Terraria: Terraria.Graphics.FinalFractalHelper.GetFinalFractalProfile
GetFinalFractalProfile()
static FinalFractalProfile Terraria.Graphics.FinalFractalHelper.GetFinalFractalProfile (int usedSwordId) inline static
    {
        if (!_fractalProfiles.TryGetValue(usedSwordId, out var value))
        {
            return _defaultProfile;
        }
        return value;
    }
References Terraria.Graphics.FinalFractalHelper._defaultProfile, and Terraria.Graphics.FinalFractalHelper._fractalProfiles.
Referenced by Terraria.Projectile.AI_182_FinalFractal(), Terraria.Graphics.FinalFractalHelper.Draw(), and Terraria.Main.DrawProjDirect().