Terraria: System.DateOnly.TryParseExactInternal
TryParseExactInternal() [1/2]
static ParseFailureKind System.DateOnly.TryParseExactInternal (ReadOnlySpan< char > s, ReadOnlySpan< char > format, IFormatProvider provider, DateTimeStyles style, out DateOnly result) inline static private
Definition at line 300 of file DateOnly.cs.
    {
        if (((uint)style & 0xFFFFFFF8u) != 0)
        {
            result = default(DateOnly);
            return ParseFailureKind.FormatWithParameter;
        }
        if (format.Length == 1)
        {
            switch (format[0])
            {
            case 'O':
            case 'o':
                format = "yyyy'-'MM'-'dd";
                provider = CultureInfo.InvariantCulture.DateTimeFormat;
                break;
            case 'R':
            case 'r':
                format = "ddd, dd MMM yyyy";
                provider = CultureInfo.InvariantCulture.DateTimeFormat;
                break;
            }
        }
        DateTimeResult result2 = default(DateTimeResult);
        result2.Init(s);
        if (!DateTimeParse.TryParseExact(s, format, DateTimeFormatInfo.GetInstance(provider), style, ref result2))
        {
            result = default(DateOnly);
            return ParseFailureKind.FormatWithOriginalDateTime;
        }
        if ((result2.flags & (ParseFlags.HaveHour | ParseFlags.HaveMinute | ParseFlags.HaveSecond | ParseFlags.HaveTime | ParseFlags.TimeZoneUsed | ParseFlags.TimeZoneUtc | ParseFlags.CaptureOffset | ParseFlags.UtcSortPattern)) != 0)
        {
            result = default(DateOnly);
            return ParseFailureKind.WrongParts;
        }
        result = new DateOnly(DayNumberFromDateTime(result2.parsedDate));
        return ParseFailureKind.None;
    }
References System.DateOnly.DateOnly(), System.DateOnly.DayNumberFromDateTime(), System.DateTimeResult.flags, System.format, System.DateTimeResult.Init(), System.Globalization.CultureInfo.InvariantCulture, System.DateTimeResult.parsedDate, System.s, and System.DateTimeParse.TryParseExact().
Referenced by System.DateOnly.ParseExact(), System.DateOnly.ParseExact(), System.DateOnly.TryParseExact(), and System.DateOnly.TryParseExact().