Terraria: System.DateOnly.TryFormat
TryFormat()
bool System.DateOnly.TryFormat (Span< char > destination, out int charsWritten, ReadOnlySpan< char > format = default(ReadOnlySpan<char>), IFormatProvider? provider = null) inline
Implements System.ISpanFormattable.
Definition at line 516 of file DateOnly.cs.
    {
        if (format.Length == 0)
        {
            format = "d";
        }
        if (format.Length == 1)
        {
            switch (format[0])
            {
            case 'O':
            case 'o':
                if (!DateTimeFormat.TryFormatDateOnlyO(Year, Month, Day, destination))
                {
                    charsWritten = 0;
                    return false;
                }
                charsWritten = 10;
                return true;
            case 'R':
            case 'r':
                if (!DateTimeFormat.TryFormatDateOnlyR(DayOfWeek, Year, Month, Day, destination))
                {
                    charsWritten = 0;
                    return false;
                }
                charsWritten = 16;
                return true;
            case 'D':
            case 'M':
            case 'Y':
            case 'd':
            case 'm':
            case 'y':
                return DateTimeFormat.TryFormat(GetEquivalentDateTime(), destination, out charsWritten, format, provider);
            default:
                charsWritten = 0;
                return false;
            }
        }
        if (!DateTimeFormat.IsValidCustomDateFormat(format, throwOnError: false))
        {
            charsWritten = 0;
            return false;
        }
        return DateTimeFormat.TryFormat(GetEquivalentDateTime(), destination, out charsWritten, format, provider);
    }
References System.DateOnly.Day, System.destination, System.format, System.DateOnly.GetEquivalentDateTime(), System.DateTimeFormat.IsValidCustomDateFormat(), System.DateOnly.Month, System.DateTimeFormat.TryFormat(), System.DateTimeFormat.TryFormatDateOnlyO(), System.DateTimeFormat.TryFormatDateOnlyR(), and System.DateOnly.Year.