Terraria: System.DateOnly.Parse
Parse() [3/7]
static DateOnly System.DateOnly.Parse (ReadOnlySpan< char > s, IFormatProvider? provider = null, DateTimeStyles style = DateTimeStyles::None) inline static
Definition at line 173 of file DateOnly.cs.
    {
        DateOnly result;
        ParseFailureKind parseFailureKind = TryParseInternal(s, provider, style, out result);
        if (parseFailureKind != 0)
        {
            ThrowOnError(parseFailureKind, s);
        }
        return result;
    }
References System.s, System.DateOnly.ThrowOnError(), and System.DateOnly.TryParseInternal().
Referenced by System.DateOnly.Parse(), System.DateOnly.Parse(), System.DateOnly.Parse(), and System.DateOnly.Parse().