Terraria: System.DateOnly.TryParseExactInternal
TryParseExactInternal() [2/2]
static ParseFailureKind System.DateOnly.TryParseExactInternal (ReadOnlySpan< char > s, string[] formats, IFormatProvider provider, DateTimeStyles style, out DateOnly result) inline static private
Definition at line 349 of file DateOnly.cs.
    {
        if (((uint)style & 0xFFFFFFF8u) != 0 || formats == null)
        {
            result = default(DateOnly);
            return ParseFailureKind.FormatWithParameter;
        }
        DateTimeFormatInfo instance = DateTimeFormatInfo.GetInstance(provider);
        for (int i = 0; i < formats.Length; i++)
        {
            DateTimeFormatInfo dtfi = instance;
            string text = formats[i];
            if (string.IsNullOrEmpty(text))
            {
                result = default(DateOnly);
                return ParseFailureKind.FormatWithFormatSpecifier;
            }
            if (text.Length == 1)
            {
                switch (text[0])
                {
                case 'O':
                case 'o':
                    text = "yyyy'-'MM'-'dd";
                    dtfi = CultureInfo.InvariantCulture.DateTimeFormat;
                    break;
                case 'R':
                case 'r':
                    text = "ddd, dd MMM yyyy";
                    dtfi = CultureInfo.InvariantCulture.DateTimeFormat;
                    break;
                }
            }
            DateTimeResult result2 = default(DateTimeResult);
            result2.Init(s);
            if (DateTimeParse.TryParseExact(s, text, dtfi, style, ref result2) && (result2.flags & (ParseFlags.HaveHour | ParseFlags.HaveMinute | ParseFlags.HaveSecond | ParseFlags.HaveTime | ParseFlags.TimeZoneUsed | ParseFlags.TimeZoneUtc | ParseFlags.CaptureOffset | ParseFlags.UtcSortPattern)) == 0)
            {
                result = new DateOnly(DayNumberFromDateTime(result2.parsedDate));
                return ParseFailureKind.None;
            }
        }
        result = default(DateOnly);
        return ParseFailureKind.FormatWithOriginalDateTime;
    }
References System.DateOnly.DateOnly(), System.DateOnly.DayNumberFromDateTime(), System.DateTimeResult.flags, System.formats, System.DateTimeResult.Init(), System.Globalization.CultureInfo.InvariantCulture, System.DateTimeResult.parsedDate, System.s, System.text, and System.DateTimeParse.TryParseExact().