Terraria: System.DateOnly.TryParseInternal
TryParseInternal()
static ParseFailureKind System.DateOnly.TryParseInternal (ReadOnlySpan< char > s, IFormatProvider provider, DateTimeStyles style, out DateOnly result) inline static private
Definition at line 267 of file DateOnly.cs.
    {
        if (((uint)style & 0xFFFFFFF8u) != 0)
        {
            result = default(DateOnly);
            return ParseFailureKind.FormatWithParameter;
        }
        DateTimeResult result2 = default(DateTimeResult);
        result2.Init(s);
        if (!DateTimeParse.TryParse(s, DateTimeFormatInfo.GetInstance(provider), style, ref result2))
        {
            result = default(DateOnly);
            return ParseFailureKind.FormatWithOriginalDateTime;
        }
        if ((result2.flags & (ParseFlags.HaveHour | ParseFlags.HaveMinute | ParseFlags.HaveSecond | ParseFlags.HaveTime | ParseFlags.TimeZoneUsed | ParseFlags.TimeZoneUtc | ParseFlags.CaptureOffset | ParseFlags.UtcSortPattern)) != 0)
        {
            result = default(DateOnly);
            return ParseFailureKind.WrongParts;
        }
        result = new DateOnly(DayNumberFromDateTime(result2.parsedDate));
        return ParseFailureKind.None;
    }
References System.DateOnly.DateOnly(), System.DateOnly.DayNumberFromDateTime(), System.DateTimeResult.flags, System.DateTimeResult.Init(), System.DateTimeResult.parsedDate, System.s, and System.DateTimeParse.TryParse().
Referenced by System.DateOnly.Parse(), and System.DateOnly.TryParse().