Terraria: System.DateOnly.GetEquivalentDateTime
GetEquivalentDateTime()
DateTime System.DateOnly.GetEquivalentDateTime () inline private
Definition at line 38 of file DateOnly.cs.
    {
        return DateTime.UnsafeCreate(_dayNumber * 864000000000L);
    }
References System.DateOnly._dayNumber, System.L, and System.DateTime.UnsafeCreate().
Referenced by System.DateOnly.AddMonths(), System.DateOnly.AddYears(), System.DateOnly.ToString(), and System.DateOnly.TryFormat().