Terraria: System.DateOnly.ToString
ToString() [4/4]
string System.DateOnly.ToString (string? format, IFormatProvider? provider) inline
Implements System.IFormattable.
Definition at line 479 of file DateOnly.cs.
    {
        if (format == null || format.Length == 0)
        {
            format = "d";
        }
        if (format.Length == 1)
        {
            switch (format[0])
            {
            case 'O':
            case 'o':
                return string.Create(10, this, delegate(Span<char> destination, DateOnly value)
                {
                    bool flag = DateTimeFormat.TryFormatDateOnlyO(value.Year, value.Month, value.Day, destination);
                });
            case 'R':
            case 'r':
                return string.Create(16, this, delegate(Span<char> destination, DateOnly value)
                {
                    bool flag2 = DateTimeFormat.TryFormatDateOnlyR(value.DayOfWeek, value.Year, value.Month, value.Day, destination);
                });
            case 'D':
            case 'M':
            case 'Y':
            case 'd':
            case 'm':
            case 'y':
                return DateTimeFormat.Format(GetEquivalentDateTime(), format, provider);
            default:
                throw new FormatException(SR.Format_InvalidString);
            }
        }
        DateTimeFormat.IsValidCustomDateFormat(format.AsSpan(), throwOnError: true);
        return DateTimeFormat.Format(GetEquivalentDateTime(), format, provider);
    }
References System.destination, System.DateTimeFormat.Format(), System.format, System.SR.Format_InvalidString, System.DateOnly.GetEquivalentDateTime(), System.DateTimeFormat.IsValidCustomDateFormat(), System.DateTimeFormat.TryFormatDateOnlyO(), System.DateTimeFormat.TryFormatDateOnlyR(), and System.value.