Terraria: System.Xml.Xsl.XsltOld.RootAction.CheckAttributeSets_RecurceInList
CheckAttributeSets_RecurceInList()
void System.Xml.Xsl.XsltOld.RootAction.CheckAttributeSets_RecurceInList (Hashtable markTable, ICollection setQNames) inline private
Definition at line 106 of file RootAction.cs.
    {
        foreach (XmlQualifiedName setQName in setQNames)
        {
            object obj = markTable[setQName];
            if (obj == "P")
            {
                throw XsltException.Create(System.SR.Xslt_CircularAttributeSet, setQName.ToString());
            }
            if (obj != "D")
            {
                markTable[setQName] = "P";
                CheckAttributeSets_RecurceInContainer(markTable, GetAttributeSet(setQName));
                markTable[setQName] = "D";
            }
        }
    }
References System.Xml.Xsl.XsltOld.RootAction.CheckAttributeSets_RecurceInContainer(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.RootAction.GetAttributeSet(), System.obj, and System.SR.Xslt_CircularAttributeSet.
Referenced by System.Xml.Xsl.XsltOld.RootAction.CheckAttributeSets_RecurceInContainer(), and System.Xml.Xsl.XsltOld.RootAction.PorcessAttributeSets().