Terraria: System.Xml.Xsl.XsltOld.RootAction.MirgeAttributeSets
MirgeAttributeSets()
void System.Xml.Xsl.XsltOld.RootAction.MirgeAttributeSets (Stylesheet stylesheet) inline private
Definition at line 73 of file RootAction.cs.
    {
        if (stylesheet.AttributeSetTable != null)
        {
            foreach (AttributeSetAction value in stylesheet.AttributeSetTable.Values)
            {
                ArrayList arrayList = value.containedActions;
                AttributeSetAction attributeSetAction2 = (AttributeSetAction)_attributeSetTable[value.Name];
                if (attributeSetAction2 == null)
                {
                    attributeSetAction2 = new AttributeSetAction();
                    attributeSetAction2.name = value.Name;
                    attributeSetAction2.containedActions = new ArrayList();
                    _attributeSetTable[value.Name] = attributeSetAction2;
                }
                ArrayList arrayList2 = attributeSetAction2.containedActions;
                if (arrayList != null)
                {
                    int num = arrayList.Count - 1;
                    while (0 <= num)
                    {
                        arrayList2.Add(arrayList[num]);
                        num--;
                    }
                }
            }
        }
        foreach (Stylesheet import in stylesheet.Imports)
        {
            MirgeAttributeSets(import);
        }
    }
References System.Xml.Xsl.XsltOld.RootAction._attributeSetTable, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.XsltOld.Stylesheet.AttributeSetTable, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.Stylesheet.Imports, System.Xml.Xsl.XsltOld.RootAction.MirgeAttributeSets(), System.value, and System.Collections.Hashtable.Values.
Referenced by System.Xml.Xsl.XsltOld.RootAction.MirgeAttributeSets(), and System.Xml.Xsl.XsltOld.RootAction.PorcessAttributeSets().