Terraria: System.Xml.Xsl.XsltOld.RootAction.PorcessAttributeSets
PorcessAttributeSets()
void System.Xml.Xsl.XsltOld.RootAction.PorcessAttributeSets (Stylesheet rootStylesheet) inline
Definition at line 60 of file RootAction.cs.
    {
        MirgeAttributeSets(rootStylesheet);
        foreach (AttributeSetAction value in _attributeSetTable.Values)
        {
            if (value.containedActions != null)
            {
                value.containedActions.Reverse();
            }
        }
        CheckAttributeSets_RecurceInList(new Hashtable(), _attributeSetTable.Keys);
    }
References System.Xml.Xsl.XsltOld.RootAction._attributeSetTable, System.Xml.Xsl.XsltOld.RootAction.CheckAttributeSets_RecurceInList(), System.Collections.Hashtable.Keys, System.Xml.Xsl.XsltOld.RootAction.MirgeAttributeSets(), System.value, and System.Collections.Hashtable.Values.
Referenced by System.Xml.Xsl.XsltOld.Compiler.Compile().