Terraria: System.Security.Cryptography.CspKeyContainerInfo.ReadDeviceParameterVerifyContext
ReadDeviceParameterVerifyContext()
object System.Security.Cryptography.CspKeyContainerInfo.ReadDeviceParameterVerifyContext (int keyParam) inline private
Definition at line 108 of file CspKeyContainerInfo.cs.
    {
        CspParameters cspParameters = new CspParameters(_parameters);
        cspParameters.Flags &= CspProviderFlags.UseMachineKeyStore;
        cspParameters.KeyContainerName = null;
        SafeProvHandle safeProvHandle;
        int num = CapiHelper.OpenCSP(cspParameters, 4026531840u, out safeProvHandle);
        using (safeProvHandle)
        {
            if (num != 0)
            {
                throw new CryptographicException(System.SR.Format(System.SR.Cryptography_CSP_NotFound, "Error"));
            }
            return CapiHelper.GetProviderParameter(safeProvHandle, cspParameters.KeyNumber, keyParam);
        }
    }
References System.Security.Cryptography.CspKeyContainerInfo._parameters, System.SR.Cryptography_CSP_NotFound, System.SR.Format(), Internal.NativeCrypto.CapiHelper.GetProviderParameter(), System.Security.Cryptography.CspParameters.KeyNumber, and Internal.NativeCrypto.CapiHelper.OpenCSP().