Terraria: System.Security.Cryptography.CspKeyContainerInfo.ReadKeyParameterSilent
ReadKeyParameterSilent()
object System.Security.Cryptography.CspKeyContainerInfo.ReadKeyParameterSilent (int keyParam, bool throwOnNotFound = true) inline private
Definition at line 90 of file CspKeyContainerInfo.cs.
    {
        SafeProvHandle safeProvHandle;
        int num = CapiHelper.OpenCSP(_parameters, 64u, out safeProvHandle);
        using (safeProvHandle)
        {
            if (num != 0)
            {
                if (throwOnNotFound)
                {
                    throw new CryptographicException(System.SR.Format(System.SR.Cryptography_CSP_NotFound, "Error"));
                }
                return null;
            }
            return CapiHelper.GetProviderParameter(safeProvHandle, _parameters.KeyNumber, keyParam);
        }
    }
References System.Security.Cryptography.CspKeyContainerInfo._parameters, System.SR.Cryptography_CSP_NotFound, System.SR.Format(), Internal.NativeCrypto.CapiHelper.GetProviderParameter(), System.Security.Cryptography.CspParameters.KeyNumber, and Internal.NativeCrypto.CapiHelper.OpenCSP().