Terraria: System.Xml.XmlDictionary.Add
Add()
virtual XmlDictionaryString System.Xml.XmlDictionary.Add (string value) inline virtual
Definition at line 64 of file XmlDictionary.cs.
    {
        if (!_lookup.TryGetValue(value, out var value2))
        {
            if (_strings == null)
            {
                _strings = new XmlDictionaryString[4];
            }
            else if (_nextId == _strings.Length)
            {
                int num = _nextId * 2;
                if (num == 0)
                {
                    num = 4;
                }
                Array.Resize(ref _strings, num);
            }
            value2 = new XmlDictionaryString(this, value, _nextId);
            _strings[_nextId] = value2;
            _lookup.Add(value, value2);
            _nextId++;
        }
        return value2;
    }
References System.Xml.XmlDictionary._lookup, System.Xml.XmlDictionary._nextId, System.Xml.XmlDictionary._strings, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.DataContractJsonSerializer(), and System.Runtime.Serialization.Json.DataContractJsonSerializer.ConvertXmlNameToJsonName().