Terraria: System.Diagnostics.SymbolStore.SymbolToken.Equals
Equals() [1/2]
override bool System.Diagnostics.SymbolStore.SymbolToken.Equals ([NotNullWhen(true)] object? obj) inline
Definition at line 24 of file SymbolToken.cs.
    {
        if (obj is SymbolToken)
        {
            return Equals((SymbolToken)obj);
        }
        return false;
    }
References System.Diagnostics.SymbolStore.SymbolToken.Equals(), and System.obj.
Referenced by System.Diagnostics.SymbolStore.SymbolToken.Equals(), and System.Diagnostics.SymbolStore.SymbolToken.operator==().