Terraria: System.IO.Compression.SubReadStream.ReadAsync
ReadAsync() [3/3]
override ValueTask< int > System.IO.Compression.SubReadStream.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 139 of file SubReadStream.cs.
    {
        ThrowIfDisposed();
        ThrowIfCantRead();
        return Core(buffer, cancellationToken);
        async ValueTask<int> Core(Memory<byte> buffer, CancellationToken cancellationToken)
        {
            if (_superStream.Position != _positionInSuperStream)
            {
                _superStream.Seek(_positionInSuperStream, SeekOrigin.Begin);
            }
            if (_positionInSuperStream > _endInSuperStream - buffer.Length)
            {
                buffer = buffer.Slice(0, (int)(_endInSuperStream - _positionInSuperStream));
            }
            int num = await _superStream.ReadAsync(buffer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            _positionInSuperStream += num;
            return num;
        }
    }
References System.IO.Compression.SubReadStream._endInSuperStream, System.IO.Compression.SubReadStream._positionInSuperStream, System.IO.Compression.SubReadStream._superStream, System.buffer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.Position, System.IO.Stream.ReadAsync(), System.IO.Stream.Seek(), System.IO.Compression.SubReadStream.ThrowIfCantRead(), and System.IO.Compression.SubReadStream.ThrowIfDisposed().