Terraria: System.Xml.QueryOutputWriterV1.EndCDataSection
EndCDataSection()
void System.Xml.QueryOutputWriterV1.EndCDataSection () inline private
Definition at line 278 of file QueryOutputWriterV1.cs.
    {
        _inCDataSection = false;
    }
References System.Xml.QueryOutputWriterV1._inCDataSection.
Referenced by System.Xml.QueryOutputWriterV1.WriteCharEntity(), System.Xml.QueryOutputWriterV1.WriteComment(), System.Xml.QueryOutputWriterV1.WriteEndElement(), System.Xml.QueryOutputWriterV1.WriteEntityRef(), System.Xml.QueryOutputWriterV1.WriteFullEndElement(), System.Xml.QueryOutputWriterV1.WriteProcessingInstruction(), System.Xml.QueryOutputWriterV1.WriteStartElement(), and System.Xml.QueryOutputWriterV1.WriteSurrogateCharEntity().