Terraria: System.Xml.QueryOutputWriterV1.WriteStartElement
WriteStartElement() [3/4]
override void System.Xml.QueryOutputWriterV1.WriteStartElement (string prefix, string localName, string ns) inline
Definition at line 97 of file QueryOutputWriterV1.cs.
    {
        EndCDataSection();
        if (_outputDocType)
        {
            WriteState writeState = _wrapped.WriteState;
            if (writeState == WriteState.Start || writeState == WriteState.Prolog)
            {
                _wrapped.WriteDocType(string.IsNullOrEmpty(prefix) ? localName : (prefix + ":" + localName), _publicId, _systemId, null);
            }
            _outputDocType = false;
        }
        _wrapped.WriteStartElement(prefix, localName, ns);
        if (_lookupCDataElems != null)
        {
            _qnameCData.Init(localName, ns);
            _bitsCData.PushBit(_lookupCDataElems.ContainsKey(_qnameCData));
        }
    }
References System.Xml.QueryOutputWriterV1._bitsCData, System.Xml.QueryOutputWriterV1._lookupCDataElems, System.Xml.QueryOutputWriterV1._outputDocType, System.Xml.QueryOutputWriterV1._publicId, System.Xml.QueryOutputWriterV1._qnameCData, System.Xml.QueryOutputWriterV1._systemId, System.Xml.QueryOutputWriterV1._wrapped, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.QueryOutputWriterV1.EndCDataSection(), System.Xml.XmlQualifiedName.Init(), System.prefix, System.Xml.BitStack.PushBit(), System.Xml.XmlWriter.WriteDocType(), System.Xml.XmlWriter.WriteStartElement(), and System.Xml.XmlWriter.WriteState.