Terraria: System.Transactions.TransactionTable.ThreadTimer
ThreadTimer()
void System.Transactions.TransactionTable.ThreadTimer (object state) inline private
Definition at line 146 of file TransactionTable.cs.
    {
        if (!_timerEnabled)
        {
            return;
        }
        _ticks++;
        _lastTimerTime = DateTime.UtcNow.Ticks;
        BucketSet bucketSet = null;
        BucketSet bucketSet2 = _headBucketSet;
        WeakReference weakReference = null;
        BucketSet bucketSet3 = null;
        weakReference = (WeakReference)bucketSet2.nextSetWeak;
        if (weakReference != null)
        {
            bucketSet3 = (BucketSet)weakReference.Target;
        }
        if (bucketSet3 == null)
        {
            _rwLock.EnterWriteLock();
            try
            {
                weakReference = (WeakReference)bucketSet2.nextSetWeak;
                if (weakReference != null)
                {
                    bucketSet3 = (BucketSet)weakReference.Target;
                }
                if (bucketSet3 == null)
                {
                    if (!_timer.Change(-1, -1))
                    {
                        throw TransactionException.CreateInvalidOperationException(TraceSourceType.TraceSourceLtm, System.SR.UnexpectedTimerFailure, null);
                    }
                    _timerEnabled = false;
                    return;
                }
            }
            finally
            {
                _rwLock.ExitWriteLock();
            }
        }
        WeakReference weakReference2;
        while (true)
        {
            weakReference = (WeakReference)bucketSet2.nextSetWeak;
            if (weakReference == null)
            {
                return;
            }
            bucketSet3 = (BucketSet)weakReference.Target;
            if (bucketSet3 == null)
            {
                return;
            }
            bucketSet = bucketSet2;
            bucketSet2 = bucketSet3;
            if (bucketSet2.AbsoluteTimeout <= _ticks)
            {
                weakReference2 = (WeakReference)Interlocked.CompareExchange(ref bucketSet.nextSetWeak, null, weakReference);
                if (weakReference2 == weakReference)
                {
                    break;
                }
                bucketSet2 = bucketSet;
            }
        }
        BucketSet bucketSet4 = null;
        do
        {
            bucketSet4 = ((weakReference2 == null) ? null : ((BucketSet)weakReference2.Target));
            if (bucketSet4 != null)
            {
                bucketSet4.TimeoutTransactions();
                weakReference2 = (WeakReference)bucketSet4.nextSetWeak;
            }
        }
        while (bucketSet4 != null);
    }
References System.Transactions.TransactionTable._headBucketSet, System.Transactions.TransactionTable._lastTimerTime, System.Transactions.TransactionTable._rwLock, System.Transactions.TransactionTable._ticks, System.Transactions.TransactionTable._timer, System.Transactions.TransactionTable._timerEnabled, System.Transactions.BucketSet.AbsoluteTimeout, System.Threading.Timer.Change(), System.Threading.Interlocked.CompareExchange(), System.Transactions.TransactionException.CreateInvalidOperationException(), System.Transactions.CheapUnfairReaderWriterLock.EnterWriteLock(), System.Transactions.CheapUnfairReaderWriterLock.ExitWriteLock(), System.Transactions.BucketSet.nextSetWeak, System.WeakReference< T >.Target, System.Transactions.BucketSet.TimeoutTransactions(), System.SR.UnexpectedTimerFailure, and System.DateTime.UtcNow.
Referenced by System.Transactions.TransactionTable.TransactionTable().