Terraria: System.Transactions.TransactionTable.Add
Add()
int System.Transactions.TransactionTable.Add (InternalTransaction txNew) inline package
Definition at line 58 of file TransactionTable.cs.
    {
        int num = 0;
        num = _rwLock.EnterReadLock();
        try
        {
            if (txNew.AbsoluteTimeout != long.MaxValue && !_timerEnabled)
            {
                if (!_timer.Change(_timerInterval, _timerInterval))
                {
                    throw TransactionException.CreateInvalidOperationException(TraceSourceType.TraceSourceLtm, System.SR.UnexpectedTimerFailure, null);
                }
                _lastTimerTime = DateTime.UtcNow.Ticks;
                _timerEnabled = true;
            }
            txNew.CreationTime = CurrentTime;
            AddIter(txNew);
            return num;
        }
        finally
        {
            _rwLock.ExitReadLock();
        }
    }
References System.Transactions.TransactionTable._lastTimerTime, System.Transactions.TransactionTable._rwLock, System.Transactions.TransactionTable._timer, System.Transactions.TransactionTable._timerEnabled, System.Transactions.TransactionTable._timerInterval, System.Transactions.InternalTransaction.AbsoluteTimeout, System.Transactions.TransactionTable.AddIter(), System.Threading.Timer.Change(), System.Transactions.TransactionException.CreateInvalidOperationException(), System.Transactions.TransactionTable.CurrentTime, System.Transactions.CheapUnfairReaderWriterLock.EnterReadLock(), System.Transactions.CheapUnfairReaderWriterLock.ExitReadLock(), System.SR.UnexpectedTimerFailure, and System.DateTime.UtcNow.