Terraria: System.Transactions.TransactionTable.AddIter
AddIter()
void System.Transactions.TransactionTable.AddIter (InternalTransaction txNew) inline private
Definition at line 83 of file TransactionTable.cs.
    {
        BucketSet bucketSet = _headBucketSet;
        while (bucketSet.AbsoluteTimeout != txNew.AbsoluteTimeout)
        {
            BucketSet bucketSet2 = null;
            do
            {
                WeakReference weakReference = (WeakReference)bucketSet.nextSetWeak;
                BucketSet bucketSet3 = null;
                if (weakReference != null)
                {
                    bucketSet3 = (BucketSet)weakReference.Target;
                }
                if (bucketSet3 == null)
                {
                    BucketSet bucketSet4 = new BucketSet(this, txNew.AbsoluteTimeout);
                    WeakReference value = new WeakReference(bucketSet4);
                    WeakReference weakReference2 = (WeakReference)Interlocked.CompareExchange(ref bucketSet.nextSetWeak, value, weakReference);
                    if (weakReference2 == weakReference)
                    {
                        bucketSet4.prevSet = bucketSet;
                    }
                }
                else
                {
                    bucketSet2 = bucketSet;
                    bucketSet = bucketSet3;
                }
            }
            while (bucketSet.AbsoluteTimeout > txNew.AbsoluteTimeout);
            if (bucketSet.AbsoluteTimeout == txNew.AbsoluteTimeout)
            {
                continue;
            }
            BucketSet bucketSet5 = new BucketSet(this, txNew.AbsoluteTimeout);
            WeakReference value2 = new WeakReference(bucketSet5);
            bucketSet5.nextSetWeak = bucketSet2.nextSetWeak;
            WeakReference weakReference3 = (WeakReference)Interlocked.CompareExchange(ref bucketSet2.nextSetWeak, value2, bucketSet5.nextSetWeak);
            if (weakReference3 == bucketSet5.nextSetWeak)
            {
                if (weakReference3 != null)
                {
                    BucketSet bucketSet6 = (BucketSet)weakReference3.Target;
                    if (bucketSet6 != null)
                    {
                        bucketSet6.prevSet = bucketSet5;
                    }
                }
                bucketSet5.prevSet = bucketSet2;
            }
            bucketSet = bucketSet2;
            bucketSet2 = null;
        }
        bucketSet.Add(txNew);
    }
References System.Transactions.TransactionTable._headBucketSet, System.Transactions.BucketSet.AbsoluteTimeout, System.Transactions.InternalTransaction.AbsoluteTimeout, System.Transactions.BucketSet.Add(), System.Threading.Interlocked.CompareExchange(), System.Transactions.BucketSet.nextSetWeak, System.WeakReference< T >.Target, and System.value.
Referenced by System.Transactions.TransactionTable.Add().