Terraria: ReLogic.Peripherals.RGB.VendorColorProfile._profiles
_profiles
readonly DeviceColorProfile [] ReLogic.Peripherals.RGB.VendorColorProfile._profiles = new DeviceColorProfile[Enum.GetValues(typeof(RgbDeviceType)).Cast<int>().Max() + 1] private
Definition at line 10 of file VendorColorProfile.cs.
Referenced by ReLogic.Peripherals.RGB.VendorColorProfile.VendorColorProfile(), ReLogic.Peripherals.RGB.VendorColorProfile.VendorColorProfile(), and ReLogic.Peripherals.RGB.VendorColorProfile.SetColorMultiplier().