Terraria: System.Net.Http.HttpContent.LimitArrayPoolWriteStream.Grow
Grow()
void System.Net.Http.HttpContent.LimitArrayPoolWriteStream.Grow (int value) inline private
Definition at line 168 of file HttpContent.cs.
        {
            byte[] buffer = _buffer;
            _buffer = null;
            uint num = (uint)(2 * buffer.Length);
            int minimumLength = ((num > Array.MaxLength) ? Math.Max(value, Array.MaxLength) : Math.Max(value, (int)num));
            byte[] array = ArrayPool<byte>.Shared.Rent(minimumLength);
            Buffer.BlockCopy(buffer, 0, array, 0, _length);
            ArrayPool<byte>.Shared.Return(buffer);
            _buffer = array;
        }
References System.Net.Http.HttpContent.LimitArrayPoolWriteStream._buffer, System.Net.Http.HttpContent.LimitArrayPoolWriteStream._length, System.array, System.Buffer.BlockCopy(), System.buffer, System.Math.Max(), System.Array.MaxLength, System.Buffers.ArrayPool< T >.Shared, and System.value.
Referenced by System.Net.Http.HttpContent.LimitArrayPoolWriteStream.EnsureCapacity().