Terraria: Terraria.ID.SoundID.Item8
Item8
readonly LegacySoundStyle Terraria.ID.SoundID.Item8 = new LegacySoundStyle(2, 8) static
Definition at line 430 of file SoundID.cs.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_184_BadTorchLuck(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Item.SetDefaults1(), Terraria.Item.SetDefaults2(), Terraria.Item.SetDefaults4(), Terraria.Item.SetDefaults5(), Terraria.Main.TeleportEffect(), Terraria.NPC.TransformVisuals(), and Terraria.Player.Update().