Terraria: System.Xml.XmlTextReaderImpl.OnDefaultNamespaceDecl
OnDefaultNamespaceDecl()
void System.Xml.XmlTextReaderImpl.OnDefaultNamespaceDecl (NodeData attr) inline private
Definition at line 4816 of file XmlTextReaderImpl.cs.
    {
        if (_supportNamespaces)
        {
            string text = _nameTable.Add(attr.StringValue);
            attr.ns = _nameTable.Add("http://www.w3.org/2000/xmlns/");
            if (!_curNode.xmlContextPushed)
            {
                PushXmlContext();
            }
            _xmlContext.defaultNamespace = text;
            AddNamespace(string.Empty, text, attr);
        }
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._supportNamespaces, System.Xml.XmlNameTable.Add(), System.Xml.XmlTextReaderImpl.AddNamespace(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.PushXmlContext(), System.text, and System.Xml.XmlTextReaderImpl.NodeData.xmlContextPushed.
Referenced by System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal(), System.Xml.XmlTextReaderImpl.ParseAttributes(), and System.Xml.XmlTextReaderImpl.ParseAttributesAsync().