Terraria: System.Xml.XmlTextReaderImpl.ParseElementContent_ReadData
ParseElementContent_ReadData()
async Task< bool > System.Xml.XmlTextReaderImpl.ParseElementContent_ReadData () inline private
Definition at line 10079 of file XmlTextReaderImpl.cs.
    {
        if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
        {
            if (_ps.charsUsed - _ps.charPos != 0)
            {
                ThrowUnclosedElements();
            }
            if (!InEntity)
            {
                if (_index == 0 && _fragmentType != XmlNodeType.Document)
                {
                    OnEof();
                    return false;
                }
                ThrowUnclosedElements();
            }
            if (HandleEntityEnd(checkEntityNesting: true))
            {
                SetupEndEntityNodeInContent();
                return true;
            }
        }
        return await ParseElementContentAsync().ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.XmlTextReaderImpl.OnEof(), System.Xml.XmlTextReaderImpl.ParseElementContentAsync(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent(), and System.Xml.XmlTextReaderImpl.ThrowUnclosedElements().
Referenced by System.Xml.XmlTextReaderImpl.ParseElementContentAsync().