Terraria: System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_WhiteSpace
ParseDocumentContentAsync_WhiteSpace()
Task< bool > System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_WhiteSpace () inline private
Definition at line 9941 of file XmlTextReaderImpl.cs.
    {
        Task<bool> task = ParseTextAsync();
        if (task.IsSuccess())
        {
            if (task.Result)
            {
                if (_fragmentType == XmlNodeType.None && _curNode.type == XmlNodeType.Text)
                {
                    _fragmentType = XmlNodeType.Element;
                }
                return AsyncHelper.DoneTaskTrue;
            }
            return ParseDocumentContentAsync();
        }
        return _ParseDocumentContentAsync_WhiteSpace(task);
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._ParseDocumentContentAsync_WhiteSpace(), System.Xml.AsyncHelper.DoneTaskTrue, System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.task, and System.Xml.XmlTextReaderImpl.NodeData.type.
Referenced by System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync().