Terraria: System.Xml.XmlTextReaderImpl.ResetState
ResetState()
void System.Xml.XmlTextReaderImpl.ResetState () inline package
Definition at line 2606 of file XmlTextReaderImpl.cs.
    {
        if (_fragment)
        {
            Throw(new InvalidOperationException(System.SR.Xml_InvalidResetStateCall));
        }
        if (_readState != 0)
        {
            ResetAttributes();
            while (_namespaceManager.PopScope())
            {
            }
            while (InEntity)
            {
                HandleEntityEnd(checkEntityNesting: true);
            }
            _readState = ReadState.Initial;
            _parsingFunction = ParsingFunction.SwitchToInteractiveXmlDecl;
            _nextParsingFunction = ParsingFunction.DocumentContent;
            _curNode = _nodes[0];
            _curNode.Clear(XmlNodeType.None);
            _curNode.SetLineInfo(0, 0);
            _index = 0;
            _rootElementParsed = false;
            _charactersInDocument = 0L;
            _charactersFromEntities = 0L;
            _afterResetState = true;
        }
    }
References System.Xml.XmlTextReaderImpl._afterResetState, System.Xml.XmlTextReaderImpl._charactersFromEntities, System.Xml.XmlTextReaderImpl._charactersInDocument, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._fragment, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._namespaceManager, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readState, System.Xml.XmlTextReaderImpl._rootElementParsed, System.Xml.XmlTextReaderImpl.NodeData.Clear(), System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.L, System.Xml.XmlNamespaceManager.PopScope(), System.Xml.XmlTextReaderImpl.ResetAttributes(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_InvalidResetStateCall.
Referenced by System.Xml.XmlTextReader.ResetState().