Terraria: System.Xml.XmlTextReaderImpl.XmlTextReaderImpl
XmlTextReaderImpl() [17/20]
System.Xml.XmlTextReaderImpl.XmlTextReaderImpl (string uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver) inline package
Definition at line 1679 of file XmlTextReaderImpl.cs.
        : this(settings.GetXmlResolver(), settings, context)
    {
        Uri uri = uriResolver.ResolveUri(null, uriStr);
        string text = uri.ToString();
        if (context != null && context.BaseURI != null && context.BaseURI.Length > 0 && !UriEqual(uri, text, context.BaseURI, settings.GetXmlResolver()))
        {
            if (text.Length > 0)
            {
                Throw(System.SR.Xml_DoubleBaseUri);
            }
            text = context.BaseURI;
        }
        _reportedBaseUri = text;
        _closeInput = true;
        _laterInitParam = new LaterInitParam();
        _laterInitParam.inputUriStr = uriStr;
        _laterInitParam.inputbaseUri = uri;
        _laterInitParam.inputContext = context;
        _laterInitParam.inputUriResolver = uriResolver;
        _laterInitParam.initType = InitInputType.UriString;
        if (!settings.Async)
        {
            FinishInitUriString();
        }
        else
        {
            _laterInitParam.useAsync = true;
        }
    }
References System.Xml.XmlTextReaderImpl._closeInput, System.Xml.XmlTextReaderImpl._laterInitParam, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlReaderSettings.Async, System.Xml.XmlParserContext.BaseURI, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.FinishInitUriString(), System.Xml.XmlReaderSettings.GetXmlResolver(), System.text, System.Xml.XmlTextReaderImpl.Throw(), System.Uri.ToString(), System.Xml.XmlTextReaderImpl.UriEqual(), and System.SR.Xml_DoubleBaseUri.