Terraria: System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync
ParseXmlDeclarationAsync()
async Task< bool > System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync (bool isTextDecl) inline private
Definition at line 9514 of file XmlTextReaderImpl.cs.
    {
        do
        {
            if (_ps.charsUsed - _ps.charPos < 6)
            {
                continue;
            }
            if (!XmlConvert.StrEqual(_ps.chars, _ps.charPos, 5, "<?xml") || XmlCharType.IsNameSingleChar(_ps.chars[_ps.charPos + 5]))
            {
                break;
            }
            if (!isTextDecl)
            {
                _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos + 2);
                _curNode.SetNamedNode(XmlNodeType.XmlDeclaration, _xml);
            }
            _ps.charPos += 5;
            StringBuilder sb = (isTextDecl ? new StringBuilder() : _stringBuilder);
            int xmlDeclState = 0;
            Encoding encoding = null;
            while (true)
            {
                int originalSbLen = sb.Length;
                int num = await EatWhitespacesAsync((xmlDeclState == 0) ? null : sb).ConfigureAwait(continueOnCapturedContext: false);
                if (_ps.chars[_ps.charPos] == '?')
                {
                    sb.Length = originalSbLen;
                    if (_ps.chars[_ps.charPos + 1] == '>')
                    {
                        break;
                    }
                    if (_ps.charPos + 1 == _ps.charsUsed)
                    {
                        goto IL_0cb2;
                    }
                    ThrowUnexpectedToken("'>'");
                }
                if (num == 0 && xmlDeclState != 0)
                {
                    ThrowUnexpectedToken("?>");
                }
                int num2 = await ParseNameAsync().ConfigureAwait(continueOnCapturedContext: false);
                NodeData attr = null;
                char c = _ps.chars[_ps.charPos];
                if (c != 'e')
                {
                    if (c != 's')
                    {
                        if (c != 'v' || !XmlConvert.StrEqual(_ps.chars, _ps.charPos, num2 - _ps.charPos, "version") || xmlDeclState != 0)
{
                            goto IL_06a6;
                        }
                        if (!isTextDecl)
{
                            attr = AddAttributeNoChecks("version", 1);
                        }
                    }
                    else
                    {
                        if (!XmlConvert.StrEqual(_ps.chars, _ps.charPos, num2 - _ps.charPos, "standalone") || (xmlDeclState != 1 && xmlDeclState != 2) || isTextDecl)
{
                            goto IL_06a6;
                        }
                        if (!isTextDecl)
{
                            attr = AddAttributeNoChecks("standalone", 1);
                        }
                        xmlDeclState = 2;
                    }
                }
                else
                {
                    if (!XmlConvert.StrEqual(_ps.chars, _ps.charPos, num2 - _ps.charPos, "encoding") || (xmlDeclState != 1 && (!isTextDecl || xmlDeclState != 0)))
                    {
                        goto IL_06a6;
                    }
                    if (!isTextDecl)
                    {
                        attr = AddAttributeNoChecks("encoding", 1);
                    }
                    xmlDeclState = 1;
                }
                goto IL_06c0;
                IL_06c0:
                if (!isTextDecl)
                {
                    attr.SetLineInfo(_ps.LineNo, _ps.LinePos);
                }
                sb.Append(_ps.chars, _ps.charPos, num2 - _ps.charPos);
                _ps.charPos = num2;
                if (_ps.chars[_ps.charPos] != '=')
                {
                    await EatWhitespacesAsync(sb).ConfigureAwait(continueOnCapturedContext: false);
                    if (_ps.chars[_ps.charPos] != '=')
                    {
                        ThrowUnexpectedToken("=");
                    }
                }
                sb.Append('=');
                _ps.charPos++;
                char quoteChar = _ps.chars[_ps.charPos];
                if (quoteChar != '"' && quoteChar != '\'')
                {
                    await EatWhitespacesAsync(sb).ConfigureAwait(continueOnCapturedContext: false);
                    quoteChar = _ps.chars[_ps.charPos];
                    if (quoteChar != '"' && quoteChar != '\'')
                    {
                        ThrowUnexpectedToken("\"", "'");
                    }
                }
                sb.Append(quoteChar);
                _ps.charPos++;
                if (!isTextDecl)
                {
                    attr.quoteChar = quoteChar;
                    attr.SetLineInfo2(_ps.LineNo, _ps.LinePos);
                }
                int pos = _ps.charPos;
                char[] chars;
                while (true)
                {
                    for (chars = _ps.chars; XmlCharType.IsAttributeValueChar(chars[pos]); pos++)
                    {
                    }
                    if (_ps.chars[pos] == quoteChar)
                    {
                        break;
                    }
                    if (pos == _ps.charsUsed)
                    {
                        if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) != 0)
{
                            continue;
                        }
                        goto IL_0c8b;
                    }
                    goto IL_0c98;
                }
                switch (xmlDeclState)
                {
                case 0:
                    if (XmlConvert.StrEqual(_ps.chars, _ps.charPos, pos - _ps.charPos, "1.0"))
                    {
                        if (!isTextDecl)
{
                            attr.SetValue(_ps.chars, _ps.charPos, pos - _ps.charPos);
                        }
                        xmlDeclState = 1;
                    }
                    else
                    {
                        string arg = new string(_ps.chars, _ps.charPos, pos - _ps.charPos);
                        Throw(System.SR.Xml_InvalidVersionNumber, arg);
                    }
                    break;
                case 1:
                {
                    string text = new string(_ps.chars, _ps.charPos, pos - _ps.charPos);
                    encoding = CheckEncoding(text);
                    if (!isTextDecl)
                    {
                        attr.SetValue(text);
                    }
                    xmlDeclState = 2;
                    break;
                }
                case 2:
                    if (XmlConvert.StrEqual(_ps.chars, _ps.charPos, pos - _ps.charPos, "yes"))
                    {
                        _standalone = true;
                    }
                    else if (XmlConvert.StrEqual(_ps.chars, _ps.charPos, pos - _ps.charPos, "no"))
                    {
                        _standalone = false;
                    }
                    else
                    {
                        Throw(System.SR.Xml_InvalidXmlDecl, _ps.LineNo, _ps.LinePos - 1);
                    }
                    if (!isTextDecl)
                    {
                        attr.SetValue(_ps.chars, _ps.charPos, pos - _ps.charPos);
                    }
                    xmlDeclState = 3;
                    break;
                }
                sb.Append(chars, _ps.charPos, pos - _ps.charPos);
                sb.Append(quoteChar);
                _ps.charPos = pos + 1;
                continue;
                IL_0cb2:
                bool isEof = _ps.isEof;
                bool flag = isEof;
                if (!flag)
                {
                    flag = await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0;
                }
                if (flag)
                {
                    Throw(System.SR.Xml_UnexpectedEOF1);
                }
                continue;
                IL_0c98:
                Throw(isTextDecl ? System.SR.Xml_InvalidTextDecl : System.SR.Xml_InvalidXmlDecl);
                goto IL_0cb2;
                IL_0c8b:
                Throw(System.SR.Xml_UnclosedQuote);
                goto IL_0cb2;
                IL_06a6:
                Throw(isTextDecl ? System.SR.Xml_InvalidTextDecl : System.SR.Xml_InvalidXmlDecl);
                goto IL_06c0;
            }
            if (xmlDeclState == 0)
            {
                Throw(isTextDecl ? System.SR.Xml_InvalidTextDecl : System.SR.Xml_InvalidXmlDecl);
            }
            _ps.charPos += 2;
            if (!isTextDecl)
            {
                _curNode.SetValue(sb.ToString());
                sb.Length = 0;
                _nextParsingFunction = _parsingFunction;
                _parsingFunction = ParsingFunction.ResetAttributesRootLevel;
            }
            if (encoding != null)
            {
                await SwitchEncodingAsync(encoding).ConfigureAwait(continueOnCapturedContext: false);
            }
            else
            {
                if (isTextDecl)
                {
                    Throw(System.SR.Xml_InvalidTextDecl);
                }
                if (_afterResetState)
                {
                    string webName = _ps.encoding.WebName;
                    if (webName != "utf-8" && webName != "utf-16" && webName != "utf-16BE" && !(_ps.encoding is Ucs4Encoding))
                    {
                        Throw(System.SR.Xml_EncodingSwitchAfterResetState, (_ps.encoding.GetByteCount("A") == 1) ? "UTF-8" : "UTF-16");
                    }
                }
                if (_ps.decoder is SafeAsciiDecoder)
                {
                    await SwitchEncodingToUTF8Async().ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            _ps.appendMode = false;
            return true;
        }
        while (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) != 0);
        if (!isTextDecl)
        {
            _parsingFunction = _nextParsingFunction;
        }
        if (_afterResetState)
        {
            string webName2 = _ps.encoding.WebName;
            if (webName2 != "utf-8" && webName2 != "utf-16" && webName2 != "utf-16BE" && !(_ps.encoding is Ucs4Encoding))
            {
                Throw(System.SR.Xml_EncodingSwitchAfterResetState, (_ps.encoding.GetByteCount("A") == 1) ? "UTF-8" : "UTF-16");
            }
        }
        if (_ps.decoder is SafeAsciiDecoder)
        {
            await SwitchEncodingToUTF8Async().ConfigureAwait(continueOnCapturedContext: false);
        }
        _ps.appendMode = false;
        return false;
    }
References System.Xml.XmlTextReaderImpl._afterResetState, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._standalone, System.Xml.XmlTextReaderImpl._stringBuilder, System.Xml.XmlTextReaderImpl._xml, System.Xml.XmlTextReaderImpl.AddAttributeNoChecks(), System.Text.StringBuilder.Append(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.XmlTextReaderImpl.CheckEncoding(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlTextReaderImpl.ParsingState.decoder, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespacesAsync(), System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Text.Encoding.GetByteCount(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlCharType.IsNameSingleChar(), System.Text.StringBuilder.Length, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseNameAsync(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode(), System.Xml.XmlTextReaderImpl.NodeData.SetValue(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.SwitchEncodingAsync(), System.Xml.XmlTextReaderImpl.SwitchEncodingToUTF8Async(), System.text, System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.Text.StringBuilder.ToString(), System.Text.Encoding.WebName, System.SR.Xml_EncodingSwitchAfterResetState, System.SR.Xml_InvalidTextDecl, System.SR.Xml_InvalidVersionNumber, System.SR.Xml_InvalidXmlDecl, System.SR.Xml_UnclosedQuote, and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_PushExternalSubsetAsync(), System.Xml.XmlTextReaderImpl.PushExternalEntityAsync(), and System.Xml.XmlTextReaderImpl.ReadAsync_SwitchToInteractiveXmlDecl().