Terraria: System.Xml.XmlTextReaderImpl.PopElementContext
PopElementContext()
void System.Xml.XmlTextReaderImpl.PopElementContext () inline private
Definition at line 7013 of file XmlTextReaderImpl.cs.
    {
        _namespaceManager.PopScope();
        if (_curNode.xmlContextPushed)
        {
            PopXmlContext();
        }
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._namespaceManager, System.Xml.XmlNamespaceManager.PopScope(), System.Xml.XmlTextReaderImpl.PopXmlContext(), and System.Xml.XmlTextReaderImpl.NodeData.xmlContextPushed.
Referenced by System.Xml.XmlTextReaderImpl.Read(), and System.Xml.XmlTextReaderImpl.ReadAsync().