Terraria: System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData
ParseDocumentContentAsync_ReadData()
async Task< bool > System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData (bool needMoreChars) inline private
Definition at line 9972 of file XmlTextReaderImpl.cs.
    {
        if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) != 0)
        {
            return await ParseDocumentContentAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        if (needMoreChars)
        {
            Throw(System.SR.Xml_InvalidRootData);
        }
        if (InEntity)
        {
            if (HandleEntityEnd(checkEntityNesting: true))
            {
                SetupEndEntityNodeInContent();
                return true;
            }
            return await ParseDocumentContentAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        if (!_rootElementParsed && _fragmentType == XmlNodeType.Document)
        {
            ThrowWithoutLineInfo(System.SR.Xml_MissingRoot);
        }
        if (_fragmentType == XmlNodeType.None)
        {
            _fragmentType = ((!_rootElementParsed) ? XmlNodeType.Element : XmlNodeType.Document);
        }
        OnEof();
        return false;
    }
References System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._rootElementParsed, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.XmlTextReaderImpl.OnEof(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), System.SR.Xml_InvalidRootData, and System.SR.Xml_MissingRoot.
Referenced by System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync().