Terraria: System.Xml.XmlTextReaderImpl.SkipPartialTextValueAsync
SkipPartialTextValueAsync()
async Task System.Xml.XmlTextReaderImpl.SkipPartialTextValueAsync () inline private
Definition at line 11457 of file XmlTextReaderImpl.cs.
    {
        int outOrChars = 0;
        _parsingFunction = _nextParsingFunction;
        (int, int, int, bool) tuple;
        do
        {
            tuple = await ParseTextAsync(outOrChars).ConfigureAwait(continueOnCapturedContext: false);
            outOrChars = tuple.Item3;
        }
        while (!tuple.Item4);
    }
References System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlTextReaderImpl.int, and System.Xml.XmlTextReaderImpl.ParseTextAsync().
Referenced by System.Xml.XmlTextReaderImpl.FinishReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.FinishReadValueChunkAsync(), System.Xml.XmlTextReaderImpl.ReadAsync(), and System.Xml.XmlTextReaderImpl.SkipAsync().