Terraria: System.Xml.XmlTextReaderImpl.InitIncrementalRead
InitIncrementalRead()
void System.Xml.XmlTextReaderImpl.InitIncrementalRead (IncrementalReadDecoder decoder) inline private
Definition at line 7319 of file XmlTextReaderImpl.cs.
    {
        ResetAttributes();
        decoder.Reset();
        _incReadDecoder = decoder;
        _incReadState = IncrementalReadState.Text;
        _incReadDepth = 1;
        _incReadLeftStartPos = _ps.charPos;
        _incReadLeftEndPos = _ps.charPos;
        _incReadLineInfo.Set(_ps.LineNo, _ps.LinePos);
        _parsingFunction = ParsingFunction.InIncrementalRead;
    }
References System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._incReadDepth, System.Xml.XmlTextReaderImpl._incReadLeftEndPos, System.Xml.XmlTextReaderImpl._incReadLeftStartPos, System.Xml.XmlTextReaderImpl._incReadLineInfo, System.Xml.XmlTextReaderImpl._incReadState, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.IncrementalReadDecoder.Reset(), System.Xml.XmlTextReaderImpl.ResetAttributes(), and System.Xml.LineInfo.Set().
Referenced by System.Xml.XmlTextReaderImpl.ReadBase64(), System.Xml.XmlTextReaderImpl.ReadBinHex(), and System.Xml.XmlTextReaderImpl.ReadChars().