Terraria: System.Xml.XmlTextReaderImpl.ParseText
ParseText() [2/2]
bool System.Xml.XmlTextReaderImpl.ParseText (out int startPos, out int endPos, ref int outOrChars) inline private
Definition at line 5233 of file XmlTextReaderImpl.cs.
    {
        char[] chars = _ps.chars;
        int charRefEndPos = _ps.charPos;
        int num = 0;
        int num2 = -1;
        int num3 = outOrChars;
        char c;
        while (true)
        {
            if (XmlCharType.IsTextChar(c = chars[charRefEndPos]))
            {
                num3 |= c;
                charRefEndPos++;
                continue;
            }
            switch (c)
            {
            case '\t':
                charRefEndPos++;
                continue;
            case '\n':
                charRefEndPos++;
                OnNewLine(charRefEndPos);
                continue;
            case '\r':
                if (chars[charRefEndPos + 1] == '\n')
                {
                    if (!_ps.eolNormalized && _parsingMode == ParsingMode.Full)
                    {
                        if (charRefEndPos - _ps.charPos > 0)
{
                            if (num == 0)
{
                                num = 1;
                                num2 = charRefEndPos;
                            }
                            else
{
                                ShiftBuffer(num2 + num, num2, charRefEndPos - num2 - num);
                                num2 = charRefEndPos - num;
                                num++;
                            }
                        }
                        else
{
                            _ps.charPos++;
                        }
                    }
                    charRefEndPos += 2;
                }
                else
                {
                    if (charRefEndPos + 1 >= _ps.charsUsed && !_ps.isEof)
                    {
                        goto IL_0350;
                    }
                    if (!_ps.eolNormalized)
                    {
                        chars[charRefEndPos] = '\n';
                    }
                    charRefEndPos++;
                }
                OnNewLine(charRefEndPos);
                continue;
            case '&':
            {
                int num5;
                if ((num5 = ParseCharRefInline(charRefEndPos, out var charCount, out var entityType)) > 0)
                {
                    if (num > 0)
                    {
                        ShiftBuffer(num2 + num, num2, charRefEndPos - num2 - num);
                    }
                    num2 = charRefEndPos - num;
                    num += num5 - charRefEndPos - charCount;
                    charRefEndPos = num5;
                    if (!XmlCharType.IsWhiteSpace(chars[num5 - charCount]) || (_v1Compat && entityType == EntityType.CharacterDec))
                    {
                        num3 |= 0xFF;
                    }
                    continue;
                }
                if (charRefEndPos > _ps.charPos)
                {
                    break;
                }
                switch (HandleEntityReference(isInAttributeValue: false, EntityExpandType.All, out charRefEndPos))
                {
                case EntityType.Unexpanded:
                    break;
                case EntityType.CharacterDec:
                    if (!_v1Compat)
                    {
                        goto case EntityType.CharacterHex;
                    }
                    num3 |= 0xFF;
                    goto IL_023f;
                case EntityType.CharacterHex:
                case EntityType.CharacterNamed:
                    if (!XmlCharType.IsWhiteSpace(_ps.chars[charRefEndPos - 1]))
                    {
                        num3 |= 0xFF;
                    }
                    goto IL_023f;
                default:
                    {
                        charRefEndPos = _ps.charPos;
                        goto IL_023f;
                    }
                    IL_023f:
                    chars = _ps.chars;
                    continue;
                }
                _nextParsingFunction = _parsingFunction;
                _parsingFunction = ParsingFunction.EntityReference;
                goto IL_040d;
            }
            case ']':
                if (_ps.charsUsed - charRefEndPos >= 3 || _ps.isEof)
                {
                    if (chars[charRefEndPos + 1] == ']' && chars[charRefEndPos + 2] == '>')
                    {
                        Throw(charRefEndPos, System.SR.Xml_CDATAEndInText);
                    }
                    num3 |= 0x5D;
                    charRefEndPos++;
                    continue;
                }
                goto IL_0350;
            default:
                if (charRefEndPos != _ps.charsUsed)
                {
                    char c2 = chars[charRefEndPos];
                    if (XmlCharType.IsHighSurrogate(c2))
                    {
                        if (charRefEndPos + 1 == _ps.charsUsed)
{
                            goto IL_0350;
                        }
                        charRefEndPos++;
                        if (XmlCharType.IsLowSurrogate(chars[charRefEndPos]))
{
                            charRefEndPos++;
                            num3 |= c2;
                            continue;
                        }
                    }
                    int num4 = charRefEndPos - _ps.charPos;
                    if (ZeroEndingStream(charRefEndPos))
                    {
                        chars = _ps.chars;
                        charRefEndPos = _ps.charPos + num4;
                        break;
                    }
                    ThrowInvalidChar(_ps.chars, _ps.charsUsed, _ps.charPos + num4);
                }
                goto IL_0350;
            case '<':
                break;
                IL_0350:
                if (charRefEndPos > _ps.charPos)
                {
                    break;
                }
                if (ReadData() == 0)
                {
                    if (_ps.charsUsed - _ps.charPos <= 0)
                    {
                        if (InEntity)
{
                            if (!HandleEntityEnd(checkEntityNesting: true))
{
                                goto IL_03f0;
                            }
                            _nextParsingFunction = _parsingFunction;
                            _parsingFunction = ParsingFunction.ReportEndEntity;
                        }
                        goto IL_040d;
                    }
                    if (_ps.chars[_ps.charPos] != '\r' && _ps.chars[_ps.charPos] != ']')
                    {
                        Throw(System.SR.Xml_UnexpectedEOF1);
                    }
                }
                goto IL_03f0;
                IL_03f0:
                charRefEndPos = _ps.charPos;
                chars = _ps.chars;
                continue;
                IL_040d:
                startPos = (endPos = charRefEndPos);
                return true;
            }
            break;
        }
        if (_parsingMode == ParsingMode.Full && num > 0)
        {
            ShiftBuffer(num2 + num, num2, charRefEndPos - num2 - num);
        }
        startPos = _ps.charPos;
        endPos = charRefEndPos - num;
        _ps.charPos = charRefEndPos;
        outOrChars = num3;
        return c == '<';
    }
References System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._v1Compat, System.charCount, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.eolNormalized, System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.XmlTextReaderImpl.HandleEntityReference(), System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Xml.XmlCharType.IsTextChar(), System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.ParseCharRefInline(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.ShiftBuffer(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), System.SR.Xml_CDATAEndInText, System.SR.Xml_UnexpectedEOF1, and System.Xml.XmlTextReaderImpl.ZeroEndingStream().