Terraria: System.Xml.XmlTextReaderImpl.InvalidCharRecovery
InvalidCharRecovery()
void System.Xml.XmlTextReaderImpl.InvalidCharRecovery (ref int bytesCount, out int charsCount) inline private
Definition at line 3586 of file XmlTextReaderImpl.cs.
    {
        int num = 0;
        int i = 0;
        try
        {
            int bytesUsed;
            for (; i < bytesCount; i += bytesUsed)
            {
                _ps.decoder.Convert(_ps.bytes, _ps.bytePos + i, 1, _ps.chars, _ps.charsUsed + num, 2, flush: false, out bytesUsed, out var charsUsed, out var _);
                num += charsUsed;
            }
        }
        catch (ArgumentException)
        {
        }
        if (num == 0)
        {
            Throw(_ps.charsUsed, System.SR.Xml_InvalidCharInThisEncoding);
        }
        charsCount = num;
        bytesCount = i;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.bytePos, System.Xml.XmlTextReaderImpl.ParsingState.bytes, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Text.Decoder.Convert(), System.Xml.XmlTextReaderImpl.ParsingState.decoder, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_InvalidCharInThisEncoding.
Referenced by System.Xml.XmlTextReaderImpl.GetChars().