Terraria: System.Xml.XmlTextReaderImpl._ParseEndElmentAsync
_ParseEndElmentAsync()
async Task System.Xml.XmlTextReaderImpl._ParseEndElmentAsync () inline private
Definition at line 10267 of file XmlTextReaderImpl.cs.
    {
        await ParseEndElmentAsync_PrepareData().ConfigureAwait(continueOnCapturedContext: false);
        await ParseEndElementAsync_CheckNameAndParse().ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlTextReaderImpl.ParseEndElementAsync_CheckNameAndParse(), and System.Xml.XmlTextReaderImpl.ParseEndElmentAsync_PrepareData().
Referenced by System.Xml.XmlTextReaderImpl.ParseEndElementAsync().