Terraria: System.Xml.XmlTextReaderImpl.ReadAttributeValue
ReadAttributeValue()
override bool System.Xml.XmlTextReaderImpl.ReadAttributeValue () inline
Definition at line 2162 of file XmlTextReaderImpl.cs.
    {
        if (_parsingFunction != ParsingFunction.InReadAttributeValue)
        {
            if (_curNode.type != XmlNodeType.Attribute)
            {
                return false;
            }
            if (_readState != ReadState.Interactive || _curAttrIndex < 0)
            {
                return false;
            }
            if (_parsingFunction == ParsingFunction.InReadValueChunk)
            {
                FinishReadValueChunk();
            }
            if (_parsingFunction == ParsingFunction.InReadContentAsBinary)
            {
                FinishReadContentAsBinary();
            }
            if (_curNode.nextAttrValueChunk == null || _entityHandling == EntityHandling.ExpandEntities)
            {
                NodeData nodeData = AddNode(_index + _attrCount + 1, _curNode.depth + 1);
                nodeData.SetValueNode(XmlNodeType.Text, _curNode.StringValue);
                nodeData.lineInfo = _curNode.lineInfo2;
                nodeData.depth = _curNode.depth + 1;
                _curNode = nodeData;
                nodeData.nextAttrValueChunk = null;
            }
            else
            {
                _curNode = _curNode.nextAttrValueChunk;
                AddNode(_index + _attrCount + 1, _index + 2);
                _nodes[_index + _attrCount + 1] = _curNode;
                _fullAttrCleanup = true;
            }
            _nextParsingFunction = _parsingFunction;
            _parsingFunction = ParsingFunction.InReadAttributeValue;
            _attributeValueBaseEntityId = _ps.entityId;
            return true;
        }
        if (_ps.entityId == _attributeValueBaseEntityId)
        {
            if (_curNode.nextAttrValueChunk != null)
            {
                _curNode = _curNode.nextAttrValueChunk;
                _nodes[_index + _attrCount + 1] = _curNode;
                return true;
            }
            return false;
        }
        return ParseAttributeValueChunk();
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._attributeValueBaseEntityId, System.Xml.XmlTextReaderImpl._curAttrIndex, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._entityHandling, System.Xml.XmlTextReaderImpl._fullAttrCleanup, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._readState, System.Xml.XmlTextReaderImpl.AddNode(), System.Xml.XmlTextReaderImpl.NodeData.depth, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.entityId, System.Xml.XmlTextReaderImpl.FinishReadContentAsBinary(), System.Xml.XmlTextReaderImpl.FinishReadValueChunk(), System.Xml.XmlTextReaderImpl.NodeData.lineInfo2, System.Xml.XmlTextReaderImpl.NodeData.nextAttrValueChunk, System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.NodeData.StringValue, and System.Xml.XmlTextReaderImpl.NodeData.type.
Referenced by System.Xml.XmlTextReaderImpl.ParseFragmentAttribute(), and System.Xml.XmlTextReader.ReadAttributeValue().