Terraria: System.Xml.XmlTextReaderImpl.ParseTextAsync_Surrogate
ParseTextAsync_Surrogate()
async Task<(int, int, int, bool)> System.Xml.XmlTextReaderImpl.ParseTextAsync_Surrogate (int outOrChars, char[] chars, int pos, int rcount, int rpos, int orChars, char c) inline private
Definition at line 11303 of file XmlTextReaderImpl.cs.
    {
        char c2 = chars[pos];
        if (XmlCharType.IsHighSurrogate(c2))
        {
            if (pos + 1 == _ps.charsUsed)
            {
                _lastParseTextState = new ParseTextState(outOrChars, chars, pos, rcount, rpos, orChars, c);
                _parseText_NextFunction = ParseTextFunction.ReadData;
                return _parseText_dummyTask.Result;
            }
            pos++;
            if (XmlCharType.IsLowSurrogate(chars[pos]))
            {
                pos++;
                orChars |= c2;
                _lastParseTextState = new ParseTextState(outOrChars, chars, pos, rcount, rpos, orChars, c);
                _parseText_NextFunction = ParseTextFunction.ParseText;
                return _parseText_dummyTask.Result;
            }
        }
        int offset = pos - _ps.charPos;
        if (await ZeroEndingStreamAsync(pos).ConfigureAwait(continueOnCapturedContext: false))
        {
            chars = _ps.chars;
            pos = _ps.charPos + offset;
            _lastParseTextState = new ParseTextState(outOrChars, chars, pos, rcount, rpos, orChars, c);
            _parseText_NextFunction = ParseTextFunction.PartialValue;
            return _parseText_dummyTask.Result;
        }
        ThrowInvalidChar(_ps.chars, _ps.charsUsed, _ps.charPos + offset);
        throw new XmlException(System.SR.Xml_InternalError);
    }
References System.Xml.XmlTextReaderImpl._lastParseTextState, System.Xml.XmlTextReaderImpl._parseText_dummyTask, System.Xml.XmlTextReaderImpl._parseText_NextFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.offset, System.Threading.Tasks.Task< TResult >.Result, System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), System.SR.Xml_InternalError, System.Xml.XmlException, and System.Xml.XmlTextReaderImpl.ZeroEndingStreamAsync().
Referenced by System.Xml.XmlTextReaderImpl.ParseTextAsync(), and System.Xml.XmlTextReaderImpl.ParseTextAsync_AsyncFunc().