Terraria: System.Xml.XmlTextReaderImpl.SwitchEncodingAsync
SwitchEncodingAsync()
Task System.Xml.XmlTextReaderImpl.SwitchEncodingAsync (Encoding newEncoding) inline private
Definition at line 9384 of file XmlTextReaderImpl.cs.
    {
        if ((newEncoding.WebName != _ps.encoding.WebName || _ps.decoder is SafeAsciiDecoder) && !_afterResetState)
        {
            UnDecodeChars();
            _ps.appendMode = false;
            SetupEncoding(newEncoding);
            return ReadDataAsync();
        }
        return Task.CompletedTask;
    }
References System.Xml.XmlTextReaderImpl._afterResetState, System.Xml.XmlTextReaderImpl._ps, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.XmlTextReaderImpl.ParsingState.decoder, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.SetupEncoding(), System.Xml.XmlTextReaderImpl.UnDecodeChars(), and System.Text.Encoding.WebName.
Referenced by System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), and System.Xml.XmlTextReaderImpl.SwitchEncodingToUTF8Async().