Terraria: System.Xml.XmlTextReaderImpl.ReadAsync_SwitchToInteractiveXmlDecl_Helper
ReadAsync_SwitchToInteractiveXmlDecl_Helper()
Task< bool > System.Xml.XmlTextReaderImpl.ReadAsync_SwitchToInteractiveXmlDecl_Helper (bool finish) inline private
Definition at line 8784 of file XmlTextReaderImpl.cs.
    {
        if (finish)
        {
            _reportedEncoding = _ps.encoding;
            return AsyncHelper.DoneTaskTrue;
        }
        _reportedEncoding = _ps.encoding;
        return ReadAsync();
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.AsyncHelper.DoneTaskTrue, System.Xml.XmlTextReaderImpl.ParsingState.encoding, and System.Xml.XmlTextReaderImpl.ReadAsync().
Referenced by System.Xml.XmlTextReaderImpl._ReadAsync_SwitchToInteractiveXmlDecl(), and System.Xml.XmlTextReaderImpl.ReadAsync_SwitchToInteractiveXmlDecl().