Terraria: System.Xml.XmlTextReaderImpl.ResetAttributes
ResetAttributes()
void System.Xml.XmlTextReaderImpl.ResetAttributes () inline private
Definition at line 7080 of file XmlTextReaderImpl.cs.
    {
        if (_fullAttrCleanup)
        {
            FullAttributeCleanup();
        }
        _curAttrIndex = -1;
        _attrCount = 0;
        _attrHashtable = 0;
        _attrDuplWalkCount = 0;
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._attrDuplWalkCount, System.Xml.XmlTextReaderImpl._attrHashtable, System.Xml.XmlTextReaderImpl._curAttrIndex, System.Xml.XmlTextReaderImpl._fullAttrCleanup, and System.Xml.XmlTextReaderImpl.FullAttributeCleanup().
Referenced by System.Xml.XmlTextReaderImpl.Close(), System.Xml.XmlTextReaderImpl.InitIncrementalRead(), System.Xml.XmlTextReaderImpl.Read(), System.Xml.XmlTextReaderImpl.ReadAsync(), and System.Xml.XmlTextReaderImpl.ResetState().