Terraria: System.Xml.XmlTextReaderImpl.PushParsingState
PushParsingState()
void System.Xml.XmlTextReaderImpl.PushParsingState () inline private
Definition at line 7296 of file XmlTextReaderImpl.cs.
    {
        if (_parsingStatesStack == null)
        {
            _parsingStatesStack = new ParsingState[2];
        }
        else if (_parsingStatesStackTop + 1 == _parsingStatesStack.Length)
        {
            ParsingState[] array = new ParsingState[_parsingStatesStack.Length * 2];
            Array.Copy(_parsingStatesStack, array, _parsingStatesStack.Length);
            _parsingStatesStack = array;
        }
        _parsingStatesStackTop++;
        _parsingStatesStack[_parsingStatesStackTop] = _ps;
        _ps.Clear();
    }
References System.Xml.XmlTextReaderImpl._parsingStatesStack, System.Xml.XmlTextReaderImpl._parsingStatesStackTop, System.Xml.XmlTextReaderImpl._ps, System.array, System.Xml.XmlTextReaderImpl.ParsingState.Clear(), System.Array.Copy(), and System.Xml.Dictionary.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_PushInternalDtd(), System.Xml.XmlTextReaderImpl.OpenAndPush(), System.Xml.XmlTextReaderImpl.OpenAndPushAsync(), System.Xml.XmlTextReaderImpl.PushExternalEntity(), System.Xml.XmlTextReaderImpl.PushExternalEntityAsync(), and System.Xml.XmlTextReaderImpl.PushInternalEntity().