Terraria: System.Xml.XmlTextReaderImpl.GetRemainder
GetRemainder()
TextReader System.Xml.XmlTextReaderImpl.GetRemainder () inline package
Definition at line 2636 of file XmlTextReaderImpl.cs.
    {
        switch (_parsingFunction)
        {
        case ParsingFunction.Eof:
        case ParsingFunction.ReaderClosed:
            return new StringReader(string.Empty);
        case ParsingFunction.OpenUrl:
            OpenUrl();
            break;
        case ParsingFunction.InIncrementalRead:
            if (!InEntity)
            {
                _stringBuilder.Append(_ps.chars, _incReadLeftStartPos, _incReadLeftEndPos - _incReadLeftStartPos);
            }
            break;
        }
        while (InEntity)
        {
            HandleEntityEnd(checkEntityNesting: true);
        }
        _ps.appendMode = false;
        do
        {
            _stringBuilder.Append(_ps.chars, _ps.charPos, _ps.charsUsed - _ps.charPos);
            _ps.charPos = _ps.charsUsed;
        }
        while (ReadData() != 0);
        OnEof();
        string s = _stringBuilder.ToString();
        _stringBuilder.Length = 0;
        return new StringReader(s);
    }
References System.Xml.XmlTextReaderImpl._incReadLeftEndPos, System.Xml.XmlTextReaderImpl._incReadLeftStartPos, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Text.StringBuilder.Append(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.XmlTextReaderImpl.OnEof(), System.Xml.XmlTextReaderImpl.OpenUrl(), System.Xml.XmlTextReaderImpl.ReadData(), System.s, and System.Text.StringBuilder.ToString().
Referenced by System.Xml.XmlTextReader.GetRemainder().