Terraria: System.Xml.XmlTextReaderImpl.MoveToAttribute
MoveToAttribute() [2/4]
override bool System.Xml.XmlTextReaderImpl.MoveToAttribute (string localName, string namespaceURI) inline
Definition at line 1885 of file XmlTextReaderImpl.cs.
    {
        string strB = ((namespaceURI == null) ? string.Empty : _nameTable.Get(namespaceURI));
        string strB2 = _nameTable.Get(localName);
        for (int i = _index + 1; i < _index + _attrCount + 1; i++)
        {
            if (Ref.Equal(_nodes[i].localName, strB2) && Ref.Equal(_nodes[i].ns, strB))
            {
                _curAttrIndex = i - _index - 1;
                _curNode = _nodes[i];
                if (InAttributeValueIterator)
                {
                    FinishAttributeValueIterator();
                }
                return true;
            }
        }
        return false;
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._curAttrIndex, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._nodes, System.Xml.Ref.Equal(), System.Xml.XmlTextReaderImpl.FinishAttributeValueIterator(), System.Xml.XmlNameTable.Get(), and System.Xml.XmlTextReaderImpl.NodeData.localName.