Terraria: System.Xml.XmlTextReaderImpl.MoveToAttribute
MoveToAttribute() [3/4]
override bool System.Xml.XmlTextReaderImpl.MoveToAttribute (string name) inline
Definition at line 1869 of file XmlTextReaderImpl.cs.
    {
        int num = (name.Contains(':') ? GetIndexOfAttributeWithPrefix(name) : GetIndexOfAttributeWithoutPrefix(name));
        if (num >= 0)
        {
            if (InAttributeValueIterator)
            {
                FinishAttributeValueIterator();
            }
            _curAttrIndex = num - _index - 1;
            _curNode = _nodes[num];
            return true;
        }
        return false;
    }
References System.Xml.XmlTextReaderImpl._curAttrIndex, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl.FinishAttributeValueIterator(), System.Xml.XmlTextReaderImpl.GetIndexOfAttributeWithoutPrefix(), and System.Xml.XmlTextReaderImpl.GetIndexOfAttributeWithPrefix().
Referenced by System.Xml.XmlTextReader.MoveToAttribute(), System.Xml.XmlTextReader.MoveToAttribute(), and System.Xml.XmlTextReader.MoveToAttribute().