Terraria: System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk
ParseAttributeValueChunk()
bool System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk () inline private
Definition at line 7719 of file XmlTextReaderImpl.cs.
    {
        char[] chars = _ps.chars;
        int charRefEndPos = _ps.charPos;
        _curNode = AddNode(_index + _attrCount + 1, _index + 2);
        _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
        if (_emptyEntityInAttributeResolved)
        {
            _curNode.SetValueNode(XmlNodeType.Text, string.Empty);
            _emptyEntityInAttributeResolved = false;
            return true;
        }
        while (true)
        {
            if (XmlCharType.IsAttributeValueChar(chars[charRefEndPos]))
            {
                charRefEndPos++;
                continue;
            }
            switch (chars[charRefEndPos])
            {
            case '\r':
                charRefEndPos++;
                continue;
            case '\t':
            case '\n':
                if (_normalize)
                {
                    chars[charRefEndPos] = ' ';
                }
                charRefEndPos++;
                continue;
            case '"':
            case '\'':
            case '>':
                charRefEndPos++;
                continue;
            case '<':
                Throw(charRefEndPos, System.SR.Xml_BadAttributeChar, XmlException.BuildCharExceptionArgs('<', '\0'));
                goto IL_025f;
            case '&':
            {
                if (charRefEndPos - _ps.charPos > 0)
                {
                    _stringBuilder.Append(chars, _ps.charPos, charRefEndPos - _ps.charPos);
                }
                _ps.charPos = charRefEndPos;
                EntityType entityType = HandleEntityReference(isInAttributeValue: true, EntityExpandType.OnlyCharacter, out charRefEndPos);
                if ((uint)entityType > 2u)
                {
                    if (entityType == EntityType.Unexpanded)
                    {
                        if (_stringBuilder.Length == 0)
{
                            _curNode.lineInfo.linePos++;
                            _ps.charPos++;
                            _curNode.SetNamedNode(XmlNodeType.EntityReference, ParseEntityName());
                            return true;
                        }
                        break;
                    }
                }
                else
                {
                    chars = _ps.chars;
                    if (_normalize && XmlCharType.IsWhiteSpace(chars[_ps.charPos]) && charRefEndPos - _ps.charPos == 1)
                    {
                        chars[_ps.charPos] = ' ';
                    }
                }
                chars = _ps.chars;
                continue;
            }
            default:
                {
                    if (charRefEndPos != _ps.charsUsed)
                    {
                        char ch = chars[charRefEndPos];
                        if (XmlCharType.IsHighSurrogate(ch))
{
                            if (charRefEndPos + 1 == _ps.charsUsed)
{
                                goto IL_025f;
                            }
                            charRefEndPos++;
                            if (XmlCharType.IsLowSurrogate(chars[charRefEndPos]))
{
                                charRefEndPos++;
                                continue;
                            }
                        }
                        ThrowInvalidChar(chars, _ps.charsUsed, charRefEndPos);
                    }
                    goto IL_025f;
                }
                IL_025f:
                if (charRefEndPos - _ps.charPos > 0)
                {
                    _stringBuilder.Append(chars, _ps.charPos, charRefEndPos - _ps.charPos);
                    _ps.charPos = charRefEndPos;
                }
                if (ReadData() == 0)
                {
                    if (_stringBuilder.Length > 0)
                    {
                        break;
                    }
                    if (HandleEntityEnd(checkEntityNesting: false))
                    {
                        SetupEndEntityNodeInAttribute();
                        return true;
                    }
                }
                charRefEndPos = _ps.charPos;
                chars = _ps.chars;
                continue;
            }
            break;
        }
        if (charRefEndPos - _ps.charPos > 0)
        {
            _stringBuilder.Append(chars, _ps.charPos, charRefEndPos - _ps.charPos);
            _ps.charPos = charRefEndPos;
        }
        _curNode.SetValueNode(XmlNodeType.Text, _stringBuilder.ToString());
        _stringBuilder.Length = 0;
        return true;
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._emptyEntityInAttributeResolved, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._normalize, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Xml.XmlTextReaderImpl.AddNode(), System.Text.StringBuilder.Append(), System.Xml.XmlException.BuildCharExceptionArgs(), System.ch, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.XmlTextReaderImpl.HandleEntityReference(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Xml.XmlCharType.IsWhiteSpace(), System.Text.StringBuilder.Length, System.Xml.XmlTextReaderImpl.NodeData.lineInfo, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.LineInfo.linePos, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseEntityName(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode(), System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInAttribute(), System.Xml.XmlTextReaderImpl.NodeData.SetValueNode(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), System.Text.StringBuilder.ToString(), and System.SR.Xml_BadAttributeChar.
Referenced by System.Xml.XmlTextReaderImpl.ReadAttributeValue().