Terraria: System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespaceAsync
ParseRootLevelWhitespaceAsync()
async Task< bool > System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespaceAsync () inline private
Definition at line 11512 of file XmlTextReaderImpl.cs.
    {
        XmlNodeType nodeType = GetWhitespaceType();
        if (nodeType == XmlNodeType.None)
        {
            await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false);
            bool flag = _ps.chars[_ps.charPos] == '<' || _ps.charsUsed - _ps.charPos == 0;
            bool flag2 = flag;
            if (!flag2)
            {
                flag2 = await ZeroEndingStreamAsync(_ps.charPos).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (flag2)
            {
                return false;
            }
        }
        else
        {
            _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
            await EatWhitespacesAsync(_stringBuilder).ConfigureAwait(continueOnCapturedContext: false);
            bool flag3 = _ps.chars[_ps.charPos] == '<' || _ps.charsUsed - _ps.charPos == 0;
            bool flag4 = flag3;
            if (!flag4)
            {
                flag4 = await ZeroEndingStreamAsync(_ps.charPos).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (flag4)
            {
                if (_stringBuilder.Length > 0)
                {
                    _curNode.SetValueNode(nodeType, _stringBuilder.ToString());
                    _stringBuilder.Length = 0;
                    return true;
                }
                return false;
            }
        }
        if (XmlCharType.IsCharData(_ps.chars[_ps.charPos]))
        {
            Throw(System.SR.Xml_InvalidRootData);
        }
        else
        {
            ThrowInvalidChar(_ps.chars, _ps.charsUsed, _ps.charPos);
        }
        return false;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespacesAsync(), System.Xml.XmlTextReaderImpl.GetWhitespaceType(), System.Xml.XmlCharType.IsCharData(), System.Text.StringBuilder.Length, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.SetValueNode(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), System.Text.StringBuilder.ToString(), System.SR.Xml_InvalidRootData, and System.Xml.XmlTextReaderImpl.ZeroEndingStreamAsync().
Referenced by System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync().