Terraria: System.Xml.XmlTextReaderImpl.ParseElementAsync_ReadData
ParseElementAsync_ReadData()
async Task System.Xml.XmlTextReaderImpl.ParseElementAsync_ReadData (int pos) inline private
Definition at line 10246 of file XmlTextReaderImpl.cs.
    {
        if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
        {
            Throw(pos, System.SR.Xml_UnexpectedEOF, ">");
        }
        await ParseElementAsync_NoAttributes().ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlTextReaderImpl.ParseElementAsync_NoAttributes(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_UnexpectedEOF.
Referenced by System.Xml.XmlTextReaderImpl.ParseElementAsync_NoAttributes().