Terraria: System.Xml.XmlTextReaderImpl.SkipDtdAsync
SkipDtdAsync()
async Task System.Xml.XmlTextReaderImpl.SkipDtdAsync () inline private
Definition at line 12191 of file XmlTextReaderImpl.cs.
    {
        (int, int) tuple = await ParseQNameAsync().ConfigureAwait(continueOnCapturedContext: false);
        _ = tuple.Item1;
        int item = tuple.Item2;
        _ps.charPos = item;
        await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false);
        if (_ps.chars[_ps.charPos] == 'P')
        {
            while (_ps.charsUsed - _ps.charPos < 6)
            {
                if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
                {
                    Throw(System.SR.Xml_UnexpectedEOF1);
                }
            }
            if (!XmlConvert.StrEqual(_ps.chars, _ps.charPos, 6, "PUBLIC"))
            {
                ThrowUnexpectedToken("PUBLIC");
            }
            _ps.charPos += 6;
            if (await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false) == 0)
            {
                ThrowExpectingWhitespace(_ps.charPos);
            }
            await SkipPublicOrSystemIdLiteralAsync().ConfigureAwait(continueOnCapturedContext: false);
            if (await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false) == 0)
            {
                ThrowExpectingWhitespace(_ps.charPos);
            }
            await SkipPublicOrSystemIdLiteralAsync().ConfigureAwait(continueOnCapturedContext: false);
            await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false);
        }
        else if (_ps.chars[_ps.charPos] == 'S')
        {
            while (_ps.charsUsed - _ps.charPos < 6)
            {
                if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
                {
                    Throw(System.SR.Xml_UnexpectedEOF1);
                }
            }
            if (!XmlConvert.StrEqual(_ps.chars, _ps.charPos, 6, "SYSTEM"))
            {
                ThrowUnexpectedToken("SYSTEM");
            }
            _ps.charPos += 6;
            if (await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false) == 0)
            {
                ThrowExpectingWhitespace(_ps.charPos);
            }
            await SkipPublicOrSystemIdLiteralAsync().ConfigureAwait(continueOnCapturedContext: false);
            await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false);
        }
        else if (_ps.chars[_ps.charPos] != '[' && _ps.chars[_ps.charPos] != '>')
        {
            Throw(System.SR.Xml_ExpectExternalOrClose);
        }
        if (_ps.chars[_ps.charPos] == '[')
        {
            _ps.charPos++;
            await SkipUntilAsync(']', recognizeLiterals: true).ConfigureAwait(continueOnCapturedContext: false);
            await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false);
            if (_ps.chars[_ps.charPos] != '>')
            {
                ThrowUnexpectedToken(">");
            }
        }
        else if (_ps.chars[_ps.charPos] == '>')
        {
            _curNode.SetValue(string.Empty);
        }
        else
        {
            Throw(System.SR.Xml_ExpectSubOrClose);
        }
        _ps.charPos++;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespacesAsync(), System.Xml.XmlTextReaderImpl.int, System.item, System.Xml.XmlTextReaderImpl.ParseQNameAsync(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.NodeData.SetValue(), System.Xml.XmlTextReaderImpl.SkipPublicOrSystemIdLiteralAsync(), System.Xml.XmlTextReaderImpl.SkipUntilAsync(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowExpectingWhitespace(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.SR.Xml_ExpectExternalOrClose, System.SR.Xml_ExpectSubOrClose, and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.ParseDoctypeDeclAsync().