Terraria: System.Xml.XmlTextReaderImpl.ReadContentAsBinary
ReadContentAsBinary()
int System.Xml.XmlTextReaderImpl.ReadContentAsBinary (byte[] buffer, int index, int count) inline private
Definition at line 8240 of file XmlTextReaderImpl.cs.
    {
        if (_incReadState == IncrementalReadState.ReadContentAsBinary_End)
        {
            return 0;
        }
        _incReadDecoder.SetNextOutputBuffer(buffer, index, count);
        ParsingFunction parsingFunction;
        while (true)
        {
            int num = 0;
            try
            {
                num = _curNode.CopyToBinary(_incReadDecoder, _readValueOffset);
            }
            catch (XmlException e)
            {
                _curNode.AdjustLineInfo(_readValueOffset, _ps.eolNormalized, ref _incReadLineInfo);
                ReThrow(e, _incReadLineInfo.lineNo, _incReadLineInfo.linePos);
            }
            _readValueOffset += num;
            if (_incReadDecoder.IsFull)
            {
                return _incReadDecoder.DecodedCount;
            }
            if (_incReadState == IncrementalReadState.ReadContentAsBinary_OnPartialValue)
            {
                _curNode.SetValue(string.Empty);
                bool flag = false;
                int startPos = 0;
                int endPos = 0;
                while (!_incReadDecoder.IsFull && !flag)
                {
                    int outOrChars = 0;
                    _incReadLineInfo.Set(_ps.LineNo, _ps.LinePos);
                    flag = ParseText(out startPos, out endPos, ref outOrChars);
                    try
                    {
                        num = _incReadDecoder.Decode(_ps.chars, startPos, endPos - startPos);
                    }
                    catch (XmlException e2)
                    {
                        ReThrow(e2, _incReadLineInfo.lineNo, _incReadLineInfo.linePos);
                    }
                    startPos += num;
                }
                _incReadState = (flag ? IncrementalReadState.ReadContentAsBinary_OnCachedValue : IncrementalReadState.ReadContentAsBinary_OnPartialValue);
                _readValueOffset = 0;
                if (_incReadDecoder.IsFull)
                {
                    _curNode.SetValue(_ps.chars, startPos, endPos - startPos);
                    AdjustLineInfo(_ps.chars, startPos - num, startPos, _ps.eolNormalized, ref _incReadLineInfo);
                    _curNode.SetLineInfo(_incReadLineInfo.lineNo, _incReadLineInfo.linePos);
                    return _incReadDecoder.DecodedCount;
                }
            }
            parsingFunction = _parsingFunction;
            _parsingFunction = _nextParsingFunction;
            _nextParsingFunction = _nextNextParsingFunction;
            if (!MoveToNextContentNode(moveIfOnContentNode: true))
            {
                break;
            }
            SetupReadContentAsBinaryState(parsingFunction);
            _incReadLineInfo.Set(_curNode.LineNo, _curNode.LinePos);
        }
        SetupReadContentAsBinaryState(parsingFunction);
        _incReadState = IncrementalReadState.ReadContentAsBinary_End;
        return _incReadDecoder.DecodedCount;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._incReadLineInfo, System.Xml.XmlTextReaderImpl._incReadState, System.Xml.XmlTextReaderImpl._nextNextParsingFunction, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._readValueOffset, System.Xml.XmlTextReaderImpl.AdjustLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.AdjustLineInfo(), System.buffer, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.NodeData.CopyToBinary(), System.count, System.Xml.IncrementalReadDecoder.Decode(), System.Xml.IncrementalReadDecoder.DecodedCount, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.eolNormalized, System.index, System.Xml.IncrementalReadDecoder.IsFull, System.Xml.LineInfo.lineNo, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.NodeData.LineNo, System.Xml.LineInfo.linePos, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.NodeData.LinePos, System.Xml.XmlTextReaderImpl.MoveToNextContentNode(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ReThrow(), System.Xml.LineInfo.Set(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.IncrementalReadDecoder.SetNextOutputBuffer(), System.Xml.XmlTextReaderImpl.SetupReadContentAsBinaryState(), and System.Xml.XmlTextReaderImpl.NodeData.SetValue().
Referenced by System.Xml.XmlTextReaderImpl.ReadContentAsBase64(), System.Xml.XmlTextReaderImpl.ReadContentAsBinHex(), and System.Xml.XmlTextReaderImpl.ReadElementContentAsBinary().