Terraria: System.Xml.XmlTextReaderImpl.InitStreamInput
InitStreamInput() [4/5]
void System.Xml.XmlTextReaderImpl.InitStreamInput (Uri baseUri, string baseUriStr, Stream stream, byte[] bytes, int byteCount, Encoding encoding) inline private
Definition at line 3089 of file XmlTextReaderImpl.cs.
    {
        _ps.stream = stream;
        _ps.baseUri = baseUri;
        _ps.baseUriStr = baseUriStr;
        int num;
        if (bytes != null)
        {
            _ps.bytes = bytes;
            _ps.bytesUsed = byteCount;
            num = _ps.bytes.Length;
        }
        else
        {
            num = ((_laterInitParam == null || !_laterInitParam.useAsync) ? XmlReader.CalcBufferSize(stream) : 65536);
            if (_ps.bytes == null || _ps.bytes.Length < num)
            {
                _ps.bytes = new byte[num];
            }
        }
        if (_ps.chars == null || _ps.chars.Length < num + 1)
        {
            _ps.chars = new char[num + 1];
        }
        _ps.bytePos = 0;
        while (_ps.bytesUsed < 4 && _ps.bytes.Length - _ps.bytesUsed > 0)
        {
            int num2 = stream.Read(_ps.bytes, _ps.bytesUsed, _ps.bytes.Length - _ps.bytesUsed);
            if (num2 == 0)
            {
                _ps.isStreamEof = true;
                break;
            }
            _ps.bytesUsed += num2;
        }
        if (encoding == null)
        {
            encoding = DetectEncoding();
        }
        SetupEncoding(encoding);
        EatPreamble();
        _documentStartBytePos = _ps.bytePos;
        _ps.eolNormalized = !_normalize;
        _ps.appendMode = true;
        ReadData();
    }
References System.Xml.XmlTextReaderImpl._documentStartBytePos, System.Xml.XmlTextReaderImpl._laterInitParam, System.Xml.XmlTextReaderImpl._normalize, System.Xml.XmlTextReaderImpl._ps, System.byteCount, System.Xml.XmlTextReaderImpl.ParsingState.bytePos, System.bytes, System.Xml.XmlTextReaderImpl.ParsingState.bytes, System.Xml.XmlTextReaderImpl.ParsingState.bytesUsed, System.Xml.XmlReader.CalcBufferSize(), System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.DetectEncoding(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatPreamble(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.SetupEncoding(), System.stream, and System.Xml.XmlTextReaderImpl.LaterInitParam.useAsync.