Terraria: System.Xml.XmlTextReaderImpl.FinishAttributeValueIterator
FinishAttributeValueIterator()
void System.Xml.XmlTextReaderImpl.FinishAttributeValueIterator () inline private
Definition at line 3047 of file XmlTextReaderImpl.cs.
    {
        if (_parsingFunction == ParsingFunction.InReadValueChunk)
        {
            FinishReadValueChunk();
        }
        else if (_parsingFunction == ParsingFunction.InReadContentAsBinary)
        {
            FinishReadContentAsBinary();
        }
        if (_parsingFunction == ParsingFunction.InReadAttributeValue)
        {
            while (_ps.entityId != _attributeValueBaseEntityId)
            {
                HandleEntityEnd(checkEntityNesting: false);
            }
            _emptyEntityInAttributeResolved = false;
            _parsingFunction = _nextParsingFunction;
            _nextParsingFunction = ((_index <= 0) ? ParsingFunction.DocumentContent : ParsingFunction.ElementContent);
        }
    }
References System.Xml.XmlTextReaderImpl._attributeValueBaseEntityId, System.Xml.XmlTextReaderImpl._emptyEntityInAttributeResolved, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.entityId, System.Xml.XmlTextReaderImpl.FinishReadContentAsBinary(), System.Xml.XmlTextReaderImpl.FinishReadValueChunk(), and System.Xml.XmlTextReaderImpl.HandleEntityEnd().
Referenced by System.Xml.XmlTextReaderImpl.MoveToAttribute(), System.Xml.XmlTextReaderImpl.MoveToAttribute(), System.Xml.XmlTextReaderImpl.MoveToAttribute(), System.Xml.XmlTextReaderImpl.MoveToElement(), System.Xml.XmlTextReaderImpl.MoveToFirstAttribute(), System.Xml.XmlTextReaderImpl.MoveToNextAttribute(), System.Xml.XmlTextReaderImpl.Read(), System.Xml.XmlTextReaderImpl.ReadAsync(), System.Xml.XmlTextReaderImpl.Skip(), and System.Xml.XmlTextReaderImpl.SkipAsync().