Terraria: System.Xml.XmlTextReaderImpl.ParseTextAsync
ParseTextAsync() [1/3]
Task< bool > System.Xml.XmlTextReaderImpl.ParseTextAsync () inline private
Definition at line 10909 of file XmlTextReaderImpl.cs.
    {
        int outOrChars = 0;
        if (_parsingMode != 0)
        {
            return _ParseTextAsync(null);
        }
        _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
        ValueTask<(int, int, int, bool)> valueTask = ParseTextAsync(outOrChars).Preserve();
        bool flag = false;
        if (!valueTask.IsCompletedSuccessfully)
        {
            return _ParseTextAsync(valueTask.AsTask());
        }
        (int, int, int, bool) result = valueTask.Result;
        int num;
        int num2;
        (num, num2, outOrChars, _) = result;
        if (result.Item4)
        {
            if (num2 - num == 0)
            {
                return ParseTextAsync_IgnoreNode();
            }
            XmlNodeType textNodeType = GetTextNodeType(outOrChars);
            if (textNodeType == XmlNodeType.None)
            {
                return ParseTextAsync_IgnoreNode();
            }
            _curNode.SetValueNode(textNodeType, _ps.chars, num, num2 - num);
            return AsyncHelper.DoneTaskTrue;
        }
        return _ParseTextAsync(valueTask.AsTask());
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._ParseTextAsync(), System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.Dictionary, System.Xml.AsyncHelper.DoneTaskTrue, System.Xml.XmlTextReaderImpl.GetTextNodeType(), System.Xml.XmlTextReaderImpl.int, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync_IgnoreNode(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), and System.Xml.XmlTextReaderImpl.NodeData.SetValueNode().
Referenced by System.Xml.XmlTextReaderImpl._ParseTextAsync(), System.Xml.XmlTextReaderImpl.FinishPartialValueAsync(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ParseEntity(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_WhiteSpace(), System.Xml.XmlTextReaderImpl.ParseElementContentAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync_AsyncFunc(), System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.ReadValueChunkAsync(), and System.Xml.XmlTextReaderImpl.SkipPartialTextValueAsync().