Terraria: System.Xml.XmlTextReaderImpl.ThrowTagMismatchAsync
ThrowTagMismatchAsync()
async Task System.Xml.XmlTextReaderImpl.ThrowTagMismatchAsync (NodeData startTag) inline private
Definition at line 10427 of file XmlTextReaderImpl.cs.
    {
        if (startTag.type == XmlNodeType.Element)
        {
            (int, int) tuple = await ParseQNameAsync().ConfigureAwait(continueOnCapturedContext: false);
            _ = tuple.Item1;
            int item = tuple.Item2;
            Throw(args: new string[4]
            {
                startTag.GetNameWPrefix(_nameTable),
                startTag.lineInfo.lineNo.ToString(CultureInfo.InvariantCulture),
                startTag.lineInfo.linePos.ToString(CultureInfo.InvariantCulture),
                new string(_ps.chars, _ps.charPos, item - _ps.charPos)
            }, res: System.SR.Xml_TagMismatchEx);
        }
        else
        {
            Throw(System.SR.Xml_UnexpectedEndTag);
        }
    }
References System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.int, System.Globalization.CultureInfo.InvariantCulture, System.item, System.Xml.XmlTextReaderImpl.ParseQNameAsync(), System.Xml.XmlTextReaderImpl.Throw(), System.SR.Xml_TagMismatchEx, and System.SR.Xml_UnexpectedEndTag.
Referenced by System.Xml.XmlTextReaderImpl.ParseEndElementAsync_CheckEndTag(), and System.Xml.XmlTextReaderImpl.ParseEndElementAsync_CheckNameAndParse().