Terraria: System.Xml.XmlTextReaderImpl.ParseElementContentAsync
ParseElementContentAsync()
Task< bool > System.Xml.XmlTextReaderImpl.ParseElementContentAsync () inline private
Definition at line 10003 of file XmlTextReaderImpl.cs.
    {
        while (true)
        {
            int charPos = _ps.charPos;
            char[] chars = _ps.chars;
            switch (chars[charPos])
            {
            case '<':
                switch (chars[charPos + 1])
                {
                case '?':
                    _ps.charPos = charPos + 2;
                    return ParsePIAsync().ContinueBoolTaskFuncWhenFalseAsync((XmlTextReaderImpl thisRef) => thisRef.ParseElementContentAsync(), this);
                case '!':
                    charPos += 2;
                    if (_ps.charsUsed - charPos < 2)
                    {
                        return ParseElementContent_ReadData();
                    }
                    if (chars[charPos] == '-')
                    {
                        if (chars[charPos + 1] == '-')
{
                            _ps.charPos = charPos + 2;
                            return ParseCommentAsync().ContinueBoolTaskFuncWhenFalseAsync((XmlTextReaderImpl thisRef) => thisRef.ParseElementContentAsync(), this);
                        }
                        ThrowUnexpectedToken(charPos + 1, "-");
                    }
                    else if (chars[charPos] == '[')
                    {
                        charPos++;
                        if (_ps.charsUsed - charPos < 6)
{
                            return ParseElementContent_ReadData();
                        }
                        if (XmlConvert.StrEqual(chars, charPos, 6, "CDATA["))
{
                            _ps.charPos = charPos + 6;
                            return ParseCDataAsync().ReturnTrueTaskWhenFinishAsync();
                        }
                        ThrowUnexpectedToken(charPos, "CDATA[");
                    }
                    else if (ParseUnexpectedToken(charPos) == "DOCTYPE")
                    {
                        Throw(System.SR.Xml_BadDTDLocation);
                    }
                    else
                    {
                        ThrowUnexpectedToken(charPos, "<!--", "<[CDATA[");
                    }
                    break;
                case '/':
                    _ps.charPos = charPos + 2;
                    return ParseEndElementAsync().ReturnTrueTaskWhenFinishAsync();
                default:
                    if (charPos + 1 == _ps.charsUsed)
                    {
                        return ParseElementContent_ReadData();
                    }
                    _ps.charPos = charPos + 1;
                    return ParseElementAsync().ReturnTrueTaskWhenFinishAsync();
                }
                break;
            case '&':
                return ParseTextAsync().ContinueBoolTaskFuncWhenFalseAsync((XmlTextReaderImpl thisRef) => thisRef.ParseElementContentAsync(), this);
            default:
                if (charPos == _ps.charsUsed)
                {
                    return ParseElementContent_ReadData();
                }
                return ParseTextAsync().ContinueBoolTaskFuncWhenFalseAsync((XmlTextReaderImpl thisRef) => thisRef.ParseElementContentAsync(), this);
            }
        }
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParseCDataAsync(), System.Xml.XmlTextReaderImpl.ParseCommentAsync(), System.Xml.XmlTextReaderImpl.ParseElementAsync(), System.Xml.XmlTextReaderImpl.ParseElementContent_ReadData(), System.Xml.XmlTextReaderImpl.ParseEndElementAsync(), System.Xml.XmlTextReaderImpl.ParsePIAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.ParseUnexpectedToken(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), and System.SR.Xml_BadDTDLocation.
Referenced by System.Xml.XmlTextReaderImpl.ParseElementContent_ReadData(), and System.Xml.XmlTextReaderImpl.ReadAsync().