Terraria: System.Xml.XmlTextReaderImpl.DtdParserProxy_ParseCommentAsync
DtdParserProxy_ParseCommentAsync()
async Task System.Xml.XmlTextReaderImpl.DtdParserProxy_ParseCommentAsync (StringBuilder sb) inline package
Definition at line 9217 of file XmlTextReaderImpl.cs.
    {
        CheckAsyncCall();
        try
        {
            if (sb == null)
            {
                ParsingMode savedParsingMode = _parsingMode;
                _parsingMode = ParsingMode.SkipNode;
                await ParseCDataOrCommentAsync(XmlNodeType.Comment).ConfigureAwait(continueOnCapturedContext: false);
                _parsingMode = savedParsingMode;
            }
            else
            {
                NodeData originalCurNode = _curNode;
                _curNode = AddNode(_index + _attrCount + 1, _index);
                await ParseCDataOrCommentAsync(XmlNodeType.Comment).ConfigureAwait(continueOnCapturedContext: false);
                _curNode.CopyTo(0, sb);
                _curNode = originalCurNode;
            }
        }
        catch (XmlException ex)
        {
            if (ex.ResString == System.SR.Xml_UnexpectedEOF && _ps.entity != null)
            {
                SendValidationEvent(XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, null, _ps.LineNo, _ps.LinePos);
                return;
            }
            throw;
        }
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.AddNode(), System.Xml.XmlTextReaderImpl.CheckAsyncCall(), System.Xml.XmlTextReaderImpl.NodeData.CopyTo(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.entity, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseCDataOrCommentAsync(), System.SR.Sch_ParEntityRefNesting, System.Xml.XmlTextReaderImpl.SendValidationEvent(), and System.SR.Xml_UnexpectedEOF.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy.ParseCommentAsync().