Terraria: System.Xml.XmlTextReaderImpl.OnNamespaceDecl
OnNamespaceDecl()
void System.Xml.XmlTextReaderImpl.OnNamespaceDecl (NodeData attr) inline private
Definition at line 4831 of file XmlTextReaderImpl.cs.
    {
        if (_supportNamespaces)
        {
            string text = _nameTable.Add(attr.StringValue);
            if (text.Length == 0)
            {
                Throw(System.SR.Xml_BadNamespaceDecl, attr.lineInfo2.lineNo, attr.lineInfo2.linePos - 1);
            }
            AddNamespace(attr.localName, text, attr);
        }
    }
References System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._supportNamespaces, System.Xml.XmlNameTable.Add(), System.Xml.XmlTextReaderImpl.AddNamespace(), System.text, System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_BadNamespaceDecl.
Referenced by System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal(), System.Xml.XmlTextReaderImpl.ParseAttributes(), and System.Xml.XmlTextReaderImpl.ParseAttributesAsync().