Terraria: System.Xml.XmlTextReaderImpl.ParseFragmentAttribute
ParseFragmentAttribute()
bool System.Xml.XmlTextReaderImpl.ParseFragmentAttribute () inline private
Definition at line 7698 of file XmlTextReaderImpl.cs.
    {
        if (_curNode.type == XmlNodeType.None)
        {
            _curNode.type = XmlNodeType.Attribute;
            _curAttrIndex = 0;
            ParseAttributeValueSlow(_ps.charPos, ' ', _curNode);
        }
        else
        {
            _parsingFunction = ParsingFunction.InReadAttributeValue;
        }
        if (ReadAttributeValue())
        {
            _parsingFunction = ParsingFunction.FragmentAttribute;
            return true;
        }
        OnEof();
        return false;
    }
References System.Xml.XmlTextReaderImpl._curAttrIndex, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.OnEof(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ReadAttributeValue(), and System.Xml.XmlTextReaderImpl.NodeData.type.
Referenced by System.Xml.XmlTextReaderImpl.Read(), and System.Xml.XmlTextReaderImpl.ReadAsync().