Terraria: System.Xml.XmlTextReaderImpl.MoveToNextContentNodeAsync
MoveToNextContentNodeAsync()
async Task< bool > System.Xml.XmlTextReaderImpl.MoveToNextContentNodeAsync (bool moveIfOnContentNode) inline private
Definition at line 12858 of file XmlTextReaderImpl.cs.
    {
        do
        {
            switch (_curNode.type)
            {
            case XmlNodeType.Attribute:
                return !moveIfOnContentNode;
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                if (!moveIfOnContentNode)
                {
                    return true;
                }
                break;
            case XmlNodeType.EntityReference:
                _outerReader.ResolveEntity();
                break;
            default:
                return false;
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.Comment:
            case XmlNodeType.EndEntity:
                break;
            }
            moveIfOnContentNode = false;
        }
        while (await _outerReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false));
        return false;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.Dictionary, System.Xml.XmlReader.ReadAsync(), System.Xml.XmlReader.ResolveEntity(), and System.Xml.XmlTextReaderImpl.NodeData.type.
Referenced by System.Xml.XmlTextReaderImpl.FinishReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.InitReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinaryAsync(), and System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync().