Terraria: System.Xml.XmlTextReaderImpl.HandleEntityReference
HandleEntityReference()
EntityType System.Xml.XmlTextReaderImpl.HandleEntityReference (bool isInAttributeValue, EntityExpandType expandType, out int charRefEndPos) inline private
Definition at line 5594 of file XmlTextReaderImpl.cs.
    {
        if (_ps.charPos + 1 == _ps.charsUsed && ReadData() == 0)
        {
            Throw(System.SR.Xml_UnexpectedEOF1);
        }
        if (_ps.chars[_ps.charPos + 1] == '#')
        {
            charRefEndPos = ParseNumericCharRef(expandType != EntityExpandType.OnlyGeneral, null, out var entityType);
            return entityType;
        }
        charRefEndPos = ParseNamedCharRef(expandType != EntityExpandType.OnlyGeneral, null);
        if (charRefEndPos >= 0)
        {
            return EntityType.CharacterNamed;
        }
        if (expandType == EntityExpandType.OnlyCharacter || (_entityHandling != EntityHandling.ExpandEntities && (!isInAttributeValue || !_validatingReaderCompatFlag)))
        {
            return EntityType.Unexpanded;
        }
        _ps.charPos++;
        int linePos = _ps.LinePos;
        int num;
        try
        {
            num = ParseName();
        }
        catch (XmlException)
        {
            Throw(System.SR.Xml_ErrorParsingEntityName, _ps.LineNo, linePos);
            return EntityType.Skipped;
        }
        if (_ps.chars[num] != ';')
        {
            ThrowUnexpectedToken(num, ";");
        }
        int linePos2 = _ps.LinePos;
        string name = _nameTable.Add(_ps.chars, _ps.charPos, num - _ps.charPos);
        _ps.charPos = num + 1;
        charRefEndPos = -1;
        EntityType result = HandleGeneralEntityReference(name, isInAttributeValue, pushFakeEntityIfNullResolver: false, linePos2);
        _reportedBaseUri = _ps.baseUriStr;
        _reportedEncoding = _ps.encoding;
        return result;
    }
References System.Xml.XmlTextReaderImpl._entityHandling, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.XmlTextReaderImpl._validatingReaderCompatFlag, System.Xml.XmlNameTable.Add(), System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(), System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseName(), System.Xml.XmlTextReaderImpl.ParseNamedCharRef(), System.Xml.XmlTextReaderImpl.ParseNumericCharRef(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.SR.Xml_ErrorParsingEntityName, and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ParseDocumentContent(), and System.Xml.XmlTextReaderImpl.ParseText().