Terraria: System.Xml.XmlTextReaderImpl.InitFragmentReader
InitFragmentReader()
void System.Xml.XmlTextReaderImpl.InitFragmentReader (XmlNodeType fragmentType, XmlParserContext parserContext, bool allowXmlDeclFragment) inline private
Definition at line 3177 of file XmlTextReaderImpl.cs.
    {
        _fragmentParserContext = parserContext;
        if (parserContext != null)
        {
            if (parserContext.NamespaceManager != null)
            {
                _namespaceManager = parserContext.NamespaceManager;
                _xmlContext.defaultNamespace = _namespaceManager.LookupNamespace(string.Empty);
            }
            else
            {
                _namespaceManager = new XmlNamespaceManager(_nameTable);
            }
            _ps.baseUriStr = parserContext.BaseURI;
            _ps.baseUri = null;
            _xmlContext.xmlLang = parserContext.XmlLang;
            _xmlContext.xmlSpace = parserContext.XmlSpace;
        }
        else
        {
            _namespaceManager = new XmlNamespaceManager(_nameTable);
            _ps.baseUriStr = string.Empty;
            _ps.baseUri = null;
        }
        _reportedBaseUri = _ps.baseUriStr;
        if (fragmentType <= XmlNodeType.Attribute)
        {
            if (fragmentType != XmlNodeType.Element)
            {
                if (fragmentType != XmlNodeType.Attribute)
                {
                    goto IL_012e;
                }
                _ps.appendMode = false;
                _parsingFunction = ParsingFunction.SwitchToInteractive;
                _nextParsingFunction = ParsingFunction.FragmentAttribute;
            }
            else
            {
                _nextParsingFunction = ParsingFunction.DocumentContent;
            }
        }
        else if (fragmentType != XmlNodeType.Document)
        {
            if (fragmentType != XmlNodeType.XmlDeclaration || !allowXmlDeclFragment)
            {
                goto IL_012e;
            }
            _ps.appendMode = false;
            _parsingFunction = ParsingFunction.SwitchToInteractive;
            _nextParsingFunction = ParsingFunction.XmlDeclarationFragment;
        }
        _fragmentType = fragmentType;
        _fragment = true;
        return;
        IL_012e:
        Throw(System.SR.Xml_PartialContentNodeTypeNotSupportedEx, fragmentType.ToString());
    }
References System.Xml.XmlTextReaderImpl._fragment, System.Xml.XmlTextReaderImpl._fragmentParserContext, System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._namespaceManager, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.Dictionary, System.Xml.XmlNamespaceManager.LookupNamespace(), System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_PartialContentNodeTypeNotSupportedEx.
Referenced by System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), and System.Xml.XmlTextReaderImpl.XmlTextReaderImpl().