Terraria: System.Xml.XmlTextReaderImpl.ParseXmlDeclaration
ParseXmlDeclaration()
bool System.Xml.XmlTextReaderImpl.ParseXmlDeclaration (bool isTextDecl) inline private
Definition at line 3635 of file XmlTextReaderImpl.cs.
    {
        do
        {
            if (_ps.charsUsed - _ps.charPos < 6)
            {
                continue;
            }
            if (!XmlConvert.StrEqual(_ps.chars, _ps.charPos, 5, "<?xml") || XmlCharType.IsNameSingleChar(_ps.chars[_ps.charPos + 5]))
            {
                break;
            }
            if (!isTextDecl)
            {
                _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos + 2);
                _curNode.SetNamedNode(XmlNodeType.XmlDeclaration, _xml);
            }
            _ps.charPos += 5;
            StringBuilder stringBuilder = (isTextDecl ? new StringBuilder() : _stringBuilder);
            int num = 0;
            Encoding encoding = null;
            while (true)
            {
                int length = stringBuilder.Length;
                int num2 = EatWhitespaces((num == 0) ? null : stringBuilder);
                if (_ps.chars[_ps.charPos] == '?')
                {
                    stringBuilder.Length = length;
                    if (_ps.chars[_ps.charPos + 1] == '>')
                    {
                        break;
                    }
                    if (_ps.charPos + 1 == _ps.charsUsed)
                    {
                        goto IL_07a5;
                    }
                    ThrowUnexpectedToken("'>'");
                }
                if (num2 == 0 && num != 0)
                {
                    ThrowUnexpectedToken("?>");
                }
                int num3 = ParseName();
                NodeData nodeData = null;
                char c = _ps.chars[_ps.charPos];
                if (c != 'e')
                {
                    if (c != 's')
                    {
                        if (c != 'v' || !XmlConvert.StrEqual(_ps.chars, _ps.charPos, num3 - _ps.charPos, "version") || num != 0)
{
                            goto IL_03af;
                        }
                        if (!isTextDecl)
{
                            nodeData = AddAttributeNoChecks("version", 1);
                        }
                    }
                    else
                    {
                        if (!XmlConvert.StrEqual(_ps.chars, _ps.charPos, num3 - _ps.charPos, "standalone") || (num != 1 && num != 2) || isTextDecl)
{
                            goto IL_03af;
                        }
                        if (!isTextDecl)
{
                            nodeData = AddAttributeNoChecks("standalone", 1);
                        }
                        num = 2;
                    }
                }
                else
                {
                    if (!XmlConvert.StrEqual(_ps.chars, _ps.charPos, num3 - _ps.charPos, "encoding") || (num != 1 && (!isTextDecl || num != 0)))
                    {
                        goto IL_03af;
                    }
                    if (!isTextDecl)
                    {
                        nodeData = AddAttributeNoChecks("encoding", 1);
                    }
                    num = 1;
                }
                goto IL_03c4;
                IL_03c4:
                if (!isTextDecl)
                {
                    nodeData.SetLineInfo(_ps.LineNo, _ps.LinePos);
                }
                stringBuilder.Append(_ps.chars, _ps.charPos, num3 - _ps.charPos);
                _ps.charPos = num3;
                if (_ps.chars[_ps.charPos] != '=')
                {
                    EatWhitespaces(stringBuilder);
                    if (_ps.chars[_ps.charPos] != '=')
                    {
                        ThrowUnexpectedToken("=");
                    }
                }
                stringBuilder.Append('=');
                _ps.charPos++;
                char c2 = _ps.chars[_ps.charPos];
                if (c2 != '"' && c2 != '\'')
                {
                    EatWhitespaces(stringBuilder);
                    c2 = _ps.chars[_ps.charPos];
                    if (c2 != '"' && c2 != '\'')
                    {
                        ThrowUnexpectedToken("\"", "'");
                    }
                }
                stringBuilder.Append(c2);
                _ps.charPos++;
                if (!isTextDecl)
                {
                    nodeData.quoteChar = c2;
                    nodeData.SetLineInfo2(_ps.LineNo, _ps.LinePos);
                }
                int i = _ps.charPos;
                char[] chars;
                while (true)
                {
                    for (chars = _ps.chars; XmlCharType.IsAttributeValueChar(chars[i]); i++)
                    {
                    }
                    if (_ps.chars[i] == c2)
                    {
                        break;
                    }
                    if (i == _ps.charsUsed)
                    {
                        if (ReadData() != 0)
{
                            continue;
                        }
                        goto IL_0783;
                    }
                    goto IL_0790;
                }
                switch (num)
                {
                case 0:
                    if (XmlConvert.StrEqual(_ps.chars, _ps.charPos, i - _ps.charPos, "1.0"))
                    {
                        if (!isTextDecl)
{
                            nodeData.SetValue(_ps.chars, _ps.charPos, i - _ps.charPos);
                        }
                        num = 1;
                    }
                    else
                    {
                        string arg = new string(_ps.chars, _ps.charPos, i - _ps.charPos);
                        Throw(System.SR.Xml_InvalidVersionNumber, arg);
                    }
                    break;
                case 1:
                {
                    string text = new string(_ps.chars, _ps.charPos, i - _ps.charPos);
                    encoding = CheckEncoding(text);
                    if (!isTextDecl)
                    {
                        nodeData.SetValue(text);
                    }
                    num = 2;
                    break;
                }
                case 2:
                    if (XmlConvert.StrEqual(_ps.chars, _ps.charPos, i - _ps.charPos, "yes"))
                    {
                        _standalone = true;
                    }
                    else if (XmlConvert.StrEqual(_ps.chars, _ps.charPos, i - _ps.charPos, "no"))
                    {
                        _standalone = false;
                    }
                    else
                    {
                        Throw(System.SR.Xml_InvalidXmlDecl, _ps.LineNo, _ps.LinePos - 1);
                    }
                    if (!isTextDecl)
                    {
                        nodeData.SetValue(_ps.chars, _ps.charPos, i - _ps.charPos);
                    }
                    num = 3;
                    break;
                }
                stringBuilder.Append(chars, _ps.charPos, i - _ps.charPos);
                stringBuilder.Append(c2);
                _ps.charPos = i + 1;
                continue;
                IL_07a5:
                if (_ps.isEof || ReadData() == 0)
                {
                    Throw(System.SR.Xml_UnexpectedEOF1);
                }
                continue;
                IL_0790:
                Throw(isTextDecl ? System.SR.Xml_InvalidTextDecl : System.SR.Xml_InvalidXmlDecl);
                goto IL_07a5;
                IL_0783:
                Throw(System.SR.Xml_UnclosedQuote);
                goto IL_07a5;
                IL_03af:
                Throw(isTextDecl ? System.SR.Xml_InvalidTextDecl : System.SR.Xml_InvalidXmlDecl);
                goto IL_03c4;
            }
            if (num == 0)
            {
                Throw(isTextDecl ? System.SR.Xml_InvalidTextDecl : System.SR.Xml_InvalidXmlDecl);
            }
            _ps.charPos += 2;
            if (!isTextDecl)
            {
                _curNode.SetValue(stringBuilder.ToString());
                stringBuilder.Length = 0;
                _nextParsingFunction = _parsingFunction;
                _parsingFunction = ParsingFunction.ResetAttributesRootLevel;
            }
            if (encoding == null)
            {
                if (isTextDecl)
                {
                    Throw(System.SR.Xml_InvalidTextDecl);
                }
                if (_afterResetState)
                {
                    string webName = _ps.encoding.WebName;
                    if (webName != "utf-8" && webName != "utf-16" && webName != "utf-16BE" && !(_ps.encoding is Ucs4Encoding))
                    {
                        Throw(System.SR.Xml_EncodingSwitchAfterResetState, (_ps.encoding.GetByteCount("A") == 1) ? "UTF-8" : "UTF-16");
                    }
                }
                if (_ps.decoder is SafeAsciiDecoder)
                {
                    SwitchEncodingToUTF8();
                }
            }
            else
            {
                SwitchEncoding(encoding);
            }
            _ps.appendMode = false;
            return true;
        }
        while (ReadData() != 0);
        if (!isTextDecl)
        {
            _parsingFunction = _nextParsingFunction;
        }
        if (_afterResetState)
        {
            string webName2 = _ps.encoding.WebName;
            if (webName2 != "utf-8" && webName2 != "utf-16" && webName2 != "utf-16BE" && !(_ps.encoding is Ucs4Encoding))
            {
                Throw(System.SR.Xml_EncodingSwitchAfterResetState, (_ps.encoding.GetByteCount("A") == 1) ? "UTF-8" : "UTF-16");
            }
        }
        if (_ps.decoder is SafeAsciiDecoder)
        {
            SwitchEncodingToUTF8();
        }
        _ps.appendMode = false;
        return false;
    }
References System.Xml.XmlTextReaderImpl._afterResetState, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._standalone, System.Xml.XmlTextReaderImpl._stringBuilder, System.Xml.XmlTextReaderImpl._xml, System.Xml.XmlTextReaderImpl.AddAttributeNoChecks(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.XmlTextReaderImpl.CheckEncoding(), System.Xml.XmlTextReaderImpl.ParsingState.decoder, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespaces(), System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Text.Encoding.GetByteCount(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlCharType.IsNameSingleChar(), System.length, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseName(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode(), System.Xml.XmlTextReaderImpl.NodeData.SetValue(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.SwitchEncoding(), System.Xml.XmlTextReaderImpl.SwitchEncodingToUTF8(), System.text, System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.Text.Encoding.WebName, System.SR.Xml_EncodingSwitchAfterResetState, System.SR.Xml_InvalidTextDecl, System.SR.Xml_InvalidVersionNumber, System.SR.Xml_InvalidXmlDecl, System.SR.Xml_UnclosedQuote, and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_PushExternalSubset(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationFragment(), System.Xml.XmlTextReaderImpl.PushExternalEntity(), and System.Xml.XmlTextReaderImpl.Read().