Terraria: System.Xml.XmlTextReaderImpl.HandleGeneralEntityReferenceAsync
HandleGeneralEntityReferenceAsync()
async Task< EntityType > System.Xml.XmlTextReaderImpl.HandleGeneralEntityReferenceAsync (string name, bool isInAttributeValue, bool pushFakeEntityIfNullResolver, int entityStartLinePos) inline private
Definition at line 11617 of file XmlTextReaderImpl.cs.
    {
        IDtdEntityInfo entity = null;
        if (_dtdInfo == null && _fragmentParserContext != null && _fragmentParserContext.HasDtdInfo && _dtdProcessing == DtdProcessing.Parse)
        {
            await ParseDtdFromParserContextAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        if (_dtdInfo != null)
        {
            IDtdEntityInfo dtdEntityInfo;
            entity = (dtdEntityInfo = _dtdInfo.LookupEntity(name));
            if (dtdEntityInfo != null)
            {
                goto IL_012e;
            }
        }
        if (_disableUndeclaredEntityCheck)
        {
            SchemaEntity schemaEntity = new SchemaEntity(new XmlQualifiedName(name), isParameter: false);
            schemaEntity.Text = string.Empty;
            entity = schemaEntity;
        }
        else
        {
            Throw(System.SR.Xml_UndeclaredEntity, name, _ps.LineNo, entityStartLinePos);
        }
        goto IL_012e;
        IL_012e:
        if (entity.IsUnparsedEntity)
        {
            if (_disableUndeclaredEntityCheck)
            {
                SchemaEntity schemaEntity2 = new SchemaEntity(new XmlQualifiedName(name), isParameter: false);
                schemaEntity2.Text = string.Empty;
                entity = schemaEntity2;
            }
            else
            {
                Throw(System.SR.Xml_UnparsedEntityRef, name, _ps.LineNo, entityStartLinePos);
            }
        }
        if (_standalone && entity.IsDeclaredInExternal)
        {
            Throw(System.SR.Xml_ExternalEntityInStandAloneDocument, entity.Name, _ps.LineNo, entityStartLinePos);
        }
        if (entity.IsExternal)
        {
            if (isInAttributeValue)
            {
                Throw(System.SR.Xml_ExternalEntityInAttValue, name, _ps.LineNo, entityStartLinePos);
                return EntityType.Skipped;
            }
            if (_parsingMode == ParsingMode.SkipContent)
            {
                return EntityType.Skipped;
            }
            if (IsResolverNull)
            {
                if (pushFakeEntityIfNullResolver)
                {
                    await PushExternalEntityAsync(entity).ConfigureAwait(continueOnCapturedContext: false);
                    _curNode.entityId = _ps.entityId;
                    return EntityType.FakeExpanded;
                }
                return EntityType.Skipped;
            }
            await PushExternalEntityAsync(entity).ConfigureAwait(continueOnCapturedContext: false);
            _curNode.entityId = _ps.entityId;
            return (isInAttributeValue && _validatingReaderCompatFlag) ? EntityType.ExpandedInAttribute : EntityType.Expanded;
        }
        if (_parsingMode == ParsingMode.SkipContent)
        {
            return EntityType.Skipped;
        }
        PushInternalEntity(entity);
        _curNode.entityId = _ps.entityId;
        return (isInAttributeValue && _validatingReaderCompatFlag) ? EntityType.ExpandedInAttribute : EntityType.Expanded;
    }
References System.Xml.XmlTextReaderImpl._disableUndeclaredEntityCheck, System.Xml.XmlTextReaderImpl._dtdInfo, System.Xml.XmlTextReaderImpl._dtdProcessing, System.Xml.XmlTextReaderImpl._fragmentParserContext, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._standalone, System.Xml.XmlTextReaderImpl._validatingReaderCompatFlag, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.entityId, System.Xml.XmlParserContext.HasDtdInfo, System.Xml.IDtdEntityInfo.IsDeclaredInExternal, System.Xml.IDtdEntityInfo.IsExternal, System.Xml.IDtdEntityInfo.IsUnparsedEntity, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.IDtdInfo.LookupEntity(), System.Xml.IDtdEntityInfo.Name, System.Xml.XmlTextReaderImpl.ParseDtdFromParserContextAsync(), System.Xml.XmlTextReaderImpl.PushExternalEntityAsync(), System.Xml.XmlTextReaderImpl.PushInternalEntity(), System.Xml.XmlTextReaderImpl.Throw(), System.SR.Xml_ExternalEntityInAttValue, System.SR.Xml_ExternalEntityInStandAloneDocument, System.SR.Xml_UndeclaredEntity, and System.SR.Xml_UnparsedEntityRef.
Referenced by System.Xml.XmlTextReaderImpl.HandleEntityReferenceAsync().