Terraria: System.Xml.XmlTextReaderImpl.PushExternalEntityAsync
PushExternalEntityAsync()
async Task< bool > System.Xml.XmlTextReaderImpl.PushExternalEntityAsync (IDtdEntityInfo entity) inline private
Definition at line 12761 of file XmlTextReaderImpl.cs.
    {
        if (!IsResolverNull)
        {
            Uri baseUri = null;
            if (!string.IsNullOrEmpty(entity.BaseUriString))
            {
                baseUri = _xmlResolver.ResolveUri(null, entity.BaseUriString);
            }
            await PushExternalEntityOrSubsetAsync(entity.PublicId, entity.SystemId, baseUri, entity.Name).ConfigureAwait(continueOnCapturedContext: false);
            RegisterEntity(entity);
            int initialPos = _ps.charPos;
            if (_v1Compat)
            {
                await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (!(await ParseXmlDeclarationAsync(isTextDecl: true).ConfigureAwait(continueOnCapturedContext: false)))
            {
                _ps.charPos = initialPos;
            }
            return true;
        }
        Encoding encoding = _ps.encoding;
        PushParsingState();
        InitStringInput(entity.SystemId, encoding, string.Empty);
        RegisterEntity(entity);
        RegisterConsumedCharacters(0L, inEntityReference: true);
        return false;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl._xmlResolver, System.Xml.IDtdEntityInfo.BaseUriString, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespacesAsync(), System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlTextReaderImpl.InitStringInput(), System.Xml.L, System.Xml.IDtdEntityInfo.Name, System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Xml.IDtdEntityInfo.PublicId, System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubsetAsync(), System.Xml.XmlTextReaderImpl.PushParsingState(), System.Xml.XmlTextReaderImpl.RegisterConsumedCharacters(), System.Xml.XmlTextReaderImpl.RegisterEntity(), System.Xml.XmlResolver.ResolveUri(), and System.Xml.IDtdEntityInfo.SystemId.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_PushEntityAsync(), and System.Xml.XmlTextReaderImpl.HandleGeneralEntityReferenceAsync().