Terraria: System.Xml.XmlTextReaderImpl.OnXmlReservedAttribute
OnXmlReservedAttribute()
void System.Xml.XmlTextReaderImpl.OnXmlReservedAttribute (NodeData attr) inline private
Definition at line 4844 of file XmlTextReaderImpl.cs.
    {
        string localName = attr.localName;
        if (!(localName == "space"))
        {
            if (localName == "lang")
            {
                if (!_curNode.xmlContextPushed)
                {
                    PushXmlContext();
                }
                _xmlContext.xmlLang = attr.StringValue;
            }
            return;
        }
        if (!_curNode.xmlContextPushed)
        {
            PushXmlContext();
        }
        string text = XmlConvert.TrimString(attr.StringValue);
        if (!(text == "preserve"))
        {
            if (text == "default")
            {
                _xmlContext.xmlSpace = XmlSpace.Default;
            }
            else
            {
                Throw(System.SR.Xml_InvalidXmlSpace, attr.StringValue, attr.lineInfo.lineNo, attr.lineInfo.linePos);
            }
        }
        else
        {
            _xmlContext.xmlSpace = XmlSpace.Preserve;
        }
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.PushXmlContext(), System.text, System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlConvert.TrimString(), System.SR.Xml_InvalidXmlSpace, and System.Xml.XmlTextReaderImpl.NodeData.xmlContextPushed.
Referenced by System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal(), System.Xml.XmlTextReaderImpl.ParseAttributes(), and System.Xml.XmlTextReaderImpl.ParseAttributesAsync().