Terraria: System.Xml.XmlTextReaderImpl.EatWhitespaces
EatWhitespaces()
int System.Xml.XmlTextReaderImpl.EatWhitespaces (StringBuilder sb) inline private
Definition at line 6497 of file XmlTextReaderImpl.cs.
    {
        int num = _ps.charPos;
        int num2 = 0;
        char[] chars = _ps.chars;
        while (true)
        {
            switch (chars[num])
            {
            case '\n':
                num++;
                OnNewLine(num);
                continue;
            case '\r':
                if (chars[num + 1] == '\n')
                {
                    int num4 = num - _ps.charPos;
                    if (sb != null && !_ps.eolNormalized)
                    {
                        if (num4 > 0)
{
                            sb.Append(chars, _ps.charPos, num4);
                            num2 += num4;
                        }
                        _ps.charPos = num + 1;
                    }
                    num += 2;
                }
                else
                {
                    if (num + 1 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    if (!_ps.eolNormalized)
                    {
                        chars[num] = '\n';
                    }
                    num++;
                }
                OnNewLine(num);
                continue;
            case '\t':
            case ' ':
                num++;
                continue;
            default:
                if (num != _ps.charsUsed)
                {
                    int num3 = num - _ps.charPos;
                    if (num3 > 0)
                    {
                        sb?.Append(_ps.chars, _ps.charPos, num3);
                        _ps.charPos = num;
                        num2 += num3;
                    }
                    return num2;
                }
                break;
            }
            int num5 = num - _ps.charPos;
            if (num5 > 0)
            {
                sb?.Append(_ps.chars, _ps.charPos, num5);
                _ps.charPos = num;
                num2 += num5;
            }
            if (ReadData() == 0)
            {
                if (_ps.charsUsed - _ps.charPos == 0)
                {
                    break;
                }
                if (_ps.chars[_ps.charPos] != '\r')
                {
                    Throw(System.SR.Xml_UnexpectedEOF1);
                }
            }
            num = _ps.charPos;
            chars = _ps.chars;
        }
        return num2;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Text.StringBuilder.Append(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.eolNormalized, System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_PushExternalSubset(), System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseDoctypeDecl(), System.Xml.XmlTextReaderImpl.ParsePI(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.PushExternalEntity(), and System.Xml.XmlTextReaderImpl.SkipDtd().