Terraria: System.Xml.XmlTextReaderImpl.BlockCopyChars
BlockCopyChars()
static void System.Xml.XmlTextReaderImpl.BlockCopyChars (char[] src, int srcOffset, char[] dst, int dstOffset, int count) inline static package
Definition at line 8556 of file XmlTextReaderImpl.cs.
    {
        Buffer.BlockCopy(src, srcOffset * 2, dst, dstOffset * 2, count * 2);
    }
References System.Buffer.BlockCopy(), and System.count.
Referenced by System.Xml.XmlTextReaderImpl.NodeData.CopyTo(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.ReadValueChunk(), System.Xml.XmlTextReaderImpl.ReadValueChunkAsync(), and System.Xml.XmlTextReaderImpl.ShiftBuffer().