Terraria: System.Xml.XmlTextReaderImpl.ReadElementContentAsBinaryAsync
ReadElementContentAsBinaryAsync()
async Task< int > System.Xml.XmlTextReaderImpl.ReadElementContentAsBinaryAsync (byte[] buffer, int index, int count) inline private
Definition at line 12965 of file XmlTextReaderImpl.cs.
    {
        if (count == 0)
        {
            return 0;
        }
        int num = await ReadContentAsBinaryAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
        if (num > 0)
        {
            return num;
        }
        if (_curNode.type != XmlNodeType.EndElement)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, _curNode.type.ToString(), this);
        }
        _parsingFunction = _nextParsingFunction;
        _nextParsingFunction = _nextNextParsingFunction;
        await _outerReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
        return 0;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._nextNextParsingFunction, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.XmlTextReaderImpl._parsingFunction, System.buffer, System.count, System.index, System.Xml.XmlReader.ReadAsync(), System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.NodeData.type, System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64Async(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64Async_Helper(), and System.Xml.XmlTextReaderImpl.ReadElementContentAsBinHexAsync().