Terraria: System.Xml.XmlTextReaderImpl.AddNode
AddNode()
NodeData System.Xml.XmlTextReaderImpl.AddNode (int nodeIndex, int nodeDepth) inline private
Definition at line 6933 of file XmlTextReaderImpl.cs.
    {
        NodeData nodeData = _nodes[nodeIndex];
        if (nodeData != null)
        {
            nodeData.depth = nodeDepth;
            return nodeData;
        }
        return AllocNode(nodeIndex, nodeDepth);
    }
References System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl.AllocNode(), and System.Xml.Dictionary.
Referenced by System.Xml.XmlTextReaderImpl.AddAttribute(), System.Xml.XmlTextReaderImpl.AddAttributeNoChecks(), System.Xml.XmlTextReaderImpl.DtdParserProxy_ParseComment(), System.Xml.XmlTextReaderImpl.DtdParserProxy_ParseCommentAsync(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.Read(), System.Xml.XmlTextReaderImpl.ReadAsync(), and System.Xml.XmlTextReaderImpl.ReadAttributeValue().