Terraria: System.Xml.XmlTextReaderImpl.AddDefaultAttributeNonDtd
AddDefaultAttributeNonDtd()
bool System.Xml.XmlTextReaderImpl.AddDefaultAttributeNonDtd (SchemaAttDef attrDef) inline package
Definition at line 8169 of file XmlTextReaderImpl.cs.
    {
        string text = _nameTable.Add(attrDef.Name.Name);
        string text2 = _nameTable.Add(attrDef.Prefix);
        string text3 = _nameTable.Add(attrDef.Name.Namespace);
        if (text2.Length == 0 && text3.Length > 0)
        {
            text2 = _namespaceManager.LookupPrefix(text3);
            if (text2 == null)
            {
                text2 = string.Empty;
            }
        }
        for (int i = _index + 1; i < _index + 1 + _attrCount; i++)
        {
            if ((object)_nodes[i].localName == text && ((object)_nodes[i].prefix == text2 || ((object)_nodes[i].ns == text3 && text3 != null)))
            {
                return false;
            }
        }
        NodeData nodeData = AddDefaultAttributeInternal(text, text3, text2, attrDef.DefaultValueExpanded, attrDef.LineNumber, attrDef.LinePosition, attrDef.ValueLineNumber, attrDef.ValueLinePosition, attrDef.Reserved != SchemaAttDef.Reserve.None);
        nodeData.schemaType = ((attrDef.SchemaType == null) ? ((object)attrDef.Datatype) : ((object)attrDef.SchemaType));
        nodeData.typedValue = attrDef.DefaultValueTyped;
        return true;
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._namespaceManager, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlNameTable.Add(), System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal(), System.Xml.Dictionary, System.Xml.XmlNamespaceManager.LookupPrefix(), System.prefix, and System.text.
Referenced by System.Xml.XmlValidatingReaderImpl.AddDefaultAttribute().