Terraria: System.Xml.XmlTextReaderImpl.GetChars
GetChars()
int System.Xml.XmlTextReaderImpl.GetChars (int maxCharsCount) inline private
Definition at line 3565 of file XmlTextReaderImpl.cs.
    {
        int bytesUsed = _ps.bytesUsed - _ps.bytePos;
        if (bytesUsed == 0)
        {
            return 0;
        }
        int charsUsed;
        try
        {
            _ps.decoder.Convert(_ps.bytes, _ps.bytePos, bytesUsed, _ps.chars, _ps.charsUsed, maxCharsCount, flush: false, out bytesUsed, out charsUsed, out var _);
        }
        catch (ArgumentException)
        {
            InvalidCharRecovery(ref bytesUsed, out charsUsed);
        }
        _ps.bytePos += bytesUsed;
        _ps.charsUsed += charsUsed;
        return charsUsed;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.bytePos, System.Xml.XmlTextReaderImpl.ParsingState.bytes, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Text.Decoder.Convert(), System.Xml.XmlTextReaderImpl.ParsingState.decoder, System.Xml.Dictionary, and System.Xml.XmlTextReaderImpl.InvalidCharRecovery().
Referenced by System.Xml.XmlTextReaderImpl.ReadData(), and System.Xml.XmlTextReaderImpl.ReadDataAsync().