Terraria: System.Xml.XmlTextReaderImpl.ParseCDataOrCommentTupleAsync
ParseCDataOrCommentTupleAsync()
async Task<(int, int, bool)> System.Xml.XmlTextReaderImpl.ParseCDataOrCommentTupleAsync (XmlNodeType type) inline private
Definition at line 11988 of file XmlTextReaderImpl.cs.
    {
        if (_ps.charsUsed - _ps.charPos < 3 && await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
        {
            Throw(System.SR.Xml_UnexpectedEOF, (type == XmlNodeType.Comment) ? "Comment" : "CDATA");
        }
        int num = _ps.charPos;
        char[] chars = _ps.chars;
        int num2 = 0;
        int num3 = -1;
        char c = ((type == XmlNodeType.Comment) ? '-' : ']');
        int item;
        int charPos;
        while (true)
        {
            char c2;
            if (XmlCharType.IsTextChar(c2 = chars[num]) && c2 != c)
            {
                num++;
                continue;
            }
            if (chars[num] == c)
            {
                if (chars[num + 1] == c)
                {
                    if (chars[num + 2] == '>')
                    {
                        if (num2 > 0)
{
                            ShiftBuffer(num3 + num2, num3, num - num3 - num2);
                            item = num - num2;
                        }
                        else
{
                            item = num;
                        }
                        charPos = _ps.charPos;
                        _ps.charPos = num + 3;
                        return (charPos, item, true);
                    }
                    if (num + 2 == _ps.charsUsed)
                    {
                        break;
                    }
                    if (type == XmlNodeType.Comment)
                    {
                        Throw(num, System.SR.Xml_InvalidCommentChars);
                    }
                }
                else if (num + 1 == _ps.charsUsed)
                {
                    break;
                }
                num++;
                continue;
            }
            switch (chars[num])
            {
            case '\n':
                num++;
                OnNewLine(num);
                continue;
            case '\r':
                if (chars[num + 1] == '\n')
                {
                    if (!_ps.eolNormalized && _parsingMode == ParsingMode.Full)
                    {
                        if (num - _ps.charPos > 0)
{
                            if (num2 == 0)
{
                                num2 = 1;
                                num3 = num;
                            }
                            else
{
                                ShiftBuffer(num3 + num2, num3, num - num3 - num2);
                                num3 = num - num2;
                                num2++;
                            }
                        }
                        else
{
                            _ps.charPos++;
                        }
                    }
                    num += 2;
                }
                else
                {
                    if (num + 1 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    if (!_ps.eolNormalized)
                    {
                        chars[num] = '\n';
                    }
                    num++;
                }
                OnNewLine(num);
                continue;
            case '\t':
            case '&':
            case '<':
            case ']':
                num++;
                continue;
            default:
            {
                if (num == _ps.charsUsed)
                {
                    break;
                }
                char ch = chars[num];
                if (XmlCharType.IsHighSurrogate(ch))
                {
                    if (num + 1 == _ps.charsUsed)
                    {
                        break;
                    }
                    num++;
                    if (XmlCharType.IsLowSurrogate(chars[num]))
                    {
                        num++;
                        continue;
                    }
                }
                ThrowInvalidChar(chars, _ps.charsUsed, num);
                break;
            }
            }
            break;
        }
        if (num2 > 0)
        {
            ShiftBuffer(num3 + num2, num3, num - num3 - num2);
            item = num - num2;
        }
        else
        {
            item = num;
        }
        charPos = _ps.charPos;
        _ps.charPos = num;
        return (charPos, item, false);
    }
References System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.ch, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.eolNormalized, System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Xml.XmlCharType.IsTextChar(), System.item, System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.ShiftBuffer(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), System.type, System.SR.Xml_InvalidCommentChars, and System.SR.Xml_UnexpectedEOF.
Referenced by System.Xml.XmlTextReaderImpl.ParseCDataOrCommentAsync().