Terraria: System.Xml.XmlTextReaderImpl.OpenAndPushAsync
OpenAndPushAsync()
async Task< bool > System.Xml.XmlTextReaderImpl.OpenAndPushAsync (Uri uri) inline private
Definition at line 12736 of file XmlTextReaderImpl.cs.
    {
        if (_xmlResolver.SupportsType(uri, typeof(TextReader)))
        {
            TextReader textReader = (TextReader)(await _xmlResolver.GetEntityAsync(uri, null, typeof(TextReader)).ConfigureAwait(continueOnCapturedContext: false));
            if (textReader == null)
            {
                return false;
            }
            PushParsingState();
            await InitTextReaderInputAsync(uri.ToString(), uri, textReader).ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            Stream stream = (Stream)(await _xmlResolver.GetEntityAsync(uri, null, typeof(Stream)).ConfigureAwait(continueOnCapturedContext: false));
            if (stream == null)
            {
                return false;
            }
            PushParsingState();
            await InitStreamInputAsync(uri, stream, null).ConfigureAwait(continueOnCapturedContext: false);
        }
        return true;
    }
References System.Xml.XmlTextReaderImpl._xmlResolver, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlResolver.GetEntityAsync(), System.Xml.XmlTextReaderImpl.InitStreamInputAsync(), System.Xml.XmlTextReaderImpl.InitTextReaderInputAsync(), System.Xml.XmlTextReaderImpl.PushParsingState(), System.stream, System.Xml.XmlTextReaderImpl.Stream, System.Xml.XmlResolver.SupportsType(), System.Xml.XmlTextReaderImpl.TextReader, and System.Uri.ToString().
Referenced by System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubsetAsync().