Terraria: System.Xml.XmlTextReaderImpl.DetectEncoding
DetectEncoding()
Encoding System.Xml.XmlTextReaderImpl.DetectEncoding () inline private
Definition at line 3277 of file XmlTextReaderImpl.cs.
    {
        if (_ps.bytesUsed < 2)
        {
            return null;
        }
        int num = (_ps.bytes[0] << 8) | _ps.bytes[1];
        int num2 = ((_ps.bytesUsed >= 4) ? ((_ps.bytes[2] << 8) | _ps.bytes[3]) : 0);
        switch (num)
        {
        case 0:
            switch (num2)
            {
            case 65279:
                return Ucs4Encoding.UCS4_Bigendian;
            case 60:
                return Ucs4Encoding.UCS4_Bigendian;
            case 65534:
                return Ucs4Encoding.UCS4_2143;
            case 15360:
                return Ucs4Encoding.UCS4_2143;
            }
            break;
        case 65279:
            if (num2 == 0)
            {
                return Ucs4Encoding.UCS4_3412;
            }
            return Encoding.BigEndianUnicode;
        case 65534:
            if (num2 == 0)
            {
                return Ucs4Encoding.UCS4_Littleendian;
            }
            return Encoding.Unicode;
        case 15360:
            if (num2 == 0)
            {
                return Ucs4Encoding.UCS4_Littleendian;
            }
            return Encoding.Unicode;
        case 60:
            if (num2 == 0)
            {
                return Ucs4Encoding.UCS4_3412;
            }
            return Encoding.BigEndianUnicode;
        case 19567:
            if (num2 == 42900)
            {
                Throw(System.SR.Xml_UnknownEncoding, "ebcdic");
            }
            break;
        case 61371:
            if ((num2 & 0xFF00) == 48896)
            {
                return new UTF8Encoding(encoderShouldEmitUTF8Identifier: true, throwOnInvalidBytes: true);
            }
            break;
        }
        return null;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Text.Encoding.BigEndianUnicode, System.Xml.XmlTextReaderImpl.ParsingState.bytes, System.Xml.XmlTextReaderImpl.ParsingState.bytesUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.Throw(), System.Xml.Ucs4Encoding.UCS4_2143, System.Xml.Ucs4Encoding.UCS4_3412, System.Xml.Ucs4Encoding.UCS4_Bigendian, System.Xml.Ucs4Encoding.UCS4_Littleendian, System.Text.Encoding.Unicode, and System.SR.Xml_UnknownEncoding.
Referenced by System.Xml.XmlTextReaderImpl.InitStreamInput(), and System.Xml.XmlTextReaderImpl.InitStreamInputAsync().