Terraria: System.Xml.XmlTextReaderImpl.ReadAsync_SwitchToInteractiveXmlDecl
ReadAsync_SwitchToInteractiveXmlDecl()
Task< bool > System.Xml.XmlTextReaderImpl.ReadAsync_SwitchToInteractiveXmlDecl () inline private
Definition at line 8767 of file XmlTextReaderImpl.cs.
    {
        _readState = ReadState.Interactive;
        _parsingFunction = _nextParsingFunction;
        Task<bool> task = ParseXmlDeclarationAsync(isTextDecl: false);
        if (task.IsSuccess())
        {
            return ReadAsync_SwitchToInteractiveXmlDecl_Helper(task.Result);
        }
        return _ReadAsync_SwitchToInteractiveXmlDecl(task);
    }
References System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ReadAsync_SwitchToInteractiveXmlDecl(), System.Xml.XmlTextReaderImpl._readState, System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Xml.XmlTextReaderImpl.ReadAsync_SwitchToInteractiveXmlDecl_Helper(), and System.task.
Referenced by System.Xml.XmlTextReaderImpl.ReadAsync().