Terraria: System.Xml.XmlTextReaderImpl.AddDefaultAttributesAndNormalize
AddDefaultAttributesAndNormalize()
void System.Xml.XmlTextReaderImpl.AddDefaultAttributesAndNormalize () inline private
Definition at line 4362 of file XmlTextReaderImpl.cs.
    {
        IDtdAttributeListInfo dtdAttributeListInfo = _dtdInfo.LookupAttributeList(_curNode.localName, _curNode.prefix);
        if (dtdAttributeListInfo == null)
        {
            return;
        }
        if (_normalize && dtdAttributeListInfo.HasNonCDataAttributes)
        {
            for (int i = _index + 1; i < _index + 1 + _attrCount; i++)
            {
                NodeData nodeData = _nodes[i];
                IDtdAttributeInfo dtdAttributeInfo = dtdAttributeListInfo.LookupAttribute(nodeData.prefix, nodeData.localName);
                if (dtdAttributeInfo == null || !dtdAttributeInfo.IsNonCDataType)
                {
                    continue;
                }
                if (DtdValidation && _standalone && dtdAttributeInfo.IsDeclaredInExternal)
                {
                    string stringValue = nodeData.StringValue;
                    nodeData.TrimSpacesInValue();
                    if (stringValue != nodeData.StringValue)
                    {
                        SendValidationEvent(XmlSeverityType.Error, System.SR.Sch_StandAloneNormalization, nodeData.GetNameWPrefix(_nameTable), nodeData.LineNo, nodeData.LinePos);
                    }
                }
                else
                {
                    nodeData.TrimSpacesInValue();
                }
            }
        }
        IEnumerable<IDtdDefaultAttributeInfo> enumerable = dtdAttributeListInfo.LookupDefaultAttributes();
        if (enumerable == null)
        {
            return;
        }
        int attrCount = _attrCount;
        NodeData[] array = null;
        if (_attrCount >= 250)
        {
            array = new NodeData[_attrCount];
            Array.Copy(_nodes, _index + 1, array, 0, _attrCount);
            object[] array2 = array;
            Array.Sort(array2, DtdDefaultAttributeInfoToNodeDataComparer.Instance);
        }
        foreach (IDtdDefaultAttributeInfo item in enumerable)
        {
            if (AddDefaultAttributeDtd(item, definedInDtd: true, array) && DtdValidation && _standalone && item.IsDeclaredInExternal)
            {
                string prefix = item.Prefix;
                string arg = ((prefix.Length == 0) ? item.LocalName : (prefix + ":" + item.LocalName));
                SendValidationEvent(XmlSeverityType.Error, System.SR.Sch_UnSpecifiedDefaultAttributeInExternalStandalone, arg, _curNode.LineNo, _curNode.LinePos);
            }
        }
        if (attrCount == 0 && _attrNeedNamespaceLookup)
        {
            AttributeNamespaceLookup();
            _attrNeedNamespaceLookup = false;
        }
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._attrNeedNamespaceLookup, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._dtdInfo, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._normalize, System.Xml.XmlTextReaderImpl._standalone, System.Xml.XmlTextReaderImpl.AddDefaultAttributeDtd(), System.array, System.Xml.XmlTextReaderImpl.AttributeNamespaceLookup(), System.Array.Copy(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.DtdDefaultAttributeInfoToNodeDataComparer.Instance, System.item, System.Xml.XmlTextReaderImpl.NodeData.LineNo, System.Xml.XmlTextReaderImpl.NodeData.LinePos, System.Xml.XmlTextReaderImpl.NodeData.localName, System.Xml.IDtdInfo.LookupAttributeList(), System.prefix, System.Xml.XmlTextReaderImpl.NodeData.prefix, System.SR.Sch_StandAloneNormalization, System.SR.Sch_UnSpecifiedDefaultAttributeInExternalStandalone, System.Xml.XmlTextReaderImpl.SendValidationEvent(), and System.Array.Sort().
Referenced by System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseElement(), and System.Xml.XmlTextReaderImpl.ParseElementAsync_NoAttributes().