Terraria: System.Xml.XmlTextReaderImpl.InitReadContentAsBinary
InitReadContentAsBinary()
bool System.Xml.XmlTextReaderImpl.InitReadContentAsBinary () inline private
Definition at line 7983 of file XmlTextReaderImpl.cs.
    {
        if (_parsingFunction == ParsingFunction.InReadValueChunk)
        {
            throw new InvalidOperationException(System.SR.Xml_MixingReadValueChunkWithBinary);
        }
        if (_parsingFunction == ParsingFunction.InIncrementalRead)
        {
            throw new InvalidOperationException(System.SR.Xml_MixingV1StreamingWithV2Binary);
        }
        if (!XmlReader.IsTextualNode(_curNode.type) && !MoveToNextContentNode(moveIfOnContentNode: false))
        {
            return false;
        }
        SetupReadContentAsBinaryState(ParsingFunction.InReadContentAsBinary);
        _incReadLineInfo.Set(_curNode.LineNo, _curNode.LinePos);
        return true;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadLineInfo, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlReader.IsTextualNode(), System.Xml.XmlTextReaderImpl.NodeData.LineNo, System.Xml.XmlTextReaderImpl.NodeData.LinePos, System.Xml.XmlTextReaderImpl.MoveToNextContentNode(), System.Xml.LineInfo.Set(), System.Xml.XmlTextReaderImpl.SetupReadContentAsBinaryState(), System.Xml.XmlTextReaderImpl.NodeData.type, System.SR.Xml_MixingReadValueChunkWithBinary, and System.SR.Xml_MixingV1StreamingWithV2Binary.
Referenced by System.Xml.XmlTextReaderImpl.ReadContentAsBase64(), and System.Xml.XmlTextReaderImpl.ReadContentAsBinHex().