Terraria: System.Xml.XmlTextReaderImpl.FinishReadElementContentAsBinaryAsync
FinishReadElementContentAsBinaryAsync()
async Task System.Xml.XmlTextReaderImpl.FinishReadElementContentAsBinaryAsync () inline private
Definition at line 11502 of file XmlTextReaderImpl.cs.
    {
        await FinishReadContentAsBinaryAsync().ConfigureAwait(continueOnCapturedContext: false);
        if (_curNode.type != XmlNodeType.EndElement)
        {
            Throw(System.SR.Xml_InvalidNodeType, _curNode.type.ToString());
        }
        await _outerReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.XmlTextReaderImpl.FinishReadContentAsBinaryAsync(), System.Xml.XmlReader.ReadAsync(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.NodeData.type, and System.SR.Xml_InvalidNodeType.
Referenced by System.Xml.XmlTextReaderImpl.ReadAsync(), and System.Xml.XmlTextReaderImpl.SkipAsync().