Terraria: System.Xml.XmlTextReaderImpl.OpenUrl
OpenUrl()
void System.Xml.XmlTextReaderImpl.OpenUrl () inline private
Definition at line 3252 of file XmlTextReaderImpl.cs.
    {
        XmlResolver tempResolver = GetTempResolver();
        if (_ps.baseUri == null)
        {
            _ps.baseUri = tempResolver.ResolveUri(null, _url);
            _ps.baseUriStr = _ps.baseUri.ToString();
        }
        try
        {
            _ps.stream = (Stream)tempResolver.GetEntity(_ps.baseUri, null, typeof(Stream));
        }
        catch
        {
            SetErrorState();
            throw;
        }
        if (_ps.stream == null)
        {
            ThrowWithoutLineInfo(System.SR.Xml_CannotResolveUrl, _ps.baseUriStr);
        }
        InitStreamInput(_ps.baseUri, _ps.baseUriStr, _ps.stream, null);
        _reportedEncoding = _ps.encoding;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.XmlTextReaderImpl._url, System.Xml.XmlTextReaderImpl.ParsingState.baseUri, System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlTextReaderImpl.GetTempResolver(), System.Xml.XmlTextReaderImpl.InitStreamInput(), System.Xml.XmlTextReaderImpl.SetErrorState(), System.Xml.XmlTextReaderImpl.Stream, System.Xml.XmlTextReaderImpl.ParsingState.stream, System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), System.Uri.ToString(), and System.SR.Xml_CannotResolveUrl.
Referenced by System.Xml.XmlTextReaderImpl.GetRemainder(), and System.Xml.XmlTextReaderImpl.Read().