Terraria: System.Xml.XmlTextReaderImpl.CheckAsyncCall
CheckAsyncCall()
void System.Xml.XmlTextReaderImpl.CheckAsyncCall () inline private
Definition at line 8566 of file XmlTextReaderImpl.cs.
    {
        if (!_useAsync)
        {
            throw new InvalidOperationException(System.SR.Xml_ReaderAsyncNotSetException);
        }
    }
References System.Xml.XmlTextReaderImpl._useAsync, and System.SR.Xml_ReaderAsyncNotSetException.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_ParseCommentAsync(), System.Xml.XmlTextReaderImpl.DtdParserProxy_ParseNamedCharRefAsync(), System.Xml.XmlTextReaderImpl.DtdParserProxy_ParseNumericCharRefAsync(), System.Xml.XmlTextReaderImpl.DtdParserProxy_ParsePIAsync(), System.Xml.XmlTextReaderImpl.DtdParserProxy_PushEntityAsync(), System.Xml.XmlTextReaderImpl.DtdParserProxy_PushExternalSubsetAsync(), System.Xml.XmlTextReaderImpl.DtdParserProxy_ReadDataAsync(), System.Xml.XmlTextReaderImpl.GetValueAsync(), System.Xml.XmlTextReaderImpl.ReadAsync(), System.Xml.XmlTextReaderImpl.ReadContentAsBase64Async(), System.Xml.XmlTextReaderImpl.ReadContentAsBinHexAsync(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64Async(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBinHexAsync(), System.Xml.XmlTextReaderImpl.ReadValueChunkAsync(), and System.Xml.XmlTextReaderImpl.SkipAsync().