Terraria: System.Xml.XmlTextReaderImpl.ParseElementAsync
ParseElementAsync()
Task System.Xml.XmlTextReaderImpl.ParseElementAsync () inline private
Definition at line 10105 of file XmlTextReaderImpl.cs.
    {
        int num = _ps.charPos;
        char[] chars = _ps.chars;
        int num2 = -1;
        _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
        while (true)
        {
            if (XmlCharType.IsStartNCNameSingleChar(chars[num]))
            {
                num++;
                while (true)
                {
                    if (XmlCharType.IsNCNameSingleChar(chars[num]))
                    {
                        num++;
                        continue;
                    }
                    if (chars[num] != ':')
                    {
                        break;
                    }
                    if (num2 == -1)
                    {
                        goto IL_0088;
                    }
                    if (!_supportNamespaces)
                    {
                        num++;
                        continue;
                    }
                    goto IL_006c;
                }
                if (num + 1 < _ps.charsUsed)
                {
                    break;
                }
            }
            goto IL_00a0;
            IL_0088:
            num2 = num;
            num++;
            continue;
            IL_00a0:
            Task<(int, int)> task = ParseQNameAsync();
            return ParseElementAsync_ContinueWithSetElement(task);
            IL_006c:
            Throw(num, System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(':', '\0'));
            goto IL_00a0;
        }
        return ParseElementAsync_SetElement(num2, num);
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._supportNamespaces, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.int, System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.XmlCharType.IsStartNCNameSingleChar(), System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseElementAsync_ContinueWithSetElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync_SetElement(), System.Xml.XmlTextReaderImpl.ParseQNameAsync(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.task, System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_BadNameChar.
Referenced by System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync(), and System.Xml.XmlTextReaderImpl.ParseElementContentAsync().