Terraria: System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow
ParseAttributeValueSlow()
void System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow (int curPos, char quoteChar, NodeData attr) inline private
Definition at line 4881 of file XmlTextReaderImpl.cs.
    {
        int charRefEndPos = curPos;
        char[] chars = _ps.chars;
        int entityId = _ps.entityId;
        int num = 0;
        LineInfo lineInfo = new LineInfo(_ps.lineNo, _ps.LinePos);
        NodeData lastChunk = null;
        while (true)
        {
            if (XmlCharType.IsAttributeValueChar(chars[charRefEndPos]))
            {
                charRefEndPos++;
                continue;
            }
            if (charRefEndPos - _ps.charPos > 0)
            {
                _stringBuilder.Append(chars, _ps.charPos, charRefEndPos - _ps.charPos);
                _ps.charPos = charRefEndPos;
            }
            if (chars[charRefEndPos] == quoteChar && entityId == _ps.entityId)
            {
                break;
            }
            switch (chars[charRefEndPos])
            {
            case '\n':
                charRefEndPos++;
                OnNewLine(charRefEndPos);
                if (_normalize)
                {
                    _stringBuilder.Append(' ');
                    _ps.charPos++;
                }
                continue;
            case '\r':
                if (chars[charRefEndPos + 1] == '\n')
                {
                    charRefEndPos += 2;
                    if (_normalize)
                    {
                        _stringBuilder.Append(_ps.eolNormalized ? "  " : " ");
                        _ps.charPos = charRefEndPos;
                    }
                }
                else
                {
                    if (charRefEndPos + 1 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    charRefEndPos++;
                    if (_normalize)
                    {
                        _stringBuilder.Append(' ');
                        _ps.charPos = charRefEndPos;
                    }
                }
                OnNewLine(charRefEndPos);
                continue;
            case '\t':
                charRefEndPos++;
                if (_normalize)
                {
                    _stringBuilder.Append(' ');
                    _ps.charPos++;
                }
                continue;
            case '"':
            case '\'':
            case '>':
                charRefEndPos++;
                continue;
            case '<':
                Throw(charRefEndPos, System.SR.Xml_BadAttributeChar, XmlException.BuildCharExceptionArgs('<', '\0'));
                break;
            case '&':
            {
                if (charRefEndPos - _ps.charPos > 0)
                {
                    _stringBuilder.Append(chars, _ps.charPos, charRefEndPos - _ps.charPos);
                }
                _ps.charPos = charRefEndPos;
                int entityId2 = _ps.entityId;
                LineInfo lineInfo2 = new LineInfo(_ps.lineNo, _ps.LinePos + 1);
                switch (HandleEntityReference(isInAttributeValue: true, EntityExpandType.All, out charRefEndPos))
                {
                case EntityType.Unexpanded:
                    if (_parsingMode == ParsingMode.Full && _ps.entityId == entityId)
                    {
                        int num3 = _stringBuilder.Length - num;
                        if (num3 > 0)
{
                            NodeData nodeData3 = new NodeData();
                            nodeData3.lineInfo = lineInfo;
                            nodeData3.depth = attr.depth + 1;
                            nodeData3.SetValueNode(XmlNodeType.Text, _stringBuilder.ToString(num, num3));
                            AddAttributeChunkToList(attr, nodeData3, ref lastChunk);
                        }
                        _ps.charPos++;
                        string text = ParseEntityName();
                        NodeData nodeData4 = new NodeData();
                        nodeData4.lineInfo = lineInfo2;
                        nodeData4.depth = attr.depth + 1;
                        nodeData4.SetNamedNode(XmlNodeType.EntityReference, text);
                        AddAttributeChunkToList(attr, nodeData4, ref lastChunk);
                        _stringBuilder.Append('&');
                        _stringBuilder.Append(text);
                        _stringBuilder.Append(';');
                        num = _stringBuilder.Length;
                        lineInfo.Set(_ps.LineNo, _ps.LinePos);
                        _fullAttrCleanup = true;
                    }
                    else
                    {
                        _ps.charPos++;
                        ParseEntityName();
                    }
                    charRefEndPos = _ps.charPos;
                    break;
                case EntityType.ExpandedInAttribute:
                    if (_parsingMode == ParsingMode.Full && entityId2 == entityId)
                    {
                        int num2 = _stringBuilder.Length - num;
                        if (num2 > 0)
{
                            NodeData nodeData = new NodeData();
                            nodeData.lineInfo = lineInfo;
                            nodeData.depth = attr.depth + 1;
                            nodeData.SetValueNode(XmlNodeType.Text, _stringBuilder.ToString(num, num2));
                            AddAttributeChunkToList(attr, nodeData, ref lastChunk);
                        }
                        NodeData nodeData2 = new NodeData();
                        nodeData2.lineInfo = lineInfo2;
                        nodeData2.depth = attr.depth + 1;
                        nodeData2.SetNamedNode(XmlNodeType.EntityReference, _ps.entity.Name);
                        AddAttributeChunkToList(attr, nodeData2, ref lastChunk);
                        _fullAttrCleanup = true;
                    }
                    charRefEndPos = _ps.charPos;
                    break;
                default:
                    charRefEndPos = _ps.charPos;
                    break;
                case EntityType.CharacterDec:
                case EntityType.CharacterHex:
                case EntityType.CharacterNamed:
                    break;
                }
                chars = _ps.chars;
                continue;
            }
            default:
            {
                if (charRefEndPos == _ps.charsUsed)
                {
                    break;
                }
                char ch = chars[charRefEndPos];
                if (XmlCharType.IsHighSurrogate(ch))
                {
                    if (charRefEndPos + 1 == _ps.charsUsed)
                    {
                        break;
                    }
                    charRefEndPos++;
                    if (XmlCharType.IsLowSurrogate(chars[charRefEndPos]))
                    {
                        charRefEndPos++;
                        continue;
                    }
                }
                ThrowInvalidChar(chars, _ps.charsUsed, charRefEndPos);
                break;
            }
            }
            if (ReadData() == 0)
            {
                if (_ps.charsUsed - _ps.charPos > 0)
                {
                    if (_ps.chars[_ps.charPos] != '\r')
                    {
                        Throw(System.SR.Xml_UnexpectedEOF1);
                    }
                }
                else
                {
                    if (!InEntity)
                    {
                        if (_fragmentType == XmlNodeType.Attribute)
{
                            if (entityId != _ps.entityId)
{
                                Throw(System.SR.Xml_EntityRefNesting);
                            }
                            break;
                        }
                        Throw(System.SR.Xml_UnclosedQuote);
                    }
                    if (HandleEntityEnd(checkEntityNesting: true))
                    {
                        Throw(System.SR.Xml_InternalError);
                    }
                    if (entityId == _ps.entityId)
                    {
                        num = _stringBuilder.Length;
                        lineInfo.Set(_ps.LineNo, _ps.LinePos);
                    }
                }
            }
            charRefEndPos = _ps.charPos;
            chars = _ps.chars;
        }
        if (attr.nextAttrValueChunk != null)
        {
            int num4 = _stringBuilder.Length - num;
            if (num4 > 0)
            {
                NodeData nodeData5 = new NodeData();
                nodeData5.lineInfo = lineInfo;
                nodeData5.depth = attr.depth + 1;
                nodeData5.SetValueNode(XmlNodeType.Text, _stringBuilder.ToString(num, num4));
                AddAttributeChunkToList(attr, nodeData5, ref lastChunk);
            }
        }
        _ps.charPos = charRefEndPos + 1;
        attr.SetValue(_stringBuilder.ToString());
        _stringBuilder.Length = 0;
    }
References System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._fullAttrCleanup, System.Xml.XmlTextReaderImpl._normalize, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Xml.XmlTextReaderImpl.AddAttributeChunkToList(), System.Text.StringBuilder.Append(), System.Xml.XmlException.BuildCharExceptionArgs(), System.ch, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.entity, System.Xml.XmlTextReaderImpl.ParsingState.entityId, System.Xml.XmlTextReaderImpl.ParsingState.eolNormalized, System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.XmlTextReaderImpl.HandleEntityReference(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Text.StringBuilder.Length, System.Xml.XmlTextReaderImpl.ParsingState.lineNo, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.IDtdEntityInfo.Name, System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.ParseEntityName(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.LineInfo.Set(), System.text, System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), System.Text.StringBuilder.ToString(), System.SR.Xml_BadAttributeChar, System.SR.Xml_EntityRefNesting, System.SR.Xml_InternalError, System.SR.Xml_UnclosedQuote, and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.ParseAttributes(), and System.Xml.XmlTextReaderImpl.ParseFragmentAttribute().