Terraria: System.Xml.XmlTextReaderImpl.SetupReadContentAsBinaryState
SetupReadContentAsBinaryState()
void System.Xml.XmlTextReaderImpl.SetupReadContentAsBinaryState (ParsingFunction inReadBinaryFunction) inline private
Definition at line 8057 of file XmlTextReaderImpl.cs.
    {
        if (_parsingFunction == ParsingFunction.PartialTextValue)
        {
            _incReadState = IncrementalReadState.ReadContentAsBinary_OnPartialValue;
        }
        else
        {
            _incReadState = IncrementalReadState.ReadContentAsBinary_OnCachedValue;
            _nextNextParsingFunction = _nextParsingFunction;
            _nextParsingFunction = _parsingFunction;
        }
        _readValueOffset = 0;
        _parsingFunction = inReadBinaryFunction;
    }
References System.Xml.XmlTextReaderImpl._incReadState, System.Xml.XmlTextReaderImpl._nextNextParsingFunction, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readValueOffset, and System.Xml.Dictionary.
Referenced by System.Xml.XmlTextReaderImpl.InitReadContentAsBinary(), System.Xml.XmlTextReaderImpl.InitReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinary(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.ReadContentAsBinary(), and System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync().