Terraria: System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubsetAsync
PushExternalEntityOrSubsetAsync()
async Task System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubsetAsync (string publicId, string systemId, Uri baseUri, string entityName) inline private
Definition at line 12684 of file XmlTextReaderImpl.cs.
    {
        Uri uri;
        if (!string.IsNullOrEmpty(publicId))
        {
            try
            {
                uri = _xmlResolver.ResolveUri(baseUri, publicId);
                if (await OpenAndPushAsync(uri).ConfigureAwait(continueOnCapturedContext: false))
                {
                    return;
                }
            }
            catch (Exception)
            {
            }
        }
        uri = _xmlResolver.ResolveUri(baseUri, systemId);
        try
        {
            if (await OpenAndPushAsync(uri).ConfigureAwait(continueOnCapturedContext: false))
            {
                return;
            }
        }
        catch (Exception ex2)
        {
            if (_v1Compat)
            {
                throw;
            }
            string message = ex2.Message;
            Throw(new XmlException((entityName == null) ? System.SR.Xml_ErrorOpeningExternalDtd : System.SR.Xml_ErrorOpeningExternalEntity, new string[2]
            {
                uri.ToString(),
                message
            }, ex2, 0, 0));
        }
        if (entityName == null)
        {
            ThrowWithoutLineInfo(System.SR.Xml_CannotResolveExternalSubset, new string[2]
            {
                (publicId != null) ? publicId : string.Empty,
                systemId
            }, null);
        }
        else
        {
            Throw((_dtdProcessing == DtdProcessing.Ignore) ? System.SR.Xml_CannotResolveEntityDtdIgnored : System.SR.Xml_CannotResolveEntity, entityName);
        }
    }
References System.Xml.XmlTextReaderImpl._dtdProcessing, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl._xmlResolver, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.OpenAndPushAsync(), System.Xml.XmlResolver.ResolveUri(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), System.Uri.ToString(), System.SR.Xml_CannotResolveEntity, System.SR.Xml_CannotResolveEntityDtdIgnored, System.SR.Xml_CannotResolveExternalSubset, System.SR.Xml_ErrorOpeningExternalDtd, System.SR.Xml_ErrorOpeningExternalEntity, and System.Xml.XmlException.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_PushExternalSubsetAsync(), and System.Xml.XmlTextReaderImpl.PushExternalEntityAsync().