Terraria: System.Xml.XmlTextReaderImpl.FinishInit
FinishInit()
void System.Xml.XmlTextReaderImpl.FinishInit () inline private
Definition at line 1963 of file XmlTextReaderImpl.cs.
    {
        switch (_laterInitParam.initType)
        {
        case InitInputType.UriString:
            FinishInitUriString();
            break;
        case InitInputType.Stream:
            FinishInitStream();
            break;
        case InitInputType.TextReader:
            FinishInitTextReader();
            break;
        }
    }
References System.Xml.XmlTextReaderImpl._laterInitParam, System.Xml.XmlTextReaderImpl.FinishInitStream(), System.Xml.XmlTextReaderImpl.FinishInitTextReader(), System.Xml.XmlTextReaderImpl.FinishInitUriString(), and System.Xml.XmlTextReaderImpl.LaterInitParam.initType.
Referenced by System.Xml.XmlTextReaderImpl.Read().