Terraria: System.Xml.XmlTextReaderImpl.AddAttributeNoChecks
AddAttributeNoChecks()
NodeData System.Xml.XmlTextReaderImpl.AddAttributeNoChecks (string name, int attrDepth) inline private
Definition at line 6962 of file XmlTextReaderImpl.cs.
    {
        NodeData nodeData = AddNode(_index + _attrCount + 1, attrDepth);
        nodeData.SetNamedNode(XmlNodeType.Attribute, _nameTable.Add(name));
        _attrCount++;
        return nodeData;
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlNameTable.Add(), System.Xml.XmlTextReaderImpl.AddNode(), and System.Xml.Dictionary.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_OnPublicId(), System.Xml.XmlTextReaderImpl.DtdParserProxy_OnSystemId(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), and System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync().