Terraria: System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ParseEntity
ParseDocumentContentAsync_ParseEntity()
async Task< bool > System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ParseEntity () inline private
Definition at line 9907 of file XmlTextReaderImpl.cs.
    {
        int charPos = _ps.charPos;
        if (_fragmentType == XmlNodeType.Document)
        {
            Throw(charPos, System.SR.Xml_InvalidRootData);
            return false;
        }
        if (_fragmentType == XmlNodeType.None)
        {
            _fragmentType = XmlNodeType.Element;
        }
        switch ((await HandleEntityReferenceAsync(isInAttributeValue: false, EntityExpandType.OnlyGeneral).ConfigureAwait(continueOnCapturedContext: false)).Item2)
        {
        case EntityType.Unexpanded:
            if (_parsingFunction == ParsingFunction.EntityReference)
            {
                _parsingFunction = _nextParsingFunction;
            }
            await ParseEntityReferenceAsync().ConfigureAwait(continueOnCapturedContext: false);
            return true;
        case EntityType.CharacterDec:
        case EntityType.CharacterHex:
        case EntityType.CharacterNamed:
            if (await ParseTextAsync().ConfigureAwait(continueOnCapturedContext: false))
            {
                return true;
            }
            return await ParseDocumentContentAsync().ConfigureAwait(continueOnCapturedContext: false);
        default:
            return await ParseDocumentContentAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlTextReaderImpl.HandleEntityReferenceAsync(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync(), System.Xml.XmlTextReaderImpl.ParseEntityReferenceAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_InvalidRootData.
Referenced by System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync().