Terraria: System.Xml.XmlTextReaderImpl.ZeroEndingStream
ZeroEndingStream()
bool System.Xml.XmlTextReaderImpl.ZeroEndingStream (int pos) inline private
Definition at line 7963 of file XmlTextReaderImpl.cs.
    {
        if (_v1Compat && pos == _ps.charsUsed - 1 && _ps.chars[pos] == '\0' && ReadData() == 0 && _ps.isStreamEof)
        {
            _ps.charsUsed--;
            return true;
        }
        return false;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.XmlTextReaderImpl.ParsingState.isStreamEof, and System.Xml.XmlTextReaderImpl.ReadData().
Referenced by System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace(), and System.Xml.XmlTextReaderImpl.ParseText().