Terraria: System.Xml.XmlTextReaderImpl.Read
Read()
override bool System.Xml.XmlTextReaderImpl.Read () inline
Definition at line 1979 of file XmlTextReaderImpl.cs.
    {
        if (_laterInitParam != null)
        {
            FinishInit();
        }
        while (true)
        {
            switch (_parsingFunction)
            {
            case ParsingFunction.ElementContent:
                return ParseElementContent();
            case ParsingFunction.DocumentContent:
                return ParseDocumentContent();
            case ParsingFunction.OpenUrl:
                OpenUrl();
                goto case ParsingFunction.SwitchToInteractiveXmlDecl;
            case ParsingFunction.SwitchToInteractive:
                _readState = ReadState.Interactive;
                _parsingFunction = _nextParsingFunction;
                break;
            case ParsingFunction.SwitchToInteractiveXmlDecl:
                _readState = ReadState.Interactive;
                _parsingFunction = _nextParsingFunction;
                if (ParseXmlDeclaration(isTextDecl: false))
                {
                    _reportedEncoding = _ps.encoding;
                    return true;
                }
                _reportedEncoding = _ps.encoding;
                break;
            case ParsingFunction.ResetAttributesRootLevel:
                ResetAttributes();
                _curNode = _nodes[_index];
                _parsingFunction = ((_index == 0) ? ParsingFunction.DocumentContent : ParsingFunction.ElementContent);
                break;
            case ParsingFunction.MoveToElementContent:
                ResetAttributes();
                _index++;
                _curNode = AddNode(_index, _index);
                _parsingFunction = ParsingFunction.ElementContent;
                break;
            case ParsingFunction.PopElementContext:
                PopElementContext();
                _parsingFunction = _nextParsingFunction;
                break;
            case ParsingFunction.PopEmptyElementContext:
                _curNode = _nodes[_index];
                _curNode.IsEmptyElement = false;
                ResetAttributes();
                PopElementContext();
                _parsingFunction = _nextParsingFunction;
                break;
            case ParsingFunction.EntityReference:
                _parsingFunction = _nextParsingFunction;
                ParseEntityReference();
                return true;
            case ParsingFunction.ReportEndEntity:
                SetupEndEntityNodeInContent();
                _parsingFunction = _nextParsingFunction;
                return true;
            case ParsingFunction.AfterResolveEntityInContent:
                _curNode = AddNode(_index, _index);
                _reportedEncoding = _ps.encoding;
                _reportedBaseUri = _ps.baseUriStr;
                _parsingFunction = _nextParsingFunction;
                break;
            case ParsingFunction.AfterResolveEmptyEntityInContent:
                _curNode = AddNode(_index, _index);
                _curNode.SetValueNode(XmlNodeType.Text, string.Empty);
                _curNode.SetLineInfo(_ps.lineNo, _ps.LinePos);
                _reportedEncoding = _ps.encoding;
                _reportedBaseUri = _ps.baseUriStr;
                _parsingFunction = _nextParsingFunction;
                return true;
            case ParsingFunction.InReadAttributeValue:
                FinishAttributeValueIterator();
                _curNode = _nodes[_index];
                break;
            case ParsingFunction.InIncrementalRead:
                FinishIncrementalRead();
                return true;
            case ParsingFunction.FragmentAttribute:
                return ParseFragmentAttribute();
            case ParsingFunction.XmlDeclarationFragment:
                ParseXmlDeclarationFragment();
                _parsingFunction = ParsingFunction.GoToEof;
                return true;
            case ParsingFunction.GoToEof:
                OnEof();
                return false;
            case ParsingFunction.Error:
            case ParsingFunction.Eof:
            case ParsingFunction.ReaderClosed:
                return false;
            case ParsingFunction.NoData:
                ThrowWithoutLineInfo(System.SR.Xml_MissingRoot);
                return false;
            case ParsingFunction.PartialTextValue:
                SkipPartialTextValue();
                break;
            case ParsingFunction.InReadValueChunk:
                FinishReadValueChunk();
                break;
            case ParsingFunction.InReadContentAsBinary:
                FinishReadContentAsBinary();
                break;
            case ParsingFunction.InReadElementContentAsBinary:
                FinishReadElementContentAsBinary();
                break;
            }
        }
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._laterInitParam, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._readState, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.XmlTextReaderImpl.AddNode(), System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlTextReaderImpl.FinishAttributeValueIterator(), System.Xml.XmlTextReaderImpl.FinishIncrementalRead(), System.Xml.XmlTextReaderImpl.FinishInit(), System.Xml.XmlTextReaderImpl.FinishReadContentAsBinary(), System.Xml.XmlTextReaderImpl.FinishReadElementContentAsBinary(), System.Xml.XmlTextReaderImpl.FinishReadValueChunk(), System.Xml.XmlTextReaderImpl.ParsingState.lineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.OnEof(), System.Xml.XmlTextReaderImpl.OpenUrl(), System.Xml.XmlTextReaderImpl.ParseDocumentContent(), System.Xml.XmlTextReaderImpl.ParseElementContent(), System.Xml.XmlTextReaderImpl.ParseEntityReference(), System.Xml.XmlTextReaderImpl.ParseFragmentAttribute(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationFragment(), System.Xml.XmlTextReaderImpl.PopElementContext(), System.Xml.XmlTextReaderImpl.ResetAttributes(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent(), System.Xml.XmlTextReaderImpl.NodeData.SetValueNode(), System.Xml.XmlTextReaderImpl.SkipPartialTextValue(), System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), and System.SR.Xml_MissingRoot.
Referenced by System.Xml.XmlTextReader.Read().