Terraria: System.Xml.XmlTextReaderImpl.ThrowExpectingWhitespace
ThrowExpectingWhitespace()
void System.Xml.XmlTextReaderImpl.ThrowExpectingWhitespace (int pos) inline private
Definition at line 7916 of file XmlTextReaderImpl.cs.
    {
        string text = ParseUnexpectedToken(pos);
        if (text == null)
        {
            Throw(pos, System.SR.Xml_UnexpectedEOF1);
        }
        else
        {
            Throw(pos, System.SR.Xml_ExpectingWhiteSpace, text);
        }
    }
References System.Xml.XmlTextReaderImpl.ParseUnexpectedToken(), System.text, System.Xml.XmlTextReaderImpl.Throw(), System.SR.Xml_ExpectingWhiteSpace, and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseDoctypeDecl(), System.Xml.XmlTextReaderImpl.ParseDoctypeDeclAsync(), System.Xml.XmlTextReaderImpl.SkipDtd(), and System.Xml.XmlTextReaderImpl.SkipDtdAsync().