Terraria: System.Xml.XmlTextReaderImpl.AttributeDuplCheck
AttributeDuplCheck()
void System.Xml.XmlTextReaderImpl.AttributeDuplCheck () inline private
Definition at line 4781 of file XmlTextReaderImpl.cs.
    {
        if (_attrCount < 250)
        {
            for (int i = _index + 1; i < _index + 1 + _attrCount; i++)
            {
                NodeData nodeData = _nodes[i];
                for (int j = i + 1; j < _index + 1 + _attrCount; j++)
                {
                    if (Ref.Equal(nodeData.localName, _nodes[j].localName) && Ref.Equal(nodeData.ns, _nodes[j].ns))
                    {
                        Throw(System.SR.Xml_DupAttributeName, _nodes[j].GetNameWPrefix(_nameTable), _nodes[j].LineNo, _nodes[j].LinePos);
                    }
                }
            }
            return;
        }
        if (_attrDuplSortingArray == null || _attrDuplSortingArray.Length < _attrCount)
        {
            _attrDuplSortingArray = new NodeData[_attrCount];
        }
        Array.Copy(_nodes, _index + 1, _attrDuplSortingArray, 0, _attrCount);
        Array.Sort(_attrDuplSortingArray, 0, _attrCount);
        NodeData nodeData2 = _attrDuplSortingArray[0];
        for (int k = 1; k < _attrCount; k++)
        {
            NodeData nodeData3 = _attrDuplSortingArray[k];
            if (Ref.Equal(nodeData2.localName, nodeData3.localName) && Ref.Equal(nodeData2.ns, nodeData3.ns))
            {
                Throw(System.SR.Xml_DupAttributeName, nodeData3.GetNameWPrefix(_nameTable), nodeData3.LineNo, nodeData3.LinePos);
            }
            nodeData2 = nodeData3;
        }
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._attrDuplSortingArray, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._nodes, System.Array.Copy(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.XmlTextReaderImpl.NodeData.GetNameWPrefix(), System.Xml.XmlTextReaderImpl.NodeData.LineNo, System.Xml.XmlTextReaderImpl.NodeData.LinePos, System.Xml.XmlTextReaderImpl.NodeData.localName, System.Xml.XmlTextReaderImpl.NodeData.ns, System.Array.Sort(), System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_DupAttributeName.
Referenced by System.Xml.XmlTextReaderImpl.ParseAttributes(), and System.Xml.XmlTextReaderImpl.ParseAttributesAsync().