Terraria: System.Xml.XmlTextReaderImpl.ReadContentAsBase64_AsyncHelper
ReadContentAsBase64_AsyncHelper()
async Task< int > System.Xml.XmlTextReaderImpl.ReadContentAsBase64_AsyncHelper (Task< bool > task, byte[] buffer, int index, int count) inline private
Definition at line 8851 of file XmlTextReaderImpl.cs.
    {
        if (!(await task.ConfigureAwait(continueOnCapturedContext: false)))
        {
            return 0;
        }
        InitBase64Decoder();
        return await ReadContentAsBinaryAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
    }
References System.buffer, System.count, System.index, System.Xml.XmlTextReaderImpl.InitBase64Decoder(), System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync(), and System.task.
Referenced by System.Xml.XmlTextReaderImpl.ReadContentAsBase64Async().