Terraria: System.Xml.XmlTextReaderImpl.ParseDtd
ParseDtd()
void System.Xml.XmlTextReaderImpl.ParseDtd () inline private
Definition at line 6227 of file XmlTextReaderImpl.cs.
    {
        IDtdParser dtdParser = DtdParser.Create();
        _dtdInfo = dtdParser.ParseInternalDtd(new DtdParserProxy(this), saveInternalSubset: true);
        if ((_validatingReaderCompatFlag || !_v1Compat) && (_dtdInfo.HasDefaultAttributes || _dtdInfo.HasNonCDataAttributes))
        {
            _addDefaultAttributesAndNormalize = true;
        }
        _curNode.SetNamedNode(XmlNodeType.DocumentType, _dtdInfo.Name.ToString(), string.Empty, null);
        _curNode.SetValue(_dtdInfo.InternalDtdSubset);
    }
References System.Xml.XmlTextReaderImpl._addDefaultAttributesAndNormalize, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._dtdInfo, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl._validatingReaderCompatFlag, System.Xml.DtdParser.Create(), System.Xml.Dictionary, System.Xml.IDtdInfo.HasNonCDataAttributes, System.Xml.IDtdInfo.InternalDtdSubset, System.Xml.IDtdInfo.Name, System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode(), System.Xml.XmlTextReaderImpl.NodeData.SetValue(), and System.Xml.XmlQualifiedName.ToString().
Referenced by System.Xml.XmlTextReaderImpl.ParseDoctypeDecl().