Terraria: System.Xml.XmlTextReaderImpl.DtdParserProxy_PushExternalSubsetAsync
DtdParserProxy_PushExternalSubsetAsync()
async Task< bool > System.Xml.XmlTextReaderImpl.DtdParserProxy_PushExternalSubsetAsync (string systemId, string publicId) inline package
Definition at line 9272 of file XmlTextReaderImpl.cs.
    {
        CheckAsyncCall();
        if (IsResolverNull)
        {
            return false;
        }
        if (_ps.baseUri == null && !string.IsNullOrEmpty(_ps.baseUriStr))
        {
            _ps.baseUri = _xmlResolver.ResolveUri(null, _ps.baseUriStr);
        }
        await PushExternalEntityOrSubsetAsync(publicId, systemId, _ps.baseUri, null).ConfigureAwait(continueOnCapturedContext: false);
        _ps.entity = null;
        _ps.entityId = 0;
        int initialPos = _ps.charPos;
        if (_v1Compat)
        {
            await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false);
        }
        if (!(await ParseXmlDeclarationAsync(isTextDecl: true).ConfigureAwait(continueOnCapturedContext: false)))
        {
            _ps.charPos = initialPos;
        }
        return true;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl._xmlResolver, System.Xml.XmlTextReaderImpl.ParsingState.baseUri, System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.CheckAsyncCall(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespacesAsync(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubsetAsync(), and System.Xml.XmlResolver.ResolveUri().
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy.PushExternalSubsetAsync().