Terraria: System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal
AddDefaultAttributeInternal()
NodeData System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal (string localName, string ns, string prefix, string value, int lineNo, int linePos, int valueLineNo, int valueLinePos, bool isXmlAttribute) inline private
Definition at line 8195 of file XmlTextReaderImpl.cs.
    {
        NodeData nodeData = AddAttribute(localName, prefix, (prefix.Length > 0) ? null : localName);
        if (ns != null)
        {
            nodeData.ns = ns;
        }
        nodeData.SetValue(value);
        nodeData.IsDefaultAttribute = true;
        nodeData.lineInfo.Set(lineNo, linePos);
        nodeData.lineInfo2.Set(valueLineNo, valueLinePos);
        if (nodeData.prefix.Length == 0)
        {
            if (Ref.Equal(nodeData.localName, _xmlNs))
            {
                OnDefaultNamespaceDecl(nodeData);
                if (!_attrNeedNamespaceLookup && _nodes[_index].prefix.Length == 0)
                {
                    _nodes[_index].ns = _xmlContext.defaultNamespace;
                }
            }
        }
        else if (Ref.Equal(nodeData.prefix, _xmlNs))
        {
            OnNamespaceDecl(nodeData);
            if (!_attrNeedNamespaceLookup)
            {
                string localName2 = nodeData.localName;
                for (int i = _index; i < _index + _attrCount + 1; i++)
                {
                    if (_nodes[i].prefix.Equals(localName2))
                    {
                        _nodes[i].ns = _namespaceManager.LookupNamespace(localName2);
                    }
                }
            }
        }
        else if (isXmlAttribute)
        {
            OnXmlReservedAttribute(nodeData);
        }
        _fullAttrCleanup = true;
        return nodeData;
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._attrNeedNamespaceLookup, System.Xml.XmlTextReaderImpl._fullAttrCleanup, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._namespaceManager, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._xmlContext, System.Xml.XmlTextReaderImpl._xmlNs, System.Xml.XmlTextReaderImpl.AddAttribute(), System.Xml.XmlTextReaderImpl.XmlContext.defaultNamespace, System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.XmlNamespaceManager.LookupNamespace(), System.Xml.XmlTextReaderImpl.NodeData.ns, System.Xml.XmlTextReaderImpl.OnDefaultNamespaceDecl(), System.Xml.XmlTextReaderImpl.OnNamespaceDecl(), System.Xml.XmlTextReaderImpl.OnXmlReservedAttribute(), System.prefix, and System.value.
Referenced by System.Xml.XmlTextReaderImpl.AddDefaultAttributeDtd(), and System.Xml.XmlTextReaderImpl.AddDefaultAttributeNonDtd().