Terraria: System.Xml.XmlTextReaderImpl.SkipDtd
SkipDtd()
void System.Xml.XmlTextReaderImpl.SkipDtd () inline private
Definition at line 6239 of file XmlTextReaderImpl.cs.
    {
        int colonPos;
        int charPos = ParseQName(out colonPos);
        _ps.charPos = charPos;
        EatWhitespaces(null);
        if (_ps.chars[_ps.charPos] == 'P')
        {
            while (_ps.charsUsed - _ps.charPos < 6)
            {
                if (ReadData() == 0)
                {
                    Throw(System.SR.Xml_UnexpectedEOF1);
                }
            }
            if (!XmlConvert.StrEqual(_ps.chars, _ps.charPos, 6, "PUBLIC"))
            {
                ThrowUnexpectedToken("PUBLIC");
            }
            _ps.charPos += 6;
            if (EatWhitespaces(null) == 0)
            {
                ThrowExpectingWhitespace(_ps.charPos);
            }
            SkipPublicOrSystemIdLiteral();
            if (EatWhitespaces(null) == 0)
            {
                ThrowExpectingWhitespace(_ps.charPos);
            }
            SkipPublicOrSystemIdLiteral();
            EatWhitespaces(null);
        }
        else if (_ps.chars[_ps.charPos] == 'S')
        {
            while (_ps.charsUsed - _ps.charPos < 6)
            {
                if (ReadData() == 0)
                {
                    Throw(System.SR.Xml_UnexpectedEOF1);
                }
            }
            if (!XmlConvert.StrEqual(_ps.chars, _ps.charPos, 6, "SYSTEM"))
            {
                ThrowUnexpectedToken("SYSTEM");
            }
            _ps.charPos += 6;
            if (EatWhitespaces(null) == 0)
            {
                ThrowExpectingWhitespace(_ps.charPos);
            }
            SkipPublicOrSystemIdLiteral();
            EatWhitespaces(null);
        }
        else if (_ps.chars[_ps.charPos] != '[' && _ps.chars[_ps.charPos] != '>')
        {
            Throw(System.SR.Xml_ExpectExternalOrClose);
        }
        if (_ps.chars[_ps.charPos] == '[')
        {
            _ps.charPos++;
            SkipUntil(']', recognizeLiterals: true);
            EatWhitespaces(null);
            if (_ps.chars[_ps.charPos] != '>')
            {
                ThrowUnexpectedToken(">");
            }
        }
        else if (_ps.chars[_ps.charPos] == '>')
        {
            _curNode.SetValue(string.Empty);
        }
        else
        {
            Throw(System.SR.Xml_ExpectSubOrClose);
        }
        _ps.charPos++;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespaces(), System.Xml.XmlTextReaderImpl.ParseQName(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.NodeData.SetValue(), System.Xml.XmlTextReaderImpl.SkipPublicOrSystemIdLiteral(), System.Xml.XmlTextReaderImpl.SkipUntil(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowExpectingWhitespace(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.SR.Xml_ExpectExternalOrClose, System.SR.Xml_ExpectSubOrClose, and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.ParseDoctypeDecl().