Terraria: System.Xml.XmlTextReaderImpl.ParseElementAsync_SetElement
ParseElementAsync_SetElement()
Task System.Xml.XmlTextReaderImpl.ParseElementAsync_SetElement (int colonPos, int pos) inline private
Definition at line 10174 of file XmlTextReaderImpl.cs.
    {
        char[] chars = _ps.chars;
        _namespaceManager.PushScope();
        if (colonPos == -1 || !_supportNamespaces)
        {
            _curNode.SetNamedNode(XmlNodeType.Element, _nameTable.Add(chars, _ps.charPos, pos - _ps.charPos));
        }
        else
        {
            int charPos = _ps.charPos;
            int num = colonPos - charPos;
            if (num == _lastPrefix.Length && XmlConvert.StrEqual(chars, charPos, num, _lastPrefix))
            {
                _curNode.SetNamedNode(XmlNodeType.Element, _nameTable.Add(chars, colonPos + 1, pos - colonPos - 1), _lastPrefix, null);
            }
            else
            {
                _curNode.SetNamedNode(XmlNodeType.Element, _nameTable.Add(chars, colonPos + 1, pos - colonPos - 1), _nameTable.Add(chars, _ps.charPos, num), null);
                _lastPrefix = _curNode.prefix;
            }
        }
        char ch = chars[pos];
        bool flag = XmlCharType.IsWhiteSpace(ch);
        _ps.charPos = pos;
        if (flag)
        {
            return ParseAttributesAsync();
        }
        return ParseElementAsync_NoAttributes();
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._lastPrefix, System.Xml.XmlTextReaderImpl._namespaceManager, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._supportNamespaces, System.Xml.XmlNameTable.Add(), System.ch, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.Dictionary, System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseElementAsync_NoAttributes(), System.Xml.XmlTextReaderImpl.NodeData.prefix, System.Xml.XmlNamespaceManager.PushScope(), System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode(), and System.Xml.XmlConvert.StrEqual().
Referenced by System.Xml.XmlTextReaderImpl._ParseElementAsync_ContinueWithSetElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync(), and System.Xml.XmlTextReaderImpl.ParseElementAsync_ContinueWithSetElement().