Terraria: System.Xml.XmlTextReaderImpl.HandleEntityEnd
HandleEntityEnd()
bool System.Xml.XmlTextReaderImpl.HandleEntityEnd (bool checkEntityNesting) inline private
Definition at line 5719 of file XmlTextReaderImpl.cs.
    {
        if (_parsingStatesStackTop == -1)
        {
            Throw(System.SR.Xml_InternalError);
        }
        if (_ps.entityResolvedManually)
        {
            _index--;
            if (checkEntityNesting && _ps.entityId != _nodes[_index].entityId)
            {
                Throw(System.SR.Xml_IncompleteEntity);
            }
            _lastEntity = _ps.entity;
            PopEntity();
            return true;
        }
        if (checkEntityNesting && _ps.entityId != _nodes[_index].entityId)
        {
            Throw(System.SR.Xml_IncompleteEntity);
        }
        PopEntity();
        _reportedEncoding = _ps.encoding;
        _reportedBaseUri = _ps.baseUriStr;
        return false;
    }
References System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._lastEntity, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._parsingStatesStackTop, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlTextReaderImpl.ParsingState.entity, System.Xml.XmlTextReaderImpl.ParsingState.entityId, System.Xml.XmlTextReaderImpl.NodeData.entityId, System.Xml.XmlTextReaderImpl.ParsingState.entityResolvedManually, System.Xml.XmlTextReaderImpl.PopEntity(), System.Xml.XmlTextReaderImpl.Throw(), System.SR.Xml_IncompleteEntity, and System.SR.Xml_InternalError.
Referenced by System.Xml.XmlTextReaderImpl.FinishAttributeValueIterator(), System.Xml.XmlTextReaderImpl.GetRemainder(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync(), System.Xml.XmlTextReaderImpl.ParseDocumentContent(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(), System.Xml.XmlTextReaderImpl.ParseElementContent(), System.Xml.XmlTextReaderImpl.ParseElementContent_ReadData(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseTextAsync_ReadData(), and System.Xml.XmlTextReaderImpl.ResetState().