Terraria: System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64
ReadElementContentAsBase64()
override int System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64 (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 2378 of file XmlTextReaderImpl.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (_parsingFunction == ParsingFunction.InReadElementContentAsBinary)
        {
            if (_incReadDecoder == _base64Decoder)
            {
                return ReadElementContentAsBinary(buffer, index, count);
            }
        }
        else
        {
            if (_readState != ReadState.Interactive)
            {
                return 0;
            }
            if (_parsingFunction == ParsingFunction.InReadContentAsBinary)
            {
                throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
            }
            if (_curNode.type != XmlNodeType.Element)
            {
                throw CreateReadElementContentAsException("ReadElementContentAsBinHex");
            }
            if (!InitReadElementContentAsBinary())
            {
                return 0;
            }
        }
        InitBase64Decoder();
        return ReadElementContentAsBinary(buffer, index, count);
    }
References System.Xml.XmlTextReaderImpl._base64Decoder, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readState, System.buffer, System.count, System.Xml.XmlReader.CreateReadElementContentAsException(), System.index, System.Xml.XmlTextReaderImpl.InitBase64Decoder(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinary(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBinary(), System.Xml.XmlTextReaderImpl.NodeData.type, and System.SR.Xml_MixingBinaryContentMethods.
Referenced by System.Xml.XmlTextReader.ReadElementContentAsBase64().