Terraria: System.Xml.XmlTextReaderImpl.AddAttribute
AddAttribute() [1/2]
NodeData System.Xml.XmlTextReaderImpl.AddAttribute (int endNamePos, int colonPos) inline private
Definition at line 6970 of file XmlTextReaderImpl.cs.
    {
        if (colonPos == -1 || !_supportNamespaces)
        {
            string text = _nameTable.Add(_ps.chars, _ps.charPos, endNamePos - _ps.charPos);
            return AddAttribute(text, string.Empty, text);
        }
        _attrNeedNamespaceLookup = true;
        int charPos = _ps.charPos;
        int num = colonPos - charPos;
        if (num != _lastPrefix.Length || !XmlConvert.StrEqual(_ps.chars, charPos, num, _lastPrefix))
        {
            return AddAttribute(prefix: _lastPrefix = _nameTable.Add(_ps.chars, charPos, num), localName: _nameTable.Add(_ps.chars, colonPos + 1, endNamePos - colonPos - 1), nameWPrefix: null);
        }
        return AddAttribute(_nameTable.Add(_ps.chars, colonPos + 1, endNamePos - colonPos - 1), _lastPrefix, null);
    }
References System.Xml.XmlTextReaderImpl._attrNeedNamespaceLookup, System.Xml.XmlTextReaderImpl._lastPrefix, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._supportNamespaces, System.Xml.XmlNameTable.Add(), System.Xml.XmlTextReaderImpl.AddAttribute(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.prefix, System.Xml.XmlConvert.StrEqual(), and System.text.
Referenced by System.Xml.XmlTextReaderImpl.AddAttribute(), System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal(), System.Xml.XmlTextReaderImpl.ParseAttributes(), and System.Xml.XmlTextReaderImpl.ParseAttributesAsync().