Terraria: System.Xml.XmlTextReaderImpl.ReadAsync
ReadAsync()
override Task< bool > System.Xml.XmlTextReaderImpl.ReadAsync () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 8668 of file XmlTextReaderImpl.cs.
    {
        CheckAsyncCall();
        if (_laterInitParam != null)
        {
            return FinishInitAsync().CallBoolTaskFuncWhenFinishAsync((XmlTextReaderImpl thisRef) => thisRef.ReadAsync(), this);
        }
        while (true)
        {
            switch (_parsingFunction)
            {
            case ParsingFunction.ElementContent:
                return ParseElementContentAsync();
            case ParsingFunction.DocumentContent:
                return ParseDocumentContentAsync();
            case ParsingFunction.SwitchToInteractive:
                _readState = ReadState.Interactive;
                _parsingFunction = _nextParsingFunction;
                break;
            case ParsingFunction.SwitchToInteractiveXmlDecl:
                return ReadAsync_SwitchToInteractiveXmlDecl();
            case ParsingFunction.ResetAttributesRootLevel:
                ResetAttributes();
                _curNode = _nodes[_index];
                _parsingFunction = ((_index == 0) ? ParsingFunction.DocumentContent : ParsingFunction.ElementContent);
                break;
            case ParsingFunction.MoveToElementContent:
                ResetAttributes();
                _index++;
                _curNode = AddNode(_index, _index);
                _parsingFunction = ParsingFunction.ElementContent;
                break;
            case ParsingFunction.PopElementContext:
                PopElementContext();
                _parsingFunction = _nextParsingFunction;
                break;
            case ParsingFunction.PopEmptyElementContext:
                _curNode = _nodes[_index];
                _curNode.IsEmptyElement = false;
                ResetAttributes();
                PopElementContext();
                _parsingFunction = _nextParsingFunction;
                break;
            case ParsingFunction.EntityReference:
                _parsingFunction = _nextParsingFunction;
                return ParseEntityReferenceAsync().ReturnTrueTaskWhenFinishAsync();
            case ParsingFunction.ReportEndEntity:
                SetupEndEntityNodeInContent();
                _parsingFunction = _nextParsingFunction;
                return AsyncHelper.DoneTaskTrue;
            case ParsingFunction.AfterResolveEntityInContent:
                _curNode = AddNode(_index, _index);
                _reportedEncoding = _ps.encoding;
                _reportedBaseUri = _ps.baseUriStr;
                _parsingFunction = _nextParsingFunction;
                break;
            case ParsingFunction.AfterResolveEmptyEntityInContent:
                _curNode = AddNode(_index, _index);
                _curNode.SetValueNode(XmlNodeType.Text, string.Empty);
                _curNode.SetLineInfo(_ps.lineNo, _ps.LinePos);
                _reportedEncoding = _ps.encoding;
                _reportedBaseUri = _ps.baseUriStr;
                _parsingFunction = _nextParsingFunction;
                return AsyncHelper.DoneTaskTrue;
            case ParsingFunction.InReadAttributeValue:
                FinishAttributeValueIterator();
                _curNode = _nodes[_index];
                break;
            case ParsingFunction.InIncrementalRead:
                FinishIncrementalRead();
                return AsyncHelper.DoneTaskTrue;
            case ParsingFunction.FragmentAttribute:
                return Task.FromResult(ParseFragmentAttribute());
            case ParsingFunction.XmlDeclarationFragment:
                ParseXmlDeclarationFragment();
                _parsingFunction = ParsingFunction.GoToEof;
                return AsyncHelper.DoneTaskTrue;
            case ParsingFunction.GoToEof:
                OnEof();
                return AsyncHelper.DoneTaskFalse;
            case ParsingFunction.Error:
            case ParsingFunction.Eof:
            case ParsingFunction.ReaderClosed:
                return AsyncHelper.DoneTaskFalse;
            case ParsingFunction.NoData:
                ThrowWithoutLineInfo(System.SR.Xml_MissingRoot);
                return AsyncHelper.DoneTaskFalse;
            case ParsingFunction.PartialTextValue:
                return SkipPartialTextValueAsync().CallBoolTaskFuncWhenFinishAsync((XmlTextReaderImpl thisRef) => thisRef.ReadAsync(), this);
            case ParsingFunction.InReadValueChunk:
                return FinishReadValueChunkAsync().CallBoolTaskFuncWhenFinishAsync((XmlTextReaderImpl thisRef) => thisRef.ReadAsync(), this);
            case ParsingFunction.InReadContentAsBinary:
                return FinishReadContentAsBinaryAsync().CallBoolTaskFuncWhenFinishAsync((XmlTextReaderImpl thisRef) => thisRef.ReadAsync(), this);
            case ParsingFunction.InReadElementContentAsBinary:
                return FinishReadElementContentAsBinaryAsync().CallBoolTaskFuncWhenFinishAsync((XmlTextReaderImpl thisRef) => thisRef.ReadAsync(), this);
            }
        }
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._laterInitParam, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._readState, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.XmlTextReaderImpl.AddNode(), System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.XmlTextReaderImpl.CheckAsyncCall(), System.Xml.Dictionary, System.Xml.AsyncHelper.DoneTaskFalse, System.Xml.AsyncHelper.DoneTaskTrue, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlTextReaderImpl.FinishAttributeValueIterator(), System.Xml.XmlTextReaderImpl.FinishIncrementalRead(), System.Xml.XmlTextReaderImpl.FinishInitAsync(), System.Xml.XmlTextReaderImpl.FinishReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.FinishReadElementContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.FinishReadValueChunkAsync(), System.Xml.XmlTextReaderImpl.ParsingState.lineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.OnEof(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync(), System.Xml.XmlTextReaderImpl.ParseElementContentAsync(), System.Xml.XmlTextReaderImpl.ParseEntityReferenceAsync(), System.Xml.XmlTextReaderImpl.ParseFragmentAttribute(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationFragment(), System.Xml.XmlTextReaderImpl.PopElementContext(), System.Xml.XmlTextReaderImpl.ReadAsync_SwitchToInteractiveXmlDecl(), System.Xml.XmlTextReaderImpl.ResetAttributes(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent(), System.Xml.XmlTextReaderImpl.NodeData.SetValueNode(), System.Xml.XmlTextReaderImpl.SkipPartialTextValueAsync(), System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), and System.SR.Xml_MissingRoot.
Referenced by System.Xml.XmlTextReaderImpl.ReadAsync_SwitchToInteractiveXmlDecl_Helper().