Terraria: System.Xml.XmlTextReaderImpl.ParseTextAsync_ReadData
ParseTextAsync_ReadData()
async Task<(int, int, int, bool)> System.Xml.XmlTextReaderImpl.ParseTextAsync_ReadData (int outOrChars, char[] chars, int pos, int rcount, int rpos, int orChars, char c) inline private
Definition at line 11337 of file XmlTextReaderImpl.cs.
    {
        if (pos > _ps.charPos)
        {
            _lastParseTextState = new ParseTextState(outOrChars, chars, pos, rcount, rpos, orChars, c);
            _parseText_NextFunction = ParseTextFunction.PartialValue;
            return _parseText_dummyTask.Result;
        }
        if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
        {
            if (_ps.charsUsed - _ps.charPos > 0)
            {
                if (_ps.chars[_ps.charPos] != '\r' && _ps.chars[_ps.charPos] != ']')
                {
                    Throw(System.SR.Xml_UnexpectedEOF1);
                }
            }
            else
            {
                if (!InEntity)
                {
                    _lastParseTextState = new ParseTextState(outOrChars, chars, pos, rcount, rpos, orChars, c);
                    _parseText_NextFunction = ParseTextFunction.NoValue;
                    return _parseText_dummyTask.Result;
                }
                if (HandleEntityEnd(checkEntityNesting: true))
                {
                    _nextParsingFunction = _parsingFunction;
                    _parsingFunction = ParsingFunction.ReportEndEntity;
                    _lastParseTextState = new ParseTextState(outOrChars, chars, pos, rcount, rpos, orChars, c);
                    _parseText_NextFunction = ParseTextFunction.NoValue;
                    return _parseText_dummyTask.Result;
                }
            }
        }
        pos = _ps.charPos;
        chars = _ps.chars;
        _lastParseTextState = new ParseTextState(outOrChars, chars, pos, rcount, rpos, orChars, c);
        _parseText_NextFunction = ParseTextFunction.ParseText;
        return _parseText_dummyTask.Result;
    }
References System.Xml.XmlTextReaderImpl._lastParseTextState, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parseText_dummyTask, System.Xml.XmlTextReaderImpl._parseText_NextFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Threading.Tasks.Task< TResult >.Result, System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.ParseTextAsync(), and System.Xml.XmlTextReaderImpl.ParseTextAsync_AsyncFunc().