Terraria: System.Xml.XmlTextReaderImpl.ElementNamespaceLookup
ElementNamespaceLookup()
void System.Xml.XmlTextReaderImpl.ElementNamespaceLookup () inline private
Definition at line 4757 of file XmlTextReaderImpl.cs.
    {
        if (_curNode.prefix.Length == 0)
        {
            _curNode.ns = _xmlContext.defaultNamespace;
        }
        else
        {
            _curNode.ns = LookupNamespace(_curNode);
        }
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._xmlContext, System.Xml.XmlTextReaderImpl.XmlContext.defaultNamespace, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.LookupNamespace(), and System.Xml.XmlTextReaderImpl.NodeData.prefix.
Referenced by System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseElement(), and System.Xml.XmlTextReaderImpl.ParseElementAsync_NoAttributes().