Terraria: System.Xml.XmlTextReaderImpl.ParseElement
ParseElement()
void System.Xml.XmlTextReaderImpl.ParseElement () inline private
Definition at line 4245 of file XmlTextReaderImpl.cs.
    {
        int num = _ps.charPos;
        char[] chars = _ps.chars;
        int colonPos = -1;
        _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
        while (true)
        {
            if (XmlCharType.IsStartNCNameSingleChar(chars[num]))
            {
                num++;
                while (true)
                {
                    if (XmlCharType.IsNCNameSingleChar(chars[num]))
                    {
                        num++;
                        continue;
                    }
                    if (chars[num] != ':')
                    {
                        break;
                    }
                    if (colonPos == -1)
                    {
                        goto IL_0088;
                    }
                    if (!_supportNamespaces)
                    {
                        num++;
                        continue;
                    }
                    goto IL_006c;
                }
                if (num + 1 < _ps.charsUsed)
                {
                    break;
                }
            }
            goto IL_00a0;
            IL_0088:
            colonPos = num;
            num++;
            continue;
            IL_00a0:
            num = ParseQName(out colonPos);
            chars = _ps.chars;
            break;
            IL_006c:
            Throw(num, System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(':', '\0'));
            goto IL_00a0;
        }
        _namespaceManager.PushScope();
        if (colonPos == -1 || !_supportNamespaces)
        {
            _curNode.SetNamedNode(XmlNodeType.Element, _nameTable.Add(chars, _ps.charPos, num - _ps.charPos));
        }
        else
        {
            int charPos = _ps.charPos;
            int num2 = colonPos - charPos;
            if (num2 == _lastPrefix.Length && XmlConvert.StrEqual(chars, charPos, num2, _lastPrefix))
            {
                _curNode.SetNamedNode(XmlNodeType.Element, _nameTable.Add(chars, colonPos + 1, num - colonPos - 1), _lastPrefix, null);
            }
            else
            {
                _curNode.SetNamedNode(XmlNodeType.Element, _nameTable.Add(chars, colonPos + 1, num - colonPos - 1), _nameTable.Add(chars, _ps.charPos, num2), null);
                _lastPrefix = _curNode.prefix;
            }
        }
        char c = chars[num];
        if (XmlCharType.IsWhiteSpace(c))
        {
            _ps.charPos = num;
            ParseAttributes();
            return;
        }
        switch (c)
        {
        case '>':
            _ps.charPos = num + 1;
            _parsingFunction = ParsingFunction.MoveToElementContent;
            break;
        case '/':
            if (num + 1 == _ps.charsUsed)
            {
                _ps.charPos = num;
                if (ReadData() == 0)
                {
                    Throw(num, System.SR.Xml_UnexpectedEOF, ">");
                }
                num = _ps.charPos;
                chars = _ps.chars;
            }
            if (chars[num + 1] == '>')
            {
                _curNode.IsEmptyElement = true;
                _nextParsingFunction = _parsingFunction;
                _parsingFunction = ParsingFunction.PopEmptyElementContext;
                _ps.charPos = num + 2;
            }
            else
            {
                ThrowUnexpectedToken(num, ">");
            }
            break;
        default:
            Throw(num, System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(chars, _ps.charsUsed, num));
            break;
        }
        if (_addDefaultAttributesAndNormalize)
        {
            AddDefaultAttributesAndNormalize();
        }
        ElementNamespaceLookup();
    }
References System.Xml.XmlTextReaderImpl._addDefaultAttributesAndNormalize, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._lastPrefix, System.Xml.XmlTextReaderImpl._namespaceManager, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._supportNamespaces, System.Xml.XmlNameTable.Add(), System.Xml.XmlTextReaderImpl.AddDefaultAttributesAndNormalize(), System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ElementNamespaceLookup(), System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.XmlCharType.IsStartNCNameSingleChar(), System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseQName(), System.Xml.XmlTextReaderImpl.NodeData.prefix, System.Xml.XmlNamespaceManager.PushScope(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.SR.Xml_BadNameChar, and System.SR.Xml_UnexpectedEOF.
Referenced by System.Xml.XmlTextReaderImpl.ParseDocumentContent(), and System.Xml.XmlTextReaderImpl.ParseElementContent().