Terraria: System.Xml.XmlTextReaderImpl.AddDefaultAttributeDtd
AddDefaultAttributeDtd()
bool System.Xml.XmlTextReaderImpl.AddDefaultAttributeDtd (IDtdDefaultAttributeInfo defAttrInfo, bool definedInDtd, NodeData[] nameSortedNodeData) inline private
Definition at line 8132 of file XmlTextReaderImpl.cs.
    {
        if (defAttrInfo.Prefix.Length > 0)
        {
            _attrNeedNamespaceLookup = true;
        }
        string localName = defAttrInfo.LocalName;
        string prefix = defAttrInfo.Prefix;
        if (nameSortedNodeData != null)
        {
            if (Array.BinarySearch(nameSortedNodeData, defAttrInfo, DtdDefaultAttributeInfoToNodeDataComparer.Instance) >= 0)
            {
                return false;
            }
        }
        else
        {
            for (int i = _index + 1; i < _index + 1 + _attrCount; i++)
            {
                if ((object)_nodes[i].localName == localName && (object)_nodes[i].prefix == prefix)
                {
                    return false;
                }
            }
        }
        NodeData nodeData = AddDefaultAttributeInternal(defAttrInfo.LocalName, null, defAttrInfo.Prefix, defAttrInfo.DefaultValueExpanded, defAttrInfo.LineNumber, defAttrInfo.LinePosition, defAttrInfo.ValueLineNumber, defAttrInfo.ValueLinePosition, defAttrInfo.IsXmlAttribute);
        if (DtdValidation)
        {
            if (_onDefaultAttributeUse != null)
            {
                _onDefaultAttributeUse(defAttrInfo, this);
            }
            nodeData.typedValue = defAttrInfo.DefaultValueTyped;
        }
        return nodeData != null;
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._attrNeedNamespaceLookup, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._onDefaultAttributeUse, System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal(), System.Array.BinarySearch(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.DtdDefaultAttributeInfoToNodeDataComparer.Instance, and System.prefix.
Referenced by System.Xml.XmlTextReaderImpl.AddDefaultAttributesAndNormalize().