Terraria: System.Xml.XmlTextReaderImpl.FinishReadValueChunkAsync
FinishReadValueChunkAsync()
Task System.Xml.XmlTextReaderImpl.FinishReadValueChunkAsync () inline private
Definition at line 11470 of file XmlTextReaderImpl.cs.
    {
        _readValueOffset = 0;
        if (_incReadState == IncrementalReadState.ReadValueChunk_OnPartialValue)
        {
            return SkipPartialTextValueAsync();
        }
        _parsingFunction = _nextParsingFunction;
        _nextParsingFunction = _nextNextParsingFunction;
        return Task.CompletedTask;
    }
References System.Xml.XmlTextReaderImpl._incReadState, System.Xml.XmlTextReaderImpl._nextNextParsingFunction, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readValueOffset, System.Threading.Tasks.Task< TResult >.CompletedTask, and System.Xml.XmlTextReaderImpl.SkipPartialTextValueAsync().
Referenced by System.Xml.XmlTextReaderImpl.ReadAsync(), and System.Xml.XmlTextReaderImpl.SkipAsync().