Terraria: System.Xml.XmlTextReaderImpl.XmlTextReaderImpl
XmlTextReaderImpl() [16/20]
System.Xml.XmlTextReaderImpl.XmlTextReaderImpl (string url, XmlNameTable nt) inline
Definition at line 1660 of file XmlTextReaderImpl.cs.
        : this(nt)
    {
        if (url == null)
        {
            throw new ArgumentNullException("url");
        }
        if (url.Length == 0)
        {
            throw new ArgumentException(System.SR.Xml_EmptyUrl, "url");
        }
        _namespaceManager = new XmlNamespaceManager(nt);
        _url = url;
        _ps.baseUri = GetTempResolver().ResolveUri(null, url);
        _ps.baseUriStr = _ps.baseUri.ToString();
        _reportedBaseUri = _ps.baseUriStr;
        _parsingFunction = ParsingFunction.OpenUrl;
    }
References System.Xml.XmlTextReaderImpl._namespaceManager, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._url, System.Xml.ArgumentException, System.Xml.XmlTextReaderImpl.ParsingState.baseUri, System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.GetTempResolver(), System.Xml.XmlResolver.ResolveUri(), System.Uri.ToString(), and System.SR.Xml_EmptyUrl.