Terraria: System.Xml.XmlTextReaderImpl.FinishInitUriString
FinishInitUriString()
void System.Xml.XmlTextReaderImpl.FinishInitUriString () inline private
Definition at line 1710 of file XmlTextReaderImpl.cs.
    {
        Stream stream = null;
        if (_laterInitParam.useAsync)
        {
            Task<object> entityAsync = _laterInitParam.inputUriResolver.GetEntityAsync(_laterInitParam.inputbaseUri, string.Empty, typeof(Stream));
            stream = (Stream)entityAsync.GetAwaiter().GetResult();
        }
        else
        {
            stream = (Stream)_laterInitParam.inputUriResolver.GetEntity(_laterInitParam.inputbaseUri, string.Empty, typeof(Stream));
        }
        if (stream == null)
        {
            throw new XmlException(System.SR.Xml_CannotResolveUrl, _laterInitParam.inputUriStr);
        }
        Encoding encoding = null;
        if (_laterInitParam.inputContext != null)
        {
            encoding = _laterInitParam.inputContext.Encoding;
        }
        try
        {
            InitStreamInput(_laterInitParam.inputbaseUri, _reportedBaseUri, stream, null, 0, encoding);
            _reportedEncoding = _ps.encoding;
            if (_laterInitParam.inputContext != null && _laterInitParam.inputContext.HasDtdInfo)
            {
                ProcessDtdFromParserContext(_laterInitParam.inputContext);
            }
        }
        catch
        {
            stream.Dispose();
            throw;
        }
        _laterInitParam = null;
    }
References System.Xml.XmlTextReaderImpl._laterInitParam, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.XmlParserContext.Encoding, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlResolver.GetEntity(), System.Xml.XmlResolver.GetEntityAsync(), System.Xml.XmlParserContext.HasDtdInfo, System.Xml.XmlTextReaderImpl.InitStreamInput(), System.Xml.XmlTextReaderImpl.LaterInitParam.inputbaseUri, System.Xml.XmlTextReaderImpl.LaterInitParam.inputContext, System.Xml.XmlTextReaderImpl.LaterInitParam.inputUriResolver, System.Xml.XmlTextReaderImpl.LaterInitParam.inputUriStr, System.Xml.XmlTextReaderImpl.ProcessDtdFromParserContext(), System.stream, System.Xml.XmlTextReaderImpl.Stream, System.Xml.XmlTextReaderImpl.LaterInitParam.useAsync, System.SR.Xml_CannotResolveUrl, and System.Xml.XmlException.
Referenced by System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), and System.Xml.XmlTextReaderImpl.FinishInit().