Terraria: System.Xml.XmlTextReaderImpl.ParseTextAsync_ParseEntity
ParseTextAsync_ParseEntity()
async Task<(int, int, int, bool)> System.Xml.XmlTextReaderImpl.ParseTextAsync_ParseEntity (int outOrChars, char[] chars, int pos, int rcount, int rpos, int orChars, char c) inline private
Definition at line 11243 of file XmlTextReaderImpl.cs.
    {
        int num;
        if ((num = ParseCharRefInline(pos, out var charCount, out var entityType)) > 0)
        {
            if (rcount > 0)
            {
                ShiftBuffer(rpos + rcount, rpos, pos - rpos - rcount);
            }
            rpos = pos - rcount;
            rcount += num - pos - charCount;
            pos = num;
            if (!XmlCharType.IsWhiteSpace(chars[num - charCount]) || (_v1Compat && entityType == EntityType.CharacterDec))
            {
                orChars |= 0xFF;
            }
        }
        else
        {
            if (pos > _ps.charPos)
            {
                _lastParseTextState = new ParseTextState(outOrChars, chars, pos, rcount, rpos, orChars, c);
                _parseText_NextFunction = ParseTextFunction.PartialValue;
                return _parseText_dummyTask.Result;
            }
            (int, EntityType) tuple = await HandleEntityReferenceAsync(isInAttributeValue: false, EntityExpandType.All).ConfigureAwait(continueOnCapturedContext: false);
            (pos, _) = tuple;
            switch (tuple.Item2)
            {
            case EntityType.Unexpanded:
                _nextParsingFunction = _parsingFunction;
                _parsingFunction = ParsingFunction.EntityReference;
                _lastParseTextState = new ParseTextState(outOrChars, chars, pos, rcount, rpos, orChars, c);
                _parseText_NextFunction = ParseTextFunction.NoValue;
                return _parseText_dummyTask.Result;
            case EntityType.CharacterDec:
                if (_v1Compat)
                {
                    orChars |= 0xFF;
                    break;
                }
                goto case EntityType.CharacterHex;
            case EntityType.CharacterHex:
            case EntityType.CharacterNamed:
                if (!XmlCharType.IsWhiteSpace(_ps.chars[pos - 1]))
                {
                    orChars |= 0xFF;
                }
                break;
            default:
                pos = _ps.charPos;
                break;
            }
            chars = _ps.chars;
        }
        _lastParseTextState = new ParseTextState(outOrChars, chars, pos, rcount, rpos, orChars, c);
        _parseText_NextFunction = ParseTextFunction.ParseText;
        return _parseText_dummyTask.Result;
    }
References System.Xml.XmlTextReaderImpl._lastParseTextState, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parseText_dummyTask, System.Xml.XmlTextReaderImpl._parseText_NextFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._v1Compat, System.charCount, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.HandleEntityReferenceAsync(), System.Xml.XmlTextReaderImpl.int, System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.XmlTextReaderImpl.ParseCharRefInline(), System.Threading.Tasks.Task< TResult >.Result, and System.Xml.XmlTextReaderImpl.ShiftBuffer().
Referenced by System.Xml.XmlTextReaderImpl.ParseTextAsync(), and System.Xml.XmlTextReaderImpl.ParseTextAsync_AsyncFunc().