Terraria: System.Xml.XmlTextReaderImpl.ParseText
ParseText() [1/2]
bool System.Xml.XmlTextReaderImpl.ParseText () inline private
Definition at line 5125 of file XmlTextReaderImpl.cs.
    {
        int outOrChars = 0;
        int startPos;
        int endPos;
        if (_parsingMode != 0)
        {
            while (!ParseText(out startPos, out endPos, ref outOrChars))
            {
            }
        }
        else
        {
            _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
            if (ParseText(out startPos, out endPos, ref outOrChars))
            {
                if (endPos - startPos != 0)
                {
                    XmlNodeType textNodeType = GetTextNodeType(outOrChars);
                    if (textNodeType != 0)
                    {
                        _curNode.SetValueNode(textNodeType, _ps.chars, startPos, endPos - startPos);
                        return true;
                    }
                }
            }
            else if (_v1Compat)
            {
                do
                {
                    if (endPos - startPos > 0)
                    {
                        _stringBuilder.Append(_ps.chars, startPos, endPos - startPos);
                    }
                }
                while (!ParseText(out startPos, out endPos, ref outOrChars));
                if (endPos - startPos > 0)
                {
                    _stringBuilder.Append(_ps.chars, startPos, endPos - startPos);
                }
                XmlNodeType textNodeType2 = GetTextNodeType(outOrChars);
                if (textNodeType2 != 0)
                {
                    _curNode.SetValueNode(textNodeType2, _stringBuilder.ToString());
                    _stringBuilder.Length = 0;
                    return true;
                }
                _stringBuilder.Length = 0;
            }
            else
            {
                bool flag = false;
                if (outOrChars > 32)
                {
                    _curNode.SetValueNode(XmlNodeType.Text, _ps.chars, startPos, endPos - startPos);
                    _nextParsingFunction = _parsingFunction;
                    _parsingFunction = ParsingFunction.PartialTextValue;
                    return true;
                }
                if (endPos - startPos > 0)
                {
                    _stringBuilder.Append(_ps.chars, startPos, endPos - startPos);
                }
                do
                {
                    flag = ParseText(out startPos, out endPos, ref outOrChars);
                    if (endPos - startPos > 0)
                    {
                        _stringBuilder.Append(_ps.chars, startPos, endPos - startPos);
                    }
                }
                while (!flag && outOrChars <= 32 && _stringBuilder.Length < 4096);
                XmlNodeType xmlNodeType = ((_stringBuilder.Length < 4096) ? GetTextNodeType(outOrChars) : XmlNodeType.Text);
                if (xmlNodeType != 0)
                {
                    _curNode.SetValueNode(xmlNodeType, _stringBuilder.ToString());
                    _stringBuilder.Length = 0;
                    if (!flag)
                    {
                        _nextParsingFunction = _parsingFunction;
                        _parsingFunction = ParsingFunction.PartialTextValue;
                    }
                    return true;
                }
                _stringBuilder.Length = 0;
                if (!flag)
                {
                    while (!ParseText(out startPos, out endPos, ref outOrChars))
                    {
                    }
                }
            }
        }
        if (_parsingFunction == ParsingFunction.ReportEndEntity)
        {
            SetupEndEntityNodeInContent();
            _parsingFunction = _nextParsingFunction;
            return true;
        }
        if (_parsingFunction == ParsingFunction.EntityReference)
        {
            _parsingFunction = _nextNextParsingFunction;
            ParseEntityReference();
            return true;
        }
        return false;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._nextNextParsingFunction, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Xml.XmlTextReaderImpl._v1Compat, System.Text.StringBuilder.Append(), System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.GetTextNodeType(), System.Text.StringBuilder.Length, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseEntityReference(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent(), System.Xml.XmlTextReaderImpl.NodeData.SetValueNode(), and System.Text.StringBuilder.ToString().
Referenced by System.Xml.XmlTextReaderImpl.FinishPartialValue(), System.Xml.XmlTextReaderImpl.ParseDocumentContent(), System.Xml.XmlTextReaderImpl.ParseElementContent(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ReadContentAsBinary(), System.Xml.XmlTextReaderImpl.ReadValueChunk(), and System.Xml.XmlTextReaderImpl.SkipPartialTextValue().