Terraria: System.Xml.XmlTextReaderImpl.ParseNamedCharRefInline
ParseNamedCharRefInline()
int System.Xml.XmlTextReaderImpl.ParseNamedCharRefInline (int startPos, bool expand, StringBuilder internalSubsetBuilder) inline private
Definition at line 6724 of file XmlTextReaderImpl.cs.
    {
        int num = startPos + 1;
        char[] chars = _ps.chars;
        char c = chars[num];
        char c2;
        if ((uint)c <= 103u)
        {
            if (c != 'a')
            {
                if (c != 'g')
                {
                    goto IL_0170;
                }
                if (_ps.charsUsed - num >= 3)
                {
                    if (chars[num + 1] == 't' && chars[num + 2] == ';')
                    {
                        num += 3;
                        c2 = '>';
                        goto IL_0175;
                    }
                    return -1;
                }
            }
            else
            {
                num++;
                if (chars[num] == 'm')
                {
                    if (_ps.charsUsed - num >= 3)
                    {
                        if (chars[num + 1] == 'p' && chars[num + 2] == ';')
{
                            num += 3;
                            c2 = '&';
                            goto IL_0175;
                        }
                        return -1;
                    }
                }
                else if (chars[num] == 'p')
                {
                    if (_ps.charsUsed - num >= 4)
                    {
                        if (chars[num + 1] == 'o' && chars[num + 2] == 's' && chars[num + 3] == ';')
{
                            num += 4;
                            c2 = '\'';
                            goto IL_0175;
                        }
                        return -1;
                    }
                }
                else if (num < _ps.charsUsed)
                {
                    return -1;
                }
            }
            goto IL_0172;
        }
        if (c != 'l')
        {
            if (c != 'q')
            {
                goto IL_0170;
            }
            if (_ps.charsUsed - num < 5)
            {
                goto IL_0172;
            }
            if (chars[num + 1] != 'u' || chars[num + 2] != 'o' || chars[num + 3] != 't' || chars[num + 4] != ';')
            {
                return -1;
            }
            num += 5;
            c2 = '"';
        }
        else
        {
            if (_ps.charsUsed - num < 3)
            {
                goto IL_0172;
            }
            if (chars[num + 1] != 't' || chars[num + 2] != ';')
            {
                return -1;
            }
            num += 3;
            c2 = '<';
        }
        goto IL_0175;
        IL_0170:
        return -1;
        IL_0172:
        return -2;
        IL_0175:
        if (expand)
        {
            internalSubsetBuilder?.Append(_ps.chars, _ps.charPos, num - _ps.charPos);
            _ps.chars[num - 1] = c2;
        }
        return num;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, and System.Xml.Dictionary.
Referenced by System.Xml.XmlTextReaderImpl.ParseCharRefInline(), System.Xml.XmlTextReaderImpl.ParseNamedCharRef(), and System.Xml.XmlTextReaderImpl.ParseNamedCharRefAsync().