Terraria: System.Xml.XmlTextReaderImpl.MoveToNextContentNode
MoveToNextContentNode()
bool System.Xml.XmlTextReaderImpl.MoveToNextContentNode (bool moveIfOnContentNode) inline private
Definition at line 8024 of file XmlTextReaderImpl.cs.
    {
        do
        {
            switch (_curNode.type)
            {
            case XmlNodeType.Attribute:
                return !moveIfOnContentNode;
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                if (!moveIfOnContentNode)
                {
                    return true;
                }
                break;
            case XmlNodeType.EntityReference:
                _outerReader.ResolveEntity();
                break;
            default:
                return false;
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.Comment:
            case XmlNodeType.EndEntity:
                break;
            }
            moveIfOnContentNode = false;
        }
        while (_outerReader.Read());
        return false;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.Dictionary, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ResolveEntity(), and System.Xml.XmlTextReaderImpl.NodeData.type.
Referenced by System.Xml.XmlTextReaderImpl.FinishReadContentAsBinary(), System.Xml.XmlTextReaderImpl.InitReadContentAsBinary(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinary(), and System.Xml.XmlTextReaderImpl.ReadContentAsBinary().