Terraria: System.Xml.XmlTextReaderImpl.ParseQName
ParseQName() [1/2]
int System.Xml.XmlTextReaderImpl.ParseQName (bool isQName, int startOffset, out int colonPos) inline private
Definition at line 6840 of file XmlTextReaderImpl.cs.
    {
        int num = -1;
        int pos = _ps.charPos + startOffset;
        while (true)
        {
            char[] chars = _ps.chars;
            if (XmlCharType.IsStartNCNameSingleChar(chars[pos]))
            {
                pos++;
            }
            else
            {
                if (pos + 1 >= _ps.charsUsed)
                {
                    if (ReadDataInName(ref pos))
                    {
                        continue;
                    }
                    Throw(pos, System.SR.Xml_UnexpectedEOF, "Name");
                }
                if (chars[pos] != ':' || _supportNamespaces)
                {
                    Throw(pos, System.SR.Xml_BadStartNameChar, XmlException.BuildCharExceptionArgs(chars, _ps.charsUsed, pos));
                }
            }
            while (true)
            {
                if (XmlCharType.IsNCNameSingleChar(chars[pos]))
                {
                    pos++;
                    continue;
                }
                if (chars[pos] == ':')
                {
                    if (_supportNamespaces)
                    {
                        break;
                    }
                    num = pos - _ps.charPos;
                    pos++;
                    continue;
                }
                if (pos == _ps.charsUsed)
                {
                    if (ReadDataInName(ref pos))
                    {
                        chars = _ps.chars;
                        continue;
                    }
                    Throw(pos, System.SR.Xml_UnexpectedEOF, "Name");
                }
                colonPos = ((num == -1) ? (-1) : (_ps.charPos + num));
                return pos;
            }
            if (num != -1 || !isQName)
            {
                Throw(pos, System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(':', '\0'));
            }
            num = pos - _ps.charPos;
            pos++;
        }
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._supportNamespaces, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.XmlCharType.IsStartNCNameSingleChar(), System.Xml.XmlTextReaderImpl.ReadDataInName(), System.Xml.XmlTextReaderImpl.Throw(), System.SR.Xml_BadNameChar, System.SR.Xml_BadStartNameChar, and System.SR.Xml_UnexpectedEOF.