Terraria: System.Xml.XmlTextReaderImpl.GetAttribute
GetAttribute() [3/4]
override string System.Xml.XmlTextReaderImpl.GetAttribute (string name) inline
Definition at line 1836 of file XmlTextReaderImpl.cs.
    {
        int num = (name.Contains(':') ? GetIndexOfAttributeWithPrefix(name) : GetIndexOfAttributeWithoutPrefix(name));
        if (num < 0)
        {
            return null;
        }
        return _nodes[num].StringValue;
    }
References System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl.GetIndexOfAttributeWithoutPrefix(), System.Xml.XmlTextReaderImpl.GetIndexOfAttributeWithPrefix(), and System.Xml.XmlTextReaderImpl.NodeData.StringValue.
Referenced by System.Xml.XmlTextReader.GetAttribute(), System.Xml.XmlTextReader.GetAttribute(), and System.Xml.XmlTextReader.GetAttribute().