Terraria: System.Xml.XmlTextReaderImpl.ParseDoctypeDecl
ParseDoctypeDecl()
bool System.Xml.XmlTextReaderImpl.ParseDoctypeDecl () inline private
Definition at line 6184 of file XmlTextReaderImpl.cs.
    {
        if (_dtdProcessing == DtdProcessing.Prohibit)
        {
            ThrowWithoutLineInfo(_v1Compat ? System.SR.Xml_DtdIsProhibited : System.SR.Xml_DtdIsProhibitedEx);
        }
        while (_ps.charsUsed - _ps.charPos < 8)
        {
            if (ReadData() == 0)
            {
                Throw(System.SR.Xml_UnexpectedEOF, "DOCTYPE");
            }
        }
        if (!XmlConvert.StrEqual(_ps.chars, _ps.charPos, 7, "DOCTYPE"))
        {
            ThrowUnexpectedToken((!_rootElementParsed && _dtdInfo == null) ? "DOCTYPE" : "<!--");
        }
        if (!XmlCharType.IsWhiteSpace(_ps.chars[_ps.charPos + 7]))
        {
            ThrowExpectingWhitespace(_ps.charPos + 7);
        }
        if (_dtdInfo != null)
        {
            Throw(_ps.charPos - 2, System.SR.Xml_MultipleDTDsProvided);
        }
        if (_rootElementParsed)
        {
            Throw(_ps.charPos - 2, System.SR.Xml_DtdAfterRootElement);
        }
        _ps.charPos += 8;
        EatWhitespaces(null);
        if (_dtdProcessing == DtdProcessing.Parse)
        {
            _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
            ParseDtd();
            _nextParsingFunction = _parsingFunction;
            _parsingFunction = ParsingFunction.ResetAttributesRootLevel;
            return true;
        }
        SkipDtd();
        return false;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._dtdInfo, System.Xml.XmlTextReaderImpl._dtdProcessing, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._rootElementParsed, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespaces(), System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseDtd(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.SkipDtd(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowExpectingWhitespace(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), System.SR.Xml_DtdAfterRootElement, System.SR.Xml_DtdIsProhibited, System.SR.Xml_DtdIsProhibitedEx, System.SR.Xml_MultipleDTDsProvided, and System.SR.Xml_UnexpectedEOF.
Referenced by System.Xml.XmlTextReaderImpl.ParseDocumentContent().