Terraria: System.Xml.XmlTextReaderImpl.ReadBinHex
ReadBinHex()
int System.Xml.XmlTextReaderImpl.ReadBinHex (byte[] array, int offset, int len) inline package
Definition at line 2729 of file XmlTextReaderImpl.cs.
    {
        if (_parsingFunction == ParsingFunction.InIncrementalRead)
        {
            if (_incReadDecoder != _binHexDecoder)
            {
                InitBinHexDecoder();
            }
            return IncrementalRead(array, offset, len);
        }
        if (_curNode.type != XmlNodeType.Element)
        {
            return 0;
        }
        if (_curNode.IsEmptyElement)
        {
            _outerReader.Read();
            return 0;
        }
        if (_binHexDecoder == null)
        {
            _binHexDecoder = new BinHexDecoder();
        }
        InitIncrementalRead(_binHexDecoder);
        return IncrementalRead(array, offset, len);
    }
References System.Xml.XmlTextReaderImpl._binHexDecoder, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.XmlTextReaderImpl._parsingFunction, System.array, System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.XmlTextReaderImpl.InitBinHexDecoder(), System.Xml.XmlTextReaderImpl.InitIncrementalRead(), System.Xml.XmlTextReaderImpl.NodeData.IsEmptyElement, System.len, System.offset, System.Xml.XmlReader.Read(), and System.Xml.XmlTextReaderImpl.NodeData.type.
Referenced by System.Xml.XmlTextReader.ReadBinHex().