Terraria: System.Xml.XmlTextReaderImpl.ReadContentAsBinHexAsync
ReadContentAsBinHexAsync()
override async Task< int > System.Xml.XmlTextReaderImpl.ReadContentAsBinHexAsync (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 8915 of file XmlTextReaderImpl.cs.
    {
        CheckAsyncCall();
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (_parsingFunction == ParsingFunction.InReadContentAsBinary)
        {
            if (_incReadDecoder == _binHexDecoder)
            {
                return await ReadContentAsBinaryAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        else
        {
            if (_readState != ReadState.Interactive)
            {
                return 0;
            }
            if (_parsingFunction == ParsingFunction.InReadElementContentAsBinary)
            {
                throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
            }
            if (!XmlReader.CanReadContentAs(_curNode.type))
            {
                throw CreateReadContentAsException("ReadContentAsBinHex");
            }
            if (!(await InitReadContentAsBinaryAsync().ConfigureAwait(continueOnCapturedContext: false)))
            {
                return 0;
            }
        }
        InitBinHexDecoder();
        return await ReadContentAsBinaryAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.XmlTextReaderImpl._binHexDecoder, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readState, System.buffer, System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlTextReaderImpl.CheckAsyncCall(), System.count, System.Xml.XmlReader.CreateReadContentAsException(), System.index, System.Xml.XmlTextReaderImpl.InitBinHexDecoder(), System.Xml.XmlTextReaderImpl.InitReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.NodeData.type, and System.SR.Xml_MixingBinaryContentMethods.