Terraria: System.Xml.XmlTextReaderImpl.InitBinHexDecoder
InitBinHexDecoder()
void System.Xml.XmlTextReaderImpl.InitBinHexDecoder () inline private
Definition at line 8345 of file XmlTextReaderImpl.cs.
    {
        if (_binHexDecoder == null)
        {
            _binHexDecoder = new BinHexDecoder();
        }
        else
        {
            _binHexDecoder.Reset();
        }
        _incReadDecoder = _binHexDecoder;
    }
References System.Xml.XmlTextReaderImpl._binHexDecoder, System.Xml.XmlTextReaderImpl._incReadDecoder, and System.Xml.BinHexDecoder.Reset().
Referenced by System.Xml.XmlTextReaderImpl.ReadBinHex(), System.Xml.XmlTextReaderImpl.ReadContentAsBinHex(), System.Xml.XmlTextReaderImpl.ReadContentAsBinHexAsync(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBinHex(), and System.Xml.XmlTextReaderImpl.ReadElementContentAsBinHexAsync().