Terraria: System.Xml.XmlTextReaderImpl.AttributeNamespaceLookup
AttributeNamespaceLookup()
void System.Xml.XmlTextReaderImpl.AttributeNamespaceLookup () inline private
Definition at line 4769 of file XmlTextReaderImpl.cs.
    {
        for (int i = _index + 1; i < _index + _attrCount + 1; i++)
        {
            NodeData nodeData = _nodes[i];
            if (nodeData.type == XmlNodeType.Attribute && nodeData.prefix.Length > 0)
            {
                nodeData.ns = LookupNamespace(nodeData);
            }
        }
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nodes, System.Xml.Dictionary, and System.Xml.XmlTextReaderImpl.LookupNamespace().
Referenced by System.Xml.XmlTextReaderImpl.AddDefaultAttributesAndNormalize(), System.Xml.XmlTextReaderImpl.ParseAttributes(), and System.Xml.XmlTextReaderImpl.ParseAttributesAsync().