Terraria: System.Xml.XmlTextReaderImpl.FinishPartialValue
FinishPartialValue()
void System.Xml.XmlTextReaderImpl.FinishPartialValue () inline private
Definition at line 5440 of file XmlTextReaderImpl.cs.
    {
        _curNode.CopyTo(_readValueOffset, _stringBuilder);
        int outOrChars = 0;
        int startPos;
        int endPos;
        while (!ParseText(out startPos, out endPos, ref outOrChars))
        {
            _stringBuilder.Append(_ps.chars, startPos, endPos - startPos);
        }
        _stringBuilder.Append(_ps.chars, startPos, endPos - startPos);
        _curNode.SetValue(_stringBuilder.ToString());
        _stringBuilder.Length = 0;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._readValueOffset, System.Xml.XmlTextReaderImpl._stringBuilder, System.Text.StringBuilder.Append(), System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.NodeData.CopyTo(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.NodeData.SetValue(), and System.Text.StringBuilder.ToString().
Referenced by System.Xml.XmlTextReaderImpl.FinishOtherValueIterator().