Terraria: System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent
SetupEndEntityNodeInContent()
void System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent () inline private
Definition at line 5746 of file XmlTextReaderImpl.cs.
    {
        _reportedEncoding = _ps.encoding;
        _reportedBaseUri = _ps.baseUriStr;
        _curNode = _nodes[_index];
        _curNode.SetNamedNode(XmlNodeType.EndEntity, _lastEntity.Name);
        _curNode.lineInfo.Set(_ps.lineNo, _ps.LinePos - 1);
        if (_index == 0 && _parsingFunction == ParsingFunction.ElementContent)
        {
            _parsingFunction = ParsingFunction.DocumentContent;
        }
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._lastEntity, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlTextReaderImpl.NodeData.lineInfo, System.Xml.XmlTextReaderImpl.ParsingState.lineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.IDtdEntityInfo.Name, System.Xml.LineInfo.Set(), and System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode().
Referenced by System.Xml.XmlTextReaderImpl.ParseDocumentContent(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(), System.Xml.XmlTextReaderImpl.ParseElementContent(), System.Xml.XmlTextReaderImpl.ParseElementContent_ReadData(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseTextAsync_IgnoreNode(), System.Xml.XmlTextReaderImpl.Read(), and System.Xml.XmlTextReaderImpl.ReadAsync().