Terraria: System.Xml.XmlTextReaderImpl.XmlTextReaderImpl
XmlTextReaderImpl() [3/20]
System.Xml.XmlTextReaderImpl.XmlTextReaderImpl (XmlResolver resolver, XmlReaderSettings settings, XmlParserContext context) inline private
Definition at line 1487 of file XmlTextReaderImpl.cs.
    {
        _useAsync = settings.Async;
        _v1Compat = false;
        _outerReader = this;
        _xmlContext = new XmlContext();
        XmlNameTable xmlNameTable = settings.NameTable;
        if (context == null)
        {
            if (xmlNameTable == null)
            {
                xmlNameTable = new NameTable();
            }
            else
            {
                _nameTableFromSettings = true;
            }
            _nameTable = xmlNameTable;
            _namespaceManager = new XmlNamespaceManager(xmlNameTable);
        }
        else
        {
            SetupFromParserContext(context, settings);
            xmlNameTable = _nameTable;
        }
        xmlNameTable.Add(string.Empty);
        _xml = xmlNameTable.Add("xml");
        _xmlNs = xmlNameTable.Add("xmlns");
        _xmlResolver = resolver;
        _nodes = new NodeData[8];
        _nodes[0] = new NodeData();
        _curNode = _nodes[0];
        _stringBuilder = new StringBuilder();
        _entityHandling = EntityHandling.ExpandEntities;
        _xmlResolverIsSet = settings.IsXmlResolverSet;
        _whitespaceHandling = (settings.IgnoreWhitespace ? WhitespaceHandling.Significant : WhitespaceHandling.All);
        _normalize = true;
        _ignorePIs = settings.IgnoreProcessingInstructions;
        _ignoreComments = settings.IgnoreComments;
        _checkCharacters = settings.CheckCharacters;
        _lineNumberOffset = settings.LineNumberOffset;
        _linePositionOffset = settings.LinePositionOffset;
        _ps.lineNo = _lineNumberOffset + 1;
        _ps.lineStartPos = -_linePositionOffset - 1;
        _curNode.SetLineInfo(_ps.LineNo - 1, _ps.LinePos - 1);
        _dtdProcessing = settings.DtdProcessing;
        _maxCharactersInDocument = settings.MaxCharactersInDocument;
        _maxCharactersFromEntities = settings.MaxCharactersFromEntities;
        _charactersInDocument = 0L;
        _charactersFromEntities = 0L;
        _fragmentParserContext = context;
        _parsingFunction = ParsingFunction.SwitchToInteractiveXmlDecl;
        _nextParsingFunction = ParsingFunction.DocumentContent;
        switch (settings.ConformanceLevel)
        {
        case ConformanceLevel.Auto:
            _fragmentType = XmlNodeType.None;
            _fragment = true;
            break;
        case ConformanceLevel.Fragment:
            _fragmentType = XmlNodeType.Element;
            _fragment = true;
            break;
        default:
            _fragmentType = XmlNodeType.Document;
            break;
        }
    }
References System.Xml.XmlTextReaderImpl._charactersFromEntities, System.Xml.XmlTextReaderImpl._charactersInDocument, System.Xml.XmlTextReaderImpl._checkCharacters, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._dtdProcessing, System.Xml.XmlTextReaderImpl._entityHandling, System.Xml.XmlTextReaderImpl._fragment, System.Xml.XmlTextReaderImpl._fragmentParserContext, System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._ignoreComments, System.Xml.XmlTextReaderImpl._ignorePIs, System.Xml.XmlTextReaderImpl._lineNumberOffset, System.Xml.XmlTextReaderImpl._linePositionOffset, System.Xml.XmlTextReaderImpl._maxCharactersFromEntities, System.Xml.XmlTextReaderImpl._maxCharactersInDocument, System.Xml.XmlTextReaderImpl._namespaceManager, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._nameTableFromSettings, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._normalize, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Xml.XmlTextReaderImpl._useAsync, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl._whitespaceHandling, System.Xml.XmlTextReaderImpl._xml, System.Xml.XmlTextReaderImpl._xmlContext, System.Xml.XmlTextReaderImpl._xmlNs, System.Xml.XmlTextReaderImpl._xmlResolver, System.Xml.XmlTextReaderImpl._xmlResolverIsSet, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XmlReaderSettings.Async, System.Xml.XmlReaderSettings.CheckCharacters, System.Xml.XmlReaderSettings.ConformanceLevel, System.Xml.Dictionary, System.Xml.XmlReaderSettings.DtdProcessing, System.Xml.XmlReaderSettings.IgnoreComments, System.Xml.XmlReaderSettings.IgnoreProcessingInstructions, System.Xml.XmlReaderSettings.IsXmlResolverSet, System.Xml.L, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlReaderSettings.LineNumberOffset, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlReaderSettings.LinePositionOffset, System.Xml.XmlReaderSettings.MaxCharactersFromEntities, System.Xml.XmlReaderSettings.MaxCharactersInDocument, System.Xml.XmlReader.NameTable, System.Xml.XmlReaderSettings.NameTable, System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), and System.Xml.XmlTextReaderImpl.SetupFromParserContext().