Terraria: System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken
ThrowUnexpectedToken() [1/4]
void System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken (int pos, string expectedToken) inline private
Definition at line 7860 of file XmlTextReaderImpl.cs.
    {
        ThrowUnexpectedToken(pos, expectedToken, null);
    }
References System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken().
Referenced by System.Xml.XmlTextReaderImpl.HandleEntityReference(), System.Xml.XmlTextReaderImpl.HandleEntityReferenceAsync(), System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseDoctypeDecl(), System.Xml.XmlTextReaderImpl.ParseDoctypeDeclAsync(), System.Xml.XmlTextReaderImpl.ParseDocumentContent(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync_NoAttributes(), System.Xml.XmlTextReaderImpl.ParseElementContent(), System.Xml.XmlTextReaderImpl.ParseElementContentAsync(), System.Xml.XmlTextReaderImpl.ParseEndElement(), System.Xml.XmlTextReaderImpl.ParseEndElementAsync_CheckEndTag(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Xml.XmlTextReaderImpl.SkipDtd(), System.Xml.XmlTextReaderImpl.SkipDtdAsync(), System.Xml.XmlTextReaderImpl.SkipPublicOrSystemIdLiteral(), System.Xml.XmlTextReaderImpl.SkipPublicOrSystemIdLiteralAsync(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), and System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken().