Terraria: System.Xml.XmlTextReaderImpl.ParseAttributesAsync
ParseAttributesAsync()
async Task System.Xml.XmlTextReaderImpl.ParseAttributesAsync () inline private
Definition at line 10448 of file XmlTextReaderImpl.cs.
    {
        int pos = _ps.charPos;
        char[] chars = _ps.chars;
        while (true)
        {
            int num = 0;
            while (true)
            {
                char c;
                int num2;
                if (XmlCharType.IsWhiteSpace(c = chars[pos]))
                {
                    switch (c)
                    {
                    case '\n':
                        OnNewLine(pos + 1);
                        num++;
                        goto IL_00f2;
                    case '\r':
                        if (chars[pos + 1] == '\n')
{
                            OnNewLine(pos + 2);
                            num++;
                            pos++;
                            goto IL_00f2;
                        }
                        if (pos + 1 != _ps.charsUsed)
{
                            OnNewLine(pos + 1);
                            num++;
                            goto IL_00f2;
                        }
                        break;
                    default:
                        goto IL_00f2;
                    }
                    _ps.charPos = pos;
                }
                else
                {
                    num2 = 0;
                    char c2;
                    if (XmlCharType.IsStartNCNameSingleChar(c2 = chars[pos]))
                    {
                        num2 = 1;
                    }
                    if (num2 != 0)
                    {
                        goto IL_0234;
                    }
                    if (c2 == '>')
                    {
                        _ps.charPos = pos + 1;
                        _parsingFunction = ParsingFunction.MoveToElementContent;
                        goto IL_090f;
                    }
                    if (c2 == '/')
                    {
                        if (pos + 1 != _ps.charsUsed)
{
                            if (chars[pos + 1] == '>')
{
                                _ps.charPos = pos + 2;
                                _curNode.IsEmptyElement = true;
                                _nextParsingFunction = _parsingFunction;
                                _parsingFunction = ParsingFunction.PopEmptyElementContext;
                                goto IL_090f;
                            }
                            ThrowUnexpectedToken(pos + 1, ">");
                            goto IL_0234;
                        }
                    }
                    else if (pos != _ps.charsUsed)
                    {
                        if (c2 != ':' || _supportNamespaces)
{
                            Throw(pos, System.SR.Xml_BadStartNameChar, XmlException.BuildCharExceptionArgs(chars, _ps.charsUsed, pos));
                        }
                        goto IL_0234;
                    }
                }
                _ps.lineNo -= num;
                if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) != 0)
                {
                    pos = _ps.charPos;
                    chars = _ps.chars;
                }
                else
                {
                    ThrowUnclosedElements();
                }
                break;
                IL_090f:
                if (_addDefaultAttributesAndNormalize)
                {
                    AddDefaultAttributesAndNormalize();
                }
                ElementNamespaceLookup();
                if (_attrNeedNamespaceLookup)
                {
                    AttributeNamespaceLookup();
                    _attrNeedNamespaceLookup = false;
                }
                if (_attrDuplWalkCount >= 250)
                {
                    AttributeDuplCheck();
                }
                return;
                IL_00f2:
                pos++;
                continue;
                IL_0234:
                if (pos == _ps.charPos)
                {
                    ThrowExpectingWhitespace(pos);
                }
                _ps.charPos = pos;
                int attrNameLinePos = _ps.LinePos;
                int num3 = -1;
                pos += num2;
                while (true)
                {
                    char c3;
                    if (XmlCharType.IsNCNameSingleChar(c3 = chars[pos]))
                    {
                        pos++;
                        continue;
                    }
                    if (c3 == ':')
                    {
                        if (num3 != -1)
{
                            if (_supportNamespaces)
{
                                Throw(pos, System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(':', '\0'));
                                break;
                            }
                            pos++;
                            continue;
                        }
                        num3 = pos;
                        pos++;
                        if (XmlCharType.IsStartNCNameSingleChar(chars[pos]))
{
                            pos++;
                            continue;
                        }
                        (int, int) tuple = await ParseQNameAsync().ConfigureAwait(continueOnCapturedContext: false);
                        num3 = tuple.Item1;
                        pos = tuple.Item2;
                        chars = _ps.chars;
                        break;
                    }
                    if (pos + 1 >= _ps.charsUsed)
                    {
                        (int, int) tuple2 = await ParseQNameAsync().ConfigureAwait(continueOnCapturedContext: false);
                        num3 = tuple2.Item1;
                        pos = tuple2.Item2;
                        chars = _ps.chars;
                    }
                    break;
                }
                NodeData attr = AddAttribute(pos, num3);
                attr.SetLineInfo(_ps.LineNo, attrNameLinePos);
                if (chars[pos] != '=')
                {
                    _ps.charPos = pos;
                    await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false);
                    pos = _ps.charPos;
                    if (chars[pos] != '=')
                    {
                        ThrowUnexpectedToken("=");
                    }
                }
                pos++;
                char c4 = chars[pos];
                if (c4 != '"' && c4 != '\'')
                {
                    _ps.charPos = pos;
                    await EatWhitespacesAsync(null).ConfigureAwait(continueOnCapturedContext: false);
                    pos = _ps.charPos;
                    c4 = chars[pos];
                    if (c4 != '"' && c4 != '\'')
                    {
                        ThrowUnexpectedToken("\"", "'");
                    }
                }
                pos++;
                _ps.charPos = pos;
                attr.quoteChar = c4;
                attr.SetLineInfo2(_ps.LineNo, _ps.LinePos);
                char c5;
                while (XmlCharType.IsAttributeValueChar(c5 = chars[pos]))
                {
                    pos++;
                }
                if (c5 == c4)
                {
                    attr.SetValue(chars, _ps.charPos, pos - _ps.charPos);
                    pos++;
                    _ps.charPos = pos;
                }
                else
                {
                    await ParseAttributeValueSlowAsync(pos, c4, attr).ConfigureAwait(continueOnCapturedContext: false);
                    pos = _ps.charPos;
                    chars = _ps.chars;
                }
                if (attr.prefix.Length == 0)
                {
                    if (Ref.Equal(attr.localName, _xmlNs))
                    {
                        OnDefaultNamespaceDecl(attr);
                    }
                }
                else if (Ref.Equal(attr.prefix, _xmlNs))
                {
                    OnNamespaceDecl(attr);
                }
                else if (Ref.Equal(attr.prefix, _xml))
                {
                    OnXmlReservedAttribute(attr);
                }
                break;
            }
        }
    }
References System.Xml.XmlTextReaderImpl._addDefaultAttributesAndNormalize, System.Xml.XmlTextReaderImpl._attrDuplWalkCount, System.Xml.XmlTextReaderImpl._attrNeedNamespaceLookup, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._supportNamespaces, System.Xml.XmlTextReaderImpl._xml, System.Xml.XmlTextReaderImpl._xmlNs, System.Xml.XmlTextReaderImpl.AddAttribute(), System.Xml.XmlTextReaderImpl.AddDefaultAttributesAndNormalize(), System.Xml.XmlTextReaderImpl.AttributeDuplCheck(), System.Xml.XmlTextReaderImpl.AttributeNamespaceLookup(), System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespacesAsync(), System.Xml.XmlTextReaderImpl.ElementNamespaceLookup(), System.Xml.Ref.Equal(), System.Xml.XmlTextReaderImpl.int, System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.XmlCharType.IsStartNCNameSingleChar(), System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.OnDefaultNamespaceDecl(), System.Xml.XmlTextReaderImpl.OnNamespaceDecl(), System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.OnXmlReservedAttribute(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync(), System.Xml.XmlTextReaderImpl.ParseQNameAsync(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowExpectingWhitespace(), System.Xml.XmlTextReaderImpl.ThrowUnclosedElements(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.SR.Xml_BadNameChar, and System.SR.Xml_BadStartNameChar.
Referenced by System.Xml.XmlTextReaderImpl.ParseElementAsync_SetElement().