Terraria: System.Xml.XmlTextReaderImpl.DtdParserProxy_PushExternalSubset
DtdParserProxy_PushExternalSubset()
bool System.Xml.XmlTextReaderImpl.DtdParserProxy_PushExternalSubset (string systemId, string publicId) inline package
Definition at line 2867 of file XmlTextReaderImpl.cs.
    {
        if (IsResolverNull)
        {
            return false;
        }
        if (_ps.baseUri == null && !string.IsNullOrEmpty(_ps.baseUriStr))
        {
            _ps.baseUri = _xmlResolver.ResolveUri(null, _ps.baseUriStr);
        }
        PushExternalEntityOrSubset(publicId, systemId, _ps.baseUri, null);
        _ps.entity = null;
        _ps.entityId = 0;
        int charPos = _ps.charPos;
        if (_v1Compat)
        {
            EatWhitespaces(null);
        }
        if (!ParseXmlDeclaration(isTextDecl: true))
        {
            _ps.charPos = charPos;
        }
        return true;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl._xmlResolver, System.Xml.XmlTextReaderImpl.ParsingState.baseUri, System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespaces(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubset(), and System.Xml.XmlResolver.ResolveUri().
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy.PushExternalSubset().