Terraria: System.Xml.XmlTextReaderImpl.Close
Close() [2/2]
void System.Xml.XmlTextReaderImpl.Close (bool closeInput) inline package
Definition at line 3610 of file XmlTextReaderImpl.cs.
    {
        if (_parsingFunction != ParsingFunction.ReaderClosed)
        {
            while (InEntity)
            {
                PopParsingState();
            }
            _ps.Close(closeInput);
            _curNode = NodeData.None;
            _parsingFunction = ParsingFunction.ReaderClosed;
            _reportedEncoding = null;
            _reportedBaseUri = string.Empty;
            _readState = ReadState.Closed;
            _fullAttrCleanup = false;
            ResetAttributes();
            _laterInitParam = null;
        }
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._fullAttrCleanup, System.Xml.XmlTextReaderImpl._laterInitParam, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._readState, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.XmlTextReaderImpl.ParsingState.Close(), System.Xml.XmlTextReaderImpl.NodeData.None, System.Xml.XmlTextReaderImpl.PopParsingState(), and System.Xml.XmlTextReaderImpl.ResetAttributes().