Terraria: System.Xml.XmlTextReaderImpl.XmlTextReaderImpl
XmlTextReaderImpl() [12/20]
System.Xml.XmlTextReaderImpl.XmlTextReaderImpl (Stream xmlFragment, XmlNodeType fragType, XmlParserContext context) inline package
Definition at line 1611 of file XmlTextReaderImpl.cs.
        : this((context != null && context.NameTable != null) ? context.NameTable : new NameTable())
    {
        Encoding encoding = context?.Encoding;
        if (context == null || context.BaseURI == null || context.BaseURI.Length == 0)
        {
            InitStreamInput(xmlFragment, encoding);
        }
        else
        {
            InitStreamInput(GetTempResolver().ResolveUri(null, context.BaseURI), xmlFragment, encoding);
        }
        InitFragmentReader(fragType, context, allowXmlDeclFragment: false);
        _reportedBaseUri = _ps.baseUriStr;
        _reportedEncoding = _ps.encoding;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.XmlParserContext.BaseURI, System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.XmlParserContext.Encoding, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlTextReaderImpl.GetTempResolver(), System.Xml.XmlTextReaderImpl.InitFragmentReader(), and System.Xml.XmlTextReaderImpl.InitStreamInput().