Terraria: System.Xml.XmlTextReaderImpl.AddNamespace
AddNamespace()
void System.Xml.XmlTextReaderImpl.AddNamespace (string prefix, string uri, NodeData attr) inline private
Definition at line 7049 of file XmlTextReaderImpl.cs.
    {
        if (uri == "http://www.w3.org/2000/xmlns/")
        {
            if (Ref.Equal(prefix, _xmlNs))
            {
                Throw(System.SR.Xml_XmlnsPrefix, attr.lineInfo2.lineNo, attr.lineInfo2.linePos);
            }
            else
            {
                Throw(System.SR.Xml_NamespaceDeclXmlXmlns, prefix, attr.lineInfo2.lineNo, attr.lineInfo2.linePos);
            }
        }
        else if (uri == "http://www.w3.org/XML/1998/namespace" && !Ref.Equal(prefix, _xml) && !_v1Compat)
        {
            Throw(System.SR.Xml_NamespaceDeclXmlXmlns, prefix, attr.lineInfo2.lineNo, attr.lineInfo2.linePos);
        }
        if (uri.Length == 0 && prefix.Length > 0)
        {
            Throw(System.SR.Xml_BadNamespaceDecl, attr.lineInfo.lineNo, attr.lineInfo.linePos);
        }
        try
        {
            _namespaceManager.AddNamespace(prefix, uri);
        }
        catch (ArgumentException e)
        {
            ReThrow(e, attr.lineInfo.lineNo, attr.lineInfo.linePos);
        }
    }
References System.Xml.XmlTextReaderImpl._namespaceManager, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl._xml, System.Xml.XmlTextReaderImpl._xmlNs, System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.Ref.Equal(), System.prefix, System.Xml.XmlTextReaderImpl.ReThrow(), System.Xml.XmlTextReaderImpl.Throw(), System.SR.Xml_BadNamespaceDecl, System.SR.Xml_NamespaceDeclXmlXmlns, and System.SR.Xml_XmlnsPrefix.
Referenced by System.Xml.XmlTextReaderImpl.OnDefaultNamespaceDecl(), and System.Xml.XmlTextReaderImpl.OnNamespaceDecl().