Terraria: System.Xml.XmlTextReaderImpl._ParseTextAsync
_ParseTextAsync()
async Task< bool > System.Xml.XmlTextReaderImpl._ParseTextAsync (Task<(int, int, int, bool)> parseTask) inline private
Definition at line 10944 of file XmlTextReaderImpl.cs.
    {
        int outOrChars = 0;
        if (parseTask == null)
        {
            if (_parsingMode != 0)
            {
                (int, int, int, bool) tuple;
                do
                {
                    tuple = await ParseTextAsync(outOrChars).ConfigureAwait(continueOnCapturedContext: false);
                    _ = tuple.Item1;
                    _ = tuple.Item2;
                    outOrChars = tuple.Item3;
                }
                while (!tuple.Item4);
                goto IL_0574;
            }
            _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
            parseTask = ParseTextAsync(outOrChars).AsTask();
        }
        (int, int, int, bool) tuple2 = await parseTask.ConfigureAwait(continueOnCapturedContext: false);
        int num;
        int num2;
        (num, num2, outOrChars, _) = tuple2;
        if (tuple2.Item4)
        {
            if (num2 - num != 0)
            {
                XmlNodeType textNodeType = GetTextNodeType(outOrChars);
                if (textNodeType != 0)
                {
                    _curNode.SetValueNode(textNodeType, _ps.chars, num, num2 - num);
                    return true;
                }
            }
        }
        else if (_v1Compat)
        {
            (int, int, int, bool) tuple4;
            do
            {
                if (num2 - num > 0)
                {
                    _stringBuilder.Append(_ps.chars, num, num2 - num);
                }
                tuple4 = await ParseTextAsync(outOrChars).ConfigureAwait(continueOnCapturedContext: false);
                (num, num2, outOrChars, _) = tuple4;
            }
            while (!tuple4.Item4);
            if (num2 - num > 0)
            {
                _stringBuilder.Append(_ps.chars, num, num2 - num);
            }
            XmlNodeType textNodeType2 = GetTextNodeType(outOrChars);
            if (textNodeType2 != 0)
            {
                _curNode.SetValueNode(textNodeType2, _stringBuilder.ToString());
                _stringBuilder.Length = 0;
                return true;
            }
            _stringBuilder.Length = 0;
        }
        else
        {
            if (outOrChars > 32)
            {
                _curNode.SetValueNode(XmlNodeType.Text, _ps.chars, num, num2 - num);
                _nextParsingFunction = _parsingFunction;
                _parsingFunction = ParsingFunction.PartialTextValue;
                return true;
            }
            if (num2 - num > 0)
            {
                _stringBuilder.Append(_ps.chars, num, num2 - num);
            }
            bool flag;
            do
            {
                (num, num2, outOrChars, flag) = await ParseTextAsync(outOrChars).ConfigureAwait(continueOnCapturedContext: false);
                if (num2 - num > 0)
                {
                    _stringBuilder.Append(_ps.chars, num, num2 - num);
                }
            }
            while (!flag && outOrChars <= 32 && _stringBuilder.Length < 4096);
            XmlNodeType xmlNodeType = ((_stringBuilder.Length < 4096) ? GetTextNodeType(outOrChars) : XmlNodeType.Text);
            if (xmlNodeType != 0)
            {
                _curNode.SetValueNode(xmlNodeType, _stringBuilder.ToString());
                _stringBuilder.Length = 0;
                if (!flag)
                {
                    _nextParsingFunction = _parsingFunction;
                    _parsingFunction = ParsingFunction.PartialTextValue;
                }
                return true;
            }
            _stringBuilder.Length = 0;
            if (!flag)
            {
                (int, int, int, bool) tuple7;
                do
                {
                    tuple7 = await ParseTextAsync(outOrChars).ConfigureAwait(continueOnCapturedContext: false);
                    _ = tuple7.Item1;
                    _ = tuple7.Item2;
                    outOrChars = tuple7.Item3;
                }
                while (!tuple7.Item4);
            }
        }
        goto IL_0574;
        IL_0574:
        return await ParseTextAsync_IgnoreNode().ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Xml.XmlTextReaderImpl._v1Compat, System.Text.StringBuilder.Append(), System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.GetTextNodeType(), System.Xml.XmlTextReaderImpl.int, System.Text.StringBuilder.Length, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync_IgnoreNode(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.SetValueNode(), and System.Text.StringBuilder.ToString().
Referenced by System.Xml.XmlTextReaderImpl.ParseTextAsync().