Terraria: System.Xml.XmlTextReaderImpl.ReadElementContentAsBinHexAsync
ReadElementContentAsBinHexAsync()
override async Task< int > System.Xml.XmlTextReaderImpl.ReadElementContentAsBinHexAsync (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 9028 of file XmlTextReaderImpl.cs.
    {
        CheckAsyncCall();
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (_parsingFunction == ParsingFunction.InReadElementContentAsBinary)
        {
            if (_incReadDecoder == _binHexDecoder)
            {
                return await ReadElementContentAsBinaryAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        else
        {
            if (_readState != ReadState.Interactive)
            {
                return 0;
            }
            if (_parsingFunction == ParsingFunction.InReadContentAsBinary)
            {
                throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
            }
            if (_curNode.type != XmlNodeType.Element)
            {
                throw CreateReadElementContentAsException("ReadElementContentAsBinHex");
            }
            if (!(await InitReadElementContentAsBinaryAsync().ConfigureAwait(continueOnCapturedContext: false)))
            {
                return 0;
            }
        }
        InitBinHexDecoder();
        return await ReadElementContentAsBinaryAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.XmlTextReaderImpl._binHexDecoder, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readState, System.buffer, System.Xml.XmlTextReaderImpl.CheckAsyncCall(), System.count, System.Xml.XmlReader.CreateReadElementContentAsException(), System.index, System.Xml.XmlTextReaderImpl.InitBinHexDecoder(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.NodeData.type, and System.SR.Xml_MixingBinaryContentMethods.