Terraria: System.Xml.XmlTextReaderImpl.GetTextNodeType
GetTextNodeType()
XmlNodeType System.Xml.XmlTextReaderImpl.GetTextNodeType (int orChars) inline private
Definition at line 7131 of file XmlTextReaderImpl.cs.
    {
        if (orChars > 32)
        {
            return XmlNodeType.Text;
        }
        return GetWhitespaceType();
    }
References System.Xml.XmlTextReaderImpl.GetWhitespaceType().
Referenced by System.Xml.XmlTextReaderImpl._ParseTextAsync(), System.Xml.XmlTextReaderImpl.ParseText(), and System.Xml.XmlTextReaderImpl.ParseTextAsync().