Terraria: System.Xml.XmlTextReaderImpl.ReadContentAsBase64Async
ReadContentAsBase64Async()
override Task< int > System.Xml.XmlTextReaderImpl.ReadContentAsBase64Async (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 8861 of file XmlTextReaderImpl.cs.
    {
        CheckAsyncCall();
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (_parsingFunction == ParsingFunction.InReadContentAsBinary)
        {
            if (_incReadDecoder == _base64Decoder)
            {
                return ReadContentAsBinaryAsync(buffer, index, count);
            }
        }
        else
        {
            if (_readState != ReadState.Interactive)
            {
                return AsyncHelper.DoneTaskZero;
            }
            if (_parsingFunction == ParsingFunction.InReadElementContentAsBinary)
            {
                throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
            }
            if (!XmlReader.CanReadContentAs(_curNode.type))
            {
                throw CreateReadContentAsException("ReadContentAsBase64");
            }
            Task<bool> task = InitReadContentAsBinaryAsync();
            if (!task.IsSuccess())
            {
                return ReadContentAsBase64_AsyncHelper(task, buffer, index, count);
            }
            if (!task.Result)
            {
                return AsyncHelper.DoneTaskZero;
            }
        }
        InitBase64Decoder();
        return ReadContentAsBinaryAsync(buffer, index, count);
    }
References System.Xml.XmlTextReaderImpl._base64Decoder, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readState, System.buffer, System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlTextReaderImpl.CheckAsyncCall(), System.count, System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.AsyncHelper.DoneTaskZero, System.index, System.Xml.XmlTextReaderImpl.InitBase64Decoder(), System.Xml.XmlTextReaderImpl.InitReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.ReadContentAsBase64_AsyncHelper(), System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync(), System.task, System.Xml.XmlTextReaderImpl.NodeData.type, and System.SR.Xml_MixingBinaryContentMethods.