Terraria: System.Xml.XmlTextReaderImpl.ParseDocumentContent
ParseDocumentContent()
bool System.Xml.XmlTextReaderImpl.ParseDocumentContent () inline private
Definition at line 3901 of file XmlTextReaderImpl.cs.
    {
        bool flag = false;
        while (true)
        {
            bool flag2 = false;
            int charPos = _ps.charPos;
            char[] chars = _ps.chars;
            if (chars[charPos] == '<')
            {
                flag2 = true;
                if (_ps.charsUsed - charPos >= 4)
                {
                    charPos++;
                    switch (chars[charPos])
                    {
                    case '?':
                        _ps.charPos = charPos + 1;
                        if (!ParsePI())
{
                            continue;
                        }
                        return true;
                    case '!':
                        charPos++;
                        if (_ps.charsUsed - charPos < 2)
{
                            break;
                        }
                        if (chars[charPos] == '-')
{
                            if (chars[charPos + 1] == '-')
{
                                _ps.charPos = charPos + 2;
                                if (!ParseComment())
{
                                    continue;
                                }
                                return true;
                            }
                            ThrowUnexpectedToken(charPos + 1, "-");
                            break;
                        }
                        if (chars[charPos] == '[')
{
                            if (_fragmentType != XmlNodeType.Document)
{
                                charPos++;
                                if (_ps.charsUsed - charPos < 6)
{
                                    break;
                                }
                                if (XmlConvert.StrEqual(chars, charPos, 6, "CDATA["))
{
                                    _ps.charPos = charPos + 6;
                                    ParseCData();
                                    if (_fragmentType == XmlNodeType.None)
{
                                        _fragmentType = XmlNodeType.Element;
                                    }
                                    return true;
                                }
                                ThrowUnexpectedToken(charPos, "CDATA[");
                            }
                            else
{
                                Throw(_ps.charPos, System.SR.Xml_InvalidRootData);
                            }
                            break;
                        }
                        if (_fragmentType == XmlNodeType.Document || _fragmentType == XmlNodeType.None)
{
                            _fragmentType = XmlNodeType.Document;
                            _ps.charPos = charPos;
                            if (!ParseDoctypeDecl())
{
                                continue;
                            }
                            return true;
                        }
                        if (ParseUnexpectedToken(charPos) == "DOCTYPE")
{
                            Throw(System.SR.Xml_BadDTDLocation);
                        }
                        else
{
                            ThrowUnexpectedToken(charPos, "<!--", "<[CDATA[");
                        }
                        break;
                    case '/':
                        Throw(charPos + 1, System.SR.Xml_UnexpectedEndTag);
                        break;
                    default:
                        if (_rootElementParsed)
{
                            if (_fragmentType == XmlNodeType.Document)
{
                                Throw(charPos, System.SR.Xml_MultipleRoots);
                            }
                            if (_fragmentType == XmlNodeType.None)
{
                                _fragmentType = XmlNodeType.Element;
                            }
                        }
                        _ps.charPos = charPos;
                        _rootElementParsed = true;
                        ParseElement();
                        return true;
                    }
                }
            }
            else if (chars[charPos] == '&')
            {
                if (_fragmentType != XmlNodeType.Document)
                {
                    if (_fragmentType == XmlNodeType.None)
                    {
                        _fragmentType = XmlNodeType.Element;
                    }
                    int charRefEndPos;
                    switch (HandleEntityReference(isInAttributeValue: false, EntityExpandType.OnlyGeneral, out charRefEndPos))
                    {
                    case EntityType.Unexpanded:
                        if (_parsingFunction == ParsingFunction.EntityReference)
{
                            _parsingFunction = _nextParsingFunction;
                        }
                        ParseEntityReference();
                        return true;
                    case EntityType.CharacterDec:
                    case EntityType.CharacterHex:
                    case EntityType.CharacterNamed:
                        if (ParseText())
{
                            return true;
                        }
                        break;
                    default:
                        chars = _ps.chars;
                        charPos = _ps.charPos;
                        break;
                    }
                    continue;
                }
                Throw(charPos, System.SR.Xml_InvalidRootData);
            }
            else if (charPos != _ps.charsUsed && (!(_v1Compat || flag) || chars[charPos] != 0))
            {
                if (_fragmentType == XmlNodeType.Document)
                {
                    if (ParseRootLevelWhitespace())
                    {
                        return true;
                    }
                }
                else if (ParseText())
                {
                    if (_fragmentType == XmlNodeType.None && _curNode.type == XmlNodeType.Text)
                    {
                        _fragmentType = XmlNodeType.Element;
                    }
                    return true;
                }
                continue;
            }
            if (ReadData() != 0)
            {
                charPos = _ps.charPos;
                charPos = _ps.charPos;
                chars = _ps.chars;
                continue;
            }
            if (flag2)
            {
                Throw(System.SR.Xml_InvalidRootData);
            }
            if (!InEntity)
            {
                break;
            }
            if (HandleEntityEnd(checkEntityNesting: true))
            {
                SetupEndEntityNodeInContent();
                return true;
            }
        }
        if (!_rootElementParsed && _fragmentType == XmlNodeType.Document)
        {
            ThrowWithoutLineInfo(System.SR.Xml_MissingRoot);
        }
        if (_fragmentType == XmlNodeType.None)
        {
            _fragmentType = ((!_rootElementParsed) ? XmlNodeType.Element : XmlNodeType.Document);
        }
        OnEof();
        return false;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._rootElementParsed, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.XmlTextReaderImpl.HandleEntityReference(), System.Xml.XmlTextReaderImpl.OnEof(), System.Xml.XmlTextReaderImpl.ParseCData(), System.Xml.XmlTextReaderImpl.ParseComment(), System.Xml.XmlTextReaderImpl.ParseDoctypeDecl(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseEntityReference(), System.Xml.XmlTextReaderImpl.ParsePI(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseUnexpectedToken(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.type, System.SR.Xml_BadDTDLocation, System.SR.Xml_InvalidRootData, System.SR.Xml_MissingRoot, System.SR.Xml_MultipleRoots, and System.SR.Xml_UnexpectedEndTag.
Referenced by System.Xml.XmlTextReaderImpl.Read().