Terraria: System.Xml.XmlTextReaderImpl.ParseTextAsync_IgnoreNode
ParseTextAsync_IgnoreNode()
Task< bool > System.Xml.XmlTextReaderImpl.ParseTextAsync_IgnoreNode () inline private
Definition at line 11061 of file XmlTextReaderImpl.cs.
    {
        if (_parsingFunction == ParsingFunction.ReportEndEntity)
        {
            SetupEndEntityNodeInContent();
            _parsingFunction = _nextParsingFunction;
            return AsyncHelper.DoneTaskTrue;
        }
        if (_parsingFunction == ParsingFunction.EntityReference)
        {
            _parsingFunction = _nextNextParsingFunction;
            return ParseEntityReferenceAsync().ReturnTrueTaskWhenFinishAsync();
        }
        return AsyncHelper.DoneTaskFalse;
    }
References System.Xml.XmlTextReaderImpl._nextNextParsingFunction, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.AsyncHelper.DoneTaskFalse, System.Xml.AsyncHelper.DoneTaskTrue, System.Xml.XmlTextReaderImpl.ParseEntityReferenceAsync(), and System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent().
Referenced by System.Xml.XmlTextReaderImpl._ParseTextAsync(), and System.Xml.XmlTextReaderImpl.ParseTextAsync().