Terraria: System.Xml.XmlTextReaderImpl.ParseEndElementAsync_ReadData
ParseEndElementAsync_ReadData()
async Task System.Xml.XmlTextReaderImpl.ParseEndElementAsync_ReadData () inline private
Definition at line 10418 of file XmlTextReaderImpl.cs.
    {
        if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
        {
            ThrowUnclosedElements();
        }
        _parseEndElement_NextFunc = ParseEndElementParseFunction.CheckEndTag;
    }
References System.Xml.XmlTextReaderImpl._parseEndElement_NextFunc, System.Xml.XmlTextReaderImpl.ReadDataAsync(), and System.Xml.XmlTextReaderImpl.ThrowUnclosedElements().
Referenced by System.Xml.XmlTextReaderImpl.ParseEndElementAsync_Finish(), and System.Xml.XmlTextReaderImpl.ParseEndElementAsync_Finish().