Terraria: System.Xml.XmlTextReaderImpl.MoveOffEntityReference
MoveOffEntityReference()
void System.Xml.XmlTextReaderImpl.MoveOffEntityReference () inline package
Definition at line 2268 of file XmlTextReaderImpl.cs.
    {
        if (_outerReader.NodeType == XmlNodeType.EntityReference && _parsingFunction == ParsingFunction.AfterResolveEntityInContent && !_outerReader.Read())
        {
            throw new InvalidOperationException(System.SR.Xml_InvalidOperation);
        }
    }
References System.Xml.XmlTextReaderImpl._outerReader, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), and System.SR.Xml_InvalidOperation.
Referenced by System.Xml.XmlTextReader.ReadString(), and System.Xml.XmlTextReaderImpl.ReadString().