Terraria: System.Xml.XmlTextReaderImpl.InitStringInput
InitStringInput()
void System.Xml.XmlTextReaderImpl.InitStringInput (string baseUriStr, Encoding originalEncoding, string str) inline private
Definition at line 3163 of file XmlTextReaderImpl.cs.
    {
        _ps.baseUriStr = baseUriStr;
        _ps.baseUri = null;
        int length = str.Length;
        _ps.chars = new char[length + 1];
        str.CopyTo(0, _ps.chars, 0, str.Length);
        _ps.charsUsed = length;
        _ps.chars[length] = '\0';
        _ps.encoding = originalEncoding;
        _ps.eolNormalized = !_normalize;
        _ps.isEof = true;
    }
References System.Xml.XmlTextReaderImpl._normalize, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.Dictionary, System.length, and System.str.
Referenced by System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), System.Xml.XmlTextReaderImpl.DtdParserProxy_PushInternalDtd(), System.Xml.XmlTextReaderImpl.PushExternalEntity(), System.Xml.XmlTextReaderImpl.PushExternalEntityAsync(), and System.Xml.XmlTextReaderImpl.PushInternalEntity().