Terraria: System.Xml.XmlTextReaderImpl.OpenAndPush
OpenAndPush()
bool System.Xml.XmlTextReaderImpl.OpenAndPush (Uri uri) inline private
Definition at line 7192 of file XmlTextReaderImpl.cs.
    {
        if (_xmlResolver.SupportsType(uri, typeof(TextReader)))
        {
            TextReader textReader = (TextReader)_xmlResolver.GetEntity(uri, null, typeof(TextReader));
            if (textReader == null)
            {
                return false;
            }
            PushParsingState();
            InitTextReaderInput(uri.ToString(), uri, textReader);
        }
        else
        {
            Stream stream = (Stream)_xmlResolver.GetEntity(uri, null, typeof(Stream));
            if (stream == null)
            {
                return false;
            }
            PushParsingState();
            InitStreamInput(uri, stream, null);
        }
        return true;
    }
References System.Xml.XmlTextReaderImpl._xmlResolver, System.Xml.XmlResolver.GetEntity(), System.Xml.XmlTextReaderImpl.InitStreamInput(), System.Xml.XmlTextReaderImpl.InitTextReaderInput(), System.Xml.XmlTextReaderImpl.PushParsingState(), System.stream, System.Xml.XmlTextReaderImpl.Stream, System.Xml.XmlResolver.SupportsType(), System.Xml.XmlTextReaderImpl.TextReader, and System.Uri.ToString().
Referenced by System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubset().