Terraria: System.Xml.XmlTextReaderImpl.ReadBase64
ReadBase64()
int System.Xml.XmlTextReaderImpl.ReadBase64 (byte[] array, int offset, int len) inline package
Definition at line 2702 of file XmlTextReaderImpl.cs.
    {
        if (_parsingFunction == ParsingFunction.InIncrementalRead)
        {
            if (_incReadDecoder != _base64Decoder)
            {
                InitBase64Decoder();
            }
            return IncrementalRead(array, offset, len);
        }
        if (_curNode.type != XmlNodeType.Element)
        {
            return 0;
        }
        if (_curNode.IsEmptyElement)
        {
            _outerReader.Read();
            return 0;
        }
        if (_base64Decoder == null)
        {
            _base64Decoder = new Base64Decoder();
        }
        InitIncrementalRead(_base64Decoder);
        return IncrementalRead(array, offset, len);
    }
References System.Xml.XmlTextReaderImpl._base64Decoder, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.XmlTextReaderImpl._parsingFunction, System.array, System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.XmlTextReaderImpl.InitBase64Decoder(), System.Xml.XmlTextReaderImpl.InitIncrementalRead(), System.Xml.XmlTextReaderImpl.NodeData.IsEmptyElement, System.len, System.offset, System.Xml.XmlReader.Read(), and System.Xml.XmlTextReaderImpl.NodeData.type.
Referenced by System.Xml.XmlTextReader.ReadBase64().