Terraria: System.Xml.XmlTextReaderImpl.SkipAsync
SkipAsync()
override async Task System.Xml.XmlTextReaderImpl.SkipAsync () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 8795 of file XmlTextReaderImpl.cs.
    {
        CheckAsyncCall();
        if (_readState != ReadState.Interactive)
        {
            return;
        }
        if (InAttributeValueIterator)
        {
            FinishAttributeValueIterator();
            _curNode = _nodes[_index];
        }
        else
        {
            switch (_parsingFunction)
            {
            case ParsingFunction.InIncrementalRead:
                FinishIncrementalRead();
                break;
            case ParsingFunction.PartialTextValue:
                await SkipPartialTextValueAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            case ParsingFunction.InReadValueChunk:
                await FinishReadValueChunkAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            case ParsingFunction.InReadContentAsBinary:
                await FinishReadContentAsBinaryAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            case ParsingFunction.InReadElementContentAsBinary:
                await FinishReadElementContentAsBinaryAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            }
        }
        XmlNodeType type = _curNode.type;
        if (type != XmlNodeType.Element)
        {
            if (type != XmlNodeType.Attribute)
            {
                goto IL_0328;
            }
            _outerReader.MoveToElement();
        }
        if (!_curNode.IsEmptyElement)
        {
            int initialDepth = _index;
            _parsingMode = ParsingMode.SkipContent;
            while (await _outerReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false) && _index > initialDepth)
            {
            }
            _parsingMode = ParsingMode.Full;
        }
        goto IL_0328;
        IL_0328:
        await _outerReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._readState, System.Xml.XmlTextReaderImpl.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.FinishAttributeValueIterator(), System.Xml.XmlTextReaderImpl.FinishIncrementalRead(), System.Xml.XmlTextReaderImpl.FinishReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.FinishReadElementContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.FinishReadValueChunkAsync(), System.Xml.XmlTextReaderImpl.NodeData.IsEmptyElement, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.ReadAsync(), System.Xml.XmlTextReaderImpl.SkipPartialTextValueAsync(), System.type, and System.Xml.XmlTextReaderImpl.NodeData.type.