Terraria: System.Xml.XmlTextReaderImpl.RegisterEntity
RegisterEntity()
void System.Xml.XmlTextReaderImpl.RegisterEntity (IDtdEntityInfo entity) inline private
Definition at line 7270 of file XmlTextReaderImpl.cs.
    {
        if (_currentEntities != null && _currentEntities.ContainsKey(entity))
        {
            Throw(entity.IsParameterEntity ? System.SR.Xml_RecursiveParEntity : System.SR.Xml_RecursiveGenEntity, entity.Name, _parsingStatesStack[_parsingStatesStackTop].LineNo, _parsingStatesStack[_parsingStatesStackTop].LinePos);
        }
        _ps.entity = entity;
        _ps.entityId = _nextEntityId++;
        if (entity != null)
        {
            if (_currentEntities == null)
            {
                _currentEntities = new Dictionary<IDtdEntityInfo, IDtdEntityInfo>();
            }
            _currentEntities.Add(entity, entity);
        }
    }
References System.Xml.XmlTextReaderImpl._currentEntities, System.Xml.XmlTextReaderImpl._nextEntityId, System.Xml.XmlTextReaderImpl._parsingStatesStack, System.Xml.XmlTextReaderImpl._parsingStatesStackTop, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Dictionary, System.Xml.IDtdEntityInfo.IsParameterEntity, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.IDtdEntityInfo.Name, System.Xml.XmlTextReaderImpl.Throw(), System.SR.Xml_RecursiveGenEntity, and System.SR.Xml_RecursiveParEntity.
Referenced by System.Xml.XmlTextReaderImpl.PushExternalEntity(), System.Xml.XmlTextReaderImpl.PushExternalEntityAsync(), and System.Xml.XmlTextReaderImpl.PushInternalEntity().