Terraria: System.Xml.XmlTextReaderImpl.ParseDtdFromParserContext
ParseDtdFromParserContext()
void System.Xml.XmlTextReaderImpl.ParseDtdFromParserContext () inline private
Definition at line 7973 of file XmlTextReaderImpl.cs.
    {
        IDtdParser dtdParser = DtdParser.Create();
        _dtdInfo = dtdParser.ParseFreeFloatingDtd(_fragmentParserContext.BaseURI, _fragmentParserContext.DocTypeName, _fragmentParserContext.PublicId, _fragmentParserContext.SystemId, _fragmentParserContext.InternalSubset, new DtdParserProxy(this));
        if ((_validatingReaderCompatFlag || !_v1Compat) && (_dtdInfo.HasDefaultAttributes || _dtdInfo.HasNonCDataAttributes))
        {
            _addDefaultAttributesAndNormalize = true;
        }
    }
References System.Xml.XmlTextReaderImpl._addDefaultAttributesAndNormalize, System.Xml.XmlTextReaderImpl._dtdInfo, System.Xml.XmlTextReaderImpl._fragmentParserContext, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl._validatingReaderCompatFlag, System.Xml.XmlParserContext.BaseURI, System.Xml.DtdParser.Create(), System.Xml.XmlParserContext.DocTypeName, System.Xml.IDtdInfo.HasDefaultAttributes, System.Xml.IDtdInfo.HasNonCDataAttributes, System.Xml.XmlParserContext.InternalSubset, System.Xml.XmlParserContext.PublicId, and System.Xml.XmlParserContext.SystemId.
Referenced by System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(), and System.Xml.XmlTextReaderImpl.ProcessDtdFromParserContext().