Terraria: System.Xml.XmlTextReaderImpl.Skip
Skip()
override void System.Xml.XmlTextReaderImpl.Skip () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 2098 of file XmlTextReaderImpl.cs.
    {
        if (_readState != ReadState.Interactive)
        {
            return;
        }
        if (InAttributeValueIterator)
        {
            FinishAttributeValueIterator();
            _curNode = _nodes[_index];
        }
        else
        {
            switch (_parsingFunction)
            {
            case ParsingFunction.InIncrementalRead:
                FinishIncrementalRead();
                break;
            case ParsingFunction.PartialTextValue:
                SkipPartialTextValue();
                break;
            case ParsingFunction.InReadValueChunk:
                FinishReadValueChunk();
                break;
            case ParsingFunction.InReadContentAsBinary:
                FinishReadContentAsBinary();
                break;
            case ParsingFunction.InReadElementContentAsBinary:
                FinishReadElementContentAsBinary();
                break;
            }
        }
        XmlNodeType type = _curNode.type;
        if (type != XmlNodeType.Element)
        {
            if (type != XmlNodeType.Attribute)
            {
                goto IL_00dc;
            }
            _outerReader.MoveToElement();
        }
        if (!_curNode.IsEmptyElement)
        {
            int index = _index;
            _parsingMode = ParsingMode.SkipContent;
            while (_outerReader.Read() && _index > index)
            {
            }
            _parsingMode = ParsingMode.Full;
        }
        goto IL_00dc;
        IL_00dc:
        _outerReader.Read();
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._readState, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.FinishAttributeValueIterator(), System.Xml.XmlTextReaderImpl.FinishIncrementalRead(), System.Xml.XmlTextReaderImpl.FinishReadContentAsBinary(), System.Xml.XmlTextReaderImpl.FinishReadElementContentAsBinary(), System.Xml.XmlTextReaderImpl.FinishReadValueChunk(), System.index, System.Xml.XmlTextReaderImpl.NodeData.IsEmptyElement, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.Read(), System.Xml.XmlTextReaderImpl.SkipPartialTextValue(), System.type, and System.Xml.XmlTextReaderImpl.NodeData.type.
Referenced by System.Xml.XmlTextReader.Skip().