Terraria: System.Xml.XmlTextReaderImpl.FinishOtherValueIteratorAsync
FinishOtherValueIteratorAsync()
async Task System.Xml.XmlTextReaderImpl.FinishOtherValueIteratorAsync () inline private
Definition at line 11415 of file XmlTextReaderImpl.cs.
    {
        switch (_parsingFunction)
        {
        case ParsingFunction.InReadValueChunk:
            if (_incReadState == IncrementalReadState.ReadValueChunk_OnPartialValue)
            {
                await FinishPartialValueAsync().ConfigureAwait(continueOnCapturedContext: false);
                _incReadState = IncrementalReadState.ReadValueChunk_OnCachedValue;
            }
            else if (_readValueOffset > 0)
            {
                _curNode.SetValue(_curNode.StringValue.Substring(_readValueOffset));
                _readValueOffset = 0;
            }
            break;
        case ParsingFunction.InReadContentAsBinary:
        case ParsingFunction.InReadElementContentAsBinary:
            switch (_incReadState)
            {
            case IncrementalReadState.ReadContentAsBinary_OnPartialValue:
                await FinishPartialValueAsync().ConfigureAwait(continueOnCapturedContext: false);
                _incReadState = IncrementalReadState.ReadContentAsBinary_OnCachedValue;
                break;
            case IncrementalReadState.ReadContentAsBinary_OnCachedValue:
                if (_readValueOffset > 0)
                {
                    _curNode.SetValue(_curNode.StringValue.Substring(_readValueOffset));
                    _readValueOffset = 0;
                }
                break;
            case IncrementalReadState.ReadContentAsBinary_End:
                _curNode.SetValue(string.Empty);
                break;
            }
            break;
        case ParsingFunction.InReadAttributeValue:
            break;
        }
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadState, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readValueOffset, System.Xml.XmlTextReaderImpl.FinishPartialValueAsync(), System.Xml.XmlTextReaderImpl.NodeData.SetValue(), and System.Xml.XmlTextReaderImpl.NodeData.StringValue.
Referenced by System.Xml.XmlTextReaderImpl._GetValueAsync().