Terraria: System.Xml.XmlTextReaderImpl.ReadContentAsBase64
ReadContentAsBase64()
override int System.Xml.XmlTextReaderImpl.ReadContentAsBase64 (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 2282 of file XmlTextReaderImpl.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (_parsingFunction == ParsingFunction.InReadContentAsBinary)
        {
            if (_incReadDecoder == _base64Decoder)
            {
                return ReadContentAsBinary(buffer, index, count);
            }
        }
        else
        {
            if (_readState != ReadState.Interactive)
            {
                return 0;
            }
            if (_parsingFunction == ParsingFunction.InReadElementContentAsBinary)
            {
                throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
            }
            if (!XmlReader.CanReadContentAs(_curNode.type))
            {
                throw CreateReadContentAsException("ReadContentAsBase64");
            }
            if (!InitReadContentAsBinary())
            {
                return 0;
            }
        }
        InitBase64Decoder();
        return ReadContentAsBinary(buffer, index, count);
    }
References System.Xml.XmlTextReaderImpl._base64Decoder, System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readState, System.buffer, System.Xml.XmlReader.CanReadContentAs(), System.count, System.Xml.XmlReader.CreateReadContentAsException(), System.index, System.Xml.XmlTextReaderImpl.InitBase64Decoder(), System.Xml.XmlTextReaderImpl.InitReadContentAsBinary(), System.Xml.XmlTextReaderImpl.ReadContentAsBinary(), System.Xml.XmlTextReaderImpl.NodeData.type, and System.SR.Xml_MixingBinaryContentMethods.
Referenced by System.Xml.XmlTextReader.ReadContentAsBase64().