Terraria: System.Xml.XmlTextReaderImpl.ParsePIAsync
ParsePIAsync() [2/2]
async Task< bool > System.Xml.XmlTextReaderImpl.ParsePIAsync (StringBuilder piInDtdStringBuilder) inline private
Definition at line 11701 of file XmlTextReaderImpl.cs.
    {
        if (_parsingMode == ParsingMode.Full)
        {
            _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
        }
        int num = await ParseNameAsync().ConfigureAwait(continueOnCapturedContext: false);
        string text = _nameTable.Add(_ps.chars, _ps.charPos, num - _ps.charPos);
        if (string.Equals(text, "xml", StringComparison.OrdinalIgnoreCase))
        {
            Throw(text.Equals("xml") ? System.SR.Xml_XmlDeclNotFirst : System.SR.Xml_InvalidPIName, text);
        }
        _ps.charPos = num;
        if (piInDtdStringBuilder == null)
        {
            if (!_ignorePIs && _parsingMode == ParsingMode.Full)
            {
                _curNode.SetNamedNode(XmlNodeType.ProcessingInstruction, text);
            }
        }
        else
        {
            piInDtdStringBuilder.Append(text);
        }
        char ch = _ps.chars[_ps.charPos];
        if (await EatWhitespacesAsync(piInDtdStringBuilder).ConfigureAwait(continueOnCapturedContext: false) == 0)
        {
            if (_ps.charsUsed - _ps.charPos < 2)
            {
                await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            if (ch != '?' || _ps.chars[_ps.charPos + 1] != '>')
            {
                Throw(System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(_ps.chars, _ps.charsUsed, _ps.charPos));
            }
        }
        (int, int, bool) tuple = await ParsePIValueAsync().ConfigureAwait(continueOnCapturedContext: false);
        var (num2, num3, _) = tuple;
        if (tuple.Item3)
        {
            if (piInDtdStringBuilder == null)
            {
                if (_ignorePIs)
                {
                    return false;
                }
                if (_parsingMode == ParsingMode.Full)
                {
                    _curNode.SetValue(_ps.chars, num2, num3 - num2);
                }
            }
            else
            {
                piInDtdStringBuilder.Append(_ps.chars, num2, num3 - num2);
            }
        }
        else
        {
            StringBuilder sb;
            if (piInDtdStringBuilder == null)
            {
                if (_ignorePIs || _parsingMode != 0)
                {
                    (int, int, bool) tuple3;
                    do
                    {
                        tuple3 = await ParsePIValueAsync().ConfigureAwait(continueOnCapturedContext: false);
                        _ = tuple3.Item1;
                        _ = tuple3.Item2;
                    }
                    while (!tuple3.Item3);
                    return false;
                }
                sb = _stringBuilder;
            }
            else
            {
                sb = piInDtdStringBuilder;
            }
            (int, int, bool) tuple4;
            do
            {
                sb.Append(_ps.chars, num2, num3 - num2);
                tuple4 = await ParsePIValueAsync().ConfigureAwait(continueOnCapturedContext: false);
                (num2, num3, _) = tuple4;
            }
            while (!tuple4.Item3);
            sb.Append(_ps.chars, num2, num3 - num2);
            if (piInDtdStringBuilder == null)
            {
                _curNode.SetValue(_stringBuilder.ToString());
                _stringBuilder.Length = 0;
            }
        }
        return true;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._ignorePIs, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Xml.XmlNameTable.Add(), System.Text.StringBuilder.Append(), System.Xml.XmlException.BuildCharExceptionArgs(), System.ch, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespacesAsync(), System.Xml.XmlTextReaderImpl.int, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseNameAsync(), System.Xml.XmlTextReaderImpl.ParsePIValueAsync(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode(), System.Xml.XmlTextReaderImpl.NodeData.SetValue(), System.text, System.Xml.XmlTextReaderImpl.Throw(), System.Text.StringBuilder.ToString(), System.SR.Xml_BadNameChar, System.SR.Xml_InvalidPIName, and System.SR.Xml_XmlDeclNotFirst.