Terraria: System.Xml.XmlTextReaderImpl.Throw
Throw() [3/11]
void System.Xml.XmlTextReaderImpl.Throw (int pos, string res, string arg) inline private
Definition at line 2925 of file XmlTextReaderImpl.cs.
    {
        _ps.charPos = pos;
        Throw(res, arg);
    }
References System.Xml.Dictionary, and System.Xml.XmlTextReaderImpl.Throw().
Referenced by System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), System.Xml.XmlTextReaderImpl.AddNamespace(), System.Xml.XmlTextReaderImpl.AttributeDuplCheck(), System.Xml.XmlTextReaderImpl.CheckEncoding(), System.Xml.XmlTextReaderImpl.DetectEncoding(), System.Xml.XmlTextReaderImpl.DtdParserProxy_Throw(), System.Xml.XmlTextReaderImpl.EatWhitespaces(), System.Xml.XmlTextReaderImpl.EatWhitespacesAsync(), System.Xml.XmlTextReaderImpl.FinishReadElementContentAsBinary(), System.Xml.XmlTextReaderImpl.FinishReadElementContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.XmlTextReaderImpl.HandleEntityReference(), System.Xml.XmlTextReaderImpl.HandleEntityReferenceAsync(), System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(), System.Xml.XmlTextReaderImpl.HandleGeneralEntityReferenceAsync(), System.Xml.XmlTextReaderImpl.InitFragmentReader(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinary(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.InvalidCharRecovery(), System.Xml.XmlTextReaderImpl.LookupNamespace(), System.Xml.XmlTextReaderImpl.OnNamespaceDecl(), System.Xml.XmlTextReaderImpl.OnXmlReservedAttribute(), System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync(), System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), System.Xml.XmlTextReaderImpl.ParseCDataOrCommentTupleAsync(), System.Xml.XmlTextReaderImpl.ParseDoctypeDecl(), System.Xml.XmlTextReaderImpl.ParseDoctypeDeclAsync(), System.Xml.XmlTextReaderImpl.ParseDocumentContent(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ParseEntity(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync(), System.Xml.XmlTextReaderImpl.ParseElementAsync_NoAttributes(), System.Xml.XmlTextReaderImpl.ParseElementAsync_ReadData(), System.Xml.XmlTextReaderImpl.ParseElementContent(), System.Xml.XmlTextReaderImpl.ParseElementContentAsync(), System.Xml.XmlTextReaderImpl.ParseEntityName(), System.Xml.XmlTextReaderImpl.ParseEntityNameAsync(), System.Xml.XmlTextReaderImpl.ParseNumericCharRef(), System.Xml.XmlTextReaderImpl.ParseNumericCharRefAsync(), System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(), System.Xml.XmlTextReaderImpl.ParsePI(), System.Xml.XmlTextReaderImpl.ParsePIAsync(), System.Xml.XmlTextReaderImpl.ParsePIValue(), System.Xml.XmlTextReaderImpl.ParsePIValueAsync(), System.Xml.XmlTextReaderImpl.ParseQName(), System.Xml.XmlTextReaderImpl.ParseQNameAsync(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespaceAsync(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync_ReadData(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubset(), System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubsetAsync(), System.Xml.XmlTextReaderImpl.ReadValueChunk(), System.Xml.XmlTextReaderImpl.ReadValueChunkAsync(), System.Xml.XmlTextReaderImpl.RegisterEntity(), System.Xml.XmlTextReaderImpl.ResetState(), System.Xml.XmlTextReaderImpl.ReThrow(), System.Xml.XmlTextReaderImpl.SkipDtd(), System.Xml.XmlTextReaderImpl.SkipDtdAsync(), System.Xml.XmlTextReaderImpl.SkipUntil(), System.Xml.XmlTextReaderImpl.SkipUntilAsync(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowExpectingWhitespace(), System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), System.Xml.XmlTextReaderImpl.ThrowTagMismatch(), System.Xml.XmlTextReaderImpl.ThrowTagMismatchAsync(), System.Xml.XmlTextReaderImpl.ThrowUnclosedElements(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), and System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo().