Terraria: System.Xml.XmlTextReaderImpl.FinishInitAsync
FinishInitAsync()
Task System.Xml.XmlTextReaderImpl.FinishInitAsync () inline private
Definition at line 8601 of file XmlTextReaderImpl.cs.
    {
        return _laterInitParam.initType switch
        {
            InitInputType.UriString => FinishInitUriStringAsync(),
            InitInputType.Stream => FinishInitStreamAsync(),
            InitInputType.TextReader => FinishInitTextReaderAsync(),
            _ => Task.CompletedTask,
        };
    }
References System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.FinishInitStreamAsync(), System.Xml.XmlTextReaderImpl.FinishInitTextReaderAsync(), and System.Xml.XmlTextReaderImpl.FinishInitUriStringAsync().
Referenced by System.Xml.XmlTextReaderImpl.ReadAsync().