Terraria: System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync
ReadContentAsBinaryAsync()
async Task< int > System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync (byte[] buffer, int index, int count) inline private
Definition at line 12891 of file XmlTextReaderImpl.cs.
    {
        if (_incReadState == IncrementalReadState.ReadContentAsBinary_End)
        {
            return 0;
        }
        _incReadDecoder.SetNextOutputBuffer(buffer, index, count);
        ParsingFunction tmp;
        while (true)
        {
            int charsRead = 0;
            try
            {
                charsRead = _curNode.CopyToBinary(_incReadDecoder, _readValueOffset);
            }
            catch (XmlException e)
            {
                _curNode.AdjustLineInfo(_readValueOffset, _ps.eolNormalized, ref _incReadLineInfo);
                ReThrow(e, _incReadLineInfo.lineNo, _incReadLineInfo.linePos);
            }
            _readValueOffset += charsRead;
            if (_incReadDecoder.IsFull)
            {
                return _incReadDecoder.DecodedCount;
            }
            if (_incReadState == IncrementalReadState.ReadContentAsBinary_OnPartialValue)
            {
                _curNode.SetValue(string.Empty);
                bool flag = false;
                int num = 0;
                int num2 = 0;
                while (!_incReadDecoder.IsFull && !flag)
                {
                    int outOrChars = 0;
                    _incReadLineInfo.Set(_ps.LineNo, _ps.LinePos);
                    (int, int, int, bool) tuple = await ParseTextAsync(outOrChars).ConfigureAwait(continueOnCapturedContext: false);
                    (num, num2, _, _) = tuple;
                    _ = tuple.Item3;
                    flag = tuple.Item4;
                    try
                    {
                        charsRead = _incReadDecoder.Decode(_ps.chars, num, num2 - num);
                    }
                    catch (XmlException e2)
                    {
                        ReThrow(e2, _incReadLineInfo.lineNo, _incReadLineInfo.linePos);
                    }
                    num += charsRead;
                }
                _incReadState = (flag ? IncrementalReadState.ReadContentAsBinary_OnCachedValue : IncrementalReadState.ReadContentAsBinary_OnPartialValue);
                _readValueOffset = 0;
                if (_incReadDecoder.IsFull)
                {
                    _curNode.SetValue(_ps.chars, num, num2 - num);
                    AdjustLineInfo(_ps.chars, num - charsRead, num, _ps.eolNormalized, ref _incReadLineInfo);
                    _curNode.SetLineInfo(_incReadLineInfo.lineNo, _incReadLineInfo.linePos);
                    return _incReadDecoder.DecodedCount;
                }
            }
            tmp = _parsingFunction;
            _parsingFunction = _nextParsingFunction;
            _nextParsingFunction = _nextNextParsingFunction;
            if (!(await MoveToNextContentNodeAsync(moveIfOnContentNode: true).ConfigureAwait(continueOnCapturedContext: false)))
            {
                break;
            }
            SetupReadContentAsBinaryState(tmp);
            _incReadLineInfo.Set(_curNode.LineNo, _curNode.LinePos);
        }
        SetupReadContentAsBinaryState(tmp);
        _incReadState = IncrementalReadState.ReadContentAsBinary_End;
        return _incReadDecoder.DecodedCount;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._incReadLineInfo, System.Xml.XmlTextReaderImpl._incReadState, System.Xml.XmlTextReaderImpl._nextNextParsingFunction, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._readValueOffset, System.Xml.XmlTextReaderImpl.AdjustLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.AdjustLineInfo(), System.buffer, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlTextReaderImpl.NodeData.CopyToBinary(), System.count, System.Xml.IncrementalReadDecoder.Decode(), System.Xml.IncrementalReadDecoder.DecodedCount, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.eolNormalized, System.index, System.Xml.XmlTextReaderImpl.int, System.Xml.IncrementalReadDecoder.IsFull, System.Xml.LineInfo.lineNo, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.NodeData.LineNo, System.Xml.LineInfo.linePos, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.NodeData.LinePos, System.Xml.XmlTextReaderImpl.MoveToNextContentNodeAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.ReThrow(), System.Xml.LineInfo.Set(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.IncrementalReadDecoder.SetNextOutputBuffer(), System.Xml.XmlTextReaderImpl.SetupReadContentAsBinaryState(), and System.Xml.XmlTextReaderImpl.NodeData.SetValue().
Referenced by System.Xml.XmlTextReaderImpl.ReadContentAsBase64_AsyncHelper(), System.Xml.XmlTextReaderImpl.ReadContentAsBase64Async(), System.Xml.XmlTextReaderImpl.ReadContentAsBinHexAsync(), and System.Xml.XmlTextReaderImpl.ReadElementContentAsBinaryAsync().