Terraria: System.Xml.XmlTextReaderImpl.UnDecodeChars
UnDecodeChars()
void System.Xml.XmlTextReaderImpl.UnDecodeChars () inline private
Definition at line 3428 of file XmlTextReaderImpl.cs.
    {
        if (_maxCharactersInDocument > 0)
        {
            _charactersInDocument -= _ps.charsUsed - _ps.charPos;
        }
        if (_maxCharactersFromEntities > 0 && InEntity)
        {
            _charactersFromEntities -= _ps.charsUsed - _ps.charPos;
        }
        _ps.bytePos = _documentStartBytePos;
        if (_ps.charPos > 0)
        {
            _ps.bytePos += _ps.encoding.GetByteCount(_ps.chars, 0, _ps.charPos);
        }
        _ps.charsUsed = _ps.charPos;
        _ps.isEof = false;
    }
References System.Xml.XmlTextReaderImpl._charactersFromEntities, System.Xml.XmlTextReaderImpl._charactersInDocument, System.Xml.XmlTextReaderImpl._documentStartBytePos, System.Xml.XmlTextReaderImpl._maxCharactersFromEntities, System.Xml.XmlTextReaderImpl._maxCharactersInDocument, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.encoding, and System.Text.Encoding.GetByteCount().
Referenced by System.Xml.XmlTextReaderImpl.SwitchEncoding(), and System.Xml.XmlTextReaderImpl.SwitchEncodingAsync().