Terraria: System.Xml.XmlTextReaderImpl.InitBase64Decoder
InitBase64Decoder()
void System.Xml.XmlTextReaderImpl.InitBase64Decoder () inline private
Definition at line 8332 of file XmlTextReaderImpl.cs.
    {
        if (_base64Decoder == null)
        {
            _base64Decoder = new Base64Decoder();
        }
        else
        {
            _base64Decoder.Reset();
        }
        _incReadDecoder = _base64Decoder;
    }
References System.Xml.XmlTextReaderImpl._base64Decoder, System.Xml.XmlTextReaderImpl._incReadDecoder, and System.Xml.Base64Decoder.Reset().
Referenced by System.Xml.XmlTextReaderImpl.ReadBase64(), System.Xml.XmlTextReaderImpl.ReadContentAsBase64(), System.Xml.XmlTextReaderImpl.ReadContentAsBase64_AsyncHelper(), System.Xml.XmlTextReaderImpl.ReadContentAsBase64Async(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64Async(), and System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64Async_Helper().