Terraria: System.Xml.XmlTextReaderImpl.ParseAttributes
ParseAttributes()
void System.Xml.XmlTextReaderImpl.ParseAttributes () inline private
Definition at line 4531 of file XmlTextReaderImpl.cs.
    {
        int num = _ps.charPos;
        char[] chars = _ps.chars;
        NodeData nodeData = null;
        while (true)
        {
            int num2 = 0;
            while (true)
            {
                char c;
                int num3;
                if (XmlCharType.IsWhiteSpace(c = chars[num]))
                {
                    switch (c)
                    {
                    case '\n':
                        OnNewLine(num + 1);
                        num2++;
                        goto IL_0085;
                    case '\r':
                        if (chars[num + 1] == '\n')
{
                            OnNewLine(num + 2);
                            num2++;
                            num++;
                            goto IL_0085;
                        }
                        if (num + 1 != _ps.charsUsed)
{
                            OnNewLine(num + 1);
                            num2++;
                            goto IL_0085;
                        }
                        break;
                    default:
                        goto IL_0085;
                    }
                    _ps.charPos = num;
                }
                else
                {
                    num3 = 0;
                    char c2;
                    if (XmlCharType.IsStartNCNameSingleChar(c2 = chars[num]))
                    {
                        num3 = 1;
                    }
                    if (num3 != 0)
                    {
                        goto IL_0171;
                    }
                    if (c2 == '>')
                    {
                        _ps.charPos = num + 1;
                        _parsingFunction = ParsingFunction.MoveToElementContent;
                        goto IL_0438;
                    }
                    if (c2 == '/')
                    {
                        if (num + 1 != _ps.charsUsed)
{
                            if (chars[num + 1] == '>')
{
                                _ps.charPos = num + 2;
                                _curNode.IsEmptyElement = true;
                                _nextParsingFunction = _parsingFunction;
                                _parsingFunction = ParsingFunction.PopEmptyElementContext;
                                goto IL_0438;
                            }
                            ThrowUnexpectedToken(num + 1, ">");
                            goto IL_0171;
                        }
                    }
                    else if (num != _ps.charsUsed)
                    {
                        if (c2 != ':' || _supportNamespaces)
{
                            Throw(num, System.SR.Xml_BadStartNameChar, XmlException.BuildCharExceptionArgs(chars, _ps.charsUsed, num));
                        }
                        goto IL_0171;
                    }
                }
                _ps.lineNo -= num2;
                if (ReadData() != 0)
                {
                    num = _ps.charPos;
                    chars = _ps.chars;
                }
                else
                {
                    ThrowUnclosedElements();
                }
                break;
                IL_0438:
                if (_addDefaultAttributesAndNormalize)
                {
                    AddDefaultAttributesAndNormalize();
                }
                ElementNamespaceLookup();
                if (_attrNeedNamespaceLookup)
                {
                    AttributeNamespaceLookup();
                    _attrNeedNamespaceLookup = false;
                }
                if (_attrDuplWalkCount >= 250)
                {
                    AttributeDuplCheck();
                }
                return;
                IL_0085:
                num++;
                continue;
                IL_0171:
                if (num == _ps.charPos)
                {
                    ThrowExpectingWhitespace(num);
                }
                _ps.charPos = num;
                int linePos = _ps.LinePos;
                int colonPos = -1;
                num += num3;
                while (true)
                {
                    char c3;
                    if (XmlCharType.IsNCNameSingleChar(c3 = chars[num]))
                    {
                        num++;
                        continue;
                    }
                    if (c3 == ':')
                    {
                        if (colonPos != -1)
{
                            if (_supportNamespaces)
{
                                Throw(num, System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(':', '\0'));
                                break;
                            }
                            num++;
                            continue;
                        }
                        colonPos = num;
                        num++;
                        if (XmlCharType.IsStartNCNameSingleChar(chars[num]))
{
                            num++;
                            continue;
                        }
                        num = ParseQName(out colonPos);
                        chars = _ps.chars;
                        break;
                    }
                    if (num + 1 >= _ps.charsUsed)
                    {
                        num = ParseQName(out colonPos);
                        chars = _ps.chars;
                    }
                    break;
                }
                nodeData = AddAttribute(num, colonPos);
                nodeData.SetLineInfo(_ps.LineNo, linePos);
                if (chars[num] != '=')
                {
                    _ps.charPos = num;
                    EatWhitespaces(null);
                    num = _ps.charPos;
                    if (chars[num] != '=')
                    {
                        ThrowUnexpectedToken("=");
                    }
                }
                num++;
                char c4 = chars[num];
                if (c4 != '"' && c4 != '\'')
                {
                    _ps.charPos = num;
                    EatWhitespaces(null);
                    num = _ps.charPos;
                    c4 = chars[num];
                    if (c4 != '"' && c4 != '\'')
                    {
                        ThrowUnexpectedToken("\"", "'");
                    }
                }
                num++;
                _ps.charPos = num;
                nodeData.quoteChar = c4;
                nodeData.SetLineInfo2(_ps.LineNo, _ps.LinePos);
                char c5;
                while (XmlCharType.IsAttributeValueChar(c5 = chars[num]))
                {
                    num++;
                }
                if (c5 == c4)
                {
                    nodeData.SetValue(chars, _ps.charPos, num - _ps.charPos);
                    num++;
                    _ps.charPos = num;
                }
                else
                {
                    ParseAttributeValueSlow(num, c4, nodeData);
                    num = _ps.charPos;
                    chars = _ps.chars;
                }
                if (nodeData.prefix.Length == 0)
                {
                    if (Ref.Equal(nodeData.localName, _xmlNs))
                    {
                        OnDefaultNamespaceDecl(nodeData);
                    }
                }
                else if (Ref.Equal(nodeData.prefix, _xmlNs))
                {
                    OnNamespaceDecl(nodeData);
                }
                else if (Ref.Equal(nodeData.prefix, _xml))
                {
                    OnXmlReservedAttribute(nodeData);
                }
                break;
            }
        }
    }
References System.Xml.XmlTextReaderImpl._addDefaultAttributesAndNormalize, System.Xml.XmlTextReaderImpl._attrDuplWalkCount, System.Xml.XmlTextReaderImpl._attrNeedNamespaceLookup, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._supportNamespaces, System.Xml.XmlTextReaderImpl._xml, System.Xml.XmlTextReaderImpl._xmlNs, System.Xml.XmlTextReaderImpl.AddAttribute(), System.Xml.XmlTextReaderImpl.AddDefaultAttributesAndNormalize(), System.Xml.XmlTextReaderImpl.AttributeDuplCheck(), System.Xml.XmlTextReaderImpl.AttributeNamespaceLookup(), System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespaces(), System.Xml.XmlTextReaderImpl.ElementNamespaceLookup(), System.Xml.Ref.Equal(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.XmlCharType.IsStartNCNameSingleChar(), System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.OnDefaultNamespaceDecl(), System.Xml.XmlTextReaderImpl.OnNamespaceDecl(), System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.OnXmlReservedAttribute(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ParseQName(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowExpectingWhitespace(), System.Xml.XmlTextReaderImpl.ThrowUnclosedElements(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.SR.Xml_BadNameChar, and System.SR.Xml_BadStartNameChar.
Referenced by System.Xml.XmlTextReaderImpl.ParseElement().