Terraria: System.Xml.XmlTextReaderImpl.SkipPartialTextValue
SkipPartialTextValue()
void System.Xml.XmlTextReaderImpl.SkipPartialTextValue () inline private
Definition at line 5497 of file XmlTextReaderImpl.cs.
    {
        int outOrChars = 0;
        _parsingFunction = _nextParsingFunction;
        int startPos;
        int endPos;
        while (!ParseText(out startPos, out endPos, ref outOrChars))
        {
        }
    }
References System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.Dictionary, and System.Xml.XmlTextReaderImpl.ParseText().
Referenced by System.Xml.XmlTextReaderImpl.FinishReadContentAsBinary(), System.Xml.XmlTextReaderImpl.FinishReadValueChunk(), System.Xml.XmlTextReaderImpl.Read(), and System.Xml.XmlTextReaderImpl.Skip().