Terraria: System.Xml.XmlTextReaderImpl.ParseEndElement
ParseEndElement()
void System.Xml.XmlTextReaderImpl.ParseEndElement () inline private
Definition at line 4424 of file XmlTextReaderImpl.cs.
    {
        NodeData nodeData = _nodes[_index - 1];
        int length = nodeData.prefix.Length;
        int length2 = nodeData.localName.Length;
        while (_ps.charsUsed - _ps.charPos < length + length2 + 1 && ReadData() != 0)
        {
        }
        char[] chars = _ps.chars;
        int num;
        if (nodeData.prefix.Length == 0)
        {
            if (!XmlConvert.StrEqual(chars, _ps.charPos, length2, nodeData.localName))
            {
                ThrowTagMismatch(nodeData);
            }
            num = length2;
        }
        else
        {
            int num2 = _ps.charPos + length;
            if (!XmlConvert.StrEqual(chars, _ps.charPos, length, nodeData.prefix) || chars[num2] != ':' || !XmlConvert.StrEqual(chars, num2 + 1, length2, nodeData.localName))
            {
                ThrowTagMismatch(nodeData);
            }
            num = length2 + length + 1;
        }
        LineInfo lineInfo = new LineInfo(_ps.lineNo, _ps.LinePos);
        int num3;
        while (true)
        {
            num3 = _ps.charPos + num;
            chars = _ps.chars;
            if (num3 != _ps.charsUsed)
            {
                if (XmlCharType.IsNCNameSingleChar(chars[num3]) || chars[num3] == ':')
                {
                    ThrowTagMismatch(nodeData);
                }
                if (chars[num3] != '>')
                {
                    char c;
                    while (XmlCharType.IsWhiteSpace(c = chars[num3]))
                    {
                        num3++;
                        switch (c)
{
                        case '\n':
                            OnNewLine(num3);
                            break;
                        case '\r':
                            if (chars[num3] == '\n')
{
                                num3++;
                            }
                            else if (num3 == _ps.charsUsed && !_ps.isEof)
{
                                break;
                            }
                            OnNewLine(num3);
                            break;
                        }
                    }
                }
                if (chars[num3] == '>')
                {
                    break;
                }
                if (num3 != _ps.charsUsed)
                {
                    ThrowUnexpectedToken(num3, ">");
                }
            }
            if (ReadData() == 0)
            {
                ThrowUnclosedElements();
            }
        }
        _index--;
        _curNode = _nodes[_index];
        nodeData.lineInfo = lineInfo;
        nodeData.type = XmlNodeType.EndElement;
        _ps.charPos = num3 + 1;
        _nextParsingFunction = ((_index > 0) ? _parsingFunction : ParsingFunction.DocumentContent);
        _parsingFunction = ParsingFunction.PopElementContext;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.XmlCharType.IsWhiteSpace(), System.length, System.length2, System.Xml.XmlTextReaderImpl.ParsingState.lineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.ThrowTagMismatch(), System.Xml.XmlTextReaderImpl.ThrowUnclosedElements(), and System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken().
Referenced by System.Xml.XmlTextReaderImpl.ParseElementContent().