Terraria: System.Xml.XmlTextReaderImpl.ProcessDtdFromParserContext
ProcessDtdFromParserContext()
void System.Xml.XmlTextReaderImpl.ProcessDtdFromParserContext (XmlParserContext context) inline private
Definition at line 3237 of file XmlTextReaderImpl.cs.
    {
        switch (_dtdProcessing)
        {
        case DtdProcessing.Prohibit:
            ThrowWithoutLineInfo(System.SR.Xml_DtdIsProhibitedEx);
            break;
        case DtdProcessing.Parse:
            ParseDtdFromParserContext();
            break;
        case DtdProcessing.Ignore:
            break;
        }
    }
References System.Xml.XmlTextReaderImpl._dtdProcessing, System.Xml.XmlTextReaderImpl.ParseDtdFromParserContext(), System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), and System.SR.Xml_DtdIsProhibitedEx.
Referenced by System.Xml.XmlTextReaderImpl.FinishInitStream(), System.Xml.XmlTextReaderImpl.FinishInitTextReader(), and System.Xml.XmlTextReaderImpl.FinishInitUriString().