Terraria: System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinary
InitReadElementContentAsBinary()
bool System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinary () inline private
Definition at line 8002 of file XmlTextReaderImpl.cs.
    {
        bool isEmptyElement = _curNode.IsEmptyElement;
        _outerReader.Read();
        if (isEmptyElement)
        {
            return false;
        }
        if (!MoveToNextContentNode(moveIfOnContentNode: false))
        {
            if (_curNode.type != XmlNodeType.EndElement)
            {
                Throw(System.SR.Xml_InvalidNodeType, _curNode.type.ToString());
            }
            _outerReader.Read();
            return false;
        }
        SetupReadContentAsBinaryState(ParsingFunction.InReadElementContentAsBinary);
        _incReadLineInfo.Set(_curNode.LineNo, _curNode.LinePos);
        return true;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadLineInfo, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.XmlTextReaderImpl.NodeData.IsEmptyElement, System.Xml.XmlTextReaderImpl.NodeData.LineNo, System.Xml.XmlTextReaderImpl.NodeData.LinePos, System.Xml.XmlTextReaderImpl.MoveToNextContentNode(), System.Xml.XmlReader.Read(), System.Xml.LineInfo.Set(), System.Xml.XmlTextReaderImpl.SetupReadContentAsBinaryState(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.NodeData.type, and System.SR.Xml_InvalidNodeType.
Referenced by System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64(), and System.Xml.XmlTextReaderImpl.ReadElementContentAsBinHex().