Terraria: System.Xml.XmlTextReaderImpl.ParseEntityName
ParseEntityName()
string System.Xml.XmlTextReaderImpl.ParseEntityName () inline private
Definition at line 6912 of file XmlTextReaderImpl.cs.
    {
        int num;
        try
        {
            num = ParseName();
        }
        catch (XmlException)
        {
            Throw(System.SR.Xml_ErrorParsingEntityName);
            return null;
        }
        if (_ps.chars[num] != ';')
        {
            Throw(System.SR.Xml_ErrorParsingEntityName);
        }
        string result = _nameTable.Add(_ps.chars, _ps.charPos, num - _ps.charPos);
        _ps.charPos = num + 1;
        return result;
    }
References System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlNameTable.Add(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParseName(), System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_ErrorParsingEntityName.
Referenced by System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), and System.Xml.XmlTextReaderImpl.ParseEntityReference().