Terraria: System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference
HandleGeneralEntityReference()
EntityType System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference (string name, bool isInAttributeValue, bool pushFakeEntityIfNullResolver, int entityStartLinePos) inline private
Definition at line 5640 of file XmlTextReaderImpl.cs.
    {
        IDtdEntityInfo dtdEntityInfo = null;
        if (_dtdInfo == null && _fragmentParserContext != null && _fragmentParserContext.HasDtdInfo && _dtdProcessing == DtdProcessing.Parse)
        {
            ParseDtdFromParserContext();
        }
        if (_dtdInfo == null || (dtdEntityInfo = _dtdInfo.LookupEntity(name)) == null)
        {
            if (_disableUndeclaredEntityCheck)
            {
                SchemaEntity schemaEntity = new SchemaEntity(new XmlQualifiedName(name), isParameter: false);
                schemaEntity.Text = string.Empty;
                dtdEntityInfo = schemaEntity;
            }
            else
            {
                Throw(System.SR.Xml_UndeclaredEntity, name, _ps.LineNo, entityStartLinePos);
            }
        }
        if (dtdEntityInfo.IsUnparsedEntity)
        {
            if (_disableUndeclaredEntityCheck)
            {
                SchemaEntity schemaEntity2 = new SchemaEntity(new XmlQualifiedName(name), isParameter: false);
                schemaEntity2.Text = string.Empty;
                dtdEntityInfo = schemaEntity2;
            }
            else
            {
                Throw(System.SR.Xml_UnparsedEntityRef, name, _ps.LineNo, entityStartLinePos);
            }
        }
        if (_standalone && dtdEntityInfo.IsDeclaredInExternal)
        {
            Throw(System.SR.Xml_ExternalEntityInStandAloneDocument, dtdEntityInfo.Name, _ps.LineNo, entityStartLinePos);
        }
        if (dtdEntityInfo.IsExternal)
        {
            if (isInAttributeValue)
            {
                Throw(System.SR.Xml_ExternalEntityInAttValue, name, _ps.LineNo, entityStartLinePos);
                return EntityType.Skipped;
            }
            if (_parsingMode == ParsingMode.SkipContent)
            {
                return EntityType.Skipped;
            }
            if (IsResolverNull)
            {
                if (pushFakeEntityIfNullResolver)
                {
                    PushExternalEntity(dtdEntityInfo);
                    _curNode.entityId = _ps.entityId;
                    return EntityType.FakeExpanded;
                }
                return EntityType.Skipped;
            }
            PushExternalEntity(dtdEntityInfo);
            _curNode.entityId = _ps.entityId;
            if (!isInAttributeValue || !_validatingReaderCompatFlag)
            {
                return EntityType.Expanded;
            }
            return EntityType.ExpandedInAttribute;
        }
        if (_parsingMode == ParsingMode.SkipContent)
        {
            return EntityType.Skipped;
        }
        PushInternalEntity(dtdEntityInfo);
        _curNode.entityId = _ps.entityId;
        if (!isInAttributeValue || !_validatingReaderCompatFlag)
        {
            return EntityType.Expanded;
        }
        return EntityType.ExpandedInAttribute;
    }
References System.Xml.XmlTextReaderImpl._disableUndeclaredEntityCheck, System.Xml.XmlTextReaderImpl._dtdInfo, System.Xml.XmlTextReaderImpl._dtdProcessing, System.Xml.XmlTextReaderImpl._fragmentParserContext, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._standalone, System.Xml.XmlTextReaderImpl._validatingReaderCompatFlag, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.entityId, System.Xml.XmlParserContext.HasDtdInfo, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.IDtdInfo.LookupEntity(), System.Xml.XmlTextReaderImpl.ParseDtdFromParserContext(), System.Xml.XmlTextReaderImpl.PushExternalEntity(), System.Xml.XmlTextReaderImpl.PushInternalEntity(), System.Xml.XmlTextReaderImpl.Throw(), System.SR.Xml_ExternalEntityInAttValue, System.SR.Xml_ExternalEntityInStandAloneDocument, System.SR.Xml_UndeclaredEntity, and System.SR.Xml_UnparsedEntityRef.
Referenced by System.Xml.XmlTextReaderImpl.HandleEntityReference(), and System.Xml.XmlTextReaderImpl.ResolveEntity().