Terraria: System.Xml.XmlTextReaderImpl.FinishInitTextReaderAsync
FinishInitTextReaderAsync()
async Task System.Xml.XmlTextReaderImpl.FinishInitTextReaderAsync () inline private
Definition at line 8657 of file XmlTextReaderImpl.cs.
    {
        await InitTextReaderInputAsync(_reportedBaseUri, _laterInitParam.inputTextReader).ConfigureAwait(continueOnCapturedContext: false);
        _reportedEncoding = _ps.encoding;
        if (_laterInitParam.inputContext != null && _laterInitParam.inputContext.HasDtdInfo)
        {
            await ProcessDtdFromParserContextAsync(_laterInitParam.inputContext).ConfigureAwait(continueOnCapturedContext: false);
        }
        _laterInitParam = null;
    }
References System.Xml.XmlTextReaderImpl._laterInitParam, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlParserContext.HasDtdInfo, System.Xml.XmlTextReaderImpl.InitTextReaderInputAsync(), System.Xml.XmlTextReaderImpl.LaterInitParam.inputContext, System.Xml.XmlTextReaderImpl.LaterInitParam.inputTextReader, and System.Xml.XmlTextReaderImpl.ProcessDtdFromParserContextAsync().
Referenced by System.Xml.XmlTextReaderImpl.FinishInitAsync().