Terraria: System.Xml.XmlTextReaderImpl.ParseElementContent
ParseElementContent()
bool System.Xml.XmlTextReaderImpl.ParseElementContent () inline private
Definition at line 4099 of file XmlTextReaderImpl.cs.
    {
        while (true)
        {
            int charPos = _ps.charPos;
            char[] chars = _ps.chars;
            switch (chars[charPos])
            {
            case '<':
                switch (chars[charPos + 1])
                {
                case '?':
                    _ps.charPos = charPos + 2;
                    if (!ParsePI())
                    {
                        continue;
                    }
                    return true;
                case '!':
                    charPos += 2;
                    if (_ps.charsUsed - charPos < 2)
                    {
                        break;
                    }
                    if (chars[charPos] == '-')
                    {
                        if (chars[charPos + 1] == '-')
{
                            _ps.charPos = charPos + 2;
                            if (!ParseComment())
{
                                continue;
                            }
                            return true;
                        }
                        ThrowUnexpectedToken(charPos + 1, "-");
                    }
                    else if (chars[charPos] == '[')
                    {
                        charPos++;
                        if (_ps.charsUsed - charPos >= 6)
{
                            if (XmlConvert.StrEqual(chars, charPos, 6, "CDATA["))
{
                                _ps.charPos = charPos + 6;
                                ParseCData();
                                return true;
                            }
                            ThrowUnexpectedToken(charPos, "CDATA[");
                        }
                    }
                    else if (ParseUnexpectedToken(charPos) == "DOCTYPE")
                    {
                        Throw(System.SR.Xml_BadDTDLocation);
                    }
                    else
                    {
                        ThrowUnexpectedToken(charPos, "<!--", "<[CDATA[");
                    }
                    break;
                case '/':
                    _ps.charPos = charPos + 2;
                    ParseEndElement();
                    return true;
                default:
                    if (charPos + 1 != _ps.charsUsed)
                    {
                        _ps.charPos = charPos + 1;
                        ParseElement();
                        return true;
                    }
                    break;
                }
                break;
            case '&':
                if (!ParseText())
                {
                    continue;
                }
                return true;
            default:
                if (charPos != _ps.charsUsed)
                {
                    if (!ParseText())
                    {
                        continue;
                    }
                    return true;
                }
                break;
            }
            if (ReadData() != 0)
            {
                continue;
            }
            if (_ps.charsUsed - _ps.charPos != 0)
            {
                ThrowUnclosedElements();
            }
            if (!InEntity)
            {
                if (_index == 0 && _fragmentType != XmlNodeType.Document)
                {
                    OnEof();
                    return false;
                }
                ThrowUnclosedElements();
            }
            if (HandleEntityEnd(checkEntityNesting: true))
            {
                break;
            }
        }
        SetupEndEntityNodeInContent();
        return true;
    }
References System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.XmlTextReaderImpl.OnEof(), System.Xml.XmlTextReaderImpl.ParseCData(), System.Xml.XmlTextReaderImpl.ParseComment(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseEndElement(), System.Xml.XmlTextReaderImpl.ParsePI(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseUnexpectedToken(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowUnclosedElements(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), and System.SR.Xml_BadDTDLocation.
Referenced by System.Xml.XmlTextReaderImpl.Read().