Terraria: System.Xml.XmlTextReaderImpl.ThrowUnclosedElements
ThrowUnclosedElements()
void System.Xml.XmlTextReaderImpl.ThrowUnclosedElements () inline private
Definition at line 4216 of file XmlTextReaderImpl.cs.
    {
        if (_index == 0 && _curNode.type != XmlNodeType.Element)
        {
            Throw(_ps.charsUsed, System.SR.Xml_UnexpectedEOF1);
            return;
        }
        int num = ((_parsingFunction == ParsingFunction.InIncrementalRead) ? _index : (_index - 1));
        _stringBuilder.Length = 0;
        while (num >= 0)
        {
            NodeData nodeData = _nodes[num];
            if (nodeData.type == XmlNodeType.Element)
            {
                _stringBuilder.Append(nodeData.GetNameWPrefix(_nameTable));
                if (num > 0)
                {
                    _stringBuilder.Append(", ");
                }
                else
                {
                    _stringBuilder.Append('.');
                }
            }
            num--;
        }
        Throw(_ps.charsUsed, System.SR.Xml_UnexpectedEOFInElementContent, _stringBuilder.ToString());
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Text.StringBuilder.Append(), System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.Throw(), System.Text.StringBuilder.ToString(), System.Xml.XmlTextReaderImpl.NodeData.type, System.SR.Xml_UnexpectedEOF1, and System.SR.Xml_UnexpectedEOFInElementContent.
Referenced by System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseElementContent(), System.Xml.XmlTextReaderImpl.ParseElementContent_ReadData(), System.Xml.XmlTextReaderImpl.ParseEndElement(), and System.Xml.XmlTextReaderImpl.ParseEndElementAsync_ReadData().