Terraria: System.Xml.XmlTextReaderImpl.ParseEndElementAsync_CheckNameAndParse
ParseEndElementAsync_CheckNameAndParse()
Task System.Xml.XmlTextReaderImpl.ParseEndElementAsync_CheckNameAndParse () inline private
Definition at line 10283 of file XmlTextReaderImpl.cs.
    {
        NodeData nodeData = _nodes[_index - 1];
        int length = nodeData.prefix.Length;
        int length2 = nodeData.localName.Length;
        char[] chars = _ps.chars;
        int nameLen;
        if (nodeData.prefix.Length == 0)
        {
            if (!XmlConvert.StrEqual(chars, _ps.charPos, length2, nodeData.localName))
            {
                return ThrowTagMismatchAsync(nodeData);
            }
            nameLen = length2;
        }
        else
        {
            int num = _ps.charPos + length;
            if (!XmlConvert.StrEqual(chars, _ps.charPos, length, nodeData.prefix) || chars[num] != ':' || !XmlConvert.StrEqual(chars, num + 1, length2, nodeData.localName))
            {
                return ThrowTagMismatchAsync(nodeData);
            }
            nameLen = length2 + length + 1;
        }
        LineInfo endTagLineInfo = new LineInfo(_ps.lineNo, _ps.LinePos);
        return ParseEndElementAsync_Finish(nameLen, nodeData, endTagLineInfo);
    }
References System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.Dictionary, System.length, System.length2, System.Xml.XmlTextReaderImpl.ParsingState.lineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseEndElementAsync_Finish(), System.Xml.XmlConvert.StrEqual(), and System.Xml.XmlTextReaderImpl.ThrowTagMismatchAsync().
Referenced by System.Xml.XmlTextReaderImpl._ParseEndElmentAsync(), and System.Xml.XmlTextReaderImpl.ParseEndElementAsync().