Terraria: System.Xml.XmlTextReaderImpl.SkipUntil
SkipUntil()
void System.Xml.XmlTextReaderImpl.SkipUntil (char stopChar, bool recognizeLiterals) inline private
Definition at line 6328 of file XmlTextReaderImpl.cs.
    {
        bool flag = false;
        bool flag2 = false;
        bool flag3 = false;
        char c = '"';
        char[] chars = _ps.chars;
        int num = _ps.charPos;
        while (true)
        {
            char c2;
            if (XmlCharType.IsAttributeValueChar(c2 = chars[num]) && chars[num] != stopChar && c2 != '-' && c2 != '?')
            {
                num++;
                continue;
            }
            if (c2 == stopChar && !flag)
            {
                break;
            }
            _ps.charPos = num;
            switch (c2)
            {
            case '\n':
                num++;
                OnNewLine(num);
                continue;
            case '\r':
                if (chars[num + 1] == '\n')
                {
                    num += 2;
                }
                else
                {
                    if (num + 1 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    num++;
                }
                OnNewLine(num);
                continue;
            case '<':
                if (chars[num + 1] == '?')
                {
                    if (recognizeLiterals && !flag && !flag2)
                    {
                        flag3 = true;
                        num += 2;
                        continue;
                    }
                }
                else if (chars[num + 1] == '!')
                {
                    if (num + 3 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    if (chars[num + 2] == '-' && chars[num + 3] == '-' && recognizeLiterals && !flag && !flag3)
                    {
                        flag2 = true;
                        num += 4;
                        continue;
                    }
                }
                else if (num + 1 >= _ps.charsUsed && !_ps.isEof)
                {
                    break;
                }
                num++;
                continue;
            case '-':
                if (flag2)
                {
                    if (num + 2 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    if (chars[num + 1] == '-' && chars[num + 2] == '>')
                    {
                        flag2 = false;
                        num += 2;
                        continue;
                    }
                }
                num++;
                continue;
            case '?':
                if (flag3)
                {
                    if (num + 1 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    if (chars[num + 1] == '>')
                    {
                        flag3 = false;
                        num++;
                        continue;
                    }
                }
                num++;
                continue;
            case '\t':
            case '&':
            case '>':
            case ']':
                num++;
                continue;
            case '"':
            case '\'':
                if (flag)
                {
                    if (c == c2)
                    {
                        flag = false;
                    }
                }
                else if (recognizeLiterals && !flag2 && !flag3)
                {
                    flag = true;
                    c = c2;
                }
                num++;
                continue;
            default:
            {
                if (num == _ps.charsUsed)
                {
                    break;
                }
                char ch = chars[num];
                if (XmlCharType.IsHighSurrogate(ch))
                {
                    if (num + 1 == _ps.charsUsed)
                    {
                        break;
                    }
                    num++;
                    if (XmlCharType.IsLowSurrogate(chars[num]))
                    {
                        num++;
                        continue;
                    }
                }
                ThrowInvalidChar(chars, _ps.charsUsed, num);
                break;
            }
            }
            if (ReadData() == 0)
            {
                if (_ps.charsUsed - _ps.charPos > 0)
                {
                    if (_ps.chars[_ps.charPos] != '\r')
                    {
                        Throw(System.SR.Xml_UnexpectedEOF1);
                    }
                }
                else
                {
                    Throw(System.SR.Xml_UnexpectedEOF1);
                }
            }
            chars = _ps.chars;
            num = _ps.charPos;
        }
        _ps.charPos = num + 1;
    }
References System.Xml.XmlTextReaderImpl._ps, System.ch, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.SkipDtd(), and System.Xml.XmlTextReaderImpl.SkipPublicOrSystemIdLiteral().