Terraria: System.Xml.XmlTextReaderImpl.OnEof
OnEof()
void System.Xml.XmlTextReaderImpl.OnEof () inline private
Definition at line 7028 of file XmlTextReaderImpl.cs.
    {
        _curNode = _nodes[0];
        _curNode.Clear(XmlNodeType.None);
        _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
        _parsingFunction = ParsingFunction.Eof;
        _readState = ReadState.EndOfFile;
        _reportedEncoding = null;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._readState, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.XmlTextReaderImpl.NodeData.Clear(), System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, and System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo().
Referenced by System.Xml.XmlTextReaderImpl.GetRemainder(), System.Xml.XmlTextReaderImpl.ParseDocumentContent(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(), System.Xml.XmlTextReaderImpl.ParseElementContent(), System.Xml.XmlTextReaderImpl.ParseElementContent_ReadData(), System.Xml.XmlTextReaderImpl.ParseFragmentAttribute(), System.Xml.XmlTextReaderImpl.Read(), and System.Xml.XmlTextReaderImpl.ReadAsync().