Terraria: System.Xml.XmlTextReaderImpl.GetIndexOfAttributeWithPrefix
GetIndexOfAttributeWithPrefix()
int System.Xml.XmlTextReaderImpl.GetIndexOfAttributeWithPrefix (string name) inline private
Definition at line 7946 of file XmlTextReaderImpl.cs.
    {
        name = _nameTable.Add(name);
        if (name == null)
        {
            return -1;
        }
        for (int i = _index + 1; i < _index + _attrCount + 1; i++)
        {
            if (Ref.Equal(_nodes[i].GetNameWPrefix(_nameTable), name))
            {
                return i;
            }
        }
        return -1;
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlNameTable.Add(), System.Xml.Ref.Equal(), and System.Xml.XmlTextReaderImpl.NodeData.GetNameWPrefix().
Referenced by System.Xml.XmlTextReaderImpl.GetAttribute(), and System.Xml.XmlTextReaderImpl.MoveToAttribute().