Terraria: System.Xml.XmlTextReaderImpl.IncrementalRead
IncrementalRead() [1/2]
int System.Xml.XmlTextReaderImpl.IncrementalRead () inline private
Definition at line 7360 of file XmlTextReaderImpl.cs.
    {
        int num = 0;
        int num3;
        while (true)
        {
            int num2 = _incReadLeftEndPos - _incReadLeftStartPos;
            if (num2 > 0)
            {
                try
                {
                    num3 = _incReadDecoder.Decode(_ps.chars, _incReadLeftStartPos, num2);
                }
                catch (XmlException e)
                {
                    ReThrow(e, _incReadLineInfo.lineNo, _incReadLineInfo.linePos);
                    return 0;
                }
                if (num3 < num2)
                {
                    _incReadLeftStartPos += num3;
                    _incReadLineInfo.linePos += num3;
                    return num3;
                }
                _incReadLeftStartPos = 0;
                _incReadLeftEndPos = 0;
                _incReadLineInfo.linePos += num3;
                if (_incReadDecoder.IsFull)
                {
                    break;
                }
            }
            int outStartPos = 0;
            int outEndPos = 0;
            while (true)
            {
                switch (_incReadState)
                {
                case IncrementalReadState.PI:
                    if (ParsePIValue(out outStartPos, out outEndPos))
                    {
                        _ps.charPos -= 2;
                        _incReadState = IncrementalReadState.Text;
                    }
                    break;
                case IncrementalReadState.Comment:
                    if (ParseCDataOrComment(XmlNodeType.Comment, out outStartPos, out outEndPos))
                    {
                        _ps.charPos -= 3;
                        _incReadState = IncrementalReadState.Text;
                    }
                    break;
                case IncrementalReadState.CDATA:
                    if (ParseCDataOrComment(XmlNodeType.CDATA, out outStartPos, out outEndPos))
                    {
                        _ps.charPos -= 3;
                        _incReadState = IncrementalReadState.Text;
                    }
                    break;
                case IncrementalReadState.EndElement:
                    _parsingFunction = ParsingFunction.PopElementContext;
                    _nextParsingFunction = ((_index <= 0 && _fragmentType == XmlNodeType.Document) ? ParsingFunction.DocumentContent : ParsingFunction.ElementContent);
                    _outerReader.Read();
                    _incReadState = IncrementalReadState.End;
                    goto case IncrementalReadState.End;
                case IncrementalReadState.End:
                    return num;
                case IncrementalReadState.ReadData:
                    if (ReadData() == 0)
                    {
                        ThrowUnclosedElements();
                    }
                    _incReadState = IncrementalReadState.Text;
                    outStartPos = _ps.charPos;
                    outEndPos = outStartPos;
                    goto default;
                default:
                {
                    char[] chars = _ps.chars;
                    outStartPos = _ps.charPos;
                    outEndPos = outStartPos;
                    while (true)
                    {
                        _incReadLineInfo.Set(_ps.LineNo, _ps.LinePos);
                        if (_incReadState == IncrementalReadState.Attributes)
{
                            char c;
                            while (XmlCharType.IsAttributeValueChar(c = chars[outEndPos]) && c != '/')
{
                                outEndPos++;
                            }
                        }
                        else
{
                            char c;
                            while (XmlCharType.IsAttributeValueChar(c = chars[outEndPos]))
{
                                outEndPos++;
                            }
                        }
                        if (chars[outEndPos] == '&' || chars[outEndPos] == '\t')
{
                            outEndPos++;
                            continue;
                        }
                        if (outEndPos - outStartPos <= 0)
{
                            char c2 = chars[outEndPos];
                            if ((uint)c2 <= 34u)
{
                                if (c2 == '\n')
{
                                    outEndPos++;
                                    OnNewLine(outEndPos);
                                    continue;
                                }
                                if (c2 == '\r')
{
                                    if (chars[outEndPos + 1] == '\n')
{
                                        outEndPos += 2;
                                    }
                                    else
{
                                        if (outEndPos + 1 >= _ps.charsUsed)
{
                                            goto IL_0662;
                                        }
                                        outEndPos++;
                                    }
                                    OnNewLine(outEndPos);
                                    continue;
                                }
                                if (c2 == '"')
{
                                    goto IL_0600;
                                }
                            }
                            else if ((uint)c2 <= 47u)
{
                                if (c2 == '\'')
{
                                    goto IL_0600;
                                }
                                if (c2 == '/')
{
                                    if (_incReadState == IncrementalReadState.Attributes)
{
                                        if (_ps.charsUsed - outEndPos < 2)
{
                                            goto IL_0662;
                                        }
                                        if (chars[outEndPos + 1] == '>')
{
                                            _incReadState = IncrementalReadState.Text;
                                            _incReadDepth--;
                                        }
                                    }
                                    outEndPos++;
                                    continue;
                                }
                            }
                            else
{
                                if (c2 == '<')
{
                                    if (_incReadState != 0)
{
                                        outEndPos++;
                                        continue;
                                    }
                                    if (_ps.charsUsed - outEndPos < 2)
{
                                        goto IL_0662;
                                    }
                                    char c3 = chars[outEndPos + 1];
                                    if (c3 != '!')
{
                                        switch (c3)
{
                                        case '?':
                                            outEndPos += 2;
                                            _incReadState = IncrementalReadState.PI;
                                            break;
                                        case '/':
{
                                            int colonPos2;
                                            int num5 = ParseQName(isQName: true, 2, out colonPos2);
                                            if (XmlConvert.StrEqual(chars, _ps.charPos + 2, num5 - _ps.charPos - 2, _curNode.GetNameWPrefix(_nameTable)) && (_ps.chars[num5] == '>' || XmlCharType.IsWhiteSpace(_ps.chars[num5])))
{
                                                if (--_incReadDepth > 0)
{
                                                    outEndPos = num5 + 1;
                                                    continue;
                                                }
                                                _ps.charPos = num5;
                                                if (XmlCharType.IsWhiteSpace(_ps.chars[num5]))
{
                                                    EatWhitespaces(null);
                                                }
                                                if (_ps.chars[_ps.charPos] != '>')
{
                                                    ThrowUnexpectedToken(">");
                                                }
                                                goto end_IL_00bb;
                                            }
                                            outEndPos = num5;
                                            outStartPos = _ps.charPos;
                                            chars = _ps.chars;
                                            continue;
                                        }
                                        default:
{
                                            int colonPos;
                                            int num4 = ParseQName(isQName: true, 1, out colonPos);
                                            if (XmlConvert.StrEqual(_ps.chars, _ps.charPos + 1, num4 - _ps.charPos - 1, _curNode.localName) && (_ps.chars[num4] == '>' || _ps.chars[num4] == '/' || XmlCharType.IsWhiteSpace(_ps.chars[num4])))
{
                                                _incReadDepth++;
                                                _incReadState = IncrementalReadState.Attributes;
                                                outEndPos = num4;
                                                break;
                                            }
                                            outEndPos = num4;
                                            outStartPos = _ps.charPos;
                                            chars = _ps.chars;
                                            continue;
                                        }
                                        }
                                    }
                                    else
{
                                        if (_ps.charsUsed - outEndPos < 4)
{
                                            goto IL_0662;
                                        }
                                        if (chars[outEndPos + 2] == '-' && chars[outEndPos + 3] == '-')
{
                                            outEndPos += 4;
                                            _incReadState = IncrementalReadState.Comment;
                                        }
                                        else
{
                                            if (_ps.charsUsed - outEndPos < 9)
{
                                                goto IL_0662;
                                            }
                                            if (!XmlConvert.StrEqual(chars, outEndPos + 2, 7, "[CDATA["))
{
                                                continue;
                                            }
                                            outEndPos += 9;
                                            _incReadState = IncrementalReadState.CDATA;
                                        }
                                    }
                                    goto IL_0669;
                                }
                                if (c2 == '>')
{
                                    if (_incReadState == IncrementalReadState.Attributes)
{
                                        _incReadState = IncrementalReadState.Text;
                                    }
                                    outEndPos++;
                                    continue;
                                }
                            }
                            if (outEndPos != _ps.charsUsed)
{
                                outEndPos++;
                                continue;
                            }
                            goto IL_0662;
                        }
                        goto IL_0669;
                        IL_0669:
                        _ps.charPos = outEndPos;
                        break;
                        IL_0662:
                        _incReadState = IncrementalReadState.ReadData;
                        goto IL_0669;
                        IL_0600:
                        switch (_incReadState)
{
                        case IncrementalReadState.AttributeValue:
                            if (chars[outEndPos] == _curNode.quoteChar)
{
                                _incReadState = IncrementalReadState.Attributes;
                            }
                            break;
                        case IncrementalReadState.Attributes:
                            _curNode.quoteChar = chars[outEndPos];
                            _incReadState = IncrementalReadState.AttributeValue;
                            break;
                        }
                        outEndPos++;
                    }
                    break;
                }
                }
                int num6 = outEndPos - outStartPos;
                if (num6 > 0)
                {
                    int num7;
                    try
                    {
                        num7 = _incReadDecoder.Decode(_ps.chars, outStartPos, num6);
                    }
                    catch (XmlException e2)
                    {
                        ReThrow(e2, _incReadLineInfo.lineNo, _incReadLineInfo.linePos);
                        return 0;
                    }
                    num += num7;
                    if (_incReadDecoder.IsFull)
                    {
                        _incReadLeftStartPos = outStartPos + num7;
                        _incReadLeftEndPos = outEndPos;
                        _incReadLineInfo.linePos += num7;
                        return num;
                    }
                }
                continue;
                end_IL_00bb:
                break;
            }
            _ps.charPos++;
            _incReadState = IncrementalReadState.EndElement;
        }
        return num3;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._incReadDepth, System.Xml.XmlTextReaderImpl._incReadLeftEndPos, System.Xml.XmlTextReaderImpl._incReadLeftStartPos, System.Xml.XmlTextReaderImpl._incReadLineInfo, System.Xml.XmlTextReaderImpl._incReadState, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nameTable, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.IncrementalReadDecoder.Decode(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.EatWhitespaces(), System.Xml.XmlTextReaderImpl.NodeData.GetNameWPrefix(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.IncrementalReadDecoder.IsFull, System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.LineInfo.lineNo, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.LineInfo.linePos, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.NodeData.localName, System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), System.Xml.XmlTextReaderImpl.ParsePIValue(), System.Xml.XmlTextReaderImpl.ParseQName(), System.Xml.XmlTextReaderImpl.NodeData.quoteChar, System.Xml.XmlReader.Read(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.ReThrow(), System.Xml.LineInfo.Set(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.ThrowUnclosedElements(), and System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken().
Referenced by System.Xml.XmlTextReaderImpl.FinishIncrementalRead(), System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.XmlTextReaderImpl.ReadBase64(), System.Xml.XmlTextReaderImpl.ReadBinHex(), and System.Xml.XmlTextReaderImpl.ReadChars().