Terraria: System.Xml.XmlTextReaderImpl.ParseCDataOrCommentAsync
ParseCDataOrCommentAsync()
async Task System.Xml.XmlTextReaderImpl.ParseCDataOrCommentAsync (XmlNodeType type) inline private
Definition at line 11951 of file XmlTextReaderImpl.cs.
    {
        if (_parsingMode == ParsingMode.Full)
        {
            _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
            (int, int, bool) tuple = await ParseCDataOrCommentTupleAsync(type).ConfigureAwait(continueOnCapturedContext: false);
            var (num, num2, _) = tuple;
            if (tuple.Item3)
            {
                _curNode.SetValueNode(type, _ps.chars, num, num2 - num);
                return;
            }
            (int, int, bool) tuple3;
            do
            {
                _stringBuilder.Append(_ps.chars, num, num2 - num);
                tuple3 = await ParseCDataOrCommentTupleAsync(type).ConfigureAwait(continueOnCapturedContext: false);
                (num, num2, _) = tuple3;
            }
            while (!tuple3.Item3);
            _stringBuilder.Append(_ps.chars, num, num2 - num);
            _curNode.SetValueNode(type, _stringBuilder.ToString());
            _stringBuilder.Length = 0;
        }
        else
        {
            (int, int, bool) tuple5;
            do
            {
                tuple5 = await ParseCDataOrCommentTupleAsync(type).ConfigureAwait(continueOnCapturedContext: false);
                _ = tuple5.Item1;
                _ = tuple5.Item2;
            }
            while (!tuple5.Item3);
        }
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Text.StringBuilder.Append(), System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.int, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseCDataOrCommentTupleAsync(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.SetValueNode(), System.Text.StringBuilder.ToString(), and System.type.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_ParseCommentAsync(), System.Xml.XmlTextReaderImpl.ParseCDataAsync(), and System.Xml.XmlTextReaderImpl.ParseCommentAsync().