Terraria: System.Xml.XmlTextReaderImpl.ParseEndElementAsync_CheckEndTag
ParseEndElementAsync_CheckEndTag()
Task System.Xml.XmlTextReaderImpl.ParseEndElementAsync_CheckEndTag (int nameLen, NodeData startTagNode, LineInfo endTagLineInfo) inline private
Definition at line 10350 of file XmlTextReaderImpl.cs.
    {
        int num;
        while (true)
        {
            num = _ps.charPos + nameLen;
            char[] chars = _ps.chars;
            if (num == _ps.charsUsed)
            {
                _parseEndElement_NextFunc = ParseEndElementParseFunction.ReadData;
                return Task.CompletedTask;
            }
            bool flag = false;
            if (XmlCharType.IsNCNameSingleChar(chars[num]) || chars[num] == ':')
            {
                flag = true;
            }
            if (flag)
            {
                return ThrowTagMismatchAsync(startTagNode);
            }
            if (chars[num] != '>')
            {
                char c;
                while (XmlCharType.IsWhiteSpace(c = chars[num]))
                {
                    num++;
                    switch (c)
                    {
                    case '\n':
                        OnNewLine(num);
                        break;
                    case '\r':
                        if (chars[num] == '\n')
{
                            num++;
                        }
                        else if (num == _ps.charsUsed && !_ps.isEof)
{
                            break;
                        }
                        OnNewLine(num);
                        break;
                    }
                }
            }
            if (chars[num] == '>')
            {
                break;
            }
            if (num == _ps.charsUsed)
            {
                _parseEndElement_NextFunc = ParseEndElementParseFunction.ReadData;
                return Task.CompletedTask;
            }
            ThrowUnexpectedToken(num, ">");
        }
        _index--;
        _curNode = _nodes[_index];
        startTagNode.lineInfo = endTagLineInfo;
        startTagNode.type = XmlNodeType.EndElement;
        _ps.charPos = num + 1;
        _nextParsingFunction = ((_index > 0) ? _parsingFunction : ParsingFunction.DocumentContent);
        _parsingFunction = ParsingFunction.PopElementContext;
        _parseEndElement_NextFunc = ParseEndElementParseFunction.Done;
        return Task.CompletedTask;
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._parseEndElement_NextFunc, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.ThrowTagMismatchAsync(), and System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken().
Referenced by System.Xml.XmlTextReaderImpl.ParseEndElementAsync_Finish(), and System.Xml.XmlTextReaderImpl.ParseEndElementAsync_Finish().