Terraria: System.Xml.XmlTextReaderImpl.FinishReadContentAsBinary
FinishReadContentAsBinary()
void System.Xml.XmlTextReaderImpl.FinishReadContentAsBinary () inline private
Definition at line 5520 of file XmlTextReaderImpl.cs.
    {
        _readValueOffset = 0;
        if (_incReadState == IncrementalReadState.ReadContentAsBinary_OnPartialValue)
        {
            SkipPartialTextValue();
        }
        else
        {
            _parsingFunction = _nextParsingFunction;
            _nextParsingFunction = _nextNextParsingFunction;
        }
        if (_incReadState != IncrementalReadState.ReadContentAsBinary_End)
        {
            while (MoveToNextContentNode(moveIfOnContentNode: true))
            {
            }
        }
    }
References System.Xml.XmlTextReaderImpl._incReadState, System.Xml.XmlTextReaderImpl._nextNextParsingFunction, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readValueOffset, System.Xml.XmlTextReaderImpl.MoveToNextContentNode(), and System.Xml.XmlTextReaderImpl.SkipPartialTextValue().
Referenced by System.Xml.XmlTextReaderImpl.FinishAttributeValueIterator(), System.Xml.XmlTextReaderImpl.FinishReadElementContentAsBinary(), System.Xml.XmlTextReaderImpl.Read(), System.Xml.XmlTextReaderImpl.ReadAttributeValue(), and System.Xml.XmlTextReaderImpl.Skip().