Terraria: System.Xml.XmlTextReaderImpl.ThrowInvalidChar
ThrowInvalidChar()
void System.Xml.XmlTextReaderImpl.ThrowInvalidChar (char[] data, int length, int invCharPos) inline private
Definition at line 3023 of file XmlTextReaderImpl.cs.
    {
        Throw(invCharPos, System.SR.Xml_InvalidCharacter, XmlException.BuildCharExceptionArgs(data, length, invCharPos));
    }
References System.Xml.XmlException.BuildCharExceptionArgs(), System.length, System.Xml.XmlTextReaderImpl.Throw(), and System.SR.Xml_InvalidCharacter.
Referenced by System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync(), System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), System.Xml.XmlTextReaderImpl.ParseCDataOrCommentTupleAsync(), System.Xml.XmlTextReaderImpl.ParsePIValue(), System.Xml.XmlTextReaderImpl.ParsePIValueAsync(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespaceAsync(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseTextAsync_Surrogate(), System.Xml.XmlTextReaderImpl.SkipUntil(), and System.Xml.XmlTextReaderImpl.SkipUntilAsync().