Terraria: System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync
ParseDocumentContentAsync()
Task< bool > System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync () inline private
Definition at line 9786 of file XmlTextReaderImpl.cs.
    {
        char[] chars;
        bool needMoreChars;
        int charPos;
        while (true)
        {
            needMoreChars = false;
            charPos = _ps.charPos;
            chars = _ps.chars;
            if (chars[charPos] != '<')
            {
                break;
            }
            needMoreChars = true;
            if (_ps.charsUsed - charPos < 4)
            {
                return ParseDocumentContentAsync_ReadData(needMoreChars);
            }
            charPos++;
            switch (chars[charPos])
            {
            case '?':
                _ps.charPos = charPos + 1;
                return ParsePIAsync().ContinueBoolTaskFuncWhenFalseAsync((XmlTextReaderImpl thisRef) => thisRef.ParseDocumentContentAsync(), this);
            case '!':
                charPos++;
                if (_ps.charsUsed - charPos < 2)
                {
                    return ParseDocumentContentAsync_ReadData(needMoreChars);
                }
                if (chars[charPos] == '-')
                {
                    if (chars[charPos + 1] == '-')
                    {
                        _ps.charPos = charPos + 2;
                        return ParseCommentAsync().ContinueBoolTaskFuncWhenFalseAsync((XmlTextReaderImpl thisRef) => thisRef.ParseDocumentContentAsync(), this);
                    }
                    ThrowUnexpectedToken(charPos + 1, "-");
                    continue;
                }
                if (chars[charPos] == '[')
                {
                    if (_fragmentType != XmlNodeType.Document)
                    {
                        charPos++;
                        if (_ps.charsUsed - charPos < 6)
{
                            return ParseDocumentContentAsync_ReadData(needMoreChars);
                        }
                        if (XmlConvert.StrEqual(chars, charPos, 6, "CDATA["))
{
                            _ps.charPos = charPos + 6;
                            return ParseCDataAsync().CallBoolTaskFuncWhenFinishAsync((XmlTextReaderImpl thisRef) => thisRef.ParseDocumentContentAsync_CData(), this);
                        }
                        ThrowUnexpectedToken(charPos, "CDATA[");
                    }
                    else
                    {
                        Throw(_ps.charPos, System.SR.Xml_InvalidRootData);
                    }
                    continue;
                }
                if (_fragmentType == XmlNodeType.Document || _fragmentType == XmlNodeType.None)
                {
                    _fragmentType = XmlNodeType.Document;
                    _ps.charPos = charPos;
                    return ParseDoctypeDeclAsync().ContinueBoolTaskFuncWhenFalseAsync((XmlTextReaderImpl thisRef) => thisRef.ParseDocumentContentAsync(), this);
                }
                if (ParseUnexpectedToken(charPos) == "DOCTYPE")
                {
                    Throw(System.SR.Xml_BadDTDLocation);
                }
                else
                {
                    ThrowUnexpectedToken(charPos, "<!--", "<[CDATA[");
                }
                continue;
            case '/':
                Throw(charPos + 1, System.SR.Xml_UnexpectedEndTag);
                continue;
            }
            if (_rootElementParsed)
            {
                if (_fragmentType == XmlNodeType.Document)
                {
                    Throw(charPos, System.SR.Xml_MultipleRoots);
                }
                if (_fragmentType == XmlNodeType.None)
                {
                    _fragmentType = XmlNodeType.Element;
                }
            }
            _ps.charPos = charPos;
            _rootElementParsed = true;
            return ParseElementAsync().ReturnTrueTaskWhenFinishAsync();
        }
        if (chars[charPos] == '&')
        {
            return ParseDocumentContentAsync_ParseEntity();
        }
        if (charPos == _ps.charsUsed || (_v1Compat && chars[charPos] == '\0'))
        {
            return ParseDocumentContentAsync_ReadData(needMoreChars);
        }
        if (_fragmentType == XmlNodeType.Document)
        {
            return ParseRootLevelWhitespaceAsync().ContinueBoolTaskFuncWhenFalseAsync((XmlTextReaderImpl thisRef) => thisRef.ParseDocumentContentAsync(), this);
        }
        return ParseDocumentContentAsync_WhiteSpace();
    }
References System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._rootElementParsed, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParseCDataAsync(), System.Xml.XmlTextReaderImpl.ParseCommentAsync(), System.Xml.XmlTextReaderImpl.ParseDoctypeDeclAsync(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ParseEntity(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_WhiteSpace(), System.Xml.XmlTextReaderImpl.ParseElementAsync(), System.Xml.XmlTextReaderImpl.ParsePIAsync(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespaceAsync(), System.Xml.XmlTextReaderImpl.ParseUnexpectedToken(), System.Xml.XmlConvert.StrEqual(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), System.SR.Xml_BadDTDLocation, System.SR.Xml_InvalidRootData, System.SR.Xml_MultipleRoots, and System.SR.Xml_UnexpectedEndTag.
Referenced by System.Xml.XmlTextReaderImpl._ParseDocumentContentAsync_WhiteSpace(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ParseEntity(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_WhiteSpace(), and System.Xml.XmlTextReaderImpl.ReadAsync().