Terraria: System.Xml.XmlTextReaderImpl.ParsePIValueAsync
ParsePIValueAsync()
async Task<(int, int, bool)> System.Xml.XmlTextReaderImpl.ParsePIValueAsync () inline private
Definition at line 11798 of file XmlTextReaderImpl.cs.
    {
        if (_ps.charsUsed - _ps.charPos < 2 && await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
        {
            Throw(_ps.charsUsed, System.SR.Xml_UnexpectedEOF, "PI");
        }
        int num = _ps.charPos;
        char[] chars = _ps.chars;
        int num2 = 0;
        int num3 = -1;
        int item;
        int charPos;
        while (true)
        {
            char c;
            if (XmlCharType.IsTextChar(c = chars[num]) && c != '?')
            {
                num++;
                continue;
            }
            switch (chars[num])
            {
            case '?':
                if (chars[num + 1] == '>')
                {
                    if (num2 > 0)
                    {
                        ShiftBuffer(num3 + num2, num3, num - num3 - num2);
                        item = num - num2;
                    }
                    else
                    {
                        item = num;
                    }
                    charPos = _ps.charPos;
                    _ps.charPos = num + 2;
                    return (charPos, item, true);
                }
                if (num + 1 != _ps.charsUsed)
                {
                    num++;
                    continue;
                }
                break;
            case '\n':
                num++;
                OnNewLine(num);
                continue;
            case '\r':
                if (chars[num + 1] == '\n')
                {
                    if (!_ps.eolNormalized && _parsingMode == ParsingMode.Full)
                    {
                        if (num - _ps.charPos > 0)
{
                            if (num2 == 0)
{
                                num2 = 1;
                                num3 = num;
                            }
                            else
{
                                ShiftBuffer(num3 + num2, num3, num - num3 - num2);
                                num3 = num - num2;
                                num2++;
                            }
                        }
                        else
{
                            _ps.charPos++;
                        }
                    }
                    num += 2;
                }
                else
                {
                    if (num + 1 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    if (!_ps.eolNormalized)
                    {
                        chars[num] = '\n';
                    }
                    num++;
                }
                OnNewLine(num);
                continue;
            case '\t':
            case '&':
            case '<':
            case ']':
                num++;
                continue;
            default:
            {
                if (num == _ps.charsUsed)
                {
                    break;
                }
                char ch = chars[num];
                if (XmlCharType.IsHighSurrogate(ch))
                {
                    if (num + 1 == _ps.charsUsed)
                    {
                        break;
                    }
                    num++;
                    if (XmlCharType.IsLowSurrogate(chars[num]))
                    {
                        num++;
                        continue;
                    }
                }
                ThrowInvalidChar(chars, _ps.charsUsed, num);
                continue;
            }
            }
            break;
        }
        if (num2 > 0)
        {
            ShiftBuffer(num3 + num2, num3, num - num3 - num2);
            item = num - num2;
        }
        else
        {
            item = num;
        }
        charPos = _ps.charPos;
        _ps.charPos = num;
        return (charPos, item, false);
    }
References System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.ch, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.eolNormalized, System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Xml.XmlCharType.IsTextChar(), System.item, System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.ShiftBuffer(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), and System.SR.Xml_UnexpectedEOF.
Referenced by System.Xml.XmlTextReaderImpl.ParsePIAsync().