Terraria: System.Xml.XmlTextReaderImpl._ParseDocumentContentAsync_WhiteSpace
_ParseDocumentContentAsync_WhiteSpace()
async Task< bool > System.Xml.XmlTextReaderImpl._ParseDocumentContentAsync_WhiteSpace (Task< bool > task) inline private
Definition at line 9959 of file XmlTextReaderImpl.cs.
    {
        if (await task.ConfigureAwait(continueOnCapturedContext: false))
        {
            if (_fragmentType == XmlNodeType.None && _curNode.type == XmlNodeType.Text)
            {
                _fragmentType = XmlNodeType.Element;
            }
            return true;
        }
        return await ParseDocumentContentAsync().ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._fragmentType, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync(), System.task, and System.Xml.XmlTextReaderImpl.NodeData.type.
Referenced by System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_WhiteSpace().