Terraria: System.Xml.XmlTextReaderImpl.FinishInitUriStringAsync
FinishInitUriStringAsync()
async Task System.Xml.XmlTextReaderImpl.FinishInitUriStringAsync () inline private
Definition at line 8612 of file XmlTextReaderImpl.cs.
    {
        Stream stream = (Stream)(await _laterInitParam.inputUriResolver.GetEntityAsync(_laterInitParam.inputbaseUri, string.Empty, typeof(Stream)).ConfigureAwait(continueOnCapturedContext: false));
        if (stream == null)
        {
            throw new XmlException(System.SR.Xml_CannotResolveUrl, _laterInitParam.inputUriStr);
        }
        Encoding encoding = null;
        if (_laterInitParam.inputContext != null)
        {
            encoding = _laterInitParam.inputContext.Encoding;
        }
        try
        {
            await InitStreamInputAsync(_laterInitParam.inputbaseUri, _reportedBaseUri, stream, null, 0, encoding).ConfigureAwait(continueOnCapturedContext: false);
            _reportedEncoding = _ps.encoding;
            if (_laterInitParam.inputContext != null && _laterInitParam.inputContext.HasDtdInfo)
            {
                await ProcessDtdFromParserContextAsync(_laterInitParam.inputContext).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        catch
        {
            stream.Dispose();
            throw;
        }
        _laterInitParam = null;
    }
References System.Xml.XmlTextReaderImpl._laterInitParam, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlParserContext.Encoding, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlResolver.GetEntityAsync(), System.Xml.XmlParserContext.HasDtdInfo, System.Xml.XmlTextReaderImpl.InitStreamInputAsync(), System.Xml.XmlTextReaderImpl.LaterInitParam.inputbaseUri, System.Xml.XmlTextReaderImpl.LaterInitParam.inputContext, System.Xml.XmlTextReaderImpl.LaterInitParam.inputUriResolver, System.Xml.XmlTextReaderImpl.LaterInitParam.inputUriStr, System.Xml.XmlTextReaderImpl.ProcessDtdFromParserContextAsync(), System.stream, System.Xml.XmlTextReaderImpl.Stream, System.SR.Xml_CannotResolveUrl, and System.Xml.XmlException.
Referenced by System.Xml.XmlTextReaderImpl.FinishInitAsync().