Terraria: System.Xml.XmlTextReaderImpl.SkipUntilAsync
SkipUntilAsync()
async Task System.Xml.XmlTextReaderImpl.SkipUntilAsync (char stopChar, bool recognizeLiterals) inline private
Definition at line 12281 of file XmlTextReaderImpl.cs.
    {
        bool inLiteral = false;
        bool inComment = false;
        bool inPI = false;
        char literalQuote = '"';
        char[] chars = _ps.chars;
        int num = _ps.charPos;
        while (true)
        {
            char c;
            if (XmlCharType.IsAttributeValueChar(c = chars[num]) && c != stopChar && c != '-' && c != '?')
            {
                num++;
                continue;
            }
            if (c == stopChar && !inLiteral)
            {
                break;
            }
            _ps.charPos = num;
            switch (c)
            {
            case '\n':
                num++;
                OnNewLine(num);
                continue;
            case '\r':
                if (chars[num + 1] == '\n')
                {
                    num += 2;
                }
                else
                {
                    if (num + 1 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    num++;
                }
                OnNewLine(num);
                continue;
            case '<':
                if (chars[num + 1] == '?')
                {
                    if (recognizeLiterals && !inLiteral && !inComment)
                    {
                        inPI = true;
                        num += 2;
                        continue;
                    }
                }
                else if (chars[num + 1] == '!')
                {
                    if (num + 3 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    if (chars[num + 2] == '-' && chars[num + 3] == '-' && recognizeLiterals && !inLiteral && !inPI)
                    {
                        inComment = true;
                        num += 4;
                        continue;
                    }
                }
                else if (num + 1 >= _ps.charsUsed && !_ps.isEof)
                {
                    break;
                }
                num++;
                continue;
            case '-':
                if (inComment)
                {
                    if (num + 2 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    if (chars[num + 1] == '-' && chars[num + 2] == '>')
                    {
                        inComment = false;
                        num += 2;
                        continue;
                    }
                }
                num++;
                continue;
            case '?':
                if (inPI)
                {
                    if (num + 1 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    if (chars[num + 1] == '>')
                    {
                        inPI = false;
                        num++;
                        continue;
                    }
                }
                num++;
                continue;
            case '\t':
            case '&':
            case '>':
            case ']':
                num++;
                continue;
            case '"':
            case '\'':
                if (inLiteral)
                {
                    if (literalQuote == c)
                    {
                        inLiteral = false;
                    }
                }
                else if (recognizeLiterals && !inComment && !inPI)
                {
                    inLiteral = true;
                    literalQuote = c;
                }
                num++;
                continue;
            default:
            {
                if (num == _ps.charsUsed)
                {
                    break;
                }
                char ch = chars[num];
                if (XmlCharType.IsHighSurrogate(ch))
                {
                    if (num + 1 == _ps.charsUsed)
                    {
                        break;
                    }
                    num++;
                    if (XmlCharType.IsLowSurrogate(chars[num]))
                    {
                        num++;
                        continue;
                    }
                }
                ThrowInvalidChar(chars, _ps.charsUsed, num);
                break;
            }
            }
            if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
            {
                if (_ps.charsUsed - _ps.charPos > 0)
                {
                    if (_ps.chars[_ps.charPos] != '\r')
                    {
                        Throw(System.SR.Xml_UnexpectedEOF1);
                    }
                }
                else
                {
                    Throw(System.SR.Xml_UnexpectedEOF1);
                }
            }
            chars = _ps.chars;
            num = _ps.charPos;
        }
        _ps.charPos = num + 1;
    }
References System.Xml.XmlTextReaderImpl._ps, System.ch, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.SkipDtdAsync(), and System.Xml.XmlTextReaderImpl.SkipPublicOrSystemIdLiteralAsync().