Terraria: System.Xml.XmlTextReaderImpl.RegisterConsumedCharacters
RegisterConsumedCharacters()
void System.Xml.XmlTextReaderImpl.RegisterConsumedCharacters (long characters, bool inEntityReference) inline private
Definition at line 8372 of file XmlTextReaderImpl.cs.
    {
        if (_maxCharactersInDocument > 0)
        {
            long num = _charactersInDocument + characters;
            if (num < _charactersInDocument)
            {
                ThrowWithoutLineInfo(System.SR.Xml_LimitExceeded, "MaxCharactersInDocument");
            }
            else
            {
                _charactersInDocument = num;
            }
            if (_charactersInDocument > _maxCharactersInDocument)
            {
                ThrowWithoutLineInfo(System.SR.Xml_LimitExceeded, "MaxCharactersInDocument");
            }
        }
        if (_maxCharactersFromEntities > 0 && inEntityReference)
        {
            long num2 = _charactersFromEntities + characters;
            if (num2 < _charactersFromEntities)
            {
                ThrowWithoutLineInfo(System.SR.Xml_LimitExceeded, "MaxCharactersFromEntities");
            }
            else
            {
                _charactersFromEntities = num2;
            }
            if (_charactersFromEntities > _maxCharactersFromEntities)
            {
                ThrowWithoutLineInfo(System.SR.Xml_LimitExceeded, "MaxCharactersFromEntities");
            }
        }
    }
References System.Xml.XmlTextReaderImpl._charactersFromEntities, System.Xml.XmlTextReaderImpl._charactersInDocument, System.Xml.XmlTextReaderImpl._maxCharactersFromEntities, System.Xml.XmlTextReaderImpl._maxCharactersInDocument, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), and System.SR.Xml_LimitExceeded.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_PushInternalDtd(), System.Xml.XmlTextReaderImpl.PushExternalEntity(), System.Xml.XmlTextReaderImpl.PushExternalEntityAsync(), System.Xml.XmlTextReaderImpl.PushInternalEntity(), System.Xml.XmlTextReaderImpl.ReadData(), and System.Xml.XmlTextReaderImpl.ReadDataAsync().