Terraria: System.Xml.XmlTextReaderImpl.DtdParserProxy_ParsePIAsync
DtdParserProxy_ParsePIAsync()
async Task System.Xml.XmlTextReaderImpl.DtdParserProxy_ParsePIAsync (StringBuilder sb) inline package
Definition at line 9201 of file XmlTextReaderImpl.cs.
    {
        CheckAsyncCall();
        if (sb == null)
        {
            ParsingMode pm = _parsingMode;
            _parsingMode = ParsingMode.SkipNode;
            await ParsePIAsync(null).ConfigureAwait(continueOnCapturedContext: false);
            _parsingMode = pm;
        }
        else
        {
            await ParsePIAsync(sb).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, and System.Xml.XmlTextReaderImpl.ParsePIAsync().
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy.ParsePIAsync().