Terraria: System.Xml.XmlTextReaderImpl.ReadData
ReadData()
int System.Xml.XmlTextReaderImpl.ReadData () inline private
Definition at line 3452 of file XmlTextReaderImpl.cs.
    {
        if (_ps.isEof)
        {
            return 0;
        }
        int num;
        if (_ps.appendMode)
        {
            if (_ps.charsUsed == _ps.chars.Length - 1)
            {
                for (int i = 0; i < _attrCount; i++)
                {
                    _nodes[_index + i + 1].OnBufferInvalidated();
                }
                char[] array = new char[_ps.chars.Length * 2];
                BlockCopyChars(_ps.chars, 0, array, 0, _ps.chars.Length);
                _ps.chars = array;
            }
            if (_ps.stream != null && _ps.bytesUsed - _ps.bytePos < 6 && _ps.bytes.Length - _ps.bytesUsed < 6)
            {
                byte[] array2 = new byte[_ps.bytes.Length * 2];
                BlockCopy(_ps.bytes, 0, array2, 0, _ps.bytesUsed);
                _ps.bytes = array2;
            }
            num = _ps.chars.Length - _ps.charsUsed - 1;
            if (num > 80)
            {
                num = 80;
            }
        }
        else
        {
            int num2 = _ps.chars.Length;
            if (num2 - _ps.charsUsed <= num2 / 2)
            {
                for (int j = 0; j < _attrCount; j++)
                {
                    _nodes[_index + j + 1].OnBufferInvalidated();
                }
                int num3 = _ps.charsUsed - _ps.charPos;
                if (num3 < num2 - 1)
                {
                    _ps.lineStartPos -= _ps.charPos;
                    if (num3 > 0)
                    {
                        BlockCopyChars(_ps.chars, _ps.charPos, _ps.chars, 0, num3);
                    }
                    _ps.charPos = 0;
                    _ps.charsUsed = num3;
                }
                else
                {
                    char[] array3 = new char[_ps.chars.Length * 2];
                    BlockCopyChars(_ps.chars, 0, array3, 0, _ps.chars.Length);
                    _ps.chars = array3;
                }
            }
            if (_ps.stream != null)
            {
                int num4 = _ps.bytesUsed - _ps.bytePos;
                if (num4 <= 128)
                {
                    if (num4 == 0)
                    {
                        _ps.bytesUsed = 0;
                    }
                    else
                    {
                        BlockCopy(_ps.bytes, _ps.bytePos, _ps.bytes, 0, num4);
                        _ps.bytesUsed = num4;
                    }
                    _ps.bytePos = 0;
                }
            }
            num = _ps.chars.Length - _ps.charsUsed - 1;
        }
        if (_ps.stream != null)
        {
            if (!_ps.isStreamEof && _ps.bytePos == _ps.bytesUsed && _ps.bytes.Length - _ps.bytesUsed > 0)
            {
                int num5 = _ps.stream.Read(_ps.bytes, _ps.bytesUsed, _ps.bytes.Length - _ps.bytesUsed);
                if (num5 == 0)
                {
                    _ps.isStreamEof = true;
                }
                _ps.bytesUsed += num5;
            }
            int bytePos = _ps.bytePos;
            num = GetChars(num);
            if (num == 0 && _ps.bytePos != bytePos)
            {
                return ReadData();
            }
        }
        else if (_ps.textReader != null)
        {
            num = _ps.textReader.Read(_ps.chars, _ps.charsUsed, _ps.chars.Length - _ps.charsUsed - 1);
            _ps.charsUsed += num;
        }
        else
        {
            num = 0;
        }
        RegisterConsumedCharacters(num, InEntity);
        if (num == 0)
        {
            _ps.isEof = true;
        }
        _ps.chars[_ps.charsUsed] = '\0';
        return num;
    }
References System.Xml.XmlTextReaderImpl._attrCount, System.Xml.XmlTextReaderImpl._index, System.Xml.XmlTextReaderImpl._nodes, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.appendMode, System.array, System.Xml.XmlTextReaderImpl.BlockCopy(), System.Xml.XmlTextReaderImpl.BlockCopyChars(), System.Xml.XmlTextReaderImpl.ParsingState.bytePos, System.Xml.XmlTextReaderImpl.ParsingState.bytes, System.Xml.XmlTextReaderImpl.ParsingState.bytesUsed, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.GetChars(), System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlTextReaderImpl.ParsingState.isStreamEof, System.Xml.XmlTextReaderImpl.NodeData.OnBufferInvalidated(), System.IO.TextReader.Read(), System.IO.Stream.Read(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.RegisterConsumedCharacters(), System.Xml.XmlTextReaderImpl.ParsingState.stream, and System.Xml.XmlTextReaderImpl.ParsingState.textReader.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_ReadData(), System.Xml.XmlTextReaderImpl.EatWhitespaces(), System.Xml.XmlTextReaderImpl.GetRemainder(), System.Xml.XmlTextReaderImpl.HandleEntityReference(), System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.XmlTextReaderImpl.InitStreamInput(), System.Xml.XmlTextReaderImpl.InitTextReaderInput(), System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), System.Xml.XmlTextReaderImpl.ParseDoctypeDecl(), System.Xml.XmlTextReaderImpl.ParseDocumentContent(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementContent(), System.Xml.XmlTextReaderImpl.ParseEndElement(), System.Xml.XmlTextReaderImpl.ParseNamedCharRef(), System.Xml.XmlTextReaderImpl.ParseNumericCharRef(), System.Xml.XmlTextReaderImpl.ParsePI(), System.Xml.XmlTextReaderImpl.ParsePIValue(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.ReadData(), System.Xml.XmlTextReaderImpl.ReadDataInName(), System.Xml.XmlTextReaderImpl.SkipDtd(), System.Xml.XmlTextReaderImpl.SkipUntil(), System.Xml.XmlTextReaderImpl.SwitchEncoding(), and System.Xml.XmlTextReaderImpl.ZeroEndingStream().