Terraria: System.Xml.XmlTextReaderImpl.ParseTextAsync_AsyncFunc
ParseTextAsync_AsyncFunc()
async Task<(int, int, int, bool)> System.Xml.XmlTextReaderImpl.ParseTextAsync_AsyncFunc (Task<(int, int, int, bool)> task) inline private
Definition at line 11112 of file XmlTextReaderImpl.cs.
    {
        while (true)
        {
            await task.ConfigureAwait(continueOnCapturedContext: false);
            int outOrChars = _lastParseTextState.outOrChars;
            char[] chars = _lastParseTextState.chars;
            int pos = _lastParseTextState.pos;
            int rcount = _lastParseTextState.rcount;
            int rpos = _lastParseTextState.rpos;
            int orChars = _lastParseTextState.orChars;
            char c = _lastParseTextState.c;
            switch (_parseText_NextFunction)
            {
            case ParseTextFunction.ParseText:
                task = ParseTextAsync(outOrChars, chars, pos, rcount, rpos, orChars, c);
                break;
            case ParseTextFunction.Entity:
                task = ParseTextAsync_ParseEntity(outOrChars, chars, pos, rcount, rpos, orChars, c);
                break;
            case ParseTextFunction.ReadData:
                task = ParseTextAsync_ReadData(outOrChars, chars, pos, rcount, rpos, orChars, c);
                break;
            case ParseTextFunction.Surrogate:
                task = ParseTextAsync_Surrogate(outOrChars, chars, pos, rcount, rpos, orChars, c);
                break;
            case ParseTextFunction.NoValue:
                return ParseText_NoValue(outOrChars, pos);
            case ParseTextFunction.PartialValue:
                return ParseText_PartialValue(pos, rcount, rpos, orChars, c);
            }
        }
    }
References System.Xml.XmlTextReaderImpl._lastParseTextState, System.Xml.XmlTextReaderImpl._parseText_NextFunction, System.Xml.XmlTextReaderImpl.ParseTextState.c, System.chars, System.Xml.XmlTextReaderImpl.ParseTextState.chars, System.Xml.XmlTextReaderImpl.ParseTextState.orChars, System.Xml.XmlTextReaderImpl.ParseTextState.outOrChars, System.Xml.XmlTextReaderImpl.ParseText_NoValue(), System.Xml.XmlTextReaderImpl.ParseText_PartialValue(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync_ParseEntity(), System.Xml.XmlTextReaderImpl.ParseTextAsync_ReadData(), System.Xml.XmlTextReaderImpl.ParseTextAsync_Surrogate(), System.Xml.XmlTextReaderImpl.ParseTextState.pos, System.Xml.XmlTextReaderImpl.ParseTextState.rcount, System.Xml.XmlTextReaderImpl.ParseTextState.rpos, and System.task.
Referenced by System.Xml.XmlTextReaderImpl.ParseTextAsync().