Terraria: System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo
ThrowWithoutLineInfo() [1/3]
void System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (string res) inline private
Definition at line 3005 of file XmlTextReaderImpl.cs.
    {
        Throw(new XmlException(res, string.Empty, _ps.baseUriStr));
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.baseUriStr, System.Xml.XmlTextReaderImpl.Throw(), and System.Xml.XmlException.
Referenced by System.Xml.XmlTextReaderImpl.CheckEncoding(), System.Xml.XmlTextReaderImpl.OpenUrl(), System.Xml.XmlTextReaderImpl.ParseDoctypeDecl(), System.Xml.XmlTextReaderImpl.ParseDoctypeDeclAsync(), System.Xml.XmlTextReaderImpl.ParseDocumentContent(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(), System.Xml.XmlTextReaderImpl.ProcessDtdFromParserContext(), System.Xml.XmlTextReaderImpl.ProcessDtdFromParserContextAsync(), System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubset(), System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubsetAsync(), System.Xml.XmlTextReaderImpl.Read(), System.Xml.XmlTextReaderImpl.ReadAsync(), and System.Xml.XmlTextReaderImpl.RegisterConsumedCharacters().