Terraria: System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync
ParseAttributeValueSlowAsync()
async Task System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync (int curPos, char quoteChar, NodeData attr) inline private
Definition at line 10677 of file XmlTextReaderImpl.cs.
    {
        int pos = curPos;
        char[] chars = _ps.chars;
        int attributeBaseEntityId = _ps.entityId;
        int valueChunkStartPos = 0;
        LineInfo valueChunkLineInfo = new LineInfo(_ps.lineNo, _ps.LinePos);
        NodeData lastChunk = null;
        while (true)
        {
            if (XmlCharType.IsAttributeValueChar(chars[pos]))
            {
                pos++;
                continue;
            }
            if (pos - _ps.charPos > 0)
            {
                _stringBuilder.Append(chars, _ps.charPos, pos - _ps.charPos);
                _ps.charPos = pos;
            }
            if (chars[pos] == quoteChar && attributeBaseEntityId == _ps.entityId)
            {
                break;
            }
            switch (chars[pos])
            {
            case '\n':
                pos++;
                OnNewLine(pos);
                if (_normalize)
                {
                    _stringBuilder.Append(' ');
                    _ps.charPos++;
                }
                continue;
            case '\r':
                if (chars[pos + 1] == '\n')
                {
                    pos += 2;
                    if (_normalize)
                    {
                        _stringBuilder.Append(_ps.eolNormalized ? "  " : " ");
                        _ps.charPos = pos;
                    }
                }
                else
                {
                    if (pos + 1 >= _ps.charsUsed && !_ps.isEof)
                    {
                        break;
                    }
                    pos++;
                    if (_normalize)
                    {
                        _stringBuilder.Append(' ');
                        _ps.charPos = pos;
                    }
                }
                OnNewLine(pos);
                continue;
            case '\t':
                pos++;
                if (_normalize)
                {
                    _stringBuilder.Append(' ');
                    _ps.charPos++;
                }
                continue;
            case '"':
            case '\'':
            case '>':
                pos++;
                continue;
            case '<':
                Throw(pos, System.SR.Xml_BadAttributeChar, XmlException.BuildCharExceptionArgs('<', '\0'));
                break;
            case '&':
            {
                if (pos - _ps.charPos > 0)
                {
                    _stringBuilder.Append(chars, _ps.charPos, pos - _ps.charPos);
                }
                _ps.charPos = pos;
                int enclosingEntityId = _ps.entityId;
                LineInfo entityLineInfo = new LineInfo(_ps.lineNo, _ps.LinePos + 1);
                (int, EntityType) tuple = await HandleEntityReferenceAsync(isInAttributeValue: true, EntityExpandType.All).ConfigureAwait(continueOnCapturedContext: false);
                (pos, _) = tuple;
                switch (tuple.Item2)
                {
                case EntityType.Unexpanded:
                    if (_parsingMode == ParsingMode.Full && _ps.entityId == attributeBaseEntityId)
                    {
                        int num2 = _stringBuilder.Length - valueChunkStartPos;
                        if (num2 > 0)
{
                            NodeData nodeData3 = new NodeData();
                            nodeData3.lineInfo = valueChunkLineInfo;
                            nodeData3.depth = attr.depth + 1;
                            nodeData3.SetValueNode(XmlNodeType.Text, _stringBuilder.ToString(valueChunkStartPos, num2));
                            AddAttributeChunkToList(attr, nodeData3, ref lastChunk);
                        }
                        _ps.charPos++;
                        string text = await ParseEntityNameAsync().ConfigureAwait(continueOnCapturedContext: false);
                        NodeData nodeData4 = new NodeData();
                        nodeData4.lineInfo = entityLineInfo;
                        nodeData4.depth = attr.depth + 1;
                        nodeData4.SetNamedNode(XmlNodeType.EntityReference, text);
                        AddAttributeChunkToList(attr, nodeData4, ref lastChunk);
                        _stringBuilder.Append('&');
                        _stringBuilder.Append(text);
                        _stringBuilder.Append(';');
                        valueChunkStartPos = _stringBuilder.Length;
                        valueChunkLineInfo.Set(_ps.LineNo, _ps.LinePos);
                        _fullAttrCleanup = true;
                    }
                    else
                    {
                        _ps.charPos++;
                        await ParseEntityNameAsync().ConfigureAwait(continueOnCapturedContext: false);
                    }
                    pos = _ps.charPos;
                    break;
                case EntityType.ExpandedInAttribute:
                    if (_parsingMode == ParsingMode.Full && enclosingEntityId == attributeBaseEntityId)
                    {
                        int num = _stringBuilder.Length - valueChunkStartPos;
                        if (num > 0)
{
                            NodeData nodeData = new NodeData();
                            nodeData.lineInfo = valueChunkLineInfo;
                            nodeData.depth = attr.depth + 1;
                            nodeData.SetValueNode(XmlNodeType.Text, _stringBuilder.ToString(valueChunkStartPos, num));
                            AddAttributeChunkToList(attr, nodeData, ref lastChunk);
                        }
                        NodeData nodeData2 = new NodeData();
                        nodeData2.lineInfo = entityLineInfo;
                        nodeData2.depth = attr.depth + 1;
                        nodeData2.SetNamedNode(XmlNodeType.EntityReference, _ps.entity.Name);
                        AddAttributeChunkToList(attr, nodeData2, ref lastChunk);
                        _fullAttrCleanup = true;
                    }
                    pos = _ps.charPos;
                    break;
                default:
                    pos = _ps.charPos;
                    break;
                case EntityType.CharacterDec:
                case EntityType.CharacterHex:
                case EntityType.CharacterNamed:
                    break;
                }
                chars = _ps.chars;
                continue;
            }
            default:
            {
                if (pos == _ps.charsUsed)
                {
                    break;
                }
                char ch = chars[pos];
                if (XmlCharType.IsHighSurrogate(ch))
                {
                    if (pos + 1 == _ps.charsUsed)
                    {
                        break;
                    }
                    pos++;
                    if (XmlCharType.IsLowSurrogate(chars[pos]))
                    {
                        pos++;
                        continue;
                    }
                }
                ThrowInvalidChar(chars, _ps.charsUsed, pos);
                break;
            }
            }
            if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
            {
                if (_ps.charsUsed - _ps.charPos > 0)
                {
                    if (_ps.chars[_ps.charPos] != '\r')
                    {
                        Throw(System.SR.Xml_UnexpectedEOF1);
                    }
                }
                else
                {
                    if (!InEntity)
                    {
                        if (_fragmentType == XmlNodeType.Attribute)
{
                            if (attributeBaseEntityId != _ps.entityId)
{
                                Throw(System.SR.Xml_EntityRefNesting);
                            }
                            break;
                        }
                        Throw(System.SR.Xml_UnclosedQuote);
                    }
                    if (HandleEntityEnd(checkEntityNesting: true))
                    {
                        Throw(System.SR.Xml_InternalError);
                    }
                    if (attributeBaseEntityId == _ps.entityId)
                    {
                        valueChunkStartPos = _stringBuilder.Length;
                        valueChunkLineInfo.Set(_ps.LineNo, _ps.LinePos);
                    }
                }
            }
            pos = _ps.charPos;
            chars = _ps.chars;
        }
        if (attr.nextAttrValueChunk != null)
        {
            int num3 = _stringBuilder.Length - valueChunkStartPos;
            if (num3 > 0)
            {
                NodeData nodeData5 = new NodeData();
                nodeData5.lineInfo = valueChunkLineInfo;
                nodeData5.depth = attr.depth + 1;
                nodeData5.SetValueNode(XmlNodeType.Text, _stringBuilder.ToString(valueChunkStartPos, num3));
                AddAttributeChunkToList(attr, nodeData5, ref lastChunk);
            }
        }
        _ps.charPos = pos + 1;
        attr.SetValue(_stringBuilder.ToString());
        _stringBuilder.Length = 0;
    }
References System.Xml.XmlTextReaderImpl._fragmentType, System.Xml.XmlTextReaderImpl._fullAttrCleanup, System.Xml.XmlTextReaderImpl._normalize, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Xml.XmlTextReaderImpl.AddAttributeChunkToList(), System.Text.StringBuilder.Append(), System.Xml.XmlException.BuildCharExceptionArgs(), System.ch, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.entity, System.Xml.XmlTextReaderImpl.ParsingState.entityId, System.Xml.XmlTextReaderImpl.ParsingState.eolNormalized, System.Xml.XmlTextReaderImpl.HandleEntityEnd(), System.Xml.XmlTextReaderImpl.HandleEntityReferenceAsync(), System.Xml.XmlTextReaderImpl.int, System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlTextReaderImpl.ParsingState.isEof, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Text.StringBuilder.Length, System.Xml.XmlTextReaderImpl.ParsingState.lineNo, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.IDtdEntityInfo.Name, System.Xml.XmlTextReaderImpl.OnNewLine(), System.Xml.XmlTextReaderImpl.ParseEntityNameAsync(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.text, System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), System.Text.StringBuilder.ToString(), System.SR.Xml_BadAttributeChar, System.SR.Xml_EntityRefNesting, System.SR.Xml_InternalError, System.SR.Xml_UnclosedQuote, and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlTextReaderImpl.ParseAttributesAsync().