Terraria: System.Xml.XmlTextReaderImpl.ParseElementAsync_NoAttributes
ParseElementAsync_NoAttributes()
Task System.Xml.XmlTextReaderImpl.ParseElementAsync_NoAttributes () inline private
Definition at line 10206 of file XmlTextReaderImpl.cs.
    {
        int charPos = _ps.charPos;
        char[] chars = _ps.chars;
        switch (chars[charPos])
        {
        case '>':
            _ps.charPos = charPos + 1;
            _parsingFunction = ParsingFunction.MoveToElementContent;
            break;
        case '/':
            if (charPos + 1 == _ps.charsUsed)
            {
                _ps.charPos = charPos;
                return ParseElementAsync_ReadData(charPos);
            }
            if (chars[charPos + 1] == '>')
            {
                _curNode.IsEmptyElement = true;
                _nextParsingFunction = _parsingFunction;
                _parsingFunction = ParsingFunction.PopEmptyElementContext;
                _ps.charPos = charPos + 2;
            }
            else
            {
                ThrowUnexpectedToken(charPos, ">");
            }
            break;
        default:
            Throw(charPos, System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(chars, _ps.charsUsed, charPos));
            break;
        }
        if (_addDefaultAttributesAndNormalize)
        {
            AddDefaultAttributesAndNormalize();
        }
        ElementNamespaceLookup();
        return Task.CompletedTask;
    }
References System.Xml.XmlTextReaderImpl._addDefaultAttributesAndNormalize, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.AddDefaultAttributesAndNormalize(), System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ElementNamespaceLookup(), System.Xml.XmlTextReaderImpl.ParseElementAsync_ReadData(), System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(), and System.SR.Xml_BadNameChar.
Referenced by System.Xml.XmlTextReaderImpl.ParseElementAsync_ReadData(), and System.Xml.XmlTextReaderImpl.ParseElementAsync_SetElement().