Terraria: System.Xml.XmlTextReaderImpl.SetupEncoding
SetupEncoding()
void System.Xml.XmlTextReaderImpl.SetupEncoding (Encoding encoding) inline private
Definition at line 3340 of file XmlTextReaderImpl.cs.
    {
        if (encoding == null)
        {
            _ps.encoding = Encoding.UTF8;
            _ps.decoder = new SafeAsciiDecoder();
            return;
        }
        _ps.encoding = encoding;
        _ = _ps;
        string webName = _ps.encoding.WebName;
        Decoder decoder = ((webName == "utf-16") ? new UTF16Decoder(bigEndian: false) : ((!(webName == "utf-16BE")) ? encoding.GetDecoder() : new UTF16Decoder(bigEndian: true)));
        _ps.decoder = decoder;
    }
References System.Xml.XmlTextReaderImpl._ps, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Text.Encoding.GetDecoder(), System.Text.Encoding.UTF8, and System.Text.Encoding.WebName.
Referenced by System.Xml.XmlTextReaderImpl.InitStreamInput(), System.Xml.XmlTextReaderImpl.InitStreamInputAsync(), System.Xml.XmlTextReaderImpl.SwitchEncoding(), and System.Xml.XmlTextReaderImpl.SwitchEncodingAsync().