Terraria: System.Xml.XmlTextReaderImpl.ParseCDataOrComment
ParseCDataOrComment() [1/2]
void System.Xml.XmlTextReaderImpl.ParseCDataOrComment (XmlNodeType type) inline private
Definition at line 6009 of file XmlTextReaderImpl.cs.
    {
        int outStartPos;
        int outEndPos;
        if (_parsingMode == ParsingMode.Full)
        {
            _curNode.SetLineInfo(_ps.LineNo, _ps.LinePos);
            if (ParseCDataOrComment(type, out outStartPos, out outEndPos))
            {
                _curNode.SetValueNode(type, _ps.chars, outStartPos, outEndPos - outStartPos);
                return;
            }
            do
            {
                _stringBuilder.Append(_ps.chars, outStartPos, outEndPos - outStartPos);
            }
            while (!ParseCDataOrComment(type, out outStartPos, out outEndPos));
            _stringBuilder.Append(_ps.chars, outStartPos, outEndPos - outStartPos);
            _curNode.SetValueNode(type, _stringBuilder.ToString());
            _stringBuilder.Length = 0;
        }
        else
        {
            while (!ParseCDataOrComment(type, out outStartPos, out outEndPos))
            {
            }
        }
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._parsingMode, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._stringBuilder, System.Text.StringBuilder.Append(), System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.ParsingState.LineNo, System.Xml.XmlTextReaderImpl.ParsingState.LinePos, System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.SetValueNode(), System.Text.StringBuilder.ToString(), and System.type.
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_ParseComment(), System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.XmlTextReaderImpl.ParseCData(), System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), and System.Xml.XmlTextReaderImpl.ParseComment().