Terraria: System.Xml.XmlTextReaderImpl.ReadChars
ReadChars()
int System.Xml.XmlTextReaderImpl.ReadChars (char[] buffer, int index, int count) inline package
Definition at line 2670 of file XmlTextReaderImpl.cs.
    {
        if (_parsingFunction == ParsingFunction.InIncrementalRead)
        {
            if (_incReadDecoder != _readCharsDecoder)
            {
                if (_readCharsDecoder == null)
                {
                    _readCharsDecoder = new IncrementalReadCharsDecoder();
                }
                _readCharsDecoder.Reset();
                _incReadDecoder = _readCharsDecoder;
            }
            return IncrementalRead(buffer, index, count);
        }
        if (_curNode.type != XmlNodeType.Element)
        {
            return 0;
        }
        if (_curNode.IsEmptyElement)
        {
            _outerReader.Read();
            return 0;
        }
        if (_readCharsDecoder == null)
        {
            _readCharsDecoder = new IncrementalReadCharsDecoder();
        }
        InitIncrementalRead(_readCharsDecoder);
        return IncrementalRead(buffer, index, count);
    }
References System.Xml.XmlTextReaderImpl._curNode, System.Xml.XmlTextReaderImpl._incReadDecoder, System.Xml.XmlTextReaderImpl._outerReader, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readCharsDecoder, System.buffer, System.count, System.Xml.XmlTextReaderImpl.IncrementalRead(), System.index, System.Xml.XmlTextReaderImpl.InitIncrementalRead(), System.Xml.XmlTextReaderImpl.NodeData.IsEmptyElement, System.Xml.XmlReader.Read(), System.Xml.IncrementalReadCharsDecoder.Reset(), and System.Xml.XmlTextReaderImpl.NodeData.type.
Referenced by System.Xml.XmlTextReader.ReadChars().