Terraria: System.Xml.XmlTextReaderImpl.CheckEncoding
CheckEncoding()
Encoding System.Xml.XmlTextReaderImpl.CheckEncoding (string newEncodingName) inline private
Definition at line 3380 of file XmlTextReaderImpl.cs.
    {
        if (_ps.stream == null)
        {
            return _ps.encoding;
        }
        if (string.Equals(newEncodingName, "ucs-2", StringComparison.OrdinalIgnoreCase) || string.Equals(newEncodingName, "utf-16", StringComparison.OrdinalIgnoreCase) || string.Equals(newEncodingName, "iso-10646-ucs-2", StringComparison.OrdinalIgnoreCase) || string.Equals(newEncodingName, "ucs-4", StringComparison.OrdinalIgnoreCase))
        {
            if (_ps.encoding.WebName != "utf-16BE" && _ps.encoding.WebName != "utf-16" && !string.Equals(newEncodingName, "ucs-4", StringComparison.OrdinalIgnoreCase))
            {
                if (_afterResetState)
                {
                    Throw(System.SR.Xml_EncodingSwitchAfterResetState, newEncodingName);
                }
                else
                {
                    ThrowWithoutLineInfo(System.SR.Xml_MissingByteOrderMark);
                }
            }
            return _ps.encoding;
        }
        Encoding encoding = null;
        if (string.Equals(newEncodingName, "utf-8", StringComparison.OrdinalIgnoreCase))
        {
            encoding = UTF8BomThrowing;
        }
        else
        {
            try
            {
                encoding = Encoding.GetEncoding(newEncodingName);
            }
            catch (NotSupportedException innerException)
            {
                Throw(System.SR.Xml_UnknownEncoding, newEncodingName, innerException);
            }
            catch (ArgumentException innerException2)
            {
                Throw(System.SR.Xml_UnknownEncoding, newEncodingName, innerException2);
            }
        }
        if (_afterResetState && _ps.encoding.WebName != encoding.WebName)
        {
            Throw(System.SR.Xml_EncodingSwitchAfterResetState, newEncodingName);
        }
        return encoding;
    }
References System.Xml.XmlTextReaderImpl._afterResetState, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Text.Encoding.GetEncoding(), System.Xml.XmlTextReaderImpl.ParsingState.stream, System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(), System.Xml.XmlTextReaderImpl.UTF8BomThrowing, System.Text.Encoding.WebName, System.SR.Xml_EncodingSwitchAfterResetState, System.SR.Xml_MissingByteOrderMark, and System.SR.Xml_UnknownEncoding.
Referenced by System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), and System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync().