Terraria: System.Xml.XmlTextReaderImpl.LookupNamespace
LookupNamespace() [2/3]
override string System.Xml.XmlTextReaderImpl.LookupNamespace (string prefix) inline
Implements System.Xml.IXmlNamespaceResolver.
Definition at line 2153 of file XmlTextReaderImpl.cs.
    {
        if (!_supportNamespaces)
        {
            return null;
        }
        return _namespaceManager.LookupNamespace(prefix);
    }
References System.Xml.XmlTextReaderImpl._namespaceManager, System.Xml.XmlTextReaderImpl._supportNamespaces, System.Xml.XmlNamespaceManager.LookupNamespace(), and System.prefix.
Referenced by System.Xml.XmlTextReaderImpl.AttributeNamespaceLookup(), System.Xml.XmlTextReaderImpl.ElementNamespaceLookup(), System.Xml.XmlTextReader.LookupNamespace(), System.Xml.XmlTextReaderImpl.LookupNamespace(), and System.Xml.XmlValidatingReaderImpl.LookupNamespace().