Terraria: System.Xml.XmlTextReaderImpl.XmlTextReaderImpl
XmlTextReaderImpl() [18/20]
System.Xml.XmlTextReaderImpl.XmlTextReaderImpl (Stream stream, byte[] bytes, int byteCount, XmlReaderSettings settings, Uri baseUri, string baseUriStr, XmlParserContext context, bool closeInput) inline package
Definition at line 1748 of file XmlTextReaderImpl.cs.
        : this(settings.GetXmlResolver(), settings, context)
    {
        if (context != null && context.BaseURI != null && context.BaseURI.Length > 0 && !UriEqual(baseUri, baseUriStr, context.BaseURI, settings.GetXmlResolver()))
        {
            if (baseUriStr.Length > 0)
            {
                Throw(System.SR.Xml_DoubleBaseUri);
            }
            baseUriStr = context.BaseURI;
        }
        _reportedBaseUri = baseUriStr ?? string.Empty;
        _closeInput = closeInput;
        _laterInitParam = new LaterInitParam();
        _laterInitParam.inputStream = stream;
        _laterInitParam.inputBytes = bytes;
        _laterInitParam.inputByteCount = byteCount;
        _laterInitParam.inputbaseUri = baseUri;
        _laterInitParam.inputContext = context;
        _laterInitParam.initType = InitInputType.Stream;
        if (!settings.Async)
        {
            FinishInitStream();
        }
        else
        {
            _laterInitParam.useAsync = true;
        }
    }
References System.Xml.XmlTextReaderImpl._closeInput, System.Xml.XmlTextReaderImpl._laterInitParam, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlReaderSettings.Async, System.Xml.XmlParserContext.BaseURI, System.byteCount, System.bytes, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.FinishInitStream(), System.Xml.XmlReaderSettings.GetXmlResolver(), System.stream, System.Xml.XmlTextReaderImpl.Throw(), System.Xml.XmlTextReaderImpl.UriEqual(), and System.SR.Xml_DoubleBaseUri.