Terraria: System.Xml.XmlTextReaderImpl.FinishReadValueChunk
FinishReadValueChunk()
void System.Xml.XmlTextReaderImpl.FinishReadValueChunk () inline private
Definition at line 5508 of file XmlTextReaderImpl.cs.
    {
        _readValueOffset = 0;
        if (_incReadState == IncrementalReadState.ReadValueChunk_OnPartialValue)
        {
            SkipPartialTextValue();
            return;
        }
        _parsingFunction = _nextParsingFunction;
        _nextParsingFunction = _nextNextParsingFunction;
    }
References System.Xml.XmlTextReaderImpl._incReadState, System.Xml.XmlTextReaderImpl._nextNextParsingFunction, System.Xml.XmlTextReaderImpl._nextParsingFunction, System.Xml.XmlTextReaderImpl._parsingFunction, System.Xml.XmlTextReaderImpl._readValueOffset, and System.Xml.XmlTextReaderImpl.SkipPartialTextValue().
Referenced by System.Xml.XmlTextReaderImpl.FinishAttributeValueIterator(), System.Xml.XmlTextReaderImpl.Read(), System.Xml.XmlTextReaderImpl.ReadAttributeValue(), and System.Xml.XmlTextReaderImpl.Skip().