Terraria: System.Xml.XmlTextReaderImpl.FinishInitStream
FinishInitStream()
void System.Xml.XmlTextReaderImpl.FinishInitStream () inline private
Definition at line 1778 of file XmlTextReaderImpl.cs.
    {
        Encoding encoding = null;
        if (_laterInitParam.inputContext != null)
        {
            encoding = _laterInitParam.inputContext.Encoding;
        }
        InitStreamInput(_laterInitParam.inputbaseUri, _reportedBaseUri, _laterInitParam.inputStream, _laterInitParam.inputBytes, _laterInitParam.inputByteCount, encoding);
        _reportedEncoding = _ps.encoding;
        if (_laterInitParam.inputContext != null && _laterInitParam.inputContext.HasDtdInfo)
        {
            ProcessDtdFromParserContext(_laterInitParam.inputContext);
        }
        _laterInitParam = null;
    }
References System.Xml.XmlTextReaderImpl._laterInitParam, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._reportedBaseUri, System.Xml.XmlTextReaderImpl._reportedEncoding, System.Xml.XmlParserContext.Encoding, System.Xml.XmlTextReaderImpl.ParsingState.encoding, System.Xml.XmlParserContext.HasDtdInfo, System.Xml.XmlTextReaderImpl.InitStreamInput(), System.Xml.XmlTextReaderImpl.LaterInitParam.inputbaseUri, System.Xml.XmlTextReaderImpl.LaterInitParam.inputByteCount, System.Xml.XmlTextReaderImpl.LaterInitParam.inputBytes, System.Xml.XmlTextReaderImpl.LaterInitParam.inputContext, System.Xml.XmlTextReaderImpl.LaterInitParam.inputStream, and System.Xml.XmlTextReaderImpl.ProcessDtdFromParserContext().
Referenced by System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), and System.Xml.XmlTextReaderImpl.FinishInit().