Terraria: System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline
ParseNumericCharRefInline()
int System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline (int startPos, bool expand, StringBuilder internalSubsetBuilder, out int charCount, out EntityType entityType) inline private
Definition at line 6615 of file XmlTextReaderImpl.cs.
    {
        int num = 0;
        string res = null;
        char[] chars = _ps.chars;
        int i = startPos + 2;
        charCount = 0;
        int num2 = 0;
        try
        {
            if (chars[i] == 'x')
            {
                i++;
                num2 = i;
                res = System.SR.Xml_BadHexEntity;
                while (true)
                {
                    int num3 = System.HexConverter.FromChar(chars[i]);
                    if (num3 == 255)
                    {
                        break;
                    }
                    num = checked(num * 16 + num3);
                    i++;
                }
                entityType = EntityType.CharacterHex;
            }
            else
            {
                if (i >= _ps.charsUsed)
                {
                    entityType = EntityType.Skipped;
                    return -2;
                }
                num2 = i;
                res = System.SR.Xml_BadDecimalEntity;
                for (; chars[i] >= '0' && chars[i] <= '9'; i++)
                {
                    num = checked(num * 10 + chars[i] - 48);
                }
                entityType = EntityType.CharacterDec;
            }
        }
        catch (OverflowException innerException)
        {
            _ps.charPos = i;
            entityType = EntityType.Skipped;
            Throw(System.SR.Xml_CharEntityOverflow, (string)null, (Exception)innerException);
        }
        if (chars[i] != ';' || num2 == i)
        {
            if (i == _ps.charsUsed)
            {
                return -2;
            }
            Throw(i, res);
        }
        if (num <= 65535)
        {
            char c = (char)num;
            if (!XmlCharType.IsCharData(c) && ((_v1Compat && _normalize) || (!_v1Compat && _checkCharacters)))
            {
                Throw((_ps.chars[startPos + 2] == 'x') ? (startPos + 3) : (startPos + 2), System.SR.Xml_InvalidCharacter, XmlException.BuildCharExceptionArgs(c, '\0'));
            }
            if (expand)
            {
                internalSubsetBuilder?.Append(_ps.chars, _ps.charPos, i - _ps.charPos + 1);
                chars[i] = c;
            }
            charCount = 1;
            return i + 1;
        }
        XmlCharType.SplitSurrogateChar(num, out var lowChar, out var highChar);
        if (_normalize && (!XmlCharType.IsHighSurrogate(highChar) || !XmlCharType.IsLowSurrogate(lowChar)))
        {
            Throw((_ps.chars[startPos + 2] == 'x') ? (startPos + 3) : (startPos + 2), System.SR.Xml_InvalidCharacter, XmlException.BuildCharExceptionArgs(highChar, lowChar));
        }
        if (expand)
        {
            internalSubsetBuilder?.Append(_ps.chars, _ps.charPos, i - _ps.charPos + 1);
            chars[i - 1] = highChar;
            chars[i] = lowChar;
        }
        charCount = 2;
        return i + 1;
    }
References System.Xml.XmlTextReaderImpl._checkCharacters, System.Xml.XmlTextReaderImpl._normalize, System.Xml.XmlTextReaderImpl._ps, System.Xml.XmlTextReaderImpl._v1Compat, System.Xml.XmlException.BuildCharExceptionArgs(), System.charCount, System.Xml.XmlTextReaderImpl.ParsingState.charPos, System.chars, System.Xml.XmlTextReaderImpl.ParsingState.chars, System.Xml.XmlTextReaderImpl.ParsingState.charsUsed, System.Xml.Dictionary, System.HexConverter.FromChar(), System.Xml.XmlCharType.IsCharData(), System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Xml.XmlCharType.SplitSurrogateChar(), System.Xml.XmlTextReaderImpl.Throw(), System.SR.Xml_BadDecimalEntity, System.SR.Xml_BadHexEntity, System.SR.Xml_CharEntityOverflow, and System.SR.Xml_InvalidCharacter.
Referenced by System.Xml.XmlTextReaderImpl.ParseCharRefInline(), System.Xml.XmlTextReaderImpl.ParseNumericCharRef(), and System.Xml.XmlTextReaderImpl.ParseNumericCharRefAsync().