Terraria: Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD
QuickCDD() [2/2]
static void Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD (List< DrawData > drawData, Texture2D texture, Vector2 position, Rectangle? sourceRectangle, Color color, float rotation, Vector2 origin, float scale, SpriteEffects effects, float layerDepth) inline static
Definition at line 431 of file PlayerDrawHeadLayers.cs.
    {
        drawData.Add(new DrawData(texture, position, sourceRectangle, color, rotation, origin, scale, effects));
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add().
Referenced by Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_01_FaceSkin(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_BadgersHat(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_CapricornMask(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_RabbitOrder(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_05_TallHats(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_06_NormalHats(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_07_JustHair(), and Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc().