Terraria: System.Net.Http.HttpWindowsProxy.GetMultiProxy
GetMultiProxy()
MultiProxy System.Net.Http.HttpWindowsProxy.GetMultiProxy (Uri uri) inline
Implements System.Net.Http.IMultiWebProxy.
Definition at line 181 of file HttpWindowsProxy.cs.
    {
        if (_proxyHelper.AutoSettingsUsed && !_proxyHelper.RecentAutoDetectionFailure)
        {
            global::Interop.WinHttp.WINHTTP_PROXY_INFO proxyInfo = default(global::Interop.WinHttp.WINHTTP_PROXY_INFO);
            try
            {
                if (!_proxyHelper.GetProxyForUrl(_sessionHandle, uri, out proxyInfo))
                {
                    return MultiProxy.Empty;
                }
                if (proxyInfo.ProxyBypass == IntPtr.Zero)
                {
                    if (proxyInfo.Proxy != IntPtr.Zero)
                    {
                        string proxyConfig = Marshal.PtrToStringUni(proxyInfo.Proxy);
                        return MultiProxy.CreateLazy(_failedProxies, proxyConfig, IsSecureUri(uri));
                    }
                    return MultiProxy.Empty;
                }
            }
            finally
            {
                Marshal.FreeHGlobal(proxyInfo.Proxy);
                Marshal.FreeHGlobal(proxyInfo.ProxyBypass);
            }
        }
        if (_proxyHelper.ManualSettingsUsed)
        {
            if (_bypassLocal)
            {
                if (uri.IsLoopback)
                {
                    return MultiProxy.Empty;
                }
                if ((uri.HostNameType == UriHostNameType.IPv6 || uri.HostNameType == UriHostNameType.IPv4) && IPAddress.TryParse(uri.IdnHost, out IPAddress address))
                {
                    foreach (IPAddress item in _localIp)
                    {
                        if (item.Equals(address))
{
                            return MultiProxy.Empty;
                        }
                    }
                }
                if (uri.HostNameType != UriHostNameType.IPv6 && !uri.IdnHost.Contains('.'))
                {
                    return MultiProxy.Empty;
                }
            }
            if (_bypass != null)
            {
                foreach (string item2 in _bypass)
                {
                    if (SimpleRegex.IsMatchWithStarWildcard(uri.IdnHost, item2))
                    {
                        return MultiProxy.Empty;
                    }
                }
            }
            if (!IsSecureUri(uri))
            {
                return _insecureProxy;
            }
            return _secureProxy;
        }
        return MultiProxy.Empty;
    }
References System.Net.Http.HttpWindowsProxy._bypass, System.Net.Http.HttpWindowsProxy._bypassLocal, System.Net.Http.HttpWindowsProxy._failedProxies, System.Net.Http.HttpWindowsProxy._insecureProxy, System.Net.Http.HttpWindowsProxy._localIp, System.Net.Http.HttpWindowsProxy._proxyHelper, System.Net.Http.HttpWindowsProxy._secureProxy, System.Net.Http.HttpWindowsProxy._sessionHandle, System.Net.Http.WinInetProxyHelper.AutoSettingsUsed, System.Net.Http.MultiProxy.CreateLazy(), System.Net.Http.MultiProxy.Empty, System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Net.Http.WinInetProxyHelper.GetProxyForUrl(), System.Uri.HostNameType, System.Uri.IdnHost, System.Uri.IsLoopback, System.Text.SimpleRegex.IsMatchWithStarWildcard(), System.Net.Http.HttpWindowsProxy.IsSecureUri(), System.item, System.Net.Http.WinInetProxyHelper.ManualSettingsUsed, System.Runtime.InteropServices.Marshal.PtrToStringUni(), System.Net.Http.WinInetProxyHelper.RecentAutoDetectionFailure, System.Net.IPAddress.TryParse(), and System.IntPtr.Zero.
Referenced by System.Net.Http.HttpWindowsProxy.GetProxy().