Terraria: System.Net.Http.HttpWindowsProxy.HttpWindowsProxy
HttpWindowsProxy()
System.Net.Http.HttpWindowsProxy.HttpWindowsProxy (WinInetProxyHelper proxyHelper, global::Interop::WinHttp::SafeWinHttpHandle sessionHandle) inline private
Definition at line 73 of file HttpWindowsProxy.cs.
    {
        _proxyHelper = proxyHelper;
        _sessionHandle = sessionHandle;
        if (!proxyHelper.ManualSettingsUsed)
        {
            return;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(proxyHelper, $"ManualSettingsUsed, {proxyHelper.Proxy}", ".ctor");
        }
        _secureProxy = MultiProxy.Parse(_failedProxies, proxyHelper.Proxy, secure: true);
        _insecureProxy = MultiProxy.Parse(_failedProxies, proxyHelper.Proxy, secure: false);
        if (!string.IsNullOrWhiteSpace(proxyHelper.ProxyBypass))
        {
            int i = 0;
            int num = 0;
            _bypass = new List<string>(proxyHelper.ProxyBypass.Length / 5);
            while (i < proxyHelper.ProxyBypass.Length)
            {
                for (; i < proxyHelper.ProxyBypass.Length && proxyHelper.ProxyBypass[i] == ' '; i++)
                {
                }
                if (string.Compare(proxyHelper.ProxyBypass, i, "http://", 0, 7, StringComparison.OrdinalIgnoreCase) == 0)
                {
                    i += 7;
                }
                else if (string.Compare(proxyHelper.ProxyBypass, i, "https://", 0, 8, StringComparison.OrdinalIgnoreCase) == 0)
                {
                    i += 8;
                }
                if (i < proxyHelper.ProxyBypass.Length && proxyHelper.ProxyBypass[i] == '[')
                {
                    i++;
                }
                num = i;
                for (; i < proxyHelper.ProxyBypass.Length && proxyHelper.ProxyBypass[i] != ' ' && proxyHelper.ProxyBypass[i] != ';' && proxyHelper.ProxyBypass[i] != ']'; i++)
                {
                }
                string text;
                if (i == num)
                {
                    text = null;
                }
                else if (string.Compare(proxyHelper.ProxyBypass, num, "<local>", 0, 7, StringComparison.OrdinalIgnoreCase) == 0)
                {
                    _bypassLocal = true;
                    text = null;
                }
                else
                {
                    text = proxyHelper.ProxyBypass.Substring(num, i - num);
                }
                if (i < proxyHelper.ProxyBypass.Length && proxyHelper.ProxyBypass[i] != ';')
                {
                    for (; i < proxyHelper.ProxyBypass.Length && proxyHelper.ProxyBypass[i] != ';'; i++)
                    {
                    }
                }
                if (i < proxyHelper.ProxyBypass.Length && proxyHelper.ProxyBypass[i] == ';')
                {
                    i++;
                }
                if (text != null)
                {
                    _bypass.Add(text);
                }
            }
            if (_bypass.Count == 0)
            {
                _bypass = null;
            }
        }
        if (!_bypassLocal)
        {
            return;
        }
        _localIp = new List<IPAddress>();
        NetworkInterface[] allNetworkInterfaces = NetworkInterface.GetAllNetworkInterfaces();
        foreach (NetworkInterface networkInterface in allNetworkInterfaces)
        {
            IPInterfaceProperties iPProperties = networkInterface.GetIPProperties();
            foreach (UnicastIPAddressInformation unicastAddress in iPProperties.UnicastAddresses)
            {
                _localIp.Add(unicastAddress.Address);
            }
        }
    }
References System.Net.Http.HttpWindowsProxy._bypass, System.Net.Http.HttpWindowsProxy._bypassLocal, System.Net.Http.HttpWindowsProxy._failedProxies, System.Net.Http.HttpWindowsProxy._insecureProxy, System.Net.Http.HttpWindowsProxy._localIp, System.Net.Http.HttpWindowsProxy._proxyHelper, System.Net.Http.HttpWindowsProxy._secureProxy, System.Net.Http.HttpWindowsProxy._sessionHandle, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.List< T >.Count, System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.Http.MultiProxy.Parse(), and System.text.
Referenced by System.Net.Http.HttpWindowsProxy.TryCreate().