Terraria: System.Net.Http.HttpWindowsProxy.TryCreate
TryCreate()
static bool System.Net.Http.HttpWindowsProxy.TryCreate ([NotNullWhen(true)] out IWebProxy proxy) inline static
Definition at line 44 of file HttpWindowsProxy.cs.
    {
        global::Interop.WinHttp.SafeWinHttpHandle safeWinHttpHandle = null;
        proxy = null;
        WinInetProxyHelper winInetProxyHelper = new WinInetProxyHelper();
        if (!winInetProxyHelper.ManualSettingsOnly && !winInetProxyHelper.AutoSettingsUsed)
        {
            return false;
        }
        if (winInetProxyHelper.AutoSettingsUsed)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(winInetProxyHelper, FormattableStringFactory.Create("AutoSettingsUsed, calling {0}", "WinHttpOpen"), "TryCreate");
            }
            safeWinHttpHandle = global::Interop.WinHttp.WinHttpOpen(IntPtr.Zero, 1u, null, null, 268435456);
            if (safeWinHttpHandle.IsInvalid)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(winInetProxyHelper, FormattableStringFactory.Create("{0} returned invalid handle", "WinHttpOpen"), "TryCreate");
                }
                return false;
            }
        }
        proxy = new HttpWindowsProxy(winInetProxyHelper, safeWinHttpHandle);
        return true;
    }
References System.Net.Http.HttpWindowsProxy.HttpWindowsProxy(), System.Runtime.CompilerServices.FormattableStringFactory.Create(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.IntPtr.Zero.
Referenced by System.Net.Http.SystemProxyInfo.ConstructSystemProxy().