Terraria: Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair
DrawPlayer_03_HelmetHair()
static void Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair (ref PlayerDrawHeadSet drawinfo) inline static
    {
        if (!drawinfo.hideHair && drawinfo.hatHair)
        {
            Rectangle hairFrame = drawinfo.HairFrame;
            hairFrame.Y -= 336;
            if (hairFrame.Y < 0)
            {
                hairFrame.Y = 0;
            }
            if (!drawinfo.drawPlayer.invis)
            {
                QuickCDD(drawinfo.DrawData, drawinfo.hairShaderPacked, TextureAssets.PlayerHairAlt[drawinfo.drawPlayer.hair].Value, new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, hairFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
            }
        }
    }
References Terraria.GameContent.TextureAssets.PlayerHairAlt, Terraria.DataStructures.PlayerDrawHeadLayers.QuickCDD(), Terraria.Main.screenPosition, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead(), and Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent().