Terraria: System.Dynamic.Utils.TypeUtils.GetArrayAddressMethod
GetArrayAddressMethod()
static MethodInfo System.Dynamic.Utils.TypeUtils.GetArrayAddressMethod (Type arrayType) inline static
Definition at line 781 of file TypeUtils.cs.
    {
        return arrayType.GetMethod("Address", BindingFlags.Instance | BindingFlags.Public);
    }
References System.Type.GetMethod().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), and System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf().