Terraria: System.Dynamic.Utils.TypeUtils.HasReferenceEquality
HasReferenceEquality()
static bool System.Dynamic.Utils.TypeUtils.HasReferenceEquality (Type left, Type right) inline static
Definition at line 439 of file TypeUtils.cs.
    {
        if (left.IsValueType || right.IsValueType)
        {
            return false;
        }
        if (!left.IsInterface && !right.IsInterface && !AreReferenceAssignable(left, right))
        {
            return AreReferenceAssignable(right, left);
        }
        return true;
    }
References System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Type.IsInterface, and System.Type.IsValueType.
Referenced by System.Linq.Expressions.Expression< TDelegate >.ReferenceEqual(), and System.Linq.Expressions.Expression< TDelegate >.ReferenceNotEqual().