Terraria: System.Dynamic.Utils.TypeUtils.IsLegalExplicitVariantDelegateConversion
IsLegalExplicitVariantDelegateConversion()
static bool System.Dynamic.Utils.TypeUtils.IsLegalExplicitVariantDelegateConversion (Type source, Type dest) inline static
Definition at line 382 of file TypeUtils.cs.
    {
        if (!IsDelegate(source) || !IsDelegate(dest) || !source.IsGenericType || !dest.IsGenericType)
        {
            return false;
        }
        Type genericTypeDefinition = source.GetGenericTypeDefinition();
        if (dest.GetGenericTypeDefinition() != genericTypeDefinition)
        {
            return false;
        }
        Type[] genericArguments = genericTypeDefinition.GetGenericArguments();
        Type[] genericArguments2 = source.GetGenericArguments();
        Type[] genericArguments3 = dest.GetGenericArguments();
        for (int i = 0; i < genericArguments.Length; i++)
        {
            Type type = genericArguments2[i];
            Type type2 = genericArguments3[i];
            if (AreEquivalent(type, type2))
            {
                continue;
            }
            Type t = genericArguments[i];
            if (IsInvariant(t))
            {
                return false;
            }
            if (IsCovariant(t))
            {
                if (!type.HasReferenceConversionTo(type2))
                {
                    return false;
                }
            }
            else if (IsContravariant(t) && (type.IsValueType || type2.IsValueType))
            {
                return false;
            }
        }
        return true;
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Type.GetGenericArguments(), System.Type.GetGenericTypeDefinition(), System.Dynamic.Utils.TypeUtils.IsContravariant(), System.Dynamic.Utils.TypeUtils.IsCovariant(), System.Dynamic.Utils.TypeUtils.IsDelegate(), System.Type.IsGenericType, System.Dynamic.Utils.TypeUtils.IsInvariant(), System.Type.IsValueType, System.source, and System.type.
Referenced by System.Linq.Expressions.Compiler.ILGen.EmitConvertToType(), System.Dynamic.Utils.TypeUtils.HasReferenceConversionTo(), and System.Dynamic.Utils.TypeUtils.StrictHasReferenceConversionTo().