Terraria: System.Dynamic.Utils.TypeUtils.GetBooleanOperator
GetBooleanOperator()
static MethodInfo System.Dynamic.Utils.TypeUtils.GetBooleanOperator (Type type, string name) inline static
Definition at line 640 of file TypeUtils.cs.
    {
        do
        {
            MethodInfo anyStaticMethodValidated = type.GetAnyStaticMethodValidated(name, new Type[1] { type });
            if (anyStaticMethodValidated != null && anyStaticMethodValidated.IsSpecialName && !anyStaticMethodValidated.ContainsGenericParameters)
            {
                return anyStaticMethodValidated;
            }
            type = type.BaseType;
        }
        while (type != null);
        return null;
    }
References System.Reflection.MethodBase.ContainsGenericParameters, System.Reflection.MethodBase.IsSpecialName, and System.type.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodLogicalBinaryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodOrElse(), System.Linq.Expressions.BinaryExpression.ReduceUserdefinedLifted(), and System.Linq.Expressions.Expression< TDelegate >.ValidateUserDefinedConditionalLogicOperator().