Terraria: System.Dynamic.Utils.TypeUtils.IsValidInstanceType
IsValidInstanceType()
static bool System.Dynamic.Utils.TypeUtils.IsValidInstanceType (MemberInfo member, Type instanceType) inline static
Definition at line 157 of file TypeUtils.cs.
    {
        Type declaringType = member.DeclaringType;
        if (declaringType == null)
        {
            return false;
        }
        if (AreReferenceAssignable(declaringType, instanceType))
        {
            return true;
        }
        if (instanceType.IsValueType)
        {
            if (AreReferenceAssignable(declaringType, typeof(object)))
            {
                return true;
            }
            if (AreReferenceAssignable(declaringType, typeof(ValueType)))
            {
                return true;
            }
            if (instanceType.IsEnum && AreReferenceAssignable(declaringType, typeof(Enum)))
            {
                return true;
            }
            if (declaringType.IsInterface)
            {
                Type[] array = GetTypeInterfaces(instanceType);
                foreach (Type src in array)
                {
                    if (AreReferenceAssignable(declaringType, src))
                    {
                        return true;
                    }
                }
            }
        }
        return false;
        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2070:UnrecognizedReflectionPattern", Justification = "The targetType must be preserved (since we have an instance of it here),So if it's an interface that interface will be preserved everywhereSo if it was implemented by the instanceType, it will be kept even after trimming.The fact that GetInterfaces may return fewer interfaces doesn't matter as longas it returns the one we're looking for.")]
        static Type[] GetTypeInterfaces(Type instanceType)
        {
            return instanceType.GetInterfaces();
        }
    }
References System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.array, System.Reflection.MemberInfo.DeclaringType, System.Type.GetInterfaces(), System.Type.IsEnum, System.Type.IsInterface, and System.Type.IsValueType.
Referenced by System.Linq.Expressions.Expression< TDelegate >.Property(), and System.Linq.Expressions.Expression< TDelegate >.ValidateCallInstanceType().