Terraria: System.Dynamic.Utils.TypeUtils.AreReferenceAssignable
AreReferenceAssignable()
static bool System.Dynamic.Utils.TypeUtils.AreReferenceAssignable (Type dest, Type src) inline static
Definition at line 673 of file TypeUtils.cs.
    {
        if (AreEquivalent(dest, src))
        {
            return true;
        }
        if (!dest.IsValueType && !src.IsValueType)
        {
            return dest.IsAssignableFrom(src);
        }
        return false;
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Type.IsAssignableFrom(), and System.Type.IsValueType.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.AddReturnLabel(), System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Dynamic.DynamicMetaObjectBinder.Bind(), System.Linq.Expressions.Expression< TDelegate >.BlockCore(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Runtime.CompilerServices.CallSite< T >.Convert(), System.Linq.Expressions.Expression< TDelegate >.Field(), System.Linq.Expressions.Compiler.LambdaCompiler.GetEqualityOperand(), System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedAssignOperator(), System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedAssignOperatorOrThrow(), System.Dynamic.Utils.TypeUtils.HasBuiltInEqualityOperator(), System.Dynamic.Utils.TypeUtils.HasReferenceEquality(), System.Linq.Expressions.Expression< TDelegate >.IsCompatible(), System.Linq.Expressions.Expression< TDelegate >.IsCompatible(), System.Dynamic.Utils.TypeUtils.IsValidInstanceType(), System.Linq.Expressions.Expression< TDelegate >.MakeOpAssignUnary(), System.Dynamic.Utils.TypeExtensions.MatchesArgumentTypes(), System.Linq.Expressions.Expression< TDelegate >.NewArrayInit(), System.Linq.Expressions.Expression< TDelegate >.ParameterIsAssignable(), System.Linq.Expressions.Expression< TDelegate >.ReduceAndCheck(), System.Linq.Expressions.Expression< TDelegate >.ValidateAccessorArgumentTypes(), System.Linq.Expressions.Expression< TDelegate >.ValidateGotoType(), System.Linq.Expressions.Expression< TDelegate >.ValidateLambdaArgs(), System.Linq.Expressions.Expression< TDelegate >.ValidateNewArgs(), System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(), System.Linq.Expressions.Expression< TDelegate >.ValidateSwitchCaseType(), and System.Linq.Expressions.Expression< TDelegate >.ValidateTryAndCatchHaveSameType().