Terraria: System.Dynamic.Utils.TypeUtils.ValidateType
ValidateType() [2/3]
static void System.Dynamic.Utils.TypeUtils.ValidateType (Type type, string paramName, bool allowByRef, bool allowPointer) inline static
Definition at line 700 of file TypeUtils.cs.
    {
        if (ValidateType(type, paramName, -1))
        {
            if (!allowByRef && type.IsByRef)
            {
                throw Error.TypeMustNotBeByRef(paramName);
            }
            if (!allowPointer && type.IsPointer)
            {
                throw Error.TypeMustNotBePointer(paramName);
            }
        }
    }
References System.type, System.Linq.Expressions.Error.TypeMustNotBeByRef(), System.Linq.Expressions.Error.TypeMustNotBePointer(), and System.Dynamic.Utils.TypeUtils.ValidateType().