Terraria: System.Dynamic.Utils.TypeUtils.AreEquivalent
AreEquivalent()
static bool System.Dynamic.Utils.TypeUtils.AreEquivalent (Type t1, Type t2) inline static
Definition at line 664 of file TypeUtils.cs.
    {
        if (t1 != null)
        {
            return t1.IsEquivalentTo(t2);
        }
        return false;
    }
References System.Type.IsEquivalentTo().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Expression< TDelegate >.AndAlso(), System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Linq.Expressions.Expression< TDelegate >.BlockCore(), System.Linq.Expressions.Expression< TDelegate >.Coalesce(), System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddressWriteBack(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConvert(), System.Linq.Expressions.Compiler.ILGen.EmitConvertToType(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion(), System.Dynamic.BindingRestrictions.TypeRestriction.Equals(), System.Dynamic.Utils.TypeUtils.FindConversionOperator(), System.Dynamic.Utils.TypeUtils.FindGenericType(), System.Dynamic.DynamicObject.MetaDynamic.GetLimitedSelf(), System.Dynamic.ExpandoObject.MetaExpando.GetLimitedSelf(), System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedCoercionOperator(), System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedBinaryOperator(), System.Dynamic.Utils.TypeUtils.GetUserDefinedCoercionMethod(), System.Dynamic.Utils.TypeUtils.HasArrayToInterfaceConversion(), System.Dynamic.Utils.TypeUtils.HasBuiltInEqualityOperator(), System.Dynamic.Utils.TypeUtils.HasIdentityPrimitiveOrNullableConversionTo(), System.Dynamic.Utils.TypeUtils.HasInterfaceToArrayConversion(), System.Dynamic.Utils.TypeUtils.IsImplicitlyConvertibleTo(), System.Dynamic.Utils.TypeUtils.IsLegalExplicitVariantDelegateConversion(), System.Dynamic.Utils.TypeUtils.IsSameOrSubclass(), System.Linq.Expressions.Expression< TDelegate >.IsValidLiftedConditionalLogicalOperator(), System.Linq.Expressions.Expression< TDelegate >.MakeCatchBlock(), System.Linq.Expressions.Expression< TDelegate >.Switch(), System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitSwitchInstruction(), System.Linq.Expressions.ExpressionVisitor.ValidateChildType(), System.Linq.Expressions.Expression< TDelegate >.ValidateNewArgs(), System.Linq.Expressions.Expression< TDelegate >.ValidateOpAssignConversionLambda(), System.Linq.Expressions.Expression< TDelegate >.ValidateSwitchCaseType(), and System.Linq.Expressions.Expression< TDelegate >.ValidateTryAndCatchHaveSameType().