Terraria: System.Dynamic.Utils.TypeUtils.GetNullableConstructor
GetNullableConstructor()
static ConstructorInfo System.Dynamic.Utils.TypeUtils.GetNullableConstructor (Type nullableType) inline static
Definition at line 34 of file TypeUtils.cs.
    {
        return (ConstructorInfo)nullableType.GetMemberWithSameMetadataDefinitionAs(s_nullableConstructor);
    }
References System.Type.GetMemberWithSameMetadataDefinitionAs(), and System.Dynamic.Utils.TypeUtils.s_nullableConstructor.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(), System.Linq.Expressions.Compiler.ILGen.EmitNonNullableToNullableConversion(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToNullableConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), and System.Linq.Expressions.Compiler.ILGen.TryEmitILConstant().