Terraria: System.Dynamic.Utils.TypeUtils.GetArrayGetMethod
GetArrayGetMethod()
static MethodInfo System.Dynamic.Utils.TypeUtils.GetArrayGetMethod (Type arrayType) inline static
Definition at line 769 of file TypeUtils.cs.
    {
        return arrayType.GetMethod("Get", BindingFlags.Instance | BindingFlags.Public);
    }
References System.Type.GetMethod().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Expression< TDelegate >.ArrayIndex(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAddress(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMultiDimArrayAccess(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitGetArrayElement(), and System.Linq.Expressions.Interpreter.LightCompiler.EmitIndexGet().