Terraria: System.Dynamic.Utils.TypeUtils.HasBuiltInEqualityOperator
HasBuiltInEqualityOperator()
static bool System.Dynamic.Utils.TypeUtils.HasBuiltInEqualityOperator (Type left, Type right) inline static
Definition at line 452 of file TypeUtils.cs.
    {
        if (left.IsInterface && !right.IsValueType)
        {
            return true;
        }
        if (right.IsInterface && !left.IsValueType)
        {
            return true;
        }
        if (!left.IsValueType && !right.IsValueType && (AreReferenceAssignable(left, right) || AreReferenceAssignable(right, left)))
        {
            return true;
        }
        if (!AreEquivalent(left, right))
        {
            return false;
        }
        Type nonNullableType = left.GetNonNullableType();
        if (!(nonNullableType == typeof(bool)) && !nonNullableType.IsNumeric())
        {
            return nonNullableType.IsEnum;
        }
        return true;
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Type.IsEnum, System.Type.IsInterface, and System.Type.IsValueType.
Referenced by System.Linq.Expressions.Expression< TDelegate >.GetEqualityComparisonOperator().