Terraria: System.Dynamic.Utils.TypeUtils.ValidateType
ValidateType() [1/3]
static void System.Dynamic.Utils.TypeUtils.ValidateType (Type type, string paramName) inline static
Definition at line 695 of file TypeUtils.cs.
    {
        ValidateType(type, paramName, allowByRef: false, allowPointer: false);
    }
References System.type, and System.Dynamic.Utils.TypeUtils.ValidateType().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Linq.Expressions.Expression< TDelegate >.Convert(), System.Linq.Expressions.Expression< TDelegate >.ConvertChecked(), System.Linq.Expressions.Expression< TDelegate >.Default(), System.Linq.Expressions.Expression< TDelegate >.Label(), System.Linq.Expressions.Expression< TDelegate >.MakeCatchBlock(), System.Linq.Expressions.Expression< TDelegate >.New(), System.Linq.Expressions.Expression< TDelegate >.New(), System.Linq.Expressions.Expression< TDelegate >.New(), System.Linq.Expressions.Expression< TDelegate >.NewArrayBounds(), System.Linq.Expressions.Expression< TDelegate >.NewArrayInit(), System.Linq.Expressions.Expression< TDelegate >.Throw(), System.Linq.Expressions.Expression< TDelegate >.TypeAs(), System.Linq.Expressions.Expression< TDelegate >.Unbox(), System.Linq.Expressions.Expression< TDelegate >.Validate(), System.Linq.Expressions.Expression< TDelegate >.ValidateAccessorArgumentTypes(), System.Linq.Expressions.ExpressionExtension.ValidateDynamicArgument(), System.Linq.Expressions.Expression< TDelegate >.ValidateGettableFieldOrPropertyMember(), System.Linq.Expressions.Expression< TDelegate >.ValidateGoto(), System.Linq.Expressions.Expression< TDelegate >.ValidateLambdaArgs(), System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(), System.Linq.Expressions.Expression< TDelegate >.ValidateSettableFieldOrPropertyMember(), System.Dynamic.Utils.TypeUtils.ValidateType(), and System.Dynamic.Utils.TypeUtils.ValidateType().