Terraria: System.Dynamic.Utils.TypeUtils.IsImplicitlyConvertibleTo
IsImplicitlyConvertibleTo()
static bool System.Dynamic.Utils.TypeUtils.IsImplicitlyConvertibleTo (this Type source, Type destination) inline static
Definition at line 478 of file TypeUtils.cs.
    {
        if (!AreEquivalent(source, destination) && !IsImplicitNumericConversion(source, destination) && !IsImplicitReferenceConversion(source, destination) && !IsImplicitBoxingConversion(source, destination))
        {
            return IsImplicitNullableConversion(source, destination);
        }
        return true;
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.destination, System.Dynamic.Utils.TypeUtils.IsImplicitBoxingConversion(), System.Dynamic.Utils.TypeUtils.IsImplicitNullableConversion(), System.Dynamic.Utils.TypeUtils.IsImplicitNumericConversion(), System.Dynamic.Utils.TypeUtils.IsImplicitReferenceConversion(), and System.source.