Terraria: System.Xml.Xsl.XmlQueryType.HasIntersectionItemType
HasIntersectionItemType()
bool System.Xml.Xsl.XmlQueryType.HasIntersectionItemType (XmlQueryType other) inline private inherited
Definition at line 487 of file XmlQueryType.cs.
    {
        if (TypeCode == other.TypeCode && (NodeKinds & (XmlNodeKindFlags.Document | XmlNodeKindFlags.Element | XmlNodeKindFlags.Attribute)) != 0)
        {
            if (TypeCode == XmlTypeCode.Node)
            {
                return true;
            }
            if (!NameTest.HasIntersection(other.NameTest))
            {
                return false;
            }
            if (!XmlSchemaType.IsDerivedFrom(SchemaType, other.SchemaType, XmlSchemaDerivationMethod.Empty) && !XmlSchemaType.IsDerivedFrom(other.SchemaType, SchemaType, XmlSchemaDerivationMethod.Empty))
            {
                return false;
            }
            return true;
        }
        if (IsSubtypeOf(other) || other.IsSubtypeOf(this))
        {
            return true;
        }
        return false;
    }
References System.Xml.Xsl.XmlQualifiedNameTest.HasIntersection(), System.Xml.Schema.XmlSchemaType.IsDerivedFrom(), System.Xml.Xsl.XmlQueryType.IsSubtypeOf(), System.Xml.Xsl.XmlQueryType.NameTest, System.Xml.Xsl.XmlQueryType.NodeKinds, and System.other.