Terraria: System.Xml.Xsl.XmlQueryType.Equals
Equals() [2/2]
bool System.Xml.Xsl.XmlQueryType.Equals ([NotNullWhen(true)] XmlQueryType that) inline inherited
Definition at line 283 of file XmlQueryType.cs.
    {
        if (that == null)
        {
            return false;
        }
        if (Cardinality != that.Cardinality || IsDod != that.IsDod)
        {
            return false;
        }
        XmlQueryType prime = Prime;
        XmlQueryType prime2 = that.Prime;
        if ((object)prime == prime2)
        {
            return true;
        }
        if (prime.Count != prime2.Count)
        {
            return false;
        }
        if (prime.Count == 1)
        {
            if (prime.TypeCode == prime2.TypeCode && prime.NameTest == prime2.NameTest && prime.SchemaType == prime2.SchemaType && prime.IsStrict == prime2.IsStrict)
            {
                return prime.IsNotRtf == prime2.IsNotRtf;
            }
            return false;
        }
        using (IListEnumerator<XmlQueryType> listEnumerator = GetEnumerator())
        {
            while (listEnumerator.MoveNext())
            {
                XmlQueryType current = listEnumerator.Current;
                bool flag = false;
                foreach (XmlQueryType item in that)
                {
                    if (current.TypeCode == item.TypeCode && current.NameTest == item.NameTest && current.SchemaType == item.SchemaType && current.IsStrict == item.IsStrict && current.IsNotRtf == item.IsNotRtf)
                    {
                        flag = true;
                        break;
                    }
                }
                if (!flag)
                {
                    return false;
                }
            }
        }
        return true;
    }
References System.Xml.Xsl.XmlQueryType.Cardinality, System.Xml.Dictionary, System.Xml.Xsl.ListBase< XmlQueryType >.GetEnumerator(), System.Xml.Xsl.XmlQueryType.IsDod, System.Xml.Xsl.XmlQueryType.IsNotRtf, System.item, and System.Xml.Xsl.XmlQueryType.Prime.
Referenced by System.Xml.Xsl.XmlQueryType.Equals(), System.Xml.Xsl.XmlQueryType.operator!=(), and System.Xml.Xsl.XmlQueryType.operator==().