Terraria: ChatManager.ParseMessage
ParseMessage()
static List<TextSnippet> ChatManager.ParseMessage (string text, Color baseColor) inline static
     {
         text = text.Replace("\r", "");
         MatchCollection matchCollection = Regexes.Format.Matches(text);
         List<TextSnippet> list = new List<TextSnippet>();
         int num = 0;
         foreach (Match item in matchCollection)
         {
             if (item.Index > num)
             {
                 list.Add(new TextSnippet(text.Substring(num, item.Index - num), baseColor));
             }
             num = item.Index + item.Length;
             string value = item.Groups["tag"].Value;
             string value2 = item.Groups["text"].Value;
             string value3 = item.Groups["options"].Value;
             ITagHandler handler = GetHandler(value);
             if (handler != null)
             {
                 list.Add(handler.Parse(value2, baseColor, value3));
                 list[list.Count - 1].TextOriginal = item.ToString();
             }
             else
             {
                 list.Add(new TextSnippet(value2, baseColor));
             }
         }
         if (text.Length > num)
         {
             list.Add(new TextSnippet(text.Substring(num, text.Length - num), baseColor));
         }
         return list;
     }
References ChatManager.Regexes.Format, GetHandler(), and ITagHandler.Parse().
Referenced by DrawColorCodedStringWithShadow(), Main.DrawNetplayStatusText(), Main.DrawPlayerChat(), UIText.DrawSelf(), Main.GetInputText(), GetStringSize(), Player.OverheadMessage.NewMessage(), LegacyChatMonitor.NewTextInternal(), and Utils.WordwrapStringSmart().