Terraria: ChatManager.DrawColorCodedStringWithShadow
DrawColorCodedStringWithShadow() [3/3]
static Vector2 ChatManager.DrawColorCodedStringWithShadow (SpriteBatch spriteBatch, DynamicSpriteFont font, TextSnippet[] snippets, Vector2 position, float rotation, Vector2 origin, Vector2 baseScale, out int hoveredSnippet, float maxWidth = -1f, float spread = 2f) inline static
References Color, DrawColorCodedString(), and DrawColorCodedStringShadow().
Referenced by GameTipsDisplay.Draw(), LegacyMultiplayerClosePlayersOverlay.Draw(), CaptureInterface.ModeChangeSettings.Draw(), ItemSlot.Draw(), Utils.DrawBorderString(), ChestUI.DrawButton(), CaptureInterface.DrawCameraLock(), LegacyChatMonitor.DrawChat(), RemadeChatMonitor.DrawChat(), Main.DrawDefenseCounter(), Main.DrawGamepadInstructions(), Main.DrawInterface_14_EntityHealthBars(), Main.DrawInventory(), ChestUI.DrawName(), Main.DrawNetplayStatusText(), Main.DrawPlayerChat(), Main.DrawPlayerChatBubbles(), NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawPlayerName(), UIAchievementListItem.DrawSelf(), UIKeybindingListItem.DrawSelf(), UIKeybindingSimpleListItem.DrawSelf(), UIKeybindingSliderItem.DrawSelf(), UIKeybindingToggleListItem.DrawSelf(), Main.GUIChatDrawInner(), Main.MouseText_DrawItemTooltip(), and Main.MouseTextInner().