Terraria: System.Xml.Xsl.XmlQueryType.ItemTypeToString
ItemTypeToString()
string System.Xml.Xsl.XmlQueryType.ItemTypeToString (bool isXQ) inline private inherited
Definition at line 512 of file XmlQueryType.cs.
    {
        string text;
        if (!IsNode)
        {
            text = ((SchemaType == XmlSchemaComplexType.AnyType) ? s_typeNames[(int)TypeCode] : ((!SchemaType.QualifiedName.IsEmpty) ? QNameToString(SchemaType.QualifiedName) : ("<:" + s_typeNames[(int)TypeCode])));
        }
        else
        {
            text = s_typeNames[(int)TypeCode];
            XmlTypeCode typeCode = TypeCode;
            if (typeCode != XmlTypeCode.Document)
            {
                if ((uint)(typeCode - 4) <= 1u)
                {
                    goto IL_0048;
                }
            }
            else
            {
                if (!isXQ)
                {
                    goto IL_0048;
                }
                text = text + "{(element" + NameAndType(isXQ: true) + "?&text?&comment?&processing-instruction?)*}";
            }
        }
        goto IL_00b0;
        IL_00b0:
        if (!isXQ && IsStrict)
        {
            text += "=";
        }
        return text;
        IL_0048:
        text += NameAndType(isXQ);
        goto IL_00b0;
    }
References System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Dictionary, System.Xml.Xsl.XmlQueryType.IsNode, System.Xml.Xsl.XmlQueryType.IsStrict, System.Xml.Xsl.XmlQueryType.NameAndType(), System.Xml.Xsl.XmlQueryType.QNameToString(), System.Xml.Xsl.XmlQueryType.s_typeNames, System.text, and System.Xml.Xsl.XmlQueryType.TypeCode.
Referenced by System.Xml.Xsl.XmlQueryType.ToString().