Terraria: ChatManager.DrawColorCodedStringWithShadow
DrawColorCodedStringWithShadow() [1/3]
static Vector2 ChatManager.DrawColorCodedStringWithShadow (SpriteBatch spriteBatch, DynamicSpriteFont font, string text, Vector2 position, Color baseColor, float rotation, Vector2 origin, Vector2 baseScale, float maxWidth = -1f, float spread = 2f) inline static
     {
         TextSnippet[] snippets = ParseMessage(text, baseColor).ToArray();
         ConvertNormalSnippets(snippets);
         DrawColorCodedStringShadow(spriteBatch, font, snippets, position, new Color(0, 0, 0, baseColor.A), rotation, origin, baseScale, maxWidth, spread);
         int hoveredSnippet;
         return DrawColorCodedString(spriteBatch, font, snippets, position, Color.White, rotation, origin, baseScale, out hoveredSnippet, maxWidth);
     }
References Color, ConvertNormalSnippets(), DrawColorCodedString(), DrawColorCodedStringShadow(), and ParseMessage().