Terraria: System.Xml.Xsl.XmlQueryType.IsSubtypeOfItemType
IsSubtypeOfItemType()
bool System.Xml.Xsl.XmlQueryType.IsSubtypeOfItemType (XmlQueryType baseType) inline private inherited
Definition at line 452 of file XmlQueryType.cs.
    {
        XmlSchemaType schemaType = baseType.SchemaType;
        if (TypeCode != baseType.TypeCode)
        {
            if (baseType.IsStrict)
            {
                return false;
            }
            XmlSchemaType builtInSimpleType = XmlSchemaType.GetBuiltInSimpleType(baseType.TypeCode);
            if (builtInSimpleType != null && schemaType != builtInSimpleType)
            {
                return false;
            }
            return s_typeCodeDerivation[TypeCode, baseType.TypeCode];
        }
        if (baseType.IsStrict)
        {
            if (IsStrict)
            {
                return SchemaType == schemaType;
            }
            return false;
        }
        if ((IsNotRtf || !baseType.IsNotRtf) && NameTest.IsSubsetOf(baseType.NameTest) && (schemaType == XmlSchemaComplexType.AnyType || XmlSchemaType.IsDerivedFrom(SchemaType, schemaType, XmlSchemaDerivationMethod.Empty)))
        {
            if (IsNillable)
            {
                return baseType.IsNillable;
            }
            return true;
        }
        return false;
    }
References System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaType.GetBuiltInSimpleType(), System.Xml.Schema.XmlSchemaType.IsDerivedFrom(), System.Xml.Xsl.XmlQueryType.IsNillable, System.Xml.Xsl.XmlQueryType.IsNotRtf, System.Xml.Xsl.XmlQueryType.IsStrict, System.Xml.Xsl.XmlQualifiedNameTest.IsSubsetOf(), System.Xml.Xsl.XmlQueryType.NameTest, System.Xml.Xsl.XmlQueryType.s_typeCodeDerivation, and System.Xml.Xsl.XmlQueryType.TypeCode.
Referenced by System.Xml.Xsl.XmlQueryType.IsSubtypeOf().