Terraria: System.Xml.Xsl.XmlQueryType.ToString
ToString() [2/2]
string System.Xml.Xsl.XmlQueryType.ToString (string format) inline inherited
Definition at line 384 of file XmlQueryType.cs.
    {
        StringBuilder stringBuilder;
        if (format == "S")
        {
            stringBuilder = new StringBuilder();
            stringBuilder.Append(Cardinality.ToString(format));
            stringBuilder.Append(';');
            for (int i = 0; i < Count; i++)
            {
                if (i != 0)
                {
                    stringBuilder.Append('|');
                }
                stringBuilder.Append(this[i].TypeCode.ToString());
            }
            stringBuilder.Append(';');
            stringBuilder.Append(IsStrict);
            return stringBuilder.ToString();
        }
        bool flag = format == "X";
        if (Cardinality == XmlQueryCardinality.None)
        {
            return "none";
        }
        if (Cardinality == XmlQueryCardinality.Zero)
        {
            return "empty";
        }
        stringBuilder = new StringBuilder();
        switch (Count)
        {
        case 0:
            stringBuilder.Append("none");
            break;
        case 1:
            stringBuilder.Append(this[0].ItemTypeToString(flag));
            break;
        default:
        {
            string[] array = new string[Count];
            for (int j = 0; j < Count; j++)
            {
                array[j] = this[j].ItemTypeToString(flag);
            }
            Array.Sort(array);
            stringBuilder = new StringBuilder();
            stringBuilder.Append('(');
            stringBuilder.Append(array[0]);
            for (int k = 1; k < array.Length; k++)
            {
                stringBuilder.Append(" | ");
                stringBuilder.Append(array[k]);
            }
            stringBuilder.Append(')');
            break;
        }
        }
        stringBuilder.Append(Cardinality.ToString());
        if (!flag && IsDod)
        {
            stringBuilder.Append('#');
        }
        return stringBuilder.ToString();
    }
References System.array, System.Xml.Xsl.XmlQueryType.Cardinality, System.Xml.Xsl.ListBase< XmlQueryType >.Count, System.Xml.Dictionary, System.format, System.Xml.Xsl.XmlQueryType.IsDod, System.Xml.Xsl.XmlQueryType.IsStrict, System.Xml.Xsl.XmlQueryType.ItemTypeToString(), System.Xml.Xsl.XmlQueryCardinality.None, System.Array.Sort(), System.Xml.Xsl.XmlQueryCardinality.ToString(), and System.Xml.Xsl.XmlQueryCardinality.Zero.