Terraria: System.Xml.XmlDictionaryAsyncCheckWriter.SetLastTask
SetLastTask()
Task System.Xml.XmlDictionaryAsyncCheckWriter.SetLastTask (Task task) inline private
Definition at line 74 of file XmlDictionaryAsyncCheckWriter.cs.
    {
        _lastTask = task;
        return task;
    }
References System.Xml.XmlDictionaryAsyncCheckWriter._lastTask, and System.task.
Referenced by System.Xml.XmlDictionaryAsyncCheckWriter.FlushAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteAttributesAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteBase64Async(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteBinHexAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteCDataAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteCharEntityAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteCharsAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteCommentAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteDocTypeAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteEndDocumentAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteEndElementAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteEntityRefAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteFullEndElementAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteNameAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteNmTokenAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteNodeAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteProcessingInstructionAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteQualifiedNameAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteRawAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteRawAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteStartDocumentAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteStartDocumentAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteStartElementAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteStringAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteSurrogateCharEntityAsync(), and System.Xml.XmlDictionaryAsyncCheckWriter.WriteWhitespaceAsync().