Terraria: System.Xml.XmlDictionaryAsyncCheckWriter.WriteCharsAsync
WriteCharsAsync()
override Task System.Xml.XmlDictionaryAsyncCheckWriter.WriteCharsAsync (char[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 164 of file XmlDictionaryAsyncCheckWriter.cs.
    {
        CheckAsync();
        return SetLastTask(CoreWriter.WriteCharsAsync(buffer, index, count));
    }
References System.buffer, System.Xml.XmlDictionaryAsyncCheckWriter.CheckAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.CoreWriter, System.count, System.index, System.Xml.XmlDictionaryAsyncCheckWriter.SetLastTask(), and System.Xml.XmlWriter.WriteCharsAsync().