Terraria: Terraria.WorldBuilding.Modifiers.NotInShape.Apply
Apply()
override bool Terraria.WorldBuilding.Modifiers.NotInShape.Apply (Point origin, int x, int y, params object[] args) inline
Definition at line 182 of file Modifiers.cs.
        {
            if (_shapeData.Contains(x - origin.X, y - origin.Y))
            {
                return Fail();
            }
            return UnitApply(origin, x, y, args);
        }
References Terraria.WorldBuilding.Modifiers.NotInShape._shapeData, Terraria.WorldBuilding.ShapeData.Contains(), Terraria.WorldBuilding.GenAction.Fail(), Terraria.WorldBuilding.GenAction.UnitApply(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.