Terraria: System.Xml.XmlDictionaryAsyncCheckWriter.WriteNmTokenAsync
WriteNmTokenAsync()
override Task System.Xml.XmlDictionaryAsyncCheckWriter.WriteNmTokenAsync (string name) inline virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 266 of file XmlDictionaryAsyncCheckWriter.cs.
    {
        CheckAsync();
        return SetLastTask(CoreWriter.WriteNmTokenAsync(name));
    }
References System.Xml.XmlDictionaryAsyncCheckWriter.CheckAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.CoreWriter, System.Xml.XmlDictionaryAsyncCheckWriter.SetLastTask(), and System.Xml.XmlWriter.WriteNmTokenAsync().