Terraria: System.Collections.Generic.Stack.Push
Push()
void System.Collections.Generic.Stack< T >.Push (T item) inline
Definition at line 294 of file Stack.cs.
    {
        int size = _size;
        T[] array = _array;
        if ((uint)size < (uint)array.Length)
        {
            array[size] = item;
            _version++;
            _size = size + 1;
        }
        else
        {
            PushWithResize(item);
        }
    }
References System.Collections.Generic.Stack< T >._array, System.Collections.Generic.Stack< T >._size, System.Collections.Generic.Stack< T >._version, System.array, System.item, and System.Collections.Generic.Stack< T >.PushWithResize().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.AddVariable(), System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.CodeGenerator.AndIf(), System.Runtime.Serialization.CodeGenerator.BeginWhileBody(), System.Runtime.Serialization.CodeGenerator.BeginWhileCondition(), System.Text.RegularExpressions.RegexCompiler.RentedLocalBuilder.Dispose(), System.Runtime.Serialization.CodeGenerator.Else(), System.Xml.Serialization.CodeGenerator.Else(), System.Runtime.Serialization.CodeGenerator.ElseIf(), System.Runtime.Serialization.CodeGenerator.ElseIfIsEmptyString(), System.Runtime.Serialization.CodeGenerator.For(), System.Xml.Serialization.CodeGenerator.For(), System.Runtime.Serialization.CodeGenerator.ForEach(), System.Runtime.Serialization.CodeGenerator.If(), System.Xml.Serialization.CodeGenerator.If(), System.Runtime.Serialization.CodeGenerator.InternalIf(), System.Xml.Serialization.CodeGenerator.InternalIf(), System.Xml.Xsl.Runtime.XmlQueryOutput.PushElementNames(), System.Xml.Xsl.XPath.XPathParser< Node >.PushPosInfo(), System.Runtime.Serialization.CodeGenerator.Switch(), System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitBlock(), System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitBlock(), System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitCatchBlock(), System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitCatchBlock(), System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitLambda< T >(), System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitLambda< T >(), and System.Xml.Xsl.Xslt.InvokeGenerator.VisitReference().