Terraria: System.Collections.Generic.Stack.Peek
Peek()
T System.Collections.Generic.Stack< T >.Peek () inline
Definition at line 233 of file Stack.cs.
    {
        int num = _size - 1;
        T[] array = _array;
        if ((uint)num >= (uint)array.Length)
        {
            ThrowForEmptyStack();
        }
        return array[num];
    }
References System.Collections.Generic.Stack< T >._array, System.Collections.Generic.Stack< T >._size, System.array, and System.Collections.Generic.Stack< T >.ThrowForEmptyStack().
Referenced by System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.CodeGenerator.AndIf(), and System.Runtime.Serialization.CodeGenerator.EndCase().