Terraria: System.Collections.Generic.Stack.Pop
Pop()
T System.Collections.Generic.Stack< T >.Pop () inline
Definition at line 257 of file Stack.cs.
    {
        int num = _size - 1;
        T[] array = _array;
        if ((uint)num >= (uint)array.Length)
        {
            ThrowForEmptyStack();
        }
        _version++;
        _size = num;
        T result = array[num];
        if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
        {
            array[num] = default(T);
        }
        return result;
    }
References System.Collections.Generic.Stack< T >._array, System.Collections.Generic.Stack< T >._size, System.Collections.Generic.Stack< T >._version, System.array, and System.Collections.Generic.Stack< T >.ThrowForEmptyStack().
Referenced by System.Runtime.Serialization.CodeGenerator.BeginWhileBody(), System.Runtime.Serialization.CodeGenerator.ElseIf(), System.Runtime.Serialization.CodeGenerator.ElseIfIsEmptyString(), System.Runtime.Serialization.CodeGenerator.EndFor(), System.Xml.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.EndForEach(), System.Runtime.Serialization.CodeGenerator.EndSwitch(), System.Runtime.Serialization.CodeGenerator.EndWhile(), System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.FinishVariables(), System.Xml.Xsl.Xslt.InvokeGenerator.GenerateInvoke(), System.Xml.Serialization.CodeGenerator.InitElseIf(), System.Xml.Xsl.Runtime.XmlQueryOutput.PopElementNames(), System.Runtime.Serialization.CodeGenerator.PopIfState(), System.Xml.Serialization.CodeGenerator.PopIfState(), System.Xml.Xsl.XPath.XPathParser< Node >.PopPosInfo(), System.Xml.Xsl.XPath.XPathParser< Node >.PopPosInfo(), System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitBlock(), System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitBlock(), System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitCatchBlock(), System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitCatchBlock(), System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitLambda< T >(), and System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitLambda< T >().