Terraria: ItemSorting.SortInventory
SortInventory()
static void ItemSorting.SortInventory () inline static
     {
         if (!Main.LocalPlayer.HasItem(905))
         {
             SortCoins();
         }
         SortAmmo();
         Sort(Main.player[Main.myPlayer].inventory, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 50, 51, 52, 53, 54, 55, 56, 57, 58);
     }
References Player.HasItem(), Player.inventory, Main.LocalPlayer, Main.myPlayer, Main.player, Sort(), SortAmmo(), and SortCoins().
Referenced by Main.DrawInventory().