Terraria: NPCUtils.TargetClosestDownwindFromNPC
TargetClosestDownwindFromNPC()
static void NPCUtils.TargetClosestDownwindFromNPC (NPC searcher, float distanceMaxX, bool faceTarget = true, Vector2? checkPosition = null) inline static
     {
         TargetSearchResults searchResults = SearchForTarget(searcher, TargetSearchFlag.Players, SearchFilters.DownwindFromNPC(searcher, distanceMaxX));
         if (searchResults.FoundTarget)
         {
             searcher.target = searchResults.NearestTargetIndex;
             searcher.targetRect = searchResults.NearestTargetHitbox;
             if (searcher.ShouldFaceTarget(ref searchResults) && faceTarget)
             {
                 searcher.FaceTarget();
             }
         }
     }
References NPCUtils.SearchFilters.DownwindFromNPC(), NPC.FaceTarget(), NPCUtils.TargetSearchResults.FoundTarget, NPCUtils.TargetSearchResults.NearestTargetHitbox, NPCUtils.TargetSearchResults.NearestTargetIndex, SearchForTarget(), NPC.ShouldFaceTarget(), NPC.target, and NPC.targetRect.
Referenced by NPC.AI_119_Dandelion().