Terraria: System.Threading.Monitor.Enter
Enter() [1/2]
static void System.Threading.Monitor.Enter (object obj)
Referenced by System.Transactions.EnlistmentStatePromoted.Aborted(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AcquireLocks(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Terraria.Graphics.Capture.CaptureCamera.Capture(), System.Net.WebSockets.WebSocketBase.CloseAsyncCore(), System.Transactions.EnlistmentStatePromoted.Committed(), System.Xml.Schema.XmlSchemaSet.Compile(), System.Transactions.TransactionStatePromotedBase.CompleteAbortingClone(), System.Transactions.TransactionStatePromotedBase.CompleteBlockingClone(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.Contains(), Microsoft.Xna.Framework.Graphics.DeclarationManager.CreateBinding(), Terraria.Graphics.Capture.CaptureCamera.Dispose(), Terraria.Graphics.Capture.CaptureCamera.DrawTick(), Microsoft.Xna.Framework.Graphics.EffectPass.EndPass(), System.Transactions.TransactionStatePromotedBase.EnlistDurable(), System.Transactions.TransactionStatePromotedBase.EnlistDurable(), System.Transactions.EnlistmentStatePromoted.EnlistmentDone(), System.Transactions.TransactionStatePromotedBase.EnlistVolatile(), System.Transactions.TransactionStatePromotedBase.EnlistVolatile(), System.Transactions.DurableEnlistmentAborting.EnterState(), System.Transactions.DurableEnlistmentCommitting.EnterState(), System.Transactions.VolatileEnlistmentAborting.EnterState(), System.Transactions.VolatileEnlistmentCommitting.EnterState(), System.Transactions.VolatileEnlistmentInDoubt.EnterState(), System.Transactions.VolatileEnlistmentPreparing.EnterState(), System.Transactions.VolatileEnlistmentSPC.EnterState(), System.Transactions.TransactionStateDelegatedAborting.EnterState(), System.Transactions.TransactionStateDelegatedCommitting.EnterState(), System.Transactions.TransactionStatePromotedP0Aborting.EnterState(), System.Transactions.CheapUnfairReaderWriterLock.EnterWriteLock(), System.Xml.Schema.Preprocessor.Execute(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.FindResourceW(), System.Transactions.EnlistmentStatePromoted.ForceRollback(), System.Collections.Concurrent.ConcurrentBag< T >.FreezeBag(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.GetCachedName(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.GetCachedObject(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.GetCachedTag(), System.RuntimeType.RuntimeTypeCache.GetGenericMethodInfo(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.IncrementRefCount(), System.Transactions.EnlistmentStatePromoted.InDoubt(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.Insert(), System.SR.InternalGetResourceString(), System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue.LocalPush(), System.Net.WebSockets.WebSocketBase.OnKeepAlive(), System.Transactions.EnlistmentStatePromoted.Prepared(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process(), System.Transactions.EnlistmentStatePromoted.RecoveryInformation(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.RecreateResources(), Microsoft.Xna.Framework.WindowsManagedCallbackHandler.RegisterNativeToManagedCallbackImpl(), Microsoft.Xna.Framework.Graphics.DeclarationManager.ReleaseAllDeclarations(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllDefaultPoolResources(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllDeviceResources(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllReferences(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAutomaticResources(), Microsoft.Xna.Framework.Graphics.DeclarationManager.ReleaseBinding(), Microsoft.Xna.Framework.Graphics.Effect.ReleaseNativeObject(), System.Net.WebSockets.WebSocketBase.ResetFlagAndTakeLock(), System.Transactions.TransactionStatePromotedBase.Rollback(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.SetCachedName(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.SetCachedTag(), Microsoft.Xna.Framework.WindowsManagedCallbackHandler.SetProxyProcessHandler(), Microsoft.Xna.Framework.Graphics.DeclarationManager.SetVertexDeclaration(), Microsoft.Xna.Framework.Graphics.DeclarationManager.SetVertexDeclaration(), System.Transactions.InternalTransaction.SignalAsyncCompletion(), System.Net.WebSockets.WebSocketBase.StartOnCloseReceived(), Terraria.Social.Steam.CoreSocialModule.SteamCallbackLoop(), Terraria.Social.Steam.CoreSocialModule.SteamTickLoop(), System.Net.WebSockets.WebSocketBase.TakeLocks(), Terraria.Social.WeGame.CoreSocialModule.TickThread(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryAddInternal(), System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue.TryLocalPop(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.LockedStack.TryPop(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.LockedStack.TryPush(), System.Threading.Channels.BoundedChannel< T >.BoundedChannelWriter.TryWrite(), System.Threading.SemaphoreSlim.Wait(), Microsoft.Xna.Framework.WindowsManagedCallbackHandler.WaitForAsyncOperationToFinish(), and System.Threading.Channels.BoundedChannel< T >.BoundedChannelWriter.WriteAsync().