Terraria: Interop.Crypt32.FindOidInfo
FindOidInfo() [5/5]
static CRYPT_OID_INFO Interop.Crypt32.FindOidInfo (CryptOidInfoKeyType keyType, string key, OidGroup group, bool fallBackToAllGroups) inline static package
Definition at line 318 of file Interop.cs.
        {
            IntPtr intPtr = IntPtr.Zero;
            try
            {
                intPtr = keyType switch
                {
                    CryptOidInfoKeyType.CRYPT_OID_INFO_OID_KEY => Marshal.StringToCoTaskMemAnsi(key),
                    CryptOidInfoKeyType.CRYPT_OID_INFO_NAME_KEY => Marshal.StringToCoTaskMemUni(key),
                    _ => throw new NotSupportedException(),
                };
                if (!OidGroupWillNotUseActiveDirectory(group))
                {
                    OidGroup group2 = group | (OidGroup)(-2147483648);
                    IntPtr intPtr2 = CryptFindOIDInfo(keyType, intPtr, group2);
                    if (intPtr2 != IntPtr.Zero)
                    {
                        return Marshal.PtrToStructure<CRYPT_OID_INFO>(intPtr2);
                    }
                }
                IntPtr intPtr3 = CryptFindOIDInfo(keyType, intPtr, group);
                if (intPtr3 != IntPtr.Zero)
                {
                    return Marshal.PtrToStructure<CRYPT_OID_INFO>(intPtr3);
                }
                if (fallBackToAllGroups && group != 0)
                {
                    IntPtr intPtr4 = CryptFindOIDInfo(keyType, intPtr, OidGroup.All);
                    if (intPtr4 != IntPtr.Zero)
                    {
                        return Marshal.PtrToStructure<CRYPT_OID_INFO>(intPtr4);
                    }
                }
                CRYPT_OID_INFO result = default(CRYPT_OID_INFO);
                result.AlgId = -1;
                return result;
            }
            finally
            {
                if (intPtr != IntPtr.Zero)
                {
                    Marshal.FreeCoTaskMem(intPtr);
                }
            }
        }
References Interop.Crypt32.CryptFindOIDInfo(), System.Runtime.InteropServices.Marshal.FreeCoTaskMem(), System.key, Interop.Crypt32.OidGroupWillNotUseActiveDirectory(), System.Runtime.InteropServices.Marshal.PtrToStructure(), System.Runtime.InteropServices.Marshal.StringToCoTaskMemAnsi(), System.Runtime.InteropServices.Marshal.StringToCoTaskMemUni(), and System.IntPtr.Zero.