Terraria: Terraria.Netplay.GetLocalIPAddress
GetLocalIPAddress()
static string Terraria.Netplay.GetLocalIPAddress () inline static private
Definition at line 84 of file Netplay.cs.
    {
        string result = "";
        IPAddress[] addressList = Dns.GetHostEntry(Dns.GetHostName()).AddressList;
        foreach (IPAddress iPAddress in addressList)
        {
            if (AcceptedFamilyType(iPAddress.AddressFamily))
            {
                result = iPAddress.ToString();
                break;
            }
        }
        return result;
    }
References Terraria.Netplay.AcceptedFamilyType(), System.Net.IPAddress.AddressFamily, System.Net.Dns.GetHostEntry(), System.Net.Dns.GetHostName(), and System.Net.IPAddress.ToString().