Terraria: Terraria.Netplay.TcpClientLoop
TcpClientLoop()
static void Terraria.Netplay.TcpClientLoop () inline static
    {
        ClientLoopSetup(new TcpAddress(ServerIP, ListenPort));
        Main.menuMode = 14;
        bool flag = true;
        while (flag)
        {
            flag = false;
            try
            {
                Connection.Socket.Connect(new TcpAddress(ServerIP, ListenPort));
                flag = false;
            }
            catch
            {
                if (Platform.IsOSX)
                {
                    Thread.Sleep(200);
                    Connection.Socket.Close();
                    Connection.Socket = new TcpSocket();
                }
                if (!Disconnect && Main.gameMenu)
                {
                    flag = true;
                }
            }
        }
        InnerClientLoop();
    }
References Terraria.Netplay.ClientLoopSetup(), Terraria.Net.Sockets.ISocket.Close(), Terraria.Net.Sockets.ISocket.Connect(), Terraria.Netplay.Connection, Terraria.Netplay.Disconnect, Terraria.Main.gameMenu, Terraria.Netplay.InnerClientLoop(), ReLogic.OS.Platform.IsOSX, Terraria.Netplay.ListenPort, Terraria.Netplay.ServerIP, and Terraria.RemoteServer.Socket.
Referenced by Terraria.Netplay.StartTcpClient().