Terraria: Terraria.Netplay.ServerLoop
ServerLoop()
static void Terraria.Netplay.ServerLoop () inline static private
Definition at line 287 of file Netplay.cs.
    {
        int num = 0;
        StartBroadCasting();
        while (!Disconnect)
        {
            StartListeningIfNeeded();
            UpdateConnectedClients();
            num = (num + 1) % 10;
            Thread.Sleep((num == 0) ? 1 : 0);
        }
        StopBroadCasting();
    }
References Terraria.Netplay.Disconnect, Terraria.Netplay.StartBroadCasting(), Terraria.Netplay.StartListeningIfNeeded(), Terraria.Netplay.StopBroadCasting(), and Terraria.Netplay.UpdateConnectedClients().
Referenced by Terraria.Netplay.StartServer().