Terraria: Terraria.Netplay.SocialClientLoop
SocialClientLoop()
static void Terraria.Netplay.SocialClientLoop (object threadContext) inline static
Definition at line 399 of file Netplay.cs.
    {
        ISocket socket = (ISocket)threadContext;
        ClientLoopSetup(socket.GetRemoteAddress());
        Connection.Socket = socket;
        InnerClientLoop();
    }
References Terraria.Netplay.ClientLoopSetup(), Terraria.Net.Sockets.ISocket.GetRemoteAddress(), and Terraria.Netplay.InnerClientLoop().
Referenced by Terraria.Netplay.StartSocialClient().