Terraria: Terraria.Netplay.KickClient
KickClient()
static void Terraria.Netplay.KickClient (ISocket client, NetworkText kickMessage) inline static private
    {
        BinaryWriter writer = fullBuffer.writer;
        if (writer == null)
        {
            fullBuffer.ResetWriter();
            writer = fullBuffer.writer;
        }
        writer.BaseStream.Position = 0L;
        long position = writer.BaseStream.Position;
        writer.BaseStream.Position += 2L;
        writer.Write((byte)2);
        kickMessage.Serialize(writer);
        if (Main.dedServ)
        {
            Console.WriteLine(Language.GetTextValue("CLI.ClientWasBooted", client.GetRemoteAddress().ToString(), kickMessage));
        }
        int num = (int)writer.BaseStream.Position;
        writer.BaseStream.Position = position;
        writer.Write((short)num);
        writer.BaseStream.Position = num;
        client.AsyncSend(fullBuffer.writeBuffer, 0, num, ServerFullWriteCallBack, client);
    }
References Terraria.Net.Sockets.ISocket.AsyncSend(), Terraria.Main.dedServ, Terraria.Netplay.fullBuffer, Terraria.Net.Sockets.ISocket.GetRemoteAddress(), Terraria.Localization.Language.GetTextValue(), Terraria.MessageBuffer.ResetWriter(), Terraria.Localization.NetworkText.Serialize(), Terraria.Netplay.ServerFullWriteCallBack(), Terraria.MessageBuffer.writeBuffer, and Terraria.MessageBuffer.writer.
Referenced by Terraria.Netplay.OnConnectionAccepted().