Terraria: Terraria.Netplay.IsBanned
IsBanned()
static bool Terraria.Netplay.IsBanned (RemoteAddress address) inline static
Definition at line 126 of file Netplay.cs.
    {
        try
        {
            string identifier = address.GetIdentifier();
            if (File.Exists(BanFilePath))
            {
                using StreamReader streamReader = new StreamReader(BanFilePath);
                string text;
                while ((text = streamReader.ReadLine()) != null)
                {
                    if (text == identifier)
                    {
                        return true;
                    }
                }
            }
        }
        catch (Exception)
        {
        }
        return false;
    }
References Terraria.Netplay.BanFilePath, System.IO.File.Exists(), Terraria.Net.RemoteAddress.GetIdentifier(), and System.text.
Referenced by Terraria.MessageBuffer.GetData().