Terraria: Terraria.Netplay.UpdateConnectedClients
UpdateConnectedClients()
static void Terraria.Netplay.UpdateConnectedClients () inline static private
    {
        int num = 0;
        for (int i = 0; i < 256; i++)
        {
            if (Clients[i].PendingTermination)
            {
                if (Clients[i].PendingTerminationApproved)
                {
                    Clients[i].Reset();
                    NetMessage.SyncDisconnectedPlayer(i);
                }
                continue;
            }
            if (Clients[i].IsConnected())
            {
                Clients[i].Update();
                num++;
                continue;
            }
            if (Clients[i].IsActive)
            {
                Clients[i].PendingTermination = true;
                Clients[i].PendingTerminationApproved = true;
                continue;
            }
            Clients[i].StatusText2 = "";
            if (i < 255)
            {
                bool active = Main.player[i].active;
                Main.player[i].active = false;
                if (active)
                {
                    Player.Hooks.PlayerDisconnect(i);
                }
            }
        }
        HasClients = num != 0;
    }
References Terraria.Entity.active, Terraria.Netplay.Clients, Terraria.Netplay.HasClients, Terraria.RemoteClient.PendingTermination, Terraria.RemoteClient.PendingTerminationApproved, Terraria.Main.player, Terraria.Player.Hooks.PlayerDisconnect(), Terraria.RemoteClient.Reset(), Terraria.RemoteClient.StatusText2, Terraria.NetMessage.SyncDisconnectedPlayer(), and Terraria.RemoteClient.Update().
Referenced by Terraria.Netplay.ServerLoop().