Terraria: Terraria.Netplay.UpdateClientInMainThread
UpdateClientInMainThread()
static void Terraria.Netplay.UpdateClientInMainThread () inline static private
Definition at line 361 of file Netplay.cs.
    {
        if (Main.netMode == 1 && Connection.Socket.IsConnected() && !Connection.ServerWantsToRunCheckBytesInClientLoopThread && NetMessage.buffer[256].checkBytes)
        {
            NetMessage.CheckBytes();
        }
    }
References Terraria.NetMessage.buffer, Terraria.MessageBuffer.checkBytes, Terraria.NetMessage.CheckBytes(), Terraria.Netplay.Connection, Terraria.Net.Sockets.ISocket.IsConnected(), Terraria.Main.netMode, Terraria.RemoteServer.ServerWantsToRunCheckBytesInClientLoopThread, and Terraria.RemoteServer.Socket.
Referenced by Terraria.Netplay.UpdateInMainThread().