Terraria: TileDrawing.GetPalmTreeBiome
GetPalmTreeBiome()
int TileDrawing.GetPalmTreeBiome (int tileX, int tileY) inline private
     {
         int i;
         for (i = tileY; Main.tile[tileX, i].active() && Main.tile[tileX, i].type == 323; i++)
         {
         }
         return GetPalmTreeVariant(tileX, i);
     }
References Tile.active(), GetPalmTreeVariant(), Main.tile, and Tile.type.
Referenced by DrawTrees(), GetTileDrawData(), GetTileDrawTexture(), and PrepareForAreaDrawing().