Terraria: TileDrawing.DrawRisingVineStrip
DrawRisingVineStrip()
void TileDrawing.DrawRisingVineStrip (Vector2 screenPosition, Vector2 offSet, int x, int startY) inline private
     {
         int num = 0;
         int num2 = 0;
         Vector2 vector = new Vector2(x * 16 + 8, startY * 16 + 16 + 2);
         float amount = Math.Abs(Main.WindForVisuals) / 1.2f;
         amount = MathHelper.Lerp(0.2f, 1f, amount);
         float num3 = -0.08f * amount;
         float windCycle = GetWindCycle(x, startY, _vineWindCounter);
         float num4 = 0f;
         float num5 = 0f;
         for (int num6 = startY; num6 > 10; num6--)
         {
             Tile tile = Main.tile[x, num6];
             if (tile != null)
             {
                 ushort type = tile.type;
                 if (!tile.active() || !TileID.Sets.ReverseVineThreads[type])
                 {
                     break;
                 }
                 num++;
                 if (num2 >= 5)
                 {
                     num3 += 0.0075f * amount;
                 }
                 if (num2 >= 2)
                 {
                     num3 += 0.0025f;
                 }
                 if (WallID.Sets.AllowsWind[tile.wall] && (double)num6 < Main.worldSurface)
                 {
                     num2++;
                 }
                 float windGridPush = GetWindGridPush(x, num6, 40, -0.004f);
                 num4 = ((windGridPush != 0f || num5 == 0f) ? (num4 - windGridPush) : (num4 * -0.78f));
                 num5 = windGridPush;
                 short tileFrameX = tile.frameX;
                 short tileFrameY = tile.frameY;
                 Color color = Lighting.GetColor(x, num6);
                 GetTileDrawData(x, num6, tile, type, ref tileFrameX, ref tileFrameY, out var tileWidth, out var tileHeight, out var tileTop, out var halfBrickHeight, out var addFrX, out var addFrY, out var tileSpriteEffect, out var _, out var _, out var _);
                 Vector2 position = new Vector2(-(int)screenPosition.X, -(int)screenPosition.Y) + offSet + vector;
                 float num7 = (float)num2 * (0f - num3) * windCycle + num4;
                 Texture2D tileDrawTexture = GetTileDrawTexture(tile, x, num6);
                 if (tileDrawTexture == null)
                 {
                     break;
                 }
                 if (IsVisible(tile))
                 {
                     Main.spriteBatch.Draw(tileDrawTexture, position, new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), color, num7, new Vector2(tileWidth / 2, halfBrickHeight - tileTop + tileHeight), 1f, tileSpriteEffect, 0f);
                 }
                 vector += (num7 - (float)Math.PI / 2f).ToRotationVector2() * 16f;
             }
         }
     }
References _vineWindCounter, Tile.active(), WallID.Sets.AllowsWind, Color, Tile.frameX, Tile.frameY, Lighting.GetColor(), GetTileDrawData(), GetTileDrawTexture(), GetWindCycle(), GetWindGridPush(), IsVisible(), TileID.Sets.ReverseVineThreads, Main.spriteBatch, Main.tile, Tile.type, Tile.wall, Main.WindForVisuals, and Main.worldSurface.
Referenced by DrawReverseVines().