Terraria: TileDrawing.IsVisible
IsVisible()
bool TileDrawing.IsVisible (Tile tile) inline private
     {
         bool flag = tile.invisibleBlock();
         switch (tile.type)
         {
         case 19:
             if (tile.frameY / 18 == 48)
             {
                 flag = true;
             }
             break;
         case 541:
         case 631:
             flag = true;
             break;
         }
         if (flag)
         {
             return _shouldShowInvisibleBlocks;
         }
         return true;
     }
References _shouldShowInvisibleBlocks, Tile.frameY, Tile.invisibleBlock(), and Tile.type.
Referenced by DrawAnyDirectionalGrass(), DrawGrass(), DrawMultiTileGrassInWind(), DrawMultiTileVinesInWind(), DrawRisingVineStrip(), DrawSingleTile(), DrawTiles_EmitParticles(), and DrawVineStrip().