Terraria: TileDrawing.DrawTiles_GetLightOverride
DrawTiles_GetLightOverride()
Color TileDrawing.DrawTiles_GetLightOverride (int j, int i, Tile tileCache, ushort typeCache, short tileFrameX, short tileFrameY, Color tileLight) inline private
     {
         if (tileCache.fullbrightBlock())
         {
             return Color.White;
         }
         switch (typeCache)
         {
         case 541:
         case 631:
             return Color.White;
         case 19:
             if (tileFrameY / 18 == 48)
             {
                 return Color.White;
             }
             break;
         case 83:
         {
             int num = tileFrameX / 18;
             if (!IsAlchemyPlantHarvestable(num))
             {
                 break;
             }
             if (num == 5)
             {
                 tileLight.A = (byte)(Main.mouseTextColor / 2);
                 tileLight.G = Main.mouseTextColor;
                 tileLight.B = Main.mouseTextColor;
             }
             if (num == 6)
             {
                 byte b6 = (byte)((Main.mouseTextColor + tileLight.G * 2) / 3);
                 byte b7 = (byte)((Main.mouseTextColor + tileLight.B * 2) / 3);
                 if (b6 > tileLight.G)
                 {
                     tileLight.G = b6;
                 }
                 if (b7 > tileLight.B)
                 {
                     tileLight.B = b7;
                 }
             }
             break;
         }
         case 61:
             if (tileFrameX == 144)
             {
                 byte b2 = (tileLight.B = (byte)(245f - (float)(int)Main.mouseTextColor * 1.5f));
                 byte b4 = (tileLight.G = b2);
                 byte a = (tileLight.R = b4);
                 tileLight.A = a;
             }
             break;
         }
         return tileLight;
     }
References Color, Tile.fullbrightBlock(), IsAlchemyPlantHarvestable(), and Main.mouseTextColor.
Referenced by DrawAnyDirectionalGrass(), DrawGrass(), DrawMultiTileGrassInWind(), DrawMultiTileVinesInWind(), and DrawSingleTile().