Terraria: TileDrawing.DrawMultiTileVinesInWind
DrawMultiTileVinesInWind()
void TileDrawing.DrawMultiTileVinesInWind (Vector2 screenPosition, Vector2 offSet, int topLeftX, int topLeftY, int sizeX, int sizeY) inline private
     {
         float windCycle = GetWindCycle(topLeftX, topLeftY, _sunflowerWindCounter);
         float num = windCycle;
         int totalPushTime = 60;
         float pushForcePerFrame = 1.26f;
         float highestWindGridPushComplex = GetHighestWindGridPushComplex(topLeftX, topLeftY, sizeX, sizeY, totalPushTime, pushForcePerFrame, 3, swapLoopDir: true);
         windCycle += highestWindGridPushComplex;
         new Vector2((float)(sizeX * 16) * 0.5f, 0f);
         Vector2 vector = new Vector2((float)(topLeftX * 16 - (int)screenPosition.X) + (float)sizeX * 16f * 0.5f, topLeftY * 16 - (int)screenPosition.Y) + offSet;
         float num2 = 0.07f;
         Tile tile = Main.tile[topLeftX, topLeftY];
         int type = tile.type;
         Vector2 vector2 = new Vector2(0f, -2f);
         vector += vector2;
         bool flag = false;
         if ((type != 465 && (uint)(type - 591) > 1u) ? (sizeX == 1 && WorldGen.IsBelowANonHammeredPlatform(topLeftX, topLeftY)) : (WorldGen.IsBelowANonHammeredPlatform(topLeftX, topLeftY) && WorldGen.IsBelowANonHammeredPlatform(topLeftX + 1, topLeftY)))
         {
             vector.Y -= 8f;
             vector2.Y -= 8f;
         }
         Texture2D texture2D = null;
         Color color = Color.Transparent;
         float? num3 = null;
         float num4 = 1f;
         float num5 = -4f;
         bool flag2 = false;
         num2 = 0.15f;
         switch (type)
         {
         case 34:
         case 126:
             num3 = 1f;
             num5 = 0f;
             switch (tile.frameY / 54 + tile.frameX / 108 * 37)
             {
             case 9:
                 num3 = null;
                 num5 = -1f;
                 flag2 = true;
                 num2 *= 0.3f;
                 break;
             case 11:
                 num2 *= 0.5f;
                 break;
             case 12:
                 num3 = null;
                 num5 = -1f;
                 break;
             case 18:
                 num3 = null;
                 num5 = -1f;
                 break;
             case 21:
                 num3 = null;
                 num5 = -1f;
                 break;
             case 23:
                 num3 = 0f;
                 break;
             case 25:
                 num3 = null;
                 num5 = -1f;
                 flag2 = true;
                 break;
             case 32:
                 num2 *= 0.5f;
                 break;
             case 33:
                 num2 *= 0.5f;
                 break;
             case 35:
                 num3 = 0f;
                 break;
             case 36:
                 num3 = null;
                 num5 = -1f;
                 flag2 = true;
                 break;
             case 37:
                 num3 = null;
                 num5 = -1f;
                 flag2 = true;
                 num2 *= 0.5f;
                 break;
             case 39:
                 num3 = null;
                 num5 = -1f;
                 flag2 = true;
                 break;
             case 40:
             case 41:
             case 42:
             case 43:
                 num3 = null;
                 num5 = -2f;
                 flag2 = true;
                 num2 *= 0.5f;
                 break;
             case 44:
                 num3 = null;
                 num5 = -3f;
                 break;
             }
             break;
         case 42:
             num3 = 1f;
             num5 = 0f;
             switch (tile.frameY / 36)
             {
             case 0:
                 num3 = null;
                 num5 = -1f;
                 break;
             case 9:
                 num3 = 0f;
                 break;
             case 12:
                 num3 = null;
                 num5 = -1f;
                 break;
             case 14:
                 num3 = null;
                 num5 = -1f;
                 break;
             case 28:
                 num3 = null;
                 num5 = -1f;
                 break;
             case 30:
                 num3 = 0f;
                 break;
             case 32:
                 num3 = 0f;
                 break;
             case 33:
                 num3 = 0f;
                 break;
             case 34:
                 num3 = null;
                 num5 = -1f;
                 break;
             case 35:
                 num3 = 0f;
                 break;
             case 38:
                 num3 = null;
                 num5 = -1f;
                 break;
             case 39:
                 num3 = null;
                 num5 = -1f;
                 flag2 = true;
                 break;
             case 40:
             case 41:
             case 42:
             case 43:
                 num3 = 0f;
                 num3 = null;
                 num5 = -1f;
                 flag2 = true;
                 break;
             }
             break;
         case 95:
         case 270:
         case 271:
         case 444:
         case 454:
         case 572:
         case 581:
         case 660:
             num3 = 1f;
             num5 = 0f;
             break;
         case 591:
             num4 = 0.5f;
             num5 = -2f;
             break;
         case 592:
             num4 = 0.5f;
             num5 = -2f;
             texture2D = TextureAssets.GlowMask[294].Value;
             color = new Color(255, 255, 255, 0);
             break;
         }
         if (flag2)
         {
             vector += new Vector2(0f, 16f);
         }
         num2 *= -1f;
         if (!InAPlaceWithWind(topLeftX, topLeftY, sizeX, sizeY))
         {
             windCycle -= num;
         }
         ulong num6 = 0uL;
         for (int i = topLeftX; i < topLeftX + sizeX; i++)
         {
             for (int j = topLeftY; j < topLeftY + sizeY; j++)
             {
                 Tile tile2 = Main.tile[i, j];
                 ushort type2 = tile2.type;
                 if (type2 != type || !IsVisible(tile2))
                 {
                     continue;
                 }
                 Math.Abs(((float)(i - topLeftX) + 0.5f) / (float)sizeX - 0.5f);
                 short tileFrameX = tile2.frameX;
                 short tileFrameY = tile2.frameY;
                 float num7 = (float)(j - topLeftY + 1) / (float)sizeY;
                 if (num7 == 0f)
                 {
                     num7 = 0.1f;
                 }
                 if (num3.HasValue)
                 {
                     num7 = num3.Value;
                 }
                 if (flag2 && j == topLeftY)
                 {
                     num7 = 0f;
                 }
                 GetTileDrawData(i, j, tile2, type2, ref tileFrameX, ref tileFrameY, out var tileWidth, out var tileHeight, out var tileTop, out var halfBrickHeight, out var addFrX, out var addFrY, out var tileSpriteEffect, out var _, out var _, out var _);
                 bool flag3 = _rand.Next(4) == 0;
                 Color tileLight = Lighting.GetColor(i, j);
                 DrawAnimatedTile_AdjustForVisionChangers(i, j, tile2, type2, tileFrameX, tileFrameY, ref tileLight, flag3);
                 tileLight = DrawTiles_GetLightOverride(j, i, tile2, type2, tileFrameX, tileFrameY, tileLight);
                 if (_isActiveAndNotPaused && flag3)
                 {
                     DrawTiles_EmitParticles(j, i, tile2, type2, tileFrameX, tileFrameY, tileLight);
                 }
                 Vector2 vector3 = new Vector2(i * 16 - (int)screenPosition.X, j * 16 - (int)screenPosition.Y + tileTop) + offSet;
                 vector3 += vector2;
                 Vector2 vector4 = new Vector2(windCycle * num4, Math.Abs(windCycle) * num5 * num7);
                 Vector2 vector5 = vector - vector3;
                 Texture2D tileDrawTexture = GetTileDrawTexture(tile2, i, j);
                 if (tileDrawTexture != null)
                 {
                     Vector2 vector6 = vector + new Vector2(0f, vector4.Y);
                     Rectangle rectangle = new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight);
                     float rotation = windCycle * num2 * num7;
                     if (type2 == 660 && j == topLeftY + sizeY - 1)
                     {
                         Texture2D value = TextureAssets.Extra[260].Value;
                         _ = ((float)((i + j) % 200) * 0.11f + (float)Main.timeForVisualEffects / 360f) % 1f;
                         Color white = Color.White;
                         Main.spriteBatch.Draw(value, vector6, rectangle, white, rotation, vector5, 1f, tileSpriteEffect, 0f);
                     }
                     Main.spriteBatch.Draw(tileDrawTexture, vector6, rectangle, tileLight, rotation, vector5, 1f, tileSpriteEffect, 0f);
                     if (type2 == 660 && j == topLeftY + sizeY - 1)
                     {
                         Texture2D value2 = TextureAssets.Extra[260].Value;
                         Color color2 = Main.hslToRgb(((float)((i + j) % 200) * 0.11f + (float)Main.timeForVisualEffects / 360f) % 1f, 1f, 0.8f);
                         color2.A = 127;
                         Rectangle value3 = rectangle;
                         Vector2 position = vector6;
                         Vector2 origin = vector5;
                         Main.spriteBatch.Draw(value2, position, value3, color2, rotation, origin, 1f, tileSpriteEffect, 0f);
                     }
                     if (texture2D != null)
                     {
                         Main.spriteBatch.Draw(texture2D, vector6, rectangle, color, rotation, vector5, 1f, tileSpriteEffect, 0f);
                     }
                     TileFlameData tileFlameData = GetTileFlameData(i, j, type2, tileFrameY);
                     if (num6 == 0L)
                     {
                         num6 = tileFlameData.flameSeed;
                     }
                     tileFlameData.flameSeed = num6;
                     for (int k = 0; k < tileFlameData.flameCount; k++)
                     {
                         float x = (float)Utils.RandomInt(ref tileFlameData.flameSeed, tileFlameData.flameRangeXMin, tileFlameData.flameRangeXMax) * tileFlameData.flameRangeMultX;
                         float y = (float)Utils.RandomInt(ref tileFlameData.flameSeed, tileFlameData.flameRangeYMin, tileFlameData.flameRangeYMax) * tileFlameData.flameRangeMultY;
                         Main.spriteBatch.Draw(tileFlameData.flameTexture, vector6 + new Vector2(x, y), rectangle, tileFlameData.flameColor, rotation, vector5, 1f, tileSpriteEffect, 0f);
                     }
                 }
             }
         }
     }
References _isActiveAndNotPaused, _rand, _sunflowerWindCounter, Color, DrawAnimatedTile_AdjustForVisionChangers(), DrawTiles_EmitParticles(), DrawTiles_GetLightOverride(), TextureAssets.Extra, TileDrawing.TileFlameData.flameColor, TileDrawing.TileFlameData.flameCount, TileDrawing.TileFlameData.flameRangeMultX, TileDrawing.TileFlameData.flameRangeMultY, TileDrawing.TileFlameData.flameRangeXMax, TileDrawing.TileFlameData.flameRangeXMin, TileDrawing.TileFlameData.flameRangeYMax, TileDrawing.TileFlameData.flameRangeYMin, TileDrawing.TileFlameData.flameSeed, TileDrawing.TileFlameData.flameTexture, Tile.frameX, Tile.frameY, Lighting.GetColor(), GetHighestWindGridPushComplex(), GetTileDrawData(), GetTileDrawTexture(), GetTileFlameData(), GetWindCycle(), TextureAssets.GlowMask, Main.hslToRgb(), InAPlaceWithWind(), WorldGen.IsBelowANonHammeredPlatform(), IsVisible(), L, UnifiedRandom.Next(), Utils.RandomInt(), Main.spriteBatch, Main.tile, Main.timeForVisualEffects, Tile.type, and Asset< T >.Value.
Referenced by DrawMultiTileVines().