Terraria: TileDrawing.DrawAnimatedTile_AdjustForVisionChangers
DrawAnimatedTile_AdjustForVisionChangers()
void TileDrawing.DrawAnimatedTile_AdjustForVisionChangers (int i, int j, Tile tileCache, ushort typeCache, short tileFrameX, short tileFrameY, ref Color tileLight, bool canDoDust) inline private
     {
         if (_localPlayer.dangerSense && IsTileDangerous(_localPlayer, tileCache, typeCache))
         {
             if (tileLight.R < byte.MaxValue)
             {
                 tileLight.R = byte.MaxValue;
             }
             if (tileLight.G < 50)
             {
                 tileLight.G = 50;
             }
             if (tileLight.B < 50)
             {
                 tileLight.B = 50;
             }
             if (_isActiveAndNotPaused && canDoDust && _rand.Next(30) == 0)
             {
                 int num = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 60, 0f, 0f, 100, default(Color), 0.3f);
                 _dust[num].fadeIn = 1f;
                 _dust[num].velocity *= 0.1f;
                 _dust[num].noLight = true;
                 _dust[num].noGravity = true;
             }
         }
         if (_localPlayer.findTreasure && Main.IsTileSpelunkable(typeCache, tileFrameX, tileFrameY))
         {
             if (tileLight.R < 200)
             {
                 tileLight.R = 200;
             }
             if (tileLight.G < 170)
             {
                 tileLight.G = 170;
             }
             if (_isActiveAndNotPaused && _rand.Next(60) == 0 && canDoDust)
             {
                 int num2 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 204, 0f, 0f, 150, default(Color), 0.3f);
                 _dust[num2].fadeIn = 1f;
                 _dust[num2].velocity *= 0.1f;
                 _dust[num2].noLight = true;
             }
         }
         if (!_localPlayer.biomeSight)
         {
             return;
         }
         Color sightColor = Color.White;
         if (Main.IsTileBiomeSightable(typeCache, tileFrameX, tileFrameY, ref sightColor))
         {
             if (tileLight.R < sightColor.R)
             {
                 tileLight.R = sightColor.R;
             }
             if (tileLight.G < sightColor.G)
             {
                 tileLight.G = sightColor.G;
             }
             if (tileLight.B < sightColor.B)
             {
                 tileLight.B = sightColor.B;
             }
             if (_isActiveAndNotPaused && canDoDust && _rand.Next(480) == 0)
             {
                 Color newColor = sightColor;
                 int num3 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 267, 0f, 0f, 150, newColor, 0.3f);
                 _dust[num3].noGravity = true;
                 _dust[num3].fadeIn = 1f;
                 _dust[num3].velocity *= 0.1f;
                 _dust[num3].noLightEmittence = true;
             }
         }
     }
References _dust, _isActiveAndNotPaused, _localPlayer, _rand, Player.biomeSight, Color, Player.dangerSense, Dust.fadeIn, Player.findTreasure, Main.IsTileBiomeSightable(), IsTileDangerous(), Main.IsTileSpelunkable(), Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, and Dust.velocity.
Referenced by DrawAnyDirectionalGrass(), DrawGrass(), DrawMultiTileGrassInWind(), and DrawMultiTileVinesInWind().