Terraria: TileDrawing.DrawTrees
DrawTrees()
void TileDrawing.DrawTrees () inline private
     {
         Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
         Vector2 zero = Vector2.Zero;
         int num = 0;
         int num2 = _specialsCount[num];
         float num3 = 0.08f;
         float num4 = 0.06f;
         for (int i = 0; i < num2; i++)
         {
             Point point = _specialPositions[num][i];
             int x = point.X;
             int y = point.Y;
             Tile tile = Main.tile[x, y];
             if (tile == null || !tile.active())
             {
                 continue;
             }
             ushort type = tile.type;
             short frameX = tile.frameX;
             short frameY = tile.frameY;
             bool flag = tile.wall > 0;
             WorldGen.GetTreeFoliageDataMethod getTreeFoliageDataMethod = null;
             try
             {
                 bool flag2 = false;
                 switch (type)
                 {
                 case 5:
                     flag2 = true;
                     getTreeFoliageDataMethod = WorldGen.GetCommonTreeFoliageData;
                     break;
                 case 583:
                 case 584:
                 case 585:
                 case 586:
                 case 587:
                 case 588:
                 case 589:
                     flag2 = true;
                     getTreeFoliageDataMethod = WorldGen.GetGemTreeFoliageData;
                     break;
                 case 596:
                 case 616:
                     flag2 = true;
                     getTreeFoliageDataMethod = WorldGen.GetVanityTreeFoliageData;
                     break;
                 case 634:
                     flag2 = true;
                     getTreeFoliageDataMethod = WorldGen.GetAshTreeFoliageData;
                     break;
                 }
                 if (flag2 && frameY >= 198 && frameX >= 22)
                 {
                     int treeFrame = WorldGen.GetTreeFrame(tile);
                     switch (frameX)
                     {
                     case 22:
                     {
                         int treeStyle3 = 0;
                         int topTextureFrameWidth3 = 80;
                         int topTextureFrameHeight3 = 80;
                         int num13 = 0;
                         int grassPosX = x + num13;
                         int floorY3 = y;
                         if (!getTreeFoliageDataMethod(x, y, num13, ref treeFrame, ref treeStyle3, out floorY3, out topTextureFrameWidth3, out topTextureFrameHeight3))
{
                             continue;
                         }
                         EmitTreeLeaves(x, y, grassPosX, floorY3);
                         if (treeStyle3 == 14)
{
                             float num14 = (float)_rand.Next(28, 42) * 0.005f;
                             num14 += (float)(270 - Main.mouseTextColor) / 1000f;
                             if (tile.color() == 0)
{
                                 Lighting.AddLight(x, y, 0.1f, 0.2f + num14 / 2f, 0.7f + num14);
                             }
                             else
{
                                 Color color5 = WorldGen.paintColor(tile.color());
                                 float r3 = (float)(int)color5.R / 255f;
                                 float g3 = (float)(int)color5.G / 255f;
                                 float b3 = (float)(int)color5.B / 255f;
                                 Lighting.AddLight(x, y, r3, g3, b3);
                             }
                         }
                         byte tileColor3 = tile.color();
                         Texture2D treeTopTexture = GetTreeTopTexture(treeStyle3, 0, tileColor3);
                         Vector2 vector = (vector = new Vector2(x * 16 - (int)unscaledPosition.X + 8, y * 16 - (int)unscaledPosition.Y + 16) + zero);
                         float num15 = 0f;
                         if (!flag)
{
                             num15 = GetWindCycle(x, y, _treeWindCounter);
                         }
                         vector.X += num15 * 2f;
                         vector.Y += Math.Abs(num15) * 2f;
                         Color color6 = Lighting.GetColor(x, y);
                         if (tile.fullbrightBlock())
{
                             color6 = Color.White;
                         }
                         Main.spriteBatch.Draw(treeTopTexture, vector, new Rectangle(treeFrame * (topTextureFrameWidth3 + 2), 0, topTextureFrameWidth3, topTextureFrameHeight3), color6, num15 * num3, new Vector2(topTextureFrameWidth3 / 2, topTextureFrameHeight3), 1f, SpriteEffects.None, 0f);
                         if (type == 634)
{
                             Texture2D value3 = TextureAssets.GlowMask[316].Value;
                             Color white3 = Color.White;
                             Main.spriteBatch.Draw(value3, vector, new Rectangle(treeFrame * (topTextureFrameWidth3 + 2), 0, topTextureFrameWidth3, topTextureFrameHeight3), white3, num15 * num3, new Vector2(topTextureFrameWidth3 / 2, topTextureFrameHeight3), 1f, SpriteEffects.None, 0f);
                         }
                         break;
                     }
                     case 44:
                     {
                         int treeStyle2 = 0;
                         int num9 = x;
                         int floorY2 = y;
                         int num10 = 1;
                         if (!getTreeFoliageDataMethod(x, y, num10, ref treeFrame, ref treeStyle2, out floorY2, out var _, out var _))
{
                             continue;
                         }
                         EmitTreeLeaves(x, y, num9 + num10, floorY2);
                         if (treeStyle2 == 14)
{
                             float num11 = (float)_rand.Next(28, 42) * 0.005f;
                             num11 += (float)(270 - Main.mouseTextColor) / 1000f;
                             if (tile.color() == 0)
{
                                 Lighting.AddLight(x, y, 0.1f, 0.2f + num11 / 2f, 0.7f + num11);
                             }
                             else
{
                                 Color color3 = WorldGen.paintColor(tile.color());
                                 float r2 = (float)(int)color3.R / 255f;
                                 float g2 = (float)(int)color3.G / 255f;
                                 float b2 = (float)(int)color3.B / 255f;
                                 Lighting.AddLight(x, y, r2, g2, b2);
                             }
                         }
                         byte tileColor2 = tile.color();
                         Texture2D treeBranchTexture2 = GetTreeBranchTexture(treeStyle2, 0, tileColor2);
                         Vector2 position2 = new Vector2(x * 16, y * 16) - unscaledPosition.Floor() + zero + new Vector2(16f, 12f);
                         float num12 = 0f;
                         if (!flag)
{
                             num12 = GetWindCycle(x, y, _treeWindCounter);
                         }
                         if (num12 > 0f)
{
                             position2.X += num12;
                         }
                         position2.X += Math.Abs(num12) * 2f;
                         Color color4 = Lighting.GetColor(x, y);
                         if (tile.fullbrightBlock())
{
                             color4 = Color.White;
                         }
                         Main.spriteBatch.Draw(treeBranchTexture2, position2, new Rectangle(0, treeFrame * 42, 40, 40), color4, num12 * num4, new Vector2(40f, 24f), 1f, SpriteEffects.None, 0f);
                         if (type == 634)
{
                             Texture2D value2 = TextureAssets.GlowMask[317].Value;
                             Color white2 = Color.White;
                             Main.spriteBatch.Draw(value2, position2, new Rectangle(0, treeFrame * 42, 40, 40), white2, num12 * num4, new Vector2(40f, 24f), 1f, SpriteEffects.None, 0f);
                         }
                         break;
                     }
                     case 66:
                     {
                         int treeStyle = 0;
                         int num5 = x;
                         int floorY = y;
                         int num6 = -1;
                         if (!getTreeFoliageDataMethod(x, y, num6, ref treeFrame, ref treeStyle, out floorY, out var _, out var _))
{
                             continue;
                         }
                         EmitTreeLeaves(x, y, num5 + num6, floorY);
                         if (treeStyle == 14)
{
                             float num7 = (float)_rand.Next(28, 42) * 0.005f;
                             num7 += (float)(270 - Main.mouseTextColor) / 1000f;
                             if (tile.color() == 0)
{
                                 Lighting.AddLight(x, y, 0.1f, 0.2f + num7 / 2f, 0.7f + num7);
                             }
                             else
{
                                 Color color = WorldGen.paintColor(tile.color());
                                 float r = (float)(int)color.R / 255f;
                                 float g = (float)(int)color.G / 255f;
                                 float b = (float)(int)color.B / 255f;
                                 Lighting.AddLight(x, y, r, g, b);
                             }
                         }
                         byte tileColor = tile.color();
                         Texture2D treeBranchTexture = GetTreeBranchTexture(treeStyle, 0, tileColor);
                         Vector2 position = new Vector2(x * 16, y * 16) - unscaledPosition.Floor() + zero + new Vector2(0f, 18f);
                         float num8 = 0f;
                         if (!flag)
{
                             num8 = GetWindCycle(x, y, _treeWindCounter);
                         }
                         if (num8 < 0f)
{
                             position.X += num8;
                         }
                         position.X -= Math.Abs(num8) * 2f;
                         Color color2 = Lighting.GetColor(x, y);
                         if (tile.fullbrightBlock())
{
                             color2 = Color.White;
                         }
                         Main.spriteBatch.Draw(treeBranchTexture, position, new Rectangle(42, treeFrame * 42, 40, 40), color2, num8 * num4, new Vector2(0f, 30f), 1f, SpriteEffects.None, 0f);
                         if (type == 634)
{
                             Texture2D value = TextureAssets.GlowMask[317].Value;
                             Color white = Color.White;
                             Main.spriteBatch.Draw(value, position, new Rectangle(42, treeFrame * 42, 40, 40), white, num8 * num4, new Vector2(0f, 30f), 1f, SpriteEffects.None, 0f);
                         }
                         break;
                     }
                     }
                 }
                 if (type == 323 && frameX >= 88 && frameX <= 132)
                 {
                     int num16 = 0;
                     switch (frameX)
                     {
                     case 110:
                         num16 = 1;
                         break;
                     case 132:
                         num16 = 2;
                         break;
                     }
                     int treeTextureIndex = 15;
                     int num17 = 80;
                     int num18 = 80;
                     int num19 = 32;
                     int num20 = 0;
                     int palmTreeBiome = GetPalmTreeBiome(x, y);
                     int y2 = palmTreeBiome * 82;
                     if (palmTreeBiome >= 4 && palmTreeBiome <= 7)
                     {
                         treeTextureIndex = 21;
                         num17 = 114;
                         num18 = 98;
                         y2 = (palmTreeBiome - 4) * 98;
                         num19 = 48;
                         num20 = 2;
                     }
                     int frameY2 = Main.tile[x, y].frameY;
                     byte tileColor4 = tile.color();
                     Texture2D treeTopTexture2 = GetTreeTopTexture(treeTextureIndex, palmTreeBiome, tileColor4);
                     Vector2 position3 = new Vector2(x * 16 - (int)unscaledPosition.X - num19 + frameY2 + num17 / 2, y * 16 - (int)unscaledPosition.Y + 16 + num20) + zero;
                     float num21 = 0f;
                     if (!flag)
                     {
                         num21 = GetWindCycle(x, y, _treeWindCounter);
                     }
                     position3.X += num21 * 2f;
                     position3.Y += Math.Abs(num21) * 2f;
                     Color color7 = Lighting.GetColor(x, y);
                     if (tile.fullbrightBlock())
                     {
                         color7 = Color.White;
                     }
                     Main.spriteBatch.Draw(treeTopTexture2, position3, new Rectangle(num16 * (num17 + 2), y2, num17, num18), color7, num21 * num3, new Vector2(num17 / 2, num18), 1f, SpriteEffects.None, 0f);
                 }
             }
             catch
             {
             }
         }
     }
References _rand, _specialPositions, _specialsCount, _treeWindCounter, Tile.active(), Lighting.AddLight(), Main.Camera, Color, Tile.color(), EmitTreeLeaves(), Tile.frameX, Tile.frameY, Tile.fullbrightBlock(), WorldGen.GetAshTreeFoliageData(), Lighting.GetColor(), WorldGen.GetCommonTreeFoliageData(), WorldGen.GetGemTreeFoliageData(), GetPalmTreeBiome(), GetTreeBranchTexture(), WorldGen.GetTreeFoliageDataMethod(), WorldGen.GetTreeFrame(), GetTreeTopTexture(), WorldGen.GetVanityTreeFoliageData(), GetWindCycle(), TextureAssets.GlowMask, Main.mouseTextColor, UnifiedRandom.Next(), WorldGen.paintColor(), Main.spriteBatch, Main.tile, Tile.type, Camera.UnscaledPosition, Asset< T >.Value, and Tile.wall.
Referenced by PostDrawTiles().