Terraria: TileDrawing.PreparePaintForTilesOnScreen
PreparePaintForTilesOnScreen()
void TileDrawing.PreparePaintForTilesOnScreen () inline
     {
         if (Main.GameUpdateCount % 6 == 0)
         {
             Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
             Vector2 vector = new Vector2(Main.offScreenRange, Main.offScreenRange);
             if (Main.drawToScreen)
             {
                 vector = Vector2.Zero;
             }
             GetScreenDrawArea(unscaledPosition, vector + (Main.Camera.UnscaledPosition - Main.Camera.ScaledPosition), out var firstTileX, out var lastTileX, out var firstTileY, out var lastTileY);
             PrepareForAreaDrawing(firstTileX, lastTileX, firstTileY, lastTileY, prepareLazily: true);
         }
     }
References Main.Camera, Main.drawToScreen, Main.GameUpdateCount, GetScreenDrawArea(), Main.offScreenRange, PrepareForAreaDrawing(), Camera.ScaledPosition, and Camera.UnscaledPosition.
Referenced by Main.DoDraw().