Terraria: TileDrawing.DrawTiles_EmitParticles
DrawTiles_EmitParticles()
void TileDrawing.DrawTiles_EmitParticles (int j, int i, Tile tileCache, ushort typeCache, short tileFrameX, short tileFrameY, Color tileLight) inline private
     {
         bool num = IsVisible(tileCache);
         int leafFrequency = _leafFrequency;
         leafFrequency /= 4;
         if (typeCache == 244 && tileFrameX == 18 && tileFrameY == 18 && _rand.Next(2) == 0)
         {
             if (_rand.Next(500) == 0)
             {
                 Gore.NewGore(new Vector2(i * 16 + 8, j * 16 + 8), default(Vector2), 415, (float)_rand.Next(51, 101) * 0.01f);
             }
             else if (_rand.Next(250) == 0)
             {
                 Gore.NewGore(new Vector2(i * 16 + 8, j * 16 + 8), default(Vector2), 414, (float)_rand.Next(51, 101) * 0.01f);
             }
             else if (_rand.Next(80) == 0)
             {
                 Gore.NewGore(new Vector2(i * 16 + 8, j * 16 + 8), default(Vector2), 413, (float)_rand.Next(51, 101) * 0.01f);
             }
             else if (_rand.Next(10) == 0)
             {
                 Gore.NewGore(new Vector2(i * 16 + 8, j * 16 + 8), default(Vector2), 412, (float)_rand.Next(51, 101) * 0.01f);
             }
             else if (_rand.Next(3) == 0)
             {
                 Gore.NewGore(new Vector2(i * 16 + 8, j * 16 + 8), default(Vector2), 411, (float)_rand.Next(51, 101) * 0.01f);
             }
         }
         if (typeCache == 565 && tileFrameX == 0 && tileFrameY == 18 && _rand.Next(3) == 0 && ((Main.drawToScreen && _rand.Next(4) == 0) || !Main.drawToScreen))
         {
             Vector2 vector = new Point(i, j).ToWorldCoordinates();
             int type = 1202;
             float scale = 8f + Main.rand.NextFloat() * 1.6f;
             Vector2 position = vector + new Vector2(0f, -18f);
             Vector2 velocity = Main.rand.NextVector2Circular(0.7f, 0.25f) * 0.4f + Main.rand.NextVector2CircularEdge(1f, 0.4f) * 0.1f;
             velocity *= 4f;
             Gore.NewGorePerfect(position, velocity, type, scale);
         }
         if (typeCache == 215 && tileFrameY < 36 && _rand.Next(3) == 0 && ((Main.drawToScreen && _rand.Next(4) == 0) || !Main.drawToScreen) && tileFrameY == 0)
         {
             int num2 = Dust.NewDust(new Vector2(i * 16 + 2, j * 16 - 4), 4, 8, 31, 0f, 0f, 100);
             if (tileFrameX == 0)
             {
                 _dust[num2].position.X += _rand.Next(8);
             }
             if (tileFrameX == 36)
             {
                 _dust[num2].position.X -= _rand.Next(8);
             }
             _dust[num2].alpha += _rand.Next(100);
             _dust[num2].velocity *= 0.2f;
             _dust[num2].velocity.Y -= 0.5f + (float)_rand.Next(10) * 0.1f;
             _dust[num2].fadeIn = 0.5f + (float)_rand.Next(10) * 0.1f;
         }
         if (typeCache == 592 && tileFrameY == 18 && _rand.Next(3) == 0)
         {
             if ((Main.drawToScreen && _rand.Next(6) == 0) || !Main.drawToScreen)
             {
                 int num3 = Dust.NewDust(new Vector2(i * 16 + 2, j * 16 + 4), 4, 8, 31, 0f, 0f, 100);
                 if (tileFrameX == 0)
                 {
                     _dust[num3].position.X += _rand.Next(8);
                 }
                 if (tileFrameX == 36)
                 {
                     _dust[num3].position.X -= _rand.Next(8);
                 }
                 _dust[num3].alpha += _rand.Next(100);
                 _dust[num3].velocity *= 0.2f;
                 _dust[num3].velocity.Y -= 0.5f + (float)_rand.Next(10) * 0.1f;
                 _dust[num3].fadeIn = 0.5f + (float)_rand.Next(10) * 0.1f;
             }
         }
         else if (typeCache == 406 && tileFrameY == 54 && tileFrameX == 0 && _rand.Next(3) == 0)
         {
             Vector2 position2 = new Vector2(i * 16 + 16, j * 16 + 8);
             Vector2 velocity2 = new Vector2(0f, 0f);
             if (Main.WindForVisuals < 0f)
             {
                 velocity2.X = 0f - Main.WindForVisuals;
             }
             int type2 = _rand.Next(825, 828);
             if (_rand.Next(4) == 0)
             {
                 Gore.NewGore(position2, velocity2, type2, _rand.NextFloat() * 0.2f + 0.2f);
             }
             else if (_rand.Next(2) == 0)
             {
                 Gore.NewGore(position2, velocity2, type2, _rand.NextFloat() * 0.3f + 0.3f);
             }
             else
             {
                 Gore.NewGore(position2, velocity2, type2, _rand.NextFloat() * 0.4f + 0.4f);
             }
         }
         else if (typeCache == 452 && tileFrameY == 0 && tileFrameX == 0 && _rand.Next(3) == 0)
         {
             Vector2 position3 = new Vector2(i * 16 + 16, j * 16 + 8);
             Vector2 velocity3 = new Vector2(0f, 0f);
             if (Main.WindForVisuals < 0f)
             {
                 velocity3.X = 0f - Main.WindForVisuals;
             }
             int num4 = Main.tileFrame[typeCache];
             int type3 = 907 + num4 / 5;
             if (_rand.Next(2) == 0)
             {
                 Gore.NewGore(position3, velocity3, type3, _rand.NextFloat() * 0.4f + 0.4f);
             }
         }
         if (typeCache == 192 && _rand.Next(leafFrequency) == 0)
         {
             EmitLivingTreeLeaf(i, j, 910);
         }
         if (typeCache == 384 && _rand.Next(leafFrequency) == 0)
         {
             EmitLivingTreeLeaf(i, j, 914);
         }
         if (typeCache == 666 && _rand.Next(100) == 0 && j - 1 > 0 && !WorldGen.ActiveAndWalkableTile(i, j - 1))
         {
             ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.PooFly, new ParticleOrchestraSettings
             {
                 PositionInWorld = new Vector2(i * 16 + 8, j * 16 - 8)
             });
         }
         if (!num)
         {
             return;
         }
         if (typeCache == 238 && _rand.Next(10) == 0)
         {
             int num5 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 168);
             _dust[num5].noGravity = true;
             _dust[num5].alpha = 200;
         }
         if (typeCache == 139)
         {
             if (tileCache.frameX == 36 && tileCache.frameY % 36 == 0 && (int)Main.timeForVisualEffects % 7 == 0 && _rand.Next(3) == 0)
             {
                 int num6 = _rand.Next(570, 573);
                 Vector2 position4 = new Vector2(i * 16 + 8, j * 16 - 8);
                 Vector2 velocity4 = new Vector2(Main.WindForVisuals * 2f, -0.5f);
                 velocity4.X *= 1f + (float)_rand.Next(-50, 51) * 0.01f;
                 velocity4.Y *= 1f + (float)_rand.Next(-50, 51) * 0.01f;
                 if (num6 == 572)
                 {
                     position4.X -= 8f;
                 }
                 if (num6 == 571)
                 {
                     position4.X -= 4f;
                 }
                 Gore.NewGore(position4, velocity4, num6, 0.8f);
             }
         }
         else if (typeCache == 463)
         {
             if (tileFrameY == 54 && tileFrameX == 0)
             {
                 for (int k = 0; k < 4; k++)
                 {
                     if (_rand.Next(2) != 0)
                     {
                         Dust dust = Dust.NewDustDirect(new Vector2(i * 16 + 4, j * 16), 36, 8, 16);
                         dust.noGravity = true;
                         dust.alpha = 140;
                         dust.fadeIn = 1.2f;
                         dust.velocity = Vector2.Zero;
                     }
                 }
             }
             if (tileFrameY == 18 && (tileFrameX == 0 || tileFrameX == 36))
             {
                 for (int l = 0; l < 1; l++)
                 {
                     if (_rand.Next(13) == 0)
                     {
                         Dust dust2 = Dust.NewDustDirect(new Vector2(i * 16, j * 16), 8, 8, 274);
                         dust2.position = new Vector2(i * 16 + 8, j * 16 + 8);
                         dust2.position.X += ((tileFrameX == 36) ? 4 : (-4));
                         dust2.noGravity = true;
                         dust2.alpha = 128;
                         dust2.fadeIn = 1.2f;
                         dust2.noLight = true;
                         dust2.velocity = new Vector2(0f, _rand.NextFloatDirection() * 1.2f);
                     }
                 }
             }
         }
         else if (typeCache == 497)
         {
             if (tileCache.frameY / 40 == 31 && tileCache.frameY % 40 == 0)
             {
                 for (int m = 0; m < 1; m++)
                 {
                     if (_rand.Next(10) == 0)
                     {
                         Dust dust3 = Dust.NewDustDirect(new Vector2(i * 16, j * 16 + 8), 16, 12, 43);
                         dust3.noGravity = true;
                         dust3.alpha = 254;
                         dust3.color = Color.White;
                         dust3.scale = 0.7f;
                         dust3.velocity = Vector2.Zero;
                         dust3.noLight = true;
                     }
                 }
             }
         }
         else if (typeCache == 165 && tileFrameX >= 162 && tileFrameX <= 214 && tileFrameY == 72)
         {
             if (_rand.Next(60) == 0)
             {
                 int num7 = Dust.NewDust(new Vector2(i * 16 + 2, j * 16 + 6), 8, 4, 153);
                 _dust[num7].scale -= (float)_rand.Next(3) * 0.1f;
                 _dust[num7].velocity.Y = 0f;
                 _dust[num7].velocity.X *= 0.05f;
                 _dust[num7].alpha = 100;
             }
         }
         else if (typeCache == 42 && tileFrameX == 0)
         {
             int num8 = tileFrameY / 36;
             int num9 = tileFrameY / 18 % 2;
             if (num8 == 7 && num9 == 1)
             {
                 if (_rand.Next(50) == 0)
                 {
                     int num10 = Dust.NewDust(new Vector2(i * 16 + 4, j * 16 + 4), 8, 8, 58, 0f, 0f, 150);
                     _dust[num10].velocity *= 0.5f;
                 }
                 if (_rand.Next(100) == 0)
                 {
                     int num11 = Gore.NewGore(new Vector2(i * 16 - 2, j * 16 - 4), default(Vector2), _rand.Next(16, 18));
                     _gore[num11].scale *= 0.7f;
                     _gore[num11].velocity *= 0.25f;
                 }
             }
             else if (num8 == 29 && num9 == 1 && _rand.Next(40) == 0)
             {
                 int num12 = Dust.NewDust(new Vector2(i * 16 + 4, j * 16), 8, 8, 59, 0f, 0f, 100);
                 if (_rand.Next(3) != 0)
                 {
                     _dust[num12].noGravity = true;
                 }
                 _dust[num12].velocity *= 0.3f;
                 _dust[num12].velocity.Y -= 1.5f;
             }
         }
         if (typeCache == 4 && _rand.Next(40) == 0 && tileFrameX < 66)
         {
             int num13 = (int)MathHelper.Clamp(tileCache.frameY / 22, 0f, TorchID.Count - 1);
             int num14 = TorchID.Dust[num13];
             int num15 = 0;
             num15 = tileFrameX switch
             {
                 22 => Dust.NewDust(new Vector2(i * 16 + 6, j * 16), 4, 4, num14, 0f, 0f, 100),
                 44 => Dust.NewDust(new Vector2(i * 16 + 2, j * 16), 4, 4, num14, 0f, 0f, 100),
                 _ => Dust.NewDust(new Vector2(i * 16 + 4, j * 16), 4, 4, num14, 0f, 0f, 100),
             };
             if (_rand.Next(3) != 0)
             {
                 _dust[num15].noGravity = true;
             }
             _dust[num15].velocity *= 0.3f;
             _dust[num15].velocity.Y -= 1.5f;
             if (num14 == 66)
             {
                 _dust[num15].color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                 _dust[num15].noGravity = true;
             }
         }
         if (typeCache == 93 && _rand.Next(40) == 0 && tileFrameX == 0)
         {
             int num16 = tileFrameY / 54;
             if (tileFrameY / 18 % 3 == 0)
             {
                 int num17;
                 switch (num16)
                 {
                 case 0:
                 case 6:
                 case 7:
                 case 8:
                 case 10:
                 case 14:
                 case 15:
                 case 16:
                     num17 = 6;
                     break;
                 case 20:
                     num17 = 59;
                     break;
                 default:
                     num17 = -1;
                     break;
                 }
                 if (num17 != -1)
                 {
                     int num18 = Dust.NewDust(new Vector2(i * 16 + 4, j * 16 + 2), 4, 4, num17, 0f, 0f, 100);
                     if (_rand.Next(3) != 0)
                     {
                         _dust[num18].noGravity = true;
                     }
                     _dust[num18].velocity *= 0.3f;
                     _dust[num18].velocity.Y -= 1.5f;
                 }
             }
         }
         if (typeCache == 100 && _rand.Next(40) == 0 && tileFrameX < 36)
         {
             int num19 = tileFrameY / 36;
             if (tileFrameY / 18 % 2 == 0)
             {
                 int num20;
                 switch (num19)
                 {
                 case 0:
                 case 5:
                 case 7:
                 case 8:
                 case 10:
                 case 12:
                 case 14:
                 case 15:
                 case 16:
                     num20 = 6;
                     break;
                 case 20:
                     num20 = 59;
                     break;
                 default:
                     num20 = -1;
                     break;
                 }
                 if (num20 != -1)
                 {
                     int num21 = 0;
                     Vector2 position5 = ((tileFrameX == 0) ? ((_rand.Next(3) != 0) ? new Vector2(i * 16 + 14, j * 16 + 2) : new Vector2(i * 16 + 4, j * 16 + 2)) : ((_rand.Next(3) != 0) ? new Vector2(i * 16, j * 16 + 2) : new Vector2(i * 16 + 6, j * 16 + 2)));
                     num21 = Dust.NewDust(position5, 4, 4, num20, 0f, 0f, 100);
                     if (_rand.Next(3) != 0)
                     {
                         _dust[num21].noGravity = true;
                     }
                     _dust[num21].velocity *= 0.3f;
                     _dust[num21].velocity.Y -= 1.5f;
                 }
             }
         }
         if (typeCache == 98 && _rand.Next(40) == 0 && tileFrameY == 0 && tileFrameX == 0)
         {
             int num22 = Dust.NewDust(new Vector2(i * 16 + 12, j * 16 + 2), 4, 4, 6, 0f, 0f, 100);
             if (_rand.Next(3) != 0)
             {
                 _dust[num22].noGravity = true;
             }
             _dust[num22].velocity *= 0.3f;
             _dust[num22].velocity.Y -= 1.5f;
         }
         if (typeCache == 49 && tileFrameX == 0 && _rand.Next(2) == 0)
         {
             int num23 = Dust.NewDust(new Vector2(i * 16 + 4, j * 16 - 4), 4, 4, 172, 0f, 0f, 100);
             if (_rand.Next(3) == 0)
             {
                 _dust[num23].scale = 0.5f;
             }
             else
             {
                 _dust[num23].scale = 0.9f;
                 _dust[num23].noGravity = true;
             }
             _dust[num23].velocity *= 0.3f;
             _dust[num23].velocity.Y -= 1.5f;
         }
         if (typeCache == 372 && tileFrameX == 0 && _rand.Next(2) == 0)
         {
             int num24 = Dust.NewDust(new Vector2(i * 16 + 4, j * 16 - 4), 4, 4, 242, 0f, 0f, 100);
             if (_rand.Next(3) == 0)
             {
                 _dust[num24].scale = 0.5f;
             }
             else
             {
                 _dust[num24].scale = 0.9f;
                 _dust[num24].noGravity = true;
             }
             _dust[num24].velocity *= 0.3f;
             _dust[num24].velocity.Y -= 1.5f;
         }
         if (typeCache == 646 && tileFrameX == 0)
         {
             _rand.Next(2);
         }
         if (typeCache == 34 && _rand.Next(40) == 0 && tileFrameX < 54)
         {
             int num25 = tileFrameY / 54;
             int num26 = tileFrameX / 18 % 3;
             if (tileFrameY / 18 % 3 == 1 && num26 != 1)
             {
                 int num27;
                 switch (num25)
                 {
                 case 0:
                 case 1:
                 case 2:
                 case 3:
                 case 4:
                 case 5:
                 case 12:
                 case 13:
                 case 16:
                 case 19:
                 case 21:
                     num27 = 6;
                     break;
                 case 25:
                     num27 = 59;
                     break;
                 default:
                     num27 = -1;
                     break;
                 }
                 if (num27 != -1)
                 {
                     int num28 = Dust.NewDust(new Vector2(i * 16, j * 16 + 2), 14, 6, num27, 0f, 0f, 100);
                     if (_rand.Next(3) != 0)
                     {
                         _dust[num28].noGravity = true;
                     }
                     _dust[num28].velocity *= 0.3f;
                     _dust[num28].velocity.Y -= 1.5f;
                 }
             }
         }
         if (typeCache == 83)
         {
             int style = tileFrameX / 18;
             if (IsAlchemyPlantHarvestable(style))
             {
                 EmitAlchemyHerbParticles(j, i, style);
             }
         }
         if (typeCache == 22 && _rand.Next(400) == 0)
         {
             Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 14);
         }
         else if ((typeCache == 23 || typeCache == 24 || typeCache == 32) && _rand.Next(500) == 0)
         {
             Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 14);
         }
         else if (typeCache == 25 && _rand.Next(700) == 0)
         {
             Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 14);
         }
         else if (typeCache == 112 && _rand.Next(700) == 0)
         {
             Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 14);
         }
         else if (typeCache == 31 && _rand.Next(20) == 0)
         {
             if (tileFrameX >= 36)
             {
                 int num29 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 5, 0f, 0f, 100);
                 _dust[num29].velocity.Y = 0f;
                 _dust[num29].velocity.X *= 0.3f;
             }
             else
             {
                 Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 14, 0f, 0f, 100);
             }
         }
         else if (typeCache == 26 && _rand.Next(20) == 0)
         {
             if (tileFrameX >= 54)
             {
                 int num30 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 5, 0f, 0f, 100);
                 _dust[num30].scale = 1.5f;
                 _dust[num30].noGravity = true;
                 _dust[num30].velocity *= 0.75f;
             }
             else
             {
                 Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 14, 0f, 0f, 100);
             }
         }
         else if ((typeCache == 71 || typeCache == 72) && tileCache.color() == 0 && _rand.Next(500) == 0)
         {
             Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 41, 0f, 0f, 250, default(Color), 0.8f);
         }
         else if ((typeCache == 17 || typeCache == 77 || typeCache == 133) && _rand.Next(40) == 0)
         {
             if (tileFrameX == 18 && tileFrameY == 18)
             {
                 int num31 = Dust.NewDust(new Vector2(i * 16 - 4, j * 16 - 6), 8, 6, 6, 0f, 0f, 100);
                 if (_rand.Next(3) != 0)
                 {
                     _dust[num31].noGravity = true;
                 }
             }
         }
         else if (typeCache == 405 && _rand.Next(20) == 0)
         {
             if (tileFrameX == 18 && tileFrameY == 18)
             {
                 int num32 = Dust.NewDust(new Vector2(i * 16 - 4, j * 16 - 6), 24, 10, 6, 0f, 0f, 100);
                 if (_rand.Next(5) != 0)
                 {
                     _dust[num32].noGravity = true;
                 }
             }
         }
         else if (typeCache == 37 && _rand.Next(250) == 0)
         {
             int num33 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 6, 0f, 0f, 0, default(Color), _rand.Next(3));
             if (_dust[num33].scale > 1f)
             {
                 _dust[num33].noGravity = true;
             }
         }
         else if ((typeCache == 58 || typeCache == 76 || typeCache == 684) && _rand.Next(250) == 0)
         {
             int num34 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 6, 0f, 0f, 0, default(Color), _rand.Next(3));
             if (_dust[num34].scale > 1f)
             {
                 _dust[num34].noGravity = true;
             }
             _dust[num34].noLight = true;
         }
         else if (typeCache == 61)
         {
             if (tileFrameX == 144 && _rand.Next(60) == 0)
             {
                 int num35 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 44, 0f, 0f, 250, default(Color), 0.4f);
                 _dust[num35].fadeIn = 0.7f;
             }
         }
         else if (Main.tileShine[typeCache] > 0)
         {
             if (tileLight.R <= 20 && tileLight.B <= 20 && tileLight.G <= 20)
             {
                 return;
             }
             int num36 = tileLight.R;
             if (tileLight.G > num36)
             {
                 num36 = tileLight.G;
             }
             if (tileLight.B > num36)
             {
                 num36 = tileLight.B;
             }
             num36 /= 30;
             if (_rand.Next(Main.tileShine[typeCache]) >= num36 || ((typeCache == 21 || typeCache == 441) && (tileFrameX < 36 || tileFrameX >= 180) && (tileFrameX < 396 || tileFrameX > 409)) || ((typeCache == 467 || typeCache == 468) && (tileFrameX < 144 || tileFrameX >= 180)))
             {
                 return;
             }
             Color newColor = Color.White;
             switch (typeCache)
             {
             case 178:
             {
                 switch (tileFrameX / 18)
                 {
                 case 0:
                     newColor = new Color(255, 0, 255, 255);
                     break;
                 case 1:
                     newColor = new Color(255, 255, 0, 255);
                     break;
                 case 2:
                     newColor = new Color(0, 0, 255, 255);
                     break;
                 case 3:
                     newColor = new Color(0, 255, 0, 255);
                     break;
                 case 4:
                     newColor = new Color(255, 0, 0, 255);
                     break;
                 case 5:
                     newColor = new Color(255, 255, 255, 255);
                     break;
                 case 6:
                     newColor = new Color(255, 255, 0, 255);
                     break;
                 }
                 int num37 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 43, 0f, 0f, 254, newColor, 0.5f);
                 _dust[num37].velocity *= 0f;
                 return;
             }
             case 63:
                 newColor = new Color(0, 0, 255, 255);
                 break;
             }
             if (typeCache == 64)
             {
                 newColor = new Color(255, 0, 0, 255);
             }
             if (typeCache == 65)
             {
                 newColor = new Color(0, 255, 0, 255);
             }
             if (typeCache == 66)
             {
                 newColor = new Color(255, 255, 0, 255);
             }
             if (typeCache == 67)
             {
                 newColor = new Color(255, 0, 255, 255);
             }
             if (typeCache == 68)
             {
                 newColor = new Color(255, 255, 255, 255);
             }
             if (typeCache == 12 || typeCache == 665)
             {
                 newColor = new Color(255, 0, 0, 255);
             }
             if (typeCache == 639)
             {
                 newColor = new Color(0, 0, 255, 255);
             }
             if (typeCache == 204)
             {
                 newColor = new Color(255, 0, 0, 255);
             }
             if (typeCache == 211)
             {
                 newColor = new Color(50, 255, 100, 255);
             }
             int num38 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 43, 0f, 0f, 254, newColor, 0.5f);
             _dust[num38].velocity *= 0f;
         }
         else if (Main.tileSolid[tileCache.type] && Main.shimmerAlpha > 0f && (tileLight.R > 20 || tileLight.B > 20 || tileLight.G > 20))
         {
             int num39 = tileLight.R;
             if (tileLight.G > num39)
             {
                 num39 = tileLight.G;
             }
             if (tileLight.B > num39)
             {
                 num39 = tileLight.B;
             }
             int maxValue = 500;
             if ((float)_rand.Next(maxValue) < 2f * Main.shimmerAlpha)
             {
                 Color white = Color.White;
                 float scale2 = ((float)num39 / 255f + 1f) / 2f;
                 int num40 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 43, 0f, 0f, 254, white, scale2);
                 _dust[num40].velocity *= 0f;
             }
         }
     }
References _dust, _gore, _leafFrequency, _rand, WorldGen.ActiveAndWalkableTile(), Dust.alpha, Color, Dust.color, Tile.color(), TorchID.Count, Main.DiscoB, Main.DiscoG, Main.DiscoR, Main.drawToScreen, TorchID.Dust, EmitAlchemyHerbParticles(), EmitLivingTreeLeaf(), Dust.fadeIn, Tile.frameX, Tile.frameY, IsAlchemyPlantHarvestable(), IsVisible(), Dust.NewDust(), Dust.NewDustDirect(), Gore.NewGore(), Gore.NewGorePerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.position, Main.rand, ParticleOrchestrator.RequestParticleSpawn(), Dust.scale, Gore.scale, Main.shimmerAlpha, Main.tileFrame, Main.tileShine, Main.tileSolid, Main.timeForVisualEffects, Tile.type, Dust.velocity, Gore.velocity, and Main.WindForVisuals.
Referenced by DrawAnyDirectionalGrass(), DrawGrass(), DrawMultiTileGrassInWind(), DrawMultiTileVinesInWind(), and DrawSingleTile().