Terraria: TileDrawing.Update
Update()
void TileDrawing.Update () inline
     {
         if (!Main.dedServ)
         {
             double num = Math.Abs(Main.WindForVisuals);
             num = Utils.GetLerpValue(0.08f, 1.2f, (float)num, clamped: true);
             _treeWindCounter += 1.0 / 240.0 + 1.0 / 240.0 * num * 2.0;
             _grassWindCounter += 1.0 / 180.0 + 1.0 / 180.0 * num * 4.0;
             _sunflowerWindCounter += 1.0 / 420.0 + 1.0 / 420.0 * num * 5.0;
             _vineWindCounter += 1.0 / 120.0 + 1.0 / 120.0 * num * 0.4000000059604645;
             UpdateLeafFrequency();
             EnsureWindGridSize();
             _windGrid.Update();
             _shouldShowInvisibleBlocks = Main.ShouldShowInvisibleWalls();
             if (_shouldShowInvisibleBlocks_LastFrame != _shouldShowInvisibleBlocks)
             {
                 _shouldShowInvisibleBlocks_LastFrame = _shouldShowInvisibleBlocks;
                 Main.sectionManager.SetAllFramedSectionsAsNeedingRefresh();
             }
         }
     }
References _grassWindCounter, _shouldShowInvisibleBlocks, _shouldShowInvisibleBlocks_LastFrame, _sunflowerWindCounter, _treeWindCounter, _vineWindCounter, _windGrid, Main.dedServ, EnsureWindGridSize(), Utils.GetLerpValue(), Main.sectionManager, WorldSections.SetAllFramedSectionsAsNeedingRefresh(), Main.ShouldShowInvisibleWalls(), WindGrid.Update(), UpdateLeafFrequency(), and Main.WindForVisuals.
Referenced by Main.DoUpdateInWorld().