Terraria: TileDrawing.DrawPartialLiquid
DrawPartialLiquid()
void TileDrawing.DrawPartialLiquid (bool behindBlocks, Tile tileCache, ref Vector2 position, ref Rectangle liquidSize, int liquidType, ref VertexColors colors) inline private
     {
         int num = tileCache.slope();
         bool flag = !TileID.Sets.BlocksWaterDrawingBehindSelf[tileCache.type];
         if (!behindBlocks)
         {
             flag = false;
         }
         if (flag || num == 0)
         {
             Main.tileBatch.Draw(TextureAssets.Liquid[liquidType].Value, position, liquidSize, colors, default(Vector2), 1f, SpriteEffects.None);
             return;
         }
         liquidSize.X += 18 * (num - 1);
         switch (num)
         {
         case 1:
             Main.tileBatch.Draw(TextureAssets.LiquidSlope[liquidType].Value, position, liquidSize, colors, Vector2.Zero, 1f, SpriteEffects.None);
             break;
         case 2:
             Main.tileBatch.Draw(TextureAssets.LiquidSlope[liquidType].Value, position, liquidSize, colors, Vector2.Zero, 1f, SpriteEffects.None);
             break;
         case 3:
             Main.tileBatch.Draw(TextureAssets.LiquidSlope[liquidType].Value, position, liquidSize, colors, Vector2.Zero, 1f, SpriteEffects.None);
             break;
         case 4:
             Main.tileBatch.Draw(TextureAssets.LiquidSlope[liquidType].Value, position, liquidSize, colors, Vector2.Zero, 1f, SpriteEffects.None);
             break;
         }
     }
References TileID.Sets.BlocksWaterDrawingBehindSelf, TileBatch.Draw(), TextureAssets.Liquid, TextureAssets.LiquidSlope, Tile.slope(), Main.tileBatch, Tile.type, and Asset< T >.Value.
Referenced by DrawTile_LiquidBehindTile().