Terraria: TileDrawing.DrawGrass
DrawGrass()
void TileDrawing.DrawGrass () inline private
     {
         Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
         Vector2 zero = Vector2.Zero;
         int num = 3;
         int num2 = _specialsCount[num];
         for (int i = 0; i < num2; i++)
         {
             Point point = _specialPositions[num][i];
             int x = point.X;
             int y = point.Y;
             Tile tile = Main.tile[x, y];
             if (tile == null || !tile.active() || !IsVisible(tile))
             {
                 continue;
             }
             ushort type = tile.type;
             short tileFrameX = tile.frameX;
             short tileFrameY = tile.frameY;
             GetTileDrawData(x, y, tile, type, ref tileFrameX, ref tileFrameY, out var tileWidth, out var tileHeight, out var tileTop, out var halfBrickHeight, out var addFrX, out var addFrY, out var tileSpriteEffect, out var glowTexture, out var glowSourceRect, out var glowColor);
             bool flag = _rand.Next(4) == 0;
             Color tileLight = Lighting.GetColor(x, y);
             DrawAnimatedTile_AdjustForVisionChangers(x, y, tile, type, tileFrameX, tileFrameY, ref tileLight, flag);
             tileLight = DrawTiles_GetLightOverride(y, x, tile, type, tileFrameX, tileFrameY, tileLight);
             if (_isActiveAndNotPaused && flag)
             {
                 DrawTiles_EmitParticles(y, x, tile, type, tileFrameX, tileFrameY, tileLight);
             }
             if (type == 83 && IsAlchemyPlantHarvestable(tileFrameX / 18))
             {
                 type = 84;
                 Main.instance.LoadTiles(type);
             }
             Vector2 position = new Vector2(x * 16 - (int)unscaledPosition.X + 8, y * 16 - (int)unscaledPosition.Y + 16) + zero;
             _ = _grassWindCounter;
             float num3 = GetWindCycle(x, y, _grassWindCounter);
             if (!WallID.Sets.AllowsWind[tile.wall])
             {
                 num3 = 0f;
             }
             if (!InAPlaceWithWind(x, y, 1, 1))
             {
                 num3 = 0f;
             }
             num3 += GetWindGridPush(x, y, 20, 0.35f);
             position.X += num3 * 1f;
             position.Y += Math.Abs(num3) * 1f;
             Texture2D tileDrawTexture = GetTileDrawTexture(tile, x, y);
             if (tileDrawTexture != null)
             {
                 Main.spriteBatch.Draw(tileDrawTexture, position, new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), tileLight, num3 * 0.1f, new Vector2(tileWidth / 2, 16 - halfBrickHeight - tileTop), 1f, tileSpriteEffect, 0f);
                 if (glowTexture != null)
                 {
                     Main.spriteBatch.Draw(glowTexture, position, glowSourceRect, glowColor, num3 * 0.1f, new Vector2(tileWidth / 2, 16 - halfBrickHeight - tileTop), 1f, tileSpriteEffect, 0f);
                 }
             }
         }
     }
References _grassWindCounter, _isActiveAndNotPaused, _rand, _specialPositions, _specialsCount, Tile.active(), WallID.Sets.AllowsWind, Main.Camera, Color, DrawAnimatedTile_AdjustForVisionChangers(), DrawTiles_EmitParticles(), DrawTiles_GetLightOverride(), Tile.frameX, Tile.frameY, Lighting.GetColor(), GetTileDrawData(), GetTileDrawTexture(), GetWindCycle(), GetWindGridPush(), InAPlaceWithWind(), Main.instance, IsAlchemyPlantHarvestable(), IsVisible(), Main.LoadTiles(), UnifiedRandom.Next(), Main.spriteBatch, Main.tile, Tile.type, Camera.UnscaledPosition, and Tile.wall.
Referenced by PostDrawTiles().