Terraria: TileDrawing.GetFinalLight
GetFinalLight() [1/2]
static Color TileDrawing.GetFinalLight (Tile tileCache, ushort typeCache, Color tileLight, Color tint) inline static private
     {
         int num = (int)((float)(tileLight.R * tint.R) / 255f);
         int num2 = (int)((float)(tileLight.G * tint.G) / 255f);
         int num3 = (int)((float)(tileLight.B * tint.B) / 255f);
         if (num > 255)
         {
             num = 255;
         }
         if (num2 > 255)
         {
             num2 = 255;
         }
         if (num3 > 255)
         {
             num3 = 255;
         }
         num3 <<= 16;
         num2 <<= 8;
         tileLight.PackedValue = (uint)(num | num2 | num3) | 0xFF000000u;
         if (tileCache.fullbrightBlock())
         {
             tileLight = Color.White;
         }
         if (tileCache.inActive())
         {
             tileLight = tileCache.actColor(tileLight);
         }
         else if (ShouldTileShine(typeCache, tileCache.frameX))
         {
             tileLight = Main.shine(tileLight, typeCache);
         }
         return tileLight;
     }
References Tile.actColor(), Color, Tile.frameX, Tile.fullbrightBlock(), Tile.inActive(), Main.shine(), and ShouldTileShine().
Referenced by DrawSingleTile(), DrawSingleTile_SlicedBlock(), and DrawTile_MinecartTrack().