Terraria: TileDrawing.CacheSpecialDraws_Part2
CacheSpecialDraws_Part2()
void TileDrawing.CacheSpecialDraws_Part2 (int tileX, int tileY, TileDrawInfo drawData, bool skipDraw) inline private
     {
         if (TileID.Sets.BasicChest[drawData.typeCache])
         {
             Point key = new Point(tileX, tileY);
             if (drawData.tileFrameX % 36 != 0)
             {
                 key.X--;
             }
             if (drawData.tileFrameY % 36 != 0)
             {
                 key.Y--;
             }
             if (!_chestPositions.ContainsKey(key))
             {
                 _chestPositions[key] = Chest.FindChest(key.X, key.Y);
             }
             int num = drawData.tileFrameX / 18;
             int num2 = drawData.tileFrameY / 18;
             int num3 = drawData.tileFrameX / 36;
             int num4 = num * 18;
             drawData.addFrX = num4 - drawData.tileFrameX;
             int num5 = num2 * 18;
             if (_chestPositions[key] != -1)
             {
                 int frame = Main.chest[_chestPositions[key]].frame;
                 if (frame == 1)
                 {
                     num5 += 38;
                 }
                 if (frame == 2)
                 {
                     num5 += 76;
                 }
             }
             drawData.addFrY = num5 - drawData.tileFrameY;
             if (num2 != 0)
             {
                 drawData.tileHeight = 18;
             }
             if (drawData.typeCache == 21 && (num3 == 48 || num3 == 49))
             {
                 drawData.glowSourceRect = new Rectangle(16 * (num % 2), drawData.tileFrameY + drawData.addFrY, drawData.tileWidth, drawData.tileHeight);
             }
         }
         if (drawData.typeCache != 378)
         {
             return;
         }
         Point key2 = new Point(tileX, tileY);
         if (drawData.tileFrameX % 36 != 0)
         {
             key2.X--;
         }
         if (drawData.tileFrameY % 54 != 0)
         {
             key2.Y -= drawData.tileFrameY / 18;
         }
         if (!_trainingDummyTileEntityPositions.ContainsKey(key2))
         {
             _trainingDummyTileEntityPositions[key2] = TETrainingDummy.Find(key2.X, key2.Y);
         }
         if (_trainingDummyTileEntityPositions[key2] != -1)
         {
             int npc = ((TETrainingDummy)TileEntity.ByID[_trainingDummyTileEntityPositions[key2]]).npc;
             if (npc != -1)
             {
                 int num6 = Main.npc[npc].frame.Y / 55;
                 num6 *= 54;
                 num6 += drawData.tileFrameY;
                 drawData.addFrY = num6 - drawData.tileFrameY;
             }
         }
     }
References _chestPositions, _trainingDummyTileEntityPositions, TileDrawInfo.addFrX, TileDrawInfo.addFrY, TileID.Sets.BasicChest, TileEntity.ByID, Main.chest, TETrainingDummy.Find(), Chest.FindChest(), Chest.frame, NPC.frame, TileDrawInfo.glowSourceRect, Main.npc, TileDrawInfo.tileFrameX, TileDrawInfo.tileFrameY, TileDrawInfo.tileHeight, TileDrawInfo.tileWidth, and TileDrawInfo.typeCache.
Referenced by DrawSingleTile().