Terraria: TileDrawing.DrawMultiTileGrassInWind
DrawMultiTileGrassInWind()
void TileDrawing.DrawMultiTileGrassInWind (Vector2 screenPosition, Vector2 offSet, int topLeftX, int topLeftY, int sizeX, int sizeY) inline private
     {
         float windCycle = GetWindCycle(topLeftX, topLeftY, _sunflowerWindCounter);
         new Vector2((float)(sizeX * 16) * 0.5f, sizeY * 16);
         Vector2 vector = new Vector2((float)(topLeftX * 16 - (int)screenPosition.X) + (float)sizeX * 16f * 0.5f, topLeftY * 16 - (int)screenPosition.Y + 16 * sizeY) + offSet;
         float num = 0.07f;
         int type = Main.tile[topLeftX, topLeftY].type;
         Texture2D texture2D = null;
         Color color = Color.Transparent;
         bool flag = InAPlaceWithWind(topLeftX, topLeftY, sizeX, sizeY);
         switch (type)
         {
         case 27:
             texture2D = TextureAssets.Flames[14].Value;
             color = Color.White;
             break;
         case 519:
             flag = InAPlaceWithWind(topLeftX, topLeftY, sizeX, 1);
             break;
         default:
             num = 0.15f;
             break;
         case 521:
         case 522:
         case 523:
         case 524:
         case 525:
         case 526:
         case 527:
             num = 0f;
             flag = false;
             break;
         }
         for (int i = topLeftX; i < topLeftX + sizeX; i++)
         {
             for (int j = topLeftY; j < topLeftY + sizeY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 ushort type2 = tile.type;
                 if (type2 != type || !IsVisible(tile))
                 {
                     continue;
                 }
                 Math.Abs(((float)(i - topLeftX) + 0.5f) / (float)sizeX - 0.5f);
                 short tileFrameX = tile.frameX;
                 short tileFrameY = tile.frameY;
                 float num2 = 1f - (float)(j - topLeftY + 1) / (float)sizeY;
                 if (num2 == 0f)
                 {
                     num2 = 0.1f;
                 }
                 if (!flag)
                 {
                     num2 = 0f;
                 }
                 GetTileDrawData(i, j, tile, type2, ref tileFrameX, ref tileFrameY, out var tileWidth, out var tileHeight, out var tileTop, out var halfBrickHeight, out var addFrX, out var addFrY, out var tileSpriteEffect, out var _, out var _, out var _);
                 bool flag2 = _rand.Next(4) == 0;
                 Color tileLight = Lighting.GetColor(i, j);
                 DrawAnimatedTile_AdjustForVisionChangers(i, j, tile, type2, tileFrameX, tileFrameY, ref tileLight, flag2);
                 tileLight = DrawTiles_GetLightOverride(j, i, tile, type2, tileFrameX, tileFrameY, tileLight);
                 if (_isActiveAndNotPaused && flag2)
                 {
                     DrawTiles_EmitParticles(j, i, tile, type2, tileFrameX, tileFrameY, tileLight);
                 }
                 Vector2 vector2 = new Vector2(i * 16 - (int)screenPosition.X, j * 16 - (int)screenPosition.Y + tileTop) + offSet;
                 if (tile.type == 493 && tile.frameY == 0)
                 {
                     if (Main.WindForVisuals >= 0f)
                     {
                         tileSpriteEffect ^= SpriteEffects.FlipHorizontally;
                     }
                     if (!tileSpriteEffect.HasFlag(SpriteEffects.FlipHorizontally))
                     {
                         vector2.X -= 6f;
                     }
                     else
                     {
                         vector2.X += 6f;
                     }
                 }
                 Vector2 vector3 = new Vector2(windCycle * 1f, Math.Abs(windCycle) * 2f * num2);
                 Vector2 origin = vector - vector2;
                 Texture2D tileDrawTexture = GetTileDrawTexture(tile, i, j);
                 if (tileDrawTexture != null)
                 {
                     Main.spriteBatch.Draw(tileDrawTexture, vector + new Vector2(0f, vector3.Y), new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), tileLight, windCycle * num * num2, origin, 1f, tileSpriteEffect, 0f);
                     if (texture2D != null)
                     {
                         Main.spriteBatch.Draw(texture2D, vector + new Vector2(0f, vector3.Y), new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), color, windCycle * num * num2, origin, 1f, tileSpriteEffect, 0f);
                     }
                 }
             }
         }
     }
References _isActiveAndNotPaused, _rand, _sunflowerWindCounter, Color, DrawAnimatedTile_AdjustForVisionChangers(), DrawTiles_EmitParticles(), DrawTiles_GetLightOverride(), TextureAssets.Flames, Tile.frameX, Tile.frameY, Lighting.GetColor(), GetTileDrawData(), GetTileDrawTexture(), GetWindCycle(), InAPlaceWithWind(), IsVisible(), UnifiedRandom.Next(), Main.spriteBatch, Main.tile, Tile.type, Asset< T >.Value, and Main.WindForVisuals.
Referenced by DrawMultiTileGrass().