Terraria: TileDrawing.DrawSpecialTilesLegacy
DrawSpecialTilesLegacy()
void TileDrawing.DrawSpecialTilesLegacy (Vector2 screenPosition, Vector2 offSet) inline private
     {
         for (int i = 0; i < _specialTilesCount; i++)
         {
             int num = _specialTileX[i];
             int num2 = _specialTileY[i];
             Tile tile = Main.tile[num, num2];
             ushort type = tile.type;
             short frameX = tile.frameX;
             short frameY = tile.frameY;
             if (type == 237)
             {
                 Main.spriteBatch.Draw(TextureAssets.SunOrb.Value, new Vector2((float)(num * 16 - (int)screenPosition.X) + 8f, num2 * 16 - (int)screenPosition.Y - 36) + offSet, new Rectangle(0, 0, TextureAssets.SunOrb.Width(), TextureAssets.SunOrb.Height()), new Color(Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor, 0), Main.sunCircle, new Vector2(TextureAssets.SunOrb.Width() / 2, TextureAssets.SunOrb.Height() / 2), 1f, SpriteEffects.None, 0f);
             }
             if (type == 334 && frameX >= 5000)
             {
                 _ = frameY / 18;
                 int num3 = frameX;
                 int num4 = 0;
                 int num5 = num3 % 5000;
                 num5 -= 100;
                 while (num3 >= 5000)
                 {
                     num4++;
                     num3 -= 5000;
                 }
                 int frameX2 = Main.tile[num + 1, num2].frameX;
                 frameX2 = ((frameX2 < 25000) ? (frameX2 - 10000) : (frameX2 - 25000));
                 Item item = new Item();
                 item.netDefaults(num5);
                 item.Prefix(frameX2);
                 Main.instance.LoadItem(item.type);
                 Texture2D value = TextureAssets.Item[item.type].Value;
                 Rectangle value2 = ((Main.itemAnimations[item.type] == null) ? value.Frame() : Main.itemAnimations[item.type].GetFrame(value));
                 int width = value2.Width;
                 int height = value2.Height;
                 float num6 = 1f;
                 if (width > 40 || height > 40)
                 {
                     num6 = ((width <= height) ? (40f / (float)height) : (40f / (float)width));
                 }
                 num6 *= item.scale;
                 SpriteEffects effects = SpriteEffects.None;
                 if (num4 >= 3)
                 {
                     effects = SpriteEffects.FlipHorizontally;
                 }
                 Color color = Lighting.GetColor(num, num2);
                 Main.spriteBatch.Draw(value, new Vector2(num * 16 - (int)screenPosition.X + 24, num2 * 16 - (int)screenPosition.Y + 8) + offSet, value2, Lighting.GetColor(num, num2), 0f, new Vector2(width / 2, height / 2), num6, effects, 0f);
                 if (item.color != default(Color))
                 {
                     Main.spriteBatch.Draw(value, new Vector2(num * 16 - (int)screenPosition.X + 24, num2 * 16 - (int)screenPosition.Y + 8) + offSet, value2, item.GetColor(color), 0f, new Vector2(width / 2, height / 2), num6, effects, 0f);
                 }
             }
             if (type == 395)
             {
                 Item item2 = ((TEItemFrame)TileEntity.ByPosition[new Point16(num, num2)]).item;
                 Vector2 screenPositionForItemCenter = new Vector2(num * 16 - (int)screenPosition.X + 16, num2 * 16 - (int)screenPosition.Y + 16) + offSet;
                 Color color2 = Lighting.GetColor(num, num2);
                 ItemSlot.DrawItemIcon(item2, 31, Main.spriteBatch, screenPositionForItemCenter, item2.scale, 20f, color2);
             }
             if (type == 520)
             {
                 Item item3 = ((TEFoodPlatter)TileEntity.ByPosition[new Point16(num, num2)]).item;
                 if (!item3.IsAir)
                 {
                     Main.instance.LoadItem(item3.type);
                     Texture2D value3 = TextureAssets.Item[item3.type].Value;
                     Rectangle value4 = ((!ItemID.Sets.IsFood[item3.type]) ? value3.Frame() : value3.Frame(1, 3, 0, 2));
                     int width2 = value4.Width;
                     int height2 = value4.Height;
                     float num7 = 1f;
                     SpriteEffects effects2 = ((tile.frameX == 0) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
                     Color color3 = Lighting.GetColor(num, num2);
                     Color currentColor = color3;
                     float scale = 1f;
                     ItemSlot.GetItemLight(ref currentColor, ref scale, item3);
                     num7 *= scale;
                     Vector2 position = new Vector2(num * 16 - (int)screenPosition.X + 8, num2 * 16 - (int)screenPosition.Y + 16) + offSet;
                     position.Y += 2f;
                     Vector2 origin = new Vector2(width2 / 2, height2);
                     Main.spriteBatch.Draw(value3, position, value4, currentColor, 0f, origin, num7, effects2, 0f);
                     if (item3.color != default(Color))
                     {
                         Main.spriteBatch.Draw(value3, position, value4, item3.GetColor(color3), 0f, origin, num7, effects2, 0f);
                     }
                 }
             }
             if (type == 471)
             {
                 Item item4 = (TileEntity.ByPosition[new Point16(num, num2)] as TEWeaponsRack).item;
                 Main.GetItemDrawFrame(item4.type, out var itemTexture, out var itemFrame);
                 int width3 = itemFrame.Width;
                 int height3 = itemFrame.Height;
                 float num8 = 1f;
                 float num9 = 40f;
                 if ((float)width3 > num9 || (float)height3 > num9)
                 {
                     num8 = ((width3 <= height3) ? (num9 / (float)height3) : (num9 / (float)width3));
                 }
                 num8 *= item4.scale;
                 SpriteEffects effects3 = SpriteEffects.FlipHorizontally;
                 if (tile.frameX < 54)
                 {
                     effects3 = SpriteEffects.None;
                 }
                 Color color4 = Lighting.GetColor(num, num2);
                 Color currentColor2 = color4;
                 float scale2 = 1f;
                 ItemSlot.GetItemLight(ref currentColor2, ref scale2, item4);
                 num8 *= scale2;
                 Main.spriteBatch.Draw(itemTexture, new Vector2(num * 16 - (int)screenPosition.X + 24, num2 * 16 - (int)screenPosition.Y + 24) + offSet, itemFrame, currentColor2, 0f, new Vector2(width3 / 2, height3 / 2), num8, effects3, 0f);
                 if (item4.color != default(Color))
                 {
                     Main.spriteBatch.Draw(itemTexture, new Vector2(num * 16 - (int)screenPosition.X + 24, num2 * 16 - (int)screenPosition.Y + 24) + offSet, itemFrame, item4.GetColor(color4), 0f, new Vector2(width3 / 2, height3 / 2), num8, effects3, 0f);
                 }
             }
             if (type == 412)
             {
                 Texture2D value5 = TextureAssets.GlowMask[202].Value;
                 int num10 = Main.tileFrame[type] / 60;
                 int frameY2 = (num10 + 1) % 4;
                 float num11 = (float)(Main.tileFrame[type] % 60) / 60f;
                 Color color5 = new Color(255, 255, 255, 255);
                 Main.spriteBatch.Draw(value5, new Vector2(num * 16 - (int)screenPosition.X, num2 * 16 - (int)screenPosition.Y + 10) + offSet, value5.Frame(1, 4, 0, num10), color5 * (1f - num11), 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                 Main.spriteBatch.Draw(value5, new Vector2(num * 16 - (int)screenPosition.X, num2 * 16 - (int)screenPosition.Y + 10) + offSet, value5.Frame(1, 4, 0, frameY2), color5 * num11, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
             }
             if (type == 620)
             {
                 Texture2D value6 = TextureAssets.Extra[202].Value;
                 _ = (float)(Main.tileFrame[type] % 60) / 60f;
                 int num12 = 2;
                 Main.critterCage = true;
                 int waterAnimalCageFrame = GetWaterAnimalCageFrame(num, num2, frameX, frameY);
                 int num13 = 8;
                 int num14 = Main.butterflyCageFrame[num13, waterAnimalCageFrame];
                 int num15 = 6;
                 float num16 = 1f;
                 Rectangle value7 = new Rectangle(0, 34 * num14, 32, 32);
                 Vector2 vector = new Vector2(num * 16 - (int)screenPosition.X, num2 * 16 - (int)screenPosition.Y + num12) + offSet;
                 Main.spriteBatch.Draw(value6, vector, value7, new Color(255, 255, 255, 255), 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                 for (int j = 0; j < num15; j++)
                 {
                     Color color6 = new Color(127, 127, 127, 0).MultiplyRGBA(Main.hslToRgb((Main.GlobalTimeWrappedHourly + (float)j / (float)num15) % 1f, 1f, 0.5f));
                     color6 *= 1f - num16 * 0.5f;
                     color6.A = 0;
                     int num17 = 2;
                     Vector2 position2 = vector + ((float)j / (float)num15 * ((float)Math.PI * 2f)).ToRotationVector2() * ((float)num17 * num16 + 2f);
                     Main.spriteBatch.Draw(value6, position2, value7, color6, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                 }
                 Main.spriteBatch.Draw(value6, vector, value7, new Color(255, 255, 255, 0) * 0.1f, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
             }
         }
     }
References _specialTilesCount, _specialTileX, _specialTileY, Main.butterflyCageFrame, TileEntity.ByPosition, Color, Item.color, Main.critterCage, ItemSlot.DrawItemIcon(), TextureAssets.Extra, Tile.frameX, Tile.frameY, Item.GetColor(), Lighting.GetColor(), DrawAnimation.GetFrame(), Main.GetItemDrawFrame(), ItemSlot.GetItemLight(), GetWaterAnimalCageFrame(), Main.GlobalTimeWrappedHourly, TextureAssets.GlowMask, Main.hslToRgb(), Main.instance, Item.IsAir, ItemID.Sets.IsFood, TextureAssets.Item, Main.itemAnimations, Main.LoadItem(), Main.mouseTextColor, Item.netDefaults(), Item.Prefix(), Item.scale, Main.spriteBatch, Main.sunCircle, TextureAssets.SunOrb, Main.tile, Main.tileFrame, Item.type, Tile.type, and Asset< T >.Value.
Referenced by Draw().