Terraria: TileDrawing.GetTileDrawTexture
GetTileDrawTexture() [1/2]
Texture2D TileDrawing.GetTileDrawTexture (Tile tile, int tileX, int tileY) inline private
     {
         Texture2D result = TextureAssets.Tile[tile.type].Value;
         int tileStyle = 0;
         int num = tile.type;
         switch (tile.type)
         {
         case 5:
             tileStyle = GetTreeBiome(tileX, tileY, tile.frameX, tile.frameY);
             break;
         case 323:
             tileStyle = GetPalmTreeBiome(tileX, tileY);
             break;
         case 83:
             if (IsAlchemyPlantHarvestable(tile.frameX / 18))
             {
                 num = 84;
             }
             Main.instance.LoadTiles(num);
             break;
         }
         Texture2D texture2D = _paintSystem.TryGetTileAndRequestIfNotReady(num, tileStyle, tile.color());
         if (texture2D != null)
         {
             result = texture2D;
         }
         return result;
     }
References _paintSystem, Tile.color(), Tile.frameX, Tile.frameY, GetPalmTreeBiome(), GetTreeBiome(), Main.instance, IsAlchemyPlantHarvestable(), Main.LoadTiles(), TextureAssets.Tile, TilePaintSystemV2.TryGetTileAndRequestIfNotReady(), Tile.type, and Asset< T >.Value.
Referenced by DrawAnyDirectionalGrass(), DrawBasicTile(), DrawGrass(), DrawMultiTileGrassInWind(), DrawMultiTileVinesInWind(), DrawRisingVineStrip(), DrawSingleTile(), DrawTile_MinecartTrack(), and DrawVineStrip().