Terraria: TileDrawing.DrawVineStrip
DrawVineStrip()
void TileDrawing.DrawVineStrip (Vector2 screenPosition, Vector2 offSet, int x, int startY) inline private
     {
         int num = 0;
         int num2 = 0;
         Vector2 vector = new Vector2(x * 16 + 8, startY * 16 - 2);
         float amount = Math.Abs(Main.WindForVisuals) / 1.2f;
         amount = MathHelper.Lerp(0.2f, 1f, amount);
         float num3 = -0.08f * amount;
         float windCycle = GetWindCycle(x, startY, _vineWindCounter);
         float num4 = 0f;
         float num5 = 0f;
         for (int i = startY; i < Main.maxTilesY - 10; i++)
         {
             Tile tile = Main.tile[x, i];
             if (tile == null)
             {
                 continue;
             }
             ushort type = tile.type;
             if (!tile.active() || !TileID.Sets.VineThreads[type])
             {
                 break;
             }
             num++;
             if (num2 >= 5)
             {
                 num3 += 0.0075f * amount;
             }
             if (num2 >= 2)
             {
                 num3 += 0.0025f;
             }
             if (Main.remixWorld)
             {
                 if (WallID.Sets.AllowsWind[tile.wall] && (double)i > Main.worldSurface)
                 {
                     num2++;
                 }
             }
             else if (WallID.Sets.AllowsWind[tile.wall] && (double)i < Main.worldSurface)
             {
                 num2++;
             }
             float windGridPush = GetWindGridPush(x, i, 20, 0.01f);
             num4 = ((windGridPush != 0f || num5 == 0f) ? (num4 - windGridPush) : (num4 * -0.78f));
             num5 = windGridPush;
             short tileFrameX = tile.frameX;
             short tileFrameY = tile.frameY;
             Color color = Lighting.GetColor(x, i);
             GetTileDrawData(x, i, tile, type, ref tileFrameX, ref tileFrameY, out var tileWidth, out var tileHeight, out var tileTop, out var halfBrickHeight, out var addFrX, out var addFrY, out var tileSpriteEffect, out var glowTexture, out var glowSourceRect, out var glowColor);
             Vector2 position = new Vector2(-(int)screenPosition.X, -(int)screenPosition.Y) + offSet + vector;
             if (tile.fullbrightBlock())
             {
                 color = Color.White;
             }
             float num6 = (float)num2 * num3 * windCycle + num4;
             if (_localPlayer.biomeSight)
             {
                 Color sightColor = Color.White;
                 if (Main.IsTileBiomeSightable(type, tileFrameX, tileFrameY, ref sightColor))
                 {
                     if (color.R < sightColor.R)
                     {
                         color.R = sightColor.R;
                     }
                     if (color.G < sightColor.G)
                     {
                         color.G = sightColor.G;
                     }
                     if (color.B < sightColor.B)
                     {
                         color.B = sightColor.B;
                     }
                     if (_isActiveAndNotPaused && _rand.Next(480) == 0)
                     {
                         Color newColor = sightColor;
                         int num7 = Dust.NewDust(new Vector2(x * 16, i * 16), 16, 16, 267, 0f, 0f, 150, newColor, 0.3f);
                         _dust[num7].noGravity = true;
                         _dust[num7].fadeIn = 1f;
                         _dust[num7].velocity *= 0.1f;
                         _dust[num7].noLightEmittence = true;
                     }
                 }
             }
             Texture2D tileDrawTexture = GetTileDrawTexture(tile, x, i);
             if (tileDrawTexture == null)
             {
                 break;
             }
             if (IsVisible(tile))
             {
                 Main.spriteBatch.Draw(tileDrawTexture, position, new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), color, num6, new Vector2(tileWidth / 2, halfBrickHeight - tileTop), 1f, tileSpriteEffect, 0f);
                 if (glowTexture != null)
                 {
                     Main.spriteBatch.Draw(glowTexture, position, glowSourceRect, glowColor, num6, new Vector2(tileWidth / 2, halfBrickHeight - tileTop), 1f, tileSpriteEffect, 0f);
                 }
             }
             vector += (num6 + (float)Math.PI / 2f).ToRotationVector2() * 16f;
         }
     }
References _dust, _isActiveAndNotPaused, _localPlayer, _rand, _vineWindCounter, Tile.active(), WallID.Sets.AllowsWind, Player.biomeSight, Color, Dust.fadeIn, Tile.frameX, Tile.frameY, Tile.fullbrightBlock(), Lighting.GetColor(), GetTileDrawData(), GetTileDrawTexture(), GetWindCycle(), GetWindGridPush(), Main.IsTileBiomeSightable(), IsVisible(), Main.maxTilesY, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLightEmittence, Main.remixWorld, Main.spriteBatch, Main.tile, Tile.type, Dust.velocity, TileID.Sets.VineThreads, Tile.wall, Main.WindForVisuals, and Main.worldSurface.
Referenced by DrawVines().