Terraria: TileDrawing.DrawAnyDirectionalGrass
DrawAnyDirectionalGrass()
void TileDrawing.DrawAnyDirectionalGrass () inline private
     {
         Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
         Vector2 zero = Vector2.Zero;
         int num = 12;
         int num2 = _specialsCount[num];
         for (int i = 0; i < num2; i++)
         {
             Point point = _specialPositions[num][i];
             int x = point.X;
             int y = point.Y;
             Tile tile = Main.tile[x, y];
             if (tile == null || !tile.active() || !IsVisible(tile))
             {
                 continue;
             }
             ushort type = tile.type;
             short tileFrameX = tile.frameX;
             short tileFrameY = tile.frameY;
             GetTileDrawData(x, y, tile, type, ref tileFrameX, ref tileFrameY, out var tileWidth, out var tileHeight, out var tileTop, out var halfBrickHeight, out var addFrX, out var addFrY, out var tileSpriteEffect, out var glowTexture, out var _, out var glowColor);
             bool flag = _rand.Next(4) == 0;
             Color tileLight = Lighting.GetColor(x, y);
             DrawAnimatedTile_AdjustForVisionChangers(x, y, tile, type, tileFrameX, tileFrameY, ref tileLight, flag);
             tileLight = DrawTiles_GetLightOverride(y, x, tile, type, tileFrameX, tileFrameY, tileLight);
             if (_isActiveAndNotPaused && flag)
             {
                 DrawTiles_EmitParticles(y, x, tile, type, tileFrameX, tileFrameY, tileLight);
             }
             if (type == 83 && IsAlchemyPlantHarvestable(tileFrameX / 18))
             {
                 type = 84;
                 Main.instance.LoadTiles(type);
             }
             Vector2 position = new Vector2(x * 16 - (int)unscaledPosition.X, y * 16 - (int)unscaledPosition.Y) + zero;
             _ = _grassWindCounter;
             float num3 = GetWindCycle(x, y, _grassWindCounter);
             if (!WallID.Sets.AllowsWind[tile.wall])
             {
                 num3 = 0f;
             }
             if (!InAPlaceWithWind(x, y, 1, 1))
             {
                 num3 = 0f;
             }
             GetWindGridPush2Axis(x, y, 20, 0.35f, out var pushX, out var pushY);
             int num4 = 1;
             int num5 = 0;
             Vector2 origin = new Vector2(tileWidth / 2, 16 - halfBrickHeight - tileTop);
             switch (tileFrameY / 54)
             {
             case 0:
                 num4 = 1;
                 num5 = 0;
                 origin = new Vector2(tileWidth / 2, 16 - halfBrickHeight - tileTop);
                 position.X += 8f;
                 position.Y += 16f;
                 position.X += num3;
                 position.Y += Math.Abs(num3);
                 break;
             case 1:
                 num3 *= -1f;
                 num4 = -1;
                 num5 = 0;
                 origin = new Vector2(tileWidth / 2, -tileTop);
                 position.X += 8f;
                 position.X += 0f - num3;
                 position.Y += 0f - Math.Abs(num3);
                 break;
             case 2:
                 num4 = 0;
                 num5 = 1;
                 origin = new Vector2(2f, (16 - halfBrickHeight - tileTop) / 2);
                 position.Y += 8f;
                 position.Y += num3;
                 position.X += 0f - Math.Abs(num3);
                 break;
             case 3:
                 num3 *= -1f;
                 num4 = 0;
                 num5 = -1;
                 origin = new Vector2(14f, (16 - halfBrickHeight - tileTop) / 2);
                 position.X += 16f;
                 position.Y += 8f;
                 position.Y += 0f - num3;
                 position.X += Math.Abs(num3);
                 break;
             }
             num3 += pushX * (float)num4 + pushY * (float)num5;
             Texture2D tileDrawTexture = GetTileDrawTexture(tile, x, y);
             if (tileDrawTexture != null)
             {
                 Main.spriteBatch.Draw(tileDrawTexture, position, new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), tileLight, num3 * 0.1f, origin, 1f, tileSpriteEffect, 0f);
                 if (glowTexture != null)
                 {
                     Main.spriteBatch.Draw(glowTexture, position, new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), glowColor, num3 * 0.1f, origin, 1f, tileSpriteEffect, 0f);
                 }
             }
         }
     }
References _grassWindCounter, _isActiveAndNotPaused, _rand, _specialPositions, _specialsCount, Tile.active(), WallID.Sets.AllowsWind, Main.Camera, Color, DrawAnimatedTile_AdjustForVisionChangers(), DrawTiles_EmitParticles(), DrawTiles_GetLightOverride(), Tile.frameX, Tile.frameY, Lighting.GetColor(), GetTileDrawData(), GetTileDrawTexture(), GetWindCycle(), GetWindGridPush2Axis(), InAPlaceWithWind(), Main.instance, IsAlchemyPlantHarvestable(), IsVisible(), Main.LoadTiles(), UnifiedRandom.Next(), Main.spriteBatch, Main.tile, Tile.type, Camera.UnscaledPosition, and Tile.wall.
Referenced by PostDrawTiles().