Terraria: TileDrawing.PrepareForAreaDrawing
PrepareForAreaDrawing()
void TileDrawing.PrepareForAreaDrawing (int firstTileX, int lastTileX, int firstTileY, int lastTileY, bool prepareLazily) inline
     {
         TilePaintSystemV2.TileVariationkey lookupKey = default(TilePaintSystemV2.TileVariationkey);
         TilePaintSystemV2.WallVariationKey lookupKey2 = default(TilePaintSystemV2.WallVariationKey);
         for (int i = firstTileY; i < lastTileY + 4; i++)
         {
             for (int j = firstTileX - 2; j < lastTileX + 2; j++)
             {
                 Tile tile = Main.tile[j, i];
                 if (tile == null)
                 {
                     continue;
                 }
                 if (tile.active())
                 {
                     Main.instance.LoadTiles(tile.type);
                     lookupKey.TileType = tile.type;
                     lookupKey.PaintColor = tile.color();
                     int tileStyle = 0;
                     switch (tile.type)
                     {
                     case 5:
                         tileStyle = GetTreeBiome(j, i, tile.frameX, tile.frameY);
                         break;
                     case 323:
                         tileStyle = GetPalmTreeBiome(j, i);
                         break;
                     }
                     lookupKey.TileStyle = tileStyle;
                     if (lookupKey.PaintColor != 0)
                     {
                         _paintSystem.RequestTile(ref lookupKey);
                     }
                 }
                 if (tile.wall != 0)
                 {
                     Main.instance.LoadWall(tile.wall);
                     lookupKey2.WallType = tile.wall;
                     lookupKey2.PaintColor = tile.wallColor();
                     if (lookupKey2.PaintColor != 0)
                     {
                         _paintSystem.RequestWall(ref lookupKey2);
                     }
                 }
                 if (!prepareLazily)
                 {
                     MakeExtraPreparations(tile, j, i);
                 }
             }
         }
     }
References _paintSystem, Tile.active(), Tile.color(), Tile.frameX, Tile.frameY, GetPalmTreeBiome(), GetTreeBiome(), Main.instance, Main.LoadTiles(), Main.LoadWall(), MakeExtraPreparations(), TilePaintSystemV2.RequestTile(), TilePaintSystemV2.RequestWall(), Main.tile, Tile.type, Tile.wall, and Tile.wallColor().
Referenced by CaptureCamera.DrawTick(), and PreparePaintForTilesOnScreen().