Terraria: TileDrawing.DrawMultiTileGrass
DrawMultiTileGrass()
void TileDrawing.DrawMultiTileGrass () inline private
     {
         Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
         Vector2 zero = Vector2.Zero;
         int num = 4;
         int num2 = _specialsCount[num];
         for (int i = 0; i < num2; i++)
         {
             Point point = _specialPositions[num][i];
             int x = point.X;
             int num3 = point.Y;
             int sizeX = 1;
             int num4 = 1;
             Tile tile = Main.tile[x, num3];
             if (tile != null && tile.active())
             {
                 switch (Main.tile[x, num3].type)
                 {
                 case 27:
                     sizeX = 2;
                     num4 = 5;
                     break;
                 case 236:
                 case 238:
                     sizeX = (num4 = 2);
                     break;
                 case 233:
                     sizeX = ((Main.tile[x, num3].frameY != 0) ? 2 : 3);
                     num4 = 2;
                     break;
                 case 530:
                 case 651:
                     sizeX = 3;
                     num4 = 2;
                     break;
                 case 485:
                 case 490:
                 case 521:
                 case 522:
                 case 523:
                 case 524:
                 case 525:
                 case 526:
                 case 527:
                 case 652:
                     sizeX = 2;
                     num4 = 2;
                     break;
                 case 489:
                     sizeX = 2;
                     num4 = 3;
                     break;
                 case 493:
                     sizeX = 1;
                     num4 = 2;
                     break;
                 case 519:
                     sizeX = 1;
                     num4 = ClimbCatTail(x, num3);
                     num3 -= num4 - 1;
                     break;
                 }
                 DrawMultiTileGrassInWind(unscaledPosition, zero, x, num3, sizeX, num4);
             }
         }
     }
References _specialPositions, _specialsCount, Tile.active(), Main.Camera, ClimbCatTail(), DrawMultiTileGrassInWind(), Tile.frameY, Main.tile, Tile.type, and Camera.UnscaledPosition.
Referenced by PostDrawTiles().