Terraria: TileDrawing.GetWindCycle
GetWindCycle()
float TileDrawing.GetWindCycle (int x, int y, double windCounter) inline private
     {
         if (!Main.SettingsEnabled_TilesSwayInWind)
         {
             return 0f;
         }
         float num = (float)x * 0.5f + (float)(y / 100) * 0.5f;
         float num2 = (float)Math.Cos(windCounter * 6.2831854820251465 + (double)num) * 0.5f;
         if (Main.remixWorld)
         {
             if (!((double)y > Main.worldSurface))
             {
                 return 0f;
             }
             num2 += Main.WindForVisuals;
         }
         else
         {
             if (!((double)y < Main.worldSurface))
             {
                 return 0f;
             }
             num2 += Main.WindForVisuals;
         }
         float lerpValue = Utils.GetLerpValue(0.08f, 0.18f, Math.Abs(Main.WindForVisuals), clamped: true);
         return num2 * lerpValue;
     }
References Utils.GetLerpValue(), Main.remixWorld, Main.SettingsEnabled_TilesSwayInWind, Main.WindForVisuals, and Main.worldSurface.
Referenced by DrawAnyDirectionalGrass(), DrawGrass(), DrawMultiTileGrassInWind(), DrawMultiTileVinesInWind(), DrawRisingVineStrip(), DrawTrees(), and DrawVineStrip().