Terraria: TileDrawing.GetTileDrawData
GetTileDrawData()
void TileDrawing.GetTileDrawData (int x, int y, Tile tileCache, ushort typeCache, ref short tileFrameX, ref short tileFrameY, out int tileWidth, out int tileHeight, out int tileTop, out int halfBrickHeight, out int addFrX, out int addFrY, out SpriteEffects tileSpriteEffect, out Texture2D glowTexture, out Rectangle glowSourceRect, out Color glowColor) inline private
     {
         tileTop = 0;
         tileWidth = 16;
         tileHeight = 16;
         halfBrickHeight = 0;
         addFrY = Main.tileFrame[typeCache] * 38;
         addFrX = 0;
         tileSpriteEffect = SpriteEffects.None;
         glowTexture = null;
         glowSourceRect = Rectangle.Empty;
         glowColor = Color.Transparent;
         Color color = Lighting.GetColor(x, y);
         switch (typeCache)
         {
         case 443:
             if (tileFrameX / 36 >= 2)
             {
                 tileTop = -2;
             }
             else
             {
                 tileTop = 2;
             }
             break;
         case 571:
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             tileTop = 2;
             break;
         case 136:
             if (tileFrameX == 0)
             {
                 tileTop = 2;
             }
             break;
         case 561:
             tileTop -= 2;
             tileHeight = 20;
             addFrY = tileFrameY / 18 * 4;
             break;
         case 518:
         {
             int num27 = tileCache.liquid / 16;
             num27 -= 3;
             if (WorldGen.SolidTile(x, y - 1) && num27 > 8)
             {
                 num27 = 8;
             }
             if (tileCache.liquid == 0)
             {
                 Tile tileSafely = Framing.GetTileSafely(x, y + 1);
                 if (tileSafely.nactive())
                 {
                     switch (tileSafely.blockType())
                     {
                     case 1:
                         num27 = -16 + Math.Max(8, tileSafely.liquid / 16);
                         break;
                     case 2:
                     case 3:
                         num27 -= 4;
                         break;
                     }
                 }
             }
             tileTop -= num27;
             break;
         }
         case 330:
         case 331:
         case 332:
         case 333:
             tileTop += 2;
             break;
         case 129:
             addFrY = 0;
             if (tileFrameX >= 324)
             {
                 int num22 = (tileFrameX - 324) / 18;
                 int num23 = (num22 + Main.tileFrame[typeCache]) % 6 - num22;
                 addFrX = num23 * 18;
             }
             break;
         case 5:
         {
             tileWidth = 20;
             tileHeight = 20;
             int treeBiome = GetTreeBiome(x, y, tileFrameX, tileFrameY);
             tileFrameX += (short)(176 * (treeBiome + 1));
             break;
         }
         case 583:
         case 584:
         case 585:
         case 586:
         case 587:
         case 588:
         case 589:
         case 596:
         case 616:
         case 634:
             tileWidth = 20;
             tileHeight = 20;
             break;
         case 476:
             tileWidth = 20;
             tileHeight = 18;
             break;
         case 323:
         {
             tileWidth = 20;
             tileHeight = 20;
             int palmTreeBiome = GetPalmTreeBiome(x, y);
             tileFrameY = (short)(22 * palmTreeBiome);
             break;
         }
         case 4:
             tileWidth = 20;
             tileHeight = 20;
             if (WorldGen.SolidTile(x, y - 1))
             {
                 tileTop = 4;
             }
             break;
         case 78:
         case 85:
         case 100:
         case 133:
         case 134:
         case 173:
         case 210:
         case 233:
         case 254:
         case 283:
         case 378:
         case 457:
         case 466:
         case 520:
         case 651:
         case 652:
             tileTop = 2;
             break;
         case 530:
         {
             int num48 = y - tileFrameY % 36 / 18 + 2;
             int num49 = x - tileFrameX % 54 / 18;
             WorldGen.GetBiomeInfluence(num49, num49 + 3, num48, num48, out var corruptCount2, out var crimsonCount2, out var hallowedCount2);
             int num50 = corruptCount2;
             if (num50 < crimsonCount2)
             {
                 num50 = crimsonCount2;
             }
             if (num50 < hallowedCount2)
             {
                 num50 = hallowedCount2;
             }
             int num51 = 0;
             num51 = ((corruptCount2 != 0 || crimsonCount2 != 0 || hallowedCount2 != 0) ? ((hallowedCount2 == num50) ? 1 : ((crimsonCount2 != num50) ? 3 : 2)) : 0);
             addFrY += 36 * num51;
             tileTop = 2;
             break;
         }
         case 485:
         {
             tileTop = 2;
             int num39 = Main.tileFrameCounter[typeCache];
             num39 /= 5;
             int num40 = y - tileFrameY / 18;
             int num41 = x - tileFrameX / 18;
             num39 += num40 + num41;
             num39 %= 4;
             addFrY = num39 * 36;
             break;
         }
         case 489:
         {
             tileTop = 2;
             int num28 = y - tileFrameY / 18;
             int num29 = x - tileFrameX / 18;
             if (InAPlaceWithWind(num29, num28, 2, 3))
             {
                 int num30 = Main.tileFrameCounter[typeCache];
                 num30 /= 5;
                 num30 += num28 + num29;
                 num30 %= 16;
                 addFrY = num30 * 54;
             }
             break;
         }
         case 490:
         {
             tileTop = 2;
             int y2 = y - tileFrameY / 18;
             int x2 = x - tileFrameX / 18;
             bool num24 = InAPlaceWithWind(x2, y2, 2, 2);
             int num25 = (num24 ? Main.tileFrame[typeCache] : 0);
             int num26 = 0;
             if (num24)
             {
                 if (Math.Abs(Main.WindForVisuals) > 0.5f)
                 {
                     switch (Main.weatherVaneBobframe)
                     {
                     case 0:
                         num26 = 0;
                         break;
                     case 1:
                         num26 = 1;
                         break;
                     case 2:
                         num26 = 2;
                         break;
                     case 3:
                         num26 = 1;
                         break;
                     case 4:
                         num26 = 0;
                         break;
                     case 5:
                         num26 = -1;
                         break;
                     case 6:
                         num26 = -2;
                         break;
                     case 7:
                         num26 = -1;
                         break;
                     }
                 }
                 else
                 {
                     switch (Main.weatherVaneBobframe)
                     {
                     case 0:
                         num26 = 0;
                         break;
                     case 1:
                         num26 = 1;
                         break;
                     case 2:
                         num26 = 0;
                         break;
                     case 3:
                         num26 = -1;
                         break;
                     case 4:
                         num26 = 0;
                         break;
                     case 5:
                         num26 = 1;
                         break;
                     case 6:
                         num26 = 0;
                         break;
                     case 7:
                         num26 = -1;
                         break;
                     }
                 }
             }
             num25 += num26;
             if (num25 < 0)
             {
                 num25 += 12;
             }
             num25 %= 12;
             addFrY = num25 * 36;
             break;
         }
         case 33:
         case 49:
         case 174:
         case 372:
         case 646:
             tileHeight = 20;
             tileTop = -4;
             break;
         case 529:
         {
             int num18 = y + 1;
             WorldGen.GetBiomeInfluence(x, x, num18, num18, out var corruptCount, out var crimsonCount, out var hallowedCount);
             int num19 = corruptCount;
             if (num19 < crimsonCount)
             {
                 num19 = crimsonCount;
             }
             if (num19 < hallowedCount)
             {
                 num19 = hallowedCount;
             }
             int num20 = 0;
             num20 = ((corruptCount == 0 && crimsonCount == 0 && hallowedCount == 0) ? ((x < WorldGen.beachDistance || x > Main.maxTilesX - WorldGen.beachDistance) ? 1 : 0) : ((hallowedCount == num19) ? 2 : ((crimsonCount != num19) ? 4 : 3)));
             addFrY += 34 * num20 - tileFrameY;
             tileHeight = 32;
             tileTop = -14;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         }
         case 3:
         case 24:
         case 61:
         case 71:
         case 110:
         case 201:
         case 637:
             tileHeight = 20;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 20:
         case 590:
         case 595:
             tileHeight = 18;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 615:
             tileHeight = 18;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 16:
         case 17:
         case 18:
         case 26:
         case 32:
         case 69:
         case 72:
         case 77:
         case 79:
         case 124:
         case 137:
         case 138:
         case 352:
         case 462:
         case 487:
         case 488:
         case 574:
         case 575:
         case 576:
         case 577:
         case 578:
         case 664:
             tileHeight = 18;
             break;
         case 654:
             tileTop += 2;
             break;
         case 14:
         case 21:
         case 411:
         case 467:
         case 469:
             if (tileFrameY == 18)
             {
                 tileHeight = 18;
             }
             break;
         case 15:
         case 497:
             if (tileFrameY % 40 == 18)
             {
                 tileHeight = 18;
             }
             break;
         case 172:
         case 376:
             if (tileFrameY % 38 == 18)
             {
                 tileHeight = 18;
             }
             break;
         case 27:
             if (tileFrameY % 74 == 54)
             {
                 tileHeight = 18;
             }
             break;
         case 132:
         case 135:
             tileTop = 2;
             tileHeight = 18;
             break;
         case 82:
         case 83:
         case 84:
             tileHeight = 20;
             tileTop = -2;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 324:
             tileWidth = 20;
             tileHeight = 20;
             tileTop = -2;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 494:
             tileTop = 2;
             break;
         case 52:
         case 62:
         case 115:
         case 205:
         case 382:
         case 528:
         case 636:
         case 638:
             tileTop = -2;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 80:
         case 142:
         case 143:
             tileTop = 2;
             break;
         case 139:
         {
             tileTop = 2;
             int num31 = tileFrameY / 2016;
             addFrY -= 2016 * num31;
             addFrX += 72 * num31;
             break;
         }
         case 73:
         case 74:
         case 113:
             tileTop = -12;
             tileHeight = 32;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 388:
         case 389:
         {
             TileObjectData.GetTileData(typeCache, tileFrameX / 18);
             int num17 = 94;
             tileTop = -2;
             if (tileFrameY == num17 - 20 || tileFrameY == num17 * 2 - 20 || tileFrameY == 0 || tileFrameY == num17)
             {
                 tileHeight = 18;
             }
             if (tileFrameY != 0 && tileFrameY != num17)
             {
                 tileTop = 0;
             }
             break;
         }
         case 227:
             tileWidth = 32;
             tileHeight = 38;
             if (tileFrameX == 238)
             {
                 tileTop -= 6;
             }
             else
             {
                 tileTop -= 20;
             }
             if (tileFrameX == 204)
             {
                 WorldGen.GetCactusType(x, y, tileFrameX, tileFrameY, out var evil, out var good, out var crimson);
                 if (good)
                 {
                     tileFrameX += 238;
                 }
                 if (evil)
                 {
                     tileFrameX += 204;
                 }
                 if (crimson)
                 {
                     tileFrameX += 272;
                 }
             }
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 624:
             tileWidth = 20;
             tileHeight = 16;
             tileTop += 2;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 656:
             tileWidth = 24;
             tileHeight = 34;
             tileTop -= 16;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 579:
         {
             tileWidth = 20;
             tileHeight = 20;
             tileTop -= 2;
             bool flag = (float)(x * 16 + 8) > Main.LocalPlayer.Center.X;
             if (tileFrameX > 0)
             {
                 if (flag)
                 {
                     addFrY = 22;
                 }
                 else
                 {
                     addFrY = 0;
                 }
             }
             else if (flag)
             {
                 addFrY = 0;
             }
             else
             {
                 addFrY = 22;
             }
             break;
         }
         case 567:
             tileWidth = 26;
             tileHeight = 18;
             if (tileFrameY == 0)
             {
                 tileTop = -2;
             }
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 185:
         case 186:
         case 187:
             tileTop = 2;
             switch (typeCache)
             {
             case 185:
                 if (tileFrameY == 18 && tileFrameX >= 576 && tileFrameX <= 882)
                 {
                     Main.tileShine2[185] = true;
                 }
                 else
                 {
                     Main.tileShine2[185] = false;
                 }
                 if (tileFrameY == 18)
                 {
                     int num37 = tileFrameX / 1908;
                     addFrX -= 1908 * num37;
                     addFrY += 18 * num37;
                 }
                 break;
             case 186:
                 if (tileFrameX >= 864 && tileFrameX <= 1170)
                 {
                     Main.tileShine2[186] = true;
                 }
                 else
                 {
                     Main.tileShine2[186] = false;
                 }
                 break;
             case 187:
             {
                 int num36 = tileFrameX / 1890;
                 addFrX -= 1890 * num36;
                 addFrY += 36 * num36;
                 break;
             }
             }
             break;
         case 650:
             tileTop = 2;
             break;
         case 649:
         {
             tileTop = 2;
             int num35 = tileFrameX / 1908;
             addFrX -= 1908 * num35;
             addFrY += 18 * num35;
             break;
         }
         case 647:
             tileTop = 2;
             break;
         case 648:
         {
             tileTop = 2;
             int num34 = tileFrameX / 1890;
             addFrX -= 1890 * num34;
             addFrY += 36 * num34;
             break;
         }
         case 178:
             if (tileFrameY <= 36)
             {
                 tileTop = 2;
             }
             break;
         case 184:
             tileWidth = 20;
             if (tileFrameY <= 36)
             {
                 tileTop = 2;
             }
             else if (tileFrameY <= 108)
             {
                 tileTop = -2;
             }
             break;
         case 519:
             tileTop = 2;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 493:
             if (tileFrameY == 0)
             {
                 int num13 = Main.tileFrameCounter[typeCache];
                 float num14 = Math.Abs(Main.WindForVisuals);
                 int num15 = y - tileFrameY / 18;
                 int num16 = x - tileFrameX / 18;
                 if (!InAPlaceWithWind(x, num15, 1, 1))
                 {
                     num14 = 0f;
                 }
                 if (!(num14 < 0.1f))
                 {
                     if (num14 < 0.5f)
                     {
                         num13 /= 20;
                         num13 += num15 + num16;
                         num13 %= 6;
                         num13 = ((!(Main.WindForVisuals < 0f)) ? (num13 + 1) : (6 - num13));
                         addFrY = num13 * 36;
                     }
                     else
                     {
                         num13 /= 10;
                         num13 += num15 + num16;
                         num13 %= 6;
                         num13 = ((!(Main.WindForVisuals < 0f)) ? (num13 + 7) : (12 - num13));
                         addFrY = num13 * 36;
                     }
                 }
             }
             tileTop = 2;
             break;
         case 28:
         case 105:
         case 470:
         case 475:
         case 506:
         case 547:
         case 548:
         case 552:
         case 560:
         case 597:
         case 613:
         case 621:
         case 622:
         case 623:
         case 653:
             tileTop = 2;
             break;
         case 617:
             tileTop = 2;
             tileFrameY %= 144;
             tileFrameX %= 54;
             break;
         case 614:
             addFrX = Main.tileFrame[typeCache] * 54;
             addFrY = 0;
             tileTop = 2;
             break;
         case 81:
             tileTop -= 8;
             tileHeight = 26;
             tileWidth = 24;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         case 272:
             addFrY = 0;
             break;
         case 106:
             addFrY = Main.tileFrame[typeCache] * 54;
             break;
         case 300:
         case 301:
         case 302:
         case 303:
         case 304:
         case 305:
         case 306:
         case 307:
         case 308:
         case 354:
         case 355:
         case 499:
             addFrY = Main.tileFrame[typeCache] * 54;
             tileTop = 2;
             break;
         case 377:
             addFrY = Main.tileFrame[typeCache] * 38;
             tileTop = 2;
             break;
         case 463:
         case 464:
             addFrY = Main.tileFrame[typeCache] * 72;
             tileTop = 2;
             break;
         case 491:
             tileTop = 2;
             addFrX = 54;
             break;
         case 379:
             addFrY = Main.tileFrame[typeCache] * 90;
             break;
         case 349:
         {
             tileTop = 2;
             int num6 = tileFrameX % 36;
             int num7 = tileFrameY % 54;
             if (Animation.GetTemporaryFrame(x - num6 / 18, y - num7 / 18, out var frameData2))
             {
                 tileFrameX = (short)(36 * frameData2 + num6);
             }
             break;
         }
         case 441:
         case 468:
         {
             if (tileFrameY == 18)
             {
                 tileHeight = 18;
             }
             int num3 = tileFrameX % 36;
             int num4 = tileFrameY % 38;
             if (Animation.GetTemporaryFrame(x - num3 / 18, y - num4 / 18, out var frameData))
             {
                 tileFrameY = (short)(38 * frameData + num4);
             }
             break;
         }
         case 390:
             addFrY = Main.tileFrame[typeCache] * 36;
             break;
         case 412:
             addFrY = 0;
             tileTop = 2;
             break;
         case 406:
         {
             tileHeight = 16;
             if (tileFrameY % 54 >= 36)
             {
                 tileHeight = 18;
             }
             int num53 = Main.tileFrame[typeCache];
             if (tileFrameY >= 108)
             {
                 num53 = 6 - tileFrameY / 54;
             }
             else if (tileFrameY >= 54)
             {
                 num53 = Main.tileFrame[typeCache] - 1;
             }
             addFrY = num53 * 56;
             addFrY += tileFrameY / 54 * 2;
             break;
         }
         case 452:
         {
             int num52 = Main.tileFrame[typeCache];
             if (tileFrameX >= 54)
             {
                 num52 = 0;
             }
             addFrY = num52 * 54;
             break;
         }
         case 455:
         {
             addFrY = 0;
             tileTop = 2;
             int num47 = 1 + Main.tileFrame[typeCache];
             if (!BirthdayParty.PartyIsUp)
             {
                 num47 = 0;
             }
             addFrY = num47 * 54;
             break;
         }
         case 454:
             addFrY = Main.tileFrame[typeCache] * 54;
             break;
         case 453:
         {
             int num45 = Main.tileFrameCounter[typeCache];
             num45 /= 20;
             int num46 = y - tileFrameY / 18;
             num45 += num46 + x;
             num45 %= 3;
             addFrY = num45 * 54;
             break;
         }
         case 456:
         {
             int num42 = Main.tileFrameCounter[typeCache];
             num42 /= 20;
             int num43 = y - tileFrameY / 18;
             int num44 = x - tileFrameX / 18;
             num42 += num43 + num44;
             num42 %= 4;
             addFrY = num42 * 54;
             break;
         }
         case 405:
         {
             tileHeight = 16;
             if (tileFrameY > 0)
             {
                 tileHeight = 18;
             }
             int num38 = Main.tileFrame[typeCache];
             if (tileFrameX >= 54)
             {
                 num38 = 0;
             }
             addFrY = num38 * 38;
             break;
         }
         case 12:
         case 31:
         case 96:
         case 639:
         case 665:
             addFrY = Main.tileFrame[typeCache] * 36;
             break;
         case 238:
             tileTop = 2;
             addFrY = Main.tileFrame[typeCache] * 36;
             break;
         case 593:
         {
             if (tileFrameX >= 18)
             {
                 addFrX = -18;
             }
             tileTop = 2;
             if (Animation.GetTemporaryFrame(x, y, out var frameData4))
             {
                 addFrY = (short)(18 * frameData4);
             }
             else if (tileFrameX < 18)
             {
                 addFrY = Main.tileFrame[typeCache] * 18;
             }
             else
             {
                 addFrY = 0;
             }
             break;
         }
         case 594:
         {
             if (tileFrameX >= 36)
             {
                 addFrX = -36;
             }
             tileTop = 2;
             int num32 = tileFrameX % 36;
             int num33 = tileFrameY % 36;
             if (Animation.GetTemporaryFrame(x - num32 / 18, y - num33 / 18, out var frameData3))
             {
                 addFrY = (short)(36 * frameData3);
             }
             else if (tileFrameX < 36)
             {
                 addFrY = Main.tileFrame[typeCache] * 36;
             }
             else
             {
                 addFrY = 0;
             }
             break;
         }
         case 215:
             if (tileFrameY < 36)
             {
                 addFrY = Main.tileFrame[typeCache] * 36;
             }
             else
             {
                 addFrY = 252;
             }
             tileTop = 2;
             break;
         case 592:
             addFrY = Main.tileFrame[typeCache] * 54;
             break;
         case 228:
         case 231:
         case 243:
         case 247:
             tileTop = 2;
             addFrY = Main.tileFrame[typeCache] * 54;
             break;
         case 244:
             tileTop = 2;
             if (tileFrameX < 54)
             {
                 addFrY = Main.tileFrame[typeCache] * 36;
             }
             else
             {
                 addFrY = 0;
             }
             break;
         case 565:
             tileTop = 2;
             if (tileFrameX < 36)
             {
                 addFrY = Main.tileFrame[typeCache] * 36;
             }
             else
             {
                 addFrY = 0;
             }
             break;
         case 235:
             addFrY = Main.tileFrame[typeCache] * 18;
             break;
         case 217:
         case 218:
         case 564:
             addFrY = Main.tileFrame[typeCache] * 36;
             tileTop = 2;
             break;
         case 219:
         case 220:
         case 642:
             addFrY = Main.tileFrame[typeCache] * 54;
             tileTop = 2;
             break;
         case 270:
         case 271:
         case 581:
         {
             int num21 = Main.tileFrame[typeCache] + x % 6;
             if (x % 2 == 0)
             {
                 num21 += 3;
             }
             if (x % 3 == 0)
             {
                 num21 += 3;
             }
             if (x % 4 == 0)
             {
                 num21 += 3;
             }
             while (num21 > 5)
             {
                 num21 -= 6;
             }
             addFrX = num21 * 18;
             addFrY = 0;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         }
         case 660:
         {
             int num12 = Main.tileFrame[typeCache] + x % 5;
             if (x % 2 == 0)
             {
                 num12 += 3;
             }
             if (x % 3 == 0)
             {
                 num12 += 3;
             }
             if (x % 4 == 0)
             {
                 num12 += 3;
             }
             while (num12 > 4)
             {
                 num12 -= 5;
             }
             addFrX = num12 * 18;
             addFrY = 0;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         }
         case 572:
         {
             int num11;
             for (num11 = Main.tileFrame[typeCache] + x % 4; num11 > 3; num11 -= 4)
             {
             }
             addFrX = num11 * 18;
             addFrY = 0;
             if (x % 2 == 0)
             {
                 tileSpriteEffect = SpriteEffects.FlipHorizontally;
             }
             break;
         }
         case 428:
             tileTop += 4;
             if (PressurePlateHelper.PressurePlatesPressed.ContainsKey(new Point(x, y)))
             {
                 addFrX += 18;
             }
             break;
         case 442:
             tileWidth = 20;
             tileHeight = 20;
             switch (tileFrameX / 22)
             {
             case 1:
                 tileTop = -4;
                 break;
             case 2:
                 tileTop = -2;
                 tileWidth = 24;
                 break;
             case 3:
                 tileTop = -2;
                 break;
             }
             break;
         case 426:
         case 430:
         case 431:
         case 432:
         case 433:
         case 434:
             addFrY = 90;
             break;
         case 275:
         case 276:
         case 277:
         case 278:
         case 279:
         case 280:
         case 281:
         case 296:
         case 297:
         case 309:
         case 358:
         case 359:
         case 413:
         case 414:
         case 542:
         case 550:
         case 551:
         case 553:
         case 554:
         case 558:
         case 559:
         case 599:
         case 600:
         case 601:
         case 602:
         case 603:
         case 604:
         case 605:
         case 606:
         case 607:
         case 608:
         case 609:
         case 610:
         case 611:
         case 612:
         case 632:
         case 640:
         case 643:
         case 644:
         case 645:
         {
             tileTop = 2;
             Main.critterCage = true;
             int bigAnimalCageFrame = GetBigAnimalCageFrame(x, y, tileFrameX, tileFrameY);
             switch (typeCache)
             {
             case 275:
             case 359:
             case 599:
             case 600:
             case 601:
             case 602:
             case 603:
             case 604:
             case 605:
                 addFrY = Main.bunnyCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 550:
             case 551:
                 addFrY = Main.turtleCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 542:
                 addFrY = Main.owlCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 276:
             case 413:
             case 414:
             case 606:
             case 607:
             case 608:
             case 609:
             case 610:
             case 611:
             case 612:
                 addFrY = Main.squirrelCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 277:
                 addFrY = Main.mallardCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 278:
                 addFrY = Main.duckCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 553:
                 addFrY = Main.grebeCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 554:
                 addFrY = Main.seagullCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 279:
             case 358:
                 addFrY = Main.birdCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 280:
                 addFrY = Main.blueBirdCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 281:
                 addFrY = Main.redBirdCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 632:
             case 640:
             case 643:
             case 644:
             case 645:
                 addFrY = Main.macawCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 296:
             case 297:
                 addFrY = Main.scorpionCageFrame[0, bigAnimalCageFrame] * 54;
                 break;
             case 309:
                 addFrY = Main.penguinCageFrame[bigAnimalCageFrame] * 54;
                 break;
             case 558:
             case 559:
                 addFrY = Main.seahorseCageFrame[bigAnimalCageFrame] * 54;
                 break;
             }
             break;
         }
         case 285:
         case 286:
         case 298:
         case 299:
         case 310:
         case 339:
         case 361:
         case 362:
         case 363:
         case 364:
         case 391:
         case 392:
         case 393:
         case 394:
         case 532:
         case 533:
         case 538:
         case 544:
         case 555:
         case 556:
         case 582:
         case 619:
         case 629:
         {
             tileTop = 2;
             Main.critterCage = true;
             int smallAnimalCageFrame2 = GetSmallAnimalCageFrame(x, y, tileFrameX, tileFrameY);
             switch (typeCache)
             {
             case 285:
                 addFrY = Main.snailCageFrame[smallAnimalCageFrame2] * 36;
                 break;
             case 286:
             case 582:
                 addFrY = Main.snail2CageFrame[smallAnimalCageFrame2] * 36;
                 break;
             case 298:
             case 361:
                 addFrY = Main.frogCageFrame[smallAnimalCageFrame2] * 36;
                 break;
             case 339:
             case 362:
                 addFrY = Main.grasshopperCageFrame[smallAnimalCageFrame2] * 36;
                 break;
             case 299:
             case 363:
                 addFrY = Main.mouseCageFrame[smallAnimalCageFrame2] * 36;
                 break;
             case 310:
             case 364:
             case 391:
             case 619:
                 addFrY = Main.wormCageFrame[smallAnimalCageFrame2] * 36;
                 break;
             case 392:
             case 393:
             case 394:
                 addFrY = Main.slugCageFrame[typeCache - 392, smallAnimalCageFrame2] * 36;
                 break;
             case 532:
                 addFrY = Main.maggotCageFrame[smallAnimalCageFrame2] * 36;
                 break;
             case 533:
                 addFrY = Main.ratCageFrame[smallAnimalCageFrame2] * 36;
                 break;
             case 538:
             case 544:
             case 629:
                 addFrY = Main.ladybugCageFrame[smallAnimalCageFrame2] * 36;
                 break;
             case 555:
             case 556:
                 addFrY = Main.waterStriderCageFrame[smallAnimalCageFrame2] * 36;
                 break;
             }
             break;
         }
         case 282:
         case 505:
         case 543:
         {
             tileTop = 2;
             Main.critterCage = true;
             int waterAnimalCageFrame5 = GetWaterAnimalCageFrame(x, y, tileFrameX, tileFrameY);
             addFrY = Main.fishBowlFrame[waterAnimalCageFrame5] * 36;
             break;
         }
         case 598:
         {
             tileTop = 2;
             Main.critterCage = true;
             int waterAnimalCageFrame4 = GetWaterAnimalCageFrame(x, y, tileFrameX, tileFrameY);
             addFrY = Main.lavaFishBowlFrame[waterAnimalCageFrame4] * 36;
             break;
         }
         case 568:
         case 569:
         case 570:
         {
             tileTop = 2;
             Main.critterCage = true;
             int waterAnimalCageFrame3 = GetWaterAnimalCageFrame(x, y, tileFrameX, tileFrameY);
             addFrY = Main.fairyJarFrame[waterAnimalCageFrame3] * 36;
             break;
         }
         case 288:
         case 289:
         case 290:
         case 291:
         case 292:
         case 293:
         case 294:
         case 295:
         case 360:
         case 580:
         case 620:
         {
             tileTop = 2;
             Main.critterCage = true;
             int waterAnimalCageFrame2 = GetWaterAnimalCageFrame(x, y, tileFrameX, tileFrameY);
             int num10 = typeCache - 288;
             if (typeCache == 360 || typeCache == 580 || typeCache == 620)
             {
                 num10 = 8;
             }
             addFrY = Main.butterflyCageFrame[num10, waterAnimalCageFrame2] * 36;
             break;
         }
         case 521:
         case 522:
         case 523:
         case 524:
         case 525:
         case 526:
         case 527:
         {
             tileTop = 2;
             Main.critterCage = true;
             int waterAnimalCageFrame = GetWaterAnimalCageFrame(x, y, tileFrameX, tileFrameY);
             int num9 = typeCache - 521;
             addFrY = Main.dragonflyJarFrame[num9, waterAnimalCageFrame] * 36;
             break;
         }
         case 316:
         case 317:
         case 318:
         {
             tileTop = 2;
             Main.critterCage = true;
             int smallAnimalCageFrame = GetSmallAnimalCageFrame(x, y, tileFrameX, tileFrameY);
             int num8 = typeCache - 316;
             addFrY = Main.jellyfishCageFrame[num8, smallAnimalCageFrame] * 36;
             break;
         }
         case 207:
             tileTop = 2;
             if (tileFrameY >= 72)
             {
                 addFrY = Main.tileFrame[typeCache];
                 int num5 = x;
                 if (tileFrameX % 36 != 0)
                 {
                     num5--;
                 }
                 addFrY += num5 % 6;
                 if (addFrY >= 6)
                 {
                     addFrY -= 6;
                 }
                 addFrY *= 72;
             }
             else
             {
                 addFrY = 0;
             }
             break;
         case 410:
             if (tileFrameY == 36)
             {
                 tileHeight = 18;
             }
             if (tileFrameY >= 56)
             {
                 addFrY = Main.tileFrame[typeCache];
                 addFrY *= 56;
             }
             else
             {
                 addFrY = 0;
             }
             break;
         case 480:
         case 509:
         case 657:
             tileTop = 2;
             if (tileFrameY >= 54)
             {
                 addFrY = Main.tileFrame[typeCache];
                 addFrY *= 54;
             }
             else
             {
                 addFrY = 0;
             }
             break;
         case 658:
             tileTop = 2;
             switch (tileFrameY / 54)
             {
             default:
                 addFrY = Main.tileFrame[typeCache];
                 addFrY *= 54;
                 break;
             case 1:
                 addFrY = Main.tileFrame[typeCache];
                 addFrY *= 54;
                 addFrY += 486;
                 break;
             case 2:
                 addFrY = Main.tileFrame[typeCache];
                 addFrY *= 54;
                 addFrY += 972;
                 break;
             }
             break;
         case 326:
         case 327:
         case 328:
         case 329:
         case 345:
         case 351:
         case 421:
         case 422:
         case 458:
         case 459:
             addFrY = Main.tileFrame[typeCache] * 90;
             break;
         case 541:
             addFrY = ((!_shouldShowInvisibleBlocks) ? 90 : 0);
             break;
         case 507:
         case 508:
         {
             int num = 20;
             int num2 = (Main.tileFrameCounter[typeCache] + x * 11 + y * 27) % (num * 8);
             addFrY = 90 * (num2 / num);
             break;
         }
         case 336:
         case 340:
         case 341:
         case 342:
         case 343:
         case 344:
             addFrY = Main.tileFrame[typeCache] * 90;
             tileTop = 2;
             break;
         case 89:
             tileTop = 2;
             break;
         case 102:
             tileTop = 2;
             break;
         }
         if (tileCache.halfBrick())
         {
             halfBrickHeight = 8;
         }
         switch (typeCache)
         {
         case 657:
             if (tileFrameY >= 54)
             {
                 glowTexture = TextureAssets.GlowMask[330].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY + addFrY, tileWidth, tileHeight);
                 glowColor = Color.White;
             }
             break;
         case 656:
             glowTexture = TextureAssets.GlowMask[329].Value;
             glowSourceRect = new Rectangle(tileFrameX, tileFrameY + addFrY, tileWidth, tileHeight);
             glowColor = new Color(255, 255, 255, 0) * ((float)(int)Main.mouseTextColor / 255f);
             break;
         case 634:
             glowTexture = TextureAssets.GlowMask[315].Value;
             glowSourceRect = new Rectangle(tileFrameX, tileFrameY + addFrY, tileWidth, tileHeight);
             glowColor = Color.White;
             break;
         case 637:
             glowTexture = TextureAssets.Tile[637].Value;
             glowSourceRect = new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight);
             glowColor = Color.Lerp(Color.White, color, 0.75f);
             break;
         case 638:
             glowTexture = TextureAssets.GlowMask[327].Value;
             glowSourceRect = new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight);
             glowColor = Color.Lerp(Color.White, color, 0.75f);
             break;
         case 568:
             glowTexture = TextureAssets.GlowMask[268].Value;
             glowSourceRect = new Rectangle(tileFrameX, tileFrameY + addFrY, tileWidth, tileHeight);
             glowColor = Color.White;
             break;
         case 569:
             glowTexture = TextureAssets.GlowMask[269].Value;
             glowSourceRect = new Rectangle(tileFrameX, tileFrameY + addFrY, tileWidth, tileHeight);
             glowColor = Color.White;
             break;
         case 570:
             glowTexture = TextureAssets.GlowMask[270].Value;
             glowSourceRect = new Rectangle(tileFrameX, tileFrameY + addFrY, tileWidth, tileHeight);
             glowColor = Color.White;
             break;
         case 580:
             glowTexture = TextureAssets.GlowMask[289].Value;
             glowSourceRect = new Rectangle(tileFrameX, tileFrameY + addFrY, tileWidth, tileHeight);
             glowColor = new Color(225, 110, 110, 0);
             break;
         case 564:
             if (tileCache.frameX < 36)
             {
                 glowTexture = TextureAssets.GlowMask[267].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY + addFrY, tileWidth, tileHeight);
                 glowColor = new Color(200, 200, 200, 0) * ((float)(int)Main.mouseTextColor / 255f);
             }
             addFrY = 0;
             break;
         case 184:
             if (tileCache.frameX == 110)
             {
                 glowTexture = TextureAssets.GlowMask[127].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY, tileWidth, tileHeight);
                 glowColor = _lavaMossGlow;
             }
             if (tileCache.frameX == 132)
             {
                 glowTexture = TextureAssets.GlowMask[127].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY, tileWidth, tileHeight);
                 glowColor = _kryptonMossGlow;
             }
             if (tileCache.frameX == 154)
             {
                 glowTexture = TextureAssets.GlowMask[127].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY, tileWidth, tileHeight);
                 glowColor = _xenonMossGlow;
             }
             if (tileCache.frameX == 176)
             {
                 glowTexture = TextureAssets.GlowMask[127].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY, tileWidth, tileHeight);
                 glowColor = _argonMossGlow;
             }
             if (tileCache.frameX == 198)
             {
                 glowTexture = TextureAssets.GlowMask[127].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY, tileWidth, tileHeight);
                 glowColor = _violetMossGlow;
             }
             if (tileCache.frameX == 220)
             {
                 glowTexture = TextureAssets.GlowMask[127].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY, tileWidth, tileHeight);
                 glowColor = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
             }
             break;
         case 463:
             glowTexture = TextureAssets.GlowMask[243].Value;
             glowSourceRect = new Rectangle(tileFrameX, tileFrameY + addFrY, tileWidth, tileHeight);
             glowColor = new Color(127, 127, 127, 0);
             break;
         case 19:
         {
             int num73 = tileFrameY / 18;
             if (num73 == 26)
             {
                 glowTexture = TextureAssets.GlowMask[65].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 18, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num73 == 27)
             {
                 glowTexture = TextureAssets.GlowMask[112].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 18, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 90:
         {
             int num67 = tileFrameY / 36;
             if (num67 == 27)
             {
                 glowTexture = TextureAssets.GlowMask[52].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 36, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num67 == 28)
             {
                 glowTexture = TextureAssets.GlowMask[113].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 36, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 79:
         {
             int num63 = tileFrameY / 36;
             if (num63 == 27)
             {
                 glowTexture = TextureAssets.GlowMask[53].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 36, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num63 == 28)
             {
                 glowTexture = TextureAssets.GlowMask[114].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 36, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 89:
         {
             int num56 = tileFrameX / 54;
             int num57 = tileFrameX / 1998;
             addFrX -= 1998 * num57;
             addFrY += 36 * num57;
             if (num56 == 29)
             {
                 glowTexture = TextureAssets.GlowMask[66].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 54, tileFrameY, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num56 == 30)
             {
                 glowTexture = TextureAssets.GlowMask[123].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 54, tileFrameY, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 100:
             if (tileFrameX / 36 == 0 && tileFrameY / 36 == 27)
             {
                 glowTexture = TextureAssets.GlowMask[68].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 36, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             break;
         case 33:
             if (tileFrameX / 18 == 0 && tileFrameY / 22 == 26)
             {
                 glowTexture = TextureAssets.GlowMask[61].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 22, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             break;
         case 15:
         {
             int num70 = tileFrameY / 40;
             if (num70 == 32)
             {
                 glowTexture = TextureAssets.GlowMask[54].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 40, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num70 == 33)
             {
                 glowTexture = TextureAssets.GlowMask[116].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 40, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 34:
             if (tileFrameX / 54 == 0 && tileFrameY / 54 == 33)
             {
                 glowTexture = TextureAssets.GlowMask[55].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 54, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             break;
         case 21:
         case 467:
         {
             int num62 = tileFrameX / 36;
             if (num62 == 48)
             {
                 glowTexture = TextureAssets.GlowMask[56].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 36, tileFrameY, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num62 == 49)
             {
                 glowTexture = TextureAssets.GlowMask[117].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 36, tileFrameY, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 441:
         case 468:
         {
             int num58 = tileFrameX / 36;
             if (num58 == 48)
             {
                 glowTexture = TextureAssets.GlowMask[56].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 36, tileFrameY, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num58 == 49)
             {
                 glowTexture = TextureAssets.GlowMask[117].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 36, tileFrameY, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 10:
             if (tileFrameY / 54 == 32)
             {
                 glowTexture = TextureAssets.GlowMask[57].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 54, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             break;
         case 11:
         {
             int num74 = tileFrameY / 54;
             if (num74 == 32)
             {
                 glowTexture = TextureAssets.GlowMask[58].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 54, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num74 == 33)
             {
                 glowTexture = TextureAssets.GlowMask[119].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 54, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 88:
         {
             int num71 = tileFrameX / 54;
             int num72 = tileFrameX / 1998;
             addFrX -= 1998 * num72;
             addFrY += 36 * num72;
             if (num71 == 24)
             {
                 glowTexture = TextureAssets.GlowMask[59].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 54, tileFrameY, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num71 == 25)
             {
                 glowTexture = TextureAssets.GlowMask[120].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 54, tileFrameY, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 42:
             if (tileFrameY / 36 == 33)
             {
                 glowTexture = TextureAssets.GlowMask[63].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 36, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             break;
         case 87:
         {
             int num68 = tileFrameX / 54;
             int num69 = tileFrameX / 1998;
             addFrX -= 1998 * num69;
             addFrY += 36 * num69;
             if (num68 == 26)
             {
                 glowTexture = TextureAssets.GlowMask[64].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 54, tileFrameY, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num68 == 27)
             {
                 glowTexture = TextureAssets.GlowMask[121].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 54, tileFrameY, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 14:
         {
             int num66 = tileFrameX / 54;
             if (num66 == 31)
             {
                 glowTexture = TextureAssets.GlowMask[67].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 54, tileFrameY, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num66 == 32)
             {
                 glowTexture = TextureAssets.GlowMask[124].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 54, tileFrameY, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 93:
         {
             int num64 = tileFrameY / 54;
             int num65 = tileFrameY / 1998;
             addFrY -= 1998 * num65;
             addFrX += 36 * num65;
             tileTop += 2;
             if (num64 == 27)
             {
                 glowTexture = TextureAssets.GlowMask[62].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 54, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             break;
         }
         case 18:
         {
             int num61 = tileFrameX / 36;
             if (num61 == 27)
             {
                 glowTexture = TextureAssets.GlowMask[69].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 36, tileFrameY, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num61 == 28)
             {
                 glowTexture = TextureAssets.GlowMask[125].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 36, tileFrameY, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 101:
         {
             int num59 = tileFrameX / 54;
             int num60 = tileFrameX / 1998;
             addFrX -= 1998 * num60;
             addFrY += 72 * num60;
             if (num59 == 28)
             {
                 glowTexture = TextureAssets.GlowMask[60].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 54, tileFrameY, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num59 == 29)
             {
                 glowTexture = TextureAssets.GlowMask[115].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 54, tileFrameY, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 104:
         {
             int num55 = tileFrameX / 36;
             tileTop = 2;
             if (num55 == 24)
             {
                 glowTexture = TextureAssets.GlowMask[51].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 36, tileFrameY, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num55 == 25)
             {
                 glowTexture = TextureAssets.GlowMask[118].Value;
                 glowSourceRect = new Rectangle(tileFrameX % 36, tileFrameY, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         case 172:
         {
             int num54 = tileFrameY / 38;
             if (num54 == 28)
             {
                 glowTexture = TextureAssets.GlowMask[88].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 38, tileWidth, tileHeight);
                 glowColor = _martianGlow;
             }
             if (num54 == 29)
             {
                 glowTexture = TextureAssets.GlowMask[122].Value;
                 glowSourceRect = new Rectangle(tileFrameX, tileFrameY % 38, tileWidth, tileHeight);
                 glowColor = _meteorGlow;
             }
             break;
         }
         }
     }
References _argonMossGlow, _kryptonMossGlow, _lavaMossGlow, _martianGlow, _meteorGlow, _shouldShowInvisibleBlocks, _violetMossGlow, _xenonMossGlow, WorldGen.beachDistance, Main.birdCageFrame, Tile.blockType(), Main.blueBirdCageFrame, Main.bunnyCageFrame, Main.butterflyCageFrame, Entity.Center, Color, Main.critterCage, Main.DiscoB, Main.DiscoG, Main.DiscoR, Main.dragonflyJarFrame, Main.duckCageFrame, Main.fairyJarFrame, Main.fishBowlFrame, Tile.frameX, Main.frogCageFrame, GetBigAnimalCageFrame(), WorldGen.GetBiomeInfluence(), WorldGen.GetCactusType(), Lighting.GetColor(), GetPalmTreeBiome(), GetSmallAnimalCageFrame(), Animation.GetTemporaryFrame(), TileObjectData.GetTileData(), Framing.GetTileSafely(), GetTreeBiome(), GetWaterAnimalCageFrame(), TextureAssets.GlowMask, Main.grasshopperCageFrame, Main.grebeCageFrame, Tile.halfBrick(), InAPlaceWithWind(), Main.jellyfishCageFrame, Main.ladybugCageFrame, Main.lavaFishBowlFrame, Tile.liquid, Main.LocalPlayer, Main.macawCageFrame, Main.maggotCageFrame, Main.mallardCageFrame, Main.maxTilesX, Main.mouseCageFrame, Main.mouseTextColor, Tile.nactive(), Main.owlCageFrame, BirthdayParty.PartyIsUp, Main.penguinCageFrame, PressurePlateHelper.PressurePlatesPressed, Main.ratCageFrame, Main.redBirdCageFrame, Main.scorpionCageFrame, Main.seagullCageFrame, Main.seahorseCageFrame, Main.slugCageFrame, Main.snail2CageFrame, Main.snailCageFrame, WorldGen.SolidTile(), Main.squirrelCageFrame, TextureAssets.Tile, Main.tileFrame, Main.tileFrameCounter, Main.tileShine2, Main.turtleCageFrame, Asset< T >.Value, Main.waterStriderCageFrame, Main.weatherVaneBobframe, Main.WindForVisuals, and Main.wormCageFrame.
Referenced by DrawAnyDirectionalGrass(), DrawGrass(), DrawMultiTileGrassInWind(), DrawMultiTileVinesInWind(), DrawRisingVineStrip(), DrawSingleTile(), and DrawVineStrip().