Terraria: TileDrawing.DrawSingleTile_SlicedBlock
DrawSingleTile_SlicedBlock()
void TileDrawing.DrawSingleTile_SlicedBlock (Vector2 normalTilePosition, int tileX, int tileY, TileDrawInfo drawData) inline private
     {
         Color color = default(Color);
         Vector2 origin = default(Vector2);
         Rectangle value = default(Rectangle);
         Vector3 tileLight = default(Vector3);
         Vector2 position = default(Vector2);
         if (drawData.tileLight.R > _highQualityLightingRequirement.R || drawData.tileLight.G > _highQualityLightingRequirement.G || drawData.tileLight.B > _highQualityLightingRequirement.B)
         {
             Vector3[] slices = drawData.colorSlices;
             Lighting.GetColor9Slice(tileX, tileY, ref slices);
             Vector3 vector = drawData.tileLight.ToVector3();
             Vector3 tint = drawData.colorTint.ToVector3();
             if (drawData.tileCache.fullbrightBlock())
             {
                 slices = _glowPaintColorSlices;
             }
             for (int i = 0; i < 9; i++)
             {
                 value.X = 0;
                 value.Y = 0;
                 value.Width = 4;
                 value.Height = 4;
                 switch (i)
                 {
                 case 1:
                     value.Width = 8;
                     value.X = 4;
                     break;
                 case 2:
                     value.X = 12;
                     break;
                 case 3:
                     value.Height = 8;
                     value.Y = 4;
                     break;
                 case 4:
                     value.Width = 8;
                     value.Height = 8;
                     value.X = 4;
                     value.Y = 4;
                     break;
                 case 5:
                     value.X = 12;
                     value.Y = 4;
                     value.Height = 8;
                     break;
                 case 6:
                     value.Y = 12;
                     break;
                 case 7:
                     value.Width = 8;
                     value.Height = 4;
                     value.X = 4;
                     value.Y = 12;
                     break;
                 case 8:
                     value.X = 12;
                     value.Y = 12;
                     break;
                 }
                 tileLight.X = (slices[i].X + vector.X) * 0.5f;
                 tileLight.Y = (slices[i].Y + vector.Y) * 0.5f;
                 tileLight.Z = (slices[i].Z + vector.Z) * 0.5f;
                 GetFinalLight(drawData.tileCache, drawData.typeCache, ref tileLight, ref tint);
                 position.X = normalTilePosition.X + (float)value.X;
                 position.Y = normalTilePosition.Y + (float)value.Y;
                 value.X += drawData.tileFrameX + drawData.addFrX;
                 value.Y += drawData.tileFrameY + drawData.addFrY;
                 int num = (int)(tileLight.X * 255f);
                 int num2 = (int)(tileLight.Y * 255f);
                 int num3 = (int)(tileLight.Z * 255f);
                 if (num > 255)
                 {
                     num = 255;
                 }
                 if (num2 > 255)
                 {
                     num2 = 255;
                 }
                 if (num3 > 255)
                 {
                     num3 = 255;
                 }
                 num3 <<= 16;
                 num2 <<= 8;
                 color.PackedValue = (uint)(num | num2 | num3) | 0xFF000000u;
                 Main.spriteBatch.Draw(drawData.drawTexture, position, value, color, 0f, origin, 1f, drawData.tileSpriteEffect, 0f);
             }
         }
         else if (drawData.tileLight.R > _mediumQualityLightingRequirement.R || drawData.tileLight.G > _mediumQualityLightingRequirement.G || drawData.tileLight.B > _mediumQualityLightingRequirement.B)
         {
             Vector3[] slices2 = drawData.colorSlices;
             Lighting.GetColor4Slice(tileX, tileY, ref slices2);
             Vector3 vector2 = drawData.tileLight.ToVector3();
             Vector3 tint2 = drawData.colorTint.ToVector3();
             if (drawData.tileCache.fullbrightBlock())
             {
                 slices2 = _glowPaintColorSlices;
             }
             value.Width = 8;
             value.Height = 8;
             for (int j = 0; j < 4; j++)
             {
                 value.X = 0;
                 value.Y = 0;
                 switch (j)
                 {
                 case 1:
                     value.X = 8;
                     break;
                 case 2:
                     value.Y = 8;
                     break;
                 case 3:
                     value.X = 8;
                     value.Y = 8;
                     break;
                 }
                 tileLight.X = (slices2[j].X + vector2.X) * 0.5f;
                 tileLight.Y = (slices2[j].Y + vector2.Y) * 0.5f;
                 tileLight.Z = (slices2[j].Z + vector2.Z) * 0.5f;
                 GetFinalLight(drawData.tileCache, drawData.typeCache, ref tileLight, ref tint2);
                 position.X = normalTilePosition.X + (float)value.X;
                 position.Y = normalTilePosition.Y + (float)value.Y;
                 value.X += drawData.tileFrameX + drawData.addFrX;
                 value.Y += drawData.tileFrameY + drawData.addFrY;
                 int num4 = (int)(tileLight.X * 255f);
                 int num5 = (int)(tileLight.Y * 255f);
                 int num6 = (int)(tileLight.Z * 255f);
                 if (num4 > 255)
                 {
                     num4 = 255;
                 }
                 if (num5 > 255)
                 {
                     num5 = 255;
                 }
                 if (num6 > 255)
                 {
                     num6 = 255;
                 }
                 num6 <<= 16;
                 num5 <<= 8;
                 color.PackedValue = (uint)(num4 | num5 | num6) | 0xFF000000u;
                 Main.spriteBatch.Draw(drawData.drawTexture, position, value, color, 0f, origin, 1f, drawData.tileSpriteEffect, 0f);
             }
         }
         else
         {
             Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, drawData.tileWidth, drawData.tileHeight), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
         }
     }
References _glowPaintColorSlices, _highQualityLightingRequirement, _mediumQualityLightingRequirement, _zero, TileDrawInfo.addFrX, TileDrawInfo.addFrY, Color, TileDrawInfo.colorSlices, TileDrawInfo.colorTint, TileDrawInfo.drawTexture, TileDrawInfo.finalColor, Tile.fullbrightBlock(), Lighting.GetColor4Slice(), Lighting.GetColor9Slice(), GetFinalLight(), Main.spriteBatch, TileDrawInfo.tileCache, TileDrawInfo.tileFrameX, TileDrawInfo.tileFrameY, TileDrawInfo.tileHeight, TileDrawInfo.tileLight, TileDrawInfo.tileSpriteEffect, TileDrawInfo.tileWidth, and TileDrawInfo.typeCache.
Referenced by DrawBasicTile().