Terraria: CaptureInterface.QuickScreenshot
QuickScreenshot()
static void CaptureInterface.QuickScreenshot () inline static
     {
         Point point = Main.ViewPosition.ToTileCoordinates();
         Point point2 = (Main.ViewPosition + Main.ViewSize).ToTileCoordinates();
         StartCamera(new CaptureSettings
         {
             Area = new Rectangle(point.X, point.Y, point2.X - point.X + 1, point2.Y - point.Y + 1),
             Biome = CaptureBiome.GetCaptureBiome(Settings.BiomeChoiceIndex),
             CaptureBackground = !Settings.TransparentBackground,
             CaptureEntities = Settings.IncludeEntities,
             UseScaling = Settings.PackImage,
             CaptureMech = WiresUI.Settings.DrawWires
         });
     }
References Biome, CaptureInterface.Settings.BiomeChoiceIndex, WiresUI.Settings.DrawWires, CaptureBiome.GetCaptureBiome(), CaptureInterface.Settings.IncludeEntities, CaptureInterface.Settings.PackImage, StartCamera(), CaptureInterface.Settings.TransparentBackground, Main.ViewPosition, and Main.ViewSize.
Referenced by Main.DrawPageIcons(), and UpdateButtons().