Terraria: CaptureInterface.GetMapCoords
GetMapCoords()
static bool CaptureInterface.GetMapCoords (int PinX, int PinY, int Goal, out Point result) inline static private
     {
         if (!Main.mapFullscreen)
         {
             result = new Point(-1, -1);
             return false;
         }
         float num = 0f;
         float num2 = 0f;
         float num3 = 2f;
         _ = Main.maxTilesX / Main.textureMaxWidth;
         _ = Main.maxTilesY / Main.textureMaxHeight;
         float num4 = 10f;
         float num5 = 10f;
         float num6 = Main.maxTilesX - 10;
         float num7 = Main.maxTilesY - 10;
         num = 200f;
         num2 = 300f;
         num3 = Main.mapFullscreenScale;
         float num8 = (float)Main.screenWidth / (float)Main.maxTilesX * 0.8f;
         if (Main.mapFullscreenScale < num8)
         {
             Main.mapFullscreenScale = num8;
         }
         if (Main.mapFullscreenScale > 16f)
         {
             Main.mapFullscreenScale = 16f;
         }
         num3 = Main.mapFullscreenScale;
         if (Main.mapFullscreenPos.X < num4)
         {
             Main.mapFullscreenPos.X = num4;
         }
         if (Main.mapFullscreenPos.X > num6)
         {
             Main.mapFullscreenPos.X = num6;
         }
         if (Main.mapFullscreenPos.Y < num5)
         {
             Main.mapFullscreenPos.Y = num5;
         }
         if (Main.mapFullscreenPos.Y > num7)
         {
             Main.mapFullscreenPos.Y = num7;
         }
         float x = Main.mapFullscreenPos.X;
         float y = Main.mapFullscreenPos.Y;
         float num9 = x * num3;
         y *= num3;
         num = 0f - num9 + (float)(Main.screenWidth / 2);
         num2 = 0f - y + (float)(Main.screenHeight / 2);
         num += num4 * num3;
         num2 += num5 * num3;
         float num10 = Main.maxTilesX / 840;
         num10 *= Main.mapFullscreenScale;
         float num11 = num;
         float num12 = num2;
         float num13 = TextureAssets.Map.Width();
         float num14 = TextureAssets.Map.Height();
         if (Main.maxTilesX == 8400)
         {
             num10 *= 0.999f;
             num11 -= 40.6f * num10;
             num12 = num2 - 5f * num10;
             num13 -= 8.045f;
             num13 *= num10;
             num14 += 0.12f;
             num14 *= num10;
             if ((double)num10 < 1.2)
             {
                 num14 += 1f;
             }
         }
         else if (Main.maxTilesX == 6400)
         {
             num10 *= 1.09f;
             num11 -= 38.8f * num10;
             num12 = num2 - 3.85f * num10;
             num13 -= 13.6f;
             num13 *= num10;
             num14 -= 6.92f;
             num14 *= num10;
             if ((double)num10 < 1.2)
             {
                 num14 += 2f;
             }
         }
         else if (Main.maxTilesX == 6300)
         {
             num10 *= 1.09f;
             num11 -= 39.8f * num10;
             num12 = num2 - 4.08f * num10;
             num13 -= 26.69f;
             num13 *= num10;
             num14 -= 6.92f;
             num14 *= num10;
             if ((double)num10 < 1.2)
             {
                 num14 += 2f;
             }
         }
         else if (Main.maxTilesX == 4200)
         {
             num10 *= 0.998f;
             num11 -= 37.3f * num10;
             num12 -= 1.7f * num10;
             num13 -= 16f;
             num13 *= num10;
             num14 -= 8.31f;
             num14 *= num10;
         }
         switch (Goal)
         {
         case 0:
         {
             int num15 = (int)((0f - num + (float)PinX) / num3 + num4);
             int num16 = (int)((0f - num2 + (float)PinY) / num3 + num5);
             bool flag = false;
             if ((float)num15 < num4)
             {
                 flag = true;
             }
             if ((float)num15 >= num6)
             {
                 flag = true;
             }
             if ((float)num16 < num5)
             {
                 flag = true;
             }
             if ((float)num16 >= num7)
             {
                 flag = true;
             }
             if (!flag)
             {
                 result = new Point(num15, num16);
                 return true;
             }
             result = new Point(-1, -1);
             return false;
         }
         case 1:
         {
             Vector2 vector = new Vector2(num, num2);
             Vector2 vector2 = new Vector2(PinX, PinY) * num3 - new Vector2(10f * num3);
             result = (vector + vector2).ToPoint();
             return true;
         }
         default:
             result = new Point(-1, -1);
             return false;
         }
     }
References TextureAssets.Map, Main.mapFullscreen, Main.mapFullscreenPos, Main.mapFullscreenScale, Main.maxTilesX, Main.maxTilesY, Main.screenHeight, Main.screenWidth, Main.textureMaxHeight, and Main.textureMaxWidth.
Referenced by CaptureInterface.ModeDragBounds.DragBounds(), CaptureInterface.ModeEdgeSelection.DrawCursors(), CaptureInterface.ModeEdgeSelection.DrawMarkedArea(), CaptureInterface.ModeDragBounds.DrawMarkedArea(), and CaptureInterface.ModeEdgeSelection.EdgePlacement().