Terraria: CaptureInterface.Update
Update()
void CaptureInterface.Update () inline
     {
         PlayerInput.SetZoom_UI();
         UpdateCamera();
         if (CameraLock)
         {
             return;
         }
         bool toggleCameraMode = PlayerInput.Triggers.Current.ToggleCameraMode;
         if (toggleCameraMode && !KeyToggleActiveHeld && (Main.mouseItem.type == 0 || Active) && !Main.CaptureModeDisabled && !Main.player[Main.myPlayer].dead && !Main.player[Main.myPlayer].ghost)
         {
             ToggleCamera(!Active);
         }
         KeyToggleActiveHeld = toggleCameraMode;
         if (!Active)
         {
             return;
         }
         Main.blockMouse = true;
         if (JustActivated && Main.mouseLeftRelease && !Main.mouseLeft)
         {
             JustActivated = false;
         }
         Vector2 mouse = new Vector2(Main.mouseX, Main.mouseY);
         if (UpdateButtons(mouse) && Main.mouseLeft)
         {
             return;
         }
         foreach (KeyValuePair<int, CaptureInterfaceMode> mode in Modes)
         {
             mode.Value.Selected = mode.Key == SelectedMode;
             mode.Value.Update();
         }
         PlayerInput.SetZoom_Unscaled();
     }
References Active, Main.blockMouse, CameraLock, Main.CaptureModeDisabled, TriggersPack.Current, Player.dead, Player.ghost, JustActivated, KeyToggleActiveHeld, Modes, Main.mouseItem, Main.mouseLeft, Main.mouseLeftRelease, Main.mouseX, Main.mouseY, Main.myPlayer, Main.player, SelectedMode, PlayerInput.SetZoom_UI(), PlayerInput.SetZoom_Unscaled(), ToggleCamera(), TriggersSet.ToggleCameraMode, PlayerInput.Triggers, Item.type, UpdateButtons(), and UpdateCamera().
Referenced by CaptureManager.Update().