Terraria: Microsoft.Win32.SafeHandles.SafeNCryptHandle.SafeNCryptHandle
SafeNCryptHandle() [3/3]
Microsoft.Win32.SafeHandles.SafeNCryptHandle.SafeNCryptHandle (IntPtr handle, SafeHandle parentHandle) inline protected
Definition at line 41 of file SafeNCryptHandle.cs.
        : base(ownsHandle: true)
    {
        if (parentHandle == null)
        {
            throw new ArgumentNullException("parentHandle");
        }
        if (parentHandle.IsClosed || parentHandle.IsInvalid)
        {
            throw new ArgumentException(System.SR.Argument_Invalid_SafeHandleInvalidOrClosed, "parentHandle");
        }
        bool success = false;
        parentHandle.DangerousAddRef(ref success);
        _parentHandle = parentHandle;
        SetHandle(handle);
        if (IsInvalid)
        {
            _parentHandle.DangerousRelease();
            _parentHandle = null;
        }
    }
References Microsoft.Win32.SafeHandles.SafeNCryptHandle._parentHandle, System.SR.Argument_Invalid_SafeHandleInvalidOrClosed, System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Runtime.InteropServices.SafeHandle.handle, System.Runtime.InteropServices.SafeHandle.IsClosed, System.Runtime.InteropServices.SafeHandle.IsInvalid, Microsoft.Win32.SafeHandles.SafeNCryptHandle.IsInvalid, and System.Runtime.InteropServices.SafeHandle.SetHandle().