Terraria: CaptureInterface.ConstraintPoints
ConstraintPoints()
static void CaptureInterface.ConstraintPoints () inline static private
     {
         int offScreenTiles = Lighting.OffScreenTiles;
         if (EdgeAPinned)
         {
             PointWorldClamp(ref EdgeA, offScreenTiles);
         }
         if (EdgeBPinned)
         {
             PointWorldClamp(ref EdgeB, offScreenTiles);
         }
     }
References EdgeA, EdgeAPinned, EdgeB, EdgeBPinned, Lighting.OffScreenTiles, and PointWorldClamp().
Referenced by CaptureInterface.ModeDragBounds.DragBounds(), and CaptureInterface.ModeEdgeSelection.EdgePlacement().