Terraria: CaptureInterface.ResetFocus
ResetFocus()
static void CaptureInterface.ResetFocus () inline static
     {
         EdgeAPinned = false;
         EdgeBPinned = false;
         EdgeA = new Point(-1, -1);
         EdgeB = new Point(-1, -1);
     }
References EdgeA, EdgeAPinned, EdgeB, and EdgeBPinned.
Referenced by WorldGen.JustQuit(), WorldGen.SaveAndQuitCallBack(), and UpdateButtons().