Terraria: System.Xml.Xsl.Xslt.XsltInput.ContextInfo.SaveExtendedLineInfo
SaveExtendedLineInfo()
void System.Xml.Xsl.Xslt.XsltInput.ContextInfo.SaveExtendedLineInfo (XsltInput input) inline
Definition at line 90 of file XsltInput.cs.
        {
            if (lineInfo.Start.Line == 0)
            {
                elemNameLi = (endTagLi = null);
                return;
            }
            elemNameLi = new SourceLineInfo(lineInfo.Uri, lineInfo.Start.Line, lineInfo.Start.Pos + 1, lineInfo.Start.Line, lineInfo.Start.Pos + 1 + _elemNameLength);
            if (!input.IsEmptyElement)
            {
                endTagLi = input.BuildLineInfo();
            }
            else
            {
                endTagLi = new EmptyElementEndTag(lineInfo);
            }
        }
References System.Xml.Xsl.Xslt.XsltInput.ContextInfo._elemNameLength, System.Xml.Xsl.Xslt.XsltInput.ContextInfo.elemNameLi, System.Xml.Xsl.Xslt.XsltInput.ContextInfo.endTagLi, System.input, System.Xml.Xsl.Location.Line, System.Xml.Xsl.Xslt.XsltInput.ContextInfo.lineInfo, System.Xml.Xsl.Location.Pos, System.Xml.Xsl.ISourceLineInfo.Start, and System.Xml.Xsl.ISourceLineInfo.Uri.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.XslApplyImports(), System.Xml.Xsl.Xslt.XsltLoader.XslApplyTemplates(), System.Xml.Xsl.Xslt.XsltLoader.XslCallTemplate(), and System.Xml.Xsl.Xslt.XsltLoader.XslForEach().