Terraria: ActiveSound.Play
Play()
void ActiveSound.Play () inline private
     {
         SoundEffectInstance soundEffectInstance = Style.GetRandomSound().CreateInstance();
         soundEffectInstance.Pitch += Style.GetRandomPitch();
         Pitch = soundEffectInstance.Pitch;
         soundEffectInstance.Play();
         SoundInstanceGarbageCollector.Track(soundEffectInstance);
         Sound = soundEffectInstance;
         Update();
     }
References SoundStyle.GetRandomPitch(), SoundStyle.GetRandomSound(), Pitch, Sound, Style, SoundInstanceGarbageCollector.Track(), and Update().
Referenced by ActiveSound().