Terraria: System.Runtime.Serialization.ElementData.AddAttribute
AddAttribute()
void System.Runtime.Serialization.ElementData.AddAttribute (string prefix, string ns, string name, string value) inline
Definition at line 21 of file ElementData.cs.
    {
        GrowAttributesIfNeeded();
        AttributeData attributeData = attributes[attributeCount];
        if (attributeData == null)
        {
            attributeData = (attributes[attributeCount] = new AttributeData());
        }
        attributeData.prefix = prefix;
        attributeData.ns = ns;
        attributeData.localName = name;
        attributeData.value = value;
        attributeCount++;
    }
References System.Runtime.Serialization.ElementData.attributeCount, System.Runtime.Serialization.ElementData.attributes, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ElementData.GrowAttributesIfNeeded(), System.Runtime.Serialization.ElementData.ns, System.Runtime.Serialization.ElementData.prefix, and System.value.
Referenced by System.Runtime.Serialization.DataNode< T >.AddQualifiedNameAttribute(), System.Runtime.Serialization.CollectionDataNode.GetData(), and System.Runtime.Serialization.DataNode< T >.GetData().