Terraria: System.Text.Json.JsonWriterHelper.EscapeString
EscapeString() [1/4]
static void System.Text.Json.JsonWriterHelper.EscapeString (ReadOnlySpan< byte > value, Span< byte > destination, int indexOfFirstByteToEscape, JavaScriptEncoder encoder, out int written) inline static
Definition at line 335 of file JsonWriterHelper.cs.
    {
        value.Slice(0, indexOfFirstByteToEscape).CopyTo(destination);
        written = indexOfFirstByteToEscape;
        if (encoder != null)
        {
            destination = destination.Slice(indexOfFirstByteToEscape);
            value = value.Slice(indexOfFirstByteToEscape);
            EscapeString(value, destination, encoder, ref written);
            return;
        }
        while (indexOfFirstByteToEscape < value.Length)
        {
            byte b = value[indexOfFirstByteToEscape];
            if (IsAsciiValue(b))
            {
                if (NeedsEscaping(b))
                {
                    EscapeNextBytes(b, destination, ref written);
                    indexOfFirstByteToEscape++;
                }
                else
                {
                    destination[written] = b;
                    written++;
                    indexOfFirstByteToEscape++;
                }
                continue;
            }
            destination = destination.Slice(written);
            value = value.Slice(indexOfFirstByteToEscape);
            EscapeString(value, destination, JavaScriptEncoder.Default, ref written);
            break;
        }
    }
References System.Text.Encodings.Web.JavaScriptEncoder.Default, System.destination, System.Text.Json.Dictionary, System.Text.Json.JsonWriterHelper.EscapeNextBytes(), System.Text.Json.JsonWriterHelper.EscapeString(), System.Text.Json.JsonWriterHelper.IsAsciiValue(), System.Text.Json.JsonWriterHelper.NeedsEscaping(), and System.value.