Terraria: System.Text.Json.JsonWriterHelper.ValidateProperty
ValidateProperty() [1/2]
static void System.Text.Json.JsonWriterHelper.ValidateProperty (ReadOnlySpan< byte > propertyName) inline static
Definition at line 63 of file JsonWriterHelper.cs.
    {
        if (propertyName.Length > 166666666)
        {
            ThrowHelper.ThrowArgumentException_PropertyNameTooLarge(propertyName.Length);
        }
    }
References System.Text.Json.Dictionary, and System.Text.Json.ThrowHelper.ThrowArgumentException_PropertyNameTooLarge().
Referenced by System.Text.Json.Utf8JsonWriter.WriteBoolean(), System.Text.Json.Utf8JsonWriter.WriteBoolean(), System.Text.Json.Utf8JsonWriter.WriteNull(), System.Text.Json.Utf8JsonWriter.WriteNull(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WritePropertyNameUnescaped(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeProperty(), and System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeProperty().