Terraria: System.Text.Json.JsonWriterHelper.ToUtf8
ToUtf8()
static unsafe OperationStatus System.Text.Json.JsonWriterHelper.ToUtf8 (ReadOnlySpan< byte > utf16Source, Span< byte > utf8Destination, out int bytesConsumed, out int bytesWritten) inline static
Definition at line 508 of file JsonWriterHelper.cs.
    {
        fixed (byte* ptr = &MemoryMarshal.GetReference(utf16Source))
        {
            fixed (byte* ptr3 = &MemoryMarshal.GetReference(utf8Destination))
            {
                char* ptr2 = (char*)ptr;
                byte* ptr4 = ptr3;
                char* ptr5 = (char*)(ptr + utf16Source.Length);
                byte* ptr6 = ptr4 + utf8Destination.Length;
                while (true)
                {
                    IL_025a:
                    if (ptr5 - ptr2 > 13)
                    {
                        int num = Math.Min(PtrDiff(ptr5, ptr2), PtrDiff(ptr6, ptr4));
                        char* ptr7 = ptr2 + num - 5;
                        if (ptr2 < ptr7)
{
                            while (true)
{
                                int num2 = *ptr2;
                                ptr2++;
                                if (num2 > 127)
{
                                    goto IL_0181;
                                }
                                *ptr4 = (byte)num2;
                                ptr4++;
                                if (((uint)(int)ptr2 & 2u) != 0)
{
                                    num2 = *ptr2;
                                    ptr2++;
                                    if (num2 > 127)
{
                                        goto IL_0181;
                                    }
                                    *ptr4 = (byte)num2;
                                    ptr4++;
                                }
                                while (ptr2 < ptr7)
{
                                    num2 = *(int*)ptr2;
                                    int num3 = *(int*)(ptr2 + 2);
                                    if (((num2 | num3) & -8323200) == 0)
{
                                        if (!BitConverter.IsLittleEndian)
{
                                            *ptr4 = (byte)(num2 >> 16);
                                            ptr4[1] = (byte)num2;
                                            ptr2 += 4;
                                            ptr4[2] = (byte)(num3 >> 16);
                                            ptr4[3] = (byte)num3;
                                            ptr4 += 4;
                                        }
                                        else
{
                                            *ptr4 = (byte)num2;
                                            ptr4[1] = (byte)(num2 >> 16);
                                            ptr2 += 4;
                                            ptr4[2] = (byte)num3;
                                            ptr4[3] = (byte)(num3 >> 16);
                                            ptr4 += 4;
                                        }
                                        continue;
                                    }
                                    goto IL_014f;
                                }
                                goto IL_0251;
                                IL_014f:
                                num2 = (BitConverter.IsLittleEndian ? ((ushort)num2) : (num2 >>> 16));
                                ptr2++;
                                if (num2 > 127)
{
                                    goto IL_0181;
                                }
                                *ptr4 = (byte)num2;
                                ptr4++;
                                goto IL_0251;
                                IL_0251:
                                if (ptr2 < ptr7)
{
                                    continue;
                                }
                                goto IL_025a;
                                IL_0181:
                                int num4;
                                if (num2 <= 2047)
{
                                    num4 = -64 | (num2 >> 6);
                                }
                                else
{
                                    if (!JsonHelpers.IsInRangeInclusive(num2, 55296, 57343))
{
                                        num4 = -32 | (num2 >> 12);
                                    }
                                    else
{
                                        if (num2 > 56319)
{
                                            break;
                                        }
                                        num4 = *ptr2;
                                        if (!JsonHelpers.IsInRangeInclusive(num4, 56320, 57343))
{
                                            break;
                                        }
                                        ptr2++;
                                        num2 = num4 + (num2 << 10) + -56613888;
                                        *ptr4 = (byte)(0xFFFFFFF0u | (uint)(num2 >> 18));
                                        ptr4++;
                                        num4 = -128 | ((num2 >> 12) & 0x3F);
                                    }
                                    *ptr4 = (byte)num4;
                                    ptr7--;
                                    ptr4++;
                                    num4 = -128 | ((num2 >> 6) & 0x3F);
                                }
                                *ptr4 = (byte)num4;
                                ptr7--;
                                ptr4[1] = (byte)(0xFFFFFF80u | ((uint)num2 & 0x3Fu));
                                ptr4 += 2;
                                goto IL_0251;
                            }
                            break;
                        }
                    }
                    while (true)
                    {
                        int num5;
                        int num6;
                        if (ptr2 < ptr5)
{
                            num5 = *ptr2;
                            ptr2++;
                            if (num5 <= 127)
{
                                if (ptr6 - ptr4 > 0)
{
                                    *ptr4 = (byte)num5;
                                    ptr4++;
                                    continue;
                                }
                            }
                            else if (num5 <= 2047)
{
                                if (ptr6 - ptr4 > 1)
{
                                    num6 = -64 | (num5 >> 6);
                                    goto IL_0380;
                                }
                            }
                            else if (!JsonHelpers.IsInRangeInclusive(num5, 55296, 57343))
{
                                if (ptr6 - ptr4 > 2)
{
                                    num6 = -32 | (num5 >> 12);
                                    goto IL_0368;
                                }
                            }
                            else if (ptr6 - ptr4 > 3)
{
                                if (num5 > 56319)
{
                                    break;
                                }
                                if (ptr2 < ptr5)
{
                                    num6 = *ptr2;
                                    if (!JsonHelpers.IsInRangeInclusive(num6, 56320, 57343))
{
                                        break;
                                    }
                                    ptr2++;
                                    num5 = num6 + (num5 << 10) + -56613888;
                                    *ptr4 = (byte)(0xFFFFFFF0u | (uint)(num5 >> 18));
                                    ptr4++;
                                    num6 = -128 | ((num5 >> 12) & 0x3F);
                                    goto IL_0368;
                                }
                                bytesConsumed = (int)((byte*)(ptr2 - 1) - ptr);
                                bytesWritten = (int)(ptr4 - ptr3);
                                return OperationStatus.NeedMoreData;
                            }
                            bytesConsumed = (int)((byte*)(ptr2 - 1) - ptr);
                            bytesWritten = (int)(ptr4 - ptr3);
                            return OperationStatus.DestinationTooSmall;
                        }
                        bytesConsumed = (int)((byte*)ptr2 - ptr);
                        bytesWritten = (int)(ptr4 - ptr3);
                        return OperationStatus.Done;
                        IL_0368:
                        *ptr4 = (byte)num6;
                        ptr4++;
                        num6 = -128 | ((num5 >> 6) & 0x3F);
                        goto IL_0380;
                        IL_0380:
                        *ptr4 = (byte)num6;
                        ptr4[1] = (byte)(0xFFFFFF80u | ((uint)num5 & 0x3Fu));
                        ptr4 += 2;
                    }
                    break;
                }
                bytesConsumed = (int)((byte*)(ptr2 - 1) - ptr);
                bytesWritten = (int)(ptr4 - ptr3);
                return OperationStatus.InvalidData;
            }
        }
    }
References System.Text.Json.Dictionary, System.Text.Json.JsonHelpers.IsInRangeInclusive(), System.BitConverter.IsLittleEndian, System.Math.Min(), and System.Text.Json.JsonWriterHelper.PtrDiff().
Referenced by System.Text.Json.JsonDocument.TextEquals(), System.Text.Json.Utf8JsonWriter.TranscodeAndWrite(), System.Text.Json.Utf8JsonReader.ValueTextEquals(), System.Text.Json.Utf8JsonWriter.WriteCommentIndented(), and System.Text.Json.Utf8JsonWriter.WriteCommentMinimized().