Terraria: System.Text.Json.JsonWriterHelper.WriteDateTimeOffsetTrimmed
WriteDateTimeOffsetTrimmed()
static void System.Text.Json.JsonWriterHelper.WriteDateTimeOffsetTrimmed (Span< byte > buffer, DateTimeOffset value, out int bytesWritten) inline static
Definition at line 257 of file JsonWriterHelper.cs.
    {
        Span<byte> destination = stackalloc byte[33];
        bool flag = Utf8Formatter.TryFormat(value, destination, out bytesWritten, s_dateTimeStandardFormat);
        TrimDateTimeOffset(destination.Slice(0, bytesWritten), out bytesWritten);
        destination.Slice(0, bytesWritten).CopyTo(buffer);
    }
References System.buffer, System.destination, System.Text.Json.Dictionary, System.Text.Json.JsonWriterHelper.s_dateTimeStandardFormat, System.Text.Json.JsonWriterHelper.TrimDateTimeOffset(), System.Buffers.Text.Utf8Formatter.TryFormat(), and System.value.
Referenced by System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringValueIndented(), and System.Text.Json.Utf8JsonWriter.WriteStringValueMinimized().