Terraria: System.Text.Json.JsonWriterHelper.NeedsEscaping
NeedsEscaping() [1/3]
static bool System.Text.Json.JsonWriterHelper.NeedsEscaping (byte value) inline static private
Definition at line 294 of file JsonWriterHelper.cs.
    {
        return AllowList[value] == 0;
    }
References System.Text.Json.JsonWriterHelper.AllowList, and System.value.
Referenced by System.Text.Json.JsonEncodedText.EncodeHelper(), System.Text.Json.JsonWriterHelper.EscapeString(), System.Text.Json.JsonHelpers.GetEscapedPropertyNameSection(), System.Text.Json.Utf8JsonWriter.WriteBase64Escape(), System.Text.Json.Utf8JsonWriter.WriteBase64Escape(), System.Text.Json.Utf8JsonWriter.WriteLiteralEscape(), System.Text.Json.Utf8JsonWriter.WriteLiteralEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WriteStartEscape(), System.Text.Json.Utf8JsonWriter.WriteStartEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeValue(), and System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeValue().