Terraria: WoodHouseBuilder.AgeRoom
AgeRoom()
override void WoodHouseBuilder.AgeRoom (Rectangle room) inline protected virtual
Reimplemented from HouseBuilder.
     {
         for (int i = 0; i < room.Width * room.Height / 16; i++)
         {
             int x = WorldGen.genRand.Next(1, room.Width - 1) + room.X;
             int y = WorldGen.genRand.Next(1, room.Height - 1) + room.Y;
             WorldUtils.Gen(new Point(x, y), new Shapes.Rectangle(2, 2), Actions.Chain(new Modifiers.Dither(), new Modifiers.Blotches(2, 2), new Modifiers.IsEmpty(), new Actions.SetTile(51, setSelfFrames: true)));
         }
         WorldUtils.Gen(new Point(room.X, room.Y), new Shapes.Rectangle(room.Width, room.Height), Actions.Chain(new Modifiers.Dither(0.85), new Modifiers.Blotches(), new Modifiers.OnlyWalls(base.WallType), new Modifiers.SkipTiles(SkipTilesDuringWallAging), ((double)room.Y > Main.worldSurface) ? ((GenAction)new Actions.ClearWall(frameNeighbors: true)) : ((GenAction)new Actions.PlaceWall(2))));
         WorldUtils.Gen(new Point(room.X, room.Y), new Shapes.Rectangle(room.Width, room.Height), Actions.Chain(new Modifiers.Dither(0.95), new Modifiers.OnlyTiles(30, 321, 158), new Actions.ClearTile(frameNeighbors: true)));
     }
References Actions.Chain(), WorldUtils.Gen(), WorldGen.genRand, UnifiedRandom.Next(), HouseBuilder.SkipTilesDuringWallAging, and Main.worldSurface.