Terraria: SoundEngine.PlaySound
PlaySound() [2/4]
static void SoundEngine.PlaySound (int type, Vector2 position, int style = 1) inline static
Referenced by UIVirtualKeyboard.UIVirtualKeyboard(), ItemSlot.AfterItemSwap(), NPC.AI(), Projectile.AI(), Projectile.AI_001(), NPC.AI_002_FloatingEye(), NPC.AI_003_Fighters(), NPC.AI_005_EaterOfSouls(), NPC.AI_006_Worms(), Projectile.AI_007_GrapplingHooks(), NPC.AI_007_TownEntities(), Projectile.AI_009_MagicMissiles(), Projectile.AI_009_MagicMissiles_Old(), Projectile.AI_015_HandleMovementCollision(), Projectile.AI_015_HandleMovementCollision_Old(), Projectile.AI_016(), NPC.AI_026_Unicorns(), NPC.AI_037_Destroyer(), NPC.AI_045_Golem(), NPC.AI_047_GolemFist(), Projectile.AI_061_FishingBobber(), Projectile.AI_061_FishingBobber_DoASplash(), Projectile.AI_062(), Projectile.AI_067_FreakingPirates(), NPC.AI_069_DukeFishron(), Projectile.AI_075(), NPC.AI_084_LunaticCultist(), Projectile.AI_100_Medusa(), NPC.AI_108_DivingFlyer(), NPC.AI_112_FairyCritter(), NPC.AI_113_WindyBalloon(), NPC.AI_117_BloodNautilus(), NPC.AI_120_HallowBoss(), NPC.AI_121_QueenSlime(), NPC.AI_122_PirateGhost(), NPC.AI_123_Deerclops(), NPC.AI_125_ClumsySlimeBalloon(), Projectile.AI_150_GolfClubHelper(), Projectile.AI_151_SuperStar(), Projectile.AI_152_SuperStarSlash(), Projectile.AI_157_SharpTears(), Projectile.AI_164_StormTigerGem(), Projectile.AI_165_Whip(), Projectile.AI_169_Smolstars(), Projectile.AI_170_FairyGlowstick(), Projectile.AI_178_FireExplosion(), Projectile.AI_180_FairyQueenSunDance(), Projectile.AI_182_FinalFractal(), Projectile.AI_184_BadTorchLuck(), Projectile.AI_188_LightsBane(), Projectile.AI_189_Volcano(), Projectile.AI_190_NightsEdge(), Projectile.AI_191_TrueNightsEdge(), Main.Ambience(), Player.ApplyEquipFunctional(), Player.ApplyWilsonBeard(), ItemSlot.ArmorSwap(), IssueReportsIndicator.AttemptLettingPlayerKnow(), UIVirtualKeyboard.BackSpace(), TileEntity.BasicOpenCloseInteraction(), CreativePowers.ModifyTimeRate.bottomText_OnClick(), CreativePowers.ModifyWindDirectionAndStrength.bottomText_OnClick(), CreativePowers.ModifyRainPower.bottomText_OnClick(), CreativePowers.SpawnRateSliderPerPlayerPower.bottomText_OnClick(), UIVirtualKeyboard.BuildSpaceBarArea(), DelegateMethods.Minecart.BumperSound(), DelegateMethods.Minecart.BumperSoundFart(), CreativePowers.ModifyTimeRate.Button_OnMouseOut(), CreativePowers.DifficultySliderPower.Button_OnMouseOut(), CreativePowers.ModifyWindDirectionAndStrength.Button_OnMouseOut(), CreativePowers.ModifyRainPower.Button_OnMouseOut(), CreativePowers.SpawnRateSliderPerPlayerPower.Button_OnMouseOut(), CreativePowers.ModifyTimeRate.Button_OnMouseOver(), CreativePowers.DifficultySliderPower.Button_OnMouseOver(), CreativePowers.ModifyWindDirectionAndStrength.Button_OnMouseOver(), CreativePowers.ModifyRainPower.Button_OnMouseOver(), CreativePowers.SpawnRateSliderPerPlayerPower.Button_OnMouseOver(), UICreativeItemsInfiniteFilteringOptions.button_OnMouseOver(), Main.BuyHairWindow(), UIVirtualKeyboard.Cancel(), Main.CancelClothesWindow(), Main.CanceledGivingServerPassword(), Main.CancelHairWindow(), UILinkPointNavigator.ChangePage(), WorldGen.Check2x1(), NPC.checkDead(), Player.CheckDrowning(), WorldGen.CheckOrb(), WorldGen.CheckPot(), PlayerInput.CheckRebindingProcessGamepad(), PlayerInput.CheckRebindingProcessKeyboard(), UICharacterCreation.Click_CharGenderFemale(), UICharacterCreation.Click_CharGenderMale(), UICharacterCreation.Click_CharInfo(), UICharacterCreation.Click_ClothStyles(), UICharacterCreation.Click_ColorPicker(), UICharacterCreation.Click_CopyHex(), UICharacterCreation.Click_CopyPlayerTemplate(), CreativePowers.DifficultySliderPower.Click_Expert(), UIBestiaryTest.Click_GoBack(), UICharacterCreation.Click_GoBack(), UIWorldCreation.Click_GoBack(), UICharacterCreation.Click_HairStyles(), UIResourcePackSelectionMenu.Click_Info(), CreativePowers.DifficultySliderPower.Click_Journey(), CreativePowers.DifficultySliderPower.Click_Master(), UICharacterCreation.Click_Naming(), UICharacterCreation.Click_NamingAndCreating(), UIWorldCreation.Click_NamingAndCreating(), CreativePowers.DifficultySliderPower.Click_Normal(), UIWorkshopHub.Click_OpenResourcePackPublishMenu(), UIWorkshopHub.Click_OpenResourcePacksMenu(), UIWorkshopHub.Click_OpenWorldImportMenu(), UIWorkshopHub.Click_OpenWorldPublishMenu(), UICharacterCreation.Click_PasteHex(), UICharacterCreation.Click_PastePlayerTemplate(), UICharacterCreation.Click_RandomizePlayer(), UICharacterCreation.Click_RandomizeSingleColor(), UIWorldCreation.Click_SetName(), AWorkshopPublishInfoState< TPublishedObjectType >.Click_SetPreviewImage(), UIWorldCreation.Click_SetSeed(), IngameFancyUI.Close(), IngameOptions.Close(), WorldGen.CloseDoor(), Main.CloseNPCChatOrSign(), Player.CloseSign(), NPC.Collision_WaterCollision(), Main.CraftItem(), UIResourcePackSelectionMenu.CreateOffsetButton(), UIResourcePackSelectionMenu.CreatePackInfoButton(), UIResourcePackSelectionMenu.CreatePackToggleButton(), UIVirtualKeyboard.CursorLeft(), UIVirtualKeyboard.CursorRight(), RejectionMenuInfo.DefaultExitAction(), WorldFileData.DelayedGoToTitleScreen(), UICharacterListItem.DeleteButtonClick(), UIWorldListItem.DeleteButtonClick(), ChestUI.DepositAll(), Main.DoUpdate_Enter_ToggleChat(), Main.DoUpdate_F10_ToggleFPS(), Main.DoUpdate_F11_ToggleUI(), Main.DoUpdate_F7_ToggleGraphicsDiagnostics(), Main.DoUpdate_F8_ToggleNetDiagnostics(), Main.DoUpdate_F9_ToggleLighting(), Main.DoUpdate_HandleChat(), Main.DoUpdate_WhilePaused(), IngameOptions.Draw(), TeleportPylonsMapLayer.Draw(), WorkshopPublishingIndicator.Draw(), Main.DrawBestiaryIcon(), Main.DrawBlockReplacementIcon(), Main.DrawBuilderAccToggles(), Main.DrawClothesWindow(), Main.DrawEmoteBubblesButton(), Main.DrawHairWindow(), Main.DrawHotbarLockIcon(), Main.DrawInfoAccs(), Main.DrawInterface_38_MouseCarriedObject(), Main.DrawInventory(), Main.DrawLoadoutButtons(), Main.DrawMap(), Main.DrawMenu(), Main.DrawNPCChatButtons(), Main.DrawNPCHousesInUI(), Main.DrawNPCHousesInWorld(), Main.DrawPageIcons(), Main.DrawPVPIcons(), GroupOptionButton< T >.DrawSelf(), UICharacterNameButton.DrawSelf(), UIClothStyleButton.DrawSelf(), UIColoredSlider.DrawSelf(), UIDifficultyButton.DrawSelf(), UIHairStyleButton.DrawSelf(), UIIconTextButton.DrawSelf(), UIScrollbar.DrawSelf(), UIVerticalSlider.DrawSelf(), UIVirtualKeyboard.DrawSelf(), Main.DrawSettingButton(), Main.DrawStar(), Main.DrawTorchBiomeSwapIcon(), UIColoredSlider.DrawValueBar(), UIVerticalSlider.DrawValueBarDynamicWidth(), CaptureInterface.ModeChangeSettings.DrawWaterChoices(), DD2Film.DryadPortalFade(), DD2Film.DryadPortalKnock(), ItemSlot.DyeSwap(), GolfHelper.ContactListener.EmitGolfballExplosion(), Player.EmitMaxManaEffect(), PlayerInput.EnterBuildingMode(), ItemSlot.EquipSwap(), PlayerInput.ExitBuildingMode(), UICreativeInfiniteItemsDisplay.FadedMouseOver(), AWorkshopPublishInfoState< TPublishedObjectType >.FadedMouseOver(), UIAchievementsMenu.FadedMouseOver(), UIBestiaryTest.FadedMouseOver(), UICharacterCreation.FadedMouseOver(), UICharacterSelect.FadedMouseOver(), UIEmotesMenu.FadedMouseOver(), UIManageControls.FadedMouseOver(), UIReportsPage.FadedMouseOver(), UIResourcePackInfoMenu.FadedMouseOver(), UIResourcePackSelectionMenu.FadedMouseOver(), UIVirtualKeyboard.FadedMouseOver(), UIWorkshopHub.FadedMouseOver(), UIWorkshopSelectResourcePackToPublish.FadedMouseOver(), UIWorkshopSelectWorldToPublish.FadedMouseOver(), UIWorkshopWorldImport.FadedMouseOver(), UIWorldCreation.FadedMouseOver(), UIWorldSelect.FadedMouseOver(), NPC.FairyEffects(), UILinksInitializer.FancyExit(), Player.FillAmmo(), UIAchievementsMenu.FilterList(), NPC.FindFrame(), MessageBuffer.GetData(), ItemSlot.GetGamepadInstructions(), Player.GetItem_FillEmptyInventorySlot(), Player.GetItem_FillEmptyInventorySlot_VoidBag(), Player.GetItem_FillIntoOccupiedSlot(), Player.GetItem_FillIntoOccupiedSlot_VoidBag(), UICharacterSelect.GoBackClick(), UIReportsPage.GoBackClick(), UIWorkshopHub.GoBackClick(), UIWorldSelect.GoBackClick(), UIWorkshopHub.GoLogsClick(), UIWorkshopImportWorldListItem.GoToMainMenu(), Main.GUIChatDrawInner(), UIResourcePackSelectionMenu.HandleBackButtonUsage(), UIWorkshopHub.HandleBackButtonUsage(), UIWorkshopSelectResourcePackToPublish.HandleBackButtonUsage(), UIWorkshopSelectWorldToPublish.HandleBackButtonUsage(), UIWorkshopWorldImport.HandleBackButtonUsage(), Player.HandleBeingInChestRange(), Projectile.HandleMovement(), UILinksInitializer.HandleOptionsSpecials(), ItemSlot.HandleShopSlot(), NPC.HitEffect(), Wiring.HitSwitch(), Player.HorizontalMovement(), Main.HoverOverNPCs(), Player.Hurt(), NPC.IdleSounds(), UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles(), Main.InputTextSignCancel(), UIVirtualKeyboard.InternalSubmit(), Player.ItemCheck(), Player.ItemCheck_ApplyHoldStyle(), Player.ItemCheck_ManageRightClickFeatures(), Player.ItemCheck_ManageRightClickFeatures_ShieldRaise(), Player.ItemCheck_PlayInstruments(), Player.ItemCheck_StartActualUse(), Player.ItemCheck_UseBossSpawners(), Player.ItemCheck_UseBuckets(), Player.ItemCheck_UseEventItems(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), DelegateMethods.Minecart.JumpingSoundFart(), Player.JumpMovement(), WorldGen.JustQuit(), Projectile.Kill(), WorldGen.KillActuator(), Player.KillMe(), WorldGen.KillTile_PlaySounds(), WorldGen.KillWall_PlaySounds(), WorldGen.KillWire(), WorldGen.KillWire2(), WorldGen.KillWire3(), WorldGen.KillWire4(), DelegateMethods.Minecart.LandingSound(), DelegateMethods.Minecart.LandingSoundFart(), ItemSlot.LeftClick(), GroupOptionButton< T >.LeftMouseDown(), UIClothStyleButton.LeftMouseDown(), UIDifficultyButton.LeftMouseDown(), UIHairStyleButton.LeftMouseDown(), UIIconTextButton.LeftMouseDown(), Chest.Lock(), Player.MakeFloorDust(), Mount.MeowcartBumperSound(), Mount.MeowcartLandingSound(), CreativePowers.ModifyTimeRate.middleText_OnClick(), CreativePowers.ModifyWindDirectionAndStrength.middleText_OnClick(), CreativePowers.ModifyRainPower.middleText_OnClick(), CreativePowers.SpawnRateSliderPerPlayerPower.middleText_OnClick(), NPC.moneyPing(), EmoteButton.MouseOver(), UIColoredImageButton.MouseOver(), UIImageButton.MouseOver(), UISearchBar.MouseOver(), UIBestiaryEntryButton.MouseOver(), UIBestiaryInfoItemLine.MouseOver(), ChestUI.MoveCoins(), Item.MoveInWorld(), UICharacterSelect.NewCharacterClick(), LegacyChatMonitor.NewText(), Main.NewText(), LegacyChatMonitor.NewTextInternal(), Main.NewTextMultiline(), UIWorldSelect.NewWorldClick(), DD2Film.OgreSwingSound(), TEDisplayDoll.OnPlayerUpdate(), TEHatRack.OnPlayerUpdate(), Main.OnSubmitServerIP(), IngameOptions.Open(), Main.OpenClothesWindow(), WorldGen.OpenDoor(), UIResourcePackSelectionMenu.OpenFoldersClick(), Main.OpenHairWindow(), Player.OpenInventory(), Main.OpenShop(), IngameFancyUI.OpenVirtualKeyboard(), ItemSlot.OverrideLeftClick(), Player.PickupItem(), WorldGen.PlaceActuator(), WorldGen.PlaceObject(), Player.PlaceThing_ItemInExtractinator(), Player.PlaceThing_Tiles_PlaceIt(), WorldGen.PlaceTile(), WorldGen.PlaceWall(), WorldGen.PlaceWire(), WorldGen.PlaceWire2(), WorldGen.PlaceWire3(), WorldGen.PlaceWire4(), Player.PlayDrums(), UIWorldListItem.PlayGame(), Player.PlayGuitarChord(), Main.PlayInteractiveProjectileOpenCloseSound(), WorldGen.PlayLiquidChangeSound(), PlaySound(), LucyAxeMessage.PlaySound(), WorldGen.playWorldCallBack(), WorldGen.PoundTile(), CaptureInterface.ModeChangeSettings.PressButton(), UIVirtualKeyboard.PressSpace(), Player.QuickBuff(), Player.QuickGrapple(), Player.QuickHeal(), Player.QuickMana(), Player.QuickMount(), ChestUI.QuickStack(), UIManageControls.RadialButtonClick(), NPC.ReflectProjectile(), UIWorkshopPublishResourcePackListItem.RejectionMenuExitAction(), UICharacterListItem.RenameButtonClick(), UIWorldListItem.RenameButtonClick(), ChestUI.RenameChestCancel(), ChestUI.RenameChestSubmit(), DD2Event.RequestToSkipWaitTime(), Player.ResetEffects(), ChestUI.Restock(), ItemSlot.RightClick(), WorldGen.SaveAndQuit(), WorldGen.SaveAndQuitCallBack(), Main.SaveClothesWindow(), Player.ScrollHotbar(), CaptureInterface.Scrolling(), UICreativeInfiniteItemsDisplay.searchCancelButton_OnClick(), UIBestiaryTest.searchCancelButton_OnClick(), UICreativeInfiniteItemsDisplay.searchCancelButton_OnMouseOver(), UIBestiaryTest.searchCancelButton_OnMouseOver(), Main.SelectPlayer(), ItemSlot.SellOrTrash(), WorldGen.serverLoadWorldCallBack(), TileEntity.SetInteractionAnchor(), WorldGen.ShiftTallGate(), WorldGen.ShiftTrapdoor(), Item.ShimmerEffect(), WorldGen.SlopeTile(), UIManageControls.SnapButtonClick(), ParticleOrchestrator.Spawn_Digestion(), ParticleOrchestrator.Spawn_FlyMeal(), ParticleOrchestrator.Spawn_GasTrap(), ParticleOrchestrator.Spawn_ShimmerTownNPC(), ParticleOrchestrator.Spawn_SlapHand(), ParticleOrchestrator.Spawn_WaffleIron(), Player.SpawnFastRunParticles(), CaptureInterface.StartCamera(), AWorkshopPublishInfoState< TPublishedObjectType >.steamDisclaimerText_OnMouseOver(), NPC.StrikeNPC(), Main.SubmitSignText(), ItemSlot.SwapVanityEquip(), Player.Teleport(), Main.TeleportEffect(), Player.TileInteractionsUse(), CaptureInterface.ToggleCamera(), Player.ToggleCreativeMenu(), Player.ToggleInv(), CreativeUI.ToggleMenu(), CreativePowers.ModifyTimeRate.topText_OnClick(), CreativePowers.ModifyWindDirectionAndStrength.topText_OnClick(), CreativePowers.ModifyRainPower.topText_OnClick(), CreativePowers.SpawnRateSliderPerPlayerPower.topText_OnClick(), NPC.TransformVisuals(), TitleLinkButton.TryClicking(), TEDisplayDoll.TryFitting(), TEHatRack.TryFitting(), Main.TryInteractingWithMoneyTrough2(), Main.TryInteractingWithVoidLens(), UIWorkshopPublishResourcePackListItem.TryMovingToRejectionMenuIfNeeded(), UIWorldListItem.TryMovingToRejectionMenuIfNeeded(), ItemSlot.TryOpenContainer(), Player.TryOpeningFullscreenMap(), ItemSlot.TryPickupDyeToCursor(), ChestUI.TryPlacingInChest(), Main.TryRemovingBuff(), Player.TrySwitchingLoadout(), Player.TryToToggleSmartCursor(), UIVirtualKeyboard.TypeText(), Chest.Unlock(), WorldGen.UnlockDoor(), MinimapFrame.Update(), Gore.Update(), Player.Update(), Projectile.Update(), DontStarveDarknessDamageDealer.Update(), CaptureInterface.UpdateButtons(), Chest.UpdateChestFrames(), ChestUI.UpdateHover(), Player.UpdateManaRegen(), NPC.UpdateNPC_CritterSounds(), Player.UpdatePet(), Player.UpdatePetLight(), UICreativeInfiniteItemsDisplay.UpdateVisualFrame(), Main.UpdateWeather(), Mount.UseAbility(), Player.WingFrame(), Player.WOFTongue(), WorldGen.worldGenCallback(), and UIVirtualKeyboard.Write().