Terraria: Preferences.Load
Load()
bool Preferences.Load () inline
     {
         //IL_005d: Unknown result type (might be due to invalid IL or missing references)
         //IL_0064: Expected O, but got Unknown
         lock (_lock)
         {
             if (!File.Exists(_path))
             {
                 return false;
             }
             try
             {
                 if (!UseBson)
                 {
                     string text = File.ReadAllText(_path);
                     _data = JsonConvert.DeserializeObject<Dictionary<string, object>>(text, _serializerSettings);
                 }
                 else
                 {
                     using FileStream fileStream = File.OpenRead(_path);
                     BsonReader val = new BsonReader((Stream)fileStream);
                     try
                     {
                         JsonSerializer val2 = JsonSerializer.Create(_serializerSettings);
                         _data = val2.Deserialize<Dictionary<string, object>>((JsonReader)(object)val);
                     }
                     finally
                     {
                         ((IDisposable)val)?.Dispose();
                     }
                 }
                 if (_data == null)
                 {
                     _data = new Dictionary<string, object>();
                 }
                 if (this.OnLoad != null)
                 {
                     this.OnLoad(this);
                 }
                 return true;
             }
             catch (Exception)
             {
                 return false;
             }
         }
     }
References _data, _lock, _path, _serializerSettings, OnLoad, and UseBson.
Referenced by Main.Main(), PlayerInput.Load(), Main.LoadContent_TryEnteringHiDef(), and Main.LoadSettings().