Terraria: System.Runtime.Serialization.KnownTypeDataContractResolver.TryResolveType
TryResolveType() [1/2]
override bool System.Runtime.Serialization.KnownTypeDataContractResolver.TryResolveType (Type type, Type declaredType, DataContractResolver knownTypeResolver, out XmlDictionaryString typeName, out XmlDictionaryString typeNamespace) inline
Definition at line 16 of file KnownTypeDataContractResolver.cs.
    {
        if (type == null)
        {
            typeName = null;
            typeNamespace = null;
            return false;
        }
        if (declaredType != null && declaredType.IsInterface && CollectionDataContract.IsCollectionInterface(declaredType))
        {
            typeName = null;
            typeNamespace = null;
            return true;
        }
        DataContract dataContract = DataContract.GetDataContract(type);
        if (_context.IsKnownType(dataContract, dataContract.KnownDataContracts, declaredType))
        {
            typeName = dataContract.Name;
            typeNamespace = dataContract.Namespace;
            return true;
        }
        typeName = null;
        typeNamespace = null;
        return false;
    }
References System.Runtime.Serialization.KnownTypeDataContractResolver._context, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetDataContract(), System.Runtime.Serialization.CollectionDataContract.IsCollectionInterface(), System.Runtime.Serialization.XmlObjectSerializerContext.IsKnownType(), and System.type.