Terraria: System.Net.CertificateValidationPal.GetRequestCertificateAuthorities
GetRequestCertificateAuthorities()
static unsafe string[] System.Net.CertificateValidationPal.GetRequestCertificateAuthorities (SafeDeleteContext securityContext) inline static package
Definition at line 119 of file CertificateValidationPal.cs.
    {
        global::Interop.SspiCli.SecPkgContext_IssuerListInfoEx ctx = default(global::Interop.SspiCli.SecPkgContext_IssuerListInfoEx);
        SafeHandle sspiHandle;
        bool flag = SSPIWrapper.QueryContextAttributes_SECPKG_ATTR_ISSUER_LIST_EX(GlobalSSPI.SSPISecureChannel, securityContext, ref ctx, out sspiHandle);
        string[] array = Array.Empty<string>();
        try
        {
            if (flag && ctx.cIssuers != 0)
            {
                array = new string[ctx.cIssuers];
                Span<global::Interop.SspiCli.CERT_CHAIN_ELEMENT> span = new Span<global::Interop.SspiCli.CERT_CHAIN_ELEMENT>((void*)sspiHandle.DangerousGetHandle(), array.Length);
                for (int i = 0; i < span.Length; i++)
                {
                    if (span[i].cbSize != 0)
                    {
                        byte[] encodedDistinguishedName = new Span<byte>((void*)span[i].pCertContext, checked((int)span[i].cbSize)).ToArray();
                        X500DistinguishedName x500DistinguishedName = new X500DistinguishedName(encodedDistinguishedName);
                        array[i] = x500DistinguishedName.Name;
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(securityContext, $"IssuerListEx[{array[i]}]", "GetRequestCertificateAuthorities");
                        }
                    }
                }
            }
        }
        finally
        {
            sspiHandle?.Dispose();
        }
        return array;
    }
References System.array, System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Security.Cryptography.X509Certificates.X500DistinguishedName.Name, System.Net.SSPIWrapper.QueryContextAttributes_SECPKG_ATTR_ISSUER_LIST_EX(), System.Net.GlobalSSPI.SSPISecureChannel, and System.Span< T >.ToArray().
Referenced by System.Net.Security.SecureChannel.GetRequestCertificateAuthorities().