Terraria: System.Net.CertificateValidationPal.GetRemoteCertificate
GetRemoteCertificate() [2/3]
static X509Certificate2 System.Net.CertificateValidationPal.GetRemoteCertificate (SafeDeleteContext securityContext, bool retrieveCollection, out X509Certificate2Collection remoteCertificateCollection) inline static private
Definition at line 84 of file CertificateValidationPal.cs.
    {
        remoteCertificateCollection = null;
        if (securityContext == null)
        {
            return null;
        }
        X509Certificate2 x509Certificate = null;
        SafeFreeCertContext safeFreeCertContext = null;
        try
        {
            safeFreeCertContext = SSPIWrapper.QueryContextAttributes_SECPKG_ATTR_REMOTE_CERT_CONTEXT(GlobalSSPI.SSPISecureChannel, securityContext);
            if (safeFreeCertContext != null && !safeFreeCertContext.IsInvalid)
            {
                x509Certificate = new X509Certificate2(safeFreeCertContext.DangerousGetHandle());
            }
        }
        finally
        {
            if (safeFreeCertContext != null && !safeFreeCertContext.IsInvalid)
            {
                if (retrieveCollection)
                {
                    remoteCertificateCollection = UnmanagedCertificateContext.GetRemoteCertificatesFromStoreContext(safeFreeCertContext);
                }
                safeFreeCertContext.Dispose();
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Log.RemoteCertificate(x509Certificate);
        }
        return x509Certificate;
    }
References System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.UnmanagedCertificateContext.GetRemoteCertificatesFromStoreContext(), Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, System.Net.NetEventSource.Log, System.Net.SSPIWrapper.QueryContextAttributes_SECPKG_ATTR_REMOTE_CERT_CONTEXT(), and System.Net.GlobalSSPI.SSPISecureChannel.