Terraria: System.Net.CertificateValidationPal.EnsureStoreOpened
EnsureStoreOpened()
static X509Store System.Net.CertificateValidationPal.EnsureStoreOpened (bool isMachineStore) inline static package
Definition at line 19 of file CertificateValidationPal.cs.
    {
        X509Store x509Store = (isMachineStore ? s_myMachineCertStoreEx : s_myCertStoreEx);
        if (x509Store == null)
        {
            StoreLocation storeLocation = ((!isMachineStore) ? StoreLocation.CurrentUser : StoreLocation.LocalMachine);
            if (1 == 0)
            {
                return null;
            }
            lock (s_syncObject)
            {
                x509Store = (isMachineStore ? s_myMachineCertStoreEx : s_myCertStoreEx);
                if (x509Store == null)
                {
                    try
                    {
                        x509Store = OpenStore(storeLocation);
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(null, $"storeLocation: {storeLocation} returned store {x509Store}", "EnsureStoreOpened");
                        }
                        if (isMachineStore)
{
                            s_myMachineCertStoreEx = x509Store;
                        }
                        else
{
                            s_myCertStoreEx = x509Store;
                        }
                    }
                    catch (Exception ex)
                    {
                        if (ex is CryptographicException || ex is SecurityException)
{
                            return null;
                        }
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Error(null, System.SR.Format(System.SR.net_log_open_store_failed, storeLocation, ex), "EnsureStoreOpened");
                        }
                        throw;
                    }
                }
            }
        }
        return x509Store;
    }
References System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_log_open_store_failed, System.Net.CertificateValidationPal.OpenStore(), System.Net.CertificateValidationPal.s_myCertStoreEx, System.Net.CertificateValidationPal.s_myMachineCertStoreEx, and System.Net.CertificateValidationPal.s_syncObject.
Referenced by System.Net.Security.SecureChannel.FindCertificateWithPrivateKey().