Terraria: Interop.Kernel32.ProcessWaitHandle.ProcessWaitHandle
ProcessWaitHandle()
Interop.Kernel32.ProcessWaitHandle.ProcessWaitHandle (SafeProcessHandle processHandle) inline package
Definition at line 73 of file Interop.cs.
            {
                IntPtr currentProcess = GetCurrentProcess();
                if (!DuplicateHandle(currentProcess, (SafeHandle)processHandle, currentProcess, out SafeWaitHandle targetHandle, 0, bInheritHandle: false, 2))
                {
                    int hRForLastWin32Error = Marshal.GetHRForLastWin32Error();
                    targetHandle.Dispose();
                    Marshal.ThrowExceptionForHR(hRForLastWin32Error);
                }
                this.SetSafeWaitHandle(targetHandle);
            }
References Interop.Kernel32.DuplicateHandle(), Interop.Kernel32.GetCurrentProcess(), System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), and System.Runtime.InteropServices.Marshal.ThrowExceptionForHR().