Terraria: System.Globalization.PersianCalendar.CheckYearMonthRange
CheckYearMonthRange()
static void System.Globalization.PersianCalendar.CheckYearMonthRange (int year, int month, int era) inline static package
Definition at line 89 of file PersianCalendar.cs.
    {
        CheckYearRange(year, era);
        if (year == 9378 && month > 10)
        {
            throw new ArgumentOutOfRangeException("month", month, SR.Format(SR.ArgumentOutOfRange_Range, 1, 10));
        }
        if (month < 1 || month > 12)
        {
            ThrowHelper.ThrowArgumentOutOfRange_Month(month);
        }
    }
References System.SR.ArgumentOutOfRange_Range, System.Globalization.PersianCalendar.CheckYearRange(), System.SR.Format(), System.ThrowHelper.ThrowArgumentOutOfRange_Month(), and System.year.
Referenced by System.Globalization.PersianCalendar.GetDaysInMonth(), and System.Globalization.PersianCalendar.IsLeapMonth().