Terraria: System.Globalization.PersianCalendar.CheckTicksRange
CheckTicksRange()
static void System.Globalization.PersianCalendar.CheckTicksRange (long ticks) inline static package
Definition at line 64 of file PersianCalendar.cs.
    {
        if (ticks < s_minDate.Ticks || ticks > s_maxDate.Ticks)
        {
            throw new ArgumentOutOfRangeException("time", ticks, SR.Format(SR.ArgumentOutOfRange_CalendarRange, s_minDate, s_maxDate));
        }
    }
References System.SR.ArgumentOutOfRange_CalendarRange, System.SR.Format(), System.Globalization.PersianCalendar.s_maxDate, and System.Globalization.PersianCalendar.s_minDate.
Referenced by System.Globalization.PersianCalendar.GetDatePart(), and System.Globalization.PersianCalendar.GetEra().