Terraria: System.Xml.XmlAutoDetectWriter.WriteCData
WriteCData() [1/2]
override void System.Xml.XmlAutoDetectWriter.WriteCData (string text) inline
Definition at line 100 of file XmlAutoDetectWriter.cs.
    {
        if (TextBlockCreatesWriter(text))
        {
            _wrapped.WriteCData(text);
        }
        else
        {
            _eventCache.WriteCData(text);
        }
    }
References System.Xml.XmlAutoDetectWriter._eventCache, System.Xml.XmlAutoDetectWriter._wrapped, System.text, System.Xml.XmlAutoDetectWriter.TextBlockCreatesWriter(), System.Xml.XmlEventCache.WriteCData(), and System.Xml.XmlRawWriter.WriteCData().