Terraria: System.Xml.XPath.XPathException.Create
Create() [1/4]
static XPathException System.Xml.XPath.XPathException.Create (string res) inline static package
Definition at line 77 of file XPathException.cs.
    {
        return new XPathException(res, (string[])null);
    }
References System.Xml.XPath.XPathException.XPathException(), and System.Xml.Dictionary.
Referenced by MS.Internal.Xml.XPath.XPathScanner.XPathScanner(), MS.Internal.Xml.XPath.CompiledXpathExpr.AddSort(), MS.Internal.Xml.XPath.ExtensionQuery.Advance(), MS.Internal.Xml.XPath.ValueQuery.Advance(), MS.Internal.Xml.XPath.XPathParser.CheckNodeSet(), MS.Internal.Xml.XPath.XPathParser.CheckToken(), System.Xml.XPath.XPathNavigator.Evaluate(), MS.Internal.Xml.XPath.FunctionQuery.Evaluate(), MS.Internal.Xml.XPath.VariableQuery.Evaluate(), MS.Internal.Xml.XPath.XPathParser.GetAxis(), MS.Internal.Xml.XPath.CompiledXpathExpr.UndefinedXsltContext.LookupNamespace(), System.Xml.XPath.XPathNavigator.Matches(), MS.Internal.Xml.XPath.DescendantBaseQuery.MatchNode(), MS.Internal.Xml.XPath.Query.MatchNode(), MS.Internal.Xml.XPath.FunctionQuery.MatchNode(), MS.Internal.Xml.XPath.XPathScanner.NextLex(), MS.Internal.Xml.XPath.XPathParser.ParseExpression(), MS.Internal.Xml.XPath.XPathParser.ParseMethod(), MS.Internal.Xml.XPath.XPathParser.ParseNodeTest(), MS.Internal.Xml.XPath.XPathParser.ParseStepPattern(), MS.Internal.Xml.XPath.XPathParser.ParseXPathExpression(), MS.Internal.Xml.XPath.XPathParser.ParseXPathPattern(), MS.Internal.Xml.XPath.QueryBuilder.ProcessAxis(), MS.Internal.Xml.XPath.QueryBuilder.ProcessFunction(), MS.Internal.Xml.XPath.QueryBuilder.ProcessNode(), MS.Internal.Xml.XPath.QueryBuilder.ProcessVariable(), MS.Internal.Xml.XPath.CompiledXpathExpr.UndefinedXsltContext.ResolveFunction(), MS.Internal.Xml.XPath.CompiledXpathExpr.UndefinedXsltContext.ResolveVariable(), MS.Internal.Xml.XPath.XPathScanner.ScanString(), System.Xml.XPath.XPathNavigator.Select(), MS.Internal.Xml.XPath.FunctionQuery.SetXsltContext(), MS.Internal.Xml.XPath.VariableQuery.SetXsltContext(), and MS.Internal.Xml.XPath.SortQuery.SetXsltContext().