Terraria: System.Data.Common.TimeSpanStorage.Aggregate
Aggregate()
override object System.Data.Common.TimeSpanStorage.Aggregate (int[] records, AggregateType kind) inline virtual
Reimplemented from System.Data.Common.DataStorage.
Definition at line 18 of file TimeSpanStorage.cs.
    {
        bool flag = false;
        try
        {
            switch (kind)
            {
            case AggregateType.Min:
            {
                TimeSpan timeSpan = TimeSpan.MaxValue;
                foreach (int num9 in records)
                {
                    if (!IsNull(num9))
                    {
                        timeSpan = ((TimeSpan.Compare(_values[num9], timeSpan) < 0) ? _values[num9] : timeSpan);
                        flag = true;
                    }
                }
                if (flag)
                {
                    return timeSpan;
                }
                return _nullValue;
            }
            case AggregateType.Max:
            {
                TimeSpan timeSpan2 = TimeSpan.MinValue;
                foreach (int num13 in records)
                {
                    if (!IsNull(num13))
                    {
                        timeSpan2 = ((TimeSpan.Compare(_values[num13], timeSpan2) >= 0) ? _values[num13] : timeSpan2);
                        flag = true;
                    }
                }
                if (flag)
                {
                    return timeSpan2;
                }
                return _nullValue;
            }
            case AggregateType.First:
                if (records.Length != 0)
                {
                    return _values[records[0]];
                }
                return null;
            case AggregateType.Count:
                return base.Aggregate(records, kind);
            case AggregateType.Sum:
            {
                decimal d = default(decimal);
                foreach (int num14 in records)
                {
                    if (!IsNull(num14))
                    {
                        d += (decimal)_values[num14].Ticks;
                        flag = true;
                    }
                }
                if (flag)
                {
                    return TimeSpan.FromTicks((long)Math.Round(d));
                }
                return null;
            }
            case AggregateType.Mean:
            {
                decimal num10 = default(decimal);
                int num11 = 0;
                foreach (int num12 in records)
                {
                    if (!IsNull(num12))
                    {
                        num10 += (decimal)_values[num12].Ticks;
                        num11++;
                    }
                }
                if (num11 > 0)
                {
                    return TimeSpan.FromTicks((long)Math.Round(num10 / (decimal)num11));
                }
                return null;
            }
            case AggregateType.StDev:
            {
                int num = 0;
                decimal num2 = default(decimal);
                foreach (int num3 in records)
                {
                    if (!IsNull(num3))
                    {
                        num2 += (decimal)_values[num3].Ticks;
                        num++;
                    }
                }
                if (num > 1)
                {
                    double num4 = 0.0;
                    decimal num5 = num2 / (decimal)num;
                    foreach (int num6 in records)
                    {
                        if (!IsNull(num6))
{
                            double num7 = (double)((decimal)_values[num6].Ticks - num5);
                            num4 += num7 * num7;
                        }
                    }
                    ulong num8 = (ulong)Math.Round(Math.Sqrt(num4 / (double)(num - 1)));
                    if (num8 > long.MaxValue)
                    {
                        num8 = 9223372036854775807uL;
                    }
                    return TimeSpan.FromTicks((long)num8);
                }
                return null;
            }
            case AggregateType.Var:
                break;
            }
        }
        catch (OverflowException)
        {
            throw ExprException.Overflow(typeof(TimeSpan));
        }
        throw ExceptionBuilder.AggregateException(kind, _dataType);
    }
References System.Data.Common.DataStorage._dataType, System.Data.Common.DataStorage._nullValue, System.Data.Common.TimeSpanStorage._values, System.Data.ExceptionBuilder.AggregateException(), System.TimeSpan.Compare(), System.Xml.Dictionary, System.TimeSpan.FromTicks(), System.Data.IsNull, System.TimeSpan.MaxValue, System.TimeSpan.MinValue, System.Data.ExprException.Overflow(), System.Math.Round(), System.Math.Sqrt(), and System.TimeSpan.Ticks.