Terraria: System.Xml.XmlAutoDetectWriter.WriteString
WriteString() [1/2]
override void System.Xml.XmlAutoDetectWriter.WriteString (string text) inline
Definition at line 148 of file XmlAutoDetectWriter.cs.
    {
        if (TextBlockCreatesWriter(text))
        {
            _wrapped.WriteString(text);
        }
        else
        {
            _eventCache.WriteString(text);
        }
    }
References System.Xml.XmlAutoDetectWriter._eventCache, System.Xml.XmlAutoDetectWriter._wrapped, System.text, System.Xml.XmlAutoDetectWriter.TextBlockCreatesWriter(), System.Xml.XmlEventCache.WriteString(), and System.Xml.XmlWriter.WriteString().
Referenced by System.Xml.XmlAutoDetectWriter.WriteChars().