Terraria: Terraria.GameContent.TilePaintSystemV2.RequestTile
RequestTile()
void Terraria.GameContent.TilePaintSystemV2.RequestTile (ref TileVariationkey lookupKey) inline
Definition at line 309 of file TilePaintSystemV2.cs.
    {
        if (!_tilesRenders.TryGetValue(lookupKey, out var value))
        {
            value = new TileRenderTargetHolder
            {
                Key = lookupKey
            };
            _tilesRenders.Add(lookupKey, value);
        }
        if (!value.IsReady)
        {
            _requests.Add(value);
        }
    }
References Terraria.GameContent.TilePaintSystemV2._requests, Terraria.GameContent.TilePaintSystemV2._tilesRenders, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing(), Terraria.GameContent.TilePaintSystemV2.RequestTile_CheckForRelatedTileRequests(), and Terraria.GameContent.TilePaintSystemV2.TryGetTileAndRequestIfNotReady().