Terraria: LegacyPlayerRenderer.DrawPlayer
DrawPlayer()
void LegacyPlayerRenderer.DrawPlayer (Camera camera, Player drawPlayer, Vector2 position, float rotation, Vector2 rotationOrigin, float shadow = 0f, float scale = 1f) inline
Implements IPlayerRenderer.
     {
         if (drawPlayer.ShouldNotDraw)
         {
             return;
         }
         PlayerDrawSet drawInfo = default(PlayerDrawSet);
         _drawData.Clear();
         _dust.Clear();
         _gore.Clear();
         drawInfo.BoringSetup(drawPlayer, _drawData, _dust, _gore, position, shadow, rotation, rotationOrigin);
         DrawPlayer_UseNormalLayers(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_TransformDrawData(ref drawInfo);
         if (scale != 1f)
         {
             PlayerDrawLayers.DrawPlayer_ScaleDrawData(ref drawInfo, scale);
         }
         PlayerDrawLayers.DrawPlayer_RenderAllLayers(ref drawInfo);
         if (!drawInfo.drawPlayer.mount.Active || !drawInfo.drawPlayer.UsingSuperCart)
         {
             return;
         }
         for (int i = 0; i < 1000; i++)
         {
             if (Main.projectile[i].active && Main.projectile[i].owner == drawInfo.drawPlayer.whoAmI && Main.projectile[i].type == 591)
             {
                 Main.instance.DrawProj(i);
             }
         }
     }
References _drawData, _dust, _gore, Entity.active, Mount.Active, PlayerDrawSet.BoringSetup(), PlayerDrawSet.drawPlayer, PlayerDrawLayers.DrawPlayer_RenderAllLayers(), PlayerDrawLayers.DrawPlayer_ScaleDrawData(), PlayerDrawLayers.DrawPlayer_TransformDrawData(), DrawPlayer_UseNormalLayers(), Main.DrawProj(), Main.instance, Player.mount, Projectile.owner, Main.projectile, Player.ShouldNotDraw, Projectile.type, Player.UsingSuperCart, and Entity.whoAmI.
Referenced by DrawPlayerFull().