Terraria: LegacyPlayerRenderer.DrawPlayerHead
DrawPlayerHead()
void LegacyPlayerRenderer.DrawPlayerHead (Camera camera, Player drawPlayer, Vector2 position, float alpha = 1f, float scale = 1f, Color borderColor = default(Color)) inline
Implements IPlayerRenderer.
     {
         if (!drawPlayer.ShouldNotDraw)
         {
             _drawData.Clear();
             _dust.Clear();
             _gore.Clear();
             PlayerDrawHeadSet drawinfo = default(PlayerDrawHeadSet);
             drawinfo.BoringSetup(drawPlayer, _drawData, _dust, _gore, position.X, position.Y, alpha, scale);
             PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_01_FaceSkin(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_05_TallHats(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_06_NormalHats(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_07_JustHair(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc(ref drawinfo);
             CreateOutlines(alpha, scale, borderColor);
             PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(ref drawinfo);
         }
     }
References _drawData, _dust, _gore, PlayerDrawHeadSet.BoringSetup(), CreateOutlines(), PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet(), PlayerDrawHeadLayers.DrawPlayer_01_FaceSkin(), PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair(), PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair(), PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair(), PlayerDrawHeadLayers.DrawPlayer_05_TallHats(), PlayerDrawHeadLayers.DrawPlayer_06_NormalHats(), PlayerDrawHeadLayers.DrawPlayer_07_JustHair(), PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc(), PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(), and Player.ShouldNotDraw.