Terraria: LegacyPlayerRenderer.DrawPlayer_UseNormalLayers
DrawPlayer_UseNormalLayers()
static void LegacyPlayerRenderer.DrawPlayer_UseNormalLayers (ref PlayerDrawSet drawInfo) inline static private
     {
         PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_01_2_JimsCloak(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_03_Carpet(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_03_PortableStool(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_04_ElectrifiedDebuffBack(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_05_ForbiddenSetRing(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_05_2_SafemanSun(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_06_WebbedDebuffBack(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_08_Backpacks(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_08_1_Tails(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_09_Wings(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_01_BackHair(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_10_BackAcc(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_01_3_BackHead(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_11_Balloons(ref drawInfo);
         if (drawInfo.weaponDrawOrder == WeaponDrawOrder.BehindBackArm)
         {
             PlayerDrawLayers.DrawPlayer_27_HeldItem(ref drawInfo);
         }
         PlayerDrawLayers.DrawPlayer_12_Skin(ref drawInfo);
         if (drawInfo.drawPlayer.wearsRobe && drawInfo.drawPlayer.body != 166)
         {
             PlayerDrawLayers.DrawPlayer_14_Shoes(ref drawInfo);
             PlayerDrawLayers.DrawPlayer_13_Leggings(ref drawInfo);
         }
         else
         {
             PlayerDrawLayers.DrawPlayer_13_Leggings(ref drawInfo);
             PlayerDrawLayers.DrawPlayer_14_Shoes(ref drawInfo);
         }
         PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_15_SkinLongCoat(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_16_ArmorLongCoat(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_17_Torso(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_18_OffhandAcc(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_19_WaistAcc(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_20_NeckAcc(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_21_Head(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_21_1_Magiluminescence(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_22_FaceAcc(ref drawInfo);
         if (drawInfo.drawFrontAccInNeckAccLayer)
         {
             PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
             PlayerDrawLayers.DrawPlayer_32_FrontAcc_FrontPart(ref drawInfo);
             PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
         }
         PlayerDrawLayers.DrawPlayer_23_MountFront(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_24_Pulley(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_JimsDroneRadio(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_32_FrontAcc_BackPart(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_25_Shield(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_extra_MountPlus(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_26_SolarShield(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_extra_MountMinus(ref drawInfo);
         if (drawInfo.weaponDrawOrder == WeaponDrawOrder.BehindFrontArm)
         {
             PlayerDrawLayers.DrawPlayer_27_HeldItem(ref drawInfo);
         }
         PlayerDrawLayers.DrawPlayer_28_ArmOverItem(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_29_OnhandAcc(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_30_BladedGlove(ref drawInfo);
         if (!drawInfo.drawFrontAccInNeckAccLayer)
         {
             PlayerDrawLayers.DrawPlayer_32_FrontAcc_FrontPart(ref drawInfo);
         }
         PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
         if (drawInfo.weaponDrawOrder == WeaponDrawOrder.OverFrontArm)
         {
             PlayerDrawLayers.DrawPlayer_27_HeldItem(ref drawInfo);
         }
         PlayerDrawLayers.DrawPlayer_31_ProjectileOverArm(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_33_FrozenOrWebbedDebuff(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_34_ElectrifiedDebuffFront(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_35_IceBarrier(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_36_CTG(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_37_BeetleBuff(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_38_EyebrellaCloud(ref drawInfo);
         PlayerDrawLayers.DrawPlayer_MakeIntoFirstFractalAfterImage(ref drawInfo);
     }
References PlayerDrawLayers.DrawPlayer_01_2_JimsCloak(), PlayerDrawLayers.DrawPlayer_01_3_BackHead(), PlayerDrawLayers.DrawPlayer_01_BackHair(), PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer(), PlayerDrawLayers.DrawPlayer_03_Carpet(), PlayerDrawLayers.DrawPlayer_03_PortableStool(), PlayerDrawLayers.DrawPlayer_04_ElectrifiedDebuffBack(), PlayerDrawLayers.DrawPlayer_05_2_SafemanSun(), PlayerDrawLayers.DrawPlayer_05_ForbiddenSetRing(), PlayerDrawLayers.DrawPlayer_06_WebbedDebuffBack(), PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), PlayerDrawLayers.DrawPlayer_08_1_Tails(), PlayerDrawLayers.DrawPlayer_08_Backpacks(), PlayerDrawLayers.DrawPlayer_09_Wings(), PlayerDrawLayers.DrawPlayer_10_BackAcc(), PlayerDrawLayers.DrawPlayer_11_Balloons(), PlayerDrawLayers.DrawPlayer_12_Skin(), PlayerDrawLayers.DrawPlayer_13_Leggings(), PlayerDrawLayers.DrawPlayer_14_Shoes(), PlayerDrawLayers.DrawPlayer_15_SkinLongCoat(), PlayerDrawLayers.DrawPlayer_16_ArmorLongCoat(), PlayerDrawLayers.DrawPlayer_17_Torso(), PlayerDrawLayers.DrawPlayer_18_OffhandAcc(), PlayerDrawLayers.DrawPlayer_19_WaistAcc(), PlayerDrawLayers.DrawPlayer_20_NeckAcc(), PlayerDrawLayers.DrawPlayer_21_1_Magiluminescence(), PlayerDrawLayers.DrawPlayer_21_Head(), PlayerDrawLayers.DrawPlayer_22_FaceAcc(), PlayerDrawLayers.DrawPlayer_23_MountFront(), PlayerDrawLayers.DrawPlayer_24_Pulley(), PlayerDrawLayers.DrawPlayer_25_Shield(), PlayerDrawLayers.DrawPlayer_26_SolarShield(), PlayerDrawLayers.DrawPlayer_27_HeldItem(), PlayerDrawLayers.DrawPlayer_28_ArmOverItem(), PlayerDrawLayers.DrawPlayer_29_OnhandAcc(), PlayerDrawLayers.DrawPlayer_30_BladedGlove(), PlayerDrawLayers.DrawPlayer_31_ProjectileOverArm(), PlayerDrawLayers.DrawPlayer_32_FrontAcc_BackPart(), PlayerDrawLayers.DrawPlayer_32_FrontAcc_FrontPart(), PlayerDrawLayers.DrawPlayer_33_FrozenOrWebbedDebuff(), PlayerDrawLayers.DrawPlayer_34_ElectrifiedDebuffFront(), PlayerDrawLayers.DrawPlayer_35_IceBarrier(), PlayerDrawLayers.DrawPlayer_36_CTG(), PlayerDrawLayers.DrawPlayer_37_BeetleBuff(), PlayerDrawLayers.DrawPlayer_38_EyebrellaCloud(), PlayerDrawLayers.DrawPlayer_extra_MountMinus(), PlayerDrawLayers.DrawPlayer_extra_MountPlus(), PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(), PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(), PlayerDrawLayers.DrawPlayer_JimsDroneRadio(), and PlayerDrawLayers.DrawPlayer_MakeIntoFirstFractalAfterImage().
Referenced by DrawPlayer().