Terraria: System.Security.Cryptography.AsnEncodedData.Reset
Reset() [1/2]
void System.Security.Cryptography.AsnEncodedData.Reset (Oid oid, byte[] rawData) inline private inherited
Definition at line 104 of file AsnEncodedData.cs.
    {
        Oid = oid;
        RawData = rawData;
    }
References System.Security.Cryptography.AsnEncodedData.RawData.
Referenced by System.Security.Cryptography.AsnEncodedData.AsnEncodedData(), System.Security.Cryptography.AsnEncodedData.AsnEncodedData(), System.Security.Cryptography.AsnEncodedData.AsnEncodedData(), System.Security.Cryptography.AsnEncodedData.AsnEncodedData(), System.Security.Cryptography.AsnEncodedData.AsnEncodedData(), System.Security.Cryptography.AsnEncodedData.AsnEncodedData(), System.Security.Cryptography.AsnEncodedData.AsnEncodedData(), and System.Security.Cryptography.AsnEncodedData.CopyFrom().