Terraria: System.Array.Clear
Clear() [3/3]
static unsafe void System.Array.Clear (Array array, int index, int length) inline static
Definition at line 774 of file Array.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        ref byte source = ref Unsafe.As<RawArrayData>(array).Data;
        int num = 0;
        MethodTable* methodTable = RuntimeHelpers.GetMethodTable(array);
        if (methodTable->IsMultiDimensionalArray)
        {
            int multiDimensionalArrayRank = methodTable->MultiDimensionalArrayRank;
            num = Unsafe.Add(ref Unsafe.As<byte, int>(ref source), multiDimensionalArrayRank);
            source = ref Unsafe.Add(ref source, 8 * multiDimensionalArrayRank);
        }
        int num2 = index - num;
        if (index < num || num2 < 0 || length < 0 || (uint)(num2 + length) > array.NativeLength)
        {
            ThrowHelper.ThrowIndexOutOfRangeException();
        }
        nuint num3 = methodTable->ComponentSize;
        ref byte reference = ref Unsafe.AddByteOffset(ref source, (uint)num2 * num3);
        nuint num4 = (uint)length * num3;
        if (methodTable->ContainsGCPointers)
        {
            SpanHelpers.ClearWithReferences(ref Unsafe.As<byte, IntPtr>(ref reference), num4 / (uint)sizeof(IntPtr));
        }
        else
        {
            SpanHelpers.ClearWithoutReferences(ref reference, num4);
        }
    }
References System.array, System.SpanHelpers.ClearWithoutReferences(), System.SpanHelpers.ClearWithReferences(), System.Runtime.CompilerServices.RuntimeHelpers.GetMethodTable(), System.index, System.length, System.source, System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowIndexOutOfRangeException().