Terraria: System.Xml.XmlBaseReader.SignNode
SignNode() [1/2]
void System.Xml.XmlBaseReader.SignNode () inline protected inherited
Definition at line 3087 of file XmlBaseReader.cs.
    {
        if (_signing)
        {
            SignNode(_signingWriter);
        }
    }
References System.Xml.XmlBaseReader._signing, System.Xml.XmlBaseReader._signingWriter, and System.Xml.XmlBaseReader.SignNode().
Referenced by System.Xml.XmlBinaryReader.Read(), System.Xml.XmlUTF8TextReader.Read(), and System.Xml.XmlBaseReader.SignNode().