Terraria: System.Xml.XmlBaseReader.SignStartElement
SignStartElement()
void System.Xml.XmlBaseReader.SignStartElement (XmlSigningNodeWriter writer) inline private inherited
Definition at line 3003 of file XmlBaseReader.cs.
    {
        int offset;
        int length;
        byte[] @string = _node.Prefix.GetString(out offset, out length);
        int offset2;
        int length2;
        byte[] string2 = _node.LocalName.GetString(out offset2, out length2);
        writer.WriteStartElement(@string, offset, length, string2, offset2, length2);
    }
References System.Xml.XmlBaseReader._node, System.Xml.Dictionary, System.Xml.PrefixHandle.GetString(), System.Xml.StringHandle.GetString(), System.length, System.length2, System.Xml.XmlBaseReader.XmlNode.LocalName, System.offset, System.Xml.XmlBaseReader.XmlNode.Prefix, and System.writer.
Referenced by System.Xml.XmlBaseReader.SignNode().