Terraria: System.Array.SetValue
SetValue() [1/8]
unsafe void System.Array.SetValue (object? value, int index) inline
Definition at line 1022 of file Array.cs.
    {
        if (Rank != 1)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_Need1DArray);
        }
        InternalSetValue(value, GetFlattenedIndex(new ReadOnlySpan<int>(&index, 1)));
    }
References System.Array.GetFlattenedIndex(), System.index, System.Array.InternalSetValue(), System.Array.Rank, System.ThrowHelper.ThrowArgumentException(), and System.value.
Referenced by System.Data.DataViewSettingCollection.CopyTo(), System.Array.SorterGenericArray.DownHeap(), System.Runtime.Serialization.Formatters.Binary.ValueFixup.Fixup(), System.Array.SorterGenericArray.InsertionSort(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SorterGenericArray.Swap(), and System.Array.SorterGenericArray.SwapIfGreater().