Terraria: System.Xml.XmlBaseReader.ReadContentAsInt
ReadContentAsInt()
override int System.Xml.XmlBaseReader.ReadContentAsInt () inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 2675 of file XmlBaseReader.cs.
    {
        XmlNode node = Node;
        if (_value == null && node.IsAtomicValue)
        {
            int result = node.Value.ToInt();
            SkipValue(node);
            return result;
        }
        return XmlConverter.ToInt32(ReadContentAsString());
    }
References System.Xml.XmlBaseReader._value, System.Xml.Dictionary, System.Xml.XmlBaseReader.Node, System.Xml.XmlBaseReader.ReadContentAsString(), System.Xml.XmlBaseReader.SkipValue(), System.Xml.ValueHandle.ToInt(), System.Xml.XmlConverter.ToInt32(), and System.Xml.XmlBaseReader.XmlNode.Value.
Referenced by System.Xml.XmlBaseReader.ReadContentAs().