Terraria: System.Xml.XmlBaseReader.ReadContentAs
ReadContentAs() [1/2]
override object System.Xml.XmlBaseReader.ReadContentAs (Type type, IXmlNamespaceResolver namespaceResolver) inline inherited
Definition at line 2783 of file XmlBaseReader.cs.
    {
        if (type == typeof(ulong))
        {
            if (_value == null && _node.IsAtomicValue)
            {
                ulong num = _node.Value.ToULong();
                SkipValue(_node);
                return num;
            }
            return XmlConverter.ToUInt64(ReadContentAsString());
        }
        if (type == typeof(bool))
        {
            return ReadContentAsBoolean();
        }
        if (type == typeof(int))
        {
            return ReadContentAsInt();
        }
        if (type == typeof(long))
        {
            return ReadContentAsLong();
        }
        if (type == typeof(float))
        {
            return ReadContentAsFloat();
        }
        if (type == typeof(double))
        {
            return ReadContentAsDouble();
        }
        if (type == typeof(decimal))
        {
            return ReadContentAsDecimal();
        }
        if (type == typeof(DateTime))
        {
            return ReadContentAsDateTime();
        }
        if (type == typeof(UniqueId))
        {
            return ReadContentAsUniqueId();
        }
        if (type == typeof(Guid))
        {
            return ReadContentAsGuid();
        }
        if (type == typeof(TimeSpan))
        {
            return ReadContentAsTimeSpan();
        }
        if (type == typeof(object))
        {
            return ReadContentAsObject();
        }
        return base.ReadContentAs(type, namespaceResolver);
    }
References System.Xml.XmlBaseReader._node, System.Xml.XmlBaseReader._value, System.Xml.Dictionary, System.Xml.XmlBaseReader.XmlNode.IsAtomicValue, System.Xml.XmlBaseReader.ReadContentAsBoolean(), System.Xml.XmlBaseReader.ReadContentAsDateTime(), System.Xml.XmlBaseReader.ReadContentAsDecimal(), System.Xml.XmlBaseReader.ReadContentAsDouble(), System.Xml.XmlBaseReader.ReadContentAsFloat(), System.Xml.XmlBaseReader.ReadContentAsGuid(), System.Xml.XmlBaseReader.ReadContentAsInt(), System.Xml.XmlBaseReader.ReadContentAsLong(), System.Xml.XmlBaseReader.ReadContentAsObject(), System.Xml.XmlBaseReader.ReadContentAsString(), System.Xml.XmlBaseReader.ReadContentAsTimeSpan(), System.Xml.XmlBaseReader.ReadContentAsUniqueId(), System.Xml.XmlBaseReader.SkipValue(), System.Xml.XmlConverter.ToUInt64(), System.Xml.ValueHandle.ToULong(), System.type, and System.Xml.XmlBaseReader.XmlNode.Value.