Terraria: System.Xml.XmlBaseReader.ReadElementContentAsBinHex
ReadElementContentAsBinHex() [2/2]
override int System.Xml.XmlBaseReader.ReadElementContentAsBinHex (byte[] buffer, int offset, int count) inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 2499 of file XmlBaseReader.cs.
    {
        if (!_readingElement)
        {
            if (IsEmptyElement)
            {
                Read();
                return 0;
            }
            ReadStartElement();
            _readingElement = true;
        }
        int num = ReadContentAsBinHex(buffer, offset, count);
        if (num == 0)
        {
            ReadEndElement();
            _readingElement = false;
        }
        return num;
    }
References System.Xml.XmlBaseReader._readingElement, System.buffer, System.count, System.Xml.XmlBaseReader.IsEmptyElement, System.offset, System.Xml.XmlReader.Read(), System.Xml.XmlBaseReader.ReadContentAsBinHex(), System.Xml.XmlBaseReader.ReadEndElement(), and System.Xml.XmlBaseReader.ReadStartElement().