Terraria: System.Xml.XmlBaseReader.ReadValueChunk
ReadValueChunk()
override int System.Xml.XmlBaseReader.ReadValueChunk (char[] chars, int offset, int count) inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 2224 of file XmlBaseReader.cs.
    {
        if (chars == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("chars"));
        }
        if (offset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative));
        }
        if (offset > chars.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.Format(System.SR.OffsetExceedsBufferSize, chars.Length)));
        }
        if (count < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative));
        }
        if (count > chars.Length - offset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, chars.Length - offset)));
        }
        if (_value == null && _node.QNameType == QNameType.Normal && _node.Value.TryReadChars(chars, offset, count, out var actual))
        {
            return actual;
        }
        string value = Value;
        actual = Math.Min(count, value.Length);
        value.CopyTo(0, chars, offset, actual);
        _value = value.Substring(actual);
        return actual;
    }
References System.Xml.XmlBaseReader._node, System.Xml.XmlBaseReader._value, System.chars, System.count, System.Xml.Dictionary, System.SR.Format(), System.Math.Min(), System.offset, System.SR.OffsetExceedsBufferSize, System.Xml.XmlBaseReader.XmlNode.QNameType, System.SR.SizeExceedsRemainingBufferSpace, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.ValueHandle.TryReadChars(), System.value, System.Xml.XmlBaseReader.XmlNode.Value, System.Xml.XmlBaseReader.Value, and System.SR.ValueMustBeNonNegative.
Referenced by System.Xml.XmlBaseReader.ReadBytes().