Terraria: System.Array.GetFlattenedIndex
GetFlattenedIndex()
unsafe nint System.Array.GetFlattenedIndex (ReadOnlySpan< int > indices) inline private
Definition at line 807 of file Array.cs.
    {
        if (RuntimeHelpers.GetMethodTable(this)->IsMultiDimensionalArray)
        {
            ref int multiDimensionalArrayBounds = ref RuntimeHelpers.GetMultiDimensionalArrayBounds(this);
            nint num = 0;
            for (int i = 0; i < indices.Length; i++)
            {
                int num2 = indices[i] - Unsafe.Add(ref multiDimensionalArrayBounds, indices.Length + i);
                int num3 = Unsafe.Add(ref multiDimensionalArrayBounds, i);
                if ((uint)num2 >= (uint)num3)
                {
                    ThrowHelper.ThrowIndexOutOfRangeException();
                }
                num = num3 * num + num2;
            }
            return num;
        }
        int num4 = indices[0];
        if ((uint)num4 >= (uint)LongLength)
        {
            ThrowHelper.ThrowIndexOutOfRangeException();
        }
        return num4;
    }
References System.Runtime.CompilerServices.RuntimeHelpers.GetMethodTable(), System.Runtime.CompilerServices.RuntimeHelpers.GetMultiDimensionalArrayBounds(), System.indices, System.Array.LongLength, and System.ThrowHelper.ThrowIndexOutOfRangeException().
Referenced by System.Array.GetValue(), System.Array.GetValue(), System.Array.GetValue(), System.Array.GetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), and System.Array.SetValue().