Terraria: System.Xml.XmlBaseReader.MoveToDeclaration
MoveToDeclaration()
XmlDeclarationNode System.Xml.XmlBaseReader.MoveToDeclaration () inline protected inherited
Definition at line 1328 of file XmlBaseReader.cs.
    {
        if (_attributeCount < 1)
        {
            XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.XmlDeclMissingVersion));
        }
        if (_attributeCount > 3)
        {
            XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.XmlMalformedDecl));
        }
        if (!CheckDeclAttribute(0, "version", "1.0", checkLower: false, System.SR.XmlInvalidVersion))
        {
            XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.XmlDeclMissingVersion));
        }
        if (_attributeCount > 1)
        {
            if (CheckDeclAttribute(1, "encoding", null, checkLower: true, System.SR.XmlInvalidEncoding_UTF8))
            {
                if (_attributeCount == 3 && !CheckStandalone(2))
                {
                    XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.XmlMalformedDecl));
                }
            }
            else if (!CheckStandalone(1) || _attributeCount > 2)
            {
                XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.XmlMalformedDecl));
            }
        }
        if (_declarationNode == null)
        {
            _declarationNode = new XmlDeclarationNode(_bufferReader);
        }
        MoveToNode(_declarationNode);
        return _declarationNode;
    }
References System.Xml.XmlBaseReader.NamespaceManager._attributeCount, System.Xml.XmlBaseReader.NamespaceManager._bufferReader, System.Xml.XmlBaseReader._declarationNode, System.Xml.XmlBaseReader.CheckDeclAttribute(), System.Xml.XmlBaseReader.CheckStandalone(), System.Xml.Dictionary, System.Xml.XmlBaseReader.MoveToNode(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.SR.XmlDeclMissingVersion, System.Xml.XmlException, System.SR.XmlInvalidEncoding_UTF8, System.SR.XmlInvalidVersion, and System.SR.XmlMalformedDecl.
Referenced by System.Xml.XmlBaseReader.MoveToElement(), and System.Xml.XmlUTF8TextReader.ReadDeclaration().