Terraria: System.Xml.XmlBaseReader.ReadElementContentAsString
ReadElementContentAsString() [1/2]
override string System.Xml.XmlBaseReader.ReadElementContentAsString () inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Reimplemented in System.Xml.XmlBinaryReader.
Definition at line 2290 of file XmlBaseReader.cs.
    {
        if (_node.NodeType != XmlNodeType.Element)
        {
            MoveToStartElement();
        }
        if (_node.IsEmptyElement)
        {
            Read();
            return string.Empty;
        }
        Read();
        string result = ReadContentAsString();
        ReadEndElement();
        return result;
    }
References System.Xml.XmlBaseReader._node, System.Xml.XmlBaseReader.XmlNode.IsEmptyElement, System.Xml.XmlDictionaryReader.MoveToStartElement(), System.Xml.XmlBaseReader.XmlNode.NodeType, System.Xml.XmlReader.Read(), System.Xml.XmlBaseReader.ReadContentAsString(), and System.Xml.XmlBaseReader.ReadEndElement().