Terraria: System.Xml.XmlBaseReader.ReadBytes
ReadBytes()
int System.Xml.XmlBaseReader.ReadBytes (Encoding encoding, int byteBlock, int charBlock, byte[] buffer, int offset, int byteCount, bool readContent) inline private inherited
Definition at line 2520 of file XmlBaseReader.cs.
    {
        if (_trailByteCount > 0)
        {
            int num = Math.Min(_trailByteCount, byteCount);
            Buffer.BlockCopy(_trailBytes, 0, buffer, offset, num);
            _trailByteCount -= num;
            Buffer.BlockCopy(_trailBytes, num, _trailBytes, 0, _trailByteCount);
            return num;
        }
        XmlNodeType nodeType = _node.NodeType;
        if (nodeType == XmlNodeType.Element || nodeType == XmlNodeType.EndElement)
        {
            return 0;
        }
        int num2 = ((byteCount >= byteBlock) ? (byteCount / byteBlock * charBlock) : charBlock);
        char[] charBuffer = GetCharBuffer(num2);
        int num3 = 0;
        while (true)
        {
            if (_trailCharCount > 0)
            {
                Array.Copy(_trailChars, 0, charBuffer, num3, _trailCharCount);
                num3 += _trailCharCount;
                _trailCharCount = 0;
            }
            while (num3 < charBlock)
            {
                int num4;
                if (readContent)
                {
                    num4 = ReadContentAsChars(charBuffer, num3, num2 - num3);
                    if (num4 == 1 && charBuffer[num3] == '\n')
                    {
                        continue;
                    }
                }
                else
                {
                    num4 = ReadValueChunk(charBuffer, num3, num2 - num3);
                }
                if (num4 == 0)
                {
                    break;
                }
                num3 += num4;
            }
            if (num3 >= charBlock)
            {
                _trailCharCount = num3 % charBlock;
                if (_trailCharCount > 0)
                {
                    if (_trailChars == null)
                    {
                        _trailChars = new char[4];
                    }
                    num3 -= _trailCharCount;
                    Array.Copy(charBuffer, num3, _trailChars, 0, _trailCharCount);
                }
            }
            try
            {
                if (byteCount < byteBlock)
                {
                    if (_trailBytes == null)
                    {
                        _trailBytes = new byte[3];
                    }
                    _trailByteCount = encoding.GetBytes(charBuffer, 0, num3, _trailBytes, 0);
                    int num5 = Math.Min(_trailByteCount, byteCount);
                    Buffer.BlockCopy(_trailBytes, 0, buffer, offset, num5);
                    _trailByteCount -= num5;
                    Buffer.BlockCopy(_trailBytes, num5, _trailBytes, 0, _trailByteCount);
                    return num5;
                }
                return encoding.GetBytes(charBuffer, 0, num3, buffer, offset);
            }
            catch (FormatException ex)
            {
                int num6 = 0;
                int num7 = 0;
                while (true)
                {
                    if (num7 < num3 && XmlConverter.IsWhitespace(charBuffer[num7]))
                    {
                        num7++;
                        continue;
                    }
                    if (num7 == num3)
                    {
                        break;
                    }
                    charBuffer[num6++] = charBuffer[num7++];
                }
                if (num6 == num3)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new XmlException(ex.Message, ex.InnerException));
                }
                num3 = num6;
            }
        }
    }
References System.Xml.XmlBaseReader._node, System.Xml.XmlBaseReader._trailByteCount, System.Xml.XmlBaseReader._trailBytes, System.Xml.XmlBaseReader._trailCharCount, System.Xml.XmlBaseReader._trailChars, System.Buffer.BlockCopy(), System.buffer, System.byteCount, System.Array.Copy(), System.Xml.Dictionary, System.Text.Encoding.GetBytes(), System.Xml.XmlBaseReader.GetCharBuffer(), System.Xml.XmlConverter.IsWhitespace(), System.Math.Min(), System.Xml.XmlBaseReader.XmlNode.NodeType, System.offset, System.Xml.XmlDictionaryReader.ReadContentAsChars(), System.Xml.XmlBaseReader.ReadValueChunk(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Xml.XmlException.
Referenced by System.Xml.XmlBaseReader.ReadContentAsBase64(), System.Xml.XmlBaseReader.ReadContentAsBinHex(), and System.Xml.XmlBaseReader.ReadValueAsBase64().