Terraria: System.Array.Fill< T >
Fill< T >() [2/2]
static void System.Array.Fill< T > (T[] array, T value, int startIndex, int count) inline static
Definition at line 1603 of file Array.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        if ((uint)startIndex > (uint)array.Length)
        {
            ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index();
        }
        if ((uint)count > (uint)(array.Length - startIndex))
        {
            ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count();
        }
        if (!typeof(T).IsValueType && array.GetType() != typeof(T[]))
        {
            for (int i = startIndex; i < startIndex + count; i++)
            {
                array[i] = value;
            }
        }
        else
        {
            new Span<T>(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(array), (nint)(uint)startIndex), count).Fill(value);
        }
    }
References System.array, System.count, System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.startIndex, System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count(), System.ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index(), and System.value.