Terraria: System.Xml.XmlBaseReader.Close
Close()
override void System.Xml.XmlBaseReader.Close () inline virtual
Reimplemented from System.Xml.XmlReader.
Reimplemented in System.Xml.XmlBinaryReader, and System.Xml.XmlUTF8TextReader.
Definition at line 1612 of file XmlBaseReader.cs.
    {
        MoveToNode(s_closedNode);
        _nameTable = null;
        if (_attributeNodes != null && _attributeNodes.Length > 16)
        {
            _attributeNodes = null;
        }
        if (_elementNodes != null && _elementNodes.Length > 16)
        {
            _elementNodes = null;
        }
        _nsMgr.Close();
        _bufferReader.Close();
        if (_signingWriter != null)
        {
            _signingWriter.Close();
        }
        if (_attributeSorter != null)
        {
            _attributeSorter.Close();
        }
    }
References System.Xml.XmlBaseReader._attributeNodes, System.Xml.XmlBaseReader._attributeSorter, System.Xml.XmlBaseReader.NamespaceManager._bufferReader, System.Xml.XmlBaseReader._elementNodes, System.Xml.XmlBaseReader._nameTable, System.Xml.XmlBaseReader._nsMgr, System.Xml.XmlBaseReader._signingWriter, System.Xml.XmlBaseReader.AttributeSorter.Close(), System.Xml.XmlBaseReader.NamespaceManager.Close(), System.Xml.XmlBufferReader.Close(), System.Xml.XmlSigningNodeWriter.Close(), System.Xml.XmlBaseReader.MoveToNode(), and System.Xml.XmlBaseReader.s_closedNode.