Terraria: System.Array.LastIndexOf
LastIndexOf() [3/3]
static int System.Array.LastIndexOf (Array array, object? value, int startIndex, int count) inline static
Definition at line 2015 of file Array.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        int lowerBound = array.GetLowerBound(0);
        if (array.Length == 0)
        {
            return lowerBound - 1;
        }
        if (startIndex < lowerBound || startIndex >= array.Length + lowerBound)
        {
            ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index();
        }
        if (count < 0)
        {
            ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count();
        }
        if (count > startIndex - lowerBound + 1)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.endIndex, ExceptionResource.ArgumentOutOfRange_EndIndexStartIndex);
        }
        if (array.Rank != 1)
        {
            ThrowHelper.ThrowRankException(ExceptionResource.Rank_MultiDimNotSupported);
        }
        int num = startIndex - count + 1;
        if (array is object[] array2)
        {
            if (value == null)
            {
                for (int num2 = startIndex; num2 >= num; num2--)
                {
                    if (array2[num2] == null)
                    {
                        return num2;
                    }
                }
            }
            else
            {
                for (int num3 = startIndex; num3 >= num; num3--)
                {
                    object obj = array2[num3];
                    if (obj != null && obj.Equals(value))
                    {
                        return num3;
                    }
                }
            }
            return -1;
        }
        CorElementType corElementTypeOfElementType = array.GetCorElementTypeOfElementType();
        if (corElementTypeOfElementType.IsPrimitiveType())
        {
            if (value == null)
            {
                return lowerBound - 1;
            }
            if (array.IsValueOfElementType(value))
            {
                int adjustedIndex2 = num - lowerBound;
                int num4 = -1;
                switch (corElementTypeOfElementType)
                {
                case CorElementType.ELEMENT_TYPE_BOOLEAN:
                case CorElementType.ELEMENT_TYPE_I1:
                case CorElementType.ELEMENT_TYPE_U1:
                    num4 = GenericLastIndexOf<byte>(array, value, adjustedIndex2, count);
                    break;
                case CorElementType.ELEMENT_TYPE_CHAR:
                case CorElementType.ELEMENT_TYPE_I2:
                case CorElementType.ELEMENT_TYPE_U2:
                    num4 = GenericLastIndexOf<char>(array, value, adjustedIndex2, count);
                    break;
                case CorElementType.ELEMENT_TYPE_I4:
                case CorElementType.ELEMENT_TYPE_U4:
                    num4 = GenericLastIndexOf<int>(array, value, adjustedIndex2, count);
                    break;
                case CorElementType.ELEMENT_TYPE_I8:
                case CorElementType.ELEMENT_TYPE_U8:
                case CorElementType.ELEMENT_TYPE_I:
                case CorElementType.ELEMENT_TYPE_U:
                    num4 = GenericLastIndexOf<long>(array, value, adjustedIndex2, count);
                    break;
                case CorElementType.ELEMENT_TYPE_R4:
                    num4 = GenericLastIndexOf<float>(array, value, adjustedIndex2, count);
                    break;
                case CorElementType.ELEMENT_TYPE_R8:
                    num4 = GenericLastIndexOf<double>(array, value, adjustedIndex2, count);
                    break;
                }
                return ((num4 >= 0) ? num : lowerBound) + num4;
            }
        }
        for (int num5 = startIndex; num5 >= num; num5--)
        {
            object value2 = array.GetValue(num5);
            if (value2 == null)
            {
                if (value == null)
                {
                    return num5;
                }
            }
            else if (value2.Equals(value))
            {
                return num5;
            }
        }
        return lowerBound - 1;
        static int GenericLastIndexOf<T>(Array array, object value, int adjustedIndex, int length) where T : struct, IEquatable<T>
        {
            return UnsafeArrayAsSpan<T>(array, adjustedIndex, length).LastIndexOf(Unsafe.As<byte, T>(ref value.GetRawData()));
        }
    }
References System.array, System.count, System.length, System.obj, System.startIndex, System.T, System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), System.ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count(), System.ThrowHelper.ThrowRankException(), System.ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index(), System.Array.UnsafeArrayAsSpan< T >(), and System.value.