Terraria: System.Array.CopyTo
CopyTo() [1/3]
void System.Array.CopyTo (Array array, int index) inline
Definition at line 1555 of file Array.cs.
    {
        if (array != null && array.Rank != 1)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_RankMultiDimNotSupported);
        }
        Copy(this, GetLowerBound(0), array, index, Length);
    }
References System.array, System.Array.Copy(), System.Array.GetLowerBound(), System.index, System.Array.Length, and System.ThrowHelper.ThrowArgumentException().
Referenced by System.Array.CopyTo(), and System.Collections.Generic.EnumerableHelpers.ToArray< T >().