Terraria: System.Array.Copy
Copy() [3/5]
static unsafe void System.Array.Copy (Array sourceArray, int sourceIndex, Array destinationArray, int destinationIndex, int length) inline static
Definition at line 655 of file Array.cs.
    {
        if (sourceArray != null && destinationArray != null)
        {
            MethodTable* methodTable = RuntimeHelpers.GetMethodTable(sourceArray);
            if (methodTable == RuntimeHelpers.GetMethodTable(destinationArray) && !methodTable->IsMultiDimensionalArray && length >= 0 && sourceIndex >= 0 && destinationIndex >= 0 && (uint)(sourceIndex + length) <= sourceArray.NativeLength && (uint)(destinationIndex + length) <= destinationArray.NativeLength)
            {
                nuint num = methodTable->ComponentSize;
                nuint num2 = (uint)length * num;
                ref byte reference = ref Unsafe.AddByteOffset(ref Unsafe.As<RawArrayData>(sourceArray).Data, (uint)sourceIndex * num);
                ref byte reference2 = ref Unsafe.AddByteOffset(ref Unsafe.As<RawArrayData>(destinationArray).Data, (uint)destinationIndex * num);
                if (methodTable->ContainsGCPointers)
                {
                    Buffer.BulkMoveWithWriteBarrier(ref reference2, ref reference, num2);
                }
                else
                {
                    Buffer.Memmove(ref reference2, ref reference, num2);
                }
                return;
            }
        }
        Copy(sourceArray, sourceIndex, destinationArray, destinationIndex, length, reliable: false);
    }
References System.Buffer.BulkMoveWithWriteBarrier(), System.Array.Copy(), System.Runtime.CompilerServices.RawArrayData.Data, System.destinationArray, System.destinationIndex, System.Runtime.CompilerServices.RuntimeHelpers.GetMethodTable(), System.length, System.Buffer.Memmove(), System.sourceArray, and System.sourceIndex.