Terraria: System.Array.Reverse
Reverse() [2/2]
static void System.Array.Reverse (Array array, int index, int length) inline static
Definition at line 2216 of file Array.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        int lowerBound = array.GetLowerBound(0);
        if (index < lowerBound)
        {
            ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException();
        }
        if (length < 0)
        {
            ThrowHelper.ThrowLengthArgumentOutOfRange_ArgumentOutOfRange_NeedNonNegNum();
        }
        if (array.Length - (index - lowerBound) < length)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Argument_InvalidOffLen);
        }
        if (array.Rank != 1)
        {
            ThrowHelper.ThrowRankException(ExceptionResource.Rank_MultiDimNotSupported);
        }
        if (length <= 1)
        {
            return;
        }
        int adjustedIndex = index - lowerBound;
        switch (array.GetCorElementTypeOfElementType())
        {
        case CorElementType.ELEMENT_TYPE_BOOLEAN:
        case CorElementType.ELEMENT_TYPE_I1:
        case CorElementType.ELEMENT_TYPE_U1:
            UnsafeArrayAsSpan<byte>(array, adjustedIndex, length).Reverse();
            return;
        case CorElementType.ELEMENT_TYPE_CHAR:
        case CorElementType.ELEMENT_TYPE_I2:
        case CorElementType.ELEMENT_TYPE_U2:
            UnsafeArrayAsSpan<short>(array, adjustedIndex, length).Reverse();
            return;
        case CorElementType.ELEMENT_TYPE_I4:
        case CorElementType.ELEMENT_TYPE_U4:
        case CorElementType.ELEMENT_TYPE_R4:
            UnsafeArrayAsSpan<int>(array, adjustedIndex, length).Reverse();
            return;
        case CorElementType.ELEMENT_TYPE_I8:
        case CorElementType.ELEMENT_TYPE_U8:
        case CorElementType.ELEMENT_TYPE_R8:
        case CorElementType.ELEMENT_TYPE_I:
        case CorElementType.ELEMENT_TYPE_U:
            UnsafeArrayAsSpan<long>(array, adjustedIndex, length).Reverse();
            return;
        case CorElementType.ELEMENT_TYPE_ARRAY:
        case CorElementType.ELEMENT_TYPE_OBJECT:
        case CorElementType.ELEMENT_TYPE_SZARRAY:
            UnsafeArrayAsSpan<object>(array, adjustedIndex, length).Reverse();
            return;
        }
        int num = index;
        int num2 = index + length - 1;
        while (num < num2)
        {
            object value = array.GetValue(num);
            array.SetValue(array.GetValue(num2), num);
            array.SetValue(value, num2);
            num++;
            num2--;
        }
    }
References System.array, System.index, System.length, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException(), System.ThrowHelper.ThrowLengthArgumentOutOfRange_ArgumentOutOfRange_NeedNonNegNum(), System.ThrowHelper.ThrowRankException(), and System.value.