Terraria: System.Xml.XmlBaseReader.MoveToEndOfFile
MoveToEndOfFile()
void System.Xml.XmlBaseReader.MoveToEndOfFile () inline protected inherited
Definition at line 1467 of file XmlBaseReader.cs.
    {
        if (_depth != 0)
        {
            XmlExceptionHelper.ThrowUnexpectedEndOfFile(this);
        }
        MoveToNode(s_endOfFileNode);
    }
References System.Xml.XmlBaseReader.NamespaceManager._depth, System.Xml.XmlBaseReader.MoveToNode(), System.Xml.XmlBaseReader.s_endOfFileNode, and System.Xml.XmlExceptionHelper.ThrowUnexpectedEndOfFile().
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.Read(), System.Xml.XmlUTF8TextReader.Read(), and System.Xml.XmlBinaryReader.ReadNode().