Terraria: System.Array.LastIndexOf< T >
LastIndexOf< T >() [3/3]
static int System.Array.LastIndexOf< T > (T[] array, T value, int startIndex, int count) inline static
Definition at line 2151 of file Array.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        if (array.Length == 0)
        {
            if (startIndex != -1 && startIndex != 0)
            {
                ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index();
            }
            if (count != 0)
            {
                ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count();
            }
            return -1;
        }
        if ((uint)startIndex >= (uint)array.Length)
        {
            ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index();
        }
        if (count < 0 || startIndex - count + 1 < 0)
        {
            ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count();
        }
        if (RuntimeHelpers.IsBitwiseEquatable<T>())
        {
            if (Unsafe.SizeOf<T>() == 1)
            {
                int num = startIndex - count + 1;
                int num2 = SpanHelpers.LastIndexOf(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Unsafe.As<byte[]>(array)), num), Unsafe.As<T, byte>(ref value), count);
                return ((num2 >= 0) ? num : 0) + num2;
            }
            if (Unsafe.SizeOf<T>() == 2)
            {
                int num3 = startIndex - count + 1;
                int num4 = SpanHelpers.LastIndexOf(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Unsafe.As<char[]>(array)), num3), Unsafe.As<T, char>(ref value), count);
                return ((num4 >= 0) ? num3 : 0) + num4;
            }
            if (Unsafe.SizeOf<T>() == 4)
            {
                int num5 = startIndex - count + 1;
                int num6 = SpanHelpers.LastIndexOf(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Unsafe.As<int[]>(array)), num5), Unsafe.As<T, int>(ref value), count);
                return ((num6 >= 0) ? num5 : 0) + num6;
            }
            if (Unsafe.SizeOf<T>() == 8)
            {
                int num7 = startIndex - count + 1;
                int num8 = SpanHelpers.LastIndexOf(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Unsafe.As<long[]>(array)), num7), Unsafe.As<T, long>(ref value), count);
                return ((num8 >= 0) ? num7 : 0) + num8;
            }
        }
        return EqualityComparer<T>.Default.LastIndexOf(array, value, startIndex, count);
    }
References System.array, System.count, System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.SpanHelpers.LastIndexOf(), System.startIndex, System.T, System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count(), System.ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index(), and System.value.