Terraria: System.Array.Copy
Copy() [4/5]
static unsafe void System.Array.Copy (Array sourceArray, int sourceIndex, Array destinationArray, int destinationIndex, int length, bool reliable) inline static private
Definition at line 680 of file Array.cs.
    {
        if (sourceArray == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.sourceArray);
        }
        if (destinationArray == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.destinationArray);
        }
        if (sourceArray.GetType() != destinationArray.GetType() && sourceArray.Rank != destinationArray.Rank)
        {
            throw new RankException(SR.Rank_MustMatch);
        }
        if (length < 0)
        {
            throw new ArgumentOutOfRangeException("length", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        int lowerBound = sourceArray.GetLowerBound(0);
        if (sourceIndex < lowerBound || sourceIndex - lowerBound < 0)
        {
            throw new ArgumentOutOfRangeException("sourceIndex", SR.ArgumentOutOfRange_ArrayLB);
        }
        sourceIndex -= lowerBound;
        int lowerBound2 = destinationArray.GetLowerBound(0);
        if (destinationIndex < lowerBound2 || destinationIndex - lowerBound2 < 0)
        {
            throw new ArgumentOutOfRangeException("destinationIndex", SR.ArgumentOutOfRange_ArrayLB);
        }
        destinationIndex -= lowerBound2;
        if ((uint)(sourceIndex + length) > sourceArray.NativeLength)
        {
            throw new ArgumentException(SR.Arg_LongerThanSrcArray, "sourceArray");
        }
        if ((uint)(destinationIndex + length) > destinationArray.NativeLength)
        {
            throw new ArgumentException(SR.Arg_LongerThanDestArray, "destinationArray");
        }
        if (sourceArray.GetType() == destinationArray.GetType() || IsSimpleCopy(sourceArray, destinationArray))
        {
            MethodTable* methodTable = RuntimeHelpers.GetMethodTable(sourceArray);
            nuint num = methodTable->ComponentSize;
            nuint num2 = (uint)length * num;
            ref byte reference = ref Unsafe.AddByteOffset(ref MemoryMarshal.GetArrayDataReference(sourceArray), (uint)sourceIndex * num);
            ref byte reference2 = ref Unsafe.AddByteOffset(ref MemoryMarshal.GetArrayDataReference(destinationArray), (uint)destinationIndex * num);
            if (methodTable->ContainsGCPointers)
            {
                Buffer.BulkMoveWithWriteBarrier(ref reference2, ref reference, num2);
            }
            else
            {
                Buffer.Memmove(ref reference2, ref reference, num2);
            }
        }
        else
        {
            if (reliable)
            {
                throw new ArrayTypeMismatchException(SR.ArrayTypeMismatch_ConstrainedCopy);
            }
            CopySlow(sourceArray, sourceIndex, destinationArray, destinationIndex, length);
        }
    }
References System.SR.Arg_LongerThanDestArray, System.SR.Arg_LongerThanSrcArray, System.SR.ArgumentOutOfRange_ArrayLB, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.SR.ArrayTypeMismatch_ConstrainedCopy, System.Buffer.BulkMoveWithWriteBarrier(), System.Array.CopySlow(), System.destinationArray, System.destinationIndex, System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.Runtime.CompilerServices.RuntimeHelpers.GetMethodTable(), System.Array.IsSimpleCopy(), System.length, System.Buffer.Memmove(), System.SR.Rank_MustMatch, System.sourceArray, System.sourceIndex, and System.ThrowHelper.ThrowArgumentNullException().