Terraria: System.Array.Copy
Copy() [1/5]
static unsafe void System.Array.Copy (Array sourceArray, Array destinationArray, int length) inline static
Definition at line 624 of file Array.cs.
    {
        if (sourceArray == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.sourceArray);
        }
        if (destinationArray == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.destinationArray);
        }
        MethodTable* methodTable = RuntimeHelpers.GetMethodTable(sourceArray);
        if (methodTable == RuntimeHelpers.GetMethodTable(destinationArray) && !methodTable->IsMultiDimensionalArray && (uint)length <= sourceArray.NativeLength && (uint)length <= destinationArray.NativeLength)
        {
            nuint num = (nuint)(uint)length * (nuint)methodTable->ComponentSize;
            ref byte data = ref Unsafe.As<RawArrayData>(sourceArray).Data;
            ref byte data2 = ref Unsafe.As<RawArrayData>(destinationArray).Data;
            if (methodTable->ContainsGCPointers)
            {
                Buffer.BulkMoveWithWriteBarrier(ref data2, ref data, num);
            }
            else
            {
                Buffer.Memmove(ref data2, ref data, num);
            }
        }
        else
        {
            Copy(sourceArray, sourceArray.GetLowerBound(0), destinationArray, destinationArray.GetLowerBound(0), length, reliable: false);
        }
    }
References System.Buffer.BulkMoveWithWriteBarrier(), System.Array.Copy(), System.destinationArray, System.Runtime.CompilerServices.RuntimeHelpers.GetMethodTable(), System.length, System.Buffer.Memmove(), System.sourceArray, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by Terraria.Modules.AnchorTypesModule.AnchorTypesModule(), System.Numerics.BigInteger.BigInteger(), System.Numerics.BigInteger.BigInteger(), System.Collections.BitArray.BitArray(), System.Collections.BitArray.BitArray(), System.Numerics.BigIntegerCalculator.BitsBuffer.BitsBuffer(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ClassDataContractCriticalHelper(), System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder(), System.Reflection.Emit.MethodBuilder.MethodBuilder(), System.Text.RegularExpressions.RegexBoyerMoore.RegexBoyerMoore(), System.Reflection.Emit.SymbolMethod.SymbolMethod(), Terraria.Modules.TileObjectCoordinatesModule.TileObjectCoordinatesModule(), System.ComponentModel.DataAnnotations.UIHintAttribute.UIHintImplementation.UIHintImplementation(), System.ComponentModel.Container.Add(), System.Xml.XmlBinaryReaderSession.Add(), System.Net.Http.Headers.ObjectCollection< T >.Add(), System.Threading.Tasks.Dataflow.Internal.ImmutableArray< T >.Add(), System.Xml.Resolvers.XmlPreloadedResolver.Add(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueueList.Add(), System.Security.Cryptography.CryptoConfig.AddAlgorithm(), System.Data.FunctionNode.AddArgument(), System.Xml.XmlBaseReader.NamespaceManager.AddAttribute(), System.Xml.XmlBaseWriter.NamespaceManager.AddAttribute(), System.Xml.XsdCachingReader.AddAttribute(), System.Xml.XmlBaseReader.AddAttribute(), System.Xml.XmlCanonicalWriter.AddAttribute(), System.Xml.XmlWellFormedWriter.AddAttribute(), System.Xml.XsdValidatingReader.AddAttributePSVI(), System.Text.RegularExpressions.RegexCompiler.AddBacktrackNote(), System.Xml.XsdCachingReader.AddContent(), System.Xml.XmlTextReaderImpl.AddDefaultAttributesAndNormalize(), System.Diagnostics.Tracing.EventSource.AddEventDescriptor(), System.Xml.XmlWellFormedWriter.AttributeValueCache.AddItem(), System.Xml.Serialization.ReflectionXmlSerializationReader.AddItemInArrayMember(), System.Xml.XmlSqlBinaryReader.AddName(), System.Xml.XmlBaseReader.NamespaceManager.AddNamespace(), System.Xml.XmlSubtreeReader.AddNamespace(), System.Xml.XmlWellFormedWriter.AddNamespace(), System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace(), System.Xml.Xsl.Runtime.XmlQueryRuntime.AddNewIndex(), System.Runtime.Serialization.ObjectManager.AddObjectHolder(), System.Security.Cryptography.CryptoConfig.AddOID(), System.Runtime.CompilerServices.RuleCache< T >.AddOrInsert(), System.Text.EncodingProvider.AddProvider(), System.Xml.XmlSqlBinaryReader.AddQName(), System.Collections.Immutable.ImmutableArray< T >.Builder.AddRange(), System.Collections.Immutable.ImmutableArray< T >.Builder.AddRange(), System.Collections.Immutable.ImmutableArray< T >.Builder.AddRange< TDerived >(), System.Xml.Xsl.Xslt.CompilerScopeManager< V >.AddRecord(), System.Xml.Xsl.Xslt.OutputScopeManager.AddRecord(), System.Runtime.CompilerServices.CallSite< T >.AddRule(), System.Transactions.TransactionState.AddVolatileEnlistment(), System.Xml.XmlCanonicalWriter.AddXmlnsAttribute(), MS.Internal.Xml.XPath.XPathMultyIterator.Advance(), System.Collections.Generic.LargeArrayBuilder< T >.AllocateBuffer(), System.Xml.XmlTextReaderImpl.AllocNode(), System.Data.RBTree< K >.AllocPage(), System.Xml.XmlTextReaderImpl.AttributeDuplCheck(), System.Reflection.Emit.ILGenerator.BakeByteArray(), System.DefaultBinder.BindToMethod(), System.Xml.DocumentSchemaValidator.CheckNodeSequenceCapacity(), System.Data.DataError.Clear(), System.Collections.Queue.Clone(), System.Collections.SortedList.Clone(), System.Collections.Stack.Clone(), System.Collections.ArrayList.Clone(), System.Array.ConstrainedCopy(), System.Array.Copy(), System.Array.Copy(), System.Array.Copy(), System.Array.Copy(), System.Linq.Parallel.GrowingArray< T >.CopyFrom(), System.Collections.SortedList.KeyList.CopyTo(), System.Collections.SortedList.ValueList.CopyTo(), System.Collections.Generic.SortedList< TKey, TValue >.KeyList.CopyTo(), System.Collections.Generic.Stack< T >.CopyTo(), System.Collections.Generic.List< T >.CopyTo(), System.Collections.ArrayList.CopyTo(), System.Collections.Concurrent.BlockingCollection< T >.CopyTo(), System.Collections.Immutable.ImmutableArray< T >.CopyTo(), System.Collections.Queue.CopyTo(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.UnorderedItemsCollection.CopyTo(), System.Collections.Generic.SortedList< TKey, TValue >.ValueList.CopyTo(), System.Collections.BitArray.CopyTo(), System.ComponentModel.AttributeCollection.CopyTo(), System.ComponentModel.EventDescriptorCollection.CopyTo(), System.ComponentModel.PropertyDescriptorCollection.CopyTo(), System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.CopyTo(), System.Collections.Generic.Queue< T >.CopyTo(), System.Array.CopyTo(), System.Xml.Xsl.Runtime.XmlQuerySequence< T >.CopyTo(), System.ArraySegment< T >.CopyTo(), System.Collections.Generic.LargeArrayBuilder< T >.CopyTo(), System.Collections.ArrayList.CopyTo(), System.Collections.Generic.List< T >.CopyTo(), System.Collections.Immutable.ImmutableArray< T >.CopyTo(), System.RuntimeType.ListBuilder< T >.CopyTo(), System.Security.Cryptography.OidCollection.CopyTo(), System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.CopyTo(), System.Net.Http.Headers.ObjectCollection< T >.CopyTo(), System.Collections.Generic.List< T >.CopyTo(), System.Collections.Generic.Queue< T >.CopyTo(), System.Collections.Generic.LargeArrayBuilder< T >.CopyTo(), System.Collections.Immutable.ImmutableArray< T >.Builder.CopyTo(), System.Collections.Immutable.ImmutableArray< T >.CopyTo(), System.Collections.Immutable.ImmutableArray< T >.CopyTo(), System.ArraySegment< T >.CopyTo(), System.Linq.Grouping< TKey, TElement >.CopyTo(), System.Collections.Generic.SortedList< TKey, TValue >.KeyList.CopyTo(), System.Collections.Generic.SortedList< TKey, TValue >.ValueList.CopyTo(), System.SZArrayHelper.CopyTo< T >(), System.Collections.Immutable.ImmutableArray< T >.Create< T >(), System.Collections.Immutable.ImmutableArray< T >.Create< T >(), System.Runtime.Serialization.ClassDataContract.CreateChildElementNamespaces(), Internal.Cryptography.TripleDesImplementation.CreateTransform(), System.IO.Compression.InflaterManaged.DecodeDynamicBlockHeader(), System.Xml.Xsl.IlGen.XmlILModule.DefineMethod(), System.Text.RegularExpressions.RegexRunner.DoubleCrawl(), System.Text.RegularExpressions.RegexRunner.DoubleStack(), System.Text.RegularExpressions.RegexRunner.DoubleTrack(), System.Runtime.Serialization.ObjectManager.DoValueTypeFixup(), System.Runtime.Serialization.FixupHolderList.EnlargeArray(), System.Runtime.Serialization.LongList.EnlargeArray(), System.Runtime.Serialization.ObjectHolderList.EnlargeArray(), System.Reflection.Emit.ILGenerator.EnlargeArray< T >(), System.Xml.Serialization.XmlSerializationReader.EnsureArrayIndex(), System.Xml.Serialization.XmlSerializationCodeGen.EnsureArrayIndex(), System.Xml.Serialization.XmlSerializationILGen.EnsureArrayIndex(), System.Runtime.Serialization.XmlObjectSerializerReadContext.EnsureArraySize< T >(), System.Xml.Xsl.Runtime.XmlAttributeCache.EnsureAttributeCache(), System.Reflection.Emit.ScopeTree.EnsureCapacity(), System.Collections.Generic.ArrayBuilder< T >.EnsureCapacity(), System.Reflection.Emit.LocalSymInfo.EnsureCapacityNamespace(), System.Diagnostics.Tracing.CounterGroup.EnsureEventSourceIndexAvailable(), System.ComponentModel.EventDescriptorCollection.EnsureEventsOwned(), System.Xml.Schema.BitSet.EnsureLength(), System.ComponentModel.PropertyDescriptorCollection.EnsurePropsOwned(), System.ComponentModel.EventDescriptorCollection.EnsureSize(), System.ComponentModel.PropertyDescriptorCollection.EnsureSize(), System.Xml.Xsl.XsltOld.BuilderInfo.EnsureTextInfoSize(), System.Runtime.Serialization.Json.XmlJsonReader.EnterJsonScope(), System.Xml.XmlBaseReader.EnterScope(), System.Xml.XmlBaseWriter.EnterScope(), System.Runtime.Serialization.Json.XmlJsonWriter.EnterScope(), System.Runtime.Serialization.SerializationInfo.ExpandArrays(), System.Xml.Xsl.Xslt.XsltInput.ExtendRecordBuffer(), System.Xml.XmlSqlBinaryReader.FillAllowEOF(), System.Dynamic.ExpandoClass.FindNewClass(), System.Xml.Xsl.Runtime.XmlSortKeyAccumulator.FinishSortKeys(), System.Linq.Parallel.AsynchronousChannel< T >.FlushCachedChunk(), System.ComponentModel.AttributeCollection.FromExisting(), System.ComponentModel.TypeDescriptor.AttributeProvider.AttributeTypeDescriptor.GetAttributes(), System.Data.Common.DataRecordInternal.GetBytes(), System.Data.DataTableReader.GetBytes(), System.Data.Common.DataRecordInternal.GetChars(), System.Data.DataTableReader.GetChars(), System.Transactions.TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken(), System.ComponentModel.PropertyDescriptor.GetEditor(), Terraria.Social.Steam.AchievementsSocialModule.GetEncryptionKey(), Terraria.Social.WeGame.AchievementsSocialModule.GetEncryptionKey(), System.ComponentModel.PropertyDescriptorCollection.GetEnumerator(), System.Reflection.Emit.ILGenerator.GetExceptions(), System.Diagnostics.StackTrace.GetFrames(), System.Reflection.RuntimePropertyInfo.GetIndexParameters(), Terraria.Social.Steam.Lobby.GetMessage(), System.Runtime.InteropServices.Marshal.GetObjectsForNativeVariants< T >(), System.Diagnostics.Tracing.ConcurrentSet< KeyType, ItemType >.GetOrAdd(), System.Reflection.Emit.DynamicMethod.RTDynamicMethod.GetParameters(), System.Reflection.RuntimeConstructorInfo.GetParameters(), System.Reflection.RuntimeMethodInfo.GetParameters(), System.Diagnostics.NtProcessManager.GetProcessIds(), System.Transactions.Transaction.GetPromotedToken(), System.Data.Common.DbConnectionStringBuilder.GetProperties(), System.Collections.Generic.List< T >.GetRange(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetRenderTargets(), System.Reflection.Emit.SignatureHelper.GetSignature(), System.Data.ColumnTypeConverter.GetStandardValues(), System.ComponentModel.CultureInfoConverter.GetStandardValues(), System.ComponentModel.TypeListConverter.GetStandardValues(), System.Reflection.Emit.ILGenerator.GetTokenFixups(), System.Reflection.Assembly.GetTypes(), System.Data.DataTableReader.GetValues(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetVertexBuffers(), System.Collections.Generic.Deque< T >.Grow(), System.Text.SegmentStringBuilder.GrowAndAdd(), System.Xml.XmlSqlBinaryReader.GrowAttributes(), System.Runtime.Serialization.ElementData.GrowAttributesIfNeeded(), System.Xml.XmlSqlBinaryReader.GrowElements(), System.Runtime.Serialization.ExtensionDataReader.GrowElementsIfNeeded(), System.Data.RecordManager.GrowRecordCapacity(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GrowTable(), System.Xml.XmlEncodedRawTextWriter.GrowTextContentMarks(), System.Runtime.Serialization.Formatters.Binary.SerStack.IncreaseCapacity(), System.Runtime.Serialization.Formatters.Binary.IntSizedArray.IncreaseCapacity(), System.Runtime.Serialization.Formatters.Binary.SizedArray.IncreaseCapacity(), System.Reflection.Emit.ILGenerator.IncreaseCapacity(), System.Data.DataError.IndexOf(), System.ComponentModel.EventDescriptorCollection.Insert(), System.Collections.SortedList.Insert(), System.Collections.ArrayList.Insert(), System.ComponentModel.PropertyDescriptorCollection.Insert(), System.Xml.Xsl.Qil.QilList.Insert(), System.Collections.Immutable.ImmutableArray< T >.Builder.Insert(), System.Collections.Immutable.ImmutableArray< T >.Insert(), System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.Insert(), System.Collections.Generic.List< T >.Insert(), System.Collections.Generic.SortedList< TKey, TValue >.Insert(), System.Globalization.CalendarData.InsertOrSwapOverride(), System.Collections.ArrayList.InsertRange(), System.Collections.Generic.List< T >.InsertRange(), System.Collections.Immutable.ImmutableArray< T >.InsertRange(), System.Collections.Immutable.ImmutableArray< T >.InsertRange(), System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(), System.Attribute.InternalParamGetCustomAttributes(), System.Collections.BitArray.LeftShift(), System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue.LocalPush(), System.Linq.Parallel.SortHelper< TInputOutput, TKey >.MergeSortCooperatively(), System.Data.DataTable.NewIndexDesc(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.NextRectangleMap(), Terraria.Social.Steam.NetServerSocialModule.OnPacketRead(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), System.Xml.DtdParser.ParseCondSection(), System.Xml.DtdParser.ParseCondSectionAsync(), System.Security.Cryptography.TripleDESCng.PreprocessKey(), System.Threading.PortableThreadPool.WaitThread.ProcessRemovals(), System.Xml.HWStack.Push(), System.Collections.Stack.Push(), System.Xml.Xsl.Runtime.XmlNavigatorStack.Push(), System.Xml.BitStack.PushCurr(), System.Xml.XmlTextReaderImpl.PushParsingState(), Terraria.Social.Steam.SteamP2PWriter.QueueSend(), Terraria.Social.WeGame.WeGameP2PWriter.QueueSend(), System.Data.SqlTypes.SqlBytes.Read(), System.Data.SqlTypes.SqlChars.Read(), System.Xml.ArrayHelper< TArgument, TArray >.ReadArray(), System.Xml.XmlBaseReader.ReadBytes(), Terraria.Social.Steam.SteamP2PReader.Receive(), Terraria.Social.WeGame.WeGameP2PReader.Receive(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetEvents(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetProperties(), System.ComponentModel.Container.Remove(), System.Net.Http.Headers.ObjectCollection< T >.Remove(), System.Threading.Tasks.Dataflow.Internal.ImmutableArray< T >.Remove(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueueList.Remove(), System.Collections.Immutable.ImmutableArray< T >.Builder.RemoveAt(), System.Collections.SortedList.RemoveAt(), System.Collections.Generic.SortedList< TKey, TValue >.RemoveAt(), System.ComponentModel.EventDescriptorCollection.RemoveAt(), System.ComponentModel.PropertyDescriptorCollection.RemoveAt(), System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.RemoveAt(), System.Collections.Generic.List< T >.RemoveAt(), System.Collections.ArrayList.RemoveAt(), System.Xml.Xsl.Qil.QilList.RemoveAt(), System.Collections.Immutable.ImmutableArray< T >.RemoveAtRange(), System.Dynamic.Utils.CollectionExtensions.RemoveFirst< T >(), System.Diagnostics.Tracing.EventSource.RemoveFirstArgIfRelatedActivityId(), System.Dynamic.Utils.CollectionExtensions.RemoveLast< T >(), System.Collections.Generic.List< T >.RemoveRange(), System.Collections.ArrayList.RemoveRange(), System.Collections.Immutable.ImmutableArray< T >.RemoveRange(), System.DefaultBinder.ReorderArgumentArray(), System.Linq.Parallel.HashLookup< TKey, TValue >.Resize(), System.Net.Http.HPack.DynamicTable.Resize(), System.Collections.Generic.Dictionary< TKey, TValue >.Resize(), System.Collections.Generic.HashSet< T >.Resize(), System.Data.ProviderBase.SchemaMapping.ResizeColumnArray(), System.Collections.BitArray.RightShift(), System.Threading.AsyncLocalValueMap.MultiElementAsyncLocalValueMap.Set(), System.Reflection.Emit.SymbolType.SetBounds(), System.Collections.Queue.SetCapacity(), System.Data.Common.BigIntegerStorage.SetCapacity(), System.Data.Common.BooleanStorage.SetCapacity(), System.Data.Common.ByteStorage.SetCapacity(), System.Data.Common.CharStorage.SetCapacity(), System.Data.Common.DateTimeOffsetStorage.SetCapacity(), System.Data.Common.DateTimeStorage.SetCapacity(), System.Data.Common.DecimalStorage.SetCapacity(), System.Data.Common.DoubleStorage.SetCapacity(), System.Data.Common.Int16Storage.SetCapacity(), System.Data.Common.Int32Storage.SetCapacity(), System.Data.Common.Int64Storage.SetCapacity(), System.Data.Common.ObjectStorage.SetCapacity(), System.Data.Common.SByteStorage.SetCapacity(), System.Data.Common.SingleStorage.SetCapacity(), System.Data.Common.SqlBinaryStorage.SetCapacity(), System.Data.Common.SqlBooleanStorage.SetCapacity(), System.Data.Common.SqlBytesStorage.SetCapacity(), System.Data.Common.SqlByteStorage.SetCapacity(), System.Data.Common.SqlCharsStorage.SetCapacity(), System.Data.Common.SqlDateTimeStorage.SetCapacity(), System.Data.Common.SqlDecimalStorage.SetCapacity(), System.Data.Common.SqlDoubleStorage.SetCapacity(), System.Data.Common.SqlGuidStorage.SetCapacity(), System.Data.Common.SqlInt16Storage.SetCapacity(), System.Data.Common.SqlInt32Storage.SetCapacity(), System.Data.Common.SqlInt64Storage.SetCapacity(), System.Data.Common.SqlMoneyStorage.SetCapacity(), System.Data.Common.SqlSingleStorage.SetCapacity(), System.Data.Common.SqlStringStorage.SetCapacity(), System.Data.Common.SqlUdtStorage.SetCapacity(), System.Data.Common.StringStorage.SetCapacity(), System.Data.Common.TimeSpanStorage.SetCapacity(), System.Data.Common.UInt16Storage.SetCapacity(), System.Data.Common.UInt32Storage.SetCapacity(), System.Data.Common.UInt64Storage.SetCapacity(), System.Collections.Generic.Queue< T >.SetCapacity(), System.Diagnostics.Tracing.TraceLoggingEventHandleTable.SetEventHandle(), System.Collections.Immutable.ImmutableArray< T >.SetItem(), System.Reflection.Emit.MethodBuilder.SetSignature(), System.Xml.Serialization.XmlSerializationReader.ShrinkArray(), System.Collections.Immutable.ImmutableArray< T >.Sort(), System.Xml.XmlCanonicalWriter.StartElement(), System.Collections.Immutable.ImmutableArray< T >.Builder.ToArray(), System.Collections.Queue.ToArray(), System.Collections.Generic.ArrayBuilder< T >.ToArray(), System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.ToArray(), System.Collections.Generic.List< T >.ToArray(), System.Collections.Generic.Queue< T >.ToArray(), System.Collections.ArrayList.ToArray(), System.ArraySegment< T >.ToArray(), System.Reflection.Metadata.BlobBuilder.ToArray(), System.Reflection.Metadata.BlobWriter.ToArray(), System.Collections.ArrayList.ToArray(), System.Xml.XmlEventCache.ToBytes(), System.Runtime.Serialization.XmlObjectSerializerReadContext.TrimArraySize< T >(), System.Diagnostics.Tracing.EventSource.TrimEventDescriptors(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.TryCopyFromFillBuffer(), System.Collections.Immutable.ImmutableExtensions.TryCopyTo< T >(), System.Data.Common.DbDataAdapter.Update(), System.Dynamic.ExpandoObject.ExpandoData.UpdateClass(), System.Web.Util.HttpEncoder.UrlDecode(), System.Xml.Schema.RangeContentValidator.ValidateElement(), System.Xml.XmlSqlBinaryReader.ValueAs(), System.Xml.XmlSqlBinaryReader.ValueAsObject(), System.Data.SqlTypes.SqlBytes.Write(), System.Data.SqlTypes.SqlChars.Write(), Terraria.Social.Steam.CloudSocialModule.Write(), System.IO.Compression.OutputWindow.WriteLengthDistance(), System.Xml.XmlWellFormedWriter.WriteStartElement(), and System.Xml.XmlWellFormedWriter.WriteStartElementAsync_FinishWrite().