Terraria: System.Array.GetLength
GetLength()
int System.Array.GetLength (int dimension) inline
Definition at line 839 of file Array.cs.
    {
        int multiDimensionalArrayRank = RuntimeHelpers.GetMultiDimensionalArrayRank(this);
        if (multiDimensionalArrayRank == 0 && dimension == 0)
        {
            return Length;
        }
        if ((uint)dimension >= (uint)multiDimensionalArrayRank)
        {
            throw new IndexOutOfRangeException(SR.IndexOutOfRange_ArrayRankIndex);
        }
        return Unsafe.Add(ref RuntimeHelpers.GetMultiDimensionalArrayBounds(this), dimension);
    }
References System.Runtime.CompilerServices.RuntimeHelpers.GetMultiDimensionalArrayBounds(), System.Runtime.CompilerServices.RuntimeHelpers.GetMultiDimensionalArrayRank(), System.SR.IndexOutOfRange_ArrayRankIndex, and System.Array.Length.
Referenced by System.Array.GetLongLength(), and System.ComponentModel.ArrayConverter.ArrayPropertyDescriptor.GetValue().