Terraria: System.Array.GetLowerBound
GetLowerBound()
int System.Array.GetLowerBound (int dimension) inline
Definition at line 868 of file Array.cs.
    {
        int multiDimensionalArrayRank = RuntimeHelpers.GetMultiDimensionalArrayRank(this);
        if (multiDimensionalArrayRank == 0 && dimension == 0)
        {
            return 0;
        }
        if ((uint)dimension >= (uint)multiDimensionalArrayRank)
        {
            throw new IndexOutOfRangeException(SR.IndexOutOfRange_ArrayRankIndex);
        }
        return Unsafe.Add(ref RuntimeHelpers.GetMultiDimensionalArrayBounds(this), multiDimensionalArrayRank + dimension);
    }
References System.Runtime.CompilerServices.RuntimeHelpers.GetMultiDimensionalArrayBounds(), System.Runtime.CompilerServices.RuntimeHelpers.GetMultiDimensionalArrayRank(), and System.SR.IndexOutOfRange_ArrayRankIndex.
Referenced by System.Array.Contains(), System.Array.CopyTo(), System.Array.Sort(), System.Array.Sort(), and System.Array.Sort().