Terraria: System.Array.SetValue
SetValue() [7/8]
void System.Array.SetValue (object? value, params int[] indices) inline
Definition at line 1051 of file Array.cs.
    {
        if (indices == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.indices);
        }
        if (Rank != indices.Length)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_RankIndices);
        }
        InternalSetValue(value, GetFlattenedIndex(new ReadOnlySpan<int>(indices)));
    }
References System.Array.GetFlattenedIndex(), System.indices, System.Array.InternalSetValue(), System.Array.Rank, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), and System.value.