Terraria: System.Array.CreateInstance
CreateInstance() [1/6]
static unsafe Array System.Array.CreateInstance (Type elementType, int length) inline static
Definition at line 473 of file Array.cs.
    {
        if ((object)elementType == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.elementType);
        }
        if (length < 0)
        {
            ThrowHelper.ThrowLengthArgumentOutOfRange_ArgumentOutOfRange_NeedNonNegNum();
        }
        RuntimeType runtimeType = elementType.UnderlyingSystemType as RuntimeType;
        if (runtimeType == null)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_MustBeType, ExceptionArgument.elementType);
        }
        return InternalCreate((void*)runtimeType.TypeHandle.Value, 1, &length, null);
    }
References System.elementType, System.Array.InternalCreate(), System.length, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowLengthArgumentOutOfRange_ArgumentOutOfRange_NeedNonNegNum().
Referenced by System.Xml.Schema.XmlBaseConverter.XmlBaseConverter(), System.Xml.Serialization.ReflectionXmlSerializationReader.AddItemInArrayMember(), System.Collections.Specialized.NameObjectCollectionBase.BaseGetAllValues(), System.DefaultBinder.BindToMethod(), System.Reflection.CustomAttribute.CreateAttributeArrayHelper(), System.Attribute.CreateAttributeArrayHelper(), System.Xml.Serialization.XmlSerializationReader.EnsureArrayIndex(), System.RuntimeType.RuntimeTypeCache.GetEmptyArray(), System.RuntimeType.GetEnumValues(), System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray< T >(), System.Data.DataTable.NewRowArray(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArray(), System.Xml.Serialization.XmlSerializationReader.ReadArray(), System.Runtime.Serialization.SurrogateDataContract.ReadXmlValue(), System.Linq.Expressions.Interpreter.NewArrayBoundsInstruction.Run(), System.Linq.Expressions.Interpreter.NewArrayInitInstruction.Run(), System.Linq.Expressions.Interpreter.NewArrayInstruction.Run(), System.Xml.Serialization.ReflectionXmlSerializationReader.SetCollectionObjectWithCollectionMember(), System.Xml.Serialization.XmlSerializationReader.ShrinkArray(), System.Collections.ArrayList.IListWrapper.ToArray(), System.Collections.ArrayList.Range.ToArray(), System.Collections.ArrayList.ToArray(), System.Xml.Serialization.CodeIdentifiers.ToArray(), System.Xml.Serialization.NameTable.ToArray(), System.RuntimeType.WrapArgsForInvokeCall(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttribute().