Terraria: System.Xml.XmlBaseReader.FixXmlAttribute
FixXmlAttribute()
void System.Xml.XmlBaseReader.FixXmlAttribute (XmlAttributeNode attributeNode) inline protected inherited
Definition at line 1588 of file XmlBaseReader.cs.
    {
        if (!(attributeNode.Prefix == "xml"))
        {
            return;
        }
        if (attributeNode.LocalName == "lang")
        {
            _nsMgr.AddLangAttribute(attributeNode.Value.GetString());
        }
        else if (attributeNode.LocalName == "space")
        {
            string @string = attributeNode.Value.GetString();
            if (@string == "preserve")
            {
                _nsMgr.AddSpaceAttribute(XmlSpace.Preserve);
            }
            else if (@string == "default")
            {
                _nsMgr.AddSpaceAttribute(XmlSpace.Default);
            }
        }
    }
References System.Xml.XmlBaseReader._nsMgr, System.Xml.XmlBaseReader.NamespaceManager.AddLangAttribute(), System.Xml.XmlBaseReader.NamespaceManager.AddSpaceAttribute(), and System.Xml.Dictionary.
Referenced by System.Xml.XmlUTF8TextReader.ReadAttributes(), and System.Xml.XmlBinaryReader.ReadAttributes2().