Terraria: System.Xml.XmlBaseReader.CheckAttributes
CheckAttributes()
void System.Xml.XmlBaseReader.CheckAttributes (XmlAttributeNode[] attributeNodes, int attributeCount) inline private inherited
Definition at line 1887 of file XmlBaseReader.cs.
    {
        if (_attributeSorter == null)
        {
            _attributeSorter = new AttributeSorter();
        }
        if (!_attributeSorter.Sort(attributeNodes, attributeCount))
        {
            _attributeSorter.GetIndeces(out var attributeIndex, out var attributeIndex2);
            if (attributeNodes[attributeIndex].QNameType == QNameType.Xmlns)
            {
                XmlExceptionHelper.ThrowDuplicateXmlnsAttribute(this, attributeNodes[attributeIndex].Namespace.Prefix.GetString(), "http://www.w3.org/2000/xmlns/");
            }
            else
            {
                XmlExceptionHelper.ThrowDuplicateAttribute(this, attributeNodes[attributeIndex].Prefix.GetString(), attributeNodes[attributeIndex2].Prefix.GetString(), attributeNodes[attributeIndex].LocalName.GetString(), attributeNodes[attributeIndex].Namespace.Uri.GetString());
            }
        }
    }
References System.Xml.XmlBaseReader._attributeSorter, System.Xml.Dictionary, System.Xml.XmlBaseReader.AttributeSorter.GetIndeces(), System.Xml.PrefixHandle.GetString(), System.Xml.XmlBaseReader.Namespace.Prefix, System.Xml.XmlBaseReader.Prefix, System.Xml.XmlBaseReader.AttributeSorter.Sort(), System.Xml.XmlExceptionHelper.ThrowDuplicateAttribute(), and System.Xml.XmlExceptionHelper.ThrowDuplicateXmlnsAttribute().
Referenced by System.Xml.XmlBaseReader.ProcessAttributes().