Terraria: System.Xml.XmlBaseReader.ReadContentAsBinHex
ReadContentAsBinHex() [2/3]
override int System.Xml.XmlBaseReader.ReadContentAsBinHex (byte[] buffer, int offset, int count) inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 2470 of file XmlBaseReader.cs.
    {
        if (buffer == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("buffer"));
        }
        if (offset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative));
        }
        if (offset > buffer.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.Format(System.SR.OffsetExceedsBufferSize, buffer.Length)));
        }
        if (count < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative));
        }
        if (count > buffer.Length - offset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, buffer.Length - offset)));
        }
        if (count == 0)
        {
            return 0;
        }
        return ReadBytes(BinHexEncoding, 1, 2, buffer, offset, Math.Min(count, 512), readContent: true);
    }
References System.buffer, System.count, System.Xml.Dictionary, System.SR.Format(), System.Math.Min(), System.offset, System.SR.OffsetExceedsBufferSize, System.Xml.XmlBaseReader.ReadBytes(), System.SR.SizeExceedsRemainingBufferSpace, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.ValueMustBeNonNegative.