Terraria: System.Xml.XmlBaseReader.ReadEndElement
ReadEndElement()
override void System.Xml.XmlBaseReader.ReadEndElement () inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Reimplemented in System.Xml.XmlUTF8TextReader.
Definition at line 2328 of file XmlBaseReader.cs.
    {
        if (_node.NodeType != XmlNodeType.EndElement && MoveToContent() != XmlNodeType.EndElement)
        {
            int num = ((_node.NodeType == XmlNodeType.Element) ? (_depth - 1) : _depth);
            if (num == 0)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlEndElementNoOpenNodes));
            }
            XmlElementNode xmlElementNode = _elementNodes[num];
            XmlExceptionHelper.ThrowEndElementExpected(this, xmlElementNode.LocalName.GetString(), xmlElementNode.Namespace.Uri.GetString());
        }
        Read();
    }
References System.Xml.XmlBaseReader.NamespaceManager._depth, System.Xml.XmlBaseReader._elementNodes, System.Xml.XmlBaseReader._node, System.Xml.Dictionary, System.Xml.XmlBaseReader.MoveToContent(), System.Xml.XmlBaseReader.XmlNode.NodeType, System.Xml.XmlReader.Read(), System.Xml.XmlExceptionHelper.ThrowEndElementExpected(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.XmlEndElementNoOpenNodes.
Referenced by System.Xml.XmlBaseReader.ReadElementContentAsBase64(), System.Xml.XmlBaseReader.ReadElementContentAsBinHex(), and System.Xml.XmlBaseReader.ReadElementContentAsString().