Terraria: System.Xml.XmlBaseReader.ReadContentAsBase64
ReadContentAsBase64() [1/3]
override byte[] System.Xml.XmlBaseReader.ReadContentAsBase64 () inline virtual inherited
Reimplemented from System.Xml.XmlDictionaryReader.
Definition at line 2375 of file XmlBaseReader.cs.
    {
        if (_trailByteCount == 0 && _trailCharCount == 0 && _value == null)
        {
            XmlNode node = Node;
            if (node.IsAtomicValue)
            {
                byte[] array = node.Value.ToByteArray();
                if (array.Length > _quotas.MaxArrayLength)
                {
                    XmlExceptionHelper.ThrowMaxArrayLengthExceeded(this, _quotas.MaxArrayLength);
                }
                SkipValue(node);
                return array;
            }
        }
        if (!_bufferReader.IsStreamed)
        {
            return ReadContentAsBase64(_quotas.MaxArrayLength, _bufferReader.Buffer.Length);
        }
        return ReadContentAsBase64(_quotas.MaxArrayLength, 65535);
    }
References System.Xml.XmlBaseReader.NamespaceManager._bufferReader, System.Xml.XmlBaseReader._quotas, System.Xml.XmlBaseReader._trailByteCount, System.Xml.XmlBaseReader._trailCharCount, System.Xml.XmlBaseReader._value, System.array, System.Xml.XmlBufferReader.Buffer, System.Xml.Dictionary, System.Xml.XmlBufferReader.IsStreamed, System.Xml.XmlDictionaryReaderQuotas.MaxArrayLength, System.Xml.XmlBaseReader.Node, System.Xml.XmlBaseReader.ReadContentAsBase64(), System.Xml.XmlBaseReader.SkipValue(), System.Xml.XmlExceptionHelper.ThrowMaxArrayLengthExceeded(), System.Xml.ValueHandle.ToByteArray(), and System.Xml.XmlBaseReader.XmlNode.Value.
Referenced by System.Xml.XmlBaseReader.ReadContentAsBase64(), and System.Xml.XmlBaseReader.ReadElementContentAsBase64().