Terraria: System.Array.BinarySearch
BinarySearch() [3/4]
static int System.Array.BinarySearch (Array array, object? value) inline static
Definition at line 1320 of file Array.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        return BinarySearch(array, array.GetLowerBound(0), array.Length, value, null);
    }
References System.array, System.Array.BinarySearch(), System.ThrowHelper.ThrowArgumentNullException(), and System.value.
Referenced by System.Collections.SortedList.Add(), System.Collections.Generic.SortedList< TKey, TValue >.Add(), System.Xml.XmlTextReaderImpl.AddDefaultAttributeDtd(), System.Array.BinarySearch(), System.Type.BinarySearch(), System.Array.BinarySearch(), System.Array.BinarySearch(), System.Collections.ArrayList.BinarySearch(), System.Collections.Generic.List< T >.BinarySearch(), System.Array.BinarySearch< T >(), System.Array.BinarySearch< T >(), System.Array.BinarySearch< T >(), System.Collections.Immutable.ImmutableArray< T >.BinarySearch< T >(), System.Collections.Immutable.ImmutableArray< T >.BinarySearch< T >(), System.Collections.Immutable.ImmutableArray< T >.BinarySearch< T >(), System.Collections.Immutable.ImmutableArray< T >.BinarySearch< T >(), System.Data.XDRSchema.FindNameType(), System.Data.XSDSchema.FindNameType(), System.Xml.Schema.DatatypeImplementation.FromTypeName(), System.Xml.Schema.DatatypeImplementation.FromXdrName(), System.Enum.GetEnumName(), System.Linq.Expressions.Interpreter.DebugInfo.GetMatchingDebugInfo(), System.Resources.ResourceReader.GetResourceData(), System.Collections.SortedList.KeyList.IndexOf(), System.Collections.Generic.SortedList< TKey, TValue >.KeyList.IndexOf(), System.Collections.SortedList.IndexOfKey(), System.Collections.Generic.SortedList< TKey, TValue >.IndexOfKey(), System.Enum.IsDefined< TEnum >(), System.RuntimeType.IsEnumDefined(), System.Data.XSDSchema.IsXsdType(), and System.Data.XSDSchema.XsdtoClr().