Terraria: System.Array.Sort
Sort() [1/8]
static void System.Array.Sort (Array array) inline static
Definition at line 2329 of file Array.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        Sort(array, null, array.GetLowerBound(0), array.Length, null);
    }
References System.array, System.Array.Sort(), and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.Diagnostics.Metrics.QuantileAggregation.QuantileAggregation(), System.Collections.SortedList.SortedList(), System.Collections.Generic.SortedList< TKey, TValue >.SortedList(), System.Collections.Generic.SortedSet< T >.SortedSet(), Terraria.GameContent.Skies.MartianSky.Activate(), Terraria.GameContent.Skies.NebulaSky.Activate(), Terraria.GameContent.Skies.SolarSky.Activate(), Terraria.GameContent.Skies.StardustSky.Activate(), System.Xml.XmlTextReaderImpl.AddDefaultAttributesAndNormalize(), System.Net.CookieContainer.AgeCookies(), System.Text.RegularExpressions.RegexParser.AssignNameSlots(), System.Xml.XmlTextReaderImpl.AttributeDuplCheck(), System.Reflection.Internal.MemoryBlock.BuildPtrTable(), System.Diagnostics.Metrics.LabelInstructionCompiler.Create< TAggregator >(), System.Diagnostics.Tracing.ManifestBuilder.CreateManifestString(), System.Xml.Xsl.Runtime.XmlQueryNodeSequence.DocOrderDistinct(), System.Xml.Linq.Extensions.DocumentOrderIterator< T >(), System.Linq.Parallel.OrderedGroupByGrouping< TGroupKey, TOrderKey, TElement >.DoneAdding(), System.Resources.ResourceWriter.Generate(), System.Runtime.Serialization.CollectionDataContract.GetCollectionMethods(), System.Diagnostics.Process.GetEnvironmentVariablesBlock(), System.Resources.ResourceReader.GetResourceData(), System.ComponentModel.CultureInfoConverter.GetStandardValues(), System.Xml.Serialization.XmlSchemaImporter.ImportChoiceGroup(), System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedChoice(), System.ComponentModel.EventDescriptorCollection.InternalSort(), System.ComponentModel.PropertyDescriptorCollection.InternalSort(), System.Globalization.JapaneseCalendar.NlsGetJapaneseEras(), System.Reflection.Internal.EnumerableExtensions.OrderBy< T >(), System.Collections.Immutable.ImmutableArray< T >.Builder.Sort(), System.Xml.XmlBaseReader.AttributeSorter.Sort(), System.Xml.XmlCanonicalWriter.AttributeSorter.Sort(), Terraria.DataStructures.TileDrawSorter.Sort(), System.Array.Sort(), System.Array.Sort(), System.Array.Sort(), System.Array.Sort(), System.Array.Sort(), System.Array.Sort(), System.Array.Sort(), System.Collections.Immutable.ImmutableArray< T >.Builder.Sort(), System.Collections.Immutable.ImmutableList< T >.Node.Sort(), System.Collections.Immutable.ImmutableArray< T >.Builder.Sort(), System.Collections.ArrayList.IListWrapper.Sort(), System.Collections.Immutable.ImmutableArray< T >.Builder.Sort(), System.Collections.Immutable.ImmutableArray< T >.Sort(), System.Collections.Immutable.ImmutableList< T >.Node.Sort(), System.Collections.Generic.List< T >.Sort(), System.Collections.ArrayList.Sort(), System.Array.Sort< T >(), System.Array.Sort< T >(), System.Array.Sort< TKey, TValue >(), System.Array.Sort< TKey, TValue >(), System.Array.Sort< TKey, TValue >(), System.Array.Sort< TKey, TValue >(), System.Xml.Xsl.Runtime.XmlQuerySequence< T >.SortByKeys(), System.Xml.Xsl.Xslt.Compiler.SortErrors(), System.Xml.Serialization.AccessorMapping.SortMostToLeastDerived(), Microsoft.Xna.Framework.Graphics.SpriteBatch.SortSprites(), System.Collections.Generic.SortedSet< T >.SymmetricExceptWith(), and System.Xml.Xsl.XmlQueryType.ToString().