Terraria: System.Xml.XmlBaseReader.EnterScope
EnterScope()
XmlElementNode System.Xml.XmlBaseReader.EnterScope () inline protected inherited
Definition at line 1476 of file XmlBaseReader.cs.
    {
        if (_depth == 0)
        {
            if (_rootElement)
            {
                XmlExceptionHelper.ThrowMultipleRootElements(this);
            }
            _rootElement = true;
        }
        _nsMgr.EnterScope();
        _depth++;
        if (_depth > _quotas.MaxDepth)
        {
            XmlExceptionHelper.ThrowMaxDepthExceeded(this, _quotas.MaxDepth);
        }
        if (_elementNodes == null)
        {
            _elementNodes = new XmlElementNode[4];
        }
        else if (_elementNodes.Length == _depth)
        {
            XmlElementNode[] array = new XmlElementNode[_depth * 2];
            Array.Copy(_elementNodes, array, _depth);
            _elementNodes = array;
        }
        XmlElementNode xmlElementNode = _elementNodes[_depth];
        if (xmlElementNode == null)
        {
            xmlElementNode = new XmlElementNode(_bufferReader);
            _elementNodes[_depth] = xmlElementNode;
        }
        _attributeCount = 0;
        _attributeStart = -1;
        _attributeIndex = -1;
        MoveToNode(xmlElementNode);
        return xmlElementNode;
    }
References System.Xml.XmlBaseReader.NamespaceManager._attributeCount, System.Xml.XmlBaseReader._attributeIndex, System.Xml.XmlBaseReader._attributeStart, System.Xml.XmlBaseReader.NamespaceManager._bufferReader, System.Xml.XmlBaseReader.NamespaceManager._depth, System.Xml.XmlBaseReader._elementNodes, System.Xml.XmlBaseReader._nsMgr, System.Xml.XmlBaseReader._quotas, System.Xml.XmlBaseReader._rootElement, System.array, System.Array.Copy(), System.Xml.Dictionary, System.Xml.XmlBaseReader.NamespaceManager.EnterScope(), System.Xml.XmlDictionaryReaderQuotas.MaxDepth, System.Xml.XmlBaseReader.MoveToNode(), System.Xml.XmlExceptionHelper.ThrowMaxDepthExceeded(), and System.Xml.XmlExceptionHelper.ThrowMultipleRootElements().
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.ParseAndSetLocalName(), System.Xml.XmlBinaryReader.ReadNode(), System.Runtime.Serialization.Json.XmlJsonReader.ReadNonExistentElementName(), and System.Xml.XmlUTF8TextReader.ReadStartElement().