Terraria: System.Xml.XmlBaseReader.GetAttributeNode
GetAttributeNode() [1/4]
XmlAttributeNode System.Xml.XmlBaseReader.GetAttributeNode (int index) inline private inherited
Definition at line 1636 of file XmlBaseReader.cs.
    {
        if (!_node.CanGetAttribute)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("index", System.SR.XmlElementAttributes));
        }
        if (index < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("index", System.SR.ValueMustBeNonNegative));
        }
        if (index >= _attributeCount)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("index", System.SR.Format(System.SR.OffsetExceedsBufferSize, _attributeCount)));
        }
        return _attributeNodes[index];
    }
References System.Xml.XmlBaseReader.NamespaceManager._attributeCount, System.Xml.XmlBaseReader._attributeNodes, System.Xml.XmlBaseReader._node, System.Xml.XmlBaseReader.XmlNode.CanGetAttribute, System.SR.Format(), System.index, System.SR.OffsetExceedsBufferSize, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.ValueMustBeNonNegative, and System.SR.XmlElementAttributes.
Referenced by System.Xml.XmlBaseReader.GetAttribute(), System.Xml.XmlBaseReader.GetAttribute(), System.Xml.XmlBaseReader.GetAttribute(), System.Xml.XmlBaseReader.GetAttribute(), System.Xml.XmlBaseReader.MoveToAttribute(), System.Xml.XmlBaseReader.MoveToAttribute(), System.Xml.XmlBaseReader.MoveToAttribute(), System.Xml.XmlBaseReader.MoveToFirstAttribute(), and System.Xml.XmlBaseReader.MoveToNextAttribute().