Terraria: System.Array.Reverse
Reverse() [1/2]
static void System.Array.Reverse (Array array) inline static
Definition at line 2207 of file Array.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        Reverse(array, array.GetLowerBound(0), array.Length);
    }
References System.array, System.Array.Reverse(), and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.Globalization.CalendarData.CallEnumCalendarInfo(), System.Collections.Generic.Stack< T >.CopyTo(), Internal.NativeCrypto.CapiHelper.DecryptKey(), Internal.NativeCrypto.CapiHelper.EncryptKey(), Internal.Cryptography.Pal.FindPal.FindFromCollection(), System.Security.Cryptography.X509Certificates.X509Certificate.GetSerialNumber(), System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore(), System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore(), Internal.NativeCrypto.CapiHelper.ReadReversed(), System.Array.Reverse(), System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.Reverse(), System.Collections.Generic.List< T >.Reverse(), System.Collections.ArrayList.Reverse(), System.Array.Reverse< T >(), Internal.NativeCrypto.CapiHelper.ReverseDsaSignature(), Internal.NativeCrypto.CapiHelper.SignValue(), System.Linq.Enumerable.ReverseIterator< TSource >.ToArray(), System.Security.Cryptography.X509Certificates.X509Certificate.ToString(), Internal.NativeCrypto.CapiHelper.UnloadKey(), Internal.NativeCrypto.CapiHelper.VerifySign(), System.Formats.Asn1.AsnWriter.WriteIntegerCore(), and Internal.NativeCrypto.CapiHelper.WriteReversed().