Terraria: System.Array.FindLastIndex< T >
FindLastIndex< T >() [1/3]
static int System.Array.FindLastIndex< T > (T[] array, int startIndex, int count, Predicate< T > match) inline static
Definition at line 1756 of file Array.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        if (match == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.match);
        }
        if (array.Length == 0)
        {
            if (startIndex != -1)
            {
                ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index();
            }
        }
        else if (startIndex < 0 || startIndex >= array.Length)
        {
            ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index();
        }
        if (count < 0 || startIndex - count + 1 < 0)
        {
            ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count();
        }
        int num = startIndex - count;
        for (int num2 = startIndex; num2 > num; num2--)
        {
            if (match(array[num2]))
            {
                return num2;
            }
        }
        return -1;
    }
References System.array, System.count, System.match, System.startIndex, System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count(), and System.ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index().