Terraria: System.Array.CreateInstance
CreateInstance() [3/6]
static unsafe Array System.Array.CreateInstance (Type elementType, int length1, int length2, int length3) inline static
Definition at line 516 of file Array.cs.
    {
        if ((object)elementType == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.elementType);
        }
        if (length1 < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.length1, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (length2 < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.length2, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (length3 < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.length3, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        RuntimeType runtimeType = elementType.UnderlyingSystemType as RuntimeType;
        if (runtimeType == null)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_MustBeType, ExceptionArgument.elementType);
        }
        int* ptr = stackalloc int[3];
        *ptr = length1;
        ptr[1] = length2;
        ptr[2] = length3;
        return InternalCreate((void*)runtimeType.TypeHandle.Value, 3, ptr, null);
    }
References System.elementType, System.Array.InternalCreate(), System.length1, System.length2, System.length3, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().