Terraria: System.Array.IndexOf
IndexOf() [3/5]
static int System.Array.IndexOf (Array array, object? value, int startIndex, int count) inline static
Definition at line 1827 of file Array.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        if (array.Rank != 1)
        {
            ThrowHelper.ThrowRankException(ExceptionResource.Rank_MultiDimNotSupported);
        }
        int lowerBound = array.GetLowerBound(0);
        if (startIndex < lowerBound || startIndex > array.Length + lowerBound)
        {
            ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index();
        }
        if (count < 0 || count > array.Length - startIndex + lowerBound)
        {
            ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count();
        }
        int num = startIndex + count;
        if (array is object[] array2)
        {
            if (value == null)
            {
                for (int i = startIndex; i < num; i++)
                {
                    if (array2[i] == null)
                    {
                        return i;
                    }
                }
            }
            else
            {
                for (int j = startIndex; j < num; j++)
                {
                    object obj = array2[j];
                    if (obj != null && obj.Equals(value))
                    {
                        return j;
                    }
                }
            }
            return -1;
        }
        CorElementType corElementTypeOfElementType = array.GetCorElementTypeOfElementType();
        if (corElementTypeOfElementType.IsPrimitiveType())
        {
            if (value == null)
            {
                return lowerBound - 1;
            }
            if (array.IsValueOfElementType(value))
            {
                int adjustedIndex2 = startIndex - lowerBound;
                int num2 = -1;
                switch (corElementTypeOfElementType)
                {
                case CorElementType.ELEMENT_TYPE_BOOLEAN:
                case CorElementType.ELEMENT_TYPE_I1:
                case CorElementType.ELEMENT_TYPE_U1:
                    num2 = GenericIndexOf<byte>(array, value, adjustedIndex2, count);
                    break;
                case CorElementType.ELEMENT_TYPE_CHAR:
                case CorElementType.ELEMENT_TYPE_I2:
                case CorElementType.ELEMENT_TYPE_U2:
                    num2 = GenericIndexOf<char>(array, value, adjustedIndex2, count);
                    break;
                case CorElementType.ELEMENT_TYPE_I4:
                case CorElementType.ELEMENT_TYPE_U4:
                    num2 = GenericIndexOf<int>(array, value, adjustedIndex2, count);
                    break;
                case CorElementType.ELEMENT_TYPE_I8:
                case CorElementType.ELEMENT_TYPE_U8:
                case CorElementType.ELEMENT_TYPE_I:
                case CorElementType.ELEMENT_TYPE_U:
                    num2 = GenericIndexOf<long>(array, value, adjustedIndex2, count);
                    break;
                case CorElementType.ELEMENT_TYPE_R4:
                    num2 = GenericIndexOf<float>(array, value, adjustedIndex2, count);
                    break;
                case CorElementType.ELEMENT_TYPE_R8:
                    num2 = GenericIndexOf<double>(array, value, adjustedIndex2, count);
                    break;
                }
                return ((num2 >= 0) ? startIndex : lowerBound) + num2;
            }
        }
        for (int k = startIndex; k < num; k++)
        {
            object value2 = array.GetValue(k);
            if (value2 == null)
            {
                if (value == null)
                {
                    return k;
                }
            }
            else if (value2.Equals(value))
            {
                return k;
            }
        }
        return lowerBound - 1;
        static int GenericIndexOf<T>(Array array, object value, int adjustedIndex, int length) where T : struct, IEquatable<T>
        {
            return UnsafeArrayAsSpan<T>(array, adjustedIndex, length).IndexOf(Unsafe.As<byte, T>(ref value.GetRawData()));
        }
    }
References System.array, System.count, System.length, System.obj, System.startIndex, System.T, System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count(), System.ThrowHelper.ThrowRankException(), System.ThrowHelper.ThrowStartIndexArgumentOutOfRange_ArgumentOutOfRange_Index(), System.Array.UnsafeArrayAsSpan< T >(), and System.value.