Terraria: System.Array.Sort< TKey, TValue >
Sort< TKey, TValue >() [4/4]
static void System.Array.Sort< TKey, TValue > (TKey[] keys, TValue?[] items, int index, int length, IComparer< TKey >? comparer) inline static
Definition at line 2559 of file Array.cs.
    {
        if (keys == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.keys);
        }
        if (index < 0)
        {
            ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException();
        }
        if (length < 0)
        {
            ThrowHelper.ThrowLengthArgumentOutOfRange_ArgumentOutOfRange_NeedNonNegNum();
        }
        if (keys.Length - index < length || (items != null && index > items.Length - length))
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Argument_InvalidOffLen);
        }
        if (length > 1)
        {
            if (items == null)
            {
                Sort(keys, index, length, comparer);
                return;
            }
            Span<TKey> keys2 = new Span<TKey>(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(keys), index), length);
            Span<TValue> values = new Span<TValue>(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(items), index), length);
            ArraySortHelper<TKey, TValue>.Default.Sort(keys2, values, comparer);
        }
    }
References System.comparer, System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.index, System.keys, System.length, System.Array.Sort(), System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException(), System.ThrowHelper.ThrowLengthArgumentOutOfRange_ArgumentOutOfRange_NeedNonNegNum(), and System.values.