Terraria: System.Xml.XmlBaseReader.IsStartElement
IsStartElement() [1/4]
override bool System.Xml.XmlBaseReader.IsStartElement () inline sealed virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 2047 of file XmlBaseReader.cs.
    {
        switch (_node.NodeType)
        {
        case XmlNodeType.Element:
            return true;
        case XmlNodeType.EndElement:
            return false;
        case XmlNodeType.None:
            Read();
            if (_node.NodeType == XmlNodeType.Element)
            {
                return true;
            }
            break;
        }
        return MoveToContent() == XmlNodeType.Element;
    }
References System.Xml.XmlBaseReader._node, System.Xml.XmlBaseReader.MoveToContent(), System.Xml.XmlBaseReader.XmlNode.NodeType, and System.Xml.XmlReader.Read().
Referenced by System.Xml.XmlBinaryReader.IsStartArray(), System.Xml.XmlBinaryReader.IsStartArray(), System.Xml.XmlBaseReader.IsStartElement(), System.Xml.XmlBaseReader.IsStartElement(), and System.Xml.XmlBaseReader.IsStartElement().