Terraria: System.Xml.XmlBaseReader.ProcessAttributes
ProcessAttributes() [2/2]
void System.Xml.XmlBaseReader.ProcessAttributes (XmlAttributeNode[] attributeNodes, int attributeCount) inline private inherited
Definition at line 1831 of file XmlBaseReader.cs.
    {
        for (int i = 0; i < attributeCount; i++)
        {
            XmlAttributeNode xmlAttributeNode = attributeNodes[i];
            if (xmlAttributeNode.QNameType == QNameType.Normal)
            {
                PrefixHandle prefix = xmlAttributeNode.Prefix;
                if (!prefix.IsEmpty)
                {
                    xmlAttributeNode.Namespace = LookupNamespace(prefix);
                }
                else
                {
                    xmlAttributeNode.Namespace = NamespaceManager.EmptyNamespace;
                }
                xmlAttributeNode.AttributeText.Namespace = xmlAttributeNode.Namespace;
            }
        }
        if (attributeCount <= 1)
        {
            return;
        }
        if (attributeCount < 12)
        {
            for (int j = 0; j < attributeCount - 1; j++)
            {
                XmlAttributeNode xmlAttributeNode2 = attributeNodes[j];
                if (xmlAttributeNode2.QNameType == QNameType.Normal)
                {
                    for (int k = j + 1; k < attributeCount; k++)
                    {
                        XmlAttributeNode xmlAttributeNode3 = attributeNodes[k];
                        if (xmlAttributeNode3.QNameType == QNameType.Normal && xmlAttributeNode2.LocalName == xmlAttributeNode3.LocalName && xmlAttributeNode2.Namespace.Uri == xmlAttributeNode3.Namespace.Uri)
{
                            XmlExceptionHelper.ThrowDuplicateAttribute(this, xmlAttributeNode2.Prefix.GetString(), xmlAttributeNode3.Prefix.GetString(), xmlAttributeNode2.LocalName.GetString(), xmlAttributeNode2.Namespace.Uri.GetString());
                        }
                    }
                    continue;
                }
                for (int l = j + 1; l < attributeCount; l++)
                {
                    XmlAttributeNode xmlAttributeNode4 = attributeNodes[l];
                    if (xmlAttributeNode4.QNameType == QNameType.Xmlns && xmlAttributeNode2.Namespace.Prefix == xmlAttributeNode4.Namespace.Prefix)
                    {
                        XmlExceptionHelper.ThrowDuplicateAttribute(this, "xmlns", "xmlns", xmlAttributeNode2.Namespace.Prefix.GetString(), "http://www.w3.org/2000/xmlns/");
                    }
                }
            }
        }
        else
        {
            CheckAttributes(attributeNodes, attributeCount);
        }
    }
References System.Xml.XmlBaseReader.CheckAttributes(), System.Xml.Dictionary, System.Xml.XmlBaseReader.NamespaceManager.EmptyNamespace, System.Xml.XmlBaseReader.NamespaceManager.LookupNamespace(), System.prefix, and System.Xml.XmlExceptionHelper.ThrowDuplicateAttribute().