Terraria: System.Xml.XmlBaseReader.ReadContentAsTimeSpan
ReadContentAsTimeSpan()
override TimeSpan System.Xml.XmlBaseReader.ReadContentAsTimeSpan () inline virtual inherited
Reimplemented from System.Xml.XmlDictionaryReader.
Definition at line 2747 of file XmlBaseReader.cs.
    {
        XmlNode node = Node;
        if (_value == null && node.IsAtomicValue)
        {
            TimeSpan result = node.Value.ToTimeSpan();
            SkipValue(node);
            return result;
        }
        return XmlConverter.ToTimeSpan(ReadContentAsString());
    }
References System.Xml.XmlBaseReader._value, System.Xml.Dictionary, System.Xml.XmlBaseReader.Node, System.Xml.XmlBaseReader.ReadContentAsString(), System.Xml.XmlBaseReader.SkipValue(), and System.Xml.XmlConverter.ToTimeSpan().
Referenced by System.Xml.XmlBaseReader.ReadContentAs().