Terraria: System.Array.Resize< T >
Resize< T >()
static void System.Array.Resize< T > ([NotNull] ref T?[] array, int newSize) inline static
Definition at line 907 of file Array.cs.
    {
        if (newSize < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.newSize, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        T[] array2 = array;
        if (array2 == null)
        {
            array = new T[newSize];
        }
        else if (array2.Length != newSize)
        {
            T[] array3 = new T[newSize];
            Buffer.Memmove(ref MemoryMarshal.GetArrayDataReference(array3), ref MemoryMarshal.GetArrayDataReference(array2), (uint)Math.Min(newSize, array2.Length));
            array = array3;
        }
    }
References System.array, System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.Buffer.Memmove(), System.Math.Min(), System.newSize, and System.ThrowHelper.ThrowArgumentOutOfRangeException().