Terraria: System.Array.LastIndexOf
LastIndexOf() [1/3]
static int System.Array.LastIndexOf (Array array, object? value) inline static
Definition at line 1995 of file Array.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        int lowerBound = array.GetLowerBound(0);
        return LastIndexOf(array, value, array.Length - 1 + lowerBound, array.Length);
    }
References System.array, System.Array.LastIndexOf(), System.ThrowHelper.ThrowArgumentNullException(), and System.value.
Referenced by System.Collections.Generic.Stack< T >.Contains(), System.Array.LastIndexOf(), System.Array.LastIndexOf(), System.Collections.ArrayList.LastIndexOf(), System.Collections.Generic.List< T >.LastIndexOf(), System.Collections.Immutable.ImmutableArray< T >.Builder.LastIndexOf(), System.Collections.Immutable.ImmutableArray< T >.LastIndexOf(), System.Array.LastIndexOf< T >(), and System.Array.LastIndexOf< T >().