Terraria: System.Xml.XmlBaseReader.MoveToContent
MoveToContent()
override XmlNodeType System.Xml.XmlBaseReader.MoveToContent () inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 1952 of file XmlBaseReader.cs.
    {
        do
        {
            if (_node.HasContent)
            {
                if ((_node.NodeType != XmlNodeType.Text && _node.NodeType != XmlNodeType.CDATA) || _trailByteCount > 0)
                {
                    break;
                }
                if (_value == null)
                {
                    if (!_node.Value.IsWhitespace())
                    {
                        break;
                    }
                }
                else if (!XmlConverter.IsWhitespace(_value))
                {
                    break;
                }
            }
            else if (_node.NodeType == XmlNodeType.Attribute)
            {
                MoveToElement();
                break;
            }
        }
        while (Read());
        return _node.NodeType;
    }
References System.Xml.XmlBaseReader._node, System.Xml.XmlBaseReader._trailByteCount, System.Xml.XmlBaseReader._value, System.Xml.XmlBaseReader.XmlNode.HasContent, System.Xml.ValueHandle.IsWhitespace(), System.Xml.XmlConverter.IsWhitespace(), System.Xml.XmlBaseReader.MoveToElement(), System.Xml.XmlBaseReader.XmlNode.NodeType, System.Xml.XmlReader.Read(), and System.Xml.XmlBaseReader.XmlNode.Value.
Referenced by System.Xml.XmlBaseReader.IsStartElement(), and System.Xml.XmlBaseReader.ReadEndElement().