Terraria: System.Xml.XmlBaseReader.AddXmlnsAttribute
AddXmlnsAttribute()
XmlAttributeNode System.Xml.XmlBaseReader.AddXmlnsAttribute (Namespace ns) inline protected inherited
Definition at line 1567 of file XmlBaseReader.cs.
    {
        if (!ns.Prefix.IsEmpty && ns.Uri.IsEmpty)
        {
            XmlExceptionHelper.ThrowEmptyNamespace(this);
        }
        if (ns.Prefix.IsXml && ns.Uri != "http://www.w3.org/XML/1998/namespace")
        {
            XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.XmlSpecificBindingPrefix, "xml", "http://www.w3.org/XML/1998/namespace")));
        }
        else if (ns.Prefix.IsXmlns && ns.Uri != "http://www.w3.org/2000/xmlns/")
        {
            XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.XmlSpecificBindingPrefix, "xmlns", "http://www.w3.org/2000/xmlns/")));
        }
        _nsMgr.Register(ns);
        XmlAttributeNode xmlAttributeNode = AddAttribute(QNameType.Xmlns, isAtomicValue: false);
        xmlAttributeNode.Namespace = ns;
        xmlAttributeNode.AttributeText.Namespace = ns;
        return xmlAttributeNode;
    }
References System.Xml.XmlBaseReader._nsMgr, System.Xml.XmlBaseReader.NamespaceManager.AddAttribute(), System.Xml.Dictionary, System.SR.Format(), System.Xml.PrefixHandle.IsEmpty, System.Xml.StringHandle.IsEmpty, System.Xml.PrefixHandle.IsXml, System.Xml.PrefixHandle.IsXmlns, System.Xml.XmlBaseReader.Namespace.Prefix, System.Xml.XmlBaseReader.NamespaceManager.Register(), System.Xml.XmlExceptionHelper.ThrowEmptyNamespace(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Xml.XmlBaseReader.Namespace.Uri, System.Xml.XmlException, and System.SR.XmlSpecificBindingPrefix.
Referenced by System.Xml.XmlUTF8TextReader.ReadAttributes(), System.Xml.XmlBinaryReader.ReadAttributes2(), and System.Runtime.Serialization.Json.XmlJsonReader.SetJsonNameWithMapping().