Terraria: System.Xml.XmlBaseReader.ReadContentAsBase64
ReadContentAsBase64() [2/3]
override int System.Xml.XmlBaseReader.ReadContentAsBase64 (byte[] buffer, int offset, int count) inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 2419 of file XmlBaseReader.cs.
    {
        if (buffer == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("buffer"));
        }
        if (offset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative));
        }
        if (offset > buffer.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.Format(System.SR.OffsetExceedsBufferSize, buffer.Length)));
        }
        if (count < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative));
        }
        if (count > buffer.Length - offset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, buffer.Length - offset)));
        }
        if (count == 0)
        {
            return 0;
        }
        if (_trailByteCount == 0 && _trailCharCount == 0 && _value == null && _node.QNameType == QNameType.Normal)
        {
            int actual;
            while (_node.NodeType != XmlNodeType.Comment && _node.Value.TryReadBase64(buffer, offset, count, out actual))
            {
                if (actual != 0)
                {
                    return actual;
                }
                Read();
            }
        }
        XmlNodeType nodeType = _node.NodeType;
        if (nodeType == XmlNodeType.Element || nodeType == XmlNodeType.EndElement)
        {
            return 0;
        }
        return ReadBytes(Base64Encoding, 3, 4, buffer, offset, Math.Min(count, 512), readContent: true);
    }
References System.Xml.XmlBaseReader._node, System.Xml.XmlBaseReader._trailByteCount, System.Xml.XmlBaseReader._trailCharCount, System.Xml.XmlBaseReader._value, System.buffer, System.count, System.Xml.Dictionary, System.SR.Format(), System.Math.Min(), System.Xml.XmlBaseReader.XmlNode.NodeType, System.offset, System.SR.OffsetExceedsBufferSize, System.Xml.XmlBaseReader.XmlNode.QNameType, System.Xml.XmlReader.Read(), System.Xml.XmlBaseReader.ReadBytes(), System.SR.SizeExceedsRemainingBufferSpace, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.ValueHandle.TryReadBase64(), System.Xml.XmlBaseReader.XmlNode.Value, and System.SR.ValueMustBeNonNegative.