Terraria: System.Xml.XmlBaseReader.ReadContentAsGuid
ReadContentAsGuid()
override Guid System.Xml.XmlBaseReader.ReadContentAsGuid () inline virtual inherited
Reimplemented from System.Xml.XmlDictionaryReader.
Definition at line 2759 of file XmlBaseReader.cs.
    {
        XmlNode node = Node;
        if (_value == null && node.IsAtomicValue)
        {
            Guid result = node.Value.ToGuid();
            SkipValue(node);
            return result;
        }
        return XmlConverter.ToGuid(ReadContentAsString());
    }
References System.Xml.XmlBaseReader._value, System.Xml.Dictionary, System.Xml.XmlBaseReader.Node, System.Xml.XmlBaseReader.ReadContentAsString(), System.Xml.XmlBaseReader.SkipValue(), and System.Xml.XmlConverter.ToGuid().
Referenced by System.Xml.XmlBaseReader.ReadContentAs().