Terraria: System.Xml.XmlBaseReader.MoveToWhitespaceText
MoveToWhitespaceText()
XmlTextNode System.Xml.XmlBaseReader.MoveToWhitespaceText () inline protected inherited
Definition at line 1437 of file XmlBaseReader.cs.
    {
        if (_whitespaceTextNode == null)
        {
            _whitespaceTextNode = new XmlWhitespaceTextNode(_bufferReader);
        }
        if (_nsMgr.XmlSpace == XmlSpace.Preserve)
        {
            _whitespaceTextNode.NodeType = XmlNodeType.SignificantWhitespace;
        }
        else
        {
            _whitespaceTextNode.NodeType = XmlNodeType.Whitespace;
        }
        MoveToNode(_whitespaceTextNode);
        return _whitespaceTextNode;
    }
References System.Xml.XmlBaseReader.NamespaceManager._bufferReader, System.Xml.XmlBaseReader._nsMgr, System.Xml.XmlBaseReader._whitespaceTextNode, System.Xml.Dictionary, System.Xml.XmlBaseReader.MoveToNode(), and System.Xml.XmlBaseReader.NamespaceManager.XmlSpace.
Referenced by System.Xml.XmlUTF8TextReader.ReadEscapedText(), and System.Xml.XmlUTF8TextReader.ReadWhitespace().