Terraria: System.Xml.XmlBaseReader.ReadContentAsString
ReadContentAsString() [1/4]
override string System.Xml.XmlBaseReader.ReadContentAsString () inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 2623 of file XmlBaseReader.cs.
    {
        XmlNode node = Node;
        if (node.IsAtomicValue)
        {
            string text;
            if (_value != null)
            {
                text = _value;
                if (node.AttributeText == null)
                {
                    _value = string.Empty;
                }
            }
            else
            {
                text = node.Value.GetString();
                SkipValue(node);
                if (text.Length > _quotas.MaxStringContentLength)
                {
                    XmlExceptionHelper.ThrowMaxStringContentLengthExceeded(this, _quotas.MaxStringContentLength);
                }
            }
            return text;
        }
        return ReadContentAsString(_quotas.MaxStringContentLength);
    }
References System.Xml.XmlBaseReader._quotas, System.Xml.XmlBaseReader._value, System.Xml.Dictionary, System.Xml.XmlDictionaryReaderQuotas.MaxStringContentLength, System.Xml.XmlBaseReader.Node, System.Xml.XmlBaseReader.ReadContentAsString(), System.Xml.XmlBaseReader.SkipValue(), System.text, and System.Xml.XmlExceptionHelper.ThrowMaxStringContentLengthExceeded().
Referenced by System.Xml.XmlBaseReader.ReadContentAs(), System.Xml.XmlBaseReader.ReadContentAsBoolean(), System.Xml.XmlBaseReader.ReadContentAsDateTime(), System.Runtime.Serialization.Json.XmlJsonReader.ReadContentAsDecimal(), System.Xml.XmlBaseReader.ReadContentAsDecimal(), System.Xml.XmlBaseReader.ReadContentAsDouble(), System.Xml.XmlBaseReader.ReadContentAsFloat(), System.Xml.XmlBaseReader.ReadContentAsGuid(), System.Runtime.Serialization.Json.XmlJsonReader.ReadContentAsInt(), System.Xml.XmlBaseReader.ReadContentAsInt(), System.Runtime.Serialization.Json.XmlJsonReader.ReadContentAsLong(), System.Xml.XmlBaseReader.ReadContentAsLong(), System.Xml.XmlBaseReader.ReadContentAsObject(), System.Xml.XmlBaseReader.ReadContentAsString(), System.Xml.XmlBaseReader.ReadContentAsTimeSpan(), System.Xml.XmlBaseReader.ReadContentAsUniqueId(), and System.Xml.XmlBaseReader.ReadElementContentAsString().