Terraria: System.Xml.XmlBaseReader.ExitScope
ExitScope()
void System.Xml.XmlBaseReader.ExitScope () inline protected inherited
Definition at line 1515 of file XmlBaseReader.cs.
    {
        if (_depth == 0)
        {
            XmlExceptionHelper.ThrowUnexpectedEndElement(this);
        }
        _depth--;
        _nsMgr.ExitScope();
    }
References System.Xml.XmlBaseReader.NamespaceManager._depth, System.Xml.XmlBaseReader._nsMgr, System.Xml.XmlBaseReader.NamespaceManager.ExitScope(), and System.Xml.XmlExceptionHelper.ThrowUnexpectedEndElement().
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.Read(), System.Xml.XmlBinaryReader.Read(), System.Xml.XmlUTF8TextReader.Read(), System.Xml.XmlBinaryReader.ReadTextWithEndElement(), and System.Xml.XmlBinaryReader.SkipArrayElements().