Terraria: System.Xml.XmlBaseReader.StartCanonicalization
StartCanonicalization() [1/2]
override void System.Xml.XmlBaseReader.StartCanonicalization (Stream stream, bool includeComments, string[] inclusivePrefixes) inline inherited
Definition at line 3095 of file XmlBaseReader.cs.
    {
        if (_signing)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlCanonicalizationStarted));
        }
        if (_signingWriter == null)
        {
            _signingWriter = CreateSigningNodeWriter();
        }
        _signingWriter.SetOutput(XmlNodeWriter.Null, stream, includeComments, inclusivePrefixes);
        _nsMgr.Sign(_signingWriter);
        _signing = true;
    }
References System.Xml.XmlBaseReader._nsMgr, System.Xml.XmlBaseReader._signing, System.Xml.XmlBaseReader._signingWriter, System.Xml.XmlBaseReader.CreateSigningNodeWriter(), System.Xml.Dictionary, System.Xml.XmlNodeWriter.Null, System.Xml.XmlSigningNodeWriter.SetOutput(), System.Xml.XmlBaseReader.NamespaceManager.Sign(), System.stream, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.XmlCanonicalizationStarted.