Terraria: System.Xml.XmlBaseReader.MoveToNode
MoveToNode()
void System.Xml.XmlBaseReader.MoveToNode (XmlNode node) inline protected inherited
Definition at line 1301 of file XmlBaseReader.cs.
    {
        _node = node;
        _ns = null;
        _localName = null;
        _prefix = null;
        _value = null;
    }
References System.Xml.XmlBaseReader._localName, System.Xml.XmlBaseReader._node, System.Xml.XmlBaseReader._ns, System.Xml.XmlBaseReader._prefix, System.Xml.XmlBaseReader._value, and System.Xml.Dictionary.
Referenced by System.Xml.XmlBaseReader.Close(), System.Xml.XmlBaseReader.EnterScope(), System.Xml.XmlBinaryReader.MoveToArrayElement(), System.Xml.XmlBaseReader.MoveToAtomicText(), System.Xml.XmlBaseReader.MoveToAttribute(), System.Xml.XmlBaseReader.MoveToAttribute(), System.Xml.XmlBaseReader.MoveToAttribute(), System.Xml.XmlBaseReader.MoveToCData(), System.Xml.XmlBaseReader.MoveToComment(), System.Xml.XmlBaseReader.MoveToComplexText(), System.Xml.XmlBaseReader.MoveToDeclaration(), System.Xml.XmlBaseReader.MoveToElement(), System.Xml.XmlBaseReader.MoveToEndElement(), System.Xml.XmlBaseReader.MoveToEndOfFile(), System.Xml.XmlBaseReader.MoveToFirstAttribute(), System.Xml.XmlBaseReader.MoveToInitial(), System.Xml.XmlBaseReader.MoveToNextAttribute(), System.Xml.XmlBaseReader.MoveToWhitespaceText(), and System.Xml.XmlBaseReader.ReadAttributeValue().