Terraria: PlayerInteractionAnchor.GetTileEntity
GetTileEntity()
TileEntity PlayerInteractionAnchor.GetTileEntity () inline
     {
         if (!IsInValidUseTileEntity())
         {
             return null;
         }
         return TileEntity.ByID[interactEntityID];
     }
References TileEntity.ByID, interactEntityID, and IsInValidUseTileEntity().
Referenced by Main.DrawInventory(), ItemSlot.GetOverrideInstructions(), UILinkPointNavigator.GoToDefaultPage(), UILinksInitializer.Load(), ItemSlot.OverrideHover(), and ItemSlot.OverrideLeftClick().