Terraria: UIBestiaryFilteringOptionsGrid.UpdateButtonSelections
UpdateButtonSelections()
void UIBestiaryFilteringOptionsGrid.UpdateButtonSelections () inline private
     {
         foreach (GroupOptionButton<int> filterButton in _filterButtons)
         {
             bool flag = _filterer.IsFilterActive(filterButton.OptionValue);
             filterButton.SetCurrentOption(flag ? filterButton.OptionValue : (-1));
             if (flag)
             {
                 filterButton.SetColor(new Color(152, 175, 235), 1f);
             }
             else
             {
                 filterButton.SetColor(Colors.InventoryDefaultColor, 0.7f);
             }
         }
     }
References _filterButtons, _filterer, Color, Colors.InventoryDefaultColor, EntryFilterer< T, U >.IsFilterActive(), GroupOptionButton< T >.OptionValue, GroupOptionButton< T >.SetColor(), and GroupOptionButton< T >.SetCurrentOption().
Referenced by ClickOption(), and UpdateAvailability().