Terraria: UIBestiaryFilteringOptionsGrid.ClickOption
ClickOption()
void UIBestiaryFilteringOptionsGrid.ClickOption (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         int optionValue = ((GroupOptionButton<int>)listeningElement).OptionValue;
         _filterer.ToggleFilter(optionValue);
         UpdateButtonSelections();
         if (this.OnClickingOption != null)
         {
             this.OnClickingOption();
         }
     }
References _filterer, OnClickingOption, EntryFilterer< T, U >.ToggleFilter(), and UpdateButtonSelections().
Referenced by UpdateAvailability().