Terraria: UIBestiaryFilteringOptionsGrid.UpdateAvailability
UpdateAvailability()
void UIBestiaryFilteringOptionsGrid.UpdateAvailability () inline
     {
         GetDisplaySettings(out var widthPerButton, out var heightPerButton, out var widthWithSpacing, out var heightWithSpacing, out var perRow, out var offsetLeft, out var offsetTop, out var _);
         _container.RemoveAllChildren();
         _filterButtons.Clear();
         _areFiltersAvailable.Clear();
         int num = -1;
         int num2 = -1;
         for (int i = 0; i < _filterer.AvailableFilters.Count; i++)
         {
             int num3 = i / perRow;
             int num4 = i % perRow;
             IBestiaryEntryFilter bestiaryEntryFilter = _filterer.AvailableFilters[i];
             List<BestiaryEntry> entries = _filterAvailabilityTests[i];
             if (GetIsFilterAvailableForEntries(bestiaryEntryFilter, entries))
             {
                 GroupOptionButton<int> groupOptionButton = new GroupOptionButton<int>(i, null, null, Color.White, null)
                 {
                     Width = new StyleDimension(widthPerButton, 0f),
                     Height = new StyleDimension(heightPerButton, 0f),
                     HAlign = 0f,
                     VAlign = 0f,
                     Top = new StyleDimension(offsetTop + (float)(num3 * heightWithSpacing), 0f),
                     Left = new StyleDimension(offsetLeft + (float)(num4 * widthWithSpacing), 0f)
                 };
                 groupOptionButton.OnLeftClick += ClickOption;
                 groupOptionButton.SetSnapPoint("Filters", i);
                 groupOptionButton.ShowHighlightWhenSelected = false;
                 AddOnHover(bestiaryEntryFilter, groupOptionButton);
                 _container.Append(groupOptionButton);
                 UIElement image = bestiaryEntryFilter.GetImage();
                 if (image != null)
                 {
                     image.Left = new StyleDimension(num, 0f);
                     image.Top = new StyleDimension(num2, 0f);
                     groupOptionButton.Append(image);
                 }
                 _filterButtons.Add(groupOptionButton);
             }
             else
             {
                 _filterer.ActiveFilters.Remove(bestiaryEntryFilter);
                 GroupOptionButton<int> groupOptionButton2 = new GroupOptionButton<int>(-2, null, null, Color.White, null)
                 {
                     Width = new StyleDimension(widthPerButton, 0f),
                     Height = new StyleDimension(heightPerButton, 0f),
                     HAlign = 0f,
                     VAlign = 0f,
                     Top = new StyleDimension(offsetTop + (float)(num3 * heightWithSpacing), 0f),
                     Left = new StyleDimension(offsetLeft + (float)(num4 * widthWithSpacing), 0f),
                     FadeFromBlack = 0.5f
                 };
                 groupOptionButton2.ShowHighlightWhenSelected = false;
                 groupOptionButton2.SetPadding(0f);
                 groupOptionButton2.SetSnapPoint("Filters", i);
                 Asset<Texture2D> obj = Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Icon_Tags_Shadow", (AssetRequestMode)1);
                 UIImageFramed uIImageFramed = new UIImageFramed(obj, obj.Frame(16, 5, 0, 4))
                 {
                     HAlign = 0.5f,
                     VAlign = 0.5f,
                     Color = Color.White * 0.2f
                 };
                 uIImageFramed.Left = new StyleDimension(num, 0f);
                 uIImageFramed.Top = new StyleDimension(num2, 0f);
                 groupOptionButton2.Append(uIImageFramed);
                 _filterButtons.Add(groupOptionButton2);
                 _container.Append(groupOptionButton2);
             }
         }
         UpdateButtonSelections();
     }
References _areFiltersAvailable, _container, _filterAvailabilityTests, _filterButtons, _filterer, EntryFilterer< T, U >.ActiveFilters, AddOnHover(), UIElement.Append(), Main.Assets, EntryFilterer< T, U >.AvailableFilters, ClickOption(), Color, GetDisplaySettings(), IEntryFilter< T >.GetImage(), GetIsFilterAvailableForEntries(), UIElement.HAlign, UIElement.Height, UIElement.Left, UIElement.OnLeftClick, UIElement.RemoveAllChildren(), UIElement.SetPadding(), UIElement.SetSnapPoint(), GroupOptionButton< T >.ShowHighlightWhenSelected, UIElement.Top, UpdateButtonSelections(), UIElement.VAlign, and UIElement.Width.
Referenced by UIBestiaryTest.UpdateBestiaryContents().