Terraria: System.Collections.IEqualityComparer.Equals
Equals() [2/2]
new bool System.Collections.IEqualityComparer.Equals (object? x, object? y) inherited
Referenced by System.Linq.Parallel.Lookup< TKey, TElement >.Add(), System.ComponentModel.ComponentResourceManager.ApplyResources(), System.Collections.Specialized.NameObjectCollectionBase.BaseRemove(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.ChangeItemKey(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Contains(), System.Linq.Parallel.Lookup< TKey, TElement >.Contains(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.Contains(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Builder.ContainsValue(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.ContainsValue(), System.Collections.Generic.HashSet< T >.EqualityComparersAreEqual(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Comparers.Equals(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Comparers.Equals(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.FillFromEmpty(), System.Linq.Lookup< TKey, TElement >.GetGrouping(), System.Collections.Specialized.OrderedDictionary.IndexOfKey(), System.Collections.Hashtable.KeyEquals(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.SetItem(), and System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.TryGetValue().