Terraria: Terraria.Social.Steam.NetSocialModule._lobby
_lobby
Lobby Terraria.Social.Steam.NetSocialModule._lobby = new Lobby() protected inherited
Definition at line 38 of file NetSocialModule.cs.
Referenced by Terraria.Social.Steam.NetServerSocialModule.BroadcastConnectedUsers(), Terraria.Social.Steam.NetClientSocialModule.CancelJoin(), Terraria.Social.Steam.NetClientSocialModule.CanInvite(), Terraria.Social.Steam.NetClientSocialModule.Close(), Terraria.Social.Steam.NetClientSocialModule.ConnectToLobby(), Terraria.Social.Steam.NetServerSocialModule.GetLobbyId(), Terraria.Social.Steam.NetServerSocialModule.Initialize(), Terraria.Social.Steam.NetClientSocialModule.LaunchLocalServer(), Terraria.Social.Steam.NetSocialModule.OnLobbyChatMessage(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyEntered(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest(), Terraria.Social.Steam.NetClientSocialModule.OpenInviteInterface(), and Terraria.Social.Steam.NetSocialModule.Shutdown().