Terraria: Terraria.Social.Steam.NetSocialModule.IsConnected
IsConnected()
override bool Terraria.Social.Steam.NetSocialModule.IsConnected (RemoteAddress address) inline inherited
    {
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        if (address == null)
        {
            return false;
        }
        CSteamID val = RemoteAddressToSteamId(address);
        if (!_connectionStateMap.ContainsKey(val) || _connectionStateMap[val] != ConnectionState.Connected)
        {
            return false;
        }
        if (GetSessionState(val).m_bConnectionActive != 1)
        {
            Close(address);
            return false;
        }
        return true;
    }
References Terraria.Social.Steam.NetSocialModule._connectionStateMap, Terraria.Social.Base.NetSocialModule.Close(), Terraria.Social.Steam.NetSocialModule.GetSessionState(), and Terraria.Social.Steam.NetSocialModule.RemoteAddressToSteamId().