Terraria: System.Runtime.Intrinsics.X86.Bmi1.BitFieldExtract
BitFieldExtract() [1/2]
static uint System.Runtime.Intrinsics.X86.Bmi1.BitFieldExtract (uint value, byte start, byte length) inline static
Definition at line 57 of file Bmi1.cs.
    {
        return BitFieldExtract(value, (ushort)(start | (length << 8)));
    }
References System.Runtime.Intrinsics.X86.Bmi1.BitFieldExtract(), System.length, System.start, and System.value.
Referenced by System.Runtime.Intrinsics.X86.Bmi1.BitFieldExtract(), and System.Runtime.Intrinsics.X86.Bmi1.BitFieldExtract().