Terraria: Terraria.Social.Steam.NetSocialModule.OnLobbyChatMessage
OnLobbyChatMessage()
virtual void Terraria.Social.Steam.NetSocialModule.OnLobbyChatMessage (LobbyChatMsg_t result) inline protected virtual inherited
Definition at line 89 of file NetSocialModule.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        if (result.m_ulSteamIDLobby != _lobby.Id.m_SteamID || result.m_eChatEntryType != 1 || result.m_ulSteamIDUser != _lobby.Owner.m_SteamID)
        {
            return;
        }
        byte[] message = _lobby.GetMessage((int)result.m_iChatID);
        if (message.Length == 0)
        {
            return;
        }
        using MemoryStream memoryStream = new MemoryStream(message);
        using BinaryReader binaryReader = new BinaryReader(memoryStream);
        byte b = binaryReader.ReadByte();
        if (b != 1)
        {
            return;
        }
        CSteamID val = default(CSteamID);
        while (message.Length - memoryStream.Position >= 8)
        {
            ((CSteamID)(ref val))._002Ector(binaryReader.ReadUInt64());
            if (val != SteamUser.GetSteamID())
            {
                _lobby.SetPlayedWith(val);
            }
        }
    }
References Terraria.Social.Steam.NetSocialModule._lobby, Terraria.Social.Steam.Lobby.GetMessage(), Terraria.Social.Steam.Lobby.Id, Terraria.Social.Steam.Lobby.Owner, and Terraria.Social.Steam.Lobby.SetPlayedWith().
Referenced by Terraria.Social.Steam.NetSocialModule.Initialize().