Terraria: Terraria.Social.Steam.NetSocialModule.RemoteAddressToSteamId
RemoteAddressToSteamId()
CSteamID Terraria.Social.Steam.NetSocialModule.RemoteAddressToSteamId (RemoteAddress address) inline protected inherited
Definition at line 134 of file NetSocialModule.cs.
    {
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        return ((SteamAddress)address).SteamId;
    }
Referenced by Terraria.Social.Steam.NetClientSocialModule.Close(), Terraria.Social.Steam.NetServerSocialModule.Close(), Terraria.Social.Steam.NetSocialModule.IsConnected(), Terraria.Social.Steam.NetSocialModule.IsDataAvailable(), Terraria.Social.Steam.NetSocialModule.Receive(), and Terraria.Social.Steam.NetSocialModule.Send().