Terraria: Terraria.GameContent.Generation.ShapeBranch.PerformSegment
PerformSegment()
bool Terraria.GameContent.Generation.ShapeBranch.PerformSegment (Point origin, GenAction action, Point start, Point end, int size) inline private
Definition at line 30 of file ShapeBranch.cs.
    {
        size = Math.Max(1, size);
        for (int i = -(size >> 1); i < size - (size >> 1); i++)
        {
            for (int j = -(size >> 1); j < size - (size >> 1); j++)
            {
                if (!Utils.PlotLine(new Point(start.X + i, start.Y + j), end, (int tileX, int tileY) => UnitApply(action, origin, tileX, tileY) || !_quitOnFail, jump: false))
                {
                    return false;
                }
            }
        }
        return true;
    }
References Terraria.WorldBuilding.GenShape._quitOnFail, System.action, System.Math.Max(), Terraria.Utils.PlotLine(), System.start, and Terraria.WorldBuilding.GenShape.UnitApply().
Referenced by Terraria.GameContent.Generation.ShapeBranch.Perform().