Terraria: System.Xml.Linq.XHashtable.XHashtableState.TryGetValue
TryGetValue()
bool System.Xml.Linq.XHashtable< TValue >.XHashtableState.TryGetValue (string key, int index, int count, [MaybeNullWhen(false)] out TValue value) inline
Definition at line 82 of file XHashtable.cs.
        {
            int hashCode = ComputeHashCode(key, index, count);
            int entryIndex = 0;
            if (FindEntry(hashCode, key, index, count, ref entryIndex))
            {
                value = _entries[entryIndex].Value;
                return true;
            }
            value = default(TValue);
            return false;
        }
References System.Xml.Linq.XHashtable< TValue >.XHashtableState._entries, System.Xml.Linq.XHashtable< TValue >.XHashtableState.ComputeHashCode(), System.count, System.Xml.Dictionary, System.Xml.Linq.XHashtable< TValue >.XHashtableState.FindEntry(), System.index, System.key, System.value, and System.Xml.Linq.XHashtable< TValue >.XHashtableState.Entry.Value.
Referenced by System.Xml.Linq.XHashtable< TValue >.TryGetValue().