Terraria: System.Xml.Linq.XHashtable.XHashtableState.TryAdd
TryAdd()
bool System.Xml.Linq.XHashtable< TValue >.XHashtableState.TryAdd (TValue value, out TValue newValue) inline
Definition at line 95 of file XHashtable.cs.
        {
            newValue = value;
            string text = _extractKey(value);
            if (text == null)
            {
                return true;
            }
            int num = ComputeHashCode(text, 0, text.Length);
            int num2 = Interlocked.Increment(ref _numEntries);
            if (num2 < 0 || num2 >= _buckets.Length)
            {
                return false;
            }
            _entries[num2].Value = value;
            _entries[num2].HashCode = num;
            Thread.MemoryBarrier();
            int entryIndex = 0;
            while (!FindEntry(num, text, 0, text.Length, ref entryIndex))
            {
                entryIndex = ((entryIndex != 0) ? Interlocked.CompareExchange(ref _entries[entryIndex].Next, num2, 0) : Interlocked.CompareExchange(ref _buckets[num & (_buckets.Length - 1)], num2, 0));
                if (entryIndex <= 0)
                {
                    return entryIndex == 0;
                }
            }
            newValue = _entries[entryIndex].Value;
            return true;
        }
References System.Xml.Linq.XHashtable< TValue >.XHashtableState._buckets, System.Xml.Linq.XHashtable< TValue >.XHashtableState._entries, System.Xml.Linq.XHashtable< TValue >.XHashtableState._extractKey, System.Xml.Linq.XHashtable< TValue >.XHashtableState._numEntries, System.Threading.Interlocked.CompareExchange(), System.Xml.Linq.XHashtable< TValue >.XHashtableState.ComputeHashCode(), System.Xml.Dictionary, System.Xml.Linq.XHashtable< TValue >.XHashtableState.FindEntry(), System.Xml.Linq.XHashtable< TValue >.XHashtableState.Entry.HashCode, System.Threading.Interlocked.Increment(), System.Threading.Thread.MemoryBarrier(), System.Xml.Linq.XHashtable< TValue >.XHashtableState.Entry.Next, System.text, System.value, and System.Xml.Linq.XHashtable< TValue >.XHashtableState.Entry.Value.
Referenced by System.Xml.Linq.XHashtable< TValue >.Add().