Terraria: System.Xml.Linq.XHashtable.XHashtableState.Resize
Resize()
XHashtableState System.Xml.Linq.XHashtable< TValue >.XHashtableState.Resize () inline
Definition at line 36 of file XHashtable.cs.
        {
            if (_numEntries < _buckets.Length)
            {
                return this;
            }
            int num = 0;
            for (int i = 0; i < _buckets.Length; i++)
            {
                int num2 = _buckets[i];
                if (num2 == 0)
                {
                    num2 = Interlocked.CompareExchange(ref _buckets[i], -1, 0);
                }
                while (num2 > 0)
                {
                    if (_extractKey(_entries[num2].Value) != null)
                    {
                        num++;
                    }
                    num2 = ((_entries[num2].Next != 0) ? _entries[num2].Next : Interlocked.CompareExchange(ref _entries[num2].Next, -1, 0));
                }
            }
            if (num < _buckets.Length / 2)
            {
                num = _buckets.Length;
            }
            else
            {
                num = _buckets.Length * 2;
                if (num < 0)
                {
                    throw new OverflowException();
                }
            }
            XHashtableState xHashtableState = new XHashtableState(_extractKey, num);
            for (int j = 0; j < _buckets.Length; j++)
            {
                for (int num3 = _buckets[j]; num3 > 0; num3 = _entries[num3].Next)
                {
                    xHashtableState.TryAdd(_entries[num3].Value, out var _);
                }
            }
            return xHashtableState;
        }
References System.Xml.Linq.XHashtable< TValue >.XHashtableState.XHashtableState(), System.Xml.Linq.XHashtable< TValue >.XHashtableState._buckets, System.Xml.Linq.XHashtable< TValue >.XHashtableState._entries, System.Xml.Linq.XHashtable< TValue >.XHashtableState._extractKey, System.Xml.Linq.XHashtable< TValue >.XHashtableState._numEntries, System.Threading.Interlocked.CompareExchange(), System.Xml.Dictionary, System.Xml.Linq.XHashtable< TValue >.XHashtableState.Entry.Next, and System.Xml.Linq.Value.
Referenced by System.Xml.Linq.XHashtable< TValue >.Add().