Terraria: System.Globalization.JulianCalendar.IsLeapDay
IsLeapDay() [2/2]
override bool System.Globalization.JulianCalendar.IsLeapDay (int year, int month, int day, int era) inline
Definition at line 221 of file JulianCalendar.cs.
    {
        CheckMonthRange(month);
        if (IsLeapYear(year, era))
        {
            CheckDayRange(year, month, day);
            if (month == 2)
            {
                return day == 29;
            }
            return false;
        }
        CheckDayRange(year, month, day);
        return false;
    }
References System.Globalization.JulianCalendar.CheckDayRange(), System.Globalization.JulianCalendar.CheckMonthRange(), System.Globalization.JulianCalendar.IsLeapYear(), and System.year.