Terraria: System.Globalization.JulianCalendar.CheckDayRange
CheckDayRange()
static void System.Globalization.JulianCalendar.CheckDayRange (int year, int month, int day) inline static package
Definition at line 78 of file JulianCalendar.cs.
    {
        if (year == 1 && month == 1 && day < 3)
        {
            throw new ArgumentOutOfRangeException(null, SR.ArgumentOutOfRange_BadYearMonthDay);
        }
        int[] array = ((year % 4 == 0) ? s_daysToMonth366 : s_daysToMonth365);
        int num = array[month] - array[month - 1];
        if (day < 1 || day > num)
        {
            throw new ArgumentOutOfRangeException("day", day, SR.Format(SR.ArgumentOutOfRange_Range, 1, num));
        }
    }
References System.SR.ArgumentOutOfRange_BadYearMonthDay, System.SR.ArgumentOutOfRange_Range, System.array, System.SR.Format(), System.Globalization.JulianCalendar.s_daysToMonth365, System.Globalization.JulianCalendar.s_daysToMonth366, and System.year.
Referenced by System.Globalization.JulianCalendar.IsLeapDay(), and System.Globalization.JulianCalendar.ToDateTime().