Terraria: IngameFancyUI.Draw
Draw()
static bool IngameFancyUI.Draw (SpriteBatch spriteBatch, GameTime gameTime) inline static
     {
         bool result = false;
         if (Main.InGameUI.CurrentState is UIVirtualKeyboard && UIVirtualKeyboard.KeyboardContext > 0)
         {
             if (!Main.inFancyUI)
             {
                 Main.InGameUI.SetState(null);
             }
             if (Main.screenWidth >= 1705 || !PlayerInput.UsingGamepad)
             {
                 result = true;
             }
         }
         if (!Main.gameMenu)
         {
             Main.mouseText = false;
             if (Main.InGameUI != null && Main.InGameUI.IsElementUnderMouse())
             {
                 Main.player[Main.myPlayer].mouseInterface = true;
             }
             Main.instance.GUIBarsDraw();
             if (Main.InGameUI.CurrentState is UIVirtualKeyboard && UIVirtualKeyboard.KeyboardContext > 0)
             {
                 Main.instance.GUIChatDraw();
             }
             if (!Main.inFancyUI)
             {
                 Main.InGameUI.SetState(null);
             }
             Main.instance.DrawMouseOver();
             Main.DrawCursor(Main.DrawThickCursor());
         }
         return result;
     }
References UserInterface.CurrentState, Main.DrawCursor(), Main.DrawMouseOver(), Main.DrawThickCursor(), Main.gameMenu, Main.GUIBarsDraw(), Main.GUIChatDraw(), Main.inFancyUI, Main.InGameUI, Main.instance, UserInterface.IsElementUnderMouse(), UIVirtualKeyboard.KeyboardContext, Player.mouseInterface, Main.mouseText, Main.myPlayer, Main.player, Main.screenWidth, UserInterface.SetState(), and PlayerInput.UsingGamepad.
Referenced by Main.DrawInterface_12_IngameFancyUI().