Terraria: IngameFancyUI.Close
Close()
static void IngameFancyUI.Close () inline static
     {
         Main.inFancyUI = false;
         SoundEngine.PlaySound(11);
         bool flag = !Main.gameMenu;
         bool flag2 = !(Main.InGameUI.CurrentState is UIVirtualKeyboard);
         bool flag3 = false;
         int keyboardContext = UIVirtualKeyboard.KeyboardContext;
         if ((uint)(keyboardContext - 2) <= 1u)
         {
             flag3 = true;
         }
         if (flag && !(flag2 || flag3))
         {
             flag = false;
         }
         if (flag)
         {
             Main.playerInventory = true;
         }
         if (!Main.gameMenu && Main.InGameUI.CurrentState is UIEmotesMenu)
         {
             Main.playerInventory = false;
         }
         Main.LocalPlayer.releaseInventory = false;
         Main.InGameUI.SetState(null);
         UILinkPointNavigator.Shortcuts.FANCYUI_SPECIAL_INSTRUCTIONS = 0;
     }
References UserInterface.CurrentState, UILinkPointNavigator.Shortcuts.FANCYUI_SPECIAL_INSTRUCTIONS, Main.gameMenu, Main.inFancyUI, Main.InGameUI, UIVirtualKeyboard.KeyboardContext, Main.LocalPlayer, Main.playerInventory, SoundEngine.PlaySound(), Player.releaseInventory, and UserInterface.SetState().
Referenced by UIBestiaryTest.Click_GoBack(), UIVirtualKeyboard.DrawSelf(), UICreativeInfiniteItemsDisplay.EscapeVirtualKeyboard(), UILinksInitializer.FancyExit(), UIAchievementsMenu.GoBackClick(), UIEmotesMenu.GoBackClick(), UIManageControls.GoBackClick(), UICreativeInfiniteItemsDisplay.GoBackHere(), UIResourcePackSelectionMenu.HandleBackButtonUsage(), EmoteButton.LeftClick(), Player.ToggleCreativeMenu(), Player.ToggleInv(), and UIVirtualKeyboard.TryEscapingMenu().