Terraria: IngameFancyUI.OpenVirtualKeyboard
OpenVirtualKeyboard()
static void IngameFancyUI.OpenVirtualKeyboard (int keyboardContext) inline static
     {
         CoverNextFrame();
         ClearChat();
         SoundEngine.PlaySound(12);
         string labelText = "";
         switch (keyboardContext)
         {
         case 1:
             Main.editSign = true;
             labelText = Language.GetTextValue("UI.EnterMessage");
             break;
         case 2:
         {
             labelText = Language.GetTextValue("UI.EnterNewName");
             Player player = Main.player[Main.myPlayer];
             Main.npcChatText = Main.chest[player.chest].name;
             Tile tile = Main.tile[player.chestX, player.chestY];
             if (tile.type == 21)
             {
                 Main.defaultChestName = Lang.chestType[tile.frameX / 36].Value;
             }
             else if (tile.type == 467 && tile.frameX / 36 == 4)
             {
                 Main.defaultChestName = Lang.GetItemNameValue(3988);
             }
             else if (tile.type == 467)
             {
                 Main.defaultChestName = Lang.chestType2[tile.frameX / 36].Value;
             }
             else if (tile.type == 88)
             {
                 Main.defaultChestName = Lang.dresserType[tile.frameX / 54].Value;
             }
             if (Main.npcChatText == "")
             {
                 Main.npcChatText = Main.defaultChestName;
             }
             Main.editChest = true;
             break;
         }
         }
         Main.clrInput();
         if (!CanShowVirtualKeyboard(keyboardContext))
         {
             return;
         }
         Main.inFancyUI = true;
         switch (keyboardContext)
         {
         case 1:
             Main.InGameUI.SetState(new UIVirtualKeyboard(labelText, Main.npcChatText, delegate
             {
                 Main.SubmitSignText();
                 Close();
             }, delegate
             {
                 Main.InputTextSignCancel();
                 Close();
             }, keyboardContext));
             break;
         case 2:
             Main.InGameUI.SetState(new UIVirtualKeyboard(labelText, Main.npcChatText, delegate
             {
                 ChestUI.RenameChestSubmit(Main.player[Main.myPlayer]);
                 Close();
             }, delegate
             {
                 ChestUI.RenameChestCancel();
                 Close();
             }, keyboardContext));
             break;
         }
         UILinkPointNavigator.GoToDefaultPage(1);
     }
References CanShowVirtualKeyboard(), Main.chest, Player.chest, Lang.chestType, Lang.chestType2, Player.chestX, Player.chestY, ClearChat(), Main.clrInput(), CoverNextFrame(), Main.defaultChestName, Lang.dresserType, Main.editChest, Main.editSign, Tile.frameX, Lang.GetItemNameValue(), Language.GetTextValue(), UILinkPointNavigator.GoToDefaultPage(), Main.inFancyUI, Main.InGameUI, Main.myPlayer, Chest.name, Main.npcChatText, Main.player, SoundEngine.PlaySound(), UserInterface.SetState(), Main.tile, Tile.type, and LocalizedText.Value.
Referenced by Main.GUIChatDrawInner(), and ChestUI.RenameChest().