Terraria: IngameFancyUI.OpenAchievements
OpenAchievements()
static void IngameFancyUI.OpenAchievements () inline static
     {
         CoverNextFrame();
         Main.playerInventory = false;
         Main.editChest = false;
         Main.npcChatText = "";
         Main.inFancyUI = true;
         ClearChat();
         Main.InGameUI.SetState(Main.AchievementsMenu);
     }
References Main.AchievementsMenu, ClearChat(), CoverNextFrame(), Main.editChest, Main.inFancyUI, Main.InGameUI, Main.npcChatText, Main.playerInventory, and UserInterface.SetState().
Referenced by IngameOptions.Draw(), and OpenAchievementsAndGoto().