Terraria: System.Threading.ReaderWriterLock.RestoreLock
RestoreLock()
void System.Threading.ReaderWriterLock.RestoreLock (ref LockCookie lockCookie) inline
Definition at line 718 of file ReaderWriterLock.cs.
    {
        int currentThreadID = GetCurrentThreadID();
        if (lockCookie._threadID != currentThreadID)
        {
            throw GetInvalidLockCookieException();
        }
        if (_writerID == currentThreadID || ThreadLocalLockEntry.GetCurrent(_lockID) != null)
        {
            throw new SynchronizationLockException(System.SR.ReaderWriterLock_RestoreLockWithOwnedLocks);
        }
        LockCookieFlags flags = lockCookie._flags;
        if (((uint)flags & 0xFFF89FFFu) != 0)
        {
            throw GetInvalidLockCookieException();
        }
        if ((flags & LockCookieFlags.OwnedNone) == 0)
        {
            if ((flags & LockCookieFlags.OwnedWriter) != 0)
            {
                if (Interlocked.CompareExchange(ref _state, 4096, 0) == 0)
                {
                    _writerID = currentThreadID;
                    _writerLevel = lockCookie._writerLevel;
                    _writerSeqNum++;
                    goto IL_00e5;
                }
            }
            else if ((flags & LockCookieFlags.OwnedReader) != 0)
            {
                ThreadLocalLockEntry orCreateCurrent = ThreadLocalLockEntry.GetOrCreateCurrent(_lockID);
                int state = _state;
                if (state < 1023 && Interlocked.CompareExchange(ref _state, state + 1, state) == state)
                {
                    orCreateCurrent._readerLevel = lockCookie._readerLevel;
                    goto IL_00e5;
                }
            }
            RecoverLock(ref lockCookie, flags);
        }
        goto IL_00e5;
        IL_00e5:
        lockCookie._flags = LockCookieFlags.Invalid;
    }
References System.Threading.ReaderWriterLock._lockID, System.Threading.ReaderWriterLock._state, System.Threading.ReaderWriterLock._writerID, System.Threading.ReaderWriterLock._writerLevel, System.Threading.ReaderWriterLock._writerSeqNum, System.Threading.Interlocked.CompareExchange(), System.Runtime.Serialization.Dictionary, System.Threading.ReaderWriterLock.ThreadLocalLockEntry.GetCurrent(), System.Threading.ReaderWriterLock.GetCurrentThreadID(), System.Threading.ReaderWriterLock.GetInvalidLockCookieException(), System.Threading.ReaderWriterLock.ThreadLocalLockEntry.GetOrCreateCurrent(), System.SR.ReaderWriterLock_RestoreLockWithOwnedLocks, System.Threading.ReaderWriterLock.RecoverLock(), and System.state.