Terraria: System.Threading.ReaderWriterLock.GetCurrentThreadID
GetCurrentThreadID()
static int System.Threading.ReaderWriterLock.GetCurrentThreadID () inline static private
Definition at line 779 of file ReaderWriterLock.cs.
    {
        return Environment.CurrentManagedThreadId;
    }
References System.Environment.CurrentManagedThreadId.
Referenced by System.Threading.ReaderWriterLock.AcquireReaderLock(), System.Threading.ReaderWriterLock.AcquireWriterLock(), System.Threading.ReaderWriterLock.AnyWritersSince(), System.Threading.ReaderWriterLock.DowngradeFromWriterLock(), System.Threading.ReaderWriterLock.ReleaseLock(), System.Threading.ReaderWriterLock.ReleaseReaderLock(), System.Threading.ReaderWriterLock.ReleaseWriterLock(), System.Threading.ReaderWriterLock.RestoreLock(), and System.Threading.ReaderWriterLock.UpgradeToWriterLock().