Terraria: System.Threading.ReaderWriterLock.UpgradeToWriterLock
UpgradeToWriterLock() [1/2]
LockCookie System.Threading.ReaderWriterLock.UpgradeToWriterLock (int millisecondsTimeout) inline
Definition at line 568 of file ReaderWriterLock.cs.
    {
        if (millisecondsTimeout < -1)
        {
            throw GetInvalidTimeoutException("millisecondsTimeout");
        }
        LockCookie lockCookie = default(LockCookie);
        int num = (lockCookie._threadID = GetCurrentThreadID());
        if (_writerID == num)
        {
            lockCookie._flags = LockCookieFlags.Upgrade | LockCookieFlags.OwnedWriter;
            lockCookie._writerLevel = _writerLevel;
            AcquireWriterLock(millisecondsTimeout);
            return lockCookie;
        }
        ThreadLocalLockEntry current = ThreadLocalLockEntry.GetCurrent(_lockID);
        if (current == null)
        {
            lockCookie._flags = LockCookieFlags.Upgrade | LockCookieFlags.OwnedNone;
        }
        else
        {
            lockCookie._flags = LockCookieFlags.Upgrade | LockCookieFlags.OwnedReader;
            lockCookie._readerLevel = current._readerLevel;
            int num2 = Interlocked.CompareExchange(ref _state, 4096, 1);
            if (num2 == 1)
            {
                current._readerLevel = 0;
                _writerID = num;
                _writerLevel = 1;
                _writerSeqNum++;
                return lockCookie;
            }
            current._readerLevel = 1;
            ReleaseReaderLock();
        }
        bool flag = false;
        try
        {
            AcquireWriterLock(millisecondsTimeout);
            flag = true;
            return lockCookie;
        }
        finally
        {
            if (!flag)
            {
                LockCookieFlags flags = lockCookie._flags;
                lockCookie._flags = LockCookieFlags.Invalid;
                RecoverLock(ref lockCookie, flags & LockCookieFlags.OwnedReader);
            }
        }
    }
References System.Threading.ReaderWriterLock._lockID, System.Threading.ReaderWriterLock.ThreadLocalLockEntry._readerLevel, System.Threading.ReaderWriterLock._state, System.Threading.ReaderWriterLock._writerID, System.Threading.ReaderWriterLock._writerLevel, System.Threading.ReaderWriterLock._writerSeqNum, System.Threading.ReaderWriterLock.AcquireWriterLock(), System.Threading.Interlocked.CompareExchange(), System.Runtime.Serialization.Dictionary, System.Threading.ReaderWriterLock.ThreadLocalLockEntry.GetCurrent(), System.Threading.ReaderWriterLock.GetCurrentThreadID(), System.Threading.ReaderWriterLock.GetInvalidTimeoutException(), System.millisecondsTimeout, System.Threading.ReaderWriterLock.RecoverLock(), and System.Threading.ReaderWriterLock.ReleaseReaderLock().
Referenced by System.Threading.ReaderWriterLock.UpgradeToWriterLock().