Terraria: System.Threading.ReaderWriterLock.DowngradeFromWriterLock
DowngradeFromWriterLock()
void System.Threading.ReaderWriterLock.DowngradeFromWriterLock (ref LockCookie lockCookie) inline
Definition at line 628 of file ReaderWriterLock.cs.
    {
        int currentThreadID = GetCurrentThreadID();
        if (_writerID != currentThreadID)
        {
            throw GetNotOwnerException();
        }
        LockCookieFlags flags = lockCookie._flags;
        ushort writerLevel = lockCookie._writerLevel;
        if (((uint)flags & 0xFFF89FFFu) != 0 || lockCookie._threadID != currentThreadID || ((flags & (LockCookieFlags.OwnedNone | LockCookieFlags.OwnedWriter)) != 0 && _writerLevel <= writerLevel))
        {
            throw GetInvalidLockCookieException();
        }
        if ((flags & LockCookieFlags.OwnedReader) != 0)
        {
            ThreadLocalLockEntry orCreateCurrent = ThreadLocalLockEntry.GetOrCreateCurrent(_lockID);
            _writerID = -1;
            _writerLevel = 0;
            ManualResetEventSlim manualResetEventSlim = null;
            int num = _state;
            int num2;
            do
            {
                num2 = num;
                int num3 = -4095;
                if (((uint)num2 & 0x7FE000u) != 0)
                {
                    manualResetEventSlim = TryGetOrCreateReaderEvent();
                    if (manualResetEventSlim == null)
                    {
                        Thread.Sleep(100);
                        num = _state;
                        num2 = 0;
                        continue;
                    }
                    num3 += 1024;
                }
                num = Interlocked.CompareExchange(ref _state, num2 + num3, num2);
            }
            while (num != num2);
            if (((uint)num2 & 0x7FE000u) != 0)
            {
                manualResetEventSlim.Set();
            }
            orCreateCurrent._readerLevel = lockCookie._readerLevel;
        }
        else if ((flags & (LockCookieFlags.OwnedNone | LockCookieFlags.OwnedWriter)) != 0)
        {
            if (writerLevel > 0)
            {
                _writerLevel = writerLevel;
            }
            else
            {
                if (_writerLevel != 1)
                {
                    _writerLevel = 1;
                }
                ReleaseWriterLock();
            }
        }
        lockCookie._flags = LockCookieFlags.Invalid;
    }
References System.Threading.ReaderWriterLock._lockID, System.Threading.ReaderWriterLock._state, System.Threading.ReaderWriterLock._writerID, System.Threading.ReaderWriterLock._writerLevel, System.Threading.Interlocked.CompareExchange(), System.Runtime.Serialization.Dictionary, System.Threading.ReaderWriterLock.GetCurrentThreadID(), System.Threading.ReaderWriterLock.GetInvalidLockCookieException(), System.Threading.ReaderWriterLock.GetNotOwnerException(), System.Threading.ReaderWriterLock.ThreadLocalLockEntry.GetOrCreateCurrent(), System.Threading.ReaderWriterLock.ReleaseWriterLock(), System.Threading.Thread.Sleep(), and System.Threading.ReaderWriterLock.TryGetOrCreateReaderEvent().