Terraria: System.Threading.ReaderWriterLock.AcquireReaderLock
AcquireReaderLock() [1/2]
void System.Threading.ReaderWriterLock.AcquireReaderLock (int millisecondsTimeout) inline
Definition at line 178 of file ReaderWriterLock.cs.
    {
        if (millisecondsTimeout < -1)
        {
            throw GetInvalidTimeoutException("millisecondsTimeout");
        }
        ThreadLocalLockEntry orCreateCurrent = ThreadLocalLockEntry.GetOrCreateCurrent(_lockID);
        if (Interlocked.CompareExchange(ref _state, 1, 0) != 0)
        {
            if (orCreateCurrent._readerLevel > 0)
            {
                if (orCreateCurrent._readerLevel == ushort.MaxValue)
                {
                    throw new OverflowException(System.SR.Overflow_UInt16);
                }
                orCreateCurrent._readerLevel++;
                return;
            }
            if (_writerID == GetCurrentThreadID())
            {
                AcquireWriterLock(millisecondsTimeout);
                return;
            }
            int num = 0;
            int num2 = _state;
            do
            {
                int num3 = num2;
                if (num3 < 1023 || (((uint)num3 & 0x400u) != 0 && (num3 & 0x1000) == 0 && (num3 & 0x3FF) + ((num3 & 0x7FE000) >> 13) <= 1021))
                {
                    num2 = Interlocked.CompareExchange(ref _state, num3 + 1, num3);
                    if (num2 == num3)
                    {
                        break;
                    }
                    continue;
                }
                if ((num3 & 0x3FF) == 1023 || (num3 & 0x7FE000) == 8380416 || (num3 & 0xC00) == 1024)
                {
                    int millisecondsTimeout2 = 100;
                    if ((num3 & 0x3FF) == 1023 || (num3 & 0x7FE000) == 8380416)
                    {
                        millisecondsTimeout2 = 1000;
                    }
                    Thread.Sleep(millisecondsTimeout2);
                    num = 0;
                    num2 = _state;
                    continue;
                }
                num++;
                if ((num3 & 0xC00) == 3072)
                {
                    if (num > DefaultSpinCount)
                    {
                        Thread.Sleep(1);
                        num = 0;
                    }
                    num2 = _state;
                    continue;
                }
                if (num <= DefaultSpinCount)
                {
                    num2 = _state;
                    continue;
                }
                num2 = Interlocked.CompareExchange(ref _state, num3 + 8192, num3);
                if (num2 != num3)
                {
                    continue;
                }
                int num4 = -8192;
                ManualResetEventSlim manualResetEventSlim = null;
                bool flag = false;
                try
                {
                    manualResetEventSlim = GetOrCreateReaderEvent();
                    flag = manualResetEventSlim.Wait(millisecondsTimeout);
                    if (flag)
                    {
                        num4++;
                    }
                }
                finally
                {
                    num3 = Interlocked.Add(ref _state, num4) - num4;
                    if (!flag && ((uint)num3 & 0x400u) != 0 && (num3 & 0x7FE000) == 8192)
                    {
                        if (manualResetEventSlim == null)
{
                            manualResetEventSlim = _readerEvent;
                        }
                        manualResetEventSlim.Wait();
                        manualResetEventSlim.Reset();
                        Interlocked.Add(ref _state, -1023);
                        orCreateCurrent._readerLevel++;
                        ReleaseReaderLock();
                    }
                }
                if (!flag)
                {
                    throw GetTimeoutException();
                }
                if ((num3 & 0x7FE000) == 8192)
                {
                    manualResetEventSlim.Reset();
                    Interlocked.Add(ref _state, -1024);
                }
                break;
            }
            while (YieldProcessor());
        }
        orCreateCurrent._readerLevel++;
    }
References System.Threading.ReaderWriterLock._lockID, System.Threading.ReaderWriterLock._readerEvent, System.Threading.ReaderWriterLock._state, System.Threading.ReaderWriterLock._writerID, System.Threading.ReaderWriterLock.AcquireWriterLock(), System.Threading.Interlocked.Add(), System.Threading.Interlocked.CompareExchange(), System.Threading.ReaderWriterLock.DefaultSpinCount, System.Runtime.Serialization.Dictionary, System.Threading.ReaderWriterLock.GetCurrentThreadID(), System.Threading.ReaderWriterLock.GetInvalidTimeoutException(), System.Threading.ReaderWriterLock.ThreadLocalLockEntry.GetOrCreateCurrent(), System.Threading.ReaderWriterLock.GetOrCreateReaderEvent(), System.Threading.ReaderWriterLock.GetTimeoutException(), System.millisecondsTimeout, System.SR.Overflow_UInt16, System.Threading.ReaderWriterLock.ReleaseReaderLock(), System.Threading.Thread.Sleep(), System.Threading.ManualResetEventSlim.Wait(), and System.Threading.ReaderWriterLock.YieldProcessor().
Referenced by System.Threading.ReaderWriterLock.AcquireReaderLock(), and System.Threading.ReaderWriterLock.RecoverLock().