Terraria: System.Threading.ReaderWriterLock.GetInvalidTimeoutException
GetInvalidTimeoutException()
static ArgumentOutOfRangeException System.Threading.ReaderWriterLock.GetInvalidTimeoutException (string parameterName) inline static private
Definition at line 859 of file ReaderWriterLock.cs.
    {
        return new ArgumentOutOfRangeException(parameterName, System.SR.ArgumentOutOfRange_TimeoutMilliseconds);
    }
References System.SR.ArgumentOutOfRange_TimeoutMilliseconds, and System.Runtime.Serialization.Dictionary.
Referenced by System.Threading.ReaderWriterLock.AcquireReaderLock(), System.Threading.ReaderWriterLock.AcquireWriterLock(), System.Threading.ReaderWriterLock.ToTimeoutMilliseconds(), and System.Threading.ReaderWriterLock.UpgradeToWriterLock().