Terraria: System.Threading.ReaderWriterLock.ReleaseReaderLock
ReleaseReaderLock()
void System.Threading.ReaderWriterLock.ReleaseReaderLock () inline
Definition at line 417 of file ReaderWriterLock.cs.
    {
        if (_writerID == GetCurrentThreadID())
        {
            ReleaseWriterLock();
            return;
        }
        ThreadLocalLockEntry current = ThreadLocalLockEntry.GetCurrent(_lockID);
        if (current == null)
        {
            throw GetNotOwnerException();
        }
        current._readerLevel--;
        if (current._readerLevel > 0)
        {
            return;
        }
        AutoResetEvent autoResetEvent = null;
        ManualResetEventSlim manualResetEventSlim = null;
        int num = _state;
        bool flag;
        bool flag2;
        int num2;
        do
        {
            flag = false;
            flag2 = false;
            num2 = num;
            int num3 = -1;
            if ((num2 & 0x7FF) == 1)
            {
                flag = true;
                if (((uint)num2 & 0xFF800000u) != 0)
                {
                    autoResetEvent = TryGetOrCreateWriterEvent();
                    if (autoResetEvent == null)
                    {
                        Thread.Sleep(100);
                        num = _state;
                        num2 = 0;
                        continue;
                    }
                    num3 += 2048;
                }
                else if (((uint)num2 & 0x7FE000u) != 0)
                {
                    manualResetEventSlim = TryGetOrCreateReaderEvent();
                    if (manualResetEventSlim == null)
                    {
                        Thread.Sleep(100);
                        num = _state;
                        num2 = 0;
                        continue;
                    }
                    num3 += 1024;
                }
                else if (num2 == 1 && (_readerEvent != null || _writerEvent != null))
                {
                    flag2 = true;
                    num3 += 3072;
                }
            }
            num = Interlocked.CompareExchange(ref _state, num2 + num3, num2);
        }
        while (num != num2);
        if (flag)
        {
            if (((uint)num2 & 0xFF800000u) != 0)
            {
                autoResetEvent.Set();
            }
            else if (((uint)num2 & 0x7FE000u) != 0)
            {
                manualResetEventSlim.Set();
            }
            else if (flag2)
            {
                ReleaseEvents();
            }
        }
    }
References System.Threading.ReaderWriterLock._lockID, System.Threading.ReaderWriterLock._readerEvent, System.Threading.ReaderWriterLock.ThreadLocalLockEntry._readerLevel, System.Threading.ReaderWriterLock._state, System.Threading.ReaderWriterLock._writerEvent, System.Threading.ReaderWriterLock._writerID, System.Threading.Interlocked.CompareExchange(), System.Runtime.Serialization.Dictionary, System.Threading.ReaderWriterLock.ThreadLocalLockEntry.GetCurrent(), System.Threading.ReaderWriterLock.GetCurrentThreadID(), System.Threading.ReaderWriterLock.GetNotOwnerException(), System.Threading.ReaderWriterLock.ReleaseEvents(), System.Threading.ReaderWriterLock.ReleaseWriterLock(), System.Threading.Thread.Sleep(), System.Threading.ReaderWriterLock.TryGetOrCreateReaderEvent(), and System.Threading.ReaderWriterLock.TryGetOrCreateWriterEvent().
Referenced by System.Threading.ReaderWriterLock.AcquireReaderLock(), System.Threading.ReaderWriterLock.ReleaseLock(), and System.Threading.ReaderWriterLock.UpgradeToWriterLock().