Terraria: System.Threading.ReaderWriterLock.GetOrCreateWriterEvent
GetOrCreateWriterEvent()
AutoResetEvent System.Threading.ReaderWriterLock.GetOrCreateWriterEvent () inline private
Definition at line 807 of file ReaderWriterLock.cs.
    {
        AutoResetEvent writerEvent = _writerEvent;
        if (writerEvent != null)
        {
            return writerEvent;
        }
        writerEvent = new AutoResetEvent(initialState: false);
        AutoResetEvent autoResetEvent = Interlocked.CompareExchange(ref _writerEvent, writerEvent, null);
        if (autoResetEvent == null)
        {
            return writerEvent;
        }
        writerEvent.Dispose();
        return autoResetEvent;
    }
References System.Threading.ReaderWriterLock._writerEvent, System.Threading.Interlocked.CompareExchange(), and System.Runtime.Serialization.Dictionary.
Referenced by System.Threading.ReaderWriterLock.AcquireWriterLock(), and System.Threading.ReaderWriterLock.TryGetOrCreateWriterEvent().