Terraria: System.Threading.ReaderWriterLock.AcquireWriterLock
AcquireWriterLock() [1/2]
void System.Threading.ReaderWriterLock.AcquireWriterLock (int millisecondsTimeout) inline
Definition at line 298 of file ReaderWriterLock.cs.
    {
        if (millisecondsTimeout < -1)
        {
            throw GetInvalidTimeoutException("millisecondsTimeout");
        }
        int currentThreadID = GetCurrentThreadID();
        if (Interlocked.CompareExchange(ref _state, 4096, 0) != 0)
        {
            if (_writerID == currentThreadID)
            {
                if (_writerLevel == ushort.MaxValue)
                {
                    throw new OverflowException(System.SR.Overflow_UInt16);
                }
                _writerLevel++;
                return;
            }
            int num = 0;
            int num2 = _state;
            do
            {
                int num3 = num2;
                if (num3 == 0 || num3 == 3072)
                {
                    num2 = Interlocked.CompareExchange(ref _state, num3 + 4096, num3);
                    if (num2 == num3)
                    {
                        break;
                    }
                    continue;
                }
                if ((num3 & -8388608) == -8388608)
                {
                    Thread.Sleep(1000);
                    num = 0;
                    num2 = _state;
                    continue;
                }
                num++;
                if ((num3 & 0xC00) == 3072)
                {
                    if (num > DefaultSpinCount)
                    {
                        Thread.Sleep(1);
                        num = 0;
                    }
                    num2 = _state;
                    continue;
                }
                if (num <= DefaultSpinCount)
                {
                    num2 = _state;
                    continue;
                }
                num2 = Interlocked.CompareExchange(ref _state, num3 + 8388608, num3);
                if (num2 != num3)
                {
                    continue;
                }
                int num4 = -8388608;
                AutoResetEvent autoResetEvent = null;
                bool flag = false;
                try
                {
                    autoResetEvent = GetOrCreateWriterEvent();
                    flag = autoResetEvent.WaitOne(millisecondsTimeout);
                    if (flag)
                    {
                        num4 += 2048;
                    }
                }
                finally
                {
                    num3 = Interlocked.Add(ref _state, num4) - num4;
                    if (!flag && ((uint)num3 & 0x800u) != 0 && (num3 & -8388608) == 8388608)
                    {
                        if (autoResetEvent == null)
{
                            autoResetEvent = _writerEvent;
                        }
                        while (true)
{
                            num3 = _state;
                            if (((uint)num3 & 0x800u) != 0 && (num3 & -8388608) == 0)
{
                                if (autoResetEvent.WaitOne(10))
{
                                    num4 = 2048;
                                    num3 = Interlocked.Add(ref _state, num4) - num4;
                                    _writerID = currentThreadID;
                                    _writerLevel = 1;
                                    ReleaseWriterLock();
                                    break;
                                }
                                continue;
                            }
                            break;
                        }
                    }
                }
                if (flag)
                {
                    break;
                }
                throw GetTimeoutException();
            }
            while (YieldProcessor());
        }
        _writerID = currentThreadID;
        _writerLevel = 1;
        _writerSeqNum++;
    }
References System.Threading.ReaderWriterLock._state, System.Threading.ReaderWriterLock._writerEvent, System.Threading.ReaderWriterLock._writerID, System.Threading.ReaderWriterLock._writerLevel, System.Threading.ReaderWriterLock._writerSeqNum, System.Threading.Interlocked.Add(), System.Threading.Interlocked.CompareExchange(), System.Threading.ReaderWriterLock.DefaultSpinCount, System.Runtime.Serialization.Dictionary, System.Threading.ReaderWriterLock.GetCurrentThreadID(), System.Threading.ReaderWriterLock.GetInvalidTimeoutException(), System.Threading.ReaderWriterLock.GetOrCreateWriterEvent(), System.Threading.ReaderWriterLock.GetTimeoutException(), System.millisecondsTimeout, System.SR.Overflow_UInt16, System.Threading.ReaderWriterLock.ReleaseWriterLock(), System.Threading.Thread.Sleep(), and System.Threading.ReaderWriterLock.YieldProcessor().
Referenced by System.Threading.ReaderWriterLock.AcquireReaderLock(), System.Threading.ReaderWriterLock.AcquireWriterLock(), System.Threading.ReaderWriterLock.RecoverLock(), and System.Threading.ReaderWriterLock.UpgradeToWriterLock().