Terraria: System.Threading.ReaderWriterLock.RecoverLock
RecoverLock()
void System.Threading.ReaderWriterLock.RecoverLock (ref LockCookie lockCookie, LockCookieFlags flags) inline private
Definition at line 764 of file ReaderWriterLock.cs.
    {
        if ((flags & LockCookieFlags.OwnedWriter) != 0)
        {
            AcquireWriterLock(-1);
            _writerLevel = lockCookie._writerLevel;
        }
        else if ((flags & LockCookieFlags.OwnedReader) != 0)
        {
            AcquireReaderLock(-1);
            ThreadLocalLockEntry current = ThreadLocalLockEntry.GetCurrent(_lockID);
            current._readerLevel = lockCookie._readerLevel;
        }
    }
References System.Threading.ReaderWriterLock._lockID, System.Threading.ReaderWriterLock._writerLevel, System.Threading.ReaderWriterLock.AcquireReaderLock(), System.Threading.ReaderWriterLock.AcquireWriterLock(), System.Runtime.Serialization.Dictionary, and System.Threading.ReaderWriterLock.ThreadLocalLockEntry.GetCurrent().
Referenced by System.Threading.ReaderWriterLock.RestoreLock(), and System.Threading.ReaderWriterLock.UpgradeToWriterLock().