Terraria: System.Threading.ReaderWriterLock.ReleaseLock
ReleaseLock()
LockCookie System.Threading.ReaderWriterLock.ReleaseLock () inline
Definition at line 692 of file ReaderWriterLock.cs.
    {
        LockCookie result = default(LockCookie);
        int num = (result._threadID = GetCurrentThreadID());
        if (_writerID == num)
        {
            result._flags = LockCookieFlags.Release | LockCookieFlags.OwnedWriter;
            result._writerLevel = _writerLevel;
            _writerLevel = 1;
            ReleaseWriterLock();
            return result;
        }
        ThreadLocalLockEntry current = ThreadLocalLockEntry.GetCurrent(_lockID);
        if (current == null)
        {
            result._flags = LockCookieFlags.Release | LockCookieFlags.OwnedNone;
            return result;
        }
        result._flags = LockCookieFlags.Release | LockCookieFlags.OwnedReader;
        result._readerLevel = current._readerLevel;
        current._readerLevel = 1;
        ReleaseReaderLock();
        return result;
    }
References System.Threading.ReaderWriterLock._lockID, System.Threading.ReaderWriterLock.ThreadLocalLockEntry._readerLevel, System.Threading.ReaderWriterLock._writerID, System.Threading.ReaderWriterLock._writerLevel, System.Runtime.Serialization.Dictionary, System.Threading.ReaderWriterLock.ThreadLocalLockEntry.GetCurrent(), System.Threading.ReaderWriterLock.GetCurrentThreadID(), System.Threading.ReaderWriterLock.ReleaseReaderLock(), and System.Threading.ReaderWriterLock.ReleaseWriterLock().