Terraria: Terraria.UI.GameInterfaceLayer.Draw
Draw()
bool Terraria.UI.GameInterfaceLayer.Draw () inline inherited
Definition at line 20 of file GameInterfaceLayer.cs.
    {
        Matrix transformMatrix;
        if (ScaleType == InterfaceScaleType.Game)
        {
            PlayerInput.SetZoom_World();
            transformMatrix = Main.GameViewMatrix.ZoomMatrix;
        }
        else if (ScaleType == InterfaceScaleType.UI)
        {
            PlayerInput.SetZoom_UI();
            transformMatrix = Main.UIScaleMatrix;
        }
        else
        {
            PlayerInput.SetZoom_Unscaled();
            transformMatrix = Matrix.Identity;
        }
        bool result = false;
        Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, transformMatrix);
        try
        {
            result = DrawSelf();
        }
        catch (Exception e)
        {
            TimeLogger.DrawException(e);
        }
        Main.spriteBatch.End();
        return result;
    }
References Terraria.TimeLogger.DrawException(), Terraria.UI.GameInterfaceLayer.DrawSelf(), Terraria.Main.GameViewMatrix, Microsoft.Xna.Framework.Matrix.Identity, Terraria.UI.GameInterfaceLayer.ScaleType, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_Unscaled(), Terraria.GameInput.PlayerInput.SetZoom_World(), Terraria.Main.spriteBatch, and Terraria.Main.UIScaleMatrix.