Terraria: System.Xml.XmlNameEx.XmlNameEx
XmlNameEx()
System.Xml.XmlNameEx.XmlNameEx (string prefix, string localName, string ns, int hashCode, XmlDocument ownerDoc, XmlName next, IXmlSchemaInfo schemaInfo) inline package
Definition at line 39 of file XmlNameEx.cs.
        : base(prefix, localName, ns, hashCode, ownerDoc, next)
    {
        SetValidity(schemaInfo.Validity);
        SetIsDefault(schemaInfo.IsDefault);
        SetIsNil(schemaInfo.IsNil);
        _memberType = schemaInfo.MemberType;
        _schemaType = schemaInfo.SchemaType;
        _decl = ((schemaInfo.SchemaElement != null) ? ((XmlSchemaAnnotated)schemaInfo.SchemaElement) : ((XmlSchemaAnnotated)schemaInfo.SchemaAttribute));
    }
References System.Xml.XmlNameEx._decl, System.Xml.XmlNameEx._memberType, System.Xml.XmlNameEx._schemaType, System.Xml.Dictionary, System.Xml.Schema.IXmlSchemaInfo.IsDefault, System.Xml.Schema.IXmlSchemaInfo.IsNil, System.Xml.Schema.IXmlSchemaInfo.MemberType, System.Xml.Schema.IXmlSchemaInfo.SchemaAttribute, System.Xml.Schema.IXmlSchemaInfo.SchemaElement, System.Xml.Schema.IXmlSchemaInfo.SchemaType, System.Xml.XmlNameEx.SetIsDefault(), System.Xml.XmlNameEx.SetIsNil(), System.Xml.XmlNameEx.SetValidity(), and System.Xml.Schema.IXmlSchemaInfo.Validity.