Terraria: PlayerInteractionAnchor.IsInValidUseTileEntity
IsInValidUseTileEntity()
bool PlayerInteractionAnchor.IsInValidUseTileEntity () inline
     {
         if (InUse)
         {
             return TileEntity.ByID.ContainsKey(interactEntityID);
         }
         return false;
     }
References TileEntity.ByID, interactEntityID, and InUse.
Referenced by GetTileEntity(), ItemSlot.OverrideHover(), and ItemSlot.OverrideLeftClick().