Terraria: CreativePowers.ModifyTimeRate.UpdateSliderAndShowMultiplierMouseOver
UpdateSliderAndShowMultiplierMouseOver()
void CreativePowers.ModifyTimeRate.UpdateSliderAndShowMultiplierMouseOver (UIElement affectedElement) inline private
         {
             if (affectedElement.IsMouseHovering)
             {
                 string originalText = "x" + TargetTimeRate;
                 CreativePowersHelper.AddPermissionTextIfNeeded(this, ref originalText);
                 Main.instance.MouseTextNoOverride(originalText, 0, 0);
             }
         }
References CreativePowersHelper.AddPermissionTextIfNeeded(), Main.instance, UIElement.IsMouseHovering, Main.MouseTextNoOverride(), and CreativePowers.ModifyTimeRate.TargetTimeRate.
Referenced by CreativePowers.ModifyTimeRate.ProvideSlider().