Terraria: TETrainingDummy.Update
Update()
override void TETrainingDummy.Update () inline virtual
Reimplemented from TileEntity.
     {
         Rectangle value = new Rectangle(0, 0, 32, 48);
         value.Inflate(1600, 1600);
         int x = value.X;
         int y = value.Y;
         if (npc != -1)
         {
             if (!Main.npc[npc].active || Main.npc[npc].type != 488 || Main.npc[npc].ai[0] != (float)Position.X || Main.npc[npc].ai[1] != (float)Position.Y)
             {
                 Deactivate();
             }
             return;
         }
         FillPlayerHitboxes();
         value.X = Position.X * 16 + x;
         value.Y = Position.Y * 16 + y;
         bool flag = false;
         foreach (KeyValuePair<int, Rectangle> item in playerBox)
         {
             if (item.Value.Intersects(value))
             {
                 flag = true;
                 break;
             }
         }
         if (flag)
         {
             Activate();
         }
     }
References Activate(), Entity.active, NPC.ai, Deactivate(), FillPlayerHitboxes(), npc, Main.npc, playerBox, TileEntity.Position, NPC.type, Point16.X, and Point16.Y.