Terraria: TETrainingDummy.Activate
Activate()
void TETrainingDummy.Activate () inline
     {
         int num = NPC.NewNPC(new EntitySource_TileEntity(this), Position.X * 16 + 16, Position.Y * 16 + 48, 488, 100);
         Main.npc[num].ai[0] = Position.X;
         Main.npc[num].ai[1] = Position.Y;
         Main.npc[num].netUpdate = true;
         npc = num;
         if (Main.netMode != 1)
         {
             NetMessage.SendData(86, -1, -1, null, ID, Position.X, Position.Y);
         }
     }
References NPC.ai, TileEntity.ID, Main.netMode, NPC.netUpdate, NPC.NewNPC(), npc, Main.npc, TileEntity.Position, NetMessage.SendData(), Point16.X, and Point16.Y.
Referenced by Update().