Terraria: PlayerSleepingHelper.SetIsSleepingAndAdjustPlayerRotation
SetIsSleepingAndAdjustPlayerRotation()
void PlayerSleepingHelper.SetIsSleepingAndAdjustPlayerRotation (Player player, bool state) inline
     {
         if (isSleeping != state)
         {
             isSleeping = state;
             if (state)
             {
                 player.fullRotation = (float)Math.PI / 2f * (float)(-player.direction);
                 return;
             }
             player.fullRotation = 0f;
             visualOffsetOfBedBase = default(Vector2);
         }
     }
References Entity.direction, Player.fullRotation, isSleeping, and visualOffsetOfBedBase.
Referenced by MessageBuffer.GetData(), StartSleeping(), and StopSleeping().