Terraria: PlayerSleepingHelper.StartSleeping
StartSleeping()
void PlayerSleepingHelper.StartSleeping (Player player, int x, int y) inline
     {
         GetSleepingTargetInfo(x, y, out var targetDirection, out var anchorPosition, out var visualoffset);
         Vector2 offset = anchorPosition - player.Bottom;
         bool flag = player.CanSnapToPosition(offset);
         if (flag)
         {
             flag &= Main.sleepingManager.GetNextPlayerStackIndexInCoords((anchorPosition + new Vector2(0f, -2f)).ToTileCoordinates()) < 2;
         }
         if (!flag)
         {
             return;
         }
         if (isSleeping && player.Bottom == anchorPosition)
         {
             StopSleeping(player);
             return;
         }
         player.StopVanityActions();
         player.RemoveAllGrapplingHooks();
         player.RemoveAllFishingBobbers();
         if (player.mount.Active)
         {
             player.mount.Dismount(player);
         }
         player.Bottom = anchorPosition;
         player.ChangeDir(targetDirection);
         Main.sleepingManager.AddPlayerAndGetItsStackedIndexInCoords(player.whoAmI, new Point(x, y), out sleepingIndex);
         player.velocity = Vector2.Zero;
         player.gravDir = 1f;
         SetIsSleepingAndAdjustPlayerRotation(player, state: true);
         visualOffsetOfBedBase = visualoffset;
         if (Main.myPlayer == player.whoAmI)
         {
             NetMessage.SendData(13, -1, -1, null, player.whoAmI);
         }
     }
References Mount.Active, AnchoredEntitiesCollection.AddPlayerAndGetItsStackedIndexInCoords(), Entity.Bottom, Player.CanSnapToPosition(), Player.ChangeDir(), Mount.Dismount(), AnchoredEntitiesCollection.GetNextPlayerStackIndexInCoords(), GetSleepingTargetInfo(), Player.gravDir, isSleeping, Player.mount, Main.myPlayer, Player.RemoveAllFishingBobbers(), Player.RemoveAllGrapplingHooks(), NetMessage.SendData(), SetIsSleepingAndAdjustPlayerRotation(), sleepingIndex, Main.sleepingManager, StopSleeping(), Player.StopVanityActions(), Entity.velocity, visualOffsetOfBedBase, and Entity.whoAmI.