Terraria: PlayerSleepingHelper.GetSleepingTargetInfo
GetSleepingTargetInfo()
static bool PlayerSleepingHelper.GetSleepingTargetInfo (int x, int y, out int targetDirection, out Vector2 anchorPosition, out Vector2 visualoffset) inline static
     {
         Tile tileSafely = Framing.GetTileSafely(x, y);
         if (!TileID.Sets.CanBeSleptIn[tileSafely.type] || !tileSafely.active())
         {
             targetDirection = 1;
             anchorPosition = default(Vector2);
             visualoffset = default(Vector2);
             return false;
         }
         int num = y;
         int num2 = x - tileSafely.frameX % 72 / 18;
         if (tileSafely.frameY % 36 != 0)
         {
             num--;
         }
         targetDirection = 1;
         int num3 = tileSafely.frameX / 72;
         int num4 = num2;
         switch (num3)
         {
         case 0:
             targetDirection = -1;
             num4++;
             break;
         case 1:
             num4 += 2;
             break;
         }
         anchorPosition = new Point(num4, num + 1).ToWorldCoordinates(8f, 16f);
         visualoffset = SetOffsetbyBed(tileSafely.frameY / 36);
         return true;
     }
References Tile.active(), TileID.Sets.CanBeSleptIn, Tile.frameX, Tile.frameY, Framing.GetTileSafely(), SetOffsetbyBed(), and Tile.type.
Referenced by StartSleeping(), and UpdateState().