Terraria: System.Text.RegularExpressions.RegexPrefixAnalyzer.CalculateFC
CalculateFC()
void System.Text.RegularExpressions.RegexPrefixAnalyzer.CalculateFC (int NodeType, RegexNode node, int CurIndex) inline private
Definition at line 373 of file RegexPrefixAnalyzer.cs.
    {
        bool caseInsensitive = (node.Options & RegexOptions.IgnoreCase) != 0;
        bool flag = (node.Options & RegexOptions.RightToLeft) != 0;
        switch (NodeType)
        {
        case 98:
            if (CurIndex == 0)
            {
                SkipChild();
            }
            break;
        case 23:
            PushFC(new RegexFC(nullable: true));
            break;
        case 153:
            if (CurIndex != 0)
            {
                RegexFC fc3 = PopFC();
                RegexFC regexFC3 = TopFC();
                _failed = !regexFC3.AddFC(fc3, concatenate: true);
            }
            if (!TopFC()._nullable)
            {
                _skipAllChildren = true;
            }
            break;
        case 162:
            if (CurIndex > 1)
            {
                RegexFC fc2 = PopFC();
                RegexFC regexFC2 = TopFC();
                _failed = !regexFC2.AddFC(fc2, concatenate: false);
            }
            break;
        case 152:
        case 161:
            if (CurIndex != 0)
            {
                RegexFC fc = PopFC();
                RegexFC regexFC = TopFC();
                _failed = !regexFC.AddFC(fc, concatenate: false);
            }
            break;
        case 154:
        case 155:
            if (node.M == 0)
            {
                TopFC()._nullable = true;
            }
            break;
        case 94:
        case 95:
            SkipChild();
            PushFC(new RegexFC(nullable: true));
            break;
        case 9:
        case 10:
            PushFC(new RegexFC(node.Ch, NodeType == 10, nullable: false, caseInsensitive));
            break;
        case 3:
        case 6:
        case 43:
            PushFC(new RegexFC(node.Ch, not: false, node.M == 0, caseInsensitive));
            break;
        case 4:
        case 7:
        case 44:
            PushFC(new RegexFC(node.Ch, not: true, node.M == 0, caseInsensitive));
            break;
        case 12:
            if (node.Str.Length == 0)
            {
                PushFC(new RegexFC(nullable: true));
            }
            else if (!flag)
            {
                PushFC(new RegexFC(node.Str[0], not: false, nullable: false, caseInsensitive));
            }
            else
            {
                PushFC(new RegexFC(node.Str[node.Str.Length - 1], not: false, nullable: false, caseInsensitive));
            }
            break;
        case 11:
            PushFC(new RegexFC(node.Str, nullable: false, caseInsensitive));
            break;
        case 5:
        case 8:
        case 45:
            PushFC(new RegexFC(node.Str, node.M == 0, caseInsensitive));
            break;
        case 13:
            PushFC(new RegexFC("\0\u0001\0\0", nullable: true, caseInsensitive: false));
            break;
        case 14:
        case 15:
        case 16:
        case 17:
        case 18:
        case 19:
        case 20:
        case 21:
        case 22:
        case 41:
        case 42:
        case 46:
            PushFC(new RegexFC(nullable: true));
            break;
        default:
            throw new ArgumentException(System.SR.Format(System.SR.UnexpectedOpcode, NodeType.ToString(CultureInfo.CurrentCulture)));
        case 88:
        case 89:
        case 90:
        case 91:
        case 92:
        case 93:
        case 96:
        case 97:
        case 156:
        case 157:
        case 158:
        case 159:
        case 160:
            break;
        }
    }
References System.Text.RegularExpressions.RegexPrefixAnalyzer._failed, System.Text.RegularExpressions.RegexFC._nullable, System.Text.RegularExpressions.RegexPrefixAnalyzer._skipAllChildren, System.Globalization.CultureInfo.CurrentCulture, System.SR.Format(), System.Text.RegularExpressions.RegexPrefixAnalyzer.PopFC(), System.Text.RegularExpressions.RegexPrefixAnalyzer.PushFC(), System.Text.RegularExpressions.RegexPrefixAnalyzer.SkipChild(), System.Text.RegularExpressions.RegexPrefixAnalyzer.TopFC(), and System.SR.UnexpectedOpcode.
Referenced by System.Text.RegularExpressions.RegexPrefixAnalyzer.RegexFCFromRegexTree().