Terraria: System.Text.RegularExpressions.RegexPrefixAnalyzer.RegexFCFromRegexTree
RegexFCFromRegexTree()
RegexFC System.Text.RegularExpressions.RegexPrefixAnalyzer.RegexFCFromRegexTree (RegexTree tree) inline private
Definition at line 320 of file RegexPrefixAnalyzer.cs.
    {
        RegexNode regexNode = tree.Root;
        int num = 0;
        while (true)
        {
            int num2 = regexNode.ChildCount();
            if (num2 == 0)
            {
                CalculateFC(regexNode.Type, regexNode, 0);
            }
            else if (num < num2 && !_skipAllChildren)
            {
                CalculateFC(regexNode.Type | 0x40, regexNode, num);
                if (!_skipchild)
                {
                    regexNode = regexNode.Child(num);
                    PushInt(num);
                    num = 0;
                }
                else
                {
                    num++;
                    _skipchild = false;
                }
                continue;
            }
            _skipAllChildren = false;
            if (IntIsEmpty())
            {
                break;
            }
            num = PopInt();
            regexNode = regexNode.Next;
            CalculateFC(regexNode.Type | 0x80, regexNode, num);
            if (_failed)
            {
                return null;
            }
            num++;
        }
        if (FCIsEmpty())
        {
            return null;
        }
        return PopFC();
    }
References System.Text.RegularExpressions.RegexPrefixAnalyzer._failed, System.Text.RegularExpressions.RegexPrefixAnalyzer._skipAllChildren, System.Text.RegularExpressions.RegexPrefixAnalyzer._skipchild, System.Text.RegularExpressions.RegexPrefixAnalyzer.CalculateFC(), System.Text.RegularExpressions.RegexPrefixAnalyzer.FCIsEmpty(), System.Text.RegularExpressions.RegexPrefixAnalyzer.IntIsEmpty(), System.Text.RegularExpressions.RegexPrefixAnalyzer.PopFC(), System.Text.RegularExpressions.RegexPrefixAnalyzer.PopInt(), and System.Text.RegularExpressions.RegexPrefixAnalyzer.PushInt().