Terraria: System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize
Serialize() [2/2]
static WriteObjectInfo System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize (object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder) inline static package
Definition at line 67 of file WriteObjectInfo.cs.
    {
        WriteObjectInfo objectInfo = GetObjectInfo(serObjectInfoInit);
        objectInfo.InitSerialize(obj, surrogateSelector, context, serObjectInfoInit, converter, objectWriter, binder);
        return objectInfo;
    }
References System.converter, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.GetObjectInfo(), and System.obj.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember().