Terraria: System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize
InitSerialize() [1/2]
void System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, SerializationBinder binder) inline package
Definition at line 123 of file WriteObjectInfo.cs.
    {
        _objectType = objectType;
        _context = context;
        _serObjectInfoInit = serObjectInfoInit;
        if (objectType.IsArray)
        {
            InitNoMembers();
            return;
        }
        InvokeSerializationBinder(binder);
        if (surrogateSelector != null)
        {
            _serializationSurrogate = surrogateSelector.GetSurrogate(objectType, context, out ISurrogateSelector _);
        }
        if (_serializationSurrogate != null)
        {
            _si = new SerializationInfo(objectType, converter);
            _cache = new SerObjectInfoCache(objectType);
            _isSi = true;
        }
        else if ((object)objectType != Converter.s_typeofObject && Converter.s_typeofISerializable.IsAssignableFrom(objectType))
        {
            _si = new SerializationInfo(objectType, converter);
            _cache = new SerObjectInfoCache(objectType);
            CheckTypeForwardedFrom(_cache, objectType, _binderAssemblyString);
            _isSi = true;
        }
        if (!_isSi)
        {
            InitMemberInfo();
            CheckTypeForwardedFrom(_cache, objectType, _binderAssemblyString);
        }
    }
References System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo._binderAssemblyString, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo._cache, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo._context, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo._isSi, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo._objectType, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo._serializationSurrogate, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo._serObjectInfoInit, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo._si, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.CheckTypeForwardedFrom(), System.converter, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitNoMembers(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InvokeSerializationBinder(), System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofISerializable, and System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofObject.