Terraria: ItemDropResolver.ResolveRule
ResolveRule()
ItemDropAttemptResult ItemDropResolver.ResolveRule (IItemDropRule rule, DropAttemptInfo info) inline private
     {
         if (!rule.CanDrop(info))
         {
             ItemDropAttemptResult itemDropAttemptResult = default(ItemDropAttemptResult);
             itemDropAttemptResult.State = ItemDropAttemptResultState.DoesntFillConditions;
             ItemDropAttemptResult itemDropAttemptResult2 = itemDropAttemptResult;
             ResolveRuleChains(rule, info, itemDropAttemptResult2);
             return itemDropAttemptResult2;
         }
         ItemDropAttemptResult itemDropAttemptResult3 = ((!(rule is INestedItemDropRule nestedItemDropRule)) ? rule.TryDroppingItem(info) : nestedItemDropRule.TryDroppingItem(info, ResolveRule));
         ResolveRuleChains(rule, info, itemDropAttemptResult3);
         return itemDropAttemptResult3;
     }
References IItemDropRule.CanDrop(), ResolveRuleChains(), ItemDropAttemptResult.State, and IItemDropRule.TryDroppingItem().
Referenced by ResolveRuleChains(), and TryDropping().