Terraria: System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServerWithHandle
CheckConnectOperationsServerWithHandle()
void System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServerWithHandle () inline private
Definition at line 422 of file NamedPipeServerStream.cs.
    {
        if (base.InternalHandle == null)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_PipeHandleNotSet);
        }
        CheckConnectOperationsServer();
    }
References System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServer(), and System.SR.InvalidOperation_PipeHandleNotSet.
Referenced by System.IO.Pipes.NamedPipeServerStream.WaitForConnection(), and System.IO.Pipes.NamedPipeServerStream.WaitForConnectionCoreAsync().