Terraria: System.IO.Pipes.NamedPipeServerStream.RunAsClient
RunAsClient()
void System.IO.Pipes.NamedPipeServerStream.RunAsClient (PipeStreamImpersonationWorker impersonationWorker) inline
Definition at line 334 of file NamedPipeServerStream.cs.
    {
        CheckWriteOperations();
        ExecuteHelper executeHelper = new ExecuteHelper(impersonationWorker, base.InternalHandle);
        bool exceptionThrown = true;
        try
        {
            ImpersonateAndTryCode(executeHelper);
            exceptionThrown = false;
        }
        finally
        {
            RevertImpersonationOnBackout(executeHelper, exceptionThrown);
        }
        if (executeHelper._impersonateErrorCode != 0)
        {
            throw WinIOError(executeHelper._impersonateErrorCode);
        }
        if (executeHelper._revertImpersonateErrorCode != 0)
        {
            throw WinIOError(executeHelper._revertImpersonateErrorCode);
        }
    }
References System.IO.Pipes.NamedPipeServerStream.ExecuteHelper._impersonateErrorCode, System.IO.Pipes.NamedPipeServerStream.ExecuteHelper._revertImpersonateErrorCode, System.IO.Pipes.PipeStream.CheckWriteOperations(), System.IO.Pipes.NamedPipeServerStream.ImpersonateAndTryCode(), System.IO.Pipes.NamedPipeServerStream.RevertImpersonationOnBackout(), and System.IO.Pipes.PipeStream.WinIOError().