Terraria: System.IO.Pipes.NamedPipeServerStream.HandleGetImpersonationUserNameError
HandleGetImpersonationUserNameError()
unsafe string System.IO.Pipes.NamedPipeServerStream.HandleGetImpersonationUserNameError (int error, uint userNameMaxLength, char * userName) inline private
Definition at line 431 of file NamedPipeServerStream.cs.
    {
        if ((error == 0 || error == 1368) && Environment.Is64BitProcess)
        {
            global::Interop.Kernel32.LoadLibraryEx("sspicli.dll", IntPtr.Zero, 2048);
            if (global::Interop.Kernel32.GetNamedPipeHandleStateW(base.InternalHandle, null, null, null, null, userName, userNameMaxLength))
            {
                return new string(userName);
            }
            error = Marshal.GetLastPInvokeError();
        }
        throw WinIOError(error);
    }
References System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.Environment.Is64BitProcess, System.IO.Pipes.PipeStream.WinIOError(), and System.IntPtr.Zero.
Referenced by System.IO.Pipes.NamedPipeServerStream.GetImpersonationUserName().