Terraria: System.IO.Pipes.NamedPipeServerStream.WaitForConnectionAsync
WaitForConnectionAsync() [2/2]
Task System.IO.Pipes.NamedPipeServerStream.WaitForConnectionAsync (CancellationToken cancellationToken) inline
Definition at line 297 of file NamedPipeServerStream.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled(cancellationToken);
        }
        if (!base.IsAsync)
        {
            return Task.Factory.StartNew(delegate(object s)
            {
                ((NamedPipeServerStream)s).WaitForConnection();
            }, this, cancellationToken, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
        }
        return WaitForConnectionCoreAsync(cancellationToken).AsTask();
    }
References System.IO.Pipes.NamedPipeServerStream.NamedPipeServerStream(), System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.cancellationToken, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.s, and System.IO.Pipes.NamedPipeServerStream.WaitForConnectionCoreAsync().