Terraria: System.IO.Pipes.NamedPipeServerStream.Create
Create() [2/2]
void System.IO.Pipes.NamedPipeServerStream.Create (string pipeName, PipeDirection direction, int maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, int inBufferSize, int outBufferSize, PipeSecurity pipeSecurity, HandleInheritability inheritability, PipeAccessRights additionalAccessRights) inline private
Definition at line 229 of file NamedPipeServerStream.cs.
    {
        string fullPath = Path.GetFullPath("\\\\.\\pipe\\" + pipeName);
        if (string.Equals(fullPath, "\\\\.\\pipe\\anonymous", StringComparison.OrdinalIgnoreCase))
        {
            throw new ArgumentOutOfRangeException("pipeName", System.SR.ArgumentOutOfRange_AnonymousReserved);
        }
        if (base.IsCurrentUserOnly)
        {
            using (WindowsIdentity windowsIdentity = WindowsIdentity.GetCurrent())
            {
                SecurityIdentifier owner = windowsIdentity.Owner;
                PipeAccessRule rule = new PipeAccessRule(owner, PipeAccessRights.FullControl, AccessControlType.Allow);
                pipeSecurity = new PipeSecurity();
                pipeSecurity.AddAccessRule(rule);
                pipeSecurity.SetOwner(owner);
            }
            options &= ~PipeOptions.CurrentUserOnly;
        }
        int openMode = (int)direction | ((maxNumberOfServerInstances == 1) ? 524288 : 0) | (int)options | (int)additionalAccessRights;
        int pipeMode = ((int)transmissionMode << 2) | ((int)transmissionMode << 1);
        if (maxNumberOfServerInstances == -1)
        {
            maxNumberOfServerInstances = 255;
        }
        GCHandle pinningHandle = default(GCHandle);
        try
        {
            global::Interop.Kernel32.SECURITY_ATTRIBUTES securityAttributes = PipeStream.GetSecAttrs(inheritability, pipeSecurity, ref pinningHandle);
            SafePipeHandle safePipeHandle = global::Interop.Kernel32.CreateNamedPipe(fullPath, openMode, pipeMode, maxNumberOfServerInstances, outBufferSize, inBufferSize, 0, ref securityAttributes);
            if (safePipeHandle.IsInvalid)
            {
                throw System.IO.Win32Marshal.GetExceptionForLastWin32Error();
            }
            InitializeHandle(safePipeHandle, isExposed: false, (options & PipeOptions.Asynchronous) != 0);
        }
        finally
        {
            if (pinningHandle.IsAllocated)
            {
                pinningHandle.Free();
            }
        }
    }
References System.IO.Pipes.PipeSecurity.AddAccessRule(), System.SR.ArgumentOutOfRange_AnonymousReserved, System.Runtime.InteropServices.GCHandle.Free(), System.Security.Principal.WindowsIdentity.GetCurrent(), System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.IO.Path.GetFullPath(), System.IO.Pipes.PipeStream.GetSecAttrs(), System.IO.Pipes.PipeStream.InitializeHandle(), System.Runtime.InteropServices.GCHandle.IsAllocated, Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, System.options, System.Security.Principal.WindowsIdentity.Owner, and System.Security.AccessControl.ObjectSecurity< T >.SetOwner().