Terraria: System.IO.Pipes.NamedPipeServerStream.WaitForConnection
WaitForConnection()
void System.IO.Pipes.NamedPipeServerStream.WaitForConnection () inline
Definition at line 274 of file NamedPipeServerStream.cs.
    {
        CheckConnectOperationsServerWithHandle();
        if (base.IsAsync)
        {
            WaitForConnectionCoreAsync(CancellationToken.None).AsTask().GetAwaiter().GetResult();
            return;
        }
        if (!global::Interop.Kernel32.ConnectNamedPipe(base.InternalHandle, IntPtr.Zero))
        {
            int lastPInvokeError = Marshal.GetLastPInvokeError();
            if (lastPInvokeError != 535)
            {
                throw System.IO.Win32Marshal.GetExceptionForWin32Error(lastPInvokeError);
            }
            if (lastPInvokeError == 535 && base.State == PipeState.Connected)
            {
                throw new InvalidOperationException(System.SR.InvalidOperation_PipeAlreadyConnected);
            }
        }
        base.State = PipeState.Connected;
    }
References System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServerWithHandle(), System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.SR.InvalidOperation_PipeAlreadyConnected, System.Threading.CancellationToken.None, System.IO.Pipes.NamedPipeServerStream.WaitForConnectionCoreAsync(), and System.IntPtr.Zero.