Terraria: System.IO.Pipes.NamedPipeServerStream.WaitForConnectionCoreAsync
WaitForConnectionCoreAsync()
unsafe ValueTask System.IO.Pipes.NamedPipeServerStream.WaitForConnectionCoreAsync (CancellationToken cancellationToken) inline private
Definition at line 384 of file NamedPipeServerStream.cs.
    {
        CheckConnectOperationsServerWithHandle();
        ConnectionValueTaskSource connectionValueTaskSource = Interlocked.Exchange(ref _reusableConnectionValueTaskSource, null) ?? new ConnectionValueTaskSource(this);
        try
        {
            connectionValueTaskSource.PrepareForOperation();
            if (!global::Interop.Kernel32.ConnectNamedPipe(base.InternalHandle, connectionValueTaskSource._overlapped))
            {
                int lastPInvokeError = Marshal.GetLastPInvokeError();
                switch (lastPInvokeError)
                {
                case 997:
                    connectionValueTaskSource.RegisterForCancellation(cancellationToken);
                    break;
                case 535:
                    connectionValueTaskSource.Dispose();
                    if (base.State == PipeState.Connected)
                    {
                        return ValueTask.FromException(ExceptionDispatchInfo.SetCurrentStackTrace(new InvalidOperationException(System.SR.InvalidOperation_PipeAlreadyConnected)));
                    }
                    base.State = PipeState.Connected;
                    return ValueTask.CompletedTask;
                default:
                    connectionValueTaskSource.Dispose();
                    return ValueTask.FromException(ExceptionDispatchInfo.SetCurrentStackTrace(System.IO.Win32Marshal.GetExceptionForWin32Error(lastPInvokeError)));
                }
            }
        }
        catch
        {
            connectionValueTaskSource.Dispose();
            throw;
        }
        connectionValueTaskSource.FinishedScheduling();
        return new ValueTask(connectionValueTaskSource, connectionValueTaskSource.Version);
    }
References System.IO.Pipes.PipeStream.PipeValueTaskSource._overlapped, System.IO.Pipes.NamedPipeServerStream._reusableConnectionValueTaskSource, System.cancellationToken, System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServerWithHandle(), System.Threading.Tasks.ValueTask< TResult >.CompletedTask, System.IO.Pipes.PipeStream.PipeValueTaskSource.Dispose(), System.Threading.Interlocked.Exchange(), System.IO.Pipes.PipeStream.PipeValueTaskSource.FinishedScheduling(), System.Threading.Tasks.ValueTask< TResult >.FromException(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.SR.InvalidOperation_PipeAlreadyConnected, System.IO.Pipes.PipeStream.PipeValueTaskSource.PrepareForOperation(), System.IO.Pipes.PipeStream.PipeValueTaskSource.RegisterForCancellation(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), and System.IO.Pipes.PipeStream.PipeValueTaskSource.Version.
Referenced by System.IO.Pipes.NamedPipeServerStream.WaitForConnection(), and System.IO.Pipes.NamedPipeServerStream.WaitForConnectionAsync().