Terraria: Player.OverheadMessage.NewMessage
NewMessage()
void Player.OverheadMessage.NewMessage (string message, int displayTime) inline
         {
             chatText = message;
             snippets = ChatManager.ParseMessage(chatText, Color.White).ToArray();
             messageSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, snippets, Vector2.One);
             timeLeft = displayTime;
         }
References Player.OverheadMessage.chatText, Color, ChatManager.GetStringSize(), Player.OverheadMessage.messageSize, FontAssets.MouseText, ChatManager.ParseMessage(), Player.OverheadMessage.snippets, Player.OverheadMessage.timeLeft, and Asset< T >.Value.
Referenced by ChatHelper.DisplayMessage().