Terraria: RgbKey.Update
Update()
void RgbKey.Update (float timeElapsed) inline package
     {
         switch (Effect)
         {
         case RgbKeyEffect.Solid:
             UpdateSolidEffect();
             break;
         case RgbKeyEffect.Fade:
             UpdateFadeEffect();
             break;
         case RgbKeyEffect.Flashing:
             UpdateFlashingEffect();
             break;
         }
         _timeRemaining = Math.Max(_timeRemaining - timeElapsed, 0f);
     }
References _timeRemaining, Effect, UpdateFadeEffect(), UpdateFlashingEffect(), and UpdateSolidEffect().
Referenced by HotkeyCollection.UpdateAll().