Terraria: Terraria.Lang.GetItemName
GetItemName()
static LocalizedText Terraria.Lang.GetItemName (int id) inline static
Definition at line 166 of file Lang.cs.
    {
        id = ItemID.FromNetId((short)id);
        if (id > 0 && id < ItemID.Count && _itemNameCache[id] != null)
        {
            return _itemNameCache[id];
        }
        return LocalizedText.Empty;
    }
References Terraria.Lang._itemNameCache, Terraria.ID.ItemID.Count, Terraria.Localization.LocalizedText.Empty, and Terraria.ID.ItemID.FromNetId().
Referenced by Terraria.Lang.CreateDeathMessage(), and Terraria.Lang.GetItemNameValue().