Terraria: Terraria.Lang.CatChat
CatChat()
static string Terraria.Lang.CatChat (NPC npc) inline static
Definition at line 327 of file Lang.cs.
    {
        object obj = CreateDialogSubstitutionObject(npc);
        return Language.SelectRandom(CreateDialogFilter("CatChatter.", obj)).FormatWith(obj);
    }
References Terraria.Lang.CreateDialogFilter(), Terraria.Lang.CreateDialogSubstitutionObject(), System.obj, and Terraria.Localization.Language.SelectRandom().
Referenced by Terraria.NPC.GetChat().