Terraria: Terraria.Lang.CreateDialogSubstitutionObject
CreateDialogSubstitutionObject()
static object Terraria.Lang.CreateDialogSubstitutionObject (NPC npc = null) inline static
    {
        return new
        {
            Nurse = NPC.GetFirstNPCNameOrNull(18),
            Merchant = NPC.GetFirstNPCNameOrNull(17),
            ArmsDealer = NPC.GetFirstNPCNameOrNull(19),
            Dryad = NPC.GetFirstNPCNameOrNull(20),
            Demolitionist = NPC.GetFirstNPCNameOrNull(38),
            Clothier = NPC.GetFirstNPCNameOrNull(54),
            Guide = NPC.GetFirstNPCNameOrNull(22),
            Wizard = NPC.GetFirstNPCNameOrNull(108),
            GoblinTinkerer = NPC.GetFirstNPCNameOrNull(107),
            Mechanic = NPC.GetFirstNPCNameOrNull(124),
            Truffle = NPC.GetFirstNPCNameOrNull(160),
            Steampunker = NPC.GetFirstNPCNameOrNull(178),
            DyeTrader = NPC.GetFirstNPCNameOrNull(207),
            PartyGirl = NPC.GetFirstNPCNameOrNull(208),
            Cyborg = NPC.GetFirstNPCNameOrNull(209),
            Painter = NPC.GetFirstNPCNameOrNull(227),
            WitchDoctor = NPC.GetFirstNPCNameOrNull(228),
            Pirate = NPC.GetFirstNPCNameOrNull(229),
            Stylist = NPC.GetFirstNPCNameOrNull(353),
            TravelingMerchant = NPC.GetFirstNPCNameOrNull(368),
            Angler = NPC.GetFirstNPCNameOrNull(369),
            Bartender = NPC.GetFirstNPCNameOrNull(550),
            WorldName = Main.worldName,
            Day = Main.dayTime,
            BloodMoon = Main.bloodMoon,
            Eclipse = Main.eclipse,
            MoonLordDefeated = NPC.downedMoonlord,
            GolemDefeated = NPC.downedGolemBoss,
            DukeFishronDefeated = NPC.downedFishron,
            FrostLegionDefeated = NPC.downedFrost,
            MartiansDefeated = NPC.downedMartians,
            PumpkingDefeated = NPC.downedHalloweenKing,
            IceQueenDefeated = NPC.downedChristmasIceQueen,
            HardMode = Main.hardMode,
            Homeless = (npc?.homeless ?? false),
            InventoryKey = Main.cInv,
            PlayerName = Main.player[Main.myPlayer].name,
            GolfGuy = NPC.GetFirstNPCNameOrNull(588),
            TaxCollector = NPC.GetFirstNPCNameOrNull(441),
            Rain = Main.raining,
            Graveyard = Main.LocalPlayer.ZoneGraveyard,
            AnglerCompletedQuestsCount = Main.LocalPlayer.anglerQuestsFinished,
            TotalDeathsCount = Main.LocalPlayer.numberOfDeathsPVE,
            WorldEvilStone = (WorldGen.crimson ? Language.GetTextValue("Misc.Crimstone") : Language.GetTextValue("Misc.Ebonstone")),
            InputTriggerUI_BuildFromInventory = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: false, "QuickMount"),
            InputTriggerUI_SellItem = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: false, "SmartSelect"),
            InputTriggerUI_Trash = PlayerInput.GenerateInputTag_ForCurrentGamemode_WithHacks(tagForGameplay: false, "SmartSelect"),
            InputTriggerUI_FavoriteItem = PlayerInput.GenerateInputTag_ForCurrentGamemode_WithHacks(tagForGameplay: false, "SmartCursor"),
            InputTrigger_QuickEquip = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: false, "Grapple"),
            InputTrigger_LockOn = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "LockOn"),
            InputTrigger_RadialQuickbar = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "HotbarMinus"),
            InputTrigger_RadialHotbar = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "HotbarPlus"),
            InputTrigger_SmartCursor = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "SmartCursor"),
            InputTrigger_UseOrAttack = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "MouseLeft"),
            InputTrigger_InteractWithTile = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "MouseRight"),
            InputTrigger_SmartSelect = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "SmartSelect")
        };
    }
References Terraria.Player.anglerQuestsFinished, Terraria.Main.bloodMoon, Terraria.Main.cInv, Terraria.Main.dayTime, Terraria.NPC.downedChristmasIceQueen, Terraria.NPC.downedFishron, Terraria.NPC.downedFrost, Terraria.NPC.downedGolemBoss, Terraria.NPC.downedHalloweenKing, Terraria.NPC.downedMartians, Terraria.NPC.downedMoonlord, Terraria.Main.eclipse, Terraria.GameInput.PlayerInput.GenerateInputTag_ForCurrentGamemode(), Terraria.GameInput.PlayerInput.GenerateInputTag_ForCurrentGamemode_WithHacks(), Terraria.NPC.GetFirstNPCNameOrNull(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.hardMode, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Player.name, Terraria.Player.numberOfDeathsPVE, Terraria.Main.player, Terraria.Main.raining, Terraria.Main.worldName, and Terraria.Player.ZoneGraveyard.
Referenced by Terraria.GameContent.UI.GameTipsDisplay.GameTip.GameTip(), Terraria.Lang.AnglerQuestChat(), Terraria.Lang.AnglerQuestCountChat(), Terraria.Lang.BartenderChat(), Terraria.Lang.BartenderHelpText(), Terraria.Lang.BestiaryGirlChat(), Terraria.Lang.BunnyChat(), Terraria.Lang.CatChat(), Terraria.Lang.dialog(), Terraria.Lang.DogChat(), Terraria.Lang.DyeTraderQuestChat(), Terraria.NPC.GetChat(), Terraria.Chat.Commands.HelpCommand.GetCommandAliasesByID(), Terraria.Lang.GolferChat(), Terraria.NPC.HasLuckTextForWizard(), Terraria.NPC.HasSpecialEventText(), Terraria.Main.HelpText(), Terraria.Lang.PrincessChat(), and Terraria.Lang.SlimeChat().