Terraria: Terraria.Lang.GetMapObjectName
GetMapObjectName()
static string Terraria.Lang.GetMapObjectName (int id) inline static
Definition at line 65 of file Lang.cs.
    {
        if (_mapLegendCache != null)
        {
            return _mapLegendCache[id].Value;
        }
        return string.Empty;
    }
References Terraria.Lang._mapLegendCache, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.DrawGuideCraftText(), Terraria.Main.DrawGuideCraftText_Old(), Terraria.Main.DrawInfoAccs(), and Terraria.Main.DrawMap().