Terraria: Terraria.Lang.SupportGlyphs
SupportGlyphs()
static string Terraria.Lang.SupportGlyphs (string tooltip) inline static
Definition at line 522 of file Lang.cs.
    {
        if (tooltip.Contains("<right>"))
        {
            InputMode inputMode = InputMode.XBoxGamepad;
            if (PlayerInput.UsingGamepad)
            {
                inputMode = InputMode.XBoxGamepadUI;
            }
            if (inputMode == InputMode.XBoxGamepadUI)
            {
                KeyConfiguration keyConfiguration = PlayerInput.CurrentProfile.InputModes[inputMode];
                string text = PlayerInput.BuildCommand("", true, keyConfiguration.KeyStatus["MouseRight"]);
                text = text.Replace(": ", "");
                tooltip = tooltip.Replace("<right>", text);
            }
            else
            {
                tooltip = tooltip.Replace("<right>", Language.GetTextValue("Controls.RightClick"));
            }
        }
        if (tooltip.Contains("<left>"))
        {
            InputMode inputMode2 = InputMode.XBoxGamepad;
            if (PlayerInput.UsingGamepad)
            {
                inputMode2 = InputMode.XBoxGamepadUI;
            }
            if (inputMode2 == InputMode.XBoxGamepadUI)
            {
                KeyConfiguration keyConfiguration2 = PlayerInput.CurrentProfile.InputModes[inputMode2];
                string text2 = PlayerInput.BuildCommand("", true, keyConfiguration2.KeyStatus["MouseLeft"]);
                text2 = text2.Replace(": ", "");
                tooltip = tooltip.Replace("<left>", text2);
            }
            else
            {
                tooltip = tooltip.Replace("<left>", Language.GetTextValue("Controls.LeftClick"));
            }
        }
        return tooltip;
    }
References Terraria.GameInput.PlayerInput.BuildCommand(), Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.Localization.Language.GetTextValue(), Terraria.GameInput.KeyConfiguration.KeyStatus, System.text, and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.GameContent.UI.GameTipsDisplay.GameTip.GameTip(), Terraria.Lang.InitializeLegacyLocalization(), and Terraria.Main.TextDisplayCache.PrepareCache().