Terraria: Terraria.Lang.BartenderChat
BartenderChat()
static string Terraria.Lang.BartenderChat (NPC npc) inline static
    {
        object obj = CreateDialogSubstitutionObject(npc);
        if (Main.rand.Next(5) == 0)
        {
            string key = (DD2Event.DownedInvasionT3 ? "BartenderSpecialText.AfterDD2Tier3" : (DD2Event.DownedInvasionT2 ? "BartenderSpecialText.AfterDD2Tier2" : ((!DD2Event.DownedInvasionT1) ? "BartenderSpecialText.BeforeDD2Tier1" : "BartenderSpecialText.AfterDD2Tier1")));
            return Language.GetTextValueWith(key, obj);
        }
        return Language.SelectRandom(CreateDialogFilter("BartenderChatter.", obj)).FormatWith(obj);
    }
References Terraria.Lang.CreateDialogFilter(), Terraria.Lang.CreateDialogSubstitutionObject(), Terraria.GameContent.Events.DD2Event.DownedInvasionT1, Terraria.Localization.Language.GetTextValueWith(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, and Terraria.Localization.Language.SelectRandom().
Referenced by Terraria.NPC.GetChat().