Terraria: Terraria.Lang.GetItemNameValue
GetItemNameValue()
static string Terraria.Lang.GetItemNameValue (int id) inline static
Definition at line 185 of file Lang.cs.
    {
        return GetItemName(id).Value;
    }
References Terraria.Lang.GetItemName().
Referenced by Terraria.Map.TeleportPylonsMapLayer.Draw(), Terraria.UI.ChestUI.DrawName(), Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo(), Terraria.UI.IngameFancyUI.OpenVirtualKeyboard(), and Terraria.Main.SetRecipeMaterialDisplayName().