Terraria: Terraria.Lang.BartenderHelpText
BartenderHelpText()
static string Terraria.Lang.BartenderHelpText (NPC npc) inline static
Definition at line 263 of file Lang.cs.
    {
        object obj = CreateDialogSubstitutionObject(npc);
        Player player = Main.player[Main.myPlayer];
        if (player.bartenderQuestLog == 0)
        {
            player.bartenderQuestLog++;
            Item item = new Item();
            item.SetDefaults(3817);
            item.stack = 10;
            item.position = player.Center;
            item = player.GetItem(player.whoAmI, item, GetItemSettings.NPCEntityToPlayerInventorySettings);
            if (item.stack > 0)
            {
                int number = Item.NewItem(new EntitySource_Gift(npc), (int)player.position.X, (int)player.position.Y, player.width, player.height, item.type, item.stack, noBroadcast: false, 0, noGrabDelay: true);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number, 1f);
                }
            }
            return Language.GetTextValueWith("BartenderSpecialText.FirstHelp", obj);
        }
        LocalizedText[] array = Language.FindAll(CreateDialogFilter("BartenderHelpText.", obj));
        if (Main.BartenderHelpTextIndex >= array.Length)
        {
            Main.BartenderHelpTextIndex = 0;
        }
        return array[Main.BartenderHelpTextIndex++].FormatWith(obj);
    }
References Terraria.Main.BartenderHelpTextIndex, Terraria.Player.bartenderQuestLog, Terraria.Entity.Center, Terraria.Lang.CreateDialogFilter(), Terraria.Lang.CreateDialogSubstitutionObject(), Terraria.Localization.Language.FindAll(), Terraria.Localization.LocalizedText.FormatWith(), Terraria.Player.GetItem(), Terraria.Localization.Language.GetTextValueWith(), Terraria.Entity.height, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.GetItemSettings.NPCEntityToPlayerInventorySettings, Terraria.Main.player, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Item.type, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Main.GUIChatDrawInner().