Terraria: System.Number.DiyFp.Normalize
Normalize()
DiyFp System.Number.DiyFp.Normalize () inline
Definition at line 769 of file Number.cs.
        {
            int num = BitOperations.LeadingZeroCount(f);
            return new DiyFp(f << num, e - num);
        }
References System.Number.DiyFp.DiyFp(), System.Number.DiyFp.e, System.Number.DiyFp.f, and System.Numerics.BitOperations.LeadingZeroCount().
Referenced by System.Number.Grisu3.TryRunDouble(), System.Number.Grisu3.TryRunHalf(), and System.Number.Grisu3.TryRunSingle().