Terraria: System.Number.DiyFp.GetBoundaries
GetBoundaries()
void System.Number.DiyFp.GetBoundaries (int implicitBitIndex, out DiyFp mMinus, out DiyFp mPlus) inline private
Definition at line 780 of file Number.cs.
        {
            mPlus = new DiyFp((f << 1) + 1, e - 1).Normalize();
            if (f == (ulong)(1L << implicitBitIndex))
            {
                mMinus = new DiyFp((f << 2) - 1, e - 2);
            }
            else
            {
                mMinus = new DiyFp((f << 1) - 1, e - 1);
            }
            mMinus = new DiyFp(mMinus.f << mMinus.e - mPlus.e, mPlus.e);
        }
References System.Number.DiyFp.DiyFp(), System.Number.DiyFp.e, System.Number.DiyFp.f, and System.L.
Referenced by System.Number.DiyFp.CreateAndGetBoundaries(), System.Number.DiyFp.CreateAndGetBoundaries(), and System.Number.DiyFp.CreateAndGetBoundaries().