Terraria: UIBestiaryEntryInfoPage.AddInfoToList
AddInfoToList()
void UIBestiaryEntryInfoPage.AddInfoToList (BestiaryEntry entry, ExtraBestiaryInfoPageInformation extraInfo) inline private
     {
         BestiaryUICollectionInfo uICollectionInfo = GetUICollectionInfo(entry, extraInfo);
         IOrderedEnumerable<IGrouping<BestiaryInfoCategory, IBestiaryInfoElement>> orderedEnumerable = from x in new List<IBestiaryInfoElement>(entry.Info).GroupBy(GetBestiaryInfoCategory)
             orderby x.Key
             select x;
         UIElement item = null;
         foreach (IGrouping<BestiaryInfoCategory, IBestiaryInfoElement> item2 in orderedEnumerable)
         {
             if (item2.Count() == 0)
             {
                 continue;
             }
             bool flag = false;
             foreach (IBestiaryInfoElement item3 in item2.OrderByDescending(GetIndividualElementPriority))
             {
                 UIElement uIElement = item3.ProvideUIElement(uICollectionInfo);
                 if (uIElement != null)
                 {
                     _list.Add(uIElement);
                     flag = true;
                 }
             }
             if (flag)
             {
                 UIHorizontalSeparator uIHorizontalSeparator = new UIHorizontalSeparator
                 {
                     Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                     Color = new Color(89, 116, 213, 255) * 0.9f
                 };
                 _list.Add(uIHorizontalSeparator);
                 item = uIHorizontalSeparator;
             }
         }
         _list.Remove(item);
     }
References _list, UIList.Add(), Color, StyleDimension.FromPixelsAndPercent(), GetBestiaryInfoCategory(), GetIndividualElementPriority(), GetUICollectionInfo(), BestiaryEntry.Info, IBestiaryInfoElement.ProvideUIElement(), UIList.Remove(), and UIElement.Width.
Referenced by FillInfoForEntry().