Terraria: UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage
UIBestiaryEntryInfoPage()
UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage () inline
     {
         Width.Set(230f, 0f);
         Height.Set(0f, 1f);
         SetPadding(0f);
         BorderColor = new Color(89, 116, 213, 255);
         BackgroundColor = new Color(73, 94, 171);
         UIList uIList = new UIList
         {
             Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f, 1f)
         };
         uIList.SetPadding(2f);
         uIList.PaddingBottom = 4f;
         uIList.PaddingTop = 4f;
         Append(uIList);
         _list = uIList;
         uIList.ListPadding = 4f;
         uIList.ManualSortMethod = ManualIfnoSortingMethod;
         UIScrollbar uIScrollbar = new UIScrollbar();
         uIScrollbar.SetView(100f, 1000f);
         uIScrollbar.Height.Set(-20f, 1f);
         uIScrollbar.HAlign = 1f;
         uIScrollbar.VAlign = 0.5f;
         uIScrollbar.Left.Set(-6f, 0f);
         _scrollbar = uIScrollbar;
         _list.SetScrollbar(_scrollbar);
         CheckScrollBar();
         AppendBorderOverEverything();
     }
References _list, _scrollbar, UIElement.Append(), AppendBorderOverEverything(), UIPanel.BackgroundColor, UIPanel.BorderColor, CheckScrollBar(), Color, StyleDimension.FromPixelsAndPercent(), UIElement.HAlign, UIElement.Height, UIElement.Left, UIList.ListPadding, ManualIfnoSortingMethod(), UIList.ManualSortMethod, UIElement.PaddingBottom, UIElement.PaddingTop, StyleDimension.Set(), UIElement.SetPadding(), UIList.SetScrollbar(), UIScrollbar.SetView(), UIElement.VAlign, and UIElement.Width.