Terraria: System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAlpnHelper.Prepare
Prepare()
static unsafe void System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAlpnHelper.Prepare (List< SslApplicationProtocol > alpnProtocols, [NotNull] out MemoryHandle[] handles, [NotNull] out MsQuicNativeMethods::QuicBuffer[] buffers) inline static
Definition at line 10 of file MsQuicAlpnHelper.cs.
    {
        handles = ArrayPool<MemoryHandle>.Shared.Rent(alpnProtocols.Count);
        buffers = ArrayPool<MsQuicNativeMethods.QuicBuffer>.Shared.Rent(alpnProtocols.Count);
        try
        {
            for (int i = 0; i < alpnProtocols.Count; i++)
            {
                ReadOnlyMemory<byte> protocol = alpnProtocols[i].Protocol;
                MemoryHandle memoryHandle = protocol.Pin();
                handles[i] = memoryHandle;
                buffers[i].Buffer = (byte*)memoryHandle.Pointer;
                buffers[i].Length = (uint)protocol.Length;
            }
        }
        catch
        {
            Return(ref handles, ref buffers);
            throw;
        }
    }
References System.buffers, System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAlpnHelper.Return().
Referenced by System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), and System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start().