Terraria: System.ComponentModel.PropertyTabAttribute.InitializeTabClasses
InitializeTabClasses()
void System.ComponentModel.PropertyTabAttribute.InitializeTabClasses () inline private
Definition at line 68 of file PropertyTabAttribute.cs.
    {
        _tabClasses = new Type[_tabClassNames.Length];
        for (int i = 0; i < _tabClassNames.Length; i++)
        {
            int num = _tabClassNames[i].IndexOf(',');
            string text = null;
            string text2 = null;
            if (num != -1)
            {
                text = _tabClassNames[i].AsSpan(0, num).Trim().ToString();
                text2 = _tabClassNames[i].AsSpan(num + 1).Trim().ToString();
            }
            else
            {
                text = _tabClassNames[i];
            }
            _tabClasses[i] = Type.GetType(text, throwOnError: false);
            if (_tabClasses[i] == null)
            {
                if (text2 == null)
                {
                    throw new TypeLoadException(System.SR.Format(System.SR.PropertyTabAttributeTypeLoadException, text));
                }
                Assembly assembly = Assembly.Load(text2);
                if (assembly != null)
                {
                    _tabClasses[i] = assembly.GetType(text, throwOnError: true);
                }
            }
        }
    }
References System.ComponentModel.PropertyTabAttribute._tabClasses, System.ComponentModel.PropertyTabAttribute._tabClassNames, System.SR.Format(), System.Reflection.Assembly.GetType(), System.Type.GetType(), System.Reflection.Assembly.Load(), System.SR.PropertyTabAttributeTypeLoadException, and System.text.