Terraria: System.Data.Common.DbProviderFactories.GetFactory
GetFactory() [4/4]
static DbProviderFactory System.Data.Common.DbProviderFactories.GetFactory (string providerInvariantName, bool throwOnError) inline static private
Definition at line 133 of file DbProviderFactories.cs.
    {
        if (throwOnError)
        {
            ADP.CheckArgumentLength(providerInvariantName, "providerInvariantName");
        }
        else if (string.IsNullOrWhiteSpace(providerInvariantName))
        {
            return null;
        }
        if (!_registeredFactories.TryGetValue(providerInvariantName, out var value))
        {
            if (!throwOnError)
            {
                return null;
            }
            throw ADP.Argument(System.SR.Format(System.SR.ADP_DbProviderFactories_InvariantNameNotFound, providerInvariantName));
        }
        DbProviderFactory factoryInstance = value.FactoryInstance;
        if (factoryInstance == null)
        {
            factoryInstance = GetFactoryInstance(GetProviderTypeFromTypeName(value.FactoryTypeAssemblyQualifiedName));
            RegisterFactory(providerInvariantName, factoryInstance);
        }
        return factoryInstance;
    }
References System.Data.Common.DbProviderFactories._registeredFactories, System.SR.ADP_DbProviderFactories_InvariantNameNotFound, System.Data.Common.ADP.Argument(), System.Data.Common.ADP.CheckArgumentLength(), System.SR.Format(), System.Data.Common.DbProviderFactories.GetFactoryInstance(), System.Data.Common.DbProviderFactories.GetProviderTypeFromTypeName(), System.Data.Common.DbProviderFactories.RegisterFactory(), and System.value.