Terraria: System.Data.Common.DbProviderFactories.GetFactoryInstance
GetFactoryInstance()
static DbProviderFactory System.Data.Common.DbProviderFactories.GetFactoryInstance ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields)] Type providerFactoryClass) inline static private
Definition at line 160 of file DbProviderFactories.cs.
    {
        ADP.CheckArgumentNull(providerFactoryClass, "providerFactoryClass");
        if (!providerFactoryClass.IsSubclassOf(typeof(DbProviderFactory)))
        {
            throw ADP.Argument(System.SR.Format(System.SR.ADP_DbProviderFactories_NotAFactoryType, providerFactoryClass.FullName));
        }
        FieldInfo field = providerFactoryClass.GetField("Instance", BindingFlags.DeclaredOnly | BindingFlags.Static | BindingFlags.Public);
        if (null == field)
        {
            throw ADP.InvalidOperation(System.SR.ADP_DbProviderFactories_NoInstance);
        }
        if (!field.FieldType.IsSubclassOf(typeof(DbProviderFactory)))
        {
            throw ADP.InvalidOperation(System.SR.ADP_DbProviderFactories_NoInstance);
        }
        object value = field.GetValue(null);
        if (value == null)
        {
            throw ADP.InvalidOperation(System.SR.ADP_DbProviderFactories_NoInstance);
        }
        return (DbProviderFactory)value;
    }
References System.SR.ADP_DbProviderFactories_NoInstance, System.SR.ADP_DbProviderFactories_NotAFactoryType, System.Data.Common.ADP.Argument(), System.Data.Common.ADP.CheckArgumentNull(), System.SR.Format(), System.Data.Common.ADP.InvalidOperation(), and System.value.
Referenced by System.Data.Common.DbProviderFactories.GetFactory(), System.Data.Common.DbProviderFactories.GetFactory(), and System.Data.Common.DbProviderFactories.RegisterFactory().