Terraria: System.Data.Common.DbProviderFactories.RegisterFactory
RegisterFactory() [1/3]
static void System.Data.Common.DbProviderFactories.RegisterFactory (string providerInvariantName, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields)] string factoryTypeAssemblyQualifiedName) inline static
Definition at line 103 of file DbProviderFactories.cs.
    {
        ADP.CheckArgumentLength(providerInvariantName, "providerInvariantName");
        ADP.CheckArgumentLength(factoryTypeAssemblyQualifiedName, "factoryTypeAssemblyQualifiedName");
        _registeredFactories[providerInvariantName] = new ProviderRegistration(factoryTypeAssemblyQualifiedName, null);
    }
References System.Data.Common.DbProviderFactories._registeredFactories, and System.Data.Common.ADP.CheckArgumentLength().
Referenced by System.Data.Common.DbProviderFactories.GetFactory(), and System.Data.Common.DbProviderFactories.RegisterFactory().