Terraria: System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAlpnHelper.Return
Return()
static void System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAlpnHelper.Return (ref MemoryHandle[] handles, ref MsQuicNativeMethods::QuicBuffer[] buffers) inline static
Definition at line 32 of file MsQuicAlpnHelper.cs.
    {
        MemoryHandle[] array = handles;
        if (array != null)
        {
            MemoryHandle[] array2 = array;
            foreach (MemoryHandle memoryHandle in array2)
            {
                memoryHandle.Dispose();
            }
            handles = null;
            ArrayPool<MemoryHandle>.Shared.Return(array);
        }
        MsQuicNativeMethods.QuicBuffer[] array3 = buffers;
        if (array3 != null)
        {
            buffers = null;
            ArrayPool<MsQuicNativeMethods.QuicBuffer>.Shared.Return(array3);
        }
    }
References System.array, and System.buffers.
Referenced by System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAlpnHelper.Prepare(), and System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start().