Terraria: System.Linq.Parallel.QuerySettings.WithPerExecutionSettings
WithPerExecutionSettings() [2/2]
QuerySettings System.Linq.Parallel.QuerySettings.WithPerExecutionSettings (CancellationTokenSource topLevelCancellationTokenSource, Shared< bool > topLevelDisposedFlag) inline package
Definition at line 129 of file QuerySettings.cs.
    {
        QuerySettings result = new QuerySettings(TaskScheduler, DegreeOfParallelism, CancellationState.ExternalCancellationToken, ExecutionMode, MergeOptions);
        result.CancellationState.InternalCancellationTokenSource = topLevelCancellationTokenSource;
        result.CancellationState.MergedCancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(result.CancellationState.InternalCancellationTokenSource.Token, result.CancellationState.ExternalCancellationToken);
        result.CancellationState.TopLevelDisposedFlag = topLevelDisposedFlag;
        result._queryId = PlinqEtwProvider.NextQueryId();
        return result;
    }
References System.Linq.Parallel.QuerySettings.QuerySettings(), System.Linq.Parallel.QuerySettings.CancellationState, System.Threading.CancellationTokenSource.CreateLinkedTokenSource(), System.Linq.Parallel.QuerySettings.DegreeOfParallelism, System.Linq.Parallel.QuerySettings.ExecutionMode, System.Linq.Parallel.CancellationState.ExternalCancellationToken, System.Linq.Parallel.CancellationState.InternalCancellationTokenSource, System.Linq.Parallel.QuerySettings.MergeOptions, System.Linq.Parallel.PlinqEtwProvider.NextQueryId(), and System.Threading.CancellationTokenSource.Token.