Terraria: ReLogic.OS.Windows.NativeClipboard.TryGetText
TryGetText()
static bool ReLogic.OS.Windows.NativeClipboard.TryGetText (out string text) inline static
Definition at line 45 of file NativeClipboard.cs.
    {
        text = null;
        if (!IsClipboardFormatAvailable(13u))
        {
            return false;
        }
        try
        {
            if (!OpenClipboard(IntPtr.Zero))
            {
                return false;
            }
            IntPtr handle = GetClipboardData(13u);
            if (handle == IntPtr.Zero)
            {
                return false;
            }
            IntPtr pointer = IntPtr.Zero;
            try
            {
                pointer = GlobalLock(handle);
                if (pointer == IntPtr.Zero)
                {
                    return false;
                }
                int size = GlobalSize(handle);
                byte[] buff = new byte[size];
                Marshal.Copy(pointer, buff, 0, size);
                text = Encoding.Unicode.GetString(buff).TrimEnd('\0');
                return !string.IsNullOrEmpty(text);
            }
            finally
            {
                if (pointer != IntPtr.Zero)
                {
                    GlobalUnlock(handle);
                }
            }
        }
        finally
        {
            CloseClipboard();
        }
    }
References ReLogic.OS.Windows.NativeClipboard.CloseClipboard(), System.Runtime.InteropServices.Marshal.Copy(), ReLogic.OS.Windows.NativeClipboard.GetClipboardData(), ReLogic.OS.Windows.NativeClipboard.GlobalLock(), ReLogic.OS.Windows.NativeClipboard.GlobalSize(), ReLogic.OS.Windows.NativeClipboard.GlobalUnlock(), System.handle, ReLogic.OS.Windows.NativeClipboard.IsClipboardFormatAvailable(), ReLogic.OS.Windows.NativeClipboard.OpenClipboard(), System.pointer, System.text, System.Text.Encoding.Unicode, and System.IntPtr.Zero.
Referenced by ReLogic.OS.Windows.Clipboard.TryToGetClipboardText().