Terraria: System.Net.IPAddressParser.IPv6AddressToString
IPv6AddressToString() [2/2]
static bool System.Net.IPAddressParser.IPv6AddressToString (ushort[] address, uint scopeId, Span< char > destination, out int charsWritten) inline static package
Definition at line 82 of file IPAddressParser.cs.
    {
        StringBuilder stringBuilder = IPv6AddressToStringHelper(address, scopeId);
        if (destination.Length < stringBuilder.Length)
        {
            System.Text.StringBuilderCache.Release(stringBuilder);
            charsWritten = 0;
            return false;
        }
        stringBuilder.CopyTo(0, destination, stringBuilder.Length);
        charsWritten = stringBuilder.Length;
        System.Text.StringBuilderCache.Release(stringBuilder);
        return true;
    }
References System.Text.StringBuilder.CopyTo(), System.destination, System.Net.IPAddressParser.IPv6AddressToStringHelper(), System.Text.StringBuilder.Length, and System.Text.StringBuilderCache.Release().