Terraria: System.Net.IPAddressParser.IPv4AddressToStringHelper
IPv4AddressToStringHelper()
static unsafe int System.Net.IPAddressParser.IPv4AddressToStringHelper (uint address, char * addressString) inline static private
Definition at line 62 of file IPAddressParser.cs.
    {
        int offset = 0;
        address = (uint)IPAddress.NetworkToHostOrder((int)address);
        FormatIPv4AddressNumber((int)((address >> 24) & 0xFF), addressString, ref offset);
        addressString[offset++] = '.';
        FormatIPv4AddressNumber((int)((address >> 16) & 0xFF), addressString, ref offset);
        addressString[offset++] = '.';
        FormatIPv4AddressNumber((int)((address >> 8) & 0xFF), addressString, ref offset);
        addressString[offset++] = '.';
        FormatIPv4AddressNumber((int)(address & 0xFF), addressString, ref offset);
        return offset;
    }
References System.Net.IPAddressParser.FormatIPv4AddressNumber(), System.Net.IPAddress.NetworkToHostOrder(), and System.offset.
Referenced by System.Net.IPAddressParser.IPv4AddressToString(), System.Net.IPAddressParser.IPv4AddressToString(), and System.Net.IPAddressParser.IPv4AddressToString().