Terraria: System.Net.IPAddressParser.Ipv6StringToAddress
Ipv6StringToAddress()
static unsafe bool System.Net.IPAddressParser.Ipv6StringToAddress (ReadOnlySpan< char > ipSpan, Span< ushort > numbers, int numbersLength, out uint scope) inline static
Definition at line 149 of file IPAddressParser.cs.
    {
        int end = ipSpan.Length;
        bool flag = false;
        fixed (char* name = &MemoryMarshal.GetReference(ipSpan))
        {
            flag = System.IPv6AddressHelper.IsValidStrict(name, 0, ref end);
        }
        if (flag || end != ipSpan.Length)
        {
            string scopeId = null;
            System.IPv6AddressHelper.Parse(ipSpan, numbers, 0, ref scopeId);
            if (scopeId != null && scopeId.Length > 1)
            {
                if (uint.TryParse(scopeId.AsSpan(1), NumberStyles.None, CultureInfo.InvariantCulture, out scope))
                {
                    return true;
                }
                uint num = InterfaceInfoPal.InterfaceNameToIndex(scopeId);
                if (num != 0)
                {
                    scope = num;
                    return true;
                }
            }
            scope = 0u;
            return true;
        }
        scope = 0u;
        return false;
    }
References System.Net.NetworkInformation.InterfaceInfoPal.InterfaceNameToIndex(), System.Globalization.CultureInfo.InvariantCulture, System.IPv6AddressHelper.IsValidStrict(), System.ReadOnlySpan< T >.Length, and System.IPv6AddressHelper.Parse().
Referenced by System.Net.IPAddressParser.Parse().