Terraria: System.Net.IPAddressParser.Parse
Parse()
static IPAddress System.Net.IPAddressParser.Parse (ReadOnlySpan< char > ipSpan, bool tryParse) inline static package
Definition at line 11 of file IPAddressParser.cs.
    {
        long address;
        if (ipSpan.Contains(':'))
        {
            Span<ushort> span = stackalloc ushort[8];
            span.Clear();
            if (Ipv6StringToAddress(ipSpan, span, 8, out var scope))
            {
                return new IPAddress(span, scope);
            }
        }
        else if (Ipv4StringToAddress(ipSpan, out address))
        {
            return new IPAddress(address);
        }
        if (tryParse)
        {
            return null;
        }
        throw new FormatException(System.SR.dns_bad_ip_address, new SocketException(SocketError.InvalidArgument));
    }
References System.Span< T >.Clear(), System.SR.dns_bad_ip_address, System.Net.IPAddressParser.Ipv4StringToAddress(), and System.Net.IPAddressParser.Ipv6StringToAddress().
Referenced by System.Net.IPAddress.Parse(), System.Net.IPAddress.Parse(), System.Net.IPAddress.TryParse(), and System.Net.IPAddress.TryParse().