Terraria: TEFoodPlatter.TryPlacing
TryPlacing()
static void TEFoodPlatter.TryPlacing (int x, int y, int netid, int prefix, int stack) inline static
     {
         WorldGen.RangeFrame(x, y, x + 1, y + 1);
         int num = Find(x, y);
         if (num == -1)
         {
             int num2 = Item.NewItem(new EntitySource_TileBreak(x, y), x * 16, y * 16, 16, 16, 1);
             Main.item[num2].netDefaults(netid);
             Main.item[num2].Prefix(prefix);
             Main.item[num2].stack = stack;
             NetMessage.SendData(21, -1, -1, null, num2);
             return;
         }
         TEFoodPlatter tEFoodPlatter = (TEFoodPlatter)TileEntity.ByID[num];
         if (tEFoodPlatter.item.stack > 0)
         {
             tEFoodPlatter.DropItem();
         }
         tEFoodPlatter.item = new Item();
         tEFoodPlatter.item.netDefaults(netid);
         tEFoodPlatter.item.Prefix(prefix);
         tEFoodPlatter.item.stack = stack;
         NetMessage.SendData(86, -1, -1, null, tEFoodPlatter.ID, x, y);
     }
References TEFoodPlatter(), TileEntity.ByID, DropItem(), Find(), TileEntity.ID, item, Main.item, Item.netDefaults(), Item.NewItem(), Item.Prefix(), WorldGen.RangeFrame(), NetMessage.SendData(), and Item.stack.
Referenced by MessageBuffer.GetData(), and PlaceItemInFrame().