Terraria: CaptureInterface.ModeChangeSettings.Update
Update()
override void CaptureInterface.ModeChangeSettings.Update () inline virtual
Implements CaptureInterface.CaptureInterfaceMode.
         {
             if (!Selected || JustActivated)
             {
                 return;
             }
             PlayerInput.SetZoom_UI();
             Point value = new Point(Main.mouseX, Main.mouseY);
             hoveredButton = -1;
             Rectangle rect = GetRect();
             inUI = rect.Contains(value);
             rect.Inflate(-20, -20);
             rect.Height = 16;
             int y = rect.Y;
             for (int i = 0; i < 7; i++)
             {
                 rect.Y = y + i * 20;
                 if (rect.Contains(value))
                 {
                     hoveredButton = i;
                     break;
                 }
             }
             if (Main.mouseLeft && Main.mouseLeftRelease && hoveredButton != -1)
             {
                 PressButton(hoveredButton);
             }
         }
References CaptureInterface.ModeChangeSettings.GetRect(), CaptureInterface.ModeChangeSettings.hoveredButton, CaptureInterface.ModeChangeSettings.inUI, CaptureInterface.JustActivated, Main.mouseLeft, Main.mouseLeftRelease, Main.mouseX, Main.mouseY, CaptureInterface.ModeChangeSettings.PressButton(), CaptureInterface.CaptureInterfaceMode.Selected, and PlayerInput.SetZoom_UI().