Terraria: CaptureInterface.ModeChangeSettings.DrawWaterChoices
DrawWaterChoices()
void CaptureInterface.ModeChangeSettings.DrawWaterChoices (SpriteBatch spritebatch, Point start, Point mouse) inline private
         {
             Rectangle r = new Rectangle(0, 0, 20, 20);
             for (int i = 0; i < 2; i++)
             {
                 for (int j = 0; j < 7; j++)
                 {
                     if (i == 1 && j == 6)
                     {
                         continue;
                     }
                     int num = j + i * 7;
                     r.X = start.X + 24 * j + 12 * i;
                     r.Y = start.Y + 24 * i;
                     int num2 = num;
                     int num3 = 0;
                     if (r.Contains(mouse))
                     {
                         if (Main.mouseLeft && Main.mouseLeftRelease)
{
                             SoundEngine.PlaySound(12);
                             Settings.BiomeChoiceIndex = num2;
                         }
                         Main.instance.MouseText(Language.GetTextValue("CaptureBiomeChoice." + num2), 0, 0);
                         num3++;
                     }
                     if (Settings.BiomeChoiceIndex == num2)
                     {
                         num3 += 2;
                     }
                     Texture2D value = TextureAssets.Extra[130].Value;
                     int x = num * 18;
                     _ = Color.White;
                     float num4 = 1f;
                     if (num3 < 2)
                     {
                         num4 *= 0.5f;
                     }
                     if (num3 % 2 == 1)
                     {
                         spritebatch.Draw(TextureAssets.MagicPixel.Value, r.TopLeft(), new Rectangle(0, 0, 1, 1), Color.Gold, 0f, Vector2.Zero, new Vector2(20f), SpriteEffects.None, 0f);
                     }
                     else
                     {
                         spritebatch.Draw(TextureAssets.MagicPixel.Value, r.TopLeft(), new Rectangle(0, 0, 1, 1), Color.White * num4, 0f, Vector2.Zero, new Vector2(20f), SpriteEffects.None, 0f);
                     }
                     spritebatch.Draw(value, r.TopLeft() + new Vector2(2f), new Rectangle(x, 0, 16, 16), Color.White * num4);
                 }
             }
         }
References CaptureInterface.Settings.BiomeChoiceIndex, Color, TextureAssets.Extra, Language.GetTextValue(), Main.instance, TextureAssets.MagicPixel, Main.mouseLeft, Main.mouseLeftRelease, Main.MouseText(), SoundEngine.PlaySound(), and Asset< T >.Value.
Referenced by CaptureInterface.ModeChangeSettings.Draw().