Terraria: System.Security.Cryptography.ECCurve.CreateFromFriendlyName
CreateFromFriendlyName()
static ECCurve System.Security.Cryptography.ECCurve.CreateFromFriendlyName (string oidFriendlyName) inline static
Definition at line 135 of file ECCurve.cs.
    {
        if (oidFriendlyName == null)
        {
            throw new ArgumentNullException("oidFriendlyName");
        }
        return CreateFromValueAndName(null, oidFriendlyName);
    }
References System.Security.Cryptography.ECCurve.CreateFromValueAndName().
Referenced by Internal.Cryptography.Pal.X509Pal.DecodeECPublicKey< TAlgorithm >(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCngPublicKey.ExportParameters(), and System.Security.Cryptography.ECDiffieHellmanCngPublicKey.ExportParameters().