Terraria: System.Security.Cryptography.ECCurve.CreateFromOid
CreateFromOid()
static ECCurve System.Security.Cryptography.ECCurve.CreateFromOid (Oid curveOid) inline static
Definition at line 127 of file ECCurve.cs.
    {
        ECCurve result = default(ECCurve);
        result.CurveType = ECCurveType.Named;
        result.Oid = curveOid;
        return result;
    }
Referenced by System.Security.Cryptography.ECCurve.CreateFromValueAndName(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ExportParameters(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ExportParameters(), System.Security.Cryptography.ECDiffieHellmanCng.ExportParameters(), System.Security.Cryptography.ECDsaCng.ExportParameters(), System.Security.Cryptography.EccKeyFormatHelper.GetCurve(), and System.Security.Cryptography.EccKeyFormatHelper.GetCurve().