Terraria: System.Security.Cryptography.ECCurve.Validate
Validate()
void System.Security.Cryptography.ECCurve.Validate () inline
Definition at line 173 of file ECCurve.cs.
    {
        if (IsNamed)
        {
            if (HasAnyExplicitParameters())
            {
                throw new CryptographicException(System.SR.Cryptography_InvalidECNamedCurve);
            }
            if (Oid == null || (string.IsNullOrEmpty(Oid.FriendlyName) && string.IsNullOrEmpty(Oid.Value)))
            {
                throw new CryptographicException(System.SR.Cryptography_InvalidCurveOid);
            }
        }
        else if (IsExplicit)
        {
            bool flag = false;
            if (A == null || B == null || B.Length != A.Length || G.X == null || G.X.Length != A.Length || G.Y == null || G.Y.Length != A.Length || Order == null || Order.Length == 0 || Cofactor == null || Cofactor.Length == 0)
            {
                flag = true;
            }
            if (IsPrime)
            {
                if (!flag && (Prime == null || Prime.Length != A.Length))
                {
                    flag = true;
                }
                if (flag)
                {
                    throw new CryptographicException(System.SR.Cryptography_InvalidECPrimeCurve);
                }
            }
            else if (IsCharacteristic2)
            {
                if (!flag && (Polynomial == null || Polynomial.Length == 0))
                {
                    flag = true;
                }
                if (flag)
                {
                    throw new CryptographicException(System.SR.Cryptography_InvalidECCharacteristic2Curve);
                }
            }
        }
        else if (HasAnyExplicitParameters() || Oid != null)
        {
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_CurveNotSupported, CurveType.ToString()));
        }
    }
References System.Security.Cryptography.ECCurve.A, System.Security.Cryptography.ECCurve.B, System.Security.Cryptography.ECCurve.Cofactor, System.SR.Cryptography_CurveNotSupported, System.SR.Cryptography_InvalidCurveOid, System.SR.Cryptography_InvalidECCharacteristic2Curve, System.SR.Cryptography_InvalidECNamedCurve, System.SR.Cryptography_InvalidECPrimeCurve, System.Security.Cryptography.ECCurve.CurveType, System.SR.Format(), System.Security.Cryptography.Oid.FriendlyName, System.Security.Cryptography.ECCurve.G, System.Security.Cryptography.ECCurve.HasAnyExplicitParameters(), System.Security.Cryptography.ECCurve.IsCharacteristic2, System.Security.Cryptography.ECCurve.IsExplicit, System.Security.Cryptography.ECCurve.IsNamed, System.Security.Cryptography.ECCurve.IsPrime, System.Security.Cryptography.ECCurve.Order, System.Security.Cryptography.ECCurve.Polynomial, System.Security.Cryptography.ECCurve.Prime, System.Security.Cryptography.Oid.Value, System.Security.Cryptography.ECPoint.X, and System.Security.Cryptography.ECPoint.Y.
Referenced by System.Security.Cryptography.ECCngKey.GenerateKey(), System.Security.Cryptography.ECDiffieHellmanCng.GenerateKey(), System.Security.Cryptography.ECDsaCng.GenerateKey(), and System.Security.Cryptography.ECParameters.Validate().