Terraria: Player.ItemCheck_CheckFishingBobber_PullBobber
ItemCheck_CheckFishingBobber_PullBobber()
void Player.ItemCheck_CheckFishingBobber_PullBobber (Projectile bobber, int baitTypeUsed) inline private
     {
         if (baitTypeUsed == 2673)
         {
             if (Main.netMode != 1)
             {
                 NPC.SpawnOnPlayer(whoAmI, 370);
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, 370f);
             }
             bobber.ai[0] = 2f;
         }
         else if (bobber.localAI[1] < 0f)
         {
             Point point = new Point((int)bobber.position.X, (int)bobber.position.Y);
             int num = (int)(0f - bobber.localAI[1]);
             if (num == 618)
             {
                 point.Y += 64;
             }
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(130, -1, -1, null, point.X / 16, point.Y / 16, num);
             }
             else
             {
                 if (num == 682)
                 {
                     NPC.unlockedSlimeRedSpawn = true;
                 }
                 NPC.NewNPC(new EntitySource_FishedOut(this), point.X, point.Y, num);
                 bobber.ai[0] = 2f;
                 WorldGen.CheckAchievement_RealEstateAndTownSlimes();
             }
         }
         else if (Main.rand.Next(7) == 0 && !accFishingLine)
         {
             bobber.ai[0] = 2f;
         }
         else
         {
             bobber.ai[1] = bobber.localAI[1];
         }
         bobber.netUpdate = true;
     }
References Projectile.ai, WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Projectile.localAI, Main.netMode, Projectile.netUpdate, NPC.NewNPC(), UnifiedRandom.Next(), Entity.position, Main.rand, NetMessage.SendData(), NPC.SpawnOnPlayer(), and NPC.unlockedSlimeRedSpawn.