Terraria: Player.dropItemCheck
dropItemCheck()
void Player.dropItemCheck () inline
     {
         if (!Main.playerInventory)
         {
             noThrow = 0;
         }
         if (noThrow > 0)
         {
             noThrow--;
         }
         GetItemSettings getItemInDropItemCheck = GetItemSettings.GetItemInDropItemCheck;
         if (!Main.InGuideCraftMenu && Main.guideItem.type > 0)
         {
             Main.guideItem.position = base.Center;
             Item item = GetItem(whoAmI, Main.guideItem, getItemInDropItemCheck);
             if (item.stack > 0)
             {
                 int num = Item.NewItem(GetItemSource_Misc(4), (int)position.X, (int)position.Y, width, height, item.type, item.stack, noBroadcast: false, Main.guideItem.prefix, noGrabDelay: true);
                 Main.item[num].newAndShiny = false;
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(21, -1, -1, null, num, 1f);
                 }
             }
             Main.guideItem = new Item();
         }
         if (!Main.InReforgeMenu && Main.reforgeItem.type > 0)
         {
             Main.reforgeItem.position = base.Center;
             Item item2 = GetItem(whoAmI, Main.reforgeItem, getItemInDropItemCheck);
             if (item2.stack > 0)
             {
                 int num2 = Item.NewItem(GetItemSource_Misc(4), (int)position.X, (int)position.Y, width, height, item2.type, item2.stack, noBroadcast: false, Main.reforgeItem.prefix, noGrabDelay: true);
                 Main.item[num2].newAndShiny = false;
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(21, -1, -1, null, num2, 1f);
                 }
             }
             Main.reforgeItem = new Item();
         }
         if (Main.myPlayer == whoAmI)
         {
             inventory[58] = Main.mouseItem.Clone();
         }
         bool flag = true;
         if (Main.mouseItem.type > 0 && Main.mouseItem.stack > 0)
         {
             if (!Main.gamePaused)
             {
                 tileTargetX = (int)(((float)Main.mouseX + Main.screenPosition.X) / 16f);
                 tileTargetY = (int)(((float)Main.mouseY + Main.screenPosition.Y) / 16f);
                 if (gravDir == -1f)
                 {
                     tileTargetY = (int)((Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY) / 16f);
                 }
             }
             if (selectedItem != 58)
             {
                 oldSelectItem = selectedItem;
             }
             selectedItem = 58;
             flag = false;
         }
         if (flag && selectedItem == 58 && ItemTimeIsZero && itemAnimation == 0)
         {
             selectedItem = oldSelectItem;
         }
         if (Main.mouseItem.type > 0 && !Main.playerInventory)
         {
             Main.mouseItem.position = base.Center;
             Item item3 = GetItem(whoAmI, Main.mouseItem, getItemInDropItemCheck);
             if (item3.stack > 0)
             {
                 int num3 = Item.NewItem(GetItemSource_Misc(4), (int)position.X, (int)position.Y, width, height, item3.type, item3.stack, noBroadcast: false, Main.mouseItem.prefix, noGrabDelay: true);
                 Main.item[num3].newAndShiny = false;
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(21, -1, -1, null, num3, 1f);
                 }
             }
             Main.mouseItem = new Item();
             inventory[58] = new Item();
             Recipe.FindRecipes();
         }
         if (((controlThrow && releaseThrow && !inventory[selectedItem].favorited && inventory[selectedItem].type > 0 && !Main.drawingPlayerChat) || (((Main.mouseRight && !mouseInterface && Main.mouseRightRelease) || !Main.playerInventory) && Main.mouseItem.type > 0 && Main.mouseItem.stack > 0)) && noThrow <= 0)
         {
             DropSelectedItem();
         }
         if (Main.gamePaused && selectedItem == 58)
         {
             selectedItem = oldSelectItem;
         }
     }
References Item.Clone(), Main.drawingPlayerChat, Recipe.FindRecipes(), Main.gamePaused, GetItemSettings.GetItemInDropItemCheck, Main.guideItem, Main.InGuideCraftMenu, Main.InReforgeMenu, Main.item, Main.mouseItem, Main.mouseRight, Main.mouseRightRelease, Main.mouseX, Main.mouseY, Main.myPlayer, Main.netMode, Item.newAndShiny, Item.NewItem(), Main.playerInventory, Entity.position, Item.prefix, Main.reforgeItem, Main.screenHeight, Main.screenPosition, NetMessage.SendData(), Item.stack, and Item.type.
Referenced by Main.DoUpdate_WhilePaused(), Main.DrawInventory(), and Main.HoverOverNPCs().