Terraria: Player.PlayerFrame
PlayerFrame()
void Player.PlayerFrame () inline
     {
         if (swimTime > 0)
         {
             swimTime--;
             if (!wet)
             {
                 swimTime = 0;
             }
         }
         head = armor[0].headSlot;
         body = armor[1].bodySlot;
         legs = armor[2].legSlot;
         if (armor[10].headSlot >= 0)
         {
             head = armor[10].headSlot;
         }
         if (armor[11].bodySlot >= 0)
         {
             body = armor[11].bodySlot;
         }
         if (armor[12].legSlot >= 0)
         {
             legs = armor[12].legSlot;
         }
         if (!dead)
         {
             UpdateVisibleAccessories();
         }
         wearsRobe = false;
         bool somethingSpecial = false;
         SetMatchRequest request = default(SetMatchRequest);
         request.Head = head;
         request.Body = body;
         request.Legs = legs;
         request.Male = Male;
         request.ArmorSlotRequested = 1;
         int num = SetMatch(request, ref wearsRobe);
         if (num != -1)
         {
             legs = num;
         }
         request = default(SetMatchRequest);
         request.Head = head;
         request.Body = body;
         request.Legs = legs;
         request.Male = Male;
         request.ArmorSlotRequested = 2;
         num = SetMatch(request, ref somethingSpecial);
         if (num != -1)
         {
             legs = num;
         }
         request = default(SetMatchRequest);
         request.Head = head;
         request.Body = body;
         request.Legs = legs;
         request.Male = Male;
         request.ArmorSlotRequested = 0;
         num = SetMatch(request, ref somethingSpecial);
         if (num != -1)
         {
             head = num;
         }
         if (body == 93)
         {
             shield = 0;
             handoff = 0;
         }
         if (body > 0 && ArmorIDs.Body.Sets.DisableHandOnAndOffAccDraw[body])
         {
             handon = 0;
             handoff = 0;
         }
         if (body > 0 && waist > 0 && ArmorIDs.Body.Sets.DisableBeltAccDraw[body] && ArmorIDs.Waist.Sets.IsABelt[waist])
         {
             waist = 0;
         }
         if (!dead && body >= 0)
         {
             sbyte b = (sbyte)(Male ? ArmorIDs.Body.Sets.IncludedCapeBack : ArmorIDs.Body.Sets.IncludedCapeBackFemale)[body];
             if (b != -1)
             {
                 if (ArmorIDs.Back.Sets.DrawInBackpackLayer[b])
                 {
                     backpack = b;
                     cBackpack = cBody;
                 }
                 else if (ArmorIDs.Back.Sets.DrawInTailLayer[b])
                 {
                     tail = b;
                     cTail = cBody;
                 }
                 else if (back == -1)
                 {
                     back = b;
                     cBack = cBody;
                 }
             }
             sbyte b2 = (sbyte)ArmorIDs.Body.Sets.IncludedCapeFront[body];
             if (b2 != -1 && front == -1)
             {
                 front = b2;
                 cFront = cBody;
             }
             ArmorIDs.Body.Sets.IncludeCapeFrontAndBackInfo includeCapeFrontAndBackInfo = ArmorIDs.Body.Sets.IncludeCapeFrontAndBack[body];
             if (!includeCapeFrontAndBackInfo.Invalid && back == -1 && front == -1)
             {
                 front = includeCapeFrontAndBackInfo.frontCape;
                 cFront = cBody;
                 sbyte backCape = includeCapeFrontAndBackInfo.backCape;
                 if (ArmorIDs.Back.Sets.DrawInBackpackLayer[backCape])
                 {
                     backpack = backCape;
                     cBackpack = cBody;
                 }
                 else if (ArmorIDs.Back.Sets.DrawInTailLayer[backCape])
                 {
                     tail = backCape;
                     cTail = cBody;
                 }
                 else if (!sitting.isSitting)
                 {
                     back = backCape;
                     cBack = cBody;
                 }
             }
         }
         if (legs == 67)
         {
             shoe = 0;
         }
         if (legs == 140)
         {
             shoe = 0;
         }
         bool flag = false;
         if ((wereWolf || forceWerewolf) && !hideWolf)
         {
             legs = 20;
             body = 21;
             head = 38;
             flag = true;
         }
         bool flag2 = wet && !lavaWet && (!mount.Active || !mount.IsConsideredASlimeMount);
         if (merman || forceMerman)
         {
             if (!hideMerman)
             {
                 head = 39;
                 legs = 21;
                 body = 22;
                 flag = true;
             }
             if (flag2)
             {
                 wings = 0;
             }
         }
         socialShadowRocketBoots = false;
         socialIgnoreLight = false;
         socialGhost = false;
         armorEffectDrawShadow = false;
         armorEffectDrawShadowSubtle = false;
         armorEffectDrawOutlines = false;
         armorEffectDrawShadowLokis = false;
         armorEffectDrawShadowBasilisk = false;
         armorEffectDrawOutlinesForbidden = false;
         armorEffectDrawShadowEOCShield = false;
         if (!isDisplayDollOrInanimate)
         {
             if (head == 101 && body == 66 && legs == 55)
             {
                 socialGhost = true;
             }
             if (head == 156 && body == 66 && legs == 55)
             {
                 socialGhost = true;
             }
             SetArmorEffectVisuals(this);
         }
         hermesStepSound.SoundType = 17;
         hermesStepSound.SoundStyle = -1;
         hermesStepSound.IntendedCooldown = 9;
         if (head == 99 && body == 65 && legs == 54)
         {
             turtleArmor = true;
         }
         if (head == 162 && body == 170 && legs == 105)
         {
             spiderArmor = true;
         }
         ApplyArmorSoundAndDustChanges();
         if (legs == 140)
         {
             hermesStepSound.SoundType = 2;
             hermesStepSound.SoundStyle = 24;
             hermesStepSound.IntendedCooldown = 6;
         }
         if (flag)
         {
             face = -1;
             faceFlower = -1;
             faceHead = -1;
         }
         if (head > 0 && face > 0)
         {
             if (ArmorIDs.Face.Sets.OverrideHelmet[face])
             {
                 head = -1;
                 faceHead = -1;
             }
             else if (!ArmorIDs.Face.Sets.DrawInFaceUnderHairLayer[face])
             {
                 face = -1;
             }
         }
         if (head > 0 && faceHead > 0 && ArmorIDs.Head.Sets.UseAltFaceHeadDraw[head])
         {
             sbyte b3 = (sbyte)ArmorIDs.Face.Sets.AltFaceHead[faceHead];
             if (b3 > 0)
             {
                 faceHead = b3;
             }
         }
         if (webbed || frozen || stoned || (Main.gamePaused && !Main.gameMenu))
         {
             return;
         }
         if (head == 267 && body == 236 && (legs == 219 || legs == 220) && miscCounter % 15 == 0 && Main.rand.Next(3) == 0)
         {
             Vector2 center = base.Center;
             float num2 = 1f + Main.rand.NextFloat() * 0.5f;
             if (Main.rand.Next(2) == 0)
             {
                 num2 *= -1f;
             }
             center += new Vector2(num2 * -25f, -8f);
             Dust obj = Main.dust[Dust.NewDust(center, 2, 2, 304, 0f, 0f, 100)];
             obj.rotation = Main.rand.NextFloat() * ((float)Math.PI * 2f);
             obj.alpha = 254;
             obj.velocity.X = num2 * 0.2f;
             obj.noGravity = true;
             obj.customData = this;
             obj.shader = GameShaders.Armor.GetSecondaryShader(cBody, this);
         }
         if (!isDisplayDollOrInanimate)
         {
             if (((body == 68 && legs == 57 && head == 106) || (body == 74 && legs == 63 && head == 106)) && Main.rand.Next(10) == 0)
             {
                 int num3 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 43, 0f, 0f, 100, new Color(255, 0, 255), 0.3f);
                 Main.dust[num3].fadeIn = 0.8f;
                 Main.dust[num3].noGravity = true;
                 Main.dust[num3].velocity *= 2f;
                 Main.dust[num3].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
             }
             if (wings == 27 && wingsLogic == wings)
             {
                 float num4 = 0.4f * stealth;
                 Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, num4, num4 * 0.9f, num4 * 0.2f);
             }
             if (head == 5 && body == 5 && legs == 5)
             {
                 socialShadowRocketBoots = true;
             }
             if (head == 5 && body == 5 && legs == 5 && Main.rand.Next(10) == 0)
             {
                 int num5 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 14, 0f, 0f, 200, default(Color), 1.2f);
                 Main.dust[num5].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
             }
             if (head == 76 && body == 49 && legs == 45)
             {
                 socialShadowRocketBoots = true;
             }
             if (head == 74 && body == 48 && legs == 44)
             {
                 socialShadowRocketBoots = true;
             }
             if (head == 74 && body == 48 && legs == 44 && Main.rand.Next(10) == 0)
             {
                 int num6 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 14, 0f, 0f, 200, default(Color), 1.2f);
                 Main.dust[num6].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
             }
             if (head == 57 && body == 37 && legs == 35)
             {
                 int maxValue = 10;
                 if (Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 1f)
                 {
                     maxValue = 2;
                 }
                 if (Main.rand.Next(maxValue) == 0)
                 {
                     int num7 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 115, 0f, 0f, 140, default(Color), 0.75f);
                     Main.dust[num7].noGravity = true;
                     Main.dust[num7].fadeIn = 1.5f;
                     Main.dust[num7].velocity *= 0.3f;
                     Main.dust[num7].velocity += velocity * 0.2f;
                     Main.dust[num7].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                 }
             }
             if (head == 6 && body == 6 && legs == 6 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 1f && !rocketFrame)
             {
                 for (int i = 0; i < 2; i++)
                 {
                     int num8 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 6, 0f, 0f, 100, default(Color), 2f);
                     Main.dust[num8].noGravity = true;
                     Main.dust[num8].noLight = true;
                     Main.dust[num8].velocity.X -= velocity.X * 0.5f;
                     Main.dust[num8].velocity.Y -= velocity.Y * 0.5f;
                     Main.dust[num8].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                 }
             }
             if (head == 8 && body == 8 && legs == 8 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 1f)
             {
                 int num9 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 40, 0f, 0f, 50, default(Color), 1.4f);
                 Main.dust[num9].noGravity = true;
                 Main.dust[num9].velocity.X = velocity.X * 0.25f;
                 Main.dust[num9].velocity.Y = velocity.Y * 0.25f;
                 Main.dust[num9].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
             }
             if (head == 9 && body == 9 && legs == 9 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 1f && !rocketFrame)
             {
                 for (int j = 0; j < 2; j++)
                 {
                     int num10 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 6, 0f, 0f, 100, default(Color), 2f);
                     Main.dust[num10].noGravity = true;
                     Main.dust[num10].noLight = true;
                     Main.dust[num10].velocity.X -= velocity.X * 0.5f;
                     Main.dust[num10].velocity.Y -= velocity.Y * 0.5f;
                     Main.dust[num10].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                 }
             }
             if (body == 18 && legs == 17 && (head == 32 || head == 33 || head == 34) && Main.rand.Next(10) == 0)
             {
                 int num11 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 43, 0f, 0f, 100, default(Color), 0.3f);
                 Main.dust[num11].fadeIn = 0.8f;
                 Main.dust[num11].velocity *= 0f;
                 Main.dust[num11].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
             }
             if ((body == 24 || body == 229) && (legs == 23 || legs == 212) && (head == 43 || head == 41 || head == 42 || head == 254 || head == 255 || head == 256 || head == 257 || head == 258) && velocity.X != 0f && velocity.Y != 0f && Main.rand.Next(10) == 0)
             {
                 int num12 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 43, 0f, 0f, 100, default(Color), 0.3f);
                 Main.dust[num12].fadeIn = 0.8f;
                 Main.dust[num12].velocity *= 0f;
                 Main.dust[num12].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
             }
             if (body == 36 && head == 56 && velocity.X != 0f && velocity.Y == 0f)
             {
                 for (int k = 0; k < 2; k++)
                 {
                     int num13 = Dust.NewDust(new Vector2(position.X, position.Y + (float)((gravDir == 1f) ? (height - 2) : (-4))), width, 6, 106, 0f, 0f, 100, default(Color), 0.1f);
                     Main.dust[num13].fadeIn = 1f;
                     Main.dust[num13].noGravity = true;
                     Main.dust[num13].velocity *= 0.2f;
                     Main.dust[num13].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                 }
             }
             if (body == 27 && head == 46 && legs == 26 && velocity.X != 0f && velocity.Y == 0f && miscCounter % 2 == 0)
             {
                 for (int l = 0; l < 2; l++)
                 {
                     int num14 = ((l != 0) ? Dust.NewDust(new Vector2(position.X + (float)(width / 2), position.Y + (float)height + gfxOffY), width / 2, 6, 76, 0f, 0f, 0, default(Color), 1.35f) : Dust.NewDust(new Vector2(position.X, position.Y + (float)height + gfxOffY), width / 2, 6, 76, 0f, 0f, 0, default(Color), 1.35f));
                     Main.dust[num14].scale *= 1f + (float)Main.rand.Next(20, 40) * 0.01f;
                     Main.dust[num14].noGravity = true;
                     Main.dust[num14].noLight = true;
                     Main.dust[num14].velocity *= 0.001f;
                     Main.dust[num14].velocity.Y -= 0.003f;
                     Main.dust[num14].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                 }
             }
         }
         drawingFootball = false;
         if (ShouldDrawFootball())
         {
             SetCompositeArmBack(enabled: true, CompositeArmStretchAmount.Full, (float)Math.PI / 10f * (float)direction * -1f);
             drawingFootball = true;
         }
         Item.GetDrawHitbox(HeldItem.type, this);
         bool flag3 = CanVisuallyHoldItem(HeldItem);
         bool flag4 = HeldItem.type != 4952;
         if (mount.Active)
         {
             legFrameCounter = 0.0;
             legFrame.Y = legFrame.Height * 6;
             if (mount.Type == 23 || mount.Type == 45 || mount.Type == 48)
             {
                 ref Rectangle reference = ref legFrame;
                 _ = legFrame;
                 reference.Y = 0;
             }
             if (velocity.Y != 0f)
             {
                 if (mount.FlyTime > 0 && jump == 0 && controlJump && !mount.CanHover())
                 {
                     if (mount.Type == 0)
                     {
                         if (direction > 0)
{
                             if (Main.rand.Next(4) == 0)
{
                                 int num15 = Dust.NewDust(new Vector2(base.Center.X - 22f, position.Y + (float)height - 6f), 20, 10, 64, velocity.X * 0.25f, velocity.Y * 0.25f, 255);
                                 Main.dust[num15].velocity *= 0.1f;
                                 Main.dust[num15].noLight = true;
                             }
                             if (Main.rand.Next(4) == 0)
{
                                 int num16 = Dust.NewDust(new Vector2(base.Center.X + 12f, position.Y + (float)height - 6f), 20, 10, 64, velocity.X * 0.25f, velocity.Y * 0.25f, 255);
                                 Main.dust[num16].velocity *= 0.1f;
                                 Main.dust[num16].noLight = true;
                             }
                         }
                         else
{
                             if (Main.rand.Next(4) == 0)
{
                                 int num17 = Dust.NewDust(new Vector2(base.Center.X - 32f, position.Y + (float)height - 6f), 20, 10, 64, velocity.X * 0.25f, velocity.Y * 0.25f, 255);
                                 Main.dust[num17].velocity *= 0.1f;
                                 Main.dust[num17].noLight = true;
                             }
                             if (Main.rand.Next(4) == 0)
{
                                 int num18 = Dust.NewDust(new Vector2(base.Center.X + 2f, position.Y + (float)height - 6f), 20, 10, 64, velocity.X * 0.25f, velocity.Y * 0.25f, 255);
                                 Main.dust[num18].velocity *= 0.1f;
                                 Main.dust[num18].noLight = true;
                             }
                         }
                     }
                     mount.TryBeginningFlight(this, 3);
                     mount.UpdateFrame(this, 3, velocity);
                     mount.TryLanding(this);
                 }
                 else if (wet)
                 {
                     mount.UpdateFrame(this, 4, velocity);
                 }
                 else
                 {
                     mount.TryBeginningFlight(this, 2);
                     mount.UpdateFrame(this, 2, velocity);
                     mount.TryLanding(this);
                 }
             }
             else
             {
                 mount.UpdateFrame(this, mount.GetIntendedGroundedFrame(this), velocity);
             }
         }
         else if (legs != 140)
         {
             if (swimTime > 0)
             {
                 legFrameCounter += 2.0;
                 while (legFrameCounter > 8.0)
                 {
                     legFrameCounter -= 8.0;
                     legFrame.Y += legFrame.Height;
                 }
                 if (legFrame.Y < legFrame.Height * 7)
                 {
                     legFrame.Y = legFrame.Height * 19;
                 }
                 else if (legFrame.Y > legFrame.Height * 19)
                 {
                     legFrame.Y = legFrame.Height * 7;
                 }
             }
             else if (velocity.Y != 0f || grappling[0] > -1)
             {
                 legFrameCounter = 0.0;
                 legFrame.Y = legFrame.Height * 5;
                 if ((wings == 22 || wings == 28 || wings == 45) && ShouldDrawWingsThatAreAlwaysAnimated())
                 {
                     legFrame.Y = 0;
                 }
             }
             else if (velocity.X != 0f)
             {
                 if ((slippy || slippy2 || windPushed) && !controlLeft && !controlRight)
                 {
                     legFrameCounter = 0.0;
                     ref Rectangle reference2 = ref legFrame;
                     _ = legFrame;
                     reference2.Y = 0;
                 }
                 else
                 {
                     legFrameCounter += (double)Math.Abs(velocity.X) * 1.3;
                     while (legFrameCounter > 8.0)
                     {
                         legFrameCounter -= 8.0;
                         legFrame.Y += legFrame.Height;
                     }
                     if (legFrame.Y < legFrame.Height * 7)
                     {
                         legFrame.Y = legFrame.Height * 19;
                     }
                     else if (legFrame.Y > legFrame.Height * 19)
                     {
                         legFrame.Y = legFrame.Height * 7;
                     }
                 }
             }
             else
             {
                 legFrameCounter = 0.0;
                 ref Rectangle reference3 = ref legFrame;
                 _ = legFrame;
                 reference3.Y = 0;
             }
         }
         if (carpetFrame >= 0)
         {
             legFrameCounter = 0.0;
             ref Rectangle reference4 = ref legFrame;
             _ = legFrame;
             reference4.Y = 0;
         }
         if (sandStorm)
         {
             if (grappling[0] >= 0)
             {
                 sandStorm = false;
             }
             if (miscCounter % 4 == 0 && itemAnimation == 0)
             {
                 ChangeDir(direction * -1);
                 if (inventory[selectedItem].holdStyle == 2)
                 {
                     if (inventory[selectedItem].type == 946 || inventory[selectedItem].type == 4707)
                     {
                         itemLocation.X = position.X + (float)width * 0.5f - (float)(16 * direction);
                     }
                     if (inventory[selectedItem].type == 186)
                     {
                         itemLocation.X = position.X + (float)width * 0.5f + (float)(6 * direction);
                         itemRotation = 0.79f * (float)(-direction);
                     }
                 }
             }
             legFrameCounter = 0.0;
             ref Rectangle reference5 = ref legFrame;
             _ = legFrame;
             reference5.Y = 0;
         }
         else if (itemAnimation > 0 && inventory[selectedItem].useStyle != 10 && flag4)
         {
             if (inventory[selectedItem].useStyle == 1 || inventory[selectedItem].type == 0)
             {
                 if ((double)itemAnimation < (double)itemAnimationMax * 0.333)
                 {
                     bodyFrame.Y = bodyFrame.Height * 3;
                 }
                 else if ((double)itemAnimation < (double)itemAnimationMax * 0.666)
                 {
                     bodyFrame.Y = bodyFrame.Height * 2;
                 }
                 else
                 {
                     bodyFrame.Y = bodyFrame.Height;
                 }
             }
             else if (inventory[selectedItem].useStyle == 7)
             {
                 if ((double)itemAnimation > (double)itemAnimationMax * 0.5)
                 {
                     bodyFrame.Y = bodyFrame.Height * 3;
                 }
                 else
                 {
                     bodyFrame.Y = bodyFrame.Height * 2;
                 }
             }
             else if (inventory[selectedItem].useStyle == 2)
             {
                 bodyFrame.Y = bodyFrame.Height * 3;
             }
             else if (inventory[selectedItem].useStyle == 11)
             {
                 if ((double)itemAnimation > (double)itemAnimationMax * 0.5)
                 {
                     bodyFrame.Y = bodyFrame.Height * 4;
                 }
                 else if ((double)itemAnimation > (double)itemAnimationMax * 0.15)
                 {
                     bodyFrame.Y = bodyFrame.Height * 3;
                 }
                 else
                 {
                     bodyFrame.Y = bodyFrame.Height * 2;
                 }
             }
             else if (inventory[selectedItem].useStyle == 9)
             {
                 bodyFrame.Y = 0;
             }
             else if (inventory[selectedItem].useStyle == 6)
             {
                 float num19 = 1f - (float)itemAnimation / (float)itemAnimationMax;
                 num19 *= 6f;
                 if (num19 > 1f)
                 {
                     num19 = 1f;
                 }
                 if (num19 >= 0.5f)
                 {
                     bodyFrame.Y = bodyFrame.Height * 3;
                 }
                 else
                 {
                     bodyFrame.Y = bodyFrame.Height * 2;
                 }
             }
             else if (inventory[selectedItem].useStyle == 3)
             {
                 if ((double)itemAnimation > (double)itemAnimationMax * 0.666)
                 {
                     bodyFrame.Y = bodyFrame.Height * 3;
                 }
                 else
                 {
                     bodyFrame.Y = bodyFrame.Height * 3;
                 }
             }
             else if (inventory[selectedItem].useStyle == 4)
             {
                 bodyFrame.Y = bodyFrame.Height * 2;
             }
             else if (inventory[selectedItem].useStyle == 8)
             {
                 bodyFrame.Y = 0;
             }
             else if (inventory[selectedItem].useStyle == 12)
             {
                 bodyFrame.Y = bodyFrame.Height * 3;
             }
             else if (inventory[selectedItem].useStyle == 13)
             {
                 if ((double)itemAnimation < (double)itemAnimationMax * 0.333)
                 {
                     bodyFrame.Y = bodyFrame.Height * 3;
                 }
                 else if ((double)itemAnimation < (double)itemAnimationMax * 0.666)
                 {
                     bodyFrame.Y = bodyFrame.Height * 2;
                 }
                 else
                 {
                     bodyFrame.Y = bodyFrame.Height;
                 }
             }
             else if (inventory[selectedItem].useStyle == 5)
             {
                 if (inventory[selectedItem].type == 281 || inventory[selectedItem].type == 986)
                 {
                     bodyFrame.Y = bodyFrame.Height * 2;
                 }
                 else
                 {
                     float num20 = itemRotation * (float)direction;
                     bodyFrame.Y = bodyFrame.Height * 3;
                     if ((double)num20 < -0.75)
                     {
                         bodyFrame.Y = bodyFrame.Height * 2;
                         if (gravDir == -1f)
{
                             bodyFrame.Y = bodyFrame.Height * 4;
                         }
                     }
                     if ((double)num20 > 0.6)
                     {
                         bodyFrame.Y = bodyFrame.Height * 4;
                         if (gravDir == -1f)
{
                             bodyFrame.Y = bodyFrame.Height * 2;
                         }
                     }
                 }
             }
         }
         else if (pulley)
         {
             if (pulleyDir == 2)
             {
                 bodyFrame.Y = bodyFrame.Height;
             }
             else
             {
                 bodyFrame.Y = bodyFrame.Height * 2;
             }
         }
         else if (flag3 && inventory[selectedItem].holdStyle == 1 && (!wet || !inventory[selectedItem].noWet) && (!happyFunTorchTime || inventory[selectedItem].createTile != 4))
         {
             bodyFrame.Y = bodyFrame.Height * 3;
         }
         else if (flag3 && inventory[selectedItem].holdStyle == 2 && (!wet || !inventory[selectedItem].noWet))
         {
             bodyFrame.Y = bodyFrame.Height * 2;
         }
         else if (flag3 && inventory[selectedItem].holdStyle == 3)
         {
             bodyFrame.Y = bodyFrame.Height * 3;
         }
         else if (flag3 && inventory[selectedItem].holdStyle == 5)
         {
             bodyFrame.Y = bodyFrame.Height * 3;
         }
         else if (flag3 && inventory[selectedItem].holdStyle == 7)
         {
             bodyFrame.Y = bodyFrame.Height * 11;
         }
         else if (flag3 && inventory[selectedItem].holdStyle == 4 && velocity.Y == 0f && gravDir == 1f)
         {
             ref Rectangle reference6 = ref bodyFrame;
             _ = bodyFrame;
             reference6.Y = 0;
         }
         else if (shieldRaised)
         {
             bodyFrame.Y = bodyFrame.Height * 10;
         }
         else if (mount.Active)
         {
             bodyFrameCounter = 0.0;
             bodyFrame.Y = bodyFrame.Height * mount.BodyFrame;
         }
         else if (grappling[0] >= 0)
         {
             sandStorm = false;
             CancelAllJumpVisualEffects();
             Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num21 = 0f;
             float num22 = 0f;
             for (int m = 0; m < grapCount; m++)
             {
                 num21 += Main.projectile[grappling[m]].position.X + (float)(Main.projectile[grappling[m]].width / 2);
                 num22 += Main.projectile[grappling[m]].position.Y + (float)(Main.projectile[grappling[m]].height / 2);
             }
             num21 /= (float)grapCount;
             num22 /= (float)grapCount;
             num21 -= vector.X;
             num22 -= vector.Y;
             if (num22 < 0f && Math.Abs(num22) > Math.Abs(num21))
             {
                 bodyFrame.Y = bodyFrame.Height * 2;
                 if (gravDir == -1f)
                 {
                     bodyFrame.Y = bodyFrame.Height * 4;
                 }
             }
             else if (num22 > 0f && Math.Abs(num22) > Math.Abs(num21))
             {
                 bodyFrame.Y = bodyFrame.Height * 4;
                 if (gravDir == -1f)
                 {
                     bodyFrame.Y = bodyFrame.Height * 2;
                 }
             }
             else
             {
                 bodyFrame.Y = bodyFrame.Height * 3;
             }
         }
         else if (wet && ShouldFloatInWater)
         {
             bodyFrame.Y = bodyFrame.Height * 10;
         }
         else if (swimTime > 0)
         {
             if (swimTime > 20)
             {
                 ref Rectangle reference7 = ref bodyFrame;
                 _ = bodyFrame;
                 reference7.Y = 0;
             }
             else if (swimTime > 10)
             {
                 bodyFrame.Y = bodyFrame.Height * 5;
             }
             else
             {
                 ref Rectangle reference8 = ref bodyFrame;
                 _ = bodyFrame;
                 reference8.Y = 0;
             }
         }
         else if (velocity.Y != 0f)
         {
             if (sliding)
             {
                 bodyFrame.Y = bodyFrame.Height * 3;
             }
             else if (sandStorm || carpetFrame >= 0)
             {
                 bodyFrame.Y = bodyFrame.Height * 6;
             }
             else if (eocDash > 0)
             {
                 bodyFrame.Y = bodyFrame.Height * 6;
             }
             else if (wings > 0)
             {
                 if (wings == 22 || wings == 28 || wings == 45)
                 {
                     bodyFrame.Y = 0;
                 }
                 else if (velocity.Y > 0f)
                 {
                     if (controlJump)
                     {
                         bodyFrame.Y = bodyFrame.Height * 6;
                     }
                     else
                     {
                         bodyFrame.Y = bodyFrame.Height * 5;
                     }
                 }
                 else
                 {
                     bodyFrame.Y = bodyFrame.Height * 6;
                 }
             }
             else
             {
                 bodyFrame.Y = bodyFrame.Height * 5;
             }
             bodyFrameCounter = 0.0;
         }
         else if (velocity.X != 0f)
         {
             if (legs == 140)
             {
                 bodyFrameCounter += Math.Abs(velocity.X) * 0.5f;
                 while (bodyFrameCounter > 8.0)
                 {
                     bodyFrameCounter -= 8.0;
                     bodyFrame.Y += bodyFrame.Height;
                 }
                 if (bodyFrame.Y < bodyFrame.Height * 7)
                 {
                     bodyFrame.Y = bodyFrame.Height * 19;
                 }
                 else if (bodyFrame.Y > bodyFrame.Height * 19)
                 {
                     bodyFrame.Y = bodyFrame.Height * 7;
                 }
             }
             else
             {
                 bodyFrameCounter += (double)Math.Abs(velocity.X) * 1.5;
                 bodyFrame.Y = legFrame.Y;
             }
         }
         else
         {
             bodyFrameCounter = 0.0;
             ref Rectangle reference9 = ref bodyFrame;
             _ = bodyFrame;
             reference9.Y = 0;
         }
         if (legs == 140)
         {
             legFrameCounter = 0.0;
             legFrame.Y = legFrame.Height * (velocity.Y != 0f).ToInt();
             int num23 = bodyFrame.Y / bodyFrame.Height;
             if (Main.OffsetsPlayerHeadgear[num23].Y == 0f)
             {
                 legFrame.Y = legFrame.Height * 7;
             }
             if (wings == 22 || wings == 28)
             {
                 legFrame.Y = 0;
             }
         }
         if (legs == 217 && (sitting.isSitting || sleeping.isSleeping))
         {
             legFrameCounter = 0.0;
             legFrame.Y = legFrame.Height * 5;
         }
         if (head == 259 && !skipAnimatingValuesInPlayerFrame)
         {
             rabbitOrderFrame.Update();
         }
     }
References Lighting.AddLight(), Dust.alpha, ArmorIDs.Face.Sets.AltFaceHead, GameShaders.Armor, Player.SetMatchRequest.ArmorSlotRequested, Player.SetMatchRequest.Body, Color, Dust.customData, ArmorIDs.Body.Sets.DisableBeltAccDraw, ArmorIDs.Body.Sets.DisableHandOnAndOffAccDraw, ArmorIDs.Back.Sets.DrawInBackpackLayer, ArmorIDs.Face.Sets.DrawInFaceUnderHairLayer, ArmorIDs.Back.Sets.DrawInTailLayer, Main.dust, Dust.fadeIn, ArmorIDs.Body.Sets.IncludeCapeFrontAndBackInfo.frontCape, Main.gameMenu, Main.gamePaused, Item.GetDrawHitbox(), ArmorShaderDataSet.GetSecondaryShader(), Player.SetMatchRequest.Head, Entity.height, ArmorIDs.Body.Sets.IncludeCapeFrontAndBack, ArmorIDs.Body.Sets.IncludedCapeBack, ArmorIDs.Body.Sets.IncludedCapeBackFemale, ArmorIDs.Body.Sets.IncludedCapeFront, ArmorIDs.Waist.Sets.IsABelt, Player.SetMatchRequest.Legs, Player.SetMatchRequest.Male, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.OffsetsPlayerHeadgear, ArmorIDs.Face.Sets.OverrideHelmet, Entity.position, Main.projectile, Main.rand, Dust.rotation, Dust.scale, Dust.shader, Item.type, ArmorIDs.Head.Sets.UseAltFaceHeadDraw, Dust.velocity, and Entity.width.
Referenced by UICharacter.UICharacter(), TEDisplayDoll.Draw(), TEHatRack.Draw(), Segments.PlayerSegment.Draw(), Main.DrawClothesWindow(), Main.DrawMenu(), LegacyPlayerRenderer.DrawPlayerFull(), Main.DrawSuperSpecialProjectiles(), LoadPlayer(), and UICharacter.Update().