Terraria: Player.SporeSac
SporeSac()
void Player.SporeSac (Item sourceItem) inline
     {
         int damage = 70;
         float knockBack = 1.5f;
         if (Main.rand.Next(15) != 0)
         {
             return;
         }
         int num = 0;
         for (int i = 0; i < 1000; i++)
         {
             if (Main.projectile[i].active && Main.projectile[i].owner == whoAmI && (Main.projectile[i].type == 567 || Main.projectile[i].type == 568))
             {
                 num++;
             }
         }
         if (Main.rand.Next(15) < num || num >= 10)
         {
             return;
         }
         int num2 = 50;
         int num3 = 24;
         int num4 = 90;
         for (int j = 0; j < num2; j++)
         {
             int num5 = Main.rand.Next(200 - j * 2, 400 + j * 2);
             Vector2 center = base.Center;
             center.X += Main.rand.Next(-num5, num5 + 1);
             center.Y += Main.rand.Next(-num5, num5 + 1);
             if (Collision.SolidCollision(center, num3, num3) || Collision.WetCollision(center, num3, num3))
             {
                 continue;
             }
             center.X += num3 / 2;
             center.Y += num3 / 2;
             if (!Collision.CanHit(new Vector2(base.Center.X, position.Y), 1, 1, center, 1, 1) && !Collision.CanHit(new Vector2(base.Center.X, position.Y - 50f), 1, 1, center, 1, 1))
             {
                 continue;
             }
             int num6 = (int)center.X / 16;
             int num7 = (int)center.Y / 16;
             bool flag = false;
             if (Main.rand.Next(3) == 0 && Main.tile[num6, num7] != null && Main.tile[num6, num7].wall > 0)
             {
                 flag = true;
             }
             else
             {
                 center.X -= num4 / 2;
                 center.Y -= num4 / 2;
                 if (Collision.SolidCollision(center, num4, num4))
                 {
                     center.X += num4 / 2;
                     center.Y += num4 / 2;
                     flag = true;
                 }
                 else if (Main.tile[num6, num7] != null && Main.tile[num6, num7].active() && Main.tile[num6, num7].type == 19)
                 {
                     flag = true;
                 }
             }
             if (!flag)
             {
                 continue;
             }
             for (int k = 0; k < 1000; k++)
             {
                 if (Main.projectile[k].active && Main.projectile[k].owner == whoAmI && Main.projectile[k].aiStyle == 105 && (center - Main.projectile[k].Center).Length() < 48f)
                 {
                     flag = false;
                     break;
                 }
             }
             if (flag && Main.myPlayer == whoAmI)
             {
                 Projectile.NewProjectile(GetProjectileSource_Accessory(sourceItem), center.X, center.Y, 0f, 0f, 567 + Main.rand.Next(2), damage, knockBack, whoAmI);
                 break;
             }
         }
     }
References Entity.active, Tile.active(), Projectile.aiStyle, Collision.CanHit(), Entity.Center, Main.myPlayer, Projectile.NewProjectile(), UnifiedRandom.Next(), Projectile.owner, Main.projectile, Main.rand, Collision.SolidCollision(), Main.tile, Projectile.type, Tile.type, Tile.wall, and Collision.WetCollision().