Terraria: Player.ItemCheck_UsePeddlersSatchel
ItemCheck_UsePeddlersSatchel()
void Player.ItemCheck_UsePeddlersSatchel (Item sItem) inline private
     {
         if (!NPC.peddlersSatchelWasUsed && sItem.type == 5343 && itemAnimation > 0 && ItemTimeIsZero)
         {
             ApplyItemTime(sItem);
             if (Main.netMode == 0)
             {
                 NPC.peddlersSatchelWasUsed = true;
                 Main.NewText(Language.GetTextValue("Misc.PeddlersSatchelUsed"), 50, byte.MaxValue, 130);
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, -18f);
             }
         }
     }
References Language.GetTextValue(), Main.netMode, Main.NewText(), NPC.peddlersSatchelWasUsed, NetMessage.SendData(), and Item.type.