Terraria: Player.ApplyWilsonBeard
ApplyWilsonBeard()
void Player.ApplyWilsonBeard (Item currentItem) inline private
     {
         beardGrowthTimer++;
         if (beardGrowthTimer >= 43200 && Main.rand.Next(540) == 0)
         {
             beardGrowthTimer = 0;
             short defaults = 5105;
             if (currentItem.type == 5105)
             {
                 defaults = 5106;
             }
             SoundEngine.PlaySound(SoundID.Item60, base.Center);
             currentItem.SetDefaults(defaults);
         }
     }
References SoundID.Item60, UnifiedRandom.Next(), SoundEngine.PlaySound(), Main.rand, Item.SetDefaults(), and Item.type.