Terraria: Player.SetTalkNPC
SetTalkNPC()
void Player.SetTalkNPC (int npcIndex, bool fromNet = false) inline
     {
         talkNPC = npcIndex;
         if (Main.netMode != 1 && npcIndex >= 0 && npcIndex < 200)
         {
             Main.BestiaryTracker.Chats.RegisterChatStartWith(Main.npc[npcIndex]);
         }
         if (talkNPC == -1)
         {
             currentShoppingSettings = ShoppingSettings.NotInShop;
         }
         else
         {
             currentShoppingSettings = Main.ShopHelper.GetShoppingSettings(this, Main.npc[talkNPC]);
         }
         if (currentShoppingSettings.PriceAdjustment <= 0.8199999928474426)
         {
             AchievementsHelper.HandleSpecialEvent(this, 20);
         }
     }
References Main.BestiaryTracker, BestiaryUnlocksTracker.Chats, ShopHelper.GetShoppingSettings(), AchievementsHelper.HandleSpecialEvent(), Main.netMode, ShoppingSettings.NotInShop, Main.npc, NPCWasChatWithTracker.RegisterChatStartWith(), and Main.ShopHelper.
Referenced by NPC.AI_000_TransformBoundNPC(), Main.BuyHairWindow(), Main.CancelHairWindow(), Main.CloseNPCChatOrSign(), Main.DrawBestiaryIcon(), Main.DrawEmoteBubblesButton(), Main.DrawInventory(), MessageBuffer.GetData(), Main.HoverOverNPCs(), TileEntity.SetInteractionAnchor(), Main.TryInteractingWithMoneyTrough(), Main.TryInteractingWithMoneyTrough2(), and Main.TryInteractingWithVoidLens().