Terraria: Player.ItemCheck_UseEventItems
ItemCheck_UseEventItems()
void Player.ItemCheck_UseEventItems (Item sItem) inline private
     {
         if (ItemTimeIsZero && itemAnimation > 0 && sItem.type == 361 && Main.CanStartInvasion(1, ignoreDelay: true))
         {
             ApplyItemTime(sItem);
             SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             if (Main.netMode != 1)
             {
                 if (Main.invasionType == 0)
                 {
                     Main.invasionDelay = 0;
                     Main.StartInvasion();
                 }
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, -1f);
             }
         }
         if (ItemTimeIsZero && itemAnimation > 0 && sItem.type == 602 && Main.CanStartInvasion(2, ignoreDelay: true))
         {
             ApplyItemTime(sItem);
             SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             if (Main.netMode != 1)
             {
                 if (Main.invasionType == 0)
                 {
                     Main.invasionDelay = 0;
                     Main.StartInvasion(2);
                 }
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, -2f);
             }
         }
         if (ItemTimeIsZero && itemAnimation > 0 && sItem.type == 1315 && Main.CanStartInvasion(3, ignoreDelay: true))
         {
             ApplyItemTime(sItem);
             SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             if (Main.netMode != 1)
             {
                 if (Main.invasionType == 0)
                 {
                     Main.invasionDelay = 0;
                     Main.StartInvasion(3);
                 }
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, -3f);
             }
         }
         if (ItemTimeIsZero && itemAnimation > 0 && sItem.type == 1844 && !Main.dayTime && !Main.pumpkinMoon && !Main.snowMoon && !DD2Event.Ongoing)
         {
             ApplyItemTime(sItem);
             SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             if (Main.netMode != 1)
             {
                 Main.NewText(Lang.misc[31].Value, 50, byte.MaxValue, 130);
                 Main.startPumpkinMoon();
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, -4f);
             }
         }
         if (ItemTimeIsZero && itemAnimation > 0 && sItem.type == 2767 && Main.dayTime && !Main.eclipse)
         {
             SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             ApplyItemTime(sItem);
             if (Main.netMode == 0)
             {
                 Main.eclipse = true;
                 if (Main.remixWorld)
                 {
                     Main.NewText(Lang.misc[106].Value, 50, byte.MaxValue, 130);
                 }
                 else
                 {
                     Main.NewText(Lang.misc[20].Value, 50, byte.MaxValue, 130);
                 }
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, -6f);
             }
         }
         if (ItemTimeIsZero && itemAnimation > 0 && sItem.type == 4271 && !Main.dayTime && !Main.bloodMoon)
         {
             SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             ApplyItemTime(sItem);
             if (Main.netMode == 0)
             {
                 AchievementsHelper.NotifyProgressionEvent(4);
                 Main.bloodMoon = true;
                 if (Main.GetMoonPhase() == MoonPhase.Empty)
                 {
                     Main.moonPhase = 5;
                 }
                 Main.NewText(Lang.misc[8].Value, 50, byte.MaxValue, 130);
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, -10f);
             }
         }
         if (ItemTimeIsZero && itemAnimation > 0 && sItem.type == 3601 && NPC.downedGolemBoss && Main.hardMode && !NPC.AnyDanger() && !NPC.AnyoneNearCultists())
         {
             SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             ApplyItemTime(sItem);
             if (Main.netMode == 0)
             {
                 WorldGen.StartImpendingDoom(720);
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, -8f);
             }
         }
         if (ItemTimeIsZero && itemAnimation > 0 && sItem.type == 1958 && !Main.dayTime && !Main.pumpkinMoon && !Main.snowMoon && !DD2Event.Ongoing)
         {
             ApplyItemTime(sItem);
             SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             if (Main.netMode != 1)
             {
                 Main.NewText(Lang.misc[34].Value, 50, byte.MaxValue, 130);
                 Main.startSnowMoon();
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, -5f);
             }
         }
     }
References NPC.AnyDanger(), NPC.AnyoneNearCultists(), Main.bloodMoon, Main.CanStartInvasion(), Main.dayTime, NPC.downedGolemBoss, Main.eclipse, Main.GetMoonPhase(), Main.hardMode, Main.invasionDelay, Main.invasionType, Lang.misc, Main.moonPhase, Main.netMode, Main.NewText(), AchievementsHelper.NotifyProgressionEvent(), DD2Event.Ongoing, SoundEngine.PlaySound(), Main.pumpkinMoon, Main.remixWorld, NetMessage.SendData(), Main.snowMoon, WorldGen.StartImpendingDoom(), Main.StartInvasion(), Main.startPumpkinMoon(), Main.startSnowMoon(), Item.type, and LocalizedText.Value.