Terraria: Player.CanSnapToPosition
CanSnapToPosition()
bool Player.CanSnapToPosition (Vector2 offset) inline
     {
         if (Collision.SolidCollision(position + offset, width, height))
         {
             return false;
         }
         bool canSnapToPosition = Collision.CanHit(position, width, height, position + offset, width, height);
         if (!canSnapToPosition)
         {
             TryAllowingSnappingToPosition(ref canSnapToPosition, position, position + offset);
             if (!canSnapToPosition)
             {
                 int num = Math.Sign(offset.X);
                 if (num != 0)
                 {
                     Vector2 vector = new Vector2(num * width, 0f);
                     if (Collision.TileCollision(position, vector, width, height, fallThrough: true, fall2: true, (int)gravDir) == vector)
                     {
                         TryAllowingSnappingToPosition(ref canSnapToPosition, position + vector, position + offset);
                     }
                 }
             }
         }
         return canSnapToPosition;
     }
References Collision.CanHit(), Collision.SolidCollision(), and Collision.TileCollision().
Referenced by PlayerSittingHelper.SitDown(), and PlayerSleepingHelper.StartSleeping().