Terraria: Player.Update_NPCCollision
Update_NPCCollision()
void Player.Update_NPCCollision () inline
     {
         if (creativeGodMode)
         {
             return;
         }
         Rectangle rectangle = new Rectangle((int)position.X, (int)position.Y, width, height);
         for (int i = 0; i < 200; i++)
         {
             if (!Main.npc[i].active || Main.npc[i].friendly || Main.npc[i].damage <= 0)
             {
                 continue;
             }
             int specialHitSetter = -1;
             switch (Main.npc[i].type)
             {
             case 396:
             case 397:
             case 398:
             case 400:
             case 401:
                 specialHitSetter = 1;
                 break;
             case 636:
                 specialHitSetter = 1;
                 if (Main.npc[i].ai[0] == 0f || Main.npc[i].ai[0] == 10f)
                 {
                     continue;
                 }
                 break;
             }
             if ((specialHitSetter == -1 && immune) || (dash == 2 && i == eocHit && eocDash > 0) || npcTypeNoAggro[Main.npc[i].type])
             {
                 continue;
             }
             float damageMultiplier = 1f;
             Main.npc[i].position += Main.npc[i].netOffset;
             Rectangle npcRect = new Rectangle((int)Main.npc[i].position.X, (int)Main.npc[i].position.Y, Main.npc[i].width, Main.npc[i].height);
             NPC.GetMeleeCollisionData(rectangle, i, ref specialHitSetter, ref damageMultiplier, ref npcRect);
             if (rectangle.Intersects(npcRect))
             {
                 if (npcTypeNoAggro[Main.npc[i].type])
                 {
                     continue;
                 }
                 bool flag = true;
                 bool flag2 = false;
                 bool num = CanParryAgainst(rectangle, npcRect, Main.npc[i].velocity);
                 float num2 = thorns;
                 float knockback = 10f;
                 if (turtleThorns)
                 {
                     num2 = 2f;
                 }
                 if (num)
                 {
                     num2 = 2f;
                     knockback = 5f;
                     flag = false;
                     flag2 = true;
                 }
                 int num3 = -1;
                 if (Main.npc[i].position.X + (float)(Main.npc[i].width / 2) < position.X + (float)(width / 2))
                 {
                     num3 = 1;
                 }
                 int num4 = Main.DamageVar((float)Main.npc[i].damage * damageMultiplier, 0f - luck);
                 int num5 = Item.NPCtoBanner(Main.npc[i].BannerID());
                 if (num5 > 0 && HasNPCBannerBuff(num5))
                 {
                     num4 = ((!Main.expertMode) ? ((int)((float)num4 * ItemID.Sets.BannerStrength[Item.BannerToItem(num5)].NormalDamageReceived)) : ((int)((float)num4 * ItemID.Sets.BannerStrength[Item.BannerToItem(num5)].ExpertDamageReceived)));
                 }
                 bool flag3 = !immune;
                 if (specialHitSetter >= 0)
                 {
                     flag3 = hurtCooldowns[specialHitSetter] == 0;
                 }
                 if (whoAmI == Main.myPlayer && num2 > 0f && flag3 && !Main.npc[i].dontTakeDamage)
                 {
                     int num6 = (int)((float)num4 * num2);
                     if (num6 > 1000)
                     {
                         num6 = 1000;
                     }
                     ApplyDamageToNPC(Main.npc[i], num6, knockback, -num3, crit: false);
                 }
                 if (whoAmI == Main.myPlayer && cactusThorns && flag3 && !Main.npc[i].dontTakeDamage)
                 {
                     int damage = 15;
                     if (Main.masterMode)
                     {
                         damage = 45;
                     }
                     else if (Main.expertMode)
                     {
                         damage = 30;
                     }
                     ApplyDamageToNPC(Main.npc[i], damage, knockback, -num3, crit: false);
                 }
                 if (resistCold && Main.npc[i].coldDamage)
                 {
                     num4 = (int)((float)num4 * 0.7f);
                 }
                 if (flag && Hurt(dodgeable: Main.npc[i].IsDamageDodgeable(), damageSource: PlayerDeathReason.ByNPC(i), Damage: num4, hitDirection: num3, pvp: false, quiet: false, Crit: false, cooldownCounter: specialHitSetter) > 0.0 && !dead && !flag2)
                 {
                     StatusFromNPC(Main.npc[i]);
                 }
                 if (num)
                 {
                     GiveImmuneTimeForCollisionAttack(longInvince ? 60 : 30);
                     AddBuff(198, 300, quiet: false);
                 }
             }
             Main.npc[i].position -= Main.npc[i].netOffset;
         }
     }
References Entity.active, NPC.ai, NPC.BannerID(), ItemID.Sets.BannerStrength, Item.BannerToItem(), PlayerDeathReason.ByNPC(), NPC.coldDamage, Damage, NPC.damage, Main.DamageVar(), NPC.dontTakeDamage, ItemID.BannerEffect.ExpertDamageReceived, Main.expertMode, NPC.friendly, NPC.GetMeleeCollisionData(), Entity.height, NPC.IsDamageDodgeable(), Main.masterMode, Main.myPlayer, NPC.netOffset, ItemID.BannerEffect.NormalDamageReceived, Main.npc, Item.NPCtoBanner(), Entity.position, NPC.type, Entity.velocity, and Entity.width.