Terraria: Player.Shellphone_Spawn
Shellphone_Spawn()
void Player.Shellphone_Spawn () inline
     {
         int floorX = Main.spawnTileX;
         int floorY = Main.spawnTileY;
         Spawn_GetPositionAtWorldSpawn(ref floorX, ref floorY);
         if (Main.netMode != 1 && !Spawn_IsAreaAValidWorldSpawn(floorX, floorY))
         {
             Spawn_ForceClearArea(floorX, floorY);
         }
         Vector2 newPos = new Point(floorX, floorY).ToWorldCoordinates(8f, 0f) - new Vector2(width / 2, height);
         Teleport(newPos, 11);
         velocity = Vector2.Zero;
         if (Main.netMode == 2)
         {
             RemoteClient.CheckSection(whoAmI, position);
             NetMessage.SendData(65, -1, -1, null, 0, whoAmI, newPos.X, newPos.Y, 11);
         }
     }
References RemoteClient.CheckSection(), Main.netMode, NetMessage.SendData(), Main.spawnTileX, and Main.spawnTileY.
Referenced by MessageBuffer.GetData().