Terraria: Player.QuickMinecartSnap
QuickMinecartSnap()
bool Player.QuickMinecartSnap () inline private
     {
         bool result = false;
         List<Point> tilesIn = Collision.GetTilesIn(base.TopLeft - new Vector2(24f), base.BottomRight + new Vector2(24f));
         if (tilesIn.Count > 0)
         {
             Point? point = null;
             _ = base.Hitbox;
             for (int i = 0; i < tilesIn.Count; i++)
             {
                 Point point2 = tilesIn[i];
                 Tile tileSafely = Framing.GetTileSafely(point2.X, point2.Y);
                 if (tileSafely.active() && tileSafely.type == 314)
                 {
                     Vector2 vector = tilesIn[i].ToVector2() * 16f + new Vector2(8f);
                     if (!point.HasValue || (Distance(vector) < Distance(point.Value.ToVector2() * 16f + new Vector2(8f)) && Collision.CanHitLine(base.Center, 0, 0, vector, 0, 0)))
                     {
                         point = tilesIn[i];
                     }
                 }
             }
             if (point.HasValue)
             {
                 LaunchMinecartHook(point.Value.X, point.Value.Y);
                 result = true;
             }
         }
         return result;
     }
References Tile.active(), Collision.CanHitLine(), Framing.GetTileSafely(), Collision.GetTilesIn(), and Tile.type.