Terraria: Player.PlaceThing_XMasTreeTops
PlaceThing_XMasTreeTops()
void Player.PlaceThing_XMasTreeTops () inline private
     {
         if (inventory[selectedItem].type < 1874 || inventory[selectedItem].type > 1905 || !Main.tile[tileTargetX, tileTargetY].active() || Main.tile[tileTargetX, tileTargetY].type != 171 || !(position.X / 16f - (float)tileRangeX - (float)inventory[selectedItem].tileBoost - (float)blockRange <= (float)tileTargetX) || !((position.X + (float)width) / 16f + (float)tileRangeX + (float)inventory[selectedItem].tileBoost - 1f + (float)blockRange >= (float)tileTargetX) || !(position.Y / 16f - (float)tileRangeY - (float)inventory[selectedItem].tileBoost - (float)blockRange <= (float)tileTargetY) || !((position.Y + (float)height) / 16f + (float)tileRangeY + (float)inventory[selectedItem].tileBoost - 2f + (float)blockRange >= (float)tileTargetY) || !ItemTimeIsZero || itemAnimation <= 0 || !controlUseItem)
         {
             return;
         }
         int type = inventory[selectedItem].type;
         if (type >= 1874 && type <= 1877)
         {
             type -= 1873;
             if (WorldGen.checkXmasTreeDrop(tileTargetX, tileTargetY, 0) != type)
             {
                 ApplyItemTime(inventory[selectedItem]);
                 WorldGen.dropXmasTree(tileTargetX, tileTargetY, 0);
                 WorldGen.setXmasTree(tileTargetX, tileTargetY, 0, type);
                 int num = tileTargetX;
                 int num2 = tileTargetY;
                 if (Main.tile[tileTargetX, tileTargetY].frameX < 10)
                 {
                     num -= Main.tile[tileTargetX, tileTargetY].frameX;
                     num2 -= Main.tile[tileTargetX, tileTargetY].frameY;
                 }
                 NetMessage.SendTileSquare(-1, num, num2);
             }
         }
         else if (type >= 1878 && type <= 1883)
         {
             type -= 1877;
             if (WorldGen.checkXmasTreeDrop(tileTargetX, tileTargetY, 1) != type)
             {
                 ApplyItemTime(inventory[selectedItem]);
                 WorldGen.dropXmasTree(tileTargetX, tileTargetY, 1);
                 WorldGen.setXmasTree(tileTargetX, tileTargetY, 1, type);
                 int num3 = tileTargetX;
                 int num4 = tileTargetY;
                 if (Main.tile[tileTargetX, tileTargetY].frameX < 10)
                 {
                     num3 -= Main.tile[tileTargetX, tileTargetY].frameX;
                     num4 -= Main.tile[tileTargetX, tileTargetY].frameY;
                 }
                 NetMessage.SendTileSquare(-1, num3, num4);
             }
         }
         else if (type >= 1884 && type <= 1894)
         {
             type -= 1883;
             if (WorldGen.checkXmasTreeDrop(tileTargetX, tileTargetY, 2) != type)
             {
                 ApplyItemTime(inventory[selectedItem]);
                 WorldGen.dropXmasTree(tileTargetX, tileTargetY, 2);
                 WorldGen.setXmasTree(tileTargetX, tileTargetY, 2, type);
                 int num5 = tileTargetX;
                 int num6 = tileTargetY;
                 if (Main.tile[tileTargetX, tileTargetY].frameX < 10)
                 {
                     num5 -= Main.tile[tileTargetX, tileTargetY].frameX;
                     num6 -= Main.tile[tileTargetX, tileTargetY].frameY;
                 }
                 NetMessage.SendTileSquare(-1, num5, num6);
             }
         }
         else
         {
             if (type < 1895 || type > 1905)
             {
                 return;
             }
             type -= 1894;
             if (WorldGen.checkXmasTreeDrop(tileTargetX, tileTargetY, 3) != type)
             {
                 ApplyItemTime(inventory[selectedItem]);
                 WorldGen.dropXmasTree(tileTargetX, tileTargetY, 3);
                 WorldGen.setXmasTree(tileTargetX, tileTargetY, 3, type);
                 int num7 = tileTargetX;
                 int num8 = tileTargetY;
                 if (Main.tile[tileTargetX, tileTargetY].frameX < 10)
                 {
                     num7 -= Main.tile[tileTargetX, tileTargetY].frameX;
                     num8 -= Main.tile[tileTargetX, tileTargetY].frameY;
                 }
                 NetMessage.SendTileSquare(-1, num7, num8);
             }
         }
     }
References Tile.active(), WorldGen.checkXmasTreeDrop(), WorldGen.dropXmasTree(), Tile.frameX, Tile.frameY, NetMessage.SendTileSquare(), WorldGen.setXmasTree(), Main.tile, and Tile.type.