Terraria: Player.ToggleCreativeMenu
ToggleCreativeMenu()
void Player.ToggleCreativeMenu () inline
     {
         if (dead || difficulty != 3)
         {
             return;
         }
         bool flag = false;
         if (Main.mapFullscreen)
         {
             Main.mapFullscreen = false;
             flag = true;
         }
         if (PlayerInput.InBuildingMode)
         {
             PlayerInput.ExitBuildingMode();
         }
         if (Main.ingameOptionsWindow)
         {
             IngameOptions.Close();
         }
         if (Main.inFancyUI)
         {
             IngameFancyUI.Close();
         }
         if (CaptureManager.Instance.Active)
         {
             CaptureManager.Instance.Active = false;
         }
         if (talkNPC >= 0)
         {
             SetTalkNPC(-1);
             Main.npcChatCornerItem = 0;
             Main.npcChatText = "";
             flag = true;
             if (PlayerInput.UsingGamepad)
             {
                 Main.npcChatRelease = false;
             }
         }
         if (sign >= 0)
         {
             sign = -1;
             Main.editSign = false;
             Main.npcChatText = "";
             flag = true;
         }
         else if (Main.clothesWindow)
         {
             Main.CancelClothesWindow();
         }
         if (tileEntityAnchor.InUse)
         {
             Recipe.FindRecipes();
             tileEntityAnchor.Clear();
             flag = true;
         }
         if (flag)
         {
             SoundEngine.PlaySound(11);
         }
         if (!Main.playerInventory)
         {
             OpenInventory();
         }
         Main.CreativeMenu.ToggleMenu();
     }
References CaptureManager.Active, Main.CancelClothesWindow(), IngameFancyUI.Close(), IngameOptions.Close(), Main.clothesWindow, Main.CreativeMenu, Main.editSign, PlayerInput.ExitBuildingMode(), Recipe.FindRecipes(), PlayerInput.InBuildingMode, Main.inFancyUI, Main.ingameOptionsWindow, CaptureManager.Instance, Main.mapFullscreen, Main.npcChatCornerItem, Main.npcChatRelease, Main.npcChatText, Main.playerInventory, SoundEngine.PlaySound(), CreativeUI.ToggleMenu(), and PlayerInput.UsingGamepad.
Referenced by Main.DoUpdate_WhilePaused().