Terraria: Player.ConsumeItem
ConsumeItem()
bool Player.ConsumeItem (int type, bool reverseOrder = false, bool includeVoidBag = false) inline
     {
         int num = 0;
         int num2 = 58;
         int num3 = 1;
         if (reverseOrder)
         {
             num = 57;
             num2 = -1;
             num3 = -1;
         }
         for (int i = num; i != num2; i += num3)
         {
             if (inventory[i].stack > 0 && inventory[i].type == type)
             {
                 inventory[i].stack--;
                 if (inventory[i].stack <= 0)
                 {
                     inventory[i].SetDefaults();
                 }
                 return true;
             }
         }
         if (includeVoidBag && useVoidBag())
         {
             int num4 = FindItem(type, bank4.item);
             if (num4 == -1)
             {
                 return false;
             }
             Item item = bank4.item[num4];
             item.stack--;
             if (item.stack <= 0)
             {
                 item.TurnToAir();
             }
             return true;
         }
         return false;
     }
References Item.stack, and Item.TurnToAir().
Referenced by MessageBuffer.GetData(), Main.GUIChatDrawInner(), Wiring.MassWireOperation(), and ItemSlot.TryOpenContainer().