Terraria: Player.FindSharpTearsSpot
FindSharpTearsSpot()
Point Player.FindSharpTearsSpot (Vector2 targetSpot) inline private
     {
         Point point = targetSpot.ToTileCoordinates();
         Vector2 center = base.Center;
         Vector2 endPoint = targetSpot;
         int samplesToTake = 3;
         float samplingWidth = 4f;
         Collision.AimingLaserScan(center, endPoint, samplingWidth, samplesToTake, out var vectorTowardsTarget, out var samples);
         float num = float.PositiveInfinity;
         for (int i = 0; i < samples.Length; i++)
         {
             if (samples[i] < num)
             {
                 num = samples[i];
             }
         }
         targetSpot = center + vectorTowardsTarget.SafeNormalize(Vector2.Zero) * num;
         point = targetSpot.ToTileCoordinates();
         Rectangle value = new Rectangle(point.X, point.Y, 1, 1);
         value.Inflate(6, 16);
         Rectangle value2 = new Rectangle(0, 0, Main.maxTilesX, Main.maxTilesY);
         value2.Inflate(-40, -40);
         value = Rectangle.Intersect(value, value2);
         List<Point> list = new List<Point>();
         List<Point> list2 = new List<Point>();
         for (int j = value.Left; j <= value.Right; j++)
         {
             for (int k = value.Top; k <= value.Bottom; k++)
             {
                 if (!WorldGen.SolidTile2(j, k))
                 {
                     continue;
                 }
                 Vector2 value3 = new Vector2(j * 16 + 8, k * 16 + 8);
                 if (!(Vector2.Distance(targetSpot, value3) > 200f))
                 {
                     if (FindSharpTearsOpening(j, k, j > point.X, j < point.X, k > point.Y, k < point.Y))
                     {
                         list.Add(new Point(j, k));
                     }
                     else
                     {
                         list2.Add(new Point(j, k));
                     }
                 }
             }
         }
         if (list.Count == 0 && list2.Count == 0)
         {
             list.Add((base.Center.ToTileCoordinates().ToVector2() + Main.rand.NextVector2Square(-2f, 2f)).ToPoint());
         }
         List<Point> list3 = list;
         if (list3.Count == 0)
         {
             list3 = list2;
         }
         int index = Main.rand.Next(list3.Count);
         return list3[index];
     }
References Collision.AimingLaserScan(), Main.maxTilesX, Main.maxTilesY, UnifiedRandom.Next(), Main.rand, and WorldGen.SolidTile2().