Terraria: Player.ResetEffects
ResetEffects()
void Player.ResetEffects () inline
     {
         if (extraAccessory && (Main.expertMode || Main.gameMenu))
         {
             extraAccessorySlots = 1;
         }
         else
         {
             extraAccessorySlots = 0;
         }
         if (shimmering)
         {
             shimmerTransparency += 0.015f;
             if (shimmerTransparency > 0.8f)
             {
                 shimmerTransparency = 0.8f;
             }
         }
         else if (shimmerTransparency > 0f)
         {
             if (shimmerTransparency == 0.8f)
             {
                 SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 3);
             }
             shimmerTransparency -= 0.015f;
             if (shimmerTransparency < 0f)
             {
                 shimmerTransparency = 0f;
             }
         }
         shimmering = false;
         fairyBoots = false;
         hellfireTreads = false;
         moonLordLegs = false;
         flowerBoots = false;
         arcticDivingGear = false;
         noBuilding = false;
         strongBees = false;
         armorPenetration = 0;
         ashWoodBonus = false;
         shroomiteStealth = false;
         statDefense = 0;
         accWatch = 0;
         accCompass = 0;
         accDepthMeter = 0;
         accDivingHelm = false;
         canFloatInWater = false;
         lifeRegen = 0;
         manaCost = 1f;
         meleeSpeed = 1f;
         meleeDamage = 1f;
         rangedDamage = 1f;
         rangedMultDamage = 1f;
         magicDamage = 1f;
         minionDamage = 1f;
         summonerWeaponSpeedBonus = 0f;
         meleeCrit = 4;
         rangedCrit = 4;
         magicCrit = 4;
         hasFootball = false;
         drawingFootball = false;
         minionKB = 0f;
         moveSpeed = 1f;
         boneArmor = false;
         honey = false;
         frostArmor = false;
         rocketBoots = 0;
         vanityRocketBoots = 0;
         fireWalk = false;
         noKnockback = false;
         jumpBoost = false;
         frogLegJumpBoost = false;
         skyStoneEffects = false;
         noFallDmg = false;
         accFlipper = false;
         spawnMax = false;
         spaceGun = false;
         killGuide = false;
         killClothier = false;
         lavaImmune = false;
         gills = false;
         slowFall = false;
         findTreasure = false;
         biomeSight = false;
         invis = false;
         nightVision = false;
         enemySpawns = false;
         hasTitaniumStormBuff = false;
         thorns = 0f;
         aggro = 0;
         waterWalk = false;
         waterWalk2 = false;
         detectCreature = false;
         gravControl = false;
         if (forcedGravity > 0)
         {
             forcedGravity--;
         }
         honeyCombItem = null;
         gravControl2 = false;
         statLifeMax2 = statLifeMax;
         statManaMax2 = statManaMax;
         chloroAmmoCost80 = false;
         huntressAmmoCost90 = false;
         ammoCost80 = false;
         ammoCost75 = false;
         manaRegenBuff = false;
         hasCreditsSceneMusicBox = false;
         arrowDamage = 1f;
         arrowDamageAdditiveStack = 0f;
         bulletDamage = 1f;
         rocketDamage = 1f;
         coolWhipBuff = false;
         yoraiz0rEye = 0;
         yoraiz0rDarkness = false;
         hasFloatingTube = false;
         hasUnicornHorn = false;
         hasAngelHalo = false;
         hasRainbowCursor = false;
         leinforsHair = false;
         overrideFishingBobber = -1;
         suspiciouslookingTentacle = false;
         crimsonHeart = false;
         lightOrb = false;
         blueFairy = false;
         redFairy = false;
         greenFairy = false;
         wisp = false;
         bunny = false;
         turtle = false;
         eater = false;
         trident = false;
         skeletron = false;
         hornet = false;
         zephyrfish = false;
         tiki = false;
         lizard = false;
         parrot = false;
         sapling = false;
         cSapling = false;
         truffle = false;
         yoyoGlove = false;
         counterWeight = 0;
         stringColor = 0;
         yoyoString = false;
         shadowDodge = false;
         palladiumRegen = false;
         chaosState = false;
         onHitDodge = false;
         onHitRegen = false;
         onHitPetal = false;
         iceBarrier = false;
         onHitTitaniumStorm = false;
         maxMinions = 1;
         maxTurrets = 1;
         ammoBox = false;
         ammoPotion = false;
         penguin = false;
         sporeSac = false;
         shinyStone = false;
         empressBrooch = false;
         volatileGelatin = false;
         hasMagiluminescence = false;
         shadowArmor = false;
         if (Main.dontStarveWorld && Main.remixWorld)
         {
             dontStarveShader = false;
         }
         else
         {
             dontStarveShader = Main.dontStarveWorld;
         }
         eyebrellaCloud = false;
         stardustMonolithShader = false;
         nebulaMonolithShader = false;
         vortexMonolithShader = false;
         solarMonolithShader = false;
         moonLordMonolithShader = false;
         bloodMoonMonolithShader = false;
         shimmerMonolithShader = false;
         dd2Accessory = false;
         magicLantern = false;
         rabid = false;
         sunflower = false;
         wellFed = false;
         inferno = false;
         manaMagnet = false;
         lifeMagnet = false;
         treasureMagnet = false;
         chiselSpeed = false;
         lifeForce = false;
         dangerSense = false;
         endurance = 0f;
         whipRangeMultiplier = 1f;
         whipUseTimeMultiplier = 1f;
         calmed = false;
         beetleOrbs = 0;
         beetleBuff = false;
         miniMinotaur = false;
         goldRing = false;
         solarShields = 0;
         GoingDownWithGrapple = false;
         fishingSkill = 0;
         cratePotion = false;
         sonarPotion = false;
         accTackleBox = false;
         accFishingBobber = false;
         accFishingLine = false;
         accLavaFishing = false;
         accFishFinder = false;
         accWeatherRadio = false;
         accThirdEye = false;
         InfoAccMechShowWires = false;
         accJarOfSouls = false;
         accCalendar = false;
         accStopwatch = false;
         accOreFinder = false;
         accCritterGuide = false;
         accDreamCatcher = false;
         wallSpeed = 1f;
         tileSpeed = 1f;
         autoPaint = false;
         autoActuator = false;
         petFlagKingSlimePet = false;
         petFlagEyeOfCthulhuPet = false;
         petFlagEaterOfWorldsPet = false;
         petFlagBrainOfCthulhuPet = false;
         petFlagSkeletronPet = false;
         petFlagQueenBeePet = false;
         petFlagDestroyerPet = false;
         petFlagTwinsPet = false;
         petFlagSkeletronPrimePet = false;
         petFlagPlanteraPet = false;
         petFlagGolemPet = false;
         petFlagDukeFishronPet = false;
         petFlagLunaticCultistPet = false;
         petFlagMoonLordPet = false;
         petFlagFairyQueenPet = false;
         petFlagPumpkingPet = false;
         petFlagEverscreamPet = false;
         petFlagIceQueenPet = false;
         petFlagMartianPet = false;
         petFlagDD2OgrePet = false;
         petFlagDD2BetsyPet = false;
         petFlagQueenSlimePet = false;
         petFlagVoltBunny = false;
         petFlagShadowMimic = false;
         petFlagBabyWerewolf = false;
         petFlagDynamiteKitten = false;
         petFlagPlantero = false;
         petFlagBabyRedPanda = false;
         petFlagLilHarpy = false;
         petFlagFennecFox = false;
         petFlagGlitteryButterfly = false;
         petFlagBabyImp = false;
         petFlagBabyShark = false;
         petFlagUpbeatStar = false;
         petFlagDD2Gato = false;
         petFlagDD2Dragon = false;
         petFlagDD2Ghost = false;
         petFlagBerniePet = false;
         petFlagGlommerPet = false;
         petFlagDeerclopsPet = false;
         petFlagPigPet = false;
         petFlagChesterPet = false;
         petFlagJunimoPet = false;
         petFlagBlueChickenPet = false;
         petFlagSpiffo = false;
         petFlagCaveling = false;
         petFlagDirtiestBlock = false;
         companionCube = false;
         petFlagSugarGlider = false;
         babyFaceMonster = false;
         manaSick = false;
         puppy = false;
         grinch = false;
         blackCat = false;
         spider = false;
         squashling = false;
         magicCuffs = false;
         coldDash = false;
         desertDash = false;
         desertBoots = false;
         sailDash = false;
         cordage = false;
         magicQuiver = false;
         shimmerImmune = false;
         hasMoltenQuiver = false;
         magmaStone = false;
         hasRaisableShield = false;
         lavaRose = false;
         eyeSpring = false;
         snowman = false;
         scope = false;
         panic = false;
         brainOfConfusionItem = null;
         dino = false;
         crystalLeaf = false;
         pygmy = false;
         raven = false;
         slime = false;
         hornetMinion = false;
         impMinion = false;
         twinsMinion = false;
         spiderMinion = false;
         pirateMinion = false;
         sharknadoMinion = false;
         stardustMinion = false;
         batsOfLight = false;
         babyBird = false;
         stormTiger = false;
         flinxMinion = false;
         abigailMinion = false;
         smolstar = false;
         empressBlade = false;
         stardustGuardian = false;
         stardustDragon = false;
         UFOMinion = false;
         DeadlySphereMinion = false;
         chilled = false;
         tipsy = false;
         dazed = false;
         frozen = false;
         stoned = false;
         webbed = false;
         ichor = false;
         manaRegenBonus = 0;
         manaRegenDelayBonus = 0f;
         carpet = false;
         iceSkate = false;
         dashType = 0;
         spikedBoots = 0;
         blackBelt = false;
         lavaMax = 0;
         archery = false;
         poisoned = false;
         venom = false;
         blind = false;
         blackout = false;
         onFire = false;
         dripping = false;
         hungry = false;
         heartyMeal = false;
         starving = false;
         drippingSlime = false;
         drippingSparkleSlime = false;
         burned = false;
         suffocating = false;
         onFire2 = false;
         onFire3 = false;
         onFrostBurn = false;
         onFrostBurn2 = false;
         frostBurn = false;
         noItems = false;
         cursed = false;
         blockRange = 0;
         pickSpeed = 1f;
         wereWolf = false;
         rulerGrid = false;
         rulerLine = true;
         bleed = false;
         confused = false;
         witheredArmor = false;
         witheredWeapon = false;
         parryDamageBuff = false;
         slowOgreSpit = false;
         wings = 0;
         wingsLogic = 0;
         wingTimeMax = 0;
         brokenArmor = false;
         silence = false;
         slow = false;
         gross = false;
         tongued = false;
         kbGlove = false;
         autoReuseGlove = false;
         meleeScaleGlove = false;
         remoteVisionForDrone = false;
         kbBuff = false;
         starCloakItem = null;
         starCloakItem_manaCloakOverrideItem = null;
         starCloakItem_starVeilOverrideItem = null;
         starCloakItem_beeCloakOverrideItem = null;
         longInvince = false;
         pStone = false;
         manaFlower = false;
         crimsonRegen = false;
         ghostHeal = false;
         ghostHurt = false;
         turtleArmor = false;
         turtleThorns = false;
         cactusThorns = false;
         spiderArmor = false;
         anglerSetSpawnReduction = false;
         loveStruck = false;
         stinky = false;
         dryadWard = false;
         resistCold = false;
         electrified = false;
         moonLeech = false;
         headcovered = false;
         vortexDebuff = false;
         windPushed = false;
         ballistaPanic = false;
         vampireFrog = false;
         CanSeeInvisibleBlocks = false;
         setVortex = (setNebula = (setStardust = false));
         setForbidden = false;
         setHuntressT3 = false;
         setSquireT3 = false;
         setMonkT3 = false;
         setApprenticeT3 = false;
         setHuntressT2 = false;
         setSquireT2 = false;
         setMonkT2 = false;
         setApprenticeT2 = false;
         setForbiddenCooldownLocked = false;
         nebulaLevelDamage = (nebulaLevelLife = (nebulaLevelMana = 0));
         ignoreWater = false;
         meleeEnchant = 0;
         discountEquipped = false;
         hasLuckyCoin = false;
         boneGloveItem = null;
         hasLuck_LuckyCoin = false;
         hasLuck_LuckyHorseshoe = false;
         hasJumpOption_Cloud = false;
         hasJumpOption_Sail = false;
         hasJumpOption_Sandstorm = false;
         hasJumpOption_Blizzard = false;
         hasJumpOption_Fart = false;
         hasJumpOption_Unicorn = false;
         hasJumpOption_Santank = false;
         hasJumpOption_WallOfFleshGoat = false;
         hasJumpOption_Basilisk = false;
         defendedByPaladin = false;
         hasPaladinShield = false;
         hasLucyTheAxe = false;
         preventAllItemPickups = false;
         dontHurtCritters = false;
         dontHurtNature = false;
         portableStoolInfo.Reset();
         ResizeHitbox();
         autoJump = false;
         justJumped = false;
         jumpSpeedBoost = 0f;
         extraFall = 0;
         creativeGodMode = false;
         if (phantasmTime > 0)
         {
             phantasmTime--;
         }
         if (brainOfConfusionDodgeAnimationCounter > 0)
         {
             brainOfConfusionDodgeAnimationCounter--;
         }
         if (wireOperationsCooldown > 0)
         {
             wireOperationsCooldown--;
         }
         if (releaseUseItem)
         {
             ActuationRodLock = false;
         }
         for (int i = 0; i < npcTypeNoAggro.Length; i++)
         {
             npcTypeNoAggro[i] = false;
         }
         ResetProjectileCaches();
         if (whoAmI == Main.myPlayer && !isDisplayDollOrInanimate)
         {
             equipmentBasedLuckBonus = 0f;
             luckPotion = 0;
             tileRangeX = 5;
             tileRangeY = 4;
             if (Main.GameModeInfo.IsJourneyMode)
             {
                 CreativePowers.FarPlacementRangePower power = CreativePowerManager.Instance.GetPower<CreativePowers.FarPlacementRangePower>();
                 if (power.GetIsUnlocked() && power.IsEnabledForPlayer(whoAmI))
                 {
                     tileRangeX *= 2;
                     tileRangeY *= 2;
                     tileRangeX += 8;
                     tileRangeY += 8;
                 }
             }
         }
         mount.CheckMountBuff(this);
     }
References Main.dontStarveWorld, Main.expertMode, Main.gameMenu, Main.GameModeInfo, CreativePowerManager.Instance, GameModeData.IsJourneyMode, Main.myPlayer, SoundEngine.PlaySound(), and Main.remixWorld.
Referenced by TEDisplayDoll.Draw(), TEHatRack.Draw(), Segments.PlayerSegment.Draw(), Main.DrawSuperSpecialProjectiles(), and UICharacter.Update().