Terraria: Player.FreeUpPetsAndMinions
FreeUpPetsAndMinions()
void Player.FreeUpPetsAndMinions (Item sItem) inline private
     {
         if (ProjectileID.Sets.MinionSacrificable[sItem.shoot])
         {
             List<int> list = new List<int>();
             float num = 0f;
             for (int i = 0; i < 1000; i++)
             {
                 if (!Main.projectile[i].active || Main.projectile[i].owner != whoAmI || !Main.projectile[i].minion)
                 {
                     continue;
                 }
                 int j;
                 for (j = 0; j < list.Count; j++)
                 {
                     if (Main.projectile[list[j]].minionSlots > Main.projectile[i].minionSlots)
                     {
                         list.Insert(j, i);
                         break;
                     }
                 }
                 if (j == list.Count)
                 {
                     list.Add(i);
                 }
                 num += Main.projectile[i].minionSlots;
             }
             float num2 = ItemID.Sets.StaffMinionSlotsRequired[sItem.type];
             float num3 = 0f;
             int num4 = 388;
             int num5 = -1;
             for (int k = 0; k < list.Count; k++)
             {
                 int type = Main.projectile[list[k]].type;
                 if (type == 626)
                 {
                     list.RemoveAt(k);
                     k--;
                 }
                 if (type == 627)
                 {
                     if (Main.projectile[(int)Main.projectile[list[k]].localAI[1]].type == 628)
                     {
                         num5 = list[k];
                     }
                     list.RemoveAt(k);
                     k--;
                 }
             }
             if (num5 != -1)
             {
                 list.Add(num5);
                 list.Add(Projectile.GetByUUID(Main.projectile[num5].owner, Main.projectile[num5].ai[0]));
             }
             for (int l = 0; l < list.Count; l++)
             {
                 if (!(num - num3 > (float)maxMinions - num2))
                 {
                     break;
                 }
                 int type2 = Main.projectile[list[l]].type;
                 if (type2 == num4 || type2 == 625 || type2 == 628 || type2 == 623)
                 {
                     continue;
                 }
                 if (type2 == 388 && num4 == 387)
                 {
                     num4 = 388;
                 }
                 if (type2 == 387 && num4 == 388)
                 {
                     num4 = 387;
                 }
                 num3 += Main.projectile[list[l]].minionSlots;
                 if (type2 == 626 || type2 == 627)
                 {
                     Projectile projectile = Main.projectile[list[l]];
                     int byUUID = Projectile.GetByUUID(projectile.owner, projectile.ai[0]);
                     if (Main.projectile.IndexInRange(byUUID))
                     {
                         Projectile projectile2 = Main.projectile[byUUID];
                         if (projectile2.type != 625)
{
                             projectile2.localAI[1] = projectile.localAI[1];
                         }
                         projectile2 = Main.projectile[(int)projectile.localAI[1]];
                         projectile2.ai[0] = projectile.ai[0];
                         projectile2.ai[1] = 1f;
                         projectile2.netUpdate = true;
                     }
                 }
                 Main.projectile[list[l]].Kill();
             }
             list.Clear();
             if (num + num2 >= 9f)
             {
                 AchievementsHelper.HandleSpecialEvent(this, 6);
             }
             return;
         }
         for (int m = 0; m < 1000; m++)
         {
             Projectile projectile3 = Main.projectile[m];
             if (projectile3.active && projectile3.owner == whoAmI)
             {
                 if (projectile3.type == sItem.shoot)
                 {
                     projectile3.Kill();
                 }
                 if (sItem.shoot == 72 && (projectile3.type == 86 || projectile3.type == 87))
                 {
                     projectile3.Kill();
                 }
                 if (sItem.type == 5131 && (projectile3.type == 881 || projectile3.type == 934))
                 {
                     projectile3.Kill();
                 }
             }
         }
     }
References Entity.active, Projectile.ai, Projectile.GetByUUID(), AchievementsHelper.HandleSpecialEvent(), Projectile.Kill(), Projectile.localAI, Projectile.minion, ProjectileID.Sets.MinionSacrificable, Projectile.minionSlots, Projectile.netUpdate, Projectile.owner, Main.projectile, Item.shoot, ItemID.Sets.StaffMinionSlotsRequired, Item.type, and Projectile.type.