Terraria: Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform
PlaceThing_Tiles_PlaceIt_SpinSmartPlatform()
void Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform () inline private
     {
         if (inventory[selectedItem].createTile < 0 || !TileID.Sets.Platforms[inventory[selectedItem].createTile] || !Main.SmartCursorIsUsed)
         {
             return;
         }
         int num = tileTargetX;
         int num2 = tileTargetY;
         int num3 = -1;
         int num4 = 0;
         int num5 = 0;
         bool flag = true;
         for (int i = -1; i < 2; i++)
         {
             for (int j = -1; j < 2; j++)
             {
                 if ((i != 0 || j != 0) && TileID.Sets.Platforms[Main.tile[num + i, num2 + j].type])
                 {
                     flag = false;
                 }
             }
         }
         if (flag)
         {
             return;
         }
         Tile tile = Main.tile[num - 1, num2 - 1];
         if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 2)
         {
             num4++;
         }
         tile = Main.tile[num - 1, num2 + 1];
         if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 1)
         {
             num5++;
         }
         tile = Main.tile[num + 1, num2 - 1];
         if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 1)
         {
             num5++;
         }
         tile = Main.tile[num + 1, num2 + 1];
         if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 2)
         {
             num4++;
         }
         tile = Main.tile[num - 1, num2];
         if (WorldGen.SolidTile(tile))
         {
             num4++;
             if (TileID.Sets.Platforms[tile.type] && tile.slope() == 0)
             {
                 num4++;
             }
         }
         tile = Main.tile[num + 1, num2];
         if (WorldGen.SolidTile(tile))
         {
             num5++;
             if (TileID.Sets.Platforms[tile.type] && tile.slope() == 0)
             {
                 num5++;
             }
         }
         if (num4 > num5)
         {
             num3 = 1;
         }
         else if (num5 > num4)
         {
             num3 = 2;
         }
         tile = Main.tile[num - 1, num2];
         if (tile.active() && TileID.Sets.Platforms[tile.type])
         {
             num3 = 0;
         }
         tile = Main.tile[num + 1, num2];
         if (tile.active() && TileID.Sets.Platforms[tile.type])
         {
             num3 = 0;
         }
         int num6 = 0;
         int num7 = 0;
         if (num3 != -1)
         {
             WorldGen.SlopeTile(num, num2, num3, noEffects: true);
             int num8 = Main.tile[num, num2].slope();
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 14, tileTargetX, tileTargetY, num8);
             }
             if (num3 == 1)
             {
                 num6 = -1;
                 num7 = -1;
             }
             else
             {
                 num6 = 1;
                 num7 = -1;
             }
             tile = Main.tile[num + num6, num2 + num7];
             if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() == 0 && (!Main.tile[num + num6 + num6, num2 + num7].active() || !TileID.Sets.Platforms[Main.tile[num + num6 + num6, num2 + num7].type] || !Main.tile[num + num6 + num6, num2 + num7].halfBrick()))
             {
                 WorldGen.SlopeTile(num + num6, num2 + num7, num3);
                 num8 = tile.slope();
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(17, -1, -1, null, 14, num + num6, num2 + num7, num8);
                 }
             }
             if (num3 == 1)
             {
                 num6 = 1;
                 num7 = 1;
             }
             else
             {
                 num6 = -1;
                 num7 = 1;
             }
             tile = Main.tile[num + num6, num2 + num7];
             if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() == 0 && WorldGen.PlatformProperSides(num + num6, num2 + num7, acceptNonOpposing: true) <= 0)
             {
                 WorldGen.SlopeTile(num + num6, num2 + num7, num3);
                 num8 = tile.slope();
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(17, -1, -1, null, 14, num + num6, num2 + num7, num8);
                 }
             }
             return;
         }
         num3 = 0;
         int num9 = 0;
         num6 = -1;
         tile = Main.tile[num + num6, num2];
         if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 0)
         {
             int num10 = (tile.slope() == 1).ToDirectionInt() * num6;
             num3 = ((num10 != -1) ? tile.slope() : 0);
             bool flag2 = true;
             if (Main.tile[num + num6 * 2, num2 + num10].active() && TileID.Sets.Platforms[Main.tile[num + num6 * 2, num2].type] && num3 == Main.tile[num + num6 * 2, num2 + num10].slope())
             {
                 flag2 = false;
             }
             if (Main.tile[num, num2 - num10].active() && TileID.Sets.Platforms[Main.tile[num, num2 - num10].type] && tile.slope() == Main.tile[num, num2 - num10].slope())
             {
                 flag2 = false;
             }
             if (flag2)
             {
                 WorldGen.SlopeTile(num + num6, num2, num3);
                 num9 = tile.slope();
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(17, -1, -1, null, 14, num + num6, num2, num9);
                 }
             }
         }
         num6 = 1;
         num7 = 0;
         tile = Main.tile[num + num6, num2 + num7];
         if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 0)
         {
             int num11 = (tile.slope() == 1).ToDirectionInt() * num6;
             num3 = ((num11 != -1) ? tile.slope() : 0);
             bool flag3 = true;
             if (Main.tile[num + num6 * 2, num2 + num11].active() && TileID.Sets.Platforms[Main.tile[num + num6 * 2, num2].type] && num3 == Main.tile[num + num6 * 2, num2 + num11].slope())
             {
                 flag3 = false;
             }
             if (Main.tile[num, num2 - num11].active() && TileID.Sets.Platforms[Main.tile[num, num2 - num11].type] && tile.slope() == Main.tile[num, num2 - num11].slope())
             {
                 flag3 = false;
             }
             if (flag3)
             {
                 WorldGen.SlopeTile(num + num6, num2, num3);
                 num9 = tile.slope();
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(17, -1, -1, null, 14, num + num6, num2, num9);
                 }
             }
         }
         if (num4 != num5 || WorldGen.PlatformProperSides(num, num2) != 0)
         {
             return;
         }
         tile = Main.tile[num, num2 + 1];
         if (tile.active() && !tile.halfBrick() && tile.slope() == 0 && Main.tileSolid[tile.type])
         {
             num3 = ((direction != 1) ? 1 : 2);
             WorldGen.SlopeTile(num, num2, num3);
             num9 = Main.tile[num, num2].slope();
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 14, tileTargetX, tileTargetY, num9);
             }
         }
     }
References Tile.active(), Tile.halfBrick(), Main.netMode, WorldGen.PlatformProperSides(), TileID.Sets.Platforms, NetMessage.SendData(), Tile.slope(), WorldGen.SlopeTile(), Main.SmartCursorIsUsed, WorldGen.SolidTile(), Main.tile, Main.tileSolid, and Tile.type.