Terraria: Player.ProcessHitAgainstNPC
ProcessHitAgainstNPC()
void Player.ProcessHitAgainstNPC (Item sItem, Rectangle itemRectangle, int originalDamage, float knockBack, int npcIndex) inline private
     {
         NPC nPC = Main.npc[npcIndex];
         if (nPC.dontTakeDamage || !CanNPCBeHitByPlayerOrPlayerProjectile(nPC))
         {
             if (NPCID.Sets.ZappingJellyfish[nPC.type] && itemRectangle.Intersects(nPC.Hitbox) && (nPC.noTileCollide || CanHit(nPC)))
             {
                 TakeDamageFromJellyfish(npcIndex);
             }
         }
         else
         {
             if (nPC.friendly && (nPC.type != 22 || !killGuide) && (nPC.type != 54 || !killClothier) && (!nPC.isLikeATownNPC || sItem.type != 5129))
             {
                 return;
             }
             Rectangle rectangle = new Rectangle((int)nPC.position.X, (int)nPC.position.Y, nPC.width, nPC.height);
             bool flag = itemRectangle.Intersects(rectangle);
             int type = sItem.type;
             if (type == 121)
             {
                 GetPointOnSwungItemPath(70f, 70f, 0f, GetAdjustedItemScale(sItem), out var location, out var outwardDirection);
                 GetPointOnSwungItemPath(70f, 70f, 0.9f, GetAdjustedItemScale(sItem), out var location2, out outwardDirection);
                 bool flag2 = Utils.LineRectangleDistance(rectangle, location, location2) <= 16f;
                 flag = ((!_spawnVolcanoExplosion) ? (flag || flag2) : flag2);
             }
             if (!flag || (!nPC.noTileCollide && !CanHit(nPC)))
             {
                 return;
             }
             int num = originalDamage;
             bool flag3 = false;
             int weaponCrit = GetWeaponCrit(sItem);
             if (Main.rand.Next(1, 101) <= weaponCrit)
             {
                 flag3 = true;
             }
             int num2 = Item.NPCtoBanner(nPC.BannerID());
             if (num2 > 0 && HasNPCBannerBuff(num2))
             {
                 num = ((!Main.expertMode) ? ((int)((float)num * ItemID.Sets.BannerStrength[Item.BannerToItem(num2)].NormalDamageDealt)) : ((int)((float)num * ItemID.Sets.BannerStrength[Item.BannerToItem(num2)].ExpertDamageDealt)));
             }
             if (parryDamageBuff && sItem.melee)
             {
                 num *= 5;
                 parryDamageBuff = false;
                 ClearBuff(198);
             }
             if (sItem.type == 426 && (float)nPC.life >= (float)nPC.lifeMax * 0.9f)
             {
                 num = (int)((float)num * 2.5f);
             }
             if (sItem.type == 5096)
             {
                 int num3 = 0;
                 if (FindBuffIndex(26) != -1)
                 {
                     num3 = 1;
                 }
                 if (FindBuffIndex(206) != -1)
                 {
                     num3 = 2;
                 }
                 if (FindBuffIndex(207) != -1)
                 {
                     num3 = 3;
                 }
                 float num4 = 1f + 0.05f * (float)num3;
                 num = (int)((float)num * num4);
             }
             if (sItem.type == 671)
             {
                 float t = (float)nPC.life / (float)nPC.lifeMax;
                 float lerpValue = Utils.GetLerpValue(1f, 0.1f, t, clamped: true);
                 float num5 = 1f * lerpValue;
                 num = (int)((float)num * (1f + num5));
                 Vector2 point = itemRectangle.Center.ToVector2();
                 Vector2 positionInWorld = nPC.Hitbox.ClosestPointInRect(point);
                 ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.Keybrand, new ParticleOrchestraSettings
                 {
                     PositionInWorld = positionInWorld
                 }, whoAmI);
             }
             int num6 = Main.DamageVar(num, luck);
             float armorPenetrationPercent = 0f;
             if (sItem.type == 5129 && nPC.isLikeATownNPC)
             {
                 armorPenetrationPercent = 1f;
                 if (nPC.type == 18)
                 {
                     num6 *= 2;
                 }
             }
             if (sItem.type == 3258)
             {
                 ParticleOrchestraSettings particleOrchestraSettings = default(ParticleOrchestraSettings);
                 particleOrchestraSettings.PositionInWorld = nPC.Center;
                 ParticleOrchestraSettings settings = particleOrchestraSettings;
                 ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.SlapHand, settings, whoAmI);
             }
             if (sItem.type == 5382)
             {
                 ParticleOrchestraSettings particleOrchestraSettings = default(ParticleOrchestraSettings);
                 particleOrchestraSettings.PositionInWorld = nPC.Center;
                 ParticleOrchestraSettings settings2 = particleOrchestraSettings;
                 ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.WaffleIron, settings2, whoAmI);
             }
             if (sItem.type == 5129)
             {
                 ParticleOrchestraSettings particleOrchestraSettings = default(ParticleOrchestraSettings);
                 particleOrchestraSettings.PositionInWorld = nPC.Center;
                 ParticleOrchestraSettings settings3 = particleOrchestraSettings;
                 ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.FlyMeal, settings3, whoAmI);
             }
             StatusToNPC(sItem.type, npcIndex);
             if (nPC.life > 5)
             {
                 OnHit(nPC.Center.X, nPC.Center.Y, nPC);
             }
             num6 += nPC.checkArmorPenetration(armorPenetration, armorPenetrationPercent);
             NPCKillAttempt attempt = new NPCKillAttempt(nPC);
             int dmgDone = (int)nPC.StrikeNPC(num6, knockBack, direction, flag3);
             ApplyNPCOnHitEffects(sItem, itemRectangle, num, knockBack, npcIndex, num6, dmgDone);
             int num7 = Item.NPCtoBanner(nPC.BannerID());
             if (num7 >= 0)
             {
                 lastCreatureHit = num7;
             }
             if (Main.netMode != 0)
             {
                 if (flag3)
                 {
                     NetMessage.SendData(28, -1, -1, null, npcIndex, num6, knockBack, direction, 1);
                 }
                 else
                 {
                     NetMessage.SendData(28, -1, -1, null, npcIndex, num6, knockBack, direction);
                 }
             }
             if (accDreamCatcher)
             {
                 addDPS(num6);
             }
             SetMeleeHitCooldown(npcIndex, itemAnimation);
             if (attempt.DidNPCDie())
             {
                 OnKillNPC(ref attempt, sItem);
             }
             ApplyAttackCooldown();
         }
     }
References NPC.BannerID(), ItemID.Sets.BannerStrength, Item.BannerToItem(), Entity.Center, NPC.checkArmorPenetration(), Main.DamageVar(), NPCKillAttempt.DidNPCDie(), NPC.dontTakeDamage, ItemID.BannerEffect.ExpertDamageDealt, Main.expertMode, NPC.friendly, Utils.GetLerpValue(), Entity.height, Entity.Hitbox, NPC.isLikeATownNPC, NPC.life, NPC.lifeMax, Utils.LineRectangleDistance(), Item.melee, Main.netMode, UnifiedRandom.Next(), ItemID.BannerEffect.NormalDamageDealt, NPC.noTileCollide, Main.npc, Item.NPCtoBanner(), Entity.position, ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticleOrchestrator.RequestParticleSpawn(), NetMessage.SendData(), NPC.StrikeNPC(), Item.type, NPC.type, Entity.width, and NPCID.Sets.ZappingJellyfish.