Terraria: Player.OnHit
OnHit()
void Player.OnHit (float x, float y, Entity victim) inline
     {
         if (Main.myPlayer != whoAmI)
         {
             return;
         }
         bool flag = victim is NPC && (((NPC)victim).type == 488 || ((NPC)victim).SpawnedFromStatue);
         if (titaniumStormCooldown > 0)
         {
             flag = true;
         }
         if (victim is NPC)
         {
             Main.BigBossProgressBar.TryTracking(victim.whoAmI);
         }
         if (onHitTitaniumStorm && !flag)
         {
             titaniumStormCooldown = 10;
             AddBuff(306, 600);
             if (ownedProjectileCounts[908] < 7)
             {
                 ownedProjectileCounts[908]++;
                 Projectile.NewProjectile(GetProjectileSource_OnHit(victim, 4), base.Center, Vector2.Zero, 908, 50, 15f, whoAmI);
             }
         }
         if (onHitDodge && shadowDodgeTimer == 0)
         {
             AddBuff(59, 1800);
         }
         if (onHitRegen)
         {
             AddBuff(58, 300);
         }
         if (stardustMinion && victim is NPC)
         {
             for (int i = 0; i < 1000; i++)
             {
                 Projectile projectile = Main.projectile[i];
                 if (projectile.active && projectile.owner == whoAmI && projectile.type == 613 && !(projectile.localAI[1] > 0f) && Main.rand.Next(2) == 0)
                 {
                     Vector2 vector = new Vector2(x, y) - projectile.Center;
                     if (vector.Length() > 0f)
                     {
                         vector.Normalize();
                     }
                     vector *= 20f;
                     Projectile.NewProjectile(Projectile.InheritSource(projectile), projectile.Center.X, projectile.Center.Y, vector.X, vector.Y, 614, projectile.damage / 3, 0f, projectile.owner, 0f, victim.whoAmI);
                     projectile.localAI[1] = 30 + Main.rand.Next(4) * 10;
                 }
             }
         }
         if (onHitPetal && petalTimer == 0)
         {
             petalTimer = 20;
             _ = position.X + (float)(width / 2);
             int num = direction;
             float num2 = Main.screenPosition.X;
             if (num < 0)
             {
                 num2 += (float)Main.screenWidth;
             }
             float y2 = Main.screenPosition.Y;
             y2 += (float)Main.rand.Next(Main.screenHeight);
             Vector2 vector2 = new Vector2(num2, y2);
             float num3 = x - vector2.X;
             float num4 = y - vector2.Y;
             num3 += (float)Main.rand.Next(-50, 51) * 0.1f;
             num4 += (float)Main.rand.Next(-50, 51) * 0.1f;
             float num5 = (float)Math.Sqrt(num3 * num3 + num4 * num4);
             num5 = 24f / num5;
             num3 *= num5;
             num4 *= num5;
             Projectile.NewProjectile(GetProjectileSource_OnHit(victim, 5), num2, y2, num3, num4, 221, 36, 0f, whoAmI);
         }
         if (!crystalLeaf || petalTimer != 0)
         {
             return;
         }
         for (int j = 0; j < 1000; j++)
         {
             if (Main.projectile[j].owner != whoAmI || Main.projectile[j].type != 226)
             {
                 continue;
             }
             petalTimer = 50;
             float num6 = 12f;
             Vector2 vector3 = new Vector2(Main.projectile[j].position.X + (float)width * 0.5f, Main.projectile[j].position.Y + (float)height * 0.5f);
             float num7 = x - vector3.X;
             float num8 = y - vector3.Y;
             float num9 = (float)Math.Sqrt(num7 * num7 + num8 * num8);
             int num10 = 180;
             float num11 = num6 * (float)num10;
             if (!(num9 >= num11))
             {
                 num9 = num6 / num9;
                 num7 *= num9;
                 num8 *= num9;
                 Utils.ChaseResults chaseResults = Utils.GetChaseResults(Main.projectile[j].Center, num6 * (float)num10, victim.Center, victim.velocity);
                 if (chaseResults.InterceptionHappens && chaseResults.InterceptionTime <= 180f)
                 {
                     Vector2 vector4 = chaseResults.ChaserVelocity / num10;
                     num7 = vector4.X;
                     num8 = vector4.Y;
                 }
                 Projectile.NewProjectile(GetProjectileSource_SetBonus(6), Main.projectile[j].Center.X - 4f, Main.projectile[j].Center.Y, num7, num8, 227, crystalLeafDamage, crystalLeafKB, whoAmI);
                 break;
             }
         }
     }
References Entity.active, Main.BigBossProgressBar, Entity.Center, Utils.ChaseResults.ChaserVelocity, Projectile.damage, Utils.GetChaseResults(), Projectile.InheritSource(), Projectile.localAI, Main.myPlayer, Projectile.NewProjectile(), UnifiedRandom.Next(), Projectile.owner, Entity.position, Main.projectile, Main.rand, Main.screenHeight, Main.screenPosition, Main.screenWidth, BigProgressBarSystem.TryTracking(), Projectile.type, Entity.velocity, and Entity.whoAmI.
Referenced by Projectile.TryDoingOnHitEffects().