Terraria: Player.GetFileData
GetFileData()
static PlayerFileData Player.GetFileData (string file, bool cloudSave) inline static
     {
         if (file == null || (cloudSave && SocialAPI.Cloud == null))
         {
             return null;
         }
         PlayerFileData playerFileData = LoadPlayer(file, cloudSave);
         if (playerFileData.Player != null)
         {
             if (playerFileData.Player.loadStatus != 0 && playerFileData.Player.loadStatus != 1)
             {
                 if (FileUtilities.Exists(file + ".bak", cloudSave))
                 {
                     FileUtilities.Move(file + ".bak", file, cloudSave);
                 }
                 playerFileData = LoadPlayer(file, cloudSave);
                 if (playerFileData.Player == null)
                 {
                     return null;
                 }
             }
             return playerFileData;
         }
         return null;
     }
References SocialAPI.Cloud, FileUtilities.Exists(), loadStatus, FileUtilities.Move(), and PlayerFileData.Player.
Referenced by Main.LoadPlayers().