Terraria: Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck
PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck()
bool Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck (bool placed) inline private
     {
         bool flag = inventory[selectedItem].type == 213 || inventory[selectedItem].type == 5295;
         if (flag && !placed && Main.tile[tileTargetX, tileTargetY].type == 1 && Main.tile[tileTargetX, tileTargetY].active())
         {
             int num = 0;
             int num2 = 0;
             Point point = base.Center.ToTileCoordinates();
             Dictionary<ushort, int> dictionary = new Dictionary<ushort, int>();
             WorldUtils.Gen(new Point(point.X - 25, point.Y - 25), new Shapes.Rectangle(50, 50), new Actions.TileScanner(182, 515, 180, 513, 179, 512, 183, 516, 181, 514, 381, 517, 534, 535, 536, 537, 539, 540, 625, 626, 627, 628).Output(dictionary));
             foreach (KeyValuePair<ushort, int> item in dictionary)
             {
                 if (item.Value > num2)
                 {
                     num2 = item.Value;
                     num = item.Key;
                 }
             }
             switch (num)
             {
             case 515:
                 num = 182;
                 break;
             case 513:
                 num = 180;
                 break;
             case 512:
                 num = 179;
                 break;
             case 516:
                 num = 183;
                 break;
             case 514:
                 num = 181;
                 break;
             case 517:
                 num = 381;
                 break;
             case 535:
                 num = 534;
                 break;
             case 537:
                 num = 536;
                 break;
             case 540:
                 num = 539;
                 break;
             case 626:
                 num = 625;
                 break;
             case 628:
                 num = 627;
                 break;
             }
             if (num2 == 0)
             {
                 num = Utils.SelectRandom<int>(Main.rand, 182, 180, 179, 183, 181);
             }
             if (num != 0)
             {
                 Main.tile[tileTargetX, tileTargetY].type = (ushort)num;
                 WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
                 NetMessage.SendTileSquare(-1, tileTargetX, tileTargetY);
                 placed = true;
             }
         }
         if (flag && !placed && Main.tile[tileTargetX, tileTargetY].type == 38 && Main.tile[tileTargetX, tileTargetY].active())
         {
             int num3 = 0;
             int num4 = 0;
             Point point2 = base.Center.ToTileCoordinates();
             Dictionary<ushort, int> dictionary2 = new Dictionary<ushort, int>();
             WorldUtils.Gen(new Point(point2.X - 25, point2.Y - 25), new Shapes.Rectangle(50, 50), new Actions.TileScanner(182, 515, 180, 513, 179, 512, 183, 516, 181, 514, 381, 517, 534, 535, 536, 537, 539, 540, 625, 626, 627, 628).Output(dictionary2));
             foreach (KeyValuePair<ushort, int> item2 in dictionary2)
             {
                 if (item2.Value > num4)
                 {
                     num4 = item2.Value;
                     num3 = item2.Key;
                 }
             }
             switch (num3)
             {
             case 182:
                 num3 = 515;
                 break;
             case 180:
                 num3 = 513;
                 break;
             case 179:
                 num3 = 512;
                 break;
             case 183:
                 num3 = 516;
                 break;
             case 181:
                 num3 = 514;
                 break;
             case 381:
                 num3 = 517;
                 break;
             case 534:
                 num3 = 535;
                 break;
             case 536:
                 num3 = 537;
                 break;
             case 539:
                 num3 = 540;
                 break;
             case 625:
                 num3 = 626;
                 break;
             case 627:
                 num3 = 628;
                 break;
             }
             if (num4 == 0)
             {
                 num3 = Utils.SelectRandom<int>(Main.rand, 515, 513, 512, 516, 514);
             }
             if (num3 != 0)
             {
                 Main.tile[tileTargetX, tileTargetY].type = (ushort)num3;
                 WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
                 NetMessage.SendTileSquare(-1, tileTargetX, tileTargetY);
                 placed = true;
             }
         }
         return placed;
     }
References Tile.active(), WorldUtils.Gen(), Actions.TileScanner.Output(), Main.rand, NetMessage.SendTileSquare(), WorldGen.SquareTileFrame(), Main.tile, and Tile.type.