Terraria: Player.QuickMana
QuickMana()
void Player.QuickMana () inline
     {
         if (cursed || CCed || dead || statMana == statManaMax2)
         {
             return;
         }
         Item item = QuickMana_GetItemToUse();
         if (item != null && ItemCheck_CheckCanUse(item))
         {
             SoundEngine.PlaySound(item.UseSound, position);
             if (item.potion)
             {
                 ApplyPotionDelay(item);
             }
             ApplyLifeAndOrMana(item);
             item.stack--;
             if (item.stack <= 0)
             {
                 item.TurnToAir();
             }
             Recipe.FindRecipes();
         }
     }
References Recipe.FindRecipes(), SoundEngine.PlaySound(), Item.potion, Item.stack, Item.TurnToAir(), and Item.UseSound.