Terraria: Player.ItemCheck_ManageRightClickFeatures_ShieldRaise
ItemCheck_ManageRightClickFeatures_ShieldRaise()
void Player.ItemCheck_ManageRightClickFeatures_ShieldRaise (bool theGeneralCheck) inline
     {
         bool mouseRight = PlayerInput.Triggers.JustPressed.MouseRight;
         if (whoAmI != Main.myPlayer)
         {
             mouseRight = shieldRaised;
             theGeneralCheck = shieldRaised;
         }
         bool shouldGuard = false;
         bool flag = inventory[selectedItem].type == 3823 || inventory[selectedItem].type == 4760;
         if (theGeneralCheck && flag && hasRaisableShield && !mount.Active && (itemAnimation == 0 || mouseRight))
         {
             shouldGuard = true;
         }
         if (shield_parry_cooldown > 0)
         {
             shield_parry_cooldown--;
             if (shield_parry_cooldown == 0)
             {
                 SoundEngine.PlaySound(25, base.Center);
                 for (int i = 0; i < 10; i++)
                 {
                     int num = Dust.NewDust(base.Center + new Vector2(direction * 6 + ((direction == -1) ? (-10) : 0), -14f), 10, 16, 45, 0f, 0f, 255, new Color(255, 100, 0, 127), (float)Main.rand.Next(10, 16) * 0.1f);
                     Main.dust[num].noLight = true;
                     Main.dust[num].noGravity = true;
                     Main.dust[num].velocity *= 0.5f;
                 }
             }
         }
         if (shieldParryTimeLeft > 0 && ++shieldParryTimeLeft > 20)
         {
             shieldParryTimeLeft = 0;
         }
         TryTogglingShield(shouldGuard);
     }
References Color, Main.dust, TriggersPack.JustPressed, TriggersSet.MouseRight, Main.myPlayer, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, SoundEngine.PlaySound(), Main.rand, PlayerInput.Triggers, and Dust.velocity.