Terraria: Player.Teleport
Teleport()
void Player.Teleport (Vector2 newPos, int Style = 0, int extraInfo = 0) inline
     {
         try
         {
             _funkytownAchievementCheckCooldown = 100;
             environmentBuffImmunityTimer = 4;
             if (Style != 10)
             {
                 RemoveAllGrapplingHooks();
             }
             StopVanityActions();
             if (shimmering || shimmerWet)
             {
                 shimmering = false;
                 shimmerWet = false;
                 wet = false;
                 ClearBuff(353);
             }
             int extraInfo2 = 0;
             if (Style == 4)
             {
                 extraInfo2 = lastPortalColorIndex;
             }
             if (Style == 9)
             {
                 lastTeleportPylonStyleUsed = extraInfo;
                 extraInfo2 = lastTeleportPylonStyleUsed;
             }
             float num = MathHelper.Clamp(1f - teleportTime * 0.99f, 0.01f, 1f);
             Vector2 otherPosition = position;
             Main.TeleportEffect(getRect(), Style, extraInfo2, num, TeleportationSide.Entry, newPos);
             float num2 = Vector2.Distance(position, newPos);
             PressurePlateHelper.UpdatePlayerPosition(this);
             position = newPos;
             if (Style == 8)
             {
                 SoundEngine.PlaySound(SoundID.Item6, otherPosition);
                 SoundEngine.PlaySound(SoundID.Item6, newPos);
             }
             fallStart = (int)(position.Y / 16f);
             if (whoAmI == Main.myPlayer)
             {
                 bool flag = false;
                 if (num2 < new Vector2(Main.screenWidth, Main.screenHeight).Length() / 2f + 100f)
                 {
                     int time = 0;
                     if (Style == 1)
                     {
                         time = 10;
                     }
                     Main.SetCameraLerp(0.1f, time);
                     flag = true;
                 }
                 else
                 {
                     NPC.ResetNetOffsets();
                     Main.BlackFadeIn = 255;
                     Lighting.Clear();
                     Main.screenLastPosition = Main.screenPosition;
                     Main.screenPosition.X = position.X + (float)(width / 2) - (float)(Main.screenWidth / 2);
                     Main.screenPosition.Y = position.Y + (float)(height / 2) - (float)(Main.screenHeight / 2);
                     Main.instantBGTransitionCounter = 10;
                     ForceUpdateBiomes();
                 }
                 if (num > 0.1f || !flag || Style != 0)
                 {
                     if (Main.mapTime < 5)
                     {
                         Main.mapTime = 5;
                     }
                     Main.maxQ = true;
                     Main.renderNow = true;
                 }
             }
             if (Style == 4)
             {
                 lastPortalColorIndex = extraInfo;
                 extraInfo2 = lastPortalColorIndex;
                 portalPhysicsFlag = true;
                 gravity = 0f;
             }
             PressurePlateHelper.UpdatePlayerPosition(this);
             ResetAdvancedShadows();
             for (int i = 0; i < 3; i++)
             {
                 UpdateSocialShadow();
             }
             oldPosition = position + BlehOldPositionFixer;
             Main.TeleportEffect(getRect(), Style, extraInfo2, num, TeleportationSide.Exit, otherPosition);
             teleportTime = 1f;
             teleportStyle = Style;
         }
         catch
         {
         }
     }
References Main.BlackFadeIn, Lighting.Clear(), Main.instantBGTransitionCounter, SoundID.Item6, Main.mapTime, Main.maxQ, Main.myPlayer, SoundEngine.PlaySound(), Main.renderNow, NPC.ResetNetOffsets(), Main.screenHeight, Main.screenLastPosition, Main.screenPosition, Main.screenWidth, Main.SetCameraLerp(), Main.TeleportEffect(), and PressurePlateHelper.UpdatePlayerPosition().
Referenced by MessageBuffer.GetData(), TeleportPylonsSystem.HandleTeleportRequest(), Wiring.Teleport(), and PortalHelper.TryGoingThroughPortals().