Terraria: Player.OpenLegacyPresent
OpenLegacyPresent()
void Player.OpenLegacyPresent (int itemType) inline
     {
         IEntitySource itemSource_OpenItem = GetItemSource_OpenItem(itemType);
         int num = Main.rand.Next(14);
         if (num == 0 && Main.hardMode)
         {
             int number = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 602);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(21, -1, -1, null, number, 1f);
             }
         }
         else if (num <= 7)
         {
             int number2 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 586, Main.rand.Next(20, 50));
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(21, -1, -1, null, number2, 1f);
             }
         }
         else
         {
             int number3 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 591, Main.rand.Next(20, 50));
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(21, -1, -1, null, number3, 1f);
             }
         }
     }
References Main.hardMode, Main.netMode, Item.NewItem(), UnifiedRandom.Next(), Main.rand, and NetMessage.SendData().
Referenced by ItemSlot.TryOpenContainer().