Terraria: Player.QuickBuff
QuickBuff()
void Player.QuickBuff () inline
     {
         if (cursed || CCed || dead)
         {
             return;
         }
         LegacySoundStyle legacySoundStyle = null;
         if (CountBuffs() == maxBuffs)
         {
             return;
         }
         Item item = QuickBuff_PickBestFoodItem();
         if (item != null && ItemCheck_CheckCanUse(item))
         {
             legacySoundStyle = item.UseSound;
             int num = item.buffTime;
             if (num == 0)
             {
                 num = 3600;
             }
             AddBuff(item.buffType, num);
             if (item.consumable)
             {
                 item.stack--;
                 if (item.stack <= 0)
                 {
                     item.TurnToAir();
                 }
             }
         }
         if (CountBuffs() != maxBuffs)
         {
             int num2 = 58;
             if (useVoidBag())
             {
                 num2 = 98;
             }
             for (int i = 0; i < num2; i++)
             {
                 Item item2 = ((i >= 58) ? bank4.item[i - 58] : inventory[i]);
                 if (item2.stack <= 0 || item2.type <= 0 || item2.buffType <= 0 || item2.summon || !ItemCheck_CheckCanUse(item2))
                 {
                     continue;
                 }
                 int num3 = item2.buffType;
                 bool flag = QuickBuff_ShouldBotherUsingThisBuff(num3);
                 if (item2.mana > 0 && flag)
                 {
                     if (statMana >= (int)((float)item2.mana * manaCost))
                     {
                         manaRegenDelay = (int)maxRegenDelay;
                         statMana -= (int)((float)item2.mana * manaCost);
                     }
                     else
                     {
                         flag = false;
                     }
                 }
                 if (whoAmI == Main.myPlayer && item2.type == 603 && !Main.runningCollectorsEdition)
                 {
                     flag = false;
                 }
                 if (num3 == 27)
                 {
                     num3 = Main.rand.Next(3);
                     if (num3 == 0)
                     {
                         num3 = 27;
                     }
                     if (num3 == 1)
                     {
                         num3 = 101;
                     }
                     if (num3 == 2)
                     {
                         num3 = 102;
                     }
                 }
                 if (!flag)
                 {
                     continue;
                 }
                 legacySoundStyle = item2.UseSound;
                 int num4 = item2.buffTime;
                 if (num4 == 0)
                 {
                     num4 = 3600;
                 }
                 AddBuff(num3, num4);
                 if (item2.consumable)
                 {
                     item2.stack--;
                     if (item2.stack <= 0)
                     {
                         item2.TurnToAir();
                     }
                 }
                 if (CountBuffs() == maxBuffs)
                 {
                     break;
                 }
             }
         }
         if (legacySoundStyle != null)
         {
             SoundEngine.PlaySound(legacySoundStyle, position);
             Recipe.FindRecipes();
         }
     }
References Item.buffTime, Item.buffType, Item.consumable, Recipe.FindRecipes(), Item.mana, Main.myPlayer, UnifiedRandom.Next(), SoundEngine.PlaySound(), Main.rand, Main.runningCollectorsEdition, Item.stack, Item.summon, Item.TurnToAir(), Item.type, and Item.UseSound.
Referenced by TriggersSet.CopyInto().