Terraria: Player.StickyMovement
StickyMovement()
void Player.StickyMovement () inline
     {
         if (shimmering)
         {
             return;
         }
         bool flag = false;
         if (mount.Type > 0 && MountID.Sets.Cart[mount.Type] && Math.Abs(velocity.X) > 5f)
         {
             flag = true;
         }
         int num = width / 2;
         int num2 = height / 2;
         new Vector2(position.X + (float)(width / 2) - (float)(num / 2), position.Y + (float)(height / 2) - (float)(num2 / 2));
         Vector2 vector = Collision.StickyTiles(position, velocity, width, height);
         if (vector.Y != -1f && vector.X != -1f)
         {
             int num3 = (int)vector.X;
             int num4 = (int)vector.Y;
             int type = Main.tile[num3, num4].type;
             if (whoAmI == Main.myPlayer && type == 51 && (velocity.X != 0f || velocity.Y != 0f))
             {
                 stickyBreak++;
                 if (stickyBreak > Main.rand.Next(20, 100) || flag)
                 {
                     stickyBreak = 0;
                     WorldGen.KillTile(num3, num4);
                     if (Main.netMode == 1 && !Main.tile[num3, num4].active() && Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 0, num3, num4);
                     }
                 }
             }
             if (flag)
             {
                 return;
             }
             fallStart = (int)(position.Y / 16f);
             if (type != 229)
             {
                 jump = 0;
             }
             if (velocity.X > 1f)
             {
                 velocity.X = 1f;
             }
             if (velocity.X < -1f)
             {
                 velocity.X = -1f;
             }
             if ((double)velocity.X > 0.75 || (double)velocity.X < -0.75)
             {
                 velocity.X *= 0.85f;
             }
             else
             {
                 velocity.X *= 0.6f;
             }
             if (gravDir == -1f)
             {
                 if (velocity.Y < -1f)
                 {
                     velocity.Y = -1f;
                 }
                 if (velocity.Y > 5f)
                 {
                     velocity.Y = 5f;
                 }
                 if (velocity.Y > 0f)
                 {
                     velocity.Y *= 0.96f;
                 }
                 else
                 {
                     velocity.Y *= 0.3f;
                 }
             }
             else
             {
                 if (velocity.Y > 1f)
                 {
                     velocity.Y = 1f;
                 }
                 if (velocity.Y < -5f)
                 {
                     velocity.Y = -5f;
                 }
                 if (velocity.Y < 0f)
                 {
                     velocity.Y *= 0.96f;
                 }
                 else
                 {
                     velocity.Y *= 0.3f;
                 }
             }
             if (type != 229 || Main.rand.Next(5) != 0 || (!((double)velocity.Y > 0.15) && !(velocity.Y < 0f)))
             {
                 return;
             }
             if ((float)(num3 * 16) < position.X + (float)(width / 2))
             {
                 int num5 = Dust.NewDust(new Vector2(position.X - 4f, num4 * 16), 4, 16, 153, 0f, 0f, 50);
                 Main.dust[num5].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                 Main.dust[num5].velocity *= 0.1f;
                 Main.dust[num5].noGravity = true;
             }
             else
             {
                 int num6 = Dust.NewDust(new Vector2(position.X + (float)width - 2f, num4 * 16), 4, 16, 153, 0f, 0f, 50);
                 Main.dust[num6].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                 Main.dust[num6].velocity *= 0.1f;
                 Main.dust[num6].noGravity = true;
             }
             if (Main.tile[num3, num4 + 1] != null && Main.tile[num3, num4 + 1].type == 229 && position.Y + (float)height > (float)((num4 + 1) * 16))
             {
                 if ((float)(num3 * 16) < position.X + (float)(width / 2))
                 {
                     int num7 = Dust.NewDust(new Vector2(position.X - 4f, num4 * 16 + 16), 4, 16, 153, 0f, 0f, 50);
                     Main.dust[num7].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                     Main.dust[num7].velocity *= 0.1f;
                     Main.dust[num7].noGravity = true;
                 }
                 else
                 {
                     int num8 = Dust.NewDust(new Vector2(position.X + (float)width - 2f, num4 * 16 + 16), 4, 16, 153, 0f, 0f, 50);
                     Main.dust[num8].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                     Main.dust[num8].velocity *= 0.1f;
                     Main.dust[num8].noGravity = true;
                 }
             }
             if (Main.tile[num3, num4 + 2] != null && Main.tile[num3, num4 + 2].type == 229 && position.Y + (float)height > (float)((num4 + 2) * 16))
             {
                 if ((float)(num3 * 16) < position.X + (float)(width / 2))
                 {
                     int num9 = Dust.NewDust(new Vector2(position.X - 4f, num4 * 16 + 32), 4, 16, 153, 0f, 0f, 50);
                     Main.dust[num9].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                     Main.dust[num9].velocity *= 0.1f;
                     Main.dust[num9].noGravity = true;
                 }
                 else
                 {
                     int num10 = Dust.NewDust(new Vector2(position.X + (float)width - 2f, num4 * 16 + 32), 4, 16, 153, 0f, 0f, 50);
                     Main.dust[num10].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                     Main.dust[num10].velocity *= 0.1f;
                     Main.dust[num10].noGravity = true;
                 }
             }
         }
         else
         {
             stickyBreak = 0;
         }
     }
References Tile.active(), MountID.Sets.Cart, Main.dust, WorldGen.KillTile(), Main.myPlayer, Main.netMode, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Main.rand, Dust.scale, NetMessage.SendData(), Collision.StickyTiles(), Main.tile, Tile.type, and Dust.velocity.