Terraria: Player.DryCollision
DryCollision()
void Player.DryCollision (bool fallThrough, bool ignorePlats) inline
     {
         int num = ((!onTrack) ? height : (height - 10));
         if (velocity.Length() > 16f)
         {
             Vector2 vector = Collision.TileCollision(position, velocity, width, num, fallThrough, ignorePlats, (int)gravDir);
             float num2 = velocity.Length();
             Vector2 vector2 = Vector2.Normalize(velocity);
             if (vector.Y == 0f)
             {
                 vector2.Y = 0f;
             }
             Vector2 zero = Vector2.Zero;
             bool flag = mount.Type == 7 || mount.Type == 8 || mount.Type == 12 || mount.Type == 44 || mount.Type == 49;
             _ = Vector2.Zero;
             while (num2 > 0f)
             {
                 float num3 = num2;
                 if (num3 > 16f)
                 {
                     num3 = 16f;
                 }
                 num2 -= num3;
                 Vector2 vector3 = vector2 * num3;
                 velocity = vector3;
                 SlopeDownMovement();
                 vector3 = velocity;
                 if (velocity.Y == gravity && (!mount.Active || (!mount.Cart && mount.Type != 48 && !flag)))
                 {
                     Collision.StepDown(ref position, ref vector3, width, height, ref stepSpeed, ref gfxOffY, (int)gravDir, waterWalk || waterWalk2);
                 }
                 if (gravDir == -1f)
                 {
                     if ((carpetFrame != -1 || velocity.Y <= gravity) && !controlUp)
                     {
                         Collision.StepUp(ref position, ref vector3, width, height, ref stepSpeed, ref gfxOffY, (int)gravDir, controlUp);
                     }
                 }
                 else if (flag || ((carpetFrame != -1 || velocity.Y >= gravity) && !controlDown && !mount.Cart))
                 {
                     Collision.StepUp(ref position, ref vector3, width, height, ref stepSpeed, ref gfxOffY, (int)gravDir, controlUp);
                 }
                 Vector2 vector4 = Collision.TileCollision(position, vector3, width, num, fallThrough, ignorePlats, (int)gravDir);
                 if (Collision.up && gravDir == 1f)
                 {
                     jump = 0;
                 }
                 if (waterWalk || waterWalk2)
                 {
                     Vector2 vector5 = velocity;
                     vector4 = Collision.WaterCollision(position, vector4, width, height, fallThrough, fall2: false, waterWalk);
                     if (vector5 != velocity)
                     {
                         fallStart = (int)(position.Y / 16f);
                     }
                 }
                 position += vector4;
                 bool falling = false;
                 if (vector4.Y > gravity)
                 {
                     falling = true;
                 }
                 if (vector4.Y < 0f - gravity)
                 {
                     falling = true;
                 }
                 velocity = vector4;
                 UpdateTouchingTiles();
                 TryBouncingBlocks(falling);
                 TryLandingOnDetonator();
                 SlopingCollision(fallThrough, ignorePlats);
                 Collision.StepConveyorBelt(this, gravDir);
                 vector4 = velocity;
                 zero += vector4;
             }
             velocity = zero;
             return;
         }
         velocity = Collision.TileCollision(position, velocity, width, num, fallThrough, ignorePlats, (int)gravDir);
         if (Collision.up && gravDir == 1f)
         {
             jump = 0;
         }
         if (waterWalk || waterWalk2)
         {
             Vector2 vector6 = velocity;
             velocity = Collision.WaterCollision(position, velocity, width, height, fallThrough, fall2: false, waterWalk);
             if (vector6 != velocity)
             {
                 fallStart = (int)(position.Y / 16f);
             }
         }
         position += velocity;
     }
References Collision.StepConveyorBelt(), Collision.StepDown(), Collision.StepUp(), Collision.TileCollision(), Collision.up, and Collision.WaterCollision().