Terraria: Player.ApplyPaint
ApplyPaint()
void Player.ApplyPaint (int x, int y, bool paintingAWall, bool applyItemAnimation, Item targetItem) inline private
     {
         byte paint = targetItem.paint;
         if (paintingAWall)
         {
             if (Main.tile[x, y].wallColor() != paint && WorldGen.paintWall(x, y, paint, broadCast: true))
             {
                 targetItem.stack--;
                 if (targetItem.stack <= 0)
                 {
                     targetItem.SetDefaults();
                 }
                 if (applyItemAnimation)
                 {
                     ApplyItemTime(inventory[selectedItem], wallSpeed);
                 }
             }
         }
         else if (Main.tile[x, y].color() != paint && WorldGen.paintTile(x, y, paint, broadCast: true))
         {
             targetItem.stack--;
             if (targetItem.stack <= 0)
             {
                 targetItem.SetDefaults();
             }
             if (applyItemAnimation)
             {
                 ApplyItemTime(inventory[selectedItem], tileSpeed);
             }
         }
     }
References Tile.color(), Item.paint, WorldGen.paintTile(), WorldGen.paintWall(), Item.SetDefaults(), Item.stack, Main.tile, and Tile.wallColor().