Terraria: Player.UpdateDyes
UpdateDyes()
void Player.UpdateDyes () inline
     {
         cShieldFallback = -1;
         cHead = (cBody = (cLegs = (cHandOn = (cHandOff = (cBack = (cFront = (cShoe = (cWaist = (cShield = (cNeck = (cFace = (cFaceHead = (cFaceFlower = (cBalloon = (cBalloon = (cWings = (cCarpet = (cFloatingTube = (cBackpack = (cTail = 0))))))))))))))))))));
         cGrapple = (cMount = (cMinecart = (cPet = (cLight = (cYorai = (cPortableStool = (cUnicornHorn = (cAngelHalo = (cBeard = (cMinion = (cLeinShampoo = (cFlameWaker = 0))))))))))));
         skinDyePacked = 0;
         cHead = dye[0].dye;
         cBody = dye[1].dye;
         cLegs = dye[2].dye;
         if (wearsRobe)
         {
             cLegs = cBody;
         }
         cPet = miscDyes[0].dye;
         cLight = miscDyes[1].dye;
         cMinecart = miscDyes[2].dye;
         cMount = miscDyes[3].dye;
         cGrapple = miscDyes[4].dye;
         for (int i = 0; i < 20; i++)
         {
             if (IsItemSlotUnlockedAndUsable(i))
             {
                 int num = i % 10;
                 UpdateItemDye(i < 10, hideVisibleAccessory[num], armor[i], dye[num]);
             }
         }
         cYorai = cPet;
     }
Referenced by TEDisplayDoll.Draw(), TEHatRack.Draw(), Segments.PlayerSegment.Draw(), Main.DrawSuperSpecialProjectiles(), and UICharacter.Update().