Terraria: Player.QuickGrapple
QuickGrapple()
void Player.QuickGrapple () inline
     {
         if (frozen || tongued || webbed || stoned || dead)
         {
             return;
         }
         if (PlayerInput.GrappleAndInteractAreShared)
         {
             if (Main.HoveringOverAnNPC || Main.SmartInteractShowingGenuine || Main.SmartInteractShowingFake || (_quickGrappleCooldown > 0 && !Main.mapFullscreen) || (WiresUI.Settings.DrawToolModeUI && PlayerInput.UsingGamepad))
             {
                 return;
             }
             bool num = controlUseTile;
             bool flag = releaseUseTile;
             if (!num && !flag)
             {
                 return;
             }
             Tile tileSafely = Framing.GetTileSafely(tileTargetX, tileTargetY);
             if ((tileSafely.active() && (tileSafely.type == 4 || tileSafely.type == 33 || tileSafely.type == 372 || tileSafely.type == 174 || tileSafely.type == 646 || tileSafely.type == 49)) || (inventory[selectedItem].type == 3384 && PlayerInput.UsingGamepad))
             {
                 return;
             }
         }
         if (noItems)
         {
             return;
         }
         if (mount.Active)
         {
             mount.Dismount(this);
         }
         Item item = QuickGrapple_GetItemToUse();
         if (item == null || !ItemCheck_CheckCanUse(item))
         {
             return;
         }
         if (item.shoot == 73)
         {
             int num2 = 0;
             for (int i = 0; i < 1000; i++)
             {
                 if (Main.projectile[i].active && Main.projectile[i].owner == Main.myPlayer && (Main.projectile[i].type == 73 || Main.projectile[i].type == 74))
                 {
                     num2++;
                 }
             }
             if (num2 > 1)
             {
                 item = null;
             }
         }
         else if (item.shoot == 165)
         {
             int num3 = 0;
             for (int j = 0; j < 1000; j++)
             {
                 if (Main.projectile[j].active && Main.projectile[j].owner == Main.myPlayer && Main.projectile[j].type == 165)
                 {
                     num3++;
                 }
             }
             if (num3 > 8)
             {
                 item = null;
             }
         }
         else if (item.shoot == 372)
         {
             int num4 = 0;
             for (int k = 0; k < 1000; k++)
             {
                 if (Main.projectile[k].active && Main.projectile[k].owner == Main.myPlayer && Main.projectile[k].type == 372)
                 {
                     num4++;
                 }
             }
             if (num4 > 2)
             {
                 item = null;
             }
         }
         else if (item.shoot == 652)
         {
             int num5 = 0;
             for (int l = 0; l < 1000; l++)
             {
                 if (Main.projectile[l].active && Main.projectile[l].owner == Main.myPlayer && Main.projectile[l].type == 652)
                 {
                     num5++;
                 }
             }
             if (num5 > 1)
             {
                 item = null;
             }
         }
         else if (item.type == 3572)
         {
             int num6 = 0;
             bool flag2 = false;
             for (int m = 0; m < 1000; m++)
             {
                 if (Main.projectile[m].active && Main.projectile[m].owner == Main.myPlayer && Main.projectile[m].type >= 646 && Main.projectile[m].type <= 649)
                 {
                     num6++;
                     if (Main.projectile[m].ai[0] == 2f)
                     {
                         flag2 = true;
                     }
                 }
             }
             if (num6 > 4 || (!flag2 && num6 > 3))
             {
                 item = null;
             }
         }
         else
         {
             for (int n = 0; n < 1000; n++)
             {
                 if (Main.projectile[n].active && Main.projectile[n].owner == Main.myPlayer && Main.projectile[n].type == item.shoot && Main.projectile[n].ai[0] != 2f)
                 {
                     item = null;
                     break;
                 }
             }
         }
         if (item == null)
         {
             return;
         }
         UpdateBlacklistedTilesForGrappling();
         SoundEngine.PlaySound(item.UseSound, position);
         if (Main.netMode == 1 && whoAmI == Main.myPlayer)
         {
             NetMessage.SendData(51, -1, -1, null, whoAmI, 2f);
         }
         int num7 = item.shoot;
         float shootSpeed = item.shootSpeed;
         int damage = item.damage;
         float knockBack = item.knockBack;
         if (num7 == 13 || num7 == 32 || num7 == 315 || (num7 >= 230 && num7 <= 235) || num7 == 331 || num7 == 753 || num7 == 865 || num7 == 935)
         {
             grappling[0] = -1;
             grapCount = 0;
             for (int num8 = 0; num8 < 1000; num8++)
             {
                 if (Main.projectile[num8].active && Main.projectile[num8].owner == whoAmI)
                 {
                     switch (Main.projectile[num8].type)
                     {
                     case 13:
                     case 230:
                     case 231:
                     case 232:
                     case 233:
                     case 234:
                     case 235:
                     case 315:
                     case 331:
                     case 753:
                     case 865:
                     case 935:
                         Main.projectile[num8].Kill();
                         break;
                     }
                 }
             }
         }
         if (num7 == 256)
         {
             int num9 = 0;
             int num10 = -1;
             int num11 = 100000;
             for (int num12 = 0; num12 < 1000; num12++)
             {
                 if (Main.projectile[num12].active && Main.projectile[num12].owner == whoAmI && Main.projectile[num12].type == 256)
                 {
                     num9++;
                     if (Main.projectile[num12].timeLeft < num11)
                     {
                         num10 = num12;
                         num11 = Main.projectile[num12].timeLeft;
                     }
                 }
             }
             if (num9 > 1)
             {
                 Main.projectile[num10].Kill();
             }
         }
         if (num7 == 652)
         {
             int num13 = 0;
             int num14 = -1;
             int num15 = 100000;
             for (int num16 = 0; num16 < 1000; num16++)
             {
                 if (Main.projectile[num16].active && Main.projectile[num16].owner == whoAmI && Main.projectile[num16].type == 652)
                 {
                     num13++;
                     if (Main.projectile[num16].timeLeft < num15)
                     {
                         num14 = num16;
                         num15 = Main.projectile[num16].timeLeft;
                     }
                 }
             }
             if (num13 > 1)
             {
                 Main.projectile[num14].Kill();
             }
         }
         if (num7 == 73)
         {
             for (int num17 = 0; num17 < 1000; num17++)
             {
                 if (Main.projectile[num17].active && Main.projectile[num17].owner == whoAmI && Main.projectile[num17].type == 73)
                 {
                     num7 = 74;
                 }
             }
         }
         if (item.type == 3572)
         {
             int num18 = -1;
             int num19 = -1;
             for (int num20 = 0; num20 < 1000; num20++)
             {
                 Projectile projectile = Main.projectile[num20];
                 if (projectile.active && projectile.owner == whoAmI && projectile.type >= 646 && projectile.type <= 649 && (num19 == -1 || num19 < projectile.timeLeft))
                 {
                     num18 = projectile.type;
                     num19 = projectile.timeLeft;
                 }
             }
             switch (num18)
             {
             case 646:
                 num7 = 647;
                 break;
             case 647:
                 num7 = 648;
                 break;
             case 648:
                 num7 = 649;
                 break;
             case -1:
             case 649:
                 num7 = 646;
                 break;
             }
         }
         Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
         float num21 = (float)Main.mouseX + Main.screenPosition.X - vector.X;
         float num22 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
         if (gravDir == -1f)
         {
             num22 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - vector.Y;
         }
         float num23 = (float)Math.Sqrt(num21 * num21 + num22 * num22);
         if ((float.IsNaN(num21) && float.IsNaN(num22)) || (num21 == 0f && num22 == 0f))
         {
             num21 = direction;
             num22 = 0f;
             num23 = shootSpeed;
         }
         else
         {
             num23 = shootSpeed / num23;
         }
         num21 *= num23;
         num22 *= num23;
         Projectile.NewProjectile(GetProjectileSource_Item(item), vector.X, vector.Y, num21, num22, num7, damage, knockBack, whoAmI);
     }
References Entity.active, Tile.active(), Projectile.ai, Item.damage, WiresUI.Settings.DrawToolModeUI, Framing.GetTileSafely(), PlayerInput.GrappleAndInteractAreShared, Main.HoveringOverAnNPC, Projectile.Kill(), Item.knockBack, Main.mapFullscreen, Main.mouseX, Main.mouseY, Main.myPlayer, Main.netMode, Projectile.NewProjectile(), Projectile.owner, SoundEngine.PlaySound(), Main.projectile, Main.screenHeight, Main.screenPosition, NetMessage.SendData(), Item.shoot, Item.shootSpeed, Main.SmartInteractShowingFake, Main.SmartInteractShowingGenuine, Projectile.timeLeft, Item.type, Projectile.type, Tile.type, Item.UseSound, and PlayerInput.UsingGamepad.