Terraria: Player.ItemSpace
ItemSpace()
ItemSpaceStatus Player.ItemSpace (Item newItem) inline
     {
         if (ItemID.Sets.IsAPickup[newItem.type])
         {
             return new ItemSpaceStatus(CanTakeItem: true);
         }
         if (newItem.uniqueStack && HasItem(newItem.type))
         {
             return new ItemSpaceStatus(CanTakeItem: false);
         }
         int num = 50;
         if (newItem.IsACoin)
         {
             num = 54;
         }
         for (int i = 0; i < num; i++)
         {
             if (CanItemSlotAccept(inventory[i], newItem))
             {
                 return new ItemSpaceStatus(CanTakeItem: true);
             }
         }
         if (newItem.ammo > 0 && !newItem.notAmmo)
         {
             for (int j = 54; j < 58; j++)
             {
                 if (CanGoIntoAmmoOnPickup(inventory[j], newItem))
                 {
                     return new ItemSpaceStatus(CanTakeItem: true);
                 }
             }
         }
         for (int k = 54; k < 58; k++)
         {
             if (inventory[k].type > 0 && inventory[k].stack < inventory[k].maxStack && newItem.IsTheSameAs(inventory[k]))
             {
                 return new ItemSpaceStatus(CanTakeItem: true);
             }
         }
         if (ItemSpaceForCofveve(newItem))
         {
             return new ItemSpaceStatus(CanTakeItem: true, ItemIsGoingToVoidVault: true);
         }
         return new ItemSpaceStatus(CanTakeItem: false);
     }
References Item.ammo, Item.IsACoin, ItemID.Sets.IsAPickup, Item.IsTheSameAs(), Item.notAmmo, Item.type, and Item.uniqueStack.
Referenced by Item.FindOwner(), ItemSlot.GetOverrideInstructions(), ItemSlot.OverrideHover(), TEDisplayDoll.OverrideItemSlotHover(), TEHatRack.OverrideItemSlotHover(), Main.TryAllowingToCraftRecipe(), ItemSlot.TryEnteringBuildingMode(), TEDisplayDoll.TryGetItemGamepadOverrideInstructions(), and TEHatRack.TryGetItemGamepadOverrideInstructions().