Terraria: Player.DoBootsEffect_PlaceFlamesOnTile
DoBootsEffect_PlaceFlamesOnTile()
bool Player.DoBootsEffect_PlaceFlamesOnTile (int X, int Y) inline
     {
         Tile tile = Main.tile[X, Y + 1];
         if (tile == null || !tile.active() || tile.liquid > 0 || !WorldGen.SolidTileAllowBottomSlope(X, Y + 1))
         {
             return false;
         }
         ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.FlameWaders, new ParticleOrchestraSettings
         {
             PositionInWorld = new Vector2(X * 16 + 8, Y * 16 + 16)
         }, whoAmI);
         return true;
     }
References Tile.active(), Tile.liquid, ParticleOrchestrator.RequestParticleSpawn(), WorldGen.SolidTileAllowBottomSlope(), Main.tile, X, and Y.