Terraria: Player.TeleportationPotion
TeleportationPotion()
void Player.TeleportationPotion () inline
     {
         bool canSpawn = false;
         int teleportStartX = 100;
         int teleportRangeX = Main.maxTilesX - 200;
         int teleportStartY = 100;
         int underworldLayer = Main.UnderworldLayer;
         Vector2 vector = CheckForGoodTeleportationSpot(ref canSpawn, teleportStartX, teleportRangeX, teleportStartY, underworldLayer, new RandomTeleportationAttemptSettings
         {
             avoidLava = true,
             avoidHurtTiles = true,
             maximumFallDistanceFromOrignalPoint = 100,
             attemptsBeforeGivingUp = 1000
         });
         if (canSpawn)
         {
             Vector2 newPos = vector;
             Teleport(newPos, 2);
             velocity = Vector2.Zero;
             if (Main.netMode == 2)
             {
                 RemoteClient.CheckSection(whoAmI, position);
                 NetMessage.SendData(65, -1, -1, null, 0, whoAmI, newPos.X, newPos.Y, 2);
             }
         }
         else
         {
             Vector2 newPos2 = position;
             Teleport(newPos2, 2);
             velocity = Vector2.Zero;
             if (Main.netMode == 2)
             {
                 RemoteClient.CheckSection(whoAmI, position);
                 NetMessage.SendData(65, -1, -1, null, 0, whoAmI, newPos2.X, newPos2.Y, 2, 1);
             }
         }
     }
References RemoteClient.CheckSection(), Main.maxTilesX, Main.netMode, NetMessage.SendData(), and Main.UnderworldLayer.
Referenced by MessageBuffer.GetData().