Terraria: Player.UpdateBiomes
UpdateBiomes()
void Player.UpdateBiomes () inline
     {
         //IL_11ac: Unknown result type (might be due to invalid IL or missing references)
         //IL_11b6: Unknown result type (might be due to invalid IL or missing references)
         //IL_11c9: Unknown result type (might be due to invalid IL or missing references)
         //IL_11ce: Unknown result type (might be due to invalid IL or missing references)
         //IL_1255: Unknown result type (might be due to invalid IL or missing references)
         //IL_1261: Unknown result type (might be due to invalid IL or missing references)
         //IL_11e6: Unknown result type (might be due to invalid IL or missing references)
         //IL_11f1: Unknown result type (might be due to invalid IL or missing references)
         //IL_11dc: Unknown result type (might be due to invalid IL or missing references)
         //IL_11e1: Unknown result type (might be due to invalid IL or missing references)
         //IL_12ef: Unknown result type (might be due to invalid IL or missing references)
         //IL_12f4: Unknown result type (might be due to invalid IL or missing references)
         //IL_1282: Unknown result type (might be due to invalid IL or missing references)
         //IL_1287: Unknown result type (might be due to invalid IL or missing references)
         //IL_128c: Unknown result type (might be due to invalid IL or missing references)
         //IL_12b0: Unknown result type (might be due to invalid IL or missing references)
         //IL_12b5: Unknown result type (might be due to invalid IL or missing references)
         //IL_12ba: Unknown result type (might be due to invalid IL or missing references)
         //IL_130b: Unknown result type (might be due to invalid IL or missing references)
         //IL_1310: Unknown result type (might be due to invalid IL or missing references)
         Point point = base.Center.ToTileCoordinates();
         ZoneDungeon = false;
         if (Main.SceneMetrics.DungeonTileCount >= 250 && (double)base.Center.Y > Main.worldSurface * 16.0)
         {
             int num = (int)base.Center.X / 16;
             int num2 = (int)base.Center.Y / 16;
             if (Main.tile[num, num2] != null && Main.wallDungeon[Main.tile[num, num2].wall])
             {
                 ZoneDungeon = true;
             }
         }
         ZoneLihzhardTemple = false;
         int num3 = (int)base.Center.X / 16;
         int num4 = (int)base.Center.Y / 16;
         if (Main.tile[num3, num4] != null && Main.tile[num3, num4].wall == 87)
         {
             ZoneLihzhardTemple = true;
         }
         Tile tileSafely = Framing.GetTileSafely(base.Center);
         if (tileSafely != null)
         {
             behindBackWall = tileSafely.wall > 0;
         }
         if (behindBackWall && ZoneDesert && (double)base.Center.Y > Main.worldSurface)
         {
             if (WallID.Sets.Conversion.Sandstone[tileSafely.wall] || WallID.Sets.Conversion.HardenedSand[tileSafely.wall])
             {
                 ZoneUndergroundDesert = true;
             }
         }
         else
         {
             ZoneUndergroundDesert = false;
         }
         if (behindBackWall && (tileSafely.wall == 184 || tileSafely.wall == 180))
         {
             ZoneGranite = true;
         }
         else
         {
             ZoneGranite = false;
         }
         if (behindBackWall && (tileSafely.wall == 183 || tileSafely.wall == 178))
         {
             ZoneMarble = true;
         }
         else
         {
             ZoneMarble = false;
         }
         if (behindBackWall && (tileSafely.wall == 108 || tileSafely.wall == 86))
         {
             ZoneHive = true;
         }
         else
         {
             ZoneHive = false;
         }
         if (behindBackWall && tileSafely.wall >= 48 && tileSafely.wall <= 53)
         {
             ZoneGemCave = true;
         }
         else
         {
             ZoneGemCave = false;
         }
         bool flag = (double)(Main.screenPosition.Y / 16f) > Main.worldSurface + 50.0 && Main.screenPosition.Y / 16f < (float)(Main.maxTilesY - 330 - 100);
         ZoneShimmer = Main.SceneMetrics.EnoughTilesForShimmer && flag;
         ZoneCorrupt = Main.SceneMetrics.EnoughTilesForCorruption;
         ZoneCrimson = Main.SceneMetrics.EnoughTilesForCrimson;
         ZoneHallow = Main.SceneMetrics.EnoughTilesForHallow;
         ZoneJungle = Main.SceneMetrics.EnoughTilesForJungle && position.Y / 16f < (float)Main.UnderworldLayer;
         ZoneSnow = Main.SceneMetrics.EnoughTilesForSnow;
         ZoneDesert = Main.SceneMetrics.EnoughTilesForDesert;
         ZoneGlowshroom = Main.SceneMetrics.EnoughTilesForGlowingMushroom;
         ZoneMeteor = Main.SceneMetrics.EnoughTilesForMeteor;
         ZoneWaterCandle = Main.SceneMetrics.WaterCandleCount > 0;
         ZonePeaceCandle = Main.SceneMetrics.PeaceCandleCount > 0;
         ZoneShadowCandle = Main.SceneMetrics.ShadowCandleCount > 0;
         ZoneGraveyard = Main.SceneMetrics.EnoughTilesForGraveyard;
         UpdateGraveyard();
         if (HasGardenGnomeNearby != Main.SceneMetrics.HasGardenGnome)
         {
             luckNeedsSync = true;
             HasGardenGnomeNearby = Main.SceneMetrics.HasGardenGnome;
         }
         ZoneUnderworldHeight = point.Y > Main.UnderworldLayer;
         ZoneRockLayerHeight = point.Y <= Main.UnderworldLayer && (double)point.Y > Main.rockLayer;
         ZoneDirtLayerHeight = (double)point.Y <= Main.rockLayer && (double)point.Y > Main.worldSurface;
         ZoneOverworldHeight = (double)point.Y <= Main.worldSurface && (double)point.Y > Main.worldSurface * 0.3499999940395355;
         ZoneSkyHeight = (double)point.Y <= Main.worldSurface * 0.3499999940395355;
         ZoneBeach = WorldGen.oceanDepths(point.X, point.Y);
         ZoneRain = Main.raining && (double)point.Y <= Main.worldSurface;
         if (Main.remixWorld)
         {
             ZoneSandstorm = (double)point.Y >= Main.rockLayer && ZoneDesert && !ZoneBeach && Sandstorm.Happening;
         }
         else
         {
             ZoneSandstorm = (double)point.Y <= Main.worldSurface && ZoneDesert && !ZoneBeach && Sandstorm.Happening;
         }
         bool flag3 = (ZoneTowerStardust = false);
         bool flag5 = (ZoneTowerNebula = flag3);
         bool zoneTowerSolar = (ZoneTowerVortex = flag5);
         ZoneTowerSolar = zoneTowerSolar;
         ZoneOldOneArmy = false;
         Vector2 vector = Vector2.Zero;
         Vector2 vector2 = Vector2.Zero;
         Vector2 vector3 = Vector2.Zero;
         Vector2 vector4 = Vector2.Zero;
         _ = Vector2.Zero;
         for (int i = 0; i < 200; i++)
         {
             if (!Main.npc[i].active)
             {
                 continue;
             }
             if (Main.npc[i].type == 493)
             {
                 if (Distance(Main.npc[i].Center) <= 4000f)
                 {
                     ZoneTowerStardust = true;
                     vector4 = Main.npc[i].Center;
                 }
             }
             else if (Main.npc[i].type == 507)
             {
                 if (Distance(Main.npc[i].Center) <= 4000f)
                 {
                     ZoneTowerNebula = true;
                     vector3 = Main.npc[i].Center;
                 }
             }
             else if (Main.npc[i].type == 422)
             {
                 if (Distance(Main.npc[i].Center) <= 4000f)
                 {
                     ZoneTowerVortex = true;
                     vector2 = Main.npc[i].Center;
                 }
             }
             else if (Main.npc[i].type == 517)
             {
                 if (Distance(Main.npc[i].Center) <= 4000f)
                 {
                     ZoneTowerSolar = true;
                     vector = Main.npc[i].Center;
                 }
             }
             else if (Main.npc[i].type == 549 && Distance(Main.npc[i].Center) <= 4000f)
             {
                 ZoneOldOneArmy = true;
                 vector = Main.npc[i].Center;
             }
         }
         float num5 = 1f;
         float num6 = 1f;
         float num7 = Main.shimmerAlpha;
         if (CanSeeShimmerEffects())
         {
             num5 *= 1f;
             num6 *= 0.7f;
             if (num7 < 1f)
             {
                 num7 += 0.025f;
                 if (num7 > 1f)
                 {
                     num7 = 1f;
                 }
             }
             if (num7 >= 0.5f)
             {
                 Main.shimmerDarken = MathHelper.Clamp(Main.shimmerDarken + 0.025f, 0f, 1f);
                 Main.shimmerBrightenDelay = 4f;
             }
         }
         else if (num7 > 0f)
         {
             Main.shimmerDarken = MathHelper.Clamp(Main.shimmerDarken - 0.05f, 0f, 1f);
             if (Main.shimmerDarken == 0f && Main.shimmerBrightenDelay > 0f)
             {
                 Main.shimmerBrightenDelay -= 1f;
             }
             if (Main.shimmerBrightenDelay == 0f)
             {
                 num7 -= 0.05f;
             }
             if (num7 < 0f)
             {
                 num7 = 0f;
             }
         }
         Main.shimmerAlpha = num7;
         if (Main.getGoodWorld)
         {
             bool flag7 = false;
             int num8 = NPC.FindFirstNPC(245);
             if (num8 >= 0 && Vector2.Distance(base.Center, Main.npc[num8].Center) < 2000f)
             {
                 flag7 = true;
             }
             if (flag7)
             {
                 num5 *= 0.6f;
                 num6 *= 0.6f;
             }
             else if (ZoneLihzhardTemple)
             {
                 num5 *= 0.88f;
                 num6 *= 0.88f;
             }
             else if (ZoneDungeon)
             {
                 num5 *= 0.94f;
                 num6 *= 0.94f;
             }
         }
         if (num5 != airLightDecay)
         {
             if (airLightDecay >= num5)
             {
                 airLightDecay -= 0.005f;
                 if (airLightDecay < num5)
                 {
                     airLightDecay = num5;
                 }
             }
             else
             {
                 airLightDecay += 0.005f;
                 if (airLightDecay > num5)
                 {
                     airLightDecay = num5;
                 }
             }
         }
         if (num6 != solidLightDecay)
         {
             if (solidLightDecay >= num6)
             {
                 solidLightDecay -= 0.005f;
                 if (solidLightDecay < num6)
                 {
                     solidLightDecay = num6;
                 }
             }
             else
             {
                 solidLightDecay += 0.005f;
                 if (solidLightDecay > num6)
                 {
                     solidLightDecay = num6;
                 }
             }
         }
         bool flag8 = ZoneRain && ZoneSnow;
         if (Main.remixWorld)
         {
             flag8 = (double)(position.Y / 16f) > Main.worldSurface && Main.raining && ZoneSnow;
         }
         bool flag9 = point.Y > Main.maxTilesY - 320;
         bool flag10 = ZoneOverworldHeight && (point.X < 380 || point.X > Main.maxTilesX - 380);
         ManageSpecialBiomeVisuals("Stardust", ZoneTowerStardust, vector4 - new Vector2(0f, 10f));
         ManageSpecialBiomeVisuals("Nebula", ZoneTowerNebula, vector3 - new Vector2(0f, 10f));
         ManageSpecialBiomeVisuals("Vortex", ZoneTowerVortex, vector2 - new Vector2(0f, 10f));
         ManageSpecialBiomeVisuals("Solar", ZoneTowerSolar, vector - new Vector2(0f, 10f));
         ManageSpecialBiomeVisuals("MoonLord", NPC.AnyNPCs(398));
         ManageSpecialBiomeVisuals("BloodMoon", Main.bloodMoon || Main.SceneMetrics.BloodMoonMonolith || bloodMoonMonolithShader);
         ManageSpecialBiomeVisuals("Blizzard", Main.UseStormEffects && flag8);
         ManageSpecialBiomeVisuals("HeatDistortion", Main.UseHeatDistortion && (flag9 || ((double)point.Y < Main.worldSurface && ZoneDesert && !flag10 && !Main.raining && !Filters.Scene["Sandstorm"].IsActive())));
         if (Main.GraveyardVisualIntensity > 0f)
         {
             if (!Filters.Scene["Graveyard"].IsActive())
             {
                 Filters.Scene.Activate("Graveyard", default(Vector2));
             }
             else
             {
                 Filters.Scene["Graveyard"].GetShader().UseTargetPosition(base.Center);
                 float progress = MathHelper.Lerp(0f, 0.75f, Main.GraveyardVisualIntensity);
                 Filters.Scene["Graveyard"].GetShader().UseProgress(progress);
                 Filters.Scene["Graveyard"].GetShader().UseIntensity(1.2f);
             }
         }
         else if (Filters.Scene["Graveyard"].IsActive())
         {
             Filters.Scene.Deactivate("Graveyard");
         }
         if (!Filters.Scene["Sepia"].IsActive() && dontStarveShader)
         {
             Filters.Scene.Activate("Sepia", default(Vector2));
         }
         else if (Filters.Scene["Sepia"].IsActive() && !dontStarveShader)
         {
             Filters.Scene.Deactivate("Sepia");
         }
         if (!Filters.Scene["WaterDistortion"].IsActive() && Main.WaveQuality > 0)
         {
             Filters.Scene.Activate("WaterDistortion", default(Vector2));
         }
         else if (Filters.Scene["WaterDistortion"].IsActive() && Main.WaveQuality == 0)
         {
             Filters.Scene.Deactivate("WaterDistortion");
         }
         if (Filters.Scene["WaterDistortion"].IsActive())
         {
             float num9 = (float)Main.maxTilesX * 0.5f - Math.Abs((float)point.X - (float)Main.maxTilesX * 0.5f);
             float num10 = 1f;
             float num11 = Math.Abs(Main.windSpeedCurrent);
             num10 += num11 * 1.25f;
             float num12 = MathHelper.Clamp(Main.maxRaining, 0f, 1f);
             num10 += num12 * 1.25f;
             float num13 = 0f - (MathHelper.Clamp((num9 - 380f) / 100f, 0f, 1f) * 0.5f - 0.25f);
             num10 += num13;
             float num14 = 1f - MathHelper.Clamp(3f * ((float)((double)point.Y - Main.worldSurface) / (float)(Main.rockLayer - Main.worldSurface)), 0f, 1f);
             num10 *= num14;
             float num15 = 0.9f - MathHelper.Clamp((float)(Main.maxTilesY - point.Y - 200) / 300f, 0f, 1f) * 0.9f;
             num10 += num15;
             num10 += (1f - num14) * 0.75f;
             num10 = MathHelper.Clamp(num10, 0f, 2.5f);
             Filters.Scene["WaterDistortion"].GetShader().UseIntensity(num10);
         }
         if (flag9)
         {
             float val = (float)(point.Y - (Main.maxTilesY - 320)) / 120f;
             val = Math.Min(1f, val) * 2f;
             Filters.Scene["HeatDistortion"].GetShader().UseIntensity(val);
         }
         _shaderObstructionInternalValue = Utils.Clamp(_shaderObstructionInternalValue + (float)behindBackWall.ToDirectionInt() * -0.005f, -0.1f, 1.1f);
         _stormShaderObstruction = Utils.Clamp(_shaderObstructionInternalValue, 0f, 1f);
         if (Filters.Scene["Sandstorm"].IsActive())
         {
             Filters.Scene["Sandstorm"].GetShader().UseIntensity(_stormShaderObstruction * 0.4f * Math.Min(1f, Sandstorm.Severity));
             Filters.Scene["Sandstorm"].GetShader().UseOpacity(Math.Min(1f, Sandstorm.Severity * 1.5f) * _stormShaderObstruction);
             ((SimpleOverlay)Overlays.Scene["Sandstorm"]).GetShader().UseOpacity(Math.Min(1f, Sandstorm.Severity * 1.5f) * (1f - _stormShaderObstruction));
         }
         else if (ZoneDesert && !flag10 && !Main.raining && !flag9)
         {
             Vector3 vector5 = Main.tileColor.ToVector3();
             float num16 = (vector5.X + vector5.Y + vector5.Z) / 3f;
             float num17 = _stormShaderObstruction * 4f * Math.Max(0f, 0.5f - Main.cloudAlpha) * num16;
             Filters.Scene["HeatDistortion"].GetShader().UseIntensity(num17);
             if (num17 <= 0f)
             {
                 Filters.Scene["HeatDistortion"].IsHidden = true;
             }
             else
             {
                 Filters.Scene["HeatDistortion"].IsHidden = false;
             }
         }
         if (!disabledBlizzardGraphic)
         {
             try
             {
                 if (flag8)
                 {
                     float cloudAlpha = Main.cloudAlpha;
                     if (Main.remixWorld)
                     {
                         Main.cloudAlpha = 0.4f;
                     }
                     bool value = NPC.IsADeerclopsNearScreen();
                     _deerclopsBlizzardSmoothedEffect = MathHelper.Clamp(_deerclopsBlizzardSmoothedEffect + (float)value.ToDirectionInt() * 0.0033333334f, 0f, 1f);
                     float num18 = Math.Min(1f, Main.cloudAlpha * 2f) * _stormShaderObstruction;
                     float num19 = _stormShaderObstruction * 0.4f * Math.Min(1f, Main.cloudAlpha * 2f) * 0.9f + 0.1f;
                     num19 = MathHelper.Lerp(num19, num19 * 0.5f, _deerclopsBlizzardSmoothedEffect);
                     num18 = MathHelper.Lerp(num18, num18 * 0.5f, _deerclopsBlizzardSmoothedEffect);
                     Filters.Scene["Blizzard"].GetShader().UseIntensity(num19);
                     Filters.Scene["Blizzard"].GetShader().UseOpacity(num18);
                     ((SimpleOverlay)Overlays.Scene["Blizzard"]).GetShader().UseOpacity(1f - num18);
                     if (Main.remixWorld)
                     {
                         Main.cloudAlpha = cloudAlpha;
                     }
                 }
             }
             catch
             {
                 disabledBlizzardGraphic = true;
             }
         }
         if (!disabledBlizzardSound)
         {
             try
             {
                 if (flag8)
                 {
                     ActiveSound activeSound = SoundEngine.GetActiveSound(_strongBlizzardSound);
                     ActiveSound activeSound2 = SoundEngine.GetActiveSound(_insideBlizzardSound);
                     if (activeSound == null)
                     {
                         _strongBlizzardSound = SoundEngine.PlayTrackedSound(SoundID.BlizzardStrongLoop);
                     }
                     if (activeSound2 == null)
                     {
                         _insideBlizzardSound = SoundEngine.PlayTrackedSound(SoundID.BlizzardInsideBuildingLoop);
                     }
                     SoundEngine.GetActiveSound(_strongBlizzardSound);
                     activeSound2 = SoundEngine.GetActiveSound(_insideBlizzardSound);
                 }
                 if (flag8)
                 {
                     _blizzardSoundVolume = Math.Min(_blizzardSoundVolume + 0.01f, 1f);
                 }
                 else
                 {
                     _blizzardSoundVolume = Math.Max(_blizzardSoundVolume - 0.01f, 0f);
                 }
                 float num20 = Math.Min(1f, Main.cloudAlpha * 2f) * _stormShaderObstruction;
                 ActiveSound activeSound3 = SoundEngine.GetActiveSound(_strongBlizzardSound);
                 ActiveSound activeSound4 = SoundEngine.GetActiveSound(_insideBlizzardSound);
                 if (_blizzardSoundVolume > 0f)
                 {
                     if (activeSound3 == null)
                     {
                         _strongBlizzardSound = SoundEngine.PlayTrackedSound(SoundID.BlizzardStrongLoop);
                         activeSound3 = SoundEngine.GetActiveSound(_strongBlizzardSound);
                     }
                     activeSound3.Volume = num20 * _blizzardSoundVolume;
                     if (activeSound4 == null)
                     {
                         _insideBlizzardSound = SoundEngine.PlayTrackedSound(SoundID.BlizzardInsideBuildingLoop);
                         activeSound4 = SoundEngine.GetActiveSound(_insideBlizzardSound);
                     }
                     activeSound4.Volume = (1f - num20) * _blizzardSoundVolume;
                 }
                 else
                 {
                     if (activeSound3 != null)
                     {
                         activeSound3.Volume = 0f;
                     }
                     else
                     {
                         _strongBlizzardSound = SlotId.Invalid;
                     }
                     if (activeSound4 != null)
                     {
                         activeSound4.Volume = 0f;
                     }
                     else
                     {
                         _insideBlizzardSound = SlotId.Invalid;
                     }
                 }
             }
             catch
             {
                 disabledBlizzardSound = true;
             }
         }
         if (!dead)
         {
             Point point2 = base.Center.ToTileCoordinates();
             if (WorldGen.InWorld(point2.X, point2.Y, 1))
             {
                 int num21 = 0;
                 if (Main.tile[point2.X, point2.Y] != null)
                 {
                     num21 = Main.tile[point2.X, point2.Y].wall;
                 }
                 switch (num21)
                 {
                 case 86:
                     AchievementsHelper.HandleSpecialEvent(this, 12);
                     break;
                 case 62:
                     AchievementsHelper.HandleSpecialEvent(this, 13);
                     break;
                 }
             }
             if (_funkytownAchievementCheckCooldown > 0)
             {
                 _funkytownAchievementCheckCooldown--;
             }
             if (Main.specialSeedWorld)
             {
                 AchievementsHelper.HandleSpecialEvent(this, 26);
             }
             if (position.Y / 16f > (float)Main.UnderworldLayer)
             {
                 AchievementsHelper.HandleSpecialEvent(this, 14);
             }
             else if (_funkytownAchievementCheckCooldown == 0 && (double)(position.Y / 16f) < Main.worldSurface && ZoneGlowshroom)
             {
                 AchievementsHelper.HandleSpecialEvent(this, 15);
             }
             else if (_funkytownAchievementCheckCooldown == 0 && ZoneGraveyard)
             {
                 AchievementsHelper.HandleSpecialEvent(this, 18);
             }
         }
         else
         {
             _funkytownAchievementCheckCooldown = 100;
         }
     }
References EffectManager< T >.Activate(), Entity.active, NPC.AnyNPCs(), SoundID.BlizzardInsideBuildingLoop, SoundID.BlizzardStrongLoop, Main.bloodMoon, SceneMetrics.BloodMoonMonolith, Entity.Center, Main.cloudAlpha, EffectManager< T >.Deactivate(), SceneMetrics.DungeonTileCount, SceneMetrics.EnoughTilesForCorruption, SceneMetrics.EnoughTilesForCrimson, SceneMetrics.EnoughTilesForDesert, SceneMetrics.EnoughTilesForGlowingMushroom, SceneMetrics.EnoughTilesForGraveyard, SceneMetrics.EnoughTilesForHallow, SceneMetrics.EnoughTilesForJungle, SceneMetrics.EnoughTilesForMeteor, SceneMetrics.EnoughTilesForShimmer, SceneMetrics.EnoughTilesForSnow, NPC.FindFirstNPC(), SoundEngine.GetActiveSound(), Main.getGoodWorld, Framing.GetTileSafely(), Main.GraveyardVisualIntensity, AchievementsHelper.HandleSpecialEvent(), Sandstorm.Happening, WallID.Sets.Conversion.HardenedSand, SceneMetrics.HasGardenGnome, SlotId.Invalid, WorldGen.InWorld(), NPC.IsADeerclopsNearScreen(), Main.maxRaining, Main.maxTilesX, Main.maxTilesY, Main.npc, WorldGen.oceanDepths(), SceneMetrics.PeaceCandleCount, SoundEngine.PlayTrackedSound(), Main.raining, Main.remixWorld, Main.rockLayer, WallID.Sets.Conversion.Sandstone, Filters.Scene, Overlays.Scene, Main.SceneMetrics, Main.screenPosition, Sandstorm.Severity, SceneMetrics.ShadowCandleCount, Main.shimmerAlpha, Main.shimmerBrightenDelay, Main.shimmerDarken, Main.specialSeedWorld, Main.tile, Main.tileColor, NPC.type, Main.UnderworldLayer, Main.UseHeatDistortion, Main.UseStormEffects, ActiveSound.Volume, Tile.wall, Main.wallDungeon, SceneMetrics.WaterCandleCount, Main.WaveQuality, Main.windSpeedCurrent, and Main.worldSurface.