Terraria: Player.ManaEffect
ManaEffect()
void Player.ManaEffect (int manaAmount) inline
     {
         CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.HealMana, manaAmount);
         if (Main.netMode == 1 && whoAmI == Main.myPlayer)
         {
             NetMessage.SendData(43, -1, -1, null, whoAmI, manaAmount);
         }
     }
References CombatText.HealMana, Main.myPlayer, Main.netMode, CombatText.NewText(), and NetMessage.SendData().
Referenced by MessageBuffer.GetData().