Terraria: Player.ApplyTouchDamage
ApplyTouchDamage()
void Player.ApplyTouchDamage (int tileId, int x, int y) inline private
     {
         if (TileID.Sets.TouchDamageHot[tileId])
         {
             AddBuff(67, 20);
         }
         if (TileID.Sets.Suffocate[tileId])
         {
             if (suffocateDelay < 5)
             {
                 suffocateDelay++;
             }
             else
             {
                 AddBuff(68, 1);
             }
         }
         else
         {
             suffocateDelay = 0;
         }
         if (TileID.Sets.TouchDamageBleeding[tileId])
         {
             AddBuff(30, Main.rand.Next(240, 600));
         }
         int num = TileID.Sets.TouchDamageImmediate[tileId];
         if (num > 0)
         {
             num = Main.DamageVar(num, 0f - luck);
             Hurt(PlayerDeathReason.ByOther(3), num, 0, pvp: false, quiet: false, Crit: false, 0);
         }
         if (TileID.Sets.TouchDamageDestroyTile[tileId])
         {
             WorldGen.KillTile(x, y);
             if (Main.netMode == 1 && !Main.tile[x, y].active())
             {
                 NetMessage.SendData(17, -1, -1, null, 4, x, y);
             }
         }
     }
References Tile.active(), PlayerDeathReason.ByOther(), Main.DamageVar(), WorldGen.KillTile(), Main.netMode, UnifiedRandom.Next(), Main.rand, NetMessage.SendData(), TileID.Sets.Suffocate, Main.tile, TileID.Sets.TouchDamageBleeding, TileID.Sets.TouchDamageDestroyTile, TileID.Sets.TouchDamageHot, and TileID.Sets.TouchDamageImmediate.