Terraria: Player.ToggleInv
ToggleInv()
void Player.ToggleInv () inline
     {
         bool grappleAndInteractAreShared = PlayerInput.GrappleAndInteractAreShared;
         if (Main.mapFullscreen)
         {
             Main.mapFullscreen = false;
             releaseInventory = false;
             SoundEngine.PlaySound(11);
             if (PlayerInput.GrappleAndInteractAreShared)
             {
                 LockGamepadTileInteractions();
             }
         }
         else if (PlayerInput.InBuildingMode)
         {
             PlayerInput.ExitBuildingMode();
         }
         else if (Main.ingameOptionsWindow)
         {
             if (PlayerInput.UsingGamepadUI && UILinkPointNavigator.CurrentPage == 1002)
             {
                 UILinkPointNavigator.ChangePage(1001);
             }
             else
             {
                 IngameOptions.Close();
             }
         }
         else if (Main.inFancyUI)
         {
             IngameFancyUI.Close();
         }
         else if (CaptureManager.Instance.Active)
         {
             CaptureManager.Instance.Active = false;
         }
         else if (talkNPC >= 0)
         {
             SetTalkNPC(-1);
             Main.npcChatCornerItem = 0;
             Main.npcChatText = "";
             SoundEngine.PlaySound(11);
             if (PlayerInput.UsingGamepad)
             {
                 Main.npcChatRelease = false;
             }
         }
         else if (sign >= 0)
         {
             sign = -1;
             Main.editSign = false;
             Main.npcChatText = "";
             SoundEngine.PlaySound(11);
         }
         else if (Main.clothesWindow)
         {
             Main.CancelClothesWindow();
         }
         else if (!Main.playerInventory)
         {
             OpenInventory();
         }
         else
         {
             Main.playerInventory = false;
             if (channel && Main.mouseItem != null && !Main.mouseItem.IsAir)
             {
                 channel = false;
             }
             tileEntityAnchor.Clear();
             if (!PlayerInput.UsingGamepad)
             {
                 Main.EquipPageSelected = 0;
             }
             else
             {
                 PlayerInput.NavigatorUnCachePosition();
                 Main.GamepadCursorAlpha = 0f;
                 BlockInteractionWithProjectiles = 3;
                 if (PlayerInput.GrappleAndInteractAreShared)
                 {
                     LockGamepadTileInteractions();
                 }
             }
             SoundEngine.PlaySound(11);
             if (ItemSlot.Options.HighlightNewItems)
             {
                 Item[] array = inventory;
                 for (int i = 0; i < array.Length; i++)
                 {
                     array[i].newAndShiny = false;
                 }
             }
             if (PlayerInput.UsingGamepad)
             {
                 Main.npcChatRelease = false;
                 tileInteractionHappened = true;
                 releaseInventory = false;
                 Main.mouseRight = true;
             }
         }
         if (grappleAndInteractAreShared)
         {
             GamepadEnableGrappleCooldown();
         }
     }
References CaptureManager.Active, Main.CancelClothesWindow(), UILinkPointNavigator.ChangePage(), IngameFancyUI.Close(), IngameOptions.Close(), Main.clothesWindow, UILinkPointNavigator.CurrentPage, Main.editSign, Main.EquipPageSelected, PlayerInput.ExitBuildingMode(), Main.GamepadCursorAlpha, PlayerInput.GrappleAndInteractAreShared, ItemSlot.Options.HighlightNewItems, PlayerInput.InBuildingMode, Main.inFancyUI, Main.ingameOptionsWindow, CaptureManager.Instance, Item.IsAir, Main.mapFullscreen, Main.mouseItem, Main.mouseRight, PlayerInput.NavigatorUnCachePosition(), Item.newAndShiny, Main.npcChatCornerItem, Main.npcChatRelease, Main.npcChatText, Main.playerInventory, SoundEngine.PlaySound(), PlayerInput.UsingGamepad, and PlayerInput.UsingGamepadUI.
Referenced by Main.DoDraw(), Main.DoUpdate_WhilePaused(), and UICreativeInfiniteItemsDisplay.OnCanceledInput().