Terraria: Player.NinjaDodge
NinjaDodge()
void Player.NinjaDodge () inline
     {
         SetImmuneTimeForAllTypes(longInvince ? 120 : 80);
         for (int i = 0; i < 100; i++)
         {
             int num = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 2f);
             Main.dust[num].position.X += Main.rand.Next(-20, 21);
             Main.dust[num].position.Y += Main.rand.Next(-20, 21);
             Main.dust[num].velocity *= 0.4f;
             Main.dust[num].scale *= 1f + (float)Main.rand.Next(40) * 0.01f;
             Main.dust[num].shader = GameShaders.Armor.GetSecondaryShader(cWaist, this);
             if (Main.rand.Next(2) == 0)
             {
                 Main.dust[num].scale *= 1f + (float)Main.rand.Next(40) * 0.01f;
                 Main.dust[num].noGravity = true;
             }
         }
         int num2 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
         Main.gore[num2].scale = 1.5f;
         Main.gore[num2].velocity.X = (float)Main.rand.Next(-50, 51) * 0.01f;
         Main.gore[num2].velocity.Y = (float)Main.rand.Next(-50, 51) * 0.01f;
         Main.gore[num2].velocity *= 0.4f;
         num2 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
         Main.gore[num2].scale = 1.5f;
         Main.gore[num2].velocity.X = 1.5f + (float)Main.rand.Next(-50, 51) * 0.01f;
         Main.gore[num2].velocity.Y = 1.5f + (float)Main.rand.Next(-50, 51) * 0.01f;
         Main.gore[num2].velocity *= 0.4f;
         num2 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
         Main.gore[num2].scale = 1.5f;
         Main.gore[num2].velocity.X = -1.5f - (float)Main.rand.Next(-50, 51) * 0.01f;
         Main.gore[num2].velocity.Y = 1.5f + (float)Main.rand.Next(-50, 51) * 0.01f;
         Main.gore[num2].velocity *= 0.4f;
         num2 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
         Main.gore[num2].scale = 1.5f;
         Main.gore[num2].velocity.X = 1.5f + (float)Main.rand.Next(-50, 51) * 0.01f;
         Main.gore[num2].velocity.Y = -1.5f - (float)Main.rand.Next(-50, 51) * 0.01f;
         Main.gore[num2].velocity *= 0.4f;
         num2 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
         Main.gore[num2].scale = 1.5f;
         Main.gore[num2].velocity.X = -1.5f - (float)Main.rand.Next(-50, 51) * 0.01f;
         Main.gore[num2].velocity.Y = -1.5f - (float)Main.rand.Next(-50, 51) * 0.01f;
         Main.gore[num2].velocity *= 0.4f;
         if (whoAmI == Main.myPlayer)
         {
             NetMessage.SendData(62, -1, -1, null, whoAmI, 1f);
         }
     }
References GameShaders.Armor, Color, Main.dust, ArmorShaderDataSet.GetSecondaryShader(), Main.gore, Main.myPlayer, Dust.NewDust(), Gore.NewGore(), UnifiedRandom.Next(), Dust.noGravity, Dust.position, Main.rand, Dust.scale, Gore.scale, NetMessage.SendData(), Dust.shader, Dust.velocity, and Gore.velocity.
Referenced by MessageBuffer.GetData().