Terraria: Player.TryToPoop
TryToPoop()
void Player.TryToPoop () inline private
     {
         if (whoAmI != Main.myPlayer || !wellFed)
         {
             return;
         }
         int maxValue = 600;
         if (Main.rand.Next(maxValue) != 0)
         {
             return;
         }
         int num = 3;
         int num2 = FindBuffIndex(207);
         if (num2 == -1)
         {
             num = 2;
             num2 = FindBuffIndex(206);
         }
         if (num2 == -1)
         {
             num = 1;
             num2 = FindBuffIndex(26);
         }
         if (num2 != -1)
         {
             int num3 = buffTime[num2];
             DelBuff(num2);
             int stack = Utils.Clamp(num3 / 3600 * num, num, 999);
             Vector2 mountedCenter = MountedCenter;
             ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.Digestion, new ParticleOrchestraSettings
             {
                 PositionInWorld = mountedCenter,
                 MovementVector = new Vector2(-direction, 0f)
             }, whoAmI);
             int num4 = Item.NewItem(GetItemSource_Misc(9), mountedCenter, Vector2.Zero, 5395, stack, noBroadcast: false, 0, noGrabDelay: true);
             if (Main.netMode == 0)
             {
                 Main.item[num4].noGrabDelay = 100;
             }
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(21, -1, -1, null, num4);
             }
         }
     }
References Main.item, Main.myPlayer, Main.netMode, Item.NewItem(), UnifiedRandom.Next(), Item.noGrabDelay, Main.rand, ParticleOrchestrator.RequestParticleSpawn(), and NetMessage.SendData().