Terraria: Player.CheckIceBreak
CheckIceBreak()
void Player.CheckIceBreak () inline
     {
         if (!(velocity.Y > 7f))
         {
             return;
         }
         Vector2 vector = position + velocity;
         int num = (int)(vector.X / 16f);
         int num2 = (int)((vector.X + (float)width) / 16f);
         int num3 = (int)((position.Y + (float)height + 1f) / 16f);
         for (int i = num; i <= num2; i++)
         {
             for (int j = num3; j <= num3 + 1 && Main.tile[i, j] != null; j++)
             {
                 if (Main.tile[i, j].nactive() && Main.tile[i, j].type == 162 && !WorldGen.SolidTile(i, j - 1))
                 {
                     WorldGen.KillTile(i, j);
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 0, i, j);
                     }
                 }
             }
         }
     }
References WorldGen.KillTile(), Tile.nactive(), Main.netMode, NetMessage.SendData(), WorldGen.SolidTile(), Main.tile, and Tile.type.