Terraria: Player.PlaceThing_PaintScrapper_TryScrapping
PlaceThing_PaintScrapper_TryScrapping()
void Player.PlaceThing_PaintScrapper_TryScrapping (int x, int y) inline private
     {
         Tile tile = Main.tile[x, y];
         if ((0u | ((tile.wall > 0 && (tile.wallColor() > 0 || tile.invisibleWall() || tile.fullbrightWall())) ? 1u : 0u) | ((tile.active() && (tile.color() > 0 || tile.invisibleBlock() || tile.fullbrightBlock())) ? 1u : 0u)) == 0)
         {
             return;
         }
         cursorItemIconEnabled = true;
         if (ItemTimeIsZero && itemAnimation > 0 && controlUseItem)
         {
             if (WorldGen.paintTile(x, y, 0, broadCast: true) || WorldGen.paintCoatTile(x, y, 0, broadcast: true))
             {
                 ApplyItemTime(inventory[selectedItem], tileSpeed);
             }
             else if (WorldGen.paintWall(x, y, 0, broadCast: true) || WorldGen.paintCoatWall(x, y, 0, broadcast: true))
             {
                 ApplyItemTime(inventory[selectedItem], wallSpeed);
             }
         }
     }
References Tile.active(), Tile.color(), Tile.fullbrightBlock(), Tile.fullbrightWall(), Tile.invisibleBlock(), Tile.invisibleWall(), WorldGen.paintCoatTile(), WorldGen.paintCoatWall(), WorldGen.paintTile(), WorldGen.paintWall(), Main.tile, Tile.wall, and Tile.wallColor().