Terraria: Player.ItemCheck_ApplyUseStyle
ItemCheck_ApplyUseStyle()
void Player.ItemCheck_ApplyUseStyle (float mountOffset, Item sItem, Rectangle heldItemFrame) inline
     {
         if (Main.dedServ)
         {
             return;
         }
         if (sItem.useStyle == 1)
         {
             if (sItem.type > -1 && Item.claw[sItem.type])
             {
                 if ((double)itemAnimation < (double)itemAnimationMax * 0.333)
                 {
                     float num = 10f;
                     itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num) * (float)direction;
                     itemLocation.Y = position.Y + 26f + mountOffset;
                 }
                 else if ((double)itemAnimation < (double)itemAnimationMax * 0.666)
                 {
                     float num2 = 8f;
                     itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num2) * (float)direction;
                     num2 = 24f;
                     itemLocation.Y = position.Y + num2 + mountOffset;
                 }
                 else
                 {
                     float num3 = 6f;
                     itemLocation.X = position.X + (float)width * 0.5f - ((float)heldItemFrame.Width * 0.5f - num3) * (float)direction;
                     num3 = 20f;
                     itemLocation.Y = position.Y + num3 + mountOffset;
                 }
                 itemRotation = ((float)itemAnimation / (float)itemAnimationMax - 0.5f) * (float)(-direction) * 3.5f - (float)direction * 0.3f;
             }
             else
             {
                 Vector2 zero = Vector2.Zero;
                 if ((double)itemAnimation < (double)itemAnimationMax * 0.333)
                 {
                     float num4 = 10f;
                     if (heldItemFrame.Width > 32)
                     {
                         num4 = 14f;
                     }
                     if (heldItemFrame.Width >= 52)
                     {
                         num4 = 24f;
                     }
                     if (heldItemFrame.Width >= 64)
                     {
                         num4 = 28f;
                     }
                     if (heldItemFrame.Width >= 92)
                     {
                         num4 = 38f;
                     }
                     if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
                     {
                         num4 += 8f;
                     }
                     if (sItem.type == 671)
                     {
                         num4 += 12f;
                     }
                     itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num4) * (float)direction;
                     itemLocation.Y = position.Y + 24f + mountOffset;
                     zero = new Vector2(-4f, 1f);
                 }
                 else if ((double)itemAnimation < (double)itemAnimationMax * 0.666)
                 {
                     float num5 = 10f;
                     if (heldItemFrame.Width > 32)
                     {
                         num5 = 18f;
                     }
                     if (heldItemFrame.Width >= 52)
                     {
                         num5 = 24f;
                     }
                     if (heldItemFrame.Width >= 64)
                     {
                         num5 = 28f;
                     }
                     if (heldItemFrame.Width >= 92)
                     {
                         num5 = 38f;
                     }
                     if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
                     {
                         num5 += 4f;
                     }
                     if (sItem.type == 671)
                     {
                         num5 += 6f;
                     }
                     itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num5) * (float)direction;
                     num5 = 10f;
                     if (heldItemFrame.Height > 32)
                     {
                         num5 = 8f;
                     }
                     if (heldItemFrame.Height > 52)
                     {
                         num5 = 12f;
                     }
                     if (heldItemFrame.Height > 64)
                     {
                         num5 = 14f;
                     }
                     if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
                     {
                         num5 += 4f;
                     }
                     if (sItem.type == 671)
                     {
                         num5 += 10f;
                     }
                     itemLocation.Y = position.Y + num5 + mountOffset;
                     zero = new Vector2(-6f, -4f);
                 }
                 else
                 {
                     float num6 = 6f;
                     if (heldItemFrame.Width > 32)
                     {
                         num6 = 14f;
                     }
                     if (heldItemFrame.Width >= 48)
                     {
                         num6 = 18f;
                     }
                     if (heldItemFrame.Width >= 52)
                     {
                         num6 = 24f;
                     }
                     if (heldItemFrame.Width >= 64)
                     {
                         num6 = 28f;
                     }
                     if (heldItemFrame.Width >= 92)
                     {
                         num6 = 38f;
                     }
                     if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
                     {
                         num6 += 4f;
                     }
                     if (sItem.type == 671)
                     {
                         num6 += 8f;
                     }
                     itemLocation.X = position.X + (float)width * 0.5f - ((float)heldItemFrame.Width * 0.5f - num6) * (float)direction;
                     num6 = 10f;
                     if (heldItemFrame.Height > 32)
                     {
                         num6 = 10f;
                     }
                     if (heldItemFrame.Height > 52)
                     {
                         num6 = 12f;
                     }
                     if (heldItemFrame.Height > 64)
                     {
                         num6 = 14f;
                     }
                     if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
                     {
                         num6 += 4f;
                     }
                     if (sItem.type == 671)
                     {
                         num6 += 8f;
                     }
                     itemLocation.Y = position.Y + num6 + mountOffset;
                     zero = new Vector2(4f, -2f);
                 }
                 if (sItem.type > -1 && ItemID.Sets.UsesBetterMeleeItemLocation[sItem.type])
                 {
                     itemLocation += zero * Directions;
                 }
                 itemRotation = ((float)itemAnimation / (float)itemAnimationMax - 0.5f) * (float)(-direction) * 3.5f - (float)direction * 0.3f;
             }
             if (gravDir == -1f)
             {
                 itemRotation = 0f - itemRotation;
                 itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
             }
         }
         else if (sItem.useStyle == 7)
         {
             itemRotation = (float)itemAnimation / (float)itemAnimationMax * (float)direction * 2f + -1.4f * (float)direction;
             if ((double)itemAnimation < (double)itemAnimationMax * 0.5)
             {
                 itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - itemRotation * 12f * (float)direction) * (float)direction;
                 itemLocation.Y = position.Y + 38f + itemRotation * (float)direction * 4f + mountOffset;
             }
             else
             {
                 itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - itemRotation * 16f * (float)direction) * (float)direction;
                 itemLocation.Y = position.Y + 38f + itemRotation * (float)direction + mountOffset;
             }
             if (gravDir == -1f)
             {
                 itemRotation = 0f - itemRotation;
                 itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
             }
         }
         else if (sItem.useStyle == 9)
         {
             float num7 = (float)itemAnimation / (float)itemAnimationMax;
             float t = 1f - num7;
             t = Utils.GetLerpValue(0f, 0.7f, t, clamped: true);
             itemRotation = t * (float)(-direction) * 2f + 0.7f * (float)direction;
             itemLocation = MountedCenter + new Vector2((float)(direction * 10) * ((float)itemAnimation / (float)itemAnimationMax), 0f);
             float num8 = 8f;
             float num9 = 7f;
             float num10 = (float)Math.PI * 2f / 5f;
             float num11 = (0f - num10) * 0.5f + (1f - t) * num10;
             num11 += (float)Math.PI / 10f;
             Vector2 vector = base.Center + new Vector2((float)direction * num8, 0f) + num11.ToRotationVector2() * num9 * new Vector2(direction, 1f);
             itemLocation = vector;
             float num12 = num11 - (float)Math.PI / 2f;
             if (direction == -1)
             {
                 num12 = 0f - num12;
             }
             SetCompositeArmFront(enabled: true, CompositeArmStretchAmount.Full, num12);
             itemLocation = GetFrontHandPosition(CompositeArmStretchAmount.Full, num12);
             itemLocation -= MountedCenter;
             itemLocation *= MathHelper.Lerp(1.5f, 1.2f, t);
             itemLocation += MountedCenter;
             itemLocation.X += (float)direction * MathHelper.Lerp(8f, 2f, t);
             if (gravDir == -1f)
             {
                 itemRotation = 0f - itemRotation;
                 itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
             }
         }
         else if (sItem.useStyle == 6)
         {
             float num13 = 1f - (float)itemAnimation / (float)itemAnimationMax;
             num13 *= 6f;
             if (num13 > 1f)
             {
                 num13 = 1f;
             }
             itemRotation = (1f - num13) * (float)direction * 2f - 1.4f * (float)direction;
             if (num13 >= 0.5f)
             {
                 itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - itemRotation * 12f * (float)direction) * (float)direction;
                 itemLocation.Y = position.Y + 38f + itemRotation * (float)direction * 4f + mountOffset;
             }
             else
             {
                 itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - itemRotation * 16f * (float)direction) * (float)direction;
                 itemLocation.Y = position.Y + 38f + itemRotation * (float)direction + mountOffset;
             }
             if (gravDir == -1f)
             {
                 itemRotation = 0f - itemRotation;
                 itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
             }
         }
         else if (sItem.useStyle == 2)
         {
             itemLocation = MountedCenter + new Vector2(10 * direction, -10f).RotatedBy(itemRotation + (float)Math.PI / 4f * (float)direction);
             float num14 = 1f - (float)itemAnimation / (float)itemAnimationMax;
             CompositeArmStretchAmount compositeArmStretchAmount = CompositeArmStretchAmount.Full;
             if (num14 > 0.25f && num14 <= 0.5f)
             {
                 compositeArmStretchAmount = CompositeArmStretchAmount.ThreeQuarters;
             }
             if (num14 > 0.5f && num14 <= 0.75f)
             {
                 compositeArmStretchAmount = CompositeArmStretchAmount.Quarter;
             }
             if (num14 > 0.75f && num14 <= 1f)
             {
                 compositeArmStretchAmount = CompositeArmStretchAmount.None;
             }
             SetCompositeArmFront(enabled: true, compositeArmStretchAmount, -(float)Math.PI / 2f * (float)direction);
             SetCompositeArmBack(enabled: true, compositeArmStretchAmount, -(float)Math.PI / 2f * (float)direction);
             int num15 = 8;
             switch (compositeArmStretchAmount)
             {
             case CompositeArmStretchAmount.Full:
                 num15 = 8;
                 break;
             case CompositeArmStretchAmount.ThreeQuarters:
                 num15 = 6;
                 break;
             case CompositeArmStretchAmount.Quarter:
                 num15 = 4;
                 break;
             case CompositeArmStretchAmount.None:
                 num15 = 2;
                 break;
             }
             itemLocation = MountedCenter + new Vector2((num15 + 10 - heldItemFrame.Width / 2) * direction, heldItemFrame.Height / 2 - 4);
             if (gravDir == -1f)
             {
                 itemRotation = 0f - itemRotation;
                 itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
             }
         }
         else if (sItem.useStyle == 11)
         {
             float num16 = 1f - (float)itemAnimation / (float)itemAnimationMax;
             num16 *= 2f;
             CompositeArmStretchAmount compositeArmStretchAmount2 = CompositeArmStretchAmount.Full;
             if (num16 > 0.25f && num16 <= 0.5f)
             {
                 compositeArmStretchAmount2 = CompositeArmStretchAmount.ThreeQuarters;
             }
             if (num16 > 0.5f && num16 <= 0.75f)
             {
                 compositeArmStretchAmount2 = CompositeArmStretchAmount.Quarter;
             }
             if (num16 > 0.75f && num16 <= 1.25f)
             {
                 compositeArmStretchAmount2 = CompositeArmStretchAmount.None;
             }
             if (num16 > 1.25f && num16 <= 1.5f)
             {
                 compositeArmStretchAmount2 = CompositeArmStretchAmount.Quarter;
             }
             if (num16 > 1.5f && num16 <= 1.75f)
             {
                 compositeArmStretchAmount2 = CompositeArmStretchAmount.ThreeQuarters;
             }
             if (num16 > 1.75f && num16 <= 2f)
             {
                 compositeArmStretchAmount2 = CompositeArmStretchAmount.Full;
             }
             SetCompositeArmFront(enabled: true, compositeArmStretchAmount2, -(float)Math.PI / 4f * (float)direction);
             SetCompositeArmBack(enabled: true, CompositeArmStretchAmount.Full, -(float)Math.PI / 16f);
             int num17 = 8;
             switch (compositeArmStretchAmount2)
             {
             case CompositeArmStretchAmount.Full:
                 num17 = 8;
                 break;
             case CompositeArmStretchAmount.ThreeQuarters:
                 num17 = 6;
                 break;
             case CompositeArmStretchAmount.Quarter:
                 num17 = 4;
                 break;
             case CompositeArmStretchAmount.None:
                 num17 = 2;
                 break;
             }
             itemLocation = MountedCenter + new Vector2((num17 + 22 - heldItemFrame.Width / 2) * direction, heldItemFrame.Height / 2 - 8);
             if (gravDir == -1f)
             {
                 itemRotation = 0f - itemRotation;
                 itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
             }
         }
         else if (sItem.useStyle == 3)
         {
             if ((double)itemAnimation > (double)itemAnimationMax * 0.666)
             {
                 itemLocation.X = -1000f;
                 itemLocation.Y = -1000f;
                 itemRotation = -1.3f * (float)direction;
             }
             else
             {
                 itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 4f) * (float)direction;
                 itemLocation.Y = position.Y + 24f + mountOffset;
                 float num18 = (float)itemAnimation / (float)itemAnimationMax * (float)heldItemFrame.Width * (float)direction * GetAdjustedItemScale(sItem) * 1.2f - (float)(10 * direction);
                 if (num18 > -4f && direction == -1)
                 {
                     num18 = -8f;
                 }
                 if (num18 < 4f && direction == 1)
                 {
                     num18 = 8f;
                 }
                 itemLocation.X -= num18;
                 itemRotation = 0.8f * (float)direction;
                 if (sItem.type == 946 || sItem.type == 4707)
                 {
                     itemLocation.X -= 6 * direction;
                 }
             }
             if (gravDir == -1f)
             {
                 itemRotation = 0f - itemRotation;
                 itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
             }
         }
         else if (sItem.useStyle == 4)
         {
             int num19 = 0;
             int num20 = 0;
             if (sItem.type == 3601)
             {
                 num19 = 10;
             }
             if (sItem.type == 5114)
             {
                 num19 = 10;
                 num20 = -2;
             }
             if (sItem.type == 5120)
             {
                 num19 = 10;
             }
             itemRotation = 0f;
             itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - itemRotation * 14f * (float)direction - 4f - (float)num19) * (float)direction;
             itemLocation.Y = position.Y + (float)heldItemFrame.Height * 0.5f + 4f + mountOffset + (float)num20;
             if (gravDir == -1f)
             {
                 itemRotation = 0f - itemRotation;
                 itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
             }
         }
         else if (sItem.useStyle == 5)
         {
             if (sItem.type == 3779)
             {
                 itemRotation = 0f;
                 itemLocation.X = base.Center.X + (float)(6 * direction);
                 itemLocation.Y = MountedCenter.Y + 6f;
             }
             else if (sItem.type == 4262)
             {
                 itemRotation = 0f;
                 itemLocation.X = base.Center.X + (float)(-heldItemFrame.Width) * 0.5f + (float)(direction * -6);
                 itemLocation.Y = MountedCenter.Y - 6f;
                 if (Main.rand.Next(20) == 0)
                 {
                     int num21 = Main.rand.Next(570, 573);
                     Vector2 vector2 = new Vector2(base.Center.X + (float)(direction * 30) - 6f, itemLocation.Y - 30f);
                     Vector2 vector3 = new Vector2(Main.WindForVisuals * 2f + (float)direction * 0.3f, -0.5f);
                     vector3.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                     vector3.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                     if (num21 == 572)
                     {
                         vector2.X -= 8f;
                     }
                     if (num21 == 571)
                     {
                         vector2.X -= 4f;
                     }
                     Gore.NewGore(vector2, vector3, num21, 0.8f);
                 }
             }
             else if (Item.staff[sItem.type])
             {
                 float num22 = 6f;
                 if (sItem.type == 3476)
                 {
                     num22 = 14f;
                 }
                 itemLocation = MountedCenter;
                 itemLocation += (itemRotation.ToRotationVector2() * num22 * direction).Floor();
             }
             else
             {
                 itemLocation.X = position.X + (float)width * 0.5f - (float)heldItemFrame.Width * 0.5f - (float)(direction * 2);
                 itemLocation.Y = MountedCenter.Y - (float)heldItemFrame.Height * 0.5f;
             }
             if (sItem.type != 5065)
             {
                 return;
             }
             _ = itemRotation;
             Vector2 vector4 = itemLocation + itemRotation.ToRotationVector2() * 38f * direction;
             Vector2 vector5 = itemRotation.ToRotationVector2() * 5f * direction;
             if (itemAnimation % 2 == 0)
             {
                 Color newColor = Main.hslToRgb(0.92f, 1f, 0.5f);
                 int num23 = Dust.NewDust(vector4, 0, 0, 267, 0f, 0f, 0, newColor);
                 Main.dust[num23].position = vector4 - velocity + Main.rand.NextVector2Circular(10f, 10f);
                 Main.dust[num23].noGravity = true;
                 Main.dust[num23].scale = 0.3f;
                 Main.dust[num23].fadeIn = Main.rand.NextFloat() * 1.2f;
                 Main.dust[num23].velocity = Main.rand.NextVector2Circular(1f, 1f) + velocity;
                 if (num23 != 6000)
                 {
                     Dust dust = Dust.CloneDust(num23);
                     dust.scale /= 2f;
                     dust.fadeIn *= 0.85f;
                     dust.color = new Color(255, 255, 255, 255);
                 }
             }
             if (itemAnimation % 4 == 0)
             {
                 ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.PrincessWeapon, new ParticleOrchestraSettings
                 {
                     PositionInWorld = vector4,
                     MovementVector = vector5 * 0.1f + Main.rand.NextVector2Circular(2f, 2f) + velocity
                 }, whoAmI);
             }
         }
         else if (sItem.useStyle == 13)
         {
             int useAnimation = itemAnimationMax;
             if (itemTimeMax != 0)
             {
                 useAnimation = itemTimeMax;
             }
             if (useAnimation == 0)
             {
                 useAnimation = sItem.useAnimation;
             }
             float num24 = 1f - (float)(itemAnimation % useAnimation) / (float)useAnimation;
             CompositeArmStretchAmount stretch = CompositeArmStretchAmount.Quarter;
             if (num24 > 0.33f && num24 <= 0.66f)
             {
                 stretch = CompositeArmStretchAmount.ThreeQuarters;
             }
             if (num24 > 0.66f && num24 <= 1f)
             {
                 stretch = CompositeArmStretchAmount.Full;
             }
             float rotation = itemRotation * Directions.Y - (float)Math.PI / 2f * (float)direction;
             SetCompositeArmFront(enabled: true, stretch, rotation);
         }
         else if (sItem.useStyle == 8)
         {
             Projectile projectile = null;
             if (ownedProjectileCounts[722] > 0)
             {
                 for (int i = 0; i < 1000; i++)
                 {
                     Projectile projectile2 = Main.projectile[i];
                     if (projectile2.active && projectile2.owner == whoAmI && projectile2.type == 722)
                     {
                         projectile = projectile2;
                         break;
                     }
                 }
             }
             float num25 = 1f;
             if (projectile != null)
             {
                 num25 = MathHelper.Lerp(0.6f, 1f, Utils.GetLerpValue(0f, 800f, Vector2.Distance(MountedCenter, projectile.Center), clamped: true));
             }
             num25 = 1f;
             if (itemAnimation >= sItem.useAnimation - 1 && itemAnimation <= sItem.useAnimation)
             {
                 float num26 = new Vector2(10 * direction, 10f).ToRotation() + (float)Math.PI / 4f;
                 itemRotation = num26;
                 if (direction == -1)
                 {
                     itemRotation += (float)Math.PI / 2f;
                 }
                 _ = 1f - (float)itemAnimation / (float)itemAnimationMax;
                 CompositeArmStretchAmount stretch2 = CompositeArmStretchAmount.Full;
                 CompositeArmStretchAmount stretch3 = CompositeArmStretchAmount.ThreeQuarters;
                 float num27 = -(float)Math.PI / 10f;
                 if (direction == -1)
                 {
                     num27 *= -1f;
                 }
                 float num28 = itemRotation - (float)Math.PI / 4f + (float)Math.PI;
                 if (direction == 1)
                 {
                     num28 += (float)Math.PI / 2f;
                 }
                 float rotation2 = num28 + num27;
                 float rotation3 = num28 - num27;
                 Vector2 vector6 = (num28 + (float)Math.PI / 2f).ToRotationVector2() * -2f;
                 itemLocation = (MountedCenter + vector6).Floor();
                 SetCompositeArmFront(enabled: true, stretch2, rotation2);
                 SetCompositeArmBack(enabled: true, stretch3, rotation3);
             }
             else if (itemAnimation > sItem.useAnimation)
             {
                 float num29 = 0f - Utils.GetLerpValue(itemAnimationMax, itemAnimationMax * 5, itemAnimation, clamped: true);
                 num29 *= num25;
                 CompositeArmStretchAmount stretch4 = CompositeArmStretchAmount.Full;
                 CompositeArmStretchAmount stretch5 = CompositeArmStretchAmount.ThreeQuarters;
                 float num30 = -(float)Math.PI / 10f;
                 num30 *= 0f - num29;
                 itemRotation = (float)Math.PI / 2f * (float)(-direction) + (float)Math.PI + (float)Math.PI * num29 * (float)(-direction);
                 float num31 = -(float)Math.PI / 5f * (float)direction;
                 if (direction < 1)
                 {
                     num30 *= -1f;
                 }
                 float rotation4 = num31 + num30;
                 float rotation5 = num31 - num30;
                 Vector2 vector7 = new Vector2(10 * direction, num29 * -6f);
                 itemLocation = (MountedCenter + vector7).Floor();
                 SetCompositeArmFront(enabled: true, stretch4, rotation4);
                 SetCompositeArmBack(enabled: true, stretch5, rotation5);
             }
             else
             {
                 float num32 = 1f - (float)itemAnimation / (float)itemAnimationMax;
                 CompositeArmStretchAmount stretch6 = CompositeArmStretchAmount.Full;
                 CompositeArmStretchAmount stretch7 = CompositeArmStretchAmount.ThreeQuarters;
                 if (num32 > 0.6f)
                 {
                     stretch7 = CompositeArmStretchAmount.Quarter;
                 }
                 float num33 = -(float)Math.PI / 10f;
                 if (direction == -1)
                 {
                     num33 *= -1f;
                 }
                 num33 *= 1f - num32 * 2.2f;
                 itemRotation = (num32 * (float)Math.PI * 1.6f + -(float)Math.PI / 2f) * num25 * (float)(-direction) + (float)Math.PI;
                 float num34 = (num32 * (float)Math.PI * 0.6f + (float)Math.PI * 2f / 5f) * (float)(-direction) + (float)Math.PI - (float)Math.PI / 4f + (float)Math.PI;
                 if (direction == 1)
                 {
                     num34 += (float)Math.PI / 2f;
                 }
                 float rotation6 = num34 + num33;
                 float rotation7 = num34 - num33;
                 Vector2 vector8 = (num34 + (float)Math.PI / 2f).ToRotationVector2() * (-5f * (1f - num32));
                 itemLocation = (MountedCenter + vector8).Floor();
                 SetCompositeArmFront(enabled: true, stretch6, rotation6);
                 SetCompositeArmBack(enabled: true, stretch7, rotation7);
             }
             FlipItemLocationAndRotationForGravity();
         }
         else if (sItem.useStyle == 12)
         {
             itemRotation = 0f;
             itemLocation.X = MountedCenter.X - (float)(8 * direction);
             itemLocation.Y = position.Y + 40f + mountOffset;
             Vector2 vector9 = Main.OffsetsPlayerHeadgear[bodyFrame.Y / 56];
             itemLocation += vector9;
             float num35 = itemAnimationMax;
             if (num35 == 0f)
             {
                 num35 = sItem.useAnimation;
             }
             float num36 = 1f - (float)itemAnimation / num35;
             num36 *= 2f;
             float num37 = (float)Math.Cos(num36 * (float)Math.PI) * 0.2f;
             CompositeArmStretchAmount compositeArmStretchAmount3 = CompositeArmStretchAmount.Full;
             if (num36 > 0.25f && num36 <= 0.5f)
             {
                 compositeArmStretchAmount3 = CompositeArmStretchAmount.ThreeQuarters;
             }
             if (num36 > 0.5f && num36 <= 0.75f)
             {
                 compositeArmStretchAmount3 = CompositeArmStretchAmount.Quarter;
             }
             if (num36 > 0.75f && num36 <= 1.25f)
             {
                 compositeArmStretchAmount3 = CompositeArmStretchAmount.None;
             }
             if (num36 > 1.25f && num36 <= 1.5f)
             {
                 compositeArmStretchAmount3 = CompositeArmStretchAmount.Quarter;
             }
             if (num36 > 1.5f && num36 <= 1.75f)
             {
                 compositeArmStretchAmount3 = CompositeArmStretchAmount.ThreeQuarters;
             }
             if (num36 > 1.75f && num36 <= 2f)
             {
                 compositeArmStretchAmount3 = CompositeArmStretchAmount.Full;
             }
             SetCompositeArmFront(enabled: true, compositeArmStretchAmount3, (-(float)Math.PI / 4f + num37) * (float)direction);
             CompositeArmStretchAmount stretch8 = CompositeArmStretchAmount.Quarter;
             SetCompositeArmBack(enabled: true, stretch8, (-(float)Math.PI / 4f - num37 * 0.5f) * (float)direction);
             FlipItemLocationAndRotationForGravity();
             if (sItem.type != 4715 || compositeArmStretchAmount3 != CompositeArmStretchAmount.ThreeQuarters)
             {
                 return;
             }
             Vector2 vector10 = itemLocation + new Vector2(heldItemFrame.Width, -heldItemFrame.Height) * new Vector2(direction, gravDir) * 0.3f;
             Dust dust2 = Dust.NewDustPerfect(vector10, 228, Main.rand.NextVector2CircularEdge(1f, 1f));
             dust2.noGravity = true;
             dust2.noLight = true;
             dust2.velocity *= 2f;
             float num38 = 0.5f;
             for (float num39 = 0f; num39 < 1f; num39 += 0.5f)
             {
                 if (Main.rand.Next(3) == 0)
                 {
                     Dust dust3 = Dust.NewDustPerfect(vector10, 278, Vector2.UnitY.RotatedBy(num39 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * num38 - num38 * 0.5f + (float)Math.PI / 2f) * (2f + Main.rand.NextFloat() * 1f), 150, Color.Lerp(Color.White, Color.HotPink, Main.rand.NextFloat() * 0.5f + 0.5f), 0.45f);
                     dust3.noGravity = true;
                     dust3.velocity *= 0.5f;
                     dust3.customData = this;
                     dust3.position += dust3.velocity * 6f;
                 }
             }
             for (float num40 = 0f; num40 < 1f; num40 += 0.5f)
             {
                 if (Main.rand.Next(3) == 0)
                 {
                     Dust dust4 = Dust.NewDustPerfect(vector10, 278, Vector2.UnitY.RotatedBy(num40 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * num38 - num38 * 0.5f + (float)Math.PI / 2f) * (0.5f + Main.rand.NextFloat() * 1f), 150, Color.Lerp(Color.White, Color.Gold, Main.rand.NextFloat() * 0.5f + 0.5f), 0.45f);
                     dust4.noGravity = true;
                     dust4.velocity *= 0.5f;
                     dust4.customData = this;
                     dust4.position += dust4.velocity * 6f;
                 }
             }
         }
         else if (sItem.useStyle == 14 && !Main.dedServ)
         {
             itemRotation = 0f;
             itemLocation.X = base.Center.X + (float)(6 * direction);
             itemLocation.Y = position.Y + 40f + mountOffset - 8f;
             Vector2 vector11 = Main.OffsetsPlayerHeadgear[bodyFrame.Y / 56];
             itemLocation += vector11;
             CompositeArmStretchAmount stretch9 = CompositeArmStretchAmount.Full;
             SetCompositeArmBack(enabled: true, stretch9, (float)Math.PI * -3f / 4f * (float)direction);
             FlipItemLocationAndRotationForGravity();
         }
     }
References Entity.active, Entity.Center, Item.claw, Dust.CloneDust(), Color, Dust.color, Dust.customData, Main.dedServ, Main.dust, Dust.fadeIn, Utils.GetLerpValue(), Main.hslToRgb(), Dust.NewDust(), Dust.NewDustPerfect(), Gore.NewGore(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.OffsetsPlayerHeadgear, Projectile.owner, Dust.position, Main.projectile, Main.rand, ParticleOrchestrator.RequestParticleSpawn(), Dust.scale, Item.staff, Item.type, Projectile.type, Item.useAnimation, ItemID.Sets.UsesBetterMeleeItemLocation, Item.useStyle, Dust.velocity, and Main.WindForVisuals.