Terraria: WindGrid.GetWindTime
GetWindTime()
void WindGrid.GetWindTime (int tileX, int tileY, int timeThreshold, out int windTimeLeft, out int directionX, out int directionY) inline
     {
         WindCoord windCoord = _grid[tileX % _width, tileY % _height];
         directionX = windCoord.DirectionX;
         directionY = windCoord.DirectionY;
         if (windCoord.Time + timeThreshold < _gameTime)
         {
             windTimeLeft = 0;
         }
         else
         {
             windTimeLeft = _gameTime - windCoord.Time;
         }
     }
References _gameTime, _grid, _height, _width, WindGrid.WindCoord.DirectionX, WindGrid.WindCoord.DirectionY, and WindGrid.WindCoord.Time.
Referenced by TileDrawing.GetHighestWindGridPushComplex(), TileDrawing.GetWindGridPush(), TileDrawing.GetWindGridPush2Axis(), and TileDrawing.GetWindGridPushComplex().