Terraria: Player.RocketBootVisuals
RocketBootVisuals()
void Player.RocketBootVisuals () inline private
     {
         int num = height;
         if (gravDir == -1f)
         {
             num = 4;
         }
         for (int i = 0; i < 2; i++)
         {
             int num2 = ((i == 0) ? 2 : (-2));
             Rectangle r = ((i != 0) ? new Rectangle((int)position.X + width - 4, (int)position.Y + num - 10, 8, 8) : new Rectangle((int)position.X - 4, (int)position.Y + num - 10, 8, 8));
             if (direction == -1)
             {
                 r.X -= 4;
             }
             int type = 6;
             float scale = 2.5f;
             int alpha = 100;
             float num3 = 1f;
             Vector2 vector = new Vector2((float)(-num2) - velocity.X * 0.3f, 2f * gravDir - velocity.Y * 0.3f);
             Dust dust;
             switch (vanityRocketBoots)
             {
             case 5:
                 type = 6;
                 scale = 2.5f;
                 break;
             case 1:
                 if (socialShadowRocketBoots)
                 {
                     type = 27;
                     scale = 1.5f;
                 }
                 break;
             case 3:
                 type = 76;
                 scale = 1f;
                 alpha = 20;
                 break;
             case 2:
                 if (fairyBoots)
                 {
                     type = Main.rand.NextFromList(new short[6] { 61, 61, 61, 242, 64, 63 });
                     scale = 2f;
                     alpha = 120;
                 }
                 else
                 {
                     type = 16;
                     scale = 1.5f;
                     alpha = 20;
                 }
                 break;
             case 4:
             {
                 int num4 = Main.rand.Next(6);
                 r.Y += 2 * (int)gravDir;
                 if (num4 == 0 || num4 == 1)
                 {
                     dust = Dust.NewDustDirect(r.TopLeft(), r.Width, r.Height, 278, 0f, 0f, 100, Color.Lerp(Color.LimeGreen, Color.White, Main.rand.NextFloat() * 0.3f));
                     dust.shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
                     dust.scale = 0.66f;
                     dust.noGravity = true;
                     dust.velocity *= 0.25f;
                     dust.velocity -= velocity * 0.5f;
                     dust.velocity += vector * 0.5f;
                     dust.position += dust.velocity * 4f;
                     if (Main.rand.Next(5) == 0)
                     {
                         dust.fadeIn = 0.8f;
                     }
                     continue;
                 }
                 type = 107;
                 alpha = 100;
                 scale = 0.7f;
                 num3 = 0.5f;
                 break;
             }
             }
             dust = Dust.NewDustDirect(r.TopLeft(), r.Width, r.Height, type, 0f, 0f, alpha, default(Color), scale);
             dust.shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
             dust.velocity += vector;
             dust.velocity *= num3;
             switch (vanityRocketBoots)
             {
             case 5:
                 dust.noGravity = true;
                 break;
             case 1:
                 dust.noGravity = true;
                 break;
             case 2:
                 dust.velocity *= 0.1f;
                 break;
             case 3:
                 dust.velocity *= 0.05f;
                 dust.velocity.Y += 0.15f;
                 dust.noLight = true;
                 if (Main.rand.Next(2) == 0)
                 {
                     dust.noGravity = true;
                     dust.scale = 1.75f;
                 }
                 break;
             }
             if (fairyBoots)
             {
                 dust.noGravity = true;
                 dust.noLightEmittence = true;
             }
         }
     }
References GameShaders.Armor, Color, Dust.fadeIn, ArmorShaderDataSet.GetSecondaryShader(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, Dust.position, Main.rand, Dust.scale, Dust.shader, and Dust.velocity.