Terraria: WindGrid.ScanPlayer
ScanPlayer()
void WindGrid.ScanPlayer (int i) inline private
     {
         Player player = Main.player[i];
         if (!player.active || player.dead || (player.velocity.X == 0f && player.velocity.Y == 0f) || !Utils.CenteredRectangle(Main.Camera.Center, Main.Camera.UnscaledSize).Intersects(player.Hitbox) || player.velocity.HasNaNs())
         {
             return;
         }
         int directionX = Math.Sign(player.velocity.X);
         int directionY = Math.Sign(player.velocity.Y);
         foreach (Point item in Collision.GetTilesIn(player.TopLeft, player.BottomRight))
         {
             SetWindTime(item.X, item.Y, directionX, directionY);
         }
     }
References Entity.active, Main.Camera, Camera.Center, Utils.CenteredRectangle(), Player.dead, Collision.GetTilesIn(), Entity.Hitbox, Main.player, SetWindTime(), Camera.UnscaledSize, and Entity.velocity.
Referenced by ScanPlayers().