Terraria: Player.ApplyNPCOnHitEffects
ApplyNPCOnHitEffects()
void Player.ApplyNPCOnHitEffects (Item sItem, Rectangle itemRectangle, int damage, float knockBack, int npcIndex, int dmgRandomized, int dmgDone) inline private
     {
         bool flag = !Main.npc[npcIndex].immortal;
         if (sItem.type == 3211)
         {
             Vector2 vector = new Vector2(direction * 100 + Main.rand.Next(-25, 26), Main.rand.Next(-75, 76));
             vector.Normalize();
             vector *= (float)Main.rand.Next(30, 41) * 0.1f;
             Vector2 vector2 = new Vector2(itemRectangle.X + Main.rand.Next(itemRectangle.Width), itemRectangle.Y + Main.rand.Next(itemRectangle.Height));
             vector2 = (vector2 + Main.npc[npcIndex].Center * 2f) / 3f;
             Projectile.NewProjectile(GetProjectileSource_Item(sItem), vector2.X, vector2.Y, vector.X, vector.Y, 524, (int)((double)damage * 0.5), knockBack * 0.7f, whoAmI);
         }
         if (beetleOffense && flag)
         {
             beetleCounter += dmgDone;
             beetleCountdown = 0;
         }
         if (meleeEnchant == 7)
         {
             Projectile.NewProjectile(GetProjectileSource_Misc(8), Main.npc[npcIndex].Center.X, Main.npc[npcIndex].Center.Y, Main.npc[npcIndex].velocity.X, Main.npc[npcIndex].velocity.Y, 289, 0, 0f, whoAmI);
         }
         if (sItem.type == 3106)
         {
             stealth = 1f;
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(84, -1, -1, null, whoAmI);
             }
         }
         if (sItem.type == 5094)
         {
             TentacleSpike_TrySpiking(Main.npc[npcIndex], sItem, damage, knockBack);
         }
         if (sItem.type == 795)
         {
             BloodButcherer_TryButchering(Main.npc[npcIndex], sItem, damage, knockBack);
         }
         if (sItem.type == 121)
         {
             Volcano_TrySpawningVolcano(Main.npc[npcIndex], sItem, (int)((float)damage * 0.75f), knockBack, itemRectangle);
         }
         if (sItem.type == 5097)
         {
             BatBat_TryLifeLeeching(Main.npc[npcIndex]);
         }
         if (sItem.type == 1123 && flag)
         {
             int num = Main.rand.Next(1, 4);
             if (strongBees && Main.rand.Next(3) == 0)
             {
                 num++;
             }
             for (int i = 0; i < num; i++)
             {
                 float num2 = (float)(direction * 2) + (float)Main.rand.Next(-35, 36) * 0.02f;
                 float num3 = (float)Main.rand.Next(-35, 36) * 0.02f;
                 num2 *= 0.2f;
                 num3 *= 0.2f;
                 int num4 = Projectile.NewProjectile(GetProjectileSource_Item(sItem), itemRectangle.X + itemRectangle.Width / 2, itemRectangle.Y + itemRectangle.Height / 2, num2, num3, beeType(), beeDamage(dmgRandomized / 3), beeKB(0f), whoAmI);
                 Main.projectile[num4].melee = true;
             }
         }
         if (sItem.type == 155 && flag && _spawnMuramasaCut)
         {
             _spawnMuramasaCut = false;
             int num5 = Main.rand.Next(1, 4);
             num5 = 1;
             for (int j = 0; j < num5; j++)
             {
                 NPC nPC = Main.npc[npcIndex];
                 Rectangle hitbox = nPC.Hitbox;
                 hitbox.Inflate(30, 16);
                 hitbox.Y -= 8;
                 Vector2 vector3 = Main.rand.NextVector2FromRectangle(hitbox);
                 Vector2 vector4 = hitbox.Center.ToVector2();
                 Vector2 spinningpoint = (vector4 - vector3).SafeNormalize(new Vector2(direction, gravDir)) * 8f;
                 Main.rand.NextFloat();
                 float num6 = (float)(Main.rand.Next(2) * 2 - 1) * ((float)Math.PI / 5f + (float)Math.PI * 4f / 5f * Main.rand.NextFloat());
                 num6 *= 0.5f;
                 spinningpoint = spinningpoint.RotatedBy(0.7853981852531433);
                 int num7 = 3;
                 int num8 = 10 * num7;
                 int num9 = 5;
                 int num10 = num9 * num7;
                 vector3 = vector4;
                 for (int k = 0; k < num10; k++)
                 {
                     vector3 -= spinningpoint;
                     spinningpoint = spinningpoint.RotatedBy((0f - num6) / (float)num8);
                 }
                 vector3 += nPC.velocity * num9;
                 Projectile.NewProjectile(GetProjectileSource_Item(sItem), vector3, spinningpoint, 977, (int)((float)dmgRandomized * 0.5f), 0f, whoAmI, num6);
             }
         }
         if (Main.npc[npcIndex].value > 0f && hasLuckyCoin && Main.rand.Next(5) == 0)
         {
             int type = 71;
             if (Main.rand.Next(10) == 0)
             {
                 type = 72;
             }
             if (Main.rand.Next(100) == 0)
             {
                 type = 73;
             }
             int num11 = Item.NewItem(GetItemSource_OnHit(Main.npc[npcIndex], 2), (int)Main.npc[npcIndex].position.X, (int)Main.npc[npcIndex].position.Y, Main.npc[npcIndex].width, Main.npc[npcIndex].height, type);
             Main.item[num11].stack = Main.rand.Next(1, 11);
             Main.item[num11].velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
             Main.item[num11].velocity.X = (float)Main.rand.Next(10, 31) * 0.2f * (float)direction;
             Main.item[num11].timeLeftInWhichTheItemCannotBeTakenByEnemies = 60;
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(148, -1, -1, null, num11);
             }
         }
     }
References Entity.Center, Entity.height, Entity.Hitbox, NPC.immortal, Main.item, Projectile.melee, Main.netMode, Item.NewItem(), Projectile.NewProjectile(), UnifiedRandom.Next(), Main.npc, Entity.position, Main.projectile, Main.rand, NetMessage.SendData(), Item.stack, Item.timeLeftInWhichTheItemCannotBeTakenByEnemies, Item.type, NPC.value, Entity.velocity, and Entity.width.