Terraria: Player.GetItem_FillEmptyInventorySlot
GetItem_FillEmptyInventorySlot()
bool Player.GetItem_FillEmptyInventorySlot (int plr, Item newItem, GetItemSettings settings, Item returnItem, int i) inline private
     {
         if (inventory[i].type != 0)
         {
             return false;
         }
         if (newItem.IsACoin)
         {
             SoundEngine.PlaySound(38, (int)position.X, (int)position.Y);
         }
         else
         {
             SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
         }
         returnItem.shimmered = false;
         inventory[i] = returnItem;
         if (!settings.NoText)
         {
             PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, newItem.stack, noStack: false, settings.LongText);
         }
         DoCoins(i);
         if (plr == Main.myPlayer)
         {
             Recipe.FindRecipes();
         }
         AchievementsHelper.NotifyItemPickup(this, returnItem);
         if (plr == Main.myPlayer && newItem.type == 5095)
         {
             LucyAxeMessage.Create(LucyAxeMessage.MessageSource.PickedUp, base.Top, new Vector2(0f, -7f));
         }
         settings.HandlePostAction(inventory[i]);
         return true;
     }
References LucyAxeMessage.Create(), Recipe.FindRecipes(), GetItemSettings.HandlePostAction(), Item.IsACoin, GetItemSettings.LongText, Main.myPlayer, PopupText.NewText(), GetItemSettings.NoText, AchievementsHelper.NotifyItemPickup(), SoundEngine.PlaySound(), Item.shimmered, Item.stack, and Item.type.