Terraria: Player.GetItemExpectedPrice
GetItemExpectedPrice()
void Player.GetItemExpectedPrice (Item item, out long calcForSelling, out long calcForBuying) inline
     {
         if (item.shopSpecialCurrency != -1)
         {
             CustomCurrencyManager.GetPrices(item, out calcForSelling, out calcForBuying);
             return;
         }
         int storeValue = item.GetStoreValue();
         calcForSelling = storeValue;
         calcForBuying = storeValue;
         if (discountAvailable)
         {
             if (!item.buyOnce)
             {
                 calcForBuying = (int)((float)calcForBuying * 0.8f);
             }
             if (item.isAShopItem)
             {
                 calcForSelling = calcForBuying;
             }
         }
         if (item.buyOnce)
         {
             calcForBuying = (int)Math.Round((double)calcForBuying / currentShoppingSettings.PriceAdjustment);
             calcForSelling = (int)Math.Round((double)calcForSelling / currentShoppingSettings.PriceAdjustment);
         }
         else
         {
             calcForBuying = (int)Math.Round((double)calcForBuying * currentShoppingSettings.PriceAdjustment);
             calcForSelling = (int)Math.Round((double)calcForSelling / currentShoppingSettings.PriceAdjustment);
         }
         if (item.buyOnce)
         {
             calcForBuying /= 5L;
             if (storeValue != 0 && calcForBuying < 1)
             {
                 calcForBuying = 1L;
             }
         }
     }
References Item.buyOnce, CustomCurrencyManager.GetPrices(), Item.GetStoreValue(), Item.isAShopItem, L, and Item.shopSpecialCurrency.
Referenced by ItemSlot.HandleShopSlot(), and Main.MouseText_DrawItemTooltip().