Terraria: Player.DropSelectedItem
DropSelectedItem() [2/2]
void Player.DropSelectedItem (int slot, ref Item theItemWeDrop) inline
     {
         bool flag = false;
         if (theItemWeDrop.favorited)
         {
             theItemWeDrop = GetItem(whoAmI, theItemWeDrop, GetItemSettings.GetItemInDropItemCheck);
             if (slot == 58)
             {
                 Main.mouseItem = theItemWeDrop;
             }
             Recipe.FindRecipes();
             if (theItemWeDrop.type == 0)
             {
                 flag = true;
             }
         }
         if (!flag)
         {
             Item item = new Item();
             if (((Main.mouseRight && !mouseInterface && Main.mouseRightRelease) || !Main.playerInventory) && Main.mouseItem.type > 0 && Main.mouseItem.stack > 0)
             {
                 item = theItemWeDrop;
                 theItemWeDrop = Main.mouseItem;
                 delayUseItem = true;
                 controlUseItem = false;
             }
             if (whoAmI == Main.myPlayer && theItemWeDrop.type == 5095)
             {
                 LucyAxeMessage.Create(LucyAxeMessage.MessageSource.ThrownAway, base.Top, new Vector2(direction * 7, -2f));
             }
             int num = Item.NewItem(GetItemSource_Misc(4), (int)position.X, (int)position.Y, width, height, theItemWeDrop.type);
             theItemWeDrop.position = Main.item[num].position;
             Main.item[num] = theItemWeDrop;
             theItemWeDrop = new Item();
             if (slot == 58)
             {
                 Main.mouseItem = new Item();
             }
             Item item2 = Main.item[num];
             if (Main.netMode == 0)
             {
                 item2.noGrabDelay = 100;
             }
             item2.velocity.Y = -2f;
             item2.velocity.X = (float)(4 * direction) + velocity.X;
             item2.favorited = false;
             item2.newAndShiny = false;
             if (((Main.mouseRight && !mouseInterface) || !Main.playerInventory) && Main.mouseItem.type > 0)
             {
                 theItemWeDrop = item;
                 Main.mouseItem = new Item();
             }
             else
             {
                 SetItemAnimation(10);
                 JustDroppedAnItem = true;
                 DropSelectedItem_InterruptActionsThatUseAnimations();
             }
             Recipe.FindRecipes();
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(21, -1, -1, null, num);
             }
         }
     }
References LucyAxeMessage.Create(), Item.favorited, Recipe.FindRecipes(), GetItemSettings.GetItemInDropItemCheck, Main.item, Main.mouseItem, Main.mouseRight, Main.mouseRightRelease, Main.myPlayer, Main.netMode, Item.newAndShiny, Item.NewItem(), Item.noGrabDelay, Main.playerInventory, Entity.position, NetMessage.SendData(), Item.stack, Item.type, and Entity.velocity.