Terraria: Player.CommandForbiddenStorm
CommandForbiddenStorm()
void Player.CommandForbiddenStorm () inline
     {
         List<int> list = new List<int>();
         for (int i = 0; i < 1000; i++)
         {
             Projectile projectile = Main.projectile[i];
             if (projectile.active && projectile.type == 656 && projectile.owner == whoAmI)
             {
                 list.Add(i);
             }
         }
         bool flag = StrayMethods.CanSpawnSandstormFriendly(MinionRestTargetPoint, 30, 30);
         bool num = MinionRestTargetPoint == Vector2.Zero;
         Vector2 center = base.Center;
         Vector2 endPoint = MinionRestTargetPoint;
         if (num)
         {
             endPoint = center;
         }
         int samplesToTake = 10;
         float samplingWidth = 60f;
         Collision.AimingLaserScan(center, endPoint, samplingWidth, samplesToTake, out var vectorTowardsTarget, out var samples);
         bool flag2 = false;
         float[] array = samples;
         for (int j = 0; j < array.Length; j++)
         {
             if (Math.Abs(array[j] - vectorTowardsTarget.Length()) < 10f)
             {
                 flag2 = true;
                 break;
             }
         }
         float num2 = 0f;
         for (int k = 0; k < samples.Length; k++)
         {
             if (samples[k] > num2)
             {
                 num2 = samples[k];
             }
         }
         if (list.Count <= 1)
         {
             Vector2 vector = center + vectorTowardsTarget.SafeNormalize(Vector2.Zero) * num2;
             Vector2 vector2 = vector - center;
             if (vector2.Length() > 0f)
             {
                 for (float num3 = 0f; num3 < vector2.Length(); num3 += 15f)
                 {
                     Vector2 vector3 = center + vector2 * (num3 / vector2.Length());
                     Dust obj = Main.dust[Dust.NewDust(vector3, 0, 0, 269)];
                     obj.position = vector3;
                     obj.fadeIn = 0.5f;
                     obj.scale = 0.7f;
                     obj.velocity *= 0.4f;
                     obj.noLight = true;
                 }
             }
             for (float num4 = 0f; num4 < (float)Math.PI * 2f; num4 += (float)Math.PI / 15f)
             {
                 Dust obj2 = Main.dust[Dust.NewDust(vector, 0, 0, 269)];
                 obj2.position = vector;
                 obj2.fadeIn = 1f;
                 obj2.scale = 0.3f;
                 obj2.noLight = true;
             }
         }
         flag &= list.Count <= 1;
         flag = flag && flag2;
         if (flag)
         {
             flag = CheckMana(20, pay: true);
             if (flag)
             {
                 manaRegenDelay = (int)maxRegenDelay;
             }
         }
         if (!flag)
         {
             return;
         }
         foreach (int item in list)
         {
             Projectile projectile2 = Main.projectile[item];
             if (!(projectile2.ai[0] >= 780f))
             {
                 projectile2.ai[0] = 780f + projectile2.ai[0] % 60f;
                 projectile2.netUpdate = true;
             }
         }
         int damage = (int)(20f * (1f + magicDamage + minionDamage - 2f));
         IEntitySource projectileSource_SetBonus = GetProjectileSource_SetBonus(3);
         _ = Main.projectile[Projectile.NewProjectile(projectileSource_SetBonus, MinionRestTargetPoint, Vector2.Zero, 656, damage, 0f, Main.myPlayer)];
     }
References Entity.active, Projectile.ai, Collision.AimingLaserScan(), StrayMethods.CanSpawnSandstormFriendly(), Main.dust, Dust.fadeIn, Main.myPlayer, Projectile.netUpdate, Dust.NewDust(), Projectile.NewProjectile(), Dust.noLight, Projectile.owner, Dust.position, Main.projectile, Dust.scale, and Projectile.type.