Terraria: Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool
ItemCheck_UseMiningTools_ActuallyUseMiningTool()
void Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool (Item sItem, out bool canHitWalls, int x, int y) inline private
     {
         int num = -1;
         int num2 = 0;
         canHitWalls = true;
         Tile tile = Main.tile[x, y];
         if (!tile.active())
         {
             return;
         }
         if ((sItem.pick > 0 && !Main.tileAxe[tile.type] && !Main.tileHammer[tile.type]) || (sItem.axe > 0 && Main.tileAxe[tile.type]) || (sItem.hammer > 0 && Main.tileHammer[tile.type]))
         {
             canHitWalls = false;
         }
         num = hitTile.HitObject(x, y, 1);
         if (Main.tileNoFail[tile.type])
         {
             num2 = 100;
         }
         if (Main.tileHammer[tile.type])
         {
             canHitWalls = false;
             if (sItem.hammer > 0)
             {
                 num2 += sItem.hammer;
                 if (!WorldGen.CanKillTile(x, y))
                 {
                     num2 = 0;
                 }
                 if (tile.type == 26 && (sItem.hammer < 80 || !Main.hardMode))
                 {
                     num2 = 0;
                     Hurt(PlayerDeathReason.ByOther(4), statLife / 2, -direction);
                 }
                 AchievementsHelper.CurrentlyMining = true;
                 if (hitTile.AddDamage(num, num2) >= 100)
                 {
                     ClearMiningCacheAt(x, y, 1);
                     WorldGen.KillTile(x, y);
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 0, x, y);
                     }
                 }
                 else
                 {
                     WorldGen.KillTile(x, y, fail: true);
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 0, x, y, 1f);
                     }
                 }
                 if (num2 != 0)
                 {
                     hitTile.Prune();
                 }
                 ApplyItemTime(sItem);
                 AchievementsHelper.CurrentlyMining = false;
             }
         }
         else if (Main.tileAxe[tile.type])
         {
             num2 = ((tile.type != 80) ? (num2 + (int)((float)sItem.axe * 1.2f)) : (num2 + (int)((float)(sItem.axe * 3) * 1.2f)));
             if (Main.getGoodWorld)
             {
                 num2 = (int)((double)num2 * 1.3);
             }
             if (sItem.axe > 0)
             {
                 AchievementsHelper.CurrentlyMining = true;
                 if (!WorldGen.CanKillTile(x, y))
                 {
                     num2 = 0;
                 }
                 if (Main.dontStarveWorld && Main.myPlayer == whoAmI && num2 > 0 && tile.type == 80)
                 {
                     Hurt(PlayerDeathReason.ByOther(3), Main.DamageVar(6f, luck), 0, pvp: false, quiet: false, Crit: false, 0);
                 }
                 if (hitTile.AddDamage(num, num2) >= 100)
                 {
                     if (whoAmI == Main.myPlayer && sItem.type == 5095 && (TileID.Sets.IsATreeTrunk[tile.type] || tile.type == 323 || tile.type == 80))
                     {
                         LucyAxeMessage.MessageSource source = LucyAxeMessage.MessageSource.ChoppedTree;
                         if (TileID.Sets.CountsAsGemTree[tile.type])
{
                             source = LucyAxeMessage.MessageSource.ChoppedGemTree;
                         }
                         if (tile.type == 80)
{
                             source = LucyAxeMessage.MessageSource.ChoppedCactus;
                             LucyAxeMessage.TryCreatingMessageWithCooldown(source, base.Top, new Vector2(direction * 7, -7f), 420);
                         }
                         else
{
                             LucyAxeMessage.Create(source, base.Top, new Vector2(direction * 7, -7f));
                         }
                     }
                     ClearMiningCacheAt(x, y, 1);
                     bool flag = IsBottomOfTreeTrunkNoRoots(x, y);
                     WorldGen.KillTile(x, y);
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 0, x, y);
                     }
                     if (sItem.type == 5295 && flag)
                     {
                         TryReplantingTree();
                     }
                 }
                 else
                 {
                     WorldGen.KillTile(x, y, fail: true);
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 0, x, y, 1f);
                     }
                 }
                 if (num2 != 0)
                 {
                     hitTile.Prune();
                 }
                 ApplyItemTime(sItem);
                 AchievementsHelper.CurrentlyMining = false;
             }
         }
         else if (sItem.pick > 0)
         {
             PickTile(x, y, sItem.pick);
         }
         if (sItem.pick > 0)
         {
             itemTime = (int)((float)sItem.useTime * pickSpeed);
         }
         ItemCheck_UseMiningTools_TryPoundingTile(sItem, num, ref canHitWalls, x, y);
     }
References Tile.active(), Item.axe, PlayerDeathReason.ByOther(), WorldGen.CanKillTile(), TileID.Sets.CountsAsGemTree, LucyAxeMessage.Create(), AchievementsHelper.CurrentlyMining, Main.DamageVar(), Main.dontStarveWorld, Main.getGoodWorld, Item.hammer, Main.hardMode, TileID.Sets.IsATreeTrunk, WorldGen.KillTile(), Main.myPlayer, Main.netMode, Item.pick, NetMessage.SendData(), Main.tile, Main.tileAxe, Main.tileHammer, Main.tileNoFail, LucyAxeMessage.TryCreatingMessageWithCooldown(), Item.type, Tile.type, and Item.useTime.