Terraria: Player.UpdateBuffs
UpdateBuffs()
void Player.UpdateBuffs (int i) inline
     {
         if (soulDrain > 0 && whoAmI == Main.myPlayer)
         {
             AddBuff(151, 2);
         }
         if (Main.dontStarveWorld)
         {
             UpdateStarvingState(withEmote: true);
         }
         for (int j = 0; j < maxBuffs; j++)
         {
             if (buffType[j] <= 0 || buffTime[j] <= 0)
             {
                 continue;
             }
             if (whoAmI == Main.myPlayer && !BuffID.Sets.TimeLeftDoesNotDecrease[buffType[j]])
             {
                 buffTime[j]--;
             }
             if (buffType[j] == 1)
             {
                 lavaImmune = true;
                 fireWalk = true;
                 buffImmune[24] = true;
             }
             else if (BuffID.Sets.BasicMountData[buffType[j]] != null)
             {
                 BuffID.Sets.BuffMountData buffMountData = BuffID.Sets.BasicMountData[buffType[j]];
                 mount.SetMount(buffMountData.mountID, this, buffMountData.faceLeft);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 158)
             {
                 manaRegenDelayBonus += 0.5f;
                 manaRegenBonus += 10;
             }
             else if (buffType[j] == 159 && inventory[selectedItem].melee)
             {
                 armorPenetration += 12;
             }
             else if (buffType[j] == 192)
             {
                 pickSpeed -= 0.2f;
                 moveSpeed += 0.2f;
             }
             else if (buffType[j] == 321)
             {
                 int num = 10;
                 meleeCrit += num;
                 rangedCrit += num;
                 magicCrit += num;
                 minionDamage += (float)num / 100f;
             }
             else if (buffType[j] == 2)
             {
                 lifeRegen += 4;
             }
             else if (buffType[j] == 3)
             {
                 moveSpeed += 0.25f;
             }
             else if (buffType[j] == 4)
             {
                 gills = true;
             }
             else if (buffType[j] == 5)
             {
                 statDefense += 8;
             }
             else if (buffType[j] == 6)
             {
                 manaRegenBuff = true;
             }
             else if (buffType[j] == 7)
             {
                 magicDamage += 0.2f;
             }
             else if (buffType[j] == 8)
             {
                 slowFall = true;
             }
             else if (buffType[j] == 9)
             {
                 findTreasure = true;
             }
             else if (buffType[j] == 343)
             {
                 biomeSight = true;
             }
             else if (buffType[j] == 10)
             {
                 invis = true;
             }
             else if (buffType[j] == 11)
             {
                 Lighting.AddLight((int)(position.X + (float)(width / 2)) / 16, (int)(position.Y + (float)(height / 2)) / 16, 0.8f, 0.95f, 1f);
             }
             else if (buffType[j] == 12)
             {
                 nightVision = true;
             }
             else if (buffType[j] == 13)
             {
                 enemySpawns = true;
             }
             else if (buffType[j] == 14)
             {
                 if (thorns < 1f)
                 {
                     thorns = 1f;
                 }
             }
             else if (buffType[j] == 15)
             {
                 waterWalk = true;
             }
             else if (buffType[j] == 16)
             {
                 archery = true;
             }
             else if (buffType[j] == 17)
             {
                 detectCreature = true;
             }
             else if (buffType[j] == 18)
             {
                 gravControl = true;
             }
             else if (buffType[j] == 30)
             {
                 bleed = true;
             }
             else if (buffType[j] == 31)
             {
                 confused = true;
             }
             else if (buffType[j] == 32)
             {
                 slow = true;
             }
             else if (buffType[j] == 35)
             {
                 silence = true;
             }
             else if (buffType[j] == 160)
             {
                 dazed = true;
             }
             else if (buffType[j] == 46)
             {
                 chilled = true;
             }
             else if (buffType[j] == 47)
             {
                 frozen = true;
             }
             else if (buffType[j] == 156)
             {
                 stoned = true;
             }
             else if (buffType[j] == 69)
             {
                 ichor = true;
                 statDefense -= 15;
             }
             else if (buffType[j] == 36)
             {
                 brokenArmor = true;
             }
             else if (buffType[j] == 48)
             {
                 honey = true;
             }
             else if (buffType[j] == 59)
             {
                 shadowDodge = true;
             }
             else if (buffType[j] == 93)
             {
                 ammoBox = true;
             }
             else if (buffType[j] == 58)
             {
                 palladiumRegen = true;
             }
             else if (buffType[j] == 306)
             {
                 hasTitaniumStormBuff = true;
             }
             else if (buffType[j] == 88)
             {
                 chaosState = true;
             }
             else if (buffType[j] == 215)
             {
                 statDefense += 5;
             }
             else if (buffType[j] == 311)
             {
                 summonerWeaponSpeedBonus += 0.35f;
             }
             else if (buffType[j] == 308)
             {
                 summonerWeaponSpeedBonus += 0.25f;
             }
             else if (buffType[j] == 314)
             {
                 summonerWeaponSpeedBonus += 0.12f;
             }
             else if (buffType[j] == 312)
             {
                 coolWhipBuff = true;
             }
             else if (buffType[j] == 63)
             {
                 moveSpeed += 1f;
             }
             else if (buffType[j] == 104)
             {
                 pickSpeed -= 0.25f;
             }
             else if (buffType[j] == 105)
             {
                 lifeMagnet = true;
             }
             else if (buffType[j] == 106)
             {
                 calmed = true;
             }
             else if (buffType[j] == 121)
             {
                 fishingSkill += 15;
             }
             else if (buffType[j] == 122)
             {
                 sonarPotion = true;
             }
             else if (buffType[j] == 123)
             {
                 cratePotion = true;
             }
             else if (buffType[j] == 107)
             {
                 tileSpeed += 0.25f;
                 wallSpeed += 0.25f;
                 blockRange++;
             }
             else if (buffType[j] == 108)
             {
                 kbBuff = true;
             }
             else if (buffType[j] == 109)
             {
                 ignoreWater = true;
                 accFlipper = true;
             }
             else if (buffType[j] == 110)
             {
                 maxMinions++;
             }
             else if (buffType[j] == 150)
             {
                 maxMinions++;
             }
             else if (buffType[j] == 348)
             {
                 maxTurrets++;
             }
             else if (buffType[j] == 111)
             {
                 dangerSense = true;
             }
             else if (buffType[j] == 112)
             {
                 ammoPotion = true;
             }
             else if (buffType[j] == 113)
             {
                 lifeForce = true;
                 statLifeMax2 += statLifeMax / 5 / 20 * 20;
             }
             else if (buffType[j] == 114)
             {
                 endurance += 0.1f;
             }
             else if (buffType[j] == 115)
             {
                 meleeCrit += 10;
                 rangedCrit += 10;
                 magicCrit += 10;
             }
             else if (buffType[j] == 116)
             {
                 inferno = true;
                 Lighting.AddLight((int)(base.Center.X / 16f), (int)(base.Center.Y / 16f), 0.65f, 0.4f, 0.1f);
                 int num2 = 323;
                 float num3 = 200f;
                 bool flag = infernoCounter % 60 == 0;
                 int damage = 20;
                 if (whoAmI != Main.myPlayer)
                 {
                     continue;
                 }
                 for (int k = 0; k < 200; k++)
                 {
                     NPC nPC = Main.npc[k];
                     if (nPC.active && !nPC.friendly && nPC.damage > 0 && !nPC.dontTakeDamage && !nPC.buffImmune[num2] && CanNPCBeHitByPlayerOrPlayerProjectile(nPC) && Vector2.Distance(base.Center, nPC.Center) <= num3)
                     {
                         if (nPC.FindBuffIndex(num2) == -1)
{
                             nPC.AddBuff(num2, 120);
                         }
                         if (flag)
{
                             ApplyDamageToNPC(nPC, damage, 0f, 0, crit: false);
                         }
                     }
                 }
                 if (!hostile)
                 {
                     continue;
                 }
                 for (int l = 0; l < 255; l++)
                 {
                     Player player = Main.player[l];
                     if (player == this || !player.active || player.dead || !player.hostile || player.buffImmune[num2] || (player.team == team && player.team != 0) || !(Vector2.Distance(base.Center, player.Center) <= num3))
                     {
                         continue;
                     }
                     if (player.FindBuffIndex(num2) == -1)
                     {
                         player.AddBuff(num2, 120);
                     }
                     if (flag)
                     {
                         player.Hurt(PlayerDeathReason.LegacyEmpty(), damage, 0, pvp: true);
                         if (Main.netMode != 0)
{
                             PlayerDeathReason reason = PlayerDeathReason.ByOther(16);
                             NetMessage.SendPlayerHurt(l, reason, damage, 0, critical: false, pvp: true, -1);
                         }
                     }
                 }
             }
             else if (buffType[j] == 117)
             {
                 meleeDamage += 0.1f;
                 rangedDamage += 0.1f;
                 magicDamage += 0.1f;
                 minionDamage += 0.1f;
             }
             else if (buffType[j] == 119)
             {
                 loveStruck = true;
             }
             else if (buffType[j] == 120)
             {
                 stinky = true;
             }
             else if (buffType[j] == 124)
             {
                 resistCold = true;
             }
             else if (buffType[j] == 257)
             {
                 if (Main.myPlayer == whoAmI)
                 {
                     if (buffTime[j] > 36000)
                     {
                         luckPotion = 3;
                     }
                     else if (buffTime[j] > 18000)
                     {
                         luckPotion = 2;
                     }
                     else
                     {
                         luckPotion = 1;
                     }
                 }
             }
             else if (buffType[j] == 165)
             {
                 lifeRegen += 6;
                 statDefense += 8;
                 dryadWard = true;
                 if (thorns < 1f)
                 {
                     thorns += 0.5f;
                 }
             }
             else if (buffType[j] == 144)
             {
                 electrified = true;
                 Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.3f, 0.8f, 1.1f);
             }
             else if (buffType[j] == 94)
             {
                 manaSick = true;
                 manaSickReduction = manaSickLessDmg * ((float)buffTime[j] / (float)manaSickTime);
             }
             else if (buffType[j] >= 95 && buffType[j] <= 97)
             {
                 buffTime[j] = 5;
                 int num4 = (byte)(1 + buffType[j] - 95);
                 if (beetleOrbs > 0 && beetleOrbs != num4)
                 {
                     if (beetleOrbs > num4)
                     {
                         DelBuff(j);
                         j--;
                     }
                     else
                     {
                         for (int m = 0; m < maxBuffs; m++)
{
                             if (buffType[m] >= 95 && buffType[m] <= 95 + num4 - 1)
{
                                 DelBuff(m);
                                 m--;
                             }
                         }
                     }
                 }
                 beetleOrbs = num4;
                 if (!beetleDefense)
                 {
                     beetleOrbs = 0;
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     beetleBuff = true;
                 }
             }
             else if (buffType[j] >= 170 && buffType[j] <= 172)
             {
                 buffTime[j] = 5;
                 int num5 = (byte)(1 + buffType[j] - 170);
                 if (solarShields > 0 && solarShields != num5)
                 {
                     if (solarShields > num5)
                     {
                         DelBuff(j);
                         j--;
                     }
                     else
                     {
                         for (int n = 0; n < maxBuffs; n++)
{
                             if (buffType[n] >= 170 && buffType[n] <= 170 + num5 - 1)
{
                                 DelBuff(n);
                                 n--;
                             }
                         }
                     }
                 }
                 solarShields = num5;
                 if (!setSolar)
                 {
                     solarShields = 0;
                     DelBuff(j);
                     j--;
                 }
             }
             else if (buffType[j] >= 98 && buffType[j] <= 100)
             {
                 int num6 = (byte)(1 + buffType[j] - 98);
                 if (beetleOrbs > 0 && beetleOrbs != num6)
                 {
                     if (beetleOrbs > num6)
                     {
                         DelBuff(j);
                         j--;
                     }
                     else
                     {
                         for (int num7 = 0; num7 < maxBuffs; num7++)
{
                             if (buffType[num7] >= 98 && buffType[num7] <= 98 + num6 - 1)
{
                                 DelBuff(num7);
                                 num7--;
                             }
                         }
                     }
                 }
                 beetleOrbs = num6;
                 meleeDamage += 0.1f * (float)beetleOrbs;
                 meleeSpeed += 0.1f * (float)beetleOrbs;
                 if (!beetleOffense)
                 {
                     beetleOrbs = 0;
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     beetleBuff = true;
                 }
             }
             else if (buffType[j] >= 176 && buffType[j] <= 178)
             {
                 int num8 = nebulaLevelMana;
                 int num9 = (byte)(1 + buffType[j] - 176);
                 if (num8 > 0 && num8 != num9)
                 {
                     if (num8 > num9)
                     {
                         DelBuff(j);
                         j--;
                     }
                     else
                     {
                         for (int num10 = 0; num10 < maxBuffs; num10++)
{
                             if (buffType[num10] >= 176 && buffType[num10] <= 178 + num9 - 1)
{
                                 DelBuff(num10);
                                 num10--;
                             }
                         }
                     }
                 }
                 nebulaLevelMana = num9;
                 if (buffTime[j] == 2 && nebulaLevelMana > 1)
                 {
                     nebulaLevelMana--;
                     buffType[j]--;
                     buffTime[j] = 480;
                 }
             }
             else if (buffType[j] >= 173 && buffType[j] <= 175)
             {
                 int num11 = nebulaLevelLife;
                 int num12 = (byte)(1 + buffType[j] - 173);
                 if (num11 > 0 && num11 != num12)
                 {
                     if (num11 > num12)
                     {
                         DelBuff(j);
                         j--;
                     }
                     else
                     {
                         for (int num13 = 0; num13 < maxBuffs; num13++)
{
                             if (buffType[num13] >= 173 && buffType[num13] <= 175 + num12 - 1)
{
                                 DelBuff(num13);
                                 num13--;
                             }
                         }
                     }
                 }
                 nebulaLevelLife = num12;
                 if (buffTime[j] == 2 && nebulaLevelLife > 1)
                 {
                     nebulaLevelLife--;
                     buffType[j]--;
                     buffTime[j] = 480;
                 }
                 lifeRegen += 6 * nebulaLevelLife;
             }
             else if (buffType[j] >= 179 && buffType[j] <= 181)
             {
                 int num14 = nebulaLevelDamage;
                 int num15 = (byte)(1 + buffType[j] - 179);
                 if (num14 > 0 && num14 != num15)
                 {
                     if (num14 > num15)
                     {
                         DelBuff(j);
                         j--;
                     }
                     else
                     {
                         for (int num16 = 0; num16 < maxBuffs; num16++)
{
                             if (buffType[num16] >= 179 && buffType[num16] <= 181 + num15 - 1)
{
                                 DelBuff(num16);
                                 num16--;
                             }
                         }
                     }
                 }
                 nebulaLevelDamage = num15;
                 if (buffTime[j] == 2 && nebulaLevelDamage > 1)
                 {
                     nebulaLevelDamage--;
                     buffType[j]--;
                     buffTime[j] = 480;
                 }
                 float num17 = 0.15f * (float)nebulaLevelDamage;
                 meleeDamage += num17;
                 rangedDamage += num17;
                 magicDamage += num17;
                 minionDamage += num17;
             }
             else if (buffType[j] == 62)
             {
                 if ((double)statLife <= (double)statLifeMax2 * 0.5)
                 {
                     Lighting.AddLight((int)(base.Center.X / 16f), (int)(base.Center.Y / 16f), 0.1f, 0.2f, 0.45f);
                     iceBarrier = true;
                     endurance += 0.25f;
                     iceBarrierFrameCounter++;
                     if (iceBarrierFrameCounter > 2)
                     {
                         iceBarrierFrameCounter = 0;
                         iceBarrierFrame++;
                         if (iceBarrierFrame >= 12)
{
                             iceBarrierFrame = 0;
                         }
                     }
                 }
                 else
                 {
                     DelBuff(j);
                     j--;
                 }
             }
             else if (buffType[j] == 49)
             {
                 for (int num18 = 191; num18 <= 194; num18++)
                 {
                     if (ownedProjectileCounts[num18] > 0)
                     {
                         pygmy = true;
                     }
                 }
                 if (!pygmy)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 83)
             {
                 if (ownedProjectileCounts[317] > 0)
                 {
                     raven = true;
                 }
                 if (!raven)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 64)
             {
                 if (ownedProjectileCounts[266] > 0)
                 {
                     slime = true;
                 }
                 if (!slime)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 125)
             {
                 if (ownedProjectileCounts[373] > 0)
                 {
                     hornetMinion = true;
                 }
                 if (!hornetMinion)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 126)
             {
                 if (ownedProjectileCounts[375] > 0)
                 {
                     impMinion = true;
                 }
                 if (!impMinion)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 133)
             {
                 if (ownedProjectileCounts[390] > 0 || ownedProjectileCounts[391] > 0 || ownedProjectileCounts[392] > 0)
                 {
                     spiderMinion = true;
                 }
                 if (!spiderMinion)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 134)
             {
                 if (ownedProjectileCounts[387] > 0 || ownedProjectileCounts[388] > 0)
                 {
                     twinsMinion = true;
                 }
                 if (!twinsMinion)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 135)
             {
                 if (ownedProjectileCounts[393] > 0 || ownedProjectileCounts[394] > 0 || ownedProjectileCounts[395] > 0)
                 {
                     pirateMinion = true;
                 }
                 if (!pirateMinion)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 214)
             {
                 if (ownedProjectileCounts[758] > 0)
                 {
                     vampireFrog = true;
                 }
                 if (!vampireFrog)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 139)
             {
                 if (ownedProjectileCounts[407] > 0)
                 {
                     sharknadoMinion = true;
                 }
                 if (!sharknadoMinion)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 140)
             {
                 if (ownedProjectileCounts[423] > 0)
                 {
                     UFOMinion = true;
                 }
                 if (!UFOMinion)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 182)
             {
                 if (ownedProjectileCounts[613] > 0)
                 {
                     stardustMinion = true;
                 }
                 if (!stardustMinion)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 213)
             {
                 if (ownedProjectileCounts[755] > 0)
                 {
                     batsOfLight = true;
                 }
                 if (!batsOfLight)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 216)
             {
                 bool flag2 = true;
                 if (ownedProjectileCounts[759] > 0)
                 {
                     babyBird = true;
                 }
                 else if (whoAmI == Main.myPlayer)
                 {
                     if (numMinions < maxMinions)
                     {
                         int num19 = FindItem(4281);
                         if (num19 != -1)
{
                             Item item = inventory[num19];
                             int num20 = Projectile.NewProjectile(GetProjectileSource_Item(item), base.Top, Vector2.Zero, item.shoot, item.damage, item.knockBack, whoAmI);
                             Main.projectile[num20].originalDamage = item.damage;
                             babyBird = true;
                         }
                     }
                     if (!babyBird)
                     {
                         DelBuff(j);
                         j--;
                         flag2 = false;
                     }
                 }
                 if (flag2)
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 325)
             {
                 if (ownedProjectileCounts[951] > 0)
                 {
                     flinxMinion = true;
                 }
                 if (!flinxMinion)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 335)
             {
                 if (ownedProjectileCounts[970] > 0)
                 {
                     abigailMinion = true;
                 }
                 if (!abigailMinion)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
                 if (whoAmI == Main.myPlayer)
                 {
                     UpdateAbigailStatus();
                 }
             }
             else if (buffType[j] == 263)
             {
                 if (ownedProjectileCounts[831] > 0)
                 {
                     stormTiger = true;
                 }
                 if (!stormTiger)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
                 if (whoAmI == Main.myPlayer)
                 {
                     UpdateStormTigerStatus();
                 }
             }
             else if (buffType[j] == 271)
             {
                 if (ownedProjectileCounts[864] > 0)
                 {
                     smolstar = true;
                 }
                 if (!smolstar)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 322)
             {
                 if (ownedProjectileCounts[946] > 0)
                 {
                     empressBlade = true;
                 }
                 if (!empressBlade)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 187)
             {
                 if (ownedProjectileCounts[623] > 0)
                 {
                     stardustGuardian = true;
                 }
                 if (!stardustGuardian)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 188)
             {
                 if (ownedProjectileCounts[625] > 0)
                 {
                     stardustDragon = true;
                 }
                 if (!stardustDragon)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 161)
             {
                 if (ownedProjectileCounts[533] > 0)
                 {
                     DeadlySphereMinion = true;
                 }
                 if (!DeadlySphereMinion)
                 {
                     DelBuff(j);
                     j--;
                 }
                 else
                 {
                     buffTime[j] = 18000;
                 }
             }
             else if (buffType[j] == 90)
             {
                 mount.SetMount(0, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 128)
             {
                 mount.SetMount(1, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 129)
             {
                 mount.SetMount(2, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 130)
             {
                 mount.SetMount(3, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 131)
             {
                 ignoreWater = true;
                 accFlipper = true;
                 mount.SetMount(4, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 132)
             {
                 mount.SetMount(5, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 168)
             {
                 ignoreWater = true;
                 accFlipper = true;
                 mount.SetMount(12, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 141)
             {
                 mount.SetMount(7, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 142)
             {
                 mount.SetMount(8, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 143)
             {
                 mount.SetMount(9, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 162)
             {
                 mount.SetMount(10, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 193)
             {
                 mount.SetMount(14, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 212)
             {
                 mount.SetMount(17, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 230)
             {
                 mount.SetMount(23, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 265)
             {
                 canFloatInWater = true;
                 accFlipper = true;
                 mount.SetMount(37, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 275)
             {
                 mount.SetMount(40, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 276)
             {
                 mount.SetMount(41, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 277)
             {
                 mount.SetMount(42, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 278)
             {
                 mount.SetMount(43, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 279)
             {
                 ignoreWater = true;
                 accFlipper = true;
                 mount.SetMount(44, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 280)
             {
                 mount.SetMount(45, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 281)
             {
                 mount.SetMount(46, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 282)
             {
                 mount.SetMount(47, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 283)
             {
                 mount.SetMount(48, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 305)
             {
                 ignoreWater = true;
                 accFlipper = true;
                 lavaImmune = true;
                 mount.SetMount(49, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 318)
             {
                 mount.SetMount(50, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 342)
             {
                 mount.SetMount(52, this);
                 buffTime[j] = 10;
             }
             else if (buffType[j] == 37)
             {
                 if (Main.wofNPCIndex >= 0 && Main.npc[Main.wofNPCIndex].type == 113)
                 {
                     gross = true;
                     buffTime[j] = 10;
                 }
                 else
                 {
                     DelBuff(j);
                     j--;
                 }
             }
             else if (buffType[j] == 38)
             {
                 buffTime[j] = 10;
                 tongued = true;
             }
             else if (buffType[j] == 146)
             {
                 moveSpeed += 0.1f;
                 moveSpeed *= 1.1f;
                 sunflower = true;
             }
             else if (buffType[j] == 19)
             {
                 buffTime[j] = 18000;
                 lightOrb = true;
                 bool flag3 = true;
                 if (ownedProjectileCounts[18] > 0)
                 {
                     flag3 = false;
                 }
                 if (flag3 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 18, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 155)
             {
                 buffTime[j] = 18000;
                 crimsonHeart = true;
                 bool flag4 = true;
                 if (ownedProjectileCounts[500] > 0)
                 {
                     flag4 = false;
                 }
                 if (flag4 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 500, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 191)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref companionCube, 653);
             }
             else if (buffType[j] == 202)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagDD2Dragon, 701);
             }
             else if (buffType[j] == 217)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagUpbeatStar, 764);
             }
             else if (buffType[j] == 219)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagBabyShark, 774);
             }
             else if (buffType[j] == 258)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagLilHarpy, 815);
             }
             else if (buffType[j] == 259)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagFennecFox, 816);
             }
             else if (buffType[j] == 260)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagGlitteryButterfly, 817);
             }
             else if (buffType[j] == 261)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagBabyImp, 821);
             }
             else if (buffType[j] == 262)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagBabyRedPanda, 825);
             }
             else if (buffType[j] == 264)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagPlantero, 854);
             }
             else if (buffType[j] == 266)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagDynamiteKitten, 858);
             }
             else if (buffType[j] == 267)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagBabyWerewolf, 859);
             }
             else if (buffType[j] == 268)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagShadowMimic, 860);
             }
             else if (buffType[j] == 274)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagVoltBunny, 875);
             }
             else if (buffType[j] == 284)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagKingSlimePet, 881);
             }
             else if (buffType[j] == 285)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagEyeOfCthulhuPet, 882);
             }
             else if (buffType[j] == 286)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagEaterOfWorldsPet, 883);
             }
             else if (buffType[j] == 287)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagBrainOfCthulhuPet, 884);
             }
             else if (buffType[j] == 288)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagSkeletronPet, 885);
             }
             else if (buffType[j] == 289)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagQueenBeePet, 886);
             }
             else if (buffType[j] == 290)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagDestroyerPet, 887);
             }
             else if (buffType[j] == 291)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagTwinsPet, 888);
             }
             else if (buffType[j] == 292)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagSkeletronPrimePet, 889);
             }
             else if (buffType[j] == 293)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagPlanteraPet, 890);
             }
             else if (buffType[j] == 294)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagGolemPet, 891);
             }
             else if (buffType[j] == 295)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagDukeFishronPet, 892);
             }
             else if (buffType[j] == 296)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagLunaticCultistPet, 893);
             }
             else if (buffType[j] == 297)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagMoonLordPet, 894);
             }
             else if (buffType[j] == 298)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagFairyQueenPet, 895);
             }
             else if (buffType[j] == 299)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagPumpkingPet, 896);
             }
             else if (buffType[j] == 300)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagEverscreamPet, 897);
             }
             else if (buffType[j] == 301)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagIceQueenPet, 898);
             }
             else if (buffType[j] == 302)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagMartianPet, 899);
             }
             else if (buffType[j] == 303)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagDD2OgrePet, 900);
             }
             else if (buffType[j] == 304)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagDD2BetsyPet, 901);
             }
             else if (buffType[j] == 317)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagQueenSlimePet, 934);
             }
             else if (buffType[j] == 327)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagBerniePet, 956);
             }
             else if (buffType[j] == 328)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagGlommerPet, 957);
             }
             else if (buffType[j] == 329)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagDeerclopsPet, 958);
             }
             else if (buffType[j] == 330)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagPigPet, 959);
             }
             else if (buffType[j] == 331)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagChesterPet, 960);
             }
             else if (buffType[j] == 341)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagKingSlimePet, 881);
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagQueenSlimePet, 934);
             }
             else if (buffType[j] == 345)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagJunimoPet, 994);
             }
             else if (buffType[j] == 349)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagBlueChickenPet, 998);
             }
             else if (buffType[j] == 351)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagSpiffo, 1003);
             }
             else if (buffType[j] == 352)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagCaveling, 1004);
             }
             else if (buffType[j] == 354)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagDirtiestBlock, 1018);
             }
             else if (buffType[j] == 200)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagDD2Gato, 703);
             }
             else if (buffType[j] == 201)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagDD2Ghost, 702);
             }
             else if (buffType[j] == 218)
             {
                 BuffHandle_SpawnPetIfNeededAndSetTime(j, ref petFlagSugarGlider, 765);
             }
             else if (buffType[j] == 190)
             {
                 buffTime[j] = 18000;
                 suspiciouslookingTentacle = true;
                 bool flag5 = true;
                 if (ownedProjectileCounts[650] > 0)
                 {
                     flag5 = false;
                 }
                 if (flag5 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 650, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 27 || buffType[j] == 101 || buffType[j] == 102)
             {
                 buffTime[j] = 18000;
                 bool flag6 = true;
                 int num21 = 72;
                 if (buffType[j] == 27)
                 {
                     blueFairy = true;
                 }
                 if (buffType[j] == 101)
                 {
                     num21 = 86;
                     redFairy = true;
                 }
                 if (buffType[j] == 102)
                 {
                     num21 = 87;
                     greenFairy = true;
                 }
                 if (head == 45 && body == 26 && legs == 25)
                 {
                     num21 = 72;
                 }
                 if (ownedProjectileCounts[num21] > 0)
                 {
                     flag6 = false;
                 }
                 if (flag6 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, num21, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 40)
             {
                 buffTime[j] = 18000;
                 bunny = true;
                 bool flag7 = true;
                 if (ownedProjectileCounts[111] > 0)
                 {
                     flag7 = false;
                 }
                 if (flag7 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 111, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 148)
             {
                 rabid = true;
                 if (Main.rand.Next(1200) == 0)
                 {
                     int num22 = Main.rand.Next(6);
                     float num23 = (float)Main.rand.Next(60, 100) * 0.01f;
                     switch (num22)
                     {
                     case 0:
                         AddBuff(22, (int)(60f * num23 * 3f));
                         break;
                     case 1:
                         AddBuff(23, (int)(60f * num23 * 0.75f));
                         break;
                     case 2:
                         AddBuff(31, (int)(60f * num23 * 1.5f));
                         break;
                     case 3:
                         AddBuff(32, (int)(60f * num23 * 3.5f));
                         break;
                     case 4:
                         AddBuff(33, (int)(60f * num23 * 5f));
                         break;
                     case 5:
                         AddBuff(35, (int)(60f * num23 * 1f));
                         break;
                     }
                 }
                 meleeDamage += 0.2f;
                 magicDamage += 0.2f;
                 rangedDamage += 0.2f;
                 minionDamage += 0.2f;
             }
             else if (buffType[j] == 41)
             {
                 buffTime[j] = 18000;
                 penguin = true;
                 bool flag8 = true;
                 if (ownedProjectileCounts[112] > 0)
                 {
                     flag8 = false;
                 }
                 if (flag8 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 112, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 152)
             {
                 buffTime[j] = 18000;
                 magicLantern = true;
                 if (ownedProjectileCounts[492] == 0 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 492, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 91)
             {
                 buffTime[j] = 18000;
                 puppy = true;
                 bool flag9 = true;
                 if (ownedProjectileCounts[334] > 0)
                 {
                     flag9 = false;
                 }
                 if (flag9 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 334, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 92)
             {
                 buffTime[j] = 18000;
                 grinch = true;
                 bool flag10 = true;
                 if (ownedProjectileCounts[353] > 0)
                 {
                     flag10 = false;
                 }
                 if (flag10 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 353, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 84)
             {
                 buffTime[j] = 18000;
                 blackCat = true;
                 bool flag11 = true;
                 if (ownedProjectileCounts[319] > 0)
                 {
                     flag11 = false;
                 }
                 if (flag11 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 319, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 61)
             {
                 buffTime[j] = 18000;
                 dino = true;
                 bool flag12 = true;
                 if (ownedProjectileCounts[236] > 0)
                 {
                     flag12 = false;
                 }
                 if (flag12 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 236, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 154)
             {
                 buffTime[j] = 18000;
                 babyFaceMonster = true;
                 bool flag13 = true;
                 if (ownedProjectileCounts[499] > 0)
                 {
                     flag13 = false;
                 }
                 if (flag13 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 499, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 65)
             {
                 buffTime[j] = 18000;
                 eyeSpring = true;
                 bool flag14 = true;
                 if (ownedProjectileCounts[268] > 0)
                 {
                     flag14 = false;
                 }
                 if (flag14 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 268, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 66)
             {
                 buffTime[j] = 18000;
                 snowman = true;
                 bool flag15 = true;
                 if (ownedProjectileCounts[269] > 0)
                 {
                     flag15 = false;
                 }
                 if (flag15 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 269, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 42)
             {
                 buffTime[j] = 18000;
                 turtle = true;
                 bool flag16 = true;
                 if (ownedProjectileCounts[127] > 0)
                 {
                     flag16 = false;
                 }
                 if (flag16 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 127, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 45)
             {
                 buffTime[j] = 18000;
                 eater = true;
                 bool flag17 = true;
                 if (ownedProjectileCounts[175] > 0)
                 {
                     flag17 = false;
                 }
                 if (flag17 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 175, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 50)
             {
                 buffTime[j] = 18000;
                 skeletron = true;
                 bool flag18 = true;
                 if (ownedProjectileCounts[197] > 0)
                 {
                     flag18 = false;
                 }
                 if (flag18 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 197, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 51)
             {
                 buffTime[j] = 18000;
                 hornet = true;
                 bool flag19 = true;
                 if (ownedProjectileCounts[198] > 0)
                 {
                     flag19 = false;
                 }
                 if (flag19 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 198, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 52)
             {
                 buffTime[j] = 18000;
                 tiki = true;
                 bool flag20 = true;
                 if (ownedProjectileCounts[199] > 0)
                 {
                     flag20 = false;
                 }
                 if (flag20 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 199, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 53)
             {
                 buffTime[j] = 18000;
                 lizard = true;
                 bool flag21 = true;
                 if (ownedProjectileCounts[200] > 0)
                 {
                     flag21 = false;
                 }
                 if (flag21 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 200, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 54)
             {
                 buffTime[j] = 18000;
                 parrot = true;
                 bool flag22 = true;
                 if (ownedProjectileCounts[208] > 0)
                 {
                     flag22 = false;
                 }
                 if (flag22 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 208, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 55)
             {
                 buffTime[j] = 18000;
                 truffle = true;
                 bool flag23 = true;
                 if (ownedProjectileCounts[209] > 0)
                 {
                     flag23 = false;
                 }
                 if (flag23 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 209, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 56)
             {
                 buffTime[j] = 18000;
                 sapling = true;
                 bool flag24 = true;
                 if (ownedProjectileCounts[210] > 0)
                 {
                     flag24 = false;
                 }
                 if (flag24 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 210, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 85)
             {
                 buffTime[j] = 18000;
                 cSapling = true;
                 bool flag25 = true;
                 if (ownedProjectileCounts[324] > 0)
                 {
                     flag25 = false;
                 }
                 if (flag25 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 324, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 81)
             {
                 buffTime[j] = 18000;
                 spider = true;
                 bool flag26 = true;
                 if (ownedProjectileCounts[313] > 0)
                 {
                     flag26 = false;
                 }
                 if (flag26 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 313, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 82)
             {
                 buffTime[j] = 18000;
                 squashling = true;
                 bool flag27 = true;
                 if (ownedProjectileCounts[314] > 0)
                 {
                     flag27 = false;
                 }
                 if (flag27 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 314, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 57)
             {
                 buffTime[j] = 18000;
                 wisp = true;
                 bool flag28 = true;
                 if (ownedProjectileCounts[211] > 0)
                 {
                     flag28 = false;
                 }
                 if (flag28 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 211, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 60)
             {
                 buffTime[j] = 18000;
                 crystalLeaf = true;
                 bool flag29 = true;
                 for (int num24 = 0; num24 < 1000; num24++)
                 {
                     if (Main.projectile[num24].active && Main.projectile[num24].owner == whoAmI && Main.projectile[num24].type == 226)
                     {
                         if (!flag29)
{
                             Main.projectile[num24].Kill();
                         }
                         flag29 = false;
                     }
                 }
                 if (flag29 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 226, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 127)
             {
                 buffTime[j] = 18000;
                 zephyrfish = true;
                 bool flag30 = true;
                 if (ownedProjectileCounts[380] > 0)
                 {
                     flag30 = false;
                 }
                 if (flag30 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 380, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 136)
             {
                 buffTime[j] = 18000;
                 miniMinotaur = true;
                 bool flag31 = true;
                 if (ownedProjectileCounts[398] > 0)
                 {
                     flag31 = false;
                 }
                 if (flag31 && whoAmI == Main.myPlayer)
                 {
                     Projectile.NewProjectile(GetProjectileSource_Buff(j), position.X + (float)(width / 2), position.Y + (float)(height / 2), 0f, 0f, 398, 0, 0f, whoAmI);
                 }
             }
             else if (buffType[j] == 70)
             {
                 venom = true;
             }
             else if (buffType[j] == 20)
             {
                 poisoned = true;
             }
             else if (buffType[j] == 21)
             {
                 potionDelay = buffTime[j];
             }
             else if (buffType[j] == 22)
             {
                 blind = true;
             }
             else if (buffType[j] == 80)
             {
                 blackout = true;
             }
             else if (buffType[j] == 23)
             {
                 noItems = true;
                 cursed = true;
             }
             else if (buffType[j] == 24)
             {
                 onFire = true;
             }
             else if (buffType[j] == 103)
             {
                 dripping = true;
             }
             else if (buffType[j] == 137)
             {
                 drippingSlime = true;
             }
             else if (buffType[j] == 320)
             {
                 drippingSparkleSlime = true;
             }
             else if (buffType[j] == 67)
             {
                 burned = true;
             }
             else if (buffType[j] == 68)
             {
                 suffocating = true;
             }
             else if (buffType[j] == 39)
             {
                 onFire2 = true;
             }
             else if (buffType[j] == 323)
             {
                 onFire3 = true;
             }
             else if (buffType[j] == 44)
             {
                 onFrostBurn = true;
             }
             else if (buffType[j] == 324)
             {
                 onFrostBurn2 = true;
             }
             else if (buffType[j] == 353)
             {
                 shimmering = true;
                 frozen = true;
                 fallStart = (int)(position.Y / 16f);
                 if (Main.myPlayer != whoAmI)
                 {
                     continue;
                 }
                 if (position.Y / 16f > (float)Main.UnderworldLayer)
                 {
                     if (Main.myPlayer == whoAmI)
                     {
                         DelBuff(j);
                     }
                     continue;
                 }
                 if (shimmerWet)
                 {
                     buffTime[j] = 60;
                     continue;
                 }
                 bool flag32 = false;
                 for (int num25 = (int)(position.X / 16f); (float)num25 <= (position.X + (float)width) / 16f; num25++)
                 {
                     for (int num26 = (int)(position.Y / 16f); (float)num26 <= (position.Y + (float)height) / 16f; num26++)
                     {
                         if (WorldGen.SolidTile3(num25, num26))
{
                             flag32 = true;
                         }
                     }
                 }
                 if (flag32)
                 {
                     buffTime[j] = 6;
                 }
                 else
                 {
                     DelBuff(j);
                 }
             }
             else if (buffType[j] == 163)
             {
                 headcovered = true;
                 bleed = true;
             }
             else if (buffType[j] == 164)
             {
                 vortexDebuff = true;
             }
             else if (buffType[j] == 194)
             {
                 windPushed = true;
             }
             else if (buffType[j] == 195)
             {
                 witheredArmor = true;
             }
             else if (buffType[j] == 205)
             {
                 ballistaPanic = true;
             }
             else if (buffType[j] == 196)
             {
                 witheredWeapon = true;
             }
             else if (buffType[j] == 197)
             {
                 slowOgreSpit = true;
             }
             else if (buffType[j] == 198)
             {
                 parryDamageBuff = true;
             }
             else if (buffType[j] == 145)
             {
                 moonLeech = true;
             }
             else if (buffType[j] == 149)
             {
                 webbed = true;
                 if (velocity.Y != 0f)
                 {
                     velocity = new Vector2(0f, 1E-06f);
                 }
                 else
                 {
                     velocity = Vector2.Zero;
                 }
                 jumpHeight = 0;
                 gravity = 0f;
                 moveSpeed = 0f;
                 dash = 0;
                 dashType = 0;
                 noKnockback = true;
                 RemoveAllGrapplingHooks();
             }
             else if (buffType[j] == 43)
             {
                 defendedByPaladin = true;
             }
             else if (buffType[j] == 29)
             {
                 magicCrit += 2;
                 magicDamage += 0.05f;
                 statManaMax2 += 20;
                 manaCost -= 0.02f;
             }
             else if (buffType[j] == 28)
             {
                 if (!Main.dayTime && wolfAcc && !merman)
                 {
                     lifeRegen++;
                     wereWolf = true;
                     meleeCrit += 2;
                     meleeDamage += 0.051f;
                     meleeSpeed += 0.051f;
                     statDefense += 3;
                     moveSpeed += 0.05f;
                 }
                 else
                 {
                     DelBuff(j);
                     j--;
                 }
             }
             else if (buffType[j] == 33)
             {
                 meleeDamage -= 0.051f;
                 meleeSpeed -= 0.051f;
                 statDefense -= 4;
                 moveSpeed -= 0.1f;
             }
             else if (buffType[j] == 25)
             {
                 tipsy = true;
                 statDefense -= 4;
                 meleeCrit += 2;
                 meleeDamage += 0.1f;
                 meleeSpeed += 0.1f;
             }
             else if (buffType[j] == 26)
             {
                 wellFed = true;
                 statDefense += 2;
                 meleeCrit += 2;
                 meleeDamage += 0.05f;
                 meleeSpeed += 0.05f;
                 magicCrit += 2;
                 magicDamage += 0.05f;
                 rangedCrit += 2;
                 rangedDamage += 0.05f;
                 minionDamage += 0.05f;
                 minionKB += 0.5f;
                 moveSpeed += 0.2f;
                 pickSpeed -= 0.05f;
             }
             else if (buffType[j] == 206)
             {
                 wellFed = true;
                 statDefense += 3;
                 meleeCrit += 3;
                 meleeDamage += 0.075f;
                 meleeSpeed += 0.075f;
                 magicCrit += 3;
                 magicDamage += 0.075f;
                 rangedCrit += 3;
                 rangedDamage += 0.075f;
                 minionDamage += 0.075f;
                 minionKB += 0.75f;
                 moveSpeed += 0.3f;
                 pickSpeed -= 0.1f;
             }
             else if (buffType[j] == 207)
             {
                 wellFed = true;
                 statDefense += 4;
                 meleeCrit += 4;
                 meleeDamage += 0.1f;
                 meleeSpeed += 0.1f;
                 magicCrit += 4;
                 magicDamage += 0.1f;
                 rangedCrit += 4;
                 rangedDamage += 0.1f;
                 minionDamage += 0.1f;
                 minionKB += 1f;
                 moveSpeed += 0.4f;
                 pickSpeed -= 0.15f;
             }
             else if (buffType[j] == 333)
             {
                 hungry = true;
                 statDefense -= 2;
                 meleeCrit -= 2;
                 meleeDamage -= 0.05f;
                 meleeSpeed -= 0.05f;
                 magicCrit -= 2;
                 magicDamage -= 0.05f;
                 rangedCrit -= 2;
                 rangedDamage -= 0.05f;
                 minionDamage -= 0.05f;
                 minionKB -= 0.5f;
                 pickSpeed += 0.05f;
             }
             else if (buffType[j] == 334)
             {
                 starving = true;
                 statDefense -= 4;
                 meleeCrit -= 4;
                 meleeDamage -= 0.1f;
                 meleeSpeed -= 0.1f;
                 magicCrit -= 4;
                 magicDamage -= 0.1f;
                 rangedCrit -= 4;
                 rangedDamage -= 0.1f;
                 minionDamage -= 0.1f;
                 minionKB -= 1f;
                 pickSpeed += 0.15f;
             }
             else if (buffType[j] == 336)
             {
                 heartyMeal = true;
             }
             else if (buffType[j] == 71)
             {
                 meleeEnchant = 1;
             }
             else if (buffType[j] == 73)
             {
                 meleeEnchant = 2;
             }
             else if (buffType[j] == 74)
             {
                 meleeEnchant = 3;
             }
             else if (buffType[j] == 75)
             {
                 meleeEnchant = 4;
             }
             else if (buffType[j] == 76)
             {
                 meleeEnchant = 5;
             }
             else if (buffType[j] == 77)
             {
                 meleeEnchant = 6;
             }
             else if (buffType[j] == 78)
             {
                 meleeEnchant = 7;
             }
             else if (buffType[j] == 79)
             {
                 meleeEnchant = 8;
             }
         }
         UpdateHungerBuffs();
         if (whoAmI == Main.myPlayer && luckPotion != oldLuckPotion)
         {
             luckNeedsSync = true;
             oldLuckPotion = luckPotion;
         }
     }
References Entity.active, NPC.AddBuff(), AddBuff(), Lighting.AddLight(), BuffID.Sets.BasicMountData, NPC.buffImmune, buffImmune, PlayerDeathReason.ByOther(), Entity.Center, Item.damage, NPC.damage, Main.dayTime, dead, Main.dontStarveWorld, NPC.dontTakeDamage, E, NPC.FindBuffIndex(), FindBuffIndex(), NPC.friendly, hostile, Hurt(), Projectile.Kill(), Item.knockBack, PlayerDeathReason.LegacyEmpty(), Main.myPlayer, Main.netMode, Projectile.NewProjectile(), UnifiedRandom.Next(), Main.npc, Projectile.originalDamage, Projectile.owner, Main.player, Main.projectile, Main.rand, NetMessage.SendPlayerHurt(), Item.shoot, WorldGen.SolidTile3(), team, BuffID.Sets.TimeLeftDoesNotDecrease, NPC.type, Projectile.type, Main.UnderworldLayer, and Main.wofNPCIndex.