Terraria: Player.BloodButcherer_TryButchering
BloodButcherer_TryButchering()
void Player.BloodButcherer_TryButchering (NPC npc, Item sItem, float damage, float knockBack) inline private
     {
         if (_spawnBloodButcherer && Main.myPlayer == whoAmI && (npc == null || npc.CanBeChasedBy(this)))
         {
             Vector2 v = npc.Center - MountedCenter;
             v = v.SafeNormalize(Vector2.Zero);
             Vector2 vector = npc.Hitbox.ClosestPointInRect(MountedCenter) + v;
             Vector2 spinningpoint = (npc.Center - vector) * 0.8f;
             spinningpoint = spinningpoint.RotatedBy(Main.rand.NextFloatDirection() * (float)Math.PI * 0.25f);
             int num = Projectile.NewProjectile(GetProjectileSource_Item(sItem), vector.X, vector.Y, spinningpoint.X, spinningpoint.Y, 975, (int)damage, knockBack, whoAmI, 1f, npc.whoAmI);
             Main.projectile[num].StatusNPC(npc.whoAmI);
             Projectile.KillOldestJavelin(num, 975, npc.whoAmI, _bloodButchererMax5);
             _spawnBloodButcherer = false;
         }
     }
References NPC.CanBeChasedBy(), Entity.Center, Entity.Hitbox, Projectile.KillOldestJavelin(), Main.myPlayer, Projectile.NewProjectile(), Main.projectile, Main.rand, Projectile.StatusNPC(), and Entity.whoAmI.