Terraria: Player.PutItemInInventoryFromItemUsage
PutItemInInventoryFromItemUsage()
void Player.PutItemInInventoryFromItemUsage (int type, int theSelectedItem = -1) inline
     {
         for (int i = 0; i < 58; i++)
         {
             Item item = inventory[i];
             if (item.stack > 0 && item.type == type && item.stack < item.maxStack)
             {
                 item.stack++;
                 return;
             }
         }
         if (theSelectedItem >= 0 && (inventory[theSelectedItem].type == 0 || inventory[theSelectedItem].stack <= 0))
         {
             inventory[theSelectedItem].SetDefaults(type);
             return;
         }
         Item item2 = new Item();
         item2.SetDefaults(type);
         if (GetItem(whoAmI, item2, GetItemSettings.ItemCreatedFromItemUsage).stack > 0)
         {
             Item item3 = item2;
             if (theSelectedItem != -1)
             {
                 item3 = inventory[theSelectedItem];
             }
             int number = Item.NewItem(new EntitySource_ItemUse(this, item3), (int)position.X, (int)position.Y, width, height, type, 1, noBroadcast: false, 0, noGrabDelay: true);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(21, -1, -1, null, number, 1f);
             }
         }
         else
         {
             item2.position.X = base.Center.X - (float)(item2.width / 2);
             item2.position.Y = base.Center.Y - (float)(item2.height / 2);
             item2.active = true;
             PopupText.NewText(PopupTextContext.RegularItemPickup, item2, 0);
         }
     }
References Entity.active, Entity.height, GetItemSettings.ItemCreatedFromItemUsage, Item.maxStack, Main.netMode, Item.NewItem(), PopupText.NewText(), Entity.position, NetMessage.SendData(), Item.SetDefaults(), Item.stack, Item.type, and Entity.width.