Terraria: Player.DemonConch
DemonConch()
void Player.DemonConch () inline
     {
         bool canSpawn = false;
         int num = Main.maxTilesX / 2;
         int num2 = 100;
         int num3 = num2 / 2;
         int teleportStartY = Main.UnderworldLayer + 20;
         int teleportRangeY = 80;
         RandomTeleportationAttemptSettings settings = new RandomTeleportationAttemptSettings
         {
             mostlySolidFloor = true,
             avoidAnyLiquid = true,
             avoidLava = true,
             avoidHurtTiles = true,
             avoidWalls = true,
             attemptsBeforeGivingUp = 1000,
             maximumFallDistanceFromOrignalPoint = 30
         };
         Vector2 vector = CheckForGoodTeleportationSpot(ref canSpawn, num - num3, num2, teleportStartY, teleportRangeY, settings);
         if (!canSpawn)
         {
             vector = CheckForGoodTeleportationSpot(ref canSpawn, num - num2, num3, teleportStartY, teleportRangeY, settings);
         }
         if (!canSpawn)
         {
             vector = CheckForGoodTeleportationSpot(ref canSpawn, num + num3, num3, teleportStartY, teleportRangeY, settings);
         }
         if (canSpawn)
         {
             Vector2 newPos = vector;
             Teleport(newPos, 7);
             velocity = Vector2.Zero;
             if (Main.netMode == 2)
             {
                 RemoteClient.CheckSection(whoAmI, position);
                 NetMessage.SendData(65, -1, -1, null, 0, whoAmI, newPos.X, newPos.Y, 7);
             }
         }
         else
         {
             Vector2 newPos2 = position;
             Teleport(newPos2, 7);
             velocity = Vector2.Zero;
             if (Main.netMode == 2)
             {
                 RemoteClient.CheckSection(whoAmI, position);
                 NetMessage.SendData(65, -1, -1, null, 0, whoAmI, newPos2.X, newPos2.Y, 7, 1);
             }
         }
     }
References RemoteClient.CheckSection(), Main.maxTilesX, Main.netMode, NetMessage.SendData(), and Main.UnderworldLayer.
Referenced by MessageBuffer.GetData().