Terraria: Player.AdjTiles
AdjTiles()
void Player.AdjTiles () inline
     {
         int num = 4;
         int num2 = 3;
         if (ateArtisanBread)
         {
             num += 4;
             num2 += 4;
         }
         for (int i = 0; i < TileID.Count; i++)
         {
             oldAdjTile[i] = adjTile[i];
             adjTile[i] = false;
         }
         oldAdjWater = adjWater;
         adjWater = false;
         oldAdjHoney = adjHoney;
         adjHoney = false;
         oldAdjLava = adjLava;
         adjLava = false;
         alchemyTable = false;
         int num3 = (int)((position.X + (float)(width / 2)) / 16f);
         int num4 = (int)((position.Y + (float)height) / 16f);
         for (int j = num3 - num; j <= num3 + num; j++)
         {
             for (int k = num4 - num2; k < num4 + num2; k++)
             {
                 if (Main.tile[j, k].active())
                 {
                     adjTile[Main.tile[j, k].type] = true;
                     switch (Main.tile[j, k].type)
                     {
                     case 77:
                     case 302:
                         adjTile[17] = true;
                         break;
                     case 133:
                         adjTile[17] = true;
                         adjTile[77] = true;
                         break;
                     case 134:
                         adjTile[16] = true;
                         break;
                     case 354:
                     case 469:
                     case 487:
                         adjTile[14] = true;
                         break;
                     case 355:
                         adjTile[13] = true;
                         adjTile[14] = true;
                         alchemyTable = true;
                         break;
                     }
                 }
                 if (Main.tile[j, k].liquid > 200 && Main.tile[j, k].liquidType() == 0)
                 {
                     adjWater = true;
                 }
                 if (Main.tile[j, k].liquid > 200 && Main.tile[j, k].liquidType() == 2)
                 {
                     adjHoney = true;
                 }
                 if (Main.tile[j, k].liquid > 200 && Main.tile[j, k].liquidType() == 1)
                 {
                     adjLava = true;
                 }
             }
         }
         if (!Main.playerInventory)
         {
             return;
         }
         bool flag = false;
         for (int l = 0; l < TileID.Count; l++)
         {
             if (oldAdjTile[l] != adjTile[l])
             {
                 flag = true;
                 break;
             }
         }
         if (adjWater != oldAdjWater)
         {
             flag = true;
         }
         if (adjHoney != oldAdjHoney)
         {
             flag = true;
         }
         if (adjLava != oldAdjLava)
         {
             flag = true;
         }
         if (flag)
         {
             Recipe.FindRecipes();
         }
     }
References Tile.active(), TileID.Count, Recipe.FindRecipes(), Tile.liquid, Tile.liquidType(), Main.playerInventory, Main.tile, and Tile.type.
Referenced by Main.DoUpdate_WhilePaused().