Terraria: Player.FindClosest
FindClosest()
static byte Player.FindClosest (Vector2 Position, int Width, int Height) inline static
     {
         byte result = 0;
         for (int i = 0; i < 255; i++)
         {
             if (Main.player[i].active)
             {
                 result = (byte)i;
                 break;
             }
         }
         float num = -1f;
         for (int j = 0; j < 255; j++)
         {
             if (Main.player[j].active && !Main.player[j].dead)
             {
                 float num2 = Math.Abs(Main.player[j].position.X + (float)(Main.player[j].width / 2) - (Position.X + (float)(Width / 2))) + Math.Abs(Main.player[j].position.Y + (float)(Main.player[j].height / 2) - (Position.Y + (float)(Height / 2)));
                 if (num == -1f || num2 < num)
                 {
                     num = num2;
                     result = (byte)j;
                 }
             }
         }
         return result;
     }
References Entity.active, dead, Entity.height, Main.player, Entity.position, and Entity.width.
Referenced by NPC.AI(), Projectile.AI_001(), NPC.AI_121_QueenSlime(), WorldGen.CheckSign(), WorldGen.GetPlayerForTile(), WorldGen.KillTile_DropBait(), WorldGen.KillTile_GetTreeDrops(), NPC.NPCLoot(), EmoteBubble.PickNPCEmote(), WorldGen.SmashAltar(), WorldGen.SpawnThingsFromPot(), NPC.SpawnWOF(), DD2Event.SummonBetsy(), Main.UpdateTime(), and WorldGen.UpdateWorld().