Terraria: Player.OpenBossBag
OpenBossBag()
void Player.OpenBossBag (int type) inline
     {
         GameModeData gameModeInfo = Main.GameModeInfo;
         float strength = 1f;
         if (gameModeInfo.IsJourneyMode)
         {
             CreativePowers.DifficultySliderPower power = CreativePowerManager.Instance.GetPower<CreativePowers.DifficultySliderPower>();
             if (power != null && power.GetIsUnlocked())
             {
                 strength = power.StrengthMultiplierToGiveNPCs;
             }
         }
         bool flag = new NPCStrengthHelper(gameModeInfo, strength, Main.getGoodWorld).IsMasterMode || Main.masterMode;
         IEntitySource itemSource_OpenItem = GetItemSource_OpenItem(type);
         switch (type)
         {
         case 3318:
         {
             if (Main.rand.Next(2) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2430);
             }
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2493);
             }
             int num4 = Main.rand.Next(256, 259);
             int num5;
             for (num5 = Main.rand.Next(256, 259); num5 == num4; num5 = Main.rand.Next(256, 259))
             {
             }
             QuickSpawnItem(itemSource_OpenItem, num4);
             QuickSpawnItem(itemSource_OpenItem, num5);
             if (Main.rand.Next(2) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2610);
             }
             else
             {
                 QuickSpawnItem(itemSource_OpenItem, 2585);
             }
             QuickSpawnItem(itemSource_OpenItem, 998);
             QuickSpawnItem(itemSource_OpenItem, 3090);
             break;
         }
         case 3319:
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2112);
             }
             if (Main.rand.Next(30) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 1299);
             }
             if (WorldGen.crimson)
             {
                 int num9 = Main.rand.Next(20) + 10;
                 num9 += Main.rand.Next(20) + 10;
                 num9 += Main.rand.Next(20) + 10;
                 QuickSpawnItem(itemSource_OpenItem, 880, num9);
                 num9 = Main.rand.Next(3) + 1;
                 QuickSpawnItem(itemSource_OpenItem, 2171, num9);
             }
             else
             {
                 int num10 = Main.rand.Next(20) + 10;
                 num10 += Main.rand.Next(20) + 10;
                 num10 += Main.rand.Next(20) + 10;
                 QuickSpawnItem(itemSource_OpenItem, 56, num10);
                 num10 = Main.rand.Next(3) + 1;
                 QuickSpawnItem(itemSource_OpenItem, 59, num10);
                 num10 = Main.rand.Next(30) + 20;
                 QuickSpawnItem(itemSource_OpenItem, 47, num10);
             }
             QuickSpawnItem(itemSource_OpenItem, 3097);
             break;
         case 3320:
         {
             int num3 = Main.rand.Next(15, 30);
             if (flag)
             {
                 num3 = Main.rand.Next(110, 136);
                 QuickSpawnItem(itemSource_OpenItem, 56, num3);
             }
             else
             {
                 num3 = Main.rand.Next(80, 111);
                 QuickSpawnItem(itemSource_OpenItem, 56, num3);
             }
             if (flag)
             {
                 num3 = Main.rand.Next(30, 51);
                 QuickSpawnItem(itemSource_OpenItem, 86, num3);
             }
             else
             {
                 num3 = Main.rand.Next(20, 41);
                 QuickSpawnItem(itemSource_OpenItem, 86, num3);
             }
             if (Main.rand.Next(20) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 994);
             }
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2111);
             }
             QuickSpawnItem(itemSource_OpenItem, 3224);
             break;
         }
         case 3321:
         {
             int num8 = Main.rand.Next(20, 46);
             if (flag)
             {
                 num8 = Main.rand.Next(110, 136);
                 QuickSpawnItem(itemSource_OpenItem, 880, num8);
             }
             else
             {
                 num8 = Main.rand.Next(80, 111);
                 QuickSpawnItem(itemSource_OpenItem, 880, num8);
             }
             if (flag)
             {
                 num8 = Main.rand.Next(30, 51);
                 QuickSpawnItem(itemSource_OpenItem, 1329, num8);
             }
             else
             {
                 num8 = Main.rand.Next(20, 41);
                 QuickSpawnItem(itemSource_OpenItem, 1329, num8);
             }
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2104);
             }
             if (Main.rand.Next(20) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 3060);
             }
             QuickSpawnItem(itemSource_OpenItem, 3223);
             break;
         }
         case 3322:
         {
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2108);
             }
             int num6 = Main.rand.Next(3);
             switch (num6)
             {
             case 0:
                 num6 = 1121;
                 break;
             case 1:
                 num6 = 1123;
                 break;
             case 2:
                 num6 = 2888;
                 break;
             }
             QuickSpawnItem(itemSource_OpenItem, num6);
             QuickSpawnItem(itemSource_OpenItem, 3333);
             if (Main.rand.Next(3) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 1132);
             }
             if (Main.rand.Next(9) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 1170);
             }
             if (Main.rand.Next(9) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2502);
             }
             QuickSpawnItem(itemSource_OpenItem, 1129);
             QuickSpawnItem(itemSource_OpenItem, Main.rand.Next(842, 845));
             QuickSpawnItem(itemSource_OpenItem, 1130, Main.rand.Next(10, 30));
             QuickSpawnItem(itemSource_OpenItem, 2431, Main.rand.Next(17, 30));
             break;
         }
         case 3323:
             QuickSpawnItem(itemSource_OpenItem, 3245);
             switch (Main.rand.Next(3))
             {
             case 0:
                 QuickSpawnItem(itemSource_OpenItem, 1281);
                 break;
             case 1:
                 QuickSpawnItem(itemSource_OpenItem, 1273);
                 break;
             default:
                 QuickSpawnItem(itemSource_OpenItem, 1313);
                 break;
             }
             break;
         case 3324:
         {
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2105);
             }
             QuickSpawnItem(itemSource_OpenItem, 367);
             if (!extraAccessory)
             {
                 QuickSpawnItem(itemSource_OpenItem, 3335);
             }
             int num7 = Main.rand.Next(4);
             num7 = ((num7 != 3) ? (489 + num7) : 2998);
             QuickSpawnItem(itemSource_OpenItem, num7);
             switch (Main.rand.Next(4))
             {
             case 0:
                 QuickSpawnItem(itemSource_OpenItem, 514);
                 break;
             case 1:
                 QuickSpawnItem(itemSource_OpenItem, 426);
                 break;
             case 2:
                 QuickSpawnItem(itemSource_OpenItem, 434);
                 break;
             case 3:
                 QuickSpawnItem(itemSource_OpenItem, 4912);
                 break;
             }
             break;
         }
         case 3325:
             TryGettingDevArmor(itemSource_OpenItem);
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2113);
             }
             QuickSpawnItem(itemSource_OpenItem, 548, Main.rand.Next(25, 41));
             QuickSpawnItem(itemSource_OpenItem, 1225, Main.rand.Next(20, 36));
             QuickSpawnItem(itemSource_OpenItem, 3355);
             break;
         case 3326:
             TryGettingDevArmor(itemSource_OpenItem);
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2106);
             }
             QuickSpawnItem(itemSource_OpenItem, 549, Main.rand.Next(25, 41));
             QuickSpawnItem(itemSource_OpenItem, 1225, Main.rand.Next(20, 36));
             QuickSpawnItem(itemSource_OpenItem, 3354);
             break;
         case 3327:
             TryGettingDevArmor(itemSource_OpenItem);
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2107);
             }
             QuickSpawnItem(itemSource_OpenItem, 547, Main.rand.Next(25, 41));
             QuickSpawnItem(itemSource_OpenItem, 1225, Main.rand.Next(20, 36));
             QuickSpawnItem(itemSource_OpenItem, 3356);
             break;
         case 3328:
             TryGettingDevArmor(itemSource_OpenItem);
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2109);
             }
             QuickSpawnItem(itemSource_OpenItem, 1141);
             QuickSpawnItem(itemSource_OpenItem, 3336);
             if (Main.rand.Next(15) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 1182);
             }
             if (Main.rand.Next(20) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 1305);
             }
             if (Main.rand.Next(2) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 1157);
             }
             if (Main.rand.Next(10) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 3021);
             }
             switch (Main.rand.Next(7))
             {
             case 0:
                 QuickSpawnItem(itemSource_OpenItem, 758);
                 QuickSpawnItem(itemSource_OpenItem, 771, Main.rand.Next(50, 150));
                 break;
             case 1:
                 QuickSpawnItem(itemSource_OpenItem, 1255);
                 break;
             case 2:
                 QuickSpawnItem(itemSource_OpenItem, 788);
                 break;
             case 3:
                 QuickSpawnItem(itemSource_OpenItem, 1178);
                 break;
             case 4:
                 QuickSpawnItem(itemSource_OpenItem, 1259);
                 break;
             case 5:
                 QuickSpawnItem(itemSource_OpenItem, 1155);
                 break;
             case 6:
                 QuickSpawnItem(itemSource_OpenItem, 3018);
                 break;
             }
             break;
         case 3329:
             TryGettingDevArmor(itemSource_OpenItem);
             QuickSpawnItem(itemSource_OpenItem, 3337);
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2110);
             }
             if (Main.rand.Next(3) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 1294);
             }
             switch (Main.rand.Next(7))
             {
             case 0:
                 QuickSpawnItem(itemSource_OpenItem, 1258);
                 QuickSpawnItem(itemSource_OpenItem, 1261, Main.rand.Next(60, 100));
                 break;
             case 1:
                 QuickSpawnItem(itemSource_OpenItem, 1122);
                 break;
             case 2:
                 QuickSpawnItem(itemSource_OpenItem, 899);
                 break;
             case 3:
                 QuickSpawnItem(itemSource_OpenItem, 1248);
                 break;
             case 4:
                 QuickSpawnItem(itemSource_OpenItem, 1295);
                 break;
             case 5:
                 QuickSpawnItem(itemSource_OpenItem, 1296);
                 break;
             default:
                 QuickSpawnItem(itemSource_OpenItem, 1297);
                 break;
             }
             QuickSpawnItem(itemSource_OpenItem, 2218, Main.rand.Next(18, 24));
             break;
         case 3330:
             TryGettingDevArmor(itemSource_OpenItem);
             QuickSpawnItem(itemSource_OpenItem, 3367);
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2588);
             }
             if (Main.rand.Next(10) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 2609);
             }
             switch (Main.rand.Next(5))
             {
             case 0:
                 QuickSpawnItem(itemSource_OpenItem, 2611);
                 break;
             case 1:
                 QuickSpawnItem(itemSource_OpenItem, 2624);
                 break;
             case 2:
                 QuickSpawnItem(itemSource_OpenItem, 2622);
                 break;
             case 3:
                 QuickSpawnItem(itemSource_OpenItem, 2621);
                 break;
             case 4:
                 if (Main.remixWorld)
                 {
                     QuickSpawnItem(itemSource_OpenItem, 157);
                 }
                 else
                 {
                     QuickSpawnItem(itemSource_OpenItem, 2623);
                 }
                 break;
             }
             break;
         case 3331:
             TryGettingDevArmor(itemSource_OpenItem);
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 3372);
             }
             break;
         case 3860:
             TryGettingDevArmor(itemSource_OpenItem);
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 3863);
             }
             switch (Main.rand.Next(4))
             {
             case 0:
                 QuickSpawnItem(itemSource_OpenItem, 3859);
                 break;
             case 1:
                 QuickSpawnItem(itemSource_OpenItem, 3827);
                 break;
             case 2:
                 QuickSpawnItem(itemSource_OpenItem, 3870);
                 break;
             default:
                 QuickSpawnItem(itemSource_OpenItem, 3858);
                 break;
             }
             if (Main.rand.Next(4) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 3883);
             }
             QuickSpawnItem(itemSource_OpenItem, 3817, Main.rand.Next(30, 50));
             break;
         case 4782:
             TryGettingDevArmor(itemSource_OpenItem);
             QuickSpawnItem(itemSource_OpenItem, 4989);
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 4784);
             }
             if (Main.rand.Next(10) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 4823);
             }
             if (Main.rand.Next(20) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 4715);
             }
             if (Main.rand.Next(4) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 4778);
             }
             if (Main.rand.Next(20) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 5075);
             }
             switch (Main.rand.Next(4))
             {
             case 0:
                 QuickSpawnItem(itemSource_OpenItem, 4923);
                 break;
             case 1:
                 QuickSpawnItem(itemSource_OpenItem, 4952);
                 break;
             case 2:
                 QuickSpawnItem(itemSource_OpenItem, 4953);
                 break;
             case 3:
                 QuickSpawnItem(itemSource_OpenItem, 4914);
                 break;
             }
             break;
         case 4957:
         {
             QuickSpawnItem(itemSource_OpenItem, 4987);
             QuickSpawnItem(itemSource_OpenItem, 4986, Main.rand.Next(25, 75));
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 4959);
             }
             if (Main.rand.Next(2) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 4981);
             }
             if (Main.rand.Next(3) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 4758);
             }
             if (Main.rand.Next(2) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 4980);
             }
             int num = Main.rand.Next(4982, 4985);
             int num2 = Main.rand.Next(4982, 4985);
             while (num2 == num)
             {
                 num = Main.rand.Next(4982, 4985);
             }
             QuickSpawnItem(itemSource_OpenItem, num);
             QuickSpawnItem(itemSource_OpenItem, num2);
             break;
         }
         }
         switch (type)
         {
         case 5111:
             QuickSpawnItem(itemSource_OpenItem, 5100);
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 5109);
             }
             if (Main.rand.Next(14) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 5385);
             }
             if (Main.rand.Next(3) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 5098);
             }
             if (Main.rand.Next(3) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 5101);
             }
             if (Main.rand.Next(3) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 5113);
             }
             switch (Main.rand.Next(4))
             {
             case 0:
                 QuickSpawnItem(itemSource_OpenItem, 5117);
                 break;
             case 1:
                 QuickSpawnItem(itemSource_OpenItem, 5118);
                 break;
             case 2:
                 QuickSpawnItem(itemSource_OpenItem, 5119);
                 break;
             case 3:
                 QuickSpawnItem(itemSource_OpenItem, 5095);
                 break;
             }
             break;
         case 3332:
         {
             TryGettingDevArmor(itemSource_OpenItem);
             if (Main.rand.Next(7) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 3373);
             }
             if (Main.rand.Next(10) == 0)
             {
                 QuickSpawnItem(itemSource_OpenItem, 4469);
             }
             if (!HasItem(3384))
             {
                 QuickSpawnItem(itemSource_OpenItem, 3384);
             }
             QuickSpawnItem(itemSource_OpenItem, 3460, Main.rand.Next(90, 111));
             QuickSpawnItem(itemSource_OpenItem, 1131);
             QuickSpawnItem(itemSource_OpenItem, 3577);
             QuickSpawnItem(itemSource_OpenItem, 4954);
             List<int> list = new List<int> { 3063, 3389, 3065, 1553, 3930, 3541, 3570, 3571, 3569 };
             for (int i = 0; i < 2; i++)
             {
                 int index = Main.rand.Next(list.Count);
                 int item = list[index];
                 QuickSpawnItem(itemSource_OpenItem, item);
                 list.RemoveAt(index);
             }
             break;
         }
         }
         int num11 = -1;
         if (type == 3318)
         {
             num11 = 50;
         }
         if (type == 3319)
         {
             num11 = 4;
         }
         if (type == 3320)
         {
             num11 = 13;
         }
         if (type == 3321)
         {
             num11 = 266;
         }
         if (type == 3322)
         {
             num11 = 222;
         }
         if (type == 3323)
         {
             num11 = 35;
         }
         if (type == 3324)
         {
             num11 = 113;
         }
         if (type == 3325)
         {
             num11 = 134;
         }
         if (type == 3326)
         {
             num11 = 125;
         }
         if (type == 3327)
         {
             num11 = 127;
         }
         if (type == 3328)
         {
             num11 = 262;
         }
         if (type == 3329)
         {
             num11 = 245;
         }
         if (type == 3330)
         {
             num11 = 370;
         }
         if (type == 3331)
         {
             num11 = 439;
         }
         if (type == 3332)
         {
             num11 = 398;
         }
         if (type == 3860)
         {
             num11 = 551;
         }
         if (type == 3861)
         {
             num11 = 576;
         }
         if (type == 3862)
         {
             num11 = 564;
         }
         if (type == 4782)
         {
             num11 = 636;
         }
         if (type == 4957)
         {
             num11 = 657;
         }
         if (type == 5111)
         {
             num11 = 668;
         }
         if (num11 <= 0)
         {
             return;
         }
         NPC nPC = new NPC();
         nPC.SetDefaults(num11);
         float value = nPC.value;
         value *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
         if (Main.rand.Next(5) == 0)
         {
             value *= 1f + (float)Main.rand.Next(5, 11) * 0.01f;
         }
         if (Main.rand.Next(10) == 0)
         {
             value *= 1f + (float)Main.rand.Next(10, 21) * 0.01f;
         }
         if (Main.rand.Next(15) == 0)
         {
             value *= 1f + (float)Main.rand.Next(15, 31) * 0.01f;
         }
         if (Main.rand.Next(20) == 0)
         {
             value *= 1f + (float)Main.rand.Next(20, 41) * 0.01f;
         }
         while ((int)value > 0)
         {
             if (value > 1000000f)
             {
                 int num12 = (int)(value / 1000000f);
                 value -= (float)(1000000 * num12);
                 QuickSpawnItem(itemSource_OpenItem, 74, num12);
                 continue;
             }
             if (value > 10000f)
             {
                 int num13 = (int)(value / 10000f);
                 value -= (float)(10000 * num13);
                 QuickSpawnItem(itemSource_OpenItem, 73, num13);
                 continue;
             }
             if (value > 100f)
             {
                 int num14 = (int)(value / 100f);
                 value -= (float)(100 * num14);
                 QuickSpawnItem(itemSource_OpenItem, 72, num14);
                 continue;
             }
             int num15 = (int)value;
             if (num15 < 1)
             {
                 num15 = 1;
             }
             value -= (float)num15;
             QuickSpawnItem(itemSource_OpenItem, 71, num15);
         }
     }
References WorldGen.crimson, Main.GameModeInfo, Main.getGoodWorld, CreativePowerManager.Instance, GameModeData.IsJourneyMode, NPCStrengthHelper.IsMasterMode, Main.masterMode, UnifiedRandom.Next(), Main.rand, Main.remixWorld, NPC.SetDefaults(), CreativePowers.DifficultySliderPower.StrengthMultiplierToGiveNPCs, and NPC.value.
Referenced by ItemSlot.TryOpenContainer().