Terraria: Player.DashMovement
DashMovement()
void Player.DashMovement () inline
     {
         if (dashDelay == 0)
         {
             dash = dashType;
         }
         if (dash == 0)
         {
             dashTime = 0;
             dashDelay = 0;
         }
         if (dash == 2 && eocDash > 0)
         {
             if (eocHit < 0)
             {
                 Rectangle rectangle = new Rectangle((int)((double)position.X + (double)velocity.X * 0.5 - 4.0), (int)((double)position.Y + (double)velocity.Y * 0.5 - 4.0), width + 8, height + 8);
                 for (int i = 0; i < 200; i++)
                 {
                     NPC nPC = Main.npc[i];
                     if (!nPC.active || nPC.dontTakeDamage || nPC.friendly || (nPC.aiStyle == 112 && !(nPC.ai[2] <= 1f)) || !CanNPCBeHitByPlayerOrPlayerProjectile(nPC))
                     {
                         continue;
                     }
                     Rectangle rect = nPC.getRect();
                     if (rectangle.Intersects(rect) && (nPC.noTileCollide || CanHit(nPC)))
                     {
                         float num = 30f * meleeDamage;
                         float num2 = 9f;
                         bool crit = false;
                         if (kbGlove)
{
                             num2 *= 2f;
                         }
                         if (kbBuff)
{
                             num2 *= 1.5f;
                         }
                         if (Main.rand.Next(100) < meleeCrit)
{
                             crit = true;
                         }
                         int num3 = direction;
                         if (velocity.X < 0f)
{
                             num3 = -1;
                         }
                         if (velocity.X > 0f)
{
                             num3 = 1;
                         }
                         if (whoAmI == Main.myPlayer)
{
                             ApplyDamageToNPC(nPC, (int)num, num2, num3, crit);
                         }
                         eocDash = 10;
                         dashDelay = 30;
                         velocity.X = -num3 * 9;
                         velocity.Y = -4f;
                         GiveImmuneTimeForCollisionAttack(4);
                         eocHit = i;
                     }
                 }
             }
             else if ((!controlLeft || !(velocity.X < 0f)) && (!controlRight || !(velocity.X > 0f)))
             {
                 velocity.X *= 0.95f;
             }
         }
         if (dash == 3 && dashDelay < 0 && whoAmI == Main.myPlayer)
         {
             Rectangle rectangle2 = new Rectangle((int)((double)position.X + (double)velocity.X * 0.5 - 4.0), (int)((double)position.Y + (double)velocity.Y * 0.5 - 4.0), width + 8, height + 8);
             for (int j = 0; j < 200; j++)
             {
                 NPC nPC2 = Main.npc[j];
                 if (!nPC2.active || nPC2.dontTakeDamage || nPC2.friendly || nPC2.immune[whoAmI] > 0 || (nPC2.aiStyle == 112 && !(nPC2.ai[2] <= 1f)) || !CanNPCBeHitByPlayerOrPlayerProjectile(nPC2))
                 {
                     continue;
                 }
                 Rectangle rect2 = nPC2.getRect();
                 if (rectangle2.Intersects(rect2) && (nPC2.noTileCollide || CanHit(nPC2)))
                 {
                     if (!solarDashConsumedFlare)
                     {
                         solarDashConsumedFlare = true;
                         ConsumeSolarFlare();
                     }
                     float num4 = 150f * meleeDamage;
                     float num5 = 9f;
                     bool crit2 = false;
                     if (kbGlove)
                     {
                         num5 *= 2f;
                     }
                     if (kbBuff)
                     {
                         num5 *= 1.5f;
                     }
                     if (Main.rand.Next(100) < meleeCrit)
                     {
                         crit2 = true;
                     }
                     int num6 = direction;
                     if (velocity.X < 0f)
                     {
                         num6 = -1;
                     }
                     if (velocity.X > 0f)
                     {
                         num6 = 1;
                     }
                     if (whoAmI == Main.myPlayer)
                     {
                         ApplyDamageToNPC(nPC2, (int)num4, num5, num6, crit2);
                         int num7 = Projectile.NewProjectile(GetProjectileSource_OnHit(nPC2, 2), base.Center.X, base.Center.Y, 0f, 0f, 608, (int)num4, 15f, Main.myPlayer);
                         Main.projectile[num7].Kill();
                     }
                     nPC2.immune[whoAmI] = 6;
                     GiveImmuneTimeForCollisionAttack(4);
                 }
             }
         }
         if (dashDelay > 0)
         {
             if (eocDash > 0)
             {
                 eocDash--;
             }
             if (eocDash == 0)
             {
                 eocHit = -1;
             }
             dashDelay--;
         }
         else if (dashDelay < 0)
         {
             StopVanityActions();
             float num8 = 12f;
             float num9 = 0.992f;
             float num10 = Math.Max(accRunSpeed, maxRunSpeed);
             float num11 = 0.96f;
             int num12 = 20;
             if (dash == 1)
             {
                 for (int k = 0; k < 2; k++)
                 {
                     int num13 = ((velocity.Y != 0f) ? Dust.NewDust(new Vector2(position.X, position.Y + (float)(height / 2) - 8f), width, 16, 31, 0f, 0f, 100, default(Color), 1.4f) : Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 4f), width, 8, 31, 0f, 0f, 100, default(Color), 1.4f));
                     Main.dust[num13].velocity *= 0.1f;
                     Main.dust[num13].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                 }
             }
             else if (dash == 2)
             {
                 for (int l = 0; l < 0; l++)
                 {
                     int num14 = ((velocity.Y != 0f) ? Dust.NewDust(new Vector2(position.X, position.Y + (float)(height / 2) - 8f), width, 16, 31, 0f, 0f, 100, default(Color), 1.4f) : Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 4f), width, 8, 31, 0f, 0f, 100, default(Color), 1.4f));
                     Main.dust[num14].velocity *= 0.1f;
                     Main.dust[num14].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                 }
                 num9 = 0.985f;
                 num11 = 0.94f;
                 num12 = 30;
             }
             else if (dash == 3)
             {
                 for (int m = 0; m < 4; m++)
                 {
                     int num15 = Dust.NewDust(new Vector2(position.X, position.Y + 4f), width, height - 8, 6, 0f, 0f, 100, default(Color), 1.7f);
                     Main.dust[num15].velocity *= 0.1f;
                     Main.dust[num15].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                     Main.dust[num15].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                     Main.dust[num15].noGravity = true;
                     if (Main.rand.Next(2) == 0)
                     {
                         Main.dust[num15].fadeIn = 0.5f;
                     }
                 }
                 num8 = 14f;
                 num9 = 0.985f;
                 num11 = 0.94f;
                 num12 = 20;
             }
             else if (dash == 4)
             {
                 for (int n = 0; n < 2; n++)
                 {
                     int num16 = Dust.NewDust(new Vector2(position.X, position.Y + 4f), width, height - 8, 229, 0f, 0f, 100, default(Color), 1.2f);
                     Main.dust[num16].velocity *= 0.1f;
                     Main.dust[num16].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                     Main.dust[num16].noGravity = true;
                     if (Main.rand.Next(2) == 0)
                     {
                         Main.dust[num16].fadeIn = 0.3f;
                     }
                 }
                 num9 = 0.985f;
                 num11 = 0.94f;
                 num12 = 20;
             }
             if (dash == 5)
             {
                 for (int num17 = 0; num17 < 2; num17++)
                 {
                     int type = Main.rand.NextFromList(new short[3] { 68, 69, 70 });
                     int num18 = ((velocity.Y != 0f) ? Dust.NewDust(new Vector2(position.X, position.Y + (float)(height / 2) - 8f), width, 16, type, 0f, 0f, 100) : Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 4f), width, 8, type, 0f, 0f, 100));
                     Main.dust[num18].velocity *= 0.2f;
                     Main.dust[num18].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                     Main.dust[num18].fadeIn = 0.5f + (float)Main.rand.Next(20) * 0.01f;
                     Main.dust[num18].noGravity = true;
                     Main.dust[num18].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                 }
             }
             if (dash <= 0)
             {
                 return;
             }
             doorHelper.AllowOpeningDoorsByVelocityAloneForATime(num12 * 3);
             vortexStealthActive = false;
             if (velocity.X > num8 || velocity.X < 0f - num8)
             {
                 velocity.X *= num9;
                 return;
             }
             if (velocity.X > num10 || velocity.X < 0f - num10)
             {
                 velocity.X *= num11;
                 return;
             }
             dashDelay = num12;
             if (velocity.X < 0f)
             {
                 velocity.X = 0f - num10;
             }
             else if (velocity.X > 0f)
             {
                 velocity.X = num10;
             }
         }
         else
         {
             if (dash <= 0 || mount.Active)
             {
                 return;
             }
             if (dash == 1)
             {
                 DoCommonDashHandle(out var dir, out var dashing);
                 if (dashing)
                 {
                     velocity.X = 16.9f * (float)dir;
                     Point point = (base.Center + new Vector2(dir * width / 2 + 2, gravDir * (float)(-height) / 2f + gravDir * 2f)).ToTileCoordinates();
                     Point point2 = (base.Center + new Vector2(dir * width / 2 + 2, 0f)).ToTileCoordinates();
                     if (WorldGen.SolidOrSlopedTile(point.X, point.Y) || WorldGen.SolidOrSlopedTile(point2.X, point2.Y))
                     {
                         velocity.X /= 2f;
                     }
                     dashDelay = -1;
                     for (int num19 = 0; num19 < 20; num19++)
                     {
                         int num20 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 2f);
                         Main.dust[num20].position.X += Main.rand.Next(-5, 6);
                         Main.dust[num20].position.Y += Main.rand.Next(-5, 6);
                         Main.dust[num20].velocity *= 0.2f;
                         Main.dust[num20].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                     }
                     int num21 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 34f), default(Vector2), Main.rand.Next(61, 64));
                     Main.gore[num21].velocity.X = (float)Main.rand.Next(-50, 51) * 0.01f;
                     Main.gore[num21].velocity.Y = (float)Main.rand.Next(-50, 51) * 0.01f;
                     Main.gore[num21].velocity *= 0.4f;
                     num21 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 14f), default(Vector2), Main.rand.Next(61, 64));
                     Main.gore[num21].velocity.X = (float)Main.rand.Next(-50, 51) * 0.01f;
                     Main.gore[num21].velocity.Y = (float)Main.rand.Next(-50, 51) * 0.01f;
                     Main.gore[num21].velocity *= 0.4f;
                 }
             }
             else if (dash == 2)
             {
                 DoCommonDashHandle(out var dir2, out var dashing2);
                 if (dashing2)
                 {
                     velocity.X = 14.5f * (float)dir2;
                     Point point3 = (base.Center + new Vector2(dir2 * width / 2 + 2, gravDir * (float)(-height) / 2f + gravDir * 2f)).ToTileCoordinates();
                     Point point4 = (base.Center + new Vector2(dir2 * width / 2 + 2, 0f)).ToTileCoordinates();
                     if (WorldGen.SolidOrSlopedTile(point3.X, point3.Y) || WorldGen.SolidOrSlopedTile(point4.X, point4.Y))
                     {
                         velocity.X /= 2f;
                     }
                     dashDelay = -1;
                     eocDash = 15;
                     for (int num22 = 0; num22 < 0; num22++)
                     {
                         int num23 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 2f);
                         Main.dust[num23].position.X += Main.rand.Next(-5, 6);
                         Main.dust[num23].position.Y += Main.rand.Next(-5, 6);
                         Main.dust[num23].velocity *= 0.2f;
                         Main.dust[num23].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                     }
                 }
             }
             else if (dash == 3)
             {
                 DoCommonDashHandle(out var dir3, out var dashing3, SolarDashStart);
                 if (dashing3)
                 {
                     velocity.X = 21.9f * (float)dir3;
                     Point point5 = (base.Center + new Vector2(dir3 * width / 2 + 2, gravDir * (float)(-height) / 2f + gravDir * 2f)).ToTileCoordinates();
                     Point point6 = (base.Center + new Vector2(dir3 * width / 2 + 2, 0f)).ToTileCoordinates();
                     if (WorldGen.SolidOrSlopedTile(point5.X, point5.Y) || WorldGen.SolidOrSlopedTile(point6.X, point6.Y))
                     {
                         velocity.X /= 2f;
                     }
                     dashDelay = -1;
                     for (int num24 = 0; num24 < 20; num24++)
                     {
                         int num25 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2f);
                         Main.dust[num25].position.X += Main.rand.Next(-5, 6);
                         Main.dust[num25].position.Y += Main.rand.Next(-5, 6);
                         Main.dust[num25].velocity *= 0.2f;
                         Main.dust[num25].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                         Main.dust[num25].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                         Main.dust[num25].noGravity = true;
                         Main.dust[num25].fadeIn = 0.5f;
                     }
                 }
             }
             if (dash != 5)
             {
                 return;
             }
             DoCommonDashHandle(out var dir4, out var dashing4);
             if (dashing4)
             {
                 velocity.X = 16.9f * (float)dir4;
                 Point point7 = (base.Center + new Vector2(dir4 * width / 2 + 2, gravDir * (float)(-height) / 2f + gravDir * 2f)).ToTileCoordinates();
                 Point point8 = (base.Center + new Vector2(dir4 * width / 2 + 2, 0f)).ToTileCoordinates();
                 if (WorldGen.SolidOrSlopedTile(point7.X, point7.Y) || WorldGen.SolidOrSlopedTile(point8.X, point8.Y))
                 {
                     velocity.X /= 2f;
                 }
                 dashDelay = -1;
                 for (int num26 = 0; num26 < 20; num26++)
                 {
                     int type2 = Main.rand.NextFromList(new short[3] { 68, 69, 70 });
                     int num27 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, type2, 0f, 0f, 100, default(Color), 1.5f);
                     Main.dust[num27].position.X += Main.rand.Next(-5, 6);
                     Main.dust[num27].position.Y += Main.rand.Next(-5, 6);
                     Main.dust[num27].velocity = DirectionTo(Main.dust[num27].position) * 2f;
                     Main.dust[num27].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                     Main.dust[num27].fadeIn = 0.5f + (float)Main.rand.Next(20) * 0.01f;
                     Main.dust[num27].noGravity = true;
                     Main.dust[num27].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                 }
             }
         }
     }
References Entity.active, NPC.ai, NPC.aiStyle, GameShaders.Armor, Color, NPC.dontTakeDamage, Main.dust, Dust.fadeIn, NPC.friendly, NPC.getRect(), ArmorShaderDataSet.GetSecondaryShader(), Main.gore, NPC.immune, Projectile.Kill(), Main.myPlayer, Dust.NewDust(), Gore.NewGore(), Projectile.NewProjectile(), UnifiedRandom.Next(), Dust.noGravity, NPC.noTileCollide, Main.npc, Dust.position, Main.projectile, Main.rand, Dust.scale, Dust.shader, WorldGen.SolidOrSlopedTile(), Dust.velocity, and Gore.velocity.