Terraria: Player.FindPulley
FindPulley()
void Player.FindPulley () inline
     {
         if (portableStoolInfo.IsInUse || (!controlUp && !controlDown))
         {
             return;
         }
         int num = (int)(position.X + (float)(width / 2)) / 16;
         int num2 = (int)(position.Y - 8f) / 16;
         if (!WorldGen.IsRope(num, num2))
         {
             return;
         }
         float num3 = position.Y;
         if (Main.tile[num, num2 - 1] == null)
         {
             Main.tile[num, num2 - 1] = new Tile();
         }
         if (Main.tile[num, num2 + 1] == null)
         {
             Main.tile[num, num2 + 1] = new Tile();
         }
         if ((!Main.tile[num, num2 - 1].active() || !Main.tileRope[Main.tile[num, num2 - 1].type]) && (!Main.tile[num, num2 + 1].active() || !Main.tileRope[Main.tile[num, num2 + 1].type]))
         {
             num3 = num2 * 16 + 22;
         }
         float num4 = num * 16 + 8 - width / 2 + 6 * direction;
         int num5 = num * 16 + 8 - width / 2 + 6;
         int num6 = num * 16 + 8 - width / 2;
         int num7 = num * 16 + 8 - width / 2 + -6;
         int num8 = 1;
         float num9 = Math.Abs(position.X - (float)num5);
         if (Math.Abs(position.X - (float)num6) < num9)
         {
             num8 = 2;
             num9 = Math.Abs(position.X - (float)num6);
         }
         if (Math.Abs(position.X - (float)num7) < num9)
         {
             num8 = 3;
             num9 = Math.Abs(position.X - (float)num7);
         }
         if (num8 == 1)
         {
             num4 = num5;
             pulleyDir = 2;
             direction = 1;
         }
         if (num8 == 2)
         {
             num4 = num6;
             pulleyDir = 1;
         }
         if (num8 == 3)
         {
             num4 = num7;
             pulleyDir = 2;
             direction = -1;
         }
         if (!Collision.SolidCollision(new Vector2(num4, position.Y), width, height))
         {
             if (whoAmI == Main.myPlayer)
             {
                 Main.cameraX = Main.cameraX + position.X - num4;
             }
             pulley = true;
             position.X = num4;
             gfxOffY = position.Y - num3;
             stepSpeed = 2.5f;
             position.Y = num3;
             velocity.X = 0f;
             return;
         }
         num4 = num5;
         pulleyDir = 2;
         direction = 1;
         if (!Collision.SolidCollision(new Vector2(num4, position.Y), width, height))
         {
             if (whoAmI == Main.myPlayer)
             {
                 Main.cameraX = Main.cameraX + position.X - num4;
             }
             pulley = true;
             position.X = num4;
             gfxOffY = position.Y - num3;
             stepSpeed = 2.5f;
             position.Y = num3;
             velocity.X = 0f;
             return;
         }
         num4 = num7;
         pulleyDir = 2;
         direction = -1;
         if (!Collision.SolidCollision(new Vector2(num4, position.Y), width, height))
         {
             if (whoAmI == Main.myPlayer)
             {
                 Main.cameraX = Main.cameraX + position.X - num4;
             }
             pulley = true;
             position.X = num4;
             gfxOffY = position.Y - num3;
             stepSpeed = 2.5f;
             position.Y = num3;
             velocity.X = 0f;
         }
     }
References Tile.active(), Main.cameraX, WorldGen.IsRope(), Main.myPlayer, Collision.SolidCollision(), Main.tile, Main.tileRope, and Tile.type.