Terraria: Player.Spawn
Spawn()
void Player.Spawn (PlayerSpawnContext context) inline
     {
         Main.LocalPlayer.creativeInterface = false;
         _funkytownAchievementCheckCooldown = 100;
         bool flag = false;
         if (context == PlayerSpawnContext.SpawningIntoWorld)
         {
             if (Main.netMode == 0 && unlockedBiomeTorches)
             {
                 NPC nPC = new NPC();
                 nPC.SetDefaults(664);
                 Main.BestiaryTracker.Kills.RegisterKill(nPC);
             }
             if (dead)
             {
                 AdjustRespawnTimerForWorldJoining(this);
                 if (dead)
                 {
                     flag = true;
                 }
             }
         }
         StopVanityActions();
         if (whoAmI == Main.myPlayer)
         {
             Main.NotifyOfEvent(GameNotificationType.SpawnOrDeath);
         }
         if (whoAmI == Main.myPlayer)
         {
             if (Main.mapTime < 5)
             {
                 Main.mapTime = 5;
             }
             Main.instantBGTransitionCounter = 10;
             FindSpawn();
             if (!CheckSpawn(SpawnX, SpawnY))
             {
                 SpawnX = -1;
                 SpawnY = -1;
             }
             Main.maxQ = true;
             NPC.ResetNetOffsets();
         }
         if (Main.netMode == 1 && whoAmI == Main.myPlayer)
         {
             NetMessage.SendData(12, -1, -1, null, Main.myPlayer, (int)(byte)context);
         }
         headPosition = Vector2.Zero;
         bodyPosition = Vector2.Zero;
         legPosition = Vector2.Zero;
         headRotation = 0f;
         bodyRotation = 0f;
         legRotation = 0f;
         rabbitOrderFrame.Reset();
         lavaTime = lavaMax;
         if (!flag)
         {
             if (statLife <= 0)
             {
                 int num = statLifeMax2 / 2;
                 statLife = 100;
                 if (num > statLife)
                 {
                     statLife = num;
                 }
                 breath = breathMax;
                 if (spawnMax)
                 {
                     statLife = statLifeMax2;
                     statMana = statManaMax2;
                 }
             }
             immune = true;
             dead = false;
             immuneTime = 0;
         }
         active = true;
         Vector2 value = position;
         if (SpawnX >= 0 && SpawnY >= 0)
         {
             _ = SpawnX;
             _ = SpawnY;
             Spawn_SetPosition(SpawnX, SpawnY);
         }
         else
         {
             Spawn_SetPositionAtWorldSpawn();
         }
         wet = false;
         wetCount = 0;
         lavaWet = false;
         fallStart = (int)(position.Y / 16f);
         fallStart2 = fallStart;
         velocity.X = 0f;
         velocity.Y = 0f;
         ResetAdvancedShadows();
         for (int i = 0; i < 3; i++)
         {
             UpdateSocialShadow();
         }
         oldPosition = position + BlehOldPositionFixer;
         SetTalkNPC(-1);
         if (whoAmI == Main.myPlayer)
         {
             Main.npcChatCornerItem = 0;
         }
         if (!flag)
         {
             if (pvpDeath)
             {
                 pvpDeath = false;
                 immuneTime = 300;
                 statLife = statLifeMax;
             }
             else if (context == PlayerSpawnContext.ReviveFromDeath)
             {
                 immuneTime = 180;
             }
             else
             {
                 immuneTime = 60;
             }
             if (immuneTime > 0 && !hostile)
             {
                 immuneNoBlink = true;
             }
         }
         if (whoAmI == Main.myPlayer)
         {
             bool flag2 = Vector2.Distance(value, position) < new Vector2(Main.screenWidth, Main.screenHeight).Length() / 2f + 100f;
             if (flag2)
             {
                 Main.SetCameraLerp(0.1f, 0);
                 flag2 = true;
             }
             else
             {
                 Main.BlackFadeIn = 255;
                 Lighting.Clear();
                 Main.screenLastPosition = Main.screenPosition;
                 Main.instantBGTransitionCounter = 10;
             }
             if (!flag2)
             {
                 Main.renderNow = true;
             }
             if (Main.netMode == 1)
             {
                 Netplay.AddCurrentServerToRecentList();
             }
             if (true && !flag2)
             {
                 Main.screenPosition.X = position.X + (float)(width / 2) - (float)(Main.screenWidth / 2);
                 Main.screenPosition.Y = position.Y + (float)(height / 2) - (float)(Main.screenHeight / 2);
                 ForceUpdateBiomes();
             }
         }
         if (flag)
         {
             immuneAlpha = 255;
         }
         UpdateGraveyard(now: true);
         if (whoAmI == Main.myPlayer && context == PlayerSpawnContext.ReviveFromDeath && difficulty == 3)
         {
             AutoFinchStaff();
         }
         if (whoAmI == Main.myPlayer && context == PlayerSpawnContext.SpawningIntoWorld)
         {
             Main.ReleaseHostAndPlayProcess();
             RefreshItems();
             SetPlayerDataToOutOfClassFields();
             Main.LocalGolfState.SetScoreTime();
             Main.ActivePlayerFileData.StartPlayTimer();
             Hooks.EnterWorld(whoAmI);
         }
     }
References Main.ActivePlayerFileData, Netplay.AddCurrentServerToRecentList(), Main.BestiaryTracker, Main.BlackFadeIn, Lighting.Clear(), creativeInterface, Player.Hooks.EnterWorld(), Main.instantBGTransitionCounter, BestiaryUnlocksTracker.Kills, Main.LocalGolfState, Main.LocalPlayer, Main.mapTime, Main.maxQ, Main.myPlayer, Main.netMode, Main.NotifyOfEvent(), Main.npcChatCornerItem, NPCKillsTracker.RegisterKill(), Main.ReleaseHostAndPlayProcess(), Main.renderNow, NPC.ResetNetOffsets(), Main.screenHeight, Main.screenLastPosition, Main.screenPosition, Main.screenWidth, NetMessage.SendData(), Main.SetCameraLerp(), NPC.SetDefaults(), GolfState.SetScoreTime(), and PlayerFileData.StartPlayTimer().
Referenced by MessageBuffer.GetData(), Main.Initialize_AlmostEverything(), and WorldGen.playWorldCallBack().