Terraria: Player.PlaceThing_ValidTileForReplacement
PlaceThing_ValidTileForReplacement()
bool Player.PlaceThing_ValidTileForReplacement () inline private
     {
         int createTile = HeldItem.createTile;
         int num = HeldItem.placeStyle;
         if (UsingBiomeTorches && createTile == 4)
         {
             num = BiomeTorchPlaceStyle(num);
         }
         if (UsingBiomeTorches && createTile == 215)
         {
             num = BiomeCampfirePlaceStyle(num);
         }
         Tile tile = Main.tile[tileTargetX, tileTargetY];
         if (WorldGen.WouldTileReplacementBeBlockedByLiquid(tileTargetX, tileTargetY, 1))
         {
             return false;
         }
         if (ItemID.Sets.SortingPriorityRopes[HeldItem.type] != -1)
         {
             return false;
         }
         if (Main.tileMoss[createTile])
         {
             return false;
         }
         if (TileID.Sets.DoesntPlaceWithTileReplacement[createTile])
         {
             return false;
         }
         if (TileID.Sets.DoesntGetReplacedWithTileReplacement[tile.type])
         {
             return false;
         }
         if (!PlaceThing_CheckSpecificValidtyCaseForBlockSwap(createTile, tile.type))
         {
             return false;
         }
         if (Main.tileCut[tile.type])
         {
             return false;
         }
         if (TileID.Sets.Platforms[tile.type] && tile.type == createTile)
         {
             return tile.frameY != num * 18;
         }
         if (tile.type == 4 && tile.type == createTile)
         {
             return tile.frameY != num * 22;
         }
         if (tile.type == 215 && tile.type == createTile)
         {
             return tile.frameX / 54 != num;
         }
         if (TileID.Sets.BasicChest[tile.type] && TileID.Sets.BasicChest[createTile])
         {
             if (tile.frameX / 36 == num)
             {
                 return tile.type != createTile;
             }
             return true;
         }
         if (TileID.Sets.BasicDresser[tile.type] && TileID.Sets.BasicDresser[createTile])
         {
             if (tile.frameX / 54 == num)
             {
                 return tile.type != createTile;
             }
             return true;
         }
         bool flag = false;
         if (Main.tileRope[tile.type])
         {
             if (createTile != 314 && !TileID.Sets.Platforms[createTile])
             {
                 return false;
             }
             flag = true;
         }
         if (!flag && Main.tileFrameImportant[createTile] && !TileID.Sets.Platforms[createTile])
         {
             return false;
         }
         if (Main.tile[tileTargetX, tileTargetY].type == createTile)
         {
             return false;
         }
         if (Main.tile[tileTargetX, tileTargetY].type == 230 && Main.getGoodWorld)
         {
             return false;
         }
         if (!TileID.Sets.IgnoresTileReplacementDropCheckWhenBeingPlaced[createTile])
         {
             WorldGen.KillTile_GetItemDrops(tileTargetX, tileTargetY, tile, out var dropItem, out var _, out var _, out var _);
             if (dropItem == HeldItem.type)
             {
                 return false;
             }
         }
         if (!WorldGen.WouldTileReplacementWork((ushort)createTile, tileTargetX, tileTargetY))
         {
             return false;
         }
         return true;
     }
References TileID.Sets.BasicChest, TileID.Sets.BasicDresser, Item.createTile, TileID.Sets.DoesntGetReplacedWithTileReplacement, TileID.Sets.DoesntPlaceWithTileReplacement, Tile.frameX, Tile.frameY, Main.getGoodWorld, TileID.Sets.IgnoresTileReplacementDropCheckWhenBeingPlaced, WorldGen.KillTile_GetItemDrops(), Item.placeStyle, TileID.Sets.Platforms, ItemID.Sets.SortingPriorityRopes, Main.tile, Main.tileCut, Main.tileFrameImportant, Main.tileMoss, Main.tileRope, Item.type, Tile.type, WorldGen.WouldTileReplacementBeBlockedByLiquid(), and WorldGen.WouldTileReplacementWork().