Terraria: Player.ItemCheck_UseMiningTools_TryPoundingTile
ItemCheck_UseMiningTools_TryPoundingTile()
void Player.ItemCheck_UseMiningTools_TryPoundingTile (Item sItem, int tileHitId, ref bool hitWall, int x, int y) inline private
     {
         Tile tile = Main.tile[x, y];
         if (sItem.hammer > 0 && tile.active() && (Main.tileSolid[tile.type] || tile.type == 314 || tile.type == 351 || tile.type == 424 || tile.type == 442) && poundRelease)
         {
             hitWall = false;
             ApplyItemTime(sItem);
             int damageAmount = 100;
             if (WorldGen.IsLockedDoor(x, y - 1) || WorldGen.IsLockedDoor(x, y + 1))
             {
                 damageAmount = 0;
             }
             if (hitTile.AddDamage(tileHitId, damageAmount) >= 100)
             {
                 ClearMiningCacheAt(x, y, 1);
                 if (!poundRelease)
                 {
                     return;
                 }
                 if (TileID.Sets.Platforms[Main.tile[x, y].type])
                 {
                     if (tile.halfBrick())
                     {
                         WorldGen.PoundTile(x, y);
                         if (Main.netMode == 1)
{
                             NetMessage.SendData(17, -1, -1, null, 7, x, y, 1f);
                         }
                     }
                     else
                     {
                         int num = 1;
                         int slope = 2;
                         if (TileID.Sets.Platforms[Main.tile[x + 1, y - 1].type] || TileID.Sets.Platforms[Main.tile[x - 1, y + 1].type] || (WorldGen.SolidTile(x + 1, y) && !WorldGen.SolidTile(x - 1, y)))
{
                             num = 2;
                             slope = 1;
                         }
                         if (Main.tile[x, y].slope() == 0)
{
                             WorldGen.SlopeTile(x, y, num);
                             int num2 = Main.tile[x, y].slope();
                             if (Main.netMode == 1)
{
                                 NetMessage.SendData(17, -1, -1, null, 14, x, y, num2);
                             }
                         }
                         else if (Main.tile[x, y].slope() == num)
{
                             WorldGen.SlopeTile(x, y, slope);
                             int num3 = Main.tile[x, y].slope();
                             if (Main.netMode == 1)
{
                                 NetMessage.SendData(17, -1, -1, null, 14, x, y, num3);
                             }
                         }
                         else
{
                             WorldGen.SlopeTile(x, y);
                             int num4 = Main.tile[x, y].slope();
                             if (Main.netMode == 1)
{
                                 NetMessage.SendData(17, -1, -1, null, 14, x, y, num4);
                             }
                             WorldGen.PoundTile(x, y);
                             if (Main.netMode == 1)
{
                                 NetMessage.SendData(17, -1, -1, null, 7, x, y, 1f);
                             }
                         }
                     }
                 }
                 else if (Main.tile[x, y].type == 314)
                 {
                     if (Minecart.FrameTrack(x, y, pound: true) && Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 15, x, y, 1f);
                     }
                 }
                 else if (Main.tile[x, y].type == 137)
                 {
                     int num5 = 0;
                     switch (Main.tile[x, y].frameY / 18)
                     {
                     case 0:
                     case 1:
                     case 2:
                     case 5:
                         switch (Main.tile[x, y].frameX / 18)
{
                         case 0:
                             num5 = 2;
                             break;
                         case 1:
                             num5 = 3;
                             break;
                         case 2:
                             num5 = 4;
                             break;
                         case 3:
                             num5 = 5;
                             break;
                         case 4:
                             num5 = 1;
                             break;
                         case 5:
                             num5 = 0;
                             break;
                         }
                         break;
                     case 3:
                     case 4:
                         switch (Main.tile[x, y].frameX / 18)
{
                         case 0:
                         case 1:
                             num5 = 3;
                             break;
                         case 3:
                             num5 = 2;
                             break;
                         case 2:
                             num5 = 4;
                             break;
                         case 4:
                             num5 = 0;
                             break;
                         }
                         break;
                     }
                     Main.tile[x, y].frameX = (short)(num5 * 18);
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendTileSquare(-1, x, y);
                     }
                 }
                 else if (Main.tile[x, y].type == 424)
                 {
                     if (Main.tile[x, y].frameX == 0)
                     {
                         Main.tile[x, y].frameX = 18;
                     }
                     else if (Main.tile[x, y].frameX == 18)
                     {
                         Main.tile[x, y].frameX = 36;
                     }
                     else
                     {
                         Main.tile[x, y].frameX = 0;
                     }
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendTileSquare(-1, x, y);
                     }
                 }
                 else if (Main.tile[x, y].type == 442)
                 {
                     Tile tile2 = Main.tile[x, y - 1];
                     Tile tile3 = Main.tile[x, y + 1];
                     Tile tile4 = Main.tile[x - 1, y];
                     Tile tile5 = Main.tile[x + 1, y];
                     Tile tile6 = Main.tile[x - 1, y + 1];
                     Tile tile7 = Main.tile[x + 1, y + 1];
                     Tile tile8 = Main.tile[x - 1, y - 1];
                     Tile tile9 = Main.tile[x + 1, y - 1];
                     int num6 = -1;
                     int num7 = -1;
                     int num8 = -1;
                     int num9 = -1;
                     int tree = -1;
                     int tree2 = -1;
                     int tree3 = -1;
                     int tree4 = -1;
                     if (tile2 != null && tile2.nactive() && !tile2.bottomSlope())
                     {
                         num7 = tile2.type;
                     }
                     if (tile3 != null && tile3.nactive() && !tile3.halfBrick() && !tile3.topSlope())
                     {
                         num6 = tile3.type;
                     }
                     if (tile4 != null && tile4.nactive() && (tile4.slope() == 0 || tile4.slope() % 2 != 1))
                     {
                         num8 = tile4.type;
                     }
                     if (tile5 != null && tile5.nactive() && (tile5.slope() == 0 || tile5.slope() % 2 != 0))
                     {
                         num9 = tile5.type;
                     }
                     if (tile6 != null && tile6.nactive())
                     {
                         tree = tile6.type;
                     }
                     if (tile7 != null && tile7.nactive())
                     {
                         tree2 = tile7.type;
                     }
                     if (tile8 != null && tile8.nactive())
                     {
                         tree3 = tile8.type;
                     }
                     if (tile9 != null && tile9.nactive())
                     {
                         tree4 = tile9.type;
                     }
                     bool flag = false;
                     bool flag2 = false;
                     bool flag3 = false;
                     bool flag4 = false;
                     if (num6 >= 0 && Main.tileSolid[num6] && (!Main.tileNoAttach[num6] || TileID.Sets.Platforms[num6]) && (tile3.bottomSlope() || tile3.slope() == 0) && !tile3.halfBrick())
                     {
                         flag4 = true;
                     }
                     if (num7 >= 0 && Main.tileSolid[num7] && (!Main.tileNoAttach[num7] || (TileID.Sets.Platforms[num7] && tile2.halfBrick())) && (tile2.topSlope() || tile2.slope() == 0 || tile2.halfBrick()))
                     {
                         flag = true;
                     }
                     if ((num8 >= 0 && Main.tileSolid[num8] && !Main.tileNoAttach[num8] && (tile4.leftSlope() || tile4.slope() == 0) && !tile4.halfBrick()) || (num8 >= 0 && TileID.Sets.IsBeam[num8]) || (WorldGen.IsTreeType(num8) && WorldGen.IsTreeType(tree3) && WorldGen.IsTreeType(tree)))
                     {
                         flag2 = true;
                     }
                     if ((num9 >= 0 && Main.tileSolid[num9] && !Main.tileNoAttach[num9] && (tile5.rightSlope() || tile5.slope() == 0) && !tile5.halfBrick()) || (num9 >= 0 && TileID.Sets.IsBeam[num9]) || (WorldGen.IsTreeType(num9) && WorldGen.IsTreeType(tree4) && WorldGen.IsTreeType(tree2)))
                     {
                         flag3 = true;
                     }
                     int num10 = Main.tile[x, y].frameX / 22;
                     short num11 = -2;
                     switch (num10)
                     {
                     case 0:
                         num11 = (short)((!flag2) ? (flag ? 1 : ((!flag3) ? (-1) : 3)) : 2);
                         break;
                     case 2:
                         num11 = (short)(flag ? 1 : ((!flag3) ? ((!flag4) ? (-1) : 0) : 3));
                         break;
                     case 1:
                         num11 = (short)((!flag3) ? ((!flag4) ? ((!flag2) ? (-1) : 2) : 0) : 3);
                         break;
                     case 3:
                         num11 = (short)((!flag4) ? ((!flag2) ? (flag ? 1 : (-1)) : 2) : 0);
                         break;
                     }
                     if (num11 != -1)
                     {
                         if (num11 == -2)
{
                             num11 = 0;
                         }
                         Main.tile[x, y].frameX = (short)(22 * num11);
                         if (Main.netMode == 1)
{
                             NetMessage.SendTileSquare(-1, x, y);
                         }
                     }
                 }
                 else if ((Main.tile[x, y].halfBrick() || Main.tile[x, y].slope() != 0) && !Main.tileSolidTop[Main.tile[x, y].type])
                 {
                     int num12 = 1;
                     int num13 = 1;
                     int num14 = 2;
                     if ((WorldGen.SolidTile(x + 1, y) || Main.tile[x + 1, y].slope() == 1 || Main.tile[x + 1, y].slope() == 3) && !WorldGen.SolidTile(x - 1, y))
                     {
                         num13 = 2;
                         num14 = 1;
                     }
                     if (WorldGen.SolidTile(x, y - 1) && !WorldGen.SolidTile(x, y + 1))
                     {
                         num12 = -1;
                     }
                     if (num12 == 1)
                     {
                         if (Main.tile[x, y].slope() == 0)
{
                             WorldGen.SlopeTile(x, y, num13);
                         }
                         else if (Main.tile[x, y].slope() == num13)
{
                             WorldGen.SlopeTile(x, y, num14);
                         }
                         else if (Main.tile[x, y].slope() == num14)
{
                             WorldGen.SlopeTile(x, y, num13 + 2);
                         }
                         else if (Main.tile[x, y].slope() == num13 + 2)
{
                             WorldGen.SlopeTile(x, y, num14 + 2);
                         }
                         else
{
                             WorldGen.SlopeTile(x, y);
                         }
                     }
                     else if (Main.tile[x, y].slope() == 0)
                     {
                         WorldGen.SlopeTile(x, y, num13 + 2);
                     }
                     else if (Main.tile[x, y].slope() == num13 + 2)
                     {
                         WorldGen.SlopeTile(x, y, num14 + 2);
                     }
                     else if (Main.tile[x, y].slope() == num14 + 2)
                     {
                         WorldGen.SlopeTile(x, y, num13);
                     }
                     else if (Main.tile[x, y].slope() == num13)
                     {
                         WorldGen.SlopeTile(x, y, num14);
                     }
                     else
                     {
                         WorldGen.SlopeTile(x, y);
                     }
                     int num15 = Main.tile[x, y].slope();
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 14, x, y, num15);
                     }
                 }
                 else
                 {
                     WorldGen.PoundTile(x, y);
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 7, x, y, 1f);
                     }
                 }
                 poundRelease = false;
             }
             else
             {
                 WorldGen.KillTile(x, y, fail: true, effectOnly: true);
                 SoundEngine.PlaySound(0, x * 16, y * 16);
             }
         }
         else
         {
             poundRelease = false;
         }
     }
References Tile.active(), Tile.bottomSlope(), Minecart.FrameTrack(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Item.hammer, TileID.Sets.IsBeam, WorldGen.IsLockedDoor(), WorldGen.IsTreeType(), WorldGen.KillTile(), Tile.leftSlope(), Tile.nactive(), Main.netMode, TileID.Sets.Platforms, SoundEngine.PlaySound(), WorldGen.PoundTile(), Tile.rightSlope(), NetMessage.SendData(), NetMessage.SendTileSquare(), Tile.slope(), WorldGen.SlopeTile(), WorldGen.SolidTile(), Main.tile, Main.tileNoAttach, Main.tileSolid, Main.tileSolidTop, Tile.topSlope(), and Tile.type.