Terraria: Player.DoBootsEffect_PlaceFlowersOnTile
DoBootsEffect_PlaceFlowersOnTile()
bool Player.DoBootsEffect_PlaceFlowersOnTile (int X, int Y) inline
     {
         Tile tile = Main.tile[X, Y];
         if (tile == null)
         {
             return false;
         }
         if (!tile.active() && tile.liquid == 0 && Main.tile[X, Y + 1] != null && WorldGen.SolidTile(X, Y + 1))
         {
             tile.frameY = 0;
             tile.slope(0);
             tile.halfBrick(halfBrick: false);
             if (Main.tile[X, Y + 1].type == 2 || Main.tile[X, Y + 1].type == 477)
             {
                 int num = Main.rand.NextFromList<int>(6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 24, 27, 30, 33, 36, 39, 42);
                 switch (num)
                 {
                 case 21:
                 case 24:
                 case 27:
                 case 30:
                 case 33:
                 case 36:
                 case 39:
                 case 42:
                     num += Main.rand.Next(3);
                     break;
                 }
                 tile.active(active: true);
                 tile.type = 3;
                 tile.frameX = (short)(num * 18);
                 tile.CopyPaintAndCoating(Main.tile[X, Y + 1]);
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendTileSquare(-1, X, Y);
                 }
                 return true;
             }
             if (Main.tile[X, Y + 1].type == 109 || Main.tile[X, Y + 1].type == 492)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     tile.active(active: true);
                     tile.type = 110;
                     tile.frameX = (short)(18 * Main.rand.Next(4, 7));
                     tile.CopyPaintAndCoating(Main.tile[X, Y + 1]);
                     while (tile.frameX == 90)
                     {
                         tile.frameX = (short)(18 * Main.rand.Next(4, 7));
                     }
                 }
                 else
                 {
                     tile.active(active: true);
                     tile.type = 113;
                     tile.frameX = (short)(18 * Main.rand.Next(2, 8));
                     tile.CopyPaintAndCoating(Main.tile[X, Y + 1]);
                     while (tile.frameX == 90)
                     {
                         tile.frameX = (short)(18 * Main.rand.Next(2, 8));
                     }
                 }
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendTileSquare(-1, X, Y);
                 }
                 return true;
             }
             if (Main.tile[X, Y + 1].type == 60)
             {
                 tile.active(active: true);
                 tile.type = 74;
                 tile.frameX = (short)(18 * Main.rand.Next(9, 17));
                 tile.CopyPaintAndCoating(Main.tile[X, Y + 1]);
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendTileSquare(-1, X, Y);
                 }
                 return true;
             }
             if (Main.tile[X, Y + 1].type == 633)
             {
                 tile.active(active: true);
                 tile.type = 637;
                 tile.frameX = (short)(18 * Main.rand.Next(6, 11));
                 tile.CopyPaintAndCoating(Main.tile[X, Y + 1]);
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendTileSquare(-1, X, Y);
                 }
                 return true;
             }
         }
         return false;
     }
References Tile.active(), Tile.CopyPaintAndCoating(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.liquid, Main.netMode, UnifiedRandom.Next(), Main.rand, NetMessage.SendTileSquare(), Tile.slope(), WorldGen.SolidTile(), Main.tile, Tile.type, X, and Y.