Terraria: Player.WallslideMovement
WallslideMovement()
void Player.WallslideMovement () inline
     {
         sliding = false;
         if (slideDir == 0 || spikedBoots <= 0 || mount.Active || ((!controlLeft || slideDir != -1) && (!controlRight || slideDir != 1)))
         {
             return;
         }
         bool flag = false;
         float num = position.X;
         if (slideDir == 1)
         {
             num += (float)width;
         }
         num += (float)slideDir;
         float num2 = position.Y + (float)height + 1f;
         if (gravDir < 0f)
         {
             num2 = position.Y - 1f;
         }
         num /= 16f;
         num2 /= 16f;
         if (WorldGen.SolidTile((int)num, (int)num2) && WorldGen.SolidTile((int)num, (int)num2 - 1))
         {
             flag = true;
         }
         if (spikedBoots >= 2)
         {
             if (!flag || ((!(velocity.Y > 0f) || gravDir != 1f) && (!(velocity.Y < gravity) || gravDir != -1f)))
             {
                 return;
             }
             float num3 = gravity;
             if (slowFall)
             {
                 num3 = ((!TryingToHoverUp) ? (gravity / 3f * gravDir) : (gravity / 10f * gravDir));
             }
             fallStart = (int)(position.Y / 16f);
             if ((controlDown && gravDir == 1f) || (controlUp && gravDir == -1f))
             {
                 velocity.Y = 4f * gravDir;
                 int num4 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)((width / 2 - 4) * slideDir), position.Y + (float)(height / 2) + (float)(height / 2 - 4) * gravDir), 8, 8, 31);
                 if (slideDir < 0)
                 {
                     Main.dust[num4].position.X -= 10f;
                 }
                 if (gravDir < 0f)
                 {
                     Main.dust[num4].position.Y -= 12f;
                 }
                 Main.dust[num4].velocity *= 0.1f;
                 Main.dust[num4].scale *= 1.2f;
                 Main.dust[num4].noGravity = true;
                 Main.dust[num4].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
             }
             else if (gravDir == -1f)
             {
                 velocity.Y = (0f - num3 + 1E-05f) * gravDir;
             }
             else
             {
                 velocity.Y = (0f - num3 + 1E-05f) * gravDir;
             }
             sliding = true;
         }
         else if ((flag && (double)velocity.Y > 0.5 && gravDir == 1f) || ((double)velocity.Y < -0.5 && gravDir == -1f))
         {
             fallStart = (int)(position.Y / 16f);
             if (controlDown)
             {
                 velocity.Y = 4f * gravDir;
             }
             else
             {
                 velocity.Y = 0.5f * gravDir;
             }
             sliding = true;
             int num5 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)((width / 2 - 4) * slideDir), position.Y + (float)(height / 2) + (float)(height / 2 - 4) * gravDir), 8, 8, 31);
             if (slideDir < 0)
             {
                 Main.dust[num5].position.X -= 10f;
             }
             if (gravDir < 0f)
             {
                 Main.dust[num5].position.Y -= 12f;
             }
             Main.dust[num5].velocity *= 0.1f;
             Main.dust[num5].scale *= 1.2f;
             Main.dust[num5].noGravity = true;
             Main.dust[num5].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
         }
     }
References GameShaders.Armor, Main.dust, E, ArmorShaderDataSet.GetSecondaryShader(), Dust.NewDust(), Dust.noGravity, Dust.position, Dust.scale, Dust.shader, WorldGen.SolidTile(), and Dust.velocity.