Terraria: Player.PlaceWeapon
PlaceWeapon()
void Player.PlaceWeapon (int x, int y) inline
     {
         if (Main.tile[x, y].active() && Main.tile[x, y].type == 334)
         {
             int frameY = Main.tile[x, y].frameY;
             int num = 1;
             frameY /= 18;
             while (num > frameY)
             {
                 y++;
                 frameY = Main.tile[x, y].frameY;
                 frameY /= 18;
             }
             while (num < frameY)
             {
                 y--;
                 frameY = Main.tile[x, y].frameY;
                 frameY /= 18;
             }
             int num2 = Main.tile[x, y].frameX;
             int num3 = 0;
             while (num2 >= 5000)
             {
                 num2 -= 5000;
                 num3++;
             }
             if (num3 != 0)
             {
                 num2 = (num3 - 1) * 18;
             }
             bool flag = false;
             if (num2 >= 54)
             {
                 num2 -= 54;
                 flag = true;
             }
             x -= num2 / 18;
             int num4 = Main.tile[x, y].frameX;
             WorldGen.KillTile(x, y, fail: true);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, x, y, 1f);
             }
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, x + 1, y, 1f);
             }
             while (num4 >= 5000)
             {
                 num4 -= 5000;
             }
             Main.blockMouse = true;
             int num5 = 5000;
             int num6 = 10000;
             if (flag)
             {
                 num5 = 20000;
                 num6 = 25000;
             }
             Main.tile[x, y].frameX = (short)(inventory[selectedItem].netID + num5 + 100);
             Main.tile[x + 1, y].frameX = (short)(inventory[selectedItem].prefix + num6);
             if (Main.netMode == 1)
             {
                 NetMessage.SendTileSquare(-1, x, y);
             }
             if (Main.netMode == 1)
             {
                 NetMessage.SendTileSquare(-1, x + 1, y);
             }
             inventory[selectedItem].stack--;
             if (inventory[selectedItem].stack <= 0)
             {
                 inventory[selectedItem].SetDefaults();
                 Main.mouseItem.SetDefaults();
             }
             if (selectedItem == 58)
             {
                 Main.mouseItem = inventory[selectedItem].Clone();
             }
             releaseUseItem = false;
             mouseInterface = true;
         }
     }
References Tile.active(), Main.blockMouse, Item.Clone(), Tile.frameX, Tile.frameY, WorldGen.KillTile(), Main.mouseItem, Main.netMode, NetMessage.SendData(), NetMessage.SendTileSquare(), Item.SetDefaults(), Main.tile, and Tile.type.