Terraria: Player.GetHurtTile
GetHurtTile()
Collision.HurtTile Player.GetHurtTile () inline private
     {
         Collision.HurtTile result = Collision.HurtTiles(position, width, (!mount.Active || !mount.Cart) ? height : (height - 16), this);
         if (result.type >= 0)
         {
             return result;
         }
         foreach (Point touchedTile in TouchedTiles)
         {
             Tile tile = Main.tile[touchedTile.X, touchedTile.Y];
             if (tile != null && tile.active() && tile.nactive() && !TileID.Sets.Suffocate[tile.type] && Collision.CanTileHurt(tile.type, touchedTile.X, touchedTile.Y, this))
             {
                 Collision.HurtTile result2 = default(Collision.HurtTile);
                 result2.type = tile.type;
                 result2.x = touchedTile.X;
                 result2.y = touchedTile.Y;
                 return result2;
             }
         }
         return result;
     }
References Tile.active(), Collision.CanTileHurt(), Collision.HurtTiles(), Tile.nactive(), TileID.Sets.Suffocate, Main.tile, Collision.HurtTile.type, and Tile.type.