Terraria: Player.GetTileCutIgnorance
GetTileCutIgnorance()
bool [] Player.GetTileCutIgnorance (bool allowRegrowth, bool fromTrap) inline
     {
         bool[] result = TileID.Sets.TileCutIgnore.None;
         if (allowRegrowth)
         {
             result = TileID.Sets.TileCutIgnore.Regrowth;
         }
         if (!fromTrap && dontHurtNature)
         {
             result = TileID.Sets.TileCutIgnore.IgnoreDontHurtNature;
         }
         return result;
     }
References TileID.Sets.TileCutIgnore.IgnoreDontHurtNature, TileID.Sets.TileCutIgnore.None, and TileID.Sets.TileCutIgnore.Regrowth.
Referenced by Projectile.CutTiles(), Projectile.CutTilesAt(), and Projectile.HandleMovement().