Terraria: Player.Counterweight
Counterweight()
void Player.Counterweight (Vector2 hitPos, int dmg, float kb) inline
     {
         if (!yoyoGlove && counterWeight <= 0)
         {
             return;
         }
         int num = -1;
         int num2 = 0;
         int num3 = 0;
         for (int i = 0; i < 1000; i++)
         {
             if (Main.projectile[i].active && Main.projectile[i].owner == whoAmI)
             {
                 if (Main.projectile[i].counterweight)
                 {
                     num3++;
                 }
                 else if (Main.projectile[i].aiStyle == 99)
                 {
                     num2++;
                     num = i;
                 }
             }
         }
         if (yoyoGlove && num2 < 2)
         {
             if (num >= 0)
             {
                 Vector2 vector = hitPos - base.Center;
                 vector.Normalize();
                 vector *= 16f;
                 Projectile.NewProjectile(Projectile.InheritSource(Main.projectile[num]), base.Center.X, base.Center.Y, vector.X, vector.Y, Main.projectile[num].type, Main.projectile[num].damage, Main.projectile[num].knockBack, whoAmI, 1f);
             }
         }
         else if (num3 < num2)
         {
             Vector2 vector2 = hitPos - base.Center;
             vector2.Normalize();
             vector2 *= 16f;
             float knockBack = (kb + 6f) / 2f;
             IEntitySource spawnSource = Projectile.InheritSource(Main.projectile[num]);
             if (num3 > 0)
             {
                 Projectile.NewProjectile(spawnSource, base.Center.X, base.Center.Y, vector2.X, vector2.Y, counterWeight, (int)((double)dmg * 0.8), knockBack, whoAmI, 1f);
             }
             else
             {
                 Projectile.NewProjectile(spawnSource, base.Center.X, base.Center.Y, vector2.X, vector2.Y, counterWeight, (int)((double)dmg * 0.8), knockBack, whoAmI);
             }
         }
     }
References Entity.active, Projectile.aiStyle, Projectile.counterweight, Projectile.damage, Projectile.InheritSource(), Projectile.knockBack, Projectile.NewProjectile(), Projectile.owner, Main.projectile, and Projectile.type.
Referenced by Projectile.Damage().