Terraria: System.Diagnostics.Tracing.ScalarArrayTypeInfo.ScalarArrayTypeInfo
ScalarArrayTypeInfo()
System.Diagnostics.Tracing.ScalarArrayTypeInfo.ScalarArrayTypeInfo (Type type, TraceLoggingDataType nativeFormat, int elementSize) inline private
Definition at line 39 of file ScalarArrayTypeInfo.cs.
        : base(type)
    {
        this.nativeFormat = nativeFormat;
        this.elementSize = elementSize;
    }
References System.Diagnostics.Tracing.ScalarArrayTypeInfo.elementSize, and System.Diagnostics.Tracing.ScalarArrayTypeInfo.nativeFormat.
Referenced by System.Diagnostics.Tracing.ScalarArrayTypeInfo.Boolean(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Byte(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Char(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Double(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Guid(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Int16(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Int32(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Int64(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.IntPtr(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.SByte(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Single(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.UInt16(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.UInt32(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.UInt64(), and System.Diagnostics.Tracing.ScalarArrayTypeInfo.UIntPtr().