Terraria: Terraria.GameContent.Skies.AmbientSky.Spawn
Spawn()
void Terraria.GameContent.Skies.AmbientSky.Spawn (Player player, SkyEntityType type, int seed) inline
Definition at line 1423 of file AmbientSky.cs.
    {
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        FastRandom random = new FastRandom(seed);
        switch (type)
        {
        case SkyEntityType.AirBalloon:
            _entities.Add((SkyEntity)new AirBalloonSkyEntity(player, random));
            break;
        case SkyEntityType.Airship:
            _entities.Add((SkyEntity)new AirshipSkyEntity(player, random));
            break;
        case SkyEntityType.BirdsV:
            _entities.Add((SkyEntity)new BirdsPackSkyEntity(player, random));
            break;
        case SkyEntityType.Eyeball:
            _entities.Add((SkyEntity)new EOCSkyEntity(player, random));
            break;
        case SkyEntityType.Meteor:
            _entities.Add((SkyEntity)new MeteorSkyEntity(player, random));
            break;
        case SkyEntityType.Wyvern:
            _entities.Add((SkyEntity)new WyvernSkyEntity(player, random));
            break;
        case SkyEntityType.Bats:
        {
            List<BatsGroupSkyEntity> list5 = BatsGroupSkyEntity.CreateGroup(player, random);
            for (int m = 0; m < list5.Count; m++)
            {
                _entities.Add((SkyEntity)list5[m]);
            }
            break;
        }
        case SkyEntityType.Butterflies:
            _entities.Add((SkyEntity)new ButterfliesSkyEntity(player, random));
            break;
        case SkyEntityType.LostKite:
            _entities.Add((SkyEntity)new LostKiteSkyEntity(player, random));
            break;
        case SkyEntityType.Vulture:
            _entities.Add((SkyEntity)new VultureSkyEntity(player, random));
            break;
        case SkyEntityType.PixiePosse:
            _entities.Add((SkyEntity)new PixiePosseSkyEntity(player, random));
            break;
        case SkyEntityType.Seagulls:
        {
            List<SeagullsGroupSkyEntity> list4 = SeagullsGroupSkyEntity.CreateGroup(player, random);
            for (int l = 0; l < list4.Count; l++)
            {
                _entities.Add((SkyEntity)list4[l]);
            }
            break;
        }
        case SkyEntityType.SlimeBalloons:
        {
            List<SlimeBalloonGroupSkyEntity> list3 = SlimeBalloonGroupSkyEntity.CreateGroup(player, random);
            for (int k = 0; k < list3.Count; k++)
            {
                _entities.Add((SkyEntity)list3[k]);
            }
            break;
        }
        case SkyEntityType.Gastropods:
        {
            List<GastropodGroupSkyEntity> list2 = GastropodGroupSkyEntity.CreateGroup(player, random);
            for (int j = 0; j < list2.Count; j++)
            {
                _entities.Add((SkyEntity)list2[j]);
            }
            break;
        }
        case SkyEntityType.Pegasus:
            _entities.Add((SkyEntity)new PegasusSkyEntity(player, random));
            break;
        case SkyEntityType.EaterOfSouls:
            _entities.Add((SkyEntity)new EOSSkyEntity(player, random));
            break;
        case SkyEntityType.Crimera:
            _entities.Add((SkyEntity)new CrimeraSkyEntity(player, random));
            break;
        case SkyEntityType.Hellbats:
        {
            List<HellBatsGoupSkyEntity> list = HellBatsGoupSkyEntity.CreateGroup(player, random);
            for (int i = 0; i < list.Count; i++)
            {
                _entities.Add((SkyEntity)list[i]);
            }
            break;
        }
        }
        if (Main.netMode != 2 && !AnActiveSkyConflictsWithAmbience() && !SkyManager.Instance["Ambience"].IsActive())
        {
            SkyManager.Instance.Activate("Ambience", default(Vector2));
        }
    }
References Terraria.GameContent.Skies.AmbientSky._entities, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.GameContent.Skies.AmbientSky.AnActiveSkyConflictsWithAmbience(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.GameContent.Skies.AmbientSky.SeagullsGroupSkyEntity.CreateGroup(), Terraria.GameContent.Skies.AmbientSky.GastropodGroupSkyEntity.CreateGroup(), Terraria.GameContent.Skies.AmbientSky.SlimeBalloonGroupSkyEntity.CreateGroup(), Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.CreateGroup(), Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.CreateGroup(), Terraria.Graphics.Effects.SkyManager.Instance, System.list, Terraria.Main.netMode, and System.type.