Terraria: Terraria.GameContent.Skies.AmbientSky.Update
Update()
override void Terraria.GameContent.Skies.AmbientSky.Update (GameTime gameTime) inline
Definition at line 1369 of file AmbientSky.cs.
    {
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        if (Main.gamePaused)
        {
            return;
        }
        _frameCounter++;
        if (Main.netMode != 2 && AnActiveSkyConflictsWithAmbience() && SkyManager.Instance["Ambience"].IsActive())
        {
            SkyManager.Instance.Deactivate("Ambience");
        }
        foreach (ItemPair<SkyEntity> item in (IEnumerable<ItemPair<SkyEntity>>)_entities)
        {
            SkyEntity value = item.Value;
            value.Update(_frameCounter);
            if (!value.IsActive)
            {
                _entities.Remove(item.Id);
                if (Main.netMode != 2 && _entities.Count == 0 && SkyManager.Instance["Ambience"].IsActive())
                {
                    SkyManager.Instance.Deactivate("Ambience");
                }
            }
        }
    }
References Terraria.GameContent.Skies.AmbientSky._entities, Terraria.GameContent.Skies.AmbientSky._frameCounter, Terraria.GameContent.Skies.AmbientSky.AnActiveSkyConflictsWithAmbience(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.Main.gamePaused, Terraria.Graphics.Effects.SkyManager.Instance, System.item, Terraria.Main.netMode, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.Update(), and System.value.