Terraria: System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteXmlnsAttribute
WriteXmlnsAttribute() [1/3]
override void System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteXmlnsAttribute (string prefix, string namespaceUri) inline
Definition at line 220 of file XmlDictionaryWriter.cs.
        {
            if (namespaceUri == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("namespaceUri");
            }
            if (prefix == null)
            {
                if (LookupPrefix(namespaceUri) != null)
                {
                    return;
                }
                if (namespaceUri.Length == 0)
                {
                    prefix = string.Empty;
                }
                else
                {
                    string text = _depth.ToString(NumberFormatInfo.InvariantInfo);
                    string text2 = _prefix.ToString(NumberFormatInfo.InvariantInfo);
                    prefix = "d" + text + "p" + text2;
                }
            }
            WriteAttributeString("xmlns", prefix, null, namespaceUri);
        }
References System.Xml.XmlDictionaryWriter.XmlWrappedWriter._depth, System.Xml.XmlDictionaryWriter.XmlWrappedWriter._prefix, System.Xml.Dictionary, System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.XmlDictionaryWriter.XmlWrappedWriter.LookupPrefix(), System.prefix, System.text, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(), and System.Xml.XmlDictionaryWriter.WriteAttributeString().