Terraria: System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.DecodeCore
DecodeCore() [2/2]
static void System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.DecodeCore (ref System::Formats::Asn1::AsnValueReader reader, Asn1Tag expectedTag, ReadOnlyMemory< byte > rebind, out System::Security::Cryptography::Asn1::SubjectPublicKeyInfoAsn decoded) inline static private
Definition at line 41 of file SubjectPublicKeyInfoAsn.cs.
    {
        decoded = default(System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn);
        System.Formats.Asn1.AsnValueReader reader2 = reader.ReadSequence(expectedTag);
        ReadOnlySpan<byte> span = rebind.Span;
        System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(ref reader2, rebind, out decoded.Algorithm);
        if (reader2.TryReadPrimitiveBitString(out var unusedBitCount, out var value))
        {
            decoded.SubjectPublicKey = (span.Overlaps(value, out var elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
        }
        else
        {
            decoded.SubjectPublicKey = reader2.ReadBitString(out unusedBitCount);
        }
        reader2.ThrowIfNotEmpty();
    }
References System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(), System.Formats.Asn1.AsnValueReader.ReadBitString(), System.Formats.Asn1.AsnValueReader.ReadSequence(), System.ReadOnlyMemory< T >.Slice(), System.ReadOnlyMemory< T >.Span, System.Formats.Asn1.AsnValueReader.ThrowIfNotEmpty(), System.Formats.Asn1.AsnValueReader.TryReadPrimitiveBitString(), and System.value.