Terraria: Microsoft.Xna.Framework.Graphics.DxtDecoder.DecodeRgbBlock
DecodeRgbBlock()
void Microsoft.Xna.Framework.Graphics.DxtDecoder.DecodeRgbBlock (byte[] source, int sourceOffset, Color[] result, int resultOffset, bool isDxt1) inline private
Definition at line 75 of file DxtDecoder.cs.
    {
        ushort num = Read16(source, sourceOffset);
        ushort num2 = Read16(source, sourceOffset + 2);
        ref Color reference = ref colorPalette[0];
        Bgr565 bgr = new Bgr565
        {
            PackedValue = num
        };
        reference = new Color(bgr.ToVector3());
        ref Color reference2 = ref colorPalette[1];
        Bgr565 bgr2 = new Bgr565
        {
            PackedValue = num2
        };
        reference2 = new Color(bgr2.ToVector3());
        if (num > num2 || !isDxt1)
        {
            ref Color reference3 = ref colorPalette[2];
            reference3 = Color.Lerp(colorPalette[0], colorPalette[1], 1f / 3f);
            ref Color reference4 = ref colorPalette[3];
            reference4 = Color.Lerp(colorPalette[0], colorPalette[1], 2f / 3f);
        }
        else
        {
            ref Color reference5 = ref colorPalette[2];
            reference5 = Color.Lerp(colorPalette[0], colorPalette[1], 0.5f);
            ref Color reference6 = ref colorPalette[3];
            reference6 = Color.Transparent;
        }
        uint num3 = Read32(source, sourceOffset + 4);
        for (int i = 0; i < 4; i++)
        {
            for (int j = 0; j < 4; j++)
            {
                uint num4 = num3 & 3u;
                num3 >>= 2;
                ref Color reference7 = ref result[resultOffset + i * width + j];
                reference7 = colorPalette[num4];
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.Bgr565, Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Graphics.DxtDecoder.colorPalette, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.Graphics.DxtDecoder.Read16(), Microsoft.Xna.Framework.Graphics.DxtDecoder.Read32(), System.source, Microsoft.Xna.Framework.Color.Transparent, and Microsoft.Xna.Framework.Graphics.DxtDecoder.width.
Referenced by Microsoft.Xna.Framework.Graphics.DxtDecoder.Decode().