Terraria: MS.Internal.Xml.XPath.XPathParser.ParseNodeTest
ParseNodeTest()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseNodeTest (AstNode qyInput, Axis::AxisType axisType, XPathNodeType nodeType) inline private
Definition at line 392 of file XPathParser.cs.
    {
        string prefix;
        string text;
        switch (_scanner.Kind)
        {
        case XPathScanner.LexKind.Name:
            if (_scanner.CanBeFunction && IsNodeType)
            {
                prefix = string.Empty;
                text = string.Empty;
                nodeType = ((_scanner.Name == "comment") ? XPathNodeType.Comment : ((_scanner.Name == "text") ? XPathNodeType.Text : ((_scanner.Name == "node") ? XPathNodeType.All : ((_scanner.Name == "processing-instruction") ? XPathNodeType.ProcessingInstruction : XPathNodeType.Root))));
                NextLex();
                PassToken(XPathScanner.LexKind.LParens);
                if (nodeType == XPathNodeType.ProcessingInstruction && _scanner.Kind != XPathScanner.LexKind.RParens)
                {
                    CheckToken(XPathScanner.LexKind.String);
                    text = _scanner.StringValue;
                    NextLex();
                }
                PassToken(XPathScanner.LexKind.RParens);
            }
            else
            {
                prefix = _scanner.Prefix;
                text = _scanner.Name;
                NextLex();
                if (text == "*")
                {
                    text = string.Empty;
                }
            }
            break;
        case XPathScanner.LexKind.Star:
            prefix = string.Empty;
            text = string.Empty;
            NextLex();
            break;
        default:
            throw XPathException.Create(System.SR.Xp_NodeSetExpected, _scanner.SourceText);
        }
        return new Axis(axisType, qyInput, prefix, text, nodeType);
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, MS.Internal.Xml.XPath.XPathScanner.CanBeFunction, MS.Internal.Xml.XPath.XPathParser.CheckToken(), System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.XPathParser.IsNodeType, MS.Internal.Xml.XPath.XPathScanner.Kind, MS.Internal.Xml.XPath.XPathScanner.Name, MS.Internal.Xml.XPath.XPathParser.NextLex(), MS.Internal.Xml.XPath.XPathParser.PassToken(), System.prefix, MS.Internal.Xml.XPath.XPathScanner.Prefix, MS.Internal.Xml.XPath.XPathScanner.SourceText, MS.Internal.Xml.XPath.XPathScanner.StringValue, System.text, and System.SR.Xp_NodeSetExpected.
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseStep(), and MS.Internal.Xml.XPath.XPathParser.ParseStepPattern().