Terraria: MS.Internal.Xml.XPath.XPathParser.ParseEqualityExpr
ParseEqualityExpr()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseEqualityExpr (AstNode qyInput) inline private
Definition at line 169 of file XPathParser.cs.
    {
        AstNode astNode = ParseRelationalExpr(qyInput);
        while (true)
        {
            Operator.Op op = ((_scanner.Kind == XPathScanner.LexKind.Eq) ? Operator.Op.EQ : ((_scanner.Kind == XPathScanner.LexKind.Ne) ? Operator.Op.NE : Operator.Op.INVALID));
            if (op == Operator.Op.INVALID)
            {
                break;
            }
            NextLex();
            astNode = new Operator(op, astNode, ParseRelationalExpr(qyInput));
        }
        return astNode;
    }
References MS.Internal.Xml.XPath.XPathParser.NextLex(), and MS.Internal.Xml.XPath.XPathParser.ParseRelationalExpr().
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseAndExpr().