Terraria: MS.Internal.Xml.XPath.XPathParser.ParseExpression
ParseExpression()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseExpression (AstNode qyInput) inline private
Definition at line 136 of file XPathParser.cs.
    {
        if (++_parseDepth > 200)
        {
            throw XPathException.Create(System.SR.Xp_QueryTooComplex);
        }
        AstNode result = ParseOrExpr(qyInput);
        _parseDepth--;
        return result;
    }
References MS.Internal.Xml.XPath.XPathParser._parseDepth, System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.XPathParser.ParseOrExpr(), and System.SR.Xp_QueryTooComplex.
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseMethod(), MS.Internal.Xml.XPath.XPathParser.ParsePredicate(), and MS.Internal.Xml.XPath.XPathParser.ParsePrimaryExpr().