Terraria: MS.Internal.Xml.XPath.XPathParser.ParseUnaryExpr
ParseUnaryExpr()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseUnaryExpr (AstNode qyInput) inline private
Definition at line 233 of file XPathParser.cs.
    {
        bool flag = false;
        while (_scanner.Kind == XPathScanner.LexKind.Minus)
        {
            NextLex();
            flag = !flag;
        }
        if (flag)
        {
            return new Operator(Operator.Op.MUL, ParseUnionExpr(qyInput), new Operand(-1.0));
        }
        return ParseUnionExpr(qyInput);
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, MS.Internal.Xml.XPath.XPathScanner.Kind, MS.Internal.Xml.XPath.XPathParser.NextLex(), and MS.Internal.Xml.XPath.XPathParser.ParseUnionExpr().
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseMultiplicativeExpr().