Terraria: MS.Internal.Xml.XPath.XPathParser.ParseStep
ParseStep()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseStep (AstNode qyInput) inline private
Definition at line 355 of file XPathParser.cs.
    {
        AstNode astNode;
        if (XPathScanner.LexKind.Dot == _scanner.Kind)
        {
            NextLex();
            astNode = new Axis(Axis.AxisType.Self, qyInput);
        }
        else if (XPathScanner.LexKind.DotDot == _scanner.Kind)
        {
            NextLex();
            astNode = new Axis(Axis.AxisType.Parent, qyInput);
        }
        else
        {
            Axis.AxisType axisType = Axis.AxisType.Child;
            switch (_scanner.Kind)
            {
            case XPathScanner.LexKind.At:
                axisType = Axis.AxisType.Attribute;
                NextLex();
                break;
            case XPathScanner.LexKind.Axe:
                axisType = GetAxis();
                NextLex();
                break;
            }
            XPathNodeType nodeType = ((axisType != Axis.AxisType.Attribute) ? XPathNodeType.Element : XPathNodeType.Attribute);
            astNode = ParseNodeTest(qyInput, axisType, nodeType);
            while (XPathScanner.LexKind.LBracket == _scanner.Kind)
            {
                astNode = new Filter(astNode, ParsePredicate(astNode));
            }
        }
        return astNode;
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, MS.Internal.Xml.XPath.XPathParser.GetAxis(), MS.Internal.Xml.XPath.XPathScanner.Kind, MS.Internal.Xml.XPath.XPathParser.NextLex(), MS.Internal.Xml.XPath.XPathParser.ParseNodeTest(), and MS.Internal.Xml.XPath.XPathParser.ParsePredicate().
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseRelativeLocationPath().