Terraria: MS.Internal.Xml.XPath.XPathParser.ParseMethod
ParseMethod()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseMethod (AstNode qyInput) inline private
Definition at line 474 of file XPathParser.cs.
    {
        List<AstNode> list = new List<AstNode>();
        string name = _scanner.Name;
        string prefix = _scanner.Prefix;
        PassToken(XPathScanner.LexKind.Name);
        PassToken(XPathScanner.LexKind.LParens);
        if (_scanner.Kind != XPathScanner.LexKind.RParens)
        {
            while (true)
            {
                list.Add(ParseExpression(qyInput));
                if (_scanner.Kind == XPathScanner.LexKind.RParens)
                {
                    break;
                }
                PassToken(XPathScanner.LexKind.Comma);
            }
        }
        PassToken(XPathScanner.LexKind.RParens);
        if (prefix.Length == 0 && s_functionTable.TryGetValue(name, out var value))
        {
            int num = list.Count;
            if (num < value.Minargs)
            {
                throw XPathException.Create(System.SR.Xp_InvalidNumArgs, name, _scanner.SourceText);
            }
            if (value.FType == Function.FunctionType.FuncConcat)
            {
                for (int i = 0; i < num; i++)
                {
                    AstNode astNode = list[i];
                    if (astNode.ReturnType != XPathResultType.String)
                    {
                        astNode = new Function(Function.FunctionType.FuncString, astNode);
                    }
                    list[i] = astNode;
                }
            }
            else
            {
                if (value.Maxargs < num)
                {
                    throw XPathException.Create(System.SR.Xp_InvalidNumArgs, name, _scanner.SourceText);
                }
                if (value.ArgTypes.Length < num)
                {
                    num = value.ArgTypes.Length;
                }
                for (int j = 0; j < num; j++)
                {
                    AstNode astNode2 = list[j];
                    if (value.ArgTypes[j] == XPathResultType.Any || value.ArgTypes[j] == astNode2.ReturnType)
                    {
                        continue;
                    }
                    switch (value.ArgTypes[j])
                    {
                    case XPathResultType.NodeSet:
                        if (!(astNode2 is Variable) && (!(astNode2 is Function) || astNode2.ReturnType != XPathResultType.Any))
{
                            throw XPathException.Create(System.SR.Xp_InvalidArgumentType, name, _scanner.SourceText);
                        }
                        break;
                    case XPathResultType.String:
                        astNode2 = new Function(Function.FunctionType.FuncString, astNode2);
                        break;
                    case XPathResultType.Number:
                        astNode2 = new Function(Function.FunctionType.FuncNumber, astNode2);
                        break;
                    case XPathResultType.Boolean:
                        astNode2 = new Function(Function.FunctionType.FuncBoolean, astNode2);
                        break;
                    }
                    list[j] = astNode2;
                }
            }
            return new Function(value.FType, list);
        }
        return new Function(prefix, name, list);
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.XPathScanner.Kind, System.list, MS.Internal.Xml.XPath.XPathScanner.Name, MS.Internal.Xml.XPath.XPathParser.ParseExpression(), MS.Internal.Xml.XPath.XPathParser.PassToken(), System.prefix, MS.Internal.Xml.XPath.XPathScanner.Prefix, MS.Internal.Xml.XPath.XPathParser.s_functionTable, MS.Internal.Xml.XPath.XPathScanner.SourceText, System.value, System.SR.Xp_InvalidArgumentType, and System.SR.Xp_InvalidNumArgs.
Referenced by MS.Internal.Xml.XPath.XPathParser.ParsePrimaryExpr().