Terraria: MS.Internal.Xml.XPath.XPathParser.TestOp
TestOp()
bool MS.Internal.Xml.XPath.XPathParser.TestOp (string op) inline private
Definition at line 706 of file XPathParser.cs.
    {
        if (_scanner.Kind == XPathScanner.LexKind.Name && _scanner.Prefix.Length == 0)
        {
            return _scanner.Name.Equals(op);
        }
        return false;
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, MS.Internal.Xml.XPath.XPathScanner.Kind, MS.Internal.Xml.XPath.XPathScanner.Name, and MS.Internal.Xml.XPath.XPathScanner.Prefix.
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseAndExpr(), MS.Internal.Xml.XPath.XPathParser.ParseMultiplicativeExpr(), and MS.Internal.Xml.XPath.XPathParser.ParseOrExpr().