Terraria: MS.Internal.Xml.XPath.XPathParser.NextLex
NextLex()
void MS.Internal.Xml.XPath.XPathParser.NextLex () inline private
Definition at line 701 of file XPathParser.cs.
    {
        _scanner.NextLex();
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, and MS.Internal.Xml.XPath.XPathScanner.NextLex().
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseAdditiveExpr(), MS.Internal.Xml.XPath.XPathParser.ParseAndExpr(), MS.Internal.Xml.XPath.XPathParser.ParseEqualityExpr(), MS.Internal.Xml.XPath.XPathParser.ParseIdKeyPattern(), MS.Internal.Xml.XPath.XPathParser.ParseLocationPath(), MS.Internal.Xml.XPath.XPathParser.ParseLocationPathPattern(), MS.Internal.Xml.XPath.XPathParser.ParseMultiplicativeExpr(), MS.Internal.Xml.XPath.XPathParser.ParseNodeTest(), MS.Internal.Xml.XPath.XPathParser.ParseOrExpr(), MS.Internal.Xml.XPath.XPathParser.ParsePathExpr(), MS.Internal.Xml.XPath.XPathParser.ParsePattern(), MS.Internal.Xml.XPath.XPathParser.ParsePrimaryExpr(), MS.Internal.Xml.XPath.XPathParser.ParseRelationalExpr(), MS.Internal.Xml.XPath.XPathParser.ParseRelativeLocationPath(), MS.Internal.Xml.XPath.XPathParser.ParseRelativePathPattern(), MS.Internal.Xml.XPath.XPathParser.ParseStep(), MS.Internal.Xml.XPath.XPathParser.ParseStepPattern(), MS.Internal.Xml.XPath.XPathParser.ParseUnaryExpr(), MS.Internal.Xml.XPath.XPathParser.ParseUnionExpr(), and MS.Internal.Xml.XPath.XPathParser.PassToken().