Terraria: MS.Internal.Xml.XPath.XPathParser.ParseAndExpr
ParseAndExpr()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseAndExpr (AstNode qyInput) inline private
Definition at line 158 of file XPathParser.cs.
    {
        AstNode astNode = ParseEqualityExpr(qyInput);
        while (TestOp("and"))
        {
            NextLex();
            astNode = new Operator(Operator.Op.AND, astNode, ParseEqualityExpr(qyInput));
        }
        return astNode;
    }
References MS.Internal.Xml.XPath.XPathParser.NextLex(), MS.Internal.Xml.XPath.XPathParser.ParseEqualityExpr(), and MS.Internal.Xml.XPath.XPathParser.TestOp().
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseOrExpr().