Terraria: MS.Internal.Xml.XPath.XPathParser.ParseAdditiveExpr
ParseAdditiveExpr()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseAdditiveExpr (AstNode qyInput) inline private
Definition at line 201 of file XPathParser.cs.
    {
        AstNode astNode = ParseMultiplicativeExpr(qyInput);
        while (true)
        {
            Operator.Op op = ((_scanner.Kind == XPathScanner.LexKind.Plus) ? Operator.Op.PLUS : ((_scanner.Kind == XPathScanner.LexKind.Minus) ? Operator.Op.MINUS : Operator.Op.INVALID));
            if (op == Operator.Op.INVALID)
            {
                break;
            }
            NextLex();
            astNode = new Operator(op, astNode, ParseMultiplicativeExpr(qyInput));
        }
        return astNode;
    }
References MS.Internal.Xml.XPath.XPathParser.NextLex(), and MS.Internal.Xml.XPath.XPathParser.ParseMultiplicativeExpr().
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseRelationalExpr().