Terraria: MS.Internal.Xml.XPath.XPathParser.ParseIdKeyPattern
ParseIdKeyPattern()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseIdKeyPattern () inline private
Definition at line 610 of file XPathParser.cs.
    {
        List<AstNode> list = new List<AstNode>();
        if (_scanner.Prefix.Length == 0)
        {
            if (_scanner.Name == "id")
            {
                ParamInfo paramInfo = s_functionTable["id"];
                NextLex();
                PassToken(XPathScanner.LexKind.LParens);
                CheckToken(XPathScanner.LexKind.String);
                list.Add(new Operand(_scanner.StringValue));
                NextLex();
                PassToken(XPathScanner.LexKind.RParens);
                return new Function(paramInfo.FType, list);
            }
            if (_scanner.Name == "key")
            {
                NextLex();
                PassToken(XPathScanner.LexKind.LParens);
                CheckToken(XPathScanner.LexKind.String);
                list.Add(new Operand(_scanner.StringValue));
                NextLex();
                PassToken(XPathScanner.LexKind.Comma);
                CheckToken(XPathScanner.LexKind.String);
                list.Add(new Operand(_scanner.StringValue));
                NextLex();
                PassToken(XPathScanner.LexKind.RParens);
                return new Function("", "key", list);
            }
        }
        return null;
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, MS.Internal.Xml.XPath.XPathParser.CheckToken(), System.list, MS.Internal.Xml.XPath.XPathScanner.Name, MS.Internal.Xml.XPath.XPathParser.NextLex(), MS.Internal.Xml.XPath.XPathParser.PassToken(), MS.Internal.Xml.XPath.XPathScanner.Prefix, MS.Internal.Xml.XPath.XPathParser.s_functionTable, and MS.Internal.Xml.XPath.XPathScanner.StringValue.
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseLocationPathPattern().