Terraria: MS.Internal.Xml.XPath.XPathParser.ParsePrimaryExpr
ParsePrimaryExpr()
AstNode MS.Internal.Xml.XPath.XPathParser.ParsePrimaryExpr (AstNode qyInput) inline private
Definition at line 436 of file XPathParser.cs.
    {
        AstNode astNode = null;
        switch (_scanner.Kind)
        {
        case XPathScanner.LexKind.String:
            astNode = new Operand(_scanner.StringValue);
            NextLex();
            break;
        case XPathScanner.LexKind.Number:
            astNode = new Operand(_scanner.NumberValue);
            NextLex();
            break;
        case XPathScanner.LexKind.Dollar:
            NextLex();
            CheckToken(XPathScanner.LexKind.Name);
            astNode = new Variable(_scanner.Name, _scanner.Prefix);
            NextLex();
            break;
        case XPathScanner.LexKind.LParens:
            NextLex();
            astNode = ParseExpression(qyInput);
            if (astNode.Type != AstNode.AstType.ConstantOperand)
            {
                astNode = new Group(astNode);
            }
            PassToken(XPathScanner.LexKind.RParens);
            break;
        case XPathScanner.LexKind.Name:
            if (_scanner.CanBeFunction && !IsNodeType)
            {
                astNode = ParseMethod(null);
            }
            break;
        }
        return astNode;
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, MS.Internal.Xml.XPath.XPathScanner.CanBeFunction, MS.Internal.Xml.XPath.XPathParser.CheckToken(), MS.Internal.Xml.XPath.XPathParser.IsNodeType, MS.Internal.Xml.XPath.XPathScanner.Kind, MS.Internal.Xml.XPath.XPathScanner.Name, MS.Internal.Xml.XPath.XPathParser.NextLex(), MS.Internal.Xml.XPath.XPathScanner.NumberValue, MS.Internal.Xml.XPath.XPathParser.ParseExpression(), MS.Internal.Xml.XPath.XPathParser.ParseMethod(), MS.Internal.Xml.XPath.XPathParser.PassToken(), MS.Internal.Xml.XPath.XPathScanner.Prefix, and MS.Internal.Xml.XPath.XPathScanner.StringValue.
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseFilterExpr().