Terraria: MS.Internal.Xml.XPath.XPathParser.ParseRelativePathPattern
ParseRelativePathPattern()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseRelativePathPattern (AstNode qyInput) inline private
Definition at line 644 of file XPathParser.cs.
    {
        AstNode astNode = ParseStepPattern(qyInput);
        if (XPathScanner.LexKind.SlashSlash == _scanner.Kind)
        {
            NextLex();
            astNode = ParseRelativePathPattern(new Axis(Axis.AxisType.DescendantOrSelf, astNode));
        }
        else if (XPathScanner.LexKind.Slash == _scanner.Kind)
        {
            NextLex();
            astNode = ParseRelativePathPattern(astNode);
        }
        return astNode;
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, MS.Internal.Xml.XPath.XPathScanner.Kind, MS.Internal.Xml.XPath.XPathParser.NextLex(), MS.Internal.Xml.XPath.XPathParser.ParseRelativePathPattern(), and MS.Internal.Xml.XPath.XPathParser.ParseStepPattern().
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseLocationPathPattern(), and MS.Internal.Xml.XPath.XPathParser.ParseRelativePathPattern().