Terraria: MS.Internal.Xml.XPath.XPathParser.ParseStepPattern
ParseStepPattern()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseStepPattern (AstNode qyInput) inline private
Definition at line 660 of file XPathParser.cs.
    {
        Axis.AxisType axisType = Axis.AxisType.Child;
        switch (_scanner.Kind)
        {
        case XPathScanner.LexKind.At:
            axisType = Axis.AxisType.Attribute;
            NextLex();
            break;
        case XPathScanner.LexKind.Axe:
            axisType = GetAxis();
            if (axisType != Axis.AxisType.Child && axisType != Axis.AxisType.Attribute)
            {
                throw XPathException.Create(System.SR.Xp_InvalidToken, _scanner.SourceText);
            }
            NextLex();
            break;
        }
        XPathNodeType nodeType = ((axisType != Axis.AxisType.Attribute) ? XPathNodeType.Element : XPathNodeType.Attribute);
        AstNode astNode = ParseNodeTest(qyInput, axisType, nodeType);
        while (XPathScanner.LexKind.LBracket == _scanner.Kind)
        {
            astNode = new Filter(astNode, ParsePredicate(astNode));
        }
        return astNode;
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.XPathParser.GetAxis(), MS.Internal.Xml.XPath.XPathScanner.Kind, MS.Internal.Xml.XPath.XPathParser.NextLex(), MS.Internal.Xml.XPath.XPathParser.ParseNodeTest(), MS.Internal.Xml.XPath.XPathParser.ParsePredicate(), MS.Internal.Xml.XPath.XPathScanner.SourceText, and System.SR.Xp_InvalidToken.
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseRelativePathPattern().