Terraria: MS.Internal.Xml.XPath.XPathParser.CheckToken
CheckToken()
void MS.Internal.Xml.XPath.XPathParser.CheckToken (XPathScanner::LexKind t) inline private
Definition at line 687 of file XPathParser.cs.
    {
        if (_scanner.Kind != t)
        {
            throw XPathException.Create(System.SR.Xp_InvalidToken, _scanner.SourceText);
        }
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.XPathScanner.Kind, MS.Internal.Xml.XPath.XPathScanner.SourceText, and System.SR.Xp_InvalidToken.
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseIdKeyPattern(), MS.Internal.Xml.XPath.XPathParser.ParseNodeTest(), MS.Internal.Xml.XPath.XPathParser.ParsePrimaryExpr(), and MS.Internal.Xml.XPath.XPathParser.PassToken().