Terraria: MS.Internal.Xml.XPath.XPathParser.ParseXPathExpression
ParseXPathExpression()
static AstNode MS.Internal.Xml.XPath.XPathParser.ParseXPathExpression (string xpathExpression) inline static
Definition at line 114 of file XPathParser.cs.
    {
        XPathParser xPathParser = new XPathParser(xpathExpression);
        AstNode result = xPathParser.ParseExpression(null);
        if (xPathParser._scanner.Kind != XPathScanner.LexKind.Eof)
        {
            throw XPathException.Create(System.SR.Xp_InvalidToken, xPathParser._scanner.SourceText);
        }
        return result;
    }
References MS.Internal.Xml.XPath.XPathParser.XPathParser(), System.Xml.XPath.XPathException.Create(), and System.SR.Xp_InvalidToken.
Referenced by MS.Internal.Xml.XPath.QueryBuilder.Build(), and System.Xml.Schema.Asttree.CompileXPath().