Terraria: MS.Internal.Xml.XPath.XPathParser.ParseRelationalExpr
ParseRelationalExpr()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseRelationalExpr (AstNode qyInput) inline private
Definition at line 185 of file XPathParser.cs.
    {
        AstNode astNode = ParseAdditiveExpr(qyInput);
        while (true)
        {
            Operator.Op op = ((_scanner.Kind == XPathScanner.LexKind.Lt) ? Operator.Op.LT : ((_scanner.Kind == XPathScanner.LexKind.Le) ? Operator.Op.LE : ((_scanner.Kind == XPathScanner.LexKind.Gt) ? Operator.Op.GT : ((_scanner.Kind == XPathScanner.LexKind.Ge) ? Operator.Op.GE : Operator.Op.INVALID))));
            if (op == Operator.Op.INVALID)
            {
                break;
            }
            NextLex();
            astNode = new Operator(op, astNode, ParseAdditiveExpr(qyInput));
        }
        return astNode;
    }
References MS.Internal.Xml.XPath.XPathParser.NextLex(), and MS.Internal.Xml.XPath.XPathParser.ParseAdditiveExpr().
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseEqualityExpr().