Terraria: MS.Internal.Xml.XPath.XPathParser.ParseFilterExpr
ParseFilterExpr()
AstNode MS.Internal.Xml.XPath.XPathParser.ParseFilterExpr (AstNode qyInput) inline private
Definition at line 286 of file XPathParser.cs.
    {
        AstNode astNode = ParsePrimaryExpr(qyInput);
        while (_scanner.Kind == XPathScanner.LexKind.LBracket)
        {
            astNode = new Filter(astNode, ParsePredicate(astNode));
        }
        return astNode;
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, MS.Internal.Xml.XPath.XPathScanner.Kind, MS.Internal.Xml.XPath.XPathParser.ParsePredicate(), and MS.Internal.Xml.XPath.XPathParser.ParsePrimaryExpr().
Referenced by MS.Internal.Xml.XPath.XPathParser.ParsePathExpr().