Terraria: MS.Internal.Xml.XPath.XPathParser.CheckNodeSet
CheckNodeSet()
void MS.Internal.Xml.XPath.XPathParser.CheckNodeSet (XPathResultType t) inline private
Definition at line 715 of file XPathParser.cs.
    {
        if (t != XPathResultType.NodeSet && t != XPathResultType.Any)
        {
            throw XPathException.Create(System.SR.Xp_NodeSetExpected, _scanner.SourceText);
        }
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.XPathScanner.SourceText, and System.SR.Xp_NodeSetExpected.
Referenced by MS.Internal.Xml.XPath.XPathParser.ParsePredicate(), and MS.Internal.Xml.XPath.XPathParser.ParseUnionExpr().