Terraria: MS.Internal.Xml.XPath.XPathParser.GetAxis
GetAxis()
Axis.AxisType MS.Internal.Xml.XPath.XPathParser.GetAxis () inline private
Definition at line 775 of file XPathParser.cs.
    {
        if (!s_AxesTable.TryGetValue(_scanner.Name, out var value))
        {
            throw XPathException.Create(System.SR.Xp_InvalidToken, _scanner.SourceText);
        }
        return value;
    }
References MS.Internal.Xml.XPath.XPathParser._scanner, System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.XPathScanner.Name, MS.Internal.Xml.XPath.XPathParser.s_AxesTable, MS.Internal.Xml.XPath.XPathScanner.SourceText, System.value, and System.SR.Xp_InvalidToken.
Referenced by MS.Internal.Xml.XPath.XPathParser.ParseStep(), and MS.Internal.Xml.XPath.XPathParser.ParseStepPattern().