Terraria: Terraria.Utilities.CrashWatcher.PrintException
PrintException()
static string Terraria.Utilities.CrashWatcher.PrintException (Exception ex) inline static private
Definition at line 44 of file CrashWatcher.cs.
    {
        string text = ex.ToString();
        try
        {
            int num = (int)typeof(Exception).GetProperty("HResult", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic).GetGetMethod(nonPublic: true).Invoke(ex, null);
            if (num != 0)
            {
                text = text + "\nHResult: " + num;
            }
        }
        catch
        {
        }
        if (ex is ReflectionTypeLoadException)
        {
            Exception[] loaderExceptions = ((ReflectionTypeLoadException)ex).LoaderExceptions;
            foreach (Exception ex2 in loaderExceptions)
            {
                text = text + "\n+--> " + PrintException(ex2);
            }
        }
        return text;
    }
References Terraria.Utilities.CrashWatcher.PrintException(), System.text, and System.Exception.ToString().
Referenced by Terraria.Utilities.CrashWatcher.Inititialize(), and Terraria.Utilities.CrashWatcher.PrintException().