Terraria: System.Text.DecoderFallbackBuffer.TryInternalFallbackGetChars
TryInternalFallbackGetChars()
bool System.Text.DecoderFallbackBuffer.TryInternalFallbackGetChars (ReadOnlySpan< byte > remainingBytes, int fallbackLength, Span< char > chars, out int charsWritten) inline package inherited
Definition at line 144 of file DecoderFallbackBuffer.cs.
    {
        if (Fallback(remainingBytes.Slice(0, fallbackLength).ToArray(), _originalByteCount - remainingBytes.Length))
        {
            return TryDrainRemainingDataForGetChars(chars, out charsWritten);
        }
        charsWritten = 0;
        return true;
    }
References System.Text.DecoderFallbackBuffer._originalByteCount, System.chars, System.Text.DecoderFallbackBuffer.Fallback(), System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), and System.Text.DecoderFallbackBuffer.TryDrainRemainingDataForGetChars().