Terraria: System.Text.DecoderFallbackBuffer.InternalFallback
InternalFallback() [2/2]
virtual unsafe bool System.Text.DecoderFallbackBuffer.InternalFallback (byte[] bytes, byte * pBytes, ref char * chars) inline package virtual inherited
Definition at line 53 of file DecoderFallbackBuffer.cs.
    {
        if (Fallback(bytes, (int)(pBytes - byteStart - bytes.Length)))
        {
            char* ptr = chars;
            bool flag = false;
            char nextChar;
            while ((nextChar = GetNextChar()) != 0)
            {
                if (char.IsSurrogate(nextChar))
                {
                    if (char.IsHighSurrogate(nextChar))
                    {
                        if (flag)
{
                            throw new ArgumentException(SR.Argument_InvalidCharSequenceNoIndex);
                        }
                        flag = true;
                    }
                    else
                    {
                        if (!flag)
{
                            throw new ArgumentException(SR.Argument_InvalidCharSequenceNoIndex);
                        }
                        flag = false;
                    }
                }
                if (ptr >= charEnd)
                {
                    return false;
                }
                *(ptr++) = nextChar;
            }
            if (flag)
            {
                throw new ArgumentException(SR.Argument_InvalidCharSequenceNoIndex);
            }
            chars = ptr;
        }
        return true;
    }
References System.SR.Argument_InvalidCharSequenceNoIndex, System.bytes, System.Text.DecoderFallbackBuffer.byteStart, System.Text.DecoderFallbackBuffer.charEnd, System.chars, System.Text.DecoderFallbackBuffer.Fallback(), and System.Text.DecoderFallbackBuffer.GetNextChar().
Referenced by System.Text.Encoding.EncodingCharBuffer.Fallback(), System.Text.UnicodeEncoding.GetCharCount(), System.Text.UTF32Encoding.GetCharCount(), System.Text.UnicodeEncoding.GetChars(), and System.Text.UTF32Encoding.GetChars().