Terraria: System.Text.DecoderFallbackBuffer.Reset
Reset()
virtual void System.Text.DecoderFallbackBuffer.Reset () inline virtual
Reimplemented in System.Text.DecoderReplacementFallbackBuffer, System.Text.UTF7Encoding.DecoderUTF7FallbackBuffer, and System.Text.InternalDecoderBestFitFallbackBuffer.
Definition at line 25 of file DecoderFallbackBuffer.cs.
    {
        while (GetNextChar() != 0)
        {
        }
    }
References System.Text.DecoderFallbackBuffer.GetNextChar().
Referenced by System.Text.DecoderFallbackBuffer.InternalReset(), System.Text.DecoderFallbackBufferHelper.InternalReset(), System.Text.Decoder.Reset(), System.Text.DecoderNLS.Reset(), System.Text.UnicodeEncoding.Decoder.Reset(), System.Text.UTF32Encoding.UTF32Decoder.Reset(), System.Text.UTF7Encoding.Decoder.Reset(), System.Text.DBCSCodePageEncoding.DBCSDecoder.Reset(), System.Text.GB18030Encoding.GB18030Decoder.Reset(), System.Text.ISCIIEncoding.ISCIIDecoder.Reset(), and System.Text.ISO2022Encoding.ISO2022Decoder.Reset().