Terraria: System.Text.DecoderFallbackBuffer.CreateAndInitialize
CreateAndInitialize()
static DecoderFallbackBuffer System.Text.DecoderFallbackBuffer.CreateAndInitialize (Encoding encoding, DecoderNLS decoder, int originalByteCount) inline static package inherited
Definition at line 44 of file DecoderFallbackBuffer.cs.
    {
        DecoderFallbackBuffer decoderFallbackBuffer = ((decoder == null) ? encoding.DecoderFallback.CreateFallbackBuffer() : decoder.FallbackBuffer);
        decoderFallbackBuffer._encoding = encoding;
        decoderFallbackBuffer._decoder = decoder;
        decoderFallbackBuffer._originalByteCount = originalByteCount;
        return decoderFallbackBuffer;
    }
References System.Text.DecoderFallback.CreateFallbackBuffer(), System.Text.Encoding.DecoderFallback, and System.Text.DecoderNLS.FallbackBuffer.
Referenced by System.Text.Encoding.GetCharCountWithFallback(), and System.Text.Encoding.GetCharsWithFallback().