Terraria: System.Text.DecoderFallbackBuffer.InternalReset
InternalReset()
unsafe void System.Text.DecoderFallbackBuffer.InternalReset () inline package inherited
Definition at line 32 of file DecoderFallbackBuffer.cs.
    {
        byteStart = null;
        Reset();
    }
References System.Text.DecoderFallbackBuffer.byteStart, and System.Text.DecoderFallbackBuffer.Reset().
Referenced by System.Text.DecoderFallbackBuffer.DrainRemainingDataForGetCharCount(), System.Text.Encoding.EncodingCharBuffer.Fallback(), System.Text.UnicodeEncoding.GetChars(), System.Text.UTF32Encoding.GetChars(), and System.Text.DecoderFallbackBuffer.TryDrainRemainingDataForGetChars().