Terraria: System.Text.DecoderFallbackBuffer.ThrowLastBytesRecursive
ThrowLastBytesRecursive()
static void System.Text.DecoderFallbackBuffer.ThrowLastBytesRecursive (byte[] bytesUnknown) inline static package inherited
Definition at line 210 of file DecoderFallbackBuffer.cs.
    {
        if (bytesUnknown == null)
        {
            bytesUnknown = Array.Empty<byte>();
        }
        StringBuilder stringBuilder = new StringBuilder(bytesUnknown.Length * 3);
        int i;
        for (i = 0; i < bytesUnknown.Length && i < 20; i++)
        {
            if (stringBuilder.Length > 0)
            {
                stringBuilder.Append(' ');
            }
            StringBuilder stringBuilder2 = stringBuilder;
            StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(2, 1, stringBuilder2);
            handler.AppendLiteral("\\x");
            handler.AppendFormatted(bytesUnknown[i], "X2");
            stringBuilder2.Append(ref handler);
        }
        if (i == 20)
        {
            stringBuilder.Append(" ...");
        }
        throw new ArgumentException(SR.Format(SR.Argument_RecursiveFallbackBytes, stringBuilder.ToString()), "bytesUnknown");
    }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendLiteral(), System.SR.Argument_RecursiveFallbackBytes, System.SR.Format(), System.Text.StringBuilder.Length, and System.Text.StringBuilder.ToString().
Referenced by System.Text.DecoderReplacementFallbackBuffer.Fallback().