Terraria: System.Net.Mime.MimeMultiPart.MimePartSentCallbackHandler
MimePartSentCallbackHandler()
void System.Net.Mime.MimeMultiPart.MimePartSentCallbackHandler (IAsyncResult result) inline private
Definition at line 139 of file MimeMultiPart.cs.
    {
        MimePartContext mimePartContext = (MimePartContext)result.AsyncState;
        MimeBasePart current = mimePartContext._partsEnumerator.Current;
        current.EndSend(result);
        if (mimePartContext._partsEnumerator.MoveNext())
        {
            current = mimePartContext._partsEnumerator.Current;
            IAsyncResult asyncResult = current.BeginSend(mimePartContext._writer, _mimePartSentCallback, _allowUnicode, mimePartContext);
            if (asyncResult.CompletedSynchronously)
            {
                MimePartSentCallbackHandler(asyncResult);
            }
        }
        else
        {
            IAsyncResult asyncResult2 = ((MimeWriter)mimePartContext._writer).BeginClose(MimeWriterCloseCallback, mimePartContext);
            if (asyncResult2.CompletedSynchronously)
            {
                MimeWriterCloseCallbackHandler(asyncResult2);
            }
        }
    }
References System.Net.Mime.MimeMultiPart._allowUnicode, System.Net.Mime.MimeMultiPart._mimePartSentCallback, System.asyncResult, System.IAsyncResult.AsyncState, System.Net.Mime.MimeBasePart.BeginSend(), System.Net.Mime.MimeBasePart.EndSend(), System.Net.Mime.MimeMultiPart.MimePartSentCallbackHandler(), System.Net.Mime.MimeMultiPart.MimeWriterCloseCallback(), and System.Net.Mime.MimeMultiPart.MimeWriterCloseCallbackHandler().
Referenced by System.Net.Mime.MimeMultiPart.ContentStreamCallbackHandler(), System.Net.Mime.MimeMultiPart.MimePartSentCallback(), and System.Net.Mime.MimeMultiPart.MimePartSentCallbackHandler().