Terraria: System.Net.Mime.MimeMultiPart.MimeWriterCloseCallbackHandler
MimeWriterCloseCallbackHandler()
void System.Net.Mime.MimeMultiPart.MimeWriterCloseCallbackHandler (IAsyncResult result) inline private
Definition at line 115 of file MimeMultiPart.cs.
    {
        MimePartContext mimePartContext = (MimePartContext)result.AsyncState;
        ((MimeWriter)mimePartContext._writer).EndClose(result);
        Complete(result, null);
    }
References System.IAsyncResult.AsyncState, and System.Net.Mime.MimeMultiPart.Complete().
Referenced by System.Net.Mime.MimeMultiPart.ContentStreamCallbackHandler(), System.Net.Mime.MimeMultiPart.MimePartSentCallbackHandler(), and System.Net.Mime.MimeMultiPart.MimeWriterCloseCallback().