Terraria: System.Net.Mime.MimeMultiPart.BeginSend
BeginSend()
override IAsyncResult System.Net.Mime.MimeMultiPart.BeginSend (BaseWriter writer, AsyncCallback callback, bool allowUnicode, object state) inline package virtual
Reimplemented from System.Net.Mime.MimeBasePart.
Definition at line 205 of file MimeMultiPart.cs.
    {
        _allowUnicode = allowUnicode;
        PrepareHeaders(allowUnicode);
        writer.WriteHeaders(base.Headers, allowUnicode);
        MimePartAsyncResult result = new MimePartAsyncResult(this, state, callback);
        MimePartContext state2 = new MimePartContext(writer, result, Parts.GetEnumerator());
        IAsyncResult asyncResult = writer.BeginGetContentStream(ContentStreamCallback, state2);
        if (asyncResult.CompletedSynchronously)
        {
            ContentStreamCallbackHandler(asyncResult);
        }
        return result;
    }
References System.Net.Mime.MimeMultiPart._allowUnicode, System.asyncResult, System.Net.Mime.MimeMultiPart.ContentStreamCallback(), System.Net.Mime.MimeMultiPart.ContentStreamCallbackHandler(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Net.Mime.MimeMultiPart.Parts, System.Net.Mime.MimeBasePart.PrepareHeaders(), System.state, and System.writer.