using System;

namespace Internal.Cryptography.Pal.Native;

[Flags]
internal enum CertTrustErrorStatus
{
	CERT_TRUST_NO_ERROR = 0,
	CERT_TRUST_IS_NOT_TIME_VALID = 1,
	CERT_TRUST_IS_NOT_TIME_NESTED = 2,
	CERT_TRUST_IS_REVOKED = 4,
	CERT_TRUST_IS_NOT_SIGNATURE_VALID = 8,
	CERT_TRUST_IS_NOT_VALID_FOR_USAGE = 0x10,
	CERT_TRUST_IS_UNTRUSTED_ROOT = 0x20,
	CERT_TRUST_REVOCATION_STATUS_UNKNOWN = 0x40,
	CERT_TRUST_IS_CYCLIC = 0x80,
	CERT_TRUST_INVALID_EXTENSION = 0x100,
	CERT_TRUST_INVALID_POLICY_CONSTRAINTS = 0x200,
	CERT_TRUST_INVALID_BASIC_CONSTRAINTS = 0x400,
	CERT_TRUST_INVALID_NAME_CONSTRAINTS = 0x800,
	CERT_TRUST_HAS_NOT_SUPPORTED_NAME_CONSTRAINT = 0x1000,
	CERT_TRUST_HAS_NOT_DEFINED_NAME_CONSTRAINT = 0x2000,
	CERT_TRUST_HAS_NOT_PERMITTED_NAME_CONSTRAINT = 0x4000,
	CERT_TRUST_HAS_EXCLUDED_NAME_CONSTRAINT = 0x8000,
	CERT_TRUST_IS_OFFLINE_REVOCATION = 0x1000000,
	CERT_TRUST_NO_ISSUANCE_CHAIN_POLICY = 0x2000000,
	CERT_TRUST_IS_EXPLICIT_DISTRUST = 0x4000000,
	CERT_TRUST_HAS_NOT_SUPPORTED_CRITICAL_EXT = 0x8000000,
	CERT_TRUST_HAS_WEAK_SIGNATURE = 0x100000,
	CERT_TRUST_IS_PARTIAL_CHAIN = 0x10000,
	CERT_TRUST_CTL_IS_NOT_TIME_VALID = 0x20000,
	CERT_TRUST_CTL_IS_NOT_SIGNATURE_VALID = 0x40000,
	CERT_TRUST_CTL_IS_NOT_VALID_FOR_USAGE = 0x80000
}
