namespace Internal.Cryptography.Pal.Native;

internal enum CertStoreAddDisposition
{
	CERT_STORE_ADD_NEW = 1,
	CERT_STORE_ADD_USE_EXISTING,
	CERT_STORE_ADD_REPLACE_EXISTING,
	CERT_STORE_ADD_ALWAYS,
	CERT_STORE_ADD_REPLACE_EXISTING_INHERIT_PROPERTIES,
	CERT_STORE_ADD_NEWER,
	CERT_STORE_ADD_NEWER_INHERIT_PROPERTIES
}
