using System;

namespace Internal.Cryptography.Pal.Native;

[Flags]
internal enum CertTrustInfoStatus
{
	CERT_TRUST_HAS_EXACT_MATCH_ISSUER = 1,
	CERT_TRUST_HAS_KEY_MATCH_ISSUER = 2,
	CERT_TRUST_HAS_NAME_MATCH_ISSUER = 4,
	CERT_TRUST_IS_SELF_SIGNED = 8,
	CERT_TRUST_HAS_PREFERRED_ISSUER = 0x100,
	CERT_TRUST_HAS_ISSUANCE_CHAIN_POLICY = 0x200,
	CERT_TRUST_HAS_VALID_NAME_CONSTRAINTS = 0x400,
	CERT_TRUST_IS_COMPLEX_CHAIN = 0x10000
}
