namespace Internal.Cryptography.Pal.Native;

internal enum CertNameType
{
	CERT_NAME_EMAIL_TYPE = 1,
	CERT_NAME_RDN_TYPE,
	CERT_NAME_ATTR_TYPE,
	CERT_NAME_SIMPLE_DISPLAY_TYPE,
	CERT_NAME_FRIENDLY_DISPLAY_TYPE,
	CERT_NAME_DNS_TYPE,
	CERT_NAME_URL_TYPE,
	CERT_NAME_UPN_TYPE
}
