using System;

namespace Internal.Cryptography.Pal.Native;

[Flags]
internal enum CertChainFlags
{
	None = 0,
	CERT_CHAIN_DISABLE_AUTH_ROOT_AUTO_UPDATE = 0x100,
	CERT_CHAIN_DISABLE_AIA = 0x2000,
	CERT_CHAIN_REVOCATION_CHECK_END_CERT = 0x10000000,
	CERT_CHAIN_REVOCATION_CHECK_CHAIN = 0x20000000,
	CERT_CHAIN_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT = 0x40000000,
	CERT_CHAIN_REVOCATION_CHECK_CACHE_ONLY = int.MinValue
}
