using System;

namespace Internal.Cryptography.Pal.Native;

[Flags]
internal enum ExpectedContentTypeFlags
{
	CERT_QUERY_CONTENT_FLAG_CERT = 2,
	CERT_QUERY_CONTENT_FLAG_CTL = 4,
	CERT_QUERY_CONTENT_FLAG_CRL = 8,
	CERT_QUERY_CONTENT_FLAG_SERIALIZED_STORE = 0x10,
	CERT_QUERY_CONTENT_FLAG_SERIALIZED_CERT = 0x20,
	CERT_QUERY_CONTENT_FLAG_SERIALIZED_CTL = 0x40,
	CERT_QUERY_CONTENT_FLAG_SERIALIZED_CRL = 0x80,
	CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED = 0x100,
	CERT_QUERY_CONTENT_FLAG_PKCS7_UNSIGNED = 0x200,
	CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED_EMBED = 0x400,
	CERT_QUERY_CONTENT_FLAG_PKCS10 = 0x800,
	CERT_QUERY_CONTENT_FLAG_PFX = 0x1000,
	CERT_QUERY_CONTENT_FLAG_CERT_PAIR = 0x2000,
	CERT_QUERY_CONTENT_FLAG_PFX_AND_LOAD = 0x4000,
	CERT_QUERY_CONTENT_FLAG_ALL = 0x3FFE
}
