Terraria: TcpSocket.ListenLoop
ListenLoop()
void TcpSocket.ListenLoop () inline private
     {
         while (_isListening && !Netplay.Disconnect)
         {
             try
             {
                 ISocket socket = new TcpSocket(_listener.AcceptTcpClient());
                 Console.WriteLine(Language.GetTextValue("Net.ClientConnecting", socket.GetRemoteAddress()));
                 _listenerCallback(socket);
             }
             catch (Exception)
             {
             }
         }
         _listener.Stop();
     }
References TcpSocket(), _isListening, _listener, _listenerCallback, Netplay.Disconnect, ISocket.GetRemoteAddress(), and Language.GetTextValue().
Referenced by StartListening().