Terraria: System.Linq.Queryable.Join< TOuter, TInner, TKey, TResult >
Join< TOuter, TInner, TKey, TResult >() [1/2]
static IQueryable< TResult > System.Linq.Queryable.Join< TOuter, TInner, TKey, TResult > (this IQueryable< TOuter > outer, IEnumerable< TInner > inner, Expression< Func< TOuter, TKey > > outerKeySelector, Expression< Func< TInner, TKey > > innerKeySelector, Expression< Func< TOuter, TInner, TResult > > resultSelector) inline static
Definition at line 189 of file Queryable.cs.
    {
        if (outer == null)
        {
            throw Error.ArgumentNull("outer");
        }
        if (inner == null)
        {
            throw Error.ArgumentNull("inner");
        }
        if (outerKeySelector == null)
        {
            throw Error.ArgumentNull("outerKeySelector");
        }
        if (innerKeySelector == null)
        {
            throw Error.ArgumentNull("innerKeySelector");
        }
        if (resultSelector == null)
        {
            throw Error.ArgumentNull("resultSelector");
        }
        return outer.Provider.CreateQuery<TResult>(Expression.Call(null, CachedReflectionInfo.Join_TOuter_TInner_TKey_TResult_5(typeof(TOuter), typeof(TInner), typeof(TKey), typeof(TResult)), outer.Expression, GetSourceExpression(inner), Expression.Quote(outerKeySelector), Expression.Quote(innerKeySelector), Expression.Quote(resultSelector)));
    }
References System.Linq.Error.ArgumentNull(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.inner, System.Linq.innerKeySelector, System.Linq.CachedReflectionInfo.Join_TOuter_TInner_TKey_TResult_5(), System.Linq.outer, System.Linq.outerKeySelector, System.Linq.Expressions.Expression< TDelegate >.Quote(), and System.Linq.resultSelector.