Terraria: System.Data.SqlTypes.SqlInt32.Null
Null
readonly SqlInt32 System.Data.SqlTypes.SqlInt32.Null = new SqlInt32(fNull: true) static
Definition at line 19 of file SqlInt32.cs.
Referenced by System.Data.Common.SqlConvert.ConvertToSqlInt32(), System.Data.Common.SqlConvert.ConvertToSqlInt64(), System.Data.SqlTypes.SqlInt32.operator SqlInt32(), System.Data.SqlTypes.SqlInt32.operator SqlInt32(), System.Data.SqlTypes.SqlInt32.operator SqlInt32(), System.Data.SqlTypes.SqlInt32.operator SqlInt32(), System.Data.SqlTypes.SqlInt32.operator SqlInt32(), System.Data.SqlTypes.SqlInt32.operator SqlInt32(), System.Data.SqlTypes.SqlInt32.operator SqlInt32(), System.Data.SqlTypes.SqlInt32.operator SqlInt32(), System.Data.SqlTypes.SqlInt32.operator SqlInt32(), System.Data.SqlTypes.SqlInt32.operator%(), System.Data.SqlTypes.SqlInt32.operator&(), System.Data.SqlTypes.SqlInt32.operator*(), System.Data.SqlTypes.SqlInt32.operator+(), System.Data.SqlTypes.SqlInt32.operator-(), System.Data.SqlTypes.SqlInt32.operator-(), System.Data.SqlTypes.SqlInt32.operator/(), System.Data.SqlTypes.SqlInt32.operator^(), System.Data.SqlTypes.SqlInt32.operator|(), System.Data.SqlTypes.SqlInt32.operator~(), System.Data.SqlTypes.SqlInt32.Parse(), and System.Data.SqlTypes.SqlDecimal.Sign().