Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator
EndNestedIterator()
void System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator (QilNode nd) inline private
Definition at line 2939 of file XmlILVisitor.cs.
    {
        if (_iterCurr.IsBranching && _iterCurr.Storage.Location != 0)
        {
            _iterCurr.EnsureItemStorageType(nd.XmlType, typeof(bool));
            _iterCurr.EnsureStackNoCache();
            if (_iterCurr.CurrentBranchingContext == BranchingContext.OnTrue)
            {
                _helper.Emit(OpCodes.Brtrue, _iterCurr.LabelBranch);
            }
            else
            {
                _helper.Emit(OpCodes.Brfalse, _iterCurr.LabelBranch);
            }
            _iterCurr.Storage = StorageDescriptor.None();
        }
        _iterNested = _iterCurr;
        _iterCurr = _iterCurr.ParentIterator;
    }
References System.Reflection.Emit.OpCodes.Brfalse, System.Reflection.Emit.OpCodes.Brtrue, System.Xml.Dictionary, and System.Xml.Xsl.IlGen.StorageDescriptor.None().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateConcat(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.StartLetBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.Visit(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAnd(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFilter(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNodeValue(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId().