Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitTextCtor
VisitTextCtor() [2/2]
QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitTextCtor (QilUnary ndText, bool disableOutputEscaping) inline private
Definition at line 1744 of file XmlILVisitor.cs.
    {
        XmlILConstructInfo xmlILConstructInfo = XmlILConstructInfo.Read(ndText);
        PossibleXmlStates initialStates = xmlILConstructInfo.InitialStates;
        bool flag = (uint)(initialStates - 4) > 2u && CheckWithinContent(xmlILConstructInfo);
        if (!flag)
        {
            BeforeStartChecks(ndText);
        }
        _helper.LoadQueryOutput();
        NestedVisitEnsureStack(ndText.Child);
        switch (xmlILConstructInfo.InitialStates)
        {
        case PossibleXmlStates.WithinAttr:
            _helper.CallWriteString(disableOutputEscaping: false, flag);
            break;
        case PossibleXmlStates.WithinComment:
            _helper.Call(XmlILMethods.CommentText);
            break;
        case PossibleXmlStates.WithinPI:
            _helper.Call(XmlILMethods.PIText);
            break;
        default:
            _helper.CallWriteString(disableOutputEscaping, flag);
            break;
        }
        if (!flag)
        {
            AfterEndChecks(ndText);
        }
        _iterCurr.Storage = StorageDescriptor.None();
        return ndText;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor.AfterEndChecks(), System.Xml.Xsl.IlGen.XmlILVisitor.BeforeStartChecks(), System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteString(), System.Xml.Xsl.IlGen.XmlILVisitor.CheckWithinContent(), System.Xml.Xsl.IlGen.XmlILMethods.CommentText, System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryOutput(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.StorageDescriptor.None(), System.Xml.Xsl.IlGen.XmlILMethods.PIText, and System.Xml.Xsl.IlGen.XmlILConstructInfo.Read().