Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttributeCtor
VisitAttributeCtor()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttributeCtor (QilBinary ndAttr) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1694 of file XmlILVisitor.cs.
    {
        XmlILConstructInfo xmlILConstructInfo = XmlILConstructInfo.Read(ndAttr);
        bool flag = CheckEnumAttrs(xmlILConstructInfo) || !xmlILConstructInfo.IsNamespaceInScope;
        if (!flag)
        {
            BeforeStartChecks(ndAttr);
        }
        GenerateNameType nameType = LoadNameAndType(XPathNodeType.Attribute, ndAttr.Left, isStart: true, flag);
        _helper.CallWriteStartAttribute(nameType, flag);
        NestedVisit(ndAttr.Right);
        _helper.CallWriteEndAttribute(flag);
        if (!flag)
        {
            AfterEndChecks(ndAttr);
        }
        _iterCurr.Storage = StorageDescriptor.None();
        return ndAttr;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor.AfterEndChecks(), System.Xml.Xsl.IlGen.XmlILVisitor.BeforeStartChecks(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteEndAttribute(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteStartAttribute(), System.Xml.Xsl.IlGen.XmlILVisitor.CheckEnumAttrs(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILVisitor.LoadNameAndType(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), System.Xml.Xsl.IlGen.StorageDescriptor.None(), and System.Xml.Xsl.IlGen.XmlILConstructInfo.Read().