Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitIs
VisitIs()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitIs (QilBinary ndIs) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1048 of file XmlILVisitor.cs.
    {
        NestedVisitEnsureStack(ndIs.Left, ndIs.Right);
        _helper.Call(XmlILMethods.NavSamePos);
        ZeroCompare(QilNodeType.Ne, isBoolVal: true);
        return ndIs;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILMethods.NavSamePos, System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), and System.Xml.Xsl.IlGen.XmlILVisitor.ZeroCompare().