Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitDocumentCtor
VisitDocumentCtor()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitDocumentCtor (QilUnary ndDoc) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1778 of file XmlILVisitor.cs.
    {
        _helper.CallWriteStartRoot();
        NestedVisit(ndDoc.Child);
        _helper.CallWriteEndRoot();
        _iterCurr.Storage = StorageDescriptor.None();
        return ndDoc;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.CallWriteEndRoot(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteStartRoot(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), and System.Xml.Xsl.IlGen.StorageDescriptor.None().