Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.GenerateConcat
GenerateConcat()
void System.Xml.Xsl.IlGen.XmlILVisitor.GenerateConcat (QilNode ndStr, LocalBuilder locStringConcat) inline private
Definition at line 925 of file XmlILVisitor.cs.
    {
        Label lblOnEnd = _helper.DefineLabel();
        StartNestedIterator(ndStr, lblOnEnd);
        Visit(ndStr);
        _iterCurr.EnsureStackNoCache();
        _iterCurr.EnsureItemStorageType(ndStr.XmlType, typeof(string));
        _helper.Call(XmlILMethods.StrCatCat);
        _helper.Emit(OpCodes.Ldloca, locStringConcat);
        _iterCurr.LoopToEnd(lblOnEnd);
        EndNestedIterator(ndStr);
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStackNoCache(), System.Reflection.Emit.OpCodes.Ldloca, System.Xml.Xsl.IlGen.IteratorDescriptor.LoopToEnd(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), System.Xml.Xsl.IlGen.XmlILMethods.StrCatCat, and System.Xml.Xsl.IlGen.XmlILVisitor.Visit().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrConcat().