Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.CreateFilteredIterator
CreateFilteredIterator()
void System.Xml.Xsl.IlGen.XmlILVisitor.CreateFilteredIterator (QilNode ndCtxt, string iterName, Type iterType, MethodInfo methCreate, MethodInfo methNext, MethodInfo methCurrent, XmlNodeKindFlags kinds, QilName ndName, TriState orSelf, QilNode ndEnd) inline private
Definition at line 2480 of file XmlILVisitor.cs.
    {
        LocalBuilder localBuilder = _helper.DeclareLocal(iterName, iterType);
        _helper.Emit(OpCodes.Ldloca, localBuilder);
        NestedVisitEnsureStack(ndCtxt);
        LoadSelectFilter(kinds, ndName);
        if (orSelf != TriState.Unknown)
        {
            _helper.LoadBoolean(orSelf == TriState.True);
        }
        if (ndEnd != null)
        {
            NestedVisitEnsureStack(ndEnd);
        }
        _helper.Call(methCreate);
        GenerateSimpleIterator(typeof(XPathNavigator), localBuilder, methNext, methCurrent);
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator(), System.Reflection.Emit.OpCodes.Ldloca, System.Xml.Xsl.IlGen.GenerateHelper.LoadBoolean(), System.Xml.Xsl.IlGen.XmlILVisitor.LoadSelectFilter(), and System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAncestor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAncestorOrSelf(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDescendant(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDescendantOrSelf(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFollowingSibling(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNodeRange(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitPreceding(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitPrecedingSibling(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathFollowing(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathPreceding().