Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound
VisitXsltInvokeEarlyBound()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound (QilInvokeEarlyBound ndInvoke) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 2213 of file XmlILVisitor.cs.
    {
        QilName name = ndInvoke.Name;
        XmlExtensionFunction xmlExtensionFunction = new XmlExtensionFunction(name.LocalName, name.NamespaceUri, ndInvoke.ClrMethod);
        Type clrReturnType = xmlExtensionFunction.ClrReturnType;
        Type storageType = GetStorageType(ndInvoke);
        if (clrReturnType != storageType && !ndInvoke.XmlType.IsEmpty)
        {
            _helper.LoadQueryRuntime();
            _helper.LoadInteger(_helper.StaticData.DeclareXmlType(ndInvoke.XmlType));
        }
        if (!xmlExtensionFunction.Method.IsStatic)
        {
            if (name.NamespaceUri.Length == 0)
            {
                _helper.LoadXsltLibrary();
            }
            else
            {
                _helper.CallGetEarlyBoundObject(_helper.StaticData.DeclareEarlyBound(name.NamespaceUri, xmlExtensionFunction.Method.DeclaringType), xmlExtensionFunction.Method.DeclaringType);
            }
        }
        for (int i = 0; i < ndInvoke.Arguments.Count; i++)
        {
            QilNode qilNode = ndInvoke.Arguments[i];
            XmlQueryType xmlArgumentType = xmlExtensionFunction.GetXmlArgumentType(i);
            Type clrArgumentType = xmlExtensionFunction.GetClrArgumentType(i);
            if (name.NamespaceUri.Length == 0)
            {
                Type itemStorageType = GetItemStorageType(qilNode);
                if (clrArgumentType == XmlILMethods.StorageMethods[itemStorageType].IListType)
                {
                    NestedVisitEnsureStack(qilNode, itemStorageType, isCached: true);
                }
                else if (clrArgumentType == XmlILMethods.StorageMethods[typeof(XPathItem)].IListType)
                {
                    NestedVisitEnsureStack(qilNode, typeof(XPathItem), isCached: true);
                }
                else if ((qilNode.XmlType.IsSingleton && clrArgumentType == itemStorageType) || qilNode.XmlType.TypeCode == XmlTypeCode.None)
                {
                    NestedVisitEnsureStack(qilNode, clrArgumentType, isCached: false);
                }
                else if (qilNode.XmlType.IsSingleton && clrArgumentType == typeof(XPathItem))
                {
                    NestedVisitEnsureStack(qilNode, typeof(XPathItem), isCached: false);
                }
            }
            else
            {
                Type storageType2 = GetStorageType(xmlArgumentType);
                if (xmlArgumentType.TypeCode == XmlTypeCode.Item || !clrArgumentType.IsAssignableFrom(storageType2))
                {
                    _helper.LoadQueryRuntime();
                    _helper.LoadInteger(_helper.StaticData.DeclareXmlType(xmlArgumentType));
                    NestedVisitEnsureStack(qilNode, GetItemStorageType(xmlArgumentType), !xmlArgumentType.IsSingleton);
                    _helper.TreatAs(storageType2, typeof(object));
                    _helper.LoadType(clrArgumentType);
                    _helper.Call(XmlILMethods.ChangeTypeXsltArg);
                    _helper.TreatAs(typeof(object), clrArgumentType);
                }
                else
                {
                    NestedVisitEnsureStack(qilNode, GetItemStorageType(xmlArgumentType), !xmlArgumentType.IsSingleton);
                }
            }
        }
        _helper.Call(xmlExtensionFunction.Method);
        if (ndInvoke.XmlType.IsEmpty)
        {
            _helper.Emit(OpCodes.Ldsfld, XmlILMethods.StorageMethods[typeof(XPathItem)].SeqEmpty);
        }
        else if (clrReturnType != storageType)
        {
            _helper.TreatAs(clrReturnType, typeof(object));
            _helper.Call(XmlILMethods.ChangeTypeXsltResult);
            _helper.TreatAs(typeof(object), storageType);
        }
        else if (name.NamespaceUri.Length != 0 && !clrReturnType.IsValueType)
        {
            Label label = _helper.DefineLabel();
            _helper.Emit(OpCodes.Dup);
            _helper.Emit(OpCodes.Brtrue, label);
            _helper.LoadQueryRuntime();
            _helper.Emit(OpCodes.Ldstr, System.SR.Xslt_ItemNull);
            _helper.Call(XmlILMethods.ThrowException);
            _helper.MarkLabel(label);
        }
        _iterCurr.Storage = StorageDescriptor.Stack(GetItemStorageType(ndInvoke), !ndInvoke.XmlType.IsSingleton);
        return ndInvoke;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Reflection.Emit.OpCodes.Brtrue, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetEarlyBoundObject(), System.Xml.Xsl.IlGen.XmlILMethods.ChangeTypeXsltArg, System.Xml.Xsl.IlGen.XmlILMethods.ChangeTypeXsltResult, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.IlGen.StaticDataManager.DeclareEarlyBound(), System.Xml.Xsl.IlGen.StaticDataManager.DeclareXmlType(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Reflection.Emit.OpCodes.Dup, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.IlGen.XmlILVisitor.GetStorageType(), System.Reflection.Emit.OpCodes.Ldsfld, System.Reflection.Emit.OpCodes.Ldstr, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.GenerateHelper.LoadType(), System.Xml.Xsl.IlGen.GenerateHelper.LoadXsltLibrary(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Xml.Xsl.IlGen.GenerateHelper.StaticData, System.Xml.Xsl.IlGen.XmlILMethods.StorageMethods, System.Xml.Xsl.IlGen.XmlILMethods.ThrowException, System.Xml.Xsl.IlGen.GenerateHelper.TreatAs(), and System.SR.Xslt_ItemNull.