Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitTypeAssert
VisitTypeAssert()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitTypeAssert (QilTargetType ndTypeAssert) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1876 of file XmlILVisitor.cs.
    {
        if (!ndTypeAssert.Source.XmlType.IsSingleton && ndTypeAssert.XmlType.IsSingleton && !_iterCurr.HasLabelNext)
        {
            Label label = _helper.DefineLabel();
            _helper.MarkLabel(label);
            NestedVisit(ndTypeAssert.Source, label);
        }
        else
        {
            Visit(ndTypeAssert.Source);
        }
        _iterCurr.EnsureItemStorageType(ndTypeAssert.Source.XmlType, GetItemStorageType(ndTypeAssert));
        return ndTypeAssert;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.HasLabelNext, System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), and System.Xml.Xsl.IlGen.XmlILVisitor.Visit().