Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.CopySequence
CopySequence()
void System.Xml.Xsl.IlGen.XmlILVisitor.CopySequence (QilNode nd) inline private
Definition at line 207 of file XmlILVisitor.cs.
    {
        XmlQueryType xmlType = nd.XmlType;
        StartWriterLoop(nd, out var hasOnEnd, out var lblOnEnd);
        if (xmlType.IsSingleton)
        {
            _helper.LoadQueryOutput();
            base.Visit(nd);
            _iterCurr.EnsureItemStorageType(nd.XmlType, typeof(XPathItem));
        }
        else
        {
            base.Visit(nd);
            _iterCurr.EnsureItemStorageType(nd.XmlType, typeof(XPathItem));
            _iterCurr.EnsureNoStackNoCache("$$$copyTemp");
            _helper.LoadQueryOutput();
        }
        _iterCurr.EnsureStackNoCache();
        _helper.Call(XmlILMethods.WriteItem);
        EndWriterLoop(nd, hasOnEnd, lblOnEnd);
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.XmlILVisitor.EndWriterLoop(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoStackNoCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStackNoCache(), System.Xml.Xsl.XmlQueryType.IsSingleton, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryOutput(), System.Xml.Xsl.IlGen.XmlILVisitor.StartWriterLoop(), and System.Xml.Xsl.IlGen.XmlILMethods.WriteItem.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.Visit().