Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.BeforeStartChecks
BeforeStartChecks()
void System.Xml.Xsl.IlGen.XmlILVisitor.BeforeStartChecks (QilNode ndCtor) inline private
Definition at line 2815 of file XmlILVisitor.cs.
    {
        switch (XmlILConstructInfo.Read(ndCtor).InitialStates)
        {
        case PossibleXmlStates.WithinSequence:
            _helper.CallStartTree(QilConstructorToNodeType(ndCtor.NodeType));
            break;
        case PossibleXmlStates.EnumAttrs:
        {
            QilNodeType nodeType = ndCtor.NodeType;
            if (nodeType == QilNodeType.ElementCtor || (uint)(nodeType - 83) <= 3u)
            {
                _helper.CallStartElementContent();
            }
            break;
        }
        }
    }
References System.Xml.Xsl.IlGen.XmlILConstructInfo.Read().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttributeCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitElementCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNamespaceDecl(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitTextCtor().