Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.ClrCompare
ClrCompare()
void System.Xml.Xsl.IlGen.XmlILVisitor.ClrCompare (QilNodeType relOp, XmlTypeCode code) inline private
Definition at line 2671 of file XmlILVisitor.cs.
    {
        OpCode opcode;
        switch (_iterCurr.CurrentBranchingContext)
        {
        case BranchingContext.OnFalse:
            opcode = ((code == XmlTypeCode.Double || code == XmlTypeCode.Float) ? (relOp switch
            {
                QilNodeType.Gt => OpCodes.Ble_Un,
                QilNodeType.Ge => OpCodes.Blt_Un,
                QilNodeType.Lt => OpCodes.Bge_Un,
                QilNodeType.Le => OpCodes.Bgt_Un,
                QilNodeType.Eq => OpCodes.Bne_Un,
                QilNodeType.Ne => OpCodes.Beq,
                _ => OpCodes.Nop,
            }) : (relOp switch
            {
                QilNodeType.Gt => OpCodes.Ble,
                QilNodeType.Ge => OpCodes.Blt,
                QilNodeType.Lt => OpCodes.Bge,
                QilNodeType.Le => OpCodes.Bgt,
                QilNodeType.Eq => OpCodes.Bne_Un,
                QilNodeType.Ne => OpCodes.Beq,
                _ => OpCodes.Nop,
            }));
            _helper.Emit(opcode, _iterCurr.LabelBranch);
            _iterCurr.Storage = StorageDescriptor.None();
            return;
        case BranchingContext.OnTrue:
            opcode = relOp switch
            {
                QilNodeType.Gt => OpCodes.Bgt,
                QilNodeType.Ge => OpCodes.Bge,
                QilNodeType.Lt => OpCodes.Blt,
                QilNodeType.Le => OpCodes.Ble,
                QilNodeType.Eq => OpCodes.Beq,
                QilNodeType.Ne => OpCodes.Bne_Un,
                _ => OpCodes.Nop,
            };
            _helper.Emit(opcode, _iterCurr.LabelBranch);
            _iterCurr.Storage = StorageDescriptor.None();
            return;
        }
        Label label;
        switch (relOp)
        {
        case QilNodeType.Gt:
            _helper.Emit(OpCodes.Cgt);
            break;
        case QilNodeType.Lt:
            _helper.Emit(OpCodes.Clt);
            break;
        case QilNodeType.Eq:
            _helper.Emit(OpCodes.Ceq);
            break;
        case QilNodeType.Ge:
            opcode = OpCodes.Bge_S;
            goto IL_0207;
        case QilNodeType.Le:
            opcode = OpCodes.Ble_S;
            goto IL_0207;
        case QilNodeType.Ne:
            opcode = OpCodes.Bne_Un_S;
            goto IL_0207;
        default:
            {
                opcode = OpCodes.Nop;
                goto IL_0207;
            }
            IL_0207:
            label = _helper.DefineLabel();
            _helper.Emit(opcode, label);
            _helper.ConvBranchToBool(label, isTrueBranch: true);
            break;
        }
        _iterCurr.Storage = StorageDescriptor.Stack(typeof(bool), isCached: false);
    }
References System.Reflection.Emit.OpCodes.Beq, System.Reflection.Emit.OpCodes.Bge, System.Reflection.Emit.OpCodes.Bge_S, System.Reflection.Emit.OpCodes.Bge_Un, System.Reflection.Emit.OpCodes.Bgt, System.Reflection.Emit.OpCodes.Bgt_Un, System.Reflection.Emit.OpCodes.Ble, System.Reflection.Emit.OpCodes.Ble_S, System.Reflection.Emit.OpCodes.Ble_Un, System.Reflection.Emit.OpCodes.Blt, System.Reflection.Emit.OpCodes.Blt_Un, System.Reflection.Emit.OpCodes.Bne_Un, System.Reflection.Emit.OpCodes.Bne_Un_S, System.Reflection.Emit.OpCodes.Ceq, System.Reflection.Emit.OpCodes.Cgt, System.Reflection.Emit.OpCodes.Clt, System.Xml.Dictionary, System.Xml.Xsl.IlGen.StorageDescriptor.None(), System.Reflection.Emit.OpCodes.Nop, and System.Xml.Xsl.IlGen.StorageDescriptor.Stack().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.Compare(), System.Xml.Xsl.IlGen.XmlILVisitor.ComparePosition(), and System.Xml.Xsl.IlGen.XmlILVisitor.MatchesNodeKinds().