Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopyOf
VisitXsltCopyOf()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopyOf (QilUnary ndCopyOf) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 2320 of file XmlILVisitor.cs.
    {
        _helper.LoadQueryOutput();
        NestedVisitEnsureStack(ndCopyOf.Child);
        _helper.Call(XmlILMethods.CopyOf);
        _iterCurr.Storage = StorageDescriptor.None();
        return ndCopyOf;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.XmlILMethods.CopyOf, System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryOutput(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), and System.Xml.Xsl.IlGen.StorageDescriptor.None().