Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitInvoke
VisitInvoke()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitInvoke (QilInvoke ndInvoke) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1522 of file XmlILVisitor.cs.
    {
        QilFunction function = ndInvoke.Function;
        MethodInfo functionBinding = XmlILAnnotation.Write(function).FunctionBinding;
        bool flag = XmlILConstructInfo.Read(function).ConstructMethod == XmlILConstructMethod.Writer;
        _helper.LoadQueryRuntime();
        for (int i = 0; i < ndInvoke.Arguments.Count; i++)
        {
            QilNode nd = ndInvoke.Arguments[i];
            QilNode qilNode = ndInvoke.Function.Arguments[i];
            NestedVisitEnsureStack(nd, GetItemStorageType(qilNode), !qilNode.XmlType.IsSingleton);
        }
        if (OptimizerPatterns.Read(ndInvoke).MatchesPattern(OptimizerPatternName.TailCall))
        {
            _helper.TailCall(functionBinding);
        }
        else
        {
            _helper.Call(functionBinding);
        }
        if (!flag)
        {
            _iterCurr.Storage = StorageDescriptor.Stack(GetItemStorageType(ndInvoke), !ndInvoke.XmlType.IsSingleton);
        }
        else
        {
            _iterCurr.Storage = StorageDescriptor.None();
        }
        return ndInvoke;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.StorageDescriptor.None(), System.Xml.Xsl.IlGen.OptimizerPatterns.Read(), System.Xml.Xsl.IlGen.XmlILConstructInfo.Read(), System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Xml.Xsl.IlGen.GenerateHelper.TailCall(), and System.Xml.Xsl.IlGen.XmlILAnnotation.Write().