Terraria: PlayerFileData.StopPlayTimer
StopPlayTimer()
void PlayerFileData.StopPlayTimer () inline
     {
         if (_isTimerActive)
         {
             _isTimerActive = false;
             if (_timer.IsRunning)
             {
                 _playTime += _timer.Elapsed;
                 _timer.Reset();
             }
         }
     }
References _isTimerActive, _playTime, and _timer.
Referenced by Netplay.InnerClientLoop(), WorldGen.JustQuit(), PausePlayTimer(), and WorldGen.SaveAndQuitCallBack().