Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.CreateSimpleIterator
CreateSimpleIterator()
void System.Xml.Xsl.IlGen.XmlILVisitor.CreateSimpleIterator (QilNode ndCtxt, string iterName, Type iterType, MethodInfo methCreate, MethodInfo methNext, MethodInfo methCurrent) inline private
Definition at line 2471 of file XmlILVisitor.cs.
    {
        LocalBuilder localBuilder = _helper.DeclareLocal(iterName, iterType);
        _helper.Emit(OpCodes.Ldloca, localBuilder);
        NestedVisitEnsureStack(ndCtxt);
        _helper.Call(methCreate);
        GenerateSimpleIterator(typeof(XPathNavigator), localBuilder, methNext, methCurrent);
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator(), System.Reflection.Emit.OpCodes.Ldloca, and System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitContent(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNamespace().