Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitCommentCtor
VisitCommentCtor()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitCommentCtor (QilUnary ndComment) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1714 of file XmlILVisitor.cs.
    {
        _helper.CallWriteStartComment();
        NestedVisit(ndComment.Child);
        _helper.CallWriteEndComment();
        _iterCurr.Storage = StorageDescriptor.None();
        return ndComment;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.CallWriteEndComment(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteStartComment(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), and System.Xml.Xsl.IlGen.StorageDescriptor.None().