Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator
GenerateSimpleIterator()
void System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator (Type itemStorageType, LocalBuilder locIter, MethodInfo methNext, MethodInfo methCurrent) inline private
Definition at line 2518 of file XmlILVisitor.cs.
    {
        Label label = _helper.DefineLabel();
        _helper.MarkLabel(label);
        _helper.Emit(OpCodes.Ldloca, locIter);
        _helper.Call(methNext);
        _helper.Emit(OpCodes.Brfalse, _iterCurr.GetLabelNext());
        _iterCurr.SetIterator(label, StorageDescriptor.Current(locIter, methCurrent, itemStorageType));
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Reflection.Emit.OpCodes.Brfalse, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.StorageDescriptor.Current(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.IteratorDescriptor.GetLabelNext(), System.Reflection.Emit.OpCodes.Ldloca, System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), and System.Xml.Xsl.IlGen.IteratorDescriptor.SetIterator().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.CreateFilteredIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSimpleIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitDeref().