Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitEmpty
VisitEmpty()
void System.Xml.Xsl.IlGen.XmlILVisitor.VisitEmpty (QilNode nd) inline private
Definition at line 649 of file XmlILVisitor.cs.
    {
        _helper.EmitUnconditionalBranch(OpCodes.Brtrue, _iterCurr.GetLabelNext());
        _helper.Emit(OpCodes.Ldnull);
        _iterCurr.Storage = StorageDescriptor.Stack(typeof(XPathItem), isCached: false);
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Reflection.Emit.OpCodes.Brtrue, System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Xml.Xsl.IlGen.IteratorDescriptor.GetLabelNext(), System.Reflection.Emit.OpCodes.Ldnull, and System.Xml.Xsl.IlGen.StorageDescriptor.Stack().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitSequence(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitWarning().