Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound
VisitXsltInvokeLateBound()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound (QilInvokeLateBound ndInvoke) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 2186 of file XmlILVisitor.cs.
    {
        LocalBuilder locBldr = _helper.DeclareLocal("$$$args", typeof(IList<XPathItem>[]));
        QilName name = ndInvoke.Name;
        _helper.LoadQueryContext();
        _helper.Emit(OpCodes.Ldstr, name.LocalName);
        _helper.Emit(OpCodes.Ldstr, name.NamespaceUri);
        _helper.LoadInteger(ndInvoke.Arguments.Count);
        _helper.Emit(OpCodes.Newarr, typeof(IList<XPathItem>));
        _helper.Emit(OpCodes.Stloc, locBldr);
        for (int i = 0; i < ndInvoke.Arguments.Count; i++)
        {
            QilNode nd = ndInvoke.Arguments[i];
            _helper.Emit(OpCodes.Ldloc, locBldr);
            _helper.LoadInteger(i);
            _helper.Emit(OpCodes.Ldelema, typeof(IList<XPathItem>));
            NestedVisitEnsureCache(nd, typeof(XPathItem));
            _iterCurr.EnsureStack();
            _helper.Emit(OpCodes.Stobj, typeof(IList<XPathItem>));
        }
        _helper.Emit(OpCodes.Ldloc, locBldr);
        _helper.Call(XmlILMethods.InvokeXsltLate);
        _iterCurr.Storage = StorageDescriptor.Stack(typeof(XPathItem), isCached: true);
        return ndInvoke;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStack(), System.Xml.Xsl.IlGen.XmlILMethods.InvokeXsltLate, System.Reflection.Emit.OpCodes.Ldelema, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldstr, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryContext(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureCache(), System.Reflection.Emit.OpCodes.Newarr, System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Reflection.Emit.OpCodes.Stloc, and System.Reflection.Emit.OpCodes.Stobj.