Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.Function
Function()
void System.Xml.Xsl.IlGen.XmlILVisitor.Function (QilFunction ndFunc) inline private
Definition at line 122 of file XmlILVisitor.cs.
    {
        foreach (QilIterator argument in ndFunc.Arguments)
        {
            IteratorDescriptor iteratorDescriptor = new IteratorDescriptor(_helper);
            int paramIndex = XmlILAnnotation.Write(argument).ArgumentPosition + 1;
            iteratorDescriptor.Storage = StorageDescriptor.Parameter(paramIndex, GetItemStorageType(argument), !argument.XmlType.IsSingleton);
            XmlILAnnotation.Write(argument).CachedIteratorDescriptor = iteratorDescriptor;
        }
        MethodInfo functionBinding = XmlILAnnotation.Write(ndFunc).FunctionBinding;
        bool flag = XmlILConstructInfo.Read(ndFunc).ConstructMethod == XmlILConstructMethod.Writer;
        _helper.MethodBegin(functionBinding, ndFunc.SourceLine, flag);
        foreach (QilIterator argument2 in ndFunc.Arguments)
        {
            if (_qil.IsDebug && argument2.SourceLine != null)
            {
                _helper.DebugSequencePoint(argument2.SourceLine);
            }
            if (argument2.Binding != null)
            {
                int paramIndex = (argument2.Annotation as XmlILAnnotation).ArgumentPosition + 1;
                Label label = _helper.DefineLabel();
                _helper.LoadQueryRuntime();
                _helper.LoadParameter(paramIndex);
                _helper.LoadInteger(29);
                _helper.Call(XmlILMethods.SeqMatchesCode);
                _helper.Emit(OpCodes.Brfalse, label);
                StartNestedIterator(argument2);
                NestedVisitEnsureStack(argument2.Binding, GetItemStorageType(argument2), !argument2.XmlType.IsSingleton);
                EndNestedIterator(argument2);
                _helper.SetParameter(paramIndex);
                _helper.MarkLabel(label);
            }
        }
        StartNestedIterator(ndFunc);
        if (flag)
        {
            NestedVisit(ndFunc.Definition);
        }
        else
        {
            NestedVisitEnsureStack(ndFunc.Definition, GetItemStorageType(ndFunc), !ndFunc.XmlType.IsSingleton);
        }
        EndNestedIterator(ndFunc);
        _helper.MethodEnd();
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._qil, System.Reflection.Emit.OpCodes.Brfalse, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DebugSequencePoint(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.Qil.QilExpression.IsDebug, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.GenerateHelper.LoadParameter(), System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin(), System.Xml.Xsl.IlGen.GenerateHelper.MethodEnd(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.StorageDescriptor.Parameter(), System.Xml.Xsl.IlGen.XmlILConstructInfo.Read(), System.Xml.Xsl.IlGen.XmlILMethods.SeqMatchesCode, System.Xml.Xsl.IlGen.GenerateHelper.SetParameter(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), and System.Xml.Xsl.IlGen.XmlILAnnotation.Write().