Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.ConditionalBranch
ConditionalBranch()
void System.Xml.Xsl.IlGen.XmlILVisitor.ConditionalBranch (QilNode ndBranch, Type itemStorageType, LocalBuilder locResult) inline private
Definition at line 549 of file XmlILVisitor.cs.
    {
        if (locResult == null)
        {
            if (_iterCurr.IsBranching)
            {
                NestedVisitWithBranch(ndBranch, _iterCurr.CurrentBranchingContext, _iterCurr.LabelBranch);
            }
            else
            {
                NestedVisitEnsureStack(ndBranch, itemStorageType, isCached: false);
            }
        }
        else
        {
            NestedVisit(ndBranch, _iterCurr.GetLabelNext());
            _iterCurr.EnsureItemStorageType(ndBranch.XmlType, itemStorageType);
            _iterCurr.EnsureLocalNoCache(locResult);
        }
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.IteratorDescriptor.CurrentBranchingContext, System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureLocalNoCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.GetLabelNext(), System.Xml.Xsl.IlGen.IteratorDescriptor.IsBranching, System.Xml.Xsl.IlGen.IteratorDescriptor.LabelBranch, System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), and System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitWithBranch().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional().