Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitRtfCtor
VisitRtfCtor()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitRtfCtor (QilBinary ndRtf) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1807 of file XmlILVisitor.cs.
    {
        OptimizerPatterns optimizerPatterns = OptimizerPatterns.Read(ndRtf);
        string text = (QilLiteral)ndRtf.Right;
        if (optimizerPatterns.MatchesPattern(OptimizerPatternName.SingleTextRtf))
        {
            _helper.LoadQueryRuntime();
            NestedVisitEnsureStack((QilNode)optimizerPatterns.GetArgument(OptimizerPatternArgument.ElementQName));
            _helper.Emit(OpCodes.Ldstr, text);
            _helper.Call(XmlILMethods.RtfConstr);
        }
        else
        {
            _helper.CallStartRtfConstruction(text);
            NestedVisit(ndRtf.Left);
            _helper.CallEndRtfConstruction();
        }
        _iterCurr.Storage = StorageDescriptor.Stack(typeof(XPathNavigator), isCached: false);
        return ndRtf;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.CallEndRtfConstruction(), System.Xml.Xsl.IlGen.GenerateHelper.CallStartRtfConstruction(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Reflection.Emit.OpCodes.Ldstr, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.OptimizerPatterns.Read(), System.Xml.Xsl.IlGen.XmlILMethods.RtfConstr, System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), and System.text.