Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator
CreateAggregator()
QilNode System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator (QilUnary ndAgg, string aggName, XmlILStorageMethods methods, MethodInfo methAgg, MethodInfo methResult) inline private
Definition at line 788 of file XmlILVisitor.cs.
    {
        Label lblOnEnd = _helper.DefineLabel();
        Type declaringType = methAgg.DeclaringType;
        LocalBuilder locBldr = _helper.DeclareLocal(aggName, declaringType);
        _helper.Emit(OpCodes.Ldloca, locBldr);
        _helper.Call(methods.AggCreate);
        StartNestedIterator(ndAgg.Child, lblOnEnd);
        _helper.Emit(OpCodes.Ldloca, locBldr);
        Visit(ndAgg.Child);
        _iterCurr.EnsureStackNoCache();
        _iterCurr.EnsureItemStorageType(ndAgg.XmlType, GetItemStorageType(ndAgg));
        _helper.Call(methAgg);
        _helper.Emit(OpCodes.Ldloca, locBldr);
        _iterCurr.LoopToEnd(lblOnEnd);
        EndNestedIterator(ndAgg.Child);
        if (ndAgg.XmlType.MaybeEmpty)
        {
            _helper.Call(methods.AggIsEmpty);
            _helper.Emit(OpCodes.Brtrue, _iterCurr.GetLabelNext());
            _helper.Emit(OpCodes.Ldloca, locBldr);
        }
        _helper.Call(methResult);
        _iterCurr.Storage = StorageDescriptor.Stack(GetItemStorageType(ndAgg), isCached: false);
        return ndAgg;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Reflection.Emit.OpCodes.Brtrue, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStackNoCache(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.GetLabelNext(), System.Reflection.Emit.OpCodes.Ldloca, System.Xml.Xsl.IlGen.IteratorDescriptor.LoopToEnd(), System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), and System.Xml.Xsl.IlGen.XmlILVisitor.Visit().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitAverage(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitMaximum(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitMinimum(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitSum().