Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator
GenerateContainerIterator()
void System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator (QilNode nd, LocalBuilder locIter, Label lblOnEndNested, MethodInfo methNext, MethodInfo methCurrent, Type itemStorageType) inline private
Definition at line 2528 of file XmlILVisitor.cs.
    {
        Label label = _helper.DefineLabel();
        _iterCurr.EnsureNoStackNoCache(nd.XmlType.IsNode ? "$$$navInput" : "$$$itemInput");
        _helper.Emit(OpCodes.Ldloca, locIter);
        _iterCurr.PushValue();
        _helper.EmitUnconditionalBranch(OpCodes.Br, label);
        _helper.MarkLabel(lblOnEndNested);
        _helper.Emit(OpCodes.Ldloca, locIter);
        _helper.Emit(OpCodes.Ldnull);
        _helper.MarkLabel(label);
        _helper.Call(methNext);
        if (nd.XmlType.IsSingleton)
        {
            _helper.LoadInteger(1);
            _helper.Emit(OpCodes.Beq, _iterNested.GetLabelNext());
            _iterCurr.Storage = StorageDescriptor.Current(locIter, methCurrent, itemStorageType);
        }
        else
        {
            _helper.Emit(OpCodes.Switch, new Label[2]
            {
                _iterCurr.GetLabelNext(),
                _iterNested.GetLabelNext()
            });
            _iterCurr.SetIterator(lblOnEndNested, StorageDescriptor.Current(locIter, methCurrent, itemStorageType));
        }
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.Reflection.Emit.OpCodes.Beq, System.Reflection.Emit.OpCodes.Br, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.StorageDescriptor.Current(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoStackNoCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.GetLabelNext(), System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.OpCodes.Ldnull, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.IteratorDescriptor.PushValue(), System.Xml.Xsl.IlGen.IteratorDescriptor.SetIterator(), and System.Reflection.Emit.OpCodes.Switch.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator().