Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltConvert
VisitXsltConvert()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltConvert (QilTargetType ndConv) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 2329 of file XmlILVisitor.cs.
    {
        XmlQueryType xmlType = ndConv.Source.XmlType;
        XmlQueryType targetType = ndConv.TargetType;
        if (GetXsltConvertMethod(xmlType, targetType, out var meth))
        {
            NestedVisitEnsureStack(ndConv.Source);
        }
        else
        {
            NestedVisitEnsureStack(ndConv.Source, typeof(XPathItem), !xmlType.IsSingleton);
            GetXsltConvertMethod(xmlType.IsSingleton ? XmlQueryTypeFactory.Item : XmlQueryTypeFactory.ItemS, targetType, out meth);
        }
        if (meth != null)
        {
            _helper.Call(meth);
        }
        _iterCurr.Storage = StorageDescriptor.Stack(GetItemStorageType(targetType), !targetType.IsSingleton);
        return ndConv;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.IlGen.XmlILVisitor.GetXsltConvertMethod(), System.Xml.Xsl.XmlQueryType.IsSingleton, System.Xml.Xsl.XmlQueryTypeFactory.Item, System.Xml.Xsl.XmlQueryTypeFactory.ItemS, System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), and System.Xml.Xsl.IlGen.StorageDescriptor.Stack().