Terraria: PlayerFileData.UpdatePlayTimer
UpdatePlayTimer()
void PlayerFileData.UpdatePlayTimer () inline
     {
         bool flag = Main.gamePaused && !Main.hasFocus;
         bool flag2 = Main.instance.IsActive && !flag;
         if (Main.gameMenu)
         {
             flag2 = false;
         }
         if (flag2)
         {
             StartPlayTimer();
         }
         else
         {
             PausePlayTimer();
         }
     }
References Main.gameMenu, Main.gamePaused, Main.hasFocus, Main.instance, Game.IsActive, PausePlayTimer(), and StartPlayTimer().
Referenced by Main.DoUpdate().