Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding
StartForBinding()
void System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding (QilIterator ndFor, OptimizerPatterns patt) inline private
Definition at line 1270 of file XmlILVisitor.cs.
    {
        LocalBuilder localBuilder = null;
        if (_iterCurr.HasLabelNext)
        {
            StartNestedIterator(ndFor.Binding, _iterCurr.GetLabelNext());
        }
        else
        {
            StartNestedIterator(ndFor.Binding);
        }
        if (patt.MatchesPattern(OptimizerPatternName.IsPositional))
        {
            localBuilder = _helper.DeclareLocal("$$$pos", typeof(int));
            _helper.Emit(OpCodes.Ldc_I4_0);
            _helper.Emit(OpCodes.Stloc, localBuilder);
        }
        Visit(ndFor.Binding);
        if (_qil.IsDebug && ndFor.DebugName != null)
        {
            _helper.DebugStartScope();
            _iterCurr.EnsureLocalNoCache("$$$for");
        }
        else
        {
            _iterCurr.EnsureNoStackNoCache("$$$for");
        }
        if (patt.MatchesPattern(OptimizerPatternName.IsPositional))
        {
            _helper.Emit(OpCodes.Ldloc, localBuilder);
            _helper.Emit(OpCodes.Ldc_I4_1);
            _helper.Emit(OpCodes.Add);
            _helper.Emit(OpCodes.Stloc, localBuilder);
            if (patt.MatchesPattern(OptimizerPatternName.MaxPosition))
            {
                _helper.Emit(OpCodes.Ldloc, localBuilder);
                _helper.LoadInteger((int)patt.GetArgument(OptimizerPatternArgument.ElementQName));
                _helper.Emit(OpCodes.Bgt, _iterCurr.ParentIterator.GetLabelNext());
            }
            _iterCurr.LocalPosition = localBuilder;
        }
        EndNestedIterator(ndFor.Binding);
        _iterCurr.SetIterator(_iterNested);
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.Xml.Xsl.IlGen.XmlILVisitor._qil, System.Reflection.Emit.OpCodes.Add, System.Reflection.Emit.OpCodes.Bgt, System.Xml.Xsl.IlGen.GenerateHelper.DebugStartScope(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureLocalNoCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoStackNoCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.GetLabelNext(), System.Xml.Xsl.IlGen.IteratorDescriptor.HasLabelNext, System.Xml.Xsl.Qil.QilExpression.IsDebug, System.Reflection.Emit.OpCodes.Ldc_I4_0, System.Reflection.Emit.OpCodes.Ldc_I4_1, System.Reflection.Emit.OpCodes.Ldloc, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.IteratorDescriptor.ParentIterator, System.Xml.Xsl.IlGen.IteratorDescriptor.SetIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), System.Reflection.Emit.OpCodes.Stloc, and System.Xml.Xsl.IlGen.XmlILVisitor.Visit().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.StartBinding().