Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator
CreateContainerIterator()
void System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator (QilUnary ndDod, string iterName, Type iterType, MethodInfo methCreate, MethodInfo methNext, MethodInfo methCurrent, XmlNodeKindFlags kinds, QilName ndName, TriState orSelf) inline private
Definition at line 2498 of file XmlILVisitor.cs.
    {
        LocalBuilder localBuilder = _helper.DeclareLocal(iterName, iterType);
        QilLoop qilLoop = (QilLoop)ndDod.Child;
        _helper.Emit(OpCodes.Ldloca, localBuilder);
        LoadSelectFilter(kinds, ndName);
        if (orSelf != TriState.Unknown)
        {
            _helper.LoadBoolean(orSelf == TriState.True);
        }
        _helper.Call(methCreate);
        Label label = _helper.DefineLabel();
        StartNestedIterator(qilLoop, label);
        StartBinding(qilLoop.Variable);
        EndBinding(qilLoop.Variable);
        EndNestedIterator(qilLoop.Variable);
        _iterCurr.Storage = _iterNested.Storage;
        GenerateContainerIterator(ndDod, localBuilder, label, methNext, methCurrent, typeof(XPathNavigator));
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.EndBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator(), System.Reflection.Emit.OpCodes.Ldloca, System.Xml.Xsl.IlGen.GenerateHelper.LoadBoolean(), System.Xml.Xsl.IlGen.XmlILVisitor.LoadSelectFilter(), System.Xml.Xsl.IlGen.XmlILVisitor.StartBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), and System.Xml.Xsl.IlGen.IteratorDescriptor.Storage.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns().