Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns
HandleDodPatterns()
bool System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns (QilUnary ndDod) inline private
Definition at line 1435 of file XmlILVisitor.cs.
    {
        OptimizerPatterns optimizerPatterns = OptimizerPatterns.Read(ndDod);
        bool flag = optimizerPatterns.MatchesPattern(OptimizerPatternName.JoinAndDod);
        if (flag || optimizerPatterns.MatchesPattern(OptimizerPatternName.DodReverse))
        {
            OptimizerPatterns optimizerPatterns2 = OptimizerPatterns.Read((QilNode)optimizerPatterns.GetArgument(OptimizerPatternArgument.ElementQName));
            XmlNodeKindFlags kinds;
            QilName ndName;
            if (optimizerPatterns2.MatchesPattern(OptimizerPatternName.FilterElements))
            {
                kinds = XmlNodeKindFlags.Element;
                ndName = (QilName)optimizerPatterns2.GetArgument(OptimizerPatternArgument.ElementQName);
            }
            else if (optimizerPatterns2.MatchesPattern(OptimizerPatternName.FilterContentKind))
            {
                kinds = ((XmlQueryType)optimizerPatterns2.GetArgument(OptimizerPatternArgument.ElementQName)).NodeKinds;
                ndName = null;
            }
            else
            {
                kinds = (((ndDod.XmlType.NodeKinds & XmlNodeKindFlags.Attribute) != 0) ? XmlNodeKindFlags.Any : XmlNodeKindFlags.Content);
                ndName = null;
            }
            QilNode qilNode = (QilNode)optimizerPatterns2.GetArgument(OptimizerPatternArgument.StepNode);
            if (flag)
            {
                switch (qilNode.NodeType)
                {
                case QilNodeType.Content:
                    CreateContainerIterator(ndDod, "$$$iterContent", typeof(ContentMergeIterator), XmlILMethods.ContentMergeCreate, XmlILMethods.ContentMergeNext, XmlILMethods.ContentMergeCurrent, kinds, ndName, TriState.Unknown);
                    return true;
                case QilNodeType.Descendant:
                case QilNodeType.DescendantOrSelf:
                    CreateContainerIterator(ndDod, "$$$iterDesc", typeof(DescendantMergeIterator), XmlILMethods.DescMergeCreate, XmlILMethods.DescMergeNext, XmlILMethods.DescMergeCurrent, kinds, ndName, (qilNode.NodeType != QilNodeType.Descendant) ? TriState.True : TriState.False);
                    return true;
                case QilNodeType.XPathFollowing:
                    CreateContainerIterator(ndDod, "$$$iterFoll", typeof(XPathFollowingMergeIterator), XmlILMethods.XPFollMergeCreate, XmlILMethods.XPFollMergeNext, XmlILMethods.XPFollMergeCurrent, kinds, ndName, TriState.Unknown);
                    return true;
                case QilNodeType.FollowingSibling:
                    CreateContainerIterator(ndDod, "$$$iterFollSib", typeof(FollowingSiblingMergeIterator), XmlILMethods.FollSibMergeCreate, XmlILMethods.FollSibMergeNext, XmlILMethods.FollSibMergeCurrent, kinds, ndName, TriState.Unknown);
                    return true;
                case QilNodeType.XPathPreceding:
                    CreateContainerIterator(ndDod, "$$$iterPrec", typeof(XPathPrecedingMergeIterator), XmlILMethods.XPPrecMergeCreate, XmlILMethods.XPPrecMergeNext, XmlILMethods.XPPrecMergeCurrent, kinds, ndName, TriState.Unknown);
                    return true;
                }
            }
            else
            {
                QilNode ndCtxt = (QilNode)optimizerPatterns2.GetArgument(OptimizerPatternArgument.StepInput);
                switch (qilNode.NodeType)
                {
                case QilNodeType.Ancestor:
                case QilNodeType.AncestorOrSelf:
                    CreateFilteredIterator(ndCtxt, "$$$iterAnc", typeof(AncestorDocOrderIterator), XmlILMethods.AncDOCreate, XmlILMethods.AncDONext, XmlILMethods.AncDOCurrent, kinds, ndName, (qilNode.NodeType != QilNodeType.Ancestor) ? TriState.True : TriState.False, null);
                    return true;
                case QilNodeType.PrecedingSibling:
                    CreateFilteredIterator(ndCtxt, "$$$iterPreSib", typeof(PrecedingSiblingDocOrderIterator), XmlILMethods.PreSibDOCreate, XmlILMethods.PreSibDONext, XmlILMethods.PreSibDOCurrent, kinds, ndName, TriState.Unknown, null);
                    return true;
                case QilNodeType.XPathPreceding:
                    CreateFilteredIterator(ndCtxt, "$$$iterPrec", typeof(XPathPrecedingDocOrderIterator), XmlILMethods.XPPrecDOCreate, XmlILMethods.XPPrecDONext, XmlILMethods.XPPrecDOCurrent, kinds, ndName, TriState.Unknown, null);
                    return true;
                }
            }
        }
        else if (optimizerPatterns.MatchesPattern(OptimizerPatternName.DodMerge))
        {
            LocalBuilder locBldr = _helper.DeclareLocal("$$$dodMerge", typeof(DodSequenceMerge));
            Label lblOnEnd = _helper.DefineLabel();
            _helper.Emit(OpCodes.Ldloca, locBldr);
            _helper.LoadQueryRuntime();
            _helper.Call(XmlILMethods.DodMergeCreate);
            _helper.Emit(OpCodes.Ldloca, locBldr);
            StartNestedIterator(ndDod.Child, lblOnEnd);
            Visit(ndDod.Child);
            _iterCurr.EnsureStack();
            _helper.Call(XmlILMethods.DodMergeAdd);
            _helper.Emit(OpCodes.Ldloca, locBldr);
            _iterCurr.LoopToEnd(lblOnEnd);
            EndNestedIterator(ndDod.Child);
            _helper.Call(XmlILMethods.DodMergeSeq);
            _iterCurr.Storage = StorageDescriptor.Stack(typeof(XPathNavigator), isCached: true);
            return true;
        }
        return false;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILMethods.AncDOCreate, System.Xml.Xsl.IlGen.XmlILMethods.AncDOCurrent, System.Xml.Xsl.IlGen.XmlILMethods.AncDONext, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.XmlILMethods.ContentMergeCreate, System.Xml.Xsl.IlGen.XmlILMethods.ContentMergeCurrent, System.Xml.Xsl.IlGen.XmlILMethods.ContentMergeNext, System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateFilteredIterator(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Xsl.IlGen.XmlILMethods.DescMergeCreate, System.Xml.Xsl.IlGen.XmlILMethods.DescMergeCurrent, System.Xml.Xsl.IlGen.XmlILMethods.DescMergeNext, System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILMethods.DodMergeAdd, System.Xml.Xsl.IlGen.XmlILMethods.DodMergeCreate, System.Xml.Xsl.IlGen.XmlILMethods.DodMergeSeq, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStack(), System.Xml.Xsl.IlGen.XmlILMethods.FollSibMergeCreate, System.Xml.Xsl.IlGen.XmlILMethods.FollSibMergeCurrent, System.Xml.Xsl.IlGen.XmlILMethods.FollSibMergeNext, System.Reflection.Emit.OpCodes.Ldloca, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.IteratorDescriptor.LoopToEnd(), System.Xml.Xsl.IlGen.XmlILMethods.PreSibDOCreate, System.Xml.Xsl.IlGen.XmlILMethods.PreSibDOCurrent, System.Xml.Xsl.IlGen.XmlILMethods.PreSibDONext, System.Xml.Xsl.IlGen.OptimizerPatterns.Read(), System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.Visit(), System.Xml.Xsl.IlGen.XmlILMethods.XPFollMergeCreate, System.Xml.Xsl.IlGen.XmlILMethods.XPFollMergeCurrent, System.Xml.Xsl.IlGen.XmlILMethods.XPFollMergeNext, System.Xml.Xsl.IlGen.XmlILMethods.XPPrecDOCreate, System.Xml.Xsl.IlGen.XmlILMethods.XPPrecDOCurrent, System.Xml.Xsl.IlGen.XmlILMethods.XPPrecDONext, System.Xml.Xsl.IlGen.XmlILMethods.XPPrecMergeCreate, System.Xml.Xsl.IlGen.XmlILMethods.XPPrecMergeCurrent, and System.Xml.Xsl.IlGen.XmlILMethods.XPPrecMergeNext.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitDocOrderDistinct().