Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty
VisitIsEmpty()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty (QilUnary ndIsEmpty) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 2054 of file XmlILVisitor.cs.
    {
        if (CachesResult(ndIsEmpty.Child))
        {
            NestedVisitEnsureStack(ndIsEmpty.Child);
            _helper.CallCacheCount(_iterNested.Storage.ItemStorageType);
            switch (_iterCurr.CurrentBranchingContext)
            {
            case BranchingContext.OnFalse:
                _helper.TestAndBranch(0, _iterCurr.LabelBranch, OpCodes.Bne_Un);
                break;
            case BranchingContext.OnTrue:
                _helper.TestAndBranch(0, _iterCurr.LabelBranch, OpCodes.Beq);
                break;
            default:
            {
                Label label = _helper.DefineLabel();
                _helper.Emit(OpCodes.Brfalse_S, label);
                _helper.ConvBranchToBool(label, isTrueBranch: true);
                break;
            }
            }
        }
        else
        {
            Label label2 = _helper.DefineLabel();
            IteratorDescriptor iterCurr = _iterCurr;
            if (iterCurr.CurrentBranchingContext == BranchingContext.OnTrue)
            {
                StartNestedIterator(ndIsEmpty.Child, _iterCurr.LabelBranch);
            }
            else
            {
                StartNestedIterator(ndIsEmpty.Child, label2);
            }
            Visit(ndIsEmpty.Child);
            _iterCurr.EnsureNoCache();
            _iterCurr.DiscardStack();
            switch (iterCurr.CurrentBranchingContext)
            {
            case BranchingContext.OnFalse:
                _helper.EmitUnconditionalBranch(OpCodes.Br, iterCurr.LabelBranch);
                _helper.MarkLabel(label2);
                break;
            case BranchingContext.None:
                _helper.ConvBranchToBool(label2, isTrueBranch: true);
                break;
            }
            EndNestedIterator(ndIsEmpty.Child);
        }
        if (_iterCurr.IsBranching)
        {
            _iterCurr.Storage = StorageDescriptor.None();
        }
        else
        {
            _iterCurr.Storage = StorageDescriptor.Stack(typeof(bool), isCached: false);
        }
        return ndIsEmpty;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.Reflection.Emit.OpCodes.Beq, System.Reflection.Emit.OpCodes.Bne_Un, System.Reflection.Emit.OpCodes.Br, System.Reflection.Emit.OpCodes.Brfalse_S, System.Xml.Xsl.IlGen.XmlILVisitor.CachesResult(), System.Xml.Xsl.IlGen.GenerateHelper.CallCacheCount(), System.Xml.Xsl.IlGen.GenerateHelper.ConvBranchToBool(), System.Xml.Xsl.IlGen.IteratorDescriptor.CurrentBranchingContext, System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.IteratorDescriptor.DiscardStack(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.IsBranching, System.Xml.Xsl.IlGen.StorageDescriptor.ItemStorageType, System.Xml.Xsl.IlGen.IteratorDescriptor.LabelBranch, System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.StorageDescriptor.None(), System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.Storage, System.Xml.Xsl.IlGen.GenerateHelper.TestAndBranch(), and System.Xml.Xsl.IlGen.XmlILVisitor.Visit().