Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.ZeroCompare
ZeroCompare()
void System.Xml.Xsl.IlGen.XmlILVisitor.ZeroCompare (QilNodeType relOp, bool isBoolVal) inline private
Definition at line 2749 of file XmlILVisitor.cs.
    {
        switch (_iterCurr.CurrentBranchingContext)
        {
        case BranchingContext.OnTrue:
            _helper.Emit((relOp == QilNodeType.Eq) ? OpCodes.Brfalse : OpCodes.Brtrue, _iterCurr.LabelBranch);
            _iterCurr.Storage = StorageDescriptor.None();
            return;
        case BranchingContext.OnFalse:
            _helper.Emit((relOp == QilNodeType.Eq) ? OpCodes.Brtrue : OpCodes.Brfalse, _iterCurr.LabelBranch);
            _iterCurr.Storage = StorageDescriptor.None();
            return;
        }
        if (!isBoolVal || relOp == QilNodeType.Eq)
        {
            Label label = _helper.DefineLabel();
            _helper.Emit((relOp == QilNodeType.Eq) ? OpCodes.Brfalse : OpCodes.Brtrue, label);
            _helper.ConvBranchToBool(label, isTrueBranch: true);
        }
        _iterCurr.Storage = StorageDescriptor.Stack(typeof(bool), isCached: false);
    }
References System.Reflection.Emit.OpCodes.Brfalse, System.Reflection.Emit.OpCodes.Brtrue, System.Xml.Dictionary, System.Xml.Xsl.IlGen.StorageDescriptor.None(), and System.Xml.Xsl.IlGen.StorageDescriptor.Stack().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.Compare(), System.Xml.Xsl.IlGen.XmlILVisitor.MatchesNodeKinds(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIs(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsType().