Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns
HandleFilterPatterns()
bool System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns (QilLoop ndFilter) inline private
Definition at line 1124 of file XmlILVisitor.cs.
    {
        OptimizerPatterns optimizerPatterns = OptimizerPatterns.Read(ndFilter);
        bool flag = optimizerPatterns.MatchesPattern(OptimizerPatternName.FilterElements);
        if (flag || optimizerPatterns.MatchesPattern(OptimizerPatternName.FilterContentKind))
        {
            XmlNodeKindFlags xmlNodeKindFlags;
            QilName qilName;
            if (flag)
            {
                xmlNodeKindFlags = XmlNodeKindFlags.Element;
                qilName = (QilName)optimizerPatterns.GetArgument(OptimizerPatternArgument.ElementQName);
            }
            else
            {
                xmlNodeKindFlags = ((XmlQueryType)optimizerPatterns.GetArgument(OptimizerPatternArgument.ElementQName)).NodeKinds;
                qilName = null;
            }
            QilNode qilNode = (QilNode)optimizerPatterns.GetArgument(OptimizerPatternArgument.StepNode);
            QilNode qilNode2 = (QilNode)optimizerPatterns.GetArgument(OptimizerPatternArgument.StepInput);
            switch (qilNode.NodeType)
            {
            case QilNodeType.Content:
                if (flag)
                {
                    LocalBuilder localBuilder = _helper.DeclareLocal("$$$iterElemContent", typeof(ElementContentIterator));
                    _helper.Emit(OpCodes.Ldloca, localBuilder);
                    NestedVisitEnsureStack(qilNode2);
                    _helper.CallGetAtomizedName(_helper.StaticData.DeclareName(qilName.LocalName));
                    _helper.CallGetAtomizedName(_helper.StaticData.DeclareName(qilName.NamespaceUri));
                    _helper.Call(XmlILMethods.ElemContentCreate);
                    GenerateSimpleIterator(typeof(XPathNavigator), localBuilder, XmlILMethods.ElemContentNext, XmlILMethods.ElemContentCurrent);
                }
                else if (xmlNodeKindFlags == XmlNodeKindFlags.Content)
                {
                    CreateSimpleIterator(qilNode2, "$$$iterContent", typeof(ContentIterator), XmlILMethods.ContentCreate, XmlILMethods.ContentNext, XmlILMethods.ContentCurrent);
                }
                else
                {
                    LocalBuilder localBuilder = _helper.DeclareLocal("$$$iterContent", typeof(NodeKindContentIterator));
                    _helper.Emit(OpCodes.Ldloca, localBuilder);
                    NestedVisitEnsureStack(qilNode2);
                    _helper.LoadInteger((int)QilXmlToXPathNodeType(xmlNodeKindFlags));
                    _helper.Call(XmlILMethods.KindContentCreate);
                    GenerateSimpleIterator(typeof(XPathNavigator), localBuilder, XmlILMethods.KindContentNext, XmlILMethods.KindContentCurrent);
                }
                return true;
            case QilNodeType.Parent:
                CreateFilteredIterator(qilNode2, "$$$iterPar", typeof(ParentIterator), XmlILMethods.ParentCreate, XmlILMethods.ParentNext, XmlILMethods.ParentCurrent, xmlNodeKindFlags, qilName, TriState.Unknown, null);
                return true;
            case QilNodeType.Ancestor:
            case QilNodeType.AncestorOrSelf:
                CreateFilteredIterator(qilNode2, "$$$iterAnc", typeof(AncestorIterator), XmlILMethods.AncCreate, XmlILMethods.AncNext, XmlILMethods.AncCurrent, xmlNodeKindFlags, qilName, (qilNode.NodeType != QilNodeType.Ancestor) ? TriState.True : TriState.False, null);
                return true;
            case QilNodeType.Descendant:
            case QilNodeType.DescendantOrSelf:
                CreateFilteredIterator(qilNode2, "$$$iterDesc", typeof(DescendantIterator), XmlILMethods.DescCreate, XmlILMethods.DescNext, XmlILMethods.DescCurrent, xmlNodeKindFlags, qilName, (qilNode.NodeType != QilNodeType.Descendant) ? TriState.True : TriState.False, null);
                return true;
            case QilNodeType.Preceding:
                CreateFilteredIterator(qilNode2, "$$$iterPrec", typeof(PrecedingIterator), XmlILMethods.PrecCreate, XmlILMethods.PrecNext, XmlILMethods.PrecCurrent, xmlNodeKindFlags, qilName, TriState.Unknown, null);
                return true;
            case QilNodeType.FollowingSibling:
                CreateFilteredIterator(qilNode2, "$$$iterFollSib", typeof(FollowingSiblingIterator), XmlILMethods.FollSibCreate, XmlILMethods.FollSibNext, XmlILMethods.FollSibCurrent, xmlNodeKindFlags, qilName, TriState.Unknown, null);
                return true;
            case QilNodeType.PrecedingSibling:
                CreateFilteredIterator(qilNode2, "$$$iterPreSib", typeof(PrecedingSiblingIterator), XmlILMethods.PreSibCreate, XmlILMethods.PreSibNext, XmlILMethods.PreSibCurrent, xmlNodeKindFlags, qilName, TriState.Unknown, null);
                return true;
            case QilNodeType.NodeRange:
                CreateFilteredIterator(qilNode2, "$$$iterRange", typeof(NodeRangeIterator), XmlILMethods.NodeRangeCreate, XmlILMethods.NodeRangeNext, XmlILMethods.NodeRangeCurrent, xmlNodeKindFlags, qilName, TriState.Unknown, ((QilBinary)qilNode).Right);
                return true;
            case QilNodeType.XPathFollowing:
                CreateFilteredIterator(qilNode2, "$$$iterFoll", typeof(XPathFollowingIterator), XmlILMethods.XPFollCreate, XmlILMethods.XPFollNext, XmlILMethods.XPFollCurrent, xmlNodeKindFlags, qilName, TriState.Unknown, null);
                return true;
            case QilNodeType.XPathPreceding:
                CreateFilteredIterator(qilNode2, "$$$iterPrec", typeof(XPathPrecedingIterator), XmlILMethods.XPPrecCreate, XmlILMethods.XPPrecNext, XmlILMethods.XPPrecCurrent, xmlNodeKindFlags, qilName, TriState.Unknown, null);
                return true;
            }
        }
        else
        {
            if (optimizerPatterns.MatchesPattern(OptimizerPatternName.FilterAttributeKind))
            {
                QilNode qilNode2 = (QilNode)optimizerPatterns.GetArgument(OptimizerPatternArgument.StepInput);
                CreateSimpleIterator(qilNode2, "$$$iterAttr", typeof(AttributeIterator), XmlILMethods.AttrCreate, XmlILMethods.AttrNext, XmlILMethods.AttrCurrent);
                return true;
            }
            if (optimizerPatterns.MatchesPattern(OptimizerPatternName.EqualityIndex))
            {
                Label lblOnEnd = _helper.DefineLabel();
                Label label = _helper.DefineLabel();
                QilIterator qilIterator = (QilIterator)optimizerPatterns.GetArgument(OptimizerPatternArgument.StepNode);
                QilNode n = (QilNode)optimizerPatterns.GetArgument(OptimizerPatternArgument.StepInput);
                LocalBuilder locBldr = _helper.DeclareLocal("$$$index", typeof(XmlILIndex));
                _helper.LoadQueryRuntime();
                _helper.Emit(OpCodes.Ldarg_1);
                _helper.LoadInteger(_indexId);
                _helper.Emit(OpCodes.Ldloca, locBldr);
                _helper.Call(XmlILMethods.FindIndex);
                _helper.Emit(OpCodes.Brtrue, label);
                _helper.LoadQueryRuntime();
                _helper.Emit(OpCodes.Ldarg_1);
                _helper.LoadInteger(_indexId);
                _helper.Emit(OpCodes.Ldloc, locBldr);
                StartNestedIterator(qilIterator, lblOnEnd);
                StartBinding(qilIterator);
                Visit(n);
                _iterCurr.EnsureStackNoCache();
                VisitFor(qilIterator);
                _iterCurr.EnsureStackNoCache();
                _iterCurr.EnsureItemStorageType(qilIterator.XmlType, typeof(XPathNavigator));
                _helper.Call(XmlILMethods.IndexAdd);
                _helper.Emit(OpCodes.Ldloc, locBldr);
                _iterCurr.LoopToEnd(lblOnEnd);
                EndBinding(qilIterator);
                EndNestedIterator(qilIterator);
                _helper.Call(XmlILMethods.AddNewIndex);
                _helper.MarkLabel(label);
                _helper.Emit(OpCodes.Ldloc, locBldr);
                _helper.Emit(OpCodes.Ldarg_2);
                _helper.Call(XmlILMethods.IndexLookup);
                _iterCurr.Storage = StorageDescriptor.Stack(typeof(XPathNavigator), isCached: true);
                _indexId++;
                return true;
            }
        }
        return false;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._indexId, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILMethods.AddNewIndex, System.Xml.Xsl.IlGen.XmlILMethods.AncCreate, System.Xml.Xsl.IlGen.XmlILMethods.AncCurrent, System.Xml.Xsl.IlGen.XmlILMethods.AncNext, System.Xml.Xsl.IlGen.XmlILMethods.AttrCreate, System.Xml.Xsl.IlGen.XmlILMethods.AttrCurrent, System.Xml.Xsl.IlGen.XmlILMethods.AttrNext, System.Reflection.Emit.OpCodes.Brtrue, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetAtomizedName(), System.Xml.Xsl.IlGen.XmlILMethods.ContentCreate, System.Xml.Xsl.IlGen.XmlILMethods.ContentCurrent, System.Xml.Xsl.IlGen.XmlILMethods.ContentNext, System.Xml.Xsl.IlGen.XmlILVisitor.CreateFilteredIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSimpleIterator(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Xsl.IlGen.StaticDataManager.DeclareName(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Xsl.IlGen.XmlILMethods.DescCreate, System.Xml.Xsl.IlGen.XmlILMethods.DescCurrent, System.Xml.Xsl.IlGen.XmlILMethods.DescNext, System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILMethods.ElemContentCreate, System.Xml.Xsl.IlGen.XmlILMethods.ElemContentCurrent, System.Xml.Xsl.IlGen.XmlILMethods.ElemContentNext, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.EndBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStackNoCache(), System.Xml.Xsl.IlGen.XmlILMethods.FindIndex, System.Xml.Xsl.IlGen.XmlILMethods.FollSibCreate, System.Xml.Xsl.IlGen.XmlILMethods.FollSibCurrent, System.Xml.Xsl.IlGen.XmlILMethods.FollSibNext, System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator(), System.Xml.Xsl.IlGen.XmlILMethods.IndexAdd, System.Xml.Xsl.IlGen.XmlILMethods.IndexLookup, System.Xml.Xsl.IlGen.XmlILMethods.KindContentCreate, System.Xml.Xsl.IlGen.XmlILMethods.KindContentCurrent, System.Xml.Xsl.IlGen.XmlILMethods.KindContentNext, System.Reflection.Emit.OpCodes.Ldarg_1, System.Reflection.Emit.OpCodes.Ldarg_2, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.IteratorDescriptor.LoopToEnd(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.XmlILMethods.NodeRangeCreate, System.Xml.Xsl.IlGen.XmlILMethods.NodeRangeCurrent, System.Xml.Xsl.IlGen.XmlILMethods.NodeRangeNext, System.Xml.Xsl.IlGen.XmlILMethods.ParentCreate, System.Xml.Xsl.IlGen.XmlILMethods.ParentCurrent, System.Xml.Xsl.IlGen.XmlILMethods.ParentNext, System.Xml.Xsl.IlGen.XmlILMethods.PrecCreate, System.Xml.Xsl.IlGen.XmlILMethods.PrecCurrent, System.Xml.Xsl.IlGen.XmlILMethods.PrecNext, System.Xml.Xsl.IlGen.XmlILMethods.PreSibCreate, System.Xml.Xsl.IlGen.XmlILMethods.PreSibCurrent, System.Xml.Xsl.IlGen.XmlILMethods.PreSibNext, System.Xml.Xsl.IlGen.XmlILVisitor.QilXmlToXPathNodeType(), System.Xml.Xsl.IlGen.OptimizerPatterns.Read(), System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Xml.Xsl.IlGen.XmlILVisitor.StartBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), System.Xml.Xsl.IlGen.GenerateHelper.StaticData, System.Xml.Xsl.IlGen.XmlILVisitor.Visit(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFor(), System.Xml.Xsl.IlGen.XmlILMethods.XPFollCreate, System.Xml.Xsl.IlGen.XmlILMethods.XPFollCurrent, System.Xml.Xsl.IlGen.XmlILMethods.XPFollNext, System.Xml.Xsl.IlGen.XmlILMethods.XPPrecCreate, System.Xml.Xsl.IlGen.XmlILMethods.XPPrecCurrent, and System.Xml.Xsl.IlGen.XmlILMethods.XPPrecNext.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitFilter().