Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitDocOrderDistinct
VisitDocOrderDistinct()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitDocOrderDistinct (QilUnary ndDod) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1418 of file XmlILVisitor.cs.
    {
        if (ndDod.XmlType.IsSingleton)
        {
            return Visit(ndDod.Child);
        }
        if (HandleDodPatterns(ndDod))
        {
            return ndDod;
        }
        _helper.LoadQueryRuntime();
        NestedVisitEnsureCache(ndDod.Child, typeof(XPathNavigator));
        _iterCurr.EnsureStack();
        _helper.Call(XmlILMethods.DocOrder);
        return ndDod;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILMethods.DocOrder, System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStack(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureCache(), and System.Xml.Xsl.IlGen.XmlILVisitor.Visit().