Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.CachesResult
CachesResult()
bool System.Xml.Xsl.IlGen.XmlILVisitor.CachesResult (QilNode nd) inline private
Definition at line 3087 of file XmlILVisitor.cs.
    {
        switch (nd.NodeType)
        {
        case QilNodeType.Let:
        case QilNodeType.Parameter:
        case QilNodeType.Invoke:
        case QilNodeType.XsltInvokeLateBound:
        case QilNodeType.XsltInvokeEarlyBound:
            return !nd.XmlType.IsSingleton;
        case QilNodeType.Filter:
        {
            OptimizerPatterns optimizerPatterns = OptimizerPatterns.Read(nd);
            return optimizerPatterns.MatchesPattern(OptimizerPatternName.EqualityIndex);
        }
        case QilNodeType.DocOrderDistinct:
        {
            if (nd.XmlType.IsSingleton)
            {
                return false;
            }
            OptimizerPatterns optimizerPatterns = OptimizerPatterns.Read(nd);
            if (!optimizerPatterns.MatchesPattern(OptimizerPatternName.JoinAndDod))
            {
                return !optimizerPatterns.MatchesPattern(OptimizerPatternName.DodReverse);
            }
            return false;
        }
        case QilNodeType.TypeAssert:
        {
            QilTargetType qilTargetType = (QilTargetType)nd;
            if (CachesResult(qilTargetType.Source))
            {
                return GetItemStorageType(qilTargetType.Source) == GetItemStorageType(qilTargetType);
            }
            return false;
        }
        default:
            return false;
        }
    }
References System.Xml.Xsl.IlGen.OptimizerPatterns.Read().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength().