Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator
CreateSetIterator()
QilNode System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator (QilBinary ndSet, string iterName, Type iterType, MethodInfo methCreate, MethodInfo methNext, MethodInfo methCurrent) inline private
Definition at line 719 of file XmlILVisitor.cs.
    {
        LocalBuilder localBuilder = _helper.DeclareLocal(iterName, iterType);
        LocalBuilder localBuilder2 = _helper.DeclareLocal("$$$navSet", typeof(XPathNavigator));
        _helper.Emit(OpCodes.Ldloca, localBuilder);
        _helper.LoadQueryRuntime();
        _helper.Call(methCreate);
        Label label = _helper.DefineLabel();
        Label label2 = _helper.DefineLabel();
        Label label3 = _helper.DefineLabel();
        NestedVisit(ndSet.Left, label);
        Label labelNext = _iterNested.GetLabelNext();
        _iterCurr.EnsureLocal(localBuilder2);
        _helper.EmitUnconditionalBranch(OpCodes.Brtrue, label2);
        _helper.MarkLabel(label3);
        NestedVisit(ndSet.Right, label);
        Label labelNext2 = _iterNested.GetLabelNext();
        _iterCurr.EnsureLocal(localBuilder2);
        _helper.EmitUnconditionalBranch(OpCodes.Brtrue, label2);
        _helper.MarkLabel(label);
        _helper.Emit(OpCodes.Ldnull);
        _helper.Emit(OpCodes.Stloc, localBuilder2);
        _helper.MarkLabel(label2);
        _helper.Emit(OpCodes.Ldloca, localBuilder);
        _helper.Emit(OpCodes.Ldloc, localBuilder2);
        _helper.Call(methNext);
        if (ndSet.XmlType.IsSingleton)
        {
            _helper.Emit(OpCodes.Switch, new Label[3] { label3, labelNext, labelNext2 });
            _iterCurr.Storage = StorageDescriptor.Current(localBuilder, methCurrent, typeof(XPathNavigator));
        }
        else
        {
            _helper.Emit(OpCodes.Switch, new Label[4]
            {
                _iterCurr.GetLabelNext(),
                label3,
                labelNext,
                labelNext2
            });
            _iterCurr.SetIterator(label, StorageDescriptor.Current(localBuilder, methCurrent, typeof(XPathNavigator)));
        }
        return ndSet;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.Reflection.Emit.OpCodes.Brtrue, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.StorageDescriptor.Current(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureLocal(), System.Xml.Xsl.IlGen.IteratorDescriptor.GetLabelNext(), System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.OpCodes.Ldnull, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), System.Xml.Xsl.IlGen.IteratorDescriptor.SetIterator(), System.Reflection.Emit.OpCodes.Stloc, and System.Reflection.Emit.OpCodes.Switch.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitDifference(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIntersection(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitUnion().