Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional
VisitConditional()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional (QilTernary ndCond) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 487 of file XmlILVisitor.cs.
    {
        XmlILConstructInfo xmlILConstructInfo = XmlILConstructInfo.Read(ndCond);
        if (xmlILConstructInfo.ConstructMethod == XmlILConstructMethod.Writer)
        {
            Label label = _helper.DefineLabel();
            NestedVisitWithBranch(ndCond.Left, BranchingContext.OnFalse, label);
            NestedVisit(ndCond.Center);
            if (ndCond.Right.NodeType == QilNodeType.Sequence && ndCond.Right.Count == 0)
            {
                _helper.MarkLabel(label);
                NestedVisit(ndCond.Right);
            }
            else
            {
                Label label2 = _helper.DefineLabel();
                _helper.EmitUnconditionalBranch(OpCodes.Br, label2);
                _helper.MarkLabel(label);
                NestedVisit(ndCond.Right);
                _helper.MarkLabel(label2);
            }
            _iterCurr.Storage = StorageDescriptor.None();
        }
        else
        {
            LocalBuilder localBuilder = null;
            LocalBuilder localBuilder2 = null;
            Type itemStorageType = GetItemStorageType(ndCond);
            Label label3 = _helper.DefineLabel();
            if (ndCond.XmlType.IsSingleton)
            {
                NestedVisitWithBranch(ndCond.Left, BranchingContext.OnFalse, label3);
            }
            else
            {
                localBuilder2 = _helper.DeclareLocal("$$$cond", itemStorageType);
                localBuilder = _helper.DeclareLocal("$$$boolResult", typeof(bool));
                NestedVisitEnsureLocal(ndCond.Left, localBuilder);
                _helper.Emit(OpCodes.Ldloc, localBuilder);
                _helper.Emit(OpCodes.Brfalse, label3);
            }
            ConditionalBranch(ndCond.Center, itemStorageType, localBuilder2);
            IteratorDescriptor iterNested = _iterNested;
            Label label4 = _helper.DefineLabel();
            _helper.EmitUnconditionalBranch(OpCodes.Br, label4);
            _helper.MarkLabel(label3);
            ConditionalBranch(ndCond.Right, itemStorageType, localBuilder2);
            if (!ndCond.XmlType.IsSingleton)
            {
                _helper.EmitUnconditionalBranch(OpCodes.Brtrue, label4);
                Label label5 = _helper.DefineLabel();
                _helper.MarkLabel(label5);
                _helper.Emit(OpCodes.Ldloc, localBuilder);
                _helper.Emit(OpCodes.Brtrue, iterNested.GetLabelNext());
                _helper.EmitUnconditionalBranch(OpCodes.Br, _iterNested.GetLabelNext());
                _iterCurr.SetIterator(label5, StorageDescriptor.Local(localBuilder2, itemStorageType, isCached: false));
            }
            _helper.MarkLabel(label4);
        }
        return ndCond;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.Reflection.Emit.OpCodes.Br, System.Reflection.Emit.OpCodes.Brfalse, System.Reflection.Emit.OpCodes.Brtrue, System.Xml.Xsl.IlGen.XmlILVisitor.ConditionalBranch(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.GetLabelNext(), System.Reflection.Emit.OpCodes.Ldloc, System.Xml.Xsl.IlGen.StorageDescriptor.Local(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureLocal(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitWithBranch(), System.Xml.Xsl.IlGen.StorageDescriptor.None(), System.Xml.Xsl.IlGen.XmlILConstructInfo.Read(), and System.Xml.Xsl.IlGen.IteratorDescriptor.SetIterator().