Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort
VisitSort()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort (QilLoop ndSort) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1347 of file XmlILVisitor.cs.
    {
        Type itemStorageType = GetItemStorageType(ndSort);
        Label lblOnEnd = _helper.DefineLabel();
        XmlILStorageMethods xmlILStorageMethods = XmlILMethods.StorageMethods[itemStorageType];
        LocalBuilder localBuilder = _helper.DeclareLocal("$$$cache", xmlILStorageMethods.SeqType);
        _helper.Emit(OpCodes.Ldloc, localBuilder);
        _helper.Call(xmlILStorageMethods.SeqReuse);
        _helper.Emit(OpCodes.Stloc, localBuilder);
        _helper.Emit(OpCodes.Ldloc, localBuilder);
        LocalBuilder localBuilder2 = _helper.DeclareLocal("$$$keys", typeof(XmlSortKeyAccumulator));
        _helper.Emit(OpCodes.Ldloca, localBuilder2);
        _helper.Call(XmlILMethods.SortKeyCreate);
        StartNestedIterator(ndSort.Variable, lblOnEnd);
        StartBinding(ndSort.Variable);
        _iterCurr.EnsureStackNoCache();
        _iterCurr.EnsureItemStorageType(ndSort.Variable.XmlType, GetItemStorageType(ndSort.Variable));
        _helper.Call(xmlILStorageMethods.SeqAdd);
        _helper.Emit(OpCodes.Ldloca, localBuilder2);
        foreach (QilSortKey item in ndSort.Body)
        {
            VisitSortKey(item, localBuilder2);
        }
        _helper.Call(XmlILMethods.SortKeyFinish);
        _helper.Emit(OpCodes.Ldloc, localBuilder);
        _iterCurr.LoopToEnd(lblOnEnd);
        _helper.Emit(OpCodes.Pop);
        _helper.Emit(OpCodes.Ldloc, localBuilder);
        _helper.Emit(OpCodes.Ldloca, localBuilder2);
        _helper.Call(XmlILMethods.SortKeyKeys);
        _helper.Call(xmlILStorageMethods.SeqSortByKeys);
        _iterCurr.Storage = StorageDescriptor.Local(localBuilder, itemStorageType, isCached: true);
        EndBinding(ndSort.Variable);
        EndNestedIterator(ndSort.Variable);
        _iterCurr.SetIterator(_iterNested);
        return ndSort;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.EndBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStackNoCache(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.item, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Xml.Xsl.IlGen.StorageDescriptor.Local(), System.Xml.Xsl.IlGen.IteratorDescriptor.LoopToEnd(), System.Reflection.Emit.OpCodes.Pop, System.Xml.Xsl.IlGen.IteratorDescriptor.SetIterator(), System.Xml.Xsl.IlGen.XmlILMethods.SortKeyCreate, System.Xml.Xsl.IlGen.XmlILMethods.SortKeyFinish, System.Xml.Xsl.IlGen.XmlILMethods.SortKeyKeys, System.Xml.Xsl.IlGen.XmlILVisitor.StartBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), System.Reflection.Emit.OpCodes.Stloc, System.Xml.Xsl.IlGen.XmlILMethods.StorageMethods, and System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey().