Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.EndBinding
EndBinding()
void System.Xml.Xsl.IlGen.XmlILVisitor.EndBinding (QilIterator ndIter) inline private
Definition at line 1331 of file XmlILVisitor.cs.
    {
        if (_qil.IsDebug && ndIter.DebugName != null)
        {
            _helper.DebugEndScope();
        }
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._qil, System.Xml.Xsl.IlGen.GenerateHelper.DebugEndScope(), and System.Xml.Xsl.Qil.QilExpression.IsDebug.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFilter(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLoop(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort().