Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitFor
VisitFor()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitFor (QilIterator ndFor) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1077 of file XmlILVisitor.cs.
    {
        IteratorDescriptor cachedIteratorDescriptor = XmlILAnnotation.Write(ndFor).CachedIteratorDescriptor;
        _iterCurr.Storage = cachedIteratorDescriptor.Storage;
        if (_iterCurr.Storage.Location == ItemLocation.Global)
        {
            _iterCurr.EnsureStack();
        }
        return ndFor;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Dictionary, System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStack(), System.Xml.Xsl.IlGen.StorageDescriptor.Location, System.Xml.Xsl.IlGen.IteratorDescriptor.Storage, and System.Xml.Xsl.IlGen.XmlILAnnotation.Write().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLet(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitParameter().