Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId
VisitXsltGenerateId()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId (QilUnary ndGenId) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 2158 of file XmlILVisitor.cs.
    {
        _helper.LoadQueryRuntime();
        if (ndGenId.Child.XmlType.IsSingleton)
        {
            NestedVisitEnsureStack(ndGenId.Child, typeof(XPathNavigator), isCached: false);
            _helper.Call(XmlILMethods.GenId);
        }
        else
        {
            Label label = _helper.DefineLabel();
            StartNestedIterator(ndGenId.Child, label);
            Visit(ndGenId.Child);
            _iterCurr.EnsureStackNoCache();
            _iterCurr.EnsureItemStorageType(ndGenId.Child.XmlType, typeof(XPathNavigator));
            _helper.Call(XmlILMethods.GenId);
            Label label2 = _helper.DefineLabel();
            _helper.EmitUnconditionalBranch(OpCodes.Br, label2);
            _helper.MarkLabel(label);
            _helper.Emit(OpCodes.Pop);
            _helper.Emit(OpCodes.Ldstr, "");
            _helper.MarkLabel(label2);
            EndNestedIterator(ndGenId.Child);
        }
        _iterCurr.Storage = StorageDescriptor.Stack(typeof(string), isCached: false);
        return ndGenId;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Reflection.Emit.OpCodes.Br, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStackNoCache(), System.Xml.Xsl.IlGen.XmlILMethods.GenId, System.Reflection.Emit.OpCodes.Ldstr, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Reflection.Emit.OpCodes.Pop, System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), and System.Xml.Xsl.IlGen.XmlILVisitor.Visit().