Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey
VisitSortKey() [2/2]
void System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey (QilSortKey ndKey, LocalBuilder locKeys) inline private
Definition at line 1385 of file XmlILVisitor.cs.
    {
        _helper.Emit(OpCodes.Ldloca, locKeys);
        if (ndKey.Collation.NodeType == QilNodeType.LiteralString)
        {
            _helper.CallGetCollation(_helper.StaticData.DeclareCollation((QilLiteral)ndKey.Collation));
        }
        else
        {
            _helper.LoadQueryRuntime();
            NestedVisitEnsureStack(ndKey.Collation);
            _helper.Call(XmlILMethods.CreateCollation);
        }
        if (ndKey.XmlType.IsSingleton)
        {
            NestedVisitEnsureStack(ndKey.Key);
            _helper.AddSortKey(ndKey.Key.XmlType);
            return;
        }
        Label label = _helper.DefineLabel();
        StartNestedIterator(ndKey.Key, label);
        Visit(ndKey.Key);
        _iterCurr.EnsureStackNoCache();
        _iterCurr.EnsureItemStorageType(ndKey.Key.XmlType, GetItemStorageType(ndKey.Key));
        _helper.AddSortKey(ndKey.Key.XmlType);
        Label label2 = _helper.DefineLabel();
        _helper.EmitUnconditionalBranch(OpCodes.Br_S, label2);
        _helper.MarkLabel(label);
        _helper.AddSortKey(null);
        _helper.MarkLabel(label2);
        EndNestedIterator(ndKey.Key);
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.GenerateHelper.AddSortKey(), System.Reflection.Emit.OpCodes.Br_S, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetCollation(), System.Xml.Xsl.IlGen.XmlILMethods.CreateCollation, System.Xml.Xsl.IlGen.StaticDataManager.DeclareCollation(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStackNoCache(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Reflection.Emit.OpCodes.Ldloca, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), System.Xml.Xsl.IlGen.GenerateHelper.StaticData, and System.Xml.Xsl.IlGen.XmlILVisitor.Visit().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort().