Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitLoop
VisitLoop()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitLoop (QilLoop ndLoop) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1098 of file XmlILVisitor.cs.
    {
        StartWriterLoop(ndLoop, out var hasOnEnd, out var lblOnEnd);
        StartBinding(ndLoop.Variable);
        Visit(ndLoop.Body);
        EndBinding(ndLoop.Variable);
        EndWriterLoop(ndLoop, hasOnEnd, lblOnEnd);
        return ndLoop;
    }
References System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILVisitor.EndBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.EndWriterLoop(), System.Xml.Xsl.IlGen.XmlILVisitor.StartBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.StartWriterLoop(), and System.Xml.Xsl.IlGen.XmlILVisitor.Visit().