Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.SyncToNavigator
SyncToNavigator()
void System.Xml.Xsl.IlGen.XmlILVisitor.SyncToNavigator (LocalBuilder locNav, QilNode ndCtxt) inline private
Definition at line 2463 of file XmlILVisitor.cs.
    {
        _helper.Emit(OpCodes.Ldloc, locNav);
        NestedVisitEnsureStack(ndCtxt);
        _helper.CallSyncToNavigator();
        _helper.Emit(OpCodes.Stloc, locNav);
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.CallSyncToNavigator(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Reflection.Emit.OpCodes.Ldloc, System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), and System.Reflection.Emit.OpCodes.Stloc.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttribute(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitParent(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitRoot().