Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsType
VisitIsType()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsType (QilTargetType ndIsType) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1892 of file XmlILVisitor.cs.
    {
        XmlQueryType xmlType = ndIsType.Source.XmlType;
        XmlQueryType targetType = ndIsType.TargetType;
        if (xmlType.IsSingleton && (object)targetType == XmlQueryTypeFactory.Node)
        {
            NestedVisitEnsureStack(ndIsType.Source);
            _helper.Call(XmlILMethods.ItemIsNode);
            ZeroCompare(QilNodeType.Ne, isBoolVal: true);
            return ndIsType;
        }
        if (MatchesNodeKinds(ndIsType, xmlType, targetType))
        {
            return ndIsType;
        }
        XmlTypeCode xmlTypeCode = (((object)targetType == XmlQueryTypeFactory.Double) ? XmlTypeCode.Double : (((object)targetType == XmlQueryTypeFactory.String) ? XmlTypeCode.String : (((object)targetType == XmlQueryTypeFactory.Boolean) ? XmlTypeCode.Boolean : (((object)targetType == XmlQueryTypeFactory.Node) ? XmlTypeCode.Node : XmlTypeCode.None))));
        if (xmlTypeCode != 0)
        {
            _helper.LoadQueryRuntime();
            NestedVisitEnsureStack(ndIsType.Source, typeof(XPathItem), !xmlType.IsSingleton);
            _helper.LoadInteger((int)xmlTypeCode);
            _helper.Call(xmlType.IsSingleton ? XmlILMethods.ItemMatchesCode : XmlILMethods.SeqMatchesCode);
            ZeroCompare(QilNodeType.Ne, isBoolVal: true);
            return ndIsType;
        }
        _helper.LoadQueryRuntime();
        NestedVisitEnsureStack(ndIsType.Source, typeof(XPathItem), !xmlType.IsSingleton);
        _helper.LoadInteger(_helper.StaticData.DeclareXmlType(targetType));
        _helper.Call(xmlType.IsSingleton ? XmlILMethods.ItemMatchesType : XmlILMethods.SeqMatchesType);
        ZeroCompare(QilNodeType.Ne, isBoolVal: true);
        return ndIsType;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.XmlQueryTypeFactory.Boolean, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.StaticDataManager.DeclareXmlType(), System.Xml.Dictionary, System.Xml.Xsl.XmlQueryTypeFactory.Double, System.Xml.Xsl.XmlQueryType.IsSingleton, System.Xml.Xsl.IlGen.XmlILMethods.ItemIsNode, System.Xml.Xsl.IlGen.XmlILMethods.ItemMatchesCode, System.Xml.Xsl.IlGen.XmlILMethods.ItemMatchesType, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.XmlILVisitor.MatchesNodeKinds(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.XmlQueryTypeFactory.Node, System.Xml.Xsl.IlGen.XmlILMethods.SeqMatchesCode, System.Xml.Xsl.IlGen.XmlILMethods.SeqMatchesType, System.Xml.Xsl.IlGen.GenerateHelper.StaticData, System.Xml.Xsl.XmlQueryTypeFactory.String, and System.Xml.Xsl.IlGen.XmlILVisitor.ZeroCompare().