Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitElementCtor
VisitElementCtor()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitElementCtor (QilBinary ndElem) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1661 of file XmlILVisitor.cs.
    {
        XmlILConstructInfo xmlILConstructInfo = XmlILConstructInfo.Read(ndElem);
        bool flag = CheckWithinContent(xmlILConstructInfo) || !xmlILConstructInfo.IsNamespaceInScope || ElementCachesAttributes(xmlILConstructInfo);
        if (XmlILConstructInfo.Read(ndElem.Right).FinalStates == PossibleXmlStates.Any)
        {
            flag = true;
        }
        if (xmlILConstructInfo.FinalStates == PossibleXmlStates.Any)
        {
            flag = true;
        }
        if (!flag)
        {
            BeforeStartChecks(ndElem);
        }
        GenerateNameType nameType = LoadNameAndType(XPathNodeType.Element, ndElem.Left, isStart: true, flag);
        _helper.CallWriteStartElement(nameType, flag);
        NestedVisit(ndElem.Right);
        if (XmlILConstructInfo.Read(ndElem.Right).FinalStates == PossibleXmlStates.EnumAttrs && !flag)
        {
            _helper.CallStartElementContent();
        }
        nameType = LoadNameAndType(XPathNodeType.Element, ndElem.Left, isStart: false, flag);
        _helper.CallWriteEndElement(nameType, flag);
        if (!flag)
        {
            AfterEndChecks(ndElem);
        }
        _iterCurr.Storage = StorageDescriptor.None();
        return ndElem;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor.AfterEndChecks(), System.Xml.Xsl.IlGen.XmlILVisitor.BeforeStartChecks(), System.Xml.Xsl.IlGen.GenerateHelper.CallStartElementContent(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteEndElement(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteStartElement(), System.Xml.Xsl.IlGen.XmlILVisitor.CheckWithinContent(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILVisitor.ElementCachesAttributes(), System.Xml.Xsl.IlGen.XmlILVisitor.LoadNameAndType(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), System.Xml.Xsl.IlGen.StorageDescriptor.None(), and System.Xml.Xsl.IlGen.XmlILConstructInfo.Read().