Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.StartLetBinding
StartLetBinding()
void System.Xml.Xsl.IlGen.XmlILVisitor.StartLetBinding (QilIterator ndLet) inline
Definition at line 1315 of file XmlILVisitor.cs.
    {
        StartNestedIterator(ndLet);
        NestedVisit(ndLet.Binding, GetItemStorageType(ndLet), !ndLet.XmlType.IsSingleton);
        if (_qil.IsDebug && ndLet.DebugName != null)
        {
            _helper.DebugStartScope();
            _iterCurr.EnsureLocal("$$$cache");
        }
        else
        {
            _iterCurr.EnsureNoStack("$$$cache");
        }
        EndNestedIterator(ndLet);
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILVisitor._qil, System.Xml.Xsl.IlGen.GenerateHelper.DebugStartScope(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureLocal(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoStack(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.Qil.QilExpression.IsDebug, System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), and System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.StartBinding().