Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitDeref
VisitDeref()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitDeref (QilBinary ndDeref) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1650 of file XmlILVisitor.cs.
    {
        LocalBuilder localBuilder = _helper.DeclareLocal("$$$iterId", typeof(IdIterator));
        _helper.Emit(OpCodes.Ldloca, localBuilder);
        NestedVisitEnsureStack(ndDeref.Left);
        NestedVisitEnsureStack(ndDeref.Right);
        _helper.Call(XmlILMethods.IdCreate);
        GenerateSimpleIterator(typeof(XPathNavigator), localBuilder, XmlILMethods.IdNext, XmlILMethods.IdCurrent);
        return ndDeref;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator(), System.Xml.Xsl.IlGen.XmlILMethods.IdCreate, System.Xml.Xsl.IlGen.XmlILMethods.IdCurrent, System.Xml.Xsl.IlGen.XmlILMethods.IdNext, System.Reflection.Emit.OpCodes.Ldloca, and System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack().