Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitChoice
VisitChoice()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitChoice (QilChoice ndChoice) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 570 of file XmlILVisitor.cs.
    {
        NestedVisit(ndChoice.Expression);
        QilNode branches = ndChoice.Branches;
        int num = branches.Count - 1;
        Label[] array = new Label[num];
        int i;
        for (i = 0; i < num; i++)
        {
            array[i] = _helper.DefineLabel();
        }
        Label label = _helper.DefineLabel();
        Label label2 = _helper.DefineLabel();
        _helper.Emit(OpCodes.Switch, array);
        _helper.EmitUnconditionalBranch(OpCodes.Br, label);
        for (i = 0; i < num; i++)
        {
            _helper.MarkLabel(array[i]);
            NestedVisit(branches[i]);
            _helper.EmitUnconditionalBranch(OpCodes.Br, label2);
        }
        _helper.MarkLabel(label);
        NestedVisit(branches[i]);
        _helper.MarkLabel(label2);
        _iterCurr.Storage = StorageDescriptor.None();
        return ndChoice;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.array, System.Reflection.Emit.OpCodes.Br, System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), System.Xml.Xsl.IlGen.StorageDescriptor.None(), and System.Reflection.Emit.OpCodes.Switch.