Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.Sequence
Sequence()
void System.Xml.Xsl.IlGen.XmlILVisitor.Sequence (QilList ndSeq) inline private
Definition at line 656 of file XmlILVisitor.cs.
    {
        Label label = default(Label);
        Type itemStorageType = GetItemStorageType(ndSeq);
        if (ndSeq.XmlType.IsSingleton)
        {
            foreach (QilNode item in ndSeq)
            {
                if (item.XmlType.IsSingleton)
                {
                    NestedVisitEnsureStack(item);
                    continue;
                }
                label = _helper.DefineLabel();
                NestedVisit(item, label);
                _iterCurr.DiscardStack();
                _helper.MarkLabel(label);
            }
            _iterCurr.Storage = StorageDescriptor.Stack(itemStorageType, isCached: false);
            return;
        }
        LocalBuilder localBuilder = _helper.DeclareLocal("$$$itemList", itemStorageType);
        LocalBuilder locBldr = _helper.DeclareLocal("$$$idxList", typeof(int));
        Label[] array = new Label[ndSeq.Count];
        Label label2 = _helper.DefineLabel();
        for (int i = 0; i < ndSeq.Count; i++)
        {
            if (i != 0)
            {
                _helper.MarkLabel(label);
            }
            label = ((i != ndSeq.Count - 1) ? _helper.DefineLabel() : _iterCurr.GetLabelNext());
            _helper.LoadInteger(i);
            _helper.Emit(OpCodes.Stloc, locBldr);
            NestedVisit(ndSeq[i], label);
            _iterCurr.EnsureItemStorageType(ndSeq[i].XmlType, itemStorageType);
            _iterCurr.EnsureLocalNoCache(localBuilder);
            array[i] = _iterNested.GetLabelNext();
            _helper.EmitUnconditionalBranch(OpCodes.Brtrue, label2);
        }
        Label label3 = _helper.DefineLabel();
        _helper.MarkLabel(label3);
        _helper.Emit(OpCodes.Ldloc, locBldr);
        _helper.Emit(OpCodes.Switch, array);
        _helper.MarkLabel(label2);
        _iterCurr.SetIterator(label3, StorageDescriptor.Local(localBuilder, itemStorageType, isCached: false));
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.array, System.Reflection.Emit.OpCodes.Brtrue, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.IteratorDescriptor.DiscardStack(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureLocalNoCache(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.GetLabelNext(), System.item, System.Reflection.Emit.OpCodes.Ldloc, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.StorageDescriptor.Local(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.IteratorDescriptor.SetIterator(), System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Reflection.Emit.OpCodes.Stloc, and System.Reflection.Emit.OpCodes.Switch.