Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator
StartNestedIterator() [1/2]
void System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator (QilNode nd) inline private
Definition at line 2919 of file XmlILVisitor.cs.
    {
        IteratorDescriptor iterCurr = _iterCurr;
        if (iterCurr == null)
        {
            _iterCurr = new IteratorDescriptor(_helper);
        }
        else
        {
            _iterCurr = new IteratorDescriptor(iterCurr);
        }
        _iterNested = null;
    }
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateConcat(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.StartLetBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.Visit(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAnd(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFilter(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNodeValue(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId().