Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack
NestedVisitEnsureStack() [1/3]
void System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack (QilNode nd) inline private
Definition at line 2998 of file XmlILVisitor.cs.
    {
        NestedVisit(nd);
        _iterCurr.EnsureStack();
    }
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.ArithmeticOp(), System.Xml.Xsl.IlGen.XmlILVisitor.Compare(), System.Xml.Xsl.IlGen.XmlILVisitor.ComparePosition(), System.Xml.Xsl.IlGen.XmlILVisitor.ConditionalBranch(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateFilteredIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSimpleIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.MatchesNodeKinds(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.SyncToNavigator(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDataSource(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDeref(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitError(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitInvoke(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIs(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsType(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNamespaceDecl(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNegate(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNodeProperty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitPICtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitRtfCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrConcat(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrParseQName(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTextCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitWarning(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNodeValue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltConvert(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopy(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopyOf(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound().