Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureCache
NestedVisitEnsureCache()
void System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureCache (QilNode nd, Type itemStorageType) inline private
Definition at line 3031 of file XmlILVisitor.cs.
    {
        bool flag = CachesResult(nd);
        Label lblOnEnd = _helper.DefineLabel();
        if (flag)
        {
            StartNestedIterator(nd);
            Visit(nd);
            EndNestedIterator(nd);
            _iterCurr.Storage = _iterNested.Storage;
            if (_iterCurr.Storage.ItemStorageType == itemStorageType)
            {
                return;
            }
            if (_iterCurr.Storage.ItemStorageType == typeof(XPathNavigator) || itemStorageType == typeof(XPathNavigator))
            {
                _iterCurr.EnsureItemStorageType(nd.XmlType, itemStorageType);
                return;
            }
            _iterCurr.EnsureNoStack("$$$cacheResult");
        }
        Type type = ((GetItemStorageType(nd) == typeof(XPathNavigator)) ? typeof(XPathNavigator) : itemStorageType);
        XmlILStorageMethods xmlILStorageMethods = XmlILMethods.StorageMethods[type];
        LocalBuilder localBuilder = _helper.DeclareLocal("$$$cache", xmlILStorageMethods.SeqType);
        _helper.Emit(OpCodes.Ldloc, localBuilder);
        if (nd.XmlType.IsSingleton)
        {
            NestedVisitEnsureStack(nd, type, isCached: false);
            _helper.Call(xmlILStorageMethods.SeqReuseSgl);
            _helper.Emit(OpCodes.Stloc, localBuilder);
        }
        else
        {
            _helper.Call(xmlILStorageMethods.SeqReuse);
            _helper.Emit(OpCodes.Stloc, localBuilder);
            _helper.Emit(OpCodes.Ldloc, localBuilder);
            StartNestedIterator(nd, lblOnEnd);
            if (flag)
            {
                _iterCurr.Storage = _iterCurr.ParentIterator.Storage;
            }
            else
            {
                Visit(nd);
            }
            _iterCurr.EnsureItemStorageType(nd.XmlType, type);
            _iterCurr.EnsureStackNoCache();
            _helper.Call(xmlILStorageMethods.SeqAdd);
            _helper.Emit(OpCodes.Ldloc, localBuilder);
            _iterCurr.LoopToEnd(lblOnEnd);
            EndNestedIterator(nd);
            _helper.Emit(OpCodes.Pop);
        }
        _iterCurr.Storage = StorageDescriptor.Local(localBuilder, itemStorageType, isCached: true);
    }
References System.Xml.Dictionary, System.Reflection.Emit.OpCodes.Ldloc, System.Xml.Xsl.IlGen.StorageDescriptor.Local(), System.Reflection.Emit.OpCodes.Pop, System.Reflection.Emit.OpCodes.Stloc, System.Xml.Xsl.IlGen.XmlILMethods.StorageMethods, and System.type.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitDocOrderDistinct(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound().