Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitNamespaceDecl
VisitNamespaceDecl()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitNamespaceDecl (QilBinary ndNmsp) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1787 of file XmlILVisitor.cs.
    {
        XmlILConstructInfo info = XmlILConstructInfo.Read(ndNmsp);
        bool flag = CheckEnumAttrs(info) || MightHaveNamespacesAfterAttributes(info);
        if (!flag)
        {
            BeforeStartChecks(ndNmsp);
        }
        _helper.LoadQueryOutput();
        NestedVisitEnsureStack(ndNmsp.Left);
        NestedVisitEnsureStack(ndNmsp.Right);
        _helper.CallWriteNamespaceDecl(flag);
        if (!flag)
        {
            AfterEndChecks(ndNmsp);
        }
        _iterCurr.Storage = StorageDescriptor.None();
        return ndNmsp;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor.AfterEndChecks(), System.Xml.Xsl.IlGen.XmlILVisitor.BeforeStartChecks(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteNamespaceDecl(), System.Xml.Xsl.IlGen.XmlILVisitor.CheckEnumAttrs(), System.Xml.Dictionary, System.info, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryOutput(), System.Xml.Xsl.IlGen.XmlILVisitor.MightHaveNamespacesAfterAttributes(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.StorageDescriptor.None(), and System.Xml.Xsl.IlGen.XmlILConstructInfo.Read().