Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit
NestedVisit() [3/3]
void System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit (QilNode nd, Type itemStorageType, bool isCached) inline private
Definition at line 2959 of file XmlILVisitor.cs.
    {
        if (XmlILConstructInfo.Read(nd).PushToWriterLast)
        {
            StartNestedIterator(nd);
            Visit(nd);
            EndNestedIterator(nd);
            _iterCurr.Storage = StorageDescriptor.None();
        }
        else if (!isCached && nd.XmlType.IsSingleton)
        {
            StartNestedIterator(nd);
            Visit(nd);
            _iterCurr.EnsureNoCache();
            _iterCurr.EnsureItemStorageType(nd.XmlType, itemStorageType);
            EndNestedIterator(nd);
            _iterCurr.Storage = _iterNested.Storage;
        }
        else
        {
            NestedVisitEnsureCache(nd, itemStorageType);
        }
    }
References System.Xml.Dictionary, System.Xml.Xsl.IlGen.StorageDescriptor.None(), and System.Xml.Xsl.IlGen.XmlILConstructInfo.Read().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.ConditionalBranch(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.StartLetBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttributeCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitChoice(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitCommentCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDocumentCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitElementCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitPICtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitRtfCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSequence(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTypeAssert(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopy().