Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.Visit
Visit() [1/2]
void System.Xml.Xsl.IlGen.XmlILVisitor.Visit (QilExpression qil, GenerateHelper helper, MethodInfo methRoot) inline
Definition at line 29 of file XmlILVisitor.cs.
    {
        _qil = qil;
        _helper = helper;
        _iterNested = null;
        _indexId = 0;
        PrepareGlobalValues(qil.GlobalParameterList);
        PrepareGlobalValues(qil.GlobalVariableList);
        VisitGlobalValues(qil.GlobalParameterList);
        VisitGlobalValues(qil.GlobalVariableList);
        foreach (QilFunction function in qil.FunctionList)
        {
            Function(function);
        }
        _helper.MethodBegin(methRoot, null, initWriters: true);
        StartNestedIterator(qil.Root);
        Visit(qil.Root);
        EndNestedIterator(qil.Root);
        _helper.MethodEnd();
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._indexId, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.Xml.Xsl.IlGen.XmlILVisitor._qil, System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.Qil.Function, System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin(), System.Xml.Xsl.IlGen.GenerateHelper.MethodEnd(), System.Xml.Xsl.IlGen.XmlILVisitor.PrepareGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.Visit(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator(), System.Xml.Xsl.XmlILGenerator.Generate(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateConcat(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.Visit(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAnd(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFilter(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLoop(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNop(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitOptimizeBarrier(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTypeAssert(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNodeValue(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId().