Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitFilter
VisitFilter()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitFilter (QilLoop ndFilter) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1108 of file XmlILVisitor.cs.
    {
        if (HandleFilterPatterns(ndFilter))
        {
            return ndFilter;
        }
        StartBinding(ndFilter.Variable);
        _iterCurr.SetIterator(_iterNested);
        StartNestedIterator(ndFilter.Body);
        _iterCurr.SetBranching(BranchingContext.OnFalse, _iterCurr.ParentIterator.GetLabelNext());
        Visit(ndFilter.Body);
        EndNestedIterator(ndFilter.Body);
        EndBinding(ndFilter.Variable);
        return ndFilter;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILVisitor.EndBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.GetLabelNext(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.IteratorDescriptor.ParentIterator, System.Xml.Xsl.IlGen.IteratorDescriptor.SetBranching(), System.Xml.Xsl.IlGen.IteratorDescriptor.SetIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.StartBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), and System.Xml.Xsl.IlGen.XmlILVisitor.Visit().