Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrConcat
VisitStrConcat()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrConcat (QilStrConcat ndStrConcat) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 864 of file XmlILVisitor.cs.
    {
        QilNode qilNode = ndStrConcat.Delimiter;
        if (qilNode.NodeType == QilNodeType.LiteralString && ((string)(QilLiteral)qilNode).Length == 0)
        {
            qilNode = null;
        }
        QilNode values = ndStrConcat.Values;
        bool flag;
        if (values.NodeType == QilNodeType.Sequence && values.Count < 5)
        {
            flag = true;
            foreach (QilNode item in values)
            {
                if (!item.XmlType.IsSingleton)
                {
                    flag = false;
                }
            }
        }
        else
        {
            flag = false;
        }
        if (flag)
        {
            foreach (QilNode item2 in values)
            {
                NestedVisitEnsureStack(item2);
            }
            _helper.CallConcatStrings(values.Count);
        }
        else
        {
            LocalBuilder localBuilder = _helper.DeclareLocal("$$$strcat", typeof(StringConcat));
            _helper.Emit(OpCodes.Ldloca, localBuilder);
            _helper.Call(XmlILMethods.StrCatClear);
            if (qilNode != null)
            {
                _helper.Emit(OpCodes.Ldloca, localBuilder);
                NestedVisitEnsureStack(qilNode);
                _helper.Call(XmlILMethods.StrCatDelim);
            }
            _helper.Emit(OpCodes.Ldloca, localBuilder);
            if (values.NodeType == QilNodeType.Sequence)
            {
                foreach (QilNode item3 in values)
                {
                    GenerateConcat(item3, localBuilder);
                }
            }
            else
            {
                GenerateConcat(values, localBuilder);
            }
            _helper.Call(XmlILMethods.StrCatResult);
        }
        _iterCurr.Storage = StorageDescriptor.Stack(typeof(string), isCached: false);
        return ndStrConcat;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.CallConcatStrings(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateConcat(), System.item, System.Reflection.Emit.OpCodes.Ldloca, System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Xml.Xsl.IlGen.XmlILMethods.StrCatClear, System.Xml.Xsl.IlGen.XmlILMethods.StrCatDelim, System.Xml.Xsl.IlGen.XmlILMethods.StrCatResult, System.Collections.Generic.Dictionary< TKey, TValue >.Values, and System.values.