Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.MatchesNodeKinds
MatchesNodeKinds()
bool System.Xml.Xsl.IlGen.XmlILVisitor.MatchesNodeKinds (QilTargetType ndIsType, XmlQueryType typDerived, XmlQueryType typBase) inline private
Definition at line 1925 of file XmlILVisitor.cs.
    {
        bool flag = true;
        if (!typBase.IsNode || !typBase.IsSingleton)
        {
            return false;
        }
        if (!typDerived.IsNode || !typDerived.IsSingleton || !typDerived.IsNotRtf)
        {
            return false;
        }
        XmlNodeKindFlags xmlNodeKindFlags = XmlNodeKindFlags.None;
        foreach (XmlQueryType item in typBase)
        {
            if ((object)item == XmlQueryTypeFactory.Element)
            {
                xmlNodeKindFlags |= XmlNodeKindFlags.Element;
                continue;
            }
            if ((object)item == XmlQueryTypeFactory.Attribute)
            {
                xmlNodeKindFlags |= XmlNodeKindFlags.Attribute;
                continue;
            }
            if ((object)item == XmlQueryTypeFactory.Text)
            {
                xmlNodeKindFlags |= XmlNodeKindFlags.Text;
                continue;
            }
            if ((object)item == XmlQueryTypeFactory.Document)
            {
                xmlNodeKindFlags |= XmlNodeKindFlags.Document;
                continue;
            }
            if ((object)item == XmlQueryTypeFactory.Comment)
            {
                xmlNodeKindFlags |= XmlNodeKindFlags.Comment;
                continue;
            }
            if ((object)item == XmlQueryTypeFactory.PI)
            {
                xmlNodeKindFlags |= XmlNodeKindFlags.PI;
                continue;
            }
            if ((object)item == XmlQueryTypeFactory.Namespace)
            {
                xmlNodeKindFlags |= XmlNodeKindFlags.Namespace;
                continue;
            }
            return false;
        }
        xmlNodeKindFlags = typDerived.NodeKinds & xmlNodeKindFlags;
        if (!Bits.ExactlyOne((uint)xmlNodeKindFlags))
        {
            xmlNodeKindFlags = ~xmlNodeKindFlags & XmlNodeKindFlags.Any;
            flag = !flag;
        }
        XPathNodeType xPathNodeType;
        switch (xmlNodeKindFlags)
        {
        case XmlNodeKindFlags.Element:
            xPathNodeType = XPathNodeType.Element;
            break;
        case XmlNodeKindFlags.Attribute:
            xPathNodeType = XPathNodeType.Attribute;
            break;
        case XmlNodeKindFlags.Namespace:
            xPathNodeType = XPathNodeType.Namespace;
            break;
        case XmlNodeKindFlags.PI:
            xPathNodeType = XPathNodeType.ProcessingInstruction;
            break;
        case XmlNodeKindFlags.Comment:
            xPathNodeType = XPathNodeType.Comment;
            break;
        case XmlNodeKindFlags.Document:
            xPathNodeType = XPathNodeType.Root;
            break;
        default:
            _helper.Emit(OpCodes.Ldc_I4_1);
            xPathNodeType = XPathNodeType.All;
            break;
        }
        NestedVisitEnsureStack(ndIsType.Source);
        _helper.Call(XmlILMethods.NavType);
        if (xPathNodeType == XPathNodeType.All)
        {
            _helper.Emit(OpCodes.Shl);
            int num = 0;
            if ((xmlNodeKindFlags & XmlNodeKindFlags.Document) != 0)
            {
                num |= 1;
            }
            if ((xmlNodeKindFlags & XmlNodeKindFlags.Element) != 0)
            {
                num |= 2;
            }
            if ((xmlNodeKindFlags & XmlNodeKindFlags.Attribute) != 0)
            {
                num |= 4;
            }
            if ((xmlNodeKindFlags & XmlNodeKindFlags.Text) != 0)
            {
                num |= 0x70;
            }
            if ((xmlNodeKindFlags & XmlNodeKindFlags.Comment) != 0)
            {
                num |= 0x100;
            }
            if ((xmlNodeKindFlags & XmlNodeKindFlags.PI) != 0)
            {
                num |= 0x80;
            }
            if ((xmlNodeKindFlags & XmlNodeKindFlags.Namespace) != 0)
            {
                num |= 8;
            }
            _helper.LoadInteger(num);
            _helper.Emit(OpCodes.And);
            ZeroCompare(flag ? QilNodeType.Ne : QilNodeType.Eq, isBoolVal: false);
        }
        else
        {
            _helper.LoadInteger((int)xPathNodeType);
            ClrCompare(flag ? QilNodeType.Eq : QilNodeType.Ne, XmlTypeCode.Int);
        }
        return true;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Reflection.Emit.OpCodes.And, System.Xml.Xsl.XmlQueryTypeFactory.Attribute, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.XmlILVisitor.ClrCompare(), System.Xml.Xsl.XmlQueryTypeFactory.Comment, System.Xml.Dictionary, System.Xml.Xsl.XmlQueryTypeFactory.Document, System.Xml.Xsl.XmlQueryTypeFactory.Element, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Bits.ExactlyOne(), System.item, System.Reflection.Emit.OpCodes.Ldc_I4_1, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.XmlQueryTypeFactory.Namespace, System.Xml.Xsl.IlGen.XmlILMethods.NavType, System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.XmlQueryTypeFactory.PI, System.Reflection.Emit.OpCodes.Shl, System.Xml.Xsl.XmlQueryTypeFactory.Text, and System.Xml.Xsl.IlGen.XmlILVisitor.ZeroCompare().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsType().