Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.Compare
Compare()
void System.Xml.Xsl.IlGen.XmlILVisitor.Compare (QilBinary ndComp) inline private
Definition at line 1013 of file XmlILVisitor.cs.
    {
        QilNodeType nodeType = ndComp.NodeType;
        if ((nodeType == QilNodeType.Eq || nodeType == QilNodeType.Ne) && (TryZeroCompare(nodeType, ndComp.Left, ndComp.Right) || TryZeroCompare(nodeType, ndComp.Right, ndComp.Left) || TryNameCompare(nodeType, ndComp.Left, ndComp.Right) || TryNameCompare(nodeType, ndComp.Right, ndComp.Left)))
        {
            return;
        }
        NestedVisitEnsureStack(ndComp.Left, ndComp.Right);
        XmlTypeCode typeCode = ndComp.Left.XmlType.TypeCode;
        switch (typeCode)
        {
        case XmlTypeCode.String:
        case XmlTypeCode.Decimal:
        case XmlTypeCode.QName:
            if (nodeType == QilNodeType.Eq || nodeType == QilNodeType.Ne)
            {
                _helper.CallCompareEquals(typeCode);
                ZeroCompare((nodeType == QilNodeType.Eq) ? QilNodeType.Ne : QilNodeType.Eq, isBoolVal: true);
            }
            else
            {
                _helper.CallCompare(typeCode);
                _helper.Emit(OpCodes.Ldc_I4_0);
                ClrCompare(nodeType, typeCode);
            }
            break;
        case XmlTypeCode.Boolean:
        case XmlTypeCode.Double:
        case XmlTypeCode.Integer:
        case XmlTypeCode.Int:
            ClrCompare(nodeType, typeCode);
            break;
        }
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.CallCompare(), System.Xml.Xsl.IlGen.GenerateHelper.CallCompareEquals(), System.Xml.Xsl.IlGen.XmlILVisitor.ClrCompare(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Reflection.Emit.OpCodes.Ldc_I4_0, System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.XmlILVisitor.TryNameCompare(), System.Xml.Xsl.IlGen.XmlILVisitor.TryZeroCompare(), and System.Xml.Xsl.IlGen.XmlILVisitor.ZeroCompare().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitEq(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGe(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGt(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLe(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLt(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitNe().