Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType
GetItemStorageType() [1/2]
Type System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType (QilNode nd) inline private
Definition at line 3139 of file XmlILVisitor.cs.
    {
        return XmlILTypeHelper.GetStorageType(nd.XmlType.Prime);
    }
References System.Xml.Xsl.IlGen.XmlILTypeHelper.GetStorageType().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.ArithmeticOp(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.PrepareGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.StartLetBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAverage(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitInvoke(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitMaximum(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitMinimum(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNegate(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSum(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTypeAssert(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltConvert(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound().