Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.StartBinding
StartBinding()
void System.Xml.Xsl.IlGen.XmlILVisitor.StartBinding (QilIterator ndIter) inline private
Definition at line 1252 of file XmlILVisitor.cs.
    {
        OptimizerPatterns patt = OptimizerPatterns.Read(ndIter);
        if (_qil.IsDebug && ndIter.SourceLine != null)
        {
            _helper.DebugSequencePoint(ndIter.SourceLine);
        }
        if (ndIter.NodeType == QilNodeType.For || ndIter.XmlType.IsSingleton)
        {
            StartForBinding(ndIter, patt);
        }
        else
        {
            StartLetBinding(ndIter);
        }
        XmlILAnnotation.Write(ndIter).CachedIteratorDescriptor = _iterNested;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.Xml.Xsl.IlGen.XmlILVisitor._qil, System.Xml.Xsl.IlGen.GenerateHelper.DebugSequencePoint(), System.Xml.Xsl.Qil.QilExpression.IsDebug, System.Xml.Xsl.IlGen.OptimizerPatterns.Read(), System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.StartLetBinding(), and System.Xml.Xsl.IlGen.XmlILAnnotation.Write().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFilter(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLoop(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort().