Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.EndWriterLoop
EndWriterLoop()
void System.Xml.Xsl.IlGen.XmlILVisitor.EndWriterLoop (QilNode nd, bool hasOnEnd, Label lblOnEnd) inline private
Definition at line 2784 of file XmlILVisitor.cs.
    {
        XmlILConstructInfo xmlILConstructInfo = XmlILConstructInfo.Read(nd);
        if (xmlILConstructInfo.PushToWriterLast)
        {
            _iterCurr.Storage = StorageDescriptor.None();
            if (!nd.XmlType.IsSingleton && hasOnEnd)
            {
                _iterCurr.LoopToEnd(lblOnEnd);
            }
        }
    }
References System.Xml.Dictionary, System.Xml.Xsl.IlGen.StorageDescriptor.None(), and System.Xml.Xsl.IlGen.XmlILConstructInfo.Read().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.CopySequence(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitLoop().