Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength
VisitLength()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength (QilUnary ndSetLen) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 598 of file XmlILVisitor.cs.
    {
        Label label = _helper.DefineLabel();
        OptimizerPatterns optimizerPatterns = OptimizerPatterns.Read(ndSetLen);
        if (CachesResult(ndSetLen.Child))
        {
            NestedVisitEnsureStack(ndSetLen.Child);
            _helper.CallCacheCount(_iterNested.Storage.ItemStorageType);
        }
        else
        {
            _helper.Emit(OpCodes.Ldc_I4_0);
            StartNestedIterator(ndSetLen.Child, label);
            Visit(ndSetLen.Child);
            _iterCurr.EnsureNoCache();
            _iterCurr.DiscardStack();
            _helper.Emit(OpCodes.Ldc_I4_1);
            _helper.Emit(OpCodes.Add);
            if (optimizerPatterns.MatchesPattern(OptimizerPatternName.MaxPosition))
            {
                _helper.Emit(OpCodes.Dup);
                _helper.LoadInteger((int)optimizerPatterns.GetArgument(OptimizerPatternArgument.ElementQName));
                _helper.Emit(OpCodes.Bgt, label);
            }
            _iterCurr.LoopToEnd(label);
            EndNestedIterator(ndSetLen.Child);
        }
        _iterCurr.Storage = StorageDescriptor.Stack(typeof(int), isCached: false);
        return ndSetLen;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Xml.Xsl.IlGen.XmlILVisitor._iterNested, System.Reflection.Emit.OpCodes.Add, System.Reflection.Emit.OpCodes.Bgt, System.Xml.Xsl.IlGen.XmlILVisitor.CachesResult(), System.Xml.Xsl.IlGen.GenerateHelper.CallCacheCount(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.IteratorDescriptor.DiscardStack(), System.Reflection.Emit.OpCodes.Dup, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.IlGen.StorageDescriptor.ItemStorageType, System.Reflection.Emit.OpCodes.Ldc_I4_0, System.Reflection.Emit.OpCodes.Ldc_I4_1, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.IteratorDescriptor.LoopToEnd(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.OptimizerPatterns.Read(), System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.Storage, and System.Xml.Xsl.IlGen.XmlILVisitor.Visit().