Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues
VisitGlobalValues()
void System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues (QilList globalIterators) inline private
Definition at line 61 of file XmlILVisitor.cs.
    {
        foreach (QilIterator globalIterator in globalIterators)
        {
            QilParameter qilParameter = globalIterator as QilParameter;
            MethodInfo globalLocation = XmlILAnnotation.Write(globalIterator).CachedIteratorDescriptor.Storage.GlobalLocation;
            bool isCached = !globalIterator.XmlType.IsSingleton;
            int num = _helper.StaticData.DeclareGlobalValue(globalIterator.DebugName);
            _helper.MethodBegin(globalLocation, globalIterator.SourceLine, initWriters: false);
            Label label = _helper.DefineLabel();
            Label label2 = _helper.DefineLabel();
            _helper.LoadQueryRuntime();
            _helper.LoadInteger(num);
            _helper.Call(XmlILMethods.GlobalComputed);
            _helper.Emit(OpCodes.Brtrue, label);
            StartNestedIterator(globalIterator);
            if (qilParameter != null)
            {
                LocalBuilder locBldr = _helper.DeclareLocal("$$$param", typeof(object));
                _helper.CallGetParameter(qilParameter.Name.LocalName, qilParameter.Name.NamespaceUri);
                _helper.Emit(OpCodes.Stloc, locBldr);
                _helper.Emit(OpCodes.Ldloc, locBldr);
                _helper.Emit(OpCodes.Brfalse, label2);
                _helper.LoadQueryRuntime();
                _helper.LoadInteger(num);
                _helper.LoadQueryRuntime();
                _helper.LoadInteger(_helper.StaticData.DeclareXmlType(XmlQueryTypeFactory.ItemS));
                _helper.Emit(OpCodes.Ldloc, locBldr);
                _helper.Call(XmlILMethods.ChangeTypeXsltResult);
                _helper.CallSetGlobalValue(typeof(object));
                _helper.EmitUnconditionalBranch(OpCodes.Br, label);
            }
            _helper.MarkLabel(label2);
            if (globalIterator.Binding != null)
            {
                _helper.LoadQueryRuntime();
                _helper.LoadInteger(num);
                NestedVisitEnsureStack(globalIterator.Binding, GetItemStorageType(globalIterator), isCached);
                _helper.CallSetGlobalValue(GetStorageType(globalIterator));
            }
            else
            {
                _helper.LoadQueryRuntime();
                GenerateHelper helper = _helper;
                OpCode ldstr = OpCodes.Ldstr;
                string xmlIl_UnknownParam = System.SR.XmlIl_UnknownParam;
                object[] args = new string[2]
                {
                    qilParameter.Name.LocalName,
                    qilParameter.Name.NamespaceUri
                };
                helper.Emit(ldstr, System.SR.Format(xmlIl_UnknownParam, args));
                _helper.Call(XmlILMethods.ThrowException);
            }
            EndNestedIterator(globalIterator);
            _helper.MarkLabel(label);
            _helper.CallGetGlobalValue(num, GetStorageType(globalIterator));
            _helper.MethodEnd();
        }
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Reflection.Emit.OpCodes.Br, System.Reflection.Emit.OpCodes.Brfalse, System.Reflection.Emit.OpCodes.Brtrue, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetGlobalValue(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetParameter(), System.Xml.Xsl.IlGen.GenerateHelper.CallSetGlobalValue(), System.Xml.Xsl.IlGen.XmlILMethods.ChangeTypeXsltResult, System.Xml.Xsl.IlGen.StaticDataManager.DeclareGlobalValue(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Xsl.IlGen.StaticDataManager.DeclareXmlType(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.SR.Format(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.IlGen.XmlILVisitor.GetStorageType(), System.Xml.Xsl.IlGen.XmlILMethods.GlobalComputed, System.Xml.Xsl.XmlQueryTypeFactory.ItemS, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldstr, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin(), System.Xml.Xsl.IlGen.GenerateHelper.MethodEnd(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureStack(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), System.Xml.Xsl.IlGen.GenerateHelper.StaticData, System.Reflection.Emit.OpCodes.Stloc, System.Xml.Xsl.IlGen.XmlILMethods.ThrowException, System.Xml.Xsl.IlGen.XmlILAnnotation.Write(), and System.SR.XmlIl_UnknownParam.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.Visit().