Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitRoot
VisitRoot()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitRoot (QilUnary ndRoot) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1584 of file XmlILVisitor.cs.
    {
        LocalBuilder localBuilder = _helper.DeclareLocal("$$$navRoot", typeof(XPathNavigator));
        SyncToNavigator(localBuilder, ndRoot.Child);
        _helper.Emit(OpCodes.Ldloc, localBuilder);
        _helper.Call(XmlILMethods.NavMoveRoot);
        _iterCurr.Storage = StorageDescriptor.Local(localBuilder, typeof(XPathNavigator), isCached: false);
        return ndRoot;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Reflection.Emit.OpCodes.Ldloc, System.Xml.Xsl.IlGen.StorageDescriptor.Local(), System.Xml.Xsl.IlGen.XmlILMethods.NavMoveRoot, and System.Xml.Xsl.IlGen.XmlILVisitor.SyncToNavigator().