Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.Visit
Visit() [2/2]
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.Visit (QilNode nd) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 169 of file XmlILVisitor.cs.
    {
        if (nd == null)
        {
            return null;
        }
        if (_qil.IsDebug && nd.SourceLine != null && !(nd is QilIterator))
        {
            _helper.DebugSequencePoint(nd.SourceLine);
        }
        switch (XmlILConstructInfo.Read(nd).ConstructMethod)
        {
        case XmlILConstructMethod.WriterThenIterator:
            NestedConstruction(nd);
            break;
        case XmlILConstructMethod.IteratorThenWriter:
            CopySequence(nd);
            break;
        default:
            base.Visit(nd);
            break;
        }
        return nd;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._qil, System.Xml.Xsl.IlGen.XmlILVisitor.CopySequence(), System.Xml.Xsl.IlGen.GenerateHelper.DebugSequencePoint(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilExpression.IsDebug, System.Xml.Xsl.IlGen.XmlILVisitor.NestedConstruction(), and System.Xml.Xsl.IlGen.XmlILConstructInfo.Read().