Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.LoadNameAndType
LoadNameAndType()
GenerateNameType System.Xml.Xsl.IlGen.XmlILVisitor.LoadNameAndType (XPathNodeType nodeType, QilNode ndName, bool isStart, bool callChk) inline private
Definition at line 2557 of file XmlILVisitor.cs.
    {
        _helper.LoadQueryOutput();
        GenerateNameType result = GenerateNameType.StackName;
        if (ndName.NodeType == QilNodeType.LiteralQName)
        {
            if (isStart || !callChk)
            {
                QilName qilName = ndName as QilName;
                string prefix = qilName.Prefix;
                string localName = qilName.LocalName;
                string namespaceUri = qilName.NamespaceUri;
                if (qilName.NamespaceUri.Length == 0)
                {
                    _helper.Emit(OpCodes.Ldstr, qilName.LocalName);
                    return GenerateNameType.LiteralLocalName;
                }
                if (!ValidateNames.ValidateName(prefix, localName, namespaceUri, nodeType, ValidateNames.Flags.CheckPrefixMapping))
                {
                    if (isStart)
                    {
                        _helper.Emit(OpCodes.Ldstr, localName);
                        _helper.Emit(OpCodes.Ldstr, namespaceUri);
                        _helper.Construct(XmlILConstructors.QName);
                        result = GenerateNameType.QName;
                    }
                }
                else
                {
                    _helper.Emit(OpCodes.Ldstr, prefix);
                    _helper.Emit(OpCodes.Ldstr, localName);
                    _helper.Emit(OpCodes.Ldstr, namespaceUri);
                    result = GenerateNameType.LiteralName;
                }
            }
        }
        else if (isStart)
        {
            if (ndName.NodeType == QilNodeType.NameOf)
            {
                NestedVisitEnsureStack((ndName as QilUnary).Child);
                result = GenerateNameType.CopiedName;
            }
            else if (ndName.NodeType == QilNodeType.StrParseQName)
            {
                VisitStrParseQName(ndName as QilBinary, preservePrefix: true);
                result = (((ndName as QilBinary).Right.XmlType.TypeCode != XmlTypeCode.String) ? GenerateNameType.TagNameAndMappings : GenerateNameType.TagNameAndNamespace);
            }
            else
            {
                NestedVisitEnsureStack(ndName);
                result = GenerateNameType.QName;
            }
        }
        return result;
    }
References System.Xml.Dictionary, System.Reflection.Emit.OpCodes.Ldstr, System.prefix, System.Xml.Xsl.IlGen.XmlILConstructors.QName, System.Collections.Generic.Right, and System.Xml.ValidateNames.ValidateName().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttributeCtor(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitElementCtor().