Terraria: System.Xml.Xsl.IlGen.XmlILVisitor.VisitFalse
VisitFalse()
override QilNode System.Xml.Xsl.IlGen.XmlILVisitor.VisitFalse (QilNode ndFalse) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 301 of file XmlILVisitor.cs.
    {
        if (_iterCurr.CurrentBranchingContext != 0)
        {
            _helper.EmitUnconditionalBranch((_iterCurr.CurrentBranchingContext == BranchingContext.OnFalse) ? OpCodes.Brtrue : OpCodes.Brfalse, _iterCurr.LabelBranch);
            _iterCurr.Storage = StorageDescriptor.None();
        }
        else
        {
            _helper.LoadBoolean(boolVal: false);
            _iterCurr.Storage = StorageDescriptor.Stack(typeof(bool), isCached: false);
        }
        return ndFalse;
    }
References System.Xml.Xsl.IlGen.XmlILVisitor._helper, System.Xml.Xsl.IlGen.XmlILVisitor._iterCurr, System.Reflection.Emit.OpCodes.Brfalse, System.Reflection.Emit.OpCodes.Brtrue, System.Xml.Xsl.IlGen.IteratorDescriptor.CurrentBranchingContext, System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Xml.Xsl.IlGen.IteratorDescriptor.LabelBranch, System.Xml.Xsl.IlGen.GenerateHelper.LoadBoolean(), System.Xml.Xsl.IlGen.StorageDescriptor.None(), and System.Xml.Xsl.IlGen.StorageDescriptor.Stack().