Terraria: System.Linq.Expressions.ExpressionExtension.MakeDynamic
MakeDynamic() [7/7]
static DynamicExpression System.Linq.Expressions.ExpressionExtension.MakeDynamic (Type delegateType, CallSiteBinder binder, params Expression[] arguments) inline static
Definition at line 12 of file ExpressionExtension.cs.
    {
        return MakeDynamic(delegateType, binder, (IEnumerable<Expression>)arguments);
    }
References System.Linq.Expressions.ExpressionExtension.MakeDynamic().
Referenced by System.Linq.Expressions.ExpressionExtension.Dynamic(), System.Linq.Expressions.DynamicExpression.MakeDynamic(), System.Linq.Expressions.DynamicExpression.MakeDynamic(), System.Linq.Expressions.DynamicExpression.MakeDynamic(), System.Linq.Expressions.DynamicExpression.MakeDynamic(), System.Linq.Expressions.ExpressionExtension.MakeDynamic(), System.Linq.Expressions.DynamicExpression.MakeDynamic(), System.Linq.Expressions.ExpressionExtension.MakeDynamic(), System.Linq.Expressions.DynamicExpression.MakeDynamic(), System.Linq.Expressions.DynamicExpression1.Rewrite(), System.Linq.Expressions.DynamicExpression2.Rewrite(), System.Linq.Expressions.DynamicExpression3.Rewrite(), System.Linq.Expressions.DynamicExpression4.Rewrite(), System.Linq.Expressions.DynamicExpressionN.Rewrite(), and System.Linq.Expressions.DynamicExpression.Update().