Terraria: System.Linq.Expressions.ExpressionExtension.Dynamic
Dynamic() [2/6]
static DynamicExpression System.Linq.Expressions.ExpressionExtension.Dynamic (CallSiteBinder binder, Type returnType, Expression arg0, Expression arg1) inline static
Definition at line 147 of file ExpressionExtension.cs.
    {
        ContractUtils.RequiresNotNull(binder, "binder");
        ValidateDynamicArgument(arg0, "arg0");
        ValidateDynamicArgument(arg1, "arg1");
        System.Linq.Expressions.Compiler.DelegateHelpers.TypeInfo nextTypeInfo = System.Linq.Expressions.Compiler.DelegateHelpers.GetNextTypeInfo(returnType, System.Linq.Expressions.Compiler.DelegateHelpers.GetNextTypeInfo(arg1.Type, System.Linq.Expressions.Compiler.DelegateHelpers.GetNextTypeInfo(arg0.Type, System.Linq.Expressions.Compiler.DelegateHelpers.NextTypeInfo(typeof(CallSite)))));
        Type delegateType = nextTypeInfo.DelegateType ?? nextTypeInfo.MakeDelegateType(returnType, arg0, arg1);
        return DynamicExpression.Make(returnType, delegateType, binder, arg0, arg1);
    }
References System.Linq.Expressions.Compiler.DelegateHelpers.GetNextTypeInfo(), System.Linq.Expressions.DynamicExpression.Make(), System.Linq.Expressions.Compiler.DelegateHelpers.NextTypeInfo(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), and System.Linq.Expressions.ExpressionExtension.ValidateDynamicArgument().