Terraria: System.Linq.Expressions.ExpressionExtension.ValidateDynamicArgument
ValidateDynamicArgument() [2/2]
static void System.Linq.Expressions.ExpressionExtension.ValidateDynamicArgument (Expression arg, string paramName, int index) inline static private
Definition at line 214 of file ExpressionExtension.cs.
    {
        ExpressionUtils.RequiresCanRead(arg, paramName, index);
        Type type = arg.Type;
        ContractUtils.RequiresNotNull(type, "type");
        TypeUtils.ValidateType(type, "type", allowByRef: true, allowPointer: true);
        if (type == typeof(void))
        {
            throw Error.ArgumentTypeCannotBeVoid();
        }
    }
References System.Linq.Expressions.Error.ArgumentTypeCannotBeVoid(), System.Linq.index, System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.type, and System.Dynamic.Utils.TypeUtils.ValidateType().