Terraria: System.Linq.Expressions.ExpressionExtension.MakeDynamic
MakeDynamic() [1/7]
static DynamicExpression System.Linq.Expressions.ExpressionExtension.MakeDynamic (CallSiteBinder binder, Type returnType, ReadOnlyCollection< Expression > arguments) inline static private
Definition at line 189 of file ExpressionExtension.cs.
    {
        ContractUtils.RequiresNotNull(binder, "binder");
        int count = arguments.Count;
        for (int i = 0; i < count; i++)
        {
            Expression arg = arguments[i];
            ValidateDynamicArgument(arg, "arguments", i);
        }
        Type delegateType = System.Linq.Expressions.Compiler.DelegateHelpers.MakeCallSiteDelegate(arguments, returnType);
        return count switch
        {
            1 => DynamicExpression.Make(returnType, delegateType, binder, arguments[0]),
            2 => DynamicExpression.Make(returnType, delegateType, binder, arguments[0], arguments[1]),
            3 => DynamicExpression.Make(returnType, delegateType, binder, arguments[0], arguments[1], arguments[2]),
            4 => DynamicExpression.Make(returnType, delegateType, binder, arguments[0], arguments[1], arguments[2], arguments[3]),
            _ => DynamicExpression.Make(returnType, delegateType, binder, arguments),
        };
    }
References System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.DynamicExpression.Make(), System.Linq.Expressions.Compiler.DelegateHelpers.MakeCallSiteDelegate(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), and System.Linq.Expressions.ExpressionExtension.ValidateDynamicArgument().