Terraria: System.Linq.Expressions.ExpressionExtension.MakeDynamic
MakeDynamic() [5/7]
static DynamicExpression System.Linq.Expressions.ExpressionExtension.MakeDynamic (Type delegateType, CallSiteBinder binder, Expression arg0, Expression arg1, Expression arg2, Expression arg3) inline static
Definition at line 100 of file ExpressionExtension.cs.
    {
        ContractUtils.RequiresNotNull(delegateType, "delegateType");
        ContractUtils.RequiresNotNull(binder, "binder");
        if (!delegateType.IsSubclassOf(typeof(MulticastDelegate)))
        {
            throw Error.TypeMustBeDerivedFromSystemDelegate();
        }
        MethodInfo validMethodForDynamic = GetValidMethodForDynamic(delegateType);
        ParameterInfo[] parametersCached = validMethodForDynamic.GetParametersCached();
        ExpressionUtils.ValidateArgumentCount(validMethodForDynamic, ExpressionType.Dynamic, 5, parametersCached);
        ValidateDynamicArgument(arg0, "arg0");
        ExpressionUtils.ValidateOneArgument(validMethodForDynamic, ExpressionType.Dynamic, arg0, parametersCached[1], "delegateType", "arg0");
        ValidateDynamicArgument(arg1, "arg1");
        ExpressionUtils.ValidateOneArgument(validMethodForDynamic, ExpressionType.Dynamic, arg1, parametersCached[2], "delegateType", "arg1");
        ValidateDynamicArgument(arg2, "arg2");
        ExpressionUtils.ValidateOneArgument(validMethodForDynamic, ExpressionType.Dynamic, arg2, parametersCached[3], "delegateType", "arg2");
        ValidateDynamicArgument(arg3, "arg3");
        ExpressionUtils.ValidateOneArgument(validMethodForDynamic, ExpressionType.Dynamic, arg3, parametersCached[4], "delegateType", "arg3");
        return DynamicExpression.Make(validMethodForDynamic.GetReturnType(), delegateType, binder, arg0, arg1, arg2, arg3);
    }
References System.Linq.Expressions.ExpressionExtension.GetValidMethodForDynamic(), System.Linq.Expressions.DynamicExpression.Make(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Linq.Expressions.Error.TypeMustBeDerivedFromSystemDelegate(), System.Dynamic.Utils.ExpressionUtils.ValidateArgumentCount(), System.Linq.Expressions.ExpressionExtension.ValidateDynamicArgument(), and System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument().