Terraria: System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.DecodeCore
DecodeCore()
static void System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.DecodeCore (ref AsnValueReader reader, Asn1Tag expectedTag, ReadOnlyMemory< byte > rebind, out RSAPrivateKeyAsn decoded) inline static private
Definition at line 46 of file RSAPrivateKeyAsn.cs.
    {
        decoded = default(RSAPrivateKeyAsn);
        AsnValueReader asnValueReader = reader.ReadSequence(expectedTag);
        if (!asnValueReader.TryReadInt32(out decoded.Version))
        {
            asnValueReader.ThrowIfNotEmpty();
        }
        decoded.Modulus = asnValueReader.ReadInteger();
        decoded.PublicExponent = asnValueReader.ReadInteger();
        decoded.PrivateExponent = asnValueReader.ReadInteger();
        decoded.Prime1 = asnValueReader.ReadInteger();
        decoded.Prime2 = asnValueReader.ReadInteger();
        decoded.Exponent1 = asnValueReader.ReadInteger();
        decoded.Exponent2 = asnValueReader.ReadInteger();
        decoded.Coefficient = asnValueReader.ReadInteger();
        asnValueReader.ThrowIfNotEmpty();
    }
References System.Formats.Asn1.AsnValueReader.ReadInteger(), System.Formats.Asn1.AsnValueReader.ReadSequence(), System.Formats.Asn1.AsnValueReader.ThrowIfNotEmpty(), and System.Formats.Asn1.AsnValueReader.TryReadInt32().
Referenced by System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Decode().