Terraria: System.Data.XDRSchema.LoadSchema
LoadSchema()
void System.Data.XDRSchema.LoadSchema (XmlElement schemaRoot, DataSet ds) inline package
Definition at line 89 of file XDRSchema.cs.
    {
        if (schemaRoot == null)
        {
            return;
        }
        _schemaRoot = schemaRoot;
        _ds = ds;
        _schemaName = schemaRoot.GetAttribute("name");
        _schemaUri = string.Empty;
        if (_schemaName == null || _schemaName.Length == 0)
        {
            _schemaName = "NewDataSet";
        }
        ds.Namespace = _schemaUri;
        for (XmlNode xmlNode = schemaRoot.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            if (xmlNode is XmlElement)
            {
                XmlElement node = (XmlElement)xmlNode;
                if (XMLSchema.FEqualIdentity(node, "ElementType", "urn:schemas-microsoft-com:xml-data"))
                {
                    HandleTable(node);
                }
            }
        }
        _schemaName = XmlConvert.DecodeName(_schemaName);
        if (ds.Tables[_schemaName] == null)
        {
            ds.DataSetName = _schemaName;
        }
    }
References System.Data.XDRSchema._ds, System.Data.XDRSchema._schemaName, System.Data.XDRSchema._schemaRoot, System.Data.XDRSchema._schemaUri, System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.XMLSchema.FEqualIdentity(), System.Xml.XmlNode.FirstChild, and System.Data.XDRSchema.HandleTable().