Terraria: System.Data.XDRSchema.HandleTypeNode
HandleTypeNode()
void System.Data.XDRSchema.HandleTypeNode (XmlElement typeNode, DataTable table, ArrayList tableChildren) inline package
Definition at line 460 of file XDRSchema.cs.
    {
        for (XmlNode xmlNode = typeNode.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            if (!(xmlNode is XmlElement))
            {
                continue;
            }
            if (XMLSchema.FEqualIdentity(xmlNode, "element", "urn:schemas-microsoft-com:xml-data"))
            {
                DataTable dataTable = HandleTable((XmlElement)xmlNode);
                if (dataTable != null)
                {
                    tableChildren.Add(dataTable);
                    continue;
                }
            }
            if (XMLSchema.FEqualIdentity(xmlNode, "attribute", "urn:schemas-microsoft-com:xml-data") || XMLSchema.FEqualIdentity(xmlNode, "element", "urn:schemas-microsoft-com:xml-data"))
            {
                HandleColumn((XmlElement)xmlNode, table);
            }
        }
    }
References System.Xml.Dictionary, System.Data.XMLSchema.FEqualIdentity(), System.Xml.XmlNode.FirstChild, System.Data.XDRSchema.HandleColumn(), and System.Data.XDRSchema.HandleTable().
Referenced by System.Data.XDRSchema.InstantiateTable().