Terraria: System.Data.XDRSchema.GetMinMax
GetMinMax() [2/2]
void System.Data.XDRSchema.GetMinMax (XmlElement elNode, ref int minOccurs, ref int maxOccurs) inline package
Definition at line 415 of file XDRSchema.cs.
    {
        GetMinMax(elNode, isAttribute: false, ref minOccurs, ref maxOccurs);
    }
References System.Xml.Dictionary, and System.Data.XDRSchema.GetMinMax().
Referenced by System.Data.XDRSchema.GetMinMax(), System.Data.XDRSchema.HandleColumn(), System.Data.XDRSchema.InstantiateSimpleTable(), System.Data.XDRSchema.InstantiateTable(), and System.Data.XDRSchema.IsXDRField().