Terraria: System.Data.XDRSchema.InstantiateTable
InstantiateTable()
DataTable System.Data.XDRSchema.InstantiateTable (DataSet dataSet, XmlElement node, XmlElement typeNode) inline package
Definition at line 485 of file XDRSchema.cs.
    {
        string name = string.Empty;
        XmlAttributeCollection attributes = node.Attributes;
        int minOccurs = 1;
        int maxOccurs = 1;
        string text = null;
        ArrayList arrayList = new ArrayList();
        DataTable table;
        if (attributes.Count > 0)
        {
            name = GetInstanceName(node);
            table = dataSet.Tables.GetTable(name, _schemaUri);
            if (table != null)
            {
                return table;
            }
        }
        table = new DataTable(XmlConvert.DecodeName(name));
        table.Namespace = _schemaUri;
        GetMinMax(node, ref minOccurs, ref maxOccurs);
        table.MinOccurs = minOccurs;
        table.MaxOccurs = maxOccurs;
        _ds.Tables.Add(table);
        HandleTypeNode(typeNode, table, arrayList);
        XMLSchema.SetProperties(table, attributes);
        if (text != null)
        {
            string[] array = text.TrimEnd(null).Split((char[]?)null);
            int num = array.Length;
            DataColumn[] array2 = new DataColumn[num];
            for (int i = 0; i < num; i++)
            {
                DataColumn dataColumn = table.Columns[array[i], _schemaUri];
                if (dataColumn == null)
                {
                    throw ExceptionBuilder.ElementTypeNotFound(array[i]);
                }
                array2[i] = dataColumn;
            }
            table.PrimaryKey = array2;
        }
        foreach (DataTable item in arrayList)
        {
            DataRelation dataRelation = null;
            DataRelationCollection childRelations = table.ChildRelations;
            for (int j = 0; j < childRelations.Count; j++)
            {
                if (childRelations[j].Nested && item == childRelations[j].ChildTable)
                {
                    dataRelation = childRelations[j];
                }
            }
            if (dataRelation == null)
            {
                DataColumn dataColumn2 = table.AddUniqueKey();
                DataColumn childColumn = item.AddForeignKey(dataColumn2);
                dataRelation = new DataRelation(table.TableName + "_" + item.TableName, dataColumn2, childColumn, createConstraints: true);
                dataRelation.CheckMultipleNested = false;
                dataRelation.Nested = true;
                item.DataSet.Relations.Add(dataRelation);
                dataRelation.CheckMultipleNested = true;
            }
        }
        return table;
    }
References System.Data.XDRSchema._ds, System.Data.XDRSchema._schemaUri, System.Data.DataRelationCollection.Add(), System.Data.DataTableCollection.Add(), System.array, System.Data.DataTable.Columns, System.Xml.XmlAttributeCollection.Count, System.Data.DataRelation.DataSet, System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.ExceptionBuilder.ElementTypeNotFound(), System.Data.XDRSchema.GetInstanceName(), System.Data.XDRSchema.GetMinMax(), System.Data.XDRSchema.HandleTypeNode(), System.item, System.Data.DataSet.Relations, System.Data.XMLSchema.SetProperties(), System.Data.DataSet.Tables, and System.text.
Referenced by System.Data.XDRSchema.HandleTable().