Terraria: System.IO.Pipes.AnonymousPipeServerStream.Create
Create() [2/2]
void System.IO.Pipes.AnonymousPipeServerStream.Create (PipeDirection direction, HandleInheritability inheritability, int bufferSize, PipeSecurity pipeSecurity) inline private
Definition at line 154 of file AnonymousPipeServerStream.cs.
    {
        GCHandle pinningHandle = default(GCHandle);
        bool flag;
        SafePipeHandle hWritePipe;
        try
        {
            global::Interop.Kernel32.SECURITY_ATTRIBUTES lpPipeAttributes = PipeStream.GetSecAttrs(inheritability, pipeSecurity, ref pinningHandle);
            flag = ((direction != PipeDirection.In) ? global::Interop.Kernel32.CreatePipe(out _clientHandle, out hWritePipe, ref lpPipeAttributes, bufferSize) : global::Interop.Kernel32.CreatePipe(out hWritePipe, out _clientHandle, ref lpPipeAttributes, bufferSize));
        }
        finally
        {
            if (pinningHandle.IsAllocated)
            {
                pinningHandle.Free();
            }
        }
        if (!flag)
        {
            throw System.IO.Win32Marshal.GetExceptionForLastWin32Error();
        }
        if (!global::Interop.Kernel32.DuplicateHandle(global::Interop.Kernel32.GetCurrentProcess(), hWritePipe, global::Interop.Kernel32.GetCurrentProcess(), out var lpTargetHandle, 0u, bInheritHandle: false, 2u))
        {
            throw System.IO.Win32Marshal.GetExceptionForLastWin32Error();
        }
        hWritePipe.Dispose();
        InitializeHandle(lpTargetHandle, isExposed: false, isAsync: false);
        base.State = PipeState.Connected;
    }
References System.IO.Pipes.AnonymousPipeServerStream._clientHandle, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Runtime.InteropServices.GCHandle.Free(), System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.IO.Pipes.PipeStream.GetSecAttrs(), System.IO.Pipes.PipeStream.InitializeHandle(), and System.Runtime.InteropServices.GCHandle.IsAllocated.