Terraria: System.Data.XDRSchema.HandleColumn
HandleColumn()
void System.Data.XDRSchema.HandleColumn (XmlElement node, DataTable table) inline package
Definition at line 295 of file XDRSchema.cs.
    {
        int minOccurs = 0;
        int maxOccurs = 1;
        string name;
        DataColumn dataColumn;
        if (node.Attributes.Count > 0)
        {
            string attribute = node.GetAttribute("ref");
            if (attribute != null && attribute.Length > 0)
            {
                return;
            }
            string text = (name = GetInstanceName(node));
            dataColumn = table.Columns[name, _schemaUri];
            if (dataColumn != null)
            {
                if (dataColumn.ColumnMapping == MappingType.Attribute)
                {
                    if (XMLSchema.FEqualIdentity(node, "attribute", "urn:schemas-microsoft-com:xml-data"))
                    {
                        throw ExceptionBuilder.DuplicateDeclaration(text);
                    }
                }
                else if (XMLSchema.FEqualIdentity(node, "element", "urn:schemas-microsoft-com:xml-data"))
                {
                    throw ExceptionBuilder.DuplicateDeclaration(text);
                }
                name = XMLSchema.GenUniqueColumnName(text, table);
            }
        }
        else
        {
            name = string.Empty;
        }
        XmlElement xmlElement = FindTypeNode(node);
        SimpleType simpleType = null;
        string attribute2;
        if (xmlElement == null)
        {
            attribute2 = node.GetAttribute("type");
            throw ExceptionBuilder.UndefinedDatatype(attribute2);
        }
        attribute2 = xmlElement.GetAttribute("type", "urn:schemas-microsoft-com:datatypes");
        string attribute3 = xmlElement.GetAttribute("values", "urn:schemas-microsoft-com:datatypes");
        Type type;
        if (attribute2 == null || attribute2.Length == 0)
        {
            attribute2 = string.Empty;
            type = typeof(string);
        }
        else
        {
            type = ParseDataType(attribute2, attribute3);
            if (attribute2 == "float")
            {
                attribute2 = string.Empty;
            }
            if (attribute2 == "char")
            {
                attribute2 = string.Empty;
                simpleType = SimpleType.CreateSimpleType(StorageType.Char, type);
            }
            if (attribute2 == "enumeration")
            {
                attribute2 = string.Empty;
                simpleType = SimpleType.CreateEnumeratedType(attribute3);
            }
            if (attribute2 == "bin.base64")
            {
                attribute2 = string.Empty;
                simpleType = SimpleType.CreateByteArrayType("base64");
            }
            if (attribute2 == "bin.hex")
            {
                attribute2 = string.Empty;
                simpleType = SimpleType.CreateByteArrayType("hex");
            }
        }
        bool flag = XMLSchema.FEqualIdentity(node, "attribute", "urn:schemas-microsoft-com:xml-data");
        GetMinMax(node, flag, ref minOccurs, ref maxOccurs);
        string text2 = null;
        text2 = node.GetAttribute("default");
        bool flag2 = false;
        dataColumn = new DataColumn(XmlConvert.DecodeName(name), type, null, (!flag) ? MappingType.Element : MappingType.Attribute);
        XMLSchema.SetProperties(dataColumn, node.Attributes);
        dataColumn.XmlDataType = attribute2;
        dataColumn.SimpleType = simpleType;
        dataColumn.AllowDBNull = minOccurs == 0 || flag2;
        dataColumn.Namespace = (flag ? string.Empty : _schemaUri);
        if (node.Attributes != null)
        {
            for (int i = 0; i < node.Attributes.Count; i++)
            {
                if (node.Attributes[i].NamespaceURI == "urn:schemas-microsoft-com:xml-msdata" && node.Attributes[i].LocalName == "Expression")
                {
                    dataColumn.Expression = node.Attributes[i].Value;
                    break;
                }
            }
        }
        string attribute4 = node.GetAttribute("targetNamespace");
        if (attribute4 != null && attribute4.Length > 0)
        {
            dataColumn.Namespace = attribute4;
        }
        table.Columns.Add(dataColumn);
        if (text2 != null && text2.Length != 0)
        {
            try
            {
                dataColumn.DefaultValue = SqlConvert.ChangeTypeForXML(text2, type);
            }
            catch (FormatException)
            {
                throw ExceptionBuilder.CannotConvert(text2, type.FullName);
            }
        }
    }
References System.Data.XDRSchema._schemaUri, System.Data.DataColumnCollection.Add(), System.Data.ExceptionBuilder.CannotConvert(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.DataTable.Columns, System.Data.SimpleType.CreateByteArrayType(), System.Data.SimpleType.CreateEnumeratedType(), System.Data.SimpleType.CreateSimpleType(), System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.ExceptionBuilder.DuplicateDeclaration(), System.Data.XMLSchema.FEqualIdentity(), System.Data.XDRSchema.FindTypeNode(), System.Data.XMLSchema.GenUniqueColumnName(), System.Data.XDRSchema.GetInstanceName(), System.Data.XDRSchema.GetMinMax(), System.Data.XDRSchema.ParseDataType(), System.Data.XMLSchema.SetProperties(), System.text, System.type, and System.Data.ExceptionBuilder.UndefinedDatatype().
Referenced by System.Data.XDRSchema.HandleTypeNode(), and System.Data.XDRSchema.InstantiateSimpleTable().