Terraria: System.Data.XDRSchema.FindTypeNode
FindTypeNode()
XmlElement System.Data.XDRSchema.FindTypeNode (XmlElement node) inline package
Definition at line 122 of file XDRSchema.cs.
    {
        if (XMLSchema.FEqualIdentity(node, "ElementType", "urn:schemas-microsoft-com:xml-data"))
        {
            return node;
        }
        string attribute = node.GetAttribute("type");
        if (XMLSchema.FEqualIdentity(node, "element", "urn:schemas-microsoft-com:xml-data") || XMLSchema.FEqualIdentity(node, "attribute", "urn:schemas-microsoft-com:xml-data"))
        {
            if (attribute == null || attribute.Length == 0)
            {
                return null;
            }
            XmlNode xmlNode = node.OwnerDocument.FirstChild;
            XmlNode ownerDocument = node.OwnerDocument;
            while (xmlNode != ownerDocument)
            {
                if (((XMLSchema.FEqualIdentity(xmlNode, "ElementType", "urn:schemas-microsoft-com:xml-data") && XMLSchema.FEqualIdentity(node, "element", "urn:schemas-microsoft-com:xml-data")) || (XMLSchema.FEqualIdentity(xmlNode, "AttributeType", "urn:schemas-microsoft-com:xml-data") && XMLSchema.FEqualIdentity(node, "attribute", "urn:schemas-microsoft-com:xml-data"))) && xmlNode is XmlElement && ((XmlElement)xmlNode).GetAttribute("name") == attribute)
                {
                    return (XmlElement)xmlNode;
                }
                if (xmlNode.FirstChild != null)
                {
                    xmlNode = xmlNode.FirstChild;
                    continue;
                }
                if (xmlNode.NextSibling != null)
                {
                    xmlNode = xmlNode.NextSibling;
                    continue;
                }
                while (xmlNode != ownerDocument)
                {
                    xmlNode = xmlNode.ParentNode;
                    if (xmlNode.NextSibling != null)
                    {
                        xmlNode = xmlNode.NextSibling;
                        break;
                    }
                }
            }
            return null;
        }
        return null;
    }
References System.Xml.Dictionary, System.Data.XMLSchema.FEqualIdentity(), System.Xml.XmlNode.FirstChild, System.Xml.XmlElement.GetAttribute(), System.Xml.XmlNode.NextSibling, System.Xml.XmlNode.OwnerDocument, and System.Xml.XmlNode.ParentNode.
Referenced by System.Data.XDRSchema.HandleColumn(), and System.Data.XDRSchema.HandleTable().