Terraria: System.Threading.Barrier.SignalAndWait
SignalAndWait() [4/6]
bool System.Threading.Barrier.SignalAndWait (int millisecondsTimeout, CancellationToken cancellationToken) inline
Definition at line 245 of file Barrier.cs.
    {
        ThrowIfDisposed();
        cancellationToken.ThrowIfCancellationRequested();
        if (millisecondsTimeout < -1)
        {
            throw new ArgumentOutOfRangeException("millisecondsTimeout", millisecondsTimeout, System.SR.Barrier_SignalAndWait_ArgumentOutOfRange);
        }
        if (_actionCallerID != 0 && Environment.CurrentManagedThreadId == _actionCallerID)
        {
            throw new InvalidOperationException(System.SR.Barrier_InvalidOperation_CalledFromPHA);
        }
        SpinWait spinWait = default(SpinWait);
        int current;
        int total;
        bool sense;
        long currentPhaseNumber;
        while (true)
        {
            int currentTotalCount = _currentTotalCount;
            GetCurrentTotal(currentTotalCount, out current, out total, out sense);
            currentPhaseNumber = CurrentPhaseNumber;
            if (total == 0)
            {
                throw new InvalidOperationException(System.SR.Barrier_SignalAndWait_InvalidOperation_ZeroTotal);
            }
            if (current == 0 && sense != (CurrentPhaseNumber % 2 == 0))
            {
                throw new InvalidOperationException(System.SR.Barrier_SignalAndWait_InvalidOperation_ThreadsExceeded);
            }
            if (current + 1 == total)
            {
                if (SetCurrentTotal(currentTotalCount, 0, total, !sense))
                {
                    if (CdsSyncEtwBCLProvider.Log.IsEnabled())
                    {
                        CdsSyncEtwBCLProvider.Log.Barrier_PhaseFinished(sense, CurrentPhaseNumber);
                    }
                    FinishPhase(sense);
                    return true;
                }
            }
            else if (SetCurrentTotal(currentTotalCount, current + 1, total, sense))
            {
                break;
            }
            spinWait.SpinOnce(-1);
        }
        ManualResetEventSlim currentPhaseEvent = (sense ? _evenEvent : _oddEvent);
        bool flag = false;
        bool flag2 = false;
        try
        {
            flag2 = DiscontinuousWait(currentPhaseEvent, millisecondsTimeout, cancellationToken, currentPhaseNumber);
        }
        catch (OperationCanceledException)
        {
            flag = true;
        }
        catch (ObjectDisposedException)
        {
            if (currentPhaseNumber >= CurrentPhaseNumber)
            {
                throw;
            }
            flag2 = true;
        }
        if (!flag2)
        {
            spinWait.Reset();
            while (true)
            {
                int currentTotalCount = _currentTotalCount;
                GetCurrentTotal(currentTotalCount, out current, out total, out var sense2);
                if (currentPhaseNumber < CurrentPhaseNumber || sense != sense2)
                {
                    break;
                }
                if (SetCurrentTotal(currentTotalCount, current - 1, total, sense))
                {
                    if (flag)
                    {
                        throw new OperationCanceledException(System.SR.Common_OperationCanceled, cancellationToken);
                    }
                    return false;
                }
                spinWait.SpinOnce(-1);
            }
            WaitCurrentPhase(currentPhaseEvent, currentPhaseNumber);
        }
        if (_exception != null)
        {
            throw new BarrierPostPhaseException(_exception);
        }
        return true;
    }
References System.Threading.Barrier._actionCallerID, System.Threading.Barrier._currentTotalCount, System.Threading.Barrier._evenEvent, System.Threading.Barrier._exception, System.Threading.Barrier._oddEvent, System.SR.Barrier_InvalidOperation_CalledFromPHA, System.SR.Barrier_SignalAndWait_ArgumentOutOfRange, System.SR.Barrier_SignalAndWait_InvalidOperation_ThreadsExceeded, System.SR.Barrier_SignalAndWait_InvalidOperation_ZeroTotal, System.cancellationToken, System.SR.Common_OperationCanceled, System.Environment.CurrentManagedThreadId, System.Threading.Barrier.CurrentPhaseNumber, System.Threading.Barrier.DiscontinuousWait(), System.Threading.Barrier.FinishPhase(), System.Threading.Barrier.GetCurrentTotal(), System.Threading.CdsSyncEtwBCLProvider.Log, System.millisecondsTimeout, System.Threading.SpinWait.Reset(), System.Threading.Barrier.SetCurrentTotal(), System.Threading.SpinWait.SpinOnce(), System.Threading.Barrier.ThrowIfDisposed(), and System.Threading.Barrier.WaitCurrentPhase().