Terraria: System.Security.Cryptography.X509Certificates.X509Chain.Reset
Reset()
void System.Security.Cryptography.X509Certificates.X509Chain.Reset () inline
Definition at line 164 of file X509Chain.cs.
    {
        _lazyChainStatus = null;
        _chainElements = null;
        _useMachineContext = false;
        IChainPal pal = _pal;
        _pal = null;
        pal?.Dispose();
    }
References System.Security.Cryptography.X509Certificates.X509Chain._chainElements, System.Security.Cryptography.X509Certificates.X509Chain._lazyChainStatus, System.Security.Cryptography.X509Certificates.X509Chain._pal, System.Security.Cryptography.X509Certificates.X509Chain._useMachineContext, and System.IDisposable.Dispose().
Referenced by System.Security.Cryptography.X509Certificates.X509Chain.Build(), and System.Security.Cryptography.X509Certificates.X509Chain.Dispose().