Terraria: System.Security.Cryptography.X509Certificates.X509Chain.Build
Build() [2/2]
bool System.Security.Cryptography.X509Certificates.X509Chain.Build (X509Certificate2 certificate, bool throwOnException) inline package
Definition at line 106 of file X509Chain.cs.
    {
        lock (_syncRoot)
        {
            if (certificate == null || certificate.Pal == null)
            {
                throw new ArgumentException(System.SR.Cryptography_InvalidContextHandle, "certificate");
            }
            if (_chainPolicy != null && _chainPolicy.CustomTrustStore != null)
            {
                if (_chainPolicy.TrustMode == X509ChainTrustMode.System && _chainPolicy.CustomTrustStore.Count > 0)
                {
                    throw new CryptographicException(System.SR.Cryptography_CustomTrustCertsInSystemMode, "TrustMode");
                }
                foreach (X509Certificate2 item in _chainPolicy.CustomTrustStore)
                {
                    if (item == null || item.Handle == IntPtr.Zero)
                    {
                        throw new CryptographicException(System.SR.Cryptography_InvalidTrustCertificate, "CustomTrustStore");
                    }
                }
            }
            Reset();
            X509ChainPolicy chainPolicy = ChainPolicy;
            _pal = ChainPal.BuildChain(_useMachineContext, certificate.Pal, chainPolicy._extraStore, chainPolicy._applicationPolicy, chainPolicy._certificatePolicy, chainPolicy.RevocationMode, chainPolicy.RevocationFlag, chainPolicy.CustomTrustStore, chainPolicy.TrustMode, chainPolicy.VerificationTime, chainPolicy.UrlRetrievalTimeout, chainPolicy.DisableCertificateDownloads);
            if (_pal == null)
            {
                return false;
            }
            _chainElements = new X509ChainElementCollection(_pal.ChainElements);
            Exception exception;
            bool? flag = _pal.Verify(chainPolicy.VerificationFlags, out exception);
            if (!flag.HasValue)
            {
                if (throwOnException)
                {
                    throw exception;
                }
                flag = false;
            }
            return flag.Value;
        }
    }
References System.Security.Cryptography.X509Certificates.X509ChainPolicy._applicationPolicy, System.Security.Cryptography.X509Certificates.X509ChainPolicy._certificatePolicy, System.Security.Cryptography.X509Certificates.X509Chain._chainElements, System.Security.Cryptography.X509Certificates.X509Chain._chainPolicy, System.Security.Cryptography.X509Certificates.X509ChainPolicy._extraStore, System.Security.Cryptography.X509Certificates.X509Chain._pal, System.Security.Cryptography.X509Certificates.X509Chain._syncRoot, System.Security.Cryptography.X509Certificates.X509Chain._useMachineContext, Internal.Cryptography.Pal.ChainPal.BuildChain(), Internal.Cryptography.Pal.IChainPal.ChainElements, System.Security.Cryptography.X509Certificates.X509Chain.ChainPolicy, System.Collections.CollectionBase.Count, System.SR.Cryptography_CustomTrustCertsInSystemMode, System.SR.Cryptography_InvalidContextHandle, System.SR.Cryptography_InvalidTrustCertificate, System.Security.Cryptography.X509Certificates.X509ChainPolicy.CustomTrustStore, System.Security.Cryptography.X509Certificates.X509ChainPolicy.DisableCertificateDownloads, System.exception, System.item, System.Security.Cryptography.X509Certificates.X509Certificate2.Pal, System.Security.Cryptography.X509Certificates.X509Chain.Reset(), System.Security.Cryptography.X509Certificates.X509ChainPolicy.RevocationFlag, System.Security.Cryptography.X509Certificates.X509ChainPolicy.RevocationMode, System.Security.Cryptography.X509Certificates.X509ChainPolicy.TrustMode, System.Security.Cryptography.X509Certificates.X509ChainPolicy.UrlRetrievalTimeout, System.Security.Cryptography.X509Certificates.X509ChainPolicy.VerificationFlags, System.Security.Cryptography.X509Certificates.X509ChainPolicy.VerificationTime, Internal.Cryptography.Pal.IChainPal.Verify(), and System.IntPtr.Zero.