Terraria: System.Threading.Barrier.SetResetEvents
SetResetEvents()
void System.Threading.Barrier.SetResetEvents (bool observedSense) inline private
Definition at line 385 of file Barrier.cs.
    {
        CurrentPhaseNumber++;
        if (observedSense)
        {
            _oddEvent.Reset();
            _evenEvent.Set();
        }
        else
        {
            _evenEvent.Reset();
            _oddEvent.Set();
        }
    }
References System.Threading.Barrier._evenEvent, System.Threading.Barrier._oddEvent, System.Threading.Barrier.CurrentPhaseNumber, System.Threading.ManualResetEventSlim.Reset(), and System.Threading.ManualResetEventSlim.Set().
Referenced by System.Threading.Barrier.FinishPhase().