Terraria: System.Threading.Barrier.FinishPhase
FinishPhase()
void System.Threading.Barrier.FinishPhase (bool observedSense) inline private
Definition at line 342 of file Barrier.cs.
    {
        if (_postPhaseAction != null)
        {
            try
            {
                _actionCallerID = Environment.CurrentManagedThreadId;
                if (_ownerThreadContext != null)
                {
                    ContextCallback callback = InvokePostPhaseAction;
                    ExecutionContext.Run(_ownerThreadContext, callback, this);
                }
                else
                {
                    _postPhaseAction(this);
                }
                _exception = null;
                return;
            }
            catch (Exception exception)
            {
                _exception = exception;
                return;
            }
            finally
            {
                _actionCallerID = 0;
                SetResetEvents(observedSense);
                if (_exception != null)
                {
                    throw new BarrierPostPhaseException(_exception);
                }
            }
        }
        SetResetEvents(observedSense);
    }
References System.Threading.Barrier._actionCallerID, System.Threading.Barrier._exception, System.Threading.Barrier._ownerThreadContext, System.Threading.Barrier._postPhaseAction, System.Threading.ContextCallback(), System.Environment.CurrentManagedThreadId, System.exception, System.Threading.Barrier.InvokePostPhaseAction(), System.Threading.ExecutionContext.Run(), and System.Threading.Barrier.SetResetEvents().
Referenced by System.Threading.Barrier.RemoveParticipants(), and System.Threading.Barrier.SignalAndWait().