Terraria: System.Threading.Barrier.AddParticipants
AddParticipants()
long System.Threading.Barrier.AddParticipants (int participantCount) inline
Definition at line 107 of file Barrier.cs.
    {
        ThrowIfDisposed();
        if (participantCount < 1)
        {
            throw new ArgumentOutOfRangeException("participantCount", participantCount, System.SR.Barrier_AddParticipants_NonPositive_ArgumentOutOfRange);
        }
        if (participantCount > 32767)
        {
            throw new ArgumentOutOfRangeException("participantCount", System.SR.Barrier_AddParticipants_Overflow_ArgumentOutOfRange);
        }
        if (_actionCallerID != 0 && Environment.CurrentManagedThreadId == _actionCallerID)
        {
            throw new InvalidOperationException(System.SR.Barrier_InvalidOperation_CalledFromPHA);
        }
        SpinWait spinWait = default(SpinWait);
        long num = 0L;
        bool sense;
        while (true)
        {
            int currentTotalCount = _currentTotalCount;
            GetCurrentTotal(currentTotalCount, out var current, out var total, out sense);
            if (participantCount + total > 32767)
            {
                throw new ArgumentOutOfRangeException("participantCount", System.SR.Barrier_AddParticipants_Overflow_ArgumentOutOfRange);
            }
            if (SetCurrentTotal(currentTotalCount, current, total + participantCount, sense))
            {
                break;
            }
            spinWait.SpinOnce(-1);
        }
        long currentPhaseNumber = CurrentPhaseNumber;
        num = ((sense != (currentPhaseNumber % 2 == 0)) ? (currentPhaseNumber + 1) : currentPhaseNumber);
        if (num != currentPhaseNumber)
        {
            if (sense)
            {
                _oddEvent.Wait();
            }
            else
            {
                _evenEvent.Wait();
            }
        }
        else if (sense && _evenEvent.IsSet)
        {
            _evenEvent.Reset();
        }
        else if (!sense && _oddEvent.IsSet)
        {
            _oddEvent.Reset();
        }
        return num;
    }
References System.Threading.Barrier._actionCallerID, System.Threading.Barrier._currentTotalCount, System.Threading.Barrier._evenEvent, System.Threading.Barrier._oddEvent, System.SR.Barrier_AddParticipants_NonPositive_ArgumentOutOfRange, System.SR.Barrier_AddParticipants_Overflow_ArgumentOutOfRange, System.SR.Barrier_InvalidOperation_CalledFromPHA, System.Environment.CurrentManagedThreadId, System.Threading.Barrier.CurrentPhaseNumber, System.Threading.Barrier.GetCurrentTotal(), System.Threading.ManualResetEventSlim.IsSet, System.L, System.Threading.ManualResetEventSlim.Reset(), System.Threading.Barrier.SetCurrentTotal(), System.Threading.SpinWait.SpinOnce(), System.Threading.Barrier.ThrowIfDisposed(), and System.Threading.ManualResetEventSlim.Wait().
Referenced by System.Threading.Barrier.AddParticipant().