Terraria: System.Threading.Barrier.RemoveParticipants
RemoveParticipants()
void System.Threading.Barrier.RemoveParticipants (int participantCount) inline
Definition at line 168 of file Barrier.cs.
    {
        ThrowIfDisposed();
        if (participantCount < 1)
        {
            throw new ArgumentOutOfRangeException("participantCount", participantCount, System.SR.Barrier_RemoveParticipants_NonPositive_ArgumentOutOfRange);
        }
        if (_actionCallerID != 0 && Environment.CurrentManagedThreadId == _actionCallerID)
        {
            throw new InvalidOperationException(System.SR.Barrier_InvalidOperation_CalledFromPHA);
        }
        SpinWait spinWait = default(SpinWait);
        while (true)
        {
            int currentTotalCount = _currentTotalCount;
            GetCurrentTotal(currentTotalCount, out var current, out var total, out var sense);
            if (total < participantCount)
            {
                throw new ArgumentOutOfRangeException("participantCount", System.SR.Barrier_RemoveParticipants_ArgumentOutOfRange);
            }
            if (total - participantCount < current)
            {
                throw new InvalidOperationException(System.SR.Barrier_RemoveParticipants_InvalidOperation);
            }
            int num = total - participantCount;
            if (num > 0 && current == num)
            {
                if (SetCurrentTotal(currentTotalCount, 0, total - participantCount, !sense))
                {
                    FinishPhase(sense);
                    break;
                }
            }
            else if (SetCurrentTotal(currentTotalCount, current, total - participantCount, sense))
            {
                break;
            }
            spinWait.SpinOnce(-1);
        }
    }
References System.Threading.Barrier._actionCallerID, System.Threading.Barrier._currentTotalCount, System.SR.Barrier_InvalidOperation_CalledFromPHA, System.SR.Barrier_RemoveParticipants_ArgumentOutOfRange, System.SR.Barrier_RemoveParticipants_InvalidOperation, System.SR.Barrier_RemoveParticipants_NonPositive_ArgumentOutOfRange, System.Environment.CurrentManagedThreadId, System.Threading.Barrier.FinishPhase(), System.Threading.Barrier.GetCurrentTotal(), System.Threading.Barrier.SetCurrentTotal(), System.Threading.SpinWait.SpinOnce(), and System.Threading.Barrier.ThrowIfDisposed().
Referenced by System.Threading.Barrier.RemoveParticipant().