Terraria: System.Threading.Barrier.SetCurrentTotal
SetCurrentTotal()
bool System.Threading.Barrier.SetCurrentTotal (int currentTotal, int current, int total, bool sense) inline private
Definition at line 83 of file Barrier.cs.
    {
        int num = (current << 16) | total;
        if (!sense)
        {
            num |= int.MinValue;
        }
        return Interlocked.CompareExchange(ref _currentTotalCount, num, currentTotal) == currentTotal;
    }
References System.Threading.Barrier._currentTotalCount, and System.Threading.Interlocked.CompareExchange().
Referenced by System.Threading.Barrier.AddParticipants(), System.Threading.Barrier.RemoveParticipants(), and System.Threading.Barrier.SignalAndWait().