Terraria: System.Threading.Barrier.WaitCurrentPhase
WaitCurrentPhase()
void System.Threading.Barrier.WaitCurrentPhase (ManualResetEventSlim currentPhaseEvent, long observedPhase) inline private
Definition at line 400 of file Barrier.cs.
    {
        SpinWait spinWait = default(SpinWait);
        while (!currentPhaseEvent.IsSet && CurrentPhaseNumber - observedPhase <= 1)
        {
            spinWait.SpinOnce();
        }
    }
References System.Threading.Barrier.CurrentPhaseNumber, System.Threading.ManualResetEventSlim.IsSet, and System.Threading.SpinWait.SpinOnce().
Referenced by System.Threading.Barrier.DiscontinuousWait(), and System.Threading.Barrier.SignalAndWait().