Terraria: SpriteDrawBuffer.QueueSprite
QueueSprite()
void SpriteDrawBuffer.QueueSprite (Vector4 destinationRect, Vector2 origin, VertexColors colors, Vector4 sourceRectangle, Vector2 texCoordTL, Vector2 texCoordBR, Texture2D texture, float depth, float rotation) inline private
     {
         float num = origin.X / sourceRectangle.Z;
         float num2 = origin.Y / sourceRectangle.W;
         float x = destinationRect.X;
         float y = destinationRect.Y;
         float z = destinationRect.Z;
         float w = destinationRect.W;
         float num3 = num * z;
         float num4 = num2 * w;
         float num5;
         float num6;
         if (rotation != 0f)
         {
             num5 = (float)Math.Cos(rotation);
             num6 = (float)Math.Sin(rotation);
         }
         else
         {
             num5 = 1f;
             num6 = 0f;
         }
         if (vertexCount + 4 >= maxSprites * 4)
         {
             maxSprites *= 2;
             CreateBuffers();
         }
         textures[vertexCount / 4] = texture;
         PushVertex(new Vector3(x + num3 * num5 - num4 * num6, y + num3 * num6 + num4 * num5, depth), colors.TopLeftColor, texCoordTL);
         PushVertex(new Vector3(x + (num3 + z) * num5 - num4 * num6, y + (num3 + z) * num6 + num4 * num5, depth), colors.TopRightColor, new Vector2(texCoordBR.X, texCoordTL.Y));
         PushVertex(new Vector3(x + num3 * num5 - (num4 + w) * num6, y + num3 * num6 + (num4 + w) * num5, depth), colors.BottomLeftColor, new Vector2(texCoordTL.X, texCoordBR.Y));
         PushVertex(new Vector3(x + (num3 + z) * num5 - (num4 + w) * num6, y + (num3 + z) * num6 + (num4 + w) * num5, depth), colors.BottomRightColor, texCoordBR);
     }
References VertexColors.BottomLeftColor, VertexColors.BottomRightColor, CreateBuffers(), maxSprites, PushVertex(), textures, VertexColors.TopLeftColor, VertexColors.TopRightColor, and vertexCount.
Referenced by Draw().