Terraria: Terraria.GameContent.TeleportPylonsSystem.OnPlayerJoining
OnPlayerJoining()
void Terraria.GameContent.TeleportPylonsSystem.OnPlayerJoining (int playerIndex) inline
Implements Terraria.GameContent.IOnPlayerJoining.
Definition at line 341 of file TeleportPylonsSystem.cs.
    {
        foreach (TeleportPylonInfo pylon in _pylons)
        {
            NetManager.Instance.SendToClient(NetTeleportPylonModule.SerializePylonWasAddedOrRemoved(pylon, NetTeleportPylonModule.SubPacketType.PylonWasAdded), playerIndex);
        }
    }
References Terraria.GameContent.TeleportPylonsSystem._pylons, Terraria.Net.NetManager.Instance, Terraria.Net.NetManager.SendToClient(), and Terraria.GameContent.NetModules.NetTeleportPylonModule.SerializePylonWasAddedOrRemoved().
Referenced by Terraria.MessageBuffer.GetData().