Terraria: System.Data.SqlTypes.SqlXmlStreamWrapper.Seek
Seek()
override long System.Data.SqlTypes.SqlXmlStreamWrapper.Seek (long offset, SeekOrigin origin) inline
Definition at line 87 of file SqlXmlStreamWrapper.cs.
    {
        long num = 0L;
        ThrowIfStreamClosed("Seek");
        ThrowIfStreamCannotSeek("Seek");
        switch (origin)
        {
        case SeekOrigin.Begin:
            if (offset < 0 || offset > _stream.Length)
            {
                throw new ArgumentOutOfRangeException("offset");
            }
            _lPosition = offset;
            break;
        case SeekOrigin.Current:
            num = _lPosition + offset;
            if (num < 0 || num > _stream.Length)
            {
                throw new ArgumentOutOfRangeException("offset");
            }
            _lPosition = num;
            break;
        case SeekOrigin.End:
            num = _stream.Length + offset;
            if (num < 0 || num > _stream.Length)
            {
                throw new ArgumentOutOfRangeException("offset");
            }
            _lPosition = num;
            break;
        default:
            throw ADP.InvalidSeekOrigin("offset");
        }
        return _lPosition;
    }
References System.Data.SqlTypes.SqlXmlStreamWrapper._lPosition, System.Data.SqlTypes.SqlXmlStreamWrapper._stream, System.Data.Common.ADP.InvalidSeekOrigin(), System.L, System.IO.Stream.Length, System.offset, System.Data.SqlTypes.SqlXmlStreamWrapper.ThrowIfStreamCannotSeek(), and System.Data.SqlTypes.SqlXmlStreamWrapper.ThrowIfStreamClosed().