Terraria: System.Data.SqlTypes.SqlXmlStreamWrapper.Write
Write() [1/2]
override void System.Data.SqlTypes.SqlXmlStreamWrapper.Write (byte[] buffer, int offset, int count) inline
Definition at line 148 of file SqlXmlStreamWrapper.cs.
    {
        ThrowIfStreamClosed("Write");
        ThrowIfStreamCannotWrite("Write");
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (offset < 0 || offset > buffer.Length)
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if (count < 0 || count > buffer.Length - offset)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (_stream.CanSeek && _stream.Position != _lPosition)
        {
            _stream.Seek(_lPosition, SeekOrigin.Begin);
        }
        _stream.Write(buffer, offset, count);
        _lPosition += count;
    }
References System.Data.SqlTypes.SqlXmlStreamWrapper._lPosition, System.Data.SqlTypes.SqlXmlStreamWrapper._stream, System.buffer, System.IO.Stream.CanSeek, System.count, System.offset, System.IO.Stream.Position, System.IO.Stream.Seek(), System.Data.SqlTypes.SqlXmlStreamWrapper.ThrowIfStreamCannotWrite(), System.Data.SqlTypes.SqlXmlStreamWrapper.ThrowIfStreamClosed(), and System.IO.Stream.Write().