Terraria: System.Data.SqlTypes.SqlXmlStreamWrapper.SetLength
SetLength()
override void System.Data.SqlTypes.SqlXmlStreamWrapper.SetLength (long value) inline
Definition at line 201 of file SqlXmlStreamWrapper.cs.
    {
        ThrowIfStreamClosed("SetLength");
        ThrowIfStreamCannotSeek("SetLength");
        _stream.SetLength(value);
        if (_lPosition > value)
        {
            _lPosition = value;
        }
    }
References System.Data.SqlTypes.SqlXmlStreamWrapper._lPosition, System.Data.SqlTypes.SqlXmlStreamWrapper._stream, System.IO.Stream.SetLength(), System.Data.SqlTypes.SqlXmlStreamWrapper.ThrowIfStreamCannotSeek(), System.Data.SqlTypes.SqlXmlStreamWrapper.ThrowIfStreamClosed(), and System.value.