Terraria: System.Data.SqlTypes.SqlXmlStreamWrapper.ThrowIfStreamCannotRead
ThrowIfStreamCannotRead()
void System.Data.SqlTypes.SqlXmlStreamWrapper.ThrowIfStreamCannotRead (string method) inline private
Definition at line 240 of file SqlXmlStreamWrapper.cs.
    {
        if (!_stream.CanRead)
        {
            throw new NotSupportedException(SQLResource.InvalidOpStreamNonReadable(method));
        }
    }
References System.Data.SqlTypes.SqlXmlStreamWrapper._stream, System.IO.Stream.CanRead, and System.Data.SqlTypes.SQLResource.InvalidOpStreamNonReadable().
Referenced by System.Data.SqlTypes.SqlXmlStreamWrapper.Read(), and System.Data.SqlTypes.SqlXmlStreamWrapper.ReadByte().