Terraria: System.Xml.Schema.FacetsChecker.FacetsCompiler.CompilePatternFacet
CompilePatternFacet()
void System.Xml.Schema.FacetsChecker.FacetsCompiler.CompilePatternFacet (XmlSchemaPatternFacet facet) inline package
Definition at line 137 of file FacetsChecker.cs.
        {
            CheckProhibitedFlag(facet, RestrictionFlags.Pattern, System.SR.Sch_PatternFacetProhibited);
            if (_firstPattern)
            {
                _regStr = new StringBuilder();
                _regStr.Append('(');
                _regStr.Append(facet.Value);
                _pattern_facet = facet;
                _firstPattern = false;
            }
            else
            {
                _regStr.Append(")|(");
                _regStr.Append(facet.Value);
            }
            SetFlag(facet, RestrictionFlags.Pattern);
        }
References System.Xml.Schema.FacetsChecker.FacetsCompiler._firstPattern, System.Xml.Schema.FacetsChecker.FacetsCompiler._pattern_facet, System.Xml.Schema.FacetsChecker.FacetsCompiler._regStr, System.Text.StringBuilder.Append(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckProhibitedFlag(), System.Xml.Dictionary, System.SR.Sch_PatternFacetProhibited, and System.Xml.Schema.FacetsChecker.FacetsCompiler.SetFlag().