Terraria: System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileTotalDigitsFacet
CompileTotalDigitsFacet()
void System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileTotalDigitsFacet (XmlSchemaFacet facet) inline package
Definition at line 255 of file FacetsChecker.cs.
        {
            CheckProhibitedFlag(facet, RestrictionFlags.TotalDigits, System.SR.Sch_TotalDigitsFacetProhibited);
            CheckDupFlag(facet, RestrictionFlags.TotalDigits, System.SR.Sch_DupTotalDigitsFacet);
            XmlSchemaDatatype datatype = DatatypeImplementation.GetSimpleTypeFromTypeCode(XmlTypeCode.PositiveInteger).Datatype;
            _derivedRestriction.TotalDigits = XmlBaseConverter.DecimalToInt32((decimal)ParseFacetValue(datatype, facet, System.SR.Sch_TotalDigitsFacetInvalid, null, null));
            if ((_baseFixedFlags & RestrictionFlags.TotalDigits) != 0 && _datatype.Restriction.TotalDigits != _derivedRestriction.TotalDigits)
            {
                throw new XmlSchemaException(System.SR.Sch_FacetBaseFixed, facet);
            }
            if ((_baseFlags & RestrictionFlags.TotalDigits) != 0 && _derivedRestriction.TotalDigits > _datatype.Restriction.TotalDigits)
            {
                throw new XmlSchemaException(System.SR.Sch_TotalDigitsMismatch, string.Empty);
            }
            SetFlag(facet, RestrictionFlags.TotalDigits);
        }
References System.Xml.Schema.FacetsChecker.FacetsCompiler._baseFixedFlags, System.Xml.Schema.FacetsChecker.FacetsCompiler._baseFlags, System.Xml.Schema.FacetsChecker.FacetsCompiler._datatype, System.Xml.Schema.FacetsChecker.FacetsCompiler._derivedRestriction, System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckDupFlag(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckProhibitedFlag(), System.Xml.Schema.XmlBaseConverter.DecimalToInt32(), System.Xml.Dictionary, System.Xml.Schema.DatatypeImplementation.GetSimpleTypeFromTypeCode(), System.Xml.Schema.FacetsChecker.FacetsCompiler.ParseFacetValue(), System.Xml.Schema.DatatypeImplementation.Restriction, System.SR.Sch_DupTotalDigitsFacet, System.SR.Sch_FacetBaseFixed, System.SR.Sch_TotalDigitsFacetInvalid, System.SR.Sch_TotalDigitsFacetProhibited, System.SR.Sch_TotalDigitsMismatch, System.Xml.Schema.FacetsChecker.FacetsCompiler.SetFlag(), and System.Xml.Schema.RestrictionFacets.TotalDigits.