Terraria: System.Xml.Schema.FacetsChecker.FacetsCompiler.CopyFacetsFromBaseType
CopyFacetsFromBaseType()
void System.Xml.Schema.FacetsChecker.FacetsCompiler.CopyFacetsFromBaseType () inline private
Definition at line 416 of file FacetsChecker.cs.
        {
            RestrictionFacets restriction = _datatype.Restriction;
            if ((_derivedRestriction.Flags & RestrictionFlags.Length) == 0 && (_baseFlags & RestrictionFlags.Length) != 0)
            {
                _derivedRestriction.Length = restriction.Length;
                SetFlag(RestrictionFlags.Length);
            }
            if ((_derivedRestriction.Flags & RestrictionFlags.MinLength) == 0 && (_baseFlags & RestrictionFlags.MinLength) != 0)
            {
                _derivedRestriction.MinLength = restriction.MinLength;
                SetFlag(RestrictionFlags.MinLength);
            }
            if ((_derivedRestriction.Flags & RestrictionFlags.MaxLength) == 0 && (_baseFlags & RestrictionFlags.MaxLength) != 0)
            {
                _derivedRestriction.MaxLength = restriction.MaxLength;
                SetFlag(RestrictionFlags.MaxLength);
            }
            if ((_baseFlags & RestrictionFlags.Pattern) != 0)
            {
                if (_derivedRestriction.Patterns == null)
                {
                    _derivedRestriction.Patterns = restriction.Patterns;
                }
                else
                {
                    _derivedRestriction.Patterns.AddRange(restriction.Patterns);
                }
                SetFlag(RestrictionFlags.Pattern);
            }
            if ((_baseFlags & RestrictionFlags.Enumeration) != 0)
            {
                if (_derivedRestriction.Enumeration == null)
                {
                    _derivedRestriction.Enumeration = restriction.Enumeration;
                }
                SetFlag(RestrictionFlags.Enumeration);
            }
            if ((_derivedRestriction.Flags & RestrictionFlags.WhiteSpace) == 0 && (_baseFlags & RestrictionFlags.WhiteSpace) != 0)
            {
                _derivedRestriction.WhiteSpace = restriction.WhiteSpace;
                SetFlag(RestrictionFlags.WhiteSpace);
            }
            if ((_derivedRestriction.Flags & RestrictionFlags.MaxInclusive) == 0 && (_baseFlags & RestrictionFlags.MaxInclusive) != 0)
            {
                _derivedRestriction.MaxInclusive = restriction.MaxInclusive;
                SetFlag(RestrictionFlags.MaxInclusive);
            }
            if ((_derivedRestriction.Flags & RestrictionFlags.MaxExclusive) == 0 && (_baseFlags & RestrictionFlags.MaxExclusive) != 0)
            {
                _derivedRestriction.MaxExclusive = restriction.MaxExclusive;
                SetFlag(RestrictionFlags.MaxExclusive);
            }
            if ((_derivedRestriction.Flags & RestrictionFlags.MinInclusive) == 0 && (_baseFlags & RestrictionFlags.MinInclusive) != 0)
            {
                _derivedRestriction.MinInclusive = restriction.MinInclusive;
                SetFlag(RestrictionFlags.MinInclusive);
            }
            if ((_derivedRestriction.Flags & RestrictionFlags.MinExclusive) == 0 && (_baseFlags & RestrictionFlags.MinExclusive) != 0)
            {
                _derivedRestriction.MinExclusive = restriction.MinExclusive;
                SetFlag(RestrictionFlags.MinExclusive);
            }
            if ((_derivedRestriction.Flags & RestrictionFlags.TotalDigits) == 0 && (_baseFlags & RestrictionFlags.TotalDigits) != 0)
            {
                _derivedRestriction.TotalDigits = restriction.TotalDigits;
                SetFlag(RestrictionFlags.TotalDigits);
            }
            if ((_derivedRestriction.Flags & RestrictionFlags.FractionDigits) == 0 && (_baseFlags & RestrictionFlags.FractionDigits) != 0)
            {
                _derivedRestriction.FractionDigits = restriction.FractionDigits;
                SetFlag(RestrictionFlags.FractionDigits);
            }
        }
References System.Xml.Schema.FacetsChecker.FacetsCompiler._baseFlags, System.Xml.Schema.FacetsChecker.FacetsCompiler._datatype, System.Xml.Schema.FacetsChecker.FacetsCompiler._derivedRestriction, System.Collections.ArrayList.AddRange(), System.Xml.Dictionary, System.Xml.Schema.RestrictionFacets.Enumeration, System.Xml.Schema.RestrictionFacets.Flags, System.Xml.Schema.RestrictionFacets.Length, System.Xml.Schema.RestrictionFacets.Patterns, System.Xml.Schema.DatatypeImplementation.Restriction, and System.Xml.Schema.FacetsChecker.FacetsCompiler.SetFlag().
Referenced by System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileFacetCombinations().