Terraria: System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMinExclusiveFacet
CompileMinExclusiveFacet()
void System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMinExclusiveFacet (XmlSchemaFacet facet) inline package
Definition at line 242 of file FacetsChecker.cs.
        {
            CheckProhibitedFlag(facet, RestrictionFlags.MinExclusive, System.SR.Sch_MinExclusiveFacetProhibited);
            CheckDupFlag(facet, RestrictionFlags.MinExclusive, System.SR.Sch_DupMinExclusiveFacet);
            _derivedRestriction.MinExclusive = ParseFacetValue(_builtInType, facet, System.SR.Sch_MinExclusiveFacetInvalid, null, null);
            if ((_baseFixedFlags & RestrictionFlags.MinExclusive) != 0 && !_datatype.IsEqual(_datatype.Restriction.MinExclusive, _derivedRestriction.MinExclusive))
            {
                throw new XmlSchemaException(System.SR.Sch_FacetBaseFixed, facet);
            }
            CheckValue(_derivedRestriction.MinExclusive, facet);
            SetFlag(facet, RestrictionFlags.MinExclusive);
        }
References System.Xml.Schema.FacetsChecker.FacetsCompiler._baseFixedFlags, System.Xml.Schema.FacetsChecker.FacetsCompiler._builtInType, System.Xml.Schema.FacetsChecker.FacetsCompiler._datatype, System.Xml.Schema.FacetsChecker.FacetsCompiler._derivedRestriction, System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckDupFlag(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckProhibitedFlag(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckValue(), System.Xml.Dictionary, System.Xml.Schema.DatatypeImplementation.IsEqual(), System.Xml.Schema.RestrictionFacets.MinExclusive, System.Xml.Schema.FacetsChecker.FacetsCompiler.ParseFacetValue(), System.Xml.Schema.DatatypeImplementation.Restriction, System.SR.Sch_DupMinExclusiveFacet, System.SR.Sch_FacetBaseFixed, System.SR.Sch_MinExclusiveFacetInvalid, System.SR.Sch_MinExclusiveFacetProhibited, and System.Xml.Schema.FacetsChecker.FacetsCompiler.SetFlag().