Terraria: System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileWhitespaceFacet
CompileWhitespaceFacet()
void System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileWhitespaceFacet (XmlSchemaFacet facet) inline package
Definition at line 167 of file FacetsChecker.cs.
        {
            CheckProhibitedFlag(facet, RestrictionFlags.WhiteSpace, System.SR.Sch_WhiteSpaceFacetProhibited);
            CheckDupFlag(facet, RestrictionFlags.WhiteSpace, System.SR.Sch_DupWhiteSpaceFacet);
            if (facet.Value == "preserve")
            {
                _derivedRestriction.WhiteSpace = XmlSchemaWhiteSpace.Preserve;
            }
            else if (facet.Value == "replace")
            {
                _derivedRestriction.WhiteSpace = XmlSchemaWhiteSpace.Replace;
            }
            else
            {
                if (!(facet.Value == "collapse"))
                {
                    throw new XmlSchemaException(System.SR.Sch_InvalidWhiteSpace, facet.Value, facet);
                }
                _derivedRestriction.WhiteSpace = XmlSchemaWhiteSpace.Collapse;
            }
            if ((_baseFixedFlags & RestrictionFlags.WhiteSpace) != 0 && !_datatype.IsEqual(_datatype.Restriction.WhiteSpace, _derivedRestriction.WhiteSpace))
            {
                throw new XmlSchemaException(System.SR.Sch_FacetBaseFixed, facet);
            }
            XmlSchemaWhiteSpace xmlSchemaWhiteSpace = (((_baseFlags & RestrictionFlags.WhiteSpace) == 0) ? _datatype.BuiltInWhitespaceFacet : _datatype.Restriction.WhiteSpace);
            if (xmlSchemaWhiteSpace == XmlSchemaWhiteSpace.Collapse && (_derivedRestriction.WhiteSpace == XmlSchemaWhiteSpace.Replace || _derivedRestriction.WhiteSpace == XmlSchemaWhiteSpace.Preserve))
            {
                throw new XmlSchemaException(System.SR.Sch_WhiteSpaceRestriction1, facet);
            }
            if (xmlSchemaWhiteSpace == XmlSchemaWhiteSpace.Replace && _derivedRestriction.WhiteSpace == XmlSchemaWhiteSpace.Preserve)
            {
                throw new XmlSchemaException(System.SR.Sch_WhiteSpaceRestriction2, facet);
            }
            SetFlag(facet, RestrictionFlags.WhiteSpace);
        }
References System.Xml.Schema.FacetsChecker.FacetsCompiler._baseFixedFlags, System.Xml.Schema.FacetsChecker.FacetsCompiler._baseFlags, System.Xml.Schema.FacetsChecker.FacetsCompiler._datatype, System.Xml.Schema.FacetsChecker.FacetsCompiler._derivedRestriction, System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckDupFlag(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckProhibitedFlag(), System.Xml.Dictionary, System.Xml.Schema.DatatypeImplementation.IsEqual(), System.Xml.Schema.DatatypeImplementation.Restriction, System.SR.Sch_DupWhiteSpaceFacet, System.SR.Sch_FacetBaseFixed, System.SR.Sch_InvalidWhiteSpace, System.SR.Sch_WhiteSpaceFacetProhibited, System.SR.Sch_WhiteSpaceRestriction1, System.SR.Sch_WhiteSpaceRestriction2, System.Xml.Schema.FacetsChecker.FacetsCompiler.SetFlag(), and System.Xml.Schema.RestrictionFacets.WhiteSpace.