Terraria: System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileFractionDigitsFacet
CompileFractionDigitsFacet()
void System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileFractionDigitsFacet (XmlSchemaFacet facet) inline package
Definition at line 272 of file FacetsChecker.cs.
        {
            CheckProhibitedFlag(facet, RestrictionFlags.FractionDigits, System.SR.Sch_FractionDigitsFacetProhibited);
            CheckDupFlag(facet, RestrictionFlags.FractionDigits, System.SR.Sch_DupFractionDigitsFacet);
            _derivedRestriction.FractionDigits = XmlBaseConverter.DecimalToInt32((decimal)ParseFacetValue(_nonNegativeInt, facet, System.SR.Sch_FractionDigitsFacetInvalid, null, null));
            if (_derivedRestriction.FractionDigits != 0 && _datatype.TypeCode != XmlTypeCode.Decimal)
            {
                throw new XmlSchemaException(System.SR.Sch_FractionDigitsFacetInvalid, System.SR.Sch_FractionDigitsNotOnDecimal, facet);
            }
            if ((_baseFixedFlags & RestrictionFlags.FractionDigits) != 0 && _datatype.Restriction.FractionDigits != _derivedRestriction.FractionDigits)
            {
                throw new XmlSchemaException(System.SR.Sch_FacetBaseFixed, facet);
            }
            if ((_baseFlags & RestrictionFlags.FractionDigits) != 0 && _derivedRestriction.FractionDigits > _datatype.Restriction.FractionDigits)
            {
                throw new XmlSchemaException(System.SR.Sch_FractionDigitsMismatch, string.Empty);
            }
            SetFlag(facet, RestrictionFlags.FractionDigits);
        }
References System.Xml.Schema.FacetsChecker.FacetsCompiler._baseFixedFlags, System.Xml.Schema.FacetsChecker.FacetsCompiler._baseFlags, System.Xml.Schema.FacetsChecker.FacetsCompiler._datatype, System.Xml.Schema.FacetsChecker.FacetsCompiler._derivedRestriction, System.Xml.Schema.FacetsChecker.FacetsCompiler._nonNegativeInt, System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckDupFlag(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckProhibitedFlag(), System.Xml.Schema.XmlBaseConverter.DecimalToInt32(), System.Xml.Dictionary, System.Xml.Schema.RestrictionFacets.FractionDigits, System.Xml.Schema.FacetsChecker.FacetsCompiler.ParseFacetValue(), System.Xml.Schema.DatatypeImplementation.Restriction, System.SR.Sch_DupFractionDigitsFacet, System.SR.Sch_FacetBaseFixed, System.SR.Sch_FractionDigitsFacetInvalid, System.SR.Sch_FractionDigitsFacetProhibited, System.SR.Sch_FractionDigitsMismatch, System.SR.Sch_FractionDigitsNotOnDecimal, System.Xml.Schema.FacetsChecker.FacetsCompiler.SetFlag(), and System.Xml.Schema.DatatypeImplementation.TypeCode.