Terraria: System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckValue
CheckValue()
void System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckValue (object value, XmlSchemaFacet facet) inline private
Definition at line 319 of file FacetsChecker.cs.
        {
            RestrictionFacets restriction = _datatype.Restriction;
            switch (facet.FacetType)
            {
            case FacetType.MaxInclusive:
                if ((_baseFlags & RestrictionFlags.MaxInclusive) != 0 && _datatype.Compare(value, restriction.MaxInclusive) > 0)
                {
                    throw new XmlSchemaException(System.SR.Sch_MaxInclusiveMismatch, string.Empty);
                }
                if ((_baseFlags & RestrictionFlags.MaxExclusive) != 0 && _datatype.Compare(value, restriction.MaxExclusive) >= 0)
                {
                    throw new XmlSchemaException(System.SR.Sch_MaxIncExlMismatch, string.Empty);
                }
                break;
            case FacetType.MaxExclusive:
                if ((_baseFlags & RestrictionFlags.MaxExclusive) != 0 && _datatype.Compare(value, restriction.MaxExclusive) > 0)
                {
                    throw new XmlSchemaException(System.SR.Sch_MaxExclusiveMismatch, string.Empty);
                }
                if ((_baseFlags & RestrictionFlags.MaxInclusive) != 0 && _datatype.Compare(value, restriction.MaxInclusive) > 0)
                {
                    throw new XmlSchemaException(System.SR.Sch_MaxExlIncMismatch, string.Empty);
                }
                break;
            case FacetType.MinInclusive:
                if ((_baseFlags & RestrictionFlags.MinInclusive) != 0 && _datatype.Compare(value, restriction.MinInclusive) < 0)
                {
                    throw new XmlSchemaException(System.SR.Sch_MinInclusiveMismatch, string.Empty);
                }
                if ((_baseFlags & RestrictionFlags.MinExclusive) != 0 && _datatype.Compare(value, restriction.MinExclusive) < 0)
                {
                    throw new XmlSchemaException(System.SR.Sch_MinIncExlMismatch, string.Empty);
                }
                if ((_baseFlags & RestrictionFlags.MaxExclusive) != 0 && _datatype.Compare(value, restriction.MaxExclusive) >= 0)
                {
                    throw new XmlSchemaException(System.SR.Sch_MinIncMaxExlMismatch, string.Empty);
                }
                break;
            case FacetType.MinExclusive:
                if ((_baseFlags & RestrictionFlags.MinExclusive) != 0 && _datatype.Compare(value, restriction.MinExclusive) < 0)
                {
                    throw new XmlSchemaException(System.SR.Sch_MinExclusiveMismatch, string.Empty);
                }
                if ((_baseFlags & RestrictionFlags.MinInclusive) != 0 && _datatype.Compare(value, restriction.MinInclusive) < 0)
                {
                    throw new XmlSchemaException(System.SR.Sch_MinExlIncMismatch, string.Empty);
                }
                if ((_baseFlags & RestrictionFlags.MaxExclusive) != 0 && _datatype.Compare(value, restriction.MaxExclusive) >= 0)
                {
                    throw new XmlSchemaException(System.SR.Sch_MinExlMaxExlMismatch, string.Empty);
                }
                break;
            }
        }
References System.Xml.Schema.FacetsChecker.FacetsCompiler._baseFlags, System.Xml.Schema.FacetsChecker.FacetsCompiler._datatype, System.Xml.Schema.DatatypeImplementation.Compare(), System.Xml.Dictionary, System.Xml.Schema.RestrictionFacets.MaxInclusive, System.Xml.Schema.DatatypeImplementation.Restriction, System.SR.Sch_MaxExclusiveMismatch, System.SR.Sch_MaxExlIncMismatch, System.SR.Sch_MaxIncExlMismatch, System.SR.Sch_MaxInclusiveMismatch, System.SR.Sch_MinExclusiveMismatch, System.SR.Sch_MinExlIncMismatch, System.SR.Sch_MinExlMaxExlMismatch, System.SR.Sch_MinIncExlMismatch, System.SR.Sch_MinInclusiveMismatch, System.SR.Sch_MinIncMaxExlMismatch, and System.value.
Referenced by System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMaxExclusiveFacet(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMaxInclusiveFacet(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMinExclusiveFacet(), and System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMinInclusiveFacet().