Terraria: System.Xml.Schema.FacetsChecker.FacetsCompiler.FinishFacetCompile
FinishFacetCompile()
void System.Xml.Schema.FacetsChecker.FacetsCompiler.FinishFacetCompile () inline package
Definition at line 292 of file FacetsChecker.cs.
        {
            if (_firstPattern)
            {
                return;
            }
            if (_derivedRestriction.Patterns == null)
            {
                _derivedRestriction.Patterns = new ArrayList();
            }
            try
            {
                _regStr.Append(')');
                string text = _regStr.ToString();
                if (text.Contains('|'))
                {
                    _regStr.Insert(0, '(');
                    _regStr.Append(')');
                }
                _derivedRestriction.Patterns.Add(new Regex(Preprocess(_regStr.ToString())));
            }
            catch (Exception ex)
            {
                throw new XmlSchemaException(System.SR.Sch_PatternFacetInvalid, new string[1] { ex.Message }, ex, _pattern_facet.SourceUri, _pattern_facet.LineNumber, _pattern_facet.LinePosition, _pattern_facet);
            }
        }
References System.Xml.Schema.FacetsChecker.FacetsCompiler._derivedRestriction, System.Xml.Schema.FacetsChecker.FacetsCompiler._firstPattern, System.Xml.Schema.FacetsChecker.FacetsCompiler._pattern_facet, System.Xml.Schema.FacetsChecker.FacetsCompiler._regStr, System.Collections.ArrayList.Add(), System.Text.StringBuilder.Append(), System.Xml.Dictionary, System.Text.StringBuilder.Insert(), System.Xml.Schema.XmlSchemaObject.LineNumber, System.Xml.Schema.XmlSchemaObject.LinePosition, System.Xml.Schema.RestrictionFacets.Patterns, System.Xml.Schema.FacetsChecker.FacetsCompiler.Preprocess(), System.SR.Sch_PatternFacetInvalid, System.Xml.Schema.XmlSchemaObject.SourceUri, System.text, and System.Text.StringBuilder.ToString().