Terraria: System.Xml.Xsl.Runtime.PrecedingSiblingDocOrderIterator.MoveNext
MoveNext()
bool System.Xml.Xsl.Runtime.PrecedingSiblingDocOrderIterator.MoveNext () inline
Definition at line 30 of file PrecedingSiblingDocOrderIterator.cs.
    {
        if (_needFirst)
        {
            if (!_navCurrent.MoveToParent())
            {
                return false;
            }
            if (!_filter.MoveToContent(_navCurrent))
            {
                return false;
            }
            _needFirst = false;
        }
        else if (!_filter.MoveToFollowingSibling(_navCurrent))
        {
            return false;
        }
        if (_useCompPos)
        {
            return _navCurrent.ComparePosition(_navEnd) == XmlNodeOrder.Before;
        }
        if (_navCurrent.IsSamePosition(_navEnd))
        {
            _useCompPos = true;
            return false;
        }
        return true;
    }
References System.Xml.Xsl.Runtime.PrecedingSiblingDocOrderIterator._filter, System.Xml.Xsl.Runtime.PrecedingSiblingDocOrderIterator._navCurrent, System.Xml.Xsl.Runtime.PrecedingSiblingDocOrderIterator._navEnd, System.Xml.Xsl.Runtime.PrecedingSiblingDocOrderIterator._needFirst, System.Xml.Xsl.Runtime.PrecedingSiblingDocOrderIterator._useCompPos, System.Xml.XPath.XPathNavigator.ComparePosition(), System.Xml.XPath.XPathNavigator.IsSamePosition(), System.Xml.Xsl.Runtime.XmlNavigatorFilter.MoveToContent(), System.Xml.Xsl.Runtime.XmlNavigatorFilter.MoveToFollowingSibling(), and System.Xml.XPath.XPathNavigator.MoveToParent().