Terraria: Terraria.Gore.NewGorePerfect
NewGorePerfect()
static Gore Terraria.Gore.NewGorePerfect (Vector2 Position, Vector2 Velocity, int Type, float Scale = 1f) inline static
    {
        Gore gore = NewGoreDirect(Position, Velocity, Type, Scale);
        gore.position = Position;
        gore.velocity = Velocity;
        return gore;
    }
References Terraria.Gore.NewGoreDirect().
Referenced by Terraria.Projectile.AI_026(), Terraria.Projectile.AI_189_Volcano(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Below(), Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Sideways(), Terraria.NPC.HitEffect(), Terraria.GameContent.AmbientWindSystem.SpawnAirborneCloud(), and Terraria.GameContent.AmbientWindSystem.SpawnFloorCloud().