Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody
EmitLambdaBody() [2/2]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody (CompilerScope parent, bool inlined, CompilationFlags flags) inline private
Definition at line 2354 of file LambdaCompiler.cs.
    {
        _scope.Enter(this, parent);
        if (inlined)
        {
            for (int num = _lambda.ParameterCount - 1; num >= 0; num--)
            {
                _scope.EmitSet(_lambda.GetParameter(num));
            }
        }
        flags = UpdateEmitExpressionStartFlag(flags, CompilationFlags.EmitExpressionStart);
        if (_lambda.ReturnType == typeof(void))
        {
            EmitExpressionAsVoid(_lambda.Body, flags);
        }
        else
        {
            EmitExpression(_lambda.Body, flags);
        }
        if (!inlined)
        {
            _ilg.Emit(OpCodes.Ret);
        }
        _scope.Exit();
        foreach (LabelInfo value in _labelInfo.Values)
        {
            value.ValidateFinish();
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Linq.Expressions.Compiler.LambdaCompiler._labelInfo, System.Linq.Expressions.Compiler.LambdaCompiler._lambda, System.Linq.Expressions.Compiler.LambdaCompiler._scope, System.Linq.Expressions.LambdaExpression.Body, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Linq.Expressions.Compiler.CompilerScope.EmitSet(), System.Linq.Expressions.Compiler.CompilerScope.Enter(), System.Linq.Expressions.Compiler.CompilerScope.Exit(), System.Linq.Expressions.LambdaExpression.GetParameter(), System.Linq.Expressions.LambdaExpression.ParameterCount, System.Reflection.Emit.OpCodes.Ret, System.Linq.Expressions.LambdaExpression.ReturnType, System.Linq.Expressions.Compiler.LambdaCompiler.UpdateEmitExpressionStartFlag(), System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.