Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EnsureLabel
EnsureLabel()
LabelInfo System.Linq.Expressions.Compiler.LambdaCompiler.EnsureLabel (LabelTarget node) inline private
Definition at line 799 of file LambdaCompiler.cs.
    {
        if (!_labelInfo.TryGetValue(node, out var value))
        {
            _labelInfo.Add(node, value = new LabelInfo(_ilg, node, canReturn: false));
        }
        return value;
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Linq.Expressions.Compiler.LambdaCompiler._labelInfo, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.DefineLabel(), and System.Linq.Expressions.Compiler.LambdaCompiler.ReferenceLabel().