Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitCoalesceBinaryExpression
EmitCoalesceBinaryExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitCoalesceBinaryExpression (Expression expr) inline private
Definition at line 2440 of file LambdaCompiler.cs.
    {
        BinaryExpression binaryExpression = (BinaryExpression)expr;
        if (binaryExpression.Left.Type.IsNullableType())
        {
            EmitNullableCoalesce(binaryExpression);
        }
        else if (binaryExpression.Conversion != null)
        {
            EmitLambdaReferenceCoalesce(binaryExpression);
        }
        else
        {
            EmitReferenceCoalesceWithoutConversion(binaryExpression);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaReferenceCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().