Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchLogical
EmitBranchLogical()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchLogical (bool branch, BinaryExpression node, Label label) inline private
Definition at line 2827 of file LambdaCompiler.cs.
    {
        if (node.Method != null || node.IsLifted)
        {
            EmitExpression(node);
            EmitBranchOp(branch, label);
            return;
        }
        bool flag = node.NodeType == ExpressionType.AndAlso;
        if (branch == flag)
        {
            EmitBranchAnd(branch, node, label);
        }
        else
        {
            EmitBranchOr(branch, node, label);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchAnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchOp(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchOr(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch().