Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBucket
EmitSwitchBucket()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBucket (SwitchInfo info, List< SwitchLabel > bucket) inline private
Definition at line 3194 of file LambdaCompiler.cs.
    {
        if (bucket.Count == 1)
        {
            _ilg.Emit(OpCodes.Ldloc, info.Value);
            EmitConstant(bucket[0].Constant);
            _ilg.Emit(OpCodes.Beq, bucket[0].Label);
            return;
        }
        Label? label = null;
        if (info.Is64BitSwitch)
        {
            label = _ilg.DefineLabel();
            _ilg.Emit(OpCodes.Ldloc, info.Value);
            EmitConstant(bucket[^1].Constant);
            _ilg.Emit(info.IsUnsigned ? OpCodes.Bgt_Un : OpCodes.Bgt, label.Value);
            _ilg.Emit(OpCodes.Ldloc, info.Value);
            EmitConstant(bucket[0].Constant);
            _ilg.Emit(info.IsUnsigned ? OpCodes.Blt_Un : OpCodes.Blt, label.Value);
        }
        _ilg.Emit(OpCodes.Ldloc, info.Value);
        decimal key = bucket[0].Key;
        if (key != 0m)
        {
            EmitConstant(bucket[0].Constant);
            _ilg.Emit(OpCodes.Sub);
        }
        if (info.Is64BitSwitch)
        {
            _ilg.Emit(OpCodes.Conv_I4);
        }
        int num = (int)(bucket[bucket.Count - 1].Key - bucket[0].Key + 1m);
        Label[] array = new Label[num];
        int num2 = 0;
        foreach (SwitchLabel item in bucket)
        {
            while (key++ != item.Key)
            {
                array[num2++] = info.Default;
            }
            array[num2++] = item.Label;
        }
        _ilg.Emit(OpCodes.Switch, array);
        if (info.Is64BitSwitch)
        {
            _ilg.MarkLabel(label.Value);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.array, System.Reflection.Emit.OpCodes.Beq, System.Reflection.Emit.OpCodes.Bgt, System.Reflection.Emit.OpCodes.Bgt_Un, System.Reflection.Emit.OpCodes.Blt, System.Reflection.Emit.OpCodes.Blt_Un, System.Linq.Expressions.Constant, System.Reflection.Emit.OpCodes.Conv_I4, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstant(), System.info, System.item, System.key, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.ILGenerator.MarkLabel(), System.Reflection.Emit.OpCodes.Sub, and System.Reflection.Emit.OpCodes.Switch.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBuckets().