Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodAndAlso
EmitMethodAndAlso()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodAndAlso (BinaryExpression b, CompilationFlags flags) inline private
Definition at line 2587 of file LambdaCompiler.cs.
    {
        Label label = _ilg.DefineLabel();
        EmitExpression(b.Left);
        _ilg.Emit(OpCodes.Dup);
        MethodInfo booleanOperator = TypeUtils.GetBooleanOperator(b.Method.DeclaringType, "op_False");
        _ilg.Emit(OpCodes.Call, booleanOperator);
        _ilg.Emit(OpCodes.Brtrue, label);
        EmitExpression(b.Right);
        if ((flags & CompilationFlags.EmitAsTailCallMask) == CompilationFlags.EmitAsTail)
        {
            _ilg.Emit(OpCodes.Tailcall);
        }
        _ilg.Emit(OpCodes.Call, b.Method);
        _ilg.MarkLabel(label);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Brtrue, System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.OpCodes.Dup, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Dynamic.Utils.TypeUtils.GetBooleanOperator(), System.Reflection.Emit.ILGenerator.MarkLabel(), and System.Reflection.Emit.OpCodes.Tailcall.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitAndAlsoBinaryExpression().