Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewArrayExpression
EmitNewArrayExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewArrayExpression (Expression expr) inline private
Definition at line 1740 of file LambdaCompiler.cs.
    {
        NewArrayExpression newArrayExpression = (NewArrayExpression)expr;
        ReadOnlyCollection<Expression> expressions = newArrayExpression.Expressions;
        int count = expressions.Count;
        if (newArrayExpression.NodeType == ExpressionType.NewArrayInit)
        {
            Type elementType = newArrayExpression.Type.GetElementType();
            _ilg.EmitArray(elementType, count);
            for (int i = 0; i < count; i++)
            {
                _ilg.Emit(OpCodes.Dup);
                _ilg.EmitPrimitive(i);
                EmitExpression(expressions[i]);
                _ilg.EmitStoreElement(elementType);
            }
        }
        else
        {
            for (int j = 0; j < count; j++)
            {
                Expression expression = expressions[j];
                EmitExpression(expression);
                _ilg.EmitConvertToType(expression.Type, typeof(int), isChecked: true, this);
            }
            _ilg.EmitArray(newArrayExpression.Type);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Emit.OpCodes.Dup, System.elementType, System.Reflection.Emit.ILGenerator.Emit(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().