Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitCatchStart
EmitCatchStart()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitCatchStart (CatchBlock cb) inline private
Definition at line 3402 of file LambdaCompiler.cs.
    {
        if (cb.Filter == null)
        {
            EmitSaveExceptionOrPop(cb);
            return;
        }
        Label label = _ilg.DefineLabel();
        Label label2 = _ilg.DefineLabel();
        _ilg.Emit(OpCodes.Isinst, cb.Test);
        _ilg.Emit(OpCodes.Dup);
        _ilg.Emit(OpCodes.Brtrue, label2);
        _ilg.Emit(OpCodes.Pop);
        _ilg.Emit(OpCodes.Ldc_I4_0);
        _ilg.Emit(OpCodes.Br, label);
        _ilg.MarkLabel(label2);
        EmitSaveExceptionOrPop(cb);
        PushLabelBlock(LabelScopeKind.Filter);
        EmitExpression(cb.Filter);
        PopLabelBlock(LabelScopeKind.Filter);
        _ilg.MarkLabel(label);
        _ilg.BeginCatchBlock(null);
        _ilg.Emit(OpCodes.Pop);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.ILGenerator.BeginCatchBlock(), System.Reflection.Emit.OpCodes.Br, System.Reflection.Emit.OpCodes.Brtrue, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.OpCodes.Dup, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSaveExceptionOrPop(), System.Linq.Expressions.CatchBlock.Filter, System.Reflection.Emit.OpCodes.Isinst, System.Reflection.Emit.OpCodes.Ldc_I4_0, System.Reflection.Emit.ILGenerator.MarkLabel(), System.Reflection.Emit.OpCodes.Pop, System.Linq.Expressions.Compiler.LambdaCompiler.PopLabelBlock(), System.Linq.Expressions.Compiler.LambdaCompiler.PushLabelBlock(), and System.Linq.Expressions.CatchBlock.Test.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression().