Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedRelational
EmitLiftedRelational()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedRelational (ExpressionType op, Type type) inline private
Definition at line 624 of file LambdaCompiler.cs.
    {
        bool flag = op == ExpressionType.NotEqual;
        if (flag)
        {
            op = ExpressionType.Equal;
        }
        LocalBuilder local = GetLocal(type);
        LocalBuilder local2 = GetLocal(type);
        _ilg.Emit(OpCodes.Stloc, local2);
        _ilg.Emit(OpCodes.Stloc, local);
        _ilg.Emit(OpCodes.Ldloca, local);
        _ilg.EmitGetValueOrDefault(type);
        _ilg.Emit(OpCodes.Ldloca, local2);
        _ilg.EmitGetValueOrDefault(type);
        Type nonNullableType = type.GetNonNullableType();
        EmitUnliftedBinaryOp(op, nonNullableType, nonNullableType);
        _ilg.Emit(OpCodes.Ldloca, local);
        _ilg.EmitHasValue(type);
        _ilg.Emit(OpCodes.Ldloca, local2);
        _ilg.EmitHasValue(type);
        FreeLocal(local);
        FreeLocal(local2);
        _ilg.Emit((op == ExpressionType.Equal) ? OpCodes.Ceq : OpCodes.And);
        _ilg.Emit(OpCodes.And);
        if (flag)
        {
            _ilg.Emit(OpCodes.Ldc_I4_0);
            _ilg.Emit(OpCodes.Ceq);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.And, System.Reflection.Emit.OpCodes.Ceq, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedBinaryOp(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Reflection.Emit.OpCodes.Ldc_I4_0, System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.OpCodes.Stloc, and System.type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryOp().