Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitSwitchInstruction
TryEmitSwitchInstruction()
bool System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitSwitchInstruction (SwitchExpression node, CompilationFlags flags) inline private
Definition at line 3065 of file LambdaCompiler.cs.
    {
        if (node.Comparison != null)
        {
            return false;
        }
        Type type = node.SwitchValue.Type;
        if (!CanOptimizeSwitchType(type) || !TypeUtils.AreEquivalent(type, node.Cases[0].TestValues[0].Type))
        {
            return false;
        }
        if (!node.Cases.All((SwitchCase c) => c.TestValues.All((Expression t) => t is ConstantExpression)))
        {
            return false;
        }
        Label[] array = new Label[node.Cases.Count];
        bool[] array2 = new bool[node.Cases.Count];
        HashSet<decimal> hashSet = new HashSet<decimal>();
        List<SwitchLabel> list = new List<SwitchLabel>();
        for (int i = 0; i < node.Cases.Count; i++)
        {
            DefineSwitchCaseLabel(node.Cases[i], out array[i], out array2[i]);
            foreach (ConstantExpression testValue in node.Cases[i].TestValues)
            {
                decimal num = ConvertSwitchValue(testValue.Value);
                if (hashSet.Add(num))
                {
                    list.Add(new SwitchLabel(num, testValue.Value, array[i]));
                }
            }
        }
        list.Sort((SwitchLabel x, SwitchLabel y) => Math.Sign(x.Key - y.Key));
        List<List<SwitchLabel>> list2 = new List<List<SwitchLabel>>();
        foreach (SwitchLabel item in list)
        {
            AddToBuckets(list2, item);
        }
        LocalBuilder local = GetLocal(node.SwitchValue.Type);
        EmitExpression(node.SwitchValue);
        _ilg.Emit(OpCodes.Stloc, local);
        Label label = _ilg.DefineLabel();
        Label @default = ((node.DefaultBody == null) ? label : _ilg.DefineLabel());
        SwitchInfo info = new SwitchInfo(node, local, @default);
        EmitSwitchBuckets(info, list2, 0, list2.Count - 1);
        EmitSwitchCases(node, array, array2, @default, label, flags);
        FreeLocal(local);
        return true;
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.Expressions.Compiler.LambdaCompiler.AddToBuckets(), System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.array, System.Linq.Expressions.Compiler.LambdaCompiler.CanOptimizeSwitchType(), System.Linq.Expressions.Compiler.LambdaCompiler.ConvertSwitchValue(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Linq.Expressions.Compiler.LambdaCompiler.DefineSwitchCaseLabel(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBuckets(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchCases(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.info, System.item, System.Linq.Expressions.Compiler.LambdaCompiler.SwitchLabel.Key, System.list, System.Math.Sign(), System.Reflection.Emit.OpCodes.Stloc, System.Linq.Expressions.SwitchCase.TestValues, and System.type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchExpression().