Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid
EmitExpressionAsVoid() [1/2]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid (Expression node) inline private
Definition at line 1122 of file LambdaCompiler.cs.
    {
        EmitExpressionAsVoid(node, CompilationFlags.EmitAsNoTail);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchBlock(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConvert(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitGotoExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLabelExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLoopExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullEquality(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitTypeBinaryExpression().