Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal
GetLocal()
LocalBuilder System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal (Type type) inline
Implements System.Linq.Expressions.Compiler.ILocalCache.
Definition at line 1064 of file LambdaCompiler.cs.
    {
        return _freeLocals.TryPop(type) ?? _ilg.DeclareLocal(type);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._freeLocals, System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.ILGenerator.DeclareLocal(), and System.type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaReferenceCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanAnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanOr(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedRelational(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedToNullRelational(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitListInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitVariableAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.GetInstanceLocal(), and System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitSwitchInstruction().