Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddressWriteBack
EmitAddressWriteBack()
WriteBack System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddressWriteBack (Expression node, Type type) inline private
Definition at line 256 of file LambdaCompiler.cs.
    {
        CompilationFlags flags = EmitExpressionStart(node);
        WriteBack writeBack = null;
        if (TypeUtils.AreEquivalent(type, node.Type))
        {
            switch (node.NodeType)
            {
            case ExpressionType.MemberAccess:
                writeBack = AddressOfWriteBack((MemberExpression)node);
                break;
            case ExpressionType.Index:
                writeBack = AddressOfWriteBack((IndexExpression)node);
                break;
            }
        }
        if (writeBack == null)
        {
            EmitAddress(node, type, CompilationFlags.EmitNoExpressionStart | CompilationFlags.EmitAsNoTail);
        }
        EmitExpressionEnd(flags);
        return writeBack;
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBack(), System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionEnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionStart, System.type, and System.Linq.Expressions.Compiler.LambdaCompiler.WriteBack().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitArguments().