Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce
EmitNullableCoalesce()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce (BinaryExpression b) inline private
Definition at line 2457 of file LambdaCompiler.cs.
    {
        LocalBuilder local = GetLocal(b.Left.Type);
        Label label = _ilg.DefineLabel();
        Label label2 = _ilg.DefineLabel();
        EmitExpression(b.Left);
        _ilg.Emit(OpCodes.Stloc, local);
        _ilg.Emit(OpCodes.Ldloca, local);
        _ilg.EmitHasValue(b.Left.Type);
        _ilg.Emit(OpCodes.Brfalse, label);
        Type nonNullableType = b.Left.Type.GetNonNullableType();
        if (b.Conversion != null)
        {
            ParameterExpression parameter = b.Conversion.GetParameter(0);
            EmitLambdaExpression(b.Conversion);
            if (!parameter.Type.IsAssignableFrom(b.Left.Type))
            {
                _ilg.Emit(OpCodes.Ldloca, local);
                _ilg.EmitGetValueOrDefault(b.Left.Type);
            }
            else
            {
                _ilg.Emit(OpCodes.Ldloc, local);
            }
            _ilg.Emit(OpCodes.Callvirt, b.Conversion.Type.GetInvokeMethod());
        }
        else if (TypeUtils.AreEquivalent(b.Type, b.Left.Type))
        {
            _ilg.Emit(OpCodes.Ldloc, local);
        }
        else
        {
            _ilg.Emit(OpCodes.Ldloca, local);
            _ilg.EmitGetValueOrDefault(b.Left.Type);
            if (!TypeUtils.AreEquivalent(b.Type, nonNullableType))
            {
                _ilg.EmitConvertToType(nonNullableType, b.Type, isChecked: true, this);
            }
        }
        FreeLocal(local);
        _ilg.Emit(OpCodes.Br, label2);
        _ilg.MarkLabel(label);
        EmitExpression(b.Right);
        if (!TypeUtils.AreEquivalent(b.Right.Type, b.Type))
        {
            _ilg.EmitConvertToType(b.Right.Type, b.Type, isChecked: true, this);
        }
        _ilg.MarkLabel(label2);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Reflection.Emit.OpCodes.Br, System.Reflection.Emit.OpCodes.Brfalse, System.Reflection.Emit.OpCodes.Callvirt, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.ILGenerator.MarkLabel(), and System.Reflection.Emit.OpCodes.Stloc.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitCoalesceBinaryExpression().