Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionEnd
EmitExpressionEnd()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionEnd (CompilationFlags flags) inline private
Definition at line 1187 of file LambdaCompiler.cs.
    {
        if ((flags & CompilationFlags.EmitExpressionStartMask) == CompilationFlags.EmitExpressionStart)
        {
            PopLabelBlock(_labelBlock.Kind);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._labelBlock, System.Linq.Expressions.Compiler.LabelScopeInfo.Kind, and System.Linq.Expressions.Compiler.LambdaCompiler.PopLabelBlock().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddressWriteBack(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid().