Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchExpression
EmitSwitchExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchExpression (Expression expr, CompilationFlags flags) inline private
Definition at line 2959 of file LambdaCompiler.cs.
    {
        SwitchExpression switchExpression = (SwitchExpression)expr;
        if (switchExpression.Cases.Count == 0)
        {
            EmitExpressionAsVoid(switchExpression.SwitchValue);
            if (switchExpression.DefaultBody != null)
            {
                EmitExpressionAsType(switchExpression.DefaultBody, switchExpression.Type, flags);
            }
        }
        else
        {
            if (TryEmitSwitchInstruction(switchExpression, flags) || TryEmitHashtableSwitch(switchExpression, flags))
            {
                return;
            }
            ParameterExpression parameterExpression = Expression.Parameter(switchExpression.SwitchValue.Type, "switchValue");
            ParameterExpression parameterExpression2 = Expression.Parameter(GetTestValueType(switchExpression), "testValue");
            _scope.AddLocal(this, parameterExpression);
            _scope.AddLocal(this, parameterExpression2);
            EmitExpression(switchExpression.SwitchValue);
            _scope.EmitSet(parameterExpression);
            Label[] array = new Label[switchExpression.Cases.Count];
            bool[] array2 = new bool[switchExpression.Cases.Count];
            int i = 0;
            for (int count = switchExpression.Cases.Count; i < count; i++)
            {
                DefineSwitchCaseLabel(switchExpression.Cases[i], out array[i], out array2[i]);
                foreach (Expression testValue in switchExpression.Cases[i].TestValues)
                {
                    EmitExpression(testValue);
                    _scope.EmitSet(parameterExpression2);
                    EmitExpressionAndBranch(branchValue: true, Expression.Equal(parameterExpression, parameterExpression2, liftToNull: false, switchExpression.Comparison), array[i]);
                }
            }
            Label label = _ilg.DefineLabel();
            Label @default = ((switchExpression.DefaultBody == null) ? label : _ilg.DefineLabel());
            EmitSwitchCases(switchExpression, array, array2, @default, label, flags);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Linq.Expressions.Compiler.LambdaCompiler._scope, System.Linq.Expressions.Compiler.CompilerScope.AddLocal(), System.array, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Linq.Expressions.Compiler.LambdaCompiler.DefineSwitchCaseLabel(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Linq.Expressions.Compiler.CompilerScope.EmitSet(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchCases(), System.Linq.Expressions.Expression< TDelegate >.Equal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetTestValueType(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitHashtableSwitch(), and System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitSwitchInstruction().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().