Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType
EmitExpressionAsType()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType (Expression node, Type type, CompilationFlags flags) inline private
Definition at line 1161 of file LambdaCompiler.cs.
    {
        if (type == typeof(void))
        {
            EmitExpressionAsVoid(node, flags);
        }
        else if (!TypeUtils.AreEquivalent(node.Type, type))
        {
            EmitExpression(node);
            _ilg.Emit(OpCodes.Castclass, type);
        }
        else
        {
            EmitExpression(node, UpdateEmitExpressionStartFlag(flags, CompilationFlags.EmitExpressionStart));
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Reflection.Emit.OpCodes.Castclass, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.type, and System.Linq.Expressions.Compiler.LambdaCompiler.UpdateEmitExpressionStartFlag().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConditionalExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchCases(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchExpression().