Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitArguments
EmitArguments() [2/2]
List< WriteBack > System.Linq.Expressions.Compiler.LambdaCompiler.EmitArguments (MethodBase method, IArgumentProvider args, int skipParameters) inline private
Definition at line 1433 of file LambdaCompiler.cs.
    {
        ParameterInfo[] parametersCached = method.GetParametersCached();
        List<WriteBack> list = null;
        int i = skipParameters;
        for (int num = parametersCached.Length; i < num; i++)
        {
            ParameterInfo parameterInfo = parametersCached[i];
            Expression argument = args.GetArgument(i - skipParameters);
            Type parameterType = parameterInfo.ParameterType;
            if (parameterType.IsByRef)
            {
                parameterType = parameterType.GetElementType();
                WriteBack writeBack = EmitAddressWriteBack(argument, parameterType);
                if (writeBack != null)
                {
                    if (list == null)
                    {
                        list = new List<WriteBack>();
                    }
                    list.Add(writeBack);
                }
            }
            else
            {
                EmitExpression(argument);
            }
        }
        return list;
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddressWriteBack(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.list, and System.Linq.Expressions.Compiler.LambdaCompiler.WriteBack().