Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitInvocationExpression
EmitInvocationExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitInvocationExpression (Expression expr, CompilationFlags flags) inline private
Definition at line 1195 of file LambdaCompiler.cs.
    {
        InvocationExpression invocationExpression = (InvocationExpression)expr;
        if (invocationExpression.LambdaOperand != null)
        {
            EmitInlinedInvoke(invocationExpression, flags);
            return;
        }
        expr = invocationExpression.Expression;
        if (typeof(LambdaExpression).IsAssignableFrom(expr.Type))
        {
            expr = Expression.Call(expr, LambdaExpression.GetCompileMethod(expr.Type));
        }
        EmitMethodCall(expr, expr.Type.GetInvokeMethod(), invocationExpression, CompilationFlags.EmitExpressionStart | CompilationFlags.EmitAsNoTail);
    }
References System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitInlinedInvoke(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall(), System.Linq.Expressions.LambdaExpression.GetCompileMethod(), and System.Linq.Expressions.Expression< TDelegate >.Type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().