Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitGotoExpression
EmitGotoExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitGotoExpression (Expression expr, CompilationFlags flags) inline private
Definition at line 867 of file LambdaCompiler.cs.
    {
        GotoExpression gotoExpression = (GotoExpression)expr;
        LabelInfo labelInfo = ReferenceLabel(gotoExpression.Target);
        CompilationFlags compilationFlags = flags & CompilationFlags.EmitAsTailCallMask;
        if (compilationFlags != CompilationFlags.EmitAsNoTail)
        {
            compilationFlags = (labelInfo.CanReturn ? CompilationFlags.EmitAsTail : CompilationFlags.EmitAsNoTail);
            flags = UpdateEmitAsTailCallFlag(flags, compilationFlags);
        }
        if (gotoExpression.Value != null)
        {
            if (gotoExpression.Target.Type == typeof(void))
            {
                EmitExpressionAsVoid(gotoExpression.Value, flags);
            }
            else
            {
                flags = UpdateEmitExpressionStartFlag(flags, CompilationFlags.EmitExpressionStart);
                EmitExpression(gotoExpression.Value, flags);
            }
        }
        labelInfo.EmitJump();
        EmitUnreachable(gotoExpression, flags);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnreachable(), System.Linq.Expressions.Compiler.LambdaCompiler.ReferenceLabel(), System.Linq.Expressions.Compiler.LambdaCompiler.UpdateEmitAsTailCallFlag(), and System.Linq.Expressions.Compiler.LambdaCompiler.UpdateEmitExpressionStartFlag().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid().