Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchAnd
EmitBranchAnd()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchAnd (bool branch, BinaryExpression node, Label label) inline private
Definition at line 2846 of file LambdaCompiler.cs.
    {
        Label label2 = _ilg.DefineLabel();
        EmitExpressionAndBranch(!branch, node.Left, label2);
        EmitExpressionAndBranch(branch, node.Right, label);
        _ilg.MarkLabel(label2);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch(), and System.Reflection.Emit.ILGenerator.MarkLabel().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchLogical().