Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall
EmitMethodCall() [4/4]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall (MethodInfo mi, IArgumentProvider args, Type objectType, CompilationFlags flags) inline private
Definition at line 1359 of file LambdaCompiler.cs.
    {
        List<WriteBack> writeBacks = EmitArguments(mi, args);
        OpCode opCode = (UseVirtual(mi) ? OpCodes.Callvirt : OpCodes.Call);
        if (opCode == OpCodes.Callvirt && objectType.IsValueType)
        {
            _ilg.Emit(OpCodes.Constrained, objectType);
        }
        if ((flags & CompilationFlags.EmitAsTailCallMask) == CompilationFlags.EmitAsTail && !MethodHasByRefParameter(mi))
        {
            _ilg.Emit(OpCodes.Tailcall);
        }
        if (mi.CallingConvention == CallingConventions.VarArgs)
        {
            int argumentCount = args.ArgumentCount;
            Type[] array = new Type[argumentCount];
            for (int i = 0; i < argumentCount; i++)
            {
                array[i] = args.GetArgument(i).Type;
            }
            _ilg.EmitCall(opCode, mi, array);
        }
        else
        {
            _ilg.Emit(opCode, mi);
        }
        EmitWriteBack(writeBacks);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.array, System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.OpCodes.Callvirt, System.Reflection.Emit.OpCodes.Constrained, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitArguments(), System.Reflection.Emit.ILGenerator.EmitCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitWriteBack(), System.Linq.Expressions.Compiler.LambdaCompiler.MethodHasByRefParameter(), System.Reflection.Emit.OpCodes.Tailcall, and System.Linq.Expressions.Compiler.LambdaCompiler.UseVirtual().