Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitConvertArithmeticResult
EmitConvertArithmeticResult()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitConvertArithmeticResult (ExpressionType op, Type resultType) inline private
Definition at line 550 of file LambdaCompiler.cs.
    {
        switch (resultType.GetTypeCode())
        {
        case TypeCode.Byte:
            _ilg.Emit(IsChecked(op) ? OpCodes.Conv_Ovf_U1 : OpCodes.Conv_U1);
            break;
        case TypeCode.SByte:
            _ilg.Emit(IsChecked(op) ? OpCodes.Conv_Ovf_I1 : OpCodes.Conv_I1);
            break;
        case TypeCode.UInt16:
            _ilg.Emit(IsChecked(op) ? OpCodes.Conv_Ovf_U2 : OpCodes.Conv_U2);
            break;
        case TypeCode.Int16:
            _ilg.Emit(IsChecked(op) ? OpCodes.Conv_Ovf_I2 : OpCodes.Conv_I2);
            break;
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Conv_I1, System.Reflection.Emit.OpCodes.Conv_I2, System.Reflection.Emit.OpCodes.Conv_Ovf_U1, System.Reflection.Emit.OpCodes.Conv_U1, System.Reflection.Emit.OpCodes.Conv_U2, System.Reflection.Emit.ILGenerator.Emit(), and System.Linq.Expressions.Compiler.LambdaCompiler.IsChecked().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedBinaryOp().