Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitInstance
EmitInstance()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitInstance (Expression instance, out Type type) inline private
Definition at line 1722 of file LambdaCompiler.cs.
    {
        type = instance.Type;
        if (type.IsByRef)
        {
            type = type.GetElementType();
            EmitExpression(instance);
        }
        else if (type.IsValueType)
        {
            EmitAddress(instance, type);
        }
        else
        {
            EmitExpression(instance);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Expression< TDelegate >.Type, and System.type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberExpression(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall().