Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress
EmitAddress() [1/2]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress (Expression node, Type type) inline private
Definition at line 104 of file LambdaCompiler.cs.
    {
        EmitAddress(node, type, CompilationFlags.EmitExpressionStart);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress(), and System.type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddressWriteBack(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchComparison(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitInstance(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullEquality(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTypeBinaryExpression(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitVariableAssignment().