Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewExpression
EmitNewExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewExpression (Expression expr) inline private
Definition at line 1518 of file LambdaCompiler.cs.
    {
        NewExpression newExpression = (NewExpression)expr;
        if (newExpression.Constructor != null)
        {
            if (newExpression.Constructor.DeclaringType.IsAbstract)
            {
                throw Error.NonAbstractConstructorRequired();
            }
            List<WriteBack> writeBacks = EmitArguments(newExpression.Constructor, newExpression);
            _ilg.Emit(OpCodes.Newobj, newExpression.Constructor);
            EmitWriteBack(writeBacks);
        }
        else
        {
            LocalBuilder local = GetLocal(newExpression.Type);
            _ilg.Emit(OpCodes.Ldloca, local);
            _ilg.Emit(OpCodes.Initobj, newExpression.Type);
            _ilg.Emit(OpCodes.Ldloc, local);
            FreeLocal(local);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitArguments(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitWriteBack(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Reflection.Emit.OpCodes.Initobj, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.OpCodes.Newobj, and System.Linq.Expressions.Error.NonAbstractConstructorRequired().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().