Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchBlock
EmitBranchBlock()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchBlock (bool branch, BlockExpression node, Label label) inline private
Definition at line 2860 of file LambdaCompiler.cs.
    {
        EnterScope(node);
        int expressionCount = node.ExpressionCount;
        for (int i = 0; i < expressionCount - 1; i++)
        {
            EmitExpressionAsVoid(node.GetExpression(i));
        }
        EmitExpressionAndBranch(branch, node.GetExpression(expressionCount - 1), label);
        ExitScope(node);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Linq.Expressions.Compiler.LambdaCompiler.EnterScope(), and System.Linq.Expressions.Compiler.LambdaCompiler.ExitScope().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch().