Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore
AddressOfWriteBackCore() [1/2]
WriteBack System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore (IndexExpression node) inline private
Definition at line 326 of file LambdaCompiler.cs.
    {
        LocalBuilder instanceLocal = null;
        Type type = null;
        if (node.Object != null)
        {
            EmitInstance(node.Object, out type);
            _ilg.Emit(OpCodes.Dup);
            _ilg.Emit(OpCodes.Stloc, instanceLocal = GetInstanceLocal(type));
        }
        int argumentCount = node.ArgumentCount;
        LocalBuilder[] args = new LocalBuilder[argumentCount];
        for (int i = 0; i < argumentCount; i++)
        {
            Expression argument = node.GetArgument(i);
            EmitExpression(argument);
            LocalBuilder local = GetLocal(argument.Type);
            _ilg.Emit(OpCodes.Dup);
            _ilg.Emit(OpCodes.Stloc, local);
            args[i] = local;
        }
        EmitGetIndexCall(node, type);
        LocalBuilder valueLocal = GetLocal(node.Type);
        _ilg.Emit(OpCodes.Stloc, valueLocal);
        _ilg.Emit(OpCodes.Ldloca, valueLocal);
        return delegate(LambdaCompiler @this)
        {
            if (instanceLocal != null)
            {
                @this._ilg.Emit(OpCodes.Ldloc, instanceLocal);
                @this.FreeLocal(instanceLocal);
            }
            LocalBuilder[] array = args;
            foreach (LocalBuilder local2 in array)
            {
                @this._ilg.Emit(OpCodes.Ldloc, local2);
                @this.FreeLocal(local2);
            }
            @this._ilg.Emit(OpCodes.Ldloc, valueLocal);
            @this.FreeLocal(valueLocal);
            @this.EmitSetIndexCall(node, instanceLocal?.LocalType);
        };
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.array, System.Reflection.Emit.OpCodes.Dup, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitGetIndexCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitInstance(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSetIndexCall(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetInstanceLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.OpCodes.Stloc, and System.type.