Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitConditionalExpression
EmitConditionalExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitConditionalExpression (Expression expr, CompilationFlags flags) inline private
Definition at line 2384 of file LambdaCompiler.cs.
    {
        ConditionalExpression conditionalExpression = (ConditionalExpression)expr;
        Label label = _ilg.DefineLabel();
        EmitExpressionAndBranch(branchValue: false, conditionalExpression.Test, label);
        EmitExpressionAsType(conditionalExpression.IfTrue, conditionalExpression.Type, flags);
        if (NotEmpty(conditionalExpression.IfFalse))
        {
            Label label2 = _ilg.DefineLabel();
            if ((flags & CompilationFlags.EmitAsTailCallMask) == CompilationFlags.EmitAsTail)
            {
                _ilg.Emit(OpCodes.Ret);
            }
            else
            {
                _ilg.Emit(OpCodes.Br, label2);
            }
            _ilg.MarkLabel(label);
            EmitExpressionAsType(conditionalExpression.IfFalse, conditionalExpression.Type, flags);
            _ilg.MarkLabel(label2);
        }
        else
        {
            _ilg.MarkLabel(label);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Br, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType(), System.Reflection.Emit.ILGenerator.MarkLabel(), System.Linq.Expressions.Compiler.LambdaCompiler.NotEmpty(), and System.Reflection.Emit.OpCodes.Ret.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().