Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitInlinedInvoke
EmitInlinedInvoke()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitInlinedInvoke (InvocationExpression invoke, CompilationFlags flags) inline private
Definition at line 1211 of file LambdaCompiler.cs.
    {
        LambdaExpression lambdaOperand = invoke.LambdaOperand;
        List<WriteBack> list = EmitArguments(lambdaOperand.Type.GetInvokeMethod(), invoke);
        LambdaCompiler lambdaCompiler = new LambdaCompiler(this, lambdaOperand, invoke);
        if (list != null)
        {
            flags = UpdateEmitAsTailCallFlag(flags, CompilationFlags.EmitAsNoTail);
        }
        lambdaCompiler.EmitLambdaBody(_scope, inlined: true, flags);
        EmitWriteBack(list);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.LambdaCompiler(), System.Linq.Expressions.Compiler.LambdaCompiler._scope, System.Linq.Expressions.Compiler.LambdaCompiler.EmitArguments(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitWriteBack(), System.list, and System.Linq.Expressions.Compiler.LambdaCompiler.UpdateEmitAsTailCallFlag().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitInvocationExpression().