Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryOperator
EmitBinaryOperator()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryOperator (ExpressionType op, Type leftType, Type rightType, Type resultType, bool liftedToNull) inline private
Definition at line 444 of file LambdaCompiler.cs.
    {
        if (op == ExpressionType.ArrayIndex)
        {
            EmitGetArrayElement(leftType);
        }
        else if (leftType.IsNullableType() || rightType.IsNullableType())
        {
            EmitLiftedBinaryOp(op, leftType, rightType, resultType, liftedToNull);
        }
        else
        {
            EmitUnliftedBinaryOp(op, leftType, rightType);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitGetArrayElement(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryOp(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedBinaryOp().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary().