Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression
EmitTryExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression (Expression expr) inline private
Definition at line 3340 of file LambdaCompiler.cs.
    {
        TryExpression tryExpression = (TryExpression)expr;
        CheckTry();
        PushLabelBlock(LabelScopeKind.Try);
        _ilg.BeginExceptionBlock();
        EmitExpression(tryExpression.Body);
        Type type = tryExpression.Type;
        LocalBuilder local = null;
        if (type != typeof(void))
        {
            local = GetLocal(type);
            _ilg.Emit(OpCodes.Stloc, local);
        }
        foreach (CatchBlock handler in tryExpression.Handlers)
        {
            PushLabelBlock(LabelScopeKind.Catch);
            if (handler.Filter == null)
            {
                _ilg.BeginCatchBlock(handler.Test);
            }
            else
            {
                _ilg.BeginExceptFilterBlock();
            }
            EnterScope(handler);
            EmitCatchStart(handler);
            EmitExpression(handler.Body);
            if (type != typeof(void))
            {
                _ilg.Emit(OpCodes.Stloc, local);
            }
            ExitScope(handler);
            PopLabelBlock(LabelScopeKind.Catch);
        }
        if (tryExpression.Finally != null || tryExpression.Fault != null)
        {
            PushLabelBlock(LabelScopeKind.Finally);
            if (tryExpression.Finally != null)
            {
                _ilg.BeginFinallyBlock();
            }
            else
            {
                _ilg.BeginFaultBlock();
            }
            EmitExpressionAsVoid(tryExpression.Finally ?? tryExpression.Fault);
            _ilg.EndExceptionBlock();
            PopLabelBlock(LabelScopeKind.Finally);
        }
        else
        {
            _ilg.EndExceptionBlock();
        }
        if (type != typeof(void))
        {
            _ilg.Emit(OpCodes.Ldloc, local);
            FreeLocal(local);
        }
        PopLabelBlock(LabelScopeKind.Try);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.ILGenerator.BeginCatchBlock(), System.Reflection.Emit.ILGenerator.BeginExceptFilterBlock(), System.Reflection.Emit.ILGenerator.BeginExceptionBlock(), System.Reflection.Emit.ILGenerator.BeginFaultBlock(), System.Reflection.Emit.ILGenerator.BeginFinallyBlock(), System.Linq.Expressions.CatchBlock.Body, System.Linq.Expressions.Compiler.LambdaCompiler.CheckTry(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCatchStart(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Reflection.Emit.ILGenerator.EndExceptionBlock(), System.Linq.Expressions.Compiler.LambdaCompiler.EnterScope(), System.Linq.Expressions.Compiler.LambdaCompiler.ExitScope(), System.Linq.Expressions.CatchBlock.Filter, System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Reflection.Emit.OpCodes.Ldloc, System.Linq.Expressions.Compiler.LambdaCompiler.PopLabelBlock(), System.Linq.Expressions.Compiler.LambdaCompiler.PushLabelBlock(), System.Reflection.Emit.OpCodes.Stloc, System.Linq.Expressions.CatchBlock.Test, and System.type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().