Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress
EmitAddress() [2/2]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress (Expression node, Type type, CompilationFlags flags) inline private
Definition at line 109 of file LambdaCompiler.cs.
    {
        bool flag = (flags & CompilationFlags.EmitExpressionStartMask) == CompilationFlags.EmitExpressionStart;
        CompilationFlags flags2 = (flag ? EmitExpressionStart(node) : CompilationFlags.EmitNoExpressionStart);
        switch (node.NodeType)
        {
        default:
            EmitExpressionAddress(node, type);
            break;
        case ExpressionType.ArrayIndex:
            AddressOf((BinaryExpression)node, type);
            break;
        case ExpressionType.Parameter:
            AddressOf((ParameterExpression)node, type);
            break;
        case ExpressionType.MemberAccess:
            AddressOf((MemberExpression)node, type);
            break;
        case ExpressionType.Unbox:
            AddressOf((UnaryExpression)node, type);
            break;
        case ExpressionType.Call:
            AddressOf((MethodCallExpression)node, type);
            break;
        case ExpressionType.Index:
            AddressOf((IndexExpression)node, type);
            break;
        }
        if (flag)
        {
            EmitExpressionEnd(flags2);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionEnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionStart, and System.type.