Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitTypeBinaryExpression
EmitTypeBinaryExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitTypeBinaryExpression (Expression expr) inline private
Definition at line 1541 of file LambdaCompiler.cs.
    {
        TypeBinaryExpression typeBinaryExpression = (TypeBinaryExpression)expr;
        if (typeBinaryExpression.NodeType == ExpressionType.TypeEqual)
        {
            EmitExpression(typeBinaryExpression.ReduceTypeEqual());
            return;
        }
        Type type = typeBinaryExpression.Expression.Type;
        AnalyzeTypeIsResult analyzeTypeIsResult = ConstantCheck.AnalyzeTypeIs(typeBinaryExpression);
        switch (analyzeTypeIsResult)
        {
        case AnalyzeTypeIsResult.KnownFalse:
        case AnalyzeTypeIsResult.KnownTrue:
            EmitExpressionAsVoid(typeBinaryExpression.Expression);
            _ilg.EmitPrimitive(analyzeTypeIsResult == AnalyzeTypeIsResult.KnownTrue);
            return;
        case AnalyzeTypeIsResult.KnownAssignable:
            if (type.IsNullableType())
            {
                EmitAddress(typeBinaryExpression.Expression, type);
                _ilg.EmitHasValue(type);
            }
            else
            {
                EmitExpression(typeBinaryExpression.Expression);
                _ilg.Emit(OpCodes.Ldnull);
                _ilg.Emit(OpCodes.Cgt_Un);
            }
            return;
        }
        EmitExpression(typeBinaryExpression.Expression);
        if (type.IsValueType)
        {
            _ilg.Emit(OpCodes.Box, type);
        }
        _ilg.Emit(OpCodes.Isinst, typeBinaryExpression.TypeOperand);
        _ilg.Emit(OpCodes.Ldnull);
        _ilg.Emit(OpCodes.Cgt_Un);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Linq.Expressions.ConstantCheck.AnalyzeTypeIs(), System.Reflection.Emit.OpCodes.Box, System.Reflection.Emit.OpCodes.Cgt_Un, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Reflection.Emit.OpCodes.Isinst, System.Reflection.Emit.OpCodes.Ldnull, and System.type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().