Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedBinaryOp
EmitUnliftedBinaryOp()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedBinaryOp (ExpressionType op, Type leftType, Type rightType) inline private
Definition at line 460 of file LambdaCompiler.cs.
    {
        switch (op)
        {
        case ExpressionType.NotEqual:
            if (leftType.GetTypeCode() != TypeCode.Boolean)
            {
                _ilg.Emit(OpCodes.Ceq);
                _ilg.Emit(OpCodes.Ldc_I4_0);
                goto case ExpressionType.Equal;
            }
            goto case ExpressionType.ExclusiveOr;
        case ExpressionType.Equal:
            _ilg.Emit(OpCodes.Ceq);
            return;
        case ExpressionType.Add:
            _ilg.Emit(OpCodes.Add);
            break;
        case ExpressionType.AddChecked:
            _ilg.Emit(leftType.IsFloatingPoint() ? OpCodes.Add : (leftType.IsUnsigned() ? OpCodes.Add_Ovf_Un : OpCodes.Add_Ovf));
            break;
        case ExpressionType.Subtract:
            _ilg.Emit(OpCodes.Sub);
            break;
        case ExpressionType.SubtractChecked:
            if (leftType.IsUnsigned())
            {
                _ilg.Emit(OpCodes.Sub_Ovf_Un);
                return;
            }
            _ilg.Emit(leftType.IsFloatingPoint() ? OpCodes.Sub : OpCodes.Sub_Ovf);
            break;
        case ExpressionType.Multiply:
            _ilg.Emit(OpCodes.Mul);
            break;
        case ExpressionType.MultiplyChecked:
            _ilg.Emit(leftType.IsFloatingPoint() ? OpCodes.Mul : (leftType.IsUnsigned() ? OpCodes.Mul_Ovf_Un : OpCodes.Mul_Ovf));
            break;
        case ExpressionType.Divide:
            _ilg.Emit(leftType.IsUnsigned() ? OpCodes.Div_Un : OpCodes.Div);
            break;
        case ExpressionType.Modulo:
            _ilg.Emit(leftType.IsUnsigned() ? OpCodes.Rem_Un : OpCodes.Rem);
            return;
        case ExpressionType.And:
        case ExpressionType.AndAlso:
            _ilg.Emit(OpCodes.And);
            return;
        case ExpressionType.Or:
        case ExpressionType.OrElse:
            _ilg.Emit(OpCodes.Or);
            return;
        case ExpressionType.LessThan:
            _ilg.Emit(leftType.IsUnsigned() ? OpCodes.Clt_Un : OpCodes.Clt);
            return;
        case ExpressionType.LessThanOrEqual:
            _ilg.Emit((leftType.IsUnsigned() || leftType.IsFloatingPoint()) ? OpCodes.Cgt_Un : OpCodes.Cgt);
            _ilg.Emit(OpCodes.Ldc_I4_0);
            _ilg.Emit(OpCodes.Ceq);
            return;
        case ExpressionType.GreaterThan:
            _ilg.Emit(leftType.IsUnsigned() ? OpCodes.Cgt_Un : OpCodes.Cgt);
            return;
        case ExpressionType.GreaterThanOrEqual:
            _ilg.Emit((leftType.IsUnsigned() || leftType.IsFloatingPoint()) ? OpCodes.Clt_Un : OpCodes.Clt);
            _ilg.Emit(OpCodes.Ldc_I4_0);
            _ilg.Emit(OpCodes.Ceq);
            return;
        case ExpressionType.ExclusiveOr:
            _ilg.Emit(OpCodes.Xor);
            return;
        case ExpressionType.LeftShift:
            EmitShiftMask(leftType);
            _ilg.Emit(OpCodes.Shl);
            break;
        case ExpressionType.RightShift:
            EmitShiftMask(leftType);
            _ilg.Emit(leftType.IsUnsigned() ? OpCodes.Shr_Un : OpCodes.Shr);
            return;
        }
        EmitConvertArithmeticResult(op, leftType);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Emit.OpCodes.Add, System.Reflection.Emit.OpCodes.Add_Ovf, System.Reflection.Emit.OpCodes.And, System.Reflection.Emit.OpCodes.Ceq, System.Reflection.Emit.OpCodes.Cgt, System.Reflection.Emit.OpCodes.Cgt_Un, System.Reflection.Emit.OpCodes.Clt, System.Reflection.Emit.OpCodes.Div, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConvertArithmeticResult(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitShiftMask(), System.Reflection.Emit.OpCodes.Ldc_I4_0, System.Reflection.Emit.OpCodes.Mul, System.Reflection.Emit.OpCodes.Mul_Ovf, System.Reflection.Emit.OpCodes.Or, System.Reflection.Emit.OpCodes.Rem, System.Reflection.Emit.OpCodes.Shl, System.Reflection.Emit.OpCodes.Shr, System.Reflection.Emit.OpCodes.Shr_Un, System.Reflection.Emit.OpCodes.Sub, System.Reflection.Emit.OpCodes.Sub_Ovf, System.Reflection.Emit.OpCodes.Sub_Ovf_Un, and System.Reflection.Emit.OpCodes.Xor.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryOperator(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedRelational(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedToNullRelational().