Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment
EmitMemberAssignment() [2/2]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment (MemberAssignment binding, Type objectType) inline private
Definition at line 1799 of file LambdaCompiler.cs.
    {
        EmitExpression(binding.Expression);
        if (binding.Member is FieldInfo field)
        {
            _ilg.Emit(OpCodes.Stfld, field);
        }
        else
        {
            EmitCall(objectType, (binding.Member as PropertyInfo).GetSetMethod(nonPublic: true));
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), and System.Reflection.Emit.OpCodes.Stfld.