Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCallExpression
EmitMethodCallExpression() [2/2]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCallExpression (Expression expr, CompilationFlags flags) inline private
Definition at line 1321 of file LambdaCompiler.cs.
    {
        MethodCallExpression methodCallExpression = (MethodCallExpression)expr;
        EmitMethodCall(methodCallExpression.Object, methodCallExpression.Method, methodCallExpression, flags);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryMethod(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCallExpression(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryMethod().