Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator
EmitUnaryOperator()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator (ExpressionType op, Type operandType, Type resultType) inline private
Definition at line 3514 of file LambdaCompiler.cs.
    {
        bool flag = operandType.IsNullableType();
        if (op == ExpressionType.ArrayLength)
        {
            _ilg.Emit(OpCodes.Ldlen);
            return;
        }
        if (flag)
        {
            switch (op)
            {
            case ExpressionType.UnaryPlus:
                return;
            case ExpressionType.TypeAs:
                if (operandType != resultType)
                {
                    _ilg.Emit(OpCodes.Box, operandType);
                    _ilg.Emit(OpCodes.Isinst, resultType);
                    if (resultType.IsNullableType())
                    {
                        _ilg.Emit(OpCodes.Unbox_Any, resultType);
                    }
                }
                return;
            }
            Label label = _ilg.DefineLabel();
            Label label2 = _ilg.DefineLabel();
            LocalBuilder local = GetLocal(operandType);
            _ilg.Emit(OpCodes.Stloc, local);
            _ilg.Emit(OpCodes.Ldloca, local);
            _ilg.EmitHasValue(operandType);
            _ilg.Emit(OpCodes.Brfalse_S, label);
            _ilg.Emit(OpCodes.Ldloca, local);
            _ilg.EmitGetValueOrDefault(operandType);
            Type nonNullableType = resultType.GetNonNullableType();
            EmitUnaryOperator(op, nonNullableType, nonNullableType);
            ConstructorInfo nullableConstructor = TypeUtils.GetNullableConstructor(resultType);
            _ilg.Emit(OpCodes.Newobj, nullableConstructor);
            _ilg.Emit(OpCodes.Br_S, label2);
            _ilg.MarkLabel(label);
            _ilg.Emit(OpCodes.Ldloc, local);
            FreeLocal(local);
            _ilg.MarkLabel(label2);
            return;
        }
        switch (op)
        {
        case ExpressionType.Not:
            if (operandType == typeof(bool))
            {
                _ilg.Emit(OpCodes.Ldc_I4_0);
                _ilg.Emit(OpCodes.Ceq);
                return;
            }
            goto case ExpressionType.OnesComplement;
        case ExpressionType.OnesComplement:
            _ilg.Emit(OpCodes.Not);
            if (!operandType.IsUnsigned())
            {
                return;
            }
            break;
        case ExpressionType.IsFalse:
            _ilg.Emit(OpCodes.Ldc_I4_0);
            _ilg.Emit(OpCodes.Ceq);
            return;
        case ExpressionType.IsTrue:
            _ilg.Emit(OpCodes.Ldc_I4_1);
            _ilg.Emit(OpCodes.Ceq);
            return;
        case ExpressionType.UnaryPlus:
            return;
        case ExpressionType.Negate:
        case ExpressionType.NegateChecked:
            _ilg.Emit(OpCodes.Neg);
            return;
        case ExpressionType.TypeAs:
            if (operandType != resultType)
            {
                if (operandType.IsValueType)
                {
                    _ilg.Emit(OpCodes.Box, operandType);
                }
                _ilg.Emit(OpCodes.Isinst, resultType);
                if (resultType.IsNullableType())
                {
                    _ilg.Emit(OpCodes.Unbox_Any, resultType);
                }
            }
            return;
        case ExpressionType.Increment:
            EmitConstantOne(resultType);
            _ilg.Emit(OpCodes.Add);
            break;
        case ExpressionType.Decrement:
            EmitConstantOne(resultType);
            _ilg.Emit(OpCodes.Sub);
            break;
        }
        EmitConvertArithmeticResult(op, resultType);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Add, System.Reflection.Emit.OpCodes.Box, System.Reflection.Emit.OpCodes.Br_S, System.Reflection.Emit.OpCodes.Brfalse_S, System.Reflection.Emit.OpCodes.Ceq, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstantOne(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConvertArithmeticResult(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Dynamic.Utils.TypeUtils.GetNullableConstructor(), System.Reflection.Emit.OpCodes.Isinst, System.Reflection.Emit.OpCodes.Ldc_I4_0, System.Reflection.Emit.OpCodes.Ldc_I4_1, System.Reflection.Emit.OpCodes.Ldlen, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.ILGenerator.MarkLabel(), System.Reflection.Emit.OpCodes.Neg, System.Reflection.Emit.OpCodes.Newobj, System.Reflection.Emit.OpCodes.Not, System.Reflection.Emit.OpCodes.Stloc, System.Reflection.Emit.OpCodes.Sub, and System.Reflection.Emit.OpCodes.Unbox_Any.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator().