Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion
EmitReferenceCoalesceWithoutConversion()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion (BinaryExpression b) inline private
Definition at line 2526 of file LambdaCompiler.cs.
    {
        Label label = _ilg.DefineLabel();
        Label label2 = _ilg.DefineLabel();
        EmitExpression(b.Left);
        _ilg.Emit(OpCodes.Dup);
        _ilg.Emit(OpCodes.Brtrue, label2);
        _ilg.Emit(OpCodes.Pop);
        EmitExpression(b.Right);
        if (!TypeUtils.AreEquivalent(b.Right.Type, b.Type))
        {
            if (b.Right.Type.IsValueType)
            {
                _ilg.Emit(OpCodes.Box, b.Right.Type);
            }
            _ilg.Emit(OpCodes.Castclass, b.Type);
        }
        _ilg.Emit(OpCodes.Br_S, label);
        _ilg.MarkLabel(label2);
        if (!TypeUtils.AreEquivalent(b.Left.Type, b.Type))
        {
            _ilg.Emit(OpCodes.Castclass, b.Type);
        }
        _ilg.MarkLabel(label);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Reflection.Emit.OpCodes.Box, System.Reflection.Emit.OpCodes.Br_S, System.Reflection.Emit.OpCodes.Brtrue, System.Reflection.Emit.OpCodes.Castclass, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.OpCodes.Dup, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Reflection.Emit.ILGenerator.MarkLabel(), and System.Reflection.Emit.OpCodes.Pop.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitCoalesceBinaryExpression().