Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryOp
EmitLiftedBinaryOp()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryOp (ExpressionType op, Type leftType, Type rightType, Type resultType, bool liftedToNull) inline private
Definition at line 569 of file LambdaCompiler.cs.
    {
        switch (op)
        {
        case ExpressionType.And:
            if (leftType == typeof(bool?))
            {
                EmitLiftedBooleanAnd();
            }
            else
            {
                EmitLiftedBinaryArithmetic(op, leftType, rightType, resultType);
            }
            break;
        case ExpressionType.Or:
            if (leftType == typeof(bool?))
            {
                EmitLiftedBooleanOr();
            }
            else
            {
                EmitLiftedBinaryArithmetic(op, leftType, rightType, resultType);
            }
            break;
        case ExpressionType.Add:
        case ExpressionType.AddChecked:
        case ExpressionType.Divide:
        case ExpressionType.ExclusiveOr:
        case ExpressionType.LeftShift:
        case ExpressionType.Modulo:
        case ExpressionType.Multiply:
        case ExpressionType.MultiplyChecked:
        case ExpressionType.RightShift:
        case ExpressionType.Subtract:
        case ExpressionType.SubtractChecked:
            EmitLiftedBinaryArithmetic(op, leftType, rightType, resultType);
            break;
        case ExpressionType.Equal:
        case ExpressionType.GreaterThan:
        case ExpressionType.GreaterThanOrEqual:
        case ExpressionType.LessThan:
        case ExpressionType.LessThanOrEqual:
        case ExpressionType.NotEqual:
            if (liftedToNull)
            {
                EmitLiftedToNullRelational(op, leftType);
            }
            else
            {
                EmitLiftedRelational(op, leftType);
            }
            break;
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanAnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanOr(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedRelational(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedToNullRelational().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryOperator().