Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitDelegateConstruction
EmitDelegateConstruction() [1/2]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitDelegateConstruction (LambdaCompiler inner) inline private
Definition at line 2303 of file LambdaCompiler.cs.
    {
        Type type = inner._lambda.Type;
        DynamicMethod value = inner._method as DynamicMethod;
        _boundConstants.EmitConstant(this, value, typeof(MethodInfo));
        _ilg.EmitType(type);
        EmitClosureCreation(inner);
        _ilg.Emit(OpCodes.Callvirt, CachedReflectionInfo.MethodInfo_CreateDelegate_Type_Object);
        _ilg.Emit(OpCodes.Castclass, type);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._boundConstants, System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Callvirt, System.Reflection.Emit.OpCodes.Castclass, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitClosureCreation(), System.Linq.Expressions.Compiler.BoundConstants.EmitConstant(), System.Linq.inner, System.Linq.Expressions.CachedReflectionInfo.MethodInfo_CreateDelegate_Type_Object, System.type, and System.value.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitDelegateConstruction(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaExpression().