Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitVariableAssignment
EmitVariableAssignment()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitVariableAssignment (AssignBinaryExpression node, CompilationFlags flags) inline private
Definition at line 1582 of file LambdaCompiler.cs.
    {
        ParameterExpression parameterExpression = (ParameterExpression)node.Left;
        CompilationFlags compilationFlags = flags & CompilationFlags.EmitAsTypeMask;
        if (node.IsByRef)
        {
            EmitAddress(node.Right, node.Right.Type);
        }
        else
        {
            EmitExpression(node.Right);
        }
        if (compilationFlags != CompilationFlags.EmitAsVoidType)
        {
            _ilg.Emit(OpCodes.Dup);
        }
        if (parameterExpression.IsByRef)
        {
            LocalBuilder local = GetLocal(parameterExpression.Type);
            _ilg.Emit(OpCodes.Stloc, local);
            _scope.EmitGet(parameterExpression);
            _ilg.Emit(OpCodes.Ldloc, local);
            FreeLocal(local);
            _ilg.EmitStoreValueIndirect(parameterExpression.Type);
        }
        else
        {
            _scope.EmitSet(parameterExpression);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Linq.Expressions.Compiler.LambdaCompiler._scope, System.Reflection.Emit.OpCodes.Dup, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.CompilerScope.EmitGet(), System.Linq.Expressions.Compiler.CompilerScope.EmitSet(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Reflection.Emit.OpCodes.Ldloc, and System.Reflection.Emit.OpCodes.Stloc.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitAssign().