Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitHashtableSwitch
TryEmitHashtableSwitch()
bool System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitHashtableSwitch (SwitchExpression node, CompilationFlags flags) inline private
Definition at line 3243 of file LambdaCompiler.cs.
    {
        if (node.Comparison != CachedReflectionInfo.String_op_Equality_String_String && node.Comparison != CachedReflectionInfo.String_Equals_String_String)
        {
            return false;
        }
        int num = 0;
        foreach (SwitchCase @case in node.Cases)
        {
            foreach (Expression testValue in @case.TestValues)
            {
                if (!(testValue is ConstantExpression))
                {
                    return false;
                }
                num++;
            }
        }
        if (num < 7)
        {
            return false;
        }
        List<ElementInit> list = new List<ElementInit>(num);
        System.Collections.Generic.ArrayBuilder<SwitchCase> builder = new System.Collections.Generic.ArrayBuilder<SwitchCase>(node.Cases.Count);
        int value = -1;
        MethodInfo dictionaryOfStringInt32_Add_String_Int = CachedReflectionInfo.DictionaryOfStringInt32_Add_String_Int32;
        int i = 0;
        for (int count = node.Cases.Count; i < count; i++)
        {
            foreach (ConstantExpression testValue2 in node.Cases[i].TestValues)
            {
                if (testValue2.Value != null)
                {
                    list.Add(Expression.ElementInit(dictionaryOfStringInt32_Add_String_Int, new TrueReadOnlyCollection<Expression>(testValue2, Utils.Constant(i))));
                }
                else
                {
                    value = i;
                }
            }
            builder.UncheckedAdd(Expression.SwitchCase(node.Cases[i].Body, new TrueReadOnlyCollection<Expression>(Utils.Constant(i))));
        }
        MemberExpression memberExpression = CreateLazyInitializedField<Dictionary<string, int>>("dictionarySwitch");
        Expression dictInit = Expression.Condition(Expression.Equal(memberExpression, Expression.Constant(null, memberExpression.Type)), Expression.Assign(memberExpression, Expression.ListInit(Expression.New(CachedReflectionInfo.DictionaryOfStringInt32_Ctor_Int32, new TrueReadOnlyCollection<Expression>(Utils.Constant(list.Count))), list)), memberExpression);
        ParameterExpression parameterExpression = Expression.Variable(typeof(string), "switchValue");
        ParameterExpression parameterExpression2 = Expression.Variable(typeof(int), "switchIndex");
        BlockExpression node2 = Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression2, parameterExpression), new TrueReadOnlyCollection<Expression>(Expression.Assign(parameterExpression, node.SwitchValue), Expression.IfThenElse(Expression.Equal(parameterExpression, Expression.Constant(null, typeof(string))), Expression.Assign(parameterExpression2, Utils.Constant(value)), Expression.IfThenElse(CallTryGetValue(dictInit, parameterExpression, parameterExpression2), Utils.Empty, Expression.Assign(parameterExpression2, Utils.Constant(-1)))), Expression.Switch(node.Type, parameterExpression2, node.DefaultBody, null, builder.ToReadOnly())));
        EmitExpression(node2, flags);
        return true;
    }
References System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Compiler.LambdaCompiler.CallTryGetValue(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Utils.Constant(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.CachedReflectionInfo.DictionaryOfStringInt32_Add_String_Int32, System.Linq.Expressions.CachedReflectionInfo.DictionaryOfStringInt32_Ctor_Int32, System.Linq.Expressions.Expression< TDelegate >.ElementInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Utils.Empty, System.Linq.Expressions.Expression< TDelegate >.Equal(), System.Linq.Expressions.Expression< TDelegate >.IfThenElse(), System.list, System.Linq.Expressions.Expression< TDelegate >.ListInit(), System.Linq.Expressions.Expression< TDelegate >.New(), System.Linq.Expressions.CachedReflectionInfo.String_Equals_String_String, System.Linq.Expressions.CachedReflectionInfo.String_op_Equality_String_String, System.Linq.Expressions.Expression< TDelegate >.Switch(), System.Linq.Expressions.Expression< TDelegate >.SwitchCase(), System.value, and System.Linq.Expressions.Expression< TDelegate >.Variable().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchExpression().