Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitThrow
EmitThrow()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitThrow (UnaryExpression expr, CompilationFlags flags) inline private
Definition at line 3449 of file LambdaCompiler.cs.
    {
        if (expr.Operand == null)
        {
            CheckRethrow();
            _ilg.Emit(OpCodes.Rethrow);
        }
        else
        {
            EmitExpression(expr.Operand);
            _ilg.Emit(OpCodes.Throw);
        }
        EmitUnreachable(expr, flags);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Linq.Expressions.Compiler.LambdaCompiler.CheckRethrow(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnreachable(), System.Linq.Expressions.UnaryExpression.Operand, System.Reflection.Emit.OpCodes.Rethrow, and System.Reflection.Emit.OpCodes.Throw.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitThrowUnaryExpression().