Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf
AddressOf() [5/6]
void System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf (ParameterExpression node, Type type) inline private
Definition at line 157 of file LambdaCompiler.cs.
    {
        if (TypeUtils.AreEquivalent(type, node.Type))
        {
            if (node.IsByRef)
            {
                _scope.EmitGet(node);
            }
            else
            {
                _scope.EmitAddressOf(node);
            }
        }
        else if (node.Type.IsByRef && node.Type.GetElementType() == type)
        {
            EmitExpression(node);
        }
        else
        {
            EmitExpressionAddress(node, type);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._scope, System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Linq.Expressions.Compiler.CompilerScope.EmitAddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAddress(), System.Linq.Expressions.Compiler.CompilerScope.EmitGet(), and System.type.