Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinding
EmitBinding()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinding (MemberBinding binding, Type objectType) inline private
Definition at line 1783 of file LambdaCompiler.cs.
    {
        switch (binding.BindingType)
        {
        case MemberBindingType.Assignment:
            EmitMemberAssignment((MemberAssignment)binding, objectType);
            break;
        case MemberBindingType.ListBinding:
            EmitMemberListBinding((MemberListBinding)binding);
            break;
        case MemberBindingType.MemberBinding:
            EmitMemberMemberBinding((MemberMemberBinding)binding);
            break;
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberListBinding(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberMemberBinding().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit().