Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitQuote
EmitQuote()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitQuote (UnaryExpression quote) inline private
Definition at line 3432 of file LambdaCompiler.cs.
    {
        EmitConstant(quote.Operand, quote.Type);
        if (_scope.NearestHoistedLocals != null)
        {
            EmitConstant(_scope.NearestHoistedLocals, typeof(object));
            _scope.EmitGet(_scope.NearestHoistedLocals.SelfVariable);
            _ilg.Emit(OpCodes.Call, CachedReflectionInfo.RuntimeOps_Quote);
            _ilg.Emit(OpCodes.Castclass, quote.Type);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Linq.Expressions.Compiler.LambdaCompiler._scope, System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.OpCodes.Castclass, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstant(), System.Linq.Expressions.Compiler.CompilerScope.EmitGet(), System.Linq.Expressions.Compiler.CompilerScope.NearestHoistedLocals, System.Linq.Expressions.CachedReflectionInfo.RuntimeOps_Quote, and System.Linq.Expressions.Compiler.HoistedLocals.SelfVariable.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitQuoteUnaryExpression().