Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid
EmitExpressionAsVoid() [2/2]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid (Expression node, CompilationFlags flags) inline private
Definition at line 1127 of file LambdaCompiler.cs.
    {
        CompilationFlags flags2 = EmitExpressionStart(node);
        switch (node.NodeType)
        {
        case ExpressionType.Assign:
            EmitAssign((AssignBinaryExpression)node, CompilationFlags.EmitAsVoidType);
            break;
        case ExpressionType.Block:
            Emit((BlockExpression)node, UpdateEmitAsTypeFlag(flags, CompilationFlags.EmitAsVoidType));
            break;
        case ExpressionType.Throw:
            EmitThrow((UnaryExpression)node, CompilationFlags.EmitAsVoidType);
            break;
        case ExpressionType.Goto:
            EmitGotoExpression(node, UpdateEmitAsTypeFlag(flags, CompilationFlags.EmitAsVoidType));
            break;
        default:
            if (node.Type == typeof(void))
            {
                EmitExpression(node, UpdateEmitExpressionStartFlag(flags, CompilationFlags.EmitNoExpressionStart));
                break;
            }
            EmitExpression(node, CompilationFlags.EmitNoExpressionStart | CompilationFlags.EmitAsNoTail);
            _ilg.Emit(OpCodes.Pop);
            break;
        case ExpressionType.Constant:
        case ExpressionType.Parameter:
        case ExpressionType.Default:
            break;
        }
        EmitExpressionEnd(flags2);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitAssign(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionEnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionStart, System.Linq.Expressions.Compiler.LambdaCompiler.EmitGotoExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitThrow(), System.Reflection.Emit.OpCodes.Pop, System.Linq.Expressions.Compiler.LambdaCompiler.UpdateEmitAsTypeFlag(), and System.Linq.Expressions.Compiler.LambdaCompiler.UpdateEmitExpressionStartFlag().