Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitGetArrayElement
EmitGetArrayElement()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitGetArrayElement (Type arrayType) inline private
Definition at line 1284 of file LambdaCompiler.cs.
    {
        if (arrayType.IsSZArray)
        {
            _ilg.EmitLoadElement(arrayType.GetElementType());
        }
        else
        {
            _ilg.Emit(OpCodes.Call, TypeUtils.GetArrayGetMethod(arrayType));
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.ILGenerator.Emit(), and System.Dynamic.Utils.TypeUtils.GetArrayGetMethod().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryOperator(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitGetIndexCall().