Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.LambdaCompiler
LambdaCompiler() [1/2]
System.Linq.Expressions.Compiler.LambdaCompiler.LambdaCompiler (AnalyzedTree tree, LambdaExpression lambda) inline private
Definition at line 1017 of file LambdaCompiler.cs.
    {
        Type[] parameterTypes = GetParameterTypes(lambda, typeof(Closure));
        int num = Interlocked.Increment(ref s_lambdaMethodIndex);
        DynamicMethod dynamicMethod = new DynamicMethod(lambda.Name ?? ("lambda_method" + num), lambda.ReturnType, parameterTypes, restrictedSkipVisibility: true);
        _tree = tree;
        _lambda = lambda;
        _method = dynamicMethod;
        _ilg = dynamicMethod.GetILGenerator();
        _hasClosureArgument = true;
        _scope = tree.Scopes[lambda];
        _boundConstants = tree.Constants[lambda];
        InitializeMethod();
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._boundConstants, System.Linq.Expressions.Compiler.LambdaCompiler._hasClosureArgument, System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Linq.Expressions.Compiler.LambdaCompiler._lambda, System.Linq.Expressions.Compiler.LambdaCompiler._method, System.Linq.Expressions.Compiler.LambdaCompiler._scope, System.Linq.Expressions.Compiler.LambdaCompiler._tree, System.Linq.Expressions.Compiler.LambdaCompiler.GetParameterTypes(), System.Threading.Interlocked.Increment(), System.Linq.Expressions.Compiler.LambdaCompiler.InitializeMethod(), and System.Linq.Expressions.Compiler.LambdaCompiler.s_lambdaMethodIndex.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.Compile(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDelegateConstruction(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitInlinedInvoke().