Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchComparison
EmitBranchComparison()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchComparison (bool branch, BinaryExpression node, Label label) inline private
Definition at line 2767 of file LambdaCompiler.cs.
    {
        bool flag = branch == (node.NodeType == ExpressionType.Equal);
        if (node.Method != null)
        {
            EmitBinaryMethod(node, CompilationFlags.EmitAsNoTail);
            EmitBranchOp(branch, label);
        }
        else if (ConstantCheck.IsNull(node.Left))
        {
            if (node.Right.Type.IsNullableType())
            {
                EmitAddress(node.Right, node.Right.Type);
                _ilg.EmitHasValue(node.Right.Type);
            }
            else
            {
                EmitExpression(GetEqualityOperand(node.Right));
            }
            EmitBranchOp(!flag, label);
        }
        else if (ConstantCheck.IsNull(node.Right))
        {
            if (node.Left.Type.IsNullableType())
            {
                EmitAddress(node.Left, node.Left.Type);
                _ilg.EmitHasValue(node.Left.Type);
            }
            else
            {
                EmitExpression(GetEqualityOperand(node.Left));
            }
            EmitBranchOp(!flag, label);
        }
        else if (node.Left.Type.IsNullableType() || node.Right.Type.IsNullableType())
        {
            EmitBinaryExpression(node);
            EmitBranchOp(branch, label);
        }
        else
        {
            EmitExpression(GetEqualityOperand(node.Left));
            EmitExpression(GetEqualityOperand(node.Right));
            _ilg.Emit(flag ? OpCodes.Beq : OpCodes.Bne_Un, label);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Beq, System.Reflection.Emit.OpCodes.Bne_Un, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryMethod(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchOp(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.GetEqualityOperand(), and System.Linq.Expressions.ConstantCheck.IsNull().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch().