Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchCases
EmitSwitchCases()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchCases (SwitchExpression node, Label[] labels, bool[] isGoto, Label @ default, Label end, CompilationFlags flags) inline private
Definition at line 3139 of file LambdaCompiler.cs.
    {
        _ilg.Emit(OpCodes.Br, @default);
        int i = 0;
        for (int count = node.Cases.Count; i < count; i++)
        {
            if (isGoto[i])
            {
                continue;
            }
            _ilg.MarkLabel(labels[i]);
            EmitExpressionAsType(node.Cases[i].Body, node.Type, flags);
            if (node.DefaultBody != null || i < count - 1)
            {
                if ((flags & CompilationFlags.EmitAsTailCallMask) == CompilationFlags.EmitAsTail)
                {
                    _ilg.Emit(OpCodes.Ret);
                }
                else
                {
                    _ilg.Emit(OpCodes.Br, end);
                }
            }
        }
        if (node.DefaultBody != null)
        {
            _ilg.MarkLabel(@default);
            EmitExpressionAsType(node.DefaultBody, node.Type, flags);
        }
        _ilg.MarkLabel(end);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Br, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType(), System.Reflection.Emit.ILGenerator.MarkLabel(), and System.Reflection.Emit.OpCodes.Ret.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchExpression(), and System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitSwitchInstruction().