Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryMethod
EmitBinaryMethod()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryMethod (BinaryExpression b, CompilationFlags flags) inline private
Definition at line 429 of file LambdaCompiler.cs.
    {
        if (b.IsLifted)
        {
            ParameterExpression parameterExpression = Expression.Variable(b.Left.Type.GetNonNullableType(), null);
            ParameterExpression parameterExpression2 = Expression.Variable(b.Right.Type.GetNonNullableType(), null);
            MethodCallExpression methodCallExpression = Expression.Call(null, b.Method, parameterExpression, parameterExpression2);
            EmitLift(resultType: (!b.IsLiftedToNull) ? typeof(bool) : methodCallExpression.Type.GetNullableType(), nodeType: b.NodeType, mc: methodCallExpression, paramList: new ParameterExpression[2] { parameterExpression, parameterExpression2 }, argList: new Expression[2] { b.Left, b.Right });
        }
        else
        {
            EmitMethodCallExpression(Expression.Call(null, b.Method, b.Left, b.Right), flags);
        }
    }
References System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCallExpression(), and System.Linq.Expressions.Expression< TDelegate >.Variable().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryExpression(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchComparison().