Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression
EmitDynamicExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression (Expression expr) inline private
Definition at line 1495 of file LambdaCompiler.cs.
    {
        IDynamicExpression dynamicExpression = (IDynamicExpression)expr;
        object obj = dynamicExpression.CreateCallSite();
        Type type = obj.GetType();
        MethodInfo invokeMethod = dynamicExpression.DelegateType.GetInvokeMethod();
        EmitConstant(obj, type);
        _ilg.Emit(OpCodes.Dup);
        LocalBuilder local = GetLocal(type);
        _ilg.Emit(OpCodes.Stloc, local);
        _ilg.Emit(OpCodes.Ldfld, GetCallSiteTargetField(type));
        _ilg.Emit(OpCodes.Ldloc, local);
        FreeLocal(local);
        List<WriteBack> writeBacks = EmitArguments(invokeMethod, dynamicExpression, 1);
        _ilg.Emit(OpCodes.Callvirt, invokeMethod);
        EmitWriteBack(writeBacks);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Callvirt, System.Reflection.Emit.OpCodes.Dup, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitArguments(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstant(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitWriteBack(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetCallSiteTargetField(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Type.GetType(), System.Reflection.Emit.OpCodes.Ldfld, System.Reflection.Emit.OpCodes.Ldloc, System.obj, System.Reflection.Emit.OpCodes.Stloc, and System.type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().