Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitSaveExceptionOrPop
EmitSaveExceptionOrPop()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitSaveExceptionOrPop (CatchBlock cb) inline private
Definition at line 3328 of file LambdaCompiler.cs.
    {
        if (cb.Variable != null)
        {
            _scope.EmitSet(cb.Variable);
        }
        else
        {
            _ilg.Emit(OpCodes.Pop);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Linq.Expressions.Compiler.LambdaCompiler._scope, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.CompilerScope.EmitSet(), System.Reflection.Emit.OpCodes.Pop, and System.Linq.Expressions.CatchBlock.Variable.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitCatchStart().