Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitClosureCreation
EmitClosureCreation()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitClosureCreation (LambdaCompiler inner) inline private
Definition at line 2275 of file LambdaCompiler.cs.
    {
        bool needsClosure = inner._scope.NeedsClosure;
        bool flag = inner._boundConstants.Count > 0;
        if (!needsClosure && !flag)
        {
            _ilg.EmitNull();
            return;
        }
        if (flag)
        {
            _boundConstants.EmitConstant(this, inner._boundConstants.ToArray(), typeof(object[]));
        }
        else
        {
            _ilg.EmitNull();
        }
        if (needsClosure)
        {
            _scope.EmitGet(_scope.NearestHoistedLocals.SelfVariable);
        }
        else
        {
            _ilg.EmitNull();
        }
        _ilg.EmitNew(CachedReflectionInfo.Closure_ObjectArray_ObjectArray);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._boundConstants, System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Linq.Expressions.Compiler.LambdaCompiler._scope, System.Linq.Expressions.CachedReflectionInfo.Closure_ObjectArray_ObjectArray, System.Linq.Expressions.Compiler.BoundConstants.EmitConstant(), System.Linq.Expressions.Compiler.CompilerScope.EmitGet(), System.Linq.inner, System.Linq.Expressions.Compiler.CompilerScope.NearestHoistedLocals, and System.Linq.Expressions.Compiler.HoistedLocals.SelfVariable.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitDelegateConstruction().