Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexExpression
EmitIndexExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexExpression (Expression expr) inline private
Definition at line 1224 of file LambdaCompiler.cs.
    {
        IndexExpression indexExpression = (IndexExpression)expr;
        Type type = null;
        if (indexExpression.Object != null)
        {
            EmitInstance(indexExpression.Object, out type);
        }
        int i = 0;
        for (int argumentCount = indexExpression.ArgumentCount; i < argumentCount; i++)
        {
            Expression argument = indexExpression.GetArgument(i);
            EmitExpression(argument);
        }
        EmitGetIndexCall(indexExpression, type);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitGetIndexCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitInstance(), and System.type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().