Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBuckets
EmitSwitchBuckets()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBuckets (SwitchInfo info, List< List< SwitchLabel > > buckets, int first, int last) inline private
Definition at line 3171 of file LambdaCompiler.cs.
    {
        while (first != last)
        {
            int num = (int)(((long)first + (long)last + 1) / 2);
            if (first == num - 1)
            {
                EmitSwitchBucket(info, buckets[first]);
            }
            else
            {
                Label label = _ilg.DefineLabel();
                _ilg.Emit(OpCodes.Ldloc, info.Value);
                EmitConstant(buckets[num - 1][^1].Constant);
                _ilg.Emit(info.IsUnsigned ? OpCodes.Bgt_Un : OpCodes.Bgt, label);
                EmitSwitchBuckets(info, buckets, first, num - 1);
                _ilg.MarkLabel(label);
            }
            first = num;
        }
        EmitSwitchBucket(info, buckets[first]);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Bgt, System.Reflection.Emit.OpCodes.Bgt_Un, System.Linq.Expressions.Constant, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstant(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBucket(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBuckets(), System.Linq.first, System.info, System.Reflection.Emit.OpCodes.Ldloc, and System.Reflection.Emit.ILGenerator.MarkLabel().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBuckets(), and System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitSwitchInstruction().