Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberListBinding
EmitMemberListBinding()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberListBinding (MemberListBinding binding) inline private
Definition at line 1830 of file LambdaCompiler.cs.
    {
        Type memberType = GetMemberType(binding.Member);
        if (binding.Member is PropertyInfo && memberType.IsValueType)
        {
            throw Error.CannotAutoInitializeValueTypeElementThroughProperty(binding.Member);
        }
        if (memberType.IsValueType)
        {
            EmitMemberAddress(binding.Member, binding.Member.DeclaringType);
        }
        else
        {
            EmitMemberGet(binding.Member, binding.Member.DeclaringType);
        }
        EmitListInit(binding.Initializers, keepOnStack: false, memberType);
    }
References System.Linq.Expressions.Error.CannotAutoInitializeValueTypeElementThroughProperty(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitListInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberGet(), and System.Linq.Expressions.Compiler.LambdaCompiler.GetMemberType().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinding().