Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.Emit
Emit()
void System.Linq.Expressions.Compiler.LambdaCompiler.Emit (BlockExpression node, CompilationFlags flags) inline private
Definition at line 2877 of file LambdaCompiler.cs.
    {
        int expressionCount = node.ExpressionCount;
        if (expressionCount != 0)
        {
            EnterScope(node);
            CompilationFlags compilationFlags = flags & CompilationFlags.EmitAsTypeMask;
            CompilationFlags compilationFlags2 = flags & CompilationFlags.EmitAsTailCallMask;
            for (int i = 0; i < expressionCount - 1; i++)
            {
                Expression expression = node.GetExpression(i);
                Expression expression2 = node.GetExpression(i + 1);
                CompilationFlags newValue = ((compilationFlags2 == CompilationFlags.EmitAsNoTail) ? CompilationFlags.EmitAsNoTail : ((!(expression2 is GotoExpression gotoExpression) || (gotoExpression.Value != null && Significant(gotoExpression.Value)) || !ReferenceLabel(gotoExpression.Target).CanReturn) ? CompilationFlags.EmitAsMiddle : CompilationFlags.EmitAsTail));
                flags = UpdateEmitAsTailCallFlag(flags, newValue);
                EmitExpressionAsVoid(expression, flags);
            }
            if (compilationFlags == CompilationFlags.EmitAsVoidType || node.Type == typeof(void))
            {
                EmitExpressionAsVoid(node.GetExpression(expressionCount - 1), compilationFlags2);
            }
            else
            {
                EmitExpressionAsType(node.GetExpression(expressionCount - 1), node.Type, compilationFlags2);
            }
            ExitScope(node);
        }
    }
References System.Linq.Expressions.Compiler.LabelInfo.CanReturn, System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Linq.Expressions.Compiler.LambdaCompiler.EnterScope(), System.Linq.Expressions.Compiler.LambdaCompiler.ExitScope(), System.Linq.Expressions.Compiler.LambdaCompiler.ReferenceLabel(), System.Linq.Expressions.Compiler.LambdaCompiler.Significant(), and System.Linq.Expressions.Compiler.LambdaCompiler.UpdateEmitAsTailCallFlag().