Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression
EmitExpression() [1/2]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression (Expression node) inline package
Definition at line 1117 of file LambdaCompiler.cs.
    {
        EmitExpression(node, CompilationFlags.EmitExpressionStart | CompilationFlags.EmitAsNoTail);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitAndAlsoBinaryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitArguments(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchComparison(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchLogical(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchNot(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCatchStart(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConvert(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitGotoExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitInstance(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLabelExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaReferenceCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitListInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewArrayExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitOrElseBinaryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitThrow(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTypeBinaryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnboxUnaryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitVariableAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitHashtableSwitch(), and System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitSwitchInstruction().