Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanAnd
EmitLiftedBooleanAnd()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanAnd () inline private
Definition at line 745 of file LambdaCompiler.cs.
    {
        Type typeFromHandle = typeof(bool?);
        Label label = _ilg.DefineLabel();
        Label label2 = _ilg.DefineLabel();
        LocalBuilder local = GetLocal(typeFromHandle);
        LocalBuilder local2 = GetLocal(typeFromHandle);
        _ilg.Emit(OpCodes.Stloc, local2);
        _ilg.Emit(OpCodes.Stloc, local);
        _ilg.Emit(OpCodes.Ldloca, local);
        _ilg.EmitGetValueOrDefault(typeFromHandle);
        _ilg.Emit(OpCodes.Brtrue_S, label);
        _ilg.Emit(OpCodes.Ldloca, local);
        _ilg.EmitHasValue(typeFromHandle);
        _ilg.Emit(OpCodes.Ldloca, local2);
        _ilg.EmitGetValueOrDefault(typeFromHandle);
        _ilg.Emit(OpCodes.Or);
        _ilg.Emit(OpCodes.Brfalse_S, label);
        _ilg.Emit(OpCodes.Ldloc, local);
        FreeLocal(local);
        _ilg.Emit(OpCodes.Br_S, label2);
        _ilg.MarkLabel(label);
        _ilg.Emit(OpCodes.Ldloc, local2);
        FreeLocal(local2);
        _ilg.MarkLabel(label2);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Br_S, System.Reflection.Emit.OpCodes.Brfalse_S, System.Reflection.Emit.OpCodes.Brtrue_S, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.ILGenerator.MarkLabel(), System.Reflection.Emit.OpCodes.Or, and System.Reflection.Emit.OpCodes.Stloc.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryOp().