Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.AddToBuckets
AddToBuckets()
static void System.Linq.Expressions.Compiler.LambdaCompiler.AddToBuckets (List< List< SwitchLabel > > buckets, SwitchLabel key) inline static private
Definition at line 3040 of file LambdaCompiler.cs.
    {
        if (buckets.Count > 0)
        {
            List<SwitchLabel> list = buckets[buckets.Count - 1];
            if (FitsInBucket(list, key.Key, 1))
            {
                list.Add(key);
                MergeBuckets(buckets);
                return;
            }
        }
        buckets.Add(new List<SwitchLabel> { key });
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.Expressions.Compiler.LambdaCompiler.FitsInBucket(), System.key, System.list, and System.Linq.Expressions.Compiler.LambdaCompiler.MergeBuckets().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitSwitchInstruction().