Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit
EmitMemberInit() [1/2]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit (MemberInitExpression init) inline private
Definition at line 1848 of file LambdaCompiler.cs.
    {
        EmitExpression(init.NewExpression);
        LocalBuilder localBuilder = null;
        if (init.NewExpression.Type.IsValueType && init.Bindings.Count > 0)
        {
            localBuilder = GetLocal(init.NewExpression.Type);
            _ilg.Emit(OpCodes.Stloc, localBuilder);
            _ilg.Emit(OpCodes.Ldloca, localBuilder);
        }
        EmitMemberInit(init.Bindings, localBuilder == null, init.NewExpression.Type);
        if (localBuilder != null)
        {
            _ilg.Emit(OpCodes.Ldloc, localBuilder);
            FreeLocal(localBuilder);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, and System.Reflection.Emit.OpCodes.Stloc.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInitExpression(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberMemberBinding().