Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitCall
EmitCall()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitCall (Type objectType, MethodInfo method) inline private
Definition at line 1401 of file LambdaCompiler.cs.
    {
        if (method.CallingConvention == CallingConventions.VarArgs)
        {
            throw Error.UnexpectedVarArgsCall(method);
        }
        OpCode opCode = (UseVirtual(method) ? OpCodes.Callvirt : OpCodes.Call);
        if (opCode == OpCodes.Callvirt && objectType.IsValueType)
        {
            _ilg.Emit(OpCodes.Constrained, objectType);
        }
        _ilg.Emit(opCode, method);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.OpCodes.Callvirt, System.Reflection.Emit.OpCodes.Constrained, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Error.UnexpectedVarArgsCall(), and System.Linq.Expressions.Compiler.LambdaCompiler.UseVirtual().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitGetIndexCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberGet(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitSetIndexCall().