Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedAndAlso
EmitLiftedAndAlso()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedAndAlso (BinaryExpression b) inline private
Definition at line 2552 of file LambdaCompiler.cs.
    {
        Type typeFromHandle = typeof(bool?);
        Label label = _ilg.DefineLabel();
        Label label2 = _ilg.DefineLabel();
        Label label3 = _ilg.DefineLabel();
        EmitExpression(b.Left);
        LocalBuilder local = GetLocal(typeFromHandle);
        _ilg.Emit(OpCodes.Stloc, local);
        _ilg.Emit(OpCodes.Ldloca, local);
        _ilg.EmitHasValue(typeFromHandle);
        _ilg.Emit(OpCodes.Ldloca, local);
        _ilg.EmitGetValueOrDefault(typeFromHandle);
        _ilg.Emit(OpCodes.Not);
        _ilg.Emit(OpCodes.And);
        _ilg.Emit(OpCodes.Brtrue, label);
        EmitExpression(b.Right);
        LocalBuilder local2 = GetLocal(typeFromHandle);
        _ilg.Emit(OpCodes.Stloc, local2);
        _ilg.Emit(OpCodes.Ldloca, local);
        _ilg.EmitGetValueOrDefault(typeFromHandle);
        _ilg.Emit(OpCodes.Brtrue_S, label2);
        _ilg.Emit(OpCodes.Ldloca, local2);
        _ilg.EmitGetValueOrDefault(typeFromHandle);
        _ilg.Emit(OpCodes.Brtrue_S, label);
        _ilg.MarkLabel(label2);
        _ilg.Emit(OpCodes.Ldloc, local2);
        FreeLocal(local2);
        _ilg.Emit(OpCodes.Br_S, label3);
        _ilg.MarkLabel(label);
        _ilg.Emit(OpCodes.Ldloc, local);
        FreeLocal(local);
        _ilg.MarkLabel(label3);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.And, System.Reflection.Emit.OpCodes.Br_S, System.Reflection.Emit.OpCodes.Brtrue, System.Reflection.Emit.OpCodes.Brtrue_S, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.ILGenerator.MarkLabel(), System.Reflection.Emit.OpCodes.Not, and System.Reflection.Emit.OpCodes.Stloc.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitAndAlsoBinaryExpression().