Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EnterScope
EnterScope()
void System.Linq.Expressions.Compiler.LambdaCompiler.EnterScope (object node) inline private
Definition at line 2905 of file LambdaCompiler.cs.
    {
        if (HasVariables(node) && (_scope.MergedScopes == null || !_scope.MergedScopes.Contains(node)))
        {
            if (!_tree.Scopes.TryGetValue(node, out var value))
            {
                value = new CompilerScope(node, isMethod: false)
                {
                    NeedsClosure = _scope.NeedsClosure
                };
            }
            _scope = value.Enter(this, _scope);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._scope, System.Linq.Expressions.Compiler.LambdaCompiler._tree, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Linq.Expressions.Compiler.CompilerScope.Enter(), System.Linq.Expressions.Compiler.LambdaCompiler.HasVariables(), System.Linq.Expressions.Compiler.CompilerScope.MergedScopes, System.Linq.Expressions.Compiler.AnalyzedTree.Scopes, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchBlock(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression().