Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitLoopExpression
EmitLoopExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitLoopExpression (Expression expr) inline private
Definition at line 2946 of file LambdaCompiler.cs.
    {
        LoopExpression loopExpression = (LoopExpression)expr;
        PushLabelBlock(LabelScopeKind.Statement);
        LabelInfo labelInfo = DefineLabel(loopExpression.BreakLabel);
        LabelInfo labelInfo2 = DefineLabel(loopExpression.ContinueLabel);
        labelInfo2.MarkWithEmptyStack();
        EmitExpressionAsVoid(loopExpression.Body);
        _ilg.Emit(OpCodes.Br, labelInfo2.Label);
        PopLabelBlock(LabelScopeKind.Statement);
        labelInfo.MarkWithEmptyStack();
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Br, System.Linq.Expressions.Compiler.LambdaCompiler.DefineLabel(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Linq.Expressions.Compiler.LambdaCompiler.PopLabelBlock(), and System.Linq.Expressions.Compiler.LambdaCompiler.PushLabelBlock().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().