Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstant
EmitConstant() [1/2]
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstant (object value) inline private
Definition at line 1482 of file LambdaCompiler.cs.
    {
        EmitConstant(value, value.GetType());
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstant(), and System.value.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstant(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstantArray< T >(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstantExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberGet(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitQuote(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBucket(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBuckets().