Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexAssignment
EmitIndexAssignment()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexAssignment (AssignBinaryExpression node, CompilationFlags flags) inline private
Definition at line 1241 of file LambdaCompiler.cs.
    {
        IndexExpression indexExpression = (IndexExpression)node.Left;
        CompilationFlags compilationFlags = flags & CompilationFlags.EmitAsTypeMask;
        Type type = null;
        if (indexExpression.Object != null)
        {
            EmitInstance(indexExpression.Object, out type);
        }
        int i = 0;
        for (int argumentCount = indexExpression.ArgumentCount; i < argumentCount; i++)
        {
            Expression argument = indexExpression.GetArgument(i);
            EmitExpression(argument);
        }
        EmitExpression(node.Right);
        LocalBuilder local = null;
        if (compilationFlags != CompilationFlags.EmitAsVoidType)
        {
            _ilg.Emit(OpCodes.Dup);
            _ilg.Emit(OpCodes.Stloc, local = GetLocal(node.Type));
        }
        EmitSetIndexCall(indexExpression, type);
        if (compilationFlags != CompilationFlags.EmitAsVoidType)
        {
            _ilg.Emit(OpCodes.Ldloc, local);
            FreeLocal(local);
        }
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Dup, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitInstance(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSetIndexCall(), System.Linq.Expressions.Compiler.LambdaCompiler.FreeLocal(), System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal(), System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Stloc, and System.type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitAssign().