Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitLabelExpression
EmitLabelExpression()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitLabelExpression (Expression expr, CompilationFlags flags) inline private
Definition at line 836 of file LambdaCompiler.cs.
    {
        LabelExpression labelExpression = (LabelExpression)expr;
        LabelInfo info = null;
        if (_labelBlock.Kind == LabelScopeKind.Block)
        {
            _labelBlock.TryGetLabelInfo(labelExpression.Target, out info);
            if (info == null && _labelBlock.Parent.Kind == LabelScopeKind.Switch)
            {
                _labelBlock.Parent.TryGetLabelInfo(labelExpression.Target, out info);
            }
        }
        if (info == null)
        {
            info = DefineLabel(labelExpression.Target);
        }
        if (labelExpression.DefaultValue != null)
        {
            if (labelExpression.Target.Type == typeof(void))
            {
                EmitExpressionAsVoid(labelExpression.DefaultValue, flags);
            }
            else
            {
                flags = UpdateEmitExpressionStartFlag(flags, CompilationFlags.EmitExpressionStart);
                EmitExpression(labelExpression.DefaultValue, flags);
            }
        }
        info.Mark();
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._labelBlock, System.Linq.Expressions.Compiler.LambdaCompiler.DefineLabel(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.info, System.Linq.Expressions.Compiler.LabelScopeInfo.Kind, System.Linq.Expressions.Compiler.LabelScopeInfo.Parent, System.Linq.Expressions.Compiler.LabelScopeInfo.TryGetLabelInfo(), and System.Linq.Expressions.Compiler.LambdaCompiler.UpdateEmitExpressionStartFlag().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression().