Terraria: System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedAndAlso
EmitUnliftedAndAlso()
void System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedAndAlso (BinaryExpression b) inline private
Definition at line 2604 of file LambdaCompiler.cs.
    {
        Label label = _ilg.DefineLabel();
        Label label2 = _ilg.DefineLabel();
        EmitExpressionAndBranch(branchValue: false, b.Left, label);
        EmitExpression(b.Right);
        _ilg.Emit(OpCodes.Br, label2);
        _ilg.MarkLabel(label);
        _ilg.Emit(OpCodes.Ldc_I4_0);
        _ilg.MarkLabel(label2);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler._ilg, System.Reflection.Emit.OpCodes.Br, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch(), System.Reflection.Emit.OpCodes.Ldc_I4_0, and System.Reflection.Emit.ILGenerator.MarkLabel().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitAndAlsoBinaryExpression().