Terraria: System.Net.Http.MultiProxy.TryParseProxyConfigPart
TryParseProxyConfigPart()
static bool System.Net.Http.MultiProxy.TryParseProxyConfigPart (ReadOnlySpan< char > proxyString, bool secure, [NotNullWhen(true)] out Uri uri, out int charactersConsumed) inline static private
Definition at line 136 of file MultiProxy.cs.
    {
        int num = (secure ? 1 : 2);
        int length = proxyString.Length;
        while (true)
        {
            int i;
            for (i = 0; i < proxyString.Length && Array.IndexOf(s_proxyDelimiters, proxyString[i]) >= 0; i++)
            {
            }
            if (i == proxyString.Length)
            {
                break;
            }
            proxyString = proxyString.Slice(i);
            int num2 = 3;
            if (proxyString.StartsWith("http="))
            {
                num2 = 2;
                proxyString = proxyString.Slice("http=".Length);
            }
            else if (proxyString.StartsWith("https="))
            {
                num2 = 1;
                proxyString = proxyString.Slice("https=".Length);
            }
            if (proxyString.StartsWith("http://"))
            {
                num2 = 2;
                proxyString = proxyString.Slice("http://".Length);
            }
            else if (proxyString.StartsWith("https://"))
            {
                num2 = 1;
                proxyString = proxyString.Slice("https://".Length);
            }
            i = proxyString.IndexOfAny(s_proxyDelimiters);
            if (i < 0)
            {
                i = proxyString.Length;
            }
            if ((num2 & num) != 0 && Uri.TryCreate("http://" + proxyString.Slice(0, i), UriKind.Absolute, out uri))
            {
                charactersConsumed = length - proxyString.Length + i;
                return true;
            }
            proxyString = proxyString.Slice(i);
        }
        uri = null;
        charactersConsumed = length;
        return false;
    }
References System.Array.IndexOf(), System.length, System.ReadOnlySpan< T >.Length, System.Net.Http.MultiProxy.s_proxyDelimiters, System.ReadOnlySpan< T >.Slice(), and System.Uri.TryCreate().
Referenced by System.Net.Http.MultiProxy.Parse(), and System.Net.Http.MultiProxy.ReadNextHelper().