Terraria: System.Net.Http.MultiProxy.ReadNext
ReadNext()
bool System.Net.Http.MultiProxy.ReadNext ([NotNullWhen(true)] out Uri uri, out bool isFinalProxy) inline
Definition at line 68 of file MultiProxy.cs.
    {
        if (_currentUri != null)
        {
            _failedProxyCache.SetProxyFailed(_currentUri);
        }
        if (!ReadNextHelper(out uri, out isFinalProxy))
        {
            _currentUri = null;
            return false;
        }
        Uri uri2 = null;
        long num = long.MaxValue;
        do
        {
            long proxyRenewTicks = _failedProxyCache.GetProxyRenewTicks(uri);
            if (proxyRenewTicks == 0L)
            {
                _currentUri = uri;
                return true;
            }
            if (proxyRenewTicks < num)
            {
                uri2 = uri;
                num = proxyRenewTicks;
            }
        }
        while (ReadNextHelper(out uri, out isFinalProxy));
        if (_currentUri == null)
        {
            uri = uri2;
            _currentUri = uri2;
            if (uri2 != null)
            {
                _failedProxyCache.TryRenewProxy(uri, num);
                return true;
            }
        }
        return false;
    }
References System.Net.Http.MultiProxy._currentUri, System.Net.Http.MultiProxy._failedProxyCache, System.Net.Http.FailedProxyCache.GetProxyRenewTicks(), System.L, System.Net.Http.MultiProxy.ReadNextHelper(), System.Net.Http.FailedProxyCache.SetProxyFailed(), and System.Net.Http.FailedProxyCache.TryRenewProxy().
Referenced by System.Net.Http.HttpWindowsProxy.GetProxy().