Terraria: System.IO.Pipes.PipeSecurity.RemoveAccessRule
RemoveAccessRule() [3/3]
bool System.IO.Pipes.PipeSecurity.RemoveAccessRule (PipeAccessRule rule) inline
Definition at line 53 of file PipeSecurity.cs.
    {
        if (rule == null)
        {
            throw new ArgumentNullException("rule");
        }
        AuthorizationRuleCollection accessRules = GetAccessRules(includeExplicit: true, includeInherited: true, rule.IdentityReference.GetType());
        for (int i = 0; i < accessRules.Count; i++)
        {
            if (accessRules[i] is PipeAccessRule pipeAccessRule && pipeAccessRule.PipeAccessRights == rule.PipeAccessRights && pipeAccessRule.IdentityReference == rule.IdentityReference && pipeAccessRule.AccessControlType == rule.AccessControlType)
            {
                return RemoveAccessRule((AccessRule)rule);
            }
        }
        if (rule.PipeAccessRights != PipeAccessRights.FullControl)
        {
            return RemoveAccessRule((AccessRule)new PipeAccessRule(rule.IdentityReference, PipeAccessRule.AccessMaskFromRights(rule.PipeAccessRights, AccessControlType.Deny), isInherited: false, rule.AccessControlType));
        }
        return RemoveAccessRule((AccessRule)rule);
    }
References System.Security.AccessControl.AccessRule< T >.AccessControlType, System.IO.Pipes.PipeAccessRule.AccessMaskFromRights(), System.Collections.ReadOnlyCollectionBase.Count, System.Security.AccessControl.CommonObjectSecurity.GetAccessRules(), System.Security.AccessControl.AuthorizationRule.IdentityReference, System.IO.Pipes.PipeAccessRule.PipeAccessRights, and System.IO.Pipes.PipeSecurity.RemoveAccessRule().
Referenced by System.IO.Pipes.PipeSecurity.RemoveAccessRule().