Terraria: System.Xml.Xsl.Xslt.XsltInput.GetLiteralAttributes
GetLiteralAttributes()
ContextInfo System.Xml.Xsl.Xslt.XsltInput.GetLiteralAttributes (bool asStylesheet) inline
Definition at line 874 of file XsltInput.cs.
    {
        int num = 0;
        int attExPrefixes = 0;
        int attExPrefixes2 = 0;
        int xPathDefaultNamespace = 0;
        int defaultCollation = 0;
        int num2 = 0;
        for (int i = 1; MoveToLiteralAttribute(i); i++)
        {
            if (IsXsltNamespace())
            {
                string localName = LocalName;
                if (Ref.Equal(localName, _atoms.Version))
                {
                    num = i;
                }
                else if (Ref.Equal(localName, _atoms.ExtensionElementPrefixes))
                {
                    attExPrefixes = i;
                }
                else if (Ref.Equal(localName, _atoms.ExcludeResultPrefixes))
                {
                    attExPrefixes2 = i;
                }
                else if (Ref.Equal(localName, _atoms.XPathDefaultNamespace))
                {
                    xPathDefaultNamespace = i;
                }
                else if (Ref.Equal(localName, _atoms.DefaultCollation))
                {
                    defaultCollation = i;
                }
                else if (Ref.Equal(localName, _atoms.UseWhen))
                {
                    num2 = i;
                }
            }
        }
        _attributesRead = true;
        MoveToElement();
        if (num != 0)
        {
            SetVersion(num);
        }
        else if (asStylesheet)
        {
            ReportError((Ref.Equal(NamespaceUri, _atoms.UriWdXsl) && Ref.Equal(LocalName, _atoms.Stylesheet)) ? System.SR.Xslt_WdXslNamespace : System.SR.Xslt_WrongStylesheetElement);
            SetVersion(1.0);
        }
        InsertExNamespaces(attExPrefixes, _ctxInfo, extensions: true);
        if (!IsExtensionNamespace(_records[0].nsUri))
        {
            if (_compiler.Version == 2)
            {
                SetXPathDefaultNamespace(xPathDefaultNamespace);
                SetDefaultCollation(defaultCollation);
                if (num2 != 0)
                {
                    ReportNYI(_atoms.UseWhen);
                }
            }
            InsertExNamespaces(attExPrefixes2, _ctxInfo, extensions: false);
        }
        return _ctxInfo;
    }
References System.Xml.Xsl.Xslt.XsltInput._atoms, System.Xml.Xsl.Xslt.XsltInput._attributesRead, System.Xml.Xsl.Xslt.XsltInput._compiler, System.Xml.Xsl.Xslt.XsltInput._ctxInfo, System.Xml.Xsl.Xslt.XsltInput._records, System.Xml.Xsl.Xslt.KeywordsTable.DefaultCollation, System.Xml.Ref.Equal(), System.Xml.Xsl.Xslt.KeywordsTable.ExcludeResultPrefixes, System.Xml.Xsl.Xslt.KeywordsTable.ExtensionElementPrefixes, System.Xml.Xsl.Xslt.XsltInput.InsertExNamespaces(), System.Xml.Xsl.Xslt.XsltInput.IsExtensionNamespace(), System.Xml.Xsl.Xslt.XsltInput.IsXsltNamespace(), System.Xml.Xsl.Xslt.XsltInput.LocalName, System.Xml.Xsl.Xslt.XsltInput.MoveToElement(), System.Xml.Xsl.Xslt.XsltInput.MoveToLiteralAttribute(), System.Xml.Xsl.Xslt.XsltInput.NamespaceUri, System.Xml.Xsl.Xslt.XsltInput.ReportError(), System.Xml.Xsl.Xslt.XsltInput.ReportNYI(), System.Xml.Xsl.Xslt.XsltInput.SetDefaultCollation(), System.Xml.Xsl.Xslt.XsltInput.SetVersion(), System.Xml.Xsl.Xslt.XsltInput.SetXPathDefaultNamespace(), System.Xml.Xsl.Xslt.KeywordsTable.Stylesheet, System.Xml.Xsl.Xslt.KeywordsTable.UriWdXsl, System.Xml.Xsl.Xslt.KeywordsTable.UseWhen, System.Xml.Xsl.Xslt.Compiler.Version, System.Xml.Xsl.Xslt.KeywordsTable.Version, System.Xml.Xsl.Xslt.KeywordsTable.XPathDefaultNamespace, System.SR.Xslt_WdXslNamespace, and System.SR.Xslt_WrongStylesheetElement.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadLiteralResultElement().