Terraria: System.Xml.Xsl.Xslt.XsltInput.InsertExNamespaces
InsertExNamespaces()
void System.Xml.Xsl.Xslt.XsltInput.InsertExNamespaces (int attExPrefixes, ContextInfo ctxInfo, bool extensions) inline private
Definition at line 957 of file XsltInput.cs.
    {
        if (!MoveToLiteralAttribute(attExPrefixes))
        {
            return;
        }
        string value = Value;
        if (value.Length == 0)
        {
            return;
        }
        if (!extensions && _compiler.Version != 1 && value == "#all")
        {
            ctxInfo.nsList = new NsDecl(ctxInfo.nsList, null, null);
            return;
        }
        _compiler.EnterForwardsCompatible();
        string[] array = XmlConvert.SplitString(value);
        for (int i = 0; i < array.Length; i++)
        {
            if (array[i] == "#default")
            {
                array[i] = LookupXmlNamespace(string.Empty);
                if (array[i].Length == 0 && _compiler.Version != 1 && !BackwardCompatibility)
                {
                    ReportError(System.SR.Xslt_ExcludeDefault);
                }
            }
            else
            {
                array[i] = LookupXmlNamespace(array[i]);
            }
        }
        if (!_compiler.ExitForwardsCompatible(ForwardCompatibility))
        {
            return;
        }
        for (int j = 0; j < array.Length; j++)
        {
            if (array[j] != null)
            {
                ctxInfo.nsList = new NsDecl(ctxInfo.nsList, null, array[j]);
                if (extensions)
                {
                    _scopeManager.AddExNamespace(array[j]);
                }
            }
        }
    }
References System.Xml.Xsl.Xslt.XsltInput._compiler, System.Xml.Xsl.Xslt.XsltInput._scopeManager, System.array, System.Xml.Xsl.Xslt.XsltInput.BackwardCompatibility, System.Xml.Dictionary, System.Xml.Xsl.Xslt.Compiler.EnterForwardsCompatible(), System.Xml.Xsl.Xslt.Compiler.ExitForwardsCompatible(), System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.LookupXmlNamespace(), System.Xml.Xsl.Xslt.XsltInput.MoveToLiteralAttribute(), System.Xml.Xsl.Xslt.XsltInput.ReportError(), System.Xml.XmlConvert.SplitString(), System.value, System.Xml.Xsl.Xslt.XsltInput.Value, System.Xml.Xsl.Xslt.Compiler.Version, and System.SR.Xslt_ExcludeDefault.
Referenced by System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), and System.Xml.Xsl.Xslt.XsltInput.GetLiteralAttributes().