Terraria: System.Xml.Xsl.Xslt.XsltInput.IsNullNamespace
IsNullNamespace()
bool System.Xml.Xsl.Xslt.XsltInput.IsNullNamespace () inline
Definition at line 712 of file XsltInput.cs.
    {
        return IsNs(string.Empty);
    }
References System.Xml.Xsl.Xslt.XsltInput.IsNs().
Referenced by System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.GetVersionAttribute(), and System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().