Terraria: System.Xml.Xsl.Xslt.XsltInput.MoveToElement
MoveToElement()
void System.Xml.Xsl.Xslt.XsltInput.MoveToElement () inline
Definition at line 654 of file XsltInput.cs.
    {
        _currentRecord = 0;
    }
References System.Xml.Xsl.Xslt.XsltInput._currentRecord.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.GetLiteralAttributes(), System.Xml.Xsl.Xslt.XsltLoader.LoadFallbacks(), System.Xml.Xsl.Xslt.XsltLoader.LoadKey(), and System.Xml.Xsl.Xslt.XsltLoader.LoadNamespaceAlias().