Terraria: System.Xml.Xsl.Xslt.XsltInput.ReportNYI
ReportNYI()
void System.Xml.Xsl.Xslt.XsltInput.ReportNYI (string arg) inline private
Definition at line 1104 of file XsltInput.cs.
    {
        ReportErrorFC(System.SR.Xslt_NotYetImplemented, arg);
    }
References System.Xml.Xsl.Xslt.XsltInput.ReportErrorFC(), and System.SR.Xslt_NotYetImplemented.
Referenced by System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.GetLiteralAttributes(), System.Xml.Xsl.Xslt.XsltInput.SetDefaultCollation(), and System.Xml.Xsl.Xslt.XsltInput.SetXPathDefaultNamespace().