Terraria: System.Xml.Xsl.Xslt.XsltInput.FindStylesheetElement
FindStylesheetElement()
bool System.Xml.Xsl.Xslt.XsltInput.FindStylesheetElement () inline
Definition at line 275 of file XsltInput.cs.
    {
        if (!_topLevelReader && _reader.ReadState != ReadState.Interactive)
        {
            return false;
        }
        IDictionary<string, string> dictionary = null;
        if (_reader.ReadState == ReadState.Interactive && _reader is IXmlNamespaceResolver xmlNamespaceResolver)
        {
            dictionary = xmlNamespaceResolver.GetNamespacesInScope(XmlNamespaceScope.ExcludeXml);
        }
        while (MoveToNextSibling() && _nodeType == XmlNodeType.Whitespace)
        {
        }
        if (_nodeType == XmlNodeType.Element)
        {
            if (dictionary != null)
            {
                foreach (KeyValuePair<string, string> item in dictionary)
                {
                    if (_scopeManager.LookupNamespace(item.Key) == null)
                    {
                        string nsUri = _atoms.NameTable.Add(item.Value);
                        _scopeManager.AddNsDeclaration(item.Key, nsUri);
                        _ctxInfo.AddNamespace(item.Key, nsUri);
                    }
                }
            }
            return true;
        }
        return false;
    }
References System.Xml.Xsl.Xslt.XsltInput._atoms, System.Xml.Xsl.Xslt.XsltInput._ctxInfo, System.Xml.Xsl.Xslt.XsltInput._nodeType, System.Xml.Xsl.Xslt.XsltInput._reader, System.Xml.Xsl.Xslt.XsltInput._scopeManager, System.Xml.Xsl.Xslt.XsltInput._topLevelReader, System.Xml.XmlNameTable.Add(), System.Xml.Xsl.Xslt.XsltInput.ContextInfo.AddNamespace(), System.dictionary, System.item, System.Xml.Xsl.Xslt.XsltInput.MoveToNextSibling(), System.Xml.Xsl.Xslt.KeywordsTable.NameTable, and System.Xml.XmlReader.ReadState.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadDocument().