Terraria: System.Xml.Xsl.Xslt.XsltInput.ReadAttribute
ReadAttribute()
bool System.Xml.Xsl.Xslt.XsltInput.ReadAttribute (ref Record rec) inline private
Definition at line 410 of file XsltInput.cs.
    {
        FillupRecord(ref rec);
        if (Ref.Equal(rec.prefix, _atoms.Xmlns))
        {
            string nsUri = _atoms.NameTable.Add(_reader.Value);
            if (!Ref.Equal(rec.localName, _atoms.Xml))
            {
                _scopeManager.AddNsDeclaration(rec.localName, nsUri);
                _ctxInfo.AddNamespace(rec.localName, nsUri);
            }
            return false;
        }
        if (rec.prefix.Length == 0 && Ref.Equal(rec.localName, _atoms.Xmlns))
        {
            string nsUri2 = _atoms.NameTable.Add(_reader.Value);
            _scopeManager.AddNsDeclaration(string.Empty, nsUri2);
            _ctxInfo.AddNamespace(string.Empty, nsUri2);
            return false;
        }
        if (!_reader.ReadAttributeValue())
        {
            rec.value = string.Empty;
            SetRecordEnd(ref rec);
            return true;
        }
        if (_readerLineInfo != null)
        {
            int num = ((_reader.NodeType == XmlNodeType.EntityReference) ? (-2) : (-1));
            rec.valueStart = new Location(_readerLineInfo.LineNumber, _readerLineInfo.LinePosition + num);
            if (_reader.BaseURI != rec.baseUri || rec.valueStart.LessOrEqual(rec.start))
            {
                int num2 = ((rec.prefix.Length != 0) ? (rec.prefix.Length + 1) : 0) + rec.localName.Length;
                rec.end = new Location(rec.start.Line, rec.start.Pos + num2 + 1);
            }
        }
        string text = string.Empty;
        _strConcat.Clear();
        do
        {
            switch (_reader.NodeType)
            {
            case XmlNodeType.EntityReference:
                _reader.ResolveEntity();
                break;
            default:
                text = _reader.Value;
                _strConcat.Concat(text);
                break;
            case XmlNodeType.EndEntity:
                break;
            }
        }
        while (_reader.ReadAttributeValue());
        rec.value = _strConcat.GetResult();
        if (_readerLineInfo != null)
        {
            int num3 = ((_reader.NodeType == XmlNodeType.EndEntity) ? 1 : text.Length) + 1;
            rec.end = new Location(_readerLineInfo.LineNumber, _readerLineInfo.LinePosition + num3);
            if (_reader.BaseURI != rec.baseUri || rec.end.LessOrEqual(rec.valueStart))
            {
                rec.end = new Location(rec.start.Line, int.MaxValue);
            }
        }
        return true;
    }
References System.Xml.Xsl.Xslt.XsltInput._atoms, System.Xml.Xsl.Xslt.XsltInput._ctxInfo, System.Xml.Xsl.Xslt.XsltInput._reader, System.Xml.Xsl.Xslt.XsltInput._readerLineInfo, System.Xml.Xsl.Xslt.XsltInput._scopeManager, System.Xml.Xsl.Xslt.XsltInput._strConcat, System.Xml.XmlNameTable.Add(), System.Xml.Xsl.Xslt.XsltInput.ContextInfo.AddNamespace(), System.Xml.XmlReader.BaseURI, System.Xml.Xsl.Runtime.StringConcat.Clear(), System.Xml.Xsl.Runtime.StringConcat.Concat(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.Xsl.Xslt.XsltInput.FillupRecord(), System.Xml.Xsl.Runtime.StringConcat.GetResult(), System.Xml.IXmlLineInfo.LineNumber, System.Xml.IXmlLineInfo.LinePosition, System.Xml.Xsl.Xslt.KeywordsTable.NameTable, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlReader.ResolveEntity(), System.Xml.Xsl.Xslt.XsltInput.SetRecordEnd(), System.text, System.Xml.XmlReader.Value, System.Xml.Xsl.Xslt.KeywordsTable.Xml, and System.Xml.Xsl.Xslt.KeywordsTable.Xmlns.
Referenced by System.Xml.Xsl.Xslt.XsltInput.ReadElement().