Terraria: System.Xml.Xsl.Xslt.XsltInput.SkipNode
SkipNode()
void System.Xml.Xsl.Xslt.XsltInput.SkipNode () inline
Definition at line 495 of file XsltInput.cs.
    {
        if (_nodeType == XmlNodeType.Element && MoveToFirstChild())
        {
            do
            {
                SkipNode();
            }
            while (MoveToNextSibling());
        }
    }
References System.Xml.Xsl.Xslt.XsltInput._nodeType, System.Xml.Xsl.Xslt.XsltInput.MoveToFirstChild(), System.Xml.Xsl.Xslt.XsltInput.MoveToNextSibling(), and System.Xml.Xsl.Xslt.XsltInput.SkipNode().
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet(), System.Xml.Xsl.Xslt.XsltLoader.LoadDocument(), System.Xml.Xsl.Xslt.XsltLoader.LoadFallbacks(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.Xml.Xsl.Xslt.XsltLoader.LoadKey(), System.Xml.Xsl.Xslt.XsltLoader.LoadMsScript(), System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet(), System.Xml.Xsl.Xslt.XsltLoader.LoadUnknownXsltInstruction(), System.Xml.Xsl.Xslt.XsltLoader.LoadWithParams(), System.Xml.Xsl.Xslt.XsltLoader.SkipEmptyContent(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.Xml.Xsl.Xslt.XsltLoader.XslApplyImports(), System.Xml.Xsl.Xslt.XsltLoader.XslChoose(), System.Xml.Xsl.Xslt.XsltLoader.XslFallback(), System.Xml.Xsl.Xslt.XsltLoader.XslText(), and System.Xml.Xsl.Xslt.XsltLoader.XslValueOf().