Terraria: System.Xml.Xsl.Xslt.XsltInput.ReadElement
ReadElement()
int System.Xml.Xsl.Xslt.XsltInput.ReadElement () inline private
Definition at line 626 of file XsltInput.cs.
    {
        _attributesRead = false;
        FillupRecord(ref _records[0]);
        _nodeType = XmlNodeType.Element;
        _isEmptyElement = _reader.IsEmptyElement;
        _ctxInfo = new ContextInfo(this);
        int num = 1;
        if (_reader.MoveToFirstAttribute())
        {
            do
            {
                ExtendRecordBuffer(num);
                if (ReadAttribute(ref _records[num]))
                {
                    num++;
                }
            }
            while (_reader.MoveToNextAttribute());
            _reader.MoveToElement();
        }
        _reader.Read();
        SetRecordEnd(ref _records[0]);
        _ctxInfo.lineInfo = BuildLineInfo();
        _attributes = null;
        return num - 1;
    }
References System.Xml.Xsl.Xslt.XsltInput._attributes, System.Xml.Xsl.Xslt.XsltInput._attributesRead, System.Xml.Xsl.Xslt.XsltInput._ctxInfo, System.Xml.Xsl.Xslt.XsltInput._isEmptyElement, System.Xml.Xsl.Xslt.XsltInput._nodeType, System.Xml.Xsl.Xslt.XsltInput._reader, System.Xml.Xsl.Xslt.XsltInput._records, System.Xml.Xsl.Xslt.XsltInput.BuildLineInfo(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.ExtendRecordBuffer(), System.Xml.Xsl.Xslt.XsltInput.FillupRecord(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.Read(), System.Xml.Xsl.Xslt.XsltInput.ReadAttribute(), and System.Xml.Xsl.Xslt.XsltInput.SetRecordEnd().
Referenced by System.Xml.Xsl.Xslt.XsltInput.ReadNextSibling().