Terraria: System.Xml.Xsl.Xslt.XsltInput.GetAttributes
GetAttributes() [2/2]
ContextInfo System.Xml.Xsl.Xslt.XsltInput.GetAttributes (XsltAttribute[] attributes) inline
Definition at line 766 of file XsltInput.cs.
    {
        _attributes = attributes;
        _records[0].value = null;
        int attExPrefixes = 0;
        int attExPrefixes2 = 0;
        int xPathDefaultNamespace = 0;
        int defaultCollation = 0;
        int num = 0;
        bool flag = IsXsltNamespace() && IsKeyword(_atoms.Output);
        bool flag2 = IsXsltNamespace() && (IsKeyword(_atoms.Stylesheet) || IsKeyword(_atoms.Transform));
        bool flag3 = _compiler.Version == 2;
        for (int i = 0; i < attributes.Length; i++)
        {
            _xsltAttributeNumber[i] = 0;
        }
        _compiler.EnterForwardsCompatible();
        if (flag2 || (flag3 && !flag))
        {
            for (int j = 1; MoveToAttributeBase(j); j++)
            {
                if (IsNullNamespace() && IsKeyword(_atoms.Version))
                {
                    SetVersion(j);
                    break;
                }
            }
        }
        if (_compiler.Version == 0)
        {
            SetVersion(1.0);
        }
        flag3 = _compiler.Version == 2;
        int num2 = (flag3 ? (XsltLoader.V2Opt | XsltLoader.V2Req) : (XsltLoader.V1Opt | XsltLoader.V1Req));
        for (int k = 1; MoveToAttributeBase(k); k++)
        {
            if (IsNullNamespace())
            {
                string localName = LocalName;
                int l;
                for (l = 0; l < attributes.Length; l++)
                {
                    if (Ref.Equal(localName, attributes[l].name) && (attributes[l].flags & num2) != 0)
                    {
                        _xsltAttributeNumber[l] = k;
                        break;
                    }
                }
                if (l == attributes.Length)
                {
                    if (Ref.Equal(localName, _atoms.ExcludeResultPrefixes) && (flag2 || flag3))
                    {
                        attExPrefixes2 = k;
                        continue;
                    }
                    if (Ref.Equal(localName, _atoms.ExtensionElementPrefixes) && (flag2 || flag3))
                    {
                        attExPrefixes = k;
                        continue;
                    }
                    if (Ref.Equal(localName, _atoms.XPathDefaultNamespace) && flag3)
                    {
                        xPathDefaultNamespace = k;
                        continue;
                    }
                    if (Ref.Equal(localName, _atoms.DefaultCollation) && flag3)
                    {
                        defaultCollation = k;
                        continue;
                    }
                    if (Ref.Equal(localName, _atoms.UseWhen) && flag3)
                    {
                        num = k;
                        continue;
                    }
                    ReportError(System.SR.Xslt_InvalidAttribute, QualifiedName, _records[0].QualifiedName);
                }
            }
            else if (IsXsltNamespace())
            {
                ReportError(System.SR.Xslt_InvalidAttribute, QualifiedName, _records[0].QualifiedName);
            }
        }
        _attributesRead = true;
        _compiler.ExitForwardsCompatible(ForwardCompatibility);
        InsertExNamespaces(attExPrefixes, _ctxInfo, extensions: true);
        InsertExNamespaces(attExPrefixes2, _ctxInfo, extensions: false);
        SetXPathDefaultNamespace(xPathDefaultNamespace);
        SetDefaultCollation(defaultCollation);
        if (num != 0)
        {
            ReportNYI(_atoms.UseWhen);
        }
        MoveToElement();
        for (int m = 0; m < attributes.Length; m++)
        {
            if (_xsltAttributeNumber[m] == 0)
            {
                int flags = attributes[m].flags;
                if ((_compiler.Version == 2 && (flags & XsltLoader.V2Req) != 0) || (_compiler.Version == 1 && (flags & XsltLoader.V1Req) != 0 && (!ForwardCompatibility || (flags & XsltLoader.V2Req) != 0)))
                {
                    ReportError(System.SR.Xslt_MissingAttribute, attributes[m].name);
                }
            }
        }
        return _ctxInfo;
    }
References System.Xml.Xsl.Xslt.XsltInput._atoms, System.Xml.Xsl.Xslt.XsltInput._attributes, System.Xml.Xsl.Xslt.XsltInput._attributesRead, System.Xml.Xsl.Xslt.XsltInput._compiler, System.Xml.Xsl.Xslt.XsltInput._ctxInfo, System.Xml.Xsl.Xslt.XsltInput._records, System.Xml.Xsl.Xslt.XsltInput._xsltAttributeNumber, System.Xml.Xsl.Xslt.KeywordsTable.DefaultCollation, System.Xml.Dictionary, System.Xml.Xsl.Xslt.Compiler.EnterForwardsCompatible(), System.Xml.Ref.Equal(), System.Xml.Xsl.Xslt.KeywordsTable.ExcludeResultPrefixes, System.Xml.Xsl.Xslt.Compiler.ExitForwardsCompatible(), System.Xml.Xsl.Xslt.KeywordsTable.ExtensionElementPrefixes, System.Xml.Xsl.Xslt.XsltInput.XsltAttribute.flags, System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.InsertExNamespaces(), System.Xml.Xsl.Xslt.XsltInput.IsKeyword(), System.Xml.Xsl.Xslt.XsltInput.IsNullNamespace(), System.Xml.Xsl.Xslt.XsltInput.IsXsltNamespace(), System.Xml.Xsl.Xslt.XsltInput.LocalName, System.Xml.Xsl.Xslt.XsltInput.MoveToAttributeBase(), System.Xml.Xsl.Xslt.XsltInput.MoveToElement(), System.Xml.Xsl.Xslt.XsltInput.XsltAttribute.name, System.Xml.Xsl.Xslt.KeywordsTable.Output, System.Xml.Xsl.Xslt.XsltInput.Record.QualifiedName, System.Xml.Xsl.Xslt.XsltInput.QualifiedName, System.Xml.Xsl.Xslt.XsltInput.ReportError(), System.Xml.Xsl.Xslt.XsltInput.ReportNYI(), System.Xml.Xsl.Xslt.XsltInput.SetDefaultCollation(), System.Xml.Xsl.Xslt.XsltInput.SetVersion(), System.Xml.Xsl.Xslt.XsltInput.SetXPathDefaultNamespace(), System.Xml.Xsl.Xslt.KeywordsTable.Stylesheet, System.Xml.Xsl.Xslt.KeywordsTable.Transform, System.Xml.Xsl.Xslt.KeywordsTable.UseWhen, System.Xml.Xsl.Xslt.XsltLoader.V1Req, System.Xml.Xsl.Xslt.XsltLoader.V2Req, System.Xml.Xsl.Xslt.XsltInput.Record.value, System.Xml.Xsl.Xslt.Compiler.Version, System.Xml.Xsl.Xslt.KeywordsTable.Version, System.Xml.Xsl.Xslt.KeywordsTable.XPathDefaultNamespace, System.SR.Xslt_InvalidAttribute, and System.SR.Xslt_MissingAttribute.