Terraria: System.Xml.Xsl.Xslt.XsltInput.BuildNameLineInfo
BuildNameLineInfo()
ISourceLineInfo System.Xml.Xsl.Xslt.XsltInput.BuildNameLineInfo () inline
Definition at line 1054 of file XsltInput.cs.
    {
        if (_readerLineInfo == null)
        {
            return BuildLineInfo();
        }
        if (LocalName == null)
        {
            FillupRecord(ref _records[_currentRecord]);
        }
        Location start = Start;
        int line = start.Line;
        int num = start.Pos + PositionAdjustment(NodeType);
        return new SourceLineInfo(Uri, new Location(line, num), new Location(line, num + QualifiedName.Length));
    }
References System.Xml.Xsl.Xslt.XsltInput._currentRecord, System.Xml.Xsl.Xslt.XsltInput._readerLineInfo, System.Xml.Xsl.Xslt.XsltInput._records, System.Xml.Xsl.Xslt.XsltInput.BuildLineInfo(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.FillupRecord(), System.Xml.Xsl.Xslt.XsltInput.LocalName, System.Xml.Xsl.Xslt.XsltInput.NodeType, System.Xml.Xsl.Xslt.XsltInput.PositionAdjustment(), System.Xml.Xsl.Xslt.XsltInput.QualifiedName, System.start, and System.Xml.Xsl.Xslt.XsltInput.Start.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Xsl.Xslt.XsltLoader.LoadFallbacks(), System.Xml.Xsl.Xslt.XsltInput.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltInput.ReportErrorFC(), System.Xml.Xsl.Xslt.XsltLoader.ReportWarning(), and System.Xml.Xsl.Xslt.XsltLoader.SkipEmptyContent().