Terraria: System.Xml.Xsl.Xslt.XsltInput.ReadNextSibling
ReadNextSibling()
bool System.Xml.Xsl.Xslt.XsltInput.ReadNextSibling () inline private
Definition at line 577 of file XsltInput.cs.
    {
        if (_currentRecord < _lastTextNode)
        {
            _currentRecord++;
            if (_currentRecord == _lastTextNode)
            {
                _lastTextNode = 0;
            }
            return true;
        }
        _currentRecord = 0;
        while (!_reader.EOF)
        {
            switch (_reader.NodeType)
            {
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
            case XmlNodeType.EntityReference:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
            {
                int num = ReadTextNodes();
                if (num != 0)
                {
                    _lastTextNode = num - 1;
                    return true;
                }
                break;
            }
            case XmlNodeType.Element:
                _scopeManager.EnterScope();
                _numAttributes = ReadElement();
                return true;
            case XmlNodeType.EndElement:
                _nodeType = XmlNodeType.EndElement;
                _isEmptyElement = false;
                FillupRecord(ref _records[0]);
                _reader.Read();
                SetRecordEnd(ref _records[0]);
                return false;
            default:
                _reader.Read();
                break;
            }
        }
        return false;
    }
References System.Xml.Xsl.Xslt.XsltInput._currentRecord, System.Xml.Xsl.Xslt.XsltInput._isEmptyElement, System.Xml.Xsl.Xslt.XsltInput._lastTextNode, System.Xml.Xsl.Xslt.XsltInput._nodeType, System.Xml.Xsl.Xslt.XsltInput._numAttributes, System.Xml.Xsl.Xslt.XsltInput._reader, System.Xml.Xsl.Xslt.XsltInput._records, System.Xml.Xsl.Xslt.XsltInput._scopeManager, System.Xml.XmlReader.EOF, System.Xml.Xsl.Xslt.XsltInput.FillupRecord(), System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.Xsl.Xslt.XsltInput.ReadElement(), System.Xml.Xsl.Xslt.XsltInput.ReadTextNodes(), and System.Xml.Xsl.Xslt.XsltInput.SetRecordEnd().
Referenced by System.Xml.Xsl.Xslt.XsltInput.MoveToFirstChild(), and System.Xml.Xsl.Xslt.XsltInput.MoveToNextSibling().