Terraria: System.Xml.Xsl.Xslt.XsltInput.GetVersionAttribute
GetVersionAttribute()
void System.Xml.Xsl.Xslt.XsltInput.GetVersionAttribute () inline
Definition at line 941 of file XsltInput.cs.
    {
        if (_compiler.Version == 2)
        {
            for (int i = 1; MoveToAttributeBase(i); i++)
            {
                if (IsNullNamespace() && IsKeyword(_atoms.Version))
                {
                    SetVersion(i);
                    break;
                }
            }
        }
        _attributesRead = true;
    }
References System.Xml.Xsl.Xslt.XsltInput._atoms, System.Xml.Xsl.Xslt.XsltInput._attributesRead, System.Xml.Xsl.Xslt.XsltInput._compiler, System.Xml.Xsl.Xslt.XsltInput.IsKeyword(), System.Xml.Xsl.Xslt.XsltInput.IsNullNamespace(), System.Xml.Xsl.Xslt.XsltInput.MoveToAttributeBase(), System.Xml.Xsl.Xslt.XsltInput.SetVersion(), System.Xml.Xsl.Xslt.Compiler.Version, and System.Xml.Xsl.Xslt.KeywordsTable.Version.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet(), and System.Xml.Xsl.Xslt.XsltLoader.LoadUnknownXsltInstruction().