Terraria: System.Xml.Xsl.Xslt.XsltInput.SetDefaultCollation
SetDefaultCollation()
void System.Xml.Xsl.Xslt.XsltInput.SetDefaultCollation (int attCollation) inline private
Definition at line 1015 of file XsltInput.cs.
    {
        if (MoveToLiteralAttribute(attCollation))
        {
            string[] array = XmlConvert.SplitString(Value);
            int i;
            for (i = 0; i < array.Length && XmlCollation.Create(array[i], throwOnError: false) == null; i++)
            {
            }
            if (i == array.Length)
            {
                ReportErrorFC(System.SR.Xslt_CollationSyntax);
            }
            else if (array[i] != "http://www.w3.org/2004/10/xpath-functions/collation/codepoint")
            {
                ReportNYI(_atoms.DefaultCollation);
            }
        }
    }
References System.Xml.Xsl.Xslt.XsltInput._atoms, System.array, System.Xml.Xsl.Runtime.XmlCollation.Create(), System.Xml.Xsl.Xslt.KeywordsTable.DefaultCollation, System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.MoveToLiteralAttribute(), System.Xml.Xsl.Xslt.XsltInput.ReportErrorFC(), System.Xml.Xsl.Xslt.XsltInput.ReportNYI(), System.Xml.XmlConvert.SplitString(), System.Xml.Xsl.Xslt.XsltInput.Value, and System.SR.Xslt_CollationSyntax.
Referenced by System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), and System.Xml.Xsl.Xslt.XsltInput.GetLiteralAttributes().