Terraria: System.Xml.Xsl.Xslt.XsltInput.SetXPathDefaultNamespace
SetXPathDefaultNamespace()
void System.Xml.Xsl.Xslt.XsltInput.SetXPathDefaultNamespace (int attNamespace) inline private
Definition at line 1007 of file XsltInput.cs.
    {
        if (MoveToLiteralAttribute(attNamespace) && Value.Length != 0)
        {
            ReportNYI(_atoms.XPathDefaultNamespace);
        }
    }
References System.Xml.Xsl.Xslt.XsltInput._atoms, System.Xml.Xsl.Xslt.XsltInput.MoveToLiteralAttribute(), System.Xml.Xsl.Xslt.XsltInput.ReportNYI(), System.Xml.Xsl.Xslt.XsltInput.Value, and System.Xml.Xsl.Xslt.KeywordsTable.XPathDefaultNamespace.
Referenced by System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), and System.Xml.Xsl.Xslt.XsltInput.GetLiteralAttributes().