Terraria: System.Xml.Xsl.Xslt.XsltInput.SetVersion
SetVersion() [2/2]
void System.Xml.Xsl.Xslt.XsltInput.SetVersion (int attVersion) inline private
Definition at line 731 of file XsltInput.cs.
    {
        MoveToLiteralAttribute(attVersion);
        double num = XPathConvert.StringToDouble(Value);
        if (double.IsNaN(num))
        {
            ReportError(System.SR.Xslt_InvalidAttrValue, _atoms.Version, Value);
            num = 1.0;
        }
        SetVersion(num);
    }
References System.Xml.Xsl.Xslt.XsltInput._atoms, System.Xml.Xsl.Xslt.XsltInput.MoveToLiteralAttribute(), System.Xml.Xsl.Xslt.XsltInput.ReportError(), System.Xml.Xsl.Xslt.XsltInput.SetVersion(), System.Xml.Xsl.XPathConvert.StringToDouble(), System.Xml.Xsl.Xslt.XsltInput.Value, System.Xml.Xsl.Xslt.KeywordsTable.Version, and System.SR.Xslt_InvalidAttrValue.
Referenced by System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.GetLiteralAttributes(), System.Xml.Xsl.Xslt.XsltInput.GetVersionAttribute(), and System.Xml.Xsl.Xslt.XsltInput.SetVersion().