Terraria: System.Xml.Xsl.Xslt.XsltInput.IsKeyword
IsKeyword()
bool System.Xml.Xsl.Xslt.XsltInput.IsKeyword (string kwd) inline
Definition at line 702 of file XsltInput.cs.
    {
        return Ref.Equal(kwd, LocalName);
    }
References System.Xml.Ref.Equal(), and System.Xml.Xsl.Xslt.XsltInput.LocalName.
Referenced by System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.GetVersionAttribute(), System.Xml.Xsl.Xslt.XsltInput.IsXsltKeyword(), System.Xml.Xsl.Xslt.XsltLoader.LoadDocument(), System.Xml.Xsl.Xslt.XsltLoader.LoadLiteralResultElement(), and System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().