Terraria: System.Xml.Xsl.Xslt.XsltInput.FillupRecord
FillupRecord()
void System.Xml.Xsl.Xslt.XsltInput.FillupRecord (ref Record rec) inline private
Definition at line 319 of file XsltInput.cs.
    {
        rec.localName = _reader.LocalName;
        rec.nsUri = _reader.NamespaceURI;
        rec.prefix = _reader.Prefix;
        rec.value = _reader.Value;
        rec.baseUri = _reader.BaseURI;
        if (_reatomize)
        {
            rec.localName = _atoms.NameTable.Add(rec.localName);
            rec.nsUri = _atoms.NameTable.Add(rec.nsUri);
            rec.prefix = _atoms.NameTable.Add(rec.prefix);
        }
        if (_readerLineInfo != null)
        {
            rec.start = new Location(_readerLineInfo.LineNumber, _readerLineInfo.LinePosition - PositionAdjustment(_reader.NodeType));
        }
    }
References System.Xml.Xsl.Xslt.XsltInput._atoms, System.Xml.Xsl.Xslt.XsltInput._reader, System.Xml.Xsl.Xslt.XsltInput._readerLineInfo, System.Xml.Xsl.Xslt.XsltInput._reatomize, System.Xml.XmlNameTable.Add(), System.Xml.XmlReader.BaseURI, System.Xml.Dictionary, System.Xml.IXmlLineInfo.LineNumber, System.Xml.IXmlLineInfo.LinePosition, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.Xsl.Xslt.KeywordsTable.NameTable, System.Xml.XmlReader.NodeType, System.Xml.Xsl.Xslt.XsltInput.PositionAdjustment(), System.Xml.XmlReader.Prefix, and System.Xml.XmlReader.Value.
Referenced by System.Xml.Xsl.Xslt.XsltInput.BuildNameLineInfo(), System.Xml.Xsl.Xslt.XsltInput.ReadAttribute(), System.Xml.Xsl.Xslt.XsltInput.ReadElement(), and System.Xml.Xsl.Xslt.XsltInput.ReadNextSibling().