Terraria: System.Xml.Xsl.Xslt.XsltInput.MoveToFirstChild
MoveToFirstChild()
bool System.Xml.Xsl.Xslt.XsltInput.MoveToFirstChild () inline
Definition at line 477 of file XsltInput.cs.
    {
        if (IsEmptyElement)
        {
            return false;
        }
        return ReadNextSibling();
    }
References System.Xml.Xsl.Xslt.XsltInput.IsEmptyElement, and System.Xml.Xsl.Xslt.XsltInput.ReadNextSibling().
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet(), System.Xml.Xsl.Xslt.XsltLoader.LoadFallbacks(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet(), System.Xml.Xsl.Xslt.XsltLoader.LoadWithParams(), System.Xml.Xsl.Xslt.XsltLoader.SkipEmptyContent(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.Xml.Xsl.Xslt.XsltLoader.XslChoose(), and System.Xml.Xsl.Xslt.XsltLoader.XslText().