Terraria: System.Xml.Xsl.Xslt.XsltInput.LookupXmlNamespace
LookupXmlNamespace()
string System.Xml.Xsl.Xslt.XsltInput.LookupXmlNamespace (string prefix) inline
Definition at line 1076 of file XsltInput.cs.
    {
        string text = _scopeManager.LookupNamespace(prefix);
        if (text != null)
        {
            return text;
        }
        if (prefix.Length == 0)
        {
            return string.Empty;
        }
        ReportError(System.SR.Xslt_InvalidPrefix, prefix);
        return null;
    }
References System.Xml.Xsl.Xslt.XsltInput._scopeManager, System.prefix, System.Xml.Xsl.Xslt.XsltInput.ReportError(), System.text, and System.SR.Xslt_InvalidPrefix.
Referenced by System.Xml.Xsl.Xslt.XsltInput.InsertExNamespaces(), System.Xml.Xsl.Xslt.XsltLoader.LoadMsScript(), System.Xml.Xsl.Xslt.XsltLoader.LoadNamespaceAlias(), System.Xml.Xsl.Xslt.XsltLoader.ParseWhitespaceRules(), and System.Xml.Xsl.Xslt.XsltLoader.ResolveQName().