Terraria: System.Xml.Xsl.Xslt.XsltInput.ReadTextNodes
ReadTextNodes()
int System.Xml.Xsl.Xslt.XsltInput.ReadTextNodes () inline private
Definition at line 507 of file XsltInput.cs.
    {
        bool flag = _reader.XmlSpace == XmlSpace.Preserve;
        bool flag2 = true;
        int num = 0;
        while (true)
        {
            XmlNodeType nodeType = _reader.NodeType;
            if (nodeType <= XmlNodeType.EntityReference)
            {
                if ((uint)(nodeType - 3) > 1u)
                {
                    if (nodeType != XmlNodeType.EntityReference)
                    {
                        break;
                    }
                    string localName = _reader.LocalName;
                    if (localName.Length > 0)
                    {
                        if (localName[0] != '#')
{
                            switch (localName)
{
                            case "lt":
                            case "gt":
                            case "quot":
                            case "apos":
                                break;
                            default:
                                goto IL_0121;
                            }
                        }
                        ExtendRecordBuffer(num);
                        FillupCharacterEntityRecord(ref _records[num]);
                        if (flag2 && !XmlCharType.IsOnlyWhitespace(_records[num].value))
{
                            flag2 = false;
                        }
                        num++;
                        continue;
                    }
                    goto IL_0121;
                }
                if (flag2 && !XmlCharType.IsOnlyWhitespace(_reader.Value))
                {
                    flag2 = false;
                }
            }
            else if ((uint)(nodeType - 13) > 1u)
            {
                if (nodeType != XmlNodeType.EndEntity)
                {
                    break;
                }
                _reader.Read();
                continue;
            }
            ExtendRecordBuffer(num);
            FillupTextRecord(ref _records[num]);
            _reader.Read();
            num++;
            continue;
            IL_0121:
            _reader.ResolveEntity();
            _reader.Read();
        }
        _nodeType = ((!flag2) ? XmlNodeType.Text : (flag ? XmlNodeType.SignificantWhitespace : XmlNodeType.Whitespace));
        return num;
    }
References System.Xml.Xsl.Xslt.XsltInput._nodeType, System.Xml.Xsl.Xslt.XsltInput._reader, System.Xml.Xsl.Xslt.XsltInput._records, System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.ExtendRecordBuffer(), System.Xml.Xsl.Xslt.XsltInput.FillupCharacterEntityRecord(), System.Xml.Xsl.Xslt.XsltInput.FillupTextRecord(), System.Xml.XmlCharType.IsOnlyWhitespace(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ResolveEntity(), System.Xml.Xsl.Xslt.XsltInput.Record.value, and System.Xml.XmlReader.Value.
Referenced by System.Xml.Xsl.Xslt.XsltInput.ReadNextSibling().