Terraria: System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute
MoveToXsltAttribute()
bool System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute (int attNum, string attName) inline
Definition at line 681 of file XsltInput.cs.
    {
        _currentRecord = _xsltAttributeNumber[attNum];
        return _currentRecord != 0;
    }
References System.Xml.Xsl.Xslt.XsltInput._currentRecord, System.Xml.Xsl.Xslt.XsltInput._xsltAttributeNumber, and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet(), System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat(), System.Xml.Xsl.Xslt.XsltLoader.LoadImport(), System.Xml.Xsl.Xslt.XsltLoader.LoadInclude(), System.Xml.Xsl.Xslt.XsltLoader.LoadMsScript(), System.Xml.Xsl.Xslt.XsltLoader.LoadNamespaceAlias(), System.Xml.Xsl.Xslt.XsltLoader.LoadOutput(), System.Xml.Xsl.Xslt.XsltLoader.LoadPreserveSpace(), System.Xml.Xsl.Xslt.XsltLoader.LoadStripSpace(), System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate(), System.Xml.Xsl.Xslt.XsltLoader.ParseCharAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseCollationAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseInputTypeAnnotationsAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseModeAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseModeListAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseNCNameAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseQNameAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseTypeAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseUseCharacterMaps(), System.Xml.Xsl.Xslt.XsltLoader.ParseValidationAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseYesNoAttribute(), System.Xml.Xsl.Xslt.XsltLoader.XslCopy(), System.Xml.Xsl.Xslt.XsltLoader.XslElement(), and System.Xml.Xsl.Xslt.XsltLoader.XslNumber().