Terraria: System.Xml.Xsl.Xslt.XsltInput.GetAttributes
GetAttributes() [1/2]
ContextInfo System.Xml.Xsl.Xslt.XsltInput.GetAttributes () inline
Definition at line 761 of file XsltInput.cs.
    {
        return GetAttributes(Array.Empty<XsltAttribute>());
    }
References System.Xml.Xsl.Xslt.XsltInput.GetAttributes().
Referenced by System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet(), System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat(), System.Xml.Xsl.Xslt.XsltLoader.LoadFallbacks(), System.Xml.Xsl.Xslt.XsltLoader.LoadImport(), System.Xml.Xsl.Xslt.XsltLoader.LoadInclude(), System.Xml.Xsl.Xslt.XsltLoader.LoadKey(), System.Xml.Xsl.Xslt.XsltLoader.LoadMsScript(), System.Xml.Xsl.Xslt.XsltLoader.LoadNamespaceAlias(), System.Xml.Xsl.Xslt.XsltLoader.LoadOutput(), System.Xml.Xsl.Xslt.XsltLoader.LoadPreserveSpace(), System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet(), System.Xml.Xsl.Xslt.XsltLoader.LoadStripSpace(), System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate(), System.Xml.Xsl.Xslt.XsltLoader.LoadUnknownXsltInstruction(), System.Xml.Xsl.Xslt.XsltLoader.XslApplyImports(), System.Xml.Xsl.Xslt.XsltLoader.XslApplyTemplates(), System.Xml.Xsl.Xslt.XsltLoader.XslAttribute(), System.Xml.Xsl.Xslt.XsltLoader.XslCallTemplate(), System.Xml.Xsl.Xslt.XsltLoader.XslChoose(), System.Xml.Xsl.Xslt.XsltLoader.XslComment(), System.Xml.Xsl.Xslt.XsltLoader.XslCopy(), System.Xml.Xsl.Xslt.XsltLoader.XslCopyOf(), System.Xml.Xsl.Xslt.XsltLoader.XslElement(), System.Xml.Xsl.Xslt.XsltLoader.XslFallback(), System.Xml.Xsl.Xslt.XsltLoader.XslForEach(), System.Xml.Xsl.Xslt.XsltLoader.XslIf(), System.Xml.Xsl.Xslt.XsltLoader.XslMessage(), System.Xml.Xsl.Xslt.XsltLoader.XslNumber(), System.Xml.Xsl.Xslt.XsltLoader.XslOtherwise(), System.Xml.Xsl.Xslt.XsltLoader.XslProcessingInstruction(), System.Xml.Xsl.Xslt.XsltLoader.XslSort(), System.Xml.Xsl.Xslt.XsltLoader.XslText(), System.Xml.Xsl.Xslt.XsltLoader.XslValueOf(), and System.Xml.Xsl.Xslt.XsltLoader.XslVarPar().