Terraria: System.Xml.Xsl.Xslt.XsltInput.FillupCharacterEntityRecord
FillupCharacterEntityRecord()
void System.Xml.Xsl.Xslt.XsltInput.FillupCharacterEntityRecord (ref Record rec) inline private
Definition at line 389 of file XsltInput.cs.
    {
        string localName = _reader.LocalName;
        rec.localName = string.Empty;
        rec.nsUri = string.Empty;
        rec.prefix = string.Empty;
        rec.baseUri = _reader.BaseURI;
        if (_readerLineInfo != null)
        {
            rec.start = new Location(_readerLineInfo.LineNumber, _readerLineInfo.LinePosition - 1);
        }
        _reader.ResolveEntity();
        _reader.Read();
        rec.value = _reader.Value;
        _reader.Read();
        if (_readerLineInfo != null)
        {
            rec.end = new Location(_readerLineInfo.LineNumber, _readerLineInfo.LinePosition + 1);
        }
    }
References System.Xml.Xsl.Xslt.XsltInput._reader, System.Xml.Xsl.Xslt.XsltInput._readerLineInfo, System.Xml.XmlReader.BaseURI, System.Xml.Dictionary, System.Xml.IXmlLineInfo.LineNumber, System.Xml.IXmlLineInfo.LinePosition, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ResolveEntity(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.Xsl.Xslt.XsltInput.ReadTextNodes().