Terraria: System.Net.NetworkInformation.SystemUnicastIPAddressInformation.MarshalUnicastIpAddressInformationCollection
MarshalUnicastIpAddressInformationCollection()
static UnicastIPAddressInformationCollection System.Net.NetworkInformation.SystemUnicastIPAddressInformation.MarshalUnicastIpAddressInformationCollection (IntPtr ptr) inline static package
Definition at line 75 of file SystemUnicastIPAddressInformation.cs.
    {
        UnicastIPAddressInformationCollection unicastIPAddressInformationCollection = new UnicastIPAddressInformationCollection();
        while (ptr != IntPtr.Zero)
        {
            global::Interop.IpHlpApi.IpAdapterUnicastAddress adapterAddress = Marshal.PtrToStructure<global::Interop.IpHlpApi.IpAdapterUnicastAddress>(ptr);
            unicastIPAddressInformationCollection.InternalAdd(new SystemUnicastIPAddressInformation(adapterAddress));
            ptr = adapterAddress.next;
        }
        return unicastIPAddressInformationCollection;
    }
References System.Net.NetworkInformation.SystemUnicastIPAddressInformation.SystemUnicastIPAddressInformation(), System.Net.NetworkInformation.UnicastIPAddressInformationCollection.InternalAdd(), System.Runtime.InteropServices.Marshal.PtrToStructure(), and System.IntPtr.Zero.
Referenced by System.Net.NetworkInformation.SystemIPInterfaceProperties.SystemIPInterfaceProperties().