Terraria: ItemDropDatabase.RegisterBoss_PumpkinMoon
RegisterBoss_PumpkinMoon()
void ItemDropDatabase.RegisterBoss_PumpkinMoon () inline private
     {
         Conditions.PumpkinMoonDropGatingChance condition = new Conditions.PumpkinMoonDropGatingChance();
         Conditions.PumpkinMoonDropGateForTrophies condition2 = new Conditions.PumpkinMoonDropGateForTrophies();
         new Conditions.IsPumpkinMoon();
         new Conditions.FromCertainWaveAndAbove(15);
         RegisterToNPC(315, ItemDropRule.ByCondition(condition, 1857, 20));
         int[] npcNetIds = new int[10] { 305, 306, 307, 308, 309, 310, 311, 312, 313, 314 };
         RegisterToMultipleNPCs(new LeadingConditionRule(condition), npcNetIds).OnSuccess(ItemDropRule.OneFromOptions(10, 1788, 1789, 1790));
         IItemDropRule rule = RegisterToNPC(325, new LeadingConditionRule(condition));
         IItemDropRule itemDropRule = ItemDropRule.Common(1835);
         itemDropRule.OnSuccess(ItemDropRule.Common(1836, 1, 30, 60), hideLootReport: true);
         rule.OnSuccess(new OneFromRulesRule(1, ItemDropRule.Common(1829), ItemDropRule.Common(1831), itemDropRule, ItemDropRule.Common(1837), ItemDropRule.Common(1845)));
         rule.OnSuccess(ItemDropRule.ByCondition(condition2, 1855));
         rule.OnSuccess(ItemDropRule.ByCondition(new Conditions.IsExpert(), 4444, 5));
         rule.OnSuccess(ItemDropRule.MasterModeCommonDrop(4941));
         rule.OnSuccess(ItemDropRule.MasterModeDropOnAllPlayers(4793, _masterModeDropRng));
         IItemDropRule itemDropRule2 = ItemDropRule.Common(1782);
         itemDropRule2.OnSuccess(ItemDropRule.Common(1783, 1, 50, 100), hideLootReport: true);
         IItemDropRule itemDropRule3 = ItemDropRule.Common(1784);
         itemDropRule3.OnSuccess(ItemDropRule.Common(1785, 1, 25, 50), hideLootReport: true);
         IItemDropRule rule2 = RegisterToNPC(327, new LeadingConditionRule(condition));
         rule2.OnSuccess(new OneFromRulesRule(1, itemDropRule2, itemDropRule3, ItemDropRule.Common(1811), ItemDropRule.Common(1826), ItemDropRule.Common(1801), ItemDropRule.Common(1802), ItemDropRule.Common(4680), ItemDropRule.Common(1798)));
         rule2.OnSuccess(ItemDropRule.ByCondition(condition2, 1856));
         rule2.OnSuccess(ItemDropRule.MasterModeCommonDrop(4942));
         rule2.OnSuccess(ItemDropRule.MasterModeDropOnAllPlayers(4812, _masterModeDropRng));
         RegisterToNPC(326, new DropBasedOnMasterAndExpertMode(new CommonDrop(1729, 1, 1, 3), new CommonDrop(1729, 1, 1, 4), new CommonDrop(1729, 1, 2, 4)));
         RegisterToNPC(325, new DropBasedOnMasterAndExpertMode(new CommonDrop(1729, 1, 15, 30), new CommonDrop(1729, 1, 25, 40), new CommonDrop(1729, 1, 30, 50)));
     }
References _masterModeDropRng, ItemDropRule.ByCondition(), ItemDropRule.Common(), ItemDropRule.MasterModeCommonDrop(), ItemDropRule.MasterModeDropOnAllPlayers(), ItemDropRule.OneFromOptions(), RegisterToMultipleNPCs(), and RegisterToNPC().
Referenced by RegisterBosses().