Terraria: ItemDropDatabase.RegisterBoss_EOW
RegisterBoss_EOW()
void ItemDropDatabase.RegisterBoss_EOW () inline private
     {
         Conditions.LegacyHack_IsBossAndExpert condition = new Conditions.LegacyHack_IsBossAndExpert();
         Conditions.LegacyHack_IsBossAndNotExpert condition2 = new Conditions.LegacyHack_IsBossAndNotExpert();
         int[] npcNetIds = new int[3] { 13, 14, 15 };
         RegisterToMultipleNPCs(new DropBasedOnMasterAndExpertMode(ItemDropRule.Common(86, 2, 1, 2), ItemDropRule.Common(86, 5, 1, 2), ItemDropRule.Common(86, 10, 1, 2)), npcNetIds);
         RegisterToMultipleNPCs(new DropBasedOnMasterAndExpertMode(ItemDropRule.Common(56, 2, 2, 5), ItemDropRule.Common(56, 2, 1, 3), ItemDropRule.Common(56, 3, 1, 2)), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.BossBagByCondition(condition, 3320), npcNetIds);
         IItemDropRule rule = RegisterToMultipleNPCs(new LeadingConditionRule(new Conditions.LegacyHack_IsABoss()), npcNetIds);
         rule.OnSuccess(ItemDropRule.MasterModeCommonDrop(4925));
         rule.OnSuccess(ItemDropRule.MasterModeDropOnAllPlayers(4799, _masterModeDropRng));
         RegisterToMultipleNPCs(ItemDropRule.ByCondition(condition2, 56, 1, 20, 60), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.ByCondition(condition2, 994, 20), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.ByCondition(condition2, 2111, 7), npcNetIds);
     }
References _masterModeDropRng, ItemDropRule.BossBagByCondition(), ItemDropRule.ByCondition(), ItemDropRule.Common(), ItemDropRule.MasterModeCommonDrop(), ItemDropRule.MasterModeDropOnAllPlayers(), and RegisterToMultipleNPCs().
Referenced by RegisterBosses().