Terraria: ItemDropDatabase.RegisterHardmodeFeathers
RegisterHardmodeFeathers()
void ItemDropDatabase.RegisterHardmodeFeathers () inline private
     {
         RegisterToNPC(156, ItemDropRule.Common(1518, 50));
         RegisterToNPC(243, ItemDropRule.Common(1519, 3));
         RegisterToMultipleNPCs(ItemDropRule.Common(1517, 300), 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280);
         RegisterToMultipleNPCs(ItemDropRule.Common(1520, 40), 159, 158);
         RegisterToNPC(48, ItemDropRule.Common(1516, 150));
         RegisterToNPC(176, new ItemDropWithConditionRule(1521, 100, 1, 1, new Conditions.BeatAnyMechBoss()));
         RegisterToNPC(205, new ItemDropWithConditionRule(1611, 2, 1, 1, new Conditions.BeatAnyMechBoss()));
     }
References ItemDropRule.Common(), RegisterToMultipleNPCs(), and RegisterToNPC().
Referenced by Populate().