Terraria: System.Diagnostics.Debugger.NotifyOfCrossThreadDependency
NotifyOfCrossThreadDependency()
static void System.Diagnostics.Debugger.NotifyOfCrossThreadDependency () inline static
Definition at line 44 of file Debugger.cs.
    {
        if (IsAttached)
        {
            NotifyOfCrossThreadDependencySlow();
        }
    }
References System.Diagnostics.Debugger.IsAttached, and System.Diagnostics.Debugger.NotifyOfCrossThreadDependencySlow().
Referenced by System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.GetStateMachineBox< TStateMachine >(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.GetStateMachineBox< TStateMachine >(), System.Threading.ThreadLocal< T >.GetValueSlow(), System.Threading.Tasks.Task< TResult >.InternalWaitCore(), and System.Threading.Tasks.ValueTask< TResult >.ToString().