Terraria: ItemDropDatabase.RegisterMiscDrops
RegisterMiscDrops()
void ItemDropDatabase.RegisterMiscDrops () inline private
     {
         RegisterToNPC(68, ItemDropRule.Common(1169));
         RegisterToMultipleNPCs(ItemDropRule.Common(3086, 1, 5, 10), 483, 482);
         RegisterToNPC(77, ItemDropRule.Common(723, 150));
         RegisterToMultipleNPCs(ItemDropRule.NormalvsExpert(3102, 2, 1), 195, 196);
         RegisterToNPC(471, ItemDropRule.NormalvsExpertOneFromOptions(2, 1, 3052, 3053, 3054));
         RegisterToNPC(153, ItemDropRule.Common(1328, 12));
         RegisterToNPC(59, new LeadingConditionRule(new Conditions.RemixSeed())).OnSuccess(ItemDropRule.Common(23, 1, 1, 2));
         RegisterToNPC(59, new LeadingConditionRule(new Conditions.RemixSeed())).OnSuccess(ItemDropRule.NormalvsExpert(1309, 8000, 5600));
         RegisterToNPC(120, new LeadingConditionRule(new Conditions.TenthAnniversaryIsUp())).OnSuccess(ItemDropRule.Common(1326, 100));
         RegisterToNPC(120, new LeadingConditionRule(new Conditions.TenthAnniversaryIsNotUp())).OnSuccess(ItemDropRule.NormalvsExpert(1326, 500, 400));
         RegisterToNPC(49, new LeadingConditionRule(new Conditions.NotRemixSeed())).OnSuccess(ItemDropRule.Common(1325, 250));
         RegisterToNPC(49, new LeadingConditionRule(new Conditions.RemixSeed())).OnSuccess(ItemDropRule.Common(1314, 250));
         RegisterToNPC(109, new LeadingConditionRule(new Conditions.NotRemixSeed())).OnSuccess(ItemDropRule.Common(1314, 5));
         RegisterToNPC(109, new LeadingConditionRule(new Conditions.RemixSeed())).OnSuccess(ItemDropRule.Common(1325, 5));
         RegisterToNPC(156, new LeadingConditionRule(new Conditions.NotRemixSeed())).OnSuccess(ItemDropRule.Common(683, 30));
         RegisterToNPC(156, new LeadingConditionRule(new Conditions.RemixSeed())).OnSuccess(ItemDropRule.Common(112, 30));
         RegisterToNPC(634, ItemDropRule.Common(4764, 40));
         RegisterToNPC(185, ItemDropRule.Common(951, 150));
         RegisterToNPC(185, new DropBasedOnExpertMode(ItemDropRule.Common(5070, 1, 1, 2), new CommonDrop(5070, 1, 1, 3)));
         RegisterToNPC(44, ItemDropRule.Common(1320, 20));
         RegisterToNPC(44, ItemDropRule.Common(88, 20));
         RegisterToNPC(60, ItemDropRule.Common(1322, 150));
         RegisterToNPC(151, ItemDropRule.Common(1322, 50));
         RegisterToNPC(24, ItemDropRule.Common(1323, 20));
         RegisterToNPC(109, ItemDropRule.Common(1324, 10));
         RegisterToNPC(109, ItemDropRule.Common(4271, 10));
         int[] npcNetIds = new int[2] { 163, 238 };
         RegisterToMultipleNPCs(ItemDropRule.Common(1308, 40), npcNetIds);
         RegisterToMultipleNPCs(new DropBasedOnExpertMode(ItemDropRule.Common(2607, 2, 1, 3), new CommonDrop(2607, 10, 1, 3, 9)), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(1306, 100), 197, 206, 169, 154);
         RegisterToNPC(244, ItemDropRule.Common(23, 1, 1, 20));
         RegisterToNPC(244, ItemDropRule.Common(662, 1, 30, 60));
         RegisterToNPC(250, ItemDropRule.Common(1244, 15));
         RegisterToNPC(172, ItemDropRule.Common(754));
         RegisterToNPC(172, ItemDropRule.Common(755));
         RegisterToNPC(110, ItemDropRule.Common(682, 200));
         RegisterToNPC(110, ItemDropRule.Common(1321, 40));
         RegisterToMultipleNPCs(ItemDropRule.Common(4428, 100), 170, 180, 171);
         RegisterToMultipleNPCs(new ItemDropWithConditionRule(4613, 25, 1, 1, new Conditions.WindyEnoughForKiteDrops()), 170, 180, 171);
         RegisterToMultipleNPCs(new ItemDropWithConditionRule(5096, 10, 1, 1, new Conditions.DontStarveIsUp()), 170, 180, 171);
         RegisterToMultipleNPCs(new ItemDropWithConditionRule(5096, 25, 1, 1, new Conditions.DontStarveIsNotUp()), 170, 180, 171);
         RegisterToNPC(154, ItemDropRule.Common(1253, 50));
         RegisterToMultipleNPCs(ItemDropRule.Common(726, 50), 169, 206);
         RegisterToNPC(243, ItemDropRule.Common(2161));
         RegisterToNPC(155, ItemDropRule.NormalvsExpert(5130, 30, 25));
         RegisterToNPC(480, ItemDropRule.Common(3269, 25));
         RegisterToNPC(480, ItemDropRule.NormalvsExpert(3781, 40, 20));
         int[] npcNetIds2 = new int[3] { 198, 199, 226 };
         RegisterToMultipleNPCs(ItemDropRule.Common(1172, 1000), npcNetIds2);
         RegisterToMultipleNPCs(ItemDropRule.Common(1293, 50), npcNetIds2);
         RegisterToMultipleNPCs(ItemDropRule.Common(2766, 7, 1, 2), npcNetIds2);
         int[] npcNetIds3 = new int[4] { 78, 79, 80, 630 };
         RegisterToMultipleNPCs(ItemDropRule.Common(870, 75), npcNetIds3);
         RegisterToMultipleNPCs(ItemDropRule.Common(871, 75), npcNetIds3);
         RegisterToMultipleNPCs(ItemDropRule.Common(872, 75), npcNetIds3);
         RegisterToNPC(473, ItemDropRule.OneFromOptions(1, 3008, 3014, 3012, 3015, 3023));
         RegisterToNPC(474, ItemDropRule.OneFromOptions(1, 3006, 3007, 3013, 3016, 3020));
         RegisterToNPC(475, ItemDropRule.OneFromOptions(1, 3029, 3030, 3051, 3022));
         RegisterToNPC(476, ItemDropRule.Common(52, 3));
         RegisterToNPC(476, ItemDropRule.Common(1724, 3));
         RegisterToNPC(476, ItemDropRule.Common(2353, 3, 5, 10));
         RegisterToNPC(476, ItemDropRule.Common(1922, 3));
         RegisterToNPC(476, ItemDropRule.Common(678, 3, 3, 5));
         RegisterToNPC(476, ItemDropRule.Common(1336, 3));
         RegisterToNPC(476, ItemDropRule.Common(2676, 3, 2, 4));
         RegisterToNPC(476, ItemDropRule.Common(2272, 3));
         RegisterToNPC(476, ItemDropRule.Common(5395, 3));
         RegisterToNPC(476, ItemDropRule.Common(4986, 3, 69, 69));
         int[] npcNetIds4 = new int[3] { 473, 474, 475 };
         RegisterToMultipleNPCs(ItemDropRule.Common(499, 1, 5, 10), npcNetIds4);
         RegisterToMultipleNPCs(ItemDropRule.Common(500, 1, 5, 15), npcNetIds4);
         RegisterToNPC(87, new ItemDropWithConditionRule(4379, 25, 1, 1, new Conditions.WindyEnoughForKiteDrops()));
         RegisterToNPC(87, new DropBasedOnExpertMode(ItemDropRule.Common(575, 1, 5, 10), ItemDropRule.Common(575, 1, 10, 20)));
         RegisterToMultipleNPCs(ItemDropRule.OneFromOptions(10, 803, 804, 805), 161, 431);
         RegisterToNPC(217, ItemDropRule.Common(1115));
         RegisterToNPC(218, ItemDropRule.Common(1116));
         RegisterToNPC(219, ItemDropRule.Common(1117));
         RegisterToNPC(220, ItemDropRule.Common(1118));
         RegisterToNPC(221, ItemDropRule.Common(1119));
         RegisterToNPC(167, ItemDropRule.Common(879, 50));
         RegisterToNPC(628, ItemDropRule.Common(313, 2, 1, 2));
         int[] npcNetIds5 = new int[3] { 143, 144, 145 };
         RegisterToMultipleNPCs(ItemDropRule.Common(593, 1, 5, 10), npcNetIds5);
         RegisterToMultipleNPCs(ItemDropRule.Common(527, 10), 79, 630);
         RegisterToNPC(80, ItemDropRule.Common(528, 10));
         RegisterToNPC(524, ItemDropRule.Common(3794, 10, 1, 3));
         RegisterToNPC(525, ItemDropRule.Common(3794, 10));
         RegisterToNPC(525, ItemDropRule.Common(522, 3, 1, 3));
         RegisterToNPC(525, ItemDropRule.Common(527, 15));
         RegisterToNPC(526, ItemDropRule.Common(3794, 10));
         RegisterToNPC(526, ItemDropRule.Common(1332, 3, 1, 3));
         RegisterToNPC(526, ItemDropRule.Common(527, 15));
         RegisterToNPC(527, ItemDropRule.Common(3794, 10));
         RegisterToNPC(527, ItemDropRule.Common(528, 15));
         RegisterToNPC(513, ItemDropRule.Common(3380, 2, 1, 2));
         RegisterToNPC(532, ItemDropRule.Common(3380, 1, 1, 3));
         RegisterToNPC(532, ItemDropRule.Common(3771, 50));
         RegisterToNPC(528, ItemDropRule.Common(2802, 25));
         RegisterToNPC(528, ItemDropRule.OneFromOptions(60, 3786, 3785, 3784));
         RegisterToNPC(529, ItemDropRule.Common(2801, 25));
         RegisterToNPC(529, ItemDropRule.OneFromOptions(40, 3786, 3785, 3784));
         RegisterToMultipleNPCs(ItemDropRule.Common(18, 100), 49, 51, 150, 93, 634);
         RegisterToMultipleNPCs(new ItemDropWithConditionRule(5097, 250, 1, 1, new Conditions.DontStarveIsNotUp()), 49, 51, 150, 93, 634, 151, 60, 137, 152);
         RegisterToMultipleNPCs(new ItemDropWithConditionRule(5097, 100, 1, 1, new Conditions.DontStarveIsUp()), 49, 51, 150, 93, 634, 151, 60, 137, 152);
         RegisterToMultipleNPCs(ItemDropRule.Common(393, 50), 16, 185, 167, 197);
         RegisterToNPC(58, ItemDropRule.Common(393, 75));
         int[] npcNetIds6 = new int[13]
         {
             494, 495, 496, 497, 498, 499, 500, 501, 502, 503,
             504, 505, 506
         };
         RegisterToMultipleNPCs(ItemDropRule.Common(18, 80), npcNetIds6).OnFailedRoll(ItemDropRule.Common(393, 80)).OnFailedRoll(ItemDropRule.Common(3285, 25));
         int[] npcNetIds7 = new int[12]
         {
             21, 201, 202, 203, 322, 323, 324, 635, 449, 450,
             451, 452
         };
         RegisterToMultipleNPCs(ItemDropRule.Common(954, 100), npcNetIds7).OnFailedRoll(ItemDropRule.Common(955, 200)).OnFailedRoll(ItemDropRule.Common(1166, 200)).OnFailedRoll(ItemDropRule.Common(1274, 500));
         RegisterToNPC(6, ItemDropRule.OneFromOptions(175, 956, 957, 958));
         int[] npcNetIds8 = new int[7] { 42, 43, 231, 232, 233, 234, 235 };
         RegisterToMultipleNPCs(ItemDropRule.OneFromOptions(100, 960, 961, 962), npcNetIds8);
         int[] npcNetIds9 = new int[5] { 31, 32, 294, 295, 296 };
         RegisterToMultipleNPCs(ItemDropRule.Common(959, 450), npcNetIds9);
         RegisterToMultipleNPCs(ItemDropRule.Common(1307, 300), npcNetIds9);
         RegisterToMultipleNPCs(ItemDropRule.Common(996, 200), 174, 179, 182, 183, 98, 83, 94, 81, 101);
         RegisterToMultipleNPCs(ItemDropRule.Common(522, 1, 2, 5), 101, 98);
         RegisterToNPC(98, ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4611, 25));
         RegisterToNPC(86, ItemDropRule.Common(526));
         RegisterToNPC(86, ItemDropRule.Common(856, 100));
         RegisterToNPC(86, ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4684, 25));
         RegisterToNPC(224, ItemDropRule.Common(4057, 100));
         RegisterToMultipleNPCs(ItemDropRule.Common(40, 1, 1, 9), 186, 432);
         RegisterToNPC(225, ItemDropRule.Common(1243, 45)).OnFailedRoll(ItemDropRule.Common(23, 1, 2, 6));
         RegisterToNPC(537, ItemDropRule.Common(23, 1, 2, 3));
         RegisterToNPC(537, ItemDropRule.NormalvsExpert(1309, 8000, 5600));
         int[] npcNetIds10 = new int[4] { 335, 336, 333, 334 };
         RegisterToMultipleNPCs(ItemDropRule.Common(1906, 20), npcNetIds10);
         RegisterToNPC(-4, ItemDropRule.Common(3111, 1, 25, 50));
         RegisterToNPC(-4, ItemDropRule.NormalvsExpert(1309, 100, 70));
         int[] npcNetIds11 = new int[18]
         {
             1, 16, 138, 141, 147, 184, 187, 433, 204, 302,
             333, 334, 335, 336, 535, 658, 659, 660
         };
         int[] npcNetIds12 = new int[4] { -6, -7, -8, -9 };
         int[] npcNetIds13 = new int[5] { -6, -7, -8, -9, -4 };
         IItemDropRule entry = RegisterToMultipleNPCs(ItemDropRule.Common(23, 1, 1, 2), npcNetIds11);
         RemoveFromMultipleNPCs(entry, npcNetIds13);
         RegisterToMultipleNPCs(ItemDropRule.Common(23, 1, 2, 5), npcNetIds12);
         IItemDropRule entry2 = RegisterToMultipleNPCs(ItemDropRule.NormalvsExpert(1309, 10000, 7000), npcNetIds11);
         RemoveFromMultipleNPCs(entry2, npcNetIds13);
         RegisterToMultipleNPCs(ItemDropRule.NormalvsExpert(1309, 10000, 7000), npcNetIds12);
         RegisterToNPC(75, ItemDropRule.Common(501, 1, 1, 3));
         RegisterToMultipleNPCs(ItemDropRule.Common(23, 1, 2, 4), 81, 183);
         RegisterToNPC(122, ItemDropRule.Common(23, 1, 5, 10));
         RegisterToNPC(71, ItemDropRule.Common(327));
         int[] npcNetIds14 = new int[9] { 2, 317, 318, 190, 191, 192, 193, 194, 133 };
         RegisterToMultipleNPCs(ItemDropRule.Common(236, 100), npcNetIds14).OnFailedRoll(ItemDropRule.Common(38, 3));
         RegisterToNPC(133, ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4683, 25));
         RegisterToNPC(104, ItemDropRule.Common(485, 60));
         RegisterToNPC(58, ItemDropRule.Common(263, 250)).OnFailedRoll(ItemDropRule.Common(118, 30));
         RegisterToNPC(102, ItemDropRule.Common(263, 250));
         int[] npcNetIds15 = new int[23]
         {
             3, 591, 590, 331, 332, 132, 161, 186, 187, 188,
             189, 200, 223, 319, 320, 321, 430, 431, 432, 433,
             434, 435, 436
         };
         RegisterToMultipleNPCs(ItemDropRule.Common(216, 50), npcNetIds15);
         RegisterToMultipleNPCs(ItemDropRule.Common(1304, 250), npcNetIds15);
         RegisterToMultipleNPCs(ItemDropRule.Common(5332, 1500), npcNetIds15);
         RegisterToMultipleNPCs(ItemDropRule.Common(8, 1, 5, 20), 590, 591);
         RegisterToMultipleNPCs(ItemDropRule.NormalvsExpert(3212, 150, 75), 489, 490);
         RegisterToMultipleNPCs(ItemDropRule.NormalvsExpert(3213, 200, 100), 489, 490);
         RegisterToNPC(223, ItemDropRule.OneFromOptions(20, 1135, 1136));
         RegisterToNPC(66, ItemDropRule.Common(267));
         RegisterToMultipleNPCs(ItemDropRule.Common(272, 35), 62, 66);
         RegisterToNPC(52, ItemDropRule.Common(251));
         RegisterToNPC(53, ItemDropRule.Common(239));
         RegisterToNPC(536, ItemDropRule.Common(3478));
         RegisterToNPC(536, ItemDropRule.Common(3479));
         RegisterToMultipleNPCs(ItemDropRule.Common(323, 3, 1, 2), 69, 581, 580, 508, 509);
         RegisterToNPC(582, ItemDropRule.Common(323, 6));
         RegisterToMultipleNPCs(ItemDropRule.Common(3772, 50), 581, 580, 508, 509);
         RegisterToNPC(73, ItemDropRule.Common(362, 1, 1, 2));
         int[] npcNetIds16 = new int[2] { 483, 482 };
         RegisterToMultipleNPCs(ItemDropRule.Common(3109, 30), npcNetIds16);
         RegisterToMultipleNPCs(ItemDropRule.Common(4400, 20), npcNetIds16);
         RegisterToMultipleNPCs(ItemDropRule.Common(68, 3), 6, 94);
         RegisterToMultipleNPCs(ItemDropRule.Common(1330, 3), 181, 173, 239, 182, 240);
         RegisterToMultipleNPCs(ItemDropRule.Common(68, 3, 1, 2), 7, 8, 9);
         RegisterToMultipleNPCs(ItemDropRule.Common(69, 1, 3, 8), 7, 8, 9);
         RegisterToMultipleNPCs(new ItemDropWithConditionRule(5094, 100, 1, 1, new Conditions.DontStarveIsUp()), 6, 7, 8, 9, 173, 181, 239, 240);
         RegisterToMultipleNPCs(new ItemDropWithConditionRule(5094, 525, 1, 1, new Conditions.DontStarveIsNotUp()), 6, 7, 8, 9, 173, 181, 239, 240);
         RegisterToMultipleNPCs(new ItemDropWithConditionRule(5091, 500, 1, 1, new Conditions.DontStarveIsUp()), 6, 7, 8, 9, 94, 81, 101, 173, 181, 239, 240, 174, 183, 242, 241, 268, 182, 98, 99, 100);
         RegisterToMultipleNPCs(new ItemDropWithConditionRule(5091, 1500, 1, 1, new Conditions.DontStarveIsNotUp()), 6, 7, 8, 9, 94, 81, 101, 173, 181, 239, 240, 174, 183, 242, 241, 268, 182, 98, 99, 100);
         RegisterToMultipleNPCs(new DropBasedOnExpertMode(ItemDropRule.Common(215, 50), ItemDropRule.WithRerolls(215, 1, 50)), 10, 11, 12, 95, 96, 97);
         RegisterToMultipleNPCs(ItemDropRule.Common(243, 75), 47, 464);
         RegisterToMultipleNPCs(ItemDropRule.OneFromOptions(50, 3757, 3758, 3759), 168, 470);
         RegisterToNPC(533, ItemDropRule.Common(3795, 40)).OnFailedRoll(ItemDropRule.Common(3770, 30));
         int[] npcNetIds17 = new int[3] { 63, 103, 64 };
         RegisterToMultipleNPCs(ItemDropRule.Common(1303, 100), npcNetIds17);
         RegisterToMultipleNPCs(ItemDropRule.Common(282, 1, 1, 4), npcNetIds17);
         RegisterToMultipleNPCs(ItemDropRule.Common(282, 1, 1, 4), 223);
         RegisterToMultipleNPCs(ItemDropRule.Common(282, 1, 1, 4), 224);
         RegisterToNPC(63, ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4649, 50));
         RegisterToNPC(64, ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4650, 50));
         RegisterToNPC(481, ItemDropRule.Common(3094, 2, 40, 80));
         RegisterToNPC(481, ItemDropRule.OneFromOptions(7, 3187, 3188, 3189));
         RegisterToNPC(481, ItemDropRule.Common(4463, 20));
         int[] npcNetIds18 = new int[13]
         {
             21, 167, 201, 202, 481, 203, 322, 323, 324, 449,
             450, 451, 452
         };
         RegisterToMultipleNPCs(ItemDropRule.Common(118, 25), npcNetIds18);
         RegisterToNPC(44, ItemDropRule.Common(118, 25)).OnFailedRoll(ItemDropRule.OneFromOptions(4, 410, 411)).OnFailedRoll(ItemDropRule.Common(166, 1, 1, 3));
         RegisterToNPC(45, ItemDropRule.Common(238));
         RegisterToNPC(23, ItemDropRule.Common(116, 50));
         RegisterToNPC(24, ItemDropRule.Common(244, 250));
         int[] npcNetIds19 = new int[6] { 31, 32, 34, 294, 295, 296 };
         RegisterToMultipleNPCs(ItemDropRule.Common(932, 250), npcNetIds19).OnFailedRoll(ItemDropRule.Common(3095, 100)).OnFailedRoll(ItemDropRule.Common(327, 65)).OnFailedRoll(ItemDropRule.ByCondition(new Conditions.NotExpert(), 154, 1, 1, 3));
         RegisterToMultipleNPCs(ItemDropRule.ByCondition(new Conditions.IsExpert(), 154, 1, 2, 6), npcNetIds19);
         int[] npcNetIds20 = new int[5] { 26, 27, 28, 29, 111 };
         RegisterToMultipleNPCs(ItemDropRule.Common(160, 200), npcNetIds20).OnFailedRoll(ItemDropRule.Common(161, 2, 1, 5));
         RegisterToNPC(175, ItemDropRule.Common(1265, 100));
         RegisterToNPC(175, ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4675, 25));
         RegisterToMultipleNPCs(new DropBasedOnExpertMode(new CommonDrop(209, 3, 1, 1, 2), ItemDropRule.Common(209)), 42, 231, 232, 233, 234, 235);
         RegisterToNPC(176, ItemDropRule.Common(209, 6));
         RegisterToNPC(177, new ItemDropWithConditionRule(5089, 100, 1, 1, new Conditions.DontStarveIsNotUp()));
         RegisterToNPC(177, new ItemDropWithConditionRule(5089, 40, 1, 1, new Conditions.DontStarveIsUp()));
         RegisterToNPC(204, ItemDropRule.NormalvsExpert(209, 2, 1));
         RegisterToNPC(43, ItemDropRule.NormalvsExpert(210, 2, 1));
         RegisterToNPC(43, ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4648, 25));
         RegisterToNPC(39, ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4610, 15));
         RegisterToNPC(65, ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4651, 25));
         RegisterToNPC(65, ItemDropRule.Common(268, 20)).OnFailedRoll(ItemDropRule.Common(319));
         RegisterToNPC(48, ItemDropRule.NotScalingWithLuck(320, 2));
         RegisterToNPC(541, ItemDropRule.Common(3783));
         RegisterToMultipleNPCs(ItemDropRule.Common(319, 8), 542, 543, 544, 545);
         RegisterToMultipleNPCs(ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4669, 25), 542, 543, 544, 545);
         RegisterToNPC(543, ItemDropRule.Common(527, 25));
         RegisterToNPC(544, ItemDropRule.Common(527, 25));
         RegisterToNPC(545, ItemDropRule.Common(528, 25));
         RegisterToNPC(47, ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4670, 25));
         RegisterToNPC(464, ItemDropRule.ByCondition(new Conditions.WindyEnoughForKiteDrops(), 4671, 25));
         RegisterToNPC(268, ItemDropRule.Common(1332, 1, 2, 5));
         RegisterToNPC(631, ItemDropRule.Common(3, 1, 10, 20));
         RegisterToNPC(631, ItemDropRule.Common(4761, 10));
         int[] npcNetIds21 = new int[1] { 594 };
         LeadingConditionRule leadingConditionRule = new LeadingConditionRule(new Conditions.NeverTrue());
         int[] options = new int[0];
         IItemDropRule rule = leadingConditionRule.OnSuccess(ItemDropRule.OneFromOptions(8, options));
         int chanceDenominator = 9;
         rule.OnSuccess(new CommonDrop(4367, chanceDenominator));
         rule.OnSuccess(new CommonDrop(4368, chanceDenominator));
         rule.OnSuccess(new CommonDrop(4369, chanceDenominator));
         rule.OnSuccess(new CommonDrop(4370, chanceDenominator));
         rule.OnSuccess(new CommonDrop(4371, chanceDenominator));
         rule.OnSuccess(new CommonDrop(4612, chanceDenominator));
         rule.OnSuccess(new CommonDrop(4674, chanceDenominator));
         rule.OnSuccess(new CommonDrop(4343, chanceDenominator, 2, 5));
         rule.OnSuccess(new CommonDrop(4344, chanceDenominator, 2, 5));
         RegisterToMultipleNPCs(leadingConditionRule, npcNetIds21);
     }
References ItemDropRule.ByCondition(), ItemDropRule.Common(), ItemDropRule.NormalvsExpert(), ItemDropRule.NormalvsExpertOneFromOptions(), ItemDropRule.NotScalingWithLuck(), ItemDropRule.OneFromOptions(), RegisterToMultipleNPCs(), RegisterToNPC(), RemoveFromMultipleNPCs(), and ItemDropRule.WithRerolls().
Referenced by Populate().