Terraria: ItemDropDatabase.RegisterBoss_FrostMoon
RegisterBoss_FrostMoon()
void ItemDropDatabase.RegisterBoss_FrostMoon () inline private
     {
         Conditions.FrostMoonDropGatingChance condition = new Conditions.FrostMoonDropGatingChance();
         Conditions.FrostMoonDropGateForTrophies condition2 = new Conditions.FrostMoonDropGateForTrophies();
         Conditions.FromCertainWaveAndAbove condition3 = new Conditions.FromCertainWaveAndAbove(15);
         IItemDropRule rule = RegisterToNPC(344, new LeadingConditionRule(condition));
         rule.OnSuccess(ItemDropRule.ByCondition(condition2, 1962));
         rule.OnSuccess(ItemDropRule.Common(1871, 15)).OnFailedRoll(ItemDropRule.OneFromOptions(1, 1916, 1928, 1930));
         rule.OnSuccess(ItemDropRule.MasterModeCommonDrop(4944));
         rule.OnSuccess(ItemDropRule.MasterModeDropOnAllPlayers(4813, _masterModeDropRng));
         IItemDropRule rule2 = RegisterToNPC(345, new LeadingConditionRule(condition));
         rule2.OnSuccess(ItemDropRule.ByCondition(condition2, 1960));
         rule2.OnSuccess(ItemDropRule.ByCondition(condition3, 1914, 15));
         rule2.OnSuccess(ItemDropRule.Common(1959, 15)).OnFailedRoll(ItemDropRule.OneFromOptions(1, 1931, 1946, 1947));
         rule2.OnSuccess(ItemDropRule.MasterModeCommonDrop(4943));
         rule2.OnSuccess(ItemDropRule.MasterModeDropOnAllPlayers(4814, _masterModeDropRng));
         IItemDropRule rule3 = RegisterToNPC(346, new LeadingConditionRule(condition));
         rule3.OnSuccess(ItemDropRule.ByCondition(condition2, 1961));
         rule3.OnSuccess(ItemDropRule.OneFromOptions(1, 1910, 1929));
         rule3.OnSuccess(ItemDropRule.MasterModeCommonDrop(4945));
         rule3.OnSuccess(ItemDropRule.MasterModeDropOnAllPlayers(4794, _masterModeDropRng));
         int[] npcNetIds = new int[3] { 338, 339, 340 };
         RegisterToMultipleNPCs(ItemDropRule.OneFromOptions(200, 1943, 1944, 1945), npcNetIds);
         RegisterToNPC(341, ItemDropRule.ByCondition(new Conditions.IsChristmas(), 1869));
     }
References _masterModeDropRng, ItemDropRule.ByCondition(), ItemDropRule.Common(), ItemDropRule.MasterModeCommonDrop(), ItemDropRule.MasterModeDropOnAllPlayers(), ItemDropRule.OneFromOptions(), RegisterToMultipleNPCs(), and RegisterToNPC().
Referenced by RegisterBosses().