Terraria: ItemDropDatabase.Populate
Populate()
void ItemDropDatabase.Populate () inline
     {
         PrepareNPCNetIDsByTypeDictionary();
         RegisterGlobalRules();
         RegisterFoodDrops();
         RegisterWeirdRules();
         RegisterTownNPCDrops();
         RegisterDD2EventDrops();
         RegisterMiscDrops();
         RegisterHardmodeFeathers();
         RegisterYoyos();
         RegisterStatusImmunityItems();
         RegisterPirateDrops();
         RegisterBloodMoonFishingEnemies();
         RegisterMartianDrops();
         RegisterBossTrophies();
         RegisterBosses();
         RegisterHardmodeDungeonDrops();
         RegisterMimic();
         RegisterEclipse();
         RegisterBloodMoonFishing();
         TrimDuplicateRulesForNegativeIDs();
     }
References PrepareNPCNetIDsByTypeDictionary(), RegisterBloodMoonFishing(), RegisterBloodMoonFishingEnemies(), RegisterBosses(), RegisterBossTrophies(), RegisterDD2EventDrops(), RegisterEclipse(), RegisterFoodDrops(), RegisterGlobalRules(), RegisterHardmodeDungeonDrops(), RegisterHardmodeFeathers(), RegisterMartianDrops(), RegisterMimic(), RegisterMiscDrops(), RegisterPirateDrops(), RegisterStatusImmunityItems(), RegisterTownNPCDrops(), RegisterWeirdRules(), RegisterYoyos(), and TrimDuplicateRulesForNegativeIDs().
Referenced by Main.Initialize_AlmostEverything().