Terraria: ItemDropDatabase.RegisterDD2EventDrops
RegisterDD2EventDrops()
void ItemDropDatabase.RegisterDD2EventDrops () inline private
     {
         new Conditions.IsExpert();
         RegisterToNPC(576, new CommonDropNotScalingWithLuck(3865, 7, 1, 1));
         RegisterToNPC(576, ItemDropRule.NormalvsExpertOneFromOptionsNotScalingWithLuck(3, 2, 3811, 3812));
         RegisterToNPC(576, ItemDropRule.NormalvsExpertOneFromOptionsNotScalingWithLuck(2, 1, 3852, 3854, 3823, 3835, 3836));
         RegisterToNPC(576, ItemDropRule.NormalvsExpertNotScalingWithLuck(3856, 5, 4));
         RegisterToNPC(577, new CommonDropNotScalingWithLuck(3865, 14, 1, 1));
         RegisterToNPC(577, ItemDropRule.MasterModeCommonDrop(4947));
         RegisterToNPC(577, ItemDropRule.MasterModeDropOnAllPlayers(4816, _masterModeDropRng));
         RegisterToNPC(577, ItemDropRule.OneFromOptionsNotScalingWithLuck(6, 3811, 3812));
         RegisterToNPC(577, ItemDropRule.OneFromOptionsNotScalingWithLuck(4, 3852, 3854, 3823, 3835, 3836));
         RegisterToNPC(577, ItemDropRule.Common(3856, 10));
         RegisterToNPC(564, ItemDropRule.Common(3864, 7));
         RegisterToNPC(564, ItemDropRule.MasterModeDropOnAllPlayers(4796, _masterModeDropRng));
         RegisterToNPC(564, ItemDropRule.NormalvsExpertOneFromOptionsNotScalingWithLuck(2, 1, 3810, 3809));
         RegisterToNPC(564, new DropBasedOnExpertMode(ItemDropRule.NotScalingWithLuck(3814, 2), ItemDropRule.NotScalingWithLuck(3814)));
         RegisterToNPC(564, new DropBasedOnExpertMode(ItemDropRule.NotScalingWithLuck(3815, 2, 4, 4), ItemDropRule.NotScalingWithLuck(3815, 1, 4, 4)));
         RegisterToNPC(564, ItemDropRule.NormalvsExpertOneFromOptionsNotScalingWithLuck(3, 2, 3857, 3855));
         RegisterToNPC(565, ItemDropRule.Common(3864, 14));
         RegisterToNPC(565, ItemDropRule.MasterModeCommonDrop(4946));
         RegisterToNPC(565, ItemDropRule.MasterModeDropOnAllPlayers(4796, _masterModeDropRng));
         RegisterToNPC(565, ItemDropRule.OneFromOptionsNotScalingWithLuck(6, 3810, 3809));
         RegisterToNPC(565, new DropBasedOnExpertMode(ItemDropRule.NotScalingWithLuck(3814, 8), ItemDropRule.NotScalingWithLuck(3814, 4)));
         RegisterToNPC(565, new DropBasedOnExpertMode(ItemDropRule.NotScalingWithLuck(3815, 8, 4, 4), ItemDropRule.NotScalingWithLuck(3815, 4, 4, 4)));
         RegisterToNPC(565, ItemDropRule.OneFromOptionsNotScalingWithLuck(6, 3857, 3855));
     }
References _masterModeDropRng, ItemDropRule.Common(), ItemDropRule.MasterModeCommonDrop(), ItemDropRule.MasterModeDropOnAllPlayers(), ItemDropRule.NormalvsExpertNotScalingWithLuck(), ItemDropRule.NormalvsExpertOneFromOptionsNotScalingWithLuck(), ItemDropRule.NotScalingWithLuck(), ItemDropRule.OneFromOptionsNotScalingWithLuck(), and RegisterToNPC().
Referenced by Populate().