Terraria: ItemDropDatabase.RegisterHardmodeDungeonDrops
RegisterHardmodeDungeonDrops()
void ItemDropDatabase.RegisterHardmodeDungeonDrops () inline private
     {
         int[] npcNetIds = new int[12]
         {
             269, 270, 271, 272, 273, 274, 275, 276, 277, 278,
             279, 280
         };
         RegisterToNPC(290, ItemDropRule.ExpertGetsRerolls(1513, 15, 1));
         RegisterToNPC(290, ItemDropRule.ExpertGetsRerolls(938, 10, 1));
         RegisterToNPC(287, ItemDropRule.ExpertGetsRerolls(977, 12, 1));
         RegisterToNPC(287, ItemDropRule.ExpertGetsRerolls(963, 12, 1));
         RegisterToNPC(291, ItemDropRule.ExpertGetsRerolls(1300, 12, 1));
         RegisterToNPC(291, ItemDropRule.ExpertGetsRerolls(1254, 12, 1));
         RegisterToNPC(292, ItemDropRule.ExpertGetsRerolls(1514, 12, 1));
         RegisterToNPC(292, ItemDropRule.ExpertGetsRerolls(679, 12, 1));
         RegisterToNPC(293, ItemDropRule.ExpertGetsRerolls(759, 18, 1));
         RegisterToNPC(289, ItemDropRule.ExpertGetsRerolls(4789, 25, 1));
         RegisterToMultipleNPCs(ItemDropRule.ExpertGetsRerolls(1446, 20, 1), 281, 282);
         RegisterToMultipleNPCs(ItemDropRule.ExpertGetsRerolls(1444, 20, 1), 283, 284);
         RegisterToMultipleNPCs(ItemDropRule.ExpertGetsRerolls(1445, 20, 1), 285, 286);
         RegisterToMultipleNPCs(ItemDropRule.ExpertGetsRerolls(1183, 400, 1), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.ExpertGetsRerolls(1266, 300, 1), npcNetIds);
         RegisterToMultipleNPCsNotRemixSeed(ItemDropRule.ExpertGetsRerolls(671, 200, 1), npcNetIds);
         RegisterToMultipleNPCsRemixSeed(ItemDropRule.ExpertGetsRerolls(2273, 200, 1), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.ExpertGetsRerolls(4679, 200, 1), npcNetIds);
         RegisterToNPC(288, ItemDropRule.Common(1508, 1, 1, 2));
     }
References ItemDropRule.Common(), ItemDropRule.ExpertGetsRerolls(), RegisterToMultipleNPCs(), RegisterToMultipleNPCsNotRemixSeed(), RegisterToMultipleNPCsRemixSeed(), and RegisterToNPC().
Referenced by Populate().