Terraria: System.Reflection.Metadata.Ecma335.GenericParamTableReader.BinarySearchTag
BinarySearchTag()
int System.Reflection.Metadata.Ecma335.GenericParamTableReader.BinarySearchTag (uint searchCodedTag, ref ushort genericParamCount) inline private
Definition at line 82 of file GenericParamTableReader.cs.
    {
        Block.BinarySearchReferenceRange(NumberOfRows, RowSize, _OwnerOffset, searchCodedTag, _IsTypeOrMethodDefRefSizeSmall, out var startRowNumber, out var endRowNumber);
        if (startRowNumber == -1)
        {
            genericParamCount = 0;
            return 0;
        }
        genericParamCount = (ushort)(endRowNumber - startRowNumber + 1);
        return startRowNumber + 1;
    }
References System.Reflection.Metadata.Ecma335.GenericParamTableReader._IsTypeOrMethodDefRefSizeSmall, System.Reflection.Metadata.Ecma335.GenericParamTableReader._OwnerOffset, System.Reflection.Internal.MemoryBlock.BinarySearchReferenceRange(), System.Reflection.Metadata.Ecma335.GenericParamTableReader.Block, System.Reflection.Metadata.Ecma335.GenericParamTableReader.NumberOfRows, and System.Reflection.Metadata.Ecma335.GenericParamTableReader.RowSize.
Referenced by System.Reflection.Metadata.Ecma335.GenericParamTableReader.FindGenericParametersForMethod(), and System.Reflection.Metadata.Ecma335.GenericParamTableReader.FindGenericParametersForType().