Terraria: System.Reflection.Metadata.Ecma335.GenericParamTableReader.GenericParamTableReader
GenericParamTableReader()
System.Reflection.Metadata.Ecma335.GenericParamTableReader.GenericParamTableReader (int numberOfRows, bool declaredSorted, int typeOrMethodDefRefSize, int stringHeapRefSize, MemoryBlock containingBlock, int containingBlockOffset) inline package
Definition at line 25 of file GenericParamTableReader.cs.
    {
        NumberOfRows = numberOfRows;
        _IsTypeOrMethodDefRefSizeSmall = typeOrMethodDefRefSize == 2;
        _IsStringHeapRefSizeSmall = stringHeapRefSize == 2;
        _NumberOffset = 0;
        _FlagsOffset = _NumberOffset + 2;
        _OwnerOffset = _FlagsOffset + 2;
        _NameOffset = _OwnerOffset + typeOrMethodDefRefSize;
        RowSize = _NameOffset + stringHeapRefSize;
        Block = containingBlock.GetMemoryBlockAt(containingBlockOffset, RowSize * numberOfRows);
        if (!declaredSorted && !CheckSorted())
        {
            Throw.TableNotSorted(TableIndex.GenericParam);
        }
    }
References System.Reflection.Metadata.Ecma335.GenericParamTableReader._FlagsOffset, System.Reflection.Metadata.Ecma335.GenericParamTableReader._IsStringHeapRefSizeSmall, System.Reflection.Metadata.Ecma335.GenericParamTableReader._IsTypeOrMethodDefRefSizeSmall, System.Reflection.Metadata.Ecma335.GenericParamTableReader._NameOffset, System.Reflection.Metadata.Ecma335.GenericParamTableReader._NumberOffset, System.Reflection.Metadata.Ecma335.GenericParamTableReader._OwnerOffset, System.Reflection.Metadata.Ecma335.GenericParamTableReader.Block, System.Reflection.Metadata.Ecma335.GenericParamTableReader.CheckSorted(), System.Reflection.Internal.MemoryBlock.GetMemoryBlockAt(), System.Reflection.Metadata.Ecma335.GenericParamTableReader.NumberOfRows, System.Reflection.Metadata.Ecma335.GenericParamTableReader.RowSize, and System.Reflection.Throw.TableNotSorted().