Terraria: System.Text.Encodings.Web.OptimizedInboxTextEncoder.Encode
Encode()
OperationStatus System.Text.Encodings.Web.OptimizedInboxTextEncoder.Encode (ReadOnlySpan< char > source, Span< char > destination, out int charsConsumed, out int charsWritten, bool isFinalBlock) inline
Definition at line 161 of file OptimizedInboxTextEncoder.cs.
    {
        _AssertThisNotNull();
        int num = 0;
        int num2 = 0;
        OperationStatus result2;
        while (true)
        {
            int num3;
            Rune result;
            if (SpanUtility.IsValidIndex(source, num))
            {
                char c = source[num];
                if (_asciiPreescapedData.TryGetPreescapedData(c, out var preescapedData))
                {
                    if (SpanUtility.IsValidIndex(destination, num2))
                    {
                        destination[num2] = (char)(byte)preescapedData;
                        if (((int)preescapedData & 0xFF00) == 0)
{
                            num2++;
                            num++;
                            continue;
                        }
                        preescapedData >>= 8;
                        num3 = num2 + 1;
                        while (SpanUtility.IsValidIndex(destination, num3))
{
                            destination[num3++] = (char)(byte)preescapedData;
                            if ((byte)(preescapedData >>= 8) != 0)
{
                                continue;
                            }
                            goto IL_0091;
                        }
                    }
                    goto IL_0148;
                }
                if (Rune.TryCreate(c, out result))
                {
                    goto IL_00e1;
                }
                int index = num + 1;
                if (SpanUtility.IsValidIndex(source, index))
                {
                    if (Rune.TryCreate(c, source[index], out result))
                    {
                        goto IL_00e1;
                    }
                }
                else if (!isFinalBlock && char.IsHighSurrogate(c))
                {
                    result2 = OperationStatus.NeedMoreData;
                    break;
                }
                result = Rune.ReplacementChar;
                goto IL_010d;
            }
            result2 = OperationStatus.Done;
            break;
            IL_0148:
            result2 = OperationStatus.DestinationTooSmall;
            break;
            IL_0091:
            num2 = num3;
            num++;
            continue;
            IL_010d:
            int num4 = _scalarEscaper.EncodeUtf16(result, destination.Slice(num2));
            if (num4 >= 0)
            {
                num2 += num4;
                num += result.Utf16SequenceLength;
                continue;
            }
            goto IL_0148;
            IL_00e1:
            if (!IsScalarValueAllowed(result))
            {
                goto IL_010d;
            }
            if (result.TryEncodeToUtf16(destination.Slice(num2), out var charsWritten2))
            {
                num2 += charsWritten2;
                num += charsWritten2;
                continue;
            }
            goto IL_0148;
        }
        charsConsumed = num;
        charsWritten = num2;
        return result2;
    }
References System.Text.Encodings.Web.OptimizedInboxTextEncoder._asciiPreescapedData, System.Text.Encodings.Web.OptimizedInboxTextEncoder._AssertThisNotNull(), System.Text.Encodings.Web.OptimizedInboxTextEncoder._scalarEscaper, System.destination, System.Text.Encodings.Web.ScalarEscaperBase.EncodeUtf16(), System.index, System.Text.Encodings.Web.OptimizedInboxTextEncoder.IsScalarValueAllowed(), System.Text.Rune.ReplacementChar, System.source, System.Text.Rune.TryCreate(), System.Text.Rune.TryEncodeToUtf16(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.AsciiPreescapedData.TryGetPreescapedData(), and System.Text.Rune.Utf16SequenceLength.
Referenced by System.Text.Encodings.Web.DefaultHtmlEncoder.EncodeCore(), System.Text.Encodings.Web.DefaultJavaScriptEncoder.EncodeCore(), and System.Text.Encodings.Web.DefaultUrlEncoder.EncodeCore().