Terraria: System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncode
GetIndexOfFirstCharToEncode()
unsafe int System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncode (ReadOnlySpan< char > data) inline
Definition at line 368 of file OptimizedInboxTextEncoder.cs.
    {
        fixed (char* ptr = data)
        {
            nuint num = (uint)data.Length;
            nuint num2 = 0u;
            if (Ssse3.IsSupported)
            {
                num2 = GetIndexOfFirstCharToEncodeSsse3(ptr, num);
            }
            else if (AdvSimd.Arm64.IsSupported && BitConverter.IsLittleEndian)
            {
                num2 = GetIndexOfFirstCharToEncodeAdvSimd64(ptr, num);
            }
            if (num2 < num)
            {
                _AssertThisNotNull();
                nint num3 = 0;
                while (true)
                {
                    if (num - num2 >= 8)
                    {
                        num3 = -1;
                        if (_allowedBmpCodePoints.IsCharAllowed(ptr[(nuint)((nint)num2 + ++num3)]) && _allowedBmpCodePoints.IsCharAllowed(ptr[(nuint)((nint)num2 + ++num3)]) && _allowedBmpCodePoints.IsCharAllowed(ptr[(nuint)((nint)num2 + ++num3)]) && _allowedBmpCodePoints.IsCharAllowed(ptr[(nuint)((nint)num2 + ++num3)]) && _allowedBmpCodePoints.IsCharAllowed(ptr[(nuint)((nint)num2 + ++num3)]) && _allowedBmpCodePoints.IsCharAllowed(ptr[(nuint)((nint)num2 + ++num3)]) && _allowedBmpCodePoints.IsCharAllowed(ptr[(nuint)((nint)num2 + ++num3)]) && _allowedBmpCodePoints.IsCharAllowed(ptr[(nuint)((nint)num2 + ++num3)]))
{
                            num2 += 8;
                            continue;
                        }
                        num2 += (nuint)num3;
                        break;
                    }
                    for (; num2 < num && _allowedBmpCodePoints.IsCharAllowed(ptr[num2]); num2++)
                    {
                    }
                    break;
                }
            }
            int num4 = (int)num2;
            if (num4 == (int)num)
            {
                num4 = -1;
            }
            return num4;
        }
    }
References System.Text.Encodings.Web.OptimizedInboxTextEncoder._allowedBmpCodePoints, System.Text.Encodings.Web.OptimizedInboxTextEncoder._AssertThisNotNull(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeAdvSimd64(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeSsse3(), System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.IsCharAllowed(), System.BitConverter.IsLittleEndian, System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.IsSupported, System.Runtime.Intrinsics.X86.Ssse3.IsSupported, and System.ReadOnlySpan< T >.Length.
Referenced by System.Text.Encodings.Web.OptimizedInboxTextEncoder.FindFirstCharacterToEncode(), System.Text.Encodings.Web.DefaultHtmlEncoder.FindFirstCharacterToEncode(), System.Text.Encodings.Web.DefaultJavaScriptEncoder.FindFirstCharacterToEncode(), and System.Text.Encodings.Web.DefaultUrlEncoder.FindFirstCharacterToEncode().