Terraria: System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3
GetIndexOfFirstByteToEncodeSsse3()
unsafe nuint System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3 (byte * pData, nuint lengthInBytes) inline private
Definition at line 426 of file OptimizedInboxTextEncoder.cs.
    {
        Vector128<byte> zero = Vector128<byte>.Zero;
        Vector128<byte> right = Vector128.Create((byte)7);
        Vector128<byte> value = Vector128.Create(1, 2, 4, 8, 16, 32, 64, 128, 0, 0, 0, 0, 0, 0, 0, 0);
        Vector128<byte> asVector = _allowedAsciiCodePoints.AsVector;
        nuint num = 0u;
        if (lengthInBytes < 16)
        {
            goto IL_00b3;
        }
        nuint num2 = lengthInBytes & unchecked((nuint)(-16));
        int num3;
        while (true)
        {
            Vector128<byte> vector = Sse2.LoadVector128(pData + num);
            Vector128<byte> left = Ssse3.Shuffle(asVector, vector);
            Vector128<byte> right2 = Ssse3.Shuffle(value, Sse2.And(Sse2.ShiftRightLogical(vector.AsUInt32(), 4).AsByte(), right));
            Vector128<byte> left2 = Sse2.And(left, right2);
            num3 = Sse2.MoveMask(Sse2.CompareEqual(left2, zero));
            if (((uint)num3 & 0xFFFFu) != 0)
            {
                break;
            }
            if ((num += 16) < num2)
            {
                continue;
            }
            goto IL_00b3;
        }
        goto IL_01af;
        IL_00b3:
        if ((lengthInBytes & 8) != 0)
        {
            Vector128<byte> vector2 = Sse2.LoadScalarVector128((ulong*)(pData + num)).AsByte();
            Vector128<byte> left3 = Ssse3.Shuffle(asVector, vector2);
            Vector128<byte> right3 = Ssse3.Shuffle(value, Sse2.And(Sse2.ShiftRightLogical(vector2.AsUInt32(), 4).AsByte(), right));
            Vector128<byte> left4 = Sse2.And(left3, right3);
            num3 = Sse2.MoveMask(Sse2.CompareEqual(left4, zero));
            if ((byte)num3 != 0)
            {
                goto IL_01af;
            }
            num += 8;
        }
        if ((lengthInBytes & 4) != 0)
        {
            Vector128<byte> vector3 = Sse2.LoadScalarVector128((uint*)(pData + num)).AsByte();
            Vector128<byte> left5 = Ssse3.Shuffle(asVector, vector3);
            Vector128<byte> right4 = Ssse3.Shuffle(value, Sse2.And(Sse2.ShiftRightLogical(vector3.AsUInt32(), 4).AsByte(), right));
            Vector128<byte> left6 = Sse2.And(left5, right4);
            num3 = Sse2.MoveMask(Sse2.CompareEqual(left6, zero));
            if (((uint)num3 & 0xFu) != 0)
            {
                goto IL_01af;
            }
            num += 4;
        }
        if ((lengthInBytes & 3) != 0)
        {
            while (_allowedAsciiCodePoints.IsAllowedAsciiCodePoint(pData[num]) && ++num != lengthInBytes)
            {
            }
        }
        goto IL_01ac;
        IL_01af:
        num += (uint)BitOperations.TrailingZeroCount(num3);
        goto IL_01ac;
        IL_01ac:
        return num;
    }
References System.Text.Encodings.Web.OptimizedInboxTextEncoder._allowedAsciiCodePoints, System.Runtime.Intrinsics.X86.Sse2.And(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.AllowedAsciiCodePoints.AsVector, System.Runtime.Intrinsics.X86.Sse2.CompareEqual(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.AllowedAsciiCodePoints.IsAllowedAsciiCodePoint(), System.Runtime.Intrinsics.X86.Sse2.LoadScalarVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Ssse3.Shuffle(), System.Numerics.BitOperations.TrailingZeroCount(), System.Text.Encodings.Web.value, and System.Runtime.Intrinsics.Vector128< T >.Zero.
Referenced by System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncode().