Terraria: System.Text.Encodings.Web.OptimizedInboxTextEncoder.EncodeUtf8
EncodeUtf8()
OperationStatus System.Text.Encodings.Web.OptimizedInboxTextEncoder.EncodeUtf8 (ReadOnlySpan< byte > source, Span< byte > destination, out int bytesConsumed, out int bytesWritten, bool isFinalBlock) inline
Definition at line 255 of file OptimizedInboxTextEncoder.cs.
    {
        _AssertThisNotNull();
        int num = 0;
        int num2 = 0;
        OperationStatus result2;
        while (true)
        {
            int num3;
            if (SpanUtility.IsValidIndex(source, num))
            {
                uint codePoint = source[num];
                if (_asciiPreescapedData.TryGetPreescapedData(codePoint, out var preescapedData))
                {
                    if (SpanUtility.TryWriteUInt64LittleEndian(destination, num2, preescapedData))
                    {
                        num2 += (int)(preescapedData >> 56);
                        num++;
                        continue;
                    }
                    num3 = num2;
                    while (SpanUtility.IsValidIndex(destination, num3))
                    {
                        destination[num3++] = (byte)preescapedData;
                        if ((byte)(preescapedData >>= 8) != 0)
{
                            continue;
                        }
                        goto IL_0076;
                    }
                }
                else
                {
                    Rune result;
                    int bytesConsumed2;
                    OperationStatus operationStatus = Rune.DecodeFromUtf8(source.Slice(num), out result, out bytesConsumed2);
                    if (operationStatus != 0)
                    {
                        if (!isFinalBlock && operationStatus == OperationStatus.NeedMoreData)
{
                            result2 = OperationStatus.NeedMoreData;
                            break;
                        }
                    }
                    else if (IsScalarValueAllowed(result))
                    {
                        if (result.TryEncodeToUtf8(destination.Slice(num2), out var bytesWritten2))
{
                            num2 += bytesWritten2;
                            num += bytesWritten2;
                            continue;
                        }
                        goto IL_0103;
                    }
                    int num4 = _scalarEscaper.EncodeUtf8(result, destination.Slice(num2));
                    if (num4 >= 0)
                    {
                        num2 += num4;
                        num += bytesConsumed2;
                        continue;
                    }
                }
                goto IL_0103;
            }
            result2 = OperationStatus.Done;
            break;
            IL_0076:
            num2 = num3;
            num++;
            continue;
            IL_0103:
            result2 = OperationStatus.DestinationTooSmall;
            break;
        }
        bytesConsumed = num;
        bytesWritten = num2;
        return result2;
    }
References System.Text.Encodings.Web.OptimizedInboxTextEncoder._asciiPreescapedData, System.Text.Encodings.Web.OptimizedInboxTextEncoder._AssertThisNotNull(), System.Text.Encodings.Web.OptimizedInboxTextEncoder._scalarEscaper, System.codePoint, System.Text.Rune.DecodeFromUtf8(), System.destination, System.Text.Encodings.Web.ScalarEscaperBase.EncodeUtf8(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.IsScalarValueAllowed(), System.source, System.Text.Rune.TryEncodeToUtf8(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.AsciiPreescapedData.TryGetPreescapedData(), and System.Text.Encodings.Web.SpanUtility.TryWriteUInt64LittleEndian().
Referenced by System.Text.Encodings.Web.DefaultHtmlEncoder.EncodeUtf8Core(), System.Text.Encodings.Web.DefaultJavaScriptEncoder.EncodeUtf8Core(), and System.Text.Encodings.Web.DefaultUrlEncoder.EncodeUtf8Core().