Terraria: System.Text.Encodings.Web.OptimizedInboxTextEncoder.IsScalarValueAllowed
IsScalarValueAllowed()
bool System.Text.Encodings.Web.OptimizedInboxTextEncoder.IsScalarValueAllowed (Rune value) inline
Definition at line 415 of file OptimizedInboxTextEncoder.cs.
    {
        return _allowedBmpCodePoints.IsCodePointAllowed((uint)value.Value);
    }
References System.Text.Encodings.Web.OptimizedInboxTextEncoder._allowedBmpCodePoints, System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.IsCodePointAllowed(), and System.Text.Encodings.Web.value.
Referenced by System.Text.Encodings.Web.OptimizedInboxTextEncoder.Encode(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.EncodeUtf8(), System.Text.Encodings.Web.DefaultHtmlEncoder.WillEncode(), System.Text.Encodings.Web.DefaultJavaScriptEncoder.WillEncode(), and System.Text.Encodings.Web.DefaultUrlEncoder.WillEncode().