Terraria: System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeAdvSimd64
GetIndexOfFirstCharToEncodeAdvSimd64()
unsafe nuint System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeAdvSimd64 (char * pData, nuint lengthInChars) inline private
Definition at line 644 of file OptimizedInboxTextEncoder.cs.
    {
        Vector128<byte> right = Vector128.Create((byte)15);
        Vector128<byte> table = Vector128.Create(1, 2, 4, 8, 16, 32, 64, 128, 0, 0, 0, 0, 0, 0, 0, 0);
        Vector128<byte> right2 = Vector128.Create((ushort)61455).AsByte();
        Vector128<byte> asVector = _allowedAsciiCodePoints.AsVector;
        nuint num = 0u;
        if (lengthInChars < 16)
        {
            goto IL_00f0;
        }
        nuint num2 = lengthInChars & unchecked((nuint)(-16));
        ulong num3;
        while (true)
        {
            Vector128<byte> vector = AdvSimd.ExtractNarrowingSaturateUnsignedUpper(AdvSimd.ExtractNarrowingSaturateUnsignedLower(AdvSimd.LoadVector128((short*)(pData + num))), AdvSimd.LoadVector128((short*)(pData + 8 + num)));
            Vector128<byte> left = AdvSimd.Arm64.VectorTableLookup(asVector, AdvSimd.And(vector, right));
            Vector128<byte> right3 = AdvSimd.Arm64.VectorTableLookup(table, AdvSimd.ShiftRightArithmetic(vector.AsSByte(), 4).AsByte());
            Vector128<byte> left2 = AdvSimd.CompareTest(left, right3);
            Vector128<byte> vector2 = AdvSimd.And(left2, right2);
            num3 = AdvSimd.Arm64.AddPairwise(vector2, vector2).AsUInt64().ToScalar();
            if (num3 != ulong.MaxValue)
            {
                break;
            }
            if ((num += 16) < num2)
            {
                continue;
            }
            goto IL_00f0;
        }
        num += (uint)(BitOperations.TrailingZeroCount(~num3) >>> 2);
        goto IL_0205;
        IL_0205:
        return num;
        IL_00f0:
        if ((lengthInChars & 8) != 0)
        {
            Vector128<byte> vector3 = AdvSimd.ExtractNarrowingSaturateUnsignedLower(AdvSimd.LoadVector128((short*)(pData + num))).AsByte().ToVector128Unsafe();
            Vector128<byte> left3 = AdvSimd.Arm64.VectorTableLookup(asVector, AdvSimd.And(vector3, right));
            Vector128<byte> right4 = AdvSimd.Arm64.VectorTableLookup(table, AdvSimd.ShiftRightArithmetic(vector3.AsSByte(), 4).AsByte());
            Vector128<byte> vector4 = AdvSimd.CompareTest(left3, right4);
            num3 = vector4.AsUInt64().ToScalar();
            if (num3 != ulong.MaxValue)
            {
                goto IL_021a;
            }
            num += 8;
        }
        if ((lengthInChars & 4) != 0)
        {
            Vector128<byte> vector5 = AdvSimd.ExtractNarrowingSaturateUnsignedLower(AdvSimd.LoadVector64((short*)(pData + num)).ToVector128Unsafe()).ToVector128Unsafe();
            Vector128<byte> left4 = AdvSimd.Arm64.VectorTableLookup(asVector, AdvSimd.And(vector5, right));
            Vector128<byte> right5 = AdvSimd.Arm64.VectorTableLookup(table, AdvSimd.ShiftRightArithmetic(vector5.AsSByte(), 4).AsByte());
            Vector128<byte> vector6 = AdvSimd.CompareTest(left4, right5);
            num3 = vector6.AsUInt32().ToScalar();
            if (num3 != uint.MaxValue)
            {
                goto IL_021a;
            }
            num += 4;
        }
        if ((lengthInChars & 3) != 0)
        {
            while (_allowedAsciiCodePoints.IsAllowedAsciiCodePoint(pData[num]) && ++num != lengthInChars)
            {
            }
        }
        goto IL_0205;
        IL_021a:
        num += (uint)(BitOperations.TrailingZeroCount(~num3) >>> 3);
        goto IL_0205;
    }
References System.Text.Encodings.Web.OptimizedInboxTextEncoder._allowedAsciiCodePoints, System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.AddPairwise(), System.Runtime.Intrinsics.Arm.AdvSimd.And(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.AllowedAsciiCodePoints.AsVector, System.Runtime.Intrinsics.Arm.AdvSimd.CompareTest(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Arm.AdvSimd.ExtractNarrowingSaturateUnsignedLower(), System.Runtime.Intrinsics.Arm.AdvSimd.ExtractNarrowingSaturateUnsignedUpper(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.AllowedAsciiCodePoints.IsAllowedAsciiCodePoint(), System.Runtime.Intrinsics.Arm.AdvSimd.LoadVector128(), System.Runtime.Intrinsics.Arm.AdvSimd.LoadVector64(), System.Runtime.Intrinsics.Arm.AdvSimd.ShiftRightArithmetic(), System.Numerics.BitOperations.TrailingZeroCount(), and System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.VectorTableLookup().
Referenced by System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncode().