Terraria: System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncode
GetIndexOfFirstByteToEncode()
unsafe int System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncode (ReadOnlySpan< byte > data) inline
Definition at line 334 of file OptimizedInboxTextEncoder.cs.
    {
        int length = data.Length;
        if (Ssse3.IsSupported || (AdvSimd.Arm64.IsSupported && BitConverter.IsLittleEndian))
        {
            int num;
            fixed (byte* pData = data)
            {
                UIntPtr uIntPtr = ((!AdvSimd.Arm64.IsSupported || !BitConverter.IsLittleEndian) ? GetIndexOfFirstByteToEncodeSsse3(pData, (uint)length) : GetIndexOfFirstByteToEncodeAdvSimd64(pData, (uint)length));
                num = (int)(nuint)uIntPtr;
            }
            if (!SpanUtility.IsValidIndex(data, num))
            {
                return -1;
            }
            if (System.Text.UnicodeUtility.IsAsciiCodePoint(data[num]))
            {
                return num;
            }
            data = data.Slice(num);
        }
        Rune result;
        int bytesConsumed;
        while (!data.IsEmpty && Rune.DecodeFromUtf8(data, out result, out bytesConsumed) == OperationStatus.Done && bytesConsumed < 4 && _allowedBmpCodePoints.IsCharAllowed((char)result.Value))
        {
            data = data.Slice(bytesConsumed);
        }
        if (!data.IsEmpty)
        {
            return length - data.Length;
        }
        return -1;
    }
References System.Text.Encodings.Web.OptimizedInboxTextEncoder._allowedBmpCodePoints, System.Text.Rune.DecodeFromUtf8(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeAdvSimd64(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3(), System.Text.UnicodeUtility.IsAsciiCodePoint(), System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.IsCharAllowed(), System.ReadOnlySpan< T >.IsEmpty, System.BitConverter.IsLittleEndian, System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.IsSupported, System.Runtime.Intrinsics.X86.Ssse3.IsSupported, System.length, System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), and System.Text.Rune.Value.
Referenced by System.Text.Encodings.Web.DefaultHtmlEncoder.FindFirstCharacterToEncodeUtf8(), System.Text.Encodings.Web.DefaultJavaScriptEncoder.FindFirstCharacterToEncodeUtf8(), and System.Text.Encodings.Web.DefaultUrlEncoder.FindFirstCharacterToEncodeUtf8().