Terraria: System.Text.Encodings.Web.OptimizedInboxTextEncoder.TryEncodeUnicodeScalar
TryEncodeUnicodeScalar()
unsafe bool System.Text.Encodings.Web.OptimizedInboxTextEncoder.TryEncodeUnicodeScalar (int unicodeScalar, char * buffer, int bufferLength, out int numberOfCharactersWritten) inline
Definition at line 136 of file OptimizedInboxTextEncoder.cs.
    {
        Span<char> destination = new Span<char>(buffer, bufferLength);
        if (_allowedBmpCodePoints.IsCodePointAllowed((uint)unicodeScalar))
        {
            if (!destination.IsEmpty)
            {
                destination[0] = (char)unicodeScalar;
                numberOfCharactersWritten = 1;
                return true;
            }
        }
        else
        {
            int num = _scalarEscaper.EncodeUtf16(new Rune(unicodeScalar), destination);
            if (num >= 0)
            {
                numberOfCharactersWritten = num;
                return true;
            }
        }
        numberOfCharactersWritten = 0;
        return false;
    }
References System.Text.Encodings.Web.OptimizedInboxTextEncoder._allowedBmpCodePoints, System.Text.Encodings.Web.OptimizedInboxTextEncoder._scalarEscaper, System.buffer, System.destination, System.Text.Encodings.Web.ScalarEscaperBase.EncodeUtf16(), and System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.IsCodePointAllowed().
Referenced by System.Text.Encodings.Web.DefaultHtmlEncoder.TryEncodeUnicodeScalar(), System.Text.Encodings.Web.DefaultJavaScriptEncoder.TryEncodeUnicodeScalar(), and System.Text.Encodings.Web.DefaultUrlEncoder.TryEncodeUnicodeScalar().