Terraria: System.Text.Encodings.Web.OptimizedInboxTextEncoder.OptimizedInboxTextEncoder
OptimizedInboxTextEncoder()
System.Text.Encodings.Web.OptimizedInboxTextEncoder.OptimizedInboxTextEncoder (ScalarEscaperBase scalarEscaper, in AllowedBmpCodePointsBitmap allowedCodePointsBmp, bool forbidHtmlSensitiveCharacters = true, ReadOnlySpan< char > extraCharactersToEscape = default(ReadOnlySpan<char>)) inline package
Definition at line 109 of file OptimizedInboxTextEncoder.cs.
    {
        _scalarEscaper = scalarEscaper;
        _allowedBmpCodePoints = allowedCodePointsBmp;
        _allowedBmpCodePoints.ForbidUndefinedCharacters();
        if (forbidHtmlSensitiveCharacters)
        {
            _allowedBmpCodePoints.ForbidHtmlCharacters();
        }
        ReadOnlySpan<char> readOnlySpan = extraCharactersToEscape;
        for (int i = 0; i < readOnlySpan.Length; i++)
        {
            char value = readOnlySpan[i];
            _allowedBmpCodePoints.ForbidChar(value);
        }
        _asciiPreescapedData.PopulatePreescapedData(in _allowedBmpCodePoints, scalarEscaper);
        _allowedAsciiCodePoints.PopulateAllowedCodePoints(in _allowedBmpCodePoints);
    }
References System.Text.Encodings.Web.OptimizedInboxTextEncoder._allowedAsciiCodePoints, System.Text.Encodings.Web.OptimizedInboxTextEncoder._allowedBmpCodePoints, System.Text.Encodings.Web.OptimizedInboxTextEncoder._asciiPreescapedData, System.Text.Encodings.Web.OptimizedInboxTextEncoder._scalarEscaper, System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.ForbidChar(), System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.ForbidHtmlCharacters(), System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.ForbidUndefinedCharacters(), System.ReadOnlySpan< T >.Length, System.Text.Encodings.Web.OptimizedInboxTextEncoder.AllowedAsciiCodePoints.PopulateAllowedCodePoints(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.AsciiPreescapedData.PopulatePreescapedData(), and System.Text.Encodings.Web.value.