Terraria: BestiaryDatabaseNPCsPopulator.AddEmptyEntries_CrittersAndEnemies_Automated
AddEmptyEntries_CrittersAndEnemies_Automated()
void BestiaryDatabaseNPCsPopulator.AddEmptyEntries_CrittersAndEnemies_Automated () inline private
     {
         HashSet<int> exclusions = GetExclusions();
         foreach (KeyValuePair<int, NPC> item in ContentSamples.NpcsByNetId)
         {
             if (!exclusions.Contains(item.Key) && !item.Value.isLikeATownNPC)
             {
                 if (item.Value.CountsAsACritter)
                 {
                     Register(BestiaryEntry.Critter(item.Key));
                 }
                 else
                 {
                     Register(BestiaryEntry.Enemy(item.Key));
                 }
             }
         }
     }
References BestiaryEntry.Critter(), BestiaryEntry.Enemy(), GetExclusions(), ContentSamples.NpcsByNetId, and Register().
Referenced by Populate().