Terraria: BestiaryDatabaseNPCsPopulator.RegisterFilters
RegisterFilters()
void BestiaryDatabaseNPCsPopulator.RegisterFilters () inline private
     {
         Register(new Filters.ByUnlockState());
         Register(new Filters.ByBoss());
         Register(new Filters.ByRareCreature());
         List<IBestiaryInfoElement> commonInfoElementsForFilters = CommonTags.GetCommonInfoElementsForFilters();
         for (int i = 0; i < commonInfoElementsForFilters.Count; i++)
         {
             Register(new Filters.ByInfoElement(commonInfoElementsForFilters[i]));
         }
     }
References BestiaryDatabaseNPCsPopulator.CommonTags.GetCommonInfoElementsForFilters(), and Register().
Referenced by Populate().