Terraria: BestiaryDatabaseNPCsPopulator.ModifyEntriesThatNeedIt
ModifyEntriesThatNeedIt()
void BestiaryDatabaseNPCsPopulator.ModifyEntriesThatNeedIt () inline private
     {
         FindEntryByNPCID(258).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.SurfaceMushroom));
         FindEntryByNPCID(-1).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCorruption));
         FindEntryByNPCID(81).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCorruption));
         FindEntryByNPCID(121).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCorruption));
         FindEntryByNPCID(7).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCorruption));
         FindEntryByNPCID(98).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCorruption));
         FindEntryByNPCID(6).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCorruption));
         FindEntryByNPCID(94).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCorruption));
         FindEntryByNPCID(173).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCrimson));
         FindEntryByNPCID(181).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCrimson));
         FindEntryByNPCID(183).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCrimson));
         FindEntryByNPCID(242).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCrimson));
         FindEntryByNPCID(241).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCrimson));
         FindEntryByNPCID(174).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCrimson));
         FindEntryByNPCID(240).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.TheCrimson));
         FindEntryByNPCID(175).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.UndergroundJungle));
         FindEntryByNPCID(153).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.Jungle));
         FindEntryByNPCID(52).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.Jungle));
         FindEntryByNPCID(58).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.Jungle));
         FindEntryByNPCID(102).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.Caverns));
         FindEntryByNPCID(157).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.Jungle));
         FindEntryByNPCID(51).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.Jungle));
         FindEntryByNPCID(169).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.UndergroundSnow));
         FindEntryByNPCID(510).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.UndergroundDesert));
         FindEntryByNPCID(69).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.Desert));
         FindEntryByNPCID(580).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.UndergroundDesert));
         FindEntryByNPCID(581).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.UndergroundDesert));
         FindEntryByNPCID(78).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.Desert));
         FindEntryByNPCID(79).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.CorruptDesert));
         FindEntryByNPCID(630).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.CrimsonDesert));
         FindEntryByNPCID(80).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.HallowDesert));
         FindEntryByNPCID(533).AddTags(new BestiaryPortraitBackgroundBasedOnWorldEvilProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.CorruptUndergroundDesert, CommonTags.SpawnConditions.Biomes.CrimsonUndergroundDesert));
         FindEntryByNPCID(528).AddTags(new BestiaryPortraitBackgroundProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.UndergroundDesert));
         FindEntryByNPCID(529).AddTags(new BestiaryPortraitBackgroundBasedOnWorldEvilProviderPreferenceInfoElement(CommonTags.SpawnConditions.Biomes.CorruptUndergroundDesert, CommonTags.SpawnConditions.Biomes.CrimsonUndergroundDesert));
         _currentDatabase.ApplyPass(TryGivingEntryFlavorTextIfItIsMissing);
         BestiaryEntry bestiaryEntry = FindEntryByNPCID(398);
         bestiaryEntry.Info.Add(new MoonLordPortraitBackgroundProviderBestiaryInfoElement());
         bestiaryEntry.Info.RemoveAll((IBestiaryInfoElement x) => x is NamePlateInfoElement);
         bestiaryEntry.Info.Add(new NamePlateInfoElement("Enemies.MoonLord", 398));
         bestiaryEntry.Icon = new UnlockableNPCEntryIcon(398, 0f, 0f, 0f, 0f, "Enemies.MoonLord");
         FindEntryByNPCID(664).Info.RemoveAll((IBestiaryInfoElement x) => x is NPCKillCounterInfoElement);
         FindEntryByNPCID(687).Info.RemoveAll((IBestiaryInfoElement x) => x is NPCKillCounterInfoElement);
         ModifyEntriesThatNeedIt_NameOverride(637, "Friends.TownCat");
         ModifyEntriesThatNeedIt_NameOverride(638, "Friends.TownDog");
         ModifyEntriesThatNeedIt_NameOverride(656, "Friends.TownBunny");
         for (int i = 494; i <= 506; i++)
         {
             FindEntryByNPCID(i).UIInfoProvider = new SalamanderShellyDadUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[i]);
         }
         FindEntryByNPCID(534).UIInfoProvider = new HighestOfMultipleUICollectionInfoProvider(new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[534], quickUnlock: false), new TownNPCUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[441]));
         foreach (NPCStatsReportInfoElement item in from x in FindEntryByNPCID(13).Info
             select x as NPCStatsReportInfoElement into x
             where x != null
             select x)
         {
             item.OnRefreshStats += AdjustEaterOfWorldStats;
         }
         foreach (NPCStatsReportInfoElement item2 in from x in FindEntryByNPCID(491).Info
             select x as NPCStatsReportInfoElement into x
             where x != null
             select x)
         {
             item2.OnRefreshStats += AdjustPirateShipStats;
         }
         FindEntryByNPCID(68).UIInfoProvider = new HighestOfMultipleUICollectionInfoProvider(new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[68], quickUnlock: true), new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[35], quickUnlock: true), new TownNPCUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[54]));
         FindEntryByNPCID(35).UIInfoProvider = new HighestOfMultipleUICollectionInfoProvider(new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[35], quickUnlock: true), new TownNPCUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[54]));
         FindEntryByNPCID(37).UIInfoProvider = new HighestOfMultipleUICollectionInfoProvider(new TownNPCUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[37]), new TownNPCUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[54]), new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[35], quickUnlock: true));
         FindEntryByNPCID(565).UIInfoProvider = new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[565], quickUnlock: true);
         FindEntryByNPCID(577).UIInfoProvider = new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[577], quickUnlock: true);
         FindEntryByNPCID(551).UIInfoProvider = new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[551], quickUnlock: true);
         FindEntryByNPCID(491).UIInfoProvider = new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[491], quickUnlock: true);
         foreach (KeyValuePair<int, int> item3 in new Dictionary<int, int>
         {
             { 5, 4 },
             { 267, 266 },
             { 115, 113 },
             { 116, 113 },
             { 117, 113 },
             { 139, 134 },
             { 372, 370 },
             { 658, 657 },
             { 659, 657 },
             { 660, 657 },
             { 454, 439 },
             { 521, 439 }
         })
         {
             int key = item3.Key;
             int value = item3.Value;
             FindEntryByNPCID(key).UIInfoProvider = new CommonEnemyUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[value], quickUnlock: true);
         }
         Dictionary<int, int[]> dictionary = new Dictionary<int, int[]>();
         dictionary.Add(443, new int[1] { 46 });
         dictionary.Add(442, new int[1] { 74 });
         dictionary.Add(592, new int[1] { 55 });
         dictionary.Add(444, new int[1] { 356 });
         dictionary.Add(601, new int[1] { 599 });
         dictionary.Add(445, new int[1] { 361 });
         dictionary.Add(446, new int[1] { 377 });
         dictionary.Add(605, new int[1] { 604 });
         dictionary.Add(447, new int[1] { 300 });
         dictionary.Add(627, new int[1] { 626 });
         dictionary.Add(613, new int[1] { 612 });
         dictionary.Add(448, new int[1] { 357 });
         dictionary.Add(539, new int[2] { 299, 538 });
         foreach (KeyValuePair<int, int[]> item4 in dictionary)
         {
             FindEntryByNPCID(item4.Key).UIInfoProvider = new GoldCritterUICollectionInfoProvider(item4.Value, ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[item4.Key]);
         }
         foreach (KeyValuePair<int, int> item5 in new Dictionary<int, int>
         {
             { 362, 363 },
             { 364, 365 },
             { 602, 603 },
             { 608, 609 }
         })
         {
             FindEntryByNPCID(item5.Key).UIInfoProvider = new HighestOfMultipleUICollectionInfoProvider(new CritterUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[item5.Key]), new CritterUICollectionInfoProvider(ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[item5.Value]));
         }
         FindEntryByNPCID(4).AddTags(new SearchAliasInfoElement("eoc"));
         FindEntryByNPCID(13).AddTags(new SearchAliasInfoElement("eow"));
         FindEntryByNPCID(266).AddTags(new SearchAliasInfoElement("boc"));
         FindEntryByNPCID(113).AddTags(new SearchAliasInfoElement("wof"));
         FindEntryByNPCID(50).AddTags(new SearchAliasInfoElement("slime king"));
         FindEntryByNPCID(125).AddTags(new SearchAliasInfoElement("the twins"));
         FindEntryByNPCID(126).AddTags(new SearchAliasInfoElement("the twins"));
         FindEntryByNPCID(222).AddTags(new SearchAliasInfoElement("qb"));
         FindEntryByNPCID(222).AddTags(new SearchAliasInfoElement("bee queen"));
         FindEntryByNPCID(398).AddTags(new SearchAliasInfoElement("moonlord"));
         FindEntryByNPCID(398).AddTags(new SearchAliasInfoElement("cthulhu"));
         FindEntryByNPCID(398).AddTags(new SearchAliasInfoElement("ml"));
         FindEntryByNPCID(125).AddTags(new SearchAliasInfoElement("mech boss"));
         FindEntryByNPCID(126).AddTags(new SearchAliasInfoElement("mech boss"));
         FindEntryByNPCID(127).AddTags(new SearchAliasInfoElement("mech boss"));
         FindEntryByNPCID(134).AddTags(new SearchAliasInfoElement("mech boss"));
         FindEntryByNPCID(657).AddTags(new SearchAliasInfoElement("slime queen"));
         FindEntryByNPCID(636).AddTags(new SearchAliasInfoElement("eol"));
         FindEntryByNPCID(636).AddTags(new SearchAliasInfoElement("fairy"));
     }
References _currentDatabase, BestiaryEntry.AddTags(), AdjustEaterOfWorldStats(), AdjustPirateShipStats(), BestiaryDatabase.ApplyPass(), BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Caverns, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CorruptDesert, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CorruptUndergroundDesert, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CrimsonDesert, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.CrimsonUndergroundDesert, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Desert, FindEntryByNPCID(), BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.HallowDesert, BestiaryEntry.Icon, BestiaryEntry.Info, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Jungle, ModifyEntriesThatNeedIt_NameOverride(), ContentSamples.NpcBestiaryCreditIdsByNpcNetIds, NPCStatsReportInfoElement.OnRefreshStats, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.SurfaceMushroom, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCorruption, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.TheCrimson, TryGivingEntryFlavorTextIfItIsMissing(), BestiaryEntry.UIInfoProvider, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundDesert, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundJungle, and BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.UndergroundSnow.
Referenced by Populate().