Terraria: BestiaryDatabaseNPCsPopulator.Populate
Populate()
void BestiaryDatabaseNPCsPopulator.Populate (BestiaryDatabase database) inline
     {
         _currentDatabase = database;
         AddEmptyEntries_CrittersAndEnemies_Automated();
         AddTownNPCs_Manual();
         AddNPCBiomeRelationships_Automated();
         AddNPCBiomeRelationships_Manual();
         AddNPCBiomeRelationships_AddDecorations_Automated();
         ModifyEntriesThatNeedIt();
         RegisterFilters();
         RegisterSortSteps();
     }
References _currentDatabase, AddEmptyEntries_CrittersAndEnemies_Automated(), AddNPCBiomeRelationships_AddDecorations_Automated(), AddNPCBiomeRelationships_Automated(), AddNPCBiomeRelationships_Manual(), AddTownNPCs_Manual(), ModifyEntriesThatNeedIt(), RegisterFilters(), and RegisterSortSteps().
Referenced by Main.Initialize_AlmostEverything().