Terraria: System.Net.Mime.QEncodedStream.WriteAsyncResult.CompleteWrite
CompleteWrite()
void System.Net.Mime.QEncodedStream.WriteAsyncResult.CompleteWrite (IAsyncResult result) inline private
Definition at line 39 of file QEncodedStream.cs.
        {
            _parent.BaseStream.EndWrite(result);
            _parent.WriteState.Reset();
        }
References System.Net.Mime.QEncodedStream.WriteAsyncResult._parent, System.Net.DelegatedStream.BaseStream, System.IO.Stream.EndWrite(), System.Net.Mime.WriteStateInfoBase.Reset(), and System.Net.Mime.QEncodedStream.WriteState.
Referenced by System.Net.Mime.QEncodedStream.WriteAsyncResult.OnWrite(), and System.Net.Mime.QEncodedStream.WriteAsyncResult.Write().