Terraria: System.Text.EncodingCharBuffer.AddChar
AddChar() [2/3]
unsafe bool System.Text.EncodingCharBuffer.AddChar (char ch, int numBytes) inline package
Definition at line 55 of file EncodingCharBuffer.cs.
    {
        if (_chars != null)
        {
            if (_chars >= _charEnd)
            {
                _bytes -= numBytes;
                _enc.ThrowCharsOverflow(_decoder, _bytes <= _byteStart);
                return false;
            }
            *(_chars++) = ch;
        }
        _charCountResult++;
        return true;
    }
References System.Text.EncodingCharBuffer._bytes, System.Text.EncodingCharBuffer._byteStart, System.Text.EncodingCharBuffer._charCountResult, System.Text.EncodingCharBuffer._charEnd, System.Text.EncodingCharBuffer._chars, System.Text.EncodingCharBuffer._decoder, System.Text.EncodingCharBuffer._enc, System.ch, and System.Text.EncodingNLS.ThrowCharsOverflow().
Referenced by System.Text.EncodingCharBuffer.AddChar(), and System.Text.EncodingCharBuffer.AddChar().