Terraria: System.Text.EncodingCharBuffer.Fallback
Fallback() [4/4]
unsafe bool System.Text.EncodingCharBuffer.Fallback (byte[] byteBuffer) inline package
Definition at line 128 of file EncodingCharBuffer.cs.
    {
        if (_chars != null)
        {
            char* chars = _chars;
            if (!_fallbackBufferHelper.InternalFallback(byteBuffer, _bytes, ref _chars))
            {
                _bytes -= byteBuffer.Length;
                _fallbackBufferHelper.InternalReset();
                _enc.ThrowCharsOverflow(_decoder, _chars == _charStart);
                return false;
            }
            _charCountResult += (int)(_chars - chars);
        }
        else
        {
            _charCountResult += _fallbackBufferHelper.InternalFallback(byteBuffer, _bytes);
        }
        return true;
    }
References System.Text.EncodingCharBuffer._bytes, System.Text.EncodingCharBuffer._charCountResult, System.Text.EncodingCharBuffer._chars, System.Text.EncodingCharBuffer._charStart, System.Text.EncodingCharBuffer._decoder, System.Text.EncodingCharBuffer._enc, System.Text.EncodingCharBuffer._fallbackBufferHelper, System.chars, System.Text.DecoderFallbackBufferHelper.InternalFallback(), System.Text.DecoderFallbackBufferHelper.InternalReset(), and System.Text.EncodingNLS.ThrowCharsOverflow().