Terraria: System.MemoryExtensions.TryWriteInterpolatedStringHandler.Fail
Fail()
bool System.MemoryExtensions.TryWriteInterpolatedStringHandler.Fail () inline private
Definition at line 293 of file MemoryExtensions.cs.
        {
            _success = false;
            return false;
        }
References System.MemoryExtensions.TryWriteInterpolatedStringHandler._success.
Referenced by System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendLiteral(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendStringDirect(), and System.MemoryExtensions.TryWriteInterpolatedStringHandler.TryAppendOrInsertAlignmentIfNeeded().