Terraria: System.MemoryExtensions.TryWriteInterpolatedStringHandler.TryAppendOrInsertAlignmentIfNeeded
TryAppendOrInsertAlignmentIfNeeded()
bool System.MemoryExtensions.TryWriteInterpolatedStringHandler.TryAppendOrInsertAlignmentIfNeeded (int startingPos, int alignment) inline private
Definition at line 262 of file MemoryExtensions.cs.
        {
            int num = _pos - startingPos;
            bool flag = false;
            if (alignment < 0)
            {
                flag = true;
                alignment = -alignment;
            }
            int num2 = alignment - num;
            if (num2 <= 0)
            {
                return true;
            }
            if (num2 <= _destination.Length - _pos)
            {
                if (flag)
                {
                    _destination.Slice(_pos, num2).Fill(' ');
                }
                else
                {
                    _destination.Slice(startingPos, num).CopyTo(_destination.Slice(startingPos + num2));
                    _destination.Slice(startingPos, num2).Fill(' ');
                }
                _pos += num2;
                return true;
            }
            return Fail();
        }
References System.MemoryExtensions.TryWriteInterpolatedStringHandler._destination, System.MemoryExtensions.TryWriteInterpolatedStringHandler._pos, System.MemoryExtensions.TryWriteInterpolatedStringHandler.Fail(), System.Span< T >.Length, and System.Span< T >.Slice().
Referenced by System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >(), and System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >().