Terraria: System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >
AppendFormatted< T >() [1/4]
bool System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T > (T value) inline
Definition at line 85 of file MemoryExtensions.cs.
        {
            if (_hasCustomFormatter)
            {
                return AppendCustomFormatter(value, null);
            }
            string text;
            if (value is IFormattable)
            {
                if (value is ISpanFormattable)
                {
                    if (((ISpanFormattable)(object)value).TryFormat(_destination.Slice(_pos), out var charsWritten, default(ReadOnlySpan<char>), _provider))
                    {
                        _pos += charsWritten;
                        return true;
                    }
                    return Fail();
                }
                text = ((IFormattable)(object)value).ToString(null, _provider);
            }
            else
            {
                text = value?.ToString();
            }
            if (text != null)
            {
                return AppendStringDirect(text);
            }
            return true;
        }
References System.MemoryExtensions.TryWriteInterpolatedStringHandler._destination, System.MemoryExtensions.TryWriteInterpolatedStringHandler._hasCustomFormatter, System.MemoryExtensions.TryWriteInterpolatedStringHandler._pos, System.MemoryExtensions.TryWriteInterpolatedStringHandler._provider, System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendStringDirect(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.Fail(), System.Span< T >.Slice(), System.text, System.ToString, and System.value.