Terraria: System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted
AppendFormatted() [2/5]
bool System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted (ReadOnlySpan< char > value) inline
Definition at line 175 of file MemoryExtensions.cs.
        {
            if (value.TryCopyTo(_destination.Slice(_pos)))
            {
                _pos += value.Length;
                return true;
            }
            return Fail();
        }
References System.MemoryExtensions.TryWriteInterpolatedStringHandler._destination, System.MemoryExtensions.TryWriteInterpolatedStringHandler._pos, System.MemoryExtensions.TryWriteInterpolatedStringHandler.Fail(), System.Span< T >.Slice(), and System.value.
Referenced by System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >(), and System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >().