Terraria: System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >
AppendFormatted< T >() [2/4]
bool System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T > (T value, int alignment) inline
Definition at line 147 of file MemoryExtensions.cs.
        {
            int pos = _pos;
            if (AppendFormatted(value))
            {
                if (alignment != 0)
                {
                    return TryAppendOrInsertAlignmentIfNeeded(pos, alignment);
                }
                return true;
            }
            return Fail();
        }
References System.MemoryExtensions.TryWriteInterpolatedStringHandler._pos, System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.Fail(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.TryAppendOrInsertAlignmentIfNeeded(), and System.value.