Terraria: System.Reflection.Metadata.Ecma335.VirtualHeap.AddBlob
AddBlob()
MemoryBlock System.Reflection.Metadata.Ecma335.VirtualHeap.AddBlob (uint rawHandle, byte[] value) inline package
Definition at line 69 of file VirtualHeap.cs.
    {
        Dictionary<uint, PinnedBlob> blobs = GetBlobs();
        PinnedBlob value2 = new PinnedBlob(GCHandle.Alloc(value, GCHandleType.Pinned), value.Length);
        blobs.Add(rawHandle, value2);
        return value2.GetMemoryBlock();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.InteropServices.GCHandle.Alloc(), System.Reflection.Metadata.Ecma335.VirtualHeap.GetBlobs(), and System.value.
Referenced by System.Reflection.Metadata.Ecma335.BlobHeap.GetVirtualHandleMemoryBlock(), and System.Reflection.Metadata.Ecma335.StringHeap.GetVirtualHandleMemoryBlock().