Terraria: System.Threading.Tasks.Task.DelayPromiseWithCancellation.DelayPromiseWithCancellation
DelayPromiseWithCancellation()
System.Threading.Tasks.Task< TResult >.DelayPromiseWithCancellation.DelayPromiseWithCancellation (uint millisecondsDelay, CancellationToken token) inline package
Definition at line 645 of file Task.cs.
            : base(millisecondsDelay)
        {
            _registration = token.UnsafeRegister(delegate(object state, CancellationToken cancellationToken)
            {
                DelayPromiseWithCancellation delayPromiseWithCancellation = (DelayPromiseWithCancellation)state;
                if (delayPromiseWithCancellation.TrySetCanceled(cancellationToken))
                {
                    delayPromiseWithCancellation.Cleanup();
                }
            }, this);
            if (base.IsCompleted)
            {
                _registration.Dispose();
            }
        }
References System.Threading.Tasks.Task< TResult >.DelayPromiseWithCancellation.DelayPromiseWithCancellation(), System.Threading.Tasks.Task< TResult >.DelayPromiseWithCancellation._registration, System.cancellationToken, System.Threading.CancellationTokenRegistration.Dispose(), System.state, and System.Threading.CancellationToken.UnsafeRegister().
Referenced by System.Threading.Tasks.Task< TResult >.DelayPromiseWithCancellation.DelayPromiseWithCancellation().