Terraria: System.Reflection.NullabilityInfoContext.IsPublicOnly
IsPublicOnly()
bool System.Reflection.NullabilityInfoContext.IsPublicOnly (bool isPrivate, bool isFamilyAndAssembly, bool isAssembly, Module module) inline private
Definition at line 226 of file NullabilityInfoContext.cs.
    {
        if (!_publicOnlyModules.TryGetValue(module, out var value))
        {
            value = PopulateAnnotationInfo(module.GetCustomAttributesData());
            _publicOnlyModules.Add(module, value);
        }
        if (value == NotAnnotatedStatus.None)
        {
            return false;
        }
        if (((isPrivate || isFamilyAndAssembly) && value.HasFlag(NotAnnotatedStatus.Private)) || (isAssembly && value.HasFlag(NotAnnotatedStatus.Internal)))
        {
            return true;
        }
        return false;
    }
References System.Reflection.NullabilityInfoContext._publicOnlyModules, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.NullabilityInfoContext.PopulateAnnotationInfo(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Reflection.NullabilityInfoContext.IsPrivateOrInternalFieldAndAnnotationDisabled(), and System.Reflection.NullabilityInfoContext.IsPrivateOrInternalMethodAndAnnotationDisabled().