Terraria: System.Reflection.NullabilityInfoContext.Create
Create() [2/4]
NullabilityInfo System.Reflection.NullabilityInfoContext.Create (FieldInfo fieldInfo) inline
Definition at line 192 of file NullabilityInfoContext.cs.
    {
        if ((object)fieldInfo == null)
        {
            throw new ArgumentNullException("fieldInfo");
        }
        EnsureIsSupported();
        if (IsPrivateOrInternalFieldAndAnnotationDisabled(fieldInfo))
        {
            return new NullabilityInfo(fieldInfo.FieldType, NullabilityState.Unknown, NullabilityState.Unknown, null, Array.Empty<NullabilityInfo>());
        }
        IList<CustomAttributeData> customAttributesData = fieldInfo.GetCustomAttributesData();
        NullabilityInfo nullabilityInfo = GetNullabilityInfo(fieldInfo, fieldInfo.FieldType, customAttributesData);
        CheckNullabilityAttributes(nullabilityInfo, customAttributesData);
        return nullabilityInfo;
    }
References System.Reflection.NullabilityInfoContext.CheckNullabilityAttributes(), System.Reflection.NullabilityInfoContext.EnsureIsSupported(), System.Reflection.NullabilityInfoContext.GetNullabilityInfo(), and System.Reflection.NullabilityInfoContext.IsPrivateOrInternalFieldAndAnnotationDisabled().