Terraria: System.Reflection.NullabilityInfoContext.CheckGenericParameters
CheckGenericParameters()
void System.Reflection.NullabilityInfoContext.CheckGenericParameters (NullabilityInfo nullability, MemberInfo metaMember, Type metaType) inline private
Definition at line 392 of file NullabilityInfoContext.cs.
    {
        if (metaType.IsGenericParameter)
        {
            NullabilityState state = nullability.ReadState;
            if (state == NullabilityState.NotNull && !ParseNullableState(metaType.GetCustomAttributesData(), 0, ref state))
            {
                state = GetNullableContext(metaType);
            }
            nullability.ReadState = state;
            nullability.WriteState = state;
        }
        else
        {
            if (!metaType.ContainsGenericParameters)
            {
                return;
            }
            if (nullability.GenericTypeArguments.Length != 0)
            {
                Type[] genericArguments = metaType.GetGenericArguments();
                for (int i = 0; i < genericArguments.Length; i++)
                {
                    if (genericArguments[i].IsGenericParameter)
                    {
                        NullabilityInfo nullabilityInfo = GetNullabilityInfo(metaMember, genericArguments[i], genericArguments[i].GetCustomAttributesData(), i + 1);
                        nullability.GenericTypeArguments[i].ReadState = nullabilityInfo.ReadState;
                        nullability.GenericTypeArguments[i].WriteState = nullabilityInfo.WriteState;
                    }
                    else
                    {
                        UpdateGenericArrayElements(nullability.GenericTypeArguments[i].ElementType, metaMember, genericArguments[i]);
                    }
                }
            }
            else
            {
                UpdateGenericArrayElements(nullability.ElementType, metaMember, metaType);
            }
        }
    }
References System.Reflection.NullabilityInfoContext.GetNullabilityInfo(), System.Reflection.NullabilityInfoContext.GetNullableContext(), System.Reflection.NullabilityInfoContext.ParseNullableState(), System.state, and System.Reflection.NullabilityInfoContext.UpdateGenericArrayElements().
Referenced by System.Reflection.NullabilityInfoContext.CheckParameterMetadataType(), and System.Reflection.NullabilityInfoContext.TryLoadGenericMetaTypeNullability().