Terraria: System.Reflection.NullabilityInfoContext.GetNullabilityInfo
GetNullabilityInfo() [2/2]
NullabilityInfo System.Reflection.NullabilityInfoContext.GetNullabilityInfo (MemberInfo memberInfo, Type type, IList< CustomAttributeData > customAttributes, int index) inline private
Definition at line 277 of file NullabilityInfoContext.cs.
    {
        NullabilityState state = NullabilityState.Unknown;
        NullabilityInfo elementType = null;
        NullabilityInfo[] array = Array.Empty<NullabilityInfo>();
        Type type2 = type;
        if (type.IsValueType)
        {
            type2 = Nullable.GetUnderlyingType(type);
            if (type2 != null)
            {
                state = NullabilityState.Nullable;
            }
            else
            {
                type2 = type;
                state = NullabilityState.NotNull;
            }
        }
        else
        {
            if (!ParseNullableState(customAttributes, index, ref state))
            {
                state = GetNullableContext(memberInfo);
            }
            if (type.IsArray)
            {
                elementType = GetNullabilityInfo(memberInfo, type.GetElementType(), customAttributes, index + 1);
            }
        }
        if (type2.IsGenericType)
        {
            Type[] genericArguments = type2.GetGenericArguments();
            array = new NullabilityInfo[genericArguments.Length];
            int i = 0;
            int num = 0;
            for (; i < genericArguments.Length; i++)
            {
                Type type3 = Nullable.GetUnderlyingType(genericArguments[i]) ?? genericArguments[i];
                if (!type3.IsValueType || type3.IsGenericType)
                {
                    num++;
                }
                array[i] = GetNullabilityInfo(memberInfo, genericArguments[i], customAttributes, index + num);
            }
        }
        NullabilityInfo nullabilityInfo = new NullabilityInfo(type, state, state, elementType, array);
        if (!type.IsValueType && state != 0)
        {
            TryLoadGenericMetaTypeNullability(memberInfo, nullabilityInfo);
        }
        return nullabilityInfo;
    }
References System.array, System.elementType, System.Reflection.NullabilityInfoContext.GetNullabilityInfo(), System.Reflection.NullabilityInfoContext.GetNullableContext(), System.Nullable< T >.GetUnderlyingType(), System.index, System.Reflection.NullabilityInfoContext.ParseNullableState(), System.state, System.Reflection.NullabilityInfoContext.TryLoadGenericMetaTypeNullability(), and System.type.