Terraria: System.Reflection.NullabilityInfoContext.ParseNullableState
ParseNullableState()
static bool System.Reflection.NullabilityInfoContext.ParseNullableState (IList< CustomAttributeData > customAttributes, int index, ref NullabilityState state) inline static private
Definition at line 331 of file NullabilityInfoContext.cs.
    {
        foreach (CustomAttributeData customAttribute in customAttributes)
        {
            if (customAttribute.AttributeType.Name == "NullableAttribute" && customAttribute.AttributeType.Namespace == "System.Runtime.CompilerServices" && customAttribute.ConstructorArguments.Count == 1)
            {
                object value = customAttribute.ConstructorArguments[0].Value;
                if (value is byte b)
                {
                    state = TranslateByte(b);
                    return true;
                }
                if (value is ReadOnlyCollection<CustomAttributeTypedArgument> readOnlyCollection && index < readOnlyCollection.Count && readOnlyCollection[index].Value is byte b2)
                {
                    state = TranslateByte(b2);
                    return true;
                }
                break;
            }
        }
        return false;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.index, System.state, System.Reflection.NullabilityInfoContext.TranslateByte(), and System.value.
Referenced by System.Reflection.NullabilityInfoContext.CheckGenericParameters(), and System.Reflection.NullabilityInfoContext.GetNullabilityInfo().