Terraria: System.Reflection.NullabilityInfoContext.Create
Create() [4/4]
NullabilityInfo System.Reflection.NullabilityInfoContext.Create (PropertyInfo propertyInfo) inline
Definition at line 136 of file NullabilityInfoContext.cs.
    {
        if ((object)propertyInfo == null)
        {
            throw new ArgumentNullException("propertyInfo");
        }
        EnsureIsSupported();
        NullabilityInfo nullabilityInfo = GetNullabilityInfo(propertyInfo, propertyInfo.PropertyType, propertyInfo.GetCustomAttributesData());
        MethodInfo getMethod = propertyInfo.GetGetMethod(nonPublic: true);
        MethodInfo setMethod = propertyInfo.GetSetMethod(nonPublic: true);
        if (getMethod != null)
        {
            if (IsPrivateOrInternalMethodAndAnnotationDisabled(getMethod))
            {
                nullabilityInfo.ReadState = NullabilityState.Unknown;
            }
            CheckNullabilityAttributes(nullabilityInfo, getMethod.ReturnParameter.GetCustomAttributesData());
        }
        else
        {
            nullabilityInfo.ReadState = NullabilityState.Unknown;
        }
        if (setMethod != null)
        {
            if (IsPrivateOrInternalMethodAndAnnotationDisabled(setMethod))
            {
                nullabilityInfo.WriteState = NullabilityState.Unknown;
            }
            CheckNullabilityAttributes(nullabilityInfo, setMethod.GetParameters()[0].GetCustomAttributesData());
        }
        else
        {
            nullabilityInfo.WriteState = NullabilityState.Unknown;
        }
        return nullabilityInfo;
    }
References System.Reflection.NullabilityInfoContext.CheckNullabilityAttributes(), System.Reflection.NullabilityInfoContext.EnsureIsSupported(), System.Reflection.MemberInfo.GetCustomAttributesData(), System.Reflection.PropertyInfo.GetGetMethod(), System.Reflection.NullabilityInfoContext.GetNullabilityInfo(), System.Reflection.PropertyInfo.GetSetMethod(), System.Reflection.NullabilityInfoContext.IsPrivateOrInternalMethodAndAnnotationDisabled(), and System.Reflection.PropertyInfo.PropertyType.