Terraria: Terraria.DataStructures.TileReachCheckSettings.GetRanges
GetRanges()
void Terraria.DataStructures.TileReachCheckSettings.GetRanges (Player player, out int x, out int y) inline
Definition at line 46 of file TileReachCheckSettings.cs.
    {
        x = Player.tileRangeX * TileRangeMultiplier;
        y = Player.tileRangeY * TileRangeMultiplier;
        int? tileReachLimit = TileReachLimit;
        if (tileReachLimit.HasValue)
        {
            int value = tileReachLimit.Value;
            if (x > value)
            {
                x = value;
            }
            if (y > value)
            {
                y = value;
            }
        }
        if (OverrideXReach.HasValue)
        {
            x = OverrideXReach.Value;
        }
        if (OverrideYReach.HasValue)
        {
            y = OverrideYReach.Value;
        }
    }
References Terraria.DataStructures.TileReachCheckSettings.OverrideXReach, Terraria.DataStructures.TileReachCheckSettings.OverrideYReach, Terraria.DataStructures.TileReachCheckSettings.TileRangeMultiplier, and Terraria.DataStructures.TileReachCheckSettings.TileReachLimit.
Referenced by Terraria.Player.InInteractionRange(), Terraria.Player.IsInTileInteractionRange(), and Terraria.Player.IsTileTypeInInteractionRange().