Terraria: Internal.Cryptography.Pal.Native.SafeCertContextHandleWithKeyContainerDeletion.DeleteKeyContainer
DeleteKeyContainer()
static unsafe void Internal.Cryptography.Pal.Native.SafeCertContextHandleWithKeyContainerDeletion.DeleteKeyContainer (SafeCertContextHandle pCertContext) inline static
Definition at line 19 of file SafeCertContextHandleWithKeyContainerDeletion.cs.
    {
        if (pCertContext.IsInvalid)
        {
            return;
        }
        int pcbData = 0;
        if (!global::Interop.crypt32.CertGetCertificateContextProperty(pCertContext, CertContextPropId.CERT_KEY_PROV_INFO_PROP_ID, null, ref pcbData))
        {
            return;
        }
        byte[] array = new byte[pcbData];
        if (!global::Interop.crypt32.CertGetCertificateContextProperty(pCertContext, CertContextPropId.CERT_KEY_PROV_INFO_PROP_ID, array, ref pcbData))
        {
            return;
        }
        fixed (byte* ptr = array)
        {
            CRYPT_KEY_PROV_INFO* ptr2 = (CRYPT_KEY_PROV_INFO*)ptr;
            if (ptr2->dwProvType == 0)
            {
                string provider = Marshal.PtrToStringUni((IntPtr)ptr2->pwszProvName);
                string keyName = Marshal.PtrToStringUni((IntPtr)ptr2->pwszContainerName);
                try
                {
                    using CngKey cngKey = CngKey.Open(keyName, new CngProvider(provider));
                    cngKey.Delete();
                }
                catch (CryptographicException)
                {
                }
            }
            else
            {
                CryptAcquireContextFlags dwFlags = (ptr2->dwFlags & CryptAcquireContextFlags.CRYPT_MACHINE_KEYSET) | CryptAcquireContextFlags.CRYPT_DELETEKEYSET;
                global::Interop.cryptoapi.CryptAcquireContext(out var _, ptr2->pwszContainerName, ptr2->pwszProvName, ptr2->dwProvType, dwFlags);
            }
        }
    }
References System.array, Internal.Cryptography.Pal.Native.CRYPT_KEY_PROV_INFO.dwFlags, Internal.Cryptography.Pal.Native.CRYPT_KEY_PROV_INFO.dwProvType, Internal.Cryptography.Pal.Native.SafePointerHandle< T >.IsInvalid, System.Security.Cryptography.CngKey.Open(), System.Runtime.InteropServices.Marshal.PtrToStringUni(), Internal.Cryptography.Pal.Native.CRYPT_KEY_PROV_INFO.pwszContainerName, and Internal.Cryptography.Pal.Native.CRYPT_KEY_PROV_INFO.pwszProvName.
Referenced by Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(), and Internal.Cryptography.Pal.Native.SafeCertContextHandleWithKeyContainerDeletion.ReleaseHandle().