Terraria: System.Runtime.Serialization.ObjectToIdCache.FindElement
FindElement()
int System.Runtime.Serialization.ObjectToIdCache.FindElement (object obj, out bool isEmpty, out bool isWrapped) inline private
Definition at line 83 of file ObjectToIdCache.cs.
    {
        isWrapped = false;
        int num = ComputeStartPosition(obj);
        for (int i = num; i != num - 1; i++)
        {
            if (m_objs[i] == null)
            {
                isEmpty = true;
                return i;
            }
            if (m_objs[i] == obj)
            {
                isEmpty = false;
                return i;
            }
            if (i == m_objs.Length - 1)
            {
                isWrapped = true;
                i = -1;
            }
        }
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.ObjectTableOverflow));
    }
References System.Runtime.Serialization.ObjectToIdCache.ComputeStartPosition(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ObjectToIdCache.m_objs, System.obj, System.SR.ObjectTableOverflow, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.ObjectToIdCache.GetId(), System.Runtime.Serialization.ObjectToIdCache.ReassignId(), and System.Runtime.Serialization.ObjectToIdCache.Rehash().