Terraria: System.Runtime.Serialization.ObjectToIdCache.GetId
GetId()
int System.Runtime.Serialization.ObjectToIdCache.GetId (object obj, ref bool newId) inline
Definition at line 30 of file ObjectToIdCache.cs.
    {
        bool isEmpty;
        bool isWrapped;
        int num = FindElement(obj, out isEmpty, out isWrapped);
        if (!isEmpty)
        {
            newId = false;
            return m_ids[num];
        }
        if (!newId)
        {
            return -1;
        }
        int num2 = m_currentCount++;
        m_objs[num] = obj;
        m_ids[num] = num2;
        m_isWrapped[num] = isWrapped;
        if (m_currentCount >= m_objs.Length - 1)
        {
            Rehash();
        }
        return num2;
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ObjectToIdCache.FindElement(), System.Runtime.Serialization.ObjectToIdCache.m_currentCount, System.Runtime.Serialization.ObjectToIdCache.m_ids, System.Runtime.Serialization.ObjectToIdCache.m_isWrapped, System.Runtime.Serialization.ObjectToIdCache.m_objs, System.obj, and System.Runtime.Serialization.ObjectToIdCache.Rehash().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleIsReference().