Terraria: System.Runtime.Serialization.ObjectToIdCache.RemoveAt
RemoveAt()
void System.Runtime.Serialization.ObjectToIdCache.RemoveAt (int position) inline private
Definition at line 108 of file ObjectToIdCache.cs.
    {
        int num = m_objs.Length;
        int num2 = position;
        for (int i = ((position != num - 1) ? (position + 1) : 0); i != position; i++)
        {
            if (m_objs[i] == null)
            {
                m_objs[num2] = null;
                m_ids[num2] = 0;
                m_isWrapped[num2] = false;
                return;
            }
            int num3 = ComputeStartPosition(m_objs[i]);
            bool flag = i < position && !m_isWrapped[i];
            bool flag2 = num2 < position;
            if ((num3 <= num2 && (!flag || flag2)) || (flag2 && !flag))
            {
                m_objs[num2] = m_objs[i];
                m_ids[num2] = m_ids[i];
                m_isWrapped[num2] = m_isWrapped[i] && i > num2;
                num2 = i;
            }
            if (i == num - 1)
            {
                i = -1;
            }
        }
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.ObjectTableOverflow));
    }
References System.Runtime.Serialization.ObjectToIdCache.ComputeStartPosition(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ObjectToIdCache.m_ids, System.Runtime.Serialization.ObjectToIdCache.m_isWrapped, System.Runtime.Serialization.ObjectToIdCache.m_objs, System.SR.ObjectTableOverflow, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.ObjectToIdCache.ReassignId().