Terraria: System.Collections.Concurrent.ConcurrentQueue.ConcurrentQueue
ConcurrentQueue() [2/2]
System.Collections.Concurrent.ConcurrentQueue< T >.ConcurrentQueue (IEnumerable< T > collection) inline
Definition at line 104 of file ConcurrentQueue.cs.
    {
        if (collection == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.collection);
        }
        _crossSegmentLock = new object();
        int num = 32;
        if (collection is ICollection<T> { Count: var count } && count > num)
        {
            num = (int)Math.Min(BitOperations.RoundUpToPowerOf2((uint)count), 1048576u);
        }
        _tail = (_head = new ConcurrentQueueSegment<T>(num));
        foreach (T item in collection)
        {
            Enqueue(item);
        }
    }
References System.Collections.Concurrent.ConcurrentQueue< T >._crossSegmentLock, System.Collections.Concurrent.ConcurrentQueue< T >._head, System.Collections.Concurrent.ConcurrentQueue< T >._tail, System.collection, System.count, System.Collections.Concurrent.ConcurrentQueue< T >.Count, System.Collections.Concurrent.ConcurrentQueue< T >.Enqueue(), System.item, System.Math.Min(), System.Numerics.BitOperations.RoundUpToPowerOf2(), and System.ThrowHelper.ThrowArgumentNullException().