Terraria: System.Collections.Concurrent.ConcurrentQueue.Enumerate
Enumerate()
static IEnumerator< T > System.Collections.Concurrent.ConcurrentQueue< T >.Enumerate (ConcurrentQueueSegment< T > head, int headHead, ConcurrentQueueSegment< T > tail, int tailTail) inline static private inherited
Definition at line 269 of file ConcurrentQueue.cs.
    {
        int headTail = ((head == tail) ? tailTail : Volatile.Read(ref head._headAndTail.Tail)) - head.FreezeOffset;
        if (headHead < headTail)
        {
            headHead &= head._slotsMask;
            headTail &= head._slotsMask;
            if (headHead < headTail)
            {
                for (int l = headHead; l < headTail; l++)
                {
                    yield return GetItemWhenAvailable(head, l);
                }
            }
            else
            {
                for (int l = headHead; l < head._slots.Length; l++)
                {
                    yield return GetItemWhenAvailable(head, l);
                }
                for (int l = 0; l < headTail; l++)
                {
                    yield return GetItemWhenAvailable(head, l);
                }
            }
        }
        if (head == tail)
        {
            yield break;
        }
        for (ConcurrentQueueSegment<T> s = head._nextSegment; s != tail; s = s._nextSegment)
        {
            int l = s._headAndTail.Tail - s.FreezeOffset;
            for (int j = 0; j < l; j++)
            {
                yield return GetItemWhenAvailable(s, j);
            }
        }
        tailTail -= tail.FreezeOffset;
        for (int l = 0; l < tailTail; l++)
        {
            yield return GetItemWhenAvailable(tail, l);
        }
    }
References System.Collections.Concurrent.ConcurrentQueue< T >.GetItemWhenAvailable(), System.Threading.Volatile.Read(), and System.s.
Referenced by System.Collections.Concurrent.ConcurrentQueue< T >.CopyTo(), System.Collections.Concurrent.ConcurrentQueue< T >.GetEnumerator(), and System.Collections.Concurrent.ConcurrentQueue< T >.ToArray().