Terraria: System.Collections.Concurrent.ConcurrentQueue.SnapForObservation
SnapForObservation()
void System.Collections.Concurrent.ConcurrentQueue< T >.SnapForObservation (out ConcurrentQueueSegment< T > head, out int headHead, out ConcurrentQueueSegment< T > tail, out int tailTail) inline private inherited
Definition at line 233 of file ConcurrentQueue.cs.
    {
        lock (_crossSegmentLock)
        {
            head = _head;
            tail = _tail;
            ConcurrentQueueSegment<T> concurrentQueueSegment = head;
            while (true)
            {
                concurrentQueueSegment._preservedForObservation = true;
                if (concurrentQueueSegment == tail)
                {
                    break;
                }
                concurrentQueueSegment = concurrentQueueSegment._nextSegment;
            }
            tail.EnsureFrozenForEnqueues();
            headHead = Volatile.Read(ref head._headAndTail.Head);
            tailTail = Volatile.Read(ref tail._headAndTail.Tail);
        }
    }
References System.Collections.Concurrent.ConcurrentQueue< T >._crossSegmentLock, System.Collections.Concurrent.ConcurrentQueue< T >._head, System.Collections.Concurrent.ConcurrentQueue< T >._tail, and System.Threading.Volatile.Read().
Referenced by System.Collections.Concurrent.ConcurrentQueue< T >.CopyTo(), System.Collections.Concurrent.ConcurrentQueue< T >.GetEnumerator(), and System.Collections.Concurrent.ConcurrentQueue< T >.ToArray().