Terraria: Terraria.Graphics.MagicMissileDrawer.StripColors
StripColors()
Color Terraria.Graphics.MagicMissileDrawer.StripColors (float progressOnStrip) inline private
Definition at line 23 of file MagicMissileDrawer.cs.
    {
        Color result = Color.Lerp(Color.White, Color.Violet, Utils.GetLerpValue(0f, 0.7f, progressOnStrip, clamped: true)) * (1f - Utils.GetLerpValue(0f, 0.98f, progressOnStrip));
        result.A /= 2;
        return result;
    }
References Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.Color.Violet, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Graphics.MagicMissileDrawer.Draw().