Terraria: Terraria.Graphics.MagicMissileDrawer.Draw
Draw()
void Terraria.Graphics.MagicMissileDrawer.Draw (Projectile proj) inline
Definition at line 12 of file MagicMissileDrawer.cs.
    {
        MiscShaderData miscShaderData = GameShaders.Misc["MagicMissile"];
        miscShaderData.UseSaturation(-2.8f);
        miscShaderData.UseOpacity(2f);
        miscShaderData.Apply();
        _vertexStrip.PrepareStripWithProceduralPadding(proj.oldPos, proj.oldRot, StripColors, StripWidth, -Main.screenPosition + proj.Size / 2f);
        _vertexStrip.DrawTrail();
        Main.pixelShader.CurrentTechnique.Passes[0].Apply();
    }
References Terraria.Graphics.MagicMissileDrawer._vertexStrip, Terraria.Graphics.Shaders.MiscShaderData.Apply(), Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.Projectile.oldPos, Terraria.Projectile.oldRot, Terraria.Main.pixelShader, Terraria.Main.screenPosition, Terraria.Entity.Size, Terraria.Graphics.MagicMissileDrawer.StripColors(), Terraria.Graphics.MagicMissileDrawer.StripWidth(), Terraria.Graphics.Shaders.MiscShaderData.UseOpacity(), and Terraria.Graphics.Shaders.MiscShaderData.UseSaturation().