Terraria: ReLogic.Peripherals.RGB.Fragment.SetupCanvasBounds
SetupCanvasBounds()
void ReLogic.Peripherals.RGB.Fragment.SetupCanvasBounds () inline private
Definition at line 129 of file Fragment.cs.
    {
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        if (_canvasPositions.Length != 0)
        {
            float num = _canvasPositions[0].X;
            float num2 = _canvasPositions[0].X;
            float num3 = _canvasPositions[0].Y;
            float num4 = _canvasPositions[0].Y;
            for (int i = 1; i < _canvasPositions.Length; i++)
            {
                num = Math.Min(num, _canvasPositions[i].X);
                num3 = Math.Min(num3, _canvasPositions[i].Y);
                num2 = Math.Max(num2, _canvasPositions[i].X);
                num4 = Math.Max(num4, _canvasPositions[i].Y);
            }
            CanvasTopLeft = new Vector2(num, num3);
            CanvasBottomRight = new Vector2(num2, num4);
            CanvasSize = new Vector2(num2 - num, num4 - num3);
            CanvasCenter = CanvasTopLeft + CanvasSize * 0.5f;
        }
    }
References ReLogic.Peripherals.RGB.Fragment._canvasPositions, ReLogic.Peripherals.RGB.Fragment.CanvasBottomRight, ReLogic.Peripherals.RGB.Fragment.CanvasCenter, ReLogic.Peripherals.RGB.Fragment.CanvasSize, ReLogic.Peripherals.RGB.Fragment.CanvasTopLeft, Microsoft.Xna.Framework.Vector2.Length(), System.Math.Max(), System.Math.Min(), Microsoft.Xna.Framework.Vector2.X, System.X, Microsoft.Xna.Framework.Vector2.Y, and System.Y.
Referenced by ReLogic.Peripherals.RGB.Fragment.Fragment().