Terraria: ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex
GetGridPositionOfIndex()
Point ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex (int index) inline
Definition at line 81 of file Fragment.cs.
    {
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        return _gridPositions[index];
    }
References ReLogic.Peripherals.RGB.Fragment._gridPositions, and System.index.
Referenced by ReLogic.Peripherals.RGB.RgbDevice.GetLedGridPosition(), Terraria.GameContent.RGB.SkyShader.ProcessAnyDetail(), Terraria.GameContent.RGB.CorruptSurfaceShader.ProcessHighDetail(), Terraria.GameContent.RGB.DesertShader.ProcessHighDetail(), Terraria.GameContent.RGB.DrippingShader.ProcessHighDetail(), Terraria.GameContent.RGB.DukeFishronShader.ProcessHighDetail(), Terraria.GameContent.RGB.DungeonShader.ProcessHighDetail(), Terraria.GameContent.RGB.EmpressShader.ProcessHighDetail(), Terraria.GameContent.RGB.FrostLegionShader.ProcessHighDetail(), Terraria.GameContent.RGB.GemCaveShader.ProcessHighDetail(), Terraria.GameContent.RGB.GolemShader.ProcessHighDetail(), Terraria.GameContent.RGB.HallowSurfaceShader.ProcessHighDetail(), Terraria.GameContent.RGB.JungleShader.ProcessHighDetail(), Terraria.GameContent.RGB.MeteoriteShader.ProcessHighDetail(), Terraria.GameContent.RGB.PirateInvasionShader.ProcessHighDetail(), Terraria.GameContent.RGB.PlanteraShader.ProcessHighDetail(), Terraria.GameContent.RGB.RainShader.ProcessHighDetail(), Terraria.GameContent.RGB.SkullShader.ProcessHighDetail(), Terraria.GameContent.RGB.SlimeRainShader.ProcessHighDetail(), Terraria.GameContent.RGB.SurfaceBiomeShader.ProcessHighDetail(), Terraria.GameContent.RGB.TempleShader.ProcessHighDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundCorruptionShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundHallowShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundMushroomShader.ProcessHighDetail(), Terraria.GameContent.RGB.VineShader.ProcessHighDetail(), Terraria.GameContent.RGB.MartianMadnessShader.ProcessLowDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessLowDetail(), and Terraria.GameContent.RGB.EmpressShader.RedsVersion().