Terraria: Terraria.WorldBuilding.Actions.SwapSolidTile.Apply
Apply()
override bool Terraria.WorldBuilding.Actions.SwapSolidTile.Apply (Point origin, int x, int y, params object[] args) inline
Definition at line 426 of file Actions.cs.
        {
            Tile tile = GenBase._tiles[x, y];
            if (WorldGen.SolidTile(tile))
            {
                tile.ResetToType(_type);
                return UnitApply(origin, x, y, args);
            }
            return Fail();
        }
References Terraria.WorldBuilding.GenBase._tiles, Terraria.WorldBuilding.Actions.SwapSolidTile._type, Terraria.WorldBuilding.GenAction.Fail(), Terraria.Tile.ResetToType(), Terraria.WorldGen.SolidTile(), and Terraria.WorldBuilding.GenAction.UnitApply().