Terraria: MysticLogFairiesEvent.ScanWholeOverworldForLogs
ScanWholeOverworldForLogs()
void MysticLogFairiesEvent.ScanWholeOverworldForLogs () inline private
     {
         _stumpCoords.Clear();
         NPC.fairyLog = false;
         int num = (int)Main.worldSurface - 10;
         int num2 = 100;
         int num3 = Main.maxTilesX - 100;
         if (Main.remixWorld)
         {
             num = Main.maxTilesY - 350;
             num2 = (int)Main.rockLayer;
         }
         int num4 = 3;
         int num5 = 2;
         List<Point> list = new List<Point>();
         for (int i = 100; i < num3; i += num4)
         {
             for (int num6 = num; num6 >= num2; num6 -= num5)
             {
                 Tile tile = Main.tile[i, num6];
                 if (tile.active() && tile.type == 488 && tile.liquid == 0)
                 {
                     list.Add(new Point(i, num6));
                     NPC.fairyLog = true;
                 }
             }
         }
         foreach (Point item in list)
         {
             _stumpCoords.Add(GetStumpTopLeft(item));
         }
     }
References _stumpCoords, Tile.active(), NPC.fairyLog, GetStumpTopLeft(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Main.remixWorld, Main.rockLayer, Main.tile, Tile.type, and Main.worldSurface.
Referenced by FallenLogDestroyed(), StartNight(), and StartWorld().