Terraria: MysticLogFairiesEvent.TrySpawningFairies
TrySpawningFairies()
void MysticLogFairiesEvent.TrySpawningFairies () inline private
     {
         if (Main.maxRaining > 0f || Main.bloodMoon || NPC.MoonLordCountdown > 0 || Main.snowMoon || Main.pumpkinMoon || Main.invasionType > 0 || _stumpCoords.Count == 0)
         {
             return;
         }
         int oneOverSpawnChance = GetOneOverSpawnChance();
         bool flag = false;
         for (int i = 0; i < Main.dayRate; i++)
         {
             if (Main.rand.Next(oneOverSpawnChance) == 0)
             {
                 flag = true;
                 break;
             }
         }
         if (!flag)
         {
             return;
         }
         int index = Main.rand.Next(_stumpCoords.Count);
         Point p = _stumpCoords[index];
         Vector2 vector = p.ToWorldCoordinates(24f);
         vector.Y -= 50f;
         if (WorldGen.PlayerLOS(p.X, p.Y))
         {
             return;
         }
         int num = Main.rand.Next(1, 4);
         if (Main.rand.Next(7) == 0)
         {
             num++;
         }
         int num2 = Utils.SelectRandom(Main.rand, new short[3] { 585, 584, 583 });
         for (int j = 0; j < num; j++)
         {
             num2 = Utils.SelectRandom(Main.rand, new short[3] { 585, 584, 583 });
             if (Main.tenthAnniversaryWorld && Main.rand.Next(4) != 0)
             {
                 num2 = 583;
             }
             int num3 = NPC.NewNPC(new EntitySource_WorldEvent(), (int)vector.X, (int)vector.Y, num2);
             if (Main.netMode == 2 && num3 < 200)
             {
                 NetMessage.SendData(23, -1, -1, null, num3);
             }
         }
         _canSpawnFairies = false;
     }
References _canSpawnFairies, _stumpCoords, Main.bloodMoon, Main.dayRate, GetOneOverSpawnChance(), Main.invasionType, Main.maxRaining, NPC.MoonLordCountdown, Main.netMode, NPC.NewNPC(), UnifiedRandom.Next(), WorldGen.PlayerLOS(), Main.pumpkinMoon, Main.rand, NetMessage.SendData(), Main.snowMoon, and Main.tenthAnniversaryWorld.
Referenced by UpdateTime().