Terraria: Terraria.GameContent.RGB.EyeOfCthulhuShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.EyeOfCthulhuShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Invalid comparison between Unknown and I4
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        if ((int)device.Type != 0 && (int)device.Type != 6)
        {
            ProcessLowDetail(device, fragment, quality, time);
            return;
        }
        float num = time * 0.2f % 2f;
        int num2 = 1;
        if (num > 1f)
        {
            num = 2f - num;
            num2 = -1;
        }
        Vector2 vector = new Vector2(num * 7f - 3.5f, 0f) + fragment.CanvasCenter;
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Vector4 vector2 = _backgroundColor;
            Vector2 vector3 = canvasPositionOfIndex - vector;
            float num3 = vector3.Length();
            if (num3 < 0.5f)
            {
                float amount = 1f - MathHelper.Clamp((num3 - 0.5f + 0.2f) / 0.2f, 0f, 1f);
                float num4 = MathHelper.Clamp((vector3.X + 0.5f - 0.2f) / 0.6f, 0f, 1f);
                if (num2 == 1)
                {
                    num4 = 1f - num4;
                }
                Vector4 value = Vector4.Lerp(_eyeColor, _veinColor, num4);
                vector2 = Vector4.Lerp(vector2, value, amount);
            }
            fragment.SetColor(i, vector2);
        }
    }
References Terraria.GameContent.RGB.EyeOfCthulhuShader._backgroundColor, Terraria.GameContent.RGB.EyeOfCthulhuShader._eyeColor, Terraria.GameContent.RGB.EyeOfCthulhuShader._veinColor, ReLogic.Peripherals.RGB.Fragment.CanvasCenter, ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Terraria.GameContent.RGB.EyeOfCthulhuShader.ProcessLowDetail(), ReLogic.Peripherals.RGB.Fragment.SetColor(), and ReLogic.Peripherals.RGB.RgbDevice.Type.