Terraria: BigProgressBarSystem.TryFindingNPCToTrack
TryFindingNPCToTrack()
void BigProgressBarSystem.TryFindingNPCToTrack () inline private
     {
         Rectangle value = new Rectangle((int)Main.screenPosition.X, (int)Main.screenPosition.Y, Main.screenWidth, Main.screenHeight);
         value.Inflate(5000, 5000);
         float num = float.PositiveInfinity;
         for (int i = 0; i < 200; i++)
         {
             NPC nPC = Main.npc[i];
             if (nPC.active && nPC.Hitbox.Intersects(value))
             {
                 float num2 = nPC.Distance(Main.LocalPlayer.Center);
                 if (num > num2 && TryTracking(i))
                 {
                     num = num2;
                 }
             }
         }
     }
References Entity.active, Entity.Center, Entity.Distance(), Entity.Hitbox, Main.LocalPlayer, Main.npc, Main.screenHeight, Main.screenPosition, Main.screenWidth, and TryTracking().
Referenced by Update().