Terraria: System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart
WorkerThreadStart()
static void System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart () inline static private
Definition at line 1005 of file PortableThreadPool.cs.
        {
            Thread.CurrentThread.SetThreadPoolWorkerThreadName();
            PortableThreadPool threadPoolInstance = ThreadPoolInstance;
            if (NativeRuntimeEventSource.Log.IsEnabled())
            {
                NativeRuntimeEventSource.Log.ThreadPoolWorkerThreadStart((uint)threadPoolInstance._separated.counts.VolatileRead().NumExistingThreads, 0u, 0);
            }
            LowLevelLock threadAdjustmentLock = threadPoolInstance._threadAdjustmentLock;
            LowLevelLifoSemaphore lowLevelLifoSemaphore = s_semaphore;
            while (true)
            {
                bool spinWait = true;
                while (lowLevelLifoSemaphore.Wait(20000, spinWait))
                {
                    bool flag = false;
                    while (TakeActiveRequest(threadPoolInstance))
                    {
                        threadPoolInstance._separated.lastDequeueTime = Environment.TickCount;
                        if (!ThreadPoolWorkQueue.Dispatch())
{
                            flag = true;
                            break;
                        }
                        if (threadPoolInstance._separated.numRequestedWorkers <= 0)
{
                            break;
                        }
                        Thread.UninterruptibleSleep0();
                        if (!Environment.IsSingleProcessor)
{
                            Thread.SpinWait(1);
                        }
                    }
                    spinWait = !flag;
                    if (!flag)
                    {
                        RemoveWorkingWorker(threadPoolInstance);
                    }
                }
                threadAdjustmentLock.Acquire();
                try
                {
                    ThreadCounts threadCounts = threadPoolInstance._separated.counts;
                    while (true)
                    {
                        short numExistingThreads = threadCounts.NumExistingThreads;
                        if (numExistingThreads <= threadCounts.NumProcessingWork)
{
                            break;
                        }
                        ThreadCounts newCounts = threadCounts;
                        newCounts.SubtractNumExistingThreads(1);
                        short num = (short)(numExistingThreads - 1);
                        short newThreadCount = (newCounts.NumThreadsGoal = Math.Max(threadPoolInstance.MinThreadsGoal, Math.Min(num, threadCounts.NumThreadsGoal)));
                        ThreadCounts threadCounts2 = threadPoolInstance._separated.counts.InterlockedCompareExchange(newCounts, threadCounts);
                        if (threadCounts2 == threadCounts)
{
                            HillClimbing.ThreadPoolHillClimber.ForceChange(newThreadCount, HillClimbing.StateOrTransition.ThreadTimedOut);
                            if (NativeRuntimeEventSource.Log.IsEnabled())
{
                                NativeRuntimeEventSource.Log.ThreadPoolWorkerThreadStop((uint)num, 0u, 0);
                            }
                            return;
                        }
                        threadCounts = threadCounts2;
                    }
                }
                finally
                {
                    threadAdjustmentLock.Release();
                }
            }
        }
References System.Threading.PortableThreadPool._separated, System.Threading.PortableThreadPool._threadAdjustmentLock, System.Threading.LowLevelLock.Acquire(), System.Threading.PortableThreadPool.CacheLineSeparated.counts, System.Threading.Thread.CurrentThread, System.Threading.ThreadPoolWorkQueue.Dispatch(), System.Threading.PortableThreadPool.ThreadCounts.InterlockedCompareExchange(), System.Environment.IsSingleProcessor, System.Diagnostics.Tracing.NativeRuntimeEventSource.Log, System.Math.Max(), System.Math.Min(), System.Threading.PortableThreadPool.MinThreadsGoal, System.Threading.PortableThreadPool.ThreadCounts.NumExistingThreads, System.Threading.PortableThreadPool.ThreadCounts.NumProcessingWork, System.Threading.PortableThreadPool.CacheLineSeparated.numRequestedWorkers, System.Threading.PortableThreadPool.ThreadCounts.NumThreadsGoal, System.Threading.LowLevelLock.Release(), System.Threading.PortableThreadPool.WorkerThread.RemoveWorkingWorker(), System.Threading.PortableThreadPool.WorkerThread.s_semaphore, System.Threading.Thread.SpinWait(), System.Threading.PortableThreadPool.ThreadCounts.SubtractNumExistingThreads(), System.Threading.PortableThreadPool.WorkerThread.TakeActiveRequest(), System.Threading.PortableThreadPool.HillClimbing.ThreadPoolHillClimber, System.Threading.PortableThreadPool.ThreadPoolInstance, System.Environment.TickCount, System.Threading.Thread.UninterruptibleSleep0(), System.Threading.PortableThreadPool.ThreadCounts.VolatileRead(), and System.Threading.LowLevelLifoSemaphore.Wait().