Terraria: System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker
MaybeAddWorkingWorker()
static void System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker (PortableThreadPool threadPoolInstance) inline static package
Definition at line 1089 of file PortableThreadPool.cs.
        {
            ThreadCounts threadCounts = threadPoolInstance._separated.counts;
            short numProcessingWork;
            short num;
            short numExistingThreads;
            short num2;
            while (true)
            {
                numProcessingWork = threadCounts.NumProcessingWork;
                if (numProcessingWork >= threadCounts.NumThreadsGoal)
                {
                    return;
                }
                num = (short)(numProcessingWork + 1);
                numExistingThreads = threadCounts.NumExistingThreads;
                num2 = Math.Max(numExistingThreads, num);
                ThreadCounts newCounts = threadCounts;
                newCounts.NumProcessingWork = num;
                newCounts.NumExistingThreads = num2;
                ThreadCounts threadCounts2 = threadPoolInstance._separated.counts.InterlockedCompareExchange(newCounts, threadCounts);
                if (threadCounts2 == threadCounts)
                {
                    break;
                }
                threadCounts = threadCounts2;
            }
            int num3 = num2 - numExistingThreads;
            int num4 = num - numProcessingWork;
            if (num4 > 0)
            {
                s_semaphore.Release(num4);
            }
            while (num3 > 0)
            {
                if (TryCreateWorkerThread())
                {
                    num3--;
                    continue;
                }
                threadCounts = threadPoolInstance._separated.counts;
                while (true)
                {
                    ThreadCounts newCounts2 = threadCounts;
                    newCounts2.SubtractNumProcessingWork((short)num3);
                    newCounts2.SubtractNumExistingThreads((short)num3);
                    ThreadCounts threadCounts3 = threadPoolInstance._separated.counts.InterlockedCompareExchange(newCounts2, threadCounts);
                    if (!(threadCounts3 == threadCounts))
                    {
                        threadCounts = threadCounts3;
                        continue;
                    }
                    break;
                }
                break;
            }
        }
References System.Threading.PortableThreadPool._separated, System.Threading.PortableThreadPool.CacheLineSeparated.counts, System.Threading.PortableThreadPool.ThreadCounts.InterlockedCompareExchange(), System.Math.Max(), System.Threading.PortableThreadPool.ThreadCounts.NumExistingThreads, System.Threading.PortableThreadPool.ThreadCounts.NumProcessingWork, System.Threading.PortableThreadPool.ThreadCounts.NumThreadsGoal, System.Threading.PortableThreadPool.WorkerThread.s_semaphore, System.Threading.PortableThreadPool.ThreadCounts.SubtractNumExistingThreads(), System.Threading.PortableThreadPool.ThreadCounts.SubtractNumProcessingWork(), and System.Threading.PortableThreadPool.WorkerThread.TryCreateWorkerThread().
Referenced by System.Threading.PortableThreadPool.AdjustMaxWorkersActive(), System.Threading.PortableThreadPool.GateThread.GateThreadStart(), System.Threading.PortableThreadPool.PerformBlockingAdjustment(), System.Threading.PortableThreadPool.WorkerThread.RemoveWorkingWorker(), System.Threading.PortableThreadPool.RequestWorker(), and System.Threading.PortableThreadPool.SetMinThreads().