Terraria: System.Data.Index.ApplyChangeAction
ApplyChangeAction()
void System.Data.Index.ApplyChangeAction (int record, int action, int changeRecord) inline private
Definition at line 236 of file Index.cs.
    {
        if (action == 0)
        {
            return;
        }
        if (action > 0)
        {
            if (AcceptRecord(record))
            {
                InsertRecord(record, fireEvent: true);
            }
        }
        else if (_comparison != null && -1 != record)
        {
            DeleteRecord(GetIndex(record, changeRecord));
        }
        else
        {
            DeleteRecord(GetIndex(record));
        }
    }
References System.Data.Index._comparison, System.Data.Index.AcceptRecord(), System.action, System.Data.Index.DeleteRecord(), System.Data.Index.GetIndex(), and System.Data.Index.InsertRecord().
Referenced by System.Data.Index.RecordStateChanged(), and System.Data.Index.RecordStateChanged().