Terraria: System.Data.Index.DeleteRecord
DeleteRecord() [1/2]
void System.Data.Index.DeleteRecord (int recordIndex) inline private
Definition at line 346 of file Index.cs.
    {
        DeleteRecord(recordIndex, fireEvent: true);
    }
References System.Data.Index.DeleteRecord().
Referenced by System.Data.Index.ApplyChangeAction(), System.Data.Index.DeleteRecord(), and System.Data.Index.DeleteRecordFromIndex().