Terraria: System.Data.Index.GetUniqueKeyValues
GetUniqueKeyValues() [1/2]
object[] System.Data.Index.GetUniqueKeyValues () inline
Definition at line 408 of file Index.cs.
    {
        if (_indexFields == null || _indexFields.Length == 0)
        {
            return Array.Empty<object>();
        }
        List<object[]> list = new List<object[]>();
        GetUniqueKeyValues(list, _records.root);
        return list.ToArray();
    }
References System.Data.Index._indexFields, System.Data.Index._records, System.Data.Index.GetUniqueKeyValues(), System.list, and System.Data.RBTree< K >.root.
Referenced by System.Data.ForeignKeyConstraint.CanEnableConstraint(), System.Data.Index.GetUniqueKeyValues(), System.Data.Index.GetUniqueKeyValues(), System.Data.ForeignKeyConstraint.IsConstraintViolated(), and System.Data.UniqueConstraint.IsConstraintViolated().