Terraria: System.Data.Index.AddRef
AddRef()
void System.Data.Index.AddRef () inline
Definition at line 196 of file Index.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.Index.AddRef|API> {0}", ObjectID);
        _table._indexesLock.EnterWriteLock();
        try
        {
            if (_refCount == 0)
            {
                _table.ShadowIndexCopy();
                _table._indexes.Add(this);
            }
            _refCount++;
        }
        finally
        {
            _table._indexesLock.ExitWriteLock();
        }
    }
References System.Data.DataTable._indexes, System.Data.DataTable._indexesLock, System.Data.Index._refCount, System.Data.Index._table, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.ReaderWriterLockSlim.EnterWriteLock(), System.Threading.ReaderWriterLockSlim.ExitWriteLock(), System.Data.DataCommonEventSource.Log, System.Data.Index.ObjectID, and System.Data.DataTable.ShadowIndexCopy().
Referenced by System.Data.DataRelationCollection.DataSetRelationCollection.AddCore(), System.Data.DataTable.BeginLoadData(), System.Data.UniqueConstraint.ConstraintIndexInitialize(), System.Data.Select.CreateIndex(), System.Data.DataView.Find(), and System.Data.DataTable.LoadDataRow().