Terraria: System.Data.Index.FindRecords< TKey, TRow >
FindRecords< TKey, TRow >()
Range System.Data.Index.FindRecords< TKey, TRow > (ComparisonBySelector< TKey, TRow > comparison, TKey key) inline package
Type Constraints
TRow : DataRow
Definition at line 535 of file Index.cs.
                                                                                                             : DataRow
    {
        int num = _records.root;
        while (num != 0)
        {
            int num2 = comparison(key, (TRow)_table._recordManager[_records.Key(num)]);
            if (num2 == 0)
            {
                break;
            }
            num = ((num2 >= 0) ? _records.Right(num) : _records.Left(num));
        }
        return GetRangeFromNode(num);
    }
References System.Data.DataTable._recordManager, System.Data.Index._records, System.Data.Index._table, System.comparison, System.Data.Index.GetRangeFromNode(), System.Data.RBTree< K >.Key(), System.key, System.Data.RBTree< K >.Left(), System.Data.RBTree< K >.Right(), and System.Data.RBTree< K >.root.