Terraria: System.Data.Index.RemoveRef
RemoveRef()
int System.Data.Index.RemoveRef () inline
Definition at line 215 of file Index.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.Index.RemoveRef|API> {0}", ObjectID);
        _table._indexesLock.EnterWriteLock();
        int result;
        try
        {
            result = --_refCount;
            if (_refCount <= 0)
            {
                _table.ShadowIndexCopy();
                _table._indexes.Remove(this);
            }
        }
        finally
        {
            _table._indexesLock.ExitWriteLock();
        }
        return result;
    }
References System.Data.DataTable._indexes, System.Data.DataTable._indexesLock, System.Data.Index._refCount, System.Data.Index._table, System.Threading.ReaderWriterLockSlim.EnterWriteLock(), System.Threading.ReaderWriterLockSlim.ExitWriteLock(), System.Data.DataCommonEventSource.Log, System.Data.Index.ObjectID, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.Data.DataTable.ShadowIndexCopy().
Referenced by System.Data.UniqueConstraint.ConstraintIndexClear(), System.Data.DataTable.EndLoadData(), System.Data.DataRelationCollection.DataSetRelationCollection.RemoveCore(), and System.Data.DataColumn.SetOrdinalInternal().