Terraria: System.Data.Index.RecordStateChanged
RecordStateChanged() [1/2]
void System.Data.Index.RecordStateChanged (int oldRecord, DataViewRowState oldOldState, DataViewRowState oldNewState, int newRecord, DataViewRowState newOldState, DataViewRowState newNewState) inline
Definition at line 816 of file Index.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.Index.RecordStateChanged|API> {0}, oldRecord={1}, oldOldState={2}, oldNewState={3}, newRecord={4}, newOldState={5}, newNewState={6}", ObjectID, oldRecord, oldOldState, oldNewState, newRecord, newOldState, newNewState);
        int changeAction = GetChangeAction(oldOldState, oldNewState);
        int changeAction2 = GetChangeAction(newOldState, newNewState);
        if (changeAction == -1 && changeAction2 == 1 && AcceptRecord(newRecord))
        {
            int num = ((_comparison == null || changeAction >= 0) ? GetIndex(oldRecord) : GetIndex(oldRecord, GetReplaceAction(oldOldState)));
            if (_comparison == null && num != -1 && CompareRecords(oldRecord, newRecord) == 0)
            {
                _records.UpdateNodeKey(oldRecord, newRecord);
                int index = GetIndex(newRecord);
                OnListChanged(ListChangedType.ItemChanged, index, index);
                return;
            }
            _suspendEvents = true;
            if (num != -1)
            {
                _records.DeleteByIndex(num);
                _recordCount--;
            }
            _records.Insert(newRecord);
            _recordCount++;
            _suspendEvents = false;
            int index2 = GetIndex(newRecord);
            if (num == index2)
            {
                OnListChanged(ListChangedType.ItemChanged, index2, num);
            }
            else if (num == -1)
            {
                MaintainDataView(ListChangedType.ItemAdded, newRecord, trackAddRemove: false);
                OnListChanged(ListChangedType.ItemAdded, GetIndex(newRecord));
            }
            else
            {
                OnListChanged(ListChangedType.ItemMoved, index2, num);
            }
        }
        else
        {
            ApplyChangeAction(oldRecord, changeAction, GetReplaceAction(oldOldState));
            ApplyChangeAction(newRecord, changeAction2, GetReplaceAction(newOldState));
        }
    }
References System.Data.Index._comparison, System.Data.Index._recordCount, System.Data.Index._records, System.Data.Index._suspendEvents, System.Data.Index.AcceptRecord(), System.Data.Index.ApplyChangeAction(), System.Data.Index.CompareRecords(), System.Data.RBTree< K >.DeleteByIndex(), System.Data.Index.GetChangeAction(), System.Data.Index.GetIndex(), System.Data.Index.GetReplaceAction(), System.index, System.index2, System.Data.RBTree< K >.Insert(), System.Data.DataCommonEventSource.Log, System.Data.Index.MaintainDataView(), System.Data.Index.ObjectID, System.Data.Index.OnListChanged(), and System.Data.RBTree< K >.UpdateNodeKey().