Terraria: System.Data.Index.InsertRecord
InsertRecord()
int System.Data.Index.InsertRecord (int record, bool fireEvent) inline private
Definition at line 690 of file Index.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.Index.InsertRecord|INFO> {0}, record={1}, fireEvent={2}", ObjectID, record, fireEvent);
        bool append = false;
        if (_indexFields.Length == 0 && _table != null)
        {
            DataRow row = _table._recordManager[record];
            append = _table.Rows.IndexOf(row) + 1 == _table.Rows.Count;
        }
        int node = _records.InsertAt(-1, record, append);
        _recordCount++;
        MaintainDataView(ListChangedType.ItemAdded, record, !fireEvent);
        if (fireEvent)
        {
            if (DoListChanged)
            {
                OnListChanged(ListChangedType.ItemAdded, _records.GetIndexByNode(node));
            }
            return 0;
        }
        return _records.GetIndexByNode(node);
    }
References System.Data.Index._indexFields, System.Data.Index._recordCount, System.Data.DataTable._recordManager, System.Data.Index._records, System.Data.Index._table, System.Data.DataRowCollection.Count, System.Data.Index.DoListChanged, System.Data.RBTree< K >.GetIndexByNode(), System.Data.DataRowCollection.IndexOf(), System.Data.RBTree< K >.InsertAt(), System.Data.DataCommonEventSource.Log, System.Data.Index.MaintainDataView(), System.Data.Index.ObjectID, System.Data.Index.OnListChanged(), and System.Data.DataTable.Rows.
Referenced by System.Data.Index.ApplyChangeAction(), and System.Data.Index.InsertRecordToIndex().