Terraria: System.Data.Index.FindRecordByKey
FindRecordByKey() [1/2]
int System.Data.Index.FindRecordByKey (object key) inline
Definition at line 429 of file Index.cs.
    {
        int num = FindNodeByKey(key);
        if (num != 0)
        {
            return _records.GetIndexByNode(num);
        }
        return -1;
    }
References System.Data.Index._records, System.Data.Index.FindNodeByKey(), System.Data.RBTree< K >.GetIndexByNode(), and System.key.
Referenced by System.Data.DataView.FindByKey(), and System.Data.DataView.FindByKey().