Terraria: System.Data.Index.MaintainDataView
MaintainDataView()
void System.Data.Index.MaintainDataView (ListChangedType changedType, int record, bool trackAddRemove) inline private
Definition at line 756 of file Index.cs.
    {
        _listeners.Notify(changedType, (0 <= record) ? _table._recordManager[record] : null, trackAddRemove, delegate(DataViewListener listener, ListChangedType type, DataRow row, bool track)
        {
            listener.MaintainDataView(changedType, row, track);
        });
    }
References System.Data.Index._listeners, System.Data.DataTable._recordManager, System.Data.Index._table, System.Data.DataViewListener.MaintainDataView(), and System.type.
Referenced by System.Data.Index.DeleteRecord(), System.Data.Index.InsertRecord(), System.Data.Index.RecordStateChanged(), and System.Data.Index.Reset().