Terraria: System.Data.Index.GetRangeFromNode
GetRangeFromNode()
Range System.Data.Index.GetRangeFromNode (int nodeId) inline private
Definition at line 550 of file Index.cs.
    {
        if (nodeId == 0)
        {
            return default(Range);
        }
        int indexByNode = _records.GetIndexByNode(nodeId);
        if (_records.Next(nodeId) == 0)
        {
            return new Range(indexByNode, indexByNode);
        }
        int num = _records.SubTreeSize(_records.Next(nodeId));
        return new Range(indexByNode, indexByNode + num - 1);
    }
References System.Data.Index._records, System.Data.RBTree< K >.GetIndexByNode(), System.Data.RBTree< K >.Next(), and System.Data.RBTree< K >.SubTreeSize().
Referenced by System.Data.Index.FindRecords(), System.Data.Index.FindRecords(), and System.Data.Index.FindRecords< TKey, TRow >().