Terraria: System.Data.Index.CompareRecords
CompareRecords()
int System.Data.Index.CompareRecords (int record1, int record2) inline private
Definition at line 264 of file Index.cs.
    {
        if (_comparison != null)
        {
            return CompareDataRows(record1, record2);
        }
        if (_indexFields.Length != 0)
        {
            for (int i = 0; i < _indexFields.Length; i++)
            {
                int num = _indexFields[i].Column.Compare(record1, record2);
                if (num != 0)
                {
                    if (!_indexFields[i].IsDescending)
                    {
                        return num;
                    }
                    return -num;
                }
            }
            return 0;
        }
        DataRow dataRow = _table._recordManager[record1];
        DataRow dataRow2 = _table._recordManager[record2];
        DataRow row = dataRow;
        DataRow row2 = dataRow2;
        return _table.Rows.IndexOf(row).CompareTo(_table.Rows.IndexOf(row2));
    }
References System.Data.Index._comparison, System.Data.Index._indexFields, System.Data.DataTable._recordManager, System.Data.Index._table, System.Data.IndexField.Column, System.Data.DataColumn.Compare(), System.Data.Index.CompareDataRows(), System.Data.DataRowCollection.IndexOf(), and System.Data.DataTable.Rows.
Referenced by System.Data.Index.IndexTree.CompareNode(), System.Data.Index.FindNodeByKeyRecord(), and System.Data.Index.RecordStateChanged().