Terraria: Terraria.GameContent.Skies.LanternSky.GenerateLanterns
GenerateLanterns()
void Terraria.GameContent.Skies.LanternSky.GenerateLanterns (bool onlyMissing) inline private
Definition at line 83 of file LanternSky.cs.
    {
        if (!onlyMissing)
        {
            _lanterns = new Lantern[Main.maxTilesY / 4];
        }
        for (int i = 0; i < _lanterns.Length; i++)
        {
            if (!onlyMissing || !_lanterns[i].Active)
            {
                int num = (int)((double)Main.screenPosition.Y * 0.7 - (double)Main.screenHeight);
                int minValue = (int)((double)num - Main.worldSurface * 16.0);
                _lanterns[i].Position = new Vector2(_random.Next(0, Main.maxTilesX) * 16, _random.Next(minValue, num));
                ResetLantern(i);
                _lanterns[i].Active = true;
            }
        }
        _lanternsDrawing = _lanterns.Length;
    }
References Terraria.GameContent.Skies.LanternSky._lanterns, Terraria.GameContent.Skies.LanternSky._lanternsDrawing, Terraria.GameContent.Skies.LanternSky._random, Terraria.GameContent.Skies.LanternSky.Lantern.Active, Terraria.Graphics.Effects.Active, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Skies.LanternSky.Lantern.Position, Terraria.GameContent.Skies.LanternSky.ResetLantern(), Terraria.Main.screenHeight, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.Skies.LanternSky.Activate(), and Terraria.GameContent.Skies.LanternSky.OnLoad().