Terraria: System.Data.Index.FindNodeByKeyRecord
FindNodeByKeyRecord()
int System.Data.Index.FindNodeByKeyRecord (int record) inline private
Definition at line 516 of file Index.cs.
    {
        int num = _records.root;
        if (num != 0)
        {
            num = _records.root;
            while (num != 0)
            {
                int num2 = CompareRecords(_records.Key(num), record);
                if (num2 == 0)
                {
                    break;
                }
                num = ((num2 <= 0) ? _records.Right(num) : _records.Left(num));
            }
        }
        return num;
    }
References System.Data.Index._records, System.Data.Index.CompareRecords(), System.Data.RBTree< K >.Key(), System.Data.RBTree< K >.Left(), System.Data.RBTree< K >.Right(), and System.Data.RBTree< K >.root.
Referenced by System.Data.Index.IsKeyRecordInIndex().