Terraria: System.Data.Index.FindRecords
FindRecords() [1/2]
Range System.Data.Index.FindRecords (object key) inline
Definition at line 565 of file Index.cs.
    {
        int nodeId = FindNodeByKey(key);
        return GetRangeFromNode(nodeId);
    }
References System.Data.Index.FindNodeByKey(), System.Data.Index.GetRangeFromNode(), and System.key.
Referenced by System.Data.ForeignKeyConstraint.CascadeCommit(), System.Data.ForeignKeyConstraint.CascadeDelete(), System.Data.ForeignKeyConstraint.CascadeRollback(), System.Data.ForeignKeyConstraint.CascadeUpdate(), System.Data.DataView.FindRecords< TKey, TRow >(), System.Data.DataView.FindRowsByKey(), System.Data.Index.GetRows(), System.Data.ForeignKeyConstraint.IsConstraintViolated(), and System.Data.UniqueConstraint.IsConstraintViolated().