Terraria: Terraria.GameContent.Skies.LanternSky.ResetLantern
ResetLantern()
void Terraria.GameContent.Skies.LanternSky.ResetLantern (int i) inline
Definition at line 103 of file LanternSky.cs.
    {
        _lanterns[i].Depth = (1f - (float)i / (float)_lanterns.Length) * 4.4f + 1.6f;
        _lanterns[i].Speed = -1.5f - 2.5f * (float)_random.NextDouble();
        _lanterns[i].Texture = _texture.Value;
        _lanterns[i].Variant = _random.Next(3);
        _lanterns[i].TimeUntilFloat = (int)((float)(2000 + _random.Next(1200)) * 2f);
        _lanterns[i].TimeUntilFloatMax = _lanterns[i].TimeUntilFloat;
    }
References Terraria.GameContent.Skies.LanternSky._lanterns, Terraria.GameContent.Skies.LanternSky._random, Terraria.GameContent.Skies.LanternSky._texture, Terraria.GameContent.Skies.LanternSky.Lantern.Depth, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.GameContent.Skies.LanternSky.Lantern.Speed, Terraria.GameContent.Skies.LanternSky.Lantern.Texture, Terraria.GameContent.Skies.LanternSky.Lantern.TimeUntilFloat, Terraria.GameContent.Skies.LanternSky.Lantern.TimeUntilFloatMax, ReLogic.Content.Asset< T >.Value, and Terraria.GameContent.Skies.LanternSky.Lantern.Variant.
Referenced by Terraria.GameContent.Skies.LanternSky.GenerateLanterns(), and Terraria.GameContent.Skies.LanternSky.Update().