Terraria: System.Data.Index.InitRecords
InitRecords()
void System.Data.Index.InitRecords (IFilter filter) inline private
Definition at line 634 of file Index.cs.
    {
        DataViewRowState recordStates = _recordStates;
        bool append = _indexFields.Length == 0;
        _records = new IndexTree(this);
        _recordCount = 0;
        foreach (DataRow row in _table.Rows)
        {
            int num = -1;
            if (row._oldRecord == row._newRecord)
            {
                if ((recordStates & DataViewRowState.Unchanged) != 0)
                {
                    num = row._oldRecord;
                }
            }
            else if (row._oldRecord == -1)
            {
                if ((recordStates & DataViewRowState.Added) != 0)
                {
                    num = row._newRecord;
                }
            }
            else if (row._newRecord == -1)
            {
                if ((recordStates & DataViewRowState.Deleted) != 0)
                {
                    num = row._oldRecord;
                }
            }
            else if ((recordStates & DataViewRowState.ModifiedCurrent) != 0)
            {
                num = row._newRecord;
            }
            else if ((recordStates & DataViewRowState.ModifiedOriginal) != 0)
            {
                num = row._oldRecord;
            }
            if (num != -1 && AcceptRecord(num, filter))
            {
                _records.InsertAt(-1, num, append);
                _recordCount++;
            }
        }
    }
References System.Data.Index._recordCount, System.Data.Index._records, System.Data.Index._recordStates, System.Data.Index._table, System.Data.Index.AcceptRecord(), System.Data.RBTree< K >.InsertAt(), and System.Data.DataTable.Rows.
Referenced by System.Data.Index.Index(), and System.Data.Index.Reset().