Terraria: System.Data.Index.FindNodeByKey
FindNodeByKey()
int System.Data.Index.FindNodeByKey (object originalKey) inline private
Definition at line 449 of file Index.cs.
    {
        if (_indexFields.Length != 1)
        {
            throw ExceptionBuilder.IndexKeyLength(_indexFields.Length, 1);
        }
        int num = _records.root;
        if (num != 0)
        {
            DataColumn column = _indexFields[0].Column;
            object value = column.ConvertValue(originalKey);
            num = _records.root;
            if (_indexFields[0].IsDescending)
            {
                while (num != 0)
                {
                    int num2 = column.CompareValueTo(_records.Key(num), value);
                    if (num2 == 0)
                    {
                        break;
                    }
                    num = ((num2 >= 0) ? _records.Right(num) : _records.Left(num));
                }
            }
            else
            {
                while (num != 0)
                {
                    int num2 = column.CompareValueTo(_records.Key(num), value);
                    if (num2 == 0)
                    {
                        break;
                    }
                    num = ((num2 <= 0) ? _records.Right(num) : _records.Left(num));
                }
            }
        }
        return num;
    }
References System.Data.Index._indexFields, System.Data.Index._records, System.Data.IndexField.Column, System.Data.ExceptionBuilder.IndexKeyLength(), System.Data.RBTree< K >.Key(), System.Data.RBTree< K >.Left(), System.Data.RBTree< K >.Right(), System.Data.RBTree< K >.root, and System.value.
Referenced by System.Data.Index.FindRecordByKey(), System.Data.Index.FindRecords(), and System.Data.Index.IsKeyInIndex().