Terraria: System.Data.Index.GetRecord
GetRecord()
int System.Data.Index.GetRecord (int recordIndex) inline
Definition at line 148 of file Index.cs.
    {
        return _records[recordIndex];
    }
References System.Data.Index._records.
Referenced by System.Data.Select.FindFirstMatchingRecord(), System.Data.Select.FindLastMatchingRecord(), System.Data.DataView.GetRecord(), System.Data.Index.GetRow(), and System.Data.DataTable.LoadDataRow().