Terraria: System.Data.Index.GetEnumerator
GetEnumerator()
RBTree< int >.RBTreeEnumerator System.Data.Index.GetEnumerator (int startIndex) inline
Definition at line 366 of file Index.cs.
    {
        return new RBTree<int>.RBTreeEnumerator(_records, startIndex);
    }
References System.Data.Index._records, and System.startIndex.
Referenced by System.Data.DataView.CopyTo(), System.Data.DataView.CopyTo(), System.Data.Select.GetLinearFilteredRecords(), System.Data.Select.GetLinearFilteredRows(), System.Data.Index.GetRows(), and System.Data.DataView.ResetRowViewCache().