Terraria: System.IO.Win32Marshal.GetExceptionForWin32Error
GetExceptionForWin32Error() [6/6]
static Exception System.IO.Win32Marshal.GetExceptionForWin32Error (int errorCode, string path = "") inline static package
Definition at line 12 of file Win32Marshal.cs.
    {
        switch (errorCode)
        {
        case 2:
            return new FileNotFoundException(string.IsNullOrEmpty(path) ? SR.IO_FileNotFound : SR.Format(SR.IO_FileNotFound_FileName, path), path);
        case 3:
            return new DirectoryNotFoundException(string.IsNullOrEmpty(path) ? SR.IO_PathNotFound_NoPathName : SR.Format(SR.IO_PathNotFound_Path, path));
        case 5:
            return new UnauthorizedAccessException(string.IsNullOrEmpty(path) ? SR.UnauthorizedAccess_IODenied_NoPathName : SR.Format(SR.UnauthorizedAccess_IODenied_Path, path));
        case 183:
            if (!string.IsNullOrEmpty(path))
            {
                return new IOException(SR.Format(SR.IO_AlreadyExists_Name, path), MakeHRFromErrorCode(errorCode));
            }
            break;
        case 206:
            return new PathTooLongException(string.IsNullOrEmpty(path) ? SR.IO_PathTooLong : SR.Format(SR.IO_PathTooLong_Path, path));
        case 32:
            return new IOException(string.IsNullOrEmpty(path) ? SR.IO_SharingViolation_NoFileName : SR.Format(SR.IO_SharingViolation_File, path), MakeHRFromErrorCode(errorCode));
        case 80:
            if (!string.IsNullOrEmpty(path))
            {
                return new IOException(SR.Format(SR.IO_FileExists_Name, path), MakeHRFromErrorCode(errorCode));
            }
            break;
        case 995:
            return new OperationCanceledException();
        }
        return new IOException(string.IsNullOrEmpty(path) ? GetMessage(errorCode) : (GetMessage(errorCode) + " : '" + path + "'"), MakeHRFromErrorCode(errorCode));
    }
References System.SR.Format(), System.IO.Win32Marshal.GetMessage(), System.SR.IO_AlreadyExists_Name, System.SR.IO_FileExists_Name, System.SR.IO_FileNotFound, System.SR.IO_FileNotFound_FileName, System.SR.IO_PathNotFound_NoPathName, System.SR.IO_PathNotFound_Path, System.SR.IO_PathTooLong, System.SR.IO_PathTooLong_Path, System.SR.IO_SharingViolation_File, System.SR.IO_SharingViolation_NoFileName, System.IO.Win32Marshal.MakeHRFromErrorCode(), System.SR.UnauthorizedAccess_IODenied_NoPathName, and System.SR.UnauthorizedAccess_IODenied_Path.