Terraria: TEHatRack.OnPlayerInteraction
OnPlayerInteraction()
static void TEHatRack.OnPlayerInteraction (Player player, int clickX, int clickY) inline static
     {
         int num = clickX;
         int num2 = clickY;
         num -= Main.tile[num, num2].frameX % 54 / 18;
         num2 -= Main.tile[num, num2].frameY / 18;
         int num3 = Find(num, num2);
         if (num3 != -1)
         {
             num2++;
             num++;
             TileEntity.BasicOpenCloseInteraction(player, num, num2, num3);
         }
     }
References TileEntity.BasicOpenCloseInteraction(), Find(), Tile.frameX, Tile.frameY, and Main.tile.
Referenced by Player.TileInteractionsUse().