Terraria: TEHatRack.IsBreakable
IsBreakable()
static bool TEHatRack.IsBreakable (int clickX, int clickY) inline static
     {
         int num = clickX;
         int num2 = clickY;
         num -= Main.tile[num, num2].frameX % 54 / 18;
         num2 -= Main.tile[num, num2].frameY / 18;
         int num3 = Find(num, num2);
         if (num3 != -1)
         {
             return !(TileEntity.ByID[num3] as TEHatRack).ContainsItems();
         }
         return true;
     }
References TEHatRack(), TileEntity.ByID, ContainsItems(), Find(), Tile.frameX, Tile.frameY, and Main.tile.
Referenced by WorldGen.CheckTileBreakability2_ShouldTileSurvive().