Terraria: GroupOptionButton.DrawSelf
DrawSelf()
override void GroupOptionButton< T >.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         if (_hovered)
         {
             if (!_soundedHover)
             {
                 SoundEngine.PlaySound(12);
             }
             _soundedHover = true;
         }
         else
         {
             _soundedHover = false;
         }
         CalculatedStyle dimensions = GetDimensions();
         Color color = _color;
         float num = _opacity;
         bool isSelected = IsSelected;
         if (_UseOverrideColors)
         {
             color = (isSelected ? _overridePickedColor : _overrideUnpickedColor);
             num = (isSelected ? _overrideOpacityPicked : _overrideOpacityUnpicked);
         }
         Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, Color.Lerp(Color.Black, color, FadeFromBlack) * num);
         if (isSelected && ShowHighlightWhenSelected)
         {
             Utils.DrawSplicedPanel(spriteBatch, _selectedBorderTexture.Value, (int)dimensions.X + 7, (int)dimensions.Y + 7, (int)dimensions.Width - 14, (int)dimensions.Height - 14, 10, 10, 10, 10, Color.Lerp(color, Color.White, _whiteLerp) * num);
         }
         if (_hovered)
         {
             Utils.DrawSplicedPanel(spriteBatch, _hoveredBorderTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, _borderColor);
         }
         if (_iconTexture != null)
         {
             Color color2 = Color.White;
             if (!_hovered && !isSelected)
             {
                 color2 = Color.Lerp(color, Color.White, _whiteLerp) * num;
             }
             spriteBatch.Draw(_iconTexture.Value, new Vector2(dimensions.X + 1f, dimensions.Y + 1f), color2);
         }
     }
References GroupOptionButton< T >._BasePanelTexture, GroupOptionButton< T >._borderColor, GroupOptionButton< T >._color, GroupOptionButton< T >._hovered, GroupOptionButton< T >._hoveredBorderTexture, GroupOptionButton< T >._iconTexture, GroupOptionButton< T >._opacity, GroupOptionButton< T >._overrideOpacityPicked, GroupOptionButton< T >._overrideOpacityUnpicked, GroupOptionButton< T >._overridePickedColor, GroupOptionButton< T >._overrideUnpickedColor, GroupOptionButton< T >._selectedBorderTexture, GroupOptionButton< T >._soundedHover, GroupOptionButton< T >._UseOverrideColors, GroupOptionButton< T >._whiteLerp, Color, Utils.DrawSplicedPanel(), GroupOptionButton< T >.FadeFromBlack, UIElement.GetDimensions(), CalculatedStyle.Height, GroupOptionButton< T >.IsSelected, SoundEngine.PlaySound(), GroupOptionButton< T >.ShowHighlightWhenSelected, Asset< T >.Value, CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.