Terraria: System.Xml.XmlBinaryWriterSession.PriorityDictionary.Clear
Clear()
void System.Xml.XmlBinaryWriterSession.PriorityDictionary< K, V >.Clear () inline
Definition at line 45 of file XmlBinaryWriterSession.cs.
        {
            _now = 0;
            _listCount = 0;
            Array.Clear(_list);
            if (_dictionary != null)
            {
                _dictionary.Clear();
            }
        }
References System.Xml.XmlBinaryWriterSession.PriorityDictionary< K, V >._dictionary, System.Xml.XmlBinaryWriterSession.PriorityDictionary< K, V >._list, System.Xml.XmlBinaryWriterSession.PriorityDictionary< K, V >._listCount, System.Xml.XmlBinaryWriterSession.PriorityDictionary< K, V >._now, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), and System.Array.Clear().
Referenced by System.Xml.XmlBinaryWriterSession.Reset().