Terraria: TileLightScanner.ApplyHellLight
ApplyHellLight()
void TileLightScanner.ApplyHellLight (Tile tile, int x, int y, ref Vector3 lightColor) inline private
     {
         float num = 0f;
         float num2 = 0f;
         float num3 = 0f;
         float num4 = 0.55f + (float)Math.Sin(Main.GlobalTimeWrappedHourly * 2f) * 0.08f;
         if ((!tile.active() || !Main.tileNoSunLight[tile.type] || ((tile.slope() != 0 || tile.halfBrick()) && Main.tile[x, y - 1].liquid == 0 && Main.tile[x, y + 1].liquid == 0 && Main.tile[x - 1, y].liquid == 0 && Main.tile[x + 1, y].liquid == 0)) && lightColor.X < num4 && (Main.wallLight[tile.wall] || tile.wall == 73 || tile.wall == 227 || (tile.invisibleWall() && !_drawInvisibleWalls)) && tile.liquid < 200 && (!tile.halfBrick() || Main.tile[x, y - 1].liquid < 200))
         {
             num = num4;
             num2 = num4 * 0.6f;
             num3 = num4 * 0.2f;
         }
         if ((!tile.active() || tile.halfBrick() || !Main.tileNoSunLight[tile.type]) && tile.wall >= 88 && tile.wall <= 93 && tile.liquid < byte.MaxValue)
         {
             num = num4;
             num2 = num4 * 0.6f;
             num3 = num4 * 0.2f;
             switch (tile.wall)
             {
             case 88:
                 num *= 0.9f;
                 num2 *= 0.15f;
                 num3 *= 0.9f;
                 break;
             case 89:
                 num *= 0.9f;
                 num2 *= 0.9f;
                 num3 *= 0.15f;
                 break;
             case 90:
                 num *= 0.15f;
                 num2 *= 0.15f;
                 num3 *= 0.9f;
                 break;
             case 91:
                 num *= 0.15f;
                 num2 *= 0.9f;
                 num3 *= 0.15f;
                 break;
             case 92:
                 num *= 0.9f;
                 num2 *= 0.15f;
                 num3 *= 0.15f;
                 break;
             case 93:
             {
                 float num5 = 0.2f;
                 float num6 = 0.7f - num5;
                 num *= num6 + (float)Main.DiscoR / 255f * num5;
                 num2 *= num6 + (float)Main.DiscoG / 255f * num5;
                 num3 *= num6 + (float)Main.DiscoB / 255f * num5;
                 break;
             }
             }
         }
         if (lightColor.X < num)
         {
             lightColor.X = num;
         }
         if (lightColor.Y < num2)
         {
             lightColor.Y = num2;
         }
         if (lightColor.Z < num3)
         {
             lightColor.Z = num3;
         }
     }
References Tile.active(), Main.DiscoB, Main.DiscoG, Main.DiscoR, Main.GlobalTimeWrappedHourly, Tile.halfBrick(), Tile.invisibleWall(), Tile.liquid, Tile.slope(), Main.tile, Main.tileNoSunLight, Tile.type, Tile.wall, and Main.wallLight.