Terraria: TileLightScanner.ApplyTileLight
ApplyTileLight()
void TileLightScanner.ApplyTileLight (Tile tile, int x, int y, ref FastRandom localRandom, ref Vector3 lightColor) inline private
References B, Main.cageFrames, Color, Tile.color(), Main.dayTime, Main.demonTorch, Main.DiscoB, Main.DiscoG, Main.DiscoR, Tile.frameX, Tile.frameY, G, PortalHelper.GetPortalColor(), LiquidRenderer.GetShimmerBaseColor(), Main.GlobalTimeWrappedHourly, Main.hslToRgb(), Tile.invisibleBlock(), Main.jellyfishCageMode, Main.moondialCooldown, Main.mouseTextColor, Main.myPlayer, WorldGen.paintColor(), R, Main.raining, Main.sundialCooldown, Main.tile, Main.tileLighted, Main.time, Main.timeForVisualEffects, TorchID.TorchColor(), and Tile.type.