Terraria: Terraria.ID.TileID.Sets.BasicChest
BasicChest
bool [] Terraria.ID.TileID.Sets.BasicChest = Factory.CreateBoolSet(21, 467) static
Definition at line 223 of file TileID.cs.
Referenced by Terraria.WorldGen.AllowsSandfall(), Terraria.NPC.BigMimicSummonCheck(), Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part2(), Terraria.Projectile.CanExplodeTile(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check3x1(), Terraria.WorldGen.CheckTileBreakability2_ShouldTileSurvive(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.Wiring.DeActive(), Terraria.Main.DrawInfoAccs(), Terraria.Wiring.HitWireSingle(), Terraria.WorldGen.IsAContainer(), Terraria.Player.IsInInteractionRangeToMultiTileHitbox(), Terraria.WorldGen.meteor(), Terraria.WorldGen.MineHouse(), Terraria.WorldGen.MoveReplaceTileAnchor(), Terraria.Chest.NearOtherChests(), Terraria.GameContent.Biomes.CaveHouseBiome.Place(), Terraria.WorldGen.PlaceSandTrap(), Terraria.Player.PlaceThing_ValidTileForReplacement(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.ReplaceTIle_DoActualReplacement(), Terraria.WorldGen.ReplaceTile_IsValidChest(), Terraria.WorldGen.ScoreRoom(), Terraria.WorldGen.TileFrame(), Terraria.Player.TileInteractionsCheckLongDistance(), and Terraria.Player.TileInteractionsUse().