Terraria: Terraria.ID.TileID.Sets.CanBeClearedDuringGeneration
CanBeClearedDuringGeneration
bool [] Terraria.ID.TileID.Sets.CanBeClearedDuringGeneration = Factory.CreateBoolSet(true, 396, 400, 401, 397, 398, 399, 404, 368, 367, 226, 237) static
Definition at line 229 of file TileID.cs.
Referenced by Terraria.WorldGen.CaveOpenater(), Terraria.WorldGen.Cavinator(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpotSingle(), Terraria.GameContent.Biomes.DeadMansChestBiome.IsAGoodSpot(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceBoulderTrapSpot(), Terraria.WorldGen.ScanTileColumnAndRemoveClumps(), Terraria.WorldGen.SpreadGrass(), Terraria.WorldGen.tileCounterNext(), and Terraria.WorldGen.TileRunner().