Terraria: Terraria.ID.TileID.Sets.IsATreeTrunk
IsATreeTrunk
bool [] Terraria.ID.TileID.Sets.IsATreeTrunk = Factory.CreateBoolSet(false, 5, 72, 583, 584, 585, 586, 587, 588, 589, 596, 616, 634) static
Referenced by Terraria.Projectile.AI_007_GrapplingHooks_CanTileBeLatchedOnTo(), Terraria.Lang.BuildMapAtlas(), Terraria.WorldGen.CanKillTile(), Terraria.TileObject.CanPlace(), Terraria.WorldGen.CheckTileBreakability(), Terraria.NPC.FindTreeBranch(), Terraria.WorldGen.GetTreeBottom(), Terraria.Player.IsBottomOfTreeTrunkNoRoots(), Terraria.WorldGen.IsTileReplacable(), Terraria.WorldGen.IsTreeType(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), and Terraria.GameContent.SmartCursorHelper.Step_Axe().