Terraria: Terraria.ID.TileID.Sets.NotReallySolid
NotReallySolid
bool [] Terraria.ID.TileID.Sets.NotReallySolid = Factory.CreateBoolSet(387, 388, 10) static
Definition at line 257 of file TileID.cs.
Referenced by Terraria.WorldGen.AnchorValid(), Terraria.TileObject.CanPlace(), Terraria.WorldGen.CheckBanner(), Terraria.Wiring.DeActive(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Terraria.WorldGen.PlaceTile(), Terraria.GameContent.SmartCursorHelper.Step_Torch(), and Terraria.GameContent.PortalHelper.SupportedNormal().