Terraria: System.UriBuilder.ToString
ToString()
override string System.UriBuilder.ToString () inline
Definition at line 303 of file UriBuilder.cs.
    {
        if (UserName.Length == 0 && Password.Length != 0)
        {
            throw new UriFormatException(System.SR.net_uri_BadUserPassword);
        }
        Span<char> initialBuffer = stackalloc char[512];
        System.Text.ValueStringBuilder valueStringBuilder = new System.Text.ValueStringBuilder(initialBuffer);
        string scheme = Scheme;
        string host = Host;
        if (scheme.Length != 0)
        {
            UriParser syntax = UriParser.GetSyntax(scheme);
            string s = ((syntax != null) ? ((syntax.InFact(UriSyntaxFlags.MustHaveAuthority) || (host.Length != 0 && syntax.NotAny(UriSyntaxFlags.MailToLikeUri) && syntax.InFact(UriSyntaxFlags.OptionalAuthority))) ? System.Uri.SchemeDelimiter : ":") : ((host.Length == 0) ? ":" : System.Uri.SchemeDelimiter));
            valueStringBuilder.Append(scheme);
            valueStringBuilder.Append(s);
        }
        string userName = UserName;
        if (userName.Length != 0)
        {
            valueStringBuilder.Append(userName);
            string password = Password;
            if (password.Length != 0)
            {
                valueStringBuilder.Append(':');
                valueStringBuilder.Append(password);
            }
            valueStringBuilder.Append('@');
        }
        if (host.Length != 0)
        {
            valueStringBuilder.Append(host);
            if (_port != -1)
            {
                valueStringBuilder.Append(':');
                int charsWritten;
                bool flag = _port.TryFormat(valueStringBuilder.AppendSpan(5), out charsWritten);
                valueStringBuilder.Length -= 5 - charsWritten;
            }
        }
        string path = Path;
        if (path.Length != 0)
        {
            if (!path.StartsWith('/') && host.Length != 0)
            {
                valueStringBuilder.Append('/');
            }
            valueStringBuilder.Append(path);
        }
        valueStringBuilder.Append(Query);
        valueStringBuilder.Append(Fragment);
        return valueStringBuilder.ToString();
    }
References System.UriBuilder._port, System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.AppendSpan(), System.UriBuilder.Fragment, System.UriParser.GetSyntax(), System.UriBuilder.Host, System.UriParser.InFact(), System.SR.net_uri_BadUserPassword, System.UriParser.NotAny(), System.UriBuilder.Password, System.UriBuilder.Path, System.UriBuilder.Query, System.s, System.UriBuilder.Scheme, System.Uri.SchemeDelimiter, System.Text.ValueStringBuilder.ToString(), and System.UriBuilder.UserName.