Terraria: Terraria.ID.TileID.Sets.CrackedBricks
CrackedBricks
bool [] Terraria.ID.TileID.Sets.CrackedBricks = Factory.CreateBoolSet(481, 482, 483) static
Definition at line 113 of file TileID.cs.
Referenced by Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.Projectile.ExplodeCrackedTiles(), Terraria.WorldGen.FinishDrunkGen(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishRemixWorld(), Terraria.Projectile.HandleMovement(), Terraria.Projectile.Kill(), Terraria.WorldGen.NotTheBees(), and Terraria.WorldGen.PaintTheDungeon().