Terraria: System.Xml.Xsl.IlGen.XmlILElementAnalyzer.AnalyzeAttributeCtor
AnalyzeAttributeCtor()
void System.Xml.Xsl.IlGen.XmlILElementAnalyzer.AnalyzeAttributeCtor (QilBinary ndAttr, XmlILConstructInfo info) inline private
Definition at line 51 of file XmlILElementAnalyzer.cs.
    {
        if (ndAttr.Left.NodeType == QilNodeType.LiteralQName)
        {
            QilName qilName = ndAttr.Left as QilName;
            parentInfo.MightHaveAttributes = true;
            if (!parentInfo.MightHaveDuplicateAttributes)
            {
                XmlQualifiedName xmlQualifiedName = new XmlQualifiedName(_attrNames.Add(qilName.LocalName), _attrNames.Add(qilName.NamespaceUri));
                int i;
                for (i = 0; i < _dupAttrs.Count; i++)
                {
                    XmlQualifiedName xmlQualifiedName2 = (XmlQualifiedName)_dupAttrs[i];
                    if ((object)xmlQualifiedName2.Name == xmlQualifiedName.Name && (object)xmlQualifiedName2.Namespace == xmlQualifiedName.Namespace)
                    {
                        parentInfo.MightHaveDuplicateAttributes = true;
                    }
                }
                if (i >= _dupAttrs.Count)
                {
                    _dupAttrs.Add(xmlQualifiedName);
                }
            }
            if (!info.IsNamespaceInScope)
            {
                parentInfo.MightHaveNamespaces = true;
            }
        }
        else
        {
            CheckAttributeNamespaceConstruct(ndAttr.XmlType);
        }
    }
References System.Xml.Xsl.IlGen.XmlILElementAnalyzer._attrNames, System.Xml.Xsl.IlGen.XmlILElementAnalyzer._dupAttrs, System.Collections.ArrayList.Add(), System.Xml.NameTable.Add(), System.Xml.Xsl.IlGen.XmlILElementAnalyzer.CheckAttributeNamespaceConstruct(), System.Collections.ArrayList.Count, System.Xml.Dictionary, System.info, System.Xml.Xsl.IlGen.XmlILConstructInfo.MightHaveDuplicateAttributes, and System.Xml.Xsl.IlGen.XmlILStateAnalyzer.parentInfo.
Referenced by System.Xml.Xsl.IlGen.XmlILElementAnalyzer.AnalyzeCopy().