Terraria: System.Xml.XmlStreamNodeWriter.FlushBufferAsync
FlushBufferAsync()
virtual Task System.Xml.XmlStreamNodeWriter.FlushBufferAsync () inline protected virtual inherited
Definition at line 386 of file XmlStreamNodeWriter.cs.
    {
        if (_offset != 0)
        {
            Task result = _stream.WriteAsync(_buffer, 0, _offset);
            _offset = 0;
            return result;
        }
        return Task.CompletedTask;
    }
References System.Xml.XmlStreamNodeWriter._buffer, System.Xml.XmlStreamNodeWriter._offset, System.Xml.XmlStreamNodeWriter._stream, System.Threading.Tasks.Task< TResult >.CompletedTask, and System.IO.Stream.WriteAsync().
Referenced by System.Xml.XmlStreamNodeWriter.FlushAndWriteBytesAsync(), System.Xml.XmlStreamNodeWriter.FlushAsync(), System.Xml.XmlStreamNodeWriter.FlushBufferAndWriteByteAsync(), and System.Xml.XmlStreamNodeWriter.GetBufferAsync().