Terraria: System.Xml.Xsl.Runtime.XmlQueryStaticData.GetObjectData
GetObjectData()
void System.Xml.Xsl.Runtime.XmlQueryStaticData.GetObjectData (out byte[] data, out Type[] ebTypes) inline
Definition at line 152 of file XmlQueryStaticData.cs.
    {
        MemoryStream memoryStream = new MemoryStream(4096);
        XmlQueryDataWriter xmlQueryDataWriter = new XmlQueryDataWriter(memoryStream);
        xmlQueryDataWriter.Write7BitEncodedInt(0);
        _defaultWriterSettings.GetObjectData(xmlQueryDataWriter);
        if (_whitespaceRules == null)
        {
            xmlQueryDataWriter.Write(0);
        }
        else
        {
            xmlQueryDataWriter.Write(_whitespaceRules.Count);
            foreach (WhitespaceRule whitespaceRule in _whitespaceRules)
            {
                whitespaceRule.GetObjectData(xmlQueryDataWriter);
            }
        }
        if (_names == null)
        {
            xmlQueryDataWriter.Write(0);
        }
        else
        {
            xmlQueryDataWriter.Write(_names.Length);
            string[] names = _names;
            foreach (string value in names)
            {
                xmlQueryDataWriter.Write(value);
            }
        }
        if (_prefixMappingsList == null)
        {
            xmlQueryDataWriter.Write(0);
        }
        else
        {
            xmlQueryDataWriter.Write(_prefixMappingsList.Length);
            StringPair[][] prefixMappingsList = _prefixMappingsList;
            foreach (StringPair[] array in prefixMappingsList)
            {
                xmlQueryDataWriter.Write(array.Length);
                StringPair[] array2 = array;
                for (int k = 0; k < array2.Length; k++)
                {
                    StringPair stringPair = array2[k];
                    xmlQueryDataWriter.Write(stringPair.Left);
                    xmlQueryDataWriter.Write(stringPair.Right);
                }
            }
        }
        if (_filters == null)
        {
            xmlQueryDataWriter.Write(0);
        }
        else
        {
            xmlQueryDataWriter.Write(_filters.Length);
            Int32Pair[] filters = _filters;
            for (int l = 0; l < filters.Length; l++)
            {
                Int32Pair int32Pair = filters[l];
                xmlQueryDataWriter.Write7BitEncodedInt(int32Pair.Left);
                xmlQueryDataWriter.Write7BitEncodedInt(int32Pair.Right);
            }
        }
        if (_types == null)
        {
            xmlQueryDataWriter.Write(0);
        }
        else
        {
            xmlQueryDataWriter.Write(_types.Length);
            XmlQueryType[] types = _types;
            foreach (XmlQueryType type in types)
            {
                XmlQueryTypeFactory.Serialize(xmlQueryDataWriter, type);
            }
        }
        if (_collations == null)
        {
            xmlQueryDataWriter.Write(0);
        }
        else
        {
            xmlQueryDataWriter.Write(_collations.Length);
            XmlCollation[] collations = _collations;
            foreach (XmlCollation xmlCollation in collations)
            {
                xmlCollation.GetObjectData(xmlQueryDataWriter);
            }
        }
        if (_globalNames == null)
        {
            xmlQueryDataWriter.Write(0);
        }
        else
        {
            xmlQueryDataWriter.Write(_globalNames.Length);
            string[] globalNames = _globalNames;
            foreach (string value2 in globalNames)
            {
                xmlQueryDataWriter.Write(value2);
            }
        }
        if (_earlyBound == null)
        {
            xmlQueryDataWriter.Write(0);
            ebTypes = null;
        }
        else
        {
            xmlQueryDataWriter.Write(_earlyBound.Length);
            ebTypes = new Type[_earlyBound.Length];
            int num2 = 0;
            EarlyBoundInfo[] earlyBound = _earlyBound;
            foreach (EarlyBoundInfo earlyBoundInfo in earlyBound)
            {
                xmlQueryDataWriter.Write(earlyBoundInfo.NamespaceUri);
                ebTypes[num2++] = earlyBoundInfo.EarlyBoundType;
            }
        }
        xmlQueryDataWriter.Dispose();
        data = memoryStream.ToArray();
    }
References System.Xml.Xsl.Runtime.XmlQueryStaticData._collations, System.Xml.Xsl.Runtime.XmlQueryStaticData._defaultWriterSettings, System.Xml.Xsl.Runtime.XmlQueryStaticData._earlyBound, System.Xml.Xsl.Runtime.XmlQueryStaticData._filters, System.Xml.Xsl.Runtime.XmlQueryStaticData._globalNames, System.Xml.Xsl.Runtime.XmlQueryStaticData._names, System.Xml.Xsl.Runtime.XmlQueryStaticData._prefixMappingsList, System.Xml.Xsl.Runtime.XmlQueryStaticData._types, System.Xml.Xsl.Runtime.XmlQueryStaticData._whitespaceRules, System.array, System.Xml.Dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.GetObjectData(), System.Xml.XmlWriterSettings.GetObjectData(), System.Xml.Xsl.XmlQueryTypeFactory.Serialize(), System.type, and System.value.