Terraria: System.Xml.XmlStreamNodeWriter.UnsafeGetUTF8Length
UnsafeGetUTF8Length()
unsafe int System.Xml.XmlStreamNodeWriter.UnsafeGetUTF8Length (char * chars, int charCount) inline protected inherited
Definition at line 317 of file XmlStreamNodeWriter.cs.
    {
        char* ptr = chars + charCount;
        while (chars < ptr && *chars < '\u0080')
        {
            chars++;
        }
        if (chars == ptr)
        {
            return charCount;
        }
        char[] array = new char[ptr - chars];
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = chars[i];
        }
        return (int)(chars - (ptr - charCount)) + GetByteCount(array);
    }
References System.array, System.charCount, System.chars, System.Xml.Dictionary, and System.Xml.XmlStreamNodeWriter.GetByteCount().
Referenced by System.Xml.XmlBinaryNodeWriter.UnsafeWriteName(), and System.Xml.XmlBinaryNodeWriter.UnsafeWriteText().