Terraria: System.Xml.XmlStreamNodeWriter.Close
Close()
override void System.Xml.XmlStreamNodeWriter.Close () inline inherited
Definition at line 409 of file XmlStreamNodeWriter.cs.
    {
        if (_stream != null)
        {
            if (_ownsStream)
            {
                _stream.Dispose();
            }
            _stream = null;
        }
    }
References System.Xml.XmlStreamNodeWriter._ownsStream, System.Xml.XmlStreamNodeWriter._stream, and System.IO.Stream.Dispose().
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.Close(), System.Xml.XmlBaseWriter.Close(), and System.Xml.XmlCanonicalWriter.Close().