Terraria: System.Xml.XmlStreamNodeWriter.Advance
Advance()
void System.Xml.XmlStreamNodeWriter.Advance (int count) inline protected inherited
Definition at line 84 of file XmlStreamNodeWriter.cs.
    {
        _offset += count;
    }
References System.Xml.XmlStreamNodeWriter._offset, and System.count.
Referenced by System.Xml.XmlUTF8NodeWriter.InternalWriteBase64Text(), System.Xml.XmlUTF8NodeWriter.InternalWriteBase64TextAsync(), System.Xml.XmlBinaryNodeWriter.UnsafeWriteName(), System.Xml.XmlBinaryNodeWriter.UnsafeWriteText(), System.Xml.XmlStreamNodeWriter.UnsafeWriteUnicodeChars(), System.Xml.XmlStreamNodeWriter.UnsafeWriteUTF8Chars(), System.Xml.XmlUTF8NodeWriter.WriteAmpersandCharEntity(), System.Xml.XmlUTF8NodeWriter.WriteApostropheCharEntity(), System.Xml.XmlBinaryNodeWriter.WriteBase64Text(), System.Xml.XmlUTF8NodeWriter.WriteBoolText(), System.Xml.XmlStreamNodeWriter.WriteBytes(), System.Xml.XmlUTF8NodeWriter.WriteCData(), System.Xml.XmlUTF8NodeWriter.WriteDateTimeText(), System.Xml.XmlBinaryNodeWriter.WriteDecimalText(), System.Xml.XmlUTF8NodeWriter.WriteDecimalText(), System.Xml.XmlBinaryNodeWriter.WriteDoubleText(), System.Xml.XmlUTF8NodeWriter.WriteDoubleText(), System.Xml.XmlUTF8NodeWriter.WriteEndComment(), System.Xml.XmlBinaryNodeWriter.WriteFloatText(), System.Xml.XmlUTF8NodeWriter.WriteFloatText(), System.Xml.XmlUTF8NodeWriter.WriteGreaterThanCharEntity(), System.Xml.XmlBinaryNodeWriter.WriteGuidText(), System.Xml.XmlBinaryNodeWriter.WriteInt32Text(), System.Xml.XmlUTF8NodeWriter.WriteInt32Text(), System.Xml.XmlBinaryNodeWriter.WriteInt64(), System.Xml.XmlUTF8NodeWriter.WriteInt64Text(), System.Xml.XmlUTF8NodeWriter.WriteLessThanCharEntity(), System.Xml.XmlBinaryNodeWriter.WriteMultiByteInt32(), System.Xml.XmlUTF8NodeWriter.WriteQuoteCharEntity(), System.Xml.XmlUTF8NodeWriter.WriteStartComment(), System.Xml.XmlUTF8NodeWriter.WriteStartXmlnsAttribute(), System.Xml.XmlBinaryNodeWriter.WriteTextNodeWithInt64(), System.Xml.XmlBinaryNodeWriter.WriteTextNodeWithLength(), System.Xml.XmlUTF8NodeWriter.WriteUInt64Text(), System.Xml.XmlBinaryNodeWriter.WriteUniqueIdText(), and System.Xml.XmlStreamNodeWriter.WriteUTF8Chars().