Terraria: System.Xml.XmlStreamNodeWriter.WriteBytesAsync
WriteBytesAsync() [1/2]
Task System.Xml.XmlStreamNodeWriter.WriteBytesAsync (byte b1, byte b2) inline protected inherited
Definition at line 143 of file XmlStreamNodeWriter.cs.
    {
        if (_offset + 1 >= 512)
        {
            return FlushAndWriteBytesAsync(b1, b2);
        }
        _buffer[_offset++] = b1;
        _buffer[_offset++] = b2;
        return Task.CompletedTask;
    }
References System.Xml.XmlStreamNodeWriter._buffer, System.Xml.XmlStreamNodeWriter._offset, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.Dictionary, and System.Xml.XmlStreamNodeWriter.FlushAndWriteBytesAsync().
Referenced by System.Xml.XmlStreamNodeWriter.WriteBytesAsync(), System.Xml.XmlUTF8NodeWriter.WriteEndElementAsync(), and System.Xml.XmlUTF8NodeWriter.WriteEndStartElementAsync().