Terraria: System.Xml.XmlStreamNodeWriter.UnsafeGetUTF8Chars
UnsafeGetUTF8Chars()
unsafe int System.Xml.XmlStreamNodeWriter.UnsafeGetUTF8Chars (char * chars, int charCount, byte[] buffer, int offset) inline protected inherited
Definition at line 336 of file XmlStreamNodeWriter.cs.
    {
        if (charCount > 0)
        {
            fixed (byte* ptr = &buffer[offset])
            {
                byte* ptr2 = ptr;
                byte* ptr3 = ptr2 + (buffer.Length - offset);
                char* ptr4 = chars + charCount;
                do
                {
                    IL_0045:
                    if (chars < ptr4)
                    {
                        char c = *chars;
                        if (c < '\u0080')
{
                            *ptr2 = (byte)c;
                            ptr2++;
                            chars++;
                            goto IL_0045;
                        }
                    }
                    if (chars >= ptr4)
                    {
                        break;
                    }
                    char* ptr5 = chars;
                    while (chars < ptr4 && *chars >= '\u0080')
                    {
                        chars++;
                    }
                    ptr2 += (_encoding ?? s_UTF8Encoding).GetBytes(ptr5, (int)(chars - ptr5), ptr2, (int)(ptr3 - ptr2));
                }
                while (chars < ptr4);
                return (int)(ptr2 - ptr);
            }
        }
        return 0;
    }
References System.Xml.XmlStreamNodeWriter._encoding, System.buffer, System.charCount, System.chars, System.Xml.Dictionary, System.offset, and System.Xml.XmlStreamNodeWriter.s_UTF8Encoding.
Referenced by System.Xml.XmlBinaryNodeWriter.UnsafeWriteName(), System.Xml.XmlBinaryNodeWriter.UnsafeWriteText(), and System.Xml.XmlStreamNodeWriter.UnsafeWriteUTF8Chars().