Terraria: System.Xml.XmlStreamNodeWriter.Flush
Flush()
override void System.Xml.XmlStreamNodeWriter.Flush () inline inherited
Definition at line 397 of file XmlStreamNodeWriter.cs.
    {
        FlushBuffer();
        _stream.Flush();
    }
References System.Xml.XmlStreamNodeWriter._stream, System.IO.Stream.Flush(), and System.Xml.XmlStreamNodeWriter.FlushBuffer().
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.Close(), System.Runtime.Serialization.Json.XmlJsonWriter.Flush(), System.Xml.XmlCanonicalWriter.Flush(), and System.Xml.XmlCanonicalWriter.WriteEndStartElement().