Terraria: System.Xml.XmlStreamNodeWriter.WriteUTF8Chars
WriteUTF8Chars() [1/2]
void System.Xml.XmlStreamNodeWriter.WriteUTF8Chars (byte[] chars, int charOffset, int charCount) inline protected inherited
Definition at line 230 of file XmlStreamNodeWriter.cs.
    {
        if (charCount < 512)
        {
            int offset;
            byte[] buffer = GetBuffer(charCount, out offset);
            Buffer.BlockCopy(chars, charOffset, buffer, offset, charCount);
            Advance(charCount);
        }
        else
        {
            FlushBuffer();
            _stream.Write(chars, charOffset, charCount);
        }
    }
References System.Xml.XmlStreamNodeWriter._stream, System.Xml.XmlStreamNodeWriter.Advance(), System.Buffer.BlockCopy(), System.buffer, System.charCount, System.chars, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.FlushBuffer(), System.Xml.XmlStreamNodeWriter.GetBuffer(), System.offset, and System.IO.Stream.Write().
Referenced by System.Xml.XmlUTF8NodeWriter.WriteCData(), System.Xml.XmlUTF8NodeWriter.WriteComment(), System.Xml.XmlUTF8NodeWriter.WriteDeclaration(), System.Xml.XmlUTF8NodeWriter.WriteEscapedText(), System.Xml.XmlUTF8NodeWriter.WriteHexCharEntity(), System.Xml.XmlUTF8NodeWriter.WriteLocalName(), System.Xml.XmlUTF8NodeWriter.WriteLocalName(), System.Xml.XmlUTF8NodeWriter.WritePrefix(), System.Xml.XmlUTF8NodeWriter.WritePrefix(), System.Xml.XmlUTF8NodeWriter.WriteText(), System.Xml.XmlUTF8NodeWriter.WriteText(), and System.Xml.XmlUTF8NodeWriter.WriteText().