Terraria: System.Xml.XmlStreamNodeWriter.FlushBuffer
FlushBuffer()
virtual void System.Xml.XmlStreamNodeWriter.FlushBuffer () inline protected virtual inherited
Reimplemented in System.Xml.XmlBinaryNodeWriter.
Definition at line 377 of file XmlStreamNodeWriter.cs.
    {
        if (_offset != 0)
        {
            _stream.Write(_buffer, 0, _offset);
            _offset = 0;
        }
    }
References System.Xml.XmlStreamNodeWriter._buffer, System.Xml.XmlStreamNodeWriter._offset, System.Xml.XmlStreamNodeWriter._stream, and System.IO.Stream.Write().
Referenced by System.Xml.XmlStreamNodeWriter.EnsureByte(), System.Xml.XmlStreamNodeWriter.Flush(), System.Xml.XmlStreamNodeWriter.GetBuffer(), System.Xml.XmlStreamNodeWriter.UnsafeWriteBytes(), System.Xml.XmlStreamNodeWriter.WriteBytes(), System.Xml.XmlStreamNodeWriter.WriteBytes(), and System.Xml.XmlStreamNodeWriter.WriteUTF8Chars().