Terraria: System.Xml.XmlStreamNodeWriter.WriteByteAsync
WriteByteAsync() [1/2]
Task System.Xml.XmlStreamNodeWriter.WriteByteAsync (byte b) inline protected inherited
Definition at line 103 of file XmlStreamNodeWriter.cs.
    {
        if (_offset >= 512)
        {
            return FlushBufferAndWriteByteAsync(b);
        }
        _buffer[_offset++] = b;
        return Task.CompletedTask;
    }
References System.Xml.XmlStreamNodeWriter._buffer, System.Xml.XmlStreamNodeWriter._offset, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.Dictionary, and System.Xml.XmlStreamNodeWriter.FlushBufferAndWriteByteAsync().
Referenced by System.Xml.XmlStreamNodeWriter.WriteByteAsync(), System.Xml.XmlUTF8NodeWriter.WriteEndAttributeAsync(), System.Xml.XmlUTF8NodeWriter.WriteEndElementAsync(), System.Xml.XmlUTF8NodeWriter.WriteEndStartElementAsync(), and System.Xml.XmlUTF8NodeWriter.WriteStartElementAsync().