Terraria: System.Xml.XmlStreamNodeWriter.WriteBytes
WriteBytes() [2/3]
void System.Xml.XmlStreamNodeWriter.WriteBytes (byte[] byteBuffer, int byteOffset, int byteCount) inline inherited
Definition at line 171 of file XmlStreamNodeWriter.cs.
    {
        if (byteCount < 512)
        {
            int offset;
            byte[] buffer = GetBuffer(byteCount, out offset);
            Buffer.BlockCopy(byteBuffer, byteOffset, buffer, offset, byteCount);
            Advance(byteCount);
        }
        else
        {
            FlushBuffer();
            _stream.Write(byteBuffer, byteOffset, byteCount);
        }
    }
References System.Xml.XmlStreamNodeWriter._stream, System.Xml.XmlStreamNodeWriter.Advance(), System.Buffer.BlockCopy(), System.buffer, System.byteCount, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.FlushBuffer(), System.Xml.XmlStreamNodeWriter.GetBuffer(), System.offset, and System.IO.Stream.Write().