Terraria: System.Xml.XmlStreamNodeWriter.UnsafeWriteUnicodeChars
UnsafeWriteUnicodeChars()
unsafe void System.Xml.XmlStreamNodeWriter.UnsafeWriteUnicodeChars (char * chars, int charCount) inline protected inherited
Definition at line 281 of file XmlStreamNodeWriter.cs.
    {
        while (charCount > 256)
        {
            int num = 256;
            if ((chars[num - 1] & 0xFC00) == 55296)
            {
                num--;
            }
            int offset;
            byte[] buffer = GetBuffer(num * 2, out offset);
            Advance(UnsafeGetUnicodeChars(chars, num, buffer, offset));
            charCount -= num;
            chars += num;
        }
        if (charCount > 0)
        {
            int offset2;
            byte[] buffer2 = GetBuffer(charCount * 2, out offset2);
            Advance(UnsafeGetUnicodeChars(chars, charCount, buffer2, offset2));
        }
    }
References System.Xml.XmlStreamNodeWriter.Advance(), System.buffer, System.charCount, System.chars, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.GetBuffer(), System.offset, and System.Xml.XmlStreamNodeWriter.UnsafeGetUnicodeChars().
Referenced by System.Xml.XmlBinaryNodeWriter.UnsafeWriteText().