Terraria: System.Xml.XmlStreamNodeWriter.UnsafeWriteBytes
UnsafeWriteBytes()
unsafe void System.Xml.XmlStreamNodeWriter.UnsafeWriteBytes (byte * bytes, int byteCount) inline protected inherited
Definition at line 187 of file XmlStreamNodeWriter.cs.
    {
        FlushBuffer();
        byte[] buffer = _buffer;
        while (byteCount >= 512)
        {
            for (int i = 0; i < 512; i++)
            {
                buffer[i] = bytes[i];
            }
            _stream.Write(buffer, 0, 512);
            bytes += 512;
            byteCount -= 512;
        }
        for (int j = 0; j < byteCount; j++)
        {
            buffer[j] = bytes[j];
        }
        _stream.Write(buffer, 0, byteCount);
    }
References System.Xml.XmlStreamNodeWriter._buffer, System.Xml.XmlStreamNodeWriter._stream, System.buffer, System.byteCount, System.bytes, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.FlushBuffer(), and System.IO.Stream.Write().
Referenced by System.Xml.XmlBinaryNodeWriter.UnsafeWriteArray().