Terraria: System.Xml.XmlStreamNodeWriter.WriteByte
WriteByte() [1/2]
void System.Xml.XmlStreamNodeWriter.WriteByte (byte b) inline protected inherited
Definition at line 97 of file XmlStreamNodeWriter.cs.
    {
        EnsureByte();
        _buffer[_offset++] = b;
    }
References System.Xml.XmlStreamNodeWriter._buffer, System.Xml.XmlStreamNodeWriter._offset, System.Xml.Dictionary, and System.Xml.XmlStreamNodeWriter.EnsureByte().
Referenced by System.Xml.XmlStreamNodeWriter.WriteByte(), System.Xml.XmlUTF8NodeWriter.WriteEndAttribute(), System.Xml.XmlUTF8NodeWriter.WriteEndElement(), System.Xml.XmlUTF8NodeWriter.WriteEndElement(), System.Xml.XmlUTF8NodeWriter.WriteEndStartElement(), System.Xml.XmlUTF8NodeWriter.WriteListSeparator(), System.Xml.XmlBinaryNodeWriter.WriteName(), System.Xml.XmlBinaryNodeWriter.WriteNode(), System.Xml.XmlBinaryNodeWriter.WriteQualifiedName(), System.Xml.XmlUTF8NodeWriter.WriteQualifiedName(), System.Xml.XmlUTF8NodeWriter.WriteStartAttribute(), System.Xml.XmlUTF8NodeWriter.WriteStartAttribute(), System.Xml.XmlUTF8NodeWriter.WriteStartElement(), System.Xml.XmlUTF8NodeWriter.WriteStartElement(), System.Xml.XmlBinaryNodeWriter.WriteTextNode(), System.Xml.XmlStreamNodeWriter.WriteUTF8Char(), System.Xml.XmlUTF8NodeWriter.WriteXmlnsAttribute(), and System.Xml.XmlUTF8NodeWriter.WriteXmlnsAttribute().