Terraria: System.Xml.XmlStreamNodeWriter.UnsafeWriteUTF8Chars
UnsafeWriteUTF8Chars()
unsafe void System.Xml.XmlStreamNodeWriter.UnsafeWriteUTF8Chars (char * chars, int charCount) inline protected inherited
Definition at line 258 of file XmlStreamNodeWriter.cs.
    {
        while (charCount > 170)
        {
            int num = 170;
            if ((chars[num - 1] & 0xFC00) == 55296)
            {
                num--;
            }
            int offset;
            byte[] buffer = GetBuffer(num * 3, out offset);
            Advance(UnsafeGetUTF8Chars(chars, num, buffer, offset));
            charCount -= num;
            chars += num;
        }
        if (charCount > 0)
        {
            int offset2;
            byte[] buffer2 = GetBuffer(charCount * 3, out offset2);
            Advance(UnsafeGetUTF8Chars(chars, charCount, buffer2, offset2));
        }
    }
References System.Xml.XmlStreamNodeWriter.Advance(), System.buffer, System.charCount, System.chars, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.GetBuffer(), System.offset, and System.Xml.XmlStreamNodeWriter.UnsafeGetUTF8Chars().
Referenced by System.Xml.XmlUTF8NodeWriter.UnsafeWriteEscapedText(), System.Xml.XmlBinaryNodeWriter.UnsafeWriteName(), System.Xml.XmlBinaryNodeWriter.UnsafeWriteText(), System.Runtime.Serialization.Json.XmlJsonWriter.JsonNodeWriter.WriteChars(), System.Xml.XmlUTF8NodeWriter.WriteText(), System.Xml.XmlStreamNodeWriter.WriteUTF8Char(), and System.Xml.XmlStreamNodeWriter.WriteUTF8Chars().