Terraria: MS.Internal.Xml.XPath.DescendantOverDescendantQuery.Advance
Advance()
override XPathNavigator MS.Internal.Xml.XPath.DescendantOverDescendantQuery.Advance () inline
Definition at line 26 of file DescendantOverDescendantQuery.cs.
    {
        while (true)
        {
            if (_level == 0)
            {
                currentNode = qyInput.Advance();
                position = 0;
                if (currentNode == null)
                {
                    return null;
                }
                if (matchSelf && matches(currentNode))
                {
                    break;
                }
                currentNode = currentNode.Clone();
                if (!MoveToFirstChild())
                {
                    continue;
                }
            }
            else if (!MoveUpUntilNext())
            {
                continue;
            }
            do
            {
                if (matches(currentNode))
                {
                    position++;
                    return currentNode;
                }
            }
            while (MoveToFirstChild());
        }
        position = 1;
        return currentNode;
    }
References MS.Internal.Xml.XPath.DescendantOverDescendantQuery._level, MS.Internal.Xml.XPath.Query.Advance(), System.Xml.XPath.XPathNavigator.Clone(), MS.Internal.Xml.XPath.BaseAxisQuery.currentNode, MS.Internal.Xml.XPath.BaseAxisQuery.matches(), MS.Internal.Xml.XPath.DescendantBaseQuery.matchSelf, MS.Internal.Xml.XPath.DescendantOverDescendantQuery.MoveToFirstChild(), MS.Internal.Xml.XPath.DescendantOverDescendantQuery.MoveUpUntilNext(), MS.Internal.Xml.XPath.BaseAxisQuery.position, and MS.Internal.Xml.XPath.BaseAxisQuery.qyInput.