Terraria: System.Xml.XmlStreamNodeWriter.WriteUTF8Char
WriteUTF8Char()
unsafe void System.Xml.XmlStreamNodeWriter.WriteUTF8Char (int ch) inline protected inherited
Definition at line 208 of file XmlStreamNodeWriter.cs.
    {
        if (ch < 128)
        {
            WriteByte((byte)ch);
        }
        else if (ch <= 65535)
        {
            char* ptr = stackalloc char[1];
            *ptr = (char)ch;
            UnsafeWriteUTF8Chars(ptr, 1);
        }
        else
        {
            SurrogateChar surrogateChar = new SurrogateChar(ch);
            char* ptr2 = stackalloc char[2];
            *ptr2 = surrogateChar.HighChar;
            ptr2[1] = surrogateChar.LowChar;
            UnsafeWriteUTF8Chars(ptr2, 2);
        }
    }
References System.ch, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.UnsafeWriteUTF8Chars(), and System.Xml.XmlStreamNodeWriter.WriteByte().
Referenced by System.Xml.XmlUTF8NodeWriter.WritePrefix(), System.Xml.XmlUTF8NodeWriter.WritePrefix(), and System.Xml.XmlUTF8NodeWriter.WriteText().