Terraria: Microsoft.Xna.Framework.Graphics.Model.ReadBoneReference
ReadBoneReference()
ModelBone Microsoft.Xna.Framework.Graphics.Model.ReadBoneReference (ContentReader input) inline private
Definition at line 172 of file Model.cs.
    {
        int num = bones.Count + 1;
        int num2 = 0;
        num2 = ((num > 255) ? input.ReadInt32() : input.ReadByte());
        if (num2 != 0)
        {
            return bones[num2 - 1];
        }
        return null;
    }
References Microsoft.Xna.Framework.Graphics.Model.bones, and System.input.
Referenced by Microsoft.Xna.Framework.Graphics.Model.Read(), Microsoft.Xna.Framework.Graphics.Model.ReadBones(), and Microsoft.Xna.Framework.Graphics.Model.ReadMeshes().