Terraria: Microsoft.Xna.Framework.Graphics.Model.ReadMeshes
ReadMeshes()
void Microsoft.Xna.Framework.Graphics.Model.ReadMeshes (ContentReader input) inline private
Definition at line 184 of file Model.cs.
    {
        int num = input.ReadInt32();
        ModelMesh[] array = new ModelMesh[num];
        for (int i = 0; i < num; i++)
        {
            string name = input.ReadObject<string>();
            ModelBone parentBone = ReadBoneReference(input);
            BoundingSphere boundingSphere = default(BoundingSphere);
            boundingSphere.Center = input.ReadVector3();
            boundingSphere.Radius = input.ReadSingle();
            object obj = input.ReadObject<object>();
            ModelMeshPart[] meshParts = ReadMeshParts(input);
            array[i] = new ModelMesh(name, parentBone, boundingSphere, meshParts, obj);
        }
        meshes = new ModelMeshCollection(array);
    }
References System.array, System.input, Microsoft.Xna.Framework.Graphics.Model.meshes, System.obj, Microsoft.Xna.Framework.Graphics.Model.ReadBoneReference(), and Microsoft.Xna.Framework.Graphics.Model.ReadMeshParts().
Referenced by Microsoft.Xna.Framework.Graphics.Model.Read().