Terraria: Terraria.GameContent.Events.MysticLogFairiesEvent.ScanWholeOverworldForLogs
ScanWholeOverworldForLogs()
void Terraria.GameContent.Events.MysticLogFairiesEvent.ScanWholeOverworldForLogs () inline private
Definition at line 135 of file MysticLogFairiesEvent.cs.
    {
        _stumpCoords.Clear();
        NPC.fairyLog = false;
        int num = (int)Main.worldSurface - 10;
        int num2 = 100;
        int num3 = Main.maxTilesX - 100;
        if (Main.remixWorld)
        {
            num = Main.maxTilesY - 350;
            num2 = (int)Main.rockLayer;
        }
        int num4 = 3;
        int num5 = 2;
        List<Point> list = new List<Point>();
        for (int i = 100; i < num3; i += num4)
        {
            for (int num6 = num; num6 >= num2; num6 -= num5)
            {
                Tile tile = Main.tile[i, num6];
                if (tile.active() && tile.type == 488 && tile.liquid == 0)
                {
                    list.Add(new Point(i, num6));
                    NPC.fairyLog = true;
                }
            }
        }
        foreach (Point item in list)
        {
            _stumpCoords.Add(GetStumpTopLeft(item));
        }
    }
References Terraria.GameContent.Events.MysticLogFairiesEvent._stumpCoords, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), Terraria.GameContent.Events.MysticLogFairiesEvent.GetStumpTopLeft(), System.item, Terraria.Tile.liquid, System.list, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Events.MysticLogFairiesEvent.FallenLogDestroyed(), Terraria.GameContent.Events.MysticLogFairiesEvent.StartNight(), and Terraria.GameContent.Events.MysticLogFairiesEvent.StartWorld().