Terraria: System.Xml.Xsl.Xslt.Stylesheet.AddTemplate
AddTemplate()
bool System.Xml.Xsl.Xslt.Stylesheet.AddTemplate (Template template) inline
Definition at line 73 of file Stylesheet.cs.
    {
        template.ImportPrecedence = _importPrecedence;
        template.OrderNumber = _orderNumber++;
        _compiler.AllTemplates.Add(template);
        if (template.Name != null)
        {
            if (!_compiler.NamedTemplates.TryGetValue(template.Name, out var value))
            {
                _compiler.NamedTemplates[template.Name] = template;
            }
            else if (value.ImportPrecedence == template.ImportPrecedence)
            {
                return false;
            }
        }
        if (template.Match != null)
        {
            Templates.Add(template);
        }
        return true;
    }
References System.Xml.Xsl.Xslt.Stylesheet._compiler, System.Xml.Xsl.Xslt.Stylesheet._importPrecedence, System.Xml.Xsl.Xslt.Stylesheet._orderNumber, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.Compiler.AllTemplates, System.Xml.Dictionary, System.Xml.Name, System.Xml.Xsl.Xslt.Compiler.NamedTemplates, System.Xml.Xsl.Xslt.Stylesheet.Templates, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadSimplifiedStylesheet(), and System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate().