Terraria: System.Reflection.Metadata.Ecma335.TypeSpecTableReader.GetSignature
GetSignature()
BlobHandle System.Reflection.Metadata.Ecma335.TypeSpecTableReader.GetSignature (TypeSpecificationHandle handle) inline package
Definition at line 26 of file TypeSpecTableReader.cs.
    {
        int num = (handle.RowId - 1) * RowSize;
        return BlobHandle.FromOffset(Block.PeekHeapReference(num + _SignatureOffset, _IsBlobHeapRefSizeSmall));
    }
References System.Reflection.Metadata.Ecma335.TypeSpecTableReader._IsBlobHeapRefSizeSmall, System.Reflection.Metadata.Ecma335.TypeSpecTableReader._SignatureOffset, System.Reflection.Metadata.Ecma335.TypeSpecTableReader.Block, System.Reflection.Metadata.BlobHandle.FromOffset(), System.Reflection.Internal.MemoryBlock.PeekHeapReference(), and System.Reflection.Metadata.Ecma335.TypeSpecTableReader.RowSize.
Referenced by System.Reflection.Metadata.MetadataReader.ImplementsRedirectedInterface().