Terraria: System.Xml.BinXmlSqlDecimal.ToString
ToString()
override string System.Xml.BinXmlSqlDecimal.ToString () inline
Definition at line 139 of file BinXmlSqlDecimal.cs.
    {
        uint[] array = new uint[4] { m_data1, m_data2, m_data3, m_data4 };
        int ciulU = m_bLen;
        char[] array2 = new char[39];
        int num = 0;
        while (ciulU > 1 || array[0] != 0)
        {
            MpDiv1(array, ref ciulU, 10u, out var iulR);
            array2[num++] = ChFromDigit(iulR);
        }
        while (num <= m_bScale)
        {
            array2[num++] = ChFromDigit(0u);
        }
        bool isPositive = IsPositive;
        int num2 = (isPositive ? num : (num + 1));
        if (m_bScale > 0)
        {
            num2++;
        }
        char[] array3 = new char[num2];
        int num3 = 0;
        if (!isPositive)
        {
            array3[num3++] = '-';
        }
        while (num > 0)
        {
            if (num-- == m_bScale)
            {
                array3[num3++] = '.';
            }
            array3[num3++] = array2[num];
        }
        return new string(array3);
    }
References System.array, System.Xml.BinXmlSqlDecimal.ChFromDigit(), System.Xml.Dictionary, System.Xml.BinXmlSqlDecimal.IsPositive, System.Xml.BinXmlSqlDecimal.m_bLen, System.Xml.BinXmlSqlDecimal.m_bScale, System.Xml.BinXmlSqlDecimal.m_data1, System.Xml.BinXmlSqlDecimal.m_data2, System.Xml.BinXmlSqlDecimal.m_data3, System.Xml.BinXmlSqlDecimal.m_data4, and System.Xml.BinXmlSqlDecimal.MpDiv1().
Referenced by System.Xml.XmlSqlBinaryReader.ValueAsString().