Terraria: System.Xml.BinXmlSqlDecimal.MpDiv1
MpDiv1()
static void System.Xml.BinXmlSqlDecimal.MpDiv1 (uint[] rgulU, ref int ciulU, uint iulD, out uint iulR) inline static private
Definition at line 65 of file BinXmlSqlDecimal.cs.
    {
        uint num = 0u;
        ulong num2 = iulD;
        int num3 = ciulU;
        while (num3 > 0)
        {
            num3--;
            ulong num4 = ((ulong)num << 32) + rgulU[num3];
            rgulU[num3] = (uint)(num4 / num2);
            num = (uint)(num4 - rgulU[num3] * num2);
        }
        iulR = num;
        MpNormalize(rgulU, ref ciulU);
    }
References System.Xml.Dictionary, and System.Xml.BinXmlSqlDecimal.MpNormalize().
Referenced by System.Xml.BinXmlSqlDecimal.ToString(), and System.Xml.BinXmlSqlDecimal.TrimTrailingZeros().