Terraria: System.Linq.Parallel.AsynchronousChannel.FlushCachedChunk
FlushCachedChunk()
void System.Linq.Parallel.AsynchronousChannel< T >.FlushCachedChunk () inline private
Definition at line 146 of file AsynchronousChannel.cs.
    {
        if (_producerChunk != null && _producerChunkIndex != 0)
        {
            T[] array = new T[_producerChunkIndex];
            Array.Copy(_producerChunk, array, _producerChunkIndex);
            EnqueueChunk(array);
            _producerChunk = null;
        }
    }
References System.Linq.Parallel.AsynchronousChannel< T >._producerChunk, System.Linq.Parallel.AsynchronousChannel< T >._producerChunkIndex, System.array, System.Array.Copy(), and System.Linq.Parallel.AsynchronousChannel< T >.EnqueueChunk().
Referenced by System.Linq.Parallel.AsynchronousChannel< T >.FlushBuffers().