Terraria: System.Linq.Parallel.AsynchronousChannel.WaitUntilNonFull
WaitUntilNonFull()
void System.Linq.Parallel.AsynchronousChannel< T >.WaitUntilNonFull () inline private
Definition at line 128 of file AsynchronousChannel.cs.
    {
        do
        {
            _producerEvent.Reset();
            Interlocked.Exchange(ref _producerIsWaiting, 1);
            if (IsFull)
            {
                _producerEvent.Wait(_cancellationToken);
            }
            else
            {
                _producerIsWaiting = 0;
            }
        }
        while (IsFull);
    }
References System.Linq.Parallel.AsynchronousChannel< T >._cancellationToken, System.Linq.Parallel.AsynchronousChannel< T >._producerEvent, System.Linq.Parallel.AsynchronousChannel< T >._producerIsWaiting, System.Threading.Interlocked.Exchange(), System.Linq.Parallel.AsynchronousChannel< T >.IsFull, System.Threading.ManualResetEventSlim.Reset(), and System.Threading.ManualResetEventSlim.Wait().
Referenced by System.Linq.Parallel.AsynchronousChannel< T >.EnqueueChunk().