Terraria: System.Linq.Parallel.AsynchronousChannel.EnqueueChunk
EnqueueChunk()
void System.Linq.Parallel.AsynchronousChannel< T >.EnqueueChunk (T[] chunk) inline private
Definition at line 112 of file AsynchronousChannel.cs.
    {
        if (IsFull)
        {
            WaitUntilNonFull();
        }
        int producerBufferIndex = _producerBufferIndex;
        _buffer[producerBufferIndex] = chunk;
        Interlocked.Exchange(ref _producerBufferIndex, (producerBufferIndex + 1) % _buffer.Length);
        if (_consumerIsWaiting == 1 && !IsChunkBufferEmpty)
        {
            _consumerIsWaiting = 0;
            _consumerEvent.Set(_index);
        }
    }
References System.Linq.Parallel.AsynchronousChannel< T >._buffer, System.Linq.Parallel.AsynchronousChannel< T >._consumerEvent, System.Linq.Parallel.AsynchronousChannel< T >._consumerIsWaiting, System.Linq.Parallel.AsynchronousChannel< T >._index, System.Linq.Parallel.AsynchronousChannel< T >._producerBufferIndex, System.Threading.Interlocked.Exchange(), System.Linq.Parallel.AsynchronousChannel< T >.IsChunkBufferEmpty, System.Linq.Parallel.AsynchronousChannel< T >.IsFull, System.Linq.Parallel.IntValueEvent.Set(), and System.Linq.Parallel.AsynchronousChannel< T >.WaitUntilNonFull().
Referenced by System.Linq.Parallel.AsynchronousChannel< T >.Enqueue(), and System.Linq.Parallel.AsynchronousChannel< T >.FlushCachedChunk().