Terraria: System.Globalization.IdnMapping.PunycodeEncode
PunycodeEncode()
static string System.Globalization.IdnMapping.PunycodeEncode (string unicode) inline static private
Definition at line 246 of file IdnMapping.cs.
    {
        if (unicode.Length == 0)
        {
            throw new ArgumentException(SR.Argument_IdnBadLabelSize, "unicode");
        }
        StringBuilder stringBuilder = new StringBuilder(unicode.Length);
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        while (num < unicode.Length)
        {
            num = unicode.IndexOfAny(s_dotSeparators, num2);
            if (num < 0)
            {
                num = unicode.Length;
            }
            if (num == num2)
            {
                if (num == unicode.Length)
                {
                    break;
                }
                throw new ArgumentException(SR.Argument_IdnBadLabelSize, "unicode");
            }
            stringBuilder.Append("xn--");
            bool flag = false;
            StrongBidiCategory bidiCategory = CharUnicodeInfo.GetBidiCategory(unicode, num2);
            if (bidiCategory == StrongBidiCategory.StrongRightToLeft)
            {
                flag = true;
                int num4 = num - 1;
                if (char.IsLowSurrogate(unicode, num4))
                {
                    num4--;
                }
                bidiCategory = CharUnicodeInfo.GetBidiCategory(unicode, num4);
                if (bidiCategory != StrongBidiCategory.StrongRightToLeft)
                {
                    throw new ArgumentException(SR.Argument_IdnBadBidi, "unicode");
                }
            }
            int num5 = 0;
            for (int i = num2; i < num; i++)
            {
                StrongBidiCategory bidiCategory2 = CharUnicodeInfo.GetBidiCategory(unicode, i);
                if (flag && bidiCategory2 == StrongBidiCategory.StrongLeftToRight)
                {
                    throw new ArgumentException(SR.Argument_IdnBadBidi, "unicode");
                }
                if (!flag && bidiCategory2 == StrongBidiCategory.StrongRightToLeft)
                {
                    throw new ArgumentException(SR.Argument_IdnBadBidi, "unicode");
                }
                if (Basic(unicode[i]))
                {
                    stringBuilder.Append(EncodeBasic(unicode[i]));
                    num5++;
                }
                else if (char.IsSurrogatePair(unicode, i))
                {
                    i++;
                }
            }
            int num6 = num5;
            if (num6 == num - num2)
            {
                stringBuilder.Remove(num3, "xn--".Length);
            }
            else
            {
                if (unicode.Length - num2 >= "xn--".Length && unicode.Substring(num2, "xn--".Length).Equals("xn--", StringComparison.OrdinalIgnoreCase))
                {
                    throw new ArgumentException(SR.Argument_IdnBadPunycode, "unicode");
                }
                int num7 = 0;
                if (num6 > 0)
                {
                    stringBuilder.Append('-');
                }
                int num8 = 128;
                int num9 = 0;
                int num10 = 72;
                while (num5 < num - num2)
                {
                    int num11 = 0;
                    int num12 = 134217727;
                    for (int j = num2; j < num; j += ((!IsSupplementary(num11)) ? 1 : 2))
                    {
                        num11 = char.ConvertToUtf32(unicode, j);
                        if (num11 >= num8 && num11 < num12)
{
                            num12 = num11;
                        }
                    }
                    num9 += (num12 - num8) * (num5 - num7 + 1);
                    num8 = num12;
                    for (int j = num2; j < num; j += ((!IsSupplementary(num11)) ? 1 : 2))
                    {
                        num11 = char.ConvertToUtf32(unicode, j);
                        if (num11 < num8)
{
                            num9++;
                        }
                        if (num11 != num8)
{
                            continue;
                        }
                        int num13 = num9;
                        int num14 = 36;
                        while (true)
{
                            int num15 = ((num14 <= num10) ? 1 : ((num14 >= num10 + 26) ? 26 : (num14 - num10)));
                            if (num13 < num15)
{
                                break;
                            }
                            stringBuilder.Append(EncodeDigit(num15 + (num13 - num15) % (36 - num15)));
                            num13 = (num13 - num15) / (36 - num15);
                            num14 += 36;
                        }
                        stringBuilder.Append(EncodeDigit(num13));
                        num10 = Adapt(num9, num5 - num7 + 1, num5 == num6);
                        num9 = 0;
                        num5++;
                        if (IsSupplementary(num12))
{
                            num5++;
                            num7++;
                        }
                    }
                    num9++;
                    num8++;
                }
            }
            if (stringBuilder.Length - num3 > 63)
            {
                throw new ArgumentException(SR.Argument_IdnBadLabelSize, "unicode");
            }
            if (num != unicode.Length)
            {
                stringBuilder.Append('.');
            }
            num2 = num + 1;
            num3 = stringBuilder.Length;
        }
        if (stringBuilder.Length > 255 - ((!IsDot(unicode[^1])) ? 1 : 0))
        {
            throw new ArgumentException(SR.Format(SR.Argument_IdnBadNameSize, 255 - ((!IsDot(unicode[^1])) ? 1 : 0)), "unicode");
        }
        return stringBuilder.ToString();
    }
References System.Globalization.IdnMapping.Adapt(), System.Text.StringBuilder.Append(), System.SR.Argument_IdnBadBidi, System.SR.Argument_IdnBadLabelSize, System.SR.Argument_IdnBadNameSize, System.SR.Argument_IdnBadPunycode, System.Basic, System.Globalization.IdnMapping.EncodeBasic(), System.Globalization.IdnMapping.EncodeDigit(), System.SR.Format(), System.Globalization.CharUnicodeInfo.GetBidiCategory(), System.Globalization.IdnMapping.IsDot(), System.Globalization.IdnMapping.IsSupplementary(), System.Text.StringBuilder.Length, System.Text.StringBuilder.Remove(), System.Globalization.IdnMapping.s_dotSeparators, and System.Text.StringBuilder.ToString().
Referenced by System.Globalization.IdnMapping.GetAsciiInvariant().