Terraria: System.Globalization.IdnMapping.GetAsciiInvariant
GetAsciiInvariant()
string System.Globalization.IdnMapping.GetAsciiInvariant (string unicode, int index, int count) inline private
Definition at line 172 of file IdnMapping.cs.
    {
        if (index > 0 || count < unicode.Length)
        {
            unicode = unicode.Substring(index, count);
        }
        if (ValidateStd3AndAscii(unicode, UseStd3AsciiRules, bCheckAscii: true))
        {
            return unicode;
        }
        if (unicode[^1] <= '\u001f')
        {
            throw new ArgumentException(SR.Format(SR.Argument_InvalidCharSequence, unicode.Length - 1), "unicode");
        }
        if (UseStd3AsciiRules)
        {
            ValidateStd3AndAscii(unicode, bUseStd3: true, bCheckAscii: false);
        }
        return PunycodeEncode(unicode);
    }
References System.SR.Argument_InvalidCharSequence, System.count, System.SR.Format(), System.index, System.Globalization.IdnMapping.PunycodeEncode(), System.Globalization.IdnMapping.UseStd3AsciiRules, and System.Globalization.IdnMapping.ValidateStd3AndAscii().
Referenced by System.Globalization.IdnMapping.GetAscii().