Terraria: System.Globalization.IdnMapping.GetUnicode
GetUnicode() [3/3]
unsafe string System.Globalization.IdnMapping.GetUnicode (string ascii, int index, int count) inline
Definition at line 112 of file IdnMapping.cs.
    {
        if (ascii == null)
        {
            throw new ArgumentNullException("ascii");
        }
        if (index < 0 || count < 0)
        {
            throw new ArgumentOutOfRangeException((index < 0) ? "index" : "count", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (index > ascii.Length)
        {
            throw new ArgumentOutOfRangeException("index", SR.ArgumentOutOfRange_Index);
        }
        if (index > ascii.Length - count)
        {
            throw new ArgumentOutOfRangeException("ascii", SR.ArgumentOutOfRange_IndexCountBuffer);
        }
        if (count > 0 && ascii[index + count - 1] == '\0')
        {
            throw new ArgumentException(SR.Argument_IdnBadPunycode, "ascii");
        }
        if (GlobalizationMode.Invariant)
        {
            return GetUnicodeInvariant(ascii, index, count);
        }
        fixed (char* ptr = ascii)
        {
            if (!GlobalizationMode.UseNls)
            {
                return IcuGetUnicodeCore(ascii, ptr + index, count);
            }
            return NlsGetUnicodeCore(ascii, ptr + index, count);
        }
    }
References System.SR.Argument_IdnBadPunycode, System.SR.ArgumentOutOfRange_Index, System.SR.ArgumentOutOfRange_IndexCountBuffer, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.count, System.Globalization.IdnMapping.GetUnicodeInvariant(), System.Globalization.IdnMapping.IcuGetUnicodeCore(), System.index, System.Globalization.GlobalizationMode.Invariant, System.Globalization.IdnMapping.NlsGetUnicodeCore(), and System.Globalization.GlobalizationMode.UseNls.