Terraria: System.Globalization.IdnMapping.GetUnicodeInvariant
GetUnicodeInvariant()
string System.Globalization.IdnMapping.GetUnicodeInvariant (string ascii, int index, int count) inline private
Definition at line 444 of file IdnMapping.cs.
    {
        if (index > 0 || count < ascii.Length)
        {
            ascii = ascii.Substring(index, count);
        }
        string text = PunycodeDecode(ascii);
        if (!ascii.Equals(GetAscii(text), StringComparison.OrdinalIgnoreCase))
        {
            throw new ArgumentException(SR.Argument_IdnIllegalName, "ascii");
        }
        return text;
    }
References System.SR.Argument_IdnIllegalName, System.count, System.Globalization.IdnMapping.GetAscii(), System.index, System.Globalization.IdnMapping.PunycodeDecode(), and System.text.
Referenced by System.Globalization.IdnMapping.GetUnicode().