Terraria: System.Globalization.IdnMapping.IcuGetAsciiCore
IcuGetAsciiCore()
unsafe string System.Globalization.IdnMapping.IcuGetAsciiCore (string unicodeString, char * unicode, int count) inline private
Definition at line 693 of file IdnMapping.cs.
    {
        uint icuFlags = IcuFlags;
        CheckInvalidIdnCharacters(unicode, count, icuFlags, "unicode");
        int num = (int)Math.Min((long)count * 3L + 4, 512L);
        int num2;
        if (num < 512)
        {
            char* ptr = stackalloc char[num];
            num2 = Interop.Globalization.ToAscii(icuFlags, unicode, count, ptr, num);
            if (num2 > 0 && num2 <= num)
            {
                return GetStringForOutput(unicodeString, unicode, count, ptr, num2);
            }
        }
        else
        {
            num2 = Interop.Globalization.ToAscii(icuFlags, unicode, count, null, 0);
        }
        if (num2 == 0)
        {
            throw new ArgumentException(SR.Argument_IdnIllegalName, "unicode");
        }
        char[] array = new char[num2];
        fixed (char* ptr2 = &array[0])
        {
            num2 = Interop.Globalization.ToAscii(icuFlags, unicode, count, ptr2, num2);
            if (num2 == 0 || num2 > array.Length)
            {
                throw new ArgumentException(SR.Argument_IdnIllegalName, "unicode");
            }
            return GetStringForOutput(unicodeString, unicode, count, ptr2, num2);
        }
    }
References System.SR.Argument_IdnIllegalName, System.array, System.Globalization.IdnMapping.CheckInvalidIdnCharacters(), System.count, System.Globalization.IdnMapping.GetStringForOutput(), System.Globalization.IdnMapping.IcuFlags, System.L, System.Math.Min(), and Interop.Globalization.ToAscii().
Referenced by System.Globalization.IdnMapping.GetAscii().