Terraria: System.Globalization.IdnMapping.GetAscii
GetAscii() [3/3]
unsafe string System.Globalization.IdnMapping.GetAscii (string unicode, int index, int count) inline
Definition at line 58 of file IdnMapping.cs.
    {
        if (unicode == null)
        {
            throw new ArgumentNullException("unicode");
        }
        if (index < 0 || count < 0)
        {
            throw new ArgumentOutOfRangeException((index < 0) ? "index" : "count", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (index > unicode.Length)
        {
            throw new ArgumentOutOfRangeException("index", SR.ArgumentOutOfRange_Index);
        }
        if (index > unicode.Length - count)
        {
            throw new ArgumentOutOfRangeException("unicode", SR.ArgumentOutOfRange_IndexCountBuffer);
        }
        if (count == 0)
        {
            throw new ArgumentException(SR.Argument_IdnBadLabelSize, "unicode");
        }
        if (unicode[index + count - 1] == '\0')
        {
            throw new ArgumentException(SR.Format(SR.Argument_InvalidCharSequence, index + count - 1), "unicode");
        }
        if (GlobalizationMode.Invariant)
        {
            return GetAsciiInvariant(unicode, index, count);
        }
        fixed (char* ptr = unicode)
        {
            if (!GlobalizationMode.UseNls)
            {
                return IcuGetAsciiCore(unicode, ptr + index, count);
            }
            return NlsGetAsciiCore(unicode, ptr + index, count);
        }
    }
References System.SR.Argument_IdnBadLabelSize, System.SR.Argument_InvalidCharSequence, System.SR.ArgumentOutOfRange_Index, System.SR.ArgumentOutOfRange_IndexCountBuffer, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.count, System.SR.Format(), System.Globalization.IdnMapping.GetAsciiInvariant(), System.Globalization.IdnMapping.IcuGetAsciiCore(), System.index, System.Globalization.GlobalizationMode.Invariant, System.Globalization.IdnMapping.NlsGetAsciiCore(), and System.Globalization.GlobalizationMode.UseNls.