Terraria: System.Globalization.IdnMapping.ValidateStd3AndAscii
ValidateStd3AndAscii()
static bool System.Globalization.IdnMapping.ValidateStd3AndAscii (string unicode, bool bUseStd3, bool bCheckAscii) inline static private
Definition at line 193 of file IdnMapping.cs.
    {
        if (unicode.Length == 0)
        {
            throw new ArgumentException(SR.Argument_IdnBadLabelSize, "unicode");
        }
        int num = -1;
        for (int i = 0; i < unicode.Length; i++)
        {
            if (unicode[i] <= '\u001f')
            {
                throw new ArgumentException(SR.Format(SR.Argument_InvalidCharSequence, i), "unicode");
            }
            if (bCheckAscii && unicode[i] >= '\u007f')
            {
                return false;
            }
            if (IsDot(unicode[i]))
            {
                if (i == num + 1)
                {
                    throw new ArgumentException(SR.Argument_IdnBadLabelSize, "unicode");
                }
                if (i - num > 64)
                {
                    throw new ArgumentException(SR.Argument_IdnBadLabelSize, "unicode");
                }
                if (bUseStd3 && i > 0)
                {
                    ValidateStd3(unicode[i - 1], bNextToDot: true);
                }
                num = i;
            }
            else if (bUseStd3)
            {
                ValidateStd3(unicode[i], i == num + 1);
            }
        }
        if (num == -1 && unicode.Length > 63)
        {
            throw new ArgumentException(SR.Argument_IdnBadLabelSize, "unicode");
        }
        if (unicode.Length > 255 - ((!IsDot(unicode[^1])) ? 1 : 0))
        {
            throw new ArgumentException(SR.Format(SR.Argument_IdnBadNameSize, 255 - ((!IsDot(unicode[^1])) ? 1 : 0)), "unicode");
        }
        if (bUseStd3 && !IsDot(unicode[^1]))
        {
            ValidateStd3(unicode[^1], bNextToDot: true);
        }
        return true;
    }
References System.SR.Argument_IdnBadLabelSize, System.SR.Argument_IdnBadNameSize, System.SR.Argument_InvalidCharSequence, System.SR.Format(), System.Globalization.IdnMapping.IsDot(), and System.Globalization.IdnMapping.ValidateStd3().
Referenced by System.Globalization.IdnMapping.GetAsciiInvariant().