Terraria: System.Globalization.IdnMapping.IcuGetUnicodeCore
IcuGetUnicodeCore() [1/2]
unsafe string System.Globalization.IdnMapping.IcuGetUnicodeCore (string asciiString, char * ascii, int count) inline private
Definition at line 728 of file IdnMapping.cs.
    {
        uint icuFlags = IcuFlags;
        CheckInvalidIdnCharacters(ascii, count, icuFlags, "ascii");
        if (count < 512)
        {
            char* output = stackalloc char[count];
            return IcuGetUnicodeCore(asciiString, ascii, count, icuFlags, output, count, reattempt: true);
        }
        char[] array = new char[count];
        fixed (char* output2 = &array[0])
        {
            return IcuGetUnicodeCore(asciiString, ascii, count, icuFlags, output2, count, reattempt: true);
        }
    }
References System.array, System.Globalization.IdnMapping.CheckInvalidIdnCharacters(), System.count, System.Globalization.IdnMapping.IcuFlags, and System.Globalization.IdnMapping.IcuGetUnicodeCore().
Referenced by System.Globalization.IdnMapping.GetUnicode(), System.Globalization.IdnMapping.IcuGetUnicodeCore(), and System.Globalization.IdnMapping.IcuGetUnicodeCore().