Terraria: System.Globalization.IdnMapping.NlsGetUnicodeCore
NlsGetUnicodeCore() [2/2]
static unsafe string System.Globalization.IdnMapping.NlsGetUnicodeCore (string asciiString, char * ascii, int count, uint flags, char * output, int outputLength) inline static private
Definition at line 831 of file IdnMapping.cs.
    {
        int num = Interop.Normaliz.IdnToUnicode(flags, ascii, count, output, outputLength);
        if (num == 0)
        {
            ThrowForZeroLength(unicode: false);
        }
        return GetStringForOutput(asciiString, ascii, count, output, num);
    }
References System.count, System.Globalization.IdnMapping.GetStringForOutput(), Interop.Normaliz.IdnToUnicode(), and System.Globalization.IdnMapping.ThrowForZeroLength().