Terraria: System.Globalization.IdnMapping.PunycodeDecode
PunycodeDecode()
static string System.Globalization.IdnMapping.PunycodeDecode (string ascii) inline static private
Definition at line 458 of file IdnMapping.cs.
    {
        if (ascii.Length == 0)
        {
            throw new ArgumentException(SR.Argument_IdnBadLabelSize, "ascii");
        }
        if (ascii.Length > 255 - ((!IsDot(ascii[^1])) ? 1 : 0))
        {
            throw new ArgumentException(SR.Format(SR.Argument_IdnBadNameSize, 255 - ((!IsDot(ascii[^1])) ? 1 : 0)), "ascii");
        }
        StringBuilder stringBuilder = new StringBuilder(ascii.Length);
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        while (num < ascii.Length)
        {
            num = ascii.IndexOf('.', num2);
            if (num < 0 || num > ascii.Length)
            {
                num = ascii.Length;
            }
            if (num == num2)
            {
                if (num == ascii.Length)
                {
                    break;
                }
                throw new ArgumentException(SR.Argument_IdnBadLabelSize, "ascii");
            }
            if (num - num2 > 63)
            {
                throw new ArgumentException(SR.Argument_IdnBadLabelSize, "ascii");
            }
            if (ascii.Length < "xn--".Length + num2 || string.Compare(ascii, num2, "xn--", 0, "xn--".Length, StringComparison.OrdinalIgnoreCase) != 0)
            {
                stringBuilder.Append(ascii, num2, num - num2);
            }
            else
            {
                num2 += "xn--".Length;
                int num4 = ascii.LastIndexOf('-', num - 1);
                if (num4 == num - 1)
                {
                    throw new ArgumentException(SR.Argument_IdnBadPunycode, "ascii");
                }
                int num5;
                if (num4 <= num2)
                {
                    num5 = 0;
                }
                else
                {
                    num5 = num4 - num2;
                    for (int i = num2; i < num2 + num5; i++)
                    {
                        if (ascii[i] > '\u007f')
{
                            throw new ArgumentException(SR.Argument_IdnBadPunycode, "ascii");
                        }
                        stringBuilder.Append((char)((ascii[i] >= 'A' && ascii[i] <= 'Z') ? (ascii[i] - 65 + 97) : ascii[i]));
                    }
                }
                int num6 = num2 + ((num5 > 0) ? (num5 + 1) : 0);
                int num7 = 128;
                int num8 = 72;
                int num9 = 0;
                int num10 = 0;
                while (num6 < num)
                {
                    int num11 = num9;
                    int num12 = 1;
                    int num13 = 36;
                    while (true)
                    {
                        if (num6 >= num)
{
                            throw new ArgumentException(SR.Argument_IdnBadPunycode, "ascii");
                        }
                        int num14 = DecodeDigit(ascii[num6++]);
                        if (num14 > (134217727 - num9) / num12)
{
                            throw new ArgumentException(SR.Argument_IdnBadPunycode, "ascii");
                        }
                        num9 += num14 * num12;
                        int num15 = ((num13 <= num8) ? 1 : ((num13 >= num8 + 26) ? 26 : (num13 - num8)));
                        if (num14 < num15)
{
                            break;
                        }
                        if (num12 > 134217727 / (36 - num15))
{
                            throw new ArgumentException(SR.Argument_IdnBadPunycode, "ascii");
                        }
                        num12 *= 36 - num15;
                        num13 += 36;
                    }
                    num8 = Adapt(num9 - num11, stringBuilder.Length - num3 - num10 + 1, num11 == 0);
                    if (num9 / (stringBuilder.Length - num3 - num10 + 1) > 134217727 - num7)
                    {
                        throw new ArgumentException(SR.Argument_IdnBadPunycode, "ascii");
                    }
                    num7 += num9 / (stringBuilder.Length - num3 - num10 + 1);
                    num9 %= stringBuilder.Length - num3 - num10 + 1;
                    if (num7 < 0 || num7 > 1114111 || (num7 >= 55296 && num7 <= 57343))
                    {
                        throw new ArgumentException(SR.Argument_IdnBadPunycode, "ascii");
                    }
                    string value = char.ConvertFromUtf32(num7);
                    int num17;
                    if (num10 > 0)
                    {
                        int num16 = num9;
                        num17 = num3;
                        while (num16 > 0)
{
                            if (num17 >= stringBuilder.Length)
{
                                throw new ArgumentException(SR.Argument_IdnBadPunycode, "ascii");
                            }
                            if (char.IsSurrogate(stringBuilder[num17]))
{
                                num17++;
                            }
                            num16--;
                            num17++;
                        }
                    }
                    else
                    {
                        num17 = num3 + num9;
                    }
                    stringBuilder.Insert(num17, value);
                    if (IsSupplementary(num7))
                    {
                        num10++;
                    }
                    num9++;
                }
                bool flag = false;
                StrongBidiCategory bidiCategory = CharUnicodeInfo.GetBidiCategory(stringBuilder, num3);
                if (bidiCategory == StrongBidiCategory.StrongRightToLeft)
                {
                    flag = true;
                }
                for (int j = num3; j < stringBuilder.Length; j++)
                {
                    if (!char.IsLowSurrogate(stringBuilder[j]))
                    {
                        bidiCategory = CharUnicodeInfo.GetBidiCategory(stringBuilder, j);
                        if ((flag && bidiCategory == StrongBidiCategory.StrongLeftToRight) || (!flag && bidiCategory == StrongBidiCategory.StrongRightToLeft))
{
                            throw new ArgumentException(SR.Argument_IdnBadBidi, "ascii");
                        }
                    }
                }
                if (flag && bidiCategory != StrongBidiCategory.StrongRightToLeft)
                {
                    throw new ArgumentException(SR.Argument_IdnBadBidi, "ascii");
                }
            }
            if (num - num2 > 63)
            {
                throw new ArgumentException(SR.Argument_IdnBadLabelSize, "ascii");
            }
            if (num != ascii.Length)
            {
                stringBuilder.Append('.');
            }
            num2 = num + 1;
            num3 = stringBuilder.Length;
        }
        if (stringBuilder.Length > 255 - ((!IsDot(stringBuilder[stringBuilder.Length - 1])) ? 1 : 0))
        {
            throw new ArgumentException(SR.Format(SR.Argument_IdnBadNameSize, 255 - ((!IsDot(stringBuilder[stringBuilder.Length - 1])) ? 1 : 0)), "ascii");
        }
        return stringBuilder.ToString();
    }
References System.Globalization.IdnMapping.Adapt(), System.Text.StringBuilder.Append(), System.SR.Argument_IdnBadBidi, System.SR.Argument_IdnBadLabelSize, System.SR.Argument_IdnBadNameSize, System.SR.Argument_IdnBadPunycode, System.Globalization.IdnMapping.DecodeDigit(), System.SR.Format(), System.Globalization.CharUnicodeInfo.GetBidiCategory(), System.Text.StringBuilder.Insert(), System.Globalization.IdnMapping.IsDot(), System.Globalization.IdnMapping.IsSupplementary(), System.Text.StringBuilder.Length, System.Text.StringBuilder.ToString(), and System.value.
Referenced by System.Globalization.IdnMapping.GetUnicodeInvariant().