Terraria: System.Net.SecurityPackageInfoClass.SecurityPackageInfoClass
SecurityPackageInfoClass() [4/4]
unsafe System.Net.SecurityPackageInfoClass.SecurityPackageInfoClass (SafeHandle safeHandle, int index) inline package
Definition at line 19 of file SecurityPackageInfoClass.cs.
    {
        if (safeHandle.IsInvalid)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"Invalid handle: {safeHandle}", ".ctor");
            }
            return;
        }
        IntPtr intPtr = safeHandle.DangerousGetHandle() + sizeof(SecurityPackageInfo) * index;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"unmanagedAddress: {intPtr}", ".ctor");
        }
        SecurityPackageInfo* ptr = (SecurityPackageInfo*)(void*)intPtr;
        Capabilities = ptr->Capabilities;
        Version = ptr->Version;
        RPCID = ptr->RPCID;
        MaxToken = ptr->MaxToken;
        IntPtr name = ptr->Name;
        if (name != IntPtr.Zero)
        {
            Name = Marshal.PtrToStringUni(name);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"Name: {Name}", ".ctor");
            }
        }
        name = ptr->Comment;
        if (name != IntPtr.Zero)
        {
            Comment = Marshal.PtrToStringUni(name);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"Comment: {Comment}", ".ctor");
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, ToString(), ".ctor");
        }
    }
References System.Net.SecurityPackageInfo.Capabilities, System.Net.SecurityPackageInfoClass.Capabilities, System.Net.SecurityPackageInfo.Comment, System.Net.SecurityPackageInfoClass.Comment, System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.index, System.Net.NetEventSource.Info(), System.Runtime.InteropServices.SafeHandle.IsInvalid, System.Net.NetEventSource.Log, System.Net.SecurityPackageInfo.MaxToken, System.Net.SecurityPackageInfoClass.MaxToken, System.Net.SecurityPackageInfo.Name, System.Net.SecurityPackageInfoClass.Name, System.Runtime.InteropServices.Marshal.PtrToStringUni(), System.Net.SecurityPackageInfo.RPCID, System.Net.SecurityPackageInfoClass.RPCID, System.Net.SecurityPackageInfoClass.ToString(), System.Net.SecurityPackageInfo.Version, and System.IntPtr.Zero.