Terraria: System.Runtime.InteropServices.PosixSignalRegistration.Register
Register()
static unsafe PosixSignalRegistration System.Runtime.InteropServices.PosixSignalRegistration.Register (PosixSignal signal, Action< PosixSignalContext > handler) inline static private
Definition at line 55 of file PosixSignalRegistration.cs.
    {
        if ((uint)(signal - -4) > 3u)
        {
            throw new PlatformNotSupportedException();
        }
        Token token = new Token(signal, handler);
        PosixSignalRegistration result = new PosixSignalRegistration(token);
        lock (s_registrations)
        {
            if (s_registrations.Count == 0 && !Interop.Kernel32.SetConsoleCtrlHandler((delegate* unmanaged<int, Interop.BOOL>)(delegate*<int, Interop.BOOL>)(&HandlerRoutine), Add: true))
            {
                throw Win32Marshal.GetExceptionForLastWin32Error();
            }
            s_registrations.Add(token);
            return result;
        }
    }
References System.Runtime.InteropServices.PosixSignalRegistration.PosixSignalRegistration(), System.Add, System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.Runtime.InteropServices.PosixSignalRegistration.HandlerRoutine(), System.Runtime.InteropServices.PosixSignalRegistration.s_registrations, and Interop.Kernel32.SetConsoleCtrlHandler().
Referenced by System.Runtime.InteropServices.PosixSignalRegistration.Create().