Terraria: System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance
ILGenForCreateInstance() [1/2]
void System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance (CodeGenerator ilg, Type type, bool ctorInaccessible, bool cast) inline package
Definition at line 68 of file ReflectionAwareILGen.cs.
    {
        if (!ctorInaccessible)
        {
            ConstructorInfo constructor = type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            if (constructor != null)
            {
                ilg.New(constructor);
                return;
            }
            LocalBuilder tempLocal = ilg.GetTempLocal(type);
            ilg.Ldloca(tempLocal);
            ilg.InitObj(type);
            ilg.Ldloc(tempLocal);
        }
        else
        {
            ILGenForCreateInstance(ilg, type, cast ? type : null, ctorInaccessible);
        }
    }
References System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.GetTempLocal(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.CodeGenerator.InitObj(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldloca(), System.Xml.Serialization.CodeGenerator.New(), and System.type.
Referenced by System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), and System.Xml.Serialization.ReflectionAwareILGen.WriteCreateInstance().