Terraria: System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance
ILGenForCreateInstance() [2/2]
void System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance (CodeGenerator ilg, Type type, Type cast, bool nonPublic) inline package
Definition at line 90 of file ReflectionAwareILGen.cs.
    {
        if (type == typeof(DBNull))
        {
            FieldInfo field = type.GetField("Value", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
            ilg.LoadMember(field);
            return;
        }
        if (type.FullName == "System.Xml.Linq.XElement")
        {
            Type type2 = type.Assembly.GetType("System.Xml.Linq.XName");
            if (type2 != null)
            {
                MethodInfo method = type2.GetMethod("op_Implicit", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
                ConstructorInfo constructor = type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { type2 });
                if (method != null && constructor != null)
                {
                    ilg.Ldstr("default");
                    ilg.Call(method);
                    ilg.New(constructor);
                    return;
                }
            }
        }
        Label label = ilg.DefineLabel();
        Label label2 = ilg.DefineLabel();
        ilg.Ldc(type);
        MethodInfo method2 = typeof(IntrospectionExtensions).GetMethod("GetTypeInfo", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(Type) });
        ilg.Call(method2);
        LocalBuilder localBuilder = ilg.DeclareLocal(typeof(IEnumerator<>).MakeGenericType(typeof(ConstructorInfo)), "e");
        MethodInfo method3 = typeof(TypeInfo).GetMethod("get_DeclaredConstructors");
        MethodInfo method4 = typeof(IEnumerable<>).MakeGenericType(typeof(ConstructorInfo)).GetMethod("GetEnumerator");
        ilg.Call(method3);
        ilg.Call(method4);
        ilg.Stloc(localBuilder);
        ilg.WhileBegin();
        MethodInfo method5 = typeof(IEnumerator).GetMethod("get_Current");
        ilg.Ldloc(localBuilder);
        ilg.Call(method5);
        LocalBuilder localBuilder2 = ilg.DeclareLocal(typeof(ConstructorInfo), "constructorInfo");
        ilg.Stloc(localBuilder2);
        ilg.Ldloc(localBuilder2);
        MethodInfo method6 = typeof(ConstructorInfo).GetMethod("get_IsStatic");
        ilg.Call(method6);
        ilg.Brtrue(label2);
        ilg.Ldloc(localBuilder2);
        MethodInfo method7 = typeof(ConstructorInfo).GetMethod("GetParameters");
        ilg.Call(method7);
        ilg.Ldlen();
        ilg.Ldc(0);
        ilg.Cne();
        ilg.Brtrue(label2);
        MethodInfo method8 = typeof(ConstructorInfo).GetMethod("Invoke", new Type[1] { typeof(object[]) });
        ilg.Ldloc(localBuilder2);
        ilg.Load(null);
        ilg.Call(method8);
        ilg.Br(label);
        ilg.MarkLabel(label2);
        ilg.WhileBeginCondition();
        MethodInfo method9 = typeof(IEnumerator).GetMethod("MoveNext", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg.Ldloc(localBuilder);
        ilg.Call(method9);
        ilg.WhileEndCondition();
        ilg.WhileEnd();
        MethodInfo method10 = typeof(Activator).GetMethod("CreateInstance", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(Type) });
        ilg.Ldc(type);
        ilg.Call(method10);
        ilg.MarkLabel(label);
        if (cast != null)
        {
            ilg.ConvertValue(method10.ReturnType, cast);
        }
    }
References System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Brtrue(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Cne(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldlen(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.CodeGenerator.New(), System.Xml.Serialization.CodeGenerator.Stloc(), System.type, System.Xml.Serialization.CodeGenerator.WhileBegin(), System.Xml.Serialization.CodeGenerator.WhileBeginCondition(), System.Xml.Serialization.CodeGenerator.WhileEnd(), and System.Xml.Serialization.CodeGenerator.WhileEndCondition().