Terraria: RemadeChatMonitor.DrawChat
DrawChat()
void RemadeChatMonitor.DrawChat (bool drawingPlayerChat) inline
Implements IChatMonitor.
     {
         int num = _startChatLine;
         int num2 = 0;
         int num3 = 0;
         while (num > 0 && num2 < _messages.Count)
         {
             int num4 = Math.Min(num, _messages[num2].LineCount);
             num -= num4;
             num3 += num4;
             if (num3 == _messages[num2].LineCount)
             {
                 num3 = 0;
                 num2++;
             }
         }
         int num5 = 0;
         int? num6 = null;
         int snippetIndex = -1;
         int? num7 = null;
         int hoveredSnippet = -1;
         while (num5 < _showCount && num2 < _messages.Count)
         {
             ChatMessageContainer chatMessageContainer = _messages[num2];
             if (!chatMessageContainer.Prepared || !(drawingPlayerChat | chatMessageContainer.CanBeShownWhenChatIsClosed))
             {
                 break;
             }
             TextSnippet[] snippetWithInversedIndex = chatMessageContainer.GetSnippetWithInversedIndex(num3);
             ChatManager.DrawColorCodedStringWithShadow(Main.spriteBatch, FontAssets.MouseText.Value, snippetWithInversedIndex, new Vector2(88f, Main.screenHeight - 30 - 28 - num5 * 21), 0f, Vector2.Zero, Vector2.One, out hoveredSnippet);
             if (hoveredSnippet >= 0)
             {
                 num7 = hoveredSnippet;
                 num6 = num2;
                 snippetIndex = num3;
             }
             num5++;
             num3++;
             if (num3 >= chatMessageContainer.LineCount)
             {
                 num3 = 0;
                 num2++;
             }
         }
         if (num6.HasValue && num7.HasValue)
         {
             TextSnippet[] snippetWithInversedIndex2 = _messages[num6.Value].GetSnippetWithInversedIndex(snippetIndex);
             snippetWithInversedIndex2[num7.Value].OnHover();
             if (Main.mouseLeft && Main.mouseLeftRelease)
             {
                 snippetWithInversedIndex2[num7.Value].OnClick();
             }
         }
     }
References _messages, _showCount, _startChatLine, ChatMessageContainer.CanBeShownWhenChatIsClosed, ChatManager.DrawColorCodedStringWithShadow(), ChatMessageContainer.GetSnippetWithInversedIndex(), ChatMessageContainer.LineCount, Main.mouseLeft, Main.mouseLeftRelease, FontAssets.MouseText, TextSnippet.OnClick(), TextSnippet.OnHover(), ChatMessageContainer.Prepared, Main.screenHeight, Main.spriteBatch, and Asset< T >.Value.