Terraria: System.Net.Cookie.VerifySetDefaults
VerifySetDefaults()
bool System.Net.Cookie.VerifySetDefaults (CookieVariant variant, Uri uri, bool isLocalDomain, string localDomain, bool setDefault, bool shouldThrow) inline package
Definition at line 376 of file Cookie.cs.
    {
        string host = uri.Host;
        int port = uri.Port;
        string absolutePath = uri.AbsolutePath;
        bool flag = true;
        if (setDefault)
        {
            if (Version == 0)
            {
                variant = CookieVariant.Plain;
            }
            else if (Version == 1 && variant == CookieVariant.Unknown)
            {
                variant = CookieVariant.Rfc2109;
            }
            m_cookieVariant = variant;
        }
        if (string.IsNullOrEmpty(m_name) || m_name[0] == '$' || m_name.IndexOfAny(ReservedToName) != -1 || m_name[0] == ' ' || m_name[m_name.Length - 1] == ' ')
        {
            if (shouldThrow)
            {
                throw new CookieException(System.SR.Format(System.SR.net_cookie_attribute, "Name", (m_name == null) ? "<null>" : m_name));
            }
            return false;
        }
        if (m_value == null || ((m_value.Length <= 2 || m_value[0] != '"' || m_value[m_value.Length - 1] != '"') && m_value.IndexOfAny(ReservedToValue) != -1))
        {
            if (shouldThrow)
            {
                throw new CookieException(System.SR.Format(System.SR.net_cookie_attribute, "Value", (m_value == null) ? "<null>" : m_value));
            }
            return false;
        }
        if (Comment != null && (Comment.Length <= 2 || Comment[0] != '"' || Comment[Comment.Length - 1] != '"') && Comment.IndexOfAny(ReservedToValue) != -1)
        {
            if (shouldThrow)
            {
                throw new CookieException(System.SR.Format(System.SR.net_cookie_attribute, "Comment", Comment));
            }
            return false;
        }
        if (Path != null && (Path.Length <= 2 || Path[0] != '"' || Path[Path.Length - 1] != '"') && Path.IndexOfAny(ReservedToValue) != -1)
        {
            if (shouldThrow)
            {
                throw new CookieException(System.SR.Format(System.SR.net_cookie_attribute, "Path", Path));
            }
            return false;
        }
        if (setDefault && m_domain_implicit)
        {
            m_domain = host;
        }
        else
        {
            if (!m_domain_implicit)
            {
                string text = m_domain;
                if (!DomainCharsTest(text))
                {
                    if (shouldThrow)
                    {
                        throw new CookieException(System.SR.Format(System.SR.net_cookie_attribute, "Domain", (text == null) ? "<null>" : text));
                    }
                    return false;
                }
                if (text[0] != '.')
                {
                    text = "." + text;
                }
                int num = host.IndexOf('.');
                if (isLocalDomain && string.Equals(localDomain, text, StringComparison.OrdinalIgnoreCase))
                {
                    flag = true;
                }
                else if (text.IndexOf('.', 1, text.Length - 2) == -1)
                {
                    if (!IsDomainEqualToHost(text, host))
                    {
                        flag = false;
                    }
                }
                else if (variant == CookieVariant.Plain)
                {
                    if (!IsDomainEqualToHost(text, host) && (host.Length <= text.Length || string.Compare(host, host.Length - text.Length, text, 0, text.Length, StringComparison.OrdinalIgnoreCase) != 0))
                    {
                        flag = false;
                    }
                }
                else if ((num == -1 || text.Length != host.Length - num || string.Compare(host, num, text, 0, text.Length, StringComparison.OrdinalIgnoreCase) != 0) && !IsDomainEqualToHost(text, host))
                {
                    flag = false;
                }
                if (flag)
                {
                    m_domainKey = text.ToLowerInvariant();
                }
            }
            else if (!string.Equals(host, m_domain, StringComparison.OrdinalIgnoreCase))
            {
                flag = false;
            }
            if (!flag)
            {
                if (shouldThrow)
                {
                    throw new CookieException(System.SR.Format(System.SR.net_cookie_attribute, "Domain", m_domain));
                }
                return false;
            }
        }
        if (setDefault && m_path_implicit)
        {
            switch (m_cookieVariant)
            {
            case CookieVariant.Plain:
            {
                int length;
                if (absolutePath.Length == 0 || absolutePath[0] != '/' || (length = absolutePath.LastIndexOf('/')) == 0)
                {
                    m_path = "/";
                }
                else
                {
                    m_path = absolutePath.Substring(0, length);
                }
                break;
            }
            case CookieVariant.Rfc2109:
                m_path = absolutePath.Substring(0, absolutePath.LastIndexOf('/'));
                break;
            default:
                m_path = absolutePath.Substring(0, absolutePath.LastIndexOf('/') + 1);
                break;
            }
        }
        if (setDefault && !m_port_implicit && m_port.Length == 0)
        {
            m_port_list = new int[1] { port };
        }
        if (!m_port_implicit)
        {
            flag = false;
            int[] port_list = m_port_list;
            foreach (int num2 in port_list)
            {
                if (num2 == port)
                {
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                if (shouldThrow)
                {
                    throw new CookieException(System.SR.Format(System.SR.net_cookie_attribute, "Port", m_port));
                }
                return false;
            }
        }
        return true;
    }
References System.Uri.AbsolutePath, System.Net.Cookie.Comment, System.Runtime.Serialization.Dictionary, System.Net.Cookie.DomainCharsTest(), System.Net.Equals, System.SR.Format(), System.Uri.Host, System.Net.Cookie.IsDomainEqualToHost(), System.length, System.Net.Cookie.m_cookieVariant, System.Net.Cookie.m_domain, System.Net.Cookie.m_domain_implicit, System.Net.Cookie.m_domainKey, System.Net.Cookie.m_name, System.Net.Cookie.m_path, System.Net.Cookie.m_path_implicit, System.Net.Cookie.m_port, System.Net.Cookie.m_port_implicit, System.Net.Cookie.m_port_list, System.Net.Cookie.m_value, System.SR.net_cookie_attribute, System.Net.Cookie.Path, System.Uri.Port, System.Net.Cookie.ReservedToName, System.Net.Cookie.ReservedToValue, and System.text.