Terraria: System.Collections.Generic.ComparerHelpers.CreateDefaultComparer
CreateDefaultComparer()
static object System.Collections.Generic.ComparerHelpers.CreateDefaultComparer (Type type) inline static package
Definition at line 5 of file ComparerHelpers.cs.
    {
        object obj = null;
        RuntimeType runtimeType = (RuntimeType)type;
        if (typeof(IComparable<>).MakeGenericType(type).IsAssignableFrom(type))
        {
            obj = RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter((RuntimeType)typeof(GenericComparer<int>), runtimeType);
        }
        else if (type.IsGenericType)
        {
            if (type.GetGenericTypeDefinition() == typeof(Nullable<>))
            {
                obj = TryCreateNullableComparer(runtimeType);
            }
        }
        else if (type.IsEnum)
        {
            obj = TryCreateEnumComparer(runtimeType);
        }
        return obj ?? RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter((RuntimeType)typeof(ObjectComparer<object>), runtimeType);
    }
References System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(), System.obj, System.Collections.Generic.ComparerHelpers.TryCreateEnumComparer(), System.Collections.Generic.ComparerHelpers.TryCreateNullableComparer(), and System.type.