Terraria: System.Xml.XmlEncodedRawTextWriter.WriteCDataSection
WriteCDataSection()
unsafe void System.Xml.XmlEncodedRawTextWriter.WriteCDataSection (string text) inline protected inherited
Definition at line 1210 of file XmlEncodedRawTextWriter.cs.
    {
        if (text.Length == 0)
        {
            if (_bufPos >= _bufLen)
            {
                FlushBuffer();
            }
            return;
        }
        fixed (char* ptr2 = text)
        {
            char[] bufChars = _bufChars;
            fixed (char[] array = bufChars)
            {
                char* ptr = (char*)((bufChars != null && array.Length != 0) ? Unsafe.AsPointer(ref array[0]) : null);
                char* ptr3 = ptr2;
                char* ptr4 = ptr2 + text.Length;
                char* ptr5 = ptr + _bufPos;
                int num = 0;
                while (true)
                {
                    char* ptr6 = ptr5 + (ptr4 - ptr3);
                    if (ptr6 > ptr + _bufLen)
                    {
                        ptr6 = ptr + _bufLen;
                    }
                    while (ptr5 < ptr6 && XmlCharType.IsAttributeValueChar((char)(num = *ptr3)) && num != 93)
                    {
                        *ptr5 = (char)num;
                        ptr5++;
                        ptr3++;
                    }
                    if (ptr3 >= ptr4)
                    {
                        break;
                    }
                    if (ptr5 >= ptr6)
                    {
                        _bufPos = (int)(ptr5 - ptr);
                        FlushBuffer();
                        ptr5 = ptr + 1;
                        continue;
                    }
                    switch (num)
                    {
                    case 62:
                        if (_hadDoubleBracket && ptr5[-1] == ']')
{
                            ptr5 = RawEndCData(ptr5);
                            ptr5 = RawStartCData(ptr5);
                        }
                        *ptr5 = '>';
                        ptr5++;
                        break;
                    case 93:
                        if (ptr5[-1] == ']')
{
                            _hadDoubleBracket = true;
                        }
                        else
{
                            _hadDoubleBracket = false;
                        }
                        *ptr5 = ']';
                        ptr5++;
                        break;
                    case 13:
                        if (_newLineHandling == NewLineHandling.Replace)
{
                            if (ptr3 + 1 < ptr4 && ptr3[1] == '\n')
{
                                ptr3++;
                            }
                            ptr5 = WriteNewLine(ptr5);
                        }
                        else
{
                            *ptr5 = (char)num;
                            ptr5++;
                        }
                        break;
                    case 10:
                        if (_newLineHandling == NewLineHandling.Replace)
{
                            ptr5 = WriteNewLine(ptr5);
                            break;
                        }
                        *ptr5 = (char)num;
                        ptr5++;
                        break;
                    case 9:
                    case 34:
                    case 38:
                    case 39:
                    case 60:
                        *ptr5 = (char)num;
                        ptr5++;
                        break;
                    default:
                        if (XmlCharType.IsSurrogate(num))
{
                            ptr5 = EncodeSurrogate(ptr3, ptr4, ptr5);
                            ptr3 += 2;
                        }
                        else if (num <= 127 || num >= 65534)
{
                            ptr5 = InvalidXmlChar(num, ptr5, entitize: false);
                            ptr3++;
                        }
                        else
{
                            *ptr5 = (char)num;
                            ptr5++;
                            ptr3++;
                        }
                        continue;
                    }
                    ptr3++;
                }
                _bufPos = (int)(ptr5 - ptr);
            }
        }
    }
References System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufLen, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.XmlEncodedRawTextWriter._hadDoubleBracket, System.Xml.XmlEncodedRawTextWriter._newLineHandling, System.array, System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.EncodeSurrogate(), System.Xml.XmlEncodedRawTextWriter.FlushBuffer(), System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsSurrogate(), System.Xml.XmlEncodedRawTextWriter.RawEndCData(), System.Xml.XmlEncodedRawTextWriter.RawStartCData(), System.text, and System.Xml.XmlEncodedRawTextWriter.WriteNewLine().
Referenced by System.Xml.XmlEncodedRawTextWriter.WriteCData().