Terraria: System.Xml.XmlEncodedRawTextWriter._RawTextAsync
_RawTextAsync()
async Task System.Xml.XmlEncodedRawTextWriter._RawTextAsync (string text1, int curIndex1, int leftCount1, string text2 = null, string text3 = null, string text4 = null) inline private inherited
Definition at line 2676 of file XmlEncodedRawTextWriter.cs.
    {
        await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
        int writeLen;
        do
        {
            writeLen = RawTextNoFlush(text1, curIndex1, leftCount1);
            curIndex1 += writeLen;
            leftCount1 -= writeLen;
            if (writeLen >= 0)
            {
                await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        while (writeLen >= 0);
        if (text2 != null)
        {
            await RawTextAsync(text2, text3, text4).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.FlushBufferAsync(), System.Xml.XmlEncodedRawTextWriter.RawTextAsync(), and System.Xml.XmlEncodedRawTextWriter.RawTextNoFlush().
Referenced by System.Xml.XmlEncodedRawTextWriter.RawTextAsync(), and System.Xml.XmlEncodedRawTextWriter.RawTextAsync().