Terraria: System.Xml.XmlEncodedRawTextWriter.FlushAsync
FlushAsync()
override async Task System.Xml.XmlEncodedRawTextWriter.FlushAsync () inline virtual inherited
Reimplemented from System.Xml.XmlWriter.
Definition at line 2066 of file XmlEncodedRawTextWriter.cs.
    {
        CheckAsyncCall();
        await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
        await FlushEncoderAsync().ConfigureAwait(continueOnCapturedContext: false);
        if (_stream != null)
        {
            await _stream.FlushAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        else if (_writer != null)
        {
            await _writer.FlushAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Xml.XmlEncodedRawTextWriter._stream, System.Xml.XmlEncodedRawTextWriter._writer, System.Xml.XmlEncodedRawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.IO.Stream.FlushAsync(), System.IO.TextWriter.FlushAsync(), System.Xml.XmlEncodedRawTextWriter.FlushBufferAsync(), and System.Xml.XmlEncodedRawTextWriter.FlushEncoderAsync().