Terraria: System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclarationAsync
WriteXmlDeclarationAsync() [2/2]
override async Task System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclarationAsync (XmlStandalone standalone) inline package virtual inherited
Reimplemented from System.Xml.XmlRawWriter.
Definition at line 1605 of file XmlEncodedRawTextWriter.cs.
    {
        CheckAsyncCall();
        if (!_omitXmlDeclaration && !_autoXmlDeclaration)
        {
            if (_trackTextContent && _inTextContent)
            {
                ChangeTextContentMark(value: false);
            }
            await RawTextAsync("<?xml version=\"").ConfigureAwait(continueOnCapturedContext: false);
            await RawTextAsync("1.0").ConfigureAwait(continueOnCapturedContext: false);
            if (_encoding != null)
            {
                await RawTextAsync("\" encoding=\"").ConfigureAwait(continueOnCapturedContext: false);
                await RawTextAsync(_encoding.WebName).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (standalone != 0)
            {
                await RawTextAsync("\" standalone=\"").ConfigureAwait(continueOnCapturedContext: false);
                await RawTextAsync((standalone == XmlStandalone.Yes) ? "yes" : "no").ConfigureAwait(continueOnCapturedContext: false);
            }
            await RawTextAsync("\"?>").ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Xml.XmlEncodedRawTextWriter._autoXmlDeclaration, System.Xml.XmlEncodedRawTextWriter._encoding, System.Xml.XmlEncodedRawTextWriter._inTextContent, System.Xml.XmlEncodedRawTextWriter._omitXmlDeclaration, System.Xml.XmlEncodedRawTextWriter._trackTextContent, System.Xml.XmlEncodedRawTextWriter.ChangeTextContentMark(), System.Xml.XmlEncodedRawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.RawTextAsync(), System.value, and System.Text.Encoding.WebName.