Terraria: System.Xml.XmlEncodedRawTextWriter.EncodeChar
EncodeChar()
unsafe void System.Xml.XmlEncodedRawTextWriter.EncodeChar (ref char * pSrc, char * pSrcEnd, ref char * pDst) inline package inherited
Definition at line 1372 of file XmlEncodedRawTextWriter.cs.
    {
        int num = *pSrc;
        if (XmlCharType.IsSurrogate(num))
        {
            pDst = EncodeSurrogate(pSrc, pSrcEnd, pDst);
            pSrc += 2;
        }
        else if (num <= 127 || num >= 65534)
        {
            pDst = InvalidXmlChar(num, pDst, entitize: false);
            pSrc++;
        }
        else
        {
            *pDst = (char)num;
            pDst++;
            pSrc++;
        }
    }
References System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.EncodeSurrogate(), System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(), and System.Xml.XmlCharType.IsSurrogate().
Referenced by System.Xml.HtmlEncodedRawTextWriter.WriteHtmlAttributeText().