Terraria: System.Xml.XmlEncodedRawTextWriter.EncodeCharsAsync
EncodeCharsAsync()
async Task System.Xml.XmlEncodedRawTextWriter.EncodeCharsAsync (int startOffset, int endOffset, bool writeAllToStream) inline private inherited
Definition at line 2128 of file XmlEncodedRawTextWriter.cs.
    {
        while (startOffset < endOffset)
        {
            if (_charEntityFallback != null)
            {
                _charEntityFallback.StartOffset = startOffset;
            }
            _encoder.Convert(_bufChars, startOffset, endOffset - startOffset, _bufBytes, _bufBytesUsed, _bufBytes.Length - _bufBytesUsed, flush: false, out var charsUsed, out var bytesUsed, out var _);
            startOffset += charsUsed;
            _bufBytesUsed += bytesUsed;
            if (_bufBytesUsed >= _bufBytes.Length - 16)
            {
                await _stream.WriteAsync(_bufBytes.AsMemory(0, _bufBytesUsed)).ConfigureAwait(continueOnCapturedContext: false);
                _bufBytesUsed = 0;
            }
        }
        if (writeAllToStream && _bufBytesUsed > 0)
        {
            await _stream.WriteAsync(_bufBytes.AsMemory(0, _bufBytesUsed)).ConfigureAwait(continueOnCapturedContext: false);
            _bufBytesUsed = 0;
        }
    }
References System.Xml.XmlEncodedRawTextWriter._bufBytes, System.Xml.XmlEncodedRawTextWriter._bufBytesUsed, System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._charEntityFallback, System.Xml.XmlEncodedRawTextWriter._encoder, System.Xml.XmlEncodedRawTextWriter._stream, System.Text.Encoder.Convert(), System.Xml.Dictionary, and System.IO.Stream.WriteAsync().
Referenced by System.Xml.XmlEncodedRawTextWriter.FlushBufferAsync().