Terraria: System.Xml.XmlEncodedRawTextWriter.FlushBufferAsync
FlushBufferAsync()
virtual async Task System.Xml.XmlEncodedRawTextWriter.FlushBufferAsync () inline protected virtual inherited
Definition at line 2081 of file XmlEncodedRawTextWriter.cs.
    {
        _ = 1;
        try
        {
            if (_writeToNull)
            {
                return;
            }
            if (_stream != null)
            {
                if (_trackTextContent)
                {
                    _charEntityFallback.Reset(_textContentMarks, _lastMarkPos);
                    if (((uint)_lastMarkPos & (true ? 1u : 0u)) != 0)
                    {
                        _textContentMarks[1] = 1;
                        _lastMarkPos = 1;
                    }
                    else
                    {
                        _lastMarkPos = 0;
                    }
                }
                await EncodeCharsAsync(1, _bufPos, writeAllToStream: true).ConfigureAwait(continueOnCapturedContext: false);
            }
            else if (_bufPos - 1 > 0)
            {
                await _writer.WriteAsync(_bufChars.AsMemory(1, _bufPos - 1)).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        catch
        {
            _writeToNull = true;
            throw;
        }
        finally
        {
            _bufChars[0] = _bufChars[_bufPos - 1];
            _textPos = ((_textPos == _bufPos) ? 1 : 0);
            _attrEndPos = ((_attrEndPos == _bufPos) ? 1 : 0);
            _contentPos = 0;
            _cdataPos = 0;
            _bufPos = 1;
        }
    }
References System.Xml.XmlEncodedRawTextWriter._attrEndPos, System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.XmlEncodedRawTextWriter._cdataPos, System.Xml.XmlEncodedRawTextWriter._charEntityFallback, System.Xml.XmlEncodedRawTextWriter._contentPos, System.Xml.XmlEncodedRawTextWriter._lastMarkPos, System.Xml.XmlEncodedRawTextWriter._stream, System.Xml.XmlEncodedRawTextWriter._textContentMarks, System.Xml.XmlEncodedRawTextWriter._textPos, System.Xml.XmlEncodedRawTextWriter._trackTextContent, System.Xml.XmlEncodedRawTextWriter._writer, System.Xml.XmlEncodedRawTextWriter._writeToNull, System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.EncodeCharsAsync(), System.Xml.CharEntityEncoderFallback.Reset(), and System.IO.TextWriter.WriteAsync().
Referenced by System.Xml.XmlEncodedRawTextWriter._RawTextAsync(), System.Xml.XmlEncodedRawTextWriter._WriteAttributeTextBlockAsync(), System.Xml.XmlEncodedRawTextWriter._WriteElementTextBlockAsync(), System.Xml.XmlEncodedRawTextWriter.DisposeAsyncCore(), System.Xml.XmlEncodedRawTextWriter.FlushAsync(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSectionAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCharEntityAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPiAsync(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlockAsync(), System.Xml.XmlEncodedRawTextWriter.WriteEntityRefAsync(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharCheckingAsync(), and System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharCheckingAsync().