Terraria: System.Xml.XmlEncodedRawTextWriter.Flush
Flush()
override void System.Xml.XmlEncodedRawTextWriter.Flush () inline inherited
Definition at line 631 of file XmlEncodedRawTextWriter.cs.
    {
        FlushBuffer();
        FlushEncoder();
        if (_stream != null)
        {
            _stream.Flush();
        }
        else if (_writer != null)
        {
            _writer.Flush();
        }
    }
References System.Xml.XmlEncodedRawTextWriter._stream, System.Xml.XmlEncodedRawTextWriter._writer, System.IO.Stream.Flush(), System.IO.TextWriter.Flush(), System.Xml.XmlEncodedRawTextWriter.FlushBuffer(), and System.Xml.XmlEncodedRawTextWriter.FlushEncoder().