Terraria: System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockAsync
WriteAttributeTextBlockAsync() [1/2]
async Task System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockAsync (char[] chars, int index, int count) inline protected inherited
Definition at line 2299 of file XmlEncodedRawTextWriter.cs.
    {
        int curIndex = index;
        int leftCount = count;
        int writeLen;
        do
        {
            writeLen = WriteAttributeTextBlockNoFlush(chars, curIndex, leftCount);
            curIndex += writeLen;
            leftCount -= writeLen;
            if (writeLen >= 0)
            {
                await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        while (writeLen >= 0);
    }
References System.chars, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.FlushBufferAsync(), System.index, and System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockNoFlush().
Referenced by System.Xml.XmlEncodedRawTextWriter.WriteCharsAsync(), System.Xml.XmlEncodedRawTextWriter.WriteStringAsync(), and System.Xml.XmlEncodedRawTextWriter.WriteWhitespaceAsync().