Terraria: System.Xml.XmlEncodedRawTextWriter._WriteElementTextBlockAsync
_WriteElementTextBlockAsync()
async Task System.Xml.XmlEncodedRawTextWriter._WriteElementTextBlockAsync (bool newLine, string text, int curIndex, int leftCount) inline private inherited
Definition at line 2531 of file XmlEncodedRawTextWriter.cs.
    {
        bool needWriteNewLine = false;
        if (!newLine)
        {
            await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            await RawTextAsync(_newLineChars).ConfigureAwait(continueOnCapturedContext: false);
            curIndex++;
            leftCount--;
        }
        int writeLen;
        do
        {
            writeLen = WriteElementTextBlockNoFlush(text, curIndex, leftCount, out needWriteNewLine);
            curIndex += writeLen;
            leftCount -= writeLen;
            if (needWriteNewLine)
            {
                await RawTextAsync(_newLineChars).ConfigureAwait(continueOnCapturedContext: false);
                curIndex++;
                leftCount--;
            }
            else if (writeLen >= 0)
            {
                await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        while (writeLen >= 0 || needWriteNewLine);
    }
References System.Xml.XmlEncodedRawTextWriter._newLineChars, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.FlushBufferAsync(), System.Xml.XmlEncodedRawTextWriter.RawTextAsync(), System.text, and System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlockNoFlush().
Referenced by System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlockAsync().