Terraria: System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclaration
WriteXmlDeclaration() [2/2]
override void System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclaration (XmlStandalone standalone) inline package virtual inherited
Reimplemented from System.Xml.XmlRawWriter.
Definition at line 162 of file XmlEncodedRawTextWriter.cs.
    {
        if (!_omitXmlDeclaration && !_autoXmlDeclaration)
        {
            if (_trackTextContent && _inTextContent)
            {
                ChangeTextContentMark(value: false);
            }
            RawText("<?xml version=\"");
            RawText("1.0");
            if (_encoding != null)
            {
                RawText("\" encoding=\"");
                RawText(_encoding.WebName);
            }
            if (standalone != 0)
            {
                RawText("\" standalone=\"");
                RawText((standalone == XmlStandalone.Yes) ? "yes" : "no");
            }
            RawText("\"?>");
        }
    }
References System.Xml.XmlEncodedRawTextWriter._autoXmlDeclaration, System.Xml.XmlEncodedRawTextWriter._encoding, System.Xml.XmlEncodedRawTextWriter._inTextContent, System.Xml.XmlEncodedRawTextWriter._omitXmlDeclaration, System.Xml.XmlEncodedRawTextWriter._trackTextContent, System.Xml.XmlEncodedRawTextWriter.ChangeTextContentMark(), System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.RawText(), System.value, and System.Text.Encoding.WebName.
Referenced by System.Xml.XmlEncodedRawTextWriter.XmlEncodedRawTextWriter(), and System.Xml.XmlEncodedRawTextWriter.XmlEncodedRawTextWriter().