Terraria: System.Xml.XmlEncodedRawTextWriter.WriteProcessingInstruction
WriteProcessingInstruction() [1/2]
override void System.Xml.XmlEncodedRawTextWriter.WriteProcessingInstruction (string name, string text) inline
Definition at line 418 of file XmlEncodedRawTextWriter.cs.
    {
        if (_trackTextContent && _inTextContent)
        {
            ChangeTextContentMark(value: false);
        }
        _bufChars[_bufPos++] = '<';
        _bufChars[_bufPos++] = '?';
        RawText(name);
        if (text.Length > 0)
        {
            _bufChars[_bufPos++] = ' ';
            WriteCommentOrPi(text, 63);
        }
        _bufChars[_bufPos++] = '?';
        _bufChars[_bufPos++] = '>';
    }
References System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.XmlEncodedRawTextWriter._inTextContent, System.Xml.XmlEncodedRawTextWriter._trackTextContent, System.Xml.XmlEncodedRawTextWriter.ChangeTextContentMark(), System.Xml.XmlEncodedRawTextWriter.RawText(), System.text, System.value, and System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPi().
Referenced by System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclaration().