Terraria: System.Xml.XmlEncodedRawTextWriter.WriteCDataSectionNoFlush
WriteCDataSectionNoFlush()
unsafe int System.Xml.XmlEncodedRawTextWriter.WriteCDataSectionNoFlush (string text, int index, int count, out bool needWriteNewLine) inline protected inherited
Definition at line 3021 of file XmlEncodedRawTextWriter.cs.
    {
        needWriteNewLine = false;
        if (count == 0)
        {
            return -1;
        }
        fixed (char* ptr = text)
        {
            char* ptr2 = ptr + index;
            char[] bufChars = _bufChars;
            fixed (char[] array = bufChars)
            {
                char* ptr3 = (char*)((bufChars != null && array.Length != 0) ? Unsafe.AsPointer(ref array[0]) : null);
                char* ptr4 = ptr2;
                char* ptr5 = ptr2 + count;
                char* ptr6 = ptr4;
                char* ptr7 = ptr3 + _bufPos;
                int num = 0;
                while (true)
                {
                    char* ptr8 = ptr7 + (ptr5 - ptr4);
                    if (ptr8 > ptr3 + _bufLen)
                    {
                        ptr8 = ptr3 + _bufLen;
                    }
                    while (ptr7 < ptr8 && XmlCharType.IsAttributeValueChar((char)(num = *ptr4)) && num != 93)
                    {
                        *ptr7 = (char)num;
                        ptr7++;
                        ptr4++;
                    }
                    if (ptr4 >= ptr5)
                    {
                        break;
                    }
                    if (ptr7 >= ptr8)
                    {
                        _bufPos = (int)(ptr7 - ptr3);
                        return (int)(ptr4 - ptr6);
                    }
                    switch (num)
                    {
                    case 62:
                        if (_hadDoubleBracket && ptr7[-1] == ']')
{
                            ptr7 = RawEndCData(ptr7);
                            ptr7 = RawStartCData(ptr7);
                        }
                        *ptr7 = '>';
                        ptr7++;
                        break;
                    case 93:
                        if (ptr7[-1] == ']')
{
                            _hadDoubleBracket = true;
                        }
                        else
{
                            _hadDoubleBracket = false;
                        }
                        *ptr7 = ']';
                        ptr7++;
                        break;
                    case 13:
                        if (_newLineHandling == NewLineHandling.Replace)
{
                            if (ptr4 + 1 < ptr5 && ptr4[1] == '\n')
{
                                ptr4++;
                            }
                            _bufPos = (int)(ptr7 - ptr3);
                            needWriteNewLine = true;
                            return (int)(ptr4 - ptr6);
                        }
                        *ptr7 = (char)num;
                        ptr7++;
                        break;
                    case 10:
                        if (_newLineHandling == NewLineHandling.Replace)
{
                            _bufPos = (int)(ptr7 - ptr3);
                            needWriteNewLine = true;
                            return (int)(ptr4 - ptr6);
                        }
                        *ptr7 = (char)num;
                        ptr7++;
                        break;
                    case 9:
                    case 34:
                    case 38:
                    case 39:
                    case 60:
                        *ptr7 = (char)num;
                        ptr7++;
                        break;
                    default:
                        if (XmlCharType.IsSurrogate(num))
{
                            ptr7 = EncodeSurrogate(ptr4, ptr5, ptr7);
                            ptr4 += 2;
                        }
                        else if (num <= 127 || num >= 65534)
{
                            ptr7 = InvalidXmlChar(num, ptr7, entitize: false);
                            ptr4++;
                        }
                        else
{
                            *ptr7 = (char)num;
                            ptr7++;
                            ptr4++;
                        }
                        continue;
                    }
                    ptr4++;
                }
                _bufPos = (int)(ptr7 - ptr3);
            }
            return -1;
        }
    }
References System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufLen, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.XmlEncodedRawTextWriter._hadDoubleBracket, System.Xml.XmlEncodedRawTextWriter._newLineHandling, System.array, System.count, System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.EncodeSurrogate(), System.index, System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsSurrogate(), System.Xml.XmlEncodedRawTextWriter.RawEndCData(), System.Xml.XmlEncodedRawTextWriter.RawStartCData(), and System.text.
Referenced by System.Xml.XmlEncodedRawTextWriter.WriteCDataSectionAsync().