Terraria: System.Xml.XmlEncodedRawTextWriter.RawTextAsync
RawTextAsync() [1/2]
Task System.Xml.XmlEncodedRawTextWriter.RawTextAsync (string text) inline protected inherited
Definition at line 2632 of file XmlEncodedRawTextWriter.cs.
    {
        int num = RawTextNoFlush(text, 0, text.Length);
        if (num < 0)
        {
            return Task.CompletedTask;
        }
        return _RawTextAsync(text, num, text.Length - num);
    }
References System.Xml.XmlEncodedRawTextWriter._RawTextAsync(), System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.XmlEncodedRawTextWriter.RawTextNoFlush(), and System.text.
Referenced by System.Xml.XmlEncodedRawTextWriter._RawTextAsync(), System.Xml.XmlEncodedRawTextWriter._WriteElementTextBlockAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSectionAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCharEntityAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPiAsync(), System.Xml.XmlEncodedRawTextWriter.WriteDocTypeAsync(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlockAsync(), System.Xml.XmlEncodedRawTextWriter.WriteEndElementAsync(), System.Xml.XmlEncodedRawTextWriter.WriteEntityRefAsync(), System.Xml.XmlEncodedRawTextWriter.WriteFullEndElementAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteIndentAsync(), System.Xml.XmlEncodedRawTextWriter.WriteProcessingInstructionAsync(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharCheckingAsync(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharCheckingAsync(), System.Xml.XmlEncodedRawTextWriter.WriteStartAttributeAsync(), System.Xml.XmlEncodedRawTextWriter.WriteStartElementAsync(), System.Xml.XmlEncodedRawTextWriter.WriteStartNamespaceDeclarationAsync(), System.Xml.XmlEncodedRawTextWriter.WriteSurrogateCharEntityAsync(), and System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclarationAsync().