Terraria: System.Xml.XmlEncodedRawTextWriter.RawText
RawText() [1/2]
unsafe void System.Xml.XmlEncodedRawTextWriter.RawText (char * pSrcBegin, char * pSrcEnd) inline protected inherited
Definition at line 943 of file XmlEncodedRawTextWriter.cs.
    {
        fixed (char* ptr = _bufChars)
        {
            char* ptr2 = ptr + _bufPos;
            char* ptr3 = pSrcBegin;
            int num = 0;
            while (true)
            {
                char* ptr4 = ptr2 + (pSrcEnd - ptr3);
                if (ptr4 > ptr + _bufLen)
                {
                    ptr4 = ptr + _bufLen;
                }
                for (; ptr2 < ptr4; ptr2++)
                {
                    if ((num = *ptr3) >= 55296)
                    {
                        break;
                    }
                    ptr3++;
                    *ptr2 = (char)num;
                }
                if (ptr3 >= pSrcEnd)
                {
                    break;
                }
                if (ptr2 >= ptr4)
                {
                    _bufPos = (int)(ptr2 - ptr);
                    FlushBuffer();
                    ptr2 = ptr + 1;
                }
                else if (XmlCharType.IsSurrogate(num))
                {
                    ptr2 = EncodeSurrogate(ptr3, pSrcEnd, ptr2);
                    ptr3 += 2;
                }
                else if (num <= 127 || num >= 65534)
                {
                    ptr2 = InvalidXmlChar(num, ptr2, entitize: false);
                    ptr3++;
                }
                else
                {
                    *ptr2 = (char)num;
                    ptr2++;
                    ptr3++;
                }
            }
            _bufPos = (int)(ptr2 - ptr);
        }
    }
References System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufLen, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.EncodeSurrogate(), System.Xml.XmlEncodedRawTextWriter.FlushBuffer(), System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(), and System.Xml.XmlCharType.IsSurrogate().