Terraria: System.Xml.XmlEncodedRawTextWriter.EncodeSurrogate
EncodeSurrogate()
static unsafe char * System.Xml.XmlEncodedRawTextWriter.EncodeSurrogate (char * pSrc, char * pSrcEnd, char * pDst) inline static private inherited
Definition at line 1335 of file XmlEncodedRawTextWriter.cs.
    {
        int num = *pSrc;
        if (num <= 56319)
        {
            if (pSrc + 1 < pSrcEnd)
            {
                int num2 = pSrc[1];
                if (num2 >= 56320 && (System.LocalAppContextSwitches.DontThrowOnInvalidSurrogatePairs || num2 <= 57343))
                {
                    *pDst = (char)num;
                    pDst[1] = (char)num2;
                    pDst += 2;
                    return pDst;
                }
                throw XmlConvert.CreateInvalidSurrogatePairException((char)num2, (char)num);
            }
            throw new ArgumentException(System.SR.Xml_InvalidSurrogateMissingLowChar);
        }
        throw XmlConvert.CreateInvalidHighSurrogateCharException((char)num);
    }
References System.Xml.ArgumentException, System.Xml.XmlConvert.CreateInvalidHighSurrogateCharException(), System.Xml.XmlConvert.CreateInvalidSurrogatePairException(), System.Xml.Dictionary, System.LocalAppContextSwitches.DontThrowOnInvalidSurrogatePairs, and System.SR.Xml_InvalidSurrogateMissingLowChar.
Referenced by System.Xml.XmlEncodedRawTextWriter.EncodeChar(), System.Xml.XmlEncodedRawTextWriter.RawText(), System.Xml.XmlEncodedRawTextWriter.RawTextNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSection(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSectionNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPi(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPiNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlockNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharChecking(), and System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharCheckingNoFlush().