Terraria: System.Xml.XmlEncodedRawTextWriter.RawTextNoFlush
RawTextNoFlush() [1/2]
unsafe int System.Xml.XmlEncodedRawTextWriter.RawTextNoFlush (char * pSrcBegin, char * pSrcEnd) inline protected inherited
Definition at line 2564 of file XmlEncodedRawTextWriter.cs.
    {
        fixed (char* ptr = _bufChars)
        {
            char* ptr2 = ptr + _bufPos;
            char* ptr3 = pSrcBegin;
            int num = 0;
            while (true)
            {
                char* ptr4 = ptr2 + (pSrcEnd - ptr3);
                if (ptr4 > ptr + _bufLen)
                {
                    ptr4 = ptr + _bufLen;
                }
                for (; ptr2 < ptr4; ptr2++)
                {
                    if ((num = *ptr3) >= 55296)
                    {
                        break;
                    }
                    ptr3++;
                    *ptr2 = (char)num;
                }
                if (ptr3 >= pSrcEnd)
                {
                    break;
                }
                if (ptr2 >= ptr4)
                {
                    _bufPos = (int)(ptr2 - ptr);
                    return (int)(ptr3 - pSrcBegin);
                }
                if (XmlCharType.IsSurrogate(num))
                {
                    ptr2 = EncodeSurrogate(ptr3, pSrcEnd, ptr2);
                    ptr3 += 2;
                }
                else if (num <= 127 || num >= 65534)
                {
                    ptr2 = InvalidXmlChar(num, ptr2, entitize: false);
                    ptr3++;
                }
                else
                {
                    *ptr2 = (char)num;
                    ptr2++;
                    ptr3++;
                }
            }
            _bufPos = (int)(ptr2 - ptr);
        }
        return -1;
    }
References System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufLen, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.EncodeSurrogate(), System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(), and System.Xml.XmlCharType.IsSurrogate().
Referenced by System.Xml.XmlEncodedRawTextWriter._RawTextAsync(), System.Xml.XmlEncodedRawTextWriter.RawTextAsync(), System.Xml.XmlEncodedRawTextWriter.RawTextAsync(), and System.Xml.XmlEncodedRawTextWriter.RawTextNoFlush().