Terraria: System.Xml.XmlEncodedRawTextWriter.RawText
RawText() [2/2]
unsafe void System.Xml.XmlEncodedRawTextWriter.RawText (string s) inline protected inherited
Definition at line 935 of file XmlEncodedRawTextWriter.cs.
    {
        fixed (char* ptr = s)
        {
            RawText(ptr, ptr + s.Length);
        }
    }
References System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.RawText(), and System.s.
Referenced by System.Xml.XmlEncodedRawTextWriter.RawText(), System.Xml.XmlEncodedRawTextWriter.WriteCharEntity(), System.Xml.HtmlEncodedRawTextWriter.WriteDocType(), System.Xml.XmlEncodedRawTextWriter.WriteDocType(), System.Xml.HtmlEncodedRawTextWriter.WriteEndElement(), System.Xml.XmlEncodedRawTextWriter.WriteEndElement(), System.Xml.XmlEncodedRawTextWriter.WriteEntityRef(), System.Xml.HtmlEncodedRawTextWriter.WriteFullEndElement(), System.Xml.XmlEncodedRawTextWriter.WriteFullEndElement(), System.Xml.HtmlEncodedRawTextWriter.WriteHtmlElementTextBlock(), System.Xml.HtmlEncodedRawTextWriterIndent.WriteIndent(), System.Xml.XmlEncodedRawTextWriterIndent.WriteIndent(), System.Xml.HtmlEncodedRawTextWriter.WriteMetaElement(), System.Xml.XmlEncodedRawTextWriter.WriteNewLine(), System.Xml.XmlEncodedRawTextWriter.WriteProcessingInstruction(), System.Xml.HtmlEncodedRawTextWriter.WriteProcessingInstruction(), System.Xml.HtmlEncodedRawTextWriter.WriteStartAttribute(), System.Xml.HtmlEncodedRawTextWriterIndent.WriteStartAttribute(), System.Xml.XmlEncodedRawTextWriter.WriteStartAttribute(), System.Xml.HtmlEncodedRawTextWriter.WriteStartElement(), System.Xml.HtmlEncodedRawTextWriterIndent.WriteStartElement(), System.Xml.XmlEncodedRawTextWriter.WriteStartElement(), System.Xml.XmlEncodedRawTextWriter.WriteStartNamespaceDeclaration(), System.Xml.XmlEncodedRawTextWriter.WriteSurrogateCharEntity(), and System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclaration().