Terraria: System.Xml.XmlEncodedRawTextWriter.WriteRawAsync
WriteRawAsync() [2/2]
override async Task System.Xml.XmlEncodedRawTextWriter.WriteRawAsync (string data) inline virtual
Reimplemented from System.Xml.XmlWriter.
Reimplemented in System.Xml.XmlEncodedRawTextWriterIndent.
Definition at line 2055 of file XmlEncodedRawTextWriter.cs.
    {
        CheckAsyncCall();
        if (_trackTextContent && _inTextContent)
        {
            ChangeTextContentMark(value: false);
        }
        await WriteRawWithCharCheckingAsync(data).ConfigureAwait(continueOnCapturedContext: false);
        _textPos = _bufPos;
    }
References System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.XmlEncodedRawTextWriter._inTextContent, System.Xml.XmlEncodedRawTextWriter._textPos, System.Xml.XmlEncodedRawTextWriter._trackTextContent, System.Xml.XmlEncodedRawTextWriter.ChangeTextContentMark(), System.Xml.XmlEncodedRawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.value, and System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharCheckingAsync().