Terraria: System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar
InvalidXmlChar()
unsafe char * System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar (int ch, char * pDst, bool entitize) inline private inherited
Definition at line 1357 of file XmlEncodedRawTextWriter.cs.
    {
        if (_checkCharacters)
        {
            throw XmlConvert.CreateInvalidCharException((char)ch, '\0');
        }
        if (entitize)
        {
            return CharEntity(pDst, (char)ch);
        }
        *pDst = (char)ch;
        pDst++;
        return pDst;
    }
References System.Xml.XmlEncodedRawTextWriter._checkCharacters, System.ch, System.Xml.XmlEncodedRawTextWriter.CharEntity(), System.Xml.XmlConvert.CreateInvalidCharException(), and System.Xml.Dictionary.
Referenced by System.Xml.XmlEncodedRawTextWriter.EncodeChar(), System.Xml.XmlEncodedRawTextWriter.RawText(), System.Xml.XmlEncodedRawTextWriter.RawTextNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSection(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSectionNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPi(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPiNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlockNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharChecking(), and System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharCheckingNoFlush().