Terraria: WorkshopHelper.UGCBased.APublisherInstance.UpdateItem
UpdateItem()
void WorkshopHelper.UGCBased.APublisherInstance.UpdateItem () inline private inherited
             {
                 //IL_002e: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0034: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0039: Unknown result type (might be due to invalid IL or missing references)
                 //IL_003e: Unknown result type (might be due to invalid IL or missing references)
                 //IL_004c: Unknown result type (might be due to invalid IL or missing references)
                 //IL_007d: Unknown result type (might be due to invalid IL or missing references)
                 //IL_008f: Unknown result type (might be due to invalid IL or missing references)
                 //IL_006b: Unknown result type (might be due to invalid IL or missing references)
                 //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
                 //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
                 //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
                 //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
                 //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
                 //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0108: Unknown result type (might be due to invalid IL or missing references)
                 //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
                 //IL_00de: Unknown result type (might be due to invalid IL or missing references)
                 string headerText = GetHeaderText();
                 if (!TryWritingManifestToFolder(_entryData.ContentFolderPath, headerText))
                 {
                     _endAction(this);
                     return;
                 }
                 PrepareContentForUpdate();
                 UGCUpdateHandle_t val = SteamUGC.StartItemUpdate(SteamUtils.GetAppID(), _publishedFileID);
                 if (_entryData.Title != null)
                 {
                     SteamUGC.SetItemTitle(val, _entryData.Title);
                 }
                 if (_entryData.Description != null)
                 {
                     SteamUGC.SetItemDescription(val, _entryData.Description);
                 }
                 SteamUGC.SetItemContent(val, _entryData.ContentFolderPath);
                 SteamUGC.SetItemTags(val, (IList<string>)_entryData.Tags);
                 if (_entryData.PreviewImagePath != null)
                 {
                     SteamUGC.SetItemPreview(val, _entryData.PreviewImagePath);
                 }
                 if (_entryData.Visibility.HasValue)
                 {
                     SteamUGC.SetItemVisibility(val, _entryData.Visibility.Value);
                 }
                 CoreSocialModule.SetSkipPulsing(shouldSkipPausing: true);
                 SteamAPICall_t val2 = SteamUGC.SubmitItemUpdate(val, "");
                 _updateHandle = val;
                 _updateItemHook.Set(val2, (APIDispatchDelegate<SubmitItemUpdateResult_t>)UpdateItemResult);
                 CoreSocialModule.SetSkipPulsing(shouldSkipPausing: false);
             }
References WorkshopHelper.UGCBased.APublisherInstance._endAction, WorkshopHelper.UGCBased.APublisherInstance._entryData, WorkshopHelper.UGCBased.APublisherInstance._publishedFileID, WorkshopHelper.UGCBased.APublisherInstance._updateHandle, WorkshopHelper.UGCBased.APublisherInstance._updateItemHook, WorkshopHelper.UGCBased.SteamWorkshopItem.ContentFolderPath, WorkshopHelper.UGCBased.SteamWorkshopItem.Description, WorkshopHelper.UGCBased.APublisherInstance.GetHeaderText(), WorkshopHelper.UGCBased.APublisherInstance.PrepareContentForUpdate(), WorkshopHelper.UGCBased.SteamWorkshopItem.PreviewImagePath, CoreSocialModule.SetSkipPulsing(), WorkshopHelper.UGCBased.SteamWorkshopItem.Tags, WorkshopHelper.UGCBased.SteamWorkshopItem.Title, WorkshopHelper.UGCBased.APublisherInstance.TryWritingManifestToFolder(), WorkshopHelper.UGCBased.APublisherInstance.UpdateItemResult(), and WorkshopHelper.UGCBased.SteamWorkshopItem.Visibility.
Referenced by WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult(), and WorkshopHelper.UGCBased.APublisherInstance.PublishContent().