Terraria: System.Xml.XmlEncodedRawTextWriter.CheckAsyncCall
CheckAsyncCall()
void System.Xml.XmlEncodedRawTextWriter.CheckAsyncCall () inline protected inherited
Definition at line 1597 of file XmlEncodedRawTextWriter.cs.
    {
        if (!_useAsync)
        {
            throw new InvalidOperationException(System.SR.Xml_WriterAsyncNotSetException);
        }
    }
References System.Xml.XmlEncodedRawTextWriter._useAsync, and System.SR.Xml_WriterAsyncNotSetException.
Referenced by System.Xml.XmlEncodedRawTextWriter.FlushAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteBase64Async(), System.Xml.XmlEncodedRawTextWriter.WriteCDataAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteCDataAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCharEntityAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteCharEntityAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCharsAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteCharsAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCommentAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteCommentAsync(), System.Xml.XmlEncodedRawTextWriter.WriteDocTypeAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteDocTypeAsync(), System.Xml.XmlEncodedRawTextWriter.WriteEndAttributeAsync(), System.Xml.XmlEncodedRawTextWriter.WriteEndElementAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteEndElementAsync(), System.Xml.XmlEncodedRawTextWriter.WriteEndNamespaceDeclarationAsync(), System.Xml.XmlEncodedRawTextWriter.WriteEntityRefAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteEntityRefAsync(), System.Xml.XmlEncodedRawTextWriter.WriteFullEndElementAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteFullEndElementAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteIndentAsync(), System.Xml.XmlEncodedRawTextWriter.WriteNamespaceDeclarationAsync(), System.Xml.XmlEncodedRawTextWriter.WriteProcessingInstructionAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteProcessingInstructionAsync(), System.Xml.XmlEncodedRawTextWriter.WriteRawAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteRawAsync(), System.Xml.XmlEncodedRawTextWriter.WriteRawAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteRawAsync(), System.Xml.XmlEncodedRawTextWriter.WriteStartAttributeAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteStartAttributeAsync(), System.Xml.XmlEncodedRawTextWriter.WriteStartElementAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteStartElementAsync(), System.Xml.XmlEncodedRawTextWriter.WriteStartNamespaceDeclarationAsync(), System.Xml.XmlEncodedRawTextWriter.WriteStringAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteStringAsync(), System.Xml.XmlEncodedRawTextWriter.WriteSurrogateCharEntityAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteSurrogateCharEntityAsync(), System.Xml.XmlEncodedRawTextWriter.WriteWhitespaceAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteWhitespaceAsync(), System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclarationAsync(), and System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclarationAsync().