Terraria: System.Xml.XmlEncodedRawTextWriter._WriteAttributeTextBlockAsync
_WriteAttributeTextBlockAsync()
async Task System.Xml.XmlEncodedRawTextWriter._WriteAttributeTextBlockAsync (string text, int curIndex, int leftCount) inline private inherited
Definition at line 2332 of file XmlEncodedRawTextWriter.cs.
    {
        await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
        int writeLen;
        do
        {
            writeLen = WriteAttributeTextBlockNoFlush(text, curIndex, leftCount);
            curIndex += writeLen;
            leftCount -= writeLen;
            if (writeLen >= 0)
            {
                await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        while (writeLen >= 0);
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.FlushBufferAsync(), System.text, and System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockNoFlush().
Referenced by System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockAsync().