Terraria: System.Xml.XmlEncodedRawTextWriter.WriteNamespaceDeclaration
WriteNamespaceDeclaration()
override void System.Xml.XmlEncodedRawTextWriter.WriteNamespaceDeclaration (string prefix, string namespaceName) inline package inherited
Definition at line 330 of file XmlEncodedRawTextWriter.cs.
    {
        WriteStartNamespaceDeclaration(prefix);
        WriteString(namespaceName);
        WriteEndNamespaceDeclaration();
    }
References System.Xml.Dictionary, System.prefix, System.Xml.XmlEncodedRawTextWriter.WriteEndNamespaceDeclaration(), System.Xml.XmlEncodedRawTextWriter.WriteStartNamespaceDeclaration(), and System.Xml.XmlEncodedRawTextWriter.WriteString().