Terraria: System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockNoFlush
WriteAttributeTextBlockNoFlush() [1/3]
unsafe int System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockNoFlush (char * pSrc, char * pSrcEnd) inline protected inherited
Definition at line 2165 of file XmlEncodedRawTextWriter.cs.
    {
        char* ptr = pSrc;
        fixed (char* ptr2 = _bufChars)
        {
            char* ptr3 = ptr2 + _bufPos;
            int num = 0;
            while (true)
            {
                char* ptr4 = ptr3 + (pSrcEnd - pSrc);
                if (ptr4 > ptr2 + _bufLen)
                {
                    ptr4 = ptr2 + _bufLen;
                }
                while (ptr3 < ptr4 && XmlCharType.IsAttributeValueChar((char)(num = *pSrc)))
                {
                    *ptr3 = (char)num;
                    ptr3++;
                    pSrc++;
                }
                if (pSrc >= pSrcEnd)
                {
                    break;
                }
                if (ptr3 >= ptr4)
                {
                    _bufPos = (int)(ptr3 - ptr2);
                    return (int)(pSrc - ptr);
                }
                switch (num)
                {
                case 38:
                    ptr3 = AmpEntity(ptr3);
                    break;
                case 60:
                    ptr3 = LtEntity(ptr3);
                    break;
                case 62:
                    ptr3 = GtEntity(ptr3);
                    break;
                case 34:
                    ptr3 = QuoteEntity(ptr3);
                    break;
                case 39:
                    *ptr3 = (char)num;
                    ptr3++;
                    break;
                case 9:
                    if (_newLineHandling == NewLineHandling.None)
                    {
                        *ptr3 = (char)num;
                        ptr3++;
                    }
                    else
                    {
                        ptr3 = TabEntity(ptr3);
                    }
                    break;
                case 13:
                    if (_newLineHandling == NewLineHandling.None)
                    {
                        *ptr3 = (char)num;
                        ptr3++;
                    }
                    else
                    {
                        ptr3 = CarriageReturnEntity(ptr3);
                    }
                    break;
                case 10:
                    if (_newLineHandling == NewLineHandling.None)
                    {
                        *ptr3 = (char)num;
                        ptr3++;
                    }
                    else
                    {
                        ptr3 = LineFeedEntity(ptr3);
                    }
                    break;
                default:
                    if (XmlCharType.IsSurrogate(num))
                    {
                        ptr3 = EncodeSurrogate(pSrc, pSrcEnd, ptr3);
                        pSrc += 2;
                    }
                    else if (num <= 127 || num >= 65534)
                    {
                        ptr3 = InvalidXmlChar(num, ptr3, entitize: true);
                        pSrc++;
                    }
                    else
                    {
                        *ptr3 = (char)num;
                        ptr3++;
                        pSrc++;
                    }
                    continue;
                }
                pSrc++;
            }
            _bufPos = (int)(ptr3 - ptr2);
        }
        return -1;
    }
References System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufLen, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.XmlEncodedRawTextWriter._newLineHandling, System.Xml.XmlEncodedRawTextWriter.AmpEntity(), System.Xml.XmlEncodedRawTextWriter.CarriageReturnEntity(), System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.EncodeSurrogate(), System.Xml.XmlEncodedRawTextWriter.GtEntity(), System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsSurrogate(), System.Xml.XmlEncodedRawTextWriter.LineFeedEntity(), System.Xml.XmlEncodedRawTextWriter.LtEntity(), System.Xml.XmlEncodedRawTextWriter.QuoteEntity(), and System.Xml.XmlEncodedRawTextWriter.TabEntity().
Referenced by System.Xml.XmlEncodedRawTextWriter._WriteAttributeTextBlockAsync(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockAsync(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockAsync(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockNoFlush(), and System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockNoFlush().