Terraria: System.Xml.XmlEncodedRawTextWriter.FlushBuffer
FlushBuffer()
virtual void System.Xml.XmlEncodedRawTextWriter.FlushBuffer () inline protected virtual inherited
Reimplemented in System.Xml.HtmlEncodedRawTextWriterIndent.
Definition at line 645 of file XmlEncodedRawTextWriter.cs.
    {
        try
        {
            if (_writeToNull)
            {
                return;
            }
            if (_stream != null)
            {
                if (_trackTextContent)
                {
                    _charEntityFallback.Reset(_textContentMarks, _lastMarkPos);
                    if (((uint)_lastMarkPos & (true ? 1u : 0u)) != 0)
                    {
                        _textContentMarks[1] = 1;
                        _lastMarkPos = 1;
                    }
                    else
                    {
                        _lastMarkPos = 0;
                    }
                }
                EncodeChars(1, _bufPos, writeAllToStream: true);
            }
            else if (_bufPos - 1 > 0)
            {
                _writer.Write(_bufChars, 1, _bufPos - 1);
            }
        }
        catch
        {
            _writeToNull = true;
            throw;
        }
        finally
        {
            _bufChars[0] = _bufChars[_bufPos - 1];
            _textPos = ((_textPos == _bufPos) ? 1 : 0);
            _attrEndPos = ((_attrEndPos == _bufPos) ? 1 : 0);
            _contentPos = 0;
            _cdataPos = 0;
            _bufPos = 1;
        }
    }
References System.Xml.XmlEncodedRawTextWriter._attrEndPos, System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.XmlEncodedRawTextWriter._cdataPos, System.Xml.XmlEncodedRawTextWriter._charEntityFallback, System.Xml.XmlEncodedRawTextWriter._contentPos, System.Xml.XmlEncodedRawTextWriter._lastMarkPos, System.Xml.XmlEncodedRawTextWriter._stream, System.Xml.XmlEncodedRawTextWriter._textContentMarks, System.Xml.XmlEncodedRawTextWriter._textPos, System.Xml.XmlEncodedRawTextWriter._trackTextContent, System.Xml.XmlEncodedRawTextWriter._writer, System.Xml.XmlEncodedRawTextWriter._writeToNull, System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.EncodeChars(), System.Xml.CharEntityEncoderFallback.Reset(), and System.IO.TextWriter.Write().
Referenced by System.Xml.XmlEncodedRawTextWriter.Close(), System.Xml.XmlEncodedRawTextWriter.Flush(), System.Xml.XmlEncodedRawTextWriter.RawText(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSection(), System.Xml.XmlEncodedRawTextWriter.WriteCharEntity(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPi(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(), System.Xml.XmlEncodedRawTextWriter.WriteEntityRef(), System.Xml.HtmlEncodedRawTextWriter.WriteHtmlAttributeText(), System.Xml.HtmlEncodedRawTextWriter.WriteProcessingInstruction(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharChecking(), and System.Xml.HtmlEncodedRawTextWriter.WriteUriAttributeText().