Terraria: System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock
WriteElementTextBlock()
unsafe void System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock (char * pSrc, char * pSrcEnd) inline protected inherited
Definition at line 833 of file XmlEncodedRawTextWriter.cs.
    {
        fixed (char* ptr = _bufChars)
        {
            char* ptr2 = ptr + _bufPos;
            int num = 0;
            while (true)
            {
                char* ptr3 = ptr2 + (pSrcEnd - pSrc);
                if (ptr3 > ptr + _bufLen)
                {
                    ptr3 = ptr + _bufLen;
                }
                while (ptr2 < ptr3 && XmlCharType.IsAttributeValueChar((char)(num = *pSrc)))
                {
                    *ptr2 = (char)num;
                    ptr2++;
                    pSrc++;
                }
                if (pSrc >= pSrcEnd)
                {
                    break;
                }
                if (ptr2 >= ptr3)
                {
                    _bufPos = (int)(ptr2 - ptr);
                    FlushBuffer();
                    ptr2 = ptr + 1;
                    continue;
                }
                switch (num)
                {
                case 38:
                    ptr2 = AmpEntity(ptr2);
                    break;
                case 60:
                    ptr2 = LtEntity(ptr2);
                    break;
                case 62:
                    ptr2 = GtEntity(ptr2);
                    break;
                case 9:
                case 34:
                case 39:
                    *ptr2 = (char)num;
                    ptr2++;
                    break;
                case 10:
                    if (_newLineHandling == NewLineHandling.Replace)
                    {
                        ptr2 = WriteNewLine(ptr2);
                        break;
                    }
                    *ptr2 = (char)num;
                    ptr2++;
                    break;
                case 13:
                    switch (_newLineHandling)
                    {
                    case NewLineHandling.Replace:
                        if (pSrc + 1 < pSrcEnd && pSrc[1] == '\n')
{
                            pSrc++;
                        }
                        ptr2 = WriteNewLine(ptr2);
                        break;
                    case NewLineHandling.Entitize:
                        ptr2 = CarriageReturnEntity(ptr2);
                        break;
                    case NewLineHandling.None:
                        *ptr2 = (char)num;
                        ptr2++;
                        break;
                    }
                    break;
                default:
                    if (XmlCharType.IsSurrogate(num))
                    {
                        ptr2 = EncodeSurrogate(pSrc, pSrcEnd, ptr2);
                        pSrc += 2;
                    }
                    else if (num <= 127 || num >= 65534)
                    {
                        ptr2 = InvalidXmlChar(num, ptr2, entitize: true);
                        pSrc++;
                    }
                    else
                    {
                        *ptr2 = (char)num;
                        ptr2++;
                        pSrc++;
                    }
                    continue;
                }
                pSrc++;
            }
            _bufPos = (int)(ptr2 - ptr);
            _textPos = _bufPos;
            _contentPos = 0;
        }
    }
References System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufLen, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.XmlEncodedRawTextWriter._contentPos, System.Xml.XmlEncodedRawTextWriter._newLineHandling, System.Xml.XmlEncodedRawTextWriter._textPos, System.Xml.XmlEncodedRawTextWriter.AmpEntity(), System.Xml.XmlEncodedRawTextWriter.CarriageReturnEntity(), System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.EncodeSurrogate(), System.Xml.XmlEncodedRawTextWriter.FlushBuffer(), System.Xml.XmlEncodedRawTextWriter.GtEntity(), System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsSurrogate(), System.Xml.XmlEncodedRawTextWriter.LtEntity(), and System.Xml.XmlEncodedRawTextWriter.WriteNewLine().
Referenced by System.Xml.HtmlEncodedRawTextWriter.WriteChars(), System.Xml.XmlEncodedRawTextWriter.WriteChars(), System.Xml.HtmlEncodedRawTextWriter.WriteHtmlElementTextBlock(), System.Xml.XmlEncodedRawTextWriter.WriteString(), and System.Xml.XmlEncodedRawTextWriter.WriteWhitespace().