Terraria: System.Xml.XmlEncodedRawTextWriter.WriteCharsAsync
WriteCharsAsync()
override Task System.Xml.XmlEncodedRawTextWriter.WriteCharsAsync (char[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlWriter.
Reimplemented in System.Xml.XmlEncodedRawTextWriterIndent.
Definition at line 2030 of file XmlEncodedRawTextWriter.cs.
    {
        CheckAsyncCall();
        if (_trackTextContent && !_inTextContent)
        {
            ChangeTextContentMark(value: true);
        }
        if (_inAttributeValue)
        {
            return WriteAttributeTextBlockAsync(buffer, index, count);
        }
        return WriteElementTextBlockAsync(buffer, index, count);
    }
References System.Xml.XmlEncodedRawTextWriter._inAttributeValue, System.Xml.XmlEncodedRawTextWriter._inTextContent, System.Xml.XmlEncodedRawTextWriter._trackTextContent, System.buffer, System.Xml.XmlEncodedRawTextWriter.ChangeTextContentMark(), System.Xml.XmlEncodedRawTextWriter.CheckAsyncCall(), System.count, System.index, System.value, System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockAsync(), and System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlockAsync().