Terraria: System.Xml.XmlEncodedRawTextWriter.Close
Close() [1/2]
override void System.Xml.XmlEncodedRawTextWriter.Close () inline virtual inherited
Reimplemented from System.Xml.XmlWriter.
Definition at line 576 of file XmlEncodedRawTextWriter.cs.
    {
        try
        {
            FlushBuffer();
            FlushEncoder();
        }
        finally
        {
            _writeToNull = true;
            if (_stream != null)
            {
                try
                {
                    _stream.Flush();
                }
                finally
                {
                    try
                    {
                        if (_closeOutput)
{
                            _stream.Dispose();
                        }
                    }
                    finally
                    {
                        _stream = null;
                    }
                }
            }
            else if (_writer != null)
            {
                try
                {
                    _writer.Flush();
                }
                finally
                {
                    try
                    {
                        if (_closeOutput)
{
                            _writer.Dispose();
                        }
                    }
                    finally
                    {
                        _writer = null;
                    }
                }
            }
        }
    }
References System.Xml.XmlEncodedRawTextWriter._closeOutput, System.Xml.XmlEncodedRawTextWriter._stream, System.Xml.XmlEncodedRawTextWriter._writer, System.Xml.XmlEncodedRawTextWriter._writeToNull, System.IO.Stream.Dispose(), System.IO.TextWriter.Dispose(), System.IO.Stream.Flush(), System.IO.TextWriter.Flush(), System.Xml.XmlEncodedRawTextWriter.FlushBuffer(), and System.Xml.XmlEncodedRawTextWriter.FlushEncoder().