Terraria: System.Xml.XmlEncodedRawTextWriter.WriteNamespaceDeclarationAsync
WriteNamespaceDeclarationAsync()
override async Task System.Xml.XmlEncodedRawTextWriter.WriteNamespaceDeclarationAsync (string prefix, string namespaceName) inline package virtual inherited
Reimplemented from System.Xml.XmlRawWriter.
Definition at line 1831 of file XmlEncodedRawTextWriter.cs.
    {
        CheckAsyncCall();
        await WriteStartNamespaceDeclarationAsync(prefix).ConfigureAwait(continueOnCapturedContext: false);
        await WriteStringAsync(namespaceName).ConfigureAwait(continueOnCapturedContext: false);
        await WriteEndNamespaceDeclarationAsync().ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.XmlEncodedRawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.prefix, System.Xml.XmlEncodedRawTextWriter.WriteEndNamespaceDeclarationAsync(), System.Xml.XmlEncodedRawTextWriter.WriteStartNamespaceDeclarationAsync(), and System.Xml.XmlEncodedRawTextWriter.WriteStringAsync().