Terraria: System.Xml.XmlEncodedRawTextWriter.XmlEncodedRawTextWriter
XmlEncodedRawTextWriter() [3/3]
System.Xml.XmlEncodedRawTextWriter.XmlEncodedRawTextWriter (Stream stream, XmlWriterSettings settings) inline
Definition at line 129 of file XmlEncodedRawTextWriter.cs.
        : this(settings)
    {
        _stream = stream;
        _encoding = settings.Encoding;
        if (settings.Async)
        {
            _bufLen = 65536;
        }
        _bufChars = new char[_bufLen + 32];
        _bufBytes = new byte[_bufChars.Length];
        _bufBytesUsed = 0;
        _trackTextContent = true;
        _inTextContent = false;
        _lastMarkPos = 0;
        _textContentMarks = new int[64];
        _textContentMarks[0] = 1;
        _charEntityFallback = new CharEntityEncoderFallback();
        ReadOnlySpan<byte> preamble = _encoding.Preamble;
        _encoding = (Encoding)settings.Encoding.Clone();
        _encoding.EncoderFallback = _charEntityFallback;
        _encoder = _encoding.GetEncoder();
        if ((!stream.CanSeek || stream.Position == 0L) && preamble.Length != 0)
        {
            _stream.Write(preamble);
        }
        if (settings.AutoXmlDeclaration)
        {
            WriteXmlDeclaration(_standalone);
            _autoXmlDeclaration = true;
        }
    }
References System.Xml.XmlEncodedRawTextWriter._autoXmlDeclaration, System.Xml.XmlEncodedRawTextWriter._bufBytes, System.Xml.XmlEncodedRawTextWriter._bufBytesUsed, System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufLen, System.Xml.XmlEncodedRawTextWriter._charEntityFallback, System.Xml.XmlEncodedRawTextWriter._encoder, System.Xml.XmlEncodedRawTextWriter._encoding, System.Xml.XmlEncodedRawTextWriter._inTextContent, System.Xml.XmlEncodedRawTextWriter._lastMarkPos, System.Xml.XmlEncodedRawTextWriter._standalone, System.Xml.XmlEncodedRawTextWriter._stream, System.Xml.XmlEncodedRawTextWriter._textContentMarks, System.Xml.XmlEncodedRawTextWriter._trackTextContent, System.Xml.XmlWriterSettings.Async, System.Xml.XmlWriterSettings.AutoXmlDeclaration, System.Text.Encoding.Clone(), System.Xml.Dictionary, System.Xml.Encoding, System.Xml.XmlWriterSettings.Encoding, System.Text.Encoding.GetEncoder(), System.Xml.L, System.Text.Encoding.Preamble, System.stream, System.IO.Stream.Write(), and System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclaration().