Terraria: System.Xml.XmlEncodedRawTextWriter.WriteCharEntity
WriteCharEntity()
override void System.Xml.XmlEncodedRawTextWriter.WriteCharEntity (char ch) inline
Definition at line 452 of file XmlEncodedRawTextWriter.cs.
    {
        int num = ch;
        string s = num.ToString("X", NumberFormatInfo.InvariantInfo);
        if (_checkCharacters && !XmlCharType.IsCharData(ch))
        {
            throw XmlConvert.CreateInvalidCharException(ch, '\0');
        }
        if (_trackTextContent && _inTextContent)
        {
            ChangeTextContentMark(value: false);
        }
        _bufChars[_bufPos++] = '&';
        _bufChars[_bufPos++] = '#';
        _bufChars[_bufPos++] = 'x';
        RawText(s);
        _bufChars[_bufPos++] = ';';
        if (_bufPos > _bufLen)
        {
            FlushBuffer();
        }
        _textPos = _bufPos;
    }
References System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufLen, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.XmlEncodedRawTextWriter._checkCharacters, System.Xml.XmlEncodedRawTextWriter._inTextContent, System.Xml.XmlEncodedRawTextWriter._textPos, System.Xml.XmlEncodedRawTextWriter._trackTextContent, System.ch, System.Xml.XmlEncodedRawTextWriter.ChangeTextContentMark(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.XmlEncodedRawTextWriter.FlushBuffer(), System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.XmlCharType.IsCharData(), System.Xml.XmlEncodedRawTextWriter.RawText(), System.s, and System.value.