Terraria: System.Xml.XmlEncodedRawTextWriter.ValidateContentChars
ValidateContentChars()
void System.Xml.XmlEncodedRawTextWriter.ValidateContentChars (string chars, string propertyName, bool allowOnlyWhitespace) inline protected inherited
Definition at line 1530 of file XmlEncodedRawTextWriter.cs.
    {
        if (allowOnlyWhitespace)
        {
            if (!XmlCharType.IsOnlyWhitespace(chars))
            {
                throw new ArgumentException(System.SR.Format(System.SR.Xml_IndentCharsNotWhitespace, propertyName));
            }
            return;
        }
        string text = null;
        int num = 0;
        object[] args;
        while (true)
        {
            if (num >= chars.Length)
            {
                return;
            }
            if (!XmlCharType.IsTextChar(chars[num]))
            {
                switch (chars[num])
                {
                case '&':
                case '<':
                case ']':
                {
                    string xml_InvalidCharacter = System.SR.Xml_InvalidCharacter;
                    args = XmlException.BuildCharExceptionArgs(chars, num);
                    text = System.SR.Format(xml_InvalidCharacter, args);
                    break;
                }
                default:
                    if (XmlCharType.IsHighSurrogate(chars[num]))
                    {
                        if (num + 1 < chars.Length && XmlCharType.IsLowSurrogate(chars[num + 1]))
{
                            num++;
                            goto IL_00f6;
                        }
                        text = System.SR.Xml_InvalidSurrogateMissingLowChar;
                    }
                    else
                    {
                        if (!XmlCharType.IsLowSurrogate(chars[num]))
{
                            goto IL_00f6;
                        }
                        text = System.SR.Format(System.SR.Xml_InvalidSurrogateHighChar, ((uint)chars[num]).ToString("X", CultureInfo.InvariantCulture));
                    }
                    break;
                case '\t':
                case '\n':
                case '\r':
                    goto IL_00f6;
                }
                break;
            }
            goto IL_00f6;
            IL_00f6:
            num++;
        }
        string xml_InvalidCharsInIndent = System.SR.Xml_InvalidCharsInIndent;
        args = new string[2] { propertyName, text };
        throw new ArgumentException(System.SR.Format(xml_InvalidCharsInIndent, args));
    }
References System.Xml.ArgumentException, System.Xml.XmlException.BuildCharExceptionArgs(), System.chars, System.Xml.Dictionary, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Xml.XmlCharType.IsOnlyWhitespace(), System.Xml.XmlCharType.IsTextChar(), System.text, System.SR.Xml_IndentCharsNotWhitespace, System.SR.Xml_InvalidCharacter, System.SR.Xml_InvalidCharsInIndent, System.SR.Xml_InvalidSurrogateHighChar, and System.SR.Xml_InvalidSurrogateMissingLowChar.
Referenced by System.Xml.XmlEncodedRawTextWriter.XmlEncodedRawTextWriter(), and System.Xml.XmlEncodedRawTextWriterIndent.Init().