Terraria: System.Security.SecurityElement.Equal
Equal()
bool System.Security.SecurityElement.Equal ([NotNullWhen(true)] SecurityElement? other) inline
Definition at line 215 of file SecurityElement.cs.
    {
        if (other == null)
        {
            return false;
        }
        if (!string.Equals(_tag, other._tag))
        {
            return false;
        }
        if (!string.Equals(_text, other._text))
        {
            return false;
        }
        if (_attributes == null || other._attributes == null)
        {
            if (_attributes != other._attributes)
            {
                return false;
            }
        }
        else
        {
            int count = _attributes.Count;
            if (count != other._attributes.Count)
            {
                return false;
            }
            for (int i = 0; i < count; i++)
            {
                string a = (string)_attributes[i];
                string b = (string)other._attributes[i];
                if (!string.Equals(a, b))
                {
                    return false;
                }
            }
        }
        if (_children == null || other._children == null)
        {
            if (_children != other._children)
            {
                return false;
            }
        }
        else
        {
            if (_children.Count != other._children.Count)
            {
                return false;
            }
            IEnumerator enumerator = _children.GetEnumerator();
            IEnumerator enumerator2 = other._children.GetEnumerator();
            while (enumerator.MoveNext())
            {
                enumerator2.MoveNext();
                SecurityElement securityElement = (SecurityElement)enumerator.Current;
                SecurityElement other2 = (SecurityElement)enumerator2.Current;
                if (securityElement == null || !securityElement.Equal(other2))
                {
                    return false;
                }
            }
        }
        return true;
    }
References System.Security.SecurityElement.SecurityElement(), System.Security.SecurityElement._attributes, System.Security.SecurityElement._children, System.Security.SecurityElement._tag, System.Security.SecurityElement._text, System.count, System.Collections.ArrayList.Count, System.Collections.IEnumerator.Current, System.Security.SecurityElement.Equal(), System.Collections.ArrayList.GetEnumerator(), System.Collections.IEnumerator.MoveNext(), and System.other.
Referenced by System.Security.SecurityElement.Equal().