Terraria: System.Security.SecurityElement.SecurityElement
SecurityElement() [1/2]
System.Security.SecurityElement.SecurityElement (string tag) inline
Definition at line 128 of file SecurityElement.cs.
    {
        if (tag == null)
        {
            throw new ArgumentNullException("tag");
        }
        if (!IsValidTag(tag))
        {
            throw new ArgumentException(SR.Format(SR.Argument_InvalidElementTag, tag));
        }
        _tag = tag;
    }
References System.Security.SecurityElement._tag, System.SR.Argument_InvalidElementTag, System.SR.Format(), and System.Security.SecurityElement.IsValidTag().
Referenced by System.Security.SecurityElement.Copy(), System.Security.SecurityElement.Equal(), and System.Security.SecurityElement.ToString().