Terraria: System.Security.SecurityElement.Escape
Escape()
static ? string System.Security.SecurityElement.Escape (string? str) inline static
Definition at line 338 of file SecurityElement.cs.
    {
        if (str == null)
        {
            return null;
        }
        StringBuilder stringBuilder = null;
        int length = str.Length;
        int num = 0;
        while (true)
        {
            int num2 = str.IndexOfAny(s_escapeChars, num);
            if (num2 == -1)
            {
                break;
            }
            if (stringBuilder == null)
            {
                stringBuilder = new StringBuilder();
            }
            stringBuilder.Append(str, num, num2 - num);
            stringBuilder.Append(GetEscapeSequence(str[num2]));
            num = num2 + 1;
        }
        if (stringBuilder == null)
        {
            return str;
        }
        stringBuilder.Append(str, num, length - num);
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.Append(), System.Security.SecurityElement.GetEscapeSequence(), System.length, System.Text.StringBuilder.Length, System.Security.SecurityElement.s_escapeChars, System.str, and System.Text.StringBuilder.ToString().