Terraria: System.Transactions.TransactionStatePromotedNonMSDTCEnded.EnterState
EnterState()
override void System.Transactions.TransactionStatePromotedNonMSDTCEnded.EnterState (InternalTransaction tx) inline package
Definition at line 11 of file TransactionStatePromotedNonMSDTCEnded.cs.
    {
        base.EnterState(tx);
        CommonEnterState(tx);
        if (!ThreadPool.QueueUserWorkItem(SignalMethod, tx))
        {
            throw TransactionException.CreateInvalidOperationException(TraceSourceType.TraceSourceLtm, System.SR.UnexpectedFailureOfThreadPool, null, tx?.DistributedTxId ?? Guid.Empty);
        }
    }
References System.Transactions.TransactionState.CommonEnterState(), System.Transactions.TransactionException.CreateInvalidOperationException(), System.Transactions.InternalTransaction.DistributedTxId, System.Guid.Empty, System.Threading.ThreadPool.QueueUserWorkItem(), System.Transactions.TransactionStatePromotedNonMSDTCEnded.SignalMethod, and System.SR.UnexpectedFailureOfThreadPool.