Terraria: LegacyLighting.doColors_Mode0_Swipe
doColors_Mode0_Swipe()
void LegacyLighting.doColors_Mode0_Swipe (int outerLoopStart, int outerLoopEnd, object context) inline private
     {
         LightingSwipeData lightingSwipeData = context as LightingSwipeData;
         FastRandom fastRandom = default(FastRandom);
         try
         {
             bool flag = true;
             while (true)
             {
                 int num;
                 int val;
                 int val2;
                 if (flag)
                 {
                     num = 1;
                     val = lightingSwipeData.InnerLoop1Start;
                     val2 = lightingSwipeData.InnerLoop1End;
                 }
                 else
                 {
                     num = -1;
                     val = lightingSwipeData.InnerLoop2Start;
                     val2 = lightingSwipeData.InnerLoop2End;
                 }
                 for (int i = outerLoopStart; i < outerLoopEnd; i++)
                 {
                     LightingState[] array = lightingSwipeData.JaggedArray[i];
                     float num2 = 0f;
                     float num3 = 0f;
                     float num4 = 0f;
                     int num5 = Math.Min(array.Length - 1, Math.Max(0, val));
                     int num6 = Math.Min(array.Length - 1, Math.Max(0, val2));
                     for (int j = num5; j != num6; j += num)
                     {
                         LightingState lightingState = array[j];
                         LightingState lightingState2 = array[j + num];
                         bool flag2;
                         bool flag3 = (flag2 = false);
                         if (lightingState.R2 > num2)
{
                             num2 = lightingState.R2;
                         }
                         else if ((double)num2 <= 0.0185)
{
                             flag3 = true;
                         }
                         else if (lightingState.R2 < num2)
{
                             lightingState.R2 = num2;
                         }
                         if (lightingState.WetLight)
{
                             fastRandom = _swipeRandom.WithModifier((ulong)(i * 1000 + j));
                         }
                         if (!flag3 && lightingState2.R2 <= num2)
{
                             num2 = (lightingState.StopLight ? (num2 * _negLight2) : ((!lightingState.WetLight) ? (num2 * _negLight) : ((!lightingState.HoneyLight) ? (num2 * (_wetLightR * (float)fastRandom.Next(98, 100) * 0.01f)) : (num2 * (_honeyLightR * (float)fastRandom.Next(98, 100) * 0.01f)))));
                         }
                         if (lightingState.G2 > num3)
{
                             num3 = lightingState.G2;
                         }
                         else if ((double)num3 <= 0.0185)
{
                             flag2 = true;
                         }
                         else
{
                             lightingState.G2 = num3;
                         }
                         if (!flag2 && lightingState2.G2 <= num3)
{
                             num3 = (lightingState.StopLight ? (num3 * _negLight2) : ((!lightingState.WetLight) ? (num3 * _negLight) : ((!lightingState.HoneyLight) ? (num3 * (_wetLightG * (float)fastRandom.Next(97, 100) * 0.01f)) : (num3 * (_honeyLightG * (float)fastRandom.Next(97, 100) * 0.01f)))));
                         }
                         if (lightingState.B2 > num4)
{
                             num4 = lightingState.B2;
                         }
                         else
{
                             if ((double)num4 <= 0.0185)
{
                                 continue;
                             }
                             lightingState.B2 = num4;
                         }
                         if (!(lightingState2.B2 >= num4))
{
                             num4 = ((!lightingState.StopLight) ? ((!lightingState.WetLight) ? (num4 * _negLight) : ((!lightingState.HoneyLight) ? (num4 * (_wetLightB * (float)fastRandom.Next(97, 100) * 0.01f)) : (num4 * (_honeyLightB * (float)fastRandom.Next(97, 100) * 0.01f)))) : (num4 * _negLight2));
                         }
                     }
                 }
                 if (flag)
                 {
                     flag = false;
                     continue;
                 }
                 break;
             }
         }
         catch
         {
         }
     }
References _honeyLightB, _honeyLightG, _honeyLightR, _negLight, _negLight2, _swipeRandom, _wetLightB, _wetLightG, _wetLightR, LegacyLighting.LightingState.B2, LegacyLighting.LightingState.G2, LegacyLighting.LightingState.HoneyLight, LegacyLighting.LightingSwipeData.InnerLoop1End, LegacyLighting.LightingSwipeData.InnerLoop1Start, LegacyLighting.LightingSwipeData.InnerLoop2End, LegacyLighting.LightingSwipeData.InnerLoop2Start, LegacyLighting.LightingSwipeData.JaggedArray, FastRandom.Next(), LegacyLighting.LightingState.R2, LegacyLighting.LightingState.StopLight, LegacyLighting.LightingState.WetLight, and FastRandom.WithModifier().
Referenced by DoColors().