Terraria: System.Linq.Enumerable.DefaultIfEmptyIterator.MoveNext
MoveNext()
override bool System.Linq.Enumerable.DefaultIfEmptyIterator< TSource >.MoveNext () inline
Implements System.Collections.IEnumerator.
Definition at line 725 of file Enumerable.cs.
        {
            switch (_state)
            {
            case 1:
                _enumerator = _source.GetEnumerator();
                if (_enumerator.MoveNext())
                {
                    _current = _enumerator.Current;
                    _state = 2;
                }
                else
                {
                    _current = _default;
                    _state = -1;
                }
                return true;
            case 2:
                if (_enumerator.MoveNext())
                {
                    _current = _enumerator.Current;
                    return true;
                }
                break;
            }
            Dispose();
            return false;
        }
References System.Linq.Enumerable.Iterator< TSource >._current, System.Linq.Enumerable.DefaultIfEmptyIterator< TSource >._default, System.Linq.Enumerable.DefaultIfEmptyIterator< TSource >._enumerator, System.Linq.Enumerable.DefaultIfEmptyIterator< TSource >._source, System.Linq.Enumerable.Iterator< TSource >._state, System.Collections.IEnumerator.Current, System.Linq.Enumerable.DefaultIfEmptyIterator< TSource >.Dispose(), System.Collections.IEnumerable.GetEnumerator(), and System.Collections.IEnumerator.MoveNext().