Terraria: LegacyLighting.PreRenderPhase
PreRenderPhase()
void LegacyLighting.PreRenderPhase () inline private
     {
         _ = (float)(int)Main.tileColor.R / 255f;
         _ = (float)(int)Main.tileColor.G / 255f;
         _ = (float)(int)Main.tileColor.B / 255f;
         Stopwatch stopwatch = new Stopwatch();
         stopwatch.Start();
         int num = 0;
         int num2 = (int)_camera.UnscaledSize.X / 16 + Lighting.OffScreenTiles * 2 + 10;
         int num3 = 0;
         int num4 = (int)_camera.UnscaledSize.Y / 16 + Lighting.OffScreenTiles * 2 + 10;
         _minX = num2;
         _maxX = num;
         _minY = num4;
         _maxY = num3;
         _rgb = Mode == 0 || Mode == 3;
         for (int i = num; i < num2; i++)
         {
             LightingState[] array = _states[i];
             for (int j = num3; j < num4; j++)
             {
                 LightingState obj = array[j];
                 obj.R2 = 0f;
                 obj.G2 = 0f;
                 obj.B2 = 0f;
                 obj.StopLight = false;
                 obj.WetLight = false;
                 obj.HoneyLight = false;
             }
         }
         if (Main.wofNPCIndex >= 0 && Main.player[Main.myPlayer].gross)
         {
             try
             {
                 int num5 = (int)_camera.UnscaledPosition.Y / 16 - 10;
                 int num6 = (int)(_camera.UnscaledPosition.Y + _camera.UnscaledSize.Y) / 16 + 10;
                 int num7 = (int)Main.npc[Main.wofNPCIndex].position.X / 16;
                 num7 = ((Main.npc[Main.wofNPCIndex].direction <= 0) ? (num7 + 2) : (num7 - 3));
                 int num8 = num7 + 8;
                 float num9 = 0.5f * Main.demonTorch + 1f * (1f - Main.demonTorch);
                 float num10 = 0.3f;
                 float num11 = 1f * Main.demonTorch + 0.5f * (1f - Main.demonTorch);
                 num9 *= 0.2f;
                 num10 *= 0.1f;
                 num11 *= 0.3f;
                 for (int k = num7; k <= num8; k++)
                 {
                     LightingState[] array2 = _states[k - num7];
                     for (int l = num5; l <= num6; l++)
                     {
                         LightingState lightingState = array2[l - _expandedRectTop];
                         if (lightingState.R2 < num9)
{
                             lightingState.R2 = num9;
                         }
                         if (lightingState.G2 < num10)
{
                             lightingState.G2 = num10;
                         }
                         if (lightingState.B2 < num11)
{
                             lightingState.B2 = num11;
                         }
                     }
                 }
             }
             catch
             {
             }
         }
         num = Utils.Clamp(_expandedRectLeft, 5, Main.maxTilesX - 1);
         num2 = Utils.Clamp(_expandedRectRight, 5, Main.maxTilesX - 1);
         num3 = Utils.Clamp(_expandedRectTop, 5, Main.maxTilesY - 1);
         num4 = Utils.Clamp(_expandedRectBottom, 5, Main.maxTilesY - 1);
         Main.SceneMetrics.ScanAndExportToMain(new SceneMetricsScanSettings
         {
             VisualScanArea = new Rectangle(num, num3, num2 - num, num4 - num3),
             BiomeScanCenterPositionInWorld = Main.LocalPlayer.Center,
             ScanOreFinderData = Main.LocalPlayer.accOreFinder
         });
         _tileScanner.Update();
         _tileScanner.ExportTo(new Rectangle(num, num3, num2 - num, num4 - num3), _lightMap, new TileLightScannerOptions
         {
             DrawInvisibleWalls = Main.ShouldShowInvisibleWalls()
         });
         for (int m = num; m < num2; m++)
         {
             LightingState[] array3 = _states[m - _expandedRectLeft];
             for (int n = num3; n < num4; n++)
             {
                 LightingState lightingState2 = array3[n - _expandedRectTop];
                 Tile tile = Main.tile[m, n];
                 if (tile == null)
                 {
                     tile = new Tile();
                     Main.tile[m, n] = tile;
                 }
                 _lightMap.GetLight(m - num, n - num3, out var color);
                 if (_rgb)
                 {
                     lightingState2.R2 = color.X;
                     lightingState2.G2 = color.Y;
                     lightingState2.B2 = color.Z;
                 }
                 else
                 {
                     lightingState2.B2 = (lightingState2.G2 = (lightingState2.R2 = (color.X + color.Y + color.Z) / 3f));
                 }
                 switch (_lightMap.GetMask(m - num, n - num3))
                 {
                 case LightMaskMode.Solid:
                     lightingState2.StopLight = true;
                     break;
                 case LightMaskMode.Water:
                     lightingState2.WetLight = true;
                     break;
                 case LightMaskMode.Honey:
                     lightingState2.WetLight = true;
                     lightingState2.HoneyLight = true;
                     break;
                 }
                 if (lightingState2.R2 > 0f || (_rgb && (lightingState2.G2 > 0f || lightingState2.B2 > 0f)))
                 {
                     int num12 = m - _expandedRectLeft;
                     int num13 = n - _expandedRectTop;
                     if (_minX > num12)
                     {
                         _minX = num12;
                     }
                     if (_maxX < num12 + 1)
                     {
                         _maxX = num12 + 1;
                     }
                     if (_minY > num13)
                     {
                         _minY = num13;
                     }
                     if (_maxY < num13 + 1)
                     {
                         _maxY = num13 + 1;
                     }
                 }
             }
         }
         foreach (KeyValuePair<Point16, ColorTriplet> tempLight in _tempLights)
         {
             int num14 = tempLight.Key.X - _requestedRectLeft + Lighting.OffScreenTiles;
             int num15 = tempLight.Key.Y - _requestedRectTop + Lighting.OffScreenTiles;
             if (num14 >= 0 && (float)num14 < _camera.UnscaledSize.X / 16f + (float)(Lighting.OffScreenTiles * 2) + 10f && num15 >= 0 && (float)num15 < _camera.UnscaledSize.Y / 16f + (float)(Lighting.OffScreenTiles * 2) + 10f)
             {
                 LightingState lightingState3 = _states[num14][num15];
                 if (lightingState3.R2 < tempLight.Value.R)
                 {
                     lightingState3.R2 = tempLight.Value.R;
                 }
                 if (lightingState3.G2 < tempLight.Value.G)
                 {
                     lightingState3.G2 = tempLight.Value.G;
                 }
                 if (lightingState3.B2 < tempLight.Value.B)
                 {
                     lightingState3.B2 = tempLight.Value.B;
                 }
                 if (_minX > num14)
                 {
                     _minX = num14;
                 }
                 if (_maxX < num14 + 1)
                 {
                     _maxX = num14 + 1;
                 }
                 if (_minY > num15)
                 {
                     _minY = num15;
                 }
                 if (_maxY < num15 + 1)
                 {
                     _maxY = num15 + 1;
                 }
             }
         }
         if (!Main.gamePaused)
         {
             _tempLights.Clear();
         }
         _minX += _expandedRectLeft;
         _maxX += _expandedRectLeft;
         _minY += _expandedRectTop;
         _maxY += _expandedRectTop;
         _minBoundArea.Set(_minX, _maxX, _minY, _maxY);
         _requestedArea.Set(_requestedRectLeft, _requestedRectRight, _requestedRectTop, _requestedRectBottom);
         _expandedArea.Set(_expandedRectLeft, _expandedRectRight, _expandedRectTop, _expandedRectBottom);
         _offScreenTiles2ExpandedArea.Set(_requestedRectLeft - _offScreenTiles2, _requestedRectRight + _offScreenTiles2, _requestedRectTop - _offScreenTiles2, _requestedRectBottom + _offScreenTiles2);
         _scrX = (int)Math.Floor(_camera.UnscaledPosition.X / 16f);
         _scrY = (int)Math.Floor(_camera.UnscaledPosition.Y / 16f);
         Main.renderCount = 0;
         TimeLogger.LightingTime(0, stopwatch.Elapsed.TotalMilliseconds);
         DoColors();
     }
References _camera, _expandedArea, _expandedRectBottom, _expandedRectLeft, _expandedRectRight, _expandedRectTop, _lightMap, _maxX, _maxY, _minBoundArea, _minX, _minY, _offScreenTiles2, _offScreenTiles2ExpandedArea, _requestedArea, _requestedRectBottom, _requestedRectLeft, _requestedRectRight, _requestedRectTop, _rgb, _scrX, _scrY, _states, _tempLights, _tileScanner, Player.accOreFinder, LegacyLighting.LightingState.B2, Entity.Center, Main.demonTorch, Entity.direction, DoColors(), TileLightScanner.ExportTo(), LegacyLighting.LightingState.G2, Main.gamePaused, LightMap.GetLight(), LightMap.GetMask(), Player.gross, LegacyLighting.LightingState.HoneyLight, TimeLogger.LightingTime(), Main.LocalPlayer, Main.maxTilesX, Main.maxTilesY, Mode, Main.myPlayer, Main.npc, Lighting.OffScreenTiles, Main.player, Entity.position, LegacyLighting.LightingState.R2, Main.renderCount, SceneMetrics.ScanAndExportToMain(), Main.SceneMetrics, LegacyLighting.RectArea.Set(), Main.ShouldShowInvisibleWalls(), LegacyLighting.LightingState.StopLight, Tile, Main.tile, Main.tileColor, Camera.UnscaledPosition, Camera.UnscaledSize, TileLightScanner.Update(), LegacyLighting.LightingState.WetLight, and Main.wofNPCIndex.
Referenced by ProcessArea().