Terraria: System.Security.Cryptography.CngKey.GetCurveName
GetCurveName()
string System.Security.Cryptography.CngKey.GetCurveName (out string oidValue) inline package
Definition at line 450 of file CngKey.cs.
    {
        if (IsECNamedCurve())
        {
            oidValue = null;
            return _keyHandle.GetPropertyAsString("ECCCurveName", CngPropertyOptions.None);
        }
        return GetECSpecificCurveName(out oidValue);
    }
References System.Security.Cryptography.CngKey._keyHandle, System.Security.Cryptography.CngKey.GetECSpecificCurveName(), and System.Security.Cryptography.CngKey.IsECNamedCurve().
Referenced by System.Security.Cryptography.ECDiffieHellmanCng.GetCurveName(), and System.Security.Cryptography.ECDsaCng.GetCurveName().