Terraria: System.Security.Cryptography.CngKey.Export
Export()
byte[] System.Security.Cryptography.CngKey.Export (CngKeyBlobFormat format) inline
Definition at line 622 of file CngKey.cs.
    {
        if (format == null)
        {
            throw new ArgumentNullException("format");
        }
        global::Interop.NCrypt.ErrorCode errorCode = global::Interop.NCrypt.NCryptExportKey(_keyHandle, IntPtr.Zero, format.Format, IntPtr.Zero, null, 0, out var pcbResult, 0);
        if (errorCode != 0)
        {
            throw errorCode.ToCryptographicException();
        }
        byte[] array = new byte[pcbResult];
        errorCode = global::Interop.NCrypt.NCryptExportKey(_keyHandle, IntPtr.Zero, format.Format, IntPtr.Zero, array, array.Length, out pcbResult, 0);
        if (errorCode != 0)
        {
            throw errorCode.ToCryptographicException();
        }
        Array.Resize(ref array, pcbResult);
        return array;
    }
References System.Security.Cryptography.CngKey._keyHandle, System.array, System.format, and System.IntPtr.Zero.
Referenced by System.Security.Cryptography.DSACng.ExportKeyBlob(), System.Security.Cryptography.RSACng.ExportKeyBlob(), and Internal.Cryptography.SymmetricImportExportExtensions.GetSymmetricKeyDataIfExportable().