Terraria: System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.IsValidCallback
IsValidCallback()
static bool System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.IsValidCallback (MethodInfo method, ParameterInfo[] parameters, Type attributeType, MethodInfo currentCallback, ref Type prevAttributeType) inline static private
Definition at line 756 of file ClassDataContract.cs.
        {
            if (method.IsDefined(attributeType, inherit: false))
            {
                if (currentCallback != null)
                {
                    DataContract.ThrowInvalidDataContractException(System.SR.Format(System.SR.DuplicateCallback, method, currentCallback, DataContract.GetClrTypeFullName(method.DeclaringType), attributeType), method.DeclaringType);
                }
                else if (prevAttributeType != null)
                {
                    DataContract.ThrowInvalidDataContractException(System.SR.Format(System.SR.DuplicateAttribute, prevAttributeType, attributeType, DataContract.GetClrTypeFullName(method.DeclaringType), method), method.DeclaringType);
                }
                else if (method.IsVirtual)
                {
                    DataContract.ThrowInvalidDataContractException(System.SR.Format(System.SR.CallbacksCannotBeVirtualMethods, method, DataContract.GetClrTypeFullName(method.DeclaringType), attributeType), method.DeclaringType);
                }
                else
                {
                    if (method.ReturnType != Globals.TypeOfVoid)
                    {
                        DataContract.ThrowInvalidDataContractException(System.SR.Format(System.SR.CallbackMustReturnVoid, DataContract.GetClrTypeFullName(method.DeclaringType), method), method.DeclaringType);
                    }
                    if (parameters == null || parameters.Length != 1 || parameters[0].ParameterType != Globals.TypeOfStreamingContext)
                    {
                        DataContract.ThrowInvalidDataContractException(System.SR.Format(System.SR.CallbackParameterInvalid, DataContract.GetClrTypeFullName(method.DeclaringType), method, Globals.TypeOfStreamingContext), method.DeclaringType);
                    }
                    prevAttributeType = attributeType;
                }
                return true;
            }
            return false;
        }
References System.SR.CallbackMustReturnVoid, System.SR.CallbackParameterInvalid, System.SR.CallbacksCannotBeVirtualMethods, System.Runtime.Serialization.Dictionary, System.SR.DuplicateAttribute, System.SR.DuplicateCallback, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Reflection.ParameterInfo.ParameterType, System.Runtime.Serialization.DataContract.ThrowInvalidDataContractException(), System.Runtime.Serialization.Globals.TypeOfStreamingContext, and System.Runtime.Serialization.Globals.TypeOfVoid.
Referenced by System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.EnsureMethodsImported().