Terraria: System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers
ImportDataMembers()
void System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers () inline private
Definition at line 449 of file ClassDataContract.cs.
        {
            Type underlyingType = base.UnderlyingType;
            EnsureIsReferenceImported(underlyingType);
            List<DataMember> list = new List<DataMember>();
            Dictionary<string, DataMember> memberNamesTable = new Dictionary<string, DataMember>();
            bool flag = !_isNonAttributedType || IsKnownSerializableType(underlyingType);
            MemberInfo[] array = (flag ? underlyingType.GetMembers(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic) : underlyingType.GetMembers(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public));
            foreach (MemberInfo memberInfo in array)
            {
                if (HasDataContract)
                {
                    object[] array2 = memberInfo.GetCustomAttributes(typeof(DataMemberAttribute), inherit: false).ToArray();
                    if (array2 == null || array2.Length == 0)
                    {
                        continue;
                    }
                    if (array2.Length > 1)
                    {
                        ThrowInvalidDataContractException(System.SR.Format(System.SR.TooManyDataMembers, DataContract.GetClrTypeFullName(memberInfo.DeclaringType), memberInfo.Name));
                    }
                    DataMember dataMember = new DataMember(memberInfo);
                    if (memberInfo is PropertyInfo)
                    {
                        PropertyInfo propertyInfo = (PropertyInfo)memberInfo;
                        MethodInfo getMethod = propertyInfo.GetMethod;
                        if (getMethod != null && IsMethodOverriding(getMethod))
{
                            continue;
                        }
                        MethodInfo setMethod = propertyInfo.SetMethod;
                        if (setMethod != null && IsMethodOverriding(setMethod))
{
                            continue;
                        }
                        if (getMethod == null)
{
                            ThrowInvalidDataContractException(System.SR.Format(System.SR.NoGetMethodForProperty, propertyInfo.DeclaringType, propertyInfo.Name));
                        }
                        if (setMethod == null && !SetIfGetOnlyCollection(dataMember))
{
                            ThrowInvalidDataContractException(System.SR.Format(System.SR.NoSetMethodForProperty, propertyInfo.DeclaringType, propertyInfo.Name));
                        }
                        if (getMethod.GetParameters().Length != 0)
{
                            ThrowInvalidDataContractException(System.SR.Format(System.SR.IndexedPropertyCannotBeSerialized, propertyInfo.DeclaringType, propertyInfo.Name));
                        }
                    }
                    else if (!(memberInfo is FieldInfo))
                    {
                        ThrowInvalidDataContractException(System.SR.Format(System.SR.InvalidMember, DataContract.GetClrTypeFullName(underlyingType), memberInfo.Name));
                    }
                    DataMemberAttribute dataMemberAttribute = (DataMemberAttribute)array2[0];
                    if (dataMemberAttribute.IsNameSetExplicitly)
                    {
                        if (dataMemberAttribute.Name == null || dataMemberAttribute.Name.Length == 0)
{
                            ThrowInvalidDataContractException(System.SR.Format(System.SR.InvalidDataMemberName, memberInfo.Name, DataContract.GetClrTypeFullName(underlyingType)));
                        }
                        dataMember.Name = dataMemberAttribute.Name;
                    }
                    else
                    {
                        dataMember.Name = memberInfo.Name;
                    }
                    dataMember.Name = DataContract.EncodeLocalName(dataMember.Name);
                    dataMember.IsNullable = DataContract.IsTypeNullable(dataMember.MemberType);
                    dataMember.IsRequired = dataMemberAttribute.IsRequired;
                    if (dataMemberAttribute.IsRequired && base.IsReference)
                    {
                        DataContractCriticalHelper.ThrowInvalidDataContractException(System.SR.Format(System.SR.IsRequiredDataMemberOnIsReferenceDataContractType, DataContract.GetClrTypeFullName(memberInfo.DeclaringType), memberInfo.Name, true), underlyingType);
                    }
                    dataMember.EmitDefaultValue = dataMemberAttribute.EmitDefaultValue;
                    dataMember.Order = dataMemberAttribute.Order;
                    CheckAndAddMember(list, dataMember, memberNamesTable);
                    continue;
                }
                if (!flag)
                {
                    FieldInfo fieldInfo = memberInfo as FieldInfo;
                    PropertyInfo propertyInfo2 = memberInfo as PropertyInfo;
                    if ((fieldInfo == null && propertyInfo2 == null) || (fieldInfo != null && fieldInfo.IsInitOnly))
                    {
                        continue;
                    }
                    object[] array3 = memberInfo.GetCustomAttributes(typeof(IgnoreDataMemberAttribute), inherit: false).ToArray();
                    if (array3 != null && array3.Length != 0)
                    {
                        if (array3.Length <= 1)
{
                            continue;
                        }
                        ThrowInvalidDataContractException(System.SR.Format(System.SR.TooManyIgnoreDataMemberAttributes, DataContract.GetClrTypeFullName(memberInfo.DeclaringType), memberInfo.Name));
                    }
                    DataMember dataMember2 = new DataMember(memberInfo);
                    if (propertyInfo2 != null)
                    {
                        MethodInfo getMethod2 = propertyInfo2.GetGetMethod();
                        if (getMethod2 == null || IsMethodOverriding(getMethod2) || getMethod2.GetParameters().Length != 0)
{
                            continue;
                        }
                        MethodInfo setMethod2 = propertyInfo2.SetMethod;
                        if (setMethod2 == null)
{
                            if (!SetIfGetOnlyCollection(dataMember2))
{
                                continue;
                            }
                        }
                        else if (!setMethod2.IsPublic || IsMethodOverriding(setMethod2))
{
                            continue;
                        }
                    }
                    dataMember2.Name = DataContract.EncodeLocalName(memberInfo.Name);
                    dataMember2.IsNullable = DataContract.IsTypeNullable(dataMember2.MemberType);
                    CheckAndAddMember(list, dataMember2, memberNamesTable);
                    continue;
                }
                FieldInfo fieldInfo2 = memberInfo as FieldInfo;
                if (!((!IsKnownSerializableType(underlyingType)) ? (fieldInfo2 != null && !fieldInfo2.IsNotSerialized) : CanSerializeMember(fieldInfo2)))
                {
                    continue;
                }
                DataMember dataMember3 = new DataMember(memberInfo);
                dataMember3.Name = DataContract.EncodeLocalName(memberInfo.Name);
                object[] customAttributes = fieldInfo2.GetCustomAttributes(Globals.TypeOfOptionalFieldAttribute, inherit: false);
                if (customAttributes == null || customAttributes.Length == 0)
                {
                    if (base.IsReference)
                    {
                        DataContractCriticalHelper.ThrowInvalidDataContractException(System.SR.Format(System.SR.NonOptionalFieldMemberOnIsReferenceSerializableType, DataContract.GetClrTypeFullName(memberInfo.DeclaringType), memberInfo.Name, true), underlyingType);
                    }
                    dataMember3.IsRequired = true;
                }
                dataMember3.IsNullable = DataContract.IsTypeNullable(dataMember3.MemberType);
                CheckAndAddMember(list, dataMember3, memberNamesTable);
            }
            if (list.Count > 1)
            {
                list.Sort(DataMemberComparer.Singleton);
            }
            SetIfMembersHaveConflict(list);
            Interlocked.MemoryBarrier();
            _members = list;
        }
References System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper._isNonAttributedType, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper._members, System.array, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.CanSerializeMember(), System.Runtime.Serialization.ClassDataContract.CheckAndAddMember(), System.Reflection.MemberInfo.DeclaringType, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.EncodeLocalName(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.EnsureIsReferenceImported(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Reflection.PropertyInfo.GetMethod, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.HasDataContract, System.SR.IndexedPropertyCannotBeSerialized, System.SR.InvalidDataMemberName, System.SR.InvalidMember, System.Runtime.Serialization.ClassDataContract.IsKnownSerializableType(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.IsMethodOverriding(), System.SR.IsRequiredDataMemberOnIsReferenceDataContractType, System.Runtime.Serialization.DataContract.IsTypeNullable(), System.list, System.Threading.Interlocked.MemoryBarrier(), System.Reflection.MemberInfo.Name, System.SR.NoGetMethodForProperty, System.SR.NonOptionalFieldMemberOnIsReferenceSerializableType, System.SR.NoSetMethodForProperty, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.SetIfGetOnlyCollection(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.SetIfMembersHaveConflict(), System.Reflection.PropertyInfo.SetMethod, System.Runtime.Serialization.ClassDataContract.DataMemberComparer.Singleton, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(), System.SR.TooManyDataMembers, System.SR.TooManyIgnoreDataMemberAttributes, and System.Runtime.Serialization.Globals.TypeOfOptionalFieldAttribute.
Referenced by System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ClassDataContractCriticalHelper(), and System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ClassDataContractCriticalHelper().