Terraria: System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.EnsureMethodsImported
EnsureMethodsImported()
void System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.EnsureMethodsImported () inline package
Definition at line 684 of file ClassDataContract.cs.
        {
            if (_isMethodChecked || !(base.UnderlyingType != null))
            {
                return;
            }
            lock (this)
            {
                if (_isMethodChecked)
                {
                    return;
                }
                Type underlyingType = base.UnderlyingType;
                MethodInfo[] methods = underlyingType.GetMethods(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                foreach (MethodInfo methodInfo in methods)
                {
                    Type prevAttributeType = null;
                    ParameterInfo[] parameters = methodInfo.GetParameters();
                    if (HasExtensionData && IsValidExtensionDataSetMethod(methodInfo, parameters))
                    {
                        if (methodInfo.Name == "System.Runtime.Serialization.IExtensibleDataObject.set_ExtensionData" || !methodInfo.IsPublic)
{
                            _extensionDataSetMethod = XmlFormatGeneratorStatics.ExtensionDataSetExplicitMethodInfo;
                        }
                        else
{
                            _extensionDataSetMethod = methodInfo;
                        }
                    }
                    if (IsValidCallback(methodInfo, parameters, Globals.TypeOfOnSerializingAttribute, _onSerializing, ref prevAttributeType))
                    {
                        _onSerializing = methodInfo;
                    }
                    if (IsValidCallback(methodInfo, parameters, Globals.TypeOfOnSerializedAttribute, _onSerialized, ref prevAttributeType))
                    {
                        _onSerialized = methodInfo;
                    }
                    if (IsValidCallback(methodInfo, parameters, Globals.TypeOfOnDeserializingAttribute, _onDeserializing, ref prevAttributeType))
                    {
                        _onDeserializing = methodInfo;
                    }
                    if (IsValidCallback(methodInfo, parameters, Globals.TypeOfOnDeserializedAttribute, _onDeserialized, ref prevAttributeType))
                    {
                        _onDeserialized = methodInfo;
                    }
                }
                Interlocked.MemoryBarrier();
                _isMethodChecked = true;
            }
        }
References System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper._extensionDataSetMethod, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper._isMethodChecked, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper._onDeserialized, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper._onDeserializing, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper._onSerialized, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper._onSerializing, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlFormatGeneratorStatics.ExtensionDataSetExplicitMethodInfo, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.HasExtensionData, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.IsValidCallback(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.IsValidExtensionDataSetMethod(), System.Threading.Interlocked.MemoryBarrier(), System.Runtime.Serialization.Globals.TypeOfOnDeserializedAttribute, System.Runtime.Serialization.Globals.TypeOfOnDeserializingAttribute, System.Runtime.Serialization.Globals.TypeOfOnSerializedAttribute, and System.Runtime.Serialization.Globals.TypeOfOnSerializingAttribute.
Referenced by System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ClassDataContractCriticalHelper(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ClassDataContractCriticalHelper(), and System.Runtime.Serialization.ClassDataContract.EnsureMethodsImported().