Terraria: System.Security.Cryptography.CngKey.TryExportKeyBlob
TryExportKeyBlob()
bool System.Security.Cryptography.CngKey.TryExportKeyBlob (string blobType, Span< byte > destination, out int bytesWritten) inline package
Definition at line 643 of file CngKey.cs.
    {
        Span<byte> span = default(Span<byte>);
        global::Interop.NCrypt.ErrorCode errorCode = global::Interop.NCrypt.NCryptExportKey(_keyHandle, IntPtr.Zero, blobType, IntPtr.Zero, ref MemoryMarshal.GetReference(span), span.Length, out var pcbResult, 0);
        if (errorCode != 0)
        {
            throw errorCode.ToCryptographicException();
        }
        if (pcbResult > destination.Length)
        {
            bytesWritten = 0;
            return false;
        }
        errorCode = global::Interop.NCrypt.NCryptExportKey(_keyHandle, IntPtr.Zero, blobType, IntPtr.Zero, ref MemoryMarshal.GetReference(destination), destination.Length, out pcbResult, 0);
        if (errorCode != 0)
        {
            throw errorCode.ToCryptographicException();
        }
        bytesWritten = pcbResult;
        return true;
    }
References System.Security.Cryptography.CngKey._keyHandle, System.destination, System.Span< T >.Length, and System.IntPtr.Zero.
Referenced by System.Security.Cryptography.DSACng.TryExportPkcs8PrivateKey(), System.Security.Cryptography.ECDiffieHellmanCng.TryExportPkcs8PrivateKey(), System.Security.Cryptography.ECDsaCng.TryExportPkcs8PrivateKey(), and System.Security.Cryptography.RSACng.TryExportPkcs8PrivateKey().