Terraria: System.Security.Cryptography.CngKey.Open
Open() [2/4]
static CngKey System.Security.Cryptography.CngKey.Open (string keyName) inline static
Definition at line 799 of file CngKey.cs.
    {
        return Open(keyName, CngProvider.MicrosoftSoftwareKeyStorageProvider);
    }
References System.Security.Cryptography.CngProvider.MicrosoftSoftwareKeyStorageProvider, and System.Security.Cryptography.CngKey.Open().
Referenced by Internal.Cryptography.Pal.Native.SafeCertContextHandleWithKeyContainerDeletion.DeleteKeyContainer(), Internal.Cryptography.CngAlgorithmCore.Duplicate(), Internal.Cryptography.Pal.CertificatePal.GetPrivateKey< T >(), Internal.Cryptography.Pal.CertificatePal.GuessKeySpec(), System.Security.Cryptography.CngKey.Open(), System.Security.Cryptography.CngKey.Open(), and Internal.Cryptography.CngSymmetricAlgorithmCore.ProduceCngKey().