Terraria: System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetNonAttributedTypeConstructor
GetNonAttributedTypeConstructor()
ConstructorInfo System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetNonAttributedTypeConstructor () inline package
Definition at line 815 of file ClassDataContract.cs.
        {
            if (!IsNonAttributedType)
            {
                return null;
            }
            Type underlyingType = base.UnderlyingType;
            if (underlyingType.IsValueType)
            {
                return null;
            }
            ConstructorInfo constructor = underlyingType.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            if (constructor == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.NonAttributedSerializableTypesMustHaveDefaultConstructor, DataContract.GetClrTypeFullName(underlyingType))));
            }
            return constructor;
        }
References System.Runtime.Serialization.Dictionary, System.Type.EmptyTypes, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.IsNonAttributedType, System.SR.NonAttributedSerializableTypesMustHaveDefaultConstructor, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.ClassDataContract.GetNonAttributedTypeConstructor().