Terraria: System.Security.Cryptography.CngKey.InitializeKeyProperties
InitializeKeyProperties()
static unsafe void System.Security.Cryptography.CngKey.InitializeKeyProperties (SafeNCryptKeyHandle keyHandle, CngKeyCreationParameters creationParameters) inline static private
Definition at line 318 of file CngKey.cs.
    {
        if (creationParameters.ExportPolicy.HasValue)
        {
            CngExportPolicies value = creationParameters.ExportPolicy.Value;
            keyHandle.SetExportPolicy(value);
        }
        if (creationParameters.KeyUsage.HasValue)
        {
            CngKeyUsages value2 = creationParameters.KeyUsage.Value;
            global::Interop.NCrypt.ErrorCode errorCode = global::Interop.NCrypt.NCryptSetProperty(keyHandle, "Key Usage", &value2, 4, CngPropertyOptions.Persist);
            if (errorCode != 0)
            {
                throw errorCode.ToCryptographicException();
            }
        }
        if (creationParameters.ParentWindowHandle != IntPtr.Zero)
        {
            IntPtr parentWindowHandle = creationParameters.ParentWindowHandle;
            global::Interop.NCrypt.ErrorCode errorCode2 = global::Interop.NCrypt.NCryptSetProperty(keyHandle, "HWND Handle", &parentWindowHandle, sizeof(IntPtr), CngPropertyOptions.None);
            if (errorCode2 != 0)
            {
                throw errorCode2.ToCryptographicException();
            }
        }
        CngUIPolicy uIPolicy = creationParameters.UIPolicy;
        if (uIPolicy != null)
        {
            InitializeKeyUiPolicyProperties(keyHandle, uIPolicy);
        }
        foreach (CngProperty parameter in creationParameters.Parameters)
        {
            byte[] valueWithoutCopying = parameter.GetValueWithoutCopying();
            int cbInput = ((valueWithoutCopying != null) ? valueWithoutCopying.Length : 0);
            fixed (byte* pbInput = valueWithoutCopying.MapZeroLengthArrayToNonNullPointer())
            {
                global::Interop.NCrypt.ErrorCode errorCode3 = global::Interop.NCrypt.NCryptSetProperty(keyHandle, parameter.Name, pbInput, cbInput, parameter.Options);
                if (errorCode3 != 0)
                {
                    throw errorCode3.ToCryptographicException();
                }
            }
        }
    }
References System.Security.Cryptography.CngKeyCreationParameters.ExportPolicy, System.Security.Cryptography.CngProperty.GetValueWithoutCopying(), System.Security.Cryptography.CngKey.InitializeKeyUiPolicyProperties(), System.Security.Cryptography.CngKeyCreationParameters.KeyUsage, System.Security.Cryptography.CngProperty.Name, System.Security.Cryptography.CngProperty.Options, System.Security.Cryptography.CngKeyCreationParameters.ParentWindowHandle, System.Security.Cryptography.CngKeyCreationParameters.UIPolicy, System.value, and System.IntPtr.Zero.
Referenced by System.Security.Cryptography.CngKey.Create().