Terraria: System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ClassDataContractCriticalHelper
ClassDataContractCriticalHelper() [2/2]
System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ClassDataContractCriticalHelper ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors | DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods | DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicProperties)] Type type, XmlDictionaryString ns, string[] memberNames) inline package
Definition at line 388 of file ClassDataContract.cs.
            : base(type)
        {
            base.StableName = new XmlQualifiedName(GetStableNameAndSetHasDataContract(type).Name, ns.Value);
            ImportDataMembers();
            XmlDictionary xmlDictionary = new XmlDictionary(1 + Members.Count);
            base.Name = xmlDictionary.Add(base.StableName.Name);
            base.Namespace = ns;
            ContractNamespaces = new XmlDictionaryString[1] { base.Namespace };
            MemberNames = new XmlDictionaryString[Members.Count];
            MemberNamespaces = new XmlDictionaryString[Members.Count];
            for (int i = 0; i < Members.Count; i++)
            {
                Members[i].Name = memberNames[i];
                MemberNames[i] = xmlDictionary.Add(Members[i].Name);
                MemberNamespaces[i] = base.Namespace;
            }
            EnsureMethodsImported();
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ContractNamespaces, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.EnsureMethodsImported(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetStableNameAndSetHasDataContract(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.MemberNames, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.MemberNamespaces, System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.Members, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.Name, System.type, and System.Xml.XmlDictionaryString.Value.