Terraria: System.Security.Cryptography.CngKey.Import
Import() [5/6]
static CngKey System.Security.Cryptography.CngKey.Import (ReadOnlySpan< byte > keyBlob, CngKeyBlobFormat format) inline static package
Definition at line 525 of file CngKey.cs.
    {
        return Import(keyBlob, null, format, CngProvider.MicrosoftSoftwareKeyStorageProvider);
    }
References System.format, System.Security.Cryptography.CngKey.Import(), and System.Security.Cryptography.CngProvider.MicrosoftSoftwareKeyStorageProvider.
Referenced by Internal.Cryptography.Pal.X509Pal.DecodeECPublicKey< TAlgorithm >(), Internal.Cryptography.Pal.X509Pal.DecodePublicKey(), System.Security.Cryptography.ECDiffieHellmanCng.DeriveKeyMaterial(), System.Security.Cryptography.ECDiffieHellmanCng.DeriveSecretAgreementHandle(), System.Security.Cryptography.ECDiffieHellmanCngPublicKey.FromByteArray(), System.Security.Cryptography.ECDiffieHellmanCngPublicKey.Import(), System.Security.Cryptography.CngKey.Import(), System.Security.Cryptography.CngKey.Import(), System.Security.Cryptography.CngKey.Import(), System.Security.Cryptography.CngKey.Import(), System.Security.Cryptography.CngKey.Import(), System.Security.Cryptography.ECCng.ImportFullKeyBlob(), System.Security.Cryptography.DSACng.ImportKeyBlob(), System.Security.Cryptography.ECCng.ImportKeyBlob(), System.Security.Cryptography.RSACng.ImportKeyBlob(), and System.Security.Cryptography.CngPkcs8.ImportPkcs8().