Terraria: System.Security.Cryptography.CngKey.ImportEncryptedPkcs8
ImportEncryptedPkcs8() [1/2]
static CngKey System.Security.Cryptography.CngKey.ImportEncryptedPkcs8 (ReadOnlySpan< byte > keyBlob, ReadOnlySpan< char > password) inline static package
Definition at line 545 of file CngKey.cs.
    {
        return ImportEncryptedPkcs8(keyBlob, password, CngProvider.MicrosoftSoftwareKeyStorageProvider);
    }
References System.Security.Cryptography.CngKey.ImportEncryptedPkcs8(), and System.Security.Cryptography.CngProvider.MicrosoftSoftwareKeyStorageProvider.
Referenced by System.Security.Cryptography.CngKey.ImportEncryptedPkcs8(), and System.Security.Cryptography.CngPkcs8.ImportPkcs8().