Terraria: System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.IsValidExtensionDataSetMethod
IsValidExtensionDataSetMethod()
bool System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.IsValidExtensionDataSetMethod (MethodInfo method, ParameterInfo[] parameters) inline private
Definition at line 735 of file ClassDataContract.cs.
        {
            if (method.Name == "System.Runtime.Serialization.IExtensibleDataObject.set_ExtensionData" || method.Name == "set_ExtensionData")
            {
                if (_extensionDataSetMethod != null)
                {
                    ThrowInvalidDataContractException(System.SR.Format(System.SR.DuplicateExtensionDataSetMethod, method, _extensionDataSetMethod, DataContract.GetClrTypeFullName(method.DeclaringType)));
                }
                if (method.ReturnType != Globals.TypeOfVoid)
                {
                    DataContract.ThrowInvalidDataContractException(System.SR.Format(System.SR.ExtensionDataSetMustReturnVoid, DataContract.GetClrTypeFullName(method.DeclaringType), method), method.DeclaringType);
                }
                if (parameters == null || parameters.Length != 1 || parameters[0].ParameterType != Globals.TypeOfExtensionDataObject)
                {
                    DataContract.ThrowInvalidDataContractException(System.SR.Format(System.SR.ExtensionDataSetParameterInvalid, DataContract.GetClrTypeFullName(method.DeclaringType), method, Globals.TypeOfExtensionDataObject), method.DeclaringType);
                }
                return true;
            }
            return false;
        }
References System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper._extensionDataSetMethod, System.SR.DuplicateExtensionDataSetMethod, System.SR.ExtensionDataSetMustReturnVoid, System.SR.ExtensionDataSetParameterInvalid, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Reflection.ParameterInfo.ParameterType, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(), System.Runtime.Serialization.DataContract.ThrowInvalidDataContractException(), System.Runtime.Serialization.Globals.TypeOfExtensionDataObject, and System.Runtime.Serialization.Globals.TypeOfVoid.
Referenced by System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.EnsureMethodsImported().