Terraria: System.Security.Cryptography.CngKey.ExportPkcs8KeyBlob
ExportPkcs8KeyBlob() [2/2]
byte[] System.Security.Cryptography.CngKey.ExportPkcs8KeyBlob (ReadOnlySpan< char > password, int kdfCount) inline package
Definition at line 665 of file CngKey.cs.
    {
        int bytesWritten;
        byte[] allocated;
        bool flag = ExportPkcs8KeyBlob(allocate: true, _keyHandle, password, kdfCount, Span<byte>.Empty, out bytesWritten, out allocated);
        return allocated;
    }
References System.Security.Cryptography.CngKey._keyHandle, System.Span< T >.Empty, and System.Security.Cryptography.CngKey.ExportPkcs8KeyBlob().
Referenced by System.Security.Cryptography.DSACng.ExportEncryptedPkcs8(), System.Security.Cryptography.ECDiffieHellmanCng.ExportEncryptedPkcs8(), System.Security.Cryptography.ECDsaCng.ExportEncryptedPkcs8(), System.Security.Cryptography.RSACng.ExportEncryptedPkcs8(), System.Security.Cryptography.CngKey.ExportPkcs8KeyBlob(), and System.Security.Cryptography.CngKey.TryExportPkcs8KeyBlob().