Terraria: System.Security.Cryptography.CngKey.Dispose
Dispose()
void System.Security.Cryptography.CngKey.Dispose () inline
Implements System.IDisposable.
Definition at line 215 of file CngKey.cs.
    {
        if (_providerHandle != null)
        {
            _providerHandle.Dispose();
        }
        if (_keyHandle != null)
        {
            _keyHandle.Dispose();
        }
    }
References System.Security.Cryptography.CngKey._keyHandle, System.Security.Cryptography.CngKey._providerHandle, and System.Runtime.InteropServices.SafeHandle.Dispose().
Referenced by System.Security.Cryptography.CngKey.Delete(), Internal.Cryptography.BasicSymmetricCipherNCrypt.Dispose(), Internal.Cryptography.CngAlgorithmCore.DisposeKey(), System.Security.Cryptography.CngPkcs8.Pkcs8Response.FreeKey(), and System.Security.Cryptography.CngKey.Open().