Terraria: System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.EnsureIsReferenceImported
EnsureIsReferenceImported()
void System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.EnsureIsReferenceImported (Type type) inline private
Definition at line 408 of file ClassDataContract.cs.
        {
            bool flag = false;
            DataContractAttribute dataContractAttribute;
            bool flag2 = DataContract.TryGetDCAttribute(type, out dataContractAttribute);
            if (BaseContract != null)
            {
                if (flag2 && dataContractAttribute.IsReferenceSetExplicitly)
                {
                    bool isReference = BaseContract.IsReference;
                    if ((isReference && !dataContractAttribute.IsReference) || (!isReference && dataContractAttribute.IsReference))
                    {
                        DataContract.ThrowInvalidDataContractException(System.SR.Format(System.SR.InconsistentIsReference, DataContract.GetClrTypeFullName(type), dataContractAttribute.IsReference, DataContract.GetClrTypeFullName(BaseContract.UnderlyingType), BaseContract.IsReference), type);
                    }
                    else
                    {
                        flag = dataContractAttribute.IsReference;
                    }
                }
                else
                {
                    flag = BaseContract.IsReference;
                }
            }
            else if (flag2 && dataContractAttribute.IsReference)
            {
                flag = dataContractAttribute.IsReference;
            }
            if (flag && type.IsValueType)
            {
                DataContract.ThrowInvalidDataContractException(System.SR.Format(System.SR.ValueTypeCannotHaveIsReference, DataContract.GetClrTypeFullName(type), true, false), type);
            }
            else
            {
                base.IsReference = flag;
            }
        }
References System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.BaseContract, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.InconsistentIsReference, System.Runtime.Serialization.DataContract.IsReference, System.Runtime.Serialization.DataContract.ThrowInvalidDataContractException(), System.Runtime.Serialization.DataContract.TryGetDCAttribute(), System.type, System.Runtime.Serialization.DataContract.UnderlyingType, and System.SR.ValueTypeCannotHaveIsReference.
Referenced by System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers().