Terraria: System.Security.Cryptography.CngKey.CngKey
CngKey()
System.Security.Cryptography.CngKey.CngKey (SafeNCryptProviderHandle providerHandle, SafeNCryptKeyHandle keyHandle) inline private
Definition at line 209 of file CngKey.cs.
    {
        _providerHandle = providerHandle;
        _keyHandle = keyHandle;
    }
References System.Security.Cryptography.CngKey._keyHandle, and System.Security.Cryptography.CngKey._providerHandle.
Referenced by System.Security.Cryptography.CngKey.Create(), System.Security.Cryptography.CngKey.Import(), System.Security.Cryptography.CngKey.ImportEncryptedPkcs8(), System.Security.Cryptography.CngKey.Open(), and System.Security.Cryptography.CngKey.Open().