Terraria: System.Security.Cryptography.CngKey.Open
Open() [1/4]
static CngKey System.Security.Cryptography.CngKey.Open (SafeNCryptKeyHandle keyHandle, CngKeyHandleOpenOptions keyHandleOpenOptions) inline static
Definition at line 829 of file CngKey.cs.
    {
        if (keyHandle == null)
        {
            throw new ArgumentNullException("keyHandle");
        }
        if (keyHandle.IsClosed || keyHandle.IsInvalid)
        {
            throw new ArgumentException(System.SR.Cryptography_OpenInvalidHandle, "keyHandle");
        }
        SafeNCryptKeyHandle keyHandle2 = keyHandle.Duplicate();
        SafeNCryptProviderHandle safeNCryptProviderHandle = new SafeNCryptProviderHandle();
        IntPtr propertyAsIntPtr = keyHandle.GetPropertyAsIntPtr("Provider Handle", CngPropertyOptions.None);
        safeNCryptProviderHandle.SetHandleValue(propertyAsIntPtr);
        CngKey cngKey = null;
        try
        {
            cngKey = new CngKey(safeNCryptProviderHandle, keyHandle2);
            bool flag = (keyHandleOpenOptions & CngKeyHandleOpenOptions.EphemeralKey) == CngKeyHandleOpenOptions.EphemeralKey;
            if (!cngKey.IsEphemeral && flag)
            {
                cngKey.IsEphemeral = true;
            }
            else if (cngKey.IsEphemeral && !flag)
            {
                throw new ArgumentException(System.SR.Cryptography_OpenEphemeralKeyHandleWithoutEphemeralFlag, "keyHandleOpenOptions");
            }
        }
        catch
        {
            cngKey?.Dispose();
            throw;
        }
        return cngKey;
    }
References System.Security.Cryptography.CngKey.CngKey(), System.SR.Cryptography_OpenEphemeralKeyHandleWithoutEphemeralFlag, System.SR.Cryptography_OpenInvalidHandle, System.Security.Cryptography.CngKey.Dispose(), Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle.Duplicate(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.Security.Cryptography.CngKey.IsEphemeral, Microsoft.Win32.SafeHandles.SafeNCryptHandle.IsInvalid, and Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle.SetHandleValue().