Terraria: System.Collections.Generic.ArraySortHelper.IntroSort
IntroSort() [2/2]
static void System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntroSort (Span< TKey > keys, Span< TValue > values, int depthLimit, IComparer< TKey > comparer) inline static private
Definition at line 309 of file ArraySortHelper.cs.
    {
        int num = keys.Length;
        while (num > 1)
        {
            if (num <= 16)
            {
                switch (num)
                {
                case 2:
                    SwapIfGreaterWithValues(keys, values, comparer, 0, 1);
                    break;
                case 3:
                    SwapIfGreaterWithValues(keys, values, comparer, 0, 1);
                    SwapIfGreaterWithValues(keys, values, comparer, 0, 2);
                    SwapIfGreaterWithValues(keys, values, comparer, 1, 2);
                    break;
                default:
                    InsertionSort(keys.Slice(0, num), values.Slice(0, num), comparer);
                    break;
                }
                break;
            }
            if (depthLimit == 0)
            {
                HeapSort(keys.Slice(0, num), values.Slice(0, num), comparer);
                break;
            }
            depthLimit--;
            int num2 = PickPivotAndPartition(keys.Slice(0, num), values.Slice(0, num), comparer);
            Span<TKey> span = keys;
            Span<TKey> keys2 = span[(num2 + 1)..num];
            Span<TValue> span2 = values;
            IntroSort(keys2, span2[(num2 + 1)..num], depthLimit, comparer);
            num = num2;
        }
    }
References System.comparer, System.Collections.Generic.ArraySortHelper< TKey, TValue >.HeapSort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.InsertionSort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntroSort(), System.keys, System.Collections.Generic.ArraySortHelper< TKey, TValue >.PickPivotAndPartition(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.SwapIfGreaterWithValues(), and System.values.