Terraria: System.Collections.Generic.ArraySortHelper.IntrospectiveSort
IntrospectiveSort() [1/2]
static void System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntrospectiveSort (Span< T > keys, Comparison< T > comparer) inline static package
Definition at line 119 of file ArraySortHelper.cs.
    {
        if (keys.Length > 1)
        {
            IntroSort(keys, 2 * (BitOperations.Log2((uint)keys.Length) + 1), comparer);
        }
    }
References System.comparer, System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntroSort(), System.keys, and System.Numerics.BitOperations.Log2().
Referenced by System.Collections.Generic.ArraySortHelper< TKey, TValue >.Sort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.Sort(), and System.Collections.Generic.ArraySortHelper< TKey, TValue >.Sort().