Terraria: System.Collections.Generic.ArraySortHelper.IntroSort
IntroSort() [1/2]
static void System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntroSort (Span< T > keys, int depthLimit, Comparison< T > comparer) inline static private
Definition at line 127 of file ArraySortHelper.cs.
    {
        int num = keys.Length;
        while (num > 1)
        {
            if (num <= 16)
            {
                switch (num)
                {
                case 2:
                    SwapIfGreater(keys, comparer, 0, 1);
                    break;
                case 3:
                    SwapIfGreater(keys, comparer, 0, 1);
                    SwapIfGreater(keys, comparer, 0, 2);
                    SwapIfGreater(keys, comparer, 1, 2);
                    break;
                default:
                    InsertionSort(keys.Slice(0, num), comparer);
                    break;
                }
                break;
            }
            if (depthLimit == 0)
            {
                HeapSort(keys.Slice(0, num), comparer);
                break;
            }
            depthLimit--;
            int num2 = PickPivotAndPartition(keys.Slice(0, num), comparer);
            Span<T> span = keys;
            IntroSort(span[(num2 + 1)..num], depthLimit, comparer);
            num = num2;
        }
    }
References System.comparer, System.Collections.Generic.ArraySortHelper< TKey, TValue >.HeapSort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.InsertionSort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntroSort(), System.keys, System.Collections.Generic.ArraySortHelper< TKey, TValue >.PickPivotAndPartition(), and System.Collections.Generic.ArraySortHelper< TKey, TValue >.SwapIfGreater().
Referenced by System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntroSort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntroSort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntrospectiveSort(), and System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntrospectiveSort().