Terraria: Terraria.ObjectData.TileObjectData.addTile
addTile()
static void Terraria.ObjectData.TileObjectData.addTile (int tileType) inline static private
    {
        newTile.Calculate();
        _data[tileType] = newTile;
        newTile = new TileObjectData(_baseObject);
    }
References Terraria.ObjectData.TileObjectData.TileObjectData(), Terraria.ObjectData.TileObjectData._baseObject, Terraria.ObjectData.TileObjectData._data, Terraria.ObjectData.TileObjectData.Calculate(), and Terraria.ObjectData.TileObjectData.newTile.
Referenced by Terraria.ObjectData.TileObjectData.Initialize().