Terraria: Terraria.ObjectData.TileObjectData.addSubTile
addSubTile() [2/2]
static void Terraria.ObjectData.TileObjectData.addSubTile (params int[] styles) inline static private
    {
        newSubTile.Calculate();
        foreach (int num in styles)
        {
            List<TileObjectData> list;
            if (!newTile._hasOwnSubTiles)
            {
                list = new List<TileObjectData>(num + 1);
                newTile.SubTiles = list;
            }
            else
            {
                list = newTile.SubTiles;
            }
            if (list.Count <= num)
            {
                for (int j = list.Count; j <= num; j++)
                {
                    list.Add(null);
                }
            }
            newSubTile._parent = newTile;
            list[num] = newSubTile;
        }
        newSubTile = new TileObjectData(_baseObject);
    }
References Terraria.ObjectData.TileObjectData.TileObjectData(), Terraria.ObjectData.TileObjectData._baseObject, Terraria.ObjectData.TileObjectData._hasOwnSubTiles, Terraria.ObjectData.TileObjectData.Calculate(), Terraria.ObjectData.TileObjectData.newSubTile, Terraria.ObjectData.TileObjectData.newTile, and Terraria.ObjectData.TileObjectData.SubTiles.
Referenced by Terraria.ObjectData.TileObjectData.Initialize().