Terraria: Terraria.ObjectData.TileObjectData.TileObjectData
TileObjectData()
Terraria.ObjectData.TileObjectData.TileObjectData (TileObjectData copyFrom = null) inline
Definition at line 1584 of file TileObjectData.cs.
    {
        _parent = null;
        _linkedAlternates = false;
        if (copyFrom == null)
        {
            _usesCustomCanPlace = false;
            _alternates = null;
            _anchor = null;
            _anchorTiles = null;
            _tileObjectBase = null;
            _liquidDeath = null;
            _liquidPlacement = null;
            _placementHooks = null;
            _tileObjectDraw = null;
            _tileObjectStyle = null;
            _tileObjectCoords = null;
        }
        else
        {
            CopyFrom(copyFrom);
        }
    }
References Terraria.ObjectData.TileObjectData._alternates, Terraria.ObjectData.TileObjectData._anchor, Terraria.ObjectData.TileObjectData._anchorTiles, Terraria.ObjectData.TileObjectData._linkedAlternates, Terraria.ObjectData.TileObjectData._liquidDeath, Terraria.ObjectData.TileObjectData._liquidPlacement, Terraria.ObjectData.TileObjectData._parent, Terraria.ObjectData.TileObjectData._placementHooks, Terraria.ObjectData.TileObjectData._tileObjectBase, Terraria.ObjectData.TileObjectData._tileObjectCoords, Terraria.ObjectData.TileObjectData._tileObjectDraw, Terraria.ObjectData.TileObjectData._tileObjectStyle, Terraria.ObjectData.TileObjectData._usesCustomCanPlace, and Terraria.ObjectData.TileObjectData.CopyFrom().
Referenced by Terraria.ObjectData.TileObjectData.addAlternate(), Terraria.ObjectData.TileObjectData.addBaseTile(), Terraria.ObjectData.TileObjectData.addSubTile(), Terraria.ObjectData.TileObjectData.addSubTile(), Terraria.ObjectData.TileObjectData.addTile(), and Terraria.ObjectData.TileObjectData.Initialize().