Terraria: Terraria.ObjectData.TileObjectData.addAlternate
addAlternate()
static void Terraria.ObjectData.TileObjectData.addAlternate (int baseStyle) inline static private
    {
        newAlternate.Calculate();
        if (!newTile._hasOwnAlternates)
        {
            newTile.Alternates = new List<TileObjectData>();
        }
        newAlternate.Style = baseStyle;
        newAlternate._parent = newTile;
        newTile.Alternates.Add(newAlternate);
        newAlternate = new TileObjectData(_baseObject);
    }
References Terraria.ObjectData.TileObjectData.TileObjectData(), Terraria.ObjectData.TileObjectData._baseObject, Terraria.ObjectData.TileObjectData._hasOwnAlternates, Terraria.ObjectData.TileObjectData.Alternates, Terraria.ObjectData.TileObjectData.Calculate(), Terraria.ObjectData.TileObjectData.newAlternate, and Terraria.ObjectData.TileObjectData.newTile.
Referenced by Terraria.ObjectData.TileObjectData.Initialize().