Terraria: Terraria.ObjectData.TileObjectData.CallPostPlacementPlayerHook
CallPostPlacementPlayerHook()
static bool Terraria.ObjectData.TileObjectData.CallPostPlacementPlayerHook (int tileX, int tileY, int type, int style, int dir, int alternate, TileObject data) inline static
    {
        TileObjectData tileData = GetTileData(type, style, data.alternate);
        if (tileData == null || tileData._placementHooks == null || tileData._placementHooks.postPlaceMyPlayer.hook == null)
        {
            return false;
        }
        PlacementHook postPlaceMyPlayer = tileData._placementHooks.postPlaceMyPlayer;
        if (postPlaceMyPlayer.processedCoordinates)
        {
            tileX -= tileData.Origin.X;
            tileY -= tileData.Origin.Y;
        }
        return postPlaceMyPlayer.hook(tileX, tileY, type, style, dir, data.alternate) == postPlaceMyPlayer.badReturn;
    }
References Terraria.ObjectData.TileObjectData._placementHooks, Terraria.TileObject.alternate, Terraria.DataStructures.PlacementHook.badReturn, Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.DataStructures.PlacementHook.hook, Terraria.ObjectData.TileObjectData.Origin, Terraria.Modules.TilePlacementHooksModule.postPlaceMyPlayer, Terraria.DataStructures.PlacementHook.processedCoordinates, Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.Player.PlaceThing_Tiles_PlaceIt(), and Terraria.Player.TryReplantingTree().