Terraria: System.Buffers.ConfigurableArrayPool.Return
Return()
override void System.Buffers.ConfigurableArrayPool< T >.Return (T[] array, bool clearArray = false) inline
Definition at line 181 of file ConfigurableArrayPool.cs.
    {
        if (array == null)
        {
            throw new ArgumentNullException("array");
        }
        if (array.Length == 0)
        {
            return;
        }
        int num = Utilities.SelectBucketIndex(array.Length);
        bool flag = num < _buckets.Length;
        if (flag)
        {
            if (clearArray)
            {
                Array.Clear(array);
            }
            _buckets[num].Return(array);
        }
        ArrayPoolEventSource log = ArrayPoolEventSource.Log;
        if (log.IsEnabled())
        {
            int hashCode = array.GetHashCode();
            log.BufferReturned(hashCode, array.Length, Id);
            if (!flag)
            {
                log.BufferDropped(hashCode, array.Length, Id, -1, ArrayPoolEventSource.BufferDroppedReason.Full);
            }
        }
    }
References System.Buffers.ConfigurableArrayPool< T >._buckets, System.array, System.Buffers.ArrayPoolEventSource.BufferDropped(), System.Buffers.ArrayPoolEventSource.BufferReturned(), System.Array.Clear(), System.Buffers.ConfigurableArrayPool< T >.Id, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Buffers.ArrayPoolEventSource.Log, System.Buffers.ConfigurableArrayPool< T >.Bucket.Return(), and System.Buffers.Utilities.SelectBucketIndex().