Terraria: Terraria.UI.Gamepad.UILinkPointNavigator.Points
Points
Dictionary<int, UILinkPoint> Terraria.UI.Gamepad.UILinkPointNavigator.Points = new Dictionary<int, UILinkPoint>() static
Referenced by Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.UI.Gamepad.UILinkPointNavigator.ConsumeSuggestion(), Terraria.UI.Gamepad.UILinkPointNavigator.ConsumeSuggestionSwap(), Terraria.GameContent.UI.States.UICharacterCreation.GetAndSet(), Terraria.UI.Gamepad.UILinkPointNavigator.GetInstructions(), Terraria.GameContent.UI.States.UIBestiaryTest.MakeLinkPointFromSnapPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.MakeLinkPointFromSnapPoint(), Terraria.GameContent.UI.States.UICharacterCreation.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIBestiaryTest.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIWorldLoad.OnActivate(), Terraria.UI.Gamepad.UILinkPointNavigator.RegisterPage(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIAchievementsMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIBestiaryTest.SetupGamepadPoints(), Terraria.GameContent.UI.States.UICharacterCreation.SetupGamepadPoints(), Terraria.GameContent.UI.States.UICharacterSelect.SetupGamepadPoints(), Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIManageControls.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIVirtualKeyboard.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorldCreation.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorldSelect.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints2(), Terraria.UI.Gamepad.UILinkPointNavigator.SuggestUsage(), Terraria.GameContent.UI.States.UIGamepadHelper.TryMovingBackIntoCreativeGridIfOutOfIt(), Terraria.UI.Gamepad.UILinkPointNavigator.Update(), and Terraria.GameContent.UI.States.UIWorldLoad.UpdateGamepadSquiggle().