Terraria: Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint
ChangePoint()
static void Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint (int PointID) inline static
References Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPage, Terraria.UI.Gamepad.UILinkPointNavigator.OverridePoint, Terraria.UI.Gamepad.UILinkPointNavigator.Points, and Terraria.UI.Gamepad.UILinkPointNavigator.ProcessChanges().
Referenced by Terraria.GameInput.PlayerInput.ExitBuildingMode(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.GameContent.UI.States.UICharacterCreation.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIBestiaryTest.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIAchievementsMenu.OnActivate(), Terraria.GameContent.UI.States.UICharacterSelect.OnActivate(), Terraria.GameContent.UI.States.UIManageControls.OnActivate(), Terraria.GameContent.UI.States.UIVirtualKeyboard.OnActivate(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.OnActivate(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.OnActivate(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.OnActivate(), Terraria.GameContent.UI.States.UIWorldLoad.OnActivate(), Terraria.GameContent.UI.States.UIWorldSelect.OnActivate(), Terraria.GameContent.UI.States.UICharacterSelect.SetupGamepadPoints(), Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIManageControls.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorldSelect.SetupGamepadPoints(), Terraria.UI.Gamepad.UILinkPage.Travel(), and Terraria.UI.Gamepad.GamepadMainMenuHandler.Update().