Terraria: Terraria.UI.Gamepad.UILinkPointNavigator.GoToDefaultPage
GoToDefaultPage()
static void Terraria.UI.Gamepad.UILinkPointNavigator.GoToDefaultPage (int specialFlag = 0) inline static
Definition at line 137 of file UILinkPointNavigator.cs.
    {
        TileEntity tileEntity = Main.LocalPlayer.tileEntityAnchor.GetTileEntity();
        if (Main.MenuUI.IsVisible)
        {
            CurrentPage = 1004;
        }
        else if (Main.InGameUI.IsVisible || specialFlag == 1)
        {
            CurrentPage = 1004;
        }
        else if (Main.gameMenu)
        {
            CurrentPage = 1000;
        }
        else if (Main.ingameOptionsWindow)
        {
            CurrentPage = 1001;
        }
        else if (Main.CreativeMenu.Enabled)
        {
            CurrentPage = 1005;
        }
        else if (Main.hairWindow)
        {
            CurrentPage = 12;
        }
        else if (Main.clothesWindow)
        {
            CurrentPage = 15;
        }
        else if (Main.npcShop != 0)
        {
            CurrentPage = 13;
        }
        else if (Main.InGuideCraftMenu)
        {
            CurrentPage = 0;
        }
        else if (Main.InReforgeMenu)
        {
            CurrentPage = 0;
        }
        else if (Main.player[Main.myPlayer].chest != -1)
        {
            CurrentPage = 4;
        }
        else if (tileEntity is TEDisplayDoll)
        {
            CurrentPage = 20;
        }
        else if (tileEntity is TEHatRack)
        {
            CurrentPage = 21;
        }
        else if (Main.player[Main.myPlayer].talkNPC != -1 || Main.player[Main.myPlayer].sign != -1)
        {
            CurrentPage = 1003;
        }
        else
        {
            CurrentPage = 0;
        }
    }
References Terraria.Main.clothesWindow, Terraria.Main.CreativeMenu, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPage, Terraria.Main.gameMenu, Terraria.Main.hairWindow, Terraria.Main.ingameOptionsWindow, Terraria.Main.InGameUI, Terraria.Main.InGuideCraftMenu, Terraria.Main.InReforgeMenu, Terraria.Main.LocalPlayer, Terraria.Main.MenuUI, Terraria.Main.myPlayer, Terraria.Main.npcShop, and Terraria.Main.player.
Referenced by Terraria.Main.GUIChatDrawInner(), Terraria.UI.IngameFancyUI.OpenVirtualKeyboard(), Terraria.UI.Gamepad.UILinkPointNavigator.ProcessChanges(), and Terraria.UI.Gamepad.UILinkPointNavigator.Update().