Terraria: Terraria.UI.Gamepad.UILinkPointNavigator.ProcessChanges
ProcessChanges()
static void Terraria.UI.Gamepad.UILinkPointNavigator.ProcessChanges () inline static
    {
        UILinkPage value = Pages[OldPage];
        if (OldPage != CurrentPage)
        {
            value.Leave();
            if (!Pages.TryGetValue(CurrentPage, out value))
            {
                GoToDefaultPage();
                ProcessChanges();
                OverridePoint = -1;
            }
            value.CurrentPoint = value.DefaultPoint;
            value.Enter();
            value.Update();
            OldPage = CurrentPage;
        }
        if (OverridePoint != -1 && value.LinkMap.ContainsKey(OverridePoint))
        {
            value.CurrentPoint = OverridePoint;
        }
    }
References Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPage, Terraria.UI.Gamepad.UILinkPointNavigator.GoToDefaultPage(), Terraria.UI.Gamepad.UILinkPage.Leave(), Terraria.UI.Gamepad.UILinkPage.LinkMap, Terraria.UI.Gamepad.UILinkPointNavigator.OldPage, Terraria.UI.Gamepad.UILinkPointNavigator.OverridePoint, Terraria.UI.Gamepad.UILinkPointNavigator.Pages, and Terraria.UI.Gamepad.UILinkPointNavigator.ProcessChanges().
Referenced by Terraria.UI.Gamepad.UILinkPointNavigator.ChangePage(), Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.UI.Gamepad.UILinkPointNavigator.ConsumeSuggestion(), Terraria.UI.Gamepad.UILinkPointNavigator.ProcessChanges(), and Terraria.UI.Gamepad.UILinkPointNavigator.Update().