Terraria: Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition
SetPosition()
static void Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition (int ID, Vector2 Position) inline static
Definition at line 456 of file UILinkPointNavigator.cs.
    {
        Points[ID].Position = Position * Main.UIScale;
    }
References Terraria.UI.Gamepad.UILinkPointNavigator.Points, and Terraria.Main.UIScale.
Referenced by Terraria.UI.ItemSlot.Draw(), Terraria.Main.DrawBestiaryIcon(), Terraria.Main.DrawBlockReplacementIcon(), Terraria.Main.DrawBuilderAccToggles(), Terraria.UI.ChestUI.DrawButton(), Terraria.Main.DrawClothesWindow(), Terraria.Main.DrawDefenseCounter(), Terraria.Main.DrawEmoteBubblesButton(), Terraria.Main.DrawHairWindow(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawInventory(), Terraria.Main.DrawLoadoutButtons(), Terraria.Main.DrawMenu(), Terraria.Main.DrawNPCChatButtons(), Terraria.Main.DrawNPCHousesInUI(), Terraria.Main.DrawPageIcons(), Terraria.Main.DrawPVPIcons(), Terraria.Main.DrawSettingButton(), Terraria.GameContent.Creative.CreativeUI.DrawToggleButton(), Terraria.Main.DrawTorchBiomeSwapIcon(), Terraria.GameContent.UI.States.UICharacterCreation.GetAndSet(), Terraria.GameContent.UI.States.UIBestiaryTest.MakeLinkPointFromSnapPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.MakeLinkPointFromSnapPoint(), Terraria.GameContent.UI.States.UIAchievementsMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UICharacterCreation.SetupGamepadPoints(), Terraria.GameContent.UI.States.UICharacterSelect.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIManageControls.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIVirtualKeyboard.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorldCreation.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorldSelect.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints2(), Terraria.UI.Gamepad.GamepadMainMenuHandler.Update(), and Terraria.GameContent.UI.States.UIWorldLoad.UpdateGamepadSquiggle().