Terraria: System.Xml.XmlBoundElement.WriteBoundElementContentTo
WriteBoundElementContentTo()
static void System.Xml.XmlBoundElement.WriteBoundElementContentTo (DataPointer dp, XmlWriter w) inline static private
Definition at line 316 of file XmlBoundElement.cs.
    {
        if (!dp.IsEmptyElement && dp.MoveToFirstChild())
        {
            do
            {
                WriteTo(dp, w);
            }
            while (dp.MoveToNextSibling());
            dp.MoveToParent();
        }
    }
References System.Xml.Dictionary, and System.Xml.XmlBoundElement.WriteTo().
Referenced by System.Xml.XmlBoundElement.WriteBoundElementTo(), System.Xml.XmlBoundElement.WriteContentTo(), and System.Xml.XmlBoundElement.WriteRootBoundElementTo().