Terraria: System.Xml.XmlBoundElement.WriteTo
WriteTo() [2/2]
override void System.Xml.XmlBoundElement.WriteTo (XmlWriter w) inline
Definition at line 241 of file XmlBoundElement.cs.
    {
        DataPointer dataPointer = new DataPointer((XmlDataDocument)OwnerDocument, this);
        try
        {
            dataPointer.AddPointer();
            WriteRootBoundElementTo(dataPointer, w);
        }
        finally
        {
            dataPointer.SetNoLongerUse();
        }
    }
References System.Xml.Dictionary, System.Xml.XmlElement.OwnerDocument, and System.Xml.XmlBoundElement.WriteRootBoundElementTo().
Referenced by System.Xml.XmlBoundElement.WriteBoundElementContentTo(), System.Xml.XmlBoundElement.WriteBoundElementTo(), System.Xml.XmlBoundElement.WriteRootBoundElementTo(), and System.Xml.XmlBoundElement.WriteTo().