Terraria: System.Xml.XmlBoundElement.WriteRootBoundElementTo
WriteRootBoundElementTo()
void System.Xml.XmlBoundElement.WriteRootBoundElementTo (DataPointer dp, XmlWriter w) inline private
Definition at line 256 of file XmlBoundElement.cs.
    {
        XmlDataDocument xmlDataDocument = (XmlDataDocument)OwnerDocument;
        w.WriteStartElement(dp.Prefix, dp.LocalName, dp.NamespaceURI);
        int attributeCount = dp.AttributeCount;
        bool flag = false;
        if (attributeCount > 0)
        {
            for (int i = 0; i < attributeCount; i++)
            {
                dp.MoveToAttribute(i);
                if (dp.Prefix == "xmlns" && dp.LocalName == "xsi")
                {
                    flag = true;
                }
                WriteTo(dp, w);
                dp.MoveToOwnerElement();
            }
        }
        if (!flag && xmlDataDocument._bLoadFromDataSet && xmlDataDocument._bHasXSINIL)
        {
            w.WriteAttributeString("xmlns", "xsi", "http://www.w3.org/2000/xmlns/", "http://www.w3.org/2001/XMLSchema-instance");
        }
        WriteBoundElementContentTo(dp, w);
        if (dp.IsEmptyElement)
        {
            w.WriteEndElement();
        }
        else
        {
            w.WriteFullEndElement();
        }
    }
References System.Xml.Dictionary, System.Xml.XmlElement.OwnerDocument, System.Xml.XmlBoundElement.WriteBoundElementContentTo(), and System.Xml.XmlBoundElement.WriteTo().
Referenced by System.Xml.XmlBoundElement.WriteTo().