Terraria: System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync
ConnectAsync()
ValueTask System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync (Socket socket) inline
Definition at line 256 of file Socket.cs.
        {
            try
            {
                if (socket.ConnectAsync(this, userSocket: true, saeaCancelable: false))
                {
                    return new ValueTask(this, _token);
                }
            }
            catch
            {
                Release();
                throw;
            }
            SocketError socketError = base.SocketError;
            Release();
            if (socketError != 0)
            {
                return ValueTask.FromException(CreateException(socketError));
            }
            return default(ValueTask);
        }
References System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._token, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(), System.Threading.Tasks.ValueTask< TResult >.FromException(), and System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.Release().