Terraria: System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.Release
Release()
void System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.Release () inline private
Definition at line 75 of file Socket.cs.
        {
            _cancellationToken = default(CancellationToken);
            _token++;
            _continuation = null;
            if (Interlocked.CompareExchange(ref _isReadForCaching ? ref _owner._singleBufferReceiveEventArgs : ref _owner._singleBufferSendEventArgs, this, null) != null)
            {
                Dispose();
            }
        }
References System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._cancellationToken, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._continuation, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._isReadForCaching, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._owner, System.Net.Sockets.Socket._singleBufferReceiveEventArgs, System.Net.Sockets.Socket._singleBufferSendEventArgs, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._token, System.Threading.Interlocked.CompareExchange(), and System.Net.Sockets.SocketAsyncEventArgs.Dispose().
Referenced by System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.AcceptAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.DisconnectAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveFromAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveMessageFromAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendPacketsAsync(), and System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendToAsync().