Terraria: System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult
GetResult() [3/5]
Socket IValueTaskSource< Socket >. System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult (short token) inline private
Implements System.Threading.Tasks.Sources.IValueTaskSource< out TResult >.
Definition at line 421 of file Socket.cs.
        {
            if (token != _token)
            {
                ThrowIncorrectTokenException();
            }
            SocketError socketError = base.SocketError;
            Socket acceptSocket = base.AcceptSocket;
            CancellationToken cancellationToken = _cancellationToken;
            Release();
            if (socketError != 0)
            {
                ThrowException(socketError, cancellationToken);
            }
            return acceptSocket;
        }
References System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._cancellationToken, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._token, System.cancellationToken, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.Release(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(), and System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowIncorrectTokenException().