Terraria: System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation
InvokeContinuation()
void System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation (Action< object > continuation, object state, bool forceAsync, bool requiresExecutionContextFlow) inline private
Definition at line 353 of file Socket.cs.
        {
            object scheduler = _scheduler;
            _scheduler = null;
            if (scheduler != null)
            {
                if (scheduler is SynchronizationContext synchronizationContext)
                {
                    synchronizationContext.Post(delegate(object s)
                    {
                        (Action<object>, object) tuple = ((Action<object>, object))s;
                        tuple.Item1(tuple.Item2);
                    }, (continuation, state));
                }
                else
                {
                    Task.Factory.StartNew(continuation, state, CancellationToken.None, TaskCreationOptions.DenyChildAttach, (TaskScheduler)scheduler);
                }
            }
            else if (forceAsync)
            {
                if (requiresExecutionContextFlow)
                {
                    ThreadPool.QueueUserWorkItem(continuation, state, preferLocal: true);
                }
                else
                {
                    ThreadPool.UnsafeQueueUserWorkItem(continuation, state, preferLocal: true);
                }
            }
            else
            {
                continuation(state);
            }
        }
References System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._scheduler, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.CancellationToken.None, System.Threading.ThreadPool.QueueUserWorkItem(), System.s, System.scheduler, System.state, and System.Threading.ThreadPool.UnsafeQueueUserWorkItem().
Referenced by System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(), and System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted().