Terraria: System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted
OnCompleted() [1/7]
void System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted (Action< object > continuation, object state, short token, ValueTaskSourceOnCompletedFlags flags) inline
Definition at line 312 of file Socket.cs.
        {
            if (token != _token)
            {
                ThrowIncorrectTokenException();
            }
            if ((flags & ValueTaskSourceOnCompletedFlags.FlowExecutionContext) != 0)
            {
                _executionContext = ExecutionContext.Capture();
            }
            if ((flags & ValueTaskSourceOnCompletedFlags.UseSchedulingContext) != 0)
            {
                SynchronizationContext current = SynchronizationContext.Current;
                if (current != null && current.GetType() != typeof(SynchronizationContext))
                {
                    _scheduler = current;
                }
                else
                {
                    TaskScheduler current2 = TaskScheduler.Current;
                    if (current2 != TaskScheduler.Default)
                    {
                        _scheduler = current2;
                    }
                }
            }
            base.UserToken = state;
            Action<object> action = Interlocked.CompareExchange(ref _continuation, continuation, null);
            if ((object)action == s_completedSentinel)
            {
                bool requiresExecutionContextFlow = _executionContext != null;
                _executionContext = null;
                base.UserToken = null;
                InvokeContinuation(continuation, state, forceAsync: true, requiresExecutionContextFlow);
            }
            else if (action != null)
            {
                ThrowMultipleContinuationsException();
            }
        }
References System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._continuation, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._executionContext, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._scheduler, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._token, System.action, System.Threading.ExecutionContext.Capture(), System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.TaskScheduler.Current, System.Threading.SynchronizationContext.Current, System.Threading.Tasks.TaskScheduler.Default, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.s_completedSentinel, System.state, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowIncorrectTokenException(), and System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowMultipleContinuationsException().