Terraria: System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException
CreateException()
Exception System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException (SocketError error, bool forAsyncThrow = true) inline private
Definition at line 503 of file Socket.cs.
        {
            Exception ex = (Exception)(object)new SocketException((int)error);
            if (forAsyncThrow)
            {
                ex = ExceptionDispatchInfo.SetCurrentStackTrace(ex);
            }
            if (!WrapExceptionsForNetworkStream)
            {
                return ex;
            }
            return new IOException(System.SR.Format(_isReadForCaching ? System.SR.net_io_readfailure : System.SR.net_io_writefailure, ex.Message), ex);
        }
References System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._isReadForCaching, System.SR.Format(), System.SR.net_io_readfailure, System.SR.net_io_writefailure, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), and System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.WrapExceptionsForNetworkStream.
Referenced by System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.AcceptAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.DisconnectAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveFromAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveMessageFromAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendPacketsAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendToAsync(), and System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException().