Terraria: System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted
OnCompleted() [7/7]
override void System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted (SocketAsyncEventArgs _) inline protected virtual
Reimplemented from System.Net.Sockets.SocketAsyncEventArgs.
Definition at line 86 of file Socket.cs.
        {
            Action<object> action = _continuation;
            if (action == null && (action = Interlocked.CompareExchange(ref _continuation, s_completedSentinel, null)) == null)
            {
                return;
            }
            object userToken = base.UserToken;
            base.UserToken = null;
            _continuation = s_completedSentinel;
            ExecutionContext executionContext = _executionContext;
            if (executionContext == null)
            {
                InvokeContinuation(action, userToken, forceAsync: false, requiresExecutionContextFlow: false);
                return;
            }
            _executionContext = null;
            ExecutionContext.Run(executionContext, delegate(object runState)
            {
                (AwaitableSocketAsyncEventArgs, Action<object>, object) tuple = ((AwaitableSocketAsyncEventArgs, Action<object>, object))runState;
                tuple.Item1.InvokeContinuation(tuple.Item2, tuple.Item3, forceAsync: false, requiresExecutionContextFlow: false);
            }, (this, action, userToken));
        }
References System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.AwaitableSocketAsyncEventArgs(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._continuation, System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs._executionContext, System.action, System.Threading.Interlocked.CompareExchange(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(), System.Threading.ExecutionContext.Run(), and System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.s_completedSentinel.