Terraria: System.Data.SimpleType.LoadTypeValues
LoadTypeValues()
void System.Data.SimpleType.LoadTypeValues (XmlSchemaSimpleType node) inline package
Definition at line 93 of file SimpleType.cs.
    {
        if (node.Content is XmlSchemaSimpleTypeList || node.Content is XmlSchemaSimpleTypeUnion)
        {
            throw ExceptionBuilder.SimpleTypeNotSupported();
        }
        if (node.Content is XmlSchemaSimpleTypeRestriction)
        {
            XmlSchemaSimpleTypeRestriction xmlSchemaSimpleTypeRestriction = (XmlSchemaSimpleTypeRestriction)node.Content;
            if (node.BaseXmlSchemaType is XmlSchemaSimpleType xmlSchemaSimpleType && xmlSchemaSimpleType.QualifiedName.Namespace != "http://www.w3.org/2001/XMLSchema")
            {
                _baseSimpleType = new SimpleType(xmlSchemaSimpleType);
            }
            if (xmlSchemaSimpleTypeRestriction.BaseTypeName.Namespace == "http://www.w3.org/2001/XMLSchema")
            {
                _baseType = xmlSchemaSimpleTypeRestriction.BaseTypeName.Name;
            }
            else
            {
                _baseType = xmlSchemaSimpleTypeRestriction.BaseTypeName.ToString();
            }
            if (_baseSimpleType != null && _baseSimpleType.Name != null && _baseSimpleType.Name.Length > 0)
            {
                _xmlBaseType = _baseSimpleType.XmlBaseType;
            }
            else
            {
                _xmlBaseType = xmlSchemaSimpleTypeRestriction.BaseTypeName;
            }
            if (_baseType == null || _baseType.Length == 0)
            {
                _baseType = xmlSchemaSimpleTypeRestriction.BaseType.Name;
                _xmlBaseType = null;
            }
            if (_baseType == "NOTATION")
            {
                _baseType = "string";
            }
            foreach (XmlSchemaFacet facet in xmlSchemaSimpleTypeRestriction.Facets)
            {
                if (facet is XmlSchemaLengthFacet)
                {
                    _length = Convert.ToInt32(facet.Value, null);
                }
                if (facet is XmlSchemaMinLengthFacet)
                {
                    _minLength = Convert.ToInt32(facet.Value, null);
                }
                if (facet is XmlSchemaMaxLengthFacet)
                {
                    _maxLength = Convert.ToInt32(facet.Value, null);
                }
                if (facet is XmlSchemaPatternFacet)
                {
                    _pattern = facet.Value;
                }
                if (facet is XmlSchemaEnumerationFacet)
                {
                    _enumeration = ((!string.IsNullOrEmpty(_enumeration)) ? (_enumeration + " " + facet.Value) : facet.Value);
                }
                if (facet is XmlSchemaMinExclusiveFacet)
                {
                    _minExclusive = facet.Value;
                }
                if (facet is XmlSchemaMinInclusiveFacet)
                {
                    _minInclusive = facet.Value;
                }
                if (facet is XmlSchemaMaxExclusiveFacet)
                {
                    _maxExclusive = facet.Value;
                }
                if (facet is XmlSchemaMaxInclusiveFacet)
                {
                    _maxInclusive = facet.Value;
                }
            }
        }
        string msdataAttribute = XSDSchema.GetMsdataAttribute(node, "targetNamespace");
        if (msdataAttribute != null)
        {
            _ns = msdataAttribute;
        }
    }
References System.Data.SimpleType.SimpleType(), System.Data.SimpleType._baseSimpleType, System.Data.SimpleType._baseType, System.Data.SimpleType._enumeration, System.Data.SimpleType._length, System.Data.SimpleType._maxExclusive, System.Data.SimpleType._maxInclusive, System.Data.SimpleType._maxLength, System.Data.SimpleType._minExclusive, System.Data.SimpleType._minInclusive, System.Data.SimpleType._minLength, System.Data.SimpleType._ns, System.Data.SimpleType._pattern, System.Data.SimpleType._xmlBaseType, System.Runtime.Serialization.Dictionary, System.Data.XSDSchema.GetMsdataAttribute(), System.Data.SimpleType.Name, System.Xml.XmlQualifiedName.Namespace, System.Xml.Schema.XmlSchemaType.QualifiedName, System.Data.ExceptionBuilder.SimpleTypeNotSupported(), System.Convert.ToInt32(), and System.Data.SimpleType.XmlBaseType.
Referenced by System.Data.SimpleType.SimpleType().