Terraria: UIImageWithBorder.DrawSelf
DrawSelf()
override void UIImageWithBorder.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIImage.
     {
         base.DrawSelf(spriteBatch);
         CalculatedStyle dimensions = GetDimensions();
         Texture2D texture2D = null;
         if (_borderTexture != null)
         {
             texture2D = _borderTexture.Value;
         }
         if (_nonReloadingBorderTexture != null)
         {
             texture2D = _nonReloadingBorderTexture;
         }
         if (ScaleToFit)
         {
             spriteBatch.Draw(texture2D, dimensions.ToRectangle(), Color);
             return;
         }
         Vector2 vector = texture2D.Size();
         Vector2 vector2 = dimensions.Position() + vector * (1f - ImageScale) / 2f + vector * NormalizedOrigin;
         if (RemoveFloatingPointsFromDrawPosition)
         {
             vector2 = vector2.Floor();
         }
         spriteBatch.Draw(texture2D, vector2, null, Color, Rotation, vector * NormalizedOrigin, ImageScale, SpriteEffects.None, 0f);
     }
References _borderTexture, _nonReloadingBorderTexture, UIImage.Color, UIElement.GetDimensions(), UIImage.ImageScale, UIImage.NormalizedOrigin, CalculatedStyle.Position(), UIImage.RemoveFloatingPointsFromDrawPosition, UIImage.Rotation, UIImage.ScaleToFit, CalculatedStyle.ToRectangle(), and Asset< T >.Value.