Terraria: System.Xml.Xsl.XsltOld.NavigatorOutput.RecordDone
RecordDone()
Processor.OutputResult System.Xml.Xsl.XsltOld.NavigatorOutput.RecordDone (RecordBuilder record) inline
Implements System.Xml.Xsl.XsltOld.IRecordOutput.
Definition at line 21 of file NavigatorOutput.cs.
    {
        BuilderInfo mainNode = record.MainNode;
        _documentIndex++;
        switch (mainNode.NodeType)
        {
        case XmlNodeType.Element:
        {
            _wr.WriteStartElement(mainNode.Prefix, mainNode.LocalName, mainNode.NamespaceURI);
            for (int i = 0; i < record.AttributeCount; i++)
            {
                _documentIndex++;
                BuilderInfo builderInfo = (BuilderInfo)record.AttributeList[i];
                if (builderInfo.NamespaceURI == "http://www.w3.org/2000/xmlns/")
                {
                    if (builderInfo.Prefix.Length == 0)
                    {
                        _wr.WriteNamespaceDeclaration(string.Empty, builderInfo.Value);
                    }
                    else
                    {
                        _wr.WriteNamespaceDeclaration(builderInfo.LocalName, builderInfo.Value);
                    }
                }
                else
                {
                    _wr.WriteAttributeString(builderInfo.Prefix, builderInfo.LocalName, builderInfo.NamespaceURI, builderInfo.Value);
                }
            }
            _wr.StartElementContent();
            if (mainNode.IsEmptyTag)
            {
                _wr.WriteEndElement(mainNode.Prefix, mainNode.LocalName, mainNode.NamespaceURI);
            }
            break;
        }
        case XmlNodeType.Text:
            _wr.WriteString(mainNode.Value);
            break;
        case XmlNodeType.SignificantWhitespace:
            _wr.WriteString(mainNode.Value);
            break;
        case XmlNodeType.ProcessingInstruction:
            _wr.WriteProcessingInstruction(mainNode.LocalName, mainNode.Value);
            break;
        case XmlNodeType.Comment:
            _wr.WriteComment(mainNode.Value);
            break;
        case XmlNodeType.EndElement:
            _wr.WriteEndElement(mainNode.Prefix, mainNode.LocalName, mainNode.NamespaceURI);
            break;
        }
        record.Reset();
        return Processor.OutputResult.Continue;
    }
References System.Xml.Xsl.XsltOld.NavigatorOutput._documentIndex, System.Xml.Xsl.XsltOld.NavigatorOutput._wr, System.Xml.Dictionary, System.Xml.XmlRawWriter.StartElementContent(), System.Empty.Value, System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteComment(), System.Xml.XmlRawWriter.WriteEndElement(), System.Xml.XmlRawWriter.WriteNamespaceDeclaration(), System.Xml.XmlWriter.WriteProcessingInstruction(), System.Xml.XmlWriter.WriteStartElement(), and System.Xml.XmlWriter.WriteString().