Terraria: System.Security.Claims.ClaimsPrincipal.HasClaim
HasClaim() [1/2]
virtual bool System.Security.Claims.ClaimsPrincipal.HasClaim (Predicate< Claim > match) inline virtual inherited
Definition at line 314 of file ClaimsPrincipal.cs.
    {
        if (match == null)
        {
            throw new ArgumentNullException("match");
        }
        for (int i = 0; i < _identities.Count; i++)
        {
            if (_identities[i] != null && _identities[i].HasClaim(match))
            {
                return true;
            }
        }
        return false;
    }
References System.Security.Claims.ClaimsPrincipal._identities, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Security.Claims.ClaimsPrincipal.HasClaim(), and System.match.
Referenced by System.Security.Claims.ClaimsPrincipal.HasClaim(), System.Security.Claims.ClaimsPrincipal.HasClaim(), and System.Security.Claims.ClaimsPrincipal.IsInRole().