Terraria: System.Net.NetworkInformation.NetworkChange.AvailabilityChangeListener.Start
Start()
static void System.Net.NetworkInformation.NetworkChange.AvailabilityChangeListener.Start (NetworkAvailabilityChangedEventHandler caller) inline static package
Definition at line 52 of file NetworkChange.cs.
        {
            if (caller == null)
            {
                return;
            }
            lock (s_globalLock)
            {
                if (s_availabilityChangedSubscribers.Count == 0)
                {
                    s_isAvailable = NetworkInterface.GetIsNetworkAvailable();
                    AddressChangeListener.UnsafeStart(s_addressChange);
                }
                s_availabilityChangedSubscribers.TryAdd(caller, ExecutionContext.Capture());
            }
        }
References System.Threading.ExecutionContext.Capture(), System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable(), System.Net.NetworkInformation.NetworkChange.AvailabilityChangeListener.s_addressChange, System.Net.NetworkInformation.NetworkChange.s_availabilityChangedSubscribers, System.Net.NetworkInformation.NetworkChange.s_globalLock, System.Net.NetworkInformation.NetworkChange.AvailabilityChangeListener.s_isAvailable, and System.Net.NetworkInformation.NetworkChange.AddressChangeListener.UnsafeStart().