Terraria: System.Net.NetworkInformation.NetworkChange.AvailabilityChangeListener.ChangedAddress
ChangedAddress()
static void System.Net.NetworkInformation.NetworkChange.AvailabilityChangeListener.ChangedAddress (object sender, EventArgs eventArgs) inline static private
Definition at line 15 of file NetworkChange.cs.
        {
            Dictionary<NetworkAvailabilityChangedEventHandler, ExecutionContext> dictionary = null;
            lock (s_globalLock)
            {
                bool flag = SystemNetworkInterface.InternalGetIsNetworkAvailable();
                if (flag != s_isAvailable)
                {
                    s_isAvailable = flag;
                    if (s_availabilityChangedSubscribers.Count > 0)
                    {
                        dictionary = new Dictionary<NetworkAvailabilityChangedEventHandler, ExecutionContext>(s_availabilityChangedSubscribers);
                    }
                }
            }
            if (dictionary == null)
            {
                return;
            }
            bool flag2 = s_isAvailable;
            NetworkAvailabilityEventArgs e = (flag2 ? s_availableEventArgs : s_notAvailableEventArgs);
            ContextCallback callback = (flag2 ? s_runHandlerAvailable : s_runHandlerNotAvailable);
            foreach (KeyValuePair<NetworkAvailabilityChangedEventHandler, ExecutionContext> item in dictionary)
            {
                NetworkAvailabilityChangedEventHandler key = item.Key;
                ExecutionContext value = item.Value;
                if (value == null)
                {
                    key(null, e);
                }
                else
                {
                    ExecutionContext.Run(value, callback, key);
                }
            }
        }
References System.Threading.ContextCallback(), System.dictionary, System.Net.NetworkInformation.SystemNetworkInterface.InternalGetIsNetworkAvailable(), System.item, System.key, System.Net.NetworkInformation.NetworkAvailabilityChangedEventHandler(), System.Threading.ExecutionContext.Run(), System.Net.NetworkInformation.NetworkChange.s_availabilityChangedSubscribers, System.Net.NetworkInformation.NetworkChange.s_availableEventArgs, System.Net.NetworkInformation.NetworkChange.s_globalLock, System.Net.NetworkInformation.NetworkChange.AvailabilityChangeListener.s_isAvailable, System.Net.NetworkInformation.NetworkChange.s_notAvailableEventArgs, System.Net.NetworkInformation.NetworkChange.s_runHandlerAvailable, System.Net.NetworkInformation.NetworkChange.s_runHandlerNotAvailable, and System.value.