Terraria: System.Security.Claims.ClaimsPrincipal._identities
_identities
readonly List<ClaimsIdentity> System.Security.Claims.ClaimsPrincipal._identities = new List<ClaimsIdentity>() private inherited
Definition at line 18 of file ClaimsPrincipal.cs.
Referenced by System.Security.Claims.ClaimsPrincipal.ClaimsPrincipal(), System.Security.Claims.ClaimsPrincipal.ClaimsPrincipal(), System.Security.Claims.ClaimsPrincipal.ClaimsPrincipal(), System.Security.Claims.ClaimsPrincipal.ClaimsPrincipal(), System.Security.Claims.ClaimsPrincipal.AddIdentities(), System.Security.Claims.ClaimsPrincipal.AddIdentity(), System.Security.Claims.ClaimsPrincipal.FindFirst(), System.Security.Claims.ClaimsPrincipal.HasClaim(), System.Security.Claims.ClaimsPrincipal.HasClaim(), System.Security.Claims.ClaimsPrincipal.IsInRole(), System.Security.Claims.ClaimsPrincipal.OnSerializingMethod(), and System.Security.Claims.ClaimsPrincipal.WriteTo().