Terraria: RockPaperScissorsCommand.ProcessOutgoingMessage
ProcessOutgoingMessage()
void RockPaperScissorsCommand.ProcessOutgoingMessage (ChatMessage message) inline
Implements IChatCommand.
     {
         int num = Main.rand.NextFromList<int>(37, 38, 36);
         if (Main.netMode == 0)
         {
             EmoteBubble.NewBubble(num, new WorldUIAnchor(Main.LocalPlayer), 360);
             EmoteBubble.CheckForNPCsToReactToEmoteBubble(num, Main.LocalPlayer);
         }
         else
         {
             NetMessage.SendData(120, -1, -1, null, Main.myPlayer, num);
         }
         message.Consume();
     }
References EmoteBubble.CheckForNPCsToReactToEmoteBubble(), ChatMessage.Consume(), Main.LocalPlayer, Main.myPlayer, Main.netMode, EmoteBubble.NewBubble(), Main.rand, and NetMessage.SendData().