Terraria: System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InternalSerialize
InternalSerialize()
void System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InternalSerialize (MethodInfo methodInfo, LocalBuilder memberValue, Type memberType, bool writeXsiType) inline private
Definition at line 614 of file XmlFormatWriterGenerator.cs.
        {
            _ilg.Load(_contextArg);
            _ilg.Load(_xmlWriterArg);
            _ilg.Load(memberValue);
            _ilg.ConvertValue(memberValue.LocalType, Globals.TypeOfObject);
            _ilg.Call(null, XmlFormatGeneratorStatics.IsMemberTypeSameAsMemberValue, memberValue, memberType);
            _ilg.Load(writeXsiType);
            _ilg.Load(DataContract.GetId(memberType.TypeHandle));
            _ilg.Ldtoken(memberType);
            _ilg.Call(methodInfo);
        }
References System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.DataContract.GetId(), System.Runtime.Serialization.XmlFormatGeneratorStatics.IsMemberTypeSameAsMemberValue, System.Runtime.Serialization.CodeGenerator.Ldtoken(), System.Runtime.Serialization.CodeGenerator.Load(), and System.Runtime.Serialization.Globals.TypeOfObject.
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().