Terraria: System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter
GenerateCollectionWriter()
XmlFormatCollectionWriterDelegate System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter (CollectionDataContract collectionContract) inline package
Definition at line 74 of file XmlFormatWriterGenerator.cs.
        {
            if (DataContractSerializer.Option == SerializationOption.ReflectionOnly)
            {
                return CreateReflectionXmlFormatCollectionWriterDelegate();
            }
            _ilg = new CodeGenerator();
            bool flag = collectionContract.RequiresMemberAccessForWrite(null);
            try
            {
                _ilg.BeginMethod("Write" + collectionContract.StableName.Name + "ToXml", Globals.TypeOfXmlFormatCollectionWriterDelegate, flag);
            }
            catch (SecurityException securityException)
            {
                if (!flag)
                {
                    throw;
                }
                collectionContract.RequiresMemberAccessForWrite(securityException);
            }
            InitArgs(collectionContract.UnderlyingType);
            WriteCollection(collectionContract);
            return (XmlFormatCollectionWriterDelegate)_ilg.EndMethod();
        }
References System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.BeginMethod(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.CreateReflectionXmlFormatCollectionWriterDelegate(), System.Runtime.Serialization.CodeGenerator.EndMethod(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.DataContractSerializer.Option, System.Runtime.Serialization.Globals.TypeOfXmlFormatCollectionWriterDelegate, and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection().
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.GenerateCollectionWriter().