Terraria: System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteClass
WriteClass()
void System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteClass (ClassDataContract classContract) inline private
Definition at line 162 of file XmlFormatWriterGenerator.cs.
        {
            InvokeOnSerializing(classContract);
            if (classContract.IsISerializable)
            {
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.WriteISerializableMethod, _xmlWriterArg, _objectLocal);
            }
            else
            {
                if (classContract.ContractNamespaces.Length > 1)
                {
                    _contractNamespacesLocal = _ilg.DeclareLocal(typeof(XmlDictionaryString[]), "contractNamespaces");
                    _ilg.Load(_dataContractArg);
                    _ilg.LoadMember(XmlFormatGeneratorStatics.ContractNamespacesField);
                    _ilg.Store(_contractNamespacesLocal);
                }
                _memberNamesLocal = _ilg.DeclareLocal(typeof(XmlDictionaryString[]), "memberNames");
                _ilg.Load(_dataContractArg);
                _ilg.LoadMember(XmlFormatGeneratorStatics.MemberNamesField);
                _ilg.Store(_memberNamesLocal);
                for (int i = 0; i < classContract.ChildElementNamespaces.Length; i++)
                {
                    if (classContract.ChildElementNamespaces[i] != null)
                    {
                        _childElementNamespacesLocal = _ilg.DeclareLocal(typeof(XmlDictionaryString[]), "childElementNamespaces");
                        _ilg.Load(_dataContractArg);
                        _ilg.LoadMember(XmlFormatGeneratorStatics.ChildElementNamespacesProperty);
                        _ilg.Store(_childElementNamespacesLocal);
                    }
                }
                if (classContract.HasExtensionData)
                {
                    LocalBuilder localBuilder = _ilg.DeclareLocal(Globals.TypeOfExtensionDataObject, "extensionData");
                    _ilg.Load(_objectLocal);
                    _ilg.ConvertValue(_objectLocal.LocalType, Globals.TypeOfIExtensibleDataObject);
                    _ilg.LoadMember(XmlFormatGeneratorStatics.ExtensionDataProperty);
                    _ilg.Store(localBuilder);
                    _ilg.Call(_contextArg, XmlFormatGeneratorStatics.WriteExtensionDataMethod, _xmlWriterArg, localBuilder, -1);
                    WriteMembers(classContract, localBuilder, classContract);
                }
                else
                {
                    WriteMembers(classContract, null, classContract);
                }
            }
            InvokeOnSerialized(classContract);
        }
References System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._childElementNamespacesLocal, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._contractNamespacesLocal, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._dataContractArg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._memberNamesLocal, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.XmlFormatGeneratorStatics.ChildElementNamespacesProperty, System.Runtime.Serialization.XmlFormatGeneratorStatics.ContractNamespacesField, System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlFormatGeneratorStatics.ExtensionDataProperty, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InvokeOnSerialized(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InvokeOnSerializing(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Reflection.Emit.LocalBuilder.LocalType, System.Runtime.Serialization.XmlFormatGeneratorStatics.MemberNamesField, System.Runtime.Serialization.CodeGenerator.Store(), System.Runtime.Serialization.Globals.TypeOfExtensionDataObject, System.Runtime.Serialization.Globals.TypeOfIExtensibleDataObject, System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteExtensionDataMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteISerializableMethod, and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers().
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateClassWriter().