Terraria: System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteStartElement
WriteStartElement()
void System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteStartElement (Type type, XmlDictionaryString ns, LocalBuilder namespaceLocal, LocalBuilder nameLocal, int nameIndex) inline private
Definition at line 669 of file XmlFormatWriterGenerator.cs.
        {
            bool flag = NeedsPrefix(type, ns);
            _ilg.Load(_xmlWriterArg);
            if (flag)
            {
                _ilg.Load("q");
            }
            if (nameLocal == null)
            {
                _ilg.LoadArrayElement(_memberNamesLocal, nameIndex);
            }
            else
            {
                _ilg.Load(nameLocal);
            }
            _ilg.Load(namespaceLocal);
            _ilg.Call(flag ? XmlFormatGeneratorStatics.WriteStartElementMethod3 : XmlFormatGeneratorStatics.WriteStartElementMethod2);
        }
References System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._memberNamesLocal, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadArrayElement(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.NeedsPrefix(), System.type, System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteStartElementMethod2, and System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteStartElementMethod3.
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers().