Terraria: System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitiveArray
TryWritePrimitiveArray()
bool System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitiveArray (Type type, Type itemType, LocalBuilder value, LocalBuilder itemName, LocalBuilder itemNamespace) inline private
Definition at line 499 of file XmlFormatWriterGenerator.cs.
        {
            PrimitiveDataContract primitiveDataContract = PrimitiveDataContract.GetPrimitiveDataContract(itemType);
            if (primitiveDataContract == null)
            {
                return false;
            }
            string text = null;
            switch (itemType.GetTypeCode())
            {
            case TypeCode.Boolean:
                text = "WriteBooleanArray";
                break;
            case TypeCode.DateTime:
                text = "WriteDateTimeArray";
                break;
            case TypeCode.Decimal:
                text = "WriteDecimalArray";
                break;
            case TypeCode.Int32:
                text = "WriteInt32Array";
                break;
            case TypeCode.Int64:
                text = "WriteInt64Array";
                break;
            case TypeCode.Single:
                text = "WriteSingleArray";
                break;
            case TypeCode.Double:
                text = "WriteDoubleArray";
                break;
            }
            if (text != null)
            {
                _ilg.Load(_xmlWriterArg);
                _ilg.Load(value);
                _ilg.Load(itemName);
                _ilg.Load(itemNamespace);
                _ilg.Call(typeof(XmlWriterDelegator).GetMethod(text, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[3]
                {
                    type,
                    typeof(XmlDictionaryString),
                    typeof(XmlDictionaryString)
                }));
                return true;
            }
            return false;
        }
References System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Runtime.Serialization.CodeGenerator.Load(), System.text, and System.value.
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection().