Terraria: System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue
WriteValue()
void System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue (LocalBuilder memberValue, bool writeXsiType) inline private
Definition at line 549 of file XmlFormatWriterGenerator.cs.
        {
            Type localType = memberValue.LocalType;
            bool flag = localType.IsGenericType && localType.GetGenericTypeDefinition() == Globals.TypeOfNullable;
            if (localType.IsValueType && !flag)
            {
                PrimitiveDataContract primitiveDataContract = PrimitiveDataContract.GetPrimitiveDataContract(localType);
                if (primitiveDataContract != null && !writeXsiType)
                {
                    _ilg.Call(_xmlWriterArg, primitiveDataContract.XmlFormatContentWriterMethod, memberValue);
                }
                else
                {
                    InternalSerialize(XmlFormatGeneratorStatics.InternalSerializeMethod, memberValue, localType, writeXsiType);
                }
                return;
            }
            if (flag)
            {
                memberValue = UnwrapNullableObject(memberValue);
                localType = memberValue.LocalType;
            }
            else
            {
                _ilg.Load(memberValue);
                _ilg.Load(null);
                _ilg.Ceq();
            }
            _ilg.If();
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.WriteNullMethod, _xmlWriterArg, localType, DataContract.IsTypeSerializable(localType));
            _ilg.Else();
            PrimitiveDataContract primitiveDataContract2 = PrimitiveDataContract.GetPrimitiveDataContract(localType);
            if (primitiveDataContract2 != null && primitiveDataContract2.UnderlyingType != Globals.TypeOfObject && !writeXsiType)
            {
                if (flag)
                {
                    _ilg.Call(_xmlWriterArg, primitiveDataContract2.XmlFormatContentWriterMethod, memberValue);
                }
                else
                {
                    _ilg.Call(_contextArg, primitiveDataContract2.XmlFormatContentWriterMethod, _xmlWriterArg, memberValue);
                }
            }
            else
            {
                if (localType == Globals.TypeOfObject || localType == Globals.TypeOfValueType || ((IList)Globals.TypeOfNullable.GetInterfaces()).Contains((object?)localType))
                {
                    _ilg.Load(memberValue);
                    _ilg.ConvertValue(memberValue.LocalType, Globals.TypeOfObject);
                    memberValue = _ilg.DeclareLocal(Globals.TypeOfObject, "unwrappedMemberValue");
                    localType = memberValue.LocalType;
                    _ilg.Stloc(memberValue);
                    _ilg.If(memberValue, Cmp.EqualTo, null);
                    _ilg.Call(_contextArg, XmlFormatGeneratorStatics.WriteNullMethod, _xmlWriterArg, localType, DataContract.IsTypeSerializable(localType));
                    _ilg.Else();
                }
                InternalSerialize(flag ? XmlFormatGeneratorStatics.InternalSerializeMethod : XmlFormatGeneratorStatics.InternalSerializeReferenceMethod, memberValue, localType, writeXsiType);
                if (localType == Globals.TypeOfObject)
                {
                    _ilg.EndIf();
                }
            }
            _ilg.EndIf();
        }
References System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Ceq(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Else(), System.Runtime.Serialization.CodeGenerator.EndIf(), System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.XmlFormatGeneratorStatics.InternalSerializeMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.InternalSerializeReferenceMethod, System.Runtime.Serialization.DataContract.IsTypeSerializable(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.Globals.TypeOfNullable, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.Globals.TypeOfValueType, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.UnwrapNullableObject(), and System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteNullMethod.
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers().