Terraria: System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitive
TryWritePrimitive()
bool System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitive (Type type, LocalBuilder value, MemberInfo memberInfo, LocalBuilder arrayItemIndex, LocalBuilder ns, LocalBuilder name, int nameIndex) inline private
Definition at line 456 of file XmlFormatWriterGenerator.cs.
        {
            PrimitiveDataContract primitiveDataContract = PrimitiveDataContract.GetPrimitiveDataContract(type);
            if (primitiveDataContract == null || primitiveDataContract.UnderlyingType == Globals.TypeOfObject)
            {
                return false;
            }
            if (type.IsValueType)
            {
                _ilg.Load(_xmlWriterArg);
            }
            else
            {
                _ilg.Load(_contextArg);
                _ilg.Load(_xmlWriterArg);
            }
            if (value != null)
            {
                _ilg.Load(value);
            }
            else if (memberInfo != null)
            {
                _ilg.LoadAddress(_objectLocal);
                _ilg.LoadMember(memberInfo);
            }
            else
            {
                _ilg.LoadArrayElement(_objectLocal, arrayItemIndex);
            }
            if (name != null)
            {
                _ilg.Load(name);
            }
            else
            {
                _ilg.LoadArrayElement(_memberNamesLocal, nameIndex);
            }
            _ilg.Load(ns);
            _ilg.Call(primitiveDataContract.XmlFormatWriterMethod);
            return true;
        }
References System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._memberNamesLocal, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.CodeGenerator.LoadArrayElement(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.type, System.Runtime.Serialization.Globals.TypeOfObject, and System.value.
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers().