Terraria: System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers
WriteMembers()
int System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers (ClassDataContract classContract, LocalBuilder extensionDataLocal, ClassDataContract derivedMostClassContract) inline private
Definition at line 211 of file XmlFormatWriterGenerator.cs.
        {
            int num = ((classContract.BaseContract != null) ? WriteMembers(classContract.BaseContract, extensionDataLocal, derivedMostClassContract) : 0);
            LocalBuilder localBuilder = _ilg.DeclareLocal(typeof(XmlDictionaryString), "ns");
            if (_contractNamespacesLocal == null)
            {
                _ilg.Load(_dataContractArg);
                _ilg.LoadMember(XmlFormatGeneratorStatics.NamespaceProperty);
            }
            else
            {
                _ilg.LoadArrayElement(_contractNamespacesLocal, _typeIndex - 1);
            }
            _ilg.Store(localBuilder);
            int count = classContract.Members.Count;
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.IncrementItemCountMethod, count);
            int num2 = 0;
            while (num2 < count)
            {
                DataMember dataMember = classContract.Members[num2];
                Type memberType = dataMember.MemberType;
                LocalBuilder localBuilder2 = null;
                _ilg.Load(_contextArg);
                _ilg.Call(dataMember.IsGetOnlyCollection ? XmlFormatGeneratorStatics.StoreIsGetOnlyCollectionMethod : XmlFormatGeneratorStatics.ResetIsGetOnlyCollectionMethod);
                if (!dataMember.EmitDefaultValue)
                {
                    localBuilder2 = LoadMemberValue(dataMember);
                    _ilg.IfNotDefaultValue(localBuilder2);
                }
                bool flag = CheckIfMemberHasConflict(dataMember, classContract, derivedMostClassContract);
                if (flag || !TryWritePrimitive(memberType, localBuilder2, dataMember.MemberInfo, null, localBuilder, null, num2 + _childElementIndex))
                {
                    WriteStartElement(memberType, classContract.Namespace, localBuilder, null, num2 + _childElementIndex);
                    if (classContract.ChildElementNamespaces[num2 + _childElementIndex] != null)
                    {
                        _ilg.Load(_xmlWriterArg);
                        _ilg.LoadArrayElement(_childElementNamespacesLocal, num2 + _childElementIndex);
                        _ilg.Call(XmlFormatGeneratorStatics.WriteNamespaceDeclMethod);
                    }
                    if (localBuilder2 == null)
                    {
                        localBuilder2 = LoadMemberValue(dataMember);
                    }
                    WriteValue(localBuilder2, flag);
                    WriteEndElement();
                }
                if (classContract.HasExtensionData)
                {
                    _ilg.Call(_contextArg, XmlFormatGeneratorStatics.WriteExtensionDataMethod, _xmlWriterArg, extensionDataLocal, num);
                }
                if (!dataMember.EmitDefaultValue)
                {
                    if (dataMember.IsRequired)
                    {
                        _ilg.Else();
                        _ilg.Call(null, XmlFormatGeneratorStatics.ThrowRequiredMemberMustBeEmittedMethod, dataMember.Name, classContract.UnderlyingType);
                    }
                    _ilg.EndIf();
                }
                num2++;
                num++;
            }
            _typeIndex++;
            _childElementIndex += count;
            return num;
        }
References System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._childElementIndex, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._childElementNamespacesLocal, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._contractNamespacesLocal, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._dataContractArg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._typeIndex, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.CheckIfMemberHasConflict(), System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Else(), System.Runtime.Serialization.CodeGenerator.EndIf(), System.Runtime.Serialization.CodeGenerator.IfNotDefaultValue(), System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementItemCountMethod, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadArrayElement(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.LoadMemberValue(), System.Runtime.Serialization.XmlFormatGeneratorStatics.NamespaceProperty, System.Runtime.Serialization.XmlFormatGeneratorStatics.ResetIsGetOnlyCollectionMethod, System.Runtime.Serialization.CodeGenerator.Store(), System.Runtime.Serialization.XmlFormatGeneratorStatics.StoreIsGetOnlyCollectionMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.ThrowRequiredMemberMustBeEmittedMethod, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteEndElement(), System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteExtensionDataMethod, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers(), System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteNamespaceDeclMethod, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteStartElement(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteClass(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers().