Terraria: System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.UnwrapNullableObject
UnwrapNullableObject()
LocalBuilder System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.UnwrapNullableObject (LocalBuilder memberValue) inline private
Definition at line 628 of file XmlFormatWriterGenerator.cs.
        {
            Type type = memberValue.LocalType;
            Label label = _ilg.DefineLabel();
            Label label2 = _ilg.DefineLabel();
            _ilg.Load(memberValue);
            while (type.IsGenericType && type.GetGenericTypeDefinition() == Globals.TypeOfNullable)
            {
                Type type2 = type.GetGenericArguments()[0];
                _ilg.Dup();
                _ilg.Call(XmlFormatGeneratorStatics.GetHasValueMethod.MakeGenericMethod(type2));
                _ilg.Brfalse(label);
                _ilg.Call(XmlFormatGeneratorStatics.GetNullableValueMethod.MakeGenericMethod(type2));
                type = type2;
            }
            memberValue = _ilg.DeclareLocal(type, "nullableUnwrappedMemberValue");
            _ilg.Stloc(memberValue);
            _ilg.Load(false);
            _ilg.Br(label2);
            _ilg.MarkLabel(label);
            _ilg.Pop();
            _ilg.Call(XmlFormatGeneratorStatics.GetDefaultValueMethod.MakeGenericMethod(type));
            _ilg.Stloc(memberValue);
            _ilg.Load(true);
            _ilg.MarkLabel(label2);
            return memberValue;
        }
References System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.Br(), System.Runtime.Serialization.CodeGenerator.Brfalse(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.CodeGenerator.DefineLabel(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Dup(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetDefaultValueMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetHasValueMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetNullableValueMethod, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.MarkLabel(), System.Runtime.Serialization.CodeGenerator.Pop(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.type, and System.Runtime.Serialization.Globals.TypeOfNullable.
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().