Terraria: System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection
WriteCollection()
void System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection (CollectionDataContract collectionContract) inline private
Definition at line 288 of file XmlFormatWriterGenerator.cs.
        {
            LocalBuilder localBuilder = _ilg.DeclareLocal(typeof(XmlDictionaryString), "itemNamespace");
            _ilg.Load(_dataContractArg);
            _ilg.LoadMember(XmlFormatGeneratorStatics.NamespaceProperty);
            _ilg.Store(localBuilder);
            LocalBuilder localBuilder2 = _ilg.DeclareLocal(typeof(XmlDictionaryString), "itemName");
            _ilg.Load(_dataContractArg);
            _ilg.LoadMember(XmlFormatGeneratorStatics.CollectionItemNameProperty);
            _ilg.Store(localBuilder2);
            if (collectionContract.ChildElementNamespace != null)
            {
                _ilg.Load(_xmlWriterArg);
                _ilg.Load(_dataContractArg);
                _ilg.LoadMember(XmlFormatGeneratorStatics.ChildElementNamespaceProperty);
                _ilg.Call(XmlFormatGeneratorStatics.WriteNamespaceDeclMethod);
            }
            if (collectionContract.Kind == CollectionKind.Array)
            {
                Type itemType = collectionContract.ItemType;
                LocalBuilder localBuilder3 = _ilg.DeclareLocal(Globals.TypeOfInt, "i");
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.IncrementArrayCountMethod, _xmlWriterArg, _objectLocal);
                if (!TryWritePrimitiveArray(collectionContract.UnderlyingType, itemType, _objectLocal, localBuilder2, localBuilder))
                {
                    _ilg.For(localBuilder3, 0, _objectLocal);
                    if (!TryWritePrimitive(itemType, null, null, localBuilder3, localBuilder, localBuilder2, 0))
                    {
                        WriteStartElement(itemType, collectionContract.Namespace, localBuilder, localBuilder2, 0);
                        _ilg.LoadArrayElement(_objectLocal, localBuilder3);
                        LocalBuilder localBuilder4 = _ilg.DeclareLocal(itemType, "memberValue");
                        _ilg.Stloc(localBuilder4);
                        WriteValue(localBuilder4, writeXsiType: false);
                        WriteEndElement();
                    }
                    _ilg.EndFor();
                }
                return;
            }
            MethodInfo methodInfo = null;
            switch (collectionContract.Kind)
            {
            case CollectionKind.Dictionary:
            case CollectionKind.List:
            case CollectionKind.Collection:
                methodInfo = XmlFormatGeneratorStatics.IncrementCollectionCountMethod;
                break;
            case CollectionKind.GenericList:
            case CollectionKind.GenericCollection:
                methodInfo = XmlFormatGeneratorStatics.IncrementCollectionCountGenericMethod.MakeGenericMethod(collectionContract.ItemType);
                break;
            case CollectionKind.GenericDictionary:
                methodInfo = XmlFormatGeneratorStatics.IncrementCollectionCountGenericMethod.MakeGenericMethod(Globals.TypeOfKeyValuePair.MakeGenericType(collectionContract.ItemType.GetGenericArguments()));
                break;
            }
            if (methodInfo != null)
            {
                _ilg.Call(_contextArg, methodInfo, _xmlWriterArg, _objectLocal);
            }
            bool flag = false;
            bool flag2 = false;
            Type type = null;
            Type[] typeArguments = null;
            if (collectionContract.Kind == CollectionKind.GenericDictionary)
            {
                flag2 = true;
                typeArguments = collectionContract.ItemType.GetGenericArguments();
                type = Globals.TypeOfGenericDictionaryEnumerator.MakeGenericType(typeArguments);
            }
            else if (collectionContract.Kind == CollectionKind.Dictionary)
            {
                flag = true;
                typeArguments = new Type[2]
                {
                    Globals.TypeOfObject,
                    Globals.TypeOfObject
                };
                type = Globals.TypeOfDictionaryEnumerator;
            }
            else
            {
                type = collectionContract.GetEnumeratorMethod.ReturnType;
            }
            MethodInfo methodInfo2 = type.GetMethod("MoveNext", BindingFlags.Instance | BindingFlags.Public, Type.EmptyTypes);
            MethodInfo methodInfo3 = type.GetMethod("get_Current", BindingFlags.Instance | BindingFlags.Public, Type.EmptyTypes);
            if (methodInfo2 == null || methodInfo3 == null)
            {
                if (type.IsInterface)
                {
                    if (methodInfo2 == null)
                    {
                        methodInfo2 = XmlFormatGeneratorStatics.MoveNextMethod;
                    }
                    if (methodInfo3 == null)
                    {
                        methodInfo3 = XmlFormatGeneratorStatics.GetCurrentMethod;
                    }
                }
                else
                {
                    Type interfaceType = Globals.TypeOfIEnumerator;
                    CollectionKind kind = collectionContract.Kind;
                    if (kind == CollectionKind.GenericDictionary || kind == CollectionKind.GenericCollection || kind == CollectionKind.GenericEnumerable)
                    {
                        Type[] interfaces = type.GetInterfaces();
                        Type[] array = interfaces;
                        foreach (Type type2 in array)
{
                            if (type2.IsGenericType && type2.GetGenericTypeDefinition() == Globals.TypeOfIEnumeratorGeneric && type2.GetGenericArguments()[0] == collectionContract.ItemType)
{
                                interfaceType = type2;
                                break;
                            }
                        }
                    }
                    if (methodInfo2 == null)
                    {
                        methodInfo2 = CollectionDataContract.GetTargetMethodWithName("MoveNext", type, interfaceType);
                    }
                    if (methodInfo3 == null)
                    {
                        methodInfo3 = CollectionDataContract.GetTargetMethodWithName("get_Current", type, interfaceType);
                    }
                }
            }
            Type returnType = methodInfo3.ReturnType;
            LocalBuilder localBuilder5 = _ilg.DeclareLocal(returnType, "currentValue");
            LocalBuilder localBuilder6 = _ilg.DeclareLocal(type, "enumerator");
            _ilg.Call(_objectLocal, collectionContract.GetEnumeratorMethod);
            if (flag)
            {
                _ilg.ConvertValue(collectionContract.GetEnumeratorMethod.ReturnType, Globals.TypeOfIDictionaryEnumerator);
                _ilg.New(XmlFormatGeneratorStatics.DictionaryEnumeratorCtor);
            }
            else if (flag2)
            {
                Type type3 = Globals.TypeOfIEnumeratorGeneric.MakeGenericType(Globals.TypeOfKeyValuePair.MakeGenericType(typeArguments));
                ConstructorInfo constructor = type.GetConstructor(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { type3 });
                _ilg.ConvertValue(collectionContract.GetEnumeratorMethod.ReturnType, type3);
                _ilg.New(constructor);
            }
            _ilg.Stloc(localBuilder6);
            _ilg.ForEach(localBuilder5, returnType, type, localBuilder6, methodInfo3);
            if (methodInfo == null)
            {
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.IncrementItemCountMethod, 1);
            }
            if (!TryWritePrimitive(returnType, localBuilder5, null, null, localBuilder, localBuilder2, 0))
            {
                WriteStartElement(returnType, collectionContract.Namespace, localBuilder, localBuilder2, 0);
                if (flag2 || flag)
                {
                    _ilg.Call(_dataContractArg, XmlFormatGeneratorStatics.GetItemContractMethod);
                    _ilg.Load(_xmlWriterArg);
                    _ilg.Load(localBuilder5);
                    _ilg.ConvertValue(localBuilder5.LocalType, Globals.TypeOfObject);
                    _ilg.Load(_contextArg);
                    _ilg.Call(XmlFormatGeneratorStatics.WriteXmlValueMethod);
                }
                else
                {
                    WriteValue(localBuilder5, writeXsiType: false);
                }
                WriteEndElement();
            }
            _ilg.EndForEach(methodInfo2);
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._dataContractArg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.array, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.XmlFormatGeneratorStatics.ChildElementNamespaceProperty, System.Runtime.Serialization.XmlFormatGeneratorStatics.CollectionItemNameProperty, System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlFormatGeneratorStatics.DictionaryEnumeratorCtor, System.Type.EmptyTypes, System.Runtime.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.EndForEach(), System.Runtime.Serialization.CodeGenerator.For(), System.Runtime.Serialization.CodeGenerator.ForEach(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetCurrentMethod, System.Type.GetInterfaces(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetItemContractMethod, System.Runtime.Serialization.CollectionDataContract.GetTargetMethodWithName(), System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementArrayCountMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementCollectionCountGenericMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementCollectionCountMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementItemCountMethod, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadArrayElement(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Runtime.Serialization.XmlFormatGeneratorStatics.MoveNextMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.NamespaceProperty, System.Runtime.Serialization.CodeGenerator.New(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.CodeGenerator.Store(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitiveArray(), System.type, System.Runtime.Serialization.Globals.TypeOfDictionaryEnumerator, System.Runtime.Serialization.Globals.TypeOfGenericDictionaryEnumerator, System.Runtime.Serialization.Globals.TypeOfIDictionaryEnumerator, System.Runtime.Serialization.Globals.TypeOfIEnumerator, System.Runtime.Serialization.Globals.TypeOfIEnumeratorGeneric, System.Runtime.Serialization.Globals.TypeOfInt, System.Runtime.Serialization.Globals.TypeOfKeyValuePair, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteEndElement(), System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteNamespaceDeclMethod, System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteStartElement(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue(), and System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteXmlValueMethod.
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter().