Terraria: System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateClassWriter
GenerateClassWriter()
XmlFormatClassWriterDelegate System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateClassWriter (ClassDataContract classContract) inline package
Definition at line 42 of file XmlFormatWriterGenerator.cs.
        {
            if (DataContractSerializer.Option == SerializationOption.ReflectionOnly)
            {
                return CreateReflectionXmlFormatClassWriterDelegate();
            }
            _ilg = new CodeGenerator();
            bool flag = classContract.RequiresMemberAccessForWrite(null);
            try
            {
                _ilg.BeginMethod("Write" + classContract.StableName.Name + "ToXml", Globals.TypeOfXmlFormatClassWriterDelegate, flag);
            }
            catch (SecurityException securityException)
            {
                if (!flag)
                {
                    throw;
                }
                classContract.RequiresMemberAccessForWrite(securityException);
            }
            InitArgs(classContract.UnderlyingType);
            WriteClass(classContract);
            return (XmlFormatClassWriterDelegate)_ilg.EndMethod();
        }
References System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.BeginMethod(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.CreateReflectionXmlFormatClassWriterDelegate(), System.Runtime.Serialization.CodeGenerator.EndMethod(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.DataContractSerializer.Option, System.Runtime.Serialization.Globals.TypeOfXmlFormatClassWriterDelegate, and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteClass().
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.GenerateClassWriter().