Terraria: Modifiers.NotTouching.Apply
Apply()
override bool Modifiers.NotTouching.Apply (Point origin, int x, int y, params object[] args) inline virtual
Implements GenAction.
         {
             int num = (_useDiagonals ? 16 : 8);
             for (int i = 0; i < num; i += 2)
             {
                 Tile tile = GenBase._tiles[x + DIRECTIONS[i], y + DIRECTIONS[i + 1]];
                 if (!tile.active())
                 {
                     continue;
                 }
                 for (int j = 0; j < _tileIds.Length; j++)
                 {
                     if (tile.type == _tileIds[j])
                     {
                         return Fail();
                     }
                 }
             }
             return UnitApply(origin, x, y, args);
         }
References Modifiers.NotTouching._tileIds, GenBase._tiles, Modifiers.NotTouching._useDiagonals, Tile.active(), Modifiers.NotTouching.DIRECTIONS, GenAction.Fail(), Tile.type, and GenAction.UnitApply().