Terraria: UICharacterNameButton.SetContents
SetContents()
void UICharacterNameButton.SetContents (string name) inline
     {
         actualContents = name;
         if (string.IsNullOrEmpty(actualContents))
         {
             _text.TextColor = Color.Gray;
             _text.SetText(_textToShowWhenEmpty);
         }
         else
         {
             _text.TextColor = Color.White;
             _text.SetText(actualContents);
         }
         _text.Left = StyleDimension.FromPixels(_title.GetInnerDimensions().Width + DistanceFromTitleToOption);
     }
References _text, _textToShowWhenEmpty, _title, actualContents, Color, DistanceFromTitleToOption, StyleDimension.FromPixels(), UIElement.GetInnerDimensions(), UIElement.Left, UIText.SetText(), UIText.TextColor, and CalculatedStyle.Width.
Referenced by UICharacterNameButton(), UICharacterCreation.OnFinishedNaming(), UICharacterCreation.OnFinishedNamingAndCreating(), AWorkshopPublishInfoState< TPublishedObjectType >.UpdateImagePreview(), and UIWorldCreation.UpdateInputFields().