Terraria: UIBestiaryTest.AddBackAndForwardButtons
AddBackAndForwardButtons()
void UIBestiaryTest.AddBackAndForwardButtons (UIElement innerTopContainer) inline private
     {
         UIImageButton uIImageButton = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Back", (AssetRequestMode)1));
         uIImageButton.SetHoverImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Border", (AssetRequestMode)1));
         uIImageButton.SetVisibility(1f, 1f);
         uIImageButton.SetSnapPoint("BackPage", 0);
         _entryGrid.MakeButtonGoByOffset(uIImageButton, -1);
         innerTopContainer.Append(uIImageButton);
         UIImageButton uIImageButton2 = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Forward", (AssetRequestMode)1))
         {
             Left = new StyleDimension(uIImageButton.Width.Pixels + 1f, 0f)
         };
         uIImageButton2.SetHoverImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Border", (AssetRequestMode)1));
         uIImageButton2.SetVisibility(1f, 1f);
         uIImageButton2.SetSnapPoint("NextPage", 0);
         _entryGrid.MakeButtonGoByOffset(uIImageButton2, 1);
         innerTopContainer.Append(uIImageButton2);
         UIPanel uIPanel = new UIPanel
         {
             Left = new StyleDimension(uIImageButton.Width.Pixels + 1f + uIImageButton2.Width.Pixels + 3f, 0f),
             Width = new StyleDimension(135f, 0f),
             Height = new StyleDimension(0f, 1f),
             VAlign = 0.5f
         };
         uIPanel.BackgroundColor = new Color(35, 40, 83);
         uIPanel.BorderColor = new Color(35, 40, 83);
         uIPanel.SetPadding(0f);
         innerTopContainer.Append(uIPanel);
         UIText uIText = new UIText("9000-9999 (9001)", 0.8f)
         {
             HAlign = 0.5f,
             VAlign = 0.5f
         };
         uIPanel.Append(uIText);
         _indexesRangeText = uIText;
     }
References _entryGrid, _indexesRangeText, UIElement.Append(), Main.Assets, UIPanel.BackgroundColor, UIPanel.BorderColor, Color, UIElement.HAlign, UIElement.Height, UIElement.Left, UIBestiaryEntryGrid.MakeButtonGoByOffset(), StyleDimension.Pixels, UIImageButton.SetHoverImage(), UIElement.SetPadding(), UIElement.SetSnapPoint(), UIImageButton.SetVisibility(), UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().