Terraria: UIBestiaryTest.ShowStats_Completion
ShowStats_Completion()
void UIBestiaryTest.ShowStats_Completion (UIElement element) inline private
     {
         if (element.IsMouseHovering)
         {
             string completionPercentText = GetCompletionPercentText();
             Main.instance.MouseText(completionPercentText, 0, 0);
         }
     }
References GetCompletionPercentText(), Main.instance, UIElement.IsMouseHovering, and Main.MouseText().
Referenced by FillProgressBottomBar().