Terraria: UIBestiaryTest.OnSearchContentsChanged
OnSearchContentsChanged()
void UIBestiaryTest.OnSearchContentsChanged (string contents) inline private
     {
         _searchString = contents;
         _filterer.SetSearchFilter(contents);
         UpdateBestiaryContents();
     }
References _filterer, _searchString, EntryFilterer< T, U >.SetSearchFilter(), and UpdateBestiaryContents().
Referenced by AddSearchBar().