Terraria: UIBestiaryTest.OpenOrCloseSortingOptions
OpenOrCloseSortingOptions()
void UIBestiaryTest.OpenOrCloseSortingOptions (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         if (_sortingGrid.Parent != null)
         {
             CloseSortingGrid();
             return;
         }
         _bestiarySpace.RemoveChild(_sortingGrid);
         _bestiarySpace.RemoveChild(_filteringGrid);
         _bestiarySpace.Append(_sortingGrid);
     }
References _bestiarySpace, _filteringGrid, _sortingGrid, UIElement.Append(), CloseSortingGrid(), UIElement.Parent, and UIElement.RemoveChild().
Referenced by AddSortAndFilterButtons().