Terraria: UIBestiaryTest.BuildPage
BuildPage()
void UIBestiaryTest.BuildPage () inline private
     {
         RemoveAllChildren();
         int num = Utils.ToInt(value: true) * 100;
         UIElement uIElement = new UIElement();
         uIElement.Width.Set(0f, 0.875f);
         uIElement.MaxWidth.Set(800f + (float)num, 0f);
         uIElement.MinWidth.Set(600f + (float)num, 0f);
         uIElement.Top.Set(220f, 0f);
         uIElement.Height.Set(-220f, 1f);
         uIElement.HAlign = 0.5f;
         Append(uIElement);
         MakeExitButton(uIElement);
         UIPanel uIPanel = new UIPanel();
         uIPanel.Width.Set(0f, 1f);
         uIPanel.Height.Set(-90f, 1f);
         uIPanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
         uIElement.Append(uIPanel);
         uIPanel.PaddingTop -= 4f;
         uIPanel.PaddingBottom -= 4f;
         int num2 = 24;
         UIElement uIElement2 = new UIElement
         {
             Width = new StyleDimension(0f, 1f),
             Height = new StyleDimension(num2, 0f),
             VAlign = 0f
         };
         uIElement2.SetPadding(0f);
         uIPanel.Append(uIElement2);
         UIBestiaryEntryInfoPage uIBestiaryEntryInfoPage = new UIBestiaryEntryInfoPage
         {
             Height = new StyleDimension(12f, 1f),
             HAlign = 1f
         };
         AddSortAndFilterButtons(uIElement2, uIBestiaryEntryInfoPage);
         AddSearchBar(uIElement2, uIBestiaryEntryInfoPage);
         int num3 = 20;
         UIElement uIElement3 = new UIElement
         {
             Width = new StyleDimension(0f, 1f),
             Height = new StyleDimension(-num2 - 6 - num3, 1f),
             VAlign = 1f,
             Top = new StyleDimension(-num3, 0f)
         };
         uIElement3.SetPadding(0f);
         uIPanel.Append(uIElement3);
         UIElement uIElement4 = new UIElement
         {
             Width = new StyleDimension(0f, 1f),
             Height = new StyleDimension(20f, 0f),
             VAlign = 1f
         };
         uIPanel.Append(uIElement4);
         uIElement4.SetPadding(0f);
         FillProgressBottomBar(uIElement4);
         UIElement uIElement5 = new UIElement
         {
             Width = new StyleDimension(-12f - uIBestiaryEntryInfoPage.Width.Pixels, 1f),
             Height = new StyleDimension(-4f, 1f),
             VAlign = 1f
         };
         uIElement3.Append(uIElement5);
         uIElement5.SetPadding(0f);
         _bestiarySpace = uIElement5;
         UIBestiaryEntryGrid uIBestiaryEntryGrid = new UIBestiaryEntryGrid(_workingSetEntries, Click_SelectEntryButton);
         uIElement5.Append(uIBestiaryEntryGrid);
         _entryGrid = uIBestiaryEntryGrid;
         _entryGrid.OnGridContentsChanged += UpdateBestiaryGridRange;
         uIElement3.Append(uIBestiaryEntryInfoPage);
         _infoSpace = uIBestiaryEntryInfoPage;
         AddBackAndForwardButtons(uIElement2);
         _sortingGrid = new UIBestiarySortingOptionsGrid(_sorter);
         _sortingGrid.OnLeftClick += Click_CloseSortingGrid;
         _sortingGrid.OnClickingOption += UpdateBestiaryContents;
         _filteringGrid = new UIBestiaryFilteringOptionsGrid(_filterer);
         _filteringGrid.OnLeftClick += Click_CloseFilteringGrid;
         _filteringGrid.OnClickingOption += UpdateBestiaryContents;
         _filteringGrid.SetupAvailabilityTest(_originalEntriesList);
         _searchBar.SetContents(null, forced: true);
         UpdateBestiaryContents();
     }
References UIElement.UIElement(), _bestiarySpace, _entryGrid, _filterer, _filteringGrid, _infoSpace, _originalEntriesList, _searchBar, _sorter, _sortingGrid, _workingSetEntries, AddBackAndForwardButtons(), AddSearchBar(), AddSortAndFilterButtons(), UIElement.Append(), UIPanel.BackgroundColor, Click_CloseFilteringGrid(), Click_CloseSortingGrid(), Click_SelectEntryButton(), Color, FillProgressBottomBar(), UIElement.HAlign, UIElement.Height, MakeExitButton(), UIElement.MaxWidth, UIElement.MinWidth, UIBestiaryFilteringOptionsGrid.OnClickingOption, UIBestiarySortingOptionsGrid.OnClickingOption, UIBestiaryEntryGrid.OnGridContentsChanged, UIElement.OnLeftClick, UIElement.PaddingBottom, UIElement.PaddingTop, StyleDimension.Pixels, UIElement.RemoveAllChildren(), StyleDimension.Set(), UISearchBar.SetContents(), UIElement.SetPadding(), UIBestiaryFilteringOptionsGrid.SetupAvailabilityTest(), Utils.ToInt(), UIElement.Top, UpdateBestiaryContents(), UpdateBestiaryGridRange(), UIElement.VAlign, and UIElement.Width.
Referenced by UIBestiaryTest().