Terraria: UICharacterListItem.CloudButtonClick
CloudButtonClick()
void UICharacterListItem.CloudButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         if (_data.IsCloudSave)
         {
             _data.MoveToLocal();
         }
         else
         {
             _data.MoveToCloud();
         }
         ((UIImageButton)evt.Target).SetImage(_data.IsCloudSave ? _buttonCloudActiveTexture : _buttonCloudInactiveTexture);
         if (_data.IsCloudSave)
         {
             _buttonLabel.SetText(Language.GetTextValue("UI.MoveOffCloud"));
         }
         else
         {
             _buttonLabel.SetText(Language.GetTextValue("UI.MoveToCloud"));
         }
     }
References _buttonCloudActiveTexture, _buttonCloudInactiveTexture, _buttonLabel, _data, Language.GetTextValue(), FileData.IsCloudSave, PlayerFileData.MoveToCloud(), PlayerFileData.MoveToLocal(), UIText.SetText(), and UIEvent.Target.
Referenced by UICharacterListItem().