Terraria: System.ComponentModel.ReferenceConverter.GetStandardValues
GetStandardValues() [2/2]
override StandardValuesCollection System.ComponentModel.ReferenceConverter.GetStandardValues (ITypeDescriptorContext? context) inline virtual inherited
Reimplemented from System.ComponentModel.TypeConverter.
Definition at line 104 of file ReferenceConverter.cs.
    {
        List<object> list = null;
        if (context != null)
        {
            list = new List<object> { null };
            if (context.GetService(typeof(IReferenceService)) is IReferenceService referenceService)
            {
                object[] references = referenceService.GetReferences(_type);
                if (references != null)
                {
                    for (int i = 0; i < references.Length; i++)
                    {
                        if (IsValueAllowed(context, references[i]))
{
                            list.Add(references[i]);
                        }
                    }
                }
            }
            else
            {
                IContainer container = context.Container;
                if (container != null)
                {
                    ComponentCollection components = container.Components;
                    foreach (IComponent item in components)
                    {
                        if (item != null && _type != null && _type.IsInstanceOfType(item) && IsValueAllowed(context, item))
{
                            list.Add(item);
                        }
                    }
                }
            }
            list.Sort(new ReferenceComparer(this));
        }
        return new StandardValuesCollection(list);
    }
References System.ComponentModel.ReferenceConverter._type, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.ComponentModel.IContainer.Components, System.ComponentModel.ITypeDescriptorContext.Container, System.IServiceProvider.GetService(), System.Type.IsInstanceOfType(), System.ComponentModel.ReferenceConverter.IsValueAllowed(), System.item, and System.list.