Terraria: TEDisplayDoll.FitsDisplayDoll
FitsDisplayDoll()
static bool TEDisplayDoll.FitsDisplayDoll (Item item) inline static
     {
         if (item.maxStack > 1)
         {
             return false;
         }
         if (item.headSlot <= 0 && item.bodySlot <= 0 && item.legSlot <= 0)
         {
             return item.accessory;
         }
         return true;
     }
References Item.accessory, Item.bodySlot, Item.headSlot, Item.legSlot, and Item.maxStack.
Referenced by OverrideItemSlotHover(), OverrideItemSlotLeftClick(), and TryGetItemGamepadOverrideInstructions().