Terraria: TEDisplayDoll.Draw
Draw()
void TEDisplayDoll.Draw (int tileLeftX, int tileTopY) inline
     {
         Player dollPlayer = _dollPlayer;
         for (int i = 0; i < 8; i++)
         {
             dollPlayer.armor[i] = _items[i];
             dollPlayer.dye[i] = _dyes[i];
         }
         dollPlayer.direction = -1;
         dollPlayer.Male = true;
         Tile tileSafely = Framing.GetTileSafely(tileLeftX, tileTopY);
         if (tileSafely.frameX % 72 == 36)
         {
             dollPlayer.direction = 1;
         }
         if (tileSafely.frameX / 72 == 1)
         {
             dollPlayer.Male = false;
         }
         dollPlayer.isDisplayDollOrInanimate = true;
         dollPlayer.ResetEffects();
         dollPlayer.ResetVisibleAccessories();
         dollPlayer.UpdateDyes();
         dollPlayer.DisplayDollUpdate();
         dollPlayer.UpdateSocialShadow();
         dollPlayer.PlayerFrame();
         Vector2 position = new Vector2(tileLeftX + 1, tileTopY + 3) * 16f + new Vector2(-dollPlayer.width / 2, -dollPlayer.height - 6);
         dollPlayer.position = position;
         dollPlayer.isFullbright = tileSafely.fullbrightBlock();
         dollPlayer.skinDyePacked = PlayerDrawHelper.PackShader(tileSafely.color(), PlayerDrawHelper.ShaderConfiguration.TilePaintID);
         Main.PlayerRenderer.DrawPlayer(Main.Camera, dollPlayer, dollPlayer.position, 0f, dollPlayer.fullRotationOrigin);
     }
References _dollPlayer, _dyes, _items, Player.armor, Main.Camera, Tile.color(), Entity.direction, Player.DisplayDollUpdate(), IPlayerRenderer.DrawPlayer(), Player.dye, Tile.frameX, Tile.fullbrightBlock(), Player.fullRotationOrigin, Framing.GetTileSafely(), Entity.height, Player.isDisplayDollOrInanimate, Player.isFullbright, Player.Male, PlayerDrawHelper.PackShader(), Player.PlayerFrame(), Main.PlayerRenderer, Entity.position, Player.ResetEffects(), Player.ResetVisibleAccessories(), Player.skinDyePacked, Player.UpdateDyes(), Player.UpdateSocialShadow(), and Entity.width.