Terraria: System.Net.SSPIWrapper.EnumerateSecurityPackages
EnumerateSecurityPackages() [1/4]
static SecurityPackageInfoClass[] System.Net.SSPIWrapper.EnumerateSecurityPackages (ISSPIInterface secModule) inline static package
Definition at line 27 of file SSPIWrapper.cs.
    {
        if (secModule.SecurityPackages == null)
        {
            lock (secModule)
            {
                if (secModule.SecurityPackages == null)
                {
                    int pkgnum = 0;
                    SafeFreeContextBuffer pkgArray = null;
                    try
                    {
                        int num = secModule.EnumerateSecurityPackages(out pkgnum, out pkgArray);
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(null, $"arrayBase: {pkgArray}", "EnumerateSecurityPackages");
                        }
                        if (num != 0)
{
                            throw new Win32Exception(num);
                        }
                        SecurityPackageInfoClass[] array = new SecurityPackageInfoClass[pkgnum];
                        for (int i = 0; i < pkgnum; i++)
{
                            array[i] = new SecurityPackageInfoClass(pkgArray, i);
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Log.EnumerateSecurityPackages(array[i].Name);
                            }
                        }
                        secModule.SecurityPackages = array;
                    }
                    finally
                    {
                        pkgArray?.Dispose();
                    }
                }
            }
        }
        return secModule.SecurityPackages;
    }
References System.array, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.ISSPIInterface.EnumerateSecurityPackages(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Name, and System.Net.ISSPIInterface.SecurityPackages.