Terraria: Terraria.GameContent.DoorOpeningHelper.LookForDoorsToClose
LookForDoorsToClose()
void Terraria.GameContent.DoorOpeningHelper.LookForDoorsToClose (Player player) inline
    {
        PlayerInfoForClosingDoors playerInfoForClosingDoor = GetPlayerInfoForClosingDoor(player);
        for (int num = _ongoingOpenDoors.Count - 1; num >= 0; num--)
        {
            DoorOpenCloseTogglingInfo info = _ongoingOpenDoors[num];
            if (info.handler.TryCloseDoor(info, playerInfoForClosingDoor) != 0)
            {
                _ongoingOpenDoors.RemoveAt(num);
            }
        }
    }
References Terraria.GameContent.DoorOpeningHelper._ongoingOpenDoors, Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForClosingDoor(), Terraria.GameContent.DoorOpeningHelper.DoorOpenCloseTogglingInfo.handler, and Terraria.GameContent.DoorOpeningHelper.DoorAutoHandler.TryCloseDoor().
Referenced by Terraria.GameContent.DoorOpeningHelper.Update().