Terraria: System.Net.SSPIWrapper.EncryptDecryptHelper
EncryptDecryptHelper() [2/2]
static unsafe int System.Net.SSPIWrapper.EncryptDecryptHelper (OP op, System::Net::ISSPIInterface secModule, System::Net::Security::SafeDeleteContext context, Span< System::Net::Security::SecurityBuffer > input, uint sequenceNumber) inline static private
Definition at line 179 of file SSPIWrapper.cs.
    {
        global::Interop.SspiCli.SecBufferDesc inputOutput = new global::Interop.SspiCli.SecBufferDesc(input.Length);
        Span<global::Interop.SspiCli.SecBuffer> span = stackalloc global::Interop.SspiCli.SecBuffer[input.Length];
        span.Clear();
        fixed (global::Interop.SspiCli.SecBuffer* pBuffers = span)
        {
            fixed (byte* ptr4 = ((input.Length > 0) ? input[0].token : null))
            {
                fixed (byte* ptr3 = ((input.Length > 1) ? input[1].token : null))
                {
                    fixed (byte* ptr2 = ((input.Length > 2) ? input[2].token : null))
                    {
                        inputOutput.pBuffers = pBuffers;
                        ThreeByteArrays threeByteArrays = default(ThreeByteArrays);
                        Span<byte[]> span2 = MemoryMarshal.CreateSpan(ref threeByteArrays._item0, 3).Slice(0, input.Length);
                        for (int i = 0; i < input.Length; i++)
{
                            ref System.Net.Security.SecurityBuffer reference = ref input[i];
                            span[i].cbBuffer = reference.size;
                            span[i].BufferType = reference.type;
                            if (reference.token == null || reference.token.Length == 0)
{
                                span[i].pvBuffer = IntPtr.Zero;
                                continue;
                            }
                            span[i].pvBuffer = Marshal.UnsafeAddrOfPinnedArrayElement(reference.token, reference.offset);
                            span2[i] = reference.token;
                        }
                        int num = op switch
{
                            OP.Encrypt => secModule.EncryptMessage(context, ref inputOutput, sequenceNumber),
                            OP.Decrypt => secModule.DecryptMessage(context, ref inputOutput, sequenceNumber),
                            OP.MakeSignature => secModule.MakeSignature(context, ref inputOutput, sequenceNumber),
                            _ => secModule.VerifySignature(context, ref inputOutput, sequenceNumber),
                        };
                        for (int j = 0; j < input.Length; j++)
{
                            ref System.Net.Security.SecurityBuffer reference2 = ref input[j];
                            reference2.size = span[j].cbBuffer;
                            reference2.type = span[j].BufferType;
                            if (reference2.size == 0)
{
                                reference2.offset = 0;
                                reference2.token = null;
                                continue;
                            }
                            int k;
                            for (k = 0; k < input.Length; k++)
{
                                if (span2[k] != null)
{
                                    byte* ptr = (byte*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(span2[k], 0);
                                    checked
{
                                        if ((void*)span[j].pvBuffer >= ptr && unchecked((nuint)(void*)span[j].pvBuffer) + unchecked((nuint)reference2.size) <= unchecked((nuint)ptr) + unchecked((nuint)span2[k].Length))
{
                                            reference2.offset = (int)(unchecked((byte*)(void*)span[j].pvBuffer) - ptr);
                                            reference2.token = span2[k];
                                            break;
                                        }
                                    }
                                }
                            }
                            if (k >= input.Length)
{
                                reference2.size = 0;
                                reference2.offset = 0;
                                reference2.token = null;
                            }
                        }
                        if (System.Net.NetEventSource.Log.IsEnabled() && num != 0)
{
                            System.Net.NetEventSource.Error(null, (num == 590625) ? System.SR.Format(System.SR.event_OperationReturnedSomething, op, "SEC_I_RENEGOTIATE") : System.SR.Format(System.SR.net_log_operation_failed_with_error, op, $"0x{0:X}"), "EncryptDecryptHelper");
                        }
                        return num;
                    }
                }
            }
        }
    }
References System.Net.SSPIWrapper.ThreeByteArrays._item0, System.Span< T >.Clear(), System.Net.NetEventSource.Error(), System.SR.event_OperationReturnedSomething, System.SR.Format(), System.input, System.Net.NetEventSource.Log, System.SR.net_log_operation_failed_with_error, System.Net.Security.SecurityBuffer.size, System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement(), and System.IntPtr.Zero.
Referenced by System.Net.SSPIWrapper.DecryptMessage(), System.Net.SSPIWrapper.EncryptMessage(), System.Net.SSPIWrapper.MakeSignature(), System.Net.SSPIWrapper.MakeSignature(), System.Net.SSPIWrapper.VerifySignature(), and System.Net.SSPIWrapper.VerifySignature().