Terraria: Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor
GetPlayerInfoForOpeningDoor()
PlayerInfoForOpeningDoors Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor (Player player) inline private
Definition at line 315 of file DoorOpeningHelper.cs.
    {
        int num = player.controlRight.ToInt() - player.controlLeft.ToInt();
        int playerGravityDirection = (int)player.gravDir;
        Rectangle hitbox = player.Hitbox;
        hitbox.Y -= -1;
        hitbox.Height += -2;
        float num2 = player.velocity.X;
        if (num == 0 && _timeWeCanOpenDoorsUsingVelocityAlone == 0)
        {
            num2 = 0f;
        }
        float value = (float)num + num2;
        int num3 = Math.Sign(value) * (int)Math.Ceiling(Math.Abs(value));
        hitbox.X += num3;
        if (num == 0)
        {
            num = Math.Sign(value);
        }
        Rectangle hitbox2;
        Rectangle value2 = (hitbox2 = player.Hitbox);
        hitbox2.X += num3;
        Rectangle r = Rectangle.Union(value2, hitbox2);
        Point point = r.TopLeft().ToTileCoordinates();
        Point point2 = r.BottomRight().ToTileCoordinates();
        Rectangle tileCoordSpaceForCheckingForDoors = new Rectangle(point.X, point.Y, point2.X - point.X, point2.Y - point.Y);
        PlayerInfoForOpeningDoors result = default(PlayerInfoForOpeningDoors);
        result.hitboxToOpenDoor = hitbox;
        result.intendedOpeningDirection = num;
        result.playerGravityDirection = playerGravityDirection;
        result.tileCoordSpaceForCheckingForDoors = tileCoordSpaceForCheckingForDoors;
        return result;
    }
References Terraria.GameContent.DoorOpeningHelper._timeWeCanOpenDoorsUsingVelocityAlone, System.Math.Abs(), System.Math.Ceiling(), Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.gravDir, Terraria.Entity.Hitbox, System.Math.Sign(), Microsoft.Xna.Framework.Rectangle.Union(), System.value, Terraria.Entity.velocity, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.DoorOpeningHelper.LookForDoorsToOpen().