Terraria: System.Net.SSPIWrapper.QueryContextAttributes_SECPKG_ATTR_REMOTE_CERT_CONTEXT
QueryContextAttributes_SECPKG_ATTR_REMOTE_CERT_CONTEXT()
static SafeFreeCertContext System.Net.SSPIWrapper.QueryContextAttributes_SECPKG_ATTR_REMOTE_CERT_CONTEXT (ISSPIInterface secModule, SafeDeleteContext securityContext) inline static
Definition at line 389 of file SSPIWrapper.cs.
    {
        Span<IntPtr> span = stackalloc IntPtr[1];
        SafeHandle refHandle;
        int num = secModule.QueryContextAttributes(securityContext, global::Interop.SspiCli.ContextAttribute.SECPKG_ATTR_REMOTE_CERT_CONTEXT, MemoryMarshal.AsBytes(span), typeof(SafeFreeCertContext), out refHandle);
        if (num != 0)
        {
            refHandle?.Dispose();
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(null, $"ERROR = {ErrorDescription(num)}", "QueryContextAttributes_SECPKG_ATTR_REMOTE_CERT_CONTEXT");
            }
            return null;
        }
        return (SafeFreeCertContext)refHandle;
    }
References System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Log, and System.Net.ISSPIInterface.QueryContextAttributes().
Referenced by System.Net.CertificateValidationPal.GetRemoteCertificate().