Terraria: System.Type.IsAssignableFrom
IsAssignableFrom() [2/4]
virtual bool System.Type.IsAssignableFrom ([NotNullWhen(true)] Type? c) inline virtual inherited
Reimplemented in System.Reflection.Emit.GenericTypeParameterBuilder, and System.Reflection.Emit.TypeBuilder.
Definition at line 1561 of file Type.cs.
    {
        if (c == null)
        {
            return false;
        }
        if (this == c)
        {
            return true;
        }
        Type underlyingSystemType = UnderlyingSystemType;
        if ((object)underlyingSystemType != null && underlyingSystemType.IsRuntimeImplemented())
        {
            return underlyingSystemType.IsAssignableFrom(c);
        }
        if (c.IsSubclassOf(this))
        {
            return true;
        }
        if (IsInterface)
        {
            return c.ImplementInterface(this);
        }
        if (IsGenericParameter)
        {
            Type[] genericParameterConstraints = GetGenericParameterConstraints();
            for (int i = 0; i < genericParameterConstraints.Length; i++)
            {
                if (!genericParameterConstraints[i].IsAssignableFrom(c))
                {
                    return false;
                }
            }
            return true;
        }
        return false;
    }
References System.Type.GetGenericParameterConstraints(), System.Type.ImplementInterface(), System.Type.IsAssignableFrom(), System.Type.IsGenericParameter, System.Type.IsInterface, System.Type.IsRuntimeImplemented(), System.Type.IsSubclassOf(), and System.Type.UnderlyingSystemType.
Referenced by System.Linq.Expressions.ConstantCheck.AnalyzeTypeIs(), System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.DefaultBinder.BindToField(), System.DefaultBinder.BindToMethod(), System.ComponentModel.TypeDescriptor.CheckDefaultProvider(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert(), System.Linq.Expressions.Compiler.ILGen.EmitConvertToType(), System.DefaultBinder.FindMostSpecificType(), System.Reflection.Emit.DynamicMethod.RTDynamicMethod.GetCustomAttributes(), System.Dynamic.Utils.TypeUtils.HasReferenceConversionTo(), System.Runtime.Serialization.CodeGenerator.InternalConvert(), System.Xml.Serialization.CodeGenerator.InternalConvert(), System.Type.IsAssignableFrom(), System.Type.IsAssignableTo(), System.Reflection.Emit.DynamicMethod.RTDynamicMethod.IsDefined(), System.Type.IsInstanceOfType(), System.Linq.Expressions.Interpreter.ExceptionHandler.Matches(), System.Security.AccessControl.ObjectSecurity< T >.ModifyAccessRule(), System.Security.AccessControl.ObjectSecurity< T >.ModifyAuditRule(), System.Linq.Expressions.Interpreter.CastInstruction.CastInstructionNoT.Run(), System.DefaultBinder.SelectMethod(), System.DefaultBinder.SelectProperty(), System.ComponentModel.DataAnnotations.RangeAttribute.SetupConversion(), System.Dynamic.Utils.TypeUtils.StrictHasReferenceConversionTo(), System.Xml.Serialization.TypeExtensions.TryConvertTo(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedSerializable(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteDerivedSerializable().