Terraria: System.Type.GetTypeHandleInternal
GetTypeHandleInternal()
virtual RuntimeTypeHandle System.Type.GetTypeHandleInternal () inline package virtual inherited
Definition at line 449 of file Type.cs.
    {
        return TypeHandle;
    }
References System.Type.TypeHandle.
Referenced by System.Reflection.MdFieldInfo.CacheEquals(), System.Enum.GetEnumInfo(), System.RuntimeType.GetGenericArguments(), System.RuntimeType.GetGenericArgumentsInternal(), System.RuntimeType.GetInterfaceMap(), and System.Reflection.MdFieldInfo.GetValue().