Terraria: System.Type.GetEnumUnderlyingType
GetEnumUnderlyingType()
virtual Type System.Type.GetEnumUnderlyingType () inline virtual inherited
Reimplemented in System.Reflection.Emit.EnumBuilder, System.Reflection.SignatureType, and System.RuntimeType.
Definition at line 1035 of file Type.cs.
    {
        if (!IsEnum)
        {
            throw new ArgumentException(SR.Arg_MustBeEnum, "enumType");
        }
        FieldInfo[] fields = GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
        if (fields == null || fields.Length != 1)
        {
            throw new ArgumentException(SR.Argument_InvalidEnum, "enumType");
        }
        return fields[0].FieldType;
    }
References System.SR.Arg_MustBeEnum, System.SR.Argument_InvalidEnum, System.Reflection.FieldInfo.FieldType, System.Type.GetFields(), and System.Type.IsEnum.
Referenced by System.ComponentModel.ReflectPropertyDescriptor.ReflectPropertyDescriptor(), System.Enum.GetUnderlyingType(), and System.Type.IsEnumDefined().