Terraria: System.Type.IsIntegerType
IsIntegerType()
static bool System.Type.IsIntegerType (Type t) inline static package inherited
Definition at line 1280 of file Type.cs.
    {
        if (!(t == typeof(int)) && !(t == typeof(short)) && !(t == typeof(ushort)) && !(t == typeof(byte)) && !(t == typeof(sbyte)) && !(t == typeof(uint)) && !(t == typeof(long)) && !(t == typeof(ulong)) && !(t == typeof(char)))
        {
            return t == typeof(bool);
        }
        return true;
    }
Referenced by System.RuntimeType.GetEnumName(), System.Type.GetEnumName(), System.RuntimeType.IsEnumDefined(), and System.Type.IsEnumDefined().