Terraria: System.Type.GetMethod
GetMethod() [1/12]
MethodInfo? System.Type.GetMethod (string name) inline inherited
Definition at line 675 of file Type.cs.
    {
        return GetMethod(name, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public);
    }
References System.Type.GetMethod().
Referenced by System.Xml.Serialization.FieldModel.FieldModel(), System.Security.Cryptography.XmlKeyHelper.ParseState.Functions.Functions(), Internal.Runtime.InteropServices.LicenseInteropProxy.LicenseInteropProxy(), System.Dynamic.Utils.DelegateHelpers.GetActionThunks(), System.Dynamic.Utils.TypeUtils.GetArrayAddressMethod(), System.Dynamic.Utils.TypeUtils.GetArrayGetMethod(), System.Dynamic.Utils.TypeUtils.GetArraySetMethod(), System.Reflection.TypeInfo.GetDeclaredMethod(), System.Dynamic.Utils.DelegateHelpers.GetFuncThunks(), System.Dynamic.Utils.TypeUtils.GetInvokeMethod(), System.Type.GetMethod(), System.Type.GetMethod(), System.Type.GetMethod(), System.Type.GetMethod(), System.Type.GetMethod(), System.Type.GetMethod(), System.Type.GetMethod(), System.Type.GetMethod(), System.Reflection.Emit.TypeBuilder.GetMethodImpl(), System.Reflection.TypeDelegator.GetMethodImpl(), System.Reflection.RuntimeModule.GetMethodInternal(), System.AppDomain.GetThreadPrincipal(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement().