Terraria: System.Type.EmptyTypes
EmptyTypes
readonly Type [] System.Type.EmptyTypes = Array.Empty<Type>() static inherited
Definition at line 19 of file Type.cs.
Referenced by System.Xml.Xsl.Runtime.EarlyBoundInfo.EarlyBoundInfo(), System.Xml.Serialization.FieldModel.FieldModel(), System.Security.Cryptography.XmlKeyHelper.ParseState.Functions.Functions(), System.Reflection.ReflectionTypeLoadException.ReflectionTypeLoadException(), System.Reflection.ReflectionTypeLoadException.ReflectionTypeLoadException(), System.Reflection.Emit.SymbolMethod.SymbolMethod(), System.Reflection.CustomAttribute.AddCustomAttributes(), System.StartupHookProvider.CallStartupHook(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Complete(), System.Xml.Serialization.SourceInfo.ConvertNullableValue(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateConstructor(), System.Text.Json.Serialization.Metadata.ReflectionMemberAccessor.CreateConstructor(), System.Xml.Xsl.XmlILGenerator.CreateGlobalValueMetadata(), System.ComponentModel.ReflectTypeDescriptionProvider.CreateInstance(), System.Xml.Serialization.XmlSerializerFactory.CreateSerializer(), System.Xml.Serialization.XmlSerializerFactory.CreateSerializer(), System.Reflection.Emit.TypeBuilder.DefineDefaultConstructorNoLock(), System.Linq.Expressions.Compiler.CompilerScope.EmitNewHoistedLocals(), System.Xml.Serialization.CodeGenerator.EndFor(), System.ComponentModel.ReflectPropertyDescriptor.FillAttributes(), System.Xml.Xsl.XmlILGenerator.Generate(), System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateBegin(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd(), System.Xml.Serialization.XmlSerializationILGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateInitCallbacksMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateInitCallbacksMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement(), System.Reflection.DispatchProxyGenerator.GenerateProxyType(), System.Xml.Serialization.XmlSerializationILGen.GenerateSerializerContract(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializers(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateTypeElement(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.GetCollectionElementType(), System.Runtime.Serialization.CollectionDataContract.GetCollectionMethods(), System.Linq.Expressions.LambdaExpression.GetCompileMethod(), System.Runtime.Serialization.XmlDataContract.GetConstructor(), System.Xml.Serialization.TypeScope.GetConstructorFlags(), System.Text.Json.JsonSerializerOptions.GetConverterFromAttribute(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Dynamic.Utils.DelegateHelpers.GetCSharpThunk(), System.ComponentModel.AttributeCollection.GetDefaultAttribute(), System.Xml.Serialization.ReflectionXmlSerializationReader.GetDefaultConstructor(), System.Xml.Serialization.TypeScope.GetEnumeratorElementType(), System.Reflection.Emit.MethodBuilder.GetGenericArguments(), System.Reflection.Emit.TypeBuilder.GetGenericArguments(), System.Reflection.RuntimeMethodInfo.GetGenericArguments(), System.Reflection.SignatureGenericParameterType.GetGenericArguments(), System.Reflection.SignatureHasElementType.GetGenericArguments(), System.RuntimeType.GetGenericArguments(), System.RuntimeType.GetGenericParameterConstraints(), System.Attribute.GetIndexParameterTypes(), System.Reflection.Emit.TypeBuilder.GetInterfaces(), System.Reflection.Emit.MethodBuilder.GetMethodSignature(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetNonAttributedTypeConstructor(), System.Reflection.MdFieldInfo.GetOptionalCustomModifiers(), System.Reflection.ParameterInfo.GetOptionalCustomModifiers(), System.Reflection.PropertyInfo.GetOptionalCustomModifiers(), System.Reflection.RuntimeParameterInfo.GetOptionalCustomModifiers(), System.Reflection.Emit.MethodBuilder.GetParameterTypes(), System.Reflection.MdFieldInfo.GetRequiredCustomModifiers(), System.Reflection.ParameterInfo.GetRequiredCustomModifiers(), System.Reflection.PropertyInfo.GetRequiredCustomModifiers(), System.Reflection.RuntimeParameterInfo.GetRequiredCustomModifiers(), System.Xml.Serialization.XmlSerializationReaderILGen.ILGenElementElseString(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes(), System.Runtime.Serialization.CollectionDataContract.IsCollectionOrTryCreate(), System.Runtime.Serialization.ClassDataContract.IsNonAttributedTypeValidForSerialization(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.ReflectionReader.ReflectionCreateCollection(), System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue(), System.Reflection.Emit.ILGenerator.ThrowException(), System.Linq.Expressions.ExpressionStringBuilder.VisitExtension(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteArray(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteIsStartTag(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberText(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteNullableMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteQNameEqual(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteText(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteText(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteWhileLoopEnd(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteWhileNotLoopStart(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteXmlNodeEqual().