Terraria: System.Type.IsSubclassOf
IsSubclassOf()
virtual bool System.Type.IsSubclassOf (Type c) inline virtual inherited
Reimplemented in System.Reflection.Emit.GenericTypeParameterBuilder, System.Reflection.Emit.TypeBuilder, System.Reflection.Emit.TypeBuilderInstantiation, System.Reflection.SignatureType, and System.RuntimeType.
Definition at line 1542 of file Type.cs.
    {
        Type type = this;
        if (type == c)
        {
            return false;
        }
        while (type != null)
        {
            if (type == c)
            {
                return true;
            }
            type = type.BaseType;
        }
        return false;
    }
References System.Type.BaseType, and System.type.
Referenced by System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.RuntimeType.IsAssignableFrom(), System.Type.IsAssignableFrom(), System.Reflection.TypeInfo.IsAssignableFrom(), System.Attribute.IsDefined(), System.Attribute.IsDefined(), System.Attribute.IsDefined(), System.Attribute.IsDefined(), System.Dynamic.Utils.TypeUtils.IsDelegate(), System.Dynamic.Utils.TypeUtils.IsSameOrSubclass(), System.Type.IsValueTypeImpl(), and System.Reflection.Emit.ILGenerator.ThrowException().