Terraria: System.Type.GetMemberWithSameMetadataDefinitionAs
GetMemberWithSameMetadataDefinitionAs()
virtual MemberInfo System.Type.GetMemberWithSameMetadataDefinitionAs (MemberInfo member) inline virtual inherited
Reimplemented in System.Reflection.TypeDelegator, and System.RuntimeType.
Definition at line 649 of file Type.cs.
    {
        if ((object)member == null)
        {
            throw new ArgumentNullException("member");
        }
        MemberInfo[] members = GetMembers(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
        foreach (MemberInfo memberInfo in members)
        {
            if (memberInfo.HasSameMetadataDefinitionAs(member))
            {
                return memberInfo;
            }
        }
        throw CreateGetMemberWithSameMetadataDefinitionAsNotFoundException(member);
    }
References System.Type.CreateGetMemberWithSameMetadataDefinitionAsNotFoundException(), System.Type.GetMembers(), and System.Reflection.MemberInfo.HasSameMetadataDefinitionAs().
Referenced by System.ComponentModel.NullableConverter.ConvertTo(), System.Linq.Expressions.Compiler.ILGen.EmitGetValue(), System.Linq.Expressions.Compiler.ILGen.EmitGetValueOrDefault(), System.Linq.Expressions.Compiler.ILGen.EmitHasValue(), System.Linq.Expressions.LambdaExpression.GetCompileMethod(), System.Reflection.TypeDelegator.GetMemberWithSameMetadataDefinitionAs(), and System.Dynamic.Utils.TypeUtils.GetNullableConstructor().