Terraria: System.Type.GetInterfaces
GetInterfaces()
Type[] System.Type.GetInterfaces () abstract inherited
Referenced by System.Xml.Serialization.Compiler.AddImport(), System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.PropertyFetch.FetcherForProperty(), System.Linq.TypeHelper.FindGenericType(), System.Type.FindInterfaces(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetAttributes(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.GetCollectionElementType(), System.Text.Json.Reflection.ReflectionExtensions.GetCompatibleGenericInterface(), System.Reflection.TypeDelegator.GetInterfaces(), System.Linq.EnumerableRewriter.GetPublicType(), System.Type.ImplementInterface(), System.Runtime.Serialization.CollectionDataContract.IsCollectionOrTryCreate(), System.Runtime.Serialization.ClassDataContract.IsNonAttributedTypeValidForSerialization(), System.Dynamic.Utils.TypeUtils.IsValidInstanceType(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection().