Terraria: System.Type.GetElementType
GetElementType()
Type? System.Type.GetElementType () abstract inherited
Referenced by System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker(), System.Linq.EnumerableRewriter.ArgsMatch(), System.DefaultBinder.BindToMethod(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert(), System.Diagnostics.Tracing.Statics.CreateDefaultTypeInfo(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Linq.Expressions.Compiler.ILGen.EmitArray(), System.Reflection.Emit.CustomAttributeBuilder.EmitValue(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.ParametersArray.EndSet(), System.DefaultBinder.FindMostSpecificType(), System.Linq.EnumerableRewriter.FixupQuotedExpression(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Reflection.TypeDelegator.GetElementType(), System.ComponentModel.ArrayConverter.GetProperties(), System.Type.GetRootElementType(), System.Xml.Serialization.SourceInfo.InternalLoad(), System.Reflection.RuntimeMethodInfo.IsDisallowedByRefType(), System.Runtime.Serialization.CodeGenerator.LoadArrayElement(), System.Xml.Serialization.CodeGenerator.LoadArrayElement(), System.Reflection.SignatureTypeExtensions.MatchesExactly(), System.Dynamic.Utils.TypeUtils.StrictHasReferenceConversionTo(), System.Xml.Schema.XmlUntypedStringConverter.StringToListType(), System.Reflection.CustomAttributeTypedArgument.ToString(), System.Xml.Serialization.TypeScope.TypeName(), System.Linq.Expressions.NewArrayExpression.Update(), System.Reflection.Emit.CustomAttributeBuilder.ValidateType(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttribute(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd().