Terraria: System.Type.IsEnumDefined
IsEnumDefined()
virtual bool System.Type.IsEnumDefined (object value) inline virtual inherited
Reimplemented in System.Reflection.SignatureType, and System.RuntimeType.
Definition at line 1147 of file Type.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (!IsEnum)
        {
            throw new ArgumentException(SR.Arg_MustBeEnum, "value");
        }
        Type type = value.GetType();
        if (type.IsEnum)
        {
            if (!type.IsEquivalentTo(this))
            {
                throw new ArgumentException(SR.Format(SR.Arg_EnumAndObjectMustBeSameType, type, this));
            }
            type = type.GetEnumUnderlyingType();
        }
        if (type == typeof(string))
        {
            string[] enumNames = GetEnumNames();
            object[] array = enumNames;
            if (Array.IndexOf(array, value) >= 0)
            {
                return true;
            }
            return false;
        }
        if (IsIntegerType(type))
        {
            Type enumUnderlyingType = GetEnumUnderlyingType();
            if (enumUnderlyingType.GetTypeCodeImpl() != type.GetTypeCodeImpl())
            {
                throw new ArgumentException(SR.Format(SR.Arg_EnumUnderlyingTypeAndObjectMustBeSameType, type, enumUnderlyingType));
            }
            Array enumRawConstantValues = GetEnumRawConstantValues();
            return BinarySearch(enumRawConstantValues, value) >= 0;
        }
        throw new InvalidOperationException(SR.InvalidOperation_UnknownEnumType);
    }
References System.SR.Arg_EnumAndObjectMustBeSameType, System.SR.Arg_EnumUnderlyingTypeAndObjectMustBeSameType, System.SR.Arg_MustBeEnum, System.array, System.Type.BinarySearch(), System.SR.Format(), System.Type.GetEnumNames(), System.Type.GetEnumRawConstantValues(), System.Type.GetEnumUnderlyingType(), System.Type.GetType(), System.Type.GetTypeCodeImpl(), System.Array.IndexOf(), System.SR.InvalidOperation_UnknownEnumType, System.Type.IsEnum, System.Type.IsIntegerType(), System.type, and System.value.
Referenced by System.Enum.IsDefined().