Terraria: System.Type.Equals
Equals() [1/2]
override bool System.Type.Equals (object? o) inline inherited
Definition at line 1113 of file Type.cs.
    {
        if (o != null)
        {
            return Equals(o as Type);
        }
        return false;
    }
References System.Type.Equals().
Referenced by Extensions.EnumerationExtensions._Value._Value(), System.ComponentModel.LicenseProviderAttribute.Equals(), System.Type.Equals(), System.Linq.Expressions.Compiler.BoundConstants.TypedConstant.Equals(), System.DefaultBinder.ExactBinding(), and Microsoft.Win32.OAVariantLib.GetCVTypeFromClass().