Terraria: System.Type.FormatTypeName
FormatTypeName()
string System.Type.FormatTypeName () inline package inherited
Definition at line 1098 of file Type.cs.
    {
        Type rootElementType = GetRootElementType();
        if (rootElementType.IsPrimitive || rootElementType.IsNested || rootElementType == typeof(void) || rootElementType == typeof(TypedReference))
        {
            return Name;
        }
        return ToString();
    }
References System.Type.GetRootElementType(), System.Type.IsNested, System.Type.IsPrimitive, System.Reflection.MemberInfo.Name, and System.Type.ToString().
Referenced by System.Reflection.Emit.DynamicMethod.RTDynamicMethod.ToString(), and System.Reflection.RuntimeFieldInfo.ToString().