Terraria: System.Type.IsInstanceOfType
IsInstanceOfType()
virtual bool System.Type.IsInstanceOfType ([NotNullWhen(true)] object? o) inline virtual inherited
Definition at line 1020 of file Type.cs.
    {
        if (o != null)
        {
            return IsAssignableFrom(o.GetType());
        }
        return false;
    }
References System.Type.IsAssignableFrom().
Referenced by System.ComponentModel.ReflectPropertyDescriptor.AddValueChanged(), System.ComponentModel.ComponentResourceManager.ApplyResources(), System.DefaultBinder.BindToMethod(), System.ComponentModel.BaseNumberConverter.ConvertTo(), System.ComponentModel.NullableConverter.ConvertTo(), System.ComponentModel.ReferenceConverter.GetStandardValues(), System.ComponentModel.TypeDescriptor.ComNativeDescriptionProvider.GetTypeDescriptor(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.GetTypeDescriptor(), System.ComponentModel.ReflectPropertyDescriptor.RemoveValueChanged(), System.Linq.Expressions.Interpreter.TypeAsInstruction.Run(), System.Linq.Expressions.Interpreter.TypeIsInstruction.Run(), System.Data.Common.ObjectStorage.Set(), System.Data.Common.SqlUdtStorage.Set(), and System.ComponentModel.DataAnnotations.CustomValidationAttribute.TryConvertValue().