Terraria: System.Type.GetType
GetType() [4/7]
static ? Type System.Type.GetType (string typeName, bool throwOnError, bool ignoreCase) inline static inherited
Definition at line 408 of file Type.cs.
    {
        StackCrawlMark stackMark = StackCrawlMark.LookForMyCaller;
        return RuntimeType.GetType(typeName, throwOnError, ignoreCase, ref stackMark);
    }
References System.RuntimeType.GetType().
Referenced by System.ComponentModel.TypeDescriptor.ComNativeDescriptorProxy.ComNativeDescriptorProxy(), System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder(), System.Reflection.CustomAttributeTypedArgument.CustomAttributeTypedArgument(), System.ComponentModel.DefaultValueAttribute.DefaultValueAttribute(), System.Security.Cryptography.XmlKeyHelper.ParseState.Functions.Functions(), Internal.Runtime.InteropServices.LicenseInteropProxy.LicenseInteropProxy(), System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap(), System.ComponentModel.ReflectEventDescriptor.AddEventHandler(), System.ComponentModel.ComponentResourceManager.ApplyResources(), System.Security.Cryptography.CryptoConfigForwarder.BindCreateFromName(), System.DefaultBinder.BindToField(), System.DefaultBinder.BindToMethod(), System.Xml.Schema.XmlListConverter.ChangeListType(), System.Xml.Schema.XmlUntypedConverter.ChangeListType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlDateTimeConverter.ChangeType(), System.Xml.Schema.XmlMiscConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlStringConverter.ChangeType(), System.Xml.Schema.XmlUnionConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.OleAutBinder.ChangeType(), System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Xml.Schema.XmlAnyConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlMiscConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlNumeric10Converter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardDestination(), System.Xml.Xsl.Runtime.XmlQueryRuntime.ChangeTypeXsltResult(), System.ComponentModel.TypeDescriptor.CheckDefaultProvider(), System.RuntimeType.CheckValue(), Internal.Runtime.InteropServices.ComActivator.ClassRegistrationScenarioForType(), System.Data.DataColumn.CompareValueTo(), System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(), System.Xml.Schema.XmlSchemaDatatype.ConcatenatedToString(), System.Data.Common.SqlConvert.ConvertToSqlBinary(), System.Data.Common.SqlConvert.ConvertToSqlBoolean(), System.Data.Common.SqlConvert.ConvertToSqlByte(), System.Data.Common.SqlConvert.ConvertToSqlBytes(), System.Data.Common.SqlConvert.ConvertToSqlChars(), System.Data.Common.SqlConvert.ConvertToSqlDateTime(), System.Data.Common.SqlConvert.ConvertToSqlDecimal(), System.Data.Common.SqlConvert.ConvertToSqlDouble(), System.Data.Common.SqlConvert.ConvertToSqlGuid(), System.Data.Common.SqlConvert.ConvertToSqlInt16(), System.Data.Common.SqlConvert.ConvertToSqlInt32(), System.Data.Common.SqlConvert.ConvertToSqlInt64(), System.Data.Common.SqlConvert.ConvertToSqlMoney(), System.Data.Common.SqlConvert.ConvertToSqlSingle(), System.Data.Common.SqlConvert.ConvertToSqlString(), System.Data.Common.TimeSpanStorage.ConvertToTimeSpan(), System.Data.Common.ObjectStorage.ConvertXmlToObject(), System.Data.Common.ObjectStorage.ConvertXmlToObject(), System.Data.Common.SqlUdtStorage.ConvertXmlToObject(), System.Collections.ObjectModel.Collection< T >.CopyTo(), System.Collections.ObjectModel.ReadOnlyCollection< T >.CopyTo(), System.ComponentModel.TypeDescriptor.CreateDesigner(), System.Security.Cryptography.CryptoConfig.CreateFromName(), System.Xml.Serialization.SchemaGraph.Depends(), System.Data.DataTable.DeserializeTableSchema(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression(), System.Reflection.Emit.ILGenerator.EmitWriteLine(), System.Reflection.Emit.ILGenerator.EmitWriteLine(), System.Reflection.Emit.ILGenerator.EmitWriteLine(), System.ValueType.Equals(), System.Data.BinaryNode.EvalBinaryOp(), System.ComponentModel.ReflectPropertyDescriptor.FillAttributes(), System.Resources.ResourceWriter.FindTypeCode(), System.Enum.Format(), System.Xml.Serialization.XmlCustomFormatter.FromDefaultValue(), System.Data.NewDiffgramGen.GenerateColumn(), System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetAsyncStateMachineDescription(), ReLogic.Utilities.AttributeUtilities.GetAttribute< T >(), System.Data.FunctionNode.GetDataType(), System.Resources.ResourceSet.GetDefaultWriter(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetEditorAttribute(), System.RuntimeType.GetEnumName(), System.Type.GetEnumName(), System.Data.DataRowComparer< TRow >.GetHashCode(), System.ComponentModel.ReflectTypeDescriptionProvider.GetIntrinsicTypeEditor(), System.ComponentModel.ArrayConverter.GetProperties(), System.Data.Common.DbProviderFactories.GetProviderTypeFromTypeName(), System.ComponentModel.TypeDescriptionProvider.GetRuntimeType(), System.Text.Json.JsonSerializer.GetRuntimeTypeAndValidateInputType(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetSimplyNamedTypeFromAssembly(), System.AppDomain.GetThreadPrincipal(), System.Exception.GetType(), System.Type.GetType(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetType(), System.Data.Common.DataStorage.GetType(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetTypeFromName(), System.ComponentModel.PropertyDescriptor.GetTypeFromName(), System.ComponentModel.ReflectTypeDescriptionProvider.GetTypeFromName(), System.Text.Json.Serialization.IEnumerableConverterFactoryHelpers.GetTypeIfExists(), Extensions.EnumerationExtensions.Has< T >(), System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.HasHandler(), Extensions.EnumerationExtensions.Include< T >(), System.Resources.ResourceReader.InitializeBinaryFormatter(), System.Diagnostics.StackFrameHelper.InitializeSourceInfo(), System.ComponentModel.PropertyTabAttribute.InitializeTabClasses(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(), Internal.Runtime.InteropServices.ComponentActivator.InternalGetFunctionPointer(), System.Resources.ManifestBasedResourceGroveler.InternalGetResourceSetFromSerializedData(), System.Type.IsEnumDefined(), System.ComponentModel.DataAnnotations.EnumDataTypeAttribute.IsValid(), System.Xml.Schema.Preprocessor.LoadExternals(), System.ComponentModel.TypeDescriptor.NodeRemove(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ReadJsonAndSetMember(), Extensions.EnumerationExtensions.Remove< T >(), System.Runtime.Serialization.ReflectionReader.ResolveAdapterObject(), System.Runtime.Serialization.ReflectionClassWriter.ResolveAdapterType(), System.Linq.Expressions.Interpreter.CastInstruction.CastInstructionNoT.Run(), System.Data.Common.ObjectStorage.Set(), System.Reflection.Emit.TypeBuilder.SetConstantValue(), System.Data.XSDSchema.SetProperties(), System.Xml.Schema.XmlAnyConverter.ToBoolean(), System.Xml.Schema.XmlBooleanConverter.ToBoolean(), System.Xml.Schema.XmlUntypedConverter.ToBoolean(), System.Xml.Schema.XmlAnyConverter.ToDateTime(), System.Xml.Schema.XmlDateTimeConverter.ToDateTime(), System.Xml.Schema.XmlUntypedConverter.ToDateTime(), System.Xml.Schema.XmlAnyConverter.ToDateTimeOffset(), System.Xml.Schema.XmlDateTimeConverter.ToDateTimeOffset(), System.Xml.Schema.XmlUntypedConverter.ToDateTimeOffset(), System.Xml.Schema.XmlAnyConverter.ToDecimal(), System.Xml.Schema.XmlNumeric10Converter.ToDecimal(), System.Xml.Schema.XmlUntypedConverter.ToDecimal(), System.Xml.Schema.XmlAnyConverter.ToDouble(), System.Xml.Schema.XmlNumeric2Converter.ToDouble(), System.Xml.Schema.XmlUntypedConverter.ToDouble(), System.Xml.Schema.XmlAnyConverter.ToInt32(), System.Xml.Schema.XmlNumeric10Converter.ToInt32(), System.Xml.Schema.XmlUntypedConverter.ToInt32(), System.Xml.Schema.XmlAnyConverter.ToInt64(), System.Xml.Schema.XmlNumeric10Converter.ToInt64(), System.Xml.Schema.XmlUntypedConverter.ToInt64(), System.Xml.Schema.XmlAnyConverter.ToSingle(), System.Xml.Schema.XmlNumeric2Converter.ToSingle(), System.Xml.Schema.XmlUntypedConverter.ToSingle(), System.Xml.Schema.XmlBooleanConverter.ToString(), System.Xml.Schema.XmlDateTimeConverter.ToString(), System.Xml.Schema.XmlMiscConverter.ToString(), System.Xml.Schema.XmlNumeric10Converter.ToString(), System.Xml.Schema.XmlNumeric2Converter.ToString(), System.Xml.Schema.XmlStringConverter.ToString(), System.Xml.Schema.XmlUntypedConverter.ToString(), System.Text.Json.Serialization.JsonConverter< T >.TryWrite(), System.Resources.ResourceReader.UseReflectionToGetType(), System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject(), System.Xml.Serialization.SchemaObjectWriter.Write48_XmlSchemaIdentityConstraint(), System.Text.Json.Serialization.Converters.ObjectConverter.WriteAsPropertyNameCore(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteCheckDefault(), System.Reflection.Metadata.BlobWriterImpl.WriteConstant(), System.Reflection.Metadata.BlobWriterImpl.WriteConstant(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteISerializable(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteJsonISerializable(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteValue(), and System.Data.XmlDataTreeWriter.XmlDataRowWriter().