Terraria: System.Type.GetTypeCode
GetTypeCode()
static TypeCode System.Type.GetTypeCode (Type? type) inline static inherited
Definition at line 919 of file Type.cs.
    {
        return type?.GetTypeCodeImpl() ?? TypeCode.Empty;
    }
References System.type.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.SwitchInfo.SwitchInfo(), System.Diagnostics.Tracing.EventSource.AddEventDescriptor(), System.DefaultBinder.CanChangePrimitive(), System.Data.DataRowComparer< TRow >.CompareArray(), System.StubHelpers.AsAnyMarshaler.ConvertArrayToNative(), System.Data.Common.ObjectStorage.ConvertObjectToXml(), System.Linq.Expressions.Interpreter.CastInstruction.Create(), System.Diagnostics.Tracing.EventSource.DecodeObjects(), System.Xml.Serialization.XmlSerializer.DeserializePrimitive(), System.Linq.Expressions.Compiler.ILGen.EmitNumericConversion(), System.Reflection.Emit.CustomAttributeBuilder.EmitType(), System.Reflection.Emit.CustomAttributeBuilder.EmitValue(), System.Data.Common.ObjectStorage.GetFamily(), System.Collections.Generic.EnumEqualityComparer< T >.GetObjectData(), System.Xml.Serialization.XmlSerializationWriter.GetPrimitiveTypeNameInternal(), System.Data.Common.DataStorage.GetStorageType(), System.Dynamic.Utils.TypeExtensions.GetTypeCode(), System.Diagnostics.Tracing.EventParameterInfo.GetTypeCodeExtended(), System.RuntimeType.GetTypeCodeImpl(), System.Type.GetTypeCodeImpl(), System.Diagnostics.Tracing.ManifestBuilder.GetTypeName(), System.Xml.Xsl.XsltOld.XsltCompileContext.GetXPathType(), System.Runtime.Serialization.CodeGenerator.InternalConvert(), System.Xml.Serialization.CodeGenerator.InternalConvert(), System.Xml.Serialization.TypeScope.IsKnownType(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.IsValueWriteAtomic(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldelem(), System.Xml.Serialization.CodeGenerator.Ldobj(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsAnyType(), System.Runtime.Serialization.XmlReaderDelegator.ReadExtensionData(), System.Runtime.Serialization.Json.ReflectionJsonReader.ReadSimpleDictionary(), System.Linq.Expressions.Interpreter.CastReferenceToEnumInstruction.Run(), System.Xml.Serialization.XmlSerializer.SerializePrimitive(), System.Xml.Xsl.XsltOld.NumberAction.SimplifyValue(), System.Xml.Serialization.CodeGenerator.Stelem(), System.Runtime.Serialization.Formatters.Binary.Converter.ToCode(), System.Enum.ToUInt64< TEnum >(), System.Collections.Generic.ComparerHelpers.TryCreateEnumComparer(), System.Collections.Generic.ComparerHelpers.TryCreateEnumEqualityComparer(), System.Enum.TryParse(), System.Enum.TryParse< TEnum >(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitiveArray(), System.Reflection.Emit.CustomAttributeBuilder.ValidateType(), System.Reflection.Emit.CustomAttributeBuilder.VerifyTypeAndPassedObjectType(), System.Runtime.Serialization.XmlWriterDelegator.WriteExtensionData(), System.Xml.Serialization.XmlSerializationWriter.WritePotentiallyReferencingElement(), and System.Xml.Serialization.XmlSerializationWriter.WriteTypedPrimitive().