Terraria: System.Type.FindMembers
FindMembers()
virtual MemberInfo[] System.Type.FindMembers (MemberTypes memberType, BindingFlags bindingAttr, MemberFilter? filter, object? filterCriteria) inline virtual inherited
Definition at line 1336 of file Type.cs.
    {
        MethodInfo[] array = null;
        ConstructorInfo[] array2 = null;
        FieldInfo[] array3 = null;
        PropertyInfo[] array4 = null;
        EventInfo[] array5 = null;
        Type[] array6 = null;
        int num = 0;
        if ((memberType & MemberTypes.Method) != 0)
        {
            array = GetMethods(bindingAttr);
            if (filter != null)
            {
                for (int i = 0; i < array.Length; i++)
                {
                    if (!filter(array[i], filterCriteria))
                    {
                        array[i] = null;
                    }
                    else
                    {
                        num++;
                    }
                }
            }
            else
            {
                num += array.Length;
            }
        }
        if ((memberType & MemberTypes.Constructor) != 0)
        {
            array2 = GetConstructors(bindingAttr);
            if (filter != null)
            {
                for (int i = 0; i < array2.Length; i++)
                {
                    if (!filter(array2[i], filterCriteria))
                    {
                        array2[i] = null;
                    }
                    else
                    {
                        num++;
                    }
                }
            }
            else
            {
                num += array2.Length;
            }
        }
        if ((memberType & MemberTypes.Field) != 0)
        {
            array3 = GetFields(bindingAttr);
            if (filter != null)
            {
                for (int i = 0; i < array3.Length; i++)
                {
                    if (!filter(array3[i], filterCriteria))
                    {
                        array3[i] = null;
                    }
                    else
                    {
                        num++;
                    }
                }
            }
            else
            {
                num += array3.Length;
            }
        }
        if ((memberType & MemberTypes.Property) != 0)
        {
            array4 = GetProperties(bindingAttr);
            if (filter != null)
            {
                for (int i = 0; i < array4.Length; i++)
                {
                    if (!filter(array4[i], filterCriteria))
                    {
                        array4[i] = null;
                    }
                    else
                    {
                        num++;
                    }
                }
            }
            else
            {
                num += array4.Length;
            }
        }
        if ((memberType & MemberTypes.Event) != 0)
        {
            array5 = GetEvents(bindingAttr);
            if (filter != null)
            {
                for (int i = 0; i < array5.Length; i++)
                {
                    if (!filter(array5[i], filterCriteria))
                    {
                        array5[i] = null;
                    }
                    else
                    {
                        num++;
                    }
                }
            }
            else
            {
                num += array5.Length;
            }
        }
        if ((memberType & MemberTypes.NestedType) != 0)
        {
            array6 = GetNestedTypes(bindingAttr);
            if (filter != null)
            {
                for (int i = 0; i < array6.Length; i++)
                {
                    if (!filter(array6[i], filterCriteria))
                    {
                        array6[i] = null;
                    }
                    else
                    {
                        num++;
                    }
                }
            }
            else
            {
                num += array6.Length;
            }
        }
        MemberInfo[] array7 = new MemberInfo[num];
        num = 0;
        if (array != null)
        {
            for (int i = 0; i < array.Length; i++)
            {
                if (array[i] != null)
                {
                    array7[num++] = array[i];
                }
            }
        }
        if (array2 != null)
        {
            foreach (ConstructorInfo constructorInfo in array2)
            {
                if ((object)constructorInfo != null)
                {
                    array7[num++] = constructorInfo;
                }
            }
        }
        if (array3 != null)
        {
            foreach (FieldInfo fieldInfo in array3)
            {
                if ((object)fieldInfo != null)
                {
                    array7[num++] = fieldInfo;
                }
            }
        }
        if (array4 != null)
        {
            foreach (PropertyInfo propertyInfo in array4)
            {
                if ((object)propertyInfo != null)
                {
                    array7[num++] = propertyInfo;
                }
            }
        }
        if (array5 != null)
        {
            foreach (EventInfo eventInfo in array5)
            {
                if ((object)eventInfo != null)
                {
                    array7[num++] = eventInfo;
                }
            }
        }
        if (array6 != null)
        {
            foreach (Type type in array6)
            {
                if ((object)type != null)
                {
                    array7[num++] = type;
                }
            }
        }
        return array7;
    }
References System.array, System.Type.GetConstructors(), System.Type.GetEvents(), System.Type.GetFields(), System.Type.GetMethods(), System.Type.GetNestedTypes(), System.Type.GetProperties(), and System.type.