Terraria: System.Type.GetEnumName
GetEnumName()
virtual ? string System.Type.GetEnumName (object value) inline virtual inherited
Reimplemented in System.Reflection.SignatureType, and System.RuntimeType.
Definition at line 1189 of file Type.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (!IsEnum)
        {
            throw new ArgumentException(SR.Arg_MustBeEnum, "value");
        }
        Type type = value.GetType();
        if (!type.IsEnum && !IsIntegerType(type))
        {
            throw new ArgumentException(SR.Arg_MustBeEnumBaseTypeOrEnum, "value");
        }
        Array enumRawConstantValues = GetEnumRawConstantValues();
        int num = BinarySearch(enumRawConstantValues, value);
        if (num >= 0)
        {
            string[] enumNames = GetEnumNames();
            return enumNames[num];
        }
        return null;
    }
References System.SR.Arg_MustBeEnum, System.SR.Arg_MustBeEnumBaseTypeOrEnum, System.Type.BinarySearch(), System.Type.GetEnumNames(), System.Type.GetEnumRawConstantValues(), System.Type.GetType(), System.Type.IsEnum, System.Type.IsIntegerType(), System.type, and System.value.
Referenced by System.Enum.GetName().