Terraria: System.Xml.Xsl.XsltOld.ReaderOutput.XmlEncoder.AttributeOuterXml
AttributeOuterXml()
string System.Xml.Xsl.XsltOld.ReaderOutput.XmlEncoder.AttributeOuterXml (string name, string value) inline
Definition at line 40 of file ReaderOutput.cs.
        {
            if (_encoder == null)
            {
                Init();
            }
            _buffer.Length = 0;
            _buffer.Append(name);
            _buffer.Append('=');
            _buffer.Append(QuoteChar);
            _encoder.StartAttribute(cacheAttrValue: false);
            _encoder.Write(value);
            _encoder.EndAttribute();
            _buffer.Append(QuoteChar);
            return _buffer.ToString();
        }
References System.Xml.Xsl.XsltOld.ReaderOutput.XmlEncoder._buffer, System.Xml.Xsl.XsltOld.ReaderOutput.XmlEncoder._encoder, System.Text.StringBuilder.Append(), System.Xml.Dictionary, System.Xml.XmlTextEncoder.EndAttribute(), System.Xml.Xsl.XsltOld.ReaderOutput.XmlEncoder.Init(), System.Xml.Xsl.XsltOld.ReaderOutput.XmlEncoder.QuoteChar, System.Xml.XmlTextEncoder.StartAttribute(), System.Text.StringBuilder.ToString(), System.value, and System.Xml.XmlTextEncoder.Write().
Referenced by System.Xml.Xsl.XsltOld.ReaderOutput.ReadOuterXml().