Terraria: System.Reflection.Metadata.MetadataStringDecoder.DefaultUTF8
DefaultUTF8
MetadataStringDecoder System.Reflection.Metadata.MetadataStringDecoder.DefaultUTF8 = new MetadataStringDecoder(System.Text.Encoding.UTF8) static get
Definition at line 9 of file MetadataStringDecoder.cs.
{ get; } = new MetadataStringDecoder(System.Text.Encoding.UTF8);
Referenced by System.Reflection.Metadata.MetadataReader.MetadataReader(), System.Reflection.Metadata.MetadataReaderProvider.CanReuseReader(), and System.Reflection.Metadata.BlobReader.ReadUtf8NullTerminated().