Terraria: System.Reflection.Metadata.MetadataStringDecoder.GetString
GetString()
virtual unsafe string System.Reflection.Metadata.MetadataStringDecoder.GetString (byte * bytes, int byteCount) inline virtual
Definition at line 21 of file MetadataStringDecoder.cs.
    {
        return Encoding.GetString(bytes, byteCount);
    }
References System.byteCount, System.bytes, and System.Text.Encoding.GetString().
Referenced by System.Reflection.Internal.EncodingHelper.DecodeUtf8(), and System.Reflection.Internal.EncodingHelper.DecodeUtf8Prefixed().