Terraria: RemoteClient.TryRead
TryRead()
void RemoteClient.TryRead () inline private
     {
         if (_isReading)
         {
             return;
         }
         try
         {
             if (Socket.IsDataAvailable())
             {
                 _isReading = true;
                 Socket.AsyncReceive(ReadBuffer, 0, ReadBuffer.Length, ServerReadCallBack);
             }
         }
         catch
         {
             PendingTermination = true;
         }
     }
References _isReading, ISocket.AsyncReceive(), ISocket.IsDataAvailable(), PendingTermination, ReadBuffer, ServerReadCallBack(), and Socket.
Referenced by Update().