Terraria: RemoteClient.Reset
Reset()
void RemoteClient.Reset () inline
     {
         ResetSections();
         if (Id < 255)
         {
             Main.player[Id] = new Player();
         }
         TimeOutTimer = 0;
         StatusCount = 0;
         StatusMax = 0;
         StatusText2 = "";
         StatusText = "";
         State = 0;
         _isReading = false;
         PendingTermination = false;
         PendingTerminationApproved = false;
         SpamClear();
         IsActive = false;
         NetMessage.buffer[Id].Reset();
         if (Socket != null)
         {
             Socket.Close();
         }
     }
References _isReading, NetMessage.buffer, ISocket.Close(), Id, IsActive, PendingTermination, PendingTerminationApproved, Player, Main.player, MessageBuffer.Reset(), ResetSections(), Socket, SpamClear(), State, StatusCount, StatusMax, StatusText, StatusText2, and TimeOutTimer.
Referenced by Netplay.InitializeServer(), Netplay.OnConnectionAccepted(), and Netplay.UpdateConnectedClients().