Terraria: RemoteClient.UpdateStatusText
UpdateStatusText()
void RemoteClient.UpdateStatusText () inline private
     {
         if (StatusMax > 0 && StatusText2 != "")
         {
             if (StatusCount >= StatusMax)
             {
                 StatusText = Language.GetTextValue("Net.ClientStatusComplete", Socket.GetRemoteAddress(), Name, StatusText2);
                 StatusText2 = "";
                 StatusMax = 0;
                 StatusCount = 0;
                 return;
             }
             StatusText = string.Concat("(", Socket.GetRemoteAddress(), ") ", Name, " ", StatusText2, ": ", (int)((float)StatusCount / (float)StatusMax * 100f), "%");
         }
         else if (State == 0)
         {
             StatusText = Language.GetTextValue("Net.ClientConnecting", $"({Socket.GetRemoteAddress()}) {Name}");
         }
         else if (State == 1)
         {
             StatusText = Language.GetTextValue("Net.ClientSendingData", Socket.GetRemoteAddress(), Name);
         }
         else if (State == 2)
         {
             StatusText = Language.GetTextValue("Net.ClientRequestedWorldInfo", Socket.GetRemoteAddress(), Name);
         }
         else if (State != 3 && State == 10)
         {
             try
             {
                 StatusText = Language.GetTextValue("Net.ClientPlaying", Socket.GetRemoteAddress(), Name);
             }
             catch (Exception)
             {
                 PendingTermination = true;
             }
         }
     }
References ISocket.GetRemoteAddress(), Language.GetTextValue(), Name, PendingTermination, Socket, State, StatusCount, StatusMax, StatusText, and StatusText2.
Referenced by Update().