Terraria: RemoteClient.SectionRange
SectionRange()
bool RemoteClient.SectionRange (int size, int firstX, int firstY) inline
     {
         for (int i = 0; i < 4; i++)
         {
             int num = firstX;
             int num2 = firstY;
             if (i == 1)
             {
                 num += size;
             }
             if (i == 2)
             {
                 num2 += size;
             }
             if (i == 3)
             {
                 num += size;
                 num2 += size;
             }
             int sectionX = Netplay.GetSectionX(num);
             int sectionY = Netplay.GetSectionY(num2);
             if (TileSections[sectionX, sectionY])
             {
                 return true;
             }
         }
         return false;
     }
References Netplay.GetSectionX(), Netplay.GetSectionY(), and TileSections.
Referenced by NetMessage.SendData().