Terraria: System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.BinarySearchTag
BinarySearchTag()
int System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.BinarySearchTag (uint searchCodedTag, ref ushort methodCount) inline private
Definition at line 71 of file MethodSemanticsTableReader.cs.
    {
        Block.BinarySearchReferenceRange(NumberOfRows, RowSize, _AssociationOffset, searchCodedTag, _IsHasSemanticRefSizeSmall, out var startRowNumber, out var endRowNumber);
        if (startRowNumber == -1)
        {
            methodCount = 0;
            return 0;
        }
        methodCount = (ushort)(endRowNumber - startRowNumber + 1);
        return startRowNumber + 1;
    }
References System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader._AssociationOffset, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader._IsHasSemanticRefSizeSmall, System.Reflection.Internal.MemoryBlock.BinarySearchReferenceRange(), System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.Block, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.NumberOfRows, and System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.RowSize.
Referenced by System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.FindSemanticMethodsForEvent(), and System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.FindSemanticMethodsForProperty().