Terraria: System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.GetMethod
GetMethod()
MethodDefinitionHandle System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.GetMethod (int rowId) inline package
Definition at line 39 of file MethodSemanticsTableReader.cs.
    {
        int num = (rowId - 1) * RowSize;
        return MethodDefinitionHandle.FromRowId(Block.PeekReference(num + _MethodOffset, _IsMethodTableRowRefSizeSmall));
    }
References System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader._IsMethodTableRowRefSizeSmall, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader._MethodOffset, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.Block, System.Reflection.Metadata.MethodDefinitionHandle.FromRowId(), System.Reflection.Internal.MemoryBlock.PeekReference(), and System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.RowSize.
Referenced by System.Reflection.Metadata.PropertyDefinition.GetAccessors().