Terraria: System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.MethodSemanticsTableReader
MethodSemanticsTableReader()
System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.MethodSemanticsTableReader (int numberOfRows, bool declaredSorted, int methodTableRowRefSize, int hasSemanticRefSize, MemoryBlock containingBlock, int containingBlockOffset) inline package
Definition at line 23 of file MethodSemanticsTableReader.cs.
    {
        NumberOfRows = numberOfRows;
        _IsMethodTableRowRefSizeSmall = methodTableRowRefSize == 2;
        _IsHasSemanticRefSizeSmall = hasSemanticRefSize == 2;
        _SemanticsFlagOffset = 0;
        _MethodOffset = _SemanticsFlagOffset + 2;
        _AssociationOffset = _MethodOffset + methodTableRowRefSize;
        RowSize = _AssociationOffset + hasSemanticRefSize;
        Block = containingBlock.GetMemoryBlockAt(containingBlockOffset, RowSize * numberOfRows);
        if (!declaredSorted && !CheckSorted())
        {
            Throw.TableNotSorted(TableIndex.MethodSemantics);
        }
    }
References System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader._AssociationOffset, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader._IsHasSemanticRefSizeSmall, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader._IsMethodTableRowRefSizeSmall, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader._MethodOffset, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader._SemanticsFlagOffset, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.Block, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.CheckSorted(), System.Reflection.Internal.MemoryBlock.GetMemoryBlockAt(), System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.NumberOfRows, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.RowSize, and System.Reflection.Throw.TableNotSorted().