Terraria: Liquid.DelWater
DelWater()
static void Liquid.DelWater (int l) inline static
     {
         int num = Main.liquid[l].x;
         int num2 = Main.liquid[l].y;
         Tile tile = Main.tile[num - 1, num2];
         Tile tile2 = Main.tile[num + 1, num2];
         Tile tile3 = Main.tile[num, num2 + 1];
         Tile tile4 = Main.tile[num, num2];
         byte b = 2;
         if (tile4.liquid < b)
         {
             tile4.liquid = 0;
             if (tile.liquid < b)
             {
                 tile.liquid = 0;
             }
             else
             {
                 AddWater(num - 1, num2);
             }
             if (tile2.liquid < b)
             {
                 tile2.liquid = 0;
             }
             else
             {
                 AddWater(num + 1, num2);
             }
         }
         else if (tile4.liquid < 20)
         {
             if ((tile.liquid < tile4.liquid && (!tile.nactive() || !Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type])) || (tile2.liquid < tile4.liquid && (!tile2.nactive() || !Main.tileSolid[tile2.type] || Main.tileSolidTop[tile2.type])) || (tile3.liquid < byte.MaxValue && (!tile3.nactive() || !Main.tileSolid[tile3.type] || Main.tileSolidTop[tile3.type])))
             {
                 tile4.liquid = 0;
             }
         }
         else if (tile3.liquid < byte.MaxValue && (!tile3.nactive() || !Main.tileSolid[tile3.type] || Main.tileSolidTop[tile3.type]) && !stuck && (!Main.tile[num, num2].nactive() || !Main.tileSolid[Main.tile[num, num2].type] || Main.tileSolidTop[Main.tile[num, num2].type]))
         {
             Main.liquid[l].kill = 0;
             return;
         }
         if (tile4.liquid < 250 && Main.tile[num, num2 - 1].liquid > 0)
         {
             AddWater(num, num2 - 1);
         }
         if (tile4.liquid == 0)
         {
             tile4.liquidType(0);
         }
         else
         {
             if (tile2.liquid > 0 && tile2.liquid < 250 && (!tile2.nactive() || !Main.tileSolid[tile2.type] || Main.tileSolidTop[tile2.type]) && tile4.liquid != tile2.liquid)
             {
                 AddWater(num + 1, num2);
             }
             if (tile.liquid > 0 && tile.liquid < 250 && (!tile.nactive() || !Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type]) && tile4.liquid != tile.liquid)
             {
                 AddWater(num - 1, num2);
             }
             if (tile4.lava())
             {
                 LavaCheck(num, num2);
                 for (int i = num - 1; i <= num + 1; i++)
                 {
                     for (int j = num2 - 1; j <= num2 + 1; j++)
                     {
                         Tile tile5 = Main.tile[i, j];
                         if (!tile5.active())
{
                             continue;
                         }
                         if (tile5.type == 2 || tile5.type == 23 || tile5.type == 109 || tile5.type == 199 || tile5.type == 477 || tile5.type == 492)
{
                             tile5.type = 0;
                             WorldGen.SquareTileFrame(i, j);
                             if (Main.netMode == 2)
{
                                 NetMessage.SendTileSquare(-1, num, num2, 3);
                             }
                         }
                         else if (tile5.type == 60 || tile5.type == 70 || tile5.type == 661 || tile5.type == 662)
{
                             tile5.type = 59;
                             WorldGen.SquareTileFrame(i, j);
                             if (Main.netMode == 2)
{
                                 NetMessage.SendTileSquare(-1, num, num2, 3);
                             }
                         }
                     }
                 }
             }
             else if (tile4.honey())
             {
                 HoneyCheck(num, num2);
             }
             else if (tile4.shimmer())
             {
                 ShimmerCheck(num, num2);
             }
         }
         if (Main.netMode == 2)
         {
             NetSendLiquid(num, num2);
         }
         numLiquid--;
         Main.tile[Main.liquid[l].x, Main.liquid[l].y].checkingLiquid(checkingLiquid: false);
         Main.liquid[l].x = Main.liquid[numLiquid].x;
         Main.liquid[l].y = Main.liquid[numLiquid].y;
         Main.liquid[l].kill = Main.liquid[numLiquid].kill;
         if (Main.tileAlch[tile4.type])
         {
             WorldGen.CheckAlch(num, num2);
         }
         else if (tile4.type == 518)
         {
             if (quickFall)
             {
                 WorldGen.CheckLilyPad(num, num2);
             }
             else if (Main.tile[num, num2 + 1].liquid < byte.MaxValue || Main.tile[num, num2 - 1].liquid > 0)
             {
                 WorldGen.SquareTileFrame(num, num2);
             }
             else
             {
                 WorldGen.CheckLilyPad(num, num2);
             }
         }
     }
References Tile.active(), AddWater(), WorldGen.CheckAlch(), Tile.checkingLiquid(), WorldGen.CheckLilyPad(), Tile.honey(), HoneyCheck(), Tile.lava(), LavaCheck(), Main.liquid, Tile.liquid, Tile.liquidType(), Tile.nactive(), Main.netMode, NetSendLiquid(), numLiquid, quickFall, NetMessage.SendTileSquare(), Tile.shimmer(), ShimmerCheck(), WorldGen.SquareTileFrame(), stuck, Main.tile, Main.tileAlch, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by UpdateLiquid().