Terraria: System.Xml.Xsl.IlGen.XmlILStateAnalyzer.AnalyzeCopy
AnalyzeCopy()
virtual void System.Xml.Xsl.IlGen.XmlILStateAnalyzer.AnalyzeCopy (QilNode ndCopy, XmlILConstructInfo info) inline protected virtual
Reimplemented in System.Xml.Xsl.IlGen.XmlILElementAnalyzer.
Definition at line 214 of file XmlILStateAnalyzer.cs.
    {
        XmlQueryType xmlType = ndCopy.XmlType;
        if (!xmlType.IsSingleton)
        {
            StartLoop(xmlType, info);
        }
        if (MaybeContent(xmlType))
        {
            if (MaybeAttrNmsp(xmlType))
            {
                if (xstates == PossibleXmlStates.EnumAttrs)
                {
                    xstates = PossibleXmlStates.Any;
                }
            }
            else if (xstates == PossibleXmlStates.EnumAttrs || withinElem)
            {
                xstates = PossibleXmlStates.WithinContent;
            }
        }
        if (!xmlType.IsSingleton)
        {
            EndLoop(xmlType, info);
        }
    }
References System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILStateAnalyzer.EndLoop(), System.info, System.Xml.Xsl.XmlQueryType.IsSingleton, System.Xml.Xsl.IlGen.XmlILStateAnalyzer.MaybeAttrNmsp(), System.Xml.Xsl.IlGen.XmlILStateAnalyzer.MaybeContent(), System.Xml.Xsl.IlGen.XmlILStateAnalyzer.StartLoop(), System.Xml.Xsl.IlGen.XmlILStateAnalyzer.withinElem, and System.Xml.Xsl.IlGen.XmlILStateAnalyzer.xstates.
Referenced by System.Xml.Xsl.IlGen.XmlILStateAnalyzer.AnalyzeContent().