Terraria: Liquid.QuickWater
QuickWater()
static void Liquid.QuickWater (int verbose = 0, int minY = -1, int maxY = -1) inline static
     {
         if (WorldGen.gen)
         {
             WorldGen.ShimmerRemoveWater();
             if (WorldGen.noTrapsWorldGen)
             {
                 Main.tileSolid[138] = false;
             }
         }
         Main.tileSolid[379] = true;
         tilesIgnoreWater(ignoreSolids: true);
         if (minY == -1)
         {
             minY = 3;
         }
         if (maxY == -1)
         {
             maxY = Main.maxTilesY - 3;
         }
         for (int num = maxY; num >= minY; num--)
         {
             UpdateProgressDisplay(verbose, minY, maxY, num);
             for (int i = 4; i < Main.maxTilesX - 4; i++)
             {
                 if (Main.tile[i, num].liquid != 0)
                 {
                     SettleWaterAt(i, num);
                 }
             }
         }
         tilesIgnoreWater(ignoreSolids: false);
         if (WorldGen.gen)
         {
             WorldGen.ShimmerRemoveWater();
             if (WorldGen.noTrapsWorldGen)
             {
                 Main.tileSolid[138] = true;
             }
         }
     }
References WorldGen.gen, Tile.liquid, Main.maxTilesX, Main.maxTilesY, WorldGen.noTrapsWorldGen, SettleWaterAt(), WorldGen.ShimmerRemoveWater(), Main.tile, tilesIgnoreWater(), Main.tileSolid, and UpdateProgressDisplay().
Referenced by UpdateLiquid().