Terraria: Liquid.AttemptToMoveLava
AttemptToMoveLava()
static void Liquid.AttemptToMoveLava (int X, int Y, bool tileAtXYHasLava) inline static private
     {
         if (Main.tile[X - 1, Y].liquid > 0 && Main.tile[X - 1, Y].lava() != tileAtXYHasLava)
         {
             if (tileAtXYHasLava)
             {
                 LavaCheck(X, Y);
             }
             else
             {
                 LavaCheck(X - 1, Y);
             }
         }
         else if (Main.tile[X + 1, Y].liquid > 0 && Main.tile[X + 1, Y].lava() != tileAtXYHasLava)
         {
             if (tileAtXYHasLava)
             {
                 LavaCheck(X, Y);
             }
             else
             {
                 LavaCheck(X + 1, Y);
             }
         }
         else if (Main.tile[X, Y - 1].liquid > 0 && Main.tile[X, Y - 1].lava() != tileAtXYHasLava)
         {
             if (tileAtXYHasLava)
             {
                 LavaCheck(X, Y);
             }
             else
             {
                 LavaCheck(X, Y - 1);
             }
         }
         else if (Main.tile[X, Y + 1].liquid > 0 && Main.tile[X, Y + 1].lava() != tileAtXYHasLava)
         {
             if (tileAtXYHasLava)
             {
                 LavaCheck(X, Y);
             }
             else
             {
                 LavaCheck(X, Y + 1);
             }
         }
     }
References Tile.lava(), LavaCheck(), Tile.liquid, Main.tile, X, and Y.
Referenced by SettleWaterAt().