Terraria: System.Xml.Xsl.IlGen.XmlILStateAnalyzer.Analyze
Analyze()
virtual QilNode System.Xml.Xsl.IlGen.XmlILStateAnalyzer.Analyze (QilNode ndConstr, QilNode ndContent) inline virtual
Reimplemented in System.Xml.Xsl.IlGen.XmlILElementAnalyzer.
Definition at line 20 of file XmlILStateAnalyzer.cs.
    {
        if (ndConstr == null)
        {
            parentInfo = null;
            xstates = PossibleXmlStates.WithinSequence;
            withinElem = false;
            ndContent = AnalyzeContent(ndContent);
        }
        else
        {
            parentInfo = XmlILConstructInfo.Write(ndConstr);
            if (ndConstr.NodeType == QilNodeType.Function)
            {
                parentInfo.ConstructMethod = XmlILConstructMethod.Writer;
                PossibleXmlStates possibleXmlStates = PossibleXmlStates.None;
                foreach (XmlILConstructInfo item in parentInfo.CallersInfo)
                {
                    if (possibleXmlStates == PossibleXmlStates.None)
                    {
                        possibleXmlStates = item.InitialStates;
                    }
                    else if (possibleXmlStates != item.InitialStates)
                    {
                        possibleXmlStates = PossibleXmlStates.Any;
                    }
                    item.PushToWriterFirst = true;
                }
                parentInfo.InitialStates = possibleXmlStates;
            }
            else
            {
                if (ndConstr.NodeType != QilNodeType.Choice)
                {
                    XmlILConstructInfo xmlILConstructInfo2 = parentInfo;
                    PossibleXmlStates initialStates = (parentInfo.FinalStates = PossibleXmlStates.WithinSequence);
                    xmlILConstructInfo2.InitialStates = initialStates;
                }
                if (ndConstr.NodeType != QilNodeType.RtfCtor)
                {
                    parentInfo.ConstructMethod = XmlILConstructMethod.WriterThenIterator;
                }
            }
            withinElem = ndConstr.NodeType == QilNodeType.ElementCtor;
            switch (ndConstr.NodeType)
            {
            case QilNodeType.DocumentCtor:
                xstates = PossibleXmlStates.WithinContent;
                break;
            case QilNodeType.ElementCtor:
                xstates = PossibleXmlStates.EnumAttrs;
                break;
            case QilNodeType.AttributeCtor:
                xstates = PossibleXmlStates.WithinAttr;
                break;
            case QilNodeType.CommentCtor:
                xstates = PossibleXmlStates.WithinComment;
                break;
            case QilNodeType.PICtor:
                xstates = PossibleXmlStates.WithinPI;
                break;
            case QilNodeType.XsltCopy:
                xstates = PossibleXmlStates.Any;
                break;
            case QilNodeType.Function:
                xstates = parentInfo.InitialStates;
                break;
            case QilNodeType.RtfCtor:
                xstates = PossibleXmlStates.WithinContent;
                break;
            case QilNodeType.Choice:
                xstates = PossibleXmlStates.Any;
                break;
            }
            if (ndContent != null)
            {
                ndContent = AnalyzeContent(ndContent);
            }
            if (ndConstr.NodeType == QilNodeType.Choice)
            {
                AnalyzeChoice(ndConstr as QilChoice, parentInfo);
            }
            if (ndConstr.NodeType == QilNodeType.Function)
            {
                parentInfo.FinalStates = xstates;
            }
        }
        return ndContent;
    }
References System.Xml.Xsl.IlGen.XmlILStateAnalyzer.AnalyzeChoice(), System.Xml.Xsl.IlGen.XmlILStateAnalyzer.AnalyzeContent(), System.Xml.Xsl.IlGen.XmlILConstructInfo.CallersInfo, System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILConstructInfo.InitialStates, System.item, System.Xml.Xsl.IlGen.XmlILStateAnalyzer.parentInfo, System.Xml.Xsl.IlGen.XmlILStateAnalyzer.withinElem, System.Xml.Xsl.IlGen.XmlILConstructInfo.Write(), and System.Xml.Xsl.IlGen.XmlILStateAnalyzer.xstates.
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAttributeCtor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitChoice(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitCommentCtor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocumentCtor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNamespaceDecl(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitPICtor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitQilExpression(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitRawTextCtor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitRtfCtor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitTextCtor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitXsltCopy(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitXsltCopyOf().