Terraria: System.Reflection.Internal.MemoryBlock.BuildPtrTable
BuildPtrTable()
int[] System.Reflection.Internal.MemoryBlock.BuildPtrTable (int numberOfRows, int rowSize, int referenceOffset, bool isReferenceSmall) inline package
Definition at line 629 of file MemoryBlock.cs.
    {
        int[] array = new int[numberOfRows];
        uint[] unsortedReferences = new uint[numberOfRows];
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = i + 1;
        }
        ReadColumn(unsortedReferences, rowSize, referenceOffset, isReferenceSmall);
        Array.Sort(array, (int a, int b) => unsortedReferences[a - 1].CompareTo(unsortedReferences[b - 1]));
        return array;
    }
References System.array, System.Reflection.Internal.MemoryBlock.ReadColumn(), and System.Array.Sort().
Referenced by System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.CustomAttributeTableReader().