Terraria: System.Reflection.Internal.MemoryBlock.PeekCompressedInteger
PeekCompressedInteger()
unsafe int System.Reflection.Internal.MemoryBlock.PeekCompressedInteger (int offset, out int numberOfBytesRead) inline package
Definition at line 132 of file MemoryBlock.cs.
    {
        CheckBounds(offset, 0);
        byte* ptr = Pointer + offset;
        long num = Length - offset;
        if (num == 0L)
        {
            numberOfBytesRead = 0;
            return int.MaxValue;
        }
        byte b = *ptr;
        if ((b & 0x80) == 0)
        {
            numberOfBytesRead = 1;
            return b;
        }
        if ((b & 0x40) == 0)
        {
            if (num >= 2)
            {
                numberOfBytesRead = 2;
                return ((b & 0x3F) << 8) | ptr[1];
            }
        }
        else if ((b & 0x20) == 0 && num >= 4)
        {
            numberOfBytesRead = 4;
            return ((b & 0x1F) << 24) | (ptr[1] << 16) | (ptr[2] << 8) | ptr[3];
        }
        numberOfBytesRead = 0;
        return int.MaxValue;
    }
References System.Reflection.Internal.MemoryBlock.CheckBounds(), System.L, System.Reflection.Internal.MemoryBlock.Length, and System.offset.
Referenced by System.Reflection.Metadata.Ecma335.BlobHeap.GetBytes(), System.Reflection.Internal.MemoryBlock.PeekHeapValueOffsetAndSize(), System.Reflection.Metadata.BlobReader.ReadCompressedIntegerOrInvalid(), and System.Reflection.Metadata.BlobReader.TryReadCompressedSignedInteger().