Terraria: System.Reflection.Internal.MemoryBlock.PeekUInt32
PeekUInt32()
unsafe uint System.Reflection.Internal.MemoryBlock.PeekUInt32 (int offset) inline package
Definition at line 125 of file MemoryBlock.cs.
    {
        CheckBounds(offset, 4);
        byte* ptr = Pointer + offset;
        return (uint)(*ptr | (ptr[1] << 8) | (ptr[2] << 16) | (ptr[3] << 24));
    }
References System.Reflection.Internal.MemoryBlock.CheckBounds(), and System.offset.
Referenced by System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.GetClassSize(), System.Reflection.Metadata.Ecma335.LocalScopeTableReader.GetEndOffset(), System.Reflection.Metadata.Ecma335.AssemblyTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.FileTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.ExportedTypeTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.ManifestResourceTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.EnCLogTableReader.GetFuncCode(), System.Reflection.Metadata.Ecma335.AssemblyTableReader.GetHashAlgorithm(), System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.GetOffset(), System.Reflection.Metadata.Ecma335.ManifestResourceTableReader.GetOffset(), System.Reflection.Metadata.Ecma335.EnCLogTableReader.GetToken(), System.Reflection.Metadata.Ecma335.EnCMapTableReader.GetToken(), System.Reflection.Internal.MemoryBlock.PeekHeapReference(), System.Reflection.Internal.MemoryBlock.PeekInt32(), System.Reflection.Internal.MemoryBlock.PeekReference(), and System.Reflection.Internal.MemoryBlock.PeekReferenceUnchecked().