Terraria: System.Reflection.Internal.MemoryBlock.PeekUInt16
PeekUInt16()
unsafe ushort System.Reflection.Internal.MemoryBlock.PeekUInt16 (int offset) inline package
Definition at line 166 of file MemoryBlock.cs.
    {
        CheckBounds(offset, 2);
        byte* ptr = Pointer + offset;
        return (ushort)(*ptr | (ptr[1] << 8));
    }
References System.Reflection.Internal.MemoryBlock.CheckBounds(), and System.offset.
Referenced by System.Reflection.Metadata.Ecma335.DeclSecurityTableReader.GetAction(), System.Reflection.Metadata.Ecma335.LocalVariableTableReader.GetAttributes(), System.Reflection.Metadata.Ecma335.EventTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.FieldTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.GenericParamTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.MethodTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.ParamTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.PropertyTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.ModuleTableReader.GetGeneration(), System.Reflection.Metadata.Ecma335.MethodTableReader.GetImplFlags(), System.Reflection.Metadata.Ecma335.ImplMapTableReader.GetImport(), System.Reflection.Metadata.Ecma335.LocalVariableTableReader.GetIndex(), System.Reflection.Metadata.Ecma335.GenericParamTableReader.GetNumber(), System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.GetPackingSize(), System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.GetSemantics(), System.Reflection.Metadata.Ecma335.ParamTableReader.GetSequence(), System.Reflection.Metadata.Ecma335.AssemblyTableReader.GetVersion(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.GetVersion(), System.Reflection.Internal.MemoryBlock.PeekHeapReference(), System.Reflection.Internal.MemoryBlock.PeekReference(), and System.Reflection.Internal.MemoryBlock.PeekReferenceUnchecked().