Terraria: System.Reflection.Internal.MemoryBlock.IsOrderedByReferenceAscending
IsOrderedByReferenceAscending()
bool System.Reflection.Internal.MemoryBlock.IsOrderedByReferenceAscending (int rowSize, int referenceOffset, bool isReferenceSmall) inline package
Definition at line 612 of file MemoryBlock.cs.
    {
        int i = referenceOffset;
        int length = Length;
        uint num = 0u;
        for (; i < length; i += rowSize)
        {
            uint num2 = PeekReferenceUnchecked(i, isReferenceSmall);
            if (num2 < num)
            {
                return false;
            }
            num = num2;
        }
        return true;
    }
References System.length, System.Reflection.Internal.MemoryBlock.Length, and System.Reflection.Internal.MemoryBlock.PeekReferenceUnchecked().
Referenced by System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.ConstantTableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.DeclSecurityTableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.FieldRVATableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.GenericParamConstraintTableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.GenericParamTableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.ImplMapTableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.MethodImplTableReader.CheckSorted(), System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.CheckSorted(), and System.Reflection.Metadata.Ecma335.NestedClassTableReader.CheckSorted().