Terraria: System.Reflection.Internal.MemoryBlock.PeekReference
PeekReference()
int System.Reflection.Internal.MemoryBlock.PeekReference (int offset, bool smallRefSize) inline package
Definition at line 187 of file MemoryBlock.cs.
    {
        if (smallRefSize)
        {
            return PeekUInt16(offset);
        }
        uint num = PeekUInt32(offset);
        if (!TokenTypeIds.IsValidRowId(num))
        {
            Throw.ReferenceOverflow();
        }
        return (int)num;
    }
References System.Reflection.Metadata.Ecma335.TokenTypeIds.IsValidRowId(), System.offset, System.Reflection.Internal.MemoryBlock.PeekUInt16(), System.Reflection.Internal.MemoryBlock.PeekUInt32(), and System.Reflection.Throw.ReferenceOverflow().
Referenced by System.Reflection.Metadata.Ecma335.NestedClassTableReader.FindEnclosingType(), System.Reflection.Metadata.Ecma335.MethodImplTableReader.GetClass(), System.Reflection.Metadata.Ecma335.LocalScopeTableReader.GetConstantStart(), System.Reflection.Metadata.Ecma335.MethodDebugInformationTableReader.GetDocument(), System.Reflection.Metadata.Ecma335.NestedClassTableReader.GetEnclosingClass(), System.Reflection.Metadata.Ecma335.EventPtrTableReader.GetEventFor(), System.Reflection.Metadata.Ecma335.EventMapTableReader.GetEventListStartFor(), System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.GetField(), System.Reflection.Metadata.Ecma335.FieldPtrTableReader.GetFieldFor(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFieldStart(), System.Reflection.Metadata.Ecma335.ImplMapTableReader.GetImport(), System.Reflection.Metadata.Ecma335.LocalScopeTableReader.GetImportScope(), System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader.GetKickoffMethod(), System.Reflection.Metadata.Ecma335.LocalScopeTableReader.GetMethod(), System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.GetMethod(), System.Reflection.Metadata.Ecma335.MethodPtrTableReader.GetMethodFor(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetMethodStart(), System.Reflection.Metadata.Ecma335.ExportedTypeTableReader.GetNamespace(), System.Reflection.Metadata.Ecma335.NestedClassTableReader.GetNestedClass(), System.Reflection.Metadata.Ecma335.GenericParamConstraintTableReader.GetOwner(), System.Reflection.Metadata.Ecma335.ParamPtrTableReader.GetParamFor(), System.Reflection.Metadata.Ecma335.MethodTableReader.GetParamStart(), System.Reflection.Metadata.Ecma335.ImportScopeTableReader.GetParent(), System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.GetParent(), System.Reflection.Metadata.Ecma335.EventMapTableReader.GetParentType(), System.Reflection.Metadata.Ecma335.PropertyMapTableReader.GetParentType(), System.Reflection.Metadata.Ecma335.PropertyPtrTableReader.GetPropertyFor(), System.Reflection.Metadata.Ecma335.PropertyMapTableReader.GetPropertyListStartFor(), and System.Reflection.Metadata.Ecma335.LocalScopeTableReader.GetVariableStart().