Terraria: System.Reflection.Internal.MemoryBlock.GetDebuggerDisplay
GetDebuggerDisplay() [3/3]
string System.Reflection.Internal.MemoryBlock.GetDebuggerDisplay (out int displayedBytes) inline package
Definition at line 72 of file MemoryBlock.cs.
    {
        displayedBytes = Math.Min(Length, 64);
        string text = BitConverter.ToString(PeekBytes(0, displayedBytes));
        if (displayedBytes < Length)
        {
            text += "-...";
        }
        return text;
    }
References System.Reflection.Internal.MemoryBlock.Length, System.Math.Min(), System.Reflection.Internal.MemoryBlock.PeekBytes(), System.text, and System.BitConverter.ToString().