Terraria: System.Reflection.Internal.MemoryBlock.GetMemoryBlockAt
GetMemoryBlockAt()
unsafe MemoryBlock System.Reflection.Internal.MemoryBlock.GetMemoryBlockAt (int offset, int length) inline package
Definition at line 102 of file MemoryBlock.cs.
    {
        CheckBounds(offset, length);
        return new MemoryBlock(Pointer + offset, length);
    }
References System.Reflection.Internal.MemoryBlock.MemoryBlock(), System.Reflection.Internal.MemoryBlock.CheckBounds(), System.length, and System.offset.
Referenced by System.Reflection.Metadata.Ecma335.AssemblyOSTableReader.AssemblyOSTableReader(), System.Reflection.Metadata.Ecma335.AssemblyProcessorTableReader.AssemblyProcessorTableReader(), System.Reflection.Metadata.Ecma335.AssemblyRefOSTableReader.AssemblyRefOSTableReader(), System.Reflection.Metadata.Ecma335.AssemblyRefProcessorTableReader.AssemblyRefProcessorTableReader(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.AssemblyRefTableReader(), System.Reflection.Metadata.Ecma335.AssemblyTableReader.AssemblyTableReader(), System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.ClassLayoutTableReader(), System.Reflection.Metadata.Ecma335.ConstantTableReader.ConstantTableReader(), System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.CustomAttributeTableReader(), System.Reflection.Metadata.Ecma335.CustomDebugInformationTableReader.CustomDebugInformationTableReader(), System.Reflection.Metadata.Ecma335.DeclSecurityTableReader.DeclSecurityTableReader(), System.Reflection.Metadata.Ecma335.DocumentTableReader.DocumentTableReader(), System.Reflection.Metadata.Ecma335.EnCLogTableReader.EnCLogTableReader(), System.Reflection.Metadata.Ecma335.EnCMapTableReader.EnCMapTableReader(), System.Reflection.Metadata.Ecma335.EventMapTableReader.EventMapTableReader(), System.Reflection.Metadata.Ecma335.EventPtrTableReader.EventPtrTableReader(), System.Reflection.Metadata.Ecma335.EventTableReader.EventTableReader(), System.Reflection.Metadata.Ecma335.ExportedTypeTableReader.ExportedTypeTableReader(), System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.FieldLayoutTableReader(), System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.FieldMarshalTableReader(), System.Reflection.Metadata.Ecma335.FieldPtrTableReader.FieldPtrTableReader(), System.Reflection.Metadata.Ecma335.FieldRVATableReader.FieldRVATableReader(), System.Reflection.Metadata.Ecma335.FieldTableReader.FieldTableReader(), System.Reflection.Metadata.Ecma335.FileTableReader.FileTableReader(), System.Reflection.Metadata.Ecma335.GenericParamConstraintTableReader.GenericParamConstraintTableReader(), System.Reflection.Metadata.Ecma335.GenericParamTableReader.GenericParamTableReader(), System.Reflection.Metadata.Ecma335.ImplMapTableReader.ImplMapTableReader(), System.Reflection.Metadata.Ecma335.ImportScopeTableReader.ImportScopeTableReader(), System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.InterfaceImplTableReader(), System.Reflection.Metadata.Ecma335.LocalConstantTableReader.LocalConstantTableReader(), System.Reflection.Metadata.Ecma335.LocalScopeTableReader.LocalScopeTableReader(), System.Reflection.Metadata.Ecma335.LocalVariableTableReader.LocalVariableTableReader(), System.Reflection.Metadata.Ecma335.ManifestResourceTableReader.ManifestResourceTableReader(), System.Reflection.Metadata.Ecma335.MemberRefTableReader.MemberRefTableReader(), System.Reflection.Metadata.Ecma335.MethodDebugInformationTableReader.MethodDebugInformationTableReader(), System.Reflection.Metadata.Ecma335.MethodImplTableReader.MethodImplTableReader(), System.Reflection.Metadata.Ecma335.MethodPtrTableReader.MethodPtrTableReader(), System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.MethodSemanticsTableReader(), System.Reflection.Metadata.Ecma335.MethodSpecTableReader.MethodSpecTableReader(), System.Reflection.Metadata.Ecma335.MethodTableReader.MethodTableReader(), System.Reflection.Metadata.Ecma335.ModuleRefTableReader.ModuleRefTableReader(), System.Reflection.Metadata.Ecma335.ModuleTableReader.ModuleTableReader(), System.Reflection.Metadata.Ecma335.NestedClassTableReader.NestedClassTableReader(), System.Reflection.Metadata.Ecma335.ParamPtrTableReader.ParamPtrTableReader(), System.Reflection.Metadata.Ecma335.ParamTableReader.ParamTableReader(), System.Reflection.Metadata.Ecma335.PropertyMapTableReader.PropertyMapTableReader(), System.Reflection.Metadata.Ecma335.PropertyPtrTableReader.PropertyPtrTableReader(), System.Reflection.Metadata.Ecma335.PropertyTableReader.PropertyTableReader(), System.Reflection.Metadata.Ecma335.StandAloneSigTableReader.StandAloneSigTableReader(), System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader.StateMachineMethodTableReader(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.TypeDefTableReader(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.TypeRefTableReader(), System.Reflection.Metadata.Ecma335.TypeSpecTableReader.TypeSpecTableReader(), System.Reflection.Metadata.Ecma335.BlobHeap.GetMemoryBlock(), and System.Reflection.Metadata.Ecma335.StringHeap.TrimEnd().