Terraria: System.Reflection.Internal.MemoryBlock.Utf8NullTerminatedFastCompare
Utf8NullTerminatedFastCompare()
unsafe FastComparisonResult System.Reflection.Internal.MemoryBlock.Utf8NullTerminatedFastCompare (int offset, string text, int textStart, out int firstDifferenceIndex, char terminator, bool ignoreCase) inline package
Definition at line 323 of file MemoryBlock.cs.
    {
        CheckBounds(offset, 0);
        byte* ptr = Pointer + offset;
        byte* ptr2 = Pointer + Length;
        byte* ptr3 = ptr;
        int ignoreCaseMask = StringUtils.IgnoreCaseMask(ignoreCase);
        int num = textStart;
        while (num < text.Length && ptr3 != ptr2)
        {
            byte b = *ptr3;
            if (b == 0 || b == terminator)
            {
                break;
            }
            char c = text[num];
            if ((b & 0x80) == 0 && StringUtils.IsEqualAscii(c, b, ignoreCaseMask))
            {
                num++;
                ptr3++;
                continue;
            }
            firstDifferenceIndex = num;
            if (c <= '\u007f')
            {
                return FastComparisonResult.Unequal;
            }
            return FastComparisonResult.Inconclusive;
        }
        firstDifferenceIndex = num;
        bool flag = num == text.Length;
        bool flag2 = ptr3 == ptr2 || *ptr3 == 0 || *ptr3 == terminator;
        if (flag && flag2)
        {
            return FastComparisonResult.Equal;
        }
        if (!flag)
        {
            return FastComparisonResult.TextStartsWithBytes;
        }
        return FastComparisonResult.BytesStartWithText;
    }
References System.Reflection.Internal.MemoryBlock.CheckBounds(), System.Reflection.Metadata.StringUtils.IgnoreCaseMask(), System.Reflection.Metadata.StringUtils.IsEqualAscii(), System.Reflection.Internal.MemoryBlock.Length, System.offset, and System.text.
Referenced by System.Reflection.Metadata.Ecma335.BlobHeap.DocumentNameEquals(), System.Reflection.Internal.MemoryBlock.Utf8NullTerminatedEquals(), and System.Reflection.Internal.MemoryBlock.Utf8NullTerminatedStartsWith().