Terraria: System.Reflection.Internal.MemoryBlock.PeekInt32
PeekInt32()
int System.Reflection.Internal.MemoryBlock.PeekInt32 (int offset) inline package
Definition at line 114 of file MemoryBlock.cs.
    {
        uint num = PeekUInt32(offset);
        if ((int)num != num)
        {
            Throw.ValueOverflow();
        }
        return (int)num;
    }
References System.offset, System.Reflection.Internal.MemoryBlock.PeekUInt32(), and System.Reflection.Throw.ValueOverflow().
Referenced by System.Reflection.Metadata.Ecma335.LocalScopeTableReader.GetLength(), System.Reflection.Metadata.Ecma335.FieldRVATableReader.GetRva(), System.Reflection.Metadata.Ecma335.MethodTableReader.GetRva(), System.Reflection.Metadata.Ecma335.LocalScopeTableReader.GetStartOffset(), and System.Reflection.Metadata.Ecma335.ExportedTypeTableReader.GetTypeDefId().