Terraria: System.Reflection.Internal.MemoryBlock.GetUtf8NullTerminatedLength
GetUtf8NullTerminatedLength()
unsafe int System.Reflection.Internal.MemoryBlock.GetUtf8NullTerminatedLength (int offset, out int numberOfBytesRead, char terminator = '\0') inline package
Definition at line 250 of file MemoryBlock.cs.
    {
        CheckBounds(offset, 0);
        byte* ptr = Pointer + offset;
        byte* ptr2 = Pointer + Length;
        byte* ptr3;
        for (ptr3 = ptr; ptr3 < ptr2; ptr3++)
        {
            byte b = *ptr3;
            if (b == 0 || b == terminator)
            {
                break;
            }
        }
        int result = (numberOfBytesRead = (int)(ptr3 - ptr));
        if (ptr3 < ptr2)
        {
            numberOfBytesRead++;
        }
        return result;
    }
References System.Reflection.Internal.MemoryBlock.CheckBounds(), System.Reflection.Internal.MemoryBlock.Length, and System.offset.
Referenced by System.Reflection.Metadata.Ecma335.StringHeap.GetNonVirtualStringMemoryBlock(), and System.Reflection.Internal.MemoryBlock.PeekUtf8NullTerminated().