Terraria: System.Reflection.Internal.MemoryBlock.PeekTaggedReference
PeekTaggedReference()
uint System.Reflection.Internal.MemoryBlock.PeekTaggedReference (int offset, bool smallRefSize) inline package
Definition at line 173 of file MemoryBlock.cs.
    {
        return PeekReferenceUnchecked(offset, smallRefSize);
    }
References System.offset, and System.Reflection.Internal.MemoryBlock.PeekReferenceUnchecked().
Referenced by System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.GetAssociation(), System.Reflection.Metadata.Ecma335.MemberRefTableReader.GetClass(), System.Reflection.Metadata.Ecma335.GenericParamConstraintTableReader.GetConstraint(), System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetConstructor(), System.Reflection.Metadata.Ecma335.EventTableReader.GetEventType(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(), System.Reflection.Metadata.Ecma335.ExportedTypeTableReader.GetImplementation(), System.Reflection.Metadata.Ecma335.ManifestResourceTableReader.GetImplementation(), System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.GetInterface(), System.Reflection.Metadata.Ecma335.ImplMapTableReader.GetMemberForwarded(), System.Reflection.Metadata.Ecma335.MethodSpecTableReader.GetMethod(), System.Reflection.Metadata.Ecma335.MethodImplTableReader.GetMethodBody(), System.Reflection.Metadata.Ecma335.MethodImplTableReader.GetMethodDeclaration(), System.Reflection.Metadata.Ecma335.GenericParamTableReader.GetOwner(), System.Reflection.Metadata.Ecma335.ConstantTableReader.GetParent(), System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetParent(), System.Reflection.Metadata.Ecma335.CustomDebugInformationTableReader.GetParent(), System.Reflection.Metadata.Ecma335.DeclSecurityTableReader.GetParent(), System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.GetParent(), and System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetResolutionScope().