Terraria: System.Reflection.Internal.MemoryBlock.BinarySearchReference
BinarySearchReference() [1/2]
int System.Reflection.Internal.MemoryBlock.BinarySearchReference (int rowCount, int rowSize, int referenceOffset, uint referenceValue, bool isReferenceSmall) inline package
Definition at line 510 of file MemoryBlock.cs.
    {
        int num = 0;
        int num2 = rowCount - 1;
        while (num <= num2)
        {
            int num3 = (num + num2) / 2;
            uint num4 = PeekReferenceUnchecked(num3 * rowSize + referenceOffset, isReferenceSmall);
            if (referenceValue > num4)
            {
                num = num3 + 1;
                continue;
            }
            if (referenceValue < num4)
            {
                num2 = num3 - 1;
                continue;
            }
            return num3;
        }
        return -1;
    }
References System.Reflection.Internal.MemoryBlock.PeekReferenceUnchecked().
Referenced by System.Reflection.Internal.MemoryBlock.BinarySearchReferenceRange(), System.Reflection.Internal.MemoryBlock.BinarySearchReferenceRange(), System.Reflection.Metadata.Ecma335.ImplMapTableReader.BinarySearchTag(), System.Reflection.Metadata.Ecma335.ConstantTableReader.FindConstant(), System.Reflection.Metadata.Ecma335.NestedClassTableReader.FindEnclosingType(), System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.FindFieldLayoutRowId(), System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.FindFieldMarshalRowId(), System.Reflection.Metadata.Ecma335.FieldRVATableReader.FindFieldRvaRowId(), System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader.FindKickoffMethod(), and System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.FindRow().