Terraria: System.Reflection.Internal.MemoryBlock.PeekHeapReference
PeekHeapReference()
int System.Reflection.Internal.MemoryBlock.PeekHeapReference (int offset, bool smallRefSize) inline package
Definition at line 201 of file MemoryBlock.cs.
    {
        if (smallRefSize)
        {
            return PeekUInt16(offset);
        }
        uint num = PeekUInt32(offset);
        if (!HeapHandleType.IsValidHeapOffset(num))
        {
            Throw.ReferenceOverflow();
        }
        return (int)num;
    }
References System.Reflection.Metadata.Ecma335.HeapHandleType.IsValidHeapOffset(), System.offset, System.Reflection.Internal.MemoryBlock.PeekUInt16(), System.Reflection.Internal.MemoryBlock.PeekUInt32(), and System.Reflection.Throw.ReferenceOverflow().
Referenced by System.Reflection.Metadata.Ecma335.AssemblyTableReader.GetCulture(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.GetCulture(), System.Reflection.Metadata.Ecma335.ModuleTableReader.GetEncBaseId(), System.Reflection.Metadata.Ecma335.ModuleTableReader.GetEncId(), System.Reflection.Metadata.Ecma335.DocumentTableReader.GetHash(), System.Reflection.Metadata.Ecma335.DocumentTableReader.GetHashAlgorithm(), System.Reflection.Metadata.Ecma335.FileTableReader.GetHashValue(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.GetHashValue(), System.Reflection.Metadata.Ecma335.ImplMapTableReader.GetImport(), System.Reflection.Metadata.Ecma335.ImportScopeTableReader.GetImports(), System.Reflection.Metadata.Ecma335.MethodSpecTableReader.GetInstantiation(), System.Reflection.Metadata.Ecma335.CustomDebugInformationTableReader.GetKind(), System.Reflection.Metadata.Ecma335.DocumentTableReader.GetLanguage(), System.Reflection.Metadata.Ecma335.ModuleTableReader.GetMvid(), System.Reflection.Metadata.Ecma335.AssemblyTableReader.GetName(), System.Reflection.Metadata.Ecma335.ModuleTableReader.GetName(), System.Reflection.Metadata.Ecma335.FileTableReader.GetName(), System.Reflection.Metadata.Ecma335.DocumentTableReader.GetName(), System.Reflection.Metadata.Ecma335.EventTableReader.GetName(), System.Reflection.Metadata.Ecma335.FieldTableReader.GetName(), System.Reflection.Metadata.Ecma335.GenericParamTableReader.GetName(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.LocalConstantTableReader.GetName(), System.Reflection.Metadata.Ecma335.LocalVariableTableReader.GetName(), System.Reflection.Metadata.Ecma335.ManifestResourceTableReader.GetName(), System.Reflection.Metadata.Ecma335.MemberRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.MethodTableReader.GetName(), System.Reflection.Metadata.Ecma335.ModuleRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.ParamTableReader.GetName(), System.Reflection.Metadata.Ecma335.PropertyTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetNamespace(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetNamespace(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetNamespaceDefinition(), System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.GetNativeType(), System.Reflection.Metadata.Ecma335.DeclSecurityTableReader.GetPermissionSet(), System.Reflection.Metadata.Ecma335.AssemblyTableReader.GetPublicKey(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.GetPublicKeyOrToken(), System.Reflection.Metadata.Ecma335.MethodDebugInformationTableReader.GetSequencePoints(), System.Reflection.Metadata.Ecma335.FieldTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.StandAloneSigTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.LocalConstantTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.MemberRefTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.MethodTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.PropertyTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.TypeSpecTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.ExportedTypeTableReader.GetTypeName(), System.Reflection.Metadata.Ecma335.ExportedTypeTableReader.GetTypeNamespace(), System.Reflection.Metadata.Ecma335.ExportedTypeTableReader.GetTypeNamespaceString(), System.Reflection.Metadata.Ecma335.ConstantTableReader.GetValue(), System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetValue(), and System.Reflection.Metadata.Ecma335.CustomDebugInformationTableReader.GetValue().