Terraria: System.Reflection.Internal.MemoryBlock.BinarySearchForSlot
BinarySearchForSlot()
int System.Reflection.Internal.MemoryBlock.BinarySearchForSlot (int rowCount, int rowSize, int referenceListOffset, uint referenceValue, bool isReferenceSmall) inline package
Definition at line 459 of file MemoryBlock.cs.
    {
        int num = 0;
        int num2 = rowCount - 1;
        uint num3 = PeekReferenceUnchecked(num * rowSize + referenceListOffset, isReferenceSmall);
        uint num4 = PeekReferenceUnchecked(num2 * rowSize + referenceListOffset, isReferenceSmall);
        if (num2 == 1)
        {
            if (referenceValue >= num4)
            {
                return num2;
            }
            return num;
        }
        while (num2 - num > 1)
        {
            if (referenceValue <= num3)
            {
                if (referenceValue != num3)
                {
                    return num - 1;
                }
                return num;
            }
            if (referenceValue >= num4)
            {
                if (referenceValue != num4)
                {
                    return num2 + 1;
                }
                return num2;
            }
            int num5 = (num + num2) / 2;
            uint num6 = PeekReferenceUnchecked(num5 * rowSize + referenceListOffset, isReferenceSmall);
            if (referenceValue > num6)
            {
                num = num5;
                num3 = num6;
                continue;
            }
            if (referenceValue < num6)
            {
                num2 = num5;
                num4 = num6;
                continue;
            }
            return num5;
        }
        return num;
    }
References System.Reflection.Internal.MemoryBlock.PeekReferenceUnchecked().
Referenced by System.Reflection.Metadata.Ecma335.TypeDefTableReader.FindTypeContainingField(), and System.Reflection.Metadata.Ecma335.TypeDefTableReader.FindTypeContainingMethod().