Terraria: System.Reflection.Internal.MemoryBlock.CompareUtf8NullTerminatedStringWithAsciiString
CompareUtf8NullTerminatedStringWithAsciiString()
unsafe int System.Reflection.Internal.MemoryBlock.CompareUtf8NullTerminatedStringWithAsciiString (int offset, string asciiString) inline package
Definition at line 385 of file MemoryBlock.cs.
    {
        CheckBounds(offset, 0);
        byte* ptr = Pointer + offset;
        int num = Length - offset;
        for (int i = 0; i < asciiString.Length; i++)
        {
            if (i > num)
            {
                return -1;
            }
            if (*ptr != asciiString[i])
            {
                return *ptr - asciiString[i];
            }
            ptr++;
        }
        if (*ptr != 0)
        {
            return 1;
        }
        return 0;
    }
References System.Reflection.Internal.MemoryBlock.CheckBounds(), System.Reflection.Internal.MemoryBlock.Length, and System.offset.
Referenced by System.Reflection.Internal.MemoryBlock.BinarySearch(), and System.Reflection.Metadata.Ecma335.StringHeap.EqualsRaw().