Terraria: System.Reflection.Internal.MemoryBlock.GetDebuggerDisplay
GetDebuggerDisplay() [1/3]
unsafe string System.Reflection.Internal.MemoryBlock.GetDebuggerDisplay () inline private
Definition at line 62 of file MemoryBlock.cs.
    {
        if (Pointer == null)
        {
            return "<null>";
        }
        int displayedBytes;
        return GetDebuggerDisplay(out displayedBytes);
    }
References System.Reflection.Internal.MemoryBlock.GetDebuggerDisplay().
Referenced by System.Reflection.Internal.MemoryBlock.GetDebuggerDisplay(), System.Reflection.Metadata.BlobReader.GetDebuggerDisplay(), and System.Reflection.Internal.MemoryBlock.GetDebuggerDisplay().