Terraria: System.Runtime.Loader.AssemblyLoadContext.GetRuntimeAssembly
GetRuntimeAssembly()
static RuntimeAssembly System.Runtime.Loader.AssemblyLoadContext.GetRuntimeAssembly (Assembly asm) inline static private inherited
Definition at line 311 of file AssemblyLoadContext.cs.
    {
        if (!(asm == null))
        {
            if (!(asm is RuntimeAssembly result))
            {
                if (!(asm is AssemblyBuilder assemblyBuilder))
                {
                    return null;
                }
                return assemblyBuilder.InternalAssembly;
            }
            return result;
        }
        return null;
    }
Referenced by System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(), System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(), and System.Runtime.Loader.AssemblyLoadContext.ValidateAssemblyNameWithSimpleName().