Terraria: System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath
LoadFromAssemblyPath()
Assembly System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath (string assemblyPath) inline inherited
Definition at line 437 of file AssemblyLoadContext.cs.
    {
        if (assemblyPath == null)
        {
            throw new ArgumentNullException("assemblyPath");
        }
        if (PathInternal.IsPartiallyQualified(assemblyPath))
        {
            throw new ArgumentException(SR.Format(SR.Argument_AbsolutePathRequired, assemblyPath), "assemblyPath");
        }
        lock (_unloadLock)
        {
            VerifyIsAlive();
            return InternalLoadFromPath(assemblyPath, null);
        }
    }
References System.Runtime.Loader.AssemblyLoadContext._unloadLock, System.SR.Argument_AbsolutePathRequired, System.SR.Format(), System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(), System.IO.PathInternal.IsPartiallyQualified(), and System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive().
Referenced by Internal.Runtime.InteropServices.IsolatedComponentLoadContext.Load().