Terraria: System.Runtime.Loader.AssemblyLoadContext.ValidateAssemblyNameWithSimpleName
ValidateAssemblyNameWithSimpleName()
static Assembly System.Runtime.Loader.AssemblyLoadContext.ValidateAssemblyNameWithSimpleName (Assembly assembly, string requestedSimpleName) inline static private inherited
Definition at line 628 of file AssemblyLoadContext.cs.
    {
        if (string.IsNullOrEmpty(requestedSimpleName))
        {
            throw new ArgumentException(SR.ArgumentNull_AssemblyNameName);
        }
        string value = null;
        RuntimeAssembly runtimeAssembly = GetRuntimeAssembly(assembly);
        if (runtimeAssembly != null)
        {
            value = runtimeAssembly.GetSimpleName();
        }
        if (string.IsNullOrEmpty(value) || !requestedSimpleName.Equals(value, StringComparison.InvariantCultureIgnoreCase))
        {
            throw new InvalidOperationException(SR.Argument_CustomAssemblyLoadContextRequestedNameMismatch);
        }
        return assembly;
    }
References System.SR.Argument_CustomAssemblyLoadContextRequestedNameMismatch, System.SR.ArgumentNull_AssemblyNameName, System.Runtime.Loader.AssemblyLoadContext.GetRuntimeAssembly(), and System.value.
Referenced by System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(), and System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad().