Terraria: System.Runtime.Loader.AssemblyLoadContext.GetLoadContext
GetLoadContext()
static ? AssemblyLoadContext System.Runtime.Loader.AssemblyLoadContext.GetLoadContext (Assembly assembly) inline static inherited
Definition at line 284 of file AssemblyLoadContext.cs.
    {
        if (assembly == null)
        {
            throw new ArgumentNullException("assembly");
        }
        AssemblyLoadContext result = null;
        RuntimeAssembly runtimeAssembly = GetRuntimeAssembly(assembly);
        if (runtimeAssembly != null)
        {
            RuntimeAssembly assembly2 = runtimeAssembly;
            IntPtr loadContextForAssembly = GetLoadContextForAssembly(new QCallAssembly(ref assembly2));
            result = ((!(loadContextForAssembly == IntPtr.Zero)) ? ((AssemblyLoadContext)GCHandle.FromIntPtr(loadContextForAssembly).Target) : Default);
        }
        return result;
    }
References System.Runtime.Loader.AssemblyLoadContext.AssemblyLoadContext(), System.Runtime.Loader.AssemblyLoadContext.Default, System.Runtime.InteropServices.GCHandle.FromIntPtr(), System.Runtime.Loader.AssemblyLoadContext.GetLoadContextForAssembly(), System.Runtime.Loader.AssemblyLoadContext.GetRuntimeAssembly(), and System.IntPtr.Zero.
Referenced by System.Runtime.Loader.AssemblyLoadContext.EnterContextualReflection(), System.Reflection.Assembly.LoadFromResolveHandler(), and System.Runtime.Loader.AssemblyLoadContext.ResolveSatelliteAssembly().