Terraria: System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent
GetFirstResolvedAssemblyFromResolvingEvent()
Assembly System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent (AssemblyName assemblyName) inline private inherited
Definition at line 604 of file AssemblyLoadContext.cs.
    {
        Assembly assembly = null;
        Func<AssemblyLoadContext, AssemblyName, Assembly> resolving = this._resolving;
        if (resolving != null)
        {
            Delegate[] invocationList = resolving.GetInvocationList();
            for (int i = 0; i < invocationList.Length; i++)
            {
                Func<AssemblyLoadContext, AssemblyName, Assembly> func = (Func<AssemblyLoadContext, AssemblyName, Assembly>)invocationList[i];
                assembly = func(this, assemblyName);
                if (IsTracingEnabled())
                {
                    TraceResolvingHandlerInvoked(assemblyName.FullName, func.Method.Name, (this != Default) ? ToString() : Name, assembly?.FullName, (assembly != null && !assembly.IsDynamic) ? assembly.Location : null);
                }
                if (assembly != null)
                {
                    return assembly;
                }
            }
        }
        return null;
    }
References System.Runtime.Loader.AssemblyLoadContext._resolving, System.Runtime.Loader.AssemblyLoadContext.Default, System.Runtime.Loader.AssemblyLoadContext.IsTracingEnabled(), System.Runtime.Loader.AssemblyLoadContext.Name, System.Runtime.Loader.AssemblyLoadContext.ToString(), and System.Runtime.Loader.AssemblyLoadContext.TraceResolvingHandlerInvoked().
Referenced by System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent().