Terraria: System.Runtime.Loader.AssemblyLoadContext.SetCurrentContextualReflectionContext
SetCurrentContextualReflectionContext()
static void System.Runtime.Loader.AssemblyLoadContext.SetCurrentContextualReflectionContext (AssemblyLoadContext value) inline static private inherited
Definition at line 569 of file AssemblyLoadContext.cs.
    {
        if (s_asyncLocalCurrent == null)
        {
            Interlocked.CompareExchange(ref s_asyncLocalCurrent, new AsyncLocal<AssemblyLoadContext>(), null);
        }
        s_asyncLocalCurrent.Value = value;
    }
References System.Threading.Interlocked.CompareExchange(), System.Runtime.Loader.AssemblyLoadContext.s_asyncLocalCurrent, and System.value.
Referenced by System.Runtime.Loader.AssemblyLoadContext.ContextualReflectionScope.ContextualReflectionScope(), and System.Runtime.Loader.AssemblyLoadContext.ContextualReflectionScope.Dispose().