Terraria: System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath
LoadUnmanagedDllFromPath()
IntPtr System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath (string unmanagedDllPath) inline protected inherited
Definition at line 510 of file AssemblyLoadContext.cs.
    {
        if (unmanagedDllPath == null)
        {
            throw new ArgumentNullException("unmanagedDllPath");
        }
        if (unmanagedDllPath.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyPath, "unmanagedDllPath");
        }
        if (PathInternal.IsPartiallyQualified(unmanagedDllPath))
        {
            throw new ArgumentException(SR.Format(SR.Argument_AbsolutePathRequired, unmanagedDllPath), "unmanagedDllPath");
        }
        return NativeLibrary.Load(unmanagedDllPath);
    }
References System.SR.Argument_AbsolutePathRequired, System.SR.Argument_EmptyPath, System.SR.Format(), System.IO.PathInternal.IsPartiallyQualified(), and System.Runtime.InteropServices.NativeLibrary.Load().
Referenced by Internal.Runtime.InteropServices.IsolatedComponentLoadContext.LoadUnmanagedDll().