Terraria: System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent
InvokeResolveEvent()
static RuntimeAssembly System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent (ResolveEventHandler eventHandler, RuntimeAssembly assembly, string name) inline static private inherited
Definition at line 690 of file AssemblyLoadContext.cs.
    {
        if (eventHandler == null)
        {
            return null;
        }
        ResolveEventArgs args = new ResolveEventArgs(name, assembly);
        Delegate[] invocationList = eventHandler.GetInvocationList();
        for (int i = 0; i < invocationList.Length; i++)
        {
            ResolveEventHandler resolveEventHandler = (ResolveEventHandler)invocationList[i];
            Assembly assembly2 = resolveEventHandler(AppDomain.CurrentDomain, args);
            if (eventHandler == AssemblyLoadContext.AssemblyResolve && IsTracingEnabled())
            {
                TraceAssemblyResolveHandlerInvoked(name, resolveEventHandler.Method.Name, assembly2?.FullName, (assembly2 != null && !assembly2.IsDynamic) ? assembly2.Location : null);
            }
            RuntimeAssembly runtimeAssembly = GetRuntimeAssembly(assembly2);
            if (runtimeAssembly != null)
            {
                return runtimeAssembly;
            }
        }
        return null;
    }
References System.Runtime.Loader.AssemblyLoadContext.AssemblyResolve, System.AppDomain.CurrentDomain, System.Runtime.Loader.AssemblyLoadContext.GetRuntimeAssembly(), System.Runtime.Loader.AssemblyLoadContext.IsTracingEnabled(), System.ResolveEventHandler(), and System.Runtime.Loader.AssemblyLoadContext.TraceAssemblyResolveHandlerInvoked().
Referenced by System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(), System.Runtime.Loader.AssemblyLoadContext.OnResourceResolve(), and System.Runtime.Loader.AssemblyLoadContext.OnTypeResolve().