Terraria: System.Runtime.Loader.AssemblyLoadContext.ResolveSatelliteAssembly
ResolveSatelliteAssembly() [1/2]
Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveSatelliteAssembly (AssemblyName assemblyName) inline private inherited
Definition at line 717 of file AssemblyLoadContext.cs.
    {
        if (assemblyName.Name == null || !assemblyName.Name.EndsWith(".resources", StringComparison.Ordinal))
        {
            return null;
        }
        string assemblyName2 = assemblyName.Name.Substring(0, assemblyName.Name.Length - ".resources".Length);
        Assembly assembly = LoadFromAssemblyName(new AssemblyName(assemblyName2));
        AssemblyLoadContext loadContext = GetLoadContext(assembly);
        string directoryName = Path.GetDirectoryName(assembly.Location);
        if (directoryName == null)
        {
            return null;
        }
        string text = Path.Combine(directoryName, assemblyName.CultureName, assemblyName.Name + ".dll");
        bool flag = FileSystem.FileExists(text);
        if (flag || PathInternal.IsCaseSensitive)
        {
        }
        Assembly result = (flag ? loadContext.LoadFromAssemblyPath(text) : null);
        if (IsTracingEnabled())
        {
            TraceSatelliteSubdirectoryPathProbed(text, (!flag) ? (-2147024894) : 0);
        }
        return result;
    }
References System.IO.Path.Combine(), System.IO.FileSystem.FileExists(), System.IO.Path.GetDirectoryName(), System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(), System.IO.PathInternal.IsCaseSensitive, System.Runtime.Loader.AssemblyLoadContext.IsTracingEnabled(), System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(), System.text, and System.Runtime.Loader.AssemblyLoadContext.TraceSatelliteSubdirectoryPathProbed().