Terraria: System.Runtime.Loader.AssemblyLoadContext.AssemblyLoadContext
AssemblyLoadContext() [4/4]
System.Runtime.Loader.AssemblyLoadContext.AssemblyLoadContext (bool representsTPALoadContext, bool isCollectible, string name) inline protected
Definition at line 359 of file AssemblyLoadContext.cs.
    {
        _isCollectible = isCollectible;
        _name = name;
        _unloadLock = new object();
        if (!isCollectible)
        {
            GC.SuppressFinalize(this);
        }
        _nativeAssemblyLoadContext = InitializeAssemblyLoadContext(GCHandle.ToIntPtr(GCHandle.Alloc(this, IsCollectible ? GCHandleType.WeakTrackResurrection : GCHandleType.Normal)), representsTPALoadContext, isCollectible);
        Dictionary<long, WeakReference<AssemblyLoadContext>> allContexts = AllContexts;
        lock (allContexts)
        {
            _id = s_nextId++;
            allContexts.Add(_id, new WeakReference<AssemblyLoadContext>(this, trackResurrection: true));
        }
    }
References System.Runtime.Loader.AssemblyLoadContext._id, System.Runtime.Loader.AssemblyLoadContext._isCollectible, System.Runtime.Loader.AssemblyLoadContext._name, System.Runtime.Loader.AssemblyLoadContext._nativeAssemblyLoadContext, System.Runtime.Loader.AssemblyLoadContext._unloadLock, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Loader.AssemblyLoadContext.AllContexts, System.Runtime.InteropServices.GCHandle.Alloc(), System.Runtime.Loader.AssemblyLoadContext.InitializeAssemblyLoadContext(), System.Runtime.Loader.AssemblyLoadContext.IsCollectible, System.Runtime.Loader.AssemblyLoadContext.s_nextId, System.GC.SuppressFinalize(), and System.Runtime.InteropServices.GCHandle.ToIntPtr().