Terraria: System.Runtime.Loader.AssemblyLoadContext.AssemblyLoadContext
AssemblyLoadContext() [1/4]
System.Runtime.Loader.AssemblyLoadContext.AssemblyLoadContext () inline protected
Definition at line 344 of file AssemblyLoadContext.cs.
        : this(representsTPALoadContext: false, isCollectible: false, null)
    {
    }
Referenced by System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(), System.Runtime.Loader.AssemblyLoadContext.Resolve(), System.Runtime.Loader.AssemblyLoadContext.ResolveSatelliteAssembly(), System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(), System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDllUsingEvent(), and System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent().