Terraria: System.Runtime.Loader.AssemblyLoadContext.InitiateUnload
InitiateUnload()
void System.Runtime.Loader.AssemblyLoadContext.InitiateUnload () inline private inherited
Definition at line 390 of file AssemblyLoadContext.cs.
    {
        RaiseUnloadEvent();
        lock (_unloadLock)
        {
            GCHandle value = GCHandle.Alloc(this, GCHandleType.Normal);
            IntPtr ptrAssemblyLoadContextStrong = GCHandle.ToIntPtr(value);
            PrepareForAssemblyLoadContextRelease(_nativeAssemblyLoadContext, ptrAssemblyLoadContextStrong);
            _state = InternalState.Unloading;
        }
        Dictionary<long, WeakReference<AssemblyLoadContext>> allContexts = AllContexts;
        lock (allContexts)
        {
            allContexts.Remove(_id);
        }
    }
References System.Runtime.Loader.AssemblyLoadContext._id, System.Runtime.Loader.AssemblyLoadContext._nativeAssemblyLoadContext, System.Runtime.Loader.AssemblyLoadContext._state, System.Runtime.Loader.AssemblyLoadContext._unloadLock, System.Runtime.Loader.AssemblyLoadContext.AllContexts, System.Runtime.InteropServices.GCHandle.Alloc(), System.Runtime.Loader.AssemblyLoadContext.PrepareForAssemblyLoadContextRelease(), System.Runtime.Loader.AssemblyLoadContext.RaiseUnloadEvent(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Runtime.InteropServices.GCHandle.ToIntPtr(), and System.value.
Referenced by System.Runtime.Loader.AssemblyLoadContext.~AssemblyLoadContext(), and System.Runtime.Loader.AssemblyLoadContext.Unload().