Terraria: System.Threading.ThreadPoolBoundHandleOverlapped.ThreadPoolBoundHandleOverlapped
ThreadPoolBoundHandleOverlapped()
unsafe System.Threading.ThreadPoolBoundHandleOverlapped.ThreadPoolBoundHandleOverlapped (IOCompletionCallback callback, object state, object pinData, PreAllocatedOverlapped preAllocated, bool flowExecutionContext) inline
Definition at line 19 of file ThreadPoolBoundHandleOverlapped.cs.
    {
        _userCallback = callback;
        _userState = state;
        _preAllocated = preAllocated;
        _nativeOverlapped = (flowExecutionContext ? Pack(s_completionCallback, pinData) : UnsafePack(s_completionCallback, pinData));
        _nativeOverlapped->OffsetLow = 0;
        _nativeOverlapped->OffsetHigh = 0;
    }
References System.Threading.ThreadPoolBoundHandleOverlapped._nativeOverlapped, System.Threading.ThreadPoolBoundHandleOverlapped._preAllocated, System.Threading.ThreadPoolBoundHandleOverlapped._userCallback, System.Threading.ThreadPoolBoundHandleOverlapped._userState, System.Threading.NativeOverlapped.OffsetHigh, System.Threading.NativeOverlapped.OffsetLow, System.Threading.Overlapped.Pack(), System.Threading.ThreadPoolBoundHandleOverlapped.s_completionCallback, System.state, and System.Threading.Overlapped.UnsafePack().
Referenced by System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback().