Terraria: System.Net.CredentialCache.Add
Add() [2/2]
void System.Net.CredentialCache.Add (Uri uriPrefix, string authType, NetworkCredential cred) inline
Definition at line 165 of file CredentialCache.cs.
    {
        if (uriPrefix == null)
        {
            throw new ArgumentNullException("uriPrefix");
        }
        if (authType == null)
        {
            throw new ArgumentNullException("authType");
        }
        if (cred is SystemNetworkCredential && !string.Equals(authType, "NTLM", StringComparison.OrdinalIgnoreCase) && !string.Equals(authType, "Kerberos", StringComparison.OrdinalIgnoreCase) && !string.Equals(authType, "Negotiate", StringComparison.OrdinalIgnoreCase))
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_nodefaultcreds, authType), "authType");
        }
        _version++;
        CredentialKey credentialKey = new CredentialKey(uriPrefix, authType);
        if (NetEventSource.Log.IsEnabled())
        {
            NetEventSource.Info(this, $"Adding key:[{credentialKey}], cred:[{cred.Domain}],[{cred.UserName}]", "Add");
        }
        if (_cache == null)
        {
            _cache = new Dictionary<CredentialKey, NetworkCredential>();
        }
        _cache.Add(credentialKey, cred);
    }
References System.Net.CredentialCache._cache, System.Net.CredentialCache._version, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Equals, System.SR.Format(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.SR.net_nodefaultcreds.