Terraria: System.Net.CredentialCache.GetCredential
GetCredential() [1/2]
NetworkCredential? System.Net.CredentialCache.GetCredential (string host, int port, string authenticationType) inline
Implements System.Net.ICredentialsByHost.
Definition at line 313 of file CredentialCache.cs.
    {
        if (host == null)
        {
            throw new ArgumentNullException("host");
        }
        if (authenticationType == null)
        {
            throw new ArgumentNullException("authenticationType");
        }
        if (host.Length == 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_emptystringcall, "host"), "host");
        }
        if (port < 0)
        {
            throw new ArgumentOutOfRangeException("port");
        }
        if (_cacheForHosts == null)
        {
            if (NetEventSource.Log.IsEnabled())
            {
                NetEventSource.Info(this, "CredentialCache::GetCredential short-circuiting because the dictionary is null.", "GetCredential");
            }
            return null;
        }
        CredentialHostKey key = new CredentialHostKey(host, port, authenticationType);
        NetworkCredential value = null;
        _cacheForHosts.TryGetValue(key, out value);
        if (NetEventSource.Log.IsEnabled())
        {
            NetEventSource.Info(this, FormattableStringFactory.Create("Returning {0}", (value == null) ? "null" : ("(" + value.UserName + ":" + value.Domain + ")")), "GetCredential");
        }
        return value;
    }
References System.Net.CredentialCache._cacheForHosts, System.Runtime.CompilerServices.FormattableStringFactory.Create(), System.SR.Format(), System.Net.NetEventSource.Info(), System.key, System.Net.NetEventSource.Log, System.SR.net_emptystringcall, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.