Terraria: System.Xml.XmlAsyncCheckReader.ReadSubtree
ReadSubtree()
override XmlReader System.Xml.XmlAsyncCheckReader.ReadSubtree () inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 738 of file XmlAsyncCheckReader.cs.
    {
        CheckAsync();
        XmlReader reader = _coreReader.ReadSubtree();
        return CreateAsyncCheckWrapper(reader);
    }
References System.Xml.XmlAsyncCheckReader._coreReader, System.Xml.XmlAsyncCheckReader.CheckAsync(), System.Xml.XmlAsyncCheckReader.CreateAsyncCheckWrapper(), and System.Xml.XmlReader.ReadSubtree().