Terraria: System.Net.Security.SslSessionsCache.CacheCredential
CacheCredential()
static void System.Net.Security.SslSessionsCache.CacheCredential (SafeFreeCredentials creds, byte[] thumbPrint, SslProtocols sslProtocols, bool isServer, EncryptionPolicy encryptionPolicy) inline static package
Definition at line 130 of file SslSessionsCache.cs.
    {
        if (creds.IsInvalid)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(null, $"Refused to cache an Invalid Handle {creds}, Current Cache Count = {s_cachedCreds.Count}", "CacheCredential");
            }
            return;
        }
        SslCredKey key = new SslCredKey(thumbPrint, (int)sslProtocols, isServer, encryptionPolicy);
        SafeFreeCredentials cachedCredential = GetCachedCredential(key);
        if (cachedCredential == null || cachedCredential.IsClosed || cachedCredential.IsInvalid)
        {
            lock (s_cachedCreds)
            {
                cachedCredential = GetCachedCredential(key);
                if (cachedCredential == null || cachedCredential.IsClosed || cachedCredential.IsInvalid)
                {
                    SafeCredentialReference safeCredentialReference = SafeCredentialReference.CreateReference(creds);
                    if (safeCredentialReference != null)
                    {
                        s_cachedCreds[key] = safeCredentialReference;
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(null, $"Caching New Handle = {creds}, Current Cache Count = {s_cachedCreds.Count}", "CacheCredential");
                        }
                        ShrinkCredentialCache();
                    }
                }
                else if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(null, $"CacheCredential() (locked retry) Found already cached Handle = {cachedCredential}", "CacheCredential");
                }
                return;
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(null, $"CacheCredential() Ignoring incoming handle = {creds} since found already cached Handle = {cachedCredential}", "CacheCredential");
        }
        static void ShrinkCredentialCache()
        {
            if (s_cachedCreds.Count % 32 == 0)
            {
                KeyValuePair<SslCredKey, SafeCredentialReference>[] array = s_cachedCreds.ToArray();
                for (int i = 0; i < array.Length; i++)
                {
                    SafeCredentialReference value = array[i].Value;
                    SafeFreeCredentials target = value.Target;
                    SafeCredentialReference value2;
                    if (target == null)
                    {
                        s_cachedCreds.TryRemove(array[i].Key, out value2);
                    }
                    else
                    {
                        value.Dispose();
                        value = SafeCredentialReference.CreateReference(target);
                        if (value != null)
{
                            s_cachedCreds[array[i].Key] = value;
                        }
                        else
{
                            s_cachedCreds.TryRemove(array[i].Key, out value2);
                        }
                    }
                }
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(null, $"Scavenged cache, New Cache Count = {s_cachedCreds.Count}", "CacheCredential");
                }
            }
        }
    }
References System.array, System.Net.Security.SafeCredentialReference.CreateReference(), System.Net.Security.SslSessionsCache.GetCachedCredential(), System.Net.NetEventSource.Info(), System.key, System.Net.NetEventSource.Log, System.Net.Security.SslSessionsCache.s_cachedCreds, and System.value.
Referenced by System.Net.Security.SecureChannel.GenerateToken().