Terraria: System.Xml.XmlAsyncCheckReader.CheckAsync
CheckAsync()
void System.Xml.XmlAsyncCheckReader.CheckAsync () inline private inherited
Definition at line 304 of file XmlAsyncCheckReader.cs.
    {
        if (!_lastTask.IsCompleted)
        {
            throw new InvalidOperationException(System.SR.Xml_AsyncIsRunningException);
        }
    }
References System.Xml.XmlAsyncCheckReader._lastTask, System.Threading.Tasks.Task< TResult >.IsCompleted, and System.SR.Xml_AsyncIsRunningException.
Referenced by System.Xml.XmlAsyncCheckReader.Close(), System.Xml.XmlAsyncCheckReader.Dispose(), System.Xml.XmlAsyncCheckReader.GetAttribute(), System.Xml.XmlAsyncCheckReader.GetAttribute(), System.Xml.XmlAsyncCheckReader.GetAttribute(), System.Xml.XmlAsyncCheckReader.GetValueAsync(), System.Xml.XmlAsyncCheckReader.IsStartElement(), System.Xml.XmlAsyncCheckReader.IsStartElement(), System.Xml.XmlAsyncCheckReader.IsStartElement(), System.Xml.XmlAsyncCheckReader.LookupNamespace(), System.Xml.XmlAsyncCheckReader.MoveToAttribute(), System.Xml.XmlAsyncCheckReader.MoveToAttribute(), System.Xml.XmlAsyncCheckReader.MoveToAttribute(), System.Xml.XmlAsyncCheckReader.MoveToContent(), System.Xml.XmlAsyncCheckReader.MoveToContentAsync(), System.Xml.XmlAsyncCheckReader.MoveToElement(), System.Xml.XmlAsyncCheckReader.MoveToFirstAttribute(), System.Xml.XmlAsyncCheckReader.MoveToNextAttribute(), System.Xml.XmlAsyncCheckReader.Read(), System.Xml.XmlAsyncCheckReader.ReadAsync(), System.Xml.XmlAsyncCheckReader.ReadAttributeValue(), System.Xml.XmlAsyncCheckReader.ReadContentAs(), System.Xml.XmlAsyncCheckReader.ReadContentAsAsync(), System.Xml.XmlAsyncCheckReader.ReadContentAsBase64(), System.Xml.XmlAsyncCheckReader.ReadContentAsBase64Async(), System.Xml.XmlAsyncCheckReader.ReadContentAsBinHex(), System.Xml.XmlAsyncCheckReader.ReadContentAsBinHexAsync(), System.Xml.XmlAsyncCheckReader.ReadContentAsBoolean(), System.Xml.XmlAsyncCheckReader.ReadContentAsDateTime(), System.Xml.XmlAsyncCheckReader.ReadContentAsDateTimeOffset(), System.Xml.XmlAsyncCheckReader.ReadContentAsDecimal(), System.Xml.XmlAsyncCheckReader.ReadContentAsDouble(), System.Xml.XmlAsyncCheckReader.ReadContentAsFloat(), System.Xml.XmlAsyncCheckReader.ReadContentAsInt(), System.Xml.XmlAsyncCheckReader.ReadContentAsLong(), System.Xml.XmlAsyncCheckReader.ReadContentAsObject(), System.Xml.XmlAsyncCheckReader.ReadContentAsObjectAsync(), System.Xml.XmlAsyncCheckReader.ReadContentAsString(), System.Xml.XmlAsyncCheckReader.ReadContentAsStringAsync(), System.Xml.XmlAsyncCheckReader.ReadElementContentAs(), System.Xml.XmlAsyncCheckReader.ReadElementContentAs(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsAsync(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsBase64(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsBase64Async(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsBinHex(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsBinHexAsync(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsBoolean(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsBoolean(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsDateTime(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsDateTime(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsDecimal(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsDecimal(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsDouble(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsDouble(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsFloat(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsFloat(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsInt(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsInt(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsLong(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsLong(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsObject(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsObject(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsObjectAsync(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsString(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsString(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsStringAsync(), System.Xml.XmlAsyncCheckReader.ReadElementString(), System.Xml.XmlAsyncCheckReader.ReadElementString(), System.Xml.XmlAsyncCheckReader.ReadElementString(), System.Xml.XmlAsyncCheckReader.ReadEndElement(), System.Xml.XmlAsyncCheckReader.ReadInnerXml(), System.Xml.XmlAsyncCheckReader.ReadInnerXmlAsync(), System.Xml.XmlAsyncCheckReader.ReadOuterXml(), System.Xml.XmlAsyncCheckReader.ReadOuterXmlAsync(), System.Xml.XmlAsyncCheckReader.ReadStartElement(), System.Xml.XmlAsyncCheckReader.ReadStartElement(), System.Xml.XmlAsyncCheckReader.ReadStartElement(), System.Xml.XmlAsyncCheckReader.ReadString(), System.Xml.XmlAsyncCheckReader.ReadSubtree(), System.Xml.XmlAsyncCheckReader.ReadToDescendant(), System.Xml.XmlAsyncCheckReader.ReadToDescendant(), System.Xml.XmlAsyncCheckReader.ReadToFollowing(), System.Xml.XmlAsyncCheckReader.ReadToFollowing(), System.Xml.XmlAsyncCheckReader.ReadToNextSibling(), System.Xml.XmlAsyncCheckReader.ReadToNextSibling(), System.Xml.XmlAsyncCheckReader.ReadValueChunk(), System.Xml.XmlAsyncCheckReader.ReadValueChunkAsync(), System.Xml.XmlAsyncCheckReader.ResolveEntity(), System.Xml.XmlAsyncCheckReader.Skip(), and System.Xml.XmlAsyncCheckReader.SkipAsync().