Terraria: System.Runtime.Serialization.Json.JsonClassDataContract.JsonClassDataContractCriticalHelper.CopyMembersAndCheckDuplicateNames
CopyMembersAndCheckDuplicateNames()
void System.Runtime.Serialization.Json.JsonClassDataContract.JsonClassDataContractCriticalHelper.CopyMembersAndCheckDuplicateNames () inline private
Definition at line 59 of file JsonClassDataContract.cs.
        {
            if (_traditionalClassDataContract.MemberNames == null)
            {
                return;
            }
            int num = _traditionalClassDataContract.MemberNames.Length;
            Dictionary<string, object> dictionary = new Dictionary<string, object>(num);
            XmlDictionaryString[] array = new XmlDictionaryString[num];
            for (int i = 0; i < num; i++)
            {
                if (dictionary.ContainsKey(_traditionalClassDataContract.MemberNames[i].Value))
                {
                    throw new SerializationException(System.SR.Format(System.SR.JsonDuplicateMemberNames, DataContract.GetClrTypeFullName(_traditionalClassDataContract.UnderlyingType), _traditionalClassDataContract.MemberNames[i].Value));
                }
                dictionary.Add(_traditionalClassDataContract.MemberNames[i].Value, null);
                array[i] = DataContractJsonSerializer.ConvertXmlNameToJsonName(_traditionalClassDataContract.MemberNames[i]);
            }
            _memberNames = array;
        }
References System.Runtime.Serialization.Json.JsonClassDataContract.JsonClassDataContractCriticalHelper._memberNames, System.Runtime.Serialization.Json.JsonClassDataContract.JsonClassDataContractCriticalHelper._traditionalClassDataContract, System.array, System.Runtime.Serialization.Json.DataContractJsonSerializer.ConvertXmlNameToJsonName(), System.dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.JsonDuplicateMemberNames, System.Runtime.Serialization.ClassDataContract.MemberNames, System.Runtime.Serialization.DataContract.UnderlyingType, and System.Xml.XmlDictionaryString.Value.
Referenced by System.Runtime.Serialization.Json.JsonClassDataContract.JsonClassDataContractCriticalHelper.JsonClassDataContractCriticalHelper().