Terraria: System.Net.Security.SslSessionsCache.TryCachedCredential
TryCachedCredential()
static SafeFreeCredentials System.Net.Security.SslSessionsCache.TryCachedCredential (byte[] thumbPrint, SslProtocols sslProtocols, bool isServer, EncryptionPolicy encryptionPolicy) inline static package
Definition at line 94 of file SslSessionsCache.cs.
    {
        if (s_cachedCreds.IsEmpty)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(null, $"Not found, Current Cache Count = {s_cachedCreds.Count}", "TryCachedCredential");
            }
            return null;
        }
        SslCredKey key = new SslCredKey(thumbPrint, (int)sslProtocols, isServer, encryptionPolicy);
        SafeFreeCredentials cachedCredential = GetCachedCredential(key);
        if (cachedCredential == null || cachedCredential.IsClosed || cachedCredential.IsInvalid)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(null, $"Not found or invalid, Current Cache Coun = {s_cachedCreds.Count}", "TryCachedCredential");
            }
            return null;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(null, $"Found a cached Handle = {cachedCredential}", "TryCachedCredential");
        }
        return cachedCredential;
    }
References System.Net.Security.SslSessionsCache.GetCachedCredential(), System.Net.NetEventSource.Info(), System.key, System.Net.NetEventSource.Log, and System.Net.Security.SslSessionsCache.s_cachedCreds.
Referenced by System.Net.Security.SecureChannel.AcquireClientCredentials(), and System.Net.Security.SecureChannel.AcquireServerCredentials().