Terraria: System.Xml.XmlAsyncCheckReader.CreateAsyncCheckWrapper
CreateAsyncCheckWrapper()
static XmlAsyncCheckReader System.Xml.XmlAsyncCheckReader.CreateAsyncCheckWrapper (XmlReader reader) inline static inherited
Definition at line 278 of file XmlAsyncCheckReader.cs.
    {
        if (reader is IXmlLineInfo)
        {
            if (reader is IXmlNamespaceResolver)
            {
                if (reader is IXmlSchemaInfo)
                {
                    return new XmlAsyncCheckReaderWithLineInfoNSSchema(reader);
                }
                return new XmlAsyncCheckReaderWithLineInfoNS(reader);
            }
            return new XmlAsyncCheckReaderWithLineInfo(reader);
        }
        if (reader is IXmlNamespaceResolver)
        {
            return new XmlAsyncCheckReaderWithNS(reader);
        }
        return new XmlAsyncCheckReader(reader);
    }
References System.Xml.XmlAsyncCheckReader.XmlAsyncCheckReader(), and System.Xml.Dictionary.
Referenced by System.Xml.XmlReaderSettings.CreateReader(), System.Xml.XmlReaderSettings.CreateReader(), System.Xml.XmlReaderSettings.CreateReader(), System.Xml.XmlReader.CreateSqlReader(), and System.Xml.XmlAsyncCheckReader.ReadSubtree().