Terraria: System.Data.DataError.Clear
Clear() [2/2]
void System.Data.DataError.Clear (DataColumn column) inline package
Definition at line 87 of file DataError.cs.
    {
        if (_count == 0)
        {
            return;
        }
        for (int i = 0; i < _count; i++)
        {
            if (_errorList[i]._column == column)
            {
                Array.Copy(_errorList, i + 1, _errorList, i, _count - i - 1);
                _count--;
                column._errors--;
            }
        }
    }
References System.Data.DataError._count, System.Data.DataError._errorList, System.Data.DataColumn._errors, and System.Array.Copy().
Referenced by System.Data.DataRow.ClearError(), and System.Data.DataRow.ClearErrors().