Terraria: SceneMetrics.IsValidForOreFinder
IsValidForOreFinder()
static bool SceneMetrics.IsValidForOreFinder (Tile t) inline static
     {
         if (t.type == 227 && (t.frameX < 272 || t.frameX > 374))
         {
             return false;
         }
         if (t.type == 129 && t.frameX < 324)
         {
             return false;
         }
         return Main.tileOreFinderPriority[t.type] > 0;
     }
References Tile.frameX, Main.tileOreFinderPriority, and Tile.type.
Referenced by NPC.AI_112_FairyCritter(), NPC.GetFairyTreasureCoords(), and UpdateOreFinderData().