Terraria: System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64
ConvertToVector256Int64() [9/12]
static Vector256< long > System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64 (Vector128< sbyte > value) inline static inherited
Definition at line 612 of file Avx2.cs.
    {
        return ConvertToVector256Int64(value);
    }
References System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), and System.value.
Referenced by System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64(), and System.Runtime.Intrinsics.X86.Avx2.ConvertToVector256Int64().