Terraria: System.Runtime.Intrinsics.X86.Avx2.GatherVector128
GatherVector128() [6/15]
static unsafe Vector128< int > System.Runtime.Intrinsics.X86.Avx2.GatherVector128 (int * baseAddress, Vector128< int > index, byte scale) inline static inherited
Definition at line 742 of file Avx2.cs.
    {
        return scale switch
        {
            1 => GatherVector128(baseAddress, index, 1),
            2 => GatherVector128(baseAddress, index, 2),
            4 => GatherVector128(baseAddress, index, 4),
            8 => GatherVector128(baseAddress, index, 8),
            _ => throw new ArgumentOutOfRangeException("scale"),
        };
    }
References System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), and System.index.
Referenced by System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), System.Runtime.Intrinsics.X86.Avx2.GatherVector128(), and System.Runtime.Intrinsics.X86.Avx2.GatherVector128().