Terraria: Terraria.DataStructures.EntrySorter.AddSortSteps
AddSortSteps()
void Terraria.DataStructures.EntrySorter< TEntryType, TStepType >.AddSortSteps (List< TStepType > sortSteps) inline
Definition at line 12 of file EntrySorter.cs.
    {
        Steps.AddRange(sortSteps);
    }
References System.Collections.Generic.List< T >.AddRange(), and Terraria.DataStructures.EntrySorter< TEntryType, TStepType >.Steps.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.UIBestiaryTest(), and Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay().