Terraria: System.Runtime.Intrinsics.X86.Avx2.Or
Or() [16/20]
static Vector256< sbyte > System.Runtime.Intrinsics.X86.Avx2.Or (Vector256< sbyte > left, Vector256< sbyte > right) inline static inherited
Definition at line 1638 of file Avx2.cs.
    {
        return Or(left, right);
    }
References System.Runtime.Intrinsics.X86.Avx2.Or().
Referenced by System.Buffers.Text.Base64.Avx2Encode(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.Collections.BitArray.Or(), System.Runtime.Intrinsics.X86.Avx2.Or(), System.Runtime.Intrinsics.X86.Avx2.Or(), System.Runtime.Intrinsics.X86.Avx2.Or(), System.Runtime.Intrinsics.X86.Avx2.Or(), System.Runtime.Intrinsics.X86.Avx2.Or(), System.Runtime.Intrinsics.X86.Avx2.Or(), System.Runtime.Intrinsics.X86.Avx2.Or(), and System.Runtime.Intrinsics.X86.Avx2.Or().