Terraria: System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128
BroadcastScalarToVector128() [10/19]
static Vector128< byte > System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128 (Vector128< byte > value) inline static
Definition at line 292 of file Avx2.cs.
    {
        return BroadcastScalarToVector128(value);
    }
References System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), and System.value.
Referenced by System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128(), and System.Runtime.Intrinsics.X86.Avx2.BroadcastScalarToVector128().