Terraria: System.Xml.Xsl.XPathConvert.BigInteger.MulAdd
MulAdd()
void System.Xml.Xsl.XPathConvert.BigInteger.MulAdd (uint uMul, uint uAdd) inline
Definition at line 1013 of file XPathConvert.cs.
        {
            for (int i = 0; i < _length; i++)
            {
                uint uHi;
                uint u = MulU(_digits[i], uMul, out uHi);
                if (uAdd != 0)
                {
                    uHi += AddU(ref u, uAdd);
                }
                _digits[i] = u;
                uAdd = uHi;
            }
            if (uAdd != 0)
            {
                Ensure(_length + 1);
                _digits[_length++] = uAdd;
            }
        }
References System.Xml.Xsl.XPathConvert.BigInteger._digits, System.Xml.Xsl.XPathConvert.BigInteger._length, System.Xml.Xsl.XPathConvert.AddU(), System.Xml.Dictionary, System.Xml.Xsl.XPathConvert.BigInteger.Ensure(), and System.Xml.Xsl.XPathConvert.MulU().
Referenced by System.Xml.Xsl.XPathConvert.BigInteger.InitFromFloatingDecimal(), and System.Xml.Xsl.XPathConvert.BigInteger.MulPow5().