Terraria: System.Xml.Xsl.XPathConvert.BigInteger.DivRem
DivRem()
uint System.Xml.Xsl.XPathConvert.BigInteger.DivRem (BigInteger bi) inline
Definition at line 1266 of file XPathConvert.cs.
        {
            int length = bi._length;
            if (_length < length)
            {
                return 0u;
            }
            uint num = _digits[length - 1] / (bi._digits[length - 1] + 1);
            switch (num)
            {
            case 1u:
                Subtract(bi);
                break;
            default:
            {
                uint u = 0u;
                uint num2 = 1u;
                int i;
                for (i = 0; i < length; i++)
                {
                    uint uHi;
                    uint u2 = MulU(num, bi._digits[i], out uHi);
                    u = uHi + AddU(ref u2, u);
                    if (u2 != 0 || num2 == 0)
                    {
                        num2 = AddU(ref _digits[i], ~u2 + num2);
                    }
                }
                while (--i >= 0 && _digits[i] == 0)
                {
                }
                _length = i + 1;
                break;
            }
            case 0u:
                break;
            }
            int num3;
            if (num < 9 && (num3 = CompareTo(bi)) >= 0)
            {
                num++;
                if (num3 == 0)
                {
                    _length = 0;
                }
                else
                {
                    Subtract(bi);
                }
            }
            return num;
        }
References System.Xml.Xsl.XPathConvert.BigInteger._digits, System.Xml.Xsl.XPathConvert.BigInteger._length, System.Xml.Xsl.XPathConvert.AddU(), System.Xml.Xsl.XPathConvert.BigInteger.CompareTo(), System.Xml.Dictionary, System.length, System.Xml.Xsl.XPathConvert.MulU(), and System.Subtract.