Terraria: Interop.NCrypt.DeriveKeyMaterial
DeriveKeyMaterial() [4/4]
static unsafe byte[] Interop.NCrypt.DeriveKeyMaterial (SafeNCryptSecretHandle secretAgreement, string kdf, string hashAlgorithm, byte[] hmacKey, byte[] secretPrepend, byte[] secretAppend, SecretAgreementFlags flags) inline static private
Definition at line 694 of file Interop.cs.
        {
            IntPtr intPtr = IntPtr.Zero;
            try
            {
                intPtr = Marshal.StringToCoTaskMemUni(hashAlgorithm);
                Span<NCryptBuffer> span = stackalloc NCryptBuffer[4];
                int num = 0;
                NCryptBuffer nCryptBuffer = default(NCryptBuffer);
                nCryptBuffer.cbBuffer = (hashAlgorithm.Length + 1) * 2;
                nCryptBuffer.BufferType = BufferType.KdfHashAlgorithm;
                nCryptBuffer.pvBuffer = intPtr;
                span[num] = nCryptBuffer;
                num++;
                fixed (byte* ptr = hmacKey)
                {
                    fixed (byte* ptr2 = secretPrepend)
                    {
                        fixed (byte* ptr3 = secretAppend)
{
                            if (ptr != null)
{
                                NCryptBuffer nCryptBuffer2 = default(NCryptBuffer);
                                nCryptBuffer2.cbBuffer = hmacKey.Length;
                                nCryptBuffer2.BufferType = BufferType.KdfHmacKey;
                                nCryptBuffer2.pvBuffer = new IntPtr(ptr);
                                span[num] = nCryptBuffer2;
                                num++;
                            }
                            if (ptr2 != null)
{
                                NCryptBuffer nCryptBuffer3 = default(NCryptBuffer);
                                nCryptBuffer3.cbBuffer = secretPrepend.Length;
                                nCryptBuffer3.BufferType = BufferType.KdfSecretPrepend;
                                nCryptBuffer3.pvBuffer = new IntPtr(ptr2);
                                span[num] = nCryptBuffer3;
                                num++;
                            }
                            if (ptr3 != null)
{
                                NCryptBuffer nCryptBuffer4 = default(NCryptBuffer);
                                nCryptBuffer4.cbBuffer = secretAppend.Length;
                                nCryptBuffer4.BufferType = BufferType.KdfSecretAppend;
                                nCryptBuffer4.pvBuffer = new IntPtr(ptr3);
                                span[num] = nCryptBuffer4;
                                num++;
                            }
                            return DeriveKeyMaterial(secretAgreement, kdf, span.Slice(0, num), flags);
                        }
                    }
                }
            }
            finally
            {
                if (intPtr != IntPtr.Zero)
                {
                    Marshal.FreeCoTaskMem(intPtr);
                }
            }
        }
References Interop.NCrypt.DeriveKeyMaterial(), System.Runtime.InteropServices.Marshal.FreeCoTaskMem(), System.Span< T >.Slice(), System.Runtime.InteropServices.Marshal.StringToCoTaskMemUni(), and System.IntPtr.Zero.