Terraria: System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpenCore
CreateOrOpenCore()
static SafeMemoryMappedFileHandle System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpenCore (string mapName, HandleInheritability inheritability, MemoryMappedFileAccess access, MemoryMappedFileOptions options, long capacity) inline static private
Definition at line 442 of file MemoryMappedFile.cs.
    {
        SafeMemoryMappedFileHandle safeMemoryMappedFileHandle = null;
        global::Interop.Kernel32.SECURITY_ATTRIBUTES securityAttributes = GetSecAttrs(inheritability);
        int num = 14;
        int num2 = 0;
        while (num > 0)
        {
            safeMemoryMappedFileHandle = global::Interop.CreateFileMapping(new IntPtr(-1), ref securityAttributes, GetPageAccess(access) | (int)options, capacity, mapName);
            if (!safeMemoryMappedFileHandle.IsInvalid)
            {
                break;
            }
            safeMemoryMappedFileHandle.Dispose();
            int lastPInvokeError = Marshal.GetLastPInvokeError();
            if (lastPInvokeError != 5)
            {
                throw System.IO.Win32Marshal.GetExceptionForWin32Error(lastPInvokeError);
            }
            safeMemoryMappedFileHandle = global::Interop.OpenFileMapping(GetFileMapAccess(access), (inheritability & HandleInheritability.Inheritable) != 0, mapName);
            if (!safeMemoryMappedFileHandle.IsInvalid)
            {
                break;
            }
            safeMemoryMappedFileHandle.Dispose();
            int lastPInvokeError2 = Marshal.GetLastPInvokeError();
            if (lastPInvokeError2 != 2)
            {
                throw System.IO.Win32Marshal.GetExceptionForWin32Error(lastPInvokeError2);
            }
            num--;
            if (num2 == 0)
            {
                num2 = 10;
                continue;
            }
            Thread.Sleep(num2);
            num2 *= 2;
        }
        if (safeMemoryMappedFileHandle == null || safeMemoryMappedFileHandle.IsInvalid)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_CantCreateFileMapping);
        }
        return safeMemoryMappedFileHandle;
    }
References System.capacity, System.Runtime.InteropServices.SafeHandle.Dispose(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.IO.MemoryMappedFiles.MemoryMappedFile.GetFileMapAccess(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.IO.MemoryMappedFiles.MemoryMappedFile.GetPageAccess(), System.IO.MemoryMappedFiles.MemoryMappedFile.GetSecAttrs(), System.SR.InvalidOperation_CantCreateFileMapping, Microsoft.Win32.SafeHandles.SafeMemoryMappedFileHandle.IsInvalid, System.options, and System.Threading.Thread.Sleep().
Referenced by System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen().