Terraria: System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor
CreateViewAccessor() [1/3]
MemoryMappedViewAccessor System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor () inline
Definition at line 316 of file MemoryMappedFile.cs.
    {
        return CreateViewAccessor(0L, 0L, MemoryMappedFileAccess.ReadWrite);
    }
References System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor(), and System.L.
Referenced by System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor(), and System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor().