Terraria: System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile
CreateFromFile() [6/6]
static MemoryMappedFile System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile (string path, FileMode mode, string? mapName, long capacity, MemoryMappedFileAccess access) inline static
Definition at line 86 of file MemoryMappedFile.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (mapName != null && mapName.Length == 0)
        {
            throw new ArgumentException(System.SR.Argument_MapNameEmptyString);
        }
        if (capacity < 0)
        {
            throw new ArgumentOutOfRangeException("capacity", System.SR.ArgumentOutOfRange_PositiveOrDefaultCapacityRequired);
        }
        if (access < MemoryMappedFileAccess.ReadWrite || access > MemoryMappedFileAccess.ReadWriteExecute)
        {
            throw new ArgumentOutOfRangeException("access");
        }
        switch (mode)
        {
        case FileMode.Append:
            throw new ArgumentException(System.SR.Argument_NewMMFAppendModeNotAllowed, "mode");
        case FileMode.Truncate:
            throw new ArgumentException(System.SR.Argument_NewMMFTruncateModeNotAllowed, "mode");
        default:
        {
            if (access == MemoryMappedFileAccess.Write)
            {
                throw new ArgumentException(System.SR.Argument_NewMMFWriteAccessNotAllowed, "access");
            }
            bool existed = File.Exists(path);
            FileStream fileStream = new FileStream(path, mode, GetFileAccess(access), FileShare.Read, 4096, FileOptions.None);
            if (capacity == 0L && fileStream.Length == 0L)
            {
                CleanupFile(fileStream, existed, path);
                throw new ArgumentException(System.SR.Argument_EmptyFile);
            }
            if (capacity == 0L)
            {
                capacity = fileStream.Length;
            }
            SafeMemoryMappedFileHandle safeMemoryMappedFileHandle = null;
            try
            {
                safeMemoryMappedFileHandle = CreateCore(fileStream, mapName, HandleInheritability.None, access, MemoryMappedFileOptions.None, capacity);
            }
            catch
            {
                CleanupFile(fileStream, existed, path);
                throw;
            }
            return new MemoryMappedFile(safeMemoryMappedFileHandle, fileStream, leaveOpen: false);
        }
        }
    }
References System.IO.MemoryMappedFiles.MemoryMappedFile.MemoryMappedFile(), System.SR.Argument_EmptyFile, System.SR.Argument_MapNameEmptyString, System.SR.Argument_NewMMFAppendModeNotAllowed, System.SR.Argument_NewMMFTruncateModeNotAllowed, System.SR.Argument_NewMMFWriteAccessNotAllowed, System.SR.ArgumentOutOfRange_PositiveOrDefaultCapacityRequired, System.capacity, System.IO.MemoryMappedFiles.MemoryMappedFile.CleanupFile(), System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(), System.IO.File.Exists(), System.IO.MemoryMappedFiles.MemoryMappedFile.GetFileAccess(), System.L, and System.IO.FileStream.Length.