Terraria: FavoritesFile.Load
Load()
void FavoritesFile.Load () inline
     {
         if (!FileUtilities.Exists(Path, IsCloudSave))
         {
             _data.Clear();
             return;
         }
         try
         {
             byte[] bytes = FileUtilities.ReadAllBytes(Path, IsCloudSave);
             string @string;
             try
             {
                 @string = _ourEncoder.GetString(bytes);
             }
             catch
             {
                 @string = Encoding.ASCII.GetString(bytes);
             }
             _data = JsonConvert.DeserializeObject<Dictionary<string, Dictionary<string, bool>>>(@string);
             if (_data == null)
             {
                 _data = new Dictionary<string, Dictionary<string, bool>>();
             }
         }
         catch (Exception)
         {
             Console.WriteLine("Unable to load favorites.json file ({0} : {1})", Path, IsCloudSave ? "Cloud Save" : "Local Save");
         }
     }
References _data, _ourEncoder, FileUtilities.Exists(), IsCloudSave, Path, and FileUtilities.ReadAllBytes().
Referenced by Main.Initialize_AlmostEverything().