Terraria: System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen
CreateOrOpen() [1/3]
static MemoryMappedFile System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen (string mapName, long capacity) inline static
Definition at line 238 of file MemoryMappedFile.cs.
    {
        return CreateOrOpen(mapName, capacity, MemoryMappedFileAccess.ReadWrite, MemoryMappedFileOptions.None, HandleInheritability.None);
    }
References System.capacity, and System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen().
Referenced by System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen(), and System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen().