Terraria: System.IO.MemoryMappedFiles.MemoryMappedFile.CleanupFile
CleanupFile()
static void System.IO.MemoryMappedFiles.MemoryMappedFile.CleanupFile (FileStream fileStream, bool existed, string path) inline static private
Definition at line 388 of file MemoryMappedFile.cs.
    {
        fileStream.Dispose();
        if (!existed)
        {
            File.Delete(path);
        }
    }
References System.IO.File.Delete(), and System.IO.FileStream.Dispose().
Referenced by System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile().