Terraria: FavoritesFile.Save
Save()
void FavoritesFile.Save () inline
     {
         try
         {
             string s = JsonConvert.SerializeObject((object)_data, (Formatting)1);
             byte[] bytes = _ourEncoder.GetBytes(s);
             FileUtilities.WriteAllBytes(Path, bytes, IsCloudSave);
         }
         catch (Exception exception)
         {
             FancyErrorPrinter.ShowFileSavingFailError(exception, Path);
             throw;
         }
     }
References _data, _ourEncoder, IsCloudSave, Path, FancyErrorPrinter.ShowFileSavingFailError(), and FileUtilities.WriteAllBytes().
Referenced by ClearEntry(), and SaveFavorite().