Terraria: System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile
CreateFromFile() [1/6]
static MemoryMappedFile System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile (FileStream fileStream, string? mapName, long capacity, MemoryMappedFileAccess access, HandleInheritability inheritability, bool leaveOpen) inline static
Definition at line 142 of file MemoryMappedFile.cs.
    {
        if (fileStream == null)
        {
            throw new ArgumentNullException("fileStream", System.SR.ArgumentNull_FileStream);
        }
        if (mapName != null && mapName.Length == 0)
        {
            throw new ArgumentException(System.SR.Argument_MapNameEmptyString);
        }
        if (capacity < 0)
        {
            throw new ArgumentOutOfRangeException("capacity", System.SR.ArgumentOutOfRange_PositiveOrDefaultCapacityRequired);
        }
        if (capacity == 0L && fileStream.Length == 0L)
        {
            throw new ArgumentException(System.SR.Argument_EmptyFile);
        }
        switch (access)
        {
        default:
            throw new ArgumentOutOfRangeException("access");
        case MemoryMappedFileAccess.Write:
            throw new ArgumentException(System.SR.Argument_NewMMFWriteAccessNotAllowed, "access");
        case MemoryMappedFileAccess.ReadWrite:
        case MemoryMappedFileAccess.Read:
        case MemoryMappedFileAccess.CopyOnWrite:
        case MemoryMappedFileAccess.ReadExecute:
        case MemoryMappedFileAccess.ReadWriteExecute:
        {
            if (inheritability < HandleInheritability.None || inheritability > HandleInheritability.Inheritable)
            {
                throw new ArgumentOutOfRangeException("inheritability");
            }
            fileStream.Flush();
            if (capacity == 0L)
            {
                capacity = fileStream.Length;
            }
            SafeMemoryMappedFileHandle handle = CreateCore(fileStream, mapName, inheritability, access, MemoryMappedFileOptions.None, capacity);
            return new MemoryMappedFile(handle, fileStream, leaveOpen);
        }
        }
    }
References System.IO.MemoryMappedFiles.MemoryMappedFile.MemoryMappedFile(), System.SR.Argument_EmptyFile, System.SR.Argument_MapNameEmptyString, System.SR.Argument_NewMMFWriteAccessNotAllowed, System.SR.ArgumentNull_FileStream, System.SR.ArgumentOutOfRange_PositiveOrDefaultCapacityRequired, System.capacity, System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(), System.IO.FileStream.Flush(), System.handle, System.L, and System.IO.FileStream.Length.