Terraria: System.Globalization.CultureData.ReescapeWin32String
ReescapeWin32String()
static string System.Globalization.CultureData.ReescapeWin32String (string str) inline static package
Definition at line 2348 of file CultureData.cs.
    {
        if (str == null)
        {
            return null;
        }
        StringBuilder stringBuilder = null;
        bool flag = false;
        for (int i = 0; i < str.Length; i++)
        {
            if (str[i] == '\'')
            {
                if (flag)
                {
                    if (i + 1 < str.Length && str[i + 1] == '\'')
                    {
                        if (stringBuilder == null)
{
                            stringBuilder = new StringBuilder(str, 0, i, str.Length * 2);
                        }
                        stringBuilder.Append("\\'");
                        i++;
                        continue;
                    }
                    flag = false;
                }
                else
                {
                    flag = true;
                }
            }
            else if (str[i] == '\\')
            {
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(str, 0, i, str.Length * 2);
                }
                stringBuilder.Append("\\\\");
                continue;
            }
            stringBuilder?.Append(str[i]);
        }
        if (stringBuilder == null)
        {
            return str;
        }
        return stringBuilder.ToString();
    }
References System.str.
Referenced by System.Globalization.CalendarData.LoadCalendarDataFromSystemCore(), System.Globalization.CultureData.NlsGetTimeFormatString(), System.Globalization.CalendarData.NlsLoadCalendarDataFromSystem(), and System.Globalization.CultureData.ReescapeWin32Strings().