Terraria: System.Globalization.CultureData.InitCultureDataCore
InitCultureDataCore()
unsafe bool System.Globalization.CultureData.InitCultureDataCore () inline private
Definition at line 2582 of file CultureData.cs.
    {
        char* ptr = stackalloc char[85];
        if (!GlobalizationMode.UseNls)
        {
            if (InitIcuCultureDataCore())
            {
                return GetLocaleInfoEx(_sRealName, 92u, ptr, 85) != 0;
            }
            return false;
        }
        string sRealName = _sRealName;
        int localeInfoEx = GetLocaleInfoEx(sRealName, 92u, ptr, 85);
        if (localeInfoEx == 0)
        {
            return false;
        }
        _sRealName = new string(ptr, 0, localeInfoEx - 1);
        sRealName = _sRealName;
        if (GetLocaleInfoEx(sRealName, 536871025u, ptr, 2) == 0)
        {
            return false;
        }
        _bNeutral = *(uint*)ptr != 0;
        _sWindowsName = sRealName;
        if (_bNeutral)
        {
            _sName = sRealName;
            localeInfoEx = Interop.Kernel32.ResolveLocaleName(sRealName, ptr, 85);
            if (localeInfoEx < 1)
            {
                return false;
            }
            _sSpecificCulture = new string(ptr, 0, localeInfoEx - 1);
        }
        else
        {
            _sSpecificCulture = sRealName;
            _sName = sRealName;
            if (GetLocaleInfoEx(sRealName, 536870913u, ptr, 2) == 0)
            {
                return false;
            }
            _iLanguage = *(int*)ptr;
            if (!IsCustomCultureId(_iLanguage))
            {
                int num = sRealName.IndexOf('_');
                if (num > 0)
                {
                    _sName = sRealName.Substring(0, num);
                }
            }
        }
        return true;
    }
References System.Globalization.CultureData._bNeutral, System.Globalization.CultureData._iLanguage, System.Globalization.CultureData._sName, System.Globalization.CultureData._sRealName, System.Globalization.CultureData._sSpecificCulture, System.Globalization.CultureData._sWindowsName, System.Globalization.CultureData.GetLocaleInfoEx(), System.Globalization.CultureData.InitIcuCultureDataCore(), System.Globalization.CultureData.IsCustomCultureId(), Interop.Kernel32.ResolveLocaleName(), and System.Globalization.GlobalizationMode.UseNls.
Referenced by System.Globalization.CultureData.InitCompatibilityCultureData().