Terraria: System.Globalization.CultureData.ReescapeWin32Strings
ReescapeWin32Strings()
static string[] System.Globalization.CultureData.ReescapeWin32Strings (string[] array) inline static package
Definition at line 2398 of file CultureData.cs.
    {
        if (array != null)
        {
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = ReescapeWin32String(array[i]);
            }
        }
        return array;
    }
References System.array, and System.Globalization.CultureData.ReescapeWin32String().
Referenced by System.Globalization.CultureData.GetTimeFormatsCore(), and System.Globalization.CalendarData.NlsLoadCalendarDataFromSystem().