Terraria: System.Globalization.CultureData.GetLocaleInfoEx
GetLocaleInfoEx() [1/2]
static unsafe string System.Globalization.CultureData.GetLocaleInfoEx (string localeName, uint field) inline static package
Definition at line 2241 of file CultureData.cs.
    {
        char* ptr = stackalloc char[530];
        int localeInfoEx = GetLocaleInfoEx(localeName, field, ptr, 530);
        if (localeInfoEx > 0)
        {
            return new string(ptr);
        }
        return null;
    }
References System.Globalization.CultureData.GetLocaleInfoEx().
Referenced by System.Globalization.CalendarData.CallEnumCalendarInfo(), System.Globalization.CultureData.EnumSystemLocalesProc(), System.Globalization.CultureData.GetLocaleInfoEx(), System.Globalization.CultureData.GetLocaleInfoExInt(), System.Globalization.CultureData.GetLocaleInfoFromLCType(), System.Globalization.CultureInfo.GetUserDefaultLocaleName(), System.Globalization.CultureData.InitCultureDataCore(), and System.Globalization.CalendarData.LoadCalendarDataFromSystemCore().