Terraria: System.Globalization.CultureData.CreateCultureData
CreateCultureData()
static CultureData System.Globalization.CultureData.CreateCultureData (string cultureName, bool useUserOverride) inline static private
Definition at line 1301 of file CultureData.cs.
    {
        if (GlobalizationMode.Invariant)
        {
            if (cultureName.Length > 85 || !CultureInfo.VerifyCultureName(cultureName, throwException: false))
            {
                return null;
            }
            CultureData cultureData = CreateCultureWithInvariantData();
            cultureData._sName = NormalizeCultureName(cultureName, out cultureData._bNeutral);
            cultureData._bUseOverridesUserSetting = useUserOverride;
            cultureData._sRealName = cultureData._sName;
            cultureData._sWindowsName = cultureData._sName;
            cultureData._iLanguage = 4096;
            return cultureData;
        }
        if (cultureName.Length == 1 && (cultureName[0] == 'C' || cultureName[0] == 'c'))
        {
            return Invariant;
        }
        CultureData cultureData2 = new CultureData();
        cultureData2._sRealName = cultureName;
        cultureData2._bUseOverridesUserSetting = useUserOverride;
        if (!cultureData2.InitCultureDataCore() && !cultureData2.InitCompatibilityCultureData())
        {
            return null;
        }
        cultureData2.InitUserOverride(useUserOverride);
        return cultureData2;
    }
References System.Globalization.CultureData.CreateCultureWithInvariantData(), System.Globalization.CultureData.Invariant, System.Globalization.GlobalizationMode.Invariant, System.Globalization.CultureData.NormalizeCultureName(), and System.Globalization.CultureInfo.VerifyCultureName().
Referenced by System.Globalization.CultureData.GetCultureData().