Terraria: System.Globalization.CultureData.GetNFIValues
GetNFIValues()
void System.Globalization.CultureData.GetNFIValues (NumberFormatInfo nfi) inline package
Definition at line 1709 of file CultureData.cs.
    {
        if (GlobalizationMode.Invariant || IsInvariantCulture)
        {
            nfi._positiveSign = _sPositiveSign;
            nfi._negativeSign = _sNegativeSign;
            nfi._numberGroupSeparator = _sThousandSeparator;
            nfi._numberDecimalSeparator = _sDecimalSeparator;
            nfi._numberDecimalDigits = _iDigits;
            nfi._numberNegativePattern = _iNegativeNumber;
            nfi._currencySymbol = _sCurrency;
            nfi._currencyGroupSeparator = _sMonetaryThousand;
            nfi._currencyDecimalSeparator = _sMonetaryDecimal;
            nfi._currencyDecimalDigits = _iCurrencyDigits;
            nfi._currencyNegativePattern = _iNegativeCurrency;
            nfi._currencyPositivePattern = _iCurrency;
        }
        else
        {
            nfi._positiveSign = GetLocaleInfoCoreUserOverride(LocaleStringData.PositiveSign);
            nfi._negativeSign = GetLocaleInfoCoreUserOverride(LocaleStringData.NegativeSign);
            nfi._numberDecimalSeparator = GetLocaleInfoCoreUserOverride(LocaleStringData.DecimalSeparator);
            nfi._numberGroupSeparator = GetLocaleInfoCoreUserOverride(LocaleStringData.ThousandSeparator);
            nfi._currencyGroupSeparator = GetLocaleInfoCoreUserOverride(LocaleStringData.MonetaryThousandSeparator);
            nfi._currencyDecimalSeparator = GetLocaleInfoCoreUserOverride(LocaleStringData.MonetaryDecimalSeparator);
            nfi._currencySymbol = GetLocaleInfoCoreUserOverride(LocaleStringData.MonetarySymbol);
            nfi._numberDecimalDigits = GetLocaleInfoCoreUserOverride(LocaleNumberData.FractionalDigitsCount);
            nfi._currencyDecimalDigits = GetLocaleInfoCoreUserOverride(LocaleNumberData.MonetaryFractionalDigitsCount);
            nfi._currencyPositivePattern = GetLocaleInfoCoreUserOverride(LocaleNumberData.PositiveMonetaryNumberFormat);
            nfi._currencyNegativePattern = GetLocaleInfoCoreUserOverride(LocaleNumberData.NegativeMonetaryNumberFormat);
            nfi._numberNegativePattern = GetLocaleInfoCoreUserOverride(LocaleNumberData.NegativeNumberFormat);
            string localeInfoCoreUserOverride = GetLocaleInfoCoreUserOverride(LocaleStringData.Digits);
            nfi._nativeDigits = new string[10];
            for (int i = 0; i < nfi._nativeDigits.Length; i++)
            {
                nfi._nativeDigits[i] = char.ToString(localeInfoCoreUserOverride[i]);
            }
            nfi._digitSubstitution = (ShouldUseUserOverrideNlsData ? NlsGetLocaleInfo(LocaleNumberData.DigitSubstitution) : IcuGetDigitSubstitution(_sRealName));
        }
        nfi._numberGroupSizes = NumberGroupSizes;
        nfi._currencyGroupSizes = CurrencyGroupSizes;
        nfi._percentNegativePattern = PercentNegativePattern;
        nfi._percentPositivePattern = PercentPositivePattern;
        nfi._percentSymbol = PercentSymbol;
        nfi._perMilleSymbol = PerMilleSymbol;
        nfi._negativeInfinitySymbol = NegativeInfinitySymbol;
        nfi._positiveInfinitySymbol = PositiveInfinitySymbol;
        nfi._nanSymbol = NaNSymbol;
        nfi._percentDecimalDigits = nfi._numberDecimalDigits;
        nfi._percentDecimalSeparator = nfi._numberDecimalSeparator;
        nfi._percentGroupSizes = nfi._numberGroupSizes;
        nfi._percentGroupSeparator = nfi._numberGroupSeparator;
        if (string.IsNullOrEmpty(nfi._positiveSign))
        {
            nfi._positiveSign = "+";
        }
        if (string.IsNullOrEmpty(nfi._currencyDecimalSeparator))
        {
            nfi._currencyDecimalSeparator = nfi._numberDecimalSeparator;
        }
    }
References System.Globalization.CultureData._iCurrency, System.Globalization.CultureData._iCurrencyDigits, System.Globalization.CultureData._iDigits, System.Globalization.CultureData._iNegativeCurrency, System.Globalization.CultureData._iNegativeNumber, System.Globalization.CultureData._sCurrency, System.Globalization.CultureData._sDecimalSeparator, System.Globalization.CultureData._sMonetaryDecimal, System.Globalization.CultureData._sMonetaryThousand, System.Globalization.CultureData._sNegativeSign, System.Globalization.CultureData._sPositiveSign, System.Globalization.CultureData._sRealName, System.Globalization.CultureData._sThousandSeparator, System.Globalization.CultureData.CurrencyGroupSizes, System.Globalization.CultureData.GetLocaleInfoCoreUserOverride(), System.Globalization.CultureData.IcuGetDigitSubstitution(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.CultureData.IsInvariantCulture, System.Globalization.CultureData.NaNSymbol, System.Globalization.CultureData.NegativeInfinitySymbol, System.Globalization.CultureData.NlsGetLocaleInfo(), System.Globalization.CultureData.NumberGroupSizes, System.Globalization.CultureData.PercentNegativePattern, System.Globalization.CultureData.PercentPositivePattern, System.Globalization.CultureData.PercentSymbol, System.Globalization.CultureData.PerMilleSymbol, System.Globalization.CultureData.PositiveInfinitySymbol, and System.Globalization.CultureData.ShouldUseUserOverrideNlsData.
Referenced by System.Globalization.NumberFormatInfo.NumberFormatInfo().