Terraria: System.Globalization.CultureData.NlsGetCultureDataFromRegionName
NlsGetCultureDataFromRegionName()
static unsafe CultureData System.Globalization.CultureData.NlsGetCultureDataFromRegionName (string regionName) inline static private
Definition at line 2306 of file CultureData.cs.
    {
        System.Runtime.CompilerServices.Unsafe.SkipInit(out EnumLocaleData value);
        value.cultureName = null;
        value.regionName = regionName;
        Interop.Kernel32.EnumSystemLocalesEx((delegate* unmanaged<char*, uint, void*, Interop.BOOL>)(delegate*<char*, uint, void*, Interop.BOOL>)(&EnumSystemLocalesProc), 34u, Unsafe.AsPointer(ref value), IntPtr.Zero);
        if (value.cultureName != null)
        {
            return GetCultureData(value.cultureName, useUserOverride: true);
        }
        return null;
    }
References Interop.Kernel32.EnumSystemLocalesEx(), System.Globalization.CultureData.EnumSystemLocalesProc(), System.Globalization.CultureData.GetCultureData(), System.value, and System.IntPtr.Zero.
Referenced by System.Globalization.CultureData.GetCultureDataForRegion().