Terraria: System.Globalization.CultureData.GetCultureDataForRegion
GetCultureDataForRegion()
static CultureData System.Globalization.CultureData.GetCultureDataForRegion (string cultureName, bool useUserOverride) inline static package
Definition at line 1052 of file CultureData.cs.
    {
        if (string.IsNullOrEmpty(cultureName))
        {
            return Invariant;
        }
        CultureData cultureData = null;
        cultureData = GetCultureData(cultureName, useUserOverride);
        if (cultureData != null && !cultureData.IsNeutralCulture)
        {
            return cultureData;
        }
        CultureData cultureData2 = cultureData;
        string key = AnsiToLower(useUserOverride ? cultureName : (cultureName + "*"));
        Dictionary<string, CultureData> dictionary = s_cachedRegions;
        if (dictionary == null)
        {
            dictionary = new Dictionary<string, CultureData>();
        }
        else
        {
            lock (s_lock)
            {
                dictionary.TryGetValue(key, out cultureData);
            }
            if (cultureData != null)
            {
                return cultureData;
            }
        }
        if ((cultureData == null || cultureData.IsNeutralCulture) && RegionNames.TryGetValue(cultureName, out var value))
        {
            cultureData = GetCultureData(value, useUserOverride);
        }
        if (!GlobalizationMode.Invariant && (cultureData == null || cultureData.IsNeutralCulture))
        {
            cultureData = (GlobalizationMode.UseNls ? NlsGetCultureDataFromRegionName(cultureName) : IcuGetCultureDataFromRegionName(cultureName));
        }
        if (cultureData != null && !cultureData.IsNeutralCulture)
        {
            lock (s_lock)
            {
                dictionary[key] = cultureData;
            }
            s_cachedRegions = dictionary;
        }
        else
        {
            cultureData = cultureData2;
        }
        return cultureData;
    }
References System.Globalization.CultureData.AnsiToLower(), System.dictionary, System.Globalization.CultureData.GetCultureData(), System.Globalization.CultureData.IcuGetCultureDataFromRegionName(), System.Globalization.CultureData.Invariant, System.Globalization.GlobalizationMode.Invariant, System.key, System.Globalization.CultureData.NlsGetCultureDataFromRegionName(), System.Globalization.CultureData.RegionNames, System.Globalization.CultureData.s_cachedRegions, System.Globalization.CultureData.s_lock, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Globalization.RegionInfo.RegionInfo(), and System.Globalization.CultureData.GetCurrentRegionData().