Terraria: System.Globalization.CultureData.GetTimeFormatsCore
GetTimeFormatsCore()
string[] System.Globalization.CultureData.GetTimeFormatsCore (bool shortFormat) inline private
Definition at line 2678 of file CultureData.cs.
    {
        if (GlobalizationMode.UseNls)
        {
            return ReescapeWin32Strings(nativeEnumTimeFormats(_sWindowsName, shortFormat ? 2u : 0u, _bUseOverrides));
        }
        string text = IcuGetTimeFormatString(shortFormat);
        if (_bUseOverrides)
        {
            string localeInfoFromLCType = GetLocaleInfoFromLCType(_sWindowsName, shortFormat ? 121u : 4099u, useUserOverride: true);
            if (localeInfoFromLCType != text)
            {
                return new string[2] { localeInfoFromLCType, text };
            }
            return new string[1] { localeInfoFromLCType };
        }
        return new string[1] { text };
    }
References System.Globalization.CultureData._bUseOverrides, System.Globalization.CultureData._sWindowsName, System.Globalization.CultureData.GetLocaleInfoFromLCType(), System.Globalization.CultureData.IcuGetTimeFormatString(), System.Globalization.CultureData.nativeEnumTimeFormats(), System.Globalization.CultureData.ReescapeWin32Strings(), System.text, and System.Globalization.GlobalizationMode.UseNls.