Terraria: System.Globalization.CultureData.GetCultures
GetCultures()
static CultureInfo[] System.Globalization.CultureData.GetCultures (CultureTypes types) inline static package
Definition at line 1111 of file CultureData.cs.
    {
        if (types <= (CultureTypes)0 || ((uint)types & 0xFFFFFF80u) != 0)
        {
            throw new ArgumentOutOfRangeException("types", SR.Format(SR.ArgumentOutOfRange_Range, CultureTypes.NeutralCultures, CultureTypes.FrameworkCultures));
        }
        if ((types & CultureTypes.WindowsOnlyCultures) != 0)
        {
            types &= ~CultureTypes.WindowsOnlyCultures;
        }
        if (GlobalizationMode.Invariant)
        {
            return new CultureInfo[1]
            {
                new CultureInfo("")
            };
        }
        if (!GlobalizationMode.UseNls)
        {
            return IcuEnumCultures(types);
        }
        return NlsEnumCultures(types);
    }
References System.SR.ArgumentOutOfRange_Range, System.SR.Format(), System.Globalization.CultureData.IcuEnumCultures(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.CultureData.NlsEnumCultures(), and System.Globalization.GlobalizationMode.UseNls.
Referenced by System.Globalization.CultureInfo.GetCultures().