Terraria: System.Globalization.CultureData.GetCurrentRegionData
GetCurrentRegionData()
static unsafe CultureData System.Globalization.CultureData.GetCurrentRegionData () inline static package
Definition at line 2643 of file CultureData.cs.
    {
        Span<char> span = stackalloc char[10];
        int userGeoID = Interop.Kernel32.GetUserGeoID(16);
        if (userGeoID != -1)
        {
            int geoInfo;
            fixed (char* lpGeoData = span)
            {
                geoInfo = Interop.Kernel32.GetGeoInfo(userGeoID, 4, lpGeoData, span.Length, 0);
            }
            if (geoInfo != 0)
            {
                geoInfo -= ((span[geoInfo - 1] == '\0') ? 1 : 0);
                CultureData cultureDataForRegion = GetCultureDataForRegion(span.Slice(0, geoInfo).ToString(), useUserOverride: true);
                if (cultureDataForRegion != null)
                {
                    return cultureDataForRegion;
                }
            }
        }
        return CultureInfo.CurrentCulture._cultureData;
    }
References System.Globalization.CultureInfo.CurrentCulture, System.Globalization.CultureData.GetCultureDataForRegion(), Interop.Kernel32.GetGeoInfo(), and Interop.Kernel32.GetUserGeoID().