Terraria: System.Globalization.CultureData.AnsiToLower
AnsiToLower()
static string System.Globalization.CultureData.AnsiToLower (string testString) inline static package
Definition at line 1771 of file CultureData.cs.
    {
        return TextInfo.ToLowerAsciiInvariant(testString);
    }
References System.Globalization.TextInfo.ToLowerAsciiInvariant().
Referenced by System.Globalization.CultureData.GetCultureData(), System.Globalization.CultureData.GetCultureDataForRegion(), System.Globalization.CultureInfo.GetCultureInfo(), System.Globalization.CultureInfo.GetCultureInfo(), and System.Globalization.CultureData.InitCompatibilityCultureData().