Terraria: System.Globalization.CultureData.GetCalendar
GetCalendar()
CalendarData System.Globalization.CultureData.GetCalendar (CalendarId calendarId) inline package
Definition at line 1552 of file CultureData.cs.
    {
        if (GlobalizationMode.Invariant)
        {
            return CalendarData.Invariant;
        }
        int num = (int)(calendarId - 1);
        if (_calendars == null)
        {
            _calendars = new CalendarData[23];
        }
        CalendarData calendarData = _calendars[num];
        if (calendarData == null)
        {
            calendarData = new CalendarData(_sWindowsName, calendarId, _bUseOverrides);
            _calendars[num] = calendarData;
        }
        return calendarData;
    }
References System.Globalization.CultureData._bUseOverrides, System.Globalization.CultureData._calendars, System.Globalization.CultureData._sWindowsName, System.Globalization.CalendarData.Invariant, and System.Globalization.GlobalizationMode.Invariant.
Referenced by System.Globalization.CultureData.AbbrevEraNames(), System.Globalization.CultureData.AbbreviatedDayNames(), System.Globalization.CultureData.AbbreviatedEnglishEraNames(), System.Globalization.CultureData.AbbreviatedGenitiveMonthNames(), System.Globalization.CultureData.AbbreviatedMonthNames(), System.Globalization.CultureData.CalendarName(), System.Globalization.CultureData.DayNames(), System.Globalization.CultureData.EraNames(), System.Globalization.CultureData.GenitiveMonthNames(), System.Globalization.CultureData.LeapYearMonthNames(), System.Globalization.CultureData.LongDates(), System.Globalization.CultureData.MonthDay(), System.Globalization.CultureData.MonthNames(), System.Globalization.CultureData.ShortDates(), System.Globalization.CultureData.SuperShortDayNames(), and System.Globalization.CultureData.YearMonths().