Terraria: System.Globalization.CultureData.GetSeparator
GetSeparator()
static string System.Globalization.CultureData.GetSeparator (string format, string timeParts) inline static private
Definition at line 1646 of file CultureData.cs.
    {
        int num = IndexOfTimePart(format, 0, timeParts);
        if (num != -1)
        {
            char c = format[num];
            do
            {
                num++;
            }
            while (num < format.Length && format[num] == c);
            int num2 = num;
            if (num2 < format.Length)
            {
                int num3 = IndexOfTimePart(format, num2, timeParts);
                if (num3 != -1)
                {
                    return UnescapeNlsString(format, num2, num3 - 1);
                }
            }
        }
        return string.Empty;
    }
References System.format, System.Globalization.CultureData.IndexOfTimePart(), and System.Globalization.CultureData.UnescapeNlsString().
Referenced by System.Globalization.CultureData.GetDateSeparator(), and System.Globalization.CultureData.GetTimeSeparator().