Terraria: System.Globalization.CultureData.NlsEnumCultures
NlsEnumCultures()
static unsafe CultureInfo[] System.Globalization.CultureData.NlsEnumCultures (CultureTypes types) inline static private
Definition at line 2543 of file CultureData.cs.
    {
        uint num = 0u;
        if ((types & (CultureTypes.InstalledWin32Cultures | CultureTypes.ReplacementCultures | CultureTypes.FrameworkCultures)) != 0)
        {
            num |= 0x30u;
        }
        if ((types & CultureTypes.NeutralCultures) != 0)
        {
            num |= 0x10u;
        }
        if ((types & CultureTypes.SpecificCultures) != 0)
        {
            num |= 0x20u;
        }
        if ((types & CultureTypes.UserCustomCulture) != 0)
        {
            num |= 2u;
        }
        if ((types & CultureTypes.ReplacementCultures) != 0)
        {
            num |= 2u;
        }
        EnumData value = default(EnumData);
        value.strings = new List<string>();
        Interop.Kernel32.EnumSystemLocalesEx((delegate* unmanaged<char*, uint, void*, Interop.BOOL>)(delegate*<char*, uint, void*, Interop.BOOL>)(&EnumAllSystemLocalesProc), num, Unsafe.AsPointer(ref value), IntPtr.Zero);
        CultureInfo[] array = new CultureInfo[value.strings.Count];
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = new CultureInfo(value.strings[i]);
        }
        return array;
    }
References System.array, System.Globalization.CultureData.EnumAllSystemLocalesProc(), Interop.Kernel32.EnumSystemLocalesEx(), System.value, and System.IntPtr.Zero.
Referenced by System.Globalization.CultureData.GetCultures().