Terraria: System.Globalization.CultureData.GetCultureData
GetCultureData() [2/2]
static CultureData System.Globalization.CultureData.GetCultureData (string cultureName, bool useUserOverride) inline static package
Definition at line 1214 of file CultureData.cs.
    {
        if (string.IsNullOrEmpty(cultureName))
        {
            return Invariant;
        }
        if (GlobalizationMode.PredefinedCulturesOnly && (GlobalizationMode.Invariant || (GlobalizationMode.UseNls ? (!NlsIsEnsurePredefinedLocaleName(cultureName)) : (!IcuIsEnsurePredefinedLocaleName(cultureName)))))
        {
            return null;
        }
        string key = AnsiToLower(useUserOverride ? cultureName : (cultureName + "*"));
        Dictionary<string, CultureData> dictionary = s_cachedCultures;
        if (dictionary == null)
        {
            dictionary = new Dictionary<string, CultureData>();
        }
        else
        {
            bool flag;
            CultureData value;
            lock (s_lock)
            {
                flag = dictionary.TryGetValue(key, out value);
            }
            if (flag && value != null)
            {
                return value;
            }
        }
        CultureData cultureData = CreateCultureData(cultureName, useUserOverride);
        if (cultureData == null)
        {
            return null;
        }
        lock (s_lock)
        {
            dictionary[key] = cultureData;
        }
        s_cachedCultures = dictionary;
        return cultureData;
    }
References System.Globalization.CultureData.AnsiToLower(), System.Globalization.CultureData.CreateCultureData(), System.dictionary, System.Globalization.CultureData.IcuIsEnsurePredefinedLocaleName(), System.Globalization.CultureData.Invariant, System.Globalization.GlobalizationMode.Invariant, System.key, System.Globalization.CultureData.NlsIsEnsurePredefinedLocaleName(), System.Globalization.GlobalizationMode.PredefinedCulturesOnly, System.Globalization.CultureData.s_cachedCultures, System.Globalization.CultureData.s_lock, System.Globalization.GlobalizationMode.UseNls, and System.value.
Referenced by System.Globalization.CultureInfo.CultureInfo(), System.Globalization.CultureInfo.CultureInfo(), System.Globalization.CultureInfo.CultureInfo(), System.Globalization.RegionInfo.RegionInfo(), System.Globalization.CultureInfo.CreateCultureInfoNoThrow(), System.Globalization.CultureData.GetCultureData(), System.Globalization.CultureData.GetCultureDataForRegion(), and System.Globalization.CultureData.NlsGetCultureDataFromRegionName().