Terraria: System.Globalization.CultureData.NlsGetLocaleInfo
NlsGetLocaleInfo() [3/4]
string System.Globalization.CultureData.NlsGetLocaleInfo (LocaleStringData type) inline private
Definition at line 2265 of file CultureData.cs.
    {
        return NlsGetLocaleInfo(_sWindowsName, type);
    }
References System.Globalization.CultureData._sWindowsName, System.Globalization.CultureData.NlsGetLocaleInfo(), and System.type.
Referenced by System.Globalization.CultureData.GetAnsiCodePage(), System.Globalization.CultureData.GetEbcdicCodePage(), System.Globalization.CultureData.GetLocaleInfoCore(), System.Globalization.CultureData.GetLocaleInfoCore(), System.Globalization.CultureData.GetLocaleInfoCore(), System.Globalization.CultureData.GetLocaleInfoCoreUserOverride(), System.Globalization.CultureData.GetLocaleInfoCoreUserOverride(), System.Globalization.CultureData.GetLocaleInfoCoreUserOverride(), System.Globalization.CultureData.GetMacCodePage(), System.Globalization.CultureData.GetNFIValues(), System.Globalization.CultureData.GetOemCodePage(), System.Globalization.CultureData.NlsGetConsoleFallbackName(), System.Globalization.CultureData.NlsGetLanguageDisplayName(), System.Globalization.CultureData.NlsGetLocaleInfo(), System.Globalization.CultureData.NlsGetRegionDisplayName(), and System.Globalization.CultureData.NlsGetThreeLetterWindowsLanguageName().