Terraria: System.Globalization.CultureData.nativeEnumTimeFormats
nativeEnumTimeFormats()
static unsafe string[] System.Globalization.CultureData.nativeEnumTimeFormats (string localeName, uint dwFlags, bool useUserOverride) inline static private
Definition at line 2506 of file CultureData.cs.
    {
        EnumData value = default(EnumData);
        value.strings = new List<string>();
        Interop.Kernel32.EnumTimeFormatsEx((delegate* unmanaged<char*, void*, Interop.BOOL>)(delegate*<char*, void*, Interop.BOOL>)(&EnumTimeCallback), localeName, dwFlags, Unsafe.AsPointer(ref value));
        if (value.strings.Count > 0)
        {
            string[] array = value.strings.ToArray();
            if (!useUserOverride && value.strings.Count > 1)
            {
                uint lctype = ((dwFlags == 2) ? 121u : 4099u);
                string localeInfoFromLCType = GetLocaleInfoFromLCType(localeName, lctype, useUserOverride);
                if (localeInfoFromLCType != "")
                {
                    string text = array[0];
                    if (localeInfoFromLCType != text)
                    {
                        array[0] = array[1];
                        array[1] = text;
                    }
                }
            }
            return array;
        }
        return null;
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Globalization.CultureData.EnumTimeCallback(), Interop.Kernel32.EnumTimeFormatsEx(), System.Globalization.CultureData.GetLocaleInfoFromLCType(), System.text, and System.value.
Referenced by System.Globalization.CultureData.GetTimeFormatsCore().