Terraria: System.Globalization.CultureData.InitIcuCultureDataCore
InitIcuCultureDataCore()
bool System.Globalization.CultureData.InitIcuCultureDataCore () inline private
Definition at line 1854 of file CultureData.cs.
    {
        string text = _sRealName;
        if (!IsValidCultureName(text, out var indexOfUnderscore))
        {
            return false;
        }
        ReadOnlySpan<char> readOnlySpan = default(ReadOnlySpan<char>);
        if (indexOfUnderscore > 0)
        {
            readOnlySpan = text.AsSpan(indexOfUnderscore + 1);
            text = string.Concat(text.AsSpan(0, indexOfUnderscore), "@collation=", readOnlySpan);
        }
        if (!GetLocaleName(text, out _sWindowsName))
        {
            return false;
        }
        indexOfUnderscore = _sWindowsName.IndexOf("@collation=", StringComparison.Ordinal);
        if (indexOfUnderscore >= 0)
        {
            _sName = string.Concat(_sWindowsName.AsSpan(0, indexOfUnderscore), "_", readOnlySpan);
        }
        else
        {
            _sName = _sWindowsName;
        }
        _sRealName = _sName;
        _iLanguage = LCID;
        if (_iLanguage == 0)
        {
            _iLanguage = 4096;
        }
        _bNeutral = TwoLetterISOCountryName.Length == 0;
        _sSpecificCulture = (_bNeutral ? IcuLocaleData.GetSpecificCultureName(_sRealName) : _sRealName);
        if (indexOfUnderscore > 0 && !_bNeutral && !IsCustomCultureId(_iLanguage))
        {
            _sName = _sWindowsName.Substring(0, indexOfUnderscore);
        }
        return true;
    }
References System.Globalization.CultureData._bNeutral, System.Globalization.CultureData._iLanguage, System.Globalization.CultureData._sName, System.Globalization.CultureData._sRealName, System.Globalization.CultureData._sSpecificCulture, System.Globalization.CultureData._sWindowsName, System.Globalization.CultureData.GetLocaleName(), System.Globalization.IcuLocaleData.GetSpecificCultureName(), System.Globalization.CultureData.IsCustomCultureId(), System.Globalization.CultureData.IsValidCultureName(), System.Globalization.CultureData.LCID, and System.text.
Referenced by System.Globalization.CultureData.InitCultureDataCore().