Terraria: System.Globalization.CultureData.IcuEnumCultures
IcuEnumCultures()
static CultureInfo[] System.Globalization.CultureData.IcuEnumCultures (CultureTypes types) inline static private
Definition at line 2088 of file CultureData.cs.
    {
        if ((types & (CultureTypes.NeutralCultures | CultureTypes.SpecificCultures)) == 0)
        {
            return Array.Empty<CultureInfo>();
        }
        int locales = Interop.Globalization.GetLocales(null, 0);
        if (locales <= 0)
        {
            return Array.Empty<CultureInfo>();
        }
        char[] array = new char[locales];
        locales = Interop.Globalization.GetLocales(array, locales);
        if (locales <= 0)
        {
            return Array.Empty<CultureInfo>();
        }
        bool flag = (types & CultureTypes.NeutralCultures) != 0;
        bool flag2 = (types & CultureTypes.SpecificCultures) != 0;
        List<CultureInfo> list = new List<CultureInfo>();
        if (flag)
        {
            list.Add(CultureInfo.InvariantCulture);
        }
        int num;
        for (int i = 0; i < locales; i += num)
        {
            num = array[i++];
            if (i + num <= locales)
            {
                CultureInfo cultureInfo = CultureInfo.GetCultureInfo(new string(array, i, num));
                if ((flag && cultureInfo.IsNeutralCulture) || (flag2 && !cultureInfo.IsNeutralCulture))
                {
                    list.Add(cultureInfo);
                }
            }
        }
        return list.ToArray();
    }
References System.array, System.Globalization.CultureInfo.GetCultureInfo(), Interop.Globalization.GetLocales(), System.Globalization.CultureInfo.InvariantCulture, and System.list.
Referenced by System.Globalization.CultureData.GetCultures().