Terraria: System.Globalization.CultureData.IcuGetLocaleInfo
IcuGetLocaleInfo() [3/4]
string System.Globalization.CultureData.IcuGetLocaleInfo (LocaleStringData type, string uiCultureName = null) inline private
Definition at line 1907 of file CultureData.cs.
    {
        return IcuGetLocaleInfo(_sWindowsName, type, uiCultureName);
    }
References System.Globalization.CultureData._sWindowsName, System.Globalization.CultureData.IcuGetLocaleInfo(), and System.type.
Referenced by System.Globalization.CultureData.GetLocaleInfoCore(), System.Globalization.CultureData.GetLocaleInfoCore(), System.Globalization.CultureData.GetLocaleInfoCore(), System.Globalization.CultureData.GetLocaleInfoCoreUserOverride(), System.Globalization.CultureData.GetLocaleInfoCoreUserOverride(), System.Globalization.CultureData.GetLocaleInfoCoreUserOverride(), System.Globalization.CultureData.IcuGetLanguageDisplayName(), System.Globalization.CultureData.IcuGetLocaleInfo(), and System.Globalization.CultureData.IcuGetLocaleInfo().