Terraria: System.Reflection.Metadata.Ecma335.FieldRVATableReader.FieldRVATableReader
FieldRVATableReader()
System.Reflection.Metadata.Ecma335.FieldRVATableReader.FieldRVATableReader (int numberOfRows, bool declaredSorted, int fieldTableRowRefSize, MemoryBlock containingBlock, int containingBlockOffset) inline package
Definition at line 19 of file FieldRVATableReader.cs.
    {
        NumberOfRows = numberOfRows;
        _IsFieldTableRowRefSizeSmall = fieldTableRowRefSize == 2;
        _RvaOffset = 0;
        _FieldOffset = _RvaOffset + 4;
        RowSize = _FieldOffset + fieldTableRowRefSize;
        Block = containingBlock.GetMemoryBlockAt(containingBlockOffset, RowSize * numberOfRows);
        if (!declaredSorted && !CheckSorted())
        {
            Throw.TableNotSorted(TableIndex.FieldRva);
        }
    }
References System.Reflection.Metadata.Ecma335.FieldRVATableReader._FieldOffset, System.Reflection.Metadata.Ecma335.FieldRVATableReader._IsFieldTableRowRefSizeSmall, System.Reflection.Metadata.Ecma335.FieldRVATableReader._RvaOffset, System.Reflection.Metadata.Ecma335.FieldRVATableReader.Block, System.Reflection.Metadata.Ecma335.FieldRVATableReader.CheckSorted(), System.Reflection.Internal.MemoryBlock.GetMemoryBlockAt(), System.Reflection.Metadata.Ecma335.FieldRVATableReader.NumberOfRows, System.Reflection.Metadata.Ecma335.FieldRVATableReader.RowSize, and System.Reflection.Throw.TableNotSorted().