Terraria: UICharacterNameButton.UICharacterNameButton
UICharacterNameButton()
UICharacterNameButton.UICharacterNameButton (LocalizedText titleText, LocalizedText emptyContentText, LocalizedText description = null) inline
     {
         Width = StyleDimension.FromPixels(400f);
         Height = StyleDimension.FromPixels(40f);
         Description = description;
         _BasePanelTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanel", (AssetRequestMode)1);
         _selectedBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", (AssetRequestMode)1);
         _hoveredBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelBorder", (AssetRequestMode)1);
         _textToShowWhenEmpty = emptyContentText;
         float textScale = 1f;
         UIText uIText = new UIText(titleText, textScale)
         {
             HAlign = 0f,
             VAlign = 0.5f,
             Left = StyleDimension.FromPixels(10f)
         };
         Append(uIText);
         _title = uIText;
         UIText uIText2 = new UIText(Language.GetText("UI.PlayerNameSlot"), textScale)
         {
             HAlign = 0f,
             VAlign = 0.5f,
             Left = StyleDimension.FromPixels(150f)
         };
         Append(uIText2);
         _text = uIText2;
         SetContents(null);
     }
References _BasePanelTexture, _hoveredBorderTexture, _selectedBorderTexture, _text, _textToShowWhenEmpty, _title, UIElement.Append(), Main.Assets, Description, StyleDimension.FromPixels(), Language.GetText(), UIElement.HAlign, UIElement.Height, UIElement.Left, SetContents(), UIElement.VAlign, and UIElement.Width.