Terraria: UICharacterNameButton.DrawSelf
DrawSelf()
override void UICharacterNameButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         if (_hovered)
         {
             if (!_soundedHover)
             {
                 SoundEngine.PlaySound(12);
             }
             _soundedHover = true;
         }
         else
         {
             _soundedHover = false;
         }
         CalculatedStyle dimensions = GetDimensions();
         Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, Color.White * 0.5f);
         if (_hovered)
         {
             Utils.DrawSplicedPanel(spriteBatch, _hoveredBorderTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, Color.White);
         }
     }
References _BasePanelTexture, _hovered, _hoveredBorderTexture, _soundedHover, Color, Utils.DrawSplicedPanel(), UIElement.GetDimensions(), CalculatedStyle.Height, SoundEngine.PlaySound(), Asset< T >.Value, CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.