Terraria: System.Net.Http.CreditWaiter.RegisterCancellation
RegisterCancellation()
void System.Net.Http.CreditWaiter.RegisterCancellation (CancellationToken cancellationToken) inline private
Definition at line 32 of file CreditWaiter.cs.
    {
        _cancellationToken = cancellationToken;
        _registration = cancellationToken.UnsafeRegister(delegate(object s, CancellationToken cancellationToken)
        {
            ((CreditWaiter)s)._source.SetException(ExceptionDispatchInfo.SetCurrentStackTrace(new OperationCanceledException(cancellationToken)));
        }, this);
    }
References System.Net.Http.CreditWaiter.CreditWaiter(), System.Net.Http.CreditWaiter._cancellationToken, System.Net.Http.CreditWaiter._registration, System.cancellationToken, System.s, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace().
Referenced by System.Net.Http.CreditWaiter.CreditWaiter(), and System.Net.Http.CreditWaiter.ResetForAwait().