Terraria: System.Net.Http.CreditWaiter.Dispose
Dispose()
void System.Net.Http.CreditWaiter.Dispose () inline
Definition at line 56 of file CreditWaiter.cs.
    {
        if (UnregisterAndOwnCompletion())
        {
            _source.SetException(ExceptionDispatchInfo.SetCurrentStackTrace(new ObjectDisposedException("CreditManager", System.SR.net_http_disposed_while_in_use)));
        }
    }
References System.Net.Http.CreditWaiter._source, System.SR.net_http_disposed_while_in_use, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetException(), and System.Net.Http.CreditWaiter.UnregisterAndOwnCompletion().
Referenced by System.Net.Http.CreditManager.AdjustCredit(), and System.Net.Http.CreditManager.Dispose().