Terraria: Terraria.GameContent.UI.Elements.UIIconTextButton.UIIconTextButton
UIIconTextButton()
Terraria.GameContent.UI.Elements.UIIconTextButton.UIIconTextButton (LocalizedText title, Color textColor, string iconTexturePath, float textSize = 1f, float titleAlignmentX = 0::5f, float titleWidthReduction = 10f) inline
Definition at line 36 of file UIIconTextButton.cs.
    {
        Width = StyleDimension.FromPixels(44f);
        Height = StyleDimension.FromPixels(34f);
        _hoverColor = Color.White;
        _BasePanelTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/PanelGrayscale", (AssetRequestMode)1);
        _hoveredTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", (AssetRequestMode)1);
        if (iconTexturePath != null)
        {
            _iconTexture = Main.Assets.Request<Texture2D>(iconTexturePath, (AssetRequestMode)1);
        }
        SetColor(Color.Lerp(Color.Black, Colors.InventoryDefaultColor, FadeFromBlack), 1f);
        if (title != null)
        {
            SetText(title, textSize, textColor);
        }
    }
References Terraria.GameContent.UI.Elements.UIIconTextButton._BasePanelTexture, Terraria.GameContent.UI.Elements.UIIconTextButton._hoverColor, Terraria.GameContent.UI.Elements.UIIconTextButton._hoveredTexture, Terraria.GameContent.UI.Elements.UIIconTextButton._iconTexture, Terraria.Main.Assets, Microsoft.Xna.Framework.Color.Black, Terraria.GameContent.UI.Elements.UIIconTextButton.FadeFromBlack, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.UIElement.Height, Terraria.ID.Colors.InventoryDefaultColor, Microsoft.Xna.Framework.Color.Lerp(), Terraria.GameContent.UI.Elements.UIIconTextButton.SetColor(), Terraria.GameContent.UI.Elements.UIIconTextButton.SetText(), Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.