Terraria: Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.CreateGroup
CreateGroup()
static List< BatsGroupSkyEntity > Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.CreateGroup (Player player, FastRandom random) inline static
Definition at line 988 of file AmbientSky.cs.
        {
            List<BatsGroupSkyEntity> list = new List<BatsGroupSkyEntity>();
            int num = 100;
            int num2 = random.Next(20, 40);
            VirtualCamera virtualCamera = new VirtualCamera(player);
            SpriteEffects spriteEffects = ((!(Main.WindForVisuals > 0f)) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
            Vector2 vector = default(Vector2);
            if (spriteEffects == SpriteEffects.FlipHorizontally)
            {
                vector.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
            }
            else
            {
                vector.X = virtualCamera.Position.X - (float)num;
            }
            vector.Y = random.NextFloat() * ((float)Main.worldSurface * 16f - 1600f - 2400f) + 2400f;
            float num3 = random.NextFloat() * 3f + 3f;
            int num4 = random.Next(30, 61) * 60;
            Vector2 vector2 = new Vector2(random.NextFloat() * 0.5f + 0.5f, random.NextFloat() * 0.5f + 0.5f);
            Vector2 targetOffset = new Vector2(random.NextFloat() * 2f - 1f, random.NextFloat() * 2f - 1f) * 100f;
            for (int i = 0; i < num2; i++)
            {
                BatsGroupSkyEntity batsGroupSkyEntity = new BatsGroupSkyEntity(player, random);
                batsGroupSkyEntity.Depth = num3 + random.NextFloat() * 0.5f;
                batsGroupSkyEntity.Position = vector + new Vector2(random.NextFloat() * 20f - 10f, random.NextFloat() * 3f) * 50f;
                batsGroupSkyEntity.Effects = spriteEffects;
                batsGroupSkyEntity.SetPositionInWorldBasedOnScreenSpace(batsGroupSkyEntity.Position);
                batsGroupSkyEntity.LifeTime = num4 + random.Next(301);
                batsGroupSkyEntity.SetMagnetization(vector2 * (random.NextFloat() * 0.3f + 0.85f) * 0.05f, targetOffset);
                list.Add(batsGroupSkyEntity);
            }
            return list;
        }
References Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.BatsGroupSkyEntity(), Terraria.Utilities.FastRandom.Next(), Terraria.Utilities.FastRandom.NextFloat(), and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Skies.AmbientSky.Spawn().