Terraria: System.Xml.Serialization.SerializableMapping.RetrieveSerializableSchema
RetrieveSerializableSchema()
void System.Xml.Serialization.SerializableMapping.RetrieveSerializableSchema () inline private
Definition at line 285 of file SerializableMapping.cs.
    {
        if (!_needSchema)
        {
            return;
        }
        _needSchema = false;
        if (_getSchemaMethod != null)
        {
            if (_schemas == null)
            {
                _schemas = new XmlSchemaSet();
            }
            object obj = _getSchemaMethod.Invoke(null, new object[1] { _schemas });
            _xsiType = XmlQualifiedName.Empty;
            if (obj != null)
            {
                if (typeof(XmlSchemaType).IsAssignableFrom(_getSchemaMethod.ReturnType))
                {
                    _xsdType = (XmlSchemaType)obj;
                    _xsiType = _xsdType.QualifiedName;
                }
                else
                {
                    if (!typeof(XmlQualifiedName).IsAssignableFrom(_getSchemaMethod.ReturnType))
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlGetSchemaMethodReturnType, _type.Name, _getSchemaMethod.Name, "XmlSchemaProviderAttribute", typeof(XmlQualifiedName).FullName));
                    }
                    _xsiType = (XmlQualifiedName)obj;
                    if (_xsiType.IsEmpty)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlGetSchemaEmptyTypeName, _type.FullName, _getSchemaMethod.Name));
                    }
                }
            }
            else
            {
                _any = true;
            }
            _schemas.ValidationEventHandler += ValidationCallbackWithErrorCode;
            _schemas.Compile();
            if (!_xsiType.IsEmpty && _xsiType.Namespace != "http://www.w3.org/2001/XMLSchema")
            {
                ArrayList arrayList = (ArrayList)_schemas.Schemas(_xsiType.Namespace);
                if (arrayList.Count == 0)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlMissingSchema, _xsiType.Namespace));
                }
                if (arrayList.Count > 1)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlGetSchemaInclude, _xsiType.Namespace, _getSchemaMethod.DeclaringType.FullName, _getSchemaMethod.Name));
                }
                XmlSchema xmlSchema = (XmlSchema)arrayList[0];
                if (xmlSchema == null)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlMissingSchema, _xsiType.Namespace));
                }
                _xsdType = (XmlSchemaType)xmlSchema.SchemaTypes[_xsiType];
                if (_xsdType == null)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlGetSchemaTypeMissing, _getSchemaMethod.DeclaringType.FullName, _getSchemaMethod.Name, _xsiType.Name, _xsiType.Namespace));
                }
                _xsdType = ((_xsdType.Redefined != null) ? _xsdType.Redefined : _xsdType);
            }
        }
        else
        {
            IXmlSerializable xmlSerializable = (IXmlSerializable)Activator.CreateInstance(_type);
            _schema = xmlSerializable.GetSchema();
            if (_schema != null && (_schema.Id == null || _schema.Id.Length == 0))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlSerializableNameMissing1, _type.FullName));
            }
        }
    }
References System.Xml.Serialization.SerializableMapping._any, System.Xml.Serialization.SerializableMapping._getSchemaMethod, System.Xml.Serialization.SerializableMapping._needSchema, System.Xml.Serialization.SerializableMapping._schema, System.Xml.Serialization.SerializableMapping._schemas, System.Xml.Serialization.SerializableMapping._type, System.Xml.Serialization.SerializableMapping._xsdType, System.Xml.Serialization.SerializableMapping._xsiType, System.Xml.Schema.XmlSchemaSet.Compile(), System.Activator.CreateInstance(), System.Reflection.MemberInfo.DeclaringType, System.Xml.Dictionary, System.Xml.XmlQualifiedName.Empty, System.SR.Format(), System.Type.FullName, System.FullName, System.Xml.Schema.XmlSchema.Id, System.Reflection.MethodBase.Invoke(), System.Xml.XmlQualifiedName.IsEmpty, System.Reflection.MemberInfo.Name, System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, System.obj, System.Xml.Schema.XmlSchemaType.QualifiedName, System.Xml.Schema.XmlSchemaType.Redefined, System.Reflection.MethodInfo.ReturnType, System.Xml.Schema.XmlSchemaSet.Schemas(), System.Xml.Serialization.SerializableMapping.ValidationCallbackWithErrorCode(), System.SR.XmlGetSchemaEmptyTypeName, System.SR.XmlGetSchemaInclude, System.SR.XmlGetSchemaMethodReturnType, System.SR.XmlGetSchemaTypeMissing, System.SR.XmlMissingSchema, and System.SR.XmlSerializableNameMissing1.