Terraria: System.Xml.Serialization.SerializableMapping.CheckDuplicateElement
CheckDuplicateElement()
void System.Xml.Serialization.SerializableMapping.CheckDuplicateElement (XmlSchemaElement element, string elementNs) inline package
Definition at line 211 of file SerializableMapping.cs.
    {
        if (element == null || element.Parent == null || !(element.Parent is XmlSchema))
        {
            return;
        }
        XmlSchemaObjectTable xmlSchemaObjectTable = null;
        if (Schema != null && Schema.TargetNamespace == elementNs)
        {
            XmlSchemas.Preprocess(Schema);
            xmlSchemaObjectTable = Schema.Elements;
        }
        else
        {
            if (Schemas == null)
            {
                return;
            }
            xmlSchemaObjectTable = Schemas.GlobalElements;
        }
        foreach (XmlSchemaElement value in xmlSchemaObjectTable.Values)
        {
            if (value.Name == element.Name && value.QualifiedName.Namespace == elementNs)
            {
                if (Match(value, element))
                {
                    break;
                }
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlSerializableRootDupName, _getSchemaMethod.DeclaringType.FullName, value.Name, elementNs));
            }
        }
    }
References System.Xml.Serialization.SerializableMapping._getSchemaMethod, System.Reflection.MemberInfo.DeclaringType, System.Xml.Dictionary, System.SR.Format(), System.Type.FullName, System.Xml.Schema.XmlSchemaSet.GlobalElements, System.Xml.Serialization.SerializableMapping.Match(), System.Xml.Schema.XmlSchemaObject.Parent, System.Xml.Serialization.XmlSchemas.Preprocess(), System.Xml.Serialization.SerializableMapping.Schemas, System.value, and System.SR.XmlSerializableRootDupName.