Terraria: System.Runtime.Serialization.XmlReaderDelegator.ReadExtensionData
ReadExtensionData()
IDataNode System.Runtime.Serialization.XmlReaderDelegator.ReadExtensionData (Type valueType) inline package inherited
Definition at line 446 of file XmlReaderDelegator.cs.
    {
        switch (Type.GetTypeCode(valueType))
        {
        case TypeCode.Boolean:
            return new DataNode<bool>(ReadContentAsBoolean());
        case TypeCode.Char:
            return new DataNode<char>(ReadContentAsChar());
        case TypeCode.Byte:
            return new DataNode<byte>(ReadContentAsUnsignedByte());
        case TypeCode.Int16:
            return new DataNode<short>(ReadContentAsShort());
        case TypeCode.Int32:
            return new DataNode<int>(ReadContentAsInt());
        case TypeCode.Int64:
            return new DataNode<long>(ReadContentAsLong());
        case TypeCode.Single:
            return new DataNode<float>(ReadContentAsSingle());
        case TypeCode.Double:
            return new DataNode<double>(ReadContentAsDouble());
        case TypeCode.Decimal:
            return new DataNode<decimal>(ReadContentAsDecimal());
        case TypeCode.DateTime:
            return new DataNode<DateTime>(ReadContentAsDateTime());
        case TypeCode.String:
            return new DataNode<string>(ReadContentAsString());
        case TypeCode.SByte:
            return new DataNode<sbyte>(ReadContentAsSignedByte());
        case TypeCode.UInt16:
            return new DataNode<ushort>(ReadContentAsUnsignedShort());
        case TypeCode.UInt32:
            return new DataNode<uint>(ReadContentAsUnsignedInt());
        case TypeCode.UInt64:
            return new DataNode<ulong>(ReadContentAsUnsignedLong());
        default:
            if (valueType == Globals.TypeOfByteArray)
            {
                return new DataNode<byte[]>(ReadContentAsBase64());
            }
            if (valueType == Globals.TypeOfObject)
            {
                return new DataNode<object>(new object());
            }
            if (valueType == Globals.TypeOfTimeSpan)
            {
                return new DataNode<TimeSpan>(ReadContentAsTimeSpan());
            }
            if (valueType == Globals.TypeOfGuid)
            {
                return new DataNode<Guid>(ReadContentAsGuid());
            }
            if (valueType == Globals.TypeOfUri)
            {
                return new DataNode<Uri>(ReadContentAsUri());
            }
            if (valueType == Globals.TypeOfXmlQualifiedName)
            {
                return new DataNode<XmlQualifiedName>(ReadContentAsQName());
            }
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateInvalidPrimitiveTypeException(valueType));
        }
    }
References System.Runtime.Serialization.XmlReaderDelegator.CreateInvalidPrimitiveTypeException(), System.Runtime.Serialization.Dictionary, System.Type.GetTypeCode(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBoolean(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsChar(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsDateTime(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsDecimal(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsDouble(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsGuid(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsInt(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsLong(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsQName(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsShort(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsSignedByte(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsSingle(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsString(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsTimeSpan(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsUnsignedByte(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsUnsignedInt(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsUnsignedLong(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsUnsignedShort(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsUri(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.Globals.TypeOfByteArray, System.Runtime.Serialization.Globals.TypeOfGuid, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.Globals.TypeOfTimeSpan, System.Runtime.Serialization.Globals.TypeOfUri, and System.Runtime.Serialization.Globals.TypeOfXmlQualifiedName.