Terraria: System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64
ReadContentAsBase64() [1/2]
virtual byte[] System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64 () inline virtual
Reimplemented in System.Runtime.Serialization.Json.JsonReaderDelegator.
Definition at line 643 of file XmlReaderDelegator.cs.
    {
        if (isEndOfEmptyElement)
        {
            return Array.Empty<byte>();
        }
        if (dictionaryReader == null)
        {
            return ReadContentAsBase64(reader.ReadContentAsString());
        }
        return dictionaryReader.ReadContentAsBase64();
    }
References System.Runtime.Serialization.XmlReaderDelegator.dictionaryReader, System.Runtime.Serialization.XmlReaderDelegator.isEndOfEmptyElement, System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64(), System.Xml.XmlDictionaryReader.ReadContentAsBase64(), System.Xml.XmlReader.ReadContentAsString(), and System.Runtime.Serialization.XmlReaderDelegator.reader.
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsAnyType(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsBase64(), and System.Runtime.Serialization.XmlReaderDelegator.ReadExtensionData().