Terraria: System.Runtime.Serialization.XmlReaderDelegator.TryReadDecimalArray
TryReadDecimalArray()
bool System.Runtime.Serialization.XmlReaderDelegator.TryReadDecimalArray (XmlObjectSerializerReadContext context, XmlDictionaryString itemName, XmlDictionaryString itemNamespace, int arrayLength, [NotNullWhen(true)] out decimal[] array) inline package inherited
Definition at line 1055 of file XmlReaderDelegator.cs.
    {
        if (dictionaryReader == null)
        {
            array = null;
            return false;
        }
        if (arrayLength != -1)
        {
            CheckExpectedArrayLength(context, arrayLength);
            array = new decimal[arrayLength];
            int num = 0;
            int num2 = 0;
            while ((num = dictionaryReader.ReadArray(itemName, itemNamespace, array, num2, arrayLength - num2)) > 0)
            {
                num2 += num;
            }
            CheckActualArrayLength(arrayLength, num2, itemName, itemNamespace);
        }
        else
        {
            array = DecimalArrayHelperWithDictionaryString.Instance.ReadArray(dictionaryReader, itemName, itemNamespace, GetArrayLengthQuota(context));
            context.IncrementItemCount(array.Length);
        }
        return true;
    }
References System.array, System.Runtime.Serialization.XmlReaderDelegator.CheckActualArrayLength(), System.Runtime.Serialization.XmlReaderDelegator.CheckExpectedArrayLength(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlReaderDelegator.dictionaryReader, System.Runtime.Serialization.XmlReaderDelegator.GetArrayLengthQuota(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.Xml.DecimalArrayHelperWithDictionaryString.Instance, and System.Xml.XmlDictionaryReader.ReadArray().