Terraria: System.Runtime.Serialization.XmlReaderDelegator.CheckExpectedArrayLength
CheckExpectedArrayLength()
void System.Runtime.Serialization.XmlReaderDelegator.CheckExpectedArrayLength (XmlObjectSerializerReadContext context, int arrayLength) inline private inherited
Definition at line 983 of file XmlReaderDelegator.cs.
    {
        context.IncrementItemCount(arrayLength);
    }
References System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.TryReadBooleanArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDateTimeArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDecimalArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDoubleArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadInt32Array(), System.Runtime.Serialization.XmlReaderDelegator.TryReadInt64Array(), and System.Runtime.Serialization.XmlReaderDelegator.TryReadSingleArray().