Terraria: System.Runtime.Serialization.XmlReaderDelegator.CheckActualArrayLength
CheckActualArrayLength()
void System.Runtime.Serialization.XmlReaderDelegator.CheckActualArrayLength (int expectedLength, int actualLength, XmlDictionaryString itemName, XmlDictionaryString itemNamespace) inline private inherited
Definition at line 993 of file XmlReaderDelegator.cs.
    {
        if (expectedLength != actualLength)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ArrayExceededSizeAttribute, expectedLength, itemName.Value, itemNamespace.Value)));
        }
    }
References System.SR.ArrayExceededSizeAttribute, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.TryReadBooleanArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDateTimeArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDecimalArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDoubleArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadInt32Array(), System.Runtime.Serialization.XmlReaderDelegator.TryReadInt64Array(), and System.Runtime.Serialization.XmlReaderDelegator.TryReadSingleArray().