Terraria: System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsString
ReadElementContentAsString()
string System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsString () inline package inherited
Definition at line 540 of file XmlReaderDelegator.cs.
    {
        if (isEndOfEmptyElement)
        {
            ThrowNotAtElement();
        }
        return reader.ReadElementContentAsString();
    }
References System.Runtime.Serialization.XmlReaderDelegator.isEndOfEmptyElement, System.Xml.XmlReader.ReadElementContentAsString(), System.Runtime.Serialization.XmlReaderDelegator.reader, and System.Runtime.Serialization.XmlReaderDelegator.ThrowNotAtElement().
Referenced by System.Runtime.Serialization.Json.JsonReaderDelegator.ReadElementContentAsChar(), System.Runtime.Serialization.Json.JsonReaderDelegator.ReadElementContentAsDateTime(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsUri(), System.Runtime.Serialization.EnumDataContract.ReadEnumValue(), and System.Runtime.Serialization.StringDataContract.ReadXmlValue().