Terraria: System.Runtime.Serialization.XmlReaderDelegator.ReadEndElement
ReadEndElement()
void System.Runtime.Serialization.XmlReaderDelegator.ReadEndElement () inline package inherited
Definition at line 358 of file XmlReaderDelegator.cs.
    {
        if (isEndOfEmptyElement)
        {
            Read();
        }
        else
        {
            reader.ReadEndElement();
        }
    }
References System.Runtime.Serialization.XmlReaderDelegator.isEndOfEmptyElement, System.Runtime.Serialization.XmlReaderDelegator.Read(), System.Xml.XmlReader.ReadEndElement(), and System.Runtime.Serialization.XmlReaderDelegator.reader.
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsAnyType(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsQName(), and System.Runtime.Serialization.ObjectDataContract.ReadXmlValue().