Terraria: System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsQName
ReadElementContentAsQName()
XmlQualifiedName System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsQName () inline package inherited
Definition at line 955 of file XmlReaderDelegator.cs.
    {
        Read();
        XmlQualifiedName result = ReadContentAsQName();
        ReadEndElement();
        return result;
    }
References System.Runtime.Serialization.XmlReaderDelegator.Read(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsQName(), and System.Runtime.Serialization.XmlReaderDelegator.ReadEndElement().
Referenced by System.Runtime.Serialization.QNameDataContract.ReadXmlValue().