Terraria: System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64
ReadContentAsBase64() [2/2]
byte[] System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64 (string str) inline package inherited
Definition at line 657 of file XmlReaderDelegator.cs.
    {
        if (str == null)
        {
            return null;
        }
        str = str.Trim();
        if (str.Length == 0)
        {
            return Array.Empty<byte>();
        }
        try
        {
            return Convert.FromBase64String(str);
        }
        catch (ArgumentException exception)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(str, "byte[]", exception));
        }
        catch (FormatException exception2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(str, "byte[]", exception2));
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.exception, System.Convert.FromBase64String(), System.str, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().