Terraria: System.Runtime.Serialization.XmlReaderDelegator.TryReadDateTimeArray
TryReadDateTimeArray()
virtual bool System.Runtime.Serialization.XmlReaderDelegator.TryReadDateTimeArray (XmlObjectSerializerReadContext context, XmlDictionaryString itemName, XmlDictionaryString itemNamespace, int arrayLength, [NotNullWhen(true)] out DateTime[] array) inline package virtual
Reimplemented in System.Runtime.Serialization.Json.JsonReaderDelegator.
Definition at line 1028 of file XmlReaderDelegator.cs.
    {
        if (dictionaryReader == null)
        {
            array = null;
            return false;
        }
        if (arrayLength != -1)
        {
            CheckExpectedArrayLength(context, arrayLength);
            array = new DateTime[arrayLength];
            int num = 0;
            int num2 = 0;
            while ((num = dictionaryReader.ReadArray(itemName, itemNamespace, array, num2, arrayLength - num2)) > 0)
            {
                num2 += num;
            }
            CheckActualArrayLength(arrayLength, num2, itemName, itemNamespace);
        }
        else
        {
            array = DateTimeArrayHelperWithDictionaryString.Instance.ReadArray(dictionaryReader, itemName, itemNamespace, GetArrayLengthQuota(context));
            context.IncrementItemCount(array.Length);
        }
        return true;
    }
References System.array, System.Runtime.Serialization.XmlReaderDelegator.CheckActualArrayLength(), System.Runtime.Serialization.XmlReaderDelegator.CheckExpectedArrayLength(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlReaderDelegator.dictionaryReader, System.Runtime.Serialization.XmlReaderDelegator.GetArrayLengthQuota(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.Xml.DateTimeArrayHelperWithDictionaryString.Instance, and System.Xml.XmlDictionaryReader.ReadArray().