Terraria: System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsLong
ReadContentAsLong()
long System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsLong () inline package inherited
Definition at line 727 of file XmlReaderDelegator.cs.
    {
        if (isEndOfEmptyElement)
        {
            ThrowConversionException(string.Empty, "Int64");
        }
        return reader.ReadContentAsLong();
    }
References System.Runtime.Serialization.XmlReaderDelegator.isEndOfEmptyElement, System.Xml.XmlReader.ReadContentAsLong(), System.Runtime.Serialization.XmlReaderDelegator.reader, and System.Runtime.Serialization.XmlReaderDelegator.ThrowConversionException().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsAnyType(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsUnsignedInt(), and System.Runtime.Serialization.XmlReaderDelegator.ReadExtensionData().