Terraria: System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsDateTime
ReadElementContentAsDateTime()
virtual DateTime System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsDateTime () inline package virtual
Reimplemented in System.Runtime.Serialization.Json.JsonReaderDelegator.
Definition at line 682 of file XmlReaderDelegator.cs.
    {
        if (isEndOfEmptyElement)
        {
            ThrowNotAtElement();
        }
        return XmlConvert.ToDateTime(reader.ReadElementContentAsString(), XmlDateTimeSerializationMode.RoundtripKind);
    }
References System.Runtime.Serialization.XmlReaderDelegator.isEndOfEmptyElement, System.Xml.XmlReader.ReadElementContentAsString(), System.Runtime.Serialization.XmlReaderDelegator.reader, System.Runtime.Serialization.XmlReaderDelegator.ThrowNotAtElement(), and System.Xml.XmlConvert.ToDateTime().
Referenced by System.Runtime.Serialization.DateTimeDataContract.ReadXmlValue().