Terraria: System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsBase64
ReadElementContentAsBase64()
virtual byte[] System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsBase64 () inline package virtual
Reimplemented in System.Runtime.Serialization.Json.JsonReaderDelegator.
Definition at line 630 of file XmlReaderDelegator.cs.
    {
        if (isEndOfEmptyElement)
        {
            ThrowNotAtElement();
        }
        if (dictionaryReader == null)
        {
            return ReadContentAsBase64(reader.ReadElementContentAsString());
        }
        return dictionaryReader.ReadElementContentAsBase64();
    }
References System.Runtime.Serialization.XmlReaderDelegator.dictionaryReader, System.Runtime.Serialization.XmlReaderDelegator.isEndOfEmptyElement, System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64(), System.Xml.XmlDictionaryReader.ReadElementContentAsBase64(), System.Xml.XmlReader.ReadElementContentAsString(), System.Runtime.Serialization.XmlReaderDelegator.reader, and System.Runtime.Serialization.XmlReaderDelegator.ThrowNotAtElement().
Referenced by System.Runtime.Serialization.ByteArrayDataContract.ReadXmlValue().