Terraria: System.Threading.Tasks.Task.FinishSlow
FinishSlow()
void System.Threading.Tasks.Task< TResult >.FinishSlow (bool userDelegateExecute) inline private inherited
Definition at line 1851 of file Task.cs.
    {
        if (!userDelegateExecute)
        {
            FinishStageTwo();
            return;
        }
        ContingentProperties contingentProperties = m_contingentProperties;
        if (contingentProperties.m_completionCountdown == 1 || Interlocked.Decrement(ref contingentProperties.m_completionCountdown) == 0)
        {
            FinishStageTwo();
        }
        else
        {
            AtomicStateUpdate(8388608, 23068672);
        }
        List<Task> exceptionalChildren = contingentProperties.m_exceptionalChildren;
        if (exceptionalChildren == null)
        {
            return;
        }
        lock (exceptionalChildren)
        {
            exceptionalChildren.RemoveAll((Task t) => t.IsExceptionObservedByParent);
        }
    }
References System.Threading.Tasks.Task< TResult >.AtomicStateUpdate(), System.Threading.Interlocked.Decrement(), System.Threading.Tasks.Task< TResult >.FinishStageTwo(), System.Threading.Tasks.Task< TResult >.IsExceptionObservedByParent, and System.Threading.Tasks.Task< TResult >.m_contingentProperties.
Referenced by System.Threading.Tasks.Task< TResult >.Finish().