Terraria: System.Threading.Tasks.Task.AddToActiveTasks
AddToActiveTasks() [2/2]
static bool System.Threading.Tasks.Task< TResult >.AddToActiveTasks (Task< TResult > task) inline static package inherited
Definition at line 1186 of file Task.cs.
    {
        Dictionary<int, Task> dictionary = Volatile.Read(ref s_currentActiveTasks) ?? Interlocked.CompareExchange(ref s_currentActiveTasks, new Dictionary<int, Task>(), null) ?? s_currentActiveTasks;
        int id = task.Id;
        lock (dictionary)
        {
            dictionary[id] = task;
        }
        return true;
    }
References System.Threading.Interlocked.CompareExchange(), System.dictionary, System.Threading.Volatile.Read(), System.Threading.Tasks.Task< TResult >.s_currentActiveTasks, and System.task.
Referenced by System.Threading.Tasks.TaskFactory< TResult >.CompleteOnCountdownPromise< T >.CompleteOnCountdownPromise(), System.Threading.Tasks.TaskFactory< TResult >.CompleteOnCountdownPromise< T >.CompleteOnCountdownPromise(), System.Threading.Tasks.TaskFactory< TResult >.CompleteOnInvokePromise.CompleteOnInvokePromise(), System.Threading.Tasks.ContinueWithTaskContinuation.ContinueWithTaskContinuation(), System.Threading.Tasks.Task< TResult >.DelayPromise.DelayPromise(), System.Threading.Tasks.UnwrapPromise< TResult >.UnwrapPromise(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.WhenAllPromise(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.WhenAllPromise(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1 >(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2 >(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2, TArg3 >(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.GetStateMachineBox< TStateMachine >(), System.Runtime.CompilerServices.TaskAwaiter< TResult >.OutputWaitEtwEvents(), and System.Threading.Tasks.Task< TResult >.ScheduleAndStart().