Terraria: System.Threading.Tasks.Task.Task
Task() [17/26]
System.Threading.Tasks.Task< TResult >.Task (object state, TaskCreationOptions creationOptions, bool promiseStyle) inline package
Definition at line 1233 of file Task.cs.
    {
        if (((uint)creationOptions & 0xFFFFFFBBu) != 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.creationOptions);
        }
        if ((creationOptions & TaskCreationOptions.AttachedToParent) != 0)
        {
            Task internalCurrent = InternalCurrent;
            if (internalCurrent != null)
            {
                EnsureContingentPropertiesInitializedUnsafe().m_parent = internalCurrent;
            }
        }
        TaskConstructorCore(null, state, default(CancellationToken), creationOptions, InternalTaskOptions.PromiseTask, null);
    }
References System.creationOptions, System.Threading.Tasks.Task< TResult >.EnsureContingentPropertiesInitializedUnsafe(), System.Threading.Tasks.Task< TResult >.InternalCurrent, System.Threading.Tasks.Task< TResult >.ContingentProperties.m_parent, System.state, System.Threading.Tasks.Task< TResult >.TaskConstructorCore(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().