Terraria: System.Threading.Tasks.Task.ProcessChildCompletion
ProcessChildCompletion() [2/2]
void System.Threading.Tasks.Task< TResult >.ProcessChildCompletion (Task< TResult > childTask) inline package inherited
Definition at line 1953 of file Task.cs.
    {
        ContingentProperties contingentProperties = Volatile.Read(ref m_contingentProperties);
        if (childTask.IsFaulted && !childTask.IsExceptionObservedByParent)
        {
            if (contingentProperties.m_exceptionalChildren == null)
            {
                Interlocked.CompareExchange(ref contingentProperties.m_exceptionalChildren, new List<Task>(), null);
            }
            List<Task> exceptionalChildren = contingentProperties.m_exceptionalChildren;
            if (exceptionalChildren != null)
            {
                lock (exceptionalChildren)
                {
                    exceptionalChildren.Add(childTask);
                }
            }
        }
        if (Interlocked.Decrement(ref contingentProperties.m_completionCountdown) == 0)
        {
            FinishStageTwo();
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.Interlocked.CompareExchange(), System.Threading.Interlocked.Decrement(), System.Threading.Tasks.Task< TResult >.FinishStageTwo(), System.Threading.Tasks.Task< TResult >.m_contingentProperties, and System.Threading.Volatile.Read().
Referenced by System.Threading.Tasks.Task< TResult >.NotifyParentIfPotentiallyAttachedTask().