Terraria: System.Threading.Tasks.Task.RemoveFromActiveTasks
RemoveFromActiveTasks() [2/2]
static void System.Threading.Tasks.Task< TResult >.RemoveFromActiveTasks (Task< TResult > task) inline static package inherited
Definition at line 1197 of file Task.cs.
    {
        Dictionary<int, Task> dictionary = s_currentActiveTasks;
        if (dictionary == null)
        {
            return;
        }
        int id = task.Id;
        lock (dictionary)
        {
            dictionary.Remove(id);
        }
    }
References System.dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Threading.Tasks.Task< TResult >.s_currentActiveTasks, and System.task.
Referenced by System.Threading.Tasks.Task< TResult >.CancellationCleanupLogic(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.ClearStateUponCompletion(), System.Threading.Tasks.Task< TResult >.DelayPromise.CompleteTimedOut(), System.Threading.Tasks.Task< TResult >.FinishStageTwo(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncCoreLogic(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1 >(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2 >(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2, TArg3 >(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.Invoke(), System.Threading.Tasks.TaskFactory< TResult >.CompleteOnCountdownPromise< T >.Invoke(), System.Threading.Tasks.TaskFactory< TResult >.CompleteOnInvokePromise.Invoke(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.Invoke(), and System.Threading.Tasks.UnwrapPromise< TResult >.TrySetFromTask().