Terraria: System.Threading.Tasks.Task.WaitAnyCore
WaitAnyCore()
static int System.Threading.Tasks.Task< TResult >.WaitAnyCore (Task< TResult >[] tasks, int millisecondsTimeout, CancellationToken cancellationToken) inline static private inherited
Definition at line 3270 of file Task.cs.
    {
        if (tasks == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.tasks);
        }
        if (millisecondsTimeout < -1)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.millisecondsTimeout);
        }
        cancellationToken.ThrowIfCancellationRequested();
        int num = -1;
        for (int i = 0; i < tasks.Length; i++)
        {
            Task task = tasks[i];
            if (task == null)
            {
                ThrowHelper.ThrowArgumentException(ExceptionResource.Task_WaitMulti_NullTask, ExceptionArgument.tasks);
            }
            if (num == -1 && task.IsCompleted)
            {
                num = i;
            }
        }
        if (num == -1 && tasks.Length != 0)
        {
            Task<Task> task2 = TaskFactory.CommonCWAnyLogic(tasks, isSyncBlocking: true);
            if (task2.Wait(millisecondsTimeout, cancellationToken))
            {
                num = Array.IndexOf(tasks, task2.Result);
            }
            else
            {
                TaskFactory.CommonCWAnyLogicCleanup(task2);
            }
        }
        GC.KeepAlive(tasks);
        return num;
    }
References System.cancellationToken, System.Threading.Tasks.TaskFactory< TResult >.CommonCWAnyLogic(), System.Threading.Tasks.TaskFactory< TResult >.CommonCWAnyLogicCleanup(), System.Array.IndexOf(), System.GC.KeepAlive(), System.millisecondsTimeout, System.task, System.tasks, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.Threading.Tasks.Task< TResult >.WaitAny(), System.Threading.Tasks.Task< TResult >.WaitAny(), System.Threading.Tasks.Task< TResult >.WaitAny(), System.Threading.Tasks.Task< TResult >.WaitAny(), and System.Threading.Tasks.Task< TResult >.WaitAny().