Terraria: System.Threading.Tasks.Task.Start
Start() [2/4]
void System.Threading.Tasks.Task< TResult >.Start () inline inherited
Definition at line 1504 of file Task.cs.
    {
        Start(TaskScheduler.Current);
    }
References System.Threading.Tasks.TaskScheduler.Current, and System.Threading.Tasks.Task< TResult >.Start().
Referenced by System.Threading.Tasks.TaskReplicator.Replica< TState >.CreateNewReplica(), System.Threading.Tasks.TaskReplicator.Replica< TState >.Execute(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessAsyncIfNecessary(), System.IO.Strategies.BufferedFileStreamStrategy.ReadAsyncSlowPath(), System.Threading.Tasks.Task< TResult >.Start(), and System.IO.Strategies.BufferedFileStreamStrategy.WriteAsyncSlowPath().