Terraria: System.Threading.Tasks.Task.ConfigureAwait
ConfigureAwait() [2/3]
new ConfiguredTaskAwaitable< TResult > System.Threading.Tasks.Task< TResult >.ConfigureAwait (bool continueOnCapturedContext) inline inherited
Definition at line 226 of file Task.cs.
    {
        return new ConfiguredTaskAwaitable<TResult>(this, continueOnCapturedContext);
    }
Referenced by System.Threading.Tasks.TaskToApm.TaskAsyncResult.TaskAsyncResult(), System.Xml.XmlWellFormedWriter._AdvanceStateAsync_ContinueWhenFinish(), System.Xml.XmlTextReaderImpl._ParseDocumentContentAsync_WhiteSpace(), System.Xml.XmlTextReaderImpl._ParseElementAsync_ContinueWithSetElement(), System.Xml.XmlTextReaderImpl._ParseEndElmentAsync(), System.Xml.XmlTextReaderImpl._ParseTextAsync(), System.Xml.XmlEncodedRawTextWriter._RawTextAsync(), System.Xml.XmlUtf8RawTextWriter._RawTextAsync(), System.Xml.XsdValidatingReader._ReadAsync_Read(), System.Xml.XmlTextReaderImpl._ReadAsync_SwitchToInteractiveXmlDecl(), System.Xml.XmlEncodedRawTextWriter._WriteAttributeTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter._WriteAttributeTextBlockAsync(), System.Xml.XmlEncodedRawTextWriter._WriteElementTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter._WriteElementTextBlockAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.AsyncModeCopyToAsync(), System.Xml.XmlBaseWriter.AutoCompleteAsync(), System.Net.Http.HttpConnection.CheckUsabilityOnScavenge(), System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(), System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(), System.Net.Sockets.TcpClient.CompleteConnectAsync(), System.Security.Cryptography.HashAlgorithm.ComputeHashAsyncCore(), System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(), System.Net.Http.StreamToStreamCopy.CopyAsync(), System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.CopyToAsync(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.CopyToAsync(), System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore(), System.IO.BufferedStream.CopyToAsyncCore(), System.Security.Cryptography.CryptoStream.CopyToAsyncInternal(), System.Net.Http.HttpConnection.CopyToUntilEofWithExistingBufferedDataAsync(), System.IO.Strategies.BufferedFileStreamStrategy.DisposeAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.DisposeAsync(), System.IO.BufferedStream.DisposeAsync(), System.Text.TranscodingStream.DisposeAsync(), System.Text.Json.Utf8JsonWriter.DisposeAsync(), System.IO.StreamWriter.DisposeAsyncCore(), System.Xml.XmlEncodedRawTextWriter.DisposeAsyncCore(), System.Xml.XmlUtf8RawTextWriter.DisposeAsyncCore(), System.Xml.XmlWellFormedWriter.DisposeAsyncCore(), System.Net.WebClient.DownloadBitsAsync(), System.Xml.XmlTextReaderImpl.DtdParserProxy_ParsePIAsync(), System.Xml.Base64Encoder.EncodeAsync(), System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(), System.Xml.ReadContentAsBinaryHelper.FinishAsync(), System.Xml.XmlTextReaderImpl.FinishInitStreamAsync(), System.Xml.XmlTextReaderImpl.FinishInitTextReaderAsync(), System.Xml.XmlTextReaderImpl.FinishInitUriStringAsync(), System.Xml.XmlTextReaderImpl.FinishPartialValueAsync(), System.Xml.XmlCharCheckingReader.FinishReadBinaryAsync(), System.IO.Stream.FinishWriteAsync(), System.Xml.XmlStreamNodeWriter.FlushAndWriteBytesAsync(), System.Xml.XmlStreamNodeWriter.FlushAsync(), System.Xml.Base64Encoder.FlushAsync(), System.Xml.XmlEncodedRawTextWriter.FlushAsync(), System.Xml.XmlUtf8RawTextWriter.FlushAsync(), System.IO.Compression.DeflateStream.FlushAsync(), System.Text.Json.Utf8JsonWriter.FlushAsync(), System.IO.Compression.BrotliStream.FlushAsyncCore(), System.IO.StreamWriter.FlushAsyncInternal(), System.IO.Strategies.BufferedFileStreamStrategy.FlushAsyncInternal(), System.IO.BufferedStream.FlushAsyncInternal(), System.Xml.XmlStreamNodeWriter.FlushBufferAndWriteByteAsync(), System.Xml.XmlUtf8RawTextWriter.FlushBufferAsync(), System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(), System.Net.Http.Http2Connection.FlushOutgoingBytesAsync(), System.Xml.XmlBaseWriter.FlushTrailBytesAsync(), System.IO.BufferedStream.FlushWriteAsync(), System.Net.NetworkInformation.Ping.GetAddressAndSendAsync(), System.Xml.XmlStreamNodeWriter.GetBufferAsync(), System.Net.Http.HttpClient.GetByteArrayAsyncCore(), System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(), System.Net.Http.HttpClient.GetStringAsyncCore(), System.Net.Http.HttpConnection.InitialFillAsync(), System.Xml.ReadContentAsBinaryHelper.InitOnElementAsync(), System.Xml.XmlReader.InternalReadContentAsStringAsync(), System.Xml.Linq.XDocument.LoadAsyncInternal(), System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext(), System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.MoveNext(), System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.MoveNext(), System.Xml.ReadContentAsBinaryHelper.MoveToNextContentNodeAsync(), System.Threading.SemaphoreSlim.ConfiguredNoThrowAwaiter< T >.OnCompleted(), System.Xml.XmlTextReaderImpl.OpenAndPushAsync(), System.CodeDom.Compiler.IndentedTextWriter.OutputTabsAsync(), System.Xml.DtdParser.ParseCommentAsync(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ParseEntity(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(), System.Xml.XmlTextReaderImpl.ParseElementAsync_ReadData(), System.Xml.XmlTextReaderImpl.ParseElementContent_ReadData(), System.Xml.DtdParser.ParseExternalSubsetAsync(), System.Xml.DtdParser.ParseFreeFloatingDtdAsync(), System.Xml.DtdParser.ParseInDocumentDtdAsync(), System.Xml.DtdParser.ParsePIAsync(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.PeekFirstByteAsync(), System.Net.Security.SslStream.ProcessAuthenticationWithTelemetryAsync(), System.Xml.XsdValidatingReader.ProcessEndElementEventAsync(), System.Net.Http.Http2Connection.ProcessIncomingFramesAsync(), System.Xml.XmlCharCheckingReader.ReadAsync(), System.Xml.XsdCachingReader.ReadAsync(), System.Text.TranscodingStream.ReadAsync(), System.IO.Compression.BrotliStream.ReadAsync(), System.IO.Compression.SubReadStream.ReadAsync(), System.IO.Stream.ReadAsync(), System.Net.Http.HttpConnection.ReadAsync(), System.Security.Cryptography.CryptoStream.ReadAsyncInternal(), System.IO.Compression.DeflateStream.ReadAsyncMemory(), System.Net.Http.MultipartContent.ContentReadStream.ReadAsyncPrivate(), System.Diagnostics.AsyncStreamReader.ReadBufferAsync(), System.IO.StreamReader.ReadBufferAsync(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64Async(), System.Xml.XmlCharCheckingReader.ReadContentAsBase64Async(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHexAsync(), System.Xml.XmlCharCheckingReader.ReadContentAsBinHexAsync(), System.Xml.DtdParser.ReadDataAsync(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Xml.XmlReader.ReadElementContentAsAsync(), System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBase64Async(), System.Xml.XmlCharCheckingReader.ReadElementContentAsBase64Async(), System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinaryAsync(), System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHexAsync(), System.Xml.XmlCharCheckingReader.ReadElementContentAsBinHexAsync(), System.Xml.XmlReader.ReadElementContentAsObjectAsync(), System.Xml.XmlReader.ReadElementContentAsStringAsync(), System.Net.Http.Http2Connection.ReadFrameAsync(), System.IO.Strategies.BufferedFileStreamStrategy.ReadFromNonSeekableAsync(), System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(), System.Xml.XmlReader.ReadInnerXmlAsync(), System.Net.BufferedReadStream.ReadMoreAsync(), System.Xml.XmlReader.ReadOuterXmlAsync(), System.Xml.XsdValidatingReader.ReadTillEndElementAsync(), System.Xml.XmlTextReaderImpl.ReadValueChunkAsync(), System.Xml.Linq.XDocument.SaveAsync(), System.Xml.Linq.XDocument.SaveAsync(), System.Xml.DtdParser.ScanAttlist1Async(), System.Xml.DtdParser.ScanElement3Async(), System.Xml.DtdParser.ScanEntity1Async(), System.Xml.DtdParser.ScanNameExpectedAsync(), System.Xml.DtdParser.ScanQNameExpectedAsync(), System.Net.Http.RedirectHandler.SendAsync(), System.Net.Http.HttpMessageInvoker.SendAsync(), System.Net.Http.HttpClient.SendAsync(), System.Net.Http.DiagnosticsHandler.SendAsyncCore(), System.Net.Http.HttpConnection.SendAsyncCore(), System.Net.Http.Http3RequestStream.SendContentAsync(), System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(), System.Net.HttpWebRequest.SendRequest(), System.Net.WebSockets.WebSocket.SendWithArrayPoolAsync(), System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(), System.Net.Http.MultipartContent.SerializeToStreamAsyncCore(), System.Net.Http.Http2Connection.SetupAsync(), System.Xml.XmlReader.SetupReadElementContentAsXxxAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.ShutdownCompleted(), System.Xml.XmlTextReaderImpl.SkipAsync(), System.Xml.XsdCachingReader.SkipAsync(), System.Xml.XmlTextReaderImpl.SkipDtdAsync(), System.Xml.XmlTextReaderImpl.SkipPartialTextValueAsync(), System.Xml.XmlReader.SkipSubtreeAsync(), System.Xml.XmlBaseWriter.StartContentAsync(), System.Xml.XmlBaseWriter.StartElementAndWriteStartElementAsync(), System.Xml.XmlBaseWriter.StartElementAsync(), System.Xml.Schema.Parser.StartParsingAsync(), System.Threading.SemaphoreSlim.ConfiguredNoThrowAwaiter< T >.UnsafeOnCompleted(), System.Net.WebClient.UploadBitsAsync(), System.Net.Http.HttpContent.WaitAndReturnAsync< TState, TResult >(), System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteAsync(), System.IO.Compression.CheckSumAndSizeWriteStream.WriteAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteAsync(), System.IO.TextWriter.WriteAsync(), System.IO.Compression.DeflateStream.CopyToStream.WriteAsyncCore(), System.Security.Cryptography.CryptoStream.WriteAsyncCore(), System.Security.Cryptography.CryptoStream.WriteAsyncInternal(), System.IO.Compression.BrotliStream.WriteAsyncMemoryCore(), System.Xml.XmlWriter.WriteAttributesAsync(), System.Xml.XmlWriter.WriteAttributeStringAsyncHelper(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockAsync(), System.Xml.XmlBaseWriter.WriteBase64AsyncImpl(), System.Xml.XmlUTF8NodeWriter.WriteBase64TextAsync(), System.Xml.XmlWellFormedWriter.WriteBinHexAsync(), System.Xml.XmlCharCheckingWriter.WriteCDataAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCDataAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCDataAsync(), System.Xml.XmlWellFormedWriter.WriteCDataAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSectionAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSectionAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCharEntityAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCharEntityAsync(), System.Xml.XmlWellFormedWriter.WriteCharEntityAsync(), System.Xml.XmlWellFormedWriter.WriteCharsAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCommentAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteCommentAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCommentAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteCommentAsync(), System.Xml.XmlWellFormedWriter.WriteCommentAsync(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPiAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPiAsync(), System.IO.Compression.DeflateStream.WriteDeflaterOutputAsync(), System.Xml.XmlEncodedRawTextWriter.WriteDocTypeAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteDocTypeAsync(), System.Xml.XmlUtf8RawTextWriter.WriteDocTypeAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteDocTypeAsync(), System.Xml.XmlWellFormedWriter.WriteDocTypeAsync(), System.Xml.Linq.ElementWriter.WriteElementAsync(), System.Xml.XmlWriter.WriteElementStringAsync(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockAsync(), System.Xml.XmlUTF8NodeWriter.WriteEndAttributeAsync(), System.Xml.XmlBaseWriter.WriteEndAttributeAsyncImpl(), System.Xml.XmlWellFormedWriter.WriteEndDocumentAsync(), System.Xml.Linq.ElementWriter.WriteEndElementAsync(), System.Xml.XmlUTF8NodeWriter.WriteEndElementAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteEndElementAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteEndElementAsync(), System.Xml.XmlBaseWriter.WriteEndElementAsyncImpl(), System.Xml.XmlUTF8NodeWriter.WriteEndStartElementAsync(), System.Xml.XmlEncodedRawTextWriter.WriteEntityRefAsync(), System.Xml.XmlUtf8RawTextWriter.WriteEntityRefAsync(), System.Xml.XmlWellFormedWriter.WriteEntityRefAsync(), System.Xml.Linq.ElementWriter.WriteFullEndElementAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteFullEndElementAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteFullEndElementAsync(), System.Net.Http.HttpConnection.WriteHeadersAsync(), System.Net.Http.HttpConnection.WriteHostHeaderAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteIndentAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteIndentAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync(), System.IO.TextWriter.WriteLineAsync(), System.Xml.XmlWriter.WriteLocalNamespacesAsync(), System.Xml.XmlEncodedRawTextWriter.WriteNamespaceDeclarationAsync(), System.Xml.XmlUtf8RawTextWriter.WriteNamespaceDeclarationAsync(), System.Xml.XmlReader.WriteNodeAsync(), System.Xml.XmlWriter.WriteNodeAsync(), System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader(), System.Xml.XmlWriter.WriteNodeAsync_CallSyncReader(), System.Xml.XmlEncodedRawTextWriter.WriteProcessingInstructionAsync(), System.Xml.XmlUtf8RawTextWriter.WriteProcessingInstructionAsync(), System.Xml.XmlWellFormedWriter.WriteProcessingInstructionAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteProcessingInstructionAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteProcessingInstructionAsync(), System.Xml.XmlWellFormedWriter.WriteQualifiedNameAsync(), System.Xml.XmlWriter.WriteQualifiedNameAsync(), System.Xml.XmlRawWriter.WriteQualifiedNameAsync(), System.Xml.XmlEncodedRawTextWriter.WriteRawAsync(), System.Xml.XmlUtf8RawTextWriter.WriteRawAsync(), System.Xml.XmlWellFormedWriter.WriteRawAsync(), System.Xml.XmlEncodedRawTextWriter.WriteRawAsync(), System.Xml.XmlUtf8RawTextWriter.WriteRawAsync(), System.Xml.XmlWellFormedWriter.WriteRawAsync(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharCheckingAsync(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingAsync(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharCheckingAsync(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingAsync(), System.Net.Security.SslStream.WriteSingleChunk< TIOAdapter >(), System.Xml.XmlEncodedRawTextWriterIndent.WriteStartAttributeAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteStartAttributeAsync(), System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync_NoAdvanceState(), System.Xml.XmlWellFormedWriter.WriteStartDocumentImplAsync(), System.Xml.XmlUTF8NodeWriter.WriteStartElementAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteStartElementAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteStartElementAsync(), System.Xml.XmlWellFormedWriter.WriteStartElementAsync_FinishWrite(), System.Xml.XmlWellFormedWriter.WriteStartElementAsync_NoAdvanceState(), System.Xml.XmlEncodedRawTextWriter.WriteStartNamespaceDeclarationAsync(), System.Xml.XmlUtf8RawTextWriter.WriteStartNamespaceDeclarationAsync(), System.Xml.XmlWellFormedWriter.WriteStringAsync_NoAdvanceState(), System.Net.Http.HttpConnection.WriteStringAsyncSlow(), System.Xml.XmlEncodedRawTextWriter.WriteSurrogateCharEntityAsync(), System.Xml.XmlUtf8RawTextWriter.WriteSurrogateCharEntityAsync(), System.Xml.XmlWellFormedWriter.WriteSurrogateCharEntityAsync(), System.Xml.Linq.XDocument.WriteToAsyncInternal(), System.IO.Strategies.BufferedFileStreamStrategy.WriteToNonSeekableAsync(), System.IO.BufferedStream.WriteToUnderlyingStreamAsync(), System.Net.Http.HttpConnection.WriteTwoBytesSlowAsync(), System.Xml.XmlWellFormedWriter.WriteWhitespaceAsync(), System.Xml.XmlEncodedRawTextWriter.WriteXmlDeclarationAsync(), and System.Xml.XmlUtf8RawTextWriter.WriteXmlDeclarationAsync().