Terraria: System.Threading.Tasks.Task.InternalWaitCore
InternalWaitCore()
bool System.Threading.Tasks.Task< TResult >.InternalWaitCore (int millisecondsTimeout, CancellationToken cancellationToken) inline private inherited
Definition at line 2330 of file Task.cs.
    {
        if (IsCompleted)
        {
            return true;
        }
        TplEventSource log = TplEventSource.Log;
        bool flag = log.IsEnabled();
        if (flag)
        {
            Task internalCurrent = InternalCurrent;
            log.TaskWaitBegin(internalCurrent?.m_taskScheduler.Id ?? TaskScheduler.Default.Id, internalCurrent?.Id ?? 0, Id, TplEventSource.TaskWaitBehavior.Synchronous, 0);
        }
        Debugger.NotifyOfCrossThreadDependency();
        bool result = (millisecondsTimeout == -1 && !cancellationToken.CanBeCanceled && WrappedTryRunInline() && IsCompleted) || SpinThenBlockingWait(millisecondsTimeout, cancellationToken);
        if (flag)
        {
            Task internalCurrent2 = InternalCurrent;
            if (internalCurrent2 != null)
            {
                log.TaskWaitEnd(internalCurrent2.m_taskScheduler.Id, internalCurrent2.Id, Id);
            }
            else
            {
                log.TaskWaitEnd(TaskScheduler.Default.Id, 0, Id);
            }
            log.TaskWaitContinuationComplete(Id);
        }
        return result;
    }
References System.cancellationToken, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Id, System.Threading.Tasks.TaskScheduler.Id, System.Threading.Tasks.Task< TResult >.InternalCurrent, System.Threading.Tasks.Task< TResult >.IsCompleted, System.Threading.Tasks.TplEventSource.Log, System.Threading.Tasks.Task< TResult >.m_taskScheduler, System.millisecondsTimeout, System.Diagnostics.Debugger.NotifyOfCrossThreadDependency(), System.Threading.Tasks.Task< TResult >.SpinThenBlockingWait(), and System.Threading.Tasks.Task< TResult >.WrappedTryRunInline().
Referenced by System.Threading.Tasks.Task< TResult >.InternalWait().