Terraria: Terraria.GameContent.Biomes.CaveHouse.HouseUtils.GetHouseType
GetHouseType()
static HouseType Terraria.GameContent.Biomes.CaveHouse.HouseUtils.GetHouseType (IEnumerable< Rectangle > rooms) inline static private
Definition at line 135 of file HouseUtils.cs.
    {
        Dictionary<ushort, int> dictionary = new Dictionary<ushort, int>();
        foreach (Rectangle room in rooms)
        {
            WorldUtils.Gen(new Point(room.X - 10, room.Y - 10), new Shapes.Rectangle(room.Width + 20, room.Height + 20), new Actions.TileScanner(0, 59, 147, 1, 161, 53, 396, 397, 368, 367, 60, 70).Output(dictionary));
        }
        List<Tuple<HouseType, int>> list = new List<Tuple<HouseType, int>>();
        list.Add(Tuple.Create(HouseType.Wood, dictionary[0] + dictionary[1]));
        list.Add(Tuple.Create(HouseType.Jungle, dictionary[59] + dictionary[60] * 10));
        list.Add(Tuple.Create(HouseType.Mushroom, dictionary[59] + dictionary[70] * 10));
        list.Add(Tuple.Create(HouseType.Ice, dictionary[147] + dictionary[161]));
        list.Add(Tuple.Create(HouseType.Desert, dictionary[397] + dictionary[396] + dictionary[53]));
        list.Add(Tuple.Create(HouseType.Granite, dictionary[368]));
        list.Add(Tuple.Create(HouseType.Marble, dictionary[367]));
        list.Sort(SortBiomeResults);
        return list[0].Item1;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.dictionary, Terraria.WorldBuilding.WorldUtils.Gen(), System.list, Terraria.WorldBuilding.Actions.TileScanner.Output(), and Terraria.GameContent.Biomes.CaveHouse.HouseUtils.SortBiomeResults().
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateBuilder().