Terraria: System.Threading.Tasks.Task.FinishStageTwo
FinishStageTwo()
void System.Threading.Tasks.Task< TResult >.FinishStageTwo () inline private inherited
Definition at line 1878 of file Task.cs.
    {
        ContingentProperties contingentProperties = Volatile.Read(ref m_contingentProperties);
        if (contingentProperties != null)
        {
            AddExceptionsFromChildren(contingentProperties);
        }
        int num;
        if (ExceptionRecorded)
        {
            num = 2097152;
            if (TplEventSource.Log.IsEnabled())
            {
                TplEventSource.Log.TraceOperationEnd(Id, AsyncCausalityStatus.Error);
            }
            if (s_asyncDebuggingEnabled)
            {
                RemoveFromActiveTasks(this);
            }
        }
        else if (IsCancellationRequested && IsCancellationAcknowledged)
        {
            num = 4194304;
            if (TplEventSource.Log.IsEnabled())
            {
                TplEventSource.Log.TraceOperationEnd(Id, AsyncCausalityStatus.Canceled);
            }
            if (s_asyncDebuggingEnabled)
            {
                RemoveFromActiveTasks(this);
            }
        }
        else
        {
            num = 16777216;
            if (TplEventSource.Log.IsEnabled())
            {
                TplEventSource.Log.TraceOperationEnd(Id, AsyncCausalityStatus.Completed);
            }
            if (s_asyncDebuggingEnabled)
            {
                RemoveFromActiveTasks(this);
            }
        }
        Interlocked.Exchange(ref m_stateFlags, m_stateFlags | num);
        contingentProperties = Volatile.Read(ref m_contingentProperties);
        if (contingentProperties != null)
        {
            contingentProperties.SetCompleted();
            contingentProperties.UnregisterCancellationCallback();
        }
        FinishStageThree();
    }
References System.Threading.Tasks.Task< TResult >.AddExceptionsFromChildren(), System.Threading.Tasks.Task< TResult >.ExceptionRecorded, System.Threading.Interlocked.Exchange(), System.Threading.Tasks.Task< TResult >.FinishStageThree(), System.Threading.Tasks.Task< TResult >.Id, System.Threading.Tasks.Task< TResult >.IsCancellationAcknowledged, System.Threading.Tasks.Task< TResult >.IsCancellationRequested, System.Threading.Tasks.TplEventSource.Log, System.Threading.Tasks.Task< TResult >.m_contingentProperties, System.Threading.Tasks.Task< TResult >.m_stateFlags, System.Threading.Volatile.Read(), System.Threading.Tasks.Task< TResult >.RemoveFromActiveTasks(), and System.Threading.Tasks.Task< TResult >.s_asyncDebuggingEnabled.
Referenced by System.Threading.Tasks.Task< TResult >.Finish(), System.Threading.Tasks.Task< TResult >.FinishSlow(), and System.Threading.Tasks.Task< TResult >.ProcessChildCompletion().