Terraria: System.Threading.Tasks.Task.AddNewChild
AddNewChild() [2/2]
void System.Threading.Tasks.Task< TResult >.AddNewChild () inline package inherited
Definition at line 1485 of file Task.cs.
    {
        ContingentProperties contingentProperties = EnsureContingentPropertiesInitialized();
        if (contingentProperties.m_completionCountdown == 1)
        {
            contingentProperties.m_completionCountdown++;
        }
        else
        {
            Interlocked.Increment(ref contingentProperties.m_completionCountdown);
        }
    }
References System.Threading.Tasks.Task< TResult >.EnsureContingentPropertiesInitialized(), and System.Threading.Interlocked.Increment().
Referenced by System.Threading.Tasks.Task< TResult >.TaskConstructorCore().