Terraria: System.Threading.Tasks.Task.TrySetException
TrySetException() [2/2]
bool System.Threading.Tasks.Task< TResult >.TrySetException (object exceptionObject) inline package inherited
Definition at line 2542 of file Task.cs.
    {
        bool result = false;
        EnsureContingentPropertiesInitialized();
        if (AtomicStateUpdate(67108864, 90177536))
        {
            AddException(exceptionObject);
            Finish(userDelegateExecute: false);
            result = true;
        }
        return result;
    }
References System.Threading.Tasks.Task< TResult >.AddException(), System.Threading.Tasks.Task< TResult >.AtomicStateUpdate(), System.Threading.Tasks.Task< TResult >.EnsureContingentPropertiesInitialized(), and System.Threading.Tasks.Task< TResult >.Finish().
Referenced by System.Threading.Tasks.TaskFactory< TResult >.FromAsyncTrimPromise< TInstance >.Complete(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.Invoke(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.Invoke(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetException(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetException(), and System.Threading.Tasks.UnwrapPromise< TResult >.TrySetFromTask().