Terraria: System.Threading.Tasks.Task.GetAwaiter
GetAwaiter() [2/3]
new TaskAwaiter< TResult > System.Threading.Tasks.Task< TResult >.GetAwaiter () inline inherited
Definition at line 221 of file Task.cs.
    {
        return new TaskAwaiter<TResult>(this);
    }
Referenced by System.Net.Security.SslStream.AuthenticateAsClient(), System.Net.Security.SslStream.AuthenticateAsServer(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.Dispose(), System.IO.Stream.EndRead(), System.IO.Stream.EndWrite(), System.IO.Strategies.Net5CompatFileStreamStrategy.FillReadBufferForReadByte(), System.Net.Http.HttpBaseStream.Flush(), System.IO.Pipes.PipeStream.Read(), System.Net.Security.NegotiateStream.Read(), System.IO.Strategies.Net5CompatFileStreamStrategy.Read(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Read(), System.Net.Http.HttpMessageHandlerStage.Send(), System.IO.StreamBuffer.ResettableValueTaskSource.Wait(), System.Net.Security.SyncReadWriteAdapter.WaitAsync(), System.IO.Pipes.NamedPipeServerStream.WaitForConnection(), System.Net.Http.Http2Connection.Http2Stream.WaitForData(), System.Diagnostics.Process.WaitForExitCore(), System.IO.Pipes.PipeStream.Write(), System.Net.Http.HttpBaseStream.Write(), System.Net.Security.NegotiateStream.Write(), System.IO.Strategies.Net5CompatFileStreamStrategy.Write(), and System.Net.Quic.Implementations.MsQuic.MsQuicStream.Write().