Terraria: System.Threading.Tasks.Task.WaitAllCore
WaitAllCore()
static bool System.Threading.Tasks.Task< TResult >.WaitAllCore (Task< TResult >[] tasks, int millisecondsTimeout, CancellationToken cancellationToken) inline static private inherited
Definition at line 3079 of file Task.cs.
    {
        if (tasks == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.tasks);
        }
        if (millisecondsTimeout < -1)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.millisecondsTimeout);
        }
        cancellationToken.ThrowIfCancellationRequested();
        List<Exception> exceptions = null;
        List<Task> list = null;
        List<Task> list2 = null;
        bool flag = false;
        bool flag2 = false;
        bool flag3 = true;
        for (int num = tasks.Length - 1; num >= 0; num--)
        {
            Task task = tasks[num];
            if (task == null)
            {
                ThrowHelper.ThrowArgumentException(ExceptionResource.Task_WaitMulti_NullTask, ExceptionArgument.tasks);
            }
            bool flag4 = task.IsCompleted;
            if (!flag4)
            {
                if (millisecondsTimeout != -1 || cancellationToken.CanBeCanceled)
                {
                    AddToList(task, ref list, tasks.Length);
                }
                else
                {
                    flag4 = task.WrappedTryRunInline() && task.IsCompleted;
                    if (!flag4)
                    {
                        AddToList(task, ref list, tasks.Length);
                    }
                }
            }
            if (flag4)
            {
                if (task.IsFaulted)
                {
                    flag = true;
                }
                else if (task.IsCanceled)
                {
                    flag2 = true;
                }
                if (task.IsWaitNotificationEnabled)
                {
                    AddToList(task, ref list2, 1);
                }
            }
        }
        if (list != null)
        {
            flag3 = WaitAllBlockingCore(list, millisecondsTimeout, cancellationToken);
            if (flag3)
            {
                foreach (Task item in list)
                {
                    if (item.IsFaulted)
                    {
                        flag = true;
                    }
                    else if (item.IsCanceled)
                    {
                        flag2 = true;
                    }
                    if (item.IsWaitNotificationEnabled)
                    {
                        AddToList(item, ref list2, 1);
                    }
                }
            }
            GC.KeepAlive(tasks);
        }
        if (flag3 && list2 != null)
        {
            foreach (Task item2 in list2)
            {
                if (item2.NotifyDebuggerOfWaitCompletionIfNecessary())
                {
                    break;
                }
            }
        }
        if (flag3 && (flag || flag2))
        {
            if (!flag)
            {
                cancellationToken.ThrowIfCancellationRequested();
            }
            foreach (Task t in tasks)
            {
                AddExceptionsForCompletedTask(ref exceptions, t);
            }
            ThrowHelper.ThrowAggregateException(exceptions);
        }
        return flag3;
    }
References System.Threading.Tasks.Task< TResult >.AddExceptionsForCompletedTask(), System.cancellationToken, System.exceptions, System.item, System.GC.KeepAlive(), System.list, System.millisecondsTimeout, System.task, System.tasks, System.ThrowHelper.ThrowAggregateException(), System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.Threading.Tasks.Task< TResult >.WaitAllBlockingCore().
Referenced by System.Threading.Tasks.Task< TResult >.WaitAll(), System.Threading.Tasks.Task< TResult >.WaitAll(), System.Threading.Tasks.Task< TResult >.WaitAll(), System.Threading.Tasks.Task< TResult >.WaitAll(), and System.Threading.Tasks.Task< TResult >.WaitAll().