Terraria: System.Threading.Tasks.Task.AddTaskContinuation
AddTaskContinuation()
bool System.Threading.Tasks.Task< TResult >.AddTaskContinuation (object tc, bool addBeforeOthers) inline private inherited
Definition at line 2992 of file Task.cs.
    {
        if (IsCompleted)
        {
            return false;
        }
        if (m_continuationObject != null || Interlocked.CompareExchange(ref m_continuationObject, tc, null) != null)
        {
            return AddTaskContinuationComplex(tc, addBeforeOthers);
        }
        return true;
    }
References System.Threading.Tasks.Task< TResult >.AddTaskContinuationComplex(), System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.Task< TResult >.IsCompleted, and System.Threading.Tasks.Task< TResult >.m_continuationObject.
Referenced by System.Threading.Tasks.Task< TResult >.AddCompletionAction(), System.Threading.Tasks.Task< TResult >.ContinueWithCore(), System.Threading.Tasks.Task< TResult >.SetContinuationForAwait(), and System.Threading.Tasks.Task< TResult >.UnsafeSetContinuationForAwait().