Terraria: System.Threading.Tasks.Task.RunContinuations
RunContinuations()
void System.Threading.Tasks.Task< TResult >.RunContinuations (object continuationObject) inline private inherited
Definition at line 2581 of file Task.cs.
    {
        TplEventSource log = TplEventSource.Log;
        bool flag = log.IsEnabled();
        if (flag)
        {
            log.TraceSynchronousWorkBegin(Id, CausalitySynchronousWork.CompletionNotification);
        }
        bool flag2 = (m_stateFlags & 0x40) == 0 && RuntimeHelpers.TryEnsureSufficientExecutionStack();
        if (!(continuationObject is IAsyncStateMachineBox box))
        {
            if (!(continuationObject is Action action))
            {
                if (!(continuationObject is TaskContinuation taskContinuation))
                {
                    if (continuationObject is ITaskCompletionAction completionAction)
                    {
                        RunOrQueueCompletionAction(completionAction, flag2);
                        LogFinishCompletionNotification();
                        return;
                    }
                    List<object> list = (List<object>)continuationObject;
                    lock (list)
                    {
                    }
                    int count = list.Count;
                    if (flag2)
                    {
                        bool flag3 = false;
                        for (int i = 0; i < count; i++)
{
                            object obj = list[i];
                            if (obj == null)
{
                                continue;
                            }
                            if (obj is ContinueWithTaskContinuation continueWithTaskContinuation)
{
                                if ((continueWithTaskContinuation.m_options & TaskContinuationOptions.ExecuteSynchronously) == 0)
{
                                    list[i] = null;
                                    if (flag)
{
                                        log.RunningContinuationList(Id, i, continueWithTaskContinuation);
                                    }
                                    continueWithTaskContinuation.Run(this, canInlineContinuationTask: false);
                                }
                            }
                            else
{
                                if (obj is ITaskCompletionAction)
{
                                    continue;
                                }
                                if (flag3)
{
                                    list[i] = null;
                                    if (flag)
{
                                        log.RunningContinuationList(Id, i, obj);
                                    }
                                    if (!(obj is IAsyncStateMachineBox box2))
{
                                        if (obj is Action action2)
{
                                            AwaitTaskContinuation.RunOrScheduleAction(action2, allowInlining: false);
                                        }
                                        else
{
                                            ((TaskContinuation)obj).Run(this, canInlineContinuationTask: false);
                                        }
                                    }
                                    else
{
                                        AwaitTaskContinuation.RunOrScheduleAction(box2, allowInlining: false);
                                    }
                                }
                                flag3 = true;
                            }
                        }
                    }
                    for (int j = 0; j < count; j++)
                    {
                        object obj2 = list[j];
                        if (obj2 == null)
{
                            continue;
                        }
                        list[j] = null;
                        if (flag)
{
                            log.RunningContinuationList(Id, j, obj2);
                        }
                        if (!(obj2 is IAsyncStateMachineBox box3))
{
                            if (!(obj2 is Action action3))
{
                                if (obj2 is TaskContinuation taskContinuation2)
{
                                    taskContinuation2.Run(this, flag2);
                                }
                                else
{
                                    RunOrQueueCompletionAction((ITaskCompletionAction)obj2, flag2);
                                }
                            }
                            else
{
                                AwaitTaskContinuation.RunOrScheduleAction(action3, flag2);
                            }
                        }
                        else
{
                            AwaitTaskContinuation.RunOrScheduleAction(box3, flag2);
                        }
                    }
                    LogFinishCompletionNotification();
                }
                else
                {
                    taskContinuation.Run(this, flag2);
                    LogFinishCompletionNotification();
                }
            }
            else
            {
                AwaitTaskContinuation.RunOrScheduleAction(action, flag2);
                LogFinishCompletionNotification();
            }
        }
        else
        {
            AwaitTaskContinuation.RunOrScheduleAction(box, flag2);
            LogFinishCompletionNotification();
        }
    }
References System.action, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.Tasks.Task< TResult >.Id, System.list, System.Threading.Tasks.TplEventSource.Log, System.Threading.Tasks.Task< TResult >.LogFinishCompletionNotification(), System.Threading.Tasks.Task< TResult >.m_stateFlags, System.obj, System.Threading.Tasks.Task< TResult >.RunOrQueueCompletionAction(), System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(), and System.Runtime.CompilerServices.RuntimeHelpers.TryEnsureSufficientExecutionStack().
Referenced by System.Threading.Tasks.Task< TResult >.FinishContinuations().