Terraria: System.Xml.XmlDictionaryString.GetString
GetString()
static string System.Xml.XmlDictionaryString.GetString (XmlDictionaryString s) inline static package
Definition at line 104 of file XmlDictionaryString.cs.
    {
        return s?.Value;
    }
References System.s.
Referenced by System.Runtime.Serialization.XmlObjectSerializer.CheckIfNeedsContractNsAtRoot(), System.Runtime.Serialization.Json.XmlJsonReader.GetAttribute(), System.Xml.XmlDictionaryReader.GetAttribute(), System.Xml.XmlDictionaryReader.IsStartElement(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlExceptionHelper.ThrowFullStartElementExpected(), System.Xml.XmlExceptionHelper.ThrowStartElementExpected(), System.Runtime.Serialization.Json.JsonReaderDelegator.TryReadJsonDateTimeArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteStartAttribute(), System.Xml.XmlDictionaryWriter.WriteStartElement(), System.Xml.XmlDictionaryWriter.WriteString(), System.Xml.XmlDictionaryWriter.WriteValue(), System.Xml.XmlDictionaryWriter.WriteXmlAttribute(), and System.Xml.XmlDictionaryWriter.WriteXmlnsAttribute().