Terraria: System.Threading.Tasks.Task.ExecuteWithThreadLocal
ExecuteWithThreadLocal()
void System.Threading.Tasks.Task< TResult >.ExecuteWithThreadLocal (ref Task< TResult > currentTaskSlot, Thread threadPoolThread = null) inline private inherited
Definition at line 2046 of file Task.cs.
    {
        Task task = currentTaskSlot;
        TplEventSource log = TplEventSource.Log;
        Guid oldActivityThatWillContinue = default(Guid);
        bool flag = log.IsEnabled();
        if (flag)
        {
            if (log.TasksSetActivityIds)
            {
                EventSource.SetCurrentThreadActivityId(TplEventSource.CreateGuidForTaskID(Id), out oldActivityThatWillContinue);
            }
            if (task != null)
            {
                log.TaskStarted(task.m_taskScheduler.Id, task.Id, Id);
            }
            else
            {
                log.TaskStarted(TaskScheduler.Current.Id, 0, Id);
            }
            log.TraceSynchronousWorkBegin(Id, CausalitySynchronousWork.Execution);
        }
        try
        {
            currentTaskSlot = this;
            try
            {
                ExecutionContext capturedContext = CapturedContext;
                if (capturedContext == null)
                {
                    InnerInvoke();
                }
                else if (threadPoolThread == null)
                {
                    ExecutionContext.RunInternal(capturedContext, s_ecCallback, this);
                }
                else
                {
                    ExecutionContext.RunFromThreadPoolDispatchLoop(threadPoolThread, capturedContext, s_ecCallback, this);
                }
            }
            catch (Exception unhandledException)
            {
                HandleException(unhandledException);
            }
            if (flag)
            {
                log.TraceSynchronousWorkEnd(CausalitySynchronousWork.Execution);
            }
            Finish(userDelegateExecute: true);
        }
        finally
        {
            currentTaskSlot = task;
            if (flag)
            {
                if (task != null)
                {
                    log.TaskCompleted(task.m_taskScheduler.Id, task.Id, Id, IsFaulted);
                }
                else
                {
                    log.TaskCompleted(TaskScheduler.Current.Id, 0, Id, IsFaulted);
                }
                if (log.TasksSetActivityIds)
                {
                    EventSource.SetCurrentThreadActivityId(oldActivityThatWillContinue);
                }
            }
        }
    }
References System.Threading.Tasks.Task< TResult >.CapturedContext, System.Threading.Tasks.TplEventSource.CreateGuidForTaskID(), System.Threading.Tasks.TaskScheduler.Current, System.Threading.Tasks.Task< TResult >.Finish(), System.Threading.Tasks.Task< TResult >.HandleException(), System.Threading.Tasks.Task< TResult >.Id, System.Threading.Tasks.Task< TResult >.InnerInvoke(), System.Threading.Tasks.Task< TResult >.IsFaulted, System.Threading.Tasks.TplEventSource.Log, System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(), System.Threading.ExecutionContext.RunInternal(), System.Threading.Tasks.Task< TResult >.s_ecCallback, System.Diagnostics.Tracing.EventSource.SetCurrentThreadActivityId(), and System.task.
Referenced by System.Threading.Tasks.Task< TResult >.ExecuteEntry(), and System.Threading.Tasks.Task< TResult >.ExecuteEntryUnsafe().