Terraria: System.Threading.Tasks.Task.ExecuteEntryCancellationRequestedOrCanceled
ExecuteEntryCancellationRequestedOrCanceled() [2/2]
void System.Threading.Tasks.Task< TResult >.ExecuteEntryCancellationRequestedOrCanceled () inline package inherited
Definition at line 2034 of file Task.cs.
    {
        if (!IsCanceled)
        {
            int num = Interlocked.Exchange(ref m_stateFlags, m_stateFlags | 0x400000);
            if ((num & 0x400000) == 0)
            {
                CancellationCleanupLogic();
            }
        }
    }
References System.Threading.Tasks.Task< TResult >.CancellationCleanupLogic(), System.Threading.Interlocked.Exchange(), System.Threading.Tasks.Task< TResult >.IsCanceled, and System.Threading.Tasks.Task< TResult >.m_stateFlags.
Referenced by System.Threading.Tasks.Task< TResult >.ExecuteEntry(), and System.Threading.Tasks.Task< TResult >.ExecuteEntryUnsafe().