Terraria: System.Threading.Tasks.Task.Run
Run() [2/8]
static Task System.Threading.Tasks.Task< TResult >.Run (Action action) inline static inherited
Definition at line 3395 of file Task.cs.
    {
        return InternalStartNew(null, action, null, default(CancellationToken), TaskScheduler.Default, TaskCreationOptions.DenyChildAttach, InternalTaskOptions.None);
    }
References System.action, System.Threading.Tasks.TaskScheduler.Default, and System.Threading.Tasks.Task< TResult >.InternalStartNew().
Referenced by System.Diagnostics.AsyncStreamReader.BeginReadLine(), System.Net.Http.HttpConnectionPool.CheckForHttp11ConnectionInjection(), System.Net.Http.HttpConnectionPool.CheckForHttp2ConnectionInjection(), System.IO.Pipes.NamedPipeClientStream.ConnectAsync(), System.Net.Http.HttpConnectionPool.DisableHttp2Connection(), System.Net.WebRequest.GetRequestStreamAsync(), System.Net.WebRequest.GetResponseAsync(), System.Xml.XmlDownloadManager.GetStreamAsync(), System.Threading.Tasks.RendezvousAwaitable< TResult >.NotifyAwaiter(), System.Threading.Tasks.RendezvousAwaitable< TResult >.OnCompleted(), System.Threading.Tasks.Task< TResult >.Run(), System.Threading.Tasks.Task< TResult >.Run< TResult >(), and System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.UnsafeOnCompleted().