Terraria: System.Threading.Tasks.Task.NotifyDebuggerOfWaitCompletionIfNecessary
NotifyDebuggerOfWaitCompletionIfNecessary() [2/2]
bool System.Threading.Tasks.Task< TResult >.NotifyDebuggerOfWaitCompletionIfNecessary () inline package inherited
Definition at line 1438 of file Task.cs.
    {
        if (IsWaitNotificationEnabled && ShouldNotifyDebuggerOfWaitCompletion)
        {
            NotifyDebuggerOfWaitCompletion();
            return true;
        }
        return false;
    }
References System.Threading.Tasks.Task< TResult >.IsWaitNotificationEnabled, System.Threading.Tasks.Task< TResult >.NotifyDebuggerOfWaitCompletion(), and System.Threading.Tasks.Task< TResult >.ShouldNotifyDebuggerOfWaitCompletion.
Referenced by System.Threading.Tasks.Task< TResult >.GetResultCore(), System.Threading.Tasks.ContinuationResultTaskFromResultTask< TAntecedentResult, TResult >.InnerInvoke(), System.Threading.Tasks.ContinuationResultTaskFromTask< TResult >.InnerInvoke(), System.Threading.Tasks.ContinuationTaskFromResultTask< TAntecedentResult >.InnerInvoke(), System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke(), and System.Threading.Tasks.Task< TResult >.Wait().