Terraria: System.Xml.XmlDictionaryString.XmlDictionaryString
XmlDictionaryString()
System.Xml.XmlDictionaryString.XmlDictionaryString (IXmlDictionary dictionary, string value, int key) inline
Definition at line 84 of file XmlDictionaryString.cs.
    {
        if (dictionary == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("dictionary"));
        }
        if (value == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("value"));
        }
        if (key < 0 || key > 536870911)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("key", System.SR.Format(System.SR.ValueMustBeInRange, 0, 536870911)));
        }
        _dictionary = dictionary;
        _value = value;
        _key = key;
    }
References System.Xml.XmlDictionaryString._dictionary, System.Xml.XmlDictionaryString._key, System.Xml.XmlDictionaryString._value, System.dictionary, System.Xml.XmlDictionaryString.Dictionary, System.SR.Format(), System.key, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.value, and System.SR.ValueMustBeInRange.
Referenced by System.Xml.XmlDictionaryString.EmptyStringDictionary.EmptyStringDictionary().