Terraria: System.Threading.Tasks.Task.CancellationCleanupLogic
CancellationCleanupLogic() [2/2]
void System.Threading.Tasks.Task< TResult >.CancellationCleanupLogic () inline package inherited
Definition at line 2501 of file Task.cs.
    {
        Interlocked.Exchange(ref m_stateFlags, m_stateFlags | 0x400000);
        ContingentProperties contingentProperties = Volatile.Read(ref m_contingentProperties);
        if (contingentProperties != null)
        {
            contingentProperties.SetCompleted();
            contingentProperties.UnregisterCancellationCallback();
        }
        if (TplEventSource.Log.IsEnabled())
        {
            TplEventSource.Log.TraceOperationEnd(Id, AsyncCausalityStatus.Canceled);
        }
        if (s_asyncDebuggingEnabled)
        {
            RemoveFromActiveTasks(this);
        }
        FinishStageThree();
    }
References System.Threading.Interlocked.Exchange(), System.Threading.Tasks.Task< TResult >.FinishStageThree(), System.Threading.Tasks.Task< TResult >.Id, System.Threading.Tasks.TplEventSource.Log, System.Threading.Tasks.Task< TResult >.m_contingentProperties, System.Threading.Tasks.Task< TResult >.m_stateFlags, System.Threading.Volatile.Read(), System.Threading.Tasks.Task< TResult >.RemoveFromActiveTasks(), and System.Threading.Tasks.Task< TResult >.s_asyncDebuggingEnabled.
Referenced by System.Threading.Tasks.Task< TResult >.ExecuteEntryCancellationRequestedOrCanceled(), System.Threading.Tasks.Task< TResult >.InternalCancel(), System.Threading.Tasks.Task< TResult >.InternalCancelContinueWithInitialState(), and System.Threading.Tasks.Task< TResult >.TrySetCanceled().