Terraria: System.Threading.Tasks.Task.Task
Task() [26/26]
System.Threading.Tasks.Task< TResult >.Task (Delegate action, object state, Task< TResult > parent, CancellationToken cancellationToken, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, TaskScheduler scheduler) inline package
Definition at line 1290 of file Task.cs.
    {
        if ((object)action == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.action);
        }
        if (parent != null && (creationOptions & TaskCreationOptions.AttachedToParent) != 0)
        {
            EnsureContingentPropertiesInitializedUnsafe().m_parent = parent;
        }
        TaskConstructorCore(action, state, cancellationToken, creationOptions, internalOptions, scheduler);
        CapturedContext = ExecutionContext.Capture();
    }
References System.action, System.cancellationToken, System.Threading.ExecutionContext.Capture(), System.Threading.Tasks.Task< TResult >.CapturedContext, System.creationOptions, System.Threading.Tasks.Task< TResult >.EnsureContingentPropertiesInitializedUnsafe(), System.Threading.Tasks.Task< TResult >.ContingentProperties.m_parent, System.scheduler, System.state, System.Threading.Tasks.Task< TResult >.TaskConstructorCore(), and System.ThrowHelper.ThrowArgumentNullException().