Terraria: System.Threading.Tasks.Task.FromCanceled
FromCanceled() [2/4]
static Task System.Threading.Tasks.Task< TResult >.FromCanceled (CancellationToken cancellationToken) inline static inherited
Definition at line 3363 of file Task.cs.
    {
        if (!cancellationToken.IsCancellationRequested)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.cancellationToken);
        }
        return new Task(canceled: true, TaskCreationOptions.None, cancellationToken);
    }
References System.Threading.Tasks.Task< TResult >.Task(), System.cancellationToken, and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.IO.File.AppendAllLinesAsync(), System.IO.File.AppendAllTextAsync(), System.Data.Common.DbConnection.ChangeDatabaseAsync(), System.Data.Common.DbTransaction.CommitAsync(), System.IO.Pipes.NamedPipeClientStream.ConnectAsync(), System.IO.Compression.DeflateStream.CopyToAsync(), System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.CopyToAsync(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsync(), System.Net.Http.HttpConnection.ConnectionCloseReadStream.CopyToAsync(), System.Net.Http.HttpConnection.ContentLengthReadStream.CopyToAsync(), System.Net.Http.HttpConnection.RawConnectionStream.CopyToAsync(), System.IO.Strategies.AsyncWindowsFileStreamStrategy.CopyToAsync(), System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.CopyToAsync(), System.IO.BufferedStream.CopyToAsync(), System.IO.MemoryStream.CopyToAsync(), System.IO.Stream.NullStream.CopyToAsync(), System.Net.Http.EmptyContent.CreateContentReadStreamAsync(), System.Data.Common.ADP.CreatedTaskWithCancellation< T >(), System.Threading.Tasks.Task< TResult >.Delay(), System.Threading.AsyncMutex.EnterAsync(), System.IO.Compression.BrotliStream.FlushAsync(), System.IO.Compression.DeflateManagedStream.FlushAsync(), System.IO.Compression.DeflateStream.FlushAsync(), System.Net.Http.Http2Connection.Http2Stream.Http2WriteStream.FlushAsync(), System.Net.Http.HttpConnection.RawConnectionStream.FlushAsync(), System.Net.RequestStream.FlushAsync(), System.IO.Strategies.BufferedFileStreamStrategy.FlushAsync(), System.IO.BufferedStream.FlushAsync(), System.IO.FileStream.FlushAsync(), System.IO.MemoryStream.FlushAsync(), System.IO.Stream.NullStream.FlushAsync(), System.IO.UnmanagedMemoryStream.FlushAsync(), System.Security.Cryptography.CryptoStream.FlushAsync(), System.IO.StreamWriter.FlushAsyncInternal(), System.Threading.Tasks.Parallel.ForEachAsync< TSource >(), System.Threading.Tasks.Parallel.ForEachAsync< TSource >(), System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.Threading.Tasks.ValueTask< TResult >.FromCanceled< TResult >(), System.Data.Common.DbDataReader.GetColumnSchemaAsync(), System.Net.Dns.GetHostEntryOrAddressesCoreAsync(), System.Threading.Channels.ChannelUtilities.GetInvalidCompletionValueTask< T >(), System.Data.Common.DbConnection.GetSchemaAsync(), System.Data.Common.DbConnection.GetSchemaAsync(), System.Data.Common.DbConnection.GetSchemaAsync(), System.Data.Common.DbDataReader.GetSchemaTableAsync(), System.Threading.Tasks.ValueTask< TResult >.GetTaskForValueTaskSource(), System.Threading.Tasks.ValueTask< TResult >.GetTaskForValueTaskSource(), System.Xml.Linq.XDocument.LoadAsync(), System.Xml.Linq.XElement.LoadAsync(), System.Net.Http.HttpBaseStream.NopAsync(), System.Data.Common.DbConnection.OpenAsync(), System.Data.Common.DbCommand.PrepareAsync(), System.IO.File.ReadAllBytesAsync(), System.IO.File.ReadAllLinesAsync(), System.IO.File.ReadAllTextAsync(), System.IO.Pipes.PipeStream.ReadAsync(), System.IO.ReadOnlyMemoryStream.ReadAsync(), System.IO.BufferedStream.ReadAsync(), System.IO.FileStream.ReadAsync(), System.IO.MemoryStream.ReadAsync(), System.IO.Stream.NullStream.ReadAsync(), System.IO.Stream.ReadAsync(), System.IO.UnmanagedMemoryStream.ReadAsync(), System.Threading.Channels.BoundedChannel< T >.BoundedChannelReader.ReadAsync(), System.Threading.Channels.SingleConsumerUnboundedChannel< T >.UnboundedChannelReader.ReadAsync(), System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelReader.ReadAsync(), System.Threading.Channels.ChannelReader< T >.ReadAsync(), System.IO.MemoryStream.ReadAsync(), System.Xml.Linq.XNode.ReadFromAsync(), System.Data.Common.DbTransaction.ReleaseAsync(), System.Data.Common.DbTransaction.RollbackAsync(), System.Data.Common.DbTransaction.RollbackAsync(), System.Threading.Tasks.Task< TResult >.Run(), System.Data.Common.DbTransaction.SaveAsync(), System.Xml.Linq.XElement.SaveAsync(), System.Net.Http.SocketsHttpHandler.SendAsync(), System.Net.Mail.SmtpClient.SendMailAsync(), System.Net.Http.EmptyContent.SerializeToStreamAsync(), System.Threading.Tasks.TaskExtensions.Unwrap(), System.Threading.Tasks.TaskExtensions.Unwrap< TResult >(), System.Threading.SemaphoreSlim.WaitAsync(), System.Threading.Tasks.Task< TResult >.WaitAsync(), System.IO.Pipes.NamedPipeServerStream.WaitForConnectionAsync(), System.Threading.Channels.BoundedChannel< T >.BoundedChannelReader.WaitToReadAsync(), System.Threading.Channels.SingleConsumerUnboundedChannel< T >.UnboundedChannelReader.WaitToReadAsync(), System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelReader.WaitToReadAsync(), System.Threading.Channels.BoundedChannel< T >.BoundedChannelWriter.WaitToWriteAsync(), System.Threading.Channels.SingleConsumerUnboundedChannel< T >.UnboundedChannelWriter.WaitToWriteAsync(), System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelWriter.WaitToWriteAsync(), System.IO.File.WriteAllBytesAsync(), System.IO.File.WriteAllLinesAsync(), System.IO.File.WriteAllTextAsync(), System.IO.Pipes.PipeStream.WriteAsync(), System.IO.ChunkedMemoryStream.WriteAsync(), System.IO.FileStream.WriteAsync(), System.IO.MemoryStream.WriteAsync(), System.IO.Stream.NullStream.WriteAsync(), System.IO.Stream.WriteAsync(), System.IO.UnmanagedMemoryStream.WriteAsync(), System.IO.MemoryStream.WriteAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StringWriter.WriteAsync(), System.IO.TextWriter.SyncTextWriter.WriteAsync(), System.IO.TextWriter.WriteAsync(), System.IO.TextWriter.SyncTextWriter.WriteAsync(), System.IO.StringWriter.WriteAsync(), System.IO.TextWriter.WriteAsync(), System.Threading.Channels.BoundedChannel< T >.BoundedChannelWriter.WriteAsync(), System.Threading.Channels.SingleConsumerUnboundedChannel< T >.UnboundedChannelWriter.WriteAsync(), System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelWriter.WriteAsync(), System.Threading.Channels.ChannelWriter< T >.WriteAsync(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StringWriter.WriteLineAsync(), System.IO.TextWriter.SyncTextWriter.WriteLineAsync(), System.IO.TextWriter.WriteLineAsync(), System.IO.TextWriter.SyncTextWriter.WriteLineAsync(), System.IO.StringWriter.WriteLineAsync(), System.IO.TextWriter.WriteLineAsync(), System.Xml.Linq.XCData.WriteToAsync(), System.Xml.Linq.XComment.WriteToAsync(), System.Xml.Linq.XDocument.WriteToAsync(), System.Xml.Linq.XDocumentType.WriteToAsync(), System.Xml.Linq.XElement.WriteToAsync(), System.Xml.Linq.XProcessingInstruction.WriteToAsync(), and System.Xml.Linq.XText.WriteToAsync().