Terraria: System.Threading.Tasks.Task.SpinThenBlockingWait
SpinThenBlockingWait()
bool System.Threading.Tasks.Task< TResult >.SpinThenBlockingWait (int millisecondsTimeout, CancellationToken cancellationToken) inline private inherited
Definition at line 2361 of file Task.cs.
    {
        bool flag = millisecondsTimeout == -1;
        uint num = ((!flag) ? ((uint)Environment.TickCount) : 0u);
        bool flag2 = SpinWait(millisecondsTimeout);
        if (!flag2)
        {
            SetOnInvokeMres setOnInvokeMres = new SetOnInvokeMres();
            try
            {
                AddCompletionAction(setOnInvokeMres, addBeforeOthers: true);
                if (flag)
                {
                    bool flag3 = ThreadPool.NotifyThreadBlocked();
                    try
                    {
                        flag2 = setOnInvokeMres.Wait(-1, cancellationToken);
                    }
                    finally
                    {
                        if (flag3)
{
                            ThreadPool.NotifyThreadUnblocked();
                        }
                    }
                }
                else
                {
                    uint num2 = (uint)Environment.TickCount - num;
                    if (num2 < millisecondsTimeout)
                    {
                        bool flag4 = ThreadPool.NotifyThreadBlocked();
                        try
{
                            flag2 = setOnInvokeMres.Wait((int)(millisecondsTimeout - num2), cancellationToken);
                        }
                        finally
{
                            if (flag4)
{
                                ThreadPool.NotifyThreadUnblocked();
                            }
                        }
                    }
                }
            }
            finally
            {
                if (!IsCompleted)
                {
                    RemoveContinuation(setOnInvokeMres);
                }
            }
        }
        return flag2;
    }
References System.Threading.Tasks.Task< TResult >.AddCompletionAction(), System.cancellationToken, System.Threading.Tasks.Task< TResult >.IsCompleted, System.millisecondsTimeout, System.Threading.ThreadPool.NotifyThreadBlocked(), System.Threading.ThreadPool.NotifyThreadUnblocked(), System.Threading.Tasks.Task< TResult >.RemoveContinuation(), System.Threading.Tasks.Task< TResult >.SpinWait(), and System.Environment.TickCount.
Referenced by System.Threading.Tasks.Task< TResult >.InternalRunSynchronously(), and System.Threading.Tasks.Task< TResult >.InternalWaitCore().