Terraria: System.Runtime.Serialization.DataContract.DataContractCriticalHelper.SetDataContractName
SetDataContractName() [2/2]
void System.Runtime.Serialization.DataContract.DataContractCriticalHelper.SetDataContractName (XmlQualifiedName stableName) inline package inherited
Definition at line 1051 of file DataContract.cs.
        {
            XmlDictionary xmlDictionary = new XmlDictionary(2);
            Name = xmlDictionary.Add(stableName.Name);
            Namespace = xmlDictionary.Add(stableName.Namespace);
            StableName = stableName;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.Name, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.Namespace, and System.Runtime.Serialization.DataContract.DataContractCriticalHelper.StableName.
Referenced by System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ClassDataContractCriticalHelper(), System.Runtime.Serialization.GenericParameterDataContract.GenericParameterDataContractCriticalHelper.GenericParameterDataContractCriticalHelper(), System.Runtime.Serialization.PrimitiveDataContract.PrimitiveDataContractCriticalHelper.PrimitiveDataContractCriticalHelper(), System.Runtime.Serialization.SpecialTypeDataContract.SpecialTypeDataContractCriticalHelper.SpecialTypeDataContractCriticalHelper(), and System.Runtime.Serialization.SurrogateDataContract.SurrogateDataContractCriticalHelper.SurrogateDataContractCriticalHelper().