Terraria: System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException
ThrowInvalidDataContractException() [2/2]
static void System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException (string message, Type type) inline static package inherited
Definition at line 1018 of file DataContract.cs.
        {
            if (type != null)
            {
                lock (s_cacheLock)
                {
                    s_typeHandleRef.Value = GetDataContractAdapterTypeHandle(type.TypeHandle);
                    try
                    {
                        s_typeToIDCache.Remove(s_typeHandleRef);
                    }
                    catch (Exception ex)
                    {
                        throw DiagnosticUtility.ExceptionUtility.ThrowHelperFatal(ex.Message, ex);
                    }
                }
            }
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(message));
        }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractAdapterTypeHandle(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.s_cacheLock, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.s_typeHandleRef, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.s_typeToIDCache, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperFatal(), and System.type.
Referenced by System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateGetOnlyCollectionDataContract(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers(), System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.ImportDataMembers(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.IsValidExtensionDataSetMethod(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(), and System.Runtime.Serialization.DataContract.ThrowInvalidDataContractException().