Terraria: System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetBuiltInDataContract
GetBuiltInDataContract() [3/3]
static DataContract System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetBuiltInDataContract (Type type) inline static inherited
Definition at line 486 of file DataContract.cs.
        {
            if (type.IsInterface && !CollectionDataContract.IsCollectionInterface(type))
            {
                type = Globals.TypeOfObject;
            }
            lock (s_initBuiltInContractsLock)
            {
                if (s_typeToBuiltInContract == null)
                {
                    s_typeToBuiltInContract = new Dictionary<Type, DataContract>();
                }
                if (!s_typeToBuiltInContract.TryGetValue(type, out var value))
                {
                    TryCreateBuiltInDataContract(type, out value);
                    s_typeToBuiltInContract.Add(type, value);
                }
                return value;
            }
        }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CollectionDataContract.IsCollectionInterface(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.s_initBuiltInContractsLock, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.s_typeToBuiltInContract, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.TryCreateBuiltInDataContract(), System.type, System.Runtime.Serialization.Globals.TypeOfObject, and System.value.
Referenced by System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(), System.Runtime.Serialization.DataContract.GetBuiltInDataContract(), System.Runtime.Serialization.DataContract.GetBuiltInDataContract(), and System.Runtime.Serialization.DataContract.GetBuiltInDataContract().