Terraria: System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetId
GetId()
static int System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetId (RuntimeTypeHandle typeHandle) inline static package inherited
Definition at line 302 of file DataContract.cs.
        {
            lock (s_cacheLock)
            {
                typeHandle = GetDataContractAdapterTypeHandle(typeHandle);
                s_typeHandleRef.Value = typeHandle;
                if (!s_typeToIDCache.TryGetValue(s_typeHandleRef, out var value))
                {
                    int num = s_dataContractID++;
                    if (num >= s_dataContractCache.Length)
                    {
                        int num2 = ((num < 1073741823) ? (num * 2) : int.MaxValue);
                        if (num2 <= num)
{
                            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SerializationException(System.SR.DataContractCacheOverflow));
                        }
                        Array.Resize(ref s_dataContractCache, num2);
                    }
                    value = new IntRef(num);
                    try
                    {
                        s_typeToIDCache.Add(new TypeHandleRef(typeHandle), value);
                    }
                    catch (Exception ex)
                    {
                        throw DiagnosticUtility.ExceptionUtility.ThrowHelperFatal(ex.Message, ex);
                    }
                }
                return value.Value;
            }
        }
References System.SR.DataContractCacheOverflow, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractAdapterTypeHandle(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.s_cacheLock, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.s_dataContractCache, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.s_dataContractID, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.s_typeHandleRef, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.s_typeToIDCache, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperFatal(), and System.value.
Referenced by System.Runtime.Serialization.DataContract.GetId().