Terraria: System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation
GetDataContractSkipValidation()
static DataContract System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation (int id, RuntimeTypeHandle typeHandle, Type type) inline static package inherited
Definition at line 241 of file DataContract.cs.
        {
            DataContract dataContract = s_dataContractCache[id];
            if (dataContract == null)
            {
                dataContract = CreateDataContract(id, typeHandle, type);
                AssignDataContractToId(dataContract, id);
                return dataContract;
            }
            return dataContract.GetValidContract();
        }
References System.Runtime.Serialization.DataContract.DataContractCriticalHelper.AssignDataContractToId(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.s_dataContractCache, and System.type.
Referenced by System.Runtime.Serialization.DataContract.GetDataContractSkipValidation().