Terraria: System.Net.Http.Http2Connection.Http2Stream.OnStatus
OnStatus()
void System.Net.Http.Http2Connection.Http2Stream.OnStatus (int statusCode) inline private
Definition at line 808 of file Http2Connection.cs.
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace($"Status code is {statusCode}", "OnStatus");
            }
            AdjustHeaderBudget(10);
            lock (SyncObject)
            {
                if (_responseProtocolState == ResponseProtocolState.Aborted)
                {
                    return;
                }
                if (_responseProtocolState == ResponseProtocolState.ExpectingHeaders)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        Trace("Received extra status header.", "OnStatus");
                    }
                    throw new HttpRequestException(System.SR.net_http_invalid_response_multiple_status_codes);
                }
                if (_responseProtocolState != 0)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        Trace($"Status pseudo-header received in {_responseProtocolState} state.", "OnStatus");
                    }
                    throw new HttpRequestException(System.SR.net_http_invalid_response_pseudo_header_in_trailer);
                }
                _response.StatusCode = (HttpStatusCode)statusCode;
                if (statusCode < 200)
                {
                    _responseProtocolState = ResponseProtocolState.ExpectingIgnoredHeaders;
                    if (_response.StatusCode == HttpStatusCode.Continue && _expect100ContinueWaiter != null)
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            Trace("Received 100-Continue status.", "OnStatus");
                        }
                        _expect100ContinueWaiter.TrySetResult(result: true);
                    }
                    return;
                }
                _responseProtocolState = ResponseProtocolState.ExpectingHeaders;
                if (_expect100ContinueWaiter != null)
                {
                    bool result = statusCode < 300;
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        Trace($"Expecting 100 Continue but received final status {statusCode}.", "OnStatus");
                    }
                    _expect100ContinueWaiter.TrySetResult(result);
                }
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._expect100ContinueWaiter, System.Net.Http.Http2Connection.Http2Stream._response, System.Net.Http.Http2Connection.Http2Stream._responseProtocolState, System.Net.Http.Http2Connection.Http2Stream.AdjustHeaderBudget(), System.Net.NetEventSource.Log, System.SR.net_http_invalid_response_multiple_status_codes, System.SR.net_http_invalid_response_pseudo_header_in_trailer, System.Net.Http.HttpResponseMessage.StatusCode, System.Net.Http.Http2Connection.Http2Stream.SyncObject, System.Net.Http.Http2Connection.Http2Stream.Trace(), and System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetResult().
Referenced by System.Net.Http.Http2Connection.Http2Stream.OnHeader(), System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader(), and System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader().