Terraria: System.Net.Http.Http2Connection.Http2Stream.OnHeadersComplete
OnHeadersComplete()
void System.Net.Http.Http2Connection.Http2Stream.OnHeadersComplete (bool endStream) inline
Definition at line 952 of file Http2Connection.cs.
        {
            bool hasWaiter;
            lock (SyncObject)
            {
                switch (_responseProtocolState)
                {
                case ResponseProtocolState.Aborted:
                    return;
                case ResponseProtocolState.ExpectingHeaders:
                    _responseProtocolState = (endStream ? ResponseProtocolState.Complete : ResponseProtocolState.ExpectingData);
                    break;
                case ResponseProtocolState.ExpectingTrailingHeaders:
                    if (!endStream)
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            Trace("Trailing headers received without endStream", "OnHeadersComplete");
                        }
                        ThrowProtocolError();
                    }
                    _responseProtocolState = ResponseProtocolState.Complete;
                    break;
                case ResponseProtocolState.ExpectingIgnoredHeaders:
                    if (endStream)
                    {
                        ThrowProtocolError();
                    }
                    _responseProtocolState = ResponseProtocolState.ExpectingStatus;
                    return;
                default:
                    ThrowProtocolError();
                    break;
                }
                if (endStream)
                {
                    _responseCompletionState = StreamCompletionState.Completed;
                    if (_requestCompletionState == StreamCompletionState.Completed)
                    {
                        Complete();
                    }
                }
                if (_responseProtocolState == ResponseProtocolState.ExpectingData)
                {
                    _windowManager.Start();
                }
                hasWaiter = _hasWaiter;
                _hasWaiter = false;
            }
            if (hasWaiter)
            {
                _waitSource.SetResult(result: true);
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._hasWaiter, System.Net.Http.Http2Connection.Http2Stream._requestCompletionState, System.Net.Http.Http2Connection.Http2Stream._responseCompletionState, System.Net.Http.Http2Connection.Http2Stream._responseProtocolState, System.Net.Http.Http2Connection.Http2Stream._waitSource, System.Net.Http.Http2Connection.Http2Stream._windowManager, System.Net.Http.Http2Connection.Http2Stream.Complete(), System.Net.NetEventSource.Log, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetResult(), System.Net.Http.Http2Connection.Http2StreamWindowManager.Start(), System.Net.Http.Http2Connection.Http2Stream.SyncObject, System.Net.Http.Http2Connection.ThrowProtocolError(), and System.Net.Http.Http2Connection.Http2Stream.Trace().