Terraria: MS.Internal.Xml.Cache.XPathNodeHelper.GetInScopeNamespaces
GetInScopeNamespaces()
static int MS.Internal.Xml.Cache.XPathNodeHelper.GetInScopeNamespaces (XPathNode[] pageElem, int idxElem, out XPathNode[] pageNmsp) inline static
Definition at line 17 of file XPathNodeHelper.cs.
    {
        if (pageElem[idxElem].NodeType == XPathNodeType.Element)
        {
            XPathDocument document = pageElem[idxElem].Document;
            while (!pageElem[idxElem].HasNamespaceDecls)
            {
                idxElem = pageElem[idxElem].GetParent(out pageElem);
                if (idxElem == 0)
                {
                    return document.GetXmlNamespaceNode(out pageNmsp);
                }
            }
            return document.LookupNamespaces(pageElem, idxElem, out pageNmsp);
        }
        pageNmsp = null;
        return 0;
    }
References MS.Internal.Xml.Cache.XPathNode.Document, MS.Internal.Xml.Cache.XPathNode.GetParent(), System.Xml.XPath.XPathDocument.GetXmlNamespaceNode(), and System.Xml.XPath.XPathDocument.LookupNamespaces().
Referenced by MS.Internal.Xml.Cache.XPathDocumentNavigator.MoveToFirstNamespace().