Terraria: System.Net.Http.Http2Connection.Http2Stream.SendReset
SendReset()
void System.Net.Http.Http2Connection.Http2Stream.SendReset () inline private
Definition at line 656 of file Http2Connection.cs.
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace($"Stream reset. Request={_requestCompletionState}, Response={_responseCompletionState}.", "SendReset");
            }
            if (_resetException == null)
            {
                _connection.LogExceptions(_connection.SendRstStreamAsync(StreamId, Http2ProtocolErrorCode.Cancel));
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._connection, System.Net.Http.Http2Connection.Http2Stream._resetException, System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionBase.LogExceptions(), System.Net.Http.Http2Connection.SendRstStreamAsync(), System.Net.Http.Http2Connection.Http2Stream.StreamId, and System.Net.Http.Http2Connection.Http2Stream.Trace().
Referenced by System.Net.Http.Http2Connection.Http2Stream.Cancel(), and System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync().