Terraria: Terraria.Utilities.CrashDump.Write
Write() [1/3]
static bool Terraria.Utilities.CrashDump.Write (Options options, ExceptionInfo exceptionInfo, string outputDirectory) inline static private
Definition at line 71 of file CrashDump.cs.
    {
        if (!Platform.IsWindows)
        {
            return false;
        }
        string path = Path.Combine(outputDirectory, CreateDumpName());
        if (!Utils.TryCreatingDirectory(outputDirectory))
        {
            return false;
        }
        using FileStream fileStream = File.Create(path);
        return Write(fileStream.SafeFileHandle, options, exceptionInfo);
    }
References System.IO.Path.Combine(), System.IO.File.Create(), Terraria.Utilities.CrashDump.CreateDumpName(), ReLogic.OS.Platform.IsWindows, System.options, Terraria.Utils.TryCreatingDirectory(), and System.IO.Write.