Terraria: System.Net.Http.Http2Connection.Http2Stream.OnResponseData
OnResponseData()
void System.Net.Http.Http2Connection.Http2Stream.OnResponseData (ReadOnlySpan< byte > buffer, bool endStream) inline
Definition at line 1007 of file Http2Connection.cs.
        {
            bool hasWaiter;
            lock (SyncObject)
            {
                switch (_responseProtocolState)
                {
                case ResponseProtocolState.Aborted:
                    return;
                default:
                    ThrowProtocolError();
                    break;
                case ResponseProtocolState.ExpectingData:
                    break;
                }
                if (_responseBuffer.ActiveMemory.Length + buffer.Length > _windowManager.StreamWindowSize)
                {
                    ThrowProtocolError(Http2ProtocolErrorCode.FlowControlError);
                }
                _responseBuffer.EnsureAvailableSpace(buffer.Length);
                _responseBuffer.AvailableMemory.CopyFrom(buffer);
                _responseBuffer.Commit(buffer.Length);
                if (endStream)
                {
                    _responseProtocolState = ResponseProtocolState.Complete;
                    _responseCompletionState = StreamCompletionState.Completed;
                    if (_requestCompletionState == StreamCompletionState.Completed)
                    {
                        Complete();
                    }
                }
                hasWaiter = _hasWaiter;
                _hasWaiter = false;
            }
            if (hasWaiter)
            {
                _waitSource.SetResult(result: true);
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._hasWaiter, System.Net.Http.Http2Connection.Http2Stream._requestCompletionState, System.Net.Http.Http2Connection.Http2Stream._responseBuffer, System.Net.Http.Http2Connection.Http2Stream._responseCompletionState, System.Net.Http.Http2Connection.Http2Stream._responseProtocolState, System.Net.Http.Http2Connection.Http2Stream._waitSource, System.Net.Http.Http2Connection.Http2Stream._windowManager, System.buffer, System.Net.Http.Http2Connection.Http2Stream.Complete(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetResult(), System.Net.Http.Http2Connection.Http2StreamWindowManager.StreamWindowSize, System.Net.Http.Http2Connection.Http2Stream.SyncObject, and System.Net.Http.Http2Connection.ThrowProtocolError().