Terraria: System.Net.Http.Http2Connection.Http2Stream.Trace
Trace()
void System.Net.Http.Http2Connection.Http2Stream.Trace (string message, [CallerMemberName] string memberName = null) inline
Implements System.Net.Http.IHttpTrace.
Definition at line 1452 of file Http2Connection.cs.
        {
            _connection.Trace(StreamId, message, memberName);
        }
References System.Net.Http.Http2Connection.Http2Stream._connection, System.Net.Http.Http2Connection.Http2Stream.StreamId, and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.~Http2ReadStream(), System.Net.Http.Http2Connection.Http2Stream.Cancel(), System.Net.Http.Http2Connection.Http2Stream.Complete(), System.Net.Http.Http2Connection.Http2Stream.Initialize(), System.Net.Http.Http2Connection.Http2Stream.OnHeader(), System.Net.Http.Http2Connection.Http2Stream.OnHeader(), System.Net.Http.Http2Connection.Http2Stream.OnHeadersComplete(), System.Net.Http.Http2Connection.Http2Stream.OnReset(), System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader(), System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader(), System.Net.Http.Http2Connection.Http2Stream.OnStatus(), System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(), System.Net.Http.Http2Connection.Http2Stream.SendReset(), and System.Net.Http.Http2Connection.Http2Stream.WaitFor100ContinueAsync().