Terraria: System.Net.Http.Http2Connection.Http2Stream.WaitForData
WaitForData()
void System.Net.Http.Http2Connection.Http2Stream.WaitForData () inline private
Definition at line 1428 of file Http2Connection.cs.
        {
            new ValueTask(this, _waitSource.Version).AsTask().GetAwaiter().GetResult();
        }
References System.Net.Http.Http2Connection.Http2Stream._waitSource, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.Threading.Tasks.Task< TResult >.GetAwaiter(), and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.Version.
Referenced by System.Net.Http.Http2Connection.Http2Stream.CopyTo(), and System.Net.Http.Http2Connection.Http2Stream.ReadData().