Terraria: System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync
ReadDataAsync()
async ValueTask< int > System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync (Memory< byte > buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken) inline
Definition at line 1219 of file Http2Connection.cs.
        {
            if (buffer.Length == 0)
            {
                return 0;
            }
            var (flag, num) = TryReadFromBuffer(buffer.Span);
            if (flag)
            {
                await WaitForDataAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                (bool wait, int bytesRead) tuple2 = TryReadFromBuffer(buffer.Span);
                _ = tuple2.wait;
                num = tuple2.bytesRead;
            }
            if (num != 0)
            {
                _windowManager.AdjustWindow(num, this);
            }
            else
            {
                MoveTrailersToResponseMessage(responseMessage);
            }
            return num;
        }
References System.Net.Http.Http2Connection.Http2Stream._windowManager, System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindow(), System.buffer, System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.Http.Http2Connection.Http2Stream.MoveTrailersToResponseMessage(), System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(), System.Net.Http.Http2Connection.Http2Stream.wait, and System.Net.Http.Http2Connection.Http2Stream.WaitForDataAsync().