Terraria: System.Net.Http.Http2Connection.Http2Stream.Complete
Complete()
void System.Net.Http.Http2Connection.Http2Stream.Complete () inline private
Definition at line 668 of file Http2Connection.cs.
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace($"Stream complete. Request={_requestCompletionState}, Response={_responseCompletionState}.", "Complete");
            }
            _connection.RemoveStream(this);
            lock (_creditSyncObject)
            {
                CreditWaiter creditWaiter = _creditWaiter;
                if (creditWaiter != null)
                {
                    creditWaiter.Dispose();
                    _creditWaiter = null;
                }
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._connection, System.Net.Http.Http2Connection.Http2Stream._creditSyncObject, System.Net.Http.Http2Connection.Http2Stream._creditWaiter, System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.RemoveStream(), and System.Net.Http.Http2Connection.Http2Stream.Trace().
Referenced by System.Net.Http.Http2Connection.Http2Stream.Cancel(), System.Net.Http.Http2Connection.Http2Stream.OnHeadersComplete(), System.Net.Http.Http2Connection.Http2Stream.OnResponseData(), and System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync().