Terraria: System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState
CheckResponseBodyState()
void System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState () inline private
Definition at line 1090 of file Http2Connection.cs.
        {
            Exception resetException = _resetException;
            if (resetException != null)
            {
                if (_canRetry)
                {
                    ThrowRetry(System.SR.net_http_request_aborted, resetException);
                }
                ThrowRequestAborted(resetException);
            }
            if (_responseProtocolState == ResponseProtocolState.Aborted)
            {
                ThrowRequestAborted();
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._canRetry, System.Net.Http.Http2Connection.Http2Stream._resetException, System.Net.Http.Http2Connection.Http2Stream._responseProtocolState, System.SR.net_http_request_aborted, System.Net.Http.Http2Connection.ThrowRequestAborted(), and System.Net.Http.Http2Connection.ThrowRetry().
Referenced by System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders(), and System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer().