Terraria: System.Net.Http.Http2Connection.Http2Stream.OnHeader
OnHeader() [1/2]
void System.Net.Http.Http2Connection.Http2Stream.OnHeader (HeaderDescriptor descriptor, ReadOnlySpan< byte > value) inline private
Definition at line 864 of file Http2Connection.cs.
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace(descriptor.Name + ": " + Encoding.ASCII.GetString(value), "OnHeader");
            }
            AdjustHeaderBudget(descriptor.Name.Length + value.Length);
            lock (SyncObject)
            {
                if (_responseProtocolState == ResponseProtocolState.Aborted || _responseProtocolState == ResponseProtocolState.ExpectingIgnoredHeaders)
                {
                    return;
                }
                if (_responseProtocolState != ResponseProtocolState.ExpectingHeaders && _responseProtocolState != ResponseProtocolState.ExpectingTrailingHeaders)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        Trace("Received header before status.", "OnHeader");
                    }
                    throw new HttpRequestException(System.SR.net_http_invalid_response);
                }
                Encoding valueEncoding = _connection._pool.Settings._responseHeaderEncodingSelector?.Invoke(descriptor.Name, _request);
                if (_responseProtocolState == ResponseProtocolState.ExpectingTrailingHeaders)
                {
                    string headerValue = descriptor.GetHeaderValue(value, valueEncoding);
                    _trailers.TryAddWithoutValidation(((descriptor.HeaderType & HttpHeaderType.Request) == HttpHeaderType.Request) ? descriptor.AsCustomHeader() : descriptor, headerValue);
                }
                else if ((descriptor.HeaderType & HttpHeaderType.Content) == HttpHeaderType.Content)
                {
                    string headerValue2 = descriptor.GetHeaderValue(value, valueEncoding);
                    _response.Content.Headers.TryAddWithoutValidation(descriptor, headerValue2);
                }
                else
                {
                    string responseHeaderValueWithCaching = _connection.GetResponseHeaderValueWithCaching(descriptor, value, valueEncoding);
                    _response.Headers.TryAddWithoutValidation(((descriptor.HeaderType & HttpHeaderType.Request) == HttpHeaderType.Request) ? descriptor.AsCustomHeader() : descriptor, responseHeaderValueWithCaching);
                }
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._connection, System.Net.Http.Http2Connection._pool, System.Net.Http.Http2Connection.Http2Stream._request, System.Net.Http.Http2Connection.Http2Stream._response, System.Net.Http.HttpConnectionSettings._responseHeaderEncodingSelector, System.Net.Http.Http2Connection.Http2Stream._responseProtocolState, System.Net.Http.Http2Connection.Http2Stream._trailers, System.Net.Http.Http2Connection.Http2Stream.AdjustHeaderBudget(), System.Text.Encoding.ASCII, System.Net.Http.Headers.HeaderDescriptor.AsCustomHeader(), System.Net.Http.HttpResponseMessage.Content, System.Net.Http.Headers.HeaderDescriptor.GetHeaderValue(), System.Net.Http.HttpConnectionBase.GetResponseHeaderValueWithCaching(), System.Net.Http.HttpContent.Headers, System.Net.Http.HttpResponseMessage.Headers, System.Net.Http.Headers.HeaderDescriptor.HeaderType, System.Net.NetEventSource.Log, System.Net.Http.Headers.HeaderDescriptor.Name, System.SR.net_http_invalid_response, System.Net.Http.HttpConnectionPool.Settings, System.Net.Http.Http2Connection.Http2Stream.SyncObject, System.Net.Http.Http2Connection.Http2Stream.Trace(), System.Net.Http.Headers.HttpHeaders.TryAddWithoutValidation(), and System.value.
Referenced by System.Net.Http.Http2Connection.Http2Stream.OnHeader(), System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader(), and System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader().