Terraria: System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer
TryReadFromBuffer()
bool int bytesRead System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer (Span< byte > buffer, bool partOfSyncRead = false) inline private
Definition at line 1170 of file Http2Connection.cs.
        {
            lock (SyncObject)
            {
                CheckResponseBodyState();
                if (!_responseBuffer.IsEmpty)
                {
                    System.Net.MultiMemory activeMemory = _responseBuffer.ActiveMemory;
                    int num = Math.Min(buffer.Length, activeMemory.Length);
                    activeMemory.Slice(0, num).CopyTo(buffer);
                    _responseBuffer.Discard(num);
                    return (wait: false, bytesRead: num);
                }
                if (_responseProtocolState == ResponseProtocolState.Complete)
                {
                    return (wait: false, bytesRead: 0);
                }
                _hasWaiter = true;
                _waitSource.Reset();
                _waitSource.RunContinuationsAsynchronously = !partOfSyncRead;
                return (wait: true, bytesRead: 0);
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._hasWaiter, System.Net.Http.Http2Connection.Http2Stream._responseBuffer, System.Net.Http.Http2Connection.Http2Stream._responseProtocolState, System.Net.Http.Http2Connection.Http2Stream._waitSource, System.buffer, System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Math.Min(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.Reset(), System.Net.Http.Http2Connection.Http2Stream.SyncObject, and System.Net.Http.Http2Connection.Http2Stream.wait.
Referenced by System.Net.Http.Http2Connection.Http2Stream.CopyTo(), System.Net.Http.Http2Connection.Http2Stream.CopyToAsync(), System.Net.Http.Http2Connection.Http2Stream.ReadData(), and System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync().