Terraria: System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader
OnStaticIndexedHeader() [2/2]
void IHttpHeadersHandler. System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader (int index, ReadOnlySpan< byte > value) inline private
Implements System.Net.Http.IHttpHeadersHandler.
Definition at line 777 of file Http2Connection.cs.
        {
            if (index <= 7)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Invalid request pseudo-header ID {index}.", "OnStaticIndexedHeader");
                }
                throw new HttpRequestException(System.SR.net_http_invalid_response);
            }
            if (index <= 14)
            {
                int statusCode = HttpConnectionBase.ParseStatusCode(value);
                OnStatus(statusCode);
            }
            else
            {
                HeaderDescriptor item = s_hpackStaticHeaderTable[index - 15].descriptor;
                OnHeader(item, value);
            }
        }
References System.index, System.item, System.Net.NetEventSource.Log, System.SR.net_http_invalid_response, System.Net.Http.Http2Connection.Http2Stream.OnHeader(), System.Net.Http.Http2Connection.Http2Stream.OnStatus(), System.Net.Http.HttpConnectionBase.ParseStatusCode(), System.Net.Http.Http2Connection.Http2Stream.Trace(), and System.value.