Terraria: System.Net.Http.Http2Connection.Http2Stream.AdjustHeaderBudget
AdjustHeaderBudget()
void System.Net.Http.Http2Connection.Http2Stream.AdjustHeaderBudget (int amount) inline private
Definition at line 799 of file Http2Connection.cs.
        {
            _headerBudgetRemaining -= amount;
            if (_headerBudgetRemaining < 0)
            {
                throw new HttpRequestException(System.SR.Format(System.SR.net_http_response_headers_exceeded_length, (long)_connection._pool.Settings._maxResponseHeadersLength * 1024L));
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._connection, System.Net.Http.Http2Connection.Http2Stream._headerBudgetRemaining, System.Net.Http.HttpConnectionSettings._maxResponseHeadersLength, System.Net.Http.Http2Connection._pool, System.SR.Format(), System.L, System.SR.net_http_response_headers_exceeded_length, and System.Net.Http.HttpConnectionPool.Settings.
Referenced by System.Net.Http.Http2Connection.Http2Stream.OnHeader(), and System.Net.Http.Http2Connection.Http2Stream.OnStatus().