Terraria: System.Net.Http.Http2Connection.Http2Stream.Cancel
Cancel()
void System.Net.Http.Http2Connection.Http2Stream.Cancel () inline private
Definition at line 686 of file Http2Connection.cs.
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace("", "Cancel");
            }
            CancellationTokenSource cancellationTokenSource = null;
            bool flag = false;
            bool flag2 = false;
            lock (SyncObject)
            {
                if (_requestCompletionState == StreamCompletionState.InProgress)
                {
                    cancellationTokenSource = _requestBodyCancellationSource;
                }
                (flag, flag2) = CancelResponseBody();
            }
            cancellationTokenSource?.Cancel();
            lock (SyncObject)
            {
                if (flag2)
                {
                    SendReset();
                    Complete();
                }
            }
            if (flag)
            {
                _waitSource.SetResult(result: true);
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._requestBodyCancellationSource, System.Net.Http.Http2Connection.Http2Stream._requestCompletionState, System.Net.Http.Http2Connection.Http2Stream._waitSource, System.Net.Http.Http2Connection.Http2Stream.CancelResponseBody(), System.Net.Http.Http2Connection.Http2Stream.Complete(), System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.Http2Stream.SendReset(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetResult(), System.Net.Http.Http2Connection.Http2Stream.SyncObject, and System.Net.Http.Http2Connection.Http2Stream.Trace().
Referenced by System.Net.Http.Http2Connection.Http2Stream.CloseResponseBody(), System.Net.Http.Http2Connection.Http2Stream.OnReset(), and System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync().