Terraria: System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders
TryEnsureHeaders()
bool bool isEmptyResponse System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders () inline private
Definition at line 1107 of file Http2Connection.cs.
        {
            lock (SyncObject)
            {
                CheckResponseBodyState();
                if (_responseProtocolState == ResponseProtocolState.ExpectingHeaders || _responseProtocolState == ResponseProtocolState.ExpectingIgnoredHeaders || _responseProtocolState == ResponseProtocolState.ExpectingStatus)
                {
                    _hasWaiter = true;
                    _waitSource.Reset();
                    return (wait: true, isEmptyResponse: false);
                }
                if (_responseProtocolState == ResponseProtocolState.ExpectingData || _responseProtocolState == ResponseProtocolState.ExpectingTrailingHeaders)
                {
                    return (wait: false, isEmptyResponse: false);
                }
                return (wait: false, isEmptyResponse: _responseBuffer.IsEmpty);
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._hasWaiter, System.Net.Http.Http2Connection.Http2Stream._responseBuffer, System.Net.Http.Http2Connection.Http2Stream._responseProtocolState, System.Net.Http.Http2Connection.Http2Stream._waitSource, System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.Reset(), System.Net.Http.Http2Connection.Http2Stream.SyncObject, and System.Net.Http.Http2Connection.Http2Stream.wait.
Referenced by System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync().