Terraria: System.Net.Http.Http2Connection.Http2Stream.WaitForDataAsync
WaitForDataAsync()
ValueTask System.Net.Http.Http2Connection.Http2Stream.WaitForDataAsync (CancellationToken cancellationToken) inline private
Definition at line 1433 of file Http2Connection.cs.
        {
            _waitSourceCancellation = cancellationToken.UnsafeRegister(delegate(object s, CancellationToken cancellationToken)
            {
                Http2Stream http2Stream = (Http2Stream)s;
                bool hasWaiter;
                lock (http2Stream.SyncObject)
                {
                    hasWaiter = http2Stream._hasWaiter;
                    http2Stream._hasWaiter = false;
                }
                if (hasWaiter)
                {
                    http2Stream._waitSource.SetException(ExceptionDispatchInfo.SetCurrentStackTrace(CancellationHelper.CreateOperationCanceledException(null, cancellationToken)));
                }
            }, this);
            return new ValueTask(this, _waitSource.Version);
        }
References System.Net.Http.Http2Connection.Http2Stream.Http2Stream(), System.Net.Http.Http2Connection.Http2Stream._waitSource, System.Net.Http.Http2Connection.Http2Stream._waitSourceCancellation, System.cancellationToken, System.Net.Http.CancellationHelper.CreateOperationCanceledException(), System.s, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.Version.
Referenced by System.Net.Http.Http2Connection.Http2Stream.CopyToAsync(), System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(), and System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync().