Terraria: System.Net.Http.Http2Connection.Http2Stream.OnHeader
OnHeader() [2/2]
void System.Net.Http.Http2Connection.Http2Stream.OnHeader (ReadOnlySpan< byte > name, ReadOnlySpan< byte > value) inline
Implements System.Net.Http.IHttpHeadersHandler.
Definition at line 904 of file Http2Connection.cs.
        {
            if (name[0] == 58)
            {
                if (!name.SequenceEqual(StatusHeaderName))
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        Trace("Invalid response pseudo-header '" + Encoding.ASCII.GetString(name) + "'.", "OnHeader");
                    }
                    throw new HttpRequestException(System.SR.net_http_invalid_response);
                }
                int statusCode = HttpConnectionBase.ParseStatusCode(value);
                OnStatus(statusCode);
            }
            else
            {
                if (!HeaderDescriptor.TryGet(name, out var descriptor))
                {
                    throw new HttpRequestException(System.SR.Format(System.SR.net_http_invalid_response_header_name, Encoding.ASCII.GetString(name)));
                }
                OnHeader(descriptor, value);
            }
        }
References System.Text.Encoding.ASCII, System.SR.Format(), System.Net.NetEventSource.Log, System.SR.net_http_invalid_response, System.SR.net_http_invalid_response_header_name, System.Net.Http.Http2Connection.Http2Stream.OnHeader(), System.Net.Http.Http2Connection.Http2Stream.OnStatus(), System.Net.Http.HttpConnectionBase.ParseStatusCode(), System.Net.Http.Http2Connection.Http2Stream.StatusHeaderName, System.Net.Http.Http2Connection.Http2Stream.Trace(), System.Net.Http.Headers.HeaderDescriptor.TryGet(), and System.value.