Terraria: System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader
OnStaticIndexedHeader() [1/2]
void IHttpHeadersHandler. System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader (int index) inline private
Implements System.Net.Http.IHttpHeadersHandler.
Definition at line 755 of file Http2Connection.cs.
        {
            if (index <= 7)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Invalid request pseudo-header ID {index}.", "OnStaticIndexedHeader");
                }
                throw new HttpRequestException(System.SR.net_http_invalid_response);
            }
            if (index <= 14)
            {
                int statusCode = s_hpackStaticStatusCodeTable[index - 8];
                OnStatus(statusCode);
            }
            else
            {
                var (descriptor, array) = s_hpackStaticHeaderTable[index - 15];
                OnHeader(descriptor, array);
            }
        }
References System.array, System.index, System.Net.NetEventSource.Log, System.SR.net_http_invalid_response, System.Net.Http.Http2Connection.Http2Stream.OnHeader(), System.Net.Http.Http2Connection.Http2Stream.OnStatus(), System.Net.Http.Http2Connection.Http2Stream.s_hpackStaticStatusCodeTable, and System.Net.Http.Http2Connection.Http2Stream.Trace().