Terraria: System.Net.Http.Http2Connection.Http2Stream.SendDataAsync
SendDataAsync()
async ValueTask System.Net.Http.Http2Connection.Http2Stream.SendDataAsync (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken) inline private
Definition at line 1312 of file Http2Connection.cs.
        {
            CancellationTokenRegistration linkedRegistration = ((cancellationToken.CanBeCanceled && cancellationToken != _requestBodyCancellationSource.Token) ? RegisterRequestBodyCancellation(cancellationToken) : default(CancellationTokenRegistration));
            try
            {
                while (buffer.Length > 0)
                {
                    int num = -1;
                    bool flush = false;
                    lock (_creditSyncObject)
                    {
                        if (_availableCredit > 0)
{
                            num = Math.Min(buffer.Length, _availableCredit);
                            _availableCredit -= num;
                            if (_availableCredit == 0)
{
                                flush = true;
                            }
                        }
                        else
{
                            if (_creditWaiter == null)
{
                                _creditWaiter = new CreditWaiter(_requestBodyCancellationSource.Token);
                            }
                            else
{
                                _creditWaiter.ResetForAwait(_requestBodyCancellationSource.Token);
                            }
                            _creditWaiter.Amount = buffer.Length;
                        }
                    }
                    if (num == -1)
                    {
                        num = await _creditWaiter.AsValueTask().ConfigureAwait(continueOnCapturedContext: false);
                        lock (_creditSyncObject)
{
                            if (_availableCredit == 0)
{
                                flush = true;
                            }
                        }
                    }
                    ReadOnlyMemory<byte> buffer2;
                    (buffer2, buffer) = SplitBuffer(buffer, num);
                    await _connection.SendStreamDataAsync(StreamId, buffer2, flush, _requestBodyCancellationSource.Token).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            catch (OperationCanceledException ex) when (ex.CancellationToken == _requestBodyCancellationSource.Token)
            {
                lock (SyncObject)
                {
                    Exception resetException = _resetException;
                    if (resetException != null)
                    {
                        if (_canRetry)
{
                            ThrowRetry(System.SR.net_http_request_aborted, resetException);
                        }
                        ThrowRequestAborted(resetException);
                    }
                }
                throw;
            }
            finally
            {
                linkedRegistration.Dispose();
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._availableCredit, System.Net.Http.Http2Connection.Http2Stream._canRetry, System.Net.Http.Http2Connection.Http2Stream._connection, System.Net.Http.Http2Connection.Http2Stream._creditSyncObject, System.Net.Http.Http2Connection.Http2Stream._creditWaiter, System.Net.Http.Http2Connection.Http2Stream._requestBodyCancellationSource, System.Net.Http.Http2Connection.Http2Stream._resetException, System.Net.Http.CreditWaiter.AsValueTask(), System.buffer, System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Math.Min(), System.SR.net_http_request_aborted, System.Net.Http.Http2Connection.Http2Stream.RegisterRequestBodyCancellation(), System.Net.Http.CreditWaiter.ResetForAwait(), System.Net.Http.Http2Connection.SendStreamDataAsync(), System.Net.Http.Http2Connection.SplitBuffer(), System.Net.Http.Http2Connection.Http2Stream.StreamId, System.Net.Http.Http2Connection.Http2Stream.SyncObject, System.Net.Http.Http2Connection.ThrowRequestAborted(), System.Net.Http.Http2Connection.ThrowRetry(), and System.Threading.CancellationTokenSource.Token.
Referenced by System.Net.Http.Http2Connection.Http2Stream.Http2WriteStream.WriteAsync().