Terraria: System.Net.Http.Http2Connection.Http2Stream.WaitFor100ContinueAsync
WaitFor100ContinueAsync()
async ValueTask< bool > System.Net.Http.Http2Connection.Http2Stream.WaitFor100ContinueAsync (CancellationToken cancellationToken) inline
Definition at line 616 of file Http2Connection.cs.
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace("Waiting to send request body content for 100-Continue.", "WaitFor100ContinueAsync");
            }
            TaskCompletionSource<bool> expect100ContinueWaiter = _expect100ContinueWaiter;
            using (cancellationToken.UnsafeRegister(delegate(object s)
            {
                ((TaskCompletionSource<bool>)s).TrySetResult(result: false);
            }, expect100ContinueWaiter))
            {
                ConfiguredAsyncDisposable configuredAsyncDisposable = new Timer(delegate(object s)
                {
                    Http2Stream http2Stream = (Http2Stream)s;
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        http2Stream.Trace("100-Continue timer expired.", "WaitFor100ContinueAsync");
                    }
                    http2Stream._expect100ContinueWaiter?.TrySetResult(result: true);
                }, this, _connection._pool.Settings._expect100ContinueTimeout, Timeout.InfiniteTimeSpan).ConfigureAwait(continueOnCapturedContext: false);
                bool result;
                try
                {
                    bool flag = await expect100ContinueWaiter.Task.ConfigureAwait(continueOnCapturedContext: false);
                    CancellationHelper.ThrowIfCancellationRequested(cancellationToken);
                    result = flag;
                }
                finally
                {
                    IAsyncDisposable asyncDisposable = configuredAsyncDisposable as IAsyncDisposable;
                    if (asyncDisposable != null)
                    {
                        await asyncDisposable.DisposeAsync();
                    }
                }
                return result;
            }
        }
References System.Net.Http.Http2Connection.Http2Stream.Http2Stream(), System.Net.Http.Http2Connection.Http2Stream._connection, System.Net.Http.HttpConnectionSettings._expect100ContinueTimeout, System.Net.Http.Http2Connection.Http2Stream._expect100ContinueWaiter, System.Net.Http.Http2Connection._pool, System.cancellationToken, System.Threading.Timeout.InfiniteTimeSpan, System.Net.NetEventSource.Log, System.s, System.Net.Http.HttpConnectionPool.Settings, System.Net.Http.CancellationHelper.ThrowIfCancellationRequested(), and System.Net.Http.Http2Connection.Http2Stream.Trace().
Referenced by System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync().