Terraria: System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync
SendRequestBodyAsync()
async Task System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync (CancellationToken cancellationToken) inline
Definition at line 510 of file Http2Connection.cs.
        {
            if (_request.Content == null)
            {
                return;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace($"{_request.Content}", "SendRequestBodyAsync");
            }
            CancellationTokenRegistration linkedRegistration = default(CancellationTokenRegistration);
            try
            {
                bool flag = true;
                if (_expect100ContinueWaiter != null)
                {
                    linkedRegistration = RegisterRequestBodyCancellation(cancellationToken);
                    flag = await WaitFor100ContinueAsync(_requestBodyCancellationSource.Token).ConfigureAwait(continueOnCapturedContext: false);
                }
                if (flag)
                {
                    using Http2WriteStream writeStream = new Http2WriteStream(this);
                    if (HttpTelemetry.Log.IsEnabled())
                    {
                        HttpTelemetry.Log.RequestContentStart();
                    }
                    ValueTask valueTask = _request.Content.InternalCopyToAsync(writeStream, null, _requestBodyCancellationSource.Token);
                    if (valueTask.IsCompleted)
                    {
                        valueTask.GetAwaiter().GetResult();
                    }
                    else
                    {
                        if (linkedRegistration.Equals(default(CancellationTokenRegistration)))
{
                            linkedRegistration = RegisterRequestBodyCancellation(cancellationToken);
                        }
                        await valueTask.ConfigureAwait(continueOnCapturedContext: false);
                    }
                    if (HttpTelemetry.Log.IsEnabled())
                    {
                        HttpTelemetry.Log.RequestContentStop(writeStream.BytesWritten);
                    }
                }
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace("Finished sending request body.", "SendRequestBodyAsync");
                }
            }
            catch (Exception value)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Failed to send request body: {value}", "SendRequestBodyAsync");
                }
                bool flag2;
                lock (SyncObject)
                {
                    if (_requestBodyAbandoned)
                    {
                        _requestCompletionState = StreamCompletionState.Completed;
                        Complete();
                        return;
                    }
                    (bool signalWaiter, bool sendReset) tuple = CancelResponseBody();
                    (flag2, _) = tuple;
                    _ = tuple.sendReset;
                    _requestCompletionState = StreamCompletionState.Failed;
                    SendReset();
                    Complete();
                }
                if (flag2)
                {
                    _waitSource.SetResult(result: true);
                }
                throw;
            }
            finally
            {
                linkedRegistration.Dispose();
            }
            bool flag3 = false;
            lock (SyncObject)
            {
                _requestCompletionState = StreamCompletionState.Completed;
                bool flag4 = false;
                if (_responseCompletionState != 0)
                {
                    flag3 = _responseCompletionState == StreamCompletionState.Failed;
                    flag4 = true;
                }
                if (flag3)
                {
                    SendReset();
                }
                else
                {
                    _connection.LogExceptions(_connection.SendEndStreamAsync(StreamId));
                }
                if (flag4)
                {
                    Complete();
                }
            }
        }
References System.Net.Http.Http2Connection.Http2Stream._connection, System.Net.Http.Http2Connection.Http2Stream._expect100ContinueWaiter, System.Net.Http.Http2Connection.Http2Stream._request, System.Net.Http.Http2Connection.Http2Stream._requestBodyAbandoned, System.Net.Http.Http2Connection.Http2Stream._requestBodyCancellationSource, System.Net.Http.Http2Connection.Http2Stream._requestCompletionState, System.Net.Http.Http2Connection.Http2Stream._responseCompletionState, System.Net.Http.Http2Connection.Http2Stream._waitSource, System.cancellationToken, System.Net.Http.Http2Connection.Http2Stream.CancelResponseBody(), System.Net.Http.Http2Connection.Http2Stream.Complete(), System.Net.Http.HttpRequestMessage.Content, System.Net.Http.HttpContent.InternalCopyToAsync(), System.Net.Http.HttpTelemetry.Log, System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionBase.LogExceptions(), System.Net.Http.Http2Connection.Http2Stream.RegisterRequestBodyCancellation(), System.Net.Http.Http2Connection.SendEndStreamAsync(), System.Net.Http.Http2Connection.Http2Stream.SendReset(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetResult(), System.Net.Http.Http2Connection.Http2Stream.signalWaiter, System.Net.Http.Http2Connection.Http2Stream.StreamId, System.Net.Http.Http2Connection.Http2Stream.SyncObject, System.Threading.CancellationTokenSource.Token, System.Net.Http.Http2Connection.Http2Stream.Trace(), System.value, and System.Net.Http.Http2Connection.Http2Stream.WaitFor100ContinueAsync().