Terraria: Terraria.Utilities.CrashDump.Write
Write() [3/3]
static bool Terraria.Utilities.CrashDump.Write (SafeHandle fileHandle, Options options, ExceptionInfo exceptionInfo) inline static private
Definition at line 86 of file CrashDump.cs.
    {
        if (!Platform.IsWindows)
        {
            return false;
        }
        Process currentProcess = Process.GetCurrentProcess();
        IntPtr handle = currentProcess.Handle;
        uint id = (uint)currentProcess.Id;
        MiniDumpExceptionInformation expParam = default(MiniDumpExceptionInformation);
        expParam.ThreadId = GetCurrentThreadId();
        expParam.ClientPointers = false;
        expParam.ExceptionPointers = IntPtr.Zero;
        if (exceptionInfo == ExceptionInfo.Present)
        {
            expParam.ExceptionPointers = Marshal.GetExceptionPointers();
        }
        bool flag = false;
        if (expParam.ExceptionPointers == IntPtr.Zero)
        {
            return MiniDumpWriteDump(handle, id, fileHandle, (uint)options, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero);
        }
        return MiniDumpWriteDump(handle, id, fileHandle, (uint)options, ref expParam, IntPtr.Zero, IntPtr.Zero);
    }
References Terraria.Utilities.CrashDump.MiniDumpExceptionInformation.ExceptionPointers, System.Diagnostics.Process.GetCurrentProcess(), Terraria.Utilities.CrashDump.GetCurrentThreadId(), System.Runtime.InteropServices.Marshal.GetExceptionPointers(), System.Diagnostics.Process.Handle, System.handle, System.Diagnostics.Process.Id, ReLogic.OS.Platform.IsWindows, Terraria.Utilities.CrashDump.MiniDumpWriteDump(), System.options, and System.IntPtr.Zero.