Terraria: Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.Draw
Draw()
override void Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.Draw (SpriteBatch sb) inline
Definition at line 57 of file CaptureInterface.cs.
        {
            if (Selected)
            {
                sb.End();
                sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.CurrentWantedZoomMatrix);
                PlayerInput.SetZoom_Context();
                DrawMarkedArea(sb);
                DrawCursors(sb);
                sb.End();
                sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.UIScaleMatrix);
                PlayerInput.SetZoom_UI();
            }
        }
References Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Terraria.Main.CurrentWantedZoomMatrix, Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawCursors(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawMarkedArea(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Microsoft.Xna.Framework.Graphics.SamplerState.LinearClamp, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.Graphics.Capture.CaptureInterface.CaptureInterfaceMode.Selected, Terraria.GameInput.PlayerInput.SetZoom_Context(), Terraria.GameInput.PlayerInput.SetZoom_UI(), and Terraria.Main.UIScaleMatrix.