Terraria: System.Text.Json.JsonDocument.MetadataDb.MetadataDb
MetadataDb() [1/2]
System.Text.Json.JsonDocument.MetadataDb.MetadataDb (byte[] initialDb, bool isLocked, bool convertToAlloc) inline private
Definition at line 53 of file JsonDocument.cs.
        {
            _data = initialDb;
            _isLocked = isLocked;
            _convertToAlloc = convertToAlloc;
            Length = 0;
        }
References System.Text.Json.JsonDocument.MetadataDb._convertToAlloc, System.Text.Json.JsonDocument.MetadataDb._data, System.Text.Json.JsonDocument.MetadataDb._isLocked, System.Text.Json.Dictionary, and System.Text.Json.JsonDocument.MetadataDb.Length.
Referenced by System.Text.Json.JsonDocument.MetadataDb.CopySegment(), System.Text.Json.JsonDocument.MetadataDb.CreateLocked(), and System.Text.Json.JsonDocument.MetadataDb.CreateRented().