Terraria: System.Text.Json.JsonDocument.MetadataDb.Get
Get()
DbRow System.Text.Json.JsonDocument.MetadataDb.Get (int index) inline package
Definition at line 185 of file JsonDocument.cs.
        {
            return MemoryMarshal.Read<DbRow>(_data.AsSpan(index));
        }
References System.Text.Json.JsonDocument.MetadataDb._data, and System.index.
Referenced by System.Text.Json.JsonDocument.MetadataDb.CopySegment(), System.Text.Json.JsonDocument.GetArrayIndexElement(), System.Text.Json.JsonDocument.GetArrayLength(), System.Text.Json.JsonDocument.GetEndIndex(), System.Text.Json.JsonDocument.GetPropertyRawValue(), System.Text.Json.JsonDocument.GetRawValue(), System.Text.Json.JsonDocument.GetString(), System.Text.Json.JsonDocument.TextEquals(), System.Text.Json.JsonDocument.TryGetNamedPropertyValue(), System.Text.Json.JsonDocument.TryGetNamedPropertyValue(), System.Text.Json.JsonDocument.TryGetNamedPropertyValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.WriteComplexElement(), and System.Text.Json.JsonDocument.WriteElementTo().