Terraria: System.Text.Json.JsonDocument.MetadataDb.CreateLocked
CreateLocked()
static MetadataDb System.Text.Json.JsonDocument.MetadataDb.CreateLocked (int payloadLength) inline static package
Definition at line 80 of file JsonDocument.cs.
        {
            int num = payloadLength + 12;
            byte[] initialDb = new byte[num];
            return new MetadataDb(initialDb, isLocked: true, convertToAlloc: false);
        }
References System.Text.Json.JsonDocument.MetadataDb.MetadataDb(), and System.Text.Json.Dictionary.
Referenced by System.Text.Json.JsonDocument.CreateForLiteral(), and System.Text.Json.JsonDocument.ParseUnrented().