Terraria: System.Reflection.Emit.ScopeTree.AddScopeInfo
AddScopeInfo()
void System.Reflection.Emit.ScopeTree.AddScopeInfo (ScopeAction sa, int iOffset) inline package
Definition at line 48 of file ScopeTree.cs.
    {
        if (sa == ScopeAction.Close && m_iOpenScopeCount <= 0)
        {
            throw new ArgumentException(SR.Argument_UnmatchingSymScope);
        }
        EnsureCapacity();
        m_ScopeActions[m_iCount] = sa;
        m_iOffsets[m_iCount] = iOffset;
        m_localSymInfos[m_iCount] = null;
        checked
        {
            m_iCount++;
        }
        m_iOpenScopeCount += 0 - sa;
    }
References System.SR.Argument_UnmatchingSymScope, System.Reflection.Emit.ScopeTree.EnsureCapacity(), System.Reflection.Emit.ScopeTree.m_iCount, System.Reflection.Emit.ScopeTree.m_iOffsets, System.Reflection.Emit.ScopeTree.m_iOpenScopeCount, System.Reflection.Emit.ScopeTree.m_localSymInfos, and System.Reflection.Emit.ScopeTree.m_ScopeActions.
Referenced by System.Reflection.Emit.ILGenerator.BeginScope(), and System.Reflection.Emit.ILGenerator.EndScope().