Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.ResolveFunction
ResolveFunction()
override IXsltContextFunction System.Xml.Xsl.XsltOld.XsltCompileContext.ResolveFunction (string prefix, string name, XPathResultType[] argTypes) inline
Definition at line 591 of file XsltCompileContext.cs.
    {
        IXsltContextFunction xsltContextFunction = null;
        if (prefix.Length == 0)
        {
            xsltContextFunction = s_FunctionTable[name] as IXsltContextFunction;
        }
        else
        {
            string text = LookupNamespace(prefix);
            if (text == "urn:schemas-microsoft-com:xslt" && name == "node-set")
            {
                xsltContextFunction = s_FuncNodeSet;
            }
            else
            {
                xsltContextFunction = GetExtentionMethod(text, name, argTypes, out var extension);
                if (extension == null)
                {
                    throw XsltException.Create(System.SR.Xslt_ScriptInvalidPrefix, prefix);
                }
            }
        }
        if (xsltContextFunction == null)
        {
            throw XsltException.Create(System.SR.Xslt_UnknownXsltFunction, name);
        }
        if (argTypes.Length < xsltContextFunction.Minargs || xsltContextFunction.Maxargs < argTypes.Length)
        {
            throw XsltException.Create(System.SR.Xslt_WrongNumberArgs, name, argTypes.Length.ToString(CultureInfo.InvariantCulture));
        }
        return xsltContextFunction;
    }
References System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.XsltCompileContext.GetExtentionMethod(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Xsl.XsltOld.XsltCompileContext.LookupNamespace(), System.prefix, System.Xml.Xsl.XsltOld.XsltCompileContext.s_FuncNodeSet, System.Xml.Xsl.XsltOld.XsltCompileContext.s_FunctionTable, System.text, System.SR.Xslt_ScriptInvalidPrefix, System.SR.Xslt_UnknownXsltFunction, and System.SR.Xslt_WrongNumberArgs.