Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.LookupNamespace
LookupNamespace()
override string System.Xml.Xsl.XsltOld.XsltCompileContext.LookupNamespace (string prefix) inline virtual
Reimplemented from System.Xml.XmlNamespaceManager.
Definition at line 462 of file XsltCompileContext.cs.
    {
        return _manager.ResolveXPathNamespace(prefix);
    }
References System.Xml.Xsl.XsltOld.XsltCompileContext._manager, System.prefix, and System.Xml.Xsl.XsltOld.InputScopeManager.ResolveXPathNamespace().
Referenced by System.Xml.Xsl.XsltOld.XsltCompileContext.FunctionAvailable(), System.Xml.Xsl.XsltOld.XsltCompileContext.ResolveFormatName(), System.Xml.Xsl.XsltOld.XsltCompileContext.ResolveFunction(), System.Xml.Xsl.XsltOld.XsltCompileContext.ResolveVariable(), and System.Xml.Xsl.XsltOld.XsltCompileContext.SystemProperty().