Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.BuildKeyTable
BuildKeyTable()
Hashtable System.Xml.Xsl.XsltOld.XsltCompileContext.BuildKeyTable (Key key, XPathNavigator root) inline private
Definition at line 656 of file XsltCompileContext.cs.
    {
        Hashtable hashtable = new Hashtable();
        string queryExpression = _processor.GetQueryExpression(key.MatchKey);
        Query compiledQuery = _processor.GetCompiledQuery(key.MatchKey);
        Query compiledQuery2 = _processor.GetCompiledQuery(key.UseKey);
        XPathNodeIterator xPathNodeIterator = root.SelectDescendants(XPathNodeType.All, matchSelf: false);
        while (xPathNodeIterator.MoveNext())
        {
            XPathNavigator current = xPathNodeIterator.Current;
            EvaluateKey(current, compiledQuery, queryExpression, compiledQuery2, hashtable);
            if (current.MoveToFirstAttribute())
            {
                do
                {
                    EvaluateKey(current, compiledQuery, queryExpression, compiledQuery2, hashtable);
                }
                while (current.MoveToNextAttribute());
                current.MoveToParent();
            }
        }
        return hashtable;
    }
References System.Xml.Xsl.XsltOld.XsltCompileContext._processor, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.XsltCompileContext.EvaluateKey(), System.Xml.Xsl.XsltOld.Processor.GetCompiledQuery(), System.Xml.Xsl.XsltOld.Processor.GetQueryExpression(), System.key, System.Xml.XPath.XPathNavigator.MoveToFirstAttribute(), System.Xml.XPath.XPathNavigator.MoveToNextAttribute(), System.Xml.XPath.XPathNavigator.MoveToParent(), and System.Xml.XPath.XPathNavigator.SelectDescendants().