Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.FunctionAvailable
FunctionAvailable()
bool System.Xml.Xsl.XsltOld.XsltCompileContext.FunctionAvailable (string qname) inline private
Definition at line 779 of file XsltCompileContext.cs.
    {
        PrefixQName.ParseQualifiedName(qname, out var prefix, out var local);
        string text = LookupNamespace(prefix);
        if (text == "urn:schemas-microsoft-com:xslt")
        {
            return local == "node-set";
        }
        if (text.Length == 0)
        {
            switch (local)
            {
            default:
                if (s_FunctionTable[local] != null)
                {
                    return local != "unparsed-entity-uri";
                }
                return false;
            case "last":
            case "position":
            case "name":
            case "namespace-uri":
            case "local-name":
            case "count":
            case "id":
            case "string":
            case "concat":
            case "starts-with":
            case "contains":
            case "substring-before":
            case "substring-after":
            case "substring":
            case "string-length":
            case "normalize-space":
            case "translate":
            case "boolean":
            case "not":
            case "true":
            case "false":
            case "lang":
            case "number":
            case "sum":
            case "floor":
            case "ceiling":
            case "round":
                return true;
            }
        }
        object extension;
        return GetExtentionMethod(text, local, null, out extension) != null;
    }
References System.Xml.Dictionary, System.Xml.Xsl.XsltOld.XsltCompileContext.GetExtentionMethod(), System.Xml.Xsl.XsltOld.XsltCompileContext.LookupNamespace(), System.Xml.Xsl.XsltOld.PrefixQName.ParseQualifiedName(), System.prefix, System.Xml.Xsl.XsltOld.XsltCompileContext.s_FunctionTable, and System.text.