Terraria: System.Reflection.Emit.ScopeTree.AddUsingNamespaceToCurrentScope
AddUsingNamespaceToCurrentScope()
void System.Reflection.Emit.ScopeTree.AddUsingNamespaceToCurrentScope (string strNamespace) inline package
Definition at line 37 of file ScopeTree.cs.
    {
        int currentActiveScopeIndex = GetCurrentActiveScopeIndex();
        ref LocalSymInfo reference = ref m_localSymInfos[currentActiveScopeIndex];
        if (reference == null)
        {
            reference = new LocalSymInfo();
        }
        m_localSymInfos[currentActiveScopeIndex].AddUsingNamespace(strNamespace);
    }
References System.Reflection.Emit.LocalSymInfo.AddUsingNamespace(), System.Reflection.Emit.ScopeTree.GetCurrentActiveScopeIndex(), and System.Reflection.Emit.ScopeTree.m_localSymInfos.
Referenced by System.Reflection.Emit.ILGenerator.UsingNamespace().