Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.GetXPathType
GetXPathType()
static XPathResultType System.Xml.Xsl.XsltOld.XsltCompileContext.GetXPathType (Type type) inline static
Definition at line 869 of file XsltCompileContext.cs.
    {
        switch (Type.GetTypeCode(type))
        {
        case TypeCode.String:
            return XPathResultType.String;
        case TypeCode.Boolean:
            return XPathResultType.Boolean;
        case TypeCode.Object:
            if (typeof(XPathNavigator).IsAssignableFrom(type) || typeof(IXPathNavigable).IsAssignableFrom(type))
            {
                return XPathResultType.String;
            }
            if (typeof(XPathNodeIterator).IsAssignableFrom(type))
            {
                return XPathResultType.NodeSet;
            }
            return XPathResultType.Any;
        case TypeCode.DateTime:
            return XPathResultType.Error;
        default:
            return XPathResultType.Number;
        }
    }
References System.Xml.Dictionary, System.Type.GetTypeCode(), and System.type.
Referenced by System.Xml.Xsl.XsltOld.XsltCompileContext.FuncExtension.FuncExtension(), and System.Xml.Xsl.XsltOld.XsltCompileContext.FindBestMethod().