Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.EvaluateKey
EvaluateKey()
static void System.Xml.Xsl.XsltOld.XsltCompileContext.EvaluateKey (XPathNavigator node, Query matchExpr, string matchStr, Query useExpr, Hashtable keyTable) inline static private
Definition at line 695 of file XsltCompileContext.cs.
    {
        try
        {
            if (matchExpr.MatchNode(node) == null)
            {
                return;
            }
        }
        catch (XPathException)
        {
            throw XsltException.Create(System.SR.Xslt_InvalidPattern, matchStr);
        }
        object obj = useExpr.Evaluate(new XPathSingletonIterator(node, moved: true));
        if (obj is XPathNodeIterator xPathNodeIterator)
        {
            bool checkDuplicates = false;
            while (xPathNodeIterator.MoveNext())
            {
                AddKeyValue(keyTable, xPathNodeIterator.Current.Value, node, checkDuplicates);
                checkDuplicates = true;
            }
        }
        else
        {
            string key = XmlConvert.ToXPathString(obj);
            AddKeyValue(keyTable, key, node, checkDuplicates: false);
        }
    }
References System.Xml.Xsl.XsltOld.XsltCompileContext.AddKeyValue(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.key, System.obj, System.Xml.XmlConvert.ToXPathString(), and System.SR.Xslt_InvalidPattern.
Referenced by System.Xml.Xsl.XsltOld.XsltCompileContext.BuildKeyTable().