Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.GetExtentionMethod
GetExtentionMethod()
IXsltContextFunction System.Xml.Xsl.XsltOld.XsltCompileContext.GetExtentionMethod (string ns, string name, XPathResultType[] argTypes, out object extension) inline private
Definition at line 565 of file XsltCompileContext.cs.
    {
        FuncExtension result = null;
        extension = _processor.GetScriptObject(ns);
        if (extension != null)
        {
            MethodInfo methodInfo = FindBestMethod(extension.GetType().GetMethods(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic), ignoreCase: true, publicOnly: false, name, argTypes);
            if (methodInfo != null)
            {
                result = new FuncExtension(extension, methodInfo);
            }
            return result;
        }
        extension = _processor.GetExtensionObject(ns);
        if (extension != null)
        {
            MethodInfo methodInfo2 = FindBestMethod(extension.GetType().GetMethods(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic), ignoreCase: false, publicOnly: true, name, argTypes);
            if (methodInfo2 != null)
            {
                result = new FuncExtension(extension, methodInfo2);
            }
            return result;
        }
        return null;
    }
References System.Xml.Xsl.XsltOld.XsltCompileContext._processor, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.XsltCompileContext.FindBestMethod(), System.Xml.Xsl.XsltOld.Processor.GetExtensionObject(), and System.Xml.Xsl.XsltOld.Processor.GetScriptObject().
Referenced by System.Xml.Xsl.XsltOld.XsltCompileContext.FunctionAvailable(), and System.Xml.Xsl.XsltOld.XsltCompileContext.ResolveFunction().