Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.ResolveFormatName
ResolveFormatName()
DecimalFormat System.Xml.Xsl.XsltOld.XsltCompileContext.ResolveFormatName (string formatName) inline private
Definition at line 725 of file XsltCompileContext.cs.
    {
        string ns = string.Empty;
        string local = string.Empty;
        if (formatName != null)
        {
            PrefixQName.ParseQualifiedName(formatName, out var prefix, out local);
            ns = LookupNamespace(prefix);
        }
        DecimalFormat decimalFormat = _processor.RootAction.GetDecimalFormat(new XmlQualifiedName(local, ns));
        if (decimalFormat == null)
        {
            if (formatName != null)
            {
                throw XsltException.Create(System.SR.Xslt_NoDecimalFormat, formatName);
            }
            decimalFormat = new DecimalFormat(new NumberFormatInfo(), '#', '0', ';');
        }
        return decimalFormat;
    }
References System.Xml.Xsl.XsltOld.XsltCompileContext._processor, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.RootAction.GetDecimalFormat(), System.Xml.Xsl.XsltOld.XsltCompileContext.LookupNamespace(), System.Xml.Xsl.XsltOld.PrefixQName.ParseQualifiedName(), System.prefix, System.Xml.Xsl.XsltOld.Processor.RootAction, and System.SR.Xslt_NoDecimalFormat.