Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.EvaluateVariable
EvaluateVariable()
object System.Xml.Xsl.XsltOld.XsltCompileContext.EvaluateVariable (VariableAction variable) inline package
Definition at line 479 of file XsltCompileContext.cs.
    {
        object variableValue = _processor.GetVariableValue(variable);
        if (variableValue == null && !variable.IsGlobal)
        {
            VariableAction variableAction = _manager.VariableScope.ResolveGlobalVariable(variable.Name);
            if (variableAction != null)
            {
                variableValue = _processor.GetVariableValue(variableAction);
            }
        }
        if (variableValue == null)
        {
            throw XsltException.Create(System.SR.Xslt_InvalidVariable, variable.Name.ToString());
        }
        return variableValue;
    }
References System.Xml.Xsl.XsltOld.XsltCompileContext._manager, System.Xml.Xsl.XsltOld.XsltCompileContext._processor, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.Processor.GetVariableValue(), System.Xml.Xsl.XsltOld.InputScope.ResolveGlobalVariable(), System.Xml.Xsl.XsltOld.InputScopeManager.VariableScope, and System.SR.Xslt_InvalidVariable.