Terraria: System.Text.ASCIIEncoding.GetCharsWithFallback
GetCharsWithFallback() [3/3]
unsafe override int System.Text.ASCIIEncoding.GetCharsWithFallback (ReadOnlySpan< byte > bytes, int originalBytesLength, Span< char > chars, int originalCharsLength, DecoderNLS decoder) inline sealed protected virtual inherited
Reimplemented from System.Text.Encoding.
Definition at line 386 of file ASCIIEncoding.cs.
    {
        if (((decoder == null) ? base.DecoderFallback : decoder.Fallback) is DecoderReplacementFallback { MaxCharCount: 1 } decoderReplacementFallback)
        {
            char c = decoderReplacementFallback.DefaultString[0];
            int num = Math.Min(bytes.Length, chars.Length);
            int num2 = 0;
            fixed (byte* ptr2 = &MemoryMarshal.GetReference(bytes))
            {
                fixed (char* ptr = &MemoryMarshal.GetReference(chars))
                {
                    while (num2 < num)
                    {
                        ptr[num2++] = c;
                        if (num2 < num)
{
                            num2 += (int)ASCIIUtility.WidenAsciiToUtf16(ptr2 + num2, ptr + num2, (uint)(num - num2));
                        }
                    }
                }
            }
            bytes = bytes.Slice(num);
            chars = chars.Slice(num);
        }
        if (bytes.IsEmpty)
        {
            return originalCharsLength - chars.Length;
        }
        return base.GetCharsWithFallback(bytes, originalBytesLength, chars, originalCharsLength, decoder);
    }
References System.bytes, System.chars, System.Text.DecoderNLS.Fallback, System.Math.Min(), and System.Text.ASCIIUtility.WidenAsciiToUtf16().
Referenced by System.Text.ASCIIEncoding.GetCharsCommon().