Terraria: System.Text.ASCIIEncoding.GetBytes
GetBytes() [7/9]
unsafe override int System.Text.ASCIIEncoding.GetBytes (string chars, int charIndex, int charCount, byte[] bytes, int byteIndex) inline virtual inherited
Reimplemented from System.Text.Encoding.
Definition at line 117 of file ASCIIEncoding.cs.
    {
        if (chars == null || bytes == null)
        {
            ThrowHelper.ThrowArgumentNullException((chars == null) ? ExceptionArgument.chars : ExceptionArgument.bytes, ExceptionResource.ArgumentNull_Array);
        }
        if ((charIndex | charCount) < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException((charIndex < 0) ? ExceptionArgument.charIndex : ExceptionArgument.charCount, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (chars.Length - charIndex < charCount)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.chars, ExceptionResource.ArgumentOutOfRange_IndexCount);
        }
        if ((uint)byteIndex > bytes.Length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.byteIndex, ExceptionResource.ArgumentOutOfRange_Index);
        }
        fixed (char* ptr2 = chars)
        {
            fixed (byte[] array = bytes)
            {
                byte* ptr = (byte*)((bytes != null && array.Length != 0) ? System.Runtime.CompilerServices.Unsafe.AsPointer(ref array[0]) : null);
                return GetBytesCommon(ptr2 + charIndex, charCount, ptr + byteIndex, bytes.Length - byteIndex);
            }
        }
    }
References System.array, System.byteIndex, System.bytes, System.charCount, System.charIndex, System.chars, System.Text.ASCIIEncoding.GetBytesCommon(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().