Terraria: System.Text.ASCIIEncoding.GetBytesCommon
GetBytesCommon()
unsafe int System.Text.ASCIIEncoding.GetBytesCommon (char * pChars, int charCount, byte * pBytes, int byteCount) inline private inherited
Definition at line 198 of file ASCIIEncoding.cs.
    {
        int charsConsumed;
        int bytesFast = GetBytesFast(pChars, charCount, pBytes, byteCount, out charsConsumed);
        if (charsConsumed == charCount)
        {
            return bytesFast;
        }
        return GetBytesWithFallback(pChars, charCount, pBytes, byteCount, charsConsumed, bytesFast);
    }
References System.byteCount, System.charCount, System.Text.ASCIIEncoding.GetBytesFast(), and System.Text.ASCIIEncoding.GetBytesWithFallback().
Referenced by System.Text.ASCIIEncoding.GetBytes(), System.Text.ASCIIEncoding.GetBytes(), System.Text.ASCIIEncoding.GetBytes(), and System.Text.ASCIIEncoding.GetBytes().