Terraria: System.Text.ASCIIEncoding.GetBytes
GetBytes() [1/9]
unsafe override int System.Text.ASCIIEncoding.GetBytes (char * chars, int charCount, byte * bytes, int byteCount) inline virtual inherited
Reimplemented from System.Text.Encoding.
Definition at line 173 of file ASCIIEncoding.cs.
    {
        if (chars == null || bytes == null)
        {
            ThrowHelper.ThrowArgumentNullException((chars == null) ? ExceptionArgument.chars : ExceptionArgument.bytes, ExceptionResource.ArgumentNull_Array);
        }
        if ((charCount | byteCount) < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException((charCount < 0) ? ExceptionArgument.charCount : ExceptionArgument.byteCount, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        return GetBytesCommon(chars, charCount, bytes, byteCount);
    }
References System.byteCount, System.bytes, System.charCount, System.chars, System.Text.ASCIIEncoding.GetBytesCommon(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().