Terraria: System.Text.ASCIIEncoding.GetCharCountCommon
GetCharCountCommon()
unsafe int System.Text.ASCIIEncoding.GetCharCountCommon (byte * pBytes, int byteCount) inline private inherited
Definition at line 289 of file ASCIIEncoding.cs.
    {
        int bytesConsumed;
        int num = GetCharCountFast(pBytes, byteCount, base.DecoderFallback, out bytesConsumed);
        if (bytesConsumed != byteCount)
        {
            num += GetCharCountWithFallback(pBytes, byteCount, bytesConsumed);
            if (num < 0)
            {
                Encoding.ThrowConversionOverflow();
            }
        }
        return num;
    }
References System.byteCount, System.Text.ASCIIEncoding.GetCharCountFast(), System.Text.Encoding.GetCharCountWithFallback(), and System.Text.Encoding.ThrowConversionOverflow().
Referenced by System.Text.ASCIIEncoding.GetCharCount(), System.Text.ASCIIEncoding.GetCharCount(), and System.Text.ASCIIEncoding.GetCharCount().