Terraria: System.Text.ASCIIEncoding.GetByteCount
GetByteCount() [4/7]
unsafe override int System.Text.ASCIIEncoding.GetByteCount (char[] chars, int index, int count) inline inherited
Definition at line 35 of file ASCIIEncoding.cs.
    {
        if (chars == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.chars, ExceptionResource.ArgumentNull_Array);
        }
        if ((index | count) < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException((index < 0) ? ExceptionArgument.index : ExceptionArgument.count, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (chars.Length - index < count)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.chars, ExceptionResource.ArgumentOutOfRange_IndexCountBuffer);
        }
        fixed (char* ptr = chars)
        {
            return GetByteCountCommon(ptr + index, count);
        }
    }
References System.chars, System.count, System.Text.ASCIIEncoding.GetByteCountCommon(), System.index, System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().