Terraria: System.Security.AccessControl.DirectoryObjectSecurity.AddAccessRule
AddAccessRule() [2/2]
void System.Security.AccessControl.DirectoryObjectSecurity.AddAccessRule (ObjectAccessRule rule) inline protected
Definition at line 316 of file DirectoryObjectSecurity.cs.
    {
        if (rule == null)
        {
            throw new ArgumentNullException("rule");
        }
        WriteLock();
        try
        {
            ModifyAccess(AccessControlModification.Add, rule, out var _);
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.Security.AccessControl.DirectoryObjectSecurity.ModifyAccess(), System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().