Terraria: System.Security.AccessControl.DirectoryObjectSecurity.ModifyAccess
ModifyAccess() [2/2]
bool System.Security.AccessControl.DirectoryObjectSecurity.ModifyAccess (AccessControlModification modification, ObjectAccessRule rule, out bool modified) inline private
Definition at line 152 of file DirectoryObjectSecurity.cs.
    {
        bool flag = true;
        if (base.SecurityDescriptor.DiscretionaryAcl == null)
        {
            if (modification == AccessControlModification.Remove || modification == AccessControlModification.RemoveAll || modification == AccessControlModification.RemoveSpecific)
            {
                modified = false;
                return flag;
            }
            base.SecurityDescriptor.AddDiscretionaryAcl(GenericAcl.AclRevisionDS, 1);
        }
        else if ((modification == AccessControlModification.Add || modification == AccessControlModification.Set || modification == AccessControlModification.Reset) && rule.ObjectFlags != 0 && base.SecurityDescriptor.DiscretionaryAcl.Revision < GenericAcl.AclRevisionDS)
        {
            byte[] array = new byte[base.SecurityDescriptor.DiscretionaryAcl.BinaryLength];
            base.SecurityDescriptor.DiscretionaryAcl.GetBinaryForm(array, 0);
            array[0] = GenericAcl.AclRevisionDS;
            base.SecurityDescriptor.DiscretionaryAcl = new DiscretionaryAcl(base.IsContainer, base.IsDS, new RawAcl(array, 0));
        }
        SecurityIdentifier sid = (SecurityIdentifier)rule.IdentityReference.Translate(typeof(SecurityIdentifier));
        if (rule.AccessControlType == AccessControlType.Allow)
        {
            switch (modification)
            {
            case AccessControlModification.Add:
                base.SecurityDescriptor.DiscretionaryAcl.AddAccess(AccessControlType.Allow, sid, rule);
                break;
            case AccessControlModification.Set:
                base.SecurityDescriptor.DiscretionaryAcl.SetAccess(AccessControlType.Allow, sid, rule);
                break;
            case AccessControlModification.Reset:
                base.SecurityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Deny, sid, -1, InheritanceFlags.ContainerInherit, PropagationFlags.None, ObjectAceFlags.None, Guid.Empty, Guid.Empty);
                base.SecurityDescriptor.DiscretionaryAcl.SetAccess(AccessControlType.Allow, sid, rule);
                break;
            case AccessControlModification.Remove:
                flag = base.SecurityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Allow, sid, rule);
                break;
            case AccessControlModification.RemoveAll:
                flag = base.SecurityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Allow, sid, -1, InheritanceFlags.ContainerInherit, PropagationFlags.None, ObjectAceFlags.None, Guid.Empty, Guid.Empty);
                if (!flag)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_RemoveFail);
                }
                break;
            case AccessControlModification.RemoveSpecific:
                base.SecurityDescriptor.DiscretionaryAcl.RemoveAccessSpecific(AccessControlType.Allow, sid, rule);
                break;
            default:
                throw new ArgumentOutOfRangeException("modification", System.SR.ArgumentOutOfRange_Enum);
            }
        }
        else
        {
            if (rule.AccessControlType != AccessControlType.Deny)
            {
                throw new ArgumentException(System.SR.Format(System.SR.TypeUnrecognized_AccessControl, rule.AccessControlType));
            }
            switch (modification)
            {
            case AccessControlModification.Add:
                base.SecurityDescriptor.DiscretionaryAcl.AddAccess(AccessControlType.Deny, sid, rule);
                break;
            case AccessControlModification.Set:
                base.SecurityDescriptor.DiscretionaryAcl.SetAccess(AccessControlType.Deny, sid, rule);
                break;
            case AccessControlModification.Reset:
                base.SecurityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Allow, sid, -1, InheritanceFlags.ContainerInherit, PropagationFlags.None, ObjectAceFlags.None, Guid.Empty, Guid.Empty);
                base.SecurityDescriptor.DiscretionaryAcl.SetAccess(AccessControlType.Deny, sid, rule);
                break;
            case AccessControlModification.Remove:
                flag = base.SecurityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Deny, sid, rule);
                break;
            case AccessControlModification.RemoveAll:
                flag = base.SecurityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Deny, sid, -1, InheritanceFlags.ContainerInherit, PropagationFlags.None, ObjectAceFlags.None, Guid.Empty, Guid.Empty);
                if (!flag)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_RemoveFail);
                }
                break;
            case AccessControlModification.RemoveSpecific:
                base.SecurityDescriptor.DiscretionaryAcl.RemoveAccessSpecific(AccessControlType.Deny, sid, rule);
                break;
            default:
                throw new ArgumentOutOfRangeException("modification", System.SR.ArgumentOutOfRange_Enum);
            }
        }
        modified = flag;
        base.AccessRulesModified |= modified;
        return flag;
    }
References System.Security.AccessControl.AccessRule< T >.AccessControlType, System.Security.AccessControl.GenericAcl.AclRevisionDS, System.SR.ArgumentOutOfRange_Enum, System.array, System.Security.AccessControl.DiscretionaryAcl, System.Guid.Empty, System.SR.Format(), System.Security.AccessControl.AuthorizationRule.IdentityReference, System.SR.InvalidOperation_RemoveFail, System.Security.AccessControl.ObjectAccessRule.ObjectFlags, System.Security.Principal.IdentityReference.Translate(), and System.SR.TypeUnrecognized_AccessControl.
Referenced by System.Security.AccessControl.DirectoryObjectSecurity.AddAccessRule(), System.Security.AccessControl.DirectoryObjectSecurity.ModifyAccess(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAccessRule(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAccessRuleAll(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAccessRuleSpecific(), System.Security.AccessControl.DirectoryObjectSecurity.ResetAccessRule(), and System.Security.AccessControl.DirectoryObjectSecurity.SetAccessRule().