Terraria: System.Security.AccessControl.DirectoryObjectSecurity.ModifyAudit
ModifyAudit() [2/2]
bool System.Security.AccessControl.DirectoryObjectSecurity.ModifyAudit (AccessControlModification modification, ObjectAuditRule rule, out bool modified) inline private
Definition at line 243 of file DirectoryObjectSecurity.cs.
    {
        bool flag = true;
        if (base.SecurityDescriptor.SystemAcl == null)
        {
            if (modification == AccessControlModification.Remove || modification == AccessControlModification.RemoveAll || modification == AccessControlModification.RemoveSpecific)
            {
                modified = false;
                return flag;
            }
            base.SecurityDescriptor.AddSystemAcl(GenericAcl.AclRevisionDS, 1);
        }
        else if ((modification == AccessControlModification.Add || modification == AccessControlModification.Set || modification == AccessControlModification.Reset) && rule.ObjectFlags != 0 && base.SecurityDescriptor.SystemAcl.Revision < GenericAcl.AclRevisionDS)
        {
            byte[] array = new byte[base.SecurityDescriptor.SystemAcl.BinaryLength];
            base.SecurityDescriptor.SystemAcl.GetBinaryForm(array, 0);
            array[0] = GenericAcl.AclRevisionDS;
            base.SecurityDescriptor.SystemAcl = new SystemAcl(base.IsContainer, base.IsDS, new RawAcl(array, 0));
        }
        SecurityIdentifier sid = (SecurityIdentifier)rule.IdentityReference.Translate(typeof(SecurityIdentifier));
        switch (modification)
        {
        case AccessControlModification.Add:
            base.SecurityDescriptor.SystemAcl.AddAudit(sid, rule);
            break;
        case AccessControlModification.Set:
            base.SecurityDescriptor.SystemAcl.SetAudit(sid, rule);
            break;
        case AccessControlModification.Reset:
            base.SecurityDescriptor.SystemAcl.RemoveAudit(AuditFlags.Success | AuditFlags.Failure, sid, -1, InheritanceFlags.ContainerInherit, PropagationFlags.None, ObjectAceFlags.None, Guid.Empty, Guid.Empty);
            base.SecurityDescriptor.SystemAcl.SetAudit(sid, rule);
            break;
        case AccessControlModification.Remove:
            flag = base.SecurityDescriptor.SystemAcl.RemoveAudit(sid, rule);
            break;
        case AccessControlModification.RemoveAll:
            flag = base.SecurityDescriptor.SystemAcl.RemoveAudit(AuditFlags.Success | AuditFlags.Failure, sid, -1, InheritanceFlags.ContainerInherit, PropagationFlags.None, ObjectAceFlags.None, Guid.Empty, Guid.Empty);
            if (!flag)
            {
                throw new InvalidOperationException(System.SR.InvalidOperation_RemoveFail);
            }
            break;
        case AccessControlModification.RemoveSpecific:
            base.SecurityDescriptor.SystemAcl.RemoveAuditSpecific(sid, rule);
            break;
        default:
            throw new ArgumentOutOfRangeException("modification", System.SR.ArgumentOutOfRange_Enum);
        }
        modified = flag;
        base.AuditRulesModified |= modified;
        return flag;
    }
References System.Security.AccessControl.GenericAcl.AclRevisionDS, System.SR.ArgumentOutOfRange_Enum, System.array, System.Guid.Empty, System.Security.AccessControl.AuthorizationRule.IdentityReference, System.SR.InvalidOperation_RemoveFail, System.Security.AccessControl.ObjectAuditRule.ObjectFlags, System.Security.AccessControl.SystemAcl, and System.Security.Principal.IdentityReference.Translate().
Referenced by System.Security.AccessControl.DirectoryObjectSecurity.AddAuditRule(), System.Security.AccessControl.DirectoryObjectSecurity.ModifyAudit(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAuditRule(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAuditRuleAll(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAuditRuleSpecific(), and System.Security.AccessControl.DirectoryObjectSecurity.SetAuditRule().