Terraria: Terraria.Utilities.NPCUtils.TargetClosestBetsy
TargetClosestBetsy()
static void Terraria.Utilities.NPCUtils.TargetClosestBetsy (NPC searcher, bool faceTarget = true, Vector2? checkPosition = null) inline static
Definition at line 308 of file NPCUtils.cs.
    {
        TargetSearchResults searchResults = SearchForTarget(searcher, TargetSearchFlag.All, null, SearchFilters.OnlyCrystal);
        if (searchResults.FoundTarget)
        {
            TargetType value = searchResults.NearestTargetType;
            if (searchResults.FoundTank && !searchResults.NearestTankOwner.dead)
            {
                value = TargetType.Player;
            }
            searcher.target = searchResults.NearestTargetIndex;
            searcher.targetRect = searchResults.NearestTargetHitbox;
            if (searcher.ShouldFaceTarget(ref searchResults, value) && faceTarget)
            {
                searcher.FaceTarget();
            }
        }
    }
References Terraria.Player.dead, Terraria.NPC.FaceTarget(), Terraria.Utilities.NPCUtils.TargetSearchResults.FoundTank, Terraria.Utilities.NPCUtils.TargetSearchResults.FoundTarget, Terraria.Utilities.NPCUtils.TargetSearchResults.NearestTankOwner, Terraria.Utilities.NPCUtils.TargetSearchResults.NearestTargetHitbox, Terraria.Utilities.NPCUtils.TargetSearchResults.NearestTargetIndex, Terraria.Utilities.NPCUtils.TargetSearchResults.NearestTargetType, Terraria.Utilities.NPCUtils.SearchFilters.OnlyCrystal(), Terraria.Utilities.NPCUtils.SearchForTarget(), Terraria.NPC.ShouldFaceTarget(), and System.value.
Referenced by Terraria.NPC.AI_110_Betsy().