Terraria: System.Security.AccessControl.DirectoryObjectSecurity.RemoveAuditRuleSpecific
RemoveAuditRuleSpecific() [2/2]
void System.Security.AccessControl.DirectoryObjectSecurity.RemoveAuditRuleSpecific (ObjectAuditRule rule) inline protected
Definition at line 499 of file DirectoryObjectSecurity.cs.
    {
        if (rule == null)
        {
            throw new ArgumentNullException("rule");
        }
        WriteLock();
        try
        {
            ModifyAudit(AccessControlModification.RemoveSpecific, rule, out var _);
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.Security.AccessControl.DirectoryObjectSecurity.ModifyAudit(), System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().