Terraria: Terraria.Utilities.NPCUtils.TargetClosestDownwindFromNPC
TargetClosestDownwindFromNPC()
static void Terraria.Utilities.NPCUtils.TargetClosestDownwindFromNPC (NPC searcher, float distanceMaxX, bool faceTarget = true, Vector2? checkPosition = null) inline static
    {
        TargetSearchResults searchResults = SearchForTarget(searcher, TargetSearchFlag.Players, SearchFilters.DownwindFromNPC(searcher, distanceMaxX));
        if (searchResults.FoundTarget)
        {
            searcher.target = searchResults.NearestTargetIndex;
            searcher.targetRect = searchResults.NearestTargetHitbox;
            if (searcher.ShouldFaceTarget(ref searchResults) && faceTarget)
            {
                searcher.FaceTarget();
            }
        }
    }
References Terraria.Utilities.NPCUtils.SearchFilters.DownwindFromNPC(), Terraria.NPC.FaceTarget(), Terraria.Utilities.NPCUtils.TargetSearchResults.FoundTarget, Terraria.Utilities.NPCUtils.TargetSearchResults.NearestTargetHitbox, Terraria.Utilities.NPCUtils.TargetSearchResults.NearestTargetIndex, Terraria.Utilities.NPCUtils.SearchForTarget(), and Terraria.NPC.ShouldFaceTarget().
Referenced by Terraria.NPC.AI_119_Dandelion().