Terraria: EmpressShader.ProcessHighDetail
ProcessHighDetail()
void EmpressShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
     {
         float num = time * 2f;
         for (int i = 0; i < fragment.Count; i++)
         {
             Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
             Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
             float staticNoise = NoiseHelper.GetStaticNoise(gridPositionOfIndex.X);
             float num2 = MathHelper.Max(0f, (float)Math.Cos((staticNoise + num) * ((float)Math.PI * 2f) * 0.2f));
             Vector4 value = Color.Lerp(Color.Black, Color.Indigo, 0.5f).ToVector4();
             float num3 = Math.Max(0f, (float)Math.Sin(Main.GlobalTimeWrappedHourly * 2f + canvasPositionOfIndex.X * 1f));
             num3 = 0f;
             value = Vector4.Lerp(value, new Vector4(1f, 0.1f, 0.1f, 1f), num3);
             float num4 = (num2 + canvasPositionOfIndex.X + canvasPositionOfIndex.Y) % 1f;
             if (num4 > 0f)
             {
                 int num5 = (gridPositionOfIndex.X + gridPositionOfIndex.Y) % _colors.Length;
                 if (num5 < 0)
                 {
                     num5 += _colors.Length;
                 }
                 Vector4 value2 = Main.hslToRgb(((canvasPositionOfIndex.X + canvasPositionOfIndex.Y) * 0.15f + time * 0.1f) % 1f, 1f, 0.5f).ToVector4();
                 value = Vector4.Lerp(value, value2, num4);
             }
             fragment.SetColor(i, value);
         }
     }
References _colors, Color, Fragment.Count, Fragment.GetCanvasPositionOfIndex(), Fragment.GetGridPositionOfIndex(), NoiseHelper.GetStaticNoise(), Main.GlobalTimeWrappedHourly, Main.hslToRgb(), and Fragment.SetColor().