Terraria: System.Diagnostics.TraceListener.TraceEvent
TraceEvent() [1/3]
virtual void System.Diagnostics.TraceListener.TraceEvent (TraceEventCache? eventCache, string source, TraceEventType eventType, int id) inline virtual inherited
Definition at line 289 of file TraceListener.cs.
    {
        TraceEvent(eventCache, source, eventType, id, string.Empty);
    }
References System.source, and System.Diagnostics.TraceListener.TraceEvent().
Referenced by System.Diagnostics.TraceListener.TraceEvent(), System.Diagnostics.TraceInternal.TraceEvent(), and System.Diagnostics.TraceListener.TraceTransfer().