Terraria: System.Diagnostics.TraceListener.WriteFooter
WriteFooter()
void System.Diagnostics.TraceListener.WriteFooter (TraceEventCache eventCache) inline private
Definition at line 336 of file TraceListener.cs.
    {
        if (eventCache == null)
        {
            return;
        }
        _indentLevel++;
        if (IsEnabled(TraceOptions.ProcessId))
        {
            WriteLine("ProcessId=" + eventCache.ProcessId);
        }
        if (IsEnabled(TraceOptions.LogicalOperationStack))
        {
            Write("LogicalOperationStack=");
            Stack logicalOperationStack = eventCache.LogicalOperationStack;
            bool flag = true;
            foreach (object item in logicalOperationStack)
            {
                if (!flag)
                {
                    Write(", ");
                }
                else
                {
                    flag = false;
                }
                Write(item.ToString());
            }
            WriteLine(string.Empty);
        }
        Span<char> span = stackalloc char[128];
        if (IsEnabled(TraceOptions.ThreadId))
        {
            WriteLine("ThreadId=" + eventCache.ThreadId);
        }
        if (IsEnabled(TraceOptions.DateTime))
        {
            IFormatProvider formatProvider = null;
            IFormatProvider provider = formatProvider;
            Span<char> span2 = span;
            Span<char> initialBuffer = span2;
            DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(9, 1, formatProvider, span2);
            handler.AppendLiteral("DateTime=");
            handler.AppendFormatted(eventCache.DateTime, "o");
            WriteLine(string.Create(provider, initialBuffer, ref handler));
        }
        if (IsEnabled(TraceOptions.Timestamp))
        {
            IFormatProvider formatProvider = null;
            IFormatProvider provider2 = formatProvider;
            Span<char> span2 = span;
            Span<char> initialBuffer2 = span2;
            DefaultInterpolatedStringHandler handler2 = new DefaultInterpolatedStringHandler(10, 1, formatProvider, span2);
            handler2.AppendLiteral("Timestamp=");
            handler2.AppendFormatted(eventCache.Timestamp);
            WriteLine(string.Create(provider2, initialBuffer2, ref handler2));
        }
        if (IsEnabled(TraceOptions.Callstack))
        {
            WriteLine("Callstack=" + eventCache.Callstack);
        }
        _indentLevel--;
    }
References System.Diagnostics.TraceListener._indentLevel, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Diagnostics.TraceEventCache.Callstack, System.Diagnostics.TraceEventCache.DateTime, System.Diagnostics.TraceListener.IsEnabled(), System.item, System.Diagnostics.TraceEventCache.LogicalOperationStack, System.Diagnostics.TraceEventCache.ProcessId, System.Diagnostics.TraceEventCache.ThreadId, System.Diagnostics.TraceEventCache.Timestamp, System.Diagnostics.TraceListener.Write(), and System.Diagnostics.TraceListener.WriteLine().
Referenced by System.Diagnostics.TraceListener.TraceData(), System.Diagnostics.TraceListener.TraceData(), System.Diagnostics.TraceListener.TraceEvent(), and System.Diagnostics.TraceListener.TraceEvent().