Terraria: System.Diagnostics.TraceListener.Write
Write() [3/4]
void System.Diagnostics.TraceListener.Write (string? message) abstract
Referenced by System.Diagnostics.TraceInternal.Write(), System.Diagnostics.TraceInternal.Write(), System.Diagnostics.TraceListener.Write(), System.Diagnostics.TraceListener.Write(), System.Diagnostics.TraceInternal.Write(), System.Diagnostics.TraceInternal.Write(), System.Diagnostics.TraceListener.Write(), System.Diagnostics.TraceListener.WriteFooter(), System.Diagnostics.TraceListener.WriteHeader(), and System.Diagnostics.TraceListener.WriteIndent().