Terraria: System.Diagnostics.TraceListener.WriteIndent
WriteIndent()
virtual void System.Diagnostics.TraceListener.WriteIndent () inline protected virtual inherited
Definition at line 214 of file TraceListener.cs.
    {
        NeedIndent = false;
        for (int i = 0; i < _indentLevel; i++)
        {
            if (_indentSize == 4)
            {
                Write("    ");
                continue;
            }
            for (int j = 0; j < _indentSize; j++)
            {
                Write(" ");
            }
        }
    }
References System.Diagnostics.TraceListener._indentLevel, System.Diagnostics.TraceListener._indentSize, System.Diagnostics.TraceListener.NeedIndent, and System.Diagnostics.TraceListener.Write().
Referenced by System.Diagnostics.DefaultTraceListener.Write(), System.Diagnostics.TextWriterTraceListener.Write(), System.Diagnostics.DefaultTraceListener.WriteLine(), and System.Diagnostics.TextWriterTraceListener.WriteLine().