Terraria: System.Diagnostics.TraceListener.WriteHeader
WriteHeader()
void System.Diagnostics.TraceListener.WriteHeader (string source, TraceEventType eventType, int id) inline private
Definition at line 321 of file TraceListener.cs.
    {
        IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
        IFormatProvider provider = invariantCulture;
        Span<char> initialBuffer = stackalloc char[256];
        DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(6, 3, invariantCulture, initialBuffer);
        handler.AppendFormatted(source);
        handler.AppendLiteral(" ");
        handler.AppendFormatted(eventType);
        handler.AppendLiteral(": ");
        handler.AppendFormatted(id);
        handler.AppendLiteral(" : ");
        Write(string.Create(provider, initialBuffer, ref handler));
    }
References System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Globalization.CultureInfo.InvariantCulture, System.source, and System.Diagnostics.TraceListener.Write().
Referenced by System.Diagnostics.TraceListener.TraceData(), System.Diagnostics.TraceListener.TraceData(), System.Diagnostics.TraceListener.TraceEvent(), and System.Diagnostics.TraceListener.TraceEvent().