Terraria: System.Diagnostics.TraceListener.TraceEvent
TraceEvent() [2/3]
virtual void System.Diagnostics.TraceListener.TraceEvent (TraceEventCache? eventCache, string source, TraceEventType eventType, int id, string? format, params object??[] args) inline virtual
Reimplemented in System.Diagnostics.DelimitedListTraceListener, and System.Diagnostics.XmlWriterTraceListener.
Definition at line 304 of file TraceListener.cs.
    {
        if (Filter == null || Filter.ShouldTrace(eventCache, source, eventType, id, format, args))
        {
            WriteHeader(source, eventType, id);
            if (args != null)
            {
                WriteLine(string.Format(CultureInfo.InvariantCulture, format, args));
            }
            else
            {
                WriteLine(format);
            }
            WriteFooter(eventCache);
        }
    }
References System.Diagnostics.TraceListener.Filter, System.format, System.Format, System.Globalization.CultureInfo.InvariantCulture, System.Diagnostics.TraceFilter.ShouldTrace(), System.source, System.Diagnostics.TraceListener.WriteFooter(), System.Diagnostics.TraceListener.WriteHeader(), and System.Diagnostics.TraceListener.WriteLine().