Terraria: System.Diagnostics.TraceListener.TraceTransfer
TraceTransfer()
virtual void System.Diagnostics.TraceListener.TraceTransfer (TraceEventCache? eventCache, string source, int id, string? message, Guid relatedActivityId) inline virtual
Reimplemented in System.Diagnostics.XmlWriterTraceListener.
Definition at line 152 of file TraceListener.cs.
    {
        IFormatProvider formatProvider = null;
        IFormatProvider provider = formatProvider;
        Span<char> initialBuffer = stackalloc char[256];
        DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(20, 2, formatProvider, initialBuffer);
        handler.AppendFormatted(message);
        handler.AppendLiteral(", relatedActivityId=");
        handler.AppendFormatted(relatedActivityId);
        TraceEvent(eventCache, source, TraceEventType.Transfer, id, string.Create(provider, initialBuffer, ref handler));
    }
References System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.source, and System.Diagnostics.TraceListener.TraceEvent().