Terraria: ParticleOrchestrator.Spawn_ShimmerTownNPC
Spawn_ShimmerTownNPC()
static void ParticleOrchestrator.Spawn_ShimmerTownNPC (ParticleOrchestraSettings settings) inline static private
     {
         Rectangle rectangle = Utils.CenteredRectangle(settings.PositionInWorld, new Vector2(30f, 60f));
         for (float num = 0f; num < 20f; num += 1f)
         {
             PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             int num2 = Main.rand.Next(20, 40);
             prettySparkleParticle.ColorTint = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f, 0);
             prettySparkleParticle.LocalPosition = Main.rand.NextVector2FromRectangle(rectangle);
             prettySparkleParticle.Rotation = (float)Math.PI / 2f;
             prettySparkleParticle.Scale = new Vector2(1f + Main.rand.NextFloat() * 2f, 0.7f + Main.rand.NextFloat() * 0.7f);
             prettySparkleParticle.Velocity = new Vector2(0f, -1f);
             prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle.TimeToLive = num2;
             prettySparkleParticle.FadeOutEnd = num2;
             prettySparkleParticle.FadeInEnd = num2 / 2;
             prettySparkleParticle.FadeOutStart = num2 / 2;
             prettySparkleParticle.AdditiveAmount = 0.35f;
             prettySparkleParticle.DrawVerticalAxis = false;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
             PrettySparkleParticle prettySparkleParticle2 = _poolPrettySparkle.RequestParticle();
             prettySparkleParticle2.ColorTint = new Color(255, 255, 255, 0);
             prettySparkleParticle2.LocalPosition = Main.rand.NextVector2FromRectangle(rectangle);
             prettySparkleParticle2.Rotation = (float)Math.PI / 2f;
             prettySparkleParticle2.Scale = prettySparkleParticle.Scale * 0.5f;
             prettySparkleParticle2.Velocity = new Vector2(0f, -1f);
             prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle2.TimeToLive = num2;
             prettySparkleParticle2.FadeOutEnd = num2;
             prettySparkleParticle2.FadeInEnd = num2 / 2;
             prettySparkleParticle2.FadeOutStart = num2 / 2;
             prettySparkleParticle2.AdditiveAmount = 1f;
             prettySparkleParticle2.DrawVerticalAxis = false;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
         }
         for (int i = 0; i < 20; i++)
         {
             int num3 = Dust.NewDust(rectangle.TopLeft(), rectangle.Width, rectangle.Height, 308);
             Main.dust[num3].velocity.Y -= 8f;
             Main.dust[num3].velocity.X *= 0.5f;
             Main.dust[num3].scale = 0.8f;
             Main.dust[num3].noGravity = true;
             switch (Main.rand.Next(6))
             {
             case 0:
                 Main.dust[num3].color = new Color(255, 255, 210);
                 break;
             case 1:
                 Main.dust[num3].color = new Color(190, 245, 255);
                 break;
             case 2:
                 Main.dust[num3].color = new Color(255, 150, 255);
                 break;
             default:
                 Main.dust[num3].color = new Color(190, 175, 255);
                 break;
             }
         }
         SoundEngine.PlaySound(SoundID.Item29, settings.PositionInWorld);
     }
References _poolPrettySparkle, ParticleRenderer.Add(), PrettySparkleParticle.AdditiveAmount, Utils.CenteredRectangle(), Color, Dust.color, PrettySparkleParticle.ColorTint, PrettySparkleParticle.DrawVerticalAxis, Main.dust, E, PrettySparkleParticle.FadeInEnd, PrettySparkleParticle.FadeInNormalizedTime, PrettySparkleParticle.FadeOutEnd, PrettySparkleParticle.FadeOutNormalizedTime, PrettySparkleParticle.FadeOutStart, Main.hslToRgb(), SoundID.Item29, ABasicParticle.LocalPosition, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Main.ParticleSystem_World_OverPlayers, SoundEngine.PlaySound(), ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Rotation, ABasicParticle.Scale, Dust.scale, PrettySparkleParticle.TimeToLive, ABasicParticle.Velocity, and Dust.velocity.
Referenced by SpawnParticlesDirect().