Terraria: ParticleOrchestrator.Spawn_PaladinsHammer
Spawn_PaladinsHammer()
static void ParticleOrchestrator.Spawn_PaladinsHammer (ParticleOrchestraSettings settings) inline static private
     {
         float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
         float num2 = 1f;
         for (float num3 = 0f; num3 < 1f; num3 += 1f / num2)
         {
             float num4 = 0.6f + Main.rand.NextFloat() * 0.35f;
             Vector2 vector = settings.MovementVector * num4;
             Vector2 vector2 = new Vector2(Main.rand.NextFloat() * 0.4f + 0.2f);
             float f = num + Main.rand.NextFloat() * ((float)Math.PI * 2f);
             float rotation = (float)Math.PI / 2f;
             _ = 0.1f * vector2;
             Vector2 vector3 = Main.rand.NextVector2Circular(12f, 12f) * vector2;
             PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             prettySparkleParticle.AccelerationPerFrame = -vector * 1f / 30f;
             prettySparkleParticle.Velocity = vector + f.ToRotationVector2() * 2f * num4;
             prettySparkleParticle.ColorTint = new Color(1f, 0.8f, 0.4f, 0f);
             prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector3;
             prettySparkleParticle.Rotation = rotation;
             prettySparkleParticle.Scale = vector2;
             prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle.TimeToLive = 40f;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
             prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             prettySparkleParticle.AccelerationPerFrame = -vector * 1f / 30f;
             prettySparkleParticle.Velocity = vector * 0.8f + f.ToRotationVector2() * 2f;
             prettySparkleParticle.ColorTint = new Color(255, 255, 255, 0);
             prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector3;
             prettySparkleParticle.Rotation = rotation;
             prettySparkleParticle.Scale = vector2 * 0.6f;
             prettySparkleParticle.FadeInNormalizedTime = 0.1f;
             prettySparkleParticle.FadeOutNormalizedTime = 0.9f;
             prettySparkleParticle.TimeToLive = 60f;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
         }
         for (int i = 0; i < 2; i++)
         {
             int num5 = Dust.NewDust(newColor: new Color(1f, 0.7f, 0.3f, 0f), Position: settings.PositionInWorld, Width: 0, Height: 0, Type: 267);
             Main.dust[num5].velocity = Main.rand.NextVector2Circular(2f, 2f);
             Main.dust[num5].velocity += settings.MovementVector * (0.5f + 0.5f * Main.rand.NextFloat()) * 1.4f;
             Main.dust[num5].noGravity = true;
             Main.dust[num5].scale = 0.1f;
             Main.dust[num5].position += Main.rand.NextVector2Circular(16f, 16f);
             Main.dust[num5].velocity = settings.MovementVector;
             if (num5 != 6000)
             {
                 Dust dust = Dust.CloneDust(num5);
                 dust.scale /= 2f;
                 dust.fadeIn *= 0.75f;
                 dust.color = new Color(255, 255, 255, 255);
             }
         }
     }
References _poolPrettySparkle, ABasicParticle.AccelerationPerFrame, ParticleRenderer.Add(), Dust.CloneDust(), Color, Dust.color, PrettySparkleParticle.ColorTint, Main.dust, E, Dust.fadeIn, PrettySparkleParticle.FadeInNormalizedTime, PrettySparkleParticle.FadeOutNormalizedTime, ABasicParticle.LocalPosition, ParticleOrchestraSettings.MovementVector, Dust.NewDust(), Dust.noGravity, Main.ParticleSystem_World_OverPlayers, Dust.position, ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Rotation, ABasicParticle.Scale, Dust.scale, PrettySparkleParticle.TimeToLive, ABasicParticle.Velocity, and Dust.velocity.
Referenced by SpawnParticlesDirect().