Terraria: ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames
Spawn_WallOfFleshGoatMountFlames()
static void ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames (ParticleOrchestraSettings settings) inline static private
     {
         float num = 50f;
         for (int i = -1; i <= 1; i++)
         {
             int num2 = Main.rand.NextFromList(new short[3] { 326, 327, 328 });
             Main.instance.LoadProjectile(num2);
             Player player = Main.player[settings.IndexOfPlayerWhoInvokedThis];
             float num3 = Main.rand.NextFloat() * 0.9f + 0.1f;
             Vector2 vector = settings.PositionInWorld + new Vector2((float)i * 5.3333335f, 0f);
             FlameParticle flameParticle = _poolFlame.RequestParticle();
             flameParticle.SetBasicInfo(TextureAssets.Projectile[num2], null, Vector2.Zero, vector);
             flameParticle.SetTypeInfo(num, settings.IndexOfPlayerWhoInvokedThis, player.cMount);
             flameParticle.FadeOutNormalizedTime = 0.3f;
             flameParticle.ScaleAcceleration = Vector2.One * num3 * (-1f / 60f) / num;
             flameParticle.Scale = Vector2.One * num3;
             Main.ParticleSystem_World_BehindPlayers.Add(flameParticle);
             if (Main.rand.Next(8) == 0)
             {
                 Dust dust = Dust.NewDustDirect(vector, 4, 4, 6, 0f, 0f, 100);
                 if (Main.rand.Next(2) == 0)
                 {
                     dust.noGravity = true;
                     dust.fadeIn = 1.15f;
                 }
                 else
                 {
                     dust.scale = 0.6f;
                 }
                 dust.velocity *= 0.6f;
                 dust.velocity.Y -= 1.2f;
                 dust.noLight = true;
                 dust.position.Y -= 4f;
                 dust.shader = GameShaders.Armor.GetSecondaryShader(player.cMount, player);
             }
         }
     }
References _poolFlame, ParticleRenderer.Add(), GameShaders.Armor, Player.cMount, Dust.fadeIn, FlameParticle.FadeOutNormalizedTime, ArmorShaderDataSet.GetSecondaryShader(), ParticleOrchestraSettings.IndexOfPlayerWhoInvokedThis, Main.instance, Main.LoadProjectile(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.ParticleSystem_World_BehindPlayers, Main.player, Dust.position, ParticleOrchestraSettings.PositionInWorld, TextureAssets.Projectile, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Scale, Dust.scale, ABasicParticle.ScaleAcceleration, FlameParticle.SetBasicInfo(), FlameParticle.SetTypeInfo(), Dust.shader, and Dust.velocity.
Referenced by SpawnParticlesDirect().