Terraria: ParticleOrchestrator.BroadcastOrRequestParticleSpawn
BroadcastOrRequestParticleSpawn()
static void ParticleOrchestrator.BroadcastOrRequestParticleSpawn (ParticleOrchestraType type, ParticleOrchestraSettings settings) inline static
     {
         settings.IndexOfPlayerWhoInvokedThis = (byte)Main.myPlayer;
         if (Main.netMode == 1)
         {
             NetManager.Instance.SendToServerAndSelf(NetParticlesModule.Serialize(type, settings));
         }
         else
         {
             NetManager.Instance.BroadcastOrLoopback(NetParticlesModule.Serialize(type, settings));
         }
     }
References NetManager.BroadcastOrLoopback(), ParticleOrchestraSettings.IndexOfPlayerWhoInvokedThis, NetManager.Instance, Main.myPlayer, Main.netMode, NetManager.SendToServerAndSelf(), and NetParticlesModule.Serialize().
Referenced by Player.ShimmerUnstuck(), ShimmerUnstuckHelper.Update(), Chest.VisualizeChestTransfer(), and Chest.VisualizeChestTransfer_CoinsBatch().