Terraria: ParticleOrchestrator.Spawn_StellarTune
Spawn_StellarTune()
static void ParticleOrchestrator.Spawn_StellarTune (ParticleOrchestraSettings settings) inline static private
     {
         float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
         float num2 = 5f;
         Vector2 vector = new Vector2(0.7f);
         for (float num3 = 0f; num3 < 1f; num3 += 1f / num2)
         {
             float num4 = (float)Math.PI * 2f * num3 + num + Main.rand.NextFloatDirection() * 0.25f;
             Vector2 vector2 = 1.5f * vector;
             float num5 = 60f;
             Vector2 vector3 = Main.rand.NextVector2Circular(12f, 12f) * vector;
             Color colorTint = Color.Lerp(Color.Gold, Color.HotPink, Main.rand.NextFloat());
             if (Main.rand.Next(2) == 0)
             {
                 colorTint = Color.Lerp(Color.Violet, Color.HotPink, Main.rand.NextFloat());
             }
             PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             prettySparkleParticle.Velocity = num4.ToRotationVector2() * vector2;
             prettySparkleParticle.AccelerationPerFrame = num4.ToRotationVector2() * -(vector2 / num5);
             prettySparkleParticle.ColorTint = colorTint;
             prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector3;
             prettySparkleParticle.Rotation = num4;
             prettySparkleParticle.Scale = vector * (Main.rand.NextFloat() * 0.8f + 0.2f);
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
         }
         num2 = 1f;
     }
References _poolPrettySparkle, ABasicParticle.AccelerationPerFrame, ParticleRenderer.Add(), Color, PrettySparkleParticle.ColorTint, ABasicParticle.LocalPosition, UnifiedRandom.Next(), Main.ParticleSystem_World_OverPlayers, ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Rotation, ABasicParticle.Scale, and ABasicParticle.Velocity.
Referenced by SpawnParticlesDirect().