Terraria: ParticleOrchestrator.Spawn_LoadOutChange
Spawn_LoadOutChange()
static void ParticleOrchestrator.Spawn_LoadOutChange (ParticleOrchestraSettings settings) inline static private
     {
         Player player = Main.player[settings.IndexOfPlayerWhoInvokedThis];
         if (player.active)
         {
             Rectangle hitbox = player.Hitbox;
             int num = 6;
             hitbox.Height -= num;
             if (player.gravDir == 1f)
             {
                 hitbox.Y += num;
             }
             for (int i = 0; i < 40; i++)
             {
                 Dust dust = Dust.NewDustPerfect(Main.rand.NextVector2FromRectangle(hitbox), 16, null, 120, default(Color), Main.rand.NextFloat() * 0.8f + 0.8f);
                 dust.velocity = new Vector2(0f, (float)(-hitbox.Height) * Main.rand.NextFloat() * 0.04f).RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.1f);
                 dust.velocity += player.velocity * 2f * Main.rand.NextFloat();
                 dust.noGravity = true;
                 dust.noLight = (dust.noLightEmittence = true);
             }
             for (int j = 0; j < 5; j++)
             {
                 Dust dust2 = Dust.NewDustPerfect(Main.rand.NextVector2FromRectangle(hitbox), 43, null, 254, Main.hslToRgb(Main.rand.NextFloat(), 0.3f, 0.8f), Main.rand.NextFloat() * 0.8f + 0.8f);
                 dust2.velocity = new Vector2(0f, (float)(-hitbox.Height) * Main.rand.NextFloat() * 0.04f).RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.1f);
                 dust2.velocity += player.velocity * 2f * Main.rand.NextFloat();
                 dust2.noGravity = true;
                 dust2.noLight = (dust2.noLightEmittence = true);
             }
         }
     }
References Entity.active, Color, Player.gravDir, Entity.Hitbox, Main.hslToRgb(), ParticleOrchestraSettings.IndexOfPlayerWhoInvokedThis, Dust.NewDustPerfect(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, Main.player, Main.rand, Dust.velocity, and Entity.velocity.
Referenced by SpawnParticlesDirect().