Terraria: ParticleOrchestrator.ElderSlimeEffect
ElderSlimeEffect()
static void ParticleOrchestrator.ElderSlimeEffect (ParticleOrchestraSettings settings) inline static private
     {
         for (int i = 0; i < 30; i++)
         {
             Dust dust = Dust.NewDustPerfect(settings.PositionInWorld + Main.rand.NextVector2Circular(20f, 20f), 43, (settings.MovementVector * 0.75f + Main.rand.NextVector2Circular(6f, 6f)) * Main.rand.NextFloat(), 26, Color.Lerp(Main.OurFavoriteColor, Color.White, Main.rand.NextFloat()), 1f + Main.rand.NextFloat() * 1.4f);
             dust.fadeIn = 1.5f;
             if (dust.velocity.Y > 0f && Main.rand.Next(2) == 0)
             {
                 dust.velocity.Y *= -1f;
             }
             dust.noGravity = true;
         }
         for (int j = 0; j < 8; j++)
         {
             Gore.NewGoreDirect(settings.PositionInWorld + Utils.RandomVector2(Main.rand, -30f, 30f) * new Vector2(0.5f, 1f), Vector2.Zero, 61 + Main.rand.Next(3)).velocity *= 0.5f;
         }
     }
References Color, Dust.fadeIn, ParticleOrchestraSettings.MovementVector, Dust.NewDustPerfect(), Gore.NewGoreDirect(), UnifiedRandom.Next(), Dust.noGravity, Main.OurFavoriteColor, ParticleOrchestraSettings.PositionInWorld, Main.rand, Utils.RandomVector2(), Dust.velocity, and Gore.velocity.
Referenced by Spawn_TownSlimeTransform().