Terraria: ParticleOrchestrator.Spawn_ShimmerBlock
Spawn_ShimmerBlock()
static void ParticleOrchestrator.Spawn_ShimmerBlock (ParticleOrchestraSettings settings) inline static private
     {
         FadingParticle fadingParticle = _poolFading.RequestParticle();
         fadingParticle.SetBasicInfo(TextureAssets.Star[0], null, settings.MovementVector, settings.PositionInWorld);
         float num = 45f;
         fadingParticle.SetTypeInfo(num);
         fadingParticle.AccelerationPerFrame = settings.MovementVector / num;
         fadingParticle.ColorTint = Main.hslToRgb(Main.rand.NextFloat(), 0.75f, 0.8f);
         fadingParticle.ColorTint.A = 30;
         fadingParticle.FadeInNormalizedTime = 0.5f;
         fadingParticle.FadeOutNormalizedTime = 0.5f;
         fadingParticle.Rotation = Main.rand.NextFloat() * ((float)Math.PI * 2f);
         fadingParticle.Scale = Vector2.One * (0.5f + 0.5f * Main.rand.NextFloat());
         Main.ParticleSystem_World_OverPlayers.Add(fadingParticle);
     }
References _poolFading, ABasicParticle.AccelerationPerFrame, ParticleRenderer.Add(), FadingParticle.ColorTint, FadingParticle.FadeInNormalizedTime, FadingParticle.FadeOutNormalizedTime, Main.hslToRgb(), ParticleOrchestraSettings.MovementVector, Main.ParticleSystem_World_OverPlayers, ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Rotation, ABasicParticle.Scale, ABasicParticle.SetBasicInfo(), FadingParticle.SetTypeInfo(), and TextureAssets.Star.
Referenced by SpawnParticlesDirect().