Terraria: ParticleOrchestrator.SpawnParticlesDirect
SpawnParticlesDirect()
static void ParticleOrchestrator.SpawnParticlesDirect (ParticleOrchestraType type, ParticleOrchestraSettings settings) inline static
     {
         if (Main.netMode != 2)
         {
             switch (type)
             {
             case ParticleOrchestraType.Keybrand:
                 Spawn_Keybrand(settings);
                 break;
             case ParticleOrchestraType.FlameWaders:
                 Spawn_FlameWaders(settings);
                 break;
             case ParticleOrchestraType.StellarTune:
                 Spawn_StellarTune(settings);
                 break;
             case ParticleOrchestraType.WallOfFleshGoatMountFlames:
                 Spawn_WallOfFleshGoatMountFlames(settings);
                 break;
             case ParticleOrchestraType.BlackLightningHit:
                 Spawn_BlackLightningHit(settings);
                 break;
             case ParticleOrchestraType.RainbowRodHit:
                 Spawn_RainbowRodHit(settings);
                 break;
             case ParticleOrchestraType.BlackLightningSmall:
                 Spawn_BlackLightningSmall(settings);
                 break;
             case ParticleOrchestraType.StardustPunch:
                 Spawn_StardustPunch(settings);
                 break;
             case ParticleOrchestraType.PrincessWeapon:
                 Spawn_PrincessWeapon(settings);
                 break;
             case ParticleOrchestraType.PaladinsHammer:
                 Spawn_PaladinsHammer(settings);
                 break;
             case ParticleOrchestraType.NightsEdge:
                 Spawn_NightsEdge(settings);
                 break;
             case ParticleOrchestraType.SilverBulletSparkle:
                 Spawn_SilverBulletSparkle(settings);
                 break;
             case ParticleOrchestraType.TrueNightsEdge:
                 Spawn_TrueNightsEdge(settings);
                 break;
             case ParticleOrchestraType.ChlorophyteLeafCrystalPassive:
                 Spawn_LeafCrystalPassive(settings);
                 break;
             case ParticleOrchestraType.ChlorophyteLeafCrystalShot:
                 Spawn_LeafCrystalShot(settings);
                 break;
             case ParticleOrchestraType.AshTreeShake:
                 Spawn_AshTreeShake(settings);
                 break;
             case ParticleOrchestraType.TerraBlade:
                 Spawn_TerraBlade(settings);
                 break;
             case ParticleOrchestraType.Excalibur:
                 Spawn_Excalibur(settings);
                 break;
             case ParticleOrchestraType.TrueExcalibur:
                 Spawn_TrueExcalibur(settings);
                 break;
             case ParticleOrchestraType.PetExchange:
                 Spawn_PetExchange(settings);
                 break;
             case ParticleOrchestraType.SlapHand:
                 Spawn_SlapHand(settings);
                 break;
             case ParticleOrchestraType.WaffleIron:
                 Spawn_WaffleIron(settings);
                 break;
             case ParticleOrchestraType.FlyMeal:
                 Spawn_FlyMeal(settings);
                 break;
             case ParticleOrchestraType.GasTrap:
                 Spawn_GasTrap(settings);
                 break;
             case ParticleOrchestraType.ItemTransfer:
                 Spawn_ItemTransfer(settings);
                 break;
             case ParticleOrchestraType.ShimmerArrow:
                 Spawn_ShimmerArrow(settings);
                 break;
             case ParticleOrchestraType.TownSlimeTransform:
                 Spawn_TownSlimeTransform(settings);
                 break;
             case ParticleOrchestraType.LoadoutChange:
                 Spawn_LoadOutChange(settings);
                 break;
             case ParticleOrchestraType.ShimmerBlock:
                 Spawn_ShimmerBlock(settings);
                 break;
             case ParticleOrchestraType.Digestion:
                 Spawn_Digestion(settings);
                 break;
             case ParticleOrchestraType.PooFly:
                 Spawn_PooFly(settings);
                 break;
             case ParticleOrchestraType.ShimmerTownNPC:
                 Spawn_ShimmerTownNPC(settings);
                 break;
             case ParticleOrchestraType.ShimmerTownNPCSend:
                 Spawn_ShimmerTownNPCSend(settings);
                 break;
             }
         }
     }
References Main.netMode, Spawn_AshTreeShake(), Spawn_BlackLightningHit(), Spawn_BlackLightningSmall(), Spawn_Digestion(), Spawn_Excalibur(), Spawn_FlameWaders(), Spawn_FlyMeal(), Spawn_GasTrap(), Spawn_ItemTransfer(), Spawn_Keybrand(), Spawn_LeafCrystalPassive(), Spawn_LeafCrystalShot(), Spawn_LoadOutChange(), Spawn_NightsEdge(), Spawn_PaladinsHammer(), Spawn_PetExchange(), Spawn_PooFly(), Spawn_PrincessWeapon(), Spawn_RainbowRodHit(), Spawn_ShimmerArrow(), Spawn_ShimmerBlock(), Spawn_ShimmerTownNPC(), Spawn_ShimmerTownNPCSend(), Spawn_SilverBulletSparkle(), Spawn_SlapHand(), Spawn_StardustPunch(), Spawn_StellarTune(), Spawn_TerraBlade(), Spawn_TownSlimeTransform(), Spawn_TrueExcalibur(), Spawn_TrueNightsEdge(), Spawn_WaffleIron(), and Spawn_WallOfFleshGoatMountFlames().
Referenced by NetParticlesModule.Deserialize(), and RequestParticleSpawn().