Terraria: ParticleOrchestrator.Spawn_Digestion
Spawn_Digestion()
static void ParticleOrchestrator.Spawn_Digestion (ParticleOrchestraSettings settings) inline static private
     {
         Vector2 positionInWorld = settings.PositionInWorld;
         int num = ((settings.MovementVector.X < 0f) ? 1 : (-1));
         int num2 = Main.rand.Next(4);
         for (int i = 0; i < 3 + num2; i++)
         {
             int num3 = Dust.NewDust(positionInWorld + Vector2.UnitX * -num * 8f - Vector2.One * 5f + Vector2.UnitY * 8f, 3, 6, 216, -num, 1f);
             Main.dust[num3].velocity /= 2f;
             Main.dust[num3].scale = 0.8f;
         }
         if (Main.rand.Next(30) == 0)
         {
             int num4 = Gore.NewGore(positionInWorld + Vector2.UnitX * -num * 8f, Vector2.Zero, Main.rand.Next(580, 583));
             Main.gore[num4].velocity /= 2f;
             Main.gore[num4].velocity.Y = Math.Abs(Main.gore[num4].velocity.Y);
             Main.gore[num4].velocity.X = (0f - Math.Abs(Main.gore[num4].velocity.X)) * (float)num;
         }
         SoundEngine.PlaySound(SoundID.Item16, settings.PositionInWorld);
     }
References Main.dust, Main.gore, SoundID.Item16, ParticleOrchestraSettings.MovementVector, Dust.NewDust(), Gore.NewGore(), UnifiedRandom.Next(), SoundEngine.PlaySound(), ParticleOrchestraSettings.PositionInWorld, Main.rand, Dust.scale, Dust.velocity, and Gore.velocity.
Referenced by SpawnParticlesDirect().