Terraria: ParticleOrchestrator.Spawn_TerraBlade
Spawn_TerraBlade()
static void ParticleOrchestrator.Spawn_TerraBlade (ParticleOrchestraSettings settings) inline static private
     {
         float num = 30f;
         float num2 = settings.MovementVector.ToRotation() + (float)Math.PI / 2f;
         float x = 3f;
         for (float num3 = 0f; num3 < 4f; num3 += 1f)
         {
             PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             Vector2 vector = ((float)Math.PI / 2f * num3 + num2).ToRotationVector2() * 4f;
             prettySparkleParticle.ColorTint = new Color(0.2f, 0.85f, 0.4f, 0.5f);
             prettySparkleParticle.LocalPosition = settings.PositionInWorld;
             prettySparkleParticle.Rotation = vector.ToRotation();
             prettySparkleParticle.Scale = new Vector2(x, 0.5f) * 1.1f;
             prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle.TimeToLive = num;
             prettySparkleParticle.FadeOutEnd = num;
             prettySparkleParticle.FadeInEnd = num / 2f;
             prettySparkleParticle.FadeOutStart = num / 2f;
             prettySparkleParticle.AdditiveAmount = 0.35f;
             prettySparkleParticle.Velocity = -vector * 0.2f;
             prettySparkleParticle.DrawVerticalAxis = false;
             if (num3 % 2f == 1f)
             {
                 prettySparkleParticle.Scale *= 1.5f;
                 prettySparkleParticle.Velocity *= 2f;
             }
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
         }
         for (float num4 = -1f; num4 <= 1f; num4 += 2f)
         {
             PrettySparkleParticle prettySparkleParticle2 = _poolPrettySparkle.RequestParticle();
             _ = num2.ToRotationVector2() * 4f;
             Vector2 vector2 = ((float)Math.PI / 2f * num4 + num2).ToRotationVector2() * 2f;
             prettySparkleParticle2.ColorTint = new Color(0.4f, 1f, 0.4f, 0.5f);
             prettySparkleParticle2.LocalPosition = settings.PositionInWorld;
             prettySparkleParticle2.Rotation = vector2.ToRotation();
             prettySparkleParticle2.Scale = new Vector2(x, 0.5f) * 1.1f;
             prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle2.TimeToLive = num;
             prettySparkleParticle2.FadeOutEnd = num;
             prettySparkleParticle2.FadeInEnd = num / 2f;
             prettySparkleParticle2.FadeOutStart = num / 2f;
             prettySparkleParticle2.AdditiveAmount = 0.35f;
             prettySparkleParticle2.Velocity = vector2.RotatedBy(1.5707963705062866) * 0.5f;
             prettySparkleParticle2.DrawVerticalAxis = false;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
         }
         for (float num5 = 0f; num5 < 4f; num5 += 1f)
         {
             PrettySparkleParticle prettySparkleParticle3 = _poolPrettySparkle.RequestParticle();
             Vector2 vector3 = ((float)Math.PI / 2f * num5 + num2).ToRotationVector2() * 4f;
             prettySparkleParticle3.ColorTint = new Color(0.2f, 1f, 0.2f, 1f);
             prettySparkleParticle3.LocalPosition = settings.PositionInWorld;
             prettySparkleParticle3.Rotation = vector3.ToRotation();
             prettySparkleParticle3.Scale = new Vector2(x, 0.5f) * 0.7f;
             prettySparkleParticle3.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle3.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle3.TimeToLive = num;
             prettySparkleParticle3.FadeOutEnd = num;
             prettySparkleParticle3.FadeInEnd = num / 2f;
             prettySparkleParticle3.FadeOutStart = num / 2f;
             prettySparkleParticle3.Velocity = vector3 * 0.2f;
             prettySparkleParticle3.DrawVerticalAxis = false;
             if (num5 % 2f == 1f)
             {
                 prettySparkleParticle3.Scale *= 1.5f;
                 prettySparkleParticle3.Velocity *= 2f;
             }
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle3);
             for (int i = 0; i < 1; i++)
             {
                 Dust dust = Dust.NewDustPerfect(settings.PositionInWorld, 107, vector3.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                 dust.noGravity = true;
                 dust.scale = 0.8f;
                 Dust dust2 = Dust.NewDustPerfect(settings.PositionInWorld, 107, -vector3.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                 dust2.noGravity = true;
                 dust2.scale = 1.4f;
             }
         }
     }
References _poolPrettySparkle, ParticleRenderer.Add(), PrettySparkleParticle.AdditiveAmount, Color, PrettySparkleParticle.ColorTint, PrettySparkleParticle.DrawVerticalAxis, E, PrettySparkleParticle.FadeInEnd, PrettySparkleParticle.FadeInNormalizedTime, PrettySparkleParticle.FadeOutEnd, PrettySparkleParticle.FadeOutNormalizedTime, PrettySparkleParticle.FadeOutStart, ABasicParticle.LocalPosition, ParticleOrchestraSettings.MovementVector, Dust.NewDustPerfect(), Dust.noGravity, Main.ParticleSystem_World_OverPlayers, ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Rotation, ABasicParticle.Scale, Dust.scale, PrettySparkleParticle.TimeToLive, and ABasicParticle.Velocity.
Referenced by SpawnParticlesDirect().