Terraria: ParticleOrchestrator.Spawn_GasTrap
Spawn_GasTrap()
static void ParticleOrchestrator.Spawn_GasTrap (ParticleOrchestraSettings settings) inline static private
     {
         SoundEngine.PlaySound(SoundID.Item16, settings.PositionInWorld);
         Vector2 movementVector = settings.MovementVector;
         int num = 12;
         int num2 = 10;
         float num3 = 5f;
         float num4 = 2.5f;
         Color lightColorTint = new Color(0.2f, 0.4f, 0.15f);
         Vector2 positionInWorld = settings.PositionInWorld;
         float num5 = (float)Math.PI / 20f;
         float num6 = (float)Math.PI / 15f;
         for (int i = 0; i < num; i++)
         {
             Vector2 spinninpoint = movementVector + new Vector2(num3 + Main.rand.NextFloat() * 1f, 0f).RotatedBy((float)i / (float)num * ((float)Math.PI * 2f), Vector2.Zero);
             spinninpoint = spinninpoint.RotatedByRandom(num5);
             GasParticle gasParticle = _poolGas.RequestParticle();
             gasParticle.AccelerationPerFrame = Vector2.Zero;
             gasParticle.Velocity = spinninpoint;
             gasParticle.ColorTint = Color.White;
             gasParticle.LightColorTint = lightColorTint;
             gasParticle.LocalPosition = positionInWorld + spinninpoint;
             gasParticle.TimeToLive = 50 + Main.rand.Next(20);
             gasParticle.InitialScale = 1f + Main.rand.NextFloat() * 0.35f;
             Main.ParticleSystem_World_BehindPlayers.Add(gasParticle);
         }
         for (int j = 0; j < num2; j++)
         {
             Vector2 spinninpoint2 = new Vector2(num4 + Main.rand.NextFloat() * 1.45f, 0f).RotatedBy((float)j / (float)num2 * ((float)Math.PI * 2f), Vector2.Zero);
             spinninpoint2 = spinninpoint2.RotatedByRandom(num6);
             if (j % 2 == 0)
             {
                 spinninpoint2 *= 0.5f;
             }
             GasParticle gasParticle2 = _poolGas.RequestParticle();
             gasParticle2.AccelerationPerFrame = Vector2.Zero;
             gasParticle2.Velocity = spinninpoint2;
             gasParticle2.ColorTint = Color.White;
             gasParticle2.LightColorTint = lightColorTint;
             gasParticle2.LocalPosition = positionInWorld;
             gasParticle2.TimeToLive = 80 + Main.rand.Next(30);
             gasParticle2.InitialScale = 1f + Main.rand.NextFloat() * 0.5f;
             Main.ParticleSystem_World_BehindPlayers.Add(gasParticle2);
         }
     }
References _poolGas, ABasicParticle.AccelerationPerFrame, ParticleRenderer.Add(), Color, GasParticle.ColorTint, GasParticle.InitialScale, SoundID.Item16, GasParticle.LightColorTint, ABasicParticle.LocalPosition, ParticleOrchestraSettings.MovementVector, UnifiedRandom.Next(), Main.ParticleSystem_World_BehindPlayers, SoundEngine.PlaySound(), ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), GasParticle.TimeToLive, and ABasicParticle.Velocity.
Referenced by SpawnParticlesDirect().