Terraria: ParticleOrchestrator.Spawn_ShimmerArrow
Spawn_ShimmerArrow()
static void ParticleOrchestrator.Spawn_ShimmerArrow (ParticleOrchestraSettings settings) inline static private
     {
         float num = 20f;
         for (int i = 0; i < 2; i++)
         {
             float num2 = (float)Math.PI * 2f * Main.rand.NextFloatDirection() * 0.05f;
             Color color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f);
             color.A /= 2;
             Color value = color;
             value.A = byte.MaxValue;
             value = Color.Lerp(value, Color.White, 0.5f);
             for (float num3 = 0f; num3 < 4f; num3 += 1f)
             {
                 PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
                 Vector2 vector = ((float)Math.PI / 2f * num3 + num2).ToRotationVector2() * 4f;
                 prettySparkleParticle.ColorTint = color;
                 prettySparkleParticle.LocalPosition = settings.PositionInWorld;
                 prettySparkleParticle.Rotation = vector.ToRotation();
                 prettySparkleParticle.Scale = new Vector2((num3 % 2f == 0f) ? 2f : 4f, 0.5f) * 1.1f;
                 prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
                 prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
                 prettySparkleParticle.TimeToLive = num;
                 prettySparkleParticle.FadeOutEnd = num;
                 prettySparkleParticle.FadeInEnd = num / 2f;
                 prettySparkleParticle.FadeOutStart = num / 2f;
                 prettySparkleParticle.AdditiveAmount = 0.35f;
                 prettySparkleParticle.Velocity = -vector * 0.2f;
                 prettySparkleParticle.DrawVerticalAxis = false;
                 if (num3 % 2f == 1f)
                 {
                     prettySparkleParticle.Scale *= 0.9f;
                     prettySparkleParticle.Velocity *= 0.9f;
                 }
                 Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
             }
             for (float num4 = 0f; num4 < 4f; num4 += 1f)
             {
                 PrettySparkleParticle prettySparkleParticle2 = _poolPrettySparkle.RequestParticle();
                 Vector2 vector2 = ((float)Math.PI / 2f * num4 + num2).ToRotationVector2() * 4f;
                 prettySparkleParticle2.ColorTint = value;
                 prettySparkleParticle2.LocalPosition = settings.PositionInWorld;
                 prettySparkleParticle2.Rotation = vector2.ToRotation();
                 prettySparkleParticle2.Scale = new Vector2((num4 % 2f == 0f) ? 2f : 4f, 0.5f) * 0.7f;
                 prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
                 prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
                 prettySparkleParticle2.TimeToLive = num;
                 prettySparkleParticle2.FadeOutEnd = num;
                 prettySparkleParticle2.FadeInEnd = num / 2f;
                 prettySparkleParticle2.FadeOutStart = num / 2f;
                 prettySparkleParticle2.Velocity = vector2 * 0.2f;
                 prettySparkleParticle2.DrawVerticalAxis = false;
                 if (num4 % 2f == 1f)
                 {
                     prettySparkleParticle2.Scale *= 1.2f;
                     prettySparkleParticle2.Velocity *= 1.2f;
                 }
                 Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
                 if (i == 0)
                 {
                     for (int j = 0; j < 1; j++)
                     {
                         Dust dust = Dust.NewDustPerfect(settings.PositionInWorld, 306, vector2.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                         dust.noGravity = true;
                         dust.scale = 1.4f;
                         dust.fadeIn = 1.2f;
                         dust.color = color;
                         Dust dust2 = Dust.NewDustPerfect(settings.PositionInWorld, 306, -vector2.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                         dust2.noGravity = true;
                         dust2.scale = 1.4f;
                         dust2.fadeIn = 1.2f;
                         dust2.color = color;
                     }
                 }
             }
         }
     }
References _poolPrettySparkle, ParticleRenderer.Add(), PrettySparkleParticle.AdditiveAmount, Color, Dust.color, PrettySparkleParticle.ColorTint, PrettySparkleParticle.DrawVerticalAxis, E, Dust.fadeIn, PrettySparkleParticle.FadeInEnd, PrettySparkleParticle.FadeInNormalizedTime, PrettySparkleParticle.FadeOutEnd, PrettySparkleParticle.FadeOutNormalizedTime, PrettySparkleParticle.FadeOutStart, Main.hslToRgb(), ABasicParticle.LocalPosition, Dust.NewDustPerfect(), Dust.noGravity, Main.ParticleSystem_World_OverPlayers, ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Rotation, ABasicParticle.Scale, Dust.scale, PrettySparkleParticle.TimeToLive, and ABasicParticle.Velocity.
Referenced by SpawnParticlesDirect().