Terraria: ParticleOrchestrator.Spawn_AshTreeShake
Spawn_AshTreeShake()
static void ParticleOrchestrator.Spawn_AshTreeShake (ParticleOrchestraSettings settings) inline static private
     {
         float num = 10f + 20f * Main.rand.NextFloat();
         float num2 = -(float)Math.PI / 4f;
         float num3 = 0.2f + 0.4f * Main.rand.NextFloat();
         Color colorTint = Main.hslToRgb(Main.rand.NextFloat() * 0.1f + 0.06f, 1f, 0.5f);
         colorTint.A /= 2;
         colorTint *= Main.rand.NextFloat() * 0.3f + 0.7f;
         for (float num4 = 0f; num4 < 2f; num4 += 1f)
         {
             PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             Vector2 vector = ((float)Math.PI / 4f + (float)Math.PI * num4 + num2).ToRotationVector2() * 4f;
             prettySparkleParticle.ColorTint = colorTint;
             prettySparkleParticle.LocalPosition = settings.PositionInWorld;
             prettySparkleParticle.Rotation = vector.ToRotation();
             prettySparkleParticle.Scale = new Vector2(4f, 1f) * 1.1f * num3;
             prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle.TimeToLive = num;
             prettySparkleParticle.FadeOutEnd = num;
             prettySparkleParticle.FadeInEnd = num / 2f;
             prettySparkleParticle.FadeOutStart = num / 2f;
             prettySparkleParticle.AdditiveAmount = 0.35f;
             prettySparkleParticle.LocalPosition -= vector * num * 0.25f;
             prettySparkleParticle.Velocity = vector * 0.05f;
             prettySparkleParticle.DrawVerticalAxis = false;
             if (num4 == 1f)
             {
                 prettySparkleParticle.Scale *= 1.5f;
                 prettySparkleParticle.Velocity *= 1.5f;
                 prettySparkleParticle.LocalPosition -= prettySparkleParticle.Velocity * 4f;
             }
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
         }
         for (float num5 = 0f; num5 < 2f; num5 += 1f)
         {
             PrettySparkleParticle prettySparkleParticle2 = _poolPrettySparkle.RequestParticle();
             Vector2 vector2 = ((float)Math.PI / 4f + (float)Math.PI * num5 + num2).ToRotationVector2() * 4f;
             prettySparkleParticle2.ColorTint = new Color(1f, 0.4f, 0.2f, 1f);
             prettySparkleParticle2.LocalPosition = settings.PositionInWorld;
             prettySparkleParticle2.Rotation = vector2.ToRotation();
             prettySparkleParticle2.Scale = new Vector2(4f, 1f) * 0.7f * num3;
             prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle2.TimeToLive = num;
             prettySparkleParticle2.FadeOutEnd = num;
             prettySparkleParticle2.FadeInEnd = num / 2f;
             prettySparkleParticle2.FadeOutStart = num / 2f;
             prettySparkleParticle2.LocalPosition -= vector2 * num * 0.25f;
             prettySparkleParticle2.Velocity = vector2 * 0.05f;
             prettySparkleParticle2.DrawVerticalAxis = false;
             if (num5 == 1f)
             {
                 prettySparkleParticle2.Scale *= 1.5f;
                 prettySparkleParticle2.Velocity *= 1.5f;
                 prettySparkleParticle2.LocalPosition -= prettySparkleParticle2.Velocity * 4f;
             }
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
             for (int i = 0; i < 1; i++)
             {
                 Dust dust = Dust.NewDustPerfect(settings.PositionInWorld, 6, vector2.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                 dust.noGravity = true;
                 dust.scale = 1.4f;
                 Dust dust2 = Dust.NewDustPerfect(settings.PositionInWorld, 6, -vector2.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                 dust2.noGravity = true;
                 dust2.scale = 1.4f;
             }
         }
     }
References _poolPrettySparkle, ParticleRenderer.Add(), PrettySparkleParticle.AdditiveAmount, Color, PrettySparkleParticle.ColorTint, PrettySparkleParticle.DrawVerticalAxis, E, PrettySparkleParticle.FadeInEnd, PrettySparkleParticle.FadeInNormalizedTime, PrettySparkleParticle.FadeOutEnd, PrettySparkleParticle.FadeOutNormalizedTime, PrettySparkleParticle.FadeOutStart, Main.hslToRgb(), ABasicParticle.LocalPosition, Dust.NewDustPerfect(), Dust.noGravity, Main.ParticleSystem_World_OverPlayers, ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Rotation, ABasicParticle.Scale, Dust.scale, PrettySparkleParticle.TimeToLive, and ABasicParticle.Velocity.
Referenced by SpawnParticlesDirect().