Terraria: ParticleOrchestrator.RequestParticleSpawn
RequestParticleSpawn()
static void ParticleOrchestrator.RequestParticleSpawn (bool clientOnly, ParticleOrchestraType type, ParticleOrchestraSettings settings, int? overrideInvokingPlayerIndex = null) inline static
     {
         settings.IndexOfPlayerWhoInvokedThis = (byte)Main.myPlayer;
         if (overrideInvokingPlayerIndex.HasValue)
         {
             settings.IndexOfPlayerWhoInvokedThis = (byte)overrideInvokingPlayerIndex.Value;
         }
         if (clientOnly)
         {
             SpawnParticlesDirect(type, settings);
         }
         else
         {
             NetManager.Instance.SendToServerAndSelf(NetParticlesModule.Serialize(type, settings));
         }
     }
References ParticleOrchestraSettings.IndexOfPlayerWhoInvokedThis, NetManager.Instance, Main.myPlayer, NetManager.SendToServerAndSelf(), NetParticlesModule.Serialize(), and SpawnParticlesDirect().
Referenced by NPC.AI_007_TownEntities(), Projectile.AI_165_Whip(), Projectile.AI_186_PrincessWeapon(), Projectile.Damage(), Player.DoBootsEffect_PlaceFlamesOnTile(), TileDrawing.DrawTiles_EmitParticles(), Projectile.EmitBlackLightningParticles(), NPC.HitEffect(), Player.ItemCheck_ApplyUseStyle(), Projectile.Kill(), Player.MakeFloorDust(), Player.ProcessHitAgainstNPC(), Player.TryBouncingBlocks(), Player.TrySwitchingLoadout(), Player.TryToPoop(), Mount.UpdateFrame(), and NPC.UpdateNPC_BuffApplyVFX().