Terraria: PotionOfReturnHelper.TryGetGateHitbox
TryGetGateHitbox()
static bool PotionOfReturnHelper.TryGetGateHitbox (Player player, out Rectangle homeHitbox) inline static
     {
         homeHitbox = Rectangle.Empty;
         if (!player.PotionOfReturnHomePosition.HasValue)
         {
             return false;
         }
         Vector2 vector = new Vector2(0f, -21f);
         Vector2 center = player.PotionOfReturnHomePosition.Value + vector;
         homeHitbox = Utils.CenteredRectangle(center, new Vector2(24f, 40f));
         return true;
     }
References Utils.CenteredRectangle(), and Player.PotionOfReturnHomePosition.
Referenced by ReturnGatePlayerRenderer.DrawReturnGateInWorld(), and PotionOfReturnSmartInteractCandidateProvider.ProvideCandidate().