Terraria: Internal.Cryptography.HashProvider.AppendHashData
AppendHashData() [1/3]
void Internal.Cryptography.HashProvider.AppendHashData (byte[] data, int offset, int count) inline inherited
Definition at line 9 of file HashProvider.cs.
    {
        if (data == null)
        {
            throw new ArgumentNullException("data", System.SR.ArgumentNull_Buffer);
        }
        if (offset < 0)
        {
            throw new ArgumentOutOfRangeException("offset", System.SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", System.SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (data.Length - offset < count)
        {
            throw new ArgumentException(System.SR.Argument_InvalidOffLen);
        }
        AppendHashData(new ReadOnlySpan<byte>(data, offset, count));
    }
References Internal.Cryptography.HashProvider.AppendHashData(), System.SR.Argument_InvalidOffLen, System.SR.ArgumentNull_Buffer, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.count, and System.offset.
Referenced by System.Security.Cryptography.IncrementalHash.AppendData(), Internal.Cryptography.HashProvider.AppendHashData(), Internal.Cryptography.HMACCommon.AppendHashData(), Internal.Cryptography.HMACCommon.AppendHashData(), Internal.Cryptography.HMACCommon.ChangeKeyImpl(), System.Security.Cryptography.MD5.Implementation.HashCore(), System.Security.Cryptography.SHA1.Implementation.HashCore(), System.Security.Cryptography.SHA1Managed.HashCore(), System.Security.Cryptography.SHA256.Implementation.HashCore(), System.Security.Cryptography.SHA256Managed.HashCore(), System.Security.Cryptography.SHA384.Implementation.HashCore(), System.Security.Cryptography.SHA384Managed.HashCore(), System.Security.Cryptography.SHA512.Implementation.HashCore(), System.Security.Cryptography.SHA512Managed.HashCore(), System.Security.Cryptography.MD5.Implementation.HashCore(), System.Security.Cryptography.SHA1.Implementation.HashCore(), System.Security.Cryptography.SHA1Managed.HashCore(), System.Security.Cryptography.SHA256.Implementation.HashCore(), System.Security.Cryptography.SHA256Managed.HashCore(), System.Security.Cryptography.SHA384.Implementation.HashCore(), System.Security.Cryptography.SHA384Managed.HashCore(), System.Security.Cryptography.SHA512.Implementation.HashCore(), and System.Security.Cryptography.SHA512Managed.HashCore().