Terraria: Internal.Cryptography.HashProvider.Dispose
Dispose() [1/3]
void Internal.Cryptography.HashProvider.Dispose () inline inherited
Implements System.IDisposable.
Definition at line 54 of file HashProvider.cs.
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
References Internal.Cryptography.HashProvider.Dispose(), and System.GC.SuppressFinalize().
Referenced by Internal.Cryptography.HMACCommon.ChangeKeyImpl(), Internal.Cryptography.HashProvider.Dispose(), System.Security.Cryptography.IncrementalHash.Dispose(), Internal.Cryptography.HMACCommon.Dispose(), System.Security.Cryptography.MD5.Implementation.Dispose(), System.Security.Cryptography.SHA1.Implementation.Dispose(), System.Security.Cryptography.SHA1Managed.Dispose(), System.Security.Cryptography.SHA256.Implementation.Dispose(), System.Security.Cryptography.SHA256Managed.Dispose(), System.Security.Cryptography.SHA384.Implementation.Dispose(), System.Security.Cryptography.SHA384Managed.Dispose(), System.Security.Cryptography.SHA512.Implementation.Dispose(), and System.Security.Cryptography.SHA512Managed.Dispose().