Terraria: System.Xml.Xsl.XsltOld.ContainerAction.CompileInclude
CompileInclude()
void System.Xml.Xsl.XsltOld.ContainerAction.CompileInclude (Compiler compiler) inline private inherited
Definition at line 176 of file ContainerAction.cs.
    {
        Uri uri = compiler.ResolveUri(compiler.GetSingleAttribute(compiler.Input.Atoms.Href));
        string text = uri.ToString();
        if (compiler.IsCircularReference(text))
        {
            throw XsltException.Create(System.SR.Xslt_CircularInclude, text);
        }
        NavigatorInput navigatorInput = compiler.ResolveDocument(uri);
        compiler.PushInputDocument(navigatorInput);
        try
        {
            CompileDocument(compiler, inInclude: true);
        }
        catch (XsltCompileException)
        {
            throw;
        }
        catch (Exception inner)
        {
            throw new XsltCompileException(inner, navigatorInput.BaseURI, navigatorInput.LineNumber, navigatorInput.LinePosition);
        }
        finally
        {
            compiler.PopInputDocument();
        }
        CheckEmpty(compiler);
    }
References System.Xml.Xsl.XsltOld.CompiledAction.CheckEmpty(), System.Xml.Xsl.XsltOld.ContainerAction.CompileDocument(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.text, System.Uri.ToString(), and System.SR.Xslt_CircularInclude.
Referenced by System.Xml.Xsl.XsltOld.ContainerAction.CompileTopLevelElements().