Terraria: System.Xml.Xsl.XsltOld.ContainerAction.AddEvent
AddEvent()
void System.Xml.Xsl.XsltOld.ContainerAction.AddEvent (Event copyEvent) inline protected inherited
Definition at line 755 of file ContainerAction.cs.
    {
        EnsureCopyCodeAction();
        lastCopyCodeAction.AddEvent(copyEvent);
    }
References System.Xml.Xsl.XsltOld.CopyCodeAction.AddEvent(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.ContainerAction.EnsureCopyCodeAction(), and System.Xml.Xsl.XsltOld.ContainerAction.lastCopyCodeAction.
Referenced by System.Xml.Xsl.XsltOld.ContainerAction.CompileLiteral(), System.Xml.Xsl.XsltOld.ContainerAction.CompileLiteralAttributesAndNamespaces(), System.Xml.Xsl.XsltOld.TemplateAction.CompileParameters(), and System.Xml.Xsl.XsltOld.ForEachAction.CompileSortElements().