Terraria: System.Xml.Xsl.XsltOld.ContainerAction.AddAction
AddAction()
void System.Xml.Xsl.XsltOld.ContainerAction.AddAction (Action action) inline package inherited
Definition at line 734 of file ContainerAction.cs.
    {
        if (containedActions == null)
        {
            containedActions = new ArrayList();
        }
        containedActions.Add(action);
        lastCopyCodeAction = null;
    }
References System.action, System.Collections.ArrayList.Add(), System.Xml.Xsl.XsltOld.ContainerAction.containedActions, and System.Xml.Xsl.XsltOld.ContainerAction.lastCopyCodeAction.
Referenced by System.Xml.Xsl.XsltOld.AttributeSetAction.CompileAttribute(), System.Xml.Xsl.XsltOld.CopyAction.CompileAttribute(), System.Xml.Xsl.XsltOld.ElementAction.CompileAttribute(), System.Xml.Xsl.XsltOld.ChooseAction.CompileConditions(), System.Xml.Xsl.XsltOld.ApplyTemplatesAction.CompileContent(), System.Xml.Xsl.XsltOld.AttributeSetAction.CompileContent(), System.Xml.Xsl.XsltOld.CallTemplateAction.CompileContent(), System.Xml.Xsl.XsltOld.ContainerAction.CompileInstruction(), System.Xml.Xsl.XsltOld.ContainerAction.CompileLiteralAttributesAndNamespaces(), System.Xml.Xsl.XsltOld.ContainerAction.CompileOnceTemplate(), System.Xml.Xsl.XsltOld.TemplateAction.CompileParameters(), System.Xml.Xsl.XsltOld.ForEachAction.CompileSortElements(), System.Xml.Xsl.XsltOld.ContainerAction.CompileTopLevelElements(), System.Xml.Xsl.XsltOld.ContainerAction.EnsureCopyCodeAction(), and System.Xml.Xsl.XsltOld.AttributeSetAction.Merge().