Terraria: System.Xml.Xsl.XsltOld.ContainerAction.CompileDecimalFormat
CompileDecimalFormat()
void System.Xml.Xsl.XsltOld.ContainerAction.CompileDecimalFormat (Compiler compiler) inline protected inherited
Definition at line 289 of file ContainerAction.cs.
    {
        NumberFormatInfo numberFormatInfo = new NumberFormatInfo();
        DecimalFormat decimalFormat = new DecimalFormat(numberFormatInfo, '#', '0', ';');
        XmlQualifiedName xmlQualifiedName = null;
        NavigatorInput input = compiler.Input;
        if (input.MoveToFirstAttribute())
        {
            do
            {
                if (input.Prefix.Length != 0)
                {
                    continue;
                }
                string localName = input.LocalName;
                string value = input.Value;
                if (Ref.Equal(localName, input.Atoms.Name))
                {
                    xmlQualifiedName = compiler.CreateXPathQName(value);
                }
                else if (Ref.Equal(localName, input.Atoms.DecimalSeparator))
                {
                    numberFormatInfo.NumberDecimalSeparator = value;
                }
                else if (Ref.Equal(localName, input.Atoms.GroupingSeparator))
                {
                    numberFormatInfo.NumberGroupSeparator = value;
                }
                else if (Ref.Equal(localName, input.Atoms.Infinity))
                {
                    numberFormatInfo.PositiveInfinitySymbol = value;
                }
                else if (Ref.Equal(localName, input.Atoms.MinusSign))
                {
                    numberFormatInfo.NegativeSign = value;
                }
                else if (Ref.Equal(localName, input.Atoms.NaN))
                {
                    numberFormatInfo.NaNSymbol = value;
                }
                else if (Ref.Equal(localName, input.Atoms.Percent))
                {
                    numberFormatInfo.PercentSymbol = value;
                }
                else if (Ref.Equal(localName, input.Atoms.PerMille))
                {
                    numberFormatInfo.PerMilleSymbol = value;
                }
                else if (Ref.Equal(localName, input.Atoms.Digit))
                {
                    if (CheckAttribute(value.Length == 1, compiler))
                    {
                        decimalFormat.digit = value[0];
                    }
                }
                else if (Ref.Equal(localName, input.Atoms.ZeroDigit))
                {
                    if (CheckAttribute(value.Length == 1, compiler))
                    {
                        decimalFormat.zeroDigit = value[0];
                    }
                }
                else if (Ref.Equal(localName, input.Atoms.PatternSeparator) && CheckAttribute(value.Length == 1, compiler))
                {
                    decimalFormat.patternSeparator = value[0];
                }
            }
            while (input.MoveToNextAttribute());
            input.ToParent();
        }
        numberFormatInfo.NegativeInfinitySymbol = numberFormatInfo.NegativeSign + numberFormatInfo.PositiveInfinitySymbol;
        if (xmlQualifiedName == null)
        {
            xmlQualifiedName = new XmlQualifiedName();
        }
        compiler.AddDecimalFormat(xmlQualifiedName, decimalFormat);
        CheckEmpty(compiler);
    }
References System.Xml.Xsl.XsltOld.ContainerAction.CheckAttribute(), System.Xml.Xsl.XsltOld.CompiledAction.CheckEmpty(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.input, System.Xml.Xsl.XsltOld.NavigatorInput.LocalName, and System.value.
Referenced by System.Xml.Xsl.XsltOld.ContainerAction.CompileTopLevelElements().