Terraria: System.Xml.Xsl.XsltOld.ContainerAction.AddScript
AddScript()
void System.Xml.Xsl.XsltOld.ContainerAction.AddScript (Compiler compiler) inline private inherited
Definition at line 767 of file ContainerAction.cs.
    {
        NavigatorInput input = compiler.Input;
        ScriptingLanguage lang = ScriptingLanguage.JScript;
        string text = null;
        if (input.MoveToFirstAttribute())
        {
            do
            {
                if (input.LocalName == input.Atoms.Language)
                {
                    string value = input.Value;
                    if (string.Equals(value, "jscript", StringComparison.OrdinalIgnoreCase) || string.Equals(value, "javascript", StringComparison.OrdinalIgnoreCase))
                    {
                        lang = ScriptingLanguage.JScript;
                        continue;
                    }
                    if (string.Equals(value, "c#", StringComparison.OrdinalIgnoreCase) || string.Equals(value, "csharp", StringComparison.OrdinalIgnoreCase))
                    {
                        lang = ScriptingLanguage.CSharp;
                        continue;
                    }
                    if (!string.Equals(value, "vb", StringComparison.OrdinalIgnoreCase) && !string.Equals(value, "visualbasic", StringComparison.OrdinalIgnoreCase))
                    {
                        throw XsltException.Create(System.SR.Xslt_ScriptInvalidLanguage, value);
                    }
                    lang = ScriptingLanguage.VisualBasic;
                }
                else if (input.LocalName == input.Atoms.ImplementsPrefix)
                {
                    if (!PrefixQName.ValidatePrefix(input.Value))
                    {
                        throw XsltException.Create(System.SR.Xslt_InvalidAttrValue, input.LocalName, input.Value);
                    }
                    text = compiler.ResolveXmlNamespace(input.Value);
                }
            }
            while (input.MoveToNextAttribute());
            input.ToParent();
        }
        if (text == null)
        {
            throw XsltException.Create(System.SR.Xslt_MissingAttribute, input.Atoms.ImplementsPrefix);
        }
        if (!input.Recurse() || input.NodeType != XPathNodeType.Text)
        {
            throw XsltException.Create(System.SR.Xslt_ScriptEmpty);
        }
        compiler.AddScript(input.Value, lang, text, input.BaseURI, input.LineNumber);
        input.ToParent();
    }
References System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.input, System.text, System.Xml.Xsl.XsltOld.PrefixQName.ValidatePrefix(), System.value, System.Xml.Xsl.XsltOld.NavigatorInput.Value, System.SR.Xslt_InvalidAttrValue, System.SR.Xslt_MissingAttribute, System.SR.Xslt_ScriptEmpty, and System.SR.Xslt_ScriptInvalidLanguage.
Referenced by System.Xml.Xsl.XsltOld.ContainerAction.CompileTopLevelElements().