Terraria: System.Xml.Xsl.XsltOld.ContainerAction.CompileNamespaceAlias
CompileNamespaceAlias()
void System.Xml.Xsl.XsltOld.ContainerAction.CompileNamespaceAlias (Compiler compiler) inline package inherited
Definition at line 205 of file ContainerAction.cs.
    {
        NavigatorInput input = compiler.Input;
        string localName = input.LocalName;
        string text = null;
        string text2 = null;
        string text3 = null;
        string prefix = null;
        if (input.MoveToFirstAttribute())
        {
            do
            {
                string namespaceURI = input.NamespaceURI;
                string localName2 = input.LocalName;
                if (namespaceURI.Length == 0)
                {
                    if (Ref.Equal(localName2, input.Atoms.StylesheetPrefix))
                    {
                        text3 = input.Value;
                        text = compiler.GetNsAlias(ref text3);
                    }
                    else if (Ref.Equal(localName2, input.Atoms.ResultPrefix))
                    {
                        prefix = input.Value;
                        text2 = compiler.GetNsAlias(ref prefix);
                    }
                    else if (!compiler.ForwardCompatibility)
                    {
                        throw XsltException.Create(System.SR.Xslt_InvalidAttribute, localName2, localName);
                    }
                }
            }
            while (input.MoveToNextAttribute());
            input.ToParent();
        }
        CheckRequiredAttribute(compiler, text, "stylesheet-prefix");
        CheckRequiredAttribute(compiler, text2, "result-prefix");
        CheckEmpty(compiler);
        compiler.AddNamespaceAlias(text, new NamespaceInfo(prefix, text2, compiler.Stylesheetid));
    }
References System.Xml.Xsl.XsltOld.CompiledAction.CheckEmpty(), System.Xml.Xsl.XsltOld.CompiledAction.CheckRequiredAttribute(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.input, System.Xml.Xsl.XsltOld.NavigatorInput.LocalName, System.prefix, System.text, and System.SR.Xslt_InvalidAttribute.
Referenced by System.Xml.Xsl.XsltOld.ContainerAction.CompileTopLevelElements().