Terraria: System.Xml.Xsl.XsltOld.ContainerAction.CompileDocument
CompileDocument()
void System.Xml.Xsl.XsltOld.ContainerAction.CompileDocument (Compiler compiler, bool inInclude) inline protected inherited
Definition at line 105 of file ContainerAction.cs.
    {
        NavigatorInput input = compiler.Input;
        while (input.NodeType != XPathNodeType.Element)
        {
            if (!compiler.Advance())
            {
                throw XsltException.Create(System.SR.Xslt_WrongStylesheetElement);
            }
        }
        if (Ref.Equal(input.NamespaceURI, input.Atoms.UriXsl))
        {
            if (!Ref.Equal(input.LocalName, input.Atoms.Stylesheet) && !Ref.Equal(input.LocalName, input.Atoms.Transform))
            {
                throw XsltException.Create(System.SR.Xslt_WrongStylesheetElement);
            }
            compiler.PushNamespaceScope();
            CompileStylesheetAttributes(compiler);
            CompileTopLevelElements(compiler);
            if (!inInclude)
            {
                CompileImports(compiler);
            }
        }
        else
        {
            compiler.PushLiteralScope();
            CompileSingleTemplate(compiler);
        }
        compiler.PopScope();
    }
References System.Xml.Xsl.XsltOld.ContainerAction.CompileImports(), System.Xml.Xsl.XsltOld.ContainerAction.CompileSingleTemplate(), System.Xml.Xsl.XsltOld.ContainerAction.CompileStylesheetAttributes(), System.Xml.Xsl.XsltOld.ContainerAction.CompileTopLevelElements(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.input, and System.SR.Xslt_WrongStylesheetElement.
Referenced by System.Xml.Xsl.XsltOld.RootAction.Compile(), System.Xml.Xsl.XsltOld.ContainerAction.CompileImport(), and System.Xml.Xsl.XsltOld.ContainerAction.CompileInclude().