Terraria: System.Xml.Xsl.XsltOld.ContainerAction.CompileKey
CompileKey()
void System.Xml.Xsl.XsltOld.ContainerAction.CompileKey (Compiler compiler) inline package inherited
Definition at line 246 of file ContainerAction.cs.
    {
        NavigatorInput input = compiler.Input;
        string localName = input.LocalName;
        int num = -1;
        int num2 = -1;
        XmlQualifiedName xmlQualifiedName = null;
        if (input.MoveToFirstAttribute())
        {
            do
            {
                string namespaceURI = input.NamespaceURI;
                string localName2 = input.LocalName;
                string value = input.Value;
                if (namespaceURI.Length == 0)
                {
                    if (Ref.Equal(localName2, input.Atoms.Name))
                    {
                        xmlQualifiedName = compiler.CreateXPathQName(value);
                    }
                    else if (Ref.Equal(localName2, input.Atoms.Match))
                    {
                        num = compiler.AddQuery(value, allowVar: false, allowKey: false, isPattern: true);
                    }
                    else if (Ref.Equal(localName2, input.Atoms.Use))
                    {
                        num2 = compiler.AddQuery(value, allowVar: false, allowKey: false, isPattern: false);
                    }
                    else if (!compiler.ForwardCompatibility)
                    {
                        throw XsltException.Create(System.SR.Xslt_InvalidAttribute, localName2, localName);
                    }
                }
            }
            while (input.MoveToNextAttribute());
            input.ToParent();
        }
        CheckRequiredAttribute(compiler, num != -1, "match");
        CheckRequiredAttribute(compiler, num2 != -1, "use");
        CheckRequiredAttribute(compiler, xmlQualifiedName != null, "name");
        compiler.InsertKey(xmlQualifiedName, num, num2);
    }
References System.Xml.Xsl.XsltOld.CompiledAction.CheckRequiredAttribute(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.input, System.Xml.Xsl.XsltOld.NavigatorInput.LocalName, System.value, and System.SR.Xslt_InvalidAttribute.
Referenced by System.Xml.Xsl.XsltOld.ContainerAction.CompileTopLevelElements().