Terraria: System.Xml.Xsl.XsltOld.ContainerAction.CompileInstruction
CompileInstruction()
void System.Xml.Xsl.XsltOld.ContainerAction.CompileInstruction (Compiler compiler) inline private inherited
Definition at line 571 of file ContainerAction.cs.
    {
        NavigatorInput input = compiler.Input;
        CompiledAction compiledAction = null;
        string localName = input.LocalName;
        if (Ref.Equal(localName, input.Atoms.ApplyImports))
        {
            compiledAction = compiler.CreateApplyImportsAction();
        }
        else if (Ref.Equal(localName, input.Atoms.ApplyTemplates))
        {
            compiledAction = compiler.CreateApplyTemplatesAction();
        }
        else if (Ref.Equal(localName, input.Atoms.Attribute))
        {
            compiledAction = compiler.CreateAttributeAction();
        }
        else if (Ref.Equal(localName, input.Atoms.CallTemplate))
        {
            compiledAction = compiler.CreateCallTemplateAction();
        }
        else if (Ref.Equal(localName, input.Atoms.Choose))
        {
            compiledAction = compiler.CreateChooseAction();
        }
        else if (Ref.Equal(localName, input.Atoms.Comment))
        {
            compiledAction = compiler.CreateCommentAction();
        }
        else if (Ref.Equal(localName, input.Atoms.Copy))
        {
            compiledAction = compiler.CreateCopyAction();
        }
        else if (Ref.Equal(localName, input.Atoms.CopyOf))
        {
            compiledAction = compiler.CreateCopyOfAction();
        }
        else if (Ref.Equal(localName, input.Atoms.Element))
        {
            compiledAction = compiler.CreateElementAction();
        }
        else
        {
            if (Ref.Equal(localName, input.Atoms.Fallback))
            {
                return;
            }
            if (Ref.Equal(localName, input.Atoms.ForEach))
            {
                compiledAction = compiler.CreateForEachAction();
            }
            else if (Ref.Equal(localName, input.Atoms.If))
            {
                compiledAction = compiler.CreateIfAction(IfAction.ConditionType.ConditionIf);
            }
            else if (Ref.Equal(localName, input.Atoms.Message))
            {
                compiledAction = compiler.CreateMessageAction();
            }
            else if (Ref.Equal(localName, input.Atoms.Number))
            {
                compiledAction = compiler.CreateNumberAction();
            }
            else if (Ref.Equal(localName, input.Atoms.ProcessingInstruction))
            {
                compiledAction = compiler.CreateProcessingInstructionAction();
            }
            else if (Ref.Equal(localName, input.Atoms.Text))
            {
                compiledAction = compiler.CreateTextAction();
            }
            else if (Ref.Equal(localName, input.Atoms.ValueOf))
            {
                compiledAction = compiler.CreateValueOfAction();
            }
            else if (Ref.Equal(localName, input.Atoms.Variable))
            {
                compiledAction = compiler.CreateVariableAction(VariableType.LocalVariable);
            }
            else
            {
                if (!compiler.ForwardCompatibility)
                {
                    throw compiler.UnexpectedKeyword();
                }
                compiledAction = compiler.CreateNewInstructionAction();
            }
        }
        AddAction(compiledAction);
    }
References System.Xml.Xsl.XsltOld.ContainerAction.AddAction(), System.Xml.Dictionary, System.Xml.Ref.Equal(), and System.input.
Referenced by System.Xml.Xsl.XsltOld.ContainerAction.CompileOnceTemplate().