Terraria: System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget.OfferMessage
OfferMessage() [1/2]
DataflowMessageStatus ITargetBlock< T >. System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >.OfferMessage (DataflowMessageHeader messageHeader, T messageValue, ISourceBlock< T > source, bool consumeToAccept) inline private
Definition at line 314 of file JoinBlockTarget.cs.
    {
        if (!messageHeader.IsValid)
        {
            throw new ArgumentException(System.SR.Argument_InvalidMessageHeader, "messageHeader");
        }
        if (source == null && consumeToAccept)
        {
            throw new ArgumentException(System.SR.Argument_CantConsumeFromANullSource, "consumeToAccept");
        }
        lock (_sharedResources.IncomingLock)
        {
            if (_decliningPermanently || _sharedResources._decliningPermanently)
            {
                _sharedResources.CompleteBlockIfPossible();
                return DataflowMessageStatus.DecliningPermanently;
            }
            if (_sharedResources._dataflowBlockOptions.Greedy && (_sharedResources._boundingState == null || ((_sharedResources._boundingState.CountIsLessThanBound || !HasTheHighestNumberOfMessagesAvailable) && _nonGreedy.PostponedMessages.Count == 0 && _sharedResources._taskForInputProcessing == null)))
            {
                if (consumeToAccept)
                {
                    messageValue = source.ConsumeMessage(messageHeader, this, out var messageConsumed);
                    if (!messageConsumed)
                    {
                        return DataflowMessageStatus.NotAvailable;
                    }
                }
                if (_sharedResources._boundingState != null && HasTheHighestNumberOfMessagesAvailable)
                {
                    _sharedResources._boundingState.CurrentCount++;
                }
                _messages.Enqueue(messageValue);
                CompleteIfLastJoinIsFeasible();
                if (_sharedResources.AllTargetsHaveAtLeastOneMessage)
                {
                    _sharedResources._joinFilledAction();
                    _sharedResources._joinsCreated++;
                }
                _sharedResources.CompleteBlockIfPossible();
                return DataflowMessageStatus.Accepted;
            }
            if (source != null)
            {
                _nonGreedy.PostponedMessages.Push(source, messageHeader);
                _sharedResources.ProcessAsyncIfNecessary();
                return DataflowMessageStatus.Postponed;
            }
            return DataflowMessageStatus.Declined;
        }
    }
References System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._boundingState, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._dataflowBlockOptions, System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._joinFilledAction, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._joinsCreated, System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >._messages, System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >._nonGreedy, System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >._sharedResources, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._taskForInputProcessing, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.AllTargetsHaveAtLeastOneMessage, System.SR.Argument_CantConsumeFromANullSource, System.SR.Argument_InvalidMessageHeader, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.CompleteBlockIfPossible(), System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >.CompleteIfLastJoinIsFeasible(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.Tasks.Dataflow.Internal.BoundingState.CountIsLessThanBound, System.Threading.Tasks.Dataflow.Internal.BoundingState.CurrentCount, System.Threading.Tasks.Dataflow.GroupingDataflowBlockOptions.Greedy, System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >.HasTheHighestNumberOfMessagesAvailable, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.IncomingLock, System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >.NonGreedyState.PostponedMessages, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.ProcessAsyncIfNecessary(), and System.source.