Terraria: System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget.CompleteIfLastJoinIsFeasible
CompleteIfLastJoinIsFeasible()
void System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >.CompleteIfLastJoinIsFeasible () inline private
Definition at line 245 of file JoinBlockTarget.cs.
    {
        int num = (_sharedResources._dataflowBlockOptions.Greedy ? _messages.Count : (_nonGreedy.ConsumedMessage.Key ? 1 : 0));
        if (_sharedResources._joinsCreated + num < _sharedResources._dataflowBlockOptions.ActualMaxNumberOfGroups)
        {
            return;
        }
        _decliningPermanently = true;
        bool flag = true;
        JoinBlockTargetBase[] targets = _sharedResources._targets;
        foreach (JoinBlockTargetBase joinBlockTargetBase in targets)
        {
            if (!joinBlockTargetBase.IsDecliningPermanently)
            {
                flag = false;
                break;
            }
        }
        if (flag)
        {
            _sharedResources._decliningPermanently = true;
        }
    }
References System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._dataflowBlockOptions, System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._joinsCreated, System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >._sharedResources, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._targets, and System.Threading.Tasks.Dataflow.GroupingDataflowBlockOptions.ActualMaxNumberOfGroups.
Referenced by System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >.ConsumeOnePostponedMessage(), System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >.ConsumeReservedMessage(), and System.Threading.Tasks.Dataflow.Internal.JoinBlockTarget< T >.OfferMessage().