Terraria: NetLiquidModule.Serialize
Serialize()
static NetPacket NetLiquidModule.Serialize (HashSet< int > changes) inline static
     {
         NetPacket result = NetModule.CreatePacket<NetLiquidModule>(changes.Count * 6 + 2);
         result.Writer.Write((ushort)changes.Count);
         foreach (int change in changes)
         {
             int num = (change >> 16) & 0xFFFF;
             int num2 = change & 0xFFFF;
             result.Writer.Write(change);
             result.Writer.Write(Main.tile[num, num2].liquid);
             result.Writer.Write(Main.tile[num, num2].liquidType());
         }
         return result;
     }
References Tile.liquid, Tile.liquidType(), Main.tile, and NetPacket.Writer.
Referenced by BroadcastAllChanges(), and BroadcastEachChunkSeparately().