Terraria: Internal.Cryptography.TripleDesImplementation.CreateTransform
CreateTransform()
ICryptoTransform Internal.Cryptography.TripleDesImplementation.CreateTransform (byte[] rgbKey, byte[] rgbIV, bool encrypting) inline private
Definition at line 44 of file TripleDesImplementation.cs.
    {
        if (rgbKey == null)
        {
            throw new ArgumentNullException("rgbKey");
        }
        long num = (long)rgbKey.Length * 8L;
        if (num > int.MaxValue || !((int)num).IsLegalSize(LegalKeySizes))
        {
            throw new ArgumentException(System.SR.Cryptography_InvalidKeySize, "rgbKey");
        }
        if (rgbIV != null)
        {
            long num2 = (long)rgbIV.Length * 8L;
            if (num2 != BlockSize)
            {
                throw new ArgumentException(System.SR.Cryptography_InvalidIVSize, "rgbIV");
            }
        }
        if (rgbKey.Length == 16)
        {
            byte[] array = new byte[24];
            Array.Copy(rgbKey, array, 16);
            Array.Copy(rgbKey, 0, array, 16, 8);
            rgbKey = array;
        }
        if (Mode == CipherMode.CFB)
        {
            ValidateCFBFeedbackSize(FeedbackSize);
        }
        return CreateTransformCore(Mode, Padding, rgbKey, rgbIV, BlockSize / 8, this.GetPaddingSize(Mode, FeedbackSize), FeedbackSize / 8, encrypting);
    }
References System.array, System.Security.Cryptography.SymmetricAlgorithm.BlockSize, System.Array.Copy(), Internal.Cryptography.TripleDesImplementation.CreateTransformCore(), System.SR.Cryptography_InvalidIVSize, System.SR.Cryptography_InvalidKeySize, System.Security.Cryptography.SymmetricAlgorithm.FeedbackSize, System.L, System.Security.Cryptography.SymmetricAlgorithm.LegalKeySizes, System.Security.Cryptography.SymmetricAlgorithm.Padding, and Internal.Cryptography.TripleDesImplementation.ValidateCFBFeedbackSize().
Referenced by Internal.Cryptography.TripleDesImplementation.CreateDecryptor(), Internal.Cryptography.TripleDesImplementation.CreateDecryptor(), Internal.Cryptography.TripleDesImplementation.CreateEncryptor(), and Internal.Cryptography.TripleDesImplementation.CreateEncryptor().