Terraria: Internal.Cryptography.TripleDesImplementation.CreateTransformCore
CreateTransformCore()
static UniversalCryptoTransform Internal.Cryptography.TripleDesImplementation.CreateTransformCore (CipherMode cipherMode, PaddingMode paddingMode, byte[] key, byte[] iv, int blockSize, int paddingSize, int feedbackSize, bool encrypting) inline static private
Definition at line 141 of file TripleDesImplementation.cs.
    {
        SafeAlgorithmHandle sharedHandle = TripleDesBCryptModes.GetSharedHandle(cipherMode, feedbackSize);
        BasicSymmetricCipher cipher = new BasicSymmetricCipherBCrypt(sharedHandle, cipherMode, blockSize, paddingSize, key, ownsParentHandle: false, iv, encrypting);
        return UniversalCryptoTransform.Create(paddingMode, cipher, encrypting);
    }
References Internal.Cryptography.UniversalCryptoTransform.Create(), Internal.Cryptography.TripleDesBCryptModes.GetSharedHandle(), and System.key.
Referenced by Internal.Cryptography.TripleDesImplementation.CreateTransform(), Internal.Cryptography.TripleDesImplementation.TryDecryptCbcCore(), Internal.Cryptography.TripleDesImplementation.TryDecryptCfbCore(), Internal.Cryptography.TripleDesImplementation.TryDecryptEcbCore(), Internal.Cryptography.TripleDesImplementation.TryEncryptCbcCore(), Internal.Cryptography.TripleDesImplementation.TryEncryptCfbCore(), and Internal.Cryptography.TripleDesImplementation.TryEncryptEcbCore().