Terraria: Internal.Cryptography.TripleDesImplementation.ValidateCFBFeedbackSize
ValidateCFBFeedbackSize()
static void Internal.Cryptography.TripleDesImplementation.ValidateCFBFeedbackSize (int feedback) inline static private
Definition at line 133 of file TripleDesImplementation.cs.
    {
        if (feedback != 8 && feedback != 64)
        {
            throw new CryptographicException(string.Format(System.SR.Cryptography_CipherModeFeedbackNotSupported, feedback, CipherMode.CFB));
        }
    }
References System.SR.Cryptography_CipherModeFeedbackNotSupported, and System.Format.
Referenced by Internal.Cryptography.TripleDesImplementation.CreateTransform(), Internal.Cryptography.TripleDesImplementation.TryDecryptCfbCore(), and Internal.Cryptography.TripleDesImplementation.TryEncryptCfbCore().