Terraria: System.Diagnostics.TextWriterTraceListener.EnsureWriter
EnsureWriter()
void System.Diagnostics.TextWriterTraceListener.EnsureWriter () inline package inherited
Definition at line 160 of file TextWriterTraceListener.cs.
    {
        if (_writer != null)
        {
            return;
        }
        bool flag = false;
        if (_fileName == null)
        {
            return;
        }
        Encoding encodingWithFallback = GetEncodingWithFallback(new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        string path = Path.GetFullPath(_fileName);
        string directoryName = Path.GetDirectoryName(path);
        string text = Path.GetFileName(path);
        for (int i = 0; i < 2; i++)
        {
            try
            {
                _writer = new StreamWriter(path, append: true, encodingWithFallback, 4096);
                flag = true;
            }
            catch (IOException)
            {
                text = $"{Guid.NewGuid()}{text}";
                path = Path.Combine(directoryName, text);
                continue;
            }
            catch (UnauthorizedAccessException)
            {
            }
            catch (Exception)
            {
            }
            break;
        }
        if (!flag)
        {
            _fileName = null;
        }
    }
References System.Diagnostics.TextWriterTraceListener._fileName, System.Diagnostics.TextWriterTraceListener._writer, System.IO.Path.Combine(), System.IO.Path.GetDirectoryName(), System.Diagnostics.TextWriterTraceListener.GetEncodingWithFallback(), System.IO.Path.GetFileName(), System.IO.Path.GetFullPath(), and System.text.
Referenced by System.Diagnostics.TextWriterTraceListener.Flush(), System.Diagnostics.XmlWriterTraceListener.InternalWrite(), System.Diagnostics.TextWriterTraceListener.Write(), and System.Diagnostics.TextWriterTraceListener.WriteLine().