Terraria: Terraria.GameContent.UI.Elements.UISearchBar.TrimDisplayIfOverElementDimensions
TrimDisplayIfOverElementDimensions()
void Terraria.GameContent.UI.Elements.UISearchBar.TrimDisplayIfOverElementDimensions (int padding) inline
Definition at line 81 of file UISearchBar.cs.
    {
        CalculatedStyle dimensions = GetDimensions();
        if (dimensions.Width != 0f || dimensions.Height != 0f)
        {
            Point point = new Point((int)dimensions.X, (int)dimensions.Y);
            Point point2 = new Point(point.X + (int)dimensions.Width, point.Y + (int)dimensions.Height);
            Rectangle rectangle = new Rectangle(point.X, point.Y, point2.X - point.X, point2.Y - point.Y);
            CalculatedStyle dimensions2 = _text.GetDimensions();
            Point point3 = new Point((int)dimensions2.X, (int)dimensions2.Y);
            Point point4 = new Point(point3.X + (int)_text.MinWidth.Pixels, point3.Y + (int)_text.MinHeight.Pixels);
            Rectangle rectangle2 = new Rectangle(point3.X, point3.Y, point4.X - point3.X, point4.Y - point3.Y);
            int num = 0;
            while (rectangle2.Right > rectangle.Right - padding && _text.Text.Length > 0)
            {
                _text.SetText(_text.Text.Substring(0, _text.Text.Length - 1));
                num++;
                RecalculateChildren();
                dimensions2 = _text.GetDimensions();
                point3 = new Point((int)dimensions2.X, (int)dimensions2.Y);
                point4 = new Point(point3.X + (int)_text.MinWidth.Pixels, point3.Y + (int)_text.MinHeight.Pixels);
                rectangle2 = new Rectangle(point3.X, point3.Y, point4.X - point3.X, point4.Y - point3.Y);
                actualContents = _text.Text;
            }
        }
    }
References Terraria.GameContent.UI.Elements.UISearchBar._text, Terraria.GameContent.UI.Elements.UISearchBar.actualContents, Terraria.UI.UIElement.GetDimensions(), Terraria.UI.CalculatedStyle.Height, Terraria.UI.UIElement.RecalculateChildren(), Terraria.GameContent.UI.Elements.UITextBox.SetText(), Terraria.GameContent.UI.Elements.UITextPanel< T >.Text, Terraria.UI.CalculatedStyle.Width, Terraria.UI.CalculatedStyle.X, and Terraria.UI.CalculatedStyle.Y.
Referenced by Terraria.GameContent.UI.Elements.UISearchBar.SetContents().