Terraria: ARenderTargetContentByRequest.PrepareARenderTarget_AndListenToEvents
PrepareARenderTarget_AndListenToEvents()
void ARenderTargetContentByRequest.PrepareARenderTarget_AndListenToEvents (ref RenderTarget2D target, GraphicsDevice device, int neededWidth, int neededHeight, RenderTargetUsage usage) inline protected inherited
     {
         if (target == null || target.IsDisposed || target.Width != neededWidth || target.Height != neededHeight)
         {
             if (target != null)
             {
                 target.ContentLost -= target_ContentLost;
                 target.Disposing -= target_Disposing;
             }
             target = new RenderTarget2D(device, neededWidth, neededHeight, mipMap: false, device.PresentationParameters.BackBufferFormat, DepthFormat.None, 0, usage);
             target.ContentLost += target_ContentLost;
             target.Disposing += target_Disposing;
         }
     }
References ARenderTargetContentByRequest.target_ContentLost(), and ARenderTargetContentByRequest.target_Disposing().
Referenced by AnOutlinedDrawRenderTargetContent.HandleUseReqest(), PlayerQueenSlimeMountTextureContent.HandleUseReqest(), PlayerRainbowWingsTextureContent.HandleUseReqest(), and HandleUseReqest().