Terraria: System.Reflection.CustomAttribute.AddCustomAttributes
AddCustomAttributes()
static unsafe void System.Reflection.CustomAttribute.AddCustomAttributes (ref RuntimeType::ListBuilder< object > attributes, RuntimeModule decoratedModule, int decoratedMetadataToken, RuntimeType attributeFilterType, bool mustBeInheritable, RuntimeType::ListBuilder< object > derivedAttributes) inline static private
Definition at line 300 of file CustomAttribute.cs.
    {
        CustomAttributeRecord[] customAttributeRecords = RuntimeCustomAttributeData.GetCustomAttributeRecords(decoratedModule, decoratedMetadataToken);
        if ((object)attributeFilterType == null && customAttributeRecords.Length == 0)
        {
            return;
        }
        MetadataImport scope = decoratedModule.MetadataImport;
        for (int i = 0; i < customAttributeRecords.Length; i++)
        {
            ref CustomAttributeRecord reference = ref customAttributeRecords[i];
            IntPtr blob = reference.blob.Signature;
            IntPtr intPtr = (IntPtr)((byte*)(void*)blob + reference.blob.Length);
            if (!FilterCustomAttributeRecord(reference.tkCtor, in scope, decoratedModule, decoratedMetadataToken, attributeFilterType, mustBeInheritable, ref derivedAttributes, out var attributeType, out var ctorWithParameters, out var isVarArg))
            {
                continue;
            }
            RuntimeConstructorInfo.CheckCanCreateInstance(attributeType, isVarArg);
            object obj;
            int namedArgs;
            if (ctorWithParameters != null)
            {
                obj = CreateCaObject(decoratedModule, attributeType, ctorWithParameters, ref blob, intPtr, out namedArgs);
            }
            else
            {
                obj = attributeType.CreateInstanceDefaultCtor(publicOnly: false, wrapExceptions: false);
                if ((int)((byte*)(void*)intPtr - (byte*)(void*)blob) == 0)
                {
                    namedArgs = 0;
                }
                else
                {
                    int num = Unsafe.ReadUnaligned<int>((void*)blob);
                    if ((num & 0xFFFF) != 1)
                    {
                        throw new CustomAttributeFormatException();
                    }
                    namedArgs = num >> 16;
                    blob = (IntPtr)((byte*)(void*)blob + 4);
                }
            }
            for (int j = 0; j < namedArgs; j++)
            {
                GetPropertyOrFieldData(decoratedModule, ref blob, intPtr, out var name, out var isProperty, out var type, out var value);
                try
                {
                    if (isProperty)
                    {
                        if ((object)type == null && value != null)
{
                            type = (RuntimeType)value.GetType();
                            if (type == Type_RuntimeType)
{
                                type = Type_Type;
                            }
                        }
                        PropertyInfo propertyInfo = (((object)type == null) ? attributeType.GetProperty(name) : attributeType.GetProperty(name, type, Type.EmptyTypes));
                        if ((object)propertyInfo == null)
{
                            throw new CustomAttributeFormatException(SR.Format(SR.RFLCT_InvalidPropFail, name));
                        }
                        MethodInfo setMethod = propertyInfo.GetSetMethod(nonPublic: true);
                        if (setMethod.IsPublic)
{
                            setMethod.Invoke(obj, BindingFlags.Default, null, new object[1] { value }, null);
                        }
                    }
                    else
                    {
                        FieldInfo field = attributeType.GetField(name);
                        field.SetValue(obj, value, BindingFlags.Default, Type.DefaultBinder, null);
                    }
                }
                catch (Exception inner)
                {
                    throw new CustomAttributeFormatException(SR.Format(isProperty ? SR.RFLCT_InvalidPropFail : SR.RFLCT_InvalidFieldFail, name), inner);
                }
            }
            if (blob != intPtr)
            {
                throw new CustomAttributeFormatException();
            }
            attributes.Add(obj);
        }
    }
References System.Reflection.RuntimeConstructorInfo.CheckCanCreateInstance(), System.Reflection.CustomAttribute.CreateCaObject(), System.Type.DefaultBinder, System.Type.EmptyTypes, System.Reflection.CustomAttribute.FilterCustomAttributeRecord(), System.SR.Format(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributeRecords(), System.Reflection.CustomAttribute.GetPropertyOrFieldData(), System.Reflection.PropertyInfo.GetSetMethod(), System.Reflection.MethodBase.Invoke(), System.Reflection.MethodBase.IsPublic, System.Reflection.RuntimeModule.MetadataImport, System.obj, System.SR.RFLCT_InvalidFieldFail, System.SR.RFLCT_InvalidPropFail, System.Reflection.FieldInfo.SetValue(), System.type, System.Reflection.CustomAttribute.Type_RuntimeType, System.Reflection.CustomAttribute.Type_Type, and System.value.
Referenced by System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), and System.Reflection.CustomAttribute.GetCustomAttributes().