Terraria: System.Reflection.CustomAttribute.IsCustomAttributeDefined
IsCustomAttributeDefined() [2/2]
static bool System.Reflection.CustomAttribute.IsCustomAttributeDefined (RuntimeModule decoratedModule, int decoratedMetadataToken, RuntimeType attributeFilterType, int attributeCtorToken, bool mustBeInheritable) inline static private
Definition at line 251 of file CustomAttribute.cs.
    {
        MetadataImport scope = decoratedModule.MetadataImport;
        scope.EnumCustomAttributes(decoratedMetadataToken, out var result);
        if (result.Length == 0)
        {
            return false;
        }
        CustomAttributeRecord customAttributeRecord = default(CustomAttributeRecord);
        if ((object)attributeFilterType != null)
        {
            RuntimeType.ListBuilder<object> derivedAttributes = default(RuntimeType.ListBuilder<object>);
            for (int i = 0; i < result.Length; i++)
            {
                scope.GetCustomAttributeProps(result[i], out customAttributeRecord.tkCtor.Value, out customAttributeRecord.blob);
                if (FilterCustomAttributeRecord(customAttributeRecord.tkCtor, in scope, decoratedModule, decoratedMetadataToken, attributeFilterType, mustBeInheritable, ref derivedAttributes, out var _, out var _, out var _))
                {
                    return true;
                }
            }
        }
        else
        {
            for (int j = 0; j < result.Length; j++)
            {
                scope.GetCustomAttributeProps(result[j], out customAttributeRecord.tkCtor.Value, out customAttributeRecord.blob);
                if ((int)customAttributeRecord.tkCtor == attributeCtorToken)
                {
                    return true;
                }
            }
        }
        return false;
    }
References System.Reflection.CustomAttributeRecord.blob, System.Reflection.MetadataImport.EnumCustomAttributes(), System.Reflection.CustomAttribute.FilterCustomAttributeRecord(), System.Reflection.MetadataImport.GetCustomAttributeProps(), System.Reflection.RuntimeModule.MetadataImport, System.Reflection.CustomAttributeRecord.tkCtor, and System.Reflection.MetadataToken.Value.