Terraria: System.Reflection.CustomAttribute.CreateAttributeArrayHelper
CreateAttributeArrayHelper()
static object[] System.Reflection.CustomAttribute.CreateAttributeArrayHelper (RuntimeType elementType, int elementCount) inline static private
Definition at line 533 of file CustomAttribute.cs.
    {
        if (elementCount == 0)
        {
            return elementType.GetEmptyArray();
        }
        return (object[])Array.CreateInstance(elementType, elementCount);
    }
References System.Array.CreateInstance(), and System.elementType.
Referenced by System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), and System.Reflection.CustomAttribute.GetCustomAttributes().