Terraria: System.Reflection.CustomAttribute.GetAttributeUsage
GetAttributeUsage()
static AttributeUsageAttribute System.Reflection.CustomAttribute.GetAttributeUsage (RuntimeType decoratedAttribute) inline static package
Definition at line 477 of file CustomAttribute.cs.
    {
        RuntimeModule runtimeModule = decoratedAttribute.GetRuntimeModule();
        MetadataImport metadataImport = runtimeModule.MetadataImport;
        CustomAttributeRecord[] customAttributeRecords = RuntimeCustomAttributeData.GetCustomAttributeRecords(runtimeModule, decoratedAttribute.MetadataToken);
        AttributeUsageAttribute attributeUsageAttribute = null;
        for (int i = 0; i < customAttributeRecords.Length; i++)
        {
            ref CustomAttributeRecord reference = ref customAttributeRecords[i];
            RuntimeType runtimeType = runtimeModule.ResolveType(metadataImport.GetParentToken(reference.tkCtor), null, null) as RuntimeType;
            if (!(runtimeType != (RuntimeType)typeof(AttributeUsageAttribute)))
            {
                if (attributeUsageAttribute != null)
                {
                    throw new FormatException(SR.Format(SR.Format_AttributeUsage, runtimeType));
                }
                ParseAttributeUsageAttribute(reference.blob, out var targets, out var inherited, out var allowMultiple);
                attributeUsageAttribute = new AttributeUsageAttribute(targets, allowMultiple, inherited);
            }
        }
        return attributeUsageAttribute ?? AttributeUsageAttribute.Default;
    }
References System.AttributeUsageAttribute.Default, System.SR.Format(), System.SR.Format_AttributeUsage, System.Reflection.RuntimeCustomAttributeData.GetCustomAttributeRecords(), System.Reflection.MetadataImport.GetParentToken(), System.RuntimeType.GetRuntimeModule(), System.Reflection.RuntimeModule.MetadataImport, System.RuntimeType.MetadataToken, and System.Reflection.RuntimeModule.ResolveType().
Referenced by System.Reflection.CustomAttribute.GetCustomAttributes(), and System.Reflection.CustomAttribute.GetCustomAttributes().