Terraria: System.Reflection.CustomAttribute.IsDefined
IsDefined() [1/9]
static bool System.Reflection.CustomAttribute.IsDefined (RuntimeAssembly assembly, RuntimeType caType) inline static package
Definition at line 102 of file CustomAttribute.cs.
    {
        return IsCustomAttributeDefined(assembly.ManifestModule as RuntimeModule, RuntimeAssembly.GetToken(assembly.GetNativeHandle()), caType);
    }
References System.Reflection.RuntimeAssembly.GetNativeHandle(), System.Reflection.RuntimeAssembly.GetToken(), System.Reflection.CustomAttribute.IsCustomAttributeDefined(), and System.Reflection.RuntimeAssembly.ManifestModule.