Terraria: System.Reflection.CustomAttribute.IsDefined
IsDefined() [9/9]
static bool System.Reflection.CustomAttribute.IsDefined (RuntimeType type, RuntimeType caType, bool inherit) inline static package
Definition at line 13 of file CustomAttribute.cs.
    {
        if ((object)type.GetElementType() != null)
        {
            return false;
        }
        if (PseudoCustomAttribute.IsDefined(type, caType))
        {
            return true;
        }
        if (IsCustomAttributeDefined(type.GetRuntimeModule(), type.MetadataToken, caType))
        {
            return true;
        }
        if (!inherit)
        {
            return false;
        }
        type = type.BaseType as RuntimeType;
        while ((object)type != null)
        {
            if (IsCustomAttributeDefined(type.GetRuntimeModule(), type.MetadataToken, caType, 0, inherit))
            {
                return true;
            }
            type = type.BaseType as RuntimeType;
        }
        return false;
    }
References System.Reflection.CustomAttribute.IsCustomAttributeDefined(), System.Reflection.PseudoCustomAttribute.IsDefined(), and System.type.
Referenced by System.Reflection.Emit.TypeBuilder.IsDefined(), System.Reflection.RuntimeAssembly.IsDefined(), System.Reflection.RuntimeConstructorInfo.IsDefined(), System.Reflection.RuntimeEventInfo.IsDefined(), System.Reflection.RuntimeFieldInfo.IsDefined(), System.Reflection.RuntimeMethodInfo.IsDefined(), System.Reflection.RuntimeModule.IsDefined(), System.Reflection.RuntimeParameterInfo.IsDefined(), System.Reflection.RuntimePropertyInfo.IsDefined(), and System.RuntimeType.IsDefined().