Terraria: System.Reflection.CustomAttribute.IsDefined
IsDefined() [7/9]
static bool System.Reflection.CustomAttribute.IsDefined (RuntimeParameterInfo parameter, RuntimeType caType) inline static package
Definition at line 93 of file CustomAttribute.cs.
    {
        if (PseudoCustomAttribute.IsDefined(parameter, caType))
        {
            return true;
        }
        return IsCustomAttributeDefined(parameter.GetRuntimeModule(), parameter.MetadataToken, caType);
    }
References System.Reflection.RuntimeParameterInfo.GetRuntimeModule(), System.Reflection.CustomAttribute.IsCustomAttributeDefined(), System.Reflection.PseudoCustomAttribute.IsDefined(), and System.Reflection.RuntimeParameterInfo.MetadataToken.