Terraria: System.ComponentModel.DataAnnotations.Validator.GetPropertyValues
GetPropertyValues()
static ICollection< KeyValuePair< ValidationContext, object > > System.ComponentModel.DataAnnotations.Validator.GetPropertyValues (object instance, ValidationContext validationContext) inline static private
Definition at line 244 of file Validator.cs.
    {
        PropertyDescriptorCollection properties = TypeDescriptor.GetProperties(instance);
        List<KeyValuePair<ValidationContext, object>> list = new List<KeyValuePair<ValidationContext, object>>(properties.Count);
        foreach (PropertyDescriptor item in properties)
        {
            ValidationContext validationContext2 = CreateValidationContext(instance, validationContext);
            validationContext2.MemberName = item.Name;
            if (_store.GetPropertyValidationAttributes(validationContext2).Any())
            {
                list.Add(new KeyValuePair<ValidationContext, object>(validationContext2, item.GetValue(instance)));
            }
        }
        return list;
    }
References System.ComponentModel.DataAnnotations.Validator._store, System.ComponentModel.PropertyDescriptorCollection.Count, System.ComponentModel.DataAnnotations.Validator.CreateValidationContext(), System.ComponentModel.TypeDescriptor.GetProperties(), System.item, and System.list.
Referenced by System.ComponentModel.DataAnnotations.Validator.GetObjectPropertyValidationErrors().