Terraria: System.Reflection.CustomAttribute.GetCustomAttributes
GetCustomAttributes() [5/10]
static object[] System.Reflection.CustomAttribute.GetCustomAttributes (RuntimeMethodInfo method, RuntimeType caType, bool inherit) inline static package
Definition at line 158 of file CustomAttribute.cs.
    {
        if (method.IsGenericMethod && !method.IsGenericMethodDefinition)
        {
            method = method.GetGenericMethodDefinition() as RuntimeMethodInfo;
        }
        RuntimeType.ListBuilder<Attribute> pcas = default(RuntimeType.ListBuilder<Attribute>);
        PseudoCustomAttribute.GetCustomAttributes(method, caType, ref pcas);
        if (!inherit || (caType.IsSealed && !GetAttributeUsage(caType).Inherited))
        {
            object[] customAttributes = GetCustomAttributes(method.GetRuntimeModule(), method.MetadataToken, pcas.Count, caType);
            if (pcas.Count > 0)
            {
                pcas.CopyTo(customAttributes, customAttributes.Length - pcas.Count);
            }
            return customAttributes;
        }
        RuntimeType.ListBuilder<object> attributes = default(RuntimeType.ListBuilder<object>);
        bool mustBeInheritable = false;
        RuntimeType elementType = ((caType.IsValueType || caType.ContainsGenericParameters) ? ((RuntimeType)typeof(object)) : caType);
        for (int i = 0; i < pcas.Count; i++)
        {
            attributes.Add(pcas[i]);
        }
        while (method != null)
        {
            AddCustomAttributes(ref attributes, method.GetRuntimeModule(), method.MetadataToken, caType, mustBeInheritable, attributes);
            mustBeInheritable = true;
            method = method.GetParentDefinition();
        }
        object[] array = CreateAttributeArrayHelper(elementType, attributes.Count);
        for (int j = 0; j < attributes.Count; j++)
        {
            array[j] = attributes[j];
        }
        return array;
    }
References System.Reflection.CustomAttribute.AddCustomAttributes(), System.array, System.RuntimeType.ContainsGenericParameters, System.Reflection.CustomAttribute.CreateAttributeArrayHelper(), System.elementType, System.Reflection.CustomAttribute.GetAttributeUsage(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.PseudoCustomAttribute.GetCustomAttributes(), System.Reflection.RuntimeMethodInfo.GetGenericMethodDefinition(), System.Reflection.RuntimeMethodInfo.GetParentDefinition(), System.Reflection.RuntimeMethodInfo.GetRuntimeModule(), System.Reflection.RuntimeMethodInfo.IsGenericMethod, System.Reflection.RuntimeMethodInfo.IsGenericMethodDefinition, System.Type.IsSealed, and System.Reflection.RuntimeMethodInfo.MetadataToken.