Terraria: System.Reflection.CustomAttribute.GetCustomAttributes
GetCustomAttributes() [10/10]
static object[] System.Reflection.CustomAttribute.GetCustomAttributes (RuntimeType type, RuntimeType caType, bool inherit) inline static package
Definition at line 112 of file CustomAttribute.cs.
    {
        if ((object)type.GetElementType() != null)
        {
            if (!caType.IsValueType)
            {
                return CreateAttributeArrayHelper(caType, 0);
            }
            return Array.Empty<object>();
        }
        if (type.IsGenericType && !type.IsGenericTypeDefinition)
        {
            type = type.GetGenericTypeDefinition() as RuntimeType;
        }
        RuntimeType.ListBuilder<Attribute> pcas = default(RuntimeType.ListBuilder<Attribute>);
        PseudoCustomAttribute.GetCustomAttributes(type, caType, ref pcas);
        if (!inherit || (caType.IsSealed && !GetAttributeUsage(caType).Inherited))
        {
            object[] customAttributes = GetCustomAttributes(type.GetRuntimeModule(), type.MetadataToken, pcas.Count, caType);
            if (pcas.Count > 0)
            {
                pcas.CopyTo(customAttributes, customAttributes.Length - pcas.Count);
            }
            return customAttributes;
        }
        RuntimeType.ListBuilder<object> attributes = default(RuntimeType.ListBuilder<object>);
        bool mustBeInheritable = false;
        RuntimeType elementType = ((caType.IsValueType || caType.ContainsGenericParameters) ? ((RuntimeType)typeof(object)) : caType);
        for (int i = 0; i < pcas.Count; i++)
        {
            attributes.Add(pcas[i]);
        }
        while (type != (RuntimeType)typeof(object) && type != null)
        {
            AddCustomAttributes(ref attributes, type.GetRuntimeModule(), type.MetadataToken, caType, mustBeInheritable, attributes);
            mustBeInheritable = true;
            type = type.BaseType as RuntimeType;
        }
        object[] array = CreateAttributeArrayHelper(elementType, attributes.Count);
        for (int j = 0; j < attributes.Count; j++)
        {
            array[j] = attributes[j];
        }
        return array;
    }
References System.Reflection.CustomAttribute.AddCustomAttributes(), System.array, System.RuntimeType.ContainsGenericParameters, System.Reflection.CustomAttribute.CreateAttributeArrayHelper(), System.elementType, System.Reflection.CustomAttribute.GetAttributeUsage(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.PseudoCustomAttribute.GetCustomAttributes(), System.Type.IsSealed, System.Type.IsValueType, and System.type.
Referenced by System.Reflection.Emit.TypeBuilder.GetCustomAttributes(), System.Reflection.RuntimeAssembly.GetCustomAttributes(), System.Reflection.RuntimeConstructorInfo.GetCustomAttributes(), System.Reflection.RuntimeEventInfo.GetCustomAttributes(), System.Reflection.RuntimeFieldInfo.GetCustomAttributes(), System.Reflection.RuntimeMethodInfo.GetCustomAttributes(), System.Reflection.RuntimeModule.GetCustomAttributes(), System.Reflection.RuntimeParameterInfo.GetCustomAttributes(), System.Reflection.RuntimePropertyInfo.GetCustomAttributes(), System.RuntimeType.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.Emit.TypeBuilder.GetCustomAttributes(), System.Reflection.RuntimeAssembly.GetCustomAttributes(), System.Reflection.RuntimeConstructorInfo.GetCustomAttributes(), System.Reflection.RuntimeEventInfo.GetCustomAttributes(), System.Reflection.RuntimeFieldInfo.GetCustomAttributes(), System.Reflection.RuntimeMethodInfo.GetCustomAttributes(), System.Reflection.RuntimeModule.GetCustomAttributes(), System.Reflection.RuntimeParameterInfo.GetCustomAttributes(), System.Reflection.RuntimePropertyInfo.GetCustomAttributes(), and System.RuntimeType.GetCustomAttributes().