Terraria: System.ComponentModel.DataAnnotations.Validator.GetObjectValidationErrors
GetObjectValidationErrors()
static List< ValidationError > System.ComponentModel.DataAnnotations.Validator.GetObjectValidationErrors (object instance, ValidationContext validationContext, bool validateAllProperties, bool breakOnFirstError) inline static private
Definition at line 173 of file Validator.cs.
    {
        if (validationContext == null)
        {
            throw new ArgumentNullException("validationContext");
        }
        List<ValidationError> list = new List<ValidationError>();
        list.AddRange(GetObjectPropertyValidationErrors(instance, validationContext, validateAllProperties, breakOnFirstError));
        if (list.Count > 0)
        {
            return list;
        }
        IEnumerable<ValidationAttribute> typeValidationAttributes = _store.GetTypeValidationAttributes(validationContext);
        list.AddRange(GetValidationErrors(instance, validationContext, typeValidationAttributes, breakOnFirstError));
        if (list.Count > 0)
        {
            return list;
        }
        if (instance is IValidatableObject validatableObject)
        {
            IEnumerable<ValidationResult> enumerable = validatableObject.Validate(validationContext);
            if (enumerable != null)
            {
                foreach (ValidationResult item in enumerable)
                {
                    if (item != ValidationResult.Success)
                    {
                        list.Add(new ValidationError(null, instance, item));
                    }
                }
            }
        }
        return list;
    }
References System.ComponentModel.DataAnnotations.Validator._store, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.enumerable, System.ComponentModel.DataAnnotations.Validator.GetObjectPropertyValidationErrors(), System.ComponentModel.DataAnnotations.Validator.GetValidationErrors(), System.item, System.list, and System.ComponentModel.DataAnnotations.ValidationResult.Success.
Referenced by System.ComponentModel.DataAnnotations.Validator.TryValidateObject(), and System.ComponentModel.DataAnnotations.Validator.ValidateObject().