Terraria: System.ComponentModel.DataAnnotations.Validator.GetValidationErrors
GetValidationErrors()
static List< ValidationError > System.ComponentModel.DataAnnotations.Validator.GetValidationErrors (object value, ValidationContext validationContext, IEnumerable< ValidationAttribute > attributes, bool breakOnFirstError) inline static private
Definition at line 260 of file Validator.cs.
    {
        if (validationContext == null)
        {
            throw new ArgumentNullException("validationContext");
        }
        List<ValidationError> list = new List<ValidationError>();
        RequiredAttribute requiredAttribute = null;
        ValidationError validationError;
        foreach (ValidationAttribute attribute in attributes)
        {
            requiredAttribute = attribute as RequiredAttribute;
            if (requiredAttribute != null)
            {
                if (!TryValidate(value, validationContext, requiredAttribute, out validationError))
                {
                    list.Add(validationError);
                    return list;
                }
                break;
            }
        }
        foreach (ValidationAttribute attribute2 in attributes)
        {
            if (attribute2 != requiredAttribute && !TryValidate(value, validationContext, attribute2, out validationError))
            {
                list.Add(validationError);
                if (breakOnFirstError)
                {
                    break;
                }
            }
        }
        return list;
    }
References System.list, System.ComponentModel.DataAnnotations.Validator.TryValidate(), and System.value.
Referenced by System.ComponentModel.DataAnnotations.Validator.GetObjectPropertyValidationErrors(), System.ComponentModel.DataAnnotations.Validator.GetObjectValidationErrors(), System.ComponentModel.DataAnnotations.Validator.TryValidateProperty(), System.ComponentModel.DataAnnotations.Validator.TryValidateValue(), System.ComponentModel.DataAnnotations.Validator.ValidateProperty(), and System.ComponentModel.DataAnnotations.Validator.ValidateValue().