Terraria: System.Reflection.CustomAttribute.FilterCustomAttributeRecord
FilterCustomAttributeRecord()
static bool System.Reflection.CustomAttribute.FilterCustomAttributeRecord (MetadataToken caCtorToken, in MetadataImport scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, bool mustBeInheritable, ref RuntimeType::ListBuilder< object > derivedAttributes, out RuntimeType attributeType, out IRuntimeMethodInfo ctorWithParameters, out bool isVarArg) inline static private
Definition at line 388 of file CustomAttribute.cs.
    {
        ctorWithParameters = null;
        isVarArg = false;
        attributeType = decoratedModule.ResolveType(scope.GetParentToken(caCtorToken), null, null) as RuntimeType;
        if (!attributeFilterType.IsAssignableFrom(attributeType))
        {
            return false;
        }
        if (!AttributeUsageCheck(attributeType, mustBeInheritable, ref derivedAttributes))
        {
            return false;
        }
        if ((attributeType.Attributes & TypeAttributes.WindowsRuntime) == TypeAttributes.WindowsRuntime)
        {
            return false;
        }
        ConstArray methodSignature = scope.GetMethodSignature(caCtorToken);
        isVarArg = (methodSignature[0] & 5) != 0;
        if (methodSignature[1] != 0)
        {
            if (attributeType.IsGenericType)
            {
                ctorWithParameters = decoratedModule.ResolveMethod(caCtorToken, attributeType.GenericTypeArguments, null).MethodHandle.GetMethodInfo();
            }
            else
            {
                ctorWithParameters = new ModuleHandle(decoratedModule).ResolveMethodHandle(caCtorToken).GetMethodInfo();
            }
        }
        MetadataToken metadataToken = default(MetadataToken);
        if (decoratedToken.IsParamDef)
        {
            metadataToken = new MetadataToken(scope.GetParentToken(decoratedToken));
            metadataToken = new MetadataToken(scope.GetParentToken(metadataToken));
        }
        else if (decoratedToken.IsMethodDef || decoratedToken.IsProperty || decoratedToken.IsEvent || decoratedToken.IsFieldDef)
        {
            metadataToken = new MetadataToken(scope.GetParentToken(decoratedToken));
        }
        else if (decoratedToken.IsTypeDef)
        {
            metadataToken = decoratedToken;
        }
        else if (decoratedToken.IsGenericPar)
        {
            metadataToken = new MetadataToken(scope.GetParentToken(decoratedToken));
            if (metadataToken.IsMethodDef)
            {
                metadataToken = new MetadataToken(scope.GetParentToken(metadataToken));
            }
        }
        RuntimeTypeHandle rth = (metadataToken.IsTypeDef ? decoratedModule.ModuleHandle.ResolveTypeHandle(metadataToken) : default(RuntimeTypeHandle));
        RuntimeTypeHandle rth2 = attributeType.TypeHandle;
        bool result = RuntimeMethodHandle.IsCAVisibleFromDecoratedType(new QCallTypeHandle(ref rth2), (ctorWithParameters != null) ? ctorWithParameters.Value : RuntimeMethodHandleInternal.EmptyHandle, new QCallTypeHandle(ref rth), new QCallModule(ref decoratedModule)) != Interop.BOOL.FALSE;
        GC.KeepAlive(ctorWithParameters);
        return result;
    }
References System.RuntimeMethodHandleInternal.EmptyHandle, System.RuntimeMethodHandle.GetMethodInfo(), System.RuntimeType.IsAssignableFrom(), System.RuntimeMethodHandle.IsCAVisibleFromDecoratedType(), System.Reflection.MetadataToken.IsEvent, System.Reflection.MetadataToken.IsFieldDef, System.Reflection.MetadataToken.IsGenericPar, System.Reflection.MetadataToken.IsMethodDef, System.Reflection.MetadataToken.IsParamDef, System.Reflection.MetadataToken.IsProperty, System.Reflection.MetadataToken.IsTypeDef, System.GC.KeepAlive(), System.Reflection.MethodBase.MethodHandle, System.Reflection.Module.ModuleHandle, System.Reflection.RuntimeModule.ResolveMethod(), System.ModuleHandle.ResolveMethodHandle(), System.Reflection.RuntimeModule.ResolveType(), and System.ModuleHandle.ResolveTypeHandle().
Referenced by System.Reflection.CustomAttribute.AddCustomAttributes(), and System.Reflection.CustomAttribute.IsCustomAttributeDefined().