Terraria: System.Reflection.CustomAttribute.GetCustomAttributes
GetCustomAttributes() [4/10]
static object[] System.Reflection.CustomAttribute.GetCustomAttributes (RuntimeFieldInfo field, RuntimeType caType) inline static package
Definition at line 211 of file CustomAttribute.cs.
    {
        RuntimeType.ListBuilder<Attribute> pcas = default(RuntimeType.ListBuilder<Attribute>);
        PseudoCustomAttribute.GetCustomAttributes(field, caType, ref pcas);
        object[] customAttributes = GetCustomAttributes(field.GetRuntimeModule(), field.MetadataToken, pcas.Count, caType);
        if (pcas.Count > 0)
        {
            pcas.CopyTo(customAttributes, customAttributes.Length - pcas.Count);
        }
        return customAttributes;
    }
References System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.PseudoCustomAttribute.GetCustomAttributes(), System.Reflection.RuntimeFieldInfo.GetRuntimeModule(), and System.Reflection.MemberInfo.MetadataToken.