Terraria: System.Reflection.CustomAttribute.IsDefined
IsDefined() [5/9]
static bool System.Reflection.CustomAttribute.IsDefined (RuntimeMethodInfo method, RuntimeType caType, bool inherit) inline static package
Definition at line 43 of file CustomAttribute.cs.
    {
        if (PseudoCustomAttribute.IsDefined(method, caType))
        {
            return true;
        }
        if (IsCustomAttributeDefined(method.GetRuntimeModule(), method.MetadataToken, caType))
        {
            return true;
        }
        if (!inherit)
        {
            return false;
        }
        method = method.GetParentDefinition();
        while ((object)method != null)
        {
            if (IsCustomAttributeDefined(method.GetRuntimeModule(), method.MetadataToken, caType, 0, inherit))
            {
                return true;
            }
            method = method.GetParentDefinition();
        }
        return false;
    }
References System.Reflection.RuntimeMethodInfo.GetParentDefinition(), System.Reflection.RuntimeMethodInfo.GetRuntimeModule(), System.Reflection.CustomAttribute.IsCustomAttributeDefined(), System.Reflection.PseudoCustomAttribute.IsDefined(), and System.Reflection.RuntimeMethodInfo.MetadataToken.