Terraria: System.ComponentModel.DataAnnotations.Validator.GetObjectPropertyValidationErrors
GetObjectPropertyValidationErrors()
static IEnumerable< ValidationError > System.ComponentModel.DataAnnotations.Validator.GetObjectPropertyValidationErrors (object instance, ValidationContext validationContext, bool validateAllProperties, bool breakOnFirstError) inline static private
Definition at line 209 of file Validator.cs.
    {
        ICollection<KeyValuePair<ValidationContext, object>> propertyValues = GetPropertyValues(instance, validationContext);
        List<ValidationError> list = new List<ValidationError>();
        foreach (KeyValuePair<ValidationContext, object> item in propertyValues)
        {
            IEnumerable<ValidationAttribute> propertyValidationAttributes = _store.GetPropertyValidationAttributes(item.Key);
            if (validateAllProperties)
            {
                list.AddRange(GetValidationErrors(item.Value, item.Key, propertyValidationAttributes, breakOnFirstError));
            }
            else
            {
                foreach (ValidationAttribute item2 in propertyValidationAttributes)
                {
                    if (item2 is RequiredAttribute requiredAttribute)
                    {
                        ValidationResult validationResult = requiredAttribute.GetValidationResult(item.Value, item.Key);
                        if (validationResult != ValidationResult.Success)
{
                            list.Add(new ValidationError(requiredAttribute, item.Value, validationResult));
                        }
                        break;
                    }
                }
            }
            if (breakOnFirstError && list.Count > 0)
            {
                break;
            }
        }
        return list;
    }
References System.ComponentModel.DataAnnotations.Validator._store, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.ComponentModel.DataAnnotations.Validator.GetPropertyValues(), System.ComponentModel.DataAnnotations.Validator.GetValidationErrors(), System.item, System.list, and System.ComponentModel.DataAnnotations.ValidationResult.Success.
Referenced by System.ComponentModel.DataAnnotations.Validator.GetObjectValidationErrors().