Terraria: Terraria.Initializers.DyeInitializer.LoadMisc
LoadMisc()
static void Terraria.Initializers.DyeInitializer.LoadMisc () inline static private
Definition at line 417 of file DyeInitializer.cs.
    {
        Ref<Effect> pixelShaderRef = Main.PixelShaderRef;
        GameShaders.Misc["ForceField"] = new MiscShaderData(pixelShaderRef, "ForceField");
        GameShaders.Misc["WaterProcessor"] = new MiscShaderData(pixelShaderRef, "WaterProcessor");
        GameShaders.Misc["WaterDistortionObject"] = new MiscShaderData(pixelShaderRef, "WaterDistortionObject");
        GameShaders.Misc["WaterDebugDraw"] = new MiscShaderData(Main.ScreenShaderRef, "WaterDebugDraw");
        GameShaders.Misc["HallowBoss"] = new MiscShaderData(pixelShaderRef, "HallowBoss");
        GameShaders.Misc["HallowBoss"].UseImage1("Images/Extra_" + (short)156);
        GameShaders.Misc["MaskedFade"] = new MiscShaderData(pixelShaderRef, "MaskedFade");
        GameShaders.Misc["MaskedFade"].UseImage1("Images/Extra_" + (short)216);
        GameShaders.Misc["QueenSlime"] = new MiscShaderData(pixelShaderRef, "QueenSlime");
        GameShaders.Misc["QueenSlime"].UseImage1("Images/Extra_" + (short)180);
        GameShaders.Misc["QueenSlime"].UseImage2("Images/Extra_" + (short)179);
        GameShaders.Misc["StardewValleyFade"] = new MiscShaderData(pixelShaderRef, "MaskedFade").UseSamplerState(SamplerState.LinearClamp);
        GameShaders.Misc["StardewValleyFade"].UseImage1("Images/Extra_" + (short)248);
        GameShaders.Misc["RainbowTownSlime"] = new MiscShaderData(pixelShaderRef, "RainbowTownSlime");
        int type = 3530;
        bool[] array = new bool[GameShaders.Armor.GetShaderIdFromItemId(type) + 1];
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = true;
        }
        foreach (int nonColorfulDyeItem in ItemID.Sets.NonColorfulDyeItems)
        {
            array[GameShaders.Armor.GetShaderIdFromItemId(nonColorfulDyeItem)] = false;
        }
        ItemID.Sets.ColorfulDyeValues = array;
        LoadMiscVertexShaders();
    }
References Terraria.Graphics.Shaders.GameShaders.Armor, System.array, Microsoft.Xna.Framework.Graphics.SamplerState.LinearClamp, Terraria.Initializers.DyeInitializer.LoadMiscVertexShaders(), Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.ID.ItemID.Sets.NonColorfulDyeItems, Terraria.Main.PixelShaderRef, Terraria.Main.ScreenShaderRef, System.type, and Terraria.Graphics.Shaders.MiscShaderData.UseSamplerState().
Referenced by Terraria.Initializers.DyeInitializer.Load().