Terraria: System.Text.SpanRuneEnumerator.MoveNext
MoveNext()
bool System.Text.SpanRuneEnumerator.MoveNext () inline
Definition at line 22 of file SpanRuneEnumerator.cs.
    {
        if (_remaining.IsEmpty)
        {
            _current = default(Rune);
            return false;
        }
        int num = Rune.ReadFirstRuneFromUtf16Buffer(_remaining);
        if (num < 0)
        {
            num = Rune.ReplacementChar.Value;
        }
        _current = Rune.UnsafeCreate((uint)num);
        _remaining = _remaining.Slice(_current.Utf16SequenceLength);
        return true;
    }
References System.Text.SpanRuneEnumerator._current, System.Text.SpanRuneEnumerator._remaining, System.ReadOnlySpan< T >.IsEmpty, System.Text.Rune.ReadFirstRuneFromUtf16Buffer(), System.Text.Rune.ReplacementChar, System.ReadOnlySpan< T >.Slice(), System.Text.Rune.UnsafeCreate(), and System.Text.Rune.Utf16SequenceLength.
Referenced by System.UriHelper.EscapeStringToBuilder().