Terraria: System.ComponentModel.Design.ServiceContainer.AddService
AddService() [2/4]
virtual void System.ComponentModel.Design.ServiceContainer.AddService (Type serviceType, object serviceInstance, bool promote) inline virtual
Implements System.ComponentModel.Design.IServiceContainer.
Definition at line 60 of file ServiceContainer.cs.
    {
        if (promote)
        {
            IServiceContainer container = Container;
            if (container != null)
            {
                container.AddService(serviceType, serviceInstance, promote);
                return;
            }
        }
        if (serviceType == null)
        {
            throw new ArgumentNullException("serviceType");
        }
        if (serviceInstance == null)
        {
            throw new ArgumentNullException("serviceInstance");
        }
        if (!(serviceInstance is ServiceCreatorCallback) && !serviceInstance.GetType().IsCOMObject && !serviceType.IsInstanceOfType(serviceInstance))
        {
            throw new ArgumentException(System.SR.Format(System.SR.ErrorInvalidServiceInstance, serviceType.FullName));
        }
        if (Services.ContainsKey(serviceType))
        {
            throw new ArgumentException(System.SR.Format(System.SR.ErrorServiceExists, serviceType.FullName), "serviceType");
        }
        Services[serviceType] = serviceInstance;
    }
References System.ComponentModel.Design.IServiceContainer.AddService(), System.ComponentModel.Design.ServiceContainer.Container, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.SR.ErrorInvalidServiceInstance, System.SR.ErrorServiceExists, System.SR.Format(), System.ComponentModel.Design.ServiceCreatorCallback(), and System.ComponentModel.Design.ServiceContainer.Services.