Terraria: System.ComponentModel.Design.ServiceContainer.AddService
AddService() [4/4]
virtual void System.ComponentModel.Design.ServiceContainer.AddService (Type serviceType, ServiceCreatorCallback callback, bool promote) inline virtual
Implements System.ComponentModel.Design.IServiceContainer.
Definition at line 95 of file ServiceContainer.cs.
    {
        if (promote)
        {
            IServiceContainer container = Container;
            if (container != null)
            {
                container.AddService(serviceType, callback, promote);
                return;
            }
        }
        if (serviceType == null)
        {
            throw new ArgumentNullException("serviceType");
        }
        if (callback == null)
        {
            throw new ArgumentNullException("callback");
        }
        if (Services.ContainsKey(serviceType))
        {
            throw new ArgumentException(System.SR.Format(System.SR.ErrorServiceExists, serviceType.FullName), "serviceType");
        }
        Services[serviceType] = callback;
    }
References System.ComponentModel.Design.IServiceContainer.AddService(), System.ComponentModel.Design.ServiceContainer.Container, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.SR.ErrorServiceExists, System.SR.Format(), and System.ComponentModel.Design.ServiceContainer.Services.