Terraria: Utils.GetLerpValue
GetLerpValue() [2/2]
static float Utils.GetLerpValue (float from, float to, float t, bool clamped = false) inline static
     {
         if (clamped)
         {
             if (from < to)
             {
                 if (t < from)
                 {
                     return 0f;
                 }
                 if (t > to)
                 {
                     return 1f;
                 }
             }
             else
             {
                 if (t < to)
                 {
                     return 1f;
                 }
                 if (t > from)
                 {
                     return 0f;
                 }
             }
         }
         return (t - from) / (to - from);
     }
Referenced by NPC.AI(), Projectile.AI_009_MagicMissiles(), Projectile.AI_026(), NPC.AI_065_Butterflies(), Projectile.AI_067_FreakingPirates(), Projectile.AI_075(), NPC.AI_107_ImprovedWalkers(), NPC.AI_117_BloodNautilus(), NPC.AI_120_HallowBoss(), NPC.AI_120_HallowBoss_DashTo(), NPC.AI_120_HallowBoss_DoMagicEffect(), Projectile.AI_135_OgreStomp(), Projectile.AI_156_Think(), Projectile.AI_158_BabyBird(), Projectile.AI_159_PaperAirplanes(), Projectile.AI_160_Kites(), Projectile.AI_161_RapierStabs(), Projectile.AI_163_Chum(), Projectile.AI_165_Whip(), Projectile.AI_168_FirstFractal(), Projectile.AI_169_Smolstars(), Projectile.AI_171_GetColor(), Projectile.AI_171_HallowBossRainbowStreak(), Projectile.AI_172_GetPelletStormInfo(), Projectile.AI_172_HallowBossRainbowPelletStorm(), Projectile.AI_173_GetColor(), Projectile.AI_173_HallowBossRainbowTrail(), Projectile.AI_179_FairyQueenLance(), Projectile.AI_180_FairyQueenSunDance(), Projectile.AI_181_FairyQueenRangedItemShot(), Projectile.AI_182_FinalFractal(), Actions.Players.Fade.ApplyTo(), Actions.Sprites.Fade.ApplyTo(), CoinLossRevengeSystem.RevengeMarker.CalculateExpirationTime(), UIManageControls.CreatePanel(), FlameLashDrawer.Draw(), Segments.LocalizedTextSegment.Draw(), CreativeSacrificeParticle.Draw(), FadingParticle.Draw(), FlameParticle.Draw(), PrettySparkleParticle.Draw(), RandomizedFrameParticle.Draw(), ItemSlot.Draw(), Main.DrawItemTextPopups(), Main.DrawKite(), Main.DrawMurderAurora(), Main.DrawNPCDirect(), Main.DrawNPCDirect_HallowBoss(), PlayerDrawLayers.DrawPlayer_21_Head(), LegacyPlayerRenderer.DrawPlayerFull(), Main.DrawPrettyStarSparkle(), Main.DrawProj_EmpressBlade(), Main.DrawProj_FairyQueenLance(), Main.DrawProj_FairyQueenRangedItemShot(), Main.DrawProj_Flamethrower(), Main.DrawProj_PiercingStarlight(), Main.DrawProj_StardustGuardianPunching(), Main.DrawProjDirect(), Main.DrawProjWithStarryTrail(), PlayerDrawLayers.DrawStarboardRainbowTrail(), UIVerticalSlider.DrawValueBarDynamicWidth(), Main.DrawWhip_RainbowWhip(), Main.DrawWhip_WhipBland(), Main.DrawWhip_WhipMace(), Main.DrawWhip_WhipScythe(), HorizontalBarsPlayerResourcesDisplaySet.FillBarByValues(), Projectile.GetLastPrismHue(), Actions.Sprites.LinearScale.GetProgress(), Actions.Sprites.OutCircleScale.GetProgress(), UICreativeInfiniteItemsDisplay.GetSacrificeAnimationProgress(), FancyGolfPredictionLine.GetScale(), CreativePowers.ModifyWindDirectionAndStrength.GetSliderValueInner(), TileDrawing.GetWindCycle(), Projectile.HandleMovement(), FancyClassicPlayerResourcesDisplaySet.HeartFillingDrawer(), AmbientSky.SkyEntity.Helper_GetOpacityWithAccountingForOceanWaterLine(), Player.ItemCheck_ApplyUseStyle(), Player.ItemCheck_Shoot(), Projectile.Kill(), Player.ProcessHitAgainstNPC(), Remap(), FancyClassicPlayerResourcesDisplaySet.StarFillingDrawer(), ChromaHotkeyPainter.Step_QuickHeal(), EmpressBladeDrawer.StripColors(), FinalFractalHelper.FinalFractalProfile.StripColors(), FinalFractalHelper.StripColors(), FlameLashDrawer.StripColors(), MagicMissileDrawer.StripColors(), RainbowRodDrawer.StripColors(), FlameLashDrawer.StripWidth(), MagicMissileDrawer.StripWidth(), RainbowRodDrawer.StripWidth(), TileDrawing.Update(), ChromaHotkeyPainter.ReactiveRGBKey.Update(), GameTipsDisplay.GameTip.Update(), UIWorldLoad.Update(), PrettySparkleParticle.Update(), Mount.UpdateFrame(), Player.UpdateGraveyard(), AmbientSky.FadingSkyEntity.UpdateOpacity(), and UICreativeInfiniteItemsDisplay.UpdateVisualFrame().