Terraria: Utils.DrawCursorSingle
DrawCursorSingle()
static void Utils.DrawCursorSingle (SpriteBatch sb, Color color, float rot = float.NaN, float scale = 1f, Vector2 manualPosition = default(Vector2), int cursorSlot = 0, int specialMode = 0) inline static
     {
         bool flag = false;
         bool flag2 = true;
         bool flag3 = true;
         Vector2 origin = Vector2.Zero;
         Vector2 vector = new Vector2(Main.mouseX, Main.mouseY);
         if (manualPosition != Vector2.Zero)
         {
             vector = manualPosition;
         }
         if (float.IsNaN(rot))
         {
             rot = 0f;
         }
         else
         {
             flag = true;
             rot -= (float)Math.PI * 3f / 4f;
         }
         if (cursorSlot == 4 || cursorSlot == 5)
         {
             flag2 = false;
             origin = new Vector2(8f);
             if (flag && specialMode == 0)
             {
                 float num = rot;
                 if (num < 0f)
                 {
                     num += (float)Math.PI * 2f;
                 }
                 for (float num2 = 0f; num2 < 4f; num2 += 1f)
                 {
                     if (Math.Abs(num - (float)Math.PI / 2f * num2) <= (float)Math.PI / 4f)
                     {
                         rot = (float)Math.PI / 2f * num2;
                         break;
                     }
                 }
             }
         }
         Vector2 vector2 = Vector2.One;
         if ((Main.ThickMouse && cursorSlot == 0) || cursorSlot == 1)
         {
             vector2 = Main.DrawThickCursor(cursorSlot == 1);
         }
         if (flag2)
         {
             sb.Draw(TextureAssets.Cursors[cursorSlot].Value, vector + vector2 + Vector2.One, null, color.MultiplyRGB(new Color(0.2f, 0.2f, 0.2f, 0.5f)), rot, origin, scale * 1.1f, SpriteEffects.None, 0f);
         }
         if (flag3)
         {
             sb.Draw(TextureAssets.Cursors[cursorSlot].Value, vector + vector2, null, color, rot, origin, scale, SpriteEffects.None, 0f);
         }
     }
References Color, TextureAssets.Cursors, Main.DrawThickCursor(), Main.mouseX, Main.mouseY, Main.ThickMouse, and Asset< T >.Value.
Referenced by CaptureInterface.Draw(), and CaptureInterface.ModeEdgeSelection.DrawCursors().