Terraria: Utils.DrawBorderStringFourWay
DrawBorderStringFourWay()
static void Utils.DrawBorderStringFourWay (SpriteBatch sb, DynamicSpriteFont font, string text, float x, float y, Color textColor, Color borderColor, Vector2 origin, float scale = 1f) inline static
     {
         Color color = borderColor;
         Vector2 zero = Vector2.Zero;
         for (int i = 0; i < 5; i++)
         {
             switch (i)
             {
             case 0:
                 zero.X = x - 2f;
                 zero.Y = y;
                 break;
             case 1:
                 zero.X = x + 2f;
                 zero.Y = y;
                 break;
             case 2:
                 zero.X = x;
                 zero.Y = y - 2f;
                 break;
             case 3:
                 zero.X = x;
                 zero.Y = y + 2f;
                 break;
             default:
                 zero.X = x;
                 zero.Y = y;
                 color = textColor;
                 break;
             }
             DynamicSpriteFontExtensionMethods.DrawString(sb, font, text, zero, color, 0f, origin, scale, SpriteEffects.None, 0f);
         }
     }
References Color, and DynamicSpriteFontExtensionMethods.DrawString().
Referenced by UIAchievementsMenu.Draw(), UICharacterCreation.Draw(), WorkshopPublishingIndicator.Draw(), BigProgressBarHelper.DrawHealthText(), Main.DrawInventory(), Main.DrawMenu(), ItemSlot.DrawMoney(), Main.DrawMouseOver(), CustomCurrencyManager.DrawSavings(), CustomCurrencySingleCoin.DrawSavingsMoney(), and Main.GUIChatDrawInner().