Terraria: Utils.CenteredRectangle
CenteredRectangle()
static Rectangle Utils.CenteredRectangle (Vector2 center, Vector2 size) inline static
     {
         return new Rectangle((int)(center.X - size.X / 2f), (int)(center.Y - size.Y / 2f), (int)size.X, (int)size.Y);
     }
Referenced by CoinLossRevengeSystem.RevengeMarker.RevengeMarker(), NPC.AI(), Projectile.AI_019_Spears_GetExtensionHitbox(), Projectile.AI_067_FreakingPirates(), Projectile.AI_067_TigerSpecialAttack(), NPC.AI_112_FairyCritter(), Projectile.AI_138_ExplosiveTrap(), Projectile.AI_144_DD2Pet(), Projectile.AI_150_GolfClubHelper(), Projectile.AI_151_SuperStar(), Projectile.AI_165_Whip(), Projectile.AI_192_JuminoAnimation(), NPC.AnyoneNearCultists(), CoinLossRevengeSystem.CheckRespawns(), Projectile.Colliding(), IssueReportsIndicator.Draw(), BigProgressBarHelper.DrawBareBonesBar(), Main.DrawBuilderAccToggles(), Main.DrawDefenseCounter(), MoonlordDeathDrama.DrawExplosions(), BigProgressBarHelper.DrawFancyBar(), WiresUI.WiresRadial.DrawFlower(), InGamePopups.AchievementUnlockedPopup.DrawInGame(), InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame(), InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea(), Main.DrawInvasionProgress(), WiresUI.WiresRadial.DrawLine(), CoinLossRevengeSystem.RevengeMarker.DrawMapIcon(), Main.DrawMapIcons_LastGolfballHit(), Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition(), Main.DrawMapIcons_PotionOfReturnHomePosition(), MoonlordDeathDrama.DrawPieces(), PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), PlayerDrawLayers.DrawPlayer_14_2_GlassSlipperSparkles(), ItemSlot.DrawSavings(), CustomCurrencyManager.DrawSavings(), TileDrawing.DrawTeleportationPylons(), CreativeUI.DrawToggleButton(), UIVerticalSlider.DrawValueBarDynamicWidth(), Projectile.HallowBossPelletStormInfo.GetBulletHitbox(), IngameOptions.GetExpectedRectangleForNotification(), NPC.GetMeleeCollisionData(), Player.GetSparkleGuitarTarget(), Projectile.Kill(), Player.MowTheLawn(), NPCSmartInteractCandidateProvider.ProvideCandidate(), LockOnHelper.RefreshTargets(), WindGrid.ScanPlayer(), ParticleOrchestrator.Spawn_ShimmerTownNPC(), ParticleOrchestrator.Spawn_ShimmerTownNPCSend(), PotionOfReturnHelper.TryGetGateHitbox(), Projectile.UpdateEnchantmentVisuals(), and Player.WingFrame().