Terraria: Utils.DrawSettingsPanel
DrawSettingsPanel()
static void Utils.DrawSettingsPanel (SpriteBatch spriteBatch, Vector2 position, float width, Color color) inline static
     {
         DrawPanel(TextureAssets.SettingsPanel.Value, 2, 0, spriteBatch, position, width, color);
     }
References DrawPanel(), TextureAssets.SettingsPanel, and Asset< T >.Value.
Referenced by UIKeybindingListItem.DrawSelf(), UIKeybindingSliderItem.DrawSelf(), and UIKeybindingToggleListItem.DrawSelf().