Terraria: Utils.DrawSplicedPanel
DrawSplicedPanel()
static void Utils.DrawSplicedPanel (SpriteBatch sb, Texture2D texture, int x, int y, int w, int h, int leftEnd, int rightEnd, int topEnd, int bottomEnd, Color c) inline static
     {
         if (w < leftEnd + rightEnd)
         {
             w = leftEnd + rightEnd;
         }
         if (h < topEnd + bottomEnd)
         {
             h = topEnd + bottomEnd;
         }
         sb.Draw(texture, new Rectangle(x, y, leftEnd, topEnd), new Rectangle(0, 0, leftEnd, topEnd), c);
         sb.Draw(texture, new Rectangle(x + leftEnd, y, w - leftEnd - rightEnd, topEnd), new Rectangle(leftEnd, 0, texture.Width - leftEnd - rightEnd, topEnd), c);
         sb.Draw(texture, new Rectangle(x + w - rightEnd, y, topEnd, rightEnd), new Rectangle(texture.Width - rightEnd, 0, rightEnd, topEnd), c);
         sb.Draw(texture, new Rectangle(x, y + topEnd, leftEnd, h - topEnd - bottomEnd), new Rectangle(0, topEnd, leftEnd, texture.Height - topEnd - bottomEnd), c);
         sb.Draw(texture, new Rectangle(x + leftEnd, y + topEnd, w - leftEnd - rightEnd, h - topEnd - bottomEnd), new Rectangle(leftEnd, topEnd, texture.Width - leftEnd - rightEnd, texture.Height - topEnd - bottomEnd), c);
         sb.Draw(texture, new Rectangle(x + w - rightEnd, y + topEnd, rightEnd, h - topEnd - bottomEnd), new Rectangle(texture.Width - rightEnd, topEnd, rightEnd, texture.Height - topEnd - bottomEnd), c);
         sb.Draw(texture, new Rectangle(x, y + h - bottomEnd, leftEnd, bottomEnd), new Rectangle(0, texture.Height - bottomEnd, leftEnd, bottomEnd), c);
         sb.Draw(texture, new Rectangle(x + leftEnd, y + h - bottomEnd, w - leftEnd - rightEnd, bottomEnd), new Rectangle(leftEnd, texture.Height - bottomEnd, texture.Width - leftEnd - rightEnd, bottomEnd), c);
         sb.Draw(texture, new Rectangle(x + w - rightEnd, y + h - bottomEnd, rightEnd, bottomEnd), new Rectangle(texture.Width - rightEnd, texture.Height - bottomEnd, rightEnd, bottomEnd), c);
     }
Referenced by Main.DrawHairWindow(), UIWorkshopPublishResourcePackListItem.DrawPanel(), UIWorkshopPublishWorldListItem.DrawPanel(), GroupOptionButton< T >.DrawSelf(), UICharacterNameButton.DrawSelf(), UIClothStyleButton.DrawSelf(), UIDifficultyButton.DrawSelf(), UIIconTextButton.DrawSelf(), UIResourcePackInfoButton< T >.DrawSelf(), UISelectableTextPanel< T >.DrawSelf(), UISlicedImage.DrawSelf(), UIColoredSliderSimple.DrawValueBarDynamicWidth(), and UIVerticalSlider.DrawValueBarDynamicWidth().