Terraria: JunglePass.GenerateHolesInMudWalls
GenerateHolesInMudWalls()
void JunglePass.GenerateHolesInMudWalls () inline private
     {
         for (int i = 0; i < Main.maxTilesX / 4; i++)
         {
             int num = GenBase._random.Next(20, Main.maxTilesX - 20);
             int num2 = GenBase._random.Next((int)GenVars.worldSurface + 10, Main.UnderworldLayer);
             while (Main.tile[num, num2].wall != 64 && Main.tile[num, num2].wall != 15)
             {
                 num = GenBase._random.Next(20, Main.maxTilesX - 20);
                 num2 = GenBase._random.Next((int)GenVars.worldSurface + 10, Main.UnderworldLayer);
             }
             WorldGen.MudWallRunner(num, num2);
         }
     }
References GenBase._random, Main.maxTilesX, WorldGen.MudWallRunner(), UnifiedRandom.Next(), Main.tile, Main.UnderworldLayer, Tile.wall, and GenVars.worldSurface.
Referenced by ApplyPass().