Terraria: JunglePass.GenerateFinishingTouches
GenerateFinishingTouches()
void JunglePass.GenerateFinishingTouches (GenerationProgress progress, int oldX, int oldY) inline private
     {
         int num = oldX;
         int num2 = oldY;
         double worldScale = _worldScale;
         for (int i = 0; (double)i <= 20.0 * worldScale; i++)
         {
             progress.Set((60.0 + (double)i / worldScale) * 0.01);
             num += GenBase._random.Next((int)(-5.0 * worldScale), (int)(6.0 * worldScale));
             num2 += GenBase._random.Next((int)(-5.0 * worldScale), (int)(6.0 * worldScale));
             WorldGen.TileRunner(num, num2, GenBase._random.Next(40, 100), GenBase._random.Next(300, 500), 59);
         }
         for (int j = 0; (double)j <= 10.0 * worldScale; j++)
         {
             progress.Set((80.0 + (double)j / worldScale * 2.0) * 0.01);
             num = oldX + GenBase._random.Next((int)(-600.0 * worldScale), (int)(600.0 * worldScale));
             num2 = oldY + GenBase._random.Next((int)(-200.0 * worldScale), (int)(200.0 * worldScale));
             while (num < 1 || num >= Main.maxTilesX - 1 || num2 < 1 || num2 >= Main.maxTilesY - 1 || Main.tile[num, num2].type != 59)
             {
                 num = oldX + GenBase._random.Next((int)(-600.0 * worldScale), (int)(600.0 * worldScale));
                 num2 = oldY + GenBase._random.Next((int)(-200.0 * worldScale), (int)(200.0 * worldScale));
             }
             for (int k = 0; (double)k < 8.0 * worldScale; k++)
             {
                 num += GenBase._random.Next(-30, 31);
                 num2 += GenBase._random.Next(-30, 31);
                 int type = -1;
                 if (GenBase._random.Next(7) == 0)
                 {
                     type = -2;
                 }
                 WorldGen.TileRunner(num, num2, GenBase._random.Next(10, 20), GenBase._random.Next(30, 70), type);
             }
         }
         for (int l = 0; (double)l <= 300.0 * worldScale; l++)
         {
             num = oldX + GenBase._random.Next((int)(-600.0 * worldScale), (int)(600.0 * worldScale));
             num2 = oldY + GenBase._random.Next((int)(-200.0 * worldScale), (int)(200.0 * worldScale));
             while (num < 1 || num >= Main.maxTilesX - 1 || num2 < 1 || num2 >= Main.maxTilesY - 1 || Main.tile[num, num2].type != 59)
             {
                 num = oldX + GenBase._random.Next((int)(-600.0 * worldScale), (int)(600.0 * worldScale));
                 num2 = oldY + GenBase._random.Next((int)(-200.0 * worldScale), (int)(200.0 * worldScale));
             }
             WorldGen.TileRunner(num, num2, GenBase._random.Next(4, 10), GenBase._random.Next(5, 30), 1);
             if (GenBase._random.Next(4) == 0)
             {
                 int type2 = GenBase._random.Next(63, 69);
                 WorldGen.TileRunner(num + GenBase._random.Next(-1, 2), num2 + GenBase._random.Next(-1, 2), GenBase._random.Next(3, 7), GenBase._random.Next(4, 8), type2);
             }
         }
     }
References GenBase._random, _worldScale, Main.maxTilesX, Main.maxTilesY, UnifiedRandom.Next(), GenerationProgress.Set(), Main.tile, WorldGen.TileRunner(), and Tile.type.
Referenced by ApplyPass().