Terraria: System.Data.Select.SelectRows
SelectRows()
DataRow[] System.Data.Select.SelectRows () inline
Definition at line 488 of file Select.cs.
    {
        bool flag = true;
        InitCandidateColumns();
        if (_expression is BinaryNode)
        {
            AnalyzeExpression((BinaryNode)_expression);
            if (!_candidatesForBinarySearch)
            {
                _linearExpression = _expression;
            }
            if (_linearExpression == _expression)
            {
                for (int i = 0; i < _candidateColumns.Length; i++)
                {
                    if (_candidateColumns[i] != null)
                    {
                        _candidateColumns[i].equalsOperator = false;
                        _candidateColumns[i].expr = null;
                    }
                }
            }
            else
            {
                flag = !FindClosestCandidateIndex();
            }
        }
        else
        {
            _linearExpression = _expression;
        }
        if (_index == null && (_indexFields.Length != 0 || _linearExpression == _expression))
        {
            flag = !FindSortIndex();
        }
        if (_index == null)
        {
            CreateIndex();
            flag = false;
        }
        if (_index.RecordCount == 0)
        {
            return _table.NewRowArray(0);
        }
        Range range;
        if (_matchedCandidates == 0)
        {
            range = new Range(0, _index.RecordCount - 1);
            _linearExpression = _expression;
            return GetLinearFilteredRows(range);
        }
        range = GetBinaryFilteredRecords();
        if (range.Count == 0)
        {
            return _table.NewRowArray(0);
        }
        if (_matchedCandidates < _nCandidates)
        {
            BuildLinearExpression();
        }
        if (!flag)
        {
            return GetLinearFilteredRows(range);
        }
        _records = GetLinearFilteredRecords(range);
        _recordCount = _records.Length;
        if (_recordCount == 0)
        {
            return _table.NewRowArray(0);
        }
        Sort(0, _recordCount - 1);
        return GetRows();
    }
References System.Data.Select._candidateColumns, System.Data.Select._candidatesForBinarySearch, System.Data.Select._expression, System.Data.Select._index, System.Data.Select._indexFields, System.Data.Select._linearExpression, System.Data.Select._matchedCandidates, System.Data.Select._nCandidates, System.Data.Select._recordCount, System.Data.Select._records, System.Data.Select._table, System.Data.Select.AnalyzeExpression(), System.Data.Select.BuildLinearExpression(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.Select.CreateIndex(), System.Data.Select.ColumnInfo.equalsOperator, System.Data.Select.ColumnInfo.expr, System.Data.Select.FindClosestCandidateIndex(), System.Data.Select.FindSortIndex(), System.Data.Select.GetBinaryFilteredRecords(), System.Data.Select.GetLinearFilteredRecords(), System.Data.Select.GetLinearFilteredRows(), System.Data.Select.GetRows(), System.Data.Select.InitCandidateColumns(), System.Data.DataTable.NewRowArray(), System.Data.Index.RecordCount, and System.Data.Select.Sort().