Terraria: System.Data.Select.GetLinearFilteredRows
GetLinearFilteredRows()
DataRow[] System.Data.Select.GetLinearFilteredRows (Range range) inline private
Definition at line 813 of file Select.cs.
    {
        if (_linearExpression == null)
        {
            return _index.GetRows(range);
        }
        List<DataRow> list = new List<DataRow>();
        RBTree<int>.RBTreeEnumerator enumerator = _index.GetEnumerator(range.Min);
        for (int i = 0; i < range.Count; i++)
        {
            if (!enumerator.MoveNext())
            {
                break;
            }
            if (AcceptRecord(enumerator.Current))
            {
                list.Add(_table._recordManager[enumerator.Current]);
            }
        }
        DataRow[] array = _table.NewRowArray(list.Count);
        list.CopyTo(array);
        return array;
    }
References System.Data.Select._index, System.Data.Select._linearExpression, System.Data.DataTable._recordManager, System.Data.Select._table, System.Data.Select.AcceptRecord(), System.Data.RBTree< K >.Add(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.Index.GetEnumerator(), System.Data.Index.GetRows(), System.list, and System.Data.DataTable.NewRowArray().
Referenced by System.Data.Select.SelectRows().