Terraria: System.Data.Select.GetLinearFilteredRecords
GetLinearFilteredRecords()
int[] System.Data.Select.GetLinearFilteredRecords (Range range) inline private
Definition at line 781 of file Select.cs.
    {
        if (_linearExpression == null)
        {
            int[] array = new int[range.Count];
            RBTree<int>.RBTreeEnumerator enumerator = _index.GetEnumerator(range.Min);
            for (int i = 0; i < range.Count; i++)
            {
                if (!enumerator.MoveNext())
                {
                    break;
                }
                array[i] = enumerator.Current;
            }
            return array;
        }
        List<int> list = new List<int>();
        RBTree<int>.RBTreeEnumerator enumerator2 = _index.GetEnumerator(range.Min);
        for (int j = 0; j < range.Count; j++)
        {
            if (!enumerator2.MoveNext())
            {
                break;
            }
            if (AcceptRecord(enumerator2.Current))
            {
                list.Add(enumerator2.Current);
            }
        }
        return list.ToArray();
    }
References System.Data.Select._index, System.Data.Select._linearExpression, System.Data.Select.AcceptRecord(), System.Data.RBTree< K >.Add(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.Index.GetEnumerator(), and System.list.
Referenced by System.Data.Select.SelectRows().