Terraria: System.Data.Select.GetBinaryFilteredRecords
GetBinaryFilteredRecords()
Range System.Data.Select.GetBinaryFilteredRecords () inline private
Definition at line 766 of file Select.cs.
    {
        if (_matchedCandidates == 0)
        {
            return new Range(0, _index.RecordCount - 1);
        }
        int num = FindFirstMatchingRecord();
        if (num == -1)
        {
            return default(Range);
        }
        int max = FindLastMatchingRecord(num);
        return new Range(num, max);
    }
References System.Data.Select._index, System.Data.Select._matchedCandidates, System.Data.Select.FindFirstMatchingRecord(), System.Data.Select.FindLastMatchingRecord(), and System.Data.Index.RecordCount.
Referenced by System.Data.Select.SelectRows().