Terraria: System.Xml.Xsl.SourceLineInfo.GetFileName
GetFileName()
static string System.Xml.Xsl.SourceLineInfo.GetFileName (string uriString) inline static
Definition at line 50 of file SourceLineInfo.cs.
    {
        if (uriString.Length != 0 && System.Uri.TryCreate(uriString, UriKind.Absolute, out Uri result) && result.IsFile)
        {
            return result.LocalPath;
        }
        return uriString;
    }
References System.Xml.Dictionary, System.Uri.TryCreate(), and System.Xml.Xsl.SourceLineInfo.uriString.
Referenced by System.Xml.Xsl.XslLoadException.AppendLineInfoMessage(), and System.Xml.Xsl.IlGen.GenerateHelper.GetFileName().