Terraria: System.Data.Select.CreateIndex
CreateIndex()
void System.Data.Select.CreateIndex () inline private
Definition at line 322 of file Select.cs.
    {
        if (_index != null)
        {
            return;
        }
        if (_nCandidates == 0)
        {
            _index = new Index(_table, _indexFields, _recordStates, null);
            _index.AddRef();
            return;
        }
        int num = _candidateColumns.Length;
        int num2 = _indexFields.Length;
        bool flag = true;
        int i;
        for (i = 0; i < num; i++)
        {
            if (_candidateColumns[i] != null && !_candidateColumns[i].equalsOperator)
            {
                flag = false;
                break;
            }
        }
        int num3 = 0;
        for (i = 0; i < num2; i++)
        {
            ColumnInfo columnInfo = _candidateColumns[_indexFields[i].Column.Ordinal];
            if (columnInfo != null)
            {
                columnInfo.flag = true;
                num3++;
            }
        }
        int num4 = num2 - num3;
        IndexField[] array = new IndexField[_nCandidates + num4];
        if (flag)
        {
            num3 = 0;
            for (i = 0; i < num; i++)
            {
                if (_candidateColumns[i] != null)
                {
                    array[num3++] = new IndexField(_table.Columns[i], isDescending: false);
                    _candidateColumns[i].flag = false;
                }
            }
            for (i = 0; i < num2; i++)
            {
                ColumnInfo columnInfo2 = _candidateColumns[_indexFields[i].Column.Ordinal];
                if (columnInfo2 == null || columnInfo2.flag)
                {
                    array[num3++] = _indexFields[i];
                    if (columnInfo2 != null)
                    {
                        columnInfo2.flag = false;
                    }
                }
            }
            for (i = 0; i < _candidateColumns.Length; i++)
            {
                if (_candidateColumns[i] != null)
                {
                    _candidateColumns[i].flag = false;
                }
            }
            _index = new Index(_table, array, _recordStates, null);
            if (!IsOperatorIn(_expression))
            {
                _index.AddRef();
            }
            _matchedCandidates = _nCandidates;
            return;
        }
        for (i = 0; i < num2; i++)
        {
            array[i] = _indexFields[i];
            ColumnInfo columnInfo3 = _candidateColumns[_indexFields[i].Column.Ordinal];
            if (columnInfo3 != null)
            {
                columnInfo3.flag = true;
            }
        }
        num3 = i;
        for (i = 0; i < num; i++)
        {
            if (_candidateColumns[i] != null)
            {
                if (!_candidateColumns[i].flag)
                {
                    array[num3++] = new IndexField(_table.Columns[i], isDescending: false);
                }
                else
                {
                    _candidateColumns[i].flag = false;
                }
            }
        }
        _index = new Index(_table, array, _recordStates, null);
        _matchedCandidates = 0;
        if (_linearExpression != _expression)
        {
            IndexField[] indexFields = _index._indexFields;
            while (_matchedCandidates < num3)
            {
                ColumnInfo columnInfo4 = _candidateColumns[indexFields[_matchedCandidates].Column.Ordinal];
                if (columnInfo4 == null || columnInfo4.expr == null)
                {
                    break;
                }
                _matchedCandidates++;
                if (!columnInfo4.equalsOperator)
                {
                    break;
                }
            }
        }
        for (i = 0; i < _candidateColumns.Length; i++)
        {
            if (_candidateColumns[i] != null)
            {
                _candidateColumns[i].flag = false;
            }
        }
    }
References System.Data.Select._candidateColumns, System.Data.Select._expression, System.Data.Select._index, System.Data.Index._indexFields, System.Data.Select._indexFields, System.Data.Select._linearExpression, System.Data.Select._matchedCandidates, System.Data.Select._nCandidates, System.Data.Select._recordStates, System.Data.Select._table, System.Data.Index.AddRef(), System.array, System.Data.IndexField.Column, System.Data.DataTable.Columns, System.Data.Select.ColumnInfo.flag, System.Data.Select.IsOperatorIn(), and System.Data.DataColumn.Ordinal.
Referenced by System.Data.Select.SelectRows().