Terraria: System.Data.Select.FindLastMatchingRecord
FindLastMatchingRecord()
int System.Data.Select.FindLastMatchingRecord (int lo) inline private
Definition at line 741 of file Select.cs.
    {
        int result = -1;
        int num = _index.RecordCount - 1;
        while (lo <= num)
        {
            int num2 = lo + num >> 1;
            int record = _index.GetRecord(num2);
            int num3 = Evaluate(record);
            if (num3 == 0)
            {
                result = num2;
            }
            if (num3 <= 0)
            {
                lo = num2 + 1;
            }
            else
            {
                num = num2 - 1;
            }
        }
        return result;
    }
References System.Data.Select._index, System.Data.Select.Evaluate(), and System.Data.Index.GetRecord().
Referenced by System.Data.Select.GetBinaryFilteredRecords().