Terraria: System.Data.Select.Eval
Eval()
int System.Data.Select.Eval (BinaryNode expr, DataRow row, DataRowVersion version) inline private
Definition at line 605 of file Select.cs.
    {
        if (expr._op == 26)
        {
            int num = Eval((BinaryNode)expr._left, row, version);
            if (num != 0)
            {
                return num;
            }
            int num2 = Eval((BinaryNode)expr._right, row, version);
            if (num2 != 0)
            {
                return num2;
            }
            return 0;
        }
        long num3 = 0L;
        object obj = expr._left.Eval(row, version);
        if (expr._op != 13 && expr._op != 39)
        {
            object obj2 = expr._right.Eval(row, version);
            bool flag = expr._left is ConstNode;
            bool flag2 = expr._right is ConstNode;
            if (obj == DBNull.Value || (expr._left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)))
            {
                return -1;
            }
            if (obj2 == DBNull.Value || (expr._right.IsSqlColumn && DataStorage.IsObjectSqlNull(obj2)))
            {
                return 1;
            }
            StorageType storageType = DataStorage.GetStorageType(obj.GetType());
            if (StorageType.Char == storageType)
            {
                obj2 = ((!flag2 && expr._right.IsSqlColumn) ? SqlConvert.ChangeType2(obj2, StorageType.Char, typeof(char), _table.FormatProvider) : ((object)Convert.ToChar(obj2, _table.FormatProvider)));
            }
            StorageType storageType2 = DataStorage.GetStorageType(obj2.GetType());
            StorageType storageType3 = ((!expr._left.IsSqlColumn && !expr._right.IsSqlColumn) ? expr.ResultType(storageType, storageType2, flag, flag2, expr._op) : expr.ResultSqlType(storageType, storageType2, flag, flag2, expr._op));
            if (storageType3 == StorageType.Empty)
            {
                expr.SetTypeMismatchError(expr._op, obj.GetType(), obj2.GetType());
            }
            NameNode nameNode = null;
            CompareInfo comparer = (((flag && !flag2 && storageType == StorageType.String && storageType2 == StorageType.Guid && expr._right is NameNode nameNode2 && nameNode2._column.DataType == typeof(Guid)) || (flag2 && !flag && storageType2 == StorageType.String && storageType == StorageType.Guid && expr._left is NameNode nameNode3 && nameNode3._column.DataType == typeof(Guid))) ? CultureInfo.InvariantCulture.CompareInfo : null);
            num3 = expr.BinaryCompare(obj, obj2, storageType3, expr._op, comparer);
        }
        switch (expr._op)
        {
        case 7:
            num3 = ((num3 != 0L) ? ((num3 >= 0) ? 1 : (-1)) : 0);
            break;
        case 8:
            num3 = ((num3 <= 0) ? (-1) : 0);
            break;
        case 9:
            num3 = ((num3 >= 0) ? 1 : 0);
            break;
        case 10:
            num3 = ((num3 < 0) ? (-1) : 0);
            break;
        case 11:
            num3 = ((num3 > 0) ? 1 : 0);
            break;
        case 13:
            num3 = ((obj != DBNull.Value) ? (-1) : 0);
            break;
        case 39:
            num3 = ((obj == DBNull.Value) ? 1 : 0);
            break;
        }
        return (int)num3;
    }
References System.Data.BinaryNode._left, System.Data.BinaryNode._op, System.Data.BinaryNode._right, System.Data.Select._table, System.Data.BinaryNode.BinaryCompare(), System.Data.Common.SqlConvert.ChangeType2(), System.comparer, System.Data.ExpressionNode.Eval(), System.Data.Select.Eval(), System.Data.DataTable.FormatProvider, System.Data.Common.DataStorage.GetStorageType(), System.Data.Common.DataStorage.IsObjectSqlNull(), System.Data.ExpressionNode.IsSqlColumn, System.L, System.obj, System.Data.BinaryNode.ResultSqlType(), System.Data.BinaryNode.ResultType(), System.Data.BinaryNode.SetTypeMismatchError(), System.Convert.ToChar(), and System.DBNull.Value.
Referenced by System.Data.Select.Eval(), and System.Data.Select.Evaluate().