Terraria: System.Data.Select.AcceptRecord
AcceptRecord()
bool System.Data.Select.AcceptRecord (int record) inline private
Definition at line 573 of file Select.cs.
    {
        DataRow dataRow = _table._recordManager[record];
        if (dataRow == null)
        {
            return true;
        }
        DataRowVersion version = DataRowVersion.Default;
        if (dataRow._oldRecord == record)
        {
            version = DataRowVersion.Original;
        }
        else if (dataRow._newRecord == record)
        {
            version = DataRowVersion.Current;
        }
        else if (dataRow._tempRecord == record)
        {
            version = DataRowVersion.Proposed;
        }
        object value = _linearExpression.Eval(dataRow, version);
        try
        {
            return DataExpression.ToBoolean(value);
        }
        catch (Exception e) when (ADP.IsCatchableExceptionType(e))
        {
            throw ExprException.FilterConvertion(_rowFilter.Expression);
        }
    }
References System.Data.Select._linearExpression, System.Data.DataTable._recordManager, System.Data.Select._rowFilter, System.Data.Select._table, System.Data.ExpressionNode.Eval(), System.Data.DataExpression.Expression, System.Data.ExprException.FilterConvertion(), System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.DataExpression.ToBoolean(), and System.value.
Referenced by System.Data.Select.GetLinearFilteredRecords(), and System.Data.Select.GetLinearFilteredRows().