Terraria: MS.Internal.Xml.XPath.NodeFunctions.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.NodeFunctions.Evaluate (XPathNodeIterator context) inline
Definition at line 41 of file NodeFunctions.cs.
    {
        switch (_funcType)
        {
        case Function.FunctionType.FuncPosition:
            return (double)context.CurrentPosition;
        case Function.FunctionType.FuncLast:
            return (double)context.Count;
        case Function.FunctionType.FuncNameSpaceUri:
        {
            XPathNavigator xPathNavigator2 = EvaluateArg(context);
            if (xPathNavigator2 != null)
            {
                return xPathNavigator2.NamespaceURI;
            }
            break;
        }
        case Function.FunctionType.FuncLocalName:
        {
            XPathNavigator xPathNavigator2 = EvaluateArg(context);
            if (xPathNavigator2 != null)
            {
                return xPathNavigator2.LocalName;
            }
            break;
        }
        case Function.FunctionType.FuncName:
        {
            XPathNavigator xPathNavigator2 = EvaluateArg(context);
            if (xPathNavigator2 != null)
            {
                return xPathNavigator2.Name;
            }
            break;
        }
        case Function.FunctionType.FuncCount:
        {
            _arg.Evaluate(context);
            int num = 0;
            if (_xsltContext != null)
            {
                XPathNavigator xPathNavigator;
                while ((xPathNavigator = _arg.Advance()) != null)
                {
                    if (xPathNavigator.NodeType != XPathNodeType.Whitespace || _xsltContext.PreserveWhitespace(xPathNavigator))
                    {
                        num++;
                    }
                }
            }
            else
            {
                while (_arg.Advance() != null)
                {
                    num++;
                }
            }
            return (double)num;
        }
        }
        return string.Empty;
    }
References MS.Internal.Xml.XPath.NodeFunctions._arg, MS.Internal.Xml.XPath.NodeFunctions._funcType, MS.Internal.Xml.XPath.NodeFunctions._xsltContext, MS.Internal.Xml.XPath.Query.Advance(), System.Xml.XPath.XPathNodeIterator.Count, System.Xml.XPath.XPathNodeIterator.CurrentPosition, MS.Internal.Xml.XPath.Query.Evaluate(), MS.Internal.Xml.XPath.NodeFunctions.EvaluateArg(), System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.Name, System.Xml.XPath.XPathNavigator.NamespaceURI, System.Xml.XPath.XPathNavigator.NodeType, and System.Xml.Xsl.XsltContext.PreserveWhitespace().