Terraria: System.Xml.Xsl.XsltOld.RecordBuilder.FinalizeRecord
FinalizeRecord()
void System.Xml.Xsl.XsltOld.RecordBuilder.FinalizeRecord () inline private
Definition at line 579 of file RecordBuilder.cs.
    {
        switch (_mainNode.NodeType)
        {
        case XmlNodeType.Element:
        {
            int attributeCount = _attributeCount;
            FixupElement();
            FixupAttributes(attributeCount);
            AnalyzeSpaceLang();
            AppendNamespaces();
            break;
        }
        case XmlNodeType.Comment:
            AnalyzeComment();
            break;
        case XmlNodeType.ProcessingInstruction:
            AnalyzeProcessingInstruction();
            break;
        }
    }
References System.Xml.Xsl.XsltOld.RecordBuilder._attributeCount, System.Xml.Xsl.XsltOld.RecordBuilder._mainNode, System.Xml.Xsl.XsltOld.RecordBuilder.AnalyzeComment(), System.Xml.Xsl.XsltOld.RecordBuilder.AnalyzeProcessingInstruction(), System.Xml.Xsl.XsltOld.RecordBuilder.AnalyzeSpaceLang(), System.Xml.Xsl.XsltOld.RecordBuilder.AppendNamespaces(), System.Xml.Xsl.XsltOld.RecordBuilder.FixupAttributes(), System.Xml.Xsl.XsltOld.RecordBuilder.FixupElement(), and System.Xml.Xsl.XsltOld.BuilderInfo.NodeType.
Referenced by System.Xml.Xsl.XsltOld.RecordBuilder.CanOutput(), System.Xml.Xsl.XsltOld.RecordBuilder.CheckRecordBegin(), System.Xml.Xsl.XsltOld.RecordBuilder.CheckRecordEnd(), and System.Xml.Xsl.XsltOld.RecordBuilder.TheEnd().