Terraria: System.Xml.Xsl.XsltOld.RecordBuilder.CheckRecordBegin
CheckRecordBegin()
Processor.OutputResult System.Xml.Xsl.XsltOld.RecordBuilder.CheckRecordBegin (int state) inline private
Definition at line 344 of file RecordBuilder.cs.
    {
        if (((uint)state & 0x4000u) != 0)
        {
            _recordState = 2;
            FinalizeRecord();
            SetEmptyFlag(state);
            return _output.RecordDone(this);
        }
        _recordState = 1;
        return Processor.OutputResult.Continue;
    }
References System.Xml.Xsl.XsltOld.RecordBuilder._output, System.Xml.Xsl.XsltOld.RecordBuilder._recordState, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.RecordBuilder.FinalizeRecord(), System.Xml.Xsl.XsltOld.IRecordOutput.RecordDone(), System.Xml.Xsl.XsltOld.RecordBuilder.SetEmptyFlag(), and System.state.
Referenced by System.Xml.Xsl.XsltOld.RecordBuilder.BeginEvent(), and System.Xml.Xsl.XsltOld.RecordBuilder.TextEvent().