Terraria: System.Xml.Xsl.XsltOld.RecordBuilder.TheEnd
TheEnd()
void System.Xml.Xsl.XsltOld.RecordBuilder.TheEnd () inline package
Definition at line 185 of file RecordBuilder.cs.
    {
        if (_recordState == 1)
        {
            _recordState = 2;
            FinalizeRecord();
            _output.RecordDone(this);
        }
        _output.TheEnd();
    }
References System.Xml.Xsl.XsltOld.RecordBuilder._output, System.Xml.Xsl.XsltOld.RecordBuilder._recordState, System.Xml.Xsl.XsltOld.RecordBuilder.FinalizeRecord(), System.Xml.Xsl.XsltOld.IRecordOutput.RecordDone(), and System.Xml.Xsl.XsltOld.IRecordOutput.TheEnd().
Referenced by System.Xml.Xsl.XsltOld.Processor.Execute().