Terraria: System.Xml.Xsl.XsltOld.RecordBuilder.DeclareNamespace
DeclareNamespace()
void System.Xml.Xsl.XsltOld.RecordBuilder.DeclareNamespace (string nspace, string prefix) inline private
Definition at line 610 of file RecordBuilder.cs.
    {
        int index = NewNamespace();
        BuilderInfo builderInfo = (BuilderInfo)_namespaceList[index];
        if (prefix == _atoms.Empty)
        {
            builderInfo.Initialize(_atoms.Empty, _atoms.Xmlns, _atoms.XmlnsNamespace);
        }
        else
        {
            builderInfo.Initialize(_atoms.Xmlns, prefix, _atoms.XmlnsNamespace);
        }
        builderInfo.Depth = _recordDepth;
        builderInfo.NodeType = XmlNodeType.Attribute;
        builderInfo.Value = nspace;
        _scopeManager.PushNamespace(prefix, nspace);
    }
References System.Xml.Xsl.XsltOld.RecordBuilder._atoms, System.Xml.Xsl.XsltOld.RecordBuilder._namespaceList, System.Xml.Xsl.XsltOld.RecordBuilder._recordDepth, System.Xml.Xsl.XsltOld.RecordBuilder._scopeManager, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.OutKeywords.Empty, System.index, System.Xml.Xsl.XsltOld.RecordBuilder.NewNamespace(), System.prefix, System.Xml.Xsl.XsltOld.OutputScopeManager.PushNamespace(), System.Xml.Xsl.XsltOld.OutKeywords.Xmlns, and System.Xml.Xsl.XsltOld.OutKeywords.XmlnsNamespace.
Referenced by System.Xml.Xsl.XsltOld.RecordBuilder.BeginNamespace(), System.Xml.Xsl.XsltOld.RecordBuilder.DeclareNewNamespace(), System.Xml.Xsl.XsltOld.RecordBuilder.FixupAttributes(), and System.Xml.Xsl.XsltOld.RecordBuilder.FixupElement().