Terraria: System.Xml.Xsl.XsltOld.RecordBuilder.DeclareNewNamespace
DeclareNewNamespace()
string System.Xml.Xsl.XsltOld.RecordBuilder.DeclareNewNamespace (string nspace) inline private
Definition at line 628 of file RecordBuilder.cs.
    {
        string text = _scopeManager.GeneratePrefix("xp_{0}");
        DeclareNamespace(nspace, text);
        return text;
    }
References System.Xml.Xsl.XsltOld.RecordBuilder._scopeManager, System.Xml.Xsl.XsltOld.RecordBuilder.DeclareNamespace(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.OutputScopeManager.GeneratePrefix(), and System.text.
Referenced by System.Xml.Xsl.XsltOld.RecordBuilder.GetPrefixForNamespace().