Terraria: System.Xml.Xsl.XsltOld.RecordBuilder.BeginAttribute
BeginAttribute()
void System.Xml.Xsl.XsltOld.RecordBuilder.BeginAttribute (string prefix, string name, string nspace, object htmlAttrProps, bool search) inline private
Definition at line 246 of file RecordBuilder.cs.
    {
        int num = FindAttribute(name, nspace, ref prefix);
        if (num == -1)
        {
            num = NewAttribute();
        }
        BuilderInfo builderInfo = (BuilderInfo)_attributeList[num];
        builderInfo.Initialize(prefix, name, nspace);
        builderInfo.Depth = _recordDepth;
        builderInfo.NodeType = XmlNodeType.Attribute;
        builderInfo.htmlAttrProps = htmlAttrProps as HtmlAttributeProps;
        builderInfo.search = search;
        _currentInfo = builderInfo;
    }
References System.Xml.Xsl.XsltOld.RecordBuilder._attributeList, System.Xml.Xsl.XsltOld.RecordBuilder._currentInfo, System.Xml.Xsl.XsltOld.RecordBuilder._recordDepth, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.RecordBuilder.FindAttribute(), System.Xml.Xsl.XsltOld.RecordBuilder.NewAttribute(), and System.prefix.
Referenced by System.Xml.Xsl.XsltOld.RecordBuilder.BeginEvent().