Terraria: System.Xml.Xsl.XsltOld.RecordBuilder.FixupElement
FixupElement()
void System.Xml.Xsl.XsltOld.RecordBuilder.FixupElement () inline private
Definition at line 397 of file RecordBuilder.cs.
    {
        if (Ref.Equal(_mainNode.NamespaceURI, _atoms.Empty))
        {
            _mainNode.Prefix = _atoms.Empty;
        }
        if (Ref.Equal(_mainNode.Prefix, _atoms.Empty))
        {
            if (!Ref.Equal(_mainNode.NamespaceURI, _scopeManager.DefaultNamespace))
            {
                DeclareNamespace(_mainNode.NamespaceURI, _mainNode.Prefix);
            }
        }
        else
        {
            bool thisScope = false;
            string text = _scopeManager.ResolveNamespace(_mainNode.Prefix, out thisScope);
            if (text != null)
            {
                if (!Ref.Equal(_mainNode.NamespaceURI, text))
                {
                    if (thisScope)
                    {
                        _mainNode.Prefix = GetPrefixForNamespace(_mainNode.NamespaceURI);
                    }
                    else
                    {
                        DeclareNamespace(_mainNode.NamespaceURI, _mainNode.Prefix);
                    }
                }
            }
            else
            {
                DeclareNamespace(_mainNode.NamespaceURI, _mainNode.Prefix);
            }
        }
        OutputScope currentElementScope = _scopeManager.CurrentElementScope;
        currentElementScope.Prefix = _mainNode.Prefix;
    }
References System.Xml.Xsl.XsltOld.RecordBuilder._atoms, System.Xml.Xsl.XsltOld.RecordBuilder._mainNode, System.Xml.Xsl.XsltOld.RecordBuilder._scopeManager, System.Xml.Xsl.XsltOld.OutputScopeManager.CurrentElementScope, System.Xml.Xsl.XsltOld.RecordBuilder.DeclareNamespace(), System.Xml.Xsl.XsltOld.OutputScopeManager.DefaultNamespace, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.OutKeywords.Empty, System.Xml.Ref.Equal(), System.Xml.Xsl.XsltOld.RecordBuilder.GetPrefixForNamespace(), System.Xml.Xsl.XsltOld.BuilderInfo.NamespaceURI, System.Xml.Xsl.XsltOld.BuilderInfo.Prefix, System.Xml.Xsl.XsltOld.OutputScopeManager.ResolveNamespace(), and System.text.
Referenced by System.Xml.Xsl.XsltOld.RecordBuilder.FinalizeRecord().