Terraria: System.Xml.Xsl.XsltOld.RecordBuilder.BeginEvent
BeginEvent()
Processor.OutputResult System.Xml.Xsl.XsltOld.RecordBuilder.BeginEvent (int state, XPathNodeType nodeType, string prefix, string name, string nspace, bool empty, object htmlProps, bool search) inline package
Definition at line 100 of file RecordBuilder.cs.
    {
        if (!CanOutput(state))
        {
            return Processor.OutputResult.Overflow;
        }
        AdjustDepth(state);
        ResetRecord(state);
        PopElementScope();
        prefix = ((prefix != null) ? _nameTable.Add(prefix) : _atoms.Empty);
        name = ((name != null) ? _nameTable.Add(name) : _atoms.Empty);
        nspace = ((nspace != null) ? _nameTable.Add(nspace) : _atoms.Empty);
        switch (nodeType)
        {
        case XPathNodeType.Element:
            _mainNode.htmlProps = htmlProps as HtmlElementProps;
            _mainNode.search = search;
            BeginElement(prefix, name, nspace, empty);
            break;
        case XPathNodeType.Attribute:
            BeginAttribute(prefix, name, nspace, htmlProps, search);
            break;
        case XPathNodeType.Namespace:
            BeginNamespace(name, nspace);
            break;
        case XPathNodeType.ProcessingInstruction:
            if (!BeginProcessingInstruction(prefix, name, nspace))
            {
                return Processor.OutputResult.Error;
            }
            break;
        case XPathNodeType.Comment:
            BeginComment();
            break;
        }
        return CheckRecordBegin(state);
    }
References System.Xml.Xsl.XsltOld.RecordBuilder._atoms, System.Xml.Xsl.XsltOld.RecordBuilder._nameTable, System.Xml.XmlNameTable.Add(), System.Xml.Xsl.XsltOld.RecordBuilder.AdjustDepth(), System.Xml.Xsl.XsltOld.RecordBuilder.BeginAttribute(), System.Xml.Xsl.XsltOld.RecordBuilder.BeginComment(), System.Xml.Xsl.XsltOld.RecordBuilder.BeginElement(), System.Xml.Xsl.XsltOld.RecordBuilder.BeginNamespace(), System.Xml.Xsl.XsltOld.RecordBuilder.BeginProcessingInstruction(), System.Xml.Xsl.XsltOld.RecordBuilder.CanOutput(), System.Xml.Xsl.XsltOld.RecordBuilder.CheckRecordBegin(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.OutKeywords.Empty, System.Xml.Xsl.XsltOld.RecordBuilder.PopElementScope(), System.prefix, System.Xml.Xsl.XsltOld.RecordBuilder.ResetRecord(), and System.state.
Referenced by System.Xml.Xsl.XsltOld.Processor.BeginEvent().