Terraria: System.Xml.Xsl.XsltOld.RecordBuilder.TextEvent
TextEvent()
Processor.OutputResult System.Xml.Xsl.XsltOld.RecordBuilder.TextEvent (int state, string text, bool disableOutputEscaping) inline package
Definition at line 138 of file RecordBuilder.cs.
    {
        if (!CanOutput(state))
        {
            return Processor.OutputResult.Overflow;
        }
        AdjustDepth(state);
        ResetRecord(state);
        PopElementScope();
        if (((uint)state & 0x2000u) != 0)
        {
            _currentInfo.Depth = _recordDepth;
            _currentInfo.NodeType = XmlNodeType.Text;
        }
        ValueAppend(text, disableOutputEscaping);
        return CheckRecordBegin(state);
    }
References System.Xml.Xsl.XsltOld.RecordBuilder._recordDepth, System.Xml.Xsl.XsltOld.RecordBuilder.AdjustDepth(), System.Xml.Xsl.XsltOld.RecordBuilder.CanOutput(), System.Xml.Xsl.XsltOld.RecordBuilder.CheckRecordBegin(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.RecordBuilder.PopElementScope(), System.Xml.Xsl.XsltOld.RecordBuilder.ResetRecord(), System.state, System.text, and System.Xml.Xsl.XsltOld.RecordBuilder.ValueAppend().
Referenced by System.Xml.Xsl.XsltOld.Processor.TextEvent().