Terraria: System.Xml.Xsl.XsltOld.RecordBuilder.ResetRecord
ResetRecord()
void System.Xml.Xsl.XsltOld.RecordBuilder.ResetRecord (int state) inline private
Definition at line 320 of file RecordBuilder.cs.
    {
        if (((uint)state & 0x2000u) != 0)
        {
            _attributeCount = 0;
            _namespaceCount = 0;
            _currentInfo = _mainNode;
            _currentInfo.Initialize(_atoms.Empty, _atoms.Empty, _atoms.Empty);
            _currentInfo.NodeType = XmlNodeType.None;
            _currentInfo.IsEmptyTag = false;
            _currentInfo.htmlProps = null;
            _currentInfo.htmlAttrProps = null;
        }
    }
References System.Xml.Xsl.XsltOld.RecordBuilder._atoms, System.Xml.Xsl.XsltOld.RecordBuilder._attributeCount, System.Xml.Xsl.XsltOld.RecordBuilder._currentInfo, System.Xml.Xsl.XsltOld.RecordBuilder._mainNode, System.Xml.Xsl.XsltOld.RecordBuilder._namespaceCount, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.OutKeywords.Empty, System.Xml.Xsl.XsltOld.BuilderInfo.Initialize(), and System.state.
Referenced by System.Xml.Xsl.XsltOld.RecordBuilder.BeginEvent(), System.Xml.Xsl.XsltOld.RecordBuilder.EndEvent(), and System.Xml.Xsl.XsltOld.RecordBuilder.TextEvent().