Terraria: System.Text.ValueStringBuilder.Insert
Insert() [2/2]
void System.Text.ValueStringBuilder.Insert (int index, string s) inline
Definition at line 344 of file ValueStringBuilder.cs.
    {
        if (s != null)
        {
            int length = s.Length;
            if (_pos > _chars.Length - length)
            {
                Grow(length);
            }
            int length2 = _pos - index;
            _chars.Slice(index, length2).CopyTo(_chars.Slice(index + length));
            s.CopyTo(_chars.Slice(index));
            _pos += length;
        }
    }
References System.Text.ValueStringBuilder._chars, System.Text.ValueStringBuilder._pos, System.Text.ValueStringBuilder.Grow(), System.index, System.length, System.Span< T >.Length, System.length2, System.s, and System.Span< T >.Slice().
Referenced by System.Numerics.BigNumber.FormatBigIntegerToHex().