Terraria: System.Text.ValueStringBuilder.AsSpan
AsSpan() [4/8]
ReadOnlySpan< char > System.Text.ValueStringBuilder.AsSpan (bool terminate) inline
Definition at line 306 of file ValueStringBuilder.cs.
    {
        if (terminate)
        {
            EnsureCapacity(Length + 1);
            _chars[Length] = '\0';
        }
        return _chars.Slice(0, _pos);
    }
References System.Text.ValueStringBuilder._chars, System.Text.ValueStringBuilder._pos, System.Text.ValueStringBuilder.EnsureCapacity(), System.Text.ValueStringBuilder.Length, and System.Span< T >.Slice().
Referenced by System.Text.Encodings.Web.TextEncoder.EncodeToNewString(), System.IO.PathHelper.Normalize(), System.IO.PathHelper.Normalize(), and System.UriHelper.UnescapeString().