Terraria: System.Text.ValueStringBuilder.AppendFormatHelper
AppendFormatHelper()
void System.Text.ValueStringBuilder.AppendFormatHelper (IFormatProvider provider, string format, ParamsArray args) inline package
Definition at line 45 of file ValueStringBuilder.cs.
    {
        if (format == null)
        {
            throw new ArgumentNullException("format");
        }
        int num = 0;
        int length = format.Length;
        char c = '\0';
        ICustomFormatter customFormatter = (ICustomFormatter)(provider?.GetFormat(typeof(ICustomFormatter)));
        while (true)
        {
            if (num < length)
            {
                c = format[num];
                num++;
                if (c == '}')
                {
                    if (num < length && format[num] == '}')
                    {
                        num++;
                    }
                    else
                    {
                        ThrowFormatError();
                    }
                }
                else if (c == '{')
                {
                    if (num >= length || format[num] != '{')
                    {
                        num--;
                        goto IL_008f;
                    }
                    num++;
                }
                Append(c);
                continue;
            }
            goto IL_008f;
            IL_008f:
            if (num == length)
            {
                break;
            }
            num++;
            if (num == length || (c = format[num]) < '0' || c > '9')
            {
                ThrowFormatError();
            }
            int num2 = 0;
            do
            {
                num2 = num2 * 10 + c - 48;
                num++;
                if (num == length)
                {
                    ThrowFormatError();
                }
                c = format[num];
            }
            while (c >= '0' && c <= '9' && num2 < 1000000);
            if (num2 >= args.Length)
            {
                throw new FormatException(SR.Format_IndexOutOfRange);
            }
            for (; num < length; num++)
            {
                if ((c = format[num]) != ' ')
                {
                    break;
                }
            }
            bool flag = false;
            int num3 = 0;
            if (c == ',')
            {
                for (num++; num < length && format[num] == ' '; num++)
                {
                }
                if (num == length)
                {
                    ThrowFormatError();
                }
                c = format[num];
                if (c == '-')
                {
                    flag = true;
                    num++;
                    if (num == length)
                    {
                        ThrowFormatError();
                    }
                    c = format[num];
                }
                if (c < '0' || c > '9')
                {
                    ThrowFormatError();
                }
                do
                {
                    num3 = num3 * 10 + c - 48;
                    num++;
                    if (num == length)
                    {
                        ThrowFormatError();
                    }
                    c = format[num];
                }
                while (c >= '0' && c <= '9' && num3 < 1000000);
            }
            for (; num < length; num++)
            {
                if ((c = format[num]) != ' ')
                {
                    break;
                }
            }
            object obj = args[num2];
            ReadOnlySpan<char> readOnlySpan = default(ReadOnlySpan<char>);
            switch (c)
            {
            case ':':
            {
                num++;
                int num4 = num;
                while (true)
                {
                    if (num == length)
                    {
                        ThrowFormatError();
                    }
                    c = format[num];
                    switch (c)
                    {
                    case '{':
                        ThrowFormatError();
                        goto IL_0205;
                    default:
                        goto IL_0205;
                    case '}':
                        break;
                    }
                    break;
                    IL_0205:
                    num++;
                }
                if (num > num4)
                {
                    readOnlySpan = format.AsSpan(num4, num - num4);
                }
                break;
            }
            default:
                ThrowFormatError();
                break;
            case '}':
                break;
            }
            num++;
            string text = null;
            string text2 = null;
            if (customFormatter != null)
            {
                if (readOnlySpan.Length != 0)
                {
                    text2 = new string(readOnlySpan);
                }
                text = customFormatter.Format(text2, obj, provider);
            }
            if (text == null)
            {
                if (obj is ISpanFormattable spanFormattable && (flag || num3 == 0) && spanFormattable.TryFormat(_chars.Slice(_pos), out var charsWritten, readOnlySpan, provider))
                {
                    _pos += charsWritten;
                    int num5 = num3 - charsWritten;
                    if (flag && num5 > 0)
                    {
                        Append(' ', num5);
                    }
                    continue;
                }
                if (obj is IFormattable formattable)
                {
                    if (readOnlySpan.Length != 0 && text2 == null)
                    {
                        text2 = new string(readOnlySpan);
                    }
                    text = formattable.ToString(text2, provider);
                }
                else if (obj != null)
                {
                    text = obj.ToString();
                }
            }
            if (text == null)
            {
                text = string.Empty;
            }
            int num6 = num3 - text.Length;
            if (!flag && num6 > 0)
            {
                Append(' ', num6);
            }
            Append(text);
            if (flag && num6 > 0)
            {
                Append(' ', num6);
            }
        }
    }
References System.Text.ValueStringBuilder._chars, System.Text.ValueStringBuilder._pos, System.Text.ValueStringBuilder.Append(), System.format, System.ICustomFormatter.Format(), System.SR.Format_IndexOutOfRange, System.length, System.ParamsArray.Length, System.ReadOnlySpan< T >.Length, System.obj, System.Span< T >.Slice(), System.text, System.Text.ValueStringBuilder.ThrowFormatError(), and System.ISpanFormattable.TryFormat().