Terraria: ItemSlot.DrawItemIcon
DrawItemIcon()
static float ItemSlot.DrawItemIcon (Item item, int context, SpriteBatch spriteBatch, Vector2 screenPositionForItemCenter, float scale, float sizeLimit, Color environmentColor) inline static
     {
         int num = item.type;
         if ((uint)(num - 5358) <= 3u && context == 31)
         {
             num = 5437;
         }
         Main.instance.LoadItem(num);
         Texture2D value = TextureAssets.Item[num].Value;
         Rectangle frame = ((Main.itemAnimations[num] == null) ? value.Frame() : Main.itemAnimations[num].GetFrame(value));
         DrawItem_GetColorAndScale(item, scale, ref environmentColor, sizeLimit, ref frame, out var itemLight, out var finalDrawScale);
         SpriteEffects effects = SpriteEffects.None;
         Vector2 origin = frame.Size() / 2f;
         spriteBatch.Draw(value, screenPositionForItemCenter, frame, item.GetAlpha(itemLight), 0f, origin, finalDrawScale, effects, 0f);
         if (item.color != Color.Transparent)
         {
             Color newColor = environmentColor;
             if (context == 13)
             {
                 newColor.A = byte.MaxValue;
             }
             spriteBatch.Draw(value, screenPositionForItemCenter, frame, item.GetColor(newColor), 0f, origin, finalDrawScale, effects, 0f);
         }
         switch (num)
         {
         case 5140:
         case 5141:
         case 5142:
         case 5143:
         case 5144:
         case 5145:
         {
             Texture2D value3 = TextureAssets.GlowMask[item.glowMask].Value;
             Color white = Color.White;
             spriteBatch.Draw(value3, screenPositionForItemCenter, frame, white, 0f, origin, finalDrawScale, effects, 0f);
             break;
         }
         case 5146:
         {
             Texture2D value2 = TextureAssets.GlowMask[324].Value;
             spriteBatch.Draw(color: new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB), texture: value2, position: screenPositionForItemCenter, sourceRectangle: frame, rotation: 0f, origin: origin, scale: finalDrawScale, effects: effects, layerDepth: 0f);
             break;
         }
         }
         return finalDrawScale;
     }
References Color, Item.color, Main.DiscoB, Main.DiscoG, Main.DiscoR, DrawItem_GetColorAndScale(), Item.GetAlpha(), Item.GetColor(), DrawAnimation.GetFrame(), TextureAssets.GlowMask, Item.glowMask, Main.instance, TextureAssets.Item, Main.itemAnimations, Main.LoadItem(), Item.type, and Asset< T >.Value.
Referenced by ItemTransferParticle.Draw(), Draw(), UIItemIcon.DrawSelf(), and TileDrawing.DrawSpecialTilesLegacy().