Terraria: ItemSlot.RightClick
RightClick() [1/2]
static void ItemSlot.RightClick (Item[] inv, int context = 0, int slot = 0) inline static
     {
         Player player = Main.player[Main.myPlayer];
         inv[slot].newAndShiny = false;
         if (player.itemAnimation > 0)
         {
             return;
         }
         if (context == 15)
         {
             HandleShopSlot(inv, slot, rightClickIsValid: true, leftClickIsValid: false);
         }
         else
         {
             if (!Main.mouseRight)
             {
                 return;
             }
             if (context == 0 && Main.mouseRightRelease)
             {
                 TryItemSwap(inv[slot]);
             }
             if (context == 0 && ItemID.Sets.OpenableBag[inv[slot].type])
             {
                 if (Main.mouseRightRelease)
                 {
                     TryOpenContainer(inv[slot], player);
                 }
                 return;
             }
             switch (context)
             {
             case 9:
             case 11:
                 if (Main.mouseRightRelease)
                 {
                     SwapVanityEquip(inv, context, slot, player);
                 }
                 break;
             case 12:
             case 25:
             case 27:
             case 33:
                 if (Main.mouseRightRelease)
                 {
                     TryPickupDyeToCursor(context, inv, slot, player);
                 }
                 break;
             case 0:
             case 3:
             case 4:
             case 32:
                 if (inv[slot].maxStack == 1)
                 {
                     if (Main.mouseRightRelease)
                     {
                         SwapEquip(inv, context, slot);
                     }
                     break;
                 }
                 goto default;
             default:
             {
                 if (Main.stackSplit > 1)
                 {
                     break;
                 }
                 bool flag = true;
                 bool flag2 = inv[slot].maxStack <= 1 && inv[slot].stack <= 1;
                 if (context == 0 && flag2)
                 {
                     flag = false;
                 }
                 if (context == 3 && flag2)
                 {
                     flag = false;
                 }
                 if (context == 4 && flag2)
                 {
                     flag = false;
                 }
                 if (context == 32 && flag2)
                 {
                     flag = false;
                 }
                 if (!flag)
                 {
                     break;
                 }
                 int num = Main.superFastStack + 1;
                 for (int i = 0; i < num; i++)
                 {
                     if ((Main.mouseItem.IsTheSameAs(inv[slot]) || Main.mouseItem.type == 0) && (Main.mouseItem.stack < Main.mouseItem.maxStack || Main.mouseItem.type == 0))
                     {
                         PickupItemIntoMouse(inv, context, slot, player);
                         SoundEngine.PlaySound(12);
                         RefreshStackSplitCooldown();
                     }
                 }
                 break;
             }
             }
         }
     }
References HandleShopSlot(), Item.IsTheSameAs(), Player.itemAnimation, Item.maxStack, Main.mouseItem, Main.mouseRight, Main.mouseRightRelease, Main.myPlayer, Item.newAndShiny, ItemID.Sets.OpenableBag, PickupItemIntoMouse(), Main.player, SoundEngine.PlaySound(), RefreshStackSplitCooldown(), Item.stack, Main.stackSplit, Main.superFastStack, SwapEquip(), SwapVanityEquip(), TryItemSwap(), TryOpenContainer(), TryPickupDyeToCursor(), and Item.type.