Terraria: ItemSlot.TryPickupDyeToCursor
TryPickupDyeToCursor()
static void ItemSlot.TryPickupDyeToCursor (int context, Item[] inv, int slot, Player player) inline static private
     {
         bool flag = false;
         if (!flag && ((Main.mouseItem.stack < Main.mouseItem.maxStack && Main.mouseItem.type > 0) || Main.mouseItem.IsAir) && inv[slot].type > 0 && (Main.mouseItem.type == inv[slot].type || Main.mouseItem.IsAir))
         {
             flag = true;
             if (Main.mouseItem.IsAir)
             {
                 Main.mouseItem = inv[slot].Clone();
             }
             else
             {
                 Main.mouseItem.stack++;
             }
             inv[slot].SetDefaults();
             SoundEngine.PlaySound(7);
         }
         if (flag)
         {
             if (context == 25 && Main.netMode == 1)
             {
                 NetMessage.SendData(121, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot, 1f);
             }
             if (context == 27 && Main.netMode == 1)
             {
                 NetMessage.SendData(124, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot, 1f);
             }
         }
     }
References Item.Clone(), PlayerInteractionAnchor.interactEntityID, Item.IsAir, Item.maxStack, Main.mouseItem, Main.myPlayer, Main.netMode, SoundEngine.PlaySound(), NetMessage.SendData(), Item.SetDefaults(), Item.stack, Player.tileEntityAnchor, and Item.type.
Referenced by RightClick().