Terraria: ItemSlot.PickItemMovementAction
PickItemMovementAction()
static int ItemSlot.PickItemMovementAction (Item[] inv, int context, int slot, Item checkItem) inline static
     {
         _ = Main.player[Main.myPlayer];
         int result = -1;
         switch (context)
         {
         case 0:
             result = 0;
             break;
         case 1:
             if (checkItem.type == 0 || checkItem.type == 71 || checkItem.type == 72 || checkItem.type == 73 || checkItem.type == 74)
             {
                 result = 0;
             }
             break;
         case 2:
             if (checkItem.FitsAmmoSlot())
             {
                 result = 0;
             }
             break;
         case 3:
             result = 0;
             break;
         case 4:
         case 32:
         {
             ChestUI.GetContainerUsageInfo(out var _, out var chestinv);
             if (!ChestUI.IsBlockedFromTransferIntoChest(checkItem, chestinv))
             {
                 result = 0;
             }
             break;
         }
         case 5:
             if (checkItem.Prefix(-3) || checkItem.type == 0)
             {
                 result = 0;
             }
             break;
         case 6:
             result = 0;
             break;
         case 7:
             if (checkItem.material || checkItem.type == 0)
             {
                 result = 0;
             }
             break;
         case 8:
             if (checkItem.type == 0 || (checkItem.headSlot > -1 && slot == 0) || (checkItem.bodySlot > -1 && slot == 1) || (checkItem.legSlot > -1 && slot == 2))
             {
                 result = 1;
             }
             break;
         case 23:
             if (checkItem.type == 0 || (checkItem.headSlot > 0 && slot == 0) || (checkItem.bodySlot > 0 && slot == 1) || (checkItem.legSlot > 0 && slot == 2))
             {
                 result = 1;
             }
             break;
         case 26:
             if (checkItem.type == 0 || checkItem.headSlot > 0)
             {
                 result = 1;
             }
             break;
         case 9:
             if (checkItem.type == 0 || (checkItem.headSlot > -1 && slot == 10) || (checkItem.bodySlot > -1 && slot == 11) || (checkItem.legSlot > -1 && slot == 12))
             {
                 result = 1;
             }
             break;
         case 10:
             if (checkItem.type == 0 || (checkItem.accessory && !AccCheck(Main.LocalPlayer.armor, checkItem, slot)))
             {
                 result = 1;
             }
             break;
         case 24:
             if (checkItem.type == 0 || (checkItem.accessory && !AccCheck(inv, checkItem, slot)))
             {
                 result = 1;
             }
             break;
         case 11:
             if (checkItem.type == 0 || (checkItem.accessory && !AccCheck(Main.LocalPlayer.armor, checkItem, slot)))
             {
                 result = 1;
             }
             break;
         case 12:
         case 25:
         case 27:
         case 33:
             result = 2;
             break;
         case 15:
             if (checkItem.type == 0 && inv[slot].type > 0)
             {
                 result = 3;
             }
             else if (checkItem.type == inv[slot].type && checkItem.type > 0 && checkItem.stack < checkItem.maxStack && inv[slot].stack > 0)
             {
                 result = 3;
             }
             else if (inv[slot].type == 0 && checkItem.type > 0 && (checkItem.type < 71 || checkItem.type > 74))
             {
                 result = 4;
             }
             break;
         case 16:
             if (checkItem.type == 0 || Main.projHook[checkItem.shoot])
             {
                 result = 1;
             }
             break;
         case 17:
             if (checkItem.type == 0 || (checkItem.mountType != -1 && !MountID.Sets.Cart[checkItem.mountType]))
             {
                 result = 1;
             }
             break;
         case 19:
             if (checkItem.type == 0 || (checkItem.buffType > 0 && Main.vanityPet[checkItem.buffType] && !Main.lightPet[checkItem.buffType]))
             {
                 result = 1;
             }
             break;
         case 18:
             if (checkItem.type == 0 || (checkItem.mountType != -1 && MountID.Sets.Cart[checkItem.mountType]))
             {
                 result = 1;
             }
             break;
         case 20:
             if (checkItem.type == 0 || (checkItem.buffType > 0 && Main.lightPet[checkItem.buffType]))
             {
                 result = 1;
             }
             break;
         case 29:
             if (checkItem.type == 0 && inv[slot].type > 0)
             {
                 result = 5;
             }
             break;
         }
         if (context == 30)
         {
             result = 0;
         }
         return result;
     }
References AccCheck(), Item.accessory, Player.armor, Item.bodySlot, Item.buffType, MountID.Sets.Cart, Item.FitsAmmoSlot(), ChestUI.GetContainerUsageInfo(), Item.headSlot, ChestUI.IsBlockedFromTransferIntoChest(), Item.legSlot, Main.lightPet, Main.LocalPlayer, Item.material, Item.maxStack, Item.mountType, Main.myPlayer, Main.player, Item.Prefix(), Main.projHook, Item.shoot, Item.stack, Item.type, and Main.vanityPet.
Referenced by LeftClick(), and ChestUI.Restock().