Terraria: ItemSlot.SetGlow
SetGlow()
static void ItemSlot.SetGlow (int index, float hue, bool chest) inline static
     {
         if (chest)
         {
             if (hue < 0f)
             {
                 inventoryGlowTimeChest[index] = 0;
                 inventoryGlowHueChest[index] = 0f;
             }
             else
             {
                 inventoryGlowTimeChest[index] = 300;
                 inventoryGlowHueChest[index] = hue;
             }
         }
         else
         {
             inventoryGlowTime[index] = 300;
             inventoryGlowHue[index] = hue;
         }
     }
References inventoryGlowHue, inventoryGlowHueChest, inventoryGlowTime, and inventoryGlowTimeChest.
Referenced by ItemSorting.FillAmmoFromInventory(), Player.OpenChest(), ItemSorting.Sort(), Main.TryInteractingWithMoneyTrough(), and Main.TryInteractingWithVoidLens().