Terraria: ItemSlot.SellOrTrash
SellOrTrash()
static void ItemSlot.SellOrTrash (Item[] inv, int context, int slot) inline static private
     {
         Player player = Main.player[Main.myPlayer];
         if (inv[slot].type <= 0)
         {
             return;
         }
         if (Main.npcShop > 0 && !inv[slot].favorited)
         {
             Chest chest = Main.instance.shop[Main.npcShop];
             if (inv[slot].type < 71 || inv[slot].type > 74)
             {
                 if (player.SellItem(inv[slot]))
                 {
                     chest.AddItemToShop(inv[slot]);
                     AnnounceTransfer(new ItemTransferInfo(inv[slot], context, 15));
                     inv[slot].TurnToAir();
                     SoundEngine.PlaySound(18);
                     Recipe.FindRecipes();
                 }
                 else if (inv[slot].value == 0)
                 {
                     chest.AddItemToShop(inv[slot]);
                     AnnounceTransfer(new ItemTransferInfo(inv[slot], context, 15));
                     inv[slot].TurnToAir();
                     SoundEngine.PlaySound(7);
                     Recipe.FindRecipes();
                 }
             }
         }
         else if (!inv[slot].favorited)
         {
             SoundEngine.PlaySound(7);
             player.trashItem = inv[slot].Clone();
             AnnounceTransfer(new ItemTransferInfo(player.trashItem, context, 6));
             inv[slot].TurnToAir();
             if (context == 3 && Main.netMode == 1)
             {
                 NetMessage.SendData(32, -1, -1, null, player.chest, slot);
             }
             Recipe.FindRecipes();
         }
     }
References Chest.AddItemToShop(), AnnounceTransfer(), Player.chest, Item.Clone(), Item.favorited, Recipe.FindRecipes(), Main.instance, Main.myPlayer, Main.netMode, Main.npcShop, Main.player, SoundEngine.PlaySound(), Player.SellItem(), NetMessage.SendData(), Main.shop, Player.trashItem, and Item.TurnToAir().
Referenced by LeftClick_SellOrTrash().