Terraria: ItemSlot.GetGamepadInstructions
GetGamepadInstructions() [1/2]
static string ItemSlot.GetGamepadInstructions (Item[] inv, int context = 0, int slot = 0) inline static
     {
         Player player = Main.player[Main.myPlayer];
         string s = "";
         if (inv == null || inv[slot] == null || Main.mouseItem == null)
         {
             return s;
         }
         if (context == 0 || context == 1 || context == 2)
         {
             if (inv[slot].type > 0 && inv[slot].stack > 0)
             {
                 if (Main.mouseItem.type > 0)
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                     if (inv[slot].type == Main.mouseItem.type && Main.mouseItem.stack < inv[slot].maxStack && inv[slot].maxStack > 1)
                     {
                         s += PlayerInput.BuildCommand(Lang.misc[55].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"]);
                     }
                 }
                 else
                 {
                     if (context == 0 && player.chest == -1 && PlayerInput.AllowExecutionOfGamepadInstructions)
                     {
                         player.DpadRadial.ChangeBinding(slot);
                     }
                     s += PlayerInput.BuildCommand(Lang.misc[54].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                     if (inv[slot].maxStack > 1)
                     {
                         s += PlayerInput.BuildCommand(Lang.misc[55].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"]);
                     }
                 }
                 if (inv[slot].maxStack == 1 && Equippable(inv, context, slot))
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[67].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"]);
                     if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
                     {
                         SwapEquip(inv, context, slot);
                         PlayerInput.LockGamepadButtons("Grapple");
                         PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                     }
                 }
                 s += PlayerInput.BuildCommand(Lang.misc[83].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["SmartCursor"]);
                 if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartCursor)
                 {
                     inv[slot].favorited = !inv[slot].favorited;
                     PlayerInput.LockGamepadButtons("SmartCursor");
                     PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                 }
             }
             else if (Main.mouseItem.type > 0)
             {
                 s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
             }
         }
         if (context == 3 || context == 4 || context == 32)
         {
             if (inv[slot].type > 0 && inv[slot].stack > 0)
             {
                 if (Main.mouseItem.type > 0)
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                     if (inv[slot].type == Main.mouseItem.type && Main.mouseItem.stack < inv[slot].maxStack && inv[slot].maxStack > 1)
                     {
                         s += PlayerInput.BuildCommand(Lang.misc[55].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"]);
                     }
                 }
                 else
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[54].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                     if (inv[slot].maxStack > 1)
                     {
                         s += PlayerInput.BuildCommand(Lang.misc[55].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"]);
                     }
                 }
                 if (inv[slot].maxStack == 1 && Equippable(inv, context, slot))
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[67].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"]);
                     if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
                     {
                         SwapEquip(inv, context, slot);
                         PlayerInput.LockGamepadButtons("Grapple");
                         PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                     }
                 }
                 if (context == 32)
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[83].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["SmartCursor"]);
                     if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartCursor)
                     {
                         inv[slot].favorited = !inv[slot].favorited;
                         PlayerInput.LockGamepadButtons("SmartCursor");
                         PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                     }
                 }
             }
             else if (Main.mouseItem.type > 0)
             {
                 s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
             }
         }
         if (context == 15)
         {
             if (inv[slot].type > 0 && inv[slot].stack > 0)
             {
                 if (Main.mouseItem.type > 0)
                 {
                     if (inv[slot].type == Main.mouseItem.type && Main.mouseItem.stack < inv[slot].maxStack && inv[slot].maxStack > 1)
                     {
                         s += PlayerInput.BuildCommand(Lang.misc[91].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"]);
                     }
                 }
                 else
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[90].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"], PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"]);
                 }
             }
             else if (Main.mouseItem.type > 0)
             {
                 s += PlayerInput.BuildCommand(Lang.misc[92].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
             }
         }
         if (context == 8 || context == 9 || context == 16 || context == 17 || context == 18 || context == 19 || context == 20)
         {
             if (inv[slot].type > 0 && inv[slot].stack > 0)
             {
                 if (Main.mouseItem.type > 0)
                 {
                     if (Equippable(ref Main.mouseItem, context))
                     {
                         s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                     }
                 }
                 else if (context != 8 || !isEquipLocked(inv[slot].type))
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[54].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                 }
                 if (context == 8 && slot >= 3)
                 {
                     bool flag = player.hideVisibleAccessory[slot];
                     s += PlayerInput.BuildCommand(Lang.misc[flag ? 77 : 78].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"]);
                     if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
                     {
                         player.hideVisibleAccessory[slot] = !player.hideVisibleAccessory[slot];
                         SoundEngine.PlaySound(12);
                         if (Main.netMode == 1)
{
                             NetMessage.SendData(4, -1, -1, null, Main.myPlayer);
                         }
                         PlayerInput.LockGamepadButtons("Grapple");
                         PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                     }
                 }
                 if ((context == 16 || context == 17 || context == 18 || context == 19 || context == 20) && slot < 2)
                 {
                     bool flag2 = player.hideMisc[slot];
                     s += PlayerInput.BuildCommand(Lang.misc[flag2 ? 77 : 78].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"]);
                     if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
                     {
                         if (slot == 0)
{
                             player.TogglePet();
                         }
                         if (slot == 1)
{
                             player.ToggleLight();
                         }
                         SoundEngine.PlaySound(12);
                         if (Main.netMode == 1)
{
                             NetMessage.SendData(4, -1, -1, null, Main.myPlayer);
                         }
                         PlayerInput.LockGamepadButtons("Grapple");
                         PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                     }
                 }
             }
             else
             {
                 if (Main.mouseItem.type > 0 && Equippable(ref Main.mouseItem, context))
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                 }
                 if (context == 8 && slot >= 3)
                 {
                     int num = slot;
                     if (num % 10 == 8 && !player.CanDemonHeartAccessoryBeShown())
                     {
                         num++;
                     }
                     bool flag3 = player.hideVisibleAccessory[num];
                     s += PlayerInput.BuildCommand(Lang.misc[flag3 ? 77 : 78].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"]);
                     if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
                     {
                         player.hideVisibleAccessory[num] = !player.hideVisibleAccessory[num];
                         SoundEngine.PlaySound(12);
                         if (Main.netMode == 1)
{
                             NetMessage.SendData(4, -1, -1, null, Main.myPlayer);
                         }
                         PlayerInput.LockGamepadButtons("Grapple");
                         PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                     }
                 }
                 if ((context == 16 || context == 17 || context == 18 || context == 19 || context == 20) && slot < 2)
                 {
                     bool flag4 = player.hideMisc[slot];
                     s += PlayerInput.BuildCommand(Lang.misc[flag4 ? 77 : 78].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"]);
                     if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
                     {
                         if (slot == 0)
{
                             player.TogglePet();
                         }
                         if (slot == 1)
{
                             player.ToggleLight();
                         }
                         Main.mouseLeftRelease = false;
                         SoundEngine.PlaySound(12);
                         if (Main.netMode == 1)
{
                             NetMessage.SendData(4, -1, -1, null, Main.myPlayer);
                         }
                         PlayerInput.LockGamepadButtons("Grapple");
                         PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                     }
                 }
             }
         }
         switch (context)
         {
         case 12:
         case 25:
         case 27:
         case 33:
             if (inv[slot].type > 0 && inv[slot].stack > 0)
             {
                 if (Main.mouseItem.type > 0)
                 {
                     if (Main.mouseItem.dye > 0)
                     {
                         s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                     }
                 }
                 else
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[54].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                 }
                 if (context == 12 || context == 25 || context == 27 || context == 33)
                 {
                     int num2 = -1;
                     if (inv == player.dye)
                     {
                         num2 = slot;
                     }
                     if (inv == player.miscDyes)
                     {
                         num2 = 10 + slot;
                     }
                     if (num2 != -1)
                     {
                         if (num2 < 10)
{
                             bool flag7 = player.hideVisibleAccessory[slot];
                             s += PlayerInput.BuildCommand(Lang.misc[flag7 ? 77 : 78].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"]);
                             if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                                 player.hideVisibleAccessory[slot] = !player.hideVisibleAccessory[slot];
                                 SoundEngine.PlaySound(12);
                                 if (Main.netMode == 1)
{
                                     NetMessage.SendData(4, -1, -1, null, Main.myPlayer);
                                 }
                                 PlayerInput.LockGamepadButtons("Grapple");
                                 PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                             }
                         }
                         else
{
                             bool flag8 = player.hideMisc[slot];
                             s += PlayerInput.BuildCommand(Lang.misc[flag8 ? 77 : 78].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"]);
                             if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                                 player.hideMisc[slot] = !player.hideMisc[slot];
                                 SoundEngine.PlaySound(12);
                                 if (Main.netMode == 1)
{
                                     NetMessage.SendData(4, -1, -1, null, Main.myPlayer);
                                 }
                                 PlayerInput.LockGamepadButtons("Grapple");
                                 PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                             }
                         }
                     }
                 }
             }
             else if (Main.mouseItem.type > 0 && Main.mouseItem.dye > 0)
             {
                 s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
             }
             return s;
         case 18:
         {
             if (inv[slot].type > 0 && inv[slot].stack > 0)
             {
                 if (Main.mouseItem.type > 0)
                 {
                     if (Main.mouseItem.dye > 0)
                     {
                         s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                     }
                 }
                 else
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[54].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                 }
             }
             else if (Main.mouseItem.type > 0 && Main.mouseItem.dye > 0)
             {
                 s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
             }
             bool enabledSuperCart = player.enabledSuperCart;
             s += PlayerInput.BuildCommand(Language.GetTextValue((!enabledSuperCart) ? "UI.EnableSuperCart" : "UI.DisableSuperCart"), false, PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"]);
             if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
             {
                 player.enabledSuperCart = !player.enabledSuperCart;
                 SoundEngine.PlaySound(12);
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(4, -1, -1, null, Main.myPlayer);
                 }
                 PlayerInput.LockGamepadButtons("Grapple");
                 PlayerInput.SettingsForUI.TryRevertingToMouseMode();
             }
             return s;
         }
         case 6:
             if (inv[slot].type > 0 && inv[slot].stack > 0)
             {
                 s = ((Main.mouseItem.type <= 0) ? (s + PlayerInput.BuildCommand(Lang.misc[54].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"])) : (s + PlayerInput.BuildCommand(Lang.misc[74].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"])));
             }
             else if (Main.mouseItem.type > 0)
             {
                 s += PlayerInput.BuildCommand(Lang.misc[74].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
             }
             return s;
         case 5:
         case 7:
         {
             bool flag6 = false;
             if (context == 5)
             {
                 flag6 = Main.mouseItem.Prefix(-3) || Main.mouseItem.type == 0;
             }
             if (context == 7)
             {
                 flag6 = Main.mouseItem.material;
             }
             if (inv[slot].type > 0 && inv[slot].stack > 0)
             {
                 if (Main.mouseItem.type > 0)
                 {
                     if (flag6)
                     {
                         s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                     }
                 }
                 else
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[54].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
                 }
             }
             else if (Main.mouseItem.type > 0 && flag6)
             {
                 s += PlayerInput.BuildCommand(Lang.misc[65].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"]);
             }
             return s;
         }
         default:
         {
             string overrideInstructions = GetOverrideInstructions(inv, context, slot);
             bool flag5 = Main.mouseItem.type > 0 && (context == 0 || context == 1 || context == 2 || context == 6 || context == 15 || context == 7 || context == 4 || context == 32 || context == 3);
             if (context != 8 || !isEquipLocked(inv[slot].type))
             {
                 if (flag5 && string.IsNullOrEmpty(overrideInstructions))
                 {
                     s += PlayerInput.BuildCommand(Lang.inter[121].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["SmartSelect"]);
                     if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartSelect)
                     {
                         player.DropSelectedItem();
                         PlayerInput.LockGamepadButtons("SmartSelect");
                         PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                     }
                 }
                 else if (!string.IsNullOrEmpty(overrideInstructions))
                 {
                     ShiftForcedOn = true;
                     int cursorOverride = Main.cursorOverride;
                     OverrideHover(inv, context, slot);
                     if (-1 != Main.cursorOverride)
                     {
                         s += PlayerInput.BuildCommand(overrideInstructions, false, PlayerInput.ProfileGamepadUI.KeyStatus["SmartSelect"]);
                         if (CanDoSimulatedClickAction() && CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartSelect)
{
                             bool mouseLeft = Main.mouseLeft;
                             Main.mouseLeft = true;
                             LeftClick(inv, context, slot);
                             Main.mouseLeft = mouseLeft;
                             PlayerInput.LockGamepadButtons("SmartSelect");
                             PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                         }
                     }
                     Main.cursorOverride = cursorOverride;
                     ShiftForcedOn = false;
                 }
             }
             if (!TryEnteringFastUseMode(inv, context, slot, player, ref s))
             {
                 TryEnteringBuildingMode(inv, context, slot, player, ref s);
             }
             return s;
         }
         }
     }
References PlayerInput.AllowExecutionOfGamepadInstructions, PlayerInput.BuildCommand(), Player.CanDemonHeartAccessoryBeShown(), CanDoSimulatedClickAction(), CanExecuteCommand(), Player.SelectionRadial.ChangeBinding(), Player.chest, Main.cursorOverride, Player.DpadRadial, Player.DropSelectedItem(), Item.dye, Player.dye, Player.enabledSuperCart, Equippable(), Item.favorited, GetOverrideInstructions(), Language.GetTextValue(), TriggersSet.Grapple, Player.hideMisc, Player.hideVisibleAccessory, Lang.inter, isEquipLocked(), TriggersPack.JustPressed, KeyConfiguration.KeyStatus, LeftClick(), PlayerInput.LockGamepadButtons(), Item.material, Item.maxStack, Lang.misc, Player.miscDyes, Main.mouseItem, Main.mouseLeft, Main.mouseLeftRelease, Main.myPlayer, Main.netMode, OverrideHover(), Main.player, SoundEngine.PlaySound(), Item.Prefix(), PlayerInput.ProfileGamepadUI, NetMessage.SendData(), ShiftForcedOn, TriggersSet.SmartCursor, TriggersSet.SmartSelect, Item.stack, SwapEquip(), Player.ToggleLight(), Player.TogglePet(), PlayerInput.Triggers, TryEnteringBuildingMode(), TryEnteringFastUseMode(), PlayerInput.SettingsForUI.TryRevertingToMouseMode(), Item.type, and LocalizedText.Value.