Terraria: ItemSlot.OverrideLeftClick
OverrideLeftClick()
static bool ItemSlot.OverrideLeftClick (Item[] inv, int context = 0, int slot = 0) inline static private
     {
         if (context == 10 && isEquipLocked(inv[slot].type))
         {
             return true;
         }
         if (Main.LocalPlayer.tileEntityAnchor.IsInValidUseTileEntity() && Main.LocalPlayer.tileEntityAnchor.GetTileEntity().OverrideItemSlotLeftClick(inv, context, slot))
         {
             return true;
         }
         Item item = inv[slot];
         if (Main.cursorOverride == 2)
         {
             if (ChatManager.AddChatText(FontAssets.MouseText.Value, ItemTagHandler.GenerateTag(item), Vector2.One))
             {
                 SoundEngine.PlaySound(12);
             }
             return true;
         }
         if (Main.cursorOverride == 3)
         {
             if (!canFavoriteAt[context])
             {
                 return false;
             }
             item.favorited = !item.favorited;
             SoundEngine.PlaySound(12);
             return true;
         }
         if (Main.cursorOverride == 7)
         {
             if (context == 29)
             {
                 Item item2 = new Item();
                 item2.SetDefaults(inv[slot].netID);
                 item2.stack = item2.maxStack;
                 item2.OnCreated(new JourneyDuplicationItemCreationContext());
                 item2 = Main.player[Main.myPlayer].GetItem(Main.myPlayer, item2, GetItemSettings.InventoryEntityToPlayerInventorySettings);
                 SoundEngine.PlaySound(12);
                 return true;
             }
             inv[slot] = Main.player[Main.myPlayer].GetItem(Main.myPlayer, inv[slot], GetItemSettings.InventoryEntityToPlayerInventorySettings);
             SoundEngine.PlaySound(12);
             return true;
         }
         if (Main.cursorOverride == 8)
         {
             inv[slot] = Main.player[Main.myPlayer].GetItem(Main.myPlayer, inv[slot], GetItemSettings.InventoryEntityToPlayerInventorySettings);
             if (Main.player[Main.myPlayer].chest > -1)
             {
                 NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, slot);
             }
             return true;
         }
         if (Main.cursorOverride == 9)
         {
             if (Main.CreativeMenu.IsShowingResearchMenu())
             {
                 Main.CreativeMenu.SwapItem(ref inv[slot]);
                 SoundEngine.PlaySound(7);
                 Main.CreativeMenu.SacrificeItemInSacrificeSlot();
             }
             else if (Main.InReforgeMenu)
             {
                 Utils.Swap(ref inv[slot], ref Main.reforgeItem);
                 SoundEngine.PlaySound(7);
             }
             else if (Main.InGuideCraftMenu)
             {
                 Utils.Swap(ref inv[slot], ref Main.guideItem);
                 Recipe.FindRecipes();
                 SoundEngine.PlaySound(7);
             }
             else
             {
                 ChestUI.TryPlacingInChest(inv[slot], justCheck: false, context);
             }
             return true;
         }
         return false;
     }
References ChatManager.AddChatText(), canFavoriteAt, Player.chest, Main.CreativeMenu, Main.cursorOverride, Item.favorited, Recipe.FindRecipes(), ItemTagHandler.GenerateTag(), Player.GetItem(), PlayerInteractionAnchor.GetTileEntity(), Main.guideItem, Main.InGuideCraftMenu, Main.InReforgeMenu, GetItemSettings.InventoryEntityToPlayerInventorySettings, isEquipLocked(), PlayerInteractionAnchor.IsInValidUseTileEntity(), CreativeUI.IsShowingResearchMenu(), Main.LocalPlayer, Item.maxStack, FontAssets.MouseText, Main.myPlayer, Item.OnCreated(), TileEntity.OverrideItemSlotLeftClick(), Main.player, SoundEngine.PlaySound(), Main.reforgeItem, CreativeUI.SacrificeItemInSacrificeSlot(), NetMessage.SendData(), Item.SetDefaults(), Item.stack, CreativeUI.SwapItem(), Player.tileEntityAnchor, ChestUI.TryPlacingInChest(), and Asset< T >.Value.
Referenced by LeftClick().