Terraria: ItemSlot.PickupItemIntoMouse
PickupItemIntoMouse()
static void ItemSlot.PickupItemIntoMouse (Item[] inv, int context, int slot, Player player) inline static
     {
         if (Main.mouseItem.type == 0)
         {
             Main.mouseItem = inv[slot].Clone();
             if (context == 29)
             {
                 Main.mouseItem.SetDefaults(Main.mouseItem.type);
                 Main.mouseItem.OnCreated(new JourneyDuplicationItemCreationContext());
             }
             Main.mouseItem.stack = 0;
             if (inv[slot].favorited && inv[slot].stack == 1)
             {
                 Main.mouseItem.favorited = true;
             }
             else
             {
                 Main.mouseItem.favorited = false;
             }
             AnnounceTransfer(new ItemTransferInfo(inv[slot], context, 21));
         }
         Main.mouseItem.stack++;
         if (context != 29)
         {
             inv[slot].stack--;
         }
         if (inv[slot].stack <= 0)
         {
             inv[slot] = new Item();
         }
         Recipe.FindRecipes();
         if (context == 3 && Main.netMode == 1)
         {
             NetMessage.SendData(32, -1, -1, null, player.chest, slot);
         }
         if ((context == 23 || context == 24) && Main.netMode == 1)
         {
             NetMessage.SendData(121, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot);
         }
         if (context == 25 && Main.netMode == 1)
         {
             NetMessage.SendData(121, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot, 1f);
         }
         if (context == 26 && Main.netMode == 1)
         {
             NetMessage.SendData(124, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot);
         }
         if (context == 27 && Main.netMode == 1)
         {
             NetMessage.SendData(124, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot, 1f);
         }
     }
References AnnounceTransfer(), Player.chest, Item.Clone(), Item.favorited, Recipe.FindRecipes(), PlayerInteractionAnchor.interactEntityID, Main.mouseItem, Main.myPlayer, Main.netMode, Item.OnCreated(), NetMessage.SendData(), Item.SetDefaults(), Item.stack, Player.tileEntityAnchor, and Item.type.
Referenced by RightClick(), and PlayerInput.FastUseItemMemory.TryStartForItemSlot().