Terraria: System.Reflection.PortableExecutable.ManagedPEBuilder.ManagedPEBuilder
ManagedPEBuilder()
System.Reflection.PortableExecutable.ManagedPEBuilder.ManagedPEBuilder (PEHeaderBuilder header, MetadataRootBuilder metadataRootBuilder, BlobBuilder ilStream, BlobBuilder? mappedFieldData = null, BlobBuilder? managedResources = null, ResourceSectionBuilder? nativeResources = null, DebugDirectoryBuilder? debugDirectoryBuilder = null, int strongNameSignatureSize = 128, MethodDefinitionHandle entryPoint = default(MethodDefinitionHandle), CorFlags flags = CorFlags::ILOnly, Func< IEnumerable< Blob >, BlobContentId >? deterministicIdProvider = null) inline
Definition at line 38 of file ManagedPEBuilder.cs.
        : base(header, deterministicIdProvider)
    {
        if (header == null)
        {
            Throw.ArgumentNull("header");
        }
        if (metadataRootBuilder == null)
        {
            Throw.ArgumentNull("metadataRootBuilder");
        }
        if (ilStream == null)
        {
            Throw.ArgumentNull("ilStream");
        }
        if (strongNameSignatureSize < 0)
        {
            Throw.ArgumentOutOfRange("strongNameSignatureSize");
        }
        _metadataRootBuilder = metadataRootBuilder;
        _ilStream = ilStream;
        _mappedFieldDataOpt = mappedFieldData;
        _managedResourcesOpt = managedResources;
        _nativeResourcesOpt = nativeResources;
        _strongNameSignatureSize = strongNameSignatureSize;
        _entryPointOpt = entryPoint;
        _debugDirectoryBuilderOpt = debugDirectoryBuilder ?? CreateDefaultDebugDirectoryBuilder();
        _corFlags = flags;
        _peDirectoriesBuilder = new PEDirectoriesBuilder();
    }
References System.Reflection.PortableExecutable.ManagedPEBuilder._corFlags, System.Reflection.PortableExecutable.ManagedPEBuilder._debugDirectoryBuilderOpt, System.Reflection.PortableExecutable.ManagedPEBuilder._entryPointOpt, System.Reflection.PortableExecutable.ManagedPEBuilder._ilStream, System.Reflection.PortableExecutable.ManagedPEBuilder._managedResourcesOpt, System.Reflection.PortableExecutable.ManagedPEBuilder._mappedFieldDataOpt, System.Reflection.PortableExecutable.ManagedPEBuilder._metadataRootBuilder, System.Reflection.PortableExecutable.ManagedPEBuilder._nativeResourcesOpt, System.Reflection.PortableExecutable.ManagedPEBuilder._peDirectoriesBuilder, System.Reflection.PortableExecutable.ManagedPEBuilder._strongNameSignatureSize, System.Reflection.Throw.ArgumentNull(), System.Reflection.Throw.ArgumentOutOfRange(), and System.Reflection.PortableExecutable.ManagedPEBuilder.CreateDefaultDebugDirectoryBuilder().