Terraria: System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableBox.Run
Run()
override int System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableBox.Run (InterpretedFrame frame) inline
Definition at line 188 of file InitializeLocalInstruction.cs.
        {
            object value;
            try
            {
                value = (_type.IsNullableType() ? Activator.CreateInstance(_type) : RuntimeHelpers.GetUninitializedObject(_type));
            }
            catch (TargetInvocationException exception)
            {
                ExceptionHelpers.UnwrapAndRethrow(exception);
                throw ContractUtils.Unreachable;
            }
            frame.Data[_index] = new StrongBox<object>(value);
            return 1;
        }
References System.Linq.Expressions.Interpreter.LocalAccessInstruction._index, System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableBox._type, System.Activator.CreateInstance(), System.Linq.Expressions.Interpreter.InterpretedFrame.Data, System.exception, System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(), System.Dynamic.Utils.ContractUtils.Unreachable, System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow(), and System.value.