Terraria: System.Reflection.PortableExecutable.ManagedPEBuilder.SerializeTextSection
SerializeTextSection()
BlobBuilder System.Reflection.PortableExecutable.ManagedPEBuilder.SerializeTextSection (SectionLocation location) inline private
Definition at line 106 of file ManagedPEBuilder.cs.
    {
        BlobBuilder blobBuilder = new BlobBuilder();
        BlobBuilder blobBuilder2 = new BlobBuilder();
        MetadataSizes sizes = _metadataRootBuilder.Sizes;
        ManagedTextSection managedTextSection = new ManagedTextSection(base.Header.ImageCharacteristics, base.Header.Machine, _ilStream.Count, sizes.MetadataSize, _managedResourcesOpt?.Count ?? 0, _strongNameSignatureSize, _debugDirectoryBuilderOpt?.Size ?? 0, _mappedFieldDataOpt?.Count ?? 0);
        int methodBodyStreamRva = location.RelativeVirtualAddress + managedTextSection.OffsetToILStream;
        int mappedFieldDataStreamRva = location.RelativeVirtualAddress + managedTextSection.CalculateOffsetToMappedFieldDataStream();
        _metadataRootBuilder.Serialize(blobBuilder2, methodBodyStreamRva, mappedFieldDataStreamRva);
        BlobBuilder blobBuilder3;
        DirectoryEntry debugTable;
        if (_debugDirectoryBuilderOpt != null)
        {
            int num = managedTextSection.ComputeOffsetToDebugDirectory();
            blobBuilder3 = new BlobBuilder(_debugDirectoryBuilderOpt.TableSize);
            _debugDirectoryBuilderOpt.Serialize(blobBuilder3, location, num);
            debugTable = new DirectoryEntry(location.RelativeVirtualAddress + num, _debugDirectoryBuilderOpt.TableSize);
        }
        else
        {
            blobBuilder3 = null;
            debugTable = default(DirectoryEntry);
        }
        _lazyEntryPointAddress = managedTextSection.GetEntryPointAddress(location.RelativeVirtualAddress);
        managedTextSection.Serialize(blobBuilder, location.RelativeVirtualAddress, (!_entryPointOpt.IsNil) ? MetadataTokens.GetToken(_entryPointOpt) : 0, _corFlags, base.Header.ImageBase, blobBuilder2, _ilStream, _mappedFieldDataOpt, _managedResourcesOpt, blobBuilder3, out _lazyStrongNameSignature);
        _peDirectoriesBuilder.AddressOfEntryPoint = _lazyEntryPointAddress;
        _peDirectoriesBuilder.DebugTable = debugTable;
        _peDirectoriesBuilder.ImportAddressTable = managedTextSection.GetImportAddressTableDirectoryEntry(location.RelativeVirtualAddress);
        _peDirectoriesBuilder.ImportTable = managedTextSection.GetImportTableDirectoryEntry(location.RelativeVirtualAddress);
        _peDirectoriesBuilder.CorHeaderTable = managedTextSection.GetCorHeaderDirectoryEntry(location.RelativeVirtualAddress);
        return blobBuilder;
    }
References System.Reflection.PortableExecutable.ManagedPEBuilder._corFlags, System.Reflection.PortableExecutable.ManagedPEBuilder._debugDirectoryBuilderOpt, System.Reflection.PortableExecutable.ManagedPEBuilder._entryPointOpt, System.Reflection.PortableExecutable.ManagedPEBuilder._ilStream, System.Reflection.PortableExecutable.ManagedPEBuilder._lazyEntryPointAddress, System.Reflection.PortableExecutable.ManagedPEBuilder._lazyStrongNameSignature, System.Reflection.PortableExecutable.ManagedPEBuilder._managedResourcesOpt, System.Reflection.PortableExecutable.ManagedPEBuilder._mappedFieldDataOpt, System.Reflection.PortableExecutable.ManagedPEBuilder._metadataRootBuilder, System.Reflection.PortableExecutable.ManagedPEBuilder._strongNameSignatureSize, System.Reflection.Metadata.BlobBuilder.Count, System.Reflection.Metadata.Ecma335.MetadataTokens.GetToken(), System.Reflection.Metadata.MethodDefinitionHandle.IsNil, System.Reflection.Metadata.Ecma335.MetadataRootBuilder.Serialize(), System.Reflection.PortableExecutable.DebugDirectoryBuilder.Serialize(), System.Reflection.PortableExecutable.DebugDirectoryBuilder.Size, System.Reflection.Metadata.Ecma335.MetadataRootBuilder.Sizes, and System.Reflection.PortableExecutable.DebugDirectoryBuilder.TableSize.
Referenced by System.Reflection.PortableExecutable.ManagedPEBuilder.SerializeSection().