Terraria: System.Reflection.PortableExecutable.ManagedPEBuilder.SerializeSection
SerializeSection()
override BlobBuilder System.Reflection.PortableExecutable.ManagedPEBuilder.SerializeSection (string name, SectionLocation location) inline protected
Definition at line 95 of file ManagedPEBuilder.cs.
    {
        return name switch
        {
            ".text" => SerializeTextSection(location),
            ".rsrc" => SerializeResourceSection(location),
            ".reloc" => SerializeRelocationSection(location),
            _ => throw new ArgumentException(System.SR.Format(System.SR.UnknownSectionName, name), "name"),
        };
    }
References System.SR.Format(), System.Reflection.PortableExecutable.ManagedPEBuilder.SerializeRelocationSection(), System.Reflection.PortableExecutable.ManagedPEBuilder.SerializeResourceSection(), System.Reflection.PortableExecutable.ManagedPEBuilder.SerializeTextSection(), and System.SR.UnknownSectionName.