Terraria: System.Reflection.PortableExecutable.ManagedPEBuilder.Sign
Sign() [2/2]
void System.Reflection.PortableExecutable.ManagedPEBuilder.Sign (BlobBuilder peImage, Func< IEnumerable< Blob >, byte[]> signatureProvider) inline
Definition at line 175 of file ManagedPEBuilder.cs.
    {
        if (peImage == null)
        {
            Throw.ArgumentNull("peImage");
        }
        if (signatureProvider == null)
        {
            Throw.ArgumentNull("signatureProvider");
        }
        Sign(peImage, _lazyStrongNameSignature, signatureProvider);
    }
References System.Reflection.PortableExecutable.ManagedPEBuilder._lazyStrongNameSignature, System.Reflection.Throw.ArgumentNull(), and System.Reflection.PortableExecutable.ManagedPEBuilder.Sign().
Referenced by System.Reflection.PortableExecutable.ManagedPEBuilder.Sign().