Terraria: System.Net.Http.IHttpHeadersHandler.OnHeader
OnHeader()
void System.Net.Http.IHttpHeadersHandler.OnHeader (ReadOnlySpan< byte > name, ReadOnlySpan< byte > value)
Implemented in System.Net.Http.Http2Connection.NopHeadersHandler, System.Net.Http.Http2Connection.Http2Stream, and System.Net.Http.Http3RequestStream.
Referenced by System.Net.Http.HPack.HPackDecoder.OnIndexedHeaderField(), System.Net.Http.QPack.QPackDecoder.ProcessHeaderValue(), and System.Net.Http.HPack.HPackDecoder.ProcessHeaderValue().