Terraria: Microsoft.Xna.Framework.Graphics.Effect.Effect
Effect() [3/3]
unsafe Microsoft.Xna.Framework.Graphics.Effect.Effect (Effect cloneSource) inline protected
Definition at line 255 of file Effect.cs.
    {
        try
        {
            if (cloneSource == null)
            {
                throw new ArgumentNullException("cloneSource", FrameworkResources.NullNotAllowed);
            }
            IntPtr intPtr = (IntPtr)cloneSource.pComPtr;
            Helpers.CheckDisposed(cloneSource, intPtr);
            GraphicsDevice parent = cloneSource._parent;
            if (parent == null)
            {
                throw new ArgumentNullException("graphicsDevice", FrameworkResources.DeviceCannotBeNullOnResourceCreate);
            }
            ID3DXEffect* ptr = null;
            ID3DXEffect* ptr2 = cloneSource.pComPtr;
            int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DDevice9*, ID3DXEffect**, int>)(int)(*(uint*)(*(int*)ptr2 + 308)))((nint)ptr2, (IDirect3DDevice9*)parent.pStateTracker, &ptr);
            if (num < 0)
            {
                throw GraphicsHelpers.GetExceptionFromResult((uint)num);
            }
            _parent = parent;
            pComPtr = ptr;
            pParentEffect = new WeakReference(cloneSource);
            cloneSource.AddClonedEffect(this);
            parent.Resources.AddTrackedObject(this, ptr, 0u, _internalHandle, ref _internalHandle);
            InitializeHelpers();
            CurrentTechnique = pTechniqueCollection[0];
            int num2 = 0;
            if (0 >= pParamCollection.Count)
            {
                return;
            }
            do
            {
                EffectParameter effectParameter = pParamCollection[num2];
                if (effectParameter.ElementCount > 1)
                {
                    EffectParameterType paramType = effectParameter._paramType;
                    EffectParameterType effectParameterType = paramType;
                    if (effectParameterType != EffectParameterType.Bool)
                    {
                        EffectParameterType effectParameterType2 = paramType;
                        if (effectParameterType2 != EffectParameterType.Int32)
{
                            EffectParameterType effectParameterType3 = paramType;
                            if (effectParameterType3 != EffectParameterType.Single)
{
                                goto IL_015f;
                            }
                        }
                    }
                    int rows = effectParameter._rows;
                    int columns = effectParameter._columns;
                    int num3 = effectParameter.ElementCount * columns * rows;
                    if (num3 > 0)
                    {
                        float[] valueSingleArray = cloneSource.pParamCollection[num2].GetValueSingleArray(num3);
                        effectParameter.SetValue(valueSingleArray);
                    }
                }
                goto IL_015f;
                IL_015f:
                num2++;
            }
            while (num2 < pParamCollection.Count);
            return;
        }
        catch
        {
            //try-fault
            base.Dispose(true);
            throw;
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.EffectParameterCollection.Count, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.FrameworkResources.DeviceCannotBeNullOnResourceCreate, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.Effect.InitializeHelpers(), Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, Microsoft.Xna.Framework.Graphics.Effect.pComPtr, Microsoft.Xna.Framework.Graphics.Effect.pParamCollection, Microsoft.Xna.Framework.Graphics.Effect.pParentEffect, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pStateTracker, Microsoft.Xna.Framework.Graphics.Effect.pTechniqueCollection, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources.