Terraria: Microsoft.Xna.Framework.Graphics.Effect.Dispose
Dispose() [2/2]
override void Microsoft.Xna.Framework.Graphics.Effect.Dispose ([MarshalAs(UnmanagedType.U1)] bool P_0) inline protected virtual inherited
Reimplemented from Microsoft.Xna.Framework.Graphics.GraphicsResource.
Definition at line 516 of file Effect.cs.
    {
        if (P_0)
        {
            try
            {
                _007EEffect();
                return;
            }
            finally
            {
                base.Dispose(true);
            }
        }
        try
        {
            _0021Effect();
        }
        finally
        {
            base.Dispose(false);
        }
    }
References Microsoft.Xna.Framework.Graphics.Effect._0021Effect(), and Microsoft.Xna.Framework.Graphics.Effect._007EEffect().
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.Dispose().