Terraria: Microsoft.Xna.Framework.Graphics.Effect.RecreateAndPopulateObject
RecreateAndPopulateObject() [1/2]
virtual unsafe int Microsoft.Xna.Framework.Graphics.Effect.RecreateAndPopulateObject () inline package virtual inherited
Implements Microsoft.Xna.Framework.Graphics.IGraphicsResource.
Definition at line 387 of file Effect.cs.
    {
        if (pComPtr != null)
        {
            return 0;
        }
        GraphicsDevice parent = _parent;
        if (parent == null)
        {
            return -2147467259;
        }
        int num = 0;
        WeakReference weakReference = pParentEffect;
        if (weakReference == null)
        {
            CreateEffectFromCode(parent, pCachedEffectData);
        }
        else if (weakReference.Target is Effect { pComPtr: var ptr } && ptr != null)
        {
            ID3DXEffect* ptr2 = null;
            num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DDevice9*, ID3DXEffect**, int>)(int)(*(uint*)(*(int*)ptr + 308)))((nint)ptr, (IDirect3DDevice9*)_parent.pStateTracker, &ptr2);
            pComPtr = ptr2;
            _parent.Resources.AddTrackedObject(this, ptr2, 0u, _internalHandle, ref _internalHandle);
            InitializeHelpers();
        }
        List<WeakReference> list = pClonedEffects;
        if (list != null)
        {
            int num2 = 0;
            if (0 < list.Count)
            {
                do
                {
                    if (num >= 0 && pClonedEffects[num2].Target is Effect effect2 && effect2.pComPtr == null)
                    {
                        num = effect2.RecreateAndPopulateObject();
                    }
                    num2++;
                }
                while (num2 < pClonedEffects.Count);
            }
        }
        EffectTechnique currentTechnique = _currentTechnique;
        if (currentTechnique != null && pComPtr != null)
        {
            EffectTechnique currentTechnique2 = currentTechnique;
            _currentTechnique = null;
            CurrentTechnique = currentTechnique2;
        }
        return num;
    }
References Microsoft.Xna.Framework.Graphics.Effect._currentTechnique, Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Graphics.Effect.CreateEffectFromCode(), Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.Effect.InitializeHelpers(), System.list, Microsoft.Xna.Framework.Graphics.Effect.pCachedEffectData, Microsoft.Xna.Framework.Graphics.Effect.pClonedEffects, Microsoft.Xna.Framework.Graphics.Effect.pComPtr, Microsoft.Xna.Framework.Graphics.Effect.pParentEffect, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pStateTracker, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources, and Microsoft.Xna.Framework.Graphics.Target.
Referenced by Microsoft.Xna.Framework.Graphics.Effect.RecreateAndPopulateObject().