Terraria: Microsoft.Xna.Framework.Graphics.Effect.GetManagedObject
GetManagedObject()
static unsafe Effect Microsoft.Xna.Framework.Graphics.Effect.GetManagedObject (ID3DXEffect * pInterface, GraphicsDevice pDevice, uint pool) inline static package inherited
Definition at line 479 of file Effect.cs.
    {
        Effect effect = pDevice.Resources.GetCachedObject(pInterface) as Effect;
        if (effect != null)
        {
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)pInterface + 8)))((nint)pInterface);
            effect.isDisposed = false;
            GC.ReRegisterForFinalize(effect);
        }
        else
        {
            effect = new Effect(pInterface, pDevice);
            pDevice.Resources.AddTrackedObject(effect, pInterface, pool, 0uL, ref effect._internalHandle);
        }
        return effect;
    }
References Microsoft.Xna.Framework.Graphics.Effect.Effect(), Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.GetCachedObject(), System.GC.ReRegisterForFinalize(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources.