Terraria: Microsoft.Xna.Framework.Graphics.Effect.ReleaseNativeObject
ReleaseNativeObject() [1/2]
virtual unsafe void Microsoft.Xna.Framework.Graphics.Effect.ReleaseNativeObject ([MarshalAs(UnmanagedType.U1)] bool disposeManagedResource) inline package virtual inherited
Implements Microsoft.Xna.Framework.Graphics.IGraphicsResource.
Definition at line 445 of file Effect.cs.
    {
        bool lockTaken = false;
        try
        {
            Monitor.Enter(pSyncObject, ref lockTaken);
            GraphicsDevice parent = _parent;
            if (parent != null && pComPtr != null)
            {
                parent.Resources.ReleaseAllReferences(_internalHandle, disposeManagedResource);
            }
            pComPtr = null;
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(pSyncObject);
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), Microsoft.Xna.Framework.Graphics.Effect.pComPtr, Microsoft.Xna.Framework.Graphics.Effect.pSyncObject, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllReferences(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources.
Referenced by Microsoft.Xna.Framework.Graphics.Effect._0021Effect(), Microsoft.Xna.Framework.Graphics.Effect.ReleaseNativeObject(), and Microsoft.Xna.Framework.Graphics.Effect.SaveDataForRecreation().