Terraria: Microsoft.Xna.Framework.Graphics.Effect.OnResetDevice
OnResetDevice()
unsafe void Microsoft.Xna.Framework.Graphics.Effect.OnResetDevice () inline package inherited
Definition at line 353 of file Effect.cs.
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        ID3DXEffect* intPtr2 = pComPtr;
        int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr2 + 280)))((nint)intPtr2);
        if (num < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
        }
    }
References Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), and Microsoft.Xna.Framework.Graphics.Effect.pComPtr.
Referenced by Microsoft.Xna.Framework.Graphics.DeviceResourceManager.RecreateResources().