Terraria: Microsoft.Xna.Framework.Graphics.Effect.InitializeHelpers
InitializeHelpers()
unsafe void Microsoft.Xna.Framework.Graphics.Effect.InitializeHelpers () inline private inherited
Definition at line 70 of file Effect.cs.
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        ID3DXEffect* ptr = pComPtr;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DXEFFECT_DESC d3DXEFFECT_DESC);
        int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DXEFFECT_DESC*, int>)(int)(*(uint*)(*(int*)ptr + 12)))((nint)ptr, &d3DXEFFECT_DESC);
        if (num < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
        }
        EffectTechniqueCollection effectTechniqueCollection = pTechniqueCollection;
        if (effectTechniqueCollection != null && pParamCollection != null)
        {
            effectTechniqueCollection.UpdateParent((ID3DXBaseEffect*)pComPtr);
            pParamCollection.UpdateParent((ID3DXBaseEffect*)pComPtr, null, arrayElements: false);
        }
        else
        {
            pTechniqueCollection = new EffectTechniqueCollection((ID3DXBaseEffect*)pComPtr, this, System.Runtime.CompilerServices.Unsafe.As<_D3DXEFFECT_DESC, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DXEFFECT_DESC, 8)));
            pParamCollection = new EffectParameterCollection((ID3DXBaseEffect*)pComPtr, this, null, System.Runtime.CompilerServices.Unsafe.As<_D3DXEFFECT_DESC, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DXEFFECT_DESC, 4)), arrayElements: false);
        }
    }
References Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.Effect.pComPtr, Microsoft.Xna.Framework.Graphics.Effect.pParamCollection, Microsoft.Xna.Framework.Graphics.Effect.pTechniqueCollection, and Microsoft.Xna.Framework.Graphics.EffectParameterCollection.UpdateParent().
Referenced by Microsoft.Xna.Framework.Graphics.Effect.Effect(), Microsoft.Xna.Framework.Graphics.Effect.Effect(), Microsoft.Xna.Framework.Graphics.Effect.CreateEffectFromCode(), Microsoft.Xna.Framework.Graphics.Effect.OnObjectCreation(), and Microsoft.Xna.Framework.Graphics.Effect.RecreateAndPopulateObject().