Terraria: Microsoft.Xna.Framework.Graphics.Effect.CreateEffectFromCode
CreateEffectFromCode()
unsafe void Microsoft.Xna.Framework.Graphics.Effect.CreateEffectFromCode (GraphicsDevice graphicsDevice, byte[] effectCode) inline private inherited
Definition at line 94 of file Effect.cs.
    {
        //The blocks IL_0203 are reachable both inside and outside the pinned region starting at IL_0057. ILSpy has duplicated these blocks in order to place them both within and outside the `fixed` statement.
        //The blocks IL_0203 are reachable both inside and outside the pinned region starting at IL_00ac. ILSpy has duplicated these blocks in order to place them both within and outside the `fixed` statement.
        if (effectCode != null)
        {
            int num = effectCode.Length;
            if (num != 0)
            {
                if (num % 4 != 0)
                {
                    string text = "effectCode";
                    throw new ArgumentException(string.Format(FrameworkResources.ArrayMultipleFour, text), text);
                }
                if (graphicsDevice == null)
                {
                    throw new ArgumentNullException("graphicsDevice", FrameworkResources.DeviceCannotBeNullOnResourceCreate);
                }
                if ((uint)num >= 8u)
                {
                    ID3DXBuffer* ptr = null;
                    fixed (void* ptr2 = &System.Runtime.CompilerServices.Unsafe.As<byte, void>(ref effectCode[0]))
                    {
                        uint* ptr3 = (uint*)ptr2;
                        if (*ptr3 == 3169848271u)
{
                            ptr3++;
                            uint num2 = *ptr3;
                            if ((nint)effectCode.LongLength >= (int)(num2 + 4))
{
                                void* ptr4 = System.Runtime.CompilerServices.Unsafe.AsPointer(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref *ptr2, num2));
                                if (*(int*)ptr4 == -16840447)
{
                                    StateTrackerDevice* pStateTracker = graphicsDevice.pStateTracker;
                                    *(int*)((byte*)pStateTracker + 92) = 0;
                                    *(int*)((byte*)pStateTracker + 96) = 0;
                                    *(int*)((byte*)pStateTracker + 100) = 0;
                                    fixed (ID3DXEffect** ptr5 = &pComPtr)
{
                                        int num3 = _003CModule_003E.D3DXCreateEffectEx((IDirect3DDevice9*)pStateTracker, ptr4, (uint)((nint)effectCode.LongLength - (int)num2), null, null, null, 131072u, null, ptr5, &ptr);
                                        if (ptr != null)
{
                                            ID3DXBuffer* intPtr = ptr;
                                            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)intPtr + 8)))((nint)intPtr);
                                            ptr = null;
                                        }
                                        uint num4 = *(uint*)((byte*)pStateTracker + 92);
                                        if (num4 != 0)
{
                                            graphicsDevice._profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileVertexShaderModel, FormatShaderModel(num4));
                                        }
                                        uint num5 = *(uint*)((byte*)pStateTracker + 96);
                                        if (num5 != 0)
{
                                            graphicsDevice._profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfilePixelShaderModel, FormatShaderModel(num5));
                                        }
                                        if (num3 < 0)
{
                                            throw GraphicsHelpers.GetExceptionFromResult((uint)num3);
                                        }
                                        int num6 = *(int*)((byte*)pStateTracker + 100);
                                        if (num6 < 0)
{
                                            throw GraphicsHelpers.GetExceptionFromResult((uint)num6);
                                        }
                                        _parent = graphicsDevice;
                                        pCachedEffectData = effectCode;
                                        graphicsDevice.Resources.AddTrackedObject(this, pComPtr, 0u, _internalHandle, ref _internalHandle);
                                        InitializeHelpers();
                                        CurrentTechnique = pTechniqueCollection[0];
                                        List<EffectTechnique>.Enumerator enumerator = pTechniqueCollection.GetEnumerator();
                                        if (!enumerator.MoveNext())
{
                                            return;
                                        }
                                        do
{
                                            List<EffectPass>.Enumerator enumerator2 = enumerator.Current.pPasses.GetEnumerator();
                                            if (!enumerator2.MoveNext())
{
                                                continue;
                                            }
                                            uint* ptr6 = ptr3 + 1;
                                            do
{
                                                EffectPass current = enumerator2.Current;
                                                if (ptr6 < ptr4)
{
                                                    ptr3++;
                                                    ptr6++;
                                                    current._stateFlags = (EffectStateFlags)(*ptr3);
                                                    ptr3++;
                                                    ptr6++;
                                                    current._textureFlags = *ptr3;
                                                    continue;
                                                }
                                                throw new InvalidOperationException(FrameworkResources.MustUserShaderCode);
                                            }
                                            while (enumerator2.MoveNext());
                                        }
                                        while (enumerator.MoveNext());
                                        return;
                                    }
                                }
                            }
                        }
                        throw new InvalidOperationException(FrameworkResources.MustUserShaderCode);
                    }
                }
                throw new InvalidOperationException(FrameworkResources.MustUserShaderCode);
            }
        }
        throw new ArgumentNullException("effectCode", FrameworkResources.NullNotAllowed);
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.FrameworkResources.ArrayMultipleFour, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.FrameworkResources.DeviceCannotBeNullOnResourceCreate, System.Globalization.Format, Microsoft.Xna.Framework.Graphics.Effect.FormatShaderModel(), Microsoft.Xna.Framework.Graphics.EffectTechniqueCollection.GetEnumerator(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.Effect.InitializeHelpers(), Microsoft.Xna.Framework.FrameworkResources.MustUserShaderCode, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, Microsoft.Xna.Framework.Graphics.Effect.pCachedEffectData, Microsoft.Xna.Framework.Graphics.Effect.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfilePixelShaderModel, Microsoft.Xna.Framework.FrameworkResources.ProfileVertexShaderModel, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pStateTracker, Microsoft.Xna.Framework.Graphics.Effect.pTechniqueCollection, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources, System.text, and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException().
Referenced by Microsoft.Xna.Framework.Graphics.Effect.Effect(), and Microsoft.Xna.Framework.Graphics.Effect.RecreateAndPopulateObject().