Terraria: System.Security.SecureString.UnmanagedBuffer.Allocate
Allocate()
static UnmanagedBuffer System.Security.SecureString.UnmanagedBuffer.Allocate (int byteLength) inline static
Definition at line 18 of file SecureString.cs.
        {
            UnmanagedBuffer unmanagedBuffer = new UnmanagedBuffer();
            unmanagedBuffer.SetHandle(Marshal.AllocHGlobal(byteLength));
            unmanagedBuffer.Initialize((ulong)byteLength);
            unmanagedBuffer._byteLength = byteLength;
            return unmanagedBuffer;
        }
References System.Security.SecureString.UnmanagedBuffer.UnmanagedBuffer(), System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Runtime.InteropServices.SafeBuffer.Initialize(), and System.Runtime.InteropServices.SafeHandle.SetHandle().
Referenced by System.Security.SecureString.SecureString(), System.Security.SecureString.EnsureCapacity(), and System.Security.SecureString.Initialize().