Terraria: System.Net.Security.TlsFrameHelper.TryParseHelloExtensions
TryParseHelloExtensions()
static bool System.Net.Security.TlsFrameHelper.TryParseHelloExtensions (ReadOnlySpan< byte > extensions, ref TlsFrameInfo info, ProcessingOptions options, HelloExtensionCallback callback) inline static private
Definition at line 254 of file TlsFrameHelper.cs.
    {
        bool result = true;
        while (extensions.Length >= 4)
        {
            ExtensionType extensionType = (ExtensionType)BinaryPrimitives.ReadUInt16BigEndian(extensions);
            extensions = SkipBytes(extensions, 2);
            ushort num = BinaryPrimitives.ReadUInt16BigEndian(extensions);
            extensions = SkipBytes(extensions, 2);
            if (extensions.Length < num)
            {
                result = false;
                break;
            }
            ReadOnlySpan<byte> readOnlySpan = extensions.Slice(0, num);
            if (extensionType == ExtensionType.ServerName && (options == ProcessingOptions.All || (options & ProcessingOptions.ServerName) == ProcessingOptions.ServerName))
            {
                if (!TryGetSniFromServerNameList(readOnlySpan, out var sni))
                {
                    return false;
                }
                info.TargetName = sni;
            }
            else if (extensionType == ExtensionType.SupportedVersions && (options == ProcessingOptions.All || (options & ProcessingOptions.Versions) == ProcessingOptions.Versions))
            {
                if (!TryGetSupportedVersionsFromExtension(readOnlySpan, out var protocols))
                {
                    return false;
                }
                info.SupportedVersions |= protocols;
            }
            else if (extensionType == ExtensionType.ApplicationProtocols && (options == ProcessingOptions.All || (options & ProcessingOptions.ApplicationProtocol) == ProcessingOptions.ApplicationProtocol))
            {
                if (!TryGetApplicationProtocolsFromExtension(readOnlySpan, out var alpn))
                {
                    return false;
                }
                info.ApplicationProtocols |= alpn;
            }
            callback?.Invoke(ref info, extensionType, readOnlySpan);
            extensions = extensions.Slice(num);
        }
        return result;
    }
References System.info, System.ReadOnlySpan< T >.Length, System.options, System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(), System.Net.Security.TlsFrameHelper.SkipBytes(), System.ReadOnlySpan< T >.Slice(), System.Net.Security.TlsFrameHelper.TryGetApplicationProtocolsFromExtension(), System.Net.Security.TlsFrameHelper.TryGetSniFromServerNameList(), and System.Net.Security.TlsFrameHelper.TryGetSupportedVersionsFromExtension().
Referenced by System.Net.Security.TlsFrameHelper.TryParseClientHello(), and System.Net.Security.TlsFrameHelper.TryParseServerHello().