Terraria: System.Net.Security.TlsFrameHelper.SkipOpaqueType1
SkipOpaqueType1()
static ReadOnlySpan< byte > System.Net.Security.TlsFrameHelper.SkipOpaqueType1 (ReadOnlySpan< byte > bytes) inline static private
Definition at line 460 of file TlsFrameHelper.cs.
    {
        if (bytes.Length < 1)
        {
            return ReadOnlySpan<byte>.Empty;
        }
        byte b = bytes[0];
        int numberOfBytesToSkip = 1 + b;
        return SkipBytes(bytes, numberOfBytesToSkip);
    }
References System.bytes, System.ReadOnlySpan< T >.Empty, and System.Net.Security.TlsFrameHelper.SkipBytes().
Referenced by System.Net.Security.TlsFrameHelper.TryParseClientHello(), and System.Net.Security.TlsFrameHelper.TryParseServerHello().