Terraria: System.Net.Security.TlsFrameHelper.GetSniFromHostNameStruct
GetSniFromHostNameStruct()
static string System.Net.Security.TlsFrameHelper.GetSniFromHostNameStruct (ReadOnlySpan< byte > hostNameStruct, out bool invalid) inline static private
Definition at line 334 of file TlsFrameHelper.cs.
    {
        int num = BinaryPrimitives.ReadUInt16BigEndian(hostNameStruct);
        ReadOnlySpan<byte> bytes = hostNameStruct.Slice(2);
        if (num != bytes.Length)
        {
            invalid = true;
            return null;
        }
        invalid = false;
        return DecodeString(bytes);
    }
References System.bytes, System.Net.Security.TlsFrameHelper.DecodeString(), System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(), and System.ReadOnlySpan< T >.Slice().
Referenced by System.Net.Security.TlsFrameHelper.GetSniFromServerName().