Terraria: System.Net.Security.TlsFrameHelper.TryParseHelloFrame
TryParseHelloFrame()
static bool System.Net.Security.TlsFrameHelper.TryParseHelloFrame (ReadOnlySpan< byte > sslHandshake, ref TlsFrameInfo info, ProcessingOptions options, HelloExtensionCallback callback) inline static private
Definition at line 194 of file TlsFrameHelper.cs.
    {
        if (sslHandshake.Length < 4 || (sslHandshake[0] != 1 && sslHandshake[0] != 2))
        {
            return false;
        }
        int num = ReadUInt24BigEndian(sslHandshake.Slice(1));
        ReadOnlySpan<byte> readOnlySpan = sslHandshake.Slice(4);
        if (readOnlySpan.Length < num)
        {
            return false;
        }
        if (readOnlySpan[0] == 3)
        {
            info.SupportedVersions |= TlsMinorVersionToProtocol(readOnlySpan[1]);
        }
        if (sslHandshake[0] != 1)
        {
            return TryParseServerHello(readOnlySpan.Slice(0, num), ref info, options, callback);
        }
        return TryParseClientHello(readOnlySpan.Slice(0, num), ref info, options, callback);
    }
References System.info, System.ReadOnlySpan< T >.Length, System.options, System.Net.Security.TlsFrameHelper.ReadUInt24BigEndian(), System.ReadOnlySpan< T >.Slice(), System.Net.Security.TlsFrameHelper.TlsMinorVersionToProtocol(), System.Net.Security.TlsFrameHelper.TryParseClientHello(), and System.Net.Security.TlsFrameHelper.TryParseServerHello().
Referenced by System.Net.Security.TlsFrameHelper.TryGetFrameInfo().