Terraria: System.Net.Security.TlsFrameHelper.TryGetApplicationProtocolsFromExtension
TryGetApplicationProtocolsFromExtension()
static bool System.Net.Security.TlsFrameHelper.TryGetApplicationProtocolsFromExtension (ReadOnlySpan< byte > extensionData, out ApplicationProtocolInfo alpn) inline static private
Definition at line 367 of file TlsFrameHelper.cs.
    {
        alpn = ApplicationProtocolInfo.None;
        if (extensionData.Length < 2)
        {
            return false;
        }
        int num = BinaryPrimitives.ReadUInt16BigEndian(extensionData);
        ReadOnlySpan<byte> readOnlySpan = extensionData.Slice(2);
        if (num != readOnlySpan.Length)
        {
            return false;
        }
        while (!readOnlySpan.IsEmpty)
        {
            byte b = readOnlySpan[0];
            if (readOnlySpan.Length < b + 1)
            {
                return false;
            }
            ReadOnlySpan<byte> span = readOnlySpan.Slice(1, b);
            if (b == 2)
            {
                if (span.SequenceEqual(SslApplicationProtocol.Http2.Protocol.Span))
                {
                    alpn |= ApplicationProtocolInfo.Http2;
                }
                else
                {
                    alpn |= ApplicationProtocolInfo.Other;
                }
            }
            else if (b == SslApplicationProtocol.Http11.Protocol.Length && span.SequenceEqual(SslApplicationProtocol.Http11.Protocol.Span))
            {
                alpn |= ApplicationProtocolInfo.Http11;
            }
            else
            {
                alpn |= ApplicationProtocolInfo.Other;
            }
            readOnlySpan = readOnlySpan.Slice(b + 1);
        }
        return true;
    }
References System.Net.Security.SslApplicationProtocol.Http11, System.Net.Security.SslApplicationProtocol.Http2, System.ReadOnlySpan< T >.IsEmpty, System.ReadOnlySpan< T >.Length, System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(), and System.ReadOnlySpan< T >.Slice().
Referenced by System.Net.Security.TlsFrameHelper.TryParseHelloExtensions().