Terraria: System.Net.Security.TlsFrameHelper.SkipOpaqueType2
SkipOpaqueType2()
static ReadOnlySpan< byte > System.Net.Security.TlsFrameHelper.SkipOpaqueType2 (ReadOnlySpan< byte > bytes) inline static private
Definition at line 471 of file TlsFrameHelper.cs.
    {
        if (bytes.Length < 2)
        {
            return ReadOnlySpan<byte>.Empty;
        }
        ushort num = BinaryPrimitives.ReadUInt16BigEndian(bytes);
        int numberOfBytesToSkip = 2 + num;
        return SkipBytes(bytes, numberOfBytesToSkip);
    }
References System.bytes, System.ReadOnlySpan< T >.Empty, System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(), and System.Net.Security.TlsFrameHelper.SkipBytes().
Referenced by System.Net.Security.TlsFrameHelper.TryParseClientHello().