Terraria: System.Net.Security.TlsFrameHelper.TryGetSniFromServerNameList
TryGetSniFromServerNameList()
static bool System.Net.Security.TlsFrameHelper.TryGetSniFromServerNameList (ReadOnlySpan< byte > serverNameListExtension, out string sni) inline static private
Definition at line 299 of file TlsFrameHelper.cs.
    {
        sni = null;
        if (serverNameListExtension.Length < 2)
        {
            return false;
        }
        int num = BinaryPrimitives.ReadUInt16BigEndian(serverNameListExtension);
        ReadOnlySpan<byte> readOnlySpan = serverNameListExtension.Slice(2);
        if (num != readOnlySpan.Length)
        {
            return false;
        }
        ReadOnlySpan<byte> serverName = readOnlySpan.Slice(0, num);
        sni = GetSniFromServerName(serverName, out var invalid);
        return !invalid;
    }
References System.Net.Security.TlsFrameHelper.GetSniFromServerName(), System.ReadOnlySpan< T >.Length, System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(), and System.ReadOnlySpan< T >.Slice().
Referenced by System.Net.Security.TlsFrameHelper.TryParseHelloExtensions().