Terraria: System.Net.Security.TlsFrameHelper.TryGetFrameHeader
TryGetFrameHeader()
static bool System.Net.Security.TlsFrameHelper.TryGetFrameHeader (ReadOnlySpan< byte > frame, ref TlsFrameHeader header) inline static
Definition at line 84 of file TlsFrameHelper.cs.
    {
        bool result = frame.Length > 4;
        if (frame.Length >= 1)
        {
            header.Type = (TlsContentType)frame[0];
            if (frame.Length >= 3)
            {
                if (frame[1] == 3)
                {
                    if (frame.Length > 4)
                    {
                        header.Length = (frame[3] << 8) | frame[4];
                    }
                    header.Version = TlsMinorVersionToProtocol(frame[2]);
                }
                else
                {
                    header.Length = -1;
                    header.Version = SslProtocols.None;
                }
            }
        }
        return result;
    }
References System.ReadOnlySpan< T >.Length, and System.Net.Security.TlsFrameHelper.TlsMinorVersionToProtocol().
Referenced by System.Net.Security.SslStream.ProcessBlob(), System.Net.Security.SslStream.ReadAsyncInternal< TIOAdapter >(), System.Net.Security.SslStream.ReceiveBlobAsync< TIOAdapter >(), and System.Net.Security.TlsFrameHelper.TryGetFrameInfo().