Terraria: System.Net.Security.TlsFrameHelper.TlsMinorVersionToProtocol
TlsMinorVersionToProtocol()
static SslProtocols System.Net.Security.TlsFrameHelper.TlsMinorVersionToProtocol (byte value) inline static private
Definition at line 412 of file TlsFrameHelper.cs.
    {
        return value switch
        {
            4 => SslProtocols.Tls13,
            3 => SslProtocols.Tls12,
            2 => SslProtocols.Tls11,
            1 => SslProtocols.Tls,
            0 => SslProtocols.Ssl3,
            _ => SslProtocols.None,
        };
    }
References System.value.
Referenced by System.Net.Security.TlsFrameHelper.TryGetFrameHeader(), System.Net.Security.TlsFrameHelper.TryGetSupportedVersionsFromExtension(), and System.Net.Security.TlsFrameHelper.TryParseHelloFrame().