Terraria: System.Net.Security.TlsFrameHelper.TryParseClientHello
TryParseClientHello()
static bool System.Net.Security.TlsFrameHelper.TryParseClientHello (ReadOnlySpan< byte > clientHello, ref TlsFrameInfo info, ProcessingOptions options, HelloExtensionCallback callback) inline static private
Definition at line 217 of file TlsFrameHelper.cs.
    {
        ReadOnlySpan<byte> bytes = SkipBytes(clientHello, 34);
        bytes = SkipOpaqueType1(bytes);
        bytes = SkipOpaqueType2(bytes);
        bytes = SkipOpaqueType1(bytes);
        if (bytes.IsEmpty)
        {
            return false;
        }
        int num = BinaryPrimitives.ReadUInt16BigEndian(bytes);
        bytes = SkipBytes(bytes, 2);
        if (num != bytes.Length)
        {
            return false;
        }
        return TryParseHelloExtensions(bytes, ref info, options, callback);
    }
References System.bytes, System.info, System.options, System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(), System.Net.Security.TlsFrameHelper.SkipBytes(), System.Net.Security.TlsFrameHelper.SkipOpaqueType1(), System.Net.Security.TlsFrameHelper.SkipOpaqueType2(), and System.Net.Security.TlsFrameHelper.TryParseHelloExtensions().
Referenced by System.Net.Security.TlsFrameHelper.TryParseHelloFrame().