Terraria: System.Net.Security.TlsFrameHelper.SkipBytes
SkipBytes()
static ReadOnlySpan< byte > System.Net.Security.TlsFrameHelper.SkipBytes (ReadOnlySpan< byte > bytes, int numberOfBytesToSkip) inline static private
Definition at line 451 of file TlsFrameHelper.cs.
    {
        if (numberOfBytesToSkip >= bytes.Length)
        {
            return ReadOnlySpan<byte>.Empty;
        }
        return bytes.Slice(numberOfBytesToSkip);
    }
References System.bytes, and System.ReadOnlySpan< T >.Empty.
Referenced by System.Net.Security.TlsFrameHelper.SkipOpaqueType1(), System.Net.Security.TlsFrameHelper.SkipOpaqueType2(), System.Net.Security.TlsFrameHelper.TryParseClientHello(), System.Net.Security.TlsFrameHelper.TryParseHelloExtensions(), and System.Net.Security.TlsFrameHelper.TryParseServerHello().