Terraria: System.Net.Security.TlsFrameHelper.TryGetSupportedVersionsFromExtension
TryGetSupportedVersionsFromExtension()
static bool System.Net.Security.TlsFrameHelper.TryGetSupportedVersionsFromExtension (ReadOnlySpan< byte > extensionData, out SslProtocols protocols) inline static private
Definition at line 347 of file TlsFrameHelper.cs.
    {
        protocols = SslProtocols.None;
        byte b = extensionData[0];
        extensionData = extensionData.Slice(1);
        if (extensionData.Length != b)
        {
            return false;
        }
        while (extensionData.Length >= 2)
        {
            if (extensionData[0] == 3)
            {
                protocols |= TlsMinorVersionToProtocol(extensionData[1]);
            }
            extensionData = extensionData.Slice(2);
        }
        return true;
    }
References System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), and System.Net.Security.TlsFrameHelper.TlsMinorVersionToProtocol().
Referenced by System.Net.Security.TlsFrameHelper.TryParseHelloExtensions().