Terraria: System.Net.Security.TlsFrameHelper.TryGetFrameInfo
TryGetFrameInfo()
static bool System.Net.Security.TlsFrameHelper.TryGetFrameInfo (ReadOnlySpan< byte > frame, ref TlsFrameInfo info, ProcessingOptions options = ProcessingOptions::All, HelloExtensionCallback callback = null) inline static
Definition at line 110 of file TlsFrameHelper.cs.
    {
        if (frame.Length < 5)
        {
            return false;
        }
        bool flag = TryGetFrameHeader(frame, ref info.Header);
        info.SupportedVersions = info.Header.Version;
        if (info.Header.Type == TlsContentType.Alert)
        {
            TlsAlertLevel level = (TlsAlertLevel)0;
            TlsAlertDescription description = TlsAlertDescription.CloseNotify;
            if (TryGetAlertInfo(frame, ref level, ref description))
            {
                info.AlertDescription = description;
                return true;
            }
            return false;
        }
        if (info.Header.Type != TlsContentType.Handshake || frame.Length <= 5)
        {
            return false;
        }
        info.HandshakeType = (TlsHandshakeType)frame[5];
        bool result = frame.Length >= 5 + info.Header.Length;
        if (info.Header.Version >= SslProtocols.Tls && (info.HandshakeType == TlsHandshakeType.ClientHello || info.HandshakeType == TlsHandshakeType.ServerHello) && !TryParseHelloFrame(frame.Slice(5), ref info, options, callback))
        {
            result = false;
        }
        return result;
    }
References System.info, System.ReadOnlySpan< T >.Length, System.options, System.ReadOnlySpan< T >.Slice(), System.Net.Security.TlsFrameHelper.TryGetAlertInfo(), System.Net.Security.TlsFrameHelper.TryGetFrameHeader(), and System.Net.Security.TlsFrameHelper.TryParseHelloFrame().
Referenced by System.Net.Security.SslStream.ReceiveBlobAsync< TIOAdapter >(), and System.Net.NetEventSource.SentFrame().