Terraria: PlayerInput.FastUseItemMemory.TryStartForItemSlot
TryStartForItemSlot()
bool PlayerInput.FastUseItemMemory.TryStartForItemSlot (Player player, int itemSlot) inline
         {
             if (itemSlot < 0 || itemSlot >= 50)
             {
                 Clear();
                 return false;
             }
             _player = player;
             _slot = itemSlot;
             _itemType = _player.inventory[itemSlot].type;
             _shouldFastUse = true;
             _isMouseItem = false;
             ItemSlot.PickupItemIntoMouse(player.inventory, 0, itemSlot, player);
             return true;
         }
References PlayerInput.FastUseItemMemory._isMouseItem, PlayerInput.FastUseItemMemory._itemType, PlayerInput.FastUseItemMemory._player, PlayerInput.FastUseItemMemory._shouldFastUse, PlayerInput.FastUseItemMemory._slot, PlayerInput.FastUseItemMemory.Clear(), Player.inventory, ItemSlot.PickupItemIntoMouse(), and Item.type.
Referenced by PlayerInput.TryEnteringFastUseModeForInventorySlot().