Terraria: Terraria.GameContent.Skies.MoonLordSky.OnTileColor
OnTileColor()
override Color Terraria.GameContent.Skies.MoonLordSky.OnTileColor (Color inColor) inline virtual
Reimplemented from Terraria.Graphics.Effects.CustomSky.
Definition at line 63 of file MoonLordSky.cs.
    {
        float intensity = GetIntensity();
        return new Color(Vector4.Lerp(new Vector4(0.5f, 0.8f, 1f, 1f), inColor.ToVector4(), 1f - intensity));
    }
References Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.Skies.MoonLordSky.GetIntensity(), Microsoft.Xna.Framework.Vector4.Lerp(), and Microsoft.Xna.Framework.Color.ToVector4().