Terraria: System.UriHelper.EscapeString
EscapeString() [2/2]
static string System.UriHelper.EscapeString (string stringToEscape, bool checkExistingEscaped, ReadOnlySpan< bool > unreserved, char forceEscape1 = '\0', char forceEscape2 = '\0') inline static package
Definition at line 110 of file UriHelper.cs.
    {
        if (stringToEscape == null)
        {
            throw new ArgumentNullException("stringToEscape");
        }
        if (stringToEscape.Length == 0)
        {
            return string.Empty;
        }
        ReadOnlySpan<bool> readOnlySpan = default(Span<bool>);
        if ((forceEscape1 | forceEscape2) == 0)
        {
            readOnlySpan = unreserved;
        }
        else
        {
            Span<bool> span = stackalloc bool[128];
            unreserved.CopyTo(span);
            span[forceEscape1] = false;
            span[forceEscape2] = false;
            readOnlySpan = span;
        }
        int i;
        for (i = 0; i < stringToEscape.Length; i++)
        {
            char index;
            if ((index = stringToEscape[i]) > '\u007f')
            {
                break;
            }
            if (!readOnlySpan[index])
            {
                break;
            }
        }
        if (i == stringToEscape.Length)
        {
            return stringToEscape;
        }
        Span<char> initialBuffer = stackalloc char[512];
        System.Text.ValueStringBuilder vsb = new System.Text.ValueStringBuilder(initialBuffer);
        vsb.Append(stringToEscape.AsSpan(0, i));
        EscapeStringToBuilder(stringToEscape.AsSpan(i), ref vsb, readOnlySpan, checkExistingEscaped);
        return vsb.ToString();
    }
References System.Text.ValueStringBuilder.Append(), System.ReadOnlySpan< T >.CopyTo(), System.UriHelper.EscapeStringToBuilder(), System.index, and System.Text.ValueStringBuilder.ToString().
Referenced by System.Uri.CreateHostString(), System.Uri.EscapeDataString(), System.Uri.EscapeString(), System.Uri.EscapeUriString(), System.Uri.GetCanonicalPath(), System.Uri.GetRelativeSerializationString(), System.Uri.InternalEscapeString(), and System.Uri.ReCreateParts().