Terraria: System.UriHelper.UnescapeString
UnescapeString() [1/5]
static unsafe char[] System.UriHelper.UnescapeString (char * pStr, int start, int end, char[] dest, ref int destPosition, char rsvd1, char rsvd2, char rsvd3, UnescapeMode unescapeMode, UriParser syntax, bool isQuery) inline static package
Definition at line 253 of file UriHelper.cs.
    {
        System.Text.ValueStringBuilder dest2 = new System.Text.ValueStringBuilder(dest.Length);
        dest2.Append(dest.AsSpan(0, destPosition));
        UnescapeString(pStr, start, end, ref dest2, rsvd1, rsvd2, rsvd3, unescapeMode, syntax, isQuery);
        if (dest2.Length > dest.Length)
        {
            dest = dest2.AsSpan().ToArray();
        }
        else
        {
            dest2.AsSpan(destPosition).TryCopyTo(dest.AsSpan(destPosition));
        }
        destPosition = dest2.Length;
        dest2.Dispose();
        return dest;
    }
References System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.AsSpan(), System.Text.ValueStringBuilder.Dispose(), System.Text.ValueStringBuilder.Length, System.start, System.ReadOnlySpan< T >.ToArray(), System.ReadOnlySpan< T >.TryCopyTo(), and System.UriHelper.UnescapeString().