Terraria: System.UriHelper.UnescapeString
UnescapeString() [2/5]
static unsafe void System.UriHelper.UnescapeString (char * pStr, int start, int end, ref System::Text::ValueStringBuilder dest, char rsvd1, char rsvd2, char rsvd3, UnescapeMode unescapeMode, UriParser syntax, bool isQuery) inline static package
Definition at line 287 of file UriHelper.cs.
    {
        if ((unescapeMode & UnescapeMode.EscapeUnescape) == 0)
        {
            dest.Append(pStr + start, end - start);
            return;
        }
        bool flag = false;
        bool flag2 = Uri.IriParsingStatic(syntax) && (unescapeMode & UnescapeMode.EscapeUnescape) == UnescapeMode.EscapeUnescape;
        int i = start;
        while (i < end)
        {
            char c = '\0';
            for (; i < end; i++)
            {
                if ((c = pStr[i]) == '%')
                {
                    if ((unescapeMode & UnescapeMode.Unescape) == 0)
                    {
                        flag = true;
                        break;
                    }
                    if (i + 2 < end)
                    {
                        c = DecodeHexChars(pStr[i + 1], pStr[i + 2]);
                        if (unescapeMode < UnescapeMode.UnescapeAll)
{
                            switch (c)
{
                            case '\uffff':
                                if ((unescapeMode & UnescapeMode.Escape) == 0)
{
                                    continue;
                                }
                                flag = true;
                                break;
                            case '%':
                                i += 2;
                                continue;
                            default:
                                if (c == rsvd1 || c == rsvd2 || c == rsvd3)
{
                                    i += 2;
                                    continue;
                                }
                                if ((unescapeMode & UnescapeMode.V1ToStringFlag) == 0 && IsNotSafeForUnescape(c))
{
                                    i += 2;
                                    continue;
                                }
                                if (flag2 && ((c <= '\u009f' && IsNotSafeForUnescape(c)) || (c > '\u009f' && !IriHelper.CheckIriUnicodeRange(c, isQuery))))
{
                                    i += 2;
                                    continue;
                                }
                                break;
                            }
                            break;
                        }
                        if (c != '\uffff')
{
                            break;
                        }
                        if (unescapeMode >= UnescapeMode.UnescapeAllOrThrow)
{
                            throw new UriFormatException(System.SR.net_uri_BadString);
                        }
                    }
                    else
                    {
                        if (unescapeMode < UnescapeMode.UnescapeAll)
{
                            flag = true;
                            break;
                        }
                        if (unescapeMode >= UnescapeMode.UnescapeAllOrThrow)
{
                            throw new UriFormatException(System.SR.net_uri_BadString);
                        }
                    }
                }
                else if ((unescapeMode & (UnescapeMode.Unescape | UnescapeMode.UnescapeAll)) != (UnescapeMode.Unescape | UnescapeMode.UnescapeAll) && (unescapeMode & UnescapeMode.Escape) != 0)
                {
                    if (c == rsvd1 || c == rsvd2 || c == rsvd3)
                    {
                        flag = true;
                        break;
                    }
                    if ((unescapeMode & UnescapeMode.V1ToStringFlag) == 0 && (c <= '\u001f' || (c >= '\u007f' && c <= '\u009f')))
                    {
                        flag = true;
                        break;
                    }
                }
            }
            while (start < i)
            {
                dest.Append(pStr[start++]);
            }
            if (i != end)
            {
                if (flag)
                {
                    EscapeAsciiChar((byte)pStr[i], ref dest);
                    flag = false;
                    i++;
                }
                else if (c <= '\u007f')
                {
                    dest.Append(c);
                    i += 3;
                }
                else
                {
                    int num = PercentEncodingHelper.UnescapePercentEncodedUTF8Sequence(pStr + i, end - i, ref dest, isQuery, flag2);
                    i += num;
                }
                start = i;
            }
        }
    }
References System.IriHelper.CheckIriUnicodeRange(), System.UriHelper.DecodeHexChars(), System.UriHelper.EscapeAsciiChar(), System.Uri.IriParsingStatic(), System.UriHelper.IsNotSafeForUnescape(), System.SR.net_uri_BadString, System.start, and System.PercentEncodingHelper.UnescapePercentEncodedUTF8Sequence().