Terraria: System.UriHelper.IsLWS
IsLWS()
static bool System.UriHelper.IsLWS (char ch) inline static package
Definition at line 444 of file UriHelper.cs.
    {
        if (ch <= ' ')
        {
            if (ch != ' ' && ch != '\n' && ch != '\r')
            {
                return ch == '\t';
            }
            return true;
        }
        return false;
    }
References System.ch.
Referenced by System.Uri.CreateUriInfo(), System.Uri.GetLengthWithoutTrailingSpaces(), System.Uri.ParseSchemeCheckImplicitFile(), System.Uri.PrivateParseMinimal(), and System.Uri.ResolveHelper().