Terraria: System.UriHelper.StripBidiControlCharacters
StripBidiControlCharacters()
static unsafe string System.UriHelper.StripBidiControlCharacters (ReadOnlySpan< char > strToClean, string backingString = null) inline static package
Definition at line 485 of file UriHelper.cs.
    {
        int num = 0;
        ReadOnlySpan<char> readOnlySpan = strToClean;
        for (int i = 0; i < readOnlySpan.Length; i++)
        {
            char c = readOnlySpan[i];
            if ((uint)(c - 8206) <= 32u && IsBidiControlCharacter(c))
            {
                num++;
            }
        }
        if (num == 0)
        {
            return backingString ?? new string(strToClean);
        }
        if (num == strToClean.Length)
        {
            return string.Empty;
        }
        fixed (char* ptr = &MemoryMarshal.GetReference(strToClean))
        {
            return string.Create(strToClean.Length - num, ((IntPtr)ptr, strToClean.Length), delegate(Span<char> buffer, (IntPtr StrToClean, int Length) state)
            {
                ReadOnlySpan<char> readOnlySpan2 = new ReadOnlySpan<char>((void*)state.StrToClean, state.Length);
                int num2 = 0;
                ReadOnlySpan<char> readOnlySpan3 = readOnlySpan2;
                for (int j = 0; j < readOnlySpan3.Length; j++)
                {
                    char c2 = readOnlySpan3[j];
                    if ((uint)(c2 - 8206) > 32u || !IsBidiControlCharacter(c2))
                    {
                        buffer[num2++] = c2;
                    }
                }
            });
        }
    }
References System.buffer, System.UriHelper.IsBidiControlCharacter(), System.ReadOnlySpan< T >.Length, and System.state.
Referenced by System.Uri.CheckAuthorityHelperHandleDnsIri(), System.DomainNameHelper.IdnEquivalent(), and System.Uri.ReCreateParts().