Terraria: System.UriHelper.UnescapeString
UnescapeString() [4/5]
static unsafe char[] System.UriHelper.UnescapeString (string input, int start, int end, char[] dest, ref int destPosition, char rsvd1, char rsvd2, char rsvd3, UnescapeMode unescapeMode, UriParser syntax, bool isQuery) inline static package
Definition at line 245 of file UriHelper.cs.
    {
        fixed (char* pStr = input)
        {
            return UnescapeString(pStr, start, end, dest, ref destPosition, rsvd1, rsvd2, rsvd3, unescapeMode, syntax, isQuery);
        }
    }
References System.input, System.start, and System.UriHelper.UnescapeString().
Referenced by System.Uri.GetCanonicalPath(), System.Uri.GetLocalPath(), System.Uri.GetRelativeSerializationString(), System.Uri.ReCreateParts(), System.Uri.Unescape(), System.Uri.UnescapeDataString(), System.UriHelper.UnescapeString(), System.UriHelper.UnescapeString(), System.UriHelper.UnescapeString(), and System.UriHelper.UnescapeString().