Terraria: System.UriHelper.EscapeStringToBuilder
EscapeStringToBuilder()
static void System.UriHelper.EscapeStringToBuilder (ReadOnlySpan< char > stringToEscape, ref System::Text::ValueStringBuilder vsb, ReadOnlySpan< bool > noEscape, bool checkExistingEscaped) inline static private
Definition at line 195 of file UriHelper.cs.
    {
        Span<byte> destination = stackalloc byte[4];
        SpanRuneEnumerator spanRuneEnumerator = stringToEscape.EnumerateRunes();
        while (spanRuneEnumerator.MoveNext())
        {
            Rune current = spanRuneEnumerator.Current;
            if (!current.IsAscii)
            {
                current.TryEncodeToUtf8(destination, out var bytesWritten);
                Span<byte> span = destination.Slice(0, bytesWritten);
                for (int i = 0; i < span.Length; i++)
                {
                    byte value = span[i];
                    vsb.Append('%');
                    System.HexConverter.ToCharsBuffer(value, vsb.AppendSpan(2));
                }
                continue;
            }
            byte b = (byte)current.Value;
            if (noEscape[b])
            {
                vsb.Append((char)b);
                continue;
            }
            if (checkExistingEscaped && b == 37)
            {
                SpanRuneEnumerator spanRuneEnumerator2 = spanRuneEnumerator;
                if (spanRuneEnumerator2.MoveNext())
                {
                    Rune current2 = spanRuneEnumerator2.Current;
                    if (current2.IsAscii && IsHexDigit((char)current2.Value) && spanRuneEnumerator2.MoveNext())
                    {
                        Rune current3 = spanRuneEnumerator2.Current;
                        if (current3.IsAscii && IsHexDigit((char)current3.Value))
{
                            vsb.Append('%');
                            vsb.Append((char)current2.Value);
                            vsb.Append((char)current3.Value);
                            spanRuneEnumerator = spanRuneEnumerator2;
                            continue;
                        }
                    }
                }
            }
            vsb.Append('%');
            System.HexConverter.ToCharsBuffer(b, vsb.AppendSpan(2));
        }
    }
References System.Text.SpanRuneEnumerator.Current, System.destination, System.Text.Rune.IsAscii, System.UriHelper.IsHexDigit(), System.Span< T >.Length, System.Text.SpanRuneEnumerator.MoveNext(), System.Span< T >.Slice(), System.HexConverter.ToCharsBuffer(), System.Text.Rune.TryEncodeToUtf8(), System.Text.Rune.Value, and System.value.
Referenced by System.UriHelper.EscapeString(), and System.UriHelper.EscapeString().