Terraria: System.Globalization.JapaneseCalendar.NlsGetJapaneseEras
NlsGetJapaneseEras()
static EraInfo[] System.Globalization.JapaneseCalendar.NlsGetJapaneseEras () inline static private
Definition at line 293 of file JapaneseCalendar.cs.
    {
        int num = 0;
        EraInfo[] array = null;
        try
        {
            using RegistryKey registryKey = Registry.LocalMachine.OpenSubKey("System\\CurrentControlSet\\Control\\Nls\\Calendars\\Japanese\\Eras");
            if (registryKey == null)
            {
                return null;
            }
            string[] valueNames = registryKey.GetValueNames();
            if (valueNames != null && valueNames.Length != 0)
            {
                array = new EraInfo[valueNames.Length];
                for (int i = 0; i < valueNames.Length; i++)
                {
                    EraInfo eraFromValue = GetEraFromValue(valueNames[i], registryKey.GetValue(valueNames[i])?.ToString());
                    if (eraFromValue != null)
                    {
                        array[num] = eraFromValue;
                        num++;
                    }
                }
            }
        }
        catch (SecurityException)
        {
            return null;
        }
        catch (IOException)
        {
            return null;
        }
        catch (UnauthorizedAccessException)
        {
            return null;
        }
        if (num < 4)
        {
            return null;
        }
        Array.Resize(ref array, num);
        Array.Sort(array, CompareEraRanges);
        for (int j = 0; j < array.Length; j++)
        {
            array[j].era = array.Length - j;
            if (j == 0)
            {
                array[0].maxEraYear = 9999 - array[0].yearOffset;
            }
            else
            {
                array[j].maxEraYear = array[j - 1].yearOffset + 1 - array[j].yearOffset;
            }
        }
        return array;
    }
References System.array, System.Globalization.JapaneseCalendar.CompareEraRanges(), System.Globalization.JapaneseCalendar.GetEraFromValue(), Internal.Win32.Registry.LocalMachine, and System.Array.Sort().
Referenced by System.Globalization.JapaneseCalendar.GetEraInfo().