Terraria: System.Globalization.JapaneseCalendar.IcuGetJapaneseEras
IcuGetJapaneseEras()
static EraInfo[] System.Globalization.JapaneseCalendar.IcuGetJapaneseEras () inline static private
Definition at line 227 of file JapaneseCalendar.cs.
    {
        if (GlobalizationMode.Invariant)
        {
            return null;
        }
        if (!CalendarData.EnumCalendarInfo("ja-JP", CalendarId.JAPAN, CalendarDataType.EraNames, out var calendarData))
        {
            return null;
        }
        List<EraInfo> list = new List<EraInfo>();
        int num = 9999;
        int latestJapaneseEra = Interop.Globalization.GetLatestJapaneseEra();
        for (int num2 = latestJapaneseEra; num2 >= 0; num2--)
        {
            if (!GetJapaneseEraStartDate(num2, out var dateTime))
            {
                return null;
            }
            if (dateTime < s_calendarMinValue)
            {
                break;
            }
            list.Add(new EraInfo(num2, dateTime.Year, dateTime.Month, dateTime.Day, dateTime.Year - 1, 1, num - dateTime.Year + 1, calendarData[num2], GetAbbreviatedEraName(calendarData, num2), ""));
            num = dateTime.Year;
        }
        if (!CalendarData.EnumCalendarInfo("ja", CalendarId.JAPAN, CalendarDataType.AbbrevEraNames, out var calendarData2))
        {
            calendarData2 = s_abbreviatedEnglishEraNames;
        }
        if (calendarData2[^1].Length == 0 || calendarData2[^1][0] > '\u007f')
        {
            calendarData2 = s_abbreviatedEnglishEraNames;
        }
        int num3 = ((calendarData2 == s_abbreviatedEnglishEraNames) ? (list.Count - 1) : (calendarData2.Length - 1));
        for (int i = 0; i < list.Count; i++)
        {
            list[i].era = list.Count - i;
            if (num3 < calendarData2.Length)
            {
                list[i].englishEraName = calendarData2[num3];
            }
            num3--;
        }
        return list.ToArray();
    }
References System.Globalization.CalendarData.EnumCalendarInfo(), System.Globalization.JapaneseCalendar.GetAbbreviatedEraName(), System.Globalization.JapaneseCalendar.GetJapaneseEraStartDate(), Interop.Globalization.GetLatestJapaneseEra(), System.Globalization.GlobalizationMode.Invariant, System.list, System.Globalization.JapaneseCalendar.s_abbreviatedEnglishEraNames, and System.Globalization.JapaneseCalendar.s_calendarMinValue.
Referenced by System.Globalization.JapaneseCalendar.GetEraInfo().