Terraria: System.Runtime.Serialization.DateTimeOffsetAdapter.GetDateTimeOffset
GetDateTimeOffset()
static DateTimeOffset System.Runtime.Serialization.DateTimeOffsetAdapter.GetDateTimeOffset (DateTimeOffsetAdapter value) inline static
Definition at line 45 of file DateTimeOffsetAdapter.cs.
    {
        try
        {
            if (value.UtcDateTime.Kind == DateTimeKind.Unspecified)
            {
                return new DateTimeOffset(value.UtcDateTime, new TimeSpan(0, value.OffsetMinutes, 0));
            }
            return new DateTimeOffset(value.UtcDateTime).ToOffset(new TimeSpan(0, value.OffsetMinutes, 0));
        }
        catch (ArgumentException exception)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value.ToString(CultureInfo.InvariantCulture), "DateTimeOffset", exception));
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.exception, System.Globalization.CultureInfo.InvariantCulture, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.TimeSpan, System.DateTimeOffset.ToOffset(), and System.value.
Referenced by System.Runtime.Serialization.ReflectionReader.ResolveAdapterObject().