Terraria: Terraria.GameContent.ChromaHotkeyPainter.Step_KeybindsMenu
Step_KeybindsMenu()
void Terraria.GameContent.ChromaHotkeyPainter.Step_KeybindsMenu () inline private
Definition at line 305 of file ChromaHotkeyPainter.cs.
    {
        SetGroupColorBase(_wasdKeys, PainterColors.MovementKeys);
        _jumpKey.SetSolid(PainterColors.MovementKeys);
        _grappleKey.SetSolid(PainterColors.QuickGrapple);
        _mountKey.SetSolid(PainterColors.QuickMount);
        _quickHealAlert = 0;
        _healKey.SetSolid(PainterColors.QuickHealReady);
        _manaKey.SetSolid(PainterColors.QuickMana);
        _throwKey.SetSolid(PainterColors.Throw);
        _smartCursorKey.SetSolid(PainterColors.SmartCursor);
        _smartSelectKey.SetSolid(PainterColors.SmartSelect);
    }
References Terraria.GameContent.ChromaHotkeyPainter._grappleKey, Terraria.GameContent.ChromaHotkeyPainter._healKey, Terraria.GameContent.ChromaHotkeyPainter._jumpKey, Terraria.GameContent.ChromaHotkeyPainter._manaKey, Terraria.GameContent.ChromaHotkeyPainter._mountKey, Terraria.GameContent.ChromaHotkeyPainter._quickHealAlert, Terraria.GameContent.ChromaHotkeyPainter._smartCursorKey, Terraria.GameContent.ChromaHotkeyPainter._smartSelectKey, Terraria.GameContent.ChromaHotkeyPainter._throwKey, Terraria.GameContent.ChromaHotkeyPainter._wasdKeys, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.MovementKeys, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.QuickGrapple, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.QuickHealReady, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.QuickMana, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.QuickMount, Terraria.GameContent.ChromaHotkeyPainter.SetGroupColorBase(), Terraria.GameContent.ChromaHotkeyPainter.PaintKey.SetSolid(), Terraria.GameContent.ChromaHotkeyPainter.PainterColors.SmartCursor, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.SmartSelect, and Terraria.GameContent.ChromaHotkeyPainter.PainterColors.Throw.
Referenced by Terraria.GameContent.ChromaHotkeyPainter.Update().