Terraria: System.IO.Strategies.BufferedFileStreamStrategy.WriteAsync
WriteAsync() [3/3]
override ValueTask System.IO.Strategies.BufferedFileStreamStrategy.WriteAsync (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 797 of file BufferedFileStreamStrategy.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            return ValueTask.FromCanceled(cancellationToken);
        }
        EnsureCanWrite();
        if (!_strategy.CanSeek)
        {
            return WriteToNonSeekableAsync(buffer, cancellationToken);
        }
        SemaphoreSlim semaphoreSlim = EnsureAsyncActiveSemaphoreInitialized();
        Task task = semaphoreSlim.WaitAsync(cancellationToken);
        if (task.IsCompletedSuccessfully && _readPos == _readLen)
        {
            bool flag = true;
            try
            {
                if (_writePos == 0 && buffer.Length >= _bufferSize)
                {
                    return _strategy.WriteAsync(buffer, cancellationToken);
                }
                if (_bufferSize - _writePos >= buffer.Length)
                {
                    EnsureBufferAllocated();
                    buffer.Span.CopyTo(_buffer.AsSpan(_writePos));
                    _writePos += buffer.Length;
                    return default(ValueTask);
                }
                flag = false;
            }
            finally
            {
                if (flag)
                {
                    semaphoreSlim.Release();
                }
            }
        }
        return WriteAsyncSlowPath(task, buffer, cancellationToken);
    }
References System.IO.Strategies.BufferedFileStreamStrategy._buffer, System.IO.Strategies.BufferedFileStreamStrategy._bufferSize, System.IO.Strategies.BufferedFileStreamStrategy._readLen, System.IO.Strategies.BufferedFileStreamStrategy._readPos, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Strategies.BufferedFileStreamStrategy._writePos, System.buffer, System.cancellationToken, System.IO.Stream.CanSeek, System.IO.Stream.EnsureAsyncActiveSemaphoreInitialized(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureBufferAllocated(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureCanWrite(), System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.Threading.SemaphoreSlim.Release(), System.task, System.Threading.SemaphoreSlim.WaitAsync(), System.IO.Stream.WriteAsync(), System.IO.Strategies.BufferedFileStreamStrategy.WriteAsyncSlowPath(), and System.IO.Strategies.BufferedFileStreamStrategy.WriteToNonSeekableAsync().