Terraria: System.IO.Strategies.BufferedFileStreamStrategy.WriteToNonSeekableAsync
WriteToNonSeekableAsync()
async ValueTask System.IO.Strategies.BufferedFileStreamStrategy.WriteToNonSeekableAsync (ReadOnlyMemory< byte > source, CancellationToken cancellationToken) inline private
Definition at line 839 of file BufferedFileStreamStrategy.cs.
    {
        await EnsureAsyncActiveSemaphoreInitialized().WaitAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        try
        {
            await _strategy.WriteAsync(source, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            _asyncActiveSemaphore.Release();
        }
    }
References System.IO.Stream._asyncActiveSemaphore, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.EnsureAsyncActiveSemaphoreInitialized(), System.Threading.SemaphoreSlim.Release(), System.source, System.Threading.SemaphoreSlim.WaitAsync(), and System.IO.Stream.WriteAsync().
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.WriteAsync().