Terraria: System.IO.Strategies.BufferedFileStreamStrategy.Flush
Flush() [2/2]
override void System.IO.Strategies.BufferedFileStreamStrategy.Flush (bool flushToDisk) inline package
Definition at line 888 of file BufferedFileStreamStrategy.cs.
    {
        EnsureNotClosed();
        if (_writePos > 0 && _strategy.CanWrite)
        {
            FlushWrite();
        }
        else if (_readPos < _readLen)
        {
            if (_strategy.CanSeek)
            {
                FlushRead();
            }
        }
        else
        {
            _strategy.Flush(flushToDisk);
            _writePos = (_readPos = (_readLen = 0));
        }
    }
References System.IO.Strategies.BufferedFileStreamStrategy._readLen, System.IO.Strategies.BufferedFileStreamStrategy._readPos, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Strategies.BufferedFileStreamStrategy._writePos, System.IO.Stream.CanSeek, System.IO.Stream.CanWrite, System.IO.Strategies.BufferedFileStreamStrategy.EnsureNotClosed(), System.IO.Strategies.FileStreamStrategy.Flush(), System.IO.Strategies.BufferedFileStreamStrategy.FlushRead(), and System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite().