Terraria: System.IO.Strategies.BufferedFileStreamStrategy.ClearReadBufferBeforeWrite
ClearReadBufferBeforeWrite()
void System.IO.Strategies.BufferedFileStreamStrategy.ClearReadBufferBeforeWrite () inline private
Definition at line 1046 of file BufferedFileStreamStrategy.cs.
    {
        if (_readPos == _readLen)
        {
            _readPos = (_readLen = 0);
        }
        else
        {
            FlushRead();
        }
    }
References System.IO.Strategies.BufferedFileStreamStrategy._readLen, System.IO.Strategies.BufferedFileStreamStrategy._readPos, and System.IO.Strategies.BufferedFileStreamStrategy.FlushRead().
Referenced by System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.MoveNext(), System.IO.Strategies.BufferedFileStreamStrategy.WriteByteSlow(), and System.IO.Strategies.BufferedFileStreamStrategy.WriteSpan().