Terraria: System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync
ReadAsync() [2/3]
override Task< int > System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 601 of file BufferedFileStreamStrategy.cs.
    {
        ValueTask<int> valueTask = ReadAsync(new Memory<byte>(buffer, offset, count), cancellationToken);
        if (!valueTask.IsCompletedSuccessfully)
        {
            return valueTask.AsTask();
        }
        return LastSyncCompletedReadTask(valueTask.Result);
        Task<int> LastSyncCompletedReadTask(int val)
        {
            Task<int> lastSyncCompletedReadTask = _lastSyncCompletedReadTask;
            if (lastSyncCompletedReadTask != null && lastSyncCompletedReadTask.Result == val)
            {
                return lastSyncCompletedReadTask;
            }
            return _lastSyncCompletedReadTask = Task.FromResult(val);
        }
    }
References System.IO.Strategies.BufferedFileStreamStrategy._lastSyncCompletedReadTask, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.buffer, System.cancellationToken, System.count, System.Threading.Tasks.ValueTask< TResult >.IsCompletedSuccessfully, System.offset, System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync(), System.Threading.Tasks.Task< TResult >.Result, and System.Threading.Tasks.ValueTask< TResult >.Result.
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.BeginRead(), and System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync().