Terraria: System.IO.Strategies.BufferedFileStreamStrategy.WriteSpan
WriteSpan()
void System.IO.Strategies.BufferedFileStreamStrategy.WriteSpan (ReadOnlySpan< byte > source, ArraySegment< byte > arraySegment) inline private
Definition at line 717 of file BufferedFileStreamStrategy.cs.
    {
        if (_writePos == 0)
        {
            EnsureCanWrite();
            ClearReadBufferBeforeWrite();
        }
        if (_writePos > 0)
        {
            int num = _bufferSize - _writePos;
            if (num > 0)
            {
                if (num >= source.Length)
                {
                    source.CopyTo(_buffer.AsSpan(_writePos));
                    _writePos += source.Length;
                    return;
                }
                source.Slice(0, num).CopyTo(_buffer.AsSpan(_writePos));
                _writePos += num;
                source = source.Slice(num);
                if (arraySegment.Array != null)
                {
                    arraySegment = arraySegment.Slice(num);
                }
            }
            FlushWrite();
        }
        if (source.Length >= _bufferSize)
        {
            if (arraySegment.Array != null)
            {
                _strategy.Write(arraySegment.Array, arraySegment.Offset, arraySegment.Count);
            }
            else
            {
                _strategy.Write(source);
            }
        }
        else if (source.Length != 0)
        {
            EnsureBufferAllocated();
            source.CopyTo(_buffer.AsSpan(_writePos));
            _writePos = source.Length;
        }
    }
References System.IO.Strategies.BufferedFileStreamStrategy._buffer, System.IO.Strategies.BufferedFileStreamStrategy._bufferSize, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Strategies.BufferedFileStreamStrategy._writePos, System.ArraySegment< T >.Array, System.IO.Strategies.BufferedFileStreamStrategy.ClearReadBufferBeforeWrite(), System.ArraySegment< T >.Count, System.IO.Strategies.BufferedFileStreamStrategy.EnsureBufferAllocated(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureCanWrite(), System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite(), System.ArraySegment< T >.Offset, System.ArraySegment< T >.Slice(), System.source, and System.IO.Stream.Write().
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.Write(), and System.IO.Strategies.BufferedFileStreamStrategy.Write().