Terraria: System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite
FlushWrite()
void System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite () inline private
Definition at line 1040 of file BufferedFileStreamStrategy.cs.
    {
        _strategy.Write(_buffer, 0, _writePos);
        _writePos = 0;
    }
References System.IO.Strategies.BufferedFileStreamStrategy._buffer, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Strategies.BufferedFileStreamStrategy._writePos, and System.IO.Stream.Write().
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.CopyTo(), System.IO.Strategies.BufferedFileStreamStrategy.Flush(), System.IO.Strategies.BufferedFileStreamStrategy.ReadByteSlow(), System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(), System.IO.Strategies.BufferedFileStreamStrategy.Seek(), System.IO.Strategies.BufferedFileStreamStrategy.WriteByteSlow(), and System.IO.Strategies.BufferedFileStreamStrategy.WriteSpan().