Terraria: System.IO.Strategies.BufferedFileStreamStrategy.EnsureCanWrite
EnsureCanWrite()
void System.IO.Strategies.BufferedFileStreamStrategy.EnsureCanWrite () inline private
Definition at line 1082 of file BufferedFileStreamStrategy.cs.
    {
        if (!_strategy.CanWrite)
        {
            ThrowHelper.ThrowNotSupportedException_UnwritableStream();
        }
    }
References System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Stream.CanWrite, and System.ThrowHelper.ThrowNotSupportedException_UnwritableStream().
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.WriteAsync(), System.IO.Strategies.BufferedFileStreamStrategy.WriteByteSlow(), and System.IO.Strategies.BufferedFileStreamStrategy.WriteSpan().