Terraria: System.IO.Strategies.BufferedFileStreamStrategy.Seek
Seek()
override long System.IO.Strategies.BufferedFileStreamStrategy.Seek (long offset, SeekOrigin origin) inline
Definition at line 992 of file BufferedFileStreamStrategy.cs.
    {
        EnsureNotClosed();
        EnsureCanSeek();
        if (_writePos > 0)
        {
            FlushWrite();
            return _strategy.Seek(offset, origin);
        }
        if (_readLen - _readPos > 0 && origin == SeekOrigin.Current)
        {
            offset -= _readLen - _readPos;
        }
        long position = Position;
        long num = _strategy.Seek(offset, origin);
        long num2 = num - (position - _readPos);
        if (0 <= num2 && num2 < _readLen)
        {
            _readPos = (int)num2;
            _strategy.Seek(_readLen - _readPos, SeekOrigin.Current);
        }
        else
        {
            _readPos = (_readLen = 0);
        }
        return num;
    }
References System.IO.Strategies.BufferedFileStreamStrategy._readLen, System.IO.Strategies.BufferedFileStreamStrategy._readPos, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Strategies.BufferedFileStreamStrategy._writePos, System.IO.Strategies.BufferedFileStreamStrategy.EnsureCanSeek(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureNotClosed(), System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite(), System.offset, System.IO.Strategies.BufferedFileStreamStrategy.Position, and System.IO.Stream.Seek().