Terraria: System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore
CopyToAsyncCore()
async Task System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore (Stream destination, int bufferSize, CancellationToken cancellationToken) inline private
Definition at line 951 of file BufferedFileStreamStrategy.cs.
    {
        await EnsureAsyncActiveSemaphoreInitialized().WaitAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        try
        {
            int num = _readLen - _readPos;
            if (num > 0)
            {
                await destination.WriteAsync(new ReadOnlyMemory<byte>(_buffer, _readPos, num), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                _readPos = (_readLen = 0);
            }
            else if (_writePos > 0)
            {
                await _strategy.WriteAsync(new ReadOnlyMemory<byte>(_buffer, 0, _writePos), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                _writePos = 0;
            }
            await _strategy.CopyToAsync(destination, bufferSize, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            _asyncActiveSemaphore.Release();
        }
    }
References System.IO.Stream._asyncActiveSemaphore, System.IO.Strategies.BufferedFileStreamStrategy._buffer, System.IO.Strategies.BufferedFileStreamStrategy._readLen, System.IO.Strategies.BufferedFileStreamStrategy._readPos, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Strategies.BufferedFileStreamStrategy._writePos, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.CopyToAsync(), System.destination, System.IO.Stream.EnsureAsyncActiveSemaphoreInitialized(), System.Threading.SemaphoreSlim.Release(), System.Threading.SemaphoreSlim.WaitAsync(), and System.IO.Stream.WriteAsync().
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsync().