Terraria: System.IO.Strategies.BufferedFileStreamStrategy.DisposeAsync
DisposeAsync()
override async ValueTask System.IO.Strategies.BufferedFileStreamStrategy.DisposeAsync () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 467 of file BufferedFileStreamStrategy.cs.
    {
        _ = 1;
        try
        {
            if (!_strategy.IsClosed)
            {
                try
                {
                    await FlushAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
                finally
                {
                    await _strategy.DisposeAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
            }
        }
        finally
        {
            _writePos = 0;
        }
    }
References System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Strategies.BufferedFileStreamStrategy._writePos, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.IO.Stream.DisposeAsync(), System.IO.Stream.FlushAsync(), and System.IO.Strategies.FileStreamStrategy.IsClosed.