Terraria: System.IO.Strategies.BufferedFileStreamStrategy.ReadFromNonSeekableAsync
ReadFromNonSeekableAsync()
async ValueTask< int > System.IO.Strategies.BufferedFileStreamStrategy.ReadFromNonSeekableAsync (Memory< byte > destination, CancellationToken cancellationToken) inline private
Definition at line 661 of file BufferedFileStreamStrategy.cs.
    {
        await EnsureAsyncActiveSemaphoreInitialized().WaitAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        try
        {
            if (_readPos < _readLen)
            {
                int num = Math.Min(_readLen - _readPos, destination.Length);
                new Span<byte>(_buffer, _readPos, num).CopyTo(destination.Span);
                _readPos += num;
                return num;
            }
            return await _strategy.ReadAsync(destination, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            _asyncActiveSemaphore.Release();
        }
    }
References System.IO.Stream._asyncActiveSemaphore, System.IO.Strategies.BufferedFileStreamStrategy._buffer, System.IO.Strategies.BufferedFileStreamStrategy._readLen, System.IO.Strategies.BufferedFileStreamStrategy._readPos, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Span< T >.CopyTo(), System.destination, System.IO.Stream.EnsureAsyncActiveSemaphoreInitialized(), System.Math.Min(), System.IO.Stream.ReadAsync(), System.Threading.SemaphoreSlim.Release(), and System.Threading.SemaphoreSlim.WaitAsync().
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync().