Terraria: Terraria.GameContent.ChromaHotkeyPainter.Step_QuickMana
Step_QuickMana()
void Terraria.GameContent.ChromaHotkeyPainter.Step_QuickMana () inline private
    {
        PaintKey manaKey = _manaKey;
        if (_player.QuickMana_GetItemToUse() == null || _player.DeadOrGhost || _player.statMana == _player.statManaMax2)
        {
            manaKey.SetClear();
        }
        else
        {
            manaKey.SetSolid(PainterColors.QuickMana);
        }
    }
References Terraria.GameContent.ChromaHotkeyPainter._manaKey, Terraria.GameContent.ChromaHotkeyPainter._player, Terraria.Player.DeadOrGhost, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.QuickMana, Terraria.Player.QuickMana_GetItemToUse(), Terraria.GameContent.ChromaHotkeyPainter.PaintKey.SetClear(), Terraria.GameContent.ChromaHotkeyPainter.PaintKey.SetSolid(), Terraria.Player.statMana, and Terraria.Player.statManaMax2.