Terraria: System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan
ReadSpan()
int System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan (Span< byte > destination, ArraySegment< byte > arraySegment) inline private
Definition at line 530 of file BufferedFileStreamStrategy.cs.
    {
        bool flag = false;
        int num = _readLen - _readPos;
        if (num == 0)
        {
            EnsureCanRead();
            if (_writePos > 0)
            {
                FlushWrite();
            }
            if (!_strategy.CanSeek || destination.Length >= _bufferSize)
            {
                num = ((arraySegment.Array != null) ? _strategy.Read(arraySegment.Array, arraySegment.Offset, arraySegment.Count) : _strategy.Read(destination));
                _readPos = 0;
                _readLen = 0;
                return num;
            }
            EnsureBufferAllocated();
            num = _strategy.Read(_buffer, 0, _bufferSize);
            if (num == 0)
            {
                return 0;
            }
            flag = num < _bufferSize;
            _readPos = 0;
            _readLen = num;
        }
        if (num > destination.Length)
        {
            num = destination.Length;
        }
        new ReadOnlySpan<byte>(_buffer, _readPos, num).CopyTo(destination);
        _readPos += num;
        if (_strategy.CanSeek && num < destination.Length && !flag)
        {
            int num2 = ((arraySegment.Array != null) ? _strategy.Read(arraySegment.Array, arraySegment.Offset + num, arraySegment.Count - num) : _strategy.Read(destination.Slice(num)));
            num += num2;
            _readPos = 0;
            _readLen = 0;
        }
        return num;
    }
References System.IO.Strategies.BufferedFileStreamStrategy._buffer, System.IO.Strategies.BufferedFileStreamStrategy._bufferSize, System.IO.Strategies.BufferedFileStreamStrategy._readLen, System.IO.Strategies.BufferedFileStreamStrategy._readPos, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Strategies.BufferedFileStreamStrategy._writePos, System.ArraySegment< T >.Array, System.IO.Stream.CanSeek, System.ReadOnlySpan< T >.CopyTo(), System.ArraySegment< T >.Count, System.destination, System.IO.Strategies.BufferedFileStreamStrategy.EnsureBufferAllocated(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureCanRead(), System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite(), System.ArraySegment< T >.Offset, and System.IO.Stream.Read().
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.Read(), and System.IO.Strategies.BufferedFileStreamStrategy.Read().