Terraria: System.IO.Strategies.BufferedFileStreamStrategy.WriteByteSlow
WriteByteSlow()
void System.IO.Strategies.BufferedFileStreamStrategy.WriteByteSlow (byte value) inline private
Definition at line 776 of file BufferedFileStreamStrategy.cs.
    {
        if (_writePos == 0)
        {
            EnsureNotClosed();
            EnsureCanWrite();
            ClearReadBufferBeforeWrite();
            EnsureBufferAllocated();
        }
        else
        {
            FlushWrite();
        }
        _buffer[_writePos++] = value;
    }
References System.IO.Strategies.BufferedFileStreamStrategy._buffer, System.IO.Strategies.BufferedFileStreamStrategy._writePos, System.IO.Strategies.BufferedFileStreamStrategy.ClearReadBufferBeforeWrite(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureBufferAllocated(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureCanWrite(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureNotClosed(), System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite(), and System.value.
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.WriteByte().