Terraria: System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync
ReadAsync() [3/3]
override ValueTask< int > System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 620 of file BufferedFileStreamStrategy.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            return ValueTask.FromCanceled<int>(cancellationToken);
        }
        EnsureCanRead();
        if (!_strategy.CanSeek)
        {
            return ReadFromNonSeekableAsync(buffer, cancellationToken);
        }
        SemaphoreSlim semaphoreSlim = EnsureAsyncActiveSemaphoreInitialized();
        Task task = semaphoreSlim.WaitAsync(cancellationToken);
        if (task.IsCompletedSuccessfully && _writePos == 0)
        {
            bool flag = true;
            try
            {
                if (_readLen == _readPos && buffer.Length >= _bufferSize)
                {
                    return _strategy.ReadAsync(buffer, cancellationToken);
                }
                if (_readLen - _readPos >= buffer.Length)
                {
                    _buffer.AsSpan(_readPos, buffer.Length).CopyTo(buffer.Span);
                    _readPos += buffer.Length;
                    return new ValueTask<int>(buffer.Length);
                }
                flag = false;
            }
            finally
            {
                if (flag)
                {
                    semaphoreSlim.Release();
                }
            }
        }
        return ReadAsyncSlowPath(task, buffer, cancellationToken);
    }
References System.IO.Strategies.BufferedFileStreamStrategy._buffer, System.IO.Strategies.BufferedFileStreamStrategy._bufferSize, System.IO.Strategies.BufferedFileStreamStrategy._readLen, System.IO.Strategies.BufferedFileStreamStrategy._readPos, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Strategies.BufferedFileStreamStrategy._writePos, System.buffer, System.cancellationToken, System.IO.Stream.CanSeek, System.IO.Stream.EnsureAsyncActiveSemaphoreInitialized(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureCanRead(), System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.IO.Stream.ReadAsync(), System.IO.Strategies.BufferedFileStreamStrategy.ReadAsyncSlowPath(), System.IO.Strategies.BufferedFileStreamStrategy.ReadFromNonSeekableAsync(), System.Threading.SemaphoreSlim.Release(), System.task, and System.Threading.SemaphoreSlim.WaitAsync().