Terraria: Terraria.GameContent.ChromaHotkeyPainter.Step_Mount
Step_Mount()
void Terraria.GameContent.ChromaHotkeyPainter.Step_Mount () inline private
Definition at line 390 of file ChromaHotkeyPainter.cs.
    {
        PaintKey mountKey = _mountKey;
        if (_player.QuickMount_GetItemToUse() == null || _player.DeadOrGhost)
        {
            mountKey.SetClear();
        }
        else if (_player.frozen || _player.tongued || _player.webbed || _player.stoned || _player.gravDir == -1f || _player.noItems)
        {
            mountKey.SetSolid(PainterColors.DangerKeyBlocked);
            if (_player.gravDir == -1f)
            {
                mountKey.SetSolid(PainterColors.DangerKeyBlocked * 0.6f);
            }
        }
        else
        {
            mountKey.SetSolid(PainterColors.QuickMount);
        }
    }
References Terraria.GameContent.ChromaHotkeyPainter._mountKey, Terraria.GameContent.ChromaHotkeyPainter._player, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.DangerKeyBlocked, Terraria.Player.DeadOrGhost, Terraria.Player.frozen, Terraria.Player.gravDir, Terraria.Player.noItems, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.QuickMount, Terraria.Player.QuickMount_GetItemToUse(), Terraria.GameContent.ChromaHotkeyPainter.PaintKey.SetClear(), Terraria.GameContent.ChromaHotkeyPainter.PaintKey.SetSolid(), Terraria.Player.stoned, Terraria.Player.tongued, and Terraria.Player.webbed.