Terraria: System.IO.Strategies.BufferedFileStreamStrategy.ReadAsyncSlowPath
ReadAsyncSlowPath()
ValueTask< int > System.IO.Strategies.BufferedFileStreamStrategy.ReadAsyncSlowPath (Task semaphoreLockTask, Memory< byte > buffer, CancellationToken cancellationToken) inline private
Definition at line 683 of file BufferedFileStreamStrategy.cs.
    {
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _003CReadAsyncSlowPath_003Ed__39 stateMachine);
        stateMachine._003C_003Et__builder = PoolingAsyncValueTaskMethodBuilder<int>.Create();
        stateMachine._003C_003E4__this = this;
        stateMachine.semaphoreLockTask = semaphoreLockTask;
        stateMachine.buffer = buffer;
        stateMachine.cancellationToken = cancellationToken;
        stateMachine._003C_003E1__state = -1;
        stateMachine._003C_003Et__builder.Start(ref stateMachine);
        return stateMachine._003C_003Et__builder.Task;
    }
References System.buffer, System.cancellationToken, System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.Create(), System.Threading.Tasks.Task< TResult >.Start(), and System.stateMachine.
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync().