Terraria: System.IO.Strategies.BufferedFileStreamStrategy.WriteAsyncSlowPath
WriteAsyncSlowPath()
ValueTask System.IO.Strategies.BufferedFileStreamStrategy.WriteAsyncSlowPath (Task semaphoreLockTask, ReadOnlyMemory< byte > source, CancellationToken cancellationToken) inline private
Definition at line 854 of file BufferedFileStreamStrategy.cs.
    {
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _003CWriteAsyncSlowPath_003Ed__50 stateMachine);
        stateMachine._003C_003Et__builder = PoolingAsyncValueTaskMethodBuilder.Create();
        stateMachine._003C_003E4__this = this;
        stateMachine.semaphoreLockTask = semaphoreLockTask;
        stateMachine.source = source;
        stateMachine.cancellationToken = cancellationToken;
        stateMachine._003C_003E1__state = -1;
        stateMachine._003C_003Et__builder.Start(ref stateMachine);
        return stateMachine._003C_003Et__builder.Task;
    }
References System.cancellationToken, System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.Create(), System.source, System.Threading.Tasks.Task< TResult >.Start(), and System.stateMachine.
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.WriteAsync().