Terraria: RgbDevice.DebugDraw
DebugDraw()
virtual void RgbDevice.DebugDraw (IDebugDrawer drawer, Vector2 position, float scale) inline virtual inherited
Reimplemented in DebugKeyboard.
     {
         //IL_000e: Unknown result type (might be due to invalid IL or missing references)
         //IL_0013: Unknown result type (might be due to invalid IL or missing references)
         //IL_0020: Unknown result type (might be due to invalid IL or missing references)
         //IL_0025: Unknown result type (might be due to invalid IL or missing references)
         //IL_002f: Unknown result type (might be due to invalid IL or missing references)
         //IL_0040: Unknown result type (might be due to invalid IL or missing references)
         //IL_0051: Unknown result type (might be due to invalid IL or missing references)
         //IL_005a: Unknown result type (might be due to invalid IL or missing references)
         //IL_005c: Unknown result type (might be due to invalid IL or missing references)
         //IL_0061: Unknown result type (might be due to invalid IL or missing references)
         //IL_0062: Unknown result type (might be due to invalid IL or missing references)
         //IL_0075: Unknown result type (might be due to invalid IL or missing references)
         //IL_007a: Unknown result type (might be due to invalid IL or missing references)
         //IL_007b: Unknown result type (might be due to invalid IL or missing references)
         for (int i = 0; i < LedCount; i++)
         {
             Vector2 canvasPositionOfIndex = _backBuffer.GetCanvasPositionOfIndex(i);
             Vector4 vector = _backBuffer.Colors[i];
             vector.X *= vector.W;
             vector.Y *= vector.W;
             vector.Z *= vector.W;
             drawer.DrawSquare(new Vector4(canvasPositionOfIndex * scale + position, scale / 10f, scale / 10f), new Color(vector));
         }
     }
References RgbDevice._backBuffer, Color, Fragment.Colors, IDebugDrawer.DrawSquare(), Fragment.GetCanvasPositionOfIndex(), and RgbDevice.LedCount.
Referenced by ChromaEngine.DebugDraw().