Terraria: RgbDevice.RgbDevice
RgbDevice()
RgbDevice.RgbDevice (RgbDeviceVendor vendor, RgbDeviceType type, Fragment fragment, DeviceColorProfile colorProfile) inline protected
     {
         PreferredLevelOfDetail = EffectDetailLevel.High;
         Vendor = vendor;
         Type = type;
         _backBuffer = fragment;
         _workingFragment = fragment.CreateCopy();
         _colorProfile = colorProfile;
     }
References _backBuffer, _colorProfile, _workingFragment, Fragment.CreateCopy(), PreferredLevelOfDetail, Type, and Vendor.
Referenced by DebugKeyboard.DebugDraw(), and VirtualKeyboard.Render().