Terraria: Terraria.Graphics.Effects.Filters.Scene
Scene
FilterManager Terraria.Graphics.Effects.Filters.Scene = new FilterManager() static
Definition at line 5 of file Filters.cs.
Referenced by Terraria.NPC.AI(), Terraria.Main.BindSettingsTo(), Terraria.Main.CheckMonoliths(), Terraria.Main.ClearVisualPostProcessEffects(), Terraria.Main.ClientInitialize(), Terraria.Main.DoDraw(), Terraria.Main.DoUpdate(), Terraria.Main.DrawNPCDirect(), Terraria.Graphics.Capture.CaptureCamera.DrawTick(), Terraria.GameContent.Events.Sandstorm.HandleEffectAndSky(), Terraria.Initializers.ScreenEffectInitializer.Load(), Terraria.Rain.MakeRain(), Terraria.Player.ManageSpecialBiomeVisuals(), Terraria.Gore.Update(), Terraria.Player.UpdateBiomes(), Terraria.GameContent.Events.DD2Event.UpdateTime(), and Terraria.Main.UpdateTime().