Terraria: SkyManager.Update
Update()
void SkyManager.Update (GameTime gameTime) inline
     {
         int num = Main.dayRate;
         if (num < 1)
         {
             num = 1;
         }
         for (int i = 0; i < num; i++)
         {
             LinkedListNode<CustomSky> linkedListNode = _activeSkies.First;
             while (linkedListNode != null)
             {
                 CustomSky value = linkedListNode.Value;
                 LinkedListNode<CustomSky> next = linkedListNode.Next;
                 value.Update(gameTime);
                 if (!value.IsActive())
                 {
                     _activeSkies.Remove(linkedListNode);
                 }
                 linkedListNode = next;
             }
         }
     }
References _activeSkies, Main.dayRate, CustomSky.IsActive(), and CustomSky.Update().
Referenced by Main.DoUpdate().