Terraria: System.Xml.Xsl.Runtime.XmlSortKey.BreakSortingTie
BreakSortingTie()
int System.Xml.Xsl.Runtime.XmlSortKey.BreakSortingTie (XmlSortKey that) inline protected inherited
Definition at line 33 of file XmlSortKey.cs.
    {
        if (_nextKey != null)
        {
            return _nextKey.CompareTo(that._nextKey);
        }
        if (_priority >= that._priority)
        {
            return 1;
        }
        return -1;
    }
References System.Xml.Xsl.Runtime.XmlSortKey._nextKey, System.Xml.Xsl.Runtime.XmlSortKey._priority, System.Xml.Xsl.Runtime.XmlSortKey.CompareTo(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Runtime.XmlDecimalSortKey.CompareTo(), System.Xml.Xsl.Runtime.XmlDoubleSortKey.CompareTo(), System.Xml.Xsl.Runtime.XmlEmptySortKey.CompareTo(), System.Xml.Xsl.Runtime.XmlIntegerSortKey.CompareTo(), System.Xml.Xsl.Runtime.XmlIntSortKey.CompareTo(), and System.Xml.Xsl.Runtime.XmlStringSortKey.CompareTo().