Terraria: System.Xml.Xsl.Runtime.DocumentOrderComparer.GetDocumentIndex
GetDocumentIndex()
int System.Xml.Xsl.Runtime.DocumentOrderComparer.GetDocumentIndex (XPathNavigator nav) inline
Definition at line 33 of file DocumentOrderComparer.cs.
    {
        if (_roots == null)
        {
            _roots = new List<XPathNavigator>();
        }
        XPathNavigator xPathNavigator = nav.Clone();
        xPathNavigator.MoveToRoot();
        for (int i = 0; i < _roots.Count; i++)
        {
            if (xPathNavigator.IsSamePosition(_roots[i]))
            {
                return i;
            }
        }
        _roots.Add(xPathNavigator);
        return _roots.Count - 1;
    }
References System.Xml.Xsl.Runtime.DocumentOrderComparer._roots, System.Collections.Generic.List< T >.Add(), System.Xml.XPath.XPathNavigator.Clone(), System.Collections.Generic.List< T >.Count, and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Runtime.DocumentOrderComparer.Compare(), and System.Xml.Xsl.Runtime.XmlQueryRuntime.GenerateId().