Terraria: Terraria.GameContent.UI.Elements.UIBestiaryInfoLine.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIBestiaryInfoLine< T >.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 83 of file UIBestiaryInfoLine.cs.
    {
        CalculatedStyle innerDimensions = GetInnerDimensions();
        Vector2 pos = innerDimensions.Position();
        pos.Y -= 2f * _textScale;
        pos.X += (innerDimensions.Width - _textSize.X) * 0.5f;
        Utils.DrawBorderString(spriteBatch, Text, pos, _color, _textScale);
    }
References Terraria.GameContent.UI.Elements.UIBestiaryInfoLine< T >._color, Terraria.GameContent.UI.Elements.UIBestiaryInfoLine< T >._textScale, Terraria.GameContent.UI.Elements.UIBestiaryInfoLine< T >._textSize, Terraria.Utils.DrawBorderString(), Terraria.UI.UIElement.GetInnerDimensions(), and Terraria.UI.CalculatedStyle.Position().