Terraria: System.Net.HttpRequestStream.HttpRequestStreamAsyncResult.Callback
Callback()
static unsafe void System.Net.HttpRequestStream.HttpRequestStreamAsyncResult.Callback (uint errorCode, uint numBytes, NativeOverlapped * nativeOverlapped) inline static private
Definition at line 82 of file HttpRequestStream.cs.
        {
            HttpRequestStreamAsyncResult httpRequestStreamAsyncResult = (HttpRequestStreamAsyncResult)ThreadPoolBoundHandle.GetNativeOverlappedState(nativeOverlapped);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(null, $"asyncResult: {httpRequestStreamAsyncResult} errorCode:0x {errorCode:x8} numBytes: {numBytes} nativeOverlapped:0x{(IntPtr)nativeOverlapped:x8}", "Callback");
            }
            IOCompleted(httpRequestStreamAsyncResult, errorCode, numBytes);
        }
References System.Net.HttpRequestStream.HttpRequestStreamAsyncResult.HttpRequestStreamAsyncResult(), System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState(), System.Net.NetEventSource.Info(), System.Net.HttpRequestStream.HttpRequestStreamAsyncResult.IOCompleted(), and System.Net.NetEventSource.Log.