Terraria: System.Reflection.Metadata.Ecma335.ControlFlowBuilder.HasSmallExceptionRegions
HasSmallExceptionRegions()
bool System.Reflection.Metadata.Ecma335.ControlFlowBuilder.HasSmallExceptionRegions () inline private
Definition at line 250 of file ControlFlowBuilder.cs.
    {
        if (!ExceptionRegionEncoder.IsSmallRegionCount(_lazyExceptionHandlers.Count))
        {
            return false;
        }
        foreach (ExceptionHandlerInfo lazyExceptionHandler in _lazyExceptionHandlers)
        {
            if (!ExceptionRegionEncoder.IsSmallExceptionRegionFromBounds(GetLabelOffsetChecked(lazyExceptionHandler.TryStart), GetLabelOffsetChecked(lazyExceptionHandler.TryEnd)) || !ExceptionRegionEncoder.IsSmallExceptionRegionFromBounds(GetLabelOffsetChecked(lazyExceptionHandler.HandlerStart), GetLabelOffsetChecked(lazyExceptionHandler.HandlerEnd)))
            {
                return false;
            }
        }
        return true;
    }
References System.Reflection.Metadata.Ecma335.ControlFlowBuilder._lazyExceptionHandlers, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.Ecma335.ControlFlowBuilder.GetLabelOffsetChecked(), System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.IsSmallExceptionRegionFromBounds(), and System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.IsSmallRegionCount().
Referenced by System.Reflection.Metadata.Ecma335.ControlFlowBuilder.SerializeExceptionTable().