Terraria: System.Reflection.Metadata.Ecma335.ControlFlowBuilder.SerializeExceptionTable
SerializeExceptionTable()
void System.Reflection.Metadata.Ecma335.ControlFlowBuilder.SerializeExceptionTable (BlobBuilder builder) inline package
Definition at line 219 of file ControlFlowBuilder.cs.
    {
        if (_lazyExceptionHandlers == null || _lazyExceptionHandlers.Count == 0)
        {
            return;
        }
        ExceptionRegionEncoder exceptionRegionEncoder = ExceptionRegionEncoder.SerializeTableHeader(builder, _lazyExceptionHandlers.Count, HasSmallExceptionRegions());
        foreach (ExceptionHandlerInfo lazyExceptionHandler in _lazyExceptionHandlers)
        {
            int labelOffsetChecked = GetLabelOffsetChecked(lazyExceptionHandler.TryStart);
            int labelOffsetChecked2 = GetLabelOffsetChecked(lazyExceptionHandler.TryEnd);
            int labelOffsetChecked3 = GetLabelOffsetChecked(lazyExceptionHandler.HandlerStart);
            int labelOffsetChecked4 = GetLabelOffsetChecked(lazyExceptionHandler.HandlerEnd);
            if (labelOffsetChecked > labelOffsetChecked2)
            {
                Throw.InvalidOperation(System.SR.Format(System.SR.InvalidExceptionRegionBounds, labelOffsetChecked, labelOffsetChecked2));
            }
            if (labelOffsetChecked3 > labelOffsetChecked4)
            {
                Throw.InvalidOperation(System.SR.Format(System.SR.InvalidExceptionRegionBounds, labelOffsetChecked3, labelOffsetChecked4));
            }
            int catchTokenOrOffset = lazyExceptionHandler.Kind switch
            {
                ExceptionRegionKind.Catch => MetadataTokens.GetToken(lazyExceptionHandler.CatchType),
                ExceptionRegionKind.Filter => GetLabelOffsetChecked(lazyExceptionHandler.FilterStart),
                _ => 0,
            };
            exceptionRegionEncoder.AddUnchecked(lazyExceptionHandler.Kind, labelOffsetChecked, labelOffsetChecked2 - labelOffsetChecked, labelOffsetChecked3, labelOffsetChecked4 - labelOffsetChecked3, catchTokenOrOffset);
        }
    }
References System.Reflection.Metadata.Ecma335.ControlFlowBuilder._lazyExceptionHandlers, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.SR.Format(), System.Reflection.Metadata.Ecma335.ControlFlowBuilder.GetLabelOffsetChecked(), System.Reflection.Metadata.Ecma335.MetadataTokens.GetToken(), System.Reflection.Metadata.Ecma335.ControlFlowBuilder.HasSmallExceptionRegions(), System.SR.InvalidExceptionRegionBounds, System.Reflection.Throw.InvalidOperation(), and System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.SerializeTableHeader().
Referenced by System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.AddMethodBody().