Terraria: System.Reflection.Metadata.Ecma335.ControlFlowBuilder.ValidateLabel
ValidateLabel()
void System.Reflection.Metadata.Ecma335.ControlFlowBuilder.ValidateLabel (LabelHandle label, string parameterName) inline private
Definition at line 125 of file ControlFlowBuilder.cs.
    {
        if (label.IsNil)
        {
            Throw.ArgumentNull(parameterName);
        }
        if (label.Id > _labels.Count)
        {
            Throw.LabelDoesntBelongToBuilder(parameterName);
        }
    }
References System.Reflection.Metadata.Ecma335.ControlFlowBuilder._labels, System.Reflection.Throw.ArgumentNull(), System.Collections.Immutable.ImmutableArray< T >.Count, and System.Reflection.Throw.LabelDoesntBelongToBuilder().
Referenced by System.Reflection.Metadata.Ecma335.ControlFlowBuilder.AddBranch(), System.Reflection.Metadata.Ecma335.ControlFlowBuilder.AddExceptionRegion(), System.Reflection.Metadata.Ecma335.ControlFlowBuilder.AddFilterRegion(), and System.Reflection.Metadata.Ecma335.ControlFlowBuilder.MarkLabel().