Terraria: System.Number.BigInteger.Pow10
Pow10()
static unsafe void System.Number.BigInteger.Pow10 (uint exponent, out BigInteger result) inline static
Definition at line 412 of file Number.cs.
        {
            SetUInt32(out var result2, s_Pow10UInt32Table[exponent & 7]);
            ref BigInteger reference = ref result2;
            SetZero(out var result3);
            ref BigInteger reference2 = ref result3;
            exponent >>= 3;
            uint num = 0u;
            while (exponent != 0)
            {
                if ((exponent & (true ? 1u : 0u)) != 0)
                {
                    fixed (uint* ptr = &s_Pow10BigNumTable[s_Pow10BigNumTableIndices[num]])
                    {
                        Multiply(ref reference, ref *(BigInteger*)ptr, out reference2);
                    }
                    ref BigInteger reference3 = ref reference2;
                    reference2 = ref reference;
                    reference = ref reference3;
                }
                num++;
                exponent >>= 1;
            }
            SetValue(out result, ref reference);
        }
References System.Multiply, System.Number.BigInteger.s_Pow10BigNumTable, System.Number.BigInteger.s_Pow10BigNumTableIndices, System.Number.BigInteger.s_Pow10UInt32Table, System.Number.BigInteger.SetUInt32(), System.Number.BigInteger.SetValue(), and System.Number.BigInteger.SetZero().
Referenced by System.Number.Dragon4(), System.Number.BigInteger.MultiplyPow10(), and System.Number.NumberToFloatingPointBitsSlow().