Terraria: System.Number.BigInteger.Multiply
Multiply() [2/4]
static unsafe void System.Number.BigInteger.Multiply (ref BigInteger lhs, uint value, out BigInteger result) inline static
Definition at line 310 of file Number.cs.
        {
            if (lhs._length <= 1)
            {
                SetUInt64(out result, (ulong)lhs.ToUInt32() * (ulong)value);
                return;
            }
            switch (value)
            {
            case 0u:
                SetZero(out result);
                return;
            case 1u:
                SetValue(out result, ref lhs);
                return;
            }
            int length = lhs._length;
            int i = 0;
            uint num = 0u;
            for (; i < length; i++)
            {
                ulong num2 = (ulong)((long)lhs._blocks[i] * (long)value + num);
                result._blocks[i] = (uint)num2;
                num = (uint)(num2 >> 32);
            }
            if (num != 0)
            {
                result._blocks[i] = num;
                result._length = length + 1;
            }
            else
            {
                result._length = length;
            }
        }
References System.length, System.Number.BigInteger.SetUInt64(), System.Number.BigInteger.SetValue(), System.Number.BigInteger.SetZero(), and System.value.
Referenced by System.Number.Dragon4().