Terraria: System.Number.BigInteger.MultiplyPow10
MultiplyPow10()
void System.Number.BigInteger.MultiplyPow10 (uint exponent) inline
Definition at line 579 of file Number.cs.
        {
            if (exponent <= 9)
            {
                Multiply(s_Pow10UInt32Table[exponent]);
            }
            else if (!IsZero())
            {
                Pow10(exponent, out var result);
                Multiply(ref result);
            }
        }
References System.Number.BigInteger.IsZero(), System.Multiply, System.Number.BigInteger.Pow10(), and System.Number.BigInteger.s_Pow10UInt32Table.
Referenced by System.Number.Dragon4().