Terraria: NetTeleportPylonModule.Deserialize
Deserialize()
override bool NetTeleportPylonModule.Deserialize (BinaryReader reader, int userId) inline virtual
Implements NetModule.
     {
         switch ((SubPacketType)reader.ReadByte())
         {
         case SubPacketType.PylonWasAdded:
         {
             if (Main.dedServ)
             {
                 return false;
             }
             TeleportPylonInfo info3 = default(TeleportPylonInfo);
             info3.PositionInTiles = new Point16(reader.ReadInt16(), reader.ReadInt16());
             info3.TypeOfPylon = (TeleportPylonType)reader.ReadByte();
             Main.PylonSystem.AddForClient(info3);
             break;
         }
         case SubPacketType.PylonWasRemoved:
         {
             if (Main.dedServ)
             {
                 return false;
             }
             TeleportPylonInfo info2 = default(TeleportPylonInfo);
             info2.PositionInTiles = new Point16(reader.ReadInt16(), reader.ReadInt16());
             info2.TypeOfPylon = (TeleportPylonType)reader.ReadByte();
             Main.PylonSystem.RemoveForClient(info2);
             break;
         }
         case SubPacketType.PlayerRequestsTeleport:
         {
             TeleportPylonInfo info = default(TeleportPylonInfo);
             info.PositionInTiles = new Point16(reader.ReadInt16(), reader.ReadInt16());
             info.TypeOfPylon = (TeleportPylonType)reader.ReadByte();
             Main.PylonSystem.HandleTeleportRequest(info, userId);
             break;
         }
         }
         return true;
     }
References TeleportPylonsSystem.AddForClient(), Main.dedServ, TeleportPylonsSystem.HandleTeleportRequest(), TeleportPylonInfo.PositionInTiles, Main.PylonSystem, TeleportPylonsSystem.RemoveForClient(), and TeleportPylonInfo.TypeOfPylon.