Terraria: System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment
ConsumeValueMultiSegment()
bool System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment (byte marker) inline private
Definition at line 2232 of file Utf8JsonReader.cs.
    {
        while (true)
        {
            _trailingCommaBeforeComment = false;
            switch (marker)
            {
            case 34:
                return ConsumeStringMultiSegment();
            case 123:
                StartObject();
                break;
            case 91:
                StartArray();
                break;
            default:
                if (JsonHelpers.IsDigit(marker) || marker == 45)
                {
                    return ConsumeNumberMultiSegment();
                }
                switch (marker)
                {
                case 102:
                    return ConsumeLiteralMultiSegment(JsonConstants.FalseValue, JsonTokenType.False);
                case 116:
                    return ConsumeLiteralMultiSegment(JsonConstants.TrueValue, JsonTokenType.True);
                case 110:
                    return ConsumeLiteralMultiSegment(JsonConstants.NullValue, JsonTokenType.Null);
                }
                switch (_readerOptions.CommentHandling)
                {
                case JsonCommentHandling.Allow:
                    if (marker == 47)
                    {
                        SequencePosition currentPosition2 = _currentPosition;
                        if (!SkipOrConsumeCommentMultiSegmentWithRollback())
{
                            _currentPosition = currentPosition2;
                            return false;
                        }
                        return true;
                    }
                    break;
                default:
                {
                    if (marker != 47)
                    {
                        break;
                    }
                    SequencePosition currentPosition = _currentPosition;
                    if (SkipCommentMultiSegment(out var _))
                    {
                        if (_consumed >= (uint)_buffer.Length)
{
                            if (_isNotPrimitive && IsLastSpan && _tokenType != JsonTokenType.EndArray && _tokenType != JsonTokenType.EndObject)
{
                                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.InvalidEndOfJsonNonPrimitive, 0);
                            }
                            if (!GetNextSpan())
{
                                if (_isNotPrimitive && IsLastSpan && _tokenType != JsonTokenType.EndArray && _tokenType != JsonTokenType.EndObject)
{
                                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.InvalidEndOfJsonNonPrimitive, 0);
                                }
                                _currentPosition = currentPosition;
                                return false;
                            }
                        }
                        marker = _buffer[_consumed];
                        if (marker <= 32)
{
                            SkipWhiteSpaceMultiSegment();
                            if (!HasMoreDataMultiSegment())
{
                                _currentPosition = currentPosition;
                                return false;
                            }
                            marker = _buffer[_consumed];
                        }
                        goto IL_01a8;
                    }
                    _currentPosition = currentPosition;
                    return false;
                }
                case JsonCommentHandling.Disallow:
                    break;
                }
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfValueNotFound, marker);
                break;
            }
            break;
            IL_01a8:
            TokenStartIndex = BytesConsumed;
        }
        return true;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._currentPosition, System.Text.Json.Utf8JsonReader._isNotPrimitive, System.Text.Json.Utf8JsonReader._readerOptions, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._trailingCommaBeforeComment, System.Text.Json.Utf8JsonReader.BytesConsumed, System.Text.Json.JsonReaderOptions.CommentHandling, System.Text.Json.Utf8JsonReader.ConsumeLiteralMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNumberMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeStringMultiSegment(), System.Text.Json.Dictionary, System.Text.Json.JsonConstants.FalseValue, System.Text.Json.Utf8JsonReader.GetNextSpan(), System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment(), System.Text.Json.JsonHelpers.IsDigit(), System.Text.Json.Utf8JsonReader.IsLastSpan, System.ReadOnlySpan< T >.Length, System.Text.Json.JsonConstants.NullValue, System.Text.Json.Utf8JsonReader.SkipCommentMultiSegment(), System.Text.Json.Utf8JsonReader.SkipOrConsumeCommentMultiSegmentWithRollback(), System.Text.Json.Utf8JsonReader.SkipWhiteSpaceMultiSegment(), System.Text.Json.Utf8JsonReader.StartArray(), System.Text.Json.Utf8JsonReader.StartObject(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), System.Text.Json.Utf8JsonReader.TokenStartIndex, and System.Text.Json.JsonConstants.TrueValue.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkippedMultiSegment(), System.Text.Json.Utf8JsonReader.ReadFirstTokenMultiSegment(), and System.Text.Json.Utf8JsonReader.ReadMultiSegment().