Terraria: System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentToken
ConsumeNextTokenFromLastNonCommentToken()
ConsumeTokenResult System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentToken () inline private
Definition at line 1373 of file Utf8JsonReader.cs.
    {
        if (JsonReaderHelper.IsTokenTypePrimitive(_previousTokenType))
        {
            _tokenType = (_inObject ? JsonTokenType.StartObject : JsonTokenType.StartArray);
        }
        else
        {
            _tokenType = _previousTokenType;
        }
        if (HasMoreData())
        {
            byte b = _buffer[_consumed];
            if (b <= 32)
            {
                SkipWhiteSpace();
                if (!HasMoreData())
                {
                    goto IL_0343;
                }
                b = _buffer[_consumed];
            }
            if (_bitStack.CurrentDepth == 0 && _tokenType != 0)
            {
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedEndAfterSingleJson, b);
            }
            TokenStartIndex = _consumed;
            if (b != 44)
            {
                if (b == 125)
                {
                    EndObject();
                }
                else
                {
                    if (b != 93)
                    {
                        if (_tokenType == JsonTokenType.None)
{
                            if (ReadFirstToken(b))
{
                                goto IL_0341;
                            }
                        }
                        else if (_tokenType == JsonTokenType.StartObject)
{
                            if (b != 34)
{
                                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyNotFound, b);
                            }
                            int consumed = _consumed;
                            long bytePositionInLine = _bytePositionInLine;
                            long lineNumber = _lineNumber;
                            if (ConsumePropertyName())
{
                                goto IL_0341;
                            }
                            _consumed = consumed;
                            _tokenType = JsonTokenType.StartObject;
                            _bytePositionInLine = bytePositionInLine;
                            _lineNumber = lineNumber;
                        }
                        else if (_tokenType == JsonTokenType.StartArray)
{
                            if (ConsumeValue(b))
{
                                goto IL_0341;
                            }
                        }
                        else if (_tokenType == JsonTokenType.PropertyName)
{
                            if (ConsumeValue(b))
{
                                goto IL_0341;
                            }
                        }
                        else if (_inObject)
{
                            if (b != 34)
{
                                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyNotFound, b);
                            }
                            if (ConsumePropertyName())
{
                                goto IL_0341;
                            }
                        }
                        else if (ConsumeValue(b))
{
                            goto IL_0341;
                        }
                        goto IL_0343;
                    }
                    EndArray();
                }
                goto IL_0341;
            }
            if ((int)_previousTokenType <= 1 || _previousTokenType == JsonTokenType.StartArray || _trailingCommaBeforeComment)
            {
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyOrValueAfterComment, b);
            }
            _consumed++;
            _bytePositionInLine++;
            if (_consumed >= (uint)_buffer.Length)
            {
                if (IsLastSpan)
                {
                    _consumed--;
                    _bytePositionInLine--;
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyOrValueNotFound, 0);
                }
            }
            else
            {
                b = _buffer[_consumed];
                if (b <= 32)
                {
                    SkipWhiteSpace();
                    if (!HasMoreData(ExceptionResource.ExpectedStartOfPropertyOrValueNotFound))
                    {
                        goto IL_0343;
                    }
                    b = _buffer[_consumed];
                }
                TokenStartIndex = _consumed;
                if (b == 47)
                {
                    _trailingCommaBeforeComment = true;
                    if (ConsumeComment())
                    {
                        goto IL_0341;
                    }
                }
                else if (_inObject)
                {
                    if (b != 34)
                    {
                        if (b == 125)
{
                            if (_readerOptions.AllowTrailingCommas)
{
                                EndObject();
                                goto IL_0341;
                            }
                            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.TrailingCommaNotAllowedBeforeObjectEnd, 0);
                        }
                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyNotFound, b);
                    }
                    if (ConsumePropertyName())
                    {
                        goto IL_0341;
                    }
                }
                else
                {
                    if (b == 93)
                    {
                        if (_readerOptions.AllowTrailingCommas)
{
                            EndArray();
                            goto IL_0341;
                        }
                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.TrailingCommaNotAllowedBeforeArrayEnd, 0);
                    }
                    if (ConsumeValue(b))
                    {
                        goto IL_0341;
                    }
                }
            }
        }
        goto IL_0343;
        IL_0343:
        return ConsumeTokenResult.NotEnoughDataRollBackState;
        IL_0341:
        return ConsumeTokenResult.Success;
    }
References System.Text.Json.Utf8JsonReader._bitStack, System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._inObject, System.Text.Json.Utf8JsonReader._lineNumber, System.Text.Json.Utf8JsonReader._previousTokenType, System.Text.Json.Utf8JsonReader._readerOptions, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._trailingCommaBeforeComment, System.Text.Json.JsonReaderOptions.AllowTrailingCommas, System.Text.Json.Utf8JsonReader.ConsumeComment(), System.Text.Json.Utf8JsonReader.ConsumePropertyName(), System.Text.Json.Utf8JsonReader.ConsumeValue(), System.Text.Json.BitStack.CurrentDepth, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.EndArray(), System.Text.Json.Utf8JsonReader.EndObject(), System.Text.Json.Utf8JsonReader.HasMoreData(), System.Text.Json.Utf8JsonReader.IsLastSpan, System.Text.Json.JsonReaderHelper.IsTokenTypePrimitive(), System.ReadOnlySpan< T >.Length, System.Text.Json.Utf8JsonReader.ReadFirstToken(), System.Text.Json.Utf8JsonReader.SkipWhiteSpace(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), and System.Text.Json.Utf8JsonReader.TokenStartIndex.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextToken().