Terraria: System.Text.Json.Utf8JsonReader.ConsumePropertyName
ConsumePropertyName()
bool System.Text.Json.Utf8JsonReader.ConsumePropertyName () inline private
Definition at line 873 of file Utf8JsonReader.cs.
    {
        _trailingCommaBeforeComment = false;
        if (!ConsumeString())
        {
            return false;
        }
        if (!HasMoreData(ExceptionResource.ExpectedValueAfterPropertyNameNotFound))
        {
            return false;
        }
        byte b = _buffer[_consumed];
        if (b <= 32)
        {
            SkipWhiteSpace();
            if (!HasMoreData(ExceptionResource.ExpectedValueAfterPropertyNameNotFound))
            {
                return false;
            }
            b = _buffer[_consumed];
        }
        if (b != 58)
        {
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedSeparatorAfterPropertyNameNotFound, b);
        }
        _consumed++;
        _bytePositionInLine++;
        _tokenType = JsonTokenType.PropertyName;
        return true;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._trailingCommaBeforeComment, System.Text.Json.Utf8JsonReader.ConsumeString(), System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.HasMoreData(), System.Text.Json.Utf8JsonReader.SkipWhiteSpace(), and System.Text.Json.ThrowHelper.ThrowJsonReaderException().
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextToken(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentToken(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(), and System.Text.Json.Utf8JsonReader.ReadSingleSegment().