Terraria: System.Text.Json.Utf8JsonReader.ConsumeLiteralMultiSegment
ConsumeLiteralMultiSegment()
bool System.Text.Json.Utf8JsonReader.ConsumeLiteralMultiSegment (ReadOnlySpan< byte > literal, JsonTokenType tokenType) inline private
Definition at line 2329 of file Utf8JsonReader.cs.
    {
        ReadOnlySpan<byte> span = _buffer.Slice(_consumed);
        int consumed = literal.Length;
        if (!span.StartsWith(literal))
        {
            int consumed2 = _consumed;
            if (!CheckLiteralMultiSegment(span, literal, out consumed))
            {
                _consumed = consumed2;
                return false;
            }
        }
        else
        {
            ValueSpan = span.Slice(0, literal.Length);
            HasValueSequence = false;
        }
        _tokenType = tokenType;
        _consumed += consumed;
        _bytePositionInLine += consumed;
        return true;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader.CheckLiteralMultiSegment(), System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.HasValueSequence, System.ReadOnlySpan< T >.Slice(), and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment().