Terraria: System.Text.Json.Utf8JsonReader.CheckLiteralMultiSegment
CheckLiteralMultiSegment()
bool System.Text.Json.Utf8JsonReader.CheckLiteralMultiSegment (ReadOnlySpan< byte > span, ReadOnlySpan< byte > literal, out int consumed) inline private
Definition at line 2353 of file Utf8JsonReader.cs.
    {
        Span<byte> destination = stackalloc byte[5];
        int num = 0;
        long totalConsumed = _totalConsumed;
        SequencePosition currentPosition = _currentPosition;
        if (span.Length >= literal.Length || IsLastSpan)
        {
            _bytePositionInLine += FindMismatch(span, literal);
            int num2 = Math.Min(span.Length, (int)_bytePositionInLine + 1);
            span.Slice(0, num2).CopyTo(destination);
            num += num2;
        }
        else if (!literal.StartsWith(span))
        {
            _bytePositionInLine += FindMismatch(span, literal);
            int num3 = Math.Min(span.Length, (int)_bytePositionInLine + 1);
            span.Slice(0, num3).CopyTo(destination);
            num += num3;
        }
        else
        {
            ReadOnlySpan<byte> readOnlySpan = literal.Slice(span.Length);
            SequencePosition currentPosition2 = _currentPosition;
            int consumed2 = _consumed;
            int num4 = literal.Length - readOnlySpan.Length;
            while (true)
            {
                _totalConsumed += num4;
                _bytePositionInLine += num4;
                if (!GetNextSpan())
                {
                    _totalConsumed = totalConsumed;
                    consumed = 0;
                    _currentPosition = currentPosition;
                    if (IsLastSpan)
                    {
                        break;
                    }
                    return false;
                }
                int num5 = Math.Min(span.Length, destination.Length - num);
                span.Slice(0, num5).CopyTo(destination.Slice(num));
                num += num5;
                span = _buffer;
                if (span.StartsWith(readOnlySpan))
                {
                    HasValueSequence = true;
                    SequencePosition start = new SequencePosition(currentPosition2.GetObject(), currentPosition2.GetInteger() + consumed2);
                    SequencePosition end = new SequencePosition(_currentPosition.GetObject(), _currentPosition.GetInteger() + readOnlySpan.Length);
                    ValueSequence = _sequence.Slice(start, end);
                    consumed = readOnlySpan.Length;
                    return true;
                }
                if (!readOnlySpan.StartsWith(span))
                {
                    _bytePositionInLine += FindMismatch(span, readOnlySpan);
                    num5 = Math.Min(span.Length, (int)_bytePositionInLine + 1);
                    span.Slice(0, num5).CopyTo(destination.Slice(num));
                    num += num5;
                    break;
                }
                readOnlySpan = readOnlySpan.Slice(span.Length);
                num4 = span.Length;
            }
        }
        _totalConsumed = totalConsumed;
        consumed = 0;
        _currentPosition = currentPosition;
        throw GetInvalidLiteralMultiSegment(destination.Slice(0, num).ToArray());
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._currentPosition, System.Text.Json.Utf8JsonReader._sequence, System.Text.Json.Utf8JsonReader._totalConsumed, System.destination, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.FindMismatch(), System.SequencePosition.GetInteger(), System.Text.Json.Utf8JsonReader.GetInvalidLiteralMultiSegment(), System.Text.Json.Utf8JsonReader.GetNextSpan(), System.SequencePosition.GetObject(), System.Text.Json.Utf8JsonReader.HasValueSequence, System.Text.Json.Utf8JsonReader.IsLastSpan, System.Math.Min(), System.ReadOnlySpan< T >.Slice(), System.Buffers.ReadOnlySequence< T >.Slice(), System.start, and System.Text.Json.Utf8JsonReader.ValueSequence.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeLiteralMultiSegment().