Terraria: System.Text.Json.Utf8JsonReader.ConsumeNumber
ConsumeNumber()
bool System.Text.Json.Utf8JsonReader.ConsumeNumber () inline private
Definition at line 857 of file Utf8JsonReader.cs.
    {
        if (!TryGetNumber(_buffer.Slice(_consumed), out var consumed))
        {
            return false;
        }
        _tokenType = JsonTokenType.Number;
        _consumed += consumed;
        _bytePositionInLine += consumed;
        if (_consumed >= (uint)_buffer.Length && _isNotPrimitive)
        {
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedEndOfDigitNotFound, _buffer[_consumed - 1]);
        }
        return true;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._isNotPrimitive, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Dictionary, System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), and System.Text.Json.Utf8JsonReader.TryGetNumber().
Referenced by System.Text.Json.Utf8JsonReader.ConsumeValue().