Terraria: System.Text.Json.Utf8JsonReader.StartArray
StartArray()
void System.Text.Json.Utf8JsonReader.StartArray () inline private
Definition at line 504 of file Utf8JsonReader.cs.
    {
        if (_bitStack.CurrentDepth >= _readerOptions.MaxDepth)
        {
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ArrayDepthTooLarge, 0);
        }
        _bitStack.PushFalse();
        ValueSpan = _buffer.Slice(_consumed, 1);
        _consumed++;
        _bytePositionInLine++;
        _tokenType = JsonTokenType.StartArray;
        _inObject = false;
    }
References System.Text.Json.Utf8JsonReader._bitStack, System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._inObject, System.Text.Json.Utf8JsonReader._readerOptions, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.BitStack.CurrentDepth, System.Text.Json.Dictionary, System.Text.Json.JsonReaderOptions.MaxDepth, System.Text.Json.BitStack.PushFalse(), System.ReadOnlySpan< T >.Slice(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeValue(), and System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment().