Terraria: System.Text.Json.Utf8JsonReader.TryGetGuidCore
TryGetGuidCore()
bool System.Text.Json.Utf8JsonReader.TryGetGuidCore (out Guid value) inline package
Definition at line 4873 of file Utf8JsonReader.cs.
    {
        ReadOnlySpan<byte> readOnlySpan = default(Span<byte>);
        int num = (_stringHasEscaping ? 216 : 36);
        if (HasValueSequence)
        {
            long length = ValueSequence.Length;
            if (length > num)
            {
                value = default(Guid);
                return false;
            }
            Span<byte> destination = stackalloc byte[_stringHasEscaping ? 216 : 36];
            ReadOnlySequence<byte> source = ValueSequence;
            source.CopyTo(destination);
            readOnlySpan = destination.Slice(0, (int)length);
        }
        else
        {
            if (ValueSpan.Length > num)
            {
                value = default(Guid);
                return false;
            }
            readOnlySpan = ValueSpan;
        }
        if (_stringHasEscaping)
        {
            return JsonReaderHelper.TryGetEscapedGuid(readOnlySpan, out value);
        }
        if (readOnlySpan.Length == 36 && Utf8Parser.TryParse(readOnlySpan, out Guid value2, out int _, 'D'))
        {
            value = value2;
            return true;
        }
        value = default(Guid);
        return false;
    }
References System.Text.Json.Utf8JsonReader._stringHasEscaping, System.destination, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.HasValueSequence, System.Buffers.ReadOnlySequence< T >.Length, System.length, System.ReadOnlySpan< T >.Length, System.Buffers.ReadOnlySequence< T >.Slice(), System.source, System.Text.Json.JsonReaderHelper.TryGetEscapedGuid(), System.Buffers.Text.Utf8Parser.TryParse(), System.value, System.Text.Json.Utf8JsonReader.ValueSequence, and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.GetGuidNoValidation(), and System.Text.Json.Utf8JsonReader.TryGetGuid().