Terraria: System.Text.Json.Utf8JsonReader.SkipComment
SkipComment()
bool System.Text.Json.Utf8JsonReader.SkipComment () inline private
Definition at line 1742 of file Utf8JsonReader.cs.
    {
        ReadOnlySpan<byte> readOnlySpan = _buffer.Slice(_consumed + 1);
        if (readOnlySpan.Length > 0)
        {
            int idx;
            switch (readOnlySpan[0])
            {
            case 47:
                return SkipSingleLineComment(readOnlySpan.Slice(1), out idx);
            case 42:
                return SkipMultiLineComment(readOnlySpan.Slice(1), out idx);
            }
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfValueNotFound, 47);
        }
        if (IsLastSpan)
        {
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfValueNotFound, 47);
        }
        return false;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.IsLastSpan, System.Text.Json.Utf8JsonReader.SkipMultiLineComment(), System.Text.Json.Utf8JsonReader.SkipSingleLineComment(), System.ReadOnlySpan< T >.Slice(), and System.Text.Json.ThrowHelper.ThrowJsonReaderException().
Referenced by System.Text.Json.Utf8JsonReader.ConsumeValue(), System.Text.Json.Utf8JsonReader.SkipAllComments(), and System.Text.Json.Utf8JsonReader.SkipAllComments().