Terraria: System.Text.Json.Utf8JsonReader.SkipAllCommentsMultiSegment
SkipAllCommentsMultiSegment() [1/2]
bool System.Text.Json.Utf8JsonReader.SkipAllCommentsMultiSegment (ref byte marker) inline private
Definition at line 3498 of file Utf8JsonReader.cs.
    {
        while (true)
        {
            if (marker == 47)
            {
                if (!SkipOrConsumeCommentMultiSegmentWithRollback() || !HasMoreDataMultiSegment())
                {
                    break;
                }
                marker = _buffer[_consumed];
                if (marker <= 32)
                {
                    SkipWhiteSpaceMultiSegment();
                    if (!HasMoreDataMultiSegment())
                    {
                        break;
                    }
                    marker = _buffer[_consumed];
                }
                continue;
            }
            return true;
        }
        return false;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment(), System.Text.Json.Utf8JsonReader.SkipOrConsumeCommentMultiSegmentWithRollback(), and System.Text.Json.Utf8JsonReader.SkipWhiteSpaceMultiSegment().
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkippedMultiSegment().