Terraria: System.Text.Json.Utf8JsonReader.ReadSingleSegment
ReadSingleSegment()
bool System.Text.Json.Utf8JsonReader.ReadSingleSegment () inline private
Definition at line 545 of file Utf8JsonReader.cs.
    {
        bool flag = false;
        ValueSpan = default(ReadOnlySpan<byte>);
        if (HasMoreData())
        {
            byte b = _buffer[_consumed];
            if (b <= 32)
            {
                SkipWhiteSpace();
                if (!HasMoreData())
                {
                    goto IL_0132;
                }
                b = _buffer[_consumed];
            }
            TokenStartIndex = _consumed;
            if (_tokenType != 0)
            {
                if (b == 47)
                {
                    flag = ConsumeNextTokenOrRollback(b);
                }
                else if (_tokenType == JsonTokenType.StartObject)
                {
                    if (b == 125)
                    {
                        EndObject();
                        goto IL_0130;
                    }
                    if (b != 34)
                    {
                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyNotFound, b);
                    }
                    int consumed = _consumed;
                    long bytePositionInLine = _bytePositionInLine;
                    long lineNumber = _lineNumber;
                    flag = ConsumePropertyName();
                    if (!flag)
                    {
                        _consumed = consumed;
                        _tokenType = JsonTokenType.StartObject;
                        _bytePositionInLine = bytePositionInLine;
                        _lineNumber = lineNumber;
                    }
                }
                else if (_tokenType != JsonTokenType.StartArray)
                {
                    flag = ((_tokenType != JsonTokenType.PropertyName) ? ConsumeNextTokenOrRollback(b) : ConsumeValue(b));
                }
                else
                {
                    if (b == 93)
                    {
                        EndArray();
                        goto IL_0130;
                    }
                    flag = ConsumeValue(b);
                }
            }
            else
            {
                flag = ReadFirstToken(b);
            }
        }
        goto IL_0132;
        IL_0132:
        return flag;
        IL_0130:
        flag = true;
        goto IL_0132;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._lineNumber, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(), System.Text.Json.Utf8JsonReader.ConsumePropertyName(), System.Text.Json.Utf8JsonReader.ConsumeValue(), System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.EndArray(), System.Text.Json.Utf8JsonReader.EndObject(), System.Text.Json.Utf8JsonReader.HasMoreData(), System.Text.Json.Utf8JsonReader.ReadFirstToken(), System.Text.Json.Utf8JsonReader.SkipWhiteSpace(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), System.Text.Json.Utf8JsonReader.TokenStartIndex, and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.Read().