Terraria: System.Text.Json.Utf8JsonReader.SkipMultiLineCommentMultiSegment
SkipMultiLineCommentMultiSegment()
bool System.Text.Json.Utf8JsonReader.SkipMultiLineCommentMultiSegment (ReadOnlySpan< byte > localBuffer) inline private
Definition at line 3941 of file Utf8JsonReader.cs.
    {
        bool flag = false;
        bool flag2 = false;
        while (true)
        {
            if (flag)
            {
                if (localBuffer[0] == 47)
                {
                    _consumed++;
                    _bytePositionInLine++;
                    return true;
                }
                flag = false;
            }
            if (flag2)
            {
                if (localBuffer[0] == 10)
                {
                    _consumed++;
                    localBuffer = localBuffer.Slice(1);
                }
                flag2 = false;
            }
            int num = localBuffer.IndexOfAny<byte>(42, 10, 13);
            if (num != -1)
            {
                int num2 = num + 1;
                byte b = localBuffer[num];
                localBuffer = localBuffer.Slice(num2);
                _consumed += num2;
                switch (b)
                {
                case 42:
                    flag = true;
                    _bytePositionInLine += num2;
                    break;
                case 10:
                    _bytePositionInLine = 0L;
                    _lineNumber++;
                    break;
                default:
                    _bytePositionInLine = 0L;
                    _lineNumber++;
                    flag2 = true;
                    break;
                }
            }
            else
            {
                _consumed += localBuffer.Length;
                _bytePositionInLine += localBuffer.Length;
                localBuffer = ReadOnlySpan<byte>.Empty;
            }
            if (!localBuffer.IsEmpty)
            {
                continue;
            }
            if (IsLastSpan)
            {
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.UnexpectedEndOfDataWhileReadingComment, 0);
            }
            if (!GetNextSpan())
            {
                if (!IsLastSpan)
                {
                    break;
                }
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.UnexpectedEndOfDataWhileReadingComment, 0);
            }
            localBuffer = _buffer;
        }
        return false;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._lineNumber, System.Text.Json.Dictionary, System.ReadOnlySpan< T >.Empty, System.Text.Json.Utf8JsonReader.GetNextSpan(), System.Text.Json.Utf8JsonReader.IsLastSpan, System.L, and System.Text.Json.ThrowHelper.ThrowJsonReaderException().
Referenced by System.Text.Json.Utf8JsonReader.SkipCommentMultiSegment().