Terraria: System.Text.Json.Utf8JsonReader.TryGetNumberMultiSegment
TryGetNumberMultiSegment()
bool System.Text.Json.Utf8JsonReader.TryGetNumberMultiSegment (ReadOnlySpan< byte > data, out int consumed) inline private
Definition at line 2813 of file Utf8JsonReader.cs.
    {
        PartialStateForRollback rollBackState = CaptureState();
        consumed = 0;
        int i = 0;
        ConsumeNumberResult consumeNumberResult = ConsumeNegativeSignMultiSegment(ref data, ref i, in rollBackState);
        if (consumeNumberResult == ConsumeNumberResult.NeedMoreData)
        {
            RollBackState(in rollBackState);
            return false;
        }
        byte b = data[i];
        if (b == 48)
        {
            ConsumeNumberResult consumeNumberResult2 = ConsumeZeroMultiSegment(ref data, ref i, in rollBackState);
            if (consumeNumberResult2 == ConsumeNumberResult.NeedMoreData)
            {
                RollBackState(in rollBackState);
                return false;
            }
            if (consumeNumberResult2 != 0)
            {
                b = data[i];
                goto IL_00bf;
            }
        }
        else
        {
            ConsumeNumberResult consumeNumberResult3 = ConsumeIntegerDigitsMultiSegment(ref data, ref i);
            if (consumeNumberResult3 == ConsumeNumberResult.NeedMoreData)
            {
                RollBackState(in rollBackState);
                return false;
            }
            if (consumeNumberResult3 != 0)
            {
                b = data[i];
                if (b != 46 && b != 69 && b != 101)
                {
                    RollBackState(in rollBackState, isError: true);
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedEndOfDigitNotFound, b);
                }
                goto IL_00bf;
            }
        }
        goto IL_01b1;
        IL_00bf:
        if (b == 46)
        {
            i++;
            _bytePositionInLine++;
            ConsumeNumberResult consumeNumberResult4 = ConsumeDecimalDigitsMultiSegment(ref data, ref i, in rollBackState);
            if (consumeNumberResult4 == ConsumeNumberResult.NeedMoreData)
            {
                RollBackState(in rollBackState);
                return false;
            }
            if (consumeNumberResult4 == ConsumeNumberResult.Success)
            {
                goto IL_01b1;
            }
            b = data[i];
            if (b != 69 && b != 101)
            {
                RollBackState(in rollBackState, isError: true);
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedNextDigitEValueNotFound, b);
            }
        }
        i++;
        _bytePositionInLine++;
        consumeNumberResult = ConsumeSignMultiSegment(ref data, ref i, in rollBackState);
        if (consumeNumberResult == ConsumeNumberResult.NeedMoreData)
        {
            RollBackState(in rollBackState);
            return false;
        }
        i++;
        _bytePositionInLine++;
        switch (ConsumeIntegerDigitsMultiSegment(ref data, ref i))
        {
        case ConsumeNumberResult.NeedMoreData:
            RollBackState(in rollBackState);
            return false;
        default:
            RollBackState(in rollBackState, isError: true);
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedEndOfDigitNotFound, data[i]);
            break;
        case ConsumeNumberResult.Success:
            break;
        }
        goto IL_01b1;
        IL_01b1:
        if (HasValueSequence)
        {
            SequencePosition startPosition = rollBackState.GetStartPosition();
            SequencePosition end = new SequencePosition(_currentPosition.GetObject(), _currentPosition.GetInteger() + i);
            ValueSequence = _sequence.Slice(startPosition, end);
            consumed = i;
        }
        else
        {
            ValueSpan = data.Slice(0, i);
            consumed = i;
        }
        return true;
    }
References System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._currentPosition, System.Text.Json.Utf8JsonReader._sequence, System.Text.Json.Utf8JsonReader.CaptureState(), System.Text.Json.Utf8JsonReader.ConsumeDecimalDigitsMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeIntegerDigitsMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNegativeSignMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeSignMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeZeroMultiSegment(), System.Text.Json.Dictionary, System.SequencePosition.GetInteger(), System.SequencePosition.GetObject(), System.Text.Json.Utf8JsonReader.HasValueSequence, System.Text.Json.Utf8JsonReader.RollBackState(), System.ReadOnlySpan< T >.Slice(), System.Buffers.ReadOnlySequence< T >.Slice(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), System.Text.Json.Utf8JsonReader.ValueSequence, and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNumberMultiSegment(), and System.Text.Json.Utf8JsonReader.ReadFirstTokenMultiSegment().