Terraria: System.Text.Json.Utf8JsonReader.TryGetDateTimeCore
TryGetDateTimeCore()
bool System.Text.Json.Utf8JsonReader.TryGetDateTimeCore (out DateTime value) inline package
Definition at line 4777 of file Utf8JsonReader.cs.
    {
        ReadOnlySpan<byte> readOnlySpan = default(Span<byte>);
        int num = (_stringHasEscaping ? 252 : 42);
        if (HasValueSequence)
        {
            long length = ValueSequence.Length;
            if (!JsonHelpers.IsInRangeInclusive(length, 10L, num))
            {
                value = default(DateTime);
                return false;
            }
            Span<byte> destination = stackalloc byte[_stringHasEscaping ? 252 : 42];
            ReadOnlySequence<byte> source = ValueSequence;
            source.CopyTo(destination);
            readOnlySpan = destination.Slice(0, (int)length);
        }
        else
        {
            if (!JsonHelpers.IsInRangeInclusive(ValueSpan.Length, 10, num))
            {
                value = default(DateTime);
                return false;
            }
            readOnlySpan = ValueSpan;
        }
        if (_stringHasEscaping)
        {
            return JsonReaderHelper.TryGetEscapedDateTime(readOnlySpan, out value);
        }
        if (JsonHelpers.TryParseAsISO(readOnlySpan, out DateTime value2))
        {
            value = value2;
            return true;
        }
        value = default(DateTime);
        return false;
    }
References System.Text.Json.Utf8JsonReader._stringHasEscaping, System.destination, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.HasValueSequence, System.Text.Json.JsonHelpers.IsInRangeInclusive(), System.L, System.Buffers.ReadOnlySequence< T >.Length, System.length, System.ReadOnlySpan< T >.Length, System.Buffers.ReadOnlySequence< T >.Slice(), System.source, System.Text.Json.JsonReaderHelper.TryGetEscapedDateTime(), System.Text.Json.JsonHelpers.TryParseAsISO(), System.value, System.Text.Json.Utf8JsonReader.ValueSequence, and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.GetDateTimeNoValidation(), and System.Text.Json.Utf8JsonReader.TryGetDateTime().