Terraria: System.Text.Json.Utf8JsonReader.ConsumeString
ConsumeString()
bool System.Text.Json.Utf8JsonReader.ConsumeString () inline private
Definition at line 904 of file Utf8JsonReader.cs.
    {
        ReadOnlySpan<byte> readOnlySpan = _buffer.Slice(_consumed + 1);
        int num = readOnlySpan.IndexOfQuoteOrAnyControlOrBackSlash();
        if (num >= 0)
        {
            byte b = readOnlySpan[num];
            if (b == 34)
            {
                _bytePositionInLine += num + 2;
                ValueSpan = readOnlySpan.Slice(0, num);
                _stringHasEscaping = false;
                _tokenType = JsonTokenType.String;
                _consumed += num + 2;
                return true;
            }
            return ConsumeStringAndValidate(readOnlySpan, num);
        }
        if (IsLastSpan)
        {
            _bytePositionInLine += readOnlySpan.Length + 1;
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.EndOfStringNotFound, 0);
        }
        return false;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._stringHasEscaping, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(), System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.IsLastSpan, System.ReadOnlySpan< T >.Slice(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.ConsumePropertyName(), and System.Text.Json.Utf8JsonReader.ConsumeValue().