Terraria: System.Text.Json.Utf8JsonReader.ConsumeComment
ConsumeComment()
bool System.Text.Json.Utf8JsonReader.ConsumeComment () inline private
Definition at line 1876 of file Utf8JsonReader.cs.
    {
        ReadOnlySpan<byte> readOnlySpan = _buffer.Slice(_consumed + 1);
        if (readOnlySpan.Length > 0)
        {
            byte b = readOnlySpan[0];
            switch (b)
            {
            case 47:
                return ConsumeSingleLineComment(readOnlySpan.Slice(1), _consumed);
            case 42:
                return ConsumeMultiLineComment(readOnlySpan.Slice(1), _consumed);
            }
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.InvalidCharacterAtStartOfComment, b);
        }
        if (IsLastSpan)
        {
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.UnexpectedEndOfDataWhileReadingComment, 0);
        }
        return false;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader.ConsumeMultiLineComment(), System.Text.Json.Utf8JsonReader.ConsumeSingleLineComment(), System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.IsLastSpan, System.ReadOnlySpan< T >.Slice(), and System.Text.Json.ThrowHelper.ThrowJsonReaderException().
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextToken(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentToken(), and System.Text.Json.Utf8JsonReader.ConsumeValue().