Terraria: System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkippedMultiSegment
ConsumeNextTokenUntilAfterAllCommentsAreSkippedMultiSegment()
ConsumeTokenResult System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkippedMultiSegment (byte marker) inline private
Definition at line 3552 of file Utf8JsonReader.cs.
    {
        if (SkipAllCommentsMultiSegment(ref marker))
        {
            TokenStartIndex = BytesConsumed;
            if (_tokenType == JsonTokenType.StartObject)
            {
                if (marker == 125)
                {
                    EndObject();
                }
                else
                {
                    if (marker != 34)
                    {
                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyNotFound, marker);
                    }
                    long totalConsumed = _totalConsumed;
                    int consumed = _consumed;
                    long bytePositionInLine = _bytePositionInLine;
                    long lineNumber = _lineNumber;
                    SequencePosition currentPosition = _currentPosition;
                    if (!ConsumePropertyNameMultiSegment())
                    {
                        _consumed = consumed;
                        _tokenType = JsonTokenType.StartObject;
                        _bytePositionInLine = bytePositionInLine;
                        _lineNumber = lineNumber;
                        _totalConsumed = totalConsumed;
                        _currentPosition = currentPosition;
                        goto IL_02e7;
                    }
                }
            }
            else if (_tokenType == JsonTokenType.StartArray)
            {
                if (marker == 93)
                {
                    EndArray();
                }
                else if (!ConsumeValueMultiSegment(marker))
                {
                    goto IL_02e7;
                }
            }
            else if (_tokenType == JsonTokenType.PropertyName)
            {
                if (!ConsumeValueMultiSegment(marker))
                {
                    goto IL_02e7;
                }
            }
            else if (_bitStack.CurrentDepth == 0)
            {
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedEndAfterSingleJson, marker);
            }
            else
            {
                switch (marker)
                {
                case 44:
                    _consumed++;
                    _bytePositionInLine++;
                    if (_consumed >= (uint)_buffer.Length)
                    {
                        if (IsLastSpan)
{
                            _consumed--;
                            _bytePositionInLine--;
                            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyOrValueNotFound, 0);
                        }
                        if (!GetNextSpan())
{
                            if (IsLastSpan)
{
                                _consumed--;
                                _bytePositionInLine--;
                                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyOrValueNotFound, 0);
                            }
                            return ConsumeTokenResult.NotEnoughDataRollBackState;
                        }
                    }
                    marker = _buffer[_consumed];
                    if (marker <= 32)
                    {
                        SkipWhiteSpaceMultiSegment();
                        if (!HasMoreDataMultiSegment(ExceptionResource.ExpectedStartOfPropertyOrValueNotFound))
{
                            return ConsumeTokenResult.NotEnoughDataRollBackState;
                        }
                        marker = _buffer[_consumed];
                    }
                    if (SkipAllCommentsMultiSegment(ref marker, ExceptionResource.ExpectedStartOfPropertyOrValueNotFound))
                    {
                        TokenStartIndex = BytesConsumed;
                        if (_inObject)
{
                            if (marker != 34)
{
                                if (marker == 125)
{
                                    if (_readerOptions.AllowTrailingCommas)
{
                                        EndObject();
                                        break;
                                    }
                                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.TrailingCommaNotAllowedBeforeObjectEnd, 0);
                                }
                                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyNotFound, marker);
                            }
                            if (!ConsumePropertyNameMultiSegment())
{
                                return ConsumeTokenResult.NotEnoughDataRollBackState;
                            }
                            return ConsumeTokenResult.Success;
                        }
                        if (marker == 93)
{
                            if (_readerOptions.AllowTrailingCommas)
{
                                EndArray();
                                break;
                            }
                            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.TrailingCommaNotAllowedBeforeArrayEnd, 0);
                        }
                        if (!ConsumeValueMultiSegment(marker))
{
                            return ConsumeTokenResult.NotEnoughDataRollBackState;
                        }
                        return ConsumeTokenResult.Success;
                    }
                    return ConsumeTokenResult.NotEnoughDataRollBackState;
                case 125:
                    EndObject();
                    break;
                case 93:
                    EndArray();
                    break;
                default:
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.FoundInvalidCharacter, marker);
                    break;
                }
            }
            return ConsumeTokenResult.Success;
        }
        goto IL_02e7;
        IL_02e7:
        return ConsumeTokenResult.IncompleteNoRollBackNecessary;
    }
References System.Text.Json.Utf8JsonReader._bitStack, System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._currentPosition, System.Text.Json.Utf8JsonReader._inObject, System.Text.Json.Utf8JsonReader._lineNumber, System.Text.Json.Utf8JsonReader._readerOptions, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._totalConsumed, System.Text.Json.JsonReaderOptions.AllowTrailingCommas, System.Text.Json.Utf8JsonReader.BytesConsumed, System.Text.Json.Utf8JsonReader.ConsumePropertyNameMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment(), System.Text.Json.BitStack.CurrentDepth, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.EndArray(), System.Text.Json.Utf8JsonReader.EndObject(), System.Text.Json.Utf8JsonReader.GetNextSpan(), System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment(), System.Text.Json.Utf8JsonReader.IsLastSpan, System.ReadOnlySpan< T >.Length, System.Text.Json.Utf8JsonReader.SkipAllCommentsMultiSegment(), System.Text.Json.Utf8JsonReader.SkipWhiteSpaceMultiSegment(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), and System.Text.Json.Utf8JsonReader.TokenStartIndex.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextTokenMultiSegment().