Terraria: System.Text.Json.Utf8JsonReader.ConsumeStringNextSegment
ConsumeStringNextSegment()
bool System.Text.Json.Utf8JsonReader.ConsumeStringNextSegment () inline private
Definition at line 2519 of file Utf8JsonReader.cs.
    {
        PartialStateForRollback state = CaptureState();
        HasValueSequence = true;
        int num = _buffer.Length - _consumed;
        ReadOnlySpan<byte> buffer;
        int num2;
        while (true)
        {
            if (!GetNextSpan())
            {
                if (IsLastSpan)
                {
                    _bytePositionInLine += num;
                    RollBackState(in state, isError: true);
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.EndOfStringNotFound, 0);
                }
                RollBackState(in state);
                return false;
            }
            buffer = _buffer;
            num2 = buffer.IndexOfQuoteOrAnyControlOrBackSlash();
            if (num2 >= 0)
            {
                break;
            }
            _totalConsumed += buffer.Length;
            _bytePositionInLine += buffer.Length;
        }
        byte b = buffer[num2];
        SequencePosition end;
        if (b == 34)
        {
            end = new SequencePosition(_currentPosition.GetObject(), _currentPosition.GetInteger() + num2);
            _bytePositionInLine += num + num2 + 1;
            _totalConsumed += num;
            _consumed = num2 + 1;
            _stringHasEscaping = false;
        }
        else
        {
            _bytePositionInLine += num + num2;
            _stringHasEscaping = true;
            bool flag = false;
            while (true)
            {
                if (num2 < buffer.Length)
                {
                    byte b2 = buffer[num2];
                    if (b2 == 34)
                    {
                        if (!flag)
{
                            break;
                        }
                        flag = false;
                    }
                    else if (b2 == 92)
                    {
                        flag = !flag;
                    }
                    else if (flag)
                    {
                        int num3 = JsonConstants.EscapableChars.IndexOf(b2);
                        if (num3 == -1)
{
                            RollBackState(in state, isError: true);
                            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.InvalidCharacterAfterEscapeWithinString, b2);
                        }
                        if (b2 == 117)
{
                            _bytePositionInLine++;
                            int num4 = 0;
                            int num5 = num2 + 1;
                            while (true)
{
                                if (num5 < buffer.Length)
{
                                    byte nextByte = buffer[num5];
                                    if (!JsonReaderHelper.IsHexDigit(nextByte))
{
                                        RollBackState(in state, isError: true);
                                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.InvalidHexCharacterWithinString, nextByte);
                                    }
                                    num4++;
                                    _bytePositionInLine++;
                                    if (num4 >= 4)
{
                                        break;
                                    }
                                    num5++;
                                    continue;
                                }
                                if (!GetNextSpan())
{
                                    if (IsLastSpan)
{
                                        RollBackState(in state, isError: true);
                                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.EndOfStringNotFound, 0);
                                    }
                                    RollBackState(in state);
                                    return false;
                                }
                                _totalConsumed += buffer.Length;
                                buffer = _buffer;
                                num5 = 0;
                            }
                            flag = false;
                            num2 = num5 + 1;
                            continue;
                        }
                        flag = false;
                    }
                    else if (b2 < 32)
                    {
                        RollBackState(in state, isError: true);
                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.InvalidCharacterWithinString, b2);
                    }
                    _bytePositionInLine++;
                    num2++;
                    continue;
                }
                if (!GetNextSpan())
                {
                    if (IsLastSpan)
                    {
                        RollBackState(in state, isError: true);
                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.EndOfStringNotFound, 0);
                    }
                    RollBackState(in state);
                    return false;
                }
                _totalConsumed += buffer.Length;
                buffer = _buffer;
                num2 = 0;
            }
            _bytePositionInLine++;
            _consumed = num2 + 1;
            _totalConsumed += num;
            end = new SequencePosition(_currentPosition.GetObject(), _currentPosition.GetInteger() + num2);
        }
        SequencePosition startPosition = state.GetStartPosition(1);
        ValueSequence = _sequence.Slice(startPosition, end);
        _tokenType = JsonTokenType.String;
        return true;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._currentPosition, System.Text.Json.Utf8JsonReader._sequence, System.Text.Json.Utf8JsonReader._stringHasEscaping, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._totalConsumed, System.buffer, System.Text.Json.Utf8JsonReader.CaptureState(), System.Text.Json.Dictionary, System.Text.Json.JsonConstants.EscapableChars, System.SequencePosition.GetInteger(), System.Text.Json.Utf8JsonReader.GetNextSpan(), System.SequencePosition.GetObject(), System.Text.Json.Utf8JsonReader.HasValueSequence, System.Text.Json.JsonReaderHelper.IsHexDigit(), System.Text.Json.Utf8JsonReader.IsLastSpan, System.Text.Json.Utf8JsonReader.RollBackState(), System.Buffers.ReadOnlySequence< T >.Slice(), System.state, System.Text.Json.ThrowHelper.ThrowJsonReaderException(), and System.Text.Json.Utf8JsonReader.ValueSequence.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeStringMultiSegment().