Terraria: System.Text.Json.Utf8JsonReader.SkipOrConsumeCommentMultiSegmentWithRollback
SkipOrConsumeCommentMultiSegmentWithRollback()
bool System.Text.Json.Utf8JsonReader.SkipOrConsumeCommentMultiSegmentWithRollback () inline private
Definition at line 3702 of file Utf8JsonReader.cs.
    {
        long bytesConsumed = BytesConsumed;
        SequencePosition start = new SequencePosition(_currentPosition.GetObject(), _currentPosition.GetInteger() + _consumed);
        int tailBytesToIgnore;
        bool flag = SkipCommentMultiSegment(out tailBytesToIgnore);
        if (flag)
        {
            if (_readerOptions.CommentHandling == JsonCommentHandling.Allow)
            {
                SequencePosition end = new SequencePosition(_currentPosition.GetObject(), _currentPosition.GetInteger() + _consumed);
                ReadOnlySequence<byte> readOnlySequence = _sequence.Slice(start, end);
                readOnlySequence = readOnlySequence.Slice(2L, readOnlySequence.Length - 2 - tailBytesToIgnore);
                HasValueSequence = !readOnlySequence.IsSingleSegment;
                if (HasValueSequence)
                {
                    ValueSequence = readOnlySequence;
                }
                else
                {
                    ValueSpan = readOnlySequence.First.Span;
                }
                if (_tokenType != JsonTokenType.Comment)
                {
                    _previousTokenType = _tokenType;
                }
                _tokenType = JsonTokenType.Comment;
            }
        }
        else
        {
            _totalConsumed = bytesConsumed;
            _consumed = 0;
        }
        return flag;
    }
References System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._currentPosition, System.Text.Json.Utf8JsonReader._previousTokenType, System.Text.Json.Utf8JsonReader._readerOptions, System.Text.Json.Utf8JsonReader._sequence, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._totalConsumed, System.Text.Json.Utf8JsonReader.BytesConsumed, System.Text.Json.JsonReaderOptions.CommentHandling, System.Text.Json.Dictionary, System.SequencePosition.GetInteger(), System.SequencePosition.GetObject(), System.Text.Json.Utf8JsonReader.HasValueSequence, System.L, System.Text.Json.Utf8JsonReader.SkipCommentMultiSegment(), System.Buffers.ReadOnlySequence< T >.Slice(), System.start, System.Text.Json.Utf8JsonReader.ValueSequence, and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment(), System.Text.Json.Utf8JsonReader.SkipAllCommentsMultiSegment(), and System.Text.Json.Utf8JsonReader.SkipAllCommentsMultiSegment().