Terraria: System.Text.Json.Utf8JsonReader.ConsumeIntegerDigits
ConsumeIntegerDigits()
ConsumeNumberResult System.Text.Json.Utf8JsonReader.ConsumeIntegerDigits (ref ReadOnlySpan< byte > data, ref int i) inline private
Definition at line 1159 of file Utf8JsonReader.cs.
    {
        byte value = 0;
        while (i < data.Length)
        {
            value = data[i];
            if (!JsonHelpers.IsDigit(value))
            {
                break;
            }
            i++;
        }
        if (i >= data.Length)
        {
            if (IsLastSpan)
            {
                return ConsumeNumberResult.Success;
            }
            return ConsumeNumberResult.NeedMoreData;
        }
        if (JsonConstants.Delimiters.IndexOf(value) >= 0)
        {
            return ConsumeNumberResult.Success;
        }
        return ConsumeNumberResult.OperationIncomplete;
    }
References System.Text.Json.JsonConstants.Delimiters, System.Text.Json.JsonHelpers.IsDigit(), System.Text.Json.Utf8JsonReader.IsLastSpan, and System.value.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeDecimalDigits(), and System.Text.Json.Utf8JsonReader.TryGetNumber().