Terraria: System.Text.Json.Utf8JsonReader.SkipWhiteSpace
SkipWhiteSpace()
void System.Text.Json.Utf8JsonReader.SkipWhiteSpace () inline private
Definition at line 706 of file Utf8JsonReader.cs.
    {
        ReadOnlySpan<byte> buffer = _buffer;
        while (_consumed < buffer.Length)
        {
            byte b = buffer[_consumed];
            if (b == 32 || b == 13 || b == 10 || b == 9)
            {
                if (b == 10)
                {
                    _lineNumber++;
                    _bytePositionInLine = 0L;
                }
                else
                {
                    _bytePositionInLine++;
                }
                _consumed++;
                continue;
            }
            break;
        }
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._lineNumber, System.buffer, System.Text.Json.Dictionary, and System.L.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextToken(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentToken(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(), System.Text.Json.Utf8JsonReader.ConsumePropertyName(), System.Text.Json.Utf8JsonReader.ConsumeValue(), System.Text.Json.Utf8JsonReader.ReadSingleSegment(), System.Text.Json.Utf8JsonReader.SkipAllComments(), System.Text.Json.Utf8JsonReader.SkipAllComments(), and System.Text.Json.Utf8JsonReader.SkipWhiteSpaceMultiSegment().