Terraria: System.Text.Json.Utf8JsonReader.GetNextSpan
GetNextSpan()
bool System.Text.Json.Utf8JsonReader.GetNextSpan () inline private
Definition at line 2149 of file Utf8JsonReader.cs.
    {
        ReadOnlyMemory<byte> memory = default(ReadOnlyMemory<byte>);
        while (true)
        {
            SequencePosition currentPosition = _currentPosition;
            _currentPosition = _nextPosition;
            if (!_sequence.TryGet(ref _nextPosition, out memory))
            {
                _currentPosition = currentPosition;
                _isLastSegment = true;
                return false;
            }
            if (memory.Length != 0)
            {
                break;
            }
            _currentPosition = currentPosition;
        }
        if (_isFinalBlock)
        {
            _isLastSegment = !_sequence.TryGet(ref _nextPosition, out var _, advance: false);
        }
        _buffer = memory.Span;
        _totalConsumed += _consumed;
        _consumed = 0;
        return true;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._currentPosition, System.Text.Json.Utf8JsonReader._isFinalBlock, System.Text.Json.Utf8JsonReader._isLastSegment, System.Text.Json.Utf8JsonReader._nextPosition, System.Text.Json.Utf8JsonReader._sequence, System.Text.Json.Utf8JsonReader._totalConsumed, System.Text.Json.Dictionary, and System.Buffers.ReadOnlySequence< T >.TryGet().
Referenced by System.Text.Json.Utf8JsonReader.CheckLiteralMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeDecimalDigitsMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeIntegerDigitsMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNegativeSignMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkippedMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeSignMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeStringAndValidateMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeStringNextSegment(), System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeZeroMultiSegment(), System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment(), System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment(), System.Text.Json.Utf8JsonReader.SkipCommentMultiSegment(), System.Text.Json.Utf8JsonReader.SkipMultiLineCommentMultiSegment(), System.Text.Json.Utf8JsonReader.SkipSingleLineCommentMultiSegment(), and System.Text.Json.Utf8JsonReader.SkipWhiteSpaceMultiSegment().