Terraria: System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentTokenMultiSegment
ConsumeNextTokenFromLastNonCommentTokenMultiSegment()
ConsumeTokenResult System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentTokenMultiSegment () inline private
Definition at line 3311 of file Utf8JsonReader.cs.
    {
        if (JsonReaderHelper.IsTokenTypePrimitive(_previousTokenType))
        {
            _tokenType = (_inObject ? JsonTokenType.StartObject : JsonTokenType.StartArray);
        }
        else
        {
            _tokenType = _previousTokenType;
        }
        if (HasMoreDataMultiSegment())
        {
            byte b = _buffer[_consumed];
            if (b <= 32)
            {
                SkipWhiteSpaceMultiSegment();
                if (!HasMoreDataMultiSegment())
                {
                    goto IL_0393;
                }
                b = _buffer[_consumed];
            }
            if (_bitStack.CurrentDepth == 0 && _tokenType != 0)
            {
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedEndAfterSingleJson, b);
            }
            TokenStartIndex = BytesConsumed;
            if (b != 44)
            {
                if (b == 125)
                {
                    EndObject();
                }
                else
                {
                    if (b != 93)
                    {
                        if (_tokenType == JsonTokenType.None)
{
                            if (ReadFirstTokenMultiSegment(b))
{
                                goto IL_0391;
                            }
                        }
                        else if (_tokenType == JsonTokenType.StartObject)
{
                            if (b != 34)
{
                                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyNotFound, b);
                            }
                            long totalConsumed = _totalConsumed;
                            int consumed = _consumed;
                            long bytePositionInLine = _bytePositionInLine;
                            long lineNumber = _lineNumber;
                            if (ConsumePropertyNameMultiSegment())
{
                                goto IL_0391;
                            }
                            _consumed = consumed;
                            _tokenType = JsonTokenType.StartObject;
                            _bytePositionInLine = bytePositionInLine;
                            _lineNumber = lineNumber;
                            _totalConsumed = totalConsumed;
                        }
                        else if (_tokenType == JsonTokenType.StartArray)
{
                            if (ConsumeValueMultiSegment(b))
{
                                goto IL_0391;
                            }
                        }
                        else if (_tokenType == JsonTokenType.PropertyName)
{
                            if (ConsumeValueMultiSegment(b))
{
                                goto IL_0391;
                            }
                        }
                        else if (_inObject)
{
                            if (b != 34)
{
                                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyNotFound, b);
                            }
                            if (ConsumePropertyNameMultiSegment())
{
                                goto IL_0391;
                            }
                        }
                        else if (ConsumeValueMultiSegment(b))
{
                            goto IL_0391;
                        }
                        goto IL_0393;
                    }
                    EndArray();
                }
                goto IL_0391;
            }
            if ((int)_previousTokenType <= 1 || _previousTokenType == JsonTokenType.StartArray || _trailingCommaBeforeComment)
            {
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyOrValueAfterComment, b);
            }
            _consumed++;
            _bytePositionInLine++;
            if (_consumed >= (uint)_buffer.Length)
            {
                if (IsLastSpan)
                {
                    _consumed--;
                    _bytePositionInLine--;
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyOrValueNotFound, 0);
                }
                if (!GetNextSpan())
                {
                    if (IsLastSpan)
                    {
                        _consumed--;
                        _bytePositionInLine--;
                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyOrValueNotFound, 0);
                    }
                    goto IL_0393;
                }
            }
            b = _buffer[_consumed];
            if (b <= 32)
            {
                SkipWhiteSpaceMultiSegment();
                if (!HasMoreDataMultiSegment(ExceptionResource.ExpectedStartOfPropertyOrValueNotFound))
                {
                    goto IL_0393;
                }
                b = _buffer[_consumed];
            }
            TokenStartIndex = BytesConsumed;
            if (b == 47)
            {
                _trailingCommaBeforeComment = true;
                if (SkipOrConsumeCommentMultiSegmentWithRollback())
                {
                    goto IL_0391;
                }
            }
            else if (_inObject)
            {
                if (b != 34)
                {
                    if (b == 125)
                    {
                        if (_readerOptions.AllowTrailingCommas)
{
                            EndObject();
                            goto IL_0391;
                        }
                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.TrailingCommaNotAllowedBeforeObjectEnd, 0);
                    }
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyNotFound, b);
                }
                if (ConsumePropertyNameMultiSegment())
                {
                    goto IL_0391;
                }
            }
            else
            {
                if (b == 93)
                {
                    if (_readerOptions.AllowTrailingCommas)
                    {
                        EndArray();
                        goto IL_0391;
                    }
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.TrailingCommaNotAllowedBeforeArrayEnd, 0);
                }
                if (ConsumeValueMultiSegment(b))
                {
                    goto IL_0391;
                }
            }
        }
        goto IL_0393;
        IL_0393:
        return ConsumeTokenResult.NotEnoughDataRollBackState;
        IL_0391:
        return ConsumeTokenResult.Success;
    }
References System.Text.Json.Utf8JsonReader._bitStack, System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._inObject, System.Text.Json.Utf8JsonReader._lineNumber, System.Text.Json.Utf8JsonReader._previousTokenType, System.Text.Json.Utf8JsonReader._readerOptions, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._totalConsumed, System.Text.Json.Utf8JsonReader._trailingCommaBeforeComment, System.Text.Json.JsonReaderOptions.AllowTrailingCommas, System.Text.Json.Utf8JsonReader.BytesConsumed, System.Text.Json.Utf8JsonReader.ConsumePropertyNameMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment(), System.Text.Json.BitStack.CurrentDepth, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.EndArray(), System.Text.Json.Utf8JsonReader.EndObject(), System.Text.Json.Utf8JsonReader.GetNextSpan(), System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment(), System.Text.Json.Utf8JsonReader.IsLastSpan, System.Text.Json.JsonReaderHelper.IsTokenTypePrimitive(), System.ReadOnlySpan< T >.Length, System.Text.Json.Utf8JsonReader.ReadFirstTokenMultiSegment(), System.Text.Json.Utf8JsonReader.SkipOrConsumeCommentMultiSegmentWithRollback(), System.Text.Json.Utf8JsonReader.SkipWhiteSpaceMultiSegment(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), and System.Text.Json.Utf8JsonReader.TokenStartIndex.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextTokenMultiSegment().