Terraria: System.Text.Json.Utf8JsonReader.TryGetUInt16
TryGetUInt16()
bool System.Text.Json.Utf8JsonReader.TryGetUInt16 (out ushort value) inline
Definition at line 4586 of file Utf8JsonReader.cs.
    {
        if (TokenType != JsonTokenType.Number)
        {
            throw ThrowHelper.GetInvalidOperationException_ExpectedNumber(TokenType);
        }
        ReadOnlySpan<byte> readOnlySpan;
        if (!HasValueSequence)
        {
            readOnlySpan = ValueSpan;
        }
        else
        {
            ReadOnlySequence<byte> sequence = ValueSequence;
            readOnlySpan = BuffersExtensions.ToArray(in sequence);
        }
        ReadOnlySpan<byte> span = readOnlySpan;
        return TryGetUInt16Core(out value, span);
    }
References System.Text.Json.Dictionary, System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedNumber(), System.Text.Json.Utf8JsonReader.HasValueSequence, System.Text.Json.Utf8JsonReader.TryGetUInt16Core(), System.value, System.Text.Json.Utf8JsonReader.ValueSequence, and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.GetUInt16().