Terraria: System.Text.Json.Utf8JsonReader.ConsumePropertyNameMultiSegment
ConsumePropertyNameMultiSegment()
bool System.Text.Json.Utf8JsonReader.ConsumePropertyNameMultiSegment () inline private
Definition at line 2461 of file Utf8JsonReader.cs.
    {
        _trailingCommaBeforeComment = false;
        if (!ConsumeStringMultiSegment())
        {
            return false;
        }
        if (!HasMoreDataMultiSegment(ExceptionResource.ExpectedValueAfterPropertyNameNotFound))
        {
            return false;
        }
        byte b = _buffer[_consumed];
        if (b <= 32)
        {
            SkipWhiteSpaceMultiSegment();
            if (!HasMoreDataMultiSegment(ExceptionResource.ExpectedValueAfterPropertyNameNotFound))
            {
                return false;
            }
            b = _buffer[_consumed];
        }
        if (b != 58)
        {
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedSeparatorAfterPropertyNameNotFound, b);
        }
        _consumed++;
        _bytePositionInLine++;
        _tokenType = JsonTokenType.PropertyName;
        return true;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._trailingCommaBeforeComment, System.Text.Json.Utf8JsonReader.ConsumeStringMultiSegment(), System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment(), System.Text.Json.Utf8JsonReader.SkipWhiteSpaceMultiSegment(), and System.Text.Json.ThrowHelper.ThrowJsonReaderException().
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkippedMultiSegment(), and System.Text.Json.Utf8JsonReader.ReadMultiSegment().