Terraria: System.Text.Json.Utf8JsonReader.ConsumeNegativeSign
ConsumeNegativeSign()
ConsumeNumberResult System.Text.Json.Utf8JsonReader.ConsumeNegativeSign (ref ReadOnlySpan< byte > data, ref int i) inline private
Definition at line 1108 of file Utf8JsonReader.cs.
    {
        byte b = data[i];
        if (b == 45)
        {
            i++;
            if (i >= data.Length)
            {
                if (IsLastSpan)
                {
                    _bytePositionInLine += i;
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.RequiredDigitNotFoundEndOfData, 0);
                }
                return ConsumeNumberResult.NeedMoreData;
            }
            b = data[i];
            if (!JsonHelpers.IsDigit(b))
            {
                _bytePositionInLine += i;
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.RequiredDigitNotFoundAfterSign, b);
            }
        }
        return ConsumeNumberResult.OperationIncomplete;
    }
References System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Dictionary, System.Text.Json.JsonHelpers.IsDigit(), System.Text.Json.Utf8JsonReader.IsLastSpan, and System.Text.Json.ThrowHelper.ThrowJsonReaderException().
Referenced by System.Text.Json.Utf8JsonReader.TryGetNumber().