Terraria: System.Text.Json.Utf8JsonReader.ReadMultiSegment
ReadMultiSegment()
bool System.Text.Json.Utf8JsonReader.ReadMultiSegment () inline private
Definition at line 2011 of file Utf8JsonReader.cs.
    {
        bool flag = false;
        HasValueSequence = false;
        ValueSpan = default(ReadOnlySpan<byte>);
        ValueSequence = default(ReadOnlySequence<byte>);
        if (HasMoreDataMultiSegment())
        {
            byte b = _buffer[_consumed];
            if (b <= 32)
            {
                SkipWhiteSpaceMultiSegment();
                if (!HasMoreDataMultiSegment())
                {
                    goto IL_016c;
                }
                b = _buffer[_consumed];
            }
            TokenStartIndex = BytesConsumed;
            if (_tokenType != 0)
            {
                if (b == 47)
                {
                    flag = ConsumeNextTokenOrRollbackMultiSegment(b);
                }
                else if (_tokenType == JsonTokenType.StartObject)
                {
                    if (b == 125)
                    {
                        EndObject();
                        goto IL_016a;
                    }
                    if (b != 34)
                    {
                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyNotFound, b);
                    }
                    long totalConsumed = _totalConsumed;
                    int consumed = _consumed;
                    long bytePositionInLine = _bytePositionInLine;
                    long lineNumber = _lineNumber;
                    SequencePosition currentPosition = _currentPosition;
                    flag = ConsumePropertyNameMultiSegment();
                    if (!flag)
                    {
                        _consumed = consumed;
                        _tokenType = JsonTokenType.StartObject;
                        _bytePositionInLine = bytePositionInLine;
                        _lineNumber = lineNumber;
                        _totalConsumed = totalConsumed;
                        _currentPosition = currentPosition;
                    }
                }
                else if (_tokenType != JsonTokenType.StartArray)
                {
                    flag = ((_tokenType != JsonTokenType.PropertyName) ? ConsumeNextTokenOrRollbackMultiSegment(b) : ConsumeValueMultiSegment(b));
                }
                else
                {
                    if (b == 93)
                    {
                        EndArray();
                        goto IL_016a;
                    }
                    flag = ConsumeValueMultiSegment(b);
                }
            }
            else
            {
                flag = ReadFirstTokenMultiSegment(b);
            }
        }
        goto IL_016c;
        IL_016c:
        return flag;
        IL_016a:
        flag = true;
        goto IL_016c;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._currentPosition, System.Text.Json.Utf8JsonReader._lineNumber, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._totalConsumed, System.Text.Json.Utf8JsonReader.BytesConsumed, System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollbackMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumePropertyNameMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment(), System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.EndArray(), System.Text.Json.Utf8JsonReader.EndObject(), System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment(), System.Text.Json.Utf8JsonReader.HasValueSequence, System.Text.Json.Utf8JsonReader.ReadFirstTokenMultiSegment(), System.Text.Json.Utf8JsonReader.SkipWhiteSpaceMultiSegment(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), System.Text.Json.Utf8JsonReader.TokenStartIndex, System.Text.Json.Utf8JsonReader.ValueSequence, and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.Read().