Terraria: System.Text.Json.Utf8JsonReader.ConsumeValue
ConsumeValue()
bool System.Text.Json.Utf8JsonReader.ConsumeValue (byte marker) inline private
Definition at line 730 of file Utf8JsonReader.cs.
    {
        while (true)
        {
            _trailingCommaBeforeComment = false;
            switch (marker)
            {
            case 34:
                return ConsumeString();
            case 123:
                StartObject();
                break;
            case 91:
                StartArray();
                break;
            default:
                if (JsonHelpers.IsDigit(marker) || marker == 45)
                {
                    return ConsumeNumber();
                }
                switch (marker)
                {
                case 102:
                    return ConsumeLiteral(JsonConstants.FalseValue, JsonTokenType.False);
                case 116:
                    return ConsumeLiteral(JsonConstants.TrueValue, JsonTokenType.True);
                case 110:
                    return ConsumeLiteral(JsonConstants.NullValue, JsonTokenType.Null);
                }
                switch (_readerOptions.CommentHandling)
                {
                case JsonCommentHandling.Allow:
                    if (marker == 47)
                    {
                        return ConsumeComment();
                    }
                    break;
                default:
                    if (marker != 47)
                    {
                        break;
                    }
                    if (SkipComment())
                    {
                        if (_consumed >= (uint)_buffer.Length)
{
                            if (_isNotPrimitive && IsLastSpan && _tokenType != JsonTokenType.EndArray && _tokenType != JsonTokenType.EndObject)
{
                                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.InvalidEndOfJsonNonPrimitive, 0);
                            }
                            return false;
                        }
                        marker = _buffer[_consumed];
                        if (marker <= 32)
{
                            SkipWhiteSpace();
                            if (!HasMoreData())
{
                                return false;
                            }
                            marker = _buffer[_consumed];
                        }
                        goto IL_0140;
                    }
                    return false;
                case JsonCommentHandling.Disallow:
                    break;
                }
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfValueNotFound, marker);
                break;
            }
            break;
            IL_0140:
            TokenStartIndex = _consumed;
        }
        return true;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._isNotPrimitive, System.Text.Json.Utf8JsonReader._readerOptions, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._trailingCommaBeforeComment, System.Text.Json.JsonReaderOptions.CommentHandling, System.Text.Json.Utf8JsonReader.ConsumeComment(), System.Text.Json.Utf8JsonReader.ConsumeLiteral(), System.Text.Json.Utf8JsonReader.ConsumeNumber(), System.Text.Json.Utf8JsonReader.ConsumeString(), System.Text.Json.Dictionary, System.Text.Json.JsonConstants.FalseValue, System.Text.Json.Utf8JsonReader.HasMoreData(), System.Text.Json.JsonHelpers.IsDigit(), System.Text.Json.Utf8JsonReader.IsLastSpan, System.ReadOnlySpan< T >.Length, System.Text.Json.JsonConstants.NullValue, System.Text.Json.Utf8JsonReader.SkipComment(), System.Text.Json.Utf8JsonReader.SkipWhiteSpace(), System.Text.Json.Utf8JsonReader.StartArray(), System.Text.Json.Utf8JsonReader.StartObject(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), System.Text.Json.Utf8JsonReader.TokenStartIndex, and System.Text.Json.JsonConstants.TrueValue.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextToken(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentToken(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(), System.Text.Json.Utf8JsonReader.ReadFirstToken(), and System.Text.Json.Utf8JsonReader.ReadSingleSegment().