Terraria: System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment
HasMoreDataMultiSegment() [1/2]
bool System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment () inline private
Definition at line 2108 of file Utf8JsonReader.cs.
    {
        if (_consumed >= (uint)_buffer.Length)
        {
            if (_isNotPrimitive && IsLastSpan && !ValidateStateAtEndOfData())
            {
                return false;
            }
            if (!GetNextSpan())
            {
                if (_isNotPrimitive && IsLastSpan)
                {
                    ValidateStateAtEndOfData();
                }
                return false;
            }
        }
        return true;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._isNotPrimitive, System.Text.Json.Utf8JsonReader.GetNextSpan(), System.Text.Json.Utf8JsonReader.IsLastSpan, System.ReadOnlySpan< T >.Length, and System.Text.Json.Utf8JsonReader.ValidateStateAtEndOfData().
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkippedMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumePropertyNameMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment(), System.Text.Json.Utf8JsonReader.ReadMultiSegment(), System.Text.Json.Utf8JsonReader.SkipAllCommentsMultiSegment(), and System.Text.Json.Utf8JsonReader.SkipAllCommentsMultiSegment().