Terraria: System.Text.Json.Utf8JsonReader.SkipSingleLineCommentMultiSegment
SkipSingleLineCommentMultiSegment()
bool System.Text.Json.Utf8JsonReader.SkipSingleLineCommentMultiSegment (ReadOnlySpan< byte > localBuffer, out int tailBytesToSkip) inline private
Definition at line 3804 of file Utf8JsonReader.cs.
    {
        bool flag = false;
        int dangerousLineSeparatorBytesConsumed = 0;
        tailBytesToSkip = 0;
        while (true)
        {
            if (flag)
            {
                if (localBuffer[0] == 10)
                {
                    tailBytesToSkip++;
                    _consumed++;
                }
                break;
            }
            int num = FindLineSeparatorMultiSegment(localBuffer, ref dangerousLineSeparatorBytesConsumed);
            if (num != -1)
            {
                tailBytesToSkip++;
                _consumed += num + 1;
                _bytePositionInLine += num + 1;
                if (localBuffer[num] == 10)
                {
                    break;
                }
                if (num < localBuffer.Length - 1)
                {
                    if (localBuffer[num + 1] == 10)
                    {
                        tailBytesToSkip++;
                        _consumed++;
                        _bytePositionInLine++;
                    }
                    break;
                }
                flag = true;
            }
            else
            {
                _consumed += localBuffer.Length;
                _bytePositionInLine += localBuffer.Length;
            }
            if (IsLastSpan)
            {
                if (flag)
                {
                    break;
                }
                return true;
            }
            if (!GetNextSpan())
            {
                if (IsLastSpan)
                {
                    if (flag)
                    {
                        break;
                    }
                    return true;
                }
                return false;
            }
            localBuffer = _buffer;
        }
        _bytePositionInLine = 0L;
        _lineNumber++;
        return true;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._lineNumber, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.FindLineSeparatorMultiSegment(), System.Text.Json.Utf8JsonReader.GetNextSpan(), System.Text.Json.Utf8JsonReader.IsLastSpan, and System.L.
Referenced by System.Text.Json.Utf8JsonReader.SkipCommentMultiSegment().