Terraria: System.Text.Json.Utf8JsonReader.ReadFirstToken
ReadFirstToken()
bool System.Text.Json.Utf8JsonReader.ReadFirstToken (byte first) inline private
Definition at line 657 of file Utf8JsonReader.cs.
    {
        switch (first)
        {
        case 123:
            _bitStack.SetFirstBit();
            _tokenType = JsonTokenType.StartObject;
            ValueSpan = _buffer.Slice(_consumed, 1);
            _consumed++;
            _bytePositionInLine++;
            _inObject = true;
            _isNotPrimitive = true;
            break;
        case 91:
            _bitStack.ResetFirstBit();
            _tokenType = JsonTokenType.StartArray;
            ValueSpan = _buffer.Slice(_consumed, 1);
            _consumed++;
            _bytePositionInLine++;
            _isNotPrimitive = true;
            break;
        default:
        {
            ReadOnlySpan<byte> buffer = _buffer;
            if (JsonHelpers.IsDigit(first) || first == 45)
            {
                if (!TryGetNumber(buffer.Slice(_consumed), out var consumed))
                {
                    return false;
                }
                _tokenType = JsonTokenType.Number;
                _consumed += consumed;
                _bytePositionInLine += consumed;
                return true;
            }
            if (!ConsumeValue(first))
            {
                return false;
            }
            if (_tokenType == JsonTokenType.StartObject || _tokenType == JsonTokenType.StartArray)
            {
                _isNotPrimitive = true;
            }
            break;
        }
        }
        return true;
    }
References System.Text.Json.Utf8JsonReader._bitStack, System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._inObject, System.Text.Json.Utf8JsonReader._isNotPrimitive, System.Text.Json.Utf8JsonReader._tokenType, System.buffer, System.Text.Json.Utf8JsonReader.ConsumeValue(), System.Text.Json.Dictionary, System.Text.Json.JsonHelpers.IsDigit(), System.Text.Json.BitStack.ResetFirstBit(), System.Text.Json.BitStack.SetFirstBit(), System.ReadOnlySpan< T >.Slice(), System.Text.Json.Utf8JsonReader.TryGetNumber(), and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentToken(), and System.Text.Json.Utf8JsonReader.ReadSingleSegment().