Terraria: System.Text.Json.Utf8JsonReader.ConsumeNextTokenMultiSegment
ConsumeNextTokenMultiSegment()
ConsumeTokenResult System.Text.Json.Utf8JsonReader.ConsumeNextTokenMultiSegment (byte marker) inline private
Definition at line 3192 of file Utf8JsonReader.cs.
    {
        if (_readerOptions.CommentHandling != 0)
        {
            if (_readerOptions.CommentHandling != JsonCommentHandling.Allow)
            {
                return ConsumeNextTokenUntilAfterAllCommentsAreSkippedMultiSegment(marker);
            }
            if (marker == 47)
            {
                if (!SkipOrConsumeCommentMultiSegmentWithRollback())
                {
                    return ConsumeTokenResult.NotEnoughDataRollBackState;
                }
                return ConsumeTokenResult.Success;
            }
            if (_tokenType == JsonTokenType.Comment)
            {
                return ConsumeNextTokenFromLastNonCommentTokenMultiSegment();
            }
        }
        if (_bitStack.CurrentDepth == 0)
        {
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedEndAfterSingleJson, marker);
        }
        switch (marker)
        {
        case 44:
        {
            _consumed++;
            _bytePositionInLine++;
            if (_consumed >= (uint)_buffer.Length)
            {
                if (IsLastSpan)
                {
                    _consumed--;
                    _bytePositionInLine--;
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyOrValueNotFound, 0);
                }
                if (!GetNextSpan())
                {
                    if (IsLastSpan)
                    {
                        _consumed--;
                        _bytePositionInLine--;
                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyOrValueNotFound, 0);
                    }
                    return ConsumeTokenResult.NotEnoughDataRollBackState;
                }
            }
            byte b = _buffer[_consumed];
            if (b <= 32)
            {
                SkipWhiteSpaceMultiSegment();
                if (!HasMoreDataMultiSegment(ExceptionResource.ExpectedStartOfPropertyOrValueNotFound))
                {
                    return ConsumeTokenResult.NotEnoughDataRollBackState;
                }
                b = _buffer[_consumed];
            }
            TokenStartIndex = BytesConsumed;
            if (_readerOptions.CommentHandling == JsonCommentHandling.Allow && b == 47)
            {
                _trailingCommaBeforeComment = true;
                if (!SkipOrConsumeCommentMultiSegmentWithRollback())
                {
                    return ConsumeTokenResult.NotEnoughDataRollBackState;
                }
                return ConsumeTokenResult.Success;
            }
            if (_inObject)
            {
                if (b != 34)
                {
                    if (b == 125)
                    {
                        if (_readerOptions.AllowTrailingCommas)
{
                            EndObject();
                            return ConsumeTokenResult.Success;
                        }
                        ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.TrailingCommaNotAllowedBeforeObjectEnd, 0);
                    }
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedStartOfPropertyNotFound, b);
                }
                if (!ConsumePropertyNameMultiSegment())
                {
                    return ConsumeTokenResult.NotEnoughDataRollBackState;
                }
                return ConsumeTokenResult.Success;
            }
            if (b == 93)
            {
                if (_readerOptions.AllowTrailingCommas)
                {
                    EndArray();
                    return ConsumeTokenResult.Success;
                }
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.TrailingCommaNotAllowedBeforeArrayEnd, 0);
            }
            if (!ConsumeValueMultiSegment(b))
            {
                return ConsumeTokenResult.NotEnoughDataRollBackState;
            }
            return ConsumeTokenResult.Success;
        }
        case 125:
            EndObject();
            break;
        case 93:
            EndArray();
            break;
        default:
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.FoundInvalidCharacter, marker);
            break;
        }
        return ConsumeTokenResult.Success;
    }
References System.Text.Json.Utf8JsonReader._bitStack, System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._inObject, System.Text.Json.Utf8JsonReader._readerOptions, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._trailingCommaBeforeComment, System.Text.Json.JsonReaderOptions.AllowTrailingCommas, System.Text.Json.Utf8JsonReader.BytesConsumed, System.Text.Json.JsonReaderOptions.CommentHandling, System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkippedMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumePropertyNameMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment(), System.Text.Json.BitStack.CurrentDepth, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.EndArray(), System.Text.Json.Utf8JsonReader.EndObject(), System.Text.Json.Utf8JsonReader.GetNextSpan(), System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment(), System.Text.Json.Utf8JsonReader.IsLastSpan, System.ReadOnlySpan< T >.Length, System.Text.Json.Utf8JsonReader.SkipOrConsumeCommentMultiSegmentWithRollback(), System.Text.Json.Utf8JsonReader.SkipWhiteSpaceMultiSegment(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), and System.Text.Json.Utf8JsonReader.TokenStartIndex.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollbackMultiSegment().