Terraria: System.Text.Json.Utf8JsonReader.ConsumeStringAndValidateMultiSegment
ConsumeStringAndValidateMultiSegment()
bool System.Text.Json.Utf8JsonReader.ConsumeStringAndValidateMultiSegment (ReadOnlySpan< byte > data, int idx) inline private
Definition at line 2666 of file Utf8JsonReader.cs.
    {
        PartialStateForRollback state = CaptureState();
        HasValueSequence = false;
        int num = _buffer.Length - _consumed;
        _bytePositionInLine += idx + 1;
        bool flag = false;
        while (true)
        {
            if (idx < data.Length)
            {
                byte b = data[idx];
                switch (b)
                {
                case 34:
                    if (flag)
                    {
                        flag = false;
                        goto IL_01b7;
                    }
                    if (HasValueSequence)
                    {
                        _bytePositionInLine++;
                        _consumed = idx + 1;
                        _totalConsumed += num;
                        SequencePosition end = new SequencePosition(_currentPosition.GetObject(), _currentPosition.GetInteger() + idx);
                        SequencePosition startPosition = state.GetStartPosition(1);
                        ValueSequence = _sequence.Slice(startPosition, end);
                    }
                    else
                    {
                        _bytePositionInLine++;
                        _consumed += idx + 2;
                        ValueSpan = data.Slice(0, idx);
                    }
                    _stringHasEscaping = true;
                    _tokenType = JsonTokenType.String;
                    return true;
                case 92:
                    flag = !flag;
                    goto IL_01b7;
                default:
                    {
                        if (flag)
{
                            int num2 = JsonConstants.EscapableChars.IndexOf(b);
                            if (num2 == -1)
{
                                RollBackState(in state, isError: true);
                                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.InvalidCharacterAfterEscapeWithinString, b);
                            }
                            if (b == 117)
{
                                _bytePositionInLine++;
                                int num3 = 0;
                                int num4 = idx + 1;
                                while (true)
{
                                    if (num4 < data.Length)
{
                                        byte nextByte = data[num4];
                                        if (!JsonReaderHelper.IsHexDigit(nextByte))
{
                                            RollBackState(in state, isError: true);
                                            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.InvalidHexCharacterWithinString, nextByte);
                                        }
                                        num3++;
                                        _bytePositionInLine++;
                                        if (num3 >= 4)
{
                                            break;
                                        }
                                        num4++;
                                        continue;
                                    }
                                    if (!GetNextSpan())
{
                                        if (IsLastSpan)
{
                                            RollBackState(in state, isError: true);
                                            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.EndOfStringNotFound, 0);
                                        }
                                        RollBackState(in state);
                                        return false;
                                    }
                                    if (HasValueSequence)
{
                                        _totalConsumed += data.Length;
                                    }
                                    data = _buffer;
                                    num4 = 0;
                                    HasValueSequence = true;
                                }
                                flag = false;
                                idx = num4 + 1;
                                break;
                            }
                            flag = false;
                        }
                        else if (b < 32)
{
                            RollBackState(in state, isError: true);
                            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.InvalidCharacterWithinString, b);
                        }
                        goto IL_01b7;
                    }
                    IL_01b7:
                    _bytePositionInLine++;
                    idx++;
                    break;
                }
            }
            else
            {
                if (!GetNextSpan())
                {
                    break;
                }
                if (HasValueSequence)
                {
                    _totalConsumed += data.Length;
                }
                data = _buffer;
                idx = 0;
                HasValueSequence = true;
            }
        }
        if (IsLastSpan)
        {
            RollBackState(in state, isError: true);
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.EndOfStringNotFound, 0);
        }
        RollBackState(in state);
        return false;
    }
References System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._currentPosition, System.Text.Json.Utf8JsonReader._sequence, System.Text.Json.Utf8JsonReader._stringHasEscaping, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.Utf8JsonReader._totalConsumed, System.Text.Json.Utf8JsonReader.CaptureState(), System.Text.Json.Dictionary, System.Text.Json.JsonConstants.EscapableChars, System.SequencePosition.GetInteger(), System.Text.Json.Utf8JsonReader.GetNextSpan(), System.SequencePosition.GetObject(), System.Text.Json.Utf8JsonReader.HasValueSequence, System.Text.Json.JsonReaderHelper.IsHexDigit(), System.Text.Json.Utf8JsonReader.IsLastSpan, System.ReadOnlySpan< T >.Length, System.Text.Json.Utf8JsonReader.RollBackState(), System.ReadOnlySpan< T >.Slice(), System.Buffers.ReadOnlySequence< T >.Slice(), System.state, System.Text.Json.ThrowHelper.ThrowJsonReaderException(), System.Text.Json.Utf8JsonReader.ValueSequence, and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeStringMultiSegment().