Terraria: System.Text.Json.Utf8JsonReader.TryGetNumber
TryGetNumber()
bool System.Text.Json.Utf8JsonReader.TryGetNumber (ReadOnlySpan< byte > data, out int consumed) inline private
Definition at line 1020 of file Utf8JsonReader.cs.
    {
        consumed = 0;
        int i = 0;
        ConsumeNumberResult consumeNumberResult = ConsumeNegativeSign(ref data, ref i);
        if (consumeNumberResult == ConsumeNumberResult.NeedMoreData)
        {
            return false;
        }
        byte b = data[i];
        if (b == 48)
        {
            ConsumeNumberResult consumeNumberResult2 = ConsumeZero(ref data, ref i);
            if (consumeNumberResult2 == ConsumeNumberResult.NeedMoreData)
            {
                return false;
            }
            if (consumeNumberResult2 != 0)
            {
                b = data[i];
                goto IL_00a3;
            }
        }
        else
        {
            i++;
            ConsumeNumberResult consumeNumberResult3 = ConsumeIntegerDigits(ref data, ref i);
            if (consumeNumberResult3 == ConsumeNumberResult.NeedMoreData)
            {
                return false;
            }
            if (consumeNumberResult3 != 0)
            {
                b = data[i];
                if (b != 46 && b != 69 && b != 101)
                {
                    _bytePositionInLine += i;
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedEndOfDigitNotFound, b);
                }
                goto IL_00a3;
            }
        }
        goto IL_0152;
        IL_00a3:
        if (b == 46)
        {
            i++;
            ConsumeNumberResult consumeNumberResult4 = ConsumeDecimalDigits(ref data, ref i);
            if (consumeNumberResult4 == ConsumeNumberResult.NeedMoreData)
            {
                return false;
            }
            if (consumeNumberResult4 == ConsumeNumberResult.Success)
            {
                goto IL_0152;
            }
            b = data[i];
            if (b != 69 && b != 101)
            {
                _bytePositionInLine += i;
                ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedNextDigitEValueNotFound, b);
            }
        }
        i++;
        consumeNumberResult = ConsumeSign(ref data, ref i);
        if (consumeNumberResult == ConsumeNumberResult.NeedMoreData)
        {
            return false;
        }
        i++;
        switch (ConsumeIntegerDigits(ref data, ref i))
        {
        case ConsumeNumberResult.NeedMoreData:
            return false;
        default:
            _bytePositionInLine += i;
            ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ExpectedEndOfDigitNotFound, data[i]);
            break;
        case ConsumeNumberResult.Success:
            break;
        }
        goto IL_0152;
        IL_0152:
        ValueSpan = data.Slice(0, i);
        consumed = i;
        return true;
    }
References System.Text.Json.Utf8JsonReader._bytePositionInLine, System.Text.Json.Utf8JsonReader.ConsumeDecimalDigits(), System.Text.Json.Utf8JsonReader.ConsumeIntegerDigits(), System.Text.Json.Utf8JsonReader.ConsumeNegativeSign(), System.Text.Json.Utf8JsonReader.ConsumeSign(), System.Text.Json.Utf8JsonReader.ConsumeZero(), System.Text.Json.Dictionary, System.ReadOnlySpan< T >.Slice(), System.Text.Json.ThrowHelper.ThrowJsonReaderException(), and System.Text.Json.Utf8JsonReader.ValueSpan.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNumber(), and System.Text.Json.Utf8JsonReader.ReadFirstToken().