Terraria: System.Text.Json.Utf8JsonReader.HasMoreData
HasMoreData() [1/2]
bool System.Text.Json.Utf8JsonReader.HasMoreData () inline private
Definition at line 619 of file Utf8JsonReader.cs.
    {
        if (_consumed >= (uint)_buffer.Length)
        {
            if (_isNotPrimitive && IsLastSpan)
            {
                if (_bitStack.CurrentDepth != 0)
                {
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.ZeroDepthAtEnd, 0);
                }
                if (_readerOptions.CommentHandling == JsonCommentHandling.Allow && _tokenType == JsonTokenType.Comment)
                {
                    return false;
                }
                if (_tokenType != JsonTokenType.EndArray && _tokenType != JsonTokenType.EndObject)
                {
                    ThrowHelper.ThrowJsonReaderException(ref this, ExceptionResource.InvalidEndOfJsonNonPrimitive, 0);
                }
            }
            return false;
        }
        return true;
    }
References System.Text.Json.Utf8JsonReader._bitStack, System.Text.Json.Utf8JsonReader._buffer, System.Text.Json.Utf8JsonReader._consumed, System.Text.Json.Utf8JsonReader._isNotPrimitive, System.Text.Json.Utf8JsonReader._readerOptions, System.Text.Json.Utf8JsonReader._tokenType, System.Text.Json.JsonReaderOptions.CommentHandling, System.Text.Json.BitStack.CurrentDepth, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonReader.IsLastSpan, System.ReadOnlySpan< T >.Length, and System.Text.Json.ThrowHelper.ThrowJsonReaderException().
Referenced by System.Text.Json.Utf8JsonReader.ConsumeNextToken(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentToken(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(), System.Text.Json.Utf8JsonReader.ConsumePropertyName(), System.Text.Json.Utf8JsonReader.ConsumeValue(), System.Text.Json.Utf8JsonReader.ReadSingleSegment(), System.Text.Json.Utf8JsonReader.SkipAllComments(), and System.Text.Json.Utf8JsonReader.SkipAllComments().