Terraria: System.Net.Sockets.TcpListener.SetIPProtectionLevel
SetIPProtectionLevel()
void System.Net.Sockets.TcpListener.SetIPProtectionLevel (bool allowed) inline private
Definition at line 257 of file TcpListener.cs.
    {
        _serverSocket.SetIPProtectionLevel(allowed ? IPProtectionLevel.Unrestricted : IPProtectionLevel.EdgeRestricted);
    }
References System.Net.Sockets.TcpListener._serverSocket, and System.Net.Sockets.Socket.SetIPProtectionLevel().
Referenced by System.Net.Sockets.TcpListener.AllowNatTraversal(), and System.Net.Sockets.TcpListener.CreateNewSocketIfNeeded().