Terraria: System.Linq.Expressions.Compiler.LabelInfo.EnsureLabelAndValue
EnsureLabelAndValue()
void System.Linq.Expressions.Compiler.LabelInfo.EnsureLabelAndValue () inline private
Definition at line 196 of file LabelInfo.cs.
    {
        if (!_labelDefined)
        {
            _labelDefined = true;
            _label = _ilg.DefineLabel();
            if (_node != null && _node.Type != typeof(void))
            {
                _value = _ilg.DeclareLocal(_node.Type);
            }
        }
    }
References System.Linq.Expressions.Compiler.LabelInfo._ilg, System.Linq.Expressions.Compiler.LabelInfo._label, System.Linq.Expressions.Compiler.LabelInfo._labelDefined, System.Linq.Expressions.Compiler.LabelInfo._node, System.Linq.Expressions.Compiler.LabelInfo._value, System.Reflection.Emit.ILGenerator.DeclareLocal(), System.Reflection.Emit.ILGenerator.DefineLabel(), and System.Linq.Expressions.LabelTarget.Type.
Referenced by System.Linq.Expressions.Compiler.LabelInfo.StoreValue().