Terraria: System.Linq.Expressions.Compiler.LabelInfo.Define
Define()
void System.Linq.Expressions.Compiler.LabelInfo.Define (LabelScopeInfo block) inline package
Definition at line 58 of file LabelInfo.cs.
    {
        for (LabelScopeInfo labelScopeInfo = block; labelScopeInfo != null; labelScopeInfo = labelScopeInfo.Parent)
        {
            if (labelScopeInfo.ContainsTarget(_node))
            {
                throw Error.LabelTargetAlreadyDefined(_node.Name);
            }
        }
        _definitions.Add(block);
        block.AddLabelInfo(_node, this);
        if (_definitions.Count == 1)
        {
            foreach (LabelScopeInfo reference in _references)
            {
                ValidateJump(reference);
            }
            return;
        }
        if (_acrossBlockJump)
        {
            throw Error.AmbiguousJump(_node.Name);
        }
        _labelDefined = false;
    }
References System.Linq.Expressions.Compiler.LabelInfo._acrossBlockJump, System.Linq.Expressions.Compiler.LabelInfo._definitions, System.Linq.Expressions.Compiler.LabelInfo._labelDefined, System.Linq.Expressions.Compiler.LabelInfo._node, System.Linq.Expressions.Compiler.LabelInfo._references, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.Expressions.Error.AmbiguousJump(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Error.LabelTargetAlreadyDefined(), System.Linq.Expressions.LabelTarget.Name, and System.Linq.Expressions.Compiler.LabelInfo.ValidateJump().