Terraria: System.Linq.Expressions.Compiler.LabelInfo.ValidateJump
ValidateJump()
void System.Linq.Expressions.Compiler.LabelInfo.ValidateJump (LabelScopeInfo reference) inline private
Definition at line 84 of file LabelInfo.cs.
    {
        _opCode = (_canReturn ? OpCodes.Ret : OpCodes.Br);
        for (LabelScopeInfo labelScopeInfo = reference; labelScopeInfo != null; labelScopeInfo = labelScopeInfo.Parent)
        {
            if (_definitions.Contains(labelScopeInfo))
            {
                return;
            }
            if (labelScopeInfo.Kind == LabelScopeKind.Finally || labelScopeInfo.Kind == LabelScopeKind.Filter)
            {
                break;
            }
            if (labelScopeInfo.Kind == LabelScopeKind.Try || labelScopeInfo.Kind == LabelScopeKind.Catch)
            {
                _opCode = OpCodes.Leave;
            }
        }
        _acrossBlockJump = true;
        if (_node != null && _node.Type != typeof(void))
        {
            throw Error.NonLocalJumpWithValue(_node.Name);
        }
        if (_definitions.Count > 1)
        {
            throw Error.AmbiguousJump(_node.Name);
        }
        LabelScopeInfo labelScopeInfo2 = _definitions.First();
        LabelScopeInfo labelScopeInfo3 = Helpers.CommonNode(labelScopeInfo2, reference, (LabelScopeInfo b) => b.Parent);
        _opCode = (_canReturn ? OpCodes.Ret : OpCodes.Br);
        for (LabelScopeInfo labelScopeInfo4 = reference; labelScopeInfo4 != labelScopeInfo3; labelScopeInfo4 = labelScopeInfo4.Parent)
        {
            if (labelScopeInfo4.Kind == LabelScopeKind.Finally)
            {
                throw Error.ControlCannotLeaveFinally();
            }
            if (labelScopeInfo4.Kind == LabelScopeKind.Filter)
            {
                throw Error.ControlCannotLeaveFilterTest();
            }
            if (labelScopeInfo4.Kind == LabelScopeKind.Try || labelScopeInfo4.Kind == LabelScopeKind.Catch)
            {
                _opCode = OpCodes.Leave;
            }
        }
        for (LabelScopeInfo labelScopeInfo5 = labelScopeInfo2; labelScopeInfo5 != labelScopeInfo3; labelScopeInfo5 = labelScopeInfo5.Parent)
        {
            if (!labelScopeInfo5.CanJumpInto)
            {
                if (labelScopeInfo5.Kind == LabelScopeKind.Expression)
                {
                    throw Error.ControlCannotEnterExpression();
                }
                throw Error.ControlCannotEnterTry();
            }
        }
    }
References System.Linq.Expressions.Compiler.LabelInfo._acrossBlockJump, System.Linq.Expressions.Compiler.LabelInfo._canReturn, System.Linq.Expressions.Compiler.LabelInfo._definitions, System.Linq.Expressions.Compiler.LabelInfo._node, System.Linq.Expressions.Compiler.LabelInfo._opCode, System.Linq.Expressions.Error.AmbiguousJump(), System.Reflection.Emit.OpCodes.Br, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Linq.Expressions.Error.ControlCannotEnterExpression(), System.Linq.Expressions.Error.ControlCannotEnterTry(), System.Linq.Expressions.Error.ControlCannotLeaveFilterTest(), System.Linq.Expressions.Error.ControlCannotLeaveFinally(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Emit.OpCodes.Leave, System.Linq.Expressions.LabelTarget.Name, System.Linq.Expressions.Error.NonLocalJumpWithValue(), and System.Linq.Expressions.LabelTarget.Type.
Referenced by System.Linq.Expressions.Compiler.LabelInfo.Define(), and System.Linq.Expressions.Compiler.LabelInfo.Reference().