Terraria: System.Linq.Expressions.Compiler.LabelInfo.StoreValue
StoreValue()
void System.Linq.Expressions.Compiler.LabelInfo.StoreValue () inline private
Definition at line 161 of file LabelInfo.cs.
    {
        EnsureLabelAndValue();
        if (_value != null)
        {
            _ilg.Emit(OpCodes.Stloc, _value);
        }
    }
References System.Linq.Expressions.Compiler.LabelInfo._ilg, System.Linq.Expressions.Compiler.LabelInfo._value, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LabelInfo.EnsureLabelAndValue(), and System.Reflection.Emit.OpCodes.Stloc.
Referenced by System.Linq.Expressions.Compiler.LabelInfo.EmitJump(), and System.Linq.Expressions.Compiler.LabelInfo.Mark().