Terraria: GenShape.UnitApply
UnitApply()
bool GenShape.UnitApply (GenAction action, Point origin, int x, int y, params object[] args) inline protected inherited
     {
         if (_outputData != null)
         {
             _outputData.Add(x - origin.X, y - origin.Y);
         }
         return action.Apply(origin, x, y, args);
     }
References GenShape._outputData, ShapeData.Add(), and GenAction.Apply().
Referenced by ShapeRoot.DoRoot(), ShapeFloodFill.Perform(), ShapeRunner.Perform(), ModShapes.All.Perform(), ModShapes.OuterOutline.Perform(), ModShapes.InnerOutline.Perform(), Shapes.Circle.Perform(), Shapes.HalfCircle.Perform(), Shapes.Slime.Perform(), Shapes.Rectangle.Perform(), Shapes.Tail.Perform(), Shapes.Mound.Perform(), and ShapeBranch.PerformSegment().