Terraria: System.Xml.Xsl.XPath.XPathScanner.NextLex
NextLex()
void System.Xml.Xsl.XPath.XPathScanner.NextLex () inline
Definition at line 106 of file XPathScanner.cs.
    {
        _prevLexEnd = _curIndex;
        _prevKind = _kind;
        SkipSpace();
        _lexStart = _curIndex;
        switch (_curChar)
        {
        case '\0':
            _kind = LexKind.Eof;
            return;
        case '$':
        case '(':
        case ')':
        case ',':
        case '@':
        case '[':
        case ']':
        case '}':
            _kind = (LexKind)_curChar;
            NextChar();
            return;
        case '.':
            NextChar();
            if (_curChar == '.')
            {
                _kind = LexKind.DotDot;
                NextChar();
                return;
            }
            if (IsAsciiDigit(_curChar))
            {
                SetSourceIndex(_lexStart);
                goto case '0';
            }
            _kind = LexKind.Dot;
            return;
        case ':':
            NextChar();
            if (_curChar == ':')
            {
                _kind = LexKind.ColonColon;
                NextChar();
            }
            else
            {
                _kind = LexKind.Unknown;
            }
            return;
        case '*':
            _kind = LexKind.Star;
            NextChar();
            CheckOperator(star: true);
            return;
        case '/':
            NextChar();
            if (_curChar == '/')
            {
                _kind = LexKind.SlashSlash;
                NextChar();
            }
            else
            {
                _kind = LexKind.Slash;
            }
            return;
        case '|':
            _kind = LexKind.Union;
            NextChar();
            return;
        case '+':
            _kind = LexKind.Plus;
            NextChar();
            return;
        case '-':
            _kind = LexKind.Minus;
            NextChar();
            return;
        case '=':
            _kind = LexKind.Eq;
            NextChar();
            return;
        case '!':
            NextChar();
            if (_curChar == '=')
            {
                _kind = LexKind.Ne;
                NextChar();
            }
            else
            {
                _kind = LexKind.Unknown;
            }
            return;
        case '<':
            NextChar();
            if (_curChar == '=')
            {
                _kind = LexKind.Le;
                NextChar();
            }
            else
            {
                _kind = LexKind.Lt;
            }
            return;
        case '>':
            NextChar();
            if (_curChar == '=')
            {
                _kind = LexKind.Ge;
                NextChar();
            }
            else
            {
                _kind = LexKind.Gt;
            }
            return;
        case '"':
        case '\'':
            _kind = LexKind.String;
            ScanString();
            return;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
            _kind = LexKind.Number;
            ScanNumber();
            return;
        }
        if (XmlCharType.IsStartNCNameSingleChar(_curChar))
        {
            _kind = LexKind.Name;
            _name = ScanNCName();
            _prefix = string.Empty;
            _canBeFunction = false;
            _axis = XPathAxis.Unknown;
            bool flag = false;
            int curIndex = _curIndex;
            if (_curChar == ':')
            {
                NextChar();
                if (_curChar == ':')
                {
                    NextChar();
                    flag = true;
                    SetSourceIndex(curIndex);
                }
                else if (_curChar == '*')
                {
                    NextChar();
                    _prefix = _name;
                    _name = "*";
                }
                else if (XmlCharType.IsStartNCNameSingleChar(_curChar))
                {
                    _prefix = _name;
                    _name = ScanNCName();
                    curIndex = _curIndex;
                    SkipSpace();
                    _canBeFunction = _curChar == '(';
                    SetSourceIndex(curIndex);
                }
                else
                {
                    SetSourceIndex(curIndex);
                }
            }
            else
            {
                SkipSpace();
                if (_curChar == ':')
                {
                    NextChar();
                    if (_curChar == ':')
                    {
                        NextChar();
                        flag = true;
                    }
                    SetSourceIndex(curIndex);
                }
                else
                {
                    _canBeFunction = _curChar == '(';
                }
            }
            if (!CheckOperator(star: false) && flag)
            {
                _axis = CheckAxis();
            }
        }
        else
        {
            _kind = LexKind.Unknown;
            NextChar();
        }
    }
References System.Xml.Xsl.XPath.XPathScanner._axis, System.Xml.Xsl.XPath.XPathScanner._canBeFunction, System.Xml.Xsl.XPath.XPathScanner._curChar, System.Xml.Xsl.XPath.XPathScanner._curIndex, System.Xml.Xsl.XPath.XPathScanner._kind, System.Xml.Xsl.XPath.XPathScanner._lexStart, System.Xml.Xsl.XPath.XPathScanner._name, System.Xml.Xsl.XPath.XPathScanner._prefix, System.Xml.Xsl.XPath.XPathScanner._prevKind, System.Xml.Xsl.XPath.XPathScanner._prevLexEnd, System.Xml.Xsl.XPath.XPathScanner.CheckAxis(), System.Xml.Xsl.XPath.XPathScanner.CheckOperator(), System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathScanner.IsAsciiDigit(), System.Xml.XmlCharType.IsStartNCNameSingleChar(), System.Xml.Xsl.XPath.XPathScanner.NextChar(), System.Xml.Xsl.XPath.XPathScanner.ScanNCName(), System.Xml.Xsl.XPath.XPathScanner.ScanNumber(), System.Xml.Xsl.XPath.XPathScanner.ScanString(), System.Xml.Xsl.XPath.XPathScanner.SetSourceIndex(), and System.Xml.Xsl.XPath.XPathScanner.SkipSpace().
Referenced by System.Xml.Xsl.XPath.XPathScanner.XPathScanner(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseFunctionCall(), System.Xml.Xsl.Xslt.XPathPatternParser.ParseIdKeyPattern(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseLocationPath(), System.Xml.Xsl.Xslt.XPathPatternParser.ParseLocationPathPattern(), System.Xml.Xsl.XPath.XPathParser< Node >.ParsePathExpr(), System.Xml.Xsl.Xslt.XPathPatternParser.ParsePattern(), System.Xml.Xsl.Xslt.XPathPatternParser.ParsePredicate(), System.Xml.Xsl.XPath.XPathParser< Node >.ParsePrimaryExpr(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseRelativeLocationPath(), System.Xml.Xsl.Xslt.XPathPatternParser.ParseRelativePathPattern(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseStep(), System.Xml.Xsl.Xslt.XPathPatternParser.ParseStepPattern(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseSubExpr(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseUnionExpr(), and System.Xml.Xsl.XPath.XPathScanner.PassToken().