Terraria: System.Xml.Xsl.XPath.XPathScanner.PassToken
PassToken()
void System.Xml.Xsl.XPath.XPathScanner.PassToken (LexKind t) inline
Definition at line 452 of file XPathScanner.cs.
    {
        CheckToken(t);
        NextLex();
    }
References System.Xml.Xsl.XPath.XPathScanner.CheckToken(), and System.Xml.Xsl.XPath.XPathScanner.NextLex().
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.ParseFunctionCall(), System.Xml.Xsl.Xslt.XPathPatternParser.ParseIdKeyPattern(), System.Xml.Xsl.XPath.XPathParser< Node >.ParsePredicate(), and System.Xml.Xsl.XPath.XPathParser< Node >.ParsePrimaryExpr().