Terraria: System.Xml.Xsl.XPath.XPathScanner.CheckToken
CheckToken()
void System.Xml.Xsl.XPath.XPathScanner.CheckToken (LexKind t) inline
Definition at line 458 of file XPathScanner.cs.
    {
        if (_kind != t)
        {
            if (t == LexKind.Eof)
            {
                throw CreateException(System.SR.XPath_EofExpected, RawValue);
            }
            throw CreateException(System.SR.XPath_TokenExpected, LexKindToString(t), RawValue);
        }
    }
References System.Xml.Xsl.XPath.XPathScanner._kind, System.Xml.Xsl.XPath.XPathScanner.CreateException(), System.Xml.Xsl.XPath.XPathScanner.LexKindToString(), System.Xml.Xsl.XPath.XPathScanner.RawValue, System.SR.XPath_EofExpected, and System.SR.XPath_TokenExpected.
Referenced by System.Xml.Xsl.Xslt.XPathPatternParser.Parse(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseFunctionCall(), System.Xml.Xsl.Xslt.XPathPatternParser.ParseIdKeyPattern(), System.Xml.Xsl.XPath.XPathParser< Node >.ParsePrimaryExpr(), and System.Xml.Xsl.XPath.XPathScanner.PassToken().