Terraria: System.Xml.Xsl.XPath.XPathScanner.ScanString
ScanString()
void System.Xml.Xsl.XPath.XPathScanner.ScanString () inline private
Definition at line 429 of file XPathScanner.cs.
    {
        int num = _curIndex + 1;
        int num2 = _xpathExpr.IndexOf(_curChar, num);
        if (num2 < 0)
        {
            SetSourceIndex(_xpathExpr.Length);
            throw CreateException(System.SR.XPath_UnclosedString);
        }
        _stringValue = _xpathExpr.Substring(num, num2 - num);
        SetSourceIndex(num2 + 1);
    }
References System.Xml.Xsl.XPath.XPathScanner._curChar, System.Xml.Xsl.XPath.XPathScanner._curIndex, System.Xml.Xsl.XPath.XPathScanner._stringValue, System.Xml.Xsl.XPath.XPathScanner._xpathExpr, System.Xml.Xsl.XPath.XPathScanner.CreateException(), System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathScanner.SetSourceIndex(), and System.SR.XPath_UnclosedString.
Referenced by System.Xml.Xsl.XPath.XPathScanner.NextLex().