Terraria: System.Xml.XPath.XPathExpression.Compile
Compile() [1/2]
static XPathExpression System.Xml.XPath.XPathExpression.Compile (string xpath) inline static inherited
Definition at line 26 of file XPathExpression.cs.
    {
        return Compile(xpath, null);
    }
References System.Xml.XPath.XPathExpression.Compile(), and System.Xml.Dictionary.
Referenced by System.Xml.XPath.XPathExpression.Compile(), System.Xml.XPath.XPathNavigator.Compile(), System.Xml.XPath.XPathNavigator.Evaluate(), System.Xml.XPath.XPathNavigator.Evaluate(), System.Xml.XPath.XPathNavigator.Select(), System.Xml.XPath.XPathNavigator.Select(), System.Xml.XmlNode.SelectNodes(), System.Xml.XPath.XPathNavigator.SelectSingleNode(), System.Xml.XPath.XPathNavigator.SelectSingleNode(), and System.Xml.XmlNode.SelectSingleNode().