Terraria: System.Collections.Generic.Dictionary.Dictionary
Dictionary() [1/9]
System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary () inline
Definition at line 768 of file Dictionary.cs.
        : this(0, (IEqualityComparer<TKey>?)null)
    {
    }
Referenced by System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Collections.Generic.Dictionary< TKey, TValue >.Enumerator.Enumerator(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsValue(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyEntries(), System.Collections.Generic.Dictionary< TKey, TValue >.EnsureCapacity(), System.Xml.XmlBufferReader.Equals2(), System.Collections.Generic.Dictionary< TKey, TValue >.FindValue(), System.Runtime.Serialization.ReflectionReader.GetCollectionReadItemDelegate(), System.Runtime.Serialization.ReflectionReader.GetCollectionSetItemDelegate< T >(), System.Collections.Generic.Dictionary< TKey, TValue >.GetObjectData(), System.Collections.Generic.Dictionary< TKey, TValue >.CollectionsMarshalHelper.GetValueRefOrAddDefault(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.IncrementCollectionCount(), System.Collections.Generic.Dictionary< TKey, TValue >.Initialize(), System.Runtime.Serialization.CollectionDataContract.IsCollectionOrTryCreate(), System.Collections.Generic.Dictionary< TKey, TValue >.Enumerator.MoveNext(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.Enumerator.MoveNext(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.Enumerator.MoveNext(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.Resize(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Collections.Generic.Dictionary< TKey, TValue >.TryInsert(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection().