Terraria: ChestUI.RenameChestCancel
RenameChestCancel()
static void ChestUI.RenameChestCancel () inline static
     {
         SoundEngine.PlaySound(12);
         Main.editChest = false;
         Main.npcChatText = string.Empty;
         Main.blockKey = Keys.Escape.ToString();
     }
References Main.blockKey, Main.editChest, Main.npcChatText, and SoundEngine.PlaySound().
Referenced by DrawButton(), UIVirtualKeyboard.DrawSelf(), Main.InputTextChest(), and UIVirtualKeyboard.TryEscapingMenu().