Terraria: ChestUI.TryPlacingInChest
TryPlacingInChest()
static bool ChestUI.TryPlacingInChest (Item I, bool justCheck, int itemSlotContext) inline static
     {
         GetContainerUsageInfo(out var sync, out var chestinv);
         if (IsBlockedFromTransferIntoChest(I, chestinv))
         {
             return false;
         }
         Player player = Main.player[Main.myPlayer];
         bool flag = false;
         if (I.maxStack > 1)
         {
             for (int i = 0; i < 40; i++)
             {
                 if (chestinv[i].stack >= chestinv[i].maxStack || !I.IsTheSameAs(chestinv[i]))
                 {
                     continue;
                 }
                 int num = I.stack;
                 if (I.stack + chestinv[i].stack > chestinv[i].maxStack)
                 {
                     num = chestinv[i].maxStack - chestinv[i].stack;
                 }
                 if (justCheck)
                 {
                     flag = flag || num > 0;
                     break;
                 }
                 I.stack -= num;
                 chestinv[i].stack += num;
                 SoundEngine.PlaySound(7);
                 if (I.stack <= 0)
                 {
                     I.SetDefaults();
                     if (sync)
                     {
                         NetMessage.SendData(32, -1, -1, null, player.chest, i);
                     }
                     break;
                 }
                 if (chestinv[i].type == 0)
                 {
                     chestinv[i] = I.Clone();
                     I.SetDefaults();
                 }
                 if (sync)
                 {
                     NetMessage.SendData(32, -1, -1, null, player.chest, i);
                 }
             }
         }
         if (I.stack > 0)
         {
             for (int j = 0; j < 40; j++)
             {
                 if (chestinv[j].stack != 0)
                 {
                     continue;
                 }
                 if (justCheck)
                 {
                     flag = true;
                     break;
                 }
                 SoundEngine.PlaySound(7);
                 chestinv[j] = I.Clone();
                 I.SetDefaults();
                 ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(chestinv[j], 0, 3));
                 if (sync)
                 {
                     NetMessage.SendData(32, -1, -1, null, player.chest, j);
                 }
                 break;
             }
         }
         return flag;
     }
References ItemSlot.AnnounceTransfer(), Player.chest, GetContainerUsageInfo(), I, IsBlockedFromTransferIntoChest(), Main.myPlayer, Main.player, SoundEngine.PlaySound(), and NetMessage.SendData().
Referenced by ItemSlot.GetOverrideInstructions(), ItemSlot.OverrideHover(), and ItemSlot.OverrideLeftClick().