Terraria: ChestUI.LootAll
LootAll()
static void ChestUI.LootAll () inline static
     {
         GetItemSettings lootAllSettings = GetItemSettings.LootAllSettings;
         Player player = Main.player[Main.myPlayer];
         if (player.chest > -1)
         {
             GetItemSettings lootAllSettingsRegularChest = GetItemSettings.LootAllSettingsRegularChest;
             Chest chest = Main.chest[player.chest];
             for (int i = 0; i < 40; i++)
             {
                 if (chest.item[i].type > 0)
                 {
                     chest.item[i].position = player.Center;
                     chest.item[i] = player.GetItem(Main.myPlayer, chest.item[i], lootAllSettingsRegularChest);
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendData(32, -1, -1, null, player.chest, i);
                     }
                 }
             }
             return;
         }
         if (player.chest == -3)
         {
             for (int j = 0; j < 40; j++)
             {
                 if (player.bank2.item[j].type > 0)
                 {
                     player.bank2.item[j].position = player.Center;
                     player.bank2.item[j] = player.GetItem(Main.myPlayer, player.bank2.item[j], lootAllSettings);
                 }
             }
             return;
         }
         if (player.chest == -4)
         {
             for (int k = 0; k < 40; k++)
             {
                 if (player.bank3.item[k].type > 0)
                 {
                     player.bank3.item[k].position = player.Center;
                     player.bank3.item[k] = player.GetItem(Main.myPlayer, player.bank3.item[k], lootAllSettings);
                 }
             }
             return;
         }
         if (player.chest == -5)
         {
             for (int l = 0; l < 40; l++)
             {
                 if (player.bank4.item[l].type > 0 && !player.bank4.item[l].favorited)
                 {
                     player.bank4.item[l].position = player.Center;
                     player.bank4.item[l] = player.GetItem(Main.myPlayer, player.bank4.item[l], lootAllSettings);
                 }
             }
             return;
         }
         for (int m = 0; m < 40; m++)
         {
             if (player.bank.item[m].type > 0)
             {
                 player.bank.item[m].position = player.Center;
                 player.bank.item[m] = player.GetItem(Main.myPlayer, player.bank.item[m], lootAllSettings);
             }
         }
     }
References Player.bank, Player.bank2, Player.bank3, Player.bank4, Entity.Center, Main.chest, Player.chest, Item.favorited, Player.GetItem(), Chest.item, GetItemSettings.LootAllSettings, GetItemSettings.LootAllSettingsRegularChest, Main.myPlayer, Main.netMode, Main.player, Entity.position, NetMessage.SendData(), and Item.type.
Referenced by DrawButton().