Terraria: System.Collections.Generic.Dictionary.Dictionary
Dictionary() [4/9]
System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary (int capacity, IEqualityComparer< TKey >? comparer) inline
Definition at line 783 of file Dictionary.cs.
    {
        if (capacity < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.capacity);
        }
        if (capacity > 0)
        {
            Initialize(capacity);
        }
        if (comparer != null && comparer != EqualityComparer<TKey>.Default)
        {
            _comparer = comparer;
        }
        if (typeof(TKey) == typeof(string))
        {
            IEqualityComparer<string> stringComparer = NonRandomizedStringEqualityComparer.GetStringComparer(_comparer);
            if (stringComparer != null)
            {
                _comparer = (IEqualityComparer<TKey>)stringComparer;
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Collections.Generic.Dictionary< TKey, TValue >._comparer, System.capacity, System.comparer, System.Default, System.Collections.Generic.NonRandomizedStringEqualityComparer.GetStringComparer(), System.Collections.Generic.Dictionary< TKey, TValue >.Initialize(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().