Terraria: Terraria.GameContent.Biomes.JunglePass.GenerateTunnelToSurface
GenerateTunnelToSurface()
void Terraria.GameContent.Biomes.JunglePass.GenerateTunnelToSurface (int i, int j) inline private
    {
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_041b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0460: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0395: Unknown result type (might be due to invalid IL or missing references)
        //IL_0493: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e7: Unknown result type (might be due to invalid IL or missing references)
        double num = GenBase._random.Next(5, 11);
        Vector2D val = default(Vector2D);
        val.X = i;
        val.Y = j;
        Vector2D val2 = default(Vector2D);
        val2.X = (double)GenBase._random.Next(-10, 11) * 0.1;
        val2.Y = (double)GenBase._random.Next(10, 20) * 0.1;
        int num2 = 0;
        bool flag = true;
        while (flag)
        {
            if (val.Y < Main.worldSurface)
            {
                if (WorldGen.drunkWorldGen)
                {
                    flag = false;
                }
                int value = (int)val.X;
                int value2 = (int)val.Y;
                value = Utils.Clamp(value, 10, Main.maxTilesX - 10);
                value2 = Utils.Clamp(value2, 10, Main.maxTilesY - 10);
                if (value2 < 5)
                {
                    value2 = 5;
                }
                if (Main.tile[value, value2].wall == 0 && !Main.tile[value, value2].active() && Main.tile[value, value2 - 3].wall == 0 && !Main.tile[value, value2 - 3].active() && Main.tile[value, value2 - 1].wall == 0 && !Main.tile[value, value2 - 1].active() && Main.tile[value, value2 - 4].wall == 0 && !Main.tile[value, value2 - 4].active() && Main.tile[value, value2 - 2].wall == 0 && !Main.tile[value, value2 - 2].active() && Main.tile[value, value2 - 5].wall == 0 && !Main.tile[value, value2 - 5].active())
                {
                    flag = false;
                }
            }
            GenVars.JungleX = (int)val.X;
            num += (double)GenBase._random.Next(-20, 21) * 0.1;
            if (num < 5.0)
            {
                num = 5.0;
            }
            if (num > 10.0)
            {
                num = 10.0;
            }
            int value3 = (int)(val.X - num * 0.5);
            int value4 = (int)(val.X + num * 0.5);
            int value5 = (int)(val.Y - num * 0.5);
            int value6 = (int)(val.Y + num * 0.5);
            int num3 = Utils.Clamp(value3, 10, Main.maxTilesX - 10);
            value4 = Utils.Clamp(value4, 10, Main.maxTilesX - 10);
            value5 = Utils.Clamp(value5, 10, Main.maxTilesY - 10);
            value6 = Utils.Clamp(value6, 10, Main.maxTilesY - 10);
            for (int k = num3; k < value4; k++)
            {
                for (int l = value5; l < value6; l++)
                {
                    if (Math.Abs((double)k - val.X) + Math.Abs((double)l - val.Y) < num * 0.5 * (1.0 + (double)GenBase._random.Next(-10, 11) * 0.015))
                    {
                        WorldGen.KillTile(k, l);
                    }
                }
            }
            num2++;
            if (num2 > 10 && GenBase._random.Next(50) < num2)
            {
                num2 = 0;
                int num4 = -2;
                if (GenBase._random.Next(2) == 0)
                {
                    num4 = 2;
                }
                WorldGen.TileRunner((int)val.X, (int)val.Y, GenBase._random.Next(3, 20), GenBase._random.Next(10, 100), -1, addTile: false, num4);
            }
            val += val2;
            val2.Y += (double)GenBase._random.Next(-10, 11) * 0.01;
            if (val2.Y > 0.0)
            {
                val2.Y = 0.0;
            }
            if (val2.Y < -2.0)
            {
                val2.Y = -2.0;
            }
            val2.X += (double)GenBase._random.Next(-10, 11) * 0.1;
            if (val.X < (double)(i - 200))
            {
                val2.X += (double)GenBase._random.Next(5, 21) * 0.1;
            }
            if (val.X > (double)(i + 200))
            {
                val2.X -= (double)GenBase._random.Next(5, 21) * 0.1;
            }
            if (val2.X > 1.5)
            {
                val2.X = 1.5;
            }
            if (val2.X < -1.5)
            {
                val2.X = -1.5;
            }
        }
    }
References Terraria.WorldBuilding.GenBase._random, Terraria.Tile.active(), Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.KillTile(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.WorldGen.TileRunner(), Terraria.Tile.wall, Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Biomes.JunglePass.ApplyPass().