Terraria: System.Threading.Tasks.TaskFactory.FromAsyncTrimPromise.Complete
Complete()
void System.Threading.Tasks.TaskFactory< TResult >.FromAsyncTrimPromise< TInstance >.Complete (TInstance thisRef, Func< TInstance, IAsyncResult, TResult > endMethod, IAsyncResult asyncResult, bool requiresSynchronization) inline package
Definition at line 46 of file TaskFactory.cs.
        {
            try
            {
                TResult result = endMethod(thisRef, asyncResult);
                bool flag;
                if (requiresSynchronization)
                {
                    flag = TrySetResult(result);
                    return;
                }
                DangerousSetResult(result);
                flag = true;
            }
            catch (OperationCanceledException ex)
            {
                bool flag = TrySetCanceled(ex.CancellationToken, ex);
            }
            catch (Exception exceptionObject)
            {
                bool flag = TrySetException(exceptionObject);
            }
        }
References System.asyncResult, System.Threading.Tasks.Task< TResult >.DangerousSetResult(), System.endMethod, System.Threading.Tasks.Task< TResult >.TrySetCanceled(), System.Threading.Tasks.Task< TResult >.TrySetException(), and System.Threading.Tasks.Task< TResult >.TrySetResult().