Terraria: Terraria.Social.Steam.SteamP2PReader.ReadTick
ReadTick()
void Terraria.Social.Steam.SteamP2PReader.ReadTick () inline
Definition at line 87 of file SteamP2PReader.cs.
    {
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        lock (_pendingReadBuffers)
        {
            while (_deletionQueue.Count > 0)
            {
                _pendingReadBuffers.Remove(_deletionQueue.Dequeue());
            }
            uint size;
            uint size2 = default(uint);
            CSteamID val = default(CSteamID);
            while (IsPacketAvailable(out size))
            {
                byte[] array = ((_bufferPool.Count != 0) ? _bufferPool.Dequeue() : new byte[Math.Max(size, 4096u)]);
                bool flag;
                lock (SteamLock)
                {
                    flag = SteamNetworking.ReadP2PPacket(array, (uint)array.Length, ref size2, ref val, _channel);
                }
                if (!flag)
                {
                    continue;
                }
                if (_readEvent == null || _readEvent(array, (int)size2, val))
                {
                    if (!_pendingReadBuffers.ContainsKey(val))
                    {
                        _pendingReadBuffers[val] = new Queue<ReadResult>();
                    }
                    _pendingReadBuffers[val].Enqueue(new ReadResult(array, size2));
                }
                else
                {
                    _bufferPool.Enqueue(array);
                }
            }
        }
    }
References Terraria.Social.Steam.SteamP2PReader._bufferPool, Terraria.Social.Steam.SteamP2PReader._channel, Terraria.Social.Steam.SteamP2PReader._deletionQueue, Terraria.Social.Steam.SteamP2PReader._pendingReadBuffers, Terraria.Social.Steam.SteamP2PReader._readEvent, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Collections.Generic.Queue< T >.Count, System.Collections.Generic.Queue< T >.Dequeue(), System.Collections.Generic.Queue< T >.Enqueue(), Terraria.Social.Steam.SteamP2PReader.IsPacketAvailable(), System.Math.Max(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and Terraria.Social.Steam.SteamP2PReader.SteamLock.
Referenced by Terraria.Social.Steam.NetSocialModule.Initialize().