Terraria: System.Xml.Schema.XmlBooleanConverter.ChangeType
ChangeType() [8/9]
override object System.Xml.Schema.XmlBooleanConverter.ChangeType (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline
Definition at line 135 of file XmlBooleanConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        Type type = value.GetType();
        if (destinationType == XmlBaseConverter.ObjectType)
        {
            destinationType = base.DefaultClrType;
        }
        if (destinationType == XmlBaseConverter.BooleanType)
        {
            return ToBoolean(value);
        }
        if (destinationType == XmlBaseConverter.StringType)
        {
            return ToString(value, nsResolver);
        }
        if (destinationType == XmlBaseConverter.XmlAtomicValueType)
        {
            if (type == XmlBaseConverter.BooleanType)
            {
                return new XmlAtomicValue(base.SchemaType, (bool)value);
            }
            if (type == XmlBaseConverter.StringType)
            {
                return new XmlAtomicValue(base.SchemaType, (string)value);
            }
            if (type == XmlBaseConverter.XmlAtomicValueType)
            {
                return (XmlAtomicValue)value;
            }
        }
        if (destinationType == XmlBaseConverter.XPathItemType)
        {
            if (type == XmlBaseConverter.BooleanType)
            {
                return new XmlAtomicValue(base.SchemaType, (bool)value);
            }
            if (type == XmlBaseConverter.StringType)
            {
                return new XmlAtomicValue(base.SchemaType, (string)value);
            }
            if (type == XmlBaseConverter.XmlAtomicValueType)
            {
                return (XmlAtomicValue)value;
            }
        }
        return ChangeListType(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.BooleanType, System.Xml.Schema.XmlBaseConverter.ChangeListType(), System.Xml.Dictionary, System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.ObjectType, System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlBooleanConverter.ToBoolean(), System.ToString, System.type, System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, and System.Xml.Schema.XmlBaseConverter.XPathItemType.