Terraria: System.Xml.XmlCharCheckingReader.ReadAsync
ReadAsync()
override async Task< bool > System.Xml.XmlCharCheckingReader.ReadAsync () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 520 of file XmlCharCheckingReader.cs.
    {
        switch (_state)
        {
        case State.Initial:
            _state = State.Interactive;
            if (reader.ReadState != 0)
            {
                break;
            }
            goto case State.Interactive;
        case State.Error:
            return false;
        case State.InReadBinary:
            await FinishReadBinaryAsync().ConfigureAwait(continueOnCapturedContext: false);
            _state = State.Interactive;
            goto case State.Interactive;
        case State.Interactive:
            if (!(await reader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false)))
            {
                return false;
            }
            break;
        default:
            return false;
        }
        XmlNodeType nodeType = reader.NodeType;
        if (!_checkCharacters)
        {
            switch (nodeType)
            {
            case XmlNodeType.Comment:
                if (_ignoreComments)
                {
                    return await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
                break;
            case XmlNodeType.Whitespace:
                if (_ignoreWhitespace)
                {
                    return await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
                break;
            case XmlNodeType.ProcessingInstruction:
                if (_ignorePis)
                {
                    return await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
                break;
            case XmlNodeType.DocumentType:
                if (_dtdProcessing == DtdProcessing.Prohibit)
                {
                    Throw(System.SR.Xml_DtdIsProhibitedEx, string.Empty);
                }
                else if (_dtdProcessing == DtdProcessing.Ignore)
                {
                    return await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
                break;
            }
            return true;
        }
        switch (nodeType)
        {
        case XmlNodeType.Element:
            if (!_checkCharacters)
            {
                break;
            }
            ValidateQName(reader.Prefix, reader.LocalName);
            if (reader.MoveToFirstAttribute())
            {
                do
                {
                    ValidateQName(reader.Prefix, reader.LocalName);
                    CheckCharacters(reader.Value);
                }
                while (reader.MoveToNextAttribute());
                reader.MoveToElement();
            }
            break;
        case XmlNodeType.Text:
        case XmlNodeType.CDATA:
            if (_checkCharacters)
            {
                CheckCharacters(await reader.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
            }
            break;
        case XmlNodeType.EntityReference:
            if (_checkCharacters)
            {
                ValidateQName(reader.Name);
            }
            break;
        case XmlNodeType.ProcessingInstruction:
            if (_ignorePis)
            {
                return await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            if (_checkCharacters)
            {
                ValidateQName(reader.Name);
                CheckCharacters(reader.Value);
            }
            break;
        case XmlNodeType.Comment:
            if (_ignoreComments)
            {
                return await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            if (_checkCharacters)
            {
                CheckCharacters(reader.Value);
            }
            break;
        case XmlNodeType.DocumentType:
            if (_dtdProcessing == DtdProcessing.Prohibit)
            {
                Throw(System.SR.Xml_DtdIsProhibitedEx, string.Empty);
            }
            else if (_dtdProcessing == DtdProcessing.Ignore)
            {
                return await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            if (_checkCharacters)
            {
                ValidateQName(reader.Name);
                CheckCharacters(reader.Value);
                string attribute = reader.GetAttribute("SYSTEM");
                if (attribute != null)
                {
                    CheckCharacters(attribute);
                }
                attribute = reader.GetAttribute("PUBLIC");
                int invCharIndex;
                if (attribute != null && (invCharIndex = XmlCharType.IsPublicId(attribute)) >= 0)
                {
                    Throw(System.SR.Xml_InvalidCharacter, XmlException.BuildCharExceptionArgs(attribute, invCharIndex));
                }
            }
            break;
        case XmlNodeType.Whitespace:
            if (_ignoreWhitespace)
            {
                return await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            if (_checkCharacters)
            {
                CheckWhitespace(await reader.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
            }
            break;
        case XmlNodeType.SignificantWhitespace:
            if (_checkCharacters)
            {
                CheckWhitespace(await reader.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
            }
            break;
        case XmlNodeType.EndElement:
            if (_checkCharacters)
            {
                ValidateQName(reader.Prefix, reader.LocalName);
            }
            break;
        }
        _lastNodeType = nodeType;
        return true;
    }
References System.Xml.XmlCharCheckingReader._checkCharacters, System.Xml.XmlCharCheckingReader._dtdProcessing, System.Xml.XmlCharCheckingReader._ignoreComments, System.Xml.XmlCharCheckingReader._ignorePis, System.Xml.XmlCharCheckingReader._ignoreWhitespace, System.Xml.XmlCharCheckingReader._lastNodeType, System.Xml.XmlCharCheckingReader._state, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlCharCheckingReader.CheckCharacters(), System.Xml.XmlCharCheckingReader.CheckWhitespace(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlCharCheckingReader.FinishReadBinaryAsync(), System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.GetValueAsync(), System.Xml.XmlCharType.IsPublicId(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlCharCheckingReader.ReadAsync(), System.Xml.XmlReader.ReadAsync(), System.Xml.XmlWrappingReader.reader, System.Xml.XmlReader.ReadState, System.Xml.XmlCharCheckingReader.Throw(), System.Xml.XmlCharCheckingReader.ValidateQName(), System.Xml.XmlReader.Value, System.SR.Xml_DtdIsProhibitedEx, and System.SR.Xml_InvalidCharacter.
Referenced by System.Xml.XmlCharCheckingReader.ReadAsync().