Terraria: System.Xml.XmlCharCheckingReader.ReadContentAsBase64Async
ReadContentAsBase64Async()
override async Task< int > System.Xml.XmlCharCheckingReader.ReadContentAsBase64Async (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 688 of file XmlCharCheckingReader.cs.
    {
        if (ReadState != ReadState.Interactive)
        {
            return 0;
        }
        if (_state != State.InReadBinary)
        {
            if (base.CanReadBinaryContent && !_checkCharacters)
            {
                _readBinaryHelper = null;
                _state = State.InReadBinary;
                return await base.ReadContentAsBase64Async(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
            }
            _readBinaryHelper = ReadContentAsBinaryHelper.CreateOrReset(_readBinaryHelper, this);
        }
        else if (_readBinaryHelper == null)
        {
            return await base.ReadContentAsBase64Async(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
        }
        _state = State.Interactive;
        int result = await _readBinaryHelper.ReadContentAsBase64Async(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
        _state = State.InReadBinary;
        return result;
    }
References System.Xml.XmlCharCheckingReader._checkCharacters, System.Xml.XmlCharCheckingReader._readBinaryHelper, System.Xml.XmlCharCheckingReader._state, System.buffer, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.Xml.ReadContentAsBinaryHelper.CreateOrReset(), System.Xml.Dictionary, System.index, and System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64Async().