Terraria: System.Xml.Schema.XmlBooleanConverter.ToString
ToString() [10/10]
override string System.Xml.Schema.XmlBooleanConverter.ToString (object value, IXmlNamespaceResolver nsResolver) inline
Definition at line 51 of file XmlBooleanConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        Type type = value.GetType();
        if (type == XmlBaseConverter.BooleanType)
        {
            return XmlConvert.ToString((bool)value);
        }
        if (type == XmlBaseConverter.StringType)
        {
            return (string)value;
        }
        if (type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).Value;
        }
        return (string)ChangeListType(value, XmlBaseConverter.StringType, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.BooleanType, System.Xml.Schema.XmlBaseConverter.ChangeListType(), System.Xml.Dictionary, System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.XmlConvert.ToString(), System.type, System.value, and System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType.