Terraria: ReLogic.Peripherals.RGB.ChromaEngine._deviceGroups
_deviceGroups
readonly Dictionary<string, RgbDeviceGroup> ReLogic.Peripherals.RGB.ChromaEngine._deviceGroups = new Dictionary<string, RgbDeviceGroup>() private
Definition at line 19 of file ChromaEngine.cs.
Referenced by ReLogic.Peripherals.RGB.ChromaEngine.AddDeviceGroup(), ReLogic.Peripherals.RGB.ChromaEngine.DebugDraw(), ReLogic.Peripherals.RGB.ChromaEngine.DisableAllDeviceGroups(), ReLogic.Peripherals.RGB.ChromaEngine.DisableDeviceGroup(), ReLogic.Peripherals.RGB.ChromaEngine.Draw(), ReLogic.Peripherals.RGB.ChromaEngine.EnableAllDeviceGroups(), ReLogic.Peripherals.RGB.ChromaEngine.EnableDeviceGroup(), ReLogic.Peripherals.RGB.ChromaEngine.HasDeviceGroup(), ReLogic.Peripherals.RGB.ChromaEngine.IsDeviceGroupEnabled(), ReLogic.Peripherals.RGB.ChromaEngine.LoadSpecialRules(), ReLogic.Peripherals.RGB.ChromaEngine.RemoveDeviceGroup(), and ReLogic.Peripherals.RGB.ChromaEngine.Update().