Terraria: ReLogic.Peripherals.RGB.ChromaEngine.DisableAllDeviceGroups
DisableAllDeviceGroups()
void ReLogic.Peripherals.RGB.ChromaEngine.DisableAllDeviceGroups () inline
    {
        lock (_updateLock)
        {
            foreach (RgbDeviceGroup item in _deviceGroups.Values.Where((RgbDeviceGroup deviceGroup) => deviceGroup.IsEnabled))
            {
                item.Disable();
            }
        }
    }
References ReLogic.Peripherals.RGB.ChromaEngine._deviceGroups, ReLogic.Peripherals.RGB.ChromaEngine._updateLock, ReLogic.Peripherals.RGB.RgbDeviceGroup.Disable(), and ReLogic.Peripherals.RGB.RgbDeviceGroup.IsEnabled.
Referenced by Terraria.Initializers.ChromaInitializer.DisableAllDeviceGroups(), ReLogic.Peripherals.RGB.ChromaEngine.Draw(), and ReLogic.Peripherals.RGB.ChromaEngine.Update().