Terraria: System.Xml.XmlCharCheckingReader.ReadElementContentAsBinHexAsync
ReadElementContentAsBinHexAsync()
override async Task< int > System.Xml.XmlCharCheckingReader.ReadElementContentAsBinHexAsync (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 782 of file XmlCharCheckingReader.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (ReadState != ReadState.Interactive)
        {
            return 0;
        }
        if (_state != State.InReadBinary)
        {
            if (base.CanReadBinaryContent && !_checkCharacters)
            {
                _readBinaryHelper = null;
                _state = State.InReadBinary;
                return await base.ReadElementContentAsBinHexAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
            }
            _readBinaryHelper = ReadContentAsBinaryHelper.CreateOrReset(_readBinaryHelper, this);
        }
        else if (_readBinaryHelper == null)
        {
            return await base.ReadElementContentAsBinHexAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
        }
        _state = State.Interactive;
        int result = await _readBinaryHelper.ReadElementContentAsBinHexAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
        _state = State.InReadBinary;
        return result;
    }
References System.Xml.XmlCharCheckingReader._checkCharacters, System.Xml.XmlCharCheckingReader._readBinaryHelper, System.Xml.XmlCharCheckingReader._state, System.buffer, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.Xml.ReadContentAsBinaryHelper.CreateOrReset(), System.Xml.Dictionary, System.index, and System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHexAsync().