Terraria: System.Collections.Immutable.ImmutableList.Node.CreateRange
CreateRange()
static Node System.Collections.Immutable.ImmutableList< T >.Node.CreateRange (IEnumerable< T > keys) inline static private
Definition at line 1573 of file ImmutableList.cs.
        {
            if (ImmutableList<T>.TryCastToImmutableList(keys, out ImmutableList<T> other))
            {
                return other._root;
            }
            IOrderedCollection<T> orderedCollection = keys.AsOrderedCollection();
            return NodeTreeFromList(orderedCollection, 0, orderedCollection.Count);
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.keys, System.Collections.Immutable.ImmutableList< T >.Node.NodeTreeFromList(), System.other, and System.Collections.Immutable.ImmutableList< T >.TryCastToImmutableList().
Referenced by System.Collections.Immutable.ImmutableList< T >.Node.AddRange(), and System.Collections.Immutable.ImmutableList< T >.Node.InsertRange().