Terraria: System.Collections.Immutable.ImmutableList.Node.FindAll
FindAll()
ImmutableList< T > System.Collections.Immutable.ImmutableList< T >.Node.FindAll (Predicate< T > match) inline package
Definition at line 1308 of file ImmutableList.cs.
        {
            Requires.NotNull(match, "match");
            if (IsEmpty)
            {
                return ImmutableList<T>.Empty;
            }
            List<T> list = null;
            using (Enumerator enumerator = GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    T current = enumerator.Current;
                    if (match(current))
                    {
                        if (list == null)
{
                            list = new List<T>();
                        }
                        list.Add(current);
                    }
                }
            }
            if (list == null)
            {
                return ImmutableList<T>.Empty;
            }
            return ImmutableList.CreateRange(list);
        }
References System.Collections.Immutable.ImmutableList< T >.CreateRange(), System.Collections.Immutable.ImmutableList< T >.Node.GetEnumerator(), System.Collections.Immutable.ImmutableList< T >.Node.IsEmpty, System.list, and System.match.
Referenced by System.Collections.Immutable.ImmutableList< T >.Builder.FindAll(), and System.Collections.Immutable.ImmutableList< T >.FindAll().