Terraria: System.Collections.Immutable.ImmutableList.Node.GetEnumerator
GetEnumerator() [1/4]
Enumerator System.Collections.Immutable.ImmutableList< T >.Node.GetEnumerator () inline
Implements System.Collections.IEnumerable.
Definition at line 836 of file ImmutableList.cs.
        {
            return new Enumerator(this);
        }
Referenced by System.Collections.Immutable.ImmutableList< T >.Node.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Node.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Node.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Node.Exists(), System.Collections.Immutable.ImmutableList< T >.Node.Find(), System.Collections.Immutable.ImmutableList< T >.Node.FindAll(), System.Collections.Immutable.ImmutableList< T >.Builder.GetEnumerator(), System.Collections.Immutable.ImmutableList< T >.Node.GetEnumerator(), and System.Collections.Immutable.ImmutableList< T >.Node.TrueForAll().