Terraria: System.Collections.Immutable.ImmutableList.Node.BalanceLeft
BalanceLeft()
Node System.Collections.Immutable.ImmutableList< T >.Node.BalanceLeft () inline private
Definition at line 1474 of file ImmutableList.cs.
        {
            if (_left.BalanceFactor <= 0)
            {
                return RotateRight();
            }
            return DoubleRight();
        }
References System.Collections.Immutable.ImmutableList< T >.Node._left, System.Collections.Immutable.ImmutableList< T >.Node.BalanceFactor, System.Collections.Immutable.ImmutableList< T >.Node.DoubleRight(), and System.Collections.Immutable.ImmutableList< T >.Node.RotateRight().
Referenced by System.Collections.Immutable.ImmutableList< T >.Node.Balance().