Terraria: System.Collections.Immutable.ImmutableList.Node.CopyTo
CopyTo() [3/4]
void System.Collections.Immutable.ImmutableList< T >.Node.CopyTo (T[] array) inline package
Definition at line 1193 of file ImmutableList.cs.
        {
            Requires.NotNull(array, "array");
            Requires.Range(array.Length >= Count, "array");
            int num = 0;
            using Enumerator enumerator = GetEnumerator();
            while (enumerator.MoveNext())
            {
                T current = enumerator.Current;
                array[num++] = current;
            }
        }
References System.array, System.Collections.Immutable.ImmutableList< T >.Node.Count, System.Collections.Immutable.ImmutableList< T >.Node.GetEnumerator(), and System.Collections.Immutable.Requires.Range().
Referenced by System.Collections.Immutable.ImmutableList< T >.Builder.CopyTo(), System.Collections.Immutable.ImmutableList< T >.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Builder.CopyTo(), System.Collections.Immutable.ImmutableList< T >.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Builder.CopyTo(), System.Collections.Immutable.ImmutableList< T >.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Builder.CopyTo(), System.Collections.Immutable.ImmutableList< T >.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Node.Sort(), and System.Collections.Immutable.ImmutableList< T >.Node.Sort().