Terraria: System.Collections.Immutable.ImmutableList.Node.Exists
Exists()
bool System.Collections.Immutable.ImmutableList< T >.Node.Exists (Predicate< T > match) inline package
Definition at line 1274 of file ImmutableList.cs.
        {
            Requires.NotNull(match, "match");
            using (Enumerator enumerator = GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    T current = enumerator.Current;
                    if (match(current))
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References System.Collections.Immutable.ImmutableList< T >.Node.GetEnumerator(), and System.match.
Referenced by System.Collections.Immutable.ImmutableList< T >.Builder.Exists(), and System.Collections.Immutable.ImmutableList< T >.Exists().