Terraria: System.Collections.Immutable.ImmutableList.Node.RemoveAt
RemoveAt()
Node System.Collections.Immutable.ImmutableList< T >.Node.RemoveAt (int index) inline package
Definition at line 949 of file ImmutableList.cs.
        {
            Requires.Range(index >= 0 && index < Count, "index");
            Node node = this;
            if (index == _left._count)
            {
                if (_right.IsEmpty && _left.IsEmpty)
                {
                    node = EmptyNode;
                }
                else if (_right.IsEmpty && !_left.IsEmpty)
                {
                    node = _left;
                }
                else if (!_right.IsEmpty && _left.IsEmpty)
                {
                    node = _right;
                }
                else
                {
                    Node node2 = _right;
                    while (!node2._left.IsEmpty)
                    {
                        node2 = node2._left;
                    }
                    Node right = _right.RemoveAt(0);
                    node = node2.MutateBoth(_left, right);
                }
            }
            else if (index < _left._count)
            {
                Node left = _left.RemoveAt(index);
                node = MutateLeft(left);
            }
            else
            {
                Node right2 = _right.RemoveAt(index - _left._count - 1);
                node = MutateRight(right2);
            }
            if (!node.IsEmpty && !node.IsBalanced)
            {
                return node.Balance();
            }
            return node;
        }
References System.Collections.Immutable.ImmutableList< T >.Node._count, System.Collections.Immutable.ImmutableList< T >.Node._left, System.Collections.Immutable.ImmutableList< T >.Node._right, System.Collections.Immutable.ImmutableList< T >.Node.Count, System.Collections.Immutable.ImmutableList< T >.Node.EmptyNode, System.index, System.Collections.Immutable.ImmutableList< T >.Node.IsEmpty, System.Collections.Immutable.ImmutableList< T >.Node.MutateLeft(), System.Collections.Immutable.ImmutableList< T >.Node.MutateRight(), System.Collections.Immutable.Requires.Range(), and System.Collections.Immutable.ImmutableList< T >.Node.RemoveAt().
Referenced by System.Collections.Immutable.ImmutableList< T >.Builder.Remove(), System.Collections.Immutable.ImmutableList< T >.Builder.RemoveAt(), System.Collections.Immutable.ImmutableList< T >.Node.RemoveAt(), and System.Collections.Immutable.ImmutableList< T >.RemoveAt().