Terraria: System.Collections.Immutable.ImmutableList.Node.Sort
Sort() [4/4]
Node System.Collections.Immutable.ImmutableList< T >.Node.Sort (int index, int count, IComparer< T >? comparer) inline package
Definition at line 1084 of file ImmutableList.cs.
        {
            Requires.Range(index >= 0, "index");
            Requires.Range(count >= 0, "count");
            Requires.Argument(index + count <= Count);
            T[] array = new T[Count];
            CopyTo(array);
            Array.Sort(array, index, count, comparer);
            return NodeTreeFromList(array.AsOrderedCollection(), 0, Count);
        }
References System.Collections.Immutable.Requires.Argument(), System.array, System.comparer, System.Collections.Immutable.ImmutableList< T >.Node.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Node.Count, System.count, System.index, System.Collections.Immutable.ImmutableList< T >.Node.NodeTreeFromList(), System.Collections.Immutable.Requires.Range(), and System.Array.Sort().