Terraria: System.Collections.Immutable.ImmutableList.Node.InsertRange
InsertRange()
Node System.Collections.Immutable.ImmutableList< T >.Node.InsertRange (int index, IEnumerable< T > keys) inline package
Definition at line 927 of file ImmutableList.cs.
        {
            Requires.Range(index >= 0 && index <= Count, "index");
            Requires.NotNull(keys, "keys");
            if (IsEmpty)
            {
                return CreateRange(keys);
            }
            Node node;
            if (index <= _left._count)
            {
                Node left = _left.InsertRange(index, keys);
                node = MutateLeft(left);
            }
            else
            {
                Node right = _right.InsertRange(index - _left._count - 1, keys);
                node = MutateRight(right);
            }
            return node.BalanceMany();
        }
References System.Collections.Immutable.ImmutableList< T >.Node._count, System.Collections.Immutable.ImmutableList< T >.Node._left, System.Collections.Immutable.ImmutableList< T >.Node._right, System.Collections.Immutable.ImmutableList< T >.Node.Count, System.Collections.Immutable.ImmutableList< T >.Node.CreateRange(), System.index, System.Collections.Immutable.ImmutableList< T >.Node.InsertRange(), System.Collections.Immutable.ImmutableList< T >.Node.IsEmpty, System.keys, System.Collections.Immutable.ImmutableList< T >.Node.MutateLeft(), System.Collections.Immutable.ImmutableList< T >.Node.MutateRight(), and System.Collections.Immutable.Requires.Range().
Referenced by System.Collections.Immutable.ImmutableList< T >.Builder.InsertRange(), System.Collections.Immutable.ImmutableList< T >.InsertRange(), and System.Collections.Immutable.ImmutableList< T >.Node.InsertRange().