Terraria: System.Collections.Immutable.ImmutableList.Node.Node
Node() [1/2]
System.Collections.Immutable.ImmutableList< T >.Node.Node () inline private
Definition at line 800 of file ImmutableList.cs.
        {
            _frozen = true;
        }
References System.Collections.Immutable.ImmutableList< T >.Node._frozen.
Referenced by System.Collections.Immutable.ImmutableList< T >.Node.CreateLeaf(), System.Collections.Immutable.ImmutableList< T >.Node.MutateBoth(), System.Collections.Immutable.ImmutableList< T >.Node.MutateKey(), System.Collections.Immutable.ImmutableList< T >.Node.MutateLeft(), System.Collections.Immutable.ImmutableList< T >.Node.MutateRight(), and System.Collections.Immutable.ImmutableList< T >.Node.NodeTreeFromList().