Terraria: System.Collections.Immutable.ImmutableList.Node.Sort
Sort() [2/4]
Node System.Collections.Immutable.ImmutableList< T >.Node.Sort (Comparison< T > comparison) inline package
Definition at line 1070 of file ImmutableList.cs.
        {
            Requires.NotNull(comparison, "comparison");
            T[] array = new T[Count];
            CopyTo(array);
            Array.Sort(array, comparison);
            return NodeTreeFromList(array.AsOrderedCollection(), 0, Count);
        }
References System.array, System.comparison, System.Collections.Immutable.ImmutableList< T >.Node.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Node.Count, System.Collections.Immutable.ImmutableList< T >.Node.NodeTreeFromList(), and System.Array.Sort().