Terraria: System.Collections.Immutable.ImmutableList.Node.BinarySearch
BinarySearch()
int System.Collections.Immutable.ImmutableList< T >.Node.BinarySearch (int index, int count, T item, IComparer< T >? comparer) inline package
Definition at line 1095 of file ImmutableList.cs.
        {
            Requires.Range(index >= 0, "index");
            Requires.Range(count >= 0, "count");
            comparer = comparer ?? Comparer<T>.Default;
            if (IsEmpty || count <= 0)
            {
                return ~index;
            }
            int count2 = _left.Count;
            if (index + count <= count2)
            {
                return _left.BinarySearch(index, count, item, comparer);
            }
            if (index > count2)
            {
                int num = _right.BinarySearch(index - count2 - 1, count, item, comparer);
                int num2 = count2 + 1;
                if (num >= 0)
                {
                    return num + num2;
                }
                return num - num2;
            }
            int num3 = comparer.Compare(item, _key);
            if (num3 == 0)
            {
                return count2;
            }
            if (num3 > 0)
            {
                int num4 = count - (count2 - index) - 1;
                int num5 = ((num4 < 0) ? (-1) : _right.BinarySearch(0, num4, item, comparer));
                int num6 = count2 + 1;
                if (num5 >= 0)
                {
                    return num5 + num6;
                }
                return num5 - num6;
            }
            if (index == count2)
            {
                return ~index;
            }
            return _left.BinarySearch(index, count, item, comparer);
        }
References System.Collections.Immutable.ImmutableList< T >.Node._key, System.Collections.Immutable.ImmutableList< T >.Node._left, System.Collections.Immutable.ImmutableList< T >.Node._right, System.Collections.Immutable.ImmutableList< T >.Node.BinarySearch(), System.comparer, System.Collections.Immutable.ImmutableList< T >.Node.Count, System.count, System.index, System.Collections.Immutable.ImmutableList< T >.Node.IsEmpty, System.item, and System.Collections.Immutable.Requires.Range().
Referenced by System.Collections.Immutable.ImmutableList< T >.Builder.BinarySearch(), System.Collections.Immutable.ImmutableList< T >.Node.BinarySearch(), and System.Collections.Immutable.ImmutableList< T >.BinarySearch().