Terraria: System.Collections.Immutable.ImmutableList.Node.AddRange
AddRange()
Node System.Collections.Immutable.ImmutableList< T >.Node.AddRange (IEnumerable< T > keys) inline package
Definition at line 915 of file ImmutableList.cs.
        {
            Requires.NotNull(keys, "keys");
            if (IsEmpty)
            {
                return CreateRange(keys);
            }
            Node right = _right.AddRange(keys);
            Node node = MutateRight(right);
            return node.BalanceMany();
        }
References System.Collections.Immutable.ImmutableList< T >.Node._right, System.Collections.Immutable.ImmutableList< T >.Node.AddRange(), System.Collections.Immutable.ImmutableList< T >.Node.CreateRange(), System.Collections.Immutable.ImmutableList< T >.Node.IsEmpty, System.keys, and System.Collections.Immutable.ImmutableList< T >.Node.MutateRight().
Referenced by System.Collections.Immutable.ImmutableList< T >.Builder.AddRange(), System.Collections.Immutable.ImmutableList< T >.AddRange(), and System.Collections.Immutable.ImmutableList< T >.Node.AddRange().