Terraria: System.Collections.Immutable.ImmutableList.Node.Sort
Sort() [1/4]
Node System.Collections.Immutable.ImmutableList< T >.Node.Sort () inline package
Definition at line 1065 of file ImmutableList.cs.
        {
            return Sort(Comparer<T>.Default);
        }
References System.Default, and System.Collections.Immutable.ImmutableList< T >.Node.Sort().
Referenced by System.Collections.Immutable.ImmutableList< T >.Builder.Sort(), System.Collections.Immutable.ImmutableList< T >.Node.Sort(), System.Collections.Immutable.ImmutableList< T >.Sort(), System.Collections.Immutable.ImmutableList< T >.Builder.Sort(), System.Collections.Immutable.ImmutableList< T >.Sort(), System.Collections.Immutable.ImmutableList< T >.Builder.Sort(), System.Collections.Immutable.ImmutableList< T >.Node.Sort(), System.Collections.Immutable.ImmutableList< T >.Sort(), System.Collections.Immutable.ImmutableList< T >.Builder.Sort(), and System.Collections.Immutable.ImmutableList< T >.Sort().