Terraria: System.Numerics.Plane.Normalize
Normalize()
static Plane System.Numerics.Plane.Normalize (Plane value) inline static
Definition at line 85 of file Plane.cs.
    {
        if (Vector.IsHardwareAccelerated)
        {
            float num = value.Normal.LengthSquared();
            if (MathF.Abs(num - 1f) < 1.1920929E-07f)
            {
                return value;
            }
            float num2 = MathF.Sqrt(num);
            return new Plane(value.Normal / num2, value.D / num2);
        }
        float num3 = value.Normal.X * value.Normal.X + value.Normal.Y * value.Normal.Y + value.Normal.Z * value.Normal.Z;
        if (MathF.Abs(num3 - 1f) < 1.1920929E-07f)
        {
            return value;
        }
        float num4 = 1f / MathF.Sqrt(num3);
        return new Plane(value.Normal.X * num4, value.Normal.Y * num4, value.Normal.Z * num4, value.D * num4);
    }
References System.Numerics.Plane.Plane(), System.MathF.Abs(), System.Numerics.Vector< T >.IsHardwareAccelerated, System.MathF.Sqrt(), and System.value.
Referenced by System.Numerics.Matrix4x4.CreateReflection(), and System.Numerics.Matrix4x4.CreateShadow().