Terraria: System.Numerics.Plane.CreateFromVertices
CreateFromVertices()
static Plane System.Numerics.Plane.CreateFromVertices (Vector3 point1, Vector3 point2, Vector3 point3) inline static
Definition at line 32 of file Plane.cs.
    {
        if (Vector.IsHardwareAccelerated)
        {
            Vector3 vector = point2 - point1;
            Vector3 vector2 = point3 - point1;
            Vector3 value = Vector3.Cross(vector, vector2);
            Vector3 vector3 = Vector3.Normalize(value);
            float d = 0f - Vector3.Dot(vector3, point1);
            return new Plane(vector3, d);
        }
        float num = point2.X - point1.X;
        float num2 = point2.Y - point1.Y;
        float num3 = point2.Z - point1.Z;
        float num4 = point3.X - point1.X;
        float num5 = point3.Y - point1.Y;
        float num6 = point3.Z - point1.Z;
        float num7 = num2 * num6 - num3 * num5;
        float num8 = num3 * num4 - num * num6;
        float num9 = num * num5 - num2 * num4;
        float x = num7 * num7 + num8 * num8 + num9 * num9;
        float num10 = 1f / MathF.Sqrt(x);
        Vector3 normal = new Vector3(num7 * num10, num8 * num10, num9 * num10);
        return new Plane(normal, 0f - (normal.X * point1.X + normal.Y * point1.Y + normal.Z * point1.Z));
    }
References System.Numerics.Plane.Plane(), System.Numerics.Vector3.Cross(), System.Numerics.Vector3.Dot(), System.Numerics.Vector< T >.IsHardwareAccelerated, System.Numerics.Vector3.Normalize(), System.MathF.Sqrt(), System.value, System.Numerics.Vector3.X, System.Numerics.Vector3.Y, and System.Numerics.Vector3.Z.