Terraria: Terraria.GameContent.UI.WiresUI.WiresRadial.DrawLine
DrawLine()
void Terraria.GameContent.UI.WiresUI.WiresRadial.DrawLine (SpriteBatch spriteBatch) inline private
Definition at line 177 of file WiresUI.cs.
        {
            if (active || _lineOpacity == 0f)
            {
                return;
            }
            Vector2 vector = Main.MouseScreen;
            Vector2 vector2 = new Vector2(Main.screenWidth / 2, Main.screenHeight - 70);
            if (PlayerInput.UsingGamepad)
            {
                vector = Vector2.Zero;
            }
            Vector2 vector3 = vector - vector2;
            Vector2.Dot(Vector2.Normalize(vector3), Vector2.UnitX);
            Vector2.Dot(Vector2.Normalize(vector3), Vector2.UnitY);
            vector3.ToRotation();
            vector3.Length();
            bool flag = false;
            bool drawToolAllowActuators = Settings.DrawToolAllowActuators;
            for (int i = 0; i < 6; i++)
            {
                if (!drawToolAllowActuators && i == 5)
                {
                    continue;
                }
                bool flag2 = Settings.ToolMode.HasFlag((Settings.MultiToolMode)(1 << i));
                if (i == 5)
                {
                    flag2 = Settings.ToolMode.HasFlag(Settings.MultiToolMode.Actuator);
                }
                Vector2 vector4 = vector2 + Vector2.UnitX * (45f * ((float)i - 1.5f));
                int num = i;
                if (i == 0)
                {
                    num = 3;
                }
                if (i == 3)
                {
                    num = 0;
                }
                switch (num)
                {
                case 0:
                case 1:
                    vector4 = vector2 + new Vector2((45f + (float)(drawToolAllowActuators ? 15 : 0)) * (float)(2 - num), 0f) * _lineOpacity;
                    break;
                case 2:
                case 3:
                    vector4 = vector2 + new Vector2((0f - (45f + (float)(drawToolAllowActuators ? 15 : 0))) * (float)(num - 1), 0f) * _lineOpacity;
                    break;
                case 5:
                    vector4 = vector2 + new Vector2(0f, 22f) * _lineOpacity;
                    break;
                case 4:
                    flag2 = false;
                    vector4 = vector2 - new Vector2(0f, drawToolAllowActuators ? 22f : 0f) * _lineOpacity;
                    break;
                }
                bool flag3 = false;
                if (!PlayerInput.UsingGamepad)
                {
                    flag3 = Vector2.Distance(vector4, vector) < 19f * _lineOpacity;
                }
                if (flag)
                {
                    flag3 = false;
                }
                if (flag3)
                {
                    flag = true;
                }
                Texture2D value = TextureAssets.WireUi[(Settings.ToolMode.HasFlag(Settings.MultiToolMode.Cutter) ? 8 : 0) + (flag3 ? 1 : 0)].Value;
                Texture2D texture2D = null;
                switch (i)
                {
                case 0:
                case 1:
                case 2:
                case 3:
                    texture2D = TextureAssets.WireUi[2 + i].Value;
                    break;
                case 4:
                    texture2D = TextureAssets.WireUi[Settings.ToolMode.HasFlag(Settings.MultiToolMode.Cutter) ? 7 : 6].Value;
                    break;
                case 5:
                    texture2D = TextureAssets.WireUi[10].Value;
                    break;
                }
                Color color = Color.White;
                Color color2 = Color.White;
                if (!flag2 && i != 4)
                {
                    if (flag3)
                    {
                        color2 = new Color(100, 100, 100);
                        color2 = new Color(120, 120, 120);
                        color = new Color(200, 200, 200);
                    }
                    else
                    {
                        color2 = new Color(150, 150, 150);
                        color2 = new Color(80, 80, 80);
                        color = new Color(100, 100, 100);
                    }
                }
                Utils.CenteredRectangle(vector4, new Vector2(40f));
                if (flag3)
                {
                    if (Main.mouseLeft && Main.mouseLeftRelease)
                    {
                        switch (i)
{
                        case 0:
                            Settings.ToolMode ^= Settings.MultiToolMode.Red;
                            break;
                        case 1:
                            Settings.ToolMode ^= Settings.MultiToolMode.Green;
                            break;
                        case 2:
                            Settings.ToolMode ^= Settings.MultiToolMode.Blue;
                            break;
                        case 3:
                            Settings.ToolMode ^= Settings.MultiToolMode.Yellow;
                            break;
                        case 4:
                            Settings.ToolMode ^= Settings.MultiToolMode.Cutter;
                            break;
                        case 5:
                            Settings.ToolMode ^= Settings.MultiToolMode.Actuator;
                            break;
                        }
                    }
                    if (!Main.mouseLeft || Main.player[Main.myPlayer].mouseInterface)
                    {
                        Main.player[Main.myPlayer].mouseInterface = true;
                    }
                    OnWiresMenu = true;
                }
                spriteBatch.Draw(value, vector4, null, color * _lineOpacity, 0f, value.Size() / 2f, _lineOpacity, SpriteEffects.None, 0f);
                spriteBatch.Draw(texture2D, vector4, null, color2 * _lineOpacity, 0f, texture2D.Size() / 2f, _lineOpacity, SpriteEffects.None, 0f);
            }
            if (Main.mouseLeft && Main.mouseLeftRelease && !flag)
            {
                active = false;
            }
        }
References Terraria.GameContent.UI.WiresUI.WiresRadial._lineOpacity, Terraria.GameContent.UI.WiresUI.WiresRadial.active, Terraria.Utils.CenteredRectangle(), Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Vector2.Dot(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.UI.WiresUI.Settings.DrawToolAllowActuators, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseScreen, Terraria.Main.myPlayer, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.GameContent.UI.WiresUI.WiresRadial.OnWiresMenu, Terraria.Main.player, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.GameInput.PlayerInput.UsingGamepad, System.value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.GameContent.TextureAssets.WireUi, and Microsoft.Xna.Framework.Vector2.Zero.