Terraria: Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.PopulateEntries
PopulateEntries()
void Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.PopulateEntries () inline private
Definition at line 134 of file UIWorkshopSelectWorldToPublish.cs.
    {
        Main.LoadWorlds();
        _entryList.Clear();
        IOrderedEnumerable<WorldFileData> orderedEnumerable = from x in new List<WorldFileData>(Main.WorldList)
            orderby x.IsFavorite descending, x.Name, x.GetFileName()
            select x;
        _entryList.Clear();
        int num = 0;
        foreach (WorldFileData item in orderedEnumerable)
        {
            _entryList.Add(new UIWorkshopPublishWorldListItem(this, item, num++));
        }
    }
References Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish._entryList, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.Main.LoadWorlds(), and Terraria.Main.WorldList.
Referenced by Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.OnActivate().