Terraria: Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.OnInitialize
OnInitialize()
override void Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 37 of file UIWorkshopSelectWorldToPublish.cs.
    {
        UIElement uIElement = new UIElement();
        uIElement.Width.Set(0f, 0.8f);
        uIElement.MaxWidth.Set(650f, 0f);
        uIElement.Top.Set(220f, 0f);
        uIElement.Height.Set(-220f, 1f);
        uIElement.HAlign = 0.5f;
        UIPanel uIPanel = new UIPanel();
        uIPanel.Width.Set(0f, 1f);
        uIPanel.Height.Set(-110f, 1f);
        uIPanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
        uIElement.Append(uIPanel);
        _containerPanel = uIPanel;
        _entryList = new UIList();
        _entryList.Width.Set(0f, 1f);
        _entryList.Height.Set(0f, 1f);
        _entryList.ListPadding = 5f;
        uIPanel.Append(_entryList);
        _scrollbar = new UIScrollbar();
        _scrollbar.SetView(100f, 1000f);
        _scrollbar.Height.Set(0f, 1f);
        _scrollbar.HAlign = 1f;
        _entryList.SetScrollbar(_scrollbar);
        UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.WorkshopSelectWorldToPublishMenuTitle"), 0.8f, large: true);
        uITextPanel.HAlign = 0.5f;
        uITextPanel.Top.Set(-40f, 0f);
        uITextPanel.SetPadding(15f);
        uITextPanel.BackgroundColor = new Color(73, 94, 171);
        uIElement.Append(uITextPanel);
        UITextPanel<LocalizedText> uITextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true);
        uITextPanel2.Width.Set(-10f, 0.5f);
        uITextPanel2.Height.Set(50f, 0f);
        uITextPanel2.VAlign = 1f;
        uITextPanel2.HAlign = 0.5f;
        uITextPanel2.Top.Set(-45f, 0f);
        uITextPanel2.OnMouseOver += FadedMouseOver;
        uITextPanel2.OnMouseOut += FadedMouseOut;
        uITextPanel2.OnLeftClick += GoBackClick;
        uIElement.Append(uITextPanel2);
        _backPanel = uITextPanel2;
        Append(uIElement);
    }
References Terraria.UI.UIElement.UIElement(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish._backPanel, Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish._containerPanel, Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish._entryList, Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish._scrollbar, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.FadedMouseOver(), Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.GoBackClick(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.MaxWidth, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.UI.UIElement.Top, and Terraria.UI.UIElement.Width.