Terraria: Terraria.GameContent.UI.WiresUI.WiresRadial.DrawCursorArea
DrawCursorArea()
void Terraria.GameContent.UI.WiresUI.WiresRadial.DrawCursorArea (SpriteBatch spriteBatch) inline private
Definition at line 493 of file WiresUI.cs.
        {
            if (active || _lineOpacity == 0f)
            {
                return;
            }
            Vector2 vector = Main.MouseScreen + new Vector2(10 - 9 * PlayerInput.UsingGamepad.ToInt(), 25f);
            Color color = new Color(50, 50, 50);
            bool drawToolAllowActuators = Settings.DrawToolAllowActuators;
            if (!drawToolAllowActuators)
            {
                if (!PlayerInput.UsingGamepad)
                {
                    vector += new Vector2(-20f, 10f);
                }
                else
                {
                    vector += new Vector2(0f, 10f);
                }
            }
            Texture2D value = TextureAssets.BuilderAcc.Value;
            Texture2D texture = value;
            Rectangle rectangle = new Rectangle(140, 2, 6, 6);
            Rectangle rectangle2 = new Rectangle(148, 2, 6, 6);
            Rectangle rectangle3 = new Rectangle(128, 0, 10, 10);
            float num = 1f;
            float scale = 1f;
            bool flag = false;
            if (flag && !drawToolAllowActuators)
            {
                num *= Main.cursorScale;
            }
            float num2 = _lineOpacity;
            if (PlayerInput.UsingGamepad)
            {
                num2 *= Main.GamepadCursorAlpha;
            }
            for (int i = 0; i < 5; i++)
            {
                if (!drawToolAllowActuators && i == 4)
                {
                    continue;
                }
                float num3 = num2;
                Vector2 vec = vector + Vector2.UnitX * (45f * ((float)i - 1.5f));
                int num4 = i;
                if (i == 0)
                {
                    num4 = 3;
                }
                if (i == 1)
                {
                    num4 = 2;
                }
                if (i == 2)
                {
                    num4 = 1;
                }
                if (i == 3)
                {
                    num4 = 0;
                }
                if (i == 4)
                {
                    num4 = 5;
                }
                int num5 = num4;
                switch (num5)
                {
                case 2:
                    num5 = 1;
                    break;
                case 1:
                    num5 = 2;
                    break;
                }
                bool flag2 = Settings.ToolMode.HasFlag((Settings.MultiToolMode)(1 << num5));
                if (num5 == 5)
                {
                    flag2 = Settings.ToolMode.HasFlag(Settings.MultiToolMode.Actuator);
                }
                Color color2 = Color.HotPink;
                switch (num4)
                {
                case 0:
                    color2 = new Color(253, 58, 61);
                    break;
                case 1:
                    color2 = new Color(83, 180, 253);
                    break;
                case 2:
                    color2 = new Color(83, 253, 153);
                    break;
                case 3:
                    color2 = new Color(253, 254, 83);
                    break;
                case 5:
                    color2 = Color.WhiteSmoke;
                    break;
                }
                if (!flag2)
                {
                    color2 = Color.Lerp(color2, Color.Black, 0.65f);
                }
                if (flag)
                {
                    if (drawToolAllowActuators)
                    {
                        switch (num4)
{
                        case 0:
                            vec = vector + new Vector2(-12f, 0f) * num;
                            break;
                        case 3:
                            vec = vector + new Vector2(12f, 0f) * num;
                            break;
                        case 1:
                            vec = vector + new Vector2(-6f, 12f) * num;
                            break;
                        case 2:
                            vec = vector + new Vector2(6f, 12f) * num;
                            break;
                        case 5:
                            vec = vector + new Vector2(0f, 0f) * num;
                            break;
                        }
                    }
                    else
                    {
                        vec = vector + new Vector2(12 * (num4 + 1), 12 * (3 - num4)) * num;
                    }
                }
                else if (drawToolAllowActuators)
                {
                    switch (num4)
                    {
                    case 0:
                        vec = vector + new Vector2(-12f, 0f) * num;
                        break;
                    case 3:
                        vec = vector + new Vector2(12f, 0f) * num;
                        break;
                    case 1:
                        vec = vector + new Vector2(-6f, 12f) * num;
                        break;
                    case 2:
                        vec = vector + new Vector2(6f, 12f) * num;
                        break;
                    case 5:
                        vec = vector + new Vector2(0f, 0f) * num;
                        break;
                    }
                }
                else
                {
                    float num6 = 0.7f;
                    switch (num4)
                    {
                    case 0:
                        vec = vector + new Vector2(0f, -12f) * num * num6;
                        break;
                    case 3:
                        vec = vector + new Vector2(12f, 0f) * num * num6;
                        break;
                    case 1:
                        vec = vector + new Vector2(-12f, 0f) * num * num6;
                        break;
                    case 2:
                        vec = vector + new Vector2(0f, 12f) * num * num6;
                        break;
                    }
                }
                vec = vec.Floor();
                spriteBatch.Draw(texture, vec, rectangle3, color * num3, 0f, rectangle3.Size() / 2f, scale, SpriteEffects.None, 0f);
                spriteBatch.Draw(value, vec, rectangle, color2 * num3, 0f, rectangle.Size() / 2f, scale, SpriteEffects.None, 0f);
                if (Settings.ToolMode.HasFlag(Settings.MultiToolMode.Cutter))
                {
                    spriteBatch.Draw(value, vec, rectangle2, color * num3, 0f, rectangle2.Size() / 2f, scale, SpriteEffects.None, 0f);
                }
            }
        }
References Terraria.GameContent.UI.WiresUI.WiresRadial._lineOpacity, Terraria.GameContent.UI.WiresUI.WiresRadial.active, Microsoft.Xna.Framework.Color.Black, Terraria.GameContent.TextureAssets.BuilderAcc, Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.cursorScale, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.UI.WiresUI.Settings.DrawToolAllowActuators, Terraria.Main.GamepadCursorAlpha, Microsoft.Xna.Framework.Color.HotPink, Microsoft.Xna.Framework.Color.Lerp(), Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Terraria.GameInput.PlayerInput.UsingGamepad, System.value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.WhiteSmoke.
Referenced by Terraria.GameContent.UI.WiresUI.WiresRadial.Draw().