Terraria: Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 160 of file UIWorkshopSelectWorldToPublish.cs.
    {
        UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
        int num = 3000;
        UILinkPointNavigator.SetPosition(num, _backPanel.GetInnerDimensions().ToRectangle().Center.ToVector2());
        int num2 = num;
        UILinkPoint uILinkPoint = UILinkPointNavigator.Points[num2];
        uILinkPoint.Unlink();
        uILinkPoint.Right = num2;
        float num3 = 1f / Main.UIScale;
        Rectangle clippingRectangle = _containerPanel.GetClippingRectangle(spriteBatch);
        Vector2 minimum = clippingRectangle.TopLeft() * num3;
        Vector2 maximum = clippingRectangle.BottomRight() * num3;
        List<SnapPoint> snapPoints = GetSnapPoints();
        for (int i = 0; i < snapPoints.Count; i++)
        {
            if (!snapPoints[i].Position.Between(minimum, maximum))
            {
                snapPoints.Remove(snapPoints[i]);
                i--;
            }
        }
        int num4 = 1;
        SnapPoint[,] array = new SnapPoint[_entryList.Count, num4];
        foreach (SnapPoint item in snapPoints.Where((SnapPoint a) => a.Name == "Publish"))
        {
            array[item.Id, 0] = item;
        }
        num2 = num + 1;
        int[] array2 = new int[_entryList.Count];
        for (int j = 0; j < array2.Length; j++)
        {
            array2[j] = -1;
        }
        for (int k = 0; k < num4; k++)
        {
            int num5 = -1;
            for (int l = 0; l < array.GetLength(0); l++)
            {
                if (array[l, k] != null)
                {
                    uILinkPoint = UILinkPointNavigator.Points[num2];
                    uILinkPoint.Unlink();
                    UILinkPointNavigator.SetPosition(num2, array[l, k].Position);
                    if (num5 != -1)
                    {
                        uILinkPoint.Up = num5;
                        UILinkPointNavigator.Points[num5].Down = num2;
                    }
                    if (array2[l] != -1)
                    {
                        uILinkPoint.Left = array2[l];
                        UILinkPointNavigator.Points[array2[l]].Right = num2;
                    }
                    uILinkPoint.Down = num;
                    if (k == 0)
                    {
                        UILinkPointNavigator.Points[num].Up = (UILinkPointNavigator.Points[num + 1].Up = num2);
                    }
                    num5 = num2;
                    array2[l] = num2;
                    UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = num2;
                    num2++;
                }
            }
        }
        if (PlayerInput.UsingGamepadUI && _entryList.Count == 0 && UILinkPointNavigator.CurrentPoint > 3000)
        {
            UILinkPointNavigator.ChangePoint(3000);
        }
    }
References Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish._backPanel, Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish._containerPanel, Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish._entryList, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.GameContent.UI.Elements.UIList.Count, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.UI.UIElement.GetClippingRectangle(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.UI.Gamepad.UILinkPointNavigator.Points, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.UIScale, and Terraria.GameInput.PlayerInput.UsingGamepadUI.
Referenced by Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.Draw().