Terraria: Terraria.Graphics.Shaders.MiscShaderData.UseOpacity
UseOpacity()
MiscShaderData Terraria.Graphics.Shaders.MiscShaderData.UseOpacity (float alpha) inline
Definition at line 132 of file MiscShaderData.cs.
    {
        _uOpacity = alpha;
        return this;
    }
References Terraria.Graphics.Shaders.MiscShaderData._uOpacity.
Referenced by Terraria.Graphics.FlameLashDrawer.Draw(), Terraria.Graphics.LightDiscDrawer.Draw(), Terraria.Graphics.MagicMissileDrawer.Draw(), Terraria.Graphics.RainbowRodDrawer.Draw(), and Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.UpdateSettingsForRendering().