Terraria: System.Diagnostics.Tracing.ScalarTypeInfo.UIntPtr
UIntPtr()
static TraceLoggingTypeInfo System.Diagnostics.Tracing.ScalarTypeInfo.UIntPtr () inline static
Definition at line 108 of file ScalarTypeInfo.cs.
    {
        return s_uintptr ?? (s_uintptr = new ScalarTypeInfo(typeof(UIntPtr), Statics.UIntPtrType));
    }
References System.Diagnostics.Tracing.ScalarTypeInfo.ScalarTypeInfo(), System.Diagnostics.Tracing.ScalarTypeInfo.s_uintptr, and System.Diagnostics.Tracing.Statics.UIntPtrType.
Referenced by System.Diagnostics.Tracing.Statics.CreateDefaultTypeInfo(), and System.Diagnostics.Tracing.EventParameterInfo.GetTypeInfoFromType().