Terraria: System.Diagnostics.Tracing.ScalarTypeInfo.Boolean
Boolean()
static TraceLoggingTypeInfo System.Diagnostics.Tracing.ScalarTypeInfo.Boolean () inline static
Definition at line 53 of file ScalarTypeInfo.cs.
    {
        return s_boolean ?? (s_boolean = new ScalarTypeInfo(typeof(bool), TraceLoggingDataType.Boolean8));
    }
References System.Diagnostics.Tracing.ScalarTypeInfo.ScalarTypeInfo(), and System.Diagnostics.Tracing.ScalarTypeInfo.s_boolean.
Referenced by System.Diagnostics.Tracing.Statics.CreateDefaultTypeInfo(), and System.Diagnostics.Tracing.EventParameterInfo.GetTypeInfoFromType().