Terraria: System.Xml.Xsl.Xslt.XPathPatternParser.Parse
Parse()
QilNode System.Xml.Xsl.Xslt.XPathPatternParser.Parse (XPathScanner scanner, IPatternBuilder ptrnBuilder) inline
Definition at line 23 of file XPathPatternParser.cs.
    {
        QilNode result = null;
        ptrnBuilder.StartBuild();
        try
        {
            _scanner = scanner;
            _ptrnBuilder = ptrnBuilder;
            result = ParsePattern();
            _scanner.CheckToken(LexKind.Eof);
        }
        finally
        {
            result = ptrnBuilder.EndBuild(result);
        }
        return result;
    }
References System.Xml.Xsl.Xslt.XPathPatternParser._ptrnBuilder, System.Xml.Xsl.Xslt.XPathPatternParser._scanner, System.Xml.Xsl.XPath.XPathScanner.CheckToken(), System.Xml.Dictionary, and System.Xml.Xsl.Xslt.XPathPatternParser.ParsePattern().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileKeyMatch(), System.Xml.Xsl.Xslt.QilGenerator.CompileMatchPattern(), and System.Xml.Xsl.Xslt.QilGenerator.CompileNumberPattern().