Terraria: System.Xml.Xsl.Xslt.XPathPatternParser.ParsePattern
ParsePattern()
QilNode System.Xml.Xsl.Xslt.XPathPatternParser.ParsePattern () inline private
Definition at line 41 of file XPathPatternParser.cs.
    {
        QilNode qilNode = ParseLocationPathPattern();
        while (_scanner.Kind == LexKind.Union)
        {
            _scanner.NextLex();
            qilNode = _ptrnBuilder.Operator(XPathOperator.Union, qilNode, ParseLocationPathPattern());
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.XPathPatternParser._ptrnBuilder, System.Xml.Xsl.Xslt.XPathPatternParser._scanner, System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathScanner.Kind, System.Xml.Xsl.XPath.XPathScanner.NextLex(), System.Xml.Xsl.XPath.IXPathBuilder< Node >.Operator(), and System.Xml.Xsl.Xslt.XPathPatternParser.ParseLocationPathPattern().
Referenced by System.Xml.Xsl.Xslt.XPathPatternParser.Parse().