Terraria: System.Xml.Xsl.Xslt.XPathPatternParser.ParsePredicate
ParsePredicate()
QilNode System.Xml.Xsl.Xslt.XPathPatternParser.ParsePredicate (QilNode context) inline private
Definition at line 190 of file XPathPatternParser.cs.
    {
        _scanner.NextLex();
        QilNode result = _predicateParser.Parse(_scanner, _ptrnBuilder.GetPredicateBuilder(context), LexKind.RBracket);
        _scanner.NextLex();
        return result;
    }
References System.Xml.Xsl.Xslt.XPathPatternParser._predicateParser, System.Xml.Xsl.Xslt.XPathPatternParser._ptrnBuilder, System.Xml.Xsl.Xslt.XPathPatternParser._scanner, System.Xml.Xsl.Xslt.XPathPatternParser.IPatternBuilder.GetPredicateBuilder(), System.Xml.Xsl.XPath.XPathScanner.NextLex(), and System.Xml.Xsl.XPath.XPathParser< Node >.Parse().
Referenced by System.Xml.Xsl.Xslt.XPathPatternParser.ParseStepPattern().