Terraria: System.Xml.Xsl.Xslt.XPathPatternParser.ParseRelativePathPattern
ParseRelativePathPattern()
QilNode System.Xml.Xsl.Xslt.XPathPatternParser.ParseRelativePathPattern () inline private
Definition at line 117 of file XPathPatternParser.cs.
    {
        if (++_parseRelativePath > 1024 && System.LocalAppContextSwitches.LimitXPathComplexity)
        {
            throw _scanner.CreateException(System.SR.Xslt_InputTooComplex);
        }
        QilNode qilNode = ParseStepPattern();
        if (_scanner.Kind == LexKind.Slash)
        {
            _scanner.NextLex();
            qilNode = _ptrnBuilder.JoinStep(qilNode, ParseRelativePathPattern());
        }
        else if (_scanner.Kind == LexKind.SlashSlash)
        {
            _scanner.NextLex();
            qilNode = _ptrnBuilder.JoinStep(qilNode, _ptrnBuilder.JoinStep(_ptrnBuilder.Axis(XPathAxis.DescendantOrSelf, XPathNodeType.All, null, null), ParseRelativePathPattern()));
        }
        _parseRelativePath--;
        return qilNode;
    }
References System.Xml.Xsl.Xslt.XPathPatternParser._parseRelativePath, System.Xml.Xsl.Xslt.XPathPatternParser._ptrnBuilder, System.Xml.Xsl.Xslt.XPathPatternParser._scanner, System.Xml.Xsl.XPath.IXPathBuilder< Node >.Axis(), System.Xml.Xsl.XPath.XPathScanner.CreateException(), System.Xml.Dictionary, System.Xml.Xsl.XPath.IXPathBuilder< Node >.JoinStep(), System.Xml.Xsl.XPath.XPathScanner.Kind, System.LocalAppContextSwitches.LimitXPathComplexity, System.Xml.Xsl.XPath.XPathScanner.NextLex(), System.Xml.Xsl.Xslt.XPathPatternParser.ParseRelativePathPattern(), System.Xml.Xsl.Xslt.XPathPatternParser.ParseStepPattern(), and System.SR.Xslt_InputTooComplex.
Referenced by System.Xml.Xsl.Xslt.XPathPatternParser.ParseLocationPathPattern(), and System.Xml.Xsl.Xslt.XPathPatternParser.ParseRelativePathPattern().