Terraria: System.Xml.Xsl.Xslt.XPathPatternParser.ParseLocationPathPattern
ParseLocationPathPattern()
QilNode System.Xml.Xsl.Xslt.XPathPatternParser.ParseLocationPathPattern () inline private
Definition at line 52 of file XPathPatternParser.cs.
    {
        switch (_scanner.Kind)
        {
        case LexKind.Slash:
        {
            _scanner.NextLex();
            QilNode qilNode = _ptrnBuilder.Axis(XPathAxis.Root, XPathNodeType.All, null, null);
            if (XPathParser<QilNode>.IsStep(_scanner.Kind))
            {
                qilNode = _ptrnBuilder.JoinStep(qilNode, ParseRelativePathPattern());
            }
            return qilNode;
        }
        case LexKind.SlashSlash:
            _scanner.NextLex();
            return _ptrnBuilder.JoinStep(_ptrnBuilder.Axis(XPathAxis.Root, XPathNodeType.All, null, null), _ptrnBuilder.JoinStep(_ptrnBuilder.Axis(XPathAxis.DescendantOrSelf, XPathNodeType.All, null, null), ParseRelativePathPattern()));
        case LexKind.Name:
            if (_scanner.CanBeFunction && _scanner.Prefix.Length == 0 && (_scanner.Name == "id" || _scanner.Name == "key"))
            {
                QilNode qilNode = ParseIdKeyPattern();
                switch (_scanner.Kind)
                {
                case LexKind.Slash:
                    _scanner.NextLex();
                    qilNode = _ptrnBuilder.JoinStep(qilNode, ParseRelativePathPattern());
                    break;
                case LexKind.SlashSlash:
                    _scanner.NextLex();
                    qilNode = _ptrnBuilder.JoinStep(qilNode, _ptrnBuilder.JoinStep(_ptrnBuilder.Axis(XPathAxis.DescendantOrSelf, XPathNodeType.All, null, null), ParseRelativePathPattern()));
                    break;
                }
                return qilNode;
            }
            break;
        }
        return ParseRelativePathPattern();
    }
References System.Xml.Xsl.Xslt.XPathPatternParser._ptrnBuilder, System.Xml.Xsl.Xslt.XPathPatternParser._scanner, System.Xml.Xsl.XPath.IXPathBuilder< Node >.Axis(), System.Xml.Xsl.XPath.XPathScanner.CanBeFunction, System.Xml.Dictionary, System.Xml.Xsl.XPath.IXPathBuilder< Node >.JoinStep(), System.Xml.Xsl.XPath.XPathScanner.Kind, System.Xml.Xsl.XPath.XPathScanner.Name, System.Xml.Xsl.XPath.XPathScanner.NextLex(), System.Xml.Xsl.Xslt.XPathPatternParser.ParseIdKeyPattern(), System.Xml.Xsl.Xslt.XPathPatternParser.ParseRelativePathPattern(), and System.Xml.Xsl.XPath.XPathScanner.Prefix.
Referenced by System.Xml.Xsl.Xslt.XPathPatternParser.ParsePattern().