Terraria: System.Xml.Xsl.Xslt.XPathPatternParser.ParseIdKeyPattern
ParseIdKeyPattern()
QilNode System.Xml.Xsl.Xslt.XPathPatternParser.ParseIdKeyPattern () inline private
Definition at line 91 of file XPathPatternParser.cs.
    {
        List<QilNode> list = new List<QilNode>(2);
        if (_scanner.Name == "id")
        {
            _scanner.NextLex();
            _scanner.PassToken(LexKind.LParens);
            _scanner.CheckToken(LexKind.String);
            list.Add(_ptrnBuilder.String(_scanner.StringValue));
            _scanner.NextLex();
            _scanner.PassToken(LexKind.RParens);
            return _ptrnBuilder.Function("", "id", list);
        }
        _scanner.NextLex();
        _scanner.PassToken(LexKind.LParens);
        _scanner.CheckToken(LexKind.String);
        list.Add(_ptrnBuilder.String(_scanner.StringValue));
        _scanner.NextLex();
        _scanner.PassToken(LexKind.Comma);
        _scanner.CheckToken(LexKind.String);
        list.Add(_ptrnBuilder.String(_scanner.StringValue));
        _scanner.NextLex();
        _scanner.PassToken(LexKind.RParens);
        return _ptrnBuilder.Function("", "key", list);
    }
References System.Xml.Xsl.Xslt.XPathPatternParser._ptrnBuilder, System.Xml.Xsl.Xslt.XPathPatternParser._scanner, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.XPath.XPathScanner.CheckToken(), System.Xml.Dictionary, System.Xml.Xsl.XPath.IXPathBuilder< Node >.Function(), System.list, System.Xml.Xsl.XPath.XPathScanner.Name, System.Xml.Xsl.XPath.XPathScanner.NextLex(), System.Xml.Xsl.XPath.XPathScanner.PassToken(), System.Xml.Xsl.XPath.IXPathBuilder< Node >.String(), and System.Xml.Xsl.XPath.XPathScanner.StringValue.
Referenced by System.Xml.Xsl.Xslt.XPathPatternParser.ParseLocationPathPattern().