Terraria: System.Data.UniqueConstraint.IsConstraintViolated
IsConstraintViolated()
override bool System.Data.UniqueConstraint.IsConstraintViolated () inline package
Definition at line 189 of file UniqueConstraint.cs.
    {
        bool result = false;
        Index constraintIndex = ConstraintIndex;
        if (constraintIndex.HasDuplicates)
        {
            object[] uniqueKeyValues = constraintIndex.GetUniqueKeyValues();
            for (int i = 0; i < uniqueKeyValues.Length; i++)
            {
                Range range = constraintIndex.FindRecords((object[])uniqueKeyValues[i]);
                if (1 >= range.Count)
                {
                    continue;
                }
                DataRow[] rows = constraintIndex.GetRows(range);
                string text = ExceptionBuilder.UniqueConstraintViolationText(_key.ColumnsReference, (object[])uniqueKeyValues[i]);
                for (int j = 0; j < rows.Length; j++)
                {
                    rows[j].RowError = text;
                    DataColumn[] columnsReference = _key.ColumnsReference;
                    foreach (DataColumn column in columnsReference)
                    {
                        rows[j].SetColumnError(column, text);
                    }
                }
                result = true;
            }
        }
        return result;
    }
References System.Data.UniqueConstraint._key, System.Data.DataKey.ColumnsReference, System.Data.UniqueConstraint.ConstraintIndex, System.Data.Range.Count, System.Data.Index.FindRecords(), System.Data.Index.GetRows(), System.Data.Index.GetUniqueKeyValues(), System.Data.Index.HasDuplicates, System.Data.DataRow.RowError, System.Data.DataRow.SetColumnError(), System.text, and System.Data.ExceptionBuilder.UniqueConstraintViolationText().