Terraria: System.Data.UniqueConstraint.CanBeRemovedFromCollection
CanBeRemovedFromCollection()
override bool System.Data.UniqueConstraint.CanBeRemovedFromCollection (ConstraintCollection constraints, bool fThrowException) inline package
Definition at line 154 of file UniqueConstraint.cs.
    {
        if (Equals(constraints.Table._primaryKey))
        {
            if (!fThrowException)
            {
                return false;
            }
            throw ExceptionBuilder.RemovePrimaryKey(constraints.Table);
        }
        ParentForeignKeyConstraintEnumerator parentForeignKeyConstraintEnumerator = new ParentForeignKeyConstraintEnumerator(Table.DataSet, Table);
        while (parentForeignKeyConstraintEnumerator.GetNext())
        {
            ForeignKeyConstraint foreignKeyConstraint = parentForeignKeyConstraintEnumerator.GetForeignKeyConstraint();
            if (_key.ColumnsEqual(foreignKeyConstraint.ParentKey))
            {
                if (!fThrowException)
                {
                    return false;
                }
                throw ExceptionBuilder.NeededForForeignKeyConstraint(this, foreignKeyConstraint);
            }
        }
        return true;
    }
References System.Data.UniqueConstraint._key, System.Data.DataTable._primaryKey, System.Data.DataKey.ColumnsEqual(), System.Data.DataTable.DataSet, System.Data.UniqueConstraint.Equals(), System.Data.ForeignKeyConstraintEnumerator.GetForeignKeyConstraint(), System.Data.ConstraintEnumerator.GetNext(), System.Data.ExceptionBuilder.NeededForForeignKeyConstraint(), System.Data.ForeignKeyConstraint.ParentKey, System.Data.ExceptionBuilder.RemovePrimaryKey(), System.Data.ConstraintCollection.Table, and System.Data.UniqueConstraint.Table.