Terraria: System.Data.UniqueConstraint.Create
Create()
void System.Data.UniqueConstraint.Create (string constraintName, DataColumn[] columns) inline private
Definition at line 305 of file UniqueConstraint.cs.
    {
        for (int i = 0; i < columns.Length; i++)
        {
            if (columns[i].Computed)
            {
                throw ExceptionBuilder.ExpressionInConstraint(columns[i]);
            }
        }
        _key = new DataKey(columns, copyColumns: true);
        ConstraintName = constraintName;
        NonVirtualCheckState();
    }
References System.Data.UniqueConstraint._key, System.Data.Constraint.ConstraintName, System.Data.ExceptionBuilder.ExpressionInConstraint(), and System.Data.UniqueConstraint.NonVirtualCheckState().
Referenced by System.Data.UniqueConstraint.UniqueConstraint(), System.Data.UniqueConstraint.UniqueConstraint(), System.Data.UniqueConstraint.UniqueConstraint(), System.Data.UniqueConstraint.UniqueConstraint(), System.Data.UniqueConstraint.UniqueConstraint(), System.Data.UniqueConstraint.UniqueConstraint(), System.Data.UniqueConstraint.UniqueConstraint(), and System.Data.UniqueConstraint.UniqueConstraint().