Terraria: System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem
CreateFromPem() [2/2]
static X509Certificate2 System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem (ReadOnlySpan< char > certPem, ReadOnlySpan< char > keyPem) inline static
Definition at line 661 of file X509Certificate2.cs.
    {
        using X509Certificate2 x509Certificate = CreateFromPem(certPem);
        string keyAlgorithm = x509Certificate.GetKeyAlgorithm();
        switch (keyAlgorithm)
        {
        case "1.2.840.113549.1.1.1":
            return ExtractKeyFromPem(keyPem, s_RsaPublicKeyPrivateKeyLabels, RSA.Create, x509Certificate.CopyWithPrivateKey);
        case "1.2.840.10040.4.1":
            if (Internal.Cryptography.Helpers.IsDSASupported)
            {
                return ExtractKeyFromPem(keyPem, s_DsaPublicKeyPrivateKeyLabels, DSA.Create, x509Certificate.CopyWithPrivateKey);
            }
            break;
        case "1.2.840.10045.2.1":
            if (IsECDsa(x509Certificate))
            {
                return ExtractKeyFromPem(keyPem, s_EcPublicKeyPrivateKeyLabels, ECDsa.Create, x509Certificate.CopyWithPrivateKey);
            }
            if (IsECDiffieHellman(x509Certificate))
            {
                return ExtractKeyFromPem(keyPem, s_EcPublicKeyPrivateKeyLabels, ECDiffieHellman.Create, x509Certificate.CopyWithPrivateKey);
            }
            break;
        }
        throw new CryptographicException(System.SR.Format(System.SR.Cryptography_UnknownKeyAlgorithm, keyAlgorithm));
    }
References System.Security.Cryptography.DSA.Create(), System.Security.Cryptography.RSA.Create(), System.Security.Cryptography.ECDiffieHellman.Create(), System.Security.Cryptography.ECDsa.Create(), System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem(), System.SR.Cryptography_UnknownKeyAlgorithm, System.Runtime.Serialization.Dictionary, System.SR.Format(), Internal.Cryptography.Helpers.IsDSASupported, System.Security.Cryptography.X509Certificates.X509Certificate2.IsECDiffieHellman(), System.Security.Cryptography.X509Certificates.X509Certificate2.IsECDsa(), System.Security.Cryptography.X509Certificates.X509Certificate2.s_DsaPublicKeyPrivateKeyLabels, System.Security.Cryptography.X509Certificates.X509Certificate2.s_EcPublicKeyPrivateKeyLabels, and System.Security.Cryptography.X509Certificates.X509Certificate2.s_RsaPublicKeyPrivateKeyLabels.
Referenced by System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromEncryptedPem(), System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem(), and System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPemFile().