Terraria: System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem
CreateFromPem() [1/2]
static X509Certificate2 System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem (ReadOnlySpan< char > certPem) inline static
Definition at line 729 of file X509Certificate2.cs.
    {
        PemEnumerator.Enumerator enumerator = new PemEnumerator(certPem).GetEnumerator();
        while (enumerator.MoveNext())
        {
            enumerator.Current.Deconstruct(out var contents, out var pemFields);
            ReadOnlySpan<char> readOnlySpan = contents;
            PemFields pemFields2 = pemFields;
            contents = readOnlySpan;
            ReadOnlySpan<char> span = contents[pemFields2.Label];
            if (span.SequenceEqual("CERTIFICATE"))
            {
                byte[] array = System.Security.Cryptography.CryptoPool.Rent(pemFields2.DecodedDataLength);
                contents = readOnlySpan;
                if (!Convert.TryFromBase64Chars(contents[pemFields2.Base64Data], array, out var bytesWritten) || bytesWritten != pemFields2.DecodedDataLength)
                {
                    throw new CryptographicException(System.SR.Cryptography_X509_NoPemCertificate);
                }
                ReadOnlyMemory<byte> encoded = new ReadOnlyMemory<byte>(array, 0, bytesWritten);
                try
                {
                    CertificateAsn.Decode(encoded, AsnEncodingRules.DER);
                }
                catch (CryptographicException)
                {
                    throw new CryptographicException(System.SR.Cryptography_X509_NoPemCertificate);
                }
                X509Certificate2 result = new X509Certificate2(encoded.Span);
                System.Security.Cryptography.CryptoPool.Return(array, 0);
                return result;
            }
        }
        throw new CryptographicException(System.SR.Cryptography_X509_NoPemCertificate);
    }
References System.Security.Cryptography.X509Certificates.X509Certificate2.X509Certificate2(), System.array, System.SR.Cryptography_X509_NoPemCertificate, Internal.Cryptography.PemEnumerator.Enumerator.Current, System.Security.Cryptography.X509Certificates.Asn1.CertificateAsn.Decode(), Internal.Cryptography.PemEnumerator.Enumerator.PemFieldItem.Deconstruct(), System.Runtime.Serialization.Dictionary, Internal.Cryptography.PemEnumerator.GetEnumerator(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), and System.Convert.TryFromBase64Chars().