Terraria: System.Security.Cryptography.X509Certificates.X509Certificate2.CopyWithPrivateKey
CopyWithPrivateKey()
X509Certificate2 System.Security.Cryptography.X509Certificates.X509Certificate2.CopyWithPrivateKey (ECDiffieHellman privateKey) inline
Definition at line 614 of file X509Certificate2.cs.
    {
        if (privateKey == null)
        {
            throw new ArgumentNullException("privateKey");
        }
        if (HasPrivateKey)
        {
            throw new InvalidOperationException(System.SR.Cryptography_Cert_AlreadyHasPrivateKey);
        }
        using (ECDiffieHellman eCDiffieHellman = GetECDiffieHellmanPublicKey())
        {
            if (eCDiffieHellman == null)
            {
                throw new ArgumentException(System.SR.Cryptography_PrivateKey_WrongAlgorithm);
            }
            if (!Internal.Cryptography.Helpers.AreSamePublicECParameters(eCDiffieHellman.ExportParameters(includePrivateParameters: false), privateKey.ExportParameters(includePrivateParameters: false)))
            {
                throw new ArgumentException(System.SR.Cryptography_PrivateKey_DoesNotMatch, "privateKey");
            }
        }
        ICertificatePal pal = Pal.CopyWithPrivateKey(privateKey);
        return new X509Certificate2(pal);
    }
References System.Security.Cryptography.X509Certificates.X509Certificate2.X509Certificate2(), Internal.Cryptography.Helpers.AreSamePublicECParameters(), Internal.Cryptography.ICertificatePal.CopyWithPrivateKey(), System.SR.Cryptography_Cert_AlreadyHasPrivateKey, System.SR.Cryptography_PrivateKey_DoesNotMatch, System.SR.Cryptography_PrivateKey_WrongAlgorithm, System.Runtime.Serialization.Dictionary, System.Security.Cryptography.X509Certificates.X509Certificate2.GetECDiffieHellmanPublicKey(), and System.Security.Cryptography.X509Certificates.X509Certificate2.HasPrivateKey.