Terraria: System.Security.Cryptography.X509Certificates.X509Certificate2.ToString
ToString() [2/2]
override string System.Security.Cryptography.X509Certificates.X509Certificate2.ToString (bool verbose) inline virtual
Reimplemented from System.Security.Cryptography.X509Certificates.X509Certificate.
Definition at line 382 of file X509Certificate2.cs.
    {
        if (!verbose || Pal == null)
        {
            return ToString();
        }
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.AppendLine("[Version]");
        stringBuilder.Append("  V");
        stringBuilder.Append(Version);
        stringBuilder.AppendLine();
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Subject]");
        stringBuilder.Append("  ");
        stringBuilder.Append(SubjectName.Name);
        string nameInfo = GetNameInfo(X509NameType.SimpleName, forIssuer: false);
        if (nameInfo.Length > 0)
        {
            stringBuilder.AppendLine();
            stringBuilder.Append("  ");
            stringBuilder.Append("Simple Name: ");
            stringBuilder.Append(nameInfo);
        }
        string nameInfo2 = GetNameInfo(X509NameType.EmailName, forIssuer: false);
        if (nameInfo2.Length > 0)
        {
            stringBuilder.AppendLine();
            stringBuilder.Append("  ");
            stringBuilder.Append("Email Name: ");
            stringBuilder.Append(nameInfo2);
        }
        string nameInfo3 = GetNameInfo(X509NameType.UpnName, forIssuer: false);
        if (nameInfo3.Length > 0)
        {
            stringBuilder.AppendLine();
            stringBuilder.Append("  ");
            stringBuilder.Append("UPN Name: ");
            stringBuilder.Append(nameInfo3);
        }
        string nameInfo4 = GetNameInfo(X509NameType.DnsName, forIssuer: false);
        if (nameInfo4.Length > 0)
        {
            stringBuilder.AppendLine();
            stringBuilder.Append("  ");
            stringBuilder.Append("DNS Name: ");
            stringBuilder.Append(nameInfo4);
        }
        stringBuilder.AppendLine();
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Issuer]");
        stringBuilder.Append("  ");
        stringBuilder.Append(IssuerName.Name);
        nameInfo = GetNameInfo(X509NameType.SimpleName, forIssuer: true);
        if (nameInfo.Length > 0)
        {
            stringBuilder.AppendLine();
            stringBuilder.Append("  ");
            stringBuilder.Append("Simple Name: ");
            stringBuilder.Append(nameInfo);
        }
        nameInfo2 = GetNameInfo(X509NameType.EmailName, forIssuer: true);
        if (nameInfo2.Length > 0)
        {
            stringBuilder.AppendLine();
            stringBuilder.Append("  ");
            stringBuilder.Append("Email Name: ");
            stringBuilder.Append(nameInfo2);
        }
        nameInfo3 = GetNameInfo(X509NameType.UpnName, forIssuer: true);
        if (nameInfo3.Length > 0)
        {
            stringBuilder.AppendLine();
            stringBuilder.Append("  ");
            stringBuilder.Append("UPN Name: ");
            stringBuilder.Append(nameInfo3);
        }
        nameInfo4 = GetNameInfo(X509NameType.DnsName, forIssuer: true);
        if (nameInfo4.Length > 0)
        {
            stringBuilder.AppendLine();
            stringBuilder.Append("  ");
            stringBuilder.Append("DNS Name: ");
            stringBuilder.Append(nameInfo4);
        }
        stringBuilder.AppendLine();
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Serial Number]");
        stringBuilder.Append("  ");
        stringBuilder.AppendLine(SerialNumber);
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Not Before]");
        stringBuilder.Append("  ");
        stringBuilder.AppendLine(X509Certificate.FormatDate(NotBefore));
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Not After]");
        stringBuilder.Append("  ");
        stringBuilder.AppendLine(X509Certificate.FormatDate(NotAfter));
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Thumbprint]");
        stringBuilder.Append("  ");
        stringBuilder.AppendLine(Thumbprint);
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Signature Algorithm]");
        stringBuilder.Append("  ");
        stringBuilder.Append(SignatureAlgorithm.FriendlyName);
        stringBuilder.Append('(');
        stringBuilder.Append(SignatureAlgorithm.Value);
        stringBuilder.AppendLine(")");
        stringBuilder.AppendLine();
        stringBuilder.Append("[Public Key]");
        try
        {
            PublicKey publicKey = PublicKey;
            stringBuilder.AppendLine();
            stringBuilder.Append("  ");
            stringBuilder.Append("Algorithm: ");
            stringBuilder.Append(publicKey.Oid.FriendlyName);
            try
            {
                stringBuilder.AppendLine();
                stringBuilder.Append("  ");
                stringBuilder.Append("Length: ");
                using RSA rSA = this.GetRSAPublicKey();
                if (rSA != null)
                {
                    stringBuilder.Append(rSA.KeySize);
                }
            }
            catch (NotSupportedException)
            {
            }
            stringBuilder.AppendLine();
            stringBuilder.Append("  ");
            stringBuilder.Append("Key Blob: ");
            stringBuilder.AppendLine(publicKey.EncodedKeyValue.Format(multiLine: true));
            stringBuilder.Append("  ");
            stringBuilder.Append("Parameters: ");
            stringBuilder.Append(publicKey.EncodedParameters.Format(multiLine: true));
        }
        catch (CryptographicException)
        {
        }
        Pal.AppendPrivateKeyInfo(stringBuilder);
        X509ExtensionCollection extensions = Extensions;
        if (extensions.Count > 0)
        {
            stringBuilder.AppendLine();
            stringBuilder.AppendLine();
            stringBuilder.Append("[Extensions]");
            foreach (X509Extension item in extensions)
            {
                try
                {
                    stringBuilder.AppendLine();
                    stringBuilder.Append("* ");
                    stringBuilder.Append(item.Oid.FriendlyName);
                    stringBuilder.Append('(');
                    stringBuilder.Append(item.Oid.Value);
                    stringBuilder.Append("):");
                    stringBuilder.AppendLine();
                    stringBuilder.Append("  ");
                    stringBuilder.Append(item.Format(multiLine: true));
                }
                catch (CryptographicException)
                {
                }
            }
        }
        stringBuilder.AppendLine();
        return stringBuilder.ToString();
    }
References System.Runtime.Serialization.Dictionary, System.Security.Cryptography.X509Certificates.X509Certificate2.Extensions, System.Security.Cryptography.X509Certificates.X509Certificate.FormatDate(), System.Security.Cryptography.Oid.FriendlyName, System.Security.Cryptography.X509Certificates.X509Certificate2.GetNameInfo(), System.Security.Cryptography.X509Certificates.X509Certificate2.IssuerName, System.item, System.Security.Cryptography.X509Certificates.X500DistinguishedName.Name, System.Security.Cryptography.X509Certificates.X509Certificate2.NotAfter, System.Security.Cryptography.X509Certificates.X509Certificate2.NotBefore, System.Security.Cryptography.X509Certificates.X509Certificate2.PublicKey, System.Security.Cryptography.X509Certificates.X509Certificate2.SerialNumber, System.Security.Cryptography.X509Certificates.X509Certificate2.SignatureAlgorithm, System.Security.Cryptography.X509Certificates.X509Certificate2.SubjectName, System.Security.Cryptography.X509Certificates.X509Certificate2.Thumbprint, System.Security.Cryptography.X509Certificates.X509Certificate2.ToString(), and System.Security.Cryptography.Oid.Value.