Terraria: System.Linq.Expressions.Compiler.StackSpiller.TempMaker.Temp
Temp()
ParameterExpression System.Linq.Expressions.Compiler.StackSpiller.TempMaker.Temp (Type type) inline package
Definition at line 481 of file StackSpiller.cs.
        {
            ParameterExpression parameterExpression;
            if (_freeTemps != null)
            {
                for (int num = _freeTemps.Count - 1; num >= 0; num--)
                {
                    parameterExpression = _freeTemps[num];
                    if (parameterExpression.Type == type)
                    {
                        _freeTemps.RemoveAt(num);
                        return UseTemp(parameterExpression);
                    }
                }
            }
            parameterExpression = ParameterExpression.Make(type, "$temp$" + _temp++, isByRef: false);
            Temps.Add(parameterExpression);
            return UseTemp(parameterExpression);
        }
References System.Linq.Expressions.Compiler.StackSpiller.TempMaker._freeTemps, System.Linq.Expressions.Compiler.StackSpiller.TempMaker._temp, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.ParameterExpression.Make(), System.Linq.Expressions.Compiler.StackSpiller.TempMaker.Temps, System.type, and System.Linq.Expressions.Compiler.StackSpiller.TempMaker.UseTemp().
Referenced by System.Linq.Expressions.Compiler.StackSpiller.MakeTemp().