Terraria: System.Linq.Parallel.TakeOrSkipQueryOperator.TakeOrSkipQueryOperatorEnumerator.MoveNext
MoveNext() [2/2]
override bool System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >.MoveNext ([AllowNull] ref TResult currentElement, [AllowNull] ref TKey currentKey) inline package
Definition at line 40 of file TakeOrSkipQueryOperator.cs.
        {
            if (_buffer == null && _count > 0)
            {
                List<Pair<TResult, TKey>> list = new List<Pair<TResult, TKey>>();
                TResult currentElement2 = default(TResult);
                TKey currentKey2 = default(TKey);
                int num = 0;
                while (list.Count < _count && _source.MoveNext(ref currentElement2, ref currentKey2))
                {
                    if ((num++ & 0x3F) == 0)
                    {
                        _cancellationToken.ThrowIfCancellationRequested();
                    }
                    list.Add(new Pair<TResult, TKey>(currentElement2, currentKey2));
                    lock (_sharedIndices)
                    {
                        if (!_sharedIndices.Insert(currentKey2))
{
                            break;
                        }
                    }
                }
                _sharedBarrier.Signal();
                _sharedBarrier.Wait(_cancellationToken);
                _buffer = list;
                _bufferIndex = new Shared<int>(-1);
            }
            if (_take)
            {
                if (_count == 0 || _bufferIndex.Value >= _buffer.Count - 1)
                {
                    return false;
                }
                _bufferIndex.Value++;
                currentElement = _buffer[_bufferIndex.Value].First;
                currentKey = _buffer[_bufferIndex.Value].Second;
                if (_sharedIndices.Count != 0)
                {
                    return _keyComparer.Compare(_buffer[_bufferIndex.Value].Second, _sharedIndices.MaxValue) <= 0;
                }
                return true;
            }
            TKey val = default(TKey);
            if (_count > 0)
            {
                if (_sharedIndices.Count < _count)
                {
                    return false;
                }
                val = _sharedIndices.MaxValue;
                if (_bufferIndex.Value < _buffer.Count - 1)
                {
                    _bufferIndex.Value++;
                    while (_bufferIndex.Value < _buffer.Count)
                    {
                        if (_keyComparer.Compare(_buffer[_bufferIndex.Value].Second, val) > 0)
{
                            currentElement = _buffer[_bufferIndex.Value].First;
                            currentKey = _buffer[_bufferIndex.Value].Second;
                            return true;
                        }
                        _bufferIndex.Value++;
                    }
                }
            }
            if (_source.MoveNext(ref currentElement, ref currentKey))
            {
                return true;
            }
            return false;
        }
References System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >._buffer, System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >._bufferIndex, System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >._cancellationToken, System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >._count, System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >._keyComparer, System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >._sharedBarrier, System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >._sharedIndices, System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >._source, System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >._take, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.IComparer< in T >.Compare(), System.Linq.Parallel.FixedMaxHeap< TElement >.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Parallel.FixedMaxHeap< TElement >.Insert(), System.list, System.Linq.Parallel.FixedMaxHeap< TElement >.MaxValue, System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.MoveNext(), System.Threading.CountdownEvent.Signal(), System.Threading.CancellationToken.ThrowIfCancellationRequested(), System.Linq.Parallel.Shared< T >.Value, and System.Threading.CountdownEvent.Wait().