Terraria: Terraria.GameContent.UI.Chat.RemadeChatMonitor.AddNewMessage
AddNewMessage()
void Terraria.GameContent.UI.Chat.RemadeChatMonitor.AddNewMessage (string text, Color color, int widthLimitInPixels = -1) inline
Definition at line 37 of file RemadeChatMonitor.cs.
    {
        ChatMessageContainer chatMessageContainer = new ChatMessageContainer();
        chatMessageContainer.SetContents(text, color, widthLimitInPixels);
        _messages.Insert(0, chatMessageContainer);
        while (_messages.Count > 500)
        {
            _messages.RemoveAt(_messages.Count - 1);
        }
    }
References Terraria.GameContent.UI.Chat.RemadeChatMonitor._messages, and Terraria.UI.Chat.ChatMessageContainer.SetContents().
Referenced by Terraria.GameContent.UI.Chat.RemadeChatMonitor.NewText(), and Terraria.GameContent.UI.Chat.RemadeChatMonitor.NewTextMultiline().