Terraria: System.Security.Cryptography.Asn1.ECPrivateKey.Decode
Decode() [3/4]
static ECPrivateKey System.Security.Cryptography.Asn1.ECPrivateKey.Decode (ReadOnlyMemory< byte > encoded, AsnEncodingRules ruleSet) inline static package
Definition at line 15 of file ECPrivateKey.cs.
    {
        return Decode(Asn1Tag.Sequence, encoded, ruleSet);
    }
References System.Security.Cryptography.Asn1.ECPrivateKey.Decode(), and System.Formats.Asn1.Asn1Tag.Sequence.
Referenced by System.Security.Cryptography.Asn1.ECPrivateKey.Decode(), System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey(), and System.Security.Cryptography.CngPkcs8.RewritePkcs8ECPrivateKeyWithZeroPublicKey().