Terraria: System.Security.Cryptography.Asn1.ECPrivateKey.DecodeCore
DecodeCore() [1/2]
static void System.Security.Cryptography.Asn1.ECPrivateKey.DecodeCore (ref AsnValueReader reader, Asn1Tag expectedTag, ReadOnlyMemory< byte > rebind, out ECPrivateKey decoded) inline static private
Definition at line 35 of file ECPrivateKey.cs.
    {
        decoded = default(ECPrivateKey);
        AsnValueReader asnValueReader = reader.ReadSequence(expectedTag);
        ReadOnlySpan<byte> span = rebind.Span;
        if (!asnValueReader.TryReadInt32(out decoded.Version))
        {
            asnValueReader.ThrowIfNotEmpty();
        }
        int elementOffset;
        if (asnValueReader.TryReadPrimitiveOctetString(out var value))
        {
            decoded.PrivateKey = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
        }
        else
        {
            decoded.PrivateKey = asnValueReader.ReadOctetString();
        }
        AsnValueReader reader2;
        if (asnValueReader.HasData && asnValueReader.PeekTag().HasSameClassAndValue(new Asn1Tag(TagClass.ContextSpecific, 0)))
        {
            reader2 = asnValueReader.ReadSequence(new Asn1Tag(TagClass.ContextSpecific, 0));
            ECDomainParameters.Decode(ref reader2, rebind, out var decoded2);
            decoded.Parameters = decoded2;
            reader2.ThrowIfNotEmpty();
        }
        if (asnValueReader.HasData && asnValueReader.PeekTag().HasSameClassAndValue(new Asn1Tag(TagClass.ContextSpecific, 1)))
        {
            reader2 = asnValueReader.ReadSequence(new Asn1Tag(TagClass.ContextSpecific, 1));
            if (reader2.TryReadPrimitiveBitString(out var unusedBitCount, out value))
            {
                decoded.PublicKey = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
            }
            else
            {
                decoded.PublicKey = reader2.ReadBitString(out unusedBitCount);
            }
            reader2.ThrowIfNotEmpty();
        }
        asnValueReader.ThrowIfNotEmpty();
    }
References System.Security.Cryptography.Asn1.ECDomainParameters.Decode(), System.Formats.Asn1.AsnValueReader.HasData, System.Formats.Asn1.Asn1Tag.HasSameClassAndValue(), System.Formats.Asn1.AsnValueReader.PeekTag(), System.Formats.Asn1.AsnValueReader.ReadBitString(), System.Formats.Asn1.AsnValueReader.ReadOctetString(), System.Formats.Asn1.AsnValueReader.ReadSequence(), System.ReadOnlyMemory< T >.Slice(), System.ReadOnlyMemory< T >.Span, System.Formats.Asn1.AsnValueReader.ThrowIfNotEmpty(), System.Formats.Asn1.AsnValueReader.TryReadInt32(), System.Formats.Asn1.AsnValueReader.TryReadPrimitiveBitString(), System.Formats.Asn1.AsnValueReader.TryReadPrimitiveOctetString(), and System.value.
Referenced by System.Security.Cryptography.Asn1.ECPrivateKey.Decode().