Terraria: System.Collections.IEnumerator.MoveNext
MoveNext()
bool System.Collections.IEnumerator.MoveNext () inherited
Implemented in Microsoft.Xna.Framework.Graphics.ModelBoneCollection.Enumerator, Microsoft.Xna.Framework.Graphics.ModelEffectCollection.Enumerator, Microsoft.Xna.Framework.Graphics.ModelMeshCollection.Enumerator, Microsoft.Xna.Framework.Graphics.ModelMeshPartCollection.Enumerator, ReLogic.Utilities.SlotVector< T >.Enumerator, System.Collections.Concurrent.ConcurrentBag< T >.Enumerator, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Enumerator, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.DictionaryEnumerator, System.Collections.Concurrent.OrderablePartitioner< TSource >.EnumeratorDropIndices, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionEnumerator_Abstract< TSource, TSourceReader >, System.Collections.Concurrent.Partitioner< TSource >.StaticIndexRangePartition< TSource >, System.Collections.Immutable.DictionaryEnumerator< TKey, TValue >, System.Collections.Immutable.ImmutableArray< T >.EnumeratorObject, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Enumerator, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket.Enumerator, System.Collections.Immutable.ImmutableHashSet< T >.Enumerator, System.Collections.Immutable.ImmutableHashSet< T >.HashBucket.Enumerator, System.Collections.Immutable.ImmutableList< T >.Enumerator, System.Collections.Immutable.ImmutableQueue< T >.EnumeratorObject, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Enumerator, System.Collections.Immutable.ImmutableSortedSet< T >.Enumerator, System.Collections.Immutable.ImmutableStack< T >.EnumeratorObject, System.Collections.Immutable.SortedInt32KeyNode< TValue >.Enumerator, System.Collections.Queue.QueueEnumerator, System.Collections.SortedList.SortedListEnumerator, System.Collections.Stack.StackEnumerator, System.Collections.Specialized.ListDictionary.NodeEnumerator, System.Collections.Specialized.ListDictionary.NodeKeyValueCollection.NodeKeyValueEnumerator, System.Collections.Specialized.NameObjectCollectionBase.NameObjectKeysEnumerator, System.Collections.Specialized.OrderedDictionary.OrderedDictionaryEnumerator, System.Collections.Generic.LinkedList< T >.Enumerator, System.Collections.Generic.PriorityQueue< TElement, TPriority >.UnorderedItemsCollection.Enumerator, System.Collections.Generic.SortedDictionary< TKey, TValue >.Enumerator, System.Collections.Generic.SortedDictionary< TKey, TValue >.KeyCollection.Enumerator, System.Collections.Generic.SortedDictionary< TKey, TValue >.ValueCollection.Enumerator, System.Collections.Generic.SortedList< TKey, TValue >.Enumerator, System.Collections.Generic.SortedList< TKey, TValue >.SortedListKeyEnumerator, System.Collections.Generic.SortedList< TKey, TValue >.SortedListValueEnumerator, System.Collections.Generic.SortedSet< T >.Enumerator, System.Collections.Generic.Stack< T >.Enumerator, System.Collections.BitArray.BitArrayEnumeratorSimple, System.ComponentModel.EventDescriptorCollection.ArraySubsetEnumerator, System.ComponentModel.PropertyDescriptorCollection.PropertyDescriptorEnumerator, System.Data.Common.DbEnumerator, System.Data.DataViewSettingCollection.DataViewSettingsEnumerator, System.Data.RBTree< K >.RBTreeEnumerator, System.Diagnostics.ActivityTagsCollection.Enumerator, System.Diagnostics.Enumerator< T >, System.Diagnostics.TagList.Enumerator, System.IO.IsolatedStorage.IsolatedStorageFile.IsolatedStorageFileEnumerator, System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.Enumerator, System.Linq.Parallel.EmptyEnumerator< T >, System.Linq.Parallel.EnumerableWrapperWeakToStrong.WrapperEnumeratorWeakToStrong, System.Linq.Parallel.MergeEnumerator< TInputOutput >, System.Linq.Parallel.QueryOpeningEnumerator< TOutput >, System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.QueryOperatorClassicEnumerator, System.Linq.EmptyPartition< TElement >, System.Linq.Enumerable.AppendPrepend1Iterator< TSource >, System.Linq.Enumerable.AppendPrependN< TSource >, System.Linq.Enumerable.ConcatIterator< TSource >, System.Linq.Enumerable.DefaultIfEmptyIterator< TSource >, System.Linq.Enumerable.DistinctIterator< TSource >, System.Linq.Enumerable.ListPartition< TSource >, System.Linq.Enumerable.EnumerablePartition< TSource >, System.Linq.Enumerable.ReverseIterator< TSource >, System.Linq.Enumerable.UnionIterator< TSource >, System.Linq.Enumerable.WhereEnumerableIterator< TSource >, System.Linq.Enumerable.WhereArrayIterator< TSource >, System.Linq.Enumerable.WhereListIterator< TSource >, System.Linq.Enumerable.Iterator< TSource >, System.Net.Http.Headers.HeaderStringValues.Enumerator, System.Net.Http.Headers.HttpHeadersNonValidated.Enumerator, System.Net.Http.Headers.ObjectCollection< T >.Enumerator, System.Net.ListenerPrefixEnumerator, System.Net.CredentialCache.CredentialEnumerator, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.DictionaryEnumerator, System.Collections.Generic.Dictionary< TKey, TValue >.Enumerator, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.Enumerator, System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.Enumerator, System.Collections.Generic.HashSet< T >.Enumerator, System.Collections.Generic.List< T >.Enumerator, System.Collections.Generic.Queue< T >.Enumerator, System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper, System.Collections.ArrayList.ArrayListEnumerator, System.Collections.ArrayList.ArrayListEnumeratorSimple, System.Collections.EmptyReadOnlyDictionaryInternal.NodeEnumerator, System.Collections.Hashtable.HashtableEnumerator, System.Collections.ListDictionaryInternal.NodeEnumerator, System.Collections.ListDictionaryInternal.NodeKeyValueCollection.NodeKeyValueEnumerator, System.Globalization.TextElementEnumerator, System.IO.Enumeration.FileSystemEnumerator< TResult >, System.IO.Iterator< TSource >, System.Resources.ResourceReader.ResourceEnumerator, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Enumerator, System.Runtime.InteropServices.CustomMarshalers.EnumeratorViewOfEnumVariant, System.Runtime.Serialization.SerializationInfoEnumerator, System.Text.StringRuneEnumerator, System.ArrayEnumerator, System.ArraySegment< T >.Enumerator, System.CharEnumerator, System.SZGenericArrayEnumerator< T >, System.Runtime.Serialization.CollectionDataContract.DictionaryEnumerator, System.Runtime.Serialization.CollectionDataContract.GenericDictionaryEnumerator< K, V >, System.Xml.Schema.XmlSchemaCollectionEnumerator, System.Xml.Schema.XmlSchemaCollectionEnumerator, System.Xml.Schema.XmlSchemaObjectEnumerator, System.Xml.Schema.XmlSchemaObjectEnumerator, System.Xml.Schema.XmlSchemaObjectTable.XSOEnumerator, System.Xml.Serialization.XmlSchemaEnumerator, System.Xml.XPath.XPathNodeIterator.Enumerator, System.Xml.Xsl.IListEnumerator< T >, System.Xml.EmptyEnumerator, System.Xml.XmlChildEnumerator, System.Xml.XmlChildEnumerator, System.Xml.XmlElementListEnumerator, System.Xml.XmlEmptyElementListEnumerator, System.Xml.XmlNamedNodeMap.SmallXmlNodeList.SingleObjectEnumerator, System.Xml.XmlNodeListEnumerator, System.Reflection.Metadata.AssemblyFileHandleCollection.Enumerator, System.Reflection.Metadata.AssemblyReferenceHandleCollection.Enumerator, System.Reflection.Metadata.BlobBuilder.Chunks, System.Reflection.Metadata.BlobBuilder.Blobs, System.Reflection.Metadata.CustomAttributeHandleCollection.Enumerator, System.Reflection.Metadata.CustomDebugInformationHandleCollection.Enumerator, System.Reflection.Metadata.DeclarativeSecurityAttributeHandleCollection.Enumerator, System.Reflection.Metadata.DocumentHandleCollection.Enumerator, System.Reflection.Metadata.EventDefinitionHandleCollection.Enumerator, System.Reflection.Metadata.ExportedTypeHandleCollection.Enumerator, System.Reflection.Metadata.FieldDefinitionHandleCollection.Enumerator, System.Reflection.Metadata.GenericParameterConstraintHandleCollection.Enumerator, System.Reflection.Metadata.GenericParameterHandleCollection.Enumerator, System.Reflection.Metadata.ImportDefinitionCollection.Enumerator, System.Reflection.Metadata.ImportScopeCollection.Enumerator, System.Reflection.Metadata.InterfaceImplementationHandleCollection.Enumerator, System.Reflection.Metadata.LocalConstantHandleCollection.Enumerator, System.Reflection.Metadata.LocalScopeHandleCollection.Enumerator, System.Reflection.Metadata.LocalScopeHandleCollection.ChildrenEnumerator, System.Reflection.Metadata.LocalVariableHandleCollection.Enumerator, System.Reflection.Metadata.ManifestResourceHandleCollection.Enumerator, System.Reflection.Metadata.MemberReferenceHandleCollection.Enumerator, System.Reflection.Metadata.MethodDebugInformationHandleCollection.Enumerator, System.Reflection.Metadata.MethodDefinitionHandleCollection.Enumerator, System.Reflection.Metadata.MethodImplementationHandleCollection.Enumerator, System.Reflection.Metadata.ParameterHandleCollection.Enumerator, System.Reflection.Metadata.PropertyDefinitionHandleCollection.Enumerator, System.Reflection.Metadata.SequencePointCollection.Enumerator, System.Reflection.Metadata.TypeDefinitionHandleCollection.Enumerator, System.Reflection.Metadata.TypeReferenceHandleCollection.Enumerator, System.Security.AccessControl.AceEnumerator, System.Security.Cryptography.AsnEncodedDataEnumerator, System.Security.Cryptography.OidEnumerator, System.Security.Cryptography.X509Certificates.X509Certificate2Enumerator, System.Security.Cryptography.X509Certificates.X509Certificate2Enumerator, System.Security.Cryptography.X509Certificates.X509CertificateCollection.X509CertificateEnumerator, System.Security.Cryptography.X509Certificates.X509CertificateCollection.X509CertificateEnumerator, System.Security.Cryptography.X509Certificates.X509ChainElementEnumerator, System.Security.Cryptography.X509Certificates.X509ExtensionEnumerator, System.Security.Principal.IdentityReferenceEnumerator, System.Text.Json.JsonElement.ArrayEnumerator, System.Text.Json.JsonElement.ObjectEnumerator, System.Text.RegularExpressions.CaptureCollection.Enumerator, System.Text.RegularExpressions.GroupCollection.Enumerator, and System.Text.RegularExpressions.MatchCollection.Enumerator.
Referenced by System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper.IListWrapperEnumWrapper(), System.Collections.Queue.Queue(), System.Collections.Stack.Stack(), System.Collections.Specialized.HybridDictionary.ChangeOver(), System.Data.DataViewSettingCollection.CopyTo(), System.Data.DataViewSettingCollection.CopyTo(), System.Diagnostics.ProcessModuleCollection.Dispose(), System.Diagnostics.ProcessThreadCollection.Dispose(), System.Security.SecurityElement.Equal(), System.Data.ConstraintEnumerator.GetNext(), System.Linq.Enumerable.UnionIterator< TSource >.GetNext(), System.Security.Cryptography.XmlKeyHelper.ParseState.GetValue(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.GrabChunk_Buffered(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.GrabChunk_Single(), System.Collections.ArrayList.IListWrapper.InsertRange(), System.Linq.Enumerable.AppendPrependIterator< TSource >.LoadFromEnumerator(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.DictionaryEnumerator.MoveNext(), System.Collections.Concurrent.OrderablePartitioner< TSource >.EnumeratorDropIndices.MoveNext(), System.Collections.Immutable.DictionaryEnumerator< TKey, TValue >.MoveNext(), System.Collections.Specialized.OrderedDictionary.OrderedDictionaryEnumerator.MoveNext(), System.Collections.Specialized.StringEnumerator.MoveNext(), System.Data.DataViewSettingCollection.DataViewSettingsEnumerator.MoveNext(), System.Linq.Parallel.EnumerableWrapperWeakToStrong.WrapperEnumeratorWeakToStrong.MoveNext(), System.Linq.Enumerable.ConcatIterator< TSource >.MoveNext(), System.Linq.Enumerable.DefaultIfEmptyIterator< TSource >.MoveNext(), System.Linq.Enumerable.DistinctIterator< TSource >.MoveNext(), System.Linq.Enumerable.EnumerablePartition< TSource >.MoveNext(), System.Linq.Enumerable.SelectEnumerableIterator< TSource, TResult >.MoveNext(), System.Linq.Enumerable.SelectIListIterator< TSource, TResult >.MoveNext(), System.Linq.Enumerable.SelectIPartitionIterator< TSource, TResult >.MoveNext(), System.Linq.Enumerable.SelectManySingleSelectorIterator< TSource, TResult >.MoveNext(), System.Linq.Enumerable.WhereEnumerableIterator< TSource >.MoveNext(), System.Linq.Enumerable.WhereSelectEnumerableIterator< TSource, TResult >.MoveNext(), System.Net.ListenerPrefixEnumerator.MoveNext(), System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.DictionaryEnumerator.MoveNext(), System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper.MoveNext(), System.Runtime.Serialization.CollectionDataContract.DictionaryEnumerator.MoveNext(), System.Xml.Schema.XmlSchemaCollectionEnumerator.MoveNext(), System.Xml.Schema.XmlSchemaObjectEnumerator.MoveNext(), System.Security.Cryptography.X509Certificates.X509Certificate2Enumerator.MoveNext(), System.Security.Cryptography.X509Certificates.X509CertificateCollection.X509CertificateEnumerator.MoveNext(), System.ComponentModel.TypeDescriptor.PipelineInitialize(), System.ComponentModel.TypeDescriptor.PipelineMerge(), System.Transactions.TransactionManager.ProcessExistingTransactions(), System.ComponentModel.TypeDescriptor.Refresh(), System.ComponentModel.TypeDescriptor.Refresh(), System.ComponentModel.TypeDescriptor.Refresh(), System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper.Reset(), System.Collections.ArrayList.IListWrapper.SetRange(), and Terraria.Main.TickLoadProcess().