Terraria: SmartSelectGamepadPointer.SmartSelectLookup_GetTargetTile
SmartSelectLookup_GetTargetTile()
void SmartSelectGamepadPointer.SmartSelectLookup_GetTargetTile (Player player, out int tX, out int tY) inline
     {
         tX = (int)(((float)Main.mouseX + Main.screenPosition.X) / 16f);
         tY = (int)(((float)Main.mouseY + Main.screenPosition.Y) / 16f);
         if (player.gravDir == -1f)
         {
             tY = (int)((Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY) / 16f);
         }
         if (ShouldBeUsed())
         {
             Point point = GetPointerPosition().ToPoint();
             tX = (int)(((float)point.X + Main.screenPosition.X) / 16f);
             tY = (int)(((float)point.Y + Main.screenPosition.Y) / 16f);
             if (player.gravDir == -1f)
             {
                 tY = (int)((Main.screenPosition.Y + (float)Main.screenHeight - (float)point.Y) / 16f);
             }
         }
     }
References GetPointerPosition(), Player.gravDir, Main.mouseX, Main.mouseY, Main.screenHeight, Main.screenPosition, and ShouldBeUsed().
Referenced by Player.SmartSelectLookup().