Terraria: System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.AwaitUnsafeOnCompleted
AwaitUnsafeOnCompleted()
void IStateMachineBoxAwareAwaiter. System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.AwaitUnsafeOnCompleted (IAsyncStateMachineBox box) inline
Implements System.Runtime.CompilerServices.IStateMachineBoxAwareAwaiter.
Definition at line 64 of file YieldAwaitable.cs.
        {
            if (TplEventSource.Log.IsEnabled())
            {
                QueueContinuation(box.MoveNextAction, flowContext: false);
                return;
            }
            SynchronizationContext current = SynchronizationContext.Current;
            if (current != null && current.GetType() != typeof(SynchronizationContext))
            {
                current.Post(delegate(object s)
                {
                    ((IAsyncStateMachineBox)s).MoveNext();
                }, box);
                return;
            }
            TaskScheduler current2 = TaskScheduler.Current;
            if (current2 == TaskScheduler.Default)
            {
                ThreadPool.UnsafeQueueUserWorkItemInternal(box, preferLocal: false);
                return;
            }
            Task.Factory.StartNew(delegate(object s)
            {
                ((IAsyncStateMachineBox)s).MoveNext();
            }, box, default(CancellationToken), TaskCreationOptions.PreferFairness, current2);
        }
References System.Threading.Tasks.TaskScheduler.Current, System.Threading.SynchronizationContext.Current, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.TplEventSource.Log, System.Runtime.CompilerServices.IAsyncStateMachineBox.MoveNextAction, System.Threading.SynchronizationContext.Post(), System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.QueueContinuation(), System.s, and System.Threading.ThreadPool.UnsafeQueueUserWorkItemInternal().