Terraria: System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.OutputCorrelationEtwEvent
OutputCorrelationEtwEvent()
static Action System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.OutputCorrelationEtwEvent (Action continuation) inline static private
Definition at line 92 of file YieldAwaitable.cs.
        {
            int num = Task.NewId();
            Task internalCurrent = Task.InternalCurrent;
            TplEventSource.Log.AwaitTaskContinuationScheduled(TaskScheduler.Current.Id, internalCurrent?.Id ?? 0, num);
            return AsyncMethodBuilderCore.CreateContinuationWrapper(continuation, delegate(Action innerContinuation, Task continuationIdTask)
            {
                TplEventSource log = TplEventSource.Log;
                log.TaskWaitContinuationStarted(((Task<int>)continuationIdTask).Result);
                Guid oldActivityThatWillContinue = default(Guid);
                if (log.TasksSetActivityIds)
                {
                    EventSource.SetCurrentThreadActivityId(TplEventSource.CreateGuidForTaskID(((Task<int>)continuationIdTask).Result), out oldActivityThatWillContinue);
                }
                innerContinuation();
                if (log.TasksSetActivityIds)
                {
                    EventSource.SetCurrentThreadActivityId(oldActivityThatWillContinue);
                }
                log.TaskWaitContinuationComplete(((Task<int>)continuationIdTask).Result);
            }, Task.FromResult(num));
        }
References System.Runtime.CompilerServices.AsyncMethodBuilderCore.CreateContinuationWrapper(), System.Threading.Tasks.TaskScheduler.Current, System.Threading.Tasks.Task< TResult >.Id, System.Threading.Tasks.Task< TResult >.InternalCurrent, System.Threading.Tasks.TplEventSource.Log, System.Threading.Tasks.Task< TResult >.NewId(), System.Threading.Tasks.TplEventSource.TasksSetActivityIds, System.Threading.Tasks.TplEventSource.TaskWaitContinuationComplete(), and System.Threading.Tasks.TplEventSource.TaskWaitContinuationStarted().
Referenced by System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.QueueContinuation().