Terraria: System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.QueueContinuation
QueueContinuation()
static void System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.QueueContinuation (Action continuation, bool flowContext) inline static private
Definition at line 30 of file YieldAwaitable.cs.
        {
            if (continuation == null)
            {
                throw new ArgumentNullException("continuation");
            }
            if (TplEventSource.Log.IsEnabled())
            {
                continuation = OutputCorrelationEtwEvent(continuation);
            }
            SynchronizationContext current = SynchronizationContext.Current;
            if (current != null && current.GetType() != typeof(SynchronizationContext))
            {
                current.Post(s_sendOrPostCallbackRunAction, continuation);
                return;
            }
            TaskScheduler current2 = TaskScheduler.Current;
            if (current2 == TaskScheduler.Default)
            {
                if (flowContext)
                {
                    ThreadPool.QueueUserWorkItem(s_waitCallbackRunAction, continuation);
                }
                else
                {
                    ThreadPool.UnsafeQueueUserWorkItem(s_waitCallbackRunAction, continuation);
                }
            }
            else
            {
                Task.Factory.StartNew(continuation, default(CancellationToken), TaskCreationOptions.PreferFairness, current2);
            }
        }
References System.Threading.Tasks.TaskScheduler.Current, System.Threading.SynchronizationContext.Current, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.TplEventSource.Log, System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.OutputCorrelationEtwEvent(), System.Threading.SynchronizationContext.Post(), System.Threading.ThreadPool.QueueUserWorkItem(), System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.s_sendOrPostCallbackRunAction, System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.s_waitCallbackRunAction, and System.Threading.ThreadPool.UnsafeQueueUserWorkItem().
Referenced by System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.AwaitUnsafeOnCompleted(), System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.OnCompleted(), and System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.UnsafeOnCompleted().