Terraria: System.Threading.Volatile.Write
Write() [1/13]
static void System.Threading.Volatile.Write (ref bool location, bool value) inline static
Definition at line 74 of file Volatile.cs.
    {
        Unsafe.As<bool, VolatileBoolean>(ref location).Value = value;
    }
References System.value.
Referenced by System.ComponentModel.DefaultValueAttribute.DefaultValueAttribute(), System.Threading.Tasks.Dataflow.JoinBlock< T1, T2, T3 >.JoinBlock(), System.Dynamic.Utils.CacheDict< TKey, TValue >.Add(), System.Threading.PortableThreadPool.AdjustMaxWorkersActive(), System.IO.Compression.BrotliStream.AsyncOperationCompleting(), System.IO.Compression.DeflateStream.AsyncOperationCompleting(), System.Net.Http.HttpConnection.ConsumeReadAheadTask(), System.Text.Unicode.UnicodeRanges.CreateEmptyRange(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.CreateEntryNoResize(), System.Text.Unicode.UnicodeRanges.CreateRange(), System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >.EnqueueSlow(), System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >.EnqueueSlow(), System.Threading.LazyInitializer.EnsureInitializedCore< T >(), System.Threading.LazyInitializer.EnsureInitializedCore< T >(), System.Threading.LazyInitializer.EnsureInitializedCore<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T >(), System.Threading.ReaderWriterLockSlim.SpinLock.Exit(), System.Threading.CancellationTokenSource.Registrations.ExitLock(), System.Text.RegularExpressions.RegexCache.Get(), System.Net.Sockets.SafeSocketHandle.GetOrAllocateThreadPoolBoundHandle(), Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult(), System.Threading.Channels.AsyncOperation< TResult >.GetResult(), System.AppDomain.GetThreadPrincipal(), System.Resources.ResourceReader.InitializeBinaryFormatter(), System.Globalization.OrdinalCasing.InitOrdinalCasingPage(), System.Reflection.CerHashtable< K, V >.Table.Insert(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.Insert(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalFindAndPop(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPush(), System.Security.SecureString.MakeReadOnly(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.MergeWithGlobalList(), System.Reflection.CerHashtable< K, V >.Rehash(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.RemoveIndex(), System.IO.StreamBuffer.ResettableValueTaskSource.Reset(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.Resize(), System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.StateMachineBox< TStateMachine >.ReturnToCache(), System.Console.SetError(), System.Diagnostics.Tracing.TraceLoggingEventHandleTable.SetEventHandle(), System.Console.SetIn(), System.Console.SetOut(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryAddInternal(), System.Collections.Concurrent.ConcurrentQueueSegment< T >.TryDequeue(), System.Collections.Concurrent.ConcurrentQueueSegment< T >.TryEnqueue(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryRemoveInternal(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryUpdateInternal(), System.DateTime.UpdateLeapSecondCacheAndReturnUtcNow(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Thread.VolatileWrite(), System.Threading.Volatile.Write(), System.Threading.Volatile.Write(), and System.Net.Quic.Implementations.Mock.MockStream.WriteAsync().