Terraria: System.Threading.Volatile.Read
Read() [1/13]
static bool System.Threading.Volatile.Read (ref bool location) inline static
Definition at line 67 of file Volatile.cs.
    {
        return Unsafe.As<bool, VolatileBoolean>(ref location).Value;
    }
Referenced by System.Text.RegularExpressions.RegexCache.Add(), System.Dynamic.Utils.CacheDict< TKey, TValue >.Add(), System.Threading.Tasks.Task< TResult >.AddExceptionsFromChildren(), System.Collections.Immutable.ImmutableInterlocked.AddOrUpdate< TKey, TValue >(), System.Collections.Immutable.ImmutableInterlocked.AddOrUpdate< TKey, TValue >(), System.Threading.DeferredDisposableLifetime< T >.AddRef(), System.Threading.Tasks.Task< TResult >.AddToActiveTasks(), System.Threading.Tasks.Task< TResult >.CancellationCleanupLogic(), System.Net.HttpWebRequest.CheckAbort(), System.RuntimeType.ClearCache(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.CompleteBlockOncePossible(), System.Resources.ResourceReader.DeserializeObject(), System.Net.Sockets.TcpClient.Dispose(), System.Threading.Tasks.Task< TResult >.Dispose(), System.Threading.DeferredDisposableLifetime< T >.Dispose(), System.Collections.Immutable.ImmutableInterlocked.Enqueue< T >(), System.IO.Stream.EnsureAsyncActiveSemaphoreInitialized(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.EnsureCompletionStateInitialized(), System.Threading.Tasks.Task< TResult >.EnsureContingentPropertiesInitialized(), System.Threading.LazyInitializer.EnsureInitialized< T >(), System.Threading.LazyInitializer.EnsureInitialized< T >(), System.Threading.LazyInitializer.EnsureInitialized< T >(), System.Threading.LazyInitializer.EnsureInitialized<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T >(), System.Threading.LazyInitializer.EnsureInitialized<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T >(), System.Threading.LazyInitializer.EnsureInitializedCore< T >(), System.Threading.LazyInitializer.EnsureInitializedCore< T >(), System.Threading.LazyInitializer.EnsureInitializedCore<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T >(), System.Collections.Concurrent.ConcurrentQueue< T >.Enumerate(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.FindEntry(), System.Threading.Tasks.Task< TResult >.FinishStageTwo(), System.Text.RegularExpressions.RegexCache.Get(), Internal.Cryptography.BCryptAeadHandleCache.GetCachedAlgorithmHandle(), System.Threading.Tasks.Task< TResult >.GetCancellationExceptionDispatchInfo(), System.Collections.Concurrent.ConcurrentQueue< T >.GetCount(), System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(), Microsoft.Win32.SafeHandles.SafeHandleCache< T >.GetInvalidHandle(), System.Collections.Concurrent.ConcurrentQueue< T >.GetItemWhenAvailable(), System.Threading.PortableThreadPool.GetMaxThreads(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.GetMemberList(), System.Threading.PortableThreadPool.GetMinThreads(), System.Collections.Immutable.ImmutableInterlocked.GetOrAdd< TKey, TValue >(), System.Collections.Immutable.ImmutableInterlocked.GetOrAdd< TKey, TValue >(), System.Collections.Immutable.ImmutableInterlocked.GetOrAdd< TKey, TValue, TArg >(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionEnumeratorForIndexRange_Abstract< TSource, TSourceReader >.GrabNextChunk(), System.Resources.ResourceReader.InitializeBinaryFormatter(), Microsoft.Win32.SafeHandles.SafeHandleCache< T >.IsCachedInvalidHandle(), System.Security.SecureString.IsReadOnly(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPopCore(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Enumerator.MoveNext(), System.Linq.Parallel.SingleQueryOperator< TSource >.SingleQueryOperatorEnumerator< TKey >.MoveNext(), System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.OfferMessage(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferToTargets(), System.Threading.Tasks.Task< TResult >.ProcessChildCompletion(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.ProcessMessagesLoopCore(), System.Collections.Immutable.ImmutableInterlocked.Push< T >(), System.ComponentModel.TypeDescriptor.RaiseRefresh(), System.ComponentModel.TypeDescriptor.RaiseRefresh(), System.Threading.Volatile.Read(), System.Threading.Volatile.Read(), System.IO.Strategies.OSFileStreamStrategy.ReadAsync(), System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(), System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveCoreByLinking< TOutput >(), System.Threading.CancellationTokenSource.Register(), System.Threading.DeferredDisposableLifetime< T >.Release(), System.Net.Http.HttpConnection.SendAsyncCore(), System.Threading.PortableThreadPool.ShouldAdjustMaxWorkersActive(), System.Collections.Concurrent.ConcurrentQueue< T >.SnapForObservation(), System.Diagnostics.Tracing.EventCounter.ToString(), System.Collections.Immutable.ImmutableInterlocked.TryAdd< TKey, TValue >(), System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.TryCleanupAndComplete(), System.Collections.Concurrent.ConcurrentQueueSegment< T >.TryDequeue(), System.Collections.Immutable.ImmutableInterlocked.TryDequeue< T >(), System.Collections.Concurrent.ConcurrentQueueSegment< T >.TryEnqueue(), System.Runtime.CompilerServices.CastHelpers.TryGet(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryGetValue(), System.Dynamic.Utils.CacheDict< TKey, TValue >.TryGetValue(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryGetValueInternal(), System.Collections.Concurrent.ConcurrentQueue< T >.TryPeek(), System.Collections.Concurrent.ConcurrentQueueSegment< T >.TryPeek(), System.Collections.Immutable.ImmutableInterlocked.TryPop< T >(), System.Collections.Immutable.ImmutableInterlocked.TryRemove< TKey, TValue >(), System.Threading.CancellationTokenSource.TryReset(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.TrySteal(), System.Collections.Immutable.ImmutableInterlocked.TryUpdate< TKey, TValue >(), System.Collections.Immutable.ImmutableInterlocked.Update< T >(), System.Collections.Immutable.ImmutableInterlocked.Update< T >(), System.Collections.Immutable.ImmutableInterlocked.Update< T, TArg >(), System.Collections.Immutable.ImmutableInterlocked.Update< T, TArg >(), System.Threading.PortableThreadPool.ThreadCounts.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.Thread.VolatileRead(), System.Threading.CancellationTokenSource.Registrations.WaitForCallbackToComplete(), System.Threading.CancellationTokenSource.Registrations.WaitForCallbackToCompleteAsync(), System.Net.Quic.Implementations.Mock.MockStream.Write(), and System.Net.Quic.Implementations.Mock.MockStream.WriteAsync().