Terraria: System.Collections.IDictionary.Remove
Remove()
void System.Collections.IDictionary.Remove (object key) inherited
Implemented in System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Builder, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Builder, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >, System.Collections.DictionaryBase, System.Collections.SortedList.SyncSortedList, System.Collections.SortedList, System.Collections.Specialized.HybridDictionary, System.Collections.Specialized.ListDictionary, System.Collections.Specialized.OrderedDictionary, System.Collections.Specialized.DictionaryWrapper, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >, System.Collections.EmptyReadOnlyDictionaryInternal, System.Collections.Hashtable.SyncHashtable, System.Collections.Hashtable, and System.Collections.ListDictionaryInternal.
Referenced by System.ComponentModel.TypeDescriptor.PipelineFilter(), System.ComponentModel.TypeDescriptor.PipelineInitialize(), and System.ComponentModel.TypeDescriptor.Refresh().