Terraria: System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadArgument
LoadArgument()
void System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadArgument (int argumentIndex) inline
Definition at line 236 of file InstructionEncoder.cs.
    {
        switch (argumentIndex)
        {
        case 0:
            OpCode(ILOpCode.Ldarg_0);
            return;
        case 1:
            OpCode(ILOpCode.Ldarg_1);
            return;
        case 2:
            OpCode(ILOpCode.Ldarg_2);
            return;
        case 3:
            OpCode(ILOpCode.Ldarg_3);
            return;
        }
        if ((uint)argumentIndex <= 255u)
        {
            OpCode(ILOpCode.Ldarg_s);
            CodeBuilder.WriteByte((byte)argumentIndex);
        }
        else if (argumentIndex > 0)
        {
            OpCode(ILOpCode.Ldarg);
            CodeBuilder.WriteInt32(argumentIndex);
        }
        else
        {
            Throw.ArgumentOutOfRange("argumentIndex");
        }
    }
References System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.Metadata.Ecma335.InstructionEncoder.CodeBuilder, System.Reflection.Metadata.Ecma335.InstructionEncoder.OpCode(), System.Reflection.Metadata.BlobBuilder.WriteByte(), and System.Reflection.Metadata.BlobBuilder.WriteInt32().