Terraria: System.Reflection.Metadata.Ecma335.InstructionEncoder.Branch
Branch()
void System.Reflection.Metadata.Ecma335.InstructionEncoder.Branch (ILOpCode code, LabelHandle label) inline
Definition at line 310 of file InstructionEncoder.cs.
    {
        int branchOperandSize = code.GetBranchOperandSize();
        GetBranchBuilder().AddBranch(Offset, label, code);
        OpCode(code);
        if (branchOperandSize == 1)
        {
            CodeBuilder.WriteSByte(-1);
        }
        else
        {
            CodeBuilder.WriteInt32(-1);
        }
    }
References System.Reflection.Metadata.Ecma335.ControlFlowBuilder.AddBranch(), System.Reflection.Metadata.Ecma335.InstructionEncoder.CodeBuilder, System.Reflection.Metadata.Ecma335.InstructionEncoder.GetBranchBuilder(), System.Reflection.Metadata.Ecma335.InstructionEncoder.Offset, System.Reflection.Metadata.Ecma335.InstructionEncoder.OpCode(), System.Reflection.Metadata.BlobBuilder.WriteInt32(), and System.Reflection.Metadata.BlobBuilder.WriteSByte().