Terraria: System.Reflection.Metadata.Ecma335.InstructionEncoder.OpCode
OpCode()
void System.Reflection.Metadata.Ecma335.InstructionEncoder.OpCode (ILOpCode code) inline
Definition at line 21 of file InstructionEncoder.cs.
    {
        if ((uint)(byte)code == (uint)code)
        {
            CodeBuilder.WriteByte((byte)code);
        }
        else
        {
            CodeBuilder.WriteUInt16BE((ushort)code);
        }
    }
References System.Reflection.Metadata.Ecma335.InstructionEncoder.CodeBuilder, System.Reflection.Metadata.BlobBuilder.WriteByte(), and System.Reflection.Metadata.BlobBuilder.WriteUInt16BE().
Referenced by System.Reflection.Metadata.Ecma335.InstructionEncoder.Branch(), System.Reflection.Metadata.Ecma335.InstructionEncoder.Call(), System.Reflection.Metadata.Ecma335.InstructionEncoder.Call(), System.Reflection.Metadata.Ecma335.InstructionEncoder.Call(), System.Reflection.Metadata.Ecma335.InstructionEncoder.Call(), System.Reflection.Metadata.Ecma335.InstructionEncoder.CallIndirect(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadArgument(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadArgumentAddress(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadConstantI4(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadConstantI8(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadConstantR4(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadConstantR8(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadLocal(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadLocalAddress(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadString(), System.Reflection.Metadata.Ecma335.InstructionEncoder.StoreArgument(), and System.Reflection.Metadata.Ecma335.InstructionEncoder.StoreLocal().