Terraria: System.Linq.Expressions.DebugViewWriter.VisitExpressions< T >
VisitExpressions< T >() [2/3]
void System.Linq.Expressions.DebugViewWriter.VisitExpressions< T > (char open, char separator, IReadOnlyList< T > expressions, Action< T > visit) inline private
Definition at line 215 of file DebugViewWriter.cs.
    {
        Out(open.ToString());
        if (expressions != null)
        {
            Indent();
            bool flag = true;
            foreach (T expression in expressions)
            {
                if (flag)
                {
                    if (open == '{' || expressions.Count > 1)
                    {
                        NewLine();
                    }
                    flag = false;
                }
                else
                {
                    Out(separator.ToString(), Flow.NewLine);
                }
                visit(expression);
            }
            Dedent();
        }
        char c = open switch
        {
            '(' => ')',
            '{' => '}',
            '[' => ']',
            _ => throw ContractUtils.Unreachable,
        };
        if (open == '{')
        {
            NewLine();
        }
        Out(c.ToString(), Flow.Break);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.DebugViewWriter.Dedent(), System.Linq.Expressions.DebugViewWriter.Indent(), System.Linq.Expressions.DebugViewWriter.NewLine(), System.Reflection.Out, and System.Dynamic.Utils.ContractUtils.Unreachable.