Terraria: System.Linq.Expressions.DebugViewWriter.VisitConditional
VisitConditional()
override Expression System.Linq.Expressions.DebugViewWriter.VisitConditional (ConditionalExpression node) inline package virtual
Reimplemented from System.Linq.Expressions.ExpressionVisitor.
Definition at line 454 of file DebugViewWriter.cs.
    {
        if (IsSimpleExpression(node.Test))
        {
            Out(".If (");
            Visit(node.Test);
            Out(") {", Flow.NewLine);
        }
        else
        {
            Out(".If (", Flow.NewLine);
            Indent();
            Visit(node.Test);
            Dedent();
            Out(Flow.NewLine, ") {", Flow.NewLine);
        }
        Indent();
        Visit(node.IfTrue);
        Dedent();
        Out(Flow.NewLine, "} .Else {", Flow.NewLine);
        Indent();
        Visit(node.IfFalse);
        Dedent();
        Out(Flow.NewLine, "}");
        return node;
    }
References System.Linq.Expressions.DebugViewWriter.Dedent(), System.Linq.Expressions.DebugViewWriter.Indent(), System.Linq.Expressions.DebugViewWriter.IsSimpleExpression(), System.Reflection.Out, and System.Linq.Expressions.ExpressionVisitor.Visit().