Terraria: System.Linq.Expressions.DebugViewWriter.VisitBinary
VisitBinary()
override Expression System.Linq.Expressions.DebugViewWriter.VisitBinary (BinaryExpression node) inline package virtual
Reimplemented from System.Linq.Expressions.ExpressionVisitor.
Definition at line 254 of file DebugViewWriter.cs.
    {
        if (node.NodeType == ExpressionType.ArrayIndex)
        {
            ParenthesizedVisit(node, node.Left);
            Out("[");
            Visit(node.Right);
            Out("]");
        }
        else
        {
            bool flag = NeedsParentheses(node, node.Left);
            bool flag2 = NeedsParentheses(node, node.Right);
            Flow before = Flow.Space;
            string s;
            switch (node.NodeType)
            {
            case ExpressionType.Assign:
                s = "=";
                break;
            case ExpressionType.Equal:
                s = "==";
                break;
            case ExpressionType.NotEqual:
                s = "!=";
                break;
            case ExpressionType.AndAlso:
                s = "&&";
                before = Flow.Space | Flow.Break;
                break;
            case ExpressionType.OrElse:
                s = "||";
                before = Flow.Space | Flow.Break;
                break;
            case ExpressionType.GreaterThan:
                s = ">";
                break;
            case ExpressionType.LessThan:
                s = "<";
                break;
            case ExpressionType.GreaterThanOrEqual:
                s = ">=";
                break;
            case ExpressionType.LessThanOrEqual:
                s = "<=";
                break;
            case ExpressionType.Add:
                s = "+";
                break;
            case ExpressionType.AddAssign:
                s = "+=";
                break;
            case ExpressionType.AddAssignChecked:
                s = "#+=";
                break;
            case ExpressionType.AddChecked:
                s = "#+";
                break;
            case ExpressionType.Subtract:
                s = "-";
                break;
            case ExpressionType.SubtractAssign:
                s = "-=";
                break;
            case ExpressionType.SubtractAssignChecked:
                s = "#-=";
                break;
            case ExpressionType.SubtractChecked:
                s = "#-";
                break;
            case ExpressionType.Divide:
                s = "/";
                break;
            case ExpressionType.DivideAssign:
                s = "/=";
                break;
            case ExpressionType.Modulo:
                s = "%";
                break;
            case ExpressionType.ModuloAssign:
                s = "%=";
                break;
            case ExpressionType.Multiply:
                s = "*";
                break;
            case ExpressionType.MultiplyAssign:
                s = "*=";
                break;
            case ExpressionType.MultiplyAssignChecked:
                s = "#*=";
                break;
            case ExpressionType.MultiplyChecked:
                s = "#*";
                break;
            case ExpressionType.LeftShift:
                s = "<<";
                break;
            case ExpressionType.LeftShiftAssign:
                s = "<<=";
                break;
            case ExpressionType.RightShift:
                s = ">>";
                break;
            case ExpressionType.RightShiftAssign:
                s = ">>=";
                break;
            case ExpressionType.And:
                s = "&";
                break;
            case ExpressionType.AndAssign:
                s = "&=";
                break;
            case ExpressionType.Or:
                s = "|";
                break;
            case ExpressionType.OrAssign:
                s = "|=";
                break;
            case ExpressionType.ExclusiveOr:
                s = "^";
                break;
            case ExpressionType.ExclusiveOrAssign:
                s = "^=";
                break;
            case ExpressionType.Power:
                s = "**";
                break;
            case ExpressionType.PowerAssign:
                s = "**=";
                break;
            case ExpressionType.Coalesce:
                s = "??";
                break;
            default:
                throw new InvalidOperationException();
            }
            if (flag)
            {
                Out("(", Flow.None);
            }
            Visit(node.Left);
            if (flag)
            {
                Out(Flow.None, ")", Flow.Break);
            }
            Out(before, s, Flow.Space | Flow.Break);
            if (flag2)
            {
                Out("(", Flow.None);
            }
            Visit(node.Right);
            if (flag2)
            {
                Out(Flow.None, ")", Flow.Break);
            }
        }
        return node;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.Expressions.DebugViewWriter.NeedsParentheses(), System.Reflection.Out, System.Linq.Expressions.DebugViewWriter.ParenthesizedVisit(), System.s, and System.Linq.Expressions.ExpressionVisitor.Visit().