Terraria: System.Linq.Expressions.DebugViewWriter.VisitLoop
VisitLoop()
override Expression System.Linq.Expressions.DebugViewWriter.VisitLoop (LoopExpression node) inline package virtual
Reimplemented from System.Linq.Expressions.ExpressionVisitor.
Definition at line 970 of file DebugViewWriter.cs.
    {
        Out(".Loop", Flow.Space);
        if (node.ContinueLabel != null)
        {
            DumpLabel(node.ContinueLabel);
        }
        Out(" {", Flow.NewLine);
        Indent();
        Visit(node.Body);
        Dedent();
        Out(Flow.NewLine, "}");
        if (node.BreakLabel != null)
        {
            Out("", Flow.NewLine);
            DumpLabel(node.BreakLabel);
        }
        return node;
    }
References System.Linq.Expressions.DebugViewWriter.Dedent(), System.Linq.Expressions.DebugViewWriter.DumpLabel(), System.Linq.Expressions.DebugViewWriter.Indent(), System.Reflection.Out, and System.Linq.Expressions.ExpressionVisitor.Visit().