Terraria: System.Linq.Expressions.DebugViewWriter.ParenthesizedVisit
ParenthesizedVisit()
void System.Linq.Expressions.DebugViewWriter.ParenthesizedVisit (Expression parent, Expression nodeToVisit) inline private
Definition at line 714 of file DebugViewWriter.cs.
    {
        if (NeedsParentheses(parent, nodeToVisit))
        {
            Out("(");
            Visit(nodeToVisit);
            Out(")");
        }
        else
        {
            Visit(nodeToVisit);
        }
    }
References System.Linq.Expressions.DebugViewWriter.NeedsParentheses(), System.Reflection.Out, and System.Linq.Expressions.ExpressionVisitor.Visit().
Referenced by System.Linq.Expressions.DebugViewWriter.OutMember(), System.Linq.Expressions.DebugViewWriter.VisitBinary(), System.Linq.Expressions.DebugViewWriter.VisitIndex(), System.Linq.Expressions.DebugViewWriter.VisitInvocation(), System.Linq.Expressions.DebugViewWriter.VisitMethodCall(), System.Linq.Expressions.DebugViewWriter.VisitTypeBinary(), and System.Linq.Expressions.DebugViewWriter.VisitUnary().