Terraria: System.Linq.Expressions.DebugViewWriter.GetFlow
GetFlow()
Flow System.Linq.Expressions.DebugViewWriter.GetFlow (Flow flow) inline private
Definition at line 172 of file DebugViewWriter.cs.
    {
        Flow val = CheckBreak(_flow);
        flow = CheckBreak(flow);
        return (Flow)Math.Max((int)val, (int)flow);
    }
References System.Linq.Expressions.DebugViewWriter._flow, System.Linq.Expressions.DebugViewWriter.CheckBreak(), and System.Math.Max().
Referenced by System.Linq.Expressions.DebugViewWriter.Out().