Terraria: CustomCurrencyManager.BuyItem
BuyItem()
static bool CustomCurrencyManager.BuyItem (Player player, long price, int currencyIndex) inline static
     {
         CustomCurrencySystem customCurrencySystem = _currencies[currencyIndex];
         bool overFlowing;
         long num = customCurrencySystem.CountCurrency(out overFlowing, player.inventory, 58, 57, 56, 55, 54);
         long num2 = customCurrencySystem.CountCurrency(out overFlowing, player.bank.item);
         long num3 = customCurrencySystem.CountCurrency(out overFlowing, player.bank2.item);
         long num4 = customCurrencySystem.CountCurrency(out overFlowing, player.bank3.item);
         long num5 = customCurrencySystem.CountCurrency(out overFlowing, player.bank4.item);
         if (customCurrencySystem.CombineStacks(out overFlowing, num, num2, num3, num4, num5) < price)
         {
             return false;
         }
         List<Item[]> list = new List<Item[]>();
         Dictionary<int, List<int>> dictionary = new Dictionary<int, List<int>>();
         List<Point> list2 = new List<Point>();
         List<Point> list3 = new List<Point>();
         List<Point> list4 = new List<Point>();
         List<Point> list5 = new List<Point>();
         List<Point> list6 = new List<Point>();
         List<Point> list7 = new List<Point>();
         list.Add(player.inventory);
         list.Add(player.bank.item);
         list.Add(player.bank2.item);
         list.Add(player.bank3.item);
         list.Add(player.bank4.item);
         for (int i = 0; i < list.Count; i++)
         {
             dictionary[i] = new List<int>();
         }
         dictionary[0] = new List<int> { 58, 57, 56, 55, 54 };
         for (int j = 0; j < list.Count; j++)
         {
             for (int k = 0; k < list[j].Length; k++)
             {
                 if (!dictionary[j].Contains(k) && customCurrencySystem.Accepts(list[j][k]))
                 {
                     list3.Add(new Point(j, k));
                 }
             }
         }
         FindEmptySlots(list, dictionary, list2, 0);
         FindEmptySlots(list, dictionary, list4, 1);
         FindEmptySlots(list, dictionary, list5, 2);
         FindEmptySlots(list, dictionary, list6, 3);
         FindEmptySlots(list, dictionary, list7, 4);
         if (!customCurrencySystem.TryPurchasing(price, list, list3, list2, list4, list5, list6, list7))
         {
             return false;
         }
         return true;
     }
References _currencies, CustomCurrencySystem.Accepts(), Player.bank, Player.bank2, Player.bank3, Player.bank4, CustomCurrencySystem.CombineStacks(), CustomCurrencySystem.CountCurrency(), FindEmptySlots(), Player.inventory, Chest.item, and CustomCurrencySystem.TryPurchasing().
Referenced by Player.BuyItem().