Terraria: CustomCurrencyManager.DrawSavings
DrawSavings()
static void CustomCurrencyManager.DrawSavings (SpriteBatch sb, int currencyIndex, float shopx, float shopy, bool horizontal = false) inline static
     {
         CustomCurrencySystem customCurrencySystem = _currencies[currencyIndex];
         Player player = Main.player[Main.myPlayer];
         bool overFlowing;
         long num = customCurrencySystem.CountCurrency(out overFlowing, player.bank.item);
         long num2 = customCurrencySystem.CountCurrency(out overFlowing, player.bank2.item);
         long num3 = customCurrencySystem.CountCurrency(out overFlowing, player.bank3.item);
         long num4 = customCurrencySystem.CountCurrency(out overFlowing, player.bank4.item);
         long num5 = customCurrencySystem.CombineStacks(out overFlowing, num, num2, num3, num4);
         if (num5 > 0)
         {
             Main.GetItemDrawFrame(4076, out var itemTexture, out var itemFrame);
             Main.GetItemDrawFrame(3813, out var itemTexture2, out var itemFrame2);
             Main.GetItemDrawFrame(346, out var itemTexture3, out var itemFrame3);
             Main.GetItemDrawFrame(87, out var itemTexture4, out var itemFrame4);
             if (num4 > 0)
             {
                 sb.Draw(itemTexture, Utils.CenteredRectangle(new Vector2(shopx + 96f, shopy + 50f), itemFrame.Size() * 0.65f), null, Color.White);
             }
             if (num3 > 0)
             {
                 sb.Draw(itemTexture2, Utils.CenteredRectangle(new Vector2(shopx + 80f, shopy + 50f), itemFrame2.Size() * 0.65f), null, Color.White);
             }
             if (num2 > 0)
             {
                 sb.Draw(itemTexture3, Utils.CenteredRectangle(new Vector2(shopx + 80f, shopy + 50f), itemFrame3.Size() * 0.65f), null, Color.White);
             }
             if (num > 0)
             {
                 sb.Draw(itemTexture4, Utils.CenteredRectangle(new Vector2(shopx + 70f, shopy + 60f), itemFrame4.Size() * 0.65f), null, Color.White);
             }
             Utils.DrawBorderStringFourWay(sb, FontAssets.MouseText.Value, Lang.inter[66].Value, shopx, shopy + 40f, Color.White * ((float)(int)Main.mouseTextColor / 255f), Color.Black, Vector2.Zero);
             customCurrencySystem.DrawSavingsMoney(sb, Lang.inter[66].Value, shopx, shopy, num5, horizontal);
         }
     }
References _currencies, Player.bank, Player.bank2, Player.bank3, Player.bank4, Utils.CenteredRectangle(), Color, CustomCurrencySystem.CombineStacks(), CustomCurrencySystem.CountCurrency(), Utils.DrawBorderStringFourWay(), CustomCurrencySystem.DrawSavingsMoney(), Main.GetItemDrawFrame(), Lang.inter, Chest.item, FontAssets.MouseText, Main.mouseTextColor, Main.myPlayer, Main.player, Asset< T >.Value, and LocalizedText.Value.
Referenced by ItemSlot.DrawSavings().