Terraria: Interop.crypt32.CertGetNameString
CertGetNameString() [1/2]
static unsafe string Interop.crypt32.CertGetNameString (SafeCertContextHandle certContext, CertNameType certNameType, CertNameFlags certNameFlags, CertNameStringType strType) inline static
Definition at line 51 of file Interop.cs.
        {
            int num = CertGetNameString(certContext, certNameType, certNameFlags, in strType, null, 0);
            if (num == 0)
            {
                throw Marshal.GetLastWin32Error().ToCryptographicException();
            }
            Span<char> span = ((num > 256) ? ((Span<char>)new char[num]) : stackalloc char[num]);
            Span<char> span2 = span;
            fixed (char* pszNameString = &MemoryMarshal.GetReference(span2))
            {
                if (CertGetNameString(certContext, certNameType, certNameFlags, in strType, pszNameString, num) == 0)
                {
                    throw Marshal.GetLastWin32Error().ToCryptographicException();
                }
                return new string(span2.Slice(0, num - 1));
            }
        }
References Interop.crypt32.CertGetNameString(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), and System.Span< T >.Slice().
Referenced by Interop.crypt32.CertGetNameString().