Terraria: System.Xml.XPath.XPathDocument.LoadFromReader
LoadFromReader()
void System.Xml.XPath.XPathDocument.LoadFromReader (XmlReader reader, XmlSpace space) inline package
Definition at line 119 of file XPathDocument.cs.
    {
        if (reader == null)
        {
            throw new ArgumentNullException("reader");
        }
        IXmlLineInfo xmlLineInfo = reader as IXmlLineInfo;
        if (xmlLineInfo == null || !xmlLineInfo.HasLineInfo())
        {
            xmlLineInfo = null;
        }
        _hasLineInfo = xmlLineInfo != null;
        _nameTable = reader.NameTable;
        XPathDocumentBuilder xPathDocumentBuilder = new XPathDocumentBuilder(this, xmlLineInfo, reader.BaseURI, LoadFlags.None);
        try
        {
            bool flag = reader.ReadState == ReadState.Initial;
            int depth = reader.Depth;
            string text = _nameTable.Get("http://www.w3.org/2000/xmlns/");
            if (flag && !reader.Read())
            {
                return;
            }
            while (flag || reader.Depth >= depth)
            {
                switch (reader.NodeType)
                {
                case XmlNodeType.Element:
                {
                    bool isEmptyElement = reader.IsEmptyElement;
                    xPathDocumentBuilder.WriteStartElement(reader.Prefix, reader.LocalName, reader.NamespaceURI, reader.BaseURI);
                    while (reader.MoveToNextAttribute())
                    {
                        string namespaceURI = reader.NamespaceURI;
                        if ((object)namespaceURI == text)
{
                            if (reader.Prefix.Length == 0)
{
                                xPathDocumentBuilder.WriteNamespaceDeclaration(string.Empty, reader.Value);
                            }
                            else
{
                                xPathDocumentBuilder.WriteNamespaceDeclaration(reader.LocalName, reader.Value);
                            }
                        }
                        else
{
                            xPathDocumentBuilder.WriteStartAttribute(reader.Prefix, reader.LocalName, namespaceURI);
                            xPathDocumentBuilder.WriteString(reader.Value, TextBlockType.Text);
                            xPathDocumentBuilder.WriteEndAttribute();
                        }
                    }
                    if (isEmptyElement)
                    {
                        xPathDocumentBuilder.WriteEndElement(allowShortcutTag: true);
                    }
                    break;
                }
                case XmlNodeType.EndElement:
                    xPathDocumentBuilder.WriteEndElement(allowShortcutTag: false);
                    break;
                case XmlNodeType.Text:
                case XmlNodeType.CDATA:
                    xPathDocumentBuilder.WriteString(reader.Value, TextBlockType.Text);
                    break;
                case XmlNodeType.SignificantWhitespace:
                    if (reader.XmlSpace == XmlSpace.Preserve)
                    {
                        xPathDocumentBuilder.WriteString(reader.Value, TextBlockType.SignificantWhitespace);
                        break;
                    }
                    goto case XmlNodeType.Whitespace;
                case XmlNodeType.Whitespace:
                    if (space == XmlSpace.Preserve && (!flag || reader.Depth != 0))
                    {
                        xPathDocumentBuilder.WriteString(reader.Value, TextBlockType.Whitespace);
                    }
                    break;
                case XmlNodeType.Comment:
                    xPathDocumentBuilder.WriteComment(reader.Value);
                    break;
                case XmlNodeType.ProcessingInstruction:
                    xPathDocumentBuilder.WriteProcessingInstruction(reader.LocalName, reader.Value, reader.BaseURI);
                    break;
                case XmlNodeType.EntityReference:
                    reader.ResolveEntity();
                    break;
                case XmlNodeType.DocumentType:
                {
                    IDtdInfo dtdInfo = reader.DtdInfo;
                    if (dtdInfo != null)
                    {
                        xPathDocumentBuilder.CreateIdTables(dtdInfo);
                    }
                    break;
                }
                }
                if (!reader.Read())
                {
                    break;
                }
            }
        }
        finally
        {
            xPathDocumentBuilder.Close();
        }
    }
References System.Xml.XPath.XPathDocument._hasLineInfo, System.Xml.XPath.XPathDocument._nameTable, System.Xml.XmlReader.BaseURI, System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlReader.DtdInfo, System.Xml.XmlNameTable.Get(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NameTable, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ResolveEntity(), System.text, System.Xml.XmlReader.Value, and System.Xml.XmlReader.XmlSpace.
Referenced by System.Xml.XPath.XPathDocument.XPathDocument(), System.Xml.XPath.XPathDocument.XPathDocument(), System.Xml.XPath.XPathDocument.XPathDocument(), and System.Xml.XPath.XPathDocument.XPathDocument().