Terraria: System.Runtime.Serialization.ObjectDataContract.ReadXmlValue
ReadXmlValue()
override object System.Runtime.Serialization.ObjectDataContract.ReadXmlValue (XmlReaderDelegator reader, XmlObjectSerializerReadContext context) inline virtual
Reimplemented from System.Runtime.Serialization.DataContract.
Definition at line 27 of file ObjectDataContract.cs.
    {
        object obj;
        if (reader.IsEmptyElement)
        {
            reader.Skip();
            obj = new object();
        }
        else
        {
            string localName = reader.LocalName;
            string namespaceURI = reader.NamespaceURI;
            reader.Read();
            try
            {
                reader.ReadEndElement();
                obj = new object();
            }
            catch (XmlException innerException)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.XmlForObjectCannotHaveContent, localName, namespaceURI), innerException));
            }
        }
        if (context != null)
        {
            return HandleReadValue(obj, context);
        }
        return obj;
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.PrimitiveDataContract.HandleReadValue(), System.Runtime.Serialization.XmlReaderDelegator.IsEmptyElement, System.Runtime.Serialization.XmlReaderDelegator.LocalName, System.Runtime.Serialization.XmlReaderDelegator.NamespaceURI, System.obj, System.Runtime.Serialization.XmlReaderDelegator.Read(), System.Runtime.Serialization.XmlReaderDelegator.ReadEndElement(), System.Runtime.Serialization.XmlReaderDelegator.Skip(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.XmlForObjectCannotHaveContent.