Terraria: System.Net.Http.MultipartContent.ContentReadStream.ReadAsyncPrivate
ReadAsyncPrivate()
async ValueTask< int > System.Net.Http.MultipartContent.ContentReadStream.ReadAsyncPrivate (Memory< byte > buffer, CancellationToken cancellationToken) inline
Definition at line 178 of file MultipartContent.cs.
        {
            if (buffer.Length == 0)
            {
                return 0;
            }
            while (true)
            {
                if (_current != null)
                {
                    int num = await _current.ReadAsync(buffer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    if (num != 0)
                    {
                        _position += num;
                        return num;
                    }
                    _current = null;
                }
                if (_next >= _streams.Length)
                {
                    break;
                }
                _current = _streams[_next++];
            }
            return 0;
        }
References System.Net.Http.MultipartContent.ContentReadStream._current, System.Net.Http.MultipartContent.ContentReadStream._next, System.Net.Http.MultipartContent.ContentReadStream._position, System.Net.Http.MultipartContent.ContentReadStream._streams, System.buffer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.Length, and System.IO.Stream.ReadAsync().
Referenced by System.Net.Http.MultipartContent.ContentReadStream.ReadAsync(), and System.Net.Http.MultipartContent.ContentReadStream.ReadAsync().