Terraria: System.Net.Http.MultipartContent.ContentReadStream.ReadAsync
ReadAsync() [2/3]
override Task< int > System.Net.Http.MultipartContent.ContentReadStream.ReadAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 157 of file MultipartContent.cs.
        {
            Stream.ValidateBufferArguments(buffer, offset, count);
            return ReadAsyncPrivate(new Memory<byte>(buffer, offset, count), cancellationToken).AsTask();
        }
References System.buffer, System.cancellationToken, System.count, System.offset, System.Net.Http.MultipartContent.ContentReadStream.ReadAsyncPrivate(), and System.IO.Stream.ValidateBufferArguments().
Referenced by System.Net.Http.MultipartContent.ContentReadStream.BeginRead().