Terraria: System.Runtime.Serialization.XmlSerializableReader.EndRead
EndRead()
void System.Runtime.Serialization.XmlSerializableReader.EndRead () inline package
Definition at line 105 of file XmlSerializableReader.cs.
    {
        if (_isRootEmptyElement)
        {
            _xmlReader.Read();
            return;
        }
        if (_xmlReader.IsStartElement() && _xmlReader.Depth == _startDepth)
        {
            _xmlReader.Read();
        }
        while (_xmlReader.Depth > _startDepth)
        {
            if (!_xmlReader.Read())
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializerReadContext.CreateUnexpectedStateException(XmlNodeType.EndElement, _xmlReader));
            }
        }
    }
References System.Runtime.Serialization.XmlSerializableReader._isRootEmptyElement, System.Runtime.Serialization.XmlSerializableReader._startDepth, System.Runtime.Serialization.XmlSerializableReader._xmlReader, System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateUnexpectedStateException(), System.Runtime.Serialization.XmlReaderDelegator.Depth, System.Runtime.Serialization.XmlReaderDelegator.IsStartElement(), System.Runtime.Serialization.XmlReaderDelegator.Read(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().