Terraria: UIResourcePack.UIResourcePack
UIResourcePack()
UIResourcePack.UIResourcePack (ResourcePack pack, int order) inline
     {
         ResourcePack = pack;
         Order = order;
         BackgroundColor = DefaultBackgroundColor;
         BorderColor = DefaultBorderColor;
         Height = StyleDimension.FromPixels(102f);
         MinHeight = Height;
         MaxHeight = Height;
         MinWidth = StyleDimension.FromPixels(102f);
         Width = StyleDimension.FromPercent(1f);
         SetPadding(5f);
         _iconBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/Achievement_Borders", (AssetRequestMode)1);
         OverflowHidden = true;
         BuildChildren();
     }
References _iconBorderTexture, Main.Assets, UIPanel.BackgroundColor, UIPanel.BorderColor, BuildChildren(), DefaultBackgroundColor, DefaultBorderColor, StyleDimension.FromPercent(), StyleDimension.FromPixels(), UIElement.Height, UIElement.MaxHeight, UIElement.MinHeight, UIElement.MinWidth, Order, UIElement.OverflowHidden, UIElement.SetPadding(), and UIElement.Width.