Terraria: UIResourcePack.BuildChildren
BuildChildren()
void UIResourcePack.BuildChildren () inline private
     {
         StyleDimension left = StyleDimension.FromPixels(77f);
         StyleDimension top = StyleDimension.FromPixels(4f);
         UIText uIText = new UIText(ResourcePack.Name)
         {
             Left = left,
             Top = top
         };
         Append(uIText);
         top.Pixels += uIText.GetOuterDimensions().Height + 6f;
         UIText uIText2 = new UIText(Language.GetTextValue("UI.Author", ResourcePack.Author), 0.7f)
         {
             Left = left,
             Top = top
         };
         Append(uIText2);
         top.Pixels += uIText2.GetOuterDimensions().Height + 10f;
         Asset<Texture2D> val = Main.Assets.Request<Texture2D>("Images/UI/Divider", (AssetRequestMode)1);
         UIImage uIImage = new UIImage(val)
         {
             Left = StyleDimension.FromPixels(72f),
             Top = top,
             Height = StyleDimension.FromPixels(val.Height()),
             Width = StyleDimension.FromPixelsAndPercent(-80f, 1f),
             ScaleToFit = true
         };
         Recalculate();
         Append(uIImage);
         top.Pixels += uIImage.GetOuterDimensions().Height + 5f;
         UIElement uIElement = new UIElement
         {
             Left = left,
             Top = top,
             Height = StyleDimension.FromPixels(92f - top.Pixels),
             Width = StyleDimension.FromPixelsAndPercent(0f - left.Pixels, 1f)
         };
         Append(uIElement);
         ContentPanel = uIElement;
     }
References UIElement.Append(), Main.Assets, ResourcePack.Author, ContentPanel, StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), UIElement.GetOuterDimensions(), Language.GetTextValue(), CalculatedStyle.Height, UIElement.Height, UIElement.Left, ResourcePack.Name, StyleDimension.Pixels, UIElement.Recalculate(), UIElement.Top, and UIElement.Width.
Referenced by UIResourcePack().