Terraria: CaptureInterface.ModeDragBounds.DragBounds
DragBounds()
void CaptureInterface.ModeDragBounds.DragBounds (Vector2 mouse) inline private
         {
             if (!EdgeAPinned || !EdgeBPinned)
             {
                 bool flag = false;
                 if (Main.mouseLeft)
                 {
                     flag = true;
                 }
                 if (flag)
                 {
                     bool flag2 = true;
                     Point result;
                     if (!Main.mapFullscreen)
                     {
                         result = (Main.screenPosition + mouse).ToTileCoordinates();
                     }
                     else
                     {
                         flag2 = GetMapCoords((int)mouse.X, (int)mouse.Y, 0, out result);
                     }
                     if (flag2)
                     {
                         if (!EdgeAPinned)
{
                             EdgeAPinned = true;
                             EdgeA = result;
                         }
                         if (!EdgeBPinned)
{
                             EdgeBPinned = true;
                             EdgeB = result;
                         }
                     }
                     currentAim = 3;
                     caughtEdge = 1;
                 }
             }
             int num = Math.Min(EdgeA.X, EdgeB.X);
             int num2 = Math.Min(EdgeA.Y, EdgeB.Y);
             int num3 = Math.Abs(EdgeA.X - EdgeB.X);
             int num4 = Math.Abs(EdgeA.Y - EdgeB.Y);
             bool value = Main.player[Main.myPlayer].gravDir == -1f;
             int num5 = 1 - value.ToInt();
             int num6 = value.ToInt();
             Rectangle value2;
             Rectangle value3;
             Rectangle result2;
             if (!Main.mapFullscreen)
             {
                 value2 = Main.ReverseGravitySupport(new Rectangle(num * 16, num2 * 16, (num3 + 1) * 16, (num4 + 1) * 16));
                 value3 = Main.ReverseGravitySupport(new Rectangle((int)Main.screenPosition.X, (int)Main.screenPosition.Y, Main.screenWidth + 1, Main.screenHeight + 1));
                 Rectangle.Intersect(ref value3, ref value2, out result2);
                 if (result2.Width == 0 || result2.Height == 0)
                 {
                     return;
                 }
                 result2.Offset(-value3.X, -value3.Y);
             }
             else
             {
                 GetMapCoords(num, num2, 1, out var result3);
                 GetMapCoords(num + num3 + 1, num2 + num4 + 1, 1, out var result4);
                 value2 = new Rectangle(result3.X, result3.Y, result4.X - result3.X, result4.Y - result3.Y);
                 value3 = new Rectangle(0, 0, Main.screenWidth + 1, Main.screenHeight + 1);
                 Rectangle.Intersect(ref value3, ref value2, out result2);
                 if (result2.Width == 0 || result2.Height == 0)
                 {
                     return;
                 }
                 result2.Offset(-value3.X, -value3.Y);
             }
             dragging = false;
             if (!Main.mouseLeft)
             {
                 currentAim = -1;
             }
             if (currentAim != -1)
             {
                 dragging = true;
                 Point point = default(Point);
                 if (!Main.mapFullscreen)
                 {
                     point = Main.MouseWorld.ToTileCoordinates();
                 }
                 else
                 {
                     if (!GetMapCoords((int)mouse.X, (int)mouse.Y, 0, out var result5))
                     {
                         return;
                     }
                     point = result5;
                 }
                 switch (currentAim)
                 {
                 case 0:
                 case 1:
                     if (caughtEdge == 0)
                     {
                         EdgeA.Y = point.Y;
                     }
                     if (caughtEdge == 1)
                     {
                         EdgeB.Y = point.Y;
                     }
                     break;
                 case 2:
                 case 3:
                     if (caughtEdge == 0)
                     {
                         EdgeA.X = point.X;
                     }
                     if (caughtEdge == 1)
                     {
                         EdgeB.X = point.X;
                     }
                     break;
                 }
             }
             else
             {
                 caughtEdge = -1;
                 Rectangle drawbox = value2;
                 drawbox.Offset(-value3.X, -value3.Y);
                 inMap = drawbox.Contains(mouse.ToPoint());
                 for (int i = 0; i < 4; i++)
                 {
                     Rectangle bound = GetBound(drawbox, i);
                     bound.Inflate(8, 8);
                     if (!bound.Contains(mouse.ToPoint()))
                     {
                         continue;
                     }
                     currentAim = i;
                     switch (i)
                     {
                     case 0:
                         if (EdgeA.Y < EdgeB.Y)
{
                             caughtEdge = num6;
                         }
                         else
{
                             caughtEdge = num5;
                         }
                         break;
                     case 1:
                         if (EdgeA.Y >= EdgeB.Y)
{
                             caughtEdge = num6;
                         }
                         else
{
                             caughtEdge = num5;
                         }
                         break;
                     case 2:
                         if (EdgeA.X < EdgeB.X)
{
                             caughtEdge = 0;
                         }
                         else
{
                             caughtEdge = 1;
                         }
                         break;
                     case 3:
                         if (EdgeA.X >= EdgeB.X)
{
                             caughtEdge = 0;
                         }
                         else
{
                             caughtEdge = 1;
                         }
                         break;
                     }
                     break;
                 }
             }
             ConstraintPoints();
         }
References CaptureInterface.ModeDragBounds.caughtEdge, CaptureInterface.ConstraintPoints(), CaptureInterface.ModeDragBounds.currentAim, CaptureInterface.ModeDragBounds.dragging, CaptureInterface.EdgeA, CaptureInterface.EdgeAPinned, CaptureInterface.EdgeB, CaptureInterface.EdgeBPinned, CaptureInterface.ModeDragBounds.GetBound(), CaptureInterface.GetMapCoords(), Player.gravDir, CaptureInterface.ModeDragBounds.inMap, Main.mapFullscreen, Main.mouseLeft, Main.MouseWorld, Main.myPlayer, Main.player, Main.ReverseGravitySupport(), Main.screenHeight, Main.screenPosition, and Main.screenWidth.
Referenced by CaptureInterface.ModeDragBounds.Update().