Terraria: Terraria.GameInput.PlayerInput.SetZoom_Unscaled
SetZoom_Unscaled()
static void Terraria.GameInput.PlayerInput.SetZoom_Unscaled () inline static
Definition at line 2263 of file PlayerInput.cs.
    {
        Main.lastMouseX = _originalLastMouseX;
        Main.lastMouseY = _originalLastMouseY;
        Main.mouseX = _originalMouseX;
        Main.mouseY = _originalMouseY;
        Main.screenWidth = _originalScreenWidth;
        Main.screenHeight = _originalScreenHeight;
    }
References Terraria.GameInput.PlayerInput._originalLastMouseX, Terraria.GameInput.PlayerInput._originalLastMouseY, Terraria.GameInput.PlayerInput._originalMouseX, Terraria.GameInput.PlayerInput._originalMouseY, Terraria.GameInput.PlayerInput._originalScreenHeight, and Terraria.GameInput.PlayerInput._originalScreenWidth.
Referenced by Terraria.Main.DoDraw(), Terraria.Main.DoUpdate(), Terraria.Main.DoUpdate_HandleInput(), Terraria.UI.GameInterfaceLayer.Draw(), Terraria.Main.DrawCapture(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.Main.DrawMap(), Terraria.Main.DrawMouseOver(), Terraria.GameInput.PlayerInput.SetZoom_Context(), and Terraria.Graphics.Capture.CaptureInterface.Update().