Terraria: System.IO.BinaryWriter.WriteCharsCommonWithoutLengthPrefix
WriteCharsCommonWithoutLengthPrefix()
void System.IO.BinaryWriter.WriteCharsCommonWithoutLengthPrefix (ReadOnlySpan< char > chars, bool useThisWriteOverride) inline private inherited
Definition at line 342 of file BinaryWriter.cs.
    {
        byte[] array;
        if (chars.Length <= 65536)
        {
            int maxByteCount = _encoding.GetMaxByteCount(chars.Length);
            if (maxByteCount <= 65536)
            {
                array = ArrayPool<byte>.Shared.Rent(maxByteCount);
                int bytes = _encoding.GetBytes(chars, array);
                WriteToOutStream(array, 0, bytes, useThisWriteOverride);
                ArrayPool<byte>.Shared.Return(array);
                return;
            }
        }
        array = ArrayPool<byte>.Shared.Rent(65536);
        Encoder encoder = _encoding.GetEncoder();
        bool completed;
        do
        {
            encoder.Convert(chars, array, flush: true, out var charsUsed, out var bytesUsed, out completed);
            if (bytesUsed != 0)
            {
                WriteToOutStream(array, 0, bytesUsed, useThisWriteOverride);
            }
            chars = chars.Slice(charsUsed);
        }
        while (!completed);
        ArrayPool<byte>.Shared.Return(array);
        void WriteToOutStream(byte[] buffer, int offset, int count, bool useThisWriteOverride)
        {
            if (useThisWriteOverride)
            {
                Write(buffer, offset, count);
            }
            else
            {
                OutStream.Write(buffer, offset, count);
            }
        }
    }
References System.IO.BinaryWriter._encoding, System.array, System.buffer, System.bytes, System.chars, System.Text.Encoder.Convert(), System.count, System.Text.Encoding.GetBytes(), System.Text.Encoding.GetEncoder(), System.Text.Encoding.GetMaxByteCount(), System.offset, System.IO.BinaryWriter.OutStream, System.Buffers.ArrayPool< T >.Shared, System.IO.Write, and System.IO.Stream.Write().
Referenced by System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), and System.IO.BinaryWriter.Write().