Terraria: System.IO.BinaryWriter.Write
Write() [5/21]
virtual void System.IO.BinaryWriter.Write (char ch) inline virtual inherited
Definition at line 156 of file BinaryWriter.cs.
    {
        if (!Rune.TryCreate(ch, out var result))
        {
            throw new ArgumentException(SR.Arg_SurrogatesNotAllowedAsSingleChar);
        }
        Span<byte> span = stackalloc byte[8];
        if (_useFastUtf8)
        {
            int length = result.EncodeToUtf8(span);
            OutStream.Write(span.Slice(0, length));
            return;
        }
        byte[] array = null;
        int maxByteCount = _encoding.GetMaxByteCount(1);
        if (maxByteCount > span.Length)
        {
            array = ArrayPool<byte>.Shared.Rent(maxByteCount);
            span = array;
        }
        int bytes = _encoding.GetBytes(MemoryMarshal.CreateReadOnlySpan(ref ch, 1), span);
        OutStream.Write(span.Slice(0, bytes));
        if (array != null)
        {
            ArrayPool<byte>.Shared.Return(array);
        }
    }
References System.IO.BinaryWriter._encoding, System.IO.BinaryWriter._useFastUtf8, System.SR.Arg_SurrogatesNotAllowedAsSingleChar, System.array, System.bytes, System.ch, System.Text.Encoding.GetBytes(), System.Text.Encoding.GetMaxByteCount(), System.length, System.Span< T >.Length, System.IO.BinaryWriter.OutStream, System.Buffers.ArrayPool< T >.Shared, System.Span< T >.Slice(), System.Text.Rune.TryCreate(), and System.IO.Stream.Write().