Terraria: Terraria.GameInput.PlayerInput.SetZoom_UI
SetZoom_UI()
static void Terraria.GameInput.PlayerInput.SetZoom_UI () inline static
Definition at line 2251 of file PlayerInput.cs.
    {
        float uIScale = Main.UIScale;
        SetZoom_Scaled(1f / uIScale);
    }
References Terraria.GameInput.PlayerInput.SetZoom_Scaled(), and Terraria.Main.UIScale.
Referenced by Terraria.Main.DoDraw(), Terraria.Main.DoUpdate(), Terraria.Main.DoUpdate_WhilePaused(), Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.Draw(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.Draw(), Terraria.UI.GameInterfaceLayer.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Draw(), Terraria.Graphics.Capture.CaptureInterface.Draw(), Terraria.Main.DrawInterface(), Terraria.Main.DrawInterface_10_CheckCaptureManager(), Terraria.Main.DrawInterface_11_IngameOptionsMenu(), Terraria.Main.DrawInterface_16_MapOrMinimap(), Terraria.Main.DrawMap(), Terraria.UI.AchievementAdvisor.DrawMouseHover(), Terraria.Main.DrawMouseOver(), Terraria.Main.DrawNPCChatBubble(), Terraria.Main.PreDrawMenu(), Terraria.GameInput.PlayerInput.SetZoom_Context(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Update(), Terraria.Graphics.Capture.CaptureInterface.Update(), and Terraria.Player.Update().