Terraria: Terraria.GameInput.PlayerInput.GenerateInputTag_ForCurrentGamemode_WithHacks
GenerateInputTag_ForCurrentGamemode_WithHacks()
static string Terraria.GameInput.PlayerInput.GenerateInputTag_ForCurrentGamemode_WithHacks (bool tagForGameplay, string triggerName) inline static
Definition at line 1660 of file PlayerInput.cs.
    {
        InputMode inputMode = CurrentInputMode;
        if (inputMode == InputMode.Mouse || inputMode == InputMode.KeyboardUI)
        {
            inputMode = InputMode.Keyboard;
        }
        if (!(triggerName == "SmartSelect"))
        {
            if (triggerName == "SmartCursor" && inputMode == InputMode.Keyboard)
            {
                return GenerateRawInputList(new List<string> { Keys.LeftAlt.ToString() });
            }
        }
        else if (inputMode == InputMode.Keyboard)
        {
            return GenerateRawInputList(new List<string> { Keys.LeftControl.ToString() });
        }
        return GenerateInputTag_ForCurrentGamemode(tagForGameplay, triggerName);
    }
References Terraria.GameInput.PlayerInput.CurrentInputMode, Terraria.GameInput.PlayerInput.GenerateInputTag_ForCurrentGamemode(), and Terraria.GameInput.PlayerInput.GenerateRawInputList().
Referenced by Terraria.Lang.CreateDialogSubstitutionObject().