Terraria: Terraria.GameInput.PlayerInput.SetSelectedProfile
SetSelectedProfile()
static void Terraria.GameInput.PlayerInput.SetSelectedProfile (string name) inline static
Definition at line 519 of file PlayerInput.cs.
    {
        if (Profiles.ContainsKey(name))
        {
            _selectedProfile = name;
            _currentProfile = Profiles[_selectedProfile];
        }
    }
References Terraria.GameInput.PlayerInput._currentProfile, and Terraria.GameInput.PlayerInput._selectedProfile.
Referenced by Terraria.GameInput.PlayerInput.Initialize(), Terraria.GameInput.PlayerInput.Load(), and Terraria.GameContent.UI.States.UIManageControls.profileButtonClick().