Terraria: Terraria.GameInput.PlayerInput.ExitBuildingMode
ExitBuildingMode()
static void Terraria.GameInput.PlayerInput.ExitBuildingMode () inline static
Definition at line 482 of file PlayerInput.cs.
    {
        SoundEngine.PlaySound(11);
        _InBuildingMode = false;
        UILinkPointNavigator.ChangePoint(_UIPointForBuildingMode);
        if (Main.mouseItem.stack > 0 && Main.player[Main.myPlayer].itemAnimation == 0)
        {
            int uIPointForBuildingMode = _UIPointForBuildingMode;
            if (uIPointForBuildingMode < 50 && uIPointForBuildingMode >= 0 && Main.player[Main.myPlayer].inventory[uIPointForBuildingMode].stack <= 0)
            {
                Utils.Swap(ref Main.mouseItem, ref Main.player[Main.myPlayer].inventory[uIPointForBuildingMode]);
            }
        }
        _UIPointForBuildingMode = -1;
    }
References Terraria.GameInput.PlayerInput._InBuildingMode, Terraria.GameInput.PlayerInput._UIPointForBuildingMode, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.Main.player, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.Player.ToggleCreativeMenu(), Terraria.Player.ToggleInv(), Terraria.GameInput.PlayerInput.UpdateInput(), and Terraria.GameInput.PlayerInput.VerifyBuildingMode().