Terraria: System.IO.BinaryWriter.Write
Write() [1/21]
virtual void System.IO.BinaryWriter.Write (bool value) inline virtual inherited
Definition at line 126 of file BinaryWriter.cs.
    {
        OutStream.WriteByte((byte)(value ? 1u : 0u));
    }
References System.IO.BinaryWriter.OutStream, System.value, and System.IO.Stream.WriteByte().
Referenced by System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder(), Terraria.NetMessage.CompressTileBlock(), Internal.Cryptography.Pal.X509Pal.ConstructDSSPublicKeyCspBlob(), Terraria.GameContent.NetModules.NetCreativePowersModule.PreparePacket(), Terraria.GameContent.NetModules.NetLiquidModule.Serialize(), Terraria.GameContent.NetModules.NetParticlesModule.Serialize(), System.ComponentModel.Design.DesigntimeLicenseContextSerializer.Serialize(), Terraria.GameContent.NetModules.NetBestiaryModule.SerializeChat(), Terraria.GameContent.NetModules.NetCreativePowerPermissionsModule.SerializeCurrentPowerPermissionLevel(), Terraria.GameContent.NetModules.NetLiquidModule.SerializeForPlayer(), Terraria.GameContent.NetModules.NetCreativeUnlocksModule.SerializeItemSacrifice(), Terraria.GameContent.NetModules.NetBestiaryModule.SerializeKillCount(), Terraria.GameContent.NetModules.NetTeleportPylonModule.SerializePylonWasAddedOrRemoved(), Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(), Terraria.GameContent.NetModules.NetTextModule.SerializeServerMessage(), Terraria.GameContent.NetModules.NetBestiaryModule.SerializeSight(), Terraria.GameContent.NetModules.NetAmbienceModule.SerializeSkyEntitySpawn(), Terraria.GameContent.NetModules.NetTeleportPylonModule.SerializeUseRequest(), Internal.NativeCrypto.CapiHelper.ToKeyBlob(), System.IO.Compression.Zip64EndOfCentralDirectoryRecord.WriteBlock(), System.IO.Compression.ZipEndOfCentralDirectoryBlock.WriteBlock(), System.IO.Compression.Zip64EndOfCentralDirectoryLocator.WriteBlock(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteBoolean(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteByte(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteBytes(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteBytes(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteChar(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteChars(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteDouble(), Internal.NativeCrypto.CapiHelper.WriteDSSSeed(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteInt16(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteInt32(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteInt64(), Internal.NativeCrypto.CapiHelper.WriteKeyBlobHeader(), Internal.NativeCrypto.CapiHelper.WriteKeyBlobHeader(), Internal.NativeCrypto.CapiHelper.WriteReversed(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteSingle(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteString(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteUInt16(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteUInt32(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteUInt64().