Terraria: Terraria.GameInput.PlayerInput.Initialize
Initialize()
static void Terraria.GameInput.PlayerInput.Initialize () inline static
    {
        Main.InputProfiles.OnProcessText += PrettyPrintProfiles;
        Player.Hooks.OnEnterWorld += Hook_OnEnterWorld;
        PlayerInputProfile playerInputProfile = new PlayerInputProfile("Redigit's Pick");
        playerInputProfile.Initialize(PresetProfiles.Redigit);
        Profiles.Add(playerInputProfile.Name, playerInputProfile);
        playerInputProfile = new PlayerInputProfile("Yoraiz0r's Pick");
        playerInputProfile.Initialize(PresetProfiles.Yoraiz0r);
        Profiles.Add(playerInputProfile.Name, playerInputProfile);
        playerInputProfile = new PlayerInputProfile("Console (Playstation)");
        playerInputProfile.Initialize(PresetProfiles.ConsolePS);
        Profiles.Add(playerInputProfile.Name, playerInputProfile);
        playerInputProfile = new PlayerInputProfile("Console (Xbox)");
        playerInputProfile.Initialize(PresetProfiles.ConsoleXBox);
        Profiles.Add(playerInputProfile.Name, playerInputProfile);
        playerInputProfile = new PlayerInputProfile("Custom");
        playerInputProfile.Initialize(PresetProfiles.Redigit);
        Profiles.Add(playerInputProfile.Name, playerInputProfile);
        playerInputProfile = new PlayerInputProfile("Redigit's Pick");
        playerInputProfile.Initialize(PresetProfiles.Redigit);
        OriginalProfiles.Add(playerInputProfile.Name, playerInputProfile);
        playerInputProfile = new PlayerInputProfile("Yoraiz0r's Pick");
        playerInputProfile.Initialize(PresetProfiles.Yoraiz0r);
        OriginalProfiles.Add(playerInputProfile.Name, playerInputProfile);
        playerInputProfile = new PlayerInputProfile("Console (Playstation)");
        playerInputProfile.Initialize(PresetProfiles.ConsolePS);
        OriginalProfiles.Add(playerInputProfile.Name, playerInputProfile);
        playerInputProfile = new PlayerInputProfile("Console (Xbox)");
        playerInputProfile.Initialize(PresetProfiles.ConsoleXBox);
        OriginalProfiles.Add(playerInputProfile.Name, playerInputProfile);
        SetSelectedProfile("Custom");
        Triggers.Initialize();
    }
References Terraria.GameInput.PlayerInput.Hook_OnEnterWorld(), Terraria.GameInput.TriggersPack.Initialize(), Terraria.GameInput.PlayerInputProfile.Initialize(), Terraria.GameInput.PlayerInputProfile.Name, Terraria.GameInput.PlayerInput.OriginalProfiles, Terraria.GameInput.PlayerInput.PrettyPrintProfiles(), Terraria.GameInput.PlayerInput.SetSelectedProfile(), and Terraria.GameInput.PlayerInput.Triggers.
Referenced by Terraria.Main.Initialize().