Terraria: Terraria.GameInput.PlayerInput.OriginalProfiles
OriginalProfiles
Dictionary<string, PlayerInputProfile> Terraria.GameInput.PlayerInput.OriginalProfiles = new Dictionary<string, PlayerInputProfile>() static
Definition at line 218 of file PlayerInput.cs.
Referenced by Terraria.GameInput.PlayerInputProfile.ConditionalAdd(), Terraria.GameInput.PlayerInputProfile.ConditionalAddProfile(), Terraria.GameContent.UI.States.UIManageControls.CreatePanel(), Terraria.GameContent.UI.States.UIManageControls.GetCopyableProfileName(), Terraria.GameInput.PlayerInput.Initialize(), Terraria.GameInput.PlayerInputProfile.Load(), and Terraria.GameInput.PlayerInput.ResetKeyBinding().