Terraria: System.Globalization.NumberFormatInfo.GetFormat
GetFormat()
object? System.Globalization.NumberFormatInfo.GetFormat (Type? formatType) inline
Implements System.IFormatProvider.
Definition at line 704 of file NumberFormatInfo.cs.
    {
        if (!(formatType == typeof(NumberFormatInfo)))
        {
            return null;
        }
        return this;
    }
Referenced by System.ComponentModel.BaseNumberConverter.ConvertFrom(), System.ComponentModel.BaseNumberConverter.ConvertTo(), and System.Drawing.ColorConverterCommon.IntFromString().