Terraria: Terraria.GameInput.PlayerInput.GenerateInputTag_ForCurrentGamemode
GenerateInputTag_ForCurrentGamemode()
static string Terraria.GameInput.PlayerInput.GenerateInputTag_ForCurrentGamemode (bool tagForGameplay, string triggerName) inline static
Definition at line 1681 of file PlayerInput.cs.
    {
        InputMode inputMode = CurrentInputMode;
        if (inputMode == InputMode.Mouse || inputMode == InputMode.KeyboardUI)
        {
            inputMode = InputMode.Keyboard;
        }
        if (tagForGameplay)
        {
            if ((uint)(inputMode - 3) > 1u)
            {
                return GenerateRawInputList(CurrentProfile.InputModes[inputMode].KeyStatus[triggerName]);
            }
            return GenerateGlyphList(CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus[triggerName]);
        }
        if ((uint)(inputMode - 3) > 1u)
        {
            return GenerateRawInputList(CurrentProfile.InputModes[inputMode].KeyStatus[triggerName]);
        }
        return GenerateGlyphList(CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus[triggerName]);
    }
References Terraria.GameInput.PlayerInput.CurrentInputMode, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameInput.PlayerInput.GenerateGlyphList(), and Terraria.GameInput.PlayerInput.GenerateRawInputList().
Referenced by Terraria.Lang.CreateDialogSubstitutionObject(), Terraria.GameInput.PlayerInput.GenerateInputTag_ForCurrentGamemode_WithHacks(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateHelpGlyphs().