Terraria: Terraria.GameInput.PlayerInput.BuildCommand
BuildCommand()
static string Terraria.GameInput.PlayerInput.BuildCommand (string CommandText, bool Last, params List< string >[] Bindings) inline static
Definition at line 1633 of file PlayerInput.cs.
    {
        string text = "";
        if (Bindings.Length == 0)
        {
            return text;
        }
        text += GenerateGlyphList(Bindings[0]);
        for (int i = 1; i < Bindings.Length; i++)
        {
            string text2 = GenerateGlyphList(Bindings[i]);
            if (text2.Length > 0)
            {
                text = text + "/" + text2;
            }
        }
        if (text.Length > 0)
        {
            text = text + ": " + CommandText;
            if (!Last)
            {
                text += "   ";
            }
        }
        return text;
    }
References Terraria.GameInput.PlayerInput.GenerateGlyphList(), and System.text.
Referenced by Terraria.GameInput.PlayerInput.ComposeInstructionsForGamepad(), Terraria.Initializers.UILinksInitializer.FancyUISpecialInstructions(), Terraria.UI.ItemSlot.GetGamepadInstructions(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.Lang.SupportGlyphs(), Terraria.UI.ItemSlot.TryEnteringBuildingMode(), and Terraria.UI.ItemSlot.TryEnteringFastUseMode().