Terraria: Terraria.GameInput.PlayerInput.SetZoom_Context
SetZoom_Context()
static void Terraria.GameInput.PlayerInput.SetZoom_Context () inline static
Definition at line 2319 of file PlayerInput.cs.
    {
        switch (_currentWantedZoom)
        {
        case ZoomContext.Unscaled:
            SetZoom_Unscaled();
            Main.SetRecommendedZoomContext(Matrix.Identity);
            break;
        case ZoomContext.Unscaled_MouseInWorld:
            SetZoom_Unscaled();
            SetZoom_MouseInWorld();
            Main.SetRecommendedZoomContext(Main.GameViewMatrix.ZoomMatrix);
            break;
        case ZoomContext.UI:
            SetZoom_UI();
            Main.SetRecommendedZoomContext(Main.UIScaleMatrix);
            break;
        case ZoomContext.World:
            SetZoom_World();
            Main.SetRecommendedZoomContext(Main.GameViewMatrix.ZoomMatrix);
            break;
        }
    }
References Terraria.GameInput.PlayerInput._currentWantedZoom, Terraria.Main.GameViewMatrix, Terraria.Main.SetRecommendedZoomContext(), Terraria.GameInput.PlayerInput.SetZoom_MouseInWorld(), Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_Unscaled(), Terraria.GameInput.PlayerInput.SetZoom_World(), and Terraria.Main.UIScaleMatrix.
Referenced by Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.Update(), and Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.Update().