Terraria: Terraria.GameInput.PlayerInput.CheckRebindingProcessKeyboard
CheckRebindingProcessKeyboard()
static bool Terraria.GameInput.PlayerInput.CheckRebindingProcessKeyboard (string newKey) inline static private
    {
        _canReleaseRebindingLock = false;
        if (CurrentlyRebinding && _listeningInputMode == InputMode.Keyboard)
        {
            NavigatorRebindingLock = 3;
            _memoOfLastPoint = UILinkPointNavigator.CurrentPoint;
            SoundEngine.PlaySound(12);
            if (CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus[ListeningTrigger].Contains(newKey))
            {
                CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus[ListeningTrigger].Remove(newKey);
            }
            else
            {
                CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus[ListeningTrigger] = new List<string> { newKey };
            }
            ListenFor(null, InputMode.Keyboard);
            Main.blockKey = newKey;
            Main.blockInput = false;
            Main.ChromaPainter.CollectBoundKeys();
        }
        if (CurrentlyRebinding && _listeningInputMode == InputMode.KeyboardUI)
        {
            NavigatorRebindingLock = 3;
            _memoOfLastPoint = UILinkPointNavigator.CurrentPoint;
            SoundEngine.PlaySound(12);
            if (CurrentProfile.InputModes[InputMode.KeyboardUI].KeyStatus[ListeningTrigger].Contains(newKey))
            {
                CurrentProfile.InputModes[InputMode.KeyboardUI].KeyStatus[ListeningTrigger].Remove(newKey);
            }
            else
            {
                CurrentProfile.InputModes[InputMode.KeyboardUI].KeyStatus[ListeningTrigger] = new List<string> { newKey };
            }
            ListenFor(null, InputMode.KeyboardUI);
            Main.blockKey = newKey;
            Main.blockInput = false;
            Main.ChromaPainter.CollectBoundKeys();
        }
        FixDerpedRebinds();
        if (PlayerInput.OnBindingChange != null)
        {
            PlayerInput.OnBindingChange();
        }
        return NavigatorRebindingLock > 0;
    }
References Terraria.GameInput.PlayerInput._canReleaseRebindingLock, Terraria.GameInput.PlayerInput._listeningInputMode, Terraria.GameInput.PlayerInput._memoOfLastPoint, Terraria.Main.ChromaPainter, Terraria.GameInput.PlayerInput.CurrentlyRebinding, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameInput.PlayerInput.FixDerpedRebinds(), Terraria.GameInput.PlayerInputProfile.InputModes, Terraria.GameInput.PlayerInput.ListenFor(), Terraria.GameInput.PlayerInput.ListeningTrigger, Terraria.GameInput.PlayerInput.NavigatorRebindingLock, Terraria.GameInput.PlayerInput.OnBindingChange, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.GameInput.PlayerInput.KeyboardInput().