Terraria: System.IO.BinaryWriter.Write
Write() [18/21]
virtual void System.IO.BinaryWriter.Write (string value) inline virtual inherited
Definition at line 287 of file BinaryWriter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (_useFastUtf8)
        {
            if (value.Length <= 42)
            {
                Span<byte> span = stackalloc byte[128];
                int bytes = _encoding.GetBytes(value, span.Slice(1));
                span[0] = (byte)bytes;
                OutStream.Write(span.Slice(0, bytes + 1));
                return;
            }
            if (value.Length <= 21845)
            {
                byte[] array = ArrayPool<byte>.Shared.Rent(value.Length * 3);
                int bytes2 = _encoding.GetBytes(value, array);
                Write7BitEncodedInt(bytes2);
                OutStream.Write(array, 0, bytes2);
                ArrayPool<byte>.Shared.Return(array);
                return;
            }
        }
        int byteCount = _encoding.GetByteCount(value);
        Write7BitEncodedInt(byteCount);
        WriteCharsCommonWithoutLengthPrefix(value, useThisWriteOverride: false);
    }
References System.IO.BinaryWriter._encoding, System.IO.BinaryWriter._useFastUtf8, System.array, System.byteCount, System.bytes, System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetBytes(), System.IO.BinaryWriter.OutStream, System.Buffers.ArrayPool< T >.Shared, System.Span< T >.Slice(), System.value, System.IO.Stream.Write(), System.IO.BinaryWriter.Write7BitEncodedInt(), and System.IO.BinaryWriter.WriteCharsCommonWithoutLengthPrefix().