Terraria: System.Net.Quic.Implementations.MsQuic.Internal.MsQuicParameterHelpers.GetINetParam
GetINetParam()
static unsafe MsQuicNativeMethods.SOCKADDR_INET System.Net.Quic.Implementations.MsQuic.Internal.MsQuicParameterHelpers.GetINetParam (MsQuicApi api, SafeHandle nativeObject, QUIC_PARAM_LEVEL level, uint param) inline static package
Definition at line 8 of file MsQuicParameterHelpers.cs.
    {
        uint bufferLength = (uint)sizeof(MsQuicNativeMethods.SOCKADDR_INET);
        Unsafe.SkipInit(out MsQuicNativeMethods.SOCKADDR_INET result);
        uint status = api.GetParamDelegate(nativeObject, level, param, ref bufferLength, (byte*)(&result));
        QuicExceptionHelpers.ThrowIfFailed(status, "GetINETParam failed.");
        return result;
    }
References System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.GetParamDelegate, and System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed().
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventConnected(), and System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start().