Terraria: NPCStatsReportInfoElement.RefreshStats
RefreshStats()
void NPCStatsReportInfoElement.RefreshStats (GameModeData gameModeFound, NPC instance) inline private
     {
         instance.SetDefaults(NpcId, new NPCSpawnParams
         {
             gameModeData = gameModeFound,
             strengthMultiplierOverride = null
         });
         Damage = instance.damage;
         LifeMax = instance.lifeMax;
         MonetaryValue = instance.value;
         Defense = instance.defense;
         KnockbackResist = instance.knockBackResist;
         if (this.OnRefreshStats != null)
         {
             this.OnRefreshStats(this);
         }
     }
References Damage, NPC.damage, Defense, NPC.defense, KnockbackResist, NPC.knockBackResist, LifeMax, NPC.lifeMax, MonetaryValue, NpcId, OnRefreshStats, NPC.SetDefaults(), and NPC.value.
Referenced by NPCStatsReportInfoElement(), ProvideUIElement(), and UpdateBeforeSorting().