Terraria: System.Numerics.BigIntegerCalculator.Divide
Divide() [1/5]
static unsafe void System.Numerics.BigIntegerCalculator.Divide (uint * left, int leftLength, uint * right, int rightLength, uint * bits, int bitsLength) inline static private
Definition at line 541 of file BigIntegerCalculator.cs.
    {
        uint num = right[rightLength - 1];
        uint num2 = ((rightLength > 1) ? right[rightLength - 2] : 0u);
        int num3 = LeadingZeros(num);
        int num4 = 32 - num3;
        if (num3 > 0)
        {
            uint num5 = ((rightLength > 2) ? right[rightLength - 3] : 0u);
            num = (num << num3) | (num2 >> num4);
            num2 = (num2 << num3) | (num5 >> num4);
        }
        for (int num6 = leftLength; num6 >= rightLength; num6--)
        {
            int num7 = num6 - rightLength;
            uint num8 = ((num6 < leftLength) ? left[num6] : 0u);
            ulong num9 = ((ulong)num8 << 32) | left[num6 - 1];
            uint num10 = ((num6 > 1) ? left[num6 - 2] : 0u);
            if (num3 > 0)
            {
                uint num11 = ((num6 > 2) ? left[num6 - 3] : 0u);
                num9 = (num9 << num3) | (num10 >> num4);
                num10 = (num10 << num3) | (num11 >> num4);
            }
            ulong num12 = num9 / num;
            if (num12 > uint.MaxValue)
            {
                num12 = 4294967295uL;
            }
            while (DivideGuessTooBig(num12, num9, num10, num, num2))
            {
                num12--;
            }
            if (num12 != 0)
            {
                uint num13 = SubtractDivisor(left + num7, leftLength - num7, right, rightLength, num12);
                if (num13 != num8)
                {
                    num13 = AddDivisor(left + num7, leftLength - num7, right, rightLength);
                    num12--;
                }
            }
            if (bitsLength != 0)
            {
                bits[num7] = (uint)num12;
            }
            if (num6 < leftLength)
            {
                left[num6] = 0u;
            }
        }
    }
References System.Numerics.BigIntegerCalculator.AddDivisor(), System.Numerics.BigIntegerCalculator.DivideGuessTooBig(), System.Numerics.BigIntegerCalculator.LeadingZeros(), and System.Numerics.BigIntegerCalculator.SubtractDivisor().