Terraria: System.Numerics.BigIntegerCalculator.Divide
Divide() [4/5]
static unsafe uint[] System.Numerics.BigIntegerCalculator.Divide (uint[] left, uint[] right) inline static
Definition at line 498 of file BigIntegerCalculator.cs.
    {
        Span<uint> destination = default(Span<uint>);
        Span<uint> span;
        if (left.Length <= 64)
        {
            span = stackalloc uint[64];
            destination = span.Slice(0, left.Length);
            span = left.AsSpan();
            span.CopyTo(destination);
        }
        else
        {
            span = left.AsSpan();
            destination = span.ToArray();
        }
        uint[] array = new uint[left.Length - right.Length + 1];
        fixed (uint* left2 = &destination[0])
        {
            fixed (uint* right2 = &right[0])
            {
                fixed (uint* bits = &array[0])
                {
                    Divide(left2, destination.Length, right2, right.Length, bits, array.Length);
                }
            }
        }
        return array;
    }
References System.array, System.Span< T >.CopyTo(), System.destination, System.Divide, System.Span< T >.Slice(), and System.Span< T >.ToArray().