Terraria: System.Numerics.BigIntegerCalculator.Square
Square() [1/2]
static unsafe void System.Numerics.BigIntegerCalculator.Square (uint * value, int valueLength, uint * bits, int bitsLength) inline static private
Definition at line 1152 of file BigIntegerCalculator.cs.
    {
        if (valueLength < SquareThreshold)
        {
            for (int i = 0; i < valueLength; i++)
            {
                ulong num = 0uL;
                for (int j = 0; j < i; j++)
                {
                    ulong num2 = bits[i + j] + num;
                    ulong num3 = (ulong)value[j] * (ulong)value[i];
                    bits[i + j] = (uint)(num2 + (num3 << 1));
                    num = num3 + (num2 >> 1) >> 31;
                }
                ulong num4 = (ulong)((long)value[i] * (long)value[i]) + num;
                bits[i + i] = (uint)num4;
                bits[i + i + 1] = (uint)(num4 >> 32);
            }
            return;
        }
        int num5 = valueLength >> 1;
        int num6 = num5 << 1;
        int num7 = num5;
        uint* ptr = value + num5;
        int num8 = valueLength - num5;
        int num9 = num6;
        uint* ptr2 = bits + num6;
        int num10 = bitsLength - num6;
        Square(value, num7, bits, num9);
        Square(ptr, num8, ptr2, num10);
        int num11 = num8 + 1;
        int num12 = num11 + num11;
        if (num12 < AllocationThreshold)
        {
            uint* ptr3 = stackalloc uint[num11];
            new Span<uint>(ptr3, num11).Clear();
            uint* ptr4 = stackalloc uint[num12];
            new Span<uint>(ptr4, num12).Clear();
            Add(ptr, num8, value, num7, ptr3, num11);
            Square(ptr3, num11, ptr4, num12);
            SubtractCore(ptr2, num10, bits, num9, ptr4, num12);
            AddSelf(bits + num5, bitsLength - num5, ptr4, num12);
            return;
        }
        fixed (uint* ptr5 = new uint[num11])
        {
            fixed (uint* ptr6 = new uint[num12])
            {
                Add(ptr, num8, value, num7, ptr5, num11);
                Square(ptr5, num11, ptr6, num12);
                SubtractCore(ptr2, num10, bits, num9, ptr6, num12);
                AddSelf(bits + num5, bitsLength - num5, ptr6, num12);
            }
        }
    }
References System.Add, System.Numerics.BigIntegerCalculator.AddSelf(), System.Numerics.BigIntegerCalculator.AllocationThreshold, System.Span< T >.Clear(), System.Numerics.BigIntegerCalculator.Square(), System.Numerics.BigIntegerCalculator.SquareThreshold, System.Numerics.BigIntegerCalculator.SubtractCore(), and System.value.