Terraria: System.Numerics.BigIntegerCalculator.Gcd
Gcd() [1/5]
static void System.Numerics.BigIntegerCalculator.Gcd (ref BitsBuffer left, ref BitsBuffer right) inline static private
Definition at line 722 of file BigIntegerCalculator.cs.
    {
        while (right.GetLength() > 2)
        {
            ExtractDigits(ref left, ref right, out var x, out var y);
            uint num = 1u;
            uint num2 = 0u;
            uint num3 = 0u;
            uint num4 = 1u;
            int num5 = 0;
            while (y != 0L)
            {
                ulong num6 = x / y;
                if (num6 > uint.MaxValue)
                {
                    break;
                }
                ulong num7 = num + num6 * num3;
                ulong num8 = num2 + num6 * num4;
                ulong num9 = x - num6 * y;
                if (num7 > int.MaxValue || num8 > int.MaxValue || num9 < num8 || num9 + num7 > y - num3)
                {
                    break;
                }
                num = (uint)num7;
                num2 = (uint)num8;
                x = num9;
                num5++;
                if (x == num2)
                {
                    break;
                }
                num6 = y / x;
                if (num6 > uint.MaxValue)
                {
                    break;
                }
                num7 = num4 + num6 * num2;
                num8 = num3 + num6 * num;
                num9 = y - num6 * x;
                if (num7 > int.MaxValue || num8 > int.MaxValue || num9 < num8 || num9 + num7 > x - num2)
                {
                    break;
                }
                num4 = (uint)num7;
                num3 = (uint)num8;
                y = num9;
                num5++;
                if (y == num3)
                {
                    break;
                }
            }
            if (num2 == 0)
            {
                left.Reduce(ref right);
                BitsBuffer bitsBuffer = left;
                left = right;
                right = bitsBuffer;
                continue;
            }
            LehmerCore(ref left, ref right, num, num2, num3, num4);
            if (num5 % 2 == 1)
            {
                BitsBuffer bitsBuffer2 = left;
                left = right;
                right = bitsBuffer2;
            }
        }
        if (right.GetLength() > 0)
        {
            left.Reduce(ref right);
            uint[] bits = right.GetBits();
            uint[] bits2 = left.GetBits();
            ulong left2 = ((ulong)bits[1] << 32) | bits[0];
            ulong right2 = ((ulong)bits2[1] << 32) | bits2[0];
            left.Overwrite(Gcd(left2, right2));
            right.Overwrite(0u);
        }
    }
References System.Numerics.BigIntegerCalculator.ExtractDigits(), System.Numerics.BigIntegerCalculator.Gcd(), System.L, System.Numerics.BigIntegerCalculator.LehmerCore(), and System.Numerics.BigIntegerCalculator.BitsBuffer.Reduce().