Terraria: System.Numerics.BigIntegerCalculator.ActualLength
ActualLength() [1/2]
static int System.Numerics.BigIntegerCalculator.ActualLength (uint[] value) inline static private
Definition at line 1125 of file BigIntegerCalculator.cs.
    {
        return ActualLength(value, value.Length);
    }
References System.Numerics.BigIntegerCalculator.ActualLength(), and System.value.
Referenced by System.Numerics.BigIntegerCalculator.BitsBuffer.BitsBuffer(), System.Numerics.BigIntegerCalculator.FastReducer.FastReducer(), System.Numerics.BigIntegerCalculator.ActualLength(), System.Numerics.BigIntegerCalculator.BitsBuffer.Apply(), System.Numerics.BigIntegerCalculator.FastReducer.DivMul(), System.Numerics.BigIntegerCalculator.BitsBuffer.Reduce(), System.Numerics.BigIntegerCalculator.BitsBuffer.Reduce(), System.Numerics.BigIntegerCalculator.BitsBuffer.Refresh(), and System.Numerics.BigIntegerCalculator.FastReducer.SubMod().