Terraria: Terraria.UI.UIElement.GetDimensions
GetDimensions()
CalculatedStyle Terraria.UI.UIElement.GetDimensions () inline inherited
    {
        return _dimensions;
    }
References Terraria.UI.UIElement._dimensions.
Referenced by Terraria.UI.SnapPoint.Calculate(), Terraria.GameContent.UI.Elements.UIList.UIInnerList.DrawChildren(), Terraria.GameContent.UI.Elements.UIPanel.DrawPanel(), Terraria.GameContent.UI.Elements.UICharacter.DrawPets(), Terraria.GameContent.UI.Elements.EmoteButton.DrawSelf(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIBestiaryEntryIcon.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacter.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacterListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacterNameButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIClothStyleButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIColoredImageButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIColoredSlider.DrawSelf(), Terraria.GameContent.UI.Elements.UIDifficultyButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIGenProgressBar.DrawSelf(), Terraria.GameContent.UI.Elements.UIHairStyleButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIHeader.DrawSelf(), Terraria.GameContent.UI.Elements.UIHorizontalSeparator.DrawSelf(), Terraria.GameContent.UI.Elements.UIIconTextButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIImage.DrawSelf(), Terraria.GameContent.UI.Elements.UIImageButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIImageFramed.DrawSelf(), Terraria.GameContent.UI.Elements.UIImageWithBorder.DrawSelf(), Terraria.GameContent.UI.Elements.UIItemIcon.DrawSelf(), Terraria.GameContent.UI.Elements.UIItemSlot.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingSimpleListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingSliderItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingToggleListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIProgressBar.UIInnerProgressBar.DrawSelf(), Terraria.GameContent.UI.Elements.UIResourcePack.DrawSelf(), Terraria.GameContent.UI.Elements.UIResourcePackInfoButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UIScrollbar.DrawSelf(), Terraria.GameContent.UI.Elements.UISelectableTextPanel< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UISlicedImage.DrawSelf(), Terraria.GameContent.UI.Elements.UIToggleImage.DrawSelf(), Terraria.GameContent.UI.Elements.UIVerticalSeparator.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorldCreationPreview.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIColoredSliderSimple.DrawValueBarDynamicWidth(), Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetEntriesToShow(), Terraria.GameContent.UI.States.UIBestiaryTest.GetEntriesToShow(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetGridParameters(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetSnapPoints(), Terraria.GameContent.UI.Elements.UIParticleLayer.Recalculate(), Terraria.GameContent.UI.Elements.UIIconTextButton.SetText(), Terraria.GameContent.UI.States.UIVirtualKeyboard.SetupGamepadPoints(), Terraria.GameContent.UI.Elements.UICharacterNameButton.TrimDisplayIfOverElementDimensions(), Terraria.GameContent.UI.Elements.UISearchBar.TrimDisplayIfOverElementDimensions(), Terraria.GameContent.UI.Elements.UIBestiaryEntryIcon.Update(), and Terraria.GameContent.UI.Elements.UIDynamicItemCollection.UpdateSize().