Terraria: Terraria.UI.UIElement.GetElementAt
GetElementAt()
UIElement Terraria.UI.UIElement.GetElementAt (Vector2 point) inline inherited
Definition at line 320 of file UIElement.cs.
    {
        UIElement uIElement = null;
        for (int num = Elements.Count - 1; num >= 0; num--)
        {
            UIElement uIElement2 = Elements[num];
            if (!uIElement2.IgnoresMouseInteraction && uIElement2.ContainsPoint(point))
            {
                uIElement = uIElement2;
                break;
            }
        }
        if (uIElement != null)
        {
            return uIElement.GetElementAt(point);
        }
        if (IgnoresMouseInteraction)
        {
            return null;
        }
        if (ContainsPoint(point))
        {
            return this;
        }
        return null;
    }
References Terraria.UI.UIElement.ContainsPoint(), Terraria.UI.UIElement.GetElementAt(), and Terraria.UI.UIElement.IgnoresMouseInteraction.
Referenced by Terraria.UI.UIElement.GetElementAt(), and Terraria.UI.UserInterface.Update().