Terraria: Terraria.UI.UIElement.GetInnerDimensions
GetInnerDimensions()
CalculatedStyle Terraria.UI.UIElement.GetInnerDimensions () inline inherited
Definition at line 377 of file UIElement.cs.
    {
        return _innerDimensions;
    }
References Terraria.UI.UIElement._innerDimensions.
Referenced by Terraria.UI.UIElement.DrawDebugHitbox(), Terraria.GameContent.UI.Elements.UIResourcePack.DrawIcon(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIBestiaryInfoLine< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacterListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIScrollbar.DrawSelf(), Terraria.GameContent.UI.Elements.UIText.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UITextPanel< T >.DrawText(), Terraria.GameContent.UI.Elements.UIScrollbar.GetHandleRectangle(), Terraria.GameContent.UI.Elements.UIText.InternalSetText(), Terraria.GameContent.UI.Elements.UIScrollbar.LeftMouseDown(), Terraria.UI.UIElement.Recalculate(), Terraria.GameContent.UI.Elements.UICharacterNameButton.SetContents(), Terraria.GameContent.UI.States.UIAchievementsMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIManageControls.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints2(), and Terraria.GameContent.UI.Elements.UIList.UpdateScrollbar().