Terraria: Terraria.UI.UIElement.RemoveAllChildren
RemoveAllChildren()
void Terraria.UI.UIElement.RemoveAllChildren () inline inherited
Definition at line 188 of file UIElement.cs.
    {
        foreach (UIElement element in Elements)
        {
            element.Parent = null;
        }
        Elements.Clear();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Clear().
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildPage(), Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage(), Terraria.GameContent.UI.States.UICharacterCreation.BuildPage(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreation.BuildPage(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FillBestiarySpaceWithEntries(), Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage(), Terraria.GameContent.UI.States.UIEmotesMenu.InitializePage(), Terraria.GameContent.UI.States.UICreativePowersMenu.RefreshElementsOrder(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay_OnUpdate(), and Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateAvailability().