Terraria: Terraria.UI.UIElement.Update
Update()
virtual void Terraria.UI.UIElement.Update (GameTime gameTime) inline virtual inherited
Reimplemented in Terraria.GameContent.UI.Elements.EmoteButton, Terraria.GameContent.UI.Elements.UIBestiaryEntryIcon, Terraria.GameContent.UI.Elements.UICharacter, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay, Terraria.GameContent.UI.Elements.UIDynamicItemCollection, Terraria.GameContent.UI.Elements.UISearchBar, Terraria.GameContent.UI.States.UIBestiaryTest, and Terraria.GameContent.UI.States.UIWorldLoad.
Definition at line 234 of file UIElement.cs.
    {
        if (this.OnUpdate != null)
        {
            this.OnUpdate(this);
        }
        foreach (UIElement element in Elements)
        {
            element.Update(gameTime);
        }
    }
References Terraria.UI.UIElement.OnUpdate, and Terraria.UI.UIElement.Update().
Referenced by Terraria.UI.UIElement.Update(), and Terraria.UI.UserInterface.Update().