Terraria: Terraria.UI.UIElement.Append
Append()
void Terraria.UI.UIElement.Append (UIElement element) inline inherited
References Terraria.UI.UIElement.Recalculate(), and Terraria.UI.UIElement.Remove().
Referenced by Terraria.GameContent.UI.Elements.EmotesGroupListItem.EmotesGroupListItem(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.GroupOptionButton(), Terraria.GameContent.UI.Elements.PowerStripUIElement.PowerStripUIElement(), Terraria.GameContent.UI.Elements.UIAchievementListItem.UIAchievementListItem(), Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.UIBestiaryEntryButton(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage(), Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.UIBestiaryInfoItemLine(), Terraria.GameContent.UI.Elements.UIBestiaryNPCEntryPortrait.UIBestiaryNPCEntryPortrait(), Terraria.GameContent.UI.Elements.UICharacterListItem.UICharacterListItem(), Terraria.GameContent.UI.Elements.UICharacterNameButton.UICharacterNameButton(), Terraria.GameContent.UI.Elements.UIClothStyleButton.UIClothStyleButton(), Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions(), Terraria.GameContent.UI.Elements.UIDifficultyButton.UIDifficultyButton(), Terraria.GameContent.UI.Elements.UIList.UIList(), Terraria.GameContent.UI.Elements.UIProgressBar.UIProgressBar(), Terraria.GameContent.UI.Elements.UISearchBar.UISearchBar(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.UIWorkshopPublishResourcePackListItem(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem(), Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem(), Terraria.GameContent.UI.States.UIWorldLoad.UIWorldLoad(), Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.AppendBorderOverEverything(), Terraria.GameContent.UI.Elements.UIResourcePack.BuildChildren(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.BuildContainer(), Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.BuildGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage(), Terraria.GameContent.UI.States.UICharacterCreation.BuildPage(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreation.BuildPage(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.CheckScrollBar(), Terraria.GameContent.UI.States.UICharacterCreation.Click_CharInfo(), Terraria.GameContent.UI.States.UICharacterCreation.Click_ClothStyles(), Terraria.GameContent.UI.States.UICharacterCreation.Click_HairStyles(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreateMainPowerStrip(), Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FillBestiarySpaceWithEntries(), Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage(), Terraria.GameContent.UI.States.UICreativePowersMenu.InitializePage(), Terraria.GameContent.UI.States.UIEmotesMenu.InitializePage(), Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.MouseOut(), Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.MouseOver(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.OnInitialize(), Terraria.GameContent.UI.States.UICharacterSelect.OnInitialize(), Terraria.GameContent.UI.States.UIManageControls.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopHub.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.OnInitialize(), Terraria.GameContent.UI.States.UIWorldSelect.OnInitialize(), Terraria.GameContent.UI.States.UIBestiaryTest.OpenOrCloseFilteringGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.OpenOrCloseSortingOptions(), Terraria.GameContent.Bestiary.NamePlateInfoElement.ProvideUIElement(), Terraria.GameContent.UI.States.UICharacterSelect.Recalculate(), Terraria.GameContent.UI.States.UIEmotesMenu.Recalculate(), Terraria.GameContent.UI.States.UIReportsPage.Recalculate(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.Recalculate(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.Recalculate(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.Recalculate(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.Recalculate(), Terraria.GameContent.UI.States.UIWorldSelect.Recalculate(), Terraria.GameContent.UI.States.UICreativePowersMenu.RefreshElementsOrder(), Terraria.GameContent.UI.States.UICharacterCreation.SelectColorPicker(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetText(), Terraria.GameContent.UI.Elements.UIIconTextButton.SetText(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay_OnUpdate(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateAvailability(), and Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.UpdateScrollbar().