Terraria: Microsoft.Extensions.Internal.ValueStopwatch.StartNew
StartNew() [1/3]
static Microsoft.Extensions.Internal.ValueStopwatch Microsoft.Extensions.Internal.ValueStopwatch.StartNew () inline static
Definition at line 19 of file ValueStopwatch.cs.
    {
        return new Microsoft.Extensions.Internal.ValueStopwatch(Stopwatch.GetTimestamp());
    }
References System.Diagnostics.Stopwatch.GetTimestamp().
Referenced by System.Net.NameResolutionTelemetry.BeforeResolution(), System.Net.Dns.GetAddrInfoWithTelemetryAsync< T >(), System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(), and System.Net.Security.SslStream.ProcessAuthenticationWithTelemetryAsync().