Terraria: Terraria.GameContent.Golf.GolfHelper.ValidateShot
ValidateShot()
static bool Terraria.GameContent.Golf.GolfHelper.ValidateShot (Entity golfBall, Player player, ref Vector2 shotVector) inline static
Definition at line 440 of file GolfHelper.cs.
    {
        Vector2 vector = golfBall.Center - player.Bottom;
        if (player.direction == -1)
        {
            vector.X *= -1f;
            shotVector.X *= -1f;
        }
        float num = shotVector.ToRotation();
        if (num > 0f)
        {
            shotVector = shotVector.Length() * new Vector2((float)Math.Cos(0.0), (float)Math.Sin(0.0));
        }
        else if (num < -1.5207964f)
        {
            shotVector = shotVector.Length() * new Vector2((float)Math.Cos(-1.5207964181900024), (float)Math.Sin(-1.5207964181900024));
        }
        if (player.direction == -1)
        {
            shotVector.X *= -1f;
        }
        if (vector.X >= -16f && vector.X <= 32f && vector.Y <= 16f)
        {
            return vector.Y >= -16f;
        }
        return false;
    }
References Terraria.Entity.Bottom, System.Math.Cos(), Terraria.Entity.direction, Microsoft.Xna.Framework.Vector2.Length(), System.Math.Sin(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.AI_150_GolfClubHelper(), Terraria.Main.DrawProjDirect(), and Terraria.GameContent.Golf.GolfHelper.FindGolfBallForHelper().