Terraria: Terraria.GameContent.Golf.GolfHelper.CalculateShotStrength
CalculateShotStrength() [2/2]
static ShotStrength Terraria.GameContent.Golf.GolfHelper.CalculateShotStrength (Vector2 shotVector, ClubProperties clubProperties) inline static
Definition at line 310 of file GolfHelper.cs.
    {
        Vector2.Normalize(shotVector);
        float value = shotVector.Length();
        float num = FindVectorOnOval(shotVector, clubProperties.MaximumStrength).Length();
        float num2 = FindVectorOnOval(shotVector, clubProperties.MinimumStrength).Length();
        float num3 = MathHelper.Clamp(value, num2, num);
        float relativeStrength = Math.Max((num3 - num2) / (num - num2), 0.001f);
        return new ShotStrength(num3 * 32f, relativeStrength, clubProperties.RoughLandResistance);
    }
References Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.GameContent.Golf.GolfHelper.FindVectorOnOval(), Microsoft.Xna.Framework.Vector2.Length(), System.Math.Max(), Terraria.GameContent.Golf.GolfHelper.ClubProperties.MaximumStrength, Terraria.GameContent.Golf.GolfHelper.ClubProperties.MinimumStrength, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.GameContent.Golf.GolfHelper.ClubProperties.RoughLandResistance, and System.value.
Referenced by Terraria.Projectile.AI_150_GolfClubHelper(), Terraria.GameContent.Golf.GolfHelper.CalculateShotStrength(), Terraria.Main.DrawInterface_Resources_GolfPower(), and Terraria.Main.DrawProjDirect().