Terraria: Terraria.GameContent.Golf.GolfHelper.StepGolfBall
StepGolfBall()
static BallStepResult Terraria.GameContent.Golf.GolfHelper.StepGolfBall (Entity entity, ref float angularVelocity) inline static
Definition at line 296 of file GolfHelper.cs.
    {
        return BallCollision.Step(PhysicsProperties, entity, ref angularVelocity, Listener);
    }
References Terraria.GameContent.Golf.GolfHelper.Listener, and Terraria.Physics.BallCollision.Step().
Referenced by Terraria.Projectile.AI_149_GolfBall(), and Terraria.GameContent.Golf.FancyGolfPredictionLine.Update().