Terraria: TeleportPylonsSystem.UpdatePylonsListAndBroadcastChanges
UpdatePylonsListAndBroadcastChanges()
void TeleportPylonsSystem.UpdatePylonsListAndBroadcastChanges () inline private
     {
         Utils.Swap(ref _pylons, ref _pylonsOld);
         _pylons.Clear();
         foreach (TileEntity value in TileEntity.ByPosition.Values)
         {
             if (value is TETeleportationPylon tETeleportationPylon && tETeleportationPylon.TryGetPylonType(out var pylonType))
             {
                 TeleportPylonInfo teleportPylonInfo = default(TeleportPylonInfo);
                 teleportPylonInfo.PositionInTiles = tETeleportationPylon.Position;
                 teleportPylonInfo.TypeOfPylon = pylonType;
                 TeleportPylonInfo item = teleportPylonInfo;
                 _pylons.Add(item);
             }
         }
         IEnumerable<TeleportPylonInfo> enumerable = _pylonsOld.Except(_pylons);
         foreach (TeleportPylonInfo item2 in _pylons.Except(_pylonsOld))
         {
             NetManager.Instance.BroadcastOrLoopback(NetTeleportPylonModule.SerializePylonWasAddedOrRemoved(item2, NetTeleportPylonModule.SubPacketType.PylonWasAdded));
         }
         foreach (TeleportPylonInfo item3 in enumerable)
         {
             NetManager.Instance.BroadcastOrLoopback(NetTeleportPylonModule.SerializePylonWasAddedOrRemoved(item3, NetTeleportPylonModule.SubPacketType.PylonWasRemoved));
         }
     }
References _pylons, _pylonsOld, NetManager.BroadcastOrLoopback(), TileEntity.ByPosition, NetManager.Instance, TeleportPylonInfo.PositionInTiles, NetTeleportPylonModule.SerializePylonWasAddedOrRemoved(), TETeleportationPylon.TryGetPylonType(), and TeleportPylonInfo.TypeOfPylon.
Referenced by RequestImmediateUpdate(), and Update().