Terraria: TeleportPylonsSystem.HandleTeleportRequest
HandleTeleportRequest()
void TeleportPylonsSystem.HandleTeleportRequest (TeleportPylonInfo info, int playerIndex) inline
     {
         Player player = Main.player[playerIndex];
         string key = null;
         bool flag = true;
         if (flag)
         {
             flag &= IsPlayerNearAPylon(player);
             if (!flag)
             {
                 key = "Net.CannotTeleportToPylonBecausePlayerIsNotNearAPylon";
             }
         }
         if (flag)
         {
             int necessaryNPCCount = HowManyNPCsDoesPylonNeed(info, player);
             flag &= DoesPylonHaveEnoughNPCsAroundIt(info, necessaryNPCCount);
             if (!flag)
             {
                 key = "Net.CannotTeleportToPylonBecauseNotEnoughNPCs";
             }
         }
         if (flag)
         {
             flag &= !NPC.AnyDanger(quickBossNPCCheck: false, ignorePillarsAndMoonlordCountdown: true);
             if (!flag)
             {
                 key = "Net.CannotTeleportToPylonBecauseThereIsDanger";
             }
         }
         if (flag)
         {
             if (!NPC.downedPlantBoss && (double)info.PositionInTiles.Y > Main.worldSurface && Framing.GetTileSafely(info.PositionInTiles.X, info.PositionInTiles.Y).wall == 87)
             {
                 flag = false;
             }
             if (!flag)
             {
                 key = "Net.CannotTeleportToPylonBecauseAccessingLihzahrdTempleEarly";
             }
         }
         if (flag)
         {
             _sceneMetrics.ScanAndExportToMain(new SceneMetricsScanSettings
             {
                 VisualScanArea = null,
                 BiomeScanCenterPositionInWorld = info.PositionInTiles.ToWorldCoordinates(),
                 ScanOreFinderData = false
             });
             flag = DoesPylonAcceptTeleportation(info, player);
             if (!flag)
             {
                 key = "Net.CannotTeleportToPylonBecauseNotMeetingBiomeRequirements";
             }
         }
         if (flag)
         {
             bool flag2 = false;
             int num = 0;
             for (int i = 0; i < _pylons.Count; i++)
             {
                 TeleportPylonInfo info2 = _pylons[i];
                 if (!player.InInteractionRange(info2.PositionInTiles.X, info2.PositionInTiles.Y, TileReachCheckSettings.Pylons))
                 {
                     continue;
                 }
                 if (num < 1)
                 {
                     num = 1;
                 }
                 int necessaryNPCCount2 = HowManyNPCsDoesPylonNeed(info2, player);
                 if (DoesPylonHaveEnoughNPCsAroundIt(info2, necessaryNPCCount2))
                 {
                     if (num < 2)
                     {
                         num = 2;
                     }
                     _sceneMetrics.ScanAndExportToMain(new SceneMetricsScanSettings
                     {
                         VisualScanArea = null,
                         BiomeScanCenterPositionInWorld = info2.PositionInTiles.ToWorldCoordinates(),
                         ScanOreFinderData = false
                     });
                     if (DoesPylonAcceptTeleportation(info2, player))
                     {
                         flag2 = true;
                         break;
                     }
                 }
             }
             if (!flag2)
             {
                 flag = false;
                 key = num switch
                 {
                     1 => "Net.CannotTeleportToPylonBecauseNotEnoughNPCsAtCurrentPylon",
                     2 => "Net.CannotTeleportToPylonBecauseNotMeetingBiomeRequirements",
                     _ => "Net.CannotTeleportToPylonBecausePlayerIsNotNearAPylon",
                 };
             }
         }
         if (flag)
         {
             Vector2 newPos = info.PositionInTiles.ToWorldCoordinates() - new Vector2(0f, player.HeightOffsetBoost);
             int num2 = 9;
             int typeOfPylon = (int)info.TypeOfPylon;
             int number = 0;
             player.Teleport(newPos, num2, typeOfPylon);
             player.velocity = Vector2.Zero;
             if (Main.netMode == 2)
             {
                 RemoteClient.CheckSection(player.whoAmI, player.position);
                 NetMessage.SendData(65, -1, -1, null, 0, player.whoAmI, newPos.X, newPos.Y, num2, number, typeOfPylon);
             }
         }
         else
         {
             ChatHelper.SendChatMessageToClient(NetworkText.FromKey(key), new Color(255, 240, 20), playerIndex);
         }
     }
References _pylons, _sceneMetrics, NPC.AnyDanger(), RemoteClient.CheckSection(), Color, DoesPylonAcceptTeleportation(), DoesPylonHaveEnoughNPCsAroundIt(), NPC.downedPlantBoss, NetworkText.FromKey(), Framing.GetTileSafely(), Player.HeightOffsetBoost, HowManyNPCsDoesPylonNeed(), Player.InInteractionRange(), IsPlayerNearAPylon(), Main.netMode, Main.player, Entity.position, TeleportPylonInfo.PositionInTiles, TileReachCheckSettings.Pylons, SceneMetrics.ScanAndExportToMain(), ChatHelper.SendChatMessageToClient(), NetMessage.SendData(), Player.Teleport(), TeleportPylonInfo.TypeOfPylon, Entity.velocity, Tile.wall, Entity.whoAmI, Main.worldSurface, Point16.X, and Point16.Y.
Referenced by NetTeleportPylonModule.Deserialize().