Terraria: TeleportPylonsSystem.RequestImmediateUpdate
RequestImmediateUpdate()
void TeleportPylonsSystem.RequestImmediateUpdate () inline
     {
         if (Main.netMode != 1)
         {
             _cooldownForUpdatingPylonsList = int.MaxValue;
             UpdatePylonsListAndBroadcastChanges();
         }
     }
References _cooldownForUpdatingPylonsList, Main.netMode, and UpdatePylonsListAndBroadcastChanges().
Referenced by TETeleportationPylon.Kill(), and TETeleportationPylon.Place().