Terraria: System.Collections.ArrayList.IListWrapper.LastIndexOf
LastIndexOf() [1/6]
override int System.Collections.ArrayList.IListWrapper.LastIndexOf (object value) inline
Definition at line 350 of file ArrayList.cs.
        {
            return LastIndexOf(value, _list.Count - 1, _list.Count);
        }
References System.Collections.ArrayList.IListWrapper._list, System.Collections.ICollection.Count, System.Collections.ArrayList.IListWrapper.LastIndexOf(), and System.value.
Referenced by System.Collections.ArrayList.IListWrapper.LastIndexOf(), and System.Collections.ArrayList.IListWrapper.LastIndexOf().