Terraria: System.Security.Cryptography.ChaCha20Poly1305.ThrowIfNotSupported
ThrowIfNotSupported()
static void System.Security.Cryptography.ChaCha20Poly1305.ThrowIfNotSupported () inline static private
Definition at line 83 of file ChaCha20Poly1305.cs.
    {
        if (!IsSupported)
        {
            throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_AlgorithmNotSupported, "ChaCha20Poly1305"));
        }
    }
References System.SR.Cryptography_AlgorithmNotSupported, System.SR.Format(), and System.Security.Cryptography.ChaCha20Poly1305.IsSupported.
Referenced by System.Security.Cryptography.ChaCha20Poly1305.ChaCha20Poly1305(), and System.Security.Cryptography.ChaCha20Poly1305.ChaCha20Poly1305().