Terraria: System.Formats.Asn1.Asn1Tag.AsPrimitive
AsPrimitive()
Asn1Tag System.Formats.Asn1.Asn1Tag.AsPrimitive () inline
Definition at line 82 of file Asn1Tag.cs.
    {
        return new Asn1Tag((byte)(_controlFlags & 0xFFFFFFDFu), TagValue);
    }
References System.Formats.Asn1.Asn1Tag.Asn1Tag(), System.Formats.Asn1.Asn1Tag._controlFlags, and System.Formats.Asn1.Asn1Tag.TagValue.
Referenced by System.Formats.Asn1.AsnWriter.PopTag(), System.Formats.Asn1.AsnWriter.WriteBitStringCore(), System.Formats.Asn1.AsnWriter.WriteCharacterStringCore(), and System.Formats.Asn1.AsnWriter.WriteOctetStringCore().