Terraria: System.Formats.Asn1.Asn1Tag.HasSameClassAndValue
HasSameClassAndValue()
bool System.Formats.Asn1.Asn1Tag.HasSameClassAndValue (Asn1Tag other) inline
Definition at line 251 of file Asn1Tag.cs.
    {
        if (TagValue == other.TagValue)
        {
            return TagClass == other.TagClass;
        }
        return false;
    }
References System.other, and System.Formats.Asn1.Asn1Tag.TagValue.
Referenced by System.Security.Cryptography.Asn1.CurveAsn.DecodeCore(), System.Security.Cryptography.Asn1.ECPrivateKey.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2Params.DecodeCore(), System.Security.Cryptography.Asn1.SpecifiedECDomain.DecodeCore(), System.Security.Cryptography.Asn1.ECDomainParameters.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.DecodeCore(), System.Security.Cryptography.Asn1.CurveAsn.DecodeCore(), System.Security.Cryptography.Asn1.ECPrivateKey.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2Params.DecodeCore(), System.Security.Cryptography.Asn1.SpecifiedECDomain.DecodeCore(), System.Security.Cryptography.Asn1.X509ExtensionAsn.DecodeCore(), System.Security.Cryptography.Asn1.ECDomainParameters.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.DecodeCore(), and System.Security.Cryptography.X509Certificates.Asn1.TimeAsn.DecodeCore().