Terraria: System.Formats.Asn1.Asn1Tag.TryDecode
TryDecode()
static bool System.Formats.Asn1.Asn1Tag.TryDecode (ReadOnlySpan< byte > source, out Asn1Tag tag, out int bytesConsumed) inline static
Definition at line 87 of file Asn1Tag.cs.
    {
        tag = default(Asn1Tag);
        bytesConsumed = 0;
        if (source.IsEmpty)
        {
            return false;
        }
        byte b = source[bytesConsumed];
        bytesConsumed++;
        uint num = b & 0x1Fu;
        if (num == 31)
        {
            num = 0u;
            byte b2;
            do
            {
                if (source.Length <= bytesConsumed)
                {
                    bytesConsumed = 0;
                    return false;
                }
                b2 = source[bytesConsumed];
                byte b3 = (byte)(b2 & 0x7Fu);
                bytesConsumed++;
                if (num >= 33554432)
                {
                    bytesConsumed = 0;
                    return false;
                }
                num <<= 7;
                num |= b3;
                if (num == 0)
                {
                    bytesConsumed = 0;
                    return false;
                }
            }
            while ((b2 & 0x80) == 128);
            if (num <= 30)
            {
                bytesConsumed = 0;
                return false;
            }
            if (num > int.MaxValue)
            {
                bytesConsumed = 0;
                return false;
            }
        }
        tag = new Asn1Tag(b, (int)num);
        return true;
    }
References System.Formats.Asn1.Asn1Tag.Asn1Tag(), and System.source.
Referenced by System.Formats.Asn1.Asn1Tag.Decode(), System.Security.Cryptography.Asn1.DirectoryStringAsn.Encode(), System.Security.Cryptography.Asn1.GeneralNameAsn.Encode(), System.Security.Cryptography.X509Certificates.Asn1.CertificationRequestInfoAsn.Encode(), System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.Encode(), and System.Formats.Asn1.AsnDecoder.TryReadEncodedValue().