Terraria: System.Formats.Asn1.Asn1Tag.CalculateEncodedSize
CalculateEncodedSize()
int System.Formats.Asn1.Asn1Tag.CalculateEncodedSize () inline
Definition at line 150 of file Asn1Tag.cs.
    {
        if (TagValue < 31)
        {
            return 1;
        }
        if (TagValue <= 127)
        {
            return 2;
        }
        if (TagValue <= 16383)
        {
            return 3;
        }
        if (TagValue <= 2097151)
        {
            return 4;
        }
        if (TagValue <= 268435455)
        {
            return 5;
        }
        return 6;
    }
References System.Formats.Asn1.Asn1Tag.TagValue.
Referenced by System.Formats.Asn1.AsnWriter.DetermineCerBitStringTotalLength(), System.Formats.Asn1.AsnWriter.PopTag(), System.Formats.Asn1.Asn1Tag.TryEncode(), and System.Formats.Asn1.AsnWriter.WriteTag().