Terraria: System.Formats.Asn1.Asn1Tag.Asn1Tag
Asn1Tag() [1/3]
System.Formats.Asn1.Asn1Tag.Asn1Tag (byte controlFlags, int tagValue) inline private
Definition at line 43 of file Asn1Tag.cs.
    {
        _controlFlags = (byte)(controlFlags & 0xE0u);
        TagValue = tagValue;
    }
References System.Formats.Asn1.Asn1Tag._controlFlags, and System.Formats.Asn1.Asn1Tag.TagValue.
Referenced by System.Formats.Asn1.Asn1Tag.AsConstructed(), System.Formats.Asn1.Asn1Tag.AsPrimitive(), and System.Formats.Asn1.Asn1Tag.TryDecode().