Terraria: Terraria.GameContent.RGB.EyeballShader.Update
Update()
override void Terraria.GameContent.RGB.EyeballShader.Update (float elapsedTime) inline virtual
Reimplemented from ReLogic.Peripherals.RGB.ChromaShader.
Definition at line 63 of file EyeballShader.cs.
    {
        UpdateEyelid(elapsedTime);
        bool num = _timeUntilPupilMove <= 0f;
        _pupilOffset = (_targetOffset + _pupilOffset) * 0.5f;
        _timeUntilPupilMove -= elapsedTime;
        if (num)
        {
            float num2 = (float)_random.NextDouble() * ((float)Math.PI * 2f);
            float num3;
            if (_isSpawning)
            {
                _timeUntilPupilMove = (float)_random.NextDouble() * 0.4f + 0.3f;
                num3 = (float)_random.NextDouble() * 0.7f;
            }
            else
            {
                _timeUntilPupilMove = (float)_random.NextDouble() * 0.4f + 0.6f;
                num3 = (float)_random.NextDouble() * 0.3f;
            }
            _targetOffset = new Vector2((float)Math.Cos(num2), (float)Math.Sin(num2)) * num3;
        }
    }
References Terraria.GameContent.RGB.EyeballShader._isSpawning, Terraria.GameContent.RGB.EyeballShader._pupilOffset, Terraria.GameContent.RGB.EyeballShader._random, Terraria.GameContent.RGB.EyeballShader._targetOffset, Terraria.GameContent.RGB.EyeballShader._timeUntilPupilMove, System.Math.Cos(), Terraria.Utilities.UnifiedRandom.NextDouble(), System.Math.PI, System.Math.Sin(), and Terraria.GameContent.RGB.EyeballShader.UpdateEyelid().