Terraria: System.Xml.Xsl.XPath.XPathBuilder.FunctionInfo.CastArguments
CastArguments()
void System.Xml.Xsl.XPath.XPathBuilder.FunctionInfo< T >.CastArguments (IList< QilNode > args, string name, XPathQilFactory f) inline
Definition at line 197 of file XPathBuilder.cs.
        {
            CheckArity(minArgs, maxArgs, name, args.Count);
            if (maxArgs == int.MaxValue)
            {
                for (int i = 0; i < args.Count; i++)
                {
                    args[i] = f.ConvertToType(XmlTypeCode.String, args[i]);
                }
                return;
            }
            for (int j = 0; j < args.Count; j++)
            {
                if (argTypes[j] == XmlTypeCode.Node && f.CannotBeNodeSet(args[j]))
                {
                    throw new XPathCompileException(System.SR.XPath_NodeSetArgumentExpected, name, (j + 1).ToString(CultureInfo.InvariantCulture));
                }
                args[j] = f.ConvertToType(argTypes[j], args[j]);
            }
        }
References System.Xml.Xsl.XPath.XPathBuilder.FunctionInfo< T >.argTypes, System.Xml.Xsl.XPath.XPathQilFactory.CannotBeNodeSet(), System.Xml.Xsl.XPath.XPathBuilder.FunctionInfo< T >.CheckArity(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToType(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Xml.Xsl.XPath.XPathBuilder.FunctionInfo< T >.maxArgs, System.Xml.Xsl.XPath.XPathBuilder.FunctionInfo< T >.minArgs, and System.SR.XPath_NodeSetArgumentExpected.