Terraria: Terraria.Social.Steam.WorkshopSocialModule.TryGetInfoForWorld
TryGetInfoForWorld()
override bool Terraria.Social.Steam.WorkshopSocialModule.TryGetInfoForWorld (WorldFileData world, out FoundWorkshopEntryInfo info) inline
Definition at line 193 of file WorkshopSocialModule.cs.
    {
        info = null;
        string text = GetTemporaryFolderPath() + world.GetFileName(includeExtension: false);
        if (!Directory.Exists(text))
        {
            return false;
        }
        if (AWorkshopEntry.TryReadingManifest(text + Path.DirectorySeparatorChar + "workshop.json", out info))
        {
            return true;
        }
        return false;
    }
References System.IO.Path.DirectorySeparatorChar, System.IO.Directory.Exists(), Terraria.IO.FileData.GetFileName(), Terraria.Social.Steam.WorkshopSocialModule.GetTemporaryFolderPath(), and Terraria.Social.Base.AWorkshopEntry.TryReadingManifest().