Terraria: Terraria.Social.Steam.WorkshopSocialModule.Forget
Forget()
void Terraria.Social.Steam.WorkshopSocialModule.Forget (WorkshopHelper::UGCBased::APublisherInstance instance) inline private
Definition at line 89 of file WorkshopSocialModule.cs.
    {
        _publisherInstances.Remove(instance);
        RefreshSubscriptionsAndPublishings();
    }
References Terraria.Social.Steam.WorkshopSocialModule._publisherInstances, Terraria.Social.Steam.WorkshopSocialModule.RefreshSubscriptionsAndPublishings(), and System.Collections.Generic.Dictionary< TKey, TValue >.Remove().
Referenced by Terraria.Social.Steam.WorkshopSocialModule.PublishResourcePack(), and Terraria.Social.Steam.WorkshopSocialModule.PublishWorld().