Terraria: System.Xml.CharEntityEncoderFallbackBuffer.Fallback
Fallback() [2/2]
override bool System.Xml.CharEntityEncoderFallbackBuffer.Fallback (char charUnknownHigh, char charUnknownLow, int index) inline
Definition at line 55 of file CharEntityEncoderFallbackBuffer.cs.
    {
        if (!char.IsSurrogatePair(charUnknownHigh, charUnknownLow))
        {
            throw XmlConvert.CreateInvalidSurrogatePairException(charUnknownHigh, charUnknownLow);
        }
        if (_charEntityIndex >= 0)
        {
            new EncoderExceptionFallback().CreateFallbackBuffer().Fallback(charUnknownHigh, charUnknownLow, index);
        }
        if (_parent.CanReplaceAt(index))
        {
            IFormatProvider formatProvider = null;
            IFormatProvider provider = formatProvider;
            Span<char> initialBuffer = stackalloc char[64];
            DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(4, 1, formatProvider, initialBuffer);
            handler.AppendLiteral("&#x");
            handler.AppendFormatted(SurrogateCharToUtf32(charUnknownHigh, charUnknownLow), "X");
            handler.AppendLiteral(";");
            _charEntity = string.Create(provider, initialBuffer, ref handler);
            _charEntityIndex = 0;
            return true;
        }
        EncoderFallbackBuffer encoderFallbackBuffer = new EncoderExceptionFallback().CreateFallbackBuffer();
        encoderFallbackBuffer.Fallback(charUnknownHigh, charUnknownLow, index);
        return false;
    }
References System.Xml.CharEntityEncoderFallbackBuffer._charEntity, System.Xml.CharEntityEncoderFallbackBuffer._charEntityIndex, System.Xml.CharEntityEncoderFallbackBuffer._parent, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Xml.CharEntityEncoderFallback.CanReplaceAt(), System.Text.EncoderExceptionFallback.CreateFallbackBuffer(), System.Xml.XmlConvert.CreateInvalidSurrogatePairException(), System.Xml.Dictionary, System.Text.EncoderFallbackBuffer.Fallback(), System.index, and System.Xml.CharEntityEncoderFallbackBuffer.SurrogateCharToUtf32().