Terraria: SteelSeriesDeviceGroup.SteelSeriesDeviceGroup
SteelSeriesDeviceGroup()
SteelSeriesDeviceGroup.SteelSeriesDeviceGroup (VendorColorProfile colorProfiles, string gameNameIdInAllCaps, string gameDisplayName, IconColor iconColor) inline
     {
         //IL_002f: Unknown result type (might be due to invalid IL or missing references)
         //IL_0034: Unknown result type (might be due to invalid IL or missing references)
         //IL_003b: Unknown result type (might be due to invalid IL or missing references)
         //IL_0042: Unknown result type (might be due to invalid IL or missing references)
         //IL_004e: Expected O, but got Unknown
         //IL_006e: Unknown result type (might be due to invalid IL or missing references)
         //IL_0070: Unknown result type (might be due to invalid IL or missing references)
         _gameSenseConnection = new GameSenseConnection
         {
             GameName = gameNameIdInAllCaps,
             GameDisplayName = gameDisplayName,
             IconColor = iconColor
         };
         _colorProfiles = colorProfiles;
         GameSenseConnection gameSenseConnection = _gameSenseConnection;
         gameSenseConnection.OnConnectionBecameActive = (GameSenseConnection.ClientStateEvent)Delegate.Combine(gameSenseConnection.OnConnectionBecameActive, new GameSenseConnection.ClientStateEvent(_gameSenseConnection_OnConnectionBecameActive));
         GameSenseConnection gameSenseConnection2 = _gameSenseConnection;
         gameSenseConnection2.OnConnectionBecameInactive = (GameSenseConnection.ClientStateEvent)Delegate.Combine(gameSenseConnection2.OnConnectionBecameInactive, new GameSenseConnection.ClientStateEvent(_gameSenseConnection_OnConnectionBecameInactive));
         _gameSenseConnection.SetEvents();
     }
References _colorProfiles, _gameSenseConnection, _gameSenseConnection_OnConnectionBecameActive(), _gameSenseConnection_OnConnectionBecameInactive(), GameSenseConnection.ClientStateEvent(), GameSenseConnection.OnConnectionBecameActive, GameSenseConnection.OnConnectionBecameInactive, and GameSenseConnection.SetEvents().