Terraria: System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync
WaitUntilCountOrTimeoutAsync()
async Task< bool > System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync (TaskNode asyncWaiter, int millisecondsTimeout, CancellationToken cancellationToken) inline private
Definition at line 371 of file SemaphoreSlim.cs.
    {
        await new ConfiguredNoThrowAwaiter<bool>(asyncWaiter.WaitAsync(TimeSpan.FromMilliseconds(millisecondsTimeout), cancellationToken));
        if (cancellationToken.IsCancellationRequested)
        {
            await TaskScheduler.Default;
        }
        if (asyncWaiter.IsCompleted)
        {
            return true;
        }
        lock (m_lockObjAndDisposed)
        {
            if (RemoveAsyncWaiter(asyncWaiter))
            {
                cancellationToken.ThrowIfCancellationRequested();
                return false;
            }
        }
        return await asyncWaiter.ConfigureAwait(continueOnCapturedContext: false);
    }
References System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.Tasks.TaskScheduler.Default, System.TimeSpan.FromMilliseconds(), System.Threading.Tasks.Task< TResult >.IsCompleted, System.Threading.SemaphoreSlim.m_lockObjAndDisposed, System.millisecondsTimeout, System.Threading.SemaphoreSlim.RemoveAsyncWaiter(), and System.Threading.Tasks.Task< TResult >.WaitAsync().
Referenced by System.Threading.SemaphoreSlim.WaitAsync().