Terraria: System.Threading.SemaphoreSlim.Release
Release() [1/2]
int System.Threading.SemaphoreSlim.Release () inline
Definition at line 393 of file SemaphoreSlim.cs.
    {
        return Release(1);
    }
References System.Threading.SemaphoreSlim.Release().
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore(), System.IO.BufferedStream.CopyToAsyncCore(), System.IO.Stream.FinishTrackingAsyncOperation(), System.IO.Strategies.BufferedFileStreamStrategy.FlushAsyncInternal(), System.IO.BufferedStream.FlushAsyncInternal(), System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(), System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.MoveNext(), System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.MoveNext(), System.IO.BufferedStream.ReadAsync(), System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync(), System.IO.BufferedStream.ReadAsync(), System.Security.Cryptography.CryptoStream.ReadAsyncInternal(), System.IO.Strategies.BufferedFileStreamStrategy.ReadFromNonSeekableAsync(), System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(), System.Threading.SemaphoreSlim.Release(), System.Net.WebSockets.WebSocketBase.SendFrameAsync(), System.Collections.Concurrent.BlockingCollection< T >.TryAddWithNoTimeValidation(), System.Collections.Concurrent.BlockingCollection< T >.TryTakeWithNoTimeValidation(), System.IO.Strategies.BufferedFileStreamStrategy.WriteAsync(), System.IO.BufferedStream.WriteAsync(), System.Security.Cryptography.CryptoStream.WriteAsyncInternal(), System.IO.Strategies.BufferedFileStreamStrategy.WriteToNonSeekableAsync(), and System.IO.BufferedStream.WriteToUnderlyingStreamAsync().