Terraria: System.Threading.SemaphoreSlim.WaitAsync
WaitAsync() [1/6]
Task System.Threading.SemaphoreSlim.WaitAsync () inline
Definition at line 270 of file SemaphoreSlim.cs.
    {
        return WaitAsync(-1, default(CancellationToken));
    }
References System.Threading.SemaphoreSlim.WaitAsync().
Referenced by System.IO.Stream.BeginReadInternal(), System.IO.Stream.BeginWriteInternal(), System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore(), System.IO.BufferedStream.CopyToAsyncCore(), System.IO.Strategies.BufferedFileStreamStrategy.FlushAsyncInternal(), System.IO.BufferedStream.FlushAsyncInternal(), System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(), System.IO.BufferedStream.ReadAsync(), System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync(), System.IO.BufferedStream.ReadAsync(), System.Security.Cryptography.CryptoStream.ReadAsyncInternal(), System.IO.Strategies.BufferedFileStreamStrategy.ReadFromNonSeekableAsync(), System.Net.WebSockets.WebSocketBase.SendFrameAsync(), System.Threading.SemaphoreSlim.Wait(), System.Threading.SemaphoreSlim.WaitAsync(), System.Threading.SemaphoreSlim.WaitAsync(), System.Threading.SemaphoreSlim.WaitAsync(), System.Threading.SemaphoreSlim.WaitAsync(), System.Threading.SemaphoreSlim.WaitAsync(), System.IO.Strategies.BufferedFileStreamStrategy.WriteAsync(), System.IO.BufferedStream.WriteAsync(), System.Security.Cryptography.CryptoStream.WriteAsyncInternal(), and System.IO.Strategies.BufferedFileStreamStrategy.WriteToNonSeekableAsync().