Terraria: System.Xml.Serialization.TypeDesc.TypeDesc
TypeDesc() [1/4]
System.Xml.Serialization.TypeDesc.TypeDesc (string name, string fullName, XmlSchemaType dataType, TypeKind kind, TypeDesc baseTypeDesc, TypeFlags flags, string formatterName) inline package
Definition at line 219 of file TypeDesc.cs.
    {
        _name = name.Replace('+', '.');
        _fullName = fullName.Replace('+', '.');
        _kind = kind;
        _baseTypeDesc = baseTypeDesc;
        _flags = flags;
        _isXsdType = kind == TypeKind.Primitive;
        if (_isXsdType)
        {
            _weight = 1;
        }
        else if (kind == TypeKind.Enum)
        {
            _weight = 2;
        }
        else if (_kind == TypeKind.Root)
        {
            _weight = -1;
        }
        else
        {
            _weight = ((baseTypeDesc != null) ? (baseTypeDesc.Weight + 1) : 0);
        }
        _dataType = dataType;
        _formatterName = formatterName;
    }
References System.Xml.Serialization.TypeDesc._baseTypeDesc, System.Xml.Serialization.TypeDesc._dataType, System.Xml.Serialization.TypeDesc._flags, System.Xml.Serialization.TypeDesc._formatterName, System.Xml.Serialization.TypeDesc._fullName, System.Xml.Serialization.TypeDesc._isXsdType, System.Xml.Serialization.TypeDesc._kind, System.Xml.Serialization.TypeDesc._name, System.Xml.Serialization.TypeDesc._weight, and System.Xml.Dictionary.
Referenced by System.Xml.Serialization.TypeDesc.CreateArrayTypeDesc(), System.Xml.Serialization.TypeDesc.GetNullableTypeDesc(), System.Xml.Serialization.SchemaImporter.MakeDerived(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElement(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitive().