Terraria: System.Xml.Serialization.TypeDesc.CheckSupported
CheckSupported()
void System.Xml.Serialization.TypeDesc.CheckSupported () inline package
Definition at line 285 of file TypeDesc.cs.
    {
        if (IsUnsupported)
        {
            if (Exception != null)
            {
                throw Exception;
            }
            throw new NotSupportedException(System.SR.Format(System.SR.XmlSerializerUnsupportedType, FullName));
        }
        if (_baseTypeDesc != null)
        {
            _baseTypeDesc.CheckSupported();
        }
        if (_arrayElementTypeDesc != null)
        {
            _arrayElementTypeDesc.CheckSupported();
        }
    }
References System.Xml.Serialization.TypeDesc._arrayElementTypeDesc, System.Xml.Serialization.TypeDesc._baseTypeDesc, System.Xml.Serialization.TypeDesc.CheckSupported(), System.Xml.Serialization.TypeDesc.Exception, System.SR.Format(), System.Xml.Serialization.TypeDesc.FullName, System.Xml.Serialization.TypeDesc.IsUnsupported, and System.SR.XmlSerializerUnsupportedType.
Referenced by System.Xml.Serialization.TypeDesc.CheckSupported().