Terraria: SmartCursorHelper.Step_MinecartTracks
Step_MinecartTracks()
static void SmartCursorHelper.Step_MinecartTracks (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
     {
         if ((providedInfo.item.type == 2340 || providedInfo.item.type == 2739) && focusedX == -1 && focusedY == -1)
         {
             _targets.Clear();
             Vector2 value = (Main.MouseWorld - providedInfo.Center).SafeNormalize(Vector2.UnitY);
             float num = Vector2.Dot(value, -Vector2.UnitY);
             bool flag = num >= 0.5f;
             bool flag2 = num <= -0.5f;
             float num2 = Vector2.Dot(value, Vector2.UnitX);
             bool flag3 = num2 >= 0.5f;
             bool flag4 = num2 <= -0.5f;
             bool flag5 = flag && flag4;
             bool flag6 = flag && flag3;
             bool flag7 = flag2 && flag4;
             bool flag8 = flag2 && flag3;
             if (flag5)
             {
                 flag4 = false;
             }
             if (flag6)
             {
                 flag3 = false;
             }
             if (flag7)
             {
                 flag4 = false;
             }
             if (flag8)
             {
                 flag3 = false;
             }
             bool flag9 = false;
             if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].active() && Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].type == 314)
             {
                 flag9 = true;
             }
             if (!flag9)
             {
                 for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                 {
                     for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                     {
                         Tile tile = Main.tile[i, j];
                         if (tile.active() && tile.type == 314)
{
                             bool flag10 = Main.tile[i + 1, j + 1].active() && Main.tile[i + 1, j + 1].type == 314;
                             bool flag11 = Main.tile[i + 1, j - 1].active() && Main.tile[i + 1, j - 1].type == 314;
                             bool flag12 = Main.tile[i - 1, j + 1].active() && Main.tile[i - 1, j + 1].type == 314;
                             bool flag13 = Main.tile[i - 1, j - 1].active() && Main.tile[i - 1, j - 1].type == 314;
                             if (flag5 && (!Main.tile[i - 1, j - 1].active() || Main.tileCut[Main.tile[i - 1, j - 1].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i - 1, j - 1].type]) && !(!flag10 && flag11) && !flag12)
{
                                 _targets.Add(new Tuple<int, int>(i - 1, j - 1));
                             }
                             if (flag4 && (!Main.tile[i - 1, j].active() || Main.tileCut[Main.tile[i - 1, j].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i - 1, j].type]))
{
                                 _targets.Add(new Tuple<int, int>(i - 1, j));
                             }
                             if (flag7 && (!Main.tile[i - 1, j + 1].active() || Main.tileCut[Main.tile[i - 1, j + 1].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i - 1, j + 1].type]) && !(!flag11 && flag10) && !flag13)
{
                                 _targets.Add(new Tuple<int, int>(i - 1, j + 1));
                             }
                             if (flag6 && (!Main.tile[i + 1, j - 1].active() || Main.tileCut[Main.tile[i + 1, j - 1].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i + 1, j - 1].type]) && !(!flag12 && flag13) && !flag10)
{
                                 _targets.Add(new Tuple<int, int>(i + 1, j - 1));
                             }
                             if (flag3 && (!Main.tile[i + 1, j].active() || Main.tileCut[Main.tile[i + 1, j].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i + 1, j].type]))
{
                                 _targets.Add(new Tuple<int, int>(i + 1, j));
                             }
                             if (flag8 && (!Main.tile[i + 1, j + 1].active() || Main.tileCut[Main.tile[i + 1, j + 1].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i + 1, j + 1].type]) && !(!flag13 && flag12) && !flag11)
{
                                 _targets.Add(new Tuple<int, int>(i + 1, j + 1));
                             }
                         }
                     }
                 }
             }
             if (_targets.Count > 0)
             {
                 float num3 = -1f;
                 Tuple<int, int> tuple = _targets[0];
                 for (int k = 0; k < _targets.Count; k++)
                 {
                     if ((!Main.tile[_targets[k].Item1, _targets[k].Item2 - 1].active() || Main.tile[_targets[k].Item1, _targets[k].Item2 - 1].type != 314) && (!Main.tile[_targets[k].Item1, _targets[k].Item2 + 1].active() || Main.tile[_targets[k].Item1, _targets[k].Item2 + 1].type != 314))
                     {
                         float num4 = Vector2.Distance(new Vector2(_targets[k].Item1, _targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                         if (num3 == -1f || num4 < num3)
{
                             num3 = num4;
                             tuple = _targets[k];
                         }
                     }
                 }
                 if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY) && num3 != -1f)
                 {
                     focusedX = tuple.Item1;
                     focusedY = tuple.Item2;
                 }
             }
             _targets.Clear();
         }
         if (providedInfo.item.type != 2492 || focusedX != -1 || focusedY != -1)
         {
             return;
         }
         _targets.Clear();
         bool flag14 = false;
         if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].active() && Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].type == 314)
         {
             flag14 = true;
         }
         if (!flag14)
         {
             for (int l = providedInfo.reachableStartX; l <= providedInfo.reachableEndX; l++)
             {
                 for (int m = providedInfo.reachableStartY; m <= providedInfo.reachableEndY; m++)
                 {
                     Tile tile2 = Main.tile[l, m];
                     if (tile2.active() && tile2.type == 314)
                     {
                         if (!Main.tile[l - 1, m].active() || Main.tileCut[Main.tile[l - 1, m].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[l - 1, m].type])
{
                             _targets.Add(new Tuple<int, int>(l - 1, m));
                         }
                         if (!Main.tile[l + 1, m].active() || Main.tileCut[Main.tile[l + 1, m].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[l + 1, m].type])
{
                             _targets.Add(new Tuple<int, int>(l + 1, m));
                         }
                     }
                 }
             }
         }
         if (_targets.Count > 0)
         {
             float num5 = -1f;
             Tuple<int, int> tuple2 = _targets[0];
             for (int n = 0; n < _targets.Count; n++)
             {
                 if ((!Main.tile[_targets[n].Item1, _targets[n].Item2 - 1].active() || Main.tile[_targets[n].Item1, _targets[n].Item2 - 1].type != 314) && (!Main.tile[_targets[n].Item1, _targets[n].Item2 + 1].active() || Main.tile[_targets[n].Item1, _targets[n].Item2 + 1].type != 314))
                 {
                     float num6 = Vector2.Distance(new Vector2(_targets[n].Item1, _targets[n].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                     if (num5 == -1f || num6 < num5)
                     {
                         num5 = num6;
                         tuple2 = _targets[n];
                     }
                 }
             }
             if (Collision.InTileBounds(tuple2.Item1, tuple2.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY) && num5 != -1f)
             {
                 focusedX = tuple2.Item1;
                 focusedY = tuple2.Item2;
             }
         }
         _targets.Clear();
     }
References _targets, Tile.active(), TileID.Sets.BreakableWhenPlacing, SmartCursorHelper.SmartCursorUsageInfo.Center, Collision.InTileBounds(), SmartCursorHelper.SmartCursorUsageInfo.item, SmartCursorHelper.SmartCursorUsageInfo.mouse, Main.MouseWorld, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Main.tile, Main.tileCut, Item.type, and Tile.type.
Referenced by SmartCursorLookup().