Terraria: SmartCursorHelper.Step_ClayPots
Step_ClayPots()
static void SmartCursorHelper.Step_ClayPots (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
     {
         if (providedInfo.item.createTile != 78 || focusedX != -1 || focusedY != -1)
         {
             return;
         }
         _targets.Clear();
         bool flag = false;
         if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].active())
         {
             flag = true;
         }
         if (!Collision.InTileBounds(providedInfo.screenTargetX, providedInfo.screenTargetY, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
         {
             flag = true;
         }
         if (!flag)
         {
             for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
             {
                 for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                 {
                     Tile tile = Main.tile[i, j];
                     Tile tile2 = Main.tile[i, j + 1];
                     if ((!tile.active() || Main.tileCut[tile.type] || TileID.Sets.BreakableWhenPlacing[tile.type]) && tile2.nactive() && !tile2.halfBrick() && tile2.slope() == 0 && Main.tileSolid[tile2.type])
                     {
                         _targets.Add(new Tuple<int, int>(i, j));
                     }
                 }
             }
         }
         if (_targets.Count > 0)
         {
             float num = -1f;
             Tuple<int, int> tuple = _targets[0];
             for (int k = 0; k < _targets.Count; k++)
             {
                 if (Collision.EmptyTile(_targets[k].Item1, _targets[k].Item2, ignoreTiles: true))
                 {
                     float num2 = Vector2.Distance(new Vector2(_targets[k].Item1, _targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                     if (num == -1f || num2 < num)
                     {
                         num = num2;
                         tuple = _targets[k];
                     }
                 }
             }
             if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY) && num != -1f)
             {
                 focusedX = tuple.Item1;
                 focusedY = tuple.Item2;
             }
         }
         _targets.Clear();
     }
References _targets, Tile.active(), TileID.Sets.BreakableWhenPlacing, Item.createTile, Collision.EmptyTile(), Tile.halfBrick(), Collision.InTileBounds(), SmartCursorHelper.SmartCursorUsageInfo.item, SmartCursorHelper.SmartCursorUsageInfo.mouse, Tile.nactive(), SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Tile.slope(), Main.tile, Main.tileCut, Main.tileSolid, and Tile.type.
Referenced by SmartCursorLookup().