Terraria: SmartCursorHelper.Step_Torch
Step_Torch()
static void SmartCursorHelper.Step_Torch (SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
     {
         int reachableStartX = providedInfo.reachableStartX;
         int reachableStartY = providedInfo.reachableStartY;
         int reachableEndX = providedInfo.reachableEndX;
         int reachableEndY = providedInfo.reachableEndY;
         _ = providedInfo.screenTargetX;
         _ = providedInfo.screenTargetY;
         if (providedInfo.item.createTile != 4 || fX != -1 || fY != -1)
         {
             return;
         }
         _targets.Clear();
         bool flag = providedInfo.item.type != 1333 && providedInfo.item.type != 523 && providedInfo.item.type != 4384;
         for (int i = reachableStartX; i <= reachableEndX; i++)
         {
             for (int j = reachableStartY; j <= reachableEndY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 Tile tile2 = Main.tile[i - 1, j];
                 Tile tile3 = Main.tile[i + 1, j];
                 Tile tile4 = Main.tile[i, j + 1];
                 if (tile.active() && !TileID.Sets.BreakableWhenPlacing[tile.type] && (!Main.tileCut[tile.type] || tile.type == 82 || tile.type == 83))
                 {
                     continue;
                 }
                 bool flag2 = false;
                 for (int k = i - 8; k <= i + 8; k++)
                 {
                     for (int l = j - 8; l <= j + 8; l++)
                     {
                         if (Main.tile[k, l] != null && Main.tile[k, l].type == 4)
{
                             flag2 = true;
                             break;
                         }
                     }
                     if (flag2)
                     {
                         break;
                     }
                 }
                 if (!flag2 && (!flag || tile.liquid <= 0) && (tile.wall > 0 || (tile2.active() && (tile2.slope() == 0 || tile2.slope() % 2 != 1) && ((Main.tileSolid[tile2.type] && !Main.tileNoAttach[tile2.type] && !Main.tileSolidTop[tile2.type] && !TileID.Sets.NotReallySolid[tile2.type]) || TileID.Sets.IsBeam[tile2.type] || (WorldGen.IsTreeType(tile2.type) && WorldGen.IsTreeType(Main.tile[i - 1, j - 1].type) && WorldGen.IsTreeType(Main.tile[i - 1, j + 1].type)))) || (tile3.active() && (tile3.slope() == 0 || tile3.slope() % 2 != 0) && ((Main.tileSolid[tile3.type] && !Main.tileNoAttach[tile3.type] && !Main.tileSolidTop[tile3.type] && !TileID.Sets.NotReallySolid[tile3.type]) || TileID.Sets.IsBeam[tile3.type] || (WorldGen.IsTreeType(tile3.type) && WorldGen.IsTreeType(Main.tile[i + 1, j - 1].type) && WorldGen.IsTreeType(Main.tile[i + 1, j + 1].type)))) || (tile4.active() && Main.tileSolid[tile4.type] && !Main.tileNoAttach[tile4.type] && (!Main.tileSolidTop[tile4.type] || (TileID.Sets.Platforms[tile4.type] && tile4.slope() == 0)) && !TileID.Sets.NotReallySolid[tile4.type] && !tile4.halfBrick() && tile4.slope() == 0)) && tile.type != 4)
                 {
                     _targets.Add(new Tuple<int, int>(i, j));
                 }
             }
         }
         if (_targets.Count > 0)
         {
             float num = -1f;
             Tuple<int, int> tuple = _targets[0];
             for (int m = 0; m < _targets.Count; m++)
             {
                 float num2 = Vector2.Distance(new Vector2(_targets[m].Item1, _targets[m].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                 if (num == -1f || num2 < num)
                 {
                     num = num2;
                     tuple = _targets[m];
                 }
             }
             if (Collision.InTileBounds(tuple.Item1, tuple.Item2, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
             {
                 fX = tuple.Item1;
                 fY = tuple.Item2;
             }
         }
         _targets.Clear();
     }
References _targets, Tile.active(), TileID.Sets.BreakableWhenPlacing, Item.createTile, Tile.halfBrick(), Collision.InTileBounds(), TileID.Sets.IsBeam, WorldGen.IsTreeType(), SmartCursorHelper.SmartCursorUsageInfo.item, Tile.liquid, SmartCursorHelper.SmartCursorUsageInfo.mouse, TileID.Sets.NotReallySolid, TileID.Sets.Platforms, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Tile.slope(), Main.tile, Main.tileCut, Main.tileNoAttach, Main.tileSolid, Main.tileSolidTop, Item.type, Tile.type, and Tile.wall.
Referenced by SmartCursorLookup().