Terraria: SmartCursorHelper.Step_Boulders
Step_Boulders()
static void SmartCursorHelper.Step_Boulders (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
     {
         if (providedInfo.item.createTile <= -1 || providedInfo.item.createTile >= TileID.Count || !TileID.Sets.Boulders[providedInfo.item.createTile] || focusedX != -1 || focusedY != -1)
         {
             return;
         }
         _targets.Clear();
         for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
         {
             for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
             {
                 Tile tile = Main.tile[i, j + 1];
                 Tile tile2 = Main.tile[i + 1, j + 1];
                 bool flag = true;
                 if (!tile2.nactive() || !tile.nactive())
                 {
                     flag = false;
                 }
                 if (tile2.slope() > 0 || tile.slope() > 0 || tile2.halfBrick() || tile.halfBrick())
                 {
                     flag = false;
                 }
                 if ((!Main.tileSolid[tile2.type] && !Main.tileTable[tile2.type]) || (!Main.tileSolid[tile.type] && !Main.tileTable[tile.type]))
                 {
                     flag = false;
                 }
                 if (Main.tileNoAttach[tile2.type] || Main.tileNoAttach[tile.type])
                 {
                     flag = false;
                 }
                 for (int k = i; k <= i + 1; k++)
                 {
                     for (int l = j - 1; l <= j; l++)
                     {
                         Tile tile3 = Main.tile[k, l];
                         if (tile3.active() && !Main.tileCut[tile3.type])
{
                             flag = false;
                         }
                     }
                 }
                 int x = i * 16;
                 int y = j * 16 - 16;
                 int width = 32;
                 int height = 32;
                 Rectangle value = new Rectangle(x, y, width, height);
                 for (int m = 0; m < 255; m++)
                 {
                     Player player = Main.player[m];
                     if (player.active && !player.dead && player.Hitbox.Intersects(value))
                     {
                         flag = false;
                         break;
                     }
                 }
                 if (flag)
                 {
                     _targets.Add(new Tuple<int, int>(i, j));
                 }
             }
         }
         if (_targets.Count > 0)
         {
             float num = -1f;
             Tuple<int, int> tuple = _targets[0];
             for (int n = 0; n < _targets.Count; n++)
             {
                 float num2 = Vector2.Distance(new Vector2(_targets[n].Item1, _targets[n].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                 if (num == -1f || num2 < num)
                 {
                     num = num2;
                     tuple = _targets[n];
                 }
             }
             if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
             {
                 focusedX = tuple.Item1;
                 focusedY = tuple.Item2;
             }
         }
         _targets.Clear();
     }
References _targets, Entity.active, Tile.active(), TileID.Sets.Boulders, TileID.Count, Item.createTile, Player.dead, Tile.halfBrick(), Entity.Hitbox, Collision.InTileBounds(), SmartCursorHelper.SmartCursorUsageInfo.item, SmartCursorHelper.SmartCursorUsageInfo.mouse, Tile.nactive(), Main.player, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Tile.slope(), Main.tile, Main.tileCut, Main.tileNoAttach, Main.tileSolid, Main.tileTable, and Tile.type.
Referenced by SmartCursorLookup().