Terraria: System.Data.PropertyCollection.Clone
Clone()
override object System.Data.PropertyCollection.Clone () inline virtual
Reimplemented from System.Collections.Hashtable.
Definition at line 20 of file PropertyCollection.cs.
    {
        PropertyCollection propertyCollection = new PropertyCollection();
        IDictionaryEnumerator dictionaryEnumerator = GetEnumerator();
        try
        {
            while (dictionaryEnumerator.MoveNext())
            {
                DictionaryEntry dictionaryEntry = (DictionaryEntry)dictionaryEnumerator.Current;
                propertyCollection.Add(dictionaryEntry.Key, dictionaryEntry.Value);
            }
            return propertyCollection;
        }
        finally
        {
            IDisposable disposable = dictionaryEnumerator as IDisposable;
            if (disposable != null)
            {
                disposable.Dispose();
            }
        }
    }
References System.Data.PropertyCollection.PropertyCollection(), System.Runtime.Serialization.Dictionary, System.IDisposable.Dispose(), and System.Collections.Hashtable.GetEnumerator().