Terraria: System.Net.Http.CancellationHelper.ThrowIfCancellationRequested
ThrowIfCancellationRequested()
static void System.Net.Http.CancellationHelper.ThrowIfCancellationRequested (CancellationToken cancellationToken) inline static package
Definition at line 29 of file CancellationHelper.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            ThrowOperationCanceledException(null, cancellationToken);
        }
    }
References System.cancellationToken, and System.Net.Http.CancellationHelper.ThrowOperationCanceledException().
Referenced by System.Net.Http.HttpConnection.ConnectionCloseReadStream.CompleteCopyToAsync(), System.Net.Http.HttpConnection.RawConnectionStream.CompleteCopyToAsync(), System.Net.Http.HttpConnection.ContentLengthReadStream.DrainAsync(), System.Net.Http.HttpConnection.ConnectionCloseReadStream.ReadAsync(), System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(), System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer(), System.Net.Http.HttpConnection.SendAsyncCore(), and System.Net.Http.Http2Connection.Http2Stream.WaitFor100ContinueAsync().