Terraria: System.Reflection.RuntimeModule.ResolveSignature
ResolveSignature()
override byte[] System.Reflection.RuntimeModule.ResolveSignature (int metadataToken) inline virtual inherited
Reimplemented from System.Reflection.Module.
Definition at line 127 of file RuntimeModule.cs.
    {
        MetadataToken metadataToken2 = new MetadataToken(metadataToken);
        if (!MetadataImport.IsValidToken(metadataToken2))
        {
            throw new ArgumentOutOfRangeException("metadataToken", SR.Format(SR.Argument_InvalidToken, metadataToken2, this));
        }
        if (!metadataToken2.IsMemberRef && !metadataToken2.IsMethodDef && !metadataToken2.IsTypeSpec && !metadataToken2.IsSignature && !metadataToken2.IsFieldDef)
        {
            throw new ArgumentException(SR.Format(SR.Argument_InvalidToken, metadataToken2, this), "metadataToken");
        }
        ConstArray constArray = ((!metadataToken2.IsMemberRef) ? MetadataImport.GetSignatureFromToken(metadataToken) : MetadataImport.GetMemberRefProps(metadataToken));
        byte[] array = new byte[constArray.Length];
        for (int i = 0; i < constArray.Length; i++)
        {
            array[i] = constArray[i];
        }
        return array;
    }
References System.SR.Argument_InvalidToken, System.array, System.SR.Format(), System.Reflection.MetadataImport.GetMemberRefProps(), System.Reflection.MetadataImport.GetSignatureFromToken(), System.Reflection.MetadataImport.IsValidToken(), and System.Reflection.RuntimeModule.MetadataToken.
Referenced by System.Reflection.Emit.ModuleBuilder.ResolveSignature().