Terraria: System.Reflection.RuntimeModule.ResolveString
ResolveString()
override string System.Reflection.RuntimeModule.ResolveString (int metadataToken) inline virtual inherited
Reimplemented from System.Reflection.Module.
Definition at line 338 of file RuntimeModule.cs.
    {
        MetadataToken metadataToken2 = new MetadataToken(metadataToken);
        if (!metadataToken2.IsString)
        {
            throw new ArgumentException(SR.Format(SR.Argument_ResolveString, metadataToken, this));
        }
        if (!MetadataImport.IsValidToken(metadataToken2))
        {
            throw new ArgumentOutOfRangeException("metadataToken", SR.Format(SR.Argument_InvalidToken, metadataToken2, this));
        }
        string userString = MetadataImport.GetUserString(metadataToken);
        if (userString == null)
        {
            throw new ArgumentException(SR.Format(SR.Argument_ResolveString, metadataToken, this));
        }
        return userString;
    }
References System.SR.Argument_InvalidToken, System.SR.Argument_ResolveString, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Reflection.MetadataImport.GetUserString(), System.Reflection.MetadataImport.IsValidToken(), and System.Reflection.RuntimeModule.MetadataToken.
Referenced by System.Reflection.Emit.ModuleBuilder.ResolveString().