Terraria: System.Reflection.RuntimeModule.ResolveType
ResolveType() [2/3]
override Type System.Reflection.RuntimeModule.ResolveType (int metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) inline inherited
Definition at line 267 of file RuntimeModule.cs.
    {
        try
        {
            MetadataToken metadataToken2 = new MetadataToken(metadataToken);
            if (metadataToken2.IsGlobalTypeDefToken)
            {
                throw new ArgumentException(SR.Format(SR.Argument_ResolveModuleType, metadataToken2), "metadataToken");
            }
            if (!metadataToken2.IsTypeDef && !metadataToken2.IsTypeSpec && !metadataToken2.IsTypeRef)
            {
                throw new ArgumentException(SR.Format(SR.Argument_ResolveType, metadataToken2, this), "metadataToken");
            }
            RuntimeTypeHandle[] typeInstantiationContext = null;
            RuntimeTypeHandle[] methodInstantiationContext = null;
            if (genericTypeArguments != null && genericTypeArguments.Length != 0)
            {
                typeInstantiationContext = ConvertToTypeHandleArray(genericTypeArguments);
            }
            if (genericMethodArguments != null && genericMethodArguments.Length != 0)
            {
                methodInstantiationContext = ConvertToTypeHandleArray(genericMethodArguments);
            }
            return GetModuleHandleImpl().ResolveTypeHandle(metadataToken, typeInstantiationContext, methodInstantiationContext).GetRuntimeType();
        }
        catch (BadImageFormatException innerException)
        {
            throw new ArgumentException(SR.Argument_BadImageFormatExceptionResolve, innerException);
        }
    }
References System.SR.Argument_BadImageFormatExceptionResolve, System.SR.Argument_ResolveModuleType, System.SR.Argument_ResolveType, System.Reflection.RuntimeModule.ConvertToTypeHandleArray(), System.SR.Format(), System.Reflection.RuntimeModule.GetModuleHandleImpl(), and System.Reflection.RuntimeModule.MetadataToken.
Referenced by System.Reflection.RuntimeCustomAttributeData.RuntimeCustomAttributeData(), System.Reflection.CustomAttribute.FilterCustomAttributeRecord(), System.Reflection.CustomAttribute.GetAttributeUsage(), System.Reflection.RuntimeModule.ResolveField(), System.Reflection.RuntimeModule.ResolveLiteralField(), System.Reflection.RuntimeModule.ResolveMember(), System.Reflection.RuntimeModule.ResolveMethod(), and System.Reflection.Emit.ModuleBuilder.ResolveType().