Terraria: System.Reflection.RuntimeModule.ResolveMethod
ResolveMethod() [2/3]
unsafe override MethodBase System.Reflection.RuntimeModule.ResolveMethod (int metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) inline inherited
Definition at line 148 of file RuntimeModule.cs.
    {
        try
        {
            MetadataToken metadataToken2 = new MetadataToken(metadataToken);
            if (!metadataToken2.IsMethodDef && !metadataToken2.IsMethodSpec)
            {
                if (!metadataToken2.IsMemberRef)
                {
                    throw new ArgumentException(SR.Format(SR.Argument_ResolveMethod, metadataToken2, this), "metadataToken");
                }
                if (*(byte*)(void*)MetadataImport.GetMemberRefProps(metadataToken2).Signature == 6)
                {
                    throw new ArgumentException(SR.Format(SR.Argument_ResolveMethod, metadataToken2, this), "metadataToken");
                }
            }
            RuntimeTypeHandle[] typeInstantiationContext = null;
            RuntimeTypeHandle[] methodInstantiationContext = null;
            if (genericTypeArguments != null && genericTypeArguments.Length != 0)
            {
                typeInstantiationContext = ConvertToTypeHandleArray(genericTypeArguments);
            }
            if (genericMethodArguments != null && genericMethodArguments.Length != 0)
            {
                methodInstantiationContext = ConvertToTypeHandleArray(genericMethodArguments);
            }
            IRuntimeMethodInfo methodInfo = new ModuleHandle(this).ResolveMethodHandle(metadataToken2, typeInstantiationContext, methodInstantiationContext).GetMethodInfo();
            Type type = RuntimeMethodHandle.GetDeclaringType(methodInfo);
            if (type.IsGenericType || type.IsArray)
            {
                MetadataToken metadataToken3 = new MetadataToken(MetadataImport.GetParentToken(metadataToken2));
                if (metadataToken2.IsMethodSpec)
                {
                    metadataToken3 = new MetadataToken(MetadataImport.GetParentToken(metadataToken3));
                }
                type = ResolveType(metadataToken3, genericTypeArguments, genericMethodArguments);
            }
            return RuntimeType.GetMethodBase(type as RuntimeType, methodInfo);
        }
        catch (BadImageFormatException innerException)
        {
            throw new ArgumentException(SR.Argument_BadImageFormatExceptionResolve, innerException);
        }
    }
References System.SR.Argument_BadImageFormatExceptionResolve, System.SR.Argument_ResolveMethod, System.Reflection.RuntimeModule.ConvertToTypeHandleArray(), System.SR.Format(), System.RuntimeMethodHandle.GetDeclaringType(), System.Reflection.MetadataImport.GetMemberRefProps(), System.RuntimeType.GetMethodBase(), System.RuntimeMethodHandle.GetMethodInfo(), System.Reflection.MetadataImport.GetParentToken(), System.Reflection.RuntimeModule.MetadataToken, System.Reflection.Module.ModuleHandle, System.ModuleHandle.ResolveMethodHandle(), System.Reflection.RuntimeModule.ResolveType(), System.Reflection.ConstArray.Signature, and System.type.
Referenced by System.Reflection.RuntimeCustomAttributeData.RuntimeCustomAttributeData(), System.Reflection.CustomAttribute.FilterCustomAttributeRecord(), System.Reflection.RuntimeModule.ResolveMember(), and System.Reflection.Emit.ModuleBuilder.ResolveMethod().