Terraria: System.Reflection.RuntimeModule.ResolveField
ResolveField() [2/3]
unsafe override FieldInfo System.Reflection.RuntimeModule.ResolveField (int metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) inline inherited
Definition at line 216 of file RuntimeModule.cs.
    {
        try
        {
            MetadataToken metadataToken2 = new MetadataToken(metadataToken);
            if (!MetadataImport.IsValidToken(metadataToken2))
            {
                throw new ArgumentOutOfRangeException("metadataToken", SR.Format(SR.Argument_InvalidToken, metadataToken2, this));
            }
            RuntimeTypeHandle[] typeInstantiationContext = null;
            RuntimeTypeHandle[] methodInstantiationContext = null;
            if (genericTypeArguments != null && genericTypeArguments.Length != 0)
            {
                typeInstantiationContext = ConvertToTypeHandleArray(genericTypeArguments);
            }
            if (genericMethodArguments != null && genericMethodArguments.Length != 0)
            {
                methodInstantiationContext = ConvertToTypeHandleArray(genericMethodArguments);
            }
            ModuleHandle moduleHandle = new ModuleHandle(this);
            if (!metadataToken2.IsFieldDef)
            {
                if (!metadataToken2.IsMemberRef)
                {
                    throw new ArgumentException(SR.Format(SR.Argument_ResolveField, metadataToken2, this), "metadataToken");
                }
                if (*(byte*)(void*)MetadataImport.GetMemberRefProps(metadataToken2).Signature != 6)
                {
                    throw new ArgumentException(SR.Format(SR.Argument_ResolveField, metadataToken2, this), "metadataToken");
                }
            }
            IRuntimeFieldInfo runtimeFieldInfo = moduleHandle.ResolveFieldHandle(metadataToken, typeInstantiationContext, methodInstantiationContext).GetRuntimeFieldInfo();
            RuntimeType runtimeType = RuntimeFieldHandle.GetApproxDeclaringType(runtimeFieldInfo.Value);
            if (runtimeType.IsGenericType || runtimeType.IsArray)
            {
                int parentToken = ModuleHandle.GetMetadataImport(this).GetParentToken(metadataToken);
                runtimeType = (RuntimeType)ResolveType(parentToken, genericTypeArguments, genericMethodArguments);
            }
            return RuntimeType.GetFieldInfo(runtimeType, runtimeFieldInfo);
        }
        catch (MissingFieldException)
        {
            return ResolveLiteralField(metadataToken, genericTypeArguments, genericMethodArguments);
        }
        catch (BadImageFormatException innerException)
        {
            throw new ArgumentException(SR.Argument_BadImageFormatExceptionResolve, innerException);
        }
    }
References System.SR.Argument_BadImageFormatExceptionResolve, System.SR.Argument_InvalidToken, System.SR.Argument_ResolveField, System.Reflection.RuntimeModule.ConvertToTypeHandleArray(), System.SR.Format(), System.RuntimeFieldHandle.GetApproxDeclaringType(), System.RuntimeType.GetFieldInfo(), System.Reflection.MetadataImport.GetMemberRefProps(), System.ModuleHandle.GetMetadataImport(), System.Reflection.MetadataImport.IsValidToken(), System.Reflection.RuntimeModule.MetadataToken, System.Reflection.Module.ModuleHandle, System.Reflection.RuntimeModule.ResolveLiteralField(), System.Reflection.RuntimeModule.ResolveType(), System.Reflection.RuntimeModule.RuntimeType, and System.Reflection.ConstArray.Signature.
Referenced by System.Reflection.Emit.ModuleBuilder.ResolveField(), and System.Reflection.RuntimeModule.ResolveMember().