Terraria: System.Xml.HtmlUtf8RawTextWriterIndent.WriteIndent
WriteIndent()
void System.Xml.HtmlUtf8RawTextWriterIndent.WriteIndent () inline private
Definition at line 116 of file HtmlUtf8RawTextWriterIndent.cs.
    {
        RawText(_newLineChars);
        for (int num = _indentLevel; num > 0; num--)
        {
            RawText(_indentChars);
        }
    }
References System.Xml.HtmlUtf8RawTextWriterIndent._indentChars, System.Xml.HtmlUtf8RawTextWriterIndent._indentLevel, System.Xml.XmlUtf8RawTextWriter._newLineChars, and System.Xml.XmlUtf8RawTextWriter.RawText().
Referenced by System.Xml.HtmlUtf8RawTextWriterIndent.StartElementContent(), System.Xml.HtmlUtf8RawTextWriterIndent.WriteEndElement(), System.Xml.HtmlUtf8RawTextWriterIndent.WriteStartAttribute(), and System.Xml.HtmlUtf8RawTextWriterIndent.WriteStartElement().