Terraria: System.Xml.HtmlUtf8RawTextWriterIndent.WriteStartElement
WriteStartElement() [3/4]
override void System.Xml.HtmlUtf8RawTextWriterIndent.WriteStartElement (string prefix, string localName, string ns) inline
Definition at line 27 of file HtmlUtf8RawTextWriterIndent.cs.
    {
        _elementScope.Push((byte)_currentElementProperties);
        if (ns.Length == 0)
        {
            _currentElementProperties = (ElementProperties)HtmlUtf8RawTextWriter._elementPropertySearch.FindCaseInsensitiveString(localName);
            if (_endBlockPos == _bufPos && (_currentElementProperties & ElementProperties.BLOCK_WS) != 0)
            {
                WriteIndent();
            }
            _indentLevel++;
            _bufBytes[_bufPos++] = 60;
        }
        else
        {
            _currentElementProperties = (ElementProperties)192u;
            if (_endBlockPos == _bufPos)
            {
                WriteIndent();
            }
            _indentLevel++;
            _bufBytes[_bufPos++] = 60;
            if (prefix.Length != 0)
            {
                RawText(prefix);
                _bufBytes[_bufPos++] = 58;
            }
        }
        RawText(localName);
        _attrEndPos = _bufPos;
    }
References System.Xml.XmlUtf8RawTextWriter._attrEndPos, System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.HtmlUtf8RawTextWriter._currentElementProperties, System.Xml.HtmlUtf8RawTextWriter._elementPropertySearch, System.Xml.HtmlUtf8RawTextWriter._elementScope, System.Xml.HtmlUtf8RawTextWriterIndent._endBlockPos, System.Xml.HtmlUtf8RawTextWriterIndent._indentLevel, System.Xml.Dictionary, System.prefix, System.Xml.ByteStack.Push(), System.Xml.XmlUtf8RawTextWriter.RawText(), and System.Xml.HtmlUtf8RawTextWriterIndent.WriteIndent().