Terraria: System.Reflection.RuntimeModule.ResolveMember
ResolveMember() [2/3]
unsafe override MemberInfo System.Reflection.RuntimeModule.ResolveMember (int metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) inline inherited
Definition at line 299 of file RuntimeModule.cs.
    {
        MetadataToken metadataToken2 = new MetadataToken(metadataToken);
        if (metadataToken2.IsProperty)
        {
            throw new ArgumentException(SR.InvalidOperation_PropertyInfoNotAvailable);
        }
        if (metadataToken2.IsEvent)
        {
            throw new ArgumentException(SR.InvalidOperation_EventInfoNotAvailable);
        }
        if (metadataToken2.IsMethodSpec || metadataToken2.IsMethodDef)
        {
            return ResolveMethod(metadataToken, genericTypeArguments, genericMethodArguments);
        }
        if (metadataToken2.IsFieldDef)
        {
            return ResolveField(metadataToken, genericTypeArguments, genericMethodArguments);
        }
        if (metadataToken2.IsTypeRef || metadataToken2.IsTypeDef || metadataToken2.IsTypeSpec)
        {
            return ResolveType(metadataToken, genericTypeArguments, genericMethodArguments);
        }
        if (metadataToken2.IsMemberRef)
        {
            if (!MetadataImport.IsValidToken(metadataToken2))
            {
                throw new ArgumentOutOfRangeException("metadataToken", SR.Format(SR.Argument_InvalidToken, metadataToken2, this));
            }
            if (*(byte*)(void*)MetadataImport.GetMemberRefProps(metadataToken2).Signature == 6)
            {
                return ResolveField(metadataToken2, genericTypeArguments, genericMethodArguments);
            }
            return ResolveMethod(metadataToken2, genericTypeArguments, genericMethodArguments);
        }
        throw new ArgumentException(SR.Format(SR.Argument_ResolveMember, metadataToken2, this), "metadataToken");
    }
References System.SR.Argument_InvalidToken, System.SR.Argument_ResolveMember, System.SR.Format(), System.Reflection.MetadataImport.GetMemberRefProps(), System.SR.InvalidOperation_EventInfoNotAvailable, System.SR.InvalidOperation_PropertyInfoNotAvailable, System.Reflection.MetadataImport.IsValidToken(), System.Reflection.RuntimeModule.MetadataToken, System.Reflection.RuntimeModule.ResolveField(), System.Reflection.RuntimeModule.ResolveMethod(), System.Reflection.RuntimeModule.ResolveType(), and System.Reflection.ConstArray.Signature.
Referenced by System.Reflection.Emit.ModuleBuilder.ResolveMember().