Terraria: LanternNight.UpdateTime
UpdateTime()
static void LanternNight.UpdateTime () inline static
     {
         if (GenuineLanterns && !LanternsCanPersist())
         {
             GenuineLanterns = false;
         }
         if (_wasLanternNight != LanternsUp)
         {
             if (Main.netMode != 2)
             {
                 if (LanternsUp)
                 {
                     SkyManager.Instance.Activate("Lantern", default(Vector2));
                 }
                 else
                 {
                     SkyManager.Instance.Deactivate("Lantern");
                 }
             }
             else
             {
                 NetMessage.SendData(7);
             }
         }
         _wasLanternNight = LanternsUp;
     }
References _wasLanternNight, EffectManager< T >.Activate(), EffectManager< T >.Deactivate(), GenuineLanterns, SkyManager.Instance, LanternsCanPersist(), LanternsUp, Main.netMode, and NetMessage.SendData().
Referenced by Main.UpdateTime().