Terraria: Microsoft.Xna.Framework.Color.PackHelper
PackHelper()
static uint Microsoft.Xna.Framework.Color.PackHelper (float vectorX, float vectorY, float vectorZ, float vectorW) inline static private
Definition at line 437 of file Color.cs.
    {
        uint num = PackUtils.PackUNorm(255f, vectorX);
        uint num2 = PackUtils.PackUNorm(255f, vectorY) << 8;
        uint num3 = PackUtils.PackUNorm(255f, vectorZ) << 16;
        uint num4 = PackUtils.PackUNorm(255f, vectorW) << 24;
        return num | num2 | num3 | num4;
    }
Referenced by Microsoft.Xna.Framework.Color.Color(), Microsoft.Xna.Framework.Color.Color(), Microsoft.Xna.Framework.Color.Color(), Microsoft.Xna.Framework.Color.Color(), Microsoft.Xna.Framework.Color.FromNonPremultiplied(), and Microsoft.Xna.Framework.Color.PackFromVector4().