Terraria: System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteText
WriteText() [1/2]
void System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteText (string s) inline
Definition at line 24 of file XmlBinaryNodeWriter.cs.
        {
            if (_captureStream != null)
            {
                ArraySegment<byte> buffer;
                bool flag = _captureStream.TryGetBuffer(out buffer);
                _captureText = XmlConverter.Base64Encoding.GetString(buffer.Array, buffer.Offset, buffer.Count);
                _captureStream = null;
            }
            if (_captureXText != null)
            {
                _captureText = _captureXText.Value;
                _captureXText = null;
            }
            if (_captureText == null || _captureText.Length == 0)
            {
                _captureText = s;
            }
            else
            {
                _captureText += s;
            }
        }
References System.Xml.XmlBinaryNodeWriter.AttributeValue._captureStream, System.Xml.XmlBinaryNodeWriter.AttributeValue._captureText, System.Xml.XmlBinaryNodeWriter.AttributeValue._captureXText, System.Xml.XmlConverter.Base64Encoding, System.buffer, System.Xml.Dictionary, System.s, System.IO.MemoryStream.TryGetBuffer(), and System.Xml.XmlDictionaryString.Value.
Referenced by System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteBase64Text(), System.Xml.XmlBinaryNodeWriter.WriteText(), System.Xml.XmlBinaryNodeWriter.WriteText(), System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteText(), and System.Xml.XmlBinaryNodeWriter.WriteText().