Terraria: System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteBase64Text
WriteBase64Text()
void System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteBase64Text (byte[] trailBytes, int trailByteCount, byte[] buffer, int offset, int count) inline
Definition at line 60 of file XmlBinaryNodeWriter.cs.
        {
            if (_captureText != null || _captureXText != null)
            {
                if (trailByteCount > 0)
                {
                    WriteText(XmlConverter.Base64Encoding.GetString(trailBytes, 0, trailByteCount));
                }
                WriteText(XmlConverter.Base64Encoding.GetString(buffer, offset, count));
                return;
            }
            if (_captureStream == null)
            {
                _captureStream = new MemoryStream();
            }
            if (trailByteCount > 0)
            {
                _captureStream.Write(trailBytes, 0, trailByteCount);
            }
            _captureStream.Write(buffer, offset, count);
        }
References System.Xml.XmlBinaryNodeWriter.AttributeValue._captureStream, System.Xml.XmlBinaryNodeWriter.AttributeValue._captureText, System.Xml.XmlBinaryNodeWriter.AttributeValue._captureXText, System.Xml.XmlConverter.Base64Encoding, System.buffer, System.count, System.Xml.Dictionary, System.offset, System.IO.MemoryStream.Write(), and System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteText().
Referenced by System.Xml.XmlBinaryNodeWriter.WriteBase64Text().