Terraria: Microsoft.Xna.Framework.Color.Multiply
Multiply()
static Color Microsoft.Xna.Framework.Color.Multiply (Color value, float scale) inline static
Definition at line 513 of file Color.cs.
    {
        uint num = value.packedValue;
        uint num2 = (byte)num;
        uint num3 = (byte)(num >> 8);
        uint num4 = (byte)(num >> 16);
        uint num5 = (byte)(num >> 24);
        scale *= 65536f;
        uint num6 = ((!(scale < 0f)) ? ((!(scale > 16777215f)) ? ((uint)scale) : 16777215u) : 0u);
        num2 = num2 * num6 >> 16;
        num3 = num3 * num6 >> 16;
        num4 = num4 * num6 >> 16;
        num5 = num5 * num6 >> 16;
        if (num2 > 255)
        {
            num2 = 255u;
        }
        if (num3 > 255)
        {
            num3 = 255u;
        }
        if (num4 > 255)
        {
            num4 = 255u;
        }
        if (num5 > 255)
        {
            num5 = 255u;
        }
        Color result = default(Color);
        result.packedValue = num2 | (num3 << 8) | (num4 << 16) | (num5 << 24);
        return result;
    }
References System.value.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.Mount.Draw(), Terraria.Player.GetImmuneAlpha(), and Terraria.Player.GetImmuneAlphaPure().