Terraria: System.Uri.InterlockedSetFlags
InterlockedSetFlags()
void System.Uri.InterlockedSetFlags (Flags flags) inline private
Definition at line 588 of file Uri.cs.
    {
        if (_syntax.IsSimple)
        {
            Interlocked.Or(ref Internal.Runtime.CompilerServices.Unsafe.As<Flags, ulong>(ref _flags), (ulong)flags);
            return;
        }
        lock (_info)
        {
            _flags |= flags;
        }
    }
References System.Uri._flags, System.Uri._info, System.Uri._syntax, System.Runtime.Serialization.Dictionary, System.UriParser.IsSimple, and System.Threading.Interlocked.Or().
Referenced by System.Uri.CreateHostString(), and System.Uri.ParseRemaining().