Terraria: System.Uri.CreateHostStringHelper
CreateHostStringHelper()
static string System.Uri.CreateHostStringHelper (string str, int idx, int end, ref Flags flags, ref string scopeId) inline static private
Definition at line 1713 of file Uri.cs.
    {
        bool loopback = false;
        string text;
        switch (flags & Flags.HostTypeMask)
        {
        case Flags.DnsHostType:
            text = DomainNameHelper.ParseCanonicalName(str, idx, end, ref loopback);
            break;
        case Flags.IPv6HostType:
            text = IPv6AddressHelper.ParseCanonicalName(str, idx, ref loopback, ref scopeId);
            break;
        case Flags.IPv4HostType:
            text = IPv4AddressHelper.ParseCanonicalName(str, idx, end, ref loopback);
            break;
        case Flags.UncHostType:
            text = UncNameHelper.ParseCanonicalName(str, idx, end, ref loopback);
            break;
        case Flags.BasicHostType:
            text = ((!StaticInFact(flags, Flags.DosPath)) ? str.Substring(idx, end - idx) : string.Empty);
            if (text.Length == 0)
            {
                loopback = true;
            }
            break;
        case Flags.HostTypeMask:
            text = string.Empty;
            break;
        default:
            throw GetException(ParsingError.BadHostName);
        }
        if (loopback)
        {
            flags |= Flags.LoopbackHost;
        }
        return text;
    }
References System.Uri.GetException(), System.IPv4AddressHelper.ParseCanonicalName(), System.DomainNameHelper.ParseCanonicalName(), System.UncNameHelper.ParseCanonicalName(), System.IPv6AddressHelper.ParseCanonicalName(), System.Uri.StaticInFact(), System.str, and System.text.
Referenced by System.Uri.CreateHostString(), and System.Uri.GetHostViaCustomSyntax().