Terraria: System.Uri.ParseSchemeCheckImplicitFile
ParseSchemeCheckImplicitFile()
static unsafe int System.Uri.ParseSchemeCheckImplicitFile (char * uriString, int length, ref ParsingError err, ref Flags flags, ref UriParser syntax) inline static private
Definition at line 2480 of file Uri.cs.
    {
        int i;
        for (i = 0; i < length && UriHelper.IsLWS(uriString[i]); i++)
        {
        }
        int j;
        for (j = i; j < length && uriString[j] != ':'; j++)
        {
        }
        if (IntPtr.Size == 4)
        {
        }
        if (i + 2 >= length || j == i)
        {
            err = ParsingError.BadFormat;
            return 0;
        }
        char c;
        if ((c = uriString[i + 1]) == ':' || c == '|')
        {
            if (UriHelper.IsAsciiLetter(uriString[i]))
            {
                if ((c = uriString[i + 2]) == '\\' || c == '/')
                {
                    flags |= Flags.AuthorityFound | Flags.DosPath | Flags.ImplicitFile;
                    syntax = UriParser.FileUri;
                    return i;
                }
                err = ParsingError.MustRootedPath;
                return 0;
            }
            if (c == ':')
            {
                err = ParsingError.BadScheme;
            }
            else
            {
                err = ParsingError.BadFormat;
            }
            return 0;
        }
        if ((c = uriString[i]) == '/' || c == '\\')
        {
            if ((c = uriString[i + 1]) == '\\' || c == '/')
            {
                flags |= Flags.AuthorityFound | Flags.UncPath | Flags.ImplicitFile;
                syntax = UriParser.FileUri;
                for (i += 2; i < length; i++)
                {
                    if ((c = uriString[i]) != '/' && c != '\\')
                    {
                        break;
                    }
                }
                return i;
            }
            err = ParsingError.BadFormat;
            return 0;
        }
        if (j == length)
        {
            err = ParsingError.BadFormat;
            return 0;
        }
        err = CheckSchemeSyntax(new ReadOnlySpan<char>(uriString + i, j - i), ref syntax);
        if (err != 0)
        {
            return 0;
        }
        return j + 1;
    }
References System.Uri.CheckSchemeSyntax(), System.Runtime.Serialization.Dictionary, System.UriParser.FileUri, System.UriHelper.IsAsciiLetter(), System.UriHelper.IsLWS(), System.length, and System.IntPtr.Size.
Referenced by System.Uri.ParseScheme().