Terraria: System.Uri.CheckCanonical
CheckCanonical()
unsafe Check System.Uri.CheckCanonical (char * str, ref int idx, int end, char delim) inline private
Definition at line 2971 of file Uri.cs.
    {
        Check check = Check.None;
        bool flag = false;
        bool flag2 = false;
        bool iriParsing = IriParsing;
        int i;
        for (i = idx; i < end; i++)
        {
            char c = str[i];
            if (c <= '\u001f' || (c >= '\u007f' && c <= '\u009f'))
            {
                flag = true;
                flag2 = true;
                check |= Check.ReservedFound;
                continue;
            }
            if (c > '~')
            {
                if (iriParsing)
                {
                    bool flag3 = false;
                    check |= Check.FoundNonAscii;
                    if (char.IsHighSurrogate(c))
                    {
                        if (i + 1 < end)
{
                            flag3 = IriHelper.CheckIriUnicodeRange(c, str[i + 1], out var _, isQuery: true);
                        }
                    }
                    else
                    {
                        flag3 = IriHelper.CheckIriUnicodeRange(c, isQuery: true);
                    }
                    if (!flag3)
                    {
                        check |= Check.NotIriCanonical;
                    }
                }
                if (!flag)
                {
                    flag = true;
                }
                continue;
            }
            if (c == delim || (delim == '?' && c == '#' && _syntax != null && _syntax.InFact(UriSyntaxFlags.MayHaveFragment)))
            {
                break;
            }
            if (c == '?')
            {
                if (IsImplicitFile || (_syntax != null && !_syntax.InFact(UriSyntaxFlags.MayHaveQuery) && delim != '\ufffe'))
                {
                    check |= Check.ReservedFound;
                    flag2 = true;
                    flag = true;
                }
                continue;
            }
            if (c == '#')
            {
                flag = true;
                if (IsImplicitFile || (_syntax != null && !_syntax.InFact(UriSyntaxFlags.MayHaveFragment)))
                {
                    check |= Check.ReservedFound;
                    flag2 = true;
                }
                continue;
            }
            if (c == '/' || c == '\\')
            {
                if ((check & Check.BackslashInPath) == 0 && c == '\\')
                {
                    check |= Check.BackslashInPath;
                }
                if ((check & Check.DotSlashAttn) == 0 && i + 1 != end && (str[i + 1] == '/' || str[i + 1] == '\\'))
                {
                    check |= Check.DotSlashAttn;
                }
                continue;
            }
            if (c == '.')
            {
                if (((check & Check.DotSlashAttn) == 0 && i + 1 == end) || str[i + 1] == '.' || str[i + 1] == '/' || str[i + 1] == '\\' || str[i + 1] == '?' || str[i + 1] == '#')
                {
                    check |= Check.DotSlashAttn;
                }
                continue;
            }
            if ((c > '"' || c == '!') && (c < '[' || c > '^'))
            {
                switch (c)
                {
                case '<':
                case '>':
                case '`':
                    break;
                case '{':
                case '|':
                case '}':
                    flag = true;
                    continue;
                default:
                    if (c != '%')
                    {
                        continue;
                    }
                    if (!flag2)
                    {
                        flag2 = true;
                    }
                    if (i + 2 < end && (c = UriHelper.DecodeHexChars(str[i + 1], str[i + 2])) != '\uffff')
                    {
                        if (c == '.' || c == '/' || c == '\\')
{
                            check |= Check.DotSlashEscaped;
                        }
                        i += 2;
                    }
                    else if (!flag)
                    {
                        flag = true;
                    }
                    continue;
                }
            }
            if (!flag)
            {
                flag = true;
            }
            if ((_flags & Flags.HasUnicode) != Flags.Zero)
            {
                check |= Check.NotIriCanonical;
            }
        }
        if (flag2)
        {
            if (!flag)
            {
                check |= Check.EscapedCanonical;
            }
        }
        else
        {
            check |= Check.DisplayCanonical;
            if (!flag)
            {
                check |= Check.EscapedCanonical;
            }
        }
        idx = i;
        return check;
    }
References System.Uri._flags, System.Uri._syntax, System.IriHelper.CheckIriUnicodeRange(), System.UriHelper.DecodeHexChars(), System.UriParser.InFact(), System.Uri.IriParsing, System.Uri.IsImplicitFile, and System.str.
Referenced by System.Uri.CreateHostString(), System.Uri.InternalIsWellFormedOriginalString(), and System.Uri.ParseRemaining().