Terraria: System.Uri.Compress
Compress() [1/2]
static void System.Uri.Compress (char[] dest, int start, ref int destLength, UriParser syntax) inline static private
Definition at line 3300 of file Uri.cs.
    {
        destLength = start + Compress(dest.AsSpan(start, destLength - start), syntax);
    }
References System.Uri.Compress(), and System.start.
Referenced by System.Uri.CombineUri(), System.Uri.Compress(), System.Uri.GetCanonicalPath(), and System.Uri.GetLocalPath().