Terraria: System.Uri.IsBaseOfHelper
IsBaseOfHelper()
unsafe bool System.Uri.IsBaseOfHelper (Uri uriLink) inline package
Definition at line 4295 of file Uri.cs.
    {
        //The blocks IL_00a5, IL_00bf, IL_00c7, IL_00c8 are reachable both inside and outside the pinned region starting at IL_00a0. ILSpy has duplicated these blocks in order to place them both within and outside the `fixed` statement.
        if (!IsAbsoluteUri || UserDrivenParsing)
        {
            return false;
        }
        if (!uriLink.IsAbsoluteUri)
        {
            string newUriString = null;
            bool userEscaped = false;
            uriLink = ResolveHelper(this, uriLink, ref newUriString, ref userEscaped);
            if ((object)uriLink == null)
            {
                UriFormatException e = null;
                string uriString = newUriString;
                bool dontEscape = userEscaped;
                UriCreationOptions creationOptions = default(UriCreationOptions);
                uriLink = CreateHelper(uriString, dontEscape, UriKind.Absolute, ref e, in creationOptions);
                if (e != null)
                {
                    return false;
                }
            }
        }
        if (Syntax.SchemeName != uriLink.Syntax.SchemeName)
        {
            return false;
        }
        string parts = GetParts(UriComponents.HttpRequestUrl | UriComponents.UserInfo, UriFormat.SafeUnescaped);
        string parts2 = uriLink.GetParts(UriComponents.HttpRequestUrl | UriComponents.UserInfo, UriFormat.SafeUnescaped);
        fixed (char* ptr3 = parts)
        {
            char* intPtr;
            char* selfPtr;
            int length;
            char* otherPtr;
            int length2;
            int ignoreCase;
            char* ptr2;
            if (parts2 != null)
            {
                fixed (char* ptr = &parts2.GetPinnableReference())
                {
                    intPtr = (ptr2 = ptr);
                    selfPtr = ptr3;
                    length = parts.Length;
                    otherPtr = ptr2;
                    length2 = parts2.Length;
                    ignoreCase = ((IsUncOrDosPath || uriLink.IsUncOrDosPath) ? 1 : 0);
                    return UriHelper.TestForSubPath(selfPtr, length, otherPtr, length2, (byte)ignoreCase != 0);
                }
            }
            intPtr = (ptr2 = null);
            selfPtr = ptr3;
            length = parts.Length;
            otherPtr = ptr2;
            length2 = parts2.Length;
            ignoreCase = ((IsUncOrDosPath || uriLink.IsUncOrDosPath) ? 1 : 0);
            return UriHelper.TestForSubPath(selfPtr, length, otherPtr, length2, (byte)ignoreCase != 0);
        }
    }
References System.Uri.CreateHelper(), System.creationOptions, System.Runtime.Serialization.Dictionary, System.Uri.GetParts(), System.Uri.IsAbsoluteUri, System.Uri.IsUncOrDosPath, System.length, System.length2, System.Uri.ResolveHelper(), System.UriParser.SchemeName, System.Uri.Syntax, System.UriHelper.TestForSubPath(), and System.Uri.UserDrivenParsing.
Referenced by System.UriParser.IsBaseOf(), and System.Uri.IsBaseOf().