Terraria: System.Uri.GetCanonicalPath
GetCanonicalPath()
unsafe void System.Uri.GetCanonicalPath (ref System::Text::ValueStringBuilder dest, UriFormat formatAs) inline private
Definition at line 3125 of file Uri.cs.
    {
        if (InFact(Flags.FirstSlashAbsent))
        {
            dest.Append('/');
        }
        if (_info.Offset.Path == _info.Offset.Query)
        {
            return;
        }
        int length = dest.Length;
        int securedPathIndex = SecuredPathIndex;
        if (formatAs == UriFormat.UriEscaped)
        {
            if (InFact(Flags.ShouldBeCompressed))
            {
                dest.Append(_string.AsSpan(_info.Offset.Path, _info.Offset.Query - _info.Offset.Path));
                if (_syntax.InFact(UriSyntaxFlags.UnEscapeDotsAndSlashes) && InFact(Flags.PathNotCanonical) && !IsImplicitFile)
                {
                    fixed (char* pch = dest)
                    {
                        int end = dest.Length;
                        UnescapeOnly(pch, length, ref end, '.', '/', _syntax.InFact(UriSyntaxFlags.ConvertPathSlashes) ? '\\' : '\uffff');
                        dest.Length = end;
                    }
                }
            }
            else if (InFact(Flags.E_PathNotCanonical) && NotAny(Flags.UserEscaped))
            {
                ReadOnlySpan<char> readOnlySpan = _string;
                if (securedPathIndex != 0 && readOnlySpan[securedPathIndex + _info.Offset.Path - 1] == '|')
                {
                    char[] array = readOnlySpan.ToArray();
                    array[securedPathIndex + _info.Offset.Path - 1] = ':';
                    readOnlySpan = array;
                }
                UriHelper.EscapeString(readOnlySpan.Slice(_info.Offset.Path, _info.Offset.Query - _info.Offset.Path), ref dest, !IsImplicitFile, '?', '#');
            }
            else
            {
                dest.Append(_string.AsSpan(_info.Offset.Path, _info.Offset.Query - _info.Offset.Path));
            }
        }
        else
        {
            dest.Append(_string.AsSpan(_info.Offset.Path, _info.Offset.Query - _info.Offset.Path));
            if (InFact(Flags.ShouldBeCompressed) && _syntax.InFact(UriSyntaxFlags.UnEscapeDotsAndSlashes) && InFact(Flags.PathNotCanonical) && !IsImplicitFile)
            {
                fixed (char* pch2 = dest)
                {
                    int end2 = dest.Length;
                    UnescapeOnly(pch2, length, ref end2, '.', '/', _syntax.InFact(UriSyntaxFlags.ConvertPathSlashes) ? '\\' : '\uffff');
                    dest.Length = end2;
                }
            }
        }
        int num = length + securedPathIndex;
        if (securedPathIndex != 0 && dest[num - 1] == '|')
        {
            dest[num - 1] = ':';
        }
        if (InFact(Flags.ShouldBeCompressed) && dest.Length - num > 0)
        {
            dest.Length = num + Compress(dest.RawChars.Slice(num, dest.Length - num), _syntax);
            if (dest[length] == '\\')
            {
                dest[length] = '/';
            }
            if (formatAs == UriFormat.UriEscaped && NotAny(Flags.UserEscaped) && InFact(Flags.E_PathNotCanonical))
            {
                Span<char> initialBuffer = stackalloc char[512];
                System.Text.ValueStringBuilder valueStringBuilder = new System.Text.ValueStringBuilder(initialBuffer);
                valueStringBuilder.Append(dest.AsSpan(length, dest.Length - length));
                dest.Length = length;
                ReadOnlySpan<char> stringToEscape = MemoryMarshal.CreateReadOnlySpan(ref valueStringBuilder.GetPinnableReference(), valueStringBuilder.Length);
                UriHelper.EscapeString(stringToEscape, ref dest, !IsImplicitFile, '?', '#');
                length = dest.Length;
                valueStringBuilder.Dispose();
            }
        }
        if (formatAs == UriFormat.UriEscaped || !InFact(Flags.PathNotCanonical))
        {
            return;
        }
        UnescapeMode unescapeMode;
        switch (formatAs)
        {
        case (UriFormat)32767:
            unescapeMode = (InFact(Flags.UserEscaped) ? UnescapeMode.Unescape : UnescapeMode.EscapeUnescape) | UnescapeMode.V1ToStringFlag;
            if (IsImplicitFile)
            {
                unescapeMode &= ~UnescapeMode.Unescape;
            }
            break;
        case UriFormat.Unescaped:
            unescapeMode = ((!IsImplicitFile) ? (UnescapeMode.Unescape | UnescapeMode.UnescapeAll) : UnescapeMode.CopyOnly);
            break;
        default:
            unescapeMode = (InFact(Flags.UserEscaped) ? UnescapeMode.Unescape : UnescapeMode.EscapeUnescape);
            if (IsImplicitFile)
            {
                unescapeMode &= ~UnescapeMode.Unescape;
            }
            break;
        }
        if (unescapeMode != 0)
        {
            Span<char> initialBuffer = stackalloc char[512];
            System.Text.ValueStringBuilder valueStringBuilder2 = new System.Text.ValueStringBuilder(initialBuffer);
            valueStringBuilder2.Append(dest.AsSpan(length, dest.Length - length));
            dest.Length = length;
            fixed (char* pStr = valueStringBuilder2)
            {
                UriHelper.UnescapeString(pStr, 0, valueStringBuilder2.Length, ref dest, '?', '#', '\uffff', unescapeMode, _syntax, isQuery: false);
            }
            valueStringBuilder2.Dispose();
        }
    }
References System.Uri._info, System.Uri._string, System.Uri._syntax, System.array, System.Uri.Compress(), System.Runtime.Serialization.Dictionary, System.UriHelper.EscapeString(), System.Uri.InFact(), System.UriParser.InFact(), System.Uri.IsImplicitFile, System.length, System.Uri.NotAny(), System.Uri.UriInfo.Offset, System.Uri.Offset.Path, System.Uri.Offset.Query, System.Uri.SecuredPathIndex, System.Uri.UnescapeOnly(), and System.UriHelper.UnescapeString().
Referenced by System.Uri.ReCreateParts().