Terraria: System.Uri.PrivateParseMinimal
PrivateParseMinimal()
unsafe ParsingError System.Uri.PrivateParseMinimal () inline private
Definition at line 1354 of file Uri.cs.
    {
        int num = (int)(_flags & Flags.IndexMask);
        int num2 = _string.Length;
        string newHost = null;
        _flags &= ~(Flags.IndexMask | Flags.UserDrivenParsing);
        fixed (char* ptr = (((_flags & Flags.HostUnicodeNormalized) == Flags.Zero) ? OriginalString : _string))
        {
            if (num2 > num && UriHelper.IsLWS(ptr[num2 - 1]))
            {
                num2--;
                while (num2 != num && UriHelper.IsLWS(ptr[--num2]))
                {
                }
                num2++;
            }
            if (_syntax.IsAllSet(UriSyntaxFlags.AllowEmptyHost | UriSyntaxFlags.AllowDOSPath) && NotAny(Flags.ImplicitFile) && num + 1 < num2)
            {
                int i;
                for (i = num; i < num2; i++)
                {
                    char c;
                    if ((c = ptr[i]) != '\\' && c != '/')
                    {
                        break;
                    }
                }
                if (_syntax.InFact(UriSyntaxFlags.FileLikeUri) || i - num <= 3)
                {
                    if (i - num >= 2)
                    {
                        _flags |= Flags.AuthorityFound;
                    }
                    char c;
                    if (i + 1 < num2 && ((c = ptr[i + 1]) == ':' || c == '|') && UriHelper.IsAsciiLetter(ptr[i]))
                    {
                        if (i + 2 >= num2 || ((c = ptr[i + 2]) != '\\' && c != '/'))
{
                            if (_syntax.InFact(UriSyntaxFlags.FileLikeUri))
{
                                return ParsingError.MustRootedPath;
                            }
                        }
                        else
{
                            _flags |= Flags.DosPath;
                            if (_syntax.InFact(UriSyntaxFlags.MustHaveAuthority))
{
                                _flags |= Flags.AuthorityFound;
                            }
                            num = ((i == num || i - num == 2) ? i : (i - 1));
                        }
                    }
                    else if (_syntax.InFact(UriSyntaxFlags.FileLikeUri) && i - num >= 2 && i - num != 3 && i < num2 && ptr[i] != '?' && ptr[i] != '#')
                    {
                        _flags |= Flags.UncPath;
                        num = i;
                    }
                }
            }
            if ((_flags & (Flags.DosPath | Flags.UncPath | Flags.UnixPath)) == Flags.Zero)
            {
                if (num + 2 <= num2)
                {
                    char c2 = ptr[num];
                    char c3 = ptr[num + 1];
                    if (_syntax.InFact(UriSyntaxFlags.MustHaveAuthority))
                    {
                        if ((c2 != '/' && c2 != '\\') || (c3 != '/' && c3 != '\\'))
{
                            return ParsingError.BadAuthority;
                        }
                        _flags |= Flags.AuthorityFound;
                        num += 2;
                    }
                    else if (_syntax.InFact(UriSyntaxFlags.OptionalAuthority) && (InFact(Flags.AuthorityFound) || (c2 == '/' && c3 == '/')))
                    {
                        _flags |= Flags.AuthorityFound;
                        num += 2;
                    }
                    else if (_syntax.NotAny(UriSyntaxFlags.MailToLikeUri))
                    {
                        if ((_flags & (Flags.HasUnicode | Flags.HostUnicodeNormalized)) == Flags.HasUnicode)
{
                            _string = _string.Substring(0, num);
                        }
                        _flags |= (Flags)((ulong)num | 0x70000uL);
                        return ParsingError.None;
                    }
                }
                else
                {
                    if (_syntax.InFact(UriSyntaxFlags.MustHaveAuthority))
                    {
                        return ParsingError.BadAuthority;
                    }
                    if (_syntax.NotAny(UriSyntaxFlags.MailToLikeUri))
                    {
                        if ((_flags & (Flags.HasUnicode | Flags.HostUnicodeNormalized)) == Flags.HasUnicode)
{
                            _string = _string.Substring(0, num);
                        }
                        _flags |= (Flags)((ulong)num | 0x70000uL);
                        return ParsingError.None;
                    }
                }
            }
            if (InFact(Flags.DosPath))
            {
                _flags |= (Flags)(((_flags & Flags.AuthorityFound) != Flags.Zero) ? 327680 : 458752);
                _flags |= (Flags)num;
                return ParsingError.None;
            }
            ParsingError err = ParsingError.None;
            num = CheckAuthorityHelper(ptr, num, num2, ref err, ref _flags, _syntax, ref newHost);
            if (err != 0)
            {
                return err;
            }
            if (num < num2)
            {
                char c4 = ptr[num];
                if (c4 == '\\' && NotAny(Flags.ImplicitFile) && _syntax.NotAny(UriSyntaxFlags.AllowDOSPath))
                {
                    return ParsingError.BadAuthorityTerminator;
                }
            }
            _flags |= (Flags)num;
        }
        if (IriParsing && newHost != null)
        {
            _string = newHost;
        }
        return ParsingError.None;
    }
References System.Uri._flags, System.Uri._string, System.Uri._syntax, System.Uri.CheckAuthorityHelper(), System.Runtime.Serialization.Dictionary, System.Uri.InFact(), System.UriParser.InFact(), System.Uri.IriParsing, System.UriParser.IsAllSet(), System.UriHelper.IsAsciiLetter(), System.UriHelper.IsLWS(), System.Uri.NotAny(), System.UriParser.NotAny(), and System.Uri.OriginalString.
Referenced by System.Uri.InitializeUri(), and System.Uri.ParseMinimal().