Terraria: System.Uri.InitializeUri
InitializeUri()
void System.Uri.InitializeUri (ParsingError err, UriKind uriKind, out UriFormatException e) inline private
Definition at line 3642 of file Uri.cs.
    {
        if (err == ParsingError.None)
        {
            if (IsImplicitFile)
            {
                if (NotAny(Flags.DosPath) && uriKind != UriKind.Absolute && (uriKind == UriKind.Relative || (_string.Length >= 2 && (_string[0] != '\\' || _string[1] != '\\'))))
                {
                    _syntax = null;
                    _flags &= Flags.UserEscaped;
                    e = null;
                    return;
                }
                if (uriKind == UriKind.Relative && InFact(Flags.DosPath))
                {
                    _syntax = null;
                    _flags &= Flags.UserEscaped;
                    e = null;
                    return;
                }
            }
        }
        else if (err > ParsingError.EmptyUriString)
        {
            _string = null;
            e = GetException(err);
            return;
        }
        bool flag = false;
        if (IriParsing && CheckForUnicodeOrEscapedUnreserved(_string))
        {
            _flags |= Flags.HasUnicode;
            flag = true;
            _originalUnicodeString = _string;
        }
        if (_syntax != null)
        {
            if (_syntax.IsSimple)
            {
                if ((err = PrivateParseMinimal()) != 0)
                {
                    if (uriKind != UriKind.Absolute && err <= ParsingError.EmptyUriString)
                    {
                        _syntax = null;
                        e = null;
                        _flags &= Flags.UserEscaped;
                        return;
                    }
                    e = GetException(err);
                }
                else if (uriKind == UriKind.Relative)
                {
                    e = GetException(ParsingError.CannotCreateRelative);
                }
                else
                {
                    e = null;
                }
                if (flag)
                {
                    try
                    {
                        EnsureParseRemaining();
                        return;
                    }
                    catch (UriFormatException ex)
                    {
                        e = ex;
                        return;
                    }
                }
                return;
            }
            _syntax = _syntax.InternalOnNewUri();
            _flags |= Flags.UserDrivenParsing;
            _syntax.InternalValidate(this, out e);
            if (e != null)
            {
                if (uriKind != UriKind.Absolute && err != 0 && err <= ParsingError.EmptyUriString)
                {
                    _syntax = null;
                    e = null;
                    _flags &= Flags.UserEscaped;
                }
                return;
            }
            if (err != 0 || InFact(Flags.ErrorOrParsingRecursion))
            {
                _flags = Flags.UserDrivenParsing | (_flags & Flags.UserEscaped);
            }
            else if (uriKind == UriKind.Relative)
            {
                e = GetException(ParsingError.CannotCreateRelative);
            }
            if (flag)
            {
                try
                {
                    EnsureParseRemaining();
                }
                catch (UriFormatException ex2)
                {
                    e = ex2;
                }
            }
        }
        else if (err != 0 && uriKind != UriKind.Absolute && err <= ParsingError.EmptyUriString)
        {
            e = null;
            _flags &= Flags.UserEscaped | Flags.HasUnicode;
            if (flag)
            {
                _string = EscapeUnescapeIri(_originalUnicodeString, 0, _originalUnicodeString.Length, (UriComponents)0);
                if (_string.Length > 65535)
                {
                    err = ParsingError.SizeLimit;
                }
            }
        }
        else
        {
            _string = null;
            e = GetException(err);
        }
    }
References System.Uri._flags, System.Uri._originalUnicodeString, System.Uri._string, System.Uri._syntax, System.Uri.CheckForUnicodeOrEscapedUnreserved(), System.Runtime.Serialization.Dictionary, System.Uri.EnsureParseRemaining(), System.Uri.EscapeUnescapeIri(), System.Uri.GetException(), System.Uri.InFact(), System.UriParser.InternalOnNewUri(), System.UriParser.InternalValidate(), System.Uri.IriParsing, System.Uri.IsImplicitFile, System.UriParser.IsSimple, System.Uri.NotAny(), and System.Uri.PrivateParseMinimal().
Referenced by System.Uri.CreateHelper(), and System.Uri.CreateThis().