Terraria: System.Uri.CreateHostString
CreateHostString()
unsafe void System.Uri.CreateHostString () inline private
Definition at line 1646 of file Uri.cs.
    {
        if (!_syntax.IsSimple)
        {
            lock (_info)
            {
                if (NotAny(Flags.ErrorOrParsingRecursion))
                {
                    _flags |= Flags.ErrorOrParsingRecursion;
                    GetHostViaCustomSyntax();
                    _flags &= ~Flags.ErrorOrParsingRecursion;
                    return;
                }
            }
        }
        Flags flags = _flags;
        string text = CreateHostStringHelper(_string, _info.Offset.Host, _info.Offset.Path, ref flags, ref _info.ScopeId);
        if (text.Length != 0)
        {
            if (HostType == Flags.BasicHostType)
            {
                int idx = 0;
                Check check;
                fixed (char* str = text)
                {
                    check = CheckCanonical(str, ref idx, text.Length, '\uffff');
                }
                if ((check & Check.DisplayCanonical) == 0 && (NotAny(Flags.ImplicitFile) || (check & Check.ReservedFound) != 0))
                {
                    flags |= Flags.HostNotCanonical;
                }
                if (InFact(Flags.ImplicitFile) && (check & (Check.EscapedCanonical | Check.ReservedFound)) != 0)
                {
                    check &= ~Check.EscapedCanonical;
                }
                if ((check & (Check.EscapedCanonical | Check.BackslashInPath)) != Check.EscapedCanonical)
                {
                    flags |= Flags.E_HostNotCanonical;
                    if (NotAny(Flags.UserEscaped))
                    {
                        text = UriHelper.EscapeString(text, !IsImplicitFile, UriHelper.UnreservedReservedTable, '?', '#');
                    }
                }
            }
            else if (NotAny(Flags.CanonicalDnsHost))
            {
                if (_info.ScopeId != null)
                {
                    flags |= Flags.HostNotCanonical | Flags.E_HostNotCanonical;
                }
                else
                {
                    for (int i = 0; i < text.Length; i++)
                    {
                        if (_info.Offset.Host + i >= _info.Offset.End || text[i] != _string[_info.Offset.Host + i])
{
                            flags |= Flags.HostNotCanonical | Flags.E_HostNotCanonical;
                            break;
                        }
                    }
                }
            }
        }
        _info.Host = text;
        InterlockedSetFlags(flags);
    }
References System.Uri._flags, System.Uri._info, System.Uri._string, System.Uri._syntax, System.Uri.CheckCanonical(), System.Uri.CreateHostStringHelper(), System.Runtime.Serialization.Dictionary, System.Uri.Offset.End, System.UriHelper.EscapeString(), System.Uri.GetHostViaCustomSyntax(), System.Uri.Offset.Host, System.Uri.HostType, System.Uri.InFact(), System.Uri.InterlockedSetFlags(), System.Uri.IsImplicitFile, System.UriParser.IsSimple, System.Uri.NotAny(), System.Uri.UriInfo.Offset, System.Uri.Offset.Path, System.Uri.UriInfo.ScopeId, System.str, System.text, and System.UriHelper.UnreservedReservedTable.
Referenced by System.Uri.EnsureHostString().