Terraria: System.Uri.CombineUri
CombineUri()
static string System.Uri.CombineUri (Uri basePart, string relativePart, UriFormat uriFormat) inline static private
Definition at line 3381 of file Uri.cs.
    {
        char c = relativePart[0];
        if (basePart.IsDosPath && (c == '/' || c == '\\') && (relativePart.Length == 1 || (relativePart[1] != '/' && relativePart[1] != '\\')))
        {
            int num = basePart.OriginalString.IndexOf(':');
            if (basePart.IsImplicitFile)
            {
                return string.Concat(basePart.OriginalString.AsSpan(0, num + 1), relativePart);
            }
            num = basePart.OriginalString.IndexOf(':', num + 1);
            return string.Concat(basePart.OriginalString.AsSpan(0, num + 1), relativePart);
        }
        if (StaticIsFile(basePart.Syntax) && (c == '\\' || c == '/'))
        {
            if (relativePart.Length >= 2 && (relativePart[1] == '\\' || relativePart[1] == '/'))
            {
                if (!basePart.IsImplicitFile)
                {
                    return "file:" + relativePart;
                }
                return relativePart;
            }
            if (basePart.IsUnc)
            {
                ReadOnlySpan<char> readOnlySpan = basePart.GetParts(UriComponents.Path | UriComponents.KeepDelimiter, UriFormat.Unescaped);
                for (int i = 1; i < readOnlySpan.Length; i++)
                {
                    if (readOnlySpan[i] == '/')
                    {
                        readOnlySpan = readOnlySpan.Slice(0, i);
                        break;
                    }
                }
                if (basePart.IsImplicitFile)
                {
                    return string.Concat("\\\\", basePart.GetParts(UriComponents.Host, UriFormat.Unescaped), readOnlySpan, relativePart);
                }
                return string.Concat("file://", basePart.GetParts(UriComponents.Host, uriFormat), readOnlySpan, relativePart);
            }
            return "file://" + relativePart;
        }
        bool flag = basePart.Syntax.InFact(UriSyntaxFlags.ConvertPathSlashes);
        string text = null;
        if (c == '/' || (c == '\\' && flag))
        {
            if (relativePart.Length >= 2 && relativePart[1] == '/')
            {
                return basePart.Scheme + ":" + relativePart;
            }
            text = ((basePart.HostType != Flags.IPv6HostType) ? basePart.GetParts(UriComponents.SchemeAndServer | UriComponents.UserInfo, uriFormat) : $"{basePart.GetParts(UriComponents.Scheme | UriComponents.UserInfo, uriFormat)}[{basePart.DnsSafeHost}]{basePart.GetParts(UriComponents.Port | UriComponents.KeepDelimiter, uriFormat)}");
            if (!flag || c != '\\')
            {
                return text + relativePart;
            }
            return text + "/" + relativePart.AsSpan(1);
        }
        text = basePart.GetParts(UriComponents.Path | UriComponents.KeepDelimiter, basePart.IsImplicitFile ? UriFormat.Unescaped : uriFormat);
        int num2 = text.Length;
        char[] array = new char[num2 + relativePart.Length];
        if (num2 > 0)
        {
            text.CopyTo(0, array, 0, num2);
            while (num2 > 0)
            {
                if (array[--num2] == '/')
                {
                    num2++;
                    break;
                }
            }
        }
        relativePart.CopyTo(0, array, num2, relativePart.Length);
        c = (basePart.Syntax.InFact(UriSyntaxFlags.MayHaveQuery) ? '?' : '\uffff');
        char c2 = ((!basePart.IsImplicitFile && basePart.Syntax.InFact(UriSyntaxFlags.MayHaveFragment)) ? '#' : '\uffff');
        ReadOnlySpan<char> readOnlySpan2 = string.Empty;
        if (c != '\uffff' || c2 != '\uffff')
        {
            int j;
            for (j = 0; j < relativePart.Length && array[num2 + j] != c && array[num2 + j] != c2; j++)
            {
            }
            if (j == 0)
            {
                readOnlySpan2 = relativePart;
            }
            else if (j < relativePart.Length)
            {
                readOnlySpan2 = relativePart.AsSpan(j);
            }
            num2 += j;
        }
        else
        {
            num2 += relativePart.Length;
        }
        if (basePart.HostType == Flags.IPv6HostType)
        {
            text = ((!basePart.IsImplicitFile) ? (basePart.GetParts(UriComponents.Scheme | UriComponents.UserInfo, uriFormat) + "[" + basePart.DnsSafeHost + "]" + basePart.GetParts(UriComponents.Port | UriComponents.KeepDelimiter, uriFormat)) : ("\\\\[" + basePart.DnsSafeHost + "]"));
        }
        else if (basePart.IsImplicitFile)
        {
            if (basePart.IsDosPath)
            {
                Compress(array, 3, ref num2, basePart.Syntax);
                return string.Concat(array.AsSpan(1, num2 - 1), readOnlySpan2);
            }
            text = "\\\\" + basePart.GetParts(UriComponents.Host, UriFormat.Unescaped);
        }
        else
        {
            text = basePart.GetParts(UriComponents.SchemeAndServer | UriComponents.UserInfo, uriFormat);
        }
        Compress(array, basePart.SecuredPathIndex, ref num2, basePart.Syntax);
        return string.Concat(text, array.AsSpan(0, num2), readOnlySpan2);
    }
References System.array, System.Uri.Compress(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Runtime.Serialization.Dictionary, System.Uri.StaticIsFile(), and System.text.
Referenced by System.Uri.GetCombinedString().