Terraria: System.Uri.MakeRelativeUri
MakeRelativeUri()
Uri System.Uri.MakeRelativeUri (Uri uri) inline
Definition at line 1276 of file Uri.cs.
    {
        if ((object)uri == null)
        {
            throw new ArgumentNullException("uri");
        }
        if (IsNotAbsoluteUri || uri.IsNotAbsoluteUri)
        {
            throw new InvalidOperationException(System.SR.net_uri_NotAbsolute);
        }
        if (Scheme == uri.Scheme && Host == uri.Host && Port == uri.Port)
        {
            string absolutePath = uri.AbsolutePath;
            string text = PathDifference(AbsolutePath, absolutePath, !IsUncOrDosPath);
            if (CheckForColonInFirstPathSegment(text) && (!uri.IsDosPath || !absolutePath.Equals(text, StringComparison.Ordinal)))
            {
                text = "./" + text;
            }
            text += uri.GetParts(UriComponents.Query | UriComponents.Fragment, UriFormat.UriEscaped);
            return new Uri(text, UriKind.Relative);
        }
        return uri;
    }
References System.Uri.Uri(), System.Uri.AbsolutePath, System.Uri.CheckForColonInFirstPathSegment(), System.Uri.GetParts(), System.Uri.Host, System.Uri.IsDosPath, System.Uri.IsNotAbsoluteUri, System.Uri.IsUncOrDosPath, System.SR.net_uri_NotAbsolute, System.Uri.PathDifference(), System.Uri.Port, System.Uri.Scheme, and System.text.