Terraria: System.Uri.CheckSchemeName
CheckSchemeName()
static bool System.Uri.CheckSchemeName ([NotNullWhen(true)] string? schemeName) inline static
Definition at line 1072 of file Uri.cs.
    {
        if (string.IsNullOrEmpty(schemeName) || !UriHelper.IsAsciiLetter(schemeName[0]))
        {
            return false;
        }
        for (int num = schemeName.Length - 1; num > 0; num--)
        {
            if (!UriHelper.IsAsciiLetterOrDigit(schemeName[num]) && schemeName[num] != '+' && schemeName[num] != '-' && schemeName[num] != '.')
            {
                return false;
            }
        }
        return true;
    }
References System.UriHelper.IsAsciiLetter(), and System.UriHelper.IsAsciiLetterOrDigit().
Referenced by System.UriParser.IsKnownScheme(), and System.UriParser.Register().