Terraria: System.Uri.ResolveHelper
ResolveHelper()
static Uri System.Uri.ResolveHelper (Uri baseUri, Uri relativeUri, ref string newUriString, ref bool userEscaped) inline static package
Definition at line 4149 of file Uri.cs.
    {
        string text;
        if ((object)relativeUri != null)
        {
            if (relativeUri.IsAbsoluteUri)
            {
                return relativeUri;
            }
            text = relativeUri.OriginalString;
            userEscaped = relativeUri.UserEscaped;
        }
        else
        {
            text = string.Empty;
        }
        if (text.Length > 0 && (UriHelper.IsLWS(text[0]) || UriHelper.IsLWS(text[text.Length - 1])))
        {
            text = text.Trim(UriHelper.s_WSchars);
        }
        if (text.Length == 0)
        {
            newUriString = baseUri.GetParts(UriComponents.AbsoluteUri, baseUri.UserEscaped ? UriFormat.UriEscaped : UriFormat.SafeUnescaped);
            return null;
        }
        if (text[0] == '#' && !baseUri.IsImplicitFile && baseUri.Syntax.InFact(UriSyntaxFlags.MayHaveFragment))
        {
            newUriString = baseUri.GetParts(UriComponents.HttpRequestUrl | UriComponents.UserInfo, UriFormat.UriEscaped) + text;
            return null;
        }
        if (text[0] == '?' && !baseUri.IsImplicitFile && baseUri.Syntax.InFact(UriSyntaxFlags.MayHaveQuery))
        {
            newUriString = baseUri.GetParts(UriComponents.SchemeAndServer | UriComponents.UserInfo | UriComponents.Path, UriFormat.UriEscaped) + text;
            return null;
        }
        if (text.Length >= 3 && (text[1] == ':' || text[1] == '|') && UriHelper.IsAsciiLetter(text[0]) && (text[2] == '\\' || text[2] == '/'))
        {
            if (baseUri.IsImplicitFile)
            {
                newUriString = text;
                return null;
            }
            if (baseUri.Syntax.InFact(UriSyntaxFlags.AllowDOSPath))
            {
                newUriString = string.Concat(str1: (!baseUri.InFact(Flags.AuthorityFound)) ? (baseUri.Syntax.InFact(UriSyntaxFlags.PathIsRooted) ? ":/" : ":") : (baseUri.Syntax.InFact(UriSyntaxFlags.PathIsRooted) ? ":///" : "://"), str0: baseUri.Scheme, str2: text);
                return null;
            }
        }
        GetCombinedString(baseUri, text, userEscaped, ref newUriString);
        if ((object)newUriString == baseUri._string)
        {
            return baseUri;
        }
        return null;
    }
References System.Uri._string, System.Runtime.Serialization.Dictionary, System.Uri.GetCombinedString(), System.Uri.GetParts(), System.Uri.InFact(), System.UriParser.InFact(), System.UriHelper.IsAsciiLetter(), System.Uri.IsImplicitFile, System.UriHelper.IsLWS(), System.UriHelper.s_WSchars, System.Uri.Scheme, System.Uri.Syntax, System.text, and System.Uri.UserEscaped.
Referenced by System.Uri.Uri(), System.Uri.CreateUri(), System.Uri.IsBaseOfHelper(), System.UriParser.Resolve(), and System.Uri.TryCreate().