Terraria: System.Uri.CreateThis
CreateThis()
void System.Uri.CreateThis (string uri, bool dontEscape, UriKind uriKind, in UriCreationOptions creationOptions = default(UriCreationOptions)) inline private
Definition at line 3619 of file Uri.cs.
    {
        if (uriKind < UriKind.RelativeOrAbsolute || uriKind > UriKind.Relative)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_uri_InvalidUriKind, uriKind));
        }
        _string = uri ?? string.Empty;
        if (dontEscape)
        {
            _flags |= Flags.UserEscaped;
        }
        if (creationOptions.DangerousDisablePathAndQueryCanonicalization)
        {
            _flags |= Flags.DisablePathAndQueryCanonicalization;
        }
        ParsingError err = ParseScheme(_string, ref _flags, ref _syntax);
        InitializeUri(err, uriKind, out var e);
        if (e != null)
        {
            throw e;
        }
    }
References System.Uri._flags, System.Uri._string, System.Uri._syntax, System.creationOptions, System.SR.Format(), System.Uri.InitializeUri(), System.SR.net_uri_InvalidUriKind, and System.Uri.ParseScheme().
Referenced by System.Uri.Uri(), System.Uri.Uri(), System.Uri.Uri(), System.Uri.Uri(), System.Uri.Uri(), System.Uri.Uri(), and System.Uri.CreateUri().