Terraria: System.Uri.CheckSchemeSyntax
CheckSchemeSyntax()
static unsafe ParsingError System.Uri.CheckSchemeSyntax (ReadOnlySpan< char > span, ref UriParser syntax) inline static private
Definition at line 2553 of file Uri.cs.
    {
        if (span.Length == 0)
        {
            return ParsingError.BadScheme;
        }
        char c2 = span[0];
        switch (c2)
        {
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
            c2 = (char)(c2 | 0x20u);
            break;
        default:
            return ParsingError.BadScheme;
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
            break;
        }
        switch (span.Length)
        {
        case 2:
            if (30579 == (((uint)c2 << 8) | ToLowerCaseAscii(span[1])))
            {
                syntax = UriParser.WsUri;
                return ParsingError.None;
            }
            break;
        case 3:
            switch ((int)(((uint)c2 << 16) | ((uint)ToLowerCaseAscii(span[1]) << 8) | ToLowerCaseAscii(span[2])))
            {
            case 6714480:
                syntax = UriParser.FtpUri;
                return ParsingError.None;
            case 7828339:
                syntax = UriParser.WssUri;
                return ParsingError.None;
            }
            break;
        case 4:
            switch ((int)(((uint)c2 << 24) | ((uint)ToLowerCaseAscii(span[1]) << 16) | ((uint)ToLowerCaseAscii(span[2]) << 8) | ToLowerCaseAscii(span[3])))
            {
            case 1752462448:
                syntax = UriParser.HttpUri;
                return ParsingError.None;
            case 1718185061:
                syntax = UriParser.FileUri;
                return ParsingError.None;
            }
            break;
        case 5:
            if (1752462448 == (((uint)c2 << 24) | ((uint)ToLowerCaseAscii(span[1]) << 16) | ((uint)ToLowerCaseAscii(span[2]) << 8) | ToLowerCaseAscii(span[3])) && ToLowerCaseAscii(span[4]) == 's')
            {
                syntax = UriParser.HttpsUri;
                return ParsingError.None;
            }
            break;
        case 6:
            if (1835100524 == (((uint)c2 << 24) | ((uint)ToLowerCaseAscii(span[1]) << 16) | ((uint)ToLowerCaseAscii(span[2]) << 8) | ToLowerCaseAscii(span[3])) && ToLowerCaseAscii(span[4]) == 't' && ToLowerCaseAscii(span[5]) == 'o')
            {
                syntax = UriParser.MailToUri;
                return ParsingError.None;
            }
            break;
        }
        for (int i = 1; i < span.Length; i++)
        {
            char c3 = span[i];
            if ((uint)(c3 - 97) > 25u && (uint)(c3 - 65) > 25u && (uint)(c3 - 48) > 9u && c3 != '+' && c3 != '-' && c3 != '.')
            {
                return ParsingError.BadScheme;
            }
        }
        if (span.Length > 1024)
        {
            return ParsingError.SchemeLimit;
        }
        string lwrCaseScheme;
        fixed (char* ptr = span)
        {
            lwrCaseScheme = string.Create(span.Length, ((IntPtr)ptr, span.Length), delegate(Span<char> buffer, (IntPtr ip, int length) state)
            {
                int num = new ReadOnlySpan<char>((void*)state.ip, state.length).ToLowerInvariant(buffer);
            });
        }
        syntax = UriParser.FindOrFetchAsUnknownV1Syntax(lwrCaseScheme);
        return ParsingError.None;
        static char ToLowerCaseAscii(char c)
        {
            if ((uint)(c - 65) > 25u)
            {
                return c;
            }
            return (char)(c | 0x20u);
        }
    }
References System.buffer, System.Runtime.Serialization.Dictionary, System.UriParser.FileUri, System.UriParser.FindOrFetchAsUnknownV1Syntax(), System.UriParser.FtpUri, System.UriParser.HttpsUri, System.UriParser.HttpUri, System.length, System.UriParser.MailToUri, System.state, System.UriParser.WssUri, and System.UriParser.WsUri.
Referenced by System.Uri.GetCombinedString(), and System.Uri.ParseSchemeCheckImplicitFile().