Terraria: System.Uri.UnescapeDataString
UnescapeDataString()
static string System.Uri.UnescapeDataString (string stringToUnescape) inline static
Definition at line 4058 of file Uri.cs.
    {
        if (stringToUnescape == null)
        {
            throw new ArgumentNullException("stringToUnescape");
        }
        if (stringToUnescape.Length == 0)
        {
            return string.Empty;
        }
        int num = stringToUnescape.IndexOf('%');
        if (num == -1)
        {
            return stringToUnescape;
        }
        Span<char> initialBuffer = stackalloc char[512];
        System.Text.ValueStringBuilder dest = new System.Text.ValueStringBuilder(initialBuffer);
        dest.EnsureCapacity(stringToUnescape.Length);
        dest.Append(stringToUnescape.AsSpan(0, num));
        UriHelper.UnescapeString(stringToUnescape, num, stringToUnescape.Length, ref dest, '\uffff', '\uffff', '\uffff', UnescapeMode.Unescape | UnescapeMode.UnescapeAll, null, isQuery: false);
        return dest.ToString();
    }
References System.Runtime.Serialization.Dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.EnsureCapacity(), and System.UriHelper.UnescapeString().
Referenced by System.Net.FtpWebRequest.FtpWebRequest(), Terraria.Main.ConvertFromSafeArgument(), Terraria.Net.NetGroupInfo.ConvertFromSafeInfo(), System.Net.Http.HttpEnvironmentProxyCredentials.GetCredentialsFromString(), System.Uri.GetRelativeSerializationString(), and System.Net.Http.HttpEnvironmentProxy.GetUriFromString().