Terraria: System.Uri.GetHostViaCustomSyntax
GetHostViaCustomSyntax()
unsafe void System.Uri.GetHostViaCustomSyntax () inline private
Definition at line 1751 of file Uri.cs.
    {
        if (_info.Host != null)
        {
            return;
        }
        string text = _syntax.InternalGetComponents(this, UriComponents.Host, UriFormat.UriEscaped);
        if (_info.Host == null)
        {
            if (text.Length >= 65520)
            {
                throw GetException(ParsingError.SizeLimit);
            }
            ParsingError err = ParsingError.None;
            Flags flags = (Flags)((ulong)_flags & 0xFFFFFFFFFFF8FFFFuL);
            fixed (char* pString = text)
            {
                string newHost = null;
                if (CheckAuthorityHelper(pString, 0, text.Length, ref err, ref flags, _syntax, ref newHost) != text.Length)
                {
                    flags = (Flags)((ulong)flags & 0xFFFFFFFFFFF8FFFFuL);
                    flags |= Flags.HostTypeMask;
                }
            }
            if (err != 0 || (flags & Flags.HostTypeMask) == Flags.HostTypeMask)
            {
                _flags = (Flags)(((ulong)_flags & 0xFFFFFFFFFFF8FFFFuL) | 0x50000);
            }
            else
            {
                text = CreateHostStringHelper(text, 0, text.Length, ref flags, ref _info.ScopeId);
                for (int i = 0; i < text.Length; i++)
                {
                    if (_info.Offset.Host + i >= _info.Offset.End || text[i] != _string[_info.Offset.Host + i])
                    {
                        _flags |= Flags.HostNotCanonical | Flags.E_HostNotCanonical;
                        break;
                    }
                }
                _flags = (Flags)(((ulong)_flags & 0xFFFFFFFFFFF8FFFFuL) | (ulong)(flags & Flags.HostTypeMask));
            }
        }
        string text2 = _syntax.InternalGetComponents(this, UriComponents.StrongPort, UriFormat.UriEscaped);
        int num = 0;
        if (string.IsNullOrEmpty(text2))
        {
            _flags &= ~Flags.NotDefaultPort;
            _flags |= Flags.PortNotCanonical | Flags.E_PortNotCanonical;
            _info.Offset.PortValue = 0;
        }
        else
        {
            for (int j = 0; j < text2.Length; j++)
            {
                int num2 = text2[j] - 48;
                if (num2 < 0 || num2 > 9 || (num = num * 10 + num2) > 65535)
                {
                    throw new UriFormatException(System.SR.Format(System.SR.net_uri_PortOutOfRange, _syntax.GetType(), text2));
                }
            }
            if (num != _info.Offset.PortValue)
            {
                if (num == _syntax.DefaultPort)
                {
                    _flags &= ~Flags.NotDefaultPort;
                }
                else
                {
                    _flags |= Flags.NotDefaultPort;
                }
                _flags |= Flags.PortNotCanonical | Flags.E_PortNotCanonical;
                _info.Offset.PortValue = (ushort)num;
            }
        }
        _info.Host = text;
    }
References System.Uri._flags, System.Uri._info, System.Uri._string, System.Uri._syntax, System.Uri.CheckAuthorityHelper(), System.Uri.CreateHostStringHelper(), System.UriParser.DefaultPort, System.Runtime.Serialization.Dictionary, System.Uri.Offset.End, System.SR.Format(), System.Uri.GetException(), System.Uri.UriInfo.Host, System.Uri.Offset.Host, System.UriParser.InternalGetComponents(), System.SR.net_uri_PortOutOfRange, System.Uri.UriInfo.Offset, System.Uri.Offset.PortValue, System.Uri.UriInfo.ScopeId, and System.text.
Referenced by System.Uri.CreateHostString().