Terraria: System.Uri.InternalGetComponents
InternalGetComponents()
string System.Uri.InternalGetComponents (UriComponents components, UriFormat format) inline private
Definition at line 3892 of file Uri.cs.
    {
        if (((uint)components & 0x80000000u) != 0 && components != UriComponents.SerializationInfoString)
        {
            throw new ArgumentOutOfRangeException("components", components, System.SR.net_uri_NotJustSerialization);
        }
        if (((uint)format & 0xFFFFFFFCu) != 0)
        {
            throw new ArgumentOutOfRangeException("format");
        }
        if (IsNotAbsoluteUri)
        {
            if (components == UriComponents.SerializationInfoString)
            {
                return GetRelativeSerializationString(format);
            }
            throw new InvalidOperationException(System.SR.net_uri_NotAbsolute);
        }
        if (Syntax.IsSimple)
        {
            return GetComponentsHelper(components, format);
        }
        return Syntax.InternalGetComponents(this, components, format);
    }
References System.format, System.Uri.GetComponentsHelper(), System.Uri.GetRelativeSerializationString(), System.UriParser.InternalGetComponents(), System.Uri.IsNotAbsoluteUri, System.UriParser.IsSimple, System.SR.net_uri_NotAbsolute, System.SR.net_uri_NotJustSerialization, and System.Uri.Syntax.
Referenced by System.Uri.GetComponents(), and System.Uri.GetParts().