Terraria: System.Uri.Uri
Uri() [8/9]
System.Uri.Uri (Uri baseUri, Uri relativeUri) inline
Definition at line 794 of file Uri.cs.
    {
        if ((object)baseUri == null)
        {
            throw new ArgumentNullException("baseUri");
        }
        if (!baseUri.IsAbsoluteUri)
        {
            throw new ArgumentOutOfRangeException("baseUri");
        }
        CreateThisFromUri(relativeUri);
        string newUriString = null;
        bool userEscaped;
        if (baseUri.Syntax.IsSimple)
        {
            userEscaped = InFact(Flags.UserEscaped);
            Uri uri = ResolveHelper(baseUri, this, ref newUriString, ref userEscaped);
            if (uri != null)
            {
                if ((object)this != uri)
                {
                    CreateThisFromUri(uri);
                }
                return;
            }
        }
        else
        {
            userEscaped = false;
            newUriString = baseUri.Syntax.InternalResolve(baseUri, this, out var parsingError);
            if (parsingError != null)
            {
                throw parsingError;
            }
        }
        _flags = Flags.Zero;
        _info = null;
        _syntax = null;
        _originalUnicodeString = null;
        string uri2 = newUriString;
        bool dontEscape = userEscaped;
        UriCreationOptions creationOptions = default(UriCreationOptions);
        CreateThis(uri2, dontEscape, UriKind.Absolute, in creationOptions);
    }
References System.Uri._flags, System.Uri._info, System.Uri._originalUnicodeString, System.Uri._syntax, System.Uri.CreateThis(), System.Uri.CreateThisFromUri(), System.creationOptions, System.Runtime.Serialization.Dictionary, System.Uri.InFact(), System.UriParser.InternalResolve(), System.Uri.IsAbsoluteUri, System.UriParser.IsSimple, System.Uri.ResolveHelper(), and System.Uri.Syntax.