Terraria: System.Uri.GetLeftPart
GetLeftPart()
string System.Uri.GetLeftPart (UriPartial part) inline
Definition at line 1006 of file Uri.cs.
    {
        if (IsNotAbsoluteUri)
        {
            throw new InvalidOperationException(System.SR.net_uri_NotAbsolute);
        }
        EnsureUriInfo();
        switch (part)
        {
        case UriPartial.Scheme:
            return GetParts(UriComponents.Scheme | UriComponents.KeepDelimiter, UriFormat.UriEscaped);
        case UriPartial.Authority:
            if (NotAny(Flags.AuthorityFound) || IsDosPath)
            {
                return string.Empty;
            }
            return GetParts(UriComponents.SchemeAndServer | UriComponents.UserInfo, UriFormat.UriEscaped);
        case UriPartial.Path:
            return GetParts(UriComponents.SchemeAndServer | UriComponents.UserInfo | UriComponents.Path, UriFormat.UriEscaped);
        case UriPartial.Query:
            return GetParts(UriComponents.HttpRequestUrl | UriComponents.UserInfo, UriFormat.UriEscaped);
        default:
            throw new ArgumentException(System.SR.Format(System.SR.Argument_InvalidUriSubcomponent, part), "part");
        }
    }
References System.SR.Argument_InvalidUriSubcomponent, System.Uri.EnsureUriInfo(), System.SR.Format(), System.Uri.GetParts(), System.Uri.IsDosPath, System.Uri.IsNotAbsoluteUri, System.SR.net_uri_NotAbsolute, and System.Uri.NotAny().