Terraria: System.Uri.GetCombinedString
GetCombinedString()
static void System.Uri.GetCombinedString (Uri baseUri, string relativeStr, bool dontEscape, ref string result) inline static private
Definition at line 839 of file Uri.cs.
    {
        for (int i = 0; i < relativeStr.Length && relativeStr[i] != '/' && relativeStr[i] != '\\' && relativeStr[i] != '?' && relativeStr[i] != '#'; i++)
        {
            if (relativeStr[i] == ':')
            {
                if (i < 2)
                {
                    break;
                }
                UriParser syntax = null;
                if (CheckSchemeSyntax(relativeStr.AsSpan(0, i), ref syntax) != 0)
                {
                    break;
                }
                if (baseUri.Syntax == syntax)
                {
                    relativeStr = ((i + 1 >= relativeStr.Length) ? string.Empty : relativeStr.Substring(i + 1));
                    break;
                }
                result = relativeStr;
                return;
            }
        }
        if (relativeStr.Length == 0)
        {
            result = baseUri.OriginalString;
        }
        else
        {
            result = CombineUri(baseUri, relativeStr, dontEscape ? UriFormat.UriEscaped : UriFormat.SafeUnescaped);
        }
    }
References System.Uri.CheckSchemeSyntax(), System.Uri.CombineUri(), System.Runtime.Serialization.Dictionary, System.Uri.OriginalString, and System.Uri.Syntax.
Referenced by System.Uri.ResolveHelper().