Terraria: System.Uri.GetUriPartsFromUserString
GetUriPartsFromUserString()
string System.Uri.GetUriPartsFromUserString (UriComponents uriParts) inline private
Definition at line 2069 of file Uri.cs.
    {
        switch (uriParts & ~UriComponents.KeepDelimiter)
        {
        case UriComponents.SchemeAndServer:
            if (!InFact(Flags.HasUserInfo))
            {
                return _string.Substring(_info.Offset.Scheme, _info.Offset.Path - _info.Offset.Scheme);
            }
            return string.Concat(_string.AsSpan(_info.Offset.Scheme, _info.Offset.User - _info.Offset.Scheme), _string.AsSpan(_info.Offset.Host, _info.Offset.Path - _info.Offset.Host));
        case UriComponents.HostAndPort:
            if (InFact(Flags.HasUserInfo))
            {
                if (InFact(Flags.NotDefaultPort) || _syntax.DefaultPort == -1)
                {
                    return _string.Substring(_info.Offset.Host, _info.Offset.Path - _info.Offset.Host);
                }
                return string.Concat(_string.AsSpan(_info.Offset.Host, _info.Offset.Path - _info.Offset.Host), ":", _info.Offset.PortValue.ToString(CultureInfo.InvariantCulture));
            }
            goto case UriComponents.StrongAuthority;
        case UriComponents.AbsoluteUri:
            if (_info.Offset.Scheme == 0 && _info.Offset.End == _string.Length)
            {
                return _string;
            }
            return _string.Substring(_info.Offset.Scheme, _info.Offset.End - _info.Offset.Scheme);
        case UriComponents.HttpRequestUrl:
            if (InFact(Flags.HasUserInfo))
            {
                return string.Concat(_string.AsSpan(_info.Offset.Scheme, _info.Offset.User - _info.Offset.Scheme), _string.AsSpan(_info.Offset.Host, _info.Offset.Fragment - _info.Offset.Host));
            }
            if (_info.Offset.Scheme == 0 && _info.Offset.Fragment == _string.Length)
            {
                return _string;
            }
            return _string.Substring(_info.Offset.Scheme, _info.Offset.Fragment - _info.Offset.Scheme);
        case UriComponents.SchemeAndServer | UriComponents.UserInfo:
            return _string.Substring(_info.Offset.Scheme, _info.Offset.Path - _info.Offset.Scheme);
        case UriComponents.HttpRequestUrl | UriComponents.UserInfo:
            if (_info.Offset.Scheme == 0 && _info.Offset.Fragment == _string.Length)
            {
                return _string;
            }
            return _string.Substring(_info.Offset.Scheme, _info.Offset.Fragment - _info.Offset.Scheme);
        case UriComponents.Scheme:
            if (uriParts != UriComponents.Scheme)
            {
                return _string.Substring(_info.Offset.Scheme, _info.Offset.User - _info.Offset.Scheme);
            }
            return _syntax.SchemeName;
        case UriComponents.Host:
        {
            int num2 = _info.Offset.Path;
            if (InFact(Flags.PortNotCanonical | Flags.NotDefaultPort))
            {
                while (_string[--num2] != ':')
                {
                }
            }
            if (num2 - _info.Offset.Host != 0)
            {
                return _string.Substring(_info.Offset.Host, num2 - _info.Offset.Host);
            }
            return string.Empty;
        }
        case UriComponents.Path:
        {
            int num = ((uriParts != UriComponents.Path || !InFact(Flags.AuthorityFound) || _info.Offset.End <= _info.Offset.Path || _string[_info.Offset.Path] != '/') ? _info.Offset.Path : (_info.Offset.Path + 1));
            if (num >= _info.Offset.Query)
            {
                return string.Empty;
            }
            return _string.Substring(num, _info.Offset.Query - num);
        }
        case UriComponents.Query:
        {
            int num = ((uriParts != UriComponents.Query) ? _info.Offset.Query : (_info.Offset.Query + 1));
            if (num >= _info.Offset.Fragment)
            {
                return string.Empty;
            }
            return _string.Substring(num, _info.Offset.Fragment - num);
        }
        case UriComponents.Fragment:
        {
            int num = ((uriParts != UriComponents.Fragment) ? _info.Offset.Fragment : (_info.Offset.Fragment + 1));
            if (num >= _info.Offset.End)
            {
                return string.Empty;
            }
            return _string.Substring(num, _info.Offset.End - num);
        }
        case UriComponents.UserInfo | UriComponents.Host | UriComponents.Port:
            if (_info.Offset.Path - _info.Offset.User != 0)
            {
                return _string.Substring(_info.Offset.User, _info.Offset.Path - _info.Offset.User);
            }
            return string.Empty;
        case UriComponents.StrongAuthority:
            if (!InFact(Flags.NotDefaultPort) && _syntax.DefaultPort != -1)
            {
                return string.Concat(_string.AsSpan(_info.Offset.User, _info.Offset.Path - _info.Offset.User), ":", _info.Offset.PortValue.ToString(CultureInfo.InvariantCulture));
            }
            goto case UriComponents.UserInfo | UriComponents.Host | UriComponents.Port;
        case UriComponents.PathAndQuery:
            return _string.Substring(_info.Offset.Path, _info.Offset.Fragment - _info.Offset.Path);
        case UriComponents.HttpRequestUrl | UriComponents.Fragment:
            if (InFact(Flags.HasUserInfo))
            {
                return string.Concat(_string.AsSpan(_info.Offset.Scheme, _info.Offset.User - _info.Offset.Scheme), _string.AsSpan(_info.Offset.Host, _info.Offset.End - _info.Offset.Host));
            }
            if (_info.Offset.Scheme == 0 && _info.Offset.End == _string.Length)
            {
                return _string;
            }
            return _string.Substring(_info.Offset.Scheme, _info.Offset.End - _info.Offset.Scheme);
        case UriComponents.PathAndQuery | UriComponents.Fragment:
            return _string.Substring(_info.Offset.Path, _info.Offset.End - _info.Offset.Path);
        case UriComponents.UserInfo:
        {
            if (NotAny(Flags.HasUserInfo))
            {
                return string.Empty;
            }
            int num = ((uriParts != UriComponents.UserInfo) ? _info.Offset.Host : (_info.Offset.Host - 1));
            if (_info.Offset.User >= num)
            {
                return string.Empty;
            }
            return _string.Substring(_info.Offset.User, num - _info.Offset.User);
        }
        default:
            return null;
        }
    }
References System.Uri._info, System.Uri._string, System.Uri._syntax, System.UriParser.DefaultPort, System.Runtime.Serialization.Dictionary, System.Uri.Offset.End, System.Uri.Offset.Fragment, System.Uri.Offset.Host, System.Uri.InFact(), System.Globalization.CultureInfo.InvariantCulture, System.Uri.NotAny(), System.Uri.UriInfo.Offset, System.Uri.Offset.Path, System.Uri.Offset.PortValue, System.Uri.Offset.Query, System.Uri.Offset.Scheme, System.UriParser.SchemeName, and System.Uri.Offset.User.
Referenced by System.Uri.GetEscapedParts(), and System.Uri.GetUnescapedParts().