Terraria: System.Uri.CreateUri
CreateUri()
void System.Uri.CreateUri (Uri baseUri, string relativeUri, bool dontEscape) inline private
Definition at line 757 of file Uri.cs.
    {
        string uri = relativeUri;
        bool dontEscape2 = dontEscape;
        UriCreationOptions creationOptions = default(UriCreationOptions);
        CreateThis(uri, dontEscape2, UriKind.RelativeOrAbsolute, in creationOptions);
        if (baseUri.Syntax.IsSimple)
        {
            Uri uri2 = ResolveHelper(baseUri, this, ref relativeUri, ref dontEscape);
            if (uri2 != null)
            {
                if ((object)this != uri2)
                {
                    CreateThisFromUri(uri2);
                }
                return;
            }
        }
        else
        {
            dontEscape = false;
            relativeUri = baseUri.Syntax.InternalResolve(baseUri, this, out var parsingError);
            if (parsingError != null)
            {
                throw parsingError;
            }
        }
        _flags = Flags.Zero;
        _info = null;
        _syntax = null;
        _originalUnicodeString = null;
        string uri3 = relativeUri;
        bool dontEscape3 = dontEscape;
        creationOptions = default(UriCreationOptions);
        CreateThis(uri3, dontEscape3, UriKind.Absolute, in creationOptions);
    }
References System.Uri._flags, System.Uri._info, System.Uri._originalUnicodeString, System.Uri._syntax, System.Uri.CreateThis(), System.Uri.CreateThisFromUri(), System.creationOptions, System.Runtime.Serialization.Dictionary, System.UriParser.InternalResolve(), System.UriParser.IsSimple, System.Uri.ResolveHelper(), and System.Uri.Syntax.
Referenced by System.Uri.Uri(), and System.Uri.Uri().