Terraria: System.Uri.IsHexDigit
IsHexDigit()
static bool System.Uri.IsHexDigit (char character) inline static
Definition at line 1088 of file Uri.cs.
    {
        return System.HexConverter.IsHexChar(character);
    }
References System.HexConverter.IsHexChar().
Referenced by System.IPv6AddressHelper.InternalIsValid(), System.Uri.IsHexEncoding(), and System.IPv6AddressHelper.IsValidStrict().