Terraria: System.Uri.InternalIsWellFormedOriginalString
InternalIsWellFormedOriginalString()
unsafe bool System.Uri.InternalIsWellFormedOriginalString () inline package
Definition at line 3964 of file Uri.cs.
    {
        if (UserDrivenParsing)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_uri_UserDrivenParsing, GetType()));
        }
        fixed (char* ptr = _string)
        {
            int idx = 0;
            if (!IsAbsoluteUri)
            {
                if (CheckForColonInFirstPathSegment(_string))
                {
                    return false;
                }
                return (CheckCanonical(ptr, ref idx, _string.Length, '\ufffe') & (Check.EscapedCanonical | Check.BackslashInPath)) == Check.EscapedCanonical;
            }
            if (IsImplicitFile)
            {
                return false;
            }
            EnsureParseRemaining();
            Flags flags = _flags & (Flags.E_CannotDisplayCanonical | Flags.IriCanonical);
            if ((flags & Flags.IriCanonical) != Flags.Zero)
            {
                if ((flags & (Flags.E_UserNotCanonical | Flags.UserIriCanonical)) == (Flags.E_UserNotCanonical | Flags.UserIriCanonical))
                {
                    flags &= ~(Flags.E_UserNotCanonical | Flags.UserIriCanonical);
                }
                if ((flags & (Flags.E_PathNotCanonical | Flags.PathIriCanonical)) == (Flags.E_PathNotCanonical | Flags.PathIriCanonical))
                {
                    flags &= ~(Flags.E_PathNotCanonical | Flags.PathIriCanonical);
                }
                if ((flags & (Flags.E_QueryNotCanonical | Flags.QueryIriCanonical)) == (Flags.E_QueryNotCanonical | Flags.QueryIriCanonical))
                {
                    flags &= ~(Flags.E_QueryNotCanonical | Flags.QueryIriCanonical);
                }
                if ((flags & (Flags.E_FragmentNotCanonical | Flags.FragmentIriCanonical)) == (Flags.E_FragmentNotCanonical | Flags.FragmentIriCanonical))
                {
                    flags &= ~(Flags.E_FragmentNotCanonical | Flags.FragmentIriCanonical);
                }
            }
            if ((flags & Flags.E_CannotDisplayCanonical & (Flags.E_UserNotCanonical | Flags.E_PathNotCanonical | Flags.E_QueryNotCanonical | Flags.E_FragmentNotCanonical)) != Flags.Zero)
            {
                return false;
            }
            if (InFact(Flags.AuthorityFound))
            {
                idx = _info.Offset.Scheme + _syntax.SchemeName.Length + 2;
                if (idx >= _info.Offset.User || _string[idx - 1] == '\\' || _string[idx] == '\\')
                {
                    return false;
                }
                if (InFact(Flags.DosPath | Flags.UncPath) && ++idx < _info.Offset.User && (_string[idx] == '/' || _string[idx] == '\\'))
                {
                    return false;
                }
            }
            if (InFact(Flags.FirstSlashAbsent) && _info.Offset.Query > _info.Offset.Path)
            {
                return false;
            }
            if (InFact(Flags.BackslashInPath))
            {
                return false;
            }
            if (IsDosPath && _string[_info.Offset.Path + SecuredPathIndex - 1] == '|')
            {
                return false;
            }
            if ((_flags & Flags.CanonicalDnsHost) == Flags.Zero && HostType != Flags.IPv6HostType)
            {
                idx = _info.Offset.User;
                Check check = CheckCanonical(ptr, ref idx, _info.Offset.Path, '/');
                if ((check & (Check.EscapedCanonical | Check.BackslashInPath | Check.ReservedFound)) != Check.EscapedCanonical && (!IriParsing || (check & (Check.DisplayCanonical | Check.NotIriCanonical | Check.FoundNonAscii)) != (Check.DisplayCanonical | Check.FoundNonAscii)))
                {
                    return false;
                }
            }
            if ((_flags & (Flags.SchemeNotCanonical | Flags.AuthorityFound)) == (Flags.SchemeNotCanonical | Flags.AuthorityFound))
            {
                idx = _syntax.SchemeName.Length;
                while (ptr[idx++] != ':')
                {
                }
                if (idx + 1 >= _string.Length || ptr[idx] != '/' || ptr[idx + 1] != '/')
                {
                    return false;
                }
            }
        }
        return true;
    }
References System.Uri._flags, System.Uri._info, System.Uri._string, System.Uri._syntax, System.Uri.CheckCanonical(), System.Uri.CheckForColonInFirstPathSegment(), System.Runtime.Serialization.Dictionary, System.Uri.EnsureParseRemaining(), System.SR.Format(), System.Uri.HostType, System.Uri.InFact(), System.Uri.IriParsing, System.Uri.IsAbsoluteUri, System.Uri.IsDosPath, System.Uri.IsImplicitFile, System.SR.net_uri_UserDrivenParsing, System.Uri.UriInfo.Offset, System.Uri.Offset.Path, System.UriParser.SchemeName, System.Uri.SecuredPathIndex, System.Uri.Offset.User, and System.Uri.UserDrivenParsing.
Referenced by System.Uri.IsWellFormedOriginalString(), and System.UriParser.IsWellFormedOriginalString().