Terraria: System.Uri.IsBaseOf
IsBaseOf()
bool System.Uri.IsBaseOf (Uri uri) inline
Definition at line 4278 of file Uri.cs.
    {
        if ((object)uri == null)
        {
            throw new ArgumentNullException("uri");
        }
        if (!IsAbsoluteUri)
        {
            return false;
        }
        if (Syntax.IsSimple)
        {
            return IsBaseOfHelper(uri);
        }
        return Syntax.InternalIsBaseOf(this, uri);
    }
References System.UriParser.InternalIsBaseOf(), System.Uri.IsAbsoluteUri, System.Uri.IsBaseOfHelper(), System.UriParser.IsSimple, and System.Uri.Syntax.
Referenced by System.Xml.Xsl.Runtime.XmlCollation.Create(), and System.Net.FtpControlStream.TryUpdateResponseUri().