Terraria: System.Uri.GetException
GetException()
static UriFormatException System.Uri.GetException (ParsingError err) inline static private
Definition at line 873 of file Uri.cs.
    {
        return err switch
        {
            ParsingError.None => null,
            ParsingError.BadFormat => new UriFormatException(System.SR.net_uri_BadFormat),
            ParsingError.BadScheme => new UriFormatException(System.SR.net_uri_BadScheme),
            ParsingError.BadAuthority => new UriFormatException(System.SR.net_uri_BadAuthority),
            ParsingError.EmptyUriString => new UriFormatException(System.SR.net_uri_EmptyUri),
            ParsingError.SchemeLimit => new UriFormatException(System.SR.net_uri_SchemeLimit),
            ParsingError.SizeLimit => new UriFormatException(System.SR.net_uri_SizeLimit),
            ParsingError.MustRootedPath => new UriFormatException(System.SR.net_uri_MustRootedPath),
            ParsingError.BadHostName => new UriFormatException(System.SR.net_uri_BadHostName),
            ParsingError.NonEmptyHost => new UriFormatException(System.SR.net_uri_BadFormat),
            ParsingError.BadPort => new UriFormatException(System.SR.net_uri_BadPort),
            ParsingError.BadAuthorityTerminator => new UriFormatException(System.SR.net_uri_BadAuthorityTerminator),
            ParsingError.CannotCreateRelative => new UriFormatException(System.SR.net_uri_CannotCreateRelative),
            _ => new UriFormatException(System.SR.net_uri_BadFormat),
        };
    }
References System.Runtime.Serialization.Dictionary, System.SR.net_uri_BadAuthority, System.SR.net_uri_BadAuthorityTerminator, System.SR.net_uri_BadFormat, System.SR.net_uri_BadHostName, System.SR.net_uri_BadPort, System.SR.net_uri_BadScheme, System.SR.net_uri_CannotCreateRelative, System.SR.net_uri_EmptyUri, System.SR.net_uri_MustRootedPath, System.SR.net_uri_SchemeLimit, and System.SR.net_uri_SizeLimit.
Referenced by System.Uri.CreateHostStringHelper(), System.Uri.GetHostViaCustomSyntax(), System.Uri.InitializeUri(), System.Uri.ParseMinimal(), and System.Uri.ParseRemaining().