Terraria: System.Uri.CreateThisFromUri
CreateThisFromUri()
void System.Uri.CreateThisFromUri (Uri otherUri) inline private
Definition at line 4358 of file Uri.cs.
    {
        _info = null;
        _flags = otherUri._flags;
        if (InFact(Flags.MinimalUriInfoSet))
        {
            _flags &= ~(Flags.IndexMask | Flags.MinimalUriInfoSet | Flags.AllUriInfoSet);
            int num = otherUri._info.Offset.Path;
            if (InFact(Flags.NotDefaultPort))
            {
                while (otherUri._string[num] != ':' && num > otherUri._info.Offset.Host)
                {
                    num--;
                }
                if (otherUri._string[num] != ':')
                {
                    num = otherUri._info.Offset.Path;
                }
            }
            _flags |= (Flags)num;
        }
        _syntax = otherUri._syntax;
        _string = otherUri._string;
        _originalUnicodeString = otherUri._originalUnicodeString;
    }
References System.Uri._flags, System.Uri._info, System.Uri._originalUnicodeString, System.Uri._string, System.Uri._syntax, System.Runtime.Serialization.Dictionary, and System.Uri.InFact().
Referenced by System.Uri.Uri(), and System.Uri.CreateUri().