Terraria: System.Uri.TryCreate
TryCreate() [2/4]
static bool System.Uri.TryCreate ([NotNullWhen(true)] string? uriString, UriKind uriKind, [NotNullWhen(true)] out Uri? result) inline static
Definition at line 3793 of file Uri.cs.
    {
        if (uriString == null)
        {
            result = null;
            return false;
        }
        UriFormatException e = null;
        UriCreationOptions creationOptions = default(UriCreationOptions);
        result = CreateHelper(uriString, dontEscape: false, uriKind, ref e, in creationOptions);
        if (e == null)
        {
            return result != null;
        }
        return false;
    }
References System.Uri.CreateHelper(), System.creationOptions, and System.Runtime.Serialization.Dictionary.
Referenced by System.Net.CookieContainer.Add(), System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingCookedPath(), System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath(), System.Runtime.Serialization.DataContract.CheckExplicitDataContractNamespaceUri(), System.Xml.Xsl.Runtime.XmlCollation.Create(), System.Uri.Equals(), System.Net.CookieParser.Get(), System.Xml.Xsl.SourceLineInfo.GetFileName(), System.Net.WebClient.GetUri(), System.Net.WebClient.GetUri(), System.UriTypeConverter.IsValid(), System.Net.Http.HttpRuleParser.IsValidHostName(), System.Uri.IsWellFormedUriString(), System.Net.ServiceNameStore.NormalizeServiceName(), System.Security.Authentication.ExtendedProtection.ServiceNameCollection.NormalizeServiceName(), System.Text.Json.Serialization.Converters.UriConverter.Read(), System.Net.WebRequest.RegisterPrefix(), System.Xml.Extensions.ExtensionMethods.ToUri(), System.Xml.XmlConvert.ToUri(), System.Uri.TryCreate(), System.Net.HttpWebRequest.TryGetHostUri(), System.Net.Http.MultiProxy.TryParseProxyConfigPart(), System.Net.Http.Headers.UriHeaderParser.TryParseValue(), System.Web.Util.UriUtil.TrySplitUriForPathEncode(), System.Xml.XmlConvert.TryToUri(), and System.Net.FtpControlStream.TryUpdateResponseUri().