Terraria: System.Uri.ToString
ToString()
override string System.Uri.ToString () inline
Definition at line 1119 of file Uri.cs.
    {
        if (_syntax == null)
        {
            return _string;
        }
        EnsureUriInfo();
        if (_info.String == null)
        {
            if (_syntax.IsSimple)
            {
                _info.String = GetComponentsHelper(UriComponents.AbsoluteUri, (UriFormat)32767);
            }
            else
            {
                _info.String = GetParts(UriComponents.AbsoluteUri, UriFormat.SafeUnescaped);
            }
        }
        return _info.String;
    }
References System.Uri._info, System.Uri._string, System.Uri._syntax, System.Runtime.Serialization.Dictionary, System.Uri.EnsureUriInfo(), System.Uri.GetComponentsHelper(), System.Uri.GetParts(), System.UriParser.IsSimple, and System.Uri.UriInfo.String.
Referenced by System.Net.CredentialKey.CredentialKey(), System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), System.Xml.Xsl.XsltOld.ContainerAction.CompileInclude(), System.Xml.Xsl.XsltOld.ContainerAction.CompileTopLevelElements(), System.Xml.XmlReaderSettings.CreateReader(), System.Xml.Xsl.Xslt.XsltLoader.CreateReader(), System.Security.IdentityHelper.GetNormalizedUriHash(), System.Xml.DtdParser.Initialize(), System.Xml.XmlTextReaderImpl.InitStreamInput(), System.Xml.XmlTextReaderImpl.InitStreamInputAsync(), System.Xml.Xsl.Xslt.XsltLoader.LoadImport(), System.Xml.Xsl.Xslt.XsltLoader.LoadInclude(), System.Xml.XmlTextReaderImpl.OpenAndPush(), System.Xml.XmlTextReaderImpl.OpenAndPushAsync(), System.Xml.XmlTextReaderImpl.OpenUrl(), System.Xml.DtdParser.ParseExternalSubset(), System.Xml.DtdParser.ParseExternalSubsetAsync(), System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubset(), System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubsetAsync(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.Throw(), System.Net.Cookie.ToServerString(), and System.Net.Http.HttpRequestMessage.ToString().