Terraria: System.Uri.GetEscapedParts
GetEscapedParts()
string System.Uri.GetEscapedParts (UriComponents uriParts) inline private
Definition at line 1833 of file Uri.cs.
    {
        ushort num = (ushort)(((ushort)_flags & 0x3F80) >> 6);
        if (InFact(Flags.SchemeNotCanonical))
        {
            num = (ushort)(num | 1u);
        }
        if ((uriParts & UriComponents.Path) != 0)
        {
            if (InFact(Flags.ShouldBeCompressed | Flags.FirstSlashAbsent | Flags.BackslashInPath))
            {
                num = (ushort)(num | 0x10u);
            }
            else if (IsDosPath && _string[_info.Offset.Path + SecuredPathIndex - 1] == '|')
            {
                num = (ushort)(num | 0x10u);
            }
        }
        if (((ushort)uriParts & num) == 0)
        {
            string uriPartsFromUserString = GetUriPartsFromUserString(uriParts);
            if (uriPartsFromUserString != null)
            {
                return uriPartsFromUserString;
            }
        }
        return ReCreateParts(uriParts, num, UriFormat.UriEscaped);
    }
References System.Uri._flags, System.Uri._info, System.Uri._string, System.Runtime.Serialization.Dictionary, System.Uri.GetUriPartsFromUserString(), System.Uri.InFact(), System.Uri.IsDosPath, System.Uri.UriInfo.Offset, System.Uri.Offset.Path, System.Uri.ReCreateParts(), and System.Uri.SecuredPathIndex.
Referenced by System.Uri.GetComponentsHelper().