Terraria: System.Uri.ParseMinimal
ParseMinimal()
UriFormatException System.Uri.ParseMinimal () inline package
Definition at line 1343 of file Uri.cs.
    {
        ParsingError parsingError = PrivateParseMinimal();
        if (parsingError == ParsingError.None)
        {
            return null;
        }
        _flags |= Flags.ErrorOrParsingRecursion;
        return GetException(parsingError);
    }
References System.Uri._flags, System.Uri.GetException(), and System.Uri.PrivateParseMinimal().
Referenced by System.UriParser.InitializeAndValidate().