Terraria: System.Uri.CreateHelper
CreateHelper()
static Uri System.Uri.CreateHelper (string uriString, bool dontEscape, UriKind uriKind, ref UriFormatException e, in UriCreationOptions creationOptions = default(UriCreationOptions)) inline static package
Definition at line 4107 of file Uri.cs.
    {
        if (uriKind < UriKind.RelativeOrAbsolute || uriKind > UriKind.Relative)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_uri_InvalidUriKind, uriKind));
        }
        UriParser syntax = null;
        Flags flags = Flags.Zero;
        ParsingError parsingError = ParseScheme(uriString, ref flags, ref syntax);
        if (dontEscape)
        {
            flags |= Flags.UserEscaped;
        }
        if (creationOptions.DangerousDisablePathAndQueryCanonicalization)
        {
            flags |= Flags.DisablePathAndQueryCanonicalization;
        }
        if (parsingError != 0)
        {
            if (uriKind != UriKind.Absolute && parsingError <= ParsingError.EmptyUriString)
            {
                return new Uri(flags & Flags.UserEscaped, null, uriString);
            }
            return null;
        }
        Uri uri = new Uri(flags, syntax, uriString);
        try
        {
            uri.InitializeUri(parsingError, uriKind, out e);
            if (e == null)
            {
                return uri;
            }
            return null;
        }
        catch (UriFormatException ex)
        {
            e = ex;
            return null;
        }
    }
References System.Uri.Uri(), System.creationOptions, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Uri.InitializeUri(), System.SR.net_uri_InvalidUriKind, and System.Uri.ParseScheme().
Referenced by System.Uri.IsBaseOfHelper(), System.Uri.TryCreate(), System.Uri.TryCreate(), and System.Uri.TryCreate().