Terraria: System.Uri.GetRelativeSerializationString
GetRelativeSerializationString()
string System.Uri.GetRelativeSerializationString (UriFormat format) inline private
Definition at line 4205 of file Uri.cs.
    {
        switch (format)
        {
        case UriFormat.UriEscaped:
            return UriHelper.EscapeString(_string, checkExistingEscaped: true, UriHelper.UnreservedReservedTable);
        case UriFormat.Unescaped:
            return UnescapeDataString(_string);
        case UriFormat.SafeUnescaped:
        {
            if (_string.Length == 0)
            {
                return string.Empty;
            }
            Span<char> initialBuffer = stackalloc char[512];
            System.Text.ValueStringBuilder dest = new System.Text.ValueStringBuilder(initialBuffer);
            UriHelper.UnescapeString(_string, ref dest, '\uffff', '\uffff', '\uffff', UnescapeMode.EscapeUnescape, null, isQuery: false);
            return dest.ToString();
        }
        default:
            throw new ArgumentOutOfRangeException("format");
        }
    }
References System.Uri._string, System.UriHelper.EscapeString(), System.format, System.Uri.UnescapeDataString(), System.UriHelper.UnescapeString(), and System.UriHelper.UnreservedReservedTable.
Referenced by System.Uri.InternalGetComponents().