Terraria: System.Uri.GetComponentsHelper
GetComponentsHelper()
string System.Uri.GetComponentsHelper (UriComponents uriComponents, UriFormat uriFormat) inline package
Definition at line 4229 of file Uri.cs.
    {
        if (uriComponents == UriComponents.Scheme)
        {
            return _syntax.SchemeName;
        }
        if (((uint)uriComponents & 0x80000000u) != 0)
        {
            uriComponents |= UriComponents.AbsoluteUri;
        }
        EnsureParseRemaining();
        if ((uriComponents & UriComponents.NormalizedHost) != 0)
        {
            uriComponents |= UriComponents.Host;
        }
        if ((uriComponents & UriComponents.Host) != 0)
        {
            EnsureHostString(allowDnsOptimization: true);
        }
        if (uriComponents == UriComponents.Port || uriComponents == UriComponents.StrongPort)
        {
            if ((_flags & Flags.NotDefaultPort) != Flags.Zero || (uriComponents == UriComponents.StrongPort && _syntax.DefaultPort != -1))
            {
                return _info.Offset.PortValue.ToString(CultureInfo.InvariantCulture);
            }
            return string.Empty;
        }
        if ((uriComponents & UriComponents.StrongPort) != 0)
        {
            uriComponents |= UriComponents.Port;
        }
        if (uriComponents == UriComponents.Host && (uriFormat == UriFormat.UriEscaped || (_flags & (Flags.HostNotCanonical | Flags.E_HostNotCanonical)) == Flags.Zero))
        {
            EnsureHostString(allowDnsOptimization: false);
            return _info.Host;
        }
        switch (uriFormat)
        {
        case UriFormat.UriEscaped:
            return GetEscapedParts(uriComponents);
        case UriFormat.Unescaped:
        case UriFormat.SafeUnescaped:
        case (UriFormat)32767:
            return GetUnescapedParts(uriComponents, uriFormat);
        default:
            throw new ArgumentOutOfRangeException("uriFormat");
        }
    }
References System.Uri._flags, System.Uri._info, System.Uri._syntax, System.Runtime.Serialization.Dictionary, System.Uri.EnsureHostString(), System.Uri.EnsureParseRemaining(), System.Uri.GetEscapedParts(), System.Uri.GetUnescapedParts(), System.Uri.UriInfo.Host, System.Globalization.CultureInfo.InvariantCulture, System.Uri.UriInfo.Offset, System.Uri.Offset.PortValue, and System.UriParser.SchemeName.
Referenced by System.UriParser.GetComponents(), System.Uri.InternalGetComponents(), and System.Uri.ToString().