Terraria: System.Uri.EnsureUriInfo
EnsureUriInfo()
UriInfo System.Uri.EnsureUriInfo () inline private
Definition at line 626 of file Uri.cs.
    {
        Flags flags = _flags;
        if ((flags & Flags.MinimalUriInfoSet) == Flags.Zero)
        {
            CreateUriInfo(flags);
        }
        return _info;
    }
References System.Uri._flags, System.Uri._info, and System.Uri.CreateUriInfo().
Referenced by System.Uri.EnsureHostString(), System.Uri.Equals(), System.Uri.GetHashCode(), System.Uri.GetLeftPart(), System.Uri.ParseRemaining(), and System.Uri.ToString().