Terraria: System.Uri.Equals
Equals()
override bool System.Uri.Equals ([NotNullWhen(true)] object? comparand) inline
Definition at line 1166 of file Uri.cs.
    {
        if (comparand == null)
        {
            return false;
        }
        if (this == comparand)
        {
            return true;
        }
        Uri result = comparand as Uri;
        if ((object)result == null)
        {
            if (DisablePathAndQueryCanonicalization)
            {
                return false;
            }
            if (!(comparand is string text))
            {
                return false;
            }
            if ((object)text == OriginalString)
            {
                return true;
            }
            if (!TryCreate(text, UriKind.RelativeOrAbsolute, out result))
            {
                return false;
            }
        }
        if (DisablePathAndQueryCanonicalization != result.DisablePathAndQueryCanonicalization)
        {
            return false;
        }
        if ((object)OriginalString == result.OriginalString)
        {
            return true;
        }
        if (IsAbsoluteUri != result.IsAbsoluteUri)
        {
            return false;
        }
        if (IsNotAbsoluteUri)
        {
            return OriginalString.Equals(result.OriginalString);
        }
        if ((NotAny(Flags.AllUriInfoSet) || result.NotAny(Flags.AllUriInfoSet)) && string.Equals(_string, result._string, IsUncOrDosPath ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal))
        {
            return true;
        }
        EnsureUriInfo();
        result.EnsureUriInfo();
        if (!UserDrivenParsing && !result.UserDrivenParsing && Syntax.IsSimple && result.Syntax.IsSimple)
        {
            if (InFact(Flags.CanonicalDnsHost) && result.InFact(Flags.CanonicalDnsHost))
            {
                int num = _info.Offset.Host;
                int num2 = _info.Offset.Path;
                int num3 = result._info.Offset.Host;
                int path = result._info.Offset.Path;
                string @string = result._string;
                if (num2 - num > path - num3)
                {
                    num2 = num + path - num3;
                }
                while (num < num2)
                {
                    if (_string[num] != @string[num3])
                    {
                        return false;
                    }
                    if (@string[num3] == ':')
                    {
                        break;
                    }
                    num++;
                    num3++;
                }
                if (num < _info.Offset.Path && _string[num] != ':')
                {
                    return false;
                }
                if (num3 < path && @string[num3] != ':')
                {
                    return false;
                }
            }
            else
            {
                EnsureHostString(allowDnsOptimization: false);
                result.EnsureHostString(allowDnsOptimization: false);
                if (!_info.Host.Equals(result._info.Host))
                {
                    return false;
                }
            }
            if (Port != result.Port)
            {
                return false;
            }
        }
        MoreInfo moreInfo = _info.MoreInfo;
        MoreInfo moreInfo2 = result._info.MoreInfo;
        MoreInfo moreInfo3 = moreInfo;
        string a = moreInfo3.RemoteUrl ?? (moreInfo3.RemoteUrl = GetParts(UriComponents.HttpRequestUrl, UriFormat.SafeUnescaped));
        moreInfo3 = moreInfo2;
        string b = moreInfo3.RemoteUrl ?? (moreInfo3.RemoteUrl = result.GetParts(UriComponents.HttpRequestUrl, UriFormat.SafeUnescaped));
        return string.Equals(a, b, IsUncOrDosPath ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal);
    }
References System.Uri.Uri(), System.Uri._info, System.Uri._string, System.Runtime.Serialization.Dictionary, System.Uri.DisablePathAndQueryCanonicalization, System.Uri.EnsureHostString(), System.Uri.EnsureUriInfo(), System.Uri.GetParts(), System.Uri.UriInfo.Host, System.Uri.Offset.Host, System.Uri.InFact(), System.Uri.IsAbsoluteUri, System.Uri.IsNotAbsoluteUri, System.UriParser.IsSimple, System.Uri.IsUncOrDosPath, System.Uri.UriInfo.MoreInfo, System.Uri.NotAny(), System.Uri.UriInfo.Offset, System.Uri.OriginalString, System.Uri.Offset.Path, System.Uri.Port, System.Uri.Syntax, System.text, System.Uri.TryCreate(), and System.Uri.UserDrivenParsing.
Referenced by System.Net.CredentialKey.Equals(), System.Xml.Schema.ChameleonKey.Equals(), System.UriBuilder.Equals(), and System.Net.Http.HttpEnvironmentProxyCredentials.GetCredential().