Terraria: System.Uri.CreateUriInfo
CreateUriInfo()
unsafe void System.Uri.CreateUriInfo (Flags cF) inline private
Definition at line 1490 of file Uri.cs.
    {
        UriInfo uriInfo = new UriInfo();
        uriInfo.Offset.End = (ushort)_string.Length;
        if (!UserDrivenParsing)
        {
            bool flag = false;
            int i;
            if ((cF & Flags.ImplicitFile) != Flags.Zero)
            {
                i = 0;
                while (UriHelper.IsLWS(_string[i]))
                {
                    i++;
                    uriInfo.Offset.Scheme++;
                }
                if (StaticInFact(cF, Flags.UncPath))
                {
                    i += 2;
                    for (int num = (int)(cF & Flags.IndexMask); i < num && (_string[i] == '/' || _string[i] == '\\'); i++)
                    {
                    }
                }
            }
            else
            {
                i = _syntax.SchemeName.Length;
                while (_string[i++] != ':')
                {
                    uriInfo.Offset.Scheme++;
                }
                if ((cF & Flags.AuthorityFound) != Flags.Zero)
                {
                    if (_string[i] == '\\' || _string[i + 1] == '\\')
                    {
                        flag = true;
                    }
                    i += 2;
                    if ((cF & (Flags.DosPath | Flags.UncPath)) != Flags.Zero)
                    {
                        for (int num2 = (int)(cF & Flags.IndexMask); i < num2 && (_string[i] == '/' || _string[i] == '\\'); i++)
{
                            flag = true;
                        }
                    }
                }
            }
            if (_syntax.DefaultPort != -1)
            {
                uriInfo.Offset.PortValue = (ushort)_syntax.DefaultPort;
            }
            if ((cF & Flags.HostTypeMask) == Flags.HostTypeMask || StaticInFact(cF, Flags.DosPath))
            {
                uriInfo.Offset.User = (ushort)(cF & Flags.IndexMask);
                uriInfo.Offset.Host = uriInfo.Offset.User;
                uriInfo.Offset.Path = uriInfo.Offset.User;
                cF = (Flags)((ulong)cF & 0xFFFFFFFFFFFF0000uL);
                if (flag)
                {
                    cF |= Flags.SchemeNotCanonical;
                }
            }
            else
            {
                uriInfo.Offset.User = (ushort)i;
                if (HostType == Flags.BasicHostType)
                {
                    uriInfo.Offset.Host = (ushort)i;
                    uriInfo.Offset.Path = (ushort)(cF & Flags.IndexMask);
                    cF = (Flags)((ulong)cF & 0xFFFFFFFFFFFF0000uL);
                }
                else
                {
                    if ((cF & Flags.HasUserInfo) != Flags.Zero)
                    {
                        for (; _string[i] != '@'; i++)
{
                        }
                        i++;
                        uriInfo.Offset.Host = (ushort)i;
                    }
                    else
                    {
                        uriInfo.Offset.Host = (ushort)i;
                    }
                    i = (int)(cF & Flags.IndexMask);
                    cF = (Flags)((ulong)cF & 0xFFFFFFFFFFFF0000uL);
                    if (flag)
                    {
                        cF |= Flags.SchemeNotCanonical;
                    }
                    uriInfo.Offset.Path = (ushort)i;
                    bool flag2 = false;
                    if ((cF & Flags.HasUnicode) != Flags.Zero)
                    {
                        uriInfo.Offset.End = (ushort)_originalUnicodeString.Length;
                    }
                    if (i < uriInfo.Offset.End)
                    {
                        fixed (char* ptr = OriginalString)
{
                            if (ptr[i] == ':')
{
                                int num3 = 0;
                                if (++i < uriInfo.Offset.End)
{
                                    num3 = ptr[i] - 48;
                                    if ((uint)num3 <= 9u)
{
                                        flag2 = true;
                                        if (num3 == 0)
{
                                            cF |= Flags.PortNotCanonical | Flags.E_PortNotCanonical;
                                        }
                                        for (i++; i < uriInfo.Offset.End; i++)
{
                                            int num4 = ptr[i] - 48;
                                            if ((uint)num4 > 9u)
{
                                                break;
                                            }
                                            num3 = num3 * 10 + num4;
                                        }
                                    }
                                }
                                if (flag2 && _syntax.DefaultPort != num3)
{
                                    uriInfo.Offset.PortValue = (ushort)num3;
                                    cF |= Flags.NotDefaultPort;
                                }
                                else
{
                                    cF |= Flags.PortNotCanonical | Flags.E_PortNotCanonical;
                                }
                                uriInfo.Offset.Path = (ushort)i;
                            }
                        }
                    }
                }
            }
        }
        cF |= Flags.MinimalUriInfoSet;
        Interlocked.CompareExchange(ref _info, uriInfo, null);
        Flags flags = _flags;
        while ((flags & Flags.MinimalUriInfoSet) == Flags.Zero)
        {
            Flags value = (Flags)(((ulong)flags & 0xFFFFFFFFFFFF0000uL) | (ulong)cF);
            ulong num5 = Interlocked.CompareExchange(ref Internal.Runtime.CompilerServices.Unsafe.As<Flags, ulong>(ref _flags), (ulong)value, (ulong)flags);
            if (num5 == (ulong)flags)
            {
                break;
            }
            flags = (Flags)num5;
        }
    }
References System.Uri._flags, System.Uri._info, System.Uri._originalUnicodeString, System.Uri._string, System.Uri._syntax, System.Threading.Interlocked.CompareExchange(), System.UriParser.DefaultPort, System.Runtime.Serialization.Dictionary, System.Uri.HostType, System.UriHelper.IsLWS(), System.Uri.OriginalString, System.UriParser.SchemeName, System.Uri.StaticInFact(), System.Uri.UserDrivenParsing, and System.value.
Referenced by System.Uri.EnsureUriInfo().