Terraria: System.Uri.InFact
InFact()
bool System.Uri.InFact (Flags flags) inline private
Definition at line 611 of file Uri.cs.
    {
        return (_flags & flags) != 0;
    }
References System.Uri._flags.
Referenced by System.Uri.Uri(), System.Uri.CreateHostString(), System.Uri.CreateThisFromUri(), System.Uri.EnsureHostString(), System.Uri.Equals(), System.Uri.GetCanonicalPath(), System.Uri.GetEscapedParts(), System.Uri.GetLocalPath(), System.Uri.GetUriPartsFromUserString(), System.Uri.InitializeUri(), System.Uri.InternalIsWellFormedOriginalString(), System.Uri.PrivateParseMinimal(), System.Uri.ReCreateParts(), and System.Uri.ResolveHelper().