Terraria: System.Uri.ReCreateParts
ReCreateParts()
string System.Uri.ReCreateParts (UriComponents parts, ushort nonCanonical, UriFormat formatAs) inline private
Definition at line 1887 of file Uri.cs.
    {
        EnsureHostString(allowDnsOptimization: false);
        string @string = _string;
        System.Text.ValueStringBuilder valueStringBuilder;
        if (@string.Length <= 512)
        {
            Span<char> initialBuffer = stackalloc char[512];
            valueStringBuilder = new System.Text.ValueStringBuilder(initialBuffer);
        }
        else
        {
            valueStringBuilder = new System.Text.ValueStringBuilder(@string.Length);
        }
        System.Text.ValueStringBuilder dest = valueStringBuilder;
        if ((parts & UriComponents.Scheme) != 0)
        {
            dest.Append(_syntax.SchemeName);
            if (parts != UriComponents.Scheme)
            {
                dest.Append(':');
                if (InFact(Flags.AuthorityFound))
                {
                    dest.Append('/');
                    dest.Append('/');
                }
            }
        }
        ReadOnlySpan<char> format;
        if ((parts & UriComponents.UserInfo) != 0 && InFact(Flags.HasUserInfo))
        {
            ReadOnlySpan<char> readOnlySpan = @string.AsSpan(_info.Offset.User, _info.Offset.Host - _info.Offset.User);
            if ((nonCanonical & 2u) != 0)
            {
                switch (formatAs)
                {
                case UriFormat.UriEscaped:
                    if (NotAny(Flags.UserEscaped))
                    {
                        UriHelper.EscapeString(readOnlySpan, ref dest, checkExistingEscaped: true, '?', '#');
                        break;
                    }
                    InFact(Flags.E_UserNotCanonical);
                    dest.Append(readOnlySpan);
                    break;
                case UriFormat.SafeUnescaped:
                    format = readOnlySpan;
                    UriHelper.UnescapeString(format[..^1], ref dest, '@', '/', '\\', InFact(Flags.UserEscaped) ? UnescapeMode.Unescape : UnescapeMode.EscapeUnescape, _syntax, isQuery: false);
                    dest.Append('@');
                    break;
                case UriFormat.Unescaped:
                    UriHelper.UnescapeString(readOnlySpan, ref dest, '\uffff', '\uffff', '\uffff', UnescapeMode.Unescape | UnescapeMode.UnescapeAll, _syntax, isQuery: false);
                    break;
                default:
                    dest.Append(readOnlySpan);
                    break;
                }
            }
            else
            {
                dest.Append(readOnlySpan);
            }
            if (parts == UriComponents.UserInfo)
            {
                dest.Length--;
            }
        }
        if ((parts & UriComponents.Host) != 0)
        {
            string text = _info.Host;
            if (text.Length != 0)
            {
                UnescapeMode unescapeMode = ((formatAs != UriFormat.UriEscaped && HostType == Flags.BasicHostType && (nonCanonical & 4u) != 0) ? ((formatAs == UriFormat.Unescaped) ? (UnescapeMode.Unescape | UnescapeMode.UnescapeAll) : (InFact(Flags.UserEscaped) ? UnescapeMode.Unescape : UnescapeMode.EscapeUnescape)) : UnescapeMode.CopyOnly);
                Span<char> initialBuffer = stackalloc char[512];
                System.Text.ValueStringBuilder dest2 = new System.Text.ValueStringBuilder(initialBuffer);
                if ((parts & UriComponents.NormalizedHost) != 0)
                {
                    text = UriHelper.StripBidiControlCharacters(text, text);
                    if (!DomainNameHelper.TryGetUnicodeEquivalent(text, ref dest2))
                    {
                        dest2.Length = 0;
                    }
                }
                UriHelper.UnescapeString((dest2.Length == 0) ? ((ReadOnlySpan<char>)text) : dest2.AsSpan(), ref dest, '/', '?', '#', unescapeMode, _syntax, isQuery: false);
                dest2.Dispose();
                if (((uint)parts & 0x80000000u) != 0 && HostType == Flags.IPv6HostType && _info.ScopeId != null)
                {
                    dest.Length--;
                    dest.Append(_info.ScopeId);
                    dest.Append(']');
                }
            }
        }
        if ((parts & UriComponents.Port) != 0 && (InFact(Flags.NotDefaultPort) || ((parts & UriComponents.StrongPort) != 0 && _syntax.DefaultPort != -1)))
        {
            dest.Append(':');
            ref ushort portValue = ref _info.Offset.PortValue;
            Span<char> destination = dest.AppendSpan(5);
            format = default(ReadOnlySpan<char>);
            int charsWritten;
            bool flag = portValue.TryFormat(destination, out charsWritten, format);
            dest.Length -= 5 - charsWritten;
        }
        if ((parts & UriComponents.Path) != 0)
        {
            GetCanonicalPath(ref dest, formatAs);
            if (parts == UriComponents.Path)
            {
                int start = ((InFact(Flags.AuthorityFound) && dest.Length != 0 && dest[0] == '/') ? 1 : 0);
                format = dest.AsSpan(start);
                string result = format.ToString();
                dest.Dispose();
                return result;
            }
        }
        if ((parts & UriComponents.Query) != 0 && _info.Offset.Query < _info.Offset.Fragment)
        {
            int num = _info.Offset.Query + 1;
            if (parts != UriComponents.Query)
            {
                dest.Append('?');
            }
            UnescapeMode unescapeMode2 = UnescapeMode.CopyOnly;
            if ((nonCanonical & 0x20u) != 0)
            {
                if (formatAs == UriFormat.UriEscaped)
                {
                    if (NotAny(Flags.UserEscaped))
                    {
                        UriHelper.EscapeString(@string.AsSpan(num, _info.Offset.Fragment - num), ref dest, checkExistingEscaped: true, '#');
                        goto IL_04d5;
                    }
                }
                else
                {
                    unescapeMode2 = formatAs switch
                    {
                        (UriFormat)32767 => (InFact(Flags.UserEscaped) ? UnescapeMode.Unescape : UnescapeMode.EscapeUnescape) | UnescapeMode.V1ToStringFlag,
                        UriFormat.Unescaped => UnescapeMode.Unescape | UnescapeMode.UnescapeAll,
                        _ => InFact(Flags.UserEscaped) ? UnescapeMode.Unescape : UnescapeMode.EscapeUnescape,
                    };
                }
            }
            UriHelper.UnescapeString(@string, num, _info.Offset.Fragment, ref dest, '#', '\uffff', '\uffff', unescapeMode2, _syntax, isQuery: true);
        }
        goto IL_04d5;
        IL_04d5:
        if ((parts & UriComponents.Fragment) != 0 && _info.Offset.Fragment < _info.Offset.End)
        {
            int num2 = _info.Offset.Fragment + 1;
            if (parts != UriComponents.Fragment)
            {
                dest.Append('#');
            }
            UnescapeMode unescapeMode3 = UnescapeMode.CopyOnly;
            if ((nonCanonical & 0x40u) != 0)
            {
                if (formatAs == UriFormat.UriEscaped)
                {
                    if (NotAny(Flags.UserEscaped))
                    {
                        UriHelper.EscapeString(@string.AsSpan(num2, _info.Offset.End - num2), ref dest, checkExistingEscaped: true);
                        goto IL_05d8;
                    }
                }
                else
                {
                    unescapeMode3 = formatAs switch
                    {
                        (UriFormat)32767 => (InFact(Flags.UserEscaped) ? UnescapeMode.Unescape : UnescapeMode.EscapeUnescape) | UnescapeMode.V1ToStringFlag,
                        UriFormat.Unescaped => UnescapeMode.Unescape | UnescapeMode.UnescapeAll,
                        _ => InFact(Flags.UserEscaped) ? UnescapeMode.Unescape : UnescapeMode.EscapeUnescape,
                    };
                }
            }
            UriHelper.UnescapeString(@string, num2, _info.Offset.End, ref dest, '#', '\uffff', '\uffff', unescapeMode3, _syntax, isQuery: false);
        }
        goto IL_05d8;
        IL_05d8:
        return dest.ToString();
    }
References System.Uri._info, System.Uri._string, System.Uri._syntax, System.UriParser.DefaultPort, System.destination, System.Runtime.Serialization.Dictionary, System.Uri.Offset.End, System.Uri.EnsureHostString(), System.UriHelper.EscapeString(), System.format, System.Uri.Offset.Fragment, System.Uri.GetCanonicalPath(), System.Uri.UriInfo.Host, System.Uri.Offset.Host, System.Uri.HostType, System.Uri.InFact(), System.Uri.NotAny(), System.Uri.UriInfo.Offset, System.Uri.Offset.PortValue, System.UriParser.SchemeName, System.Uri.UriInfo.ScopeId, System.start, System.UriHelper.StripBidiControlCharacters(), System.text, System.DomainNameHelper.TryGetUnicodeEquivalent(), System.UriHelper.UnescapeString(), and System.Uri.Offset.User.
Referenced by System.Uri.GetEscapedParts(), and System.Uri.GetUnescapedParts().