Terraria: System.Data.DataTableCollection.Clear
Clear()
void System.Data.DataTableCollection.Clear () inline
Definition at line 391 of file DataTableCollection.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTableCollection.Clear|API> {0}", ObjectID);
        try
        {
            int count = _list.Count;
            DataTable[] array = new DataTable[_list.Count];
            _list.CopyTo(array, 0);
            OnCollectionChanging(InternalDataCollectionBase.s_refreshEventArgs);
            if (_dataSet._fInitInProgress && _delayedAddRangeTables != null)
            {
                _delayedAddRangeTables = null;
            }
            BaseGroupSwitch(array, count, Array.Empty<DataTable>(), 0);
            _list.Clear();
            OnCollectionChanged(InternalDataCollectionBase.s_refreshEventArgs);
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTableCollection._dataSet, System.Data.DataTableCollection._delayedAddRangeTables, System.Data.DataSet._fInitInProgress, System.Data.DataTableCollection._list, System.array, System.Data.DataTableCollection.BaseGroupSwitch(), System.Collections.ArrayList.Clear(), System.Collections.ArrayList.CopyTo(), System.count, System.Collections.ArrayList.Count, System.Data.DataCommonEventSource.Log, System.Data.DataTableCollection.ObjectID, System.Data.DataTableCollection.OnCollectionChanged(), System.Data.DataTableCollection.OnCollectionChanging(), and System.Data.InternalDataCollectionBase.s_refreshEventArgs.
Referenced by System.Data.DataSet.Clear(), and System.Data.DataSet.Reset().