Terraria: System.Data.DataTableCollection.InternalIndexOf
InternalIndexOf() [1/2]
int System.Data.DataTableCollection.InternalIndexOf (string tableName) inline package
Definition at line 544 of file DataTableCollection.cs.
    {
        int num = -1;
        if (tableName != null && 0 < tableName.Length)
        {
            int count = _list.Count;
            int num2 = 0;
            for (int i = 0; i < count; i++)
            {
                DataTable dataTable = (DataTable)_list[i];
                switch (NamesEqual(dataTable.TableName, tableName, fCaseSensitive: false, _dataSet.Locale))
                {
                case 1:
                {
                    for (int j = i + 1; j < count; j++)
                    {
                        DataTable dataTable2 = (DataTable)_list[j];
                        if (NamesEqual(dataTable2.TableName, tableName, fCaseSensitive: false, _dataSet.Locale) == 1)
{
                            return -3;
                        }
                    }
                    return i;
                }
                case -1:
                    num = ((num == -1) ? i : (-2));
                    break;
                }
            }
        }
        return num;
    }
References System.Data.DataTableCollection._dataSet, System.Data.DataTableCollection._list, System.count, System.Collections.ArrayList.Count, System.Data.DataSet.Locale, and System.Data.InternalDataCollectionBase.NamesEqual().
Referenced by System.Data.DataTableCollection.Contains(), System.Data.DataTableCollection.Contains(), System.Data.DataTableCollection.Contains(), System.Data.DataTableCollection.Contains(), System.Data.XmlTreeGen.HandleRelation(), System.Data.XmlTreeGen.HandleTable(), System.Data.DataTableCollection.IndexOf(), and System.Data.DataTableCollection.IndexOf().