Terraria: System.Data.DataTableCollection.BaseGroupSwitch
BaseGroupSwitch()
void System.Data.DataTableCollection.BaseGroupSwitch (DataTable[] oldArray, int oldLength, DataTable[] newArray, int newLength) inline private
Definition at line 278 of file DataTableCollection.cs.
    {
        int num = 0;
        for (int i = 0; i < oldLength; i++)
        {
            bool flag = false;
            for (int j = num; j < newLength; j++)
            {
                if (oldArray[i] == newArray[j])
                {
                    if (num == j)
                    {
                        num++;
                    }
                    flag = true;
                    break;
                }
            }
            if (!flag && oldArray[i].DataSet == _dataSet)
            {
                BaseRemove(oldArray[i]);
            }
        }
        for (int k = 0; k < newLength; k++)
        {
            if (newArray[k].DataSet != _dataSet)
            {
                BaseAdd(newArray[k]);
                _list.Add(newArray[k]);
            }
        }
    }
References System.Data.DataTableCollection._dataSet, System.Data.DataTableCollection._list, System.Collections.ArrayList.Add(), System.Data.DataTableCollection.BaseAdd(), and System.Data.DataTableCollection.BaseRemove().
Referenced by System.Data.DataTableCollection.Clear().