Terraria: System.Data.DataTableCollection.CanRemove
CanRemove() [1/2]
bool System.Data.DataTableCollection.CanRemove ([NotNullWhen(true)] DataTable table, bool fThrowException) inline package
Definition at line 327 of file DataTableCollection.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTableCollection.CanRemove|INFO> {0}, table={1}, fThrowException={2}", ObjectID, table?.ObjectID ?? 0, fThrowException);
        try
        {
            if (table == null)
            {
                if (!fThrowException)
                {
                    return false;
                }
                throw ExceptionBuilder.ArgumentNull("table");
            }
            if (table.DataSet != _dataSet)
            {
                if (!fThrowException)
                {
                    return false;
                }
                throw ExceptionBuilder.TableNotInTheDataSet(table.TableName);
            }
            _dataSet.OnRemoveTable(table);
            if (table.ChildRelations.Count != 0 || table.ParentRelations.Count != 0)
            {
                if (!fThrowException)
                {
                    return false;
                }
                throw ExceptionBuilder.TableInRelation();
            }
            ParentForeignKeyConstraintEnumerator parentForeignKeyConstraintEnumerator = new ParentForeignKeyConstraintEnumerator(_dataSet, table);
            while (parentForeignKeyConstraintEnumerator.GetNext())
            {
                ForeignKeyConstraint foreignKeyConstraint = parentForeignKeyConstraintEnumerator.GetForeignKeyConstraint();
                if (foreignKeyConstraint.Table != table || foreignKeyConstraint.RelatedTable != table)
                {
                    if (!fThrowException)
                    {
                        return false;
                    }
                    throw ExceptionBuilder.TableInConstraint(table, foreignKeyConstraint);
                }
            }
            ChildForeignKeyConstraintEnumerator childForeignKeyConstraintEnumerator = new ChildForeignKeyConstraintEnumerator(_dataSet, table);
            while (childForeignKeyConstraintEnumerator.GetNext())
            {
                ForeignKeyConstraint foreignKeyConstraint2 = childForeignKeyConstraintEnumerator.GetForeignKeyConstraint();
                if (foreignKeyConstraint2.Table != table || foreignKeyConstraint2.RelatedTable != table)
                {
                    if (!fThrowException)
                    {
                        return false;
                    }
                    throw ExceptionBuilder.TableInConstraint(table, foreignKeyConstraint2);
                }
            }
            return true;
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTableCollection._dataSet, System.Data.ExceptionBuilder.ArgumentNull(), System.Data.DataTable.ChildRelations, System.Data.InternalDataCollectionBase.Count, System.Data.DataTable.DataSet, System.Data.DataCommonEventSource.Log, System.Data.DataTableCollection.ObjectID, System.Data.DataSet.OnRemoveTable(), System.Data.DataTable.ParentRelations, System.Data.ExceptionBuilder.TableInConstraint(), System.Data.ExceptionBuilder.TableInRelation(), System.Data.DataTable.TableName, and System.Data.ExceptionBuilder.TableNotInTheDataSet().