Terraria: System.Data.DataTableCollection.AssignName
AssignName()
string System.Data.DataTableCollection.AssignName () inline package
Definition at line 239 of file DataTableCollection.cs.
    {
        string text = null;
        while (Contains(text = MakeName(_defaultNameIndex)))
        {
            _defaultNameIndex++;
        }
        return text;
    }
References System.Data.DataTableCollection._defaultNameIndex, System.Data.DataTableCollection.Contains(), System.Data.DataTableCollection.MakeName(), and System.text.
Referenced by System.Data.DataTableCollection.BaseAdd().