Terraria: System.Data.DataTableCollection.RegisterName
RegisterName()
void System.Data.DataTableCollection.RegisterName (string name, string tbNamespace) inline package
Definition at line 645 of file DataTableCollection.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.DataTableCollection.RegisterName|INFO> {0}, name='{1}', tbNamespace='{2}'", ObjectID, name, tbNamespace);
        CultureInfo locale = _dataSet.Locale;
        int count = _list.Count;
        for (int i = 0; i < count; i++)
        {
            DataTable dataTable = (DataTable)_list[i];
            if (NamesEqual(name, dataTable.TableName, fCaseSensitive: true, locale) != 0 && tbNamespace == dataTable.Namespace)
            {
                throw ExceptionBuilder.DuplicateTableName(((DataTable)_list[i]).TableName);
            }
        }
        if (NamesEqual(name, MakeName(_defaultNameIndex), fCaseSensitive: true, locale) != 0)
        {
            _defaultNameIndex++;
        }
    }
References System.Data.DataTableCollection._dataSet, System.Data.DataTableCollection._defaultNameIndex, System.Data.DataTableCollection._list, System.count, System.Collections.ArrayList.Count, System.Data.ExceptionBuilder.DuplicateTableName(), System.Data.DataSet.Locale, System.Data.DataCommonEventSource.Log, System.Data.DataTableCollection.MakeName(), System.Data.InternalDataCollectionBase.NamesEqual(), and System.Data.DataTableCollection.ObjectID.
Referenced by System.Data.DataTableCollection.BaseAdd().