Terraria: System.Data.DataTableCollection.Add
Add() [2/4]
void System.Data.DataTableCollection.Add (DataTable table) inline
Definition at line 163 of file DataTableCollection.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTableCollection.Add|API> {0}, table={1}", ObjectID, table?.ObjectID ?? 0);
        try
        {
            OnCollectionChanging(new CollectionChangeEventArgs(CollectionChangeAction.Add, table));
            BaseAdd(table);
            ArrayAdd(table);
            if (table.SetLocaleValue(_dataSet.Locale, userSet: false, resetIndexes: false) || table.SetCaseSensitiveValue(_dataSet.CaseSensitive, userSet: false, resetIndexes: false))
            {
                table.ResetIndexes();
            }
            OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Add, table));
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTableCollection._dataSet, System.Data.DataTableCollection.ArrayAdd(), System.Data.DataTableCollection.BaseAdd(), System.Data.DataSet.CaseSensitive, System.Data.DataSet.Locale, System.Data.DataCommonEventSource.Log, System.Data.DataTableCollection.ObjectID, System.Data.DataTableCollection.OnCollectionChanged(), System.Data.DataTableCollection.OnCollectionChanging(), System.Data.DataTable.ResetIndexes(), System.Data.DataTable.SetCaseSensitiveValue(), and System.Data.DataTable.SetLocaleValue().
Referenced by System.Data.DataSet.DeserializeDataSetSchema(), System.Data.Common.DataTableMapping.GetDataTableBySchemaAction(), System.Data.XDRSchema.InstantiateSimpleTable(), System.Data.XSDSchema.InstantiateSimpleTable(), System.Data.XDRSchema.InstantiateTable(), System.Data.XSDSchema.InstantiateTable(), System.Data.DataSet.Load(), System.Data.Merger.MergeSchema(), System.Data.ProviderBase.SchemaMapping.SetupSchemaWithKeyInfo(), System.Data.ProviderBase.SchemaMapping.SetupSchemaWithoutKeyInfo(), and System.Data.DataSet.TopLevelTables().