Terraria: System.Data.DataTableCollection.Remove
Remove() [1/3]
void System.Data.DataTableCollection.Remove (DataTable table) inline
Definition at line 664 of file DataTableCollection.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTableCollection.Remove|API> {0}, table={1}", ObjectID, table?.ObjectID ?? 0);
        try
        {
            OnCollectionChanging(new CollectionChangeEventArgs(CollectionChangeAction.Remove, table));
            BaseRemove(table);
            OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Remove, table));
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTableCollection.BaseRemove(), System.Data.DataCommonEventSource.Log, System.Data.DataTableCollection.ObjectID, System.Data.DataTableCollection.OnCollectionChanged(), and System.Data.DataTableCollection.OnCollectionChanging().
Referenced by System.Data.DataTable.SerializeDataTable().