Terraria: System.Data.DataTableCollection.BaseAdd
BaseAdd()
void System.Data.DataTableCollection.BaseAdd ([NotNull] DataTable table) inline private
Definition at line 249 of file DataTableCollection.cs.
    {
        if (table == null)
        {
            throw ExceptionBuilder.ArgumentNull("table");
        }
        if (table.DataSet == _dataSet)
        {
            throw ExceptionBuilder.TableAlreadyInTheDataSet();
        }
        if (table.DataSet != null)
        {
            throw ExceptionBuilder.TableAlreadyInOtherDataSet();
        }
        if (table.TableName.Length == 0)
        {
            table.TableName = AssignName();
        }
        else
        {
            if (NamesEqual(table.TableName, _dataSet.DataSetName, fCaseSensitive: false, _dataSet.Locale) != 0 && !table._fNestedInDataset)
            {
                throw ExceptionBuilder.DatasetConflictingName(_dataSet.DataSetName);
            }
            RegisterName(table.TableName, table.Namespace);
        }
        table.SetDataSet(_dataSet);
    }
References System.Data.DataTableCollection._dataSet, System.Data.ExceptionBuilder.ArgumentNull(), System.Data.DataTableCollection.AssignName(), System.Data.ExceptionBuilder.DatasetConflictingName(), System.Data.DataSet.DataSetName, System.Data.DataSet.Locale, System.Data.InternalDataCollectionBase.NamesEqual(), System.Data.DataTableCollection.RegisterName(), System.Data.ExceptionBuilder.TableAlreadyInOtherDataSet(), and System.Data.ExceptionBuilder.TableAlreadyInTheDataSet().
Referenced by System.Data.DataTableCollection.Add(), and System.Data.DataTableCollection.BaseGroupSwitch().