Terraria: System.Data.DataTableCollection.BaseRemove
BaseRemove()
void System.Data.DataTableCollection.BaseRemove (DataTable table) inline private
Definition at line 311 of file DataTableCollection.cs.
    {
        if (CanRemove(table, fThrowException: true))
        {
            UnregisterName(table.TableName);
            table.SetDataSet(null);
        }
        _list.Remove(table);
        _dataSet.OnRemovedTable(table);
    }
References System.Data.DataTableCollection._dataSet, System.Data.DataTableCollection._list, System.Data.DataTableCollection.CanRemove(), System.Data.DataSet.OnRemovedTable(), System.Collections.ArrayList.Remove(), System.Data.DataTable.SetDataSet(), System.Data.DataTable.TableName, and System.Data.DataTableCollection.UnregisterName().
Referenced by System.Data.DataTableCollection.BaseGroupSwitch(), and System.Data.DataTableCollection.Remove().