Terraria: System.Data.DataTableCollection.UnregisterName
UnregisterName()
void System.Data.DataTableCollection.UnregisterName (string name) inline package
Definition at line 733 of file DataTableCollection.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.DataTableCollection.UnregisterName|INFO> {0}, name='{1}'", ObjectID, name);
        if (NamesEqual(name, MakeName(_defaultNameIndex - 1), fCaseSensitive: true, _dataSet.Locale) != 0)
        {
            do
            {
                _defaultNameIndex--;
            }
            while (_defaultNameIndex > 1 && !Contains(MakeName(_defaultNameIndex - 1)));
        }
    }
References System.Data.DataTableCollection._dataSet, System.Data.DataTableCollection._defaultNameIndex, System.Data.DataTableCollection.Contains(), System.Data.DataSet.Locale, System.Data.DataCommonEventSource.Log, System.Data.DataTableCollection.MakeName(), System.Data.InternalDataCollectionBase.NamesEqual(), and System.Data.DataTableCollection.ObjectID.
Referenced by System.Data.DataTableCollection.BaseRemove().