Terraria: Internal.Cryptography.UniversalCryptoTransform.UncheckedTransformBlock
UncheckedTransformBlock() [1/4]
int Internal.Cryptography.UniversalCryptoTransform.UncheckedTransformBlock (byte[] inputBuffer, int inputOffset, int inputCount, byte[] outputBuffer, int outputOffset) inline protected inherited
Definition at line 119 of file UniversalCryptoTransform.cs.
    {
        return UncheckedTransformBlock(inputBuffer.AsSpan(inputOffset, inputCount), outputBuffer.AsSpan(outputOffset));
    }
References Internal.Cryptography.UniversalCryptoTransform.UncheckedTransformBlock().
Referenced by Internal.Cryptography.UniversalCryptoTransform.TransformBlock(), and Internal.Cryptography.UniversalCryptoTransform.UncheckedTransformBlock().