Terraria: System.IO.Compression.BrotliDecoder.EnsureInitialized
EnsureInitialized()
void System.IO.Compression.BrotliDecoder.EnsureInitialized () inline package
Definition at line 22 of file BrotliDecoder.cs.
    {
        EnsureNotDisposed();
        if (_state == null)
        {
            InitializeDecoder();
        }
    }
References System.IO.Compression.BrotliDecoder._state, System.IO.Compression.BrotliDecoder.EnsureNotDisposed(), and System.IO.Compression.BrotliDecoder.InitializeDecoder().
Referenced by System.IO.Compression.BrotliDecoder.Decompress().