Terraria: System.Net.EndPoint.Serialize
Serialize()
virtual SocketAddress System.Net.EndPoint.Serialize () inline virtual
Reimplemented in System.Net.IPEndPoint, and System.Net.Sockets.UnixDomainSocketEndPoint.
Definition at line 15 of file EndPoint.cs.
    {
        throw System.NotImplemented.ByDesignWithMessage(System.SR.net_MethodNotImplementedException);
    }
References System.NotImplemented.ByDesignWithMessage(), and System.SR.net_MethodNotImplementedException.
Referenced by System.Net.Sockets.SocketsTelemetry.AcceptStart(), and System.Net.Sockets.IPEndPointExtensions.Serialize().