Terraria: Terraria.GameContent.UI.States.UIWorldLoad.UIWorldLoad
UIWorldLoad()
Terraria.GameContent.UI.States.UIWorldLoad.UIWorldLoad () inline
Definition at line 21 of file UIWorldLoad.cs.
    {
        _progressBar.Top.Pixels = 270f;
        _progressBar.HAlign = 0.5f;
        _progressBar.VAlign = 0f;
        _progressBar.Recalculate();
        _progressMessage.CopyStyle(_progressBar);
        _progressMessage.Top.Pixels -= 70f;
        _progressMessage.Recalculate();
        Append(_progressBar);
        Append(_progressMessage);
    }
References Terraria.GameContent.UI.States.UIWorldLoad._progressBar, Terraria.GameContent.UI.States.UIWorldLoad._progressMessage, Terraria.UI.UIElement.Append(), Terraria.UI.UIElement.CopyStyle(), Terraria.GameContent.UI.Elements.UIGenProgressBar.Recalculate(), and Terraria.UI.UIElement.Recalculate().