Terraria: System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.GetBox
GetBox()
IStrongBox System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.GetBox (ParameterExpression variable) inline private
Definition at line 200 of file RuntimeOps.cs.
        {
            foreach (HashSet<ParameterExpression> shadowedVar in _shadowedVars)
            {
                if (shadowedVar.Contains(variable))
                {
                    return null;
                }
            }
            HoistedLocals hoistedLocals = _scope;
            object[] array = _locals;
            while (true)
            {
                if (hoistedLocals.Indexes.TryGetValue(variable, out var value))
                {
                    return (IStrongBox)array[value];
                }
                hoistedLocals = hoistedLocals.Parent;
                if (hoistedLocals == null)
                {
                    break;
                }
                array = HoistedLocals.GetParent(array);
            }
            throw ContractUtils.Unreachable;
        }
References System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter._locals, System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter._scope, System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter._shadowedVars, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Linq.Expressions.Compiler.HoistedLocals.GetParent(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Dynamic.Utils.ContractUtils.Unreachable, and System.value.
Referenced by System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitParameter(), and System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitRuntimeVariables().