Terraria: System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitBlock
VisitBlock()
override Expression System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitBlock (BlockExpression node) inline package virtual
Reimplemented from System.Linq.Expressions.ExpressionVisitor.
Definition at line 121 of file RuntimeOps.cs.
        {
            if (node.Variables.Count > 0)
            {
                _shadowedVars.Push(new HashSet<ParameterExpression>(node.Variables));
            }
            Expression[] array = ExpressionVisitorUtils.VisitBlockExpressions(this, node);
            if (node.Variables.Count > 0)
            {
                _shadowedVars.Pop();
            }
            if (array == null)
            {
                return node;
            }
            return node.Rewrite(node.Variables, array);
        }
References System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter._shadowedVars, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Generic.Stack< T >.Pop(), System.Collections.Generic.Stack< T >.Push(), and System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions().