Terraria: Modifiers.Conditions.Apply
Apply()
override bool Modifiers.Conditions.Apply (Point origin, int x, int y, params object[] args) inline virtual
Implements GenAction.
         {
             bool flag = true;
             for (int i = 0; i < _conditions.Length; i++)
             {
                 flag &= _conditions[i].IsValid(x, y);
             }
             if (flag)
             {
                 return UnitApply(origin, x, y, args);
             }
             return Fail();
         }
References Modifiers.Conditions._conditions, GenAction.Fail(), GenCondition.IsValid(), and GenAction.UnitApply().