Terraria: System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitLambda< T >
VisitLambda< T >()
override Expression System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitLambda< T > (Expression< T > node) inline package virtual
Reimplemented from System.Linq.Expressions.ExpressionVisitor.
Definition at line 97 of file RuntimeOps.cs.
        {
            if (node.ParameterCount > 0)
            {
                HashSet<ParameterExpression> hashSet = new HashSet<ParameterExpression>();
                int i = 0;
                for (int parameterCount = node.ParameterCount; i < parameterCount; i++)
                {
                    hashSet.Add(node.GetParameter(i));
                }
                _shadowedVars.Push(hashSet);
            }
            Expression expression = Visit(node.Body);
            if (node.ParameterCount > 0)
            {
                _shadowedVars.Pop();
            }
            if (expression == node.Body)
            {
                return node;
            }
            return node.Rewrite(expression, null);
        }
References System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter._shadowedVars, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Stack< T >.Pop(), System.Collections.Generic.Stack< T >.Push(), and System.Linq.Expressions.ExpressionVisitor.Visit().