Terraria: System.Text.Json.Serialization.Metadata.JsonTypeInfo.ObjectType
ObjectType
readonly Type System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ObjectType = typeof(object) static package inherited
Definition at line 82 of file JsonTypeInfo.cs.
Referenced by System.Text.Json.Serialization.JsonConverter< T >.JsonConverter(), System.Text.Json.Serialization.Converters.JsonNodeConverterFactory.CanConvert(), System.Text.Json.Serialization.Metadata.ReflectionMemberAccessor.CreateAddMethodDelegate<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods)] TCollection >(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateConstructor(), System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateConverter(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.CreatePropertyInfoForTypeInfo(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateSetterMethod(), System.Text.Json.JsonSerializer.GetRuntimeType< TValue >(), System.Text.Json.JsonSerializer.GetRuntimeTypeAndValidateInputType(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.NumberHandingIsApplicable(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ReadJsonAndAddExtensionProperty(), and System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ReadJsonExtensionDataValue().