Terraria: System.Text.Json.Serialization.Metadata.JsonTypeInfo.ValidateAndAssignDataExtensionProperty
ValidateAndAssignDataExtensionProperty()
void System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ValidateAndAssignDataExtensionProperty (JsonPropertyInfo jsonPropertyInfo) inline private inherited
Definition at line 771 of file JsonTypeInfo.cs.
    {
        if (!IsValidDataExtensionProperty(jsonPropertyInfo))
        {
            ThrowHelper.ThrowInvalidOperationException_SerializationDataExtensionPropertyInvalid(Type, jsonPropertyInfo);
        }
        DataExtensionProperty = jsonPropertyInfo;
    }
References System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.DataExtensionProperty, System.Text.Json.Dictionary, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.IsValidDataExtensionProperty(), and System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializationDataExtensionPropertyInvalid().
Referenced by System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.CacheMember().