Terraria: System.Text.Json.Serialization.Metadata.JsonTypeInfo.JsonTypeInfo
JsonTypeInfo() [5/5]
System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.JsonTypeInfo (Type type, JsonConverter converter, Type runtimeType, JsonSerializerOptions options) inline package
Definition at line 547 of file JsonTypeInfo.cs.
    {
        Type = type;
        Options = options;
        JsonNumberHandling? numberHandlingForType = GetNumberHandlingForType(Type);
        PropertyInfoForTypeInfo = CreatePropertyInfoForTypeInfo(Type, runtimeType, converter, numberHandlingForType, Options);
        ElementType = converter.ElementType;
        switch (PropertyInfoForTypeInfo.ConverterStrategy)
        {
        case ConverterStrategy.Object:
        {
            CreateObject = Options.MemberAccessorStrategy.CreateConstructor(type);
            Dictionary<string, JsonPropertyInfo> ignoredMembers = null;
            PropertyInfo[] properties = type.GetProperties(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            bool propertyOrderSpecified = false;
            PropertyCache = new JsonPropertyDictionary<JsonPropertyInfo>(Options.PropertyNameCaseInsensitive, properties.Length);
            Type type2 = type;
            while (true)
            {
                PropertyInfo[] array = properties;
                foreach (PropertyInfo propertyInfo in array)
                {
                    bool flag = propertyInfo.IsVirtual();
                    string name = propertyInfo.Name;
                    if (propertyInfo.GetIndexParameters().Length != 0 || PropertyIsOverridenAndIgnored(name, propertyInfo.PropertyType, flag, ignoredMembers))
                    {
                        continue;
                    }
                    MethodInfo? getMethod = propertyInfo.GetMethod;
                    if ((object)getMethod == null || !getMethod.IsPublic)
                    {
                        MethodInfo? setMethod = propertyInfo.SetMethod;
                        if ((object)setMethod == null || !setMethod.IsPublic)
{
                            if (JsonPropertyInfo.GetAttribute<JsonIncludeAttribute>(propertyInfo) != null)
{
                                ThrowHelper.ThrowInvalidOperationException_JsonIncludeOnNonPublicInvalid(name, type2);
                            }
                            continue;
                        }
                    }
                    CacheMember(type2, propertyInfo.PropertyType, propertyInfo, flag, numberHandlingForType, ref propertyOrderSpecified, ref ignoredMembers);
                }
                FieldInfo[] fields = type2.GetFields(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                foreach (FieldInfo fieldInfo in fields)
                {
                    string name2 = fieldInfo.Name;
                    if (PropertyIsOverridenAndIgnored(name2, fieldInfo.FieldType, currentMemberIsVirtual: false, ignoredMembers))
                    {
                        continue;
                    }
                    bool flag2 = JsonPropertyInfo.GetAttribute<JsonIncludeAttribute>(fieldInfo) != null;
                    if (fieldInfo.IsPublic)
                    {
                        if (flag2 || Options.IncludeFields)
{
                            CacheMember(type2, fieldInfo.FieldType, fieldInfo, isVirtual: false, numberHandlingForType, ref propertyOrderSpecified, ref ignoredMembers);
                        }
                    }
                    else if (flag2)
                    {
                        ThrowHelper.ThrowInvalidOperationException_JsonIncludeOnNonPublicInvalid(name2, type2);
                    }
                }
                type2 = type2.BaseType;
                if (type2 == null)
                {
                    break;
                }
                properties = type2.GetProperties(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            }
            if (propertyOrderSpecified)
            {
                PropertyCache.List.Sort((KeyValuePair<string, JsonPropertyInfo> p1, KeyValuePair<string, JsonPropertyInfo> p2) => p1.Value.Order.CompareTo(p2.Value.Order));
            }
            if (converter.ConstructorIsParameterized)
            {
                converter.Initialize(Options, this);
                ParameterInfo[] parameters = converter.ConstructorInfo.GetParameters();
                int num = parameters.Length;
                JsonParameterInfoValues[] parameterInfoArray = GetParameterInfoArray(parameters);
                InitializeConstructorParameters(parameterInfoArray);
            }
            break;
        }
        case ConverterStrategy.Enumerable:
            CreateObject = Options.MemberAccessorStrategy.CreateConstructor(runtimeType);
            if (converter.RequiresDynamicMemberAccessors)
            {
                converter.Initialize(Options, this);
            }
            break;
        case ConverterStrategy.Dictionary:
            KeyType = converter.KeyType;
            CreateObject = Options.MemberAccessorStrategy.CreateConstructor(runtimeType);
            if (converter.RequiresDynamicMemberAccessors)
            {
                converter.Initialize(Options, this);
            }
            break;
        case ConverterStrategy.Value:
            CreateObject = Options.MemberAccessorStrategy.CreateConstructor(type);
            break;
        case ConverterStrategy.None:
            ThrowHelper.ThrowNotSupportedException_SerializationNotSupported(type);
            break;
        default:
            throw new InvalidOperationException();
        }
    }
References System.array, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.CacheMember(), System.converter, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ConverterStrategy, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.CreateObject, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.CreatePropertyInfoForTypeInfo(), System.Text.Json.Dictionary, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ElementType, System.Reflection.PropertyInfo.GetIndexParameters(), System.Reflection.PropertyInfo.GetMethod, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.GetNumberHandlingForType(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.GetParameterInfoArray(), System.Text.Json.JsonSerializerOptions.IncludeFields, System.Collections.Generic.Dictionary< TKey, TValue >.Initialize(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.InitializeConstructorParameters(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.KeyType, System.Text.Json.JsonSerializerOptions.MemberAccessorStrategy, System.Reflection.MemberInfo.Name, System.options, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.Options, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.PropertyCache, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.PropertyInfoForTypeInfo, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.PropertyIsOverridenAndIgnored(), System.Text.Json.JsonSerializerOptions.PropertyNameCaseInsensitive, System.Reflection.PropertyInfo.PropertyType, System.Reflection.PropertyInfo.SetMethod, System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonIncludeOnNonPublicInvalid(), System.Text.Json.ThrowHelper.ThrowNotSupportedException_SerializationNotSupported(), and System.type.