Terraria: System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializeConstructorParameters
InitializeConstructorParameters()
void System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.InitializeConstructorParameters (JsonParameterInfoValues[] jsonParameters, bool sourceGenMode = false) inline private inherited
Definition at line 700 of file JsonTypeInfo.cs.
    {
        JsonPropertyDictionary<JsonParameterInfo> jsonPropertyDictionary = new JsonPropertyDictionary<JsonParameterInfo>(Options.PropertyNameCaseInsensitive, jsonParameters.Length);
        Dictionary<ParameterLookupKey, ParameterLookupValue> dictionary = new Dictionary<ParameterLookupKey, ParameterLookupValue>(PropertyCache.Count);
        foreach (KeyValuePair<string, JsonPropertyInfo> item in PropertyCache.List)
        {
            JsonPropertyInfo value = item.Value;
            string clrName = value.ClrName;
            ParameterLookupKey key = new ParameterLookupKey(clrName, value.DeclaredPropertyType);
            ParameterLookupValue value2 = new ParameterLookupValue(value);
            if (!dictionary.TryAdd(in key, in value2))
            {
                ParameterLookupValue parameterLookupValue = dictionary[key];
                parameterLookupValue.DuplicateName = clrName;
            }
        }
        foreach (JsonParameterInfoValues jsonParameterInfoValues in jsonParameters)
        {
            ParameterLookupKey parameterLookupKey = new ParameterLookupKey(jsonParameterInfoValues.Name, jsonParameterInfoValues.ParameterType);
            if (dictionary.TryGetValue(parameterLookupKey, out var value3))
            {
                if (value3.DuplicateName != null)
                {
                    ThrowHelper.ThrowInvalidOperationException_MultiplePropertiesBindToConstructorParameters(Type, jsonParameterInfoValues.Name, value3.JsonPropertyInfo.NameAsString, value3.DuplicateName);
                }
                JsonPropertyInfo jsonPropertyInfo = value3.JsonPropertyInfo;
                JsonParameterInfo value4 = CreateConstructorParameter(jsonParameterInfoValues, jsonPropertyInfo, sourceGenMode, Options);
                jsonPropertyDictionary.Add(jsonPropertyInfo.NameAsString, value4);
            }
            else if (DataExtensionProperty != null && StringComparer.OrdinalIgnoreCase.Equals(parameterLookupKey.Name, DataExtensionProperty.NameAsString))
            {
                ThrowHelper.ThrowInvalidOperationException_ExtensionDataCannotBindToCtorParam(DataExtensionProperty);
            }
        }
        ParameterCache = jsonPropertyDictionary;
        ParameterCount = jsonParameters.Length;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.CreateConstructorParameter(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.DataExtensionProperty, System.dictionary, System.Text.Json.Dictionary, System.item, System.key, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.NameAsString, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.Options, System.StringComparer.OrdinalIgnoreCase, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ParameterCache, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ParameterCount, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.PropertyCache, System.Text.Json.JsonSerializerOptions.PropertyNameCaseInsensitive, System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExtensionDataCannotBindToCtorParam(), System.Text.Json.ThrowHelper.ThrowInvalidOperationException_MultiplePropertiesBindToConstructorParameters(), and System.value.
Referenced by System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.JsonTypeInfo(), and System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.InitializeParameterCache().