Terraria: System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropCache
InitializePropCache()
void System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.InitializePropCache () inline package inherited
Definition at line 479 of file JsonTypeInfo.cs.
    {
        JsonSerializerContext context = Options._context;
        JsonPropertyInfo[] array;
        if (PropInitFunc == null || (array = PropInitFunc(context)) == null)
        {
            ThrowHelper.ThrowInvalidOperationException_NoMetadataForTypeProperties(context, Type);
            return;
        }
        Dictionary<string, JsonPropertyInfo> ignoredMembers = null;
        JsonPropertyDictionary<JsonPropertyInfo> propertyCache = new JsonPropertyDictionary<JsonPropertyInfo>(Options.PropertyNameCaseInsensitive, array.Length);
        foreach (JsonPropertyInfo jsonPropertyInfo in array)
        {
            bool srcGen_HasJsonInclude = jsonPropertyInfo.SrcGen_HasJsonInclude;
            if (!jsonPropertyInfo.SrcGen_IsPublic)
            {
                if (srcGen_HasJsonInclude)
                {
                    ThrowHelper.ThrowInvalidOperationException_JsonIncludeOnNonPublicInvalid(jsonPropertyInfo.ClrName, jsonPropertyInfo.DeclaringType);
                }
            }
            else if (jsonPropertyInfo.MemberType != MemberTypes.Field || srcGen_HasJsonInclude || Options.IncludeFields)
            {
                if (jsonPropertyInfo.SrcGen_IsExtensionData)
                {
                    DataExtensionProperty = jsonPropertyInfo;
                }
                else
                {
                    CacheMember(jsonPropertyInfo, propertyCache, ref ignoredMembers);
                }
            }
        }
        PropertyCache = propertyCache;
    }
References System.Text.Json.JsonSerializerOptions._context, System.array, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.CacheMember(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.DataExtensionProperty, System.Text.Json.Dictionary, System.Text.Json.JsonSerializerOptions.IncludeFields, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.Options, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.PropertyCache, System.Text.Json.JsonSerializerOptions.PropertyNameCaseInsensitive, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.PropInitFunc, System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonIncludeOnNonPublicInvalid(), and System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NoMetadataForTypeProperties().