Terraria: System.Text.Json.Serialization.Metadata.JsonTypeInfo.GetProperty
GetProperty()
JsonPropertyInfo System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.GetProperty (ReadOnlySpan< byte > propertyName, ref ReadStackFrame frame, out byte[] utf8PropertyName) inline package inherited
Definition at line 205 of file JsonTypeInfo.cs.
    {
        ulong key = GetKey(propertyName);
        PropertyRef[] propertyRefsSorted = _propertyRefsSorted;
        if (propertyRefsSorted != null)
        {
            int propertyIndex = frame.PropertyIndex;
            int num = propertyRefsSorted.Length;
            int num2 = Math.Min(propertyIndex, num);
            int num3 = num2 - 1;
            while (true)
            {
                if (num2 < num)
                {
                    PropertyRef propertyRef = propertyRefsSorted[num2];
                    if (IsPropertyRefEqual(in propertyRef, propertyName, key))
                    {
                        utf8PropertyName = propertyRef.NameFromJson;
                        return propertyRef.Info;
                    }
                    num2++;
                    if (num3 >= 0)
                    {
                        propertyRef = propertyRefsSorted[num3];
                        if (IsPropertyRefEqual(in propertyRef, propertyName, key))
{
                            utf8PropertyName = propertyRef.NameFromJson;
                            return propertyRef.Info;
                        }
                        num3--;
                    }
                }
                else
                {
                    if (num3 < 0)
                    {
                        break;
                    }
                    PropertyRef propertyRef = propertyRefsSorted[num3];
                    if (IsPropertyRefEqual(in propertyRef, propertyName, key))
                    {
                        utf8PropertyName = propertyRef.NameFromJson;
                        return propertyRef.Info;
                    }
                    num3--;
                }
            }
        }
        if (PropertyCache.TryGetValue(JsonHelpers.Utf8GetString(propertyName), out var value))
        {
            if (Options.PropertyNameCaseInsensitive)
            {
                if (propertyName.SequenceEqual(value.NameAsUtf8Bytes))
                {
                    utf8PropertyName = value.NameAsUtf8Bytes;
                }
                else
                {
                    utf8PropertyName = propertyName.ToArray();
                }
            }
            else
            {
                utf8PropertyName = value.NameAsUtf8Bytes;
            }
        }
        else
        {
            value = JsonPropertyInfo.s_missingProperty;
            utf8PropertyName = propertyName.ToArray();
        }
        int num4 = 0;
        if (propertyRefsSorted != null)
        {
            num4 = propertyRefsSorted.Length;
        }
        if (num4 < 64)
        {
            if (frame.PropertyRefCache != null)
            {
                num4 += frame.PropertyRefCache.Count;
            }
            if (num4 < 64)
            {
                if (frame.PropertyRefCache == null)
                {
                    frame.PropertyRefCache = new List<PropertyRef>();
                }
                PropertyRef propertyRef = new PropertyRef(key, value, utf8PropertyName);
                frame.PropertyRefCache.Add(propertyRef);
            }
        }
        return value;
    }
References System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >._propertyRefsSorted, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Text.Json.Dictionary, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.GetKey(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.IsPropertyRefEqual(), System.key, System.Math.Min(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.Options, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.PropertyCache, System.Text.Json.JsonSerializerOptions.PropertyNameCaseInsensitive, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.s_missingProperty, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Text.Json.JsonHelpers.Utf8GetString(), and System.value.