Terraria: System.Text.Json.Serialization.Metadata.JsonTypeInfo.GetParameter
GetParameter()
JsonParameterInfo System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.GetParameter (ReadOnlySpan< byte > propertyName, ref ReadStackFrame frame, out byte[] utf8PropertyName) inline package inherited
Definition at line 301 of file JsonTypeInfo.cs.
    {
        ulong key = GetKey(propertyName);
        ParameterRef[] parameterRefsSorted = _parameterRefsSorted;
        if (parameterRefsSorted != null)
        {
            int parameterIndex = frame.CtorArgumentState.ParameterIndex;
            int num = parameterRefsSorted.Length;
            int num2 = Math.Min(parameterIndex, num);
            int num3 = num2 - 1;
            while (true)
            {
                if (num2 < num)
                {
                    ParameterRef parameterRef = parameterRefsSorted[num2];
                    if (IsParameterRefEqual(in parameterRef, propertyName, key))
                    {
                        utf8PropertyName = parameterRef.NameFromJson;
                        return parameterRef.Info;
                    }
                    num2++;
                    if (num3 >= 0)
                    {
                        parameterRef = parameterRefsSorted[num3];
                        if (IsParameterRefEqual(in parameterRef, propertyName, key))
{
                            utf8PropertyName = parameterRef.NameFromJson;
                            return parameterRef.Info;
                        }
                        num3--;
                    }
                }
                else
                {
                    if (num3 < 0)
                    {
                        break;
                    }
                    ParameterRef parameterRef = parameterRefsSorted[num3];
                    if (IsParameterRefEqual(in parameterRef, propertyName, key))
                    {
                        utf8PropertyName = parameterRef.NameFromJson;
                        return parameterRef.Info;
                    }
                    num3--;
                }
            }
        }
        if (ParameterCache.TryGetValue(JsonHelpers.Utf8GetString(propertyName), out var value))
        {
            if (Options.PropertyNameCaseInsensitive)
            {
                if (propertyName.SequenceEqual(value.NameAsUtf8Bytes))
                {
                    utf8PropertyName = value.NameAsUtf8Bytes;
                }
                else
                {
                    utf8PropertyName = propertyName.ToArray();
                }
            }
            else
            {
                utf8PropertyName = value.NameAsUtf8Bytes;
            }
        }
        else
        {
            utf8PropertyName = propertyName.ToArray();
        }
        int num4 = 0;
        if (parameterRefsSorted != null)
        {
            num4 = parameterRefsSorted.Length;
        }
        if (num4 < 32)
        {
            if (frame.CtorArgumentState.ParameterRefCache != null)
            {
                num4 += frame.CtorArgumentState.ParameterRefCache.Count;
            }
            if (num4 < 32)
            {
                if (frame.CtorArgumentState.ParameterRefCache == null)
                {
                    frame.CtorArgumentState.ParameterRefCache = new List<ParameterRef>();
                }
                ParameterRef parameterRef = new ParameterRef(key, value, utf8PropertyName);
                frame.CtorArgumentState.ParameterRefCache.Add(parameterRef);
            }
        }
        return value;
    }
References System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >._parameterRefsSorted, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Text.Json.Dictionary, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.GetKey(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.IsParameterRefEqual(), System.key, System.Math.Min(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.Options, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ParameterCache, System.Text.Json.JsonSerializerOptions.PropertyNameCaseInsensitive, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Text.Json.JsonHelpers.Utf8GetString(), and System.value.