Terraria: System.Text.Json.Serialization.Metadata.JsonTypeInfo.CacheMember
CacheMember() [2/2]
void System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.CacheMember (Type declaringType, Type memberType, MemberInfo memberInfo, bool isVirtual, JsonNumberHandling? typeNumberHandling, ref bool propertyOrderSpecified, ref Dictionary< string, JsonPropertyInfo > ignoredMembers) inline private inherited
Definition at line 658 of file JsonTypeInfo.cs.
    {
        bool flag = memberInfo.GetCustomAttribute(typeof(JsonExtensionDataAttribute)) != null;
        if (flag && DataExtensionProperty != null)
        {
            ThrowHelper.ThrowInvalidOperationException_SerializationDuplicateTypeAttribute(Type, typeof(JsonExtensionDataAttribute));
        }
        JsonPropertyInfo jsonPropertyInfo = AddProperty(memberInfo, memberType, declaringType, isVirtual, typeNumberHandling, Options);
        if (flag)
        {
            ValidateAndAssignDataExtensionProperty(jsonPropertyInfo);
            return;
        }
        CacheMember(jsonPropertyInfo, PropertyCache, ref ignoredMembers);
        propertyOrderSpecified |= jsonPropertyInfo.Order != 0;
    }
References System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.AddProperty(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.CacheMember(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.DataExtensionProperty, System.Text.Json.Dictionary, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.Options, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.PropertyCache, System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializationDuplicateTypeAttribute(), and System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ValidateAndAssignDataExtensionProperty().
Referenced by System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.JsonTypeInfo(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.CacheMember(), and System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.InitializePropCache().