Terraria: System.Net.NTAuthentication.GetOutgoingBlob
GetOutgoingBlob() [5/7]
byte[] System.Net.NTAuthentication.GetOutgoingBlob (byte[] incomingBlob, bool throwOnError, out System::Net::SecurityStatusPal statusCode) inline package
Definition at line 134 of file NTAuthentication.cs.
    {
        byte[] resultBlob = new byte[_tokenSize];
        bool flag = _securityContext == null;
        try
        {
            if (!_isServer)
            {
                statusCode = System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(ref _credentialsHandle, ref _securityContext, _spn, _requestedContextFlags, incomingBlob, _channelBinding, ref resultBlob, ref _contextFlags);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, $"SSPIWrapper.InitializeSecurityContext() returns statusCode:0x{(int)statusCode.ErrorCode:x8} ({statusCode})", "GetOutgoingBlob");
                }
                if (statusCode.ErrorCode == System.Net.SecurityStatusPalErrorCode.CompleteNeeded)
                {
                    statusCode = System.Net.Security.NegotiateStreamPal.CompleteAuthToken(ref _securityContext, resultBlob);
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"SSPIWrapper.CompleteAuthToken() returns statusCode:0x{(int)statusCode.ErrorCode:x8} ({statusCode})", "GetOutgoingBlob");
                    }
                    resultBlob = null;
                }
            }
            else
            {
                statusCode = System.Net.Security.NegotiateStreamPal.AcceptSecurityContext(_credentialsHandle, ref _securityContext, _requestedContextFlags, incomingBlob, _channelBinding, ref resultBlob, ref _contextFlags);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, $"SSPIWrapper.AcceptSecurityContext() returns statusCode:0x{(int)statusCode.ErrorCode:x8} ({statusCode})", "GetOutgoingBlob");
                }
            }
        }
        finally
        {
            if (flag)
            {
                _credentialsHandle?.Dispose();
            }
        }
        if (statusCode.ErrorCode >= System.Net.SecurityStatusPalErrorCode.OutOfMemory)
        {
            CloseContext();
            _isCompleted = true;
            if (throwOnError)
            {
                throw System.Net.Security.NegotiateStreamPal.CreateExceptionFromError(statusCode);
            }
            return null;
        }
        if (flag && _credentialsHandle != null)
        {
            System.Net.Security.SSPIHandleCache.CacheCredential(_credentialsHandle);
        }
        if (statusCode.ErrorCode == System.Net.SecurityStatusPalErrorCode.OK || (_isServer && statusCode.ErrorCode == System.Net.SecurityStatusPalErrorCode.CompleteNeeded))
        {
            _isCompleted = true;
        }
        else if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"need continue statusCode:0x{(int)statusCode.ErrorCode:x8} ({statusCode}) _securityContext:{_securityContext}", "GetOutgoingBlob");
        }
        return resultBlob;
    }
References System.Net.NTAuthentication._channelBinding, System.Net.NTAuthentication._contextFlags, System.Net.NTAuthentication._credentialsHandle, System.Net.NTAuthentication._isCompleted, System.Net.NTAuthentication._isServer, System.Net.NTAuthentication._requestedContextFlags, System.Net.NTAuthentication._securityContext, System.Net.NTAuthentication._spn, System.Net.NTAuthentication._tokenSize, System.Net.Security.NegotiateStreamPal.AcceptSecurityContext(), System.Net.Security.SSPIHandleCache.CacheCredential(), System.Net.NTAuthentication.CloseContext(), System.Net.Security.NegotiateStreamPal.CompleteAuthToken(), System.Net.Security.NegotiateStreamPal.CreateExceptionFromError(), System.Net.NetEventSource.Info(), System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(), and System.Net.NetEventSource.Log.