Terraria: Terraria.GameContent.UI.GameTipsDisplay.GameTip.GameTip
GameTip()
Terraria.GameContent.UI.GameTipsDisplay.GameTip.GameTip (string textKey, double spawnTime) inline
        {
            _textKey = Language.GetText(textKey);
            SpawnTime = spawnTime;
            ScreenAnchorX = 2.5f;
            Duration = 11.5f;
            object obj = Lang.CreateDialogSubstitutionObject();
            _formattedText = _textKey.FormatWith(obj);
            _formattedText = Lang.SupportGlyphs(_formattedText);
        }
References Terraria.GameContent.UI.GameTipsDisplay.GameTip._formattedText, Terraria.GameContent.UI.GameTipsDisplay.GameTip._textKey, Terraria.Lang.CreateDialogSubstitutionObject(), Terraria.GameContent.UI.GameTipsDisplay.GameTip.Duration, Terraria.Localization.LocalizedText.FormatWith(), Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.GameTipsDisplay.GameTip.ScreenAnchorX, Terraria.GameContent.UI.GameTipsDisplay.GameTip.SpawnTime, and Terraria.Lang.SupportGlyphs().