Terraria: IngameOptions.Open
Open()
static void IngameOptions.Open () inline static
     {
         Main.ClosePlayerChat();
         Main.chatText = "";
         Main.playerInventory = false;
         Main.editChest = false;
         Main.npcChatText = "";
         SoundEngine.PlaySound(10);
         Main.ingameOptionsWindow = true;
         category = 0;
         for (int i = 0; i < leftScale.Length; i++)
         {
             leftScale[i] = 0f;
         }
         for (int j = 0; j < rightScale.Length; j++)
         {
             rightScale[j] = 0f;
         }
         leftHover = -1;
         rightHover = -1;
         oldLeftHover = -1;
         oldRightHover = -1;
         rightLock = -1;
         inBar = false;
         notBar = false;
         noSound = false;
     }
References category, Main.chatText, Main.ClosePlayerChat(), Main.editChest, inBar, Main.ingameOptionsWindow, leftHover, leftScale, noSound, notBar, Main.npcChatText, oldLeftHover, oldRightHover, Main.playerInventory, SoundEngine.PlaySound(), rightHover, rightLock, and rightScale.
Referenced by Main.DrawInterface_29_SettingsButton(), and Player.TryOpeningInGameOptionsBasedOnInput().