Terraria: MapHelper.LoadMapVersion2
LoadMapVersion2()
static void MapHelper.LoadMapVersion2 (BinaryReader fileIO, int release) inline static
     {
         //IL_0388: Unknown result type (might be due to invalid IL or missing references)
         //IL_0392: Expected O, but got Unknown
         if (release >= 135)
         {
             Main.MapFileMetadata = FileMetadata.Read(fileIO, FileType.Map);
         }
         else
         {
             Main.MapFileMetadata = FileMetadata.FromCurrentSettings(FileType.Map);
         }
         fileIO.ReadString();
         int num = fileIO.ReadInt32();
         int num2 = fileIO.ReadInt32();
         int num3 = fileIO.ReadInt32();
         if (num != Main.worldID || num3 != Main.maxTilesX || num2 != Main.maxTilesY)
         {
             throw new Exception("Map meta-data is invalid.");
         }
         short num4 = fileIO.ReadInt16();
         short num5 = fileIO.ReadInt16();
         short num6 = fileIO.ReadInt16();
         short num7 = fileIO.ReadInt16();
         short num8 = fileIO.ReadInt16();
         short num9 = fileIO.ReadInt16();
         bool[] array = new bool[num4];
         byte b = 0;
         byte b2 = 128;
         for (int i = 0; i < num4; i++)
         {
             if (b2 == 128)
             {
                 b = fileIO.ReadByte();
                 b2 = 1;
             }
             else
             {
                 b2 <<= 1;
             }
             if ((b & b2) == b2)
             {
                 array[i] = true;
             }
         }
         bool[] array2 = new bool[num5];
         b = 0;
         b2 = 128;
         for (int i = 0; i < num5; i++)
         {
             if (b2 == 128)
             {
                 b = fileIO.ReadByte();
                 b2 = 1;
             }
             else
             {
                 b2 <<= 1;
             }
             if ((b & b2) == b2)
             {
                 array2[i] = true;
             }
         }
         byte[] array3 = new byte[num4];
         ushort num10 = 0;
         for (int i = 0; i < num4; i++)
         {
             if (array[i])
             {
                 array3[i] = fileIO.ReadByte();
             }
             else
             {
                 array3[i] = 1;
             }
             num10 += array3[i];
         }
         byte[] array4 = new byte[num5];
         ushort num11 = 0;
         for (int i = 0; i < num5; i++)
         {
             if (array2[i])
             {
                 array4[i] = fileIO.ReadByte();
             }
             else
             {
                 array4[i] = 1;
             }
             num11 += array4[i];
         }
         ushort[] array5 = new ushort[num10 + num11 + num6 + num7 + num8 + num9 + 2];
         array5[0] = 0;
         ushort num12 = 1;
         ushort num13 = 1;
         ushort num14 = num13;
         for (int i = 0; i < TileID.Count; i++)
         {
             if (i < num4)
             {
                 int num15 = array3[i];
                 int num16 = tileOptionCounts[i];
                 for (int j = 0; j < num16; j++)
                 {
                     if (j < num15)
                     {
                         array5[num13] = num12;
                         num13++;
                     }
                     num12++;
                 }
             }
             else
             {
                 num12 += (ushort)tileOptionCounts[i];
             }
         }
         ushort num17 = num13;
         for (int i = 0; i < WallID.Count; i++)
         {
             if (i < num5)
             {
                 int num18 = array4[i];
                 int num19 = wallOptionCounts[i];
                 for (int k = 0; k < num19; k++)
                 {
                     if (k < num18)
                     {
                         array5[num13] = num12;
                         num13++;
                     }
                     num12++;
                 }
             }
             else
             {
                 num12 += (ushort)wallOptionCounts[i];
             }
         }
         ushort num20 = num13;
         for (int i = 0; i < 4; i++)
         {
             if (i < num6)
             {
                 array5[num13] = num12;
                 num13++;
             }
             num12++;
         }
         ushort num21 = num13;
         for (int i = 0; i < 256; i++)
         {
             if (i < num7)
             {
                 array5[num13] = num12;
                 num13++;
             }
             num12++;
         }
         ushort num22 = num13;
         for (int i = 0; i < 256; i++)
         {
             if (i < num8)
             {
                 array5[num13] = num12;
                 num13++;
             }
             num12++;
         }
         ushort num23 = num13;
         for (int i = 0; i < 256; i++)
         {
             if (i < num9)
             {
                 array5[num13] = num12;
                 num13++;
             }
             num12++;
         }
         ushort num24 = num13;
         array5[num13] = num12;
         BinaryReader binaryReader = ((release < 93) ? new BinaryReader(fileIO.BaseStream) : new BinaryReader((Stream)new DeflateStream(fileIO.BaseStream, (CompressionMode)1)));
         for (int l = 0; l < Main.maxTilesY; l++)
         {
             float num25 = (float)l / (float)Main.maxTilesY;
             Main.statusText = Lang.gen[67].Value + " " + (int)(num25 * 100f + 1f) + "%";
             for (int m = 0; m < Main.maxTilesX; m++)
             {
                 byte b3 = binaryReader.ReadByte();
                 byte b4 = (byte)(((b3 & 1) == 1) ? binaryReader.ReadByte() : 0);
                 if ((b4 & 1) == 1)
                 {
                     binaryReader.ReadByte();
                 }
                 byte b5 = (byte)((b3 & 0xE) >> 1);
                 bool flag;
                 switch (b5)
                 {
                 case 0:
                     flag = false;
                     break;
                 case 1:
                 case 2:
                 case 7:
                     flag = true;
                     break;
                 case 3:
                 case 4:
                 case 5:
                     flag = false;
                     break;
                 case 6:
                     flag = false;
                     break;
                 default:
                     flag = false;
                     break;
                 }
                 ushort num26 = (ushort)(flag ? (((b3 & 0x10) != 16) ? binaryReader.ReadByte() : binaryReader.ReadUInt16()) : 0);
                 byte b6 = (((b3 & 0x20) != 32) ? byte.MaxValue : binaryReader.ReadByte());
                 int num27 = (byte)((b3 & 0xC0) >> 6) switch
                 {
                     0 => 0,
                     1 => binaryReader.ReadByte(),
                     2 => binaryReader.ReadInt16(),
                     _ => 0,
                 };
                 switch (b5)
                 {
                 case 0:
                     m += num27;
                     continue;
                 case 1:
                     num26 += num14;
                     break;
                 case 2:
                     num26 += num17;
                     break;
                 case 3:
                 case 4:
                 case 5:
                 {
                     int num28 = b5 - 3;
                     if ((b4 & 0x40) == 64)
                     {
                         num28 = 3;
                     }
                     num26 += (ushort)(num20 + num28);
                     break;
                 }
                 case 6:
                     if ((double)l < Main.worldSurface)
                     {
                         ushort num29 = (ushort)((double)num7 * ((double)l / Main.worldSurface));
                         num26 += (ushort)(num21 + num29);
                     }
                     else
                     {
                         num26 = num24;
                     }
                     break;
                 case 7:
                     num26 = ((!((double)l < Main.rockLayer)) ? ((ushort)(num26 + num23)) : ((ushort)(num26 + num22)));
                     break;
                 }
                 MapTile tile = MapTile.Create(array5[num26], b6, (byte)((uint)(b4 >> 1) & 0x1Fu));
                 Main.Map.SetTile(m, l, ref tile);
                 if (b6 == byte.MaxValue)
                 {
                     while (num27 > 0)
                     {
                         m++;
                         Main.Map.SetTile(m, l, ref tile);
                         num27--;
                     }
                     continue;
                 }
                 while (num27 > 0)
                 {
                     m++;
                     tile = tile.WithLight(binaryReader.ReadByte());
                     Main.Map.SetTile(m, l, ref tile);
                     num27--;
                 }
             }
         }
         binaryReader.Close();
     }
References TileID.Count, WallID.Count, MapTile.Create(), FileMetadata.FromCurrentSettings(), Lang.gen, Main.Map, Main.MapFileMetadata, Main.maxTilesX, Main.maxTilesY, FileMetadata.Read(), Main.rockLayer, WorldMap.SetTile(), Main.statusText, tileOptionCounts, LocalizedText.Value, wallOptionCounts, MapTile.WithLight(), Main.worldID, and Main.worldSurface.
Referenced by WorldMap.Load().