Terraria: MapHelper.InternalSaveMap
InternalSaveMap()
static void MapHelper.InternalSaveMap () inline static private
     {
         //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
         //IL_00b3: Expected O, but got Unknown
         bool isCloudSave = Main.ActivePlayerFileData.IsCloudSave;
         string text = Main.playerPathName.Substring(0, Main.playerPathName.Length - 4);
         if (!isCloudSave)
         {
             Utils.TryCreatingDirectory(text);
         }
         text += Path.DirectorySeparatorChar;
         text = ((!Main.ActiveWorldFileData.UseGuidAsMapName) ? (text + Main.worldID + ".map") : string.Concat(text, Main.ActiveWorldFileData.UniqueId, ".map"));
         new Stopwatch().Start();
         if (!Main.gameMenu)
         {
             noStatusText = true;
         }
         using (MemoryStream memoryStream = new MemoryStream(4000))
         {
             using BinaryWriter binaryWriter = new BinaryWriter(memoryStream);
             DeflateStream val = new DeflateStream((Stream)memoryStream, (CompressionMode)0);
             try
             {
                 int num = 0;
                 byte[] array = new byte[16384];
                 binaryWriter.Write(279);
                 Main.MapFileMetadata.IncrementAndWrite(binaryWriter);
                 binaryWriter.Write(Main.worldName);
                 binaryWriter.Write(Main.worldID);
                 binaryWriter.Write(Main.maxTilesY);
                 binaryWriter.Write(Main.maxTilesX);
                 binaryWriter.Write((short)TileID.Count);
                 binaryWriter.Write((short)WallID.Count);
                 binaryWriter.Write((short)4);
                 binaryWriter.Write((short)256);
                 binaryWriter.Write((short)256);
                 binaryWriter.Write((short)256);
                 byte b = 1;
                 byte b2 = 0;
                 int i;
                 for (i = 0; i < TileID.Count; i++)
                 {
                     if (tileOptionCounts[i] != 1)
                     {
                         b2 |= b;
                     }
                     if (b == 128)
                     {
                         binaryWriter.Write(b2);
                         b2 = 0;
                         b = 1;
                     }
                     else
                     {
                         b <<= 1;
                     }
                 }
                 if (b != 1)
                 {
                     binaryWriter.Write(b2);
                 }
                 i = 0;
                 b = 1;
                 b2 = 0;
                 for (; i < WallID.Count; i++)
                 {
                     if (wallOptionCounts[i] != 1)
                     {
                         b2 |= b;
                     }
                     if (b == 128)
                     {
                         binaryWriter.Write(b2);
                         b2 = 0;
                         b = 1;
                     }
                     else
                     {
                         b <<= 1;
                     }
                 }
                 if (b != 1)
                 {
                     binaryWriter.Write(b2);
                 }
                 for (i = 0; i < TileID.Count; i++)
                 {
                     if (tileOptionCounts[i] != 1)
                     {
                         binaryWriter.Write((byte)tileOptionCounts[i]);
                     }
                 }
                 for (i = 0; i < WallID.Count; i++)
                 {
                     if (wallOptionCounts[i] != 1)
                     {
                         binaryWriter.Write((byte)wallOptionCounts[i]);
                     }
                 }
                 binaryWriter.Flush();
                 for (int j = 0; j < Main.maxTilesY; j++)
                 {
                     if (!noStatusText)
                     {
                         float num2 = (float)j / (float)Main.maxTilesY;
                         Main.statusText = Lang.gen[66].Value + " " + (int)(num2 * 100f + 1f) + "%";
                     }
                     int num3;
                     for (num3 = 0; num3 < Main.maxTilesX; num3++)
                     {
                         MapTile mapTile = Main.Map[num3, j];
                         byte b4;
                         byte b3;
                         byte b5 = (b4 = (b3 = 0));
                         int num4 = 0;
                         bool flag = true;
                         bool flag2 = true;
                         int num5 = 0;
                         int num6 = 0;
                         byte b6 = 0;
                         int num7;
                         ushort num8;
                         if (mapTile.Light <= 18)
{
                             flag2 = false;
                             flag = false;
                             num7 = 0;
                             num8 = 0;
                             num4 = 0;
                             int num9 = num3 + 1;
                             int num10 = Main.maxTilesX - num3 - 1;
                             while (num10 > 0 && Main.Map[num9, j].Light <= 18)
{
                                 num4++;
                                 num10--;
                                 num9++;
                             }
                         }
                         else
{
                             b6 = mapTile.Color;
                             num8 = mapTile.Type;
                             if (num8 < wallPosition)
{
                                 num7 = 1;
                                 num8 -= tilePosition;
                             }
                             else if (num8 < liquidPosition)
{
                                 num7 = 2;
                                 num8 -= wallPosition;
                             }
                             else if (num8 < skyPosition)
{
                                 int num11 = num8 - liquidPosition;
                                 if (num11 == 3)
{
                                     b4 = (byte)(b4 | 0x40u);
                                     num11 = 0;
                                 }
                                 num7 = 3 + num11;
                                 flag = false;
                             }
                             else if (num8 < dirtPosition)
{
                                 num7 = 6;
                                 flag2 = false;
                                 flag = false;
                             }
                             else if (num8 < hellPosition)
{
                                 num7 = 7;
                                 num8 = ((num8 >= rockPosition) ? ((ushort)(num8 - rockPosition)) : ((ushort)(num8 - dirtPosition)));
                             }
                             else
{
                                 num7 = 6;
                                 flag = false;
                             }
                             if (mapTile.Light == byte.MaxValue)
{
                                 flag2 = false;
                             }
                             if (flag2)
{
                                 num4 = 0;
                                 int num9 = num3 + 1;
                                 int num10 = Main.maxTilesX - num3 - 1;
                                 num5 = num9;
                                 while (num10 > 0)
{
                                     MapTile other = Main.Map[num9, j];
                                     if (mapTile.EqualsWithoutLight(ref other))
{
                                         num10--;
                                         num4++;
                                         num9++;
                                         continue;
                                     }
                                     num6 = num9;
                                     break;
                                 }
                             }
                             else
{
                                 num4 = 0;
                                 int num9 = num3 + 1;
                                 int num10 = Main.maxTilesX - num3 - 1;
                                 while (num10 > 0)
{
                                     MapTile other2 = Main.Map[num9, j];
                                     if (!mapTile.Equals(ref other2))
{
                                         break;
                                     }
                                     num10--;
                                     num4++;
                                     num9++;
                                 }
                             }
                         }
                         if (b6 > 0)
{
                             b4 |= (byte)(b6 << 1);
                         }
                         if (b3 != 0)
{
                             b4 = (byte)(b4 | 1u);
                         }
                         if (b4 != 0)
{
                             b5 = (byte)(b5 | 1u);
                         }
                         b5 |= (byte)(num7 << 1);
                         if (flag && num8 > 255)
{
                             b5 = (byte)(b5 | 0x10u);
                         }
                         if (flag2)
{
                             b5 = (byte)(b5 | 0x20u);
                         }
                         if (num4 > 0)
{
                             b5 = ((num4 <= 255) ? ((byte)(b5 | 0x40u)) : ((byte)(b5 | 0x80u)));
                         }
                         array[num] = b5;
                         num++;
                         if (b4 != 0)
{
                             array[num] = b4;
                             num++;
                         }
                         if (b3 != 0)
{
                             array[num] = b3;
                             num++;
                         }
                         if (flag)
{
                             array[num] = (byte)num8;
                             num++;
                             if (num8 > 255)
{
                                 array[num] = (byte)(num8 >> 8);
                                 num++;
                             }
                         }
                         if (flag2)
{
                             array[num] = mapTile.Light;
                             num++;
                         }
                         if (num4 > 0)
{
                             array[num] = (byte)num4;
                             num++;
                             if (num4 > 255)
{
                                 array[num] = (byte)(num4 >> 8);
                                 num++;
                             }
                         }
                         for (int k = num5; k < num6; k++)
{
                             array[num] = Main.Map[k, j].Light;
                             num++;
                         }
                         num3 += num4;
                         if (num >= 4096)
{
                             ((Stream)(object)val).Write(array, 0, num);
                             num = 0;
                         }
                     }
                 }
                 if (num > 0)
                 {
                     ((Stream)(object)val).Write(array, 0, num);
                 }
                 ((Stream)(object)val).Dispose();
                 FileUtilities.WriteAllBytes(text, memoryStream.ToArray(), isCloudSave);
             }
             finally
             {
                 ((IDisposable)val)?.Dispose();
             }
         }
         noStatusText = false;
     }
References Main.ActivePlayerFileData, Main.ActiveWorldFileData, MapTile.Color, TileID.Count, WallID.Count, dirtPosition, MapTile.Equals(), MapTile.EqualsWithoutLight(), Main.gameMenu, Lang.gen, hellPosition, FileMetadata.IncrementAndWrite(), FileData.IsCloudSave, MapTile.Light, liquidPosition, Main.Map, Main.MapFileMetadata, Main.maxTilesX, Main.maxTilesY, noStatusText, Main.playerPathName, rockPosition, skyPosition, Main.statusText, tileOptionCounts, tilePosition, Utils.TryCreatingDirectory(), MapTile.Type, WorldFileData.UniqueId, WorldFileData.UseGuidAsMapName, LocalizedText.Value, wallOptionCounts, wallPosition, Main.worldID, Main.worldName, and FileUtilities.WriteAllBytes().
Referenced by SaveMap().