Terraria: MapHelper.LoadMapVersion1
LoadMapVersion1()
static void MapHelper.LoadMapVersion1 (BinaryReader fileIO, int release) inline static
     {
         string text = fileIO.ReadString();
         int num = fileIO.ReadInt32();
         int num2 = fileIO.ReadInt32();
         int num3 = fileIO.ReadInt32();
         if (text != Main.worldName || num != Main.worldID || num3 != Main.maxTilesX || num2 != Main.maxTilesY)
         {
             throw new Exception("Map meta-data is invalid.");
         }
         OldMapHelper oldMapHelper = default(OldMapHelper);
         for (int i = 0; i < Main.maxTilesX; i++)
         {
             float num4 = (float)i / (float)Main.maxTilesX;
             Main.statusText = Lang.gen[67].Value + " " + (int)(num4 * 100f + 1f) + "%";
             for (int j = 0; j < Main.maxTilesY; j++)
             {
                 if (fileIO.ReadBoolean())
                 {
                     int num5 = ((release <= 77) ? fileIO.ReadByte() : fileIO.ReadUInt16());
                     byte b = fileIO.ReadByte();
                     oldMapHelper.misc = fileIO.ReadByte();
                     if (release >= 50)
                     {
                         oldMapHelper.misc2 = fileIO.ReadByte();
                     }
                     else
                     {
                         oldMapHelper.misc2 = 0;
                     }
                     bool flag = false;
                     int num6 = oldMapHelper.option();
                     int num7;
                     if (oldMapHelper.active())
                     {
                         num7 = num6 + tileLookup[num5];
                     }
                     else if (oldMapHelper.water())
                     {
                         num7 = liquidPosition;
                     }
                     else if (oldMapHelper.lava())
                     {
                         num7 = liquidPosition + 1;
                     }
                     else if (oldMapHelper.honey())
                     {
                         num7 = liquidPosition + 2;
                     }
                     else if (oldMapHelper.wall())
                     {
                         num7 = num6 + wallLookup[num5];
                     }
                     else if ((double)j < Main.worldSurface)
                     {
                         flag = true;
                         int num8 = (byte)(256.0 * ((double)j / Main.worldSurface));
                         num7 = skyPosition + num8;
                     }
                     else if ((double)j < Main.rockLayer)
                     {
                         flag = true;
                         if (num5 > 255)
{
                             num5 = 255;
                         }
                         num7 = num5 + dirtPosition;
                     }
                     else if (j < Main.UnderworldLayer)
                     {
                         flag = true;
                         if (num5 > 255)
{
                             num5 = 255;
                         }
                         num7 = num5 + rockPosition;
                     }
                     else
                     {
                         num7 = hellPosition;
                     }
                     MapTile tile = MapTile.Create((ushort)num7, b, 0);
                     Main.Map.SetTile(i, j, ref tile);
                     int num9 = fileIO.ReadInt16();
                     if (b == byte.MaxValue)
                     {
                         while (num9 > 0)
{
                             num9--;
                             j++;
                             if (flag)
{
                                 if ((double)j < Main.worldSurface)
{
                                     flag = true;
                                     int num10 = (byte)(256.0 * ((double)j / Main.worldSurface));
                                     num7 = skyPosition + num10;
                                 }
                                 else if ((double)j < Main.rockLayer)
{
                                     flag = true;
                                     num7 = num5 + dirtPosition;
                                 }
                                 else if (j < Main.UnderworldLayer)
{
                                     flag = true;
                                     num7 = num5 + rockPosition;
                                 }
                                 else
{
                                     flag = true;
                                     num7 = hellPosition;
                                 }
                                 tile.Type = (ushort)num7;
                             }
                             Main.Map.SetTile(i, j, ref tile);
                         }
                         continue;
                     }
                     while (num9 > 0)
                     {
                         j++;
                         num9--;
                         b = fileIO.ReadByte();
                         if (b <= 18)
{
                             continue;
                         }
                         tile.Light = b;
                         if (flag)
{
                             if ((double)j < Main.worldSurface)
{
                                 flag = true;
                                 int num11 = (byte)(256.0 * ((double)j / Main.worldSurface));
                                 num7 = skyPosition + num11;
                             }
                             else if ((double)j < Main.rockLayer)
{
                                 flag = true;
                                 num7 = num5 + dirtPosition;
                             }
                             else if (j < Main.UnderworldLayer)
{
                                 flag = true;
                                 num7 = num5 + rockPosition;
                             }
                             else
{
                                 flag = true;
                                 num7 = hellPosition;
                             }
                             tile.Type = (ushort)num7;
                         }
                         Main.Map.SetTile(i, j, ref tile);
                     }
                 }
                 else
                 {
                     int num12 = fileIO.ReadInt16();
                     j += num12;
                 }
             }
         }
     }
References MapHelper.OldMapHelper.active(), MapTile.Create(), dirtPosition, Lang.gen, hellPosition, MapHelper.OldMapHelper.honey(), MapHelper.OldMapHelper.lava(), MapTile.Light, liquidPosition, Main.Map, Main.maxTilesX, Main.maxTilesY, MapHelper.OldMapHelper.misc, MapHelper.OldMapHelper.misc2, MapHelper.OldMapHelper.option(), Main.rockLayer, rockPosition, WorldMap.SetTile(), skyPosition, Main.statusText, tileLookup, MapTile.Type, Main.UnderworldLayer, LocalizedText.Value, MapHelper.OldMapHelper.wall(), wallLookup, MapHelper.OldMapHelper.water(), Main.worldID, Main.worldName, and Main.worldSurface.
Referenced by WorldMap.Load().