Terraria: Microsoft.Xna.Framework.Graphics.DeclarationManager.SetVertexDeclaration
SetVertexDeclaration() [2/2]
unsafe void Microsoft.Xna.Framework.Graphics.DeclarationManager.SetVertexDeclaration (VertexDeclaration declaration) inline package
Definition at line 183 of file DeclarationManager.cs.
    {
        int num = (int)stackalloc byte[_003CModule_003E.__CxxQueryExceptionSize()];
        bool lockTaken = false;
        try
        {
            Monitor.Enter(this, ref lockTaken);
            if (currentDeclarationCount != 1 || declaration._binding != currentDeclarations[0])
            {
                if (declaration._binding == null || declaration.GraphicsDevice != device)
                {
                    declaration.Bind(device);
                }
                currentDeclarations[0] = declaration._binding;
                for (int i = 1; i < currentDeclarationCount; i++)
                {
                    currentDeclarations[i] = null;
                }
                currentDeclarationCount = 1;
                SetNativeDeclaration();
            }
        }
        catch when (((Func<bool>)delegate
        {
            // Could not convert BlockContainer to single expression
            uint exceptionCode = (uint)Marshal.GetExceptionCode();
            return (byte)_003CModule_003E.__CxxExceptionFilter((void*)Marshal.GetExceptionPointers(), null, 0, null) != 0;
        }).Invoke())
        {
            uint num2 = 0u;
            _003CModule_003E.__CxxRegisterExceptionObject((void*)Marshal.GetExceptionPointers(), (void*)num);
            try
            {
                try
                {
                    ClearCurrent();
                    _003CModule_003E._CxxThrowException(null, null);
                    return;
                }
                catch when (((Func<bool>)delegate
                {
                    // Could not convert BlockContainer to single expression
                    num2 = (uint)_003CModule_003E.__CxxDetectRethrow((void*)Marshal.GetExceptionPointers());
                    return (byte)num2 != 0;
                }).Invoke())
                {
                }
                if (num2 != 0)
                {
                    throw;
                }
            }
            finally
            {
                _003CModule_003E.__CxxUnregisterExceptionObject((void*)num, (int)num2);
            }
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(this);
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.DeclarationManager.ClearCurrent(), Microsoft.Xna.Framework.Graphics.DeclarationManager.currentDeclarationCount, Microsoft.Xna.Framework.Graphics.DeclarationManager.currentDeclarations, Microsoft.Xna.Framework.Graphics.DeclarationManager.device, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Runtime.InteropServices.Marshal.GetExceptionCode(), System.Runtime.InteropServices.Marshal.GetExceptionPointers(), and Microsoft.Xna.Framework.Graphics.DeclarationManager.SetNativeDeclaration().