Terraria: System.Xml.Xsl.Runtime.XmlCachedSequenceWriter.EndTree
EndTree()
override void System.Xml.Xsl.Runtime.XmlCachedSequenceWriter.EndTree () inline
Definition at line 28 of file XmlCachedSequenceWriter.cs.
    {
        _writer.Close();
        _seqTyped.Add(_doc.CreateNavigator());
    }
References System.Xml.Xsl.Runtime.XmlCachedSequenceWriter._doc, System.Xml.Xsl.Runtime.XmlCachedSequenceWriter._seqTyped, System.Xml.Xsl.Runtime.XmlCachedSequenceWriter._writer, System.Xml.Xsl.Runtime.XmlQuerySequence< T >.Add(), System.Xml.XmlRawWriter.Close(), and System.Xml.XPath.XPathDocument.CreateNavigator().