Terraria: Microsoft.Xna.Framework.Graphics.DeclarationManager.ReleaseAllDeclarations
ReleaseAllDeclarations()
void Microsoft.Xna.Framework.Graphics.DeclarationManager.ReleaseAllDeclarations () inline package
Definition at line 29 of file DeclarationManager.cs.
    {
        bool lockTaken = false;
        try
        {
            Monitor.Enter(this, ref lockTaken);
            ClearCurrent();
            Dictionary<VertexElement[], DeclarationBinding>.ValueCollection.Enumerator enumerator = bindings.Values.GetEnumerator();
            while (enumerator.MoveNext())
            {
                DeclarationBinding current = enumerator.Current;
                current.root.RecursiveRelease();
                current.indirectOffspring.Clear();
            }
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(this);
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.DeclarationManager.bindings, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Microsoft.Xna.Framework.Graphics.DeclarationManager.ClearCurrent(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.GetEnumerator(), Microsoft.Xna.Framework.Graphics.DeclarationBinding.indirectOffspring, Microsoft.Xna.Framework.Graphics.DeclarationBinding.BindingNode.RecursiveRelease(), Microsoft.Xna.Framework.Graphics.DeclarationBinding.root, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice._0021GraphicsDevice(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset().