Terraria: Microsoft.Xna.Framework.Graphics.DeclarationManager.SetNativeDeclaration
SetNativeDeclaration()
unsafe void Microsoft.Xna.Framework.Graphics.DeclarationManager.SetNativeDeclaration () inline private
Definition at line 264 of file DeclarationManager.cs.
    {
        DeclarationBinding.BindingNode bindingNode = currentDeclarations[0].root;
        int num = 1;
        if (1 < currentDeclarationCount)
        {
            do
            {
                DeclarationBinding.BindingNode bindingNode2 = bindingNode.GetChild(currentDeclarations[num]);
                if (bindingNode2 == null)
                {
                    bindingNode2 = new DeclarationBinding.BindingNode();
                    bindingNode.AddChild(currentDeclarations[num], bindingNode2);
                    currentDeclarations[num].indirectOffspring.Add(bindingNode, value: true);
                }
                bindingNode = bindingNode2;
                num++;
            }
            while (num < currentDeclarationCount);
        }
        if (bindingNode.pDecl == null)
        {
            CreateNativeDeclaration(bindingNode);
        }
        int num2 = _003CModule_003E.Microsoft_002EXna_002EFramework_002EGraphics_002EStateTrackerDevice_002ESetVertexDeclaration(device.pStateTracker, bindingNode.pDecl, bindingNode.pSemantics);
        if (num2 < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num2);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Microsoft.Xna.Framework.Graphics.DeclarationManager.CreateNativeDeclaration(), Microsoft.Xna.Framework.Graphics.DeclarationManager.currentDeclarationCount, Microsoft.Xna.Framework.Graphics.DeclarationManager.currentDeclarations, Microsoft.Xna.Framework.Graphics.DeclarationManager.device, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.DeclarationBinding.indirectOffspring, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pStateTracker, Microsoft.Xna.Framework.Graphics.DeclarationBinding.root, and System.value.
Referenced by Microsoft.Xna.Framework.Graphics.DeclarationManager.SetVertexDeclaration(), and Microsoft.Xna.Framework.Graphics.DeclarationManager.SetVertexDeclaration().