Terraria: Microsoft.Xna.Framework.Graphics.DeclarationManager.CreateNativeDeclaration
CreateNativeDeclaration()
unsafe void Microsoft.Xna.Framework.Graphics.DeclarationManager.CreateNativeDeclaration (DeclarationBinding::BindingNode node) inline private
Definition at line 295 of file DeclarationManager.cs.
    {
        int num = 0;
        int num2 = 0;
        int num3 = currentDeclarationCount;
        if (0 < num3)
        {
            DeclarationBinding[] array = currentDeclarations;
            do
            {
                num = (int)((nint)array[num2].elements.LongLength + num);
                num2++;
            }
            while (num2 < num3);
        }
        int maxVertexStreams = device._profileCapabilities.MaxVertexStreams;
        if (num > maxVertexStreams)
        {
            device._profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileMaxVertexElements, maxVertexStreams);
        }
        int num4 = num + 1;
        _D3DVERTEXELEMENT9* ptr = (_D3DVERTEXELEMENT9*)_003CModule_003E.new_005B_005D(((uint)num4 > 536870911u) ? uint.MaxValue : ((uint)(num4 << 3)), (nothrow_t*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref _003CModule_003E.std_002Enothrow));
        if (ptr == null)
        {
            throw new OutOfMemoryException();
        }
        try
        {
            int num5 = 0;
            for (int i = 0; i < currentDeclarationCount; i++)
            {
                VertexElement[] elements = currentDeclarations[i].elements;
                for (int j = 0; j < (nint)elements.LongLength; j++)
                {
                    _D3DVERTEXELEMENT9* ptr2 = (_D3DVERTEXELEMENT9*)(num5 * 8 + (byte*)ptr);
                    *(short*)ptr2 = (short)i;
                    *(short*)((byte*)ptr2 + 2) = (short)elements[j].Offset;
                    ((byte*)ptr2)[4] = _003CModule_003E.ConvertXnaVertexElementFormatToDx(elements[j].VertexElementFormat);
                    ((byte*)ptr2)[5] = 0;
                    ((byte*)ptr2)[6] = _003CModule_003E.ConvertXnaVertexElementUsageToDx(elements[j].VertexElementUsage);
                    ((byte*)ptr2)[7] = (byte)elements[j].UsageIndex;
                    while (IsDuplicateElement(ptr, num5))
                    {
                        byte b = (byte)(((byte*)ptr2)[7] + 1);
                        ((byte*)ptr2)[7] = b;
                        if (b >= device._profileCapabilities.MaxVertexStreams)
{
                            throw new ArgumentException(string.Format(args: new object[2]
{
                                elements[j].VertexElementUsage,
                                elements[j].UsageIndex
                            }, provider: CultureInfo.CurrentCulture, format: FrameworkResources.DuplicateVertexElement));
                        }
                    }
                    num5++;
                }
            }
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DVERTEXELEMENT9 d3DVERTEXELEMENT);
            *(short*)(&d3DVERTEXELEMENT) = 255;
            System.Runtime.CompilerServices.Unsafe.As<_D3DVERTEXELEMENT9, short>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVERTEXELEMENT, 2)) = 0;
            System.Runtime.CompilerServices.Unsafe.As<_D3DVERTEXELEMENT9, sbyte>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVERTEXELEMENT, 4)) = 17;
            System.Runtime.CompilerServices.Unsafe.As<_D3DVERTEXELEMENT9, sbyte>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVERTEXELEMENT, 5)) = 0;
            System.Runtime.CompilerServices.Unsafe.As<_D3DVERTEXELEMENT9, sbyte>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVERTEXELEMENT, 6)) = 0;
            System.Runtime.CompilerServices.Unsafe.As<_D3DVERTEXELEMENT9, sbyte>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVERTEXELEMENT, 7)) = 0;
            // IL cpblk instruction
            System.Runtime.CompilerServices.Unsafe.CopyBlockUnaligned(num5 * 8 + (byte*)ptr, ref d3DVERTEXELEMENT, 8);
            IDirect3DVertexDeclaration9* ptr3 = null;
            IDirect3DDevice9* pComPtr = device.pComPtr;
            int num6 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DVERTEXELEMENT9*, IDirect3DVertexDeclaration9**, int>)(int)(*(uint*)(*(int*)pComPtr + 344)))((nint)pComPtr, ptr, &ptr3);
            if (num6 < 0)
            {
                throw GraphicsHelpers.GetExceptionFromResult((uint)num6);
            }
            VertexShaderInputSemantics* ptr4 = (VertexShaderInputSemantics*)_003CModule_003E.@new(32u, (nothrow_t*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref _003CModule_003E.std_002Enothrow));
            VertexShaderInputSemantics* ptr5;
            try
            {
                ptr5 = ((ptr4 == null) ? null : _003CModule_003E.Microsoft_002EXna_002EFramework_002EGraphics_002EVertexShaderInputSemantics_002E_007Bctor_007D(ptr4, ptr, (uint)num));
                VertexShaderInputSemantics* ptr6 = ptr5;
            }
            catch
            {
                //try-fault
                _003CModule_003E.delete(ptr4, (nothrow_t*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref _003CModule_003E.std_002Enothrow));
                throw;
            }
            node.pSemantics = ptr5;
            if (ptr5 == null)
            {
                IDirect3DVertexDeclaration9* intPtr = ptr3;
                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)intPtr + 8)))((nint)intPtr);
                throw new OutOfMemoryException();
            }
            node.pDecl = ptr3;
        }
        finally
        {
            _003CModule_003E.delete_005B_005D(ptr);
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, System.array, System.Runtime.CompilerServices.Unsafe.CopyBlockUnaligned(), System.Globalization.CultureInfo.CurrentCulture, Microsoft.Xna.Framework.Graphics.DeclarationManager.currentDeclarationCount, Microsoft.Xna.Framework.Graphics.DeclarationManager.currentDeclarations, Microsoft.Xna.Framework.Graphics.DeclarationManager.device, Microsoft.Xna.Framework.FrameworkResources.DuplicateVertexElement, Microsoft.Xna.Framework.Graphics.DeclarationBinding.elements, System.Globalization.Format, System.format, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.DeclarationManager.IsDuplicateElement(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxVertexStreams, Microsoft.Xna.Framework.Graphics.VertexElement.Offset, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileMaxVertexElements, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), Microsoft.Xna.Framework.Graphics.VertexElement.UsageIndex, and Microsoft.Xna.Framework.Graphics.VertexElement.VertexElementUsage.
Referenced by Microsoft.Xna.Framework.Graphics.DeclarationManager.SetNativeDeclaration().