Terraria: Microsoft.Xna.Framework.Graphics.DeclarationManager.ReleaseBinding
ReleaseBinding()
void Microsoft.Xna.Framework.Graphics.DeclarationManager.ReleaseBinding (DeclarationBinding binding) inline package
Definition at line 79 of file DeclarationManager.cs.
    {
        bool lockTaken = false;
        try
        {
            Monitor.Enter(this, ref lockTaken);
            if (--binding.referenceCount <= 0)
            {
                binding.root.RecursiveRelease();
                List<DeclarationBinding.BindingNode>.Enumerator enumerator = new List<DeclarationBinding.BindingNode>(binding.indirectOffspring.Keys).GetEnumerator();
                while (enumerator.MoveNext())
                {
                    enumerator.Current.RemoveChild(binding);
                }
                bindings.Remove(binding.elements);
            }
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(this);
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.DeclarationManager.bindings, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Collections.Generic.Dictionary< TKey, TValue >.Keys, and System.Collections.Generic.Dictionary< TKey, TValue >.Remove().
Referenced by Microsoft.Xna.Framework.Graphics.VertexDeclaration.Bind(), and Microsoft.Xna.Framework.Graphics.VertexDeclaration.Unbind().