Terraria: Microsoft.Xna.Framework.Graphics.DeclarationManager.SetVertexDeclaration
SetVertexDeclaration() [1/2]
unsafe void Microsoft.Xna.Framework.Graphics.DeclarationManager.SetVertexDeclaration (VertexBufferBinding * vertexBuffers, int count) inline package
Definition at line 105 of file DeclarationManager.cs.
    {
        int num = (int)stackalloc byte[_003CModule_003E.__CxxQueryExceptionSize()];
        bool lockTaken = false;
        try
        {
            Monitor.Enter(this, ref lockTaken);
            bool flag = false;
            for (int i = 0; i < count; i++)
            {
                VertexDeclaration vertexDeclaration = ((VertexBufferBinding*)(System.Runtime.CompilerServices.Unsafe.SizeOf<VertexBufferBinding>() * i + (byte*)vertexBuffers))->_vertexBuffer._vertexDeclaration;
                DeclarationBinding binding = vertexDeclaration._binding;
                if (binding != currentDeclarations[i])
                {
                    if (binding == null || vertexDeclaration.GraphicsDevice != device)
                    {
                        vertexDeclaration.Bind(device);
                        binding = vertexDeclaration._binding;
                    }
                    currentDeclarations[i] = binding;
                    flag = true;
                }
            }
            for (int j = count; j < currentDeclarationCount; j++)
            {
                currentDeclarations[j] = null;
                flag = true;
            }
            currentDeclarationCount = count;
            if (flag)
            {
                SetNativeDeclaration();
            }
        }
        catch when (((Func<bool>)delegate
        {
            // Could not convert BlockContainer to single expression
            uint exceptionCode = (uint)Marshal.GetExceptionCode();
            return (byte)_003CModule_003E.__CxxExceptionFilter((void*)Marshal.GetExceptionPointers(), null, 0, null) != 0;
        }).Invoke())
        {
            uint num2 = 0u;
            _003CModule_003E.__CxxRegisterExceptionObject((void*)Marshal.GetExceptionPointers(), (void*)num);
            try
            {
                try
                {
                    ClearCurrent();
                    _003CModule_003E._CxxThrowException(null, null);
                    return;
                }
                catch when (((Func<bool>)delegate
                {
                    // Could not convert BlockContainer to single expression
                    num2 = (uint)_003CModule_003E.__CxxDetectRethrow((void*)Marshal.GetExceptionPointers());
                    return (byte)num2 != 0;
                }).Invoke())
                {
                }
                if (num2 != 0)
                {
                    throw;
                }
            }
            finally
            {
                _003CModule_003E.__CxxUnregisterExceptionObject((void*)num, (int)num2);
            }
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(this);
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.DeclarationManager.ClearCurrent(), System.count, Microsoft.Xna.Framework.Graphics.DeclarationManager.currentDeclarationCount, Microsoft.Xna.Framework.Graphics.DeclarationManager.currentDeclarations, Microsoft.Xna.Framework.Graphics.DeclarationManager.device, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Runtime.InteropServices.Marshal.GetExceptionCode(), System.Runtime.InteropServices.Marshal.GetExceptionPointers(), and Microsoft.Xna.Framework.Graphics.DeclarationManager.SetNativeDeclaration().
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.BeginUserPrimitives(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers().