Terraria: System.Xml.DocumentXPathNodeIterator_ElemDescendants.MoveNext
MoveNext()
override bool System.Xml.DocumentXPathNodeIterator_ElemDescendants.MoveNext () inline
Definition at line 38 of file DocumentXPathNodeIterator_ElemDescendants.cs.
    {
        XmlNode xmlNode;
        do
        {
            if (_nav.MoveToFirstChild())
            {
                _level++;
            }
            else
            {
                if (_level == 0)
                {
                    return false;
                }
                while (!_nav.MoveToNext())
                {
                    _level--;
                    if (_level == 0)
                    {
                        return false;
                    }
                    if (!_nav.MoveToParent())
                    {
                        return false;
                    }
                }
            }
            xmlNode = (XmlNode)_nav.UnderlyingObject;
        }
        while (xmlNode.NodeType != XmlNodeType.Element || !Match(xmlNode));
        _position++;
        return true;
    }
References System.Xml.DocumentXPathNodeIterator_ElemDescendants._level, System.Xml.DocumentXPathNodeIterator_ElemDescendants._nav, System.Xml.DocumentXPathNodeIterator_ElemDescendants._position, System.Xml.Dictionary, System.Xml.DocumentXPathNodeIterator_ElemDescendants.Match(), System.Xml.DocumentXPathNavigator.MoveToFirstChild(), System.Xml.DocumentXPathNavigator.MoveToNext(), System.Xml.DocumentXPathNavigator.MoveToParent(), and System.Xml.DocumentXPathNavigator.UnderlyingObject.