Terraria: System.Linq.Expressions.ParameterExpression.Make
Make()
static ParameterExpression System.Linq.Expressions.ParameterExpression.Make (Type type, string name, bool isByRef) inline static package inherited
Definition at line 22 of file ParameterExpression.cs.
    {
        if (isByRef)
        {
            return new ByRefParameterExpression(type, name);
        }
        if (!type.IsEnum)
        {
            switch (type.GetTypeCode())
            {
            case TypeCode.Boolean:
                return new PrimitiveParameterExpression<bool>(name);
            case TypeCode.Byte:
                return new PrimitiveParameterExpression<byte>(name);
            case TypeCode.Char:
                return new PrimitiveParameterExpression<char>(name);
            case TypeCode.DateTime:
                return new PrimitiveParameterExpression<DateTime>(name);
            case TypeCode.Decimal:
                return new PrimitiveParameterExpression<decimal>(name);
            case TypeCode.Double:
                return new PrimitiveParameterExpression<double>(name);
            case TypeCode.Int16:
                return new PrimitiveParameterExpression<short>(name);
            case TypeCode.Int32:
                return new PrimitiveParameterExpression<int>(name);
            case TypeCode.Int64:
                return new PrimitiveParameterExpression<long>(name);
            case TypeCode.Object:
                if (type == typeof(object))
                {
                    return new ParameterExpression(name);
                }
                if (type == typeof(Exception))
                {
                    return new PrimitiveParameterExpression<Exception>(name);
                }
                if (type == typeof(object[]))
                {
                    return new PrimitiveParameterExpression<object[]>(name);
                }
                break;
            case TypeCode.SByte:
                return new PrimitiveParameterExpression<sbyte>(name);
            case TypeCode.Single:
                return new PrimitiveParameterExpression<float>(name);
            case TypeCode.String:
                return new PrimitiveParameterExpression<string>(name);
            case TypeCode.UInt16:
                return new PrimitiveParameterExpression<ushort>(name);
            case TypeCode.UInt32:
                return new PrimitiveParameterExpression<uint>(name);
            case TypeCode.UInt64:
                return new PrimitiveParameterExpression<ulong>(name);
            }
        }
        return new TypedParameterExpression(type, name);
    }
References System.Linq.Expressions.ParameterExpression.ParameterExpression(), and System.type.
Referenced by System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Linq.Expressions.Compiler.StackSpiller.TempMaker.Temp(), and System.Linq.Expressions.Expression< TDelegate >.Variable().