Terraria: Terraria.GameContent.UI.Elements.UIHairStyleButton.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIHairStyleButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 41 of file UIHairStyleButton.cs.
    {
        if (_hovered)
        {
            if (!_soundedHover)
            {
                SoundEngine.PlaySound(12);
            }
            _soundedHover = true;
        }
        else
        {
            _soundedHover = false;
        }
        Vector2 vector = new Vector2(-5f, -5f);
        base.DrawSelf(spriteBatch);
        if (_player.hair == HairStyleId)
        {
            spriteBatch.Draw(_selectedBorderTexture.Value, GetDimensions().Center() - _selectedBorderTexture.Size() / 2f, Color.White);
        }
        if (_hovered)
        {
            spriteBatch.Draw(_hoveredBorderTexture.Value, GetDimensions().Center() - _hoveredBorderTexture.Size() / 2f, Color.White);
        }
        if (_framesToSkip > 0)
        {
            _framesToSkip--;
            return;
        }
        int hair = _player.hair;
        _player.hair = HairStyleId;
        Main.PlayerRenderer.DrawPlayerHead(Main.Camera, _player, GetDimensions().Center() + vector);
        _player.hair = hair;
    }
References Terraria.GameContent.UI.Elements.UIHairStyleButton._framesToSkip, Terraria.GameContent.UI.Elements.UIHairStyleButton._hovered, Terraria.GameContent.UI.Elements.UIHairStyleButton._hoveredBorderTexture, Terraria.GameContent.UI.Elements.UIHairStyleButton._player, Terraria.GameContent.UI.Elements.UIHairStyleButton._selectedBorderTexture, Terraria.GameContent.UI.Elements.UIHairStyleButton._soundedHover, Terraria.Main.Camera, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.UI.UIElement.GetDimensions(), Terraria.Player.hair, Terraria.GameContent.UI.Elements.UIHairStyleButton.HairStyleId, Terraria.Main.PlayerRenderer, Terraria.Audio.SoundEngine.PlaySound(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.