Terraria: System.Text.Latin1Utility.NarrowUtf16ToLatin1_Sse2
NarrowUtf16ToLatin1_Sse2()
static unsafe nuint System.Text.Latin1Utility.NarrowUtf16ToLatin1_Sse2 (char * pUtf16Buffer, byte * pLatin1Buffer, nuint elementCount) inline static private
Definition at line 397 of file Latin1Utility.cs.
    {
        uint num = (uint)Unsafe.SizeOf<Vector128<byte>>();
        nuint num2 = num - 1;
        Vector128<short> right = Vector128.Create((short)(-256));
        Vector128<ushort> right2 = Vector128.Create((ushort)32512);
        Vector128<short> vector = Sse2.LoadVector128((short*)pUtf16Buffer);
        if (Sse41.IsSupported)
        {
            if (!Sse41.TestZ(vector, right))
            {
                return 0u;
            }
        }
        else if (((uint)Sse2.MoveMask(Sse2.AddSaturate(vector.AsUInt16(), right2).AsByte()) & 0xAAAAu) != 0)
        {
            return 0u;
        }
        Vector128<byte> vector2 = Sse2.PackUnsignedSaturate(vector, vector);
        Sse2.StoreScalar((ulong*)pLatin1Buffer, vector2.AsUInt64());
        nuint num3 = num / 2;
        if (((uint)(int)pLatin1Buffer & (num / 2)) != 0)
        {
            goto IL_00ea;
        }
        vector = Sse2.LoadVector128((short*)(pUtf16Buffer + num3));
        if (Sse41.IsSupported)
        {
            if (Sse41.TestZ(vector, right))
            {
                goto IL_00cd;
            }
        }
        else if ((Sse2.MoveMask(Sse2.AddSaturate(vector.AsUInt16(), right2).AsByte()) & 0xAAAA) == 0)
        {
            goto IL_00cd;
        }
        goto IL_0186;
        IL_0186:
        return num3;
        IL_00cd:
        vector2 = Sse2.PackUnsignedSaturate(vector, vector);
        Sse2.StoreScalar((ulong*)(pLatin1Buffer + num3), vector2.AsUInt64());
        goto IL_00ea;
        IL_00ea:
        num3 = num - ((nuint)pLatin1Buffer & num2);
        nuint num4 = elementCount - num;
        do
        {
            vector = Sse2.LoadVector128((short*)(pUtf16Buffer + num3));
            Vector128<short> right3 = Sse2.LoadVector128((short*)(pUtf16Buffer + num3 + num / 2));
            Vector128<short> vector3 = Sse2.Or(vector, right3);
            if (Sse41.IsSupported)
            {
                if (Sse41.TestZ(vector3, right))
                {
                    goto IL_015e;
                }
            }
            else if ((Sse2.MoveMask(Sse2.AddSaturate(vector3.AsUInt16(), right2).AsByte()) & 0xAAAA) == 0)
            {
                goto IL_015e;
            }
            if (Sse41.IsSupported)
            {
                if (!Sse41.TestZ(vector, right))
                {
                    break;
                }
            }
            else if (((uint)Sse2.MoveMask(Sse2.AddSaturate(vector.AsUInt16(), right2).AsByte()) & 0xAAAAu) != 0)
            {
                break;
            }
            vector2 = Sse2.PackUnsignedSaturate(vector, vector);
            Sse2.StoreScalar((ulong*)(pLatin1Buffer + num3), vector2.AsUInt64());
            num3 += num / 2;
            break;
            IL_015e:
            vector2 = Sse2.PackUnsignedSaturate(vector, right3);
            Sse2.StoreAligned(pLatin1Buffer + num3, vector2);
            num3 += num;
        }
        while (num3 <= num4);
        goto IL_0186;
    }
References System.Runtime.Intrinsics.X86.Sse2.AddSaturate(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.X86.Sse41.IsSupported, System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse2.PackUnsignedSaturate(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Runtime.Intrinsics.X86.Sse2.StoreScalar(), and System.Runtime.Intrinsics.X86.Sse41.TestZ().
Referenced by System.Text.Latin1Utility.NarrowUtf16ToLatin1().