Terraria: System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char_Default
GetIndexOfFirstNonLatin1Char_Default()
static unsafe nuint System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char_Default (char * pBuffer, nuint bufferLength) inline static private
Definition at line 21 of file Latin1Utility.cs.
    {
        char* ptr = pBuffer;
        if (Vector.IsHardwareAccelerated && bufferLength >= (uint)(2 * Vector<ushort>.Count))
        {
            uint count = (uint)Vector<ushort>.Count;
            uint count2 = (uint)Vector<byte>.Count;
            Vector<ushort> right = new Vector<ushort>(255);
            if (Vector.LessThanOrEqualAll(Unsafe.ReadUnaligned<Vector<ushort>>(pBuffer), right))
            {
                char* ptr2 = pBuffer + bufferLength - count;
                pBuffer = (char*)((nuint)((byte*)pBuffer + count2) & ~(nuint)(count2 - 1));
                while (!Vector.GreaterThanAny(Unsafe.Read<Vector<ushort>>(pBuffer), right))
                {
                    pBuffer += count;
                    if (pBuffer > ptr2)
                    {
                        break;
                    }
                }
                bufferLength -= (nuint)(nint)(pBuffer - ptr);
            }
        }
        while (true)
        {
            uint num;
            if (bufferLength >= 4)
            {
                num = Unsafe.ReadUnaligned<uint>(pBuffer);
                uint num2 = Unsafe.ReadUnaligned<uint>(pBuffer + 2);
                if (!AllCharsInUInt32AreLatin1(num | num2))
                {
                    if (AllCharsInUInt32AreLatin1(num))
                    {
                        num = num2;
                        pBuffer += 2;
                    }
                    goto IL_010f;
                }
                pBuffer += 4;
                bufferLength -= 4;
                continue;
            }
            if ((bufferLength & 2) != 0)
            {
                num = Unsafe.ReadUnaligned<uint>(pBuffer);
                if (!AllCharsInUInt32AreLatin1(num))
                {
                    goto IL_010f;
                }
                pBuffer += 2;
            }
            if ((bufferLength & 1) != 0 && *pBuffer <= 'ÿ')
            {
                pBuffer++;
            }
            break;
            IL_010f:
            if (FirstCharInUInt32IsLatin1(num))
            {
                pBuffer++;
            }
            break;
        }
        nuint num3 = (nuint)((byte*)pBuffer - (nuint)ptr);
        return num3 / 2;
    }
References System.Text.Latin1Utility.AllCharsInUInt32AreLatin1(), System.count, System.Numerics.Vector< T >.Count, System.Text.Latin1Utility.FirstCharInUInt32IsLatin1(), and System.Numerics.Vector< T >.IsHardwareAccelerated.
Referenced by System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char().