Terraria: System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char_Sse2
GetIndexOfFirstNonLatin1Char_Sse2()
static unsafe nuint System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char_Sse2 (char * pBuffer, nuint bufferLength) inline static private
Definition at line 89 of file Latin1Utility.cs.
    {
        if (bufferLength == 0)
        {
            return 0u;
        }
        uint num = (uint)Unsafe.SizeOf<Vector128<byte>>();
        uint num2 = num / 2;
        char* ptr = pBuffer;
        Vector128<ushort> right;
        Vector128<ushort> right2;
        Vector128<ushort> left;
        uint num3;
        if (bufferLength >= num2)
        {
            right = Vector128.Create((ushort)65280);
            right2 = Vector128.Create((ushort)32512);
            left = Sse2.LoadVector128((ushort*)pBuffer);
            num3 = (uint)Sse2.MoveMask(Sse2.AddSaturate(left, right2).AsByte());
            if ((num3 & 0xAAAA) == 0)
            {
                bufferLength <<= 1;
                if (bufferLength < 2 * num)
                {
                    goto IL_013e;
                }
                pBuffer = (char*)((nuint)((byte*)pBuffer + num) & ~(nuint)(num - 1));
                bufferLength = (nuint)(bufferLength + (byte*)ptr);
                bufferLength -= (nuint)pBuffer;
                if (bufferLength < 2 * num)
                {
                    goto IL_00fa;
                }
                char* ptr2 = (char*)((byte*)pBuffer + bufferLength - 2 * num);
                Vector128<ushort> vector;
                while (true)
                {
                    left = Sse2.LoadAlignedVector128((ushort*)pBuffer);
                    vector = Sse2.LoadAlignedVector128((ushort*)(pBuffer + num2));
                    Vector128<ushort> left2 = Sse2.Or(left, vector);
                    if (Sse41.IsSupported)
                    {
                        if (!Sse41.TestZ(left2, right))
{
                            break;
                        }
                    }
                    else
                    {
                        num3 = (uint)Sse2.MoveMask(Sse2.AddSaturate(left2, right2).AsByte());
                        if ((num3 & 0xAAAAu) != 0)
{
                            break;
                        }
                    }
                    pBuffer += 2 * num2;
                    if (pBuffer <= ptr2)
                    {
                        continue;
                    }
                    goto IL_00fa;
                }
                if (Sse41.IsSupported)
                {
                    if (!Sse41.TestZ(left, right))
                    {
                        goto IL_01e6;
                    }
                }
                else
                {
                    num3 = (uint)Sse2.MoveMask(Sse2.AddSaturate(left, right2).AsByte());
                    if ((num3 & 0xAAAAu) != 0)
                    {
                        goto IL_01fa;
                    }
                }
                pBuffer += num2;
                left = vector;
                goto IL_01e6;
            }
            goto IL_01fa;
        }
        uint num5;
        if ((bufferLength & 4) != 0)
        {
            if (Bmi1.X64.IsSupported)
            {
                ulong num4 = Unsafe.ReadUnaligned<ulong>(pBuffer);
                if (!AllCharsInUInt64AreLatin1(num4))
                {
                    num4 &= 0xFF00FF00FF00FF00uL;
                    pBuffer = (char*)((byte*)pBuffer + (nuint)((nint)(Bmi1.X64.TrailingZeroCount(num4) / 8) & ~(nint)1));
                    goto IL_01a1;
                }
            }
            else
            {
                num5 = Unsafe.ReadUnaligned<uint>(pBuffer);
                uint num6 = Unsafe.ReadUnaligned<uint>(pBuffer + 2);
                if (!AllCharsInUInt32AreLatin1(num5 | num6))
                {
                    if (AllCharsInUInt32AreLatin1(num5))
                    {
                        num5 = num6;
                        pBuffer += 2;
                    }
                    goto IL_0214;
                }
            }
            pBuffer += 4;
        }
        if ((bufferLength & 2) != 0)
        {
            num5 = Unsafe.ReadUnaligned<uint>(pBuffer);
            if (!AllCharsInUInt32AreLatin1(num5))
            {
                goto IL_0214;
            }
            pBuffer += 2;
        }
        if ((bufferLength & 1) != 0 && *pBuffer <= 'ÿ')
        {
            pBuffer++;
        }
        goto IL_01a1;
        IL_01e6:
        num3 = (uint)Sse2.MoveMask(Sse2.AddSaturate(left, right2).AsByte());
        goto IL_01fa;
        IL_0214:
        if (FirstCharInUInt32IsLatin1(num5))
        {
            pBuffer++;
        }
        goto IL_01a1;
        IL_01a1:
        return (nuint)(pBuffer - ptr);
        IL_0148:
        if (((byte)bufferLength & (num - 1)) != 0)
        {
            pBuffer = (char*)((byte*)pBuffer + (bufferLength & (num - 1)) - num);
            left = Sse2.LoadVector128((ushort*)pBuffer);
            if (Sse41.IsSupported)
            {
                if (!Sse41.TestZ(left, right))
                {
                    goto IL_01e6;
                }
            }
            else
            {
                num3 = (uint)Sse2.MoveMask(Sse2.AddSaturate(left, right2).AsByte());
                if ((num3 & 0xAAAAu) != 0)
                {
                    goto IL_01fa;
                }
            }
            pBuffer += num2;
        }
        goto IL_01a1;
        IL_00fa:
        if ((bufferLength & num) != 0)
        {
            left = Sse2.LoadAlignedVector128((ushort*)pBuffer);
            if (Sse41.IsSupported)
            {
                if (!Sse41.TestZ(left, right))
                {
                    goto IL_01e6;
                }
            }
            else
            {
                num3 = (uint)Sse2.MoveMask(Sse2.AddSaturate(left, right2).AsByte());
                if ((num3 & 0xAAAAu) != 0)
                {
                    goto IL_01fa;
                }
            }
            goto IL_013e;
        }
        goto IL_0148;
        IL_01fa:
        num3 &= 0xAAAAu;
        pBuffer = (char*)((byte*)pBuffer + (uint)BitOperations.TrailingZeroCount(num3) - 1);
        goto IL_01a1;
        IL_013e:
        pBuffer += num2;
        goto IL_0148;
    }
References System.Runtime.Intrinsics.X86.Sse2.AddSaturate(), System.Text.Latin1Utility.AllCharsInUInt32AreLatin1(), System.Text.Latin1Utility.AllCharsInUInt64AreLatin1(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Text.Latin1Utility.FirstCharInUInt32IsLatin1(), System.Runtime.Intrinsics.X86.Bmi1.X64.IsSupported, System.Runtime.Intrinsics.X86.Sse41.IsSupported, System.Runtime.Intrinsics.X86.Sse2.LoadAlignedVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse41.TestZ(), System.Numerics.BitOperations.TrailingZeroCount(), and System.Runtime.Intrinsics.X86.Bmi1.X64.TrailingZeroCount().
Referenced by System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char().