Terraria: System.Text.Latin1Utility.WidenLatin1ToUtf16_Sse2
WidenLatin1ToUtf16_Sse2()
static unsafe void System.Text.Latin1Utility.WidenLatin1ToUtf16_Sse2 (byte * pLatin1Buffer, char * pUtf16Buffer, nuint elementCount) inline static private
Definition at line 496 of file Latin1Utility.cs.
    {
        uint num = (uint)Unsafe.SizeOf<Vector128<byte>>();
        nuint num2 = num - 1;
        nuint num3 = 0u;
        Vector128<byte> zero = Vector128<byte>.Zero;
        if (elementCount >= num)
        {
            Vector128<byte> left = Sse2.LoadScalarVector128((ulong*)pLatin1Buffer).AsByte();
            Sse2.Store((byte*)pUtf16Buffer, Sse2.UnpackLow(left, zero));
            num3 = (num >> 1) - (((nuint)pUtf16Buffer >> 1) & (num2 >> 1));
            char* ptr = pUtf16Buffer + num3;
            nuint num4 = elementCount - num;
            while (num3 <= num4)
            {
                left = Sse2.LoadVector128(pLatin1Buffer + num3);
                Vector128<byte> source = Sse2.UnpackLow(left, zero);
                Sse2.StoreAligned((byte*)ptr, source);
                Vector128<byte> source2 = Sse2.UnpackHigh(left, zero);
                Sse2.StoreAligned((byte*)ptr + num, source2);
                num3 += num;
                ptr += num;
            }
        }
        uint num5 = (uint)((int)elementCount - (int)num3);
        if ((num5 & 8u) != 0)
        {
            Vector128<byte> left = Sse2.LoadScalarVector128((ulong*)(pLatin1Buffer + num3)).AsByte();
            Sse2.Store((byte*)(pUtf16Buffer + num3), Sse2.UnpackLow(left, zero));
            num3 += 8;
        }
        if ((num5 & 4u) != 0)
        {
            Vector128<byte> left = Sse2.LoadScalarVector128((uint*)(pLatin1Buffer + num3)).AsByte();
            Sse2.StoreScalar((ulong*)(pUtf16Buffer + num3), Sse2.UnpackLow(left, zero).AsUInt64());
            num3 += 4;
        }
        if ((num5 & 3) == 0)
        {
            return;
        }
        pUtf16Buffer[num3] = (char)pLatin1Buffer[num3];
        if ((num5 & 2u) != 0)
        {
            pUtf16Buffer[num3 + 1] = (char)pLatin1Buffer[num3 + 1];
            if ((num5 & (true ? 1u : 0u)) != 0)
            {
                pUtf16Buffer[num3 + 2] = (char)pLatin1Buffer[num3 + 2];
            }
        }
    }
References System.Runtime.Intrinsics.X86.Sse2.LoadScalarVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.source, System.Runtime.Intrinsics.X86.Sse2.Store(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Runtime.Intrinsics.X86.Sse2.StoreScalar(), System.Runtime.Intrinsics.X86.Sse2.UnpackHigh(), System.Runtime.Intrinsics.X86.Sse2.UnpackLow(), and System.Runtime.Intrinsics.Vector128< T >.Zero.
Referenced by System.Text.Latin1Utility.WidenLatin1ToUtf16().