Terraria: System.Text.Latin1Utility.NarrowUtf16ToLatin1
NarrowUtf16ToLatin1()
static unsafe nuint System.Text.Latin1Utility.NarrowUtf16ToLatin1 (char * pUtf16Buffer, byte * pLatin1Buffer, nuint elementCount) inline static
Definition at line 280 of file Latin1Utility.cs.
    {
        nuint num = 0u;
        uint num2 = 0u;
        uint num3 = 0u;
        ulong num4 = 0uL;
        if (Sse2.IsSupported)
        {
            if (elementCount >= (uint)(2 * Unsafe.SizeOf<Vector128<byte>>()))
            {
                _ = IntPtr.Size;
                num4 = Unsafe.ReadUnaligned<ulong>(pUtf16Buffer);
                if (!AllCharsInUInt64AreLatin1(num4))
                {
                    goto IL_0191;
                }
                num = NarrowUtf16ToLatin1_Sse2(pUtf16Buffer, pLatin1Buffer, elementCount);
            }
        }
        else if (Vector.IsHardwareAccelerated)
        {
            uint num5 = (uint)Unsafe.SizeOf<Vector<byte>>();
            if (elementCount >= 2 * num5)
            {
                _ = IntPtr.Size;
                num4 = Unsafe.ReadUnaligned<ulong>(pUtf16Buffer);
                if (!AllCharsInUInt64AreLatin1(num4))
                {
                    goto IL_0191;
                }
                Vector<ushort> right = new Vector<ushort>(255);
                nuint num6 = elementCount - 2 * num5;
                do
                {
                    Vector<ushort> vector = Unsafe.ReadUnaligned<Vector<ushort>>(pUtf16Buffer + num);
                    Vector<ushort> vector2 = Unsafe.ReadUnaligned<Vector<ushort>>(pUtf16Buffer + num + Vector<ushort>.Count);
                    if (Vector.GreaterThanAny(Vector.BitwiseOr(vector, vector2), right))
                    {
                        break;
                    }
                    Vector<byte> value = Vector.Narrow(vector, vector2);
                    Unsafe.WriteUnaligned(pLatin1Buffer + num, value);
                    num += num5;
                }
                while (num <= num6);
            }
        }
        nuint num7 = elementCount - num;
        if (num7 < 4)
        {
            goto IL_013a;
        }
        nuint num8 = num + num7 - 4;
        while (true)
        {
            _ = IntPtr.Size;
            num4 = Unsafe.ReadUnaligned<ulong>(pUtf16Buffer + num);
            if (!AllCharsInUInt64AreLatin1(num4))
            {
                break;
            }
            NarrowFourUtf16CharsToLatin1AndWriteToBuffer(ref pLatin1Buffer[num], num4);
            num += 4;
            if (num <= num8)
            {
                continue;
            }
            goto IL_013a;
        }
        goto IL_0191;
        IL_01ca:
        if (FirstCharInUInt32IsLatin1(num2))
        {
            if (!BitConverter.IsLittleEndian)
            {
            }
            pLatin1Buffer[num] = (byte)num2;
            num++;
        }
        goto IL_018f;
        IL_018f:
        return num;
        IL_013a:
        if (((uint)(int)num7 & 2u) != 0)
        {
            num2 = Unsafe.ReadUnaligned<uint>(pUtf16Buffer + num);
            if (!AllCharsInUInt32AreLatin1(num2))
            {
                goto IL_01ca;
            }
            NarrowTwoUtf16CharsToLatin1AndWriteToBuffer(ref pLatin1Buffer[num], num2);
            num += 2;
        }
        if (((uint)(int)num7 & (true ? 1u : 0u)) != 0)
        {
            num2 = pUtf16Buffer[num];
            if (num2 <= 255)
            {
                pLatin1Buffer[num] = (byte)num2;
                num++;
            }
        }
        goto IL_018f;
        IL_0191:
        _ = IntPtr.Size;
        _ = BitConverter.IsLittleEndian;
        num2 = (uint)num4;
        if (AllCharsInUInt32AreLatin1(num2))
        {
            NarrowTwoUtf16CharsToLatin1AndWriteToBuffer(ref pLatin1Buffer[num], num2);
            _ = BitConverter.IsLittleEndian;
            num2 = (uint)(num4 >> 32);
            num += 2;
        }
        goto IL_01ca;
    }
References System.Text.Latin1Utility.AllCharsInUInt32AreLatin1(), System.Text.Latin1Utility.AllCharsInUInt64AreLatin1(), System.Numerics.Vector< T >.Count, System.Text.Latin1Utility.FirstCharInUInt32IsLatin1(), System.Numerics.Vector< T >.IsHardwareAccelerated, System.BitConverter.IsLittleEndian, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.Numerics.Vector< T >.Narrow(), System.Text.Latin1Utility.NarrowFourUtf16CharsToLatin1AndWriteToBuffer(), System.Text.Latin1Utility.NarrowTwoUtf16CharsToLatin1AndWriteToBuffer(), System.Text.Latin1Utility.NarrowUtf16ToLatin1_Sse2(), System.IntPtr.Size, and System.value.
Referenced by System.Text.Latin1Encoding.GetBytesFast().