Terraria: Terraria.GameContent.UI.States.UIWorkshopHub.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIWorkshopHub.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 349 of file UIWorkshopHub.cs.
    {
        UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
        int num = 3000;
        int idRangeEndExclusive = num;
        UILinkPoint linkPoint = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonUseResourcePacks);
        UILinkPoint linkPoint2 = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonPublishResourcePacks);
        UILinkPoint linkPoint3 = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonImportWorlds);
        UILinkPoint linkPoint4 = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonPublishWorlds);
        UILinkPoint linkPoint5 = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonBack);
        UILinkPoint linkPoint6 = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonLogs);
        _helper.PairLeftRight(linkPoint3, linkPoint);
        _helper.PairLeftRight(linkPoint4, linkPoint2);
        _helper.PairLeftRight(linkPoint5, linkPoint6);
        _helper.PairUpDown(linkPoint3, linkPoint4);
        _helper.PairUpDown(linkPoint, linkPoint2);
        _helper.PairUpDown(linkPoint4, linkPoint5);
        _helper.PairUpDown(linkPoint2, linkPoint6);
        _helper.MoveToVisuallyClosestPoint(num, idRangeEndExclusive);
    }
References Terraria.GameContent.UI.States.UIWorkshopHub._buttonBack, Terraria.GameContent.UI.States.UIWorkshopHub._buttonImportWorlds, Terraria.GameContent.UI.States.UIWorkshopHub._buttonLogs, Terraria.GameContent.UI.States.UIWorkshopHub._buttonPublishResourcePacks, Terraria.GameContent.UI.States.UIWorkshopHub._buttonPublishWorlds, Terraria.GameContent.UI.States.UIWorkshopHub._buttonUseResourcePacks, Terraria.GameContent.UI.States.UIWorkshopHub._helper, Terraria.GameContent.UI.States.UIGamepadHelper.GetLinkPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.PairLeftRight(), and Terraria.GameContent.UI.States.UIGamepadHelper.PairUpDown().
Referenced by Terraria.GameContent.UI.States.UIWorkshopHub.Draw().