Terraria: Terraria.GameContent.UI.States.UIWorkshopHub.AddDescriptionPanel
AddDescriptionPanel()
void Terraria.GameContent.UI.States.UIWorkshopHub.AddDescriptionPanel (UIElement container, float accumulatedHeight, float height, string tagGroup) inline private
    {
        float num = 0f;
        UISlicedImage uISlicedImage = new UISlicedImage(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", (AssetRequestMode)1))
        {
            HAlign = 0.5f,
            VAlign = 1f,
            Width = StyleDimension.FromPixelsAndPercent((0f - num) * 2f, 1f),
            Left = StyleDimension.FromPixels(0f - num),
            Height = StyleDimension.FromPixelsAndPercent(height, 0f),
            Top = StyleDimension.FromPixels(2f)
        };
        uISlicedImage.SetSliceDepths(10);
        uISlicedImage.Color = Color.LightGray * 0.7f;
        container.Append(uISlicedImage);
        UIText uIText = new UIText(Language.GetText("Workshop.HubDescriptionDefault"))
        {
            HAlign = 0f,
            VAlign = 0f,
            Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
            Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
            Top = StyleDimension.FromPixelsAndPercent(5f, 0f)
        };
        uIText.PaddingLeft = 20f;
        uIText.PaddingRight = 20f;
        uIText.PaddingTop = 6f;
        uIText.IsWrapped = true;
        uISlicedImage.Append(uIText);
        _descriptionText = uIText;
    }
References Terraria.GameContent.UI.States.UIWorkshopHub._descriptionText, Terraria.Main.Assets, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorkshopHub.OnInitialize().