Terraria: Terraria.GameContent.UI.States.UIWorkshopHub.ClearOptionDescription
ClearOptionDescription()
void Terraria.GameContent.UI.States.UIWorkshopHub.ClearOptionDescription (UIMouseEvent evt, UIElement listeningElement) inline
Definition at line 213 of file UIWorkshopHub.cs.
    {
        _descriptionText.SetText(Language.GetText("Workshop.HubDescriptionDefault"));
    }
References Terraria.GameContent.UI.States.UIWorkshopHub._descriptionText, Terraria.Localization.Language.GetText(), and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton().