Terraria: System.Xml.ReadContentAsBinaryHelper.InitAsync
InitAsync()
async Task< bool > System.Xml.ReadContentAsBinaryHelper.InitAsync () inline private
Definition at line 622 of file ReadContentAsBinaryHelper.cs.
    {
        if (!(await MoveToNextContentNodeAsync(moveIfOnContentNode: false).ConfigureAwait(continueOnCapturedContext: false)))
        {
            return false;
        }
        _state = State.InReadContent;
        _isEnd = false;
        return true;
    }
References System.Xml.ReadContentAsBinaryHelper._isEnd, System.Xml.ReadContentAsBinaryHelper._state, System.Xml.Dictionary, and System.Xml.ReadContentAsBinaryHelper.MoveToNextContentNodeAsync().
Referenced by System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64Async(), and System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHexAsync().