Terraria: System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinaryAsync
ReadElementContentAsBinaryAsync()
async Task< int > System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinaryAsync (byte[] buffer, int index, int count) inline private
Definition at line 702 of file ReadContentAsBinaryHelper.cs.
    {
        if (count == 0)
        {
            return 0;
        }
        int num = await ReadContentAsBinaryAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
        if (num > 0)
        {
            return num;
        }
        if (_reader.NodeType != XmlNodeType.EndElement)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, _reader.NodeType.ToString(), _reader as IXmlLineInfo);
        }
        await _reader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
        _state = State.None;
        return 0;
    }
References System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._state, System.buffer, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.Xml.Dictionary, System.index, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadAsync(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinaryAsync(), System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBase64Async(), and System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHexAsync().