Terraria: System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHex
ReadContentAsBinHex()
int System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHex (byte[] buffer, int index, int count) inline package
Definition at line 99 of file ReadContentAsBinaryHelper.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        switch (_state)
        {
        case State.None:
            if (!_reader.CanReadContentAs())
            {
                throw _reader.CreateReadContentAsException("ReadContentAsBinHex");
            }
            if (!Init())
            {
                return 0;
            }
            break;
        case State.InReadContent:
            if (_decoder == _binHexDecoder)
            {
                return ReadContentAsBinary(buffer, index, count);
            }
            break;
        case State.InReadElementContent:
            throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
        default:
            return 0;
        }
        InitBinHexDecoder();
        return ReadContentAsBinary(buffer, index, count);
    }
References System.Xml.ReadContentAsBinaryHelper._binHexDecoder, System.Xml.ReadContentAsBinaryHelper._decoder, System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._state, System.buffer, System.Xml.XmlReader.CanReadContentAs(), System.count, System.Xml.XmlReader.CreateReadContentAsException(), System.index, System.Xml.ReadContentAsBinaryHelper.Init(), System.Xml.ReadContentAsBinaryHelper.InitBinHexDecoder(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinary(), and System.SR.Xml_MixingBinaryContentMethods.
Referenced by System.Xml.XPath.XPathNavigatorReader.ReadContentAsBinHex(), System.Xml.XmlCharCheckingReader.ReadContentAsBinHex(), System.Xml.XmlNodeReader.ReadContentAsBinHex(), System.Xml.XmlValidatingReaderImpl.ReadContentAsBinHex(), and System.Xml.XsdValidatingReader.ReadContentAsBinHex().