Terraria: System.Xml.ReadContentAsBinaryHelper.CreateOrReset
CreateOrReset()
static ReadContentAsBinaryHelper System.Xml.ReadContentAsBinaryHelper.CreateOrReset (ReadContentAsBinaryHelper helper, XmlReader reader) inline static package
Definition at line 44 of file ReadContentAsBinaryHelper.cs.
    {
        if (helper == null)
        {
            return new ReadContentAsBinaryHelper(reader);
        }
        helper.Reset();
        return helper;
    }
References System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinaryHelper(), and System.Xml.ReadContentAsBinaryHelper.Reset().
Referenced by System.Xml.XPath.XPathNavigatorReader.ReadContentAsBase64(), System.Xml.XmlCharCheckingReader.ReadContentAsBase64(), System.Xml.XmlNodeReader.ReadContentAsBase64(), System.Xml.XmlValidatingReaderImpl.ReadContentAsBase64(), System.Xml.XsdValidatingReader.ReadContentAsBase64(), System.Xml.XmlCharCheckingReader.ReadContentAsBase64Async(), System.Xml.XmlValidatingReaderImpl.ReadContentAsBase64Async(), System.Xml.XsdValidatingReader.ReadContentAsBase64Async(), System.Xml.XPath.XPathNavigatorReader.ReadContentAsBinHex(), System.Xml.XmlCharCheckingReader.ReadContentAsBinHex(), System.Xml.XmlNodeReader.ReadContentAsBinHex(), System.Xml.XmlValidatingReaderImpl.ReadContentAsBinHex(), System.Xml.XsdValidatingReader.ReadContentAsBinHex(), System.Xml.XmlCharCheckingReader.ReadContentAsBinHexAsync(), System.Xml.XmlValidatingReaderImpl.ReadContentAsBinHexAsync(), System.Xml.XsdValidatingReader.ReadContentAsBinHexAsync(), System.Xml.XPath.XPathNavigatorReader.ReadElementContentAsBase64(), System.Xml.XmlCharCheckingReader.ReadElementContentAsBase64(), System.Xml.XmlNodeReader.ReadElementContentAsBase64(), System.Xml.XmlValidatingReaderImpl.ReadElementContentAsBase64(), System.Xml.XsdValidatingReader.ReadElementContentAsBase64(), System.Xml.XmlCharCheckingReader.ReadElementContentAsBase64Async(), System.Xml.XmlValidatingReaderImpl.ReadElementContentAsBase64Async(), System.Xml.XsdValidatingReader.ReadElementContentAsBase64Async(), System.Xml.XPath.XPathNavigatorReader.ReadElementContentAsBinHex(), System.Xml.XmlCharCheckingReader.ReadElementContentAsBinHex(), System.Xml.XmlNodeReader.ReadElementContentAsBinHex(), System.Xml.XmlValidatingReaderImpl.ReadElementContentAsBinHex(), System.Xml.XsdValidatingReader.ReadElementContentAsBinHex(), System.Xml.XmlCharCheckingReader.ReadElementContentAsBinHexAsync(), System.Xml.XmlValidatingReaderImpl.ReadElementContentAsBinHexAsync(), and System.Xml.XsdValidatingReader.ReadElementContentAsBinHexAsync().