Terraria: System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHexAsync
ReadElementContentAsBinHexAsync()
async Task< int > System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHexAsync (byte[] buffer, int index, int count) inline package
Definition at line 558 of file ReadContentAsBinaryHelper.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        switch (_state)
        {
        case State.None:
            if (_reader.NodeType != XmlNodeType.Element)
            {
                throw _reader.CreateReadElementContentAsException("ReadElementContentAsBinHex");
            }
            if (!(await InitOnElementAsync().ConfigureAwait(continueOnCapturedContext: false)))
            {
                return 0;
            }
            break;
        case State.InReadContent:
            throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
        case State.InReadElementContent:
            if (_decoder == _binHexDecoder)
            {
                return await ReadElementContentAsBinaryAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
            }
            break;
        default:
            return 0;
        }
        InitBinHexDecoder();
        return await ReadElementContentAsBinaryAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.ReadContentAsBinaryHelper._binHexDecoder, System.Xml.ReadContentAsBinaryHelper._decoder, System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._state, System.buffer, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.Xml.XmlReader.CreateReadElementContentAsException(), System.Xml.Dictionary, System.index, System.Xml.ReadContentAsBinaryHelper.InitBinHexDecoder(), System.Xml.ReadContentAsBinaryHelper.InitOnElementAsync(), System.Xml.XmlReader.NodeType, System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinaryAsync(), and System.SR.Xml_MixingBinaryContentMethods.
Referenced by System.Xml.XmlCharCheckingReader.ReadElementContentAsBinHexAsync(), System.Xml.XmlValidatingReaderImpl.ReadElementContentAsBinHexAsync(), and System.Xml.XsdValidatingReader.ReadElementContentAsBinHexAsync().