Terraria: System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinary
ReadContentAsBinary()
int System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinary (byte[] buffer, int index, int count) inline private
Definition at line 319 of file ReadContentAsBinaryHelper.cs.
    {
        if (_isEnd)
        {
            Reset();
            return 0;
        }
        _decoder.SetNextOutputBuffer(buffer, index, count);
        do
        {
            if (_canReadValueChunk)
            {
                while (true)
                {
                    if (_valueOffset < _valueChunkLength)
                    {
                        int num = _decoder.Decode(_valueChunk, _valueOffset, _valueChunkLength - _valueOffset);
                        _valueOffset += num;
                    }
                    if (_decoder.IsFull)
                    {
                        return _decoder.DecodedCount;
                    }
                    if ((_valueChunkLength = _reader.ReadValueChunk(_valueChunk, 0, 256)) == 0)
                    {
                        break;
                    }
                    _valueOffset = 0;
                }
            }
            else
            {
                string value = _reader.Value;
                int num2 = _decoder.Decode(value, _valueOffset, value.Length - _valueOffset);
                _valueOffset += num2;
                if (_decoder.IsFull)
                {
                    return _decoder.DecodedCount;
                }
            }
            _valueOffset = 0;
        }
        while (MoveToNextContentNode(moveIfOnContentNode: true));
        _isEnd = true;
        return _decoder.DecodedCount;
    }
References System.Xml.ReadContentAsBinaryHelper._canReadValueChunk, System.Xml.ReadContentAsBinaryHelper._decoder, System.Xml.ReadContentAsBinaryHelper._isEnd, System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._valueChunk, System.Xml.ReadContentAsBinaryHelper._valueChunkLength, System.Xml.ReadContentAsBinaryHelper._valueOffset, System.buffer, System.count, System.Xml.IncrementalReadDecoder.Decode(), System.Xml.IncrementalReadDecoder.DecodedCount, System.Xml.Dictionary, System.index, System.Xml.IncrementalReadDecoder.IsFull, System.Xml.ReadContentAsBinaryHelper.MoveToNextContentNode(), System.Xml.XmlReader.ReadValueChunk(), System.Xml.ReadContentAsBinaryHelper.Reset(), System.Xml.IncrementalReadDecoder.SetNextOutputBuffer(), System.value, and System.Xml.XmlReader.Value.
Referenced by System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHex(), and System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinary().