Terraria: System.Xml.ReadContentAsBinaryHelper.Finish
Finish()
void System.Xml.ReadContentAsBinaryHelper.Finish () inline package
Definition at line 234 of file ReadContentAsBinaryHelper.cs.
    {
        if (_state != 0)
        {
            while (MoveToNextContentNode(moveIfOnContentNode: true))
            {
            }
            if (_state == State.InReadElementContent)
            {
                if (_reader.NodeType != XmlNodeType.EndElement)
                {
                    throw new XmlException(System.SR.Xml_InvalidNodeType, _reader.NodeType.ToString(), _reader as IXmlLineInfo);
                }
                _reader.Read();
            }
        }
        Reset();
    }
References System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._state, System.Xml.Dictionary, System.Xml.ReadContentAsBinaryHelper.MoveToNextContentNode(), System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.ReadContentAsBinaryHelper.Reset(), System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Xml.XmlCharCheckingReader.FinishReadBinary(), System.Xml.XmlNodeReader.FinishReadBinary(), System.Xml.XsdValidatingReader.MoveToAttribute(), System.Xml.XPath.XPathNavigatorReader.MoveToAttribute(), System.Xml.XPath.XPathNavigatorReader.MoveToAttribute(), System.Xml.XsdValidatingReader.MoveToAttribute(), System.Xml.XsdValidatingReader.MoveToAttribute(), System.Xml.XPath.XPathNavigatorReader.MoveToElement(), System.Xml.XPath.XPathNavigatorReader.MoveToFirstAttribute(), System.Xml.XsdValidatingReader.MoveToFirstAttribute(), System.Xml.XPath.XPathNavigatorReader.MoveToNextAttribute(), System.Xml.XsdValidatingReader.MoveToNextAttribute(), System.Xml.XPath.XPathNavigatorReader.Read(), System.Xml.XmlValidatingReaderImpl.Read(), System.Xml.XsdValidatingReader.Read(), System.Xml.XPath.XPathNavigatorReader.ReadAttributeValue(), System.Xml.XmlValidatingReaderImpl.ReadAttributeValue(), and System.Xml.XsdValidatingReader.ReadAttributeValue().