Terraria: System.Xml.ReadContentAsBinaryHelper.FinishAsync
FinishAsync()
async Task System.Xml.ReadContentAsBinaryHelper.FinishAsync () inline package
Definition at line 603 of file ReadContentAsBinaryHelper.cs.
    {
        if (_state != 0)
        {
            while (await MoveToNextContentNodeAsync(moveIfOnContentNode: true).ConfigureAwait(continueOnCapturedContext: false))
            {
            }
            if (_state == State.InReadElementContent)
            {
                if (_reader.NodeType != XmlNodeType.EndElement)
                {
                    throw new XmlException(System.SR.Xml_InvalidNodeType, _reader.NodeType.ToString(), _reader as IXmlLineInfo);
                }
                await _reader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        Reset();
    }
References System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._state, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.ReadContentAsBinaryHelper.MoveToNextContentNodeAsync(), System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadAsync(), System.Xml.ReadContentAsBinaryHelper.Reset(), System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Xml.XmlCharCheckingReader.FinishReadBinaryAsync(), System.Xml.XmlValidatingReaderImpl.ReadAsync(), and System.Xml.XsdValidatingReader.ReadAsync().