Terraria: System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64
ReadContentAsBase64()
int System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64 (byte[] buffer, int index, int count) inline package
Definition at line 54 of file ReadContentAsBinaryHelper.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        switch (_state)
        {
        case State.None:
            if (!_reader.CanReadContentAs())
            {
                throw _reader.CreateReadContentAsException("ReadContentAsBase64");
            }
            if (!Init())
            {
                return 0;
            }
            break;
        case State.InReadContent:
            if (_decoder == _base64Decoder)
            {
                return ReadContentAsBinary(buffer, index, count);
            }
            break;
        case State.InReadElementContent:
            throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
        default:
            return 0;
        }
        InitBase64Decoder();
        return ReadContentAsBinary(buffer, index, count);
    }
References System.Xml.ReadContentAsBinaryHelper._base64Decoder, System.Xml.ReadContentAsBinaryHelper._decoder, System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._state, System.buffer, System.Xml.XmlReader.CanReadContentAs(), System.count, System.Xml.XmlReader.CreateReadContentAsException(), System.index, System.Xml.ReadContentAsBinaryHelper.Init(), System.Xml.ReadContentAsBinaryHelper.InitBase64Decoder(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinary(), and System.SR.Xml_MixingBinaryContentMethods.
Referenced by System.Xml.XPath.XPathNavigatorReader.ReadContentAsBase64(), System.Xml.XmlCharCheckingReader.ReadContentAsBase64(), System.Xml.XmlNodeReader.ReadContentAsBase64(), System.Xml.XmlValidatingReaderImpl.ReadContentAsBase64(), and System.Xml.XsdValidatingReader.ReadContentAsBase64().