Terraria: System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHexAsync
ReadContentAsBinHexAsync()
async Task< int > System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHexAsync (byte[] buffer, int index, int count) inline package
Definition at line 468 of file ReadContentAsBinaryHelper.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        switch (_state)
        {
        case State.None:
            if (!_reader.CanReadContentAs())
            {
                throw _reader.CreateReadContentAsException("ReadContentAsBinHex");
            }
            if (!(await InitAsync().ConfigureAwait(continueOnCapturedContext: false)))
            {
                return 0;
            }
            break;
        case State.InReadContent:
            if (_decoder == _binHexDecoder)
            {
                return await ReadContentAsBinaryAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
            }
            break;
        case State.InReadElementContent:
            throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
        default:
            return 0;
        }
        InitBinHexDecoder();
        return await ReadContentAsBinaryAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.ReadContentAsBinaryHelper._binHexDecoder, System.Xml.ReadContentAsBinaryHelper._decoder, System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._state, System.buffer, System.Xml.XmlReader.CanReadContentAs(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.Dictionary, System.index, System.Xml.ReadContentAsBinaryHelper.InitAsync(), System.Xml.ReadContentAsBinaryHelper.InitBinHexDecoder(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinaryAsync(), and System.SR.Xml_MixingBinaryContentMethods.
Referenced by System.Xml.XmlCharCheckingReader.ReadContentAsBinHexAsync(), System.Xml.XmlValidatingReaderImpl.ReadContentAsBinHexAsync(), and System.Xml.XsdValidatingReader.ReadContentAsBinHexAsync().