Terraria: System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHex
ReadElementContentAsBinHex()
int System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHex (byte[] buffer, int index, int count) inline package
Definition at line 189 of file ReadContentAsBinaryHelper.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        switch (_state)
        {
        case State.None:
            if (_reader.NodeType != XmlNodeType.Element)
            {
                throw _reader.CreateReadElementContentAsException("ReadElementContentAsBinHex");
            }
            if (!InitOnElement())
            {
                return 0;
            }
            break;
        case State.InReadContent:
            throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
        case State.InReadElementContent:
            if (_decoder == _binHexDecoder)
            {
                return ReadElementContentAsBinary(buffer, index, count);
            }
            break;
        default:
            return 0;
        }
        InitBinHexDecoder();
        return ReadElementContentAsBinary(buffer, index, count);
    }
References System.Xml.ReadContentAsBinaryHelper._binHexDecoder, System.Xml.ReadContentAsBinaryHelper._decoder, System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._state, System.buffer, System.count, System.Xml.XmlReader.CreateReadElementContentAsException(), System.index, System.Xml.ReadContentAsBinaryHelper.InitBinHexDecoder(), System.Xml.ReadContentAsBinaryHelper.InitOnElement(), System.Xml.XmlReader.NodeType, System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinary(), and System.SR.Xml_MixingBinaryContentMethods.
Referenced by System.Xml.XPath.XPathNavigatorReader.ReadElementContentAsBinHex(), System.Xml.XmlCharCheckingReader.ReadElementContentAsBinHex(), System.Xml.XmlNodeReader.ReadElementContentAsBinHex(), System.Xml.XmlValidatingReaderImpl.ReadElementContentAsBinHex(), and System.Xml.XsdValidatingReader.ReadElementContentAsBinHex().