Terraria: System.Xml.ReadContentAsBinaryHelper.InitBinHexDecoder
InitBinHexDecoder()
void System.Xml.ReadContentAsBinaryHelper.InitBinHexDecoder () inline private
Definition at line 306 of file ReadContentAsBinaryHelper.cs.
    {
        if (_binHexDecoder == null)
        {
            _binHexDecoder = new BinHexDecoder();
        }
        else
        {
            _binHexDecoder.Reset();
        }
        _decoder = _binHexDecoder;
    }
References System.Xml.ReadContentAsBinaryHelper._binHexDecoder, System.Xml.ReadContentAsBinaryHelper._decoder, and System.Xml.BinHexDecoder.Reset().
Referenced by System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHex(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHexAsync(), System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHex(), and System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHexAsync().