Terraria: System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinaryAsync
ReadContentAsBinaryAsync()
async Task< int > System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinaryAsync (byte[] buffer, int index, int count) inline private
Definition at line 655 of file ReadContentAsBinaryHelper.cs.
    {
        if (_isEnd)
        {
            Reset();
            return 0;
        }
        _decoder.SetNextOutputBuffer(buffer, index, count);
        do
        {
            if (_canReadValueChunk)
            {
                while (true)
                {
                    if (_valueOffset < _valueChunkLength)
                    {
                        int num = _decoder.Decode(_valueChunk, _valueOffset, _valueChunkLength - _valueOffset);
                        _valueOffset += num;
                    }
                    if (_decoder.IsFull)
                    {
                        return _decoder.DecodedCount;
                    }
                    if ((_valueChunkLength = await _reader.ReadValueChunkAsync(_valueChunk, 0, 256).ConfigureAwait(continueOnCapturedContext: false)) == 0)
                    {
                        break;
                    }
                    _valueOffset = 0;
                }
            }
            else
            {
                string text = await _reader.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false);
                int num2 = _decoder.Decode(text, _valueOffset, text.Length - _valueOffset);
                _valueOffset += num2;
                if (_decoder.IsFull)
                {
                    return _decoder.DecodedCount;
                }
            }
            _valueOffset = 0;
        }
        while (await MoveToNextContentNodeAsync(moveIfOnContentNode: true).ConfigureAwait(continueOnCapturedContext: false));
        _isEnd = true;
        return _decoder.DecodedCount;
    }
References System.Xml.ReadContentAsBinaryHelper._canReadValueChunk, System.Xml.ReadContentAsBinaryHelper._decoder, System.Xml.ReadContentAsBinaryHelper._isEnd, System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._valueChunk, System.Xml.ReadContentAsBinaryHelper._valueChunkLength, System.Xml.ReadContentAsBinaryHelper._valueOffset, System.buffer, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.Xml.IncrementalReadDecoder.Decode(), System.Xml.IncrementalReadDecoder.DecodedCount, System.Xml.Dictionary, System.Xml.XmlReader.GetValueAsync(), System.index, System.Xml.IncrementalReadDecoder.IsFull, System.Xml.ReadContentAsBinaryHelper.MoveToNextContentNodeAsync(), System.Xml.XmlReader.ReadValueChunkAsync(), System.Xml.ReadContentAsBinaryHelper.Reset(), System.Xml.IncrementalReadDecoder.SetNextOutputBuffer(), and System.text.
Referenced by System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64Async(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHexAsync(), and System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinaryAsync().