Terraria: System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBase64
ReadElementContentAsBase64()
int System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBase64 (byte[] buffer, int index, int count) inline package
Definition at line 144 of file ReadContentAsBinaryHelper.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        switch (_state)
        {
        case State.None:
            if (_reader.NodeType != XmlNodeType.Element)
            {
                throw _reader.CreateReadElementContentAsException("ReadElementContentAsBase64");
            }
            if (!InitOnElement())
            {
                return 0;
            }
            break;
        case State.InReadContent:
            throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
        case State.InReadElementContent:
            if (_decoder == _base64Decoder)
            {
                return ReadElementContentAsBinary(buffer, index, count);
            }
            break;
        default:
            return 0;
        }
        InitBase64Decoder();
        return ReadElementContentAsBinary(buffer, index, count);
    }
References System.Xml.ReadContentAsBinaryHelper._base64Decoder, System.Xml.ReadContentAsBinaryHelper._decoder, System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._state, System.buffer, System.count, System.Xml.XmlReader.CreateReadElementContentAsException(), System.index, System.Xml.ReadContentAsBinaryHelper.InitBase64Decoder(), System.Xml.ReadContentAsBinaryHelper.InitOnElement(), System.Xml.XmlReader.NodeType, System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinary(), and System.SR.Xml_MixingBinaryContentMethods.
Referenced by System.Xml.XPath.XPathNavigatorReader.ReadElementContentAsBase64(), System.Xml.XmlCharCheckingReader.ReadElementContentAsBase64(), System.Xml.XmlNodeReader.ReadElementContentAsBase64(), System.Xml.XmlValidatingReaderImpl.ReadElementContentAsBase64(), and System.Xml.XsdValidatingReader.ReadElementContentAsBase64().