Terraria: System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinary
ReadElementContentAsBinary()
int System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinary (byte[] buffer, int index, int count) inline private
Definition at line 366 of file ReadContentAsBinaryHelper.cs.
    {
        if (count == 0)
        {
            return 0;
        }
        int num = ReadContentAsBinary(buffer, index, count);
        if (num > 0)
        {
            return num;
        }
        if (_reader.NodeType != XmlNodeType.EndElement)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, _reader.NodeType.ToString(), _reader as IXmlLineInfo);
        }
        _reader.Read();
        _state = State.None;
        return 0;
    }
References System.Xml.ReadContentAsBinaryHelper._reader, System.Xml.ReadContentAsBinaryHelper._state, System.buffer, System.count, System.Xml.Dictionary, System.index, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinary(), System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBase64(), and System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHex().