Terraria: System.Diagnostics.Tracing.ManifestBuilder.TranslateToManifestConvention
TranslateToManifestConvention()
string System.Diagnostics.Tracing.ManifestBuilder.TranslateToManifestConvention (string eventMessage, string evtName) inline private
Definition at line 814 of file ManifestBuilder.cs.
    {
        StringBuilder stringBuilder = null;
        int num = 0;
        int i = 0;
        while (i < eventMessage.Length)
        {
            int num4;
            if (eventMessage[i] == '%')
            {
                UpdateStringBuilder(ref stringBuilder, eventMessage, num, i - num);
                stringBuilder.Append("%%");
                i++;
                num = i;
            }
            else if (i < eventMessage.Length - 1 && ((eventMessage[i] == '{' && eventMessage[i + 1] == '{') || (eventMessage[i] == '}' && eventMessage[i + 1] == '}')))
            {
                UpdateStringBuilder(ref stringBuilder, eventMessage, num, i - num);
                stringBuilder.Append(eventMessage[i]);
                i++;
                i++;
                num = i;
            }
            else if (eventMessage[i] == '{')
            {
                int num2 = i;
                i++;
                int num3 = 0;
                for (; i < eventMessage.Length && char.IsDigit(eventMessage[i]); i++)
                {
                    num3 = num3 * 10 + eventMessage[i] - 48;
                }
                if (i < eventMessage.Length && eventMessage[i] == '}')
                {
                    i++;
                    UpdateStringBuilder(ref stringBuilder, eventMessage, num, num2 - num);
                    int value = TranslateIndexToManifestConvention(num3, evtName);
                    stringBuilder.Append('%').Append(value);
                    if (i < eventMessage.Length && eventMessage[i] == '!')
                    {
                        i++;
                        stringBuilder.Append("%!");
                    }
                    num = i;
                }
                else
                {
                    ManifestError(SR.Format(SR.EventSource_UnsupportedMessageProperty, evtName, eventMessage));
                }
            }
            else if ((num4 = "&<>'\"\r\n\t".IndexOf(eventMessage[i])) >= 0)
            {
                UpdateStringBuilder(ref stringBuilder, eventMessage, num, i - num);
                i++;
                stringBuilder.Append(s_escapes[num4]);
                num = i;
            }
            else
            {
                i++;
            }
        }
        if (stringBuilder == null)
        {
            return eventMessage;
        }
        UpdateStringBuilder(ref stringBuilder, eventMessage, num, i - num);
        return stringBuilder.ToString();
    }
References System.SR.EventSource_UnsupportedMessageProperty, System.SR.Format(), System.Diagnostics.Tracing.ManifestBuilder.ManifestError(), System.Diagnostics.Tracing.ManifestBuilder.s_escapes, System.Diagnostics.Tracing.ManifestBuilder.TranslateIndexToManifestConvention(), System.Diagnostics.Tracing.ManifestBuilder.UpdateStringBuilder(), and System.value.
Referenced by System.Diagnostics.Tracing.ManifestBuilder.EndEvent(), and System.Diagnostics.Tracing.ManifestBuilder.GetLocalizedMessage().