Terraria: System.Diagnostics.Tracing.ManifestBuilder.GetOpcodeName
GetOpcodeName()
string System.Diagnostics.Tracing.ManifestBuilder.GetOpcodeName (EventOpcode opcode, string eventName) inline private
Definition at line 682 of file ManifestBuilder.cs.
    {
        switch (opcode)
        {
        case EventOpcode.Info:
            return "win:Info";
        case EventOpcode.Start:
            return "win:Start";
        case EventOpcode.Stop:
            return "win:Stop";
        case EventOpcode.DataCollectionStart:
            return "win:DC_Start";
        case EventOpcode.DataCollectionStop:
            return "win:DC_Stop";
        case EventOpcode.Extension:
            return "win:Extension";
        case EventOpcode.Reply:
            return "win:Reply";
        case EventOpcode.Resume:
            return "win:Resume";
        case EventOpcode.Suspend:
            return "win:Suspend";
        case EventOpcode.Send:
            return "win:Send";
        case EventOpcode.Receive:
            return "win:Receive";
        default:
        {
            if (opcodeTab == null || !opcodeTab.TryGetValue((int)opcode, out var value))
            {
                ManifestError(SR.Format(SR.EventSource_UndefinedOpcode, opcode, eventName), runtimeCritical: true);
                return null;
            }
            return value;
        }
        }
    }
References System.Diagnostics.Tracing.ManifestBuilder.eventName, System.SR.EventSource_UndefinedOpcode, System.SR.Format(), System.Diagnostics.Tracing.ManifestBuilder.ManifestError(), System.Diagnostics.Tracing.ManifestBuilder.opcodeTab, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Diagnostics.Tracing.ManifestBuilder.StartEvent().