Terraria: System.Threading.RegisteredWaitHandle.UnregisterPortable
UnregisterPortable()
bool System.Threading.RegisteredWaitHandle.UnregisterPortable (WaitHandle waitObject) inline private
Definition at line 169 of file RegisteredWaitHandle.cs.
    {
        s_callbackLock.Acquire();
        bool success = false;
        try
        {
            if (_unregisterCalled)
            {
                return false;
            }
            UserUnregisterWaitHandle = waitObject?.SafeWaitHandle;
            UserUnregisterWaitHandle?.DangerousAddRef(ref success);
            UserUnregisterWaitHandleValue = UserUnregisterWaitHandle?.DangerousGetHandle() ?? IntPtr.Zero;
            if (_unregistered)
            {
                SignalUserWaitHandle();
                return true;
            }
            if (IsBlocking)
            {
                _callbacksComplete = RentEvent();
            }
            else
            {
                _removed = RentEvent();
            }
        }
        catch (Exception)
        {
            if (_removed != null)
            {
                ReturnEvent(_removed);
                _removed = null;
            }
            else if (_callbacksComplete != null)
            {
                ReturnEvent(_callbacksComplete);
                _callbacksComplete = null;
            }
            UserUnregisterWaitHandleValue = IntPtr.Zero;
            if (success)
            {
                UserUnregisterWaitHandle?.DangerousRelease();
            }
            UserUnregisterWaitHandle = null;
            throw;
        }
        finally
        {
            _unregisterCalled = true;
            s_callbackLock.Release();
        }
        WaitThread.UnregisterWait(this);
        return true;
    }
References System.Threading.RegisteredWaitHandle._callbacksComplete, System.Threading.RegisteredWaitHandle._removed, System.Threading.RegisteredWaitHandle._unregisterCalled, System.Threading.RegisteredWaitHandle._unregistered, System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Threading.RegisteredWaitHandle.IsBlocking, System.Threading.RegisteredWaitHandle.RentEvent(), System.Threading.RegisteredWaitHandle.ReturnEvent(), System.Threading.RegisteredWaitHandle.s_callbackLock, System.Threading.WaitHandle.SafeWaitHandle, System.Threading.RegisteredWaitHandle.SignalUserWaitHandle(), System.Threading.RegisteredWaitHandle.UserUnregisterWaitHandle, System.Threading.RegisteredWaitHandle.UserUnregisterWaitHandleValue, System.Threading.RegisteredWaitHandle.WaitThread, and System.IntPtr.Zero.
Referenced by System.Threading.RegisteredWaitHandle.Unregister().