Terraria: System.Diagnostics.Tracing.ManifestBuilder.ManifestBuilder
ManifestBuilder()
System.Diagnostics.Tracing.ManifestBuilder.ManifestBuilder (string providerName, Guid providerGuid, string dllName, ResourceManager resources, EventManifestOptions flags) inline
Definition at line 63 of file ManifestBuilder.cs.
    {
        this.providerName = providerName;
        this.flags = flags;
        this.resources = resources;
        sb = new StringBuilder();
        events = new StringBuilder();
        templates = new StringBuilder();
        opcodeTab = new Dictionary<int, string>();
        stringTab = new Dictionary<string, string>();
        errors = new List<string>();
        perEventByteArrayArgIndices = new Dictionary<string, List<int>>();
        sb.AppendLine("<instrumentationManifest xmlns=\"http://schemas.microsoft.com/win/2004/08/events\">");
        sb.AppendLine(" <instrumentation xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:win=\"http://manifests.microsoft.com/win/2004/08/windows/events\">");
        sb.AppendLine("  <events xmlns=\"http://schemas.microsoft.com/win/2004/08/events\">");
        StringBuilder stringBuilder = sb;
        StringBuilder stringBuilder2 = stringBuilder;
        StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(27, 2, stringBuilder);
        handler.AppendLiteral("<provider name=\"");
        handler.AppendFormatted(providerName);
        handler.AppendLiteral("\" guid=\"{");
        handler.AppendFormatted(providerGuid);
        handler.AppendLiteral("}\"");
        stringBuilder2.Append(ref handler);
        if (dllName != null)
        {
            stringBuilder = sb;
            StringBuilder stringBuilder3 = stringBuilder;
            StringBuilder.AppendInterpolatedStringHandler handler2 = new StringBuilder.AppendInterpolatedStringHandler(39, 2, stringBuilder);
            handler2.AppendLiteral(" resourceFileName=\"");
            handler2.AppendFormatted(dllName);
            handler2.AppendLiteral("\" messageFileName=\"");
            handler2.AppendFormatted(dllName);
            handler2.AppendLiteral("\"");
            stringBuilder3.Append(ref handler2);
        }
        string value = providerName.Replace("-", "").Replace('.', '_');
        stringBuilder = sb;
        StringBuilder stringBuilder4 = stringBuilder;
        StringBuilder.AppendInterpolatedStringHandler handler3 = new StringBuilder.AppendInterpolatedStringHandler(11, 1, stringBuilder);
        handler3.AppendLiteral(" symbol=\"");
        handler3.AppendFormatted(value);
        handler3.AppendLiteral("\">");
        stringBuilder4.AppendLine(ref handler3);
    }
References System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendLine(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendLiteral(), System.Diagnostics.Tracing.ManifestBuilder.errors, System.Diagnostics.Tracing.ManifestBuilder.events, System.Diagnostics.Tracing.ManifestBuilder.flags, System.Diagnostics.Tracing.ManifestBuilder.opcodeTab, System.Diagnostics.Tracing.ManifestBuilder.perEventByteArrayArgIndices, System.Diagnostics.Tracing.ManifestBuilder.providerName, System.Diagnostics.Tracing.ManifestBuilder.resources, System.Diagnostics.Tracing.ManifestBuilder.sb, System.Diagnostics.Tracing.ManifestBuilder.stringTab, System.Diagnostics.Tracing.ManifestBuilder.templates, and System.value.