Terraria: System.Diagnostics.Tracing.ManifestBuilder.AppendKeywords
AppendKeywords()
void System.Diagnostics.Tracing.ManifestBuilder.AppendKeywords (StringBuilder sb, ulong keywords, string eventName) inline private
Definition at line 720 of file ManifestBuilder.cs.
    {
        keywords &= 0xFFFFFFFFFFFFFFFuL;
        bool flag = false;
        for (ulong num = 1uL; num != 0L; num <<= 1)
        {
            if ((keywords & num) != 0L)
            {
                string value = null;
                if ((keywordTab == null || !keywordTab.TryGetValue(num, out value)) && num >= 281474976710656L)
                {
                    value = string.Empty;
                }
                if (value == null)
                {
                    ManifestError(SR.Format(SR.EventSource_UndefinedKeyword, "0x" + num.ToString("x", CultureInfo.CurrentCulture), eventName), runtimeCritical: true);
                    value = string.Empty;
                }
                if (value.Length != 0)
                {
                    if (flag)
                    {
                        sb.Append(' ');
                    }
                    sb.Append(value);
                    flag = true;
                }
            }
        }
    }
References System.Text.StringBuilder.Append(), System.Globalization.CultureInfo.CurrentCulture, System.Diagnostics.Tracing.ManifestBuilder.eventName, System.SR.EventSource_UndefinedKeyword, System.SR.Format(), System.Diagnostics.Tracing.ManifestBuilder.keywordTab, System.L, System.Diagnostics.Tracing.ManifestBuilder.ManifestError(), System.Diagnostics.Tracing.ManifestBuilder.sb, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Diagnostics.Tracing.ManifestBuilder.StartEvent().