Terraria: System.Diagnostics.Tracing.ManifestBuilder.AddEventParameter
AddEventParameter()
void System.Diagnostics.Tracing.ManifestBuilder.AddEventParameter (Type type, string name) inline
Definition at line 262 of file ManifestBuilder.cs.
    {
        if (numParams == 0)
        {
            templates.Append("  <template tid=\"").Append(eventName).AppendLine("Args\">");
        }
        if (type == typeof(byte[]))
        {
            if (byteArrArgIndices == null)
            {
                byteArrArgIndices = new List<int>(4);
            }
            byteArrArgIndices.Add(numParams);
            numParams++;
            templates.Append("   <data name=\"").Append(name).AppendLine("Size\" inType=\"win:UInt32\"/>");
        }
        numParams++;
        templates.Append("   <data name=\"").Append(name).Append("\" inType=\"")
            .Append(GetTypeName(type))
            .Append('"');
        if ((type.IsArray || type.IsPointer) && type.GetElementType() == typeof(byte))
        {
            templates.Append(" length=\"").Append(name).Append("Size\"");
        }
        if (type.IsEnum && Enum.GetUnderlyingType(type) != typeof(ulong) && Enum.GetUnderlyingType(type) != typeof(long))
        {
            templates.Append(" map=\"").Append(type.Name).Append('"');
            if (mapsTab == null)
            {
                mapsTab = new Dictionary<string, Type>();
            }
            if (!mapsTab.ContainsKey(type.Name))
            {
                mapsTab.Add(type.Name, type);
            }
        }
        templates.AppendLine("/>");
    }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendLine(), System.Diagnostics.Tracing.ManifestBuilder.byteArrArgIndices, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Diagnostics.Tracing.ManifestBuilder.eventName, System.Diagnostics.Tracing.ManifestBuilder.GetTypeName(), System.Enum.GetUnderlyingType(), System.Diagnostics.Tracing.ManifestBuilder.mapsTab, System.Diagnostics.Tracing.ManifestBuilder.numParams, System.Diagnostics.Tracing.ManifestBuilder.templates, and System.type.