Terraria: System.Diagnostics.Tracing.ManifestBuilder.GetChannelName
GetChannelName()
string System.Diagnostics.Tracing.ManifestBuilder.GetChannelName (EventChannel channel, string eventName, string eventMessage) inline private
Definition at line 631 of file ManifestBuilder.cs.
    {
        if (channelTab == null || !channelTab.TryGetValue((int)channel, out var value))
        {
            if ((int)channel < 16)
            {
                ManifestError(SR.Format(SR.EventSource_UndefinedChannel, channel, eventName));
            }
            if (channelTab == null)
            {
                channelTab = new Dictionary<int, ChannelInfo>(4);
            }
            string text = channel.ToString();
            if (19 < (int)channel)
            {
                text = "Channel" + text;
            }
            AddChannel(text, (int)channel, GetDefaultChannelAttribute(channel));
            if (!channelTab.TryGetValue((int)channel, out value))
            {
                ManifestError(SR.Format(SR.EventSource_UndefinedChannel, channel, eventName));
            }
        }
        if (resources != null && eventMessage == null)
        {
            eventMessage = resources.GetString("event_" + eventName, CultureInfo.InvariantCulture);
        }
        if (value.Attribs.EventChannelType == EventChannelType.Admin && eventMessage == null)
        {
            ManifestError(SR.Format(SR.EventSource_EventWithAdminChannelMustHaveMessage, eventName, value.Name));
        }
        return value.Name;
    }
References System.Diagnostics.Tracing.ManifestBuilder.AddChannel(), System.Diagnostics.Tracing.ManifestBuilder.channelTab, System.Diagnostics.Tracing.ManifestBuilder.eventName, System.SR.EventSource_EventWithAdminChannelMustHaveMessage, System.SR.EventSource_UndefinedChannel, System.SR.Format(), System.Diagnostics.Tracing.ManifestBuilder.GetDefaultChannelAttribute(), System.Resources.ResourceManager.GetString(), System.Globalization.CultureInfo.InvariantCulture, System.Diagnostics.Tracing.ManifestBuilder.ManifestError(), System.Diagnostics.Tracing.ManifestBuilder.resources, System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Diagnostics.Tracing.ManifestBuilder.StartEvent().