Terraria: System.Diagnostics.Tracing.ManifestBuilder.CreateManifestString
CreateManifestString()
string System.Diagnostics.Tracing.ManifestBuilder.CreateManifestString () inline private
Definition at line 368 of file ManifestBuilder.cs.
    {
        Span<char> destination = stackalloc char[16];
        if (channelTab != null)
        {
            sb.AppendLine(" <channels>");
            List<KeyValuePair<int, ChannelInfo>> list = new List<KeyValuePair<int, ChannelInfo>>();
            foreach (KeyValuePair<int, ChannelInfo> item in channelTab)
            {
                list.Add(item);
            }
            list.Sort((KeyValuePair<int, ChannelInfo> p1, KeyValuePair<int, ChannelInfo> p2) => -Comparer<ulong>.Default.Compare(p1.Value.Keywords, p2.Value.Keywords));
            foreach (KeyValuePair<int, ChannelInfo> item2 in list)
            {
                int key = item2.Key;
                ChannelInfo value = item2.Value;
                string text = null;
                bool flag = false;
                string text2 = null;
                if (value.Attribs != null)
                {
                    EventChannelAttribute attribs = value.Attribs;
                    if (Enum.IsDefined(typeof(EventChannelType), attribs.EventChannelType))
                    {
                        text = attribs.EventChannelType.ToString();
                    }
                    flag = attribs.Enabled;
                }
                if (text2 == null)
                {
                    text2 = providerName + "/" + value.Name;
                }
                sb.Append("  <channel chid=\"").Append(value.Name).Append("\" name=\"")
                    .Append(text2)
                    .Append('"');
                WriteMessageAttrib(sb, "channel", value.Name, null);
                sb.Append(" value=\"").Append(key).Append('"');
                if (text != null)
                {
                    sb.Append(" type=\"").Append(text).Append('"');
                }
                sb.Append(" enabled=\"").Append(flag ? "true" : "false").Append('"');
                sb.AppendLine("/>");
            }
            sb.AppendLine(" </channels>");
        }
        if (taskTab != null)
        {
            sb.AppendLine(" <tasks>");
            List<int> list2 = new List<int>(taskTab.Keys);
            list2.Sort();
            foreach (int item3 in list2)
            {
                sb.Append("  <task");
                WriteNameAndMessageAttribs(sb, "task", taskTab[item3]);
                sb.Append(" value=\"").Append(item3).AppendLine("\"/>");
            }
            sb.AppendLine(" </tasks>");
        }
        if (mapsTab != null)
        {
            sb.AppendLine(" <maps>");
            foreach (Type value3 in mapsTab.Values)
            {
                bool flag2 = EventSource.IsCustomAttributeDefinedHelper(value3, typeof(FlagsAttribute), flags);
                string value2 = (flag2 ? "bitMap" : "valueMap");
                sb.Append("  <").Append(value2).Append(" name=\"")
                    .Append(value3.Name)
                    .AppendLine("\">");
                FieldInfo[] array = GetEnumFields(value3);
                bool flag3 = false;
                FieldInfo[] array2 = array;
                foreach (FieldInfo fieldInfo in array2)
                {
                    object rawConstantValue = fieldInfo.GetRawConstantValue();
                    if (rawConstantValue != null)
                    {
                        ulong num = ((!(rawConstantValue is ulong)) ? ((ulong)Convert.ToInt64(rawConstantValue)) : ((ulong)rawConstantValue));
                        if (!flag2 || ((num & (num - 1)) == 0L && num != 0L))
{
                            num.TryFormat(destination, out var charsWritten, "x");
                            Span<char> span = destination.Slice(0, charsWritten);
                            sb.Append("   <map value=\"0x").Append(span).Append('"');
                            WriteMessageAttrib(sb, "map", value3.Name + "." + fieldInfo.Name, fieldInfo.Name);
                            sb.AppendLine("/>");
                            flag3 = true;
                        }
                    }
                }
                if (!flag3)
                {
                    sb.Append("   <map value=\"0x0\"");
                    WriteMessageAttrib(sb, "map", value3.Name + ".None", "None");
                    sb.AppendLine("/>");
                }
                sb.Append("  </").Append(value2).AppendLine(">");
            }
            sb.AppendLine(" </maps>");
        }
        sb.AppendLine(" <opcodes>");
        List<int> list3 = new List<int>(opcodeTab.Keys);
        list3.Sort();
        foreach (int item4 in list3)
        {
            sb.Append("  <opcode");
            WriteNameAndMessageAttribs(sb, "opcode", opcodeTab[item4]);
            sb.Append(" value=\"").Append(item4).AppendLine("\"/>");
        }
        sb.AppendLine(" </opcodes>");
        if (keywordTab != null)
        {
            sb.AppendLine(" <keywords>");
            List<ulong> list4 = new List<ulong>(keywordTab.Keys);
            list4.Sort();
            foreach (ulong item5 in list4)
            {
                sb.Append("  <keyword");
                WriteNameAndMessageAttribs(sb, "keyword", keywordTab[item5]);
                item5.TryFormat(destination, out var charsWritten2, "x");
                Span<char> span2 = destination.Slice(0, charsWritten2);
                sb.Append(" mask=\"0x").Append(span2).AppendLine("\"/>");
            }
            sb.AppendLine(" </keywords>");
        }
        sb.AppendLine(" <events>");
        sb.Append(events);
        sb.AppendLine(" </events>");
        sb.AppendLine(" <templates>");
        if (templates.Length > 0)
        {
            sb.Append(templates);
        }
        else
        {
            sb.AppendLine("    <template tid=\"_empty\"></template>");
        }
        sb.AppendLine(" </templates>");
        sb.AppendLine("</provider>");
        sb.AppendLine("</events>");
        sb.AppendLine("</instrumentation>");
        sb.AppendLine("<localization>");
        string[] array3 = new string[stringTab.Keys.Count];
        stringTab.Keys.CopyTo(array3, 0);
        Array.Sort(array3, 0, array3.Length);
        CultureInfo currentUICulture = CultureInfo.CurrentUICulture;
        sb.Append(" <resources culture=\"").Append(currentUICulture.Name).AppendLine("\">");
        sb.AppendLine("  <stringTable>");
        string[] array4 = array3;
        foreach (string text3 in array4)
        {
            string localizedMessage = GetLocalizedMessage(text3, currentUICulture, etwFormat: true);
            sb.Append("   <string id=\"").Append(text3).Append("\" value=\"")
                .Append(localizedMessage)
                .AppendLine("\"/>");
        }
        sb.AppendLine("  </stringTable>");
        sb.AppendLine(" </resources>");
        sb.AppendLine("</localization>");
        sb.AppendLine("</instrumentationManifest>");
        return sb.ToString();
        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2070:UnrecognizedReflectionPattern", Justification = "Trimmer does not trim enums")]
        static FieldInfo[] GetEnumFields(Type localEnumType)
        {
            return localEnumType.GetFields(BindingFlags.DeclaredOnly | BindingFlags.Static | BindingFlags.Public);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendLine(), System.array, System.Diagnostics.Tracing.ManifestBuilder.channelTab, System.Globalization.CultureInfo.CurrentUICulture, System.destination, System.Diagnostics.Tracing.ManifestBuilder.events, System.Diagnostics.Tracing.ManifestBuilder.flags, System.Diagnostics.Tracing.ManifestBuilder.GetLocalizedMessage(), System.Diagnostics.Tracing.EventSource.IsCustomAttributeDefinedHelper(), System.Enum.IsDefined(), System.item, System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, System.Diagnostics.Tracing.ManifestBuilder.keywordTab, System.L, System.Text.StringBuilder.Length, System.list, System.Diagnostics.Tracing.ManifestBuilder.mapsTab, System.Diagnostics.Tracing.ManifestBuilder.opcodeTab, System.Diagnostics.Tracing.ManifestBuilder.providerName, System.Diagnostics.Tracing.ManifestBuilder.sb, System.Array.Sort(), System.Diagnostics.Tracing.ManifestBuilder.stringTab, System.Diagnostics.Tracing.ManifestBuilder.taskTab, System.Diagnostics.Tracing.ManifestBuilder.templates, System.text, System.Convert.ToInt64(), System.Text.StringBuilder.ToString(), System.value, System.Collections.Generic.Dictionary< TKey, TValue >.Values, System.Diagnostics.Tracing.ManifestBuilder.WriteMessageAttrib(), and System.Diagnostics.Tracing.ManifestBuilder.WriteNameAndMessageAttribs().
Referenced by System.Diagnostics.Tracing.ManifestBuilder.CreateManifest().