Terraria: System.Threading.RegisteredWaitHandle.SignalUserWaitHandle
SignalUserWaitHandle()
void System.Threading.RegisteredWaitHandle.SignalUserWaitHandle () inline private
Definition at line 225 of file RegisteredWaitHandle.cs.
    {
        SafeWaitHandle userUnregisterWaitHandle = UserUnregisterWaitHandle;
        IntPtr userUnregisterWaitHandleValue = UserUnregisterWaitHandleValue;
        try
        {
            if (userUnregisterWaitHandleValue != IntPtr.Zero && userUnregisterWaitHandleValue != InvalidHandleValue)
            {
                EventWaitHandle.Set(userUnregisterWaitHandle);
            }
        }
        finally
        {
            userUnregisterWaitHandle?.DangerousRelease();
            _callbacksComplete?.Set();
            _unregistered = true;
        }
    }
References System.Threading.RegisteredWaitHandle._callbacksComplete, System.Threading.RegisteredWaitHandle._unregistered, System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Threading.RegisteredWaitHandle.InvalidHandleValue, System.Threading.EventWaitHandle.Set(), System.Threading.RegisteredWaitHandle.UserUnregisterWaitHandle, System.Threading.RegisteredWaitHandle.UserUnregisterWaitHandleValue, and System.IntPtr.Zero.
Referenced by System.Threading.RegisteredWaitHandle.CompleteCallbackRequest(), System.Threading.RegisteredWaitHandle.OnRemoveWait(), and System.Threading.RegisteredWaitHandle.UnregisterPortable().