Terraria: System.Diagnostics.Tracing.ManifestBuilder.AddChannel
AddChannel()
void System.Diagnostics.Tracing.ManifestBuilder.AddChannel (string name, int value, EventChannelAttribute channelAttribute) inline
Definition at line 169 of file ManifestBuilder.cs.
    {
        EventChannel eventChannel = (EventChannel)value;
        if (value < 16 || value > 255)
        {
            ManifestError(SR.Format(SR.EventSource_EventChannelOutOfRange, name, value));
        }
        else if ((int)eventChannel >= 16 && (int)eventChannel <= 19 && channelAttribute != null && EventChannelToChannelType(eventChannel) != channelAttribute.EventChannelType)
        {
            ManifestError(SR.Format(SR.EventSource_ChannelTypeDoesNotMatchEventChannelValue, name, ((EventChannel)value).ToString()));
        }
        ulong channelKeyword = GetChannelKeyword(eventChannel, 0uL);
        if (channelTab == null)
        {
            channelTab = new Dictionary<int, ChannelInfo>(4);
        }
        channelTab[value] = new ChannelInfo
        {
            Name = name,
            Keywords = channelKeyword,
            Attribs = channelAttribute
        };
    }
References System.Diagnostics.Tracing.ManifestBuilder.channelTab, System.Diagnostics.Tracing.ManifestBuilder.EventChannelToChannelType(), System.SR.EventSource_ChannelTypeDoesNotMatchEventChannelValue, System.SR.EventSource_EventChannelOutOfRange, System.SR.Format(), System.Diagnostics.Tracing.ManifestBuilder.GetChannelKeyword(), System.Diagnostics.Tracing.ManifestBuilder.ManifestError(), System.Name, and System.value.
Referenced by System.Diagnostics.Tracing.ManifestBuilder.GetChannelName().