Terraria: System.Diagnostics.Tracing.ManifestBuilder.GetLocalizedMessage
GetLocalizedMessage()
string System.Diagnostics.Tracing.ManifestBuilder.GetLocalizedMessage (string key, CultureInfo ci, bool etwFormat) inline package
Definition at line 571 of file ManifestBuilder.cs.
    {
        string value = null;
        if (resources != null)
        {
            string @string = resources.GetString(key, ci);
            if (@string != null)
            {
                value = @string;
                if (etwFormat && key.StartsWith("event_", StringComparison.Ordinal))
                {
                    string evtName = key.Substring("event_".Length);
                    value = TranslateToManifestConvention(value, evtName);
                }
            }
        }
        if (etwFormat && value == null)
        {
            stringTab.TryGetValue(key, out value);
        }
        return value;
    }
References System.Resources.ResourceManager.GetString(), System.key, System.Diagnostics.Tracing.ManifestBuilder.resources, System.Diagnostics.Tracing.ManifestBuilder.stringTab, System.Diagnostics.Tracing.ManifestBuilder.TranslateToManifestConvention(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Diagnostics.Tracing.ManifestBuilder.CreateManifestString().