Terraria: System.Diagnostics.Tracing.ManifestBuilder.AddTask
AddTask()
void System.Diagnostics.Tracing.ManifestBuilder.AddTask (string name, int value) inline
Definition at line 125 of file ManifestBuilder.cs.
    {
        if ((flags & EventManifestOptions.Strict) != 0)
        {
            if (value <= 0 || value >= 65535)
            {
                ManifestError(SR.Format(SR.EventSource_IllegalTaskValue, name, value));
            }
            if (taskTab != null && taskTab.TryGetValue(value, out var value2) && !name.Equals(value2, StringComparison.Ordinal))
            {
                ManifestError(SR.Format(SR.EventSource_TaskCollision, name, value2, value));
            }
        }
        if (taskTab == null)
        {
            taskTab = new Dictionary<int, string>();
        }
        taskTab[value] = name;
    }
References System.SR.EventSource_IllegalTaskValue, System.SR.EventSource_TaskCollision, System.Diagnostics.Tracing.ManifestBuilder.flags, System.SR.Format(), System.Diagnostics.Tracing.ManifestBuilder.ManifestError(), System.Diagnostics.Tracing.ManifestBuilder.taskTab, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.