Terraria: System.Diagnostics.Tracing.ManifestBuilder.StartEvent
StartEvent()
void System.Diagnostics.Tracing.ManifestBuilder.StartEvent (string eventName, EventAttribute eventAttribute) inline
Definition at line 231 of file ManifestBuilder.cs.
    {
        this.eventName = eventName;
        numParams = 0;
        byteArrArgIndices = null;
        events.Append("  <event value=\"").Append(eventAttribute.EventId).Append("\" version=\"")
            .Append(eventAttribute.Version)
            .Append("\" level=\"");
        AppendLevelName(events, eventAttribute.Level);
        events.Append("\" symbol=\"").Append(eventName).Append('"');
        WriteMessageAttrib(events, "event", eventName, eventAttribute.Message);
        if (eventAttribute.Keywords != EventKeywords.None)
        {
            events.Append(" keywords=\"");
            AppendKeywords(events, (ulong)eventAttribute.Keywords, eventName);
            events.Append('"');
        }
        if (eventAttribute.Opcode != 0)
        {
            events.Append(" opcode=\"").Append(GetOpcodeName(eventAttribute.Opcode, eventName)).Append('"');
        }
        if (eventAttribute.Task != 0)
        {
            events.Append(" task=\"").Append(GetTaskName(eventAttribute.Task, eventName)).Append('"');
        }
        if (eventAttribute.Channel != 0)
        {
            events.Append(" channel=\"").Append(GetChannelName(eventAttribute.Channel, eventName, eventAttribute.Message)).Append('"');
        }
    }
References System.Text.StringBuilder.Append(), System.Diagnostics.Tracing.ManifestBuilder.AppendKeywords(), System.Diagnostics.Tracing.ManifestBuilder.AppendLevelName(), System.Diagnostics.Tracing.ManifestBuilder.byteArrArgIndices, System.Diagnostics.Tracing.ManifestBuilder.eventName, System.Diagnostics.Tracing.ManifestBuilder.events, System.Diagnostics.Tracing.ManifestBuilder.GetChannelName(), System.Diagnostics.Tracing.ManifestBuilder.GetOpcodeName(), System.Diagnostics.Tracing.ManifestBuilder.GetTaskName(), System.Diagnostics.Tracing.ManifestBuilder.numParams, and System.Diagnostics.Tracing.ManifestBuilder.WriteMessageAttrib().