Terraria: System.Threading.RegisteredWaitHandle.OnRemoveWait
OnRemoveWait()
void System.Threading.RegisteredWaitHandle.OnRemoveWait () inline package
Definition at line 263 of file RegisteredWaitHandle.cs.
    {
        s_callbackLock.Acquire();
        try
        {
            _removed?.Set();
            if (_numRequestedCallbacks == 0)
            {
                SignalUserWaitHandle();
            }
            else
            {
                _signalAfterCallbacksComplete = true;
            }
        }
        finally
        {
            s_callbackLock.Release();
        }
    }
References System.Threading.RegisteredWaitHandle._numRequestedCallbacks, System.Threading.RegisteredWaitHandle._removed, System.Threading.RegisteredWaitHandle._signalAfterCallbacksComplete, System.Threading.RegisteredWaitHandle.s_callbackLock, System.Threading.EventWaitHandle.Set(), and System.Threading.RegisteredWaitHandle.SignalUserWaitHandle().
Referenced by System.Threading.PortableThreadPool.WaitThread.ProcessRemovals().