Terraria: System.Threading.RegisteredWaitHandle.Unregister
Unregister()
bool System.Threading.RegisteredWaitHandle.Unregister (WaitHandle waitObject) inline
Definition at line 79 of file RegisteredWaitHandle.cs.
    {
        if (ThreadPool.UsePortableThreadPool)
        {
            return UnregisterPortable(waitObject);
        }
        s_callbackLock.Acquire();
        try
        {
            if (!IsValidHandle(_nativeRegisteredWaitHandle) || !UnregisterWaitNative(_nativeRegisteredWaitHandle, waitObject?.SafeWaitHandle))
            {
                return false;
            }
            _nativeRegisteredWaitHandle = InvalidHandleValue;
            if (_releaseHandle)
            {
                Handle.DangerousRelease();
                _releaseHandle = false;
            }
        }
        finally
        {
            s_callbackLock.Release();
        }
        GC.SuppressFinalize(this);
        return true;
    }
References System.Threading.RegisteredWaitHandle._nativeRegisteredWaitHandle, System.Threading.RegisteredWaitHandle._releaseHandle, System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Threading.RegisteredWaitHandle.Handle, System.Threading.RegisteredWaitHandle.InvalidHandleValue, System.Threading.RegisteredWaitHandle.IsValidHandle(), System.Threading.RegisteredWaitHandle.s_callbackLock, System.GC.SuppressFinalize(), System.Threading.RegisteredWaitHandle.UnregisterPortable(), System.Threading.RegisteredWaitHandle.UnregisterWaitNative(), and System.Threading.ThreadPool.UsePortableThreadPool.
Referenced by System.Net.NetworkInformation.Ping.UnregisterWaitHandle().