Terraria: System.Threading.RegisteredWaitHandle.ReturnEvent
ReturnEvent()
static void System.Threading.RegisteredWaitHandle.ReturnEvent (AutoResetEvent resetEvent) inline static private
Definition at line 156 of file RegisteredWaitHandle.cs.
    {
        if (Interlocked.CompareExchange(ref s_cachedEvent, resetEvent, null) != null)
        {
            resetEvent.Dispose();
        }
    }
References System.Threading.Interlocked.CompareExchange(), System.Threading.WaitHandle.Dispose(), and System.Threading.RegisteredWaitHandle.s_cachedEvent.
Referenced by System.Threading.RegisteredWaitHandle.UnregisterPortable(), System.Threading.RegisteredWaitHandle.WaitForCallbacks(), and System.Threading.RegisteredWaitHandle.WaitForRemoval().