Terraria: System.Diagnostics.Tracing.ManifestBuilder.WriteMessageAttrib
WriteMessageAttrib()
void System.Diagnostics.Tracing.ManifestBuilder.WriteMessageAttrib (StringBuilder stringBuilder, string elementName, string name, string value) inline private
Definition at line 541 of file ManifestBuilder.cs.
    {
        string text = null;
        if (resources != null)
        {
            text = elementName + "_" + name;
            string @string = resources.GetString(text, CultureInfo.InvariantCulture);
            if (@string != null)
            {
                value = @string;
            }
        }
        if (value != null)
        {
            if (text == null)
            {
                text = elementName + "_" + name;
            }
            stringBuilder.Append(" message=\"$(string.").Append(text).Append(")\"");
            if (stringTab.TryGetValue(text, out var value2) && !value2.Equals(value))
            {
                ManifestError(SR.Format(SR.EventSource_DuplicateStringKey, text), runtimeCritical: true);
            }
            else
            {
                stringTab[text] = value;
            }
        }
    }
References System.SR.EventSource_DuplicateStringKey, System.SR.Format(), System.Resources.ResourceManager.GetString(), System.Globalization.CultureInfo.InvariantCulture, System.Diagnostics.Tracing.ManifestBuilder.ManifestError(), System.Diagnostics.Tracing.ManifestBuilder.resources, System.Diagnostics.Tracing.ManifestBuilder.stringTab, System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Diagnostics.Tracing.ManifestBuilder.CreateManifestString(), System.Diagnostics.Tracing.ManifestBuilder.StartEvent(), and System.Diagnostics.Tracing.ManifestBuilder.WriteNameAndMessageAttribs().