Terraria: System.Threading.RegisteredWaitHandle.s_callbackLock
s_callbackLock
readonly LowLevelLock System.Threading.RegisteredWaitHandle.s_callbackLock = new LowLevelLock() static private
Definition at line 17 of file RegisteredWaitHandle.cs.
Referenced by System.Threading.RegisteredWaitHandle.~RegisteredWaitHandle(), System.Threading.RegisteredWaitHandle.CompleteCallbackRequest(), System.Threading.RegisteredWaitHandle.OnRemoveWait(), System.Threading.RegisteredWaitHandle.RequestCallback(), System.Threading.RegisteredWaitHandle.Unregister(), and System.Threading.RegisteredWaitHandle.UnregisterPortable().