Terraria: System.Diagnostics.Tracing.ManifestBuilder.AddKeyword
AddKeyword()
void System.Diagnostics.Tracing.ManifestBuilder.AddKeyword (string name, ulong value) inline
Definition at line 145 of file ManifestBuilder.cs.
    {
        if ((value & (value - 1)) != 0L)
        {
            ManifestError(SR.Format(SR.EventSource_KeywordNeedPowerOfTwo, "0x" + value.ToString("x", CultureInfo.CurrentCulture), name), runtimeCritical: true);
        }
        if ((flags & EventManifestOptions.Strict) != 0)
        {
            if (value >= 17592186044416L && !name.StartsWith("Session", StringComparison.Ordinal))
            {
                ManifestError(SR.Format(SR.EventSource_IllegalKeywordsValue, name, "0x" + value.ToString("x", CultureInfo.CurrentCulture)));
            }
            if (keywordTab != null && keywordTab.TryGetValue(value, out var value2) && !name.Equals(value2, StringComparison.Ordinal))
            {
                ManifestError(SR.Format(SR.EventSource_KeywordCollision, name, value2, "0x" + value.ToString("x", CultureInfo.CurrentCulture)));
            }
        }
        if (keywordTab == null)
        {
            keywordTab = new Dictionary<ulong, string>();
        }
        keywordTab[value] = name;
    }
References System.Globalization.CultureInfo.CurrentCulture, System.SR.EventSource_IllegalKeywordsValue, System.SR.EventSource_KeywordCollision, System.SR.EventSource_KeywordNeedPowerOfTwo, System.Diagnostics.Tracing.ManifestBuilder.flags, System.SR.Format(), System.Diagnostics.Tracing.ManifestBuilder.keywordTab, System.L, System.Diagnostics.Tracing.ManifestBuilder.ManifestError(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.