Terraria: System.Diagnostics.Tracing.ManifestBuilder.ManifestError
ManifestError()
void System.Diagnostics.Tracing.ManifestBuilder.ManifestError (string msg, bool runtimeCritical = false) inline
Definition at line 356 of file ManifestBuilder.cs.
    {
        if ((flags & EventManifestOptions.Strict) != 0)
        {
            errors.Add(msg);
        }
        else if (runtimeCritical)
        {
            throw new ArgumentException(msg);
        }
    }
References System.Diagnostics.Tracing.ManifestBuilder.errors, and System.Diagnostics.Tracing.ManifestBuilder.flags.
Referenced by System.Diagnostics.Tracing.ManifestBuilder.AddChannel(), System.Diagnostics.Tracing.ManifestBuilder.AddKeyword(), System.Diagnostics.Tracing.ManifestBuilder.AddOpcode(), System.Diagnostics.Tracing.ManifestBuilder.AddTask(), System.Diagnostics.Tracing.ManifestBuilder.AppendKeywords(), System.Diagnostics.Tracing.ManifestBuilder.GetChannelKeyword(), System.Diagnostics.Tracing.ManifestBuilder.GetChannelName(), System.Diagnostics.Tracing.ManifestBuilder.GetOpcodeName(), System.Diagnostics.Tracing.ManifestBuilder.GetTypeName(), System.Diagnostics.Tracing.ManifestBuilder.TranslateToManifestConvention(), and System.Diagnostics.Tracing.ManifestBuilder.WriteMessageAttrib().