Terraria: System.Xml.XmlDocument.GetDefaultAttribute
GetDefaultAttribute()
XmlAttribute System.Xml.XmlDocument.GetDefaultAttribute (XmlElement elem, string attrPrefix, string attrLocalname, string attrNamespaceURI) inline package
Definition at line 1561 of file XmlDocument.cs.
    {
        SchemaInfo dtdSchemaInfo = DtdSchemaInfo;
        SchemaElementDecl schemaElementDecl = GetSchemaElementDecl(elem);
        if (schemaElementDecl != null && schemaElementDecl.AttDefs != null)
        {
            foreach (KeyValuePair<XmlQualifiedName, SchemaAttDef> attDef in schemaElementDecl.AttDefs)
            {
                SchemaAttDef value = attDef.Value;
                if ((value.Presence == SchemaDeclBase.Use.Default || value.Presence == SchemaDeclBase.Use.Fixed) && value.Name.Name == attrLocalname && ((dtdSchemaInfo.SchemaType == SchemaType.DTD && value.Name.Namespace == attrPrefix) || (dtdSchemaInfo.SchemaType != SchemaType.DTD && value.Name.Namespace == attrNamespaceURI)))
                {
                    return PrepareDefaultAttribute(value, attrPrefix, attrLocalname, attrNamespaceURI);
                }
            }
        }
        return null;
    }
References System.Xml.XmlDocument.DtdSchemaInfo, System.Xml.XmlDocument.GetSchemaElementDecl(), System.Xml.XmlDocument.PrepareDefaultAttribute(), and System.value.
Referenced by System.Xml.XmlAttributeCollection.RemoveNodeAt().