Terraria: System.Xml.XmlDocument.CheckName
CheckName()
static void System.Xml.XmlDocument.CheckName (string name) inline static package
Definition at line 474 of file XmlDocument.cs.
    {
        int num = ValidateNames.ParseNmtoken(name, 0);
        if (num < name.Length)
        {
            throw new XmlException(System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(name, num));
        }
    }
References System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.ValidateNames.ParseNmtoken(), System.SR.Xml_BadNameChar, and System.Xml.XmlException.
Referenced by System.Xml.XmlAttribute.XmlAttribute(), and System.Xml.XmlElement.XmlElement().