Terraria: System.Xml.XmlDocument.CreateTextNode
CreateTextNode()
virtual XmlText System.Xml.XmlDocument.CreateTextNode (string? text) inline virtual
Definition at line 871 of file XmlDocument.cs.
    {
        return new XmlText(text, this);
    }
References System.text, and System.Xml.XmlText.
Referenced by System.Xml.XmlText.CloneNode(), System.Xml.XmlDataDocument.CloneNode(), System.Xml.XmlDocument.CreateNode(), System.Xml.Schema.Parser.CreateXmlNsAttribute(), System.Xml.XmlLoader.ExpandEntityReference(), System.Xml.XmlDataDocument.ForceFoliation(), System.Xml.XmlDocument.ImportNodeInternal(), System.Xml.Schema.Parser.LoadAttributeNode(), System.Xml.XmlLoader.LoadAttributeNode(), System.Xml.XmlLoader.LoadAttributeValue(), System.Xml.Schema.Parser.LoadEntityReferenceInAttribute(), System.Xml.XmlLoader.LoadEntityReferenceNode(), System.Xml.XmlLoader.LoadNode(), System.Xml.XmlDataDocument.OnColumnValueChanged(), System.Xml.Schema.Parser.ProcessAppInfoDocMarkup(), System.Xml.XmlDataDocument.ReplaceInitialChildText(), System.Xml.XmlText.SplitText(), System.Xml.DocumentSchemaValidator.ValidateAttributes(), System.Xml.DocumentSchemaValidator.ValidateElement(), System.Xml.DocumentXmlWriter.WriteEndAttribute(), System.Xml.DocumentXmlWriter.WriteEndNamespaceDeclaration(), and System.Xml.DocumentXmlWriter.WriteString().