Terraria: System.Xml.XmlDocument.GetElement
GetElement()
WeakReference< XmlElement > System.Xml.XmlDocument.GetElement (ArrayList elementList, XmlElement elem) inline private
Definition at line 542 of file XmlDocument.cs.
    {
        ArrayList arrayList = new ArrayList();
        foreach (WeakReference<XmlElement> element in elementList)
        {
            if (!element.TryGetTarget(out var target))
            {
                arrayList.Add(element);
            }
            else if (target == elem)
            {
                return element;
            }
        }
        foreach (WeakReference<XmlElement> item in arrayList)
        {
            elementList.Remove(item);
        }
        return null;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.item, and System.Collections.Generic.Dictionary< TKey, TValue >.Remove().
Referenced by System.Xml.XmlDocument.AddElementWithId(), and System.Xml.XmlDocument.RemoveElementWithId().