Terraria: System.Xml.XmlDocument.WriteContentTo
WriteContentTo()
override void System.Xml.XmlDocument.WriteContentTo (XmlWriter xw) inline
Definition at line 1417 of file XmlDocument.cs.
    {
        IEnumerator enumerator = GetEnumerator();
        try
        {
            while (enumerator.MoveNext())
            {
                XmlNode xmlNode = (XmlNode)enumerator.Current;
                xmlNode.WriteTo(xw);
            }
        }
        finally
        {
            IDisposable disposable = enumerator as IDisposable;
            if (disposable != null)
            {
                disposable.Dispose();
            }
        }
    }
References System.Xml.XmlNode.XmlNode(), and System.Xml.XmlNode.GetEnumerator().
Referenced by System.Xml.XmlDocument.WriteTo().