Terraria: System.Xml.XmlDocument.CreateNode
CreateNode() [3/3]
virtual XmlNode System.Xml.XmlDocument.CreateNode (XmlNodeType type, string? prefix, string name, string? namespaceURI) inline virtual
Definition at line 1157 of file XmlDocument.cs.
    {
        switch (type)
        {
        case XmlNodeType.Element:
            if (prefix != null)
            {
                return CreateElement(prefix, name, namespaceURI);
            }
            return CreateElement(name, namespaceURI);
        case XmlNodeType.Attribute:
            if (prefix != null)
            {
                return CreateAttribute(prefix, name, namespaceURI);
            }
            return CreateAttribute(name, namespaceURI);
        case XmlNodeType.Text:
            return CreateTextNode(string.Empty);
        case XmlNodeType.CDATA:
            return CreateCDataSection(string.Empty);
        case XmlNodeType.EntityReference:
            return CreateEntityReference(name);
        case XmlNodeType.ProcessingInstruction:
            return CreateProcessingInstruction(name, string.Empty);
        case XmlNodeType.XmlDeclaration:
            return CreateXmlDeclaration("1.0", null, null);
        case XmlNodeType.Comment:
            return CreateComment(string.Empty);
        case XmlNodeType.DocumentFragment:
            return CreateDocumentFragment();
        case XmlNodeType.DocumentType:
            return CreateDocumentType(name, string.Empty, string.Empty, string.Empty);
        case XmlNodeType.Document:
            return new XmlDocument();
        case XmlNodeType.SignificantWhitespace:
            return CreateSignificantWhitespace(string.Empty);
        case XmlNodeType.Whitespace:
            return CreateWhitespace(string.Empty);
        default:
            throw new ArgumentException(System.SR.Format(System.SR.Arg_CannotCreateNode, type));
        }
    }
References System.Xml.XmlDocument.XmlDocument(), System.SR.Arg_CannotCreateNode, System.Xml.ArgumentException, System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateCDataSection(), System.Xml.XmlDocument.CreateComment(), System.Xml.XmlDocument.CreateDocumentFragment(), System.Xml.XmlDocument.CreateDocumentType(), System.Xml.XmlDocument.CreateElement(), System.Xml.XmlDocument.CreateEntityReference(), System.Xml.XmlDocument.CreateProcessingInstruction(), System.Xml.XmlDocument.CreateSignificantWhitespace(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.XmlDocument.CreateWhitespace(), System.Xml.XmlDocument.CreateXmlDeclaration(), System.SR.Format(), System.prefix, and System.type.
Referenced by System.Xml.XmlDocument.CreateNode(), and System.Xml.XmlDocument.CreateNode().