Terraria: System.Xml.XmlDocument.ImportNodeInternal
ImportNodeInternal()
XmlNode System.Xml.XmlDocument.ImportNodeInternal (XmlNode node, bool deep) inline private
Definition at line 1050 of file XmlDocument.cs.
    {
        if (node == null)
        {
            throw new InvalidOperationException(System.SR.Xdom_Import_NullNode);
        }
        XmlNode xmlNode;
        switch (node.NodeType)
        {
        case XmlNodeType.Element:
            xmlNode = CreateElement(node.Prefix, node.LocalName, node.NamespaceURI);
            ImportAttributes(node, xmlNode);
            if (deep)
            {
                ImportChildren(node, xmlNode, deep);
            }
            break;
        case XmlNodeType.Attribute:
            xmlNode = CreateAttribute(node.Prefix, node.LocalName, node.NamespaceURI);
            ImportChildren(node, xmlNode, deep: true);
            break;
        case XmlNodeType.Text:
            xmlNode = CreateTextNode(node.Value);
            break;
        case XmlNodeType.Comment:
            xmlNode = CreateComment(node.Value);
            break;
        case XmlNodeType.ProcessingInstruction:
            xmlNode = CreateProcessingInstruction(node.Name, node.Value);
            break;
        case XmlNodeType.XmlDeclaration:
        {
            XmlDeclaration xmlDeclaration = (XmlDeclaration)node;
            xmlNode = CreateXmlDeclaration(xmlDeclaration.Version, xmlDeclaration.Encoding, xmlDeclaration.Standalone);
            break;
        }
        case XmlNodeType.CDATA:
            xmlNode = CreateCDataSection(node.Value);
            break;
        case XmlNodeType.DocumentType:
        {
            XmlDocumentType xmlDocumentType = (XmlDocumentType)node;
            xmlNode = CreateDocumentType(xmlDocumentType.Name, xmlDocumentType.PublicId, xmlDocumentType.SystemId, xmlDocumentType.InternalSubset);
            break;
        }
        case XmlNodeType.DocumentFragment:
            xmlNode = CreateDocumentFragment();
            if (deep)
            {
                ImportChildren(node, xmlNode, deep);
            }
            break;
        case XmlNodeType.EntityReference:
            xmlNode = CreateEntityReference(node.Name);
            break;
        case XmlNodeType.Whitespace:
            xmlNode = CreateWhitespace(node.Value);
            break;
        case XmlNodeType.SignificantWhitespace:
            xmlNode = CreateSignificantWhitespace(node.Value);
            break;
        default:
            throw new InvalidOperationException(System.SR.Format(CultureInfo.InvariantCulture, System.SR.Xdom_Import, node.NodeType));
        }
        return xmlNode;
    }
References System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateCDataSection(), System.Xml.XmlDocument.CreateComment(), System.Xml.XmlDocument.CreateDocumentFragment(), System.Xml.XmlDocument.CreateDocumentType(), System.Xml.XmlDocument.CreateElement(), System.Xml.XmlDocument.CreateEntityReference(), System.Xml.XmlDocument.CreateProcessingInstruction(), System.Xml.XmlDocument.CreateSignificantWhitespace(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.XmlDocument.CreateWhitespace(), System.Xml.XmlDocument.CreateXmlDeclaration(), System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlDocument.ImportAttributes(), System.Xml.XmlDocument.ImportChildren(), System.Globalization.CultureInfo.InvariantCulture, System.SR.Xdom_Import, System.SR.Xdom_Import_NullNode, and System.Xml.XmlDeclaration.
Referenced by System.Xml.XmlDocument.ImportAttributes(), System.Xml.XmlDocument.ImportChildren(), and System.Xml.XmlDocument.ImportNode().