Terraria: System.Xml.XmlDocument.GetSchemaElementDecl
GetSchemaElementDecl()
SchemaElementDecl System.Xml.XmlDocument.GetSchemaElementDecl (XmlElement elem) inline private
Definition at line 830 of file XmlDocument.cs.
    {
        SchemaInfo dtdSchemaInfo = DtdSchemaInfo;
        if (dtdSchemaInfo != null)
        {
            XmlQualifiedName key = new XmlQualifiedName(elem.LocalName, (dtdSchemaInfo.SchemaType == SchemaType.DTD) ? elem.Prefix : elem.NamespaceURI);
            if (dtdSchemaInfo.ElementDecls.TryGetValue(key, out var value))
            {
                return value;
            }
        }
        return null;
    }
References System.Xml.XmlDocument.DtdSchemaInfo, System.key, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.XmlDocument.AddDefaultAttributes(), and System.Xml.XmlDocument.GetDefaultAttribute().