Terraria: System.Xml.XmlDocument.ReadNode
ReadNode()
virtual ? XmlNode System.Xml.XmlDocument.ReadNode (XmlReader reader) inline virtual
Definition at line 1210 of file XmlDocument.cs.
    {
        XmlNode xmlNode = null;
        try
        {
            IsLoading = true;
            XmlLoader xmlLoader = new XmlLoader();
            return xmlLoader.ReadCurrentNode(this, reader);
        }
        finally
        {
            IsLoading = false;
        }
    }
References System.Xml.XmlDocument.IsLoading.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAndResolveUnknownXmlData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownXmlData(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNode(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNodes(), and System.Xml.Serialization.XmlSerializationReader.UnknownNode().