Terraria: System.Xml.XmlDocument.CreateAttribute
CreateAttribute() [1/3]
XmlAttribute System.Xml.XmlDocument.CreateAttribute (string name) inline
Definition at line 748 of file XmlDocument.cs.
    {
        string prefix = string.Empty;
        string localName = string.Empty;
        string namespaceURI = string.Empty;
        XmlNode.SplitName(name, out prefix, out localName);
        SetDefaultNamespace(prefix, localName, ref namespaceURI);
        return CreateAttribute(prefix, localName, namespaceURI);
    }
References System.Xml.XmlDocument.CreateAttribute(), System.prefix, System.Xml.XmlDocument.SetDefaultNamespace(), and System.Xml.XmlNode.SplitName().
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNamespaceDeclaration(), System.Xml.XmlDataDocument.CloneNode(), System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateNode(), System.Xml.Schema.Parser.CreateXmlNsAttribute(), System.Runtime.Serialization.SchemaExporter.ExportEmitDefaultValue(), System.Runtime.Serialization.SchemaExporter.ExportGenericInfo(), System.Xml.XmlDataDocument.ForceFoliation(), System.Xml.XmlDocument.ImportNodeInternal(), System.Xml.XmlDataDocument.Init(), System.Xml.Schema.Parser.LoadAttributeNode(), System.Xml.XmlLoader.LoadAttributeNode(), System.Xml.XmlDataDocument.OnColumnValueChanged(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNodes(), System.Xml.XmlElement.SetAttribute(), System.Xml.XmlElement.SetAttribute(), System.Xml.XmlElement.SetAttributeNode(), System.Xml.DocumentXmlWriter.WriteStartAttribute(), and System.Xml.DocumentXmlWriter.WriteStartNamespaceDeclaration().