Terraria: System.Security.AccessControl.RawSecurityDescriptor.CreateFromParts
CreateFromParts()
void System.Security.AccessControl.RawSecurityDescriptor.CreateFromParts (ControlFlags flags, SecurityIdentifier owner, SecurityIdentifier group, RawAcl systemAcl, RawAcl discretionaryAcl) inline private
Definition at line 87 of file RawSecurityDescriptor.cs.
    {
        SetFlags(flags);
        Owner = owner;
        Group = group;
        SystemAcl = systemAcl;
        DiscretionaryAcl = discretionaryAcl;
        ResourceManagerControl = 0;
    }
References System.Security.AccessControl.RawSecurityDescriptor.Group, System.Security.AccessControl.RawSecurityDescriptor.Owner, System.Security.AccessControl.RawSecurityDescriptor.ResourceManagerControl, and System.Security.AccessControl.RawSecurityDescriptor.SetFlags().
Referenced by System.Security.AccessControl.RawSecurityDescriptor.RawSecurityDescriptor(), and System.Security.AccessControl.RawSecurityDescriptor.RawSecurityDescriptor().