Terraria: System.Security.AccessControl.RawSecurityDescriptor.SetFlags
SetFlags()
void System.Security.AccessControl.RawSecurityDescriptor.SetFlags (ControlFlags flags) inline
Definition at line 189 of file RawSecurityDescriptor.cs.
    {
        _flags = flags | ControlFlags.SelfRelative;
    }
References System.Security.AccessControl.RawSecurityDescriptor._flags.
Referenced by System.Security.AccessControl.CommonSecurityDescriptor.AddControlFlags(), System.Security.AccessControl.RawSecurityDescriptor.CreateFromParts(), System.Security.AccessControl.CommonSecurityDescriptor.RemoveControlFlags(), and System.Security.AccessControl.CommonSecurityDescriptor.UpdateControlFlags().