Terraria: System.Security.AccessControl.RawSecurityDescriptor.BinaryFormFromSddlForm
BinaryFormFromSddlForm()
static byte[] System.Security.AccessControl.RawSecurityDescriptor.BinaryFormFromSddlForm (string sddlForm) inline static private
Definition at line 145 of file RawSecurityDescriptor.cs.
    {
        if (sddlForm == null)
        {
            throw new ArgumentNullException("sddlForm");
        }
        IntPtr resultSd = IntPtr.Zero;
        uint resultSdLength = 0u;
        byte[] array = null;
        try
        {
            if (!global::Interop.Advapi32.ConvertStringSdToSd(sddlForm, GenericSecurityDescriptor.Revision, out resultSd, ref resultSdLength))
            {
                int lastWin32Error = Marshal.GetLastWin32Error();
                switch (lastWin32Error)
                {
                case 87:
                case 1305:
                case 1336:
                case 1338:
                    throw new ArgumentException(System.SR.ArgumentException_InvalidSDSddlForm, "sddlForm");
                case 8:
                    throw new OutOfMemoryException();
                case 1337:
                    throw new ArgumentException(System.SR.AccessControl_InvalidSidInSDDLString, "sddlForm");
                default:
                    throw new Win32Exception(lastWin32Error, System.SR.Format(System.SR.AccessControl_UnexpectedError, lastWin32Error));
                case 0:
                    break;
                }
            }
            array = new byte[resultSdLength];
            Marshal.Copy(resultSd, array, 0, (int)resultSdLength);
            return array;
        }
        finally
        {
            if (resultSd != IntPtr.Zero)
            {
                Marshal.FreeHGlobal(resultSd);
            }
        }
    }
References System.SR.AccessControl_InvalidSidInSDDLString, System.SR.AccessControl_UnexpectedError, System.SR.ArgumentException_InvalidSDSddlForm, System.array, System.Runtime.InteropServices.Marshal.Copy(), System.SR.Format(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.Security.AccessControl.GenericSecurityDescriptor.Revision, and System.IntPtr.Zero.