Terraria: System.Security.AccessControl.NativeObjectSecurity.Persist
Persist() [8/8]
void System.Security.AccessControl.NativeObjectSecurity.Persist (string name, SafeHandle handle, AccessControlSections includeSections, object exceptionContext) inline private
Definition at line 128 of file NativeObjectSecurity.cs.
    {
        WriteLock();
        try
        {
            SecurityInfos securityInfos = (SecurityInfos)0;
            SecurityIdentifier owner = null;
            SecurityIdentifier group = null;
            SystemAcl sacl = null;
            DiscretionaryAcl dacl = null;
            if ((includeSections & AccessControlSections.Owner) != 0 && _securityDescriptor.Owner != null)
            {
                securityInfos |= SecurityInfos.Owner;
                owner = _securityDescriptor.Owner;
            }
            if ((includeSections & AccessControlSections.Group) != 0 && _securityDescriptor.Group != null)
            {
                securityInfos |= SecurityInfos.Group;
                group = _securityDescriptor.Group;
            }
            if ((includeSections & AccessControlSections.Audit) != 0)
            {
                securityInfos |= SecurityInfos.SystemAcl;
                sacl = ((!_securityDescriptor.IsSystemAclPresent || _securityDescriptor.SystemAcl == null || _securityDescriptor.SystemAcl.Count <= 0) ? null : _securityDescriptor.SystemAcl);
                securityInfos = (SecurityInfos)(((_securityDescriptor.ControlFlags & ControlFlags.SystemAclProtected) == 0) ? ((int)securityInfos | (int)UnprotectedSystemAcl) : ((int)securityInfos | (int)ProtectedSystemAcl));
            }
            if ((includeSections & AccessControlSections.Access) != 0 && _securityDescriptor.IsDiscretionaryAclPresent)
            {
                securityInfos |= SecurityInfos.DiscretionaryAcl;
                dacl = ((!_securityDescriptor.DiscretionaryAcl.EveryOneFullAccessForNullDacl) ? _securityDescriptor.DiscretionaryAcl : null);
                securityInfos = (SecurityInfos)(((_securityDescriptor.ControlFlags & ControlFlags.DiscretionaryAclProtected) == 0) ? ((int)securityInfos | (int)UnprotectedDiscretionaryAcl) : ((int)securityInfos | (int)ProtectedDiscretionaryAcl));
            }
            if (securityInfos == (SecurityInfos)0)
            {
                return;
            }
            int num = Win32.SetSecurityInfo(_resourceType, name, handle, securityInfos, owner, group, sacl, dacl);
            if (num != 0)
            {
                Exception ex = null;
                if (_exceptionFromErrorCode != null)
                {
                    ex = _exceptionFromErrorCode(num, name, handle, exceptionContext);
                }
                if (ex == null)
                {
                    ex = num switch
                    {
                        5 => new UnauthorizedAccessException(),
                        1307 => new InvalidOperationException(System.SR.AccessControl_InvalidOwner),
                        1308 => new InvalidOperationException(System.SR.AccessControl_InvalidGroup),
                        123 => new ArgumentException(System.SR.Argument_InvalidName, "name"),
                        6 => new NotSupportedException(System.SR.AccessControl_InvalidHandle),
                        2 => new FileNotFoundException(),
                        1350 => new NotSupportedException(System.SR.AccessControl_NoAssociatedSecurity),
                        _ => new InvalidOperationException(System.SR.Format(System.SR.AccessControl_UnexpectedError, num)),
                    };
                }
                throw ex;
            }
            base.OwnerModified = false;
            base.GroupModified = false;
            base.AccessRulesModified = false;
            base.AuditRulesModified = false;
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.Security.AccessControl.NativeObjectSecurity._exceptionFromErrorCode, System.Security.AccessControl.NativeObjectSecurity._resourceType, System.Security.AccessControl.ObjectSecurity< T >._securityDescriptor, System.SR.AccessControl_InvalidGroup, System.SR.AccessControl_InvalidHandle, System.SR.AccessControl_InvalidOwner, System.SR.AccessControl_NoAssociatedSecurity, System.SR.AccessControl_UnexpectedError, System.SR.Argument_InvalidName, System.Security.AccessControl.CommonSecurityDescriptor.ControlFlags, System.Security.AccessControl.CommonSecurityDescriptor.DiscretionaryAcl, System.Security.AccessControl.DiscretionaryAcl.EveryOneFullAccessForNullDacl, System.SR.Format(), System.Security.AccessControl.CommonSecurityDescriptor.Group, System.handle, System.Security.AccessControl.CommonSecurityDescriptor.IsDiscretionaryAclPresent, System.Security.AccessControl.CommonSecurityDescriptor.Owner, System.Security.AccessControl.NativeObjectSecurity.ProtectedDiscretionaryAcl, System.Security.AccessControl.NativeObjectSecurity.ProtectedSystemAcl, System.Security.AccessControl.Win32.SetSecurityInfo(), System.Security.AccessControl.CommonSecurityDescriptor.SystemAcl, System.Security.AccessControl.NativeObjectSecurity.UnprotectedDiscretionaryAcl, System.Security.AccessControl.NativeObjectSecurity.UnprotectedSystemAcl, System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().
Referenced by System.Security.AccessControl.NativeObjectSecurity.Persist(), System.Security.AccessControl.NativeObjectSecurity.Persist(), System.Security.AccessControl.NativeObjectSecurity.Persist(), and System.Security.AccessControl.NativeObjectSecurity.Persist().