Terraria: System.Security.Cryptography.Asn1.Pbkdf2Params.DecodeCore
DecodeCore() [2/2]
static void System.Security.Cryptography.Asn1.Pbkdf2Params.DecodeCore (ref System::Formats::Asn1::AsnValueReader reader, Asn1Tag expectedTag, ReadOnlyMemory< byte > rebind, out System::Security::Cryptography::Asn1::Pbkdf2Params decoded) inline static private
Definition at line 41 of file Pbkdf2Params.cs.
    {
        decoded = default(System.Security.Cryptography.Asn1.Pbkdf2Params);
        System.Formats.Asn1.AsnValueReader reader2 = reader.ReadSequence(expectedTag);
        System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.Decode(ref reader2, rebind, out decoded.Salt);
        if (!reader2.TryReadInt32(out decoded.IterationCount))
        {
            reader2.ThrowIfNotEmpty();
        }
        if (reader2.HasData && reader2.PeekTag().HasSameClassAndValue(Asn1Tag.Integer))
        {
            if (reader2.TryReadInt32(out var value))
            {
                decoded.KeyLength = value;
            }
            else
            {
                reader2.ThrowIfNotEmpty();
            }
        }
        if (reader2.HasData && reader2.PeekTag().HasSameClassAndValue(Asn1Tag.Sequence))
        {
            System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(ref reader2, rebind, out decoded.Prf);
        }
        else
        {
            System.Formats.Asn1.AsnValueReader reader3 = new System.Formats.Asn1.AsnValueReader(DefaultPrf, AsnEncodingRules.DER);
            System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(ref reader3, rebind, out decoded.Prf);
        }
        reader2.ThrowIfNotEmpty();
    }
References System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(), System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.Decode(), System.Security.Cryptography.Asn1.Pbkdf2Params.DefaultPrf, System.Formats.Asn1.AsnValueReader.HasData, System.Formats.Asn1.Asn1Tag.HasSameClassAndValue(), System.Formats.Asn1.Asn1Tag.Integer, System.Formats.Asn1.AsnValueReader.PeekTag(), System.Formats.Asn1.AsnValueReader.ReadSequence(), System.Formats.Asn1.Asn1Tag.Sequence, System.Formats.Asn1.AsnValueReader.ThrowIfNotEmpty(), System.Formats.Asn1.AsnValueReader.TryReadInt32(), and System.value.