Terraria: Terraria.Physics.BallCollision.IsPositionInsideTile
IsPositionInsideTile()
static bool Terraria.Physics.BallCollision.IsPositionInsideTile (Vector2 position, Point tileCoordinates, Tile tile) inline static private
Definition at line 125 of file BallCollision.cs.
    {
        if (tile.slope() == 0 && !tile.halfBrick())
        {
            return true;
        }
        Vector2 vector = position / 16f - new Vector2(tileCoordinates.X, tileCoordinates.Y);
        return tile.slope() switch
        {
            0 => vector.Y > 0.5f,
            1 => vector.Y > vector.X,
            2 => vector.Y > 1f - vector.X,
            3 => vector.Y < 1f - vector.X,
            4 => vector.Y < vector.X,
            _ => false,
        };
    }
References Terraria.Tile.halfBrick(), Terraria.Tile.slope(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Physics.BallCollision.CheckForPassThrough().