Terraria: System.Xml.Xsl.Runtime.XmlEmptySortKey.CompareTo
CompareTo() [1/3]
override int System.Xml.Xsl.Runtime.XmlEmptySortKey.CompareTo (object obj) inline
Definition at line 14 of file XmlEmptySortKey.cs.
    {
        if (!(obj is XmlEmptySortKey that))
        {
            return -(obj as XmlSortKey).CompareTo(this);
        }
        return BreakSortingTie(that);
    }
References System.Xml.Xsl.Runtime.XmlSortKey.BreakSortingTie(), System.Xml.Xsl.Runtime.XmlEmptySortKey.CompareTo(), System.Xml.Dictionary, and System.obj.
Referenced by System.Xml.Xsl.Runtime.XmlEmptySortKey.CompareTo().