Terraria: MinecartDiggerHelper.CorrectTrackConnections
CorrectTrackConnections()
void MinecartDiggerHelper.CorrectTrackConnections (Point startCoords, Point endCoords) inline private
     {
         GetExpectedDirections(startCoords, endCoords, out var expectedStartLeft, out var expectedStartRight, out var expectedEndLeft, out var expectedEndRight);
         Tile tileSafely = Framing.GetTileSafely(startCoords);
         Tile tileSafely2 = Framing.GetTileSafely(endCoords);
         if (tileSafely.active() && tileSafely.type == 314)
         {
             Minecart.TryFittingTileOrientation(startCoords, expectedStartLeft, expectedStartRight);
         }
         if (tileSafely2.active() && tileSafely2.type == 314)
         {
             Minecart.TryFittingTileOrientation(endCoords, expectedEndLeft, expectedEndRight);
         }
     }
References Tile.active(), GetExpectedDirections(), Framing.GetTileSafely(), Minecart.TryFittingTileOrientation(), and Tile.type.
Referenced by TryDigging().