Terraria: Terraria.Localization.LocalizedText.FormatWith
FormatWith()
string Terraria.Localization.LocalizedText.FormatWith (object obj) inline
    {
        string value = Value;
        PropertyDescriptorCollection properties = TypeDescriptor.GetProperties(obj);
        return _substitutionRegex.Replace(value, delegate(Match match)
        {
            if (match.Groups[1].Length != 0)
            {
                return "";
            }
            string name = match.Groups[2].ToString();
            PropertyDescriptor propertyDescriptor = properties.Find(name, ignoreCase: false);
            return (propertyDescriptor == null) ? "" : (propertyDescriptor.GetValue(obj) ?? "").ToString();
        });
    }
References Terraria.Localization.LocalizedText._substitutionRegex, Terraria.Localization.LocalizedText.ToString(), and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.GameContent.UI.GameTipsDisplay.GameTip.GameTip(), Terraria.Lang.AnglerQuestChat(), Terraria.Lang.AnglerQuestCountChat(), Terraria.Lang.BartenderHelpText(), Terraria.Lang.BestiaryGirlChat(), Terraria.Lang.BunnyChat(), Terraria.Lang.CatChat(), Terraria.Lang.DogChat(), Terraria.Lang.DyeTraderQuestChat(), Terraria.Localization.Language.GetTextValueWith(), Terraria.Lang.GolferChat(), Terraria.Main.HelpText(), Terraria.Lang.PrincessChat(), and Terraria.Lang.SlimeChat().