Terraria: Terraria.GameContent.RGB.DeathShader.ProcessLowDetail
ProcessLowDetail()
void Terraria.GameContent.RGB.DeathShader.ProcessLowDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 20 of file DeathShader.cs.
    {
        time *= 3f;
        float amount = 0f;
        float num = time % ((float)Math.PI * 4f);
        if (num < (float)Math.PI)
        {
            amount = (float)Math.Sin(num);
        }
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector4 vector = Vector4.Lerp(_primaryColor, _secondaryColor, amount);
            fragment.SetColor(i, vector);
        }
    }
References Terraria.GameContent.RGB.DeathShader._primaryColor, Terraria.GameContent.RGB.DeathShader._secondaryColor, ReLogic.Peripherals.RGB.Fragment.Count, Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.PI, ReLogic.Peripherals.RGB.Fragment.SetColor(), and System.Math.Sin().