Terraria: SmartInteractSystem.RunQuery
RunQuery()
void SmartInteractSystem.RunQuery (SmartInteractScanSettings settings) inline
     {
         Clear();
         foreach (ISmartInteractBlockReasonProvider blockProvider in _blockProviders)
         {
             if (blockProvider.ShouldBlockSmartInteract(settings))
             {
                 return;
             }
         }
         foreach (ISmartInteractCandidateProvider item in _candidateProvidersByOrderOfPriority)
         {
             if (item.ProvideCandidate(settings, out var candidate))
             {
                 _candidates.Add(candidate);
                 if (candidate.DistanceFromCursor == 0f)
                 {
                     break;
                 }
             }
         }
         ISmartInteractCandidate smartInteractCandidate = null;
         foreach (ISmartInteractCandidate candidate2 in _candidates)
         {
             if (smartInteractCandidate == null || smartInteractCandidate.DistanceFromCursor > candidate2.DistanceFromCursor)
             {
                 smartInteractCandidate = candidate2;
             }
         }
         smartInteractCandidate?.WinCandidacy();
     }
References _blockProviders, _candidateProvidersByOrderOfPriority, _candidates, Clear(), ISmartInteractCandidate.DistanceFromCursor, ISmartInteractCandidateProvider.ProvideCandidate(), ISmartInteractBlockReasonProvider.ShouldBlockSmartInteract(), and ISmartInteractCandidate.WinCandidacy().