Terraria: Film.AppendEmptySequence
AppendEmptySequence()
void Film.AppendEmptySequence (int duration) inline
     {
         AddSequence(_nextSequenceAppendTime, duration, EmptyFrameEvent);
     }
References _nextSequenceAppendTime, AddSequence(), and EmptyFrameEvent().
Referenced by DSTFilm.BuildSequence().