Terraria: System.Xml.XmlUTF8TextWriter.SetOutput
SetOutput() [1/2]
void System.Xml.XmlUTF8TextWriter.SetOutput (Stream stream, Encoding encoding, bool ownsStream) inline
Implements System.Xml.IXmlTextWriterInitializer.
Definition at line 10 of file XmlUTF8TextWriter.cs.
    {
        if (stream == null)
        {
            throw new ArgumentNullException("stream");
        }
        if (encoding == null)
        {
            throw new ArgumentNullException("encoding");
        }
        if (encoding.WebName != Encoding.UTF8.WebName)
        {
            stream = new EncodingStreamWrapper(stream, encoding, emitBOM: true);
        }
        if (_writer == null)
        {
            _writer = new XmlUTF8NodeWriter();
        }
        _writer.SetOutput(stream, ownsStream, encoding);
        SetOutput(_writer);
    }
References System.Xml.XmlUTF8TextWriter._writer, System.Xml.Dictionary, System.Xml.XmlUTF8NodeWriter.SetOutput(), System.Xml.XmlUTF8TextWriter.SetOutput(), System.stream, System.Text.Encoding.UTF8, and System.Text.Encoding.WebName.
Referenced by System.Xml.XmlUTF8TextWriter.SetOutput().