Terraria: UICharacterListItem.DeleteButtonClick
DeleteButtonClick()
void UICharacterListItem.DeleteButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         for (int i = 0; i < Main.PlayerList.Count; i++)
         {
             if (Main.PlayerList[i] == _data)
             {
                 SoundEngine.PlaySound(10);
                 Main.selectedPlayer = i;
                 Main.menuMode = 5;
                 break;
             }
         }
     }
References _data, Main.menuMode, Main.PlayerList, SoundEngine.PlaySound(), and Main.selectedPlayer.
Referenced by UICharacterListItem(), and FavoriteButtonClick().