Terraria: UICharacterListItem.RenameButtonClick
RenameButtonClick()
void UICharacterListItem.RenameButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         SoundEngine.PlaySound(10);
         Main.clrInput();
         UIVirtualKeyboard uIVirtualKeyboard = new UIVirtualKeyboard(Lang.menu[45].Value, "", OnFinishedSettingName, GoBackHere, 0, allowEmpty: true);
         uIVirtualKeyboard.SetMaxInputLength(20);
         Main.MenuUI.SetState(uIVirtualKeyboard);
         if (base.Parent.Parent is UIList uIList)
         {
             uIList.UpdateOrder();
         }
     }
References Main.clrInput(), GoBackHere(), Lang.menu, Main.MenuUI, OnFinishedSettingName(), SoundEngine.PlaySound(), UIVirtualKeyboard.SetMaxInputLength(), UserInterface.SetState(), and LocalizedText.Value.
Referenced by UICharacterListItem().