Terraria: UICharacterListItem.CloudMouseOver
CloudMouseOver()
void UICharacterListItem.CloudMouseOver (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         if (_data.IsCloudSave)
         {
             _buttonLabel.SetText(Language.GetTextValue("UI.MoveOffCloud"));
         }
         else
         {
             _buttonLabel.SetText(Language.GetTextValue("UI.MoveToCloud"));
         }
     }
References _buttonLabel, _data, Language.GetTextValue(), FileData.IsCloudSave, and UIText.SetText().
Referenced by UICharacterListItem().