Terraria: UICharacterListItem.DrawSelf
DrawSelf()
override void UICharacterListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         base.DrawSelf(spriteBatch);
         CalculatedStyle innerDimensions = GetInnerDimensions();
         CalculatedStyle dimensions = _playerPanel.GetDimensions();
         float num = dimensions.X + dimensions.Width;
         Color color = Color.White;
         string text = _data.Name;
         if (_data.Player.loadStatus != 0)
         {
             color = Color.Gray;
             string name = StatusID.Search.GetName(_data.Player.loadStatus);
             text = "(" + name + ") " + text;
         }
         Utils.DrawBorderString(spriteBatch, text, new Vector2(num + 6f, dimensions.Y - 2f), color);
         spriteBatch.Draw(_dividerTexture.Value, new Vector2(num, innerDimensions.Y + 21f), null, Color.White, 0f, Vector2.Zero, new Vector2((GetDimensions().X + GetDimensions().Width - num) / 8f, 1f), SpriteEffects.None, 0f);
         Vector2 vector = new Vector2(num + 6f, innerDimensions.Y + 29f);
         float num2 = 200f;
         Vector2 vector2 = vector;
         DrawPanel(spriteBatch, vector2, num2);
         spriteBatch.Draw(TextureAssets.Heart.Value, vector2 + new Vector2(5f, 2f), Color.White);
         vector2.X += 10f + (float)TextureAssets.Heart.Width();
         Utils.DrawBorderString(spriteBatch, _data.Player.statLifeMax + Language.GetTextValue("GameUI.PlayerLifeMax"), vector2 + new Vector2(0f, 3f), Color.White);
         vector2.X += 65f;
         spriteBatch.Draw(TextureAssets.Mana.Value, vector2 + new Vector2(5f, 2f), Color.White);
         vector2.X += 10f + (float)TextureAssets.Mana.Width();
         Utils.DrawBorderString(spriteBatch, _data.Player.statManaMax + Language.GetTextValue("GameUI.PlayerManaMax"), vector2 + new Vector2(0f, 3f), Color.White);
         vector.X += num2 + 5f;
         Vector2 vector3 = vector;
         float num3 = 140f;
         if (GameCulture.FromCultureName(GameCulture.CultureName.Russian).IsActive)
         {
             num3 = 180f;
         }
         DrawPanel(spriteBatch, vector3, num3);
         string text2 = "";
         Color color2 = Color.White;
         switch (_data.Player.difficulty)
         {
         case 0:
             text2 = Language.GetTextValue("UI.Softcore");
             break;
         case 1:
             text2 = Language.GetTextValue("UI.Mediumcore");
             color2 = Main.mcColor;
             break;
         case 2:
             text2 = Language.GetTextValue("UI.Hardcore");
             color2 = Main.hcColor;
             break;
         case 3:
             text2 = Language.GetTextValue("UI.Creative");
             color2 = Main.creativeModeColor;
             break;
         }
         vector3 += new Vector2(num3 * 0.5f - FontAssets.MouseText.Value.MeasureString(text2).X * 0.5f, 3f);
         Utils.DrawBorderString(spriteBatch, text2, vector3, color2);
         vector.X += num3 + 5f;
         Vector2 vector4 = vector;
         float num4 = innerDimensions.X + innerDimensions.Width - vector4.X;
         DrawPanel(spriteBatch, vector4, num4);
         TimeSpan playTime = _data.GetPlayTime();
         int num5 = playTime.Days * 24 + playTime.Hours;
         string text3 = ((num5 < 10) ? "0" : "") + num5 + playTime.ToString("\\:mm\\:ss");
         vector4 += new Vector2(num4 * 0.5f - FontAssets.MouseText.Value.MeasureString(text3).X * 0.5f, 3f);
         Utils.DrawBorderString(spriteBatch, text3, vector4, Color.White);
     }
References _data, _dividerTexture, _playerPanel, Color, Main.creativeModeColor, Player.difficulty, Utils.DrawBorderString(), DrawPanel(), GameCulture.FromCultureName(), UIElement.GetDimensions(), UIElement.GetInnerDimensions(), IdDictionary.GetName(), PlayerFileData.GetPlayTime(), Language.GetTextValue(), Main.hcColor, TextureAssets.Heart, GameCulture.IsActive, Player.loadStatus, TextureAssets.Mana, Main.mcColor, FontAssets.MouseText, FileData.Name, PlayerFileData.Player, StatusID.Search, Player.statLifeMax, Player.statManaMax, Asset< T >.Value, CalculatedStyle.Width, UIElement.Width, X, CalculatedStyle.X, and CalculatedStyle.Y.