Terraria: System.Runtime.InteropServices.ComEventsMethod.DelegateWrapper.Invoke
Invoke()
object System.Runtime.InteropServices.ComEventsMethod.DelegateWrapper.Invoke (object[] args) inline
Definition at line 26 of file ComEventsMethod.cs.
        {
            if ((object)Delegate == null)
            {
                return null;
            }
            if (!_once)
            {
                PreProcessSignature();
                _once = true;
            }
            if (_cachedTargetTypes != null && _expectedParamsCount == args.Length)
            {
                for (int i = 0; i < _expectedParamsCount; i++)
                {
                    Type type = _cachedTargetTypes[i];
                    if ((object)type != null)
                    {
                        args[i] = Enum.ToObject(type, args[i]);
                    }
                }
            }
            return Delegate.DynamicInvoke((!WrapArgs) ? args : new object[1] { args });
        }
References System.Runtime.InteropServices.ComEventsMethod.DelegateWrapper._cachedTargetTypes, System.Runtime.InteropServices.ComEventsMethod.DelegateWrapper._expectedParamsCount, System.Runtime.InteropServices.ComEventsMethod.DelegateWrapper._once, System.Delegate.DynamicInvoke(), System.Runtime.InteropServices.ComEventsMethod.DelegateWrapper.PreProcessSignature(), System.Enum.ToObject(), System.type, and System.Runtime.InteropServices.ComEventsMethod.DelegateWrapper.WrapArgs.