Terraria: System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetEditor
GetEditor()
object System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetEditor (object instance, Type editorBaseType) inline package
Definition at line 209 of file ReflectTypeDescriptionProvider.cs.
        {
            EditorAttribute editorAttribute;
            if (instance != null)
            {
                editorAttribute = GetEditorAttribute(TypeDescriptor.GetAttributes(_type), editorBaseType);
                EditorAttribute editorAttribute2 = GetEditorAttribute(TypeDescriptor.GetAttributes(instance), editorBaseType);
                if (editorAttribute != editorAttribute2)
                {
                    Type typeFromName = GetTypeFromName(editorAttribute2.EditorTypeName);
                    if (typeFromName != null && editorBaseType.IsAssignableFrom(typeFromName))
                    {
                        return CreateInstance(typeFromName, _type);
                    }
                }
            }
            lock (this)
            {
                for (int i = 0; i < _editorCount; i++)
                {
                    if (_editorTypes[i] == editorBaseType)
                    {
                        return _editors[i];
                    }
                }
            }
            object obj = null;
            editorAttribute = GetEditorAttribute(TypeDescriptor.GetAttributes(_type), editorBaseType);
            if (editorAttribute != null)
            {
                Type typeFromName2 = GetTypeFromName(editorAttribute.EditorTypeName);
                if (typeFromName2 != null && editorBaseType.IsAssignableFrom(typeFromName2))
                {
                    obj = CreateInstance(typeFromName2, _type);
                }
            }
            if (obj == null)
            {
                Hashtable editorTable = GetEditorTable(editorBaseType);
                if (editorTable != null)
                {
                    obj = GetIntrinsicTypeEditor(editorTable, _type);
                }
                if (obj != null && !editorBaseType.IsInstanceOfType(obj))
                {
                    obj = null;
                }
            }
            if (obj != null)
            {
                lock (this)
                {
                    if (_editorTypes == null || _editorTypes.Length == _editorCount)
                    {
                        int num = ((_editorTypes == null) ? 4 : (_editorTypes.Length * 2));
                        Type[] array = new Type[num];
                        object[] array2 = new object[num];
                        if (_editorTypes != null)
{
                            _editorTypes.CopyTo(array, 0);
                            _editors.CopyTo(array2, 0);
                        }
                        _editorTypes = array;
                        _editors = array2;
                        _editorTypes[_editorCount] = editorBaseType;
                        _editors[_editorCount++] = obj;
                    }
                }
            }
            return obj;
        }
References System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData._editorCount, System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData._editors, System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData._editorTypes, System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData._type, System.array, System.Reflection.CreateInstance, System.ComponentModel.TypeDescriptor.GetAttributes(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetEditorAttribute(), System.ComponentModel.ReflectTypeDescriptionProvider.GetEditorTable(), System.ComponentModel.ReflectTypeDescriptionProvider.GetIntrinsicTypeEditor(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetTypeFromName(), and System.obj.