Terraria: System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter
GetConverter()
TypeConverter System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter (object instance) inline package
Definition at line 138 of file ReflectTypeDescriptionProvider.cs.
        {
            TypeConverterAttribute typeConverterAttribute = null;
            if (instance != null)
            {
                typeConverterAttribute = (TypeConverterAttribute)TypeDescriptor.GetAttributes(_type)[typeof(TypeConverterAttribute)];
                TypeConverterAttribute typeConverterAttribute2 = (TypeConverterAttribute)TypeDescriptor.GetAttributes(instance)[typeof(TypeConverterAttribute)];
                if (typeConverterAttribute != typeConverterAttribute2)
                {
                    Type typeFromName = GetTypeFromName(typeConverterAttribute2.ConverterTypeName);
                    if (typeFromName != null && typeof(TypeConverter).IsAssignableFrom(typeFromName))
                    {
                        return (TypeConverter)CreateInstance(typeFromName, _type);
                    }
                }
            }
            if (_converter == null)
            {
                if (typeConverterAttribute == null)
                {
                    typeConverterAttribute = (TypeConverterAttribute)TypeDescriptor.GetAttributes(_type)[typeof(TypeConverterAttribute)];
                }
                if (typeConverterAttribute != null)
                {
                    Type typeFromName2 = GetTypeFromName(typeConverterAttribute.ConverterTypeName);
                    if (typeFromName2 != null && typeof(TypeConverter).IsAssignableFrom(typeFromName2))
                    {
                        _converter = (TypeConverter)CreateInstance(typeFromName2, _type);
                    }
                }
                if (_converter == null)
                {
                    _converter = GetIntrinsicTypeConverter(_type);
                }
            }
            return _converter;
        }
References System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData._converter, System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData._type, System.Reflection.CreateInstance, System.ComponentModel.TypeDescriptor.GetAttributes(), System.ComponentModel.ReflectTypeDescriptionProvider.GetIntrinsicTypeConverter(), and System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetTypeFromName().