Terraria: ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._setClientState
_setClientState()
void ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._setClientState (ClientState state) inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Invalid comparison between Unknown and I4
        if (_mClientState != state)
        {
            _mClientState = state;
            if ((int)state == 0 && OnConnectionBecameActive != null)
            {
                OnConnectionBecameActive();
            }
            if ((int)state == 2 && OnConnectionBecameInactive != null)
            {
                OnConnectionBecameInactive();
            }
        }
    }
References ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._mClientState, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.OnConnectionBecameActive, and ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.OnConnectionBecameInactive.
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._addGUIDefinedEvents(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._gamesenseWrk(), and ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.BeginConnection().