Terraria: ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.SendEvent
SendEvent() [1/2]
void ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.SendEvent (string fullEventJson) inline
Definition at line 490 of file GameSenseConnection.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Expected O, but got Unknown
        if (_isClientActive())
        {
            _mMsgQueue.PEnqueue((QueueMsg)new JsonMsg
            {
                JsonText = fullEventJson
            });
        }
    }
References ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._isClientActive(), and ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._mMsgQueue.
Referenced by ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.SendUpdatesForBindEvents(), and ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.UpdateDeviceList().