Terraria: ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._addGUIDefinedEvents
_addGUIDefinedEvents()
void ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._addGUIDefinedEvents () inline private
    {
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        if (GameName == null || GameDisplayName == null || Events == null)
        {
            _logWarning("Incomplete game registration form");
            _setClientState((ClientState)2);
        }
        else
        {
            RegisterGame(GameName, GameDisplayName, IconColor);
            RegisterEvents(Events);
        }
    }
References ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logWarning(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._setClientState(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.GameDisplayName, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.GameName, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.RegisterEvents(), and ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.RegisterGame().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.BeginConnection().