Terraria: ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendServer
_sendServer()
void ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendServer (Uri uri, string data) inline private
Definition at line 451 of file GameSenseConnection.cs.
    {
        byte[] bytes = Encoding.ASCII.GetBytes(data);
        HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(uri);
        httpWebRequest.ContentType = "application/json";
        httpWebRequest.Method = "POST";
        Stream requestStream = httpWebRequest.GetRequestStream();
        requestStream.Write(bytes, 0, bytes.Length);
        requestStream.Close();
        _currentRequest = httpWebRequest;
        try
        {
            ((HttpWebResponse)httpWebRequest.GetResponse()).Close();
        }
        catch
        {
        }
    }
References ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._currentRequest, System.Text.Encoding.ASCII, System.bytes, System.IO.Stream.Close(), System.Net.WebRequest.Create(), System.Net.HttpWebRequest.GetRequestStream(), System.Net.HttpWebRequest.GetResponse(), and System.IO.Stream.Write().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendMsg(), and ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.SendJson().