Terraria: ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._readProps
_readProps()
static string ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._readProps () inline static private
Definition at line 390 of file GameSenseConnection.cs.
    {
        string path = _getPropsPath();
        string result = null;
        try
        {
            if (File.Exists(path))
            {
                result = File.ReadAllText(path);
                return result;
            }
            _logErrorMsg("Could not read server props file, because it can't be found");
            return result;
        }
        catch (Exception e)
        {
            _logException("Could not read server props file", e);
            return result;
        }
    }
References ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._getPropsPath(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logErrorMsg(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logException(), System.IO.File.Exists(), and System.IO.File.ReadAllText().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._getServerPort().