Terraria: ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._gamesenseWrk
_gamesenseWrk()
void ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._gamesenseWrk () inline private
Definition at line 175 of file GameSenseConnection.cs.
    {
        //IL_0089: Expected O, but got Unknown
        //IL_00a5: Expected O, but got Unknown
        //IL_010c: Expected O, but got Unknown
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Expected I4, but got Unknown
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Expected O, but got Unknown
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Expected O, but got Unknown
        QueueMsg queueMsg = null;
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();
        while (_mGameSenseWrkShouldRun)
        {
            ClientState mClientState = _mClientState;
            switch ((int)mClientState)
            {
            case 0:
            {
                QueueMsg queueMsg2;
                while ((queueMsg2 = _mMsgQueue.CDequeue()) == null)
                {
                    Thread.Sleep(10);
                    if (stopwatch.ElapsedMilliseconds > 1000)
                    {
                        queueMsg2 = (QueueMsg)new QueueMsgSendHeartbeat();
                        queueMsg2.data = (object)new Game(GameName);
                        break;
                    }
                }
                try
                {
                    _sendMsg(queueMsg2);
                    stopwatch.Reset();
                    stopwatch.Start();
                }
                catch (ServerDownException val2)
                {
                    ServerDownException e2 = val2;
                    _logException("Failed connecting to GameSense server", (Exception)(object)e2);
                    queueMsg = queueMsg2;
                    _setClientState((ClientState)1);
                }
                catch (CriticalMessageIllFormedException val3)
                {
                    CriticalMessageIllFormedException e3 = val3;
                    _logException("Message ill-formed", (Exception)(object)e3);
                    _setClientState((ClientState)2);
                }
                catch (Exception e4)
                {
                    _logException("Failed processing msg", e4);
                }
                break;
            }
            case 1:
                _mServerPort = _getServerPort();
                if (_mServerPort == null)
                {
                    _logWarning("Failed to obtain GameSense server port. GameSense will not function");
                    _setClientState((ClientState)2);
                    break;
                }
                _initializeUris();
                if (queueMsg != null)
                {
                    try
                    {
                        _sendMsg(queueMsg);
                        queueMsg = null;
                    }
                    catch (ServerDownException val)
                    {
                        ServerDownException e = val;
                        _logException("Failed connecting to GameSense server", (Exception)(object)e);
                        _logDbgMsg("Retrying in 5 seconds...");
                        Thread.Sleep(5000);
                        break;
                    }
                }
                _setClientState((ClientState)0);
                break;
            case 2:
                _logDbgMsg("Entering inactive state");
                _mGameSenseWrkShouldRun = false;
                break;
            default:
                _logErrorMsg("Unknown GameSense client state");
                _setClientState((ClientState)2);
                break;
            }
        }
        _logDbgMsg("Worker exiting");
    }
References ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._getServerPort(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._initializeUris(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logDbgMsg(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logErrorMsg(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logException(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logWarning(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._mClientState, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._mGameSenseWrkShouldRun, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._mMsgQueue, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._mServerPort, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendMsg(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._setClientState(), System.Diagnostics.Stopwatch.ElapsedMilliseconds, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.GameName, System.Diagnostics.Stopwatch.Reset(), System.Threading.Thread.Sleep(), and System.Diagnostics.Stopwatch.Start().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.BeginConnection().