Terraria: ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendMsg
_sendMsg()
void ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendMsg (QueueMsg msg) inline private
Definition at line 313 of file GameSenseConnection.cs.
    {
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        string text = _toJSON(msg.data);
        JsonMsg jsonMsg = (JsonMsg)(object)((msg is JsonMsg) ? msg : null);
        if (jsonMsg != null)
        {
            text = jsonMsg.JsonText;
        }
        _logDbgMsg(text);
        try
        {
            _sendServer(msg.uri, text);
        }
        catch (WebException ex)
        {
            switch (ex.Status)
            {
            case WebExceptionStatus.ProtocolError:
                if (msg.IsCritical())
                {
                    Stream responseStream = ex.Response.GetResponseStream();
                    string text2 = new StreamReader(responseStream, Encoding.UTF8).ReadToEnd();
                    responseStream.Close();
                    throw new CriticalMessageIllFormedException(text2);
                }
                break;
            case WebExceptionStatus.ConnectFailure:
                throw new ServerDownException(ex.Message);
            default:
                _logException("Unexpected status", ex);
                break;
            }
        }
    }
References ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logDbgMsg(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logException(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendServer(), System.IO.Stream.Close(), System.Net.WebResponse.GetResponseStream(), System.Exception.Message, System.IO.StreamReader.ReadToEnd(), System.Net.WebException.Response, System.Net.WebException.Status, System.text, and System.Text.Encoding.UTF8.
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._gamesenseWrk().