Terraria: ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._getServerPort
_getServerPort()
static string ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._getServerPort () inline static private
Definition at line 411 of file GameSenseConnection.cs.
    {
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        string result = null;
        string text = _readProps();
        if (text != null)
        {
            try
            {
                JObject jObject = JObject.Parse(text);
                coreProps coreProps = default(coreProps);
                coreProps.address = (string)jObject.GetValue("address");
                string[] array = coreProps.address.Split(':');
                Convert.ToUInt16(array[1]);
                result = array[1];
                return result;
            }
            catch (Exception e)
            {
                _logException("Cannot parse port information", e);
                return result;
            }
        }
        return result;
    }
References ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logException(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._readProps(), System.array, System.text, and System.Convert.ToUInt16().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._gamesenseWrk().