Terraria: Terraria.TileColorCache.ApplyToBlock
ApplyToBlock()
void Terraria.TileColorCache.ApplyToBlock (Tile tile) inline
Definition at line 11 of file TileColorCache.cs.
    {
        tile.color(Color);
        tile.fullbrightBlock(FullBright);
        tile.invisibleBlock(Invisible);
    }
References Terraria.Tile.color(), Terraria.TileColorCache.FullBright, Terraria.Tile.fullbrightBlock(), Terraria.TileColorCache.Invisible, and Terraria.Tile.invisibleBlock().
Referenced by Terraria.Tile.UseBlockColors().