Terraria: System.Net.Http.HttpRequestOptions.Options
Options
Dictionary<string, object?> System.Net.Http.HttpRequestOptions.Options = new Dictionary<string, object>() get private
Definition at line 9 of file HttpRequestOptions.cs.
{ get; } = new Dictionary<string, object>();
Referenced by System.Net.Http.HttpRequestOptions.Add(), System.Net.Http.HttpRequestOptions.Add(), System.Net.Http.HttpRequestOptions.Clear(), System.Net.Http.HttpRequestOptions.Contains(), System.Net.Http.HttpRequestOptions.ContainsKey(), System.Net.Http.HttpRequestOptions.CopyTo(), System.Net.Http.HttpRequestOptions.GetEnumerator(), System.Net.Http.HttpRequestOptions.Remove(), System.Net.Http.HttpRequestOptions.Remove(), System.Net.Http.HttpRequestOptions.Set< TValue >(), System.Net.Http.HttpRequestOptions.TryGetValue(), and System.Net.Http.HttpRequestOptions.TryGetValue< TValue >().