Terraria: WorldFile.CreateMetadata
CreateMetadata()
static WorldFileData WorldFile.CreateMetadata (string name, bool cloudSave, int GameMode) inline static
     {
         WorldFileData worldFileData = new WorldFileData(Main.GetWorldPathFromName(name, cloudSave), cloudSave);
         if (Main.autoGenFileLocation != null && Main.autoGenFileLocation != "")
         {
             worldFileData = new WorldFileData(Main.autoGenFileLocation, cloudSave);
             Main.autoGenFileLocation = null;
         }
         worldFileData.Name = name;
         worldFileData.GameMode = GameMode;
         worldFileData.CreationTime = DateTime.Now;
         worldFileData.Metadata = FileMetadata.FromCurrentSettings(FileType.World);
         worldFileData.SetFavorite(favorite: false);
         worldFileData.WorldGeneratorVersion = 1198295875585uL;
         worldFileData.UniqueId = Guid.NewGuid();
         if (Main.DefaultSeed == "")
         {
             worldFileData.SetSeedToRandom();
         }
         else
         {
             worldFileData.SetSeed(Main.DefaultSeed);
         }
         return worldFileData;
     }
References Main.autoGenFileLocation, WorldFileData.CreationTime, Main.DefaultSeed, FileMetadata.FromCurrentSettings(), WorldFileData.GameMode, Main.GetWorldPathFromName(), FileData.Metadata, FileData.Name, FileData.SetFavorite(), WorldFileData.SetSeed(), WorldFileData.SetSeedToRandom(), WorldFileData.UniqueId, and WorldFileData.WorldGeneratorVersion.
Referenced by Main.DedServ(), UIWorldCreation.FinishCreatingWorld(), LoadWorld(), and Main.OnWorldNamed().