Terraria: WorldFile.LoadNPCs
LoadNPCs()
static void WorldFile.LoadNPCs (BinaryReader reader) inline static
     {
         if (_versionNumber >= 268)
         {
             int num = reader.ReadInt32();
             while (num-- > 0)
             {
                 NPC.ShimmeredTownNPCs[reader.ReadInt32()] = true;
             }
         }
         int num2 = 0;
         bool flag = reader.ReadBoolean();
         while (flag)
         {
             NPC nPC = Main.npc[num2];
             if (_versionNumber >= 190)
             {
                 nPC.SetDefaults(reader.ReadInt32());
             }
             else
             {
                 nPC.SetDefaults(NPCID.FromLegacyName(reader.ReadString()));
             }
             nPC.GivenName = reader.ReadString();
             nPC.position.X = reader.ReadSingle();
             nPC.position.Y = reader.ReadSingle();
             nPC.homeless = reader.ReadBoolean();
             nPC.homeTileX = reader.ReadInt32();
             nPC.homeTileY = reader.ReadInt32();
             if (_versionNumber >= 213 && ((BitsByte)reader.ReadByte())[0])
             {
                 nPC.townNpcVariationIndex = reader.ReadInt32();
             }
             num2++;
             flag = reader.ReadBoolean();
         }
         if (_versionNumber < 140)
         {
             return;
         }
         flag = reader.ReadBoolean();
         while (flag)
         {
             NPC nPC = Main.npc[num2];
             if (_versionNumber >= 190)
             {
                 nPC.SetDefaults(reader.ReadInt32());
             }
             else
             {
                 nPC.SetDefaults(NPCID.FromLegacyName(reader.ReadString()));
             }
             nPC.position = reader.ReadVector2();
             num2++;
             flag = reader.ReadBoolean();
         }
         if (_versionNumber < 251)
         {
             NPC.unlockedMerchantSpawn = NPC.AnyNPCs(17);
             NPC.unlockedDemolitionistSpawn = NPC.AnyNPCs(38);
             NPC.unlockedPartyGirlSpawn = NPC.AnyNPCs(208);
             NPC.unlockedDyeTraderSpawn = NPC.AnyNPCs(207);
             NPC.unlockedTruffleSpawn = NPC.AnyNPCs(160);
             NPC.unlockedArmsDealerSpawn = NPC.AnyNPCs(19);
             NPC.unlockedNurseSpawn = NPC.AnyNPCs(18);
             NPC.unlockedPrincessSpawn = NPC.AnyNPCs(663);
         }
     }
References _versionNumber, NPC.AnyNPCs(), NPCID.FromLegacyName(), NPC.GivenName, NPC.homeless, NPC.homeTileX, NPC.homeTileY, Main.npc, Entity.position, NPC.SetDefaults(), NPC.ShimmeredTownNPCs, NPC.townNpcVariationIndex, NPC.unlockedArmsDealerSpawn, NPC.unlockedDemolitionistSpawn, NPC.unlockedDyeTraderSpawn, NPC.unlockedMerchantSpawn, NPC.unlockedNurseSpawn, NPC.unlockedPartyGirlSpawn, NPC.unlockedPrincessSpawn, and NPC.unlockedTruffleSpawn.
Referenced by LoadWorld_Version2().