Terraria: WorldFile.LoadWorld
LoadWorld()
static void WorldFile.LoadWorld (bool loadFromCloud) inline static
     {
         Main.lockMenuBGChange = true;
         _isWorldOnCloud = loadFromCloud;
         Main.checkXMas();
         Main.checkHalloween();
         bool flag = loadFromCloud && SocialAPI.Cloud != null;
         if (!FileUtilities.Exists(Main.worldPathName, flag) && Main.autoGen)
         {
             if (!flag)
             {
                 for (int num = Main.worldPathName.Length - 1; num >= 0; num--)
                 {
                     if (Main.worldPathName.Substring(num, 1) == (Path.DirectorySeparatorChar.ToString() ?? ""))
                     {
                         Utils.TryCreatingDirectory(Main.worldPathName.Substring(0, num));
                         break;
                     }
                 }
             }
             WorldGen.clearWorld();
             Main.ActiveWorldFileData = CreateMetadata((Main.worldName == "") ? "World" : Main.worldName, flag, Main.GameMode);
             string text = (Main.AutogenSeedName ?? "").Trim();
             if (text.Length == 0)
             {
                 Main.ActiveWorldFileData.SetSeedToRandom();
             }
             else
             {
                 Main.ActiveWorldFileData.SetSeed(text);
             }
             UIWorldCreation.ProcessSpecialWorldSeeds(text);
             WorldGen.GenerateWorld(Main.ActiveWorldFileData.Seed, Main.AutogenProgress);
             SaveWorld();
         }
         try
         {
             using MemoryStream memoryStream = new MemoryStream(FileUtilities.ReadAllBytes(Main.worldPathName, flag));
             using BinaryReader binaryReader = new BinaryReader(memoryStream);
             try
             {
                 WorldGen.loadFailed = false;
                 WorldGen.loadSuccess = false;
                 int num2 = (_versionNumber = binaryReader.ReadInt32());
                 if (_versionNumber <= 0 || _versionNumber > 279)
                 {
                     WorldGen.loadFailed = true;
                     return;
                 }
                 int num3 = ((num2 > 87) ? LoadWorld_Version2(binaryReader) : LoadWorld_Version1_Old_BeforeRelease88(binaryReader));
                 if (num2 < 141)
                 {
                     if (!loadFromCloud)
                     {
                         Main.ActiveWorldFileData.CreationTime = File.GetCreationTime(Main.worldPathName);
                     }
                     else
                     {
                         Main.ActiveWorldFileData.CreationTime = DateTime.Now;
                     }
                 }
                 CheckSavedOreTiers();
                 binaryReader.Close();
                 memoryStream.Close();
                 if (num3 != 0)
                 {
                     WorldGen.loadFailed = true;
                 }
                 else
                 {
                     WorldGen.loadSuccess = true;
                 }
                 if (WorldGen.loadFailed || !WorldGen.loadSuccess)
                 {
                     return;
                 }
                 ConvertOldTileEntities();
                 ClearTempTiles();
                 WorldGen.gen = true;
                 GenVars.waterLine = Main.maxTilesY;
                 Liquid.QuickWater(2);
                 WorldGen.WaterCheck();
                 int num4 = 0;
                 Liquid.quickSettle = true;
                 int num5 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                 float num6 = 0f;
                 while (Liquid.numLiquid > 0 && num4 < 100000)
                 {
                     num4++;
                     float num7 = (float)(num5 - (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer)) / (float)num5;
                     if (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer > num5)
                     {
                         num5 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                     }
                     if (num7 > num6)
                     {
                         num6 = num7;
                     }
                     else
                     {
                         num7 = num6;
                     }
                     Main.statusText = Lang.gen[27].Value + " " + (int)(num7 * 100f / 2f + 50f) + "%";
                     Liquid.UpdateLiquid();
                 }
                 Liquid.quickSettle = false;
                 Main.weatherCounter = WorldGen.genRand.Next(3600, 18000);
                 Cloud.resetClouds();
                 WorldGen.WaterCheck();
                 WorldGen.gen = false;
                 NPC.setFireFlyChance();
                 if (Main.slimeRainTime > 0.0)
                 {
                     Main.StartSlimeRain(announce: false);
                 }
                 NPC.SetWorldSpecificMonstersByWorldID();
             }
             catch (Exception lastThrownLoadException)
             {
                 LastThrownLoadException = lastThrownLoadException;
                 WorldGen.loadFailed = true;
                 WorldGen.loadSuccess = false;
                 try
                 {
                     binaryReader.Close();
                     memoryStream.Close();
                     return;
                 }
                 catch
                 {
                     return;
                 }
             }
         }
         catch (Exception lastThrownLoadException2)
         {
             LastThrownLoadException = lastThrownLoadException2;
             WorldGen.loadFailed = true;
             WorldGen.loadSuccess = false;
             return;
         }
         if (WorldFile.OnWorldLoad != null)
         {
             WorldFile.OnWorldLoad();
         }
     }
References _isWorldOnCloud, _versionNumber, Main.ActiveWorldFileData, Main.autoGen, Main.AutogenProgress, Main.AutogenSeedName, Main.checkHalloween(), CheckSavedOreTiers(), Main.checkXMas(), ClearTempTiles(), WorldGen.clearWorld(), SocialAPI.Cloud, ConvertOldTileEntities(), CreateMetadata(), WorldFileData.CreationTime, FileUtilities.Exists(), Main.GameMode, Lang.gen, WorldGen.gen, WorldGen.GenerateWorld(), WorldGen.genRand, LastThrownLoadException, Liquid, WorldGen.loadFailed, WorldGen.loadSuccess, LoadWorld_Version1_Old_BeforeRelease88(), LoadWorld_Version2(), Main.lockMenuBGChange, Main.maxTilesY, UnifiedRandom.Next(), LiquidBuffer.numLiquidBuffer, OnWorldLoad, UIWorldCreation.ProcessSpecialWorldSeeds(), FileUtilities.ReadAllBytes(), Cloud.resetClouds(), SaveWorld(), WorldFileData.Seed, NPC.setFireFlyChance(), WorldFileData.SetSeed(), WorldFileData.SetSeedToRandom(), NPC.SetWorldSpecificMonstersByWorldID(), Main.slimeRainTime, Main.StartSlimeRain(), Main.statusText, Utils.TryCreatingDirectory(), LocalizedText.Value, WorldGen.WaterCheck(), GenVars.waterLine, Main.weatherCounter, Main.worldName, and Main.worldPathName.
Referenced by WorldGen.playWorldCallBack(), WorldGen.RenameWorldCallBack(), and WorldGen.serverLoadWorldCallBack().