Terraria: WorldFile.ConvertOldTileEntities
ConvertOldTileEntities()
static void WorldFile.ConvertOldTileEntities () inline static private
     {
         List<Point> list = new List<Point>();
         List<Point> list2 = new List<Point>();
         for (int i = 0; i < Main.maxTilesX; i++)
         {
             for (int j = 0; j < Main.maxTilesY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if ((tile.type == 128 || tile.type == 269) && tile.frameY == 0 && (tile.frameX % 100 == 0 || tile.frameX % 100 == 36))
                 {
                     list.Add(new Point(i, j));
                 }
                 if (tile.type == 334 && tile.frameY == 0 && tile.frameX % 54 == 0)
                 {
                     list2.Add(new Point(i, j));
                 }
                 if (tile.type == 49 && (tile.frameX == -1 || tile.frameY == -1))
                 {
                     tile.frameX = 0;
                     tile.frameY = 0;
                 }
             }
         }
         foreach (Point item in list)
         {
             if (!WorldGen.InWorld(item.X, item.Y, 5))
             {
                 continue;
             }
             int frameX = Main.tile[item.X, item.Y].frameX;
             int frameX2 = Main.tile[item.X, item.Y + 1].frameX;
             int frameX3 = Main.tile[item.X, item.Y + 2].frameX;
             for (int k = 0; k < 2; k++)
             {
                 for (int l = 0; l < 3; l++)
                 {
                     Tile tile2 = Main.tile[item.X + k, item.Y + l];
                     tile2.frameX %= 100;
                     if (tile2.type == 269)
                     {
                         tile2.frameX += 72;
                     }
                     tile2.type = 470;
                 }
             }
             int num = TEDisplayDoll.Place(item.X, item.Y);
             if (num != -1)
             {
                 (TileEntity.ByID[num] as TEDisplayDoll).SetInventoryFromMannequin(frameX, frameX2, frameX3);
             }
         }
         foreach (Point item2 in list2)
         {
             if (!WorldGen.InWorld(item2.X, item2.Y, 5))
             {
                 continue;
             }
             bool flag = Main.tile[item2.X, item2.Y].frameX >= 54;
             short frameX4 = Main.tile[item2.X, item2.Y + 1].frameX;
             int frameX5 = Main.tile[item2.X + 1, item2.Y + 1].frameX;
             bool flag2 = frameX4 >= 5000;
             int num2 = frameX4 % 5000;
             num2 -= 100;
             int prefix = frameX5 - ((frameX5 >= 25000) ? 25000 : 10000);
             for (int m = 0; m < 3; m++)
             {
                 for (int n = 0; n < 3; n++)
                 {
                     Tile tile3 = Main.tile[item2.X + m, item2.Y + n];
                     tile3.type = 471;
                     tile3.frameX = (short)((flag ? 54 : 0) + m * 18);
                     tile3.frameY = (short)(n * 18);
                 }
             }
             if (TEWeaponsRack.Place(item2.X, item2.Y) != -1 && flag2)
             {
                 TEWeaponsRack.TryPlacing(item2.X, item2.Y, num2, prefix, 1);
             }
         }
     }
References TileEntity.ByID, Tile.frameX, Tile.frameY, WorldGen.InWorld(), Main.maxTilesX, Main.maxTilesY, TEDisplayDoll.Place(), TEWeaponsRack.Place(), Main.tile, TEWeaponsRack.TryPlacing(), and Tile.type.
Referenced by LoadWorld().