Terraria: WorldFile.LoadWorld_LastMinuteFixes
LoadWorld_LastMinuteFixes()
static void WorldFile.LoadWorld_LastMinuteFixes () inline static private
     {
         if (_versionNumber < 258)
         {
             ConvertIlluminantPaintToNewField();
         }
         FixAgainstExploits();
     }
References _versionNumber, ConvertIlluminantPaintToNewField(), and FixAgainstExploits().
Referenced by LoadWorld_Version2().