Terraria: WorldFile.GetAllMetadata
GetAllMetadata()
static WorldFileData WorldFile.GetAllMetadata (string file, bool cloudSave) inline static
     {
         if (file == null || (cloudSave && SocialAPI.Cloud == null))
         {
             return null;
         }
         WorldFileData worldFileData = new WorldFileData(file, cloudSave);
         if (!FileUtilities.Exists(file, cloudSave))
         {
             return WorldFileData.FromInvalidWorld(file, cloudSave);
         }
         try
         {
             using Stream stream = (cloudSave ? ((Stream)new MemoryStream(SocialAPI.Cloud.Read(file))) : ((Stream)new FileStream(file, FileMode.Open)));
             using BinaryReader binaryReader = new BinaryReader(stream);
             int num = binaryReader.ReadInt32();
             if (num >= 135)
             {
                 worldFileData.Metadata = FileMetadata.Read(binaryReader, FileType.World);
             }
             else
             {
                 worldFileData.Metadata = FileMetadata.FromCurrentSettings(FileType.World);
             }
             if (num <= 279)
             {
                 binaryReader.ReadInt16();
                 stream.Position = binaryReader.ReadInt32();
                 worldFileData.Name = binaryReader.ReadString();
                 if (num >= 179)
                 {
                     string seed = ((num != 179) ? binaryReader.ReadString() : binaryReader.ReadInt32().ToString());
                     worldFileData.SetSeed(seed);
                     worldFileData.WorldGeneratorVersion = binaryReader.ReadUInt64();
                 }
                 else
                 {
                     worldFileData.SetSeedToEmpty();
                     worldFileData.WorldGeneratorVersion = 0uL;
                 }
                 if (num >= 181)
                 {
                     worldFileData.UniqueId = new Guid(binaryReader.ReadBytes(16));
                 }
                 else
                 {
                     worldFileData.UniqueId = Guid.Empty;
                 }
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 int y = binaryReader.ReadInt32();
                 int x = binaryReader.ReadInt32();
                 worldFileData.SetWorldSize(x, y);
                 if (num >= 209)
                 {
                     worldFileData.GameMode = binaryReader.ReadInt32();
                     if (num >= 222)
                     {
                         worldFileData.DrunkWorld = binaryReader.ReadBoolean();
                         if (num >= 227)
{
                             worldFileData.ForTheWorthy = binaryReader.ReadBoolean();
                         }
                         if (num >= 238)
{
                             worldFileData.Anniversary = binaryReader.ReadBoolean();
                         }
                         if (num >= 239)
{
                             worldFileData.DontStarve = binaryReader.ReadBoolean();
                         }
                         if (num >= 241)
{
                             worldFileData.NotTheBees = binaryReader.ReadBoolean();
                         }
                         if (num >= 249)
{
                             worldFileData.RemixWorld = binaryReader.ReadBoolean();
                         }
                         if (num >= 266)
{
                             worldFileData.NoTrapsWorld = binaryReader.ReadBoolean();
                         }
                         if (num >= 267)
{
                             worldFileData.ZenithWorld = binaryReader.ReadBoolean();
                         }
                         else
{
                             worldFileData.ZenithWorld = worldFileData.DrunkWorld && worldFileData.RemixWorld;
                         }
                     }
                 }
                 else if (num >= 112)
                 {
                     if (binaryReader.ReadBoolean())
                     {
                         worldFileData.GameMode = 1;
                     }
                     else
                     {
                         worldFileData.GameMode = 0;
                     }
                 }
                 if (num >= 141)
                 {
                     worldFileData.CreationTime = DateTime.FromBinary(binaryReader.ReadInt64());
                 }
                 else if (!cloudSave)
                 {
                     worldFileData.CreationTime = File.GetCreationTime(file);
                 }
                 else
                 {
                     worldFileData.CreationTime = DateTime.Now;
                 }
                 binaryReader.ReadByte();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadDouble();
                 binaryReader.ReadDouble();
                 binaryReader.ReadDouble();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadInt32();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 worldFileData.HasCrimson = binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 if (num >= 118)
                 {
                     binaryReader.ReadBoolean();
                 }
                 else
                     _ = 0;
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadByte();
                 binaryReader.ReadInt32();
                 worldFileData.IsHardMode = binaryReader.ReadBoolean();
                 if (num >= 257)
                 {
                     binaryReader.ReadBoolean();
                 }
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadDouble();
                 if (num >= 118)
                 {
                     binaryReader.ReadDouble();
                 }
                 if (num >= 113)
                 {
                     binaryReader.ReadByte();
                 }
                 binaryReader.ReadBoolean();
                 binaryReader.ReadInt32();
                 binaryReader.ReadSingle();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt32();
                 binaryReader.ReadByte();
                 binaryReader.ReadByte();
                 binaryReader.ReadByte();
                 binaryReader.ReadByte();
                 binaryReader.ReadByte();
                 binaryReader.ReadByte();
                 binaryReader.ReadByte();
                 binaryReader.ReadByte();
                 binaryReader.ReadInt32();
                 binaryReader.ReadInt16();
                 binaryReader.ReadSingle();
                 if (num < 95)
                 {
                     return worldFileData;
                 }
                 for (int num2 = binaryReader.ReadInt32(); num2 > 0; num2--)
                 {
                     binaryReader.ReadString();
                 }
                 if (num < 99)
                 {
                     return worldFileData;
                 }
                 binaryReader.ReadBoolean();
                 if (num < 101)
                 {
                     return worldFileData;
                 }
                 binaryReader.ReadInt32();
                 if (num < 104)
                 {
                     return worldFileData;
                 }
                 binaryReader.ReadBoolean();
                 if (num >= 129)
                 {
                     binaryReader.ReadBoolean();
                 }
                 if (num >= 201)
                 {
                     binaryReader.ReadBoolean();
                 }
                 if (num >= 107)
                 {
                     binaryReader.ReadInt32();
                 }
                 if (num >= 108)
                 {
                     binaryReader.ReadInt32();
                 }
                 if (num < 109)
                 {
                     return worldFileData;
                 }
                 int num3 = binaryReader.ReadInt16();
                 for (int i = 0; i < num3; i++)
                 {
                     binaryReader.ReadInt32();
                 }
                 if (num < 128)
                 {
                     return worldFileData;
                 }
                 binaryReader.ReadBoolean();
                 if (num < 131)
                 {
                     return worldFileData;
                 }
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 binaryReader.ReadBoolean();
                 worldFileData.DefeatedMoonlord = binaryReader.ReadBoolean();
                 return worldFileData;
             }
         }
         catch (Exception)
         {
         }
         return null;
     }
References WorldFileData.Anniversary, SocialAPI.Cloud, WorldFileData.CreationTime, WorldFileData.DefeatedMoonlord, WorldFileData.DontStarve, WorldFileData.DrunkWorld, FileUtilities.Exists(), WorldFileData.ForTheWorthy, FileMetadata.FromCurrentSettings(), WorldFileData.FromInvalidWorld(), WorldFileData.GameMode, WorldFileData.HasCrimson, WorldFileData.IsHardMode, FileData.Metadata, FileData.Name, WorldFileData.NoTrapsWorld, WorldFileData.NotTheBees, FileMetadata.Read(), CloudSocialModule.Read(), WorldFileData.RemixWorld, WorldFileData.SetSeed(), WorldFileData.SetSeedToEmpty(), WorldFileData.SetWorldSize(), WorldFileData.UniqueId, WorldFileData.WorldGeneratorVersion, and WorldFileData.ZenithWorld.
Referenced by Main.LoadDedConfig(), Main.LoadWorlds(), Main.SetWorld(), and UIWorkshopWorldImport.UpdateWorkshopWorldList().