Terraria: WorldFile.LoadFileFormatHeader
LoadFileFormatHeader()
static bool WorldFile.LoadFileFormatHeader (BinaryReader reader, out bool[] importance, out int[] positions) inline static
     {
         importance = null;
         positions = null;
         if ((_versionNumber = reader.ReadInt32()) >= 135)
         {
             try
             {
                 Main.WorldFileMetadata = FileMetadata.Read(reader, FileType.World);
             }
             catch (FormatException value)
             {
                 Console.WriteLine(Language.GetTextValue("Error.UnableToLoadWorld"));
                 Console.WriteLine(value);
                 return false;
             }
         }
         else
         {
             Main.WorldFileMetadata = FileMetadata.FromCurrentSettings(FileType.World);
         }
         short num = reader.ReadInt16();
         positions = new int[num];
         for (int i = 0; i < num; i++)
         {
             positions[i] = reader.ReadInt32();
         }
         ushort num2 = reader.ReadUInt16();
         importance = new bool[num2];
         byte b = 0;
         byte b2 = 128;
         for (int i = 0; i < num2; i++)
         {
             if (b2 == 128)
             {
                 b = reader.ReadByte();
                 b2 = 1;
             }
             else
             {
                 b2 <<= 1;
             }
             if ((b & b2) == b2)
             {
                 importance[i] = true;
             }
         }
         return true;
     }
References _versionNumber, FileMetadata.FromCurrentSettings(), Language.GetTextValue(), FileMetadata.Read(), and Main.WorldFileMetadata.
Referenced by LoadWorld_Version2(), and ValidateWorld().