Terraria: WorldFile.GetFileMetadata
GetFileMetadata()
static FileMetadata WorldFile.GetFileMetadata (string file, bool cloudSave) inline static
     {
         if (file == null)
         {
             return null;
         }
         try
         {
             byte[] buffer = null;
             int num;
             if (cloudSave)
             {
                 num = ((SocialAPI.Cloud != null) ? 1 : 0);
                 if (num != 0)
                 {
                     int num2 = 24;
                     buffer = new byte[num2];
                     SocialAPI.Cloud.Read(file, buffer, num2);
                 }
             }
             else
             {
                 num = 0;
             }
             using Stream input = ((num != 0) ? ((Stream)new MemoryStream(buffer)) : ((Stream)new FileStream(file, FileMode.Open)));
             using BinaryReader binaryReader = new BinaryReader(input);
             if (binaryReader.ReadInt32() >= 135)
             {
                 return FileMetadata.Read(binaryReader, FileType.World);
             }
             return FileMetadata.FromCurrentSettings(FileType.World);
         }
         catch
         {
         }
         return null;
     }
References SocialAPI.Cloud, FileMetadata.FromCurrentSettings(), FileMetadata.Read(), and CloudSocialModule.Read().
Referenced by IsValidWorld().