Terraria: MS.Internal.Xml.XPath.LogicalExpr.cmpNumberNumberO
cmpNumberNumberO()
static bool MS.Internal.Xml.XPath.LogicalExpr.cmpNumberNumberO (Operator::Op op, double n1, double n2) inline static private
Definition at line 316 of file LogicalExpr.cs.
    {
        return op switch
        {
            Operator.Op.LT => n1 < n2,
            Operator.Op.GT => n1 > n2,
            Operator.Op.LE => n1 <= n2,
            Operator.Op.GE => n1 >= n2,
            _ => false,
        };
    }
Referenced by MS.Internal.Xml.XPath.LogicalExpr.cmpBoolBoolO(), MS.Internal.Xml.XPath.LogicalExpr.cmpBoolNumberO(), MS.Internal.Xml.XPath.LogicalExpr.cmpBoolStringO(), MS.Internal.Xml.XPath.LogicalExpr.cmpQueryBoolO(), MS.Internal.Xml.XPath.LogicalExpr.cmpQueryStringO(), MS.Internal.Xml.XPath.LogicalExpr.cmpRtfBoolO(), MS.Internal.Xml.XPath.LogicalExpr.cmpRtfQueryO(), MS.Internal.Xml.XPath.LogicalExpr.cmpRtfRtfO(), MS.Internal.Xml.XPath.LogicalExpr.cmpRtfStringO(), and MS.Internal.Xml.XPath.LogicalExpr.cmpStringStringO().