Terraria: MS.Internal.Xml.XPath.LogicalExpr.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.LogicalExpr.Evaluate (XPathNodeIterator nodeIterator) inline
Definition at line 83 of file LogicalExpr.cs.
    {
        Operator.Op op = _op;
        object obj = _opnd1.Evaluate(nodeIterator);
        object obj2 = _opnd2.Evaluate(nodeIterator);
        int num = (int)GetXPathType(obj);
        int num2 = (int)GetXPathType(obj2);
        if (num < num2)
        {
            op = Operator.InvertOperator(op);
            object obj3 = obj;
            obj = obj2;
            obj2 = obj3;
            int num3 = num;
            num = num2;
            num2 = num3;
        }
        cmpXslt cmpXslt = ((op != Operator.Op.EQ && op != Operator.Op.NE) ? s_CompXsltO[num][num2] : s_CompXsltE[num][num2]);
        return cmpXslt(op, obj, obj2);
    }
References MS.Internal.Xml.XPath.LogicalExpr._op, MS.Internal.Xml.XPath.LogicalExpr._opnd1, MS.Internal.Xml.XPath.LogicalExpr._opnd2, MS.Internal.Xml.XPath.LogicalExpr.cmpXslt(), MS.Internal.Xml.XPath.Query.Evaluate(), MS.Internal.Xml.XPath.Query.GetXPathType(), MS.Internal.Xml.XPath.Operator.InvertOperator(), MS.Internal.Xml.XPath.LogicalExpr.s_CompXsltE, and MS.Internal.Xml.XPath.LogicalExpr.s_CompXsltO.