Terraria: WorldFile.ValidateWorld
ValidateWorld()
static bool WorldFile.ValidateWorld (BinaryReader fileIO) inline static
     {
         new Stopwatch().Start();
         try
         {
             Stream baseStream = fileIO.BaseStream;
             int num = fileIO.ReadInt32();
             if (num == 0 || num > 279)
             {
                 return false;
             }
             baseStream.Position = 0L;
             if (!LoadFileFormatHeader(fileIO, out var importance, out var positions))
             {
                 return false;
             }
             string text = fileIO.ReadString();
             if (num >= 179)
             {
                 if (num == 179)
                 {
                     fileIO.ReadInt32();
                 }
                 else
                 {
                     fileIO.ReadString();
                 }
                 fileIO.ReadUInt64();
             }
             if (num >= 181)
             {
                 fileIO.ReadBytes(16);
             }
             int num2 = fileIO.ReadInt32();
             fileIO.ReadInt32();
             fileIO.ReadInt32();
             fileIO.ReadInt32();
             fileIO.ReadInt32();
             int num3 = fileIO.ReadInt32();
             int num4 = fileIO.ReadInt32();
             baseStream.Position = positions[1];
             for (int i = 0; i < num4; i++)
             {
                 float num5 = (float)i / (float)Main.maxTilesX;
                 Main.statusText = Lang.gen[73].Value + " " + (int)(num5 * 100f + 1f) + "%";
                 int num6;
                 for (num6 = 0; num6 < num3; num6++)
                 {
                     byte b;
                     byte b2 = (b = 0);
                     byte b3 = fileIO.ReadByte();
                     bool flag = false;
                     if ((b3 & 1) == 1)
                     {
                         flag = true;
                         b2 = fileIO.ReadByte();
                     }
                     bool flag2 = false;
                     if (flag && (b2 & 1) == 1)
                     {
                         flag2 = true;
                         b = fileIO.ReadByte();
                     }
                     if (flag2 && (b & 1) == 1)
                     {
                         fileIO.ReadByte();
                     }
                     if ((b3 & 2) == 2)
                     {
                         int num7;
                         if ((b3 & 0x20) == 32)
{
                             byte b4 = fileIO.ReadByte();
                             num7 = fileIO.ReadByte();
                             num7 = (num7 << 8) | b4;
                         }
                         else
{
                             num7 = fileIO.ReadByte();
                         }
                         if (importance[num7])
{
                             fileIO.ReadInt16();
                             fileIO.ReadInt16();
                         }
                         if ((b & 8) == 8)
{
                             fileIO.ReadByte();
                         }
                     }
                     if ((b3 & 4) == 4)
                     {
                         fileIO.ReadByte();
                         if ((b & 0x10) == 16)
{
                             fileIO.ReadByte();
                         }
                     }
                     if ((b3 & 0x18) >> 3 != 0)
                     {
                         fileIO.ReadByte();
                     }
                     if ((b & 0x40) == 64)
                     {
                         fileIO.ReadByte();
                     }
                     num6 += (byte)((b3 & 0xC0) >> 6) switch
                     {
                         0 => 0,
                         1 => fileIO.ReadByte(),
                         _ => fileIO.ReadInt16(),
                     };
                 }
             }
             if (baseStream.Position != positions[2])
             {
                 return false;
             }
             int num8 = fileIO.ReadInt16();
             int num9 = fileIO.ReadInt16();
             for (int j = 0; j < num8; j++)
             {
                 fileIO.ReadInt32();
                 fileIO.ReadInt32();
                 fileIO.ReadString();
                 for (int k = 0; k < num9; k++)
                 {
                     if (fileIO.ReadInt16() > 0)
                     {
                         fileIO.ReadInt32();
                         fileIO.ReadByte();
                     }
                 }
             }
             if (baseStream.Position != positions[3])
             {
                 return false;
             }
             int num10 = fileIO.ReadInt16();
             for (int l = 0; l < num10; l++)
             {
                 fileIO.ReadString();
                 fileIO.ReadInt32();
                 fileIO.ReadInt32();
             }
             if (baseStream.Position != positions[4])
             {
                 return false;
             }
             ValidateLoadNPCs(fileIO);
             if (baseStream.Position != positions[5])
             {
                 return false;
             }
             if (_versionNumber >= 116 && _versionNumber <= 121)
             {
                 int num11 = fileIO.ReadInt32();
                 for (int m = 0; m < num11; m++)
                 {
                     fileIO.ReadInt16();
                     fileIO.ReadInt16();
                 }
                 if (baseStream.Position != positions[6])
                 {
                     return false;
                 }
             }
             if (_versionNumber >= 122)
             {
                 int num12 = fileIO.ReadInt32();
                 for (int n = 0; n < num12; n++)
                 {
                     TileEntity.Read(fileIO);
                 }
             }
             if (_versionNumber >= 170)
             {
                 int num13 = fileIO.ReadInt32();
                 for (int num14 = 0; num14 < num13; num14++)
                 {
                     fileIO.ReadInt64();
                 }
             }
             if (_versionNumber >= 189)
             {
                 int num15 = fileIO.ReadInt32();
                 fileIO.ReadBytes(12 * num15);
             }
             if (_versionNumber >= 210)
             {
                 Main.BestiaryTracker.ValidateWorld(fileIO, _versionNumber);
             }
             if (_versionNumber >= 220)
             {
                 CreativePowerManager.Instance.ValidateWorld(fileIO, _versionNumber);
             }
             bool num16 = fileIO.ReadBoolean();
             string text2 = fileIO.ReadString();
             int num17 = fileIO.ReadInt32();
             bool result = false;
             if (num16 && (text2 == text || num17 == num2))
             {
                 result = true;
             }
             return result;
         }
         catch (Exception value)
         {
             using (StreamWriter streamWriter = new StreamWriter("client-crashlog.txt", append: true))
             {
                 streamWriter.WriteLine(DateTime.Now);
                 streamWriter.WriteLine(value);
                 streamWriter.WriteLine("");
             }
             return false;
         }
     }
References _versionNumber, Main.BestiaryTracker, Lang.gen, CreativePowerManager.Instance, L, LoadFileFormatHeader(), Main.maxTilesX, TileEntity.Read(), Main.statusText, ValidateLoadNPCs(), BestiaryUnlocksTracker.ValidateWorld(), CreativePowerManager.ValidateWorld(), and LocalizedText.Value.
Referenced by InternalSaveWorld().