Terraria: WorldFile.SaveWorld_Version2
SaveWorld_Version2()
static void WorldFile.SaveWorld_Version2 (BinaryWriter writer) inline static
     {
         int[] pointers = new int[11]
         {
             SaveFileFormatHeader(writer),
             SaveWorldHeader(writer),
             SaveWorldTiles(writer),
             SaveChests(writer),
             SaveSigns(writer),
             SaveNPCs(writer),
             SaveTileEntities(writer),
             SaveWeightedPressurePlates(writer),
             SaveTownManager(writer),
             SaveBestiary(writer),
             SaveCreativePowers(writer)
         };
         SaveFooter(writer);
         SaveHeaderPointers(writer, pointers);
     }
References SaveBestiary(), SaveChests(), SaveCreativePowers(), SaveFileFormatHeader(), SaveFooter(), SaveHeaderPointers(), SaveNPCs(), SaveSigns(), SaveTileEntities(), SaveTownManager(), SaveWeightedPressurePlates(), SaveWorldHeader(), and SaveWorldTiles().
Referenced by InternalSaveWorld().