Terraria: MS.Internal.Xml.XPath.LogicalExpr.cmpBoolBoolE
cmpBoolBoolE() [1/2]
static bool MS.Internal.Xml.XPath.LogicalExpr.cmpBoolBoolE (Operator::Op op, bool n1, bool n2) inline static private
Definition at line 245 of file LogicalExpr.cs.
    {
        return op == Operator.Op.EQ == (n1 == n2);
    }
Referenced by MS.Internal.Xml.XPath.LogicalExpr.cmpBoolBoolE(), MS.Internal.Xml.XPath.LogicalExpr.cmpBoolNumberE(), MS.Internal.Xml.XPath.LogicalExpr.cmpBoolStringE(), MS.Internal.Xml.XPath.LogicalExpr.cmpQueryBoolE(), and MS.Internal.Xml.XPath.LogicalExpr.cmpRtfBoolE().