Terraria: MS.Internal.Xml.XPath.LogicalExpr.cmpNumberNumber
cmpNumberNumber() [1/2]
static bool MS.Internal.Xml.XPath.LogicalExpr.cmpNumberNumber (Operator::Op op, double n1, double n2) inline static private
Definition at line 302 of file LogicalExpr.cs.
    {
        return op switch
        {
            Operator.Op.LT => n1 < n2,
            Operator.Op.GT => n1 > n2,
            Operator.Op.LE => n1 <= n2,
            Operator.Op.GE => n1 >= n2,
            Operator.Op.EQ => n1 == n2,
            Operator.Op.NE => n1 != n2,
            _ => false,
        };
    }
Referenced by MS.Internal.Xml.XPath.LogicalExpr.cmpNumberNumber(), MS.Internal.Xml.XPath.LogicalExpr.cmpQueryNumber(), MS.Internal.Xml.XPath.LogicalExpr.cmpQueryQueryO(), MS.Internal.Xml.XPath.LogicalExpr.cmpRtfNumber(), and MS.Internal.Xml.XPath.LogicalExpr.cmpStringNumber().