Terraria: WorldFile.LoadHeader
LoadHeader()
static void WorldFile.LoadHeader (BinaryReader reader) inline static
     {
         int versionNumber = _versionNumber;
         Main.worldName = reader.ReadString();
         if (versionNumber >= 179)
         {
             string seed = ((versionNumber != 179) ? reader.ReadString() : reader.ReadInt32().ToString());
             Main.ActiveWorldFileData.SetSeed(seed);
             Main.ActiveWorldFileData.WorldGeneratorVersion = reader.ReadUInt64();
         }
         if (versionNumber >= 181)
         {
             Main.ActiveWorldFileData.UniqueId = new Guid(reader.ReadBytes(16));
         }
         else
         {
             Main.ActiveWorldFileData.UniqueId = Guid.NewGuid();
         }
         Main.worldID = reader.ReadInt32();
         Main.leftWorld = reader.ReadInt32();
         Main.rightWorld = reader.ReadInt32();
         Main.topWorld = reader.ReadInt32();
         Main.bottomWorld = reader.ReadInt32();
         Main.maxTilesY = reader.ReadInt32();
         Main.maxTilesX = reader.ReadInt32();
         WorldGen.clearWorld();
         if (versionNumber >= 209)
         {
             Main.GameMode = reader.ReadInt32();
             if (versionNumber >= 222)
             {
                 Main.drunkWorld = reader.ReadBoolean();
             }
             if (versionNumber >= 227)
             {
                 Main.getGoodWorld = reader.ReadBoolean();
             }
             if (versionNumber >= 238)
             {
                 Main.tenthAnniversaryWorld = reader.ReadBoolean();
             }
             if (versionNumber >= 239)
             {
                 Main.dontStarveWorld = reader.ReadBoolean();
             }
             if (versionNumber >= 241)
             {
                 Main.notTheBeesWorld = reader.ReadBoolean();
             }
             if (versionNumber >= 249)
             {
                 Main.remixWorld = reader.ReadBoolean();
             }
             if (versionNumber >= 266)
             {
                 Main.noTrapsWorld = reader.ReadBoolean();
             }
             if (versionNumber >= 267)
             {
                 Main.zenithWorld = reader.ReadBoolean();
             }
             else
             {
                 Main.zenithWorld = Main.remixWorld && Main.drunkWorld;
             }
         }
         else
         {
             if (versionNumber >= 112)
             {
                 Main.GameMode = (reader.ReadBoolean() ? 1 : 0);
             }
             else
             {
                 Main.GameMode = 0;
             }
             if (versionNumber == 208 && reader.ReadBoolean())
             {
                 Main.GameMode = 2;
             }
         }
         if (versionNumber >= 141)
         {
             Main.ActiveWorldFileData.CreationTime = DateTime.FromBinary(reader.ReadInt64());
         }
         Main.moonType = reader.ReadByte();
         Main.treeX[0] = reader.ReadInt32();
         Main.treeX[1] = reader.ReadInt32();
         Main.treeX[2] = reader.ReadInt32();
         Main.treeStyle[0] = reader.ReadInt32();
         Main.treeStyle[1] = reader.ReadInt32();
         Main.treeStyle[2] = reader.ReadInt32();
         Main.treeStyle[3] = reader.ReadInt32();
         Main.caveBackX[0] = reader.ReadInt32();
         Main.caveBackX[1] = reader.ReadInt32();
         Main.caveBackX[2] = reader.ReadInt32();
         Main.caveBackStyle[0] = reader.ReadInt32();
         Main.caveBackStyle[1] = reader.ReadInt32();
         Main.caveBackStyle[2] = reader.ReadInt32();
         Main.caveBackStyle[3] = reader.ReadInt32();
         Main.iceBackStyle = reader.ReadInt32();
         Main.jungleBackStyle = reader.ReadInt32();
         Main.hellBackStyle = reader.ReadInt32();
         Main.spawnTileX = reader.ReadInt32();
         Main.spawnTileY = reader.ReadInt32();
         Main.worldSurface = reader.ReadDouble();
         Main.rockLayer = reader.ReadDouble();
         _tempTime = reader.ReadDouble();
         _tempDayTime = reader.ReadBoolean();
         _tempMoonPhase = reader.ReadInt32();
         _tempBloodMoon = reader.ReadBoolean();
         _tempEclipse = reader.ReadBoolean();
         Main.eclipse = _tempEclipse;
         Main.dungeonX = reader.ReadInt32();
         Main.dungeonY = reader.ReadInt32();
         WorldGen.crimson = reader.ReadBoolean();
         NPC.downedBoss1 = reader.ReadBoolean();
         NPC.downedBoss2 = reader.ReadBoolean();
         NPC.downedBoss3 = reader.ReadBoolean();
         NPC.downedQueenBee = reader.ReadBoolean();
         NPC.downedMechBoss1 = reader.ReadBoolean();
         NPC.downedMechBoss2 = reader.ReadBoolean();
         NPC.downedMechBoss3 = reader.ReadBoolean();
         NPC.downedMechBossAny = reader.ReadBoolean();
         NPC.downedPlantBoss = reader.ReadBoolean();
         NPC.downedGolemBoss = reader.ReadBoolean();
         if (versionNumber >= 118)
         {
             NPC.downedSlimeKing = reader.ReadBoolean();
         }
         NPC.savedGoblin = reader.ReadBoolean();
         NPC.savedWizard = reader.ReadBoolean();
         NPC.savedMech = reader.ReadBoolean();
         NPC.downedGoblins = reader.ReadBoolean();
         NPC.downedClown = reader.ReadBoolean();
         NPC.downedFrost = reader.ReadBoolean();
         NPC.downedPirates = reader.ReadBoolean();
         WorldGen.shadowOrbSmashed = reader.ReadBoolean();
         WorldGen.spawnMeteor = reader.ReadBoolean();
         WorldGen.shadowOrbCount = reader.ReadByte();
         WorldGen.altarCount = reader.ReadInt32();
         Main.hardMode = reader.ReadBoolean();
         if (versionNumber >= 257)
         {
             Main.afterPartyOfDoom = reader.ReadBoolean();
         }
         else
         {
             Main.afterPartyOfDoom = false;
         }
         Main.invasionDelay = reader.ReadInt32();
         Main.invasionSize = reader.ReadInt32();
         Main.invasionType = reader.ReadInt32();
         Main.invasionX = reader.ReadDouble();
         if (versionNumber >= 118)
         {
             Main.slimeRainTime = reader.ReadDouble();
         }
         if (versionNumber >= 113)
         {
             Main.sundialCooldown = reader.ReadByte();
         }
         _tempRaining = reader.ReadBoolean();
         _tempRainTime = reader.ReadInt32();
         _tempMaxRain = reader.ReadSingle();
         WorldGen.SavedOreTiers.Cobalt = reader.ReadInt32();
         WorldGen.SavedOreTiers.Mythril = reader.ReadInt32();
         WorldGen.SavedOreTiers.Adamantite = reader.ReadInt32();
         WorldGen.setBG(0, reader.ReadByte());
         WorldGen.setBG(1, reader.ReadByte());
         WorldGen.setBG(2, reader.ReadByte());
         WorldGen.setBG(3, reader.ReadByte());
         WorldGen.setBG(4, reader.ReadByte());
         WorldGen.setBG(5, reader.ReadByte());
         WorldGen.setBG(6, reader.ReadByte());
         WorldGen.setBG(7, reader.ReadByte());
         Main.cloudBGActive = reader.ReadInt32();
         Main.cloudBGAlpha = (((double)Main.cloudBGActive < 1.0) ? 0f : 1f);
         Main.cloudBGActive = -WorldGen.genRand.Next(8640, 86400);
         Main.numClouds = reader.ReadInt16();
         Main.windSpeedTarget = reader.ReadSingle();
         Main.windSpeedCurrent = Main.windSpeedTarget;
         if (versionNumber < 95)
         {
             return;
         }
         Main.anglerWhoFinishedToday.Clear();
         for (int num = reader.ReadInt32(); num > 0; num--)
         {
             Main.anglerWhoFinishedToday.Add(reader.ReadString());
         }
         if (versionNumber < 99)
         {
             return;
         }
         NPC.savedAngler = reader.ReadBoolean();
         if (versionNumber < 101)
         {
             return;
         }
         Main.anglerQuest = reader.ReadInt32();
         if (versionNumber < 104)
         {
             return;
         }
         NPC.savedStylist = reader.ReadBoolean();
         if (versionNumber >= 129)
         {
             NPC.savedTaxCollector = reader.ReadBoolean();
         }
         if (versionNumber >= 201)
         {
             NPC.savedGolfer = reader.ReadBoolean();
         }
         if (versionNumber < 107)
         {
             if (Main.invasionType > 0 && Main.invasionSize > 0)
             {
                 Main.FakeLoadInvasionStart();
             }
         }
         else
         {
             Main.invasionSizeStart = reader.ReadInt32();
         }
         if (versionNumber < 108)
         {
             _tempCultistDelay = 86400;
         }
         else
         {
             _tempCultistDelay = reader.ReadInt32();
         }
         if (versionNumber < 109)
         {
             return;
         }
         int num2 = reader.ReadInt16();
         for (int i = 0; i < num2; i++)
         {
             if (i < NPCID.Count)
             {
                 NPC.killCount[i] = reader.ReadInt32();
             }
             else
             {
                 reader.ReadInt32();
             }
         }
         if (versionNumber < 128)
         {
             return;
         }
         Main.fastForwardTimeToDawn = reader.ReadBoolean();
         if (versionNumber < 131)
         {
             return;
         }
         NPC.downedFishron = reader.ReadBoolean();
         NPC.downedMartians = reader.ReadBoolean();
         NPC.downedAncientCultist = reader.ReadBoolean();
         NPC.downedMoonlord = reader.ReadBoolean();
         NPC.downedHalloweenKing = reader.ReadBoolean();
         NPC.downedHalloweenTree = reader.ReadBoolean();
         NPC.downedChristmasIceQueen = reader.ReadBoolean();
         NPC.downedChristmasSantank = reader.ReadBoolean();
         NPC.downedChristmasTree = reader.ReadBoolean();
         if (versionNumber < 140)
         {
             return;
         }
         NPC.downedTowerSolar = reader.ReadBoolean();
         NPC.downedTowerVortex = reader.ReadBoolean();
         NPC.downedTowerNebula = reader.ReadBoolean();
         NPC.downedTowerStardust = reader.ReadBoolean();
         NPC.TowerActiveSolar = reader.ReadBoolean();
         NPC.TowerActiveVortex = reader.ReadBoolean();
         NPC.TowerActiveNebula = reader.ReadBoolean();
         NPC.TowerActiveStardust = reader.ReadBoolean();
         NPC.LunarApocalypseIsUp = reader.ReadBoolean();
         if (NPC.TowerActiveSolar)
         {
             NPC.ShieldStrengthTowerSolar = NPC.ShieldStrengthTowerMax;
         }
         if (NPC.TowerActiveVortex)
         {
             NPC.ShieldStrengthTowerVortex = NPC.ShieldStrengthTowerMax;
         }
         if (NPC.TowerActiveNebula)
         {
             NPC.ShieldStrengthTowerNebula = NPC.ShieldStrengthTowerMax;
         }
         if (NPC.TowerActiveStardust)
         {
             NPC.ShieldStrengthTowerStardust = NPC.ShieldStrengthTowerMax;
         }
         if (versionNumber < 170)
         {
             _tempPartyManual = false;
             _tempPartyGenuine = false;
             _tempPartyCooldown = 0;
             TempPartyCelebratingNPCs.Clear();
         }
         else
         {
             _tempPartyManual = reader.ReadBoolean();
             _tempPartyGenuine = reader.ReadBoolean();
             _tempPartyCooldown = reader.ReadInt32();
             int num3 = reader.ReadInt32();
             TempPartyCelebratingNPCs.Clear();
             for (int j = 0; j < num3; j++)
             {
                 TempPartyCelebratingNPCs.Add(reader.ReadInt32());
             }
         }
         if (versionNumber < 174)
         {
             _tempSandstormHappening = false;
             _tempSandstormTimeLeft = 0;
             _tempSandstormSeverity = 0f;
             _tempSandstormIntendedSeverity = 0f;
         }
         else
         {
             _tempSandstormHappening = reader.ReadBoolean();
             _tempSandstormTimeLeft = reader.ReadInt32();
             _tempSandstormSeverity = reader.ReadSingle();
             _tempSandstormIntendedSeverity = reader.ReadSingle();
         }
         DD2Event.Load(reader, versionNumber);
         if (versionNumber > 194)
         {
             WorldGen.setBG(8, reader.ReadByte());
         }
         else
         {
             WorldGen.setBG(8, 0);
         }
         if (versionNumber >= 215)
         {
             WorldGen.setBG(9, reader.ReadByte());
         }
         else
         {
             WorldGen.setBG(9, 0);
         }
         if (versionNumber > 195)
         {
             WorldGen.setBG(10, reader.ReadByte());
             WorldGen.setBG(11, reader.ReadByte());
             WorldGen.setBG(12, reader.ReadByte());
         }
         else
         {
             WorldGen.setBG(10, WorldGen.treeBG1);
             WorldGen.setBG(11, WorldGen.treeBG1);
             WorldGen.setBG(12, WorldGen.treeBG1);
         }
         if (versionNumber >= 204)
         {
             NPC.combatBookWasUsed = reader.ReadBoolean();
         }
         if (versionNumber < 207)
         {
             _tempLanternNightCooldown = 0;
             _tempLanternNightGenuine = false;
             _tempLanternNightManual = false;
             _tempLanternNightNextNightIsGenuine = false;
         }
         else
         {
             _tempLanternNightCooldown = reader.ReadInt32();
             _tempLanternNightGenuine = reader.ReadBoolean();
             _tempLanternNightManual = reader.ReadBoolean();
             _tempLanternNightNextNightIsGenuine = reader.ReadBoolean();
         }
         WorldGen.TreeTops.Load(reader, versionNumber);
         if (versionNumber >= 212)
         {
             Main.forceHalloweenForToday = reader.ReadBoolean();
             Main.forceXMasForToday = reader.ReadBoolean();
         }
         else
         {
             Main.forceHalloweenForToday = false;
             Main.forceXMasForToday = false;
         }
         if (versionNumber >= 216)
         {
             WorldGen.SavedOreTiers.Copper = reader.ReadInt32();
             WorldGen.SavedOreTiers.Iron = reader.ReadInt32();
             WorldGen.SavedOreTiers.Silver = reader.ReadInt32();
             WorldGen.SavedOreTiers.Gold = reader.ReadInt32();
         }
         else
         {
             WorldGen.SavedOreTiers.Copper = -1;
             WorldGen.SavedOreTiers.Iron = -1;
             WorldGen.SavedOreTiers.Silver = -1;
             WorldGen.SavedOreTiers.Gold = -1;
         }
         if (versionNumber >= 217)
         {
             NPC.boughtCat = reader.ReadBoolean();
             NPC.boughtDog = reader.ReadBoolean();
             NPC.boughtBunny = reader.ReadBoolean();
         }
         else
         {
             NPC.boughtCat = false;
             NPC.boughtDog = false;
             NPC.boughtBunny = false;
         }
         if (versionNumber >= 223)
         {
             NPC.downedEmpressOfLight = reader.ReadBoolean();
             NPC.downedQueenSlime = reader.ReadBoolean();
         }
         else
         {
             NPC.downedEmpressOfLight = false;
             NPC.downedQueenSlime = false;
         }
         if (versionNumber >= 240)
         {
             NPC.downedDeerclops = reader.ReadBoolean();
         }
         else
         {
             NPC.downedDeerclops = false;
         }
         if (versionNumber >= 250)
         {
             NPC.unlockedSlimeBlueSpawn = reader.ReadBoolean();
         }
         else
         {
             NPC.unlockedSlimeBlueSpawn = false;
         }
         if (versionNumber >= 251)
         {
             NPC.unlockedMerchantSpawn = reader.ReadBoolean();
             NPC.unlockedDemolitionistSpawn = reader.ReadBoolean();
             NPC.unlockedPartyGirlSpawn = reader.ReadBoolean();
             NPC.unlockedDyeTraderSpawn = reader.ReadBoolean();
             NPC.unlockedTruffleSpawn = reader.ReadBoolean();
             NPC.unlockedArmsDealerSpawn = reader.ReadBoolean();
             NPC.unlockedNurseSpawn = reader.ReadBoolean();
             NPC.unlockedPrincessSpawn = reader.ReadBoolean();
         }
         else
         {
             NPC.unlockedMerchantSpawn = false;
             NPC.unlockedDemolitionistSpawn = false;
             NPC.unlockedPartyGirlSpawn = false;
             NPC.unlockedDyeTraderSpawn = false;
             NPC.unlockedTruffleSpawn = false;
             NPC.unlockedArmsDealerSpawn = false;
             NPC.unlockedNurseSpawn = false;
             NPC.unlockedPrincessSpawn = false;
         }
         if (versionNumber >= 259)
         {
             NPC.combatBookVolumeTwoWasUsed = reader.ReadBoolean();
         }
         else
         {
             NPC.combatBookVolumeTwoWasUsed = false;
         }
         if (versionNumber >= 260)
         {
             NPC.peddlersSatchelWasUsed = reader.ReadBoolean();
         }
         else
         {
             NPC.peddlersSatchelWasUsed = false;
         }
         if (versionNumber >= 261)
         {
             NPC.unlockedSlimeGreenSpawn = reader.ReadBoolean();
             NPC.unlockedSlimeOldSpawn = reader.ReadBoolean();
             NPC.unlockedSlimePurpleSpawn = reader.ReadBoolean();
             NPC.unlockedSlimeRainbowSpawn = reader.ReadBoolean();
             NPC.unlockedSlimeRedSpawn = reader.ReadBoolean();
             NPC.unlockedSlimeYellowSpawn = reader.ReadBoolean();
             NPC.unlockedSlimeCopperSpawn = reader.ReadBoolean();
         }
         else
         {
             NPC.unlockedSlimeGreenSpawn = false;
             NPC.unlockedSlimeOldSpawn = false;
             NPC.unlockedSlimePurpleSpawn = false;
             NPC.unlockedSlimeRainbowSpawn = false;
             NPC.unlockedSlimeRedSpawn = false;
             NPC.unlockedSlimeYellowSpawn = false;
             NPC.unlockedSlimeCopperSpawn = false;
         }
         if (versionNumber >= 264)
         {
             Main.fastForwardTimeToDusk = reader.ReadBoolean();
             Main.moondialCooldown = reader.ReadByte();
         }
         else
         {
             Main.fastForwardTimeToDusk = false;
             Main.moondialCooldown = 0;
         }
         Main.UpdateTimeRate();
     }
References _tempBloodMoon, _tempCultistDelay, _tempDayTime, _tempEclipse, _tempLanternNightCooldown, _tempLanternNightGenuine, _tempLanternNightManual, _tempLanternNightNextNightIsGenuine, _tempMaxRain, _tempMoonPhase, _tempPartyCooldown, _tempPartyGenuine, _tempPartyManual, _tempRaining, _tempRainTime, _tempSandstormHappening, _tempSandstormIntendedSeverity, _tempSandstormSeverity, _tempSandstormTimeLeft, _tempTime, _versionNumber, Main.ActiveWorldFileData, WorldGen.SavedOreTiers.Adamantite, Main.afterPartyOfDoom, WorldGen.altarCount, Main.anglerQuest, Main.anglerWhoFinishedToday, Main.bottomWorld, NPC.boughtBunny, NPC.boughtCat, NPC.boughtDog, Main.caveBackStyle, Main.caveBackX, WorldGen.clearWorld(), Main.cloudBGActive, Main.cloudBGAlpha, WorldGen.SavedOreTiers.Cobalt, NPC.combatBookVolumeTwoWasUsed, NPC.combatBookWasUsed, WorldGen.SavedOreTiers.Copper, NPCID.Count, WorldFileData.CreationTime, WorldGen.crimson, Main.dontStarveWorld, NPC.downedAncientCultist, NPC.downedBoss1, NPC.downedBoss2, NPC.downedBoss3, NPC.downedChristmasIceQueen, NPC.downedChristmasSantank, NPC.downedChristmasTree, NPC.downedClown, NPC.downedDeerclops, NPC.downedEmpressOfLight, NPC.downedFishron, NPC.downedFrost, NPC.downedGoblins, NPC.downedGolemBoss, NPC.downedHalloweenKing, NPC.downedHalloweenTree, NPC.downedMartians, NPC.downedMechBoss1, NPC.downedMechBoss2, NPC.downedMechBoss3, NPC.downedMechBossAny, NPC.downedMoonlord, NPC.downedPirates, NPC.downedPlantBoss, NPC.downedQueenBee, NPC.downedQueenSlime, NPC.downedSlimeKing, NPC.downedTowerNebula, NPC.downedTowerSolar, NPC.downedTowerStardust, NPC.downedTowerVortex, Main.drunkWorld, Main.dungeonX, Main.dungeonY, Main.eclipse, Main.FakeLoadInvasionStart(), Main.fastForwardTimeToDawn, Main.fastForwardTimeToDusk, Main.forceHalloweenForToday, Main.forceXMasForToday, Main.GameMode, WorldGen.genRand, Main.getGoodWorld, WorldGen.SavedOreTiers.Gold, Main.hardMode, Main.hellBackStyle, Main.iceBackStyle, Main.invasionDelay, Main.invasionSize, Main.invasionSizeStart, Main.invasionType, Main.invasionX, WorldGen.SavedOreTiers.Iron, Main.jungleBackStyle, NPC.killCount, Main.leftWorld, DD2Event.Load(), TreeTopsInfo.Load(), NPC.LunarApocalypseIsUp, Main.maxTilesX, Main.maxTilesY, Main.moondialCooldown, Main.moonType, WorldGen.SavedOreTiers.Mythril, UnifiedRandom.Next(), Main.noTrapsWorld, Main.notTheBeesWorld, Main.numClouds, NPC.peddlersSatchelWasUsed, Main.remixWorld, Main.rightWorld, Main.rockLayer, NPC.savedAngler, NPC.savedGoblin, NPC.savedGolfer, NPC.savedMech, NPC.savedStylist, NPC.savedTaxCollector, NPC.savedWizard, WorldGen.setBG(), WorldFileData.SetSeed(), WorldGen.shadowOrbCount, WorldGen.shadowOrbSmashed, NPC.ShieldStrengthTowerMax, NPC.ShieldStrengthTowerNebula, NPC.ShieldStrengthTowerSolar, NPC.ShieldStrengthTowerStardust, NPC.ShieldStrengthTowerVortex, WorldGen.SavedOreTiers.Silver, Main.slimeRainTime, WorldGen.spawnMeteor, Main.spawnTileX, Main.spawnTileY, Main.sundialCooldown, TempPartyCelebratingNPCs, Main.tenthAnniversaryWorld, Main.topWorld, NPC.TowerActiveNebula, NPC.TowerActiveSolar, NPC.TowerActiveStardust, NPC.TowerActiveVortex, WorldGen.treeBG1, Main.treeStyle, WorldGen.TreeTops, Main.treeX, WorldFileData.UniqueId, NPC.unlockedArmsDealerSpawn, NPC.unlockedDemolitionistSpawn, NPC.unlockedDyeTraderSpawn, NPC.unlockedMerchantSpawn, NPC.unlockedNurseSpawn, NPC.unlockedPartyGirlSpawn, NPC.unlockedPrincessSpawn, NPC.unlockedSlimeBlueSpawn, NPC.unlockedSlimeCopperSpawn, NPC.unlockedSlimeGreenSpawn, NPC.unlockedSlimeOldSpawn, NPC.unlockedSlimePurpleSpawn, NPC.unlockedSlimeRainbowSpawn, NPC.unlockedSlimeRedSpawn, NPC.unlockedSlimeYellowSpawn, NPC.unlockedTruffleSpawn, Main.UpdateTimeRate(), Main.windSpeedCurrent, Main.windSpeedTarget, WorldFileData.WorldGeneratorVersion, Main.worldID, Main.worldName, Main.worldSurface, and Main.zenithWorld.
Referenced by LoadWorld_Version2().