Terraria: System.Transactions.TransactionManager.Reenlist
Reenlist()
static Enlistment System.Transactions.TransactionManager.Reenlist (Guid resourceManagerIdentifier, byte[] recoveryInformation, IEnlistmentNotification enlistmentNotification) inline static
Definition at line 208 of file TransactionManager.cs.
    {
        if (resourceManagerIdentifier == Guid.Empty)
        {
            throw new ArgumentException(System.SR.BadResourceManagerId, "resourceManagerIdentifier");
        }
        if (recoveryInformation == null)
        {
            throw new ArgumentNullException("recoveryInformation");
        }
        if (enlistmentNotification == null)
        {
            throw new ArgumentNullException("enlistmentNotification");
        }
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceBase, "TransactionManager.Reenlist");
            log.TransactionManagerReenlist(resourceManagerIdentifier);
        }
        MemoryStream memoryStream = new MemoryStream(recoveryInformation);
        int num = 0;
        string nodeName = null;
        byte[] resourceManagerRecoveryInformation = null;
        try
        {
            BinaryReader binaryReader = new BinaryReader(memoryStream);
            num = binaryReader.ReadInt32();
            if (num != 1)
            {
                if (log.IsEnabled())
                {
                    log.TransactionExceptionTrace(TraceSourceType.TraceSourceBase, TransactionExceptionType.UnrecognizedRecoveryInformation, "recoveryInformation", string.Empty);
                }
                throw new ArgumentException(System.SR.UnrecognizedRecoveryInformation, "recoveryInformation");
            }
            nodeName = binaryReader.ReadString();
            resourceManagerRecoveryInformation = binaryReader.ReadBytes(recoveryInformation.Length - checked((int)memoryStream.Position));
        }
        catch (EndOfStreamException ex)
        {
            if (log.IsEnabled())
            {
                log.TransactionExceptionTrace(TraceSourceType.TraceSourceBase, TransactionExceptionType.UnrecognizedRecoveryInformation, "recoveryInformation", ex.ToString());
            }
            throw new ArgumentException(System.SR.UnrecognizedRecoveryInformation, "recoveryInformation", ex);
        }
        catch (FormatException ex2)
        {
            if (log.IsEnabled())
            {
                log.TransactionExceptionTrace(TraceSourceType.TraceSourceBase, TransactionExceptionType.UnrecognizedRecoveryInformation, "recoveryInformation", ex2.ToString());
            }
            throw new ArgumentException(System.SR.UnrecognizedRecoveryInformation, "recoveryInformation", ex2);
        }
        finally
        {
            memoryStream.Dispose();
        }
        DistributedTransactionManager distributedTransactionManager = CheckTransactionManager(nodeName);
        object syncRoot = new object();
        Enlistment enlistment = new Enlistment(enlistmentNotification, syncRoot);
        EnlistmentState.EnlistmentStatePromoted.EnterState(enlistment.InternalEnlistment);
        enlistment.InternalEnlistment.PromotedEnlistment = distributedTransactionManager.ReenlistTransaction(resourceManagerIdentifier, resourceManagerRecoveryInformation, (RecoveringInternalEnlistment)enlistment.InternalEnlistment);
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceBase, "TransactionManager.Reenlist");
        }
        return enlistment;
    }
References System.SR.BadResourceManagerId, System.Transactions.TransactionManager.CheckTransactionManager(), System.IO.MemoryStream.Dispose(), System.Transactions.TransactionManager.distributedTransactionManager, System.Guid.Empty, System.Transactions.EnlistmentState.EnlistmentStatePromoted, System.Transactions.Enlistment.InternalEnlistment, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodExit(), System.IO.MemoryStream.Position, System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), System.Exception.ToString(), System.Transactions.TransactionsEtwProvider.TransactionExceptionTrace(), System.Transactions.TransactionsEtwProvider.TransactionManagerReenlist(), and System.SR.UnrecognizedRecoveryInformation.