Terraria: System.Transactions.TransactionManager.FindOrCreatePromotedTransaction
FindOrCreatePromotedTransaction()
static Transaction System.Transactions.TransactionManager.FindOrCreatePromotedTransaction (Guid transactionIdentifier, DistributedTransaction dtx) inline static package
Definition at line 347 of file TransactionManager.cs.
    {
        Transaction transaction = null;
        Hashtable promotedTransactionTable = PromotedTransactionTable;
        lock (promotedTransactionTable)
        {
            WeakReference weakReference = (WeakReference)promotedTransactionTable[transactionIdentifier];
            if (weakReference != null)
            {
                transaction = weakReference.Target as Transaction;
                if (null != transaction)
                {
                    dtx.Dispose();
                    return transaction.InternalClone();
                }
                lock (promotedTransactionTable)
                {
                    promotedTransactionTable.Remove(transactionIdentifier);
                }
            }
            transaction = new Transaction(dtx);
            transaction._internalTransaction._finalizedObject = new FinalizedObject(transaction._internalTransaction, dtx.Identifier);
            weakReference = new WeakReference(transaction, trackResurrection: false);
            promotedTransactionTable[dtx.Identifier] = weakReference;
        }
        dtx.SavedLtmPromotedTransaction = transaction;
        FireDistributedTransactionStarted(transaction);
        return transaction;
    }
References System.Transactions.Transaction._internalTransaction, System.Transactions.Distributed.DistributedTransaction.Dispose(), System.Transactions.TransactionManager.FireDistributedTransactionStarted(), System.Transactions.Distributed.DistributedTransaction.Identifier, System.Transactions.Transaction.InternalClone(), System.Transactions.TransactionManager.PromotedTransactionTable, and System.Collections.Hashtable.Remove().
Referenced by System.Transactions.TransactionInterop.GetTransactionFromExportCookie(), and System.Transactions.TransactionInterop.GetTransactionFromTransmitterPropagationToken().