Terraria: System.Reflection.AssemblyName.GetAssemblyName
GetAssemblyName()
static AssemblyName System.Reflection.AssemblyName.GetAssemblyName (string assemblyFile) inline static
Definition at line 337 of file AssemblyName.cs.
    {
        if (assemblyFile == null)
        {
            throw new ArgumentNullException("assemblyFile");
        }
        return GetFileInformationCore(assemblyFile);
    }
References System.Runtime.Serialization.Dictionary, and System.Reflection.AssemblyName.GetFileInformationCore().
Referenced by System.Reflection.AssemblyNameProxy.GetAssemblyName(), and System.Runtime.Loader.AssemblyLoadContext.GetAssemblyName().