Terraria: System.Reflection.AssemblyName.EscapeString
EscapeString()
static unsafe char[] System.Reflection.AssemblyName.EscapeString (string input, int start, int end, char[] dest, ref int destPos, bool isUriString, char force1, char force2, char rsvd) inline static package
Definition at line 429 of file AssemblyName.cs.
    {
        int i = start;
        int num = start;
        byte* ptr = stackalloc byte[160];
        fixed (char* ptr2 = input)
        {
            for (; i < end; i++)
            {
                char c = ptr2[i];
                if (c > '\u007f')
                {
                    short num2 = (short)Math.Min(end - i, 39);
                    short num3 = 1;
                    while (num3 < num2 && ptr2[i + num3] > '\u007f')
                    {
                        num3++;
                    }
                    if (ptr2[i + num3 - 1] >= '\ud800' && ptr2[i + num3 - 1] <= '\udbff')
                    {
                        if (num3 == 1 || num3 == end - i)
{
                            throw new FormatException(SR.Arg_FormatException);
                        }
                        num3++;
                    }
                    dest = EnsureDestinationSize(ptr2, dest, i, (short)(num3 * 4 * 3), 480, ref destPos, num);
                    short num4 = (short)Encoding.UTF8.GetBytes(ptr2 + i, num3, ptr, 160);
                    if (num4 == 0)
                    {
                        throw new FormatException(SR.Arg_FormatException);
                    }
                    i += num3 - 1;
                    for (num3 = 0; num3 < num4; num3++)
                    {
                        EscapeAsciiChar((char)ptr[num3], dest, ref destPos);
                    }
                    num = i + 1;
                }
                else if (c == '%' && rsvd == '%')
                {
                    dest = EnsureDestinationSize(ptr2, dest, i, 3, 120, ref destPos, num);
                    if (i + 2 < end && HexConverter.IsHexChar(ptr2[i + 1]) && HexConverter.IsHexChar(ptr2[i + 2]))
                    {
                        dest[destPos++] = '%';
                        dest[destPos++] = ptr2[i + 1];
                        dest[destPos++] = ptr2[i + 2];
                        i += 2;
                    }
                    else
                    {
                        EscapeAsciiChar('%', dest, ref destPos);
                    }
                    num = i + 1;
                }
                else if (c == force1 || c == force2 || (c != rsvd && (isUriString ? (!IsReservedUnreservedOrHash(c)) : (!IsUnreserved(c)))))
                {
                    dest = EnsureDestinationSize(ptr2, dest, i, 3, 120, ref destPos, num);
                    EscapeAsciiChar(c, dest, ref destPos);
                    num = i + 1;
                }
            }
            if (num != i && (num != start || dest != null))
            {
                dest = EnsureDestinationSize(ptr2, dest, i, 0, 0, ref destPos, num);
            }
        }
        return dest;
    }
References System.SR.Arg_FormatException, System.Runtime.Serialization.Dictionary, System.Reflection.AssemblyName.EnsureDestinationSize(), System.Reflection.AssemblyName.EscapeAsciiChar(), System.input, System.HexConverter.IsHexChar(), System.Reflection.AssemblyName.IsReservedUnreservedOrHash(), System.Reflection.AssemblyName.IsUnreserved(), System.Math.Min(), System.start, and System.Text.Encoding.UTF8.
Referenced by System.Reflection.AssemblyName.EscapeCodeBase().