Terraria: System.Transactions.TransactionManager.FindPromotedTransaction
FindPromotedTransaction()
static Transaction System.Transactions.TransactionManager.FindPromotedTransaction (Guid transactionIdentifier) inline static package
Definition at line 329 of file TransactionManager.cs.
    {
        Hashtable promotedTransactionTable = PromotedTransactionTable;
        WeakReference weakReference = (WeakReference)promotedTransactionTable[transactionIdentifier];
        if (weakReference != null)
        {
            if (weakReference.Target is Transaction transaction)
            {
                return transaction.InternalClone();
            }
            lock (promotedTransactionTable)
            {
                promotedTransactionTable.Remove(transactionIdentifier);
            }
        }
        return null;
    }
References System.Transactions.TransactionManager.PromotedTransactionTable, System.Collections.Hashtable.Remove(), and System.WeakReference< T >.Target.
Referenced by System.Transactions.TransactionInterop.GetTransactionFromExportCookie(), System.Transactions.TransactionInterop.GetTransactionFromTransmitterPropagationToken(), and System.Transactions.TransactionStatePSPEOperation.PSPEPromote().