Terraria: System.Reflection.SignatureTypeExtensions.MatchesExactly
MatchesExactly()
static bool System.Reflection.SignatureTypeExtensions.MatchesExactly (this SignatureType pattern, Type actual) inline static package
Definition at line 16 of file SignatureTypeExtensions.cs.
    {
        if (pattern.IsSZArray)
        {
            if (actual.IsSZArray)
            {
                return pattern.ElementType.MatchesExactly(actual.GetElementType());
            }
            return false;
        }
        if (pattern.IsVariableBoundArray)
        {
            if (actual.IsVariableBoundArray && pattern.GetArrayRank() == actual.GetArrayRank())
            {
                return pattern.ElementType.MatchesExactly(actual.GetElementType());
            }
            return false;
        }
        if (pattern.IsByRef)
        {
            if (actual.IsByRef)
            {
                return pattern.ElementType.MatchesExactly(actual.GetElementType());
            }
            return false;
        }
        if (pattern.IsPointer)
        {
            if (actual.IsPointer)
            {
                return pattern.ElementType.MatchesExactly(actual.GetElementType());
            }
            return false;
        }
        if (pattern.IsConstructedGenericType)
        {
            if (!actual.IsConstructedGenericType)
            {
                return false;
            }
            if (!(pattern.GetGenericTypeDefinition() == actual.GetGenericTypeDefinition()))
            {
                return false;
            }
            Type[] genericTypeArguments = pattern.GenericTypeArguments;
            Type[] genericTypeArguments2 = actual.GenericTypeArguments;
            int num = genericTypeArguments.Length;
            if (num != genericTypeArguments2.Length)
            {
                return false;
            }
            for (int i = 0; i < num; i++)
            {
                Type type = genericTypeArguments[i];
                if (type is SignatureType pattern2)
                {
                    if (!pattern2.MatchesExactly(genericTypeArguments2[i]))
                    {
                        return false;
                    }
                }
                else if (type != genericTypeArguments2[i])
                {
                    return false;
                }
            }
            return true;
        }
        if (pattern.IsGenericMethodParameter)
        {
            if (!actual.IsGenericMethodParameter)
            {
                return false;
            }
            if (pattern.GenericParameterPosition != actual.GenericParameterPosition)
            {
                return false;
            }
            return true;
        }
        return false;
    }
References System.Type.GenericParameterPosition, System.Type.GenericTypeArguments, System.Type.GetArrayRank(), System.Type.GetElementType(), System.Type.GetGenericTypeDefinition(), System.Type.IsByRef, System.Type.IsConstructedGenericType, System.Type.IsGenericMethodParameter, System.Type.IsPointer, System.Type.IsSZArray, System.Type.IsVariableBoundArray, and System.type.