Terraria: System.Reflection.Emit.TypeNameBuilder.Append
Append() [2/2]
void System.Reflection.Emit.TypeNameBuilder.Append (string pStr) inline private
Definition at line 251 of file TypeNameBuilder.cs.
    {
        foreach (char c in pStr)
        {
            if (c != 0)
            {
                _str.Append(c);
                continue;
            }
            break;
        }
    }
References System.Reflection.Emit.TypeNameBuilder._str, and System.Text.StringBuilder.Append().
Referenced by System.Reflection.Emit.TypeNameBuilder.AddArray(), System.Reflection.Emit.TypeNameBuilder.AddAssemblySpec(), System.Reflection.Emit.TypeNameBuilder.AddElementType(), System.Reflection.Emit.TypeNameBuilder.AddName(), System.Reflection.Emit.TypeNameBuilder.CloseGenericArgument(), System.Reflection.Emit.TypeNameBuilder.CloseGenericArguments(), System.Reflection.Emit.TypeNameBuilder.EscapeAssemblyName(), System.Reflection.Emit.TypeNameBuilder.EscapeEmbeddedAssemblyName(), System.Reflection.Emit.TypeNameBuilder.EscapeName(), System.Reflection.Emit.TypeNameBuilder.OpenGenericArgument(), and System.Reflection.Emit.TypeNameBuilder.OpenGenericArguments().