Terraria: System.Reflection.Emit.TypeNameBuilder.AddAssemblyQualifiedName
AddAssemblyQualifiedName()
void System.Reflection.Emit.TypeNameBuilder.AddAssemblyQualifiedName (Type type, Format format) inline private
Definition at line 304 of file TypeNameBuilder.cs.
    {
        Type type2 = type;
        while (type2.HasElementType)
        {
            type2 = type2.GetElementType();
        }
        List<Type> list = new List<Type>();
        Type type3 = type2;
        while (type3 != null)
        {
            list.Add(type3);
            type3 = (type3.IsGenericParameter ? null : type3.DeclaringType);
        }
        for (int num = list.Count - 1; num >= 0; num--)
        {
            Type type4 = list[num];
            string text = type4.Name;
            if (num == list.Count - 1 && type4.Namespace != null && type4.Namespace.Length != 0)
            {
                text = type4.Namespace + "." + text;
            }
            AddName(text);
        }
        if (type2.IsGenericType && (!type2.IsGenericTypeDefinition || format == Format.ToString))
        {
            Type[] genericArguments = type2.GetGenericArguments();
            OpenGenericArguments();
            for (int i = 0; i < genericArguments.Length; i++)
            {
                Format format2 = ((format == Format.FullName) ? Format.AssemblyQualifiedName : format);
                OpenGenericArgument();
                AddAssemblyQualifiedName(genericArguments[i], format2);
                CloseGenericArgument();
            }
            CloseGenericArguments();
        }
        AddElementType(type);
        if (format == Format.AssemblyQualifiedName)
        {
            AddAssemblySpec(type.Module.Assembly.FullName);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Emit.TypeNameBuilder.AddAssemblyQualifiedName(), System.Reflection.Emit.TypeNameBuilder.AddAssemblySpec(), System.Reflection.Emit.TypeNameBuilder.AddElementType(), System.Reflection.Emit.TypeNameBuilder.AddName(), System.Reflection.Emit.TypeNameBuilder.CloseGenericArgument(), System.Reflection.Emit.TypeNameBuilder.CloseGenericArguments(), System.format, System.list, System.Reflection.Emit.TypeNameBuilder.OpenGenericArgument(), System.Reflection.Emit.TypeNameBuilder.OpenGenericArguments(), System.text, and System.type.
Referenced by System.Reflection.Emit.TypeNameBuilder.AddAssemblyQualifiedName().