Terraria: System.Reflection.Emit.TypeNameBuilder.PopOpenGenericArgument
PopOpenGenericArgument()
void System.Reflection.Emit.TypeNameBuilder.PopOpenGenericArgument () inline private
Definition at line 240 of file TypeNameBuilder.cs.
    {
        int num = _stack[--_stackIdx];
        _stack.RemoveAt(_stackIdx);
        if (!_hasAssemblySpec)
        {
            _str.Remove(num - 1, 1);
        }
        _hasAssemblySpec = false;
    }
References System.Reflection.Emit.TypeNameBuilder._hasAssemblySpec, System.Reflection.Emit.TypeNameBuilder._stack, System.Reflection.Emit.TypeNameBuilder._stackIdx, System.Reflection.Emit.TypeNameBuilder._str, System.Text.StringBuilder.Remove(), and System.Collections.Generic.List< T >.RemoveAt().
Referenced by System.Reflection.Emit.TypeNameBuilder.CloseGenericArgument().