Terraria: System.Xml.XmlRawWriter.WriteValue
WriteValue() [9/11]
override void System.Xml.XmlRawWriter.WriteValue (object value) inline virtual inherited
Reimplemented from System.Xml.XmlWriter.
Reimplemented in System.Xml.Xsl.Runtime.XmlAttributeCache, and System.Xml.Xsl.Runtime.XmlRawWriterWrapper.
Definition at line 142 of file XmlRawWriter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        WriteString(XmlUntypedConverter.Untyped.ToString(value, _resolver));
    }
References System.Xml.XmlRawWriter._resolver, System.Xml.Schema.XmlUntypedConverter.Untyped, System.value, and System.Xml.XmlWriter.WriteString().
Referenced by System.Xml.Xsl.Runtime.XmlAttributeCache.FlushAttributes(), System.Xml.XmlAutoDetectWriter.WriteValue(), System.Xml.XmlAutoDetectWriter.WriteValue(), System.Xml.XmlAutoDetectWriter.WriteValue(), System.Xml.XmlAutoDetectWriter.WriteValue(), System.Xml.XmlAutoDetectWriter.WriteValue(), System.Xml.XmlAutoDetectWriter.WriteValue(), System.Xml.XmlAutoDetectWriter.WriteValue(), System.Xml.XmlAutoDetectWriter.WriteValue(), System.Xml.XmlAutoDetectWriter.WriteValue(), and System.Xml.XmlAutoDetectWriter.WriteValue().