Terraria: System.Reflection.Emit.TypeNameBuilder.AddAssemblySpec
AddAssemblySpec()
void System.Reflection.Emit.TypeNameBuilder.AddAssemblySpec (string assemblySpec) inline private
Definition at line 131 of file TypeNameBuilder.cs.
    {
        if (assemblySpec != null && !assemblySpec.Equals(""))
        {
            Append(", ");
            if (_instNesting > 0)
            {
                EscapeEmbeddedAssemblyName(assemblySpec);
            }
            else
            {
                EscapeAssemblyName(assemblySpec);
            }
            _hasAssemblySpec = true;
        }
    }
References System.Reflection.Emit.TypeNameBuilder._hasAssemblySpec, System.Reflection.Emit.TypeNameBuilder._instNesting, System.Reflection.Emit.TypeNameBuilder.Append(), System.Reflection.Emit.TypeNameBuilder.EscapeAssemblyName(), and System.Reflection.Emit.TypeNameBuilder.EscapeEmbeddedAssemblyName().
Referenced by System.Reflection.Emit.TypeNameBuilder.AddAssemblyQualifiedName().