Terraria: Microsoft.Xna.Framework.Graphics.VertexElementValidator.Validate
Validate() [1/2]
static void Microsoft.Xna.Framework.Graphics.VertexElementValidator.Validate (int vertexStride, VertexElement[] elements) inline static package
Definition at line 22 of file VertexElementValidator.cs.
    {
        if (vertexStride <= 0)
        {
            throw new ArgumentOutOfRangeException("vertexStride");
        }
        if (((uint)vertexStride & 3u) != 0)
        {
            throw new ArgumentException(FrameworkResources.VertexElementOffsetNotMultipleFour);
        }
        int[] array = new int[vertexStride];
        for (int i = 0; i < vertexStride; i++)
        {
            array[i] = -1;
        }
        for (int j = 0; j < elements.Length; j++)
        {
            int offset = elements[j].Offset;
            int typeSize = GetTypeSize(elements[j].VertexElementFormat);
            if (elements[j].VertexElementUsage < VertexElementUsage.Position || elements[j].VertexElementUsage > VertexElementUsage.TessellateFactor)
            {
                throw new ArgumentException(string.Format(CultureInfo.CurrentCulture, FrameworkResources.VertexElementBadUsage, new object[2]
                {
                    elements[j].VertexElementUsage,
                    string.Empty
                }));
            }
            if (offset < 0 || offset + typeSize > vertexStride)
            {
                throw new ArgumentException(string.Format(CultureInfo.CurrentCulture, FrameworkResources.VertexElementOutsideStride, new object[2]
                {
                    elements[j].VertexElementUsage,
                    elements[j].UsageIndex
                }));
            }
            if (((uint)offset & 3u) != 0)
            {
                throw new ArgumentException(FrameworkResources.VertexElementOffsetNotMultipleFour);
            }
            for (int k = 0; k < j; k++)
            {
                if (elements[j].VertexElementUsage == elements[k].VertexElementUsage && elements[j].UsageIndex == elements[k].UsageIndex)
                {
                    throw new ArgumentException(string.Format(CultureInfo.CurrentCulture, FrameworkResources.DuplicateVertexElement, new object[2]
                    {
                        elements[j].VertexElementUsage,
                        elements[j].UsageIndex
                    }));
                }
            }
            for (int l = offset; l < offset + typeSize; l++)
            {
                if (array[l] >= 0)
                {
                    throw new ArgumentException(string.Format(CultureInfo.CurrentCulture, FrameworkResources.VertexElementsOverlap, elements[array[l]].VertexElementUsage, elements[array[l]].UsageIndex, elements[j].VertexElementUsage, elements[j].UsageIndex));
                }
                array[l] = j;
            }
        }
    }
References System.array, System.Globalization.CultureInfo.CurrentCulture, Microsoft.Xna.Framework.FrameworkResources.DuplicateVertexElement, System.Globalization.Format, Microsoft.Xna.Framework.Graphics.VertexElementValidator.GetTypeSize(), Microsoft.Xna.Framework.Graphics.VertexElement.Offset, System.offset, Microsoft.Xna.Framework.Graphics.VertexElement.UsageIndex, Microsoft.Xna.Framework.FrameworkResources.VertexElementBadUsage, Microsoft.Xna.Framework.FrameworkResources.VertexElementOffsetNotMultipleFour, Microsoft.Xna.Framework.FrameworkResources.VertexElementOutsideStride, Microsoft.Xna.Framework.FrameworkResources.VertexElementsOverlap, and Microsoft.Xna.Framework.Graphics.VertexElement.VertexElementUsage.
Referenced by Microsoft.Xna.Framework.Graphics.VertexDeclaration.VertexDeclaration(), Microsoft.Xna.Framework.Graphics.VertexDeclaration.VertexDeclaration(), Microsoft.Xna.Framework.Graphics.VertexDeclaration.Bind(), and Microsoft.Xna.Framework.Graphics.VertexElementValidator.Validate().