Terraria: System.Reflection.Emit.TypeNameBuilder._str
_str
StringBuilder System.Reflection.Emit.TypeNameBuilder._str = new StringBuilder() private
Definition at line 15 of file TypeNameBuilder.cs.
Referenced by System.Reflection.Emit.TypeNameBuilder.AddArray(), System.Reflection.Emit.TypeNameBuilder.Append(), System.Reflection.Emit.TypeNameBuilder.Append(), System.Reflection.Emit.TypeNameBuilder.CloseGenericArguments(), System.Reflection.Emit.TypeNameBuilder.EscapeName(), System.Reflection.Emit.TypeNameBuilder.PopOpenGenericArgument(), System.Reflection.Emit.TypeNameBuilder.PushOpenGenericArgument(), and System.Reflection.Emit.TypeNameBuilder.ToString().