Terraria: Microsoft.Xna.Framework.Graphics.VertexElementValidator.Validate
Validate() [2/2]
static void Microsoft.Xna.Framework.Graphics.VertexElementValidator.Validate (int vertexStride, VertexElement[] elements, ProfileCapabilities profile) inline static package
Definition at line 83 of file VertexElementValidator.cs.
    {
        Validate(vertexStride, elements);
        if (vertexStride > profile.MaxStreamStride)
        {
            profile.ThrowNotSupportedException(FrameworkResources.ProfileMaxVertexStride, profile.MaxStreamStride);
        }
        if (elements.Length > profile.MaxVertexStreams)
        {
            profile.ThrowNotSupportedException(FrameworkResources.ProfileMaxVertexElements, profile.MaxVertexStreams);
        }
        for (int i = 0; i < elements.Length; i++)
        {
            if (!profile.ValidVertexFormats.Contains(elements[i].VertexElementFormat))
            {
                profile.ThrowNotSupportedException(FrameworkResources.ProfileFormatNotSupported, typeof(VertexElement).Name, elements[i].VertexElementFormat);
            }
            if (elements[i].UsageIndex < 0 || elements[i].UsageIndex >= profile.MaxVertexStreams)
            {
                throw new ArgumentException(string.Format(CultureInfo.CurrentCulture, FrameworkResources.VertexElementBadUsage, new object[2]
                {
                    elements[i].VertexElementUsage,
                    elements[i].UsageIndex
                }));
            }
        }
    }
References System.Collections.Generic.List< T >.Contains(), System.Globalization.CultureInfo.CurrentCulture, System.Globalization.Format, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxStreamStride, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxVertexStreams, System.Name, Microsoft.Xna.Framework.FrameworkResources.ProfileFormatNotSupported, Microsoft.Xna.Framework.FrameworkResources.ProfileMaxVertexElements, Microsoft.Xna.Framework.FrameworkResources.ProfileMaxVertexStride, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), Microsoft.Xna.Framework.Graphics.VertexElementValidator.Validate(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ValidVertexFormats, Microsoft.Xna.Framework.FrameworkResources.VertexElementBadUsage, and Microsoft.Xna.Framework.Graphics.VertexElement.VertexElementFormat.