Terraria: System.Xml.XmlRawWriter.WriteEndNamespaceDeclaration
WriteEndNamespaceDeclaration()
virtual void System.Xml.XmlRawWriter.WriteEndNamespaceDeclaration () inline package virtual inherited
Reimplemented in System.Xml.DocumentXmlWriter, System.Xml.QueryOutputWriter, System.Xml.XmlAutoDetectWriter, System.Xml.XmlEncodedRawTextWriter, and System.Xml.XmlUtf8RawTextWriter.
Definition at line 214 of file XmlRawWriter.cs.
    {
        throw new NotSupportedException();
    }
Referenced by System.Xml.XmlWellFormedWriter.WriteEndAttribute(), System.Xml.QueryOutputWriter.WriteEndNamespaceDeclaration(), and System.Xml.XmlAutoDetectWriter.WriteEndNamespaceDeclaration().