Terraria: System.Xml.XmlRawWriter.StartElementContent
StartElementContent()
void System.Xml.XmlRawWriter.StartElementContent () abstract package
Referenced by System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyNode(), System.Xml.Xsl.XsltOld.NavigatorOutput.RecordDone(), System.Xml.Xsl.Runtime.XmlAttributeCache.StartElementContent(), System.Xml.QueryOutputWriter.StartElementContent(), System.Xml.XmlAutoDetectWriter.StartElementContent(), System.Xml.XmlWellFormedWriter.StartElementContent(), System.Xml.XmlWellFormedWriter.StartElementContentAsync(), and System.Xml.XmlWellFormedWriter.StartElementContentAsync_WithNS().