Terraria: GolfHelper.HitGolfBall
HitGolfBall()
static void GolfHelper.HitGolfBall (Entity entity, Vector2 velocity, float roughLandResistance) inline static
     {
         Vector2 bottom = entity.Bottom;
         bottom.Y += 1f;
         Point point = bottom.ToTileCoordinates();
         Tile tile = Main.tile[point.X, point.Y];
         if (tile != null && tile.active())
         {
             TileMaterial byTileId = TileMaterials.GetByTileId(tile.type);
             velocity = Vector2.Lerp(velocity * byTileId.GolfPhysics.ClubImpactDampening, velocity, byTileId.GolfPhysics.ImpactDampeningResistanceEfficiency * roughLandResistance);
         }
         entity.velocity = velocity;
         if (entity is Projectile projectile)
         {
             projectile.timeLeft = 18000;
             if (projectile.ai[1] < 0f)
             {
                 projectile.ai[1] = 0f;
             }
             projectile.ai[1] += 1f;
             projectile.localAI[1] = 1f;
             Main.LocalGolfState.RecordSwing(projectile);
         }
     }
References Tile.active(), Entity.Bottom, TileGolfPhysics.ClubImpactDampening, TileMaterials.GetByTileId(), TileMaterial.GolfPhysics, TileGolfPhysics.ImpactDampeningResistanceEfficiency, Main.LocalGolfState, GolfState.RecordSwing(), Main.tile, Tile.type, and Entity.velocity.
Referenced by Projectile.AI_150_GolfClubHelper(), and FancyGolfPredictionLine.Update().