Terraria: Terraria.NPC.DespawnEncouragement_AIStyle3_Fighters_NotDiscouraged
DespawnEncouragement_AIStyle3_Fighters_NotDiscouraged()
static bool Terraria.NPC.DespawnEncouragement_AIStyle3_Fighters_NotDiscouraged (int npcID, Vector2 position, NPC npcInstance) inline static
Definition at line 53251 of file NPC.cs.
    {
        if (!Main.eclipse && Main.IsItDay() && (npcInstance == null || !npcInstance.SpawnedFromStatue) && !((double)position.Y > Main.worldSurface * 16.0) && (npcInstance == null || !Main.player[npcInstance.target].ZoneGraveyard) && (!Main.snowMoon || (npcID != 343 && npcID != 350)) && (Main.invasionType != 1 || (npcID != 26 && npcID != 27 && npcID != 28 && npcID != 111 && npcID != 471)) && (!Main.dontStarveWorld || (npcID != 164 && npcID != 163)) && npcID != 73 && npcID != 624 && (npcID != 631 || !(npcInstance.ai[2] > 0f)) && (Main.invasionType != 3 || npcID < 212 || npcID > 216) && (Main.invasionType != 4 || (npcID != 381 && npcID != 382 && npcID != 383 && npcID != 385 && npcID != 386 && npcID != 389 && npcID != 391 && npcID != 520)) && npcID != 31 && npcID != 294 && npcID != 295 && npcID != 296 && npcID != 47 && npcID != 67 && npcID != 77 && npcID != 78 && npcID != 79 && npcID != 80 && npcID != 630 && npcID != 110 && npcID != 120 && npcID != 168 && npcID != 181 && npcID != 185 && npcID != 198 && npcID != 199 && npcID != 206 && npcID != 217 && npcID != 218 && npcID != 219 && npcID != 220 && npcID != 239 && npcID != 243 && npcID != 254 && npcID != 255 && npcID != 257 && npcID != 258 && npcID != 291 && npcID != 292 && npcID != 293 && npcID != 379 && npcID != 380 && npcID != 464 && npcID != 470 && npcID != 424 && (npcID != 411 || (npcInstance != null && !(npcInstance.ai[1] >= 180f) && !(npcInstance.ai[1] < 90f))))
        {
            switch (npcID)
            {
            default:
                if (npcID != 528 && npcID != 529 && npcID != 530)
                {
                    return npcID == 532;
                }
                break;
            case 409:
            case 415:
            case 419:
            case 425:
            case 427:
            case 428:
            case 429:
            case 508:
            case 524:
            case 525:
            case 526:
            case 527:
            case 580:
            case 582:
                break;
            }
        }
        return true;
    }
References Terraria.Main.dontStarveWorld, Terraria.Main.eclipse, Terraria.Main.invasionType, Terraria.Main.IsItDay(), Terraria.Main.player, Terraria.Entity.position, Terraria.Main.snowMoon, and Terraria.Main.worldSurface.
Referenced by Terraria.NPC.AI_003_Fighters(), and Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.WouldNPCBeDiscouraged().