Terraria: Terraria.NPC.DespawnEncouragement_AIStyle2_FloatingEye_IsDiscouraged
DespawnEncouragement_AIStyle2_FloatingEye_IsDiscouraged()
static bool Terraria.NPC.DespawnEncouragement_AIStyle2_FloatingEye_IsDiscouraged (int npcID, Vector2 npcPosition, int target = 255) inline static
    {
        if (!Main.player[target].ZoneGraveyard && Main.IsItDay() && (double)npcPosition.Y <= Main.worldSurface * 16.0)
        {
            if (npcID != 2 && npcID != 133 && npcID != 190 && npcID != 191 && npcID != 192 && npcID != 193 && npcID != 194 && npcID != 317)
            {
                return npcID == 318;
            }
            return true;
        }
        return false;
    }
References Terraria.Main.IsItDay(), Terraria.Main.player, Terraria.NPC.target, and Terraria.Main.worldSurface.
Referenced by Terraria.NPC.AI_002_FloatingEye(), and Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.WouldNPCBeDiscouraged().