Terraria: Terraria.NPC.GetAttackDamage_ForProjectiles
GetAttackDamage_ForProjectiles()
int Terraria.NPC.GetAttackDamage_ForProjectiles (float normalDamage, float expertDamage) inline
Definition at line 1082 of file NPC.cs.
    {
        float amount = (Main.expertMode ? 1 : 0);
        if (Main.GameModeInfo.IsJourneyMode)
        {
            amount = MathHelper.Clamp(strengthMultiplier - 1f, 0f, 1f);
        }
        return (int)MathHelper.Lerp(normalDamage, expertDamage, amount);
    }
References Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Main.GameModeInfo, Microsoft.Xna.Framework.MathHelper.Lerp(), and Terraria.NPC.strengthMultiplier.
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_117_BloodNautilus(), and Terraria.NPC.AI_120_HallowBoss().