Terraria: Terraria.NPC.DropItemInstanced
DropItemInstanced()
void Terraria.NPC.DropItemInstanced (Vector2 Position, Vector2 HitboxSize, int itemType, int itemStack = 1, bool interactionRequired = true) inline
    {
        if (itemType <= 0)
        {
            return;
        }
        if (Main.netMode == 2)
        {
            int num = Item.NewItem(GetItemSource_Loot(), (int)Position.X, (int)Position.Y, (int)HitboxSize.X, (int)HitboxSize.Y, itemType, itemStack, noBroadcast: true);
            Main.timeItemSlotCannotBeReusedFor[num] = 54000;
            for (int i = 0; i < 255; i++)
            {
                if (Main.player[i].active && (playerInteraction[i] || !interactionRequired))
                {
                    NetMessage.SendData(90, i, -1, null, num);
                }
            }
            Main.item[num].active = false;
        }
        else if (Main.netMode == 0)
        {
            Item.NewItem(GetItemSource_Loot(), (int)Position.X, (int)Position.Y, (int)HitboxSize.X, (int)HitboxSize.Y, itemType, itemStack);
        }
        value = 0f;
    }
References Terraria.Main.item, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Main.player, Terraria.NetMessage.SendData(), and Terraria.Main.timeItemSlotCannotBeReusedFor.
Referenced by Terraria.GameContent.Events.DD2Event.DropMedals().