Terraria: Terraria.NPC.ScaleStats
ScaleStats()
void Terraria.NPC.ScaleStats (int? activePlayersCount, GameModeData gameModeData, float? strengthOverride) inline
Definition at line 12149 of file NPC.cs.
    {
        if ((!NPCID.Sets.NeedsExpertScaling.IndexInRange(type) || !NPCID.Sets.NeedsExpertScaling[type]) && (lifeMax <= 5 || damage == 0 || friendly || townNPC))
        {
            return;
        }
        float num = 1f;
        if (strengthOverride.HasValue)
        {
            num = strengthOverride.Value;
        }
        else if (gameModeData.IsJourneyMode)
        {
            CreativePowers.DifficultySliderPower power = CreativePowerManager.Instance.GetPower<CreativePowers.DifficultySliderPower>();
            if (power != null && power.GetIsUnlocked())
            {
                num = power.StrengthMultiplierToGiveNPCs;
            }
        }
        float num2 = num;
        if (gameModeData.IsJourneyMode && Main.getGoodWorld)
        {
            num += 1f;
        }
        NPCStrengthHelper nPCStrengthHelper = new NPCStrengthHelper(gameModeData, num, Main.getGoodWorld);
        if (nPCStrengthHelper.IsExpertMode)
        {
            ScaleStats_ApplyExpertTweaks();
        }
        ScaleStats_ApplyGameMode(gameModeData);
        if (Main.getGoodWorld && nPCStrengthHelper.ExtraDamageForGetGoodWorld)
        {
            damage += damage / 3;
        }
        if (nPCStrengthHelper.IsExpertMode)
        {
            int num3 = 1;
            num3 = (statsAreScaledForThisManyPlayers = ((!activePlayersCount.HasValue) ? GetActivePlayerCount() : activePlayersCount.Value));
            GetStatScalingFactors(num3, out var balance, out var boost);
            float bossAdjustment = 1f;
            if (nPCStrengthHelper.IsMasterMode)
            {
                bossAdjustment = 0.85f;
            }
            ScaleStats_ApplyMultiplayerStats(num3, balance, boost, bossAdjustment);
        }
        ScaleStats_UseStrengthMultiplier(num);
        strengthMultiplier = num2;
        if ((type < 0 || !NPCID.Sets.ProjectileNPC[type]) && lifeMax < 6)
        {
            lifeMax = 6;
        }
        life = lifeMax;
        defDamage = damage;
        defDefense = defense;
    }
References Terraria.NPC.damage, Terraria.NPC.defDamage, Terraria.NPC.defDefense, Terraria.NPC.defense, Terraria.NPC.friendly, Terraria.NPC.GetActivePlayerCount(), Terraria.Main.getGoodWorld, Terraria.NPC.GetStatScalingFactors(), Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.DataStructures.GameModeData.IsJourneyMode, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.ID.NPCID.Sets.NeedsExpertScaling, Terraria.ID.NPCID.Sets.ProjectileNPC, Terraria.NPC.ScaleStats_ApplyExpertTweaks(), Terraria.NPC.ScaleStats_ApplyGameMode(), Terraria.NPC.ScaleStats_ApplyMultiplayerStats(), Terraria.NPC.ScaleStats_UseStrengthMultiplier(), Terraria.NPC.statsAreScaledForThisManyPlayers, Terraria.NPC.strengthMultiplier, Terraria.NPC.townNPC, Terraria.NPC.type, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.NPC.SetDefaults(), and Terraria.NPC.SetDefaultsFromNetId().