Terraria: Terraria.NPC.DoDeathEvents_SummonDungeonSpirit
DoDeathEvents_SummonDungeonSpirit()
void Terraria.NPC.DoDeathEvents_SummonDungeonSpirit (Player closestPlayer) inline private
    {
        if (lifeMax > 100 && type != 288 && value > 0f && HasPlayerTarget && Main.hardMode && downedPlantBoss && Main.player[target].ZoneDungeon)
        {
            int range = 13;
            if (Main.expertMode)
            {
                range = 9;
            }
            if (closestPlayer.RollLuck(range) == 0 && Main.wallDungeon[Main.tile[(int)base.Center.X / 16, (int)base.Center.Y / 16].wall])
            {
                NewNPC(GetSpawnSource_NPCHurt(), (int)base.Center.X, (int)base.Center.Y, 288);
            }
        }
    }
References Terraria.NPC.downedPlantBoss, Terraria.Main.expertMode, Terraria.NPC.GetSpawnSource_NPCHurt(), Terraria.Main.hardMode, Terraria.NPC.HasPlayerTarget, Terraria.NPC.lifeMax, Terraria.NPC.NewNPC(), Terraria.Main.player, Terraria.NPC.target, Terraria.Main.tile, Terraria.NPC.type, Terraria.NPC.value, and Terraria.Main.wallDungeon.
Referenced by Terraria.NPC.DoDeathEvents().