Terraria: Terraria.NPC.GetSpawnSource_ForProjectile
GetSpawnSource_ForProjectile()
IEntitySource Terraria.NPC.GetSpawnSource_ForProjectile () inline
Definition at line 87526 of file NPC.cs.
    {
        return new EntitySource_Parent(this);
    }
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_069_DukeFishron(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_119_Dandelion(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_123_Deerclops_ShootRubbleUp(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike(), Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.NPC.checkDead(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DropTombstoneTownNPC(), Terraria.NPC.SpawnPassiveShadowHands(), Terraria.NPC.SpawnStardustMark_StardustTower(), Terraria.NPC.SpawnStardustMark_StardustWorm(), and Terraria.NPC.StingerExplosion().