Terraria: Terraria.NPC.GetFullnameByID
GetFullnameByID()
static string Terraria.NPC.GetFullnameByID (int npcID) inline static
Definition at line 1036 of file NPC.cs.
    {
        for (int i = 0; i < 200; i++)
        {
            if (Main.npc[i].active && Main.npc[i].type == npcID)
            {
                return Main.npc[i].FullName;
            }
        }
        return Lang.GetNPCNameValue(npcID);
    }
References Terraria.Lang.GetNPCNameValue(), and Terraria.Main.npc.
Referenced by Terraria.GameContent.ShopHelper.DislikeNPC(), Terraria.GameContent.ShopHelper.HateNPC(), Terraria.GameContent.ShopHelper.LikeNPC(), Terraria.GameContent.ShopHelper.LikePrincess(), and Terraria.GameContent.ShopHelper.LoveNPC().