Terraria: Terraria.NPC.StrikeNPC
StrikeNPC()
double Terraria.NPC.StrikeNPC (int Damage, float knockBack, int hitDirection, bool crit = false, bool noEffect = false, bool fromNet = false) inline
Definition at line 78024 of file NPC.cs.
    {
        bool flag = Main.netMode == 0;
        if (flag && ignorePlayerInteractions > 0)
        {
            ignorePlayerInteractions--;
            flag = false;
        }
        if (!active || life <= 0)
        {
            return 0.0;
        }
        double num = Damage;
        num = Main.CalculateDamageNPCsTake((int)num, defense);
        if (crit)
        {
            num *= 2.0;
        }
        if (takenDamageMultiplier > 1f)
        {
            num *= (double)takenDamageMultiplier;
        }
        if ((takenDamageMultiplier > 1f || Damage != 9999) && lifeMax > 1)
        {
            if (friendly)
            {
                Color color = (crit ? CombatText.DamagedFriendlyCrit : CombatText.DamagedFriendly);
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), color, (int)num, crit);
            }
            else
            {
                Color color2 = (crit ? CombatText.DamagedHostileCrit : CombatText.DamagedHostile);
                if (fromNet)
                {
                    color2 = (crit ? CombatText.OthersDamagedHostileCrit : CombatText.OthersDamagedHostile);
                }
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), color2, (int)num, crit);
            }
        }
        if (num >= 1.0)
        {
            if (flag)
            {
                PlayerInteraction(Main.myPlayer);
            }
            justHit = true;
            if ((type == 438 || type == 379) && Main.netMode != 1)
            {
                int num2 = (int)(0f - ai[3] - 1f);
                if (num2 > -1 && Main.npc[num2].localAI[0] == 0f)
                {
                    Main.npc[num2].localAI[0] = 1f;
                }
            }
            if (townNPC)
            {
                if (aiStyle == 7 && (ai[0] == 3f || ai[0] == 4f || ai[0] == 16f || ai[0] == 17f))
                {
                    NPC nPC = Main.npc[(int)ai[2]];
                    if (nPC.active)
                    {
                        nPC.ai[0] = 1f;
                        nPC.ai[1] = 300 + Main.rand.Next(300);
                        nPC.ai[2] = 0f;
                        nPC.localAI[3] = 0f;
                        nPC.direction = hitDirection;
                        nPC.netUpdate = true;
                    }
                }
                ai[0] = 1f;
                ai[1] = 300 + Main.rand.Next(300);
                ai[2] = 0f;
                localAI[3] = 0f;
                direction = hitDirection;
                netUpdate = true;
            }
            if (aiStyle == 8 && Main.netMode != 1)
            {
                if (type == 172)
                {
                    ai[0] = 450f;
                }
                else if (type == 283 || type == 284)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        ai[0] = 390f;
                        netUpdate = true;
                    }
                }
                else if (type == 533)
                {
                    if (Main.rand.Next(3) != 0)
                    {
                        ai[0] = 181f;
                        netUpdate = true;
                    }
                }
                else
                {
                    ai[0] = 400f;
                }
                TargetClosest();
            }
            if (aiStyle == 97 && Main.netMode != 1)
            {
                localAI[1] = 1f;
                TargetClosest();
            }
            if (type == 371)
            {
                num = 0.0;
                ai[0] = 1f;
                ai[1] = 4f;
                dontTakeDamage = true;
            }
            if (type == 346 && (double)life >= (double)lifeMax * 0.5 && (double)life - num < (double)lifeMax * 0.5)
            {
                Gore.NewGore(position, velocity, 517);
            }
            if (type == 184)
            {
                localAI[0] = 60f;
            }
            if (type == 535)
            {
                localAI[0] = 60f;
            }
            if (type == 185)
            {
                localAI[0] = 1f;
            }
            if (!immortal)
            {
                if (realLife >= 0)
                {
                    Main.npc[realLife].life -= (int)num;
                    life = Main.npc[realLife].life;
                    lifeMax = Main.npc[realLife].lifeMax;
                }
                else
                {
                    life -= (int)num;
                }
            }
            if (knockBack > 0f && knockBackResist > 0f)
            {
                float num3 = knockBack * knockBackResist;
                if (onFire2)
                {
                    num3 *= 1.1f;
                }
                if (num3 > 8f)
                {
                    float num4 = num3 - 8f;
                    num4 *= 0.9f;
                    num3 = 8f + num4;
                }
                if (num3 > 10f)
                {
                    float num5 = num3 - 10f;
                    num5 *= 0.8f;
                    num3 = 10f + num5;
                }
                if (num3 > 12f)
                {
                    float num6 = num3 - 12f;
                    num6 *= 0.7f;
                    num3 = 12f + num6;
                }
                if (num3 > 14f)
                {
                    float num7 = num3 - 14f;
                    num7 *= 0.6f;
                    num3 = 14f + num7;
                }
                if (num3 > 16f)
                {
                    num3 = 16f;
                }
                if (crit)
                {
                    num3 *= 1.4f;
                }
                int num8 = (int)num * 10;
                if (Main.expertMode)
                {
                    num8 = (int)num * 15;
                }
                if (num8 > lifeMax)
                {
                    if (hitDirection < 0 && velocity.X > 0f - num3)
                    {
                        if (velocity.X > 0f)
{
                            velocity.X -= num3;
                        }
                        velocity.X -= num3;
                        if (velocity.X < 0f - num3)
{
                            velocity.X = 0f - num3;
                        }
                    }
                    else if (hitDirection > 0 && velocity.X < num3)
                    {
                        if (velocity.X < 0f)
{
                            velocity.X += num3;
                        }
                        velocity.X += num3;
                        if (velocity.X > num3)
{
                            velocity.X = num3;
                        }
                    }
                    if (type == 185)
                    {
                        num3 *= 1.5f;
                    }
                    num3 = (noGravity ? (num3 * -0.5f) : (num3 * -0.75f));
                    if (velocity.Y > num3)
                    {
                        velocity.Y += num3;
                        if (velocity.Y < num3)
{
                            velocity.Y = num3;
                        }
                    }
                }
                else
                {
                    if (!noGravity)
                    {
                        velocity.Y = (0f - num3) * 0.75f * knockBackResist;
                    }
                    else
                    {
                        velocity.Y = (0f - num3) * 0.5f * knockBackResist;
                    }
                    velocity.X = num3 * (float)hitDirection * knockBackResist;
                }
            }
            if ((type == 113 || type == 114) && life <= 0)
            {
                for (int i = 0; i < 200; i++)
                {
                    if (Main.npc[i].active && (Main.npc[i].type == 113 || Main.npc[i].type == 114))
                    {
                        Main.npc[i].HitEffect(hitDirection, num);
                    }
                }
            }
            else
            {
                HitEffect(hitDirection, num);
            }
            if (HitSound != null)
            {
                SoundEngine.PlaySound(HitSound, position);
            }
            if (realLife >= 0)
            {
                Main.npc[realLife].checkDead();
            }
            else
            {
                checkDead();
            }
            return num;
        }
        return 0.0;
    }
References Terraria.Main.CalculateDamageNPCsTake(), Terraria.GameContent.Damage, Terraria.CombatText.DamagedFriendly, Terraria.CombatText.DamagedHostile, Terraria.Main.expertMode, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Gore.NewGore(), Terraria.CombatText.NewText(), Terraria.Main.npc, Terraria.CombatText.OthersDamagedHostile, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.rand.
Referenced by Terraria.Player.ApplyDamageToNPC(), Terraria.Projectile.Damage(), Terraria.MessageBuffer.GetData(), and Terraria.Player.ProcessHitAgainstNPC().