Terraria: Terraria.NPC.DoDeathEvents_AdvanceSlimeRain
DoDeathEvents_AdvanceSlimeRain()
void Terraria.NPC.DoDeathEvents_AdvanceSlimeRain (Player closestPlayer) inline private
Definition at line 71346 of file NPC.cs.
    {
        if (Main.slimeRain && Main.slimeRainNPC[type] && !AnyNPCs(50))
        {
            int num = 150;
            if (downedSlimeKing)
            {
                num /= 2;
            }
            Main.slimeRainKillCount++;
            if (Main.slimeRainKillCount >= num)
            {
                SpawnOnPlayer(closestPlayer.whoAmI, 50);
                Main.slimeRainKillCount = -num / 2;
            }
        }
    }
References Terraria.NPC.AnyNPCs(), Terraria.NPC.downedSlimeKing, Terraria.Main.slimeRain, Terraria.Main.slimeRainKillCount, Terraria.Main.slimeRainNPC, Terraria.NPC.SpawnOnPlayer(), and Terraria.NPC.type.
Referenced by Terraria.NPC.DoDeathEvents().