Terraria: Terraria.NPC.SpawnFaelings
SpawnFaelings()
static void Terraria.NPC.SpawnFaelings (int plr) inline static
Definition at line 77231 of file NPC.cs.
    {
        if (AnyNPCs(677))
        {
            return;
        }
        int num = Main.rand.Next(2, 6);
        int num2 = (int)(Main.player[plr].position.X / 16f) - spawnRangeX * 2;
        int num3 = (int)(Main.player[plr].position.X / 16f) + spawnRangeX * 2;
        int num4 = (int)(Main.player[plr].position.Y / 16f) - spawnRangeY * 2;
        int num5 = (int)(Main.player[plr].position.Y / 16f) + spawnRangeY * 2;
        _ = Main.player[plr].position.X / 16f;
        _ = safeRangeX;
        _ = Main.player[plr].position.X / 16f;
        _ = safeRangeX;
        _ = Main.player[plr].position.Y / 16f;
        _ = safeRangeY;
        _ = Main.player[plr].position.Y / 16f;
        _ = safeRangeY;
        if (num2 < 0)
        {
            num2 = 0;
        }
        if (num3 > Main.maxTilesX)
        {
            num3 = Main.maxTilesX;
        }
        if (num4 < 0)
        {
            num4 = 0;
        }
        if (num5 > Main.maxTilesY)
        {
            num5 = Main.maxTilesY;
        }
        for (int i = 0; i < num; i++)
        {
            int num6 = 1000;
            for (int j = 0; j < num6; j++)
            {
                int num7 = Main.rand.Next(num2, num3);
                int num8 = Main.rand.Next(num4, num5);
                if (Main.tile[num7, num8].liquid <= 0 || !Main.tile[num7, num8].shimmer())
                {
                    continue;
                }
                while (Main.tile[num7, num8].liquid > 0)
                {
                    if (num8 < 50)
                    {
                        return;
                    }
                    num8--;
                }
                bool flag = true;
                Rectangle rectangle = new Rectangle(num7 * 16, num8 * 16, 16, 16);
                for (int k = 0; k < 255; k++)
                {
                    if (Main.player[k].active)
                    {
                        Rectangle rectangle2 = new Rectangle((int)(Main.player[k].position.X + (float)(Main.player[k].width / 2) - (float)(sWidth / 2) - (float)safeRangeX), (int)(Main.player[k].position.Y + (float)(Main.player[k].height / 2) - (float)(sHeight / 2) - (float)safeRangeY), sWidth + safeRangeX * 2, sHeight + safeRangeY * 2);
                        if (rectangle.Intersects(rectangle2))
{
                            flag = false;
                        }
                    }
                }
                if (flag)
                {
                    int num9 = NewNPC(GetSpawnSourceForNaturalSpawn(), num7 * 16 + 8, num8 * 16, 677);
                    if (Main.netMode == 2 && num9 < 200)
                    {
                        NetMessage.SendData(23, -1, -1, null, num9);
                    }
                    break;
                }
            }
        }
    }
References Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Main.player, Terraria.Main.rand, Terraria.NetMessage.SendData(), and Terraria.Main.tile.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.TrySpawningFaelings().