Terraria: Terraria.NPC.AI_121_QueenSlime_GetDustColor
AI_121_QueenSlime_GetDustColor()
static Color Terraria.NPC.AI_121_QueenSlime_GetDustColor () inline static
Definition at line 38257 of file NPC.cs.
    {
        Color value = new Color(0, 160, 255);
        Color value3 = Color.Lerp(value2: new Color(255, 80, 255), value1: new Color(200, 200, 200), amount: Main.rand.NextFloat());
        return Color.Lerp(value, value3, Main.rand.NextFloat());
    }
References Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.rand, and Terraria.NPC.value.
Referenced by Terraria.Projectile.AI_001(), Terraria.NPC.AI_121_QueenSlime(), Terraria.Projectile.AI_135_OgreStomp(), and Terraria.Projectile.Kill().