Terraria: Terraria.NPC.HasLuckTextForWizard
HasLuckTextForWizard()
bool Terraria.NPC.HasLuckTextForWizard (out string specialEventText) inline
Definition at line 91500 of file NPC.cs.
    {
        specialEventText = null;
        object obj = Lang.CreateDialogSubstitutionObject(this);
        if (Main.rand.Next(3) == 0)
        {
            float normalizedLuck = Main.player[Main.myPlayer].NormalizedLuck;
            if (normalizedLuck == 0f)
            {
                return false;
            }
            string text = null;
            text = ((normalizedLuck < -0.6f) ? "WizardSpecialText.LuckIsCursed" : ((normalizedLuck < -0.4f) ? "WizardSpecialText.LuckIsTerrible" : ((normalizedLuck < -0.2f) ? "WizardSpecialText.LuckIsPoor" : ((normalizedLuck < 0f) ? "WizardSpecialText.LuckIsBad" : ((normalizedLuck < 0.25f) ? "WizardSpecialText.LuckIsGood" : ((normalizedLuck < 0.5f) ? "WizardSpecialText.LuckIsGreat" : ((!(normalizedLuck < 0.75f)) ? "WizardSpecialText.LuckIsGodly" : "WizardSpecialText.LuckIsAmazing")))))));
            specialEventText = Language.SelectRandom(Lang.CreateDialogFilter(text)).FormatWith(obj);
            return true;
        }
        return false;
    }
References Terraria.Lang.CreateDialogFilter(), Terraria.Lang.CreateDialogSubstitutionObject(), Terraria.Main.myPlayer, System.obj, Terraria.Main.player, Terraria.Main.rand, Terraria.Localization.Language.SelectRandom(), and System.text.