Terraria: Terraria.NPC.BigMimicSpawnSmoke
BigMimicSpawnSmoke()
void Terraria.NPC.BigMimicSpawnSmoke () inline
Definition at line 69678 of file NPC.cs.
    {
        if (Main.netMode == 2)
        {
            NetMessage.SendData(51, -1, -1, null, whoAmI, 4f);
            return;
        }
        for (int i = 0; i < 20; i++)
        {
            int num = Dust.NewDust(position, width, height, 54, 0f, 0f, 50, default(Color), 1.5f);
            Main.dust[num].velocity *= 2f;
            Main.dust[num].noGravity = true;
        }
        for (int j = 0; j < 3; j++)
        {
            for (int k = 0; k < 2; k++)
            {
                int num2 = Gore.NewGore(new Vector2(position.X + (float)(width * j) * 0.45f - 20f, position.Y + (float)(height * k) * 0.5f + 10f), new Vector2(0f, 0f), 99, 1.1f);
                Main.gore[num2].velocity *= 0.3f;
            }
        }
    }
References Terraria.Main.dust, Terraria.Main.gore, Terraria.Entity.height, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Entity.position, Terraria.NetMessage.SendData(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.whoAmI, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.