Terraria: Terraria.NPC.SpawnNPC
SpawnNPC()
static void Terraria.NPC.SpawnNPC () inline static
References Terraria.ID.WallID.Sets.AllowsUndergroundDesertEnemiesToSpawn, Terraria.WorldGen.beachDistance, Terraria.Main.bloodMoon, Terraria.GameContent.CoinLossRevengeSystem.CheckRespawns(), Terraria.WorldGen.checkUnderground(), Terraria.Main.cloudAlpha, Terraria.Main.cloudBGActive, Terraria.ID.TileID.Sets.Corrupt, Terraria.ID.TileID.Sets.Crimson, Terraria.Main.dayTime, Terraria.Main.dontStarveWorld, Terraria.Main.drunkWorld, Terraria.Main.dungeonY, Terraria.Main.eclipse, Terraria.Main.expertMode, Terraria.Main.GameModeInfo, Terraria.Main.getGoodWorld, Terraria.ID.TileID.Sets.Hallow, Terraria.Main.halloween, Terraria.GameContent.Events.Sandstorm.Happening, Terraria.Main.hardMode, Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.Main.invasionDelay, Terraria.Main.invasionSize, Terraria.Main.invasionSizeStart, Terraria.Main.invasionType, Terraria.Main.invasionX, Terraria.Main.IsItAHappyWindyDay, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.moonPhase, Terraria.Main.netMode, Terraria.Main.npc, Terraria.Main.numClouds, Terraria.WorldGen.oceanDepths(), Terraria.WorldGen.oceanDistance, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.GameContent.Events.BirthdayParty.PartyIsUp, Terraria.Main.player, Terraria.Main.pumpkinMoon, Terraria.Main.raining, Terraria.Main.rand, Terraria.GameContent.Events.DD2Event.ReadyToFindBartender, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.NetMessage.SendData(), Terraria.WorldGen.shadowOrbSmashed, Terraria.Main.slimeRain, Terraria.Main.snowMoon, Terraria.WorldGen.SolidTile(), Terraria.Collision.SolidTiles(), Terraria.GameContent.Events.DD2Event.SpawnNPC(), Terraria.Main.spawnTileX, Terraria.Star.starfallBoost, Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Main.tileSand, Terraria.Main.tileSolid, Terraria.Main.time, Terraria.Main.UnderworldLayer, Terraria.Main.wallHouse, Terraria.Main.wallLight, Terraria.Main.windSpeedTarget, Terraria.Main.wofNPCIndex, Terraria.Main.worldSurface, and Terraria.Main.xMas.
Referenced by Terraria.Main.DoUpdateInWorld().