Terraria: Terraria.NPC.GetBirdFlightRecommendation
GetBirdFlightRecommendation()
void Terraria.NPC.GetBirdFlightRecommendation (int downScanRange, int upRange, Point tCoords, out bool goDownwards, out bool goUpwards) inline private
Definition at line 41905 of file NPC.cs.
    {
        tCoords.X += direction;
        goDownwards = true;
        goUpwards = false;
        int x = tCoords.X;
        for (int i = tCoords.Y; i < tCoords.Y + downScanRange && WorldGen.InWorld(x, i); i++)
        {
            Tile tile = Main.tile[x, i];
            if (tile == null)
            {
                break;
            }
            if ((tile.nactive() && Main.tileSolid[tile.type]) || tile.liquid > 0)
            {
                if (i < tCoords.Y + upRange)
                {
                    goUpwards = true;
                }
                goDownwards = false;
                break;
            }
        }
    }
References Terraria.Entity.direction, Terraria.WorldGen.InWorld(), Terraria.Tile.nactive(), Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.NPC.AI_112_FairyCritter().