Terraria: Terraria.NPC.AI
AI()
void Terraria.NPC.AI () inline
References Terraria.Entity.active, Terraria.NPC.activeTime, Terraria.GameContent.Events.MoonlordDeathDrama.AddExplosion(), Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.NPC.AI_000_TransformBoundNPC(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_002_FloatingEye(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_045_Golem(), Terraria.NPC.AI_047_GolemFist(), Terraria.NPC.AI_065_Butterflies(), Terraria.NPC.AI_069_DukeFishron(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_114_Dragonflies(), Terraria.NPC.AI_115_LadyBugs(), Terraria.NPC.AI_116_WaterStriders(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_118_Seahorses(), Terraria.NPC.AI_119_Dandelion(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_122_PirateGhost(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_124_ElderSlimeChest(), Terraria.NPC.AI_125_ClumsySlimeBalloon(), Terraria.NPC.AI_87_BigMimic_FireStuffCannonBurst(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.NPC.aiAction, Terraria.NPC.aiStyle, Terraria.NPC.alpha, Terraria.NPC.AnyNPCs(), Terraria.NPC.brainOfGravity, Terraria.DataStructures.TileEntity.ByID, Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.StrayMethods.CanSpawnSandstormHostile(), Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.WorldBuilding.Searches.Chain(), Terraria.StrayMethods.CheckArenaScore(), Terraria.NPC.checkDead(), Terraria.GameContent.Events.CultistRitual.CheckFloor(), Terraria.Main.cloudAlpha, Terraria.NPC.collideX, Terraria.NPC.collideY, Terraria.NPC.color, Terraria.NPC.confused, Terraria.NPC.CountNPCS(), Terraria.NPC.crimsonBoss, Terraria.NPC.damage, Terraria.Main.dayTime, Terraria.ID.SoundID.DD2_EtherianPortalIdleLoop, Terraria.ID.SoundID.DD2_EtherianPortalOpen, Terraria.ID.SoundID.DD2_WinScene, Terraria.NPC.DeathSound, Terraria.Main.dedServ, Terraria.NPC.defDamage, Terraria.NPC.defDefense, Terraria.NPC.defense, Terraria.Entity.direction, Terraria.Entity.DirectionFrom(), Terraria.Entity.DirectionTo(), Terraria.NPC.directionY, Terraria.NPC.DiscourageDespawn(), Terraria.Entity.Distance(), Terraria.NPC.dontTakeDamage, Terraria.NPC.dontTakeDamageFromHostiles, Terraria.Main.dust, Terraria.Main.eclipse, Terraria.NPC.EncourageDespawn(), Terraria.GameContent.Events.DD2Event.EnemySpawningIsOnHold, Terraria.Collision.ExpandVertically(), Terraria.Main.expertMode, Terraria.GameContent.Tile_Entities.TETrainingDummy.Find(), Terraria.WorldBuilding.WorldUtils.Find(), Terraria.GameContent.Events.DD2Event.FindArenaHitbox(), Terraria.Player.FindClosest(), Terraria.NPC.FindClosestPlayer(), Terraria.NPC.FindFirstNPC(), Terraria.NPC.frameCounter, Terraria.NPC.friendly, ReLogic.Utilities.SlotId.FromFloat(), Terraria.Main.GameModeInfo, Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.NPC.GetAttackDamage_ForProjectiles(), Terraria.NPC.GetAttackDamage_LerpBetweenFinalValues(), Terraria.NPC.GetAttackDamage_ScaledByStrength(), Terraria.NPC.GetBrainOfCthuluCreepersCount(), Terraria.Main.getGoodWorld, Terraria.Utils.GetLerpValue(), Terraria.NPC.GetMyBalance(), Terraria.NPC.getRect(), Terraria.NPC.GetShimmered(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSpawnSourceForNaturalSpawn(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.NPC.GetSpawnSourceForProjectileNPC(), Terraria.Framing.GetTileSafely(), Terraria.Collision.GetWaterLine(), Terraria.NPC.gfxOffY, Terraria.NPC.golemBoss, Terraria.Main.gore, Terraria.ID.TileID.Sets.Conversion.HardenedSand, Terraria.NPC.HealEffect(), Terraria.Entity.height, Terraria.NPC.hide, Terraria.NPC.HitEffect(), Terraria.NPC.HitSound, Terraria.NPC.InitializeMoonLordAttacks(), ReLogic.Utilities.SlotId.Invalid, Terraria.WorldGen.InWorld(), Terraria.Main.IsItDay(), Terraria.NPC.IsMechQueenUp, Terraria.ID.SoundID.Item12, Terraria.ID.SoundID.Item14, Terraria.ID.SoundID.Item17, Terraria.ID.SoundID.Item34, Terraria.ID.SoundID.Item39, Terraria.ID.SoundID.Item5, Terraria.ID.SoundID.Item8, Terraria.NPC.justHit, Terraria.Projectile.Kill(), Terraria.NPC.knockBackResist, Terraria.GameContent.Events.DD2Event.LaneSpawnRate, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.NPC.LunarApocalypseIsUp, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.NPC.mechQueen, Terraria.NPC.MoonLordAttacksArray, Terraria.NPC.MoonLordAttacksArray2, Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netOffset, Terraria.NPC.netSpam, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGore(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.NPC.noGravity, Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.NPC.NPCCanStickToWalls(), Terraria.ID.SoundID.NPCDeath3, Terraria.ID.SoundID.NPCDeath58, Terraria.ID.SoundID.NPCDeath61, Terraria.ID.SoundID.NPCHit15, Terraria.ID.SoundID.NPCHit16, Terraria.ID.SoundID.NPCHit17, Terraria.ID.SoundID.NPCHit4, Terraria.NPC.npcsFoundForCheckActive, Terraria.Entity.oldPosition, Terraria.Entity.oldVelocity, Terraria.NPC.Opacity, Terraria.NPC.plantBoss, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.NPC.PopAllAttachedProjectilesAndTakeDamageForThem(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.GameContent.FixExploitManEaters.ProtectSpot(), Terraria.Main.pumpkinMoon, Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.NPC.realLife, Terraria.NPC.ReflectProjectiles(), Terraria.NPC.reflectsProjectiles, Terraria.NPC.releaseOwner, Terraria.Main.remixWorld, Terraria.GameContent.Events.DD2Event.ReportLoss(), Terraria.GameContent.Events.MoonlordDeathDrama.RequestLight(), Terraria.NPC.rotation, Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.ID.TileID.Sets.Conversion.Sandstone, Terraria.NPC.scale, Terraria.Graphics.Effects.Filters.Scene, Terraria.NetMessage.SendData(), Terraria.NPC.ShieldStrengthTowerNebula, Terraria.NPC.ShieldStrengthTowerSolar, Terraria.NPC.ShieldStrengthTowerStardust, Terraria.NPC.ShieldStrengthTowerVortex, Terraria.Tile.shimmer(), Terraria.NPC.SimpleFlyMovement(), Terraria.Main.snowMoon, Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile2(), Terraria.Collision.SolidTiles(), Terraria.NPC.soundDelay, Terraria.GameContent.Events.DD2Event.SpawnMonsterFromGate(), Terraria.WorldGen.SpawnPlanteraThorns(), Terraria.NPC.SpawnStardustMark_StardustTower(), Terraria.NPC.spriteDirection, Terraria.Main.StartInvasion(), Terraria.NPC.stepSpeed, Terraria.GameContent.Events.DD2Event.StopInvasion(), Terraria.NPC.StrikeNPCNoInteraction(), Terraria.GameContent.Events.CultistRitual.TabletDestroyed(), Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.NPC.TargetClosest_WOF(), Terraria.NPC.targetRect, Terraria.Main.tenthAnniversaryWorld, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.NPC.timeLeft, Terraria.NPC.Transform(), Terraria.NPC.type, Terraria.Projectile.type, Terraria.Main.UnderworldLayer, Terraria.NPC.value, Terraria.Utils.Vector2FromElipse(), Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.whoAmI, Terraria.Entity.width, Terraria.Main.wofDrawAreaBottom, Terraria.Main.wofDrawAreaTop, Terraria.Main.wofNPCIndex, and Terraria.Main.worldSurface.