Terraria: Terraria.NPC.Boss_CanShootExtraAt
Boss_CanShootExtraAt()
bool Terraria.NPC.Boss_CanShootExtraAt (int playerIndex, int rotationIndexToAttack, int rotationSize, float attackScanDistance, bool alwaysSkipMainTarget = true) inline
Definition at line 40172 of file NPC.cs.
    {
        if (playerIndex == target && alwaysSkipMainTarget)
        {
            return false;
        }
        if (playerIndex % rotationSize != rotationIndexToAttack)
        {
            return false;
        }
        Player player = Main.player[playerIndex];
        if (!player.active || player.dead || !playerInteraction[playerIndex])
        {
            return false;
        }
        if (Distance(player.Center) > attackScanDistance)
        {
            return false;
        }
        return true;
    }
References Terraria.Entity.active, Terraria.Entity.Center, Terraria.Player.dead, Terraria.Entity.Distance(), Terraria.Main.player, Terraria.NPC.playerInteraction, and Terraria.NPC.target.
Referenced by Terraria.NPC.AI_120_HallowBoss(), and Terraria.NPC.SpawnPassiveShadowHands().