Terraria: Terraria.NPC.ShouldFaceTarget
ShouldFaceTarget()
bool Terraria.NPC.ShouldFaceTarget (ref NPCUtils::TargetSearchResults searchResults, NPCUtils::TargetType? overrideTargetType = null) inline
Definition at line 69788 of file NPC.cs.
    {
        NPCUtils.TargetType nearestTargetType = searchResults.NearestTargetType;
        if (overrideTargetType.HasValue)
        {
            nearestTargetType = overrideTargetType.Value;
        }
        switch (nearestTargetType)
        {
        case NPCUtils.TargetType.NPC:
        case NPCUtils.TargetType.TankPet:
            return true;
        case NPCUtils.TargetType.Player:
        {
            bool flag = true;
            Player nearestTankOwner = searchResults.NearestTankOwner;
            if (nearestTankOwner.dead || (nearestTankOwner.npcTypeNoAggro[type] && direction != 0))
            {
                flag = false;
            }
            if (!flag)
            {
                break;
            }
            float num = (float)(nearestTankOwner.width + nearestTankOwner.height + width + height) / 4f + 800f;
            if (nearestTankOwner.itemAnimation == 0 && nearestTankOwner.aggro < 0 && searchResults.NearestTankDistance > num)
            {
                if (oldTarget >= 0)
                {
                    return oldTarget >= 255;
                }
                return true;
            }
            return true;
        }
        }
        return false;
    }
References Terraria.Entity.direction, Terraria.Entity.height, Terraria.NPC.oldTarget, Terraria.NPC.type, ReLogic.Content.Asset< T >.Value, and Terraria.Entity.width.
Referenced by Terraria.Utilities.NPCUtils.TargetClosestBetsy(), Terraria.Utilities.NPCUtils.TargetClosestDownwindFromNPC(), Terraria.Utilities.NPCUtils.TargetClosestNonBees(), and Terraria.Utilities.NPCUtils.TargetClosestOldOnesInvasion().