Terraria: Terraria.NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot
GetAvailableAmountOfNPCsToSpawnUpToSlot()
static int Terraria.NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot (int amountWeWant, int highestNPCSlotIndexWeWillPick = 100) inline static
Definition at line 77558 of file NPC.cs.
    {
        if (amountWeWant <= 0)
        {
            return 0;
        }
        int num = 0;
        for (int i = 0; i < highestNPCSlotIndexWeWillPick; i++)
        {
            if (!Main.npc[i].active)
            {
                num++;
                if (num >= amountWeWant)
                {
                    return amountWeWant;
                }
            }
        }
        return num;
    }
References Terraria.Main.npc.
Referenced by Terraria.WorldGen.CheckSuper(), Terraria.Item.GetShimmered(), and Terraria.Projectile.Kill().