Terraria: Terraria.NPC.FaceTarget
FaceTarget()
void Terraria.NPC.FaceTarget () inline
Definition at line 69827 of file NPC.cs.
    {
        direction = ((!((float)targetRect.Center.X < base.Center.X)) ? 1 : (-1));
        directionY = ((!((float)targetRect.Center.Y < base.Center.Y)) ? 1 : (-1));
    }
References Microsoft.Xna.Framework.Rectangle.Center, Terraria.Entity.direction, Terraria.NPC.directionY, Terraria.NPC.targetRect, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Utilities.NPCUtils.TargetClosestBetsy(), Terraria.Utilities.NPCUtils.TargetClosestDownwindFromNPC(), Terraria.Utilities.NPCUtils.TargetClosestNonBees(), and Terraria.Utilities.NPCUtils.TargetClosestOldOnesInvasion().