Terraria: Terraria.GameContent.UI.BigProgressBar.BrainOfCthuluBigProgressBar.ValidateAndCollectNecessaryInfo
ValidateAndCollectNecessaryInfo()
bool Terraria.GameContent.UI.BigProgressBar.BrainOfCthuluBigProgressBar.ValidateAndCollectNecessaryInfo (ref BigProgressBarInfo info) inline
Implements Terraria.GameContent.UI.BigProgressBar.IBigProgressBar.
    {
        if (info.npcIndexToAimAt < 0 || info.npcIndexToAimAt > 200)
        {
            return false;
        }
        NPC nPC = Main.npc[info.npcIndexToAimAt];
        if (!nPC.active)
        {
            return false;
        }
        int brainOfCthuluCreepersCount = NPC.GetBrainOfCthuluCreepersCount();
        _creeperForReference.SetDefaults(267, nPC.GetMatchingSpawnParams());
        int num = _creeperForReference.lifeMax * brainOfCthuluCreepersCount;
        float num2 = 0f;
        for (int i = 0; i < 200; i++)
        {
            NPC nPC2 = Main.npc[i];
            if (nPC2.active && nPC2.type == _creeperForReference.type)
            {
                num2 += (float)nPC2.life;
            }
        }
        float current = (float)nPC.life + num2;
        int num3 = nPC.lifeMax + num;
        _cache.SetLife(current, num3);
        return true;
    }
References Terraria.GameContent.UI.BigProgressBar.BrainOfCthuluBigProgressBar._cache, Terraria.GameContent.UI.BigProgressBar.BrainOfCthuluBigProgressBar._creeperForReference, Terraria.Entity.active, Terraria.NPC.GetBrainOfCthuluCreepersCount(), Terraria.NPC.GetMatchingSpawnParams(), Terraria.NPC.life, Terraria.Main.npc, Terraria.NPC.SetDefaults(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarCache.SetLife(), and Terraria.NPC.type.