Terraria: System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStack
EnsureStack()
void System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStack () inline
Definition at line 176 of file IteratorDescriptor.cs.
    {
        switch (_storage.Location)
        {
        case ItemLocation.Stack:
            return;
        case ItemLocation.Parameter:
        case ItemLocation.Local:
        case ItemLocation.Current:
            PushValue();
            break;
        case ItemLocation.Global:
            _helper.LoadQueryRuntime();
            _helper.Call(_storage.GlobalLocation);
            break;
        }
        _storage = _storage.ToStack();
    }
References System.Xml.Xsl.IlGen.IteratorDescriptor._helper, System.Xml.Xsl.IlGen.IteratorDescriptor._storage, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.StorageDescriptor.GlobalLocation, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.StorageDescriptor.Location, System.Xml.Xsl.IlGen.IteratorDescriptor.PushValue(), and System.Xml.Xsl.IlGen.StorageDescriptor.ToStack().
Referenced by System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureLocal(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStackNoCache(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFor(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound().