Terraria: System.Xml.Xsl.IlGen.IteratorDescriptor.PushValue
PushValue()
void System.Xml.Xsl.IlGen.IteratorDescriptor.PushValue () inline
Definition at line 153 of file IteratorDescriptor.cs.
    {
        switch (_storage.Location)
        {
        case ItemLocation.Stack:
            _helper.Emit(OpCodes.Dup);
            break;
        case ItemLocation.Parameter:
            _helper.LoadParameter(_storage.ParameterLocation);
            break;
        case ItemLocation.Local:
            _helper.Emit(OpCodes.Ldloc, _storage.LocalLocation);
            break;
        case ItemLocation.Current:
        {
            CurrentContext currentLocation = _storage.CurrentLocation;
            _helper.Emit(OpCodes.Ldloca, currentLocation.Local);
            _helper.Call(currentLocation.CurrentMethod);
            break;
        }
        }
    }
References System.Xml.Xsl.IlGen.IteratorDescriptor._helper, System.Xml.Xsl.IlGen.IteratorDescriptor._storage, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.StorageDescriptor.CurrentLocation, System.Reflection.Emit.OpCodes.Dup, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Xml.Xsl.IlGen.GenerateHelper.LoadParameter(), System.Xml.Xsl.IlGen.StorageDescriptor.LocalLocation, System.Xml.Xsl.IlGen.StorageDescriptor.Location, and System.Xml.Xsl.IlGen.StorageDescriptor.ParameterLocation.
Referenced by System.Xml.Xsl.IlGen.IteratorDescriptor.CacheCount(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStack(), and System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator().