Terraria: System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache
EnsureNoCache()
void System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache () inline
Definition at line 115 of file IteratorDescriptor.cs.
    {
        if (_storage.IsCached)
        {
            if (!HasLabelNext)
            {
                EnsureStack();
                _helper.LoadInteger(0);
                _helper.CallCacheItem(_storage.ItemStorageType);
                _storage = StorageDescriptor.Stack(_storage.ItemStorageType, isCached: false);
                return;
            }
            LocalBuilder locBldr = _helper.DeclareLocal("$$$idx", typeof(int));
            EnsureNoStack("$$$cache");
            _helper.LoadInteger(-1);
            _helper.Emit(OpCodes.Stloc, locBldr);
            Label label = _helper.DefineLabel();
            _helper.MarkLabel(label);
            _helper.Emit(OpCodes.Ldloc, locBldr);
            _helper.LoadInteger(1);
            _helper.Emit(OpCodes.Add);
            _helper.Emit(OpCodes.Stloc, locBldr);
            _helper.Emit(OpCodes.Ldloc, locBldr);
            CacheCount();
            _helper.Emit(OpCodes.Bge, GetLabelNext());
            PushValue();
            _helper.Emit(OpCodes.Ldloc, locBldr);
            _helper.CallCacheItem(_storage.ItemStorageType);
            SetIterator(label, StorageDescriptor.Stack(_storage.ItemStorageType, isCached: false));
        }
    }
References System.Xml.Xsl.IlGen.IteratorDescriptor._helper, System.Xml.Xsl.IlGen.IteratorDescriptor._storage, System.Reflection.Emit.OpCodes.Add, System.Reflection.Emit.OpCodes.Bge, System.Xml.Xsl.IlGen.IteratorDescriptor.CacheCount(), System.Xml.Xsl.IlGen.GenerateHelper.CallCacheItem(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoStack(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStack(), System.Xml.Xsl.IlGen.IteratorDescriptor.GetLabelNext(), System.Xml.Xsl.IlGen.IteratorDescriptor.HasLabelNext, System.Xml.Xsl.IlGen.StorageDescriptor.IsCached, System.Xml.Xsl.IlGen.StorageDescriptor.ItemStorageType, System.Reflection.Emit.OpCodes.Ldloc, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.IteratorDescriptor.PushValue(), System.Xml.Xsl.IlGen.IteratorDescriptor.SetIterator(), System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), and System.Reflection.Emit.OpCodes.Stloc.
Referenced by System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureLocalNoCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureLocalNoCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoStackNoCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStackNoCache(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength().