Terraria: System.Xml.Xsl.IlGen.IteratorDescriptor.DiscardStack
DiscardStack()
void System.Xml.Xsl.IlGen.IteratorDescriptor.DiscardStack () inline
Definition at line 228 of file IteratorDescriptor.cs.
    {
        if (_storage.Location == ItemLocation.Stack)
        {
            _helper.Emit(OpCodes.Pop);
            _storage = StorageDescriptor.None();
        }
    }
References System.Xml.Xsl.IlGen.IteratorDescriptor._helper, System.Xml.Xsl.IlGen.IteratorDescriptor._storage, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.StorageDescriptor.Location, System.Xml.Xsl.IlGen.StorageDescriptor.None(), and System.Reflection.Emit.OpCodes.Pop.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength().