Terraria: System.Xml.Xsl.IlGen.IteratorDescriptor.SetIterator
SetIterator() [2/2]
void System.Xml.Xsl.IlGen.IteratorDescriptor.SetIterator (Label lblNext, StorageDescriptor storage) inline
Definition at line 82 of file IteratorDescriptor.cs.
    {
        _lblNext = lblNext;
        _hasNext = true;
        _storage = storage;
    }
References System.Xml.Xsl.IlGen.IteratorDescriptor._hasNext, System.Xml.Xsl.IlGen.IteratorDescriptor._lblNext, System.Xml.Xsl.IlGen.IteratorDescriptor._storage, and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFilter(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort().