Terraria: CreativePowers.ASharedTogglePower.ProvidePowerButtons
ProvidePowerButtons()
void CreativePowers.ASharedTogglePower.ProvidePowerButtons (CreativePowerUIElementRequestInfo info, List< UIElement > elements) inline inherited
Implements ICreativePower.
         {
             GroupOptionButton<bool> groupOptionButton = CreativePowersHelper.CreateToggleButton(info);
             CreativePowersHelper.UpdateUnlockStateByPower(this, groupOptionButton, Main.OurFavoriteColor);
             CustomizeButton(groupOptionButton);
             groupOptionButton.OnLeftClick += button_OnClick;
             groupOptionButton.OnUpdate += button_OnUpdate;
             elements.Add(groupOptionButton);
         }
References CreativePowers.ASharedTogglePower.button_OnClick(), CreativePowers.ASharedTogglePower.button_OnUpdate(), CreativePowersHelper.CreateToggleButton(), CreativePowers.ASharedTogglePower.CustomizeButton(), UIElement.OnLeftClick, UIElement.OnUpdate, Main.OurFavoriteColor, and CreativePowersHelper.UpdateUnlockStateByPower().