Terraria: System.Reflection.Metadata.Ecma335.NestedClassTableReader.GetEnclosingClass
GetEnclosingClass()
TypeDefinitionHandle System.Reflection.Metadata.Ecma335.NestedClassTableReader.GetEnclosingClass (int rowId) inline package
Definition at line 39 of file NestedClassTableReader.cs.
    {
        int num = (rowId - 1) * RowSize;
        return TypeDefinitionHandle.FromRowId(Block.PeekReference(num + _EnclosingClassOffset, _IsTypeDefTableRowRefSizeSmall));
    }
References System.Reflection.Metadata.Ecma335.NestedClassTableReader._EnclosingClassOffset, System.Reflection.Metadata.Ecma335.NestedClassTableReader._IsTypeDefTableRowRefSizeSmall, System.Reflection.Metadata.Ecma335.NestedClassTableReader.Block, System.Reflection.Metadata.TypeDefinitionHandle.FromRowId(), System.Reflection.Internal.MemoryBlock.PeekReference(), and System.Reflection.Metadata.Ecma335.NestedClassTableReader.RowSize.
Referenced by System.Reflection.Metadata.MetadataReader.InitializeNestedTypesMap().