Terraria: System.Reflection.Emit.CustomAttributeBuilder.CreateCustomAttribute
CreateCustomAttribute()
void System.Reflection.Emit.CustomAttributeBuilder.CreateCustomAttribute (ModuleBuilder mod, int tkOwner) inline package
Definition at line 448 of file CustomAttributeBuilder.cs.
    {
        TypeBuilder.DefineCustomAttribute(mod, tkOwner, mod.GetConstructorToken(m_con), m_blob);
    }
References System.Reflection.Emit.TypeBuilder.DefineCustomAttribute(), System.Reflection.Emit.ModuleBuilder.GetConstructorToken(), System.Reflection.Emit.CustomAttributeBuilder.m_blob, and System.Reflection.Emit.CustomAttributeBuilder.m_con.
Referenced by System.Reflection.Emit.TypeBuilder.CustAttr.Bake(), System.Reflection.Emit.EventBuilder.SetCustomAttribute(), System.Reflection.Emit.FieldBuilder.SetCustomAttribute(), System.Reflection.Emit.MethodBuilder.SetCustomAttribute(), System.Reflection.Emit.ParameterBuilder.SetCustomAttribute(), and System.Reflection.Emit.PropertyBuilder.SetCustomAttribute().