Terraria: System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder
CustomAttributeBuilder() [4/4]
System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder (ConstructorInfo con, object?[] constructorArgs, PropertyInfo[] namedProperties, object?[] propertyValues, FieldInfo[] namedFields, object?[] fieldValues) inline
Definition at line 30 of file CustomAttributeBuilder.cs.
    {
        if (con == null)
        {
            throw new ArgumentNullException("con");
        }
        if (constructorArgs == null)
        {
            throw new ArgumentNullException("constructorArgs");
        }
        if (namedProperties == null)
        {
            throw new ArgumentNullException("namedProperties");
        }
        if (propertyValues == null)
        {
            throw new ArgumentNullException("propertyValues");
        }
        if (namedFields == null)
        {
            throw new ArgumentNullException("namedFields");
        }
        if (fieldValues == null)
        {
            throw new ArgumentNullException("fieldValues");
        }
        if (namedProperties.Length != propertyValues.Length)
        {
            throw new ArgumentException(SR.Arg_ArrayLengthsDiffer, "namedProperties, propertyValues");
        }
        if (namedFields.Length != fieldValues.Length)
        {
            throw new ArgumentException(SR.Arg_ArrayLengthsDiffer, "namedFields, fieldValues");
        }
        if ((con.Attributes & MethodAttributes.Static) == MethodAttributes.Static || (con.Attributes & MethodAttributes.MemberAccessMask) == MethodAttributes.Private)
        {
            throw new ArgumentException(SR.Argument_BadConstructor);
        }
        if ((con.CallingConvention & CallingConventions.Standard) != CallingConventions.Standard)
        {
            throw new ArgumentException(SR.Argument_BadConstructorCallConv);
        }
        m_con = con;
        m_constructorArgs = new object[constructorArgs.Length];
        Array.Copy(constructorArgs, m_constructorArgs, constructorArgs.Length);
        Type[] parameterTypes = con.GetParameterTypes();
        if (parameterTypes.Length != constructorArgs.Length)
        {
            throw new ArgumentException(SR.Argument_BadParameterCountsForConstructor);
        }
        for (int i = 0; i < parameterTypes.Length; i++)
        {
            if (!ValidateType(parameterTypes[i]))
            {
                throw new ArgumentException(SR.Argument_BadTypeInCustomAttribute);
            }
        }
        for (int i = 0; i < parameterTypes.Length; i++)
        {
            object obj = constructorArgs[i];
            if (obj == null)
            {
                if (parameterTypes[i].IsValueType)
                {
                    throw new ArgumentNullException($"{"constructorArgs"}[{i}]");
                }
            }
            else
            {
                VerifyTypeAndPassedObjectType(parameterTypes[i], obj.GetType(), $"{"constructorArgs"}[{i}]");
            }
        }
        MemoryStream output = new MemoryStream();
        BinaryWriter binaryWriter = new BinaryWriter(output);
        binaryWriter.Write((ushort)1);
        for (int i = 0; i < constructorArgs.Length; i++)
        {
            EmitValue(binaryWriter, parameterTypes[i], constructorArgs[i]);
        }
        binaryWriter.Write((ushort)(namedProperties.Length + namedFields.Length));
        for (int i = 0; i < namedProperties.Length; i++)
        {
            PropertyInfo propertyInfo = namedProperties[i];
            if (propertyInfo == null)
            {
                throw new ArgumentNullException("namedProperties[" + i + "]");
            }
            Type propertyType = propertyInfo.PropertyType;
            object obj2 = propertyValues[i];
            if (obj2 == null && propertyType.IsValueType)
            {
                throw new ArgumentNullException("propertyValues[" + i + "]");
            }
            if (!ValidateType(propertyType))
            {
                throw new ArgumentException(SR.Argument_BadTypeInCustomAttribute);
            }
            if (!propertyInfo.CanWrite)
            {
                throw new ArgumentException(SR.Argument_NotAWritableProperty);
            }
            if (propertyInfo.DeclaringType != con.DeclaringType && !(con.DeclaringType is TypeBuilderInstantiation) && !con.DeclaringType.IsSubclassOf(propertyInfo.DeclaringType) && !TypeBuilder.IsTypeEqual(propertyInfo.DeclaringType, con.DeclaringType) && (!(propertyInfo.DeclaringType is TypeBuilder) || !con.DeclaringType.IsSubclassOf(((TypeBuilder)propertyInfo.DeclaringType).BakedRuntimeType)))
            {
                throw new ArgumentException(SR.Argument_BadPropertyForConstructorBuilder);
            }
            if (obj2 != null)
            {
                VerifyTypeAndPassedObjectType(propertyType, obj2.GetType(), $"{"propertyValues"}[{i}]");
            }
            binaryWriter.Write((byte)84);
            EmitType(binaryWriter, propertyType);
            EmitString(binaryWriter, namedProperties[i].Name);
            EmitValue(binaryWriter, propertyType, obj2);
        }
        for (int i = 0; i < namedFields.Length; i++)
        {
            FieldInfo fieldInfo = namedFields[i];
            if (fieldInfo == null)
            {
                throw new ArgumentNullException("namedFields[" + i + "]");
            }
            Type fieldType = fieldInfo.FieldType;
            object obj3 = fieldValues[i];
            if (obj3 == null && fieldType.IsValueType)
            {
                throw new ArgumentNullException("fieldValues[" + i + "]");
            }
            if (!ValidateType(fieldType))
            {
                throw new ArgumentException(SR.Argument_BadTypeInCustomAttribute);
            }
            if (fieldInfo.DeclaringType != con.DeclaringType && !(con.DeclaringType is TypeBuilderInstantiation) && !con.DeclaringType.IsSubclassOf(fieldInfo.DeclaringType) && !TypeBuilder.IsTypeEqual(fieldInfo.DeclaringType, con.DeclaringType) && (!(fieldInfo.DeclaringType is TypeBuilder) || !con.DeclaringType.IsSubclassOf(((TypeBuilder)namedFields[i].DeclaringType).BakedRuntimeType)))
            {
                throw new ArgumentException(SR.Argument_BadFieldForConstructorBuilder);
            }
            if (obj3 != null)
            {
                VerifyTypeAndPassedObjectType(fieldType, obj3.GetType(), $"{"fieldValues"}[{i}]");
            }
            binaryWriter.Write((byte)83);
            EmitType(binaryWriter, fieldType);
            EmitString(binaryWriter, fieldInfo.Name);
            EmitValue(binaryWriter, fieldType, obj3);
        }
        m_blob = ((MemoryStream)binaryWriter.BaseStream).ToArray();
    }
References System.SR.Arg_ArrayLengthsDiffer, System.SR.Argument_BadConstructor, System.SR.Argument_BadConstructorCallConv, System.SR.Argument_BadFieldForConstructorBuilder, System.SR.Argument_BadParameterCountsForConstructor, System.SR.Argument_BadPropertyForConstructorBuilder, System.SR.Argument_BadTypeInCustomAttribute, System.SR.Argument_NotAWritableProperty, System.Reflection.MethodBase.Attributes, System.IO.BinaryWriter.BaseStream, System.Reflection.MethodBase.CallingConvention, System.Reflection.PropertyInfo.CanWrite, System.Array.Copy(), System.Reflection.MemberInfo.DeclaringType, System.Reflection.Emit.CustomAttributeBuilder.EmitString(), System.Reflection.Emit.CustomAttributeBuilder.EmitType(), System.Reflection.Emit.CustomAttributeBuilder.EmitValue(), System.Reflection.FieldInfo.FieldType, System.Reflection.MethodBase.GetParameterTypes(), System.Type.GetType(), System.Type.IsSubclassOf(), System.Reflection.Emit.TypeBuilder.IsTypeEqual(), System.Type.IsValueType, System.Reflection.Emit.CustomAttributeBuilder.m_blob, System.Reflection.Emit.CustomAttributeBuilder.m_con, System.Reflection.Emit.CustomAttributeBuilder.m_constructorArgs, System.Reflection.MemberInfo.Name, System.Reflection.Name, System.obj, System.Reflection.PropertyInfo.PropertyType, System.Reflection.Emit.CustomAttributeBuilder.ValidateType(), System.Reflection.Emit.CustomAttributeBuilder.VerifyTypeAndPassedObjectType(), and System.IO.BinaryWriter.Write().