Terraria: System.Reflection.Emit.CustomAttributeBuilder.EmitValue
EmitValue()
static void System.Reflection.Emit.CustomAttributeBuilder.EmitValue (BinaryWriter writer, Type type, object value) inline static private
Definition at line 310 of file CustomAttributeBuilder.cs.
    {
        if (type.IsEnum)
        {
            switch (Type.GetTypeCode(Enum.GetUnderlyingType(type)))
            {
            case TypeCode.SByte:
                writer.Write((sbyte)value);
                break;
            case TypeCode.Byte:
                writer.Write((byte)value);
                break;
            case TypeCode.Int16:
                writer.Write((short)value);
                break;
            case TypeCode.UInt16:
                writer.Write((ushort)value);
                break;
            case TypeCode.Int32:
                writer.Write((int)value);
                break;
            case TypeCode.UInt32:
                writer.Write((uint)value);
                break;
            case TypeCode.Int64:
                writer.Write((long)value);
                break;
            case TypeCode.UInt64:
                writer.Write((ulong)value);
                break;
            }
            return;
        }
        if (type == typeof(string))
        {
            if (value == null)
            {
                writer.Write(byte.MaxValue);
            }
            else
            {
                EmitString(writer, (string)value);
            }
            return;
        }
        if (type == typeof(Type))
        {
            if (value == null)
            {
                writer.Write(byte.MaxValue);
                return;
            }
            string text = TypeNameBuilder.ToString((Type)value, TypeNameBuilder.Format.AssemblyQualifiedName);
            if (text == null)
            {
                throw new ArgumentException(SR.Format(SR.Argument_InvalidTypeForCA, value.GetType()));
            }
            EmitString(writer, text);
            return;
        }
        if (type.IsArray)
        {
            if (value == null)
            {
                writer.Write(uint.MaxValue);
                return;
            }
            Array array = (Array)value;
            Type elementType = type.GetElementType();
            writer.Write(array.Length);
            for (int i = 0; i < array.Length; i++)
            {
                EmitValue(writer, elementType, array.GetValue(i));
            }
            return;
        }
        if (type.IsPrimitive)
        {
            switch (Type.GetTypeCode(type))
            {
            case TypeCode.SByte:
                writer.Write((sbyte)value);
                break;
            case TypeCode.Byte:
                writer.Write((byte)value);
                break;
            case TypeCode.Char:
                writer.Write(Convert.ToUInt16((char)value));
                break;
            case TypeCode.Boolean:
                writer.Write((byte)(((bool)value) ? 1u : 0u));
                break;
            case TypeCode.Int16:
                writer.Write((short)value);
                break;
            case TypeCode.UInt16:
                writer.Write((ushort)value);
                break;
            case TypeCode.Int32:
                writer.Write((int)value);
                break;
            case TypeCode.UInt32:
                writer.Write((uint)value);
                break;
            case TypeCode.Int64:
                writer.Write((long)value);
                break;
            case TypeCode.UInt64:
                writer.Write((ulong)value);
                break;
            case TypeCode.Single:
                writer.Write((float)value);
                break;
            case TypeCode.Double:
                writer.Write((double)value);
                break;
            }
            return;
        }
        if (type == typeof(object))
        {
            Type type2 = ((value == null) ? typeof(string) : ((value is Type) ? typeof(Type) : value.GetType()));
            if (type2 == typeof(object))
            {
                throw new ArgumentException(SR.Format(SR.Argument_BadParameterTypeForCAB, type2));
            }
            EmitType(writer, type2);
            EmitValue(writer, type2, value);
            return;
        }
        string p = "null";
        if (value != null)
        {
            p = value.GetType().ToString();
        }
        throw new ArgumentException(SR.Format(SR.Argument_BadParameterTypeForCAB, p));
    }
References System.SR.Argument_BadParameterTypeForCAB, System.SR.Argument_InvalidTypeForCA, System.array, System.Reflection.Array, System.elementType, System.Reflection.Emit.CustomAttributeBuilder.EmitString(), System.Reflection.Emit.CustomAttributeBuilder.EmitType(), System.Reflection.Emit.CustomAttributeBuilder.EmitValue(), System.SR.Format(), System.Type.GetElementType(), System.Type.GetTypeCode(), System.Enum.GetUnderlyingType(), System.Reflection.MaxValue, System.text, System.Reflection.Emit.TypeNameBuilder.ToString(), System.Convert.ToUInt16(), System.Reflection.Type, System.type, System.value, and System.writer.
Referenced by System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder(), and System.Reflection.Emit.CustomAttributeBuilder.EmitValue().