Terraria: System.Reflection.Emit.CustomAttributeBuilder.EmitString
EmitString()
static void System.Reflection.Emit.CustomAttributeBuilder.EmitString (BinaryWriter writer, string str) inline static private
Definition at line 291 of file CustomAttributeBuilder.cs.
    {
        byte[] bytes = Encoding.UTF8.GetBytes(str);
        uint num = (uint)bytes.Length;
        if (num <= 127)
        {
            writer.Write((byte)num);
        }
        else if (num <= 16383)
        {
            writer.Write(BinaryPrimitives.ReverseEndianness((short)(num | 0x8000)));
        }
        else
        {
            writer.Write(BinaryPrimitives.ReverseEndianness(num | 0xC0000000u));
        }
        writer.Write(bytes);
    }
References System.bytes, System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), System.str, System.Text.Encoding.UTF8, and System.writer.
Referenced by System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder(), System.Reflection.Emit.CustomAttributeBuilder.EmitType(), and System.Reflection.Emit.CustomAttributeBuilder.EmitValue().