Terraria: System.Collections.CollectionBase.Insert
Insert() [1/2]
void IList. System.Collections.CollectionBase.Insert (int index, object value) inline private inherited
Definition at line 156 of file CollectionBase.cs.
    {
        if (index < 0 || index > Count)
        {
            throw new ArgumentOutOfRangeException("index", System.SR.ArgumentOutOfRange_Index);
        }
        OnValidate(value);
        OnInsert(index, value);
        InnerList.Insert(index, value);
        try
        {
            OnInsertComplete(index, value);
        }
        catch
        {
            InnerList.RemoveAt(index);
            throw;
        }
    }
References System.SR.ArgumentOutOfRange_Index, System.Collections.CollectionBase.Count, System.index, System.Collections.CollectionBase.InnerList, System.Collections.ArrayList.Insert(), System.Collections.CollectionBase.OnInsert(), System.Collections.CollectionBase.OnInsertComplete(), System.Collections.CollectionBase.OnValidate(), System.Collections.ArrayList.RemoveAt(), and System.value.