Terraria: System.Collections.CollectionBase.RemoveAt
RemoveAt()
void System.Collections.CollectionBase.RemoveAt (int index) inline inherited
Implements System.Collections.IList.
Definition at line 82 of file CollectionBase.cs.
    {
        if (index < 0 || index >= Count)
        {
            throw new ArgumentOutOfRangeException("index", System.SR.ArgumentOutOfRange_Index);
        }
        object value = InnerList[index];
        OnValidate(value);
        OnRemove(index, value);
        InnerList.RemoveAt(index);
        try
        {
            OnRemoveComplete(index, value);
        }
        catch
        {
            InnerList.Insert(index, value);
            throw;
        }
    }
References System.SR.ArgumentOutOfRange_Index, System.Collections.CollectionBase.Count, System.index, System.Collections.CollectionBase.InnerList, System.Collections.ArrayList.Insert(), System.Collections.CollectionBase.OnRemove(), System.Collections.CollectionBase.OnRemoveComplete(), System.Collections.CollectionBase.OnValidate(), System.Collections.ArrayList.RemoveAt(), and System.value.
Referenced by System.Security.Cryptography.X509Certificates.X509Certificate2Collection.ImportFromPem().