Terraria: NPC.SpawnNPC
SpawnNPC()
static void NPC.SpawnNPC () inline static
References Entity.active, Main.CurrentFrameFlags.ActivePlayersCount, Player.afkCounter, ai, WallID.Sets.AllowsUndergroundDesertEnemiesToSpawn, Player.anglerSetSpawnReduction, Player.armor, WorldGen.beachDistance, Main.bloodMoon, Entity.Bottom, Player.calmed, Entity.Center, CoinLossRevengeSystem.CheckRespawns(), WorldGen.checkUnderground(), Main.cloudAlpha, Main.cloudBGActive, TileID.Sets.Corrupt, TileID.Sets.Crimson, Main.dayTime, Player.dead, Main.dontStarveWorld, Main.drunkWorld, Main.dungeonY, Main.eclipse, Player.enemySpawns, Main.expertMode, Main.GameModeInfo, Main.getGoodWorld, TileID.Sets.Hallow, Main.halloween, Sandstorm.Happening, Main.hardMode, Entity.height, Tile.honey(), CreativePowerManager.Instance, Main.invasionDelay, Main.invasionSize, Main.invasionSizeStart, Main.invasionType, Main.invasionX, Player.inventory, Player.invis, Main.IsItAHappyWindyDay, GameModeData.IsJourneyMode, Player.isNearFairy(), Player.isNearNPC(), Tile.lava(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Main.moonPhase, Tile.nactive(), Player.nearbyActiveNPCs, Main.netMode, netUpdate, UnifiedRandom.Next(), Main.npc, npcSlots, Main.numClouds, WorldGen.oceanDepths(), WorldGen.oceanDistance, DD2Event.Ongoing, BirthdayParty.PartyIsUp, Main.player, Entity.position, Main.pumpkinMoon, Main.raining, Main.rand, DD2Event.ReadyToFindBartender, Main.remixWorld, Main.rockLayer, Player.RollLuck(), TileID.Sets.Conversion.Sand, Player.scope, Player.selectedItem, NetMessage.SendData(), SetDefaults(), WorldGen.shadowOrbSmashed, Tile.shimmer(), Main.slimeRain, Main.snowMoon, WorldGen.SolidTile(), Collision.SolidTiles(), DD2Event.SpawnNPC(), Main.spawnTileX, Star.starfallBoost, Player.statLifeMax, Player.sunflower, target, TargetClosest(), Main.tenthAnniversaryWorld, Main.tile, Main.tileDungeon, Main.tileSand, Main.tileSolid, Main.time, timeLeft, townNPC, Player.townNPCs, Item.type, type, Tile.type, Main.UnderworldLayer, Tile.wall, Main.wallHouse, Main.wallLight, Entity.width, Main.windSpeedTarget, Main.wofNPCIndex, Main.worldSurface, Main.xMas, Player.ZoneCorrupt, Player.ZoneCrimson, Player.ZoneDungeon, Player.ZoneGlowshroom, Player.ZoneGraveyard, Player.ZoneHallow, Player.ZoneJungle, Player.ZoneMeteor, Player.ZoneOldOneArmy, Player.ZonePeaceCandle, Player.ZoneSandstorm, Player.ZoneShadowCandle, Player.ZoneSnow, Player.ZoneTowerNebula, Player.ZoneTowerSolar, Player.ZoneTowerStardust, Player.ZoneTowerVortex, Player.ZoneUndergroundDesert, and Player.ZoneWaterCandle.
Referenced by Main.DoUpdateInWorld().