Terraria: NPC.AI_007_TownEntities_Shimmer_TeleportToLandingSpot
AI_007_TownEntities_Shimmer_TeleportToLandingSpot()
void NPC.AI_007_TownEntities_Shimmer_TeleportToLandingSpot () inline private
     {
         Vector2? vector = AI_007_TownEntities_Shimmer_ScanForBestSpotToLandOn();
         if (vector.HasValue)
         {
             Vector2 vector2 = position;
             position = vector.Value;
             Vector2 movementVector = position - vector2;
             int num = 560;
             if (movementVector.Length() >= (float)num)
             {
                 ai[2] = 30f;
                 ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.ShimmerTownNPCSend, new ParticleOrchestraSettings
                 {
                     PositionInWorld = vector2 + base.Size / 2f,
                     MovementVector = movementVector
                 });
             }
             netUpdate = true;
         }
     }
References ai, AI_007_TownEntities_Shimmer_ScanForBestSpotToLandOn(), ParticleOrchestrator.BroadcastParticleSpawn(), netUpdate, and Entity.position.
Referenced by AI_007_TownEntities().