Terraria: NPC.ReleaseNPC
ReleaseNPC()
static int NPC.ReleaseNPC (int x, int y, int Type, int Style, int who) inline static
     {
         int num = -1;
         if (Main.netMode == 1)
         {
             NetMessage.SendData(71, -1, -1, null, x, y, Type, Style);
         }
         else if (Type >= 0 && Type < NPCID.Count && (Main.npcCatchable[Type] || who == Main.myPlayer) && CanReleaseNPCs(who))
         {
             switch (Type)
             {
             case 583:
             case 584:
             case 585:
                 num = NewNPC(GetSpawnSource_NPCRelease(who), x, y, Type);
                 Main.npc[num].releaseOwner = (short)who;
                 Main.npc[num].ai[2] = 2f;
                 Main.npc[num].TargetClosest();
                 Main.npc[num].ai[3] = 0f;
                 Main.npc[num].netUpdate = true;
                 break;
             case 356:
                 num = NewNPC(GetSpawnSource_NPCRelease(who), x, y, Type);
                 Main.npc[num].ai[2] = Style;
                 Main.npc[num].releaseOwner = (short)who;
                 break;
             case 148:
             {
                 int num3 = Type + Main.rand.Next(2);
                 num = NewNPC(GetSpawnSource_NPCRelease(who), x, y, num3);
                 Main.npc[num].releaseOwner = (short)who;
                 break;
             }
             case 614:
             {
                 num = NewNPC(GetSpawnSource_NPCRelease(who), x, y, Type);
                 Main.npc[num].releaseOwner = (short)who;
                 int num2 = Main.player[who].direction;
                 if (Style > 2)
                 {
                     Style -= 2;
                     Main.npc[num].SpawnedFromStatue = true;
                     Main.npc[num].CanBeReplacedByOtherNPCs = true;
                 }
                 if (Style == 1)
                 {
                     num2 = 1;
                 }
                 if (Style == 2)
                 {
                     num2 = -1;
                 }
                 Main.npc[num].direction = num2;
                 Main.npc[num].spriteDirection = num2;
                 Main.npc[num].netUpdate = true;
                 break;
             }
             default:
                 num = NewNPC(GetSpawnSource_NPCRelease(who), x, y, Type);
                 Main.npc[num].releaseOwner = (short)who;
                 break;
             }
         }
         return num;
     }
References ai, CanBeReplacedByOtherNPCs, NPCID.Count, Entity.direction, Main.myPlayer, Main.netMode, netUpdate, UnifiedRandom.Next(), Main.npc, Main.npcCatchable, Main.player, Main.rand, releaseOwner, NetMessage.SendData(), SpawnedFromStatue, spriteDirection, and TargetClosest().
Referenced by MessageBuffer.GetData(), Item.GetShimmered(), Projectile.HandleMovement(), and Player.ItemCheck_ReleaseCritter().