Terraria: NPC.TargetClosest_WOF
TargetClosest_WOF()
void NPC.TargetClosest_WOF (bool faceTarget = true) inline
     {
         float distance = 0f;
         float realDist = 0f;
         bool t = false;
         int tankTarget = -1;
         for (int i = 0; i < 255; i++)
         {
             if (Main.player[i].active && !Main.player[i].dead && !Main.player[i].ghost && Main.player[i].gross)
             {
                 TryTrackingTarget(ref distance, ref realDist, ref t, ref tankTarget, i);
             }
         }
         SetTargetTrackingValues(faceTarget, realDist, tankTarget);
     }
References Entity.active, Player.dead, Player.ghost, Player.gross, Main.player, SetTargetTrackingValues(), and TryTrackingTarget().
Referenced by AI().