Terraria: NPC.AI_047_GolemFist
AI_047_GolemFist()
void NPC.AI_047_GolemFist () inline private
     {
         float num = GetMyBalance();
         if (Main.getGoodWorld)
         {
             num += 3f;
         }
         if ((!Main.player[target].ZoneLihzhardTemple && !Main.player[target].ZoneJungle) || (double)Main.player[target].Center.Y < Main.worldSurface * 16.0)
         {
             num *= 2f;
         }
         if (golemBoss < 0)
         {
             StrikeNPCNoInteraction(9999, 0f, 0);
             return;
         }
         if (alpha > 0)
         {
             alpha -= 10;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             ai[1] = 0f;
         }
         Player player = Main.player[target];
         NPC nPC = Main.npc[golemBoss];
         Vector2 vector = nPC.Center + nPC.velocity + new Vector2(0f, -9f * scale);
         vector.X += (float)((type == 247) ? (-84) : 78) * scale;
         Vector2 vector2 = vector - base.Center;
         float num2 = vector2.Length();
         if (ai[0] == 0f)
         {
             noTileCollide = true;
             float num3 = 14f;
             if (life < lifeMax / 2)
             {
                 num3 += 3f;
             }
             if (life < lifeMax / 4)
             {
                 num3 += 3f;
             }
             if (Main.npc[golemBoss].life < Main.npc[golemBoss].lifeMax)
             {
                 num3 += 8f;
             }
             num3 *= (num + 3f) / 4f;
             if (num3 > 32f)
             {
                 num3 = 32f;
             }
             float x = vector2.X;
             float y = vector2.Y;
             float num4 = num2;
             if (num4 < 12f + num3)
             {
                 rotation = 0f;
                 velocity.X = x;
                 velocity.Y = y;
                 float num5 = num;
                 ai[1] += num5;
                 if (life < lifeMax / 2)
                 {
                     ai[1] += num5;
                 }
                 if (life < lifeMax / 4)
                 {
                     ai[1] += num5;
                 }
                 if (Main.npc[golemBoss].life < Main.npc[golemBoss].lifeMax)
                 {
                     ai[1] += 10f * num5;
                 }
                 if (ai[1] >= 60f)
                 {
                     TargetClosest();
                     if ((type == 247 && base.Center.X + 100f > Main.player[target].Center.X) || (type == 248 && base.Center.X - 100f < Main.player[target].Center.X))
                     {
                         ai[1] = 0f;
                         ai[0] = 1f;
                     }
                     else
                     {
                         ai[1] = 0f;
                     }
                 }
             }
             else
             {
                 num4 = num3 / num4;
                 velocity.X = x * num4;
                 velocity.Y = y * num4;
                 rotation = (float)Math.Atan2(0f - velocity.Y, 0f - velocity.X);
                 if (type == 247)
                 {
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                 }
             }
         }
         else if (ai[0] == 1f)
         {
             ai[1] += 1f;
             base.Center = vector;
             rotation = 0f;
             velocity = Vector2.Zero;
             if (ai[1] <= 15f)
             {
                 for (int i = 0; i < 1; i++)
                 {
                     Vector2 vector3 = Main.rand.NextVector2Circular(80f, 80f);
                     Vector2 vector4 = vector3 * -1f * 0.05f;
                     Vector2 vector5 = Main.rand.NextVector2Circular(20f, 20f);
                     Dust dust = Dust.NewDustPerfect(base.Center + vector4 + vector3 + vector5, 228, vector4);
                     dust.fadeIn = 1.5f;
                     dust.scale = 0.5f;
                     if (Main.getGoodWorld)
                     {
                         dust.noLight = true;
                     }
                     dust.noGravity = true;
                 }
             }
             if (ai[1] >= 30f)
             {
                 noTileCollide = true;
                 collideX = false;
                 collideY = false;
                 ai[0] = 2f;
                 ai[1] = 0f;
                 float num6 = 12f;
                 if (life < lifeMax / 2)
                 {
                     num6 += 4f;
                 }
                 if (life < lifeMax / 4)
                 {
                     num6 += 4f;
                 }
                 if (Main.npc[golemBoss].life < Main.npc[golemBoss].lifeMax)
                 {
                     num6 += 10f;
                 }
                 num6 *= (num + 3f) / 4f;
                 if (num6 > 48f)
                 {
                     num6 = 48f;
                 }
                 Vector2 vector6 = new Vector2(base.Center.X, base.Center.Y);
                 float num7 = Main.player[target].Center.X - vector6.X;
                 float num8 = Main.player[target].Center.Y - vector6.Y;
                 float num9 = (float)Math.Sqrt(num7 * num7 + num8 * num8);
                 num9 = num6 / num9;
                 velocity.X = num7 * num9;
                 velocity.Y = num8 * num9;
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                 if (type == 247)
                 {
                     rotation = (float)Math.Atan2(0f - velocity.Y, 0f - velocity.X);
                 }
             }
         }
         else if (ai[0] == 2f)
         {
             if (Main.netMode != 1 && Main.getGoodWorld)
             {
                 for (int j = (int)(position.X / 16f) - 1; (float)j < (position.X + (float)width) / 16f + 1f; j++)
                 {
                     for (int k = (int)(position.Y / 16f) - 1; (float)k < (position.Y + (float)width) / 16f + 1f; k++)
                     {
                         if (Main.tile[j, k].type == 4)
{
                             Main.tile[j, k].active(active: false);
                             if (Main.netMode == 2)
{
                                 NetMessage.SendTileSquare(-1, j, k);
                             }
                         }
                     }
                 }
             }
             ai[1] += 1f;
             if (ai[1] == 1f)
             {
                 SoundEngine.PlaySound(SoundID.Item14, position);
             }
             if (Main.rand.Next(2) == 0)
             {
                 Vector2 vector7 = velocity * 0.5f;
                 Vector2 vector8 = Main.rand.NextVector2Circular(20f, 20f);
                 Dust.NewDustPerfect(base.Center + vector7 + vector8, 306, vector7, 0, Main.OurFavoriteColor).scale = 2f;
             }
             if (Math.Abs(velocity.X) > Math.Abs(velocity.Y))
             {
                 if (velocity.X > 0f && base.Center.X > player.Center.X)
                 {
                     noTileCollide = false;
                 }
                 if (velocity.X < 0f && base.Center.X < player.Center.X)
                 {
                     noTileCollide = false;
                 }
             }
             else
             {
                 if (velocity.Y > 0f && base.Center.Y > player.Center.Y)
                 {
                     noTileCollide = false;
                 }
                 if (velocity.Y < 0f && base.Center.Y < player.Center.Y)
                 {
                     noTileCollide = false;
                 }
             }
             if (num2 > 700f || collideX || collideY)
             {
                 noTileCollide = true;
                 ai[0] = 0f;
             }
         }
         else
         {
             if (ai[0] != 3f)
             {
                 return;
             }
             noTileCollide = true;
             float num10 = 0.4f;
             Vector2 vector9 = new Vector2(base.Center.X, base.Center.Y);
             float num11 = Main.player[target].Center.X - vector9.X;
             float num12 = Main.player[target].Center.Y - vector9.Y;
             float num13 = (float)Math.Sqrt(num11 * num11 + num12 * num12);
             num13 = 12f / num13;
             num11 *= num13;
             num12 *= num13;
             if (velocity.X < num11)
             {
                 velocity.X += num10;
                 if (velocity.X < 0f && num11 > 0f)
                 {
                     velocity.X += num10 * 2f;
                 }
             }
             else if (velocity.X > num11)
             {
                 velocity.X -= num10;
                 if (velocity.X > 0f && num11 < 0f)
                 {
                     velocity.X -= num10 * 2f;
                 }
             }
             if (velocity.Y < num12)
             {
                 velocity.Y += num10;
                 if (velocity.Y < 0f && num12 > 0f)
                 {
                     velocity.Y += num10 * 2f;
                 }
             }
             else if (velocity.Y > num12)
             {
                 velocity.Y -= num10;
                 if (velocity.Y > 0f && num12 < 0f)
                 {
                     velocity.Y -= num10 * 2f;
                 }
             }
             rotation = (float)Math.Atan2(velocity.Y, velocity.X);
             if (type == 247)
             {
                 rotation = (float)Math.Atan2(0f - velocity.Y, 0f - velocity.X);
             }
         }
     }
References Entity.active, Tile.active(), ai, alpha, Entity.Center, collideX, collideY, Dust.fadeIn, Main.getGoodWorld, GetMyBalance(), golemBoss, SoundID.Item14, life, lifeMax, Main.netMode, Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, noTileCollide, Main.npc, Main.OurFavoriteColor, Main.player, SoundEngine.PlaySound(), Entity.position, Main.rand, rotation, Dust.scale, scale, NetMessage.SendTileSquare(), StrikeNPCNoInteraction(), target, TargetClosest(), Main.tile, type, Tile.type, Entity.velocity, Entity.width, Main.worldSurface, Player.ZoneJungle, and Player.ZoneLihzhardTemple.
Referenced by AI().