Terraria: NPC.AI_007_TownEntities_TeleportToHome
AI_007_TownEntities_TeleportToHome()
void NPC.AI_007_TownEntities_TeleportToHome (int homeFloorX, int homeFloorY) inline private
     {
         bool flag = false;
         for (int i = 0; i < 3; i++)
         {
             int num = homeFloorX + i switch
             {
                 1 => -1,
                 0 => 0,
                 _ => 1,
             };
             if (type == 37 || !Collision.SolidTiles(num - 1, num + 1, homeFloorY - 3, homeFloorY - 1))
             {
                 velocity.X = 0f;
                 velocity.Y = 0f;
                 position.X = num * 16 + 8 - width / 2;
                 position.Y = (float)(homeFloorY * 16 - height) - 0.1f;
                 netUpdate = true;
                 AI_007_TryForcingSitting(homeFloorX, homeFloorY);
                 flag = true;
                 break;
             }
         }
         if (!flag)
         {
             homeless = true;
             WorldGen.QuickFindHome(whoAmI);
         }
     }
References AI_007_TryForcingSitting(), Entity.height, homeless, netUpdate, Entity.position, WorldGen.QuickFindHome(), Collision.SolidTiles(), type, Entity.velocity, Entity.whoAmI, and Entity.width.
Referenced by AI_007_TownEntities().