Terraria: NPC.RerollVariation
RerollVariation()
bool NPC.RerollVariation () inline
     {
         if (!TownNPCProfiles.Instance.GetProfile(type, out var profile))
         {
             return false;
         }
         int num = townNpcVariationIndex;
         int num2 = 0;
         while (num2++ < 100 && townNpcVariationIndex == num)
         {
             townNpcVariationIndex = profile.RollVariation();
         }
         if (num == townNpcVariationIndex)
         {
             return false;
         }
         GivenName = profile.GetNameForVariant(this);
         life = lifeMax;
         if (Main.netMode != 1)
         {
             ParticleOrchestraSettings particleOrchestraSettings = default(ParticleOrchestraSettings);
             particleOrchestraSettings.PositionInWorld = base.Center;
             particleOrchestraSettings.MovementVector = velocity;
             ParticleOrchestraSettings settings = particleOrchestraSettings;
             ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.PetExchange, settings);
         }
         NetMessage.TrySendData(56, -1, -1, null, whoAmI);
         return true;
     }
References ParticleOrchestrator.BroadcastParticleSpawn(), TownNPCProfiles.GetProfile(), TownNPCProfiles.Instance, ParticleOrchestraSettings.MovementVector, Main.netMode, ParticleOrchestraSettings.PositionInWorld, and NetMessage.TrySendData().
Referenced by RerollVariationForNPCType().