Terraria: NPC.AI_123_Deerclops_TryMakingSpike_FindBestY
AI_123_Deerclops_TryMakingSpike_FindBestY()
int NPC.AI_123_Deerclops_TryMakingSpike_FindBestY (ref Point sourceTileCoords, int x) inline private
     {
         int num = sourceTileCoords.Y;
         NPCAimedTarget targetData = GetTargetData();
         if (!targetData.Invalid)
         {
             Rectangle hitbox = targetData.Hitbox;
             Vector2 vector = new Vector2(hitbox.Center.X, hitbox.Bottom);
             int num2 = (int)(vector.Y / 16f);
             int num3 = Math.Sign(num2 - num);
             int num4 = num2 + num3 * 15;
             int? num5 = null;
             float num6 = float.PositiveInfinity;
             for (int i = num; i != num4; i += num3)
             {
                 if (WorldGen.ActiveAndWalkableTile(x, i))
                 {
                     float num7 = new Point(x, i).ToWorldCoordinates().Distance(vector);
                     if (!num5.HasValue || !(num7 >= num6))
                     {
                         num5 = i;
                         num6 = num7;
                     }
                 }
             }
             if (num5.HasValue)
             {
                 num = num5.Value;
             }
         }
         for (int j = 0; j < 20; j++)
         {
             if (num < 10)
             {
                 break;
             }
             if (!WorldGen.SolidTile(x, num))
             {
                 break;
             }
             num--;
         }
         for (int k = 0; k < 20; k++)
         {
             if (num > Main.maxTilesY - 10)
             {
                 break;
             }
             if (WorldGen.ActiveAndWalkableTile(x, num))
             {
                 break;
             }
             num++;
         }
         return num;
     }
References WorldGen.ActiveAndWalkableTile(), GetTargetData(), NPCAimedTarget.Hitbox, NPCAimedTarget.Invalid, Main.maxTilesY, and WorldGen.SolidTile().
Referenced by AI_123_Deerclops_TryMakingSpike().