Terraria: NPC.AI_026_Unicorns
AI_026_Unicorns()
void NPC.AI_026_Unicorns () inline private
     {
         int num = 30;
         int num2 = 10;
         bool flag = false;
         bool flag2 = false;
         bool flag3 = false;
         if (velocity.Y == 0f && ((velocity.X > 0f && direction < 0) || (velocity.X < 0f && direction > 0)))
         {
             flag2 = true;
             ai[3] += 1f;
         }
         if (type == 546)
         {
             num2 = 4;
             bool flag4 = velocity.Y == 0f;
             for (int i = 0; i < 200; i++)
             {
                 if (i != whoAmI && Main.npc[i].active && Main.npc[i].type == type && Math.Abs(position.X - Main.npc[i].position.X) + Math.Abs(position.Y - Main.npc[i].position.Y) < (float)width)
                 {
                     if (position.X < Main.npc[i].position.X)
                     {
                         velocity.X -= 0.05f;
                     }
                     else
                     {
                         velocity.X += 0.05f;
                     }
                     if (position.Y < Main.npc[i].position.Y)
                     {
                         velocity.Y -= 0.05f;
                     }
                     else
                     {
                         velocity.Y += 0.05f;
                     }
                 }
             }
             if (flag4)
             {
                 velocity.Y = 0f;
             }
         }
         if (type == 315)
         {
             int num3 = 480;
             if (localAI[0]++ >= (float)num3)
             {
                 localAI[0] = 0f;
                 int num4 = target;
                 if (Main.netMode != 1 && num4 != 255)
                 {
                     int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(40f, 30f);
                     Projectile.NewProjectile(GetSpawnSourceForNPCFromNPCAI(), base.Center + Main.rand.NextVector2Circular(40f, 40f), new Vector2(velocity.X, Main.rand.NextFloatDirection() * 3f), 1001, attackDamage_ForProjectiles, 0f, Main.myPlayer, num4);
                 }
             }
             Lighting.AddLight(base.Center, 0.4f, 0.36f, 0.2f);
             int num5 = frame.Height;
             if (num5 < 1)
             {
                 num5 = 1;
             }
             int num6 = frame.Y / num5;
             if (num6 >= 4 && num6 <= 7)
             {
                 Vector2 vector = base.Bottom + new Vector2(-30f, -8f);
                 Vector2 vector2 = new Vector2(60f, 8f);
                 if (Main.rand.Next(3) != 0)
                 {
                     Dust dust = Dust.NewDustPerfect(vector + new Vector2(Main.rand.NextFloat() * vector2.X, Main.rand.NextFloat() * vector2.Y), 6, velocity);
                     dust.scale = 0.6f;
                     dust.fadeIn = 1.1f;
                     dust.noGravity = true;
                     dust.noLight = true;
                 }
             }
         }
         if (position.X == oldPosition.X || ai[3] >= (float)num || flag2)
         {
             ai[3] += 1f;
             flag3 = true;
         }
         else if (ai[3] > 0f)
         {
             ai[3] -= 1f;
         }
         if (ai[3] > (float)(num * num2))
         {
             ai[3] = 0f;
         }
         if (justHit)
         {
             ai[3] = 0f;
         }
         if (ai[3] == (float)num)
         {
             netUpdate = true;
         }
         Vector2 vector3 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
         float num7 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector3.X;
         float num8 = Main.player[target].position.Y - vector3.Y;
         float num9 = (float)Math.Sqrt(num7 * num7 + num8 * num8);
         if (num9 < 200f && !flag3)
         {
             ai[3] = 0f;
         }
         if (type == 410)
         {
             ai[1] += 1f;
             bool flag5 = ai[1] >= 240f;
             if (!flag5 && velocity.Y == 0f)
             {
                 for (int j = 0; j < 255; j++)
                 {
                     if (Main.player[j].active && !Main.player[j].dead && Main.player[j].Distance(base.Center) < 800f && Main.player[j].Center.Y < base.Center.Y && Math.Abs(Main.player[j].Center.X - base.Center.X) < 20f)
                     {
                         flag5 = true;
                         break;
                     }
                 }
             }
             if (flag5 && Main.netMode != 1)
             {
                 for (int k = 0; k < 3; k++)
                 {
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, (Main.rand.NextFloat() - 0.5f) * 2f, -4f - 10f * Main.rand.NextFloat(), 538, 50, 0f, Main.myPlayer);
                 }
                 HitEffect(9999);
                 active = false;
                 return;
             }
         }
         else if (type == 423)
         {
             if (ai[2] == 1f)
             {
                 ai[1] += 1f;
                 velocity.X *= 0.7f;
                 if (ai[1] < 30f)
                 {
                     Vector2 vector4 = base.Center + Vector2.UnitX * spriteDirection * -20f;
                     Dust obj = Main.dust[Dust.NewDust(vector4, 0, 0, 242)];
                     Vector2 vector5 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                     obj.position = vector4 + vector5 * 20f;
                     obj.velocity = -vector5 * 2f;
                     obj.scale = 0.5f + vector5.X * (float)(-spriteDirection);
                     obj.fadeIn = 1f;
                     obj.noGravity = true;
                 }
                 else if (ai[1] == 30f)
                 {
                     for (int l = 0; l < 20; l++)
                     {
                         Vector2 vector6 = base.Center + Vector2.UnitX * spriteDirection * -20f;
                         Dust obj2 = Main.dust[Dust.NewDust(vector6, 0, 0, 242)];
                         Vector2 vector7 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                         obj2.position = vector6 + vector7 * 4f;
                         obj2.velocity = vector7 * 4f + Vector2.UnitX * Main.rand.NextFloat() * spriteDirection * -5f;
                         obj2.scale = 0.5f + vector7.X * (float)(-spriteDirection);
                         obj2.fadeIn = 1f;
                         obj2.noGravity = true;
                     }
                 }
                 if (velocity.X > -0.5f && velocity.X < 0.5f)
                 {
                     velocity.X = 0f;
                 }
                 if (ai[1] == 30f && Main.netMode != 1)
                 {
                     int attackDamage_ForProjectiles2 = GetAttackDamage_ForProjectiles(50f, 35f);
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * -20), base.Center.Y, spriteDirection * -7, 0f, 575, attackDamage_ForProjectiles2, 0f, Main.myPlayer, target);
                 }
                 if (ai[1] >= 60f)
                 {
                     ai[1] = -Main.rand.Next(320, 601);
                     ai[2] = 0f;
                 }
             }
             else
             {
                 ai[1] += 1f;
                 if (ai[1] >= 180f && num9 < 500f && velocity.Y == 0f)
                 {
                     flag = true;
                     ai[1] = 0f;
                     ai[2] = 1f;
                     netUpdate = true;
                 }
                 else if (velocity.Y == 0f && num9 < 100f && Math.Abs(velocity.X) > 3f && ((base.Center.X < Main.player[target].Center.X && velocity.X > 0f) || (base.Center.X > Main.player[target].Center.X && velocity.X < 0f)))
                 {
                     velocity.Y -= 4f;
                 }
             }
         }
         else if (type == 155 || type == 329)
         {
             if (velocity.Y == 0f && num9 < 100f && Math.Abs(velocity.X) > 3f && ((position.X + (float)(width / 2) < Main.player[target].position.X + (float)(Main.player[target].width / 2) && velocity.X > 0f) || (position.X + (float)(width / 2) > Main.player[target].position.X + (float)(Main.player[target].width / 2) && velocity.X < 0f)))
             {
                 velocity.Y -= 4f;
             }
         }
         else if (type == 546 && velocity.Y == 0f && Math.Abs(velocity.X) > 3f && ((base.Center.X < Main.player[target].Center.X && velocity.X > 0f) || (base.Center.X > Main.player[target].Center.X && velocity.X < 0f)))
         {
             velocity.Y -= 4f;
             SoundEngine.PlaySound(3, base.Center, 11);
         }
         if (type == 546 && !Main.player[target].ZoneDesert)
         {
             int num10 = direction;
             TargetClosest();
             if (!Main.player[target].ZoneDesert)
             {
                 EncourageDespawn(10);
                 ai[3] = num;
                 direction = num10;
             }
         }
         if (ai[3] < (float)num)
         {
             if ((type == 329 || type == 315) && !Main.pumpkinMoon)
             {
                 EncourageDespawn(10);
             }
             else
             {
                 TargetClosest();
             }
         }
         else
         {
             if (velocity.X == 0f)
             {
                 if (velocity.Y == 0f)
                 {
                     ai[0] += 1f;
                     if (ai[0] >= 2f)
                     {
                         direction *= -1;
                         spriteDirection = direction;
                         ai[0] = 0f;
                     }
                 }
             }
             else
             {
                 ai[0] = 0f;
             }
             directionY = -1;
             if (direction == 0)
             {
                 direction = 1;
             }
         }
         float num11 = 6f;
         float num12 = 0.07f;
         if (!flag && (velocity.Y == 0f || wet || (velocity.X <= 0f && direction < 0) || (velocity.X >= 0f && direction > 0)))
         {
             if (type == 155)
             {
                 if (velocity.X > 0f && direction < 0)
                 {
                     velocity.X *= 0.95f;
                 }
                 if (velocity.X < 0f && direction > 0)
                 {
                     velocity.X *= 0.95f;
                 }
             }
             else if (type == 329)
             {
                 if (velocity.X > 0f && direction < 0)
                 {
                     velocity.X *= 0.9f;
                 }
                 if (velocity.X < 0f && direction > 0)
                 {
                     velocity.X *= 0.9f;
                 }
                 if (direction > 0 && velocity.X < 3f)
                 {
                     velocity.X += 0.1f;
                 }
                 if (direction < 0 && velocity.X > -3f)
                 {
                     velocity.X -= 0.1f;
                 }
             }
             else if (type == 315)
             {
                 if (velocity.X > 0f && direction < 0)
                 {
                     velocity.X *= 0.95f;
                 }
                 if (velocity.X < 0f && direction > 0)
                 {
                     velocity.X *= 0.95f;
                 }
                 if (velocity.X < 0f - num11 || velocity.X > num11)
                 {
                     if (velocity.Y == 0f)
                     {
                         velocity *= 0.8f;
                     }
                 }
                 else if (velocity.X < num11 && direction == 1)
                 {
                     velocity.X += 0.07f;
                     if (velocity.X > num11)
                     {
                         velocity.X = num11;
                     }
                 }
                 else if (velocity.X > 0f - num11 && direction == -1)
                 {
                     velocity.X -= 0.07f;
                     if (velocity.X < 0f - num11)
                     {
                         velocity.X = 0f - num11;
                     }
                 }
             }
             else if (type == 410)
             {
                 if (Math.Sign(velocity.X) != direction)
                 {
                     velocity.X *= 0.9f;
                 }
                 num11 = 6f;
                 num12 = 0.2f;
             }
             else if (type == 423)
             {
                 if (Math.Sign(velocity.X) != direction)
                 {
                     velocity.X *= 0.85f;
                 }
                 num11 = 10f;
                 num12 = 0.2f;
             }
             else if (type == 546)
             {
                 if (Math.Sign(velocity.X) != direction)
                 {
                     velocity.X *= 0.92f;
                 }
                 float num13 = MathHelper.Lerp(0.6f, 1f, Math.Abs(Main.windSpeedTarget)) * (float)Math.Sign(Main.windSpeedTarget);
                 if (!Main.player[target].ZoneSandstorm)
                 {
                     num13 = 0f;
                 }
                 num11 = 4f + num13 * (float)direction * 3f;
                 num12 = 0.05f;
             }
             if (velocity.X < 0f - num11 || velocity.X > num11)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.8f;
                 }
             }
             else if (velocity.X < num11 && direction == 1)
             {
                 velocity.X += num12;
                 if (velocity.X > num11)
                 {
                     velocity.X = num11;
                 }
             }
             else if (velocity.X > 0f - num11 && direction == -1)
             {
                 velocity.X -= num12;
                 if (velocity.X < 0f - num11)
                 {
                     velocity.X = 0f - num11;
                 }
             }
         }
         if (velocity.Y >= 0f)
         {
             int num14 = 0;
             if (velocity.X < 0f)
             {
                 num14 = -1;
             }
             if (velocity.X > 0f)
             {
                 num14 = 1;
             }
             Vector2 vector8 = position;
             vector8.X += velocity.X;
             int num15 = (int)((vector8.X + (float)(width / 2) + (float)((width / 2 + 1) * num14)) / 16f);
             int num16 = (int)((vector8.Y + (float)height - 1f) / 16f);
             if (Main.tile[num15, num16] == null)
             {
                 Main.tile[num15, num16] = new Tile();
             }
             if (Main.tile[num15, num16 - 1] == null)
             {
                 Main.tile[num15, num16 - 1] = new Tile();
             }
             if (Main.tile[num15, num16 - 2] == null)
             {
                 Main.tile[num15, num16 - 2] = new Tile();
             }
             if (Main.tile[num15, num16 - 3] == null)
             {
                 Main.tile[num15, num16 - 3] = new Tile();
             }
             if (Main.tile[num15, num16 + 1] == null)
             {
                 Main.tile[num15, num16 + 1] = new Tile();
             }
             if ((float)(num15 * 16) < vector8.X + (float)width && (float)(num15 * 16 + 16) > vector8.X && ((Main.tile[num15, num16].nactive() && !Main.tile[num15, num16].topSlope() && !Main.tile[num15, num16 - 1].topSlope() && Main.tileSolid[Main.tile[num15, num16].type] && !Main.tileSolidTop[Main.tile[num15, num16].type]) || (Main.tile[num15, num16 - 1].halfBrick() && Main.tile[num15, num16 - 1].nactive())) && (!Main.tile[num15, num16 - 1].nactive() || !Main.tileSolid[Main.tile[num15, num16 - 1].type] || Main.tileSolidTop[Main.tile[num15, num16 - 1].type] || (Main.tile[num15, num16 - 1].halfBrick() && (!Main.tile[num15, num16 - 4].nactive() || !Main.tileSolid[Main.tile[num15, num16 - 4].type] || Main.tileSolidTop[Main.tile[num15, num16 - 4].type]))) && (!Main.tile[num15, num16 - 2].nactive() || !Main.tileSolid[Main.tile[num15, num16 - 2].type] || Main.tileSolidTop[Main.tile[num15, num16 - 2].type]) && (!Main.tile[num15, num16 - 3].nactive() || !Main.tileSolid[Main.tile[num15, num16 - 3].type] || Main.tileSolidTop[Main.tile[num15, num16 - 3].type]) && (!Main.tile[num15 - num14, num16 - 3].nactive() || !Main.tileSolid[Main.tile[num15 - num14, num16 - 3].type]))
             {
                 float num17 = num16 * 16;
                 if (Main.tile[num15, num16].halfBrick())
                 {
                     num17 += 8f;
                 }
                 if (Main.tile[num15, num16 - 1].halfBrick())
                 {
                     num17 -= 8f;
                 }
                 if (num17 < vector8.Y + (float)height)
                 {
                     float num18 = vector8.Y + (float)height - num17;
                     if ((double)num18 <= 16.1)
                     {
                         gfxOffY += position.Y + (float)height - num17;
                         position.Y = num17 - (float)height;
                         if (num18 < 9f)
{
                             stepSpeed = 1f;
                         }
                         else
{
                             stepSpeed = 2f;
                         }
                     }
                 }
             }
         }
         if (velocity.Y == 0f)
         {
             bool flag6 = true;
             int num19 = (int)(position.Y - 7f) / 16;
             int num20 = (int)(position.X - 7f) / 16;
             int num21 = (int)(position.X + (float)width + 7f) / 16;
             for (int m = num20; m <= num21; m++)
             {
                 if (Main.tile[m, num19] != null && Main.tile[m, num19].nactive() && Main.tileSolid[Main.tile[m, num19].type])
                 {
                     flag6 = false;
                     break;
                 }
             }
             if (flag6)
             {
                 int num22 = (int)((position.X + (float)(width / 2) + (float)((width / 2 + 2) * direction) + velocity.X * 5f) / 16f);
                 int num23 = (int)((position.Y + (float)height - 15f) / 16f);
                 if (Main.tile[num22, num23] == null)
                 {
                     Main.tile[num22, num23] = new Tile();
                 }
                 if (Main.tile[num22, num23 - 1] == null)
                 {
                     Main.tile[num22, num23 - 1] = new Tile();
                 }
                 if (Main.tile[num22, num23 - 2] == null)
                 {
                     Main.tile[num22, num23 - 2] = new Tile();
                 }
                 if (Main.tile[num22, num23 - 3] == null)
                 {
                     Main.tile[num22, num23 - 3] = new Tile();
                 }
                 if (Main.tile[num22, num23 + 1] == null)
                 {
                     Main.tile[num22, num23 + 1] = new Tile();
                 }
                 if (Main.tile[num22 + direction, num23 - 1] == null)
                 {
                     Main.tile[num22 + direction, num23 - 1] = new Tile();
                 }
                 if (Main.tile[num22 + direction, num23 + 1] == null)
                 {
                     Main.tile[num22 + direction, num23 + 1] = new Tile();
                 }
                 if (Main.tile[num22 - direction, num23 + 1] == null)
                 {
                     Main.tile[num22 - direction, num23 + 1] = new Tile();
                 }
                 if (Main.tile[num22 + direction, num23 + 3] == null)
                 {
                     Main.tile[num22 + direction, num23 + 3] = new Tile();
                 }
                 int num24 = spriteDirection;
                 if (type == 423 || type == 410 || type == 546)
                 {
                     num24 *= -1;
                 }
                 if ((velocity.X < 0f && num24 == -1) || (velocity.X > 0f && num24 == 1))
                 {
                     bool flag7 = type == 410 || type == 423;
                     float num25 = 3f;
                     if (Main.tile[num22, num23 - 2].nactive() && Main.tileSolid[Main.tile[num22, num23 - 2].type])
                     {
                         if (Main.tile[num22, num23 - 3].nactive() && Main.tileSolid[Main.tile[num22, num23 - 3].type])
{
                             velocity.Y = -8.5f;
                             netUpdate = true;
                         }
                         else
{
                             velocity.Y = -7.5f;
                             netUpdate = true;
                         }
                     }
                     else if (Main.tile[num22, num23 - 1].nactive() && !Main.tile[num22, num23 - 1].topSlope() && Main.tileSolid[Main.tile[num22, num23 - 1].type])
                     {
                         velocity.Y = -7f;
                         netUpdate = true;
                     }
                     else if (position.Y + (float)height - (float)(num23 * 16) > 20f && Main.tile[num22, num23].nactive() && !Main.tile[num22, num23].topSlope() && Main.tileSolid[Main.tile[num22, num23].type])
                     {
                         velocity.Y = -6f;
                         netUpdate = true;
                     }
                     else if ((directionY < 0 || Math.Abs(velocity.X) > num25) && (!flag7 || !Main.tile[num22, num23 + 1].nactive() || !Main.tileSolid[Main.tile[num22, num23 + 1].type]) && (!Main.tile[num22, num23 + 2].nactive() || !Main.tileSolid[Main.tile[num22, num23 + 2].type]) && (!Main.tile[num22 + direction, num23 + 3].nactive() || !Main.tileSolid[Main.tile[num22 + direction, num23 + 3].type]))
                     {
                         velocity.Y = -8f;
                         netUpdate = true;
                     }
                 }
             }
         }
         if (type == 423 && Math.Abs(velocity.X) >= num11 * 0.95f)
         {
             Rectangle hitbox = base.Hitbox;
             for (int n = 0; n < 2; n++)
             {
                 if (Main.rand.Next(3) == 0)
                 {
                     Dust obj3 = Main.dust[Dust.NewDust(hitbox.TopLeft(), hitbox.Width, hitbox.Height, 242)];
                     obj3.velocity = Vector2.Zero;
                     obj3.noGravity = true;
                     obj3.fadeIn = 1f;
                     obj3.scale = 0.5f + Main.rand.NextFloat();
                 }
             }
         }
         if (type == 546)
         {
             rotation += velocity.X * 0.05f;
             spriteDirection = -direction;
         }
     }
References Entity.active, Lighting.AddLight(), ai, Entity.Center, Player.dead, Entity.direction, directionY, Entity.Distance(), Main.dust, EncourageDespawn(), Dust.fadeIn, frame, GetAttackDamage_ForProjectiles(), GetSpawnSource_ForProjectile(), GetSpawnSourceForNPCFromNPCAI(), gfxOffY, Tile.halfBrick(), Entity.height, HitEffect(), justHit, localAI, Main.myPlayer, Tile.nactive(), Main.netMode, netUpdate, Dust.NewDust(), Dust.NewDustPerfect(), Projectile.NewProjectile(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.npc, Entity.oldPosition, Main.player, SoundEngine.PlaySound(), Dust.position, Entity.position, Main.pumpkinMoon, Main.rand, rotation, Dust.scale, spriteDirection, stepSpeed, target, TargetClosest(), Tile, Main.tile, Main.tileSolid, Main.tileSolidTop, Tile.topSlope(), type, Tile.type, Dust.velocity, Entity.velocity, Entity.wet, Entity.whoAmI, Entity.width, Main.windSpeedTarget, Player.ZoneDesert, and Player.ZoneSandstorm.
Referenced by AI().