Terraria: NPC.MakeTransitionEffectsForTextureChanges
MakeTransitionEffectsForTextureChanges()
void NPC.MakeTransitionEffectsForTextureChanges (int oldAltTexture, int currentAltTexture) inline private
     {
         if (oldAltTexture == 0 && currentAltTexture == 1)
         {
             for (int i = 0; i < 20; i++)
             {
                 Dust.NewDust(position, width, height / 4, 139 + Main.rand.Next(4), 0f, -2f);
             }
         }
         if (oldAltTexture == 1 && currentAltTexture == 0)
         {
             Utils.PoofOfSmoke(position);
         }
         if (type != 633)
         {
             return;
         }
         int num = 2;
         if ((oldAltTexture == 0 && currentAltTexture == num) || (oldAltTexture == num && currentAltTexture == 0))
         {
             for (int j = 0; j < 20; j++)
             {
                 Dust dust = Dust.NewDustDirect(position, width, height, 262, 0f, -2f);
                 dust.noGravity = true;
                 dust.scale = 2f;
             }
         }
     }
References Dust.NewDust(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Utils.PoofOfSmoke(), Main.rand, and Dust.scale.