Terraria: System.Text.Json.Serialization.Converters.ObjectDefaultConverter.OnTryRead
OnTryRead()
override bool System.Text.Json.Serialization.Converters.ObjectDefaultConverter< T >.OnTryRead (ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options, ref ReadStack state, [MaybeNullWhen(false)] out T value) inline package
Definition at line 12 of file ObjectDefaultConverter.cs.
    {
        JsonTypeInfo jsonTypeInfo = state.Current.JsonTypeInfo;
        object obj;
        if (state.UseFastPath)
        {
            if (reader.TokenType != JsonTokenType.StartObject)
            {
                ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(TypeToConvert);
            }
            if (jsonTypeInfo.CreateObject == null)
            {
                ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(jsonTypeInfo.Type, ref reader, ref state);
            }
            obj = jsonTypeInfo.CreateObject();
            if (obj is IJsonOnDeserializing jsonOnDeserializing)
            {
                jsonOnDeserializing.OnDeserializing();
            }
            while (true)
            {
                reader.ReadWithVerify();
                JsonTokenType tokenType = reader.TokenType;
                if (tokenType == JsonTokenType.EndObject)
                {
                    break;
                }
                ReadOnlySpan<byte> propertyName = JsonSerializer.GetPropertyName(ref state, ref reader, options);
                bool useExtensionProperty;
                JsonPropertyInfo jsonPropertyInfo = JsonSerializer.LookupProperty(obj, propertyName, ref state, options, out useExtensionProperty);
                ReadPropertyValue(obj, ref state, ref reader, jsonPropertyInfo, useExtensionProperty);
            }
        }
        else
        {
            if (state.Current.ObjectState == StackFrameObjectState.None)
            {
                if (reader.TokenType != JsonTokenType.StartObject)
                {
                    ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(TypeToConvert);
                }
                state.Current.ObjectState = StackFrameObjectState.StartToken;
            }
            if ((int)state.Current.ObjectState < 14 && options.ReferenceHandlingStrategy == ReferenceHandlingStrategy.Preserve)
            {
                if (!JsonSerializer.ResolveMetadataForJsonObject<T>(ref reader, ref state, options))
                {
                    value = default(T);
                    return false;
                }
                if (state.Current.ObjectState == StackFrameObjectState.ReadRefEndObject)
                {
                    value = (T)state.Current.ReturnValue;
                    return true;
                }
            }
            if ((int)state.Current.ObjectState < 15)
            {
                if (jsonTypeInfo.CreateObject == null)
                {
                    ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(jsonTypeInfo.Type, ref reader, ref state);
                }
                obj = jsonTypeInfo.CreateObject();
                if (obj is IJsonOnDeserializing jsonOnDeserializing2)
                {
                    jsonOnDeserializing2.OnDeserializing();
                }
                state.Current.ReturnValue = obj;
                state.Current.ObjectState = StackFrameObjectState.CreatedObject;
            }
            else
            {
                obj = state.Current.ReturnValue;
            }
            while (true)
            {
                if (state.Current.PropertyState == StackFramePropertyState.None)
                {
                    state.Current.PropertyState = StackFramePropertyState.ReadName;
                    if (!reader.Read())
                    {
                        state.Current.ReturnValue = obj;
                        value = default(T);
                        return false;
                    }
                }
                JsonPropertyInfo jsonPropertyInfo2;
                if ((int)state.Current.PropertyState < 2)
                {
                    state.Current.PropertyState = StackFramePropertyState.Name;
                    JsonTokenType tokenType2 = reader.TokenType;
                    if (tokenType2 == JsonTokenType.EndObject)
                    {
                        break;
                    }
                    ReadOnlySpan<byte> propertyName2 = JsonSerializer.GetPropertyName(ref state, ref reader, options);
                    jsonPropertyInfo2 = JsonSerializer.LookupProperty(obj, propertyName2, ref state, options, out var useExtensionProperty2);
                    state.Current.UseExtensionProperty = useExtensionProperty2;
                }
                else
                {
                    jsonPropertyInfo2 = state.Current.JsonPropertyInfo;
                }
                if ((int)state.Current.PropertyState < 3)
                {
                    if (!jsonPropertyInfo2.ShouldDeserialize)
                    {
                        if (!reader.TrySkip())
{
                            state.Current.ReturnValue = obj;
                            value = default(T);
                            return false;
                        }
                        state.Current.EndProperty();
                        continue;
                    }
                    if (!ReadAheadPropertyValue(ref state, ref reader, jsonPropertyInfo2))
                    {
                        state.Current.ReturnValue = obj;
                        value = default(T);
                        return false;
                    }
                }
                if ((int)state.Current.PropertyState >= 5)
                {
                    continue;
                }
                if (!state.Current.UseExtensionProperty)
                {
                    if (!jsonPropertyInfo2.ReadJsonAndSetMember(obj, ref state, ref reader))
                    {
                        state.Current.ReturnValue = obj;
                        value = default(T);
                        return false;
                    }
                }
                else if (!jsonPropertyInfo2.ReadJsonAndAddExtensionProperty(obj, ref state, ref reader))
                {
                    state.Current.ReturnValue = obj;
                    value = default(T);
                    return false;
                }
                state.Current.EndProperty();
            }
        }
        if (obj is IJsonOnDeserialized jsonOnDeserialized)
        {
            jsonOnDeserialized.OnDeserialized();
        }
        value = (T)obj;
        if (state.Current.PropertyRefCache != null)
        {
            jsonTypeInfo.UpdateSortedPropertyCache(ref state.Current);
        }
        return true;
    }
References System.Text.Json.Dictionary, System.Text.Json.JsonSerializer.GetPropertyName(), System.Text.Json.JsonSerializer.LookupProperty(), System.obj, System.options, System.Text.Json.Serialization.Converters.ObjectDefaultConverter< T >.ReadAheadPropertyValue(), System.Text.Json.Serialization.Converters.ObjectDefaultConverter< T >.ReadPropertyValue(), System.state, System.T, System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(), System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(), and System.value.