Terraria: NPC.AI
AI()
void NPC.AI () inline
References Entity.active, Gore.active, Tile.active(), activeTime, Player.AddBuff(), MoonlordDeathDrama.AddExplosion(), Lighting.AddLight(), ai, Projectile.ai, AI_000_TransformBoundNPC(), AI_001_Slimes(), AI_002_FloatingEye(), AI_003_Fighters(), AI_005_EaterOfSouls(), AI_006_Worms(), AI_007_TownEntities(), AI_026_Unicorns(), AI_037_Destroyer(), AI_045_Golem(), AI_047_GolemFist(), AI_065_Butterflies(), AI_069_DukeFishron(), AI_084_LunaticCultist(), AI_107_ImprovedWalkers(), AI_108_DivingFlyer(), AI_109_DarkMage(), AI_110_Betsy(), AI_111_DD2LightningBug(), AI_112_FairyCritter(), AI_113_WindyBalloon(), AI_114_Dragonflies(), AI_115_LadyBugs(), AI_116_WaterStriders(), AI_117_BloodNautilus(), AI_118_Seahorses(), AI_119_Dandelion(), AI_120_HallowBoss(), AI_121_QueenSlime(), AI_122_PirateGhost(), AI_123_Deerclops(), AI_124_ElderSlimeChest(), AI_125_ClumsySlimeBalloon(), AI_87_BigMimic_FireStuffCannonBurst(), AI_AttemptToFindTeleportSpot(), aiAction, aiStyle, Dust.alpha, alpha, AnyNPCs(), Entity.Bottom, Tile.bottomSlope(), brainOfGravity, TileEntity.ByID, CanBeReplacedByOtherNPCs, Collision.CanHit(), Collision.CanHitLine(), StrayMethods.CanSpawnSandstormHostile(), Entity.Center, Utils.Center(), Utils.CenteredRectangle(), Searches.Chain(), StrayMethods.CheckArenaScore(), checkDead(), CultistRitual.CheckFloor(), Main.cloudAlpha, collideX, collideY, Color, Dust.color, color, GenSearch.Conditions(), confused, CountNPCS(), Player.creativeGodMode, crimsonBoss, Dust.customData, damage, Main.dayTime, SoundID.DD2_EtherianPortalIdleLoop, SoundID.DD2_EtherianPortalOpen, SoundID.DD2_WinScene, EffectManager< T >.Deactivate(), Player.dead, Player.DeadOrGhost, DeathSound, Main.dedServ, defDamage, defDefense, defense, Entity.direction, Entity.DirectionFrom(), Entity.DirectionTo(), directionY, DiscourageDespawn(), Entity.Distance(), dontTakeDamage, dontTakeDamageFromHostiles, Main.dust, Main.eclipse, EncourageDespawn(), DD2Event.EnemySpawningIsOnHold, Main.essScale, Collision.ExpandVertically(), Main.expertMode, Dust.fadeIn, TETrainingDummy.Find(), WorldUtils.Find(), DD2Event.FindArenaHitbox(), Player.FindBuffIndex(), Player.FindClosest(), FindClosestPlayer(), FindFirstNPC(), frame, frameCounter, friendly, Projectile.friendly, SlotId.FromFloat(), Main.GameModeInfo, SoundEngine.GetActiveSound(), GetAttackDamage_ForProjectiles(), GetAttackDamage_LerpBetweenFinalValues(), GetAttackDamage_ScaledByStrength(), GetBrainOfCthuluCreepersCount(), Main.getGoodWorld, Utils.GetLerpValue(), GetMechQueenCenter(), GetMyBalance(), getRect(), Player.getRect(), GetShimmered(), GetSpawnSource_ForProjectile(), GetSpawnSourceForNaturalSpawn(), GetSpawnSourceForNPCFromNPCAI(), GetSpawnSourceForProjectileNPC(), Framing.GetTileSafely(), Collision.GetWaterLine(), gfxOffY, Player.gfxOffY, golemBoss, Main.gore, Player.gravDir, Player.gross, Tile.halfBrick(), TileID.Sets.Conversion.HardenedSand, HealEffect(), Entity.height, hide, Entity.Hitbox, HitEffect(), HitSound, InitializeMoonLordAttacks(), SlotId.Invalid, WorldGen.InWorld(), Main.IsItDay(), IsMechQueenUp, SoundID.Item12, SoundID.Item14, SoundID.Item17, SoundID.Item34, SoundID.Item39, SoundID.Item5, SoundID.Item8, justHit, Projectile.Kill(), knockBackResist, GameModeData.KnockbackToEnemiesMultiplier, DD2Event.LaneSpawnRate, Tile.lava(), Tile.leftSlope(), life, lifeMax, Tile.liquid, localAI, LunarApocalypseIsUp, Main.maxTilesX, Main.maxTilesY, mechQueen, MoonLordAttacksArray, MoonLordAttacksArray2, Main.mouseTextColor, Main.mouseX, Main.mouseY, Main.myPlayer, Tile.nactive(), Main.netMode, netOffset, netSpam, netUpdate, Projectile.netUpdate, Dust.NewDust(), Dust.NewDustDirect(), Dust.NewDustPerfect(), Gore.NewGore(), NewNPC(), Projectile.NewProjectile(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Dust.noGravity, noGravity, Dust.noLight, noTileCollide, Main.npc, NPCCanStickToWalls(), SoundID.NPCDeath3, SoundID.NPCDeath58, SoundID.NPCDeath61, SoundID.NPCHit15, SoundID.NPCHit16, SoundID.NPCHit17, SoundID.NPCHit4, npcsFoundForCheckActive, Player.npcTypeNoAggro, Entity.oldPosition, Entity.oldVelocity, Opacity, plantBoss, TileID.Sets.Platforms, Main.player, SoundEngine.PlaySound(), SoundEngine.PlayTrackedSound(), PopAllAttachedProjectilesAndTakeDamageForThem(), Dust.position, Entity.position, Main.projectile, FixExploitManEaters.ProtectSpot(), Main.pumpkinMoon, Main.rand, Utils.RandomVector2(), realLife, ReflectProjectiles(), reflectsProjectiles, releaseOwner, Main.remixWorld, DD2Event.ReportLoss(), MoonlordDeathDrama.RequestLight(), rotation, TileID.Sets.Conversion.Sand, TileID.Sets.Conversion.Sandstone, Dust.scale, scale, Filters.Scene, Main.screenPosition, NetMessage.SendData(), SetDefaults(), ShieldStrengthTowerNebula, ShieldStrengthTowerSolar, ShieldStrengthTowerStardust, ShieldStrengthTowerVortex, Tile.shimmer(), SimpleFlyMovement(), Main.snowMoon, Collision.SolidCollision(), WorldGen.SolidTile(), WorldGen.SolidTile2(), Collision.SolidTiles(), soundDelay, DD2Event.SpawnMonsterFromGate(), WorldGen.SpawnPlanteraThorns(), SpawnStardustMark_StardustTower(), spriteDirection, Main.StartInvasion(), stepSpeed, ActiveSound.Stop(), DD2Event.StopInvasion(), StrikeNPCNoInteraction(), CultistRitual.TabletDestroyed(), Player.talkNPC, target, TargetClosest(), TargetClosest_WOF(), targetRect, Main.tenthAnniversaryWorld, Tile, Main.tile, Main.tileSolid, Main.tileSolidTop, Main.timeForVisualEffects, timeLeft, Projectile.timeLeft, Entity.Top, Tile.topSlope(), townNPC, Transform(), Gore.type, type, Projectile.type, Tile.type, Main.UnderworldLayer, value, Utils.Vector2FromElipse(), Dust.velocity, Entity.velocity, Gore.velocity, ActiveSound.Volume, Tile.wall, Entity.wet, Entity.whoAmI, Entity.width, Main.windSpeedCurrent, Main.wofDrawAreaBottom, Main.wofDrawAreaTop, Main.wofNPCIndex, Main.worldSurface, X, Y, Player.ZoneCrimson, Player.ZoneJungle, and Player.ZoneLihzhardTemple.