Terraria: NPC.setFireFlyChance
setFireFlyChance()
static void NPC.setFireFlyChance () inline static
     {
         if (Main.rand == null)
         {
             Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
         }
         if (WorldGen.genRand.Next(9) == 0)
         {
             fireFlyChance = Main.rand.Next(5, 10);
             fireFlyFriendly = Main.rand.Next(1, 4);
             fireFlyMultiple = Main.rand.Next(3, 8);
         }
         else if (WorldGen.genRand.Next(3) == 0)
         {
             fireFlyChance = 999999;
             fireFlyFriendly = 999999;
             fireFlyMultiple = 999999;
         }
         else
         {
             fireFlyChance = Main.rand.Next(10, 60);
             fireFlyFriendly = Main.rand.Next(2, 15);
             fireFlyMultiple = Main.rand.Next(6, 30);
         }
         if (Main.rand.Next(3) == 0)
         {
             butterflyChance = 999999;
             stinkBugChance = Main.rand.Next(1, 14);
             if (WorldGen.genRand.Next(5) == 0)
             {
                 stinkBugChance = 999999;
             }
         }
         else
         {
             stinkBugChance = 999999;
             butterflyChance = Main.rand.Next(1, 21);
             if (WorldGen.genRand.Next(5) == 0)
             {
                 butterflyChance = 999999;
             }
         }
         if (Main.tenthAnniversaryWorld)
         {
             fireFlyChance = Math.Max(1, (int)((float)fireFlyChance * 0.5f));
             butterflyChance = Math.Max(1, (int)((float)butterflyChance * 0.5f));
         }
     }
References WorldGen.genRand, UnifiedRandom.Next(), Main.rand, and Main.tenthAnniversaryWorld.
Referenced by WorldFile.LoadWorld(), and Main.UpdateTime_StartNight().