Terraria: NPC.AI_114_Dragonflies
AI_114_Dragonflies()
void NPC.AI_114_Dragonflies () inline private
     {
         if (localAI[0] == 0f && Main.netMode != 1)
         {
             localAI[0] = 1f;
             Vector2 center = base.Center;
             ai[2] = center.X;
             ai[3] = center.Y;
             velocity = (Main.rand.NextVector2Circular(5f, 3f) + Main.rand.NextVector2CircularEdge(5f, 3f)) * 0.4f;
             ai[1] = 0f;
             ai[0] = 1f;
             netUpdate = true;
         }
         switch ((int)ai[0])
         {
         case 0:
             velocity *= 0.94f;
             if (Main.netMode != 1 && (ai[1] += 1f) >= (float)(60 + Main.rand.Next(60)))
             {
                 Vector2 vector = new Vector2(ai[2], ai[3]);
                 if (Distance(vector) > 96f)
                 {
                     velocity = DirectionTo(vector) * 3f;
                 }
                 else if (Distance(vector) > 16f)
                 {
                     velocity = DirectionTo(vector) * 1f + Main.rand.NextVector2Circular(1f, 0.5f);
                 }
                 else
                 {
                     velocity = (Main.rand.NextVector2Circular(5f, 3f) + Main.rand.NextVector2CircularEdge(5f, 3f)) * 0.4f;
                 }
                 ai[1] = 0f;
                 ai[0] = 1f;
                 netUpdate = true;
             }
             break;
         case 1:
         {
             int num = 4;
             Vector2 other = new Vector2(ai[2], ai[3]);
             if (Distance(other) > 112f)
             {
                 num = 200;
             }
             if ((ai[1] += 1f) >= (float)num)
             {
                 ai[1] = 0f;
                 ai[0] = 0f;
                 netUpdate = true;
             }
             int num2 = (int)base.Center.X / 16;
             int num3 = (int)base.Center.Y / 16;
             int num4 = 3;
             for (int i = num3; i < num3 + num4; i++)
             {
                 if (Main.tile[num2, i] != null && ((Main.tile[num2, i].nactive() && Main.tileSolid[Main.tile[num2, i].type]) || Main.tile[num2, i].liquid > 0))
                 {
                     if (velocity.Y > 0f)
                     {
                         velocity.Y *= 0.9f;
                     }
                     velocity.Y -= 0.2f;
                 }
             }
             if (!(velocity.Y < 0f))
             {
                 break;
             }
             int num5 = 30;
             bool flag = false;
             for (int j = num3; j < num3 + num5; j++)
             {
                 if (Main.tile[num2, j] != null && Main.tile[num2, j].nactive() && Main.tileSolid[Main.tile[num2, j].type])
                 {
                     flag = true;
                     break;
                 }
             }
             if (!flag && velocity.Y < 0f)
             {
                 velocity.Y *= 0.9f;
             }
             break;
         }
         }
         if (velocity.X != 0f)
         {
             direction = ((velocity.X > 0f) ? 1 : (-1));
         }
         if (wet)
         {
             velocity.Y = -3f;
         }
         if (localAI[1] > 0f)
         {
             localAI[1] -= 1f;
             return;
         }
         localAI[1] = 15f;
         float num6 = 0f;
         Vector2 zero = Vector2.Zero;
         for (int k = 0; k < 200; k++)
         {
             NPC nPC = Main.npc[k];
             if (nPC.active && nPC.damage > 0 && !nPC.friendly && nPC.Hitbox.Distance(base.Center) <= 100f)
             {
                 num6 += 1f;
                 zero += DirectionFrom(nPC.Center);
             }
         }
         for (int l = 0; l < 255; l++)
         {
             Player player = Main.player[l];
             if (player.active && player.Hitbox.Distance(base.Center) <= 150f)
             {
                 num6 += 1f;
                 zero += DirectionFrom(player.Center);
             }
         }
         if (num6 > 0f)
         {
             float num7 = 2f;
             zero /= num6;
             zero *= num7;
             velocity += zero;
             if (velocity.Length() > 16f)
             {
                 velocity = velocity.SafeNormalize(Vector2.Zero) * 16f;
             }
             Vector2 vector2 = base.Center + zero * 10f;
             ai[1] = -10f;
             ai[0] = 1f;
             ai[2] = vector2.X;
             ai[3] = vector2.Y;
             netUpdate = true;
         }
         else
         {
             if (Main.netMode == 1 || !((new Vector2(ai[2], ai[3]) - base.Center).Length() < 16f))
             {
                 return;
             }
             int maxValue = 30;
             if (Main.tile[(int)ai[2] / 16, (int)ai[3] / 16].type != 519)
             {
                 maxValue = 4;
             }
             if (Main.rand.Next(maxValue) != 0)
             {
                 return;
             }
             int cattailX = (int)ai[2];
             int cattailY = (int)ai[2];
             if (FindCattailTop((int)ai[2] / 16, (int)ai[3] / 16, out cattailX, out cattailY))
             {
                 ai[2] = cattailX * 16;
                 ai[3] = cattailY * 16;
                 netUpdate = true;
                 return;
             }
             int num8 = (int)(base.Center.X / 16f);
             int m;
             for (m = (int)(base.Center.Y / 16f); !WorldGen.SolidTile(num8, m) && (double)m < Main.worldSurface; m++)
             {
             }
             m -= Main.rand.Next(3, 6);
             ai[2] = num8 * 16;
             ai[3] = m * 16;
             netUpdate = true;
         }
     }
References Entity.active, ai, Entity.Center, damage, Entity.direction, Entity.DirectionFrom(), Entity.DirectionTo(), Entity.Distance(), FindCattailTop(), friendly, Entity.Hitbox, Tile.liquid, localAI, Tile.nactive(), Main.netMode, netUpdate, UnifiedRandom.Next(), Main.npc, Main.player, Main.rand, WorldGen.SolidTile(), Main.tile, Main.tileSolid, Tile.type, Entity.velocity, Entity.wet, and Main.worldSurface.
Referenced by AI().