Terraria: NPC.ScaleStats
ScaleStats()
void NPC.ScaleStats (int? activePlayersCount, GameModeData gameModeData, float? strengthOverride) inline
     {
         if ((!NPCID.Sets.NeedsExpertScaling.IndexInRange(type) || !NPCID.Sets.NeedsExpertScaling[type]) && (lifeMax <= 5 || damage == 0 || friendly || townNPC))
         {
             return;
         }
         float num = 1f;
         if (strengthOverride.HasValue)
         {
             num = strengthOverride.Value;
         }
         else if (gameModeData.IsJourneyMode)
         {
             CreativePowers.DifficultySliderPower power = CreativePowerManager.Instance.GetPower<CreativePowers.DifficultySliderPower>();
             if (power != null && power.GetIsUnlocked())
             {
                 num = power.StrengthMultiplierToGiveNPCs;
             }
         }
         float num2 = num;
         if (gameModeData.IsJourneyMode && Main.getGoodWorld)
         {
             num += 1f;
         }
         NPCStrengthHelper nPCStrengthHelper = new NPCStrengthHelper(gameModeData, num, Main.getGoodWorld);
         if (nPCStrengthHelper.IsExpertMode)
         {
             ScaleStats_ApplyExpertTweaks();
         }
         ScaleStats_ApplyGameMode(gameModeData);
         if (Main.getGoodWorld && nPCStrengthHelper.ExtraDamageForGetGoodWorld)
         {
             damage += damage / 3;
         }
         if (nPCStrengthHelper.IsExpertMode)
         {
             int num3 = 1;
             num3 = (statsAreScaledForThisManyPlayers = ((!activePlayersCount.HasValue) ? GetActivePlayerCount() : activePlayersCount.Value));
             GetStatScalingFactors(num3, out var balance, out var boost);
             float bossAdjustment = 1f;
             if (nPCStrengthHelper.IsMasterMode)
             {
                 bossAdjustment = 0.85f;
             }
             ScaleStats_ApplyMultiplayerStats(num3, balance, boost, bossAdjustment);
         }
         ScaleStats_UseStrengthMultiplier(num);
         strengthMultiplier = num2;
         if ((type < 0 || !NPCID.Sets.ProjectileNPC[type]) && lifeMax < 6)
         {
             lifeMax = 6;
         }
         life = lifeMax;
         defDamage = damage;
         defDefense = defense;
     }
References damage, defDamage, defDefense, defense, NPCStrengthHelper.ExtraDamageForGetGoodWorld, friendly, GetActivePlayerCount(), Main.getGoodWorld, GetStatScalingFactors(), CreativePowerManager.Instance, NPCStrengthHelper.IsExpertMode, GameModeData.IsJourneyMode, NPCStrengthHelper.IsMasterMode, life, lifeMax, NPCID.Sets.NeedsExpertScaling, NPCID.Sets.ProjectileNPC, ScaleStats_ApplyExpertTweaks(), ScaleStats_ApplyGameMode(), ScaleStats_ApplyMultiplayerStats(), ScaleStats_UseStrengthMultiplier(), statsAreScaledForThisManyPlayers, strengthMultiplier, CreativePowers.DifficultySliderPower.StrengthMultiplierToGiveNPCs, townNPC, and type.
Referenced by SetDefaults(), and SetDefaultsFromNetId().