Terraria: NPC.HitEffect
HitEffect()
void NPC.HitEffect (int hitDirection = 0, double dmg = 10.0) inline
References Entity.active, AddBuff(), ai, Dust.alpha, Gore.alpha, buffImmune, Collision.CanHitLine(), Entity.Center, DD2Event.CheckProgress(), Dust.CloneDust(), Color, Dust.color, dontTakeDamage, Main.dust, Dust.fadeIn, friendly, SlotId.FromFloat(), SoundEngine.GetActiveSound(), Main.gore, Main.hslToRgb(), Tile.lava(), lifeMax, Main.myPlayer, Tile.nactive(), Main.netMode, netUpdate, Dust.NewDust(), Dust.NewDustDirect(), Gore.NewGore(), Gore.NewGorePerfect(), Projectile.NewProjectile(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Dust.noGravity, Main.npc, Main.player, SoundEngine.PlaySound(), Dust.position, Entity.position, Gore.position, Main.rand, Utils.RandomVector2(), ParticleOrchestrator.RequestParticleSpawn(), Gore.rotation, Dust.scale, NetMessage.SendData(), SetDefaults(), Collision.SolidTiles(), MoonlordDeathDrama.ThrowPieces(), Main.tile, townNPC, Dust.velocity, Entity.velocity, Gore.velocity, X, and Y.
Referenced by AI(), AI_006_Worms(), AI_007_TownEntities(), AI_026_Unicorns(), AI_037_Destroyer(), AI_084_LunaticCultist(), AI_107_ImprovedWalkers(), AI_108_DivingFlyer(), AI_113_WindyBalloon(), AI_123_Deerclops(), AI_125_ClumsySlimeBalloon(), MessageBuffer.GetData(), and StrikeNPC().