Terraria: NPC.CreateBrickBoxForWallOfFlesh
CreateBrickBoxForWallOfFlesh()
void NPC.CreateBrickBoxForWallOfFlesh () inline private
     {
         int num = (int)(position.X + (float)(width / 2)) / 16;
         int num2 = (int)(position.Y + (float)(height / 2)) / 16;
         int num3 = width / 2 / 16 + 1;
         for (int i = num - num3; i <= num + num3; i++)
         {
             for (int j = num2 - num3; j <= num2 + num3; j++)
             {
                 if ((i == num - num3 || i == num + num3 || j == num2 - num3 || j == num2 + num3) && !Main.tile[i, j].active())
                 {
                     Main.tile[i, j].type = (ushort)(WorldGen.crimson ? 347 : 140);
                     Main.tile[i, j].active(active: true);
                 }
                 Main.tile[i, j].lava(lava: false);
                 Main.tile[i, j].liquid = 0;
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, i, j);
                 }
                 else
                 {
                     WorldGen.SquareTileFrame(i, j);
                 }
             }
         }
     }
References Entity.active, Tile.active(), WorldGen.crimson, Entity.height, Tile.lava(), Tile.liquid, Main.netMode, Entity.position, NetMessage.SendTileSquare(), WorldGen.SquareTileFrame(), Main.tile, Tile.type, and Entity.width.
Referenced by DoDeathEvents().