Terraria: NPC.UpdateNPC_BuffApplyDOTs
UpdateNPC_BuffApplyDOTs()
void NPC.UpdateNPC_BuffApplyDOTs () inline private
     {
         if (dontTakeDamage)
         {
             return;
         }
         int num = lifeRegenExpectedLossPerSecond;
         if (poisoned)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegen -= 12;
         }
         if (onFire)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegen -= 8;
         }
         if (onFire3)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegen -= 30;
             if (num < 5)
             {
                 num = 5;
             }
         }
         if (onFrostBurn)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegen -= 16;
             if (num < 2)
             {
                 num = 2;
             }
         }
         if (onFrostBurn2)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegen -= 50;
             if (num < 10)
             {
                 num = 10;
             }
         }
         if (onFire2)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegen -= 48;
             if (num < 10)
             {
                 num = 10;
             }
         }
         if (venom)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegen -= 60;
             if (num < 15)
             {
                 num = 15;
             }
         }
         if (shadowFlame)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegen -= 30;
             if (num < 5)
             {
                 num = 5;
             }
         }
         if (oiled && (onFire || onFire2 || onFire3 || onFrostBurn || onFrostBurn2 || shadowFlame))
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegen -= 50;
             if (num < 10)
             {
                 num = 10;
             }
         }
         if (javelined)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             int num2 = 0;
             int num3 = 1;
             for (int i = 0; i < 1000; i++)
             {
                 if (Main.projectile[i].active && Main.projectile[i].type == 598 && Main.projectile[i].ai[0] == 1f && Main.projectile[i].ai[1] == (float)whoAmI)
                 {
                     num2++;
                 }
             }
             lifeRegen -= num2 * 2 * 3;
             if (num < num2 * 3 / num3)
             {
                 num = num2 * 3 / num3;
             }
         }
         if (tentacleSpiked)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             int num4 = 0;
             int num5 = 1;
             for (int j = 0; j < 1000; j++)
             {
                 if (Main.projectile[j].active && Main.projectile[j].type == 971 && Main.projectile[j].ai[0] == 1f && Main.projectile[j].ai[1] == (float)whoAmI)
                 {
                     num4++;
                 }
             }
             lifeRegen -= num4 * 2 * 3;
             if (num < num4 * 3 / num5)
             {
                 num = num4 * 3 / num5;
             }
         }
         if (bloodButchered)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             int num6 = 0;
             int num7 = 1;
             for (int k = 0; k < 1000; k++)
             {
                 if (Main.projectile[k].active && Main.projectile[k].type == 975 && Main.projectile[k].ai[0] == 1f && Main.projectile[k].ai[1] == (float)whoAmI)
                 {
                     num6++;
                 }
             }
             lifeRegen -= num6 * 2 * 4;
             if (num < num6 * 4 / num7)
             {
                 num = num6 * 4 / num7;
             }
         }
         if (daybreak)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             int num8 = 0;
             int num9 = 4;
             for (int l = 0; l < 1000; l++)
             {
                 if (Main.projectile[l].active && Main.projectile[l].type == 636 && Main.projectile[l].ai[0] == 1f && Main.projectile[l].ai[1] == (float)whoAmI)
                 {
                     num8++;
                 }
             }
             if (num8 == 0)
             {
                 num8 = 1;
             }
             lifeRegen -= num8 * 2 * 100;
             if (num < num8 * 100 / num9)
             {
                 num = num8 * 100 / num9;
             }
         }
         if (celled)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             int num10 = 0;
             for (int m = 0; m < 1000; m++)
             {
                 if (Main.projectile[m].active && Main.projectile[m].type == 614 && Main.projectile[m].ai[0] == 1f && Main.projectile[m].ai[1] == (float)whoAmI)
                 {
                     num10++;
                 }
             }
             lifeRegen -= num10 * 2 * 20;
             if (num < num10 * 20)
             {
                 num = num10 * 20 / 2;
             }
         }
         if (dryadBane)
         {
             int num11 = 4;
             float num12 = 1f;
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             if (downedBoss1)
             {
                 num12 += 0.1f;
             }
             if (downedBoss2)
             {
                 num12 += 0.1f;
             }
             if (downedBoss3)
             {
                 num12 += 0.1f;
             }
             if (downedQueenBee)
             {
                 num12 += 0.1f;
             }
             if (Main.hardMode)
             {
                 num12 += 0.4f;
             }
             if (downedMechBoss1)
             {
                 num12 += 0.15f;
             }
             if (downedMechBoss2)
             {
                 num12 += 0.15f;
             }
             if (downedMechBoss3)
             {
                 num12 += 0.15f;
             }
             if (downedPlantBoss)
             {
                 num12 += 0.15f;
             }
             if (downedGolemBoss)
             {
                 num12 += 0.15f;
             }
             if (downedAncientCultist)
             {
                 num12 += 0.15f;
             }
             if (Main.expertMode)
             {
                 num12 *= Main.GameModeInfo.TownNPCDamageMultiplier;
             }
             num11 = (int)((float)num11 * num12);
             lifeRegen -= 2 * num11;
             if (num < num11)
             {
                 num = num11 / 3;
             }
         }
         if (soulDrain && realLife == -1)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegen -= 50;
             if (num < 5)
             {
                 num = 5;
             }
         }
         if (lifeRegen <= -240 && num < 2)
         {
             num = 2;
         }
         lifeRegenCount += lifeRegen;
         while (lifeRegenCount >= 120)
         {
             lifeRegenCount -= 120;
             if (!immortal)
             {
                 if (life < lifeMax)
                 {
                     life++;
                 }
                 if (life > lifeMax)
                 {
                     life = lifeMax;
                 }
             }
         }
         if (num > 0)
         {
             while (lifeRegenCount <= -120 * num)
             {
                 lifeRegenCount += 120 * num;
                 int num13 = whoAmI;
                 if (realLife >= 0)
                 {
                     num13 = realLife;
                 }
                 if (!Main.npc[num13].immortal)
                 {
                     Main.npc[num13].life -= num;
                 }
                 CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegenNegative, num, dramatic: false, dot: true);
                 if (Main.npc[num13].life > 0 || Main.npc[num13].immortal)
                 {
                     continue;
                 }
                 Main.npc[num13].life = 1;
                 if (Main.netMode != 1)
                 {
                     Main.npc[num13].StrikeNPCNoInteraction(9999, 0f, 0);
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendData(28, -1, -1, null, num13, 9999f);
                     }
                 }
             }
             return;
         }
         while (lifeRegenCount <= -120)
         {
             lifeRegenCount += 120;
             int num14 = whoAmI;
             if (realLife >= 0)
             {
                 num14 = realLife;
             }
             if (!Main.npc[num14].immortal)
             {
                 Main.npc[num14].life--;
             }
             CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegenNegative, 1, dramatic: false, dot: true);
             if (Main.npc[num14].life > 0 || Main.npc[num14].immortal)
             {
                 continue;
             }
             Main.npc[num14].life = 1;
             if (Main.netMode != 1)
             {
                 Main.npc[num14].StrikeNPCNoInteraction(9999, 0f, 0);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendData(28, -1, -1, null, num14, 9999f);
                 }
             }
         }
     }
References Entity.active, Projectile.ai, Main.expertMode, Main.GameModeInfo, Main.hardMode, immortal, life, CombatText.LifeRegenNegative, Main.netMode, CombatText.NewText(), Main.npc, Main.projectile, NetMessage.SendData(), StrikeNPCNoInteraction(), GameModeData.TownNPCDamageMultiplier, and Projectile.type.