Terraria: NPC.UpdateNPC
UpdateNPC()
void NPC.UpdateNPC (int i) inline
     {
         whoAmI = i;
         if (!active)
         {
             return;
         }
         if (offSetDelayTime > 0)
         {
             netOffset *= 0f;
         }
         else if (Main.netMode == 2)
         {
             netOffset *= 0f;
         }
         else if (Main.multiplayerNPCSmoothingRange <= 0)
         {
             netOffset *= 0f;
         }
         else if (netOffset != new Vector2(0f, 0f))
         {
             if (NPCID.Sets.NoMultiplayerSmoothingByType[type])
             {
                 netOffset *= 0f;
             }
             else if (NPCID.Sets.NoMultiplayerSmoothingByAI[aiStyle])
             {
                 netOffset *= 0f;
             }
             else
             {
                 float num = 2f;
                 float num2 = Main.multiplayerNPCSmoothingRange;
                 float num3 = netOffset.Length();
                 if (num3 > num2)
                 {
                     netOffset.Normalize();
                     netOffset *= num2;
                     num3 = netOffset.Length();
                 }
                 num += num3 / num2 * num;
                 Vector2 vector = netOffset;
                 vector.Normalize();
                 vector *= num;
                 netOffset -= vector;
                 if (netOffset.Length() < num)
                 {
                     netOffset *= 0f;
                 }
                 if (townNPC)
                 {
                     if (Vector2.Distance(position, new Vector2(homeTileX * 16 + 8 - width / 2, (float)(homeTileY * 16 - height) - 0.1f)) < 1f)
                     {
                         netOffset *= 0f;
                     }
                     if (ai[0] == 25f)
                     {
                         netOffset *= 0f;
                     }
                 }
             }
         }
         UpdateAltTexture();
         if (type == 368)
         {
             travelNPC = true;
         }
         if (Main.netMode != 2)
         {
             UpdateNPC_CastLights();
         }
         UpdateNPC_TeleportVisuals();
         UpdateNPC_CritterSounds();
         TrySyncingUniqueTownNPCData(i);
         if (aiStyle == 7 && position.Y > Main.bottomWorld - 640f + (float)height && Main.netMode != 1 && !Main.xMas)
         {
             StrikeNPCNoInteraction(9999, 0f, 0);
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(28, -1, -1, null, whoAmI, 9999f);
             }
         }
         if (Main.netMode == 1)
         {
             bool flag = false;
             int num4 = (int)(position.X + (float)(width / 2)) / 16;
             int num5 = (int)(position.Y + (float)(height / 2)) / 16;
             try
             {
                 if (num4 >= 4 && num4 <= Main.maxTilesX - 4 && num5 >= 4 && num5 <= Main.maxTilesY - 4)
                 {
                     if (Main.tile[num4, num5] == null)
                     {
                         flag = true;
                     }
                     else if (Main.tile[num4 - 3, num5] == null)
                     {
                         flag = true;
                     }
                     else if (Main.tile[num4 + 3, num5] == null)
                     {
                         flag = true;
                     }
                     else if (Main.tile[num4, num5 - 3] == null)
                     {
                         flag = true;
                     }
                     else if (Main.tile[num4, num5 + 3] == null)
                     {
                         flag = true;
                     }
                 }
             }
             catch
             {
                 flag = true;
             }
             if (flag)
             {
                 return;
             }
         }
         UpdateNPC_BuffFlagsReset();
         UpdateNPC_BuffSetFlags();
         UpdateNPC_SoulDrainDebuff();
         UpdateNPC_BuffClearExpiredBuffs();
         UpdateNPC_BuffApplyDOTs();
         UpdateNPC_BuffApplyVFX();
         UpdateNPC_BloodMoonTransformations();
         UpdateNPC_UpdateGravity(out var maxFallSpeed);
         if (soundDelay > 0)
         {
             soundDelay--;
         }
         if (life <= 0)
         {
             active = false;
             UpdateNetworkCode(i);
             netUpdate = false;
             justHit = false;
             return;
         }
         oldTarget = target;
         oldDirection = direction;
         oldDirectionY = directionY;
         float num6 = 1f + Math.Abs(velocity.X) / 3f;
         if (gfxOffY > 0f)
         {
             gfxOffY -= num6 * stepSpeed;
             if (gfxOffY < 0f)
             {
                 gfxOffY = 0f;
             }
         }
         else if (gfxOffY < 0f)
         {
             gfxOffY += num6 * stepSpeed;
             if (gfxOffY > 0f)
             {
                 gfxOffY = 0f;
             }
         }
         if (gfxOffY > 16f)
         {
             gfxOffY = 16f;
         }
         if (gfxOffY < -16f)
         {
             gfxOffY = -16f;
         }
         TryPortalJumping();
         IdleSounds();
         AI();
         SubAI_HandleTemporaryCatchableNPCPlayerInvulnerability();
         if (Main.netMode != 2 && extraValue > 0)
         {
             int num7 = 244;
             float num8 = 30f;
             if (extraValue >= 1000000)
             {
                 num7 = 247;
                 num8 *= 0.25f;
             }
             else if (extraValue >= 10000)
             {
                 num7 = 246;
                 num8 *= 0.5f;
             }
             else if (extraValue >= 100)
             {
                 num7 = 245;
                 num8 *= 0.75f;
             }
             if (Main.rand.Next((int)num8) == 0)
             {
                 position += netOffset;
                 int num9 = Dust.NewDust(position, width, height, num7, 0f, 0f, 254, default(Color), 0.25f);
                 Main.dust[num9].velocity *= 0.1f;
                 position -= netOffset;
             }
         }
         for (int j = 0; j < 256; j++)
         {
             if (immune[j] > 0)
             {
                 immune[j]--;
             }
         }
         if (!noGravity && !noTileCollide)
         {
             int num10 = (int)(position.X + (float)(width / 2)) / 16;
             int num11 = (int)(position.Y + (float)(height / 2)) / 16;
             if (WorldGen.InWorld(num10, num11) && Main.tile[num10, num11] == null)
             {
                 gravity = 0f;
                 velocity.X = 0f;
                 velocity.Y = 0f;
             }
         }
         if (!noGravity)
         {
             velocity.Y += gravity;
             if (velocity.Y > maxFallSpeed)
             {
                 velocity.Y = maxFallSpeed;
             }
         }
         if ((double)velocity.X < 0.005 && (double)velocity.X > -0.005)
         {
             velocity.X = 0f;
         }
         if (Main.netMode != 1 && type != 37 && (friendly || NPCID.Sets.TakesDamageFromHostilesWithoutBeingFriendly[type]))
         {
             if (townNPC)
             {
                 CheckDrowning();
             }
             CheckLifeRegen();
             GetHurtByOtherNPCs(NPCID.Sets.AllNPCs);
         }
         if (Main.netMode != 1 && (npcsFoundForCheckActive[210] || npcsFoundForCheckActive[211]) && !NPCID.Sets.HurtingBees[type])
         {
             GetHurtByOtherNPCs(NPCID.Sets.HurtingBees);
         }
         if (!noTileCollide)
         {
             UpdateCollision();
         }
         else
         {
             oldPosition = position;
             oldDirection = direction;
             position += velocity;
             if (onFire && boss && Main.netMode != 1 && Collision.WetCollision(position, width, height))
             {
                 for (int k = 0; k < maxBuffs; k++)
                 {
                     if (buffType[k] == 24)
                     {
                         DelBuff(k);
                     }
                 }
             }
         }
         if (Main.netMode != 1 && !noTileCollide && lifeMax > 1 && Collision.SwitchTiles(position, width, height, oldPosition, 2) && (type == 46 || type == 148 || type == 149 || type == 303 || type == 361 || type == 362 || type == 364 || type == 366 || type == 367 || (type >= 442 && type <= 448) || type == 602 || type == 608 || type == 614 || type == 687))
         {
             ai[0] = 1f;
             ai[1] = 400f;
             ai[2] = 0f;
         }
         FindFrame();
         UpdateNPC_UpdateTrails();
         UpdateNetworkCode(i);
         CheckActive();
         netUpdate = false;
         justHit = false;
     }
References NPCID.Sets.AllNPCs, Main.bottomWorld, Color, Main.dust, NPCID.Sets.HurtingBees, WorldGen.InWorld(), Main.maxTilesY, Main.multiplayerNPCSmoothingRange, Main.netMode, Dust.NewDust(), UnifiedRandom.Next(), NPCID.Sets.NoMultiplayerSmoothingByAI, NPCID.Sets.NoMultiplayerSmoothingByType, Main.rand, NetMessage.SendData(), Collision.SwitchTiles(), NPCID.Sets.TakesDamageFromHostilesWithoutBeingFriendly, Main.tile, Dust.velocity, Collision.WetCollision(), and Main.xMas.
Referenced by Main.DoUpdateInWorld().