Terraria: NPC.AI_084_LunaticCultist
AI_084_LunaticCultist()
void NPC.AI_084_LunaticCultist () inline private
     {
         if (this.ai[0] != -1f && Main.rand.Next(1000) == 0)
         {
             SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, Main.rand.Next(88, 92));
         }
         bool expertMode = Main.expertMode;
         bool flag = life <= lifeMax / 2;
         int num = 120;
         int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(35f, 25f);
         if (expertMode)
         {
             num = 90;
         }
         if (Main.getGoodWorld)
         {
             num -= 30;
         }
         int num2 = 18;
         int num3 = 3;
         int attackDamage_ForProjectiles2 = GetAttackDamage_ForProjectiles(30f, 20f);
         if (expertMode)
         {
             num2 = 12;
             num3 = 4;
         }
         if (Main.getGoodWorld)
         {
             num2 = 10;
             num3 = 5;
         }
         int num4 = 80;
         int attackDamage_ForProjectiles3 = GetAttackDamage_ForProjectiles(45f, 30f);
         if (expertMode)
         {
             num4 = 40;
         }
         if (Main.getGoodWorld)
         {
             num4 -= 20;
         }
         int num5 = 20;
         int num6 = 2;
         if (expertMode)
         {
             num5 = 30;
             num6 = 2;
         }
         int num7 = 20;
         int num8 = 3;
         bool flag2 = type == 439;
         bool flag3 = false;
         bool flag4 = false;
         if (flag)
         {
             defense = (int)((float)defDefense * 0.65f);
         }
         if (!flag2)
         {
             if (this.ai[3] < 0f || !Main.npc[(int)this.ai[3]].active || Main.npc[(int)this.ai[3]].type != 439)
             {
                 life = 0;
                 HitEffect();
                 active = false;
                 return;
             }
             this.ai[0] = Main.npc[(int)this.ai[3]].ai[0];
             this.ai[1] = Main.npc[(int)this.ai[3]].ai[1];
             if (this.ai[0] == 5f)
             {
                 if (justHit)
                 {
                     life = 0;
                     HitEffect();
                     active = false;
                     if (Main.netMode != 1)
                     {
                         NetMessage.SendData(23, -1, -1, null, whoAmI);
                     }
                     NPC obj = Main.npc[(int)this.ai[3]];
                     obj.ai[0] = 6f;
                     obj.ai[1] = 0f;
                     obj.netUpdate = true;
                 }
             }
             else
             {
                 flag3 = true;
                 flag4 = true;
             }
         }
         else if (this.ai[0] == 5f && this.ai[1] >= 120f && this.ai[1] < 420f && justHit)
         {
             this.ai[0] = 0f;
             this.ai[1] = 0f;
             this.ai[3] += 1f;
             velocity = Vector2.Zero;
             netUpdate = true;
             List<int> list = new List<int>();
             for (int i = 0; i < 200; i++)
             {
                 if (Main.npc[i].active && Main.npc[i].type == 440 && Main.npc[i].ai[3] == (float)whoAmI)
                 {
                     list.Add(i);
                 }
             }
             int num9 = 10;
             if (Main.expertMode)
             {
                 num9 = 3;
             }
             foreach (int item in list)
             {
                 NPC nPC = Main.npc[item];
                 if (nPC.localAI[1] == localAI[1] && num9 > 0)
                 {
                     num9--;
                     nPC.life = 0;
                     nPC.HitEffect();
                     nPC.active = false;
                     if (Main.netMode != 1)
                     {
                         NetMessage.SendData(23, -1, -1, null, item);
                     }
                 }
                 else if (num9 > 0)
                 {
                     num9--;
                     nPC.life = 0;
                     nPC.HitEffect();
                     nPC.active = false;
                 }
             }
             Main.projectile[(int)this.ai[2]].ai[1] = -1f;
             Main.projectile[(int)this.ai[2]].netUpdate = true;
         }
         Vector2 center = base.Center;
         Player player = Main.player[target];
         float num10 = 5600f;
         if (target < 0 || target == 255 || player.dead || !player.active || Vector2.Distance(player.Center, center) > num10)
         {
             TargetClosest(faceTarget: false);
             player = Main.player[target];
             netUpdate = true;
         }
         if (player.dead || !player.active || Vector2.Distance(player.Center, center) > num10)
         {
             life = 0;
             HitEffect();
             active = false;
             if (Main.netMode != 1)
             {
                 NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
             }
             new List<int>().Add(whoAmI);
             for (int j = 0; j < 200; j++)
             {
                 if (Main.npc[j].active && Main.npc[j].type == 440 && Main.npc[j].ai[3] == (float)whoAmI)
                 {
                     Main.npc[j].life = 0;
                     Main.npc[j].HitEffect();
                     Main.npc[j].active = false;
                     if (Main.netMode != 1)
                     {
                         NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                     }
                 }
             }
         }
         float num11 = this.ai[3];
         if (localAI[0] == 0f)
         {
             SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 89);
             localAI[0] = 1f;
             alpha = 255;
             rotation = 0f;
             if (Main.netMode != 1)
             {
                 this.ai[0] = -1f;
                 netUpdate = true;
             }
         }
         if (this.ai[0] == -1f)
         {
             alpha -= 5;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             this.ai[1] += 1f;
             if (this.ai[1] >= 420f)
             {
                 this.ai[0] = 0f;
                 this.ai[1] = 0f;
                 netUpdate = true;
             }
             else if (this.ai[1] > 360f)
             {
                 velocity *= 0.95f;
                 if (localAI[2] != 13f)
                 {
                     SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 105);
                 }
                 localAI[2] = 13f;
             }
             else if (this.ai[1] > 300f)
             {
                 velocity = -Vector2.UnitY;
                 localAI[2] = 10f;
             }
             else if (this.ai[1] > 120f)
             {
                 localAI[2] = 1f;
             }
             else
             {
                 localAI[2] = 0f;
             }
             flag3 = true;
             flag4 = true;
         }
         if (this.ai[0] == 0f)
         {
             if (this.ai[1] == 0f)
             {
                 TargetClosest(faceTarget: false);
             }
             localAI[2] = 10f;
             int num12 = Math.Sign(player.Center.X - center.X);
             if (num12 != 0)
             {
                 direction = (spriteDirection = num12);
             }
             this.ai[1] += 1f;
             if (this.ai[1] >= 40f && flag2)
             {
                 int num13 = 0;
                 if (flag)
                 {
                     switch ((int)this.ai[3])
                     {
                     case 0:
                         num13 = 0;
                         break;
                     case 1:
                         num13 = 1;
                         break;
                     case 2:
                         num13 = 0;
                         break;
                     case 3:
                         num13 = 5;
                         break;
                     case 4:
                         num13 = 0;
                         break;
                     case 5:
                         num13 = 3;
                         break;
                     case 6:
                         num13 = 0;
                         break;
                     case 7:
                         num13 = 5;
                         break;
                     case 8:
                         num13 = 0;
                         break;
                     case 9:
                         num13 = 2;
                         break;
                     case 10:
                         num13 = 0;
                         break;
                     case 11:
                         num13 = 3;
                         break;
                     case 12:
                         num13 = 0;
                         break;
                     case 13:
                         num13 = 4;
                         this.ai[3] = -1f;
                         break;
                     default:
                         this.ai[3] = -1f;
                         break;
                     }
                 }
                 else
                 {
                     switch ((int)this.ai[3])
                     {
                     case 0:
                         num13 = 0;
                         break;
                     case 1:
                         num13 = 1;
                         break;
                     case 2:
                         num13 = 0;
                         break;
                     case 3:
                         num13 = 2;
                         break;
                     case 4:
                         num13 = 0;
                         break;
                     case 5:
                         num13 = 3;
                         break;
                     case 6:
                         num13 = 0;
                         break;
                     case 7:
                         num13 = 1;
                         break;
                     case 8:
                         num13 = 0;
                         break;
                     case 9:
                         num13 = 2;
                         break;
                     case 10:
                         num13 = 0;
                         break;
                     case 11:
                         num13 = 4;
                         this.ai[3] = -1f;
                         break;
                     default:
                         this.ai[3] = -1f;
                         break;
                     }
                 }
                 int maxValue = 6;
                 if (life < lifeMax / 3)
                 {
                     maxValue = 4;
                 }
                 if (life < lifeMax / 4)
                 {
                     maxValue = 3;
                 }
                 if (expertMode && flag && Main.rand.Next(maxValue) == 0 && num13 != 0 && num13 != 4 && num13 != 5 && CountNPCS(523) < 10)
                 {
                     num13 = 6;
                 }
                 if (num13 == 0)
                 {
                     float num14 = (float)Math.Ceiling((player.Center + new Vector2(0f, -100f) - center).Length() / 50f);
                     if (num14 == 0f)
                     {
                         num14 = 1f;
                     }
                     List<int> list2 = new List<int>();
                     int num15 = 0;
                     list2.Add(whoAmI);
                     for (int k = 0; k < 200; k++)
                     {
                         if (Main.npc[k].active && Main.npc[k].type == 440 && Main.npc[k].ai[3] == (float)whoAmI)
{
                             list2.Add(k);
                         }
                     }
                     bool flag5 = list2.Count % 2 == 0;
                     foreach (int item2 in list2)
                     {
                         NPC nPC2 = Main.npc[item2];
                         Vector2 center2 = nPC2.Center;
                         float num16 = (float)((num15 + flag5.ToInt() + 1) / 2) * ((float)Math.PI * 2f) * 0.4f / (float)list2.Count;
                         if (num15 % 2 == 1)
{
                             num16 *= -1f;
                         }
                         if (list2.Count == 1)
{
                             num16 = 0f;
                         }
                         Vector2 vector = new Vector2(0f, -1f).RotatedBy(num16) * new Vector2(300f, 200f);
                         Vector2 vector2 = player.Center + vector - center2;
                         nPC2.ai[0] = 1f;
                         nPC2.ai[1] = num14 * 2f;
                         nPC2.velocity = vector2 / num14;
                         if (whoAmI >= nPC2.whoAmI)
{
                             nPC2.position -= nPC2.velocity;
                         }
                         nPC2.netUpdate = true;
                         num15++;
                     }
                 }
                 switch (num13)
                 {
                 case 1:
                     this.ai[0] = 3f;
                     this.ai[1] = 0f;
                     break;
                 case 2:
                     this.ai[0] = 2f;
                     this.ai[1] = 0f;
                     break;
                 case 3:
                     this.ai[0] = 4f;
                     this.ai[1] = 0f;
                     break;
                 case 4:
                     this.ai[0] = 5f;
                     this.ai[1] = 0f;
                     break;
                 }
                 if (num13 == 5)
                 {
                     this.ai[0] = 7f;
                     this.ai[1] = 0f;
                 }
                 if (num13 == 6)
                 {
                     this.ai[0] = 8f;
                     this.ai[1] = 0f;
                 }
                 netUpdate = true;
             }
         }
         else if (this.ai[0] == 1f)
         {
             flag3 = true;
             localAI[2] = 10f;
             if ((float)(int)this.ai[1] % 2f != 0f && this.ai[1] != 1f)
             {
                 position -= velocity;
             }
             this.ai[1] -= 1f;
             if (this.ai[1] <= 0f)
             {
                 this.ai[0] = 0f;
                 this.ai[1] = 0f;
                 this.ai[3] += 1f;
                 velocity = Vector2.Zero;
                 netUpdate = true;
             }
         }
         else if (this.ai[0] == 2f)
         {
             localAI[2] = 11f;
             Vector2 vec = Vector2.Normalize(player.Center - center);
             if (vec.HasNaNs())
             {
                 vec = new Vector2(direction, 0f);
             }
             if (this.ai[1] >= 4f && flag2 && (int)(this.ai[1] - 4f) % num == 0)
             {
                 if (Main.netMode != 1)
                 {
                     List<int> list3 = new List<int>();
                     for (int l = 0; l < 200; l++)
                     {
                         if (Main.npc[l].active && Main.npc[l].type == 440 && Main.npc[l].ai[3] == (float)whoAmI)
{
                             list3.Add(l);
                         }
                     }
                     foreach (int item3 in list3)
                     {
                         NPC nPC3 = Main.npc[item3];
                         Vector2 center3 = nPC3.Center;
                         int num17 = Math.Sign(player.Center.X - center3.X);
                         if (num17 != 0)
{
                             nPC3.direction = (nPC3.spriteDirection = num17);
                         }
                         if (Main.netMode != 1)
{
                             vec = Vector2.Normalize(player.Center - center3 + player.velocity * 20f);
                             if (vec.HasNaNs())
{
                                 vec = new Vector2(direction, 0f);
                             }
                             Vector2 vector3 = center3 + new Vector2(direction * 30, 12f);
                             for (int m = 0; m < 1; m++)
{
                                 Vector2 spinninpoint = vec * (6f + (float)Main.rand.NextDouble() * 4f);
                                 spinninpoint = spinninpoint.RotatedByRandom(0.5235987901687622);
                                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector3.X, vector3.Y, spinninpoint.X, spinninpoint.Y, 468, 18, 0f, Main.myPlayer);
                             }
                         }
                     }
                 }
                 if (Main.netMode != 1)
                 {
                     vec = Vector2.Normalize(player.Center - center + player.velocity * 20f);
                     if (vec.HasNaNs())
                     {
                         vec = new Vector2(direction, 0f);
                     }
                     Vector2 vector4 = base.Center + new Vector2(direction * 30, 12f);
                     for (int n = 0; n < 1; n++)
                     {
                         Vector2 vector5 = vec * 4f;
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector4.X, vector4.Y, vector5.X, vector5.Y, 464, attackDamage_ForProjectiles, 0f, Main.myPlayer, 0f, 1f);
                     }
                 }
             }
             this.ai[1] += 1f;
             if (this.ai[1] >= (float)(4 + num))
             {
                 this.ai[0] = 0f;
                 this.ai[1] = 0f;
                 this.ai[3] += 1f;
                 velocity = Vector2.Zero;
                 netUpdate = true;
             }
         }
         else if (this.ai[0] == 3f)
         {
             localAI[2] = 11f;
             Vector2 vec2 = Vector2.Normalize(player.Center - center);
             if (vec2.HasNaNs())
             {
                 vec2 = new Vector2(direction, 0f);
             }
             if (this.ai[1] >= 4f && flag2 && (int)(this.ai[1] - 4f) % num2 == 0)
             {
                 if ((int)(this.ai[1] - 4f) / num2 == 2)
                 {
                     List<int> list4 = new List<int>();
                     for (int num18 = 0; num18 < 200; num18++)
                     {
                         if (Main.npc[num18].active && Main.npc[num18].type == 440 && Main.npc[num18].ai[3] == (float)whoAmI)
{
                             list4.Add(num18);
                         }
                     }
                     if (Main.netMode != 1)
                     {
                         foreach (int item4 in list4)
{
                             NPC nPC4 = Main.npc[item4];
                             Vector2 center4 = nPC4.Center;
                             int num19 = Math.Sign(player.Center.X - center4.X);
                             if (num19 != 0)
{
                                 nPC4.direction = (nPC4.spriteDirection = num19);
                             }
                             if (Main.netMode != 1)
{
                                 vec2 = Vector2.Normalize(player.Center - center4 + player.velocity * 20f);
                                 if (vec2.HasNaNs())
{
                                     vec2 = new Vector2(direction, 0f);
                                 }
                                 Vector2 vector6 = center4 + new Vector2(direction * 30, 12f);
                                 for (int num20 = 0; num20 < 1; num20++)
{
                                     Vector2 spinninpoint2 = vec2 * (6f + (float)Main.rand.NextDouble() * 4f);
                                     spinninpoint2 = spinninpoint2.RotatedByRandom(0.5235987901687622);
                                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector6.X, vector6.Y, spinninpoint2.X, spinninpoint2.Y, 468, 18, 0f, Main.myPlayer);
                                 }
                             }
                         }
                     }
                 }
                 int num21 = Math.Sign(player.Center.X - center.X);
                 if (num21 != 0)
                 {
                     direction = (spriteDirection = num21);
                 }
                 if (Main.netMode != 1)
                 {
                     vec2 = Vector2.Normalize(player.Center - center + player.velocity * 20f);
                     if (vec2.HasNaNs())
                     {
                         vec2 = new Vector2(direction, 0f);
                     }
                     Vector2 vector7 = base.Center + new Vector2(direction * 30, 12f);
                     for (int num22 = 0; num22 < 1; num22++)
                     {
                         Vector2 spinninpoint3 = vec2 * (6f + (float)Main.rand.NextDouble() * 4f);
                         spinninpoint3 = spinninpoint3.RotatedByRandom(0.5235987901687622);
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector7.X, vector7.Y, spinninpoint3.X, spinninpoint3.Y, 467, attackDamage_ForProjectiles2, 0f, Main.myPlayer);
                     }
                 }
             }
             this.ai[1] += 1f;
             if (this.ai[1] >= (float)(4 + num2 * num3))
             {
                 this.ai[0] = 0f;
                 this.ai[1] = 0f;
                 this.ai[3] += 1f;
                 velocity = Vector2.Zero;
                 netUpdate = true;
             }
         }
         else if (this.ai[0] == 4f)
         {
             if (flag2)
             {
                 localAI[2] = 12f;
             }
             else
             {
                 localAI[2] = 11f;
             }
             if (this.ai[1] == 20f && flag2 && Main.netMode != 1)
             {
                 List<int> list5 = new List<int>();
                 for (int num23 = 0; num23 < 200; num23++)
                 {
                     if (Main.npc[num23].active && Main.npc[num23].type == 440 && Main.npc[num23].ai[3] == (float)whoAmI)
                     {
                         list5.Add(num23);
                     }
                 }
                 foreach (int item5 in list5)
                 {
                     NPC nPC5 = Main.npc[item5];
                     Vector2 center5 = nPC5.Center;
                     int num24 = Math.Sign(player.Center.X - center5.X);
                     if (num24 != 0)
                     {
                         nPC5.direction = (nPC5.spriteDirection = num24);
                     }
                     if (Main.netMode != 1)
                     {
                         Vector2 vector8 = Vector2.Normalize(player.Center - center5 + player.velocity * 20f);
                         if (vector8.HasNaNs())
{
                             vector8 = new Vector2(direction, 0f);
                         }
                         Vector2 vector9 = center5 + new Vector2(direction * 30, 12f);
                         for (int num25 = 0; num25 < 1; num25++)
{
                             Vector2 spinninpoint4 = vector8 * (6f + (float)Main.rand.NextDouble() * 4f);
                             spinninpoint4 = spinninpoint4.RotatedByRandom(0.5235987901687622);
                             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector9.X, vector9.Y, spinninpoint4.X, spinninpoint4.Y, 468, 18, 0f, Main.myPlayer);
                         }
                     }
                 }
                 if ((int)(this.ai[1] - 20f) % num4 == 0)
                 {
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y - 100f, 0f, 0f, 465, attackDamage_ForProjectiles3, 0f, Main.myPlayer);
                 }
             }
             this.ai[1] += 1f;
             if (this.ai[1] >= (float)(20 + num4))
             {
                 this.ai[0] = 0f;
                 this.ai[1] = 0f;
                 this.ai[3] += 1f;
                 velocity = Vector2.Zero;
                 netUpdate = true;
             }
         }
         else if (this.ai[0] == 5f)
         {
             localAI[2] = 10f;
             if (Vector2.Normalize(player.Center - center).HasNaNs())
             {
                 new Vector2(direction, 0f);
             }
             if (this.ai[1] >= 0f && this.ai[1] < 30f)
             {
                 flag3 = true;
                 flag4 = true;
                 float num26 = (this.ai[1] - 0f) / 30f;
                 alpha = (int)(num26 * 255f);
             }
             else if (this.ai[1] >= 30f && this.ai[1] < 90f)
             {
                 if (this.ai[1] == 30f && Main.netMode != 1 && flag2)
                 {
                     localAI[1] += 1f;
                     Vector2 spinningpoint = new Vector2(180f, 0f);
                     List<int> list6 = new List<int>();
                     for (int num27 = 0; num27 < 200; num27++)
                     {
                         if (Main.npc[num27].active && Main.npc[num27].type == 440 && Main.npc[num27].ai[3] == (float)whoAmI)
{
                             list6.Add(num27);
                         }
                     }
                     int num28 = 6 - list6.Count;
                     if (num28 > 2)
                     {
                         num28 = 2;
                     }
                     int num29 = list6.Count + num28 + 1;
                     float[] array = new float[num29];
                     for (int num30 = 0; num30 < array.Length; num30++)
                     {
                         array[num30] = Vector2.Distance(base.Center + spinningpoint.RotatedBy((float)num30 * ((float)Math.PI * 2f) / (float)num29 - (float)Math.PI / 2f), player.Center);
                     }
                     int num31 = 0;
                     for (int num32 = 1; num32 < array.Length; num32++)
                     {
                         if (array[num31] > array[num32])
{
                             num31 = num32;
                         }
                     }
                     num31 = ((num31 >= num29 / 2) ? (num31 - num29 / 2) : (num31 + num29 / 2));
                     int num33 = num28;
                     for (int num34 = 0; num34 < array.Length; num34++)
                     {
                         if (num31 != num34)
{
                             Vector2 center6 = base.Center + spinningpoint.RotatedBy((float)num34 * ((float)Math.PI * 2f) / (float)num29 - (float)Math.PI / 2f);
                             if (num33-- > 0)
{
                                 int num35 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)center6.X, (int)center6.Y + height / 2, 440, whoAmI);
                                 Main.npc[num35].ai[3] = whoAmI;
                                 Main.npc[num35].netUpdate = true;
                                 Main.npc[num35].localAI[1] = localAI[1];
                             }
                             else
{
                                 int num36 = list6[-num33 - 1];
                                 Main.npc[num36].Center = center6;
                                 NetMessage.SendData(23, -1, -1, null, num36);
                             }
                         }
                     }
                     this.ai[2] = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 490, 0, 0f, Main.myPlayer, 0f, whoAmI);
                     base.Center += spinningpoint.RotatedBy((float)num31 * ((float)Math.PI * 2f) / (float)num29 - (float)Math.PI / 2f);
                     netUpdate = true;
                     list6.Clear();
                 }
                 flag3 = true;
                 flag4 = true;
                 alpha = 255;
                 if (flag2)
                 {
                     Vector2 vector10 = Main.projectile[(int)this.ai[2]].Center;
                     vector10 -= base.Center;
                     if (vector10 == Vector2.Zero)
                     {
                         vector10 = -Vector2.UnitY;
                     }
                     vector10.Normalize();
                     if (Math.Abs(vector10.Y) < 0.77f)
                     {
                         localAI[2] = 11f;
                     }
                     else if (vector10.Y < 0f)
                     {
                         localAI[2] = 12f;
                     }
                     else
                     {
                         localAI[2] = 10f;
                     }
                     int num37 = Math.Sign(vector10.X);
                     if (num37 != 0)
                     {
                         direction = (spriteDirection = num37);
                     }
                 }
                 else
                 {
                     Vector2 vector11 = Main.projectile[(int)Main.npc[(int)this.ai[3]].ai[2]].Center;
                     vector11 -= base.Center;
                     if (vector11 == Vector2.Zero)
                     {
                         vector11 = -Vector2.UnitY;
                     }
                     vector11.Normalize();
                     if (Math.Abs(vector11.Y) < 0.77f)
                     {
                         localAI[2] = 11f;
                     }
                     else if (vector11.Y < 0f)
                     {
                         localAI[2] = 12f;
                     }
                     else
                     {
                         localAI[2] = 10f;
                     }
                     int num38 = Math.Sign(vector11.X);
                     if (num38 != 0)
                     {
                         direction = (spriteDirection = num38);
                     }
                 }
             }
             else if (this.ai[1] >= 90f && this.ai[1] < 120f)
             {
                 flag3 = true;
                 flag4 = true;
                 float num39 = (this.ai[1] - 90f) / 30f;
                 alpha = 255 - (int)(num39 * 255f);
             }
             else if (this.ai[1] >= 120f && this.ai[1] < 420f)
             {
                 flag4 = true;
                 alpha = 0;
                 if (flag2)
                 {
                     Vector2 vector12 = Main.projectile[(int)this.ai[2]].Center;
                     vector12 -= base.Center;
                     if (vector12 == Vector2.Zero)
                     {
                         vector12 = -Vector2.UnitY;
                     }
                     vector12.Normalize();
                     if (Math.Abs(vector12.Y) < 0.77f)
                     {
                         localAI[2] = 11f;
                     }
                     else if (vector12.Y < 0f)
                     {
                         localAI[2] = 12f;
                     }
                     else
                     {
                         localAI[2] = 10f;
                     }
                     int num40 = Math.Sign(vector12.X);
                     if (num40 != 0)
                     {
                         direction = (spriteDirection = num40);
                     }
                 }
                 else
                 {
                     Vector2 vector13 = Main.projectile[(int)Main.npc[(int)this.ai[3]].ai[2]].Center;
                     vector13 -= base.Center;
                     if (vector13 == Vector2.Zero)
                     {
                         vector13 = -Vector2.UnitY;
                     }
                     vector13.Normalize();
                     if (Math.Abs(vector13.Y) < 0.77f)
                     {
                         localAI[2] = 11f;
                     }
                     else if (vector13.Y < 0f)
                     {
                         localAI[2] = 12f;
                     }
                     else
                     {
                         localAI[2] = 10f;
                     }
                     int num41 = Math.Sign(vector13.X);
                     if (num41 != 0)
                     {
                         direction = (spriteDirection = num41);
                     }
                 }
             }
             this.ai[1] += 1f;
             if (this.ai[1] >= 420f)
             {
                 flag4 = true;
                 this.ai[0] = 0f;
                 this.ai[1] = 0f;
                 this.ai[3] += 1f;
                 velocity = Vector2.Zero;
                 netUpdate = true;
             }
         }
         else if (this.ai[0] == 6f)
         {
             localAI[2] = 13f;
             this.ai[1] += 1f;
             if (this.ai[1] >= 120f)
             {
                 this.ai[0] = 0f;
                 this.ai[1] = 0f;
                 this.ai[3] += 1f;
                 velocity = Vector2.Zero;
                 netUpdate = true;
             }
         }
         else if (this.ai[0] == 7f)
         {
             localAI[2] = 11f;
             Vector2 vec3 = Vector2.Normalize(player.Center - center);
             if (vec3.HasNaNs())
             {
                 vec3 = new Vector2(direction, 0f);
             }
             if (this.ai[1] >= 4f && flag2 && (int)(this.ai[1] - 4f) % num5 == 0)
             {
                 if ((int)(this.ai[1] - 4f) / num5 == 2)
                 {
                     List<int> list7 = new List<int>();
                     for (int num42 = 0; num42 < 200; num42++)
                     {
                         if (Main.npc[num42].active && Main.npc[num42].type == 440 && Main.npc[num42].ai[3] == (float)whoAmI)
{
                             list7.Add(num42);
                         }
                     }
                     foreach (int item6 in list7)
                     {
                         NPC nPC6 = Main.npc[item6];
                         Vector2 center7 = nPC6.Center;
                         int num43 = Math.Sign(player.Center.X - center7.X);
                         if (num43 != 0)
{
                             nPC6.direction = (nPC6.spriteDirection = num43);
                         }
                         if (Main.netMode != 1)
{
                             vec3 = Vector2.Normalize(player.Center - center7 + player.velocity * 20f);
                             if (vec3.HasNaNs())
{
                                 vec3 = new Vector2(direction, 0f);
                             }
                             Vector2 vector14 = center7 + new Vector2(direction * 30, 12f);
                             for (int num44 = 0; (float)num44 < 5f; num44++)
{
                                 Vector2 spinninpoint5 = vec3 * (6f + (float)Main.rand.NextDouble() * 4f);
                                 spinninpoint5 = spinninpoint5.RotatedByRandom(1.2566370964050293);
                                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector14.X, vector14.Y, spinninpoint5.X, spinninpoint5.Y, 468, 18, 0f, Main.myPlayer);
                             }
                         }
                     }
                 }
                 int num45 = Math.Sign(player.Center.X - center.X);
                 if (num45 != 0)
                 {
                     direction = (spriteDirection = num45);
                 }
                 if (Main.netMode != 1)
                 {
                     vec3 = Vector2.Normalize(player.Center - center + player.velocity * 20f);
                     if (vec3.HasNaNs())
                     {
                         vec3 = new Vector2(direction, 0f);
                     }
                     Vector2 vector15 = base.Center + new Vector2(direction * 30, 12f);
                     float num46 = 8f;
                     float num47 = (float)Math.PI * 2f / 25f;
                     for (int num48 = 0; (float)num48 < 5f; num48++)
                     {
                         Vector2 spinningpoint2 = vec3 * num46;
                         spinningpoint2 = spinningpoint2.RotatedBy(num47 * (float)num48 - ((float)Math.PI * 2f / 5f - num47) / 2f);
                         float ai = (Main.rand.NextFloat() - 0.5f) * 0.3f * ((float)Math.PI * 2f) / 60f;
                         int num49 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)vector15.X, (int)vector15.Y + 7, 522, 0, 0f, ai, spinningpoint2.X, spinningpoint2.Y);
                         Main.npc[num49].velocity = spinningpoint2;
                         Main.npc[num49].netUpdate = true;
                     }
                 }
             }
             this.ai[1] += 1f;
             if (this.ai[1] >= (float)(4 + num5 * num6))
             {
                 this.ai[0] = 0f;
                 this.ai[1] = 0f;
                 this.ai[3] += 1f;
                 velocity = Vector2.Zero;
                 netUpdate = true;
             }
         }
         else if (this.ai[0] == 8f)
         {
             localAI[2] = 13f;
             if (this.ai[1] >= 4f && flag2 && (int)(this.ai[1] - 4f) % num7 == 0)
             {
                 List<int> list8 = new List<int>();
                 for (int num50 = 0; num50 < 200; num50++)
                 {
                     if (Main.npc[num50].active && Main.npc[num50].type == 440 && Main.npc[num50].ai[3] == (float)whoAmI)
                     {
                         list8.Add(num50);
                     }
                 }
                 int num51 = list8.Count + 1;
                 if (num51 > 3)
                 {
                     num51 = 3;
                 }
                 int num52 = Math.Sign(player.Center.X - center.X);
                 if (num52 != 0)
                 {
                     direction = (spriteDirection = num52);
                 }
                 if (Main.netMode != 1)
                 {
                     for (int num53 = 0; num53 < num51; num53++)
                     {
                         Point point = base.Center.ToTileCoordinates();
                         Point point2 = Main.player[target].Center.ToTileCoordinates();
                         Vector2 vector16 = Main.player[target].Center - base.Center;
                         int num54 = 20;
                         int num55 = 3;
                         int num56 = 7;
                         int num57 = 2;
                         int num58 = 0;
                         bool flag6 = false;
                         if (vector16.Length() > 2000f)
{
                             flag6 = true;
                         }
                         while (!flag6 && num58 < 100)
{
                             num58++;
                             int num59 = Main.rand.Next(point2.X - num54, point2.X + num54 + 1);
                             int num60 = Main.rand.Next(point2.Y - num54, point2.Y + num54 + 1);
                             if ((num60 < point2.Y - num56 || num60 > point2.Y + num56 || num59 < point2.X - num56 || num59 > point2.X + num56) && (num60 < point.Y - num55 || num60 > point.Y + num55 || num59 < point.X - num55 || num59 > point.X + num55) && !Main.tile[num59, num60].nactive())
{
                                 bool flag7 = true;
                                 if (flag7 && Collision.SolidTiles(num59 - num57, num59 + num57, num60 - num57, num60 + num57))
{
                                     flag7 = false;
                                 }
                                 if (flag7)
{
                                     NewNPC(GetSpawnSourceForNPCFromNPCAI(), num59 * 16 + 8, num60 * 16 + 8, 523, 0, whoAmI);
                                     flag6 = true;
                                     break;
                                 }
                             }
                         }
                     }
                 }
             }
             this.ai[1] += 1f;
             if (this.ai[1] >= (float)(4 + num7 * num8))
             {
                 this.ai[0] = 0f;
                 this.ai[1] = 0f;
                 this.ai[3] += 1f;
                 velocity = Vector2.Zero;
                 netUpdate = true;
             }
         }
         if (!flag2)
         {
             this.ai[3] = num11;
         }
         dontTakeDamage = flag3;
         chaseable = !flag4;
     }
References Entity.active, ai, alpha, Entity.Center, chaseable, CountNPCS(), Player.dead, defDefense, defense, Entity.direction, dontTakeDamage, Main.expertMode, GetAttackDamage_ForProjectiles(), Main.getGoodWorld, GetSpawnSource_ForProjectile(), GetSpawnSourceForNPCFromNPCAI(), Entity.height, HitEffect(), justHit, life, lifeMax, localAI, Main.myPlayer, Tile.nactive(), Main.netMode, netUpdate, NewNPC(), Projectile.NewProjectile(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Main.npc, Main.player, SoundEngine.PlaySound(), Entity.position, Main.projectile, Main.rand, rotation, NetMessage.SendData(), Collision.SolidTiles(), spriteDirection, target, TargetClosest(), Main.tile, type, Entity.velocity, and Entity.whoAmI.
Referenced by AI().