Terraria: NPC.CanBeChasedBy
CanBeChasedBy()
bool NPC.CanBeChasedBy (object attacker = null, bool ignoreDontTakeDamage = false) inline
Referenced by Projectile.AI(), Projectile.AI_001(), AI_007_TownEntities(), Projectile.AI_009_MagicMissiles(), Projectile.AI_015_Flails(), Projectile.AI_015_Flails_Old(), Projectile.AI_016(), Projectile.AI_026(), Projectile.AI_047_MagnetSphere_TryAttacking(), Projectile.AI_062(), Projectile.AI_067_TigerSpecialAttack(), Projectile.AI_099_1(), Projectile.AI_099_2(), Projectile.AI_100_Medusa(), Projectile.AI_120_StardustGuardian(), Projectile.AI_120_StardustGuardian_FindTarget(), Projectile.AI_121_StardustDragon(), Projectile.AI_130_FlameBurstTower_FindTarget(), Projectile.AI_134_Ballista_FindTarget(), Projectile.AI_137_LightningAura(), Projectile.AI_138_ExplosiveTrap(), Projectile.AI_147_Celeb2Rocket(), Projectile.AI_156_Think(), Projectile.AI_156_TryAttackingNPCs(), Projectile.AI_169_Smolstars(), Projectile.AI_171_HallowBossRainbowStreak(), Projectile.AI_176_EdgyLightning(), Projectile.AI_177_IceWhipSlicer(), Player.BloodButcherer_TryButchering(), Mount.CastSuperCartLaser(), Projectile.Damage(), Projectile.FindTargetWithinRange(), Projectile.FindTargetWithLineOfSight(), Player.GetSparkleGuitarTarget(), Player.GetZenithTarget(), Projectile.ghostHurt(), Projectile.HandleMovement(), Projectile.Kill(), Projectile.Minion_FindTargetInRange(), Player.MinionNPCTargetAim(), NPCUtils.SearchFilters.NonBeeNPCs(), Player.SpawnHallucination(), Projectile.SummonMonkGhast(), Player.TentacleSpike_TrySpiking(), Mount.UpdateEffects(), Player.UpdateMinionTarget(), and Player.VolatileGelatin().