Terraria: NPC.AI_007_TownEntities
AI_007_TownEntities()
void NPC.AI_007_TownEntities () inline private
     {
         ShimmeredTownNPCs[type] = IsShimmerVariant;
         if (type == 441 && GivenName == "Andrew")
         {
             defDefense = 200;
         }
         int num = 300;
         if (type == 638 || type == 656 || NPCID.Sets.IsTownSlime[type])
         {
             num = 0;
         }
         bool flag = Main.raining;
         if (!Main.dayTime)
         {
             flag = true;
         }
         if (Main.eclipse)
         {
             flag = true;
         }
         if (Main.slimeRain)
         {
             flag = true;
         }
         float num2 = 1f;
         if (Main.masterMode)
         {
             defense = (dryadWard ? (defDefense + 14) : defDefense);
         }
         else if (Main.expertMode)
         {
             defense = (dryadWard ? (defDefense + 10) : defDefense);
         }
         else
         {
             defense = (dryadWard ? (defDefense + 6) : defDefense);
         }
         if (isLikeATownNPC)
         {
             if (combatBookWasUsed)
             {
                 num2 += 0.2f;
                 defense += 6;
             }
             if (combatBookVolumeTwoWasUsed)
             {
                 num2 += 0.2f;
                 defense += 6;
             }
             if (downedBoss1)
             {
                 num2 += 0.1f;
                 defense += 3;
             }
             if (downedBoss2)
             {
                 num2 += 0.1f;
                 defense += 3;
             }
             if (downedBoss3)
             {
                 num2 += 0.1f;
                 defense += 3;
             }
             if (downedQueenBee)
             {
                 num2 += 0.1f;
                 defense += 3;
             }
             if (Main.hardMode)
             {
                 num2 += 0.4f;
                 defense += 12;
             }
             if (downedQueenSlime)
             {
                 num2 += 0.15f;
                 defense += 6;
             }
             if (downedMechBoss1)
             {
                 num2 += 0.15f;
                 defense += 6;
             }
             if (downedMechBoss2)
             {
                 num2 += 0.15f;
                 defense += 6;
             }
             if (downedMechBoss3)
             {
                 num2 += 0.15f;
                 defense += 6;
             }
             if (downedPlantBoss)
             {
                 num2 += 0.15f;
                 defense += 8;
             }
             if (downedEmpressOfLight)
             {
                 num2 += 0.15f;
                 defense += 8;
             }
             if (downedGolemBoss)
             {
                 num2 += 0.15f;
                 defense += 8;
             }
             if (downedAncientCultist)
             {
                 num2 += 0.15f;
                 defense += 8;
             }
         }
         if (type == 142 && Main.netMode != 1 && !Main.xMas)
         {
             StrikeNPCNoInteraction(9999, 0f, 0);
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(28, -1, -1, null, whoAmI, 9999f);
             }
         }
         if ((type == 148 || type == 149) && localAI[0] == 0f)
         {
             localAI[0] = Main.rand.Next(1, 5);
         }
         if (type == 124)
         {
             int num3 = lazyNPCOwnedProjectileSearchArray[whoAmI];
             bool flag2 = false;
             if (Main.projectile.IndexInRange(num3))
             {
                 Projectile projectile = Main.projectile[num3];
                 if (projectile.active && projectile.type == 582 && projectile.ai[1] == (float)whoAmI)
                 {
                     flag2 = true;
                 }
             }
             localAI[0] = flag2.ToInt();
         }
         if ((type == 362 || type == 364 || type == 602 || type == 608) && Main.netMode != 1 && (velocity.Y > 4f || velocity.Y < -4f || wet))
         {
             int num4 = direction;
             Transform(type + 1);
             TargetClosest();
             direction = num4;
             netUpdate = true;
             return;
         }
         switch (type)
         {
         case 588:
             savedGolfer = true;
             break;
         case 441:
             savedTaxCollector = true;
             break;
         case 107:
             savedGoblin = true;
             break;
         case 108:
             savedWizard = true;
             break;
         case 124:
             savedMech = true;
             break;
         case 353:
             savedStylist = true;
             break;
         case 369:
             savedAngler = true;
             break;
         case 550:
             savedBartender = true;
             break;
         }
         dontTakeDamage = false;
         if (ai[0] == 25f)
         {
             dontTakeDamage = true;
             if (ai[1] == 0f)
             {
                 velocity.X = 0f;
             }
             shimmerWet = false;
             wet = false;
             lavaWet = false;
             honeyWet = false;
             if (ai[1] == 0f && Main.netMode == 1)
             {
                 return;
             }
             if (ai[1] == 0f && ai[2] < 1f)
             {
                 AI_007_TownEntities_Shimmer_TeleportToLandingSpot();
             }
             if (ai[2] > 0f)
             {
                 ai[2] -= 1f;
                 if (ai[2] <= 0f)
                 {
                     ai[1] = 1f;
                 }
                 return;
             }
             ai[1] += 1f;
             if (ai[1] >= 30f)
             {
                 if (!Collision.WetCollision(position, width, height))
                 {
                     shimmerTransparency = MathHelper.Clamp(shimmerTransparency - 1f / 60f, 0f, 1f);
                 }
                 else
                 {
                     ai[1] = 30f;
                 }
                 velocity = new Vector2(0f, -4f * shimmerTransparency);
             }
             Rectangle hitbox = base.Hitbox;
             hitbox.Y += 20;
             hitbox.Height -= 20;
             float num5 = Main.rand.NextFloatDirection();
             Lighting.AddLight(base.Center, Main.hslToRgb((float)Main.timeForVisualEffects / 360f % 1f, 0.6f, 0.65f).ToVector3() * Utils.Remap(ai[1], 30f, 90f, 0f, 0.7f));
             if (Main.rand.NextFloat() > Utils.Remap(ai[1], 30f, 60f, 1f, 0.5f))
             {
                 Dust.NewDustPerfect(Main.rand.NextVector2FromRectangle(hitbox) + Main.rand.NextVector2Circular(8f, 0f) + new Vector2(0f, 4f), 309, new Vector2(0f, -2f).RotatedBy(num5 * ((float)Math.PI * 2f) * 0.11f), 0, default(Color), 1.7f - Math.Abs(num5) * 1.3f);
             }
             if (ai[1] > 60f && Main.rand.Next(15) == 0)
             {
                 for (int i = 0; i < 3; i++)
                 {
                     Vector2 vector = Main.rand.NextVector2FromRectangle(base.Hitbox);
                     ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.ShimmerBlock, new ParticleOrchestraSettings
                     {
                         PositionInWorld = vector,
                         MovementVector = DirectionTo(vector).RotatedBy((float)Math.PI * 9f / 20f * (float)(Main.rand.Next(2) * 2 - 1)) * Main.rand.NextFloat()
                     });
                 }
             }
             TargetClosest();
             NPCAimedTarget targetData = GetTargetData();
             if (ai[1] >= 75f && shimmerTransparency <= 0f && Main.netMode != 1)
             {
                 ai[0] = 0f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] = 0f;
                 Math.Sign(targetData.Center.X - base.Center.X);
                 velocity = new Vector2(0f, -4f);
                 localAI[0] = 0f;
                 localAI[1] = 0f;
                 localAI[2] = 0f;
                 localAI[3] = 0f;
                 netUpdate = true;
                 townNpcVariationIndex = ((townNpcVariationIndex != 1) ? 1 : 0);
                 NetMessage.SendData(56, -1, -1, null, whoAmI);
                 Teleport(position, 12);
                 ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.ShimmerTownNPC, new ParticleOrchestraSettings
                 {
                     PositionInWorld = base.Center
                 });
             }
             return;
         }
         if (type >= 0 && type < NPCID.Count && NPCID.Sets.TownCritter[type] && target == 255)
         {
             TargetClosest();
             if (position.X < Main.player[target].position.X)
             {
                 direction = 1;
                 spriteDirection = direction;
             }
             if (position.X > Main.player[target].position.X)
             {
                 direction = -1;
                 spriteDirection = direction;
             }
             if (homeTileX == -1)
             {
                 UpdateHomeTileState(homeless, (int)((position.X + (float)(width / 2)) / 16f), homeTileY);
             }
         }
         else if (homeTileX == -1 && homeTileY == -1 && velocity.Y == 0f && !shimmering)
         {
             UpdateHomeTileState(homeless, (int)base.Center.X / 16, (int)(position.Y + (float)height + 4f) / 16);
         }
         bool flag3 = false;
         int num6 = (int)(position.X + (float)(width / 2)) / 16;
         int num7 = (int)(position.Y + (float)height + 1f) / 16;
         AI_007_FindGoodRestingSpot(num6, num7, out var floorX, out var floorY);
         if (type == 441)
         {
             taxCollector = true;
         }
         directionY = -1;
         if (direction == 0)
         {
             direction = 1;
         }
         if (ai[0] != 24f)
         {
             for (int j = 0; j < 255; j++)
             {
                 if (Main.player[j].active && Main.player[j].talkNPC == whoAmI)
                 {
                     flag3 = true;
                     if (ai[0] != 0f)
                     {
                         netUpdate = true;
                     }
                     ai[0] = 0f;
                     ai[1] = 300f;
                     localAI[3] = 100f;
                     if (Main.player[j].position.X + (float)(Main.player[j].width / 2) < position.X + (float)(width / 2))
                     {
                         direction = -1;
                     }
                     else
                     {
                         direction = 1;
                     }
                 }
             }
         }
         if (ai[3] == 1f)
         {
             life = -1;
             HitEffect();
             active = false;
             netUpdate = true;
             if (type == 37)
             {
                 SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             }
             return;
         }
         if (type == 37 && Main.netMode != 1)
         {
             UpdateHomeTileState(homeless: false, Main.dungeonX, Main.dungeonY);
             if (downedBoss3)
             {
                 ai[3] = 1f;
                 netUpdate = true;
             }
         }
         if (type == 368)
         {
             homeless = true;
             if (!Main.dayTime)
             {
                 if (!shimmering)
                 {
                     UpdateHomeTileState(homeless, (int)(base.Center.X / 16f), (int)(position.Y + (float)height + 2f) / 16);
                 }
                 if (!flag3 && ai[0] == 0f)
                 {
                     ai[0] = 1f;
                     ai[1] = 200f;
                 }
                 flag = false;
             }
         }
         if (type == 369 && homeless && wet)
         {
             if (base.Center.X / 16f < 380f || base.Center.X / 16f > (float)(Main.maxTilesX - 380))
             {
                 UpdateHomeTileState(homeless, Main.spawnTileX, Main.spawnTileY);
                 ai[0] = 1f;
                 ai[1] = 200f;
             }
             if (position.X / 16f < 300f)
             {
                 direction = 1;
             }
             else if (position.X / 16f > (float)(Main.maxTilesX - 300))
             {
                 direction = -1;
             }
         }
         if (!WorldGen.InWorld(num6, num7) || Main.tile[num6, num7] == null)
         {
             return;
         }
         if (!homeless && Main.netMode != 1 && townNPC && (flag || (type == 37 && Main.tileDungeon[Main.tile[num6, num7].type])) && !AI_007_TownEntities_IsInAGoodRestingSpot(num6, num7, floorX, floorY))
         {
             bool flag4 = true;
             for (int k = 0; k < 2; k++)
             {
                 if (!flag4)
                 {
                     break;
                 }
                 Rectangle rectangle = new Rectangle((int)(position.X + (float)(width / 2) - (float)(sWidth / 2) - (float)safeRangeX), (int)(position.Y + (float)(height / 2) - (float)(sHeight / 2) - (float)safeRangeY), sWidth + safeRangeX * 2, sHeight + safeRangeY * 2);
                 if (k == 1)
                 {
                     rectangle = new Rectangle(floorX * 16 + 8 - sWidth / 2 - safeRangeX, floorY * 16 + 8 - sHeight / 2 - safeRangeY, sWidth + safeRangeX * 2, sHeight + safeRangeY * 2);
                 }
                 for (int l = 0; l < 255; l++)
                 {
                     if (Main.player[l].active && new Rectangle((int)Main.player[l].position.X, (int)Main.player[l].position.Y, Main.player[l].width, Main.player[l].height).Intersects(rectangle))
                     {
                         flag4 = false;
                         break;
                     }
                 }
             }
             if (flag4)
             {
                 AI_007_TownEntities_TeleportToHome(floorX, floorY);
             }
         }
         bool flag5 = type == 300 || type == 447 || type == 610;
         bool flag6 = type == 616 || type == 617 || type == 625;
         bool flag7 = type == 361 || type == 445 || type == 687;
         bool flag8 = NPCID.Sets.IsTownSlime[type];
         _ = NPCID.Sets.IsTownPet[type];
         bool flag9 = flag6 || flag7;
         bool flag10 = flag6 || flag7;
         bool flag11 = flag8;
         bool flag12 = flag8;
         float num8 = 200f;
         if (NPCID.Sets.DangerDetectRange[type] != -1)
         {
             num8 = NPCID.Sets.DangerDetectRange[type];
         }
         bool flag13 = false;
         bool flag14 = false;
         float num9 = -1f;
         float num10 = -1f;
         int num11 = 0;
         int num12 = -1;
         int num13 = -1;
         if (!flag6 && Main.netMode != 1 && !flag3)
         {
             for (int m = 0; m < 200; m++)
             {
                 if (!Main.npc[m].active || Main.npc[m].friendly || Main.npc[m].damage <= 0 || !(Main.npc[m].Distance(base.Center) < num8) || (type == 453 && NPCID.Sets.Skeletons[Main.npc[m].type]) || (!Main.npc[m].noTileCollide && !Collision.CanHit(base.Center, 0, 0, Main.npc[m].Center, 0, 0)))
                 {
                     continue;
                 }
                 bool flag15 = Main.npc[m].CanBeChasedBy(this);
                 flag13 = true;
                 float num14 = Main.npc[m].Center.X - base.Center.X;
                 if (type == 614)
                 {
                     if (num14 < 0f && (num9 == -1f || num14 > num9))
                     {
                         num10 = num14;
                         num13 = m;
                     }
                     if (num14 > 0f && (num10 == -1f || num14 < num10))
                     {
                         num9 = num14;
                         num12 = m;
                     }
                     continue;
                 }
                 if (num14 < 0f && (num9 == -1f || num14 > num9))
                 {
                     num9 = num14;
                     if (flag15)
                     {
                         num12 = m;
                     }
                 }
                 if (num14 > 0f && (num10 == -1f || num14 < num10))
                 {
                     num10 = num14;
                     if (flag15)
                     {
                         num13 = m;
                     }
                 }
             }
             if (flag13)
             {
                 num11 = ((num9 == -1f) ? 1 : ((num10 != -1f) ? (num10 < 0f - num9).ToDirectionInt() : (-1)));
                 float num15 = 0f;
                 if (num9 != -1f)
                 {
                     num15 = 0f - num9;
                 }
                 if (num15 == 0f || (num10 < num15 && num10 > 0f))
                 {
                     num15 = num10;
                 }
                 if (ai[0] == 8f)
                 {
                     if (direction == -num11)
                     {
                         ai[0] = 1f;
                         ai[1] = 300 + Main.rand.Next(300);
                         ai[2] = 0f;
                         localAI[3] = 0f;
                         netUpdate = true;
                     }
                 }
                 else if (ai[0] != 10f && ai[0] != 12f && ai[0] != 13f && ai[0] != 14f && ai[0] != 15f)
                 {
                     if (NPCID.Sets.PrettySafe[type] != -1 && (float)NPCID.Sets.PrettySafe[type] < num15)
                     {
                         flag13 = false;
                         flag14 = NPCID.Sets.AttackType[type] > -1;
                     }
                     else if (ai[0] != 1f)
                     {
                         int tileX = (int)((position.X + (float)(width / 2) + (float)(15 * direction)) / 16f);
                         int tileY = (int)((position.Y + (float)height - 16f) / 16f);
                         bool currentlyDrowning = wet && !flag9;
                         AI_007_TownEntities_GetWalkPrediction(num6, floorX, flag9, currentlyDrowning, tileX, tileY, out var _, out var avoidFalling);
                         if (!avoidFalling)
{
                             if (ai[0] == 3f || ai[0] == 4f || ai[0] == 16f || ai[0] == 17f)
{
                                 NPC nPC = Main.npc[(int)ai[2]];
                                 if (nPC.active)
{
                                     nPC.ai[0] = 1f;
                                     nPC.ai[1] = 120 + Main.rand.Next(120);
                                     nPC.ai[2] = 0f;
                                     nPC.localAI[3] = 0f;
                                     nPC.direction = -num11;
                                     nPC.netUpdate = true;
                                 }
                             }
                             ai[0] = 1f;
                             ai[1] = 120 + Main.rand.Next(120);
                             ai[2] = 0f;
                             localAI[3] = 0f;
                             direction = -num11;
                             netUpdate = true;
                         }
                     }
                     else if (ai[0] == 1f && direction != -num11)
                     {
                         direction = -num11;
                         netUpdate = true;
                     }
                 }
             }
         }
         if (ai[0] == 0f)
         {
             if (localAI[3] > 0f)
             {
                 localAI[3] -= 1f;
             }
             int num16 = 120;
             if (type == 638)
             {
                 num16 = 60;
             }
             if ((flag7 || flag8) && wet)
             {
                 ai[0] = 1f;
                 ai[1] = 200 + Main.rand.Next(500, 700);
                 ai[2] = 0f;
                 localAI[3] = 0f;
                 netUpdate = true;
             }
             else if (flag && !flag3 && !NPCID.Sets.TownCritter[type])
             {
                 if (Main.netMode != 1)
                 {
                     if (num6 == floorX && num7 == floorY)
                     {
                         if (velocity.X != 0f)
{
                             netUpdate = true;
                         }
                         if (velocity.X > 0.1f)
{
                             velocity.X -= 0.1f;
                         }
                         else if (velocity.X < -0.1f)
{
                             velocity.X += 0.1f;
                         }
                         else
{
                             velocity.X = 0f;
                             AI_007_TryForcingSitting(floorX, floorY);
                         }
                         if (NPCID.Sets.IsTownPet[type])
{
                             AI_007_AttemptToPlayIdleAnimationsForPets(num16 * 4);
                         }
                     }
                     else
                     {
                         if (num6 > floorX)
{
                             direction = -1;
                         }
                         else
{
                             direction = 1;
                         }
                         ai[0] = 1f;
                         ai[1] = 200 + Main.rand.Next(200);
                         ai[2] = 0f;
                         localAI[3] = 0f;
                         netUpdate = true;
                     }
                 }
             }
             else
             {
                 if (flag5)
                 {
                     velocity.X *= 0.5f;
                 }
                 if (velocity.X > 0.1f)
                 {
                     velocity.X -= 0.1f;
                 }
                 else if (velocity.X < -0.1f)
                 {
                     velocity.X += 0.1f;
                 }
                 else
                 {
                     velocity.X = 0f;
                 }
                 if (Main.netMode != 1)
                 {
                     if (!flag3 && NPCID.Sets.IsTownPet[type] && ai[1] >= 100f && ai[1] <= 150f)
                     {
                         AI_007_AttemptToPlayIdleAnimationsForPets(num16);
                     }
                     if (ai[1] > 0f)
                     {
                         ai[1] -= 1f;
                     }
                     bool flag16 = true;
                     int tileX2 = (int)((position.X + (float)(width / 2) + (float)(15 * direction)) / 16f);
                     int tileY2 = (int)((position.Y + (float)height - 16f) / 16f);
                     bool currentlyDrowning2 = wet && !flag9;
                     AI_007_TownEntities_GetWalkPrediction(num6, floorX, flag9, currentlyDrowning2, tileX2, tileY2, out var _, out var avoidFalling2);
                     if (wet && !flag9)
                     {
                         bool currentlyDrowning3 = Collision.DrownCollision(position, width, height, 1f, includeSlopes: true);
                         if (AI_007_TownEntities_CheckIfWillDrown(currentlyDrowning3))
{
                             ai[0] = 1f;
                             ai[1] = 200 + Main.rand.Next(300);
                             ai[2] = 0f;
                             if (NPCID.Sets.TownCritter[type])
{
                                 ai[1] += Main.rand.Next(200, 400);
                             }
                             localAI[3] = 0f;
                             netUpdate = true;
                         }
                     }
                     if (avoidFalling2)
                     {
                         flag16 = false;
                     }
                     if (ai[1] <= 0f)
                     {
                         if (flag16 && !avoidFalling2)
{
                             ai[0] = 1f;
                             ai[1] = 200 + Main.rand.Next(300);
                             ai[2] = 0f;
                             if (NPCID.Sets.TownCritter[type])
{
                                 ai[1] += Main.rand.Next(200, 400);
                             }
                             localAI[3] = 0f;
                             netUpdate = true;
                         }
                         else
{
                             direction *= -1;
                             ai[1] = 60 + Main.rand.Next(120);
                             netUpdate = true;
                         }
                     }
                 }
             }
             if (Main.netMode != 1 && (!flag || AI_007_TownEntities_IsInAGoodRestingSpot(num6, num7, floorX, floorY)))
             {
                 if (num6 < floorX - 25 || num6 > floorX + 25)
                 {
                     if (localAI[3] == 0f)
                     {
                         if (num6 < floorX - 50 && direction == -1)
{
                             direction = 1;
                             netUpdate = true;
                         }
                         else if (num6 > floorX + 50 && direction == 1)
{
                             direction = -1;
                             netUpdate = true;
                         }
                     }
                 }
                 else if (Main.rand.Next(80) == 0 && localAI[3] == 0f)
                 {
                     localAI[3] = 200f;
                     direction *= -1;
                     netUpdate = true;
                 }
             }
         }
         else if (ai[0] == 1f)
         {
             if (Main.netMode != 1 && flag && AI_007_TownEntities_IsInAGoodRestingSpot(num6, num7, floorX, floorY) && !NPCID.Sets.TownCritter[type])
             {
                 ai[0] = 0f;
                 ai[1] = 200 + Main.rand.Next(200);
                 localAI[3] = 60f;
                 netUpdate = true;
             }
             else
             {
                 bool flag17 = !flag9 && Collision.DrownCollision(position, width, height, 1f, includeSlopes: true);
                 if (!flag17)
                 {
                     if (Main.netMode != 1 && !homeless && !Main.tileDungeon[Main.tile[num6, num7].type] && (num6 < floorX - 35 || num6 > floorX + 35))
                     {
                         if (position.X < (float)(floorX * 16) && direction == -1)
{
                             ai[1] -= 5f;
                         }
                         else if (position.X > (float)(floorX * 16) && direction == 1)
{
                             ai[1] -= 5f;
                         }
                     }
                     ai[1] -= 1f;
                 }
                 if (ai[1] <= 0f)
                 {
                     ai[0] = 0f;
                     ai[1] = 300 + Main.rand.Next(300);
                     ai[2] = 0f;
                     if (NPCID.Sets.TownCritter[type])
                     {
                         ai[1] -= Main.rand.Next(100);
                     }
                     else
                     {
                         ai[1] += Main.rand.Next(900);
                     }
                     localAI[3] = 60f;
                     netUpdate = true;
                 }
                 if (closeDoor && ((position.X + (float)(width / 2)) / 16f > (float)(doorX + 2) || (position.X + (float)(width / 2)) / 16f < (float)(doorX - 2)))
                 {
                     Tile tileSafely = Framing.GetTileSafely(doorX, doorY);
                     if (tileSafely.type == 11)
                     {
                         if (WorldGen.CloseDoor(doorX, doorY))
{
                             closeDoor = false;
                             NetMessage.SendData(19, -1, -1, null, 1, doorX, doorY, direction);
                         }
                         if ((position.X + (float)(width / 2)) / 16f > (float)(doorX + 4) || (position.X + (float)(width / 2)) / 16f < (float)(doorX - 4) || (position.Y + (float)(height / 2)) / 16f > (float)(doorY + 4) || (position.Y + (float)(height / 2)) / 16f < (float)(doorY - 4))
{
                             closeDoor = false;
                         }
                     }
                     else if (tileSafely.type == 389)
                     {
                         if (WorldGen.ShiftTallGate(doorX, doorY, closing: true))
{
                             closeDoor = false;
                             NetMessage.SendData(19, -1, -1, null, 5, doorX, doorY);
                         }
                         if ((position.X + (float)(width / 2)) / 16f > (float)(doorX + 4) || (position.X + (float)(width / 2)) / 16f < (float)(doorX - 4) || (position.Y + (float)(height / 2)) / 16f > (float)(doorY + 4) || (position.Y + (float)(height / 2)) / 16f < (float)(doorY - 4))
{
                             closeDoor = false;
                         }
                     }
                     else
                     {
                         closeDoor = false;
                     }
                 }
                 float num17 = 1f;
                 float num18 = 0.07f;
                 if (type == 614 && flag13)
                 {
                     num17 = 1.5f;
                     num18 = 0.1f;
                 }
                 else if (type == 299 || type == 539 || type == 538 || (type >= 639 && type <= 645))
                 {
                     num17 = 1.5f;
                 }
                 else if (flag6)
                 {
                     if (wet)
                     {
                         num18 = 1f;
                         num17 = 2f;
                     }
                     else
                     {
                         num18 = 0.07f;
                         num17 = 0.5f;
                     }
                 }
                 if (type == 625)
                 {
                     if (wet)
                     {
                         num18 = 1f;
                         num17 = 2.5f;
                     }
                     else
                     {
                         num18 = 0.07f;
                         num17 = 0.2f;
                     }
                 }
                 if (flag5)
                 {
                     num17 = 2f;
                     num18 = 1f;
                 }
                 if (friendly && (flag13 || flag17))
                 {
                     num17 = 1.5f;
                     float num19 = 1f - (float)life / (float)lifeMax;
                     num17 += num19 * 0.9f;
                     num18 = 0.1f;
                 }
                 if (flag11 && wet)
                 {
                     num17 = 2f;
                     num18 = 0.2f;
                 }
                 if (flag7 && wet)
                 {
                     if (Math.Abs(velocity.X) < 0.05f && Math.Abs(velocity.Y) < 0.05f)
                     {
                         velocity.X += num17 * 10f * (float)direction;
                     }
                     else
                     {
                         velocity.X *= 0.9f;
                     }
                 }
                 else if (velocity.X < 0f - num17 || velocity.X > num17)
                 {
                     if (velocity.Y == 0f)
                     {
                         velocity *= 0.8f;
                     }
                 }
                 else if (velocity.X < num17 && direction == 1)
                 {
                     velocity.X += num18;
                     if (velocity.X > num17)
                     {
                         velocity.X = num17;
                     }
                 }
                 else if (velocity.X > 0f - num17 && direction == -1)
                 {
                     velocity.X -= num18;
                     if (velocity.X > num17)
                     {
                         velocity.X = num17;
                     }
                 }
                 bool flag18 = true;
                 if ((float)(homeTileY * 16 - 32) > position.Y)
                 {
                     flag18 = false;
                 }
                 if (!flag18 && velocity.Y == 0f)
                 {
                     Collision.StepDown(ref position, ref velocity, width, height, ref stepSpeed, ref gfxOffY);
                 }
                 if (velocity.Y >= 0f)
                 {
                     Collision.StepUp(ref position, ref velocity, width, height, ref stepSpeed, ref gfxOffY, 1, flag18, 1);
                 }
                 if (velocity.Y == 0f)
                 {
                     int num20 = (int)((position.X + (float)(width / 2) + (float)(15 * direction)) / 16f);
                     int num21 = (int)((position.Y + (float)height - 16f) / 16f);
                     int num22 = 180;
                     AI_007_TownEntities_GetWalkPrediction(num6, floorX, flag9, flag17, num20, num21, out var keepwalking3, out var avoidFalling3);
                     bool flag19 = false;
                     bool flag20 = false;
                     if (wet && !flag9 && townNPC && (flag20 = AI_007_TownEntities_CheckIfWillDrown(flag17)) && localAI[3] <= 0f)
                     {
                         avoidFalling3 = true;
                         localAI[3] = num22;
                         int num23 = 0;
                         for (int n = 0; n <= 10 && Framing.GetTileSafely(num20 - direction, num21 - n).liquid != 0; n++)
{
                             num23++;
                         }
                         float num24 = 0.3f;
                         float num25 = (float)Math.Sqrt((float)(num23 * 16 + 16) * 2f * num24);
                         if (num25 > 26f)
{
                             num25 = 26f;
                         }
                         velocity.Y = 0f - num25;
                         localAI[3] = position.X;
                         flag19 = true;
                     }
                     if (avoidFalling3 && !flag19)
                     {
                         int num26 = (int)((position.X + (float)(width / 2)) / 16f);
                         int num27 = 0;
                         for (int num28 = -1; num28 <= 1; num28++)
{
                             Tile tileSafely2 = Framing.GetTileSafely(num26 + num28, num21 + 1);
                             if (tileSafely2.nactive() && Main.tileSolid[tileSafely2.type])
{
                                 num27++;
                             }
                         }
                         if (num27 <= 2)
{
                             if (velocity.X != 0f)
{
                                 netUpdate = true;
                             }
                             keepwalking3 = (avoidFalling3 = false);
                             ai[0] = 0f;
                             ai[1] = 50 + Main.rand.Next(50);
                             ai[2] = 0f;
                             localAI[3] = 40f;
                         }
                     }
                     if (position.X == localAI[3] && !flag19)
                     {
                         direction *= -1;
                         netUpdate = true;
                         localAI[3] = num22;
                     }
                     if (flag17 && !flag19)
                     {
                         if (localAI[3] > (float)num22)
{
                             localAI[3] = num22;
                         }
                         if (localAI[3] > 0f)
{
                             localAI[3] -= 1f;
                         }
                     }
                     else
                     {
                         localAI[3] = -1f;
                     }
                     Tile tileSafely3 = Framing.GetTileSafely(num20, num21);
                     Tile tileSafely4 = Framing.GetTileSafely(num20, num21 - 1);
                     Tile tileSafely5 = Framing.GetTileSafely(num20, num21 - 2);
                     bool flag21 = height / 16 < 3;
                     if (townNPC && tileSafely5.nactive() && (tileSafely5.type == 10 || tileSafely5.type == 388) && (Main.rand.Next(10) == 0 || flag))
                     {
                         if (Main.netMode != 1)
{
                             if (WorldGen.OpenDoor(num20, num21 - 2, direction))
{
                                 closeDoor = true;
                                 doorX = num20;
                                 doorY = num21 - 2;
                                 NetMessage.SendData(19, -1, -1, null, 0, num20, num21 - 2, direction);
                                 netUpdate = true;
                                 ai[1] += 80f;
                             }
                             else if (WorldGen.OpenDoor(num20, num21 - 2, -direction))
{
                                 closeDoor = true;
                                 doorX = num20;
                                 doorY = num21 - 2;
                                 NetMessage.SendData(19, -1, -1, null, 0, num20, num21 - 2, -direction);
                                 netUpdate = true;
                                 ai[1] += 80f;
                             }
                             else if (WorldGen.ShiftTallGate(num20, num21 - 2, closing: false))
{
                                 closeDoor = true;
                                 doorX = num20;
                                 doorY = num21 - 2;
                                 NetMessage.SendData(19, -1, -1, null, 4, num20, num21 - 2);
                                 netUpdate = true;
                                 ai[1] += 80f;
                             }
                             else
{
                                 direction *= -1;
                                 netUpdate = true;
                             }
                         }
                     }
                     else
                     {
                         if ((velocity.X < 0f && direction == -1) || (velocity.X > 0f && direction == 1))
{
                             bool flag22 = false;
                             bool flag23 = false;
                             if (tileSafely5.nactive() && Main.tileSolid[tileSafely5.type] && !Main.tileSolidTop[tileSafely5.type] && (!flag21 || (tileSafely4.nactive() && Main.tileSolid[tileSafely4.type] && !Main.tileSolidTop[tileSafely4.type])))
{
                                 if (!Collision.SolidTilesVersatile(num20 - direction * 2, num20 - direction, num21 - 5, num21 - 1) && !Collision.SolidTiles(num20, num20, num21 - 5, num21 - 3))
{
                                     velocity.Y = -6f;
                                     netUpdate = true;
                                 }
                                 else if (flag5)
{
                                     if (WorldGen.SolidTile((int)(base.Center.X / 16f) + direction, (int)(base.Center.Y / 16f)))
{
                                         direction *= -1;
                                         velocity.X *= 0f;
                                         netUpdate = true;
                                     }
                                 }
                                 else if (flag13)
{
                                     flag23 = true;
                                     flag22 = true;
                                 }
                                 else if (!flag20)
{
                                     flag22 = true;
                                 }
                             }
                             else if (tileSafely4.nactive() && Main.tileSolid[tileSafely4.type] && !Main.tileSolidTop[tileSafely4.type])
{
                                 if (!Collision.SolidTilesVersatile(num20 - direction * 2, num20 - direction, num21 - 4, num21 - 1) && !Collision.SolidTiles(num20, num20, num21 - 4, num21 - 2))
{
                                     velocity.Y = -5f;
                                     netUpdate = true;
                                 }
                                 else if (flag13)
{
                                     flag23 = true;
                                     flag22 = true;
                                 }
                                 else
{
                                     flag22 = true;
                                 }
                             }
                             else if (position.Y + (float)height - (float)(num21 * 16) > 20f && tileSafely3.nactive() && Main.tileSolid[tileSafely3.type] && !tileSafely3.topSlope())
{
                                 if (!Collision.SolidTilesVersatile(num20 - direction * 2, num20, num21 - 3, num21 - 1))
{
                                     velocity.Y = -4.4f;
                                     netUpdate = true;
                                 }
                                 else if (flag13)
{
                                     flag23 = true;
                                     flag22 = true;
                                 }
                                 else
{
                                     flag22 = true;
                                 }
                             }
                             else if (avoidFalling3)
{
                                 if (!flag20)
{
                                     flag22 = true;
                                 }
                                 if (flag13)
{
                                     flag23 = true;
                                 }
                             }
                             else if (flag12 && !Collision.SolidTilesVersatile(num20 - direction * 2, num20 - direction, num21 - 2, num21 - 1))
{
                                 velocity.Y = -5f;
                                 netUpdate = true;
                             }
                             if (flag23)
{
                                 keepwalking3 = false;
                                 velocity.X = 0f;
                                 ai[0] = 8f;
                                 ai[1] = 240f;
                                 netUpdate = true;
                             }
                             if (flag22)
{
                                 direction *= -1;
                                 velocity.X *= -1f;
                                 netUpdate = true;
                             }
                             if (keepwalking3)
{
                                 ai[1] = 90f;
                                 netUpdate = true;
                             }
                             if (velocity.Y < 0f)
{
                                 localAI[3] = position.X;
                             }
                         }
                         if (velocity.Y < 0f && wet)
{
                             velocity.Y *= 1.2f;
                         }
                         if (velocity.Y < 0f && NPCID.Sets.TownCritter[type] && !flag5)
{
                             velocity.Y *= 1.2f;
                         }
                     }
                 }
                 else if (flag12 && !wet)
                 {
                     int num29 = (int)(base.Center.X / 16f);
                     int num30 = (int)((position.Y + (float)height - 16f) / 16f);
                     int num31 = 0;
                     for (int num32 = -1; num32 <= 1; num32++)
                     {
                         for (int num33 = 1; num33 <= 6; num33++)
{
                             Tile tileSafely6 = Framing.GetTileSafely(num29 + num32, num30 + num33);
                             if (tileSafely6.liquid > 0 || (tileSafely6.nactive() && Main.tileSolid[tileSafely6.type]))
{
                                 num31++;
                             }
                         }
                     }
                     if (num31 <= 2)
                     {
                         if (velocity.X != 0f)
{
                             netUpdate = true;
                         }
                         velocity.X *= 0.2f;
                         ai[0] = 0f;
                         ai[1] = 50 + Main.rand.Next(50);
                         ai[2] = 0f;
                         localAI[3] = 40f;
                     }
                 }
             }
         }
         else if (ai[0] == 2f || ai[0] == 11f)
         {
             if (Main.netMode != 1)
             {
                 localAI[3] -= 1f;
                 if (Main.rand.Next(60) == 0 && localAI[3] == 0f)
                 {
                     localAI[3] = 60f;
                     direction *= -1;
                     netUpdate = true;
                 }
             }
             ai[1] -= 1f;
             velocity.X *= 0.8f;
             if (ai[1] <= 0f)
             {
                 localAI[3] = 40f;
                 ai[0] = 0f;
                 ai[1] = 60 + Main.rand.Next(60);
                 netUpdate = true;
             }
         }
         else if (ai[0] == 3f || ai[0] == 4f || ai[0] == 5f || ai[0] == 8f || ai[0] == 9f || ai[0] == 16f || ai[0] == 17f || ai[0] == 20f || ai[0] == 21f || ai[0] == 22f || ai[0] == 23f)
         {
             velocity.X *= 0.8f;
             ai[1] -= 1f;
             if (ai[0] == 8f && ai[1] < 60f && flag13)
             {
                 ai[1] = 180f;
                 netUpdate = true;
             }
             if (ai[0] == 5f)
             {
                 Point coords = (base.Bottom + Vector2.UnitY * -2f).ToTileCoordinates();
                 Tile tile = Main.tile[coords.X, coords.Y];
                 if (tile.type != 15 && tile.type != 497)
                 {
                     ai[1] = 0f;
                 }
                 else
                 {
                     Main.sittingManager.AddNPC(whoAmI, coords);
                 }
             }
             if (ai[1] <= 0f)
             {
                 ai[0] = 0f;
                 ai[1] = 60 + Main.rand.Next(60);
                 ai[2] = 0f;
                 localAI[3] = 30 + Main.rand.Next(60);
                 netUpdate = true;
             }
         }
         else if (ai[0] == 6f || ai[0] == 7f || ai[0] == 18f || ai[0] == 19f)
         {
             if (ai[0] == 18f && (localAI[3] < 1f || localAI[3] > 2f))
             {
                 localAI[3] = 2f;
             }
             velocity.X *= 0.8f;
             ai[1] -= 1f;
             int num34 = (int)ai[2];
             if (num34 < 0 || num34 > 255 || !Main.player[num34].CanBeTalkedTo || Main.player[num34].Distance(base.Center) > 200f || !Collision.CanHitLine(base.Top, 0, 0, Main.player[num34].Top, 0, 0))
             {
                 ai[1] = 0f;
             }
             if (ai[1] > 0f)
             {
                 int num35 = ((base.Center.X < Main.player[num34].Center.X) ? 1 : (-1));
                 if (num35 != direction)
                 {
                     netUpdate = true;
                 }
                 direction = num35;
             }
             else
             {
                 ai[0] = 0f;
                 ai[1] = 60 + Main.rand.Next(60);
                 ai[2] = 0f;
                 localAI[3] = 30 + Main.rand.Next(60);
                 netUpdate = true;
             }
         }
         else if (ai[0] == 10f)
         {
             int num36 = 0;
             int num37 = 0;
             float knockBack = 0f;
             float num38 = 0f;
             int num39 = 0;
             int num40 = 0;
             int maxValue = 0;
             float num41 = 0f;
             float num42 = NPCID.Sets.DangerDetectRange[type];
             float num43 = 0f;
             if ((float)NPCID.Sets.AttackTime[type] == ai[1])
             {
                 frameCounter = 0.0;
                 localAI[3] = 0f;
             }
             if (type == 38)
             {
                 num36 = 30;
                 num38 = 6f;
                 num37 = 20;
                 num39 = 10;
                 num40 = 180;
                 maxValue = 120;
                 num41 = 16f;
                 knockBack = 7f;
             }
             else if (type == 633)
             {
                 num36 = 880;
                 num38 = 24f;
                 num37 = 15;
                 num39 = 1;
                 num41 = 0f;
                 knockBack = 7f;
                 num40 = 15;
                 maxValue = 10;
                 if (ShouldBestiaryGirlBeLycantrope())
                 {
                     num36 = 929;
                     num37 = (int)((float)num37 * 1.5f);
                 }
             }
             else if (type == 550)
             {
                 num36 = 669;
                 num38 = 6f;
                 num37 = 24;
                 num39 = 10;
                 num40 = 120;
                 maxValue = 60;
                 num41 = 16f;
                 knockBack = 9f;
             }
             else if (type == 588)
             {
                 num36 = 721;
                 num38 = 8f;
                 num37 = 15;
                 num39 = 5;
                 num40 = 20;
                 maxValue = 10;
                 num41 = 16f;
                 knockBack = 9f;
             }
             else if (type == 208)
             {
                 num36 = 588;
                 num38 = 6f;
                 num37 = 30;
                 num39 = 10;
                 num40 = 60;
                 maxValue = 120;
                 num41 = 16f;
                 knockBack = 6f;
             }
             else if (type == 17)
             {
                 num36 = 48;
                 num38 = 9f;
                 num37 = 12;
                 num39 = 10;
                 num40 = 60;
                 maxValue = 60;
                 num41 = 16f;
                 knockBack = 1.5f;
             }
             else if (type == 369)
             {
                 num36 = 520;
                 num38 = 12f;
                 num37 = 10;
                 num39 = 10;
                 num40 = 0;
                 maxValue = 1;
                 num41 = 16f;
                 knockBack = 3f;
             }
             else if (type == 453)
             {
                 num36 = 21;
                 num38 = 14f;
                 num37 = 14;
                 num39 = 10;
                 num40 = 0;
                 maxValue = 1;
                 num41 = 16f;
                 knockBack = 3f;
             }
             else if (type == 107)
             {
                 num36 = 24;
                 num38 = 5f;
                 num37 = 15;
                 num39 = 10;
                 num40 = 60;
                 maxValue = 60;
                 num41 = 16f;
                 knockBack = 1f;
             }
             else if (type == 124)
             {
                 num36 = 582;
                 num38 = 10f;
                 num37 = 11;
                 num39 = 1;
                 num40 = 30;
                 maxValue = 30;
                 knockBack = 3.5f;
             }
             else if (type == 18)
             {
                 num36 = 583;
                 num38 = 8f;
                 num37 = 8;
                 num39 = 1;
                 num40 = 15;
                 maxValue = 10;
                 knockBack = 2f;
                 num41 = 10f;
             }
             else if (type == 142)
             {
                 num36 = 589;
                 num38 = 7f;
                 num37 = 22;
                 num39 = 1;
                 num40 = 10;
                 maxValue = 1;
                 knockBack = 2f;
                 num41 = 10f;
             }
             if (Main.expertMode)
             {
                 num37 = (int)((float)num37 * Main.GameModeInfo.TownNPCDamageMultiplier);
             }
             num37 = (int)((float)num37 * num2);
             velocity.X *= 0.8f;
             ai[1] -= 1f;
             localAI[3] += 1f;
             if (localAI[3] == (float)num39 && Main.netMode != 1)
             {
                 Vector2 vec = -Vector2.UnitY;
                 if (num11 == 1 && spriteDirection == 1 && num13 != -1)
                 {
                     vec = DirectionTo(Main.npc[num13].Center + new Vector2(0f, (0f - num41) * MathHelper.Clamp(Distance(Main.npc[num13].Center) / num42, 0f, 1f)));
                 }
                 if (num11 == -1 && spriteDirection == -1 && num12 != -1)
                 {
                     vec = DirectionTo(Main.npc[num12].Center + new Vector2(0f, (0f - num41) * MathHelper.Clamp(Distance(Main.npc[num12].Center) / num42, 0f, 1f)));
                 }
                 if (vec.HasNaNs() || Math.Sign(vec.X) != spriteDirection)
                 {
                     vec = new Vector2(spriteDirection, -1f);
                 }
                 vec *= num38;
                 vec += Utils.RandomVector2(Main.rand, 0f - num43, num43);
                 int num44 = 1000;
                 num44 = ((type == 124) ? Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec.X, vec.Y, num36, num37, knockBack, Main.myPlayer, 0f, whoAmI, townNpcVariationIndex) : ((type != 142) ? Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec.X, vec.Y, num36, num37, knockBack, Main.myPlayer) : Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec.X, vec.Y, num36, num37, knockBack, Main.myPlayer, 0f, Main.rand.Next(5))));
                 Main.projectile[num44].npcProj = true;
                 Main.projectile[num44].noDropItem = true;
                 if (type == 588)
                 {
                     Main.projectile[num44].timeLeft = 480;
                 }
             }
             if (ai[1] <= 0f && 0 == 0)
             {
                 ai[0] = ((localAI[2] == 8f && flag13) ? 8 : 0);
                 ai[1] = num40 + Main.rand.Next(maxValue);
                 ai[2] = 0f;
                 localAI[1] = (localAI[3] = num40 / 2 + Main.rand.Next(maxValue));
                 netUpdate = true;
             }
         }
         else if (ai[0] == 12f)
         {
             int num45 = 0;
             int num46 = 0;
             float num47 = 0f;
             int num48 = 0;
             int num49 = 0;
             int maxValue2 = 0;
             float knockBack2 = 0f;
             int num50 = 0;
             bool flag24 = false;
             float num51 = 0f;
             if ((float)NPCID.Sets.AttackTime[type] == ai[1])
             {
                 frameCounter = 0.0;
                 localAI[3] = 0f;
             }
             int num52 = -1;
             if (num11 == 1 && spriteDirection == 1)
             {
                 num52 = num13;
             }
             if (num11 == -1 && spriteDirection == -1)
             {
                 num52 = num12;
             }
             if (type == 19)
             {
                 num45 = 14;
                 num47 = 13f;
                 num46 = 24;
                 num49 = 14;
                 maxValue2 = 4;
                 knockBack2 = 3f;
                 num48 = 1;
                 num51 = 0.5f;
                 if ((float)NPCID.Sets.AttackTime[type] == ai[1])
                 {
                     frameCounter = 0.0;
                     localAI[3] = 0f;
                 }
                 if (Main.hardMode)
                 {
                     num46 = 15;
                     if (localAI[3] > (float)num48)
                     {
                         num48 = 10;
                         flag24 = true;
                     }
                     if (localAI[3] > (float)num48)
                     {
                         num48 = 20;
                         flag24 = true;
                     }
                     if (localAI[3] > (float)num48)
                     {
                         num48 = 30;
                         flag24 = true;
                     }
                 }
             }
             else if (type == 227)
             {
                 num45 = 587;
                 num47 = 10f;
                 num46 = 8;
                 num49 = 10;
                 maxValue2 = 1;
                 knockBack2 = 1.75f;
                 num48 = 1;
                 num51 = 0.5f;
                 if (localAI[3] > (float)num48)
                 {
                     num48 = 12;
                     flag24 = true;
                 }
                 if (localAI[3] > (float)num48)
                 {
                     num48 = 24;
                     flag24 = true;
                 }
                 if (Main.hardMode)
                 {
                     num46 += 2;
                 }
             }
             else if (type == 368)
             {
                 num45 = 14;
                 num47 = 13f;
                 num46 = 24;
                 num49 = 12;
                 maxValue2 = 5;
                 knockBack2 = 2f;
                 num48 = 1;
                 num51 = 0.2f;
                 if (Main.hardMode)
                 {
                     num46 = 30;
                     num45 = 357;
                 }
             }
             else if (type == 22)
             {
                 num47 = 10f;
                 num46 = 8;
                 num48 = 1;
                 if (Main.hardMode)
                 {
                     num45 = 2;
                     num49 = 15;
                     maxValue2 = 10;
                     num46 += 6;
                 }
                 else
                 {
                     num45 = 1;
                     num49 = 30;
                     maxValue2 = 20;
                 }
                 knockBack2 = 2.75f;
                 num50 = 4;
                 num51 = 0.7f;
             }
             else if (type == 228)
             {
                 num45 = 267;
                 num47 = 14f;
                 num46 = 20;
                 num48 = 1;
                 num49 = 10;
                 maxValue2 = 1;
                 knockBack2 = 3f;
                 num50 = 6;
                 num51 = 0.4f;
             }
             else if (type == 178)
             {
                 num45 = 242;
                 num47 = 13f;
                 num46 = ((!Main.hardMode) ? 11 : 15);
                 num49 = 10;
                 maxValue2 = 1;
                 knockBack2 = 2f;
                 num48 = 1;
                 if (localAI[3] > (float)num48)
                 {
                     num48 = 8;
                     flag24 = true;
                 }
                 if (localAI[3] > (float)num48)
                 {
                     num48 = 16;
                     flag24 = true;
                 }
                 num51 = 0.3f;
             }
             else if (type == 229)
             {
                 num45 = 14;
                 num47 = 14f;
                 num46 = 24;
                 num49 = 10;
                 maxValue2 = 1;
                 knockBack2 = 2f;
                 num48 = 1;
                 num51 = 0.7f;
                 if (localAI[3] > (float)num48)
                 {
                     num48 = 16;
                     flag24 = true;
                 }
                 if (localAI[3] > (float)num48)
                 {
                     num48 = 24;
                     flag24 = true;
                 }
                 if (localAI[3] > (float)num48)
                 {
                     num48 = 32;
                     flag24 = true;
                 }
                 if (localAI[3] > (float)num48)
                 {
                     num48 = 40;
                     flag24 = true;
                 }
                 if (localAI[3] > (float)num48)
                 {
                     num48 = 48;
                     flag24 = true;
                 }
                 if (localAI[3] == 0f && num52 != -1 && Distance(Main.npc[num52].Center) < (float)NPCID.Sets.PrettySafe[type])
                 {
                     num51 = 0.1f;
                     num45 = 162;
                     num46 = 50;
                     knockBack2 = 10f;
                     num47 = 24f;
                 }
             }
             else if (type == 209)
             {
                 num45 = Utils.SelectRandom<int>(Main.rand, 134, 133, 135);
                 num48 = 1;
                 switch (num45)
                 {
                 case 135:
                     num47 = 12f;
                     num46 = 30;
                     num49 = 30;
                     maxValue2 = 10;
                     knockBack2 = 7f;
                     num51 = 0.2f;
                     break;
                 case 133:
                     num47 = 10f;
                     num46 = 25;
                     num49 = 10;
                     maxValue2 = 1;
                     knockBack2 = 6f;
                     num51 = 0.2f;
                     break;
                 case 134:
                     num47 = 13f;
                     num46 = 20;
                     num49 = 20;
                     maxValue2 = 10;
                     knockBack2 = 4f;
                     num51 = 0.1f;
                     break;
                 }
             }
             if (Main.expertMode)
             {
                 num46 = (int)((float)num46 * Main.GameModeInfo.TownNPCDamageMultiplier);
             }
             num46 = (int)((float)num46 * num2);
             velocity.X *= 0.8f;
             ai[1] -= 1f;
             localAI[3] += 1f;
             if (localAI[3] == (float)num48 && Main.netMode != 1)
             {
                 Vector2 vec2 = Vector2.Zero;
                 if (num52 != -1)
                 {
                     vec2 = DirectionTo(Main.npc[num52].Center + new Vector2(0f, -num50));
                 }
                 if (vec2.HasNaNs() || Math.Sign(vec2.X) != spriteDirection)
                 {
                     vec2 = new Vector2(spriteDirection, 0f);
                 }
                 vec2 *= num47;
                 vec2 += Utils.RandomVector2(Main.rand, 0f - num51, num51);
                 int num53 = 1000;
                 num53 = ((type != 227) ? Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec2.X, vec2.Y, num45, num46, knockBack2, Main.myPlayer) : Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec2.X, vec2.Y, num45, num46, knockBack2, Main.myPlayer, 0f, (float)Main.rand.Next(12) / 6f));
                 Main.projectile[num53].npcProj = true;
                 Main.projectile[num53].noDropItem = true;
             }
             if (localAI[3] == (float)num48 && flag24 && num52 != -1)
             {
                 Vector2 vector2 = DirectionTo(Main.npc[num52].Center);
                 if (vector2.Y <= 0.5f && vector2.Y >= -0.5f)
                 {
                     ai[2] = vector2.Y;
                 }
             }
             if (ai[1] <= 0f && 0 == 0)
             {
                 ai[0] = ((localAI[2] == 8f && flag13) ? 8 : 0);
                 ai[1] = num49 + Main.rand.Next(maxValue2);
                 ai[2] = 0f;
                 localAI[1] = (localAI[3] = num49 / 2 + Main.rand.Next(maxValue2));
                 netUpdate = true;
             }
         }
         else if (ai[0] == 13f)
         {
             velocity.X *= 0.8f;
             if ((float)NPCID.Sets.AttackTime[type] == ai[1])
             {
                 frameCounter = 0.0;
             }
             ai[1] -= 1f;
             localAI[3] += 1f;
             if (localAI[3] == 1f && Main.netMode != 1)
             {
                 Vector2 vec3 = DirectionTo(Main.npc[(int)ai[2]].Center + new Vector2(0f, -20f));
                 if (vec3.HasNaNs() || Math.Sign(vec3.X) == -spriteDirection)
                 {
                     vec3 = new Vector2(spriteDirection, -1f);
                 }
                 vec3 *= 8f;
                 int num54 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec3.X, vec3.Y, 584, 0, 0f, Main.myPlayer, ai[2]);
                 Main.projectile[num54].npcProj = true;
                 Main.projectile[num54].noDropItem = true;
             }
             if (ai[1] <= 0f)
             {
                 ai[0] = 0f;
                 ai[1] = 10 + Main.rand.Next(10);
                 ai[2] = 0f;
                 localAI[3] = 5 + Main.rand.Next(10);
                 netUpdate = true;
             }
         }
         else if (ai[0] == 14f)
         {
             int num55 = 0;
             int num56 = 0;
             float num57 = 0f;
             int num58 = 0;
             int num59 = 0;
             int maxValue3 = 0;
             float knockBack3 = 0f;
             float num60 = 0f;
             float num61 = NPCID.Sets.DangerDetectRange[type];
             float num62 = 1f;
             float num63 = 0f;
             if ((float)NPCID.Sets.AttackTime[type] == ai[1])
             {
                 frameCounter = 0.0;
                 localAI[3] = 0f;
             }
             int num64 = -1;
             if (num11 == 1 && spriteDirection == 1)
             {
                 num64 = num13;
             }
             if (num11 == -1 && spriteDirection == -1)
             {
                 num64 = num12;
             }
             if (type == 54)
             {
                 num55 = 585;
                 num57 = 10f;
                 num56 = 16;
                 num58 = 30;
                 num59 = 20;
                 maxValue3 = 15;
                 knockBack3 = 2f;
                 num63 = 1f;
             }
             else if (type == 108)
             {
                 num55 = 15;
                 num57 = 6f;
                 num56 = 18;
                 num58 = 15;
                 num59 = 15;
                 maxValue3 = 5;
                 knockBack3 = 3f;
                 num60 = 20f;
             }
             else if (type == 160)
             {
                 num55 = 590;
                 num56 = 40;
                 num58 = 15;
                 num59 = 10;
                 maxValue3 = 1;
                 knockBack3 = 3f;
                 for (; localAI[3] > (float)num58; num58 += 15)
                 {
                 }
             }
             else if (type == 663)
             {
                 num55 = 950;
                 num56 = ((!Main.hardMode) ? 15 : 20);
                 num58 = 15;
                 num59 = 0;
                 maxValue3 = 0;
                 knockBack3 = 3f;
                 for (; localAI[3] > (float)num58; num58 += 10)
                 {
                 }
             }
             else if (type == 20)
             {
                 num55 = 586;
                 num58 = 24;
                 num59 = 10;
                 maxValue3 = 1;
                 knockBack3 = 3f;
             }
             if (Main.expertMode)
             {
                 num56 = (int)((float)num56 * Main.GameModeInfo.TownNPCDamageMultiplier);
             }
             num56 = (int)((float)num56 * num2);
             velocity.X *= 0.8f;
             ai[1] -= 1f;
             localAI[3] += 1f;
             if (localAI[3] == (float)num58 && Main.netMode != 1)
             {
                 Vector2 vec4 = Vector2.Zero;
                 if (num64 != -1)
                 {
                     vec4 = DirectionTo(Main.npc[num64].Center + new Vector2(0f, (0f - num60) * MathHelper.Clamp(Distance(Main.npc[num64].Center) / num61, 0f, 1f)));
                 }
                 if (vec4.HasNaNs() || Math.Sign(vec4.X) != spriteDirection)
                 {
                     vec4 = new Vector2(spriteDirection, 0f);
                 }
                 vec4 *= num57;
                 vec4 += Utils.RandomVector2(Main.rand, 0f - num63, num63);
                 if (type == 108)
                 {
                     int num65 = Utils.SelectRandom<int>(Main.rand, 1, 1, 1, 1, 2, 2, 3);
                     for (int num66 = 0; num66 < num65; num66++)
                     {
                         Vector2 vector3 = Utils.RandomVector2(Main.rand, -3.4f, 3.4f);
                         int num67 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec4.X + vector3.X, vec4.Y + vector3.Y, num55, num56, knockBack3, Main.myPlayer, 0f, 0f, townNpcVariationIndex);
                         Main.projectile[num67].npcProj = true;
                         Main.projectile[num67].noDropItem = true;
                     }
                 }
                 else if (type == 160)
                 {
                     if (num64 != -1)
                     {
                         Vector2 vector4 = Main.npc[num64].position - Main.npc[num64].Size * 2f + Main.npc[num64].Size * Utils.RandomVector2(Main.rand, 0f, 1f) * 5f;
                         int num68 = 10;
                         while (num68 > 0 && WorldGen.SolidTile(Framing.GetTileSafely((int)vector4.X / 16, (int)vector4.Y / 16)))
{
                             num68--;
                             vector4 = Main.npc[num64].position - Main.npc[num64].Size * 2f + Main.npc[num64].Size * Utils.RandomVector2(Main.rand, 0f, 1f) * 5f;
                         }
                         int num69 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector4.X, vector4.Y, 0f, 0f, num55, num56, knockBack3, Main.myPlayer, 0f, 0f, townNpcVariationIndex);
                         Main.projectile[num69].npcProj = true;
                         Main.projectile[num69].noDropItem = true;
                     }
                 }
                 else if (type == 663)
                 {
                     if (num64 != -1)
                     {
                         Vector2 vector5 = Main.npc[num64].position + Main.npc[num64].Size * Utils.RandomVector2(Main.rand, 0f, 1f) * 1f;
                         int num70 = 5;
                         while (num70 > 0 && WorldGen.SolidTile(Framing.GetTileSafely((int)vector5.X / 16, (int)vector5.Y / 16)))
{
                             num70--;
                             vector5 = Main.npc[num64].position + Main.npc[num64].Size * Utils.RandomVector2(Main.rand, 0f, 1f) * 1f;
                         }
                         int num71 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector5.X, vector5.Y, 0f, 0f, num55, num56, knockBack3, Main.myPlayer, 0f, 0f, townNpcVariationIndex);
                         Main.projectile[num71].npcProj = true;
                         Main.projectile[num71].noDropItem = true;
                     }
                 }
                 else if (type == 20)
                 {
                     int num72 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec4.X, vec4.Y, num55, num56, knockBack3, Main.myPlayer, 0f, whoAmI, townNpcVariationIndex);
                     Main.projectile[num72].npcProj = true;
                     Main.projectile[num72].noDropItem = true;
                 }
                 else
                 {
                     int num73 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec4.X, vec4.Y, num55, num56, knockBack3, Main.myPlayer);
                     Main.projectile[num73].npcProj = true;
                     Main.projectile[num73].noDropItem = true;
                 }
             }
             if (num62 > 0f)
             {
                 Vector3 vector6 = GetMagicAuraColor().ToVector3() * num62;
                 Lighting.AddLight(base.Center, vector6.X, vector6.Y, vector6.Z);
             }
             if (ai[1] <= 0f && 0 == 0)
             {
                 ai[0] = ((localAI[2] == 8f && flag13) ? 8 : 0);
                 ai[1] = num59 + Main.rand.Next(maxValue3);
                 ai[2] = 0f;
                 localAI[1] = (localAI[3] = num59 / 2 + Main.rand.Next(maxValue3));
                 netUpdate = true;
             }
         }
         else if (ai[0] == 15f)
         {
             int num74 = 0;
             int maxValue4 = 0;
             if ((float)NPCID.Sets.AttackTime[type] == ai[1])
             {
                 frameCounter = 0.0;
                 localAI[3] = 0f;
             }
             int num75 = 0;
             float num76 = 0f;
             int num77 = 0;
             int num78 = 0;
             if (num11 == 1)
             {
                 _ = spriteDirection;
                 _ = 1;
             }
             if (num11 == -1)
             {
                 _ = spriteDirection;
                 _ = -1;
             }
             if (type == 207)
             {
                 num75 = 11;
                 num77 = (num78 = 32);
                 num74 = 12;
                 maxValue4 = 6;
                 num76 = 4.25f;
             }
             else if (type == 441)
             {
                 num75 = 9;
                 num77 = (num78 = 28);
                 num74 = 9;
                 maxValue4 = 3;
                 num76 = 3.5f;
                 if (GivenName == "Andrew")
                 {
                     num75 *= 2;
                     num76 *= 2f;
                 }
             }
             else if (type == 353)
             {
                 num75 = 10;
                 num77 = (num78 = 32);
                 num74 = 15;
                 maxValue4 = 8;
                 num76 = 5f;
             }
             else if (NPCID.Sets.IsTownPet[type])
             {
                 num75 = 10;
                 num77 = (num78 = 32);
                 num74 = 15;
                 maxValue4 = 8;
                 num76 = 3f;
             }
             if (Main.expertMode)
             {
                 num75 = (int)((float)num75 * Main.GameModeInfo.TownNPCDamageMultiplier);
             }
             num75 = (int)((float)num75 * num2);
             velocity.X *= 0.8f;
             ai[1] -= 1f;
             if (Main.netMode != 1)
             {
                 Tuple<Vector2, float> swingStats = GetSwingStats(NPCID.Sets.AttackTime[type] * 2, (int)ai[1], spriteDirection, num77, num78);
                 Rectangle itemRectangle = new Rectangle((int)swingStats.Item1.X, (int)swingStats.Item1.Y, num77, num78);
                 if (spriteDirection == -1)
                 {
                     itemRectangle.X -= num77;
                 }
                 itemRectangle.Y -= num78;
                 TweakSwingStats(NPCID.Sets.AttackTime[type] * 2, (int)ai[1], spriteDirection, ref itemRectangle);
                 int myPlayer = Main.myPlayer;
                 for (int num79 = 0; num79 < 200; num79++)
                 {
                     NPC nPC2 = Main.npc[num79];
                     if (nPC2.active && nPC2.immune[myPlayer] == 0 && !nPC2.dontTakeDamage && !nPC2.friendly && nPC2.damage > 0 && itemRectangle.Intersects(nPC2.Hitbox) && (nPC2.noTileCollide || Collision.CanHit(position, width, height, nPC2.position, nPC2.width, nPC2.height)))
                     {
                         nPC2.StrikeNPCNoInteraction(num75, num76, spriteDirection);
                         if (Main.netMode != 0)
{
                             NetMessage.SendData(28, -1, -1, null, num79, num75, num76, spriteDirection);
                         }
                         nPC2.netUpdate = true;
                         nPC2.immune[myPlayer] = (int)ai[1] + 2;
                     }
                 }
             }
             if (ai[1] <= 0f)
             {
                 bool flag25 = false;
                 if (flag13)
                 {
                     int num80 = -num11;
                     if (!Collision.CanHit(base.Center, 0, 0, base.Center + Vector2.UnitX * num80 * 32f, 0, 0) || localAI[2] == 8f)
                     {
                         flag25 = true;
                     }
                     if (flag25)
                     {
                         int num81 = NPCID.Sets.AttackTime[type];
                         int num82 = ((num11 == 1) ? num13 : num12);
                         int num83 = ((num11 == 1) ? num12 : num13);
                         if (num82 != -1 && !Collision.CanHit(base.Center, 0, 0, Main.npc[num82].Center, 0, 0))
{
                             num82 = ((num83 == -1 || !Collision.CanHit(base.Center, 0, 0, Main.npc[num83].Center, 0, 0)) ? (-1) : num83);
                         }
                         if (num82 != -1)
{
                             ai[0] = 15f;
                             ai[1] = num81;
                             ai[2] = 0f;
                             localAI[3] = 0f;
                             direction = ((position.X < Main.npc[num82].position.X) ? 1 : (-1));
                             netUpdate = true;
                         }
                         else
{
                             flag25 = false;
                         }
                     }
                 }
                 if (!flag25)
                 {
                     ai[0] = ((localAI[2] == 8f && flag13) ? 8 : 0);
                     ai[1] = num74 + Main.rand.Next(maxValue4);
                     ai[2] = 0f;
                     localAI[1] = (localAI[3] = num74 / 2 + Main.rand.Next(maxValue4));
                     netUpdate = true;
                 }
             }
         }
         else if (ai[0] == 24f)
         {
             velocity.X *= 0.8f;
             ai[1] -= 1f;
             localAI[3] += 1f;
             direction = 1;
             spriteDirection = 1;
             Vector3 vector7 = GetMagicAuraColor().ToVector3();
             Lighting.AddLight(base.Center, vector7.X, vector7.Y, vector7.Z);
             if (ai[1] <= 0f)
             {
                 ai[0] = 0f;
                 ai[1] = 480f;
                 ai[2] = 0f;
                 localAI[1] = 480f;
                 netUpdate = true;
             }
         }
         if (flag11 && wet)
         {
             int num84 = (int)(base.Center.X / 16f);
             int num85 = 5;
             if (collideX || (num84 < num85 && direction == -1) || (num84 > Main.maxTilesX - num85 && direction == 1))
             {
                 direction *= -1;
                 velocity.X *= -0.25f;
                 netUpdate = true;
             }
             velocity.Y *= 0.9f;
             velocity.Y -= 0.5f;
             if (velocity.Y < -15f)
             {
                 velocity.Y = -15f;
             }
         }
         if (flag10 && wet)
         {
             if (flag7)
             {
                 ai[1] = 50f;
             }
             int num86 = (int)(base.Center.X / 16f);
             int num87 = 5;
             if (collideX || (num86 < num87 && direction == -1) || (num86 > Main.maxTilesX - num87 && direction == 1))
             {
                 direction *= -1;
                 velocity.X *= -0.25f;
                 netUpdate = true;
             }
             if (Collision.GetWaterLine(base.Center.ToTileCoordinates(), out var waterLineHeight))
             {
                 float num88 = base.Center.Y + 1f;
                 if (base.Center.Y > waterLineHeight)
                 {
                     velocity.Y -= 0.8f;
                     if (velocity.Y < -4f)
                     {
                         velocity.Y = -4f;
                     }
                     if (num88 + velocity.Y < waterLineHeight)
                     {
                         velocity.Y = waterLineHeight - num88;
                     }
                 }
                 else
                 {
                     velocity.Y = MathHelper.Min(velocity.Y, waterLineHeight - num88);
                 }
             }
             else
             {
                 velocity.Y -= 0.2f;
             }
         }
         if (Main.netMode != 1 && isLikeATownNPC && !flag3)
         {
             bool flag26 = ai[0] < 2f && !flag13 && !wet;
             bool flag27 = (ai[0] < 2f || ai[0] == 8f) && (flag13 || flag14);
             if (localAI[1] > 0f)
             {
                 localAI[1] -= 1f;
             }
             if (localAI[1] > 0f)
             {
                 flag27 = false;
             }
             if (flag27 && type == 124 && localAI[0] == 1f)
             {
                 flag27 = false;
             }
             if (flag27 && type == 20)
             {
                 flag27 = false;
                 for (int num89 = 0; num89 < 200; num89++)
                 {
                     NPC nPC3 = Main.npc[num89];
                     if (nPC3.active && nPC3.townNPC && !(Distance(nPC3.Center) > 1200f) && nPC3.FindBuffIndex(165) == -1)
                     {
                         flag27 = true;
                         break;
                     }
                 }
             }
             if (CanTalk && flag26 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(300) == 0)
             {
                 int num90 = 420;
                 num90 = ((Main.rand.Next(2) != 0) ? (num90 * Main.rand.Next(1, 3)) : (num90 * Main.rand.Next(1, 4)));
                 int num91 = 100;
                 int num92 = 20;
                 for (int num93 = 0; num93 < 200; num93++)
                 {
                     NPC nPC4 = Main.npc[num93];
                     bool flag28 = (nPC4.ai[0] == 1f && nPC4.closeDoor) || (nPC4.ai[0] == 1f && nPC4.ai[1] > 200f) || nPC4.ai[0] > 1f || nPC4.wet;
                     if (nPC4 != this && nPC4.active && nPC4.CanBeTalkedTo && !flag28 && nPC4.Distance(base.Center) < (float)num91 && nPC4.Distance(base.Center) > (float)num92 && Collision.CanHit(base.Center, 0, 0, nPC4.Center, 0, 0))
                     {
                         int num94 = (position.X < nPC4.position.X).ToDirectionInt();
                         ai[0] = 3f;
                         ai[1] = num90;
                         ai[2] = num93;
                         direction = num94;
                         netUpdate = true;
                         nPC4.ai[0] = 4f;
                         nPC4.ai[1] = num90;
                         nPC4.ai[2] = whoAmI;
                         nPC4.direction = -num94;
                         nPC4.netUpdate = true;
                         break;
                     }
                 }
             }
             else if (CanTalk && flag26 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(1800) == 0)
             {
                 int num95 = 420;
                 num95 = ((Main.rand.Next(2) != 0) ? (num95 * Main.rand.Next(1, 3)) : (num95 * Main.rand.Next(1, 4)));
                 int num96 = 100;
                 int num97 = 20;
                 for (int num98 = 0; num98 < 200; num98++)
                 {
                     NPC nPC5 = Main.npc[num98];
                     bool flag29 = (nPC5.ai[0] == 1f && nPC5.closeDoor) || (nPC5.ai[0] == 1f && nPC5.ai[1] > 200f) || nPC5.ai[0] > 1f || nPC5.wet;
                     if (nPC5 != this && nPC5.active && nPC5.CanBeTalkedTo && !NPCID.Sets.IsTownPet[nPC5.type] && !flag29 && nPC5.Distance(base.Center) < (float)num96 && nPC5.Distance(base.Center) > (float)num97 && Collision.CanHit(base.Center, 0, 0, nPC5.Center, 0, 0))
                     {
                         int num99 = (position.X < nPC5.position.X).ToDirectionInt();
                         ai[0] = 16f;
                         ai[1] = num95;
                         ai[2] = num98;
                         localAI[2] = Main.rand.Next(4);
                         localAI[3] = Main.rand.Next(3 - (int)localAI[2]);
                         direction = num99;
                         netUpdate = true;
                         nPC5.ai[0] = 17f;
                         nPC5.ai[1] = num95;
                         nPC5.ai[2] = whoAmI;
                         nPC5.localAI[2] = 0f;
                         nPC5.localAI[3] = 0f;
                         nPC5.direction = -num99;
                         nPC5.netUpdate = true;
                         break;
                     }
                 }
             }
             else if (!NPCID.Sets.IsTownPet[type] && flag26 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(1200) == 0 && (type == 208 || (BirthdayParty.PartyIsUp && NPCID.Sets.AttackType[type] == NPCID.Sets.AttackType[208])))
             {
                 int num100 = 300;
                 int num101 = 150;
                 for (int num102 = 0; num102 < 255; num102++)
                 {
                     Player player = Main.player[num102];
                     if (player.active && !player.dead && player.Distance(base.Center) < (float)num101 && Collision.CanHitLine(base.Top, 0, 0, player.Top, 0, 0))
                     {
                         int num103 = (position.X < player.position.X).ToDirectionInt();
                         ai[0] = 6f;
                         ai[1] = num100;
                         ai[2] = num102;
                         direction = num103;
                         netUpdate = true;
                         break;
                     }
                 }
             }
             else if (flag26 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(600) == 0 && type == 550)
             {
                 int num104 = 300;
                 int num105 = 150;
                 for (int num106 = 0; num106 < 255; num106++)
                 {
                     Player player2 = Main.player[num106];
                     if (player2.active && !player2.dead && player2.Distance(base.Center) < (float)num105 && Collision.CanHitLine(base.Top, 0, 0, player2.Top, 0, 0))
                     {
                         int num107 = (position.X < player2.position.X).ToDirectionInt();
                         ai[0] = 18f;
                         ai[1] = num104;
                         ai[2] = num106;
                         direction = num107;
                         netUpdate = true;
                         break;
                     }
                 }
             }
             else if (!NPCID.Sets.IsTownPet[type] && flag26 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(1800) == 0)
             {
                 ai[0] = 2f;
                 ai[1] = 45 * Main.rand.Next(1, 2);
                 netUpdate = true;
             }
             else if (flag26 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(600) == 0 && type == 229 && !flag14)
             {
                 ai[0] = 11f;
                 ai[1] = 30 * Main.rand.Next(1, 4);
                 netUpdate = true;
             }
             else if (flag26 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(1200) == 0)
             {
                 int num108 = 220;
                 int num109 = 150;
                 for (int num110 = 0; num110 < 255; num110++)
                 {
                     Player player3 = Main.player[num110];
                     if (player3.CanBeTalkedTo && player3.Distance(base.Center) < (float)num109 && Collision.CanHitLine(base.Top, 0, 0, player3.Top, 0, 0))
                     {
                         int num111 = (position.X < player3.position.X).ToDirectionInt();
                         ai[0] = 7f;
                         ai[1] = num108;
                         ai[2] = num110;
                         direction = num111;
                         netUpdate = true;
                         break;
                     }
                 }
             }
             else if (flag26 && ai[0] == 1f && velocity.Y == 0f && num > 0 && Main.rand.Next(num) == 0)
             {
                 Point point = (base.Bottom + Vector2.UnitY * -2f).ToTileCoordinates();
                 bool flag30 = WorldGen.InWorld(point.X, point.Y, 1);
                 if (flag30)
                 {
                     for (int num112 = 0; num112 < 200; num112++)
                     {
                         if (Main.npc[num112].active && Main.npc[num112].aiStyle == 7 && Main.npc[num112].townNPC && Main.npc[num112].ai[0] == 5f && (Main.npc[num112].Bottom + Vector2.UnitY * -2f).ToTileCoordinates() == point)
{
                             flag30 = false;
                             break;
                         }
                     }
                     for (int num113 = 0; num113 < 255; num113++)
                     {
                         if (Main.player[num113].active && Main.player[num113].sitting.isSitting && Main.player[num113].Center.ToTileCoordinates() == point)
{
                             flag30 = false;
                             break;
                         }
                     }
                 }
                 if (flag30)
                 {
                     Tile tile2 = Main.tile[point.X, point.Y];
                     flag30 = tile2.type == 15 || tile2.type == 497;
                     if (flag30 && tile2.type == 15 && tile2.frameY >= 1080 && tile2.frameY <= 1098)
                     {
                         flag30 = false;
                     }
                     if (flag30)
                     {
                         ai[0] = 5f;
                         ai[1] = 900 + Main.rand.Next(10800);
                         direction = ((tile2.frameX != 0) ? 1 : (-1));
                         base.Bottom = new Vector2(point.X * 16 + 8 + 2 * direction, point.Y * 16 + 16);
                         velocity = Vector2.Zero;
                         localAI[3] = 0f;
                         netUpdate = true;
                     }
                 }
             }
             else if (flag26 && ai[0] == 1f && velocity.Y == 0f && Main.rand.Next(600) == 0 && Utils.PlotTileLine(base.Top, base.Bottom, width, DelegateMethods.SearchAvoidedByNPCs))
             {
                 Point point2 = (base.Center + new Vector2(direction * 10, 0f)).ToTileCoordinates();
                 bool flag31 = WorldGen.InWorld(point2.X, point2.Y, 1);
                 if (flag31)
                 {
                     Tile tileSafely7 = Framing.GetTileSafely(point2.X, point2.Y);
                     if (!tileSafely7.nactive() || !TileID.Sets.InteractibleByNPCs[tileSafely7.type])
                     {
                         flag31 = false;
                     }
                 }
                 if (flag31)
                 {
                     ai[0] = 9f;
                     ai[1] = 40 + Main.rand.Next(90);
                     velocity = Vector2.Zero;
                     localAI[3] = 0f;
                     netUpdate = true;
                 }
             }
             if (Main.netMode != 1 && ai[0] < 2f && velocity.Y == 0f && type == 18 && breath > 0)
             {
                 int num114 = -1;
                 for (int num115 = 0; num115 < 200; num115++)
                 {
                     NPC nPC6 = Main.npc[num115];
                     if (nPC6.active && nPC6.townNPC && nPC6.life != nPC6.lifeMax && (num114 == -1 || nPC6.lifeMax - nPC6.life > Main.npc[num114].lifeMax - Main.npc[num114].life) && Collision.CanHitLine(position, width, height, nPC6.position, nPC6.width, nPC6.height) && Distance(nPC6.Center) < 500f)
                     {
                         num114 = num115;
                     }
                 }
                 if (num114 != -1)
                 {
                     ai[0] = 13f;
                     ai[1] = 34f;
                     ai[2] = num114;
                     localAI[3] = 0f;
                     direction = ((position.X < Main.npc[num114].position.X) ? 1 : (-1));
                     netUpdate = true;
                 }
             }
             if (flag27 && velocity.Y == 0f && NPCID.Sets.AttackType[type] == 0 && NPCID.Sets.AttackAverageChance[type] > 0 && Main.rand.Next(NPCID.Sets.AttackAverageChance[type] * 2) == 0)
             {
                 int num116 = NPCID.Sets.AttackTime[type];
                 int num117 = ((num11 == 1) ? num13 : num12);
                 int num118 = ((num11 == 1) ? num12 : num13);
                 if (num117 != -1 && !Collision.CanHit(base.Center, 0, 0, Main.npc[num117].Center, 0, 0))
                 {
                     num117 = ((num118 == -1 || !Collision.CanHit(base.Center, 0, 0, Main.npc[num118].Center, 0, 0)) ? (-1) : num118);
                 }
                 bool flag32 = num117 != -1;
                 if (flag32 && type == 633)
                 {
                     flag32 = Vector2.Distance(base.Center, Main.npc[num117].Center) <= 50f;
                 }
                 if (flag32)
                 {
                     localAI[2] = ai[0];
                     ai[0] = 10f;
                     ai[1] = num116;
                     ai[2] = 0f;
                     localAI[3] = 0f;
                     direction = ((position.X < Main.npc[num117].position.X) ? 1 : (-1));
                     netUpdate = true;
                 }
             }
             else if (flag27 && velocity.Y == 0f && NPCID.Sets.AttackType[type] == 1 && NPCID.Sets.AttackAverageChance[type] > 0 && Main.rand.Next(NPCID.Sets.AttackAverageChance[type] * 2) == 0)
             {
                 int num119 = NPCID.Sets.AttackTime[type];
                 int num120 = ((num11 == 1) ? num13 : num12);
                 int num121 = ((num11 == 1) ? num12 : num13);
                 if (num120 != -1 && !Collision.CanHitLine(base.Center, 0, 0, Main.npc[num120].Center, 0, 0))
                 {
                     num120 = ((num121 == -1 || !Collision.CanHitLine(base.Center, 0, 0, Main.npc[num121].Center, 0, 0)) ? (-1) : num121);
                 }
                 if (num120 != -1)
                 {
                     Vector2 vector8 = DirectionTo(Main.npc[num120].Center);
                     if (vector8.Y <= 0.5f && vector8.Y >= -0.5f)
                     {
                         localAI[2] = ai[0];
                         ai[0] = 12f;
                         ai[1] = num119;
                         ai[2] = vector8.Y;
                         localAI[3] = 0f;
                         direction = ((position.X < Main.npc[num120].position.X) ? 1 : (-1));
                         netUpdate = true;
                     }
                 }
             }
             if (flag27 && velocity.Y == 0f && NPCID.Sets.AttackType[type] == 2 && NPCID.Sets.AttackAverageChance[type] > 0 && Main.rand.Next(NPCID.Sets.AttackAverageChance[type] * 2) == 0)
             {
                 int num122 = NPCID.Sets.AttackTime[type];
                 int num123 = ((num11 == 1) ? num13 : num12);
                 int num124 = ((num11 == 1) ? num12 : num13);
                 if (num123 != -1 && !Collision.CanHitLine(base.Center, 0, 0, Main.npc[num123].Center, 0, 0))
                 {
                     num123 = ((num124 == -1 || !Collision.CanHitLine(base.Center, 0, 0, Main.npc[num124].Center, 0, 0)) ? (-1) : num124);
                 }
                 if (num123 != -1)
                 {
                     localAI[2] = ai[0];
                     ai[0] = 14f;
                     ai[1] = num122;
                     ai[2] = 0f;
                     localAI[3] = 0f;
                     direction = ((position.X < Main.npc[num123].position.X) ? 1 : (-1));
                     netUpdate = true;
                 }
                 else if (type == 20)
                 {
                     localAI[2] = ai[0];
                     ai[0] = 14f;
                     ai[1] = num122;
                     ai[2] = 0f;
                     localAI[3] = 0f;
                     netUpdate = true;
                 }
             }
             if (flag27 && velocity.Y == 0f && NPCID.Sets.AttackType[type] == 3 && NPCID.Sets.AttackAverageChance[type] > 0 && Main.rand.Next(NPCID.Sets.AttackAverageChance[type] * 2) == 0)
             {
                 int num125 = NPCID.Sets.AttackTime[type];
                 int num126 = ((num11 == 1) ? num13 : num12);
                 int num127 = ((num11 == 1) ? num12 : num13);
                 if (num126 != -1 && !Collision.CanHit(base.Center, 0, 0, Main.npc[num126].Center, 0, 0))
                 {
                     num126 = ((num127 == -1 || !Collision.CanHit(base.Center, 0, 0, Main.npc[num127].Center, 0, 0)) ? (-1) : num127);
                 }
                 if (num126 != -1)
                 {
                     localAI[2] = ai[0];
                     ai[0] = 15f;
                     ai[1] = num125;
                     ai[2] = 0f;
                     localAI[3] = 0f;
                     direction = ((position.X < Main.npc[num126].position.X) ? 1 : (-1));
                     netUpdate = true;
                 }
             }
         }
         if (type == 681)
         {
             float R = 0f;
             float G = 0f;
             float B = 0f;
             TorchID.TorchColor(23, out R, out G, out B);
             float num128 = 0.35f;
             R *= num128;
             G *= num128;
             B *= num128;
             Lighting.AddLight(base.Center, R, G, B);
         }
         if (type == 683 || type == 687)
         {
             float num129 = Utils.WrappedLerp(0.75f, 1f, (float)Main.timeForVisualEffects % 120f / 120f);
             Lighting.AddLight(base.Center, 0.25f * num129, 0.25f * num129, 0.1f * num129);
         }
     }
References Entity.active, Lighting.AddLight(), AnchoredEntitiesCollection.AddNPC(), ai, Projectile.ai, AI_007_AttemptToPlayIdleAnimationsForPets(), AI_007_FindGoodRestingSpot(), AI_007_TownEntities_CheckIfWillDrown(), AI_007_TownEntities_GetWalkPrediction(), AI_007_TownEntities_IsInAGoodRestingSpot(), AI_007_TownEntities_Shimmer_TeleportToLandingSpot(), AI_007_TownEntities_TeleportToHome(), AI_007_TryForcingSitting(), aiStyle, NPCID.Sets.AttackAverageChance, NPCID.Sets.AttackTime, NPCID.Sets.AttackType, B, Entity.Bottom, breath, ParticleOrchestrator.BroadcastParticleSpawn(), CanBeChasedBy(), CanBeTalkedTo, Player.CanBeTalkedTo, Collision.CanHit(), Collision.CanHitLine(), CanTalk, NPCAimedTarget.Center, Entity.Center, closeDoor, WorldGen.CloseDoor(), collideX, Color, combatBookVolumeTwoWasUsed, combatBookWasUsed, NPCID.Count, damage, NPCID.Sets.DangerDetectRange, Main.dayTime, Player.dead, defDefense, defense, Entity.direction, Entity.DirectionTo(), directionY, Entity.Distance(), dontTakeDamage, doorX, doorY, downedAncientCultist, downedBoss1, downedBoss2, downedBoss3, downedEmpressOfLight, downedGolemBoss, downedMechBoss1, downedMechBoss2, downedMechBoss3, downedPlantBoss, downedQueenBee, downedQueenSlime, Collision.DrownCollision(), dryadWard, Main.dungeonX, Main.dungeonY, Main.eclipse, Main.expertMode, FindBuffIndex(), frameCounter, Tile.frameX, Tile.frameY, friendly, G, Main.GameModeInfo, GetMagicAuraColor(), GetSpawnSource_ForProjectile(), GetSwingStats(), GetTargetData(), Framing.GetTileSafely(), Collision.GetWaterLine(), gfxOffY, GivenName, Main.hardMode, Entity.height, Entity.Hitbox, HitEffect(), homeless, homeTileX, homeTileY, Entity.honeyWet, Main.hslToRgb(), immune, TileID.Sets.InteractibleByNPCs, WorldGen.InWorld(), isLikeATownNPC, IsShimmerVariant, PlayerSittingHelper.isSitting, NPCID.Sets.IsTownPet, NPCID.Sets.IsTownSlime, Entity.lavaWet, lazyNPCOwnedProjectileSearchArray, life, lifeMax, Tile.liquid, localAI, Main.masterMode, Main.maxTilesX, Main.myPlayer, Tile.nactive(), Main.netMode, netUpdate, Dust.NewDustPerfect(), Projectile.NewProjectile(), UnifiedRandom.Next(), Projectile.noDropItem, noTileCollide, Main.npc, Projectile.npcProj, WorldGen.OpenDoor(), BirthdayParty.PartyIsUp, Main.player, SoundEngine.PlaySound(), Utils.PlotTileLine(), Entity.position, NPCID.Sets.PrettySafe, Main.projectile, R, Main.raining, Main.rand, Utils.RandomVector2(), Utils.Remap(), ParticleOrchestrator.RequestParticleSpawn(), safeRangeX, safeRangeY, savedAngler, savedBartender, savedGoblin, savedGolfer, savedMech, savedStylist, savedTaxCollector, savedWizard, DelegateMethods.SearchAvoidedByNPCs(), NetMessage.SendData(), sHeight, WorldGen.ShiftTallGate(), ShimmeredTownNPCs, shimmering, shimmerTransparency, Entity.shimmerWet, ShouldBestiaryGirlBeLycantrope(), Player.sitting, Main.sittingManager, Entity.Size, NPCID.Sets.Skeletons, Main.slimeRain, WorldGen.SolidTile(), Collision.SolidTiles(), Collision.SolidTilesVersatile(), Main.spawnTileX, Main.spawnTileY, spriteDirection, Collision.StepDown(), stepSpeed, Collision.StepUp(), StrikeNPCNoInteraction(), sWidth, Player.talkNPC, target, TargetClosest(), taxCollector, Teleport(), Main.tile, Main.tileDungeon, Main.tileSolid, Main.tileSolidTop, Main.timeForVisualEffects, Projectile.timeLeft, Entity.Top, Tile.topSlope(), TorchID.TorchColor(), NPCID.Sets.TownCritter, townNPC, GameModeData.TownNPCDamageMultiplier, townNpcVariationIndex, Transform(), TweakSwingStats(), type, Projectile.type, Tile.type, UpdateHomeTileState(), Entity.velocity, Entity.wet, Collision.WetCollision(), Entity.whoAmI, Entity.width, Utils.WrappedLerp(), and Main.xMas.
Referenced by AI().