Terraria: NPC.HasLuckTextForWizard
HasLuckTextForWizard()
bool NPC.HasLuckTextForWizard (out string specialEventText) inline
     {
         specialEventText = null;
         object obj = Lang.CreateDialogSubstitutionObject(this);
         if (Main.rand.Next(3) == 0)
         {
             float normalizedLuck = Main.player[Main.myPlayer].NormalizedLuck;
             if (normalizedLuck == 0f)
             {
                 return false;
             }
             string text = null;
             text = ((normalizedLuck < -0.6f) ? "WizardSpecialText.LuckIsCursed" : ((normalizedLuck < -0.4f) ? "WizardSpecialText.LuckIsTerrible" : ((normalizedLuck < -0.2f) ? "WizardSpecialText.LuckIsPoor" : ((normalizedLuck < 0f) ? "WizardSpecialText.LuckIsBad" : ((normalizedLuck < 0.25f) ? "WizardSpecialText.LuckIsGood" : ((normalizedLuck < 0.5f) ? "WizardSpecialText.LuckIsGreat" : ((!(normalizedLuck < 0.75f)) ? "WizardSpecialText.LuckIsGodly" : "WizardSpecialText.LuckIsAmazing")))))));
             specialEventText = Language.SelectRandom(Lang.CreateDialogFilter(text)).FormatWith(obj);
             return true;
         }
         return false;
     }
References Lang.CreateDialogFilter(), Lang.CreateDialogSubstitutionObject(), Main.myPlayer, UnifiedRandom.Next(), Player.NormalizedLuck, Main.player, Main.rand, and Language.SelectRandom().