Terraria: NPC.FindCattailTop
FindCattailTop()
static bool NPC.FindCattailTop (int landX, int landY, out int cattailX, out int cattailY) inline static
     {
         cattailX = landX;
         cattailY = landY;
         if (!WorldGen.InWorld(landX, landY, 31))
         {
             return false;
         }
         int num = 1;
         for (int i = landX - 30; i <= landX + 30; i++)
         {
             for (int j = landY - 20; j <= landY + 20; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile != null && tile.active() && tile.type == 519 && tile.frameX >= 180 && Main.rand.Next(num) == 0)
                 {
                     cattailX = i;
                     cattailY = j;
                     num++;
                 }
             }
         }
         if (cattailX != landX || cattailY != landY)
         {
             return true;
         }
         return false;
     }
References Tile.active(), Tile.frameX, WorldGen.InWorld(), UnifiedRandom.Next(), Main.rand, Main.tile, and Tile.type.
Referenced by AI_114_Dragonflies().