Terraria: NPC.AI_069_DukeFishron
AI_069_DukeFishron()
void NPC.AI_069_DukeFishron () inline private
     {
         bool expertMode = Main.expertMode;
         float num = (expertMode ? 1.2f : 1f);
         bool flag = (double)life <= (double)lifeMax * 0.5;
         bool flag2 = expertMode && (double)life <= (double)lifeMax * 0.15;
         bool flag3 = ai[0] > 4f;
         bool flag4 = ai[0] > 9f;
         bool flag5 = ai[3] < 10f;
         if (flag4)
         {
             damage = (int)((float)defDamage * 1.1f * num);
             defense = 0;
         }
         else if (flag3)
         {
             damage = (int)((float)defDamage * 1.2f * num);
             defense = (int)((float)defDefense * 0.8f);
         }
         else
         {
             damage = defDamage;
             defense = defDefense;
         }
         int num2 = (expertMode ? 40 : 60);
         float num3 = (expertMode ? 0.55f : 0.45f);
         float num4 = (expertMode ? 8.5f : 7.5f);
         if (flag4)
         {
             num3 = 0.7f;
             num4 = 12f;
             num2 = 30;
         }
         else if (flag3 && flag5)
         {
             num3 = (expertMode ? 0.6f : 0.5f);
             num4 = (expertMode ? 10f : 8f);
             num2 = (expertMode ? 40 : 20);
         }
         else if (flag5 && !flag3 && !flag4)
         {
             num2 = 30;
         }
         int num5 = (expertMode ? 28 : 30);
         float num6 = (expertMode ? 17f : 16f);
         if (flag4)
         {
             num5 = 25;
             num6 = 27f;
         }
         else if (flag5 && flag3)
         {
             num5 = (expertMode ? 27 : 30);
             if (expertMode)
             {
                 num6 = 21f;
             }
         }
         int num7 = 80;
         int num8 = 4;
         float num9 = 0.3f;
         float num10 = 5f;
         int num11 = 90;
         int num12 = 180;
         int num13 = 180;
         int num14 = 30;
         int num15 = 120;
         int num16 = 4;
         float num17 = 6f;
         float num18 = 20f;
         float num19 = (float)Math.PI * 2f / (float)(num15 / 2);
         int num20 = 75;
         Vector2 center = base.Center;
         Player player = Main.player[target];
         if (target < 0 || target == 255 || player.dead || !player.active || Vector2.Distance(player.Center, center) > 5600f)
         {
             TargetClosest();
             player = Main.player[target];
             netUpdate = true;
         }
         if (player.dead || Vector2.Distance(player.Center, center) > 5600f)
         {
             velocity.Y -= 0.4f;
             EncourageDespawn(10);
             if (ai[0] > 4f)
             {
                 ai[0] = 5f;
             }
             else
             {
                 ai[0] = 0f;
             }
             ai[2] = 0f;
         }
         bool flag6 = player.position.Y < 800f || (double)player.position.Y > Main.worldSurface * 16.0 || (player.position.X > 6400f && player.position.X < (float)(Main.maxTilesX * 16 - 6400));
         if (flag6)
         {
             num2 = 10;
             damage = defDamage * 2;
             defense = defDefense * 2;
             num6 += 6f;
         }
         bool flag7 = true;
         if (localAI[0] == 0f)
         {
             localAI[0] = 1f;
             alpha = 255;
             rotation = 0f;
             if (Main.netMode != 1)
             {
                 ai[0] = -1f;
                 netUpdate = true;
             }
         }
         float num21 = (float)Math.Atan2(player.Center.Y - center.Y, player.Center.X - center.X);
         if (spriteDirection == 1)
         {
             num21 += (float)Math.PI;
         }
         if (num21 < 0f)
         {
             num21 += (float)Math.PI * 2f;
         }
         if (num21 > (float)Math.PI * 2f)
         {
             num21 -= (float)Math.PI * 2f;
         }
         if (ai[0] == -1f)
         {
             num21 = 0f;
         }
         if (ai[0] == 3f)
         {
             num21 = 0f;
         }
         if (ai[0] == 4f)
         {
             num21 = 0f;
         }
         if (ai[0] == 8f)
         {
             num21 = 0f;
         }
         float num22 = 0.04f;
         if (ai[0] == 1f || ai[0] == 6f)
         {
             num22 = 0f;
         }
         if (ai[0] == 7f)
         {
             num22 = 0f;
         }
         if (ai[0] == 3f)
         {
             num22 = 0.01f;
         }
         if (ai[0] == 4f)
         {
             num22 = 0.01f;
         }
         if (ai[0] == 8f)
         {
             num22 = 0.01f;
         }
         if (rotation < num21)
         {
             if ((double)(num21 - rotation) > Math.PI)
             {
                 rotation -= num22;
             }
             else
             {
                 rotation += num22;
             }
         }
         if (rotation > num21)
         {
             if ((double)(rotation - num21) > Math.PI)
             {
                 rotation += num22;
             }
             else
             {
                 rotation -= num22;
             }
         }
         if (rotation > num21 - num22 && rotation < num21 + num22)
         {
             rotation = num21;
         }
         if (rotation < 0f)
         {
             rotation += (float)Math.PI * 2f;
         }
         if (rotation > (float)Math.PI * 2f)
         {
             rotation -= (float)Math.PI * 2f;
         }
         if (rotation > num21 - num22 && rotation < num21 + num22)
         {
             rotation = num21;
         }
         if (ai[0] != -1f && ai[0] < 9f)
         {
             if (Collision.SolidCollision(position, width, height))
             {
                 alpha += 15;
             }
             else
             {
                 alpha -= 15;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (alpha > 150)
             {
                 alpha = 150;
             }
         }
         if (ai[0] == -1f)
         {
             flag7 = false;
             velocity *= 0.98f;
             int num23 = Math.Sign(player.Center.X - center.X);
             if (num23 != 0)
             {
                 direction = num23;
                 spriteDirection = -direction;
             }
             if (ai[2] > 20f)
             {
                 velocity.Y = -2f;
                 alpha -= 5;
                 if (Collision.SolidCollision(position, width, height))
                 {
                     alpha += 15;
                 }
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
                 if (alpha > 150)
                 {
                     alpha = 150;
                 }
             }
             if (ai[2] == (float)(num11 - 30))
             {
                 int num24 = 36;
                 for (int i = 0; i < num24; i++)
                 {
                     Vector2 vector = (Vector2.Normalize(velocity) * new Vector2((float)width / 2f, height) * 0.75f * 0.5f).RotatedBy((float)(i - (num24 / 2 - 1)) * ((float)Math.PI * 2f) / (float)num24) + base.Center;
                     Vector2 vector2 = vector - base.Center;
                     int num25 = Dust.NewDust(vector + vector2, 0, 0, 172, vector2.X * 2f, vector2.Y * 2f, 100, default(Color), 1.4f);
                     Main.dust[num25].noGravity = true;
                     Main.dust[num25].noLight = true;
                     Main.dust[num25].velocity = Vector2.Normalize(vector2) * 3f;
                 }
                 SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num20)
             {
                 ai[0] = 0f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 0f && !player.dead)
         {
             if (ai[1] == 0f)
             {
                 ai[1] = 300 * Math.Sign((center - player.Center).X);
             }
             Vector2 vector3 = Vector2.Normalize(player.Center + new Vector2(ai[1], -200f) - center - velocity) * num4;
             if (velocity.X < vector3.X)
             {
                 velocity.X += num3;
                 if (velocity.X < 0f && vector3.X > 0f)
                 {
                     velocity.X += num3;
                 }
             }
             else if (velocity.X > vector3.X)
             {
                 velocity.X -= num3;
                 if (velocity.X > 0f && vector3.X < 0f)
                 {
                     velocity.X -= num3;
                 }
             }
             if (velocity.Y < vector3.Y)
             {
                 velocity.Y += num3;
                 if (velocity.Y < 0f && vector3.Y > 0f)
                 {
                     velocity.Y += num3;
                 }
             }
             else if (velocity.Y > vector3.Y)
             {
                 velocity.Y -= num3;
                 if (velocity.Y > 0f && vector3.Y < 0f)
                 {
                     velocity.Y -= num3;
                 }
             }
             int num26 = Math.Sign(player.Center.X - center.X);
             if (num26 != 0)
             {
                 if (ai[2] == 0f && num26 != direction)
                 {
                     rotation += (float)Math.PI;
                 }
                 direction = num26;
                 if (spriteDirection != -direction)
                 {
                     rotation += (float)Math.PI;
                 }
                 spriteDirection = -direction;
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num2)
             {
                 int num27 = 0;
                 switch ((int)ai[3])
                 {
                 case 0:
                 case 1:
                 case 2:
                 case 3:
                 case 4:
                 case 5:
                 case 6:
                 case 7:
                 case 8:
                 case 9:
                     num27 = 1;
                     break;
                 case 10:
                     ai[3] = 1f;
                     num27 = 2;
                     break;
                 case 11:
                     ai[3] = 0f;
                     num27 = 3;
                     break;
                 }
                 if (flag6 && num27 == 2)
                 {
                     num27 = 3;
                 }
                 if (flag)
                 {
                     num27 = 4;
                 }
                 switch (num27)
                 {
                 case 1:
                     ai[0] = 1f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     velocity = Vector2.Normalize(player.Center - center) * num6;
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                     if (num26 != 0)
                     {
                         direction = num26;
                         if (spriteDirection == 1)
{
                             rotation += (float)Math.PI;
                         }
                         spriteDirection = -direction;
                     }
                     break;
                 case 2:
                     ai[0] = 2f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     break;
                 case 3:
                     ai[0] = 3f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     if (flag6)
                     {
                         ai[2] = num11 - 40;
                     }
                     break;
                 case 4:
                     ai[0] = 4f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     break;
                 }
                 netUpdate = true;
             }
         }
         else if (ai[0] == 1f)
         {
             int num28 = 7;
             for (int j = 0; j < num28; j++)
             {
                 Vector2 vector4 = (Vector2.Normalize(velocity) * new Vector2((float)(width + 50) / 2f, height) * 0.75f).RotatedBy((double)(j - (num28 / 2 - 1)) * Math.PI / (double)(float)num28) + center;
                 Vector2 vector5 = ((float)(Main.rand.NextDouble() * 3.1415927410125732) - (float)Math.PI / 2f).ToRotationVector2() * Main.rand.Next(3, 8);
                 int num29 = Dust.NewDust(vector4 + vector5, 0, 0, 172, vector5.X * 2f, vector5.Y * 2f, 100, default(Color), 1.4f);
                 Main.dust[num29].noGravity = true;
                 Main.dust[num29].noLight = true;
                 Main.dust[num29].velocity /= 4f;
                 Main.dust[num29].velocity -= velocity;
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num5)
             {
                 ai[0] = 0f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] += 2f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 2f)
         {
             if (ai[1] == 0f)
             {
                 ai[1] = 300 * Math.Sign((center - player.Center).X);
             }
             Vector2 vector6 = Vector2.Normalize(player.Center + new Vector2(ai[1], -200f) - center - velocity) * num10;
             if (velocity.X < vector6.X)
             {
                 velocity.X += num9;
                 if (velocity.X < 0f && vector6.X > 0f)
                 {
                     velocity.X += num9;
                 }
             }
             else if (velocity.X > vector6.X)
             {
                 velocity.X -= num9;
                 if (velocity.X > 0f && vector6.X < 0f)
                 {
                     velocity.X -= num9;
                 }
             }
             if (velocity.Y < vector6.Y)
             {
                 velocity.Y += num9;
                 if (velocity.Y < 0f && vector6.Y > 0f)
                 {
                     velocity.Y += num9;
                 }
             }
             else if (velocity.Y > vector6.Y)
             {
                 velocity.Y -= num9;
                 if (velocity.Y > 0f && vector6.Y < 0f)
                 {
                     velocity.Y -= num9;
                 }
             }
             if (ai[2] == 0f)
             {
                 SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
             }
             if (ai[2] % (float)num8 == 0f)
             {
                 SoundEngine.PlaySound(4, (int)base.Center.X, (int)base.Center.Y, 19);
                 if (Main.netMode != 1)
                 {
                     Vector2 vector7 = Vector2.Normalize(player.Center - center) * (width + 20) / 2f + center;
                     NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)vector7.X, (int)vector7.Y + 45, 371);
                 }
             }
             int num30 = Math.Sign(player.Center.X - center.X);
             if (num30 != 0)
             {
                 direction = num30;
                 if (spriteDirection != -direction)
                 {
                     rotation += (float)Math.PI;
                 }
                 spriteDirection = -direction;
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num7)
             {
                 ai[0] = 0f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 3f)
         {
             velocity *= 0.98f;
             velocity.Y = MathHelper.Lerp(velocity.Y, 0f, 0.02f);
             if (ai[2] == (float)(num11 - 30))
             {
                 SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 9);
             }
             if (Main.netMode != 1 && ai[2] == (float)(num11 - 30))
             {
                 Vector2 vector8 = rotation.ToRotationVector2() * (Vector2.UnitX * direction) * (width + 20) / 2f + center;
                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector8.X, vector8.Y, direction * 2, 8f, 385, 0, 0f, Main.myPlayer);
                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector8.X, vector8.Y, -direction * 2, 8f, 385, 0, 0f, Main.myPlayer);
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num11)
             {
                 ai[0] = 0f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 4f)
         {
             flag7 = false;
             velocity *= 0.98f;
             velocity.Y = MathHelper.Lerp(velocity.Y, 0f, 0.02f);
             if (ai[2] == (float)(num12 - 60))
             {
                 SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num12)
             {
                 ai[0] = 5f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] = 0f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 5f && !player.dead)
         {
             if (ai[1] == 0f)
             {
                 ai[1] = 300 * Math.Sign((center - player.Center).X);
             }
             Vector2 vector9 = Vector2.Normalize(player.Center + new Vector2(ai[1], -200f) - center - velocity) * num4;
             if (velocity.X < vector9.X)
             {
                 velocity.X += num3;
                 if (velocity.X < 0f && vector9.X > 0f)
                 {
                     velocity.X += num3;
                 }
             }
             else if (velocity.X > vector9.X)
             {
                 velocity.X -= num3;
                 if (velocity.X > 0f && vector9.X < 0f)
                 {
                     velocity.X -= num3;
                 }
             }
             if (velocity.Y < vector9.Y)
             {
                 velocity.Y += num3;
                 if (velocity.Y < 0f && vector9.Y > 0f)
                 {
                     velocity.Y += num3;
                 }
             }
             else if (velocity.Y > vector9.Y)
             {
                 velocity.Y -= num3;
                 if (velocity.Y > 0f && vector9.Y < 0f)
                 {
                     velocity.Y -= num3;
                 }
             }
             int num31 = Math.Sign(player.Center.X - center.X);
             if (num31 != 0)
             {
                 if (ai[2] == 0f && num31 != direction)
                 {
                     rotation += (float)Math.PI;
                 }
                 direction = num31;
                 if (spriteDirection != -direction)
                 {
                     rotation += (float)Math.PI;
                 }
                 spriteDirection = -direction;
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num2)
             {
                 int num32 = 0;
                 switch ((int)ai[3])
                 {
                 case 0:
                 case 1:
                 case 2:
                 case 3:
                 case 4:
                 case 5:
                     num32 = 1;
                     break;
                 case 6:
                     ai[3] = 1f;
                     num32 = 2;
                     break;
                 case 7:
                     ai[3] = 0f;
                     num32 = 3;
                     break;
                 }
                 if (flag2)
                 {
                     num32 = 4;
                 }
                 if (flag6 && num32 == 2)
                 {
                     num32 = 3;
                 }
                 switch (num32)
                 {
                 case 1:
                     ai[0] = 6f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     velocity = Vector2.Normalize(player.Center - center) * num6;
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                     if (num31 != 0)
                     {
                         direction = num31;
                         if (spriteDirection == 1)
{
                             rotation += (float)Math.PI;
                         }
                         spriteDirection = -direction;
                     }
                     break;
                 case 2:
                     velocity = Vector2.Normalize(player.Center - center) * num18;
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                     if (num31 != 0)
                     {
                         direction = num31;
                         if (spriteDirection == 1)
{
                             rotation += (float)Math.PI;
                         }
                         spriteDirection = -direction;
                     }
                     ai[0] = 7f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     break;
                 case 3:
                     ai[0] = 8f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     break;
                 case 4:
                     ai[0] = 9f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     break;
                 }
                 netUpdate = true;
             }
         }
         else if (ai[0] == 6f)
         {
             int num33 = 7;
             for (int k = 0; k < num33; k++)
             {
                 Vector2 vector10 = (Vector2.Normalize(velocity) * new Vector2((float)(width + 50) / 2f, height) * 0.75f).RotatedBy((double)(k - (num33 / 2 - 1)) * Math.PI / (double)(float)num33) + center;
                 Vector2 vector11 = ((float)(Main.rand.NextDouble() * 3.1415927410125732) - (float)Math.PI / 2f).ToRotationVector2() * Main.rand.Next(3, 8);
                 int num34 = Dust.NewDust(vector10 + vector11, 0, 0, 172, vector11.X * 2f, vector11.Y * 2f, 100, default(Color), 1.4f);
                 Main.dust[num34].noGravity = true;
                 Main.dust[num34].noLight = true;
                 Main.dust[num34].velocity /= 4f;
                 Main.dust[num34].velocity -= velocity;
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num5)
             {
                 ai[0] = 5f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] += 2f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 7f)
         {
             if (ai[2] == 0f)
             {
                 SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
             }
             if (ai[2] % (float)num16 == 0f)
             {
                 SoundEngine.PlaySound(4, (int)base.Center.X, (int)base.Center.Y, 19);
                 if (Main.netMode != 1)
                 {
                     Vector2 vector12 = Vector2.Normalize(velocity) * (width + 20) / 2f + center;
                     int num35 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)vector12.X, (int)vector12.Y + 45, 371);
                     Main.npc[num35].target = target;
                     Main.npc[num35].velocity = Vector2.Normalize(velocity).RotatedBy((float)Math.PI / 2f * (float)direction) * num17;
                     Main.npc[num35].netUpdate = true;
                     Main.npc[num35].ai[3] = (float)Main.rand.Next(80, 121) / 100f;
                 }
             }
             velocity = velocity.RotatedBy((0f - num19) * (float)direction);
             rotation -= num19 * (float)direction;
             ai[2] += 1f;
             if (ai[2] >= (float)num15)
             {
                 ai[0] = 5f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 8f)
         {
             velocity *= 0.98f;
             velocity.Y = MathHelper.Lerp(velocity.Y, 0f, 0.02f);
             if (ai[2] == (float)(num11 - 30))
             {
                 SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
             }
             if (Main.netMode != 1 && ai[2] == (float)(num11 - 30))
             {
                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), center.X, center.Y, 0f, 0f, 385, 0, 0f, Main.myPlayer, 1f, target + 1, flag6 ? 1 : 0);
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num11)
             {
                 ai[0] = 5f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 9f)
         {
             flag7 = false;
             if (ai[2] < (float)(num13 - 90))
             {
                 if (Collision.SolidCollision(position, width, height))
                 {
                     alpha += 15;
                 }
                 else
                 {
                     alpha -= 15;
                 }
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
                 if (alpha > 150)
                 {
                     alpha = 150;
                 }
             }
             else if (alpha < 255)
             {
                 alpha += 4;
                 if (alpha > 255)
                 {
                     alpha = 255;
                 }
             }
             velocity *= 0.98f;
             velocity.Y = MathHelper.Lerp(velocity.Y, 0f, 0.02f);
             if (ai[2] == (float)(num13 - 60))
             {
                 SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num13)
             {
                 ai[0] = 10f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] = 0f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 10f && !player.dead)
         {
             chaseable = false;
             if (alpha < 255)
             {
                 alpha += 25;
                 if (alpha > 255)
                 {
                     alpha = 255;
                 }
             }
             if (ai[1] == 0f)
             {
                 ai[1] = 360 * Math.Sign((center - player.Center).X);
             }
             Vector2 desiredVelocity = Vector2.Normalize(player.Center + new Vector2(ai[1], -200f) - center - velocity) * num4;
             SimpleFlyMovement(desiredVelocity, num3);
             int num36 = Math.Sign(player.Center.X - center.X);
             if (num36 != 0)
             {
                 if (ai[2] == 0f && num36 != direction)
                 {
                     rotation += (float)Math.PI;
                     for (int l = 0; l < oldPos.Length; l++)
                     {
                         oldPos[l] = Vector2.Zero;
                     }
                 }
                 direction = num36;
                 if (spriteDirection != -direction)
                 {
                     rotation += (float)Math.PI;
                 }
                 spriteDirection = -direction;
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num2)
             {
                 int num37 = 0;
                 switch ((int)ai[3])
                 {
                 case 0:
                 case 2:
                 case 3:
                 case 5:
                 case 6:
                 case 7:
                     num37 = 1;
                     break;
                 case 1:
                 case 4:
                 case 8:
                     num37 = 2;
                     break;
                 }
                 switch (num37)
                 {
                 case 1:
                     ai[0] = 11f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     velocity = Vector2.Normalize(player.Center - center) * num6;
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                     if (num36 != 0)
                     {
                         direction = num36;
                         if (spriteDirection == 1)
{
                             rotation += (float)Math.PI;
                         }
                         spriteDirection = -direction;
                     }
                     break;
                 case 2:
                     ai[0] = 12f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     break;
                 case 3:
                     ai[0] = 13f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     break;
                 }
                 netUpdate = true;
             }
         }
         else if (ai[0] == 11f)
         {
             chaseable = true;
             alpha -= 25;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             int num38 = 7;
             for (int m = 0; m < num38; m++)
             {
                 Vector2 vector13 = (Vector2.Normalize(velocity) * new Vector2((float)(width + 50) / 2f, height) * 0.75f).RotatedBy((double)(m - (num38 / 2 - 1)) * Math.PI / (double)(float)num38) + center;
                 Vector2 vector14 = ((float)(Main.rand.NextDouble() * 3.1415927410125732) - (float)Math.PI / 2f).ToRotationVector2() * Main.rand.Next(3, 8);
                 int num39 = Dust.NewDust(vector13 + vector14, 0, 0, 172, vector14.X * 2f, vector14.Y * 2f, 100, default(Color), 1.4f);
                 Main.dust[num39].noGravity = true;
                 Main.dust[num39].noLight = true;
                 Main.dust[num39].velocity /= 4f;
                 Main.dust[num39].velocity -= velocity;
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num5)
             {
                 ai[0] = 10f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] += 1f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 12f)
         {
             flag7 = false;
             chaseable = false;
             if (alpha < 255)
             {
                 alpha += 17;
                 if (alpha > 255)
                 {
                     alpha = 255;
                 }
             }
             velocity *= 0.98f;
             velocity.Y = MathHelper.Lerp(velocity.Y, 0f, 0.02f);
             if (ai[2] == (float)(num14 / 2))
             {
                 SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
             }
             if (Main.netMode != 1 && ai[2] == (float)(num14 / 2))
             {
                 if (ai[1] == 0f)
                 {
                     ai[1] = 300 * Math.Sign((center - player.Center).X);
                 }
                 Vector2 vector15 = player.Center + new Vector2(0f - ai[1], -200f);
                 Vector2 vector17 = (base.Center = vector15);
                 center = vector17;
                 int num40 = Math.Sign(player.Center.X - center.X);
                 if (num40 != 0)
                 {
                     if (ai[2] == 0f && num40 != direction)
                     {
                         rotation += (float)Math.PI;
                         for (int n = 0; n < oldPos.Length; n++)
{
                             oldPos[n] = Vector2.Zero;
                         }
                     }
                     direction = num40;
                     if (spriteDirection != -direction)
                     {
                         rotation += (float)Math.PI;
                     }
                     spriteDirection = -direction;
                 }
             }
             ai[2] += 1f;
             if (ai[2] >= (float)num14)
             {
                 ai[0] = 10f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] += 1f;
                 if (ai[3] >= 9f)
                 {
                     ai[3] = 0f;
                 }
                 netUpdate = true;
             }
         }
         else if (ai[0] == 13f)
         {
             if (ai[2] == 0f)
             {
                 SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
             }
             velocity = velocity.RotatedBy((0f - num19) * (float)direction);
             rotation -= num19 * (float)direction;
             ai[2] += 1f;
             if (ai[2] >= (float)num15)
             {
                 ai[0] = 10f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] += 1f;
                 netUpdate = true;
             }
         }
         dontTakeDamage = !flag7;
     }
References Entity.active, ai, alpha, Entity.Center, chaseable, Color, damage, Player.dead, defDamage, defDefense, defense, Entity.direction, dontTakeDamage, Main.dust, EncourageDespawn(), Main.expertMode, GetSpawnSource_ForProjectile(), GetSpawnSourceForNPCFromNPCAI(), Entity.height, life, lifeMax, localAI, Main.maxTilesX, Main.myPlayer, Main.netMode, netUpdate, Dust.NewDust(), NewNPC(), Projectile.NewProjectile(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Dust.noGravity, Dust.noLight, Main.npc, oldPos, Main.player, SoundEngine.PlaySound(), Entity.position, Main.rand, rotation, SimpleFlyMovement(), Collision.SolidCollision(), spriteDirection, target, TargetClosest(), Dust.velocity, Entity.velocity, Entity.width, and Main.worldSurface.
Referenced by AI().