Terraria: NPC.SetDefaults
SetDefaults()
void NPC.SetDefaults (int Type, NPCSpawnParams spawnparams = default(NPCSpawnParams)) inline
References Entity.active, activeTime, ai, aiStyle, alpha, altTexture, behindTiles, betsysCurse, bloodButchered, boss, breath, breathCounter, buffImmune, buffTime, buffType, Item.buyPrice(), CanBeReplacedByOtherNPCs, canDisplayBuffs, canGhostHeal, catchableNPCTempImmunityCounter, catchItem, celled, chaseable, coldDamage, collideX, collideY, Color, color, confused, BuffID.Count, NPCID.Count, damage, daybreak, SoundID.DD2_BetsyDeath, SoundID.DD2_BetsyHurt, SoundID.DD2_CrystalCartImpact, SoundID.DD2_DarkMageDeath, SoundID.DD2_DarkMageHurt, SoundID.DD2_DrakinDeath, SoundID.DD2_DrakinHurt, SoundID.DD2_GoblinBomberDeath, SoundID.DD2_GoblinBomberHurt, SoundID.DD2_GoblinDeath, SoundID.DD2_GoblinHurt, SoundID.DD2_JavelinThrowersDeath, SoundID.DD2_JavelinThrowersHurt, SoundID.DD2_KoboldDeath, SoundID.DD2_KoboldFlyerDeath, SoundID.DD2_KoboldFlyerHurt, SoundID.DD2_KoboldHurt, SoundID.DD2_LightningBugDeath, SoundID.DD2_LightningBugHurt, SoundID.DD2_OgreDeath, SoundID.DD2_OgreHurt, SoundID.DD2_SkeletonDeath, SoundID.DD2_SkeletonHurt, SoundID.DD2_WitherBeastDeath, SoundID.DD2_WitherBeastHurt, SoundID.DD2_WyvernDeath, SoundID.DD2_WyvernHurt, DeathSound, NPCID.Sets.DebuffImmunitySets, Main.dedServ, SoundID.DeerclopsDeath, SoundID.DeerclopsHit, defDamage, defDefense, defense, despawnEncouraged, Entity.direction, dontCountMe, dontTakeDamage, dontTakeDamageFromHostiles, downedGolemBoss, downedMechBossAny, dryadBane, dryadWard, Main.expertMode, extraValue, frame, frameCounter, friendly, Main.GameModeInfo, getGoodAdjustments(), Main.getGoodWorld, getTenthAnniversaryAdjustments(), getZenithSeedAdjustmentsBeforeEverything(), GivenName, Main.hardMode, Entity.height, hide, HitSound, homeless, homeTileX, homeTileY, honeyMovementSpeed, housingCategory, ichor, immortal, Asset< T >.IsLoaded, javelined, justHit, knockBackResist, lavaImmune, lavaMovementSpeed, Entity.lavaWet, LazySetLiquidMovementDD2(), life, lifeMax, lifeRegen, lifeRegenCount, lifeRegenExpectedLossPerSecond, localAI, loveStruck, markedByScytheWhip, Main.masterMode, maxAI, maxBuffs, midas, nameOver, needsUniqueInfoUpdate, netAlways, netID, netOffset, netShimmer, netSkip, netSpam, netStream, netUpdate, netUpdate2, noGravity, noTileCollide, TextureAssets.Npc, Main.npcCatchable, SoundID.NPCDeath1, SoundID.NPCDeath10, SoundID.NPCDeath11, SoundID.NPCDeath12, SoundID.NPCDeath14, SoundID.NPCDeath15, SoundID.NPCDeath16, SoundID.NPCDeath17, SoundID.NPCDeath18, SoundID.NPCDeath19, SoundID.NPCDeath2, SoundID.NPCDeath20, SoundID.NPCDeath21, SoundID.NPCDeath22, SoundID.NPCDeath23, SoundID.NPCDeath24, SoundID.NPCDeath25, SoundID.NPCDeath26, SoundID.NPCDeath27, SoundID.NPCDeath28, SoundID.NPCDeath29, SoundID.NPCDeath3, SoundID.NPCDeath30, SoundID.NPCDeath31, SoundID.NPCDeath32, SoundID.NPCDeath33, SoundID.NPCDeath34, SoundID.NPCDeath35, SoundID.NPCDeath36, SoundID.NPCDeath37, SoundID.NPCDeath38, SoundID.NPCDeath39, SoundID.NPCDeath4, SoundID.NPCDeath40, SoundID.NPCDeath41, SoundID.NPCDeath42, SoundID.NPCDeath43, SoundID.NPCDeath44, SoundID.NPCDeath45, SoundID.NPCDeath46, SoundID.NPCDeath47, SoundID.NPCDeath48, SoundID.NPCDeath49, SoundID.NPCDeath5, SoundID.NPCDeath50, SoundID.NPCDeath51, SoundID.NPCDeath52, SoundID.NPCDeath53, SoundID.NPCDeath54, SoundID.NPCDeath55, SoundID.NPCDeath56, SoundID.NPCDeath57, SoundID.NPCDeath59, SoundID.NPCDeath6, SoundID.NPCDeath60, SoundID.NPCDeath62, SoundID.NPCDeath63, SoundID.NPCDeath64, SoundID.NPCDeath65, SoundID.NPCDeath66, SoundID.NPCDeath7, SoundID.NPCDeath8, SoundID.NPCDeath9, Main.npcFrameCount, SoundID.NPCHit1, SoundID.NPCHit11, SoundID.NPCHit12, SoundID.NPCHit13, SoundID.NPCHit14, SoundID.NPCHit15, SoundID.NPCHit18, SoundID.NPCHit19, SoundID.NPCHit2, SoundID.NPCHit20, SoundID.NPCHit21, SoundID.NPCHit22, SoundID.NPCHit23, SoundID.NPCHit24, SoundID.NPCHit25, SoundID.NPCHit26, SoundID.NPCHit27, SoundID.NPCHit28, SoundID.NPCHit29, SoundID.NPCHit3, SoundID.NPCHit30, SoundID.NPCHit31, SoundID.NPCHit32, SoundID.NPCHit33, SoundID.NPCHit34, SoundID.NPCHit35, SoundID.NPCHit36, SoundID.NPCHit37, SoundID.NPCHit38, SoundID.NPCHit39, SoundID.NPCHit4, SoundID.NPCHit40, SoundID.NPCHit41, SoundID.NPCHit42, SoundID.NPCHit43, SoundID.NPCHit44, SoundID.NPCHit45, SoundID.NPCHit46, SoundID.NPCHit47, SoundID.NPCHit48, SoundID.NPCHit49, SoundID.NPCHit5, SoundID.NPCHit50, SoundID.NPCHit51, SoundID.NPCHit52, SoundID.NPCHit53, SoundID.NPCHit54, SoundID.NPCHit55, SoundID.NPCHit56, SoundID.NPCHit57, SoundID.NPCHit6, SoundID.NPCHit7, SoundID.NPCHit8, SoundID.NPCHit9, npcSlots, oiled, Entity.oldDirection, oldPos, oldRot, oldTarget, onFire, onFire2, onFire3, onFrostBurn, onFrostBurn2, Opacity, playerInteraction, poisoned, Entity.position, rarity, realLife, reflectsProjectiles, releaseOwner, Main.remixWorld, rotation, scale, ScaleStats(), SetDefaultsFromNetId(), setFrameSize, shadowFlame, NPCID.Sets.ShimmerImmunity, shimmering, shimmerTransparency, soulDrain, SpawnedFromStatue, SpawnWithHigherTime(), spriteDirection, statsAreScaledForThisManyPlayers, stinky, strengthMultiplier, takenDamageMultiplier, target, targetRect, tentacleSpiked, Main.tenthAnniversaryWorld, timeLeft, townNPC, townNpcVariationIndex, NPCID.Sets.TrailCacheLength, trapImmune, type, value, venom, waterMovementSpeed, Entity.wet, Entity.wetCount, Entity.width, and Main.zenithWorld.
Referenced by NPCKillCounterInfoElement.NPCKillCounterInfoElement(), Segments.NPCSegment.NPCSegment(), UnlockableNPCEntryIcon.UnlockableNPCEntryIcon(), BestiaryDatabaseNPCsPopulator.AdjustPirateShipStats(), AI(), AI_113_WindyBalloon(), AI_121_QueenSlime(), ContentSamples.FillNpcRarities(), MessageBuffer.GetData(), HitEffect(), ContentSamples.Initialize(), Player.ItemCheck_UseTorchGodsFavor(), WorldFile.LoadNPCs(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), NewNPC(), PopupText.NewText(), Player.OpenBossBag(), NPCStatsReportInfoElement.RefreshStats(), SetDefaults_ForNetId(), SetDefaultsFromNetId(), SetDefaultsKeepPlayerInteraction(), SlimeRainSpawns(), Player.Spawn(), CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), SpawnNPC(), LootSimulator.TryGettingLootFor(), BrainOfCthuluBigProgressBar.ValidateAndCollectNecessaryInfo(), EaterOfWorldsProgressBar.ValidateAndCollectNecessaryInfo(), GolemHeadProgressBar.ValidateAndCollectNecessaryInfo(), MartianSaucerBigProgressBar.ValidateAndCollectNecessaryInfo(), MoonLordProgressBar.ValidateAndCollectNecessaryInfo(), and PirateShipBigProgressBar.ValidateAndCollectNecessaryInfo().