Terraria: NPC.NPCLoot_DropCommonLifeAndMana
NPCLoot_DropCommonLifeAndMana()
void NPC.NPCLoot_DropCommonLifeAndMana (Player closestPlayer) inline private
     {
         if (type != 16 && type != 81 && type != 121 && closestPlayer.RollLuck(6) == 0 && lifeMax > 1 && damage > 0)
         {
             if (Main.rand.Next(2) == 0 && closestPlayer.statMana < closestPlayer.statManaMax2)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 184);
             }
             else if (Main.rand.Next(2) == 0 && closestPlayer.statLife < closestPlayer.statLifeMax2)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             }
         }
         if (type != 16 && type != 81 && type != 121 && closestPlayer.RollLuck(2) == 0 && lifeMax > 1 && damage > 0 && closestPlayer.statMana < closestPlayer.statManaMax2)
         {
             Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 184);
         }
     }
References Item.NewItem(), UnifiedRandom.Next(), Main.rand, Player.RollLuck(), Player.statLife, Player.statLifeMax2, Player.statMana, and Player.statManaMax2.
Referenced by NPCLoot_DropHeals().