Terraria: NPC.AI_123_Deerclops_Movement
AI_123_Deerclops_Movement()
void NPC.AI_123_Deerclops_Movement (bool haltMovement, bool goHome) inline private
     {
         float num = (float)life / (float)lifeMax;
         float num2 = 1f - num;
         float num3 = 3.5f + 1f * num2;
         float num4 = 4f;
         float num5 = -0.4f;
         float min = -8f;
         float num6 = 0.4f;
         Rectangle rectangle = GetTargetData().Hitbox;
         if (goHome)
         {
             rectangle = new Rectangle(homeTileX * 16, homeTileY * 16, 16, 16);
             if (Distance(rectangle.Center.ToVector2()) < 240f)
             {
                 rectangle.X = (int)(base.Center.X + (float)(160 * direction));
             }
         }
         float num7 = (float)rectangle.Center.X - base.Center.X;
         float num8 = Math.Abs(num7);
         if (goHome && num7 != 0f)
         {
             direction = (spriteDirection = Math.Sign(num7));
         }
         bool flag = num8 < 80f;
         bool flag2 = flag || haltMovement;
         if (ai[0] == -1f)
         {
             num7 = 5f;
             num3 = 5.35f;
             flag2 = false;
         }
         if (flag2)
         {
             velocity.X *= 0.9f;
             if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
             {
                 velocity.X = 0f;
             }
         }
         else
         {
             int num9 = Math.Sign(num7);
             velocity.X = MathHelper.Lerp(velocity.X, (float)num9 * num3, 1f / num4);
         }
         int num10 = 40;
         int num11 = 20;
         int num12 = 0;
         Vector2 vector = new Vector2(base.Center.X - (float)(num10 / 2), position.Y + (float)height - (float)num11 + (float)num12);
         bool num13 = vector.X < (float)rectangle.X && vector.X + (float)width > (float)(rectangle.X + rectangle.Width);
         bool flag3 = vector.Y + (float)num11 < (float)(rectangle.Y + rectangle.Height - 16);
         bool acceptTopSurfaces = base.Bottom.Y >= (float)rectangle.Top;
         bool flag4 = Collision.SolidCollision(vector, num10, num11, acceptTopSurfaces);
         bool flag5 = Collision.SolidCollision(vector, num10, num11 - 4, acceptTopSurfaces);
         bool flag6 = !Collision.SolidCollision(vector + new Vector2(num10 * direction, 0f), 16, 80, acceptTopSurfaces);
         float num14 = 8f;
         if (flag4 || flag5)
         {
             localAI[0] = 0f;
         }
         if ((num13 || flag) && flag3)
         {
             velocity.Y = MathHelper.Clamp(velocity.Y + num6 * 2f, 0.001f, 16f);
         }
         else if (flag4 && !flag5)
         {
             velocity.Y = 0f;
         }
         else if (flag4)
         {
             velocity.Y = MathHelper.Clamp(velocity.Y + num5, min, 0f);
         }
         else if (velocity.Y == 0f && flag6)
         {
             velocity.Y = 0f - num14;
             localAI[0] = 1f;
         }
         else
         {
             velocity.Y = MathHelper.Clamp(velocity.Y + num6, 0f - num14, 16f);
         }
     }
References ai, Entity.direction, Entity.Distance(), GetTargetData(), Entity.height, NPCAimedTarget.Hitbox, homeTileX, homeTileY, life, lifeMax, localAI, Entity.position, Collision.SolidCollision(), spriteDirection, Entity.velocity, and Entity.width.
Referenced by AI_123_Deerclops().