Terraria: NPC.AI_037_Destroyer
AI_037_Destroyer()
void NPC.AI_037_Destroyer () inline private
     {
         int num = 0;
         int num2 = 10;
         if (IsMechQueenUp && type != 134)
         {
             int num3 = (int)ai[1];
             while (num3 > 0 && num3 < 200)
             {
                 if (Main.npc[num3].active && Main.npc[num3].type >= 134 && Main.npc[num3].type <= 136)
                 {
                     num++;
                     if (Main.npc[num3].type == 134)
                     {
                         break;
                     }
                     if (num >= num2)
                     {
                         num = 0;
                         break;
                     }
                     num3 = (int)Main.npc[num3].ai[1];
                     continue;
                 }
                 num = 0;
                 break;
             }
         }
         if (ai[3] > 0f)
         {
             realLife = (int)ai[3];
         }
         if (target < 0 || target == 255 || Main.player[target].dead)
         {
             TargetClosest();
         }
         if (type >= 134 && type <= 136)
         {
             velocity.Length();
             if (type == 134 || (type != 134 && Main.npc[(int)ai[1]].alpha < 128))
             {
                 if (alpha != 0)
                 {
                     for (int i = 0; i < 2; i++)
                     {
                         int num4 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 182, 0f, 0f, 100, default(Color), 2f);
                         Main.dust[num4].noGravity = true;
                         Main.dust[num4].noLight = true;
                     }
                 }
                 alpha -= 42;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
             }
         }
         if (type > 134)
         {
             bool flag = false;
             if (ai[1] <= 0f)
             {
                 flag = true;
             }
             else if (Main.npc[(int)ai[1]].life <= 0)
             {
                 flag = true;
             }
             if (flag)
             {
                 life = 0;
                 HitEffect();
                 checkDead();
             }
         }
         if (Main.netMode != 1)
         {
             if (ai[0] == 0f && type == 134)
             {
                 ai[3] = whoAmI;
                 realLife = whoAmI;
                 int num5 = 0;
                 int num6 = whoAmI;
                 int destroyerSegmentsCount = GetDestroyerSegmentsCount();
                 for (int j = 0; j <= destroyerSegmentsCount; j++)
                 {
                     int num7 = 135;
                     if (j == destroyerSegmentsCount)
                     {
                         num7 = 136;
                     }
                     num5 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num7, whoAmI);
                     Main.npc[num5].ai[3] = whoAmI;
                     Main.npc[num5].realLife = whoAmI;
                     Main.npc[num5].ai[1] = num6;
                     Main.npc[num6].ai[0] = num5;
                     NetMessage.SendData(23, -1, -1, null, num5);
                     num6 = num5;
                 }
             }
             if (type == 135)
             {
                 localAI[0] += Main.rand.Next(4);
                 if (localAI[0] >= (float)Main.rand.Next(1400, 26000))
                 {
                     localAI[0] = 0f;
                     TargetClosest();
                     if (Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
                     {
                         Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)(height / 2));
                         float num8 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector.X + (float)Main.rand.Next(-20, 21);
                         float num9 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - vector.Y + (float)Main.rand.Next(-20, 21);
                         float num10 = (float)Math.Sqrt(num8 * num8 + num9 * num9);
                         num10 = 8f / num10;
                         num8 *= num10;
                         num9 *= num10;
                         num8 += (float)Main.rand.Next(-20, 21) * 0.05f;
                         num9 += (float)Main.rand.Next(-20, 21) * 0.05f;
                         int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(22f, 18f);
                         int num11 = 100;
                         vector.X += num8 * 5f;
                         vector.Y += num9 * 5f;
                         int num12 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector.X, vector.Y, num8, num9, num11, attackDamage_ForProjectiles, 0f, Main.myPlayer);
                         Main.projectile[num12].timeLeft = 300;
                         netUpdate = true;
                     }
                 }
             }
         }
         int num13 = (int)(position.X / 16f) - 1;
         int num14 = (int)((position.X + (float)width) / 16f) + 2;
         int num15 = (int)(position.Y / 16f) - 1;
         int num16 = (int)((position.Y + (float)height) / 16f) + 2;
         if (num13 < 0)
         {
             num13 = 0;
         }
         if (num14 > Main.maxTilesX)
         {
             num14 = Main.maxTilesX;
         }
         if (num15 < 0)
         {
             num15 = 0;
         }
         if (num16 > Main.maxTilesY)
         {
             num16 = Main.maxTilesY;
         }
         bool flag2 = false;
         if (!flag2)
         {
             Vector2 vector2 = default(Vector2);
             for (int k = num13; k < num14; k++)
             {
                 for (int l = num15; l < num16; l++)
                 {
                     if (Main.tile[k, l] != null && ((Main.tile[k, l].nactive() && (Main.tileSolid[Main.tile[k, l].type] || (Main.tileSolidTop[Main.tile[k, l].type] && Main.tile[k, l].frameY == 0))) || Main.tile[k, l].liquid > 64))
                     {
                         vector2.X = k * 16;
                         vector2.Y = l * 16;
                         if (position.X + (float)width > vector2.X && position.X < vector2.X + 16f && position.Y + (float)height > vector2.Y && position.Y < vector2.Y + 16f)
{
                             flag2 = true;
                             break;
                         }
                     }
                 }
             }
         }
         if (!flag2)
         {
             if (type != 135 || ai[2] != 1f)
             {
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.3f, 0.1f, 0.05f);
             }
             localAI[1] = 1f;
             if (type == 134)
             {
                 Rectangle rectangle = new Rectangle((int)position.X, (int)position.Y, width, height);
                 int num17 = 1000;
                 bool flag3 = true;
                 if (position.Y > Main.player[target].position.Y)
                 {
                     for (int m = 0; m < 255; m++)
                     {
                         if (Main.player[m].active)
{
                             Rectangle rectangle2 = new Rectangle((int)Main.player[m].position.X - num17, (int)Main.player[m].position.Y - num17, num17 * 2, num17 * 2);
                             if (rectangle.Intersects(rectangle2))
{
                                 flag3 = false;
                                 break;
                             }
                         }
                     }
                     if (flag3)
                     {
                         flag2 = true;
                     }
                 }
             }
         }
         else
         {
             localAI[1] = 0f;
         }
         float num18 = 16f;
         if (Main.IsItDay() || Main.player[target].dead)
         {
             flag2 = false;
             velocity.Y += 1f;
             if ((double)position.Y > Main.worldSurface * 16.0)
             {
                 velocity.Y += 1f;
                 num18 = 32f;
             }
             if ((double)position.Y > Main.rockLayer * 16.0)
             {
                 for (int n = 0; n < 200; n++)
                 {
                     if (Main.npc[n].aiStyle == aiStyle)
                     {
                         Main.npc[n].active = false;
                     }
                 }
             }
         }
         float num19 = 0.1f;
         float num20 = 0.15f;
         if (Main.getGoodWorld)
         {
             num19 *= 1.2f;
             num20 *= 1.2f;
         }
         Vector2 vector3 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
         float num21 = Main.player[target].position.X + (float)(Main.player[target].width / 2);
         float num22 = Main.player[target].position.Y + (float)(Main.player[target].height / 2);
         num21 = (int)(num21 / 16f) * 16;
         num22 = (int)(num22 / 16f) * 16;
         vector3.X = (int)(vector3.X / 16f) * 16;
         vector3.Y = (int)(vector3.Y / 16f) * 16;
         num21 -= vector3.X;
         num22 -= vector3.Y;
         float num23 = (float)Math.Sqrt(num21 * num21 + num22 * num22);
         if (ai[1] > 0f && ai[1] < (float)Main.npc.Length)
         {
             int num24 = (int)(44f * scale);
             try
             {
                 vector3 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 num21 = Main.npc[(int)ai[1]].position.X + (float)(Main.npc[(int)ai[1]].width / 2) - vector3.X;
                 num22 = Main.npc[(int)ai[1]].position.Y + (float)(Main.npc[(int)ai[1]].height / 2) - vector3.Y;
             }
             catch
             {
             }
             if (num > 0)
             {
                 float num25 = (float)num24 - (float)num24 * (((float)num - 1f) * 0.1f);
                 if (num25 < 0f)
                 {
                     num25 = 0f;
                 }
                 if (num25 > (float)num24)
                 {
                     num25 = num24;
                 }
                 num22 = Main.npc[(int)ai[1]].position.Y + (float)(Main.npc[(int)ai[1]].height / 2) + num25 - vector3.Y;
             }
             rotation = (float)Math.Atan2(num22, num21) + 1.57f;
             num23 = (float)Math.Sqrt(num21 * num21 + num22 * num22);
             if (num > 0)
             {
                 num24 = num24 / num2 * num;
             }
             num23 = (num23 - (float)num24) / num23;
             num21 *= num23;
             num22 *= num23;
             velocity = Vector2.Zero;
             position.X += num21;
             position.Y += num22;
             num21 = Main.npc[(int)ai[1]].position.X + (float)(Main.npc[(int)ai[1]].width / 2) - vector3.X;
             num22 = Main.npc[(int)ai[1]].position.Y + (float)(Main.npc[(int)ai[1]].height / 2) - vector3.Y;
             rotation = (float)Math.Atan2(num22, num21) + 1.57f;
         }
         else
         {
             if (!flag2)
             {
                 TargetClosest();
                 velocity.Y += 0.15f;
                 if (velocity.Y > num18)
                 {
                     velocity.Y = num18;
                 }
                 if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num18 * 0.4)
                 {
                     if (velocity.X < 0f)
                     {
                         velocity.X -= num19 * 1.1f;
                     }
                     else
                     {
                         velocity.X += num19 * 1.1f;
                     }
                 }
                 else if (velocity.Y == num18)
                 {
                     if (velocity.X < num21)
                     {
                         velocity.X += num19;
                     }
                     else if (velocity.X > num21)
                     {
                         velocity.X -= num19;
                     }
                 }
                 else if (velocity.Y > 4f)
                 {
                     if (velocity.X < 0f)
                     {
                         velocity.X += num19 * 0.9f;
                     }
                     else
                     {
                         velocity.X -= num19 * 0.9f;
                     }
                 }
             }
             else
             {
                 if (soundDelay == 0)
                 {
                     float num26 = num23 / 40f;
                     if (num26 < 10f)
                     {
                         num26 = 10f;
                     }
                     if (num26 > 20f)
                     {
                         num26 = 20f;
                     }
                     soundDelay = (int)num26;
                     SoundEngine.PlaySound(15, (int)position.X, (int)position.Y);
                 }
                 num23 = (float)Math.Sqrt(num21 * num21 + num22 * num22);
                 float num27 = Math.Abs(num21);
                 float num28 = Math.Abs(num22);
                 float num29 = num18 / num23;
                 num21 *= num29;
                 num22 *= num29;
                 if (((velocity.X > 0f && num21 > 0f) || (velocity.X < 0f && num21 < 0f)) && ((velocity.Y > 0f && num22 > 0f) || (velocity.Y < 0f && num22 < 0f)))
                 {
                     if (velocity.X < num21)
                     {
                         velocity.X += num20;
                     }
                     else if (velocity.X > num21)
                     {
                         velocity.X -= num20;
                     }
                     if (velocity.Y < num22)
                     {
                         velocity.Y += num20;
                     }
                     else if (velocity.Y > num22)
                     {
                         velocity.Y -= num20;
                     }
                 }
                 if ((velocity.X > 0f && num21 > 0f) || (velocity.X < 0f && num21 < 0f) || (velocity.Y > 0f && num22 > 0f) || (velocity.Y < 0f && num22 < 0f))
                 {
                     if (velocity.X < num21)
                     {
                         velocity.X += num19;
                     }
                     else if (velocity.X > num21)
                     {
                         velocity.X -= num19;
                     }
                     if (velocity.Y < num22)
                     {
                         velocity.Y += num19;
                     }
                     else if (velocity.Y > num22)
                     {
                         velocity.Y -= num19;
                     }
                     if ((double)Math.Abs(num22) < (double)num18 * 0.2 && ((velocity.X > 0f && num21 < 0f) || (velocity.X < 0f && num21 > 0f)))
                     {
                         if (velocity.Y > 0f)
{
                             velocity.Y += num19 * 2f;
                         }
                         else
{
                             velocity.Y -= num19 * 2f;
                         }
                     }
                     if ((double)Math.Abs(num21) < (double)num18 * 0.2 && ((velocity.Y > 0f && num22 < 0f) || (velocity.Y < 0f && num22 > 0f)))
                     {
                         if (velocity.X > 0f)
{
                             velocity.X += num19 * 2f;
                         }
                         else
{
                             velocity.X -= num19 * 2f;
                         }
                     }
                 }
                 else if (num27 > num28)
                 {
                     if (velocity.X < num21)
                     {
                         velocity.X += num19 * 1.1f;
                     }
                     else if (velocity.X > num21)
                     {
                         velocity.X -= num19 * 1.1f;
                     }
                     if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num18 * 0.5)
                     {
                         if (velocity.Y > 0f)
{
                             velocity.Y += num19;
                         }
                         else
{
                             velocity.Y -= num19;
                         }
                     }
                 }
                 else
                 {
                     if (velocity.Y < num22)
                     {
                         velocity.Y += num19 * 1.1f;
                     }
                     else if (velocity.Y > num22)
                     {
                         velocity.Y -= num19 * 1.1f;
                     }
                     if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num18 * 0.5)
                     {
                         if (velocity.X > 0f)
{
                             velocity.X += num19;
                         }
                         else
{
                             velocity.X -= num19;
                         }
                     }
                 }
             }
             rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
             if (type == 134)
             {
                 if (flag2)
                 {
                     if (localAI[0] != 1f)
                     {
                         netUpdate = true;
                     }
                     localAI[0] = 1f;
                 }
                 else
                 {
                     if (localAI[0] != 0f)
                     {
                         netUpdate = true;
                     }
                     localAI[0] = 0f;
                 }
                 if (((velocity.X > 0f && oldVelocity.X < 0f) || (velocity.X < 0f && oldVelocity.X > 0f) || (velocity.Y > 0f && oldVelocity.Y < 0f) || (velocity.Y < 0f && oldVelocity.Y > 0f)) && !justHit)
                 {
                     netUpdate = true;
                 }
             }
         }
         if (IsMechQueenUp && type == 134)
         {
             NPC nPC = Main.npc[mechQueen];
             Vector2 mechQueenCenter = nPC.GetMechQueenCenter();
             Vector2 vector4 = new Vector2(0f, 100f);
             Vector2 spinningpoint = mechQueenCenter + vector4;
             float num30 = nPC.velocity.X * 0.025f;
             spinningpoint = spinningpoint.RotatedBy(num30, mechQueenCenter);
             position = spinningpoint - base.Size / 2f + nPC.velocity;
             velocity.X = 0f;
             velocity.Y = 0f;
             rotation = num30 * 0.75f + (float)Math.PI;
         }
     }
References Entity.active, Lighting.AddLight(), ai, aiStyle, alpha, Collision.CanHit(), checkDead(), Color, Player.dead, Main.dust, Tile.frameY, GetAttackDamage_ForProjectiles(), GetDestroyerSegmentsCount(), Main.getGoodWorld, GetMechQueenCenter(), GetSpawnSource_ForProjectile(), GetSpawnSourceForNPCFromNPCAI(), Entity.height, HitEffect(), Main.IsItDay(), IsMechQueenUp, justHit, life, Tile.liquid, localAI, Main.maxTilesX, Main.maxTilesY, mechQueen, Main.myPlayer, Tile.nactive(), Main.netMode, netUpdate, Dust.NewDust(), NewNPC(), Projectile.NewProjectile(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.npc, Entity.oldVelocity, Main.player, SoundEngine.PlaySound(), Entity.position, Main.projectile, Main.rand, realLife, Main.rockLayer, rotation, scale, NetMessage.SendData(), soundDelay, target, TargetClosest(), Main.tile, Main.tileSolid, Main.tileSolidTop, Projectile.timeLeft, type, Tile.type, Entity.velocity, Entity.whoAmI, Entity.width, and Main.worldSurface.
Referenced by AI().