Terraria: NPC.AI_121_QueenSlime
AI_121_QueenSlime()
void NPC.AI_121_QueenSlime () inline private
     {
         int num = 30;
         int num2 = 40;
         _ = Main.expertMode;
         float num3 = 1f;
         bool flag = false;
         bool flag2 = life <= lifeMax / 2;
         if (localAI[0] == 0f)
         {
             ai[1] = -100f;
             localAI[0] = lifeMax;
             TargetClosest();
             netUpdate = true;
         }
         Lighting.AddLight(base.Center, 1f, 0.7f, 0.9f);
         int num4 = 500;
         if (Main.player[target].dead || Math.Abs(base.Center.X - Main.player[target].Center.X) / 16f > (float)num4)
         {
             TargetClosest();
             if (Main.player[target].dead || Math.Abs(base.Center.X - Main.player[target].Center.X) / 16f > (float)num4)
             {
                 EncourageDespawn(10);
                 if (Main.player[target].Center.X < base.Center.X)
                 {
                     direction = 1;
                 }
                 else
                 {
                     direction = -1;
                 }
             }
         }
         if (!Main.player[target].dead && timeLeft > 10 && !flag2 && ai[3] >= 300f && ai[0] == 0f && velocity.Y == 0f)
         {
             ai[0] = 2f;
             ai[1] = 0f;
             if (Main.netMode != 1)
             {
                 netUpdate = true;
                 TargetClosest(faceTarget: false);
                 Point point = base.Center.ToTileCoordinates();
                 Point point2 = Main.player[target].Center.ToTileCoordinates();
                 Vector2 vector = Main.player[target].Center - base.Center;
                 int num5 = 10;
                 int num6 = 0;
                 int num7 = 7;
                 int num8 = 0;
                 bool flag3 = false;
                 if (ai[3] >= 360f || vector.Length() > 2000f)
                 {
                     if (ai[3] > 360f)
                     {
                         ai[3] = 360f;
                     }
                     flag3 = true;
                     num8 = 100;
                 }
                 while (!flag3 && num8 < 100)
                 {
                     num8++;
                     int num9 = Main.rand.Next(point2.X - num5, point2.X + num5 + 1);
                     int num10 = Main.rand.Next(point2.Y - num5, point2.Y + 1);
                     if ((num10 >= point2.Y - num7 && num10 <= point2.Y + num7 && num9 >= point2.X - num7 && num9 <= point2.X + num7) || (num10 >= point.Y - num6 && num10 <= point.Y + num6 && num9 >= point.X - num6 && num9 <= point.X + num6) || Main.tile[num9, num10].nactive())
                     {
                         continue;
                     }
                     int num11 = num10;
                     int i = 0;
                     if (Main.tile[num9, num11].nactive() && Main.tileSolid[Main.tile[num9, num11].type] && !Main.tileSolidTop[Main.tile[num9, num11].type])
                     {
                         i = 1;
                     }
                     else
                     {
                         for (; i < 150 && num11 + i < Main.maxTilesY; i++)
{
                             int num12 = num11 + i;
                             if (Main.tile[num9, num12].nactive() && Main.tileSolid[Main.tile[num9, num12].type] && !Main.tileSolidTop[Main.tile[num9, num12].type])
{
                                 i--;
                                 break;
                             }
                         }
                     }
                     num10 += i;
                     bool flag4 = true;
                     if (flag4 && Main.tile[num9, num10].lava())
                     {
                         flag4 = false;
                     }
                     if (flag4 && !Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                     {
                         flag4 = false;
                     }
                     if (flag4)
                     {
                         localAI[1] = num9 * 16 + 8;
                         localAI[2] = num10 * 16 + 16;
                         flag3 = true;
                         break;
                     }
                 }
                 if (num8 >= 100)
                 {
                     Vector2 bottom = Main.player[Player.FindClosest(position, width, height)].Bottom;
                     localAI[1] = bottom.X;
                     localAI[2] = bottom.Y;
                     ai[3] = 0f;
                 }
             }
         }
         if (!flag2 && (!Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0) || Math.Abs(base.Top.Y - Main.player[target].Bottom.Y) > 320f))
         {
             ai[3] += 1.5f;
         }
         else
         {
             float num13 = ai[3];
             ai[3] -= 1f;
             if (ai[3] < 0f)
             {
                 if (Main.netMode != 1 && num13 > 0f)
                 {
                     netUpdate = true;
                 }
                 ai[3] = 0f;
             }
         }
         if (timeLeft <= 10 && ((flag2 && ai[0] != 0f) || (!flag2 && ai[0] != 3f)))
         {
             if (flag2)
             {
                 ai[0] = 0f;
             }
             else
             {
                 ai[0] = 3f;
             }
             ai[1] = 0f;
             ai[2] = 0f;
             ai[3] = 0f;
             netUpdate = true;
         }
         noTileCollide = false;
         noGravity = false;
         if (flag2)
         {
             localAI[3] += 1f;
             if (localAI[3] >= 24f)
             {
                 localAI[3] = 0f;
             }
             if (ai[0] == 4f && ai[2] == 1f)
             {
                 localAI[3] = 6f;
             }
             if (ai[0] == 5f && ai[2] != 1f)
             {
                 localAI[3] = 7f;
             }
         }
         switch ((int)ai[0])
         {
         case 0:
         {
             if (flag2)
             {
                 AI_121_QueenSlime_FlyMovement();
             }
             else
             {
                 noTileCollide = false;
                 noGravity = false;
                 if (velocity.Y == 0f)
                 {
                     velocity.X *= 0.8f;
                     if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
                     {
                         velocity.X = 0f;
                     }
                 }
             }
             if (timeLeft <= 10 || (!flag2 && velocity.Y != 0f))
             {
                 break;
             }
             ai[1] += 1f;
             int num18 = 60;
             if (flag2)
             {
                 num18 = 120;
             }
             if (!(ai[1] > (float)num18))
             {
                 break;
             }
             ai[1] = 0f;
             if (flag2)
             {
                 Player player = Main.player[target];
                 int num19 = Main.rand.Next(2);
                 if (num19 != 1)
                 {
                     ai[0] = 4f;
                 }
                 else
                 {
                     ai[0] = 5f;
                 }
                 if (ai[0] == 4f)
                 {
                     ai[2] = 1f;
                     if (player != null && player.active && !player.dead && (player.Bottom.Y < base.Bottom.Y || Math.Abs(player.Center.X - base.Center.X) > 250f))
                     {
                         ai[0] = 5f;
                         ai[2] = 0f;
                     }
                 }
             }
             else
             {
                 switch (Main.rand.Next(3))
                 {
                 default:
                     ai[0] = 3f;
                     break;
                 case 1:
                     ai[0] = 4f;
                     break;
                 case 2:
                     ai[0] = 5f;
                     break;
                 }
             }
             netUpdate = true;
             break;
         }
         case 1:
         {
             rotation = 0f;
             ai[1] += 1f;
             num3 = MathHelper.Clamp(ai[1] / 30f, 0f, 1f);
             num3 = 0.5f + num3 * 0.5f;
             if (ai[1] >= 30f && Main.netMode != 1)
             {
                 ai[0] = 0f;
                 ai[1] = 0f;
                 netUpdate = true;
                 TargetClosest();
             }
             if (Main.netMode == 1 && ai[1] >= 60f)
             {
                 ai[0] = 0f;
                 ai[1] = 0f;
                 TargetClosest();
             }
             Color newColor2 = AI_121_QueenSlime_GetDustColor();
             newColor2.A = 150;
             for (int num27 = 0; num27 < 10; num27++)
             {
                 int num28 = Dust.NewDust(position + Vector2.UnitX * -20f, width + 40, height, 4, velocity.X, velocity.Y, 50, newColor2, 1.5f);
                 Main.dust[num28].noGravity = true;
                 Main.dust[num28].velocity *= 2f;
             }
             break;
         }
         case 2:
             rotation = 0f;
             ai[1] += 1f;
             num3 = MathHelper.Clamp((60f - ai[1]) / 60f, 0f, 1f);
             num3 = 0.5f + num3 * 0.5f;
             if (ai[1] >= 60f)
             {
                 flag = true;
             }
             if (ai[1] == 60f)
             {
                 Gore.NewGore(base.Center + new Vector2(-40f, -height / 2), velocity, 1258);
             }
             if (ai[1] >= 60f && Main.netMode != 1)
             {
                 base.Bottom = new Vector2(localAI[1], localAI[2]);
                 ai[0] = 1f;
                 ai[1] = 0f;
                 netUpdate = true;
             }
             if (Main.netMode == 1 && ai[1] >= 120f)
             {
                 ai[0] = 1f;
                 ai[1] = 0f;
             }
             if (!flag)
             {
                 Color newColor = AI_121_QueenSlime_GetDustColor();
                 newColor.A = 150;
                 for (int n = 0; n < 10; n++)
                 {
                     int num26 = Dust.NewDust(position + Vector2.UnitX * -20f, width + 40, height, 4, velocity.X, velocity.Y, 50, newColor, 1.5f);
                     Main.dust[num26].noGravity = true;
                     Main.dust[num26].velocity *= 0.5f;
                 }
             }
             break;
         case 3:
             rotation = 0f;
             if (velocity.Y == 0f)
             {
                 velocity.X *= 0.8f;
                 if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
                 {
                     velocity.X = 0f;
                 }
                 ai[1] += 4f;
                 if ((double)life < (double)lifeMax * 0.66)
                 {
                     ai[1] += 4f;
                 }
                 if ((double)life < (double)lifeMax * 0.33)
                 {
                     ai[1] += 4f;
                 }
                 if (!(ai[1] >= 0f))
                 {
                     break;
                 }
                 netUpdate = true;
                 TargetClosest();
                 if (ai[2] == 3f)
                 {
                     velocity.Y = -13f;
                     velocity.X += 3.5f * (float)direction;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     if (timeLeft > 10)
                     {
                         ai[0] = 0f;
                     }
                     else
                     {
                         ai[1] = -60f;
                     }
                 }
                 else if (ai[2] == 2f)
                 {
                     velocity.Y = -6f;
                     velocity.X += 4.5f * (float)direction;
                     ai[1] = -40f;
                     ai[2] += 1f;
                 }
                 else
                 {
                     velocity.Y = -8f;
                     velocity.X += 4f * (float)direction;
                     ai[1] = -40f;
                     ai[2] += 1f;
                 }
             }
             else
             {
                 if (target >= 255)
                 {
                     break;
                 }
                 float num20 = 3f;
                 if (Main.getGoodWorld)
                 {
                     num20 = 7f;
                 }
                 if ((direction == 1 && velocity.X < num20) || (direction == -1 && velocity.X > 0f - num20))
                 {
                     if ((direction == -1 && (double)velocity.X < 0.1) || (direction == 1 && (double)velocity.X > -0.1))
                     {
                         velocity.X += 0.2f * (float)direction;
                     }
                     else
                     {
                         velocity.X *= 0.93f;
                     }
                 }
             }
             break;
         case 4:
         {
             rotation *= 0.9f;
             noTileCollide = true;
             noGravity = true;
             if (ai[2] == 1f)
             {
                 noTileCollide = false;
                 noGravity = false;
                 int num21 = 30;
                 if (flag2)
                 {
                     num21 = 10;
                 }
                 if (Main.getGoodWorld)
                 {
                     num21 = 0;
                 }
                 Player player2 = Main.player[target];
                 _ = base.Center;
                 if (!player2.dead && player2.active && Math.Abs(base.Center.X - player2.Center.X) / 16f <= (float)num4)
                 {
                     _ = player2.Center;
                 }
                 if (velocity.Y == 0f)
                 {
                     ai[0] = 0f;
                     ai[1] = 0f;
                     ai[2] = 0f;
                     netUpdate = true;
                     SoundEngine.PlaySound(SoundID.Item167, base.Center);
                     if (Main.netMode != 1)
                     {
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Bottom, Vector2.Zero, 922, num2, 0f, Main.myPlayer);
                     }
                     for (int l = 0; l < 20; l++)
                     {
                         int num22 = Dust.NewDust(base.Bottom - new Vector2(width / 2, 30f), width, 30, 31, velocity.X, velocity.Y, 40, AI_121_QueenSlime_GetDustColor());
                         Main.dust[num22].noGravity = true;
                         Main.dust[num22].velocity.Y = -5f + Main.rand.NextFloat() * -3f;
                         Main.dust[num22].velocity.X *= 7f;
                     }
                 }
                 else if (ai[1] >= (float)num21)
                 {
                     for (int m = 0; m < 4; m++)
                     {
                         Vector2 vector3 = base.Bottom - new Vector2(Main.rand.NextFloatDirection() * 16f, Main.rand.Next(8));
                         int num23 = Dust.NewDust(vector3, 2, 2, 31, velocity.X, velocity.Y, 40, AI_121_QueenSlime_GetDustColor(), 1.4f);
                         Main.dust[num23].position = vector3;
                         Main.dust[num23].noGravity = true;
                         Main.dust[num23].velocity.Y = velocity.Y * 0.9f;
                         Main.dust[num23].velocity.X = ((Main.rand.Next(2) == 0) ? (-10f) : 10f) + Main.rand.NextFloatDirection() * 3f;
                     }
                 }
                 velocity.X *= 0.8f;
                 float num24 = ai[1];
                 ai[1] += 1f;
                 if (ai[1] >= (float)num21)
                 {
                     if (num24 < (float)num21)
                     {
                         netUpdate = true;
                     }
                     if (flag2 && ai[1] > (float)(num21 + 120))
                     {
                         ai[0] = 0f;
                         ai[1] = 0f;
                         ai[2] = 0f;
                         velocity.Y *= 0.8f;
                         netUpdate = true;
                         break;
                     }
                     velocity.Y += 1f;
                     float num25 = 14f;
                     if (Main.getGoodWorld)
                     {
                         velocity.Y += 1f;
                         num25 = 15.99f;
                     }
                     if (velocity.Y == 0f)
                     {
                         velocity.Y = 0.01f;
                     }
                     if (velocity.Y >= num25)
                     {
                         velocity.Y = num25;
                     }
                 }
                 else
                 {
                     velocity.Y *= 0.8f;
                 }
                 break;
             }
             if (Main.netMode != 1 && ai[1] == 0f)
             {
                 TargetClosest();
                 netUpdate = true;
             }
             ai[1] += 1f;
             if (!(ai[1] >= 30f))
             {
                 break;
             }
             if (ai[1] >= 60f)
             {
                 ai[1] = 60f;
                 if (Main.netMode != 1)
                 {
                     ai[1] = 0f;
                     ai[2] = 1f;
                     velocity.Y = -3f;
                     netUpdate = true;
                 }
             }
             Player player3 = Main.player[target];
             Vector2 center = base.Center;
             if (!player3.dead && player3.active && Math.Abs(base.Center.X - player3.Center.X) / 16f <= (float)num4)
             {
                 center = player3.Center;
             }
             center.Y -= 384f;
             if (velocity.Y == 0f)
             {
                 velocity = center - base.Center;
                 velocity = velocity.SafeNormalize(Vector2.Zero);
                 velocity *= 20f;
             }
             else
             {
                 velocity.Y *= 0.95f;
             }
             break;
         }
         case 5:
         {
             rotation *= 0.9f;
             noTileCollide = true;
             noGravity = true;
             if (flag2)
             {
                 ai[3] = 0f;
             }
             if (ai[2] == 1f)
             {
                 ai[1] += 1f;
                 if (!(ai[1] >= 10f))
                 {
                     break;
                 }
                 if (Main.netMode != 1)
                 {
                     int num14 = 10;
                     if (Main.getGoodWorld)
                     {
                         num14 = 15;
                     }
                     int num15 = num14;
                     if (!flag2)
                     {
                         num15 = 6;
                     }
                     for (int j = 0; j < num15; j++)
                     {
                         Vector2 spinningpoint = new Vector2(9f, 0f);
                         spinningpoint = spinningpoint.RotatedBy((float)(-j) * ((float)Math.PI * 2f) / (float)num14, Vector2.Zero);
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, spinningpoint.X, spinningpoint.Y, 926, num, 0f, Main.myPlayer);
                     }
                 }
                 ai[0] = 0f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 netUpdate = true;
                 break;
             }
             if (Main.netMode != 1 && ai[1] == 0f)
             {
                 TargetClosest();
                 netUpdate = true;
             }
             ai[1] += 1f;
             if (ai[1] >= 50f)
             {
                 ai[1] = 50f;
                 if (Main.netMode != 1)
                 {
                     ai[1] = 0f;
                     ai[2] = 1f;
                     netUpdate = true;
                 }
             }
             float num16 = 100f;
             for (int k = 0; k < 4; k++)
             {
                 Vector2 vector2 = base.Center + Main.rand.NextVector2CircularEdge(num16, num16);
                 if (!flag2)
                 {
                     vector2 += new Vector2(0f, 20f);
                 }
                 Vector2 v = vector2 - base.Center;
                 v = v.SafeNormalize(Vector2.Zero) * -8f;
                 int num17 = Dust.NewDust(vector2, 2, 2, 31, v.X, v.Y, 40, AI_121_QueenSlime_GetDustColor(), 1.8f);
                 Main.dust[num17].position = vector2;
                 Main.dust[num17].noGravity = true;
                 Main.dust[num17].alpha = 250;
                 Main.dust[num17].velocity = v;
                 Main.dust[num17].customData = this;
             }
             if (flag2)
             {
                 AI_121_QueenSlime_FlyMovement();
             }
             break;
         }
         }
         dontTakeDamage = (hide = flag);
         if (num3 != scale)
         {
             position.X += width / 2;
             position.Y += height;
             scale = num3;
             width = (int)(114f * scale);
             height = (int)(100f * scale);
             position.X -= width / 2;
             position.Y -= height;
         }
         if (life <= 0)
         {
             return;
         }
         if (Main.rand.Next(360) == 0)
         {
             SoundEngine.PlaySound(65, position);
         }
         if (Main.netMode == 1)
         {
             return;
         }
         if (localAI[0] >= (float)(lifeMax / 2) && life < lifeMax / 2)
         {
             localAI[0] = life;
             ai[0] = 0f;
             ai[1] = 0f;
             ai[2] = 0f;
             netUpdate = true;
         }
         int num29 = (int)((float)lifeMax * 0.02f);
         if (flag2)
         {
             num29 = (int)((float)lifeMax * 0.015f);
         }
         if (!((float)(life + num29) < localAI[0]))
         {
             return;
         }
         localAI[0] = life;
         int num30 = Main.rand.Next(1, 3);
         for (int num31 = 0; num31 < num30; num31++)
         {
             int x = (int)(position.X + (float)Main.rand.Next(width - 32));
             int y = (int)(position.Y + (float)Main.rand.Next(height - 32));
             int num32 = 658;
             switch (Main.rand.Next(3))
             {
             case 0:
                 num32 = 658;
                 break;
             case 1:
                 num32 = 659;
                 break;
             case 2:
                 num32 = 660;
                 break;
             }
             int num33 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), x, y, num32);
             Main.npc[num33].SetDefaults(num32);
             Main.npc[num33].velocity.X = (float)Main.rand.Next(-15, 16) * 0.1f;
             Main.npc[num33].velocity.Y = (float)Main.rand.Next(-30, 1) * 0.1f;
             Main.npc[num33].ai[0] = -500 * Main.rand.Next(3);
             Main.npc[num33].ai[1] = 0f;
             if (Main.netMode == 2 && num33 < 200)
             {
                 NetMessage.SendData(23, -1, -1, null, num33);
             }
         }
     }
References Entity.active, Lighting.AddLight(), ai, AI_121_QueenSlime_FlyMovement(), AI_121_QueenSlime_GetDustColor(), Dust.alpha, Entity.Bottom, Collision.CanHitLine(), Entity.Center, Color, Dust.customData, Player.dead, Entity.direction, dontTakeDamage, Main.dust, EncourageDespawn(), Main.expertMode, Player.FindClosest(), Main.getGoodWorld, GetSpawnSource_ForProjectile(), GetSpawnSourceForNPCFromNPCAI(), Entity.height, hide, SoundID.Item167, Tile.lava(), life, lifeMax, localAI, Main.maxTilesY, Main.myPlayer, Tile.nactive(), Main.netMode, netUpdate, Dust.NewDust(), Gore.NewGore(), NewNPC(), Projectile.NewProjectile(), UnifiedRandom.Next(), Dust.noGravity, noGravity, noTileCollide, Main.npc, Main.player, SoundEngine.PlaySound(), Dust.position, Entity.position, Main.rand, rotation, scale, NetMessage.SendData(), SetDefaults(), target, TargetClosest(), Main.tile, Main.tileSolid, Main.tileSolidTop, timeLeft, Tile.type, Dust.velocity, Entity.velocity, and Entity.width.
Referenced by AI().