Terraria: NPC.AnyoneNearCultists
AnyoneNearCultists()
static bool NPC.AnyoneNearCultists () inline static
     {
         int num = FindFirstNPC(437);
         if (num == -1)
         {
             return false;
         }
         Rectangle rectangle = Utils.CenteredRectangle(Main.npc[num].Center, new Vector2(2500f, 1500f));
         Rectangle r = new Rectangle(0, 0, 2500, 1500);
         Vector2 vector = r.Size() / 2f;
         for (int i = 0; i < 255; i++)
         {
             if (Main.player[i].active)
             {
                 r.X = (int)Main.player[i].Center.X - (int)vector.X;
                 r.Y = (int)Main.player[i].Center.Y - (int)vector.Y;
                 if (rectangle.Intersects(r))
                 {
                     return true;
                 }
             }
         }
         return false;
     }
References Entity.active, Entity.Center, Utils.CenteredRectangle(), Main.npc, and Main.player.
Referenced by MessageBuffer.GetData(), Player.ItemCheck_CheckCanUse(), and Player.ItemCheck_UseEventItems().