Terraria: NPC.AI_112_FairyCritter
AI_112_FairyCritter()
void NPC.AI_112_FairyCritter () inline private
     {
         bool flag = false;
         lavaImmune = true;
         if (Main.netMode != 1 && ai[2] > 1f)
         {
             int num = 18000;
             localAI[1] += 1f;
             if (localAI[1] >= (float)num)
             {
                 ai[2] = 7f;
                 if (Main.player[target].Center.X < base.Center.X)
                 {
                     direction = 1;
                 }
                 else
                 {
                     direction = -1;
                 }
                 netUpdate = true;
             }
         }
         switch ((int)ai[2])
         {
         case 0:
         {
             lavaImmune = false;
             noTileCollide = false;
             if (ai[0] == 0f && ai[1] == 0f)
             {
                 ai[0] = base.Center.X;
                 ai[1] = base.Center.Y;
             }
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 velocity = new Vector2(MathHelper.Lerp(2f, 4f, Main.rand.NextFloat()) * (float)(Main.rand.Next(2) * 2 - 1), MathHelper.Lerp(1f, 2f, Main.rand.NextFloat()) * (float)(Main.rand.Next(2) * 2 - 1));
                 velocity *= 0.7f;
                 netUpdate = true;
             }
             Vector2 vector4 = new Vector2(ai[0], ai[1]) - base.Center;
             if (vector4.Length() > 20f)
             {
                 Vector2 vector5 = new Vector2((vector4.X > 0f) ? 1 : (-1), (vector4.Y > 0f) ? 1 : (-1));
                 velocity += vector5 * 0.04f;
                 if (Math.Abs(velocity.Y) > 2f)
                 {
                     velocity.Y *= 0.95f;
                 }
             }
             TargetClosest();
             Player player = Main.player[target];
             if (!player.dead && player.Distance(base.Center) < 250f)
             {
                 ai[2] = 1f;
                 direction = ((!(player.Center.X > base.Center.X)) ? 1 : (-1));
                 if (velocity.X * (float)direction < 0f)
                 {
                     velocity.X = direction * 2;
                 }
                 ai[3] = 0f;
                 netUpdate = true;
             }
             break;
         }
         case 1:
         {
             lavaImmune = false;
             noTileCollide = false;
             if (collideX)
             {
                 direction *= -1;
                 velocity.X = direction * 2;
             }
             if (collideY)
             {
                 velocity.Y = ((oldVelocity.Y > 0f) ? 1 : (-1));
             }
             float num12 = 4.5f;
             if (Math.Sign(velocity.X) != direction || Math.Abs(velocity.X) < num12)
             {
                 velocity.X += (float)direction * 0.04f;
                 if (velocity.X * (float)direction < 0f)
                 {
                     if (Math.Abs(velocity.X) > num12)
                     {
                         velocity.X += (float)direction * 0.4f;
                     }
                     else
                     {
                         velocity.X += (float)direction * 0.2f;
                     }
                 }
                 else if (Math.Abs(velocity.X) > num12)
                 {
                     velocity.X = (float)direction * num12;
                 }
             }
             int num13 = (int)((position.X + (float)(width / 2)) / 16f);
             int num14 = 20;
             if (direction < 0)
             {
                 num13 -= num14;
             }
             int num15 = (int)((position.Y + (float)height) / 16f);
             bool flag5 = true;
             int num16 = 8;
             bool flag6 = false;
             for (int i = num13; i <= num13 + num14; i++)
             {
                 for (int j = num15; j < num15 + num16; j++)
                 {
                     if (Main.tile[i, j] == null)
                     {
                         Main.tile[i, j] = new Tile();
                     }
                     if ((Main.tile[i, j].nactive() && Main.tileSolid[Main.tile[i, j].type]) || Main.tile[i, j].liquid > 0)
                     {
                         if (j < num15 + 5)
{
                             flag6 = true;
                         }
                         flag5 = false;
                         break;
                     }
                 }
             }
             if (flag5)
             {
                 velocity.Y += 0.05f;
             }
             else
             {
                 velocity.Y -= 0.2f;
             }
             if (flag6)
             {
                 velocity.Y -= 0.3f;
             }
             if (velocity.Y > 3f)
             {
                 velocity.Y = 3f;
             }
             if (velocity.Y < -5f)
             {
                 velocity.Y = -5f;
             }
             break;
         }
         case 2:
         {
             noTileCollide = true;
             NPCAimedTarget targetData = GetTargetData();
             bool flag3 = false;
             if (targetData.Type == NPCTargetType.Player)
             {
                 flag3 = Main.player[target].dead;
             }
             if (flag3)
             {
                 ai[2] = 1f;
                 direction = ((!(targetData.Center.X > base.Center.X)) ? 1 : (-1));
                 if (velocity.X * (float)direction < 0f)
                 {
                     velocity.X = direction * 2;
                 }
                 ai[3] = 0f;
                 netUpdate = true;
                 break;
             }
             Rectangle r = Utils.CenteredRectangle(targetData.Center, new Vector2(targetData.Width + 60, targetData.Height / 2));
             if (Main.netMode != 1 && base.Hitbox.Intersects(r))
             {
                 if (GetFairyTreasureCoords(out var treasureCoords2))
                 {
                     ai[0] = treasureCoords2.X;
                     ai[1] = treasureCoords2.Y;
                     ai[2] = 3f;
                     ai[3] = 0f;
                     netUpdate = true;
                 }
                 else
                 {
                     ai[2] = 6f;
                     ai[3] = 0f;
                     netUpdate = true;
                 }
                 break;
             }
             Vector2 vector3 = r.ClosestPointInRect(base.Center);
             Vector2 value = DirectionTo(vector3) * 2f;
             float num8 = Distance(vector3);
             if (num8 > 150f)
             {
                 value *= 2f;
             }
             else if (num8 > 80f)
             {
                 value *= 1.5f;
             }
             velocity = Vector2.Lerp(velocity, value, 0.07f);
             Point point = base.Center.ToTileCoordinates();
             if (ai[3] < 300f)
             {
                 GetBirdFlightRecommendation(6, 3, point, out var goDownwards, out var goUpwards);
                 if (goDownwards)
                 {
                     velocity.Y += 0.05f;
                 }
                 if (goUpwards)
                 {
                     velocity.Y -= 0.02f;
                 }
                 if (velocity.Y > 2f)
                 {
                     velocity.Y = 2f;
                 }
                 if (velocity.Y < -4f)
                 {
                     velocity.Y = -4f;
                 }
             }
             if (WorldGen.InWorld(point.X, point.Y))
             {
                 if (WorldGen.SolidTile(point))
                 {
                     ai[3] = Math.Min(ai[3] + 2f, 400f);
                 }
                 else
                 {
                     ai[3] = Math.Max(ai[3] - 1f, 0f);
                 }
             }
             break;
         }
         case 3:
             noTileCollide = true;
             if (ai[3] == 15f)
             {
                 SoundEngine.PlaySound(27, (int)position.X, (int)position.Y);
             }
             if (ai[3] <= 15f)
             {
                 velocity *= 0.9f;
             }
             else
             {
                 if (Main.player[target].Center.X > base.Center.X)
                 {
                     spriteDirection = -1;
                 }
                 else
                 {
                     spriteDirection = 1;
                 }
                 flag = true;
                 float num6 = 0f;
                 float num7 = ai[3] - 15f;
                 float circleHeight = 22f;
                 if (num7 <= 65f)
                 {
                     num6 = (float)Math.PI / 8f;
                     circleHeight = 14f;
                 }
                 else if (num7 <= 130f)
                 {
                     num6 = -(float)Math.PI / 8f;
                     circleHeight = 18f;
                 }
                 num6 *= (float)direction;
                 Vector2 fairyCircleOffset3 = GetFairyCircleOffset(num7 / 65f, num6, circleHeight);
                 Vector2 fairyCircleOffset4 = GetFairyCircleOffset(num7 / 65f + 1f / 65f, num6, circleHeight);
                 velocity = fairyCircleOffset4 - fairyCircleOffset3;
             }
             ai[3] += 1f;
             if (ai[3] >= 210f)
             {
                 ai[2] = 4f;
                 TargetClosest();
                 ai[3] = 0f;
                 netUpdate = true;
             }
             break;
         case 6:
         {
             noTileCollide = true;
             Vector2 vector = Main.player[target].Center - base.Center;
             if (vector.Length() > 100f)
             {
                 ai[2] = 2f;
                 TargetClosest();
                 ai[3] = 0f;
                 netUpdate = true;
                 break;
             }
             if (!Collision.SolidCollision(position, width, height))
             {
                 noTileCollide = false;
                 if (collideX)
                 {
                     velocity.X *= -1f;
                 }
                 if (collideY)
                 {
                     velocity.Y *= -1f;
                 }
             }
             if (vector.Length() > 20f)
             {
                 Vector2 vector2 = new Vector2((vector.X > 0f) ? 1 : (-1), (vector.Y > 0f) ? 1 : (-1));
                 velocity += vector2 * 0.04f;
                 if (Math.Abs(velocity.Y) > 2f)
                 {
                     velocity.Y *= 0.95f;
                 }
             }
             if (Main.netMode != 1 && GetFairyTreasureCoords(out var treasureCoords))
             {
                 ai[0] = treasureCoords.X;
                 ai[1] = treasureCoords.Y;
                 ai[2] = 3f;
                 ai[3] = 0f;
                 netUpdate = true;
             }
             break;
         }
         case 4:
         {
             noTileCollide = true;
             NPCAimedTarget targetData2 = GetTargetData();
             bool flag4 = false;
             if (targetData2.Type == NPCTargetType.Player)
             {
                 flag4 = Main.player[target].dead;
             }
             if (flag4)
             {
                 ai[2] = 1f;
                 direction = ((!(targetData2.Center.X > base.Center.X)) ? 1 : (-1));
                 if (velocity.X * (float)direction < 0f)
                 {
                     velocity.X = direction * 2;
                 }
                 ai[3] = 0f;
                 netUpdate = true;
                 break;
             }
             Rectangle r2 = Utils.CenteredRectangle(new Vector2(ai[0] * 16f + 8f, ai[1] * 16f + 8f), Vector2.One * 5f);
             if (base.Hitbox.Intersects(r2))
             {
                 ai[2] = 5f;
                 ai[3] = 0f;
                 netUpdate = true;
                 break;
             }
             float num9 = Distance(targetData2.Center);
             float num10 = 300f;
             if (num9 > num10)
             {
                 if (num9 < num10 + 100f && !Collision.SolidCollision(position, width, height))
                 {
                     noTileCollide = false;
                     if (collideX)
                     {
                         velocity.X *= -1f;
                     }
                     if (collideY)
                     {
                         velocity.Y *= -1f;
                     }
                 }
                 flag = true;
                 if (Main.player[target].Center.X > base.Center.X)
                 {
                     spriteDirection = -1;
                 }
                 else
                 {
                     spriteDirection = 1;
                 }
                 Vector2 vector6 = DirectionFrom(targetData2.Center);
                 if (num9 > num10 + 60f)
                 {
                     velocity += vector6 * -0.1f;
                     if (Main.rand.Next(30) == 0)
                     {
                         SoundEngine.PlaySound(27, (int)position.X, (int)position.Y);
                     }
                 }
                 else if (num9 < num10 + 30f)
                 {
                     Vector2 destination = r2.ClosestPointInRect(base.Center);
                     Vector2 vector7 = DirectionTo(destination);
                     velocity += vector7 * 0.1f;
                 }
                 if (velocity.Length() > 1f)
                 {
                     velocity *= 1f / velocity.Length();
                 }
                 break;
             }
             Vector2 vector8 = r2.ClosestPointInRect(base.Center);
             Vector2 value2 = DirectionTo(vector8);
             float num11 = Distance(vector8);
             if (num11 > 150f)
             {
                 value2 *= 3f;
             }
             else if (num11 > 80f)
             {
                 value2 *= 2f;
             }
             Point point2 = base.Center.ToTileCoordinates();
             if (ai[3] < 300f)
             {
                 velocity = Vector2.Lerp(velocity, value2, 0.07f);
                 GetBirdFlightRecommendation(4, 2, point2, out var goDownwards2, out var goUpwards2);
                 if (goDownwards2)
                 {
                     velocity.Y += 0.05f;
                 }
                 if (goUpwards2)
                 {
                     velocity.Y -= 0.05f;
                 }
                 if (velocity.Y > 1f)
                 {
                     velocity.Y = 1f;
                 }
                 if (velocity.Y < -1f)
                 {
                     velocity.Y = -1f;
                 }
             }
             else
             {
                 velocity = Vector2.Lerp(velocity, value2, 0.07f);
             }
             if (WorldGen.SolidTile(point2))
             {
                 ai[3] = Math.Min(ai[3] + 2f, 400f);
             }
             else
             {
                 ai[3] = Math.Max(ai[3] - 1f, 0f);
             }
             break;
         }
         case 5:
         {
             localAI[1] = 0f;
             noTileCollide = true;
             bool flag2 = false;
             Tile tileSafely = Framing.GetTileSafely(new Point((int)ai[0], (int)ai[1]));
             if (!tileSafely.active() || !SceneMetrics.IsValidForOreFinder(tileSafely))
             {
                 flag2 = true;
             }
             if (ai[3] == 15f)
             {
                 SoundEngine.PlaySound(27, (int)position.X, (int)position.Y);
             }
             if (ai[3] <= 15f)
             {
                 velocity *= 0.9f;
             }
             else
             {
                 flag = true;
                 float num2 = 0f;
                 float num3 = ai[3] - 15f;
                 float num4 = 22f;
                 int num5 = (int)(num3 / 50f);
                 num2 = (float)Math.Cos((float)num5 * 1f) * ((float)Math.PI * 2f) / 16f;
                 num4 = (float)Math.Cos((float)num5 * 2f) * 10f + 8f;
                 num2 *= (float)direction;
                 Vector2 fairyCircleOffset = GetFairyCircleOffset(num3 / 50f, num2, num4);
                 Vector2 fairyCircleOffset2 = GetFairyCircleOffset(num3 / 50f + 0.02f, num2, num4);
                 velocity = fairyCircleOffset2 - fairyCircleOffset;
                 if (Main.player[target].Center.X > base.Center.X)
                 {
                     spriteDirection = -1;
                 }
                 else
                 {
                     spriteDirection = 1;
                 }
             }
             ai[3] += 1f;
             if (Main.netMode != 1 && ai[3] > 200f)
             {
                 active = false;
                 if (Main.netMode == 0)
                 {
                     FairyEffects(base.Center, type - 583);
                 }
                 else if (Main.netMode == 2)
                 {
                     netSkip = -1;
                     life = 0;
                     NetMessage.SendData(23, -1, -1, null, whoAmI);
                     NetMessage.SendData(112, -1, -1, null, 2, (int)base.Center.X, (int)base.Center.Y, 0f, type - 583);
                 }
             }
             break;
         }
         case 7:
             noTileCollide = true;
             velocity.X += 0.05f * (float)direction;
             velocity.X = MathHelper.Clamp(velocity.X, -10f, 10f);
             velocity.Y -= 0.025f;
             velocity.Y = MathHelper.Clamp(velocity.Y, -5f, 5f);
             EncourageDespawn(10);
             break;
         }
         dontTakeDamage = (dontTakeDamageFromHostiles = ai[2] > 1f);
         for (int k = 0; k < 200; k++)
         {
             if (k != whoAmI && Main.npc[k].active && Main.npc[k].aiStyle == 112 && Math.Abs(position.X - Main.npc[k].position.X) + Math.Abs(position.Y - Main.npc[k].position.Y) < (float)width * 1.5f)
             {
                 if (position.Y < Main.npc[k].position.Y)
                 {
                     velocity.Y -= 0.05f;
                 }
                 else
                 {
                     velocity.Y += 0.05f;
                 }
             }
         }
         if (!flag)
         {
             direction = ((velocity.X >= 0f) ? 1 : (-1));
             spriteDirection = -direction;
         }
         Color value3 = Color.HotPink;
         Color value4 = Color.LightPink;
         int num17 = 4;
         if (type == 584)
         {
             value3 = Color.LimeGreen;
             value4 = Color.LightSeaGreen;
         }
         if (type == 585)
         {
             value3 = Color.RoyalBlue;
             value4 = Color.LightBlue;
         }
         if ((int)Main.timeForVisualEffects % 2 == 0)
         {
             position += netOffset;
             Dust dust = Dust.NewDustDirect(base.Center - new Vector2(num17) * 0.5f, num17 + 4, num17 + 4, 278, 0f, 0f, 200, Color.Lerp(value3, value4, Main.rand.NextFloat()), 0.65f);
             dust.velocity *= 0f;
             dust.velocity += velocity * 0.3f;
             dust.noGravity = true;
             dust.noLight = true;
             position -= netOffset;
         }
         Lighting.AddLight(base.Center, value3.ToVector3() * 0.7f);
         if (Main.netMode != 2)
         {
             Player localPlayer = Main.LocalPlayer;
             if (!localPlayer.dead && localPlayer.HitboxForBestiaryNearbyCheck.Intersects(base.Hitbox))
             {
                 AchievementsHelper.HandleSpecialEvent(localPlayer, 22);
             }
         }
     }
References Entity.active, Tile.active(), Lighting.AddLight(), ai, aiStyle, NPCAimedTarget.Center, Entity.Center, Utils.CenteredRectangle(), collideX, collideY, Color, Player.dead, Entity.direction, Entity.DirectionFrom(), Entity.DirectionTo(), Entity.Distance(), dontTakeDamage, dontTakeDamageFromHostiles, EncourageDespawn(), FairyEffects(), GetBirdFlightRecommendation(), GetFairyCircleOffset(), GetFairyTreasureCoords(), GetTargetData(), Framing.GetTileSafely(), AchievementsHelper.HandleSpecialEvent(), NPCAimedTarget.Height, Entity.height, Player.HitboxForBestiaryNearbyCheck, WorldGen.InWorld(), SceneMetrics.IsValidForOreFinder(), lavaImmune, life, Tile.liquid, localAI, Main.LocalPlayer, Tile.nactive(), Main.netMode, netOffset, netSkip, netUpdate, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, noTileCollide, Main.npc, Entity.oldVelocity, Main.player, SoundEngine.PlaySound(), Entity.position, Main.rand, NetMessage.SendData(), Collision.SolidCollision(), WorldGen.SolidTile(), spriteDirection, target, TargetClosest(), Tile, Main.tile, Main.tileSolid, Main.timeForVisualEffects, NPCAimedTarget.Type, type, Tile.type, value, Dust.velocity, Entity.velocity, Entity.whoAmI, NPCAimedTarget.Width, and Entity.width.
Referenced by AI().