Terraria: NPC.AI_065_Butterflies
AI_065_Butterflies()
void NPC.AI_065_Butterflies () inline private
     {
         float num = ai[0];
         float num2 = ai[1];
         if (type == 661)
         {
             Vector3 rgb = Main.hslToRgb(Main.GlobalTimeWrappedHourly * 0.33f % 1f, 1f, 0.5f).ToVector3() * 0.3f;
             rgb += Vector3.One * 0.1f;
             Lighting.AddLight(base.Center, rgb);
             int num3 = 60;
             bool flag = false;
             int num4 = 50;
             NPCAimedTarget targetData = GetTargetData();
             if (targetData.Invalid || targetData.Center.Distance(base.Center) >= 300f)
             {
                 flag = true;
             }
             if (!Main.remixWorld && !targetData.Invalid && targetData.Type == NPCTargetType.Player && !Main.player[target].ZoneHallow)
             {
                 num4 = num3;
                 flag = true;
             }
             ai[2] = MathHelper.Clamp(ai[2] + (float)flag.ToDirectionInt(), 0f, num4);
             if (ai[2] >= (float)num3)
             {
                 active = false;
                 if (Main.netMode != 1)
                 {
                     NetMessage.SendData(23, -1, -1, null, whoAmI);
                 }
                 return;
             }
             Opacity = Utils.GetLerpValue(num3, (float)num4 / 2f, ai[2], clamped: true);
             if (ai[2] > 0f)
             {
                 int num5 = 1;
                 for (int i = 0; i < num5; i++)
                 {
                     if (Main.rand.Next(5) == 0)
                     {
                         float num6 = MathHelper.Lerp(0.9f, 0.6f, Opacity);
                         Color newColor = Main.hslToRgb(Main.GlobalTimeWrappedHourly * 0.3f % 1f, 1f, 0.5f) * 0.5f;
                         int num7 = Dust.NewDust(position, width, height, 267, 0f, 0f, 0, newColor);
                         Main.dust[num7].position = base.Center + Main.rand.NextVector2Circular(width, height);
                         Main.dust[num7].velocity *= Main.rand.NextFloat() * 0.8f;
                         Main.dust[num7].velocity += velocity * 0.6f;
                         Main.dust[num7].noGravity = true;
                         Main.dust[num7].fadeIn = 0.6f + Main.rand.NextFloat() * 0.7f * num6;
                         Main.dust[num7].scale = 0.35f;
                         if (num7 != 6000)
{
                             Dust dust = Dust.CloneDust(num7);
                             dust.scale /= 2f;
                             dust.fadeIn *= 0.85f;
                             dust.color = new Color(255, 255, 255, 255) * 0.5f;
                         }
                     }
                 }
             }
             dontTakeDamage = ai[2] >= (float)(num4 / 2);
         }
         if (Main.netMode != 1)
         {
             if (ai[2] == 0f && type != 661)
             {
                 int num8 = 0;
                 int num9 = 4;
                 int num10 = 6;
                 int num11 = 3;
                 int num12 = 7;
                 int num13 = 2;
                 int num14 = 1;
                 int num15 = 5;
                 int num16 = Main.rand.Next(100);
                 num16 = ((num16 == 0) ? num15 : ((num16 < 3) ? num14 : ((num16 < 9) ? num13 : ((num16 < 19) ? num12 : ((num16 < 34) ? num11 : ((num16 < 53) ? num10 : ((num16 >= 75) ? num8 : num9)))))));
                 ai[2] = 1 + num16;
             }
             if (ai[3] == 0f)
             {
                 ai[3] = (float)Main.rand.Next(75, 111) * 0.01f;
             }
             localAI[0] -= 1f;
             if (localAI[0] <= 0f)
             {
                 localAI[0] = Main.rand.Next(90, 240);
                 TargetClosest();
                 float num17 = Math.Abs(base.Center.X - Main.player[target].Center.X);
                 if (num17 > 700f && localAI[3] == 0f)
                 {
                     float num18 = (float)Main.rand.Next(50, 151) * 0.01f;
                     if (num17 > 1000f)
                     {
                         num18 = (float)Main.rand.Next(150, 201) * 0.01f;
                     }
                     else if (num17 > 850f)
                     {
                         num18 = (float)Main.rand.Next(100, 151) * 0.01f;
                     }
                     int num19 = direction * Main.rand.Next(100, 251);
                     int num20 = Main.rand.Next(-50, 51);
                     if (position.Y > Main.player[target].position.Y - 100f)
                     {
                         num20 -= Main.rand.Next(100, 251);
                     }
                     float num21 = num18 / (float)Math.Sqrt(num19 * num19 + num20 * num20);
                     num = (float)num19 * num21;
                     num2 = (float)num20 * num21;
                 }
                 else
                 {
                     localAI[3] = 1f;
                     float num22 = (float)Main.rand.Next(26, 301) * 0.01f;
                     int num23 = Main.rand.Next(-100, 101);
                     int num24 = Main.rand.Next(-100, 101);
                     float num25 = num22 / (float)Math.Sqrt(num23 * num23 + num24 * num24);
                     num = (float)num23 * num25;
                     num2 = (float)num24 * num25;
                 }
                 netUpdate = true;
             }
         }
         scale = ai[3];
         int num26 = 60;
         velocity.X = (velocity.X * (float)(num26 - 1) + num) / (float)num26;
         velocity.Y = (velocity.Y * (float)(num26 - 1) + num2) / (float)num26;
         if (velocity.Y > 0f)
         {
             int num27 = 3;
             int num28 = (int)base.Center.X / 16;
             int num29 = (int)base.Center.Y / 16;
             for (int j = num29; j < num29 + num27; j++)
             {
                 if (Main.tile[num28, j] != null && ((Main.tile[num28, j].nactive() && Main.tileSolid[Main.tile[num28, j].type]) || Main.tile[num28, j].liquid > 0))
                 {
                     num2 *= -1f;
                     if (velocity.Y > 0f)
                     {
                         velocity.Y *= 0.9f;
                     }
                 }
             }
         }
         if (velocity.Y < 0f)
         {
             int num30 = 30;
             bool flag2 = false;
             int num31 = (int)base.Center.X / 16;
             int num32 = (int)base.Center.Y / 16;
             for (int k = num32; k < num32 + num30; k++)
             {
                 if (Main.tile[num31, k] != null && Main.tile[num31, k].nactive() && Main.tileSolid[Main.tile[num31, k].type])
                 {
                     flag2 = true;
                 }
             }
             if (!flag2)
             {
                 num2 *= -1f;
                 if (velocity.Y < 0f)
                 {
                     velocity.Y *= 0.9f;
                 }
             }
         }
         if (localAI[1] > 0f)
         {
             localAI[1] -= 1f;
         }
         else
         {
             localAI[1] = 15f;
             if (type == 661)
             {
                 localAI[1] = 10f;
             }
             float num33 = 0f;
             Vector2 zero = Vector2.Zero;
             for (int l = 0; l < 200; l++)
             {
                 NPC nPC = Main.npc[l];
                 if (nPC.active && nPC.damage > 0 && !nPC.friendly && nPC.Hitbox.Distance(base.Center) <= 100f)
                 {
                     num33 += 1f;
                     zero += DirectionFrom(nPC.Center);
                 }
             }
             if (num33 > 0f)
             {
                 zero /= num33;
                 zero *= 2f;
                 velocity += zero;
                 if (velocity.Length() > 16f)
                 {
                     velocity = velocity.SafeNormalize(Vector2.Zero) * 16f;
                 }
             }
         }
         if (collideX)
         {
             num = ((!(velocity.X < 0f)) ? (0f - Math.Abs(num)) : Math.Abs(num));
             velocity.X *= -0.2f;
         }
         if (velocity.X < 0f)
         {
             direction = -1;
         }
         if (velocity.X > 0f)
         {
             direction = 1;
         }
         ai[0] = num;
         ai[1] = num2;
         if (type == 356)
         {
             catchItem = (short)(1994f + ai[2] - 1f);
         }
         if (type == 653)
         {
             position += netOffset;
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.6f, 0.3f, 0.1f);
             if (Main.rand.Next(60) == 0)
             {
                 int num34 = Dust.NewDust(position, width, height, 6, 0f, 0f, 254);
                 Main.dust[num34].velocity *= 0f;
             }
             position -= netOffset;
         }
     }
References Entity.active, Lighting.AddLight(), ai, catchItem, NPCAimedTarget.Center, Entity.Center, Dust.CloneDust(), collideX, Color, Dust.color, damage, Entity.direction, Entity.DirectionFrom(), dontTakeDamage, Main.dust, Dust.fadeIn, friendly, Utils.GetLerpValue(), GetTargetData(), Main.GlobalTimeWrappedHourly, Entity.height, Entity.Hitbox, Main.hslToRgb(), NPCAimedTarget.Invalid, Tile.liquid, localAI, Tile.nactive(), Main.netMode, netOffset, netUpdate, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Main.npc, Opacity, Main.player, Dust.position, Entity.position, Main.rand, Main.remixWorld, Dust.scale, scale, NetMessage.SendData(), target, TargetClosest(), Main.tile, Main.tileSolid, NPCAimedTarget.Type, type, Tile.type, Dust.velocity, Entity.velocity, Entity.whoAmI, Entity.width, and Player.ZoneHallow.
Referenced by AI().