Terraria: NPC.TransformElderSlime
TransformElderSlime()
static void NPC.TransformElderSlime (int npcIndex) inline static
     {
         if (Main.netMode == 1)
         {
             NetMessage.SendData(140, -1, -1, null, 2, npcIndex);
         }
         else if (!unlockedSlimeOldSpawn && Main.npc.IndexInRange(npcIndex))
         {
             NPC nPC = Main.npc[npcIndex];
             if (nPC.type == 685)
             {
                 unlockedSlimeOldSpawn = true;
                 NetMessage.SendData(7);
                 Vector2 vector = nPC.velocity;
                 nPC.Transform(679);
                 nPC.netUpdate = true;
                 nPC.velocity = vector;
                 ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.TownSlimeTransform, new ParticleOrchestraSettings
                 {
                     PositionInWorld = nPC.Center,
                     MovementVector = Vector2.Zero,
                     UniqueInfoPiece = 2
                 });
             }
         }
     }
References ParticleOrchestrator.BroadcastParticleSpawn(), Main.netMode, netUpdate, Main.npc, NetMessage.SendData(), Transform(), type, unlockedSlimeOldSpawn, and Entity.velocity.
Referenced by MessageBuffer.GetData(), and Main.HoverOverNPCs().