Terraria: NPC.AI_123_Deerclops_MakeSpikesForward
AI_123_Deerclops_MakeSpikesForward()
void NPC.AI_123_Deerclops_MakeSpikesForward (int AISLOT_PhaseCounter, NPCAimedTarget targetData) inline private
     {
         int num = 9;
         int num2 = 4;
         if (Main.netMode == 1)
         {
             return;
         }
         int num3 = num * num2;
         if (!(ai[AISLOT_PhaseCounter] < (float)num3))
         {
             Point sourceTileCoords = base.Bottom.ToTileCoordinates();
             int num4 = 20;
             int num5 = 1;
             sourceTileCoords.X += direction * 3;
             int num6 = (int)ai[AISLOT_PhaseCounter] - num3;
             if (num6 == 0)
             {
                 PunchCameraModifier modifier = new PunchCameraModifier(base.Center, new Vector2(0f, 1f), 20f, 6f, 30, 1000f, "Deerclops");
                 Main.instance.CameraModifiers.Add(modifier);
             }
             int num7 = 4;
             int num8 = num6 / num7 * num7;
             int num9 = num8 + num7;
             if (num6 % num7 != 0)
             {
                 num9 = num8;
             }
             for (int i = num8; i < num9 && i < num4; i++)
             {
                 int xOffset = i * num5;
                 AI_123_Deerclops_TryMakingSpike(ref sourceTileCoords, direction, num4, i, xOffset);
             }
         }
     }
References CameraModifierStack.Add(), ai, AI_123_Deerclops_TryMakingSpike(), Main.CameraModifiers, Entity.direction, Main.instance, and Main.netMode.
Referenced by AI_123_Deerclops().