Terraria: NPC.Teleport
Teleport()
void NPC.Teleport (Vector2 newPos, int Style = 0, int extraInfo = 0) inline
     {
         int extraInfo2 = 0;
         if (Style == 4)
         {
             extraInfo2 = lastPortalColorIndex;
         }
         float dustCountMult = ((teleportTime > 0f) ? 0.3f : 1f);
         Vector2 otherPosition = position;
         Main.TeleportEffect(getRect(), Style, extraInfo2, dustCountMult, TeleportationSide.Entry, newPos);
         position = newPos;
         if (Style == 4)
         {
             lastPortalColorIndex = extraInfo;
             extraInfo2 = lastPortalColorIndex;
         }
         Main.TeleportEffect(getRect(), Style, extraInfo2, dustCountMult, TeleportationSide.Exit, otherPosition);
         teleportTime = 1f;
         teleportStyle = Style;
         if (Main.netMode == 2 && Style != 4)
         {
             NetMessage.SendData(65, -1, -1, null, 1, whoAmI, newPos.X, newPos.Y, Style);
         }
     }
References Main.netMode, NetMessage.SendData(), and Main.TeleportEffect().
Referenced by AI_007_TownEntities(), MessageBuffer.GetData(), Wiring.Teleport(), and PortalHelper.TryGoingThroughPortals().