Terraria: NPC.DoDeathEvents_SummonDungeonSpirit
DoDeathEvents_SummonDungeonSpirit()
void NPC.DoDeathEvents_SummonDungeonSpirit (Player closestPlayer) inline private
     {
         if (lifeMax > 100 && type != 288 && value > 0f && HasPlayerTarget && Main.hardMode && downedPlantBoss && Main.player[target].ZoneDungeon)
         {
             int range = 13;
             if (Main.expertMode)
             {
                 range = 9;
             }
             if (closestPlayer.RollLuck(range) == 0 && Main.wallDungeon[Main.tile[(int)base.Center.X / 16, (int)base.Center.Y / 16].wall])
             {
                 NewNPC(GetSpawnSource_NPCHurt(), (int)base.Center.X, (int)base.Center.Y, 288);
             }
         }
     }
References downedPlantBoss, Main.expertMode, GetSpawnSource_NPCHurt(), Main.hardMode, HasPlayerTarget, lifeMax, NewNPC(), Main.player, Player.RollLuck(), target, Main.tile, type, value, Tile.wall, Main.wallDungeon, and Player.ZoneDungeon.
Referenced by DoDeathEvents().