Terraria: NPC.AI_108_DivingFlyer
AI_108_DivingFlyer()
void NPC.AI_108_DivingFlyer () inline private
     {
         //IL_0210: Unknown result type (might be due to invalid IL or missing references)
         //IL_0b8b: Unknown result type (might be due to invalid IL or missing references)
         //IL_07a2: Unknown result type (might be due to invalid IL or missing references)
         //IL_07a7: Unknown result type (might be due to invalid IL or missing references)
         //IL_0bb1: Unknown result type (might be due to invalid IL or missing references)
         //IL_0bb6: Unknown result type (might be due to invalid IL or missing references)
         //IL_090e: Unknown result type (might be due to invalid IL or missing references)
         //IL_07d0: Unknown result type (might be due to invalid IL or missing references)
         //IL_07d5: Unknown result type (might be due to invalid IL or missing references)
         //IL_0930: Unknown result type (might be due to invalid IL or missing references)
         //IL_0935: Unknown result type (might be due to invalid IL or missing references)
         //IL_0bef: Unknown result type (might be due to invalid IL or missing references)
         //IL_080d: Unknown result type (might be due to invalid IL or missing references)
         //IL_0812: Unknown result type (might be due to invalid IL or missing references)
         //IL_0827: Unknown result type (might be due to invalid IL or missing references)
         //IL_0c15: Unknown result type (might be due to invalid IL or missing references)
         //IL_0c1a: Unknown result type (might be due to invalid IL or missing references)
         rotation = velocity.ToRotation();
         float num = 0.4f;
         float num2 = 10f;
         float num3 = 200f;
         float num4 = 750f;
         float num5 = 30f;
         float num6 = 30f;
         float num7 = 0.95f;
         int num8 = 50;
         float num9 = 14f;
         float num10 = 30f;
         float num11 = 100f;
         float num12 = 20f;
         float num13 = 0f;
         float num14 = 7f;
         bool flag = true;
         bool flag2 = true;
         int num15 = 120;
         bool flag3 = false;
         bool flag4 = false;
         float num16 = 0.05f;
         float num17 = 0f;
         bool flag5 = false;
         switch (type)
         {
         case 558:
         case 559:
         case 560:
             flag4 = true;
             num = 0.7f;
             if (type == 559)
             {
                 num = 0.5f;
             }
             if (type == 560)
             {
                 num = 0.2f;
             }
             num2 = 3f;
             num3 = 400f;
             num4 = 500f;
             num5 = 90f;
             num6 = 20f;
             num7 = 0.95f;
             num8 = 0;
             num9 = 8f;
             num10 = 30f;
             num11 = 150f;
             num12 = 60f;
             num13 = 0.05f;
             num14 = 6f;
             flag2 = false;
             flag5 = true;
             break;
         case 574:
         case 575:
             flag4 = true;
             num = 0.6f;
             if (type == 575)
             {
                 num = 0.4f;
             }
             num2 = 4f;
             num3 = 400f;
             num4 = 500f;
             num5 = 90f;
             num6 = 30f;
             num7 = 0.95f;
             num8 = 3;
             num9 = 8f;
             num10 = 30f;
             num11 = 150f;
             num12 = 10f;
             num13 = 0.05f;
             num14 = 0f;
             num17 = -0.1f;
             flag3 = true;
             flag5 = true;
             break;
         }
         NPCUtils.TargetClosestOldOnesInvasion(this);
         NPCAimedTarget targetData = GetTargetData();
         if (flag5)
         {
             if (localAI[0] == 0f)
             {
                 alpha = 255;
             }
             if (localAI[0] == 30f)
             {
                 SoundEngine.PlayTrackedSound(SoundID.DD2_EtherianPortalSpawnEnemy, base.Center);
             }
             if (localAI[0] < 60f)
             {
                 localAI[0] += 1f;
                 alpha -= 5;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
                 int num18 = (int)localAI[0] / 10;
                 float num19 = base.Size.Length() / 2f;
                 num19 /= 20f;
                 int maxValue = 5;
                 if (type == 576 || type == 577)
                 {
                     maxValue = 1;
                 }
                 for (int i = 0; i < num18; i++)
                 {
                     if (Main.rand.Next(maxValue) == 0)
                     {
                         Dust dust = Dust.NewDustDirect(position, width, height, 27, velocity.X * 1f, 0f, 100);
                         dust.scale = 0.55f;
                         dust.fadeIn = 0.7f;
                         dust.velocity *= 0.1f * num19;
                         dust.velocity += velocity;
                     }
                 }
             }
         }
         if (flag4)
         {
             for (int j = 0; j < 200; j++)
             {
                 if (j != whoAmI && Main.npc[j].active && Main.npc[j].type == type && Math.Abs(position.X - Main.npc[j].position.X) + Math.Abs(position.Y - Main.npc[j].position.Y) < (float)width)
                 {
                     if (position.X < Main.npc[j].position.X)
                     {
                         velocity.X -= num16;
                     }
                     else
                     {
                         velocity.X += num16;
                     }
                     if (position.Y < Main.npc[j].position.Y)
                     {
                         velocity.Y -= num16;
                     }
                     else
                     {
                         velocity.Y += num16;
                     }
                 }
             }
         }
         if (Math.Sign(velocity.X) != 0)
         {
             spriteDirection = -Math.Sign(velocity.X);
         }
         if (rotation < -(float)Math.PI / 2f)
         {
             rotation += (float)Math.PI;
         }
         if (rotation > (float)Math.PI / 2f)
         {
             rotation -= (float)Math.PI;
         }
         num13 *= num12;
         if (Main.expertMode)
         {
             num *= Main.GameModeInfo.KnockbackToEnemiesMultiplier;
         }
         SlotId val;
         if (ai[0] == 0f)
         {
             knockBackResist = num;
             float num20 = num2;
             Vector2 center = base.Center;
             Vector2 vector = targetData.Center - center;
             Vector2 vector2 = vector - Vector2.UnitY * num3;
             float num21 = vector.Length();
             vector = Vector2.Normalize(vector) * num20;
             vector2 = Vector2.Normalize(vector2) * num20;
             bool flag6 = Collision.CanHit(base.Center, 1, 1, targetData.Center, 1, 1);
             if (ai[3] >= (float)num15)
             {
                 flag6 = true;
             }
             float num22 = 8f;
             flag6 = flag6 && vector.ToRotation() > (float)Math.PI / num22 && vector.ToRotation() < (float)Math.PI - (float)Math.PI / num22;
             if (num21 > num4 || !flag6)
             {
                 velocity.X = (velocity.X * (num5 - 1f) + vector2.X) / num5;
                 velocity.Y = (velocity.Y * (num5 - 1f) + vector2.Y) / num5;
                 if (targetData.Center.Y < base.Center.Y)
                 {
                     velocity.Y -= 0.2f;
                     if (velocity.Y < -10f)
                     {
                         velocity.Y = -10f;
                     }
                 }
                 if (!flag6)
                 {
                     ai[3] += 1f;
                     if (ai[3] == (float)num15)
                     {
                         netUpdate = true;
                     }
                 }
                 else
                 {
                     ai[3] = 0f;
                 }
             }
             else
             {
                 ai[0] = 1f;
                 ai[2] = vector.X;
                 ai[3] = vector.Y;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 1f)
         {
             knockBackResist = 0f;
             velocity *= num7;
             velocity.Y += num17;
             ai[1] += 1f;
             if (ai[1] == num6)
             {
                 if (type == 558 || type == 559 || type == 560)
                 {
                     float[] array = localAI;
                     val = SoundEngine.PlayTrackedSound(SoundID.DD2_WyvernDiveDown, base.Center);
                     array[1] = ((SlotId)(ref val)).ToFloat();
                     if (Main.rand.Next(5) == 0)
                     {
                         float[] array2 = localAI;
                         val = SoundEngine.PlayTrackedSound(SoundID.DD2_WyvernScream, base.Center);
                         array2[2] = ((SlotId)(ref val)).ToFloat();
                     }
                 }
                 else if (type == 574 || type == 575)
                 {
                     float[] array3 = localAI;
                     val = SoundEngine.PlayTrackedSound(SoundID.DD2_KoboldFlyerChargeScream, base.Center);
                     array3[1] = ((SlotId)(ref val)).ToFloat();
                     SoundEngine.PlayTrackedSound(SoundID.DD2_KoboldIgnite, base.Center);
                 }
             }
             if (ai[1] >= num6)
             {
                 ai[0] = 2f;
                 ai[1] = 0f;
                 netUpdate = true;
                 Vector2 vector3 = new Vector2(ai[2], ai[3]) + new Vector2(Main.rand.Next(-num8, num8 + 1), Main.rand.Next(-num8, num8 + 1)) * 0.04f;
                 vector3.Normalize();
                 vector3 *= num9;
                 velocity = vector3;
             }
         }
         else if (ai[0] == 2f)
         {
             if (ai[1] >= 20f && (type == 574 || type == 575))
             {
                 ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2]));
                 if (activeSound == null)
                 {
                     float[] array4 = localAI;
                     val = SoundEngine.PlayTrackedSound(SoundID.DD2_KoboldIgniteLoop, base.Center);
                     array4[2] = ((SlotId)(ref val)).ToFloat();
                 }
                 else
                 {
                     activeSound.Position = base.Center;
                 }
             }
             knockBackResist = 0f;
             float num23 = num10;
             ai[1] += 1f;
             bool flag7 = Vector2.Distance(base.Center, targetData.Center) > num11 && base.Center.Y > targetData.Center.Y;
             if (flag3)
             {
                 flag7 = false;
             }
             if ((ai[1] >= num23 && flag7) || velocity.Length() < num14)
             {
                 ai[0] = 0f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] = 0f;
                 velocity /= 2f;
                 netUpdate = true;
                 if (flag)
                 {
                     ai[1] = 45f;
                     ai[0] = 4f;
                 }
             }
             else
             {
                 Vector2 center2 = base.Center;
                 Vector2 vector4 = targetData.Center - center2;
                 vector4.Normalize();
                 if (vector4.HasNaNs())
                 {
                     vector4 = new Vector2(direction, 0f);
                 }
                 velocity = (velocity * (num12 - 1f) + vector4 * (velocity.Length() + num13)) / num12;
             }
             if (flag2 && Collision.SolidCollision(position, width, height))
             {
                 ai[0] = 3f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] = 0f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 4f)
         {
             ai[1] -= 3f;
             if (ai[1] <= 0f)
             {
                 ai[0] = 0f;
                 ai[1] = 0f;
                 netUpdate = true;
             }
             velocity *= 0.95f;
         }
         ActiveSound activeSound2 = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
         if (activeSound2 != null)
         {
             activeSound2.Position = base.Center;
         }
         else
         {
             float[] array5 = localAI;
             val = SlotId.Invalid;
             array5[1] = ((SlotId)(ref val)).ToFloat();
         }
         if (type == 558 || type == 559 || type == 560)
         {
             activeSound2 = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2]));
             if (activeSound2 != null)
             {
                 activeSound2.Position = base.Center;
             }
             else
             {
                 float[] array6 = localAI;
                 val = SlotId.Invalid;
                 array6[2] = ((SlotId)(ref val)).ToFloat();
             }
         }
         if (flag2 && ai[0] != 3f && Vector2.Distance(base.Center, targetData.Center) < 64f)
         {
             ai[0] = 3f;
             ai[1] = 0f;
             ai[2] = 0f;
             ai[3] = 0f;
             netUpdate = true;
         }
         if (ai[0] != 3f)
         {
             return;
         }
         position = base.Center;
         width = (height = 192);
         position.X -= width / 2;
         position.Y -= height / 2;
         velocity = Vector2.Zero;
         damage = GetAttackDamage_ScaledByStrength(80f);
         alpha = 255;
         if (ai[1] == 0f && (type == 574 || type == 575))
         {
             for (int k = 0; k < 4; k++)
             {
                 int num24 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                 Main.dust[num24].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
             }
             for (int l = 0; l < 20; l++)
             {
                 int num25 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 200, default(Color), 3.7f);
                 Main.dust[num25].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                 Main.dust[num25].noGravity = true;
                 Main.dust[num25].velocity *= 3f;
                 num25 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                 Main.dust[num25].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 4f;
                 Main.dust[num25].velocity *= 2f;
                 Main.dust[num25].noGravity = true;
                 Main.dust[num25].fadeIn = 2.5f;
             }
             for (int m = 0; m < 6; m++)
             {
                 int num26 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 0, default(Color), 2.7f);
                 Main.dust[num26].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                 Main.dust[num26].noGravity = true;
                 Main.dust[num26].velocity *= 3f;
             }
             for (int n = 0; n < 12; n++)
             {
                 int num27 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                 Main.dust[num27].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                 Main.dust[num27].noGravity = true;
                 Main.dust[num27].velocity *= 3f;
             }
             for (int num28 = 0; num28 < 5; num28++)
             {
                 int num29 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                 Main.gore[num29].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                 Main.gore[num29].velocity *= 0.3f;
                 Main.gore[num29].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                 Main.gore[num29].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
             }
         }
         ai[1] += 1f;
         if (ai[1] >= 3f)
         {
             SoundEngine.PlaySound(SoundID.Item14, position);
             life = 0;
             HitEffect();
             active = false;
         }
     }
References Entity.active, ai, alpha, Collision.CanHit(), NPCAimedTarget.Center, Color, damage, SoundID.DD2_EtherianPortalSpawnEnemy, SoundID.DD2_KoboldFlyerChargeScream, SoundID.DD2_KoboldIgnite, SoundID.DD2_KoboldIgniteLoop, SoundID.DD2_WyvernDiveDown, SoundID.DD2_WyvernScream, Entity.direction, Main.dust, Main.expertMode, Dust.fadeIn, SlotId.FromFloat(), Main.GameModeInfo, SoundEngine.GetActiveSound(), GetAttackDamage_ScaledByStrength(), GetTargetData(), Main.gore, Entity.height, HitEffect(), SlotId.Invalid, SoundID.Item14, knockBackResist, GameModeData.KnockbackToEnemiesMultiplier, life, localAI, netUpdate, Dust.NewDust(), Dust.NewDustDirect(), Gore.NewGore(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Dust.noGravity, Main.npc, SoundEngine.PlaySound(), SoundEngine.PlayTrackedSound(), ActiveSound.Position, Dust.position, Entity.position, Gore.position, Main.rand, rotation, Dust.scale, Collision.SolidCollision(), spriteDirection, NPCUtils.TargetClosestOldOnesInvasion(), type, Dust.velocity, Entity.velocity, Gore.velocity, Entity.whoAmI, and Entity.width.
Referenced by AI().