Terraria: NPC.AI_110_Betsy
AI_110_Betsy()
void NPC.AI_110_Betsy () inline private
     {
         //IL_04f4: Unknown result type (might be due to invalid IL or missing references)
         //IL_0486: Unknown result type (might be due to invalid IL or missing references)
         //IL_0b13: Unknown result type (might be due to invalid IL or missing references)
         //IL_0c83: Unknown result type (might be due to invalid IL or missing references)
         //IL_1363: Unknown result type (might be due to invalid IL or missing references)
         //IL_1376: Unknown result type (might be due to invalid IL or missing references)
         //IL_137b: Unknown result type (might be due to invalid IL or missing references)
         //IL_0693: Unknown result type (might be due to invalid IL or missing references)
         //IL_0698: Unknown result type (might be due to invalid IL or missing references)
         //IL_10a7: Unknown result type (might be due to invalid IL or missing references)
         //IL_117f: Unknown result type (might be due to invalid IL or missing references)
         NPCUtils.TargetClosestBetsy(this, faceTarget: false);
         NPCAimedTarget targetData = GetTargetData();
         int num = -1;
         float num2 = 1f;
         int num3 = 35;
         int num4 = 35;
         float num5 = 10f;
         float num6 = 0.45f;
         float num7 = 7.5f;
         float num8 = 30f;
         float num9 = 30f;
         float num10 = 23f;
         float num11 = 600f;
         float num12 = 12f;
         float num13 = 40f;
         float num14 = 80f;
         float num15 = num13 + num14;
         float num16 = 1500f;
         float num17 = 60f;
         float num18 = 13f;
         float amount = 1f / 30f;
         float num19 = 12f;
         int num20 = 10;
         int num21 = 6 * num20;
         float num22 = 60f;
         float num23 = num17 + (float)num21 + num22;
         float num24 = 60f;
         float num25 = 1f;
         float num26 = (float)Math.PI * 2f * (num25 / num24);
         float num27 = 0.1f;
         float num28 = 32f;
         float num29 = 90f;
         float num30 = 20f;
         _ = ai[0];
         _ = -1f;
         SlotId val;
         if (ai[0] == 0f)
         {
             if ((ai[1] += 1f) >= num5)
             {
                 ai[1] = 0f;
                 ai[0] = 1f;
                 ai[2] = 0f;
                 netUpdate = true;
             }
         }
         else if (ai[0] == 1f)
         {
             if (ai[2] == 0f)
             {
                 ai[2] = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
             }
             Vector2 destination = targetData.Center + new Vector2((0f - ai[2]) * 300f, -200f);
             Vector2 desiredVelocity = DirectionTo(destination) * num7;
             SimpleFlyMovement(desiredVelocity, num6);
             int num31 = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
             direction = (spriteDirection = num31);
             if ((ai[1] += 1f) >= num8)
             {
                 int num32 = 1;
                 if (ai[3] == 5f && Main.rand.Next(3) == 0)
                 {
                     ai[3] += 1f;
                 }
                 switch ((int)ai[3])
                 {
                 case 0:
                 case 1:
                 case 3:
                     num32 = 2;
                     break;
                 case 2:
                     num32 = 3;
                     break;
                 case 4:
                     num32 = 4;
                     break;
                 case 5:
                     num32 = 5;
                     break;
                 case 6:
                     num32 = 3;
                     break;
                 case 7:
                     num32 = 6;
                     break;
                 }
                 ai[0] = num32;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] += 1f;
                 netUpdate = true;
                 if (ai[3] >= 8f)
                 {
                     ai[3] = 0f;
                 }
                 switch (num32)
                 {
                 case 2:
                 {
                     Vector2 vector2 = DirectionTo(targetData.Center);
                     spriteDirection = ((vector2.X > 0f) ? 1 : (-1));
                     rotation = vector2.ToRotation();
                     if (spriteDirection == -1)
                     {
                         rotation += (float)Math.PI;
                     }
                     velocity = vector2 * num10;
                     break;
                 }
                 case 3:
                 {
                     Vector2 vector3 = new Vector2((targetData.Center.X > base.Center.X) ? 1 : (-1), 0f);
                     spriteDirection = ((vector3.X > 0f) ? 1 : (-1));
                     velocity = vector3 * -2f;
                     break;
                 }
                 case 5:
                 {
                     Vector2 vector = DirectionTo(targetData.Center);
                     spriteDirection = ((vector.X > 0f) ? 1 : (-1));
                     rotation = vector.ToRotation();
                     if (spriteDirection == -1)
                     {
                         rotation += (float)Math.PI;
                     }
                     velocity = vector * num28;
                     break;
                 }
                 }
             }
         }
         else if (ai[0] == 2f)
         {
             if (ai[1] == 0f)
             {
                 SoundEngine.PlayTrackedSound(SoundID.DD2_BetsyWindAttack, base.Center);
             }
             if ((ai[1] += 1f) >= num9)
             {
                 ai[0] = 1f;
                 ai[1] = 0f;
                 ai[2] = 0f;
             }
         }
         else if (ai[0] == 3f)
         {
             ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2]));
             if (activeSound != null)
             {
                 activeSound.Position = base.Center;
             }
             ai[1] += 1f;
             int num33 = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
             ai[2] = num33;
             if (ai[1] < num13)
             {
                 Vector2 vector4 = targetData.Center + new Vector2((float)num33 * (0f - num11), -250f);
                 Vector2 vector5 = DirectionTo(vector4) * num12;
                 if (Distance(vector4) < num12)
                 {
                     base.Center = vector4;
                 }
                 else
                 {
                     position += vector5;
                 }
                 if (Vector2.Distance(vector4, base.Center) < 16f)
                 {
                     ai[1] = num13 - 1f;
                 }
                 num2 = 1.5f;
             }
             if (ai[1] == num13)
             {
                 int num34 = ((targetData.Center.X > base.Center.X) ? 1 : (-1));
                 velocity = new Vector2(num34, 0f) * 10f;
                 direction = (spriteDirection = num34);
                 if (Main.netMode != 1)
                 {
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center, velocity, 687, num3, 0f, Main.myPlayer, 0f, whoAmI);
                 }
                 float[] array = localAI;
                 val = SoundEngine.PlayTrackedSound(SoundID.DD2_BetsyFlameBreath, base.Center);
                 array[2] = ((SlotId)(ref val)).ToFloat();
             }
             if (ai[1] >= num13)
             {
                 num2 = 1.5f;
                 if (Math.Abs(targetData.Center.X - base.Center.X) > 550f && Math.Abs(velocity.X) < 20f)
                 {
                     velocity.X += (float)Math.Sign(velocity.X) * 0.5f;
                 }
             }
             if (ai[1] >= num15)
             {
                 ai[0] = 1f;
                 ai[1] = 0f;
                 ai[2] = 0f;
             }
         }
         else if (ai[0] == 4f)
         {
             int num35 = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
             ai[2] = num35;
             if (ai[1] < num17)
             {
                 Vector2 vector6 = targetData.Center + new Vector2((float)num35 * (0f - num16), -350f);
                 Vector2 value = DirectionTo(vector6) * num18;
                 velocity = Vector2.Lerp(velocity, value, amount);
                 int num36 = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
                 direction = (spriteDirection = num36);
                 if (Vector2.Distance(vector6, base.Center) < 16f)
                 {
                     ai[1] = num17 - 1f;
                 }
                 num2 = 1.5f;
             }
             else if (ai[1] == num17)
             {
                 Vector2 v = DirectionTo(targetData.Center);
                 v.Y *= 0.25f;
                 v = v.SafeNormalize(Vector2.UnitX * direction);
                 spriteDirection = ((v.X > 0f) ? 1 : (-1));
                 rotation = v.ToRotation();
                 if (spriteDirection == -1)
                 {
                     rotation += (float)Math.PI;
                 }
                 velocity = v * num19;
             }
             else
             {
                 position.X += DirectionTo(targetData.Center).X * 7f;
                 position.Y += DirectionTo(targetData.Center + new Vector2(0f, -400f)).Y * 6f;
                 if (ai[1] <= num23 - num22)
                 {
                     num2 = 1.5f;
                 }
                 float num37 = 30f;
                 Vector2 vector7 = base.Center + new Vector2((110f + num37) * (float)direction, 20f).RotatedBy(rotation);
                 int num38 = (int)(ai[1] - num17 + 1f);
                 if (num38 <= num21 && num38 % num20 == 0 && Main.netMode != 1)
                 {
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector7, velocity, 686, num4, 0f, Main.myPlayer);
                 }
             }
             if (ai[1] > num23 - num22)
             {
                 velocity.Y -= 0.1f;
             }
             ai[1] += 1f;
             if (ai[1] >= num23)
             {
                 ai[0] = 1f;
                 ai[1] = 0f;
                 ai[2] = 0f;
             }
         }
         else if (ai[0] == 5f)
         {
             velocity = velocity.RotatedBy((0f - num26) * (float)direction);
             position.Y -= num27;
             position += DirectionTo(targetData.Center) * 10f;
             rotation -= num26 * (float)direction;
             num2 *= 0.7f;
             if (ai[1] == 1f)
             {
                 SoundEngine.PlayTrackedSound(SoundID.DD2_BetsyFlyingCircleAttack, base.Center);
             }
             if ((ai[1] += 1f) >= num24)
             {
                 ai[0] = 1f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 velocity /= 2f;
             }
         }
         else if (ai[0] == 6f)
         {
             if (ai[1] == 0f)
             {
                 Vector2 destination2 = targetData.Center + new Vector2(0f, -200f);
                 Vector2 desiredVelocity2 = DirectionTo(destination2) * num7 * 2f;
                 SimpleFlyMovement(desiredVelocity2, num6 * 2f);
                 int num39 = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
                 direction = (spriteDirection = num39);
                 ai[2] += 1f;
                 if (Distance(targetData.Center) < 350f || ai[2] >= 180f)
                 {
                     ai[1] = 1f;
                     netUpdate = true;
                 }
             }
             else
             {
                 if (ai[1] == 1f)
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_BetsyScream);
                 }
                 if (ai[1] < num30)
                 {
                     velocity *= 0.95f;
                 }
                 else
                 {
                     velocity *= 0.98f;
                 }
                 if (ai[1] == num30)
                 {
                     if (velocity.Y > 0f)
                     {
                         velocity.Y /= 3f;
                     }
                     velocity.Y -= 3f;
                 }
                 num2 *= 0.85f;
                 if (ai[1] == 20f || ai[1] == 25f || ai[1] == 30f)
                 {
                     Point point = base.Center.ToTileCoordinates();
                     int num40 = 30;
                     int num41 = 35;
                     int num42 = 4;
                     for (int i = point.X - num40; i <= point.X + num40; i++)
                     {
                         bool flag = false;
                         for (int j = point.Y - num41 / 3; j < point.Y + num41; j++)
{
                             Tile tileSafely = Framing.GetTileSafely(i, j);
                             bool flag2 = tileSafely.active() && Main.tileSolid[tileSafely.type] && !Main.tileFrameImportant[tileSafely.type];
                             if (flag && flag2)
{
                                 int num43 = WorldGen.KillTile_GetTileDustAmount(fail: true, tileSafely);
                                 for (int k = 0; k < num43; k++)
{
                                     Dust obj = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                                     obj.velocity.Y -= 3f + (float)num42 * 1.5f;
                                     obj.velocity.Y *= Main.rand.NextFloat();
                                     obj.scale += (float)num42 * 0.03f;
                                 }
                                 for (int l = 0; l < num43 - 1; l++)
{
                                     Dust obj2 = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                                     obj2.velocity.Y -= 1f + (float)num42;
                                     obj2.velocity.Y *= Main.rand.NextFloat();
                                 }
                                 if (num43 > 0 && Main.rand.Next(3) != 0)
{
                                     float num44 = Math.Abs(point.X - i) / (num40 / 2);
                                     Gore gore = Gore.NewGoreDirect(position, Vector2.Zero, 61 + Main.rand.Next(3), 1f - (float)num42 * 0.15f + num44 * 0.5f);
                                     gore.velocity.Y -= 0.1f + (float)num42 * 0.5f + num44 * (float)num42 * 1f;
                                     gore.velocity.Y *= Main.rand.NextFloat();
                                     gore.position = new Vector2(i * 16 + 20, j * 16 + 20);
                                 }
                             }
                             flag = !flag2;
                         }
                     }
                 }
                 bool flag3 = ai[1] == 20f || ai[1] == 45f || ai[1] == 70f;
                 if (CountNPCS(560) > 4)
                 {
                     flag3 = false;
                 }
                 if (flag3 && Main.netMode != 1)
                 {
                     for (int m = 0; m < 1; m++)
                     {
                         Vector2 vector8 = base.Center + ((float)Math.PI * 2f * Main.rand.NextFloat()).ToRotationVector2() * new Vector2(2f, 1f) * 300f * (0.6f + Main.rand.NextFloat() * 0.4f);
                         if (Vector2.Distance(vector8, targetData.Center) > 100f)
{
                             Point point2 = vector8.ToPoint();
                             NewNPC(GetSpawnSourceForNPCFromNPCAI(), point2.X, point2.Y, 560, whoAmI);
                             SoundEngine.PlayTrackedSound(SoundID.DD2_BetsySummon, vector8);
                         }
                     }
                     List<NPC> list = new List<NPC>();
                     for (int n = 0; n < 200; n++)
                     {
                         NPC nPC = Main.npc[n];
                         if (nPC.active && nPC.type == 549)
{
                             list.Add(nPC);
                         }
                     }
                     if (list.Count > 0)
                     {
                         for (int num45 = 0; num45 < 3; num45++)
{
                             NPC nPC2 = list[Main.rand.Next(list.Count)];
                             Point point3 = nPC2.Center.ToPoint();
                             NewNPC(GetSpawnSourceForNPCFromNPCAI(), point3.X, point3.Y, 560);
                             SoundEngine.PlayTrackedSound(SoundID.DD2_BetsySummon, nPC2.Center);
                         }
                     }
                 }
                 ai[1] += 1f;
             }
             if (ai[1] >= num29)
             {
                 ai[0] = 1f;
                 ai[1] = 0f;
                 ai[2] = 0f;
             }
         }
         localAI[0] += num2;
         if (localAI[0] >= 36f)
         {
             localAI[0] = 0f;
         }
         if (num != -1)
         {
             localAI[0] = num * 4;
         }
         if ((localAI[1] += 1f) >= 60f)
         {
             localAI[1] = 0f;
         }
         float num46 = DirectionTo(targetData.Center).ToRotation();
         float num47 = 0.04f;
         switch ((int)ai[0])
         {
         case 2:
         case 5:
             num47 = 0f;
             break;
         case 3:
             num47 = 0.01f;
             num46 = 0f;
             if (spriteDirection == -1)
             {
                 num46 -= (float)Math.PI;
             }
             if (ai[1] >= num13)
             {
                 num46 += (float)spriteDirection * (float)Math.PI / 12f;
                 num47 = 0.05f;
             }
             break;
         case 4:
             num47 = 0.01f;
             num46 = (float)Math.PI;
             if (spriteDirection == 1)
             {
                 num46 += (float)Math.PI;
             }
             break;
         case 6:
             num47 = 0.02f;
             num46 = 0f;
             if (spriteDirection == -1)
             {
                 num46 -= (float)Math.PI;
             }
             break;
         }
         if (spriteDirection == -1)
         {
             num46 += (float)Math.PI;
         }
         if (num47 != 0f)
         {
             rotation = rotation.AngleTowards(num46, num47);
         }
         if (SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2])) == null)
         {
             float[] array2 = localAI;
             val = SlotId.Invalid;
             array2[2] = ((SlotId)(ref val)).ToFloat();
         }
     }
References Entity.active, Tile.active(), ai, NPCAimedTarget.Center, Entity.Center, CountNPCS(), SoundID.DD2_BetsyFlameBreath, SoundID.DD2_BetsyFlyingCircleAttack, SoundID.DD2_BetsyScream, SoundID.DD2_BetsySummon, SoundID.DD2_BetsyWindAttack, Entity.direction, Entity.DirectionTo(), Entity.Distance(), Main.dust, SlotId.FromFloat(), SoundEngine.GetActiveSound(), GetSpawnSource_ForProjectile(), GetSpawnSourceForNPCFromNPCAI(), GetTargetData(), Framing.GetTileSafely(), SlotId.Invalid, WorldGen.KillTile_GetTileDustAmount(), WorldGen.KillTile_MakeTileDust(), localAI, Main.myPlayer, Main.netMode, netUpdate, Gore.NewGoreDirect(), NewNPC(), Projectile.NewProjectile(), UnifiedRandom.Next(), Main.npc, SoundEngine.PlayTrackedSound(), ActiveSound.Position, Entity.position, Gore.position, Main.rand, rotation, Dust.scale, SimpleFlyMovement(), spriteDirection, NPCUtils.TargetClosestBetsy(), Main.tileFrameImportant, Main.tileSolid, type, Tile.type, value, Dust.velocity, Entity.velocity, Gore.velocity, and Entity.whoAmI.
Referenced by AI().