Terraria: NPC.CatchNPC
CatchNPC()
static void NPC.CatchNPC (int i, int who = -1) inline static
     {
         if (!Main.npc[i].active)
         {
             return;
         }
         if (who == -1)
         {
             who = Main.myPlayer;
         }
         if (Main.netMode == 1)
         {
             Main.npc[i].active = false;
             NetMessage.SendData(70, -1, -1, null, i, who);
         }
         else if (Main.npc[i].catchItem > 0)
         {
             if (Main.npc[i].type == 687)
             {
                 Main.npc[i].TryTeleportingCaughtMysticFrog();
             }
             else if (Main.npc[i].SpawnedFromStatue)
             {
                 Vector2 vector = Main.npc[i].Center - new Vector2(20f);
                 Utils.PoofOfSmoke(vector);
                 Main.npc[i].active = false;
                 NetMessage.SendData(23, -1, -1, null, i);
                 NetMessage.SendData(106, -1, -1, null, (int)vector.X, vector.Y);
             }
             else
             {
                 new Item().SetDefaults(Main.npc[i].catchItem);
                 Item.NewItem(GetSpawnSource_NPCCatch(who), (int)Main.player[who].Center.X, (int)Main.player[who].Center.Y, 0, 0, Main.npc[i].catchItem, 1, noBroadcast: false, 0, noGrabDelay: true);
                 Main.npc[i].active = false;
                 NetMessage.SendData(23, -1, -1, null, i);
             }
         }
     }
References Entity.active, catchItem, Entity.Center, Main.myPlayer, Main.netMode, Item.NewItem(), Main.npc, Main.player, Utils.PoofOfSmoke(), NetMessage.SendData(), Item.SetDefaults(), SpawnedFromStatue, TryTeleportingCaughtMysticFrog(), and type.
Referenced by MessageBuffer.GetData(), and Player.ItemCheck_CatchCritters().