Terraria: NPC.SpawnPassiveShadowHands
SpawnPassiveShadowHands()
void NPC.SpawnPassiveShadowHands (float lifePercent, int shadowHandDamage) inline private
     {
         int num = (int)Utils.Remap(lifePercent, 1f, 0f, 80f, 40f);
         localAI[2] += 1f;
         int num2 = (int)localAI[2];
         if (num2 % num != 0)
         {
             return;
         }
         int num3 = num2 / num;
         if (num2 / num >= 3)
         {
             localAI[2] = 0f;
         }
         for (int i = 0; i < 255; i++)
         {
             if (Boss_CanShootExtraAt(i, num3 % 3, 3, 1200f, alwaysSkipMainTarget: false))
             {
                 Projectile.RandomizeInsanityShadowFor(Main.player[i], isHostile: true, out var spawnposition, out var spawnvelocity, out var ai, out var ai2);
                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), spawnposition, spawnvelocity, 965, shadowHandDamage, 0f, Main.myPlayer, ai, ai2);
             }
         }
     }
References ai, Boss_CanShootExtraAt(), GetSpawnSource_ForProjectile(), localAI, Main.myPlayer, Projectile.NewProjectile(), Main.player, Projectile.RandomizeInsanityShadowFor(), and Utils.Remap().
Referenced by AI_123_Deerclops().