Terraria: NPC.SimpleFlyMovement
SimpleFlyMovement()
void NPC.SimpleFlyMovement (Vector2 desiredVelocity, float moveSpeed) inline
     {
         if (velocity.X < desiredVelocity.X)
         {
             velocity.X += moveSpeed;
             if (velocity.X < 0f && desiredVelocity.X > 0f)
             {
                 velocity.X += moveSpeed;
             }
         }
         else if (velocity.X > desiredVelocity.X)
         {
             velocity.X -= moveSpeed;
             if (velocity.X > 0f && desiredVelocity.X < 0f)
             {
                 velocity.X -= moveSpeed;
             }
         }
         if (velocity.Y < desiredVelocity.Y)
         {
             velocity.Y += moveSpeed;
             if (velocity.Y < 0f && desiredVelocity.Y > 0f)
             {
                 velocity.Y += moveSpeed;
             }
         }
         else if (velocity.Y > desiredVelocity.Y)
         {
             velocity.Y -= moveSpeed;
             if (velocity.Y > 0f && desiredVelocity.Y < 0f)
             {
                 velocity.Y -= moveSpeed;
             }
         }
     }
References Entity.velocity.
Referenced by AI(), AI_069_DukeFishron(), AI_110_Betsy(), AI_117_BloodNautilus(), AI_120_HallowBoss(), and AI_121_QueenSlime_FlyMovement().