Terraria: NPC.UpdateNPC_BuffApplyVFX
UpdateNPC_BuffApplyVFX()
void NPC.UpdateNPC_BuffApplyVFX () inline private
     {
         if (!canDisplayBuffs)
         {
             return;
         }
         position += netOffset;
         if (markedByScytheWhip && Main.rand.Next(3) == 0)
         {
             ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.BlackLightningSmall, new ParticleOrchestraSettings
             {
                 MovementVector = Main.rand.NextVector2Circular(1f, 1f),
                 PositionInWorld = Main.rand.NextVector2FromRectangle(base.Hitbox)
             });
         }
         if (poisoned && Main.rand.Next(30) == 0)
         {
             Dust dust = Dust.NewDustDirect(position, width, height, 46, 0f, 0f, 120, default(Color), 0.2f);
             dust.noGravity = true;
             dust.fadeIn = 1.9f;
         }
         if (venom && Main.rand.Next(10) == 0)
         {
             Dust dust2 = Dust.NewDustDirect(position, width, height, 171, 0f, 0f, 100, default(Color), 0.5f);
             dust2.noGravity = true;
             dust2.fadeIn = 1.5f;
         }
         if (shadowFlame && Main.rand.Next(5) < 4)
         {
             Dust dust3 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 27, velocity.X * 0.4f, velocity.Y * 0.4f, 180, default(Color), 1.95f);
             dust3.noGravity = true;
             dust3.velocity *= 0.75f;
             dust3.velocity.X *= 0.75f;
             dust3.velocity.Y -= 1f;
             if (Main.rand.Next(4) == 0)
             {
                 dust3.noGravity = false;
                 dust3.scale *= 0.5f;
             }
         }
         if (onFire)
         {
             if (Main.rand.Next(4) < 3)
             {
                 Dust dust4 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 6, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                 dust4.noGravity = true;
                 dust4.velocity *= 1.8f;
                 dust4.velocity.Y -= 0.5f;
                 if (Main.rand.Next(4) == 0)
                 {
                     dust4.noGravity = false;
                     dust4.scale *= 0.5f;
                 }
             }
             Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 1f, 0.3f, 0.1f);
         }
         if (onFire3)
         {
             if (Main.rand.Next(4) < 3)
             {
                 Dust dust5 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 6, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                 dust5.noGravity = true;
                 dust5.velocity *= 1.8f;
                 dust5.velocity.Y -= 0.5f;
                 if (Main.rand.Next(4) == 0)
                 {
                     dust5.noGravity = false;
                     dust5.scale *= 0.5f;
                 }
                 dust5.customData = 0;
             }
             Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 1f, 0.3f, 0.1f);
         }
         if (daybreak)
         {
             if (Main.rand.Next(4) < 3)
             {
                 Dust dust6 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 158, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                 dust6.noGravity = true;
                 dust6.velocity *= 2.8f;
                 dust6.velocity.Y -= 0.5f;
                 if (Main.rand.Next(4) == 0)
                 {
                     dust6.noGravity = false;
                     dust6.scale *= 0.5f;
                 }
             }
             Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 1f, 0.3f, 0.1f);
         }
         if (betsysCurse)
         {
             if (Main.rand.Next(4) < 3)
             {
                 Dust dust7 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 55, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                 dust7.noGravity = true;
                 dust7.velocity *= 2.8f;
                 dust7.velocity.Y -= 1.5f;
                 dust7.noGravity = false;
                 dust7.scale = 0.9f;
                 dust7.color = new Color(0, 0, 180, 255);
                 dust7.velocity *= 0.2f;
             }
             Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 0.6f, 0.1f, 0.9f);
         }
         if (oiled && Main.rand.Next(3) != 0)
         {
             int num = 175;
             Color newColor = new Color(0, 0, 0, 250);
             Vector2 vector = position;
             vector.X -= 2f;
             vector.Y -= 2f;
             if (Main.rand.Next(2) == 0)
             {
                 Dust dust8 = Dust.NewDustDirect(vector, width + 4, height + 2, 4, 0f, 0f, num, newColor, 1.4f);
                 if (Main.rand.Next(2) == 0)
                 {
                     dust8.alpha += 25;
                 }
                 if (Main.rand.Next(2) == 0)
                 {
                     dust8.alpha += 25;
                 }
                 dust8.noLight = true;
                 dust8.velocity *= 0.2f;
                 dust8.velocity.Y += 0.2f;
                 dust8.velocity += velocity;
             }
         }
         if (dryadWard && velocity.X != 0f && Main.rand.Next(4) == 0)
         {
             Dust dust9 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y + (float)height - 2f), width + 4, 4, 163, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 1.5f);
             dust9.noGravity = true;
             dust9.noLight = true;
             dust9.velocity *= 0f;
         }
         if (dryadBane && Main.rand.Next(4) == 0)
         {
             Dust dust10 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y), width + 4, height, 163, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 1.5f);
             dust10.noGravity = true;
             dust10.velocity *= new Vector2(Main.rand.NextFloat() * 4f - 2f, 0f);
             dust10.noLight = true;
         }
         if (loveStruck && Main.rand.Next(5) == 0)
         {
             Vector2 vector2 = new Vector2(Main.rand.Next(-10, 11), Main.rand.Next(-10, 11));
             vector2.Normalize();
             vector2.X *= 0.66f;
             int num2 = Gore.NewGore(position + new Vector2(Main.rand.Next(width + 1), Main.rand.Next(height + 1)), vector2 * Main.rand.Next(3, 6) * 0.33f, 331, (float)Main.rand.Next(40, 121) * 0.01f);
             Main.gore[num2].sticky = false;
             Main.gore[num2].velocity *= 0.4f;
             Main.gore[num2].velocity.Y -= 0.6f;
         }
         if (stinky && Main.rand.Next(5) == 0)
         {
             Vector2 vector3 = new Vector2(Main.rand.Next(-10, 11), Main.rand.Next(-10, 11));
             vector3.Normalize();
             vector3.X *= 0.66f;
             vector3.Y = Math.Abs(vector3.Y);
             Vector2 vector4 = vector3 * Main.rand.Next(3, 5) * 0.25f;
             Dust dust11 = Dust.NewDustDirect(position, width, height, 188, vector4.X, vector4.Y * 0.5f, 100, default(Color), 1.5f);
             dust11.velocity *= 0.1f;
             dust11.velocity.Y -= 0.5f;
         }
         if (dripping && Main.rand.Next(4) != 0)
         {
             Vector2 vector5 = position;
             vector5.X -= 2f;
             vector5.Y -= 2f;
             if (Main.rand.Next(2) == 0)
             {
                 Dust dust12 = Dust.NewDustDirect(vector5, width + 4, height + 2, 211, 0f, 0f, 50, default(Color), 0.8f);
                 if (Main.rand.Next(2) == 0)
                 {
                     dust12.alpha += 25;
                 }
                 if (Main.rand.Next(2) == 0)
                 {
                     dust12.alpha += 25;
                 }
                 dust12.noLight = true;
                 dust12.velocity *= 0.2f;
                 dust12.velocity.Y += 0.2f;
                 dust12.velocity += velocity;
             }
             else
             {
                 Dust dust13 = Dust.NewDustDirect(vector5, width + 8, height + 8, 211, 0f, 0f, 50, default(Color), 1.1f);
                 if (Main.rand.Next(2) == 0)
                 {
                     dust13.alpha += 25;
                 }
                 if (Main.rand.Next(2) == 0)
                 {
                     dust13.alpha += 25;
                 }
                 dust13.noLight = true;
                 dust13.noGravity = true;
                 dust13.velocity *= 0.2f;
                 dust13.velocity.Y += 1f;
                 dust13.velocity += velocity;
             }
         }
         if (drippingSlime && Main.rand.Next(4) != 0)
         {
             int num3 = 175;
             Color newColor2 = new Color(0, 80, 255, 100);
             Vector2 vector6 = position;
             vector6.X -= 2f;
             vector6.Y -= 2f;
             if (Main.rand.Next(2) == 0)
             {
                 Dust dust14 = Dust.NewDustDirect(vector6, width + 4, height + 2, 4, 0f, 0f, num3, newColor2, 1.4f);
                 if (Main.rand.Next(2) == 0)
                 {
                     dust14.alpha += 25;
                 }
                 if (Main.rand.Next(2) == 0)
                 {
                     dust14.alpha += 25;
                 }
                 dust14.noLight = true;
                 dust14.velocity *= 0.2f;
                 dust14.velocity.Y += 0.2f;
                 dust14.velocity += velocity;
             }
         }
         if (drippingSparkleSlime && Main.rand.Next(4) != 0)
         {
             int num4 = 150;
             Vector2 vector7 = position;
             vector7.X -= 2f;
             vector7.Y -= 2f;
             if (Main.rand.Next(2) == 0)
             {
                 Dust dust15 = Dust.NewDustDirect(vector7, width + 4, height + 2, 243, 0f, 0f, num4);
                 if (Main.rand.Next(2) == 0)
                 {
                     dust15.alpha += 25;
                 }
                 if (Main.rand.Next(2) == 0)
                 {
                     dust15.alpha += 25;
                 }
                 dust15.noLight = true;
                 dust15.velocity *= 0.2f;
                 dust15.velocity.Y += 0.2f;
                 dust15.velocity += velocity;
             }
         }
         if (onFrostBurn)
         {
             if (Main.rand.Next(4) < 3)
             {
                 Dust dust16 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 135, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                 dust16.noGravity = true;
                 dust16.velocity *= 1.8f;
                 dust16.velocity.Y -= 0.5f;
                 if (Main.rand.Next(4) == 0)
                 {
                     dust16.noGravity = false;
                     dust16.scale *= 0.5f;
                 }
             }
             Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 0.1f, 0.6f, 1f);
         }
         if (onFrostBurn2)
         {
             if (Main.rand.Next(4) < 3)
             {
                 Dust dust17 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 135, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                 dust17.noGravity = true;
                 dust17.velocity *= 1.8f;
                 dust17.velocity.Y -= 0.5f;
                 if (Main.rand.Next(4) == 0)
                 {
                     dust17.noGravity = false;
                     dust17.scale *= 0.5f;
                 }
             }
             Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 0.1f, 0.6f, 1f);
         }
         if (onFire2)
         {
             if (Main.rand.Next(4) < 3)
             {
                 Dust dust18 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 75, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                 dust18.noGravity = true;
                 dust18.velocity *= 1.8f;
                 dust18.velocity.Y -= 0.5f;
                 if (Main.rand.Next(4) == 0)
                 {
                     dust18.noGravity = false;
                     dust18.scale *= 0.5f;
                 }
             }
             Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 1f, 0.3f, 0.1f);
         }
         netShimmer = false;
         if (shimmering)
         {
             shimmerTransparency += 0.01f;
             if (Main.netMode != 1 && (double)shimmerTransparency > 0.9)
             {
                 GetShimmered();
             }
             if (shimmerTransparency > 1f)
             {
                 shimmerTransparency = 1f;
             }
         }
         else if (shimmerTransparency > 0f)
         {
             if (justHit)
             {
                 shimmerTransparency -= 0.1f;
             }
             if (buffImmune[353])
             {
                 shimmerTransparency -= 0.015f;
             }
             else
             {
                 shimmerTransparency -= 0.001f;
             }
             if (shimmerTransparency < 0f)
             {
                 shimmerTransparency = 0f;
             }
         }
         position -= netOffset;
     }
References Lighting.AddLight(), Dust.alpha, Color, Dust.color, Dust.customData, Dust.fadeIn, Main.gore, Main.netMode, Dust.NewDustDirect(), Gore.NewGore(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.rand, ParticleOrchestrator.RequestParticleSpawn(), Dust.scale, Gore.sticky, Dust.velocity, and Gore.velocity.