Terraria: NPC.UpdateNPC_TeleportVisuals
UpdateNPC_TeleportVisuals()
void NPC.UpdateNPC_TeleportVisuals () inline private
     {
         if (!(teleportTime > 0f))
         {
             return;
         }
         if (teleportStyle == 0)
         {
             if ((float)Main.rand.Next(100) <= 100f * teleportTime * 2f)
             {
                 int num = Dust.NewDust(new Vector2(getRect().X, getRect().Y), getRect().Width, getRect().Height, 159);
                 Main.dust[num].scale = teleportTime * 1.5f;
                 Main.dust[num].noGravity = true;
                 Main.dust[num].velocity *= 1.1f;
             }
         }
         else if (teleportStyle == 4)
         {
             teleportTime -= 0.02f;
             if ((float)Main.rand.Next(100) <= 100f * teleportTime)
             {
                 Dust obj = Main.dust[Dust.NewDust(position, width, height, 263)];
                 obj.color = PortalHelper.GetPortalColor(lastPortalColorIndex);
                 obj.noLight = true;
                 obj.noGravity = true;
                 obj.scale = 1.2f;
                 obj.fadeIn = 0.4f;
             }
         }
         else if (teleportStyle == 12)
         {
             teleportTime -= 0.02f;
             if ((float)Main.rand.Next(100) <= 100f * teleportTime)
             {
                 Dust obj2 = Main.dust[Dust.NewDust(position, width, height, 263)];
                 obj2.color = Main.hslToRgb((float)(Main.timeForVisualEffects / 60.0) % 1f, 1f, 0.75f, 0);
                 obj2.noLight = true;
                 obj2.noGravity = true;
                 obj2.scale = 1.2f;
                 obj2.fadeIn = 0.4f;
             }
         }
         else if (teleportStyle == 13)
         {
             teleportTime = 0f;
         }
         teleportTime = Math.Max(0f, teleportTime - 0.005f);
     }
References Dust.color, Main.dust, Dust.fadeIn, PortalHelper.GetPortalColor(), Main.hslToRgb(), Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.rand, Dust.scale, Main.timeForVisualEffects, Dust.velocity, X, and Y.