Terraria: NPC.Boss_CanShootExtraAt
Boss_CanShootExtraAt()
bool NPC.Boss_CanShootExtraAt (int playerIndex, int rotationIndexToAttack, int rotationSize, float attackScanDistance, bool alwaysSkipMainTarget = true) inline
     {
         if (playerIndex == target && alwaysSkipMainTarget)
         {
             return false;
         }
         if (playerIndex % rotationSize != rotationIndexToAttack)
         {
             return false;
         }
         Player player = Main.player[playerIndex];
         if (!player.active || player.dead || !playerInteraction[playerIndex])
         {
             return false;
         }
         if (Distance(player.Center) > attackScanDistance)
         {
             return false;
         }
         return true;
     }
References Entity.active, Entity.Center, Player.dead, Entity.Distance(), Main.player, playerInteraction, and target.
Referenced by AI_120_HallowBoss(), and SpawnPassiveShadowHands().