Terraria: NPC.SetFrameSize
SetFrameSize()
void NPC.SetFrameSize () inline
     {
         Main.instance.LoadNPC(type);
         if (setFrameSize)
         {
             frame = new Rectangle(0, 0, TextureAssets.Npc[type].Width(), TextureAssets.Npc[type].Height() / Main.npcFrameCount[type]);
             setFrameSize = false;
         }
     }
References frame, Main.instance, Main.LoadNPC(), TextureAssets.Npc, Main.npcFrameCount, setFrameSize, and type.
Referenced by Main.DrawNPCDirect(), and UnlockableNPCEntryIcon.SimulateFirstHover().