Terraria: NPC.SpawnStardustMark_StardustTower
SpawnStardustMark_StardustTower()
void NPC.SpawnStardustMark_StardustTower () inline private
     {
         List<int> list = new List<int>();
         if (CountNPCS(405) + CountNPCS(406) < 2)
         {
             list.Add(405);
         }
         if (CountNPCS(402) < 2)
         {
             list.Add(402);
         }
         if (CountNPCS(407) < 1)
         {
             list.Add(407);
         }
         if (list.Count > 0)
         {
             int num = Utils.SelectRandom(Main.rand, list.ToArray());
             ai[1] = 30 * Main.rand.Next(5, 16);
             int num2 = Main.rand.Next(3, 6);
             int num3 = Main.rand.Next(0, 4);
             int num4 = 0;
             List<Tuple<Vector2, int, int>> list2 = new List<Tuple<Vector2, int, int>>();
             List<Vector2> list3 = new List<Vector2>();
             list2.Add(Tuple.Create(base.Top - Vector2.UnitY * 120f, num2, 0));
             int num5 = 0;
             int num6 = list2.Count;
             while (list2.Count > 0)
             {
                 Vector2 item = list2[0].Item1;
                 int num7 = 1;
                 int num8 = 1;
                 if (num5 > 0 && num3 > 0 && (Main.rand.Next(3) != 0 || num5 == 1))
                 {
                     num8 = Main.rand.Next(Math.Max(1, list2[0].Item2));
                     num7++;
                     num3--;
                 }
                 for (int i = 0; i < num7; i++)
                 {
                     int num9 = list2[0].Item3;
                     if (num5 == 0)
                     {
                         num9 = Utils.SelectRandom<int>(Main.rand, -1, 1);
                     }
                     else if (i == 1)
                     {
                         num9 *= -1;
                     }
                     float num10 = ((num5 % 2 == 0) ? 0f : ((float)Math.PI)) + (0.5f - Main.rand.NextFloat()) * ((float)Math.PI / 4f) + (float)num9 * ((float)Math.PI / 4f) * (float)(num5 % 2 == 0).ToDirectionInt();
                     float num11 = 100f + 50f * Main.rand.NextFloat();
                     int num12 = list2[0].Item2;
                     if (i != 0)
                     {
                         num12 = num8;
                     }
                     if (num5 == 0)
                     {
                         num10 = (0.5f - Main.rand.NextFloat()) * ((float)Math.PI / 4f);
                         num11 = 100f + 100f * Main.rand.NextFloat();
                     }
                     Vector2 vector = (-Vector2.UnitY).RotatedBy(num10) * num11;
                     if (num12 - 1 < 0)
                     {
                         vector = Vector2.Zero;
                     }
                     num4 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), item.X, item.Y, vector.X, vector.Y, 540, 0, 0f, Main.myPlayer, (float)(-num5) * 10f, 0.5f + Main.rand.NextFloat() * 0.5f);
                     list3.Add(item + vector);
                     if (num5 < num2 && list2[0].Item2 > 0)
                     {
                         list2.Add(Tuple.Create(item + vector, num12 - 1, num9));
                     }
                 }
                 list2.Remove(list2[0]);
                 if (--num6 == 0)
                 {
                     num6 = list2.Count;
                     num5++;
                 }
             }
             Main.projectile[num4].localAI[0] = num;
         }
         else
         {
             ai[1] = 30f;
         }
     }
References ai, CountNPCS(), GetSpawnSource_ForProjectile(), Projectile.localAI, Main.myPlayer, Projectile.NewProjectile(), UnifiedRandom.Next(), Main.projectile, Main.rand, and Utils.ToDirectionInt().
Referenced by AI().