Terraria: NPC.AI_005_EaterOfSouls
AI_005_EaterOfSouls()
void NPC.AI_005_EaterOfSouls () inline private
     {
         if (type == 210 || type == 211)
         {
             NPCUtils.TargetClosestNonBees(this);
         }
         else if (target < 0 || target <= 255 || Main.player[target].dead)
         {
             TargetClosest();
         }
         if (type == 619)
         {
             if (Main.dayTime)
             {
                 velocity.Y -= 0.3f;
                 EncourageDespawn(60);
             }
             position += netOffset;
             if (alpha == 255)
             {
                 spriteDirection = direction;
                 velocity.Y = -6f;
                 for (int i = 0; i < 35; i++)
                 {
                     Dust dust = Dust.NewDustDirect(position, width, height, 5);
                     dust.velocity *= 1f;
                     dust.scale = 1f + Main.rand.NextFloat() * 0.5f;
                     dust.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                     dust.velocity += velocity * 0.5f;
                 }
             }
             alpha -= 15;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (alpha != 0)
             {
                 for (int j = 0; j < 2; j++)
                 {
                     Dust dust2 = Dust.NewDustDirect(position, width, height, 5);
                     dust2.velocity *= 1f;
                     dust2.scale = 1f + Main.rand.NextFloat() * 0.5f;
                     dust2.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                     dust2.velocity += velocity * 0.3f;
                 }
             }
             position -= netOffset;
         }
         NPCAimedTarget targetData = GetTargetData();
         bool flag = false;
         if (targetData.Type == NPCTargetType.Player)
         {
             flag = Main.player[target].dead;
         }
         float num = 6f;
         float num2 = 0.05f;
         if (type == 6 || type == 173)
         {
             num = 4f;
             num2 = 0.02f;
             if (type == 6 && Main.expertMode)
             {
                 num2 = 0.035f;
             }
             if (Main.remixWorld)
             {
                 num2 = 0.06f;
                 num = 5f;
             }
         }
         else if (type == 94)
         {
             num = 4.2f;
             num2 = 0.022f;
         }
         else if (type == 619)
         {
             num = 6f;
             num2 = 0.1f;
         }
         else if (type == 252)
         {
             if (targetData.Type != 0 && Collision.CanHit(this, targetData))
             {
                 num = 6f;
                 num2 = 0.1f;
             }
             else
             {
                 num2 = 0.01f;
                 num = 2f;
             }
         }
         else if (type == 42 || (type >= 231 && type <= 235))
         {
             num = 3.5f;
             num2 = 0.021f;
             if (type == 231)
             {
                 num = 3f;
                 num2 = 0.017f;
             }
             num *= 1f - scale;
             num2 *= 1f - scale;
             if ((double)(position.Y / 16f) < Main.worldSurface)
             {
                 if (Main.player[target].position.Y - position.Y > 300f && velocity.Y < 0f)
                 {
                     velocity.Y *= 0.97f;
                 }
                 if (Main.player[target].position.Y - position.Y < 80f && velocity.Y > 0f)
                 {
                     velocity.Y *= 0.97f;
                 }
             }
         }
         else if (type == 205)
         {
             num = 3.25f;
             num2 = 0.018f;
         }
         else if (type == 176)
         {
             num = 4f;
             num2 = 0.017f;
         }
         else if (type == 23)
         {
             num = 1f;
             num2 = 0.03f;
         }
         else if (type == 5)
         {
             num = 5f;
             num2 = 0.03f;
         }
         else if (type == 210 || type == 211)
         {
             ai[1] += 1f;
             float num3 = (ai[1] - 60f) / 60f;
             if (num3 > 1f)
             {
                 num3 = 1f;
             }
             else
             {
                 if (velocity.X > 6f)
                 {
                     velocity.X = 6f;
                 }
                 if (velocity.X < -6f)
                 {
                     velocity.X = -6f;
                 }
                 if (velocity.Y > 6f)
                 {
                     velocity.Y = 6f;
                 }
                 if (velocity.Y < -6f)
                 {
                     velocity.Y = -6f;
                 }
             }
             num = 5f;
             num2 = 0.1f;
             num2 *= num3;
         }
         else if (type == 139 && Main.zenithWorld)
         {
             num = 3f;
         }
         Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
         float num4 = targetData.Position.X + (float)(targetData.Width / 2);
         float num5 = targetData.Position.Y + (float)(targetData.Height / 2);
         num4 = (int)(num4 / 8f) * 8;
         num5 = (int)(num5 / 8f) * 8;
         vector.X = (int)(vector.X / 8f) * 8;
         vector.Y = (int)(vector.Y / 8f) * 8;
         num4 -= vector.X;
         num5 -= vector.Y;
         float num6 = (float)Math.Sqrt(num4 * num4 + num5 * num5);
         float num7 = num6;
         bool flag2 = false;
         if (num6 > 600f)
         {
             flag2 = true;
         }
         if (num6 == 0f)
         {
             num4 = velocity.X;
             num5 = velocity.Y;
         }
         else
         {
             num6 = num / num6;
             num4 *= num6;
             num5 *= num6;
         }
         bool num8 = type == 6 || type == 139 || type == 173 || type == 205;
         bool flag3 = type == 42 || type == 94 || type == 619 || type == 176 || type == 210 || type == 211 || (type >= 231 && type <= 235);
         bool flag4 = type != 173 && type != 6 && type != 42 && (type < 231 || type > 235) && type != 94 && type != 139 && type != 619;
         if (num8 || flag3)
         {
             if (num7 > 100f || flag3)
             {
                 ai[0] += 1f;
                 if (ai[0] > 0f)
                 {
                     velocity.Y += 0.023f;
                 }
                 else
                 {
                     velocity.Y -= 0.023f;
                 }
                 if (ai[0] < -100f || ai[0] > 100f)
                 {
                     velocity.X += 0.023f;
                 }
                 else
                 {
                     velocity.X -= 0.023f;
                 }
                 if (ai[0] > 200f)
                 {
                     ai[0] = -200f;
                 }
             }
             if (num7 < 150f && (type == 6 || type == 94 || type == 173 || type == 619))
             {
                 velocity.X += num4 * 0.007f;
                 velocity.Y += num5 * 0.007f;
             }
         }
         if (flag)
         {
             num4 = (float)direction * num / 2f;
             num5 = (0f - num) / 2f;
         }
         else if (type == 619 && base.Center.Y > targetData.Center.Y - 200f)
         {
             velocity.Y -= 0.3f;
         }
         if (type == 139 && ai[3] != 0f)
         {
             if (IsMechQueenUp)
             {
                 NPC nPC = Main.npc[mechQueen];
                 Vector2 vector2 = new Vector2(26f * ai[3], 0f);
                 int num9 = (int)ai[2];
                 if (num9 < 0 || num9 >= 200)
                 {
                     num9 = FindFirstNPC(134);
                     ai[2] = num9;
                     netUpdate = true;
                 }
                 if (num9 > -1)
                 {
                     NPC nPC2 = Main.npc[num9];
                     if (!nPC2.active || nPC2.type != 134)
                     {
                         dontTakeDamage = false;
                         if (ai[3] > 0f)
{
                             netUpdate = true;
                         }
                         ai[3] = 0f;
                     }
                     else
                     {
                         Vector2 spinningpoint = nPC2.Center + vector2;
                         spinningpoint = spinningpoint.RotatedBy(nPC2.rotation, nPC2.Center);
                         base.Center = spinningpoint;
                         velocity = nPC.velocity;
                         dontTakeDamage = true;
                     }
                 }
                 else
                 {
                     dontTakeDamage = false;
                     if (ai[3] > 0f)
                     {
                         netUpdate = true;
                     }
                     ai[3] = 0f;
                 }
             }
             else
             {
                 dontTakeDamage = false;
                 if (ai[3] > 0f)
                 {
                     netUpdate = true;
                 }
                 ai[3] = 0f;
             }
         }
         else
         {
             if (type == 139)
             {
                 dontTakeDamage = false;
             }
             if (velocity.X < num4)
             {
                 velocity.X += num2;
                 if (flag4 && velocity.X < 0f && num4 > 0f)
                 {
                     velocity.X += num2;
                 }
             }
             else if (velocity.X > num4)
             {
                 velocity.X -= num2;
                 if (flag4 && velocity.X > 0f && num4 < 0f)
                 {
                     velocity.X -= num2;
                 }
             }
             if (velocity.Y < num5)
             {
                 velocity.Y += num2;
                 if (flag4 && velocity.Y < 0f && num5 > 0f)
                 {
                     velocity.Y += num2;
                 }
             }
             else if (velocity.Y > num5)
             {
                 velocity.Y -= num2;
                 if (flag4 && velocity.Y > 0f && num5 < 0f)
                 {
                     velocity.Y -= num2;
                 }
             }
         }
         if (type == 23)
         {
             if (num4 > 0f)
             {
                 spriteDirection = 1;
                 rotation = (float)Math.Atan2(num5, num4);
             }
             else if (num4 < 0f)
             {
                 spriteDirection = -1;
                 rotation = (float)Math.Atan2(num5, num4) + 3.14f;
             }
         }
         else if (type == 139)
         {
             localAI[0] += 1f;
             if (ai[3] != 0f)
             {
                 localAI[0] += 2f;
             }
             if (justHit)
             {
                 localAI[0] = 0f;
             }
             float num10 = 120f;
             if (IsMechQueenUp)
             {
                 num10 = 360f;
             }
             if (Main.netMode != 1 && localAI[0] >= num10)
             {
                 localAI[0] = 0f;
                 if (targetData.Type != 0 && Collision.CanHit(this, targetData))
                 {
                     int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(25f, 22f);
                     int num11 = 84;
                     Vector2 vector3 = new Vector2(num4, num5);
                     if (IsMechQueenUp)
                     {
                         Vector2 v = targetData.Center - base.Center - targetData.Velocity * 20f;
                         float num12 = 8f;
                         vector3 = v.SafeNormalize(Vector2.UnitY) * num12;
                     }
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector.X, vector.Y, vector3.X, vector3.Y, num11, attackDamage_ForProjectiles, 0f, Main.myPlayer);
                 }
             }
             int num13 = (int)position.X + width / 2;
             int num14 = (int)position.Y + height / 2;
             num13 /= 16;
             num14 /= 16;
             if (WorldGen.InWorld(num13, num14) && !WorldGen.SolidTile(num13, num14))
             {
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.3f, 0.1f, 0.05f);
             }
             if (num4 > 0f)
             {
                 spriteDirection = 1;
                 rotation = (float)Math.Atan2(num5, num4);
             }
             if (num4 < 0f)
             {
                 spriteDirection = -1;
                 rotation = (float)Math.Atan2(num5, num4) + 3.14f;
             }
         }
         else if (type == 6 || type == 94 || type == 173 || type == 619)
         {
             rotation = (float)Math.Atan2(num5, num4) - 1.57f;
         }
         else if (type == 42 || type == 176 || type == 205 || (type >= 231 && type <= 235))
         {
             if (velocity.X > 0f)
             {
                 spriteDirection = 1;
             }
             if (velocity.X < 0f)
             {
                 spriteDirection = -1;
             }
             rotation = velocity.X * 0.1f;
         }
         else
         {
             rotation = (float)Math.Atan2(velocity.Y, velocity.X) - 1.57f;
         }
         if (type == 6 || type == 619 || type == 23 || type == 42 || type == 94 || type == 139 || type == 173 || type == 176 || type == 205 || type == 210 || type == 211 || (type >= 231 && type <= 235))
         {
             float num15 = 0.7f;
             if (type == 6 || type == 173)
             {
                 num15 = 0.4f;
             }
             if (collideX)
             {
                 netUpdate = true;
                 velocity.X = oldVelocity.X * (0f - num15);
                 if (direction == -1 && velocity.X > 0f && velocity.X < 2f)
                 {
                     velocity.X = 2f;
                 }
                 if (direction == 1 && velocity.X < 0f && velocity.X > -2f)
                 {
                     velocity.X = -2f;
                 }
             }
             if (collideY)
             {
                 netUpdate = true;
                 velocity.Y = oldVelocity.Y * (0f - num15);
                 if (velocity.Y > 0f && (double)velocity.Y < 1.5)
                 {
                     velocity.Y = 2f;
                 }
                 if (velocity.Y < 0f && (double)velocity.Y > -1.5)
                 {
                     velocity.Y = -2f;
                 }
             }
             position += netOffset;
             if (type == 619)
             {
                 int num16 = Dust.NewDust(position, width, height, 5, velocity.X * 0.2f, velocity.Y * 0.2f, 100);
                 Main.dust[num16].velocity *= 0.5f;
             }
             else if (type != 42 && type != 139 && type != 176 && type != 205 && type != 210 && type != 211 && type != 252 && (type < 231 || type > 235) && Main.rand.Next(20) == 0)
             {
                 int num17 = 18;
                 if (type == 173)
                 {
                     num17 = 5;
                 }
                 int num18 = Dust.NewDust(new Vector2(position.X, position.Y + (float)height * 0.25f), width, (int)((float)height * 0.5f), num17, velocity.X, 2f, 75, color, scale);
                 Main.dust[num18].velocity.X *= 0.5f;
                 Main.dust[num18].velocity.Y *= 0.1f;
             }
             position -= netOffset;
         }
         else if (type != 252 && Main.rand.Next(40) == 0)
         {
             int num19 = Dust.NewDust(new Vector2(position.X, position.Y + (float)height * 0.25f), width, (int)((float)height * 0.5f), 5, velocity.X, 2f);
             Main.dust[num19].velocity.X *= 0.5f;
             Main.dust[num19].velocity.Y *= 0.1f;
         }
         if ((type == 6 || type == 94 || type == 173 || type == 619) && wet)
         {
             if (velocity.Y > 0f)
             {
                 velocity.Y *= 0.95f;
             }
             velocity.Y -= 0.3f;
             if (velocity.Y < -2f)
             {
                 velocity.Y = -2f;
             }
         }
         if (type == 205 && wet)
         {
             if (velocity.Y > 0f)
             {
                 velocity.Y *= 0.95f;
             }
             velocity.Y -= 0.5f;
             if (velocity.Y < -4f)
             {
                 velocity.Y = -4f;
             }
             TargetClosest();
         }
         if (type == 42 || type == 176 || (type >= 231 && type <= 235))
         {
             if (wet)
             {
                 if (velocity.Y > 0f)
                 {
                     velocity.Y *= 0.95f;
                 }
                 velocity.Y -= 0.5f;
                 if (velocity.Y < -4f)
                 {
                     velocity.Y = -4f;
                 }
                 TargetClosest();
             }
             if (ai[1] == 101f)
             {
                 SoundEngine.PlaySound(SoundID.Item17, position);
                 ai[1] = 0f;
             }
             if (Main.netMode != 1)
             {
                 ai[1] += (float)Main.rand.Next(5, 20) * 0.1f * scale;
                 if (type == 176)
                 {
                     ai[1] += (float)Main.rand.Next(5, 20) * 0.1f * scale;
                 }
                 if (Main.getGoodWorld)
                 {
                     ai[1] += (float)Main.rand.Next(5, 20) * 0.1f * scale;
                 }
                 if (targetData.Type == NPCTargetType.Player)
                 {
                     Player player = Main.player[target];
                     if (player != null && player.stealth == 0f && player.itemAnimation == 0)
                     {
                         ai[1] = 0f;
                     }
                 }
                 if (ai[1] >= 130f)
                 {
                     if (targetData.Type != 0 && Collision.CanHit(this, targetData))
                     {
                         float num20 = 8f;
                         Vector2 vector4 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)(height / 2));
                         float num21 = targetData.Center.X - vector4.X + (float)Main.rand.Next(-20, 21);
                         float num22 = targetData.Center.Y - vector4.Y + (float)Main.rand.Next(-20, 21);
                         if ((num21 < 0f && velocity.X < 0f) || (num21 > 0f && velocity.X > 0f))
{
                             float num23 = (float)Math.Sqrt(num21 * num21 + num22 * num22);
                             num23 = num20 / num23;
                             num21 *= num23;
                             num22 *= num23;
                             int num24 = (int)(10f * scale);
                             if (type == 176)
{
                                 num24 = (int)(30f * scale);
                             }
                             int num25 = 55;
                             int num26 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector4.X, vector4.Y, num21, num22, num25, num24, 0f, Main.myPlayer);
                             Main.projectile[num26].timeLeft = 300;
                             ai[1] = 101f;
                             netUpdate = true;
                         }
                         else
{
                             ai[1] = 0f;
                         }
                     }
                     else
                     {
                         ai[1] = 0f;
                     }
                 }
             }
         }
         if (type == 139 && flag2)
         {
             if ((velocity.X > 0f && num4 > 0f) || (velocity.X < 0f && num4 < 0f))
             {
                 int num27 = 12;
                 if (IsMechQueenUp)
                 {
                     num27 = 5;
                 }
                 if (Math.Abs(velocity.X) < (float)num27)
                 {
                     velocity.X *= 1.05f;
                 }
             }
             else
             {
                 velocity.X *= 0.9f;
             }
         }
         if (type == 139 && IsMechQueenUp && ai[2] == 0f)
         {
             Vector2 center = GetTargetData().Center;
             Vector2 v2 = center - base.Center;
             int num28 = 120;
             if (v2.Length() < (float)num28)
             {
                 base.Center = center - v2.SafeNormalize(Vector2.UnitY) * num28;
             }
         }
         if (Main.netMode != 1)
         {
             if (Main.getGoodWorld && type == 6 && AnyNPCs(13))
             {
                 if (justHit)
                 {
                     localAI[0] = 0f;
                 }
                 localAI[0] += 1f;
                 if (localAI[0] == 60f)
                 {
                     if (targetData.Type != 0 && Collision.CanHit(this, targetData))
                     {
                         NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2) + velocity.X), (int)(position.Y + (float)(height / 2) + velocity.Y), 666);
                     }
                     localAI[0] = 0f;
                 }
             }
             if (type == 94 && !flag)
             {
                 if (justHit)
                 {
                     localAI[0] = 0f;
                 }
                 localAI[0] += 1f;
                 if (localAI[0] == 180f)
                 {
                     if (targetData.Type != 0 && Collision.CanHit(this, targetData))
                     {
                         NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2) + velocity.X), (int)(position.Y + (float)(height / 2) + velocity.Y), 112);
                     }
                     localAI[0] = 0f;
                 }
             }
             if (type == 619 && !flag)
             {
                 if (justHit)
                 {
                     localAI[0] += 10f;
                 }
                 localAI[0] += 1f;
                 if (localAI[0] >= 120f)
                 {
                     if (targetData.Type != 0 && Collision.CanHit(this, targetData))
                     {
                         if ((base.Center - targetData.Center).Length() < 400f)
{
                             Vector2 vector5 = DirectionTo(new Vector2(targetData.Center.X, targetData.Position.Y));
                             velocity = -vector5 * 5f;
                             netUpdate = true;
                             localAI[0] = 0f;
                             vector5 = DirectionTo(new Vector2(targetData.Center.X + (float)Main.rand.Next(-100, 101), targetData.Position.Y + (float)Main.rand.Next(-100, 101)));
                             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center, vector5 * 15f, 811, 35, 1f, Main.myPlayer);
                         }
                         else
{
                             localAI[0] = 50f;
                         }
                     }
                     else
                     {
                         localAI[0] = 50f;
                     }
                 }
             }
         }
         if ((Main.IsItDay() && type != 173 && type != 619 && type != 6 && type != 23 && type != 42 && type != 94 && type != 176 && type != 205 && type != 210 && type != 211 && type != 252 && (type < 231 || type > 235)) || flag)
         {
             velocity.Y -= num2 * 2f;
             EncourageDespawn(10);
         }
         if (((velocity.X > 0f && oldVelocity.X < 0f) || (velocity.X < 0f && oldVelocity.X > 0f) || (velocity.Y > 0f && oldVelocity.Y < 0f) || (velocity.Y < 0f && oldVelocity.Y > 0f)) && !justHit)
         {
             netUpdate = true;
         }
     }
References Entity.active, Lighting.AddLight(), ai, alpha, AnyNPCs(), Collision.CanHit(), NPCAimedTarget.Center, Entity.Center, collideX, collideY, color, Main.dayTime, Player.dead, Entity.direction, Entity.DirectionTo(), dontTakeDamage, Main.dust, EncourageDespawn(), Main.expertMode, Dust.fadeIn, FindFirstNPC(), GetAttackDamage_ForProjectiles(), Main.getGoodWorld, GetSpawnSource_ForProjectile(), GetSpawnSourceForNPCFromNPCAI(), GetTargetData(), NPCAimedTarget.Height, Entity.height, WorldGen.InWorld(), Main.IsItDay(), IsMechQueenUp, SoundID.Item17, Player.itemAnimation, justHit, localAI, mechQueen, Main.myPlayer, Main.netMode, netOffset, netUpdate, Dust.NewDust(), Dust.NewDustDirect(), NewNPC(), Projectile.NewProjectile(), UnifiedRandom.Next(), Main.npc, Entity.oldVelocity, Main.player, SoundEngine.PlaySound(), NPCAimedTarget.Position, Entity.position, Main.projectile, Main.rand, Main.remixWorld, rotation, Dust.scale, scale, WorldGen.SolidTile(), spriteDirection, Player.stealth, target, TargetClosest(), NPCUtils.TargetClosestNonBees(), Projectile.timeLeft, NPCAimedTarget.Type, type, NPCAimedTarget.Velocity, Dust.velocity, Entity.velocity, Entity.wet, NPCAimedTarget.Width, Entity.width, Main.worldSurface, and Main.zenithWorld.
Referenced by AI().