Terraria: NPC.NPCLoot_DropHeals
NPCLoot_DropHeals()
void NPC.NPCLoot_DropHeals (Player closestPlayer) inline private
     {
         NPCLoot_DropCommonLifeAndMana(closestPlayer);
         switch (type)
         {
         case 305:
         case 306:
         case 307:
         case 308:
         case 309:
         case 310:
         case 311:
         case 312:
         case 313:
         case 314:
         case 329:
         case 330:
             if (closestPlayer.RollLuck(4) == 0)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             }
             break;
         case 326:
             if (closestPlayer.RollLuck(6) == 0)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             }
             break;
         case 315:
             Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             break;
         case 341:
         {
             int num2 = Main.rand.Next(5, 11);
             for (int j = 0; j < num2; j++)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             }
             break;
         }
         case 338:
         case 339:
         case 340:
             if (closestPlayer.RollLuck(5) == 0)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             }
             break;
         case 342:
             if (Main.rand.Next(3) != 0)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             }
             break;
         case 325:
         case 327:
         case 344:
         case 345:
         case 346:
         {
             int num = Main.rand.Next(6) + 6;
             for (int i = 0; i < num; i++)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             }
             break;
         }
         case 267:
             if (Main.rand.Next(2) == 0 && closestPlayer.statLife < closestPlayer.statLifeMax2)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             }
             break;
         case 13:
         case 14:
         case 15:
             if (Main.rand.Next(4) == 0 && closestPlayer.statLife < closestPlayer.statLifeMax2)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             }
             break;
         case 116:
         case 117:
         case 118:
         case 119:
             if (!Main.expertMode || Main.rand.Next(5) == 0)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             }
             break;
         case 139:
             if (Main.rand.Next(2) == 0)
             {
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
             }
             break;
         }
     }
References Main.expertMode, GetItemSource_Loot(), Entity.height, Item.NewItem(), UnifiedRandom.Next(), NPCLoot_DropCommonLifeAndMana(), Entity.position, Main.rand, Player.RollLuck(), Player.statLife, Player.statLifeMax2, type, and Entity.width.
Referenced by NPCLoot().