Terraria: NPC.AI_124_DeerclopsLeg
AI_124_DeerclopsLeg()
void NPC.AI_124_DeerclopsLeg () inline private
     {
         int num = (int)ai[0];
         if (num < 0 || num > 200)
         {
             active = false;
             if (Main.netMode != 1)
             {
                 NetMessage.SendData(23, -1, -1, null, whoAmI);
             }
             return;
         }
         NPC nPC = Main.npc[num];
         if (!nPC.active || nPC.type != 668)
         {
             active = false;
             if (Main.netMode != 1)
             {
                 NetMessage.SendData(23, -1, -1, null, whoAmI);
             }
             return;
         }
         NPCAimedTarget targetData = nPC.GetTargetData();
         Vector2 vector = targetData.Center - base.Center;
         float num2 = targetData.Center.X - (float)(width / 2);
         int num3 = Math.Sign(num2 - position.X);
         float val = Math.Abs(num2 - position.X);
         float num4 = Math.Min(50f, val);
         float num5 = num2 + (float)(-num3) * num4;
         Math.Abs(vector.X);
         if (Math.Abs(num5 - base.Center.X) >= 30f && localAI[0] == 0f)
         {
             localAI[0] = 1f;
         }
         float num6 = 4f;
         float num7 = 30f;
         if (localAI[0] < 0f)
         {
             localAI[0] += 1f;
         }
         if (localAI[0] > 0f)
         {
             localAI[0] += 1f;
             if (localAI[0] >= num7)
             {
                 localAI[0] = 0f - num6;
             }
         }
         int num8 = ((ai[1] != 0f) ? 1 : (-1));
         if (localAI[0] > 0f)
         {
             Vector2 vector2 = new Vector2(num8 * 14, -20f);
             Vector2 searchStartPositionInWorld = nPC.Bottom + vector2 + new Vector2(0f, 30f);
             int searchRange = 16;
             int tilesTraveled = 0;
             float? num9 = TryFindingFloor(searchStartPositionInWorld, searchRange, out tilesTraveled);
             float amount = 1f / 3f;
             Vector2 value = new Vector2(searchStartPositionInWorld.X, searchStartPositionInWorld.Y + 100f);
             float num10 = localAI[0] / num7;
             if (num9.HasValue && tilesTraveled > 2)
             {
                 new Vector2(searchStartPositionInWorld.X, num9.Value * 16f);
                 value = new Vector2(searchStartPositionInWorld.X, num9.Value * 16f);
                 amount = num10;
             }
             value.Y -= (1f - num10) * 30f;
             Vector2 bottom = Vector2.Lerp(base.Bottom, value, amount);
             base.Bottom = bottom;
         }
         int num11 = num8;
         if (Math.Abs(vector.X) > 30f)
         {
             num11 = Math.Sign(vector.X);
         }
         spriteDirection = -num11;
     }
References Entity.active, ai, Entity.Bottom, NPCAimedTarget.Center, GetTargetData(), localAI, Main.netMode, Main.npc, Entity.position, NetMessage.SendData(), spriteDirection, TryFindingFloor(), type, value, Entity.whoAmI, and Entity.width.