Terraria: NPC.GetShimmered
GetShimmered()
void NPC.GetShimmered () inline private
     {
         if (SpawnedFromStatue)
         {
             if (Main.netMode == 0)
             {
                 Item.ShimmerEffect(base.Center);
             }
             else
             {
                 NetMessage.SendData(146, -1, -1, null, 0, (int)base.Center.X, (int)base.Center.Y);
             }
             noSpawnCycle = true;
             active = false;
             if (Main.netMode == 2)
             {
                 netSkip = -1;
                 life = 0;
                 NetMessage.SendData(23, -1, -1, null, whoAmI);
             }
         }
         else if (NPCID.Sets.ShimmerTransformToNPC[type] >= 0)
         {
             Transform(NPCID.Sets.ShimmerTransformToNPC[type]);
             if (Main.netMode == 0)
             {
                 Item.ShimmerEffect(base.Center);
             }
             else
             {
                 NetMessage.SendData(146, -1, -1, null, 0, (int)base.Center.X, (int)base.Center.Y);
             }
         }
         else if (NPCID.Sets.ShimmerTransformToItem[type] >= 0)
         {
             int num = Item.NewItem(GetItemSource_Misc(8), (int)position.X, (int)position.Y, width, height, NPCID.Sets.ShimmerTransformToItem[type]);
             Main.item[num].stack = 1;
             Main.item[num].shimmerTime = 1f;
             Main.item[num].shimmered = true;
             Main.item[num].shimmerWet = true;
             Main.item[num].wet = true;
             Main.item[num].velocity *= 0.1f;
             Main.item[num].playerIndexTheItemIsReservedFor = Main.myPlayer;
             NetMessage.SendData(145, -1, -1, null, num, 1f);
             if (Main.netMode == 0)
             {
                 Item.ShimmerEffect(base.Center);
             }
             else
             {
                 NetMessage.SendData(146, -1, -1, null, 0, (int)base.Center.X, (int)base.Center.Y);
             }
             noSpawnCycle = true;
             active = false;
             if (Main.netMode == 2)
             {
                 netSkip = -1;
                 life = 0;
                 NetMessage.SendData(23, -1, -1, null, whoAmI);
             }
         }
         else if (NPCID.Sets.ShimmerTownTransform[type])
         {
             ai[0] = 25f;
             ai[1] = 0f;
             ai[2] = 0f;
             ai[3] = 0f;
             netUpdate = true;
             shimmerTransparency = 0.89f;
             int num2 = FindBuffIndex(353);
             if (num2 != -1)
             {
                 DelBuff(num2);
             }
         }
     }
References Main.item, Main.myPlayer, Main.netMode, Item.NewItem(), Item.playerIndexTheItemIsReservedFor, NetMessage.SendData(), Item.shimmered, Item.ShimmerEffect(), Item.shimmerTime, NPCID.Sets.ShimmerTownTransform, NPCID.Sets.ShimmerTransformToItem, NPCID.Sets.ShimmerTransformToNPC, Entity.shimmerWet, Item.stack, Entity.velocity, and Entity.wet.
Referenced by AI().