Terraria: NPC.FindTreeBranch
FindTreeBranch()
static bool NPC.FindTreeBranch (int landX, int landY, out int treeBranchX, out int treeBranchY) inline static
     {
         treeBranchX = landX;
         treeBranchY = landY;
         if (!WorldGen.InWorld(landX, landY, 11))
         {
             return false;
         }
         int num = 1;
         for (int i = landX - 10; i <= landX + 10; i++)
         {
             for (int j = landY - 30; j <= landY + 30; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile != null && tile.active() && TileID.Sets.IsATreeTrunk[tile.type])
                 {
                     int num2 = tile.frameX / 22;
                     int num3 = tile.frameY / 66;
                     if (((num2 == 3 && num3 == 0) || (num2 == 3 && num3 == 3) || (num2 == 4 && num3 == 1) || (num2 == 4 && num3 == 3) || (num2 == 2 && num3 == 3)) && Main.rand.Next(num) == 0)
                     {
                         treeBranchX = i;
                         treeBranchY = j;
                         num++;
                     }
                 }
             }
         }
         if (treeBranchX != landX || treeBranchY != landY)
         {
             return true;
         }
         return false;
     }
References Tile.active(), Tile.frameX, Tile.frameY, WorldGen.InWorld(), TileID.Sets.IsATreeTrunk, UnifiedRandom.Next(), Main.rand, Main.tile, and Tile.type.