Terraria: NPC.StingerExplosion
StingerExplosion()
void NPC.StingerExplosion () inline private
     {
         int num = Main.rand.Next(4, 9);
         for (int i = 0; i < num; i++)
         {
             float num2 = 8f;
             Vector2 vector = new Vector2(Main.rand.NextFloat() - 0.5f, Main.rand.NextFloat() - 0.5f);
             vector.Normalize();
             vector *= num2;
             int num3 = (int)(10f * scale);
             if (type == 176)
             {
                 num3 = (int)(30f * scale);
             }
             int num4 = 55;
             int num5 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, vector.X, vector.Y, num4, num3, 0f, Main.myPlayer);
             Main.projectile[num5].timeLeft = 300;
         }
     }
References GetSpawnSource_ForProjectile(), Main.myPlayer, Projectile.NewProjectile(), UnifiedRandom.Next(), Main.projectile, Main.rand, scale, Projectile.timeLeft, and type.
Referenced by checkDead().