Terraria: NPC.NewNPC
NewNPC()
static int NPC.NewNPC (IEntitySource source, int X, int Y, int Type, int Start = 0, float ai0 = 0f, float ai1 = 0f, float ai2 = 0f, float ai3 = 0f, int Target = 255) inline static
     {
         if (Main.getGoodWorld && Main.rand.Next(3) != 0)
         {
             if (Type == 46)
             {
                 Type = 614;
             }
             if (Type == 62)
             {
                 Type = 66;
             }
         }
         int availableNPCSlot = GetAvailableNPCSlot(Type, Start);
         if (availableNPCSlot >= 0)
         {
             Main.npc[availableNPCSlot] = new NPC();
             Main.npc[availableNPCSlot].SetDefaults(Type);
             Main.npc[availableNPCSlot].whoAmI = availableNPCSlot;
             GiveTownUniqueDataToNPCsThatNeedIt(Type, availableNPCSlot);
             Main.npc[availableNPCSlot].position.X = X - Main.npc[availableNPCSlot].width / 2;
             Main.npc[availableNPCSlot].position.Y = Y - Main.npc[availableNPCSlot].height;
             Main.npc[availableNPCSlot].active = true;
             Main.npc[availableNPCSlot].timeLeft = (int)((double)activeTime * 1.25);
             Main.npc[availableNPCSlot].wet = Collision.WetCollision(Main.npc[availableNPCSlot].position, Main.npc[availableNPCSlot].width, Main.npc[availableNPCSlot].height);
             Main.npc[availableNPCSlot].ai[0] = ai0;
             Main.npc[availableNPCSlot].ai[1] = ai1;
             Main.npc[availableNPCSlot].ai[2] = ai2;
             Main.npc[availableNPCSlot].ai[3] = ai3;
             Main.npc[availableNPCSlot].target = Target;
             if (Type == 50)
             {
                 if (Main.netMode == 0)
                 {
                     Main.NewText(Language.GetTextValue("Announcement.HasAwoken", Main.npc[availableNPCSlot].TypeName), 175, 75);
                 }
                 else if (Main.netMode == 2)
                 {
                     ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", Main.npc[availableNPCSlot].GetTypeNetName()), new Color(175, 75, 255));
                 }
             }
             return availableNPCSlot;
         }
         return 200;
     }
References Entity.active, ai, ChatHelper.BroadcastChatMessage(), Color, NetworkText.FromKey(), Main.getGoodWorld, Language.GetTextValue(), GetTypeNetName(), Entity.height, Main.netMode, Main.NewText(), UnifiedRandom.Next(), Main.npc, Entity.position, Main.rand, SetDefaults(), target, timeLeft, TypeName, Entity.wet, Collision.WetCollision(), Entity.whoAmI, Entity.width, X, and Y.
Referenced by TETrainingDummy.Activate(), AI(), AI_003_Fighters(), AI_005_EaterOfSouls(), AI_006_Worms(), AI_037_Destroyer(), AI_045_Golem(), AI_069_DukeFishron(), AI_084_LunaticCultist(), AI_110_Betsy(), AI_113_WindyBalloon(), AI_121_QueenSlime(), BigMimicSummonCheck(), checkDead(), WorldGen.CheckSuper(), DD2Film.CreateCritters(), DD2Film.CreateOgre(), DD2Event.Difficulty_1_SpawnMonsterFromGate(), DD2Event.Difficulty_2_SpawnMonsterFromGate(), DD2Event.Difficulty_3_SpawnMonsterFromGate(), DoDeathEvents_SummonDungeonSpirit(), WorldGen.DungeonEnt(), MessageBuffer.GetData(), Item.GetShimmered(), Player.ItemCheck_CheckFishingBobber_PullBobber(), Projectile.Kill(), WorldGen.KillTile_DropBait(), WorldGen.KillTile_GetItemDrops(), DD2Film.PlaceNPCOnGround(), DSTFilm.PlaceNPCOnGround(), DD2Event.RaiseGoblins(), WorldGen.ShakeTree(), Projectile.Shimmer(), CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), DD2Film.SpawnGoblin(), DD2Film.SpawnJavalinThrower(), SpawnMechQueen(), WorldGen.SpawnThingsFromPot(), WorldGen.SpawnTownNPC(), WorldGen.SpawnTravelNPC(), DD2Film.SpawnWitherBeast(), DD2Event.SummonCrystalDirect(), WorldGen.TriggerLunarApocalypse(), CultistRitual.TrySpawning(), MysticLogFairiesEvent.TrySpawningFairies(), Main.UpdateTime_SpawnTownNPCs(), and ViolentlySpawnNerdySlime().