Terraria: NPC.AI_107_ImprovedWalkers
AI_107_ImprovedWalkers()
void NPC.AI_107_ImprovedWalkers () inline private
     {
         //IL_16d7: Unknown result type (might be due to invalid IL or missing references)
         //IL_0890: Unknown result type (might be due to invalid IL or missing references)
         //IL_0895: Unknown result type (might be due to invalid IL or missing references)
         //IL_08a6: Unknown result type (might be due to invalid IL or missing references)
         //IL_08ab: Unknown result type (might be due to invalid IL or missing references)
         //IL_139a: Unknown result type (might be due to invalid IL or missing references)
         //IL_139f: Unknown result type (might be due to invalid IL or missing references)
         //IL_08d6: Unknown result type (might be due to invalid IL or missing references)
         //IL_08f5: Unknown result type (might be due to invalid IL or missing references)
         //IL_23c4: Unknown result type (might be due to invalid IL or missing references)
         //IL_145b: Unknown result type (might be due to invalid IL or missing references)
         //IL_1e7c: Unknown result type (might be due to invalid IL or missing references)
         //IL_196e: Unknown result type (might be due to invalid IL or missing references)
         //IL_147d: Unknown result type (might be due to invalid IL or missing references)
         //IL_1482: Unknown result type (might be due to invalid IL or missing references)
         //IL_0f7b: Unknown result type (might be due to invalid IL or missing references)
         //IL_0f80: Unknown result type (might be due to invalid IL or missing references)
         //IL_0509: Unknown result type (might be due to invalid IL or missing references)
         //IL_05f1: Unknown result type (might be due to invalid IL or missing references)
         //IL_0589: Unknown result type (might be due to invalid IL or missing references)
         //IL_1e9e: Unknown result type (might be due to invalid IL or missing references)
         //IL_0813: Unknown result type (might be due to invalid IL or missing references)
         //IL_0f9d: Unknown result type (might be due to invalid IL or missing references)
         //IL_0fa2: Unknown result type (might be due to invalid IL or missing references)
         //IL_0835: Unknown result type (might be due to invalid IL or missing references)
         //IL_10a1: Unknown result type (might be due to invalid IL or missing references)
         //IL_0fe2: Unknown result type (might be due to invalid IL or missing references)
         //IL_0fe7: Unknown result type (might be due to invalid IL or missing references)
         //IL_1003: Unknown result type (might be due to invalid IL or missing references)
         //IL_1008: Unknown result type (might be due to invalid IL or missing references)
         //IL_10c3: Unknown result type (might be due to invalid IL or missing references)
         //IL_10c8: Unknown result type (might be due to invalid IL or missing references)
         //IL_10e9: Unknown result type (might be due to invalid IL or missing references)
         //IL_110b: Unknown result type (might be due to invalid IL or missing references)
         //IL_1110: Unknown result type (might be due to invalid IL or missing references)
         //IL_2c37: Unknown result type (might be due to invalid IL or missing references)
         //IL_0f1e: Unknown result type (might be due to invalid IL or missing references)
         bool flag = velocity.X == 0f && velocity.Y == 0f && !justHit;
         bool flag2 = false;
         bool flag3 = false;
         bool flag4 = false;
         int num = 32;
         int num2 = 15;
         float num3 = 9f;
         bool flag5 = false;
         float num4 = 40f;
         int num5 = 30;
         int num6 = 0;
         bool flag6 = false;
         bool flag7 = true;
         float num7 = 0.9f;
         bool flag8 = false;
         bool flag9 = false;
         bool flag10 = false;
         bool flag11 = false;
         bool flag12 = false;
         bool flag13 = false;
         bool flag14 = false;
         bool flag15 = true;
         int num8 = 70;
         int num9 = num8 / 2;
         float num10 = 11f;
         Vector2 vector = Vector2.Zero;
         int num11 = 1;
         int num12 = 81;
         float num13 = 700f;
         float num14 = 0f;
         float num15 = 0.1f;
         Vector2? vector2 = null;
         float num16 = 0.5f;
         int num17 = 1;
         float num18 = 1f;
         bool flag16 = false;
         float num19 = 30f;
         float num20 = 0f;
         bool flag17 = false;
         bool flag18 = true;
         bool flag19 = false;
         int num21 = 30;
         bool flag20 = false;
         bool flag21 = false;
         bool flag22 = false;
         bool flag23 = false;
         LegacySoundStyle style = null;
         int num22 = 0;
         bool flag24 = false;
         float num23 = 1f;
         float num24 = 0.07f;
         float num25 = 0.8f;
         float num26 = width / 2 + 6;
         bool flag25 = directionY < 0;
         bool flag26 = false;
         int num27 = 1;
         bool flag27 = false;
         float num28 = 5f;
         float num29 = 3f;
         float num30 = 8f;
         float amount = 0.05f;
         float amount2 = 0.04f;
         float amount3 = 0.1f;
         bool flag28 = false;
         float num31 = 0.025f;
         NPCAimedTarget targetData = GetTargetData();
         NPCUtils.NPCTargetingMethod nPCTargetingMethod = NPCUtils.TargetClosestCommon;
         if (NPCID.Sets.BelongsToInvasionOldOnesArmy[type])
         {
             nPCTargetingMethod = NPCUtils.TargetClosestOldOnesInvasion;
         }
         if (targetData.Type == NPCTargetType.NPC && Main.npc[TranslatedTargetIndex].type == 548 && Main.npc[TranslatedTargetIndex].dontTakeDamageFromHostiles)
         {
             nPCTargetingMethod(this, faceTarget: true, null);
             targetData = GetTargetData();
         }
         if (NPCID.Sets.FighterUsesDD2PortalAppearEffect[type])
         {
             if (!targetData.Invalid)
             {
                 flag2 = !Collision.CanHit(base.Center, 0, 0, targetData.Center, 0, 0) && (direction == Math.Sign(targetData.Center.X - base.Center.X) || (noGravity && Distance(targetData.Center) > 50f && base.Center.Y > targetData.Center.Y));
             }
             flag2 &= ai[0] <= 0f;
         }
         if (flag2)
         {
             if (velocity.Y == 0f || Math.Abs(targetData.Center.Y - base.Center.Y) > 800f)
             {
                 noGravity = true;
                 noTileCollide = true;
             }
         }
         else
         {
             noGravity = false;
             noTileCollide = false;
         }
         bool flag29 = NPCID.Sets.FighterUsesDD2PortalAppearEffect[type];
         bool flag30 = true;
         SlotId val;
         switch (type)
         {
         case 576:
         case 577:
             num22 = 700;
             style = SoundID.DD2_OgreRoar;
             num26 -= 32f;
             flag5 = true;
             num6 = 60;
             num4 = 130f;
             num5 = 44;
             flag21 = DD2Event.EnemiesShouldChasePlayers;
             num7 = 0.7f;
             if (localAI[0] > 0f)
             {
                 localAI[0] -= 1f;
             }
             if (ai[0] <= 0f)
             {
                 float num34 = ai[1];
                 float num35 = Distance(targetData.Center);
                 if (localAI[3] >= 60f)
                 {
                     if (num35 <= num4 + 300f && localAI[0] <= 0f)
                     {
                         ai[1] = 2f;
                     }
                     else if (num35 > num4 + 30f)
                     {
                         ai[1] = 1f;
                     }
                     else if (!(num35 > num4))
                     {
                         ai[1] = 0f;
                         if (num34 == 1f)
{
                             ai[0] = 0f;
                         }
                     }
                 }
                 if (num34 != ai[1])
                 {
                     netUpdate = true;
                 }
             }
             else if (ai[1] == 2f)
             {
                 localAI[0] = 300f;
             }
             switch ((int)ai[1])
             {
             case 0:
                 num5 = 44;
                 if (ai[0] == 40f)
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_OgreAttack, base.Center);
                 }
                 break;
             case 2:
                 num5 = 90;
                 num4 = 250f;
                 flag4 = true;
                 num11 = GetAttackDamage_ForProjectiles(60f, 40f);
                 num9 = 36;
                 num = 56;
                 num2 = 41;
                 num3 = 13f;
                 flag3 = true;
                 num12 = 683;
                 flag15 = false;
                 vector = new Vector2(-direction * 20, height / 2 - 1);
                 if (ai[0] == 40f)
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_OgreGroundPound, base.Center);
                 }
                 break;
             case 1:
                 flag3 = true;
                 num5 = 90;
                 num4 = 1000f;
                 num6 = 240;
                 num11 = GetAttackDamage_ForProjectiles(40f, 30f);
                 flag15 = false;
                 vector = new Vector2(direction * 30, -70f);
                 num12 = 676;
                 if (ai[0] == 80f)
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_OgreSpit, base.Center);
                 }
                 break;
             }
             if (ai[0] < (float)(-num6))
             {
                 ai[0] = -num6;
             }
             break;
         case 552:
         case 553:
         case 554:
             style = SoundID.DD2_GoblinScream;
             num22 = 1000;
             flag5 = true;
             flag21 = DD2Event.EnemiesShouldChasePlayers;
             if (type == 553)
             {
                 num24 += 0.01f;
                 num23 += 0.2f;
             }
             if (type == 554)
             {
                 num24 += 0.02f;
                 num23 += 0.4f;
             }
             if (!(localAI[3] >= 60f))
             {
                 num24 = 0.01f + localAI[3] / 60f * 0.05f;
             }
             break;
         case 570:
         case 571:
             flag21 = DD2Event.EnemiesShouldChasePlayers;
             flag24 = true;
             flag12 = true;
             flag15 = ai[1] > 40f;
             num8 = 60;
             num9 = 40;
             if (type == 571 && ai[1] > 10f && ai[1] <= 40f && (int)ai[1] % 6 == 0)
             {
                 num9 = (int)ai[1] - 1;
             }
             if (type == 570 && ai[1] > 10f && ai[1] <= 40f && (int)ai[1] % 9 == 0)
             {
                 num9 = (int)ai[1] - 1;
             }
             num12 = 671;
             vector.X += 22 * direction;
             num15 = 0.15f;
             num16 = 1.5f;
             num13 = 600f;
             num10 = 13f;
             num17 = 1;
             num18 = 0f;
             if (type == 570)
             {
                 num16 = 2.5f;
             }
             num11 = GetAttackDamage_ForProjectiles(35f, 25f);
             if (type == 571)
             {
                 num11 = GetAttackDamage_ForProjectiles(60f, 45f);
             }
             num23 = 0.77f;
             if (ai[0] > 0f)
             {
                 if (ai[1] == 40f)
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_DrakinShot, base.Center);
                 }
                 else if (ai[1] == 60f)
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_DrakinBreathIn, base.Center);
                 }
             }
             if (!(localAI[3] >= 60f))
             {
                 num13 = 1f;
                 num24 = 0.01f + localAI[3] / 60f * 0.05f;
             }
             break;
         case 572:
         case 573:
             if (localAI[3] == 0f)
             {
                 float[] array = localAI;
                 val = SlotId.Invalid;
                 array[0] = ((SlotId)(ref val)).ToFloat();
                 float[] array2 = localAI;
                 val = SlotId.Invalid;
                 array2[1] = ((SlotId)(ref val)).ToFloat();
             }
             flag21 = DD2Event.EnemiesShouldChasePlayers;
             if (ai[1] == 2f)
             {
                 SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[0]))?.Stop();
                 SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]))?.Stop();
                 position = base.Center;
                 width = (height = 192);
                 base.Center = position;
                 velocity = Vector2.Zero;
                 damage = GetAttackDamage_ScaledByStrength(80f);
                 alpha = 255;
                 for (int k = 0; k < 4; k++)
                 {
                     int num37 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                     Main.dust[num37].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                 }
                 for (int l = 0; l < 20; l++)
                 {
                     int num38 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 200, default(Color), 3.7f);
                     Main.dust[num38].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                     Main.dust[num38].noGravity = true;
                     Main.dust[num38].velocity *= 3f;
                     num38 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                     Main.dust[num38].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 4f;
                     Main.dust[num38].velocity *= 2f;
                     Main.dust[num38].noGravity = true;
                     Main.dust[num38].fadeIn = 2.5f;
                 }
                 for (int m = 0; m < 6; m++)
                 {
                     int num39 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 0, default(Color), 2.7f);
                     Main.dust[num39].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                     Main.dust[num39].noGravity = true;
                     Main.dust[num39].velocity *= 3f;
                 }
                 for (int n = 0; n < 12; n++)
                 {
                     int num40 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                     Main.dust[num40].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                     Main.dust[num40].noGravity = true;
                     Main.dust[num40].velocity *= 3f;
                 }
                 for (int num41 = 0; num41 < 5; num41++)
                 {
                     int num42 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                     Main.gore[num42].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                     Main.gore[num42].velocity *= 0.3f;
                     Main.gore[num42].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                     Main.gore[num42].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
                 }
                 ai[0] += 1f;
                 if (ai[0] >= 3f)
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_KoboldExplosion, base.Center);
                     life = 0;
                     HitEffect();
                     active = false;
                 }
                 return;
             }
             if (ai[0] > 0f && ai[1] == 0f && life > 0)
             {
                 SlotId val2 = SlotId.FromFloat(localAI[0]);
                 if (!((SlotId)(ref val2)).IsValid)
                 {
                     float[] array3 = localAI;
                     val = SoundEngine.PlayTrackedSound(SoundID.DD2_KoboldIgnite, base.Center);
                     array3[0] = ((SlotId)(ref val)).ToFloat();
                 }
                 localAI[2] += 1f;
                 if (localAI[2] == 30f)
                 {
                     float[] array4 = localAI;
                     val = SoundEngine.PlayTrackedSound(SoundID.DD2_KoboldIgniteLoop, base.Center);
                     array4[0] = ((SlotId)(ref val)).ToFloat();
                     float[] array5 = localAI;
                     val = SoundEngine.PlayTrackedSound(SoundID.DD2_KoboldScreamChargeLoop, base.Center);
                     array5[1] = ((SlotId)(ref val)).ToFloat();
                 }
             }
             if (ai[0] > 0f && ai[1] == 1f)
             {
                 ai[0] = 0f;
                 ai[1] = 2f;
                 netUpdate = true;
                 return;
             }
             num23 = 0.88f;
             if (ai[0] == 1f)
             {
                 ai[1] = 1f;
             }
             if (ai[0] == 0f && ai[1] == 1f)
             {
                 ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[0]));
                 if (activeSound == null)
                 {
                     float[] array6 = localAI;
                     val = SoundEngine.PlayTrackedSound(SoundID.DD2_KoboldIgniteLoop, base.Center);
                     array6[0] = ((SlotId)(ref val)).ToFloat();
                 }
                 else
                 {
                     activeSound.Position = base.Center;
                 }
                 ActiveSound activeSound2 = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
                 if (activeSound2 == null)
                 {
                     float[] array7 = localAI;
                     val = SoundEngine.PlayTrackedSound(SoundID.DD2_KoboldScreamChargeLoop, base.Center);
                     array7[1] = ((SlotId)(ref val)).ToFloat();
                 }
                 else
                 {
                     activeSound2.Position = base.Center;
                 }
             }
             if (ai[1] > 0f && ai[0] == 0f)
             {
                 flag5 = true;
                 num5 = 40;
                 num4 = 64f;
                 num24 = 0.3f;
                 num23 = 4f;
                 Vector2 vector3 = base.Center + new Vector2(spriteDirection * 12, 0f);
                 if (Main.rand.Next(6) == 0)
                 {
                     Dust dust3 = Dust.NewDustDirect(vector3, 1, 1, 213, Main.rand.Next(-2, 3), Main.rand.Next(-2, 3), 100, new Color(255, 255, 255, 0));
                     dust3.noGravity = true;
                     dust3.fadeIn = dust3.scale + 1f + 0.01f * (float)Main.rand.Next(0, 51);
                     dust3.velocity *= 0.3f;
                     dust3.velocity.X += (float)(-spriteDirection) * 1.2f;
                     dust3.velocity.Y += -3.5f;
                     dust3.velocity.X += velocity.X;
                 }
                 if (Main.rand.Next(12) == 0)
                 {
                     Dust dust4 = Dust.NewDustPerfect(vector3, 6, velocity, 100);
                     dust4.noGravity = true;
                     dust4.velocity.Y -= 1f + Main.rand.NextFloat();
                     dust4.scale = 1.1f;
                     dust4.fadeIn = 0.5f;
                     dust4.customData = this;
                 }
             }
             else
             {
                 flag5 = true;
                 num5 = 40;
                 num4 = 700f;
             }
             if (!(localAI[3] >= 60f))
             {
                 num24 = 0.01f + localAI[3] / 60f * 0.05f;
             }
             break;
         case 568:
         case 569:
         {
             num5 = 110;
             num24 = 0.16f;
             num25 = 0.7f;
             num23 = 1.4f;
             flag5 = true;
             num4 = 600f;
             flag21 = DD2Event.EnemiesShouldChasePlayers;
             if (!(localAI[3] >= 60f))
             {
                 num24 = 0.01f + localAI[3] / 60f * 0.05f;
             }
             if (ai[0] == 0f)
             {
                 float[] array8 = localAI;
                 val = SlotId.Invalid;
                 array8[1] = ((SlotId)(ref val)).ToFloat();
             }
             if (ai[0] != 1f)
             {
                 break;
             }
             HitSound = SoundID.DD2_WitherBeastCrystalImpact;
             ai[0] += 1f;
             if (Main.rand.Next(10) == 0)
             {
                 Dust dust7 = Dust.NewDustDirect(base.TopLeft, width, height, 271, 0f, -3f, 0, Color.Transparent, 0.6f);
                 dust7.velocity.X /= 2f;
                 dust7.noGravity = true;
                 dust7.fadeIn = 1.5f;
                 dust7.position.Y += 4f;
             }
             ActiveSound activeSound3 = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
             if (activeSound3 == null)
             {
                 float[] array9 = localAI;
                 val = SoundEngine.PlayTrackedSound(SoundID.DD2_WitherBeastAuraPulse, base.Center);
                 array9[1] = ((SlotId)(ref val)).ToFloat();
             }
             else
             {
                 activeSound3.Position = base.Center;
             }
             localAI[0] += 1f;
             if (localAI[0] > 60f && Main.rand.Next(10) == 0)
             {
                 Vector2 vec = base.Center + (Main.rand.NextFloat() * ((float)Math.PI * 2f)).ToRotationVector2() * 400f * (0.3f + 0.7f * Main.rand.NextFloat());
                 Point point = vec.ToTileCoordinates();
                 if (!WorldGen.SolidTile(point.X, point.Y))
                 {
                     Dust dust8 = Dust.NewDustPerfect(vec, 27, new Vector2(0f, -3f), 0, new Color(255, 255, 255, 127), 1.5f);
                     dust8.velocity = DirectionTo(dust8.position) * dust8.velocity.Length();
                     dust8.fadeIn = 1.5f;
                 }
             }
             if (Main.netMode != 2)
             {
                 Player player = Main.player[Main.myPlayer];
                 if (!player.dead && player.active && (player.Center - base.Center).Length() < 400f && !player.creativeGodMode)
                 {
                     player.AddBuff(195, 3, quiet: false);
                 }
             }
             if (ai[1] > 0f)
             {
                 ai[1] -= 1f;
             }
             if (!(ai[1] <= 0f))
             {
                 break;
             }
             ai[1] = 60f;
             if (Main.netMode != 1)
             {
                 int num51 = lifeMax / 20;
                 if (num51 > lifeMax - life)
                 {
                     num51 = lifeMax - life;
                 }
                 if (num51 > 0)
                 {
                     life += num51;
                     HealEffect(num51);
                     netUpdate = true;
                 }
             }
             break;
         }
         case 561:
         case 562:
         case 563:
         {
             bool num36 = localAI[3] >= 60f;
             if (ai[1] == 82f)
             {
                 SoundEngine.PlayTrackedSound(SoundID.DD2_JavelinThrowersAttack, base.Center);
                 num22 = 7;
                 style = SoundID.DD2_JavelinThrowersTaunt;
             }
             flag21 = DD2Event.EnemiesShouldChasePlayers;
             flag24 = true;
             flag12 = true;
             flag15 = ai[1] > 82f;
             num8 = 90;
             num9 = 82;
             num12 = 662;
             if (type == 563)
             {
                 num12 = 685;
             }
             vector.Y -= 14f;
             num15 = 0f;
             num16 = 0.5f;
             num13 = 600f;
             num10 = 13f;
             if (!num36)
             {
                 num13 = 1f;
                 num24 = 0.01f + localAI[3] / 60f * 0.05f;
             }
             if (type == 561)
             {
                 num23 = 0.88f;
                 num16 = 0.6f;
                 num11 = GetAttackDamage_ForProjectiles(15f, 10f);
                 num10 = 11.5f;
                 num13 -= 100f;
             }
             if (type == 562)
             {
                 num23 = 0.94f;
                 num16 = 0.5f;
                 num11 = GetAttackDamage_ForProjectiles(30f, 20f);
                 num10 = 12.2f;
                 num13 -= 50f;
             }
             if (type == 563)
             {
                 num23 = 1f;
                 num16 = 0.4f;
                 num11 = GetAttackDamage_ForProjectiles(45f, 30f);
             }
             break;
         }
         case 555:
         case 556:
         case 557:
         {
             num22 = 800;
             style = SoundID.DD2_GoblinBomberScream;
             bool num33 = localAI[3] >= 60f;
             flag21 = DD2Event.EnemiesShouldChasePlayers;
             flag24 = true;
             flag12 = true;
             flag15 = ai[1] > 18f;
             num8 = 42;
             num9 = 18;
             num12 = 681;
             num11 = 10;
             vector.Y -= 14f;
             num15 = 0.4f;
             num16 = 0.5f;
             num13 = 280f;
             num10 = 6f;
             if (!num33)
             {
                 num13 = 1f;
                 num24 = 0.01f + localAI[3] / 60f * 0.05f;
             }
             if (type == 555)
             {
                 num23 = 0.88f;
                 num16 = 0.6f;
                 num11 = GetAttackDamage_ForProjectiles(20f, 15f);
             }
             if (type == 556)
             {
                 num23 = 0.88f;
                 num16 = 0.6f;
                 num11 = GetAttackDamage_ForProjectiles(30f, 25f);
             }
             if (type == 557)
             {
                 num23 = 1.12f;
                 num16 = 0.4f;
                 num11 = GetAttackDamage_ForProjectiles(40f, 35f);
             }
             if (ai[1] == (float)num9)
             {
                 SoundEngine.PlayTrackedSound(SoundID.DD2_GoblinBomberThrow, base.Center);
             }
             break;
         }
         case 566:
         case 567:
         {
             DelegateMethods.v3_1 = new Vector3(0.3f, 0.05f, 0.45f) * 1.5f;
             Utils.PlotTileLine(base.Top, base.Bottom, width, DelegateMethods.CastLightOpen);
             flag21 = DD2Event.EnemiesShouldChasePlayers;
             bool num43 = localAI[3] >= 120f;
             if (!num43)
             {
                 num24 = 0f;
             }
             if (num43)
             {
                 dontTakeDamage = false;
                 break;
             }
             dontTakeDamage = true;
             velocity.X = 0f;
             flag24 = true;
             flag20 = true;
             ai[3] = 0f;
             if (localAI[3] == 0f)
             {
                 alpha = 255;
             }
             localAI[3] += 1f;
             float num44 = localAI[3];
             if (num44 >= 110f)
             {
                 alpha -= 26;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
             }
             if (num44 >= 100f)
             {
                 int num45 = (int)localAI[3] / 20;
                 float num46 = base.Size.Length() / 2f;
                 num46 /= 20f;
                 int maxValue = 5;
                 for (int num47 = 0; num47 < num45 * 2; num47++)
                 {
                     if (Main.rand.Next(maxValue) == 0)
                     {
                         Dust dust5 = Dust.NewDustDirect(position, width, height, 236, velocity.X * 1f);
                         dust5.scale = 1f;
                         dust5.fadeIn = 0.3f;
                         dust5.velocity = new Vector2(Main.rand.NextFloatDirection() * 1f, 0f - dust5.velocity.Length()) * 1.25f * num46;
                     }
                 }
             }
             else
             {
                 int num48 = (int)localAI[3] / 10;
                 float num49 = base.Size.Length() / 2f;
                 num49 /= 20f;
                 int maxValue2 = 5;
                 for (int num50 = 0; (float)num50 < (float)num48 * 1.3f; num50++)
                 {
                     if (Main.rand.Next(maxValue2) == 0)
                     {
                         Dust dust6 = Dust.NewDustDirect(position + new Vector2(-width / 2, 8f), width + width, height, 27, velocity.X * 1f, 0f, 100);
                         dust6.scale = 1.1f;
                         dust6.fadeIn = 0.1f;
                         dust6.velocity = new Vector2(Main.rand.NextFloatDirection() * 0.1f, 0f - dust6.velocity.Length()) * 1.05f * num49 * Main.rand.NextFloat();
                         dust6.velocity.Y *= Utils.GetLerpValue((float)width * 0.75f, 0f, Math.Abs(dust6.position.X - base.Center.X), clamped: true);
                     }
                 }
             }
             if (num44 > 100f && (int)num44 % 4 == 0)
             {
                 Gore.NewGoreDirect(base.Left, new Vector2(0f, -3f), Utils.SelectRandom<int>(Main.rand, 971, 972), 0.85f).velocity.X *= 0.8f;
             }
             break;
         }
         case 620:
         {
             flag27 = wet;
             flag30 = false;
             flag16 = true;
             num20 = 150f;
             num19 = 20f;
             bool dayTime = Main.dayTime;
             flag21 = !dayTime;
             flag24 = true;
             flag12 = true;
             flag15 = ai[1] > 40f;
             num8 = 60;
             num9 = 40;
             if (ai[1] > 10f && ai[1] <= 40f && (int)ai[1] % 5 == 0)
             {
                 num9 = (int)ai[1] - 1;
             }
             num12 = 811;
             vector.X -= 4 * direction;
             vector.Y -= 20f;
             num15 = 0.15f;
             num16 = 2.5f;
             num13 = 600f;
             num10 = 13f;
             num17 = 1;
             num18 = 0f;
             num11 = GetAttackDamage_ForProjectiles(40f, 30f);
             num23 = 8f;
             num24 *= 3f;
             num25 = 0.9f;
             if (ai[0] > 0f)
             {
                 if (ai[1] == 40f)
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_DrakinShot, base.Center);
                 }
                 else if (ai[1] == 60f)
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_DrakinBreathIn, base.Center);
                 }
             }
             position += netOffset;
             if (alpha == 255)
             {
                 spriteDirection = direction;
                 velocity.Y = -6f;
                 netUpdate = true;
                 for (int i = 0; i < 35; i++)
                 {
                     Dust dust = Dust.NewDustDirect(position, width, height, 5);
                     dust.velocity *= 1f;
                     dust.scale = 1f + Main.rand.NextFloat() * 0.5f;
                     dust.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                     dust.velocity += velocity * 0.5f;
                 }
             }
             alpha -= 15;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (alpha != 0)
             {
                 for (int j = 0; j < 2; j++)
                 {
                     Dust dust2 = Dust.NewDustDirect(position, width, height, 5);
                     dust2.velocity *= 1f;
                     dust2.scale = 1f + Main.rand.NextFloat() * 0.5f;
                     dust2.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                     dust2.velocity += velocity * 0.3f;
                 }
             }
             if (Main.rand.Next(3) == 0)
             {
                 Dust.NewDustDirect(position, width, height, 5, 0f, 0f, 50, default(Color), 1.3f).velocity = Vector2.Zero;
             }
             position -= netOffset;
             if (dayTime)
             {
                 flag12 = false;
                 flag24 = false;
                 flag23 = true;
             }
             else
             {
                 if (velocity.Y != 0f || !((float)targetData.Hitbox.Bottom < base.Top.Y) || !(Math.Abs(base.Center.X - (float)targetData.Hitbox.Center.X) < (float)(width * 3)) || !Collision.CanHit(base.Hitbox.TopLeft(), base.Hitbox.Width, base.Hitbox.Height, targetData.Hitbox.TopLeft(), targetData.Hitbox.Width, targetData.Hitbox.Height))
                 {
                     break;
                 }
                 int num32 = (int)((base.Bottom.Y - 16f - (float)targetData.Hitbox.Bottom) / 16f);
                 if (num32 < 27)
                 {
                     if (num32 < 11)
                     {
                         velocity.Y = -11f;
                     }
                     else if (num32 < 15)
                     {
                         velocity.Y = -13f;
                     }
                     else if (num32 < 19)
                     {
                         velocity.Y = -14f;
                     }
                     else
                     {
                         velocity.Y = -15.9f;
                     }
                 }
             }
             break;
         }
         }
         if (flag28)
         {
             bool flag31 = velocity.Y == 0f;
             for (int num52 = 0; num52 < 200; num52++)
             {
                 if (num52 != whoAmI && Main.npc[num52].active && Main.npc[num52].type == type && Math.Abs(position.X - Main.npc[num52].position.X) + Math.Abs(position.Y - Main.npc[num52].position.Y) < (float)width)
                 {
                     if (position.X < Main.npc[num52].position.X)
                     {
                         velocity.X -= num31;
                     }
                     else
                     {
                         velocity.X += num31;
                     }
                     if (position.Y < Main.npc[num52].position.Y)
                     {
                         velocity.Y -= num31;
                     }
                     else
                     {
                         velocity.Y += num31;
                     }
                 }
             }
             if (flag31)
             {
                 velocity.Y = 0f;
             }
         }
         if (flag29)
         {
             if (localAI[3] == 0f)
             {
                 alpha = 255;
             }
             if (localAI[3] == 30f)
             {
                 SoundEngine.PlayTrackedSound(SoundID.DD2_EtherianPortalSpawnEnemy, base.Center);
             }
             if (localAI[3] < 60f)
             {
                 localAI[3] += 1f;
                 alpha -= 5;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
                 int num53 = (int)localAI[3] / 10;
                 float num54 = base.Size.Length() / 2f;
                 num54 /= 20f;
                 int maxValue3 = 5;
                 if (type == 576 || type == 577)
                 {
                     maxValue3 = 1;
                 }
                 for (int num55 = 0; num55 < num53; num55++)
                 {
                     if (Main.rand.Next(maxValue3) == 0)
                     {
                         Dust dust9 = Dust.NewDustDirect(position, width, height, 27, velocity.X * 1f, 0f, 100);
                         dust9.scale = 0.55f;
                         dust9.fadeIn = 0.7f;
                         dust9.velocity *= 0.1f * num54;
                         dust9.velocity += velocity;
                     }
                 }
             }
         }
         if (flag27)
         {
             noGravity = true;
             TargetClosest(faceTarget: false);
             if (collideX)
             {
                 velocity.X = 0f - oldVelocity.X;
             }
             if (velocity.X != 0f)
             {
                 direction = Math.Sign(direction);
             }
             if (Collision.CanHit(position, width, height, targetData.Position, targetData.Width, targetData.Height))
             {
                 Vector2 value = targetData.Center - base.Center;
                 value.Normalize();
                 value *= num28;
                 velocity = Vector2.Lerp(velocity, value, amount);
                 return;
             }
             float num56 = num28;
             if (velocity.Y > 0f)
             {
                 num56 = num29;
             }
             if (velocity.Y < 0f)
             {
                 num56 = num30;
             }
             Vector2 value2 = new Vector2(direction, -1f);
             value2.Normalize();
             value2 *= num56;
             if (num56 < num28)
             {
                 velocity = Vector2.Lerp(velocity, value2, amount2);
             }
             else
             {
                 velocity = Vector2.Lerp(velocity, value2, amount3);
             }
             return;
         }
         bool flag32 = false;
         if ((flag12 || flag5) && ai[0] > 0f)
         {
             flag18 = false;
         }
         if (flag12 && ai[1] > 0f)
         {
             flag22 = true;
         }
         if (flag5 && ai[0] > 0f)
         {
             flag22 = true;
         }
         if (flag5)
         {
             if (ai[0] < 0f)
             {
                 ai[0] += 1f;
                 flag = false;
             }
             if (ai[0] == 0f && (velocity.Y == 0f || flag6) && targetData.Type != 0 && (Collision.CanHit(position, width, height, targetData.Position, targetData.Width, targetData.Height) || Collision.CanHitLine(position, width, height, targetData.Position, targetData.Width, targetData.Height)) && (targetData.Center - base.Center).Length() < num4)
             {
                 ai[0] = num5;
                 netUpdate = true;
             }
             if (ai[0] > 0f)
             {
                 spriteDirection = direction * num27;
                 if (flag7)
                 {
                     velocity.X *= num7;
                     flag24 = true;
                     flag20 = true;
                     ai[3] = 0f;
                     netUpdate = true;
                 }
                 ai[0] -= 1f;
                 if (ai[0] == 0f)
                 {
                     ai[0] = -num6;
                     netUpdate = true;
                 }
             }
         }
         if (flag3 && ai[0] > 0f)
         {
             if (flag15)
             {
                 nPCTargetingMethod(this, faceTarget: true, null);
                 targetData = GetTargetData();
             }
             if (ai[0] == (float)num9)
             {
                 Vector2 vector4 = base.Center + vector;
                 Vector2 v = targetData.Center - vector4;
                 v.Y -= Math.Abs(v.X) * num15;
                 Vector2 vector5 = v.SafeNormalize(-Vector2.UnitY) * num10;
                 for (int num57 = 0; num57 < num17; num57++)
                 {
                     Vector2 vector6 = vector5;
                     Vector2 vector7 = vector4;
                     if (vector2.HasValue)
                     {
                         vector6 += vector2.Value;
                     }
                     else
                     {
                         vector6 += Utils.RandomVector2(Main.rand, 0f - num16, num16);
                     }
                     vector7 += vector5 * num18;
                     if (Main.netMode != 1)
                     {
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector7, vector6, num12, num11, 0f, Main.myPlayer);
                     }
                 }
             }
         }
         if (flag4 && ai[0] > 0f)
         {
             if (velocity.Y != 0f && ai[0] < (float)num2)
             {
                 ai[0] = num2;
             }
             if (ai[0] == (float)num)
             {
                 velocity.Y = 0f - num3;
             }
         }
         if (!flag17 && flag18)
         {
             if (velocity.Y == 0f && velocity.X * (float)direction < 0f)
             {
                 flag19 = true;
             }
             if (position.X == oldPosition.X || ai[3] >= (float)num21 || flag19)
             {
                 ai[3] += 1f;
             }
             else if (Math.Abs(velocity.X) > 0.9f && ai[3] > 0f)
             {
                 ai[3] -= 1f;
             }
             if (ai[3] > (float)(num21 * 10))
             {
                 ai[3] = 0f;
             }
             if (justHit && !flag30)
             {
                 ai[3] = 0f;
             }
             if (targetData.Hitbox.Intersects(base.Hitbox))
             {
                 ai[3] = 0f;
             }
             if (ai[3] == (float)num21)
             {
                 netUpdate = true;
                 if (flag30)
                 {
                     noGravity = true;
                     noTileCollide = true;
                     position.X += direction * width * 2;
                     int num58 = 20;
                     float num59 = base.Size.Length() / 2f;
                     num59 /= 20f;
                     int maxValue4 = 5;
                     if (type == 576 || type == 577)
                     {
                         maxValue4 = 1;
                     }
                     for (int num60 = 0; num60 < num58; num60++)
                     {
                         if (Main.rand.Next(maxValue4) == 0)
{
                             Dust dust10 = Dust.NewDustDirect(position, width, height, 27, velocity.X * 1f, 0f, 100);
                             dust10.scale = 0.55f;
                             dust10.fadeIn = 0.7f;
                             dust10.velocity *= 3f * num59;
                             dust10.noGravity = true;
                             dust10.fadeIn = 1.5f;
                             dust10.velocity *= 3f;
                         }
                     }
                     return;
                 }
             }
         }
         if (!flag20)
         {
             if (ai[3] < (float)num21 && flag21)
             {
                 if (num22 > 0 && Main.rand.Next(num22) == 0)
                 {
                     SoundEngine.PlayTrackedSound(style, base.Center);
                 }
                 bool hasValidTarget = HasValidTarget;
                 nPCTargetingMethod(this, faceTarget: true, null);
                 targetData = GetTargetData();
                 if (hasValidTarget != HasValidTarget)
                 {
                     netUpdate = true;
                 }
             }
             else if (!flag22)
             {
                 if (flag23)
                 {
                     EncourageDespawn(10);
                 }
                 if (velocity.X == 0f)
                 {
                     if (velocity.Y == 0f)
                     {
                         ai[2] += 1f;
                         if (ai[2] >= 2f)
{
                             direction *= -1;
                             spriteDirection = direction * num27;
                             ai[2] = 0f;
                             netUpdate = true;
                         }
                     }
                 }
                 else if (ai[2] != 0f)
                 {
                     ai[2] = 0f;
                     netUpdate = true;
                 }
                 if (direction == 0)
                 {
                     direction = 1;
                 }
             }
         }
         if (!flag24)
         {
             if (velocity.X < 0f - num23 || velocity.X > num23)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= num25;
                 }
             }
             else if ((velocity.X < num23 && direction == 1) || (velocity.X > 0f - num23 && direction == -1))
             {
                 velocity.X = MathHelper.Clamp(velocity.X + num24 * (float)direction, 0f - num23, num23);
             }
         }
         if (flag12)
         {
             if (confused)
             {
                 ai[0] = 0f;
             }
             else
             {
                 if (ai[1] > 0f)
                 {
                     ai[1] -= 1f;
                 }
                 if (justHit)
                 {
                     ai[1] = num19;
                     ai[0] = 0f;
                 }
                 if (ai[0] > 0f)
                 {
                     if (flag15)
                     {
                         nPCTargetingMethod(this, faceTarget: true, null);
                         targetData = GetTargetData();
                     }
                     if (ai[1] == (float)num9)
                     {
                         Vector2 vector8 = base.Center + vector;
                         Vector2 v2 = targetData.Center - vector8;
                         v2.Y -= Math.Abs(v2.X) * num15;
                         Vector2 vector9 = v2.SafeNormalize(-Vector2.UnitY) * num10;
                         for (int num61 = 0; num61 < num17; num61++)
{
                             Vector2 vector10 = vector8;
                             Vector2 vector11 = vector9;
                             if (vector2.HasValue)
{
                                 vector11 += vector2.Value;
                             }
                             else
{
                                 vector11 += Utils.RandomVector2(Main.rand, 0f - num16, num16);
                             }
                             vector10 += vector11 * num18;
                             if (Main.netMode != 1)
{
                                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector10, vector11, num12, num11, 0f, Main.myPlayer);
                             }
                         }
                         if (Math.Abs(vector9.Y) > Math.Abs(vector9.X) * 2f)
{
                             ai[0] = ((vector9.Y > 0f) ? 1 : 5);
                         }
                         else if (Math.Abs(vector9.X) > Math.Abs(vector9.Y) * 2f)
{
                             ai[0] = 3f;
                         }
                         else
{
                             ai[0] = ((vector9.Y > 0f) ? 2 : 4);
                         }
                         if (flag16)
{
                             direction = ((vector9.X > 0f) ? 1 : (-1));
                         }
                     }
                     bool flag33 = true;
                     if ((velocity.Y != 0f && !flag14) || ai[1] <= 0f)
                     {
                         bool flag34 = false;
                         if (num20 != 0f && ai[1] <= 0f)
{
                             flag34 = true;
                         }
                         ai[0] = 0f;
                         ai[1] = (flag34 ? num20 : 0f);
                     }
                     else if (!flag13 || (!flag33 && (!flag14 || velocity.Y == 0f)))
                     {
                         velocity.X *= 0.9f;
                         spriteDirection = direction * num27;
                     }
                 }
                 if ((ai[0] <= 0f || flag13) && (velocity.Y == 0f || flag14) && ai[1] <= 0f && targetData.Type != 0 && Collision.CanHit(position, width, height, targetData.Position, targetData.Width, targetData.Height))
                 {
                     Vector2 vector12 = targetData.Center - base.Center;
                     if (vector12.Length() < num13)
                     {
                         netUpdate = true;
                         velocity.X *= 0.5f;
                         ai[0] = 3f;
                         ai[1] = num8;
                         if (Math.Abs(vector12.Y) > Math.Abs(vector12.X) * 2f)
{
                             ai[0] = ((vector12.Y > 0f) ? 1 : 5);
                         }
                         else if (Math.Abs(vector12.X) > Math.Abs(vector12.Y) * 2f)
{
                             ai[0] = 3f;
                         }
                         else
{
                             ai[0] = ((vector12.Y > 0f) ? 2 : 4);
                         }
                         if (flag16)
{
                             direction = ((vector12.X > 0f) ? 1 : (-1));
                         }
                     }
                 }
                 if (ai[0] <= 0f || flag13)
                 {
                     bool flag35 = Distance(targetData.Center) < num14;
                     if (flag35 && Collision.CanHitLine(position, width, height, targetData.Position, targetData.Width, targetData.Height))
                     {
                         ai[3] = 0f;
                     }
                     if (velocity.X < 0f - num23 || velocity.X > num23 || flag35)
                     {
                         if (velocity.Y == 0f)
{
                             velocity.X *= num25;
                         }
                     }
                     else if ((velocity.X < num23 && direction == 1) || (velocity.X > 0f - num23 && direction == -1))
                     {
                         velocity.X = MathHelper.Clamp(velocity.X + num24 * (float)direction, 0f - num23, num23);
                     }
                 }
             }
         }
         if (velocity.Y == 0f)
         {
             int num62 = (int)(base.Bottom.Y + 7f) / 16;
             int num63 = (int)base.Left.X / 16;
             int num64 = (int)base.Right.X / 16;
             int num65;
             for (num65 = num63; num65 <= num64; num65++)
             {
                 num65 = Utils.Clamp(num65, 0, Main.maxTilesX);
                 num62 = Utils.Clamp(num62, 0, Main.maxTilesY);
                 Tile tile = Main.tile[num65, num62];
                 if (tile == null)
                 {
                     return;
                 }
                 if (tile.nactive() && Main.tileSolid[tile.type])
                 {
                     flag32 = true;
                     break;
                 }
             }
         }
         Point point2 = base.Center.ToTileCoordinates();
         if (WorldGen.InWorld(point2.X, point2.Y, 5) && !noGravity)
         {
             GetTileCollisionParameters(out var cPosition, out var cWidth, out var cHeight);
             Vector2 vector13 = position - cPosition;
             Collision.StepUp(ref cPosition, ref velocity, cWidth, cHeight, ref stepSpeed, ref gfxOffY);
             position = cPosition + vector13;
         }
         if (flag32)
         {
             int num66 = (int)(base.Center.X + num26 * (float)direction) / 16;
             int num67 = ((int)base.Bottom.Y - 15) / 16;
             bool flag36 = position.Y + (float)height - (float)(num67 * 16) > 20f;
             Tile tileSafely = Framing.GetTileSafely(num66 + direction, num67 + 1);
             Tile tileSafely2 = Framing.GetTileSafely(num66, num67 + 1);
             Tile tileSafely3 = Framing.GetTileSafely(num66, num67);
             Tile tileSafely4 = Framing.GetTileSafely(num66, num67 - 1);
             Tile tileSafely5 = Framing.GetTileSafely(num66, num67 - 2);
             Tile tileSafely6 = Framing.GetTileSafely(num66, num67 - 3);
             if (flag8 && tileSafely4.nactive() && (tileSafely4.type == 10 || tileSafely4.type == 388))
             {
                 ai[0] += 1f;
                 ai[3] = 0f;
                 if (ai[0] >= 60f)
                 {
                     if (flag9)
                     {
                         ai[1] = 0f;
                     }
                     int num68 = 5;
                     if (Main.tile[num66, num67 - 1].type == 388)
                     {
                         num68 = 2;
                     }
                     velocity.X = 0.5f * (float)(-direction);
                     ai[1] += num68;
                     bool flag37 = false;
                     if (ai[1] >= 10f)
                     {
                         flag37 = true;
                         ai[1] = 10f;
                     }
                     if (flag10)
                     {
                         flag37 = true;
                     }
                     WorldGen.KillTile(num66, num67 - 1, fail: true);
                     if (Main.netMode != 1 && flag37)
                     {
                         if (flag11)
{
                             WorldGen.KillTile(num66, num67 - 1);
                             if (Main.netMode == 2)
{
                                 NetMessage.SendData(17, -1, -1, null, 0, num66, num67 - 1);
                             }
                         }
                         else
{
                             if (tileSafely4.type == 10)
{
                                 bool flag38 = WorldGen.OpenDoor(num66, num67 - 1, direction);
                                 if (!flag38)
{
                                     ai[3] = num21;
                                     netUpdate = true;
                                 }
                                 if (Main.netMode == 2 && flag38)
{
                                     NetMessage.SendData(19, -1, -1, null, 0, num66, num67 - 1, direction);
                                 }
                             }
                             if (tileSafely4.type == 388)
{
                                 bool flag39 = WorldGen.ShiftTallGate(num66, num67 - 1, closing: false);
                                 if (!flag39)
{
                                     ai[3] = num21;
                                     netUpdate = true;
                                 }
                                 if (Main.netMode == 2 && flag39)
{
                                     NetMessage.SendData(19, -1, -1, null, 4, num66, num67 - 1, direction);
                                 }
                             }
                         }
                     }
                 }
             }
             else
             {
                 int num69 = spriteDirection * num27;
                 if (velocity.X * (float)num69 > 0f)
                 {
                     if (height >= 32 && tileSafely5.nactive() && Main.tileSolid[tileSafely5.type])
                     {
                         netUpdate = true;
                         velocity.Y = -7f;
                         if (tileSafely6.nactive() && Main.tileSolid[tileSafely6.type])
{
                             velocity.Y = -8f;
                         }
                     }
                     else if (tileSafely4.nactive() && Main.tileSolid[tileSafely4.type])
                     {
                         velocity.Y = -6f;
                         netUpdate = true;
                     }
                     else if (flag36 && tileSafely3.nactive() && !tileSafely3.topSlope() && Main.tileSolid[tileSafely3.type])
                     {
                         velocity.Y = -5f;
                         netUpdate = true;
                     }
                     else if (flag25 && (!tileSafely2.nactive() || !Main.tileSolid[tileSafely2.type]) && (!tileSafely.nactive() || !Main.tileSolid[tileSafely.type]))
                     {
                         velocity.X *= 1.5f;
                         velocity.Y = -8f;
                         netUpdate = true;
                     }
                     else if (flag8)
                     {
                         ai[0] = 0f;
                         ai[1] = 0f;
                     }
                     if (velocity.Y == 0f && flag && ai[3] == 1f)
                     {
                         velocity.Y = -5f;
                         netUpdate = true;
                     }
                 }
                 if (flag26 && velocity.Y == 0f && Math.Abs(targetData.Center.X - base.Center.X) < 100f && Math.Abs(targetData.Center.Y - base.Center.Y) < 50f && Math.Abs(velocity.X) >= 1f && velocity.X * (float)direction > 0f)
                 {
                     velocity.X = MathHelper.Clamp(velocity.X * 2f, -3f, 3f);
                     velocity.Y = -4f;
                     netAlways = true;
                 }
             }
         }
         else if (flag8)
         {
             ai[0] = 0f;
             ai[1] = 0f;
         }
         if (!flag2 || !noTileCollide)
         {
             return;
         }
         wet = false;
         if (flag29)
         {
             if (alpha < 60)
             {
                 alpha += 20;
             }
             localAI[3] = 40f;
         }
         bool num70 = velocity.Y == 0f;
         if (Math.Abs(base.Center.X - targetData.Center.X) > 200f)
         {
             spriteDirection = (direction = ((targetData.Center.X > base.Center.X) ? 1 : (-1)));
             velocity.X = MathHelper.Lerp(velocity.X, direction, 0.05f);
         }
         int num71 = 80;
         int num72 = height;
         Vector2 vector14 = new Vector2(base.Center.X - (float)(num71 / 2), position.Y + (float)height - (float)num72);
         bool flag40 = false;
         if (position.Y + (float)height < targetData.Position.Y + (float)targetData.Height - 16f)
         {
             flag40 = true;
         }
         if (flag40)
         {
             velocity.Y += 0.5f;
         }
         else if (Collision.SolidCollision(vector14, num71, num72) || targetData.Center.Y - base.Center.Y < -100f || (targetData.Center.Y - base.Center.Y < 10f && Math.Abs(targetData.Center.X - base.Center.X) < 60f))
         {
             if (velocity.Y > 0f)
             {
                 velocity.Y = 0f;
             }
             if ((double)velocity.Y > -0.2)
             {
                 velocity.Y -= 0.025f;
             }
             else
             {
                 velocity.Y -= 0.2f;
             }
             if (velocity.Y < -4f)
             {
                 velocity.Y = -4f;
             }
         }
         else
         {
             if (velocity.Y < 0f)
             {
                 velocity.Y = 0f;
             }
             if ((double)velocity.Y < 0.1)
             {
                 velocity.Y += 0.025f;
             }
             else
             {
                 velocity.Y += 0.5f;
             }
         }
         if (velocity.Y > 10f)
         {
             velocity.Y = 10f;
         }
         if (num70)
         {
             velocity.Y = 0f;
         }
     }
References Entity.active, Player.AddBuff(), ai, alpha, NPCID.Sets.BelongsToInvasionOldOnesArmy, Collision.CanHit(), Collision.CanHitLine(), DelegateMethods.CastLightOpen(), NPCAimedTarget.Center, Entity.Center, collideX, Color, confused, Player.creativeGodMode, Dust.customData, damage, Main.dayTime, SoundID.DD2_DrakinBreathIn, SoundID.DD2_DrakinShot, SoundID.DD2_EtherianPortalSpawnEnemy, SoundID.DD2_GoblinBomberScream, SoundID.DD2_GoblinBomberThrow, SoundID.DD2_GoblinScream, SoundID.DD2_JavelinThrowersAttack, SoundID.DD2_JavelinThrowersTaunt, SoundID.DD2_KoboldExplosion, SoundID.DD2_KoboldIgnite, SoundID.DD2_KoboldIgniteLoop, SoundID.DD2_KoboldScreamChargeLoop, SoundID.DD2_OgreAttack, SoundID.DD2_OgreGroundPound, SoundID.DD2_OgreRoar, SoundID.DD2_OgreSpit, SoundID.DD2_WitherBeastAuraPulse, SoundID.DD2_WitherBeastCrystalImpact, Player.dead, Entity.direction, Entity.DirectionTo(), directionY, Entity.Distance(), dontTakeDamage, dontTakeDamageFromHostiles, Main.dust, EncourageDespawn(), DD2Event.EnemiesShouldChasePlayers, Dust.fadeIn, NPCID.Sets.FighterUsesDD2PortalAppearEffect, SlotId.FromFloat(), SoundEngine.GetActiveSound(), GetAttackDamage_ForProjectiles(), GetAttackDamage_ScaledByStrength(), Utils.GetLerpValue(), GetSpawnSource_ForProjectile(), GetTargetData(), GetTileCollisionParameters(), Framing.GetTileSafely(), gfxOffY, Main.gore, HasValidTarget, HealEffect(), NPCAimedTarget.Height, Entity.height, NPCAimedTarget.Hitbox, HitEffect(), HitSound, SlotId.Invalid, NPCAimedTarget.Invalid, WorldGen.InWorld(), justHit, WorldGen.KillTile(), life, lifeMax, localAI, Main.maxTilesX, Main.maxTilesY, Main.myPlayer, Tile.nactive(), netAlways, Main.netMode, netOffset, netUpdate, Dust.NewDust(), Dust.NewDustDirect(), Dust.NewDustPerfect(), Gore.NewGore(), Gore.NewGoreDirect(), Projectile.NewProjectile(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Dust.noGravity, noGravity, noTileCollide, Main.npc, NPCUtils.NPCTargetingMethod(), Entity.oldPosition, Entity.oldVelocity, WorldGen.OpenDoor(), Main.player, SoundEngine.PlayTrackedSound(), Utils.PlotTileLine(), ActiveSound.Position, NPCAimedTarget.Position, Dust.position, Entity.position, Gore.position, Main.rand, Utils.RandomVector2(), Dust.scale, NetMessage.SendData(), WorldGen.ShiftTallGate(), Collision.SolidCollision(), WorldGen.SolidTile(), spriteDirection, stepSpeed, Collision.StepUp(), TargetClosest(), NPCUtils.TargetClosestCommon(), NPCUtils.TargetClosestOldOnesInvasion(), Main.tile, Main.tileSolid, Tile.topSlope(), TranslatedTargetIndex, NPCAimedTarget.Type, type, Tile.type, DelegateMethods.v3_1, value, Dust.velocity, Entity.velocity, Gore.velocity, Entity.wet, Entity.whoAmI, NPCAimedTarget.Width, and Entity.width.
Referenced by AI().