Terraria: NPC.GetNPCInvasionGroup
GetNPCInvasionGroup()
static int NPC.GetNPCInvasionGroup (int npcID) inline static
     {
         int result = 0;
         switch (npcID)
         {
         case 26:
         case 27:
         case 28:
         case 29:
         case 111:
         case 471:
         case 472:
             result = 1;
             break;
         case 143:
         case 144:
         case 145:
             result = 2;
             break;
         case 212:
         case 213:
         case 214:
         case 215:
         case 216:
         case 491:
             result = 3;
             break;
         case 381:
         case 382:
         case 383:
         case 385:
         case 386:
         case 387:
         case 388:
         case 389:
         case 390:
         case 391:
         case 395:
             result = 4;
             break;
         case 338:
         case 339:
         case 340:
         case 341:
         case 342:
         case 343:
         case 344:
         case 345:
         case 346:
         case 347:
         case 348:
         case 349:
         case 350:
             result = -1;
             break;
         case 305:
         case 306:
         case 307:
         case 308:
         case 309:
         case 310:
         case 311:
         case 312:
         case 313:
         case 314:
         case 315:
         case 325:
         case 326:
         case 327:
         case 329:
         case 330:
             result = -2;
             break;
         case 547:
         case 548:
         case 549:
         case 550:
         case 551:
         case 552:
         case 553:
         case 554:
         case 555:
         case 556:
         case 557:
         case 558:
         case 559:
         case 560:
         case 561:
         case 562:
         case 563:
         case 564:
         case 565:
         case 566:
         case 567:
         case 568:
         case 569:
         case 570:
         case 571:
         case 572:
         case 573:
         case 574:
         case 575:
         case 576:
         case 577:
         case 578:
             result = -3;
             break;
         }
         return result;
     }
Referenced by Player.AllowShimmerDodge(), checkDead(), and CoinLossRevengeSystem.RevengeMarker.IsInvalid().