Terraria: NPC.AnyInteractions
AnyInteractions()
bool NPC.AnyInteractions () inline
     {
         if (Main.netMode == 0)
         {
             if (playerInteraction[Main.myPlayer])
             {
                 return true;
             }
         }
         else
         {
             for (int i = 0; i < 255; i++)
             {
                 if (playerInteraction[i])
                 {
                     return true;
                 }
             }
         }
         return false;
     }
References Main.myPlayer, Main.netMode, and playerInteraction.
Referenced by DoDeathEvents(), GetWereThereAnyInteractions(), and NPCLoot().