Terraria: NPC.GetBossHeadTextureIndex
GetBossHeadTextureIndex()
int NPC.GetBossHeadTextureIndex () inline
     {
         int result = NPCID.Sets.BossHeadTextures[type];
         switch (type)
         {
         case 4:
             if (ai[0] >= 2f)
             {
                 result = 1;
             }
             break;
         case 266:
             if (ai[0] < 0f)
             {
                 result = -1;
             }
             break;
         case 262:
             if (life <= lifeMax / 2)
             {
                 result = 12;
             }
             break;
         case 125:
             if (ai[0] >= 3f)
             {
                 result = 16;
             }
             break;
         case 126:
             if (ai[0] >= 3f)
             {
                 result = 21;
             }
             break;
         case 439:
             if (ai[0] == 5f && alpha == 255)
             {
                 result = -1;
             }
             break;
         case 440:
             if (ai[0] != 5f || alpha == 255)
             {
                 result = -1;
             }
             break;
         }
         return result;
     }
References ai, alpha, NPCID.Sets.BossHeadTextures, life, lifeMax, and type.
Referenced by Main.DrawMap(), CommonBossBigProgressBar.ValidateAndCollectNecessaryInfo(), DeerclopsBigProgressBar.ValidateAndCollectNecessaryInfo(), LunarPillarBigProgessBar.ValidateAndCollectNecessaryInfo(), and TwinsBigProgressBar.ValidateAndCollectNecessaryInfo().