Terraria: NPC.AI_123_Deerclops_MakeSpikesBothSides
AI_123_Deerclops_MakeSpikesBothSides()
void NPC.AI_123_Deerclops_MakeSpikesBothSides (int AISLOT_PhaseCounter, NPCAimedTarget targetData) inline private
     {
         if (Main.netMode == 1)
         {
             return;
         }
         int num = 56;
         if (!(ai[AISLOT_PhaseCounter] < (float)num))
         {
             Point sourceTileCoords = base.Bottom.ToTileCoordinates();
             int num2 = 15;
             int num3 = 1;
             int num4 = (int)ai[AISLOT_PhaseCounter] - num;
             if (num4 == 0)
             {
                 PunchCameraModifier modifier = new PunchCameraModifier(base.Center, new Vector2(0f, 1f), 20f, 6f, 30, 1000f, "Deerclops");
                 Main.instance.CameraModifiers.Add(modifier);
             }
             int num5 = 2;
             int num6 = num4 / num5 * num5;
             int num7 = num6 + num5;
             if (num4 % num5 != 0)
             {
                 num7 = num6;
             }
             for (int i = num6; i >= 0 && i < num7 && i < num2; i++)
             {
                 int xOffset = i * num3;
                 AI_123_Deerclops_TryMakingSpike(ref sourceTileCoords, direction, num2, -i, xOffset);
                 AI_123_Deerclops_TryMakingSpike(ref sourceTileCoords, -direction, num2, -i, xOffset);
             }
         }
     }
References CameraModifierStack.Add(), ai, AI_123_Deerclops_TryMakingSpike(), Main.CameraModifiers, Entity.direction, Main.instance, and Main.netMode.
Referenced by AI_123_Deerclops().