Terraria: NPC.AI_123_Deerclops_TryMakingSpike
AI_123_Deerclops_TryMakingSpike()
void NPC.AI_123_Deerclops_TryMakingSpike (ref Point sourceTileCoords, int dir, int howMany, int whichOne, int xOffset) inline private
     {
         int num = 13;
         int num2 = sourceTileCoords.X + xOffset * dir;
         int num3 = AI_123_Deerclops_TryMakingSpike_FindBestY(ref sourceTileCoords, num2);
         if (WorldGen.ActiveAndWalkableTile(num2, num3))
         {
             Vector2 vector = new Vector2(num2 * 16 + 8, num3 * 16 - 8);
             Vector2 vector2 = new Vector2(0f, -1f).RotatedBy((float)(whichOne * dir) * 0.7f * ((float)Math.PI / 4f / (float)howMany));
             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector, vector2, 961, num, 0f, Main.myPlayer, 0f, 0.1f + Main.rand.NextFloat() * 0.1f + (float)xOffset * 1.1f / (float)howMany);
         }
     }
References WorldGen.ActiveAndWalkableTile(), AI_123_Deerclops_TryMakingSpike_FindBestY(), GetSpawnSource_ForProjectile(), Main.myPlayer, Projectile.NewProjectile(), and Main.rand.
Referenced by AI_123_Deerclops_MakeSpikesBothSides(), and AI_123_Deerclops_MakeSpikesForward().