Terraria: NPC.ViolentlySpawnNerdySlime
ViolentlySpawnNerdySlime()
void NPC.ViolentlySpawnNerdySlime () inline private
     {
         int num = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X - 10, (int)base.Center.Y, 670);
         NPC obj = Main.npc[num];
         Vector2 movementVector = (obj.velocity = new Vector2(Main.rand.NextFloatDirection() * 3f, -10f));
         obj.netUpdate = true;
         WorldGen.CheckAchievement_RealEstateAndTownSlimes();
         ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.TownSlimeTransform, new ParticleOrchestraSettings
         {
             PositionInWorld = base.Center,
             MovementVector = movementVector,
             UniqueInfoPiece = 0
         });
     }
References ParticleOrchestrator.BroadcastParticleSpawn(), WorldGen.CheckAchievement_RealEstateAndTownSlimes(), GetSpawnSourceForNPCFromNPCAI(), netUpdate, NewNPC(), Main.npc, Main.rand, and Entity.velocity.
Referenced by DoDeathEvents().