Terraria: System.Linq.Parallel.OrderPreservingPipeliningMergeHelper.OrderedPipeliningMergeEnumerator.MoveNext
MoveNext()
override bool System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator.MoveNext () inline
Definition at line 56 of file OrderPreservingPipeliningMergeHelper.cs.
        {
            if (!_initialized)
            {
                _initialized = true;
                for (int i = 0; i < _mergeHelper._partitions.PartitionCount; i++)
                {
                    Pair<TKey, TOutput> element = default(Pair<TKey, TOutput>);
                    if (TryWaitForElement(i, ref element))
                    {
                        _producerHeap.Insert(new Producer<TKey>(element.First, i));
                        _producerNextElement[i] = element.Second;
                    }
                    else
                    {
                        ThrowIfInTearDown();
                    }
                }
            }
            else
            {
                if (_producerHeap.Count == 0)
                {
                    return false;
                }
                int producerIndex = _producerHeap.MaxValue.ProducerIndex;
                Pair<TKey, TOutput> element2 = default(Pair<TKey, TOutput>);
                if (TryGetPrivateElement(producerIndex, ref element2) || TryWaitForElement(producerIndex, ref element2))
                {
                    _producerHeap.ReplaceMax(new Producer<TKey>(element2.First, producerIndex));
                    _producerNextElement[producerIndex] = element2.Second;
                }
                else
                {
                    ThrowIfInTearDown();
                    _producerHeap.RemoveMax();
                }
            }
            return _producerHeap.Count > 0;
        }
References System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator._initialized, System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator._mergeHelper, System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator._producerHeap, System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator._producerNextElement, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator.ThrowIfInTearDown(), System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator.TryGetPrivateElement(), and System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator.TryWaitForElement().