Terraria: System.Linq.Parallel.OrderPreservingPipeliningMergeHelper.OrderedPipeliningMergeEnumerator.ThrowIfInTearDown
ThrowIfInTearDown()
void System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator.ThrowIfInTearDown () inline private
Definition at line 97 of file OrderPreservingPipeliningMergeHelper.cs.
        {
            if (!_mergeHelper._taskGroupState.CancellationState.MergedCancellationToken.IsCancellationRequested)
            {
                return;
            }
            try
            {
                object[] bufferLocks = _mergeHelper._bufferLocks;
                for (int i = 0; i < bufferLocks.Length; i++)
                {
                    lock (bufferLocks[i])
                    {
                        Monitor.Pulse(bufferLocks[i]);
                    }
                }
                _taskGroupState.QueryEnd(userInitiatedDispose: false);
            }
            finally
            {
                _producerHeap.Clear();
            }
        }
References System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator._mergeHelper, System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator._producerHeap, System.Linq.Parallel.MergeEnumerator< TOutput >._taskGroupState, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Threading.Monitor.Pulse(), and System.Linq.Parallel.QueryTaskGroupState.QueryEnd().
Referenced by System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator.MoveNext().