Terraria: System.Runtime.Serialization.SerializationEvents.AddOnDelegate
AddOnDelegate()
static SerializationEventHandler System.Runtime.Serialization.SerializationEvents.AddOnDelegate (object obj, SerializationEventHandler handler, List< MethodInfo > methods) inline static private
Definition at line 92 of file SerializationEvents.cs.
    {
        if (methods != null)
        {
            foreach (MethodInfo method in methods)
            {
                SerializationEventHandler b = method.CreateDelegate<SerializationEventHandler>(obj);
                handler = (SerializationEventHandler)Delegate.Combine(handler, b);
            }
        }
        return handler;
    }
References System.Delegate.Combine(), System.obj, and System.Runtime.Serialization.SerializationEventHandler().
Referenced by System.Runtime.Serialization.SerializationEvents.AddOnDeserialized(), System.Runtime.Serialization.SerializationEvents.AddOnSerialized(), and System.Runtime.Serialization.SerializationEvents.InvokeOnDelegate().