Terraria: System.Data.ProviderBase.FieldNameLookup.LinearIndexOf
LinearIndexOf()
int System.Data.ProviderBase.FieldNameLookup.LinearIndexOf (string fieldName, CompareOptions compareOptions) inline private
Definition at line 66 of file FieldNameLookup.cs.
    {
        CompareInfo compareInfo = _compareInfo;
        if (compareInfo == null)
        {
            if (-1 != _defaultLocaleID)
            {
                compareInfo = CompareInfo.GetCompareInfo(_defaultLocaleID);
            }
            if (compareInfo == null)
            {
                compareInfo = CultureInfo.InvariantCulture.CompareInfo;
            }
            _compareInfo = compareInfo;
        }
        int num = _fieldNames.Length;
        for (int i = 0; i < num; i++)
        {
            if (compareInfo.Compare(fieldName, _fieldNames[i], compareOptions) == 0)
            {
                _fieldNameLookup[fieldName] = i;
                return i;
            }
        }
        return -1;
    }
References System.Data.ProviderBase.FieldNameLookup._compareInfo, System.Data.ProviderBase.FieldNameLookup._defaultLocaleID, System.Data.ProviderBase.FieldNameLookup._fieldNameLookup, System.Data.ProviderBase.FieldNameLookup._fieldNames, System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.GetCompareInfo(), and System.Globalization.CultureInfo.InvariantCulture.
Referenced by System.Data.ProviderBase.FieldNameLookup.IndexOf().