Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteEndAttribute
WriteEndAttribute()
void System.Runtime.Serialization.XmlWriterDelegator.WriteEndAttribute () inline private inherited
Definition at line 42 of file XmlWriterDelegator.cs.
    {
        writer.WriteEndAttribute();
    }
References System.Xml.XmlWriter.WriteEndAttribute(), and System.Runtime.Serialization.XmlWriterDelegator.writer.
Referenced by System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeBool(), System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeInt(), System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeQualifiedName(), System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeQualifiedName(), System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeString(), System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeString(), and System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeString().