Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeBool
WriteAttributeBool()
void System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeBool (string prefix, XmlDictionaryString attrName, XmlDictionaryString attrNs, bool value) inline package inherited
Definition at line 188 of file XmlWriterDelegator.cs.
    {
        WriteStartAttribute(prefix, attrName, attrNs);
        WriteAttributeBoolValue(value);
        WriteEndAttribute();
    }
References System.Runtime.Serialization.Dictionary, System.prefix, System.value, System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeBoolValue(), System.Runtime.Serialization.XmlWriterDelegator.WriteEndAttribute(), and System.Runtime.Serialization.XmlWriterDelegator.WriteStartAttribute().