Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute
WriteXmlnsAttribute() [1/3]
void System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute (string ns) inline package inherited
Definition at line 78 of file XmlWriterDelegator.cs.
    {
        if (ns == null)
        {
            return;
        }
        if (ns.Length == 0)
        {
            writer.WriteAttributeString("xmlns", string.Empty, null, ns);
            return;
        }
        if (dictionaryWriter != null)
        {
            dictionaryWriter.WriteXmlnsAttribute(null, ns);
            return;
        }
        string text = writer.LookupPrefix(ns);
        if (text == null)
        {
            IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
            DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(2, 2, invariantCulture);
            handler.AppendLiteral("d");
            handler.AppendFormatted(depth);
            handler.AppendLiteral("p");
            handler.AppendFormatted(_prefixes);
            text = string.Create(invariantCulture, ref handler);
            _prefixes++;
            writer.WriteAttributeString("xmlns", text, null, ns);
        }
    }
References System.Runtime.Serialization.XmlWriterDelegator._prefixes, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Runtime.Serialization.XmlWriterDelegator.depth, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlWriterDelegator.dictionaryWriter, System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlWriter.LookupPrefix(), System.text, System.Xml.XmlWriter.WriteAttributeString(), System.Runtime.Serialization.XmlWriterDelegator.writer, and System.Xml.XmlDictionaryWriter.WriteXmlnsAttribute().