Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteUri
WriteUri() [1/2]
void System.Runtime.Serialization.XmlWriterDelegator.WriteUri (Uri value) inline package inherited
Definition at line 686 of file XmlWriterDelegator.cs.
    {
        writer.WriteString(value?.GetComponents(UriComponents.SerializationInfoString, UriFormat.UriEscaped));
    }
References System.value, System.Runtime.Serialization.XmlWriterDelegator.writer, and System.Xml.XmlWriter.WriteString().
Referenced by System.Runtime.Serialization.XmlWriterDelegator.WriteAnyType(), System.Runtime.Serialization.XmlWriterDelegator.WriteExtensionData(), and System.Runtime.Serialization.XmlWriterDelegator.WriteUri().