Terraria: System.Runtime.Serialization.XmlWriterDelegator.CreateInvalidPrimitiveTypeException
CreateInvalidPrimitiveTypeException()
Exception System.Runtime.Serialization.XmlWriterDelegator.CreateInvalidPrimitiveTypeException (Type type) inline private inherited
Definition at line 286 of file XmlWriterDelegator.cs.
    {
        return new InvalidDataContractException(System.SR.Format(System.SR.InvalidPrimitiveType_Serialization, DataContract.GetClrTypeFullName(type)));
    }
References System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.InvalidPrimitiveType_Serialization, and System.type.
Referenced by System.Runtime.Serialization.XmlWriterDelegator.WriteAnyType(), and System.Runtime.Serialization.XmlWriterDelegator.WriteExtensionData().