Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedByte
WriteUnsignedByte() [1/2]
virtual void System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedByte (byte value) inline package virtual
Reimplemented in System.Runtime.Serialization.Json.JsonWriterDelegator.
Definition at line 583 of file XmlWriterDelegator.cs.
    {
        writer.WriteValue(value);
    }
References System.value, System.Runtime.Serialization.XmlWriterDelegator.writer, and System.Xml.XmlWriter.WriteValue().
Referenced by System.Runtime.Serialization.XmlWriterDelegator.WriteAnyType(), System.Runtime.Serialization.XmlWriterDelegator.WriteExtensionData(), and System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedByte().