Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute
WriteXmlnsAttribute() [3/3]
void System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute (XmlDictionaryString ns) inline package inherited
Definition at line 63 of file XmlWriterDelegator.cs.
    {
        if (dictionaryWriter != null)
        {
            if (ns != null)
            {
                dictionaryWriter.WriteXmlnsAttribute(null, ns);
            }
        }
        else
        {
            WriteXmlnsAttribute(ns.Value);
        }
    }
References System.Runtime.Serialization.XmlWriterDelegator.dictionaryWriter, System.Xml.XmlDictionaryString.Value, System.Xml.XmlDictionaryWriter.WriteXmlnsAttribute(), and System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute().
Referenced by System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeQualifiedName(), System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeQualifiedName(), System.Runtime.Serialization.XmlWriterDelegator.WriteNamespaceDecl(), System.Runtime.Serialization.XmlWriterDelegator.WriteQName(), and System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute().