Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteStartElementPrimitive
WriteStartElementPrimitive()
void System.Runtime.Serialization.XmlWriterDelegator.WriteStartElementPrimitive (XmlDictionaryString localName, XmlDictionaryString namespaceUri) inline package inherited
Definition at line 264 of file XmlWriterDelegator.cs.
    {
        if (dictionaryWriter != null)
        {
            dictionaryWriter.WriteStartElement(null, localName, namespaceUri);
        }
        else
        {
            writer.WriteStartElement(null, localName?.Value, namespaceUri?.Value);
        }
    }
References System.Runtime.Serialization.XmlWriterDelegator.dictionaryWriter, System.Runtime.Serialization.XmlWriterDelegator.writer, System.Xml.XmlWriter.WriteStartElement(), and System.Xml.XmlDictionaryWriter.WriteStartElement().
Referenced by System.Runtime.Serialization.XmlWriterDelegator.WriteBoolean(), System.Runtime.Serialization.XmlWriterDelegator.WriteChar(), System.Runtime.Serialization.XmlWriterDelegator.WriteDateTime(), System.Runtime.Serialization.XmlWriterDelegator.WriteDecimal(), System.Runtime.Serialization.XmlWriterDelegator.WriteDouble(), System.Runtime.Serialization.XmlWriterDelegator.WriteFloat(), System.Runtime.Serialization.XmlWriterDelegator.WriteGuid(), System.Runtime.Serialization.XmlWriterDelegator.WriteInt(), System.Runtime.Serialization.XmlWriterDelegator.WriteLong(), System.Runtime.Serialization.XmlWriterDelegator.WriteShort(), System.Runtime.Serialization.XmlWriterDelegator.WriteSignedByte(), System.Runtime.Serialization.XmlWriterDelegator.WriteTimeSpan(), System.Runtime.Serialization.XmlWriterDelegator.WriteTimeSpan(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedByte(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedInt(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedLong(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedShort(), and System.Runtime.Serialization.XmlWriterDelegator.WriteUri().