Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteExtensionData
WriteExtensionData()
void System.Runtime.Serialization.XmlWriterDelegator.WriteExtensionData (IDataNode dataNode) inline package inherited
Definition at line 382 of file XmlWriterDelegator.cs.
    {
        bool flag = true;
        Type dataType = dataNode.DataType;
        switch (Type.GetTypeCode(dataType))
        {
        case TypeCode.Boolean:
            WriteBoolean(((DataNode<bool>)dataNode).GetValue());
            break;
        case TypeCode.Char:
            WriteChar(((DataNode<char>)dataNode).GetValue());
            break;
        case TypeCode.Byte:
            WriteUnsignedByte(((DataNode<byte>)dataNode).GetValue());
            break;
        case TypeCode.Int16:
            WriteShort(((DataNode<short>)dataNode).GetValue());
            break;
        case TypeCode.Int32:
            WriteInt(((DataNode<int>)dataNode).GetValue());
            break;
        case TypeCode.Int64:
            WriteLong(((DataNode<long>)dataNode).GetValue());
            break;
        case TypeCode.Single:
            WriteFloat(((DataNode<float>)dataNode).GetValue());
            break;
        case TypeCode.Double:
            WriteDouble(((DataNode<double>)dataNode).GetValue());
            break;
        case TypeCode.Decimal:
            WriteDecimal(((DataNode<decimal>)dataNode).GetValue());
            break;
        case TypeCode.DateTime:
            WriteDateTime(((DataNode<DateTime>)dataNode).GetValue());
            break;
        case TypeCode.String:
            WriteString(((DataNode<string>)dataNode).GetValue());
            break;
        case TypeCode.SByte:
            WriteSignedByte(((DataNode<sbyte>)dataNode).GetValue());
            break;
        case TypeCode.UInt16:
            WriteUnsignedShort(((DataNode<ushort>)dataNode).GetValue());
            break;
        case TypeCode.UInt32:
            WriteUnsignedInt(((DataNode<uint>)dataNode).GetValue());
            break;
        case TypeCode.UInt64:
            WriteUnsignedLong(((DataNode<ulong>)dataNode).GetValue());
            break;
        default:
            if (dataType == Globals.TypeOfByteArray)
            {
                WriteBase64(((DataNode<byte[]>)dataNode).GetValue());
            }
            else if (dataType == Globals.TypeOfObject)
            {
                object value = dataNode.Value;
                if (value != null)
                {
                    WriteAnyType(value);
                }
            }
            else if (dataType == Globals.TypeOfTimeSpan)
            {
                WriteTimeSpan(((DataNode<TimeSpan>)dataNode).GetValue());
            }
            else if (dataType == Globals.TypeOfGuid)
            {
                WriteGuid(((DataNode<Guid>)dataNode).GetValue());
            }
            else if (dataType == Globals.TypeOfUri)
            {
                WriteUri(((DataNode<Uri>)dataNode).GetValue());
            }
            else if (dataType == Globals.TypeOfXmlQualifiedName)
            {
                WriteQName(((DataNode<XmlQualifiedName>)dataNode).GetValue());
            }
            else
            {
                flag = false;
            }
            break;
        }
        if (!flag)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateInvalidPrimitiveTypeException(dataType));
        }
    }
References System.Runtime.Serialization.XmlWriterDelegator.CreateInvalidPrimitiveTypeException(), System.Runtime.Serialization.IDataNode.DataType, System.Type.GetTypeCode(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.Globals.TypeOfByteArray, System.Runtime.Serialization.Globals.TypeOfGuid, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.Globals.TypeOfTimeSpan, System.Runtime.Serialization.Globals.TypeOfUri, System.Runtime.Serialization.Globals.TypeOfXmlQualifiedName, System.value, System.Runtime.Serialization.DataNode< T >.Value, System.Runtime.Serialization.XmlWriterDelegator.WriteAnyType(), System.Runtime.Serialization.XmlWriterDelegator.WriteBase64(), System.Runtime.Serialization.XmlWriterDelegator.WriteBoolean(), System.Runtime.Serialization.XmlWriterDelegator.WriteChar(), System.Runtime.Serialization.XmlWriterDelegator.WriteDateTime(), System.Runtime.Serialization.XmlWriterDelegator.WriteDecimal(), System.Runtime.Serialization.XmlWriterDelegator.WriteDouble(), System.Runtime.Serialization.XmlWriterDelegator.WriteFloat(), System.Runtime.Serialization.XmlWriterDelegator.WriteGuid(), System.Runtime.Serialization.XmlWriterDelegator.WriteInt(), System.Runtime.Serialization.XmlWriterDelegator.WriteLong(), System.Runtime.Serialization.XmlWriterDelegator.WriteQName(), System.Runtime.Serialization.XmlWriterDelegator.WriteShort(), System.Runtime.Serialization.XmlWriterDelegator.WriteSignedByte(), System.Runtime.Serialization.XmlWriterDelegator.WriteString(), System.Runtime.Serialization.XmlWriterDelegator.WriteTimeSpan(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedByte(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedInt(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedLong(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedShort(), and System.Runtime.Serialization.XmlWriterDelegator.WriteUri().