Terraria: System.Text.BaseCodePageEncoding.CheckMemorySection
CheckMemorySection()
void System.Text.BaseCodePageEncoding.CheckMemorySection () inline package inherited
Definition at line 312 of file BaseCodePageEncoding.cs.
    {
        if (safeNativeMemoryHandle != null && safeNativeMemoryHandle.DangerousGetHandle() == IntPtr.Zero)
        {
            LoadManagedCodePage();
        }
    }
References System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Text.BaseCodePageEncoding.LoadManagedCodePage(), System.Text.BaseCodePageEncoding.safeNativeMemoryHandle, and System.IntPtr.Zero.
Referenced by System.Text.DBCSCodePageEncoding.GetByteCount(), System.Text.SBCSCodePageEncoding.GetByteCount(), System.Text.DBCSCodePageEncoding.GetBytes(), System.Text.SBCSCodePageEncoding.GetBytes(), System.Text.DBCSCodePageEncoding.GetCharCount(), System.Text.SBCSCodePageEncoding.GetCharCount(), System.Text.DBCSCodePageEncoding.GetChars(), and System.Text.SBCSCodePageEncoding.GetChars().