Terraria: System.Text.BaseCodePageEncoding.GetEncodings
GetEncodings() [2/2]
static unsafe EncodingInfo[] System.Text.BaseCodePageEncoding.GetEncodings (CodePagesEncodingProvider provider) inline static package inherited
Definition at line 341 of file BaseCodePageEncoding.cs.
    {
        lock (s_streamLock)
        {
            s_codePagesEncodingDataStream.Seek(44L, SeekOrigin.Begin);
            int codePageCount;
            fixed (byte* ptr = &s_codePagesDataHeader[0])
            {
                CodePageDataFileHeader* ptr2 = (CodePageDataFileHeader*)ptr;
                codePageCount = ptr2->CodePageCount;
            }
            EncodingInfo[] array = new EncodingInfo[codePageCount];
            CodePageIndex codePageIndex = default(CodePageIndex);
            Span<byte> codePageIndex2 = new Span<byte>(&codePageIndex, Unsafe.SizeOf<CodePageIndex>());
            for (int i = 0; i < codePageCount; i++)
            {
                ReadCodePageIndex(s_codePagesEncodingDataStream, codePageIndex2);
                string text = codePageIndex.CodePage switch
                {
                    950 => "big5",
                    10002 => "x-mac-chinesetrad",
                    20833 => "x-ebcdic-koreanextended",
                    _ => new string(&codePageIndex.CodePageName),
                };
                string localizedEncodingNameResource = EncodingNLS.GetLocalizedEncodingNameResource(codePageIndex.CodePage);
                string text2 = null;
                if (localizedEncodingNameResource != null && localizedEncodingNameResource.StartsWith("Globalization_cp_", StringComparison.OrdinalIgnoreCase))
                {
                    text2 = System.SR.GetResourceString(localizedEncodingNameResource);
                }
                array[i] = new EncodingInfo(provider, codePageIndex.CodePage, text, text2 ?? text);
            }
            return array;
        }
    }
References System.array, System.Text.BaseCodePageEncoding.CodePageDataFileHeader.CodePageCount, System.Runtime.Serialization.Dictionary, System.Text.EncodingNLS.GetLocalizedEncodingNameResource(), System.SR.GetResourceString(), System.L, System.Text.BaseCodePageEncoding.ReadCodePageIndex(), System.Text.BaseCodePageEncoding.s_codePagesDataHeader, System.Text.BaseCodePageEncoding.s_codePagesEncodingDataStream, System.Text.BaseCodePageEncoding.s_streamLock, and System.text.
Referenced by System.Text.CodePagesEncodingProvider.GetEncodings().