Terraria: System.Text.BaseCodePageEncoding.LoadCodePageTables
LoadCodePageTables()
void System.Text.BaseCodePageEncoding.LoadCodePageTables () inline private inherited
Definition at line 200 of file BaseCodePageEncoding.cs.
    {
        if (!FindCodePage(dataTableCodePage))
        {
            throw new NotSupportedException(System.SR.Format(System.SR.NotSupported_NoCodepageData, CodePage));
        }
        LoadManagedCodePage();
    }
References System.Text.Encoding.CodePage, System.Text.BaseCodePageEncoding.dataTableCodePage, System.Text.BaseCodePageEncoding.FindCodePage(), System.SR.Format(), System.Text.BaseCodePageEncoding.LoadManagedCodePage(), and System.SR.NotSupported_NoCodepageData.
Referenced by System.Text.BaseCodePageEncoding.BaseCodePageEncoding(), and System.Text.BaseCodePageEncoding.BaseCodePageEncoding().