Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteGuid
WriteGuid() [2/2]
void System.Runtime.Serialization.XmlWriterDelegator.WriteGuid (Guid value, XmlDictionaryString name, XmlDictionaryString ns) inline package inherited
Definition at line 679 of file XmlWriterDelegator.cs.
    {
        WriteStartElementPrimitive(name, ns);
        WriteGuid(value);
        WriteEndElementPrimitive();
    }
References System.value, System.Runtime.Serialization.XmlWriterDelegator.WriteEndElementPrimitive(), System.Runtime.Serialization.XmlWriterDelegator.WriteGuid(), and System.Runtime.Serialization.XmlWriterDelegator.WriteStartElementPrimitive().