Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeQualifiedName
WriteAttributeQualifiedName() [2/2]
void System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeQualifiedName (string attrPrefix, XmlDictionaryString attrName, XmlDictionaryString attrNs, XmlDictionaryString name, XmlDictionaryString ns) inline package inherited
Definition at line 213 of file XmlWriterDelegator.cs.
    {
        WriteXmlnsAttribute(ns);
        WriteStartAttribute(attrPrefix, attrName, attrNs);
        WriteAttributeQualifiedNameValue(name, ns);
        WriteEndAttribute();
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeQualifiedNameValue(), System.Runtime.Serialization.XmlWriterDelegator.WriteEndAttribute(), System.Runtime.Serialization.XmlWriterDelegator.WriteStartAttribute(), and System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute().