Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteDateTime
WriteDateTime() [1/2]
virtual void System.Runtime.Serialization.XmlWriterDelegator.WriteDateTime (DateTime value) inline package virtual
Reimplemented in System.Runtime.Serialization.Json.JsonWriterDelegator.
Definition at line 491 of file XmlWriterDelegator.cs.
    {
        WriteString(XmlConvert.ToString(value, XmlDateTimeSerializationMode.RoundtripKind));
    }
References System.Xml.XmlConvert.ToString(), System.value, and System.Runtime.Serialization.XmlWriterDelegator.WriteString().
Referenced by System.Runtime.Serialization.XmlWriterDelegator.WriteAnyType(), System.Runtime.Serialization.XmlWriterDelegator.WriteDateTime(), System.Runtime.Serialization.XmlWriterDelegator.WriteDateTimeArray(), and System.Runtime.Serialization.XmlWriterDelegator.WriteExtensionData().