Terraria: System.Runtime.Serialization.XmlWriterDelegator.WriteAnyType
WriteAnyType() [2/2]
void System.Runtime.Serialization.XmlWriterDelegator.WriteAnyType (object value, Type valueType) inline package inherited
Definition at line 296 of file XmlWriterDelegator.cs.
    {
        bool flag = true;
        switch (valueType.GetTypeCode())
        {
        case TypeCode.Boolean:
            WriteBoolean((bool)value);
            break;
        case TypeCode.Char:
            WriteChar((char)value);
            break;
        case TypeCode.Byte:
            WriteUnsignedByte((byte)value);
            break;
        case TypeCode.Int16:
            WriteShort((short)value);
            break;
        case TypeCode.Int32:
            WriteInt((int)value);
            break;
        case TypeCode.Int64:
            WriteLong((long)value);
            break;
        case TypeCode.Single:
            WriteFloat((float)value);
            break;
        case TypeCode.Double:
            WriteDouble((double)value);
            break;
        case TypeCode.Decimal:
            WriteDecimal((decimal)value);
            break;
        case TypeCode.DateTime:
            WriteDateTime((DateTime)value);
            break;
        case TypeCode.String:
            WriteString((string)value);
            break;
        case TypeCode.SByte:
            WriteSignedByte((sbyte)value);
            break;
        case TypeCode.UInt16:
            WriteUnsignedShort((ushort)value);
            break;
        case TypeCode.UInt32:
            WriteUnsignedInt((uint)value);
            break;
        case TypeCode.UInt64:
            WriteUnsignedLong((ulong)value);
            break;
        default:
            if (valueType == Globals.TypeOfByteArray)
            {
                WriteBase64((byte[])value);
            }
            else if (!(valueType == Globals.TypeOfObject))
            {
                if (valueType == Globals.TypeOfTimeSpan)
                {
                    WriteTimeSpan((TimeSpan)value);
                }
                else if (valueType == Globals.TypeOfGuid)
                {
                    WriteGuid((Guid)value);
                }
                else if (valueType == Globals.TypeOfUri)
                {
                    WriteUri((Uri)value);
                }
                else if (valueType == Globals.TypeOfXmlQualifiedName)
                {
                    WriteQName((XmlQualifiedName)value);
                }
                else
                {
                    flag = false;
                }
            }
            break;
        }
        if (!flag)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateInvalidPrimitiveTypeException(valueType));
        }
    }
References System.Runtime.Serialization.XmlWriterDelegator.CreateInvalidPrimitiveTypeException(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.Globals.TypeOfByteArray, System.Runtime.Serialization.Globals.TypeOfGuid, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.Globals.TypeOfTimeSpan, System.Runtime.Serialization.Globals.TypeOfUri, System.Runtime.Serialization.Globals.TypeOfXmlQualifiedName, System.value, System.Runtime.Serialization.XmlWriterDelegator.WriteBase64(), System.Runtime.Serialization.XmlWriterDelegator.WriteBoolean(), System.Runtime.Serialization.XmlWriterDelegator.WriteChar(), System.Runtime.Serialization.XmlWriterDelegator.WriteDateTime(), System.Runtime.Serialization.XmlWriterDelegator.WriteDecimal(), System.Runtime.Serialization.XmlWriterDelegator.WriteDouble(), System.Runtime.Serialization.XmlWriterDelegator.WriteFloat(), System.Runtime.Serialization.XmlWriterDelegator.WriteGuid(), System.Runtime.Serialization.XmlWriterDelegator.WriteInt(), System.Runtime.Serialization.XmlWriterDelegator.WriteLong(), System.Runtime.Serialization.XmlWriterDelegator.WriteQName(), System.Runtime.Serialization.XmlWriterDelegator.WriteShort(), System.Runtime.Serialization.XmlWriterDelegator.WriteSignedByte(), System.Runtime.Serialization.XmlWriterDelegator.WriteString(), System.Runtime.Serialization.XmlWriterDelegator.WriteTimeSpan(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedByte(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedInt(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedLong(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedShort(), and System.Runtime.Serialization.XmlWriterDelegator.WriteUri().