Terraria: PirateInvasionShader.ProcessHighDetail
ProcessHighDetail()
void PirateInvasionShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
     {
         for (int i = 0; i < fragment.Count; i++)
         {
             Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
             Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
             gridPositionOfIndex.X /= 2;
             float num = (NoiseHelper.GetStaticNoise(gridPositionOfIndex.X) * 40f + time * 1f) % 40f;
             float amount = 0f;
             float num2 = num - canvasPositionOfIndex.Y / 1.2f;
             if (num > 1f)
             {
                 float num3 = 1f - canvasPositionOfIndex.Y / 1.2f;
                 amount = (1f - Math.Min(1f, num2 - num3)) * (1f - Math.Min(1f, num3 / 1f));
             }
             Vector4 vector = _backgroundColor;
             if (num2 > 0f)
             {
                 float amount2 = Math.Max(0f, 1.2f - num2 * 4f);
                 if (num2 < 0.1f)
                 {
                     amount2 = num2 / 0.1f;
                 }
                 vector = Vector4.Lerp(vector, _cannonBallColor, amount2);
                 vector = Vector4.Lerp(vector, _splashColor, amount);
             }
             if (canvasPositionOfIndex.Y > 0.8f)
             {
                 vector = _waterColor;
             }
             fragment.SetColor(i, vector);
         }
     }
References _backgroundColor, _cannonBallColor, _splashColor, _waterColor, Fragment.Count, Fragment.GetCanvasPositionOfIndex(), Fragment.GetGridPositionOfIndex(), NoiseHelper.GetStaticNoise(), and Fragment.SetColor().