Terraria: LegacySoundPlayer.LoadAll
LoadAll()
void LegacySoundPlayer.LoadAll () inline private
     {
         SoundMech[0] = Load("Sounds/Mech_0");
         SoundGrab = Load("Sounds/Grab");
         SoundPixie = Load("Sounds/Pixie");
         SoundDig[0] = Load("Sounds/Dig_0");
         SoundDig[1] = Load("Sounds/Dig_1");
         SoundDig[2] = Load("Sounds/Dig_2");
         SoundThunder[0] = Load("Sounds/Thunder_0");
         SoundThunder[1] = Load("Sounds/Thunder_1");
         SoundThunder[2] = Load("Sounds/Thunder_2");
         SoundThunder[3] = Load("Sounds/Thunder_3");
         SoundThunder[4] = Load("Sounds/Thunder_4");
         SoundThunder[5] = Load("Sounds/Thunder_5");
         SoundThunder[6] = Load("Sounds/Thunder_6");
         SoundResearch[0] = Load("Sounds/Research_0");
         SoundResearch[1] = Load("Sounds/Research_1");
         SoundResearch[2] = Load("Sounds/Research_2");
         SoundResearch[3] = Load("Sounds/Research_3");
         SoundTink[0] = Load("Sounds/Tink_0");
         SoundTink[1] = Load("Sounds/Tink_1");
         SoundTink[2] = Load("Sounds/Tink_2");
         SoundPlayerHit[0] = Load("Sounds/Player_Hit_0");
         SoundPlayerHit[1] = Load("Sounds/Player_Hit_1");
         SoundPlayerHit[2] = Load("Sounds/Player_Hit_2");
         SoundFemaleHit[0] = Load("Sounds/Female_Hit_0");
         SoundFemaleHit[1] = Load("Sounds/Female_Hit_1");
         SoundFemaleHit[2] = Load("Sounds/Female_Hit_2");
         SoundPlayerKilled = Load("Sounds/Player_Killed");
         SoundChat = Load("Sounds/Chat");
         SoundGrass = Load("Sounds/Grass");
         SoundDoorOpen = Load("Sounds/Door_Opened");
         SoundDoorClosed = Load("Sounds/Door_Closed");
         SoundMenuTick = Load("Sounds/Menu_Tick");
         SoundMenuOpen = Load("Sounds/Menu_Open");
         SoundMenuClose = Load("Sounds/Menu_Close");
         SoundShatter = Load("Sounds/Shatter");
         SoundCamera = Load("Sounds/Camera");
         for (int i = 0; i < SoundCoin.Length; i++)
         {
             SoundCoin[i] = Load("Sounds/Coin_" + i);
         }
         for (int j = 0; j < SoundDrip.Length; j++)
         {
             SoundDrip[j] = Load("Sounds/Drip_" + j);
         }
         for (int k = 0; k < SoundZombie.Length; k++)
         {
             SoundZombie[k] = Load("Sounds/Zombie_" + k);
         }
         for (int l = 0; l < SoundLiquid.Length; l++)
         {
             SoundLiquid[l] = Load("Sounds/Liquid_" + l);
         }
         for (int m = 0; m < SoundRoar.Length; m++)
         {
             SoundRoar[m] = Load("Sounds/Roar_" + m);
         }
         for (int n = 0; n < SoundSplash.Length; n++)
         {
             SoundSplash[n] = Load("Sounds/Splash_" + n);
         }
         SoundDoubleJump = Load("Sounds/Double_Jump");
         SoundRun = Load("Sounds/Run");
         SoundCoins = Load("Sounds/Coins");
         SoundUnlock = Load("Sounds/Unlock");
         SoundMaxMana = Load("Sounds/MaxMana");
         SoundDrown = Load("Sounds/Drown");
         for (int num = 1; num < SoundItem.Length; num++)
         {
             SoundItem[num] = Load("Sounds/Item_" + num);
         }
         for (int num2 = 1; num2 < SoundNpcHit.Length; num2++)
         {
             SoundNpcHit[num2] = Load("Sounds/NPC_Hit_" + num2);
         }
         for (int num3 = 1; num3 < SoundNpcKilled.Length; num3++)
         {
             SoundNpcKilled[num3] = Load("Sounds/NPC_Killed_" + num3);
         }
         TrackableSounds = new Asset<SoundEffect>[SoundID.TrackableLegacySoundCount];
         TrackableSoundInstances = new SoundEffectInstance[TrackableSounds.Length];
         for (int num4 = 0; num4 < TrackableSounds.Length; num4++)
         {
             TrackableSounds[num4] = Load("Sounds/Custom" + Path.DirectorySeparatorChar + SoundID.GetTrackableLegacySoundPath(num4));
         }
     }
References SoundID.GetTrackableLegacySoundPath(), Load(), SoundCamera, SoundChat, SoundCoin, SoundCoins, SoundDig, SoundDoorClosed, SoundDoorOpen, SoundDoubleJump, SoundDrip, SoundDrown, SoundFemaleHit, SoundGrab, SoundGrass, SoundItem, SoundLiquid, SoundMaxMana, SoundMech, SoundMenuClose, SoundMenuOpen, SoundMenuTick, SoundNpcHit, SoundNpcKilled, SoundPixie, SoundPlayerHit, SoundPlayerKilled, SoundResearch, SoundRoar, SoundRun, SoundShatter, SoundSplash, SoundThunder, SoundTink, SoundUnlock, SoundZombie, SoundID.TrackableLegacySoundCount, TrackableSoundInstances, and TrackableSounds.
Referenced by LegacySoundPlayer().