Terraria: System.Xml.Linq.XNode.GetXmlString
GetXmlString()
string System.Xml.Linq.XNode.GetXmlString (SaveOptions o) inline private inherited
Definition at line 526 of file XNode.cs.
    {
        using StringWriter stringWriter = new StringWriter(CultureInfo.InvariantCulture);
        XmlWriterSettings xmlWriterSettings = new XmlWriterSettings();
        xmlWriterSettings.OmitXmlDeclaration = true;
        if ((o & SaveOptions.DisableFormatting) == 0)
        {
            xmlWriterSettings.Indent = true;
        }
        if ((o & SaveOptions.OmitDuplicateNamespaces) != 0)
        {
            xmlWriterSettings.NamespaceHandling |= NamespaceHandling.OmitDuplicates;
        }
        if (this is XText)
        {
            xmlWriterSettings.ConformanceLevel = ConformanceLevel.Fragment;
        }
        using (XmlWriter writer = XmlWriter.Create(stringWriter, xmlWriterSettings))
        {
            if (this is XDocument xDocument)
            {
                xDocument.WriteContentTo(writer);
            }
            else
            {
                WriteTo(writer);
            }
        }
        return stringWriter.ToString();
    }
References System.Xml.XmlWriter.Create(), System.Xml.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.writer, and System.Xml.Linq.XNode.WriteTo().
Referenced by System.Xml.Linq.XNode.ToString(), and System.Xml.Linq.XNode.ToString().