Terraria: System.Xml.Linq.XNode.GetXmlReaderSettings
GetXmlReaderSettings()
static XmlReaderSettings System.Xml.Linq.XNode.GetXmlReaderSettings (LoadOptions o) inline static package inherited
Definition at line 500 of file XNode.cs.
    {
        XmlReaderSettings xmlReaderSettings = new XmlReaderSettings();
        if ((o & LoadOptions.PreserveWhitespace) == 0)
        {
            xmlReaderSettings.IgnoreWhitespace = true;
        }
        xmlReaderSettings.DtdProcessing = DtdProcessing.Parse;
        xmlReaderSettings.MaxCharactersFromEntities = 10000000L;
        return xmlReaderSettings;
    }
References System.Xml.Dictionary, and System.Xml.L.
Referenced by System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XElement.Load(), System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XElement.Load(), System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XElement.Load(), System.Xml.Linq.XDocument.LoadAsync(), System.Xml.Linq.XElement.LoadAsync(), System.Xml.Linq.XDocument.LoadAsync(), System.Xml.Linq.XElement.LoadAsync(), System.Xml.Linq.XDocument.Parse(), and System.Xml.Linq.XElement.Parse().