Terraria: System.Xml.Linq.XNode.GetXmlWriterSettings
GetXmlWriterSettings()
static XmlWriterSettings System.Xml.Linq.XNode.GetXmlWriterSettings (SaveOptions o) inline static package inherited
Definition at line 512 of file XNode.cs.
    {
        XmlWriterSettings xmlWriterSettings = new XmlWriterSettings();
        if ((o & SaveOptions.DisableFormatting) == 0)
        {
            xmlWriterSettings.Indent = true;
        }
        if ((o & SaveOptions.OmitDuplicateNamespaces) != 0)
        {
            xmlWriterSettings.NamespaceHandling |= NamespaceHandling.OmitDuplicates;
        }
        return xmlWriterSettings;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.Linq.XDocument.Save(), System.Xml.Linq.XElement.Save(), System.Xml.Linq.XStreamingElement.Save(), System.Xml.Linq.XDocument.Save(), System.Xml.Linq.XElement.Save(), System.Xml.Linq.XStreamingElement.Save(), System.Xml.Linq.XDocument.Save(), System.Xml.Linq.XElement.Save(), System.Xml.Linq.XStreamingElement.Save(), System.Xml.Linq.XDocument.SaveAsync(), System.Xml.Linq.XElement.SaveAsync(), System.Xml.Linq.XDocument.SaveAsync(), and System.Xml.Linq.XElement.SaveAsync().