Terraria: System.Xml.Linq.XNode.CompareDocumentOrder
CompareDocumentOrder()
static int System.Xml.Linq.XNode.CompareDocumentOrder (XNode? n1, XNode? n2) inline static inherited
Definition at line 128 of file XNode.cs.
    {
        if (n1 == n2)
        {
            return 0;
        }
        if (n1 == null)
        {
            return -1;
        }
        if (n2 == null)
        {
            return 1;
        }
        if (n1.parent != n2.parent)
        {
            int num = 0;
            XNode xNode = n1;
            while (xNode.parent != null)
            {
                xNode = xNode.parent;
                num++;
            }
            XNode xNode2 = n2;
            while (xNode2.parent != null)
            {
                xNode2 = xNode2.parent;
                num--;
            }
            if (xNode != xNode2)
            {
                throw new InvalidOperationException(System.SR.InvalidOperation_MissingAncestor);
            }
            if (num < 0)
            {
                do
                {
                    n2 = n2.parent;
                    num++;
                }
                while (num != 0);
                if (n1 == n2)
                {
                    return -1;
                }
            }
            else if (num > 0)
            {
                do
                {
                    n1 = n1.parent;
                    num--;
                }
                while (num != 0);
                if (n1 == n2)
                {
                    return 1;
                }
            }
            while (n1.parent != n2.parent)
            {
                n1 = n1.parent;
                n2 = n2.parent;
            }
        }
        else if (n1.parent == null)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_MissingAncestor);
        }
        XNode xNode3 = (XNode)n1.parent.content;
        do
        {
            xNode3 = xNode3.next;
            if (xNode3 == n1)
            {
                return -1;
            }
        }
        while (xNode3 != n2);
        return 1;
    }
References System.Xml.Linq.XNode.XNode(), System.Xml.Dictionary, and System.SR.InvalidOperation_MissingAncestor.
Referenced by System.Xml.Linq.XNodeDocumentOrderComparer.Compare(), System.Xml.Linq.XNode.IsAfter(), and System.Xml.Linq.XNode.IsBefore().