Terraria: System.Xml.Linq.XNode.ReplaceWith
ReplaceWith() [1/2]
void System.Xml.Linq.XNode.ReplaceWith (object? content) inline inherited
Definition at line 387 of file XNode.cs.
    {
        if (parent == null)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_MissingParent);
        }
        XContainer xContainer = parent;
        XNode xNode = (XNode)parent.content;
        while (xNode.next != this)
        {
            xNode = xNode.next;
        }
        if (xNode == parent.content)
        {
            xNode = null;
        }
        parent.RemoveNode(this);
        if (xNode != null && xNode.parent != xContainer)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_ExternalCode);
        }
        new Inserter(xContainer, xNode).Add(content);
    }
References System.Xml.Linq.XNode.XNode(), System.Xml.Linq.Inserter.Add(), System.Xml.Linq.XContainer.content, System.SR.InvalidOperation_ExternalCode, System.SR.InvalidOperation_MissingParent, System.Xml.Linq.XObject.parent, and System.Xml.Linq.XContainer.RemoveNode().
Referenced by System.Xml.Linq.XNode.ReplaceWith().