Terraria: System.Xml.Linq.XNode.AddBeforeSelf
AddBeforeSelf() [1/2]
void System.Xml.Linq.XNode.AddBeforeSelf (object? content) inline inherited
Definition at line 91 of file XNode.cs.
    {
        if (parent == null)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_MissingParent);
        }
        XNode xNode = (XNode)parent.content;
        while (xNode.next != this)
        {
            xNode = xNode.next;
        }
        if (xNode == parent.content)
        {
            xNode = null;
        }
        new Inserter(parent, xNode).Add(content);
    }
References System.Xml.Linq.XNode.XNode(), System.Xml.Linq.Inserter.Add(), System.Xml.Linq.XContainer.content, System.SR.InvalidOperation_MissingParent, and System.Xml.Linq.XObject.parent.
Referenced by System.Xml.Linq.XNode.AddBeforeSelf().