Terraria: System.Xml.Linq.XNode.ReadFromAsyncInternal
ReadFromAsyncInternal()
static async Task< XNode > System.Xml.Linq.XNode.ReadFromAsyncInternal (XmlReader reader, CancellationToken cancellationToken) inline static private inherited
Definition at line 332 of file XNode.cs.
    {
        if (reader.ReadState != ReadState.Interactive)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_ExpectedInteractive);
        }
        XNode ret;
        switch (reader.NodeType)
        {
        case XmlNodeType.Text:
        case XmlNodeType.Whitespace:
        case XmlNodeType.SignificantWhitespace:
            ret = new XText(reader.Value);
            break;
        case XmlNodeType.CDATA:
            ret = new XCData(reader.Value);
            break;
        case XmlNodeType.Comment:
            ret = new XComment(reader.Value);
            break;
        case XmlNodeType.DocumentType:
        {
            string name2 = reader.Name;
            string attribute = reader.GetAttribute("PUBLIC");
            string attribute2 = reader.GetAttribute("SYSTEM");
            string value2 = reader.Value;
            ret = new XDocumentType(name2, attribute, attribute2, value2);
            break;
        }
        case XmlNodeType.Element:
            return await XElement.CreateAsync(reader, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        case XmlNodeType.ProcessingInstruction:
        {
            string name = reader.Name;
            string value = reader.Value;
            ret = new XProcessingInstruction(name, value);
            break;
        }
        default:
            throw new InvalidOperationException(System.SR.Format(System.SR.InvalidOperation_UnexpectedNodeType, reader.NodeType));
        }
        cancellationToken.ThrowIfCancellationRequested();
        await reader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
        return ret;
    }
References System.cancellationToken, System.Xml.Linq.XElement.CreateAsync(), System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlReader.GetAttribute(), System.SR.InvalidOperation_ExpectedInteractive, System.SR.InvalidOperation_UnexpectedNodeType, System.Xml.XmlReader.Name, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadAsync(), System.Xml.XmlReader.ReadState, System.value, and System.Xml.XmlReader.Value.
Referenced by System.Xml.Linq.XNode.ReadFromAsync().