Terraria: System.Net.Mime.ByteEncoder.EncodeBytes
EncodeBytes()
int System.Net.Mime.ByteEncoder.EncodeBytes (byte[] buffer, int offset, int count, bool dontDeferFinalBytes, bool shouldAppendSpaceToCRLF) inline inherited
Implements System.Net.Mime.IByteEncoder.
Definition at line 16 of file ByteEncoder.cs.
    {
        WriteState.AppendHeader();
        bool hasSpecialEncodingForCRLF = HasSpecialEncodingForCRLF;
        int i;
        for (i = offset; i < count + offset; i++)
        {
            if (LineBreakNeeded(buffer[i]))
            {
                AppendPadding();
                WriteState.AppendCRLF(shouldAppendSpaceToCRLF);
            }
            if (hasSpecialEncodingForCRLF && IsCRLF(buffer, i, count + offset))
            {
                AppendEncodedCRLF();
                i++;
            }
            else
            {
                ApppendEncodedByte(buffer[i]);
            }
        }
        if (dontDeferFinalBytes)
        {
            AppendPadding();
        }
        WriteState.AppendFooter();
        return i - offset;
    }
References System.Net.Mime.ByteEncoder.AppendEncodedCRLF(), System.Net.Mime.ByteEncoder.AppendPadding(), System.Net.Mime.ByteEncoder.ApppendEncodedByte(), System.buffer, System.count, System.Net.Mime.ByteEncoder.HasSpecialEncodingForCRLF, System.Net.Mime.ByteEncoder.IsCRLF(), System.Net.Mime.ByteEncoder.LineBreakNeeded(), and System.offset.
Referenced by System.Net.Mime.ByteEncoder.EncodeString().