Terraria: System.Net.ListenerAsyncResult.IOCompleted
IOCompleted()
static unsafe void System.Net.ListenerAsyncResult.IOCompleted (ListenerAsyncResult asyncResult, uint errorCode, uint numBytes) inline static private
Definition at line 19 of file ListenerAsyncResult.cs.
    {
        object obj = null;
        try
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(null, $"errorCode:[{errorCode}] numBytes:[{numBytes}]", "IOCompleted");
            }
            if (errorCode != 0 && errorCode != 234)
            {
                asyncResult.ErrorCode = (int)errorCode;
                obj = new HttpListenerException((int)errorCode);
            }
            else
            {
                HttpListenerSession httpListenerSession = asyncResult.AsyncObject as HttpListenerSession;
                if (errorCode == 0)
                {
                    bool stoleBlob = false;
                    try
                    {
                        if (HttpListener.ValidateRequest(httpListenerSession, asyncResult._requestContext))
{
                            obj = httpListenerSession.Listener.HandleAuthentication(httpListenerSession, asyncResult._requestContext, out stoleBlob);
                        }
                    }
                    finally
                    {
                        if (stoleBlob)
{
                            asyncResult._requestContext = ((obj == null) ? new AsyncRequestContext(httpListenerSession.RequestQueueBoundHandle, asyncResult) : null);
                        }
                        else
{
                            asyncResult._requestContext.Reset(httpListenerSession.RequestQueueBoundHandle, 0uL, 0u);
                        }
                    }
                }
                else
                {
                    asyncResult._requestContext.Reset(httpListenerSession.RequestQueueBoundHandle, asyncResult._requestContext.RequestBlob->RequestId, numBytes);
                }
                if (obj == null)
                {
                    uint num = asyncResult.QueueBeginGetContext();
                    if (num != 0 && num != 997)
                    {
                        obj = new HttpListenerException((int)num);
                    }
                }
                if (obj == null)
                {
                    return;
                }
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(null, "Calling Complete()", "IOCompleted");
            }
        }
        catch (Exception ex) when (!System.Net.ExceptionCheck.IsFatal(ex))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(null, $"Caught exception: {ex}", "IOCompleted");
            }
            obj = ex;
        }
        asyncResult.InvokeCallback(obj);
    }
References System.asyncResult, System.Net.HttpListener.HandleAuthentication(), System.Net.NetEventSource.Info(), System.Net.ExceptionCheck.IsFatal(), System.Net.HttpListenerSession.Listener, System.Net.NetEventSource.Log, System.obj, System.Net.HttpListenerSession.RequestQueueBoundHandle, and System.Net.HttpListener.ValidateRequest().
Referenced by System.Net.ListenerAsyncResult.QueueBeginGetContext(), and System.Net.ListenerAsyncResult.WaitCallback().