Terraria: System.Net.Http.Headers.StringWithQualityHeaderValue.StringWithQualityHeaderValue
StringWithQualityHeaderValue() [1/3]
System.Net.Http.Headers.StringWithQualityHeaderValue.StringWithQualityHeaderValue (string value) inline
Definition at line 17 of file StringWithQualityHeaderValue.cs.
    {
        HeaderUtilities.CheckValidToken(value, "value");
        _value = value;
    }
References System.Net.Http.Headers.StringWithQualityHeaderValue._value, System.Net.Http.Headers.HeaderUtilities.CheckValidToken(), and System.value.
Referenced by System.Net.Http.Headers.StringWithQualityHeaderValue.Clone(), System.Net.Http.Headers.StringWithQualityHeaderValue.GetStringWithQualityLength(), and System.Net.Http.Headers.StringWithQualityHeaderValue.TryParse().