Terraria: System.Reflection.RtFieldInfo.SetValue
SetValue() [1/3]
override void System.Reflection.RtFieldInfo.SetValue (object obj, object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture) inline
Definition at line 158 of file RtFieldInfo.cs.
    {
        INVOCATION_FLAGS invocationFlags = InvocationFlags;
        RuntimeType runtimeType = DeclaringType as RuntimeType;
        if ((invocationFlags & INVOCATION_FLAGS.INVOCATION_FLAGS_NO_INVOKE) != 0)
        {
            if (runtimeType != null && runtimeType.ContainsGenericParameters)
            {
                throw new InvalidOperationException(SR.Arg_UnboundGenField);
            }
            throw new FieldAccessException();
        }
        CheckConsistency(obj);
        RuntimeType runtimeType2 = (RuntimeType)FieldType;
        value = runtimeType2.CheckValue(value, binder, culture, invokeAttr);
        bool domainInitialized = false;
        if (runtimeType == null)
        {
            RuntimeFieldHandle.SetValue(this, obj, value, runtimeType2, m_fieldAttributes, null, ref domainInitialized);
            return;
        }
        domainInitialized = runtimeType.DomainInitialized;
        RuntimeFieldHandle.SetValue(this, obj, value, runtimeType2, m_fieldAttributes, runtimeType, ref domainInitialized);
        runtimeType.DomainInitialized = domainInitialized;
    }
References System.SR.Arg_UnboundGenField, System.Reflection.RtFieldInfo.CheckConsistency(), System.RuntimeType.CheckValue(), System.RuntimeType.ContainsGenericParameters, System.culture, System.Reflection.RuntimeFieldInfo.DeclaringType, System.RuntimeType.DomainInitialized, System.Reflection.RtFieldInfo.FieldType, System.Reflection.RtFieldInfo.InvocationFlags, System.Reflection.RtFieldInfo.m_fieldAttributes, System.obj, System.RuntimeFieldHandle.SetValue(), and System.value.