Terraria: System.Runtime.CompilerServices.ConditionalWeakTable.Enumerator.Dispose
Dispose()
void System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Enumerator.Dispose () inline
Implements System.IDisposable.
Definition at line 50 of file ConditionalWeakTable.cs.
        {
            ConditionalWeakTable<TKey, TValue> conditionalWeakTable = Interlocked.Exchange(ref _table, null);
            if (conditionalWeakTable != null)
            {
                _current = default(KeyValuePair<TKey, TValue>);
                lock (conditionalWeakTable._lock)
                {
                    conditionalWeakTable._activeEnumeratorRefCount--;
                }
                GC.SuppressFinalize(this);
            }
        }
References System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Enumerator._current, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Enumerator._table, System.Threading.Interlocked.Exchange(), and System.GC.SuppressFinalize().
Referenced by System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Enumerator.~Enumerator().