Terraria: System.Net.Http.Headers.StringWithQualityHeaderValue.GetStringWithQualityLength
GetStringWithQualityLength()
static int System.Net.Http.Headers.StringWithQualityHeaderValue.GetStringWithQualityLength (string input, int startIndex, out object parsedValue) inline static package
Definition at line 105 of file StringWithQualityHeaderValue.cs.
    {
        parsedValue = null;
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        int tokenLength = HttpRuleParser.GetTokenLength(input, startIndex);
        if (tokenLength == 0)
        {
            return 0;
        }
        string value = input.Substring(startIndex, tokenLength);
        int num = startIndex + tokenLength;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        if (num == input.Length || input[num] != ';')
        {
            parsedValue = new StringWithQualityHeaderValue(value);
            return num - startIndex;
        }
        num++;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        if (!TryReadQuality(input, out var quality, ref num))
        {
            return 0;
        }
        parsedValue = new StringWithQualityHeaderValue(value, quality);
        return num - startIndex;
    }
References System.Net.Http.Headers.StringWithQualityHeaderValue.StringWithQualityHeaderValue(), System.Net.Http.HttpRuleParser.GetTokenLength(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), System.input, System.startIndex, System.Net.Http.Headers.StringWithQualityHeaderValue.TryReadQuality(), and System.value.