Terraria: System.Net.Http.Headers.StringWithQualityHeaderValue.TryReadQuality
TryReadQuality()
static bool System.Net.Http.Headers.StringWithQualityHeaderValue.TryReadQuality (string input, out double quality, ref int index) inline static private
Definition at line 135 of file StringWithQualityHeaderValue.cs.
    {
        int num = index;
        quality = 0.0;
        if (num == input.Length || (input[num] != 'q' && input[num] != 'Q'))
        {
            return false;
        }
        num++;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        if (num == input.Length || input[num] != '=')
        {
            return false;
        }
        num++;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        if (num == input.Length)
        {
            return false;
        }
        int numberLength = HttpRuleParser.GetNumberLength(input, num, allowDecimal: true);
        if (numberLength == 0)
        {
            return false;
        }
        if (!double.TryParse(input.AsSpan(num, numberLength), NumberStyles.AllowDecimalPoint, NumberFormatInfo.InvariantInfo, out quality))
        {
            return false;
        }
        if (quality < 0.0 || quality > 1.0)
        {
            return false;
        }
        num += numberLength;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        index = num;
        return true;
    }
References System.Net.Http.HttpRuleParser.GetNumberLength(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), System.index, System.input, System.Globalization.NumberFormatInfo.InvariantInfo, and System.Net.Http.Headers.StringWithQualityHeaderValue.TryParse().
Referenced by System.Net.Http.Headers.StringWithQualityHeaderValue.GetStringWithQualityLength().