Terraria: Terraria.GameContent.Skies.AmbientSky.SkyEntity.CommonDraw
CommonDraw()
void Terraria.GameContent.Skies.AmbientSky.SkyEntity.CommonDraw (SpriteBatch spriteBatch, float depthScale, float minDepth, float maxDepth) inline inherited
Definition at line 59 of file AmbientSky.cs.
        {
            if (!(Depth <= minDepth) && !(Depth > maxDepth))
            {
                Vector2 drawPositionByDepth = GetDrawPositionByDepth();
                Color color = GetColor(Main.ColorOfTheSkies) * Main.atmo;
                Vector2 origin = SourceRectangle.Size() / 2f;
                float scale = depthScale / Depth;
                spriteBatch.Draw(Texture.Value, drawPositionByDepth - Main.Camera.UnscaledPosition, SourceRectangle, color, Rotation, origin, scale, Effects, 0f);
            }
        }
References Terraria.Main.atmo, Terraria.Main.Camera, Terraria.Main.ColorOfTheSkies, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Depth, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.GetColor(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.GetDrawPositionByDepth(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.Rotation, and Terraria.GameContent.Skies.AmbientSky.SkyEntity.SourceRectangle.
Referenced by Terraria.GameContent.Skies.AmbientSky.SkyEntity.Draw(), Terraria.GameContent.Skies.AmbientSky.PixiePosseSkyEntity.Draw(), Terraria.GameContent.Skies.AmbientSky.SeagullsGroupSkyEntity.Draw(), and Terraria.GameContent.Skies.AmbientSky.GastropodGroupSkyEntity.Draw().