Terraria: Terraria.GameContent.Skies.AmbientSky.SkyEntity.Helper_GetOpacityWithAccountingForOceanWaterLine
Helper_GetOpacityWithAccountingForOceanWaterLine()
float Terraria.GameContent.Skies.AmbientSky.SkyEntity.Helper_GetOpacityWithAccountingForOceanWaterLine () inline package inherited
Definition at line 76 of file AmbientSky.cs.
        {
            Vector2 vector = GetDrawPositionByDepth() - Main.Camera.UnscaledPosition;
            int num = SourceRectangle.Height / 2;
            float t = vector.Y + (float)num;
            float yScreenPosition = AmbientSkyDrawCache.Instance.OceanLineInfo.YScreenPosition;
            float lerpValue = Utils.GetLerpValue(yScreenPosition - 10f, yScreenPosition - 2f, t, clamped: true);
            lerpValue *= AmbientSkyDrawCache.Instance.OceanLineInfo.OceanOpacity;
            return 1f - lerpValue;
        }
References Terraria.Main.Camera, Terraria.GameContent.Skies.AmbientSky.SkyEntity.GetDrawPositionByDepth(), Terraria.Utils.GetLerpValue(), and Terraria.GameContent.Ambience.AmbientSkyDrawCache.Instance.
Referenced by Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.GetColor().