Terraria: System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.ProcessAction_IndicateReceiveComplete
ProcessAction_IndicateReceiveComplete()
override void System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.ProcessAction_IndicateReceiveComplete (ArraySegment< byte >? buffer, WebSocketProtocolComponent::BufferType bufferType, WebSocketProtocolComponent::Action action, global::Interop::WebSocket::Buffer[] dataBuffers, uint dataBufferCount, IntPtr actionContext) inline protected virtual
Reimplemented from System.Net.WebSockets.WebSocketBase.WebSocketOperation.
Definition at line 92 of file WebSocketBase.cs.
            {
                int num = 0;
                _pongReceived = false;
                if (bufferType == WebSocketProtocolComponent.BufferType.PingPong)
                {
                    _pongReceived = true;
                    WebSocketProtocolComponent.WebSocketCompleteAction(_webSocket, actionContext, num);
                    return;
                }
                WebSocketReceiveResult receiveResult;
                try
                {
                    WebSocketMessageType messageType = GetMessageType(bufferType);
                    int newReceiveState = 0;
                    if (bufferType == WebSocketProtocolComponent.BufferType.Close)
                    {
                        ArraySegment<byte> empty = ArraySegment<byte>.Empty;
                        _webSocket._internalBuffer.ConvertCloseBuffer(action, dataBuffers[0], out var closeStatus, out var reason);
                        receiveResult = new WebSocketReceiveResult(num, messageType, endOfMessage: true, closeStatus, reason);
                    }
                    else
                    {
                        ArraySegment<byte> empty = _webSocket._internalBuffer.ConvertNativeBuffer(action, dataBuffers[0], bufferType);
                        bool endOfMessage = bufferType == WebSocketProtocolComponent.BufferType.BinaryMessage || bufferType == WebSocketProtocolComponent.BufferType.UTF8Message || bufferType == WebSocketProtocolComponent.BufferType.Close;
                        if (empty.Count > buffer.Value.Count)
{
                            _webSocket._internalBuffer.BufferPayload(empty, buffer.Value.Count, messageType, endOfMessage);
                            newReceiveState = 2;
                            endOfMessage = false;
                        }
                        num = Math.Min(empty.Count, buffer.Value.Count);
                        if (num > 0)
{
                            Buffer.BlockCopy(empty.Array, empty.Offset, buffer.Value.Array, buffer.Value.Offset, num);
                        }
                        receiveResult = new WebSocketReceiveResult(num, messageType, endOfMessage);
                    }
                    _webSocket.UpdateReceiveState(newReceiveState, _receiveState);
                }
                finally
                {
                    WebSocketProtocolComponent.WebSocketCompleteAction(_webSocket, actionContext, num);
                }
                base.ReceiveResult = receiveResult;
            }
References System.Net.WebSockets.WebSocketBase._internalBuffer, System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation._pongReceived, System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation._receiveState, System.Net.WebSockets.WebSocketBase.WebSocketOperation._webSocket, System.action, System.Buffer.BlockCopy(), System.buffer, System.Net.WebSockets.WebSocketBuffer.BufferPayload(), System.Net.WebSockets.WebSocketBuffer.ConvertCloseBuffer(), System.Net.WebSockets.WebSocketBuffer.ConvertNativeBuffer(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.WebSockets.WebSocketBase.GetMessageType(), System.Math.Min(), System.Net.WebSockets.WebSocketBase.UpdateReceiveState(), and System.Net.WebSockets.WebSocketProtocolComponent.WebSocketCompleteAction().