Terraria: System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.Initialize
Initialize()
override void System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.Initialize (ArraySegment< byte >? buffer, CancellationToken cancellationToken) inline protected
Definition at line 34 of file WebSocketBase.cs.
            {
                _pongReceived = false;
                _receiveCompleted = false;
                _webSocket.ThrowIfDisposed();
                switch (Interlocked.CompareExchange(ref _webSocket._receiveState, 1, 0))
                {
                case 0:
                    _receiveState = 1;
                    break;
                case 2:
                {
                    if (!_webSocket._internalBuffer.ReceiveFromBufferedPayload(buffer.Value, out var receiveResult))
                    {
                        _webSocket.UpdateReceiveState(0, 2);
                    }
                    base.ReceiveResult = receiveResult;
                    _receiveCompleted = true;
                    break;
                }
                case 1:
                    break;
                }
            }
References System.Net.WebSockets.WebSocketBase._internalBuffer, System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation._pongReceived, System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation._receiveCompleted, System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation._receiveState, System.Net.WebSockets.WebSocketBase._receiveState, System.Net.WebSockets.WebSocketBase.WebSocketOperation._webSocket, System.buffer, System.Threading.Interlocked.CompareExchange(), System.Net.WebSockets.WebSocketBuffer.ReceiveFromBufferedPayload(), System.Net.WebSockets.WebSocketBase.ThrowIfDisposed(), and System.Net.WebSockets.WebSocketBase.UpdateReceiveState().