Terraria: Collision.GetTilesIn
GetTilesIn()
static List<Point> Collision.GetTilesIn (Vector2 TopLeft, Vector2 BottomRight) inline static
     {
         List<Point> list = new List<Point>();
         Point point = TopLeft.ToTileCoordinates();
         Point point2 = BottomRight.ToTileCoordinates();
         int num = Utils.Clamp(point.X, 0, Main.maxTilesX - 1);
         int num2 = Utils.Clamp(point.Y, 0, Main.maxTilesY - 1);
         int num3 = Utils.Clamp(point2.X, 0, Main.maxTilesX - 1);
         int num4 = Utils.Clamp(point2.Y, 0, Main.maxTilesY - 1);
         for (int i = num; i <= num3; i++)
         {
             for (int j = num2; j <= num4; j++)
             {
                 if (Main.tile[i, j] != null)
                 {
                     list.Add(new Point(i, j));
                 }
             }
         }
         return list;
     }
References Main.maxTilesX, Main.maxTilesY, and Main.tile.
Referenced by Player.QuickMinecart(), Player.QuickMinecartSnap(), WindGrid.ScanPlayer(), and PressurePlateHelper.UpdatePlayerPosition().