Terraria: Collision.StepConveyorBelt
StepConveyorBelt()
static void Collision.StepConveyorBelt (Entity entity, float gravDir) inline static
     {
         Player player = null;
         if (entity is Player)
         {
             player = (Player)entity;
             if (Math.Abs(player.gfxOffY) > 2f || player.grapCount > 0 || player.pulley)
             {
                 return;
             }
             entity.height -= 5;
             entity.position.Y += 5f;
         }
         int num = 0;
         int num2 = 0;
         bool flag = false;
         int num3 = (int)entity.position.Y + entity.height;
         entity.Hitbox.Inflate(2, 2);
         _ = entity.TopLeft;
         _ = entity.TopRight;
         _ = entity.BottomLeft;
         _ = entity.BottomRight;
         List<Point> cacheForConveyorBelts = _cacheForConveyorBelts;
         cacheForConveyorBelts.Clear();
         GetEntityEdgeTiles(cacheForConveyorBelts, entity, left: false, right: false);
         Vector2 vector = new Vector2(0.0001f);
         Vector2 lineStart = default(Vector2);
         Vector2 lineStart2 = default(Vector2);
         Vector2 lineEnd = default(Vector2);
         Vector2 lineEnd2 = default(Vector2);
         for (int i = 0; i < cacheForConveyorBelts.Count; i++)
         {
             Point point = cacheForConveyorBelts[i];
             if (!WorldGen.InWorld(point.X, point.Y) || (player != null && player.onTrack && point.Y < num3))
             {
                 continue;
             }
             Tile tile = Main.tile[point.X, point.Y];
             if (tile == null || !tile.active() || !tile.nactive())
             {
                 continue;
             }
             int num4 = TileID.Sets.ConveyorDirection[tile.type];
             if (num4 == 0)
             {
                 continue;
             }
             lineStart.X = (lineStart2.X = point.X * 16);
             lineEnd.X = (lineEnd2.X = point.X * 16 + 16);
             switch (tile.slope())
             {
             case 1:
                 lineStart2.Y = point.Y * 16;
                 lineEnd2.Y = (lineEnd.Y = (lineStart.Y = point.Y * 16 + 16));
                 break;
             case 2:
                 lineEnd2.Y = point.Y * 16;
                 lineStart2.Y = (lineEnd.Y = (lineStart.Y = point.Y * 16 + 16));
                 break;
             case 3:
                 lineEnd.Y = (lineStart2.Y = (lineEnd2.Y = point.Y * 16));
                 lineStart.Y = point.Y * 16 + 16;
                 break;
             case 4:
                 lineStart.Y = (lineStart2.Y = (lineEnd2.Y = point.Y * 16));
                 lineEnd.Y = point.Y * 16 + 16;
                 break;
             default:
                 if (tile.halfBrick())
                 {
                     lineStart2.Y = (lineEnd2.Y = point.Y * 16 + 8);
                 }
                 else
                 {
                     lineStart2.Y = (lineEnd2.Y = point.Y * 16);
                 }
                 lineStart.Y = (lineEnd.Y = point.Y * 16 + 16);
                 break;
             }
             int num5 = 0;
             if (!TileID.Sets.Platforms[tile.type] && CheckAABBvLineCollision2(entity.position - vector, entity.Size + vector * 2f, lineStart, lineEnd))
             {
                 num5--;
             }
             if (CheckAABBvLineCollision2(entity.position - vector, entity.Size + vector * 2f, lineStart2, lineEnd2))
             {
                 num5++;
             }
             if (num5 != 0)
             {
                 flag = true;
                 num += num4 * num5 * (int)gravDir;
                 if (tile.leftSlope())
                 {
                     num2 += (int)gravDir * -num4;
                 }
                 if (tile.rightSlope())
                 {
                     num2 -= (int)gravDir * -num4;
                 }
             }
         }
         if (entity is Player)
         {
             entity.height += 5;
             entity.position.Y -= 5f;
         }
         if (flag && num != 0)
         {
             num = Math.Sign(num);
             num2 = Math.Sign(num2);
             Vector2 velocity = Vector2.Normalize(new Vector2((float)num * gravDir, num2)) * 2.5f;
             Vector2 vector2 = TileCollision(entity.position, velocity, entity.width, entity.height, fallThrough: false, fall2: false, (int)gravDir);
             entity.position += vector2;
             vector2 = TileCollision(Velocity: new Vector2(0f, 2.5f * gravDir), Position: entity.position, Width: entity.width, Height: entity.height, fallThrough: false, fall2: false, gravDir: (int)gravDir);
             entity.position += vector2;
         }
     }
References _cacheForConveyorBelts, Tile.active(), Entity.BottomLeft, Entity.BottomRight, CheckAABBvLineCollision2(), TileID.Sets.ConveyorDirection, GetEntityEdgeTiles(), Player.gfxOffY, Player.grapCount, Tile.halfBrick(), Entity.height, Entity.Hitbox, WorldGen.InWorld(), Tile.leftSlope(), Tile.nactive(), Player.onTrack, TileID.Sets.Platforms, Player, Entity.position, Player.pulley, Tile.rightSlope(), Entity.Size, Tile.slope(), Main.tile, TileCollision(), Entity.TopLeft, Entity.TopRight, Tile.type, and Entity.width.
Referenced by Player.DryCollision(), Item.MoveInWorld(), Player.Update(), and NPC.UpdateCollision().