Terraria: System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.OnEventCommand
OnEventCommand()
void System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.OnEventCommand (EventCommandEventArgs command) inline
Definition at line 30 of file MetricsEventSource.cs.
        {
            try
            {
                if (OperatingSystem.IsBrowser())
                {
                    Log.Error("", "System.Diagnostics.Metrics EventSource not supported on browser");
                    return;
                }
                if (command.Command == EventCommand.Update || command.Command == EventCommand.Disable || command.Command == EventCommand.Enable)
                {
                    if (_aggregationManager != null)
                    {
                        if (command.Command == EventCommand.Enable || command.Command == EventCommand.Update)
{
                            Log.MultipleSessionsNotSupportedError(_sessionId);
                            return;
                        }
                        _aggregationManager.Dispose();
                        _aggregationManager = null;
                        Log.Message("Previous session with id " + _sessionId + " is stopped");
                    }
                    _sessionId = "";
                }
                if ((command.Command != 0 && command.Command != EventCommand.Enable) || command.Arguments == null)
                {
                    return;
                }
                if (command.Arguments.TryGetValue("SessionId", out string value))
                {
                    _sessionId = value;
                    Log.Message("SessionId argument received: " + _sessionId);
                }
                else
                {
                    _sessionId = Guid.NewGuid().ToString();
                    Log.Message("New session started. SessionId auto-generated: " + _sessionId);
                }
                double num = 1.0;
                double result = num;
                if (command.Arguments.TryGetValue("RefreshInterval", out string value2))
                {
                    Log.Message("RefreshInterval argument received: " + value2);
                    if (!double.TryParse(value2, out result))
                    {
                        Log.Message($"Failed to parse RefreshInterval. Using default {num}s.");
                        result = num;
                    }
                    else if (result < 0.1)
                    {
                        Log.Message($"RefreshInterval too small. Using minimum interval {0.1} seconds.");
                        result = 0.1;
                    }
                }
                else
                {
                    Log.Message($"No RefreshInterval argument received. Using default {num}s.");
                    result = num;
                }
                int num2 = 1000;
                int result2;
                if (command.Arguments.TryGetValue("MaxTimeSeries", out string value3))
                {
                    Log.Message("MaxTimeSeries argument received: " + value3);
                    if (!int.TryParse(value3, out result2))
                    {
                        Log.Message($"Failed to parse MaxTimeSeries. Using default {num2}");
                        result2 = num2;
                    }
                }
                else
                {
                    Log.Message($"No MaxTimeSeries argument received. Using default {num2}");
                    result2 = num2;
                }
                int num3 = 20;
                int result3;
                if (command.Arguments.TryGetValue("MaxHistograms", out string value4))
                {
                    Log.Message("MaxHistograms argument received: " + value4);
                    if (!int.TryParse(value4, out result3))
                    {
                        Log.Message($"Failed to parse MaxHistograms. Using default {num3}");
                        result3 = num3;
                    }
                }
                else
                {
                    Log.Message($"No MaxHistogram argument received. Using default {num3}");
                    result3 = num3;
                }
                string sessionId = _sessionId;
                _aggregationManager = new AggregationManager(result2, result3, delegate(Instrument i, LabeledAggregationStatistics s)
                {
                    TransmitMetricValue(i, s, sessionId);
                }, delegate(DateTime startIntervalTime, DateTime endIntervalTime)
                {
                    Log.CollectionStart(sessionId, startIntervalTime, endIntervalTime);
                }, delegate(DateTime startIntervalTime, DateTime endIntervalTime)
                {
                    Log.CollectionStop(sessionId, startIntervalTime, endIntervalTime);
                }, delegate(Instrument i)
                {
                    Log.BeginInstrumentReporting(sessionId, i.Meter.Name, i.Meter.Version, i.Name, i.GetType().Name, i.Unit, i.Description);
                }, delegate(Instrument i)
                {
                    Log.EndInstrumentReporting(sessionId, i.Meter.Name, i.Meter.Version, i.Name, i.GetType().Name, i.Unit, i.Description);
                }, delegate(Instrument i)
                {
                    Log.InstrumentPublished(sessionId, i.Meter.Name, i.Meter.Version, i.Name, i.GetType().Name, i.Unit, i.Description);
                }, delegate
                {
                    Log.InitialInstrumentEnumerationComplete(sessionId);
                }, delegate(Exception e)
                {
                    Log.Error(sessionId, e.ToString());
                }, delegate
                {
                    Log.TimeSeriesLimitReached(sessionId);
                }, delegate
                {
                    Log.HistogramLimitReached(sessionId);
                }, delegate(Exception e)
                {
                    Log.ObservableInstrumentCallbackError(sessionId, e.ToString());
                });
                _aggregationManager.SetCollectionPeriod(TimeSpan.FromSeconds(result));
                if (command.Arguments.TryGetValue("Metrics", out string value5))
                {
                    Log.Message("Metrics argument received: " + value5);
                    ParseSpecs(value5);
                }
                else
                {
                    Log.Message("No Metrics argument received");
                }
                _aggregationManager.Start();
            }
            catch (Exception e2) when (LogError(e2))
            {
            }
        }
References System.Diagnostics.Metrics.MetricsEventSource.CommandHandler._aggregationManager, System.Diagnostics.Metrics.MetricsEventSource.CommandHandler._sessionId, System.Diagnostics.Metrics.AggregationManager.Dispose(), System.TimeSpan.FromSeconds(), System.OperatingSystem.IsBrowser(), System.Diagnostics.Metrics.MetricsEventSource.Log, System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.LogError(), System.Guid.NewGuid(), System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.ParseSpecs(), System.s, System.Diagnostics.Metrics.AggregationManager.SetCollectionPeriod(), System.Diagnostics.Metrics.AggregationManager.Start(), System.Exception.ToString(), System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.TransmitMetricValue(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Diagnostics.Metrics.MetricsEventSource.OnEventCommand().