Terraria: Collision.IsWorldPointSolid
IsWorldPointSolid()
static bool Collision.IsWorldPointSolid (Vector2 pos, bool treatPlatformsAsNonSolid = false) inline static
     {
         Point point = pos.ToTileCoordinates();
         if (!WorldGen.InWorld(point.X, point.Y, 1))
         {
             return false;
         }
         Tile tile = Main.tile[point.X, point.Y];
         if (tile == null || !tile.active() || tile.inActive() || !Main.tileSolid[tile.type])
         {
             return false;
         }
         if (treatPlatformsAsNonSolid && tile.type > 0 && tile.type <= TileID.Count && (TileID.Sets.Platforms[tile.type] || tile.type == 380))
         {
             return false;
         }
         int num = tile.blockType();
         switch (num)
         {
         case 0:
             if (pos.X >= (float)(point.X * 16) && pos.X <= (float)(point.X * 16 + 16) && pos.Y >= (float)(point.Y * 16))
             {
                 return pos.Y <= (float)(point.Y * 16 + 16);
             }
             return false;
         case 1:
             if (pos.X >= (float)(point.X * 16) && pos.X <= (float)(point.X * 16 + 16) && pos.Y >= (float)(point.Y * 16 + 8))
             {
                 return pos.Y <= (float)(point.Y * 16 + 16);
             }
             return false;
         case 2:
         case 3:
         case 4:
         case 5:
         {
             if (pos.X < (float)(point.X * 16) && pos.X > (float)(point.X * 16 + 16) && pos.Y < (float)(point.Y * 16) && pos.Y > (float)(point.Y * 16 + 16))
             {
                 return false;
             }
             float num2 = pos.X % 16f;
             float num3 = pos.Y % 16f;
             switch (num)
             {
             case 3:
                 return num2 + num3 >= 16f;
             case 2:
                 return num3 >= num2;
             case 5:
                 return num3 <= num2;
             case 4:
                 return num2 + num3 <= 16f;
             }
             break;
         }
         }
         return false;
     }
References Tile.active(), Tile.blockType(), TileID.Count, Tile.inActive(), WorldGen.InWorld(), TileID.Sets.Platforms, Main.tile, Main.tileSolid, and Tile.type.