Terraria: System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.ParseSpecs
ParseSpecs()
void System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.ParseSpecs (string metricsSpecs) inline private
Definition at line 180 of file MetricsEventSource.cs.
        {
            if (metricsSpecs == null)
            {
                return;
            }
            string[] array = metricsSpecs.Split(s_instrumentSeperators, StringSplitOptions.RemoveEmptyEntries);
            string[] array2 = array;
            foreach (string text in array2)
            {
                if (!MetricSpec.TryParse(text, out var spec))
                {
                    Log.Message("Failed to parse metric spec: {specString}");
                    continue;
                }
                Log.Message("Parsed metric: {spec}");
                if (spec.InstrumentName != null)
                {
                    _aggregationManager.Include(spec.MeterName, spec.InstrumentName);
                }
                else
                {
                    _aggregationManager.Include(spec.MeterName);
                }
            }
        }
References System.Diagnostics.Metrics.MetricsEventSource.CommandHandler._aggregationManager, System.array, System.Diagnostics.Metrics.AggregationManager.Include(), System.Diagnostics.Metrics.MetricsEventSource.Log, System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.s_instrumentSeperators, System.text, and System.Diagnostics.Metrics.MetricsEventSource.MetricSpec.TryParse().
Referenced by System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.OnEventCommand().