Terraria: Collision.CheckLinevLine
CheckLinevLine()
static Vector2 [] Collision.CheckLinevLine (Vector2 a1, Vector2 a2, Vector2 b1, Vector2 b2) inline static
     {
         if (a1.Equals(a2) && b1.Equals(b2))
         {
             if (a1.Equals(b1))
             {
                 return new Vector2[1] { a1 };
             }
             return new Vector2[0];
         }
         if (b1.Equals(b2))
         {
             if (PointOnLine(b1, a1, a2))
             {
                 return new Vector2[1] { b1 };
             }
             return new Vector2[0];
         }
         if (a1.Equals(a2))
         {
             if (PointOnLine(a1, b1, b2))
             {
                 return new Vector2[1] { a1 };
             }
             return new Vector2[0];
         }
         float num = (b2.X - b1.X) * (a1.Y - b1.Y) - (b2.Y - b1.Y) * (a1.X - b1.X);
         float num2 = (a2.X - a1.X) * (a1.Y - b1.Y) - (a2.Y - a1.Y) * (a1.X - b1.X);
         float num3 = (b2.Y - b1.Y) * (a2.X - a1.X) - (b2.X - b1.X) * (a2.Y - a1.Y);
         if (!(0f - Epsilon < num3) || !(num3 < Epsilon))
         {
             float num4 = num / num3;
             float num5 = num2 / num3;
             if (0f <= num4 && num4 <= 1f && 0f <= num5 && num5 <= 1f)
             {
                 return new Vector2[1]
                 {
                     new Vector2(a1.X + num4 * (a2.X - a1.X), a1.Y + num4 * (a2.Y - a1.Y))
                 };
             }
             return new Vector2[0];
         }
         if ((0f - Epsilon < num && num < Epsilon) || (0f - Epsilon < num2 && num2 < Epsilon))
         {
             if (a1.Equals(a2))
             {
                 return OneDimensionalIntersection(b1, b2, a1, a2);
             }
             return OneDimensionalIntersection(a1, a2, b1, b2);
         }
         return new Vector2[0];
     }
References Epsilon, OneDimensionalIntersection(), and PointOnLine().
Referenced by PortalHelper.RemoveIntersectingPortals().