Terraria: Collision.HitWallSubstep
HitWallSubstep()
static bool Collision.HitWallSubstep (int x, int y) inline static
     {
         if (Main.tile[x, y].wall == 0)
         {
             return false;
         }
         bool flag = false;
         if (Main.wallHouse[Main.tile[x, y].wall])
         {
             flag = true;
         }
         if (!flag)
         {
             for (int i = -1; i < 2; i++)
             {
                 for (int j = -1; j < 2; j++)
                 {
                     if ((i != 0 || j != 0) && Main.tile[x + i, y + j].wall == 0)
                     {
                         flag = true;
                     }
                 }
             }
         }
         if (Main.tile[x, y].active() && flag)
         {
             bool flag2 = true;
             for (int k = -1; k < 2; k++)
             {
                 for (int l = -1; l < 2; l++)
                 {
                     if (k != 0 || l != 0)
                     {
                         Tile tile = Main.tile[x + k, y + l];
                         if (!tile.active() || !Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type])
{
                             flag2 = false;
                         }
                     }
                 }
             }
             if (flag2)
             {
                 flag = false;
             }
         }
         return flag;
     }
References Tile.active(), Main.tile, Main.tileSolid, Main.tileSolidTop, Tile.type, Tile.wall, and Main.wallHouse.
Referenced by SmartCursorHelper.Step_Hammers(), and TupleHitLineWall().