Terraria: Collision.DrownCollision
DrownCollision()
static bool Collision.DrownCollision (Vector2 Position, int Width, int Height, float gravDir = -1f, bool includeSlopes = false) inline static
     {
         Vector2 vector = new Vector2(Position.X + (float)(Width / 2), Position.Y + (float)(Height / 2));
         int num = 10;
         int num2 = 12;
         if (num > Width)
         {
             num = Width;
         }
         if (num2 > Height)
         {
             num2 = Height;
         }
         vector = new Vector2(vector.X - (float)(num / 2), Position.Y + -2f);
         if (gravDir == -1f)
         {
             vector.Y += Height / 2 - 6;
         }
         int value = (int)(Position.X / 16f) - 1;
         int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
         int value3 = (int)(Position.Y / 16f) - 1;
         int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
         int num3 = Utils.Clamp(value, 0, Main.maxTilesX - 1);
         value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
         value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
         value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
         int num4 = ((gravDir == 1f) ? value3 : (value4 - 1));
         Vector2 vector2 = default(Vector2);
         for (int i = num3; i < value2; i++)
         {
             for (int j = value3; j < value4; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile != null && tile.liquid > 0 && !tile.lava() && !tile.shimmer() && (j != num4 || !tile.active() || !Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type] || (includeSlopes && tile.blockType() != 0)))
                 {
                     vector2.X = i * 16;
                     vector2.Y = j * 16;
                     int num5 = 16;
                     float num6 = 256 - Main.tile[i, j].liquid;
                     num6 /= 32f;
                     vector2.Y += num6 * 2f;
                     num5 -= (int)(num6 * 2f);
                     if (vector.X + (float)num > vector2.X && vector.X < vector2.X + 16f && vector.Y + (float)num2 > vector2.Y && vector.Y < vector2.Y + (float)num5)
                     {
                         return true;
                     }
                 }
             }
         }
         return false;
     }
References Tile.active(), Tile.blockType(), Tile.lava(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Tile.shimmer(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by NPC.AI_007_TownEntities(), NPC.AI_007_TownEntities_GetWalkPrediction(), NPC.CheckDrowning(), and Player.CheckDrowning().