Terraria: Collision.CanHit
CanHit() [1/4]
static bool Collision.CanHit (Entity source, Entity target) inline static
     {
         return CanHit(source.position, source.width, source.height, target.position, target.width, target.height);
     }
References Entity.height, Entity.position, and Entity.width.
Referenced by NPC.AI(), Projectile.AI(), Projectile.AI_001(), NPC.AI_001_Slimes(), NPC.AI_002_FloatingEye(), NPC.AI_003_Fighters(), NPC.AI_005_EaterOfSouls(), NPC.AI_007_TownEntities(), Projectile.AI_015_Flails(), Projectile.AI_015_Flails_Old(), Projectile.AI_016(), Projectile.AI_019_Spears(), Projectile.AI_019_Spears_Old(), Projectile.AI_026(), NPC.AI_037_Destroyer(), NPC.AI_045_Golem(), Projectile.AI_047_MagnetSphere_TryAttacking(), Projectile.AI_062(), Projectile.AI_099_1(), Projectile.AI_099_2(), NPC.AI_107_ImprovedWalkers(), NPC.AI_108_DivingFlyer(), NPC.AI_111_DD2LightningBug(), Projectile.AI_111_DryadsWard(), NPC.AI_113_WindyBalloon(), NPC.AI_121_QueenSlime_FlyMovement(), NPC.AI_125_ClumsySlimeBalloon(), Projectile.AI_147_Celeb2Rocket(), Projectile.AI_191_TrueNightsEdge(), Player.CanHit(), CanHit(), Projectile.CanHitWithMeleeWeapon(), Projectile.CanHitWithOwnBody(), Player.CanSnapToPosition(), Player.CollideWithNPCs(), Projectile.Colliding(), Projectile.Damage(), Main.DrawInterface_14_EntityHealthBars(), NPC.FindFrame(), Projectile.FindTargetWithLineOfSight(), Projectile.ghostHurt(), Player.ItemCheck_Shoot(), Player.JumpMovement(), WorldGen.MakeDungeon_Lights(), NPCUtils.SearchForTarget(), NPC.SpawnOnPlayer(), Player.SporeSac(), NPC.TargetClosestUpgraded(), Player.TryAllowingSnappingToPosition(), NPC.TryTrackingTarget(), LockOnHelper.Update(), and Player.VolatileGelatin().