Terraria: Collision.CanHit
CanHit() [3/4]
static bool Collision.CanHit (Point Position1, int Width1, int Height1, Point Position2, int Width2, int Height2) inline static
     {
         int num = (Position1.X + Width1 / 2) / 16;
         int num2 = (Position1.Y + Height1 / 2) / 16;
         int num3 = (Position2.X + Width2 / 2) / 16;
         int num4 = (Position2.Y + Height2 / 2) / 16;
         if (num <= 1)
         {
             num = 1;
         }
         if (num >= Main.maxTilesX)
         {
             num = Main.maxTilesX - 1;
         }
         if (num3 <= 1)
         {
             num3 = 1;
         }
         if (num3 >= Main.maxTilesX)
         {
             num3 = Main.maxTilesX - 1;
         }
         if (num2 <= 1)
         {
             num2 = 1;
         }
         if (num2 >= Main.maxTilesY)
         {
             num2 = Main.maxTilesY - 1;
         }
         if (num4 <= 1)
         {
             num4 = 1;
         }
         if (num4 >= Main.maxTilesY)
         {
             num4 = Main.maxTilesY - 1;
         }
         try
         {
             do
             {
                 int num5 = Math.Abs(num - num3);
                 int num6 = Math.Abs(num2 - num4);
                 if (num == num3 && num2 == num4)
                 {
                     return true;
                 }
                 if (num5 > num6)
                 {
                     num = ((num >= num3) ? (num - 1) : (num + 1));
                     if (Main.tile[num, num2 - 1] == null)
                     {
                         return false;
                     }
                     if (Main.tile[num, num2 + 1] == null)
                     {
                         return false;
                     }
                     if (!Main.tile[num, num2 - 1].inActive() && Main.tile[num, num2 - 1].active() && Main.tileSolid[Main.tile[num, num2 - 1].type] && !Main.tileSolidTop[Main.tile[num, num2 - 1].type] && Main.tile[num, num2 - 1].slope() == 0 && !Main.tile[num, num2 - 1].halfBrick() && !Main.tile[num, num2 + 1].inActive() && Main.tile[num, num2 + 1].active() && Main.tileSolid[Main.tile[num, num2 + 1].type] && !Main.tileSolidTop[Main.tile[num, num2 + 1].type] && Main.tile[num, num2 + 1].slope() == 0 && !Main.tile[num, num2 + 1].halfBrick())
                     {
                         return false;
                     }
                 }
                 else
                 {
                     num2 = ((num2 >= num4) ? (num2 - 1) : (num2 + 1));
                     if (Main.tile[num - 1, num2] == null)
                     {
                         return false;
                     }
                     if (Main.tile[num + 1, num2] == null)
                     {
                         return false;
                     }
                     if (!Main.tile[num - 1, num2].inActive() && Main.tile[num - 1, num2].active() && Main.tileSolid[Main.tile[num - 1, num2].type] && !Main.tileSolidTop[Main.tile[num - 1, num2].type] && Main.tile[num - 1, num2].slope() == 0 && !Main.tile[num - 1, num2].halfBrick() && !Main.tile[num + 1, num2].inActive() && Main.tile[num + 1, num2].active() && Main.tileSolid[Main.tile[num + 1, num2].type] && !Main.tileSolidTop[Main.tile[num + 1, num2].type] && Main.tile[num + 1, num2].slope() == 0 && !Main.tile[num + 1, num2].halfBrick())
                     {
                         return false;
                     }
                 }
                 if (Main.tile[num, num2] == null)
                 {
                     return false;
                 }
             }
             while (Main.tile[num, num2].inActive() || !Main.tile[num, num2].active() || !Main.tileSolid[Main.tile[num, num2].type] || Main.tileSolidTop[Main.tile[num, num2].type]);
             return false;
         }
         catch
         {
             return false;
         }
     }
References Tile.active(), Tile.halfBrick(), Tile.inActive(), Main.maxTilesX, Main.maxTilesY, Tile.slope(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.