Terraria: Collision.GetTileRotation
GetTileRotation()
static float Collision.GetTileRotation (Vector2 position) inline static
     {
         float num = position.Y % 16f;
         int num2 = (int)(position.X / 16f);
         int num3 = (int)(position.Y / 16f);
         Tile tile = Main.tile[num2, num3];
         bool flag = false;
         for (int num4 = 2; num4 >= 0; num4--)
         {
             if (tile.active())
             {
                 if (Main.tileSolid[tile.type])
                 {
                     int num5 = tile.blockType();
                     if (tile.type != 19)
                     {
                         return num5 switch
{
                             1 => 0f,
                             2 => (float)Math.PI / 4f,
                             3 => -(float)Math.PI / 4f,
                             _ => 0f,
                         };
                     }
                     int num6 = tile.frameX / 18;
                     if (((num6 >= 0 && num6 <= 7) || (num6 >= 12 && num6 <= 16)) && (num == 0f || flag))
                     {
                         return 0f;
                     }
                     switch (num6)
                     {
                     case 8:
                     case 19:
                     case 21:
                     case 23:
                         return -(float)Math.PI / 4f;
                     case 10:
                     case 20:
                     case 22:
                     case 24:
                         return (float)Math.PI / 4f;
                     case 25:
                     case 26:
                         if (!flag)
{
                             switch (num5)
{
                             case 2:
                                 return (float)Math.PI / 4f;
                             case 3:
                                 return -(float)Math.PI / 4f;
                             }
                             break;
                         }
                         return 0f;
                     }
                 }
                 else if (Main.tileSolidTop[tile.type] && tile.frameY == 0 && flag)
                 {
                     return 0f;
                 }
             }
             num3++;
             tile = Main.tile[num2, num3];
             flag = true;
         }
         return 0f;
     }
References Tile.active(), Tile.blockType(), Tile.frameX, Tile.frameY, Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by Mount.UpdateFrame().