Terraria: Collision.SolidCollision
SolidCollision() [1/2]
static bool Collision.SolidCollision (Vector2 Position, int Width, int Height) inline static
     {
         int value = (int)(Position.X / 16f) - 1;
         int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
         int value3 = (int)(Position.Y / 16f) - 1;
         int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
         int num = Utils.Clamp(value, 0, Main.maxTilesX - 1);
         value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
         value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
         value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
         Vector2 vector = default(Vector2);
         for (int i = num; i < value2; i++)
         {
             for (int j = value3; j < value4; j++)
             {
                 if (Main.tile[i, j] != null && !Main.tile[i, j].inActive() && Main.tile[i, j].active() && Main.tileSolid[Main.tile[i, j].type] && !Main.tileSolidTop[Main.tile[i, j].type])
                 {
                     vector.X = i * 16;
                     vector.Y = j * 16;
                     int num2 = 16;
                     if (Main.tile[i, j].halfBrick())
                     {
                         vector.Y += 8f;
                         num2 -= 8;
                     }
                     if (Position.X + (float)Width > vector.X && Position.X < vector.X + 16f && Position.Y + (float)Height > vector.Y && Position.Y < vector.Y + (float)num2)
                     {
                         return true;
                     }
                 }
             }
         }
         return false;
     }
References Tile.active(), Tile.halfBrick(), Tile.inActive(), Main.maxTilesX, Main.maxTilesY, Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by NPC.AI(), NPC.AI_001_Slimes(), NPC.AI_002_FloatingEye(), NPC.AI_003_Fighters(), Projectile.AI_026(), Projectile.AI_062(), Projectile.AI_067_FreakingPirates(), Projectile.AI_067_TigerSpecialAttack(), NPC.AI_069_DukeFishron(), NPC.AI_107_ImprovedWalkers(), NPC.AI_108_DivingFlyer(), NPC.AI_112_FairyCritter(), NPC.AI_117_BloodNautilus(), NPC.AI_123_Deerclops_Movement(), Projectile.AI_145_BookStaffStorm(), Projectile.AI_158_BabyBird(), Player.CanMoveForwardOnRope(), Player.CanSnapToPosition(), Player.ChangeDir(), Player.CheckForGoodTeleportationSpot(), Player.FindPulley(), Player.GrappleMovement(), TeleportHelpers.IsInSolidTilesExtended(), ShimmerHelper.IsSpotShimmerFree(), Player.ItemCheck_UseTeleportRod(), Player.SporeSac(), Gore.Update(), Rain.Update(), Player.Update(), Dust.UpdateDust(), and WorldGen.UpdateWorld().