Terraria: Collision.WetCollision
WetCollision()
static bool Collision.WetCollision (Vector2 Position, int Width, int Height) inline static
     {
         honey = false;
         shimmer = false;
         Vector2 vector = new Vector2(Position.X + (float)(Width / 2), Position.Y + (float)(Height / 2));
         int num = 10;
         int num2 = Height / 2;
         if (num > Width)
         {
             num = Width;
         }
         if (num2 > Height)
         {
             num2 = Height;
         }
         vector = new Vector2(vector.X - (float)(num / 2), vector.Y - (float)(num2 / 2));
         int value = (int)(Position.X / 16f) - 1;
         int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
         int value3 = (int)(Position.Y / 16f) - 1;
         int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
         int num3 = Utils.Clamp(value, 0, Main.maxTilesX - 1);
         value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
         value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
         value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
         Vector2 vector2 = default(Vector2);
         for (int i = num3; i < value2; i++)
         {
             for (int j = value3; j < value4; j++)
             {
                 if (Main.tile[i, j] == null)
                 {
                     continue;
                 }
                 if (Main.tile[i, j].liquid > 0)
                 {
                     vector2.X = i * 16;
                     vector2.Y = j * 16;
                     int num4 = 16;
                     float num5 = 256 - Main.tile[i, j].liquid;
                     num5 /= 32f;
                     vector2.Y += num5 * 2f;
                     num4 -= (int)(num5 * 2f);
                     if (vector.X + (float)num > vector2.X && vector.X < vector2.X + 16f && vector.Y + (float)num2 > vector2.Y && vector.Y < vector2.Y + (float)num4)
                     {
                         if (Main.tile[i, j].honey())
{
                             honey = true;
                         }
                         if (Main.tile[i, j].shimmer())
{
                             shimmer = true;
                         }
                         return true;
                     }
                 }
                 else
                 {
                     if (!Main.tile[i, j].active() || Main.tile[i, j].slope() == 0 || j <= 0 || Main.tile[i, j - 1] == null || Main.tile[i, j - 1].liquid <= 0)
                     {
                         continue;
                     }
                     vector2.X = i * 16;
                     vector2.Y = j * 16;
                     int num6 = 16;
                     if (vector.X + (float)num > vector2.X && vector.X < vector2.X + 16f && vector.Y + (float)num2 > vector2.Y && vector.Y < vector2.Y + (float)num6)
                     {
                         if (Main.tile[i, j - 1].honey())
{
                             honey = true;
                         }
                         else if (Main.tile[i, j - 1].shimmer())
{
                             shimmer = true;
                         }
                         return true;
                     }
                 }
             }
         }
         return false;
     }
References Tile.active(), honey, Tile.honey(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, shimmer, Tile.shimmer(), Tile.slope(), and Main.tile.
Referenced by NPC.AI_007_TownEntities(), Projectile.AI_145_BookStaffStorm(), Player.CheckForGoodTeleportationSpot(), NPC.Collision_WaterCollision(), WaterShaderData.DrawWaves(), MessageBuffer.GetData(), ShimmerHelper.IsSpotShimmerFree(), Item.MoveInWorld(), Dust.NewDust(), Item.NewItem(), NPC.NewNPC(), Projectile.NewProjectile(), Player.ShimmerUnstuck(), Player.SporeSac(), Gore.Update(), Rain.Update(), Player.Update(), Projectile.Update(), Dust.UpdateDust(), and NPC.UpdateNPC().