Terraria: System.Net.WebSockets.ClientWebSocketOptions.SetBuffer
SetBuffer() [2/2]
void System.Net.WebSockets.ClientWebSocketOptions.SetBuffer (int receiveBufferSize, int sendBufferSize, ArraySegment< byte > buffer) inline
Definition at line 187 of file ClientWebSocketOptions.cs.
    {
        ThrowIfReadOnly();
        if (receiveBufferSize <= 0)
        {
            throw new ArgumentOutOfRangeException("receiveBufferSize", receiveBufferSize, System.SR.Format(System.SR.net_WebSockets_ArgumentOutOfRange_TooSmall, 1));
        }
        if (sendBufferSize <= 0)
        {
            throw new ArgumentOutOfRangeException("sendBufferSize", sendBufferSize, System.SR.Format(System.SR.net_WebSockets_ArgumentOutOfRange_TooSmall, 1));
        }
        System.Net.WebSockets.WebSocketValidate.ValidateArraySegment(buffer, "buffer");
        if (buffer.Count == 0)
        {
            throw new ArgumentOutOfRangeException("buffer");
        }
        _receiveBufferSize = receiveBufferSize;
        _buffer = buffer;
    }
References System.Net.WebSockets.ClientWebSocketOptions._buffer, System.Net.WebSockets.ClientWebSocketOptions._receiveBufferSize, System.buffer, System.SR.Format(), System.SR.net_WebSockets_ArgumentOutOfRange_TooSmall, System.Net.WebSockets.ClientWebSocketOptions.ThrowIfReadOnly(), and System.Net.WebSockets.WebSocketValidate.ValidateArraySegment().