Terraria: System.Net.WebSockets.ClientWebSocketOptions.ThrowIfReadOnly
ThrowIfReadOnly()
void System.Net.WebSockets.ClientWebSocketOptions.ThrowIfReadOnly () inline private
Definition at line 212 of file ClientWebSocketOptions.cs.
    {
        if (_isReadOnly)
        {
            throw new InvalidOperationException(System.SR.net_WebSockets_AlreadyStarted);
        }
    }
References System.Net.WebSockets.ClientWebSocketOptions._isReadOnly, and System.SR.net_WebSockets_AlreadyStarted.
Referenced by System.Net.WebSockets.ClientWebSocketOptions.AddSubProtocol(), System.Net.WebSockets.ClientWebSocketOptions.SetBuffer(), System.Net.WebSockets.ClientWebSocketOptions.SetBuffer(), and System.Net.WebSockets.ClientWebSocketOptions.SetRequestHeader().