Terraria: MapHeadRenderer.DrawPlayerHead
DrawPlayerHead()
void MapHeadRenderer.DrawPlayerHead (Camera camera, Player drawPlayer, Vector2 position, float alpha = 1f, float scale = 1f, Color borderColor = default(Color)) inline
     {
         PlayerHeadDrawRenderTargetContent playerHeadDrawRenderTargetContent = _playerRenders[drawPlayer.whoAmI];
         playerHeadDrawRenderTargetContent.UsePlayer(drawPlayer);
         playerHeadDrawRenderTargetContent.UseColor(borderColor);
         playerHeadDrawRenderTargetContent.Request();
         _anyDirty = true;
         _drawData.Clear();
         if (playerHeadDrawRenderTargetContent.IsReady)
         {
             RenderTarget2D target = playerHeadDrawRenderTargetContent.GetTarget();
             _drawData.Add(new DrawData(target, position, null, Color.White, 0f, ((Texture2D)target).Size() / 2f, scale, SpriteEffects.None));
             RenderDrawData(drawPlayer);
         }
     }
References _anyDirty, _drawData, _playerRenders, Color, ARenderTargetContentByRequest.GetTarget(), ARenderTargetContentByRequest.IsReady, RenderDrawData(), ARenderTargetContentByRequest.Request(), AnOutlinedDrawRenderTargetContent.UseColor(), PlayerHeadDrawRenderTargetContent.UsePlayer(), and Entity.whoAmI.
Referenced by Main.DrawMap(), and NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawPlayerHead().