Terraria: MapHeadRenderer.RenderDrawData
RenderDrawData()
void MapHeadRenderer.RenderDrawData (Player drawPlayer) inline private
     {
         Effect pixelShader = Main.pixelShader;
         _ = Main.projectile;
         SpriteBatch spriteBatch = Main.spriteBatch;
         for (int i = 0; i < _drawData.Count; i++)
         {
             DrawData cdd = _drawData[i];
             if (!cdd.sourceRect.HasValue)
             {
                 cdd.sourceRect = cdd.texture.Frame();
             }
             PlayerDrawHelper.SetShaderForData(drawPlayer, drawPlayer.cHead, ref cdd);
             if (cdd.texture != null)
             {
                 cdd.Draw(spriteBatch);
             }
         }
         pixelShader.CurrentTechnique.Passes[0].Apply();
     }
References _drawData, Player.cHead, DrawData.Draw(), Main.pixelShader, Main.projectile, PlayerDrawHelper.SetShaderForData(), DrawData.sourceRect, Main.spriteBatch, and DrawData.texture.
Referenced by DrawPlayerHead().