Terraria: System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent
InternalWriteObjectContent() [2/2]
void System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent (XmlWriterDelegator writer, object graph, DataContractResolver dataContractResolver) inline package
Definition at line 325 of file DataContractSerializer.cs.
    {
        if (MaxItemsInObjectGraph == 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ExceededMaxItemsQuota, MaxItemsInObjectGraph)));
        }
        DataContract rootContract = RootContract;
        Type underlyingType = rootContract.UnderlyingType;
        Type objType = ((graph == null) ? underlyingType : graph.GetType());
        if (_serializationSurrogateProvider != null)
        {
            graph = SurrogateToDataContractType(_serializationSurrogateProvider, graph, underlyingType, ref objType);
        }
        if (dataContractResolver == null)
        {
            dataContractResolver = DataContractResolver;
        }
        if (graph == null)
        {
            if (IsRootXmlAny(_rootName, rootContract))
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.IsAnyCannotBeNull, underlyingType)));
            }
            XmlObjectSerializer.WriteNull(writer);
            return;
        }
        if (underlyingType == objType)
        {
            if (rootContract.CanContainReferences)
            {
                XmlObjectSerializerWriteContext xmlObjectSerializerWriteContext = XmlObjectSerializerWriteContext.CreateContext(this, rootContract, dataContractResolver);
                xmlObjectSerializerWriteContext.HandleGraphAtTopLevel(writer, graph, rootContract);
                xmlObjectSerializerWriteContext.SerializeWithoutXsiType(rootContract, writer, graph, underlyingType.TypeHandle);
            }
            else
            {
                rootContract.WriteXmlValue(writer, graph, null);
            }
            return;
        }
        XmlObjectSerializerWriteContext xmlObjectSerializerWriteContext2 = null;
        if (IsRootXmlAny(_rootName, rootContract))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.IsAnyCannotBeSerializedAsDerivedType, objType, rootContract.UnderlyingType)));
        }
        rootContract = GetDataContract(rootContract, underlyingType, objType);
        xmlObjectSerializerWriteContext2 = XmlObjectSerializerWriteContext.CreateContext(this, RootContract, dataContractResolver);
        if (rootContract.CanContainReferences)
        {
            xmlObjectSerializerWriteContext2.HandleGraphAtTopLevel(writer, graph, rootContract);
        }
        xmlObjectSerializerWriteContext2.OnHandleIsReference(writer, rootContract, graph);
        xmlObjectSerializerWriteContext2.SerializeWithXsiTypeAtTopLevel(rootContract, writer, graph, underlyingType.TypeHandle, objType);
    }
References System.Runtime.Serialization.DataContractSerializer._rootName, System.Runtime.Serialization.DataContractSerializer._serializationSurrogateProvider, System.Runtime.Serialization.XmlObjectSerializerWriteContext.CreateContext(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.DataContractSerializer.DataContractResolver, System.SR.ExceededMaxItemsQuota, System.SR.Format(), System.Runtime.Serialization.DataContractSerializer.GetDataContract(), System.SR.IsAnyCannotBeNull, System.SR.IsAnyCannotBeSerializedAsDerivedType, System.Runtime.Serialization.XmlObjectSerializer.IsRootXmlAny(), System.Runtime.Serialization.DataContractSerializer.MaxItemsInObjectGraph, System.Runtime.Serialization.DataContractSerializer.RootContract, System.Runtime.Serialization.DataContractSerializer.SurrogateToDataContractType(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.XmlObjectSerializer.WriteNull(), and System.writer.