Terraria: System.Runtime.Serialization.DataContractSerializer.InternalReadObject
InternalReadObject() [2/2]
override object System.Runtime.Serialization.DataContractSerializer.InternalReadObject (XmlReaderDelegator xmlReader, bool verifyObjectName, DataContractResolver dataContractResolver) inline package virtual
Reimplemented from System.Runtime.Serialization.XmlObjectSerializer.
Definition at line 410 of file DataContractSerializer.cs.
    {
        if (MaxItemsInObjectGraph == 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ExceededMaxItemsQuota, MaxItemsInObjectGraph)));
        }
        if (dataContractResolver == null)
        {
            dataContractResolver = DataContractResolver;
        }
        if (verifyObjectName)
        {
            if (!InternalIsStartObject(xmlReader))
            {
                XmlDictionaryString p;
                XmlDictionaryString p2;
                if (_rootName == null)
                {
                    p = RootContract.TopLevelElementName;
                    p2 = RootContract.TopLevelElementNamespace;
                }
                else
                {
                    p = _rootName;
                    p2 = _rootNamespace;
                }
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationExceptionWithReaderDetails(System.SR.Format(System.SR.ExpectingElement, p2, p), xmlReader));
            }
        }
        else if (!IsStartElement(xmlReader))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationExceptionWithReaderDetails(System.SR.Format(System.SR.ExpectingElementAtDeserialize, XmlNodeType.Element), xmlReader));
        }
        DataContract rootContract = RootContract;
        if (rootContract.IsPrimitive && (object)rootContract.UnderlyingType == _rootType)
        {
            return rootContract.ReadXmlValue(xmlReader, null);
        }
        if (IsRootXmlAny(_rootName, rootContract))
        {
            return XmlObjectSerializerReadContext.ReadRootIXmlSerializable(xmlReader, rootContract as XmlDataContract, isMemberType: false);
        }
        XmlObjectSerializerReadContext xmlObjectSerializerReadContext = XmlObjectSerializerReadContext.CreateContext(this, rootContract, dataContractResolver);
        return xmlObjectSerializerReadContext.InternalDeserialize(xmlReader, _rootType, rootContract, null, null);
    }
References System.Runtime.Serialization.DataContractSerializer._rootName, System.Runtime.Serialization.DataContractSerializer._rootNamespace, System.Runtime.Serialization.DataContractSerializer._rootType, System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateContext(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationExceptionWithReaderDetails(), System.Runtime.Serialization.DataContractSerializer.DataContractResolver, System.Runtime.Serialization.Dictionary, System.SR.ExceededMaxItemsQuota, System.SR.ExpectingElement, System.SR.ExpectingElementAtDeserialize, System.SR.Format(), System.Runtime.Serialization.DataContractSerializer.InternalIsStartObject(), System.Runtime.Serialization.XmlObjectSerializer.IsRootXmlAny(), System.Runtime.Serialization.XmlObjectSerializer.IsStartElement(), System.Runtime.Serialization.DataContractSerializer.MaxItemsInObjectGraph, System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadRootIXmlSerializable(), System.Runtime.Serialization.DataContractSerializer.RootContract, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.DataContract.TopLevelElementName, and System.Runtime.Serialization.DataContract.TopLevelElementNamespace.