Terraria: System.Runtime.Serialization.DataContractSerializer.Initialize
Initialize() [1/2]
void System.Runtime.Serialization.DataContractSerializer.Initialize (Type type, IEnumerable< Type > knownTypes, int maxItemsInObjectGraph, bool ignoreExtensionDataObject, bool preserveObjectReferences, DataContractResolver dataContractResolver, bool serializeReadOnlyTypes) inline private
Definition at line 183 of file DataContractSerializer.cs.
    {
        XmlObjectSerializer.CheckNull(type, "type");
        _rootType = type;
        if (knownTypes != null)
        {
            knownTypeList = new List<Type>();
            foreach (Type knownType in knownTypes)
            {
                knownTypeList.Add(knownType);
            }
        }
        if (maxItemsInObjectGraph < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("maxItemsInObjectGraph", System.SR.ValueMustBeNonNegative));
        }
        _maxItemsInObjectGraph = maxItemsInObjectGraph;
        _ignoreExtensionDataObject = ignoreExtensionDataObject;
        _preserveObjectReferences = preserveObjectReferences;
        _dataContractResolver = dataContractResolver;
        _serializeReadOnlyTypes = serializeReadOnlyTypes;
    }
References System.Runtime.Serialization.DataContractSerializer._dataContractResolver, System.Runtime.Serialization.DataContractSerializer._ignoreExtensionDataObject, System.Runtime.Serialization.DataContractSerializer._maxItemsInObjectGraph, System.Runtime.Serialization.DataContractSerializer._preserveObjectReferences, System.Runtime.Serialization.DataContractSerializer._rootType, System.Runtime.Serialization.DataContractSerializer._serializeReadOnlyTypes, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContractSerializer.knownTypeList, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.type, and System.SR.ValueMustBeNonNegative.
Referenced by System.Runtime.Serialization.DataContractSerializer.DataContractSerializer(), System.Runtime.Serialization.DataContractSerializer.DataContractSerializer(), System.Runtime.Serialization.DataContractSerializer.DataContractSerializer(), System.Runtime.Serialization.DataContractSerializer.DataContractSerializer(), System.Runtime.Serialization.DataContractSerializer.DataContractSerializer(), and System.Runtime.Serialization.DataContractSerializer.Initialize().