Terraria: System.Runtime.Serialization.DataContractSerializer.SurrogateToDataContractType
SurrogateToDataContractType()
static object System.Runtime.Serialization.DataContractSerializer.SurrogateToDataContractType (ISerializationSurrogateProvider serializationSurrogateProvider, object oldObj, Type surrogatedDeclaredType, ref Type objType) inline static package
Definition at line 478 of file DataContractSerializer.cs.
    {
        object objectToSerialize = DataContractSurrogateCaller.GetObjectToSerialize(serializationSurrogateProvider, oldObj, objType, surrogatedDeclaredType);
        if (objectToSerialize != oldObj)
        {
            objType = ((objectToSerialize != null) ? objectToSerialize.GetType() : Globals.TypeOfObject);
        }
        return objectToSerialize;
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContractSurrogateCaller.GetObjectToSerialize(), and System.Runtime.Serialization.Globals.TypeOfObject.
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.InternalSerializeWithSurrogate(), and System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent().