Terraria: System.Runtime.Serialization.DataContractSerializer.GetDataContract
GetDataContract()
static DataContract System.Runtime.Serialization.DataContractSerializer.GetDataContract (DataContract declaredTypeContract, Type declaredType, Type objectType) inline static package
Definition at line 381 of file DataContractSerializer.cs.
    {
        if (declaredType.IsInterface && CollectionDataContract.IsCollectionInterface(declaredType))
        {
            return declaredTypeContract;
        }
        if (declaredType.IsArray)
        {
            return declaredTypeContract;
        }
        return DataContract.GetDataContract(objectType.TypeHandle, objectType, SerializationMode.SharedContract);
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetDataContract(), and System.Runtime.Serialization.CollectionDataContract.IsCollectionInterface().
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.GetDataContract(), and System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent().