Terraria: System.Transactions.Distributed.DistributedTransaction.EnlistDurable
EnlistDurable()
IPromotedEnlistment System.Transactions.Distributed.DistributedTransaction.EnlistDurable (Guid resourceManagerIdentifier, DurableInternalEnlistment internalEnlistment, bool v, EnlistmentOptions enlistmentOptions) inline package
Definition at line 59 of file DistributedTransaction.cs.
    {
        throw NotSupported();
    }
References System.Transactions.Distributed.DistributedTransaction.NotSupported().
Referenced by System.Transactions.TransactionStatePromotedBase.EnlistDurable(), System.Transactions.TransactionStatePromotedBase.EnlistDurable(), and System.Transactions.TransactionStatePromoted.PromoteDurable().