Terraria: Terraria.GameContent.UI.States.UIGamepadHelper.PairLeftRight
PairLeftRight()
void Terraria.GameContent.UI.States.UIGamepadHelper.PairLeftRight (UILinkPoint leftSide, UILinkPoint rightSide) inline
Definition at line 235 of file UIGamepadHelper.cs.
    {
        if (leftSide != null && rightSide != null)
        {
            leftSide.Right = rightSide.ID;
            rightSide.Left = leftSide.ID;
        }
    }
Referenced by Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkStripHorizontal(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStripRightSideToSingle(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStrips(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.SetupGamepadPoints(), and Terraria.GameContent.UI.States.UIWorkshopHub.SetupGamepadPoints().