Terraria: Terraria.GameContent.UI.States.UIGamepadHelper.CullPointsOutOfElementArea
CullPointsOutOfElementArea()
void Terraria.GameContent.UI.States.UIGamepadHelper.CullPointsOutOfElementArea (SpriteBatch spriteBatch, List< SnapPoint > pointsAtMiddle, UIElement container) inline
Definition at line 316 of file UIGamepadHelper.cs.
    {
        float num = 1f / Main.UIScale;
        Rectangle clippingRectangle = container.GetClippingRectangle(spriteBatch);
        Vector2 minimum = clippingRectangle.TopLeft() * num;
        Vector2 maximum = clippingRectangle.BottomRight() * num;
        for (int i = 0; i < pointsAtMiddle.Count; i++)
        {
            if (!pointsAtMiddle[i].Position.Between(minimum, maximum))
            {
                pointsAtMiddle.Remove(pointsAtMiddle[i]);
                i--;
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.UI.UIElement.GetClippingRectangle(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and Terraria.Main.UIScale.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.SetupGamepadPoints(), and Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.SetupGamepadPoints().