Terraria: Terraria.GameContent.UI.States.UIGamepadHelper.MakeLinkPointFromSnapPoint
MakeLinkPointFromSnapPoint()
UILinkPoint Terraria.GameContent.UI.States.UIGamepadHelper.MakeLinkPointFromSnapPoint (int id, SnapPoint snap) inline
Definition at line 253 of file UIGamepadHelper.cs.
    {
        UILinkPointNavigator.SetPosition(id, snap.Position);
        UILinkPoint uILinkPoint = UILinkPointNavigator.Points[id];
        uILinkPoint.Unlink();
        return uILinkPoint;
    }
References Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.SnapPoint.Position, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), and Terraria.UI.Gamepad.UILinkPoint.Unlink().
Referenced by Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkStripHorizontal(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkStripVertical(), Terraria.GameContent.UI.States.UIGamepadHelper.GetLinkPoint(), Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIReportsPage.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.SetupGamepadPoints(), and Terraria.GameContent.UI.States.UIGamepadHelper.TryMakeLinkPoint().