Terraria: System.Xml.Xsl.XPath.XPathBuilder.ArithmeticOperator
ArithmeticOperator()
QilNode System.Xml.Xsl.XPath.XPathBuilder.ArithmeticOperator (XPathOperator op, QilNode left, QilNode right) inline private inherited
Definition at line 574 of file XPathBuilder.cs.
    {
        left = _f.ConvertToNumber(left);
        right = _f.ConvertToNumber(right);
        return op switch
        {
            XPathOperator.Plus => _f.Add(left, right),
            XPathOperator.Minus => _f.Subtract(left, right),
            XPathOperator.Multiply => _f.Multiply(left, right),
            XPathOperator.Divide => _f.Divide(left, right),
            XPathOperator.Modulo => _f.Modulo(left, right),
            _ => null,
        };
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.Qil.QilPatternFactory.Add(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Divide(), System.Xml.Xsl.Qil.QilPatternFactory.Modulo(), System.Xml.Xsl.Qil.QilPatternFactory.Multiply(), and System.Xml.Xsl.Qil.QilPatternFactory.Subtract().
Referenced by System.Xml.Xsl.XPath.XPathBuilder.Operator().