Terraria: System.Xml.Xsl.XPath.XPathBuilder.PredicateToBoolean
PredicateToBoolean()
static QilNode System.Xml.Xsl.XPath.XPathBuilder.PredicateToBoolean (QilNode predicate, XPathQilFactory f, IXPathEnvironment env) inline static inherited
Definition at line 718 of file XPathBuilder.cs.
    {
        QilIterator qilIterator;
        predicate = (f.IsAnyType(predicate) ? f.Loop(qilIterator = f.Let(predicate), f.Conditional(f.IsType(qilIterator, XmlQueryTypeFactory.Double), f.Eq(env.GetPosition(), f.TypeAssert(qilIterator, XmlQueryTypeFactory.DoubleX)), f.ConvertToBoolean(qilIterator))) : ((predicate.XmlType.TypeCode != XmlTypeCode.Double) ? f.ConvertToBoolean(predicate) : f.Eq(env.GetPosition(), predicate)));
        return predicate;
    }
References System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToBoolean(), System.Xml.Dictionary, System.Xml.Xsl.XmlQueryTypeFactory.Double, System.Xml.Xsl.XmlQueryTypeFactory.DoubleX, System.Xml.Xsl.Qil.QilPatternFactory.Eq(), System.Xml.Xsl.XPath.XPathQilFactory.IsAnyType(), System.Xml.Xsl.Qil.QilPatternFactory.IsType(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), and System.Xml.Xsl.Qil.QilPatternFactory.TypeAssert().
Referenced by System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildPredicates(), and System.Xml.Xsl.XPath.XPathBuilder.Predicate().