Terraria: System.Xml.Xsl.XPath.XPathBuilder.BuildAxisFilter
BuildAxisFilter()
QilNode System.Xml.Xsl.XPath.XPathBuilder.BuildAxisFilter (QilNode qilAxis, XPathAxis xpathAxis, XPathNodeType nodeType, string name, string nsUri) inline private inherited
Definition at line 610 of file XPathBuilder.cs.
    {
        XmlNodeKindFlags nodeKinds = qilAxis.XmlType.NodeKinds;
        XmlNodeKindFlags xmlNodeKindFlags = AxisTypeMask(nodeKinds, nodeType, xpathAxis);
        if (xmlNodeKindFlags == XmlNodeKindFlags.None)
        {
            return _f.Sequence();
        }
        QilIterator expr;
        if (xmlNodeKindFlags != nodeKinds)
        {
            qilAxis = _f.Filter(expr = _f.For(qilAxis), _f.IsType(expr, XmlQueryTypeFactory.NodeChoice(xmlNodeKindFlags)));
            qilAxis.XmlType = XmlQueryTypeFactory.PrimeProduct(XmlQueryTypeFactory.NodeChoice(xmlNodeKindFlags), qilAxis.XmlType.Cardinality);
            if (qilAxis.NodeType == QilNodeType.Filter)
            {
                QilLoop qilLoop = (QilLoop)qilAxis;
                qilLoop.Body = _f.And(qilLoop.Body, (name != null && nsUri != null) ? _f.Eq(_f.NameOf(expr), _f.QName(name, nsUri)) : ((nsUri != null) ? _f.Eq(_f.NamespaceUriOf(expr), _f.String(nsUri)) : ((name != null) ? _f.Eq(_f.LocalNameOf(expr), _f.String(name)) : _f.True())));
                return qilLoop;
            }
        }
        return _f.Filter(expr = _f.For(qilAxis), (name != null && nsUri != null) ? _f.Eq(_f.NameOf(expr), _f.QName(name, nsUri)) : ((nsUri != null) ? _f.Eq(_f.NamespaceUriOf(expr), _f.String(nsUri)) : ((name != null) ? _f.Eq(_f.LocalNameOf(expr), _f.String(name)) : _f.True())));
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.Qil.QilPatternFactory.And(), System.Xml.Xsl.XPath.XPathBuilder.AxisTypeMask(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Eq(), System.Xml.Xsl.Qil.QilPatternFactory.Filter(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Qil.QilPatternFactory.IsType(), System.Xml.Xsl.Qil.QilPatternFactory.LocalNameOf(), System.Xml.Xsl.Qil.QilPatternFactory.NameOf(), System.Xml.Xsl.Qil.QilPatternFactory.NamespaceUriOf(), System.Xml.Xsl.XmlQueryTypeFactory.NodeChoice(), System.Xml.Xsl.XmlQueryTypeFactory.PrimeProduct(), System.Xml.Xsl.Qil.QilPatternFactory.QName(), System.Xml.Xsl.Qil.QilPatternFactory.Sequence(), System.Xml.Xsl.Qil.QilPatternFactory.String(), and System.Xml.Xsl.Qil.QilPatternFactory.True().
Referenced by System.Xml.Xsl.XPath.XPathBuilder.BuildAxis().