Terraria: System.Xml.Xsl.XPath.XPathBuilder.NameOfFirstNode
NameOfFirstNode()
QilNode System.Xml.Xsl.XPath.XPathBuilder.NameOfFirstNode (QilNode arg) inline private inherited
Definition at line 885 of file XPathBuilder.cs.
    {
        if (arg.XmlType.IsSingleton)
        {
            return NameOf(arg);
        }
        QilIterator arg2;
        return _f.StrConcat(_f.Loop(arg2 = _f.FirstNode(arg), NameOf(arg2)));
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathQilFactory.FirstNode(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Qil.NameOf, and System.Xml.Xsl.Qil.QilPatternFactory.StrConcat().
Referenced by System.Xml.Xsl.XPath.XPathBuilder.Function().