Terraria: System.Xml.Xsl.XPath.XPathBuilder.LogicalOperator
LogicalOperator()
QilNode System.Xml.Xsl.XPath.XPathBuilder.LogicalOperator (XPathOperator op, QilNode left, QilNode right) inline private inherited
Definition at line 454 of file XPathBuilder.cs.
    {
        left = _f.ConvertToBoolean(left);
        right = _f.ConvertToBoolean(right);
        if (op != XPathOperator.Or)
        {
            return _f.And(left, right);
        }
        return _f.Or(left, right);
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.Qil.QilPatternFactory.And(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToBoolean(), and System.Xml.Xsl.Qil.QilPatternFactory.Or().
Referenced by System.Xml.Xsl.XPath.XPathBuilder.Operator().