Terraria: System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndNodeSet
CompareNodeSetAndNodeSet()
QilNode System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndNodeSet (XPathOperator op, QilNode left, QilNode right, XmlTypeCode compType) inline private inherited
Definition at line 503 of file XPathBuilder.cs.
    {
        if (right.XmlType.IsSingleton)
        {
            return CompareNodeSetAndValue(op, left, right, compType);
        }
        if (left.XmlType.IsSingleton)
        {
            op = InvertOp(op);
            return CompareNodeSetAndValue(op, right, left, compType);
        }
        QilIterator qilIterator = _f.For(left);
        QilIterator qilIterator2 = _f.For(right);
        return _f.Not(_f.IsEmpty(_f.Loop(qilIterator, _f.Filter(qilIterator2, CompareValues(op, _f.XPathNodeValue(qilIterator), _f.XPathNodeValue(qilIterator2), compType)))));
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndValue(), System.Xml.Xsl.XPath.XPathBuilder.CompareValues(), System.Xml.Xsl.Qil.QilPatternFactory.Filter(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.XPath.XPathBuilder.InvertOp(), System.Xml.Xsl.Qil.QilPatternFactory.IsEmpty(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Qil.QilPatternFactory.Not(), System.Xml.Xsl.Qil.QilNode.XmlType, and System.Xml.Xsl.Qil.QilPatternFactory.XPathNodeValue().
Referenced by System.Xml.Xsl.XPath.XPathBuilder.EqualityOperator(), and System.Xml.Xsl.XPath.XPathBuilder.RelationalOperator().