Terraria: System.Xml.Xsl.XPath.XPathBuilder.NameOf
NameOf()
QilNode System.Xml.Xsl.XPath.XPathBuilder.NameOf (QilNode arg) inline private inherited
Definition at line 873 of file XPathBuilder.cs.
    {
        QilIterator qilIterator;
        QilIterator qilIterator2;
        if (arg is QilIterator)
        {
            return _f.Loop(qilIterator = _f.Let(_f.PrefixOf(arg)), _f.Loop(qilIterator2 = _f.Let(_f.LocalNameOf(arg)), _f.Conditional(_f.Eq(_f.StrLength(qilIterator), _f.Int32(0)), qilIterator2, _f.StrConcat(qilIterator, _f.String(":"), qilIterator2))));
        }
        QilIterator qilIterator3 = _f.Let(arg);
        return _f.Loop(qilIterator3, NameOf(qilIterator3));
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Eq(), System.Xml.Xsl.Qil.QilPatternFactory.Int32(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.LocalNameOf(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Qil.NameOf, System.Xml.Xsl.Qil.QilPatternFactory.PrefixOf(), System.Xml.Xsl.Qil.QilPatternFactory.StrConcat(), System.Xml.Xsl.Qil.QilPatternFactory.String(), and System.Xml.Xsl.Qil.QilPatternFactory.StrLength().