Terraria: System.Xml.Xsl.XPath.XPathBuilder.Function
Function() [4/4]
virtual QilNode System.Xml.Xsl.XPath.XPathBuilder.Function (string prefix, string name, IList< QilNode > args) inline virtual inherited
Definition at line 761 of file XPathBuilder.cs.
    {
        if (prefix.Length == 0 && FunctionTable.TryGetValue(name, out var value))
        {
            value.CastArguments(args, name, _f);
            switch (value.id)
            {
            case FuncId.Not:
                return _f.Not(args[0]);
            case FuncId.Last:
                return GetLastPosition();
            case FuncId.Position:
                return GetCurrentPosition();
            case FuncId.Count:
                return _f.XsltConvert(_f.Length(_f.DocOrderDistinct(args[0])), XmlQueryTypeFactory.DoubleX);
            case FuncId.LocalName:
                if (args.Count != 0)
                {
                    return LocalNameOfFirstNode(args[0]);
                }
                return _f.LocalNameOf(GetCurrentNode());
            case FuncId.NamespaceUri:
                if (args.Count != 0)
                {
                    return NamespaceOfFirstNode(args[0]);
                }
                return _f.NamespaceUriOf(GetCurrentNode());
            case FuncId.Name:
                if (args.Count != 0)
                {
                    return NameOfFirstNode(args[0]);
                }
                return NameOf(GetCurrentNode());
            case FuncId.String:
                if (args.Count != 0)
                {
                    return _f.ConvertToString(args[0]);
                }
                return _f.XPathNodeValue(GetCurrentNode());
            case FuncId.Number:
                if (args.Count != 0)
                {
                    return _f.ConvertToNumber(args[0]);
                }
                return _f.XsltConvert(_f.XPathNodeValue(GetCurrentNode()), XmlQueryTypeFactory.DoubleX);
            case FuncId.Boolean:
                return _f.ConvertToBoolean(args[0]);
            case FuncId.True:
                return _f.True();
            case FuncId.False:
                return _f.False();
            case FuncId.Id:
                return _f.DocOrderDistinct(_f.Id(GetCurrentNode(), args[0]));
            case FuncId.Concat:
                return _f.StrConcat(args);
            case FuncId.StartsWith:
                return _f.InvokeStartsWith(args[0], args[1]);
            case FuncId.Contains:
                return _f.InvokeContains(args[0], args[1]);
            case FuncId.SubstringBefore:
                return _f.InvokeSubstringBefore(args[0], args[1]);
            case FuncId.SubstringAfter:
                return _f.InvokeSubstringAfter(args[0], args[1]);
            case FuncId.Substring:
                if (args.Count != 2)
                {
                    return _f.InvokeSubstring(args[0], args[1], args[2]);
                }
                return _f.InvokeSubstring(args[0], args[1]);
            case FuncId.StringLength:
                return _f.XsltConvert(_f.StrLength((args.Count == 0) ? _f.XPathNodeValue(GetCurrentNode()) : args[0]), XmlQueryTypeFactory.DoubleX);
            case FuncId.Normalize:
                return _f.InvokeNormalizeSpace((args.Count == 0) ? _f.XPathNodeValue(GetCurrentNode()) : args[0]);
            case FuncId.Translate:
                return _f.InvokeTranslate(args[0], args[1], args[2]);
            case FuncId.Lang:
                return _f.InvokeLang(args[0], GetCurrentNode());
            case FuncId.Sum:
                return Sum(_f.DocOrderDistinct(args[0]));
            case FuncId.Floor:
                return _f.InvokeFloor(args[0]);
            case FuncId.Ceiling:
                return _f.InvokeCeiling(args[0]);
            case FuncId.Round:
                return _f.InvokeRound(args[0]);
            default:
                return null;
            }
        }
        return _environment.ResolveFunction(prefix, name, args, this);
    }
References System.Xml.Xsl.XPath.XPathBuilder._environment, System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.Qil.QilNode.Contains(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToBoolean(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Qil.QilPatternFactory.DocOrderDistinct(), System.Xml.Xsl.XmlQueryTypeFactory.DoubleX, System.Xml.Xsl.Qil.QilPatternFactory.False(), System.Xml.Xsl.XPath.XPathBuilder.FunctionTable, System.Xml.Xsl.XPath.XPathBuilder.GetCurrentNode(), System.Xml.Xsl.XPath.XPathBuilder.GetCurrentPosition(), System.Xml.Xsl.XPath.XPathBuilder.GetLastPosition(), System.Xml.Xsl.XPath.XPathQilFactory.Id(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeCeiling(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeContains(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeFloor(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeLang(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeNormalizeSpace(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeRound(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeStartsWith(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeSubstring(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeSubstringAfter(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeSubstringBefore(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeTranslate(), System.Xml.Xsl.Qil.QilPatternFactory.Length(), System.Xml.Xsl.Qil.QilPatternFactory.LocalNameOf(), System.Xml.Xsl.XPath.XPathBuilder.LocalNameOfFirstNode(), System.Xml.Xsl.Qil.NameOf, System.Xml.Xsl.XPath.XPathBuilder.NameOfFirstNode(), System.Xml.Xsl.XPath.XPathBuilder.NamespaceOfFirstNode(), System.Xml.Xsl.Qil.QilPatternFactory.NamespaceUriOf(), System.Xml.Xsl.Qil.QilPatternFactory.Not(), System.prefix, System.Xml.Xsl.XPath.IXPathEnvironment.ResolveFunction(), System.Xml.Xsl.Qil.QilPatternFactory.StrConcat(), System.Xml.Xsl.Qil.QilPatternFactory.StrLength(), System.Xml.Xsl.XPath.XPathBuilder.Sum, System.Xml.Xsl.Qil.QilPatternFactory.True(), System.value, System.Xml.Xsl.Qil.QilPatternFactory.XPathNodeValue(), and System.Xml.Xsl.Qil.QilPatternFactory.XsltConvert().