Terraria: System.Xml.Xsl.XPath.XPathBuilder.EqualityOperator
EqualityOperator()
QilNode System.Xml.Xsl.XPath.XPathBuilder.EqualityOperator (XPathOperator op, QilNode left, QilNode right) inline private inherited
Definition at line 519 of file XPathBuilder.cs.
    {
        XmlQueryType xmlType = left.XmlType;
        XmlQueryType xmlType2 = right.XmlType;
        if (_f.IsAnyType(left) || _f.IsAnyType(right))
        {
            return _f.InvokeEqualityOperator(s_qilOperator[(int)op], left, right);
        }
        if (xmlType.IsNode && xmlType2.IsNode)
        {
            return CompareNodeSetAndNodeSet(op, left, right, XmlTypeCode.String);
        }
        if (xmlType.IsNode)
        {
            return CompareNodeSetAndValue(op, left, right, xmlType2.TypeCode);
        }
        if (xmlType2.IsNode)
        {
            return CompareNodeSetAndValue(op, right, left, xmlType.TypeCode);
        }
        XmlTypeCode compType = ((xmlType.TypeCode == XmlTypeCode.Boolean || xmlType2.TypeCode == XmlTypeCode.Boolean) ? XmlTypeCode.Boolean : ((xmlType.TypeCode == XmlTypeCode.Double || xmlType2.TypeCode == XmlTypeCode.Double) ? XmlTypeCode.Double : XmlTypeCode.String));
        return CompareValues(op, left, right, compType);
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndNodeSet(), System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndValue(), System.Xml.Xsl.XPath.XPathBuilder.CompareValues(), System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathQilFactory.InvokeEqualityOperator(), System.Xml.Xsl.XPath.XPathQilFactory.IsAnyType(), System.Xml.Xsl.XmlQueryType.IsNode, System.Xml.Xsl.XPath.XPathBuilder.s_qilOperator, System.Xml.Xsl.XmlQueryType.TypeCode, and System.Xml.Xsl.Qil.QilNode.XmlType.
Referenced by System.Xml.Xsl.XPath.XPathBuilder.Operator().