Terraria: System.Xml.Xsl.XPath.XPathBuilder.Sum
Sum()
QilNode System.Xml.Xsl.XPath.XPathBuilder.Sum (QilNode arg) inline private inherited
Definition at line 895 of file XPathBuilder.cs.
    {
        QilIterator n;
        return _f.Sum(_f.Sequence(_f.Double(0.0), _f.Loop(n = _f.For(arg), _f.ConvertToNumber(n))));
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Double(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Qil.QilPatternFactory.Sequence(), and System.Xml.Xsl.Qil.QilPatternFactory.Sum().