Terraria: System.Xml.Xsl.XPath.XPathBuilder.UnionOperator
UnionOperator()
QilNode System.Xml.Xsl.XPath.XPathBuilder.UnionOperator (XPathOperator op, QilNode left, QilNode right) inline private inherited
Definition at line 589 of file XPathBuilder.cs.
    {
        if (left == null)
        {
            return _f.EnsureNodeSet(right);
        }
        left = _f.EnsureNodeSet(left);
        right = _f.EnsureNodeSet(right);
        if (left.NodeType == QilNodeType.Sequence)
        {
            ((QilList)left).Add(right);
            return left;
        }
        return _f.Union(left, right);
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.Qil.QilNode.Add(), System.Xml.Xsl.XPath.XPathQilFactory.EnsureNodeSet(), System.Xml.Xsl.Qil.QilNode.NodeType, and System.Xml.Xsl.Qil.QilPatternFactory.Union().
Referenced by System.Xml.Xsl.XPath.XPathBuilder.Operator().