Terraria: System.Xml.Xsl.XPath.XPathBuilder.JoinStep
JoinStep() [4/4]
virtual QilNode System.Xml.Xsl.XPath.XPathBuilder.JoinStep (QilNode left, QilNode right) inline virtual inherited
Definition at line 698 of file XPathBuilder.cs.
    {
        QilIterator qilIterator = _f.For(_f.EnsureNodeSet(left));
        right = _fixupVisitor.Fixup(right, qilIterator, null);
        numFixupCurrent -= _fixupVisitor.numCurrent;
        numFixupPosition -= _fixupVisitor.numPosition;
        numFixupLast -= _fixupVisitor.numLast;
        return _f.DocOrderDistinct(_f.Loop(qilIterator, right));
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.XPath.XPathBuilder._fixupVisitor, System.Xml.Xsl.Qil.QilPatternFactory.DocOrderDistinct(), System.Xml.Xsl.XPath.XPathQilFactory.EnsureNodeSet(), System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.Fixup(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.numCurrent, System.Xml.Xsl.XPath.XPathBuilder.numFixupCurrent, System.Xml.Xsl.XPath.XPathBuilder.numFixupLast, System.Xml.Xsl.XPath.XPathBuilder.numFixupPosition, System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.numLast, and System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.numPosition.