Terraria: System.Xml.Xsl.XPath.XPathBuilder.BuildOnePredicate
BuildOnePredicate()
static QilNode System.Xml.Xsl.XPath.XPathBuilder.BuildOnePredicate (QilNode nodeset, QilNode predicate, bool isReverseStep, XPathQilFactory f, FixupVisitor fixupVisitor, ref int numFixupCurrent, ref int numFixupPosition, ref int numFixupLast) inline static inherited
Definition at line 725 of file XPathBuilder.cs.
    {
        nodeset = f.EnsureNodeSet(nodeset);
        QilNode qilNode;
        if (numFixupLast != 0 && fixupVisitor.CountUnfixedLast(predicate) != 0)
        {
            QilIterator qilIterator = f.Let(nodeset);
            QilIterator qilIterator2 = f.Let(f.XsltConvert(f.Length(qilIterator), XmlQueryTypeFactory.DoubleX));
            QilIterator qilIterator3 = f.For(qilIterator);
            predicate = fixupVisitor.Fixup(predicate, qilIterator3, qilIterator2);
            numFixupCurrent -= fixupVisitor.numCurrent;
            numFixupPosition -= fixupVisitor.numPosition;
            numFixupLast -= fixupVisitor.numLast;
            qilNode = f.Loop(qilIterator, f.Loop(qilIterator2, f.Filter(qilIterator3, predicate)));
        }
        else
        {
            QilIterator qilIterator4 = f.For(nodeset);
            predicate = fixupVisitor.Fixup(predicate, qilIterator4, null);
            numFixupCurrent -= fixupVisitor.numCurrent;
            numFixupPosition -= fixupVisitor.numPosition;
            numFixupLast -= fixupVisitor.numLast;
            qilNode = f.Filter(qilIterator4, predicate);
        }
        if (isReverseStep)
        {
            qilNode = f.DocOrderDistinct(qilNode);
        }
        return qilNode;
    }
References System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.CountUnfixedLast(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.DocOrderDistinct(), System.Xml.Xsl.XmlQueryTypeFactory.DoubleX, System.Xml.Xsl.XPath.XPathQilFactory.EnsureNodeSet(), System.Xml.Xsl.Qil.QilPatternFactory.Filter(), System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.Fixup(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Qil.QilPatternFactory.Length(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.numCurrent, System.Xml.Xsl.XPath.XPathBuilder.numFixupCurrent, System.Xml.Xsl.XPath.XPathBuilder.numFixupLast, System.Xml.Xsl.XPath.XPathBuilder.numFixupPosition, System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.numLast, System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.numPosition, and System.Xml.Xsl.Qil.QilPatternFactory.XsltConvert().
Referenced by System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildPredicates(), and System.Xml.Xsl.XPath.XPathBuilder.Predicate().