Terraria: System.Xml.Xsl.XPath.XPathBuilder.BuildAxis
BuildAxis()
QilNode System.Xml.Xsl.XPath.XPathBuilder.BuildAxis (XPathAxis xpathAxis, XPathNodeType nodeType, string nsUri, string name) inline private inherited
Definition at line 633 of file XPathBuilder.cs.
    {
        QilNode currentNode = GetCurrentNode();
        QilNode qilAxis;
        switch (xpathAxis)
        {
        case XPathAxis.Ancestor:
            qilAxis = _f.Ancestor(currentNode);
            break;
        case XPathAxis.AncestorOrSelf:
            qilAxis = _f.AncestorOrSelf(currentNode);
            break;
        case XPathAxis.Attribute:
            qilAxis = _f.Content(currentNode);
            break;
        case XPathAxis.Child:
            qilAxis = _f.Content(currentNode);
            break;
        case XPathAxis.Descendant:
            qilAxis = _f.Descendant(currentNode);
            break;
        case XPathAxis.DescendantOrSelf:
            qilAxis = _f.DescendantOrSelf(currentNode);
            break;
        case XPathAxis.Following:
            qilAxis = _f.XPathFollowing(currentNode);
            break;
        case XPathAxis.FollowingSibling:
            qilAxis = _f.FollowingSibling(currentNode);
            break;
        case XPathAxis.Namespace:
            qilAxis = _f.XPathNamespace(currentNode);
            break;
        case XPathAxis.Parent:
            qilAxis = _f.Parent(currentNode);
            break;
        case XPathAxis.Preceding:
            qilAxis = _f.XPathPreceding(currentNode);
            break;
        case XPathAxis.PrecedingSibling:
            qilAxis = _f.PrecedingSibling(currentNode);
            break;
        case XPathAxis.Self:
            qilAxis = currentNode;
            break;
        case XPathAxis.Root:
            return _f.Root(currentNode);
        default:
            qilAxis = null;
            break;
        }
        QilNode qilNode = BuildAxisFilter(qilAxis, xpathAxis, nodeType, name, nsUri);
        if (xpathAxis == XPathAxis.Ancestor || xpathAxis == XPathAxis.Preceding || xpathAxis == XPathAxis.AncestorOrSelf || xpathAxis == XPathAxis.PrecedingSibling)
        {
            qilNode = _f.BaseFactory.DocOrderDistinct(qilNode);
        }
        return qilNode;
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.Qil.QilPatternFactory.Ancestor(), System.Xml.Xsl.Qil.QilPatternFactory.AncestorOrSelf(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Xsl.XPath.XPathBuilder.BuildAxisFilter(), System.Xml.Xsl.Qil.QilPatternFactory.Content(), System.Xml.Xsl.Qil.QilPatternFactory.Descendant(), System.Xml.Xsl.Qil.QilPatternFactory.DescendantOrSelf(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilFactory.DocOrderDistinct(), System.Xml.Xsl.Qil.QilPatternFactory.FollowingSibling(), System.Xml.Xsl.XPath.XPathBuilder.GetCurrentNode(), System.Xml.Xsl.Qil.QilPatternFactory.Parent(), System.Xml.Xsl.Qil.QilPatternFactory.PrecedingSibling(), System.Xml.Xsl.Qil.QilPatternFactory.Root(), System.Xml.Xsl.Qil.QilPatternFactory.XPathFollowing(), System.Xml.Xsl.Qil.QilPatternFactory.XPathNamespace(), and System.Xml.Xsl.Qil.QilPatternFactory.XPathPreceding().
Referenced by System.Xml.Xsl.XPath.XPathBuilder.Axis().