Terraria: System.Xml.Xsl.XPath.XPathBuilder.CompareValues
CompareValues()
QilNode System.Xml.Xsl.XPath.XPathBuilder.CompareValues (XPathOperator op, QilNode left, QilNode right, XmlTypeCode compType) inline private inherited
Definition at line 465 of file XPathBuilder.cs.
    {
        left = _f.ConvertToType(compType, left);
        right = _f.ConvertToType(compType, right);
        return op switch
        {
            XPathOperator.Eq => _f.Eq(left, right),
            XPathOperator.Ne => _f.Ne(left, right),
            XPathOperator.Lt => _f.Lt(left, right),
            XPathOperator.Le => _f.Le(left, right),
            XPathOperator.Gt => _f.Gt(left, right),
            XPathOperator.Ge => _f.Ge(left, right),
            _ => null,
        };
    }
References System.Xml.Xsl.XPath.XPathBuilder._f, System.Xml.Xsl.XPath.XPathQilFactory.ConvertToType(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Eq(), System.Xml.Xsl.Qil.QilPatternFactory.Ge(), System.Xml.Xsl.Qil.QilPatternFactory.Gt(), System.Xml.Xsl.Qil.QilPatternFactory.Le(), System.Xml.Xsl.Qil.QilPatternFactory.Lt(), and System.Xml.Xsl.Qil.QilPatternFactory.Ne().
Referenced by System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndNodeSet(), System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndValue(), System.Xml.Xsl.XPath.XPathBuilder.EqualityOperator(), and System.Xml.Xsl.XPath.XPathBuilder.RelationalOperator().