Terraria: System.Xml.Xsl.XPath.XPathBuilder.Operator
Operator() [4/4]
virtual QilNode System.Xml.Xsl.XPath.XPathBuilder.Operator (XPathOperator op, QilNode left, QilNode right) inline virtual inherited
Definition at line 440 of file XPathBuilder.cs.
    {
        return s_operatorGroup[(int)op] switch
        {
            XPathOperatorGroup.Logical => LogicalOperator(op, left, right),
            XPathOperatorGroup.Equality => EqualityOperator(op, left, right),
            XPathOperatorGroup.Relational => RelationalOperator(op, left, right),
            XPathOperatorGroup.Arithmetic => ArithmeticOperator(op, left, right),
            XPathOperatorGroup.Negate => NegateOperator(op, left),
            XPathOperatorGroup.Union => UnionOperator(op, left, right),
            _ => null,
        };
    }
References System.Xml.Xsl.XPath.XPathBuilder.ArithmeticOperator(), System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathBuilder.EqualityOperator(), System.Xml.Xsl.XPath.XPathBuilder.LogicalOperator(), System.Xml.Xsl.XPath.XPathBuilder.NegateOperator(), System.Xml.Xsl.XPath.XPathBuilder.RelationalOperator(), System.Xml.Xsl.XPath.XPathBuilder.s_operatorGroup, and System.Xml.Xsl.XPath.XPathBuilder.UnionOperator().