Terraria: System.Reflection.MetadataImport.GetMemberRefProps
GetMemberRefProps()
ConstArray System.Reflection.MetadataImport.GetMemberRefProps (int memberTokenRef) inline
Definition at line 236 of file MetadataImport.cs.
    {
        _GetMemberRefProps(m_metadataImport2, memberTokenRef, out var signature);
        return signature;
    }
References System.Reflection.MetadataImport._GetMemberRefProps(), and System.Reflection.MetadataImport.m_metadataImport2.
Referenced by System.Reflection.MetadataImport.GetMethodSignature(), System.Reflection.RuntimeModule.ResolveField(), System.Reflection.RuntimeModule.ResolveMember(), System.Reflection.RuntimeModule.ResolveMethod(), and System.Reflection.RuntimeModule.ResolveSignature().