Terraria: System.Reflection.MetadataImport.IsValidToken
IsValidToken()
bool System.Reflection.MetadataImport.IsValidToken (int token) inline
Definition at line 302 of file MetadataImport.cs.
    {
        return _IsValidToken(m_metadataImport2, token);
    }
References System.Reflection.MetadataImport._IsValidToken(), and System.Reflection.MetadataImport.m_metadataImport2.
Referenced by System.Reflection.RuntimeModule.ResolveField(), System.Reflection.RuntimeModule.ResolveLiteralField(), System.Reflection.RuntimeModule.ResolveMember(), System.Reflection.RuntimeModule.ResolveSignature(), and System.Reflection.RuntimeModule.ResolveString().