Terraria: System.Linq.Expressions.IParameterProvider.GetParameter
GetParameter()
ParameterExpression System.Linq.Expressions.IParameterProvider.GetParameter (int index)
Implemented in System.Linq.Expressions.Expression0< TDelegate >, System.Linq.Expressions.Expression1< TDelegate >, System.Linq.Expressions.Expression2< TDelegate >, System.Linq.Expressions.Expression3< TDelegate >, System.Linq.Expressions.ExpressionN< TDelegate >, System.Linq.Expressions.LambdaExpression, and System.Linq.Expressions.LambdaExpression.
Referenced by System.Dynamic.Utils.ListParameterProvider.GetElement(), System.Linq.Expressions.Compiler.ParameterList.GetEnumerator(), System.Linq.Expressions.Compiler.ParameterProviderExtensions.IndexOf(), and System.Dynamic.Utils.ExpressionVisitorUtils.VisitParameters().