Terraria: System.Threading.Tasks.Dataflow.Internal.Common.StartTaskSafe
StartTaskSafe()
static Exception System.Threading.Tasks.Dataflow.Internal.Common.StartTaskSafe (Task task, TaskScheduler scheduler) inline static package
Definition at line 277 of file Common.cs.
    {
        if (scheduler == TaskScheduler.Default)
        {
            task.Start(scheduler);
            return null;
        }
        return StartTaskSafeCore(task, scheduler);
    }
References System.Threading.Tasks.TaskScheduler.Default, System.scheduler, System.Threading.Tasks.Dataflow.Internal.Common.StartTaskSafeCore(), and System.task.
Referenced by System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.CompleteBlockAsync(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.ConsumeAsyncIfNecessary(), System.Threading.Tasks.Dataflow.BufferBlock< T >.ConsumeAsyncIfNecessary(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferAsyncIfNecessary(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessary_Slow(), System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.ProcessAsyncIfNecessary_Slow(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.ProcessAsyncIfNecessary_Slow(), and System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessAsyncIfNecessary_Slow().