Terraria: System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask
GetCreationOptionsForTask()
static TaskCreationOptions System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask (bool isReplacementReplica = false) inline static package
Definition at line 267 of file Common.cs.
    {
        TaskCreationOptions taskCreationOptions = TaskCreationOptions.DenyChildAttach;
        if (isReplacementReplica)
        {
            taskCreationOptions |= TaskCreationOptions.PreferFairness;
        }
        return taskCreationOptions;
    }
Referenced by System.Threading.Tasks.Dataflow.DataflowBlock.OutputAvailableAsyncTarget< T >.CancelAndUnlink(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.Complete(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.Complete(), System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.CompleteBlockAsync(), System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.CompleteBlockIfPossible(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.CompleteBlockIfPossible(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.CompleteBlockIfPossible_Slow(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.CompleteBlockIfPossible_Slow(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CompleteBlockIfPossible_Slow(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.CompleteTargetIfPossible(), System.Threading.Tasks.Dataflow.BufferBlock< T >.CompleteTargetIfPossible(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.ConsumeAsyncIfNecessary(), System.Threading.Tasks.Dataflow.BufferBlock< T >.ConsumeAsyncIfNecessary(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferAsyncIfNecessary(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessary_Slow(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.OfferToTargetAsync(), System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.ProcessAsyncIfNecessary_Slow(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.ProcessAsyncIfNecessary_Slow(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessAsyncIfNecessary_Slow(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.RunCompletionAction(), System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.ScheduleConsumerIfNecessary(), and System.Threading.Tasks.Dataflow.DataflowBlock.TryChooseFromSource< T >().