Terraria: System.Threading.Tasks.Dataflow.Internal.Common.GetNameForDebugger
GetNameForDebugger()
static string System.Threading.Tasks.Dataflow.Internal.Common.GetNameForDebugger (IDataflowBlock block, DataflowBlockOptions options = null) inline static package
Definition at line 66 of file Common.cs.
    {
        if (block == null)
        {
            return string.Empty;
        }
        string name = block.GetType().Name;
        if (options == null)
        {
            return name;
        }
        int blockId = GetBlockId(block);
        try
        {
            return string.Format(options.NameFormat, name, blockId);
        }
        catch (Exception ex)
        {
            return ex.Message;
        }
    }
References System.Threading.Tasks.Dataflow.Internal.Common.GetBlockId(), and System.options.
Referenced by System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockCreated(), System.Threading.Tasks.Dataflow.ActionBlock< TInput >.ToString(), System.Threading.Tasks.Dataflow.BatchBlock< T >.ToString(), System.Threading.Tasks.Dataflow.BatchedJoinBlock< T1, T2, T3 >.ToString(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.ToString(), System.Threading.Tasks.Dataflow.BufferBlock< T >.ToString(), System.Threading.Tasks.Dataflow.JoinBlock< T1, T2, T3 >.ToString(), System.Threading.Tasks.Dataflow.TransformBlock< TInput, TOutput >.ToString(), System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.ToString(), and System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.ToString().