Terraria: System.Threading.Tasks.Dataflow.Internal.Common.WireCancellationToComplete
WireCancellationToComplete()
static void System.Threading.Tasks.Dataflow.Internal.Common.WireCancellationToComplete (CancellationToken cancellationToken, Task completionTask, Action< object > completeAction, object completeState) inline static package
Definition at line 93 of file Common.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            completeAction(completeState);
        }
        else if (cancellationToken.CanBeCanceled)
        {
            CancellationTokenRegistration cancellationTokenRegistration = cancellationToken.Register(completeAction, completeState);
            completionTask.ContinueWith(delegate(Task completed, object state)
            {
                ((CancellationTokenRegistration)state).Dispose();
            }, cancellationTokenRegistration, cancellationToken, GetContinuationOptions(), TaskScheduler.Default);
        }
    }
References System.cancellationToken, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Dataflow.Internal.Common.GetContinuationOptions(), and System.state.
Referenced by System.Threading.Tasks.Dataflow.ActionBlock< TInput >.ActionBlock(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlock(), System.Threading.Tasks.Dataflow.BatchedJoinBlock< T1, T2, T3 >.BatchedJoinBlock(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastBlock(), System.Threading.Tasks.Dataflow.BufferBlock< T >.BufferBlock(), System.Threading.Tasks.Dataflow.DataflowBlock.ChooseTarget< T >.ChooseTarget(), System.Threading.Tasks.Dataflow.JoinBlock< T1, T2, T3 >.JoinBlock(), System.Threading.Tasks.Dataflow.TransformBlock< TInput, TOutput >.TransformBlock(), System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.TransformManyBlock(), and System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.WriteOnceBlock().