Terraria: System.Threading.Tasks.Dataflow.Internal.Common.GetContinuationOptions
GetContinuationOptions()
static TaskContinuationOptions System.Threading.Tasks.Dataflow.Internal.Common.GetContinuationOptions (TaskContinuationOptions toInclude = TaskContinuationOptions::None) inline static package
Definition at line 262 of file Common.cs.
    {
        return toInclude | TaskContinuationOptions.DenyChildAttach;
    }
Referenced by System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlock(), System.Threading.Tasks.Dataflow.BatchedJoinBlock< T1, T2, T3 >.BatchedJoinBlock(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastBlock(), System.Threading.Tasks.Dataflow.BufferBlock< T >.BufferBlock(), System.Threading.Tasks.Dataflow.JoinBlock< T1, T2, T3 >.JoinBlock(), System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.ObserversState(), System.Threading.Tasks.Dataflow.TransformBlock< TInput, TOutput >.TransformBlock(), System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.TransformManyBlock(), System.Threading.Tasks.Dataflow.DataflowBlock.CreateChooseBranch< T >(), System.Threading.Tasks.Dataflow.DataflowBlock.OutputAvailableAsync< TOutput >(), System.Threading.Tasks.Dataflow.ActionBlock< TInput >.ProcessMessageWithTask(), System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.ProcessMessageWithTask(), System.Threading.Tasks.Dataflow.TransformBlock< TInput, TOutput >.ProcessMessageWithTask(), System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletionAsContinuation(), and System.Threading.Tasks.Dataflow.Internal.Common.WireCancellationToComplete().