Terraria: System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletionAsContinuation
PropagateCompletionAsContinuation()
static void System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletionAsContinuation (Task sourceCompletionTask, IDataflowBlock target) inline static private
Definition at line 349 of file Common.cs.
    {
        sourceCompletionTask.ContinueWith(delegate(Task task, object state)
        {
            PropagateCompletion(task, (IDataflowBlock)state, AsyncExceptionHandler);
        }, target, CancellationToken.None, GetContinuationOptions(), TaskScheduler.Default);
    }
References System.Threading.Tasks.Dataflow.Internal.Common.AsyncExceptionHandler, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Dataflow.Internal.Common.GetContinuationOptions(), System.Threading.CancellationToken.None, System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletion(), System.state, and System.task.
Referenced by System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletionOnceCompleted().