Terraria: System.Threading.Tasks.Dataflow.Internal.Common.SingleMessageHeader
SingleMessageHeader
readonly DataflowMessageHeader System.Threading.Tasks.Dataflow.Internal.Common.SingleMessageHeader = new DataflowMessageHeader(1L) static package
Definition at line 26 of file Common.cs.
Referenced by System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.OfferMessage(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.OfferToTarget(), System.Threading.Tasks.Dataflow.ActionBlock< TInput >.Post(), System.Threading.Tasks.Dataflow.DataflowBlock.Post< TInput >(), and System.Threading.Tasks.Dataflow.DataflowBlock.SendAsync< TInput >().