Terraria: System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletion
PropagateCompletion()
static void System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletion (Task sourceCompletionTask, IDataflowBlock target, Action< Exception > exceptionHandler) inline static package
Definition at line 324 of file Common.cs.
    {
        AggregateException ex = (sourceCompletionTask.IsFaulted ? sourceCompletionTask.Exception : null);
        try
        {
            if (ex != null)
            {
                target.Fault(ex);
            }
            else
            {
                target.Complete();
            }
        }
        catch (Exception obj)
        {
            if (exceptionHandler != null)
            {
                exceptionHandler(obj);
                return;
            }
            throw;
        }
    }
References System.Threading.Tasks.Dataflow.IDataflowBlock.Complete(), System.Threading.Tasks.Dataflow.IDataflowBlock.Fault(), and System.obj.
Referenced by System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.LinkTo(), System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >.PropagateCompletion(), System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletionAsContinuation(), and System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletionOnceCompleted().