Terraria: System.Xml.Schema.XmlDateTimeConverter.ToDateTime
ToDateTime() [7/7]
override DateTime System.Xml.Schema.XmlDateTimeConverter.ToDateTime (string value) inline
Definition at line 20 of file XmlDateTimeConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        return base.TypeCode switch
        {
            XmlTypeCode.Date => XmlBaseConverter.StringToDate(value),
            XmlTypeCode.Time => XmlBaseConverter.StringToTime(value),
            XmlTypeCode.GDay => XmlBaseConverter.StringToGDay(value),
            XmlTypeCode.GMonth => XmlBaseConverter.StringToGMonth(value),
            XmlTypeCode.GMonthDay => XmlBaseConverter.StringToGMonthDay(value),
            XmlTypeCode.GYear => XmlBaseConverter.StringToGYear(value),
            XmlTypeCode.GYearMonth => XmlBaseConverter.StringToGYearMonth(value),
            _ => XmlBaseConverter.StringToDateTime(value),
        };
    }
References System.Xml.Dictionary, System.Xml.Schema.XmlBaseConverter.StringToDate(), System.Xml.Schema.XmlBaseConverter.StringToDateTime(), System.Xml.Schema.XmlBaseConverter.StringToGDay(), System.Xml.Schema.XmlBaseConverter.StringToGMonth(), System.Xml.Schema.XmlBaseConverter.StringToGMonthDay(), System.Xml.Schema.XmlBaseConverter.StringToGYear(), System.Xml.Schema.XmlBaseConverter.StringToGYearMonth(), System.Xml.Schema.XmlBaseConverter.StringToTime(), and System.value.