Terraria: System.ComponentModel.BindingList.SetItem
SetItem()
override void System.ComponentModel.BindingList< T >.SetItem (int index, T item) inline protected virtual
Reimplemented from System.Collections.ObjectModel.Collection< T >.
Definition at line 305 of file BindingList.cs.
    {
        if (raiseItemChangedEvents)
        {
            UnhookPropertyChanged(base[index]);
        }
        base.SetItem(index, item);
        if (raiseItemChangedEvents)
        {
            HookPropertyChanged(item);
        }
        FireListChanged(ListChangedType.ItemChanged, index);
    }
References System.ComponentModel.BindingList< T >.FireListChanged(), System.ComponentModel.BindingList< T >.HookPropertyChanged(), System.index, System.item, System.ComponentModel.BindingList< T >.raiseItemChangedEvents, and System.ComponentModel.BindingList< T >.UnhookPropertyChanged().