Terraria: System.Xml.Schema.XmlDateTimeConverter.ChangeType
ChangeType() [8/9]
override object System.Xml.Schema.XmlDateTimeConverter.ChangeType (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline
Definition at line 241 of file XmlDateTimeConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        Type type = value.GetType();
        if (destinationType == XmlBaseConverter.ObjectType)
        {
            destinationType = base.DefaultClrType;
        }
        if (destinationType == XmlBaseConverter.DateTimeType)
        {
            return ToDateTime(value);
        }
        if (destinationType == XmlBaseConverter.DateTimeOffsetType)
        {
            return ToDateTimeOffset(value);
        }
        if (destinationType == XmlBaseConverter.StringType)
        {
            return ToString(value, nsResolver);
        }
        if (destinationType == XmlBaseConverter.XmlAtomicValueType)
        {
            if (type == XmlBaseConverter.DateTimeType)
            {
                return new XmlAtomicValue(base.SchemaType, (DateTime)value);
            }
            if (type == XmlBaseConverter.DateTimeOffsetType)
            {
                return new XmlAtomicValue(base.SchemaType, (DateTimeOffset)value);
            }
            if (type == XmlBaseConverter.StringType)
            {
                return new XmlAtomicValue(base.SchemaType, (string)value);
            }
            if (type == XmlBaseConverter.XmlAtomicValueType)
            {
                return (XmlAtomicValue)value;
            }
        }
        if (destinationType == XmlBaseConverter.XPathItemType)
        {
            if (type == XmlBaseConverter.DateTimeType)
            {
                return new XmlAtomicValue(base.SchemaType, (DateTime)value);
            }
            if (type == XmlBaseConverter.DateTimeOffsetType)
            {
                return new XmlAtomicValue(base.SchemaType, (DateTimeOffset)value);
            }
            if (type == XmlBaseConverter.StringType)
            {
                return new XmlAtomicValue(base.SchemaType, (string)value);
            }
            if (type == XmlBaseConverter.XmlAtomicValueType)
            {
                return (XmlAtomicValue)value;
            }
        }
        return ChangeListType(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.ChangeListType(), System.Xml.Schema.XmlBaseConverter.DateTimeOffsetType, System.Xml.Schema.XmlBaseConverter.DateTimeType, System.Xml.Dictionary, System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.ObjectType, System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlDateTimeConverter.ToDateTime(), System.Xml.Schema.XmlDateTimeConverter.ToDateTimeOffset(), System.ToString, System.type, System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, and System.Xml.Schema.XmlBaseConverter.XPathItemType.