Terraria: System.ComponentModel.BindingList.FireListChanged
FireListChanged()
void System.ComponentModel.BindingList< T >.FireListChanged (ListChangedType type, int index) inline private
Definition at line 255 of file BindingList.cs.
    {
        if (raiseListChangedEvents)
        {
            OnListChanged(new ListChangedEventArgs(type, index));
        }
    }
References System.index, System.ComponentModel.BindingList< T >.OnListChanged(), System.ComponentModel.BindingList< T >.raiseListChangedEvents, and System.type.
Referenced by System.ComponentModel.BindingList< T >.ClearItems(), System.ComponentModel.BindingList< T >.InsertItem(), System.ComponentModel.BindingList< T >.RemoveItem(), System.ComponentModel.BindingList< T >.ResetBindings(), System.ComponentModel.BindingList< T >.ResetItem(), and System.ComponentModel.BindingList< T >.SetItem().