Terraria: System.ComponentModel.BindingList.RemoveItem
RemoveItem()
override void System.ComponentModel.BindingList< T >.RemoveItem (int index) inline protected virtual
Reimplemented from System.Collections.ObjectModel.Collection< T >.
Definition at line 289 of file BindingList.cs.
    {
        if (!allowRemove && (addNewPos < 0 || addNewPos != index))
        {
            throw new NotSupportedException();
        }
        EndNew(addNewPos);
        if (raiseItemChangedEvents)
        {
            UnhookPropertyChanged(base[index]);
        }
        base.RemoveItem(index);
        FireListChanged(ListChangedType.ItemDeleted, index);
    }
References System.ComponentModel.BindingList< T >.addNewPos, System.ComponentModel.BindingList< T >.allowRemove, System.ComponentModel.BindingList< T >.EndNew(), System.ComponentModel.BindingList< T >.FireListChanged(), System.index, System.ComponentModel.BindingList< T >.raiseItemChangedEvents, and System.ComponentModel.BindingList< T >.UnhookPropertyChanged().
Referenced by System.ComponentModel.BindingList< T >.CancelNew().