Terraria: System.Xml.Schema.XmlDateTimeConverter.ToDateTimeOffset
ToDateTimeOffset() [2/3]
override DateTimeOffset System.Xml.Schema.XmlDateTimeConverter.ToDateTimeOffset (object value) inline
Definition at line 89 of file XmlDateTimeConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        Type type = value.GetType();
        if (type == XmlBaseConverter.DateTimeType)
        {
            return ToDateTimeOffset((DateTime)value);
        }
        if (type == XmlBaseConverter.DateTimeOffsetType)
        {
            return (DateTimeOffset)value;
        }
        if (type == XmlBaseConverter.StringType)
        {
            return ToDateTimeOffset((string)value);
        }
        if (type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAsDateTime;
        }
        return (DateTimeOffset)ChangeListType(value, XmlBaseConverter.DateTimeOffsetType, null);
    }
References System.Xml.Schema.XmlBaseConverter.ChangeListType(), System.Xml.Schema.XmlBaseConverter.DateTimeOffsetType, System.Xml.Schema.XmlBaseConverter.DateTimeType, System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlDateTimeConverter.ToDateTimeOffset(), System.type, System.value, and System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType.