Terraria: System.Xml.Schema.XmlDateTimeConverter.ToString
ToString() [2/10]
override string System.Xml.Schema.XmlDateTimeConverter.ToString (DateTime value) inline
Definition at line 115 of file XmlDateTimeConverter.cs.
    {
        return base.TypeCode switch
        {
            XmlTypeCode.Date => XmlBaseConverter.DateToString(value),
            XmlTypeCode.Time => XmlBaseConverter.TimeToString(value),
            XmlTypeCode.GDay => XmlBaseConverter.GDayToString(value),
            XmlTypeCode.GMonth => XmlBaseConverter.GMonthToString(value),
            XmlTypeCode.GMonthDay => XmlBaseConverter.GMonthDayToString(value),
            XmlTypeCode.GYear => XmlBaseConverter.GYearToString(value),
            XmlTypeCode.GYearMonth => XmlBaseConverter.GYearMonthToString(value),
            _ => XmlBaseConverter.DateTimeToString(value),
        };
    }
References System.Xml.Schema.XmlBaseConverter.DateTimeToString(), System.Xml.Schema.XmlBaseConverter.DateToString(), System.Xml.Dictionary, System.Xml.Schema.XmlBaseConverter.GDayToString(), System.Xml.Schema.XmlBaseConverter.GMonthDayToString(), System.Xml.Schema.XmlBaseConverter.GMonthToString(), System.Xml.Schema.XmlBaseConverter.GYearMonthToString(), System.Xml.Schema.XmlBaseConverter.GYearToString(), System.Xml.Schema.XmlBaseConverter.TimeToString(), and System.value.