Terraria: System.ComponentModel.BindingList.Child_PropertyChanged
Child_PropertyChanged()
void System.ComponentModel.BindingList< T >.Child_PropertyChanged (object sender, PropertyChangedEventArgs e) inline private
Definition at line 419 of file BindingList.cs.
    {
        if (!RaiseListChangedEvents)
        {
            return;
        }
        if (sender == null || e == null || string.IsNullOrEmpty(e.PropertyName))
        {
            ResetBindings();
            return;
        }
        T val;
        try
        {
            val = (T)sender;
        }
        catch (InvalidCastException)
        {
            ResetBindings();
            return;
        }
        int num = _lastChangeIndex;
        if (num < 0 || num >= base.Count || !base[num].Equals(val))
        {
            num = (_lastChangeIndex = IndexOf(val));
        }
        if (num == -1)
        {
            UnhookPropertyChanged(val);
            ResetBindings();
            return;
        }
        if (_itemTypeProperties == null)
        {
            _itemTypeProperties = TypeDescriptor.GetProperties(typeof(T));
        }
        PropertyDescriptor propDesc = _itemTypeProperties.Find(e.PropertyName, ignoreCase: true);
        ListChangedEventArgs e2 = new ListChangedEventArgs(ListChangedType.ItemChanged, num, propDesc);
        OnListChanged(e2);
    }
References System.ComponentModel.BindingList< T >._itemTypeProperties, System.ComponentModel.BindingList< T >._lastChangeIndex, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.ComponentModel.PropertyDescriptorCollection.Find(), System.ComponentModel.TypeDescriptor.GetProperties(), System.Collections.Generic.IList< T >.IndexOf(), System.ComponentModel.BindingList< T >.OnListChanged(), System.ComponentModel.PropertyChangedEventArgs.PropertyName, System.ComponentModel.BindingList< T >.RaiseListChangedEvents, System.ComponentModel.BindingList< T >.ResetBindings(), System.T, and System.ComponentModel.BindingList< T >.UnhookPropertyChanged().
Referenced by System.ComponentModel.BindingList< T >.HookPropertyChanged().