Terraria: System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.DeriveSecretAgreementHandle
DeriveSecretAgreementHandle()
SafeNCryptSecretHandle System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.DeriveSecretAgreementHandle (ECDiffieHellmanPublicKey otherPartyPublicKey) inline private
Definition at line 115 of file ECDiffieHellmanImplementation.cs.
        {
            if (otherPartyPublicKey == null)
            {
                throw new ArgumentNullException("otherPartyPublicKey");
            }
            ECParameters parameters = otherPartyPublicKey.ExportParameters();
            using ECDiffieHellmanCng eCDiffieHellmanCng = (ECDiffieHellmanCng)ECDiffieHellman.Create(parameters);
            using SafeNCryptKeyHandle safeNCryptKeyHandle = eCDiffieHellmanCng.GetDuplicatedKeyHandle();
            string propertyAsString = CngKeyLite.GetPropertyAsString(safeNCryptKeyHandle, "Algorithm Group", CngPropertyOptions.None);
            if (propertyAsString != "ECDH")
            {
                throw new ArgumentException(System.SR.Cryptography_ArgECDHRequiresECDHKey, "otherPartyPublicKey");
            }
            if (CngKeyLite.GetKeyLength(safeNCryptKeyHandle) != KeySize)
            {
                throw new ArgumentException(System.SR.Cryptography_ArgECDHKeySizeMismatch, "otherPartyPublicKey");
            }
            using SafeNCryptKeyHandle privateKey = GetDuplicatedKeyHandle();
            return global::Interop.NCrypt.DeriveSecretAgreement(privateKey, safeNCryptKeyHandle);
        }
References System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ECDiffieHellmanCng(), System.Security.Cryptography.ECDiffieHellman.Create(), System.SR.Cryptography_ArgECDHKeySizeMismatch, System.SR.Cryptography_ArgECDHRequiresECDHKey, System.Security.Cryptography.ECDiffieHellmanPublicKey.ExportParameters(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.GetDuplicatedKeyHandle(), System.Security.Cryptography.CngKeyLite.GetKeyLength(), System.Security.Cryptography.CngKeyLite.GetPropertyAsString(), and System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.KeySize.
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.DeriveKeyFromHash(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.DeriveKeyFromHmac(), and System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.DeriveKeyTls().