Terraria: System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.GenerateKey
GenerateKey()
override void System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.GenerateKey (ECCurve curve) inline virtual
Reimplemented from System.Security.Cryptography.ECDiffieHellman.
Definition at line 142 of file ECDiffieHellmanImplementation.cs.
        {
            _key.GenerateKey(curve);
            ForceSetKeySize(_key.KeySize);
        }
References System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng._key, System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ForceSetKeySize(), System.Security.Cryptography.ECCngKey.GenerateKey(), and System.Security.Cryptography.ECCngKey.KeySize.
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ECDiffieHellmanCng().