Terraria: System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ThrowIfDisposed
ThrowIfDisposed()
void System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ThrowIfDisposed () inline private
Definition at line 52 of file ECDiffieHellmanImplementation.cs.
        {
            _key.ThrowIfDisposed();
        }
References System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng._key, and System.Security.Cryptography.ECCngKey.ThrowIfDisposed().
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportParameters(), and System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportPkcs8PrivateKey().