Terraria: System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportParameters
ImportParameters()
override void System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportParameters (ECParameters parameters) inline virtual
Reimplemented from System.Security.Cryptography.ECDiffieHellman.
Definition at line 225 of file ECDiffieHellmanImplementation.cs.
        {
            parameters.Validate();
            ThrowIfDisposed();
            ECCurve curve = parameters.Curve;
            bool flag = parameters.D != null;
            bool flag2 = parameters.Q.X != null && parameters.Q.Y != null;
            if (curve.IsPrime)
            {
                if (!flag2 && flag)
                {
                    byte[] array = new byte[parameters.D.Length];
                    ECParameters parameters2 = parameters;
                    parameters2.Q.X = array;
                    parameters2.Q.Y = array;
                    byte[] primeCurveBlob = ECCng.GetPrimeCurveBlob(ref parameters2, ecdh: true);
                    ImportFullKeyBlob(primeCurveBlob, includePrivateParameters: true);
                }
                else
                {
                    byte[] primeCurveBlob2 = ECCng.GetPrimeCurveBlob(ref parameters, ecdh: true);
                    ImportFullKeyBlob(primeCurveBlob2, flag);
                }
                return;
            }
            if (curve.IsNamed)
            {
                if (string.IsNullOrEmpty(curve.Oid.FriendlyName))
                {
                    throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_InvalidCurveOid, curve.Oid.Value));
                }
                if (!flag2 && flag)
                {
                    byte[] array2 = new byte[parameters.D.Length];
                    ECParameters parameters3 = parameters;
                    parameters3.Q.X = array2;
                    parameters3.Q.Y = array2;
                    byte[] namedCurveBlob = ECCng.GetNamedCurveBlob(ref parameters3, ecdh: true);
                    ImportKeyBlob(namedCurveBlob, curve.Oid.FriendlyName, includePrivateParameters: true);
                }
                else
                {
                    byte[] namedCurveBlob2 = ECCng.GetNamedCurveBlob(ref parameters, ecdh: true);
                    ImportKeyBlob(namedCurveBlob2, curve.Oid.FriendlyName, flag);
                }
                return;
            }
            throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_CurveNotSupported, curve.CurveType.ToString()));
        }
References System.array, System.SR.Cryptography_CurveNotSupported, System.SR.Cryptography_InvalidCurveOid, System.Security.Cryptography.ECParameters.Curve, System.Security.Cryptography.ECCurve.CurveType, System.Security.Cryptography.ECParameters.D, System.SR.Format(), System.Security.Cryptography.Oid.FriendlyName, System.Security.Cryptography.ECCng.GetNamedCurveBlob(), System.Security.Cryptography.ECCng.GetPrimeCurveBlob(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportFullKeyBlob(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportKeyBlob(), System.Security.Cryptography.ECCurve.IsNamed, System.Security.Cryptography.ECCurve.IsPrime, System.Security.Cryptography.ECCurve.Oid, System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ThrowIfDisposed(), System.Security.Cryptography.ECParameters.Validate(), and System.Security.Cryptography.Oid.Value.