Terraria: System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng._key
_key
readonly ECCngKey System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng._key = new ECCngKey("ECDH", "ECDiffieHellman") private
Definition at line 9 of file ECDiffieHellmanImplementation.cs.
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.AcceptImport(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.Dispose(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.DisposeKey(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.GenerateKey(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.GetCurveName(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.GetDuplicatedKeyHandle(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportFullKeyBlob(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportKeyBlob(), and System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ThrowIfDisposed().