Terraria: System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.TryExportEncryptedPkcs8PrivateKey
TryExportEncryptedPkcs8PrivateKey() [2/2]
override bool System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.TryExportEncryptedPkcs8PrivateKey (ReadOnlySpan< char > password, PbeParameters pbeParameters, Span< byte > destination, out int bytesWritten) inline virtual
Reimplemented from System.Security.Cryptography.ECDiffieHellman.
Definition at line 390 of file ECDiffieHellmanImplementation.cs.
        {
            if (pbeParameters == null)
            {
                throw new ArgumentNullException("pbeParameters");
            }
            PasswordBasedEncryption.ValidatePbeParameters(pbeParameters, password, ReadOnlySpan<byte>.Empty);
            if (CngPkcs8.IsPlatformScheme(pbeParameters))
            {
                return TryExportEncryptedPkcs8(password, pbeParameters.IterationCount, destination, out bytesWritten);
            }
            return CngPkcs8.TryExportEncryptedPkcs8PrivateKey(this, password, pbeParameters, destination, out bytesWritten);
        }
References System.destination, System.Security.Cryptography.CngPkcs8.IsPlatformScheme(), System.Security.Cryptography.PbeParameters.IterationCount, System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.TryExportEncryptedPkcs8(), System.Security.Cryptography.CngPkcs8.TryExportEncryptedPkcs8PrivateKey(), and System.Security.Cryptography.PasswordBasedEncryption.ValidatePbeParameters().