Terraria: SurfaceBiomeShader.ProcessHighDetail
ProcessHighDetail()
void SurfaceBiomeShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
     {
         Vector4 value = _primaryColor * _surfaceColor;
         Vector4 value2 = _secondaryColor * _surfaceColor;
         for (int i = 0; i < fragment.Count; i++)
         {
             Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
             Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
             float amount = (float)Math.Sin(canvasPositionOfIndex.X * 1.5f + canvasPositionOfIndex.Y + time) * 0.5f + 0.5f;
             Vector4 value3 = Vector4.Lerp(value, value2, amount);
             float dynamicNoise = NoiseHelper.GetDynamicNoise(gridPositionOfIndex.X, gridPositionOfIndex.Y, time / 60f);
             dynamicNoise = Math.Max(0f, 1f - dynamicNoise * 20f);
             dynamicNoise *= 1f - _surfaceColor.X;
             value3 = Vector4.Max(value3, new Vector4(dynamicNoise * _starVisibility));
             fragment.SetColor(i, value3);
         }
     }
References _primaryColor, _secondaryColor, _starVisibility, _surfaceColor, Fragment.Count, Fragment.GetCanvasPositionOfIndex(), NoiseHelper.GetDynamicNoise(), Fragment.GetGridPositionOfIndex(), and Fragment.SetColor().