Terraria: System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ExportParameters
ExportParameters()
override ECParameters System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ExportParameters (bool includePrivateParameters) inline virtual
Reimplemented from System.Security.Cryptography.ECDiffieHellman.
Definition at line 290 of file ECDiffieHellmanImplementation.cs.
        {
            ECParameters ecParams = default(ECParameters);
            string oidValue;
            string curveName = GetCurveName(out oidValue);
            byte[] array = null;
            try
            {
                if (string.IsNullOrEmpty(curveName))
                {
                    array = ExportFullKeyBlob(includePrivateParameters);
                    ECCng.ExportPrimeCurveParameters(ref ecParams, array, includePrivateParameters);
                }
                else
                {
                    array = ExportKeyBlob(includePrivateParameters);
                    ECCng.ExportNamedCurveParameters(ref ecParams, array, includePrivateParameters);
                    ecParams.Curve = ECCurve.CreateFromOid(new Oid(oidValue, curveName));
                }
                return ecParams;
            }
            finally
            {
                if (array != null)
                {
                    Array.Clear(array);
                }
            }
        }
References System.array, System.Array.Clear(), System.Security.Cryptography.ECCurve.CreateFromOid(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ExportFullKeyBlob(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ExportKeyBlob(), System.Security.Cryptography.ECCng.ExportNamedCurveParameters(), System.Security.Cryptography.ECCng.ExportPrimeCurveParameters(), and System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.GetCurveName().