Terraria: System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ExportEncryptedPkcs8PrivateKey
ExportEncryptedPkcs8PrivateKey() [2/2]
override byte[] System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ExportEncryptedPkcs8PrivateKey (ReadOnlySpan< char > password, PbeParameters pbeParameters) inline virtual
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Definition at line 366 of file ECDiffieHellmanImplementation.cs.
        {
            if (pbeParameters == null)
            {
                throw new ArgumentNullException("pbeParameters");
            }
            PasswordBasedEncryption.ValidatePbeParameters(pbeParameters, password, ReadOnlySpan<byte>.Empty);
            if (CngPkcs8.IsPlatformScheme(pbeParameters))
            {
                return ExportEncryptedPkcs8(password, pbeParameters.IterationCount);
            }
            return CngPkcs8.ExportEncryptedPkcs8PrivateKey(this, password, pbeParameters);
        }
References System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ExportEncryptedPkcs8(), System.Security.Cryptography.CngPkcs8.ExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.CngPkcs8.IsPlatformScheme(), System.Security.Cryptography.PbeParameters.IterationCount, and System.Security.Cryptography.PasswordBasedEncryption.ValidatePbeParameters().