Terraria: System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportFullKeyBlob
ImportFullKeyBlob()
void System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportFullKeyBlob (byte[] ecfullKeyBlob, bool includePrivateParameters) inline private
Definition at line 57 of file ECDiffieHellmanImplementation.cs.
        {
            string blobType = (includePrivateParameters ? "ECCFULLPRIVATEBLOB" : "ECCFULLPUBLICBLOB");
            SafeNCryptKeyHandle keyHandle = CngKeyLite.ImportKeyBlob(blobType, ecfullKeyBlob);
            _key.SetHandle(keyHandle, "ECDH");
            ForceSetKeySize(_key.KeySize);
        }
References System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng._key, System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ForceSetKeySize(), System.Security.Cryptography.CngKeyLite.ImportKeyBlob(), System.Security.Cryptography.ECCngKey.KeySize, and System.Security.Cryptography.ECCngKey.SetHandle().
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportParameters().