Terraria: System.Security.Cryptography.CryptoStream.DisposeAsyncCore
DisposeAsyncCore()
async ValueTask System.Security.Cryptography.CryptoStream.DisposeAsyncCore () inline private
Definition at line 694 of file CryptoStream.cs.
    {
        _ = 1;
        try
        {
            if (!_finalBlockTransformed)
            {
                await FlushFinalBlockAsync(useAsync: true, default(CancellationToken)).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (!_leaveOpen)
            {
                await _stream.DisposeAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        finally
        {
            _finalBlockTransformed = true;
            if (_inputBuffer != null)
            {
                Array.Clear(_inputBuffer);
            }
            if (_outputBuffer != null)
            {
                Array.Clear(_outputBuffer);
            }
            _inputBuffer = null;
            _outputBuffer = null;
            _canRead = false;
            _canWrite = false;
        }
    }
References System.Security.Cryptography.CryptoStream._canRead, System.Security.Cryptography.CryptoStream._canWrite, System.Security.Cryptography.CryptoStream._finalBlockTransformed, System.Security.Cryptography.CryptoStream._inputBuffer, System.Security.Cryptography.CryptoStream._leaveOpen, System.Security.Cryptography.CryptoStream._outputBuffer, System.Security.Cryptography.CryptoStream._stream, System.Array.Clear(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.IO.Stream.DisposeAsync(), and System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync().
Referenced by System.Security.Cryptography.CryptoStream.DisposeAsync().