Terraria: System.Security.Cryptography.CryptoStream.CheckWriteArguments
CheckWriteArguments()
void System.Security.Cryptography.CryptoStream.CheckWriteArguments (byte[] buffer, int offset, int count) inline private
Definition at line 439 of file CryptoStream.cs.
    {
        Stream.ValidateBufferArguments(buffer, offset, count);
        if (!CanWrite)
        {
            throw new NotSupportedException(System.SR.NotSupported_UnwritableStream);
        }
    }
References System.buffer, System.Security.Cryptography.CryptoStream.CanWrite, System.count, System.SR.NotSupported_UnwritableStream, System.offset, and System.IO.Stream.ValidateBufferArguments().
Referenced by System.Security.Cryptography.CryptoStream.Write(), and System.Security.Cryptography.CryptoStream.WriteAsync().