Terraria: System.Security.Cryptography.CryptoStream.CopyToAsyncInternal
CopyToAsyncInternal()
async Task System.Security.Cryptography.CryptoStream.CopyToAsyncInternal (Stream destination, int bufferSize, CancellationToken cancellationToken) inline private
Definition at line 588 of file CryptoStream.cs.
    {
        byte[] rentedBuffer = ArrayPool<byte>.Shared.Rent(bufferSize);
        GCHandle pinHandle = GCHandle.Alloc(rentedBuffer, GCHandleType.Pinned);
        try
        {
            int bytesRead;
            do
            {
                bytesRead = await ReadAsync(rentedBuffer.AsMemory(0, bufferSize), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                await destination.WriteAsync(rentedBuffer.AsMemory(0, bytesRead), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            while (bytesRead > 0);
        }
        finally
        {
            CryptographicOperations.ZeroMemory(rentedBuffer.AsSpan(0, bufferSize));
            pinHandle.Free();
        }
        ArrayPool<byte>.Shared.Return(rentedBuffer);
    }
References System.Runtime.InteropServices.GCHandle.Alloc(), System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.destination, System.Runtime.InteropServices.GCHandle.Free(), System.Security.Cryptography.CryptoStream.ReadAsync(), System.Buffers.ArrayPool< T >.Shared, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().
Referenced by System.Security.Cryptography.CryptoStream.CopyToAsync().