Terraria: System.Security.Cryptography.CryptoStream.Write
Write() [1/2]
override void System.Security.Cryptography.CryptoStream.Write (byte[] buffer, int offset, int count) inline
Definition at line 433 of file CryptoStream.cs.
    {
        CheckWriteArguments(buffer, offset, count);
        WriteAsyncCore(buffer.AsMemory(offset, count), default(CancellationToken), useAsync: false).AsTask().GetAwaiter().GetResult();
    }
References System.buffer, System.Security.Cryptography.CryptoStream.CheckWriteArguments(), System.count, System.Threading.Tasks.ValueTask< TResult >.GetAwaiter(), System.offset, and System.Security.Cryptography.CryptoStream.WriteAsyncCore().
Referenced by System.Security.Cryptography.PasswordDeriveBytes.ComputeBytes(), and System.Security.Cryptography.PasswordDeriveBytes.HashPrefix().