Terraria: System.Security.Cryptography.CryptoStream.WriteAsyncInternal
WriteAsyncInternal()
async ValueTask System.Security.Cryptography.CryptoStream.WriteAsyncInternal (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline private
Definition at line 410 of file CryptoStream.cs.
    {
        await AsyncActiveSemaphore.WaitAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        try
        {
            await WriteAsyncCore(buffer, cancellationToken, useAsync: true).ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            _lazyAsyncActiveSemaphore.Release();
        }
    }
References System.Security.Cryptography.CryptoStream._lazyAsyncActiveSemaphore, System.Security.Cryptography.CryptoStream.AsyncActiveSemaphore, System.buffer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.SemaphoreSlim.Release(), System.Threading.SemaphoreSlim.WaitAsync(), and System.Security.Cryptography.CryptoStream.WriteAsyncCore().
Referenced by System.Security.Cryptography.CryptoStream.WriteAsync(), and System.Security.Cryptography.CryptoStream.WriteAsync().