Terraria: System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync
FlushFinalBlockAsync() [1/2]
async ValueTask System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync (bool useAsync, CancellationToken cancellationToken) inline private
Definition at line 129 of file CryptoStream.cs.
    {
        if (_finalBlockTransformed)
        {
            throw new NotSupportedException(System.SR.Cryptography_CryptoStream_FlushFinalBlockTwice);
        }
        _finalBlockTransformed = true;
        if (_canWrite)
        {
            byte[] array = _transform.TransformFinalBlock(_inputBuffer, 0, _inputBufferIndex);
            if (useAsync)
            {
                await _stream.WriteAsync(new ReadOnlyMemory<byte>(array), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            else
            {
                _stream.Write(array, 0, array.Length);
            }
        }
        if (_stream is CryptoStream cryptoStream)
        {
            if (!cryptoStream.HasFlushedFinalBlock)
            {
                await cryptoStream.FlushFinalBlockAsync(useAsync, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        else if (useAsync)
        {
            await _stream.FlushAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            _stream.Flush();
        }
        if (_inputBuffer != null)
        {
            Array.Clear(_inputBuffer);
        }
        if (_outputBuffer != null)
        {
            Array.Clear(_outputBuffer);
        }
    }
References System.Security.Cryptography.CryptoStream._canWrite, System.Security.Cryptography.CryptoStream._finalBlockTransformed, System.Security.Cryptography.CryptoStream._inputBuffer, System.Security.Cryptography.CryptoStream._inputBufferIndex, System.Security.Cryptography.CryptoStream._outputBuffer, System.Security.Cryptography.CryptoStream._stream, System.Security.Cryptography.CryptoStream._transform, System.array, System.cancellationToken, System.Array.Clear(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.SR.Cryptography_CryptoStream_FlushFinalBlockTwice, System.IO.Stream.Flush(), System.IO.Stream.FlushAsync(), System.Security.Cryptography.ICryptoTransform.TransformFinalBlock(), System.IO.Stream.Write(), and System.IO.Stream.WriteAsync().