Terraria: System.Security.Cryptography.CryptoStream.CheckCopyToArguments
CheckCopyToArguments()
void System.Security.Cryptography.CryptoStream.CheckCopyToArguments (Stream destination, int bufferSize) inline private
Definition at line 610 of file CryptoStream.cs.
    {
        if (destination == null)
        {
            throw new ArgumentNullException("destination");
        }
        EnsureNotDisposed(destination, "destination");
        if (!destination.CanWrite)
        {
            throw new NotSupportedException(System.SR.NotSupported_UnwritableStream);
        }
        if (bufferSize <= 0)
        {
            throw new ArgumentOutOfRangeException("bufferSize", System.SR.ArgumentOutOfRange_NeedPosNum);
        }
        if (!CanRead)
        {
            throw new NotSupportedException(System.SR.NotSupported_UnreadableStream);
        }
    }
References System.SR.ArgumentOutOfRange_NeedPosNum, System.Security.Cryptography.CryptoStream.CanRead, System.destination, System.Security.Cryptography.CryptoStream.EnsureNotDisposed(), System.SR.NotSupported_UnreadableStream, and System.SR.NotSupported_UnwritableStream.
Referenced by System.Security.Cryptography.CryptoStream.CopyTo(), and System.Security.Cryptography.CryptoStream.CopyToAsync().