Terraria: System.Security.Cryptography.CryptoStream.WriteAsync
WriteAsync() [2/3]
override Task System.Security.Cryptography.CryptoStream.WriteAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 395 of file CryptoStream.cs.
    {
        CheckWriteArguments(buffer, offset, count);
        return WriteAsyncInternal(buffer.AsMemory(offset, count), cancellationToken).AsTask();
    }
References System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.buffer, System.cancellationToken, System.Security.Cryptography.CryptoStream.CheckWriteArguments(), System.count, System.offset, and System.Security.Cryptography.CryptoStream.WriteAsyncInternal().
Referenced by System.Security.Cryptography.CryptoStream.BeginWrite().