Terraria: System.Xml.Serialization.ModelScope.GetTypeModel
GetTypeModel() [2/2]
TypeModel System.Xml.Serialization.ModelScope.GetTypeModel (Type type, bool directReference) inline package
Definition at line 28 of file ModelScope.cs.
    {
        if (_models.TryGetValue(type, out var value))
        {
            return value;
        }
        TypeDesc typeDesc = _typeScope.GetTypeDesc(type, null, directReference);
        switch (typeDesc.Kind)
        {
        case TypeKind.Enum:
            value = new EnumModel(type, typeDesc, this);
            break;
        case TypeKind.Primitive:
            value = new PrimitiveModel(type, typeDesc, this);
            break;
        case TypeKind.Array:
        case TypeKind.Collection:
        case TypeKind.Enumerable:
            value = new ArrayModel(type, typeDesc, this);
            break;
        case TypeKind.Root:
        case TypeKind.Struct:
        case TypeKind.Class:
            value = new StructModel(type, typeDesc, this);
            break;
        default:
            if (!typeDesc.IsSpecial)
            {
                throw new NotSupportedException(System.SR.Format(System.SR.XmlUnsupportedTypeKind, type.FullName));
            }
            value = new SpecialModel(type, typeDesc, this);
            break;
        }
        _models.Add(type, value);
        return value;
    }
References System.Xml.Serialization.ModelScope._models, System.Xml.Serialization.ModelScope._typeScope, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.SR.Format(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.type, System.value, and System.SR.XmlUnsupportedTypeKind.