Terraria: System.Xml.Serialization.ModelScope.GetArrayModel
GetArrayModel()
ArrayModel System.Xml.Serialization.ModelScope.GetArrayModel (Type type) inline package
Definition at line 66 of file ModelScope.cs.
    {
        if (!_arrayModels.TryGetValue(type, out var value))
        {
            value = GetTypeModel(type);
            if (!(value is ArrayModel))
            {
                TypeDesc arrayTypeDesc = _typeScope.GetArrayTypeDesc(type);
                value = new ArrayModel(type, arrayTypeDesc, this);
            }
            _arrayModels.Add(type, value);
        }
        return (ArrayModel)value;
    }
References System.Xml.Serialization.ModelScope._arrayModels, System.Xml.Serialization.ModelScope._typeScope, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.TypeScope.GetArrayTypeDesc(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.type, and System.value.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping().