Terraria: System.Xml.Serialization.ModelScope.GetTypeModel
GetTypeModel() [1/2]
TypeModel System.Xml.Serialization.ModelScope.GetTypeModel (Type type) inline package
Definition at line 22 of file ModelScope.cs.
    {
        return GetTypeModel(type, directReference: true);
    }
References System.Xml.Serialization.ModelScope.GetTypeModel(), and System.type.
Referenced by System.Xml.Serialization.XmlReflectionImporter.CreateArrayElementsFromAttributes(), System.Xml.Serialization.ModelScope.GetArrayModel(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Xml.Serialization.SoapReflectionImporter.ImportAccessorMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(), System.Xml.Serialization.SoapReflectionImporter.IncludeType(), System.Xml.Serialization.XmlReflectionImporter.IncludeType(), System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(), and System.Xml.Serialization.SoapReflectionImporter.InitializeStructMembers().