Terraria: System.Diagnostics.Metrics.AggregationManager.AggregationManager
AggregationManager()
System.Diagnostics.Metrics.AggregationManager.AggregationManager (int maxTimeSeries, int maxHistograms, Action< Instrument, LabeledAggregationStatistics > collectMeasurement, Action< DateTime, DateTime > beginCollection, Action< DateTime, DateTime > endCollection, Action< Instrument > beginInstrumentMeasurements, Action< Instrument > endInstrumentMeasurements, Action< Instrument > instrumentPublished, Action initialInstrumentEnumerationComplete, Action< Exception > collectionError, Action timeSeriesLimitReached, Action histogramLimitReached, Action< Exception > observableInstrumentCallbackError) inline
Definition at line 55 of file AggregationManager.cs.
    {
        _maxTimeSeries = maxTimeSeries;
        _maxHistograms = maxHistograms;
        _collectMeasurement = collectMeasurement;
        _beginCollection = beginCollection;
        _endCollection = endCollection;
        _beginInstrumentMeasurements = beginInstrumentMeasurements;
        _endInstrumentMeasurements = endInstrumentMeasurements;
        _instrumentPublished = instrumentPublished;
        _initialInstrumentEnumerationComplete = initialInstrumentEnumerationComplete;
        _collectionError = collectionError;
        _timeSeriesLimitReached = timeSeriesLimitReached;
        _histogramLimitReached = histogramLimitReached;
        _observableInstrumentCallbackError = observableInstrumentCallbackError;
        _listener = new MeterListener
        {
            InstrumentPublished = delegate(Instrument instrument, MeterListener listener)
            {
                _instrumentPublished(instrument);
                InstrumentState instrumentState = GetInstrumentState(instrument);
                if (instrumentState != null)
                {
                    _beginInstrumentMeasurements(instrument);
                    listener.EnableMeasurementEvents(instrument, instrumentState);
                }
            },
            MeasurementsCompleted = delegate(Instrument instrument, object cookie)
            {
                _endInstrumentMeasurements(instrument);
                RemoveInstrumentState(instrument, (InstrumentState)cookie);
            }
        };
        _listener.SetMeasurementEventCallback(delegate(Instrument i, double m, ReadOnlySpan<KeyValuePair<string, object>> l, object c)
        {
            ((InstrumentState)c).Update(m, l);
        });
        _listener.SetMeasurementEventCallback(delegate(Instrument i, float m, ReadOnlySpan<KeyValuePair<string, object>> l, object c)
        {
            ((InstrumentState)c).Update(m, l);
        });
        _listener.SetMeasurementEventCallback(delegate(Instrument i, long m, ReadOnlySpan<KeyValuePair<string, object>> l, object c)
        {
            ((InstrumentState)c).Update(m, l);
        });
        _listener.SetMeasurementEventCallback(delegate(Instrument i, int m, ReadOnlySpan<KeyValuePair<string, object>> l, object c)
        {
            ((InstrumentState)c).Update(m, l);
        });
        _listener.SetMeasurementEventCallback(delegate(Instrument i, short m, ReadOnlySpan<KeyValuePair<string, object>> l, object c)
        {
            ((InstrumentState)c).Update(m, l);
        });
        _listener.SetMeasurementEventCallback(delegate(Instrument i, byte m, ReadOnlySpan<KeyValuePair<string, object>> l, object c)
        {
            ((InstrumentState)c).Update((int)m, l);
        });
        _listener.SetMeasurementEventCallback(delegate(Instrument i, decimal m, ReadOnlySpan<KeyValuePair<string, object>> l, object c)
        {
            ((InstrumentState)c).Update((double)m, l);
        });
    }
References System.Diagnostics.Metrics.AggregationManager._beginCollection, System.Diagnostics.Metrics.AggregationManager._beginInstrumentMeasurements, System.Diagnostics.Metrics.AggregationManager._collectionError, System.Diagnostics.Metrics.AggregationManager._collectMeasurement, System.Diagnostics.Metrics.AggregationManager._endCollection, System.Diagnostics.Metrics.AggregationManager._endInstrumentMeasurements, System.Diagnostics.Metrics.AggregationManager._histogramLimitReached, System.Diagnostics.Metrics.AggregationManager._initialInstrumentEnumerationComplete, System.Diagnostics.Metrics.AggregationManager._instrumentPublished, System.Diagnostics.Metrics.AggregationManager._listener, System.Diagnostics.Metrics.AggregationManager._maxHistograms, System.Diagnostics.Metrics.AggregationManager._maxTimeSeries, System.Diagnostics.Metrics.AggregationManager._observableInstrumentCallbackError, System.Diagnostics.Metrics.AggregationManager._timeSeriesLimitReached, System.Diagnostics.Metrics.MeterListener.EnableMeasurementEvents(), System.Diagnostics.Metrics.AggregationManager.GetInstrumentState(), and System.Diagnostics.Metrics.AggregationManager.RemoveInstrumentState().