Terraria: System.Diagnostics.Metrics.AggregationManager.GetAggregatorFactory
GetAggregatorFactory()
Func< Aggregator > System.Diagnostics.Metrics.AggregationManager.GetAggregatorFactory (Instrument instrument) inline private
Definition at line 250 of file AggregationManager.cs.
    {
        Type type = instrument.GetType();
        Type type2 = null;
        type2 = (type.IsGenericType ? type.GetGenericTypeDefinition() : null);
        if (type2 == typeof(Counter<>))
        {
            return delegate
            {
                lock (this)
                {
                    return CheckTimeSeriesAllowed() ? new RateSumAggregator() : null;
                }
            };
        }
        if (type2 == typeof(ObservableCounter<>))
        {
            return delegate
            {
                lock (this)
                {
                    return CheckTimeSeriesAllowed() ? new RateAggregator() : null;
                }
            };
        }
        if (type2 == typeof(ObservableGauge<>))
        {
            return delegate
            {
                lock (this)
                {
                    return CheckTimeSeriesAllowed() ? new LastValue() : null;
                }
            };
        }
        if (type2 == typeof(Histogram<>))
        {
            return delegate
            {
                lock (this)
                {
                    return (!CheckTimeSeriesAllowed() || !CheckHistogramAllowed()) ? null : new ExponentialHistogramAggregator(s_defaultHistogramConfig);
                }
            };
        }
        return null;
    }
References System.Diagnostics.Metrics.AggregationManager.CheckHistogramAllowed(), System.Diagnostics.Metrics.AggregationManager.CheckTimeSeriesAllowed(), System.Diagnostics.Metrics.AggregationManager.s_defaultHistogramConfig, and System.type.
Referenced by System.Diagnostics.Metrics.AggregationManager.BuildInstrumentState().