Terraria: System.Diagnostics.Metrics.AggregationManager.Start
Start()
void System.Diagnostics.Metrics.AggregationManager.Start () inline
Definition at line 145 of file AggregationManager.cs.
    {
        _collectThread = new Thread((ThreadStart)delegate
        {
            CollectWorker(_cts.Token);
        });
        _collectThread.IsBackground = true;
        _collectThread.Name = "MetricsEventSource CollectWorker";
        _collectThread.Start();
        _listener.Start();
        _initialInstrumentEnumerationComplete();
    }
References System.Diagnostics.Metrics.AggregationManager._collectThread, System.Diagnostics.Metrics.AggregationManager._cts, System.Diagnostics.Metrics.AggregationManager._initialInstrumentEnumerationComplete, System.Diagnostics.Metrics.AggregationManager._listener, System.Diagnostics.Metrics.AggregationManager.CollectWorker(), System.Diagnostics.Metrics.MeterListener.Start(), System.Threading.Thread.Start(), System.Threading.ThreadStart(), and System.Threading.CancellationTokenSource.Token.
Referenced by System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.OnEventCommand().