Terraria: System.Diagnostics.Metrics.AggregationManager.CollectWorker
CollectWorker()
void System.Diagnostics.Metrics.AggregationManager.CollectWorker (CancellationToken cancelToken) inline private
Definition at line 158 of file AggregationManager.cs.
    {
        try
        {
            double num = -1.0;
            lock (this)
            {
                num = _collectionPeriod.TotalSeconds;
            }
            DateTime utcNow = DateTime.UtcNow;
            DateTime arg = utcNow;
            while (!cancelToken.IsCancellationRequested)
            {
                DateTime utcNow2 = DateTime.UtcNow;
                double totalSeconds = (utcNow2 - utcNow).TotalSeconds;
                double value = Math.Ceiling(totalSeconds / num) * num;
                DateTime dateTime = utcNow.AddSeconds(value);
                DateTime dateTime2 = arg.AddSeconds(num);
                if (dateTime <= dateTime2)
                {
                    dateTime = dateTime2;
                }
                TimeSpan timeout = dateTime - utcNow2;
                if (!cancelToken.WaitHandle.WaitOne(timeout))
                {
                    _beginCollection(arg, dateTime);
                    Collect();
                    _endCollection(arg, dateTime);
                    arg = dateTime;
                    continue;
                }
                break;
            }
        }
        catch (Exception obj)
        {
            _collectionError(obj);
        }
    }
References System.Diagnostics.Metrics.AggregationManager._beginCollection, System.Diagnostics.Metrics.AggregationManager._collectionError, System.Diagnostics.Metrics.AggregationManager._collectionPeriod, System.Diagnostics.Metrics.AggregationManager._endCollection, System.Math.Ceiling(), System.Diagnostics.Metrics.AggregationManager.Collect(), System.obj, System.timeout, System.TimeSpan.TotalSeconds, System.DateTime.UtcNow, and System.value.
Referenced by System.Diagnostics.Metrics.AggregationManager.Start().