Terraria: System.Runtime.Serialization.Json.ReflectionJsonReader.ReflectionReadMembers
ReflectionReadMembers()
override void System.Runtime.Serialization.Json.ReflectionJsonReader.ReflectionReadMembers (XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context, XmlDictionaryString[] memberNames, XmlDictionaryString[] memberNamespaces, ClassDataContract classContract, ref object obj) inline protected
Definition at line 18 of file ReflectionJsonReader.cs.
    {
        XmlObjectSerializerReadContextComplexJson xmlObjectSerializerReadContextComplexJson = context as XmlObjectSerializerReadContextComplexJson;
        int num = classContract.MemberNames.Length;
        context.IncrementItemCount(num);
        DataMember[] array = new DataMember[num];
        ReflectionGetMembers(classContract, array);
        int num2 = -1;
        ExtensionDataObject extensionData = null;
        if (classContract.HasExtensionData)
        {
            extensionData = new ExtensionDataObject();
            ((IExtensibleDataObject)obj).ExtensionData = extensionData;
        }
        while (XmlObjectSerializerReadContext.MoveToNextElement(xmlReader))
        {
            num2 = xmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(xmlReader, memberNames, num2, extensionData);
            if (num2 < array.Length)
            {
                ReflectionReadMember(xmlReader, context, classContract, ref obj, num2, array);
            }
        }
    }
References System.array, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.Runtime.Serialization.XmlObjectSerializerReadContext.MoveToNextElement(), System.obj, System.Runtime.Serialization.ReflectionReader.ReflectionGetMembers(), and System.Runtime.Serialization.ReflectionReader.ReflectionReadMember().