Terraria: System.Diagnostics.Metrics.AggregationManager.BuildInstrumentState
BuildInstrumentState()
InstrumentState System.Diagnostics.Metrics.AggregationManager.BuildInstrumentState (Instrument instrument) inline package
Definition at line 238 of file AggregationManager.cs.
    {
        Func<Aggregator> aggregatorFactory = GetAggregatorFactory(instrument);
        if (aggregatorFactory == null)
        {
            return null;
        }
        Type type = aggregatorFactory.GetType().GenericTypeArguments[0];
        Type type2 = typeof(InstrumentState<>).MakeGenericType(type);
        return (InstrumentState)Activator.CreateInstance(type2, aggregatorFactory);
    }
References System.Activator.CreateInstance(), System.Diagnostics.Metrics.AggregationManager.GetAggregatorFactory(), and System.type.
Referenced by System.Diagnostics.Metrics.AggregationManager.GetInstrumentState().