Terraria: System.Runtime.Serialization.Json.ReflectionJsonReader.ReadSimpleDictionary
ReadSimpleDictionary()
void System.Runtime.Serialization.Json.ReflectionJsonReader.ReadSimpleDictionary (XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context, CollectionDataContract collectionContract, Type keyValueType, object dictionary) inline private
Definition at line 78 of file ReflectionJsonReader.cs.
    {
        Type[] genericArguments = keyValueType.GetGenericArguments();
        Type type = genericArguments[0];
        Type type2 = genericArguments[1];
        int num = 0;
        while (type.IsGenericType && type.GetGenericTypeDefinition() == Globals.TypeOfNullable)
        {
            num++;
            type = type.GetGenericArguments()[0];
        }
        ClassDataContract classDataContract = (ClassDataContract)collectionContract.ItemContract;
        DataContract memberTypeContract = classDataContract.Members[0].MemberTypeContract;
        KeyParseMode keyParseMode = KeyParseMode.Fail;
        if (type == Globals.TypeOfString || type == Globals.TypeOfObject)
        {
            keyParseMode = KeyParseMode.AsString;
        }
        else if (type.IsEnum)
        {
            keyParseMode = KeyParseMode.UsingParseEnum;
        }
        else if (memberTypeContract.ParseMethod != null)
        {
            keyParseMode = KeyParseMode.UsingCustomParse;
        }
        if (keyParseMode == KeyParseMode.Fail)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.KeyTypeCannotBeParsedInSimpleDictionary, DataContract.GetClrTypeFullName(collectionContract.UnderlyingType), DataContract.GetClrTypeFullName(type))));
        }
        while (true)
        {
            switch (xmlReader.MoveToContent())
            {
            case XmlNodeType.EndElement:
                return;
            default:
                throw XmlObjectSerializerReadContext.CreateUnexpectedStateException(XmlNodeType.Element, xmlReader);
            case XmlNodeType.Element:
            {
                context.IncrementItemCount(1);
                string jsonMemberName = XmlObjectSerializerReadContextComplexJson.GetJsonMemberName(xmlReader);
                object key = keyParseMode switch
                {
                    KeyParseMode.UsingParseEnum => Enum.Parse(type, jsonMemberName),
                    KeyParseMode.UsingCustomParse => Type.GetTypeCode(memberTypeContract.UnderlyingType) switch
                    {
                        TypeCode.Boolean => bool.Parse(jsonMemberName),
                        TypeCode.Int16 => short.Parse(jsonMemberName),
                        TypeCode.Int32 => int.Parse(jsonMemberName),
                        TypeCode.Int64 => long.Parse(jsonMemberName),
                        TypeCode.Char => char.Parse(jsonMemberName),
                        TypeCode.Byte => byte.Parse(jsonMemberName),
                        TypeCode.SByte => sbyte.Parse(jsonMemberName),
                        TypeCode.Double => double.Parse(jsonMemberName),
                        TypeCode.Decimal => decimal.Parse(jsonMemberName),
                        TypeCode.Single => float.Parse(jsonMemberName),
                        TypeCode.UInt16 => ushort.Parse(jsonMemberName),
                        TypeCode.UInt32 => uint.Parse(jsonMemberName),
                        TypeCode.UInt64 => ulong.Parse(jsonMemberName),
                        _ => memberTypeContract.ParseMethod.Invoke(null, new object[1] { jsonMemberName }),
                    },
                    _ => jsonMemberName,
                };
                if (num > 0)
                {
                    throw new NotImplementedException(System.SR.Format(System.SR.MustBeGreaterThanZero, num));
                }
                object value = ReflectionReadValue(xmlReader, context, type2, string.Empty, string.Empty);
                ((IDictionary)dictionary).Add(key, value);
                break;
            }
            }
        }
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateUnexpectedStateException(), System.dictionary, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Type.GetGenericArguments(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberName(), System.Type.GetTypeCode(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.key, System.SR.KeyTypeCannotBeParsedInSimpleDictionary, System.SR.MustBeGreaterThanZero, System.Enum.Parse(), System.Runtime.Serialization.ReflectionReader.ReflectionReadValue(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.type, System.Runtime.Serialization.Globals.TypeOfNullable, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.Globals.TypeOfString, and System.value.
Referenced by System.Runtime.Serialization.Json.ReflectionJsonReader.ReflectionReadSpecialCollection().