Terraria: System.Runtime.Serialization.Json.ReflectionJsonReader.ReflectionReadDictionaryItem
ReflectionReadDictionaryItem()
override object System.Runtime.Serialization.Json.ReflectionJsonReader.ReflectionReadDictionaryItem (XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context, CollectionDataContract collectionContract) inline protected
Definition at line 58 of file ReflectionJsonReader.cs.
    {
        XmlObjectSerializerReadContextComplexJson context2 = context as XmlObjectSerializerReadContextComplexJson;
        context.ReadAttributes(xmlReader);
        DataContract revisedItemContract = XmlObjectSerializerWriteContextComplexJson.GetRevisedItemContract(collectionContract.ItemContract);
        return DataContractJsonSerializer.ReadJsonValue(revisedItemContract, xmlReader, context2);
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.GetRevisedItemContract(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAttributes(), and System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadJsonValue().