Terraria: ScreenDarkness.Update
Update()
static void ScreenDarkness.Update () inline static
     {
         float value = 0f;
         float amount = 1f / 60f;
         Vector2 mountedCenter = Main.player[Main.myPlayer].MountedCenter;
         for (int i = 0; i < 200; i++)
         {
             if (Main.npc[i].active && Main.npc[i].type == 370 && Main.npc[i].Distance(mountedCenter) < 3000f && (Main.npc[i].ai[0] >= 10f || (Main.npc[i].ai[0] == 9f && Main.npc[i].ai[2] > 120f)))
             {
                 value = 0.95f;
                 frontColor = new Color(0, 0, 120) * 0.3f;
                 amount = 0.03f;
             }
             if (Main.npc[i].active && Main.npc[i].type == 113 && Main.npc[i].Distance(mountedCenter) < 3000f)
             {
                 float num = Utils.Remap(Main.npc[i].Distance(mountedCenter), 2000f, 3000f, 1f, 0f);
                 value = Main.npc[i].localAI[1] * num;
                 amount = 1f;
                 frontColor = Color.Black;
             }
         }
         screenObstruction = MathHelper.Lerp(screenObstruction, value, amount);
     }
References Entity.active, NPC.ai, Color, Entity.Distance(), frontColor, NPC.localAI, Player.MountedCenter, Main.myPlayer, Main.npc, Main.player, Utils.Remap(), screenObstruction, and NPC.type.
Referenced by Main.DoUpdate().