Terraria: Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult
GetExceptionFromResult()
static Exception Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult (uint result) inline static
Definition at line 20 of file GraphicsHelpers.cs.
    {
        if (result == 0)
        {
            return null;
        }
        return result switch
        {
            2289436711u => new InvalidOperationException(FrameworkResources.DriverError),
            2289436776u => new DeviceLostException(),
            2289436777u => new DeviceNotResetException(),
            2289436784u => new NotSupportedException(),
            2289435004u => new OutOfMemoryException(),
            2150814720u => new InvalidOperationException(FrameworkResources.DirectRenderingWrongMode),
            _ => Helpers.GetExceptionFromResult(result),
        };
    }
References Microsoft.Xna.Framework.FrameworkResources.DirectRenderingWrongMode, Microsoft.Xna.Framework.FrameworkResources.DriverError, and Microsoft.Xna.Framework.Helpers.GetExceptionFromResult().
Referenced by Microsoft.Xna.Framework.Graphics.Effect.Effect(), Microsoft.Xna.Framework.Graphics.EffectAnnotation.EffectAnnotation(), Microsoft.Xna.Framework.Graphics.EffectParameter.EffectParameter(), Microsoft.Xna.Framework.Graphics.EffectPass.EffectPass(), Microsoft.Xna.Framework.Graphics.EffectTechnique.EffectTechnique(), Microsoft.Xna.Framework.Graphics.OcclusionQuery.OcclusionQuery(), Microsoft.Xna.Framework.Graphics.EffectPass.Apply(), Microsoft.Xna.Framework.Graphics.OcclusionQuery.Begin(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.ClearDirtyBuffers(), Microsoft.Xna.Framework.Graphics.TextureCube.CopyData< T >(), Microsoft.Xna.Framework.Graphics.Texture3D.CopyData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.CopyData< T >(), Microsoft.Xna.Framework.Graphics.VertexBuffer.CopyData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.CopyData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.CreateBuffer(), Microsoft.Xna.Framework.Graphics.VertexBuffer.CreateBuffer(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateDevice(), Microsoft.Xna.Framework.Graphics.Effect.CreateEffectFromCode(), Microsoft.Xna.Framework.Graphics.DeclarationManager.CreateNativeDeclaration(), Microsoft.Xna.Framework.Graphics.RenderTargetHelper.CreateSurfaces(), Microsoft.Xna.Framework.Graphics.TextureCube.CreateTexture(), Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture(), Microsoft.Xna.Framework.Graphics.Texture3D.CreateTexture(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawInstancedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), Microsoft.Xna.Framework.Graphics.OcclusionQuery.End(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueBoolean(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueBooleanArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueInt32(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueInt32Array(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueMatrix(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueMatrixArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueMatrixTranspose(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueMatrixTransposeArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueQuaternion(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueQuaternionArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueSingle(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueSingleArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueString(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueTexture2D(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueTexture3D(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueTextureCube(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector2(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector2Array(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector3(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector3Array(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector4(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector4Array(), Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceReset(), Microsoft.Xna.Framework.Graphics.Texture.InitializeDescription(), Microsoft.Xna.Framework.Graphics.Texture2D.InitializeDescription(), Microsoft.Xna.Framework.Graphics.Texture3D.InitializeDescription(), Microsoft.Xna.Framework.Graphics.TextureCube.InitializeDescription(), Microsoft.Xna.Framework.Graphics.Effect.InitializeHelpers(), Microsoft.Xna.Framework.Graphics.Effect.OnLostDevice(), Microsoft.Xna.Framework.Graphics.Effect.OnResetDevice(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.RecreateResources(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAutomaticResources(), Microsoft.Xna.Framework.Graphics.GuideRenderer.ReplayDrawingCommands(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(), Microsoft.Xna.Framework.Graphics.TextureCollection.ResetState(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.ResolveRenderTarget(), Microsoft.Xna.Framework.Graphics.DeclarationManager.SetNativeDeclaration(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValueTranspose(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValueTranspose(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers(), and Microsoft.Xna.Framework.Graphics.GraphicsHelpers.ThrowExceptionFromResult().