Terraria: Internal.Runtime.InteropServices.ComActivator.LicenseClassFactory.CreateInstanceInner
CreateInstanceInner()
void Internal.Runtime.InteropServices.ComActivator.LicenseClassFactory.CreateInstanceInner (object pUnkOuter, ref Guid riid, string key, bool isDesignTime, out IntPtr ppvObject) inline private
Definition at line 139 of file ComActivator.cs.
        {
            Type validatedInterfaceType = BasicClassFactory.GetValidatedInterfaceType(_classType, ref riid, pUnkOuter);
            object obj = _licenseProxy.AllocateAndValidateLicense(_classType, key, isDesignTime);
            if (pUnkOuter != null)
            {
                obj = BasicClassFactory.CreateAggregatedObject(pUnkOuter, obj);
            }
            ppvObject = BasicClassFactory.GetObjectAsInterface(obj, validatedInterfaceType);
        }
References Internal.Runtime.InteropServices.ComActivator.LicenseClassFactory._classType, Internal.Runtime.InteropServices.ComActivator.LicenseClassFactory._licenseProxy, Internal.Runtime.InteropServices.LicenseInteropProxy.AllocateAndValidateLicense(), Internal.Runtime.InteropServices.ComActivator.BasicClassFactory.CreateAggregatedObject(), Internal.Runtime.InteropServices.ComActivator.BasicClassFactory.GetObjectAsInterface(), Internal.Runtime.InteropServices.ComActivator.BasicClassFactory.GetValidatedInterfaceType(), System.key, and System.obj.
Referenced by Internal.Runtime.InteropServices.ComActivator.LicenseClassFactory.CreateInstance(), and Internal.Runtime.InteropServices.ComActivator.LicenseClassFactory.CreateInstanceLic().