Terraria: ShapeBranch.Perform
Perform()
override bool ShapeBranch.Perform (Point origin, GenAction action) inline virtual
Implements GenShape.
     {
         //IL_012e: Unknown result type (might be due to invalid IL or missing references)
         //IL_0163: Unknown result type (might be due to invalid IL or missing references)
         //IL_0169: Unknown result type (might be due to invalid IL or missing references)
         //IL_016b: Unknown result type (might be due to invalid IL or missing references)
         //IL_0179: Unknown result type (might be due to invalid IL or missing references)
         //IL_017e: Unknown result type (might be due to invalid IL or missing references)
         //IL_0182: Unknown result type (might be due to invalid IL or missing references)
         //IL_0192: Unknown result type (might be due to invalid IL or missing references)
         Vector2D val = default(Vector2D);
         ((Vector2D)(ref val))._002Ector((double)_offset.X, (double)_offset.Y);
         double num = ((Vector2D)(ref val)).Length();
         int num2 = (int)(num / 6.0);
         if (_endPoints != null)
         {
             _endPoints.Add(new Point(origin.X + _offset.X, origin.Y + _offset.Y));
         }
         if (!PerformSegment(origin, action, origin, new Point(origin.X + _offset.X, origin.Y + _offset.Y), num2))
         {
             return false;
         }
         int num3 = (int)(num / 8.0);
         Vector2D val2 = default(Vector2D);
         for (int i = 0; i < num3; i++)
         {
             double num4 = ((double)i + 1.0) / ((double)num3 + 1.0);
             Point point = new Point((int)(num4 * (double)_offset.X), (int)(num4 * (double)_offset.Y));
             ((Vector2D)(ref val2))._002Ector((double)(_offset.X - point.X), (double)(_offset.Y - point.Y));
             val2 = val2.RotatedBy((GenBase._random.NextDouble() * 0.5 + 1.0) * (double)((GenBase._random.Next(2) != 0) ? 1 : (-1))) * 0.75;
             Point point2 = new Point((int)val2.X + point.X, (int)val2.Y + point.Y);
             if (_endPoints != null)
             {
                 _endPoints.Add(new Point(point2.X + origin.X, point2.Y + origin.Y));
             }
             if (!PerformSegment(origin, action, new Point(point.X + origin.X, point.Y + origin.Y), new Point(point2.X + origin.X, point2.Y + origin.Y), num2 - 1))
             {
                 return false;
             }
         }
         return true;
     }
References _endPoints, _offset, GenBase._random, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), and PerformSegment().