Terraria: System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableValue.Run
Run()
override int System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableValue.Run (InterpretedFrame frame) inline
Definition at line 151 of file InitializeLocalInstruction.cs.
        {
            try
            {
                frame.Data[_index] = (_type.IsNullableType() ? Activator.CreateInstance(_type) : RuntimeHelpers.GetUninitializedObject(_type));
            }
            catch (TargetInvocationException exception)
            {
                ExceptionHelpers.UnwrapAndRethrow(exception);
                throw ContractUtils.Unreachable;
            }
            return 1;
        }
References System.Linq.Expressions.Interpreter.LocalAccessInstruction._index, System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableValue._type, System.Activator.CreateInstance(), System.Linq.Expressions.Interpreter.InterpretedFrame.Data, System.exception, System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(), System.Dynamic.Utils.ContractUtils.Unreachable, and System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow().