Terraria: System.Xml.Linq.NamespaceResolver.PopScope
PopScope()
void System.Xml.Linq.NamespaceResolver.PopScope () inline
Definition at line 27 of file NamespaceResolver.cs.
    {
        NamespaceDeclaration namespaceDeclaration = _declaration;
        if (namespaceDeclaration != null)
        {
            do
            {
                namespaceDeclaration = namespaceDeclaration.prev;
                if (namespaceDeclaration.scope != _scope)
                {
                    break;
                }
                if (namespaceDeclaration == _declaration)
                {
                    _declaration = null;
                }
                else
                {
                    _declaration.prev = namespaceDeclaration.prev;
                }
                _rover = null;
            }
            while (namespaceDeclaration != _declaration && _declaration != null);
        }
        _scope--;
    }
References System.Xml.Linq.NamespaceResolver._declaration, System.Xml.Linq.NamespaceResolver._rover, System.Xml.Linq.NamespaceResolver._scope, System.Xml.Dictionary, and System.Xml.Linq.NamespaceResolver.NamespaceDeclaration.prev.
Referenced by System.Xml.Linq.ElementWriter.WriteEndElement(), System.Xml.Linq.ElementWriter.WriteEndElementAsync(), System.Xml.Linq.ElementWriter.WriteFullEndElement(), System.Xml.Linq.ElementWriter.WriteFullEndElementAsync(), and System.Xml.Linq.StreamingElementWriter.WriteStreamingElement().