Terraria: ReLogic.Peripherals.RGB.RgbKey.UpdateFlashingEffect
UpdateFlashingEffect()
void ReLogic.Peripherals.RGB.RgbKey.UpdateFlashingEffect () inline private
Definition at line 143 of file RgbKey.cs.
    {
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        float amount = (float)Math.Sin(_timeRemaining * _effectRate * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
        CurrentColor = Color.Lerp(BaseColor, TargetColor, amount);
    }
References ReLogic.Peripherals.RGB.RgbKey._effectRate, ReLogic.Peripherals.RGB.RgbKey._timeRemaining, ReLogic.Peripherals.RGB.RgbKey.BaseColor, ReLogic.Peripherals.RGB.RgbKey.CurrentColor, Microsoft.Xna.Framework.Color.Lerp(), System.Math.PI, System.Math.Sin(), and ReLogic.Peripherals.RGB.RgbKey.TargetColor.
Referenced by ReLogic.Peripherals.RGB.RgbKey.Update().