Terraria: CreativePowers.ASharedTogglePower.RequestUse
RequestUse()
void CreativePowers.ASharedTogglePower.RequestUse () inline private inherited
         {
             NetPacket packet = NetCreativePowersModule.PreparePacket(PowerId, 1);
             packet.Writer.Write(!Enabled);
             NetManager.Instance.SendToServerOrLoopback(packet);
         }
References CreativePowers.ASharedTogglePower.Enabled, NetManager.Instance, CreativePowers.ASharedTogglePower.PowerId, NetCreativePowersModule.PreparePacket(), NetManager.SendToServerOrLoopback(), and NetPacket.Writer.
Referenced by CreativePowers.ASharedTogglePower.button_OnClick().