Terraria: CreativePowers.ASharedTogglePower.DeserializeNetMessage
DeserializeNetMessage()
void CreativePowers.ASharedTogglePower.DeserializeNetMessage (BinaryReader reader, int userId) inline inherited
Implements ICreativePower.
         {
             bool powerInfo = reader.ReadBoolean();
             if (Main.netMode != 2 || CreativePowersHelper.IsAvailableForPlayer(this, userId))
             {
                 SetPowerInfo(powerInfo);
                 if (Main.netMode == 2)
                 {
                     NetPacket packet = NetCreativePowersModule.PreparePacket(PowerId, 1);
                     packet.Writer.Write(Enabled);
                     NetManager.Instance.Broadcast(packet);
                 }
             }
         }
References NetManager.Broadcast(), CreativePowers.ASharedTogglePower.Enabled, NetManager.Instance, CreativePowersHelper.IsAvailableForPlayer(), Main.netMode, CreativePowers.ASharedTogglePower.PowerId, NetCreativePowersModule.PreparePacket(), CreativePowers.ASharedTogglePower.SetPowerInfo(), and NetPacket.Writer.