Terraria: Minecart.TryFittingTileOrientation
TryFittingTileOrientation()
static void Minecart.TryFittingTileOrientation (Point tileCoords, int? expectedYOffsetForLeft, int? expectedYOffsetForRight) inline static
     {
         int nearbyTilesSetLookupIndex = GetNearbyTilesSetLookupIndex(tileCoords.X, tileCoords.Y);
         int[] array = _trackSwitchOptions[nearbyTilesSetLookupIndex];
         if (array == null)
         {
             return;
         }
         Tile tileSafely = Framing.GetTileSafely(tileCoords);
         int num = _trackType[tileSafely.FrontTrack()];
         int? num2 = null;
         foreach (int num3 in array)
         {
             _ = _leftSideConnection[num3];
             _ = _rightSideConnection[num3];
             _ = _trackType[num3];
             if (expectedYOffsetForLeft.HasValue)
             {
                 int num4 = ConvertOffsetYToTrackConnectionValue(expectedYOffsetForLeft.Value);
                 if (_leftSideConnection[num3] != num4)
                 {
                     continue;
                 }
             }
             if (expectedYOffsetForRight.HasValue)
             {
                 int num5 = ConvertOffsetYToTrackConnectionValue(expectedYOffsetForRight.Value);
                 if (_rightSideConnection[num3] != num5)
                 {
                     continue;
                 }
             }
             if (_trackType[num3] == num)
             {
                 num2 = num3;
                 break;
             }
         }
         if (num2.HasValue)
         {
             tileSafely.FrontTrack((short)num2.Value);
             NetMessage.SendTileSquare(-1, tileCoords.X, tileCoords.Y);
         }
     }
References _leftSideConnection, _rightSideConnection, _trackSwitchOptions, _trackType, ConvertOffsetYToTrackConnectionValue(), GetNearbyTilesSetLookupIndex(), Framing.GetTileSafely(), and NetMessage.SendTileSquare().
Referenced by MinecartDiggerHelper.CorrectTrackConnections().