Terraria: Minecart.TrackColors
TrackColors()
static void Minecart.TrackColors (int i, int j, Tile trackTile, out int frontColor, out int backColor) inline static
     {
         if (trackTile.type == 314)
         {
             frontColor = trackTile.color();
             backColor = frontColor;
             if (trackTile.frameY == -1)
             {
                 return;
             }
             int num = _leftSideConnection[trackTile.frameX];
             int num2 = _rightSideConnection[trackTile.frameX];
             int num3 = _leftSideConnection[trackTile.frameY];
             int num4 = _rightSideConnection[trackTile.frameY];
             int num5 = 0;
             int num6 = 0;
             int num7 = 0;
             int num8 = 0;
             for (int k = 0; k < 4; k++)
             {
                 int num9 = (k switch
                 {
                     1 => num2,
                     2 => num3,
                     3 => num4,
                     _ => num,
                 }) switch
                 {
                     0 => -1,
                     1 => 0,
                     2 => 1,
                     _ => 0,
                 };
                 Tile tile = ((k % 2 != 0) ? Main.tile[i + 1, j + num9] : Main.tile[i - 1, j + num9]);
                 int num10 = ((tile != null && tile.active() && tile.type == 314) ? tile.color() : 0);
                 switch (k)
                 {
                 default:
                     num5 = num10;
                     break;
                 case 1:
                     num6 = num10;
                     break;
                 case 2:
                     num7 = num10;
                     break;
                 case 3:
                     num8 = num10;
                     break;
                 }
             }
             if (num == num3)
             {
                 if (num6 != 0)
                 {
                     frontColor = num6;
                 }
                 else if (num5 != 0)
                 {
                     frontColor = num5;
                 }
                 if (num8 != 0)
                 {
                     backColor = num8;
                 }
                 else if (num7 != 0)
                 {
                     backColor = num7;
                 }
                 return;
             }
             if (num2 == num4)
             {
                 if (num5 != 0)
                 {
                     frontColor = num5;
                 }
                 else if (num6 != 0)
                 {
                     frontColor = num6;
                 }
                 if (num7 != 0)
                 {
                     backColor = num7;
                 }
                 else if (num8 != 0)
                 {
                     backColor = num8;
                 }
                 return;
             }
             if (num6 == 0)
             {
                 if (num5 != 0)
                 {
                     frontColor = num5;
                 }
             }
             else if (num5 != 0)
             {
                 frontColor = ((num2 <= num) ? num6 : num5);
             }
             if (num8 == 0)
             {
                 if (num7 != 0)
                 {
                     backColor = num7;
                 }
             }
             else if (num7 != 0)
             {
                 backColor = ((num4 <= num3) ? num8 : num7);
             }
         }
         else
         {
             frontColor = 0;
             backColor = 0;
         }
     }
References _leftSideConnection, _rightSideConnection, Tile.active(), Tile.color(), Tile.frameX, Tile.frameY, Main.tile, and Tile.type.
Referenced by TileDrawing.DrawTile_MinecartTrack().