Terraria: Minecart.FlipSwitchTrack
FlipSwitchTrack()
static void Minecart.FlipSwitchTrack (int i, int j) inline static
     {
         Tile tileTrack = Main.tile[i, j];
         short num = tileTrack.FrontTrack();
         if (num == -1)
         {
             return;
         }
         switch (_trackType[num])
         {
         case 0:
             if (tileTrack.BackTrack() != -1)
             {
                 tileTrack.FrontTrack(tileTrack.BackTrack());
                 tileTrack.BackTrack(num);
                 NetMessage.SendTileSquare(-1, i, j);
             }
             break;
         case 2:
             FrameTrack(i, j, pound: true, mute: true);
             NetMessage.SendTileSquare(-1, i, j);
             break;
         }
     }
References _trackType, FrameTrack(), NetMessage.SendTileSquare(), and Main.tile.
Referenced by Wiring.HitWireSingle().