Terraria: Minecart.FrameTrack
FrameTrack()
static bool Minecart.FrameTrack (int i, int j, bool pound, bool mute = false) inline static
     {
         if (_trackType == null)
         {
             return false;
         }
         Tile tile = Main.tile[i, j];
         if (tile == null)
         {
             tile = new Tile();
             Main.tile[i, j] = tile;
         }
         if (mute && tile.type != 314)
         {
             return false;
         }
         int nearbyTilesSetLookupIndex = GetNearbyTilesSetLookupIndex(i, j);
         int num = tile.FrontTrack();
         int num2 = tile.BackTrack();
         int num3 = ((num >= 0 && num < _trackType.Length) ? _trackType[num] : 0);
         int num4 = -1;
         int num5 = -1;
         int[] array = _trackSwitchOptions[nearbyTilesSetLookupIndex];
         if (array == null)
         {
             if (pound)
             {
                 return false;
             }
             tile.FrontTrack(0);
             tile.BackTrack(-1);
             return false;
         }
         if (!pound)
         {
             int num6 = -1;
             int num7 = -1;
             bool flag = false;
             for (int k = 0; k < array.Length; k++)
             {
                 int num8 = array[k];
                 if (num2 == array[k])
                 {
                     num5 = k;
                 }
                 if (_trackType[num8] != num3)
                 {
                     continue;
                 }
                 if (_leftSideConnection[num8] == -1 || _rightSideConnection[num8] == -1)
                 {
                     if (num == array[k])
                     {
                         num4 = k;
                         flag = true;
                     }
                     if (num6 == -1)
                     {
                         num6 = k;
                     }
                 }
                 else
                 {
                     if (num == array[k])
                     {
                         num4 = k;
                         flag = false;
                     }
                     if (num7 == -1)
                     {
                         num7 = k;
                     }
                 }
             }
             if (num7 != -1)
             {
                 if (num4 == -1 || flag)
                 {
                     num4 = num7;
                 }
             }
             else
             {
                 if (num4 == -1)
                 {
                     switch (num3)
                     {
                     case 2:
                         return false;
                     case 1:
                         return false;
                     }
                     num4 = num6;
                 }
                 num5 = -1;
             }
         }
         else
         {
             for (int l = 0; l < array.Length; l++)
             {
                 if (num == array[l])
                 {
                     num4 = l;
                 }
                 if (num2 == array[l])
                 {
                     num5 = l;
                 }
             }
             int num9 = 0;
             int num10 = 0;
             for (int m = 0; m < array.Length; m++)
             {
                 if (_trackType[array[m]] == num3)
                 {
                     if (_leftSideConnection[array[m]] == -1 || _rightSideConnection[array[m]] == -1)
                     {
                         num10++;
                     }
                     else
                     {
                         num9++;
                     }
                 }
             }
             if (num9 < 2 && num10 < 2)
             {
                 return false;
             }
             bool flag2 = num9 == 0;
             bool flag3 = false;
             if (!flag2)
             {
                 while (!flag3)
                 {
                     num5++;
                     if (num5 >= array.Length)
                     {
                         num5 = -1;
                         break;
                     }
                     if ((_leftSideConnection[array[num5]] != _leftSideConnection[array[num4]] || _rightSideConnection[array[num5]] != _rightSideConnection[array[num4]]) && _trackType[array[num5]] == num3 && _leftSideConnection[array[num5]] != -1 && _rightSideConnection[array[num5]] != -1)
                     {
                         flag3 = true;
                     }
                 }
             }
             if (!flag3)
             {
                 do
                 {
                     num4++;
                     if (num4 >= array.Length)
                     {
                         num4 = -1;
                         do
{
                             num4++;
                         }
                         while (_trackType[array[num4]] != num3 || (_leftSideConnection[array[num4]] == -1 || _rightSideConnection[array[num4]] == -1) != flag2);
                         break;
                     }
                 }
                 while (_trackType[array[num4]] != num3 || (_leftSideConnection[array[num4]] == -1 || _rightSideConnection[array[num4]] == -1) != flag2);
             }
         }
         bool flag4 = false;
         switch (num4)
         {
         case -2:
             if (tile.FrontTrack() != _firstPressureFrame)
             {
                 flag4 = true;
             }
             break;
         case -1:
             if (tile.FrontTrack() != 0)
             {
                 flag4 = true;
             }
             break;
         default:
             if (tile.FrontTrack() != array[num4])
             {
                 flag4 = true;
             }
             break;
         }
         if (num5 == -1)
         {
             if (tile.BackTrack() != -1)
             {
                 flag4 = true;
             }
         }
         else if (tile.BackTrack() != array[num5])
         {
             flag4 = true;
         }
         switch (num4)
         {
         case -2:
             tile.FrontTrack(_firstPressureFrame);
             break;
         case -1:
             tile.FrontTrack(0);
             break;
         default:
             tile.FrontTrack((short)array[num4]);
             break;
         }
         if (num5 == -1)
         {
             tile.BackTrack(-1);
         }
         else
         {
             tile.BackTrack((short)array[num5]);
         }
         if (pound && flag4 && !mute)
         {
             WorldGen.KillTile(i, j, fail: true);
         }
         return true;
     }
References _firstPressureFrame, _leftSideConnection, _rightSideConnection, _trackSwitchOptions, _trackType, GetNearbyTilesSetLookupIndex(), WorldGen.KillTile(), Tile, Main.tile, and Tile.type.
Referenced by FlipSwitchTrack(), MessageBuffer.GetData(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), MinecartDiggerHelper.PoundTrack(), and WorldGen.TileFrame().