Terraria: System.Console.SetIn
SetIn()
static void System.Console.SetIn (TextReader newIn) inline static
Definition at line 676 of file Console.cs.
    {
        CheckNonNull(newIn, "newIn");
        newIn = SyncTextReader.GetSynchronizedTextReader(newIn);
        lock (s_syncObject)
        {
            Volatile.Write(ref s_in, newIn);
        }
    }
References System.Console.CheckNonNull(), System.IO.SyncTextReader.GetSynchronizedTextReader(), System.Console.s_in, System.Console.s_syncObject, and System.Threading.Volatile.Write().