Terraria: EmpressBladeDrawer.Draw
Draw()
void EmpressBladeDrawer.Draw (Projectile proj) inline
     {
         _ = proj.ai[1];
         MiscShaderData miscShaderData = GameShaders.Misc["EmpressBlade"];
         int num = 1;
         int num2 = 0;
         int num3 = 0;
         float w = 0.6f;
         miscShaderData.UseShaderSpecificData(new Vector4(num, num2, num3, w));
         miscShaderData.Apply();
         _vertexStrip.PrepareStrip(proj.oldPos, proj.oldRot, StripColors, StripWidth, -Main.screenPosition + proj.Size / 2f, proj.oldPos.Length, includeBacksides: true);
         _vertexStrip.DrawTrail();
         Main.pixelShader.CurrentTechnique.Passes[0].Apply();
     }
References _vertexStrip, Projectile.ai, MiscShaderData.Apply(), VertexStrip.DrawTrail(), GameShaders.Misc, Projectile.oldPos, Projectile.oldRot, Main.pixelShader, VertexStrip.PrepareStrip(), Main.screenPosition, Entity.Size, StripColors(), StripWidth(), and MiscShaderData.UseShaderSpecificData().
Referenced by Main.DrawProjDirect().