Terraria: System.Net.Http.Headers.HttpHeaderParser.ParseValue
ParseValue()
object System.Net.Http.Headers.HttpHeaderParser.ParseValue (string value, object storeValue, ref int index) inline inherited
Definition at line 36 of file HttpHeaderParser.cs.
    {
        if (!TryParseValue(value, storeValue, ref index, out var parsedValue))
        {
            throw new FormatException(System.SR.Format(CultureInfo.InvariantCulture, System.SR.net_http_headers_invalid_value, (value == null) ? "<null>" : value.Substring(index)));
        }
        return parsedValue;
    }
References System.SR.Format(), System.index, System.Globalization.CultureInfo.InvariantCulture, System.SR.net_http_headers_invalid_value, System.Net.Http.Headers.HttpHeaderParser.TryParseValue(), and System.value.
Referenced by System.Net.Http.Headers.HttpHeaders.ParseAndAddValue().