Terraria: System.Linq.Expressions.Interpreter.NewInstruction.Run
Run()
override int System.Linq.Expressions.Interpreter.NewInstruction.Run (InterpretedFrame frame) inline
Definition at line 24 of file NewInstruction.cs.
    {
        int num = frame.StackIndex - _argumentCount;
        object[] args = GetArgs(frame, num);
        object obj;
        try
        {
            obj = _constructor.Invoke(args);
        }
        catch (TargetInvocationException exception)
        {
            ExceptionHelpers.UnwrapAndRethrow(exception);
            throw ContractUtils.Unreachable;
        }
        frame.Data[num] = obj;
        frame.StackIndex = num + 1;
        return 1;
    }
References System.Linq.Expressions.Interpreter.NewInstruction._argumentCount, System.Linq.Expressions.Interpreter.NewInstruction._constructor, System.Linq.Expressions.Interpreter.InterpretedFrame.Data, System.exception, System.Linq.Expressions.Interpreter.NewInstruction.GetArgs(), System.Reflection.ConstructorInfo.Invoke(), System.obj, System.Dynamic.Utils.ContractUtils.Unreachable, and System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow().