Terraria: System.Collections.Queue.SetCapacity
SetCapacity()
void System.Collections.Queue.SetCapacity (int capacity) inline private inherited
Definition at line 445 of file Queue.cs.
    {
        object[] array = new object[capacity];
        if (_size > 0)
        {
            if (_head < _tail)
            {
                Array.Copy(_array, _head, array, 0, _size);
            }
            else
            {
                Array.Copy(_array, _head, array, 0, _array.Length - _head);
                Array.Copy(_array, 0, array, _array.Length - _head, _tail);
            }
        }
        _array = array;
        _head = 0;
        _tail = ((_size != capacity) ? _size : 0);
        _version++;
    }
References System.Collections.Queue._array, System.Collections.Queue._head, System.Collections.Queue._size, System.Collections.Queue._tail, System.Collections.Queue._version, System.array, System.capacity, and System.Array.Copy().
Referenced by System.Collections.Queue.Enqueue(), and System.Collections.Queue.TrimToSize().