Terraria: Microsoft.Xna.Framework.Graphics.VertexDeclaration.Unbind
Unbind()
void Microsoft.Xna.Framework.Graphics.VertexDeclaration.Unbind () inline package
Definition at line 130 of file VertexDeclaration.cs.
    {
        DeclarationBinding binding = _binding;
        if (binding != null)
        {
            _parent.vertexDeclarationManager.ReleaseBinding(binding);
            _binding = null;
        }
    }
References Microsoft.Xna.Framework.Graphics.VertexDeclaration._binding, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.DeclarationManager.ReleaseBinding(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexDeclarationManager.
Referenced by Microsoft.Xna.Framework.Graphics.VertexDeclaration._0021VertexDeclaration(), and Microsoft.Xna.Framework.Graphics.VertexDeclaration._007EVertexDeclaration().