Terraria: Microsoft.Xna.Framework.Graphics.VertexDeclaration.Bind
Bind()
void Microsoft.Xna.Framework.Graphics.VertexDeclaration.Bind (GraphicsDevice device) inline package
Definition at line 113 of file VertexDeclaration.cs.
    {
        if (isDisposed)
        {
            throw new ObjectDisposedException(typeof(VertexDeclaration).Name);
        }
        VertexElementValidator.Validate(_vertexStride, _elements, device._profileCapabilities);
        DeclarationBinding binding = _binding;
        if (binding != null)
        {
            _parent.vertexDeclarationManager.ReleaseBinding(binding);
            _binding = null;
        }
        _binding = device.vertexDeclarationManager.CreateBinding(this);
        _parent = device;
    }
References Microsoft.Xna.Framework.Graphics.VertexDeclaration._binding, Microsoft.Xna.Framework.Graphics.VertexDeclaration._elements, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.VertexDeclaration._vertexStride, Microsoft.Xna.Framework.Graphics.DeclarationManager.CreateBinding(), Microsoft.Xna.Framework.Graphics.GraphicsResource.isDisposed, Microsoft.Xna.Framework.Graphics.GraphicsResource.Name, Microsoft.Xna.Framework.Graphics.DeclarationManager.ReleaseBinding(), Microsoft.Xna.Framework.Graphics.VertexElementValidator.Validate(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexDeclarationManager.
Referenced by Microsoft.Xna.Framework.Graphics.VertexBuffer.CreateBuffer().