Terraria: System.Collections.Queue.Enqueue
Enqueue() [2/2]
virtual void System.Collections.Queue.Enqueue (object? obj) inline virtual inherited
Definition at line 345 of file Queue.cs.
    {
        if (_size == _array.Length)
        {
            int num = (int)((long)_array.Length * (long)_growFactor / 100);
            if (num < _array.Length + 4)
            {
                num = _array.Length + 4;
            }
            SetCapacity(num);
        }
        _array[_tail] = obj;
        _tail = (_tail + 1) % _array.Length;
        _size++;
        _version++;
    }
References System.Collections.Queue._array, System.Collections.Queue._growFactor, System.Collections.Queue._size, System.Collections.Queue._tail, System.Collections.Queue._version, System.obj, and System.Collections.Queue.SetCapacity().
Referenced by System.Collections.Queue.Queue(), System.Collections.Queue.SynchronizedQueue.Enqueue(), and System.Runtime.Serialization.Formatter.Schedule().