Terraria: Microsoft.Xna.Framework.Graphics.VertexDeclaration.FromType
FromType()
static VertexDeclaration Microsoft.Xna.Framework.Graphics.VertexDeclaration.FromType (Type vertexType) inline static package
Definition at line 140 of file VertexDeclaration.cs.
    {
        if (vertexType == null)
        {
            throw new ArgumentNullException("vertexType", FrameworkResources.NullNotAllowed);
        }
        if (!vertexType.IsValueType)
        {
            throw new ArgumentException(string.Format(args: new object[1] { vertexType }, provider: CultureInfo.CurrentCulture, format: FrameworkResources.VertexTypeNotValueType));
        }
        if (!(Activator.CreateInstance(vertexType) is IVertexType { VertexDeclaration: var vertexDeclaration }))
        {
            throw new ArgumentException(string.Format(args: new object[1] { vertexType }, provider: CultureInfo.CurrentCulture, format: FrameworkResources.VertexTypeNotIVertexType));
        }
        if (vertexDeclaration == null)
        {
            throw new InvalidOperationException(string.Format(args: new object[1] { vertexType }, provider: CultureInfo.CurrentCulture, format: FrameworkResources.VertexTypeNullDeclaration));
        }
        if (Marshal.SizeOf(vertexType) != vertexDeclaration._vertexStride)
        {
            throw new InvalidOperationException(string.Format(args: new object[1] { vertexType }, provider: CultureInfo.CurrentCulture, format: FrameworkResources.VertexTypeWrongSize));
        }
        return vertexDeclaration;
    }
References System.Activator.CreateInstance(), System.Globalization.CultureInfo.CurrentCulture, System.Globalization.Format, System.format, System.Type.IsValueType, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, System.Runtime.InteropServices.Marshal.SizeOf(), Microsoft.Xna.Framework.FrameworkResources.VertexTypeNotIVertexType, Microsoft.Xna.Framework.FrameworkResources.VertexTypeNotValueType, Microsoft.Xna.Framework.FrameworkResources.VertexTypeNullDeclaration, and Microsoft.Xna.Framework.FrameworkResources.VertexTypeWrongSize.
Referenced by Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.DynamicVertexBuffer(), and Microsoft.Xna.Framework.Graphics.VertexBuffer.VertexBuffer().