Terraria: System.Linq.Expressions.Compiler.AssemblyGen.DefineType
DefineType()
TypeBuilder System.Linq.Expressions.Compiler.AssemblyGen.DefineType (string name, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type parent, TypeAttributes attr) inline private
Definition at line 37 of file AssemblyGen.cs.
    {
        ContractUtils.RequiresNotNull(name, "name");
        ContractUtils.RequiresNotNull(parent, "parent");
        StringBuilder stringBuilder = new StringBuilder(name);
        int value = Interlocked.Increment(ref _index);
        stringBuilder.Append('$');
        stringBuilder.Append(value);
        stringBuilder.Replace('+', '_').Replace('[', '_').Replace(']', '_')
            .Replace('*', '_')
            .Replace('&', '_')
            .Replace(',', '_')
            .Replace('\\', '_');
        name = stringBuilder.ToString();
        return _myModule.DefineType(name, attr, parent);
    }
References System.Linq.Expressions.Compiler.AssemblyGen._index, System.Linq.Expressions.Compiler.AssemblyGen._myModule, System.Text.StringBuilder.Append(), System.Reflection.Emit.ModuleBuilder.DefineType(), System.Threading.Interlocked.Increment(), System.Text.StringBuilder.Replace(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Text.StringBuilder.ToString(), and System.value.