Terraria: System.Reflection.Internal.EncodingHelper.DecodeUtf8Prefixed
DecodeUtf8Prefixed()
static unsafe string System.Reflection.Internal.EncodingHelper.DecodeUtf8Prefixed (byte * bytes, int byteCount, byte[] prefix, MetadataStringDecoder utf8Decoder) inline static private
Definition at line 33 of file EncodingHelper.cs.
    {
        int num = byteCount + prefix.Length;
        if (num == 0)
        {
            return string.Empty;
        }
        byte[] array = ArrayPool<byte>.Shared.Rent(num);
        prefix.CopyTo(array, 0);
        Marshal.Copy((IntPtr)bytes, array, prefix.Length, byteCount);
        string @string;
        fixed (byte* bytes2 = &array[0])
        {
            @string = utf8Decoder.GetString(bytes2, num);
        }
        ArrayPool<byte>.Shared.Return(array);
        return @string;
    }
References System.array, System.byteCount, System.bytes, System.Runtime.InteropServices.Marshal.Copy(), System.Reflection.Metadata.MetadataStringDecoder.GetString(), System.prefix, and System.Buffers.ArrayPool< T >.Shared.
Referenced by System.Reflection.Internal.EncodingHelper.DecodeUtf8().