Terraria: Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers
DrawPlayer_UseNormalLayers()
static void Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers (ref PlayerDrawSet drawInfo) inline static private
Definition at line 169 of file LegacyPlayerRenderer.cs.
    {
        PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_01_2_JimsCloak(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_03_Carpet(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_03_PortableStool(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_04_ElectrifiedDebuffBack(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_05_ForbiddenSetRing(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_05_2_SafemanSun(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_06_WebbedDebuffBack(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_08_Backpacks(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_08_1_Tails(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_09_Wings(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_01_BackHair(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_10_BackAcc(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_01_3_BackHead(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_11_Balloons(ref drawInfo);
        if (drawInfo.weaponDrawOrder == WeaponDrawOrder.BehindBackArm)
        {
            PlayerDrawLayers.DrawPlayer_27_HeldItem(ref drawInfo);
        }
        PlayerDrawLayers.DrawPlayer_12_Skin(ref drawInfo);
        if (drawInfo.drawPlayer.wearsRobe && drawInfo.drawPlayer.body != 166)
        {
            PlayerDrawLayers.DrawPlayer_14_Shoes(ref drawInfo);
            PlayerDrawLayers.DrawPlayer_13_Leggings(ref drawInfo);
        }
        else
        {
            PlayerDrawLayers.DrawPlayer_13_Leggings(ref drawInfo);
            PlayerDrawLayers.DrawPlayer_14_Shoes(ref drawInfo);
        }
        PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_15_SkinLongCoat(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_16_ArmorLongCoat(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_17_Torso(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_18_OffhandAcc(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_19_WaistAcc(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_20_NeckAcc(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_21_Head(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_21_1_Magiluminescence(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_22_FaceAcc(ref drawInfo);
        if (drawInfo.drawFrontAccInNeckAccLayer)
        {
            PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
            PlayerDrawLayers.DrawPlayer_32_FrontAcc_FrontPart(ref drawInfo);
            PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(ref drawInfo);
        }
        PlayerDrawLayers.DrawPlayer_23_MountFront(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_24_Pulley(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_JimsDroneRadio(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_32_FrontAcc_BackPart(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_25_Shield(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_extra_MountPlus(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_26_SolarShield(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_extra_MountMinus(ref drawInfo);
        if (drawInfo.weaponDrawOrder == WeaponDrawOrder.BehindFrontArm)
        {
            PlayerDrawLayers.DrawPlayer_27_HeldItem(ref drawInfo);
        }
        PlayerDrawLayers.DrawPlayer_28_ArmOverItem(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_29_OnhandAcc(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_30_BladedGlove(ref drawInfo);
        if (!drawInfo.drawFrontAccInNeckAccLayer)
        {
            PlayerDrawLayers.DrawPlayer_32_FrontAcc_FrontPart(ref drawInfo);
        }
        PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(ref drawInfo);
        if (drawInfo.weaponDrawOrder == WeaponDrawOrder.OverFrontArm)
        {
            PlayerDrawLayers.DrawPlayer_27_HeldItem(ref drawInfo);
        }
        PlayerDrawLayers.DrawPlayer_31_ProjectileOverArm(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_33_FrozenOrWebbedDebuff(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_34_ElectrifiedDebuffFront(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_35_IceBarrier(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_36_CTG(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_37_BeetleBuff(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_38_EyebrellaCloud(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_MakeIntoFirstFractalAfterImage(ref drawInfo);
    }
References Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_01_2_JimsCloak(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_01_3_BackHead(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_01_BackHair(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_03_Carpet(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_03_PortableStool(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_04_ElectrifiedDebuffBack(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_2_SafemanSun(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_ForbiddenSetRing(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_06_WebbedDebuffBack(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_08_1_Tails(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_08_Backpacks(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_10_BackAcc(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_11_Balloons(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_13_Leggings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_14_Shoes(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_15_SkinLongCoat(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_16_ArmorLongCoat(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_17_Torso(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_18_OffhandAcc(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_19_WaistAcc(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_20_NeckAcc(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_1_Magiluminescence(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_22_FaceAcc(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_23_MountFront(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_24_Pulley(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_25_Shield(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_26_SolarShield(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItem(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_29_OnhandAcc(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_30_BladedGlove(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_31_ProjectileOverArm(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_32_FrontAcc_BackPart(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_32_FrontAcc_FrontPart(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_33_FrozenOrWebbedDebuff(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_34_ElectrifiedDebuffFront(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_35_IceBarrier(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_36_CTG(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_37_BeetleBuff(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_38_EyebrellaCloud(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_extra_MountMinus(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_extra_MountPlus(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_extra_TorsoMinus(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_extra_TorsoPlus(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_JimsDroneRadio(), and Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_MakeIntoFirstFractalAfterImage().
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer().