Terraria: Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_MountTransformation
DrawPlayer_MountTransformation()
static void Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_MountTransformation (ref PlayerDrawSet drawInfo) inline static private
    {
        PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_23_MountFront(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_extra_MountPlus(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_26_SolarShield(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_extra_MountMinus(ref drawInfo);
    }
References Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_23_MountFront(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_26_SolarShield(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_extra_MountMinus(), and Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_extra_MountPlus().