Terraria: System.Collections.Generic.SortedSet.Enumerator.Enumerator
Enumerator() [2/2]
System.Collections.Generic.SortedSet< T >.Enumerator.Enumerator (SortedSet< T > set, bool reverse) inline package
Definition at line 276 of file SortedSet.cs.
        {
            _tree = set;
            set.VersionCheck();
            _version = set.version;
            _stack = new Stack<Node>(2 * SortedSet<T>.Log2(set.TotalCount() + 1));
            _current = null;
            _reverse = reverse;
            Initialize();
        }
References System.Collections.Generic.SortedSet< T >.Enumerator._current, System.Collections.Generic.SortedSet< T >.Enumerator._reverse, System.Collections.Generic.SortedSet< T >.Enumerator._stack, System.Collections.Generic.SortedSet< T >.Enumerator._tree, System.Collections.Generic.SortedSet< T >.Enumerator._version, System.Runtime.Serialization.Dictionary, System.Collections.Generic.SortedSet< T >.Enumerator.Initialize(), System.Collections.Generic.SortedSet< T >.Log2(), and System.Collections.Generic.SortedSet< T >.TotalCount().