Terraria: System.Collections.Generic.SortedSet.Enumerator.Reset
Reset() [1/2]
void System.Collections.Generic.SortedSet< T >.Enumerator.Reset () inline package
Implements System.Collections.IEnumerator.
Definition at line 356 of file SortedSet.cs.
        {
            if (_version != _tree.version)
            {
                throw new InvalidOperationException(System.SR.InvalidOperation_EnumFailedVersion);
            }
            _stack.Clear();
            Initialize();
        }
References System.Collections.Generic.SortedSet< T >.Enumerator._stack, System.Collections.Generic.SortedSet< T >.Enumerator._tree, System.Collections.Generic.SortedSet< T >.Enumerator._version, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.SortedSet< T >.Enumerator.Initialize(), and System.SR.InvalidOperation_EnumFailedVersion.
Referenced by System.Collections.Generic.SortedSet< T >.Enumerator.Reset().