Terraria: System.Data.Common.DataAdapter.FillFromReader
FillFromReader() [2/3]
int System.Data.Common.DataAdapter.FillFromReader (DataSet dataset, DataTable datatable, string srcTable, DataReaderContainer dataReader, int startRecord, int maxRecords, DataColumn parentChapterColumn, object parentChapterValue) inline package inherited
Definition at line 507 of file DataAdapter.cs.
    {
        int result = 0;
        int num = 0;
        do
        {
            if (0 >= dataReader.FieldCount)
            {
                continue;
            }
            SchemaMapping schemaMapping = FillMapping(dataset, datatable, srcTable, dataReader, num, parentChapterColumn, parentChapterValue);
            num++;
            if (schemaMapping == null || schemaMapping.DataValues == null || schemaMapping.DataTable == null)
            {
                continue;
            }
            schemaMapping.DataTable.BeginLoadData();
            try
            {
                if (1 == num && (0 < startRecord || 0 < maxRecords))
                {
                    result = FillLoadDataRowChunk(schemaMapping, startRecord, maxRecords);
                }
                else
                {
                    int num2 = FillLoadDataRow(schemaMapping);
                    if (1 == num)
                    {
                        result = num2;
                    }
                }
            }
            finally
            {
                schemaMapping.DataTable.EndLoadData();
            }
            if (datatable != null)
            {
                break;
            }
        }
        while (FillNextResult(dataReader));
        return result;
    }
References System.Data.DataTable.BeginLoadData(), System.Data.ProviderBase.SchemaMapping.DataTable, System.Data.ProviderBase.SchemaMapping.DataValues, System.Data.DataTable.EndLoadData(), System.Data.ProviderBase.DataReaderContainer.FieldCount, System.Data.Common.DataAdapter.FillLoadDataRow(), System.Data.Common.DataAdapter.FillLoadDataRowChunk(), System.Data.Common.DataAdapter.FillMapping(), and System.Data.Common.DataAdapter.FillNextResult().