Terraria: System.Data.Common.DataAdapter.Fill
Fill() [2/4]
virtual int System.Data.Common.DataAdapter.Fill (DataSet dataSet, string srcTable, IDataReader dataReader, int startRecord, int maxRecords) inline protected virtual inherited
Definition at line 376 of file DataAdapter.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<comm.DataAdapter.Fill|API> {0}, dataSet, srcTable, dataReader, startRecord, maxRecords", ObjectID);
        try
        {
            if (dataSet == null)
            {
                throw ADP.FillRequires("dataSet");
            }
            if (string.IsNullOrEmpty(srcTable))
            {
                throw ADP.FillRequiresSourceTableName("srcTable");
            }
            if (dataReader == null)
            {
                throw ADP.FillRequires("dataReader");
            }
            if (startRecord < 0)
            {
                throw ADP.InvalidStartRecord("startRecord", startRecord);
            }
            if (maxRecords < 0)
            {
                throw ADP.InvalidMaxRecords("maxRecords", maxRecords);
            }
            if (dataReader.IsClosed)
            {
                return 0;
            }
            DataReaderContainer dataReader2 = DataReaderContainer.Create(dataReader, ReturnProviderSpecificTypes);
            return FillFromReader(dataSet, null, srcTable, dataReader2, startRecord, maxRecords);
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.ProviderBase.DataReaderContainer.Create(), System.Data.Common.DataAdapter.FillFromReader(), System.Data.Common.ADP.FillRequires(), System.Data.Common.ADP.FillRequiresSourceTableName(), System.Data.Common.ADP.InvalidMaxRecords(), System.Data.Common.ADP.InvalidStartRecord(), System.Data.IDataReader.IsClosed, System.Data.DataCommonEventSource.Log, System.Data.Common.DataAdapter.ObjectID, and System.Data.Common.DataAdapter.ReturnProviderSpecificTypes.