Terraria: System.Data.Common.DataAdapter.FillLoadDataRowChunk
FillLoadDataRowChunk()
int System.Data.Common.DataAdapter.FillLoadDataRowChunk (SchemaMapping mapping, int startRecord, int maxRecords) inline private inherited
Definition at line 553 of file DataAdapter.cs.
    {
        DataReaderContainer dataReader = mapping.DataReader;
        while (0 < startRecord)
        {
            if (!dataReader.Read())
            {
                return 0;
            }
            startRecord--;
        }
        int num = 0;
        if (0 < maxRecords)
        {
            while (num < maxRecords && dataReader.Read())
            {
                if (_hasFillErrorHandler)
                {
                    try
                    {
                        mapping.LoadDataRowWithClear();
                        num++;
                    }
                    catch (Exception e) when (ADP.IsCatchableExceptionType(e))
                    {
                        ADP.TraceExceptionForCapture(e);
                        OnFillErrorHandler(e, mapping.DataTable, mapping.DataValues);
                    }
                }
                else
                {
                    mapping.LoadDataRow();
                    num++;
                }
            }
        }
        else
        {
            num = FillLoadDataRow(mapping);
        }
        return num;
    }
References System.Data.Common.DataAdapter._hasFillErrorHandler, System.Data.ProviderBase.SchemaMapping.DataReader, System.Data.ProviderBase.SchemaMapping.DataTable, System.Data.ProviderBase.SchemaMapping.DataValues, System.Data.Common.DataAdapter.FillLoadDataRow(), System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.ProviderBase.SchemaMapping.LoadDataRow(), System.Data.ProviderBase.SchemaMapping.LoadDataRowWithClear(), System.Data.Common.DataAdapter.OnFillErrorHandler(), System.Data.ProviderBase.DataReaderContainer.Read(), and System.Data.Common.ADP.TraceExceptionForCapture().
Referenced by System.Data.Common.DataAdapter.FillFromReader().