Terraria: System.Data.Common.DataAdapter.FillSchema
FillSchema() [3/3]
virtual ? DataTable System.Data.Common.DataAdapter.FillSchema (DataTable dataTable, SchemaType schemaType, IDataReader dataReader) inline protected virtual inherited
Definition at line 309 of file DataAdapter.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<comm.DataAdapter.FillSchema|API> {0}, dataTable, schemaType, dataReader", ObjectID);
        try
        {
            if (dataTable == null)
            {
                throw ADP.ArgumentNull("dataTable");
            }
            if (SchemaType.Source != schemaType && SchemaType.Mapped != schemaType)
            {
                throw ADP.InvalidSchemaType(schemaType);
            }
            if (dataReader == null || dataReader.IsClosed)
            {
                throw ADP.FillRequires("dataReader");
            }
            object obj = FillSchemaFromReader(null, dataTable, schemaType, null, dataReader);
            return (DataTable)obj;
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.Common.ADP.ArgumentNull(), System.Data.Common.ADP.FillRequires(), System.Data.Common.DataAdapter.FillSchemaFromReader(), System.Data.Common.ADP.InvalidSchemaType(), System.Data.IDataReader.IsClosed, System.Data.DataCommonEventSource.Log, System.obj, and System.Data.Common.DataAdapter.ObjectID.