Terraria: System.Data.Common.DataAdapter.FillNextResult
FillNextResult()
bool System.Data.Common.DataAdapter.FillNextResult (DataReaderContainer dataReader) inline private inherited
Definition at line 663 of file DataAdapter.cs.
    {
        bool result = true;
        if (_hasFillErrorHandler)
        {
            try
            {
                result = dataReader.NextResult();
            }
            catch (Exception e) when (ADP.IsCatchableExceptionType(e))
            {
                ADP.TraceExceptionForCapture(e);
                OnFillErrorHandler(e, null, null);
            }
        }
        else
        {
            result = dataReader.NextResult();
        }
        return result;
    }
References System.Data.Common.DataAdapter._hasFillErrorHandler, System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.ProviderBase.DataReaderContainer.NextResult(), System.Data.Common.DataAdapter.OnFillErrorHandler(), and System.Data.Common.ADP.TraceExceptionForCapture().
Referenced by System.Data.Common.DataAdapter.Fill(), and System.Data.Common.DataAdapter.FillFromReader().