Terraria: SelectionHolder.BindTo
BindTo()
void SelectionHolder< TCycleType >.BindTo (Preferences preferences) inline
     {
         preferences.OnLoad += Wrapped_Configuration_OnLoad;
         preferences.OnSave += Configuration_Save;
     }
References SelectionHolder< TCycleType >.Configuration_Save(), Preferences.OnLoad, Preferences.OnSave, and SelectionHolder< TCycleType >.Wrapped_Configuration_OnLoad().
Referenced by Main.BindSettingsTo().