Terraria: System.Linq.Expressions.ExpressionStringBuilder.VisitMemberInit
VisitMemberInit()
override Expression System.Linq.Expressions.ExpressionStringBuilder.VisitMemberInit (MemberInitExpression node) inline package virtual
Reimplemented from System.Linq.Expressions.ExpressionVisitor.
Definition at line 386 of file ExpressionStringBuilder.cs.
    {
        if (node.NewExpression.ArgumentCount == 0 && node.NewExpression.Type.Name.Contains('<'))
        {
            Out("new");
        }
        else
        {
            Visit(node.NewExpression);
        }
        Out(" {");
        int i = 0;
        for (int count = node.Bindings.Count; i < count; i++)
        {
            MemberBinding node2 = node.Bindings[i];
            if (i > 0)
            {
                Out(", ");
            }
            VisitMemberBinding(node2);
        }
        Out('}');
        return node;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Out, System.Linq.Expressions.ExpressionVisitor.Visit(), and System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding().