Terraria: DD2Event.WinInvasionInternal
WinInvasionInternal()
static void DD2Event.WinInvasionInternal () inline static private
     {
         if (OngoingDifficulty >= 1)
         {
             DownedInvasionT1 = true;
         }
         if (OngoingDifficulty >= 2)
         {
             DownedInvasionT2 = true;
         }
         if (OngoingDifficulty >= 3)
         {
             DownedInvasionT3 = true;
         }
         if (OngoingDifficulty == 1)
         {
             DropMedals(3);
         }
         if (OngoingDifficulty == 2)
         {
             DropMedals(15);
         }
         if (OngoingDifficulty == 3)
         {
             AchievementsHelper.NotifyProgressionEvent(23);
             DropMedals(60);
         }
         WorldGen.BroadcastText(NetworkText.FromKey("DungeonDefenders2.InvasionWin"), INFO_START_INVASION_COLOR);
     }
References WorldGen.BroadcastText(), DownedInvasionT1, DownedInvasionT2, DownedInvasionT3, DropMedals(), NetworkText.FromKey(), INFO_START_INVASION_COLOR, AchievementsHelper.NotifyProgressionEvent(), and OngoingDifficulty.
Referenced by StopInvasion().