Terraria: DD2Event.GetEnemiesForWave
GetEnemiesForWave()
static short [] DD2Event.GetEnemiesForWave (int wave) inline static private
     {
         return OngoingDifficulty switch
         {
             3 => Difficulty_3_GetEnemiesForWave(wave),
             2 => Difficulty_2_GetEnemiesForWave(wave),
             _ => Difficulty_1_GetEnemiesForWave(wave),
         };
     }
References Difficulty_1_GetEnemiesForWave(), Difficulty_2_GetEnemiesForWave(), Difficulty_3_GetEnemiesForWave(), and OngoingDifficulty.
Referenced by UpdateTime().