Terraria: DD2Event.SummonCrystalDirect
SummonCrystalDirect()
static void DD2Event.SummonCrystalDirect (int x, int y, int whoAsks) inline static
     {
         if (!NPC.AnyNPCs(548))
         {
             Tile tileSafely = Framing.GetTileSafely(x, y);
             if (tileSafely.active() && tileSafely.type == 466)
             {
                 Point point = new Point(x * 16, y * 16);
                 point.X -= tileSafely.frameX / 18 * 16;
                 point.Y -= tileSafely.frameY / 18 * 16;
                 point.X += 40;
                 point.Y += 64;
                 StartInvasion();
                 NPC.NewNPC(Main.player[whoAsks].GetNPCSource_TileInteraction(x, y), point.X, point.Y, 548);
                 DropStarterCrystals();
             }
         }
     }
References Tile.active(), NPC.AnyNPCs(), DropStarterCrystals(), Tile.frameX, Tile.frameY, Player.GetNPCSource_TileInteraction(), Framing.GetTileSafely(), NPC.NewNPC(), Main.player, StartInvasion(), and Tile.type.
Referenced by SummonCrystal().