Terraria: DD2Event.StartInvasion
StartInvasion()
static void DD2Event.StartInvasion (int difficultyOverride = -1) inline static
     {
         if (Main.netMode != 1)
         {
             _crystalsDropping_toDrop = 0;
             _crystalsDropping_alreadyDropped = 0;
             _crystalsDropping_lastWave = 0;
             _timeLeftUntilSpawningBegins = 0;
             Ongoing = true;
             FindProperDifficulty();
             if (difficultyOverride != -1)
             {
                 OngoingDifficulty = difficultyOverride;
             }
             _deadGoblinSpots.Clear();
             _downedDarkMageT1 = false;
             _downedOgreT2 = false;
             _spawnedBetsyT3 = false;
             LostThisRun = false;
             WonThisRun = false;
             NPC.totalInvasionPoints = 0f;
             NPC.waveKills = 0f;
             NPC.waveNumber = 1;
             ClearAllTowersInGame();
             WorldGen.BroadcastText(NetworkText.FromKey("DungeonDefenders2.InvasionStart"), INFO_START_INVASION_COLOR);
             NetMessage.SendData(7);
             if (Main.netMode != 1)
             {
                 Main.ReportInvasionProgress(0, 1, 3, 1);
             }
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(78, -1, -1, null, 0, 1f, 3f, 1f);
             }
             SetEnemySpawningOnHold(300);
             WipeEntities();
         }
     }
References _crystalsDropping_alreadyDropped, _crystalsDropping_lastWave, _crystalsDropping_toDrop, _deadGoblinSpots, _downedDarkMageT1, _downedOgreT2, _spawnedBetsyT3, _timeLeftUntilSpawningBegins, WorldGen.BroadcastText(), ClearAllTowersInGame(), FindProperDifficulty(), NetworkText.FromKey(), INFO_START_INVASION_COLOR, LostThisRun, Main.netMode, Ongoing, OngoingDifficulty, Main.ReportInvasionProgress(), NetMessage.SendData(), SetEnemySpawningOnHold(), NPC.totalInvasionPoints, NPC.waveKills, NPC.waveNumber, WipeEntities(), and WonThisRun.
Referenced by SummonCrystalDirect().