Terraria: DD2Event.RaiseGoblins
RaiseGoblins()
static void DD2Event.RaiseGoblins (NPC caller, Vector2 spot) inline static
     {
         List<Vector2> list = new List<Vector2>();
         foreach (Vector2 deadGoblinSpot in _deadGoblinSpots)
         {
             if (Vector2.DistanceSquared(deadGoblinSpot, spot) <= 722500f)
             {
                 list.Add(deadGoblinSpot);
             }
         }
         foreach (Vector2 item in list)
         {
             _deadGoblinSpots.Remove(item);
         }
         int num = 0;
         foreach (Vector2 item2 in list)
         {
             Point origin = item2.ToTileCoordinates();
             origin.X += Main.rand.Next(-15, 16);
             if (WorldUtils.Find(origin, Searches.Chain(new Searches.Down(50), new Conditions.IsSolid()), out var result))
             {
                 if (OngoingDifficulty == 3)
                 {
                     NPC.NewNPC(caller.GetSpawnSourceForNPCFromNPCAI(), result.X * 16 + 8, result.Y * 16, 567);
                 }
                 else
                 {
                     NPC.NewNPC(caller.GetSpawnSourceForNPCFromNPCAI(), result.X * 16 + 8, result.Y * 16, 566);
                 }
                 if (++num >= 8)
                 {
                     break;
                 }
             }
         }
     }
References _deadGoblinSpots, Searches.Chain(), WorldUtils.Find(), NPC.NewNPC(), UnifiedRandom.Next(), OngoingDifficulty, and Main.rand.
Referenced by NPC.AI_109_DarkMage().