Terraria: DD2Event.RequestToSkipWaitTime
RequestToSkipWaitTime()
static void DD2Event.RequestToSkipWaitTime (int x, int y) inline static
     {
         if (TimeLeftBetweenWaves > 60 && IsStandActive(x, y))
         {
             SoundEngine.PlaySound(SoundID.NPCDeath7, x * 16 + 8, y * 16 + 8);
             if (Main.netMode == 0)
             {
                 AttemptToSkipWaitTime();
             }
             else if (Main.netMode != 2)
             {
                 NetMessage.SendData(143);
             }
         }
     }
References AttemptToSkipWaitTime(), IsStandActive(), Main.netMode, SoundID.NPCDeath7, SoundEngine.PlaySound(), NetMessage.SendData(), and TimeLeftBetweenWaves.
Referenced by Player.TileInteractionsUse().