Terraria: DD2Event.SummonBetsy
SummonBetsy()
static void DD2Event.SummonBetsy () inline static private
     {
         if (!_spawnedBetsyT3 && !NPC.AnyNPCs(551))
         {
             Vector2 position = new Vector2(1f, 1f);
             int num = NPC.FindFirstNPC(548);
             if (num != -1)
             {
                 position = Main.npc[num].Center;
             }
             NPC.SpawnOnPlayer(Player.FindClosest(position, 1, 1), 551);
             _spawnedBetsyT3 = true;
         }
     }
References _spawnedBetsyT3, NPC.AnyNPCs(), Entity.Center, Player.FindClosest(), NPC.FindFirstNPC(), Main.npc, and NPC.SpawnOnPlayer().
Referenced by UpdateTime().