Terraria: DD2Event.GetInvasionStatus
GetInvasionStatus()
static void DD2Event.GetInvasionStatus (out int currentWave, out int requiredKillCount, out int currentKillCount, bool currentlyInCheckProgress = false) inline static private
     {
         currentWave = NPC.waveNumber;
         requiredKillCount = 10;
         currentKillCount = (int)NPC.waveKills;
         switch (OngoingDifficulty)
         {
         case 3:
             requiredKillCount = Difficulty_3_GetRequiredWaveKills(ref currentWave, ref currentKillCount, currentlyInCheckProgress);
             break;
         case 2:
             requiredKillCount = Difficulty_2_GetRequiredWaveKills(ref currentWave, ref currentKillCount, currentlyInCheckProgress);
             break;
         default:
             requiredKillCount = Difficulty_1_GetRequiredWaveKills(ref currentWave, ref currentKillCount, currentlyInCheckProgress);
             break;
         }
     }
References Difficulty_1_GetRequiredWaveKills(), Difficulty_2_GetRequiredWaveKills(), Difficulty_3_GetRequiredWaveKills(), OngoingDifficulty, NPC.waveKills, and NPC.waveNumber.
Referenced by CheckProgress(), Difficulty_1_SpawnMonsterFromGate(), Difficulty_2_SpawnMonsterFromGate(), ReportEventProgress(), ShouldDropCrystals(), SyncInvasionProgress(), and UpdateTime().