Terraria: DD2Event.ShouldDropCrystals
ShouldDropCrystals()
static bool DD2Event.ShouldDropCrystals () inline static
     {
         GetInvasionStatus(out var currentWave, out var requiredKillCount, out var currentKillCount);
         if (_crystalsDropping_lastWave < currentWave)
         {
             _crystalsDropping_lastWave++;
             if (_crystalsDropping_alreadyDropped > 0)
             {
                 _crystalsDropping_alreadyDropped -= _crystalsDropping_toDrop;
             }
             if (OngoingDifficulty == 1)
             {
                 switch (currentWave)
                 {
                 case 1:
                     _crystalsDropping_toDrop = 20;
                     break;
                 case 2:
                     _crystalsDropping_toDrop = 20;
                     break;
                 case 3:
                     _crystalsDropping_toDrop = 30;
                     break;
                 case 4:
                     _crystalsDropping_toDrop = 30;
                     break;
                 case 5:
                     _crystalsDropping_toDrop = 40;
                     break;
                 }
             }
             else if (OngoingDifficulty == 2)
             {
                 switch (currentWave)
                 {
                 case 1:
                     _crystalsDropping_toDrop = 20;
                     break;
                 case 2:
                     _crystalsDropping_toDrop = 20;
                     break;
                 case 3:
                     _crystalsDropping_toDrop = 20;
                     break;
                 case 4:
                     _crystalsDropping_toDrop = 20;
                     break;
                 case 5:
                     _crystalsDropping_toDrop = 20;
                     break;
                 case 6:
                     _crystalsDropping_toDrop = 30;
                     break;
                 case 7:
                     _crystalsDropping_toDrop = 30;
                     break;
                 }
             }
             else if (OngoingDifficulty == 3)
             {
                 switch (currentWave)
                 {
                 case 1:
                     _crystalsDropping_toDrop = 20;
                     break;
                 case 2:
                     _crystalsDropping_toDrop = 20;
                     break;
                 case 3:
                     _crystalsDropping_toDrop = 20;
                     break;
                 case 4:
                     _crystalsDropping_toDrop = 20;
                     break;
                 case 5:
                     _crystalsDropping_toDrop = 30;
                     break;
                 case 6:
                     _crystalsDropping_toDrop = 30;
                     break;
                 case 7:
                     _crystalsDropping_toDrop = 30;
                     break;
                 }
             }
         }
         if (Main.netMode != 0 && Main.expertMode)
         {
             _crystalsDropping_toDrop = (int)((float)_crystalsDropping_toDrop * NPC.GetBalance());
         }
         float num = (float)currentKillCount / (float)requiredKillCount;
         if ((float)_crystalsDropping_alreadyDropped < (float)_crystalsDropping_toDrop * num)
         {
             _crystalsDropping_alreadyDropped++;
             return true;
         }
         return false;
     }
References _crystalsDropping_alreadyDropped, _crystalsDropping_lastWave, _crystalsDropping_toDrop, Main.expertMode, NPC.GetBalance(), GetInvasionStatus(), Main.netMode, and OngoingDifficulty.
Referenced by NPC.DoDeathEvents().