Terraria: DD2Event.LoseInvasionMessage
LoseInvasionMessage()
static void DD2Event.LoseInvasionMessage () inline static
     {
         WorldGen.BroadcastText(NetworkText.FromKey("DungeonDefenders2.InvasionLose"), INFO_FAILURE_INVASION_COLOR);
     }
References WorldGen.BroadcastText(), NetworkText.FromKey(), and INFO_FAILURE_INVASION_COLOR.
Referenced by UpdateTime().