Terraria: Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.BuildContainer
BuildContainer()
void Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.BuildContainer () inline private
Definition at line 43 of file UIBestiaryFilteringOptionsGrid.cs.
    {
        GetDisplaySettings(out var _, out var _, out var widthWithSpacing, out var heightWithSpacing, out var perRow, out var _, out var _, out var howManyRows);
        UIPanel uIPanel = new UIPanel
        {
            Width = new StyleDimension(perRow * widthWithSpacing + 10, 0f),
            Height = new StyleDimension(howManyRows * heightWithSpacing + 10, 0f),
            HAlign = 1f,
            VAlign = 0f,
            Left = new StyleDimension(0f, 0f),
            Top = new StyleDimension(0f, 0f)
        };
        uIPanel.BorderColor = new Color(89, 116, 213, 255) * 0.9f;
        uIPanel.BackgroundColor = new Color(73, 94, 171) * 0.9f;
        uIPanel.SetPadding(0f);
        Append(uIPanel);
        _container = uIPanel;
    }
References Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid._container, Terraria.UI.UIElement.Append(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.GetDisplaySettings(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UIBestiaryFilteringOptionsGrid().