Terraria: Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.SetupAvailabilityTest
SetupAvailabilityTest()
void Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.SetupAvailabilityTest (List< BestiaryEntry > allAvailableEntries) inline
Definition at line 62 of file UIBestiaryFilteringOptionsGrid.cs.
    {
        _filterAvailabilityTests.Clear();
        for (int i = 0; i < _filterer.AvailableFilters.Count; i++)
        {
            List<BestiaryEntry> list = new List<BestiaryEntry>();
            _filterAvailabilityTests.Add(list);
            IBestiaryEntryFilter bestiaryEntryFilter = _filterer.AvailableFilters[i];
            for (int j = 0; j < allAvailableEntries.Count; j++)
            {
                if (bestiaryEntryFilter.FitsFilter(allAvailableEntries[j]))
                {
                    list.Add(allAvailableEntries[j]);
                }
            }
        }
    }
References Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid._filterAvailabilityTests, Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid._filterer, System.Collections.Generic.List< T >.Add(), Terraria.DataStructures.EntryFilterer< T, U >.AvailableFilters, System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Generic.List< T >.Count, and System.list.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage().