Terraria: Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.GetDisplaySettings
GetDisplaySettings()
void Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.GetDisplaySettings (out int widthPerButton, out int heightPerButton, out int widthWithSpacing, out int heightWithSpacing, out int perRow, out float offsetLeft, out float offsetTop, out int howManyRows) inline private
Definition at line 160 of file UIBestiaryFilteringOptionsGrid.cs.
    {
        widthPerButton = 32;
        heightPerButton = 32;
        int num = 2;
        widthWithSpacing = widthPerButton + num;
        heightWithSpacing = heightPerButton + num;
        perRow = (int)Math.Ceiling(Math.Sqrt(_filterer.AvailableFilters.Count));
        perRow = 12;
        howManyRows = (int)Math.Ceiling((float)_filterer.AvailableFilters.Count / (float)perRow);
        offsetLeft = (float)(perRow * widthWithSpacing - num) * 0.5f;
        offsetTop = (float)(howManyRows * heightWithSpacing - num) * 0.5f;
        offsetLeft = 6f;
        offsetTop = 6f;
    }
References Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid._filterer, and Terraria.DataStructures.EntryFilterer< T, U >.AvailableFilters.
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.BuildContainer(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.GetEntriesToShow(), and Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateAvailability().