Terraria: System.Security.Cryptography.Pkcs.Pkcs12Kdf.CircularCopyUtf16BE
CircularCopyUtf16BE() [2/2]
static void System.Security.Cryptography.Pkcs.Pkcs12Kdf.CircularCopyUtf16BE (ReadOnlySpan< char > password, Span< byte > destination) inline static private
Definition at line 141 of file Pkcs12Kdf.cs.
    {
        int num = password.Length * 2;
        Encoding bigEndianUnicode = Encoding.BigEndianUnicode;
        while (destination.Length > 0)
        {
            if (destination.Length >= num)
            {
                int bytes = bigEndianUnicode.GetBytes(password, destination);
                if (bytes != num)
                {
                    throw new CryptographicException();
                }
                destination = destination.Slice(bytes);
                Span<byte> span = destination.Slice(0, Math.Min(2, destination.Length));
                span.Clear();
                destination = destination.Slice(span.Length);
                continue;
            }
            ReadOnlySpan<char> chars = password.Slice(0, destination.Length / 2);
            int bytes2 = bigEndianUnicode.GetBytes(chars, destination);
            if (bytes2 != destination.Length)
            {
                throw new CryptographicException();
            }
            break;
        }
    }
References System.Text.Encoding.BigEndianUnicode, System.bytes, System.chars, System.Span< T >.Clear(), System.destination, System.Text.Encoding.GetBytes(), System.Span< T >.Length, System.Math.Min(), System.ReadOnlySpan< T >.Slice(), and System.Span< T >.Slice().