Terraria: System.Net.SSPISecureChannelType.QueryContextAttributes
QueryContextAttributes() [3/3]
unsafe int System.Net.SSPISecureChannelType.QueryContextAttributes (System::Net::Security::SafeDeleteContext phContext, global::Interop::SspiCli::ContextAttribute attribute, Span< byte > buffer, Type handleType, out SafeHandle refHandle) inline
Implements System.Net.ISSPIInterface.
Definition at line 89 of file SSPISecureChannelType.cs.
    {
        refHandle = null;
        if (handleType != null)
        {
            if (handleType == typeof(System.Net.Security.SafeFreeContextBuffer))
            {
                refHandle = System.Net.Security.SafeFreeContextBuffer.CreateEmptyHandle();
            }
            else
            {
                if (!(handleType == typeof(System.Net.Security.SafeFreeCertContext)))
                {
                    throw new ArgumentException(System.SR.Format(System.SR.SSPIInvalidHandleType, handleType.FullName), "handleType");
                }
                refHandle = new System.Net.Security.SafeFreeCertContext();
            }
        }
        fixed (byte* buffer2 = buffer)
        {
            return System.Net.Security.SafeFreeContextBuffer.QueryContextAttributes(phContext, attribute, buffer2, refHandle);
        }
    }
References System.buffer, System.Net.Security.SafeFreeContextBuffer.CreateEmptyHandle(), System.SR.Format(), System.Type.FullName, System.Net.Security.SafeFreeContextBuffer.QueryContextAttributes(), and System.SR.SSPIInvalidHandleType.