Terraria: Terraria.IO.WorldFileData.MoveToLocal
MoveToLocal()
override void Terraria.IO.WorldFileData.MoveToLocal () inline
Definition at line 225 of file WorldFileData.cs.
    {
        if (base.IsCloudSave)
        {
            string worldPathFromName = Main.GetWorldPathFromName(Name, cloudSave: false);
            if (FileUtilities.MoveToLocal(base.Path, worldPathFromName))
            {
                Main.CloudFavoritesData.ClearEntry(this);
                _isCloudSave = false;
                _path = worldPathFromName;
                Main.LocalFavoriteData.SaveFavorite(this);
            }
        }
    }
References Terraria.IO.FileData._isCloudSave, Terraria.IO.FileData._path, Terraria.Main.CloudFavoritesData, Terraria.Main.GetWorldPathFromName(), Terraria.Main.LocalFavoriteData, Terraria.Utilities.FileUtilities.MoveToLocal(), and Terraria.IO.FileData.Name.
Referenced by Terraria.GameContent.UI.Elements.UIWorldListItem.CloudButtonClick().