Terraria: Terraria.IO.WorldFileData.FromInvalidWorld
FromInvalidWorld()
static WorldFileData Terraria.IO.WorldFileData.FromInvalidWorld (string path, bool cloudSave) inline static
Definition at line 165 of file WorldFileData.cs.
    {
        WorldFileData worldFileData = new WorldFileData(path, cloudSave);
        worldFileData.GameMode = 0;
        worldFileData.SetSeedToEmpty();
        worldFileData.WorldGeneratorVersion = 0uL;
        worldFileData.Metadata = FileMetadata.FromCurrentSettings(FileType.World);
        worldFileData.SetWorldSize(1, 1);
        worldFileData.HasCorruption = true;
        worldFileData.IsHardMode = false;
        worldFileData.IsValid = false;
        worldFileData.Name = FileUtilities.GetFileName(path, includeExtension: false);
        worldFileData.UniqueId = Guid.Empty;
        if (!cloudSave)
        {
            worldFileData.CreationTime = File.GetCreationTime(path);
        }
        else
        {
            worldFileData.CreationTime = DateTime.Now;
        }
        return worldFileData;
    }
References Terraria.IO.WorldFileData.WorldFileData(), System.Guid.Empty, Terraria.IO.FileMetadata.FromCurrentSettings(), System.IO.File.GetCreationTime(), Terraria.Utilities.FileUtilities.GetFileName(), System.DateTime.Now, Terraria.IO.WorldFileData.SetSeedToEmpty(), and Terraria.IO.WorldFileData.SetWorldSize().
Referenced by Terraria.IO.WorldFile.GetAllMetadata(), Terraria.Main.LoadWorlds(), and Terraria.GameContent.UI.States.UIWorkshopWorldImport.UpdateWorkshopWorldList().