Terraria: Terraria.IO.WorldFileData.CopyToLocal
CopyToLocal()
void Terraria.IO.WorldFileData.CopyToLocal (string newFileName = null, string newDisplayName = null) inline
Definition at line 248 of file WorldFileData.cs.
    {
        if (!base.IsCloudSave)
        {
            if (newFileName == null)
            {
                newFileName = Guid.NewGuid().ToString();
            }
            string worldPathFromName = Main.GetWorldPathFromName(newFileName, cloudSave: false);
            FileUtilities.Copy(base.Path, worldPathFromName, cloud: false);
            _path = worldPathFromName;
            if (newDisplayName != null)
            {
                WorldGen.RenameWorld(this, newDisplayName, OnWorldRenameSuccess);
            }
        }
    }
References Terraria.IO.FileData._path, Terraria.Utilities.FileUtilities.Copy(), Terraria.Main.GetWorldPathFromName(), System.Guid.NewGuid(), Terraria.IO.WorldFileData.OnWorldRenameSuccess(), and Terraria.WorldGen.RenameWorld().
Referenced by Terraria.Social.Steam.WorkshopSocialModule.ImportDownloadedWorldToLocalSaves().