Terraria: Terraria.IO.WorldFileData.OnWorldRenameSuccess
OnWorldRenameSuccess()
void Terraria.IO.WorldFileData.OnWorldRenameSuccess (string newWorldName) inline private
Definition at line 266 of file WorldFileData.cs.
    {
        Name = newWorldName;
        Main.DelayedProcesses.Add(DelayedGoToTitleScreen());
    }
References Terraria.IO.WorldFileData.DelayedGoToTitleScreen(), Terraria.Main.DelayedProcesses, and Terraria.IO.FileData.Name.
Referenced by Terraria.IO.WorldFileData.CopyToLocal(), and Terraria.IO.WorldFileData.Rename().