Terraria: Terraria.IO.WorldFileData.GetWorldName
GetWorldName()
string Terraria.IO.WorldFileData.GetWorldName (bool allowCropping = false) inline
Definition at line 80 of file WorldFileData.cs.
    {
        string text = Name;
        if (text == null)
        {
            return text;
        }
        if (allowCropping)
        {
            int num = 530;
            text = FontAssets.MouseText.Value.CreateCroppedText(text, (float)num);
        }
        return text;
    }
References Terraria.GameContent.FontAssets.MouseText, Terraria.IO.FileData.Name, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawSelf(), and Terraria.GameContent.UI.Elements.UIWorldListItem.DrawSelf().