Terraria: System.IO.Pipes.NamedPipeClientStream.ConnectInternal
ConnectInternal()
void System.IO.Pipes.NamedPipeClientStream.ConnectInternal (int timeout, CancellationToken cancellationToken, int startTime) inline private
Definition at line 144 of file NamedPipeClientStream.cs.
    {
        int num = 0;
        SpinWait spinWait = default(SpinWait);
        do
        {
            cancellationToken.ThrowIfCancellationRequested();
            int num2 = timeout - num;
            if (cancellationToken.CanBeCanceled && num2 > 50)
            {
                num2 = 50;
            }
            if (TryConnect(num2, cancellationToken))
            {
                return;
            }
            spinWait.SpinOnce();
        }
        while (timeout == -1 || (num = Environment.TickCount - startTime) < timeout);
        throw new TimeoutException();
    }
References System.cancellationToken, System.Threading.SpinWait.SpinOnce(), System.Environment.TickCount, System.timeout, and System.IO.Pipes.NamedPipeClientStream.TryConnect().
Referenced by System.IO.Pipes.NamedPipeClientStream.Connect(), and System.IO.Pipes.NamedPipeClientStream.ConnectAsync().