Terraria: System.IO.Pipes.NamedPipeClientStream.TryConnect
TryConnect()
bool System.IO.Pipes.NamedPipeClientStream.TryConnect (int timeout, CancellationToken cancellationToken) inline private
Definition at line 224 of file NamedPipeClientStream.cs.
    {
        global::Interop.Kernel32.SECURITY_ATTRIBUTES secAttrs = PipeStream.GetSecAttrs(_inheritability);
        int num = (int)(_pipeOptions & ~PipeOptions.CurrentUserOnly);
        if (_impersonationLevel != 0)
        {
            num |= 0x100000;
            num |= (int)(_impersonationLevel - 1) << 16;
        }
        int num2 = 0;
        if ((PipeDirection.In & _direction) != 0)
        {
            num2 |= int.MinValue;
        }
        if ((PipeDirection.Out & _direction) != 0)
        {
            num2 |= 0x40000000;
        }
        SafePipeHandle safePipeHandle = global::Interop.Kernel32.CreateNamedPipeClient(_normalizedPipePath, num2, FileShare.None, ref secAttrs, FileMode.Open, num, IntPtr.Zero);
        if (safePipeHandle.IsInvalid)
        {
            int lastPInvokeError = Marshal.GetLastPInvokeError();
            if (lastPInvokeError != 231 && lastPInvokeError != 2)
            {
                throw System.IO.Win32Marshal.GetExceptionForWin32Error(lastPInvokeError);
            }
            if (!global::Interop.Kernel32.WaitNamedPipe(_normalizedPipePath, timeout))
            {
                lastPInvokeError = Marshal.GetLastPInvokeError();
                if (lastPInvokeError == 2 || lastPInvokeError == 121)
                {
                    return false;
                }
                throw System.IO.Win32Marshal.GetExceptionForWin32Error(lastPInvokeError);
            }
            safePipeHandle = global::Interop.Kernel32.CreateNamedPipeClient(_normalizedPipePath, num2, FileShare.None, ref secAttrs, FileMode.Open, num, IntPtr.Zero);
            if (safePipeHandle.IsInvalid)
            {
                lastPInvokeError = Marshal.GetLastPInvokeError();
                if (lastPInvokeError == 231)
                {
                    return false;
                }
                throw System.IO.Win32Marshal.GetExceptionForWin32Error(lastPInvokeError);
            }
        }
        InitializeHandle(safePipeHandle, isExposed: false, (_pipeOptions & PipeOptions.Asynchronous) != 0);
        base.State = PipeState.Connected;
        ValidateRemotePipeUser();
        return true;
    }
References System.IO.Pipes.NamedPipeClientStream._direction, System.IO.Pipes.NamedPipeClientStream._impersonationLevel, System.IO.Pipes.NamedPipeClientStream._inheritability, System.IO.Pipes.NamedPipeClientStream._normalizedPipePath, System.IO.Pipes.NamedPipeClientStream._pipeOptions, System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.IO.Pipes.PipeStream.GetSecAttrs(), System.IO.Pipes.PipeStream.InitializeHandle(), Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, System.timeout, System.IO.Pipes.NamedPipeClientStream.ValidateRemotePipeUser(), and System.IntPtr.Zero.
Referenced by System.IO.Pipes.NamedPipeClientStream.ConnectInternal().