Terraria: System.IO.Pipes.NamedPipeClientStream.ValidateRemotePipeUser
ValidateRemotePipeUser()
void System.IO.Pipes.NamedPipeClientStream.ValidateRemotePipeUser () inline private
Definition at line 276 of file NamedPipeClientStream.cs.
    {
        if (!base.IsCurrentUserOnly)
        {
            return;
        }
        PipeSecurity accessControl = this.GetAccessControl();
        IdentityReference owner = accessControl.GetOwner(typeof(SecurityIdentifier));
        using WindowsIdentity windowsIdentity = WindowsIdentity.GetCurrent();
        SecurityIdentifier owner2 = windowsIdentity.Owner;
        if (owner != owner2)
        {
            base.State = PipeState.Closed;
            throw new UnauthorizedAccessException(System.SR.UnauthorizedAccess_NotOwnedByCurrentUser);
        }
    }
References System.Security.Principal.WindowsIdentity.GetCurrent(), System.Security.AccessControl.ObjectSecurity< T >.GetOwner(), and System.SR.UnauthorizedAccess_NotOwnedByCurrentUser.
Referenced by System.IO.Pipes.NamedPipeClientStream.TryConnect().