Terraria: UIManageControls.CreatePanel
CreatePanel()
UIElement UIManageControls.CreatePanel (string bind, InputMode currentInputMode, Color color) inline
     {
         switch (bind)
         {
         case "sp1":
         {
             UIKeybindingToggleListItem uIKeybindingToggleListItem5 = new UIKeybindingToggleListItem(() => Lang.menu[196].Value, () => PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadSnap1"].Contains(Buttons.DPadUp.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadSnap2"].Contains(Buttons.DPadRight.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadSnap3"].Contains(Buttons.DPadDown.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadSnap4"].Contains(Buttons.DPadLeft.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadSnap1"].Contains(Buttons.DPadUp.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadSnap2"].Contains(Buttons.DPadRight.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadSnap3"].Contains(Buttons.DPadDown.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadSnap4"].Contains(Buttons.DPadLeft.ToString()), color);
             uIKeybindingToggleListItem5.OnLeftClick += SnapButtonClick;
             return uIKeybindingToggleListItem5;
         }
         case "sp2":
         {
             UIKeybindingToggleListItem uIKeybindingToggleListItem4 = new UIKeybindingToggleListItem(() => Lang.menu[197].Value, () => PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadRadial1"].Contains(Buttons.DPadUp.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadRadial2"].Contains(Buttons.DPadRight.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadRadial3"].Contains(Buttons.DPadDown.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus["DpadRadial4"].Contains(Buttons.DPadLeft.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadRadial1"].Contains(Buttons.DPadUp.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadRadial2"].Contains(Buttons.DPadRight.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadRadial3"].Contains(Buttons.DPadDown.ToString()) && PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus["DpadRadial4"].Contains(Buttons.DPadLeft.ToString()), color);
             uIKeybindingToggleListItem4.OnLeftClick += RadialButtonClick;
             return uIKeybindingToggleListItem4;
         }
         case "sp3":
             return new UIKeybindingSliderItem(() => Lang.menu[199].Value + " (" + PlayerInput.CurrentProfile.TriggersDeadzone.ToString("P1") + ")", () => PlayerInput.CurrentProfile.TriggersDeadzone, delegate(float f)
             {
                 PlayerInput.CurrentProfile.TriggersDeadzone = f;
             }, delegate
             {
                 PlayerInput.CurrentProfile.TriggersDeadzone = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.TriggersDeadzone, 0f, 0.95f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
             }, 1000, color);
         case "sp4":
             return new UIKeybindingSliderItem(() => Lang.menu[200].Value + " (" + PlayerInput.CurrentProfile.InterfaceDeadzoneX.ToString("P1") + ")", () => PlayerInput.CurrentProfile.InterfaceDeadzoneX, delegate(float f)
             {
                 PlayerInput.CurrentProfile.InterfaceDeadzoneX = f;
             }, delegate
             {
                 PlayerInput.CurrentProfile.InterfaceDeadzoneX = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0f, 0.95f, 0.35f, 0.35f);
             }, 1001, color);
         case "sp5":
             return new UIKeybindingSliderItem(() => Lang.menu[201].Value + " (" + PlayerInput.CurrentProfile.LeftThumbstickDeadzoneX.ToString("P1") + ")", () => PlayerInput.CurrentProfile.LeftThumbstickDeadzoneX, delegate(float f)
             {
                 PlayerInput.CurrentProfile.LeftThumbstickDeadzoneX = f;
             }, delegate
             {
                 PlayerInput.CurrentProfile.LeftThumbstickDeadzoneX = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.LeftThumbstickDeadzoneX, 0f, 0.95f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
             }, 1002, color);
         case "sp6":
             return new UIKeybindingSliderItem(() => Lang.menu[202].Value + " (" + PlayerInput.CurrentProfile.LeftThumbstickDeadzoneY.ToString("P1") + ")", () => PlayerInput.CurrentProfile.LeftThumbstickDeadzoneY, delegate(float f)
             {
                 PlayerInput.CurrentProfile.LeftThumbstickDeadzoneY = f;
             }, delegate
             {
                 PlayerInput.CurrentProfile.LeftThumbstickDeadzoneY = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.LeftThumbstickDeadzoneY, 0f, 0.95f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
             }, 1003, color);
         case "sp7":
             return new UIKeybindingSliderItem(() => Lang.menu[203].Value + " (" + PlayerInput.CurrentProfile.RightThumbstickDeadzoneX.ToString("P1") + ")", () => PlayerInput.CurrentProfile.RightThumbstickDeadzoneX, delegate(float f)
             {
                 PlayerInput.CurrentProfile.RightThumbstickDeadzoneX = f;
             }, delegate
             {
                 PlayerInput.CurrentProfile.RightThumbstickDeadzoneX = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.RightThumbstickDeadzoneX, 0f, 0.95f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
             }, 1004, color);
         case "sp8":
             return new UIKeybindingSliderItem(() => Lang.menu[204].Value + " (" + PlayerInput.CurrentProfile.RightThumbstickDeadzoneY.ToString("P1") + ")", () => PlayerInput.CurrentProfile.RightThumbstickDeadzoneY, delegate(float f)
             {
                 PlayerInput.CurrentProfile.RightThumbstickDeadzoneY = f;
             }, delegate
             {
                 PlayerInput.CurrentProfile.RightThumbstickDeadzoneY = UILinksInitializer.HandleSliderHorizontalInput(PlayerInput.CurrentProfile.RightThumbstickDeadzoneY, 0f, 0.95f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
             }, 1005, color);
         case "sp9":
         {
             UIKeybindingSimpleListItem uIKeybindingSimpleListItem3 = new UIKeybindingSimpleListItem(() => Lang.menu[86].Value, color);
             uIKeybindingSimpleListItem3.OnLeftClick += delegate
             {
                 string copyableProfileName3 = GetCopyableProfileName();
                 PlayerInput.CurrentProfile.CopyGameplaySettingsFrom(PlayerInput.OriginalProfiles[copyableProfileName3], currentInputMode);
             };
             return uIKeybindingSimpleListItem3;
         }
         case "sp10":
         {
             UIKeybindingSimpleListItem uIKeybindingSimpleListItem5 = new UIKeybindingSimpleListItem(() => Lang.menu[86].Value, color);
             uIKeybindingSimpleListItem5.OnLeftClick += delegate
             {
                 string copyableProfileName = GetCopyableProfileName();
                 PlayerInput.CurrentProfile.CopyHotbarSettingsFrom(PlayerInput.OriginalProfiles[copyableProfileName], currentInputMode);
             };
             return uIKeybindingSimpleListItem5;
         }
         case "sp11":
         {
             UIKeybindingSimpleListItem uIKeybindingSimpleListItem2 = new UIKeybindingSimpleListItem(() => Lang.menu[86].Value, color);
             uIKeybindingSimpleListItem2.OnLeftClick += delegate
             {
                 string copyableProfileName4 = GetCopyableProfileName();
                 PlayerInput.CurrentProfile.CopyMapSettingsFrom(PlayerInput.OriginalProfiles[copyableProfileName4], currentInputMode);
             };
             return uIKeybindingSimpleListItem2;
         }
         case "sp12":
         {
             UIKeybindingSimpleListItem uIKeybindingSimpleListItem = new UIKeybindingSimpleListItem(() => Lang.menu[86].Value, color);
             uIKeybindingSimpleListItem.OnLeftClick += delegate
             {
                 string copyableProfileName5 = GetCopyableProfileName();
                 PlayerInput.CurrentProfile.CopyGamepadSettingsFrom(PlayerInput.OriginalProfiles[copyableProfileName5], currentInputMode);
             };
             return uIKeybindingSimpleListItem;
         }
         case "sp13":
         {
             UIKeybindingSimpleListItem uIKeybindingSimpleListItem4 = new UIKeybindingSimpleListItem(() => Lang.menu[86].Value, color);
             uIKeybindingSimpleListItem4.OnLeftClick += delegate
             {
                 string copyableProfileName2 = GetCopyableProfileName();
                 PlayerInput.CurrentProfile.CopyGamepadAdvancedSettingsFrom(PlayerInput.OriginalProfiles[copyableProfileName2], currentInputMode);
             };
             return uIKeybindingSimpleListItem4;
         }
         case "sp14":
         {
             UIKeybindingToggleListItem uIKeybindingToggleListItem = new UIKeybindingToggleListItem(() => Lang.menu[205].Value, () => PlayerInput.CurrentProfile.LeftThumbstickInvertX, color);
             uIKeybindingToggleListItem.OnLeftClick += delegate
             {
                 if (PlayerInput.CurrentProfile.AllowEditting)
                 {
                     PlayerInput.CurrentProfile.LeftThumbstickInvertX = !PlayerInput.CurrentProfile.LeftThumbstickInvertX;
                 }
             };
             return uIKeybindingToggleListItem;
         }
         case "sp15":
         {
             UIKeybindingToggleListItem uIKeybindingToggleListItem3 = new UIKeybindingToggleListItem(() => Lang.menu[206].Value, () => PlayerInput.CurrentProfile.LeftThumbstickInvertY, color);
             uIKeybindingToggleListItem3.OnLeftClick += delegate
             {
                 if (PlayerInput.CurrentProfile.AllowEditting)
                 {
                     PlayerInput.CurrentProfile.LeftThumbstickInvertY = !PlayerInput.CurrentProfile.LeftThumbstickInvertY;
                 }
             };
             return uIKeybindingToggleListItem3;
         }
         case "sp16":
         {
             UIKeybindingToggleListItem uIKeybindingToggleListItem2 = new UIKeybindingToggleListItem(() => Lang.menu[207].Value, () => PlayerInput.CurrentProfile.RightThumbstickInvertX, color);
             uIKeybindingToggleListItem2.OnLeftClick += delegate
             {
                 if (PlayerInput.CurrentProfile.AllowEditting)
                 {
                     PlayerInput.CurrentProfile.RightThumbstickInvertX = !PlayerInput.CurrentProfile.RightThumbstickInvertX;
                 }
             };
             return uIKeybindingToggleListItem2;
         }
         case "sp17":
         {
             UIKeybindingToggleListItem uIKeybindingToggleListItem6 = new UIKeybindingToggleListItem(() => Lang.menu[208].Value, () => PlayerInput.CurrentProfile.RightThumbstickInvertY, color);
             uIKeybindingToggleListItem6.OnLeftClick += delegate
             {
                 if (PlayerInput.CurrentProfile.AllowEditting)
                 {
                     PlayerInput.CurrentProfile.RightThumbstickInvertY = !PlayerInput.CurrentProfile.RightThumbstickInvertY;
                 }
             };
             return uIKeybindingToggleListItem6;
         }
         case "sp18":
             return new UIKeybindingSliderItem(delegate
             {
                 int hotbarRadialHoldTimeRequired = PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired;
                 return (hotbarRadialHoldTimeRequired == -1) ? Lang.menu[228].Value : (Lang.menu[227].Value + " (" + ((float)hotbarRadialHoldTimeRequired / 60f).ToString("F2") + "s)");
             }, () => (PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired == -1) ? 1f : ((float)PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired / 301f), delegate(float f)
             {
                 PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired = (int)(f * 301f);
                 if ((float)PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired == 301f)
                 {
                     PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired = -1;
                 }
             }, delegate
             {
                 float currentValue = ((PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired == -1) ? 1f : ((float)PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired / 301f));
                 currentValue = UILinksInitializer.HandleSliderHorizontalInput(currentValue, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX);
                 PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired = (int)(currentValue * 301f);
                 if ((float)PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired == 301f)
                 {
                     PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired = -1;
                 }
             }, 1007, color);
         case "sp19":
             return new UIKeybindingSliderItem(delegate
             {
                 int inventoryMoveCD = PlayerInput.CurrentProfile.InventoryMoveCD;
                 return Lang.menu[252].Value + " (" + ((float)inventoryMoveCD / 60f).ToString("F2") + "s)";
             }, () => Utils.GetLerpValue(4f, 12f, PlayerInput.CurrentProfile.InventoryMoveCD, clamped: true), delegate(float f)
             {
                 PlayerInput.CurrentProfile.InventoryMoveCD = (int)Math.Round(MathHelper.Lerp(4f, 12f, f));
             }, delegate
             {
                 if (UILinkPointNavigator.Shortcuts.INV_MOVE_OPTION_CD > 0)
                 {
                     UILinkPointNavigator.Shortcuts.INV_MOVE_OPTION_CD--;
                 }
                 if (UILinkPointNavigator.Shortcuts.INV_MOVE_OPTION_CD == 0)
                 {
                     float lerpValue = Utils.GetLerpValue(4f, 12f, PlayerInput.CurrentProfile.InventoryMoveCD, clamped: true);
                     float num = UILinksInitializer.HandleSliderHorizontalInput(lerpValue, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX);
                     if (lerpValue != num)
                     {
                         UILinkPointNavigator.Shortcuts.INV_MOVE_OPTION_CD = 8;
                         int num2 = Math.Sign(num - lerpValue);
                         PlayerInput.CurrentProfile.InventoryMoveCD = (int)MathHelper.Clamp(PlayerInput.CurrentProfile.InventoryMoveCD + num2, 4f, 12f);
                     }
                 }
             }, 1008, color);
         default:
             return new UIKeybindingListItem(bind, currentInputMode, color);
         }
     }
References PlayerInputProfile.AllowEditting, PlayerInputProfile.CopyGamepadAdvancedSettingsFrom(), PlayerInputProfile.CopyGamepadSettingsFrom(), PlayerInputProfile.CopyGameplaySettingsFrom(), PlayerInputProfile.CopyHotbarSettingsFrom(), PlayerInputProfile.CopyMapSettingsFrom(), PlayerInput.CurrentProfile, GetCopyableProfileName(), Utils.GetLerpValue(), UILinksInitializer.HandleSliderHorizontalInput(), PlayerInputProfile.HotbarRadialHoldTimeRequired, PlayerInputProfile.InputModes, PlayerInputProfile.InterfaceDeadzoneX, UILinkPointNavigator.Shortcuts.INV_MOVE_OPTION_CD, PlayerInputProfile.InventoryMoveCD, PlayerInputProfile.LeftThumbstickDeadzoneX, PlayerInputProfile.LeftThumbstickDeadzoneY, PlayerInputProfile.LeftThumbstickInvertX, PlayerInputProfile.LeftThumbstickInvertY, Lang.menu, UIElement.OnLeftClick, PlayerInput.OriginalProfiles, RadialButtonClick(), PlayerInputProfile.RightThumbstickDeadzoneX, PlayerInputProfile.RightThumbstickDeadzoneY, PlayerInputProfile.RightThumbstickInvertX, PlayerInputProfile.RightThumbstickInvertY, SnapButtonClick(), PlayerInputProfile.TriggersDeadzone, and LocalizedText.Value.
Referenced by CreateElementGroup().