Terraria: UIManageControls.SetupGamepadPoints
SetupGamepadPoints()
void UIManageControls.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
     {
         UILinkPointNavigator.Shortcuts.BackButtonCommand = 4;
         int num = 3000;
         UILinkPointNavigator.SetPosition(num, _buttonBack.GetInnerDimensions().ToRectangle().Center.ToVector2());
         UILinkPointNavigator.SetPosition(num + 1, _buttonKeyboard.GetInnerDimensions().ToRectangle().Center.ToVector2());
         UILinkPointNavigator.SetPosition(num + 2, _buttonGamepad.GetInnerDimensions().ToRectangle().Center.ToVector2());
         UILinkPointNavigator.SetPosition(num + 3, _buttonProfile.GetInnerDimensions().ToRectangle().Center.ToVector2());
         UILinkPointNavigator.SetPosition(num + 4, _buttonVs1.GetInnerDimensions().ToRectangle().Center.ToVector2());
         UILinkPointNavigator.SetPosition(num + 5, _buttonVs2.GetInnerDimensions().ToRectangle().Center.ToVector2());
         int key = num;
         UILinkPoint uILinkPoint = UILinkPointNavigator.Points[key];
         uILinkPoint.Unlink();
         uILinkPoint.Up = num + 6;
         key = num + 1;
         UILinkPoint uILinkPoint2 = UILinkPointNavigator.Points[key];
         uILinkPoint2.Unlink();
         uILinkPoint2.Right = num + 2;
         uILinkPoint2.Down = num + 6;
         key = num + 2;
         UILinkPoint uILinkPoint3 = UILinkPointNavigator.Points[key];
         uILinkPoint3.Unlink();
         uILinkPoint3.Left = num + 1;
         uILinkPoint3.Right = num + 4;
         uILinkPoint3.Down = num + 6;
         key = num + 4;
         UILinkPoint uILinkPoint4 = UILinkPointNavigator.Points[key];
         uILinkPoint4.Unlink();
         uILinkPoint4.Left = num + 2;
         uILinkPoint4.Right = num + 5;
         uILinkPoint4.Down = num + 6;
         key = num + 5;
         UILinkPoint uILinkPoint5 = UILinkPointNavigator.Points[key];
         uILinkPoint5.Unlink();
         uILinkPoint5.Left = num + 4;
         uILinkPoint5.Right = num + 3;
         uILinkPoint5.Down = num + 6;
         key = num + 3;
         UILinkPoint uILinkPoint6 = UILinkPointNavigator.Points[key];
         uILinkPoint6.Unlink();
         uILinkPoint6.Left = num + 5;
         uILinkPoint6.Down = num + 6;
         float num2 = 1f / Main.UIScale;
         Rectangle clippingRectangle = _uilist.GetClippingRectangle(spriteBatch);
         Vector2 minimum = clippingRectangle.TopLeft() * num2;
         Vector2 maximum = clippingRectangle.BottomRight() * num2;
         List<SnapPoint> snapPoints = _uilist.GetSnapPoints();
         for (int i = 0; i < snapPoints.Count; i++)
         {
             if (!snapPoints[i].Position.Between(minimum, maximum))
             {
                 _ = snapPoints[i].Position;
                 snapPoints.Remove(snapPoints[i]);
                 i--;
             }
         }
         snapPoints.Sort((SnapPoint x, SnapPoint y) => x.Id.CompareTo(y.Id));
         for (int j = 0; j < snapPoints.Count; j++)
         {
             key = num + 6 + j;
             if (snapPoints[j].Name == "Thin")
             {
                 UILinkPoint uILinkPoint7 = UILinkPointNavigator.Points[key];
                 uILinkPoint7.Unlink();
                 UILinkPointNavigator.SetPosition(key, snapPoints[j].Position);
                 uILinkPoint7.Right = key + 1;
                 uILinkPoint7.Down = ((j < snapPoints.Count - 2) ? (key + 2) : num);
                 uILinkPoint7.Up = ((j < 2) ? (num + 1) : ((snapPoints[j - 1].Name == "Wide") ? (key - 1) : (key - 2)));
                 UILinkPointNavigator.Points[num].Up = key;
                 UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = key;
                 j++;
                 if (j < snapPoints.Count)
                 {
                     key = num + 6 + j;
                     UILinkPoint uILinkPoint8 = UILinkPointNavigator.Points[key];
                     uILinkPoint8.Unlink();
                     UILinkPointNavigator.SetPosition(key, snapPoints[j].Position);
                     uILinkPoint8.Left = key - 1;
                     uILinkPoint8.Down = ((j >= snapPoints.Count - 1) ? num : ((snapPoints[j + 1].Name == "Wide") ? (key + 1) : (key + 2)));
                     uILinkPoint8.Up = ((j < 2) ? (num + 1) : (key - 2));
                     UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = key;
                 }
             }
             else
             {
                 UILinkPoint uILinkPoint9 = UILinkPointNavigator.Points[key];
                 uILinkPoint9.Unlink();
                 UILinkPointNavigator.SetPosition(key, snapPoints[j].Position);
                 uILinkPoint9.Down = ((j < snapPoints.Count - 1) ? (key + 1) : num);
                 uILinkPoint9.Up = ((j < 1) ? (num + 1) : ((snapPoints[j - 1].Name == "Wide") ? (key - 1) : (key - 2)));
                 UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = key;
                 UILinkPointNavigator.Points[num].Up = key;
             }
         }
         if (ForceMoveTo != -1)
         {
             UILinkPointNavigator.ChangePoint((int)MathHelper.Clamp(ForceMoveTo, num, UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX));
             ForceMoveTo = -1;
         }
     }
References _buttonBack, _buttonGamepad, _buttonKeyboard, _buttonProfile, _buttonVs1, _buttonVs2, _uilist, UILinkPointNavigator.Shortcuts.BackButtonCommand, UILinkPointNavigator.ChangePoint(), UILinkPoint.Down, UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX, ForceMoveTo, UIElement.GetClippingRectangle(), UIElement.GetInnerDimensions(), UIList.GetSnapPoints(), SnapPoint.Id, UILinkPoint.Left, UILinkPointNavigator.Points, UILinkPoint.Right, UILinkPointNavigator.SetPosition(), CalculatedStyle.ToRectangle(), Main.UIScale, UILinkPoint.Unlink(), and UILinkPoint.Up.
Referenced by Draw().