Terraria: UIManageControls.VsMenuButtonClick
VsMenuButtonClick()
void UIManageControls.VsMenuButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         _buttonVs1.SetFrame(_GameplayVsUITexture.Frame(2, 2, 0, 1));
         _buttonVs2.SetFrame(_GameplayVsUITexture.Frame(2, 2, 1));
         OnGameplay = false;
         FillList();
     }
References _buttonVs1, _buttonVs2, _GameplayVsUITexture, FillList(), OnGameplay, and UIImageFramed.SetFrame().
Referenced by OnInitialize().