Terraria: UIManageControls.FillList
FillList()
void UIManageControls.FillList () inline private
     {
         List<UIElement> list = _bindsKeyboard;
         if (!OnKeyboard)
         {
             list = _bindsGamepad;
         }
         if (!OnGameplay)
         {
             list = (OnKeyboard ? _bindsKeyboardUI : _bindsGamepadUI);
         }
         _uilist.Clear();
         foreach (UIElement item in list)
         {
             _uilist.Add(item);
         }
     }
References _bindsGamepad, _bindsGamepadUI, _bindsKeyboard, _bindsKeyboardUI, _uilist, UIList.Add(), UIList.Clear(), OnGameplay, and OnKeyboard.
Referenced by GamepadButtonClick(), KeyboardButtonClick(), OnInitialize(), VsGameplayButtonClick(), and VsMenuButtonClick().