Terraria: UIManageControls.OnInitialize
OnInitialize()
override void UIManageControls.OnInitialize () inline virtual
Reimplemented from UIElement.
     {
         _KeyboardGamepadTexture = Main.Assets.Request<Texture2D>("Images/UI/Settings_Inputs", (AssetRequestMode)1);
         _keyboardGamepadBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/Settings_Inputs_Border", (AssetRequestMode)1);
         _GameplayVsUITexture = Main.Assets.Request<Texture2D>("Images/UI/Settings_Inputs_2", (AssetRequestMode)1);
         _GameplayVsUIBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/Settings_Inputs_2_Border", (AssetRequestMode)1);
         UIElement uIElement = new UIElement();
         uIElement.Width.Set(0f, 0.8f);
         uIElement.MaxWidth.Set(600f, 0f);
         uIElement.Top.Set(220f, 0f);
         uIElement.Height.Set(-200f, 1f);
         uIElement.HAlign = 0.5f;
         _outerContainer = uIElement;
         UIPanel uIPanel = new UIPanel();
         uIPanel.Width.Set(0f, 1f);
         uIPanel.Height.Set(-110f, 1f);
         uIPanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
         uIElement.Append(uIPanel);
         _buttonKeyboard = new UIImageFramed(_KeyboardGamepadTexture, _KeyboardGamepadTexture.Frame(2, 2));
         _buttonKeyboard.VAlign = 0f;
         _buttonKeyboard.HAlign = 0f;
         _buttonKeyboard.Left.Set(0f, 0f);
         _buttonKeyboard.Top.Set(8f, 0f);
         _buttonKeyboard.OnLeftClick += KeyboardButtonClick;
         _buttonKeyboard.OnMouseOver += ManageBorderKeyboardOn;
         _buttonKeyboard.OnMouseOut += ManageBorderKeyboardOff;
         uIPanel.Append(_buttonKeyboard);
         _buttonGamepad = new UIImageFramed(_KeyboardGamepadTexture, _KeyboardGamepadTexture.Frame(2, 2, 1, 1));
         _buttonGamepad.VAlign = 0f;
         _buttonGamepad.HAlign = 0f;
         _buttonGamepad.Left.Set(76f, 0f);
         _buttonGamepad.Top.Set(8f, 0f);
         _buttonGamepad.OnLeftClick += GamepadButtonClick;
         _buttonGamepad.OnMouseOver += ManageBorderGamepadOn;
         _buttonGamepad.OnMouseOut += ManageBorderGamepadOff;
         uIPanel.Append(_buttonGamepad);
         _buttonBorder1 = new UIImageFramed(_keyboardGamepadBorderTexture, _keyboardGamepadBorderTexture.Frame());
         _buttonBorder1.VAlign = 0f;
         _buttonBorder1.HAlign = 0f;
         _buttonBorder1.Left.Set(0f, 0f);
         _buttonBorder1.Top.Set(8f, 0f);
         _buttonBorder1.Color = Color.Silver;
         _buttonBorder1.IgnoresMouseInteraction = true;
         uIPanel.Append(_buttonBorder1);
         _buttonBorder2 = new UIImageFramed(_keyboardGamepadBorderTexture, _keyboardGamepadBorderTexture.Frame());
         _buttonBorder2.VAlign = 0f;
         _buttonBorder2.HAlign = 0f;
         _buttonBorder2.Left.Set(76f, 0f);
         _buttonBorder2.Top.Set(8f, 0f);
         _buttonBorder2.Color = Color.Transparent;
         _buttonBorder2.IgnoresMouseInteraction = true;
         uIPanel.Append(_buttonBorder2);
         _buttonVs1 = new UIImageFramed(_GameplayVsUITexture, _GameplayVsUITexture.Frame(2, 2));
         _buttonVs1.VAlign = 0f;
         _buttonVs1.HAlign = 0f;
         _buttonVs1.Left.Set(172f, 0f);
         _buttonVs1.Top.Set(8f, 0f);
         _buttonVs1.OnLeftClick += VsGameplayButtonClick;
         _buttonVs1.OnMouseOver += ManageBorderGameplayOn;
         _buttonVs1.OnMouseOut += ManageBorderGameplayOff;
         uIPanel.Append(_buttonVs1);
         _buttonVs2 = new UIImageFramed(_GameplayVsUITexture, _GameplayVsUITexture.Frame(2, 2, 1, 1));
         _buttonVs2.VAlign = 0f;
         _buttonVs2.HAlign = 0f;
         _buttonVs2.Left.Set(212f, 0f);
         _buttonVs2.Top.Set(8f, 0f);
         _buttonVs2.OnLeftClick += VsMenuButtonClick;
         _buttonVs2.OnMouseOver += ManageBorderMenuOn;
         _buttonVs2.OnMouseOut += ManageBorderMenuOff;
         uIPanel.Append(_buttonVs2);
         _buttonBorderVs1 = new UIImageFramed(_GameplayVsUIBorderTexture, _GameplayVsUIBorderTexture.Frame());
         _buttonBorderVs1.VAlign = 0f;
         _buttonBorderVs1.HAlign = 0f;
         _buttonBorderVs1.Left.Set(172f, 0f);
         _buttonBorderVs1.Top.Set(8f, 0f);
         _buttonBorderVs1.Color = Color.Silver;
         _buttonBorderVs1.IgnoresMouseInteraction = true;
         uIPanel.Append(_buttonBorderVs1);
         _buttonBorderVs2 = new UIImageFramed(_GameplayVsUIBorderTexture, _GameplayVsUIBorderTexture.Frame());
         _buttonBorderVs2.VAlign = 0f;
         _buttonBorderVs2.HAlign = 0f;
         _buttonBorderVs2.Left.Set(212f, 0f);
         _buttonBorderVs2.Top.Set(8f, 0f);
         _buttonBorderVs2.Color = Color.Transparent;
         _buttonBorderVs2.IgnoresMouseInteraction = true;
         uIPanel.Append(_buttonBorderVs2);
         _buttonProfile = new UIKeybindingSimpleListItem(() => PlayerInput.CurrentProfile.ShowName, new Color(73, 94, 171, 255) * 0.9f);
         _buttonProfile.VAlign = 0f;
         _buttonProfile.HAlign = 1f;
         _buttonProfile.Width.Set(180f, 0f);
         _buttonProfile.Height.Set(30f, 0f);
         _buttonProfile.MarginRight = 30f;
         _buttonProfile.Left.Set(0f, 0f);
         _buttonProfile.Top.Set(8f, 0f);
         _buttonProfile.OnLeftClick += profileButtonClick;
         uIPanel.Append(_buttonProfile);
         _uilist = new UIList();
         _uilist.Width.Set(-25f, 1f);
         _uilist.Height.Set(-50f, 1f);
         _uilist.VAlign = 1f;
         _uilist.PaddingBottom = 5f;
         _uilist.ListPadding = 20f;
         uIPanel.Append(_uilist);
         AssembleBindPanels();
         FillList();
         UIScrollbar uIScrollbar = new UIScrollbar();
         uIScrollbar.SetView(100f, 1000f);
         uIScrollbar.Height.Set(-67f, 1f);
         uIScrollbar.HAlign = 1f;
         uIScrollbar.VAlign = 1f;
         uIScrollbar.MarginBottom = 11f;
         uIPanel.Append(uIScrollbar);
         _uilist.SetScrollbar(uIScrollbar);
         UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Keybindings"), 0.7f, large: true);
         uITextPanel.HAlign = 0.5f;
         uITextPanel.Top.Set(-45f, 0f);
         uITextPanel.Left.Set(-10f, 0f);
         uITextPanel.SetPadding(15f);
         uITextPanel.BackgroundColor = new Color(73, 94, 171);
         uIElement.Append(uITextPanel);
         UITextPanel<LocalizedText> uITextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true);
         uITextPanel2.Width.Set(-10f, 0.5f);
         uITextPanel2.Height.Set(50f, 0f);
         uITextPanel2.VAlign = 1f;
         uITextPanel2.HAlign = 0.5f;
         uITextPanel2.Top.Set(-45f, 0f);
         uITextPanel2.OnMouseOver += FadedMouseOver;
         uITextPanel2.OnMouseOut += FadedMouseOut;
         uITextPanel2.OnLeftClick += GoBackClick;
         uIElement.Append(uITextPanel2);
         _buttonBack = uITextPanel2;
         Append(uIElement);
     }
References UIElement.UIElement(), _buttonBack, _buttonBorder1, _buttonBorder2, _buttonBorderVs1, _buttonBorderVs2, _buttonGamepad, _buttonKeyboard, _buttonProfile, _buttonVs1, _buttonVs2, _GameplayVsUIBorderTexture, _GameplayVsUITexture, _keyboardGamepadBorderTexture, _KeyboardGamepadTexture, _outerContainer, _uilist, UIElement.Append(), AssembleBindPanels(), Main.Assets, UIPanel.BackgroundColor, UIImageFramed.Color, Color, PlayerInput.CurrentProfile, FadedMouseOut(), FadedMouseOver(), FillList(), GamepadButtonClick(), Language.GetText(), GoBackClick(), UIElement.HAlign, UIElement.Height, UIElement.IgnoresMouseInteraction, KeyboardButtonClick(), UIElement.Left, UIList.ListPadding, ManageBorderGamepadOff(), ManageBorderGamepadOn(), ManageBorderGameplayOff(), ManageBorderGameplayOn(), ManageBorderKeyboardOff(), ManageBorderKeyboardOn(), ManageBorderMenuOff(), ManageBorderMenuOn(), UIElement.MarginBottom, UIElement.MarginRight, UIElement.MaxWidth, UIElement.OnLeftClick, UIElement.OnMouseOut, UIElement.OnMouseOver, UIElement.PaddingBottom, profileButtonClick(), StyleDimension.Set(), UIList.SetScrollbar(), UIScrollbar.SetView(), PlayerInputProfile.ShowName, UIElement.Top, UIElement.VAlign, VsGameplayButtonClick(), VsMenuButtonClick(), and UIElement.Width.