Terraria: System.ComponentModel.DefaultValueAttribute.DefaultValueAttribute
DefaultValueAttribute() [1/15]
System.ComponentModel.DefaultValueAttribute.DefaultValueAttribute ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type, string? value) inline
Definition at line 18 of file DefaultValueAttribute.cs.
    {
        if (type == null)
        {
            return;
        }
        try
        {
            if (TryConvertFromInvariantString(type, value, out var conversionResult2))
            {
                _value = conversionResult2;
            }
            else if (type.IsSubclassOf(typeof(Enum)) && value != null)
            {
                _value = Enum.Parse(type, value, ignoreCase: true);
            }
            else if (type == typeof(TimeSpan) && value != null)
            {
                _value = TimeSpan.Parse(value);
            }
            else
            {
                _value = Convert.ChangeType(value, type, CultureInfo.InvariantCulture);
            }
            [RequiresUnreferencedCode("Generic TypeConverters may require the generic types to be annotated. For example, NullableConverter requires the underlying type to be DynamicallyAccessedMembers All.")]
            static bool TryConvertFromInvariantString([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type typeToConvert, string stringValue, out object conversionResult)
            {
                conversionResult = null;
                if (s_convertFromInvariantString == null)
                {
                    MethodInfo methodInfo = Type.GetType("System.ComponentModel.TypeDescriptor, System.ComponentModel.TypeConverter", throwOnError: false)?.GetMethod("ConvertFromInvariantString", BindingFlags.Static | BindingFlags.NonPublic);
                    Volatile.Write(ref s_convertFromInvariantString, (methodInfo == null) ? new object() : methodInfo.CreateDelegate(typeof(Func<Type, string, object>)));
                }
                if (!(s_convertFromInvariantString is Func<Type, string, object> func))
                {
                    return false;
                }
                try
                {
                    conversionResult = func(typeToConvert, stringValue);
                }
                catch
                {
                    return false;
                }
                return true;
            }
        }
        catch
        {
        }
    }
References System.ComponentModel.DefaultValueAttribute._value, System.Convert.ChangeType(), System.Reflection.MethodInfo.CreateDelegate(), System.Type.GetType(), System.Globalization.CultureInfo.InvariantCulture, System.TimeSpan.Parse(), System.Enum.Parse(), System.ComponentModel.DefaultValueAttribute.s_convertFromInvariantString, System.type, System.value, and System.Threading.Volatile.Write().