Terraria: System.Data.Merger.MergeConstraints
MergeConstraints() [2/2]
void System.Data.Merger.MergeConstraints (DataTable table) inline private
Definition at line 390 of file Merger.cs.
    {
        for (int i = 0; i < table.Constraints.Count; i++)
        {
            Constraint constraint = table.Constraints[i];
            Constraint constraint2 = constraint.Clone(_dataSet, _IgnoreNSforTableLookup);
            if (constraint2 == null)
            {
                _dataSet.RaiseMergeFailed(table, System.SR.Format(System.SR.DataMerge_MissingConstraint, constraint.GetType().FullName, constraint.ConstraintName), _missingSchemaAction);
                continue;
            }
            Constraint constraint3 = constraint2.Table.Constraints.FindConstraint(constraint2);
            if (constraint3 == null)
            {
                if (MissingSchemaAction.Add == _missingSchemaAction)
                {
                    try
                    {
                        constraint2.Table.Constraints.Add(constraint2);
                    }
                    catch (DuplicateNameException)
                    {
                        constraint2.ConstraintName = string.Empty;
                        constraint2.Table.Constraints.Add(constraint2);
                    }
                }
                else if (MissingSchemaAction.Error == _missingSchemaAction)
                {
                    _dataSet.RaiseMergeFailed(table, System.SR.Format(System.SR.DataMerge_MissingConstraint, constraint.GetType().FullName, constraint.ConstraintName), _missingSchemaAction);
                }
            }
            else
            {
                MergeExtendedProperties(constraint.ExtendedProperties, constraint3.ExtendedProperties);
            }
        }
    }
References System.Data.Merger._dataSet, System.Data.Merger._IgnoreNSforTableLookup, System.Data.Merger._missingSchemaAction, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.Constraint.Clone(), System.Data.Constraint.ConstraintName, System.Data.DataTable.Constraints, System.Data.InternalDataCollectionBase.Count, System.SR.DataMerge_MissingConstraint, System.Data.Constraint.ExtendedProperties, System.SR.Format(), System.Data.Merger.MergeExtendedProperties(), and System.Data.DataSet.RaiseMergeFailed().