Terraria: System.Data.Merger.MergeRows
MergeRows()
void System.Data.Merger.MergeRows (DataRow[] rows) inline package
Definition at line 193 of file Merger.cs.
    {
        DataTable dataTable = null;
        DataTable dataTable2 = null;
        DataKey key = default(DataKey);
        Index index = null;
        bool enforceConstraints = _dataSet.EnforceConstraints;
        _dataSet.EnforceConstraints = false;
        for (int i = 0; i < rows.Length; i++)
        {
            DataRow dataRow = rows[i];
            if (dataRow == null)
            {
                throw ExceptionBuilder.ArgumentNull($"{"rows"}[{i}]");
            }
            if (dataRow.Table == null)
            {
                throw ExceptionBuilder.ArgumentNull($"{"rows"}[{i}].{"Table"}");
            }
            if (dataRow.Table.DataSet == _dataSet)
            {
                continue;
            }
            if (dataTable != dataRow.Table)
            {
                dataTable = dataRow.Table;
                dataTable2 = MergeSchema(dataRow.Table);
                if (dataTable2 == null)
                {
                    _dataSet.EnforceConstraints = enforceConstraints;
                    return;
                }
                if (dataTable2._primaryKey != null)
                {
                    key = GetSrcKey(dataTable, dataTable2);
                }
                if (key.HasValue)
                {
                    if (index != null)
                    {
                        index.RemoveRef();
                        index = null;
                    }
                    index = new Index(dataTable2, dataTable2._primaryKey.Key.GetIndexDesc(), DataViewRowState.OriginalRows | DataViewRowState.Added, null);
                    index.AddRef();
                    index.AddRef();
                }
            }
            if (dataRow._newRecord != -1 || dataRow._oldRecord != -1)
            {
                DataRow targetRow = null;
                if (0 < dataTable2.Rows.Count && index != null)
                {
                    targetRow = dataTable2.FindMergeTarget(dataRow, key, index);
                }
                targetRow = dataTable2.MergeRow(dataRow, targetRow, _preserveChanges, index);
                if (targetRow.Table._dependentColumns != null && targetRow.Table._dependentColumns.Count > 0)
                {
                    targetRow.Table.EvaluateExpressions(targetRow, DataRowAction.Change, null);
                }
            }
        }
        if (index != null)
        {
            index.RemoveRef();
            index = null;
        }
        _dataSet.EnforceConstraints = enforceConstraints;
    }
References System.Data.Merger._dataSet, System.Data.Merger._preserveChanges, System.Data.ExceptionBuilder.ArgumentNull(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.DataSet.EnforceConstraints, System.Data.Merger.GetSrcKey(), System.index, System.key, and System.Data.Merger.MergeSchema().