Terraria: System.Text.BinHexEncoding.GetChars
GetChars() [4/6]
override int System.Text.BinHexEncoding.GetChars (byte[] bytes, int byteIndex, int byteCount, char[] chars, int charIndex) inline
Definition at line 84 of file BinHexEncoding.cs.
    {
        if (bytes == null)
        {
            throw new ArgumentNullException("bytes");
        }
        if (byteIndex < 0)
        {
            throw new ArgumentOutOfRangeException("byteIndex", System.SR.ValueMustBeNonNegative);
        }
        if (byteIndex > bytes.Length)
        {
            throw new ArgumentOutOfRangeException("byteIndex", System.SR.Format(System.SR.OffsetExceedsBufferSize, bytes.Length));
        }
        if (byteCount < 0)
        {
            throw new ArgumentOutOfRangeException("byteCount", System.SR.ValueMustBeNonNegative);
        }
        if (byteCount > bytes.Length - byteIndex)
        {
            throw new ArgumentOutOfRangeException("byteCount", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, bytes.Length - byteIndex));
        }
        int charCount = GetCharCount(bytes, byteIndex, byteCount);
        if (chars == null)
        {
            throw new ArgumentNullException("chars");
        }
        if (charIndex < 0)
        {
            throw new ArgumentOutOfRangeException("charIndex", System.SR.ValueMustBeNonNegative);
        }
        if (charIndex > chars.Length)
        {
            throw new ArgumentOutOfRangeException("charIndex", System.SR.Format(System.SR.OffsetExceedsBufferSize, chars.Length));
        }
        if (charCount < 0 || charCount > chars.Length - charIndex)
        {
            throw new ArgumentException(System.SR.XmlArrayTooSmall, "chars");
        }
        if (byteCount > 0)
        {
            System.HexConverter.EncodeToUtf16(bytes.AsSpan(byteIndex, byteCount), chars.AsSpan(charIndex));
        }
        return charCount;
    }
References System.byteCount, System.byteIndex, System.bytes, System.charCount, System.charIndex, System.chars, System.HexConverter.EncodeToUtf16(), System.SR.Format(), System.Text.BinHexEncoding.GetCharCount(), System.SR.OffsetExceedsBufferSize, System.SR.SizeExceedsRemainingBufferSpace, System.SR.ValueMustBeNonNegative, and System.SR.XmlArrayTooSmall.