Terraria: System.Data.Merger.MergeRelation
MergeRelation()
void System.Data.Merger.MergeRelation (DataRelation relation) inline private
Definition at line 428 of file Merger.cs.
    {
        DataRelation dataRelation = null;
        int num = _dataSet.Relations.InternalIndexOf(relation.RelationName);
        if (num >= 0)
        {
            dataRelation = _dataSet.Relations[num];
            if (relation.ParentKey.ColumnsReference.Length != dataRelation.ParentKey.ColumnsReference.Length)
            {
                _dataSet.RaiseMergeFailed(null, System.SR.Format(System.SR.DataMerge_MissingDefinition, relation.RelationName), _missingSchemaAction);
            }
            for (int i = 0; i < relation.ParentKey.ColumnsReference.Length; i++)
            {
                DataColumn dataColumn = dataRelation.ParentKey.ColumnsReference[i];
                DataColumn dataColumn2 = relation.ParentKey.ColumnsReference[i];
                if (string.Compare(dataColumn.ColumnName, dataColumn2.ColumnName, ignoreCase: false, dataColumn.Table.Locale) != 0)
                {
                    _dataSet.RaiseMergeFailed(null, System.SR.Format(System.SR.DataMerge_ReltionKeyColumnsMismatch, relation.RelationName), _missingSchemaAction);
                }
                dataColumn = dataRelation.ChildKey.ColumnsReference[i];
                dataColumn2 = relation.ChildKey.ColumnsReference[i];
                if (string.Compare(dataColumn.ColumnName, dataColumn2.ColumnName, ignoreCase: false, dataColumn.Table.Locale) != 0)
                {
                    _dataSet.RaiseMergeFailed(null, System.SR.Format(System.SR.DataMerge_ReltionKeyColumnsMismatch, relation.RelationName), _missingSchemaAction);
                }
            }
        }
        else
        {
            if (MissingSchemaAction.Add != _missingSchemaAction)
            {
                throw ExceptionBuilder.MergeMissingDefinition(relation.RelationName);
            }
            DataTable dataTable = (_IgnoreNSforTableLookup ? _dataSet.Tables[relation.ParentTable.TableName] : _dataSet.Tables[relation.ParentTable.TableName, relation.ParentTable.Namespace]);
            DataTable dataTable2 = (_IgnoreNSforTableLookup ? _dataSet.Tables[relation.ChildTable.TableName] : _dataSet.Tables[relation.ChildTable.TableName, relation.ChildTable.Namespace]);
            DataColumn[] array = new DataColumn[relation.ParentKey.ColumnsReference.Length];
            DataColumn[] array2 = new DataColumn[relation.ParentKey.ColumnsReference.Length];
            for (int j = 0; j < relation.ParentKey.ColumnsReference.Length; j++)
            {
                array[j] = dataTable.Columns[relation.ParentKey.ColumnsReference[j].ColumnName];
                array2[j] = dataTable2.Columns[relation.ChildKey.ColumnsReference[j].ColumnName];
            }
            try
            {
                dataRelation = new DataRelation(relation.RelationName, array, array2, relation._createConstraints);
                dataRelation.Nested = relation.Nested;
                _dataSet.Relations.Add(dataRelation);
            }
            catch (Exception ex) when (ADP.IsCatchableExceptionType(ex))
            {
                ExceptionBuilder.TraceExceptionForCapture(ex);
                _dataSet.RaiseMergeFailed(null, ex.Message, _missingSchemaAction);
            }
        }
        MergeExtendedProperties(relation.ExtendedProperties, dataRelation.ExtendedProperties);
    }
References System.Data.Merger._dataSet, System.Data.Merger._IgnoreNSforTableLookup, System.Data.Merger._missingSchemaAction, System.Data.DataRelationCollection.Add(), System.array, System.SR.DataMerge_MissingDefinition, System.SR.DataMerge_ReltionKeyColumnsMismatch, System.SR.Format(), System.Data.DataRelationCollection.InternalIndexOf(), System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.Merger.MergeExtendedProperties(), System.Data.ExceptionBuilder.MergeMissingDefinition(), System.Data.DataSet.RaiseMergeFailed(), System.Data.DataSet.Relations, System.Data.DataSet.Tables, and System.Data.ExceptionBuilder.TraceExceptionForCapture().
Referenced by System.Data.Merger.MergeDataSet().