Terraria: System.Data.Merger.MergeTable
MergeTable() [1/2]
void System.Data.Merger.MergeTable (DataTable src) inline package
Definition at line 95 of file Merger.cs.
    {
        bool enforceConstraints = false;
        if (!_isStandAlonetable)
        {
            if (src.DataSet == _dataSet)
            {
                return;
            }
            enforceConstraints = _dataSet.EnforceConstraints;
            _dataSet.EnforceConstraints = false;
        }
        else
        {
            if (src == _dataTable)
            {
                return;
            }
            _dataTable.SuspendEnforceConstraints = true;
        }
        if (_dataSet != null)
        {
            if (src.DataSet == null || src.DataSet._namespaceURI != _dataSet._namespaceURI)
            {
                _IgnoreNSforTableLookup = true;
            }
        }
        else if (_dataTable.DataSet == null || src.DataSet == null || src.DataSet._namespaceURI != _dataTable.DataSet._namespaceURI)
        {
            _IgnoreNSforTableLookup = true;
        }
        MergeTableData(src);
        DataTable dataTable = _dataTable;
        if (dataTable == null && _dataSet != null)
        {
            dataTable = (_IgnoreNSforTableLookup ? _dataSet.Tables[src.TableName] : _dataSet.Tables[src.TableName, src.Namespace]);
        }
        dataTable?.EvaluateExpressions();
        if (!_isStandAlonetable)
        {
            _dataSet.EnforceConstraints = enforceConstraints;
            return;
        }
        _dataTable.SuspendEnforceConstraints = false;
        try
        {
            if (_dataTable.EnforceConstraints)
            {
                _dataTable.EnableConstraints();
            }
        }
        catch (ConstraintException)
        {
            if (_dataTable.DataSet != null)
            {
                _dataTable.DataSet.EnforceConstraints = false;
            }
            throw;
        }
    }
References System.Data.Merger._dataSet, System.Data.Merger._dataTable, System.Data.Merger._IgnoreNSforTableLookup, System.Data.Merger._isStandAlonetable, System.Data.DataSet._namespaceURI, System.Data.DataTable.DataSet, System.Data.DataTable.EnableConstraints(), System.Data.DataSet.EnforceConstraints, System.Data.DataTable.EnforceConstraints, System.Data.Merger.MergeTableData(), and System.Data.DataSet.Tables.
Referenced by System.Data.Merger.MergeTableData().