Terraria: AnOutlinedDrawRenderTargetContent.HandleUseReqest
HandleUseReqest()
override void AnOutlinedDrawRenderTargetContent.HandleUseReqest (GraphicsDevice device, SpriteBatch spriteBatch) inline protected virtual inherited
Implements ARenderTargetContentByRequest.
     {
         Effect pixelShader = Main.pixelShader;
         if (_coloringShader == null)
         {
             _coloringShader = pixelShader.CurrentTechnique.Passes["ColorOnly"];
         }
         new Rectangle(0, 0, width, height);
         PrepareARenderTarget_AndListenToEvents(ref _target, device, width, height, RenderTargetUsage.PreserveContents);
         PrepareARenderTarget_WithoutListeningToEvents(ref _helperTarget, device, width, height, RenderTargetUsage.DiscardContents);
         device.SetRenderTarget(_helperTarget);
         device.Clear(Color.Transparent);
         spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null);
         DrawTheContent(spriteBatch);
         spriteBatch.End();
         device.SetRenderTarget(_target);
         device.Clear(Color.Transparent);
         spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null);
         _coloringShader.Apply();
         int num = 2;
         int num2 = num * 2;
         for (int i = -num2; i <= num2; i += num)
         {
             for (int j = -num2; j <= num2; j += num)
             {
                 if (Math.Abs(i) + Math.Abs(j) == num2)
                 {
                     spriteBatch.Draw(_helperTarget, new Vector2(i, j), Color.Black);
                 }
             }
         }
         num2 = num;
         for (int k = -num2; k <= num2; k += num)
         {
             for (int l = -num2; l <= num2; l += num)
             {
                 if (Math.Abs(k) + Math.Abs(l) == num2)
                 {
                     spriteBatch.Draw(_helperTarget, new Vector2(k, l), _borderColor);
                 }
             }
         }
         pixelShader.CurrentTechnique.Passes[0].Apply();
         spriteBatch.Draw(_helperTarget, Vector2.Zero, Color.White);
         spriteBatch.End();
         device.SetRenderTarget(null);
         _wasPrepared = true;
     }
References AnOutlinedDrawRenderTargetContent._borderColor, AnOutlinedDrawRenderTargetContent._coloringShader, AnOutlinedDrawRenderTargetContent._helperTarget, ARenderTargetContentByRequest._target, ARenderTargetContentByRequest._wasPrepared, Color, AnOutlinedDrawRenderTargetContent.DrawTheContent(), AnOutlinedDrawRenderTargetContent.height, Main.pixelShader, ARenderTargetContentByRequest.PrepareARenderTarget_AndListenToEvents(), ARenderTargetContentByRequest.PrepareARenderTarget_WithoutListeningToEvents(), and AnOutlinedDrawRenderTargetContent.width.