Terraria: System.Data.Merger.MergeExtendedProperties
MergeExtendedProperties()
void System.Data.Merger.MergeExtendedProperties (PropertyCollection src, PropertyCollection dst) inline private
Definition at line 485 of file Merger.cs.
    {
        if (MissingSchemaAction.Ignore == _missingSchemaAction)
        {
            return;
        }
        IDictionaryEnumerator enumerator = src.GetEnumerator();
        while (enumerator.MoveNext())
        {
            if (!_preserveChanges || dst[enumerator.Key] == null)
            {
                dst[enumerator.Key] = enumerator.Value;
            }
        }
    }
References System.Data.Merger._missingSchemaAction, System.Data.Merger._preserveChanges, and System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator().
Referenced by System.Data.Merger.MergeConstraints(), System.Data.Merger.MergeDataSet(), System.Data.Merger.MergeRelation(), System.Data.Merger.MergeSchema(), and System.Data.Merger.MergeTable().