Terraria: System.Xml.Xsl.Qil.QilReplaceVisitor.VisitChildren
VisitChildren()
override QilNode System.Xml.Xsl.Qil.QilReplaceVisitor.VisitChildren (QilNode parent) inline protected virtual inherited
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 12 of file QilReplaceVisitor.cs.
    {
        XmlQueryType xmlType = parent.XmlType;
        bool flag = false;
        for (int i = 0; i < parent.Count; i++)
        {
            QilNode qilNode = parent[i];
            XmlQueryType xmlQueryType = qilNode?.XmlType;
            QilNode qilNode2 = ((!IsReference(parent, i)) ? Visit(qilNode) : VisitReference(qilNode));
            if (qilNode != qilNode2 || (qilNode2 != null && (object)xmlQueryType != qilNode2.XmlType))
            {
                flag = true;
                parent[i] = qilNode2;
            }
        }
        if (flag)
        {
            RecalculateType(parent, xmlType);
        }
        return parent;
    }
References System.Xml.Xsl.Qil.QilNode.Count, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilVisitor.IsReference(), System.Xml.Xsl.Qil.QilReplaceVisitor.RecalculateType(), System.Xml.Xsl.Qil.QilVisitor.Visit(), System.Xml.Xsl.Qil.QilVisitor.VisitReference(), and System.Xml.Xsl.Qil.QilNode.XmlType.
Referenced by System.Xml.Xsl.Qil.QilPatternVisitor.Visit().