Terraria: System.Data.Merger.MergeSchema
MergeSchema()
DataTable System.Data.Merger.MergeSchema (DataTable table) inline private
Definition at line 263 of file Merger.cs.
    {
        DataTable dataTable = null;
        if (!_isStandAlonetable)
        {
            if (_dataSet.Tables.Contains(table.TableName, caseSensitive: true))
            {
                dataTable = ((!_IgnoreNSforTableLookup) ? _dataSet.Tables[table.TableName, table.Namespace] : _dataSet.Tables[table.TableName]);
            }
        }
        else
        {
            dataTable = _dataTable;
        }
        if (dataTable == null)
        {
            if (MissingSchemaAction.Add == _missingSchemaAction)
            {
                dataTable = table.Clone(table.DataSet);
                _dataSet.Tables.Add(dataTable);
            }
            else if (MissingSchemaAction.Error == _missingSchemaAction)
            {
                throw ExceptionBuilder.MergeMissingDefinition(table.TableName);
            }
        }
        else
        {
            if (MissingSchemaAction.Ignore != _missingSchemaAction)
            {
                int count = dataTable.Columns.Count;
                for (int i = 0; i < table.Columns.Count; i++)
                {
                    DataColumn dataColumn = table.Columns[i];
                    DataColumn dataColumn2 = (dataTable.Columns.Contains(dataColumn.ColumnName, caseSensitive: true) ? dataTable.Columns[dataColumn.ColumnName] : null);
                    if (dataColumn2 == null)
                    {
                        if (MissingSchemaAction.Add == _missingSchemaAction)
{
                            dataColumn2 = dataColumn.Clone();
                            dataTable.Columns.Add(dataColumn2);
                            continue;
                        }
                        if (!_isStandAlonetable)
{
                            _dataSet.RaiseMergeFailed(dataTable, System.SR.Format(System.SR.DataMerge_MissingColumnDefinition, table.TableName, dataColumn.ColumnName), _missingSchemaAction);
                            continue;
                        }
                        throw ExceptionBuilder.MergeFailed(System.SR.Format(System.SR.DataMerge_MissingColumnDefinition, table.TableName, dataColumn.ColumnName));
                    }
                    if (dataColumn2.DataType != dataColumn.DataType || (dataColumn2.DataType == typeof(DateTime) && dataColumn2.DateTimeMode != dataColumn.DateTimeMode && (dataColumn2.DateTimeMode & dataColumn.DateTimeMode) != DataSetDateTime.Unspecified))
                    {
                        if (_isStandAlonetable)
{
                            throw ExceptionBuilder.MergeFailed(System.SR.Format(System.SR.DataMerge_DataTypeMismatch, dataColumn.ColumnName));
                        }
                        _dataSet.RaiseMergeFailed(dataTable, System.SR.Format(System.SR.DataMerge_DataTypeMismatch, dataColumn.ColumnName), MissingSchemaAction.Error);
                    }
                    MergeExtendedProperties(dataColumn.ExtendedProperties, dataColumn2.ExtendedProperties);
                }
                if (_isStandAlonetable)
                {
                    for (int j = count; j < dataTable.Columns.Count; j++)
                    {
                        dataTable.Columns[j].CopyExpressionFrom(table.Columns[dataTable.Columns[j].ColumnName]);
                    }
                }
                DataColumn[] primaryKey = dataTable.PrimaryKey;
                DataColumn[] primaryKey2 = table.PrimaryKey;
                if (primaryKey.Length != primaryKey2.Length)
                {
                    if (primaryKey.Length == 0)
                    {
                        DataColumn[] array = new DataColumn[primaryKey2.Length];
                        for (int k = 0; k < primaryKey2.Length; k++)
{
                            array[k] = dataTable.Columns[primaryKey2[k].ColumnName];
                        }
                        dataTable.PrimaryKey = array;
                    }
                    else if (primaryKey2.Length != 0)
                    {
                        _dataSet.RaiseMergeFailed(dataTable, System.SR.DataMerge_PrimaryKeyMismatch, _missingSchemaAction);
                    }
                }
                else
                {
                    for (int l = 0; l < primaryKey.Length; l++)
                    {
                        if (string.Compare(primaryKey[l].ColumnName, primaryKey2[l].ColumnName, ignoreCase: false, dataTable.Locale) != 0)
{
                            _dataSet.RaiseMergeFailed(table, System.SR.Format(System.SR.DataMerge_PrimaryKeyColumnsMismatch, primaryKey[l].ColumnName, primaryKey2[l].ColumnName), _missingSchemaAction);
                        }
                    }
                }
            }
            MergeExtendedProperties(table.ExtendedProperties, dataTable.ExtendedProperties);
        }
        return dataTable;
    }
References System.Data.Merger._dataSet, System.Data.Merger._dataTable, System.Data.Merger._IgnoreNSforTableLookup, System.Data.Merger._isStandAlonetable, System.Data.Merger._missingSchemaAction, System.Data.DataTableCollection.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Data.DataTable.Clone(), System.Data.DataTable.Columns, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Data.DataTableCollection.Contains(), System.Data.InternalDataCollectionBase.Count, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.SR.DataMerge_DataTypeMismatch, System.SR.DataMerge_MissingColumnDefinition, System.SR.DataMerge_PrimaryKeyColumnsMismatch, System.SR.DataMerge_PrimaryKeyMismatch, System.Data.DataTable.DataSet, System.Data.DataTable.ExtendedProperties, System.SR.Format(), System.Data.Merger.MergeExtendedProperties(), System.Data.ExceptionBuilder.MergeFailed(), System.Data.ExceptionBuilder.MergeMissingDefinition(), System.Data.DataTable.Namespace, System.Data.DataTable.PrimaryKey, System.Data.DataSet.RaiseMergeFailed(), System.Data.DataTable.TableName, and System.Data.DataSet.Tables.
Referenced by System.Data.Merger.MergeRows(), and System.Data.Merger.MergeTableData().