Terraria: System.Data.Merger.MergeDataSet
MergeDataSet()
void System.Data.Merger.MergeDataSet (DataSet source) inline package
Definition at line 36 of file Merger.cs.
    {
        if (source == _dataSet)
        {
            return;
        }
        bool enforceConstraints = _dataSet.EnforceConstraints;
        _dataSet.EnforceConstraints = false;
        _IgnoreNSforTableLookup = _dataSet._namespaceURI != source._namespaceURI;
        List<DataColumn> list = null;
        if (MissingSchemaAction.Add == _missingSchemaAction)
        {
            list = new List<DataColumn>();
            foreach (DataTable table in _dataSet.Tables)
            {
                foreach (DataColumn column in table.Columns)
                {
                    list.Add(column);
                }
            }
        }
        for (int i = 0; i < source.Tables.Count; i++)
        {
            MergeTableData(source.Tables[i]);
        }
        if (MissingSchemaAction.Ignore != _missingSchemaAction)
        {
            MergeConstraints(source);
            for (int j = 0; j < source.Relations.Count; j++)
            {
                MergeRelation(source.Relations[j]);
            }
        }
        if (MissingSchemaAction.Add == _missingSchemaAction)
        {
            foreach (DataTable table2 in source.Tables)
            {
                DataTable dataTable3 = ((!_IgnoreNSforTableLookup) ? _dataSet.Tables[table2.TableName, table2.Namespace] : _dataSet.Tables[table2.TableName]);
                foreach (DataColumn column2 in table2.Columns)
                {
                    if (column2.Computed)
                    {
                        DataColumn dataColumn2 = dataTable3.Columns[column2.ColumnName];
                        if (!list.Contains(dataColumn2))
{
                            dataColumn2.CopyExpressionFrom(column2);
                        }
                    }
                }
            }
        }
        MergeExtendedProperties(source.ExtendedProperties, _dataSet.ExtendedProperties);
        foreach (DataTable table3 in _dataSet.Tables)
        {
            table3.EvaluateExpressions();
        }
        _dataSet.EnforceConstraints = enforceConstraints;
    }
References System.Data.Merger._dataSet, System.Data.Merger._IgnoreNSforTableLookup, System.Data.Merger._missingSchemaAction, System.Data.DataTable.Columns, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.DataSet.EnforceConstraints, System.Data.DataSet.ExtendedProperties, System.list, System.Data.Merger.MergeConstraints(), System.Data.Merger.MergeExtendedProperties(), System.Data.Merger.MergeRelation(), System.Data.Merger.MergeTableData(), System.source, and System.Data.DataSet.Tables.