Terraria: System.Net.Http.HttpMethod.Normalize
Normalize()
static HttpMethod System.Net.Http.HttpMethod.Normalize (HttpMethod method) inline static package
Definition at line 165 of file HttpMethod.cs.
    {
        int? http3Index = method._http3Index;
        if (!http3Index.HasValue && method._method.Length >= 3)
        {
            HttpMethod httpMethod = (method._method[0] | 0x20) switch
            {
                99 => s_connectMethod,
                100 => s_deleteMethod,
                103 => s_getMethod,
                104 => s_headMethod,
                111 => s_optionsMethod,
                112 => method._method.Length switch
                {
                    3 => s_putMethod,
                    4 => s_postMethod,
                    _ => s_patchMethod,
                },
                116 => s_traceMethod,
                _ => null,
            };
            if ((object)httpMethod != null && string.Equals(method._method, httpMethod._method, StringComparison.OrdinalIgnoreCase))
            {
                return httpMethod;
            }
        }
        return method;
    }
References System.Net.Http.HttpMethod._http3Index, System.Net.Http.HttpMethod._method, System.Net.Http.HttpMethod.Equals(), System.Net.Http.HttpMethod.s_connectMethod, System.Net.Http.HttpMethod.s_deleteMethod, System.Net.Http.HttpMethod.s_getMethod, System.Net.Http.HttpMethod.s_headMethod, System.Net.Http.HttpMethod.s_optionsMethod, System.Net.Http.HttpMethod.s_patchMethod, System.Net.Http.HttpMethod.s_postMethod, System.Net.Http.HttpMethod.s_putMethod, and System.Net.Http.HttpMethod.s_traceMethod.
Referenced by System.Net.Http.Http3RequestStream.BufferHeaders(), System.Net.Http.HttpConnection.SendAsyncCore(), and System.Net.Http.Http2Connection.WriteHeaders().