Terraria: System.Text.RegularExpressions.RegexCache.Get
Get()
static Regex System.Text.RegularExpressions.RegexCache.Get (Key key) inline static private
Definition at line 141 of file RegexCache.cs.
    {
        long num = 0L;
        Node node = s_lastAccessed;
        if (node != null)
        {
            if (key.Equals(node.Key))
            {
                return node.Regex;
            }
            num = Volatile.Read(ref node.LastAccessStamp);
        }
        if (s_maxCacheSize != 0 && s_cacheDictionary.TryGetValue(key, out var value))
        {
            Volatile.Write(ref value.LastAccessStamp, num + 1);
            s_lastAccessed = value;
            return value.Regex;
        }
        return null;
    }
References System.key, System.L, System.Threading.Volatile.Read(), System.Text.RegularExpressions.RegexCache.s_cacheDictionary, System.Text.RegularExpressions.RegexCache.s_lastAccessed, System.Text.RegularExpressions.RegexCache.s_maxCacheSize, System.Text.RegularExpressions.value, and System.Threading.Volatile.Write().
Referenced by System.Text.RegularExpressions.RegexCache.GetOrAdd(), and System.Text.RegularExpressions.RegexCache.GetOrAdd().