Terraria: System.Xml.Schema.XsdDuration.TryParse
TryParse() [2/2]
static Exception System.Xml.Schema.XsdDuration.TryParse (string s, out XsdDuration result) inline static package
Definition at line 327 of file XsdDuration.cs.
    {
        return TryParse(s, DurationType.Duration, out result);
    }
References System.Xml.Dictionary, System.s, and System.Xml.Schema.XsdDuration.TryParse().
Referenced by System.Xml.Schema.XsdDuration.XsdDuration(), System.Xml.Schema.XsdDuration.TryParse(), System.Xml.Schema.Datatype_dayTimeDuration.TryParseValue(), System.Xml.Schema.Datatype_yearMonthDuration.TryParseValue(), and System.Xml.XmlConvert.TryToTimeSpan().