Terraria: Terraria.Liquid.tilesIgnoreWater
tilesIgnoreWater()
static void Terraria.Liquid.tilesIgnoreWater (bool ignoreSolids) inline static
Definition at line 67 of file Liquid.cs.
    {
        Main.tileSolid[138] = !ignoreSolids;
        Main.tileSolid[484] = !ignoreSolids;
        Main.tileSolid[546] = !ignoreSolids;
    }
References Terraria.Main.tileSolid.
Referenced by Terraria.Liquid.QuickWater(), Terraria.Liquid.SettleWaterAt(), Terraria.WorldGen.ShimmerCleanUp(), Terraria.Liquid.UpdateLiquid(), and Terraria.WorldGen.WaterCheck().