Terraria: Terraria.Liquid.StartPanic
StartPanic()
static void Terraria.Liquid.StartPanic () inline static
Definition at line 966 of file Liquid.cs.
    {
        if (!panicMode)
        {
            GenVars.waterLine = Main.maxTilesY;
            numLiquid = 0;
            LiquidBuffer.numLiquidBuffer = 0;
            panicCounter = 0;
            panicMode = true;
            panicY = Main.maxTilesY - 3;
            if (Main.dedServ)
            {
                Console.WriteLine(Language.GetTextValue("Misc.ForceWaterSettling"));
            }
        }
    }
References Terraria.Main.dedServ, Terraria.Localization.Language.GetTextValue(), Terraria.Main.maxTilesY, Terraria.Liquid.numLiquid, Terraria.Liquid.panicCounter, Terraria.Liquid.panicMode, Terraria.Liquid.panicY, and System.Console.WriteLine().
Referenced by Terraria.Main.startDedInputCallBack(), and Terraria.Liquid.UpdateLiquid().