Terraria: System.Xml.Xsl.Xslt.CompilerScopeManager.SearchVariable
SearchVariable()
int System.Xml.Xsl.Xslt.CompilerScopeManager< V >.SearchVariable (string localName, string uri) inline private
Definition at line 313 of file CompilerScopeManager.cs.
    {
        int num = _lastRecord;
        while (0 <= num)
        {
            string prefix;
            string nsUri;
            ScopeFlags name = GetName(ref _records[num], out prefix, out nsUri);
            if ((name & ScopeFlags.Variable) != 0 && prefix == localName && nsUri == uri)
            {
                return num;
            }
            num--;
        }
        return -1;
    }
References System.Xml.Xsl.Xslt.CompilerScopeManager< V >._lastRecord, System.Xml.Xsl.Xslt.CompilerScopeManager< V >._records, System.Xml.Xsl.Xslt.CompilerScopeManager< V >.GetName(), and System.prefix.
Referenced by System.Xml.Xsl.Xslt.CompilerScopeManager< V >.IsLocalVariable(), and System.Xml.Xsl.Xslt.CompilerScopeManager< V >.LookupVariable().