Terraria: Terraria.Liquid.AttemptToMoveHoney
AttemptToMoveHoney()
static void Terraria.Liquid.AttemptToMoveHoney (int X, int Y, bool tileAtXYHasHoney) inline static private
Definition at line 282 of file Liquid.cs.
    {
        if (Main.tile[X - 1, Y].liquid > 0 && Main.tile[X - 1, Y].honey() != tileAtXYHasHoney)
        {
            if (tileAtXYHasHoney)
            {
                HoneyCheck(X, Y);
            }
            else
            {
                HoneyCheck(X - 1, Y);
            }
        }
        else if (Main.tile[X + 1, Y].liquid > 0 && Main.tile[X + 1, Y].honey() != tileAtXYHasHoney)
        {
            if (tileAtXYHasHoney)
            {
                HoneyCheck(X, Y);
            }
            else
            {
                HoneyCheck(X + 1, Y);
            }
        }
        else if (Main.tile[X, Y - 1].liquid > 0 && Main.tile[X, Y - 1].honey() != tileAtXYHasHoney)
        {
            if (tileAtXYHasHoney)
            {
                HoneyCheck(X, Y);
            }
            else
            {
                HoneyCheck(X, Y - 1);
            }
        }
        else if (Main.tile[X, Y + 1].liquid > 0 && Main.tile[X, Y + 1].honey() != tileAtXYHasHoney)
        {
            if (tileAtXYHasHoney)
            {
                HoneyCheck(X, Y);
            }
            else
            {
                HoneyCheck(X, Y + 1);
            }
        }
    }
References Terraria.Tile.honey(), Terraria.Liquid.HoneyCheck(), Terraria.Tile.liquid, and Terraria.Main.tile.
Referenced by Terraria.Liquid.SettleWaterAt().