Terraria: System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create
Create() [2/3]
static unsafe SafeMsQuicConfigurationHandle System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create (QuicOptions options, QUIC_CREDENTIAL_FLAGS flags, X509Certificate certificate, SslStreamCertificateContext certificateContext, List< SslApplicationProtocol > alpnProtocols) inline static private
Definition at line 92 of file SafeMsQuicConfigurationHandle.cs.
    {
        if (alpnProtocols == null || alpnProtocols.Count == 0)
        {
            throw new Exception("At least one SslApplicationProtocol value must be present in SslClientAuthenticationOptions or SslServerAuthenticationOptions.");
        }
        if (options.MaxBidirectionalStreams > 65535)
        {
            throw new Exception("MaxBidirectionalStreams overflow.");
        }
        if (options.MaxBidirectionalStreams > 65535)
        {
            throw new Exception("MaxBidirectionalStreams overflow.");
        }
        if ((flags & QUIC_CREDENTIAL_FLAGS.CLIENT) == 0)
        {
            if (certificate == null && certificateContext == null)
            {
                throw new Exception("Server must provide certificate");
            }
        }
        else
        {
            flags |= QUIC_CREDENTIAL_FLAGS.NO_CERTIFICATE_VALIDATION | QUIC_CREDENTIAL_FLAGS.INDICATE_CERTIFICATE_RECEIVED;
        }
        if (!OperatingSystem.IsWindows())
        {
            flags |= QUIC_CREDENTIAL_FLAGS.USE_PORTABLE_CERTIFICATES;
        }
        MsQuicNativeMethods.QuicSettings quicSettings = default(MsQuicNativeMethods.QuicSettings);
        quicSettings.IsSetFlags = MsQuicNativeMethods.QuicSettingsIsSetFlags.PeerBidiStreamCount | MsQuicNativeMethods.QuicSettingsIsSetFlags.PeerUnidiStreamCount;
        quicSettings.PeerBidiStreamCount = (ushort)options.MaxBidirectionalStreams;
        quicSettings.PeerUnidiStreamCount = (ushort)options.MaxUnidirectionalStreams;
        MsQuicNativeMethods.QuicSettings settings = quicSettings;
        if (options.IdleTimeout != Timeout.InfiniteTimeSpan)
        {
            if (options.IdleTimeout <= TimeSpan.Zero)
            {
                throw new Exception("IdleTimeout must not be negative.");
            }
            ulong num = (ulong)options.IdleTimeout.Ticks / 10000uL;
            if (num > 4611686018427387903L)
            {
                throw new Exception("IdleTimeout is too large (max 2^62-1 milliseconds)");
            }
            settings.IsSetFlags |= MsQuicNativeMethods.QuicSettingsIsSetFlags.IdleTimeoutMs;
            settings.IdleTimeoutMs = (ulong)options.IdleTimeout.TotalMilliseconds;
        }
        X509Certificate2[] array = null;
        MemoryHandle[] handles = null;
        MsQuicNativeMethods.QuicBuffer[] buffers = null;
        uint status;
        SafeMsQuicConfigurationHandle configuration;
        try
        {
            MsQuicAlpnHelper.Prepare(alpnProtocols, out handles, out buffers);
            status = MsQuicApi.Api.ConfigurationOpenDelegate(MsQuicApi.Api.Registration, (MsQuicNativeMethods.QuicBuffer*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(buffers, 0), (uint)alpnProtocols.Count, ref settings, (uint)sizeof(MsQuicNativeMethods.QuicSettings), IntPtr.Zero, out configuration);
        }
        finally
        {
            MsQuicAlpnHelper.Return(ref handles, ref buffers);
        }
        QuicExceptionHelpers.ThrowIfFailed(status, "ConfigurationOpen failed.");
        try
        {
            MsQuicNativeMethods.CredentialConfig credConfig = default(MsQuicNativeMethods.CredentialConfig);
            credConfig.Flags = flags;
            if (certificateContext != null)
            {
                certificate = (X509Certificate2)_contextCertificate.GetValue(certificateContext);
                array = (X509Certificate2[])_contextChain.GetValue(certificateContext);
                if (certificate == null || array == null)
                {
                    throw new ArgumentException("certificateContext");
                }
            }
            if (certificate != null)
            {
                if (OperatingSystem.IsWindows())
                {
                    credConfig.Type = QUIC_CREDENTIAL_TYPE.CONTEXT;
                    credConfig.Certificate = certificate.Handle;
                    status = MsQuicApi.Api.ConfigurationLoadCredentialDelegate(configuration, ref credConfig);
                }
                else
                {
                    byte[] array2;
                    if (array != null && array.Length != 0)
                    {
                        X509Certificate2Collection x509Certificate2Collection = new X509Certificate2Collection();
                        x509Certificate2Collection.Add(certificate);
                        for (int i = 0; i < array?.Length; i++)
{
                            x509Certificate2Collection.Add(array[i]);
                        }
                        array2 = x509Certificate2Collection.Export(X509ContentType.Pfx);
                    }
                    else
                    {
                        array2 = certificate.Export(X509ContentType.Pfx);
                    }
                    fixed (byte* ptr = array2)
                    {
                        void* ptr2 = ptr;
                        Unsafe.SkipInit(out MsQuicNativeMethods.CredentialConfigCertificatePkcs12 credentialConfigCertificatePkcs);
                        credentialConfigCertificatePkcs.Asn1Blob = (IntPtr)ptr2;
                        credentialConfigCertificatePkcs.Asn1BlobLength = (uint)array2.Length;
                        credentialConfigCertificatePkcs.PrivateKeyPassword = IntPtr.Zero;
                        credConfig.Type = QUIC_CREDENTIAL_TYPE.PKCS12;
                        credConfig.Certificate = (IntPtr)(&credentialConfigCertificatePkcs);
                        status = MsQuicApi.Api.ConfigurationLoadCredentialDelegate(configuration, ref credConfig);
                    }
                }
            }
            else
            {
                credConfig.Type = QUIC_CREDENTIAL_TYPE.NONE;
                status = MsQuicApi.Api.ConfigurationLoadCredentialDelegate(configuration, ref credConfig);
            }
            QuicExceptionHelpers.ThrowIfFailed(status, "ConfigurationLoadCredential failed.");
            return configuration;
        }
        catch
        {
            configuration.Dispose();
            throw;
        }
    }
References System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle._contextCertificate, System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle._contextChain, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.array, System.buffers, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Threading.Timeout.InfiniteTimeSpan, System.OperatingSystem.IsWindows(), System.L, System.options, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAlpnHelper.Prepare(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAlpnHelper.Return(), System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(), System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement(), System.IntPtr.Zero, and System.TimeSpan.Zero.