Terraria: CreativePowers.APerPlayerTogglePower.Deserialize_SyncEveryone
Deserialize_SyncEveryone()
void CreativePowers.APerPlayerTogglePower.Deserialize_SyncEveryone (BinaryReader reader, int userId) inline private inherited
         {
             int num = (int)Math.Ceiling((float)_perPlayerIsEnabled.Length / 8f);
             if (Main.netMode == 2 && !CreativePowersHelper.IsAvailableForPlayer(this, userId))
             {
                 reader.ReadBytes(num);
                 return;
             }
             for (int i = 0; i < num; i++)
             {
                 BitsByte bitsByte = reader.ReadByte();
                 for (int j = 0; j < 8; j++)
                 {
                     int num2 = i * 8 + j;
                     if (num2 != Main.myPlayer)
                     {
                         if (num2 >= _perPlayerIsEnabled.Length)
{
                             break;
                         }
                         SetEnabledState(num2, bitsByte[j]);
                     }
                 }
             }
         }
References CreativePowers.APerPlayerTogglePower._perPlayerIsEnabled, CreativePowersHelper.IsAvailableForPlayer(), Main.myPlayer, Main.netMode, and CreativePowers.APerPlayerTogglePower.SetEnabledState().
Referenced by CreativePowers.APerPlayerTogglePower.DeserializeNetMessage().