Terraria: System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create
Create() [1/3]
static SafeMsQuicConfigurationHandle System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create (QuicClientConnectionOptions options) inline static
Definition at line 32 of file SafeMsQuicConfigurationHandle.cs.
    {
        X509Certificate certificate = null;
        if (options.ClientAuthenticationOptions != null)
        {
            if (options.ClientAuthenticationOptions.CipherSuitesPolicy != null)
            {
                throw new PlatformNotSupportedException(System.SR.Format(System.SR.net_quic_ssl_option, "CipherSuitesPolicy"));
            }
            if (options.ClientAuthenticationOptions.EncryptionPolicy == EncryptionPolicy.NoEncryption)
            {
                throw new PlatformNotSupportedException(System.SR.Format(System.SR.net_quic_ssl_option, "EncryptionPolicy"));
            }
            if (options.ClientAuthenticationOptions.ClientCertificates != null)
            {
                foreach (X509Certificate clientCertificate in options.ClientAuthenticationOptions.ClientCertificates)
                {
                    try
                    {
                        if (((X509Certificate2)clientCertificate).HasPrivateKey)
{
                            certificate = clientCertificate;
                            break;
                        }
                    }
                    catch
                    {
                    }
                }
            }
        }
        return Create(options, QUIC_CREDENTIAL_FLAGS.CLIENT, certificate, null, options.ClientAuthenticationOptions?.ApplicationProtocols);
    }
References System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), System.SR.Format(), System.SR.net_quic_ssl_option, and System.options.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicConnection.MsQuicConnection(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.State.State(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), and System.Net.Quic.Implementations.MsQuic.MsQuicListener.NativeCallbackHandler().