Terraria: System.Xml.Xsl.Xslt.CompilerScopeManager.AddRecord
AddRecord() [1/2]
void System.Xml.Xsl.Xslt.CompilerScopeManager< V >.AddRecord () inline private
Definition at line 174 of file CompilerScopeManager.cs.
    {
        _records[_lastRecord].scopeCount = _lastScopes;
        if (++_lastRecord == _records.Length)
        {
            ScopeRecord[] array = new ScopeRecord[_lastRecord * 2];
            Array.Copy(_records, array, _lastRecord);
            _records = array;
        }
        _lastScopes = 0;
    }
References System.Xml.Xsl.Xslt.CompilerScopeManager< V >._lastRecord, System.Xml.Xsl.Xslt.CompilerScopeManager< V >._lastScopes, System.Xml.Xsl.Xslt.CompilerScopeManager< V >._records, System.array, System.Array.Copy(), and System.Xml.Xsl.Xslt.CompilerScopeManager< V >.ScopeRecord.scopeCount.
Referenced by System.Xml.Xsl.Xslt.CompilerScopeManager< V >.AddExNamespace(), System.Xml.Xsl.Xslt.CompilerScopeManager< V >.AddNsDeclaration(), System.Xml.Xsl.Xslt.CompilerScopeManager< V >.AddRecord(), System.Xml.Xsl.Xslt.CompilerScopeManager< V >.AddVariable(), and System.Xml.Xsl.Xslt.CompilerScopeManager< V >.SetFlag().