Terraria: CreativePowers.APerPlayerTogglePower.button_OnUpdate
button_OnUpdate()
void CreativePowers.APerPlayerTogglePower.button_OnUpdate (UIElement affectedElement) inline private inherited
         {
             bool currentOption = _perPlayerIsEnabled[Main.myPlayer];
             GroupOptionButton<bool> groupOptionButton = affectedElement as GroupOptionButton<bool>;
             groupOptionButton.SetCurrentOption(currentOption);
             if (affectedElement.IsMouseHovering)
             {
                 string originalText = Language.GetTextValue(groupOptionButton.IsSelected ? (_powerNameKey + "_Enabled") : (_powerNameKey + "_Disabled"));
                 CreativePowersHelper.AddDescriptionIfNeeded(ref originalText, _powerNameKey + "_Description");
                 CreativePowersHelper.AddUnlockTextIfNeeded(ref originalText, GetIsUnlocked(), _powerNameKey + "_Unlock");
                 CreativePowersHelper.AddPermissionTextIfNeeded(this, ref originalText);
                 Main.instance.MouseTextNoOverride(originalText, 0, 0);
             }
         }
References CreativePowers.APerPlayerTogglePower._perPlayerIsEnabled, CreativePowers.APerPlayerTogglePower._powerNameKey, CreativePowersHelper.AddDescriptionIfNeeded(), CreativePowersHelper.AddPermissionTextIfNeeded(), CreativePowersHelper.AddUnlockTextIfNeeded(), CreativePowers.APerPlayerTogglePower.GetIsUnlocked(), Language.GetTextValue(), Main.instance, UIElement.IsMouseHovering, GroupOptionButton< T >.IsSelected, Main.MouseTextNoOverride(), Main.myPlayer, and GroupOptionButton< T >.SetCurrentOption().
Referenced by CreativePowers.APerPlayerTogglePower.ProvidePowerButtons().