Terraria: System.Runtime.Serialization.HybridObjectCache.Add
Add()
void System.Runtime.Serialization.HybridObjectCache.Add (string id, object obj) inline package
Definition at line 15 of file HybridObjectCache.cs.
    {
        if (_objectDictionary == null)
        {
            _objectDictionary = new Dictionary<string, object>();
        }
        if (_objectDictionary.TryGetValue(id, out var _))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.MultipleIdDefinition, id)));
        }
        _objectDictionary.Add(id, obj);
    }
References System.Runtime.Serialization.HybridObjectCache._objectDictionary, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), System.SR.MultipleIdDefinition, System.obj, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNewObjectWithId(), and System.Runtime.Serialization.XmlObjectSerializerReadContext.ReplaceDeserializedObject().