Terraria: WeightedRandom.Get
Get()
T WeightedRandom< T >.Get () inline
     {
         if (needsRefresh)
         {
             CalculateTotalWeight();
         }
         double num = random.NextDouble();
         num *= _totalWeight;
         foreach (Tuple<T, double> element in elements)
         {
             if (num > element.Item2)
             {
                 num -= element.Item2;
                 continue;
             }
             return element.Item1;
         }
         return default(T);
     }
References WeightedRandom< T >._totalWeight, WeightedRandom< T >.CalculateTotalWeight(), WeightedRandom< T >.elements, WeightedRandom< T >.needsRefresh, UnifiedRandom.NextDouble(), WeightedRandom< T >.random, and T.
Referenced by WeightedRandom< T >.operator T().