Terraria: System.Xml.Linq.XNamespace.XNamespace
XNamespace()
System.Xml.Linq.XNamespace.XNamespace (string namespaceName) inline package
Definition at line 30 of file XNamespace.cs.
    {
        _namespaceName = namespaceName;
        _hashCode = namespaceName.GetHashCode();
        _names = new XHashtable<XName>(ExtractLocalName, 8);
    }
References System.Xml.Linq.XNamespace._hashCode, System.Xml.Linq.XNamespace._names, System.Xml.Linq.XNamespace._namespaceName, System.Xml.Dictionary, and System.Xml.Linq.XNamespace.ExtractLocalName().
Referenced by System.Xml.Linq.XNamespace.EnsureNamespace(), and System.Xml.Linq.XNamespace.Get().