Terraria: System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.AddTryStart
AddTryStart()
void System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.AddTryStart (int index) inline private
Definition at line 73 of file LightLambda.cs.
        {
            if (!_tryStart.TryGetValue(index, out var value))
            {
                _tryStart.Add(index, 1);
            }
            else
            {
                _tryStart[index] = value + 1;
            }
        }
References System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter._tryStart, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.index, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.Analyze().