Terraria: System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.Analyze
Analyze()
void System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.Analyze () inline private
Definition at line 32 of file LightLambda.cs.
        {
            Instruction[] instructions = _interpreter.Instructions.Instructions;
            Instruction[] array = instructions;
            foreach (Instruction instruction in array)
            {
                if (instruction is EnterTryCatchFinallyInstruction { Handler: var handler })
                {
                    AddTryStart(handler.TryStartIndex);
                    AddHandlerExit(handler.TryEndIndex + 1);
                    if (handler.IsFinallyBlockExist)
                    {
                        _handlerEnter.Add(handler.FinallyStartIndex, "finally");
                        AddHandlerExit(handler.FinallyEndIndex);
                    }
                    if (handler.IsCatchBlockExist)
                    {
                        ExceptionHandler[] handlers = handler.Handlers;
                        foreach (ExceptionHandler exceptionHandler in handlers)
{
                            _handlerEnter.Add(exceptionHandler.HandlerStartIndex - 1, exceptionHandler.ToString());
                            AddHandlerExit(exceptionHandler.HandlerEndIndex);
                            ExceptionFilter filter = exceptionHandler.Filter;
                            if (filter != null)
{
                                _handlerEnter.Add(filter.StartIndex - 1, "filter");
                                AddHandlerExit(filter.EndIndex);
                            }
                        }
                    }
                }
                if (instruction is EnterTryFaultInstruction { Handler: var handler2 })
                {
                    AddTryStart(handler2.TryStartIndex);
                    AddHandlerExit(handler2.TryEndIndex + 1);
                    _handlerEnter.Add(handler2.FinallyStartIndex, "fault");
                    AddHandlerExit(handler2.FinallyEndIndex);
                }
            }
        }
References System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter._handlerEnter, System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter._interpreter, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.AddHandlerExit(), System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.AddTryStart(), System.array, System.Linq.Expressions.Interpreter.InstructionArray.Instructions, and System.Linq.Expressions.Interpreter.Interpreter.Instructions.
Referenced by System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.DebugViewPrinter().