Terraria: System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.ToString
ToString()
override string System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.ToString () inline
Definition at line 100 of file LightLambda.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            string value = _interpreter.Name ?? "lambda_method";
            stringBuilder.Append("object ").Append(value).AppendLine("(object[])");
            stringBuilder.AppendLine("{");
            stringBuilder.Append("  .locals ").Append(_interpreter.LocalCount).AppendLine();
            stringBuilder.Append("  .maxstack ").Append(_interpreter.Instructions.MaxStackDepth).AppendLine();
            stringBuilder.Append("  .maxcontinuation ").Append(_interpreter.Instructions.MaxContinuationDepth).AppendLine();
            stringBuilder.AppendLine();
            Instruction[] instructions = _interpreter.Instructions.Instructions;
            InstructionArray.DebugView debugView = new InstructionArray.DebugView(_interpreter.Instructions);
            InstructionList.DebugView.InstructionView[] instructionViews = debugView.GetInstructionViews();
            for (int i = 0; i < instructions.Length; i++)
            {
                EmitExits(stringBuilder, i);
                if (_tryStart.TryGetValue(i, out var value2))
                {
                    for (int j = 0; j < value2; j++)
                    {
                        stringBuilder.Append(_indent).AppendLine(".try");
                        stringBuilder.Append(_indent).AppendLine("{");
                        Indent();
                    }
                }
                if (_handlerEnter.TryGetValue(i, out var value3))
                {
                    stringBuilder.Append(_indent).AppendLine(value3);
                    stringBuilder.Append(_indent).AppendLine("{");
                    Indent();
                }
                InstructionList.DebugView.InstructionView instructionView = instructionViews[i];
                StringBuilder stringBuilder2 = stringBuilder;
                IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
                StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(5, 3, stringBuilder2, invariantCulture);
                handler.AppendFormatted(_indent);
                handler.AppendLiteral("IP_");
                handler.AppendFormatted(i.ToString().PadLeft(4, '0'));
                handler.AppendLiteral(": ");
                handler.AppendFormatted(instructionView.GetValue());
                stringBuilder2.AppendLine(invariantCulture, ref handler);
            }
            EmitExits(stringBuilder, instructions.Length);
            stringBuilder.AppendLine("}");
            return stringBuilder.ToString();
        }
References System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter._handlerEnter, System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter._indent, System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter._interpreter, System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter._tryStart, System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendLiteral(), System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.EmitExits(), System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.Indent(), System.Linq.Expressions.Interpreter.InstructionArray.Instructions, System.Linq.Expressions.Interpreter.Interpreter.Instructions, System.Globalization.CultureInfo.InvariantCulture, System.Linq.Expressions.Interpreter.Interpreter.LocalCount, System.Linq.Expressions.Interpreter.InstructionArray.MaxContinuationDepth, System.Linq.Expressions.Interpreter.InstructionArray.MaxStackDepth, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.