Terraria: System.Collections.Generic.SortedSet.TreeSubSet.InOrderTreeWalk
InOrderTreeWalk()
override bool System.Collections.Generic.SortedSet< T >.TreeSubSet.InOrderTreeWalk (TreeWalkPredicate< T > action) inline package virtual
Reimplemented from System.Collections.Generic.SortedSet< T >.
Definition at line 519 of file SortedSet.cs.
        {
            VersionCheck();
            if (root == null)
            {
                return true;
            }
            Stack<Node> stack = new Stack<Node>(2 * Log2(count + 1));
            Node node = root;
            while (node != null)
            {
                if (IsWithinRange(node.Item))
                {
                    stack.Push(node);
                    node = node.Left;
                }
                else
                {
                    node = ((!_lBoundActive || base.Comparer.Compare(_min, node.Item) <= 0) ? node.Left : node.Right);
                }
            }
            while (stack.Count != 0)
            {
                node = stack.Pop();
                if (!action(node))
                {
                    return false;
                }
                Node node2 = node.Right;
                while (node2 != null)
                {
                    if (IsWithinRange(node2.Item))
                    {
                        stack.Push(node2);
                        node2 = node2.Left;
                    }
                    else
                    {
                        node2 = ((!_lBoundActive || base.Comparer.Compare(_min, node2.Item) <= 0) ? node2.Left : node2.Right);
                    }
                }
            }
            return true;
        }
References System.Collections.Generic.SortedSet< T >.TreeSubSet._lBoundActive, System.Collections.Generic.SortedSet< T >.TreeSubSet._min, System.action, System.Collections.Generic.Dictionary< TKey, TValue >.Comparer, System.Collections.Generic.SortedSet< T >.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.Collections.Generic.SortedSet< T >.TreeSubSet.IsWithinRange(), System.Collections.Generic.SortedSet< T >.Log2(), System.Collections.Generic.SortedSet< T >.root, and System.Collections.Generic.SortedSet< T >.TreeSubSet.VersionCheck().
Referenced by System.Collections.Generic.SortedSet< T >.TreeSubSet.VersionCheckImpl().