Terraria: System.Collections.Generic.SortedSet.TreeSubSet.IsWithinRange
IsWithinRange()
override bool System.Collections.Generic.SortedSet< T >.TreeSubSet.IsWithinRange (T item) inline package virtual
Reimplemented from System.Collections.Generic.SortedSet< T >.
Definition at line 508 of file SortedSet.cs.
        {
            int num = (_lBoundActive ? base.Comparer.Compare(_min, item) : (-1));
            if (num > 0)
            {
                return false;
            }
            num = ((!_uBoundActive) ? 1 : base.Comparer.Compare(_max, item));
            return num >= 0;
        }
References System.Collections.Generic.SortedSet< T >.TreeSubSet._lBoundActive, System.Collections.Generic.SortedSet< T >.TreeSubSet._max, System.Collections.Generic.SortedSet< T >.TreeSubSet._min, System.Collections.Generic.SortedSet< T >.TreeSubSet._uBoundActive, System.Collections.Generic.Dictionary< TKey, TValue >.Comparer, and System.item.
Referenced by System.Collections.Generic.SortedSet< T >.TreeSubSet.AddIfNotPresent(), System.Collections.Generic.SortedSet< T >.TreeSubSet.BreadthFirstTreeWalk(), System.Collections.Generic.SortedSet< T >.TreeSubSet.DoRemove(), System.Collections.Generic.SortedSet< T >.TreeSubSet.FindNode(), and System.Collections.Generic.SortedSet< T >.TreeSubSet.InOrderTreeWalk().