Terraria: System.Net.Mail.SmtpNegotiateAuthenticationModule.Authenticate
Authenticate()
Authorization System.Net.Mail.SmtpNegotiateAuthenticationModule.Authenticate (string challenge, NetworkCredential credential, object sessionCookie, string spn, ChannelBinding channelBindingToken) inline
Implements System.Net.Mail.ISmtpAuthenticationModule.
Definition at line 17 of file SmtpNegotiateAuthenticationModule.cs.
    {
        try
        {
            lock (_sessions)
            {
                if (!_sessions.TryGetValue(sessionCookie, out var value))
                {
                    if (credential == null)
                    {
                        return null;
                    }
                    value = (_sessions[sessionCookie] = new System.Net.NTAuthentication(isServer: false, "Negotiate", credential, spn, System.Net.ContextFlagsPal.Connection | System.Net.ContextFlagsPal.AcceptStream, channelBindingToken));
                }
                string token = null;
                if (!value.IsCompleted)
                {
                    byte[] incomingBlob = null;
                    if (challenge != null)
                    {
                        incomingBlob = Convert.FromBase64String(challenge);
                    }
                    byte[] outgoingBlob = value.GetOutgoingBlob(incomingBlob, thrownOnError: false);
                    if (value.IsCompleted && outgoingBlob == null)
                    {
                        token = "\r\n";
                    }
                    if (outgoingBlob != null)
                    {
                        token = Convert.ToBase64String(outgoingBlob);
                    }
                }
                else
                {
                    token = GetSecurityLayerOutgoingBlob(challenge, value);
                }
                return new Authorization(token, value.IsCompleted);
            }
        }
        catch (NullReferenceException)
        {
            return null;
        }
    }
References System.Net.Mail.SmtpNegotiateAuthenticationModule._sessions, System.Net.Authorization, System.Convert.FromBase64String(), System.Net.Mail.SmtpNegotiateAuthenticationModule.GetSecurityLayerOutgoingBlob(), System.Convert.ToBase64String(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.