Terraria: System.Net.Mail.SmtpNegotiateAuthenticationModule.GetSecurityLayerOutgoingBlob
GetSecurityLayerOutgoingBlob()
string System.Net.Mail.SmtpNegotiateAuthenticationModule.GetSecurityLayerOutgoingBlob (string challenge, System::Net::NTAuthentication clientContext) inline private
Definition at line 75 of file SmtpNegotiateAuthenticationModule.cs.
    {
        if (challenge == null)
        {
            return null;
        }
        byte[] array = Convert.FromBase64String(challenge);
        int num;
        try
        {
            num = clientContext.VerifySignature(array, 0, array.Length);
        }
        catch (Win32Exception)
        {
            return null;
        }
        if (num < 4 || array[0] != 1 || array[1] != 0 || array[2] != 0 || array[3] != 0)
        {
            return null;
        }
        byte[] output = null;
        try
        {
            num = clientContext.MakeSignature(array, 0, 4, ref output);
        }
        catch (Win32Exception)
        {
            return null;
        }
        return Convert.ToBase64String(output, 0, num);
    }
References System.array, System.Convert.FromBase64String(), and System.Convert.ToBase64String().
Referenced by System.Net.Mail.SmtpNegotiateAuthenticationModule.Authenticate().