Terraria: System.Reflection.RuntimeAssembly.GetModulesInternal
GetModulesInternal()
RuntimeModule[] System.Reflection.RuntimeAssembly.GetModulesInternal (bool loadIfNotFound, bool getResourceModules) inline private inherited
Definition at line 523 of file RuntimeAssembly.cs.
    {
        RuntimeModule[] o = null;
        RuntimeAssembly assembly = this;
        GetModules(new QCallAssembly(ref assembly), loadIfNotFound, getResourceModules, ObjectHandleOnStack.Create(ref o));
        return o;
    }
References System.Runtime.Serialization.Dictionary, and System.Reflection.Assembly.GetModules().
Referenced by System.Reflection.RuntimeAssembly.GetLoadedModules(), and System.Reflection.RuntimeAssembly.GetModules().