Terraria: System.Reflection.RuntimeAssembly.AddPublicNestedTypes
AddPublicNestedTypes()
static void System.Reflection.RuntimeAssembly.AddPublicNestedTypes (Type type, List< Type > types, List< Exception > exceptions) inline static private inherited
Definition at line 596 of file RuntimeAssembly.cs.
    {
        Type[] nestedTypes;
        try
        {
            nestedTypes = type.GetNestedTypes(BindingFlags.Public);
        }
        catch (Exception item)
        {
            exceptions.Add(item);
            return;
        }
        Type[] array = nestedTypes;
        foreach (Type type2 in array)
        {
            types.Add(type2);
            AddPublicNestedTypes(type2, types, exceptions);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.RuntimeAssembly.AddPublicNestedTypes(), System.array, System.Runtime.Serialization.Dictionary, System.exceptions, System.item, and System.type.
Referenced by System.Reflection.RuntimeAssembly.AddPublicNestedTypes(), and System.Reflection.RuntimeAssembly.GetForwardedTypes().