Terraria: System.Reflection.RuntimeAssembly.GetName
GetName() [2/2]
override AssemblyName System.Reflection.RuntimeAssembly.GetName (bool copiedName) inline virtual inherited
Reimplemented from System.Reflection.Assembly.
Definition at line 193 of file RuntimeAssembly.cs.
    {
        string codeBase = GetCodeBase();
        AssemblyName assemblyName = new AssemblyName(GetSimpleName(), GetPublicKey(), null, GetVersion(), GetLocale(), GetHashAlgorithm(), AssemblyVersionCompatibility.SameMachine, codeBase, GetFlags() | AssemblyNameFlags.PublicKey);
        Module manifestModule = ManifestModule;
        if (manifestModule.MDStreamVersion > 65536)
        {
            manifestModule.GetPEKind(out var peKind, out var machine);
            assemblyName.SetProcArchIndex(peKind, machine);
        }
        return assemblyName;
    }
References System.Runtime.Serialization.Dictionary, System.Reflection.RuntimeAssembly.GetCodeBase(), System.Reflection.RuntimeAssembly.GetFlags(), System.Reflection.RuntimeAssembly.GetHashAlgorithm(), System.Reflection.RuntimeAssembly.GetLocale(), System.Reflection.RuntimeAssembly.GetPublicKey(), System.Reflection.RuntimeAssembly.GetSimpleName(), System.Reflection.RuntimeAssembly.GetVersion(), and System.Reflection.RuntimeAssembly.ManifestModule.
Referenced by System.Reflection.Emit.AssemblyBuilder.GetName().