Terraria: System.Reflection.RuntimeAssembly.GetModule
GetModule() [1/2]
static void System.Reflection.RuntimeAssembly.GetModule (QCallAssembly assembly, string name, ObjectHandleOnStack retModule) private inherited
Referenced by System.Reflection.RuntimeAssembly.GetFile(), System.Reflection.Emit.AssemblyBuilder.GetModule(), and System.Reflection.RuntimeAssembly.GetModule().