Terraria: System.Reflection.RuntimeAssembly.GetForwardedTypes
GetForwardedTypes()
override Type[] System.Reflection.RuntimeAssembly.GetForwardedTypes () inline sealed virtual inherited
Reimplemented from System.Reflection.Assembly.
Definition at line 548 of file RuntimeAssembly.cs.
    {
        List<Type> list = new List<Type>();
        List<Exception> list2 = new List<Exception>();
        GetManifestModule(GetNativeHandle()).MetadataImport.Enum(MetadataTokenType.ExportedType, 0, out var result);
        RuntimeAssembly assembly = this;
        QCallAssembly assembly2 = new QCallAssembly(ref assembly);
        for (int i = 0; i < result.Length; i++)
        {
            MetadataToken mdtExternalType = result[i];
            Type o = null;
            Exception item = null;
            ObjectHandleOnStack type = ObjectHandleOnStack.Create(ref o);
            try
            {
                GetForwardedType(assembly2, mdtExternalType, type);
                if (o == null)
                {
                    continue;
                }
            }
            catch (Exception ex)
            {
                o = null;
                item = ex;
            }
            if (o != null)
            {
                list.Add(o);
                AddPublicNestedTypes(o, list, list2);
            }
            else
            {
                list2.Add(item);
            }
        }
        if (list2.Count != 0)
        {
            int count = list.Count;
            int count2 = list2.Count;
            list.AddRange(new Type[count2]);
            list2.InsertRange(0, new Exception[count]);
            throw new ReflectionTypeLoadException(list.ToArray(), list2.ToArray());
        }
        return list.ToArray();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.RuntimeAssembly.AddPublicNestedTypes(), System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.Reflection.RuntimeAssembly.GetForwardedType(), System.Reflection.RuntimeAssembly.GetManifestModule(), System.Reflection.RuntimeAssembly.GetNativeHandle(), System.item, System.list, and System.type.