Terraria: System.Security.Cryptography.HKDF.Expand
Expand() [1/3]
static byte[] System.Security.Cryptography.HKDF.Expand (HashAlgorithmName hashAlgorithmName, byte[] prk, int outputLength, byte?[] info = null) inline static
Definition at line 40 of file HKDF.cs.
    {
        if (prk == null)
        {
            throw new ArgumentNullException("prk");
        }
        if (outputLength <= 0)
        {
            throw new ArgumentOutOfRangeException("outputLength", System.SR.ArgumentOutOfRange_NeedPosNum);
        }
        int num = HashLength(hashAlgorithmName);
        int num2 = 255 * num;
        if (outputLength <= 0 || outputLength > num2)
        {
            throw new ArgumentOutOfRangeException("outputLength", System.SR.Format(System.SR.Cryptography_Okm_TooLarge, num2));
        }
        byte[] array = new byte[outputLength];
        Expand(hashAlgorithmName, num, prk, array, info);
        return array;
    }
References System.SR.ArgumentOutOfRange_NeedPosNum, System.array, System.SR.Cryptography_Okm_TooLarge, System.Security.Cryptography.HKDF.Expand(), System.SR.Format(), System.Security.Cryptography.HKDF.HashLength(), and System.info.
Referenced by System.Security.Cryptography.HKDF.DeriveKey(), System.Security.Cryptography.HKDF.DeriveKey(), System.Security.Cryptography.HKDF.Expand(), and System.Security.Cryptography.HKDF.Expand().