Terraria: System.Security.Cryptography.HKDF.HashLength
HashLength()
static int System.Security.Cryptography.HKDF.HashLength (HashAlgorithmName hashAlgorithmName) inline static private
Definition at line 183 of file HKDF.cs.
    {
        if (hashAlgorithmName == HashAlgorithmName.SHA1)
        {
            return 20;
        }
        if (hashAlgorithmName == HashAlgorithmName.SHA256)
        {
            return 32;
        }
        if (hashAlgorithmName == HashAlgorithmName.SHA384)
        {
            return 48;
        }
        if (hashAlgorithmName == HashAlgorithmName.SHA512)
        {
            return 64;
        }
        if (hashAlgorithmName == HashAlgorithmName.MD5)
        {
            return 16;
        }
        throw new ArgumentOutOfRangeException("hashAlgorithmName");
    }
References System.Security.Cryptography.HashAlgorithmName.MD5, System.Security.Cryptography.HashAlgorithmName.SHA1, System.Security.Cryptography.HashAlgorithmName.SHA256, System.Security.Cryptography.HashAlgorithmName.SHA384, and System.Security.Cryptography.HashAlgorithmName.SHA512.
Referenced by System.Security.Cryptography.HKDF.DeriveKey(), System.Security.Cryptography.HKDF.DeriveKey(), System.Security.Cryptography.HKDF.Expand(), System.Security.Cryptography.HKDF.Expand(), System.Security.Cryptography.HKDF.Extract(), and System.Security.Cryptography.HKDF.Extract().