Terraria: System.Security.Cryptography.HKDF.Expand
Expand() [2/3]
static void System.Security.Cryptography.HKDF.Expand (HashAlgorithmName hashAlgorithmName, int hashLength, ReadOnlySpan< byte > prk, Span< byte > output, ReadOnlySpan< byte > info) inline static private
Definition at line 76 of file HKDF.cs.
    {
        if (prk.Length < hashLength)
        {
            throw new ArgumentException(System.SR.Format(System.SR.Cryptography_Prk_TooSmall, hashLength), "prk");
        }
        Span<byte> span = stackalloc byte[1];
        ref byte reference = ref span[0];
        Span<byte> span2 = Span<byte>.Empty;
        Span<byte> destination = output;
        Span<byte> span3 = stackalloc byte[64];
        ReadOnlySpan<byte> readOnlySpan = default(Span<byte>);
        byte[] array = null;
        if (output.Overlaps(info))
        {
            if (info.Length > 64)
            {
                array = System.Security.Cryptography.CryptoPool.Rent(info.Length);
                span3 = array;
            }
            span3 = span3.Slice(0, info.Length);
            info.CopyTo(span3);
            readOnlySpan = span3;
        }
        else
        {
            readOnlySpan = info;
        }
        using (IncrementalHash incrementalHash = IncrementalHash.CreateHMAC(hashAlgorithmName, prk))
        {
            int num = 1;
            while (true)
            {
                incrementalHash.AppendData(span2);
                incrementalHash.AppendData(readOnlySpan);
                reference = (byte)num;
                incrementalHash.AppendData(span);
                if (destination.Length < hashLength)
                {
                    break;
                }
                span2 = destination.Slice(0, hashLength);
                destination = destination.Slice(hashLength);
                GetHashAndReset(incrementalHash, span2);
                num++;
            }
            if (destination.Length > 0)
            {
                Span<byte> output2 = stackalloc byte[hashLength];
                GetHashAndReset(incrementalHash, output2);
                output2.Slice(0, destination.Length).CopyTo(destination);
            }
        }
        if (array != null)
        {
            System.Security.Cryptography.CryptoPool.Return(array, info.Length);
        }
    }
References System.Security.Cryptography.IncrementalHash.AppendData(), System.array, System.Security.Cryptography.IncrementalHash.CreateHMAC(), System.SR.Cryptography_Prk_TooSmall, System.destination, System.Span< T >.Empty, System.SR.Format(), System.Security.Cryptography.HKDF.GetHashAndReset(), System.info, System.ReadOnlySpan< T >.Length, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), and System.Span< T >.Slice().