Terraria: System.Security.Cryptography.HKDF.Expand
Expand() [3/3]
static void System.Security.Cryptography.HKDF.Expand (HashAlgorithmName hashAlgorithmName, ReadOnlySpan< byte > prk, Span< byte > output, ReadOnlySpan< byte > info) inline static
Definition at line 61 of file HKDF.cs.
    {
        int num = HashLength(hashAlgorithmName);
        if (output.Length == 0)
        {
            throw new ArgumentException(System.SR.Argument_DestinationTooShort, "output");
        }
        int num2 = 255 * num;
        if (output.Length > num2)
        {
            throw new ArgumentException(System.SR.Format(System.SR.Cryptography_Okm_TooLarge, num2), "output");
        }
        Expand(hashAlgorithmName, num, prk, output, info);
    }
References System.SR.Argument_DestinationTooShort, System.SR.Cryptography_Okm_TooLarge, System.Security.Cryptography.HKDF.Expand(), System.SR.Format(), System.Security.Cryptography.HKDF.HashLength(), System.info, and System.Span< T >.Length.