Terraria: Terraria.WorldBuilding.ShapeData.GetBounds
GetBounds()
static Rectangle Terraria.WorldBuilding.ShapeData.GetBounds (Point origin, params ShapeData[] shapes) inline static
Definition at line 66 of file ShapeData.cs.
    {
        int num = shapes[0]._points.First().X;
        int num2 = num;
        int num3 = shapes[0]._points.First().Y;
        int num4 = num3;
        for (int i = 0; i < shapes.Length; i++)
        {
            foreach (Point16 point in shapes[i]._points)
            {
                num = Math.Max(num, point.X);
                num2 = Math.Min(num2, point.X);
                num3 = Math.Max(num3, point.Y);
                num4 = Math.Min(num4, point.Y);
            }
        }
        return new Rectangle(num2 + origin.X, num4 + origin.Y, num - num2, num3 - num4);
    }
References Terraria.WorldBuilding.ShapeData._points, System.Math.Max(), System.Math.Min(), Microsoft.Xna.Framework.Point.X, Terraria.DataStructures.Point16.X, Microsoft.Xna.Framework.Point.Y, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.GameContent.Biomes.CorruptionPitBiome.Place().