Terraria: Terraria.WorldBuilding.ShapeData.Add
Add() [1/2]
void Terraria.WorldBuilding.ShapeData.Add (int x, int y) inline
Definition at line 25 of file ShapeData.cs.
    {
        _points.Add(new Point16(x, y));
    }
References Terraria.WorldBuilding.ShapeData._points, and System.Collections.Generic.HashSet< T >.Add().
Referenced by Terraria.WorldBuilding.GenShape.UnitApply(), and Terraria.WorldBuilding.GenAction.UnitApply().