Terraria: System.Threading.TimerQueue.EnsureTimerFiresBy
EnsureTimerFiresBy()
bool System.Threading.TimerQueue.EnsureTimerFiresBy (uint requestedDuration) inline private
Definition at line 141 of file TimerQueue.cs.
    {
        uint num = Math.Min(requestedDuration, 268435455u);
        if (_isTimerScheduled)
        {
            long num2 = TickCount64 - _currentTimerStartTicks;
            if (num2 >= _currentTimerDuration)
            {
                return true;
            }
            uint num3 = _currentTimerDuration - (uint)(int)num2;
            if (num >= num3)
            {
                return true;
            }
        }
        if (SetTimer(num))
        {
            _isTimerScheduled = true;
            _currentTimerStartTicks = TickCount64;
            _currentTimerDuration = num;
            return true;
        }
        return false;
    }
References System.Threading.TimerQueue._currentTimerDuration, System.Threading.TimerQueue._currentTimerStartTicks, System.Threading.TimerQueue._isTimerScheduled, System.Math.Min(), System.Threading.TimerQueue.SetTimer(), and System.Threading.TimerQueue.TickCount64.
Referenced by System.Threading.TimerQueue.FireNextTimers(), and System.Threading.TimerQueue.UpdateTimer().