Terraria: System.Threading.TimerQueue.SetTimer
SetTimer()
bool System.Threading.TimerQueue.SetTimer (uint actualDuration) inline private
Definition at line 95 of file TimerQueue.cs.
    {
        if (m_appDomainTimer == null || m_appDomainTimer.IsInvalid)
        {
            m_appDomainTimer = CreateAppDomainTimer(actualDuration, _id);
            return !m_appDomainTimer.IsInvalid;
        }
        return ChangeAppDomainTimer(m_appDomainTimer, actualDuration);
    }
References System.Threading.TimerQueue._id, System.Threading.TimerQueue.ChangeAppDomainTimer(), System.Threading.TimerQueue.CreateAppDomainTimer(), Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, and System.Threading.TimerQueue.m_appDomainTimer.
Referenced by System.Threading.TimerQueue.EnsureTimerFiresBy().