Terraria: System.Threading.TimerQueue.DeleteTimer
DeleteTimer()
void System.Threading.TimerQueue.DeleteTimer (TimerQueueTimer timer) inline
Definition at line 320 of file TimerQueue.cs.
    {
        if (timer._dueTime != uint.MaxValue)
        {
            long activeCount = ActiveCount - 1;
            ActiveCount = activeCount;
            UnlinkTimer(timer);
            timer._prev = null;
            timer._next = null;
            timer._dueTime = uint.MaxValue;
            timer._period = uint.MaxValue;
            timer._startTicks = 0L;
            timer._short = false;
        }
    }
References System.Threading.TimerQueue.ActiveCount, System.L, and System.Threading.TimerQueue.UnlinkTimer().
Referenced by System.Threading.TimerQueueTimer.Change(), System.Threading.TimerQueueTimer.Close(), System.Threading.TimerQueueTimer.Close(), System.Threading.TimerQueueTimer.CloseAsync(), and System.Threading.TimerQueue.FireNextTimers().