Terraria: System.Threading.TimerQueue.FireNextTimers
FireNextTimers()
void System.Threading.TimerQueue.FireNextTimers () inline private
Definition at line 167 of file TimerQueue.cs.
    {
        TimerQueueTimer timerQueueTimer = null;
        lock (this)
        {
            _isTimerScheduled = false;
            bool flag = false;
            uint num = uint.MaxValue;
            long tickCount = TickCount64;
            TimerQueueTimer timerQueueTimer2 = _shortTimers;
            for (int i = 0; i < 2; i++)
            {
                while (timerQueueTimer2 != null)
                {
                    TimerQueueTimer next = timerQueueTimer2._next;
                    long num2 = tickCount - timerQueueTimer2._startTicks;
                    long num3 = timerQueueTimer2._dueTime - num2;
                    if (num3 <= 0)
                    {
                        timerQueueTimer2._everQueued = true;
                        if (timerQueueTimer2._period != uint.MaxValue)
{
                            timerQueueTimer2._startTicks = tickCount;
                            long num4 = num2 - timerQueueTimer2._dueTime;
                            timerQueueTimer2._dueTime = ((num4 >= timerQueueTimer2._period) ? 1u : (timerQueueTimer2._period - (uint)(int)num4));
                            if (timerQueueTimer2._dueTime < num)
{
                                flag = true;
                                num = timerQueueTimer2._dueTime;
                            }
                            bool flag2 = tickCount + timerQueueTimer2._dueTime - _currentAbsoluteThreshold <= 0;
                            if (timerQueueTimer2._short != flag2)
{
                                MoveTimerToCorrectList(timerQueueTimer2, flag2);
                            }
                        }
                        else
{
                            DeleteTimer(timerQueueTimer2);
                        }
                        if (timerQueueTimer == null)
{
                            timerQueueTimer = timerQueueTimer2;
                        }
                        else
{
                            ThreadPool.UnsafeQueueUserWorkItemInternal(timerQueueTimer2, preferLocal: false);
                        }
                    }
                    else
                    {
                        if (num3 < num)
{
                            flag = true;
                            num = (uint)num3;
                        }
                        if (!timerQueueTimer2._short && num3 <= 333)
{
                            MoveTimerToCorrectList(timerQueueTimer2, shortList: true);
                        }
                    }
                    timerQueueTimer2 = next;
                }
                if (i != 0)
                {
                    continue;
                }
                long num5 = _currentAbsoluteThreshold - tickCount;
                if (num5 > 0)
                {
                    if (_shortTimers == null && _longTimers != null)
                    {
                        num = (uint)((int)num5 + 1);
                        flag = true;
                    }
                    break;
                }
                timerQueueTimer2 = _longTimers;
                _currentAbsoluteThreshold = tickCount + 333;
            }
            if (flag)
            {
                EnsureTimerFiresBy(num);
            }
        }
        timerQueueTimer?.Fire();
    }
References System.Threading.TimerQueue._currentAbsoluteThreshold, System.Threading.TimerQueue._isTimerScheduled, System.Threading.TimerQueue._longTimers, System.Threading.TimerQueue._shortTimers, System.Threading.TimerQueue.DeleteTimer(), System.Threading.TimerQueue.EnsureTimerFiresBy(), System.Threading.TimerQueue.MoveTimerToCorrectList(), System.Threading.TimerQueue.TickCount64, and System.Threading.ThreadPool.UnsafeQueueUserWorkItemInternal().