Terraria: System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.FieldLayoutTableReader
FieldLayoutTableReader()
System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.FieldLayoutTableReader (int numberOfRows, bool declaredSorted, int fieldTableRowRefSize, MemoryBlock containingBlock, int containingBlockOffset) inline package
Definition at line 19 of file FieldLayoutTableReader.cs.
    {
        NumberOfRows = numberOfRows;
        _IsFieldTableRowRefSizeSmall = fieldTableRowRefSize == 2;
        _OffsetOffset = 0;
        _FieldOffset = _OffsetOffset + 4;
        RowSize = _FieldOffset + fieldTableRowRefSize;
        Block = containingBlock.GetMemoryBlockAt(containingBlockOffset, RowSize * numberOfRows);
        if (!declaredSorted && !CheckSorted())
        {
            Throw.TableNotSorted(TableIndex.FieldLayout);
        }
    }
References System.Reflection.Metadata.Ecma335.FieldLayoutTableReader._FieldOffset, System.Reflection.Metadata.Ecma335.FieldLayoutTableReader._IsFieldTableRowRefSizeSmall, System.Reflection.Metadata.Ecma335.FieldLayoutTableReader._OffsetOffset, System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.Block, System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.CheckSorted(), System.Reflection.Internal.MemoryBlock.GetMemoryBlockAt(), System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.NumberOfRows, System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.RowSize, and System.Reflection.Throw.TableNotSorted().