Terraria: System.MulticastDelegate.GetMethodImpl
GetMethodImpl()
override MethodInfo System.MulticastDelegate.GetMethodImpl () inline protected virtual
Reimplemented from System.Delegate.
Definition at line 455 of file MulticastDelegate.cs.
    {
        if (_invocationCount != (IntPtr)0 && _invocationList != null)
        {
            if (_invocationList is object[] array)
            {
                int num = (int)_invocationCount - 1;
                return ((Delegate)array[num]).Method;
            }
            if (_invocationList is MulticastDelegate multicastDelegate)
            {
                return multicastDelegate.GetMethodImpl();
            }
        }
        else if (IsUnmanagedFunctionPtr())
        {
            if (_methodBase == null || !(_methodBase is MethodInfo))
            {
                IRuntimeMethodInfo runtimeMethodInfo = FindMethodHandle();
                RuntimeType runtimeType = RuntimeMethodHandle.GetDeclaringType(runtimeMethodInfo);
                if (RuntimeTypeHandle.IsGenericTypeDefinition(runtimeType) || RuntimeTypeHandle.HasInstantiation(runtimeType))
                {
                    RuntimeType runtimeType2 = (RuntimeType)GetType();
                    runtimeType = runtimeType2;
                }
                _methodBase = (MethodInfo)RuntimeType.GetMethodBase(runtimeType, runtimeMethodInfo);
            }
            return (MethodInfo)_methodBase;
        }
        return base.GetMethodImpl();
    }
References System.MulticastDelegate._invocationCount, System.MulticastDelegate._invocationList, System.Delegate._methodBase, System.array, System.Runtime.Serialization.Dictionary, System.Delegate.FindMethodHandle(), System.RuntimeMethodHandle.GetDeclaringType(), System.RuntimeType.GetMethodBase(), System.RuntimeTypeHandle.HasInstantiation(), System.RuntimeTypeHandle.IsGenericTypeDefinition(), System.MulticastDelegate.IsUnmanagedFunctionPtr(), and System.Delegate.Method.