Terraria: System.MulticastDelegate.NewMulticastDelegate
NewMulticastDelegate() [2/2]
MulticastDelegate System.MulticastDelegate.NewMulticastDelegate (object[] invocationList, int invocationCount, bool thisIsMultiCastAlready) inline private
Definition at line 144 of file MulticastDelegate.cs.
    {
        MulticastDelegate multicastDelegate = Delegate.InternalAllocLike(this);
        if (thisIsMultiCastAlready)
        {
            multicastDelegate._methodPtr = _methodPtr;
            multicastDelegate._methodPtrAux = _methodPtrAux;
        }
        else
        {
            multicastDelegate._methodPtr = GetMulticastInvoke();
            multicastDelegate._methodPtrAux = GetInvokeMethod();
        }
        multicastDelegate._target = multicastDelegate;
        multicastDelegate._invocationList = invocationList;
        multicastDelegate._invocationCount = (IntPtr)invocationCount;
        return multicastDelegate;
    }
References System.Delegate._methodPtr, System.Delegate._methodPtrAux, System.Runtime.Serialization.Dictionary, System.Delegate.GetInvokeMethod(), System.Delegate.GetMulticastInvoke(), and System.Delegate.InternalAllocLike().
Referenced by System.MulticastDelegate.CombineImpl(), System.MulticastDelegate.NewMulticastDelegate(), and System.MulticastDelegate.RemoveImpl().