Terraria: System.MulticastDelegate.Equals
Equals()
override bool System.MulticastDelegate.Equals ([NotNullWhen(true)] object? obj) inline sealed
Definition at line 51 of file MulticastDelegate.cs.
    {
        if (obj == null)
        {
            return false;
        }
        if (this == obj)
        {
            return true;
        }
        if (!Delegate.InternalEqualTypes(this, obj))
        {
            return false;
        }
        MulticastDelegate multicastDelegate = Unsafe.As<MulticastDelegate>(obj);
        if (_invocationCount != (IntPtr)0)
        {
            if (InvocationListLogicallyNull())
            {
                if (IsUnmanagedFunctionPtr())
                {
                    if (!multicastDelegate.IsUnmanagedFunctionPtr())
                    {
                        return false;
                    }
                    return Delegate.CompareUnmanagedFunctionPtrs(this, multicastDelegate);
                }
                if (multicastDelegate._invocationList is Delegate)
                {
                    return Equals(multicastDelegate._invocationList);
                }
                return base.Equals(obj);
            }
            if (_invocationList is Delegate @delegate)
            {
                return @delegate.Equals(obj);
            }
            return InvocationListEquals(multicastDelegate);
        }
        if (!InvocationListLogicallyNull())
        {
            if (!_invocationList.Equals(multicastDelegate._invocationList))
            {
                return false;
            }
            return base.Equals((object?)multicastDelegate);
        }
        if (multicastDelegate._invocationList is Delegate)
        {
            return Equals(multicastDelegate._invocationList);
        }
        return base.Equals((object?)multicastDelegate);
    }
References System.MulticastDelegate._invocationCount, System.MulticastDelegate._invocationList, System.Delegate.CompareUnmanagedFunctionPtrs(), System.Runtime.Serialization.Dictionary, System.MulticastDelegate.Equals(), System.Delegate.InternalEqualTypes(), System.MulticastDelegate.InvocationListEquals(), System.MulticastDelegate.InvocationListLogicallyNull(), System.MulticastDelegate.IsUnmanagedFunctionPtr(), and System.obj.
Referenced by System.MulticastDelegate.EqualInvocationLists(), System.MulticastDelegate.Equals(), and System.MulticastDelegate.RemoveImpl().