Terraria: System.MulticastDelegate.CombineImpl
CombineImpl()
override Delegate System.MulticastDelegate.CombineImpl (Delegate? follow) inline sealed protected virtual
Reimplemented from System.Delegate.
Definition at line 181 of file MulticastDelegate.cs.
    {
        if ((object)follow == null)
        {
            return this;
        }
        if (!Delegate.InternalEqualTypes(this, follow))
        {
            throw new ArgumentException(SR.Arg_DlgtTypeMis);
        }
        MulticastDelegate multicastDelegate = (MulticastDelegate)follow;
        int num = 1;
        object[] array = multicastDelegate._invocationList as object[];
        if (array != null)
        {
            num = (int)multicastDelegate._invocationCount;
        }
        int num2;
        object[] array3;
        if (!(_invocationList is object[] array2))
        {
            num2 = 1 + num;
            array3 = new object[num2];
            array3[0] = this;
            if (array == null)
            {
                array3[1] = multicastDelegate;
            }
            else
            {
                for (int i = 0; i < num; i++)
                {
                    array3[1 + i] = array[i];
                }
            }
            return NewMulticastDelegate(array3, num2);
        }
        int num3 = (int)_invocationCount;
        num2 = num3 + num;
        array3 = null;
        if (num2 <= array2.Length)
        {
            array3 = array2;
            if (array == null)
            {
                if (!TrySetSlot(array3, num3, multicastDelegate))
                {
                    array3 = null;
                }
            }
            else
            {
                for (int j = 0; j < num; j++)
                {
                    if (!TrySetSlot(array3, num3 + j, array[j]))
                    {
                        array3 = null;
                        break;
                    }
                }
            }
        }
        if (array3 == null)
        {
            int num4;
            for (num4 = array2.Length; num4 < num2; num4 *= 2)
            {
            }
            array3 = new object[num4];
            for (int k = 0; k < num3; k++)
            {
                array3[k] = array2[k];
            }
            if (array == null)
            {
                array3[num3] = multicastDelegate;
            }
            else
            {
                for (int l = 0; l < num; l++)
                {
                    array3[num3 + l] = array[l];
                }
            }
        }
        return NewMulticastDelegate(array3, num2, thisIsMultiCastAlready: true);
    }
References System.MulticastDelegate.MulticastDelegate(), System.MulticastDelegate._invocationCount, System.MulticastDelegate._invocationList, System.SR.Arg_DlgtTypeMis, System.array, System.Runtime.Serialization.Dictionary, System.Delegate.InternalEqualTypes(), System.MulticastDelegate.NewMulticastDelegate(), and System.MulticastDelegate.TrySetSlot().