Terraria: System.MulticastDelegate.RemoveImpl
RemoveImpl()
override? Delegate System.MulticastDelegate.RemoveImpl (Delegate value) inline sealed protected virtual
Reimplemented from System.Delegate.
Definition at line 301 of file MulticastDelegate.cs.
    {
        if (!(value is MulticastDelegate multicastDelegate))
        {
            return this;
        }
        if (!(multicastDelegate._invocationList is object[]))
        {
            if (!(_invocationList is object[] array))
            {
                if (Equals(value))
                {
                    return null;
                }
            }
            else
            {
                int num = (int)_invocationCount;
                int num2 = num;
                while (--num2 >= 0)
                {
                    if (value.Equals(array[num2]))
                    {
                        if (num == 2)
{
                            return (Delegate)array[1 - num2];
                        }
                        object[] invocationList = DeleteFromInvocationList(array, num, num2, 1);
                        return NewMulticastDelegate(invocationList, num - 1, thisIsMultiCastAlready: true);
                    }
                }
            }
        }
        else if (_invocationList is object[] array2)
        {
            int num3 = (int)_invocationCount;
            int num4 = (int)multicastDelegate._invocationCount;
            for (int num5 = num3 - num4; num5 >= 0; num5--)
            {
                if (EqualInvocationLists(array2, multicastDelegate._invocationList as object[], num5, num4))
                {
                    if (num3 - num4 == 0)
                    {
                        return null;
                    }
                    if (num3 - num4 == 1)
                    {
                        return (Delegate)array2[(num5 == 0) ? (num3 - 1) : 0];
                    }
                    object[] invocationList2 = DeleteFromInvocationList(array2, num3, num5, num4);
                    return NewMulticastDelegate(invocationList2, num3 - num4, thisIsMultiCastAlready: true);
                }
            }
        }
        return this;
    }
References System.MulticastDelegate._invocationCount, System.MulticastDelegate._invocationList, System.array, System.MulticastDelegate.DeleteFromInvocationList(), System.Runtime.Serialization.Dictionary, System.MulticastDelegate.EqualInvocationLists(), System.MulticastDelegate.Equals(), System.MulticastDelegate.NewMulticastDelegate(), and System.value.