Terraria: System.MulticastDelegate.StoreDynamicMethod
StoreDynamicMethod()
void System.MulticastDelegate.StoreDynamicMethod (MethodInfo dynamicMethod) inline package
Definition at line 168 of file MulticastDelegate.cs.
    {
        if (_invocationCount != (IntPtr)0)
        {
            MulticastDelegate multicastDelegate = (MulticastDelegate)_invocationList;
            multicastDelegate._methodBase = dynamicMethod;
        }
        else
        {
            _methodBase = dynamicMethod;
        }
    }
References System.MulticastDelegate.MulticastDelegate(), System.MulticastDelegate._invocationCount, System.MulticastDelegate._invocationList, System.Delegate._methodBase, and System.Runtime.Serialization.Dictionary.
Referenced by System.Reflection.Emit.DynamicMethod.CreateDelegate(), and System.Reflection.Emit.DynamicMethod.CreateDelegate().