Terraria: Microsoft.Xna.Framework.Graphics.RenderTargetHelper.CreateSurfaces
CreateSurfaces()
unsafe void Microsoft.Xna.Framework.Graphics.RenderTargetHelper.CreateSurfaces (GraphicsDevice graphicsDevice) inline package
Definition at line 77 of file RenderTargetHelper.cs.
    {
        if (multiSampleCount != 0)
        {
            fixed (IDirect3DSurface9** ptr = &pRenderTargetSurface)
            {
                try
                {
                    int num = *(int*)graphicsDevice.pComPtr + 112;
                    int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, _D3DFORMAT, _D3DMULTISAMPLE_TYPE, uint, int, IDirect3DSurface9**, void**, int>)(int)(*(uint*)num))((nint)graphicsDevice.pComPtr, (uint)width, (uint)height, _003CModule_003E.ConvertXnaFormatToWindows(format), (_D3DMULTISAMPLE_TYPE)multiSampleCount, 0u, 0, ptr, null);
                    if (num2 < 0)
                    {
                        throw GraphicsHelpers.GetExceptionFromResult((uint)num2);
                    }
                }
                catch
                {
                    //try-fault
                    ptr = null;
                    throw;
                }
            }
        }
        if (depthFormat != 0)
        {
            IntPtr intPtr = IntPtr.Zero;
            if (usage == RenderTargetUsage.DiscardContents)
            {
                intPtr = graphicsDevice.Resources.FindResourceW(GetSharedDepthSurface);
            }
            if (intPtr != IntPtr.Zero)
            {
                pDepthSurface = (IDirect3DSurface9*)intPtr.ToPointer();
            }
            else
            {
                fixed (IDirect3DSurface9** ptr2 = &pDepthSurface)
                {
                    try
                    {
                        int num3 = *(int*)graphicsDevice.pComPtr + 116;
                        int num4 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, _D3DFORMAT, _D3DMULTISAMPLE_TYPE, uint, int, IDirect3DSurface9**, void**, int>)(int)(*(uint*)num3))((nint)graphicsDevice.pComPtr, (uint)width, (uint)height, _003CModule_003E.ConvertXnaFormatToWindows(depthFormat), (_D3DMULTISAMPLE_TYPE)multiSampleCount, 0u, 0, ptr2, null);
                        if (num4 < 0)
{
                            throw GraphicsHelpers.GetExceptionFromResult((uint)num4);
                        }
                    }
                    catch
                    {
                        //try-fault
                        ptr2 = null;
                        throw;
                    }
                }
            }
        }
        try
        {
            return;
        }
        catch
        {
            //try-fault
            throw;
        }
    }
References Microsoft.Xna.Framework.Graphics.RenderTargetHelper.depthFormat, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.FindResourceW(), Microsoft.Xna.Framework.Graphics.RenderTargetHelper.format, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.RenderTargetHelper.GetSharedDepthSurface(), Microsoft.Xna.Framework.Graphics.RenderTargetHelper.height, Microsoft.Xna.Framework.Graphics.RenderTargetHelper.multiSampleCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.RenderTargetHelper.pDepthSurface, Microsoft.Xna.Framework.Graphics.RenderTargetHelper.pRenderTargetSurface, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources, System.IntPtr.ToPointer(), Microsoft.Xna.Framework.Graphics.RenderTargetHelper.usage, Microsoft.Xna.Framework.Graphics.RenderTargetHelper.width, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.RenderTarget2D.RecreateAndPopulateObject(), and Microsoft.Xna.Framework.Graphics.RenderTargetCube.RecreateAndPopulateObject().