Terraria: System.MulticastDelegate.TrySetSlot
TrySetSlot()
static bool System.MulticastDelegate.TrySetSlot (object[] a, int index, object o) inline static private
Definition at line 125 of file MulticastDelegate.cs.
    {
        if (a[index] == null && Interlocked.CompareExchange<object>(ref a[index], o, (object)null) == null)
        {
            return true;
        }
        object obj = a[index];
        if (obj != null)
        {
            MulticastDelegate multicastDelegate = (MulticastDelegate)o;
            MulticastDelegate multicastDelegate2 = (MulticastDelegate)obj;
            if (multicastDelegate2._methodPtr == multicastDelegate._methodPtr && multicastDelegate2._target == multicastDelegate._target && multicastDelegate2._methodPtrAux == multicastDelegate._methodPtrAux)
            {
                return true;
            }
        }
        return false;
    }
References System.MulticastDelegate.MulticastDelegate(), System.Threading.Interlocked.CompareExchange(), System.Runtime.Serialization.Dictionary, System.index, and System.obj.
Referenced by System.MulticastDelegate.CombineImpl().