Terraria: System.MulticastDelegate.GetTarget
GetTarget()
override object System.MulticastDelegate.GetTarget () inline package virtual
Reimplemented from System.Delegate.
Definition at line 434 of file MulticastDelegate.cs.
    {
        if (_invocationCount != (IntPtr)0)
        {
            if (InvocationListLogicallyNull())
            {
                return null;
            }
            if (_invocationList is object[] array)
            {
                int num = (int)_invocationCount;
                return ((Delegate)array[num - 1]).GetTarget();
            }
            if (_invocationList is Delegate @delegate)
            {
                return @delegate.GetTarget();
            }
        }
        return base.GetTarget();
    }
References System.MulticastDelegate._invocationCount, System.MulticastDelegate._invocationList, System.array, System.Runtime.Serialization.Dictionary, System.MulticastDelegate.GetTarget(), and System.MulticastDelegate.InvocationListLogicallyNull().
Referenced by System.MulticastDelegate.GetTarget().