Terraria: System.Text.Encoding.EncodingByteBuffer.GetNextChar
GetNextChar()
unsafe char System.Text.Encoding.EncodingByteBuffer.GetNextChar () inline package
Definition at line 321 of file Encoding.cs.
        {
            char c = fallbackBuffer.InternalGetNextChar();
            if (c == '\0' && _chars < _charEnd)
            {
                c = *(_chars++);
            }
            return c;
        }
References System.Text.Encoding.EncodingByteBuffer._charEnd, System.Text.Encoding.EncodingByteBuffer._chars, System.Text.Encoding.EncodingByteBuffer.fallbackBuffer, and System.Text.EncoderFallbackBuffer.InternalGetNextChar().
Referenced by System.Text.UTF7Encoding.GetBytes(), System.Text.GB18030Encoding.GetBytes(), System.Text.ISO2022Encoding.GetBytesCP50225KR(), System.Text.ISO2022Encoding.GetBytesCP5022xJP(), and System.Text.ISO2022Encoding.GetBytesCP52936().