Terraria: System.Text.Encoding.EncodingByteBuffer.EncodingByteBuffer
EncodingByteBuffer()
unsafe System.Text.Encoding.EncodingByteBuffer.EncodingByteBuffer (Encoding inEncoding, EncoderNLS inEncoder, byte * inByteStart, int inByteCount, char * inCharStart, int inCharCount) inline package
Definition at line 246 of file Encoding.cs.
        {
            _enc = inEncoding;
            _encoder = inEncoder;
            _charStart = inCharStart;
            _chars = inCharStart;
            _charEnd = inCharStart + inCharCount;
            _bytes = inByteStart;
            _byteStart = inByteStart;
            _byteEnd = inByteStart + inByteCount;
            if (_encoder == null)
            {
                fallbackBuffer = _enc.EncoderFallback.CreateFallbackBuffer();
            }
            else
            {
                fallbackBuffer = _encoder.FallbackBuffer;
                if (_encoder._throwOnOverflow && _encoder.InternalHasFallbackBuffer && fallbackBuffer.Remaining > 0)
                {
                    throw new ArgumentException(SR.Format(SR.Argument_EncoderFallbackNotEmpty, _encoder.Encoding.EncodingName, _encoder.Fallback.GetType()));
                }
            }
            fallbackBuffer.InternalInitialize(_chars, _charEnd, _encoder, _bytes != null);
        }
References System.Text.Encoding.EncodingByteBuffer._byteEnd, System.Text.Encoding.EncodingByteBuffer._bytes, System.Text.Encoding.EncodingByteBuffer._byteStart, System.Text.Encoding.EncodingByteBuffer._charEnd, System.Text.Encoding.EncodingByteBuffer._chars, System.Text.Encoding.EncodingByteBuffer._charStart, System.Text.Encoding.EncodingByteBuffer._enc, System.Text.Encoding.EncodingByteBuffer._encoder, System.Text.EncoderNLS._throwOnOverflow, System.SR.Argument_EncoderFallbackNotEmpty, System.Text.EncoderFallback.CreateFallbackBuffer(), System.Runtime.Serialization.Dictionary, System.Text.Encoding.EncoderFallback, System.Text.EncoderNLS.Encoding, System.Text.Encoding.EncodingName, System.Text.EncoderNLS.Fallback, System.Text.Encoding.EncodingByteBuffer.fallbackBuffer, System.Text.EncoderNLS.FallbackBuffer, System.SR.Format(), System.Text.EncoderNLS.InternalHasFallbackBuffer, System.Text.EncoderFallbackBuffer.InternalInitialize(), and System.Text.EncoderFallbackBuffer.Remaining.