Terraria: System.Text.Encoding.EncodingByteBuffer.MovePrevious
MovePrevious()
unsafe void System.Text.Encoding.EncodingByteBuffer.MovePrevious (bool bThrow) inline package
Definition at line 305 of file Encoding.cs.
        {
            if (fallbackBuffer.bFallingBack)
            {
                fallbackBuffer.MovePrevious();
            }
            else if (_chars > _charStart)
            {
                _chars--;
            }
            if (bThrow)
            {
                _enc.ThrowBytesOverflow(_encoder, _bytes == _byteStart);
            }
        }
References System.Text.Encoding.EncodingByteBuffer._bytes, System.Text.Encoding.EncodingByteBuffer._byteStart, System.Text.Encoding.EncodingByteBuffer._chars, System.Text.Encoding.EncodingByteBuffer._charStart, System.Text.Encoding.EncodingByteBuffer._enc, System.Text.Encoding.EncodingByteBuffer._encoder, System.Text.EncoderFallbackBuffer.bFallingBack, System.Text.Encoding.EncodingByteBuffer.fallbackBuffer, System.Text.EncoderFallbackBuffer.MovePrevious(), and System.Text.Encoding.ThrowBytesOverflow().
Referenced by System.Text.Encoding.EncodingByteBuffer.AddByte(), and System.Text.GB18030Encoding.GetBytes().