Terraria: System.Text.Encoding.EncodingByteBuffer.AddByte
AddByte() [1/4]
unsafe bool System.Text.Encoding.EncodingByteBuffer.AddByte (byte b, int moreBytesExpected) inline package
Definition at line 271 of file Encoding.cs.
        {
            if (_bytes != null)
            {
                if (_bytes >= _byteEnd - moreBytesExpected)
                {
                    MovePrevious(bThrow: true);
                    return false;
                }
                *(_bytes++) = b;
            }
            _byteCountResult++;
            return true;
        }
References System.Text.Encoding.EncodingByteBuffer._byteCountResult, System.Text.Encoding.EncodingByteBuffer._byteEnd, System.Text.Encoding.EncodingByteBuffer._bytes, and System.Text.Encoding.EncodingByteBuffer.MovePrevious().
Referenced by System.Text.Encoding.EncodingByteBuffer.AddByte(), System.Text.Encoding.EncodingByteBuffer.AddByte(), System.Text.Encoding.EncodingByteBuffer.AddByte(), System.Text.UTF7Encoding.GetBytes(), System.Text.GB18030Encoding.GetBytes(), System.Text.ISO2022Encoding.GetBytesCP50225KR(), System.Text.ISO2022Encoding.GetBytesCP5022xJP(), and System.Text.ISO2022Encoding.GetBytesCP52936().