Terraria: System.Diagnostics.Tracing.TraceLoggingEventTypes.TraceLoggingEventTypes
TraceLoggingEventTypes() [3/4]
System.Diagnostics.Tracing.TraceLoggingEventTypes.TraceLoggingEventTypes (string name, EventTags tags, ParameterInfo[] paramInfos) inline package
Definition at line 49 of file TraceLoggingEventTypes.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        typeInfos = MakeArray(paramInfos);
        paramNames = MakeParamNameArray(paramInfos);
        this.name = name;
        this.tags = tags;
        level = 5;
        TraceLoggingMetadataCollector traceLoggingMetadataCollector = new TraceLoggingMetadataCollector();
        for (int i = 0; i < typeInfos.Length; i++)
        {
            TraceLoggingTypeInfo traceLoggingTypeInfo = typeInfos[i];
            level = Statics.Combine((int)traceLoggingTypeInfo.Level, level);
            opcode = Statics.Combine((int)traceLoggingTypeInfo.Opcode, opcode);
            keywords |= traceLoggingTypeInfo.Keywords;
            string fieldName = paramInfos[i].Name;
            if (Statics.ShouldOverrideFieldName(fieldName))
            {
                fieldName = traceLoggingTypeInfo.Name;
            }
            traceLoggingTypeInfo.WriteMetadata(traceLoggingMetadataCollector, fieldName, EventFieldFormat.Default);
        }
        typeMetadata = traceLoggingMetadataCollector.GetMetadata();
        scratchSize = traceLoggingMetadataCollector.ScratchSize;
        dataCount = traceLoggingMetadataCollector.DataCount;
        pinCount = traceLoggingMetadataCollector.PinCount;
    }
References System.Diagnostics.Tracing.Statics.Combine(), System.Diagnostics.Tracing.TraceLoggingEventTypes.dataCount, System.Diagnostics.Tracing.TraceLoggingEventTypes.keywords, System.Diagnostics.Tracing.TraceLoggingEventTypes.level, System.Diagnostics.Tracing.TraceLoggingEventTypes.MakeArray(), System.Diagnostics.Tracing.TraceLoggingEventTypes.MakeParamNameArray(), System.Diagnostics.Tracing.TraceLoggingEventTypes.name, System.Diagnostics.Tracing.TraceLoggingEventTypes.opcode, System.Diagnostics.Tracing.TraceLoggingEventTypes.paramNames, System.Diagnostics.Tracing.TraceLoggingEventTypes.pinCount, System.Diagnostics.Tracing.TraceLoggingEventTypes.scratchSize, System.Diagnostics.Tracing.Statics.ShouldOverrideFieldName(), System.Diagnostics.Tracing.TraceLoggingEventTypes.tags, System.Diagnostics.Tracing.TraceLoggingEventTypes.typeInfos, and System.Diagnostics.Tracing.TraceLoggingEventTypes.typeMetadata.