Terraria: System.Net.Http.AuthenticationHelper.GetDigestTokenForCredential
GetDigestTokenForCredential()
static async Task< string > System.Net.Http.AuthenticationHelper.GetDigestTokenForCredential (NetworkCredential credential, HttpRequestMessage request, DigestResponse digestResponse) inline static
Definition at line 471 of file AuthenticationHelper.cs.
    {
        StringBuilder sb = System.Text.StringBuilderCache.Acquire();
        string algorithm;
        bool isAlgorithmSpecified = digestResponse.Parameters.TryGetValue("algorithm", out algorithm);
        if (isAlgorithmSpecified)
        {
            if (!algorithm.Equals("SHA-256", StringComparison.OrdinalIgnoreCase) && !algorithm.Equals("MD5", StringComparison.OrdinalIgnoreCase) && !algorithm.Equals("SHA-256-sess", StringComparison.OrdinalIgnoreCase) && !algorithm.Equals("MD5-sess", StringComparison.OrdinalIgnoreCase))
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(digestResponse, $"Algorithm not supported: {algorithm}", "GetDigestTokenForCredential");
                }
                return null;
            }
        }
        else
        {
            algorithm = "MD5";
        }
        if (!digestResponse.Parameters.TryGetValue("nonce", out var nonce))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(digestResponse, "Nonce missing", "GetDigestTokenForCredential");
            }
            return null;
        }
        digestResponse.Parameters.TryGetValue("opaque", out var opaque);
        if (!digestResponse.Parameters.TryGetValue("realm", out var value))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(digestResponse, "Realm missing", "GetDigestTokenForCredential");
            }
            return null;
        }
        if (digestResponse.Parameters.TryGetValue("userhash", out var value2) && value2 == "true")
        {
            sb.AppendKeyValue("username", ComputeHash(credential.UserName + ":" + value, algorithm));
            sb.AppendKeyValue("userhash", value2, includeQuotes: false);
        }
        else if (HeaderUtilities.ContainsNonAscii(credential.UserName))
        {
            string value3 = HeaderUtilities.Encode5987(credential.UserName);
            sb.AppendKeyValue("username*", value3, includeQuotes: false);
        }
        else
        {
            sb.AppendKeyValue("username", credential.UserName);
        }
        sb.AppendKeyValue("realm", value);
        sb.AppendKeyValue("nonce", nonce);
        sb.AppendKeyValue("uri", request.RequestUri.PathAndQuery);
        string qop = "auth";
        bool isQopSpecified = digestResponse.Parameters.ContainsKey("qop");
        if (isQopSpecified)
        {
            int num = digestResponse.Parameters["qop"].IndexOf("auth-int", StringComparison.Ordinal);
            if (num != -1)
            {
                int num2 = digestResponse.Parameters["qop"].IndexOf("auth", StringComparison.Ordinal);
                if (num2 == num)
                {
                    num2 = digestResponse.Parameters["qop"].IndexOf("auth", num + "auth-int".Length, StringComparison.Ordinal);
                    if (num2 == -1)
                    {
                        qop = "auth-int";
                    }
                }
            }
        }
        string cnonce = GetRandomAlphaNumericString();
        string a1 = credential.UserName + ":" + value + ":" + credential.Password;
        if (algorithm.EndsWith("sess", StringComparison.OrdinalIgnoreCase))
        {
            a1 = ComputeHash(a1, algorithm) + ":" + nonce + ":" + cnonce;
        }
        string a2 = request.Method.Method + ":" + request.RequestUri.PathAndQuery;
        if (qop == "auth-int")
        {
            string text = ((request.Content != null) ? (await request.Content.ReadAsStringAsync().ConfigureAwait(continueOnCapturedContext: false)) : string.Empty);
            string data = text;
            a2 = a2 + ":" + ComputeHash(data, algorithm);
        }
        string value4 = ((!isQopSpecified) ? ComputeHash(ComputeHash(a1, algorithm) + ":" + nonce + ":" + ComputeHash(a2, algorithm), algorithm) : ComputeHash(ComputeHash(a1, algorithm) + ":" + nonce + ":00000001:" + cnonce + ":" + qop + ":" + ComputeHash(a2, algorithm), algorithm));
        sb.AppendKeyValue("response", value4, includeQuotes: true, opaque != null || isAlgorithmSpecified || isQopSpecified);
        if (opaque != null)
        {
            sb.AppendKeyValue("opaque", opaque, includeQuotes: true, isAlgorithmSpecified || isQopSpecified);
        }
        if (isAlgorithmSpecified)
        {
            sb.AppendKeyValue("algorithm", algorithm, includeQuotes: false, isQopSpecified);
        }
        if (isQopSpecified)
        {
            sb.AppendKeyValue("qop", qop, includeQuotes: false);
            sb.AppendKeyValue("nc", "00000001", includeQuotes: false);
            sb.AppendKeyValue("cnonce", cnonce, includeQuotes: true, includeComma: false);
        }
        return System.Text.StringBuilderCache.GetStringAndRelease(sb);
    }
References System.Text.StringBuilderCache.Acquire(), System.Net.Http.AuthenticationHelper.ComputeHash(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Net.Http.Headers.HeaderUtilities.ContainsNonAscii(), System.Net.Http.Headers.HeaderUtilities.Encode5987(), System.Net.NetEventSource.Error(), System.Net.Http.AuthenticationHelper.GetRandomAlphaNumericString(), System.Text.StringBuilderCache.GetStringAndRelease(), System.Net.NetEventSource.Log, System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Net.Http.AuthenticationHelper.TrySetDigestAuthToken().