Terraria: System.Data.Common.SqlDecimalStorage.Aggregate
Aggregate()
override object System.Data.Common.SqlDecimalStorage.Aggregate (int[] records, AggregateType kind) inline virtual
Reimplemented from System.Data.Common.DataStorage.
Definition at line 19 of file SqlDecimalStorage.cs.
    {
        bool flag = false;
        try
        {
            switch (kind)
            {
            case AggregateType.Sum:
            {
                SqlDecimal sqlDecimal2 = 0L;
                foreach (int num3 in records)
                {
                    if (!IsNull(num3))
                    {
                        sqlDecimal2 += _values[num3];
                        flag = true;
                    }
                }
                if (flag)
                {
                    return sqlDecimal2;
                }
                return _nullValue;
            }
            case AggregateType.Mean:
            {
                SqlDecimal sqlDecimal3 = 0L;
                int num5 = 0;
                foreach (int num6 in records)
                {
                    if (!IsNull(num6))
                    {
                        sqlDecimal3 += _values[num6];
                        num5++;
                        flag = true;
                    }
                }
                if (flag)
                {
                    SqlDecimal sqlDecimal4 = 0L;
                    sqlDecimal4 = sqlDecimal3 / num5;
                    return sqlDecimal4;
                }
                return _nullValue;
            }
            case AggregateType.Var:
            case AggregateType.StDev:
            {
                int num = 0;
                SqlDouble sqlDouble = 0.0;
                SqlDouble sqlDouble2 = 0.0;
                SqlDouble sqlDouble3 = 0.0;
                SqlDouble sqlDouble4 = 0.0;
                foreach (int num4 in records)
                {
                    if (!IsNull(num4))
                    {
                        sqlDouble3 += _values[num4].ToSqlDouble();
                        sqlDouble4 += _values[num4].ToSqlDouble() * _values[num4].ToSqlDouble();
                        num++;
                    }
                }
                if (num > 1)
                {
                    sqlDouble = num * sqlDouble4 - sqlDouble3 * sqlDouble3;
                    sqlDouble2 = sqlDouble / (sqlDouble3 * sqlDouble3);
                    if (sqlDouble2 < 1E-15 || sqlDouble < 0.0)
                    {
                        sqlDouble = 0.0;
                    }
                    else
                    {
                        sqlDouble /= (SqlDouble)(num * (num - 1));
                    }
                    if (kind == AggregateType.StDev)
                    {
                        return Math.Sqrt(sqlDouble.Value);
                    }
                    return sqlDouble;
                }
                return _nullValue;
            }
            case AggregateType.Min:
            {
                SqlDecimal sqlDecimal = SqlDecimal.MaxValue;
                foreach (int num2 in records)
                {
                    if (!IsNull(num2))
                    {
                        if (SqlDecimal.LessThan(_values[num2], sqlDecimal).IsTrue)
{
                            sqlDecimal = _values[num2];
                        }
                        flag = true;
                    }
                }
                if (flag)
                {
                    return sqlDecimal;
                }
                return _nullValue;
            }
            case AggregateType.Max:
            {
                SqlDecimal sqlDecimal5 = SqlDecimal.MinValue;
                foreach (int num7 in records)
                {
                    if (!IsNull(num7))
                    {
                        if (SqlDecimal.GreaterThan(_values[num7], sqlDecimal5).IsTrue)
{
                            sqlDecimal5 = _values[num7];
                        }
                        flag = true;
                    }
                }
                if (flag)
                {
                    return sqlDecimal5;
                }
                return _nullValue;
            }
            case AggregateType.First:
                if (records.Length != 0)
                {
                    return _values[records[0]];
                }
                return null;
            case AggregateType.Count:
            {
                int num = 0;
                for (int i = 0; i < records.Length; i++)
                {
                    if (!IsNull(records[i]))
                    {
                        num++;
                    }
                }
                return num;
            }
            }
        }
        catch (OverflowException)
        {
            throw ExprException.Overflow(typeof(SqlDecimal));
        }
        throw ExceptionBuilder.AggregateException(kind, _dataType);
    }
References System.Data.Common.DataStorage._dataType, System.Data.Common.DataStorage._nullValue, System.Data.Common.SqlDecimalStorage._values, System.Data.ExceptionBuilder.AggregateException(), System.Xml.Dictionary, System.E, System.Data.SqlTypes.SqlDecimal.GreaterThan(), System.Data.IsNull, System.L, System.Data.SqlTypes.SqlDecimal.LessThan(), System.Data.SqlTypes.SqlDecimal.MaxValue, System.Data.SqlTypes.SqlDecimal.MinValue, System.Data.ExprException.Overflow(), System.Data.Common.SqlDouble, System.Math.Sqrt(), and System.Data.SqlTypes.SqlDecimal.ToSqlDouble().