Terraria: System.Data.Common.DataStorage.SetNullBit
SetNullBit()
void System.Data.Common.DataStorage.SetNullBit (int recordNo, bool flag) inline protected inherited
Definition at line 194 of file DataStorage.cs.
    {
        _dbNullBits.Set(recordNo, flag);
    }
References System.Data.Common.DataStorage._dbNullBits, System.Xml.Dictionary, and System.Collections.BitArray.Set().
Referenced by System.Data.Common.BigIntegerStorage.Set(), System.Data.Common.BooleanStorage.Set(), System.Data.Common.ByteStorage.Set(), System.Data.Common.CharStorage.Set(), System.Data.Common.DateTimeOffsetStorage.Set(), System.Data.Common.DateTimeStorage.Set(), System.Data.Common.DecimalStorage.Set(), System.Data.Common.DoubleStorage.Set(), System.Data.Common.Int16Storage.Set(), System.Data.Common.Int32Storage.Set(), System.Data.Common.Int64Storage.Set(), System.Data.Common.SByteStorage.Set(), System.Data.Common.SingleStorage.Set(), System.Data.Common.TimeSpanStorage.Set(), System.Data.Common.UInt16Storage.Set(), System.Data.Common.UInt32Storage.Set(), System.Data.Common.UInt64Storage.Set(), and System.Data.Common.SqlUdtStorage.Set().