Terraria: System.Data.Common.DataStorage.IsNull
IsNull()
virtual bool System.Data.Common.DataStorage.IsNull (int recordNo) inline virtual inherited
Reimplemented in System.Data.Common.ObjectStorage, System.Data.Common.SqlBinaryStorage, System.Data.Common.SqlBooleanStorage, System.Data.Common.SqlBytesStorage, System.Data.Common.SqlByteStorage, System.Data.Common.SqlCharsStorage, System.Data.Common.SqlDateTimeStorage, System.Data.Common.SqlDecimalStorage, System.Data.Common.SqlDoubleStorage, System.Data.Common.SqlGuidStorage, System.Data.Common.SqlInt16Storage, System.Data.Common.SqlInt32Storage, System.Data.Common.SqlInt64Storage, System.Data.Common.SqlMoneyStorage, System.Data.Common.SqlSingleStorage, System.Data.Common.SqlStringStorage, System.Data.Common.SqlUdtStorage, and System.Data.Common.StringStorage.
Definition at line 187 of file DataStorage.cs.
    {
        return _dbNullBits.Get(recordNo);
    }
References System.Data.Common.DataStorage._dbNullBits, System.Xml.Dictionary, and System.Collections.BitArray.Get().
Referenced by System.Data.DataColumn.CheckNullable(), and System.Data.DataColumn.IsNull().