Terraria: System.Data.Common.DataStorage.SetNullStorage
SetNullStorage()
void System.Data.Common.DataStorage.SetNullStorage (BitArray nullbits) inline protected inherited
Definition at line 469 of file DataStorage.cs.
    {
        _dbNullBits = nullbits;
    }
References System.Data.Common.DataStorage._dbNullBits, and System.Xml.Dictionary.
Referenced by System.Data.Common.BigIntegerStorage.SetStorage(), System.Data.Common.BooleanStorage.SetStorage(), System.Data.Common.ByteStorage.SetStorage(), System.Data.Common.CharStorage.SetStorage(), System.Data.Common.DateTimeOffsetStorage.SetStorage(), System.Data.Common.DateTimeStorage.SetStorage(), System.Data.Common.DecimalStorage.SetStorage(), System.Data.Common.DoubleStorage.SetStorage(), System.Data.Common.Int16Storage.SetStorage(), System.Data.Common.Int32Storage.SetStorage(), System.Data.Common.Int64Storage.SetStorage(), System.Data.Common.SByteStorage.SetStorage(), System.Data.Common.SingleStorage.SetStorage(), System.Data.Common.TimeSpanStorage.SetStorage(), System.Data.Common.UInt16Storage.SetStorage(), System.Data.Common.UInt32Storage.SetStorage(), and System.Data.Common.UInt64Storage.SetStorage().