Terraria: System.Net.Http.AuthenticationHelper.SetRequestAuthenticationHeaderValue
SetRequestAuthenticationHeaderValue()
static void System.Net.Http.AuthenticationHelper.SetRequestAuthenticationHeaderValue (HttpRequestMessage request, AuthenticationHeaderValue headerValue, bool isProxyAuth) inline static private
Definition at line 315 of file AuthenticationHelper.cs.
    {
        if (isProxyAuth)
        {
            request.Headers.ProxyAuthorization = headerValue;
        }
        else
        {
            request.Headers.Authorization = headerValue;
        }
    }
Referenced by System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(), System.Net.Http.AuthenticationHelper.SetBasicAuthToken(), and System.Net.Http.AuthenticationHelper.TrySetDigestAuthToken().