Terraria: System.Data.Common.DataStorage.CompareBits
CompareBits()
int System.Data.Common.DataStorage.CompareBits (int recordNo1, int recordNo2) inline protected inherited
Definition at line 135 of file DataStorage.cs.
    {
        bool flag = _dbNullBits.Get(recordNo1);
        bool flag2 = _dbNullBits.Get(recordNo2);
        if (flag ^ flag2)
        {
            if (flag)
            {
                return -1;
            }
            return 1;
        }
        return 0;
    }
References System.Data.Common.DataStorage._dbNullBits, System.Xml.Dictionary, and System.Collections.BitArray.Get().
Referenced by System.Data.Common.BigIntegerStorage.Compare(), System.Data.Common.BooleanStorage.Compare(), System.Data.Common.ByteStorage.Compare(), System.Data.Common.CharStorage.Compare(), System.Data.Common.DateTimeOffsetStorage.Compare(), System.Data.Common.DateTimeStorage.Compare(), System.Data.Common.DecimalStorage.Compare(), System.Data.Common.DoubleStorage.Compare(), System.Data.Common.Int16Storage.Compare(), System.Data.Common.Int32Storage.Compare(), System.Data.Common.Int64Storage.Compare(), System.Data.Common.SByteStorage.Compare(), System.Data.Common.SingleStorage.Compare(), System.Data.Common.TimeSpanStorage.Compare(), System.Data.Common.UInt16Storage.Compare(), System.Data.Common.UInt32Storage.Compare(), and System.Data.Common.UInt64Storage.Compare().