Terraria: System.Data.Common.DataStorage.HasValue
HasValue()
bool System.Data.Common.DataStorage.HasValue (int recordNo) inline protected inherited
Definition at line 182 of file DataStorage.cs.
    {
        return !_dbNullBits.Get(recordNo);
    }
References System.Data.Common.DataStorage._dbNullBits, System.Xml.Dictionary, and System.Collections.BitArray.Get().
Referenced by System.Data.Common.DateTimeOffsetStorage.Aggregate(), System.Data.Common.DateTimeStorage.Aggregate(), System.Data.Common.DecimalStorage.Aggregate(), System.Data.Common.Int16Storage.Aggregate(), System.Data.Common.Int32Storage.Aggregate(), System.Data.Common.Int64Storage.Aggregate(), System.Data.Common.UInt16Storage.Aggregate(), System.Data.Common.UInt32Storage.Aggregate(), System.Data.Common.UInt64Storage.Aggregate(), System.Data.Common.BigIntegerStorage.CompareValueTo(), System.Data.Common.DateTimeOffsetStorage.CompareValueTo(), System.Data.Common.DateTimeStorage.CompareValueTo(), System.Data.Common.DecimalStorage.CompareValueTo(), System.Data.Common.Int16Storage.CompareValueTo(), System.Data.Common.Int32Storage.CompareValueTo(), System.Data.Common.Int64Storage.CompareValueTo(), System.Data.Common.UInt16Storage.CompareValueTo(), System.Data.Common.UInt32Storage.CompareValueTo(), System.Data.Common.UInt64Storage.CompareValueTo(), System.Data.Common.BigIntegerStorage.CopyValue(), System.Data.Common.DateTimeOffsetStorage.CopyValue(), System.Data.Common.DateTimeStorage.CopyValue(), System.Data.Common.DecimalStorage.CopyValue(), System.Data.Common.Int16Storage.CopyValue(), System.Data.Common.Int32Storage.CopyValue(), System.Data.Common.Int64Storage.CopyValue(), System.Data.Common.UInt16Storage.CopyValue(), System.Data.Common.UInt32Storage.CopyValue(), System.Data.Common.UInt64Storage.CopyValue(), System.Data.Common.DateTimeOffsetStorage.Get(), System.Data.Common.DateTimeStorage.Get(), System.Data.Common.DecimalStorage.Get(), and System.Data.Common.DateTimeStorage.SetStorage().