Terraria: System.Net.Http.AuthenticationHelper.ComputeHash
ComputeHash()
static string System.Net.Http.AuthenticationHelper.ComputeHash (string data, string algorithm) inline static private
Definition at line 599 of file AuthenticationHelper.cs.
    {
        using HashAlgorithm hashAlgorithm = (algorithm.StartsWith("SHA-256", StringComparison.OrdinalIgnoreCase) ? ((HashAlgorithm)SHA256.Create()) : ((HashAlgorithm)MD5.Create()));
        Span<byte> span = stackalloc byte[hashAlgorithm.HashSize / 8];
        int bytesWritten;
        bool flag = hashAlgorithm.TryComputeHash(Encoding.UTF8.GetBytes(data), span, out bytesWritten);
        return System.HexConverter.ToString(span, System.HexConverter.Casing.Lower);
    }
References System.Security.Cryptography.MD5.Create(), System.Security.Cryptography.SHA256.Create(), System.Security.Cryptography.HashAlgorithm, System.HexConverter.ToString(), and System.Text.Encoding.UTF8.
Referenced by System.Net.Http.AuthenticationHelper.GetDigestTokenForCredential().