Terraria: System.Net.Http.AuthenticationHelper.TryGetValidAuthenticationChallengeForScheme
TryGetValidAuthenticationChallengeForScheme()
static bool System.Net.Http.AuthenticationHelper.TryGetValidAuthenticationChallengeForScheme (string scheme, AuthenticationType authenticationType, Uri uri, ICredentials credentials, HttpHeaderValueCollection< AuthenticationHeaderValue > authenticationHeaderValues, out AuthenticationChallenge challenge) inline static private
Definition at line 240 of file AuthenticationHelper.cs.
    {
        challenge = default(AuthenticationChallenge);
        if (!TryGetChallengeDataForScheme(scheme, authenticationHeaderValues, out var challengeData))
        {
            return false;
        }
        NetworkCredential credential = credentials.GetCredential(uri, scheme);
        if (credential == null)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.AuthenticationInfo(uri, "Authentication scheme '" + scheme + "' supported by server, but not by client.");
            }
            return false;
        }
        challenge = new AuthenticationChallenge(authenticationType, scheme, credential, challengeData);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.AuthenticationInfo(uri, "Authentication scheme '" + scheme + "' selected. Client username=" + challenge.Credential.UserName);
        }
        return true;
    }
References System.Net.NetEventSource.AuthenticationInfo(), System.Net.NetEventSource.Log, and System.Net.Http.AuthenticationHelper.TryGetChallengeDataForScheme().
Referenced by System.Net.Http.AuthenticationHelper.TryGetAuthenticationChallenge().