Terraria: System.Net.Http.AuthenticationHelper.SendWithAuthAsync
SendWithAuthAsync()
static async ValueTask< HttpResponseMessage > System.Net.Http.AuthenticationHelper.SendWithAuthAsync (HttpRequestMessage request, Uri authUri, bool async, ICredentials credentials, bool preAuthenticate, bool isProxyAuth, bool doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken) inline static private
Definition at line 359 of file AuthenticationHelper.cs.
    {
        bool performedBasicPreauth = false;
        if (preAuthenticate)
        {
            NetworkCredential credential;
            lock (pool.PreAuthCredentials)
            {
                credential = pool.PreAuthCredentials.GetCredential(authUri, "Basic");
            }
            if (credential != null)
            {
                SetBasicAuthToken(request, credential, isProxyAuth);
                performedBasicPreauth = true;
            }
        }
        HttpResponseMessage response = await InnerSendAsync(request, async, isProxyAuth, doRequestAuth, pool, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        if (TryGetAuthenticationChallenge(response, isProxyAuth, authUri, credentials, out var challenge))
        {
            switch (challenge.AuthenticationType)
            {
            case AuthenticationType.Digest:
            {
                DigestResponse digestResponse = new DigestResponse(challenge.ChallengeData);
                if (!(await TrySetDigestAuthToken(request, challenge.Credential, digestResponse, isProxyAuth).ConfigureAwait(continueOnCapturedContext: false)))
                {
                    break;
                }
                response.Dispose();
                response = await InnerSendAsync(request, async, isProxyAuth, doRequestAuth, pool, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                if (TryGetRepeatedChallenge(response, challenge.SchemeName, isProxyAuth, out var challengeData))
                {
                    digestResponse = new DigestResponse(challengeData);
                    bool flag = IsServerNonceStale(digestResponse);
                    bool flag2 = flag;
                    if (flag2)
                    {
                        flag2 = await TrySetDigestAuthToken(request, challenge.Credential, digestResponse, isProxyAuth).ConfigureAwait(continueOnCapturedContext: false);
                    }
                    if (flag2)
                    {
                        response.Dispose();
                        response = await InnerSendAsync(request, async, isProxyAuth, doRequestAuth, pool, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    }
                }
                break;
            }
            case AuthenticationType.Basic:
            {
                if (performedBasicPreauth)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.AuthenticationError(authUri, "Pre-authentication with " + (isProxyAuth ? "proxy" : "server") + " failed.");
                    }
                    break;
                }
                response.Dispose();
                SetBasicAuthToken(request, challenge.Credential, isProxyAuth);
                response = await InnerSendAsync(request, async, isProxyAuth, doRequestAuth, pool, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                if (!preAuthenticate)
                {
                    break;
                }
                HttpStatusCode statusCode = response.StatusCode;
                if (statusCode == HttpStatusCode.Unauthorized || statusCode == HttpStatusCode.ProxyAuthenticationRequired)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.AuthenticationError(authUri, "Pre-authentication with " + (isProxyAuth ? "proxy" : "server") + " failed.");
                    }
                    break;
                }
                lock (pool.PreAuthCredentials)
                {
                    try
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(pool.PreAuthCredentials, $"Adding Basic credential to cache, uri={authUri}, username={challenge.Credential.UserName}", "SendWithAuthAsync");
                        }
                        pool.PreAuthCredentials.Add(authUri, "Basic", challenge.Credential);
                    }
                    catch (ArgumentException)
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(pool.PreAuthCredentials, $"Basic credential present in cache, uri={authUri}, username={challenge.Credential.UserName}", "SendWithAuthAsync");
                        }
                    }
                }
                break;
            }
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled() && response.StatusCode == HttpStatusCode.Unauthorized)
        {
            System.Net.NetEventSource.AuthenticationError(authUri, (isProxyAuth ? "Proxy" : "Server") + " authentication failed.");
        }
        return response;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.NetEventSource.AuthenticationError(), System.cancellationToken, System.Net.NetEventSource.Info(), System.Net.Http.AuthenticationHelper.InnerSendAsync(), System.Net.Http.AuthenticationHelper.IsServerNonceStale(), System.Net.NetEventSource.Log, System.Net.Http.AuthenticationHelper.SetBasicAuthToken(), System.Net.Http.AuthenticationHelper.TryGetAuthenticationChallenge(), System.Net.Http.AuthenticationHelper.TryGetRepeatedChallenge(), and System.Net.Http.AuthenticationHelper.TrySetDigestAuthToken().
Referenced by System.Net.Http.AuthenticationHelper.SendWithProxyAuthAsync(), and System.Net.Http.AuthenticationHelper.SendWithRequestAuthAsync().