Terraria: System.Net.Http.AuthenticationHelper.TrySetDigestAuthToken
TrySetDigestAuthToken()
static async ValueTask< bool > System.Net.Http.AuthenticationHelper.TrySetDigestAuthToken (HttpRequestMessage request, NetworkCredential credential, DigestResponse digestResponse, bool isProxyAuth) inline static private
Definition at line 334 of file AuthenticationHelper.cs.
    {
        string text = await GetDigestTokenForCredential(credential, request, digestResponse).ConfigureAwait(continueOnCapturedContext: false);
        if (string.IsNullOrEmpty(text))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.AuthenticationError(request.RequestUri, "Unable to find 'Digest' authentication token when authenticating with " + (isProxyAuth ? "proxy" : "server"));
            }
            return false;
        }
        AuthenticationHeaderValue headerValue = new AuthenticationHeaderValue("Digest", text);
        SetRequestAuthenticationHeaderValue(request, headerValue, isProxyAuth);
        return true;
    }
References System.Net.NetEventSource.AuthenticationError(), System.Net.Http.AuthenticationHelper.GetDigestTokenForCredential(), System.Net.NetEventSource.Log, System.Net.Http.AuthenticationHelper.SetRequestAuthenticationHeaderValue(), and System.text.
Referenced by System.Net.Http.AuthenticationHelper.SendWithAuthAsync().