Terraria: System.Data.Common.DataStorage.IsTypeCustomType
IsTypeCustomType() [2/2]
static bool System.Data.Common.DataStorage.IsTypeCustomType (Type type) inline static package inherited
Definition at line 307 of file DataStorage.cs.
    {
        return IsTypeCustomType(GetStorageType(type));
    }
References System.Data.Common.DataStorage.GetStorageType(), System.Data.Common.DataStorage.IsTypeCustomType(), and System.type.
Referenced by System.Data.Common.DataStorage.DataStorage(), System.Data.Common.ObjectStorage.ConvertObjectToXml(), System.Data.Common.DataStorage.IsTypeCustomType(), System.Data.DataColumn.IsValueCustomTypeInstance(), System.Data.DataTable.SilentlySetValue(), and System.Data.XmlTreeGen.ValidateColumnMapping().