Terraria: System.Net.Http.AuthenticationHelper.TryGetAuthenticationChallenge
TryGetAuthenticationChallenge()
static bool System.Net.Http.AuthenticationHelper.TryGetAuthenticationChallenge (HttpResponseMessage response, bool isProxyAuth, Uri authUri, ICredentials credentials, out AuthenticationChallenge challenge) inline static private
Definition at line 264 of file AuthenticationHelper.cs.
    {
        if (!IsAuthenticationChallenge(response, isProxyAuth))
        {
            challenge = default(AuthenticationChallenge);
            return false;
        }
        HttpHeaderValueCollection<AuthenticationHeaderValue> responseAuthenticationHeaderValues = GetResponseAuthenticationHeaderValues(response, isProxyAuth);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.AuthenticationInfo(authUri, $"{(isProxyAuth ? "Proxy" : "Server")} authentication requested with WWW-Authenticate header value '{responseAuthenticationHeaderValues}'");
        }
        if (!TryGetValidAuthenticationChallengeForScheme("Negotiate", AuthenticationType.Negotiate, authUri, credentials, responseAuthenticationHeaderValues, out challenge) && !TryGetValidAuthenticationChallengeForScheme("NTLM", AuthenticationType.Ntlm, authUri, credentials, responseAuthenticationHeaderValues, out challenge) && !TryGetValidAuthenticationChallengeForScheme("Digest", AuthenticationType.Digest, authUri, credentials, responseAuthenticationHeaderValues, out challenge))
        {
            return TryGetValidAuthenticationChallengeForScheme("Basic", AuthenticationType.Basic, authUri, credentials, responseAuthenticationHeaderValues, out challenge);
        }
        return true;
    }
References System.Net.NetEventSource.AuthenticationInfo(), System.Net.Http.AuthenticationHelper.GetResponseAuthenticationHeaderValues(), System.Net.Http.AuthenticationHelper.IsAuthenticationChallenge(), System.Net.NetEventSource.Log, System.Net.Http.Proxy, and System.Net.Http.AuthenticationHelper.TryGetValidAuthenticationChallengeForScheme().
Referenced by System.Net.Http.AuthenticationHelper.SendWithAuthAsync(), and System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync().