Terraria: System.Net.Http.AuthenticationHelper.GetRandomAlphaNumericString
GetRandomAlphaNumericString()
static string System.Net.Http.AuthenticationHelper.GetRandomAlphaNumericString () inline static private
Definition at line 584 of file AuthenticationHelper.cs.
    {
        Span<byte> data = stackalloc byte[32];
        RandomNumberGenerator.Fill(data);
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire();
        int num = 0;
        while (num < data.Length)
        {
            int num2 = data[num++] % 3;
            int num3 = data[num++] % ((num2 == 0) ? 10 : 26);
            stringBuilder.Append((char)(s_alphaNumChooser[num2] + num3));
        }
        return System.Text.StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Text.StringBuilderCache.Acquire(), System.Security.Cryptography.RandomNumberGenerator.Fill(), System.Text.StringBuilderCache.GetStringAndRelease(), and System.Net.Http.AuthenticationHelper.s_alphaNumChooser.
Referenced by System.Net.Http.AuthenticationHelper.GetDigestTokenForCredential().