Terraria: System.Data.Common.DataStorage.CopyBits
CopyBits()
void System.Data.Common.DataStorage.CopyBits (int srcRecordNo, int dstRecordNo) inline protected inherited
Definition at line 159 of file DataStorage.cs.
    {
        _dbNullBits.Set(dstRecordNo, _dbNullBits.Get(srcRecordNo));
    }
References System.Data.Common.DataStorage._dbNullBits, System.Xml.Dictionary, System.Collections.BitArray.Get(), and System.Collections.BitArray.Set().
Referenced by System.Data.Common.BigIntegerStorage.Copy(), System.Data.Common.BooleanStorage.Copy(), System.Data.Common.ByteStorage.Copy(), System.Data.Common.CharStorage.Copy(), System.Data.Common.DateTimeOffsetStorage.Copy(), System.Data.Common.DateTimeStorage.Copy(), System.Data.Common.DecimalStorage.Copy(), System.Data.Common.DoubleStorage.Copy(), System.Data.Common.Int16Storage.Copy(), System.Data.Common.Int32Storage.Copy(), System.Data.Common.Int64Storage.Copy(), System.Data.Common.SByteStorage.Copy(), System.Data.Common.SingleStorage.Copy(), System.Data.Common.SqlUdtStorage.Copy(), System.Data.Common.TimeSpanStorage.Copy(), System.Data.Common.UInt16Storage.Copy(), System.Data.Common.UInt32Storage.Copy(), and System.Data.Common.UInt64Storage.Copy().