Terraria: System.Data.Common.DataStorage.GetStorageType
GetStorageType()
static StorageType System.Data.Common.DataStorage.GetStorageType (Type dataType) inline static package inherited
Definition at line 285 of file DataStorage.cs.
    {
        for (int i = 0; i < s_storageClassType.Length; i++)
        {
            if (dataType == s_storageClassType[i])
            {
                return (StorageType)i;
            }
        }
        TypeCode typeCode = Type.GetTypeCode(dataType);
        if (TypeCode.Object != typeCode)
        {
            return (StorageType)typeCode;
        }
        return StorageType.Empty;
    }
References System.Type.GetTypeCode(), and System.Data.Common.DataStorage.s_storageClassType.
Referenced by System.Data.DataColumn.DataColumn(), System.Data.DataExpression.DataExpression(), System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.SqlConvert.ChangeTypeForDefaultValue(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.Common.SqlConvert.ConvertToSqlBinary(), System.Data.Common.SqlConvert.ConvertToSqlBoolean(), System.Data.Common.SqlConvert.ConvertToSqlByte(), System.Data.Common.SqlConvert.ConvertToSqlBytes(), System.Data.Common.SqlConvert.ConvertToSqlChars(), System.Data.Common.SqlConvert.ConvertToSqlDateTime(), System.Data.Common.SqlConvert.ConvertToSqlDecimal(), System.Data.Common.SqlConvert.ConvertToSqlDouble(), System.Data.Common.SqlConvert.ConvertToSqlGuid(), System.Data.Common.SqlConvert.ConvertToSqlInt16(), System.Data.Common.SqlConvert.ConvertToSqlInt32(), System.Data.Common.SqlConvert.ConvertToSqlInt64(), System.Data.Common.SqlConvert.ConvertToSqlMoney(), System.Data.Common.SqlConvert.ConvertToSqlSingle(), System.Data.Common.SqlConvert.ConvertToSqlString(), System.Data.Select.Eval(), System.Data.FunctionNode.Eval(), System.Data.BinaryNode.EvalBinaryOp(), System.Data.FunctionNode.EvalFunction(), System.Data.UnaryNode.EvalUnaryOp(), and System.Data.Common.DataStorage.IsTypeCustomType().