Terraria: System.Net.Http.AuthenticationHelper.SetBasicAuthToken
SetBasicAuthToken()
static void System.Net.Http.AuthenticationHelper.SetBasicAuthToken (HttpRequestMessage request, NetworkCredential credential, bool isProxyAuth) inline static private
Definition at line 327 of file AuthenticationHelper.cs.
    {
        string s = ((!string.IsNullOrEmpty(credential.Domain)) ? (credential.Domain + "\\" + credential.UserName + ":" + credential.Password) : (credential.UserName + ":" + credential.Password));
        string parameter = Convert.ToBase64String(Encoding.UTF8.GetBytes(s));
        SetRequestAuthenticationHeaderValue(request, new AuthenticationHeaderValue("Basic", parameter), isProxyAuth);
    }
References System.s, System.Net.Http.AuthenticationHelper.SetRequestAuthenticationHeaderValue(), System.Convert.ToBase64String(), and System.Text.Encoding.UTF8.
Referenced by System.Net.Http.AuthenticationHelper.SendWithAuthAsync().