Terraria: System.Data.Common.DataStorage.IsObjectSqlNull
IsObjectSqlNull()
static bool System.Data.Common.DataStorage.IsObjectSqlNull (object value) inline static inherited
Definition at line 439 of file DataStorage.cs.
    {
        if (value is INullable nullable)
        {
            return nullable.IsNull;
        }
        return false;
    }
References System.Xml.Dictionary, and System.value.
Referenced by System.Data.DataColumn.Clone(), System.Data.Select.Eval(), System.Data.LikeNode.Eval(), System.Data.BinaryNode.EvalBinaryOp(), System.Data.NewDiffgramGen.GenerateColumn(), System.Data.Common.DataStorage.IsObjectNull(), and System.Data.XmlDataTreeWriter.XmlDataRowWriter().