Terraria: CaptureCamera.DrawTick
DrawTick()
void CaptureCamera.DrawTick () inline
     {
         Monitor.Enter(_captureLock);
         if (_activeSettings == null)
         {
             return;
         }
         bool notRetro = Lighting.NotRetro;
         if (_renderQueue.Count > 0)
         {
             CaptureChunk captureChunk = _renderQueue.Dequeue();
             _graphics.SetRenderTarget(null);
             _graphics.Clear(Microsoft.Xna.Framework.Color.Transparent);
             Main.instance.TilesRenderer.PrepareForAreaDrawing(captureChunk.Area.Left, captureChunk.Area.Right, captureChunk.Area.Top, captureChunk.Area.Bottom, prepareLazily: false);
             Main.instance.TilePaintSystem.PrepareAllRequests();
             _graphics.SetRenderTarget(_frameBuffer);
             _graphics.Clear(Microsoft.Xna.Framework.Color.Transparent);
             if (notRetro)
             {
                 Microsoft.Xna.Framework.Color clearColor = (_activeSettings.CaptureBackground ? Microsoft.Xna.Framework.Color.Black : Microsoft.Xna.Framework.Color.Transparent);
                 Filters.Scene.BeginCapture(_filterFrameBuffer1, clearColor);
                 Main.instance.DrawCapture(captureChunk.Area, _activeSettings);
                 Filters.Scene.EndCapture(_frameBuffer, _filterFrameBuffer1, _filterFrameBuffer2, clearColor);
             }
             else
             {
                 Main.instance.DrawCapture(captureChunk.Area, _activeSettings);
             }
             if (_activeSettings.UseScaling)
             {
                 _graphics.SetRenderTarget(_scaledFrameBuffer);
                 _graphics.Clear(Microsoft.Xna.Framework.Color.Transparent);
                 _spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, _downscaleSampleState, DepthStencilState.Default, RasterizerState.CullNone);
                 _spriteBatch.Draw(_frameBuffer, new Microsoft.Xna.Framework.Rectangle(0, 0, _scaledFrameBuffer.Width, _scaledFrameBuffer.Height), Microsoft.Xna.Framework.Color.White);
                 _spriteBatch.End();
                 _graphics.SetRenderTarget(null);
                 _scaledFrameBuffer.GetData(_scaledFrameData, 0, _scaledFrameBuffer.Width * _scaledFrameBuffer.Height * 4);
                 DrawBytesToBuffer(_scaledFrameData, _outputData, _scaledFrameBuffer.Width, _outputImageSize.Width, captureChunk.ScaledArea);
             }
             else
             {
                 _graphics.SetRenderTarget(null);
                 SaveImage(_frameBuffer, captureChunk.ScaledArea.Width, captureChunk.ScaledArea.Height, ImageFormat.Png, _activeSettings.OutputName, captureChunk.Area.X + "-" + captureChunk.Area.Y + ".png");
             }
             _tilesProcessed += captureChunk.Area.Width * captureChunk.Area.Height;
         }
         if (_renderQueue.Count == 0)
         {
             FinishCapture();
         }
         Monitor.Exit(_captureLock);
     }
References _activeSettings, _captureLock, _downscaleSampleState, _filterFrameBuffer1, _filterFrameBuffer2, _frameBuffer, _graphics, _outputData, _outputImageSize, _renderQueue, _scaledFrameBuffer, _scaledFrameData, _spriteBatch, _tilesProcessed, CaptureCamera.CaptureChunk.Area, FilterManager.BeginCapture(), CaptureSettings.CaptureBackground, DrawBytesToBuffer(), Main.DrawCapture(), FilterManager.EndCapture(), FinishCapture(), Main.instance, Lighting.NotRetro, CaptureSettings.OutputName, TilePaintSystemV2.PrepareAllRequests(), TileDrawing.PrepareForAreaDrawing(), SaveImage(), CaptureCamera.CaptureChunk.ScaledArea, Filters.Scene, Main.TilePaintSystem, Main.TilesRenderer, and CaptureSettings.UseScaling.
Referenced by CaptureManager.DrawTick().