Terraria: System.Xml.Xsl.XsltOld.WithParamAction.Compile
Compile()
override void System.Xml.Xsl.XsltOld.WithParamAction.Compile (Compiler compiler) inline package
Definition at line 10 of file WithParamAction.cs.
    {
        CompileAttributes(compiler);
        CheckRequiredAttribute(compiler, name, "name");
        if (compiler.Recurse())
        {
            CompileTemplate(compiler);
            compiler.ToParent();
            if (selectKey != -1 && containedActions != null)
            {
                throw XsltException.Create(System.SR.Xslt_VariableCntSel2, nameStr);
            }
        }
    }
References System.Xml.Xsl.XsltOld.CompiledAction.CheckRequiredAttribute(), System.Xml.Xsl.XsltOld.CompiledAction.CompileAttributes(), System.Xml.Xsl.XsltOld.ContainerAction.CompileTemplate(), System.Xml.Xsl.XsltOld.ContainerAction.containedActions, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.VariableAction.name, System.Xml.Xsl.XsltOld.VariableAction.nameStr, System.Xml.Xsl.XsltOld.VariableAction.selectKey, and System.SR.Xslt_VariableCntSel2.