Terraria: CreativePowers.ASharedSliderPower.SetValueKeyboardForced
SetValueKeyboardForced()
void CreativePowers.ASharedSliderPower.SetValueKeyboardForced (float value) inline package inherited
         {
             if (CreativePowersHelper.IsAvailableForPlayer(this, Main.myPlayer))
             {
                 _currentTargetValue = value;
                 _needsToCommitChange = true;
             }
         }
References CreativePowers.ASharedSliderPower._currentTargetValue, CreativePowers.ASharedSliderPower._needsToCommitChange, CreativePowersHelper.IsAvailableForPlayer(), and Main.myPlayer.
Referenced by CreativePowers.ModifyTimeRate.bottomText_OnClick(), CreativePowers.ModifyWindDirectionAndStrength.bottomText_OnClick(), CreativePowers.ModifyRainPower.bottomText_OnClick(), CreativePowers.DifficultySliderPower.Click_Expert(), CreativePowers.DifficultySliderPower.Click_Journey(), CreativePowers.DifficultySliderPower.Click_Master(), CreativePowers.DifficultySliderPower.Click_Normal(), CreativePowers.ModifyTimeRate.middleText_OnClick(), CreativePowers.ModifyWindDirectionAndStrength.middleText_OnClick(), CreativePowers.ModifyRainPower.middleText_OnClick(), CreativePowers.ASharedSliderPower.SetValueKeyboard(), CreativePowers.ModifyTimeRate.topText_OnClick(), CreativePowers.ModifyWindDirectionAndStrength.topText_OnClick(), and CreativePowers.ModifyRainPower.topText_OnClick().