Terraria: PlayerDataInitializer.Load
Load()
static void PlayerDataInitializer.Load () inline static
     {
         TextureAssets.Players = new Asset<Texture2D>[PlayerVariantID.Count, PlayerTextureID.Count];
         LoadStarterMale();
         LoadStarterFemale();
         LoadStickerMale();
         LoadStickerFemale();
         LoadGangsterMale();
         LoadGangsterFemale();
         LoadCoatMale();
         LoadDressFemale();
         LoadDressMale();
         LoadCoatFemale();
         LoadDisplayDollMale();
         LoadDisplayDollFemale();
     }
References PlayerTextureID.Count, PlayerVariantID.Count, LoadCoatFemale(), LoadCoatMale(), LoadDisplayDollFemale(), LoadDisplayDollMale(), LoadDressFemale(), LoadDressMale(), LoadGangsterFemale(), LoadGangsterMale(), LoadStarterFemale(), LoadStarterMale(), LoadStickerFemale(), LoadStickerMale(), and TextureAssets.Players.
Referenced by AssetInitializer.LoadTextures().