Terraria: System.IO.IsolatedStorage.IsolatedStorageFileStream.InitializeFileStream
InitializeFileStream()
static InitialiationData System.IO.IsolatedStorage.IsolatedStorageFileStream.InitializeFileStream (string path, FileMode mode, FileAccess access, FileShare share, int bufferSize, IsolatedStorageFile isf) inline static private
Definition at line 109 of file IsolatedStorageFileStream.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (path.Length == 0 || path.Equals("\\"))
        {
            throw new ArgumentException(System.SR.IsolatedStorage_Path);
        }
        bool flag = false;
        if (isf == null)
        {
            isf = IsolatedStorageFile.GetUserStoreForDomain();
            flag = true;
        }
        if (isf.Disposed)
        {
            throw new ObjectDisposedException(null, System.SR.IsolatedStorage_StoreNotOpen);
        }
        if ((uint)(mode - 1) > 5u)
        {
            throw new ArgumentException(System.SR.IsolatedStorage_FileOpenMode);
        }
        InitialiationData initialiationData = default(InitialiationData);
        initialiationData.FullPath = isf.GetFullPath(path);
        initialiationData.StorageFile = isf;
        InitialiationData result = initialiationData;
        try
        {
            result.NestedStream = new FileStream(result.FullPath, mode, access, share, bufferSize, FileOptions.None);
            return result;
        }
        catch (Exception rootCause)
        {
            try
            {
                if (flag)
                {
                    result.StorageFile?.Dispose();
                }
            }
            catch
            {
            }
            throw IsolatedStorageFile.GetIsolatedStorageException(System.SR.IsolatedStorage_Operation_ISFS, rootCause);
        }
    }
References System.IO.FileStream.FileStream(), System.IO.IsolatedStorage.IsolatedStorageFile.Dispose(), System.IO.IsolatedStorage.IsolatedStorageFile.Disposed, System.IO.IsolatedStorage.IsolatedStorageFileStream.InitialiationData.FullPath, System.IO.IsolatedStorage.IsolatedStorageFile.GetFullPath(), System.IO.IsolatedStorage.IsolatedStorageFile.GetIsolatedStorageException(), System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForDomain(), System.SR.IsolatedStorage_FileOpenMode, System.SR.IsolatedStorage_Operation_ISFS, System.SR.IsolatedStorage_Path, System.SR.IsolatedStorage_StoreNotOpen, and System.IO.IsolatedStorage.IsolatedStorageFileStream.InitialiationData.StorageFile.