Terraria: UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem
UIWorkshopPublishWorldListItem()
UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem (UIState ownerState, WorldFileData data, int orderInList) inline
     {
         _ownerState = ownerState;
         _orderInList = orderInList;
         _data = data;
         LoadTextures();
         InitializeAppearance();
         _worldIcon = GetIconElement();
         _worldIcon.Left.Set(4f, 0f);
         _worldIcon.VAlign = 0.5f;
         _worldIcon.OnLeftDoubleClick += PublishButtonClick_ImportWorldToLocalFiles;
         Append(_worldIcon);
         _ = 4f;
         _publishButton = new UIIconTextButton(Language.GetText("Workshop.Publish"), Color.White, "Images/UI/Workshop/Publish");
         _publishButton.HAlign = 1f;
         _publishButton.VAlign = 1f;
         _publishButton.OnLeftClick += PublishButtonClick_ImportWorldToLocalFiles;
         base.OnLeftDoubleClick += PublishButtonClick_ImportWorldToLocalFiles;
         Append(_publishButton);
         _publishButton.SetSnapPoint("Publish", orderInList);
     }
References AWorldListItem._data, _orderInList, _ownerState, _publishButton, _worldIcon, UIElement.Append(), Color, AWorldListItem.GetIconElement(), Language.GetText(), UIElement.HAlign, InitializeAppearance(), UIElement.Left, LoadTextures(), UIElement.OnLeftClick, UIElement.OnLeftDoubleClick, PublishButtonClick_ImportWorldToLocalFiles(), StyleDimension.Set(), UIElement.SetSnapPoint(), and UIElement.VAlign.