Terraria: Internal.Win32.Registry.LocalMachine
LocalMachine
readonly RegistryKey Internal.Win32.Registry.LocalMachine = RegistryKey.OpenBaseKey((IntPtr)(-2147483646)) static
Definition at line 9 of file Registry.cs.
Referenced by System.TimeZoneInfo.FindIdFromTimeZoneInformation(), System.Diagnostics.Tracing.EventProvider.GetDataFromController(), System.TimeZoneInfo.GetUtcStandardDisplayName(), System.Globalization.JapaneseCalendar.NlsGetJapaneseEras(), System.Environment.OpenEnvironmentKeyIfExists(), System.TimeZoneInfo.PopulateAllSystemTimeZones(), System.TimeZoneInfo.TryCompareTimeZoneInformationToRegistry(), System.TimeZoneInfo.TryCreateAdjustmentRules(), and System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine().