Terraria: System.Net.Mime.MailBnfHelper.ReadToken
ReadToken()
static string System.Net.Mime.MailBnfHelper.ReadToken (string data, ref int offset, StringBuilder builder) inline static package
Definition at line 298 of file MailBnfHelper.cs.
    {
        int num = offset;
        while (offset < data.Length)
        {
            if (data[offset] > '\u007f')
            {
                throw new FormatException(System.SR.Format(System.SR.MailHeaderFieldInvalidCharacter, data[offset]));
            }
            if (!Ttext[(uint)data[offset]])
            {
                break;
            }
            offset++;
        }
        if (num == offset && offset < data.Length)
        {
            throw new FormatException(System.SR.Format(System.SR.MailHeaderFieldInvalidCharacter, data[offset]));
        }
        return data.Substring(num, offset - num);
    }
References System.SR.Format(), System.SR.MailHeaderFieldInvalidCharacter, System.offset, and System.Net.Mime.MailBnfHelper.Ttext.
Referenced by System.Net.Mime.ContentDisposition.ParseValue(), System.Net.Mime.ContentType.ParseValue(), System.Net.Mime.MailBnfHelper.ReadParameterAttribute(), and System.Net.Mail.AttachmentBase.SetContentFromString().