Terraria: System.Net.Mime.MailBnfHelper.ReadQuotedString
ReadQuotedString() [2/2]
static string System.Net.Mime.MailBnfHelper.ReadQuotedString (string data, ref int offset, StringBuilder builder, bool doesntRequireQuotes, bool permitUnicodeInDisplayName) inline static package
Definition at line 232 of file MailBnfHelper.cs.
    {
        if (!doesntRequireQuotes)
        {
            offset++;
        }
        int num = offset;
        StringBuilder stringBuilder = ((builder != null) ? builder : new StringBuilder());
        while (offset < data.Length)
        {
            if (data[offset] == '\\')
            {
                stringBuilder.Append(data, num, offset - num);
                num = ++offset;
            }
            else
            {
                if (data[offset] == '"')
                {
                    stringBuilder.Append(data, num, offset - num);
                    offset++;
                    if (builder == null)
                    {
                        return stringBuilder.ToString();
                    }
                    return null;
                }
                if (data[offset] == '=' && data.Length > offset + 3 && data[offset + 1] == '\r' && data[offset + 2] == '\n' && (data[offset + 3] == ' ' || data[offset + 3] == '\t'))
                {
                    offset += 3;
                }
                else if (permitUnicodeInDisplayName)
                {
                    if (data[offset] <= '\u007f' && !Qtext[(uint)data[offset]])
                    {
                        throw new FormatException(System.SR.Format(System.SR.MailHeaderFieldInvalidCharacter, data[offset]));
                    }
                }
                else if (data[offset] > '\u007f' || !Qtext[(uint)data[offset]])
                {
                    throw new FormatException(System.SR.Format(System.SR.MailHeaderFieldInvalidCharacter, data[offset]));
                }
            }
            offset++;
        }
        if (doesntRequireQuotes)
        {
            stringBuilder.Append(data, num, offset - num);
            if (builder == null)
            {
                return stringBuilder.ToString();
            }
            return null;
        }
        throw new FormatException(System.SR.MailHeaderFieldMalformedHeader);
    }
References System.Text.StringBuilder.Append(), System.SR.Format(), System.SR.MailHeaderFieldInvalidCharacter, System.SR.MailHeaderFieldMalformedHeader, System.offset, System.Net.Mime.MailBnfHelper.Qtext, and System.Text.StringBuilder.ToString().