Terraria: System.Net.Mime.MailBnfHelper.GetTokenOrQuotedString
GetTokenOrQuotedString()
static void System.Net.Mime.MailBnfHelper.GetTokenOrQuotedString (string data, StringBuilder builder, bool allowUnicode) inline static package
Definition at line 365 of file MailBnfHelper.cs.
    {
        int i = 0;
        int num = 0;
        for (; i < data.Length; i++)
        {
            if (CheckForUnicode(data[i], allowUnicode) || (Ttext[(uint)data[i]] && data[i] != ' '))
            {
                continue;
            }
            builder.Append('"');
            for (; i < data.Length; i++)
            {
                if (!CheckForUnicode(data[i], allowUnicode))
                {
                    if (IsFWSAt(data, i))
                    {
                        i += 2;
                    }
                    else if (!Qtext[(uint)data[i]])
                    {
                        builder.Append(data, num, i - num);
                        builder.Append('\\');
                        num = i;
                    }
                }
            }
            builder.Append(data, num, i - num);
            builder.Append('"');
            return;
        }
        if (data.Length == 0)
        {
            builder.Append("\"\"");
        }
        builder.Append(data);
    }
References System.Text.StringBuilder.Append(), System.Net.Mime.MailBnfHelper.CheckForUnicode(), System.Net.Mime.MailBnfHelper.IsFWSAt(), System.Net.Mime.MailBnfHelper.Qtext, and System.Net.Mime.MailBnfHelper.Ttext.
Referenced by System.Net.Mime.ContentDisposition.EncodeToBuffer(), and System.Net.Mime.ContentType.EncodeToBuffer().