Terraria: System.Xml.Schema.NamespaceList.Intersection
Intersection()
static NamespaceList System.Xml.Schema.NamespaceList.Intersection (NamespaceList o1, NamespaceList o2, bool v1Compat) inline static
Definition at line 232 of file NamespaceList.cs.
    {
        NamespaceList namespaceList = null;
        if (o1._type == ListType.Any)
        {
            namespaceList = o2.Clone();
        }
        else if (o2._type == ListType.Any)
        {
            namespaceList = o1.Clone();
        }
        else if (o1._type == ListType.Set && o2._type == ListType.Other)
        {
            namespaceList = o1.Clone();
            namespaceList.RemoveNamespace(o2._targetNamespace);
            if (!v1Compat)
            {
                namespaceList.RemoveNamespace(string.Empty);
            }
        }
        else if (o1._type == ListType.Other && o2._type == ListType.Set)
        {
            namespaceList = o2.Clone();
            namespaceList.RemoveNamespace(o1._targetNamespace);
            if (!v1Compat)
            {
                namespaceList.RemoveNamespace(string.Empty);
            }
        }
        else if (o1._type == ListType.Set && o2._type == ListType.Set)
        {
            namespaceList = o1.Clone();
            namespaceList = new NamespaceList();
            namespaceList._type = ListType.Set;
            namespaceList._set = new Hashtable();
            foreach (string key in o1._set.Keys)
            {
                if (o2._set.Contains(key))
                {
                    namespaceList._set.Add(key, key);
                }
            }
        }
        else if (o1._type == ListType.Other && o2._type == ListType.Other)
        {
            if (o1._targetNamespace == o2._targetNamespace)
            {
                return o1.Clone();
            }
            if (!v1Compat)
            {
                if (o1._targetNamespace == string.Empty)
                {
                    namespaceList = o2.Clone();
                }
                else if (o2._targetNamespace == string.Empty)
                {
                    namespaceList = o1.Clone();
                }
            }
        }
        return namespaceList;
    }
References System.Xml.Schema.NamespaceList.NamespaceList(), System.Xml.Schema.NamespaceList._set, System.Collections.Hashtable.Add(), System.Xml.Schema.NamespaceList.Clone(), System.Xml.Dictionary, System.key, and System.Xml.Schema.NamespaceList.RemoveNamespace().
Referenced by System.Xml.Schema.XmlSchemaAnyAttribute.Intersection().