Terraria: System.Xml.Schema.NamespaceList.Union
Union()
static NamespaceList System.Xml.Schema.NamespaceList.Union (NamespaceList o1, NamespaceList o2, bool v1Compat) inline static
Definition at line 180 of file NamespaceList.cs.
    {
        NamespaceList namespaceList = null;
        if (o1._type == ListType.Any)
        {
            namespaceList = new NamespaceList();
        }
        else if (o2._type == ListType.Any)
        {
            namespaceList = new NamespaceList();
        }
        else if (o1._type == ListType.Set && o2._type == ListType.Set)
        {
            namespaceList = o1.Clone();
            foreach (string key in o2._set.Keys)
            {
                namespaceList._set[key] = key;
            }
        }
        else if (o1._type == ListType.Other && o2._type == ListType.Other)
        {
            namespaceList = ((!(o1._targetNamespace == o2._targetNamespace)) ? new NamespaceList("##other", string.Empty) : o1.Clone());
        }
        else if (o1._type == ListType.Set && o2._type == ListType.Other)
        {
            namespaceList = (v1Compat ? ((!o1._set.Contains(o2._targetNamespace)) ? o2.Clone() : new NamespaceList()) : ((o2._targetNamespace != string.Empty) ? o1.CompareSetToOther(o2) : ((!o1._set.Contains(string.Empty)) ? new NamespaceList("##other", string.Empty) : new NamespaceList())));
        }
        else if (o2._type == ListType.Set && o1._type == ListType.Other)
        {
            namespaceList = (v1Compat ? ((!o2._set.Contains(o2._targetNamespace)) ? o1.Clone() : new NamespaceList()) : ((o1._targetNamespace != string.Empty) ? o2.CompareSetToOther(o1) : ((!o2._set.Contains(string.Empty)) ? new NamespaceList("##other", string.Empty) : new NamespaceList())));
        }
        return namespaceList;
    }
References System.Xml.Schema.NamespaceList.NamespaceList(), System.Xml.Schema.NamespaceList._set, System.Xml.Schema.NamespaceList.Clone(), System.Xml.Dictionary, and System.key.
Referenced by System.Xml.Schema.XmlSchemaAnyAttribute.Union().