Terraria: System.Xml.Schema.NamespaceList.Allows
Allows() [1/2]
virtual bool System.Xml.Schema.NamespaceList.Allows (string ns) inline virtual
Reimplemented in System.Xml.Schema.NamespaceListV1Compat.
Definition at line 86 of file NamespaceList.cs.
    {
        switch (_type)
        {
        case ListType.Any:
            return true;
        case ListType.Other:
            if (ns != _targetNamespace)
            {
                return ns.Length != 0;
            }
            return false;
        case ListType.Set:
            return _set[ns] != null;
        default:
            return false;
        }
    }
References System.Xml.Schema.NamespaceList._set, System.Xml.Schema.NamespaceList._targetNamespace, System.Xml.Schema.NamespaceList._type, and System.Xml.Dictionary.
Referenced by System.Xml.Schema.NamespaceList.Allows(), System.Xml.Schema.XmlSchemaAny.Allows(), and System.Xml.Schema.XmlSchemaAnyAttribute.Allows().