Terraria: Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceDartTrap
ActuallyPlaceDartTrap()
void Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceDartTrap (Point position, int directionX, int x, int y, int xPush, Tile t) inline private
    {
        t.type = 137;
        t.frameY = 0;
        if (directionX == -1)
        {
            t.frameX = 18;
        }
        else
        {
            t.frameX = 0;
        }
        t.slope(0);
        t.halfBrick(halfBrick: false);
        WorldGen.TileFrame(x, y, resetFrame: true);
        PlaceWireLine(position, directionX, 0, xPush);
    }
References Terraria.Tile.halfBrick(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceWireLine(), Terraria.Tile.slope(), and Terraria.WorldGen.TileFrame().
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.Place().