Terraria: Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpots
FindDartTrapSpots()
void Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpots (Point position) inline private
Definition at line 292 of file DeadMansChestBiome.cs.
    {
        int num = GenBase._random.Next(_numberOfDartTraps);
        int num2 = ((GenBase._random.Next(2) != 0) ? 1 : (-1));
        int steps = -1;
        for (int i = 0; i < num; i++)
        {
            bool num3 = FindDartTrapSpotSingle(position, num2);
            num2 *= -1;
            position.Y--;
            if (num3)
            {
                steps = i;
            }
        }
        _wirePlacementSpots.Add(new WirePlacementAttempt(new Point(position.X, position.Y + num), 0, -1, steps));
    }
References Terraria.GameContent.Biomes.DeadMansChestBiome._numberOfDartTraps, Terraria.WorldBuilding.GenBase._random, Terraria.GameContent.Biomes.DeadMansChestBiome._wirePlacementSpots, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpotSingle(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.GetPossibleChestsToTrapify(), and Terraria.GameContent.Biomes.DeadMansChestBiome.Place().