Terraria: System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox.MoveNext
MoveNext() [2/2]
void System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.MoveNext (Thread threadPoolThread) inline private inherited
Definition at line 120 of file AsyncTaskMethodBuilder.cs.
        {
            bool flag = TplEventSource.Log.IsEnabled();
            if (flag)
            {
                TplEventSource.Log.TraceSynchronousWorkBegin(base.Id, CausalitySynchronousWork.Execution);
            }
            ExecutionContext context = Context;
            if (context == null)
            {
                StateMachine.MoveNext();
            }
            else if (threadPoolThread == null)
            {
                ExecutionContext.RunInternal(context, s_callback, this);
            }
            else
            {
                ExecutionContext.RunFromThreadPoolDispatchLoop(threadPoolThread, context, s_callback, this);
            }
            if (base.IsCompleted)
            {
                ClearStateUponCompletion();
            }
            if (flag)
            {
                TplEventSource.Log.TraceSynchronousWorkEnd(CausalitySynchronousWork.Execution);
            }
        }
References System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.ClearStateUponCompletion(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.Context, System.Threading.Tasks.TplEventSource.Log, System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(), System.Threading.ExecutionContext.RunInternal(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.s_callback, and System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.StateMachine.