Terraria: System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AsyncStateMachineBox.ClearStateUponCompletion
ClearStateUponCompletion()
void System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.ClearStateUponCompletion () inline inherited
Implements System.Runtime.CompilerServices.IAsyncStateMachineBox.
Definition at line 151 of file AsyncTaskMethodBuilder.cs.
        {
            if (System.Threading.Tasks.Task.s_asyncDebuggingEnabled)
            {
                System.Threading.Tasks.Task.RemoveFromActiveTasks(this);
            }
            StateMachine = default(TStateMachine);
            Context = null;
            if (AsyncMethodBuilderCore.TrackAsyncMethodCompletion)
            {
                GC.SuppressFinalize(this);
            }
        }
References System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.Context, System.Threading.Tasks.Task< TResult >.RemoveFromActiveTasks(), System.Threading.Tasks.Task< TResult >.s_asyncDebuggingEnabled, System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.StateMachine, System.GC.SuppressFinalize(), and System.Runtime.CompilerServices.AsyncMethodBuilderCore.TrackAsyncMethodCompletion.
Referenced by System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.MoveNext().