Terraria: Terraria.GameContent.Biomes.DeadMansChestBiome.Place
Place()
override bool Terraria.GameContent.Biomes.DeadMansChestBiome.Place (Point origin, StructureMap structures) inline
Definition at line 102 of file DeadMansChestBiome.cs.
    {
        if (!IsAGoodSpot(origin))
        {
            return false;
        }
        ClearCaches();
        Point position = new Point(origin.X, origin.Y + 1);
        FindBoulderTrapSpots(position);
        FindDartTrapSpots(position);
        FindExplosiveTrapSpots(position);
        if (!AreThereEnoughTraps())
        {
            return false;
        }
        TurnGoldChestIntoDeadMansChest(origin);
        foreach (DartTrapPlacementAttempt dartTrapPlacementSpot in _dartTrapPlacementSpots)
        {
            ActuallyPlaceDartTrap(dartTrapPlacementSpot.position, dartTrapPlacementSpot.directionX, dartTrapPlacementSpot.x, dartTrapPlacementSpot.y, dartTrapPlacementSpot.xPush, dartTrapPlacementSpot.t);
        }
        foreach (WirePlacementAttempt wirePlacementSpot in _wirePlacementSpots)
        {
            PlaceWireLine(wirePlacementSpot.position, wirePlacementSpot.dirX, wirePlacementSpot.dirY, wirePlacementSpot.steps);
        }
        foreach (BoulderPlacementAttempt boulderPlacementSpot in _boulderPlacementSpots)
        {
            ActuallyPlaceBoulderTrap(boulderPlacementSpot.position, boulderPlacementSpot.yPush, boulderPlacementSpot.requiredHeight, boulderPlacementSpot.bestType);
        }
        foreach (ExplosivePlacementAttempt item in _explosivePlacementAttempt)
        {
            ActuallyPlaceExplosive(item.position);
        }
        PlaceWiresForExplosives(origin);
        return true;
    }
References Terraria.GameContent.Biomes.DeadMansChestBiome._boulderPlacementSpots, Terraria.GameContent.Biomes.DeadMansChestBiome._dartTrapPlacementSpots, Terraria.GameContent.Biomes.DeadMansChestBiome._explosivePlacementAttempt, Terraria.GameContent.Biomes.DeadMansChestBiome._wirePlacementSpots, Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceDartTrap(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceExplosive(), Terraria.GameContent.Biomes.DeadMansChestBiome.AreThereEnoughTraps(), Terraria.GameContent.Biomes.DeadMansChestBiome.BoulderPlacementAttempt.bestType, Terraria.GameContent.Biomes.DeadMansChestBiome.ClearCaches(), Terraria.GameContent.Biomes.DeadMansChestBiome.DartTrapPlacementAttempt.directionX, Terraria.GameContent.Biomes.DeadMansChestBiome.WirePlacementAttempt.dirX, Terraria.GameContent.Biomes.DeadMansChestBiome.WirePlacementAttempt.dirY, Terraria.GameContent.Biomes.DeadMansChestBiome.FindBoulderTrapSpots(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpots(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindExplosiveTrapSpots(), Terraria.GameContent.Biomes.DeadMansChestBiome.IsAGoodSpot(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceWireLine(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceWiresForExplosives(), Terraria.GameContent.Biomes.DeadMansChestBiome.DartTrapPlacementAttempt.position, Terraria.GameContent.Biomes.DeadMansChestBiome.BoulderPlacementAttempt.position, Terraria.GameContent.Biomes.DeadMansChestBiome.WirePlacementAttempt.position, Terraria.GameContent.Biomes.DeadMansChestBiome.ExplosivePlacementAttempt.position, Terraria.GameContent.Biomes.DeadMansChestBiome.BoulderPlacementAttempt.requiredHeight, Terraria.GameContent.Biomes.DeadMansChestBiome.WirePlacementAttempt.steps, Terraria.GameContent.Biomes.DeadMansChestBiome.DartTrapPlacementAttempt.t, Terraria.GameContent.Biomes.DeadMansChestBiome.TurnGoldChestIntoDeadMansChest(), Terraria.GameContent.Biomes.DeadMansChestBiome.DartTrapPlacementAttempt.x, Terraria.GameContent.Biomes.DeadMansChestBiome.DartTrapPlacementAttempt.xPush, Terraria.GameContent.Biomes.DeadMansChestBiome.DartTrapPlacementAttempt.y, and Terraria.GameContent.Biomes.DeadMansChestBiome.BoulderPlacementAttempt.yPush.