Terraria: GroupOptionButton.SetText
SetText()
void GroupOptionButton< T >.SetText (LocalizedText text, float textSize, Color color) inline
     {
         if (_title != null)
         {
             _title.Remove();
         }
         UIText uIText = new UIText(text, textSize)
         {
             HAlign = 0.5f,
             VAlign = 0.5f,
             Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
             Top = StyleDimension.FromPixels(0f)
         };
         uIText.TextColor = color;
         Append(uIText);
         _title = uIText;
     }
References GroupOptionButton< T >._title, UIElement.Append(), StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), UIElement.HAlign, UIElement.Remove(), UIText.TextColor, UIElement.Top, UIElement.VAlign, and UIElement.Width.