Terraria: GroupOptionButton.SetColorsBasedOnSelectionState
SetColorsBasedOnSelectionState()
void GroupOptionButton< T >.SetColorsBasedOnSelectionState (Color pickedColor, Color unpickedColor, float opacityPicked, float opacityNotPicked) inline
Implements IGroupOptionButton.
     {
         _UseOverrideColors = true;
         _overridePickedColor = pickedColor;
         _overrideUnpickedColor = unpickedColor;
         _overrideOpacityPicked = opacityPicked;
         _overrideOpacityUnpicked = opacityNotPicked;
     }
References GroupOptionButton< T >._overrideOpacityPicked, GroupOptionButton< T >._overrideOpacityUnpicked, GroupOptionButton< T >._overridePickedColor, GroupOptionButton< T >._overrideUnpickedColor, and GroupOptionButton< T >._UseOverrideColors.
Referenced by CreativePowersHelper.CreateCategoryButton< T >(), UIResourcePackSelectionMenu.CreateOffsetButton(), UIResourcePackSelectionMenu.CreatePackToggleButton(), CreativePowersHelper.CreateSimpleButton(), and CreativePowersHelper.CreateToggleButton().