Terraria: GroupOptionButton.GroupOptionButton
GroupOptionButton()
GroupOptionButton< T >.GroupOptionButton (T option, LocalizedText title, LocalizedText description, Color textColor, string iconTexturePath, float textSize = 1f, float titleAlignmentX = 0.5f, float titleWidthReduction = 10f) inline
     {
         _borderColor = Color.White;
         _currentOption = option;
         _myOption = option;
         Description = description;
         Width = StyleDimension.FromPixels(44f);
         Height = StyleDimension.FromPixels(34f);
         _BasePanelTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/PanelGrayscale", (AssetRequestMode)1);
         _selectedBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", (AssetRequestMode)1);
         _hoveredBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelBorder", (AssetRequestMode)1);
         if (iconTexturePath != null)
         {
             _iconTexture = Main.Assets.Request<Texture2D>(iconTexturePath, (AssetRequestMode)1);
         }
         _color = Colors.InventoryDefaultColor;
         if (title != null)
         {
             UIText uIText = new UIText(title, textSize)
             {
                 HAlign = titleAlignmentX,
                 VAlign = 0.5f,
                 Width = StyleDimension.FromPixelsAndPercent(0f - titleWidthReduction, 1f),
                 Top = StyleDimension.FromPixels(0f)
             };
             uIText.TextColor = textColor;
             Append(uIText);
             _title = uIText;
         }
     }
References GroupOptionButton< T >._BasePanelTexture, GroupOptionButton< T >._borderColor, GroupOptionButton< T >._color, GroupOptionButton< T >._currentOption, GroupOptionButton< T >._hoveredBorderTexture, GroupOptionButton< T >._iconTexture, GroupOptionButton< T >._myOption, GroupOptionButton< T >._selectedBorderTexture, GroupOptionButton< T >._title, UIElement.Append(), Main.Assets, Color, GroupOptionButton< T >.Description, StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), UIElement.HAlign, UIElement.Height, Colors.InventoryDefaultColor, UIText.TextColor, UIElement.Top, UIElement.VAlign, and UIElement.Width.