Terraria: Terraria.DataStructures.SpriteDrawBuffer.CreateBuffers
CreateBuffers()
void Terraria.DataStructures.SpriteDrawBuffer.CreateBuffers () inline private
Definition at line 44 of file SpriteDrawBuffer.cs.
    {
        if (vertexBuffer != null)
        {
            vertexBuffer.Dispose();
        }
        vertexBuffer = new DynamicVertexBuffer(graphicsDevice, typeof(VertexPositionColorTexture), maxSprites * 4, BufferUsage.WriteOnly);
        if (indexBuffer != null)
        {
            indexBuffer.Dispose();
        }
        indexBuffer = new IndexBuffer(graphicsDevice, typeof(ushort), maxSprites * 6, BufferUsage.WriteOnly);
        indexBuffer.SetData(GenIndexBuffer(maxSprites));
        Array.Resize(ref vertices, maxSprites * 6);
        Array.Resize(ref textures, maxSprites);
    }
References Microsoft.Xna.Framework.Graphics.IndexBuffer.Dispose(), Microsoft.Xna.Framework.Graphics.VertexBuffer.Dispose(), Terraria.DataStructures.SpriteDrawBuffer.GenIndexBuffer(), Terraria.DataStructures.SpriteDrawBuffer.graphicsDevice, Terraria.DataStructures.SpriteDrawBuffer.indexBuffer, Terraria.DataStructures.SpriteDrawBuffer.maxSprites, Terraria.DataStructures.SpriteDrawBuffer.textures, Terraria.DataStructures.SpriteDrawBuffer.vertexBuffer, and Terraria.DataStructures.SpriteDrawBuffer.vertices.
Referenced by Terraria.DataStructures.SpriteDrawBuffer.SpriteDrawBuffer(), Terraria.DataStructures.SpriteDrawBuffer.CheckGraphicsDevice(), and Terraria.DataStructures.SpriteDrawBuffer.QueueSprite().