Terraria: System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindow
AdjustWindow()
void System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindow (int bytesConsumed, Http2Stream stream) inline
Definition at line 1495 of file Http2Connection.cs.
        {
            if (stream.ExpectResponseData)
            {
                if (WindowScalingEnabled)
                {
                    AdjustWindowDynamic(bytesConsumed, stream);
                }
                else
                {
                    AjdustWindowStatic(bytesConsumed, stream);
                }
            }
        }
References System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindowDynamic(), System.Net.Http.Http2Connection.Http2StreamWindowManager.AjdustWindowStatic(), System.stream, and System.Net.Http.Http2Connection.Http2StreamWindowManager.WindowScalingEnabled.
Referenced by System.Net.Http.Http2Connection.Http2Stream.CopyTo(), System.Net.Http.Http2Connection.Http2Stream.CopyToAsync(), System.Net.Http.Http2Connection.Http2Stream.ReadData(), and System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync().