Terraria: System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindowDynamic
AdjustWindowDynamic()
void System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindowDynamic (int bytesConsumed, Http2Stream stream) inline private
Definition at line 1523 of file Http2Connection.cs.
        {
            _deliveredBytes += bytesConsumed;
            if (_deliveredBytes < StreamWindowThreshold)
            {
                return;
            }
            int num = _deliveredBytes;
            long timestamp = Stopwatch.GetTimestamp();
            Http2Connection connection = stream.Connection;
            TimeSpan minRtt = connection._rttEstimator.MinRtt;
            if (minRtt > TimeSpan.Zero && _streamWindowSize < MaxStreamWindowSize)
            {
                TimeSpan timeSpan = StopwatchTicksToTimeSpan(timestamp - _lastWindowUpdate);
                if ((double)_deliveredBytes * (double)minRtt.Ticks > (double)(_streamWindowSize * timeSpan.Ticks) * WindowScaleThresholdMultiplier)
                {
                    int num2 = Math.Min(MaxStreamWindowSize, _streamWindowSize * 2);
                    num += num2 - _streamWindowSize;
                    _streamWindowSize = num2;
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        stream.Trace($"[FlowControl] Updated Stream Window. StreamWindowSize: {StreamWindowSize}, StreamWindowThreshold: {StreamWindowThreshold}", "AdjustWindowDynamic");
                    }
                    if (_streamWindowSize == MaxStreamWindowSize && System.Net.NetEventSource.Log.IsEnabled())
                    {
                        stream.Trace($"[FlowControl] StreamWindowSize reached the configured maximum of {MaxStreamWindowSize}.", "AdjustWindowDynamic");
                    }
                }
            }
            _deliveredBytes = 0;
            Task task = connection.SendWindowUpdateAsync(stream.StreamId, num);
            connection.LogExceptions(task);
            _lastWindowUpdate = timestamp;
        }
References System.Net.Http.Http2Connection.Http2StreamWindowManager._deliveredBytes, System.Net.Http.Http2Connection.Http2StreamWindowManager._lastWindowUpdate, System.Net.Http.Http2Connection._rttEstimator, System.Net.Http.Http2Connection.Http2StreamWindowManager._streamWindowSize, System.Diagnostics.Stopwatch.GetTimestamp(), System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionBase.LogExceptions(), System.Net.Http.Http2Connection.Http2StreamWindowManager.MaxStreamWindowSize, System.Math.Min(), System.Net.Http.Http2Connection.RttEstimator.MinRtt, System.Net.Http.Http2Connection.SendWindowUpdateAsync(), System.Net.Http.Http2Connection.Http2StreamWindowManager.StopwatchTicksToTimeSpan(), System.stream, System.Net.Http.Http2Connection.Http2StreamWindowManager.StreamWindowThreshold, System.task, System.Net.Http.Http2Connection.Http2StreamWindowManager.WindowScaleThresholdMultiplier, and System.TimeSpan.Zero.
Referenced by System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindow().