Terraria: System.Text.Encodings.Web.DefaultJavaScriptEncoder.EscaperImplementation.EncodeUtf8
EncodeUtf8()
override int System.Text.Encodings.Web.DefaultJavaScriptEncoder.EscaperImplementation.EncodeUtf8 (Rune value, Span< byte > destination) inline package
Definition at line 30 of file DefaultJavaScriptEncoder.cs.
        {
            if (_preescapedMap.TryLookup(value, out var value2))
            {
                if (SpanUtility.IsValidIndex(destination, 1))
                {
                    destination[0] = 92;
                    destination[1] = value2;
                    return 2;
                }
                return -1;
            }
            return TryEncodeScalarAsHex(this, value, destination);
            static int TryEncodeScalarAsHex(object @this, Rune value, Span<byte> destination)
            {
                if (value.IsBmp)
                {
                    if (SpanUtility.IsValidIndex(destination, 5))
                    {
                        destination[0] = 92;
                        destination[1] = 117;
                        System.HexConverter.ToBytesBuffer((byte)value.Value, destination, 4);
                        System.HexConverter.ToBytesBuffer((byte)((uint)value.Value >> 8), destination, 2);
                        return 6;
                    }
                }
                else
                {
                    UnicodeHelpers.GetUtf16SurrogatePairFromAstralScalarValue((uint)value.Value, out var highSurrogate, out var lowSurrogate);
                    if (SpanUtility.IsValidIndex(destination, 11))
                    {
                        destination[0] = 92;
                        destination[1] = 117;
                        System.HexConverter.ToBytesBuffer((byte)highSurrogate, destination, 4);
                        System.HexConverter.ToBytesBuffer((byte)((uint)highSurrogate >> 8), destination, 2);
                        destination[6] = 92;
                        destination[7] = 117;
                        System.HexConverter.ToBytesBuffer((byte)lowSurrogate, destination, 10);
                        System.HexConverter.ToBytesBuffer((byte)((uint)lowSurrogate >> 8), destination, 8);
                        return 12;
                    }
                }
                return -1;
            }
        }
References System.Text.Encodings.Web.DefaultJavaScriptEncoder.EscaperImplementation._preescapedMap, System.destination, System.Text.Unicode.UnicodeHelpers.GetUtf16SurrogatePairFromAstralScalarValue(), System.HexConverter.ToBytesBuffer(), System.Text.Encodings.Web.AsciiByteMap.TryLookup(), and System.Text.Encodings.Web.value.