Terraria: System.StartupHookProvider.ProcessStartupHooks
ProcessStartupHooks()
static void System.StartupHookProvider.ProcessStartupHooks () inline static private
Definition at line 30 of file StartupHookProvider.cs.
    {
        if (!IsSupported)
        {
            return;
        }
        if (EventSource.IsSupported)
        {
            RuntimeEventSource.Initialize();
        }
        if (!(AppContext.GetData("STARTUP_HOOKS") is string text))
        {
            return;
        }
        Span<char> span = stackalloc char[4]
        {
            Path.DirectorySeparatorChar,
            Path.AltDirectorySeparatorChar,
            ' ',
            ','
        };
        ReadOnlySpan<char> readOnlySpan = span;
        string[] array = text.Split(Path.PathSeparator);
        StartupHookNameOrPath[] array2 = new StartupHookNameOrPath[array.Length];
        for (int i = 0; i < array.Length; i++)
        {
            string text2 = array[i];
            if (string.IsNullOrEmpty(text2))
            {
                continue;
            }
            if (Path.IsPathFullyQualified(text2))
            {
                array2[i].Path = text2;
                continue;
            }
            for (int j = 0; j < readOnlySpan.Length; j++)
            {
                if (text2.Contains(readOnlySpan[j]))
                {
                    throw new ArgumentException(SR.Format(SR.Argument_InvalidStartupHookSimpleAssemblyName, text2));
                }
            }
            if (text2.EndsWith(".dll", StringComparison.OrdinalIgnoreCase))
            {
                throw new ArgumentException(SR.Format(SR.Argument_InvalidStartupHookSimpleAssemblyName, text2));
            }
            try
            {
                array2[i].AssemblyName = new AssemblyName(text2);
            }
            catch (Exception innerException)
            {
                throw new ArgumentException(SR.Format(SR.Argument_InvalidStartupHookSimpleAssemblyName, text2), innerException);
            }
        }
        StartupHookNameOrPath[] array3 = array2;
        foreach (StartupHookNameOrPath startupHook in array3)
        {
            CallStartupHook(startupHook);
        }
    }
References System.IO.Path.AltDirectorySeparatorChar, System.SR.Argument_InvalidStartupHookSimpleAssemblyName, System.array, System.StartupHookProvider.StartupHookNameOrPath.AssemblyName, System.StartupHookProvider.CallStartupHook(), System.IO.Path.DirectorySeparatorChar, System.SR.Format(), System.AppContext.GetData(), System.Diagnostics.Tracing.RuntimeEventSource.Initialize(), System.IO.Path.IsPathFullyQualified(), System.Diagnostics.Tracing.EventSource.IsSupported, System.StartupHookProvider.IsSupported, System.ReadOnlySpan< T >.Length, System.StartupHookProvider.StartupHookNameOrPath.Path, System.IO.Path.PathSeparator, and System.text.