Terraria: System.StartupHookProvider.CallStartupHook
CallStartupHook()
static void System.StartupHookProvider.CallStartupHook (StartupHookNameOrPath startupHook) inline static private
Definition at line 94 of file StartupHookProvider.cs.
    {
        Assembly assembly;
        try
        {
            if (startupHook.Path != null)
            {
                assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(startupHook.Path);
            }
            else
            {
                if (startupHook.AssemblyName == null)
                {
                    return;
                }
                assembly = AssemblyLoadContext.Default.LoadFromAssemblyName(startupHook.AssemblyName);
            }
        }
        catch (Exception innerException)
        {
            throw new ArgumentException(SR.Format(SR.Argument_StartupHookAssemblyLoadFailed, startupHook.Path ?? startupHook.AssemblyName.ToString()), innerException);
        }
        Type type = assembly.GetType("StartupHook", throwOnError: true);
        MethodInfo method = type.GetMethod("Initialize", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, null, Type.EmptyTypes, null);
        bool flag = false;
        if (method == null)
        {
            try
            {
                method = type.GetMethod("Initialize", BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
            }
            catch (AmbiguousMatchException)
            {
            }
            if (!(method != null))
            {
                throw new MissingMethodException("StartupHook", "Initialize");
            }
            flag = true;
        }
        else if (method.ReturnType != typeof(void))
        {
            flag = true;
        }
        if (flag)
        {
            throw new ArgumentException(SR.Format(SR.Argument_InvalidStartupHookSignature, "StartupHook" + Type.Delimiter + "Initialize", startupHook.Path ?? startupHook.AssemblyName.ToString()));
        }
        method.Invoke(null, null);
    }
References System.SR.Argument_InvalidStartupHookSignature, System.SR.Argument_StartupHookAssemblyLoadFailed, System.StartupHookProvider.StartupHookNameOrPath.AssemblyName, System.Runtime.Loader.AssemblyLoadContext.Default, System.Type.Delimiter, System.Type.EmptyTypes, System.SR.Format(), System.Reflection.Assembly.GetType(), System.Reflection.MethodBase.Invoke(), System.StartupHookProvider.StartupHookNameOrPath.Path, System.Reflection.MethodInfo.ReturnType, System.Reflection.AssemblyName.ToString(), and System.type.
Referenced by System.StartupHookProvider.ProcessStartupHooks().