Terraria: System.Net.Security.SslAuthenticationOptions.SslAuthenticationOptions
SslAuthenticationOptions() [2/3]
System.Net.Security.SslAuthenticationOptions.SslAuthenticationOptions (SslServerAuthenticationOptions sslServerAuthenticationOptions) inline package
Definition at line 71 of file SslAuthenticationOptions.cs.
    {
        AllowRenegotiation = sslServerAuthenticationOptions.AllowRenegotiation;
        ApplicationProtocols = sslServerAuthenticationOptions.ApplicationProtocols;
        CheckCertName = false;
        EnabledSslProtocols = FilterOutIncompatibleSslProtocols(sslServerAuthenticationOptions.EnabledSslProtocols);
        EncryptionPolicy = sslServerAuthenticationOptions.EncryptionPolicy;
        IsServer = true;
        RemoteCertRequired = sslServerAuthenticationOptions.ClientCertificateRequired;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"Server RemoteCertRequired: {RemoteCertRequired}.", ".ctor");
        }
        TargetHost = string.Empty;
        CipherSuitesPolicy = sslServerAuthenticationOptions.CipherSuitesPolicy;
        CertificateRevocationCheckMode = sslServerAuthenticationOptions.CertificateRevocationCheckMode;
        if (sslServerAuthenticationOptions.ServerCertificateContext != null)
        {
            CertificateContext = sslServerAuthenticationOptions.ServerCertificateContext;
        }
        else if (sslServerAuthenticationOptions.ServerCertificate != null)
        {
            if (sslServerAuthenticationOptions.ServerCertificate is X509Certificate2 { HasPrivateKey: not false } x509Certificate)
            {
                CertificateContext = SslStreamCertificateContext.Create(x509Certificate, null);
            }
            else
            {
                X509Certificate2 x509Certificate2 = SecureChannel.FindCertificateWithPrivateKey(this, isServer: true, sslServerAuthenticationOptions.ServerCertificate);
                if (x509Certificate2 == null)
                {
                    throw new AuthenticationException(System.SR.net_ssl_io_no_server_cert);
                }
                CertificateContext = SslStreamCertificateContext.Create(x509Certificate2);
            }
        }
        if (sslServerAuthenticationOptions.RemoteCertificateValidationCallback != null)
        {
            CertValidationDelegate = sslServerAuthenticationOptions.RemoteCertificateValidationCallback;
        }
    }
References System.Net.Security.SslAuthenticationOptions.AllowRenegotiation, System.Net.Security.SslAuthenticationOptions.ApplicationProtocols, System.Net.Security.SslAuthenticationOptions.CertificateContext, System.Net.Security.SslAuthenticationOptions.CertificateRevocationCheckMode, System.Net.Security.SslAuthenticationOptions.CertValidationDelegate, System.Net.Security.SslAuthenticationOptions.CheckCertName, System.Net.Security.SslStreamCertificateContext.Create(), System.Net.Security.SslAuthenticationOptions.EnabledSslProtocols, System.Net.Security.SslAuthenticationOptions.FilterOutIncompatibleSslProtocols(), System.Net.Security.SecureChannel.FindCertificateWithPrivateKey(), System.Net.NetEventSource.Info(), System.Net.Security.SslAuthenticationOptions.IsServer, System.Net.NetEventSource.Log, System.SR.net_ssl_io_no_server_cert, System.Net.Security.SslAuthenticationOptions.RemoteCertRequired, and System.Net.Security.SslAuthenticationOptions.TargetHost.