Terraria: System.Net.Security.SslAuthenticationOptions.UpdateOptions
UpdateOptions()
void System.Net.Security.SslAuthenticationOptions.UpdateOptions (SslServerAuthenticationOptions sslServerAuthenticationOptions) inline package
Definition at line 123 of file SslAuthenticationOptions.cs.
    {
        AllowRenegotiation = sslServerAuthenticationOptions.AllowRenegotiation;
        ApplicationProtocols = sslServerAuthenticationOptions.ApplicationProtocols;
        EnabledSslProtocols = FilterOutIncompatibleSslProtocols(sslServerAuthenticationOptions.EnabledSslProtocols);
        EncryptionPolicy = sslServerAuthenticationOptions.EncryptionPolicy;
        RemoteCertRequired = sslServerAuthenticationOptions.ClientCertificateRequired;
        CipherSuitesPolicy = sslServerAuthenticationOptions.CipherSuitesPolicy;
        CertificateRevocationCheckMode = sslServerAuthenticationOptions.CertificateRevocationCheckMode;
        if (sslServerAuthenticationOptions.ServerCertificateContext != null)
        {
            CertificateContext = sslServerAuthenticationOptions.ServerCertificateContext;
        }
        else if (sslServerAuthenticationOptions.ServerCertificate is X509Certificate2 { HasPrivateKey: not false } x509Certificate)
        {
            CertificateContext = SslStreamCertificateContext.Create(x509Certificate);
        }
        if (sslServerAuthenticationOptions.RemoteCertificateValidationCallback != null)
        {
            CertValidationDelegate = sslServerAuthenticationOptions.RemoteCertificateValidationCallback;
        }
    }
References System.Net.Security.SslAuthenticationOptions.AllowRenegotiation, System.Net.Security.SslAuthenticationOptions.ApplicationProtocols, System.Net.Security.SslAuthenticationOptions.CertificateContext, System.Net.Security.SslAuthenticationOptions.CertificateRevocationCheckMode, System.Net.Security.SslAuthenticationOptions.CertValidationDelegate, System.Net.Security.SslStreamCertificateContext.Create(), System.Net.Security.SslAuthenticationOptions.EnabledSslProtocols, System.Net.Security.SslAuthenticationOptions.FilterOutIncompatibleSslProtocols(), and System.Net.Security.SslAuthenticationOptions.RemoteCertRequired.
Referenced by System.Net.Security.SslStream.ReceiveBlobAsync< TIOAdapter >().