Terraria: System.Threading.LazyInitializer.EnsureInitializedCore<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T >
EnsureInitializedCore<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T >() [1/2]
static T System.Threading.LazyInitializer.EnsureInitializedCore<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T > ([AllowNull] ref T target, ref bool initialized, [NotNull] ref object syncLock) inline static private
Definition at line 50 of file LazyInitializer.cs.
    {
        lock (EnsureLockInitialized(ref syncLock))
        {
            if (!Volatile.Read(ref initialized))
            {
                try
                {
                    target = Activator.CreateInstance<T>();
                }
                catch (MissingMethodException)
                {
                    throw new MissingMemberException(SR.Lazy_CreateValue_NoParameterlessCtorForT);
                }
                Volatile.Write(ref initialized, value: true);
            }
        }
        return target;
    }
References System.Activator.CreateInstance(), System.Threading.LazyInitializer.EnsureLockInitialized(), System.SR.Lazy_CreateValue_NoParameterlessCtorForT, System.Threading.Volatile.Read(), System.value, and System.Threading.Volatile.Write().