Terraria: System.Linq.Parallel.ContainsSearchOperator.ContainsSearchOperatorEnumerator.MoveNext
MoveNext() [2/2]
override bool System.Linq.Parallel.ContainsSearchOperator< TInput >.ContainsSearchOperatorEnumerator< TKey >.MoveNext (ref bool currentElement, ref int currentKey) inline package
Definition at line 33 of file ContainsSearchOperator.cs.
        {
            if (_resultFoundFlag.Value)
            {
                return false;
            }
            TInput currentElement2 = default(TInput);
            TKey currentKey2 = default(TKey);
            if (_source.MoveNext(ref currentElement2, ref currentKey2))
            {
                currentElement = false;
                currentKey = _partitionIndex;
                int num = 0;
                do
                {
                    if ((num++ & 0x3F) == 0)
                    {
                        _cancellationToken.ThrowIfCancellationRequested();
                    }
                    if (_resultFoundFlag.Value)
                    {
                        return false;
                    }
                    if (_comparer.Equals(currentElement2, _searchValue))
                    {
                        _resultFoundFlag.Value = true;
                        currentElement = true;
                        break;
                    }
                }
                while (_source.MoveNext(ref currentElement2, ref currentKey2));
                return true;
            }
            return false;
        }
References System.Linq.Parallel.ContainsSearchOperator< TInput >.ContainsSearchOperatorEnumerator< TKey >._cancellationToken, System.Linq.Parallel.ContainsSearchOperator< TInput >.ContainsSearchOperatorEnumerator< TKey >._comparer, System.Linq.Parallel.ContainsSearchOperator< TInput >.ContainsSearchOperatorEnumerator< TKey >._partitionIndex, System.Linq.Parallel.ContainsSearchOperator< TInput >.ContainsSearchOperatorEnumerator< TKey >._resultFoundFlag, System.Linq.Parallel.ContainsSearchOperator< TInput >.ContainsSearchOperatorEnumerator< TKey >._searchValue, System.Linq.Parallel.ContainsSearchOperator< TInput >.ContainsSearchOperatorEnumerator< TKey >._source, System.Collections.Generic.IEqualityComparer< in T >.Equals(), System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.MoveNext(), System.Threading.CancellationToken.ThrowIfCancellationRequested(), and System.Linq.Parallel.Shared< T >.Value.