Terraria: System.Drawing.ColorConverterCommon.ConvertFromString
ConvertFromString() [2/2]
static Color System.Drawing.ColorConverterCommon.ConvertFromString (string strValue, CultureInfo culture) inline static
Definition at line 7 of file ColorConverterCommon.cs.
    {
        string text = strValue.Trim();
        if (text.Length == 0)
        {
            return Color.Empty;
        }
        if (ColorTable.TryGetNamedColor(text, out var result))
        {
            return result;
        }
        char c = culture.TextInfo.ListSeparator[0];
        if (!text.Contains(c))
        {
            if (text.Length >= 2 && (text[0] == '\'' || text[0] == '"') && text[0] == text[text.Length - 1])
            {
                string name = text.Substring(1, text.Length - 2);
                return Color.FromName(name);
            }
            if ((text.Length == 7 && text[0] == '#') || (text.Length == 8 && (text.StartsWith("0x") || text.StartsWith("0X"))) || (text.Length == 8 && (text.StartsWith("&h") || text.StartsWith("&H"))))
            {
                return PossibleKnownColor(Color.FromArgb(-16777216 | IntFromString(text, culture)));
            }
        }
        string[] array = text.Split(c);
        int[] array2 = new int[array.Length];
        for (int i = 0; i < array2.Length; i++)
        {
            array2[i] = IntFromString(array[i], culture);
        }
        return array2.Length switch
        {
            1 => PossibleKnownColor(Color.FromArgb(array2[0])),
            3 => PossibleKnownColor(Color.FromArgb(array2[0], array2[1], array2[2])),
            4 => PossibleKnownColor(Color.FromArgb(array2[0], array2[1], array2[2], array2[3])),
            _ => throw new ArgumentException(System.SR.Format(System.SR.InvalidColor, text)),
        };
    }
References System.array, System.culture, System.Drawing.Color.Empty, System.SR.Format(), System.Drawing.Color.FromArgb(), System.Drawing.Color.FromName(), System.Drawing.ColorConverterCommon.IntFromString(), System.SR.InvalidColor, System.Drawing.ColorConverterCommon.PossibleKnownColor(), System.text, and System.Drawing.ColorTable.TryGetNamedColor().