Terraria: System.Drawing.ColorConverterCommon.IntFromString
IntFromString() [2/6]
static int System.Drawing.ColorConverterCommon.IntFromString (string text, CultureInfo culture) inline static private
Definition at line 59 of file ColorConverterCommon.cs.
    {
        text = text.Trim();
        try
        {
            if (text[0] == '#')
            {
                return IntFromString(text.Substring(1), 16);
            }
            if (text.StartsWith("0x", StringComparison.OrdinalIgnoreCase) || text.StartsWith("&h", StringComparison.OrdinalIgnoreCase))
            {
                return IntFromString(text.Substring(2), 16);
            }
            NumberFormatInfo formatInfo = (NumberFormatInfo)culture.GetFormat(typeof(NumberFormatInfo));
            return IntFromString(text, formatInfo);
        }
        catch (Exception innerException)
        {
            throw new ArgumentException(System.SR.Format(System.SR.ConvertInvalidPrimitive, text, "Int32"), innerException);
        }
    }
References System.SR.ConvertInvalidPrimitive, System.culture, System.SR.Format(), System.Globalization.NumberFormatInfo.GetFormat(), System.Drawing.ColorConverterCommon.IntFromString(), and System.text.