Terraria: System.Data.RelatedView.GetParentValues
GetParentValues()
object[] System.Data.RelatedView.GetParentValues () inline private
Definition at line 39 of file RelatedView.cs.
    {
        if (_filterValues != null)
        {
            return _filterValues;
        }
        if (!_parentRowView.HasRecord())
        {
            return null;
        }
        return _parentKey.Value.GetKeyValues(_parentRowView.GetRecord());
    }
References System.Data.RelatedView._filterValues, System.Data.RelatedView._parentKey, System.Data.RelatedView._parentRowView, System.Data.DataKey.GetKeyValues(), System.Data.DataRowView.GetRecord(), and System.Data.DataRowView.HasRecord().
Referenced by System.Data.RelatedView.AddNew(), and System.Data.RelatedView.Invoke().