Terraria: UIIconTextButton.SetText
SetText()
void UIIconTextButton.SetText (LocalizedText text, float textSize, Color color) inline
     {
         if (_title != null)
         {
             _title.Remove();
         }
         UIText uIText = new UIText(text, textSize)
         {
             HAlign = 0f,
             VAlign = 0.5f,
             Top = StyleDimension.FromPixels(0f),
             Left = StyleDimension.FromPixelsAndPercent(10f, 0f),
             IgnoresMouseInteraction = true
         };
         uIText.TextColor = color;
         Append(uIText);
         _title = uIText;
         if (_iconTexture != null)
         {
             Width.Set(_title.GetDimensions().Width + (float)_iconTexture.Width() + 26f, 0f);
             Height.Set(Math.Max(_title.GetDimensions().Height, _iconTexture.Height()) + 16f, 0f);
         }
     }
References _iconTexture, _title, UIElement.Append(), StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), UIElement.GetDimensions(), UIElement.HAlign, CalculatedStyle.Height, UIElement.Height, UIElement.IgnoresMouseInteraction, UIElement.Left, UIElement.Remove(), StyleDimension.Set(), UIText.TextColor, UIElement.Top, UIElement.VAlign, CalculatedStyle.Width, and UIElement.Width.
Referenced by UIIconTextButton().