Terraria: UIIconTextButton.UIIconTextButton
UIIconTextButton()
UIIconTextButton.UIIconTextButton (LocalizedText title, Color textColor, string iconTexturePath, float textSize = 1f, float titleAlignmentX = 0.5f, float titleWidthReduction = 10f) inline
     {
         Width = StyleDimension.FromPixels(44f);
         Height = StyleDimension.FromPixels(34f);
         _hoverColor = Color.White;
         _BasePanelTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/PanelGrayscale", (AssetRequestMode)1);
         _hoveredTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", (AssetRequestMode)1);
         if (iconTexturePath != null)
         {
             _iconTexture = Main.Assets.Request<Texture2D>(iconTexturePath, (AssetRequestMode)1);
         }
         SetColor(Color.Lerp(Color.Black, Colors.InventoryDefaultColor, FadeFromBlack), 1f);
         if (title != null)
         {
             SetText(title, textSize, textColor);
         }
     }
References _BasePanelTexture, _hoverColor, _hoveredTexture, _iconTexture, Main.Assets, Color, FadeFromBlack, StyleDimension.FromPixels(), UIElement.Height, Colors.InventoryDefaultColor, SetColor(), SetText(), and UIElement.Width.