Terraria: System.ComponentModel.TypeDescriptor.AttributeProvider.AttributeTypeDescriptor.GetAttributes
GetAttributes()
override AttributeCollection System.ComponentModel.TypeDescriptor.AttributeProvider.AttributeTypeDescriptor.GetAttributes () inline virtual
Reimplemented from System.ComponentModel.CustomTypeDescriptor.
Definition at line 133 of file TypeDescriptor.cs.
            {
                Attribute[] array = null;
                AttributeCollection attributes = base.GetAttributes();
                Attribute[] attributeArray = _attributeArray;
                Attribute[] array2 = new Attribute[attributes.Count + attributeArray.Length];
                int count = attributes.Count;
                attributes.CopyTo(array2, 0);
                for (int i = 0; i < attributeArray.Length; i++)
                {
                    bool flag = false;
                    for (int j = 0; j < attributes.Count; j++)
                    {
                        if (array2[j].TypeId.Equals(attributeArray[i].TypeId))
{
                            flag = true;
                            array2[j] = attributeArray[i];
                            break;
                        }
                    }
                    if (!flag)
                    {
                        array2[count++] = attributeArray[i];
                    }
                }
                if (count < array2.Length)
                {
                    array = new Attribute[count];
                    Array.Copy(array2, array, count);
                }
                else
                {
                    array = array2;
                }
                return new AttributeCollection(array);
            }
References System.ComponentModel.TypeDescriptor.AttributeProvider.AttributeTypeDescriptor._attributeArray, System.array, System.Array.Copy(), System.ComponentModel.AttributeCollection.CopyTo(), System.ComponentModel.AttributeCollection.Count, System.count, System.Attribute.Equals(), and System.Attribute.TypeId.