Terraria: UIWorldLoad.Update
Update()
override void UIWorldLoad.Update (GameTime gameTime) inline virtual
Reimplemented from UIElement.
     {
         _progressBar.Top.Pixels = MathHelper.Lerp(270f, 370f, Utils.GetLerpValue(600f, 700f, Main.screenHeight, clamped: true));
         _progressMessage.Top.Pixels = _progressBar.Top.Pixels - 70f;
         _progressBar.Recalculate();
         _progressMessage.Recalculate();
         base.Update(gameTime);
     }
References _progressBar, _progressMessage, Utils.GetLerpValue(), StyleDimension.Pixels, UIGenProgressBar.Recalculate(), UIElement.Recalculate(), Main.screenHeight, and UIElement.Top.