Terraria: System.Threading.TimerQueueTimer.TimerQueueTimer
TimerQueueTimer()
System.Threading.TimerQueueTimer.TimerQueueTimer (TimerCallback timerCallback, object state, uint dueTime, uint period, bool flowExecutionContext) inline package
Definition at line 114 of file TimerQueueTimer.cs.
    {
        _timerCallback = timerCallback;
        _state = state;
        _dueTime = uint.MaxValue;
        _period = uint.MaxValue;
        if (flowExecutionContext)
        {
            _executionContext = ExecutionContext.Capture();
        }
        _associatedTimerQueue = TimerQueue.Instances[Thread.GetCurrentProcessorId() % TimerQueue.Instances.Length];
        if (dueTime != uint.MaxValue)
        {
            Change(dueTime, period);
        }
    }
References System.Threading.TimerQueueTimer._associatedTimerQueue, System.Threading.TimerQueueTimer._dueTime, System.Threading.TimerQueueTimer._executionContext, System.Threading.TimerQueueTimer._period, System.Threading.TimerQueueTimer._state, System.Threading.TimerQueueTimer._timerCallback, System.Threading.ExecutionContext.Capture(), System.Threading.TimerQueueTimer.Change(), System.Threading.Thread.GetCurrentProcessorId(), System.Threading.TimerQueue.Instances, and System.state.