Terraria: System.Threading.TimerQueueTimer.Change
Change()
bool System.Threading.TimerQueueTimer.Change (uint dueTime, uint period) inline package
Definition at line 131 of file TimerQueueTimer.cs.
    {
        lock (_associatedTimerQueue)
        {
            if (_canceled)
            {
                throw new ObjectDisposedException(null, SR.ObjectDisposed_Generic);
            }
            _period = period;
            if (dueTime == uint.MaxValue)
            {
                _associatedTimerQueue.DeleteTimer(this);
                return true;
            }
            if (FrameworkEventSource.Log.IsEnabled(EventLevel.Informational, (EventKeywords)16L))
            {
                FrameworkEventSource.Log.ThreadTransferSendObj(this, 1, string.Empty, multiDequeues: true, (int)dueTime, (int)period);
            }
            return _associatedTimerQueue.UpdateTimer(this, dueTime, period);
        }
    }
References System.Threading.TimerQueueTimer._associatedTimerQueue, System.Threading.TimerQueueTimer._canceled, System.Threading.TimerQueueTimer._period, System.Threading.TimerQueue.DeleteTimer(), System.L, System.Diagnostics.Tracing.FrameworkEventSource.Log, System.SR.ObjectDisposed_Generic, and System.Threading.TimerQueue.UpdateTimer().
Referenced by System.Threading.TimerQueueTimer.TimerQueueTimer(), System.Threading.Timer.Change(), System.Threading.Timer.Change(), and System.Threading.Timer.Change().