Terraria: System.Threading.TimerQueueTimer.CallCallback
CallCallback()
void System.Threading.TimerQueueTimer.CallCallback (bool isThreadPool) inline package
Definition at line 267 of file TimerQueueTimer.cs.
    {
        if (FrameworkEventSource.Log.IsEnabled(EventLevel.Informational, (EventKeywords)16L))
        {
            FrameworkEventSource.Log.ThreadTransferReceiveObj(this, 1, string.Empty);
        }
        ExecutionContext executionContext = _executionContext;
        if (executionContext == null)
        {
            _timerCallback(_state);
        }
        else if (isThreadPool)
        {
            ExecutionContext.RunFromThreadPoolDispatchLoop(Thread.CurrentThread, executionContext, s_callCallbackInContext, this);
        }
        else
        {
            ExecutionContext.RunInternal(executionContext, s_callCallbackInContext, this);
        }
    }
References System.Threading.TimerQueueTimer._executionContext, System.Threading.TimerQueueTimer._state, System.Threading.TimerQueueTimer._timerCallback, System.Threading.Thread.CurrentThread, System.L, System.Diagnostics.Tracing.FrameworkEventSource.Log, System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(), System.Threading.ExecutionContext.RunInternal(), and System.Threading.TimerQueueTimer.s_callCallbackInContext.
Referenced by System.Threading.TimerQueueTimer.Fire().