Terraria: System.Threading.TimerQueueTimer.CloseAsync
CloseAsync()
ValueTask System.Threading.TimerQueueTimer.CloseAsync () inline
Definition at line 191 of file TimerQueueTimer.cs.
    {
        lock (_associatedTimerQueue)
        {
            object notifyWhenNoCallbacksRunning = _notifyWhenNoCallbacksRunning;
            if (_canceled)
            {
                if (notifyWhenNoCallbacksRunning is WaitHandle)
                {
                    InvalidOperationException ex = new InvalidOperationException(SR.InvalidOperation_TimerAlreadyClosed);
                    ex.SetCurrentStackTrace();
                    return ValueTask.FromException(ex);
                }
            }
            else
            {
                _canceled = true;
                _associatedTimerQueue.DeleteTimer(this);
            }
            if (_callbacksRunning == 0)
            {
                return default(ValueTask);
            }
            if (notifyWhenNoCallbacksRunning == null)
            {
                return new ValueTask((Task)(_notifyWhenNoCallbacksRunning = new Task(null, TaskCreationOptions.RunContinuationsAsynchronously, promiseStyle: true)));
            }
            return new ValueTask((Task)notifyWhenNoCallbacksRunning);
        }
    }
References System.Threading.TimerQueueTimer._associatedTimerQueue, System.Threading.TimerQueueTimer._callbacksRunning, System.Threading.TimerQueueTimer._canceled, System.Threading.TimerQueueTimer._notifyWhenNoCallbacksRunning, System.Threading.TimerQueue.DeleteTimer(), System.Threading.Tasks.ValueTask< TResult >.FromException(), System.SR.InvalidOperation_TimerAlreadyClosed, and System.Exception.SetCurrentStackTrace().
Referenced by System.Threading.TimerHolder.CloseAsync().