Terraria: System.Threading.TimerQueueTimer.Fire
Fire()
void System.Threading.TimerQueueTimer.Fire (bool isThreadPool = false) inline package
Definition at line 227 of file TimerQueueTimer.cs.
    {
        bool flag = false;
        lock (_associatedTimerQueue)
        {
            flag = _canceled;
            if (!flag)
            {
                _callbacksRunning++;
            }
        }
        if (!flag)
        {
            CallCallback(isThreadPool);
            bool flag2;
            lock (_associatedTimerQueue)
            {
                _callbacksRunning--;
                flag2 = _canceled && _callbacksRunning == 0 && _notifyWhenNoCallbacksRunning != null;
            }
            if (flag2)
            {
                SignalNoCallbacksRunning();
            }
        }
    }
References System.Threading.TimerQueueTimer._associatedTimerQueue, System.Threading.TimerQueueTimer._callbacksRunning, System.Threading.TimerQueueTimer._canceled, System.Threading.TimerQueueTimer._notifyWhenNoCallbacksRunning, System.Threading.TimerQueueTimer.CallCallback(), and System.Threading.TimerQueueTimer.SignalNoCallbacksRunning().
Referenced by System.Threading.TimerQueueTimer.Execute().