Terraria: System.Threading.TimerQueueTimer.Close
Close() [1/2]
void System.Threading.TimerQueueTimer.Close () inline
Definition at line 153 of file TimerQueueTimer.cs.
    {
        lock (_associatedTimerQueue)
        {
            if (!_canceled)
            {
                _canceled = true;
                _associatedTimerQueue.DeleteTimer(this);
            }
        }
    }
References System.Threading.TimerQueueTimer._associatedTimerQueue, System.Threading.TimerQueueTimer._canceled, and System.Threading.TimerQueue.DeleteTimer().
Referenced by System.Threading.Tasks.Task< TResult >.DelayPromise.DelayPromise(), System.Threading.TimerHolder.~TimerHolder(), System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >.Cleanup(), System.Threading.Tasks.Task< TResult >.DelayPromise.Cleanup(), System.Threading.TimerHolder.Close(), System.Threading.TimerHolder.Close(), and System.Threading.PeriodicTimer.Dispose().