Terraria: System.ComponentModel.DateTimeOffsetConverter.ConvertFrom
ConvertFrom() [1/2]
override? object System.ComponentModel.DateTimeOffsetConverter.ConvertFrom (ITypeDescriptorContext? context, CultureInfo? culture, object value) inline virtual
Reimplemented from System.ComponentModel.TypeConverter.
Definition at line 26 of file DateTimeOffsetConverter.cs.
    {
        if (value is string text)
        {
            string text2 = text.Trim();
            if (text2.Length == 0)
            {
                return DateTimeOffset.MinValue;
            }
            try
            {
                DateTimeFormatInfo dateTimeFormatInfo = null;
                if (culture != null)
                {
                    dateTimeFormatInfo = (DateTimeFormatInfo)culture.GetFormat(typeof(DateTimeFormatInfo));
                }
                if (dateTimeFormatInfo != null)
                {
                    return DateTimeOffset.Parse(text2, dateTimeFormatInfo);
                }
                return DateTimeOffset.Parse(text2, culture);
            }
            catch (FormatException innerException)
            {
                throw new FormatException(System.SR.Format(System.SR.ConvertInvalidPrimitive, (string)value, "DateTimeOffset"), innerException);
            }
        }
        return base.ConvertFrom(context, culture, value);
    }
References System.SR.ConvertInvalidPrimitive, System.culture, System.SR.Format(), System.IFormatProvider.GetFormat(), System.DateTimeOffset.MinValue, System.DateTimeOffset.Parse(), System.text, and System.value.