Terraria: Terraria.WorldBuilding.WorldUtils.WireLine
WireLine()
static void Terraria.WorldBuilding.WorldUtils.WireLine (Point start, Point end) inline static
Definition at line 81 of file WorldUtils.cs.
    {
        Point point = start;
        Point point2 = end;
        if (end.X < start.X)
        {
            Utils.Swap(ref end.X, ref start.X);
        }
        if (end.Y < start.Y)
        {
            Utils.Swap(ref end.Y, ref start.Y);
        }
        for (int i = start.X; i <= end.X; i++)
        {
            WorldGen.PlaceWire(i, point.Y);
        }
        for (int j = start.Y; j <= end.Y; j++)
        {
            WorldGen.PlaceWire(point2.X, j);
        }
    }
References Terraria.WorldGen.PlaceWire(), System.start, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), and Terraria.WorldGen.PlaceStatueTrap().