Terraria: Terraria.WorldBuilding.WorldUtils.DebugRegen
DebugRegen()
static void Terraria.WorldBuilding.WorldUtils.DebugRegen () inline static
    {
        WorldGen.clearWorld();
        WorldGen.GenerateWorld(Main.ActiveWorldFileData.Seed);
        Main.NewText("World Regen Complete.");
    }
References Terraria.Main.ActiveWorldFileData, Terraria.WorldGen.clearWorld(), Terraria.WorldGen.GenerateWorld(), and Terraria.Main.NewText().