Terraria: Terraria.WorldBuilding.WorldUtils.ClampToWorld
ClampToWorld()
static Rectangle Terraria.WorldBuilding.WorldUtils.ClampToWorld (Rectangle tileRectangle) inline static
Definition at line 8 of file WorldUtils.cs.
    {
        int num = Math.Max(0, Math.Min(tileRectangle.Left, Main.maxTilesX));
        int num2 = Math.Max(0, Math.Min(tileRectangle.Top, Main.maxTilesY));
        int num3 = Math.Max(0, Math.Min(tileRectangle.Right, Main.maxTilesX));
        int num4 = Math.Max(0, Math.Min(tileRectangle.Bottom, Main.maxTilesY));
        return new Rectangle(num, num2, num3 - num, num4 - num2);
    }
References Microsoft.Xna.Framework.Rectangle.Bottom, Microsoft.Xna.Framework.Rectangle.Left, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Microsoft.Xna.Framework.Rectangle.Right, and Microsoft.Xna.Framework.Rectangle.Top.
Referenced by Terraria.SceneMetrics.ScanAndExportToMain().