using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Xml;

[assembly: CLSCompliant(true)]
[assembly: AssemblyDefaultAlias("System.Xml.XmlDocument")]
[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: AssemblyMetadata("Serviceable", "True")]
[assembly: AssemblyMetadata("PreferInbox", "True")]
[assembly: AssemblyMetadata("IsTrimmable", "True")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription("System.Xml.XmlDocument")]
[assembly: AssemblyFileVersion("6.0.21.52210")]
[assembly: AssemblyInformationalVersion("6.0.0+4822e3c3aa77eb82b2fb33c9321f923cf11ddde6")]
[assembly: AssemblyProduct("Microsoft® .NET")]
[assembly: AssemblyTitle("System.Xml.XmlDocument")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/runtime")]
[assembly: AssemblyVersion("6.0.0.0")]
[assembly: TypeForwardedTo(typeof(XmlAttribute))]
[assembly: TypeForwardedTo(typeof(XmlAttributeCollection))]
[assembly: TypeForwardedTo(typeof(XmlCDataSection))]
[assembly: TypeForwardedTo(typeof(XmlCharacterData))]
[assembly: TypeForwardedTo(typeof(XmlComment))]
[assembly: TypeForwardedTo(typeof(XmlDeclaration))]
[assembly: TypeForwardedTo(typeof(XmlDocument))]
[assembly: TypeForwardedTo(typeof(XmlDocumentFragment))]
[assembly: TypeForwardedTo(typeof(XmlElement))]
[assembly: TypeForwardedTo(typeof(XmlImplementation))]
[assembly: TypeForwardedTo(typeof(XmlLinkedNode))]
[assembly: TypeForwardedTo(typeof(XmlNamedNodeMap))]
[assembly: TypeForwardedTo(typeof(XmlNode))]
[assembly: TypeForwardedTo(typeof(XmlNodeChangedAction))]
[assembly: TypeForwardedTo(typeof(XmlNodeChangedEventArgs))]
[assembly: TypeForwardedTo(typeof(XmlNodeChangedEventHandler))]
[assembly: TypeForwardedTo(typeof(XmlNodeList))]
[assembly: TypeForwardedTo(typeof(XmlProcessingInstruction))]
[assembly: TypeForwardedTo(typeof(XmlSignificantWhitespace))]
[assembly: TypeForwardedTo(typeof(XmlText))]
[assembly: TypeForwardedTo(typeof(XmlWhitespace))]
[module: SkipLocalsInit]
