Terraria: System.Reflection.Metadata.Ecma335.MetadataReaderExtensions.ResolveSignatureTypeKind
ResolveSignatureTypeKind()
static SignatureTypeKind System.Reflection.Metadata.Ecma335.MetadataReaderExtensions.ResolveSignatureTypeKind (this MetadataReader reader, EntityHandle typeHandle, byte rawTypeKind) inline static
Definition at line 261 of file MetadataReaderExtensions.cs.
    {
        if (reader == null)
        {
            throw new ArgumentNullException("reader");
        }
        SignatureTypeKind signatureTypeKind = (SignatureTypeKind)rawTypeKind;
        switch (signatureTypeKind)
        {
        case SignatureTypeKind.Unknown:
            return SignatureTypeKind.Unknown;
        default:
            throw new ArgumentOutOfRangeException("rawTypeKind");
        case SignatureTypeKind.ValueType:
        case SignatureTypeKind.Class:
            switch (typeHandle.Kind)
            {
            case HandleKind.TypeDefinition:
                return signatureTypeKind;
            case HandleKind.TypeReference:
            {
                TypeRefSignatureTreatment signatureTreatment = reader.GetTypeReference((TypeReferenceHandle)typeHandle).SignatureTreatment;
                return signatureTreatment switch
                {
                    TypeRefSignatureTreatment.ProjectedToClass => SignatureTypeKind.Class,
                    TypeRefSignatureTreatment.ProjectedToValueType => SignatureTypeKind.ValueType,
                    TypeRefSignatureTreatment.None => signatureTypeKind,
                    _ => throw ExceptionUtilities.UnexpectedValue(signatureTreatment),
                };
            }
            case HandleKind.TypeSpecification:
                return SignatureTypeKind.Unknown;
            default:
                throw new ArgumentOutOfRangeException("typeHandle", System.SR.Format(System.SR.UnexpectedHandleKind, typeHandle.Kind));
            }
        }
    }
References System.SR.Format(), System.Reflection.Metadata.MetadataReader.GetTypeReference(), System.Reflection.Metadata.TypeReference.SignatureTreatment, System.SR.UnexpectedHandleKind, and System.Reflection.Internal.ExceptionUtilities.UnexpectedValue().