Terraria: Terraria.GameContent.Tile_Entities.TEWeaponsRack.OnPlayerInteraction
OnPlayerInteraction()
static void Terraria.GameContent.Tile_Entities.TEWeaponsRack.OnPlayerInteraction (Player player, int clickX, int clickY) inline static
Definition at line 209 of file TEWeaponsRack.cs.
    {
        if (FitsWeaponFrame(player.inventory[player.selectedItem]) && !player.inventory[player.selectedItem].favorited)
        {
            player.GamepadEnableGrappleCooldown();
            PlaceItemInFrame(player, clickX, clickY);
            Recipe.FindRecipes();
            return;
        }
        int num = clickX;
        int num2 = clickY;
        num -= Main.tile[num, num2].frameX % 54 / 18;
        num2 -= Main.tile[num, num2].frameY % 54 / 18;
        int num3 = Find(num, num2);
        if (num3 != -1 && ((TEWeaponsRack)TileEntity.ByID[num3]).item.stack > 0)
        {
            player.GamepadEnableGrappleCooldown();
            WorldGen.KillTile(num, num2, fail: true);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(17, -1, -1, null, 0, num, num2, 1f);
            }
        }
    }
References Terraria.DataStructures.TileEntity.ByID, Terraria.Item.favorited, Terraria.GameContent.Tile_Entities.TEWeaponsRack.Find(), Terraria.Recipe.FindRecipes(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.FitsWeaponFrame(), Terraria.Player.GamepadEnableGrappleCooldown(), Terraria.Player.inventory, Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame(), Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), and Terraria.Main.tile.
Referenced by Terraria.Player.TileInteractionsUse().