Terraria: Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame
PlaceItemInFrame()
static void Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame (Player player, int x, int y) inline static private
    {
        if (!player.ItemTimeIsZero)
        {
            return;
        }
        x -= Main.tile[x, y].frameX % 54 / 18;
        y -= Main.tile[x, y].frameY % 54 / 18;
        int num = Find(x, y);
        if (num == -1)
        {
            return;
        }
        if (((TEWeaponsRack)TileEntity.ByID[num]).item.stack > 0)
        {
            WorldGen.KillTile(x, y, fail: true);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(17, -1, -1, null, 0, Player.tileTargetX, y, 1f);
            }
        }
        if (Main.netMode == 1)
        {
            NetMessage.SendData(123, -1, -1, null, x, y, player.selectedItem, player.whoAmI, 1);
        }
        else
        {
            TryPlacing(x, y, player.inventory[player.selectedItem].netID, player.inventory[player.selectedItem].prefix, 1);
        }
        player.inventory[player.selectedItem].stack--;
        if (player.inventory[player.selectedItem].stack <= 0)
        {
            player.inventory[player.selectedItem].SetDefaults();
            Main.mouseItem.SetDefaults();
        }
        if (player.selectedItem == 58)
        {
            Main.mouseItem = player.inventory[player.selectedItem].Clone();
        }
        player.releaseUseItem = false;
        player.mouseInterface = true;
        player.PlayDroppedItemAnimation(20);
        WorldGen.RangeFrame(x, y, x + 3, y + 3);
    }
References Terraria.DataStructures.TileEntity.ByID, Terraria.Item.Clone(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Find(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Player.inventory, Terraria.Player.ItemTimeIsZero, Terraria.WorldGen.KillTile(), Terraria.Main.mouseItem, Terraria.Item.netID, Terraria.Main.netMode, Terraria.Player.PlayDroppedItemAnimation(), Terraria.Item.prefix, Terraria.WorldGen.RangeFrame(), Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Main.tile, Terraria.Player.tileTargetX, Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing(), and Terraria.Entity.whoAmI.
Referenced by Terraria.GameContent.Tile_Entities.TEWeaponsRack.OnPlayerInteraction().