Terraria: System.Security.Cryptography.RC2CryptoServiceProvider.CreateTransform
CreateTransform()
ICryptoTransform System.Security.Cryptography.RC2CryptoServiceProvider.CreateTransform (byte[] rgbKey, byte[] rgbIV, bool encrypting) inline private
Definition at line 72 of file RC2CryptoServiceProvider.cs.
    {
        long num = (long)rgbKey.Length * 8L;
        if (num > int.MaxValue || !((int)num).IsLegalSize(LegalKeySizes))
        {
            throw new ArgumentException(System.SR.Cryptography_InvalidKeySize, "rgbKey");
        }
        if (rgbIV == null)
        {
            if (Mode.UsesIv())
            {
                rgbIV = RandomNumberGenerator.GetBytes(8);
            }
        }
        else if (rgbIV.Length < 8)
        {
            throw new CryptographicException(System.SR.Cryptography_InvalidIVSize);
        }
        int effectiveKeyLength = (int)((EffectiveKeySizeValue == 0) ? num : EffectiveKeySize);
        Internal.Cryptography.BasicSymmetricCipher cipher = new BasicSymmetricCipherCsp(26114, Mode, BlockSize / 8, rgbKey, effectiveKeyLength, !UseSalt, rgbIV, encrypting, 0, 0);
        return Internal.Cryptography.UniversalCryptoTransform.Create(Padding, cipher, encrypting);
    }
References System.Security.Cryptography.SymmetricAlgorithm.BlockSize, Internal.Cryptography.UniversalCryptoTransform.Create(), System.SR.Cryptography_InvalidIVSize, System.SR.Cryptography_InvalidKeySize, System.Security.Cryptography.RC2CryptoServiceProvider.EffectiveKeySize, System.Security.Cryptography.RC2.EffectiveKeySizeValue, System.Security.Cryptography.RandomNumberGenerator.GetBytes(), System.L, System.Security.Cryptography.SymmetricAlgorithm.LegalKeySizes, System.Security.Cryptography.SymmetricAlgorithm.Padding, and System.Security.Cryptography.RC2CryptoServiceProvider.UseSalt.
Referenced by System.Security.Cryptography.RC2CryptoServiceProvider.CreateDecryptor(), and System.Security.Cryptography.RC2CryptoServiceProvider.CreateEncryptor().