Terraria: System.Security.Cryptography.Asn1.SpecifiedECDomain.DecodeCore
DecodeCore() [1/2]
static void System.Security.Cryptography.Asn1.SpecifiedECDomain.DecodeCore (ref AsnValueReader reader, Asn1Tag expectedTag, ReadOnlyMemory< byte > rebind, out SpecifiedECDomain decoded) inline static private
Definition at line 69 of file SpecifiedECDomain.cs.
    {
        decoded = default(SpecifiedECDomain);
        AsnValueReader reader2 = reader.ReadSequence(expectedTag);
        ReadOnlySpan<byte> span = rebind.Span;
        if (!reader2.TryReadInt32(out decoded.Version))
        {
            reader2.ThrowIfNotEmpty();
        }
        FieldID.Decode(ref reader2, rebind, out decoded.FieldID);
        CurveAsn.Decode(ref reader2, rebind, out decoded.Curve);
        int elementOffset;
        if (reader2.TryReadPrimitiveOctetString(out var value))
        {
            decoded.Base = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
        }
        else
        {
            decoded.Base = reader2.ReadOctetString();
        }
        value = reader2.ReadIntegerBytes();
        decoded.Order = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
        if (reader2.HasData && reader2.PeekTag().HasSameClassAndValue(Asn1Tag.Integer))
        {
            value = reader2.ReadIntegerBytes();
            decoded.Cofactor = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
        }
        if (reader2.HasData && reader2.PeekTag().HasSameClassAndValue(Asn1Tag.ObjectIdentifier))
        {
            decoded.Hash = reader2.ReadObjectIdentifier();
        }
        reader2.ThrowIfNotEmpty();
    }
References System.Security.Cryptography.Asn1.CurveAsn.Decode(), System.Security.Cryptography.Asn1.FieldID.Decode(), System.Formats.Asn1.AsnValueReader.HasData, System.Formats.Asn1.Asn1Tag.HasSameClassAndValue(), System.Formats.Asn1.Asn1Tag.Integer, System.Formats.Asn1.Asn1Tag.ObjectIdentifier, System.Formats.Asn1.AsnValueReader.PeekTag(), System.Formats.Asn1.AsnValueReader.ReadIntegerBytes(), System.Formats.Asn1.AsnValueReader.ReadObjectIdentifier(), System.Formats.Asn1.AsnValueReader.ReadOctetString(), System.Formats.Asn1.AsnValueReader.ReadSequence(), System.ReadOnlyMemory< T >.Slice(), System.ReadOnlyMemory< T >.Span, System.Formats.Asn1.AsnValueReader.ThrowIfNotEmpty(), System.Formats.Asn1.AsnValueReader.TryReadInt32(), System.Formats.Asn1.AsnValueReader.TryReadPrimitiveOctetString(), and System.value.
Referenced by System.Security.Cryptography.Asn1.SpecifiedECDomain.Decode(), and System.Security.Cryptography.Asn1.SpecifiedECDomain.Decode().