Terraria: System.Xml.Xsl.Runtime.XsltLibrary.RelationalOperator
RelationalOperator()
bool System.Xml.Xsl.Runtime.XsltLibrary.RelationalOperator (double opCode, IList< XPathItem > left, IList< XPathItem > right) inline
Definition at line 350 of file XsltLibrary.cs.
    {
        ComparisonOperator op = (ComparisonOperator)opCode;
        if (IsNodeSetOrRtf(left))
        {
            if (IsNodeSetOrRtf(right))
            {
                return CompareNodeSetAndNodeSet(op, ToNodeSetOrRtf(left), ToNodeSetOrRtf(right), TypeCode.Double);
            }
            XPathItem xPathItem = right[0];
            return CompareNodeSetAndValue(op, ToNodeSetOrRtf(left), xPathItem, WeakestTypeCode(GetTypeCode(xPathItem), TypeCode.Double));
        }
        if (IsNodeSetOrRtf(right))
        {
            XPathItem xPathItem2 = left[0];
            op = InvertOperator(op);
            return CompareNodeSetAndValue(op, ToNodeSetOrRtf(right), xPathItem2, WeakestTypeCode(GetTypeCode(xPathItem2), TypeCode.Double));
        }
        XPathItem left2 = left[0];
        XPathItem right2 = right[0];
        return CompareValues(op, left2, right2, TypeCode.Double);
    }
References System.Xml.Xsl.Runtime.XsltLibrary.CompareNodeSetAndNodeSet(), System.Xml.Xsl.Runtime.XsltLibrary.CompareNodeSetAndValue(), System.Xml.Xsl.Runtime.XsltLibrary.CompareValues(), System.Xml.Xsl.Runtime.XsltLibrary.GetTypeCode(), System.Xml.Xsl.Runtime.XsltLibrary.InvertOperator(), System.Xml.Xsl.Runtime.XsltLibrary.IsNodeSetOrRtf(), System.Xml.Xsl.Runtime.XsltLibrary.ToNodeSetOrRtf(), and System.Xml.Xsl.Runtime.XsltLibrary.WeakestTypeCode().