Terraria: System.Xml.Xsl.Runtime.XsltLibrary.CompareNodeSetAndValue
CompareNodeSetAndValue()
static bool System.Xml.Xsl.Runtime.XsltLibrary.CompareNodeSetAndValue (ComparisonOperator op, IList< XPathNavigator > nodeset, XPathItem val, TypeCode compType) inline static private
Definition at line 282 of file XsltLibrary.cs.
    {
        if (compType == TypeCode.Boolean)
        {
            return CompareNumbers(op, (nodeset.Count != 0) ? 1 : 0, XsltConvert.ToBoolean(val) ? 1 : 0);
        }
        int count = nodeset.Count;
        for (int i = 0; i < count; i++)
        {
            if (CompareValues(op, nodeset[i], val, compType))
            {
                return true;
            }
        }
        return false;
    }
References System.Xml.Xsl.Runtime.XsltLibrary.CompareNumbers(), System.Xml.Xsl.Runtime.XsltLibrary.CompareValues(), System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Xml.Xsl.Runtime.XsltConvert.ToBoolean().
Referenced by System.Xml.Xsl.Runtime.XsltLibrary.EqualityOperator(), and System.Xml.Xsl.Runtime.XsltLibrary.RelationalOperator().