Terraria: System.Xml.Xsl.Runtime.XsltLibrary.FunctionAvailableHelper
FunctionAvailableHelper()
bool System.Xml.Xsl.Runtime.XsltLibrary.FunctionAvailableHelper (XmlQualifiedName name) inline private
Definition at line 82 of file XsltLibrary.cs.
    {
        if (QilGenerator.IsFunctionAvailable(name.Name, name.Namespace))
        {
            return true;
        }
        if (name.Namespace.Length == 0 || name.Namespace == "http://www.w3.org/1999/XSL/Transform")
        {
            return false;
        }
        if (_runtime.ExternalContext.LateBoundFunctionExists(name.Name, name.Namespace))
        {
            return true;
        }
        return _runtime.EarlyBoundFunctionExists(name.Name, name.Namespace);
    }
References System.Xml.Xsl.Runtime.XsltLibrary._runtime, System.Xml.Xsl.Runtime.XmlQueryRuntime.EarlyBoundFunctionExists(), System.Xml.Xsl.Runtime.XmlQueryRuntime.ExternalContext, System.Xml.Xsl.Xslt.QilGenerator.IsFunctionAvailable(), and System.Xml.Xsl.Runtime.XmlQueryContext.LateBoundFunctionExists().
Referenced by System.Xml.Xsl.Runtime.XsltLibrary.FunctionAvailable().