Terraria: System.Xml.Xsl.Runtime.XsltLibrary.CompareValues
CompareValues()
static bool System.Xml.Xsl.Runtime.XsltLibrary.CompareValues (ComparisonOperator op, XPathItem left, XPathItem right, TypeCode compType) inline static private
Definition at line 272 of file XsltLibrary.cs.
    {
        return compType switch
        {
            TypeCode.Double => CompareNumbers(op, XsltConvert.ToDouble(left), XsltConvert.ToDouble(right)),
            TypeCode.String => XsltConvert.ToString(left) == XsltConvert.ToString(right) == (op == ComparisonOperator.Eq),
            _ => XsltConvert.ToBoolean(left) == XsltConvert.ToBoolean(right) == (op == ComparisonOperator.Eq),
        };
    }
References System.Xml.Xsl.Runtime.XsltLibrary.CompareNumbers(), System.Xml.Dictionary, System.Xml.Xsl.Runtime.XsltConvert.ToBoolean(), System.Xml.Xsl.Runtime.XsltConvert.ToDouble(), and System.Xml.Xsl.Runtime.XsltConvert.ToString().
Referenced by System.Xml.Xsl.Runtime.XsltLibrary.CompareNodeSetAndNodeSet(), System.Xml.Xsl.Runtime.XsltLibrary.CompareNodeSetAndValue(), System.Xml.Xsl.Runtime.XsltLibrary.EqualityOperator(), and System.Xml.Xsl.Runtime.XsltLibrary.RelationalOperator().