Terraria: LightingEngine.ProcessScan
ProcessScan()
void LightingEngine.ProcessScan (Rectangle area) inline private
     {
         area.Inflate(28, 28);
         _workingProcessedArea = area;
         _workingLightMap.SetSize(area.Width, area.Height);
         _workingLightMap.NonVisiblePadding = 18;
         _tileScanner.Update();
         _tileScanner.ExportTo(area, _workingLightMap, new TileLightScannerOptions
         {
             DrawInvisibleWalls = Main.ShouldShowInvisibleWalls()
         });
     }
References _tileScanner, _workingLightMap, _workingProcessedArea, TileLightScanner.ExportTo(), LightMap.NonVisiblePadding, LightMap.SetSize(), Main.ShouldShowInvisibleWalls(), and TileLightScanner.Update().
Referenced by ProcessArea().