Terraria: System.Web.Util.UriUtil.TrySplitUriForPathEncode
TrySplitUriForPathEncode()
static bool System.Web.Util.UriUtil.TrySplitUriForPathEncode (string input, [NotNullWhen(true)] out string schemeAndAuthority, [NotNullWhen(true)] out string path, out string queryAndFragment) inline static package
Definition at line 24 of file UriUtil.cs.
    {
        ExtractQueryAndFragment(input, out var path2, out queryAndFragment);
        if (Uri.TryCreate(path2, UriKind.Absolute, out Uri result))
        {
            string authority = result.Authority;
            if (!string.IsNullOrEmpty(authority))
            {
                int num = path2.IndexOf(authority, StringComparison.OrdinalIgnoreCase);
                if (num != -1)
                {
                    int num2 = num + authority.Length;
                    schemeAndAuthority = path2.Substring(0, num2);
                    path = path2.Substring(num2);
                    return true;
                }
            }
        }
        schemeAndAuthority = null;
        path = null;
        queryAndFragment = null;
        return false;
    }
References System.Web.Util.UriUtil.ExtractQueryAndFragment(), System.input, and System.Uri.TryCreate().
Referenced by System.Web.Util.HttpEncoder.UrlPathEncode().