Terraria: LightingEngine.ProcessArea
ProcessArea()
void LightingEngine.ProcessArea (Rectangle area) inline
Implements ILightingEngine.
     {
         Main.renderCount = (Main.renderCount + 1) % 4;
         _timer.Start();
         TimeLogger.LightingTime(0, 0.0);
         switch (_state)
         {
         case EngineState.MinimapUpdate:
             if (Main.mapDelay > 0)
             {
                 Main.mapDelay--;
             }
             else
             {
                 ExportToMiniMap();
             }
             TimeLogger.LightingTime(1, _timer.Elapsed.TotalMilliseconds);
             break;
         case EngineState.ExportMetrics:
             area.Inflate(28, 28);
             Main.SceneMetrics.ScanAndExportToMain(new SceneMetricsScanSettings
             {
                 VisualScanArea = area,
                 BiomeScanCenterPositionInWorld = Main.LocalPlayer.Center,
                 ScanOreFinderData = Main.LocalPlayer.accOreFinder
             });
             TimeLogger.LightingTime(2, _timer.Elapsed.TotalMilliseconds);
             break;
         case EngineState.Scan:
             ProcessScan(area);
             TimeLogger.LightingTime(3, _timer.Elapsed.TotalMilliseconds);
             break;
         case EngineState.Blur:
             ProcessBlur();
             Present();
             TimeLogger.LightingTime(4, _timer.Elapsed.TotalMilliseconds);
             break;
         }
         IncrementState();
         _timer.Reset();
     }
References _state, _timer, Player.accOreFinder, Entity.Center, ExportToMiniMap(), IncrementState(), TimeLogger.LightingTime(), Main.LocalPlayer, Main.mapDelay, Present(), ProcessBlur(), ProcessScan(), Main.renderCount, SceneMetrics.ScanAndExportToMain(), and Main.SceneMetrics.