Terraria: LightingEngine.ExportToMiniMap
ExportToMiniMap()
void LightingEngine.ExportToMiniMap () inline private
     {
         //IL_0102: Unknown result type (might be due to invalid IL or missing references)
         //IL_010d: Expected O, but got Unknown
         if (!Main.mapEnabled || _activeProcessedArea.Width <= 0 || _activeProcessedArea.Height <= 0)
         {
             return;
         }
         Rectangle area = new Rectangle(_activeProcessedArea.X + 28, _activeProcessedArea.Y + 28, _activeProcessedArea.Width - 56, _activeProcessedArea.Height - 56);
         Rectangle value = new Rectangle(0, 0, Main.maxTilesX, Main.maxTilesY);
         value.Inflate(-40, -40);
         area = Rectangle.Intersect(area, value);
         Main.mapMinX = area.Left;
         Main.mapMinY = area.Top;
         Main.mapMaxX = area.Right;
         Main.mapMaxY = area.Bottom;
         FastParallel.For(area.Left, area.Right, (ParallelForAction)delegate(int start, int end, object context)
         {
             for (int i = start; i < end; i++)
             {
                 for (int j = area.Top; j < area.Bottom; j++)
                 {
                     Vector3 vector = _activeLightMap[i - _activeProcessedArea.X, j - _activeProcessedArea.Y];
                     float num = Math.Max(Math.Max(vector.X, vector.Y), vector.Z);
                     byte light = (byte)Math.Min(255, (int)(num * 255f));
                     Main.Map.UpdateLighting(i, j, light);
                 }
             }
         }, (object)null);
         Main.updateMap = true;
     }
References _activeProcessedArea, FastParallel.For(), Main.mapEnabled, Main.mapMaxX, Main.mapMaxY, Main.mapMinX, Main.mapMinY, Main.maxTilesX, Main.maxTilesY, ParallelForAction(), and Main.updateMap.
Referenced by ProcessArea().