Terraria: System.Net.NameResolutionPal.GetAddrInfoAsync
GetAddrInfoAsync()
static unsafe Task System.Net.NameResolutionPal.GetAddrInfoAsync (string hostName, bool justAddresses, AddressFamily family, CancellationToken cancellationToken) inline static
Definition at line 268 of file NameResolutionPal.cs.
    {
        global::Interop.Winsock.EnsureInitialized();
        GetAddrInfoExContext* ptr = GetAddrInfoExContext.AllocateContext();
        GetAddrInfoExState getAddrInfoExState;
        try
        {
            getAddrInfoExState = new GetAddrInfoExState(ptr, hostName, justAddresses);
            ptr->QueryStateHandle = getAddrInfoExState.CreateHandle();
        }
        catch
        {
            GetAddrInfoExContext.FreeContext(ptr);
            throw;
        }
        global::Interop.Winsock.AddressInfoEx addressInfoEx = default(global::Interop.Winsock.AddressInfoEx);
        addressInfoEx.ai_family = family;
        global::Interop.Winsock.AddressInfoEx addressInfoEx2 = addressInfoEx;
        if (!justAddresses)
        {
            addressInfoEx2.ai_flags = AddressInfoHints.AI_CANONNAME;
        }
        SocketError addrInfoExW = (SocketError)global::Interop.Winsock.GetAddrInfoExW(hostName, null, 0, IntPtr.Zero, &addressInfoEx2, &ptr->Result, IntPtr.Zero, &ptr->Overlapped, (delegate* unmanaged<int, int, NativeOverlapped*, void>)(delegate*<int, int, NativeOverlapped*, void>)(&GetAddressInfoExCallback), &ptr->CancelHandle);
        switch (addrInfoExW)
        {
        case SocketError.IOPending:
            getAddrInfoExState.RegisterForCancellation(cancellationToken);
            break;
        case (SocketError)10111:
        case SocketError.TryAgain:
            GetAddrInfoExContext.FreeContext(ptr);
            return null;
        default:
            ProcessResult(addrInfoExW, ptr);
            break;
        }
        return getAddrInfoExState.Task;
    }
References System.Net.NameResolutionPal.GetAddrInfoExContext.AllocateContext(), System.Net.NameResolutionPal.GetAddrInfoExContext.CancelHandle, System.cancellationToken, System.Net.NameResolutionPal.GetAddrInfoExState.CreateHandle(), System.Net.NameResolutionPal.GetAddrInfoExContext.FreeContext(), System.Net.NameResolutionPal.GetAddressInfoExCallback(), System.Net.NameResolutionPal.GetAddrInfoExContext.Overlapped, System.Net.NameResolutionPal.ProcessResult(), System.Net.NameResolutionPal.GetAddrInfoExContext.QueryStateHandle, System.Net.NameResolutionPal.GetAddrInfoExState.RegisterForCancellation(), System.Net.NameResolutionPal.GetAddrInfoExContext.Result, System.Net.NameResolutionPal.GetAddrInfoExState.Task, and System.IntPtr.Zero.
Referenced by System.Net.Dns.GetAddrInfoWithTelemetryAsync< T >(), and System.Net.Dns.GetHostEntryOrAddressesCoreAsync().