Terraria: System.Net.NameResolutionPal.TryGetAddrInfo
TryGetAddrInfo()
static unsafe SocketError System.Net.NameResolutionPal.TryGetAddrInfo (string name, bool justAddresses, AddressFamily addressFamily, out string hostName, out string[] aliases, out IPAddress[] addresses, out int nativeErrorCode) inline static
Definition at line 193 of file NameResolutionPal.cs.
    {
        global::Interop.Winsock.EnsureInitialized();
        aliases = Array.Empty<string>();
        global::Interop.Winsock.AddressInfo addressInfo = default(global::Interop.Winsock.AddressInfo);
        addressInfo.ai_family = addressFamily;
        global::Interop.Winsock.AddressInfo addressInfo2 = addressInfo;
        if (!justAddresses)
        {
            addressInfo2.ai_flags = AddressInfoHints.AI_CANONNAME;
        }
        global::Interop.Winsock.AddressInfo* ptr = null;
        try
        {
            SocketError addrInfoW = (SocketError)global::Interop.Winsock.GetAddrInfoW(name, null, &addressInfo2, &ptr);
            if (addrInfoW != 0)
            {
                nativeErrorCode = (int)addrInfoW;
                hostName = name;
                addresses = Array.Empty<IPAddress>();
                return addrInfoW;
            }
            addresses = ParseAddressInfo(ptr, justAddresses, out hostName);
            nativeErrorCode = 0;
            return SocketError.Success;
        }
        finally
        {
            if (ptr != null)
            {
                global::Interop.Winsock.FreeAddrInfoW(ptr);
            }
        }
    }
References System.Net.NameResolutionPal.ParseAddressInfo().
Referenced by System.Net.Dns.GetHostEntryOrAddressesCore(), and System.Net.Dns.GetHostEntryOrAddressesCore().