Terraria: System.Net.NameResolutionPal.ParseAddressInfoEx
ParseAddressInfoEx()
static unsafe IPAddress[] System.Net.NameResolutionPal.ParseAddressInfoEx (global::Interop::Winsock::AddressInfoEx * addressInfoExPtr, bool justAddresses, out string hostName) inline static private
Definition at line 387 of file NameResolutionPal.cs.
    {
        int num = 0;
        for (global::Interop.Winsock.AddressInfoEx* ptr = addressInfoExPtr; ptr != null; ptr = ptr->ai_next)
        {
            int num2 = (int)ptr->ai_addrlen;
            if (ptr->ai_family == AddressFamily.InterNetwork)
            {
                if (num2 == 16)
                {
                    num++;
                }
            }
            else if (SocketProtocolSupportPal.OSSupportsIPv6 && ptr->ai_family == AddressFamily.InterNetworkV6 && num2 == 28)
            {
                num++;
            }
        }
        IPAddress[] array = new IPAddress[num];
        num = 0;
        string text = (justAddresses ? "NONNULLSENTINEL" : null);
        for (global::Interop.Winsock.AddressInfoEx* ptr2 = addressInfoExPtr; ptr2 != null; ptr2 = ptr2->ai_next)
        {
            if (text == null && ptr2->ai_canonname != IntPtr.Zero)
            {
                text = Marshal.PtrToStringUni(ptr2->ai_canonname);
            }
            int num3 = (int)ptr2->ai_addrlen;
            ReadOnlySpan<byte> socketAddress = new ReadOnlySpan<byte>(ptr2->ai_addr, num3);
            if (ptr2->ai_family == AddressFamily.InterNetwork)
            {
                if (num3 == 16)
                {
                    array[num++] = CreateIPv4Address(socketAddress);
                }
            }
            else if (SocketProtocolSupportPal.OSSupportsIPv6 && ptr2->ai_family == AddressFamily.InterNetworkV6 && num3 == 28)
            {
                array[num++] = CreateIPv6Address(socketAddress);
            }
        }
        hostName = (justAddresses ? null : text);
        return array;
    }
References System.array, System.Net.NameResolutionPal.CreateIPv4Address(), System.Net.NameResolutionPal.CreateIPv6Address(), System.Net.SocketProtocolSupportPal.OSSupportsIPv6, System.Runtime.InteropServices.Marshal.PtrToStringUni(), System.text, and System.IntPtr.Zero.
Referenced by System.Net.NameResolutionPal.ProcessResult().