Terraria: System.Net.NameResolutionPal.ProcessResult
ProcessResult()
static unsafe void System.Net.NameResolutionPal.ProcessResult (SocketError errorCode, GetAddrInfoExContext * context) inline static private
Definition at line 313 of file NameResolutionPal.cs.
    {
        try
        {
            GetAddrInfoExState getAddrInfoExState = GetAddrInfoExState.FromHandleAndFree(context->QueryStateHandle);
            CancellationToken token = getAddrInfoExState.UnregisterAndGetCancellationToken();
            if (errorCode == SocketError.Success)
            {
                string hostName;
                IPAddress[] array = ParseAddressInfoEx(context->Result, getAddrInfoExState.JustAddresses, out hostName);
                getAddrInfoExState.SetResult(getAddrInfoExState.JustAddresses ? ((object)array) : ((object)new IPHostEntry
                {
                    HostName = (hostName ?? getAddrInfoExState.HostName),
                    Aliases = Array.Empty<string>(),
                    AddressList = array
                }));
            }
            else
            {
                Exception currentStackTrace = ((errorCode == (SocketError)10111 && token.IsCancellationRequested) ? ((Exception)new OperationCanceledException(token)) : ((Exception)(object)new SocketException((int)errorCode)));
                getAddrInfoExState.SetResult(ExceptionDispatchInfo.SetCurrentStackTrace(currentStackTrace));
            }
        }
        finally
        {
            GetAddrInfoExContext.FreeContext(context);
        }
    }
References System.array, System.Net.NameResolutionPal.GetAddrInfoExContext.FreeContext(), System.Net.NameResolutionPal.GetAddrInfoExState.FromHandleAndFree(), System.Net.NameResolutionPal.GetAddrInfoExState.HostName, System.Threading.CancellationToken.IsCancellationRequested, System.Net.NameResolutionPal.GetAddrInfoExState.JustAddresses, System.Net.NameResolutionPal.ParseAddressInfoEx(), System.Net.NameResolutionPal.GetAddrInfoExContext.QueryStateHandle, System.Net.NameResolutionPal.GetAddrInfoExContext.Result, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.Net.NameResolutionPal.GetAddrInfoExState.SetResult(), and System.Net.NameResolutionPal.GetAddrInfoExState.UnregisterAndGetCancellationToken().
Referenced by System.Net.NameResolutionPal.GetAddressInfoExCallback(), and System.Net.NameResolutionPal.GetAddrInfoAsync().