Terraria: ReLogic.Content.Sources.FileSystemContentSource.OpenStream
OpenStream()
override Stream ReLogic.Content.Sources.FileSystemContentSource.OpenStream (string fullAssetName) inline
Must be threadsafe!
Implements ReLogic.Content.Sources.IContentSource.
Definition at line 26 of file FileSystemContentSource.cs.
    {
        if (!_nameToAbsolutePath.TryGetValue(assetName, out var value))
        {
            throw AssetLoadException.FromMissingAsset(assetName);
        }
        if (!File.Exists(value))
        {
            throw AssetLoadException.FromMissingAsset(assetName);
        }
        try
        {
            return File.OpenRead(value);
        }
        catch (Exception innerException)
        {
            throw AssetLoadException.FromMissingAsset(assetName, innerException);
        }
    }
References ReLogic.Content.Sources.FileSystemContentSource._nameToAbsolutePath, System.IO.File.Exists(), ReLogic.Content.AssetLoadException.FromMissingAsset(), System.IO.File.OpenRead(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.