Terraria: ReLogic.Content.Sources.FileSystemContentSource.FileSystemContentSource
FileSystemContentSource()
ReLogic.Content.Sources.FileSystemContentSource.FileSystemContentSource (string basePath) inline
Definition at line 15 of file FileSystemContentSource.cs.
    {
        _basePath = Path.GetFullPath(basePath);
        if (!_basePath.EndsWith("/") && !_basePath.EndsWith("\\"))
        {
            _basePath += Path.DirectorySeparatorChar;
        }
        BuildNameToAbsolutePathDictionary();
        SetAssetNames(_nameToAbsolutePath.Keys);
    }
References ReLogic.Content.Sources.FileSystemContentSource._basePath, ReLogic.Content.Sources.FileSystemContentSource._nameToAbsolutePath, ReLogic.Content.Sources.FileSystemContentSource.BuildNameToAbsolutePathDictionary(), System.IO.Path.DirectorySeparatorChar, System.IO.Path.GetFullPath(), System.Collections.Generic.Dictionary< TKey, TValue >.Keys, and ReLogic.Content.Sources.ContentSource.SetAssetNames().