Terraria: ReLogic.Content.Sources.FileSystemContentSource.BuildNameToAbsolutePathDictionary
BuildNameToAbsolutePathDictionary()
void ReLogic.Content.Sources.FileSystemContentSource.BuildNameToAbsolutePathDictionary () inline private
Definition at line 46 of file FileSystemContentSource.cs.
    {
        if (Directory.Exists(_basePath))
        {
            string[] files = Directory.GetFiles(_basePath, "*", SearchOption.AllDirectories);
            for (int i = 0; i < files.Length; i++)
            {
                string fullPath = Path.GetFullPath(files[i]);
                string path = fullPath.Substring(_basePath.Length);
                path = AssetPathHelper.CleanPath(path);
                _nameToAbsolutePath[path] = fullPath;
            }
        }
    }
References ReLogic.Content.Sources.FileSystemContentSource._basePath, ReLogic.Content.Sources.FileSystemContentSource._nameToAbsolutePath, ReLogic.Content.AssetPathHelper.CleanPath(), System.IO.Directory.Exists(), System.IO.Directory.GetFiles(), and System.IO.Path.GetFullPath().
Referenced by ReLogic.Content.Sources.FileSystemContentSource.FileSystemContentSource().