Terraria: System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Intrinsified
GetIndexOfFirstNonAsciiByte_Intrinsified()
static unsafe nuint System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Intrinsified (byte * pBuffer, nuint bufferLength) inline static private
Definition at line 134 of file ASCIIUtility.cs.
    {
        uint num = (uint)Unsafe.SizeOf<Vector128<byte>>();
        nuint num2 = num - 1;
        if (!BitConverter.IsLittleEndian)
        {
        }
        Vector128<byte> vector = Vector128.Create((ushort)4097).AsByte();
        uint num3 = uint.MaxValue;
        uint num4 = uint.MaxValue;
        uint num5 = uint.MaxValue;
        uint num6 = uint.MaxValue;
        byte* ptr = pBuffer;
        if (bufferLength >= num)
        {
            if (Sse2.IsSupported)
            {
                num3 = (uint)Sse2.MoveMask(Sse2.LoadVector128(pBuffer));
                if (!ContainsNonAsciiByte_Sse2(num3))
                {
                    if (bufferLength < 2 * num)
                    {
                        goto IL_0122;
                    }
                    pBuffer = (byte*)((nuint)(pBuffer + num) & ~num2);
                    bufferLength = (nuint)(bufferLength + ptr);
                    bufferLength -= (nuint)pBuffer;
                    if (bufferLength < 2 * num)
                    {
                        goto IL_00ef;
                    }
                    byte* ptr2 = pBuffer + bufferLength - 2 * num;
                    while (true)
                    {
                        if (Sse2.IsSupported)
{
                            Vector128<byte> value = Sse2.LoadAlignedVector128(pBuffer);
                            Vector128<byte> value2 = Sse2.LoadAlignedVector128(pBuffer + num);
                            num3 = (uint)Sse2.MoveMask(value);
                            num4 = (uint)Sse2.MoveMask(value2);
                            if (ContainsNonAsciiByte_Sse2(num3 | num4))
{
                                break;
                            }
                            pBuffer += 2 * num;
                            if (pBuffer <= ptr2)
{
                                continue;
                            }
                            goto IL_00ef;
                        }
                        if (AdvSimd.Arm64.IsSupported)
{
                        }
                        throw new PlatformNotSupportedException();
                    }
                    if (!Sse2.IsSupported)
                    {
                        if (AdvSimd.IsSupported)
{
                        }
                        throw new PlatformNotSupportedException();
                    }
                    if (!ContainsNonAsciiByte_Sse2(num3))
                    {
                        pBuffer += num;
                        num3 = num4;
                    }
                }
                goto IL_0197;
            }
            if (AdvSimd.Arm64.IsSupported)
            {
            }
            throw new PlatformNotSupportedException();
        }
        if ((bufferLength & 8) != 0)
        {
            _ = UIntPtr.Size;
            ulong num7 = Unsafe.ReadUnaligned<ulong>(pBuffer);
            if (!AllBytesInUInt64AreAscii(num7))
            {
                num7 &= 0x8080808080808080uL;
                pBuffer += (nuint)(BitOperations.TrailingZeroCount(num7) >> 3);
                goto IL_016b;
            }
            pBuffer += 8;
        }
        if ((bufferLength & 4) != 0)
        {
            uint value3 = Unsafe.ReadUnaligned<uint>(pBuffer);
            if (!AllBytesInUInt32AreAscii(value3))
            {
                pBuffer += CountNumberOfLeadingAsciiBytesFromUInt32WithSomeNonAsciiData(value3);
                goto IL_016b;
            }
            pBuffer += 4;
        }
        if ((bufferLength & 2) != 0)
        {
            uint value3 = Unsafe.ReadUnaligned<ushort>(pBuffer);
            if (!AllBytesInUInt32AreAscii(value3))
            {
                pBuffer += (nuint)(((nint)(sbyte)value3 >> 7) + 1);
                goto IL_016b;
            }
            pBuffer += 2;
        }
        if ((bufferLength & 1) != 0 && *pBuffer >= 0)
        {
            pBuffer++;
        }
        goto IL_016b;
        IL_00ef:
        if ((bufferLength & num) == 0)
        {
            goto IL_0128;
        }
        if (Sse2.IsSupported)
        {
            num3 = (uint)Sse2.MoveMask(Sse2.LoadAlignedVector128(pBuffer));
            if (!ContainsNonAsciiByte_Sse2(num3))
            {
                goto IL_0122;
            }
            goto IL_0197;
        }
        if (AdvSimd.Arm64.IsSupported)
        {
        }
        throw new PlatformNotSupportedException();
        IL_016b:
        return (nuint)(pBuffer - (nuint)ptr);
        IL_0122:
        pBuffer += num;
        goto IL_0128;
        IL_0197:
        if (Sse2.IsSupported)
        {
            pBuffer += (uint)BitOperations.TrailingZeroCount(num3);
            goto IL_016b;
        }
        if (AdvSimd.Arm64.IsSupported)
        {
        }
        throw new PlatformNotSupportedException();
        IL_0128:
        if (((byte)bufferLength & num2) != 0)
        {
            pBuffer += (bufferLength & num2) - num;
            if (!Sse2.IsSupported)
            {
                if (AdvSimd.Arm64.IsSupported)
                {
                }
                throw new PlatformNotSupportedException();
            }
            num3 = (uint)Sse2.MoveMask(Sse2.LoadVector128(pBuffer));
            if (ContainsNonAsciiByte_Sse2(num3))
            {
                goto IL_0197;
            }
            pBuffer += num;
        }
        goto IL_016b;
    }
References System.Text.ASCIIUtility.AllBytesInUInt32AreAscii(), System.Text.ASCIIUtility.AllBytesInUInt64AreAscii(), System.Text.ASCIIUtility.ContainsNonAsciiByte_Sse2(), System.Text.ASCIIUtility.CountNumberOfLeadingAsciiBytesFromUInt32WithSomeNonAsciiData(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.BitConverter.IsLittleEndian, System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.IsSupported, System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.Runtime.Intrinsics.X86.Sse2.LoadAlignedVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.UIntPtr.Size, System.Numerics.BitOperations.TrailingZeroCount(), and System.value.
Referenced by System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte().