Terraria: System.Text.ASCIIUtility.NarrowUtf16ToAscii
NarrowUtf16ToAscii()
static unsafe nuint System.Text.ASCIIUtility.NarrowUtf16ToAscii (char * pUtf16Buffer, byte * pAsciiBuffer, nuint elementCount) inline static
Definition at line 582 of file ASCIIUtility.cs.
    {
        nuint num = 0u;
        uint num2 = 0u;
        uint num3 = 0u;
        ulong num4 = 0uL;
        if (Sse2.IsSupported)
        {
            if (elementCount >= (uint)(2 * Unsafe.SizeOf<Vector128<byte>>()))
            {
                _ = IntPtr.Size;
                num4 = Unsafe.ReadUnaligned<ulong>(pUtf16Buffer);
                if (!AllCharsInUInt64AreAscii(num4))
                {
                    goto IL_018b;
                }
                num = NarrowUtf16ToAscii_Sse2(pUtf16Buffer, pAsciiBuffer, elementCount);
            }
        }
        else if (Vector.IsHardwareAccelerated)
        {
            uint num5 = (uint)Unsafe.SizeOf<Vector<byte>>();
            if (elementCount >= 2 * num5)
            {
                _ = IntPtr.Size;
                num4 = Unsafe.ReadUnaligned<ulong>(pUtf16Buffer);
                if (!AllCharsInUInt64AreAscii(num4))
                {
                    goto IL_018b;
                }
                Vector<ushort> right = new Vector<ushort>(127);
                nuint num6 = elementCount - 2 * num5;
                do
                {
                    Vector<ushort> vector = Unsafe.ReadUnaligned<Vector<ushort>>(pUtf16Buffer + num);
                    Vector<ushort> vector2 = Unsafe.ReadUnaligned<Vector<ushort>>(pUtf16Buffer + num + Vector<ushort>.Count);
                    if (Vector.GreaterThanAny(Vector.BitwiseOr(vector, vector2), right))
                    {
                        break;
                    }
                    Vector<byte> value = Vector.Narrow(vector, vector2);
                    Unsafe.WriteUnaligned(pAsciiBuffer + num, value);
                    num += num5;
                }
                while (num <= num6);
            }
        }
        nuint num7 = elementCount - num;
        if (num7 < 4)
        {
            goto IL_0137;
        }
        nuint num8 = num + num7 - 4;
        while (true)
        {
            _ = IntPtr.Size;
            num4 = Unsafe.ReadUnaligned<ulong>(pUtf16Buffer + num);
            if (!AllCharsInUInt64AreAscii(num4))
            {
                break;
            }
            NarrowFourUtf16CharsToAsciiAndWriteToBuffer(ref pAsciiBuffer[num], num4);
            num += 4;
            if (num <= num8)
            {
                continue;
            }
            goto IL_0137;
        }
        goto IL_018b;
        IL_01c4:
        if (FirstCharInUInt32IsAscii(num2))
        {
            if (!BitConverter.IsLittleEndian)
            {
            }
            pAsciiBuffer[num] = (byte)num2;
            num++;
        }
        goto IL_0189;
        IL_0189:
        return num;
        IL_0137:
        if (((uint)(int)num7 & 2u) != 0)
        {
            num2 = Unsafe.ReadUnaligned<uint>(pUtf16Buffer + num);
            if (!AllCharsInUInt32AreAscii(num2))
            {
                goto IL_01c4;
            }
            NarrowTwoUtf16CharsToAsciiAndWriteToBuffer(ref pAsciiBuffer[num], num2);
            num += 2;
        }
        if (((uint)(int)num7 & (true ? 1u : 0u)) != 0)
        {
            num2 = pUtf16Buffer[num];
            if (num2 <= 127)
            {
                pAsciiBuffer[num] = (byte)num2;
                num++;
            }
        }
        goto IL_0189;
        IL_018b:
        _ = IntPtr.Size;
        _ = BitConverter.IsLittleEndian;
        num2 = (uint)num4;
        if (AllCharsInUInt32AreAscii(num2))
        {
            NarrowTwoUtf16CharsToAsciiAndWriteToBuffer(ref pAsciiBuffer[num], num2);
            _ = BitConverter.IsLittleEndian;
            num2 = (uint)(num4 >> 32);
            num += 2;
        }
        goto IL_01c4;
    }
References System.Text.ASCIIUtility.AllCharsInUInt32AreAscii(), System.Text.ASCIIUtility.AllCharsInUInt64AreAscii(), System.Numerics.Vector< T >.Count, System.Text.ASCIIUtility.FirstCharInUInt32IsAscii(), System.Numerics.Vector< T >.IsHardwareAccelerated, System.BitConverter.IsLittleEndian, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.Numerics.Vector< T >.Narrow(), System.Text.ASCIIUtility.NarrowFourUtf16CharsToAsciiAndWriteToBuffer(), System.Text.ASCIIUtility.NarrowTwoUtf16CharsToAsciiAndWriteToBuffer(), System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(), System.IntPtr.Size, and System.value.
Referenced by System.Text.ASCIIEncoding.GetBytesFast(), System.Text.ASCIIEncoding.GetBytesWithFallback(), and System.Text.Unicode.Utf8Utility.TranscodeToUtf8().