Terraria: System.Text.ASCIIUtility.WidenAsciiToUtf16_Intrinsified
WidenAsciiToUtf16_Intrinsified()
static unsafe nuint System.Text.ASCIIUtility.WidenAsciiToUtf16_Intrinsified (byte * pAsciiBuffer, char * pUtf16Buffer, nuint elementCount) inline static private
Definition at line 877 of file ASCIIUtility.cs.
    {
        uint num = (uint)Unsafe.SizeOf<Vector128<byte>>();
        nuint num2 = num - 1;
        if (Sse2.IsSupported)
        {
            Vector128<byte> vector = Sse2.LoadVector128(pAsciiBuffer);
            if (Sse2.MoveMask(vector) != 0)
            {
                return 0u;
            }
            Vector128<byte> zero = Vector128<byte>.Zero;
            if (Sse2.IsSupported)
            {
                Vector128<byte> source = Sse2.UnpackLow(vector, zero);
                Sse2.Store((byte*)pUtf16Buffer, source);
                nuint num3 = (num >> 1) - (((nuint)pUtf16Buffer >> 1) & (num2 >> 1));
                nuint num4 = elementCount - num;
                char* ptr = pUtf16Buffer + num3;
                while (true)
                {
                    if (Sse2.IsSupported)
                    {
                        vector = Sse2.LoadVector128(pAsciiBuffer + num3);
                        bool flag = Sse2.MoveMask(vector) != 0;
                        if (!flag)
{
                            if (!Sse2.IsSupported)
{
                                if (AdvSimd.Arm64.IsSupported)
{
                                }
                                throw new PlatformNotSupportedException();
                            }
                            Vector128<byte> source2 = Sse2.UnpackLow(vector, zero);
                            Sse2.StoreAligned((byte*)ptr, source2);
                            Vector128<byte> source3 = Sse2.UnpackHigh(vector, zero);
                            Sse2.StoreAligned((byte*)ptr + num, source3);
                            num3 += num;
                            ptr += num;
                            if (num3 <= num4)
{
                                continue;
                            }
                        }
                        else if (!flag)
{
                            if (!Sse2.IsSupported)
{
                                break;
                            }
                            source = Sse2.UnpackLow(vector, zero);
                            Sse2.StoreAligned((byte*)(pUtf16Buffer + num3), source);
                            num3 += num / 2;
                        }
                        return num3;
                    }
                    if (AdvSimd.Arm64.IsSupported)
                    {
                    }
                    throw new PlatformNotSupportedException();
                }
                if (AdvSimd.Arm64.IsSupported)
                {
                }
                throw new PlatformNotSupportedException();
            }
            if (AdvSimd.IsSupported)
            {
            }
            throw new PlatformNotSupportedException();
        }
        if (AdvSimd.Arm64.IsSupported)
        {
        }
        throw new PlatformNotSupportedException();
    }
References System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.IsSupported, System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.source, System.Runtime.Intrinsics.X86.Sse2.Store(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Runtime.Intrinsics.X86.Sse2.UnpackHigh(), System.Runtime.Intrinsics.X86.Sse2.UnpackLow(), and System.Runtime.Intrinsics.Vector128< T >.Zero.
Referenced by System.Text.ASCIIUtility.WidenAsciiToUtf16().