Terraria: System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Default
GetIndexOfFirstNonAsciiByte_Default()
static unsafe nuint System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Default (byte * pBuffer, nuint bufferLength) inline static private
Definition at line 56 of file ASCIIUtility.cs.
    {
        byte* ptr = pBuffer;
        if (Vector.IsHardwareAccelerated && bufferLength >= (uint)(2 * Vector<sbyte>.Count))
        {
            uint count = (uint)Vector<sbyte>.Count;
            if (Vector.GreaterThanOrEqualAll(Unsafe.ReadUnaligned<Vector<sbyte>>(pBuffer), Vector<sbyte>.Zero))
            {
                byte* ptr2 = pBuffer + bufferLength - count;
                pBuffer = (byte*)((nuint)(pBuffer + count) & ~(nuint)(count - 1));
                while (!Vector.LessThanAny(Unsafe.Read<Vector<sbyte>>(pBuffer), Vector<sbyte>.Zero))
                {
                    pBuffer += count;
                    if (pBuffer > ptr2)
                    {
                        break;
                    }
                }
                bufferLength -= (nuint)pBuffer;
                bufferLength = (nuint)(bufferLength + ptr);
            }
        }
        while (true)
        {
            uint num;
            if (bufferLength >= 8)
            {
                num = Unsafe.ReadUnaligned<uint>(pBuffer);
                uint num2 = Unsafe.ReadUnaligned<uint>(pBuffer + 4);
                if (!AllBytesInUInt32AreAscii(num | num2))
                {
                    if (AllBytesInUInt32AreAscii(num))
                    {
                        num = num2;
                        pBuffer += 4;
                    }
                    goto IL_0100;
                }
                pBuffer += 8;
                bufferLength -= 8;
                continue;
            }
            if ((bufferLength & 4) != 0)
            {
                num = Unsafe.ReadUnaligned<uint>(pBuffer);
                if (!AllBytesInUInt32AreAscii(num))
                {
                    goto IL_0100;
                }
                pBuffer += 4;
            }
            if ((bufferLength & 2) != 0)
            {
                num = Unsafe.ReadUnaligned<ushort>(pBuffer);
                if (!AllBytesInUInt32AreAscii(num) && BitConverter.IsLittleEndian)
                {
                    goto IL_0100;
                }
                pBuffer += 2;
            }
            if ((bufferLength & 1) != 0 && *pBuffer >= 0)
            {
                pBuffer++;
            }
            break;
            IL_0100:
            pBuffer += CountNumberOfLeadingAsciiBytesFromUInt32WithSomeNonAsciiData(num);
            break;
        }
        return (nuint)(pBuffer - (nuint)ptr);
    }
References System.Text.ASCIIUtility.AllBytesInUInt32AreAscii(), System.count, System.Numerics.Vector< T >.Count, System.Text.ASCIIUtility.CountNumberOfLeadingAsciiBytesFromUInt32WithSomeNonAsciiData(), System.Numerics.Vector< T >.IsHardwareAccelerated, System.BitConverter.IsLittleEndian, and System.Numerics.Vector< T >.Zero.
Referenced by System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte().