Terraria: System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiChar
GetIndexOfFirstNonAsciiChar()
static unsafe nuint System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiChar (char * pBuffer, nuint bufferLength) inline static
Definition at line 302 of file ASCIIUtility.cs.
    {
        if (!Sse2.IsSupported)
        {
            return GetIndexOfFirstNonAsciiChar_Default(pBuffer, bufferLength);
        }
        return GetIndexOfFirstNonAsciiChar_Sse2(pBuffer, bufferLength);
    }
References System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiChar_Default(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiChar_Sse2(), and System.Runtime.Intrinsics.X86.Sse2.IsSupported.
Referenced by System.Text.ASCIIEncoding.GetByteCountFast(), System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidChar(), and System.String.IsAscii().