Terraria: System.Text.ASCIIUtility.WidenFourAsciiBytesToUtf16AndWriteToBuffer
WidenFourAsciiBytesToUtf16AndWriteToBuffer()
static void System.Text.ASCIIUtility.WidenFourAsciiBytesToUtf16AndWriteToBuffer (ref char outputBuffer, uint value) inline static package
Definition at line 956 of file ASCIIUtility.cs.
    {
        if (Sse2.X64.IsSupported)
        {
            Vector128<byte> left = Sse2.ConvertScalarToVector128UInt32(value).AsByte();
            Vector128<ulong> value2 = Sse2.UnpackLow(left, Vector128<byte>.Zero).AsUInt64();
            Unsafe.WriteUnaligned(ref Unsafe.As<char, byte>(ref outputBuffer), Sse2.X64.ConvertToUInt64(value2));
            return;
        }
        if (AdvSimd.Arm64.IsSupported)
        {
        }
        _ = BitConverter.IsLittleEndian;
        outputBuffer = (char)(byte)value;
        value >>= 8;
        Unsafe.Add(ref outputBuffer, 1) = (char)(byte)value;
        value >>= 8;
        Unsafe.Add(ref outputBuffer, 2) = (char)(byte)value;
        value >>= 8;
        Unsafe.Add(ref outputBuffer, 3) = (char)value;
    }
References System.Runtime.Intrinsics.X86.Sse2.ConvertScalarToVector128UInt32(), System.Runtime.Intrinsics.X86.Sse2.X64.ConvertToUInt64(), System.BitConverter.IsLittleEndian, System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.IsSupported, System.Runtime.Intrinsics.X86.Sse2.X64.IsSupported, System.Runtime.Intrinsics.X86.Sse2.UnpackLow(), and System.value.
Referenced by System.Text.Unicode.Utf8Utility.TranscodeToUtf16(), and System.Text.ASCIIUtility.WidenAsciiToUtf16().