Terraria: System.Text.ASCIIUtility.WidenAsciiToUtf16
WidenAsciiToUtf16()
static unsafe nuint System.Text.ASCIIUtility.WidenAsciiToUtf16 (byte * pAsciiBuffer, char * pUtf16Buffer, nuint elementCount) inline static
Definition at line 786 of file ASCIIUtility.cs.
    {
        nuint num = 0u;
        _ = BitConverter.IsLittleEndian;
        if (Sse2.IsSupported || AdvSimd.Arm64.IsSupported)
        {
            if (elementCount >= (uint)(2 * Unsafe.SizeOf<Vector128<byte>>()))
            {
                num = WidenAsciiToUtf16_Intrinsified(pAsciiBuffer, pUtf16Buffer, elementCount);
            }
        }
        else if (Vector.IsHardwareAccelerated)
        {
            uint num2 = (uint)Unsafe.SizeOf<Vector<byte>>();
            if (elementCount >= num2)
            {
                nuint num3 = elementCount - num2;
                do
                {
                    Vector<sbyte> vector = Unsafe.ReadUnaligned<Vector<sbyte>>(pAsciiBuffer + num);
                    if (Vector.LessThanAny(vector, Vector<sbyte>.Zero))
                    {
                        break;
                    }
                    Vector.Widen(Vector.AsVectorByte(vector), out var low, out var high);
                    Unsafe.WriteUnaligned(pUtf16Buffer + num, low);
                    Unsafe.WriteUnaligned(pUtf16Buffer + num + Vector<ushort>.Count, high);
                    num += num2;
                }
                while (num <= num3);
            }
        }
        nuint num4 = elementCount - num;
        if (num4 < 4)
        {
            goto IL_00df;
        }
        nuint num5 = num + num4 - 4;
        uint num6;
        while (true)
        {
            num6 = Unsafe.ReadUnaligned<uint>(pAsciiBuffer + num);
            if (!AllBytesInUInt32AreAscii(num6))
            {
                break;
            }
            WidenFourAsciiBytesToUtf16AndWriteToBuffer(ref pUtf16Buffer[num], num6);
            num += 4;
            if (num <= num5)
            {
                continue;
            }
            goto IL_00df;
        }
        goto IL_014f;
        IL_014d:
        return num;
        IL_014f:
        _ = BitConverter.IsLittleEndian;
        while (((byte)num6 & 0x80) == 0)
        {
            pUtf16Buffer[num] = (char)(byte)num6;
            num++;
            num6 >>= 8;
        }
        goto IL_014d;
        IL_00df:
        if (((uint)(int)num4 & 2u) != 0)
        {
            num6 = Unsafe.ReadUnaligned<ushort>(pAsciiBuffer + num);
            if (!AllBytesInUInt32AreAscii(num6) && BitConverter.IsLittleEndian)
            {
                goto IL_014f;
            }
            _ = BitConverter.IsLittleEndian;
            pUtf16Buffer[num] = (char)(byte)num6;
            pUtf16Buffer[num + 1] = (char)(num6 >> 8);
            num += 2;
        }
        if (((uint)(int)num4 & (true ? 1u : 0u)) != 0)
        {
            num6 = pAsciiBuffer[num];
            if (((byte)num6 & 0x80) == 0)
            {
                pUtf16Buffer[num] = (char)num6;
                num++;
            }
        }
        goto IL_014d;
    }
References System.Text.ASCIIUtility.AllBytesInUInt32AreAscii(), System.Numerics.Vector< T >.IsHardwareAccelerated, System.BitConverter.IsLittleEndian, System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.IsSupported, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.Numerics.Vector< T >.Widen(), System.Text.ASCIIUtility.WidenAsciiToUtf16_Intrinsified(), System.Text.ASCIIUtility.WidenFourAsciiBytesToUtf16AndWriteToBuffer(), and System.Numerics.Vector< T >.Zero.
Referenced by System.Text.ASCIIEncoding.GetCharsFast(), System.Text.ASCIIEncoding.GetCharsWithFallback(), and System.Text.Unicode.Utf8Utility.TranscodeToUtf16().