Terraria: System.Text.ASCIIUtility.CountNumberOfLeadingAsciiBytesFromUInt32WithSomeNonAsciiData
CountNumberOfLeadingAsciiBytesFromUInt32WithSomeNonAsciiData()
static uint System.Text.ASCIIUtility.CountNumberOfLeadingAsciiBytesFromUInt32WithSomeNonAsciiData (uint value) inline static package
Definition at line 985 of file ASCIIUtility.cs.
    {
        _ = BitConverter.IsLittleEndian;
        return (uint)BitOperations.TrailingZeroCount(value & 0x80808080u) >> 3;
    }
References System.BitConverter.IsLittleEndian, System.Numerics.BitOperations.TrailingZeroCount(), and System.value.
Referenced by System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Default(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Intrinsified(), and System.Text.Unicode.Utf8Utility.GetPointerToFirstInvalidByte().