Terraria: ReLogic.OS.Windows.Clipboard.InvokeInStaThread< T >
InvokeInStaThread< T >()
static T ReLogic.OS.Windows.Clipboard.InvokeInStaThread< T > (Func< T > callback) inline static private
Definition at line 47 of file Clipboard.cs.
    {
        if (GetApartmentStateSafely() == ApartmentState.STA)
        {
            return callback();
        }
        T result = default(T);
        Thread thread = new Thread((ThreadStart)delegate
        {
            result = callback();
        });
        thread.SetApartmentState(ApartmentState.STA);
        thread.Start();
        thread.Join();
        return result;
    }
References ReLogic.OS.Windows.Clipboard.GetApartmentStateSafely(), System.Threading.Thread.Join(), System.Threading.Thread.SetApartmentState(), System.Threading.Thread.Start(), and System.Threading.ThreadStart().