Terraria: System.Collections.Concurrent.ConcurrentStack.TryPopRange
TryPopRange() [2/2]
int System.Collections.Concurrent.ConcurrentStack< T >.TryPopRange (T[] items, int startIndex, int count) inline
Definition at line 219 of file ConcurrentStack.cs.
    {
        ValidatePushPopRangeInput(items, startIndex, count);
        if (count == 0)
        {
            return 0;
        }
        Node poppedHead;
        int num = TryPopCore(count, out poppedHead);
        if (num > 0)
        {
            CopyRemovedItems(poppedHead, items, startIndex, num);
        }
        return num;
    }
References System.Collections.Concurrent.ConcurrentStack< T >.CopyRemovedItems(), System.count, System.startIndex, System.Collections.Concurrent.ConcurrentStack< T >.TryPopCore(), and System.Collections.Concurrent.ConcurrentStack< T >.ValidatePushPopRangeInput().