Terraria: System.Collections.Concurrent.ConcurrentStack.TryPop
TryPop()
bool System.Collections.Concurrent.ConcurrentStack< T >.TryPop ([MaybeNullWhen(false)] out T result) inline
Definition at line 194 of file ConcurrentStack.cs.
    {
        Node head = _head;
        if (head == null)
        {
            result = default(T);
            return false;
        }
        if (Interlocked.CompareExchange(ref _head, head._next, head) == head)
        {
            result = head._value;
            return true;
        }
        return TryPopCore(out result);
    }
References System.Collections.Concurrent.ConcurrentStack< T >._head, System.Collections.Concurrent.ConcurrentStack< T >.Node._next, System.Collections.Concurrent.ConcurrentStack< T >.Node._value, System.Threading.Interlocked.CompareExchange(), and System.Collections.Concurrent.ConcurrentStack< T >.TryPopCore().
Referenced by System.Collections.Concurrent.ConcurrentStack< T >.TryTake().