Terraria: System.Data.Common.DataColumnMapping.CreateDataColumnBySchemaAction
CreateDataColumnBySchemaAction()
static DataColumn System.Data.Common.DataColumnMapping.CreateDataColumnBySchemaAction (string sourceColumn, string dataSetColumn, DataTable dataTable, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicProperties)] Type dataType, MissingSchemaAction schemaAction) inline static package
Definition at line 148 of file DataColumnMapping.cs.
    {
        if (string.IsNullOrEmpty(dataSetColumn))
        {
            return null;
        }
        switch (schemaAction)
        {
        case MissingSchemaAction.Add:
        case MissingSchemaAction.AddWithKey:
            return new DataColumn(dataSetColumn, dataType);
        case MissingSchemaAction.Ignore:
            return null;
        case MissingSchemaAction.Error:
            throw ADP.ColumnSchemaMissing(dataSetColumn, dataTable.TableName, sourceColumn);
        default:
            throw ADP.InvalidMissingSchemaAction(schemaAction);
        }
    }
References System.Data.Common.ADP.ColumnSchemaMissing(), System.Data.Common.ADP.InvalidMissingSchemaAction(), and System.Data.DataTable.TableName.
Referenced by System.Data.Common.DataColumnMapping.GetDataColumnBySchemaAction(), and System.Data.ProviderBase.SchemaMapping.SetupSchemaWithoutKeyInfo().