Terraria: System.Data.Common.DataColumnMapping.GetDataColumnBySchemaAction
GetDataColumnBySchemaAction() [2/2]
static ? DataColumn System.Data.Common.DataColumnMapping.GetDataColumnBySchemaAction (string? sourceColumn, string? dataSetColumn, DataTable dataTable, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicProperties)] Type? dataType, MissingSchemaAction schemaAction) inline static
Definition at line 120 of file DataColumnMapping.cs.
    {
        if (dataTable == null)
        {
            throw ADP.ArgumentNull("dataTable");
        }
        if (string.IsNullOrEmpty(dataSetColumn))
        {
            return null;
        }
        DataColumnCollection columns = dataTable.Columns;
        int num = columns.IndexOf(dataSetColumn);
        if (0 <= num && num < columns.Count)
        {
            DataColumn dataColumn = columns[num];
            if (!string.IsNullOrEmpty(dataColumn.Expression))
            {
                throw ADP.ColumnSchemaExpression(sourceColumn, dataSetColumn);
            }
            if (null == dataType || dataType.IsArray == dataColumn.DataType.IsArray)
            {
                return dataColumn;
            }
            throw ADP.ColumnSchemaMismatch(sourceColumn, dataType, dataColumn);
        }
        return CreateDataColumnBySchemaAction(sourceColumn, dataSetColumn, dataTable, dataType, schemaAction);
    }
References System.Data.Common.ADP.ArgumentNull(), System.Data.DataTable.Columns, System.Data.Common.ADP.ColumnSchemaExpression(), System.Data.Common.ADP.ColumnSchemaMismatch(), System.Data.InternalDataCollectionBase.Count, System.Data.Common.DataColumnMapping.CreateDataColumnBySchemaAction(), System.Data.DataColumn.DataType, System.Data.DataColumn.Expression, System.Data.DataColumnCollection.IndexOf(), and System.Type.IsArray.