Terraria: System.IAsyncDisposable.DisposeAsync
DisposeAsync()
ValueTask System.IAsyncDisposable.DisposeAsync () inherited
Implemented in System.Data.Common.DbBatch, System.Data.Common.DbCommand, System.Data.Common.DbConnection, System.Data.Common.DbDataReader, System.Data.Common.DbTransaction, System.IO.Compression.BrotliStream, System.IO.Compression.DeflateStream, System.IO.Compression.GZipStream, System.IO.Compression.ZLibStream, System.IO.IsolatedStorage.IsolatedStorageFileStream, System.IO.DelegatingStream, System.Net.Http.Http3RequestStream.Http3ReadStream, System.Net.Http.Http3RequestStream, System.Net.Http.MultipartContent.ContentReadStream, System.Net.Quic.Implementations.Mock.MockStream, System.Net.Quic.Implementations.MsQuic.MsQuicStream, System.Net.Quic.Implementations.QuicStreamProvider, System.Net.Security.AuthenticatedStream, System.Net.Security.NegotiateStream, System.Net.Security.SslStream, System.IO.DelegatingStream, System.CodeDom.Compiler.IndentedTextWriter, System.IO.Strategies.BufferedFileStreamStrategy, System.IO.Strategies.DerivedFileStreamStrategy, System.IO.Strategies.Net5CompatFileStreamStrategy, System.IO.Strategies.OSFileStreamStrategy, System.IO.BinaryWriter, System.IO.BufferedStream, System.IO.FileStream, System.IO.Stream.SyncStream, System.IO.Stream, System.IO.StreamWriter, System.IO.TextWriter.SyncTextWriter, System.IO.TextWriter, System.Text.TranscodingStream, System.Threading.CancellationTokenRegistration, System.Threading.Timer, System.Xml.XmlWriter, System.Security.Cryptography.CryptoStream, System.Text.Json.Utf8JsonWriter, and System.Threading.Tasks.Parallel.AsyncForEachAsyncState< TSource >.
Referenced by System.Runtime.CompilerServices.ConfiguredAsyncDisposable.DisposeAsync(), System.Xml.Linq.XDocument.SaveAsync(), and System.Xml.Linq.XDocument.SaveAsync().