Terraria: System.Reflection.Metadata.MetadataReader.CalculateMethodDefTreatmentAndRowId
CalculateMethodDefTreatmentAndRowId()
uint System.Reflection.Metadata.MetadataReader.CalculateMethodDefTreatmentAndRowId (MethodDefinitionHandle methodDef) inline private
Definition at line 1558 of file MetadataReader.cs.
    {
        MethodDefTreatment methodDefTreatment = MethodDefTreatment.Implementation;
        TypeDefinitionHandle declaringType = GetDeclaringType(methodDef);
        TypeAttributes flags = TypeDefTable.GetFlags(declaringType);
        if ((flags & TypeAttributes.WindowsRuntime) != 0)
        {
            if (IsClrImplementationType(declaringType))
            {
                methodDefTreatment = MethodDefTreatment.Implementation;
            }
            else if (flags.IsNested())
            {
                methodDefTreatment = MethodDefTreatment.Implementation;
            }
            else if ((flags & TypeAttributes.ClassSemanticsMask) != 0)
            {
                methodDefTreatment = MethodDefTreatment.InterfaceMethod;
            }
            else if (_metadataKind == MetadataKind.ManagedWindowsMetadata && (flags & TypeAttributes.Public) == 0)
            {
                methodDefTreatment = MethodDefTreatment.Implementation;
            }
            else
            {
                methodDefTreatment = MethodDefTreatment.Other;
                EntityHandle extends = TypeDefTable.GetExtends(declaringType);
                if (extends.Kind == HandleKind.TypeReference)
                {
                    switch (GetSpecialTypeRefTreatment((TypeReferenceHandle)extends))
                    {
                    case TypeRefTreatment.SystemAttribute:
                        methodDefTreatment = MethodDefTreatment.AttributeMethod;
                        break;
                    case TypeRefTreatment.SystemDelegate:
                        methodDefTreatment = MethodDefTreatment.DelegateMethod | MethodDefTreatment.MarkPublicFlag;
                        break;
                    }
                }
            }
        }
        if (methodDefTreatment == MethodDefTreatment.Other)
        {
            bool flag = false;
            bool flag2 = false;
            bool isIDisposable = false;
            foreach (MethodImplementationHandle item in new MethodImplementationHandleCollection(this, declaringType))
            {
                MethodImplementation methodImplementation = GetMethodImplementation(item);
                if (!(methodImplementation.MethodBody == methodDef))
                {
                    continue;
                }
                EntityHandle methodDeclaration = methodImplementation.MethodDeclaration;
                if (methodDeclaration.Kind == HandleKind.MemberReference && ImplementsRedirectedInterface((MemberReferenceHandle)methodDeclaration, out isIDisposable))
                {
                    flag = true;
                    if (isIDisposable)
                    {
                        break;
                    }
                }
                else
                {
                    flag2 = true;
                }
            }
            if (isIDisposable)
            {
                methodDefTreatment = MethodDefTreatment.DisposeMethod;
            }
            else if (flag && !flag2)
            {
                methodDefTreatment = MethodDefTreatment.HiddenInterfaceImplementation;
            }
        }
        if (methodDefTreatment == MethodDefTreatment.Other)
        {
            methodDefTreatment |= GetMethodTreatmentFromCustomAttributes(methodDef);
        }
        return TreatmentAndRowId((byte)methodDefTreatment, methodDef.RowId);
    }
References System.Reflection.Metadata.MetadataReader._metadataKind, System.Reflection.Metadata.MetadataReader.GetDeclaringType(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFlags(), System.Reflection.Metadata.MetadataReader.GetMethodImplementation(), System.Reflection.Metadata.MetadataReader.GetMethodTreatmentFromCustomAttributes(), System.Reflection.Metadata.MetadataReader.GetSpecialTypeRefTreatment(), System.Reflection.Metadata.MetadataReader.ImplementsRedirectedInterface(), System.Reflection.Metadata.MetadataReader.IsClrImplementationType(), System.item, System.Reflection.Metadata.MetadataReader.TreatmentAndRowId(), and System.Reflection.Metadata.MetadataReader.TypeDefTable.
Referenced by System.Reflection.Metadata.MetadataReader.GetMethodDefTreatmentAndRowId().