Terraria: System.Transactions.TransactionStatePromotedBase.EnlistDurable
EnlistDurable() [1/2]
override Enlistment System.Transactions.TransactionStatePromotedBase.EnlistDurable (InternalTransaction tx, Guid resourceManagerIdentifier, IEnlistmentNotification enlistmentNotification, EnlistmentOptions enlistmentOptions, Transaction atomicTransaction) inline package virtual inherited
Reimplemented from System.Transactions.TransactionState.
Definition at line 45 of file TransactionStatePromotedBase.cs.
    {
        tx.ThrowIfPromoterTypeIsNotMSDTC();
        Monitor.Exit(tx);
        try
        {
            Enlistment enlistment = new Enlistment(resourceManagerIdentifier, tx, enlistmentNotification, null, atomicTransaction);
            EnlistmentState.EnlistmentStatePromoted.EnterState(enlistment.InternalEnlistment);
            enlistment.InternalEnlistment.PromotedEnlistment = tx.PromotedTransaction.EnlistDurable(resourceManagerIdentifier, (DurableInternalEnlistment)enlistment.InternalEnlistment, v: false, enlistmentOptions);
            return enlistment;
        }
        finally
        {
            Monitor.Enter(tx);
        }
    }
References System.Transactions.Distributed.DistributedTransaction.EnlistDurable(), System.Transactions.EnlistmentState.EnlistmentStatePromoted, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Transactions.Enlistment.InternalEnlistment, System.Transactions.InternalTransaction.PromotedTransaction, and System.Transactions.InternalTransaction.ThrowIfPromoterTypeIsNotMSDTC().