Terraria: System.Reflection.Metadata.MetadataReader.CalculateFieldDefTreatmentAndRowId
CalculateFieldDefTreatmentAndRowId()
uint System.Reflection.Metadata.MetadataReader.CalculateFieldDefTreatmentAndRowId (FieldDefinitionHandle handle) inline private
Definition at line 1661 of file MetadataReader.cs.
    {
        FieldAttributes flags = FieldTable.GetFlags(handle);
        FieldDefTreatment treatment = FieldDefTreatment.None;
        if ((flags & FieldAttributes.RTSpecialName) != 0 && StringHeap.EqualsRaw(FieldTable.GetName(handle), "value__"))
        {
            TypeDefinitionHandle declaringType = GetDeclaringType(handle);
            EntityHandle extends = TypeDefTable.GetExtends(declaringType);
            if (extends.Kind == HandleKind.TypeReference)
            {
                TypeReferenceHandle handle2 = (TypeReferenceHandle)extends;
                if (StringHeap.EqualsRaw(TypeRefTable.GetName(handle2), "Enum") && StringHeap.EqualsRaw(TypeRefTable.GetNamespace(handle2), "System"))
                {
                    treatment = FieldDefTreatment.EnumValue;
                }
            }
        }
        return TreatmentAndRowId((byte)treatment, handle.RowId);
    }
References System.Reflection.Metadata.Ecma335.StringHeap.EqualsRaw(), System.Reflection.Metadata.MetadataReader.FieldTable, System.Reflection.Metadata.MetadataReader.GetDeclaringType(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(), System.Reflection.Metadata.Ecma335.FieldTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.FieldTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetNamespace(), System.handle, System.Reflection.Metadata.MetadataReader.TreatmentAndRowId(), System.Reflection.Metadata.MetadataReader.TypeDefTable, and System.Reflection.Metadata.MetadataReader.TypeRefTable.
Referenced by System.Reflection.Metadata.MetadataReader.GetFieldDefTreatmentAndRowId().