Terraria: System.Reflection.Metadata.MetadataReader.InitializeNestedTypesMap
InitializeNestedTypesMap()
void System.Reflection.Metadata.MetadataReader.InitializeNestedTypesMap () inline private
Definition at line 1231 of file MetadataReader.cs.
    {
        Dictionary<TypeDefinitionHandle, ImmutableArray<TypeDefinitionHandle>.Builder> dictionary = new Dictionary<TypeDefinitionHandle, ImmutableArray<TypeDefinitionHandle>.Builder>();
        int numberOfRows = NestedClassTable.NumberOfRows;
        ImmutableArray<TypeDefinitionHandle>.Builder value = null;
        TypeDefinitionHandle typeDefinitionHandle = default(TypeDefinitionHandle);
        for (int i = 1; i <= numberOfRows; i++)
        {
            TypeDefinitionHandle enclosingClass = NestedClassTable.GetEnclosingClass(i);
            if (enclosingClass != typeDefinitionHandle)
            {
                if (!dictionary.TryGetValue(enclosingClass, out value))
                {
                    value = ImmutableArray.CreateBuilder<TypeDefinitionHandle>();
                    dictionary.Add(enclosingClass, value);
                }
                typeDefinitionHandle = enclosingClass;
            }
            value.Add(NestedClassTable.GetNestedClass(i));
        }
        Dictionary<TypeDefinitionHandle, ImmutableArray<TypeDefinitionHandle>> dictionary2 = new Dictionary<TypeDefinitionHandle, ImmutableArray<TypeDefinitionHandle>>();
        foreach (KeyValuePair<TypeDefinitionHandle, ImmutableArray<TypeDefinitionHandle>.Builder> item in dictionary)
        {
            dictionary2.Add(item.Key, item.Value.ToImmutable());
        }
        _lazyNestedTypesMap = dictionary2;
    }
References System.Reflection.Metadata.MetadataReader._lazyNestedTypesMap, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.dictionary, System.Reflection.Metadata.Ecma335.NestedClassTableReader.GetEnclosingClass(), System.Reflection.Metadata.Ecma335.NestedClassTableReader.GetNestedClass(), System.item, System.Reflection.Metadata.MetadataReader.NestedClassTable, System.Reflection.Metadata.Ecma335.NestedClassTableReader.NumberOfRows, and System.value.
Referenced by System.Reflection.Metadata.MetadataReader.GetNestedTypes().