Terraria: System.Reflection.Metadata.MetadataReader.MetadataReader
MetadataReader() [4/4]
unsafe System.Reflection.Metadata.MetadataReader.MetadataReader (byte * metadata, int length, MetadataReaderOptions options, MetadataStringDecoder? utf8Decoder, object? memoryOwner) inline package
Definition at line 323 of file MetadataReader.cs.
    {
        if (length < 0)
        {
            Throw.ArgumentOutOfRange("length");
        }
        if (metadata == null)
        {
            Throw.ArgumentNull("metadata");
        }
        if (utf8Decoder == null)
        {
            utf8Decoder = MetadataStringDecoder.DefaultUTF8;
        }
        if (!(utf8Decoder.Encoding is UTF8Encoding))
        {
            Throw.InvalidArgument(System.SR.MetadataStringDecoderEncodingMustBeUtf8, "utf8Decoder");
        }
        Block = new MemoryBlock(metadata, length);
        _memoryOwnerObj = memoryOwner;
        _options = options;
        UTF8Decoder = utf8Decoder;
        BlobReader memReader = new BlobReader(Block);
        ReadMetadataHeader(ref memReader, out _versionString);
        _metadataKind = GetMetadataKind(_versionString);
        StreamHeader[] streamHeaders = ReadStreamHeaders(ref memReader);
        InitializeStreamReaders(in Block, streamHeaders, out _metadataStreamKind, out var metadataTableStream, out var standalonePdbStream);
        int[] externalTableRowCounts;
        if (standalonePdbStream.Length > 0)
        {
            int pdbStreamOffset = (int)(standalonePdbStream.Pointer - metadata);
            ReadStandalonePortablePdbStream(standalonePdbStream, pdbStreamOffset, out _debugMetadataHeader, out externalTableRowCounts);
        }
        else
        {
            externalTableRowCounts = null;
        }
        BlobReader reader = new BlobReader(metadataTableStream);
        ReadMetadataTableHeader(ref reader, out var heapSizes, out var metadataTableRowCounts, out _sortedTables);
        InitializeTableReaders(reader.GetMemoryBlockAt(0, reader.RemainingBytes), heapSizes, metadataTableRowCounts, externalTableRowCounts);
        if (standalonePdbStream.Length == 0 && ModuleTable.NumberOfRows < 1)
        {
            throw new BadImageFormatException(System.SR.Format(System.SR.ModuleTableInvalidNumberOfRows, ModuleTable.NumberOfRows));
        }
        NamespaceCache = new NamespaceCache(this);
        if (_metadataKind != 0)
        {
            WinMDMscorlibRef = FindMscorlibAssemblyRefNoProjection();
        }
    }
References System.Reflection.Metadata.MetadataReader._debugMetadataHeader, System.Reflection.Metadata.MetadataReader._memoryOwnerObj, System.Reflection.Metadata.MetadataReader._metadataKind, System.Reflection.Metadata.MetadataReader._metadataStreamKind, System.Reflection.Metadata.MetadataReader._options, System.Reflection.Metadata.MetadataReader._sortedTables, System.Reflection.Metadata.MetadataReader._versionString, System.Reflection.Throw.ArgumentNull(), System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.Metadata.MetadataReader.Block, System.Reflection.Metadata.MetadataStringDecoder.DefaultUTF8, System.Reflection.Metadata.MetadataReader.FindMscorlibAssemblyRefNoProjection(), System.SR.Format(), System.Reflection.Metadata.BlobReader.GetMemoryBlockAt(), System.Reflection.Metadata.MetadataReader.GetMetadataKind(), System.Reflection.Metadata.MetadataReader.InitializeStreamReaders(), System.Reflection.Metadata.MetadataReader.InitializeTableReaders(), System.Reflection.Throw.InvalidArgument(), System.length, System.SR.MetadataStringDecoderEncodingMustBeUtf8, System.Reflection.Metadata.MetadataReader.ModuleTable, System.SR.ModuleTableInvalidNumberOfRows, System.Reflection.Metadata.MetadataReader.NamespaceCache, System.Reflection.Metadata.Ecma335.ModuleTableReader.NumberOfRows, System.options, System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(), System.Reflection.Metadata.MetadataReader.ReadMetadataTableHeader(), System.Reflection.Metadata.MetadataReader.ReadStandalonePortablePdbStream(), System.Reflection.Metadata.MetadataReader.ReadStreamHeaders(), System.Reflection.Metadata.BlobReader.RemainingBytes, System.Reflection.Metadata.MetadataReader.UTF8Decoder, and System.Reflection.Metadata.MetadataReader.WinMDMscorlibRef.