Terraria: System.Reflection.Metadata.MetadataReader.GetWellKnownTypeDefinitionTreatment
GetWellKnownTypeDefinitionTreatment()
TypeDefTreatment System.Reflection.Metadata.MetadataReader.GetWellKnownTypeDefinitionTreatment (TypeDefinitionHandle typeDef) inline private
Definition at line 1272 of file MetadataReader.cs.
    {
        InitializeProjectedTypes();
        StringHandle name = TypeDefTable.GetName(typeDef);
        int num = StringHeap.BinarySearchRaw(s_projectedTypeNames, name);
        if (num < 0)
        {
            return TypeDefTreatment.None;
        }
        StringHandle @namespace = TypeDefTable.GetNamespace(typeDef);
        if (StringHeap.EqualsRaw(@namespace, StringHeap.GetVirtualString(s_projectionInfos[num].ClrNamespace)))
        {
            return s_projectionInfos[num].Treatment;
        }
        if (StringHeap.EqualsRaw(@namespace, s_projectionInfos[num].WinRTNamespace))
        {
            return s_projectionInfos[num].Treatment | TypeDefTreatment.MarkInternalFlag;
        }
        return TypeDefTreatment.None;
    }
References System.Reflection.Metadata.Ecma335.StringHeap.BinarySearchRaw(), System.Reflection.Metadata.MetadataReader.ProjectionInfo.ClrNamespace, System.Reflection.Metadata.Ecma335.StringHeap.EqualsRaw(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetName(), System.Reflection.Metadata.Ecma335.StringHeap.GetVirtualString(), System.Reflection.Metadata.MetadataReader.InitializeProjectedTypes(), System.Reflection.Metadata.MetadataReader.s_projectedTypeNames, System.Reflection.Metadata.MetadataReader.ProjectionInfo.Treatment, System.Reflection.Metadata.MetadataReader.TypeDefTable, and System.Reflection.Metadata.MetadataReader.ProjectionInfo.WinRTNamespace.
Referenced by System.Reflection.Metadata.MetadataReader.CalculateTypeDefTreatmentAndRowId().