Terraria: Terraria.Minecart.TrackRotation
TrackRotation()
static float Terraria.Minecart.TrackRotation (Player player, ref float rotation, Vector2 Position, int Width, int Height, bool followDown, bool followUp, Mount::MountDelegatesData delegatesData) inline static
Definition at line 1248 of file Minecart.cs.
    {
        GetWheelsPositions(player, Position, Width, Height, followDown, followUp, delegatesData, out var leftWheel, out var rightWheel);
        float num = rightWheel.Y - leftWheel.Y;
        float num2 = rightWheel.X - leftWheel.X;
        float num3 = num / num2;
        float num4 = leftWheel.Y + (Position.X - leftWheel.X) * num3;
        float num5 = (Position.X - (float)(int)Position.X) * num3;
        rotation = (float)Math.Atan2(num, num2);
        return num4 - Position.Y + num5;
    }
References System.Math.Atan2(), and Terraria.Minecart.GetWheelsPositions().
Referenced by Terraria.Player.Update().