Terraria: System.Reflection.Metadata.MetadataReader.CalculateTypeDefTreatmentAndRowId
CalculateTypeDefTreatmentAndRowId()
uint System.Reflection.Metadata.MetadataReader.CalculateTypeDefTreatmentAndRowId (TypeDefinitionHandle handle) inline package
Definition at line 1457 of file MetadataReader.cs.
    {
        TypeAttributes flags = TypeDefTable.GetFlags(handle);
        EntityHandle extends = TypeDefTable.GetExtends(handle);
        TypeDefTreatment typeDefTreatment;
        if ((flags & TypeAttributes.WindowsRuntime) == 0)
        {
            typeDefTreatment = ((_metadataKind == MetadataKind.ManagedWindowsMetadata && IsClrImplementationType(handle)) ? TypeDefTreatment.UnmangleWinRTName : TypeDefTreatment.None);
        }
        else
        {
            if (_metadataKind != MetadataKind.WindowsMetadata)
            {
                typeDefTreatment = ((_metadataKind == MetadataKind.ManagedWindowsMetadata && NeedsWinRTPrefix(flags, extends)) ? TypeDefTreatment.PrefixWinRTName : TypeDefTreatment.None);
            }
            else
            {
                typeDefTreatment = GetWellKnownTypeDefinitionTreatment(handle);
                if (typeDefTreatment != 0)
                {
                    return TreatmentAndRowId((byte)typeDefTreatment, handle.RowId);
                }
                typeDefTreatment = ((extends.Kind != HandleKind.TypeReference || !IsSystemAttribute((TypeReferenceHandle)extends)) ? TypeDefTreatment.NormalNonAttribute : TypeDefTreatment.NormalAttribute);
            }
            if ((typeDefTreatment == TypeDefTreatment.PrefixWinRTName || typeDefTreatment == TypeDefTreatment.NormalNonAttribute) && (flags & TypeAttributes.ClassSemanticsMask) == 0 && HasAttribute(handle, "Windows.UI.Xaml", "TreatAsAbstractComposableClassAttribute"))
            {
                typeDefTreatment |= TypeDefTreatment.MarkAbstractFlag;
            }
        }
        return TreatmentAndRowId((byte)typeDefTreatment, handle.RowId);
    }
References System.Reflection.Metadata.MetadataReader._metadataKind, System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFlags(), System.Reflection.Metadata.MetadataReader.GetWellKnownTypeDefinitionTreatment(), System.handle, System.Reflection.Metadata.MetadataReader.HasAttribute(), System.Reflection.Metadata.MetadataReader.IsClrImplementationType(), System.Reflection.Metadata.MetadataReader.IsSystemAttribute(), System.Reflection.Metadata.MetadataReader.NeedsWinRTPrefix(), System.Reflection.Metadata.MetadataReader.TreatmentAndRowId(), and System.Reflection.Metadata.MetadataReader.TypeDefTable.
Referenced by System.Reflection.Metadata.MetadataReader.GetTypeDefTreatmentAndRowId().