Terraria: System.Reflection.Metadata.MetadataReader.GetAttributeTypeNameRaw
GetAttributeTypeNameRaw()
bool System.Reflection.Metadata.MetadataReader.GetAttributeTypeNameRaw (CustomAttributeHandle caHandle, out StringHandle namespaceName, out StringHandle typeName) inline private
Definition at line 1793 of file MetadataReader.cs.
    {
        namespaceName = (typeName = default(StringHandle));
        EntityHandle attributeTypeRaw = GetAttributeTypeRaw(caHandle);
        if (attributeTypeRaw.IsNil)
        {
            return false;
        }
        if (attributeTypeRaw.Kind == HandleKind.TypeReference)
        {
            TypeReferenceHandle handle = (TypeReferenceHandle)attributeTypeRaw;
            EntityHandle resolutionScope = TypeRefTable.GetResolutionScope(handle);
            if (!resolutionScope.IsNil && resolutionScope.Kind == HandleKind.TypeReference)
            {
                return false;
            }
            typeName = TypeRefTable.GetName(handle);
            namespaceName = TypeRefTable.GetNamespace(handle);
        }
        else
        {
            if (attributeTypeRaw.Kind != HandleKind.TypeDefinition)
            {
                return false;
            }
            TypeDefinitionHandle handle2 = (TypeDefinitionHandle)attributeTypeRaw;
            if (TypeDefTable.GetFlags(handle2).IsNested())
            {
                return false;
            }
            typeName = TypeDefTable.GetName(handle2);
            namespaceName = TypeDefTable.GetNamespace(handle2);
        }
        return true;
    }
References System.Reflection.Metadata.MetadataReader.GetAttributeTypeRaw(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetNamespace(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetNamespace(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetResolutionScope(), System.handle, System.Reflection.Metadata.MetadataReader.TypeDefTable, and System.Reflection.Metadata.MetadataReader.TypeRefTable.
Referenced by System.Reflection.Metadata.MetadataReader.GetMethodTreatmentFromCustomAttributes(), and System.Reflection.Metadata.MetadataReader.HasAttribute().