Terraria: System.Reflection.Metadata.MetadataReader.TreatmentAndRowId
TreatmentAndRowId()
static uint System.Reflection.Metadata.MetadataReader.TreatmentAndRowId (byte treatment, int rowId) inline static private
Definition at line 1451 of file MetadataReader.cs.
    {
        return (uint)((treatment << 24) | rowId);
    }
Referenced by System.Reflection.Metadata.MetadataReader.CalculateFieldDefTreatmentAndRowId(), System.Reflection.Metadata.MetadataReader.CalculateMemberRefTreatmentAndRowId(), System.Reflection.Metadata.MetadataReader.CalculateMethodDefTreatmentAndRowId(), System.Reflection.Metadata.MetadataReader.CalculateTypeDefTreatmentAndRowId(), System.Reflection.Metadata.MetadataReader.CalculateTypeRefTreatmentAndRowId(), and System.Reflection.Metadata.MetadataReader.GetCustomAttributeTreatmentAndRowId().