Terraria: System.Reflection.Metadata.MetadataReader.InitializeTableReaders
InitializeTableReaders()
void System.Reflection.Metadata.MetadataReader.InitializeTableReaders (MemoryBlock metadataTablesMemoryBlock, HeapSizes heapSizes, int[] rowCounts, int[] externalRowCountsOpt) inline private
Definition at line 593 of file MetadataReader.cs.
    {
        TableRowCounts = rowCounts;
        int fieldRefSize = ((GetReferenceSize(rowCounts, TableIndex.FieldPtr) > 2) ? 4 : GetReferenceSize(rowCounts, TableIndex.Field));
        int methodRefSize = ((GetReferenceSize(rowCounts, TableIndex.MethodPtr) > 2) ? 4 : GetReferenceSize(rowCounts, TableIndex.MethodDef));
        int paramRefSize = ((GetReferenceSize(rowCounts, TableIndex.ParamPtr) > 2) ? 4 : GetReferenceSize(rowCounts, TableIndex.Param));
        int eventRefSize = ((GetReferenceSize(rowCounts, TableIndex.EventPtr) > 2) ? 4 : GetReferenceSize(rowCounts, TableIndex.Event));
        int propertyRefSize = ((GetReferenceSize(rowCounts, TableIndex.PropertyPtr) > 2) ? 4 : GetReferenceSize(rowCounts, TableIndex.Property));
        int typeDefOrRefRefSize = ComputeCodedTokenSize(16384, rowCounts, TableMask.TypeRef | TableMask.TypeDef | TableMask.TypeSpec);
        int hasConstantRefSize = ComputeCodedTokenSize(16384, rowCounts, TableMask.Field | TableMask.Param | TableMask.Property);
        int hasCustomAttributeRefSize = ComputeCodedTokenSize(2048, rowCounts, TableMask.Module | TableMask.TypeRef | TableMask.TypeDef | TableMask.Field | TableMask.MethodDef | TableMask.Param | TableMask.InterfaceImpl | TableMask.MemberRef | TableMask.DeclSecurity | TableMask.StandAloneSig | TableMask.Event | TableMask.Property | TableMask.ModuleRef | TableMask.TypeSpec | TableMask.Assembly | TableMask.AssemblyRef | TableMask.File | TableMask.ExportedType | TableMask.ManifestResource | TableMask.GenericParam | TableMask.MethodSpec | TableMask.GenericParamConstraint);
        int hasFieldMarshalRefSize = ComputeCodedTokenSize(32768, rowCounts, TableMask.Field | TableMask.Param);
        int hasDeclSecurityRefSize = ComputeCodedTokenSize(16384, rowCounts, TableMask.TypeDef | TableMask.MethodDef | TableMask.Assembly);
        int memberRefParentRefSize = ComputeCodedTokenSize(8192, rowCounts, TableMask.TypeRef | TableMask.TypeDef | TableMask.MethodDef | TableMask.ModuleRef | TableMask.TypeSpec);
        int hasSemanticRefSize = ComputeCodedTokenSize(32768, rowCounts, TableMask.Event | TableMask.Property);
        int methodDefOrRefRefSize = ComputeCodedTokenSize(32768, rowCounts, TableMask.MethodDef | TableMask.MemberRef);
        int memberForwardedRefSize = ComputeCodedTokenSize(32768, rowCounts, TableMask.Field | TableMask.MethodDef);
        int implementationRefSize = ComputeCodedTokenSize(16384, rowCounts, TableMask.AssemblyRef | TableMask.File | TableMask.ExportedType);
        int customAttributeTypeRefSize = ComputeCodedTokenSize(8192, rowCounts, TableMask.MethodDef | TableMask.MemberRef);
        int resolutionScopeRefSize = ComputeCodedTokenSize(16384, rowCounts, TableMask.Module | TableMask.TypeRef | TableMask.ModuleRef | TableMask.AssemblyRef);
        int typeOrMethodDefRefSize = ComputeCodedTokenSize(32768, rowCounts, TableMask.TypeDef | TableMask.MethodDef);
        int stringHeapRefSize = (((heapSizes & HeapSizes.StringHeapLarge) == HeapSizes.StringHeapLarge) ? 4 : 2);
        int guidHeapRefSize = (((heapSizes & HeapSizes.GuidHeapLarge) == HeapSizes.GuidHeapLarge) ? 4 : 2);
        int blobHeapRefSize = (((heapSizes & HeapSizes.BlobHeapLarge) == HeapSizes.BlobHeapLarge) ? 4 : 2);
        int num = 0;
        ModuleTable = new ModuleTableReader(rowCounts[0], stringHeapRefSize, guidHeapRefSize, metadataTablesMemoryBlock, num);
        num += ModuleTable.Block.Length;
        TypeRefTable = new TypeRefTableReader(rowCounts[1], resolutionScopeRefSize, stringHeapRefSize, metadataTablesMemoryBlock, num);
        num += TypeRefTable.Block.Length;
        TypeDefTable = new TypeDefTableReader(rowCounts[2], fieldRefSize, methodRefSize, typeDefOrRefRefSize, stringHeapRefSize, metadataTablesMemoryBlock, num);
        num += TypeDefTable.Block.Length;
        FieldPtrTable = new FieldPtrTableReader(rowCounts[3], GetReferenceSize(rowCounts, TableIndex.Field), metadataTablesMemoryBlock, num);
        num += FieldPtrTable.Block.Length;
        FieldTable = new FieldTableReader(rowCounts[4], stringHeapRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += FieldTable.Block.Length;
        MethodPtrTable = new MethodPtrTableReader(rowCounts[5], GetReferenceSize(rowCounts, TableIndex.MethodDef), metadataTablesMemoryBlock, num);
        num += MethodPtrTable.Block.Length;
        MethodDefTable = new MethodTableReader(rowCounts[6], paramRefSize, stringHeapRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += MethodDefTable.Block.Length;
        ParamPtrTable = new ParamPtrTableReader(rowCounts[7], GetReferenceSize(rowCounts, TableIndex.Param), metadataTablesMemoryBlock, num);
        num += ParamPtrTable.Block.Length;
        ParamTable = new ParamTableReader(rowCounts[8], stringHeapRefSize, metadataTablesMemoryBlock, num);
        num += ParamTable.Block.Length;
        InterfaceImplTable = new InterfaceImplTableReader(rowCounts[9], IsDeclaredSorted(TableMask.InterfaceImpl), GetReferenceSize(rowCounts, TableIndex.TypeDef), typeDefOrRefRefSize, metadataTablesMemoryBlock, num);
        num += InterfaceImplTable.Block.Length;
        MemberRefTable = new MemberRefTableReader(rowCounts[10], memberRefParentRefSize, stringHeapRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += MemberRefTable.Block.Length;
        ConstantTable = new ConstantTableReader(rowCounts[11], IsDeclaredSorted(TableMask.Constant), hasConstantRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += ConstantTable.Block.Length;
        CustomAttributeTable = new CustomAttributeTableReader(rowCounts[12], IsDeclaredSorted(TableMask.CustomAttribute), hasCustomAttributeRefSize, customAttributeTypeRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += CustomAttributeTable.Block.Length;
        FieldMarshalTable = new FieldMarshalTableReader(rowCounts[13], IsDeclaredSorted(TableMask.FieldMarshal), hasFieldMarshalRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += FieldMarshalTable.Block.Length;
        DeclSecurityTable = new DeclSecurityTableReader(rowCounts[14], IsDeclaredSorted(TableMask.DeclSecurity), hasDeclSecurityRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += DeclSecurityTable.Block.Length;
        ClassLayoutTable = new ClassLayoutTableReader(rowCounts[15], IsDeclaredSorted(TableMask.ClassLayout), GetReferenceSize(rowCounts, TableIndex.TypeDef), metadataTablesMemoryBlock, num);
        num += ClassLayoutTable.Block.Length;
        FieldLayoutTable = new FieldLayoutTableReader(rowCounts[16], IsDeclaredSorted(TableMask.FieldLayout), GetReferenceSize(rowCounts, TableIndex.Field), metadataTablesMemoryBlock, num);
        num += FieldLayoutTable.Block.Length;
        StandAloneSigTable = new StandAloneSigTableReader(rowCounts[17], blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += StandAloneSigTable.Block.Length;
        EventMapTable = new EventMapTableReader(rowCounts[18], GetReferenceSize(rowCounts, TableIndex.TypeDef), eventRefSize, metadataTablesMemoryBlock, num);
        num += EventMapTable.Block.Length;
        EventPtrTable = new EventPtrTableReader(rowCounts[19], GetReferenceSize(rowCounts, TableIndex.Event), metadataTablesMemoryBlock, num);
        num += EventPtrTable.Block.Length;
        EventTable = new EventTableReader(rowCounts[20], typeDefOrRefRefSize, stringHeapRefSize, metadataTablesMemoryBlock, num);
        num += EventTable.Block.Length;
        PropertyMapTable = new PropertyMapTableReader(rowCounts[21], GetReferenceSize(rowCounts, TableIndex.TypeDef), propertyRefSize, metadataTablesMemoryBlock, num);
        num += PropertyMapTable.Block.Length;
        PropertyPtrTable = new PropertyPtrTableReader(rowCounts[22], GetReferenceSize(rowCounts, TableIndex.Property), metadataTablesMemoryBlock, num);
        num += PropertyPtrTable.Block.Length;
        PropertyTable = new PropertyTableReader(rowCounts[23], stringHeapRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += PropertyTable.Block.Length;
        MethodSemanticsTable = new MethodSemanticsTableReader(rowCounts[24], IsDeclaredSorted(TableMask.MethodSemantics), GetReferenceSize(rowCounts, TableIndex.MethodDef), hasSemanticRefSize, metadataTablesMemoryBlock, num);
        num += MethodSemanticsTable.Block.Length;
        MethodImplTable = new MethodImplTableReader(rowCounts[25], IsDeclaredSorted(TableMask.MethodImpl), GetReferenceSize(rowCounts, TableIndex.TypeDef), methodDefOrRefRefSize, metadataTablesMemoryBlock, num);
        num += MethodImplTable.Block.Length;
        ModuleRefTable = new ModuleRefTableReader(rowCounts[26], stringHeapRefSize, metadataTablesMemoryBlock, num);
        num += ModuleRefTable.Block.Length;
        TypeSpecTable = new TypeSpecTableReader(rowCounts[27], blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += TypeSpecTable.Block.Length;
        ImplMapTable = new ImplMapTableReader(rowCounts[28], IsDeclaredSorted(TableMask.ImplMap), GetReferenceSize(rowCounts, TableIndex.ModuleRef), memberForwardedRefSize, stringHeapRefSize, metadataTablesMemoryBlock, num);
        num += ImplMapTable.Block.Length;
        FieldRvaTable = new FieldRVATableReader(rowCounts[29], IsDeclaredSorted(TableMask.FieldRva), GetReferenceSize(rowCounts, TableIndex.Field), metadataTablesMemoryBlock, num);
        num += FieldRvaTable.Block.Length;
        EncLogTable = new EnCLogTableReader(rowCounts[30], metadataTablesMemoryBlock, num, _metadataStreamKind);
        num += EncLogTable.Block.Length;
        EncMapTable = new EnCMapTableReader(rowCounts[31], metadataTablesMemoryBlock, num);
        num += EncMapTable.Block.Length;
        AssemblyTable = new AssemblyTableReader(rowCounts[32], stringHeapRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += AssemblyTable.Block.Length;
        AssemblyProcessorTable = new AssemblyProcessorTableReader(rowCounts[33], metadataTablesMemoryBlock, num);
        num += AssemblyProcessorTable.Block.Length;
        AssemblyOSTable = new AssemblyOSTableReader(rowCounts[34], metadataTablesMemoryBlock, num);
        num += AssemblyOSTable.Block.Length;
        AssemblyRefTable = new AssemblyRefTableReader(rowCounts[35], stringHeapRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num, _metadataKind);
        num += AssemblyRefTable.Block.Length;
        AssemblyRefProcessorTable = new AssemblyRefProcessorTableReader(rowCounts[36], GetReferenceSize(rowCounts, TableIndex.AssemblyRef), metadataTablesMemoryBlock, num);
        num += AssemblyRefProcessorTable.Block.Length;
        AssemblyRefOSTable = new AssemblyRefOSTableReader(rowCounts[37], GetReferenceSize(rowCounts, TableIndex.AssemblyRef), metadataTablesMemoryBlock, num);
        num += AssemblyRefOSTable.Block.Length;
        FileTable = new FileTableReader(rowCounts[38], stringHeapRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += FileTable.Block.Length;
        ExportedTypeTable = new ExportedTypeTableReader(rowCounts[39], implementationRefSize, stringHeapRefSize, metadataTablesMemoryBlock, num);
        num += ExportedTypeTable.Block.Length;
        ManifestResourceTable = new ManifestResourceTableReader(rowCounts[40], implementationRefSize, stringHeapRefSize, metadataTablesMemoryBlock, num);
        num += ManifestResourceTable.Block.Length;
        NestedClassTable = new NestedClassTableReader(rowCounts[41], IsDeclaredSorted(TableMask.NestedClass), GetReferenceSize(rowCounts, TableIndex.TypeDef), metadataTablesMemoryBlock, num);
        num += NestedClassTable.Block.Length;
        GenericParamTable = new GenericParamTableReader(rowCounts[42], IsDeclaredSorted(TableMask.GenericParam), typeOrMethodDefRefSize, stringHeapRefSize, metadataTablesMemoryBlock, num);
        num += GenericParamTable.Block.Length;
        MethodSpecTable = new MethodSpecTableReader(rowCounts[43], methodDefOrRefRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += MethodSpecTable.Block.Length;
        GenericParamConstraintTable = new GenericParamConstraintTableReader(rowCounts[44], IsDeclaredSorted(TableMask.GenericParamConstraint), GetReferenceSize(rowCounts, TableIndex.GenericParam), typeDefOrRefRefSize, metadataTablesMemoryBlock, num);
        num += GenericParamConstraintTable.Block.Length;
        int[] rowCounts2 = ((externalRowCountsOpt != null) ? CombineRowCounts(rowCounts, externalRowCountsOpt, TableIndex.Document) : rowCounts);
        int referenceSize = GetReferenceSize(rowCounts2, TableIndex.MethodDef);
        int hasCustomDebugInformationRefSize = ComputeCodedTokenSize(2048, rowCounts2, TableMask.Module | TableMask.TypeRef | TableMask.TypeDef | TableMask.Field | TableMask.MethodDef | TableMask.Param | TableMask.InterfaceImpl | TableMask.MemberRef | TableMask.DeclSecurity | TableMask.StandAloneSig | TableMask.Event | TableMask.Property | TableMask.ModuleRef | TableMask.TypeSpec | TableMask.Assembly | TableMask.AssemblyRef | TableMask.File | TableMask.ExportedType | TableMask.ManifestResource | TableMask.GenericParam | TableMask.MethodSpec | TableMask.GenericParamConstraint | TableMask.Document | TableMask.LocalScope | TableMask.LocalVariable | TableMask.LocalConstant | TableMask.ImportScope);
        DocumentTable = new DocumentTableReader(rowCounts[48], guidHeapRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += DocumentTable.Block.Length;
        MethodDebugInformationTable = new MethodDebugInformationTableReader(rowCounts[49], GetReferenceSize(rowCounts, TableIndex.Document), blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += MethodDebugInformationTable.Block.Length;
        LocalScopeTable = new LocalScopeTableReader(rowCounts[50], IsDeclaredSorted(TableMask.LocalScope), referenceSize, GetReferenceSize(rowCounts, TableIndex.ImportScope), GetReferenceSize(rowCounts, TableIndex.LocalVariable), GetReferenceSize(rowCounts, TableIndex.LocalConstant), metadataTablesMemoryBlock, num);
        num += LocalScopeTable.Block.Length;
        LocalVariableTable = new LocalVariableTableReader(rowCounts[51], stringHeapRefSize, metadataTablesMemoryBlock, num);
        num += LocalVariableTable.Block.Length;
        LocalConstantTable = new LocalConstantTableReader(rowCounts[52], stringHeapRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += LocalConstantTable.Block.Length;
        ImportScopeTable = new ImportScopeTableReader(rowCounts[53], GetReferenceSize(rowCounts, TableIndex.ImportScope), blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += ImportScopeTable.Block.Length;
        StateMachineMethodTable = new StateMachineMethodTableReader(rowCounts[54], IsDeclaredSorted(TableMask.StateMachineMethod), referenceSize, metadataTablesMemoryBlock, num);
        num += StateMachineMethodTable.Block.Length;
        CustomDebugInformationTable = new CustomDebugInformationTableReader(rowCounts[55], IsDeclaredSorted(TableMask.CustomDebugInformation), hasCustomDebugInformationRefSize, guidHeapRefSize, blobHeapRefSize, metadataTablesMemoryBlock, num);
        num += CustomDebugInformationTable.Block.Length;
        if (num > metadataTablesMemoryBlock.Length)
        {
            throw new BadImageFormatException(System.SR.MetadataTablesTooSmall);
        }
    }
References System.Reflection.Metadata.MetadataReader._metadataKind, System.Reflection.Metadata.MetadataReader._metadataStreamKind, System.Reflection.Metadata.MetadataReader.AssemblyOSTable, System.Reflection.Metadata.MetadataReader.AssemblyProcessorTable, System.Reflection.Metadata.MetadataReader.AssemblyRefOSTable, System.Reflection.Metadata.MetadataReader.AssemblyRefProcessorTable, System.Reflection.Metadata.MetadataReader.AssemblyRefTable, System.Reflection.Metadata.MetadataReader.AssemblyTable, System.Reflection.Metadata.Ecma335.AssemblyOSTableReader.Block, System.Reflection.Metadata.Ecma335.AssemblyProcessorTableReader.Block, System.Reflection.Metadata.Ecma335.AssemblyRefOSTableReader.Block, System.Reflection.Metadata.Ecma335.AssemblyRefProcessorTableReader.Block, System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.Block, System.Reflection.Metadata.Ecma335.AssemblyTableReader.Block, System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.Block, System.Reflection.Metadata.Ecma335.ConstantTableReader.Block, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.Block, System.Reflection.Metadata.Ecma335.CustomDebugInformationTableReader.Block, System.Reflection.Metadata.Ecma335.DeclSecurityTableReader.Block, System.Reflection.Metadata.Ecma335.DocumentTableReader.Block, System.Reflection.Metadata.Ecma335.EnCLogTableReader.Block, System.Reflection.Metadata.Ecma335.EnCMapTableReader.Block, System.Reflection.Metadata.Ecma335.EventMapTableReader.Block, System.Reflection.Metadata.Ecma335.EventPtrTableReader.Block, System.Reflection.Metadata.Ecma335.EventTableReader.Block, System.Reflection.Metadata.Ecma335.ExportedTypeTableReader.Block, System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.Block, System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.Block, System.Reflection.Metadata.Ecma335.FieldPtrTableReader.Block, System.Reflection.Metadata.Ecma335.FieldRVATableReader.Block, System.Reflection.Metadata.Ecma335.FieldTableReader.Block, System.Reflection.Metadata.Ecma335.FileTableReader.Block, System.Reflection.Metadata.Ecma335.GenericParamConstraintTableReader.Block, System.Reflection.Metadata.Ecma335.GenericParamTableReader.Block, System.Reflection.Metadata.Ecma335.ImplMapTableReader.Block, System.Reflection.Metadata.Ecma335.ImportScopeTableReader.Block, System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.Block, System.Reflection.Metadata.Ecma335.LocalConstantTableReader.Block, System.Reflection.Metadata.Ecma335.LocalScopeTableReader.Block, System.Reflection.Metadata.Ecma335.LocalVariableTableReader.Block, System.Reflection.Metadata.Ecma335.ManifestResourceTableReader.Block, System.Reflection.Metadata.Ecma335.MemberRefTableReader.Block, System.Reflection.Metadata.Ecma335.MethodDebugInformationTableReader.Block, System.Reflection.Metadata.Ecma335.MethodImplTableReader.Block, System.Reflection.Metadata.Ecma335.MethodPtrTableReader.Block, System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.Block, System.Reflection.Metadata.Ecma335.MethodSpecTableReader.Block, System.Reflection.Metadata.Ecma335.MethodTableReader.Block, System.Reflection.Metadata.Ecma335.ModuleRefTableReader.Block, System.Reflection.Metadata.Ecma335.ModuleTableReader.Block, System.Reflection.Metadata.Ecma335.NestedClassTableReader.Block, System.Reflection.Metadata.Ecma335.ParamPtrTableReader.Block, System.Reflection.Metadata.Ecma335.ParamTableReader.Block, System.Reflection.Metadata.Ecma335.PropertyMapTableReader.Block, System.Reflection.Metadata.Ecma335.PropertyPtrTableReader.Block, System.Reflection.Metadata.Ecma335.PropertyTableReader.Block, System.Reflection.Metadata.Ecma335.StandAloneSigTableReader.Block, System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader.Block, System.Reflection.Metadata.Ecma335.TypeDefTableReader.Block, System.Reflection.Metadata.Ecma335.TypeRefTableReader.Block, System.Reflection.Metadata.Ecma335.TypeSpecTableReader.Block, System.Reflection.Metadata.MetadataReader.ClassLayoutTable, System.Reflection.Metadata.MetadataReader.CombineRowCounts(), System.Reflection.Metadata.MetadataReader.ComputeCodedTokenSize(), System.Reflection.Metadata.MetadataReader.ConstantTable, System.Reflection.Metadata.MetadataReader.CustomAttributeTable, System.Reflection.Metadata.MetadataReader.CustomDebugInformationTable, System.Reflection.Metadata.MetadataReader.DeclSecurityTable, System.Reflection.Metadata.MetadataReader.DocumentTable, System.Reflection.Metadata.MetadataReader.EncLogTable, System.Reflection.Metadata.MetadataReader.EncMapTable, System.Reflection.Metadata.MetadataReader.EventMapTable, System.Reflection.Metadata.MetadataReader.EventPtrTable, System.Reflection.Metadata.MetadataReader.EventTable, System.Reflection.Metadata.MetadataReader.ExportedTypeTable, System.Reflection.Metadata.MetadataReader.FieldLayoutTable, System.Reflection.Metadata.MetadataReader.FieldMarshalTable, System.Reflection.Metadata.MetadataReader.FieldPtrTable, System.Reflection.Metadata.MetadataReader.FieldRvaTable, System.Reflection.Metadata.MetadataReader.FieldTable, System.Reflection.Metadata.MetadataReader.FileTable, System.Reflection.Metadata.MetadataReader.GenericParamConstraintTable, System.Reflection.Metadata.MetadataReader.GenericParamTable, System.Reflection.Metadata.MetadataReader.GetReferenceSize(), System.Reflection.Metadata.MetadataReader.ImplMapTable, System.Reflection.Metadata.MetadataReader.ImportScopeTable, System.Reflection.Metadata.MetadataReader.InterfaceImplTable, System.Reflection.Metadata.MetadataReader.IsDeclaredSorted(), System.Reflection.Internal.MemoryBlock.Length, System.Reflection.Metadata.MetadataReader.LocalConstantTable, System.Reflection.Metadata.MetadataReader.LocalScopeTable, System.Reflection.Metadata.MetadataReader.LocalVariableTable, System.Reflection.Metadata.MetadataReader.ManifestResourceTable, System.Reflection.Metadata.MetadataReader.MemberRefTable, System.SR.MetadataTablesTooSmall, System.Reflection.Metadata.MetadataReader.MethodDebugInformationTable, System.Reflection.Metadata.MetadataReader.MethodDefTable, System.Reflection.Metadata.MetadataReader.MethodImplTable, System.Reflection.Metadata.MetadataReader.MethodPtrTable, System.Reflection.Metadata.MetadataReader.MethodSemanticsTable, System.Reflection.Metadata.MetadataReader.MethodSpecTable, System.Reflection.Metadata.MetadataReader.ModuleRefTable, System.Reflection.Metadata.MetadataReader.ModuleTable, System.Reflection.Metadata.MetadataReader.NestedClassTable, System.Reflection.Metadata.MetadataReader.ParamPtrTable, System.Reflection.Metadata.MetadataReader.ParamTable, System.Reflection.Metadata.MetadataReader.PropertyMapTable, System.Reflection.Metadata.MetadataReader.PropertyPtrTable, System.Reflection.Metadata.MetadataReader.PropertyTable, System.Reflection.Metadata.MetadataReader.StandAloneSigTable, System.Reflection.Metadata.MetadataReader.StateMachineMethodTable, System.Reflection.Metadata.MetadataReader.TableRowCounts, System.Reflection.Metadata.MetadataReader.TypeDefTable, System.Reflection.Metadata.MetadataReader.TypeRefTable, and System.Reflection.Metadata.MetadataReader.TypeSpecTable.
Referenced by System.Reflection.Metadata.MetadataReader.MetadataReader().