Terraria: System.Transactions.TransactionStatePromotedBase.CompleteAbortingClone
CompleteAbortingClone()
override void System.Transactions.TransactionStatePromotedBase.CompleteAbortingClone (InternalTransaction tx) inline package virtual inherited
Reimplemented from System.Transactions.TransactionState.
Definition at line 164 of file TransactionStatePromotedBase.cs.
    {
        if (tx._phase1Volatiles.VolatileDemux != null)
        {
            tx._phase1Volatiles._dependentClones--;
            return;
        }
        tx._abortingDependentCloneCount--;
        if (tx._abortingDependentCloneCount != 0)
        {
            return;
        }
        DistributedDependentTransaction abortingDependentClone = tx._abortingDependentClone;
        tx._abortingDependentClone = null;
        Monitor.Exit(tx);
        try
        {
            try
            {
                abortingDependentClone.Complete();
            }
            finally
            {
                abortingDependentClone.Dispose();
            }
        }
        finally
        {
            Monitor.Enter(tx);
        }
    }
References System.Transactions.InternalTransaction._abortingDependentClone, System.Transactions.InternalTransaction._abortingDependentCloneCount, System.Transactions.VolatileEnlistmentSet._dependentClones, System.Transactions.InternalTransaction._phase1Volatiles, System.Transactions.Distributed.DistributedDependentTransaction.Complete(), System.Transactions.Distributed.DistributedTransaction.Dispose(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), and System.Transactions.VolatileEnlistmentSet.VolatileDemux.