Terraria: System.Reflection.Metadata.MetadataReader.GetAttributeTypeRaw
GetAttributeTypeRaw()
EntityHandle System.Reflection.Metadata.MetadataReader.GetAttributeTypeRaw (CustomAttributeHandle handle) inline private
Definition at line 1829 of file MetadataReader.cs.
    {
        EntityHandle constructor = CustomAttributeTable.GetConstructor(handle);
        if (constructor.Kind == HandleKind.MethodDefinition)
        {
            return GetDeclaringType((MethodDefinitionHandle)constructor);
        }
        if (constructor.Kind == HandleKind.MemberReference)
        {
            EntityHandle @class = MemberRefTable.GetClass((MemberReferenceHandle)constructor);
            HandleKind kind = @class.Kind;
            if (kind == HandleKind.TypeReference || kind == HandleKind.TypeDefinition)
            {
                return @class;
            }
        }
        return default(EntityHandle);
    }
References System.Reflection.Metadata.MetadataReader.CustomAttributeTable, System.Reflection.Metadata.Ecma335.MemberRefTableReader.GetClass(), System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetConstructor(), System.Reflection.Metadata.MetadataReader.GetDeclaringType(), System.handle, System.Reflection.Metadata.EntityHandle.Kind, and System.Reflection.Metadata.MetadataReader.MemberRefTable.
Referenced by System.Reflection.Metadata.MetadataReader.GetAttributeTypeNameRaw().