Terraria: System.Transactions.TransactionStatePromotedBase.EnlistVolatile
EnlistVolatile() [2/2]
override Enlistment System.Transactions.TransactionStatePromotedBase.EnlistVolatile (InternalTransaction tx, ISinglePhaseNotification enlistmentNotification, EnlistmentOptions enlistmentOptions, Transaction atomicTransaction) inline package virtual inherited
Reimplemented from System.Transactions.TransactionState.
Definition at line 29 of file TransactionStatePromotedBase.cs.
    {
        Monitor.Exit(tx);
        try
        {
            Enlistment enlistment = new Enlistment(enlistmentNotification, tx, atomicTransaction);
            EnlistmentState.EnlistmentStatePromoted.EnterState(enlistment.InternalEnlistment);
            enlistment.InternalEnlistment.PromotedEnlistment = tx.PromotedTransaction.EnlistVolatile(enlistment.InternalEnlistment, enlistmentOptions);
            return enlistment;
        }
        finally
        {
            Monitor.Enter(tx);
        }
    }
References System.Transactions.EnlistmentState.EnlistmentStatePromoted, System.Transactions.Distributed.DistributedTransaction.EnlistVolatile(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Transactions.Enlistment.InternalEnlistment, and System.Transactions.InternalTransaction.PromotedTransaction.