Terraria: System.Reflection.Metadata.MetadataReader.FindMscorlibAssemblyRefNoProjection
FindMscorlibAssemblyRefNoProjection()
int System.Reflection.Metadata.MetadataReader.FindMscorlibAssemblyRefNoProjection () inline private
Definition at line 1719 of file MetadataReader.cs.
    {
        for (int i = 1; i <= AssemblyRefTable.NumberOfNonVirtualRows; i++)
        {
            if (StringHeap.EqualsRaw(AssemblyRefTable.GetName(i), "mscorlib"))
            {
                return i;
            }
        }
        throw new BadImageFormatException(System.SR.WinMDMissingMscorlibRef);
    }
References System.Reflection.Metadata.MetadataReader.AssemblyRefTable, System.Reflection.Metadata.Ecma335.StringHeap.EqualsRaw(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.NumberOfNonVirtualRows, and System.SR.WinMDMissingMscorlibRef.
Referenced by System.Reflection.Metadata.MetadataReader.MetadataReader().