Terraria: System.Reflection.Metadata.MetadataReader.GetProjectionIndexForTypeReference
GetProjectionIndexForTypeReference()
int System.Reflection.Metadata.MetadataReader.GetProjectionIndexForTypeReference (TypeReferenceHandle typeRef, out bool isIDisposable) inline private
Definition at line 1293 of file MetadataReader.cs.
    {
        InitializeProjectedTypes();
        int num = StringHeap.BinarySearchRaw(s_projectedTypeNames, TypeRefTable.GetName(typeRef));
        if (num >= 0 && StringHeap.EqualsRaw(TypeRefTable.GetNamespace(typeRef), s_projectionInfos[num].WinRTNamespace))
        {
            isIDisposable = s_projectionInfos[num].IsIDisposable;
            return num;
        }
        isIDisposable = false;
        return -1;
    }
References System.Reflection.Metadata.Ecma335.StringHeap.BinarySearchRaw(), System.Reflection.Metadata.Ecma335.StringHeap.EqualsRaw(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetNamespace(), System.Reflection.Metadata.MetadataReader.InitializeProjectedTypes(), System.Reflection.Metadata.MetadataReader.s_projectedTypeNames, System.Reflection.Metadata.MetadataReader.s_projectionInfos, and System.Reflection.Metadata.MetadataReader.TypeRefTable.
Referenced by System.Reflection.Metadata.MetadataReader.CalculateTypeRefTreatmentAndRowId(), and System.Reflection.Metadata.MetadataReader.ImplementsRedirectedInterface().