Terraria: System.Reflection.Metadata.MetadataReader.GetAssemblyName
GetAssemblyName()
AssemblyName System.Reflection.Metadata.MetadataReader.GetAssemblyName (StringHandle nameHandle, Version version, StringHandle cultureHandle, BlobHandle publicKeyOrTokenHandle, AssemblyHashAlgorithm assemblyHashAlgorithm, AssemblyFlags flags) inline package
Definition at line 257 of file MetadataReader.cs.
    {
        string @string = GetString(nameHandle);
        string cultureName = ((!cultureHandle.IsNil) ? GetString(cultureHandle) : null);
        byte[] array = ((!publicKeyOrTokenHandle.IsNil) ? GetBlobBytes(publicKeyOrTokenHandle) : null);
        AssemblyName assemblyName = new AssemblyName(@string)
        {
            Version = version,
            CultureName = cultureName,
            HashAlgorithm = (System.Configuration.Assemblies.AssemblyHashAlgorithm)assemblyHashAlgorithm,
            Flags = GetAssemblyNameFlags(flags),
            ContentType = GetContentTypeFromAssemblyFlags(flags)
        };
        if ((flags & AssemblyFlags.PublicKey) != 0)
        {
            assemblyName.SetPublicKey(array);
        }
        else
        {
            assemblyName.SetPublicKeyToken(array);
        }
        return assemblyName;
    }
References System.array, System.Reflection.Metadata.MetadataReader.GetAssemblyNameFlags(), System.Reflection.Metadata.MetadataReader.GetBlobBytes(), System.Reflection.Metadata.MetadataReader.GetContentTypeFromAssemblyFlags(), and System.Reflection.Metadata.MetadataReader.GetString().
Referenced by System.Reflection.Metadata.AssemblyDefinition.GetAssemblyName(), and System.Reflection.Metadata.AssemblyReference.GetAssemblyName().