Terraria: System.Transactions.TransactionStatePromotedBase.Rollback
Rollback()
override void System.Transactions.TransactionStatePromotedBase.Rollback (InternalTransaction tx, Exception e) inline package virtual inherited
Reimplemented from System.Transactions.TransactionState.
Definition at line 79 of file TransactionStatePromotedBase.cs.
    {
        if (tx._innerException == null)
        {
            tx._innerException = e;
        }
        Monitor.Exit(tx);
        try
        {
            tx.PromotedTransaction.Rollback();
        }
        finally
        {
            Monitor.Enter(tx);
        }
    }
References System.Transactions.InternalTransaction._innerException, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Transactions.InternalTransaction.PromotedTransaction, and System.Transactions.Distributed.DistributedTransaction.Rollback().