Terraria: Terraria.Minecart.WheelSparks
WheelSparks()
static void Terraria.Minecart.WheelSparks (Action< Vector2 > DustAction, Vector2 Position, int Width, int Height, int sparkCount) inline static
Definition at line 1615 of file Minecart.cs.
    {
        Vector2 vector = new Vector2((float)(Width / 2) - 25f, Height / 2);
        Vector2 obj = Position + vector + _trackMagnetOffset;
        for (int i = 0; i < sparkCount; i++)
        {
            DustAction(obj);
        }
    }
References Terraria.Minecart._trackMagnetOffset.
Referenced by Terraria.Player.GrappleMovement(), Terraria.Player.HorizontalMovement(), and Terraria.Minecart.TrackCollision().