Terraria: System.Reflection.Metadata.MetadataReader.ImplementsRedirectedInterface
ImplementsRedirectedInterface()
bool System.Reflection.Metadata.MetadataReader.ImplementsRedirectedInterface (MemberReferenceHandle memberRef, out bool isIDisposable) inline private
Definition at line 1688 of file MetadataReader.cs.
    {
        isIDisposable = false;
        EntityHandle @class = MemberRefTable.GetClass(memberRef);
        TypeReferenceHandle typeRef;
        if (@class.Kind == HandleKind.TypeReference)
        {
            typeRef = (TypeReferenceHandle)@class;
        }
        else
        {
            if (@class.Kind != HandleKind.TypeSpecification)
            {
                return false;
            }
            BlobHandle signature = TypeSpecTable.GetSignature((TypeSpecificationHandle)@class);
            BlobReader blobReader = new BlobReader(BlobHeap.GetMemoryBlock(signature));
            if (blobReader.Length < 2 || blobReader.ReadByte() != 21 || blobReader.ReadByte() != 18)
            {
                return false;
            }
            EntityHandle entityHandle = blobReader.ReadTypeHandle();
            if (entityHandle.Kind != HandleKind.TypeReference)
            {
                return false;
            }
            typeRef = (TypeReferenceHandle)entityHandle;
        }
        return GetProjectionIndexForTypeReference(typeRef, out isIDisposable) >= 0;
    }
References System.Reflection.Metadata.Ecma335.MemberRefTableReader.GetClass(), System.Reflection.Metadata.Ecma335.BlobHeap.GetMemoryBlock(), System.Reflection.Metadata.MetadataReader.GetProjectionIndexForTypeReference(), System.Reflection.Metadata.Ecma335.TypeSpecTableReader.GetSignature(), System.Reflection.Metadata.MetadataReader.MemberRefTable, and System.Reflection.Metadata.MetadataReader.TypeSpecTable.
Referenced by System.Reflection.Metadata.MetadataReader.CalculateMemberRefTreatmentAndRowId(), and System.Reflection.Metadata.MetadataReader.CalculateMethodDefTreatmentAndRowId().