Terraria: System.Reflection.Metadata.MetadataReader.ReadStandalonePortablePdbStream
ReadStandalonePortablePdbStream()
static void System.Reflection.Metadata.MetadataReader.ReadStandalonePortablePdbStream (MemoryBlock pdbStreamBlock, int pdbStreamOffset, out DebugMetadataHeader debugMetadataHeader, out int[] externalTableRowCounts) inline static package
Definition at line 565 of file MetadataReader.cs.
    {
        BlobReader memReader = new BlobReader(pdbStreamBlock);
        byte[] array = memReader.ReadBytes(20);
        uint num = memReader.ReadUInt32();
        int num2 = (int)(num & 0xFFFFFF);
        if (num != 0 && ((num & 0x7F000000) != 100663296 || num2 == 0))
        {
            throw new BadImageFormatException(System.SR.Format(System.SR.InvalidEntryPointToken, num));
        }
        ulong num3 = memReader.ReadUInt64();
        if ((num3 & 0xFFFFE036C04800A8uL) != 0L)
        {
            throw new BadImageFormatException(System.SR.Format(System.SR.UnknownTables, num3));
        }
        externalTableRowCounts = ReadMetadataTableRowCounts(ref memReader, num3);
        debugMetadataHeader = new DebugMetadataHeader(ImmutableByteArrayInterop.DangerousCreateFromUnderlyingArray(ref array), MethodDefinitionHandle.FromRowId(num2), pdbStreamOffset);
    }
References System.array, System.Reflection.Internal.ImmutableByteArrayInterop.DangerousCreateFromUnderlyingArray(), System.Reflection.Metadata.MetadataReader.DebugMetadataHeader, System.SR.Format(), System.Reflection.Metadata.MethodDefinitionHandle.FromRowId(), System.SR.InvalidEntryPointToken, System.L, System.Reflection.Metadata.MetadataReader.ReadMetadataTableRowCounts(), and System.SR.UnknownTables.
Referenced by System.Reflection.Metadata.MetadataReader.MetadataReader().