Terraria: System.Reflection.Metadata.MetadataReader.IsWindowsAttributeUsageAttribute
IsWindowsAttributeUsageAttribute()
bool System.Reflection.Metadata.MetadataReader.IsWindowsAttributeUsageAttribute (EntityHandle targetType, CustomAttributeHandle attributeHandle) inline private
Definition at line 1757 of file MetadataReader.cs.
    {
        if (targetType.Kind != HandleKind.TypeDefinition)
        {
            return false;
        }
        EntityHandle constructor = CustomAttributeTable.GetConstructor(attributeHandle);
        if (constructor.Kind != HandleKind.MemberReference)
        {
            return false;
        }
        EntityHandle @class = MemberRefTable.GetClass((MemberReferenceHandle)constructor);
        if (@class.Kind != HandleKind.TypeReference)
        {
            return false;
        }
        TypeReferenceHandle handle = (TypeReferenceHandle)@class;
        if (StringHeap.EqualsRaw(TypeRefTable.GetName(handle), "AttributeUsageAttribute"))
        {
            return StringHeap.EqualsRaw(TypeRefTable.GetNamespace(handle), "Windows.Foundation.Metadata");
        }
        return false;
    }
References System.Reflection.Metadata.MetadataReader.CustomAttributeTable, System.Reflection.Metadata.Ecma335.StringHeap.EqualsRaw(), System.Reflection.Metadata.Ecma335.MemberRefTableReader.GetClass(), System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetConstructor(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetNamespace(), System.handle, System.Reflection.Metadata.MetadataReader.MemberRefTable, and System.Reflection.Metadata.MetadataReader.TypeRefTable.
Referenced by System.Reflection.Metadata.MetadataReader.CalculateCustomAttributeValueTreatment().