Terraria: System.Transactions.TransactionStatePromotedBase.Timeout
Timeout()
override void System.Transactions.TransactionStatePromotedBase.Timeout (InternalTransaction tx) inline package virtual inherited
Reimplemented from System.Transactions.TransactionState.
Definition at line 244 of file TransactionStatePromotedBase.cs.
    {
        try
        {
            if (tx._innerException == null)
            {
                tx._innerException = new TimeoutException(System.SR.TraceTransactionTimeout);
            }
            tx.PromotedTransaction.Rollback();
            TransactionsEtwProvider log = TransactionsEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.TransactionTimeout(tx.TransactionTraceId);
            }
        }
        catch (TransactionException exception)
        {
            TransactionsEtwProvider log2 = TransactionsEtwProvider.Log;
            if (log2.IsEnabled())
            {
                log2.ExceptionConsumed(exception);
            }
        }
    }
References System.Transactions.InternalTransaction._innerException, System.exception, System.Transactions.TransactionsEtwProvider.ExceptionConsumed(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.InternalTransaction.PromotedTransaction, System.Transactions.Distributed.DistributedTransaction.Rollback(), System.SR.TraceTransactionTimeout, System.Transactions.TransactionsEtwProvider.TransactionTimeout(), and System.Transactions.InternalTransaction.TransactionTraceId.