Terraria: System.Reflection.Metadata.MetadataReader.GetPropertyRange
GetPropertyRange()
void System.Reflection.Metadata.MetadataReader.GetPropertyRange (TypeDefinitionHandle typeDef, out int firstPropertyRowId, out int lastPropertyRowId) inline package
Definition at line 833 of file MetadataReader.cs.
    {
        int num = PropertyMapTable.FindPropertyMapRowIdFor(typeDef);
        if (num == 0)
        {
            firstPropertyRowId = 1;
            lastPropertyRowId = 0;
            return;
        }
        firstPropertyRowId = PropertyMapTable.GetPropertyListStartFor(num);
        if (num == PropertyMapTable.NumberOfRows)
        {
            lastPropertyRowId = (UsePropertyPtrTable ? PropertyPtrTable.NumberOfRows : PropertyTable.NumberOfRows);
        }
        else
        {
            lastPropertyRowId = PropertyMapTable.GetPropertyListStartFor(num + 1) - 1;
        }
    }
References System.Reflection.Metadata.Ecma335.PropertyMapTableReader.FindPropertyMapRowIdFor(), System.Reflection.Metadata.Ecma335.PropertyMapTableReader.GetPropertyListStartFor(), System.Reflection.Metadata.Ecma335.PropertyMapTableReader.NumberOfRows, System.Reflection.Metadata.Ecma335.PropertyTableReader.NumberOfRows, System.Reflection.Metadata.MetadataReader.PropertyMapTable, System.Reflection.Metadata.MetadataReader.PropertyTable, and System.Reflection.Metadata.MetadataReader.UsePropertyPtrTable.
Referenced by System.Reflection.Metadata.PropertyDefinitionHandleCollection.PropertyDefinitionHandleCollection().