Terraria: System.Reflection.Metadata.MetadataReader.NeedsWinRTPrefix
NeedsWinRTPrefix()
bool System.Reflection.Metadata.MetadataReader.NeedsWinRTPrefix (TypeAttributes flags, EntityHandle extends) inline private
Definition at line 1536 of file MetadataReader.cs.
    {
        if ((flags & (TypeAttributes.VisibilityMask | TypeAttributes.ClassSemanticsMask)) != TypeAttributes.Public)
        {
            return false;
        }
        if (extends.Kind != HandleKind.TypeReference)
        {
            return false;
        }
        TypeReferenceHandle handle = (TypeReferenceHandle)extends;
        if (StringHeap.EqualsRaw(TypeRefTable.GetNamespace(handle), "System"))
        {
            StringHandle name = TypeRefTable.GetName(handle);
            if (StringHeap.EqualsRaw(name, "MulticastDelegate") || StringHeap.EqualsRaw(name, "ValueType") || StringHeap.EqualsRaw(name, "Attribute"))
            {
                return false;
            }
        }
        return true;
    }
References System.Reflection.Metadata.Ecma335.StringHeap.EqualsRaw(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetNamespace(), System.handle, and System.Reflection.Metadata.MetadataReader.TypeRefTable.
Referenced by System.Reflection.Metadata.MetadataReader.CalculateTypeDefTreatmentAndRowId().