Terraria: System.Reflection.Metadata.MetadataReader.IsClrImplementationType
IsClrImplementationType()
bool System.Reflection.Metadata.MetadataReader.IsClrImplementationType (TypeDefinitionHandle typeDef) inline private
Definition at line 1489 of file MetadataReader.cs.
    {
        TypeAttributes flags = TypeDefTable.GetFlags(typeDef);
        if ((flags & (TypeAttributes.VisibilityMask | TypeAttributes.SpecialName)) != TypeAttributes.SpecialName)
        {
            return false;
        }
        return StringHeap.StartsWithRaw(TypeDefTable.GetName(typeDef), "<CLR>");
    }
References System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFlags(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetName(), System.Reflection.Metadata.Ecma335.StringHeap.StartsWithRaw(), and System.Reflection.Metadata.MetadataReader.TypeDefTable.
Referenced by System.Reflection.Metadata.MetadataReader.CalculateMethodDefTreatmentAndRowId(), and System.Reflection.Metadata.MetadataReader.CalculateTypeDefTreatmentAndRowId().