Terraria: System.Reflection.Metadata.MetadataReader.ReadMetadataTableHeader
ReadMetadataTableHeader()
void System.Reflection.Metadata.MetadataReader.ReadMetadataTableHeader (ref BlobReader reader, out HeapSizes heapSizes, out int[] metadataTableRowCounts, out TableMask sortedTables) inline private
Definition at line 512 of file MetadataReader.cs.
    {
        if (reader.RemainingBytes < 24)
        {
            throw new BadImageFormatException(System.SR.MetadataTableHeaderTooSmall);
        }
        reader.ReadUInt32();
        reader.ReadByte();
        reader.ReadByte();
        heapSizes = (HeapSizes)reader.ReadByte();
        reader.ReadByte();
        ulong num = reader.ReadUInt64();
        sortedTables = (TableMask)reader.ReadUInt64();
        ulong num2 = 71811071505072127uL;
        if ((num & ~num2) != 0L)
        {
            throw new BadImageFormatException(System.SR.Format(System.SR.UnknownTables, num));
        }
        if (_metadataStreamKind == MetadataStreamKind.Compressed && (num & 0x804800A8u) != 0L)
        {
            throw new BadImageFormatException(System.SR.IllegalTablesInCompressedMetadataStream);
        }
        metadataTableRowCounts = ReadMetadataTableRowCounts(ref reader, num);
        if ((heapSizes & HeapSizes.ExtraData) == HeapSizes.ExtraData)
        {
            reader.ReadUInt32();
        }
    }
References System.Reflection.Metadata.MetadataReader._metadataStreamKind, System.SR.Format(), System.SR.IllegalTablesInCompressedMetadataStream, System.L, System.SR.MetadataTableHeaderTooSmall, System.Reflection.Metadata.MetadataReader.ReadMetadataTableRowCounts(), and System.SR.UnknownTables.
Referenced by System.Reflection.Metadata.MetadataReader.MetadataReader().