Terraria: System.Reflection.Metadata.MetadataReader.GetEventRange
GetEventRange()
void System.Reflection.Metadata.MetadataReader.GetEventRange (TypeDefinitionHandle typeDef, out int firstEventRowId, out int lastEventRowId) inline package
Definition at line 813 of file MetadataReader.cs.
    {
        int num = EventMapTable.FindEventMapRowIdFor(typeDef);
        if (num == 0)
        {
            firstEventRowId = 1;
            lastEventRowId = 0;
            return;
        }
        firstEventRowId = EventMapTable.GetEventListStartFor(num);
        if (num == EventMapTable.NumberOfRows)
        {
            lastEventRowId = (UseEventPtrTable ? EventPtrTable.NumberOfRows : EventTable.NumberOfRows);
        }
        else
        {
            lastEventRowId = EventMapTable.GetEventListStartFor(num + 1) - 1;
        }
    }
References System.Reflection.Metadata.MetadataReader.EventMapTable, System.Reflection.Metadata.MetadataReader.EventTable, System.Reflection.Metadata.Ecma335.EventMapTableReader.FindEventMapRowIdFor(), System.Reflection.Metadata.Ecma335.EventMapTableReader.GetEventListStartFor(), System.Reflection.Metadata.Ecma335.EventMapTableReader.NumberOfRows, System.Reflection.Metadata.Ecma335.EventTableReader.NumberOfRows, and System.Reflection.Metadata.MetadataReader.UseEventPtrTable.
Referenced by System.Reflection.Metadata.EventDefinitionHandleCollection.EventDefinitionHandleCollection().