Terraria: System.Net.Mail.Attachment.SetContentTypeName
SetContentTypeName()
void System.Net.Mail.Attachment.SetContentTypeName (bool allowUnicode) inline package
Definition at line 108 of file Attachment.cs.
    {
        if (!allowUnicode && _name != null && _name.Length != 0 && !MimeBasePart.IsAscii(_name, permitCROrLF: false))
        {
            Encoding encoding = NameEncoding ?? Encoding.GetEncoding("utf-8");
            base.MimePart.ContentType.Name = MimeBasePart.EncodeHeaderValue(_name, encoding, MimeBasePart.ShouldUseBase64Encoding(encoding));
        }
        else
        {
            base.MimePart.ContentType.Name = _name;
        }
    }
References System.Net.Mail.Attachment._name, System.Net.Mime.MimeBasePart.EncodeHeaderValue(), System.Text.Encoding.GetEncoding(), System.Net.Mime.MimeBasePart.IsAscii(), System.Net.Mail.Attachment.NameEncoding, and System.Net.Mime.MimeBasePart.ShouldUseBase64Encoding().
Referenced by System.Net.Mail.Attachment.PrepareForSending().