Terraria: System.Reflection.Metadata.MetadataReader.GetDeclaringType
GetDeclaringType() [2/2]
TypeDefinitionHandle System.Reflection.Metadata.MetadataReader.GetDeclaringType (MethodDefinitionHandle methodDef) inline package
Definition at line 1159 of file MetadataReader.cs.
    {
        int methodDefOrPtrRowId = ((!UseMethodPtrTable) ? methodDef.RowId : MethodPtrTable.GetRowIdForMethodDefRow(methodDef.RowId));
        return TypeDefTable.FindTypeContainingMethod(methodDefOrPtrRowId, MethodDefTable.NumberOfRows);
    }
References System.Reflection.Metadata.Ecma335.TypeDefTableReader.FindTypeContainingMethod(), System.Reflection.Metadata.Ecma335.MethodPtrTableReader.GetRowIdForMethodDefRow(), System.Reflection.Metadata.MetadataReader.MethodDefTable, System.Reflection.Metadata.MetadataReader.MethodPtrTable, System.Reflection.Metadata.Ecma335.MethodTableReader.NumberOfRows, System.Reflection.Metadata.MetadataReader.TypeDefTable, and System.Reflection.Metadata.MetadataReader.UseMethodPtrTable.
Referenced by System.Reflection.Metadata.MetadataReader.CalculateFieldDefTreatmentAndRowId(), System.Reflection.Metadata.MetadataReader.CalculateMethodDefTreatmentAndRowId(), System.Reflection.Metadata.MetadataReader.GetAttributeTypeRaw(), System.Reflection.Metadata.FieldDefinition.GetDeclaringType(), and System.Reflection.Metadata.MethodDefinition.GetDeclaringType().