Terraria: TEWeaponsRack.OnPlayerInteraction
OnPlayerInteraction()
static void TEWeaponsRack.OnPlayerInteraction (Player player, int clickX, int clickY) inline static
     {
         if (FitsWeaponFrame(player.inventory[player.selectedItem]) && !player.inventory[player.selectedItem].favorited)
         {
             player.GamepadEnableGrappleCooldown();
             PlaceItemInFrame(player, clickX, clickY);
             Recipe.FindRecipes();
             return;
         }
         int num = clickX;
         int num2 = clickY;
         num -= Main.tile[num, num2].frameX % 54 / 18;
         num2 -= Main.tile[num, num2].frameY % 54 / 18;
         int num3 = Find(num, num2);
         if (num3 != -1 && ((TEWeaponsRack)TileEntity.ByID[num3]).item.stack > 0)
         {
             player.GamepadEnableGrappleCooldown();
             WorldGen.KillTile(num, num2, fail: true);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, num, num2, 1f);
             }
         }
     }
References TileEntity.ByID, Item.favorited, Find(), Recipe.FindRecipes(), FitsWeaponFrame(), Tile.frameX, Tile.frameY, Player.GamepadEnableGrappleCooldown(), Player.inventory, WorldGen.KillTile(), Main.netMode, PlaceItemInFrame(), Player.selectedItem, NetMessage.SendData(), and Main.tile.
Referenced by Player.TileInteractionsUse().