Terraria: TEWeaponsRack.Framing_CheckTile
Framing_CheckTile()
static void TEWeaponsRack.Framing_CheckTile (int callX, int callY) inline static
     {
         int num = 3;
         int num2 = 3;
         if (WorldGen.destroyObject)
         {
             return;
         }
         int num3 = callX;
         int num4 = callY;
         Tile tileSafely = Framing.GetTileSafely(callX, callY);
         num3 -= tileSafely.frameX / 18 % num;
         num4 -= tileSafely.frameY / 18 % num2;
         bool flag = false;
         for (int i = num3; i < num3 + num; i++)
         {
             for (int j = num4; j < num4 + num2; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (!tile.active() || tile.type != 471 || tile.wall == 0)
                 {
                     flag = true;
                 }
             }
         }
         if (!flag)
         {
             return;
         }
         int num5 = Find(num3, num4);
         if (num5 != -1 && ((TEWeaponsRack)TileEntity.ByID[num5]).item.stack > 0)
         {
             ((TEWeaponsRack)TileEntity.ByID[num5]).DropItem();
             if (Main.netMode != 2)
             {
                 Main.LocalPlayer.InterruptItemUsageIfOverTile(471);
             }
         }
         WorldGen.destroyObject = true;
         for (int k = num3; k < num3 + num; k++)
         {
             for (int l = num4; l < num4 + num2; l++)
             {
                 if (Main.tile[k, l].active() && Main.tile[k, l].type == 471)
                 {
                     WorldGen.KillTile(k, l);
                 }
             }
         }
         Item.NewItem(new EntitySource_TileBreak(num3, num4), num3 * 16, num4 * 16, 48, 48, 2699);
         Kill(num3, num4);
         WorldGen.destroyObject = false;
     }
References TEWeaponsRack(), Tile.active(), TileEntity.ByID, WorldGen.destroyObject, Find(), Tile.frameX, Tile.frameY, Framing.GetTileSafely(), Player.InterruptItemUsageIfOverTile(), Kill(), WorldGen.KillTile(), Main.LocalPlayer, Main.netMode, Item.NewItem(), Main.tile, Tile.type, and Tile.wall.
Referenced by WorldGen.TileFrame().