Terraria: System.Net.HttpListenerSession.CloseRequestQueueHandle
CloseRequestQueueHandle()
unsafe void System.Net.HttpListenerSession.CloseRequestQueueHandle () inline
Definition at line 52 of file HttpListenerSession.cs.
    {
        lock (this)
        {
            if (!RequestQueueHandle.IsInvalid)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info($"Dispose ThreadPoolBoundHandle: {_requestQueueBoundHandle}", null, "CloseRequestQueueHandle");
                }
                _requestQueueBoundHandle?.Dispose();
                RequestQueueHandle.Dispose();
                try
                {
                    global::Interop.Kernel32.CancelIoEx(RequestQueueHandle, null);
                    return;
                }
                catch (ObjectDisposedException)
                {
                    return;
                }
            }
        }
    }
References System.Net.HttpListenerSession._requestQueueBoundHandle, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Threading.ThreadPoolBoundHandle.Dispose(), System.Net.NetEventSource.Info(), System.Runtime.InteropServices.SafeHandle.IsInvalid, System.Net.NetEventSource.Log, and System.Net.HttpListenerSession.RequestQueueHandle.
Referenced by System.Net.HttpListener.CloseRequestQueueHandle().