Terraria: CrashDump.Write
Write() [1/3]
static bool CrashDump.Write (Options options, ExceptionInfo exceptionInfo, string outputDirectory) inline static private
     {
         if (!Platform.IsWindows)
         {
             return false;
         }
         string path = Path.Combine(outputDirectory, CreateDumpName());
         if (!Utils.TryCreatingDirectory(outputDirectory))
         {
             return false;
         }
         using FileStream fileStream = File.Create(path);
         return Write(fileStream.SafeFileHandle, options, exceptionInfo);
     }
References CreateDumpName(), Platform.IsWindows, Utils.TryCreatingDirectory(), and Write().