Terraria: System.Text.EncodingByteBuffer.MovePrevious
MovePrevious()
unsafe void System.Text.EncodingByteBuffer.MovePrevious (bool bThrow) inline package
Definition at line 126 of file EncodingByteBuffer.cs.
    {
        if (fallbackBufferHelper.bFallingBack)
        {
            fallbackBuffer.MovePrevious();
        }
        else if (_chars > _charStart)
        {
            _chars--;
        }
        if (bThrow)
        {
            _enc.ThrowBytesOverflow(_encoder, _bytes == _byteStart);
        }
    }
References System.Text.EncodingByteBuffer._bytes, System.Text.EncodingByteBuffer._byteStart, System.Text.EncodingByteBuffer._chars, System.Text.EncodingByteBuffer._charStart, System.Text.EncodingByteBuffer._enc, System.Text.EncodingByteBuffer._encoder, System.Text.EncoderFallbackBufferHelper.bFallingBack, System.Text.EncodingByteBuffer.fallbackBuffer, System.Text.EncodingByteBuffer.fallbackBufferHelper, System.Text.EncoderFallbackBuffer.MovePrevious(), and System.Text.EncodingNLS.ThrowBytesOverflow().
Referenced by System.Text.EncodingByteBuffer.AddByte().