Terraria: System.Text.EncodingByteBuffer.EncodingByteBuffer
EncodingByteBuffer()
unsafe System.Text.EncodingByteBuffer.EncodingByteBuffer (EncodingNLS inEncoding, System::Text::EncoderNLS inEncoder, byte * inByteStart, int inByteCount, char * inCharStart, int inCharCount) inline package
Definition at line 43 of file EncodingByteBuffer.cs.
    {
        _enc = inEncoding;
        _encoder = inEncoder;
        _charStart = inCharStart;
        _chars = inCharStart;
        _charEnd = inCharStart + inCharCount;
        _bytes = inByteStart;
        _byteStart = inByteStart;
        _byteEnd = inByteStart + inByteCount;
        if (_encoder == null)
        {
            fallbackBuffer = _enc.EncoderFallback.CreateFallbackBuffer();
        }
        else
        {
            fallbackBuffer = _encoder.FallbackBuffer;
            if (_encoder.m_throwOnOverflow && _encoder.InternalHasFallbackBuffer && fallbackBuffer.Remaining > 0)
            {
                throw new ArgumentException(System.SR.Format(System.SR.Argument_EncoderFallbackNotEmpty, _encoder.Encoding.EncodingName, _encoder.Fallback.GetType()));
            }
        }
        fallbackBufferHelper = new EncoderFallbackBufferHelper(fallbackBuffer);
        fallbackBufferHelper.InternalInitialize(_chars, _charEnd, _encoder, _bytes != null);
    }
References System.Text.EncodingByteBuffer._byteEnd, System.Text.EncodingByteBuffer._bytes, System.Text.EncodingByteBuffer._byteStart, System.Text.EncodingByteBuffer._charEnd, System.Text.EncodingByteBuffer._chars, System.Text.EncodingByteBuffer._charStart, System.Text.EncodingByteBuffer._enc, System.Text.EncodingByteBuffer._encoder, System.SR.Argument_EncoderFallbackNotEmpty, System.Text.EncoderFallback.CreateFallbackBuffer(), System.Text.Encoding.EncoderFallback, System.Text.EncodingByteBuffer.fallbackBuffer, System.Text.EncodingByteBuffer.fallbackBufferHelper, System.SR.Format(), System.Text.EncoderFallbackBufferHelper.InternalInitialize(), and System.Text.EncoderFallbackBuffer.Remaining.