Terraria: System.Text.EncodingByteBuffer.AddByte
AddByte() [1/7]
unsafe bool System.Text.EncodingByteBuffer.AddByte (byte b, int moreBytesExpected) inline package
Definition at line 69 of file EncodingByteBuffer.cs.
    {
        if (_bytes != null)
        {
            if (_bytes >= _byteEnd - moreBytesExpected)
            {
                MovePrevious(bThrow: true);
                return false;
            }
            *(_bytes++) = b;
        }
        _byteCountResult++;
        return true;
    }
References System.Text.EncodingByteBuffer._byteCountResult, System.Text.EncodingByteBuffer._byteEnd, System.Text.EncodingByteBuffer._bytes, and System.Text.EncodingByteBuffer.MovePrevious().
Referenced by System.Text.EncodingByteBuffer.AddByte(), System.Text.EncodingByteBuffer.AddByte(), System.Text.EncodingByteBuffer.AddByte(), System.Text.EncodingByteBuffer.AddByte(), System.Text.EncodingByteBuffer.AddByte(), and System.Text.EncodingByteBuffer.AddByte().