Terraria: System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.RequireNoValueProperty
RequireNoValueProperty()
void System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.RequireNoValueProperty () inline protected inherited
Definition at line 56 of file StackSpiller.cs.
        {
            if (_binding.Member is PropertyInfo propertyInfo && propertyInfo.PropertyType.IsValueType)
            {
                throw Error.CannotAutoInitializeValueTypeMemberThroughProperty(propertyInfo);
            }
        }
References System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter._binding, System.Linq.Expressions.Error.CannotAutoInitializeValueTypeMemberThroughProperty(), System.Type.IsValueType, System.Linq.Expressions.MemberBinding.Member, and System.Reflection.PropertyInfo.PropertyType.
Referenced by System.Linq.Expressions.Compiler.StackSpiller.MemberMemberBindingRewriter.AsExpression(), and System.Linq.Expressions.Compiler.StackSpiller.ListBindingRewriter.AsExpression().