Terraria: System.Text.Json.ReadStack.JsonPath
JsonPath()
string System.Text.Json.ReadStack.JsonPath () inline
Definition at line 143 of file ReadStack.cs.
    {
        StringBuilder stringBuilder = new StringBuilder("$");
        int num = Math.Max(_count, _continuationCount);
        for (int i = 0; i < num - 1; i++)
        {
            AppendStackFrame(stringBuilder, ref _stack[i]);
        }
        if (_continuationCount == 0)
        {
            AppendStackFrame(stringBuilder, ref Current);
        }
        return stringBuilder.ToString();
        static void AppendPropertyName(StringBuilder sb, string propertyName)
        {
            if (propertyName != null)
            {
                if (propertyName.IndexOfAny(SpecialCharacters) != -1)
                {
                    sb.Append("['");
                    sb.Append(propertyName);
                    sb.Append("']");
                }
                else
                {
                    sb.Append('.');
                    sb.Append(propertyName);
                }
            }
        }
        static void AppendStackFrame(StringBuilder sb, ref ReadStackFrame frame)
        {
            string propertyName2 = GetPropertyName(ref frame);
            AppendPropertyName(sb, propertyName2);
            if (frame.JsonTypeInfo != null && frame.IsProcessingEnumerable() && frame.ReturnValue is IEnumerable enumerable2 && (frame.ObjectState == StackFrameObjectState.None || frame.ObjectState == StackFrameObjectState.CreatedObject || frame.ObjectState == StackFrameObjectState.ReadElements))
            {
                sb.Append('[');
                sb.Append(GetCount(enumerable2));
                sb.Append(']');
            }
        }
        static int GetCount(IEnumerable enumerable)
        {
            if (enumerable is ICollection collection)
            {
                return collection.Count;
            }
            int num2 = 0;
            IEnumerator enumerator = enumerable.GetEnumerator();
            while (enumerator.MoveNext())
            {
                num2++;
            }
            return num2;
        }
        static string GetPropertyName(ref ReadStackFrame frame)
        {
            string result = null;
            byte[] array = frame.JsonPropertyName;
            if (array == null)
            {
                if (frame.JsonPropertyNameAsString != null)
                {
                    result = frame.JsonPropertyNameAsString;
                }
                else
                {
                    array = frame.JsonPropertyInfo?.NameAsUtf8Bytes ?? frame.CtorArgumentState?.JsonParameterInfo?.NameAsUtf8Bytes;
                }
            }
            if (array != null)
            {
                result = JsonHelpers.Utf8GetString(array);
            }
            return result;
        }
    }
References System.Text.Json.ReadStack._continuationCount, System.Text.Json.ReadStack._count, System.Text.Json.ReadStack._stack, System.Text.StringBuilder.Append(), System.array, System.collection, System.Text.Json.ReadStack.Current, System.Text.Json.Dictionary, System.Math.Max(), System.Text.Json.ReadStack.SpecialCharacters, and System.Text.Json.JsonHelpers.Utf8GetString().