Terraria: System.Xml.XmlUTF8NodeWriter.SetOutput
SetOutput()
new void System.Xml.XmlUTF8NodeWriter.SetOutput (Stream stream, bool ownsStream, Encoding encoding) inline
Definition at line 82 of file XmlUTF8NodeWriter.cs.
    {
        Encoding encoding2 = null;
        if (encoding != null && encoding.CodePage == Encoding.UTF8.CodePage)
        {
            encoding2 = encoding;
            encoding = null;
        }
        base.SetOutput(stream, ownsStream, encoding2);
        _encoding = encoding;
        _inAttribute = false;
    }
References System.Xml.XmlUTF8NodeWriter._encoding, System.Xml.XmlUTF8NodeWriter._inAttribute, System.Text.Encoding.CodePage, System.Xml.Dictionary, System.stream, and System.Text.Encoding.UTF8.
Referenced by System.Xml.XmlCanonicalWriter.SetOutput(), System.Runtime.Serialization.Json.XmlJsonWriter.SetOutput(), and System.Xml.XmlUTF8TextWriter.SetOutput().