Terraria: System.Xml.XmlUTF8NodeWriter.WriteStartElement
WriteStartElement() [1/3]
override void System.Xml.XmlUTF8NodeWriter.WriteStartElement (byte[] prefixBuffer, int prefixOffset, int prefixLength, byte[] localNameBuffer, int localNameOffset, int localNameLength) inline virtual
Reimplemented from System.Xml.XmlNodeWriter.
Definition at line 212 of file XmlUTF8NodeWriter.cs.
    {
        WriteByte('<');
        if (prefixLength != 0)
        {
            WritePrefix(prefixBuffer, prefixOffset, prefixLength);
            WriteByte(':');
        }
        WriteLocalName(localNameBuffer, localNameOffset, localNameLength);
    }
References System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.WriteByte(), System.Xml.XmlUTF8NodeWriter.WriteLocalName(), and System.Xml.XmlUTF8NodeWriter.WritePrefix().