Terraria: System.Xml.XmlUTF8NodeWriter.InternalWriteBase64TextAsync
InternalWriteBase64TextAsync()
async Task System.Xml.XmlUTF8NodeWriter.InternalWriteBase64TextAsync (byte[] buffer, int offset, int count) inline private
Definition at line 736 of file XmlUTF8NodeWriter.cs.
    {
        Base64Encoding encoding = XmlConverter.Base64Encoding;
        while (count >= 3)
        {
            int byteCount = Math.Min(384, count - count % 3);
            int count2 = byteCount / 3 * 4;
            BytesWithOffset bytesWithOffset = await GetBufferAsync(count2).ConfigureAwait(continueOnCapturedContext: false);
            byte[] bytes = bytesWithOffset.Bytes;
            int offset2 = bytesWithOffset.Offset;
            Advance(encoding.GetChars(buffer, offset, byteCount, bytes, offset2));
            offset += byteCount;
            count -= byteCount;
        }
        if (count > 0)
        {
            BytesWithOffset bytesWithOffset2 = await GetBufferAsync(4).ConfigureAwait(continueOnCapturedContext: false);
            byte[] bytes2 = bytesWithOffset2.Bytes;
            int offset3 = bytesWithOffset2.Offset;
            Advance(encoding.GetChars(buffer, offset, count, bytes2, offset3));
        }
    }
References System.Xml.XmlStreamNodeWriter.Advance(), System.Xml.XmlConverter.Base64Encoding, System.buffer, System.byteCount, System.bytes, System.Xml.BytesWithOffset.Bytes, System.count, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.GetBufferAsync(), System.Text.Base64Encoding.GetChars(), System.Math.Min(), and System.offset.
Referenced by System.Xml.XmlUTF8NodeWriter.WriteBase64TextAsync().