Terraria: System.Xml.XmlUTF8NodeWriter.WriteXmlnsAttribute
WriteXmlnsAttribute() [2/3]
override void System.Xml.XmlUTF8NodeWriter.WriteXmlnsAttribute (string prefix, string ns) inline
Definition at line 297 of file XmlUTF8NodeWriter.cs.
    {
        WriteStartXmlnsAttribute();
        if (!string.IsNullOrEmpty(prefix))
        {
            WriteByte(':');
            WritePrefix(prefix);
        }
        WriteBytes('=', '"');
        WriteEscapedText(ns);
        WriteEndAttribute();
    }
References System.prefix, System.Xml.XmlStreamNodeWriter.WriteByte(), System.Xml.XmlStreamNodeWriter.WriteBytes(), System.Xml.XmlUTF8NodeWriter.WriteEndAttribute(), System.Xml.XmlUTF8NodeWriter.WriteEscapedText(), System.Xml.XmlUTF8NodeWriter.WritePrefix(), and System.Xml.XmlUTF8NodeWriter.WriteStartXmlnsAttribute().
Referenced by System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute(), and System.Xml.XmlUTF8NodeWriter.WriteXmlnsAttribute().