Terraria: System.Xml.XmlUTF8NodeWriter.WriteStartComment
WriteStartComment()
void System.Xml.XmlUTF8NodeWriter.WriteStartComment () inline private
Definition at line 157 of file XmlUTF8NodeWriter.cs.
    {
        int offset;
        byte[] buffer = GetBuffer(4, out offset);
        buffer[offset] = 60;
        buffer[offset + 1] = 33;
        buffer[offset + 2] = 45;
        buffer[offset + 3] = 45;
        Advance(4);
    }
References System.Xml.XmlStreamNodeWriter.Advance(), System.buffer, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.GetBuffer(), and System.offset.
Referenced by System.Xml.XmlUTF8NodeWriter.WriteComment().