Terraria: System.Net.HttpListenerRequest.HttpListenerRequest
HttpListenerRequest()
unsafe System.Net.HttpListenerRequest.HttpListenerRequest (HttpListenerContext httpContext, RequestContextBase memoryBlob) inline package
Definition at line 819 of file HttpListenerRequest.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"httpContext:${httpContext} memoryBlob {(IntPtr)memoryBlob.RequestBlob}", ".ctor");
            System.Net.NetEventSource.Associate(this, httpContext, ".ctor");
        }
        _httpContext = httpContext;
        _memoryBlob = memoryBlob;
        _boundaryType = BoundaryType.None;
        _requestId = memoryBlob.RequestBlob->RequestId;
        _connectionId = memoryBlob.RequestBlob->ConnectionId;
        _sslStatus = ((memoryBlob.RequestBlob->pSslInfo != null) ? ((memoryBlob.RequestBlob->pSslInfo->SslClientCertNegotiated == 0) ? SslStatus.NoClientCert : SslStatus.ClientCert) : SslStatus.Insecure);
        if (memoryBlob.RequestBlob->pRawUrl != null && memoryBlob.RequestBlob->RawUrlLength > 0)
        {
            _rawUrl = Marshal.PtrToStringAnsi((IntPtr)memoryBlob.RequestBlob->pRawUrl, memoryBlob.RequestBlob->RawUrlLength);
        }
        global::Interop.HttpApi.HTTP_COOKED_URL cookedUrl = memoryBlob.RequestBlob->CookedUrl;
        if (cookedUrl.pHost != null && cookedUrl.HostLength > 0)
        {
            _cookedUrlHost = Marshal.PtrToStringUni((IntPtr)cookedUrl.pHost, cookedUrl.HostLength / 2);
        }
        if (cookedUrl.pAbsPath != null && cookedUrl.AbsPathLength > 0)
        {
            _cookedUrlPath = Marshal.PtrToStringUni((IntPtr)cookedUrl.pAbsPath, cookedUrl.AbsPathLength / 2);
        }
        if (cookedUrl.pQueryString != null && cookedUrl.QueryStringLength > 0)
        {
            _cookedUrlQuery = Marshal.PtrToStringUni((IntPtr)cookedUrl.pQueryString, cookedUrl.QueryStringLength / 2);
        }
        _version = new Version(memoryBlob.RequestBlob->Version.MajorVersion, memoryBlob.RequestBlob->Version.MinorVersion);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"RequestId:{RequestId} ConnectionId:{_connectionId} RawConnectionId:{memoryBlob.RequestBlob->RawConnectionId} UrlContext:{memoryBlob.RequestBlob->UrlContext} RawUrl:{_rawUrl} Version:{_version} Secure:{_sslStatus}", ".ctor");
            System.Net.NetEventSource.Info(this, $"httpContext:${httpContext} RequestUri:{RequestUri} Content-Length:{ContentLength64} HTTP Method:{HttpMethod}", ".ctor");
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            StringBuilder stringBuilder = new StringBuilder("HttpListenerRequest Headers:\n");
            for (int i = 0; i < Headers.Count; i++)
            {
                stringBuilder.Append('\t');
                stringBuilder.Append(Headers.GetKey(i));
                stringBuilder.Append(" : ");
                stringBuilder.Append(Headers.Get(i));
                stringBuilder.Append('\n');
            }
            System.Net.NetEventSource.Info(this, stringBuilder.ToString(), ".ctor");
        }
    }
References System.Net.HttpListenerRequest._boundaryType, System.Net.HttpListenerRequest._connectionId, System.Net.HttpListenerRequest._cookedUrlHost, System.Net.HttpListenerRequest._cookedUrlPath, System.Net.HttpListenerRequest._cookedUrlQuery, System.Net.HttpListenerRequest._httpContext, System.Net.HttpListenerRequest._memoryBlob, System.Net.HttpListenerRequest._rawUrl, System.Net.HttpListenerRequest._requestId, System.Net.HttpListenerRequest._sslStatus, System.Net.HttpListenerRequest._version, System.Net.NetEventSource.Associate(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Runtime.InteropServices.Marshal.PtrToStringAnsi(), System.Runtime.InteropServices.Marshal.PtrToStringUni(), and System.Net.Version.