Terraria: System.Xml.XmlUTF8NodeWriter.WriteUniqueIdText
WriteUniqueIdText()
override void System.Xml.XmlUTF8NodeWriter.WriteUniqueIdText (UniqueId value) inline
Definition at line 656 of file XmlUTF8NodeWriter.cs.
    {
        if (value.IsGuid)
        {
            int charArrayLength = value.CharArrayLength;
            char[] charBuffer = GetCharBuffer(charArrayLength);
            value.ToCharArray(charBuffer, 0);
            WriteText(charBuffer, 0, charArrayLength);
        }
        else
        {
            WriteEscapedText(value.ToString());
        }
    }
References System.Xml.Dictionary, System.Xml.XmlUTF8NodeWriter.GetCharBuffer(), System.value, System.Xml.XmlUTF8NodeWriter.WriteEscapedText(), and System.Xml.XmlUTF8NodeWriter.WriteText().
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue().