Terraria: System.Net.HttpListenerRequest.GetClientCertificateCore
GetClientCertificateCore()
unsafe void System.Net.HttpListenerRequest.GetClientCertificateCore () inline private
Definition at line 989 of file HttpListenerRequest.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, null, "GetClientCertificateCore");
        }
        if (_sslStatus == SslStatus.Insecure)
        {
            return;
        }
        uint num = 1500u;
        while (true)
        {
            byte[] array = new byte[checked((int)num)];
            fixed (byte* ptr = &array[0])
            {
                global::Interop.HttpApi.HTTP_SSL_CLIENT_CERT_INFO* ptr2 = (global::Interop.HttpApi.HTTP_SSL_CLIENT_CERT_INFO*)ptr;
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Calling Interop.HttpApi.HttpReceiveClientCertificate size:" + num, "GetClientCertificateCore");
                }
                uint num2 = 0u;
                uint num3 = global::Interop.HttpApi.HttpReceiveClientCertificate(HttpListenerContext.RequestQueueHandle, _connectionId, 0u, ptr2, num, &num2, null);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Call to Interop.HttpApi.HttpReceiveClientCertificate returned:" + num3 + " bytesReceived:" + num2, "GetClientCertificateCore");
                }
                switch (num3)
                {
                case 234u:
                    num = num2 + ptr2->CertEncodedSize;
                    break;
                case 0u:
                    if (ptr2 == null)
                    {
                        return;
                    }
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"pClientCertInfo:{(IntPtr)ptr2} pClientCertInfo->CertFlags: {ptr2->CertFlags} pClientCertInfo->CertEncodedSize: {ptr2->CertEncodedSize} pClientCertInfo->pCertEncoded: {(IntPtr)ptr2->pCertEncoded} pClientCertInfo->Token: {(IntPtr)ptr2->Token} pClientCertInfo->CertDeniedByMapper: {ptr2->CertDeniedByMapper}", "GetClientCertificateCore");
                    }
                    if (ptr2->pCertEncoded != null)
                    {
                        try
{
                            byte[] array2 = new byte[ptr2->CertEncodedSize];
                            Marshal.Copy((IntPtr)ptr2->pCertEncoded, array2, 0, array2.Length);
                            ClientCertificate = new X509Certificate2(array2);
                        }
                        catch (CryptographicException ex)
{
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, $"CryptographicException={ex}", "GetClientCertificateCore");
                            }
                        }
                        catch (SecurityException ex2)
{
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, $"SecurityException={ex2}", "GetClientCertificateCore");
                            }
                        }
                    }
                    _clientCertificateError = (int)ptr2->CertFlags;
                    return;
                default:
                    return;
                }
            }
        }
    }
References System.Net.HttpListenerRequest._clientCertificateError, System.Net.HttpListenerRequest._connectionId, System.Net.HttpListenerRequest._sslStatus, System.array, System.Net.HttpListenerRequest.ClientCertificate, System.Runtime.InteropServices.Marshal.Copy(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.Net.HttpListenerContext.RequestQueueHandle.
Referenced by System.Net.HttpListenerRequest.GetClientCertificate().