Terraria: System.Xml.XmlUTF8NodeWriter.WriteText
WriteText() [3/5]
void System.Xml.XmlUTF8NodeWriter.WriteText (int ch) inline
Definition at line 480 of file XmlUTF8NodeWriter.cs.
    {
        WriteUTF8Char(ch);
    }
References System.ch, and System.Xml.XmlStreamNodeWriter.WriteUTF8Char().
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteDataTypeServerType(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteEndElement(), System.Xml.XmlCanonicalWriter.WriteEndStartElement(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteEscapedJsonString(), System.Xml.XmlUTF8NodeWriter.WriteGuidText(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteIndent(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteJsonElementName(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteJsonQuote(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteNewLine(), System.Xml.XmlUTF8NodeWriter.WriteQualifiedName(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteStartElement(), System.Xml.XmlCanonicalWriter.WriteText(), System.Xml.XmlCanonicalWriter.WriteText(), System.Xml.XmlCanonicalWriter.WriteText(), System.Xml.XmlCanonicalWriter.WriteText(), System.Xml.XmlUTF8NodeWriter.WriteTimeSpanText(), System.Xml.XmlUTF8NodeWriter.WriteUniqueIdText(), and System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue().