Terraria: System.Xml.XmlUTF8NodeWriter.WriteXmlnsAttribute
WriteXmlnsAttribute() [1/3]
override void System.Xml.XmlUTF8NodeWriter.WriteXmlnsAttribute (byte[] prefixBuffer, int prefixOffset, int prefixLength, byte[] nsBuffer, int nsOffset, int nsLength) inline virtual
Reimplemented from System.Xml.XmlNodeWriter.
Definition at line 315 of file XmlUTF8NodeWriter.cs.
    {
        WriteStartXmlnsAttribute();
        if (prefixLength != 0)
        {
            WriteByte(':');
            WritePrefix(prefixBuffer, prefixOffset, prefixLength);
        }
        WriteBytes('=', '"');
        WriteEscapedText(nsBuffer, nsOffset, nsLength);
        WriteEndAttribute();
    }
References System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.WriteByte(), System.Xml.XmlStreamNodeWriter.WriteBytes(), System.Xml.XmlUTF8NodeWriter.WriteEndAttribute(), System.Xml.XmlUTF8NodeWriter.WriteEscapedText(), System.Xml.XmlUTF8NodeWriter.WritePrefix(), and System.Xml.XmlUTF8NodeWriter.WriteStartXmlnsAttribute().