Terraria: System.Xml.XmlUTF8NodeWriter.InternalWriteBase64Text
InternalWriteBase64Text()
void System.Xml.XmlUTF8NodeWriter.InternalWriteBase64Text (byte[] buffer, int offset, int count) inline private
Definition at line 715 of file XmlUTF8NodeWriter.cs.
    {
        Base64Encoding base64Encoding = XmlConverter.Base64Encoding;
        while (count >= 3)
        {
            int num = Math.Min(384, count - count % 3);
            int count2 = num / 3 * 4;
            int offset2;
            byte[] buffer2 = GetBuffer(count2, out offset2);
            Advance(base64Encoding.GetChars(buffer, offset, num, buffer2, offset2));
            offset += num;
            count -= num;
        }
        if (count > 0)
        {
            int offset3;
            byte[] buffer3 = GetBuffer(4, out offset3);
            Advance(base64Encoding.GetChars(buffer, offset, count, buffer3, offset3));
        }
    }
References System.Xml.XmlStreamNodeWriter.Advance(), System.Xml.XmlConverter.Base64Encoding, System.buffer, System.count, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.GetBuffer(), System.Math.Min(), and System.offset.
Referenced by System.Xml.XmlUTF8NodeWriter.WriteBase64Text().