Terraria: System.Xml.XmlUTF8NodeWriter.WriteCharEntity
WriteCharEntity()
override void System.Xml.XmlUTF8NodeWriter.WriteCharEntity (int ch) inline
Definition at line 583 of file XmlUTF8NodeWriter.cs.
    {
        switch (ch)
        {
        case 60:
            WriteLessThanCharEntity();
            break;
        case 62:
            WriteGreaterThanCharEntity();
            break;
        case 38:
            WriteAmpersandCharEntity();
            break;
        case 39:
            WriteApostropheCharEntity();
            break;
        case 34:
            WriteQuoteCharEntity();
            break;
        default:
            WriteHexCharEntity(ch);
            break;
        }
    }
References System.ch, System.Xml.XmlUTF8NodeWriter.WriteAmpersandCharEntity(), System.Xml.XmlUTF8NodeWriter.WriteApostropheCharEntity(), System.Xml.XmlUTF8NodeWriter.WriteGreaterThanCharEntity(), System.Xml.XmlUTF8NodeWriter.WriteHexCharEntity(), System.Xml.XmlUTF8NodeWriter.WriteLessThanCharEntity(), and System.Xml.XmlUTF8NodeWriter.WriteQuoteCharEntity().
Referenced by System.Xml.XmlUTF8NodeWriter.UnsafeWriteEscapedText(), and System.Xml.XmlUTF8NodeWriter.WriteEscapedText().