Terraria: System.Net.HttpListenerRequest.BeginGetClientCertificate
BeginGetClientCertificate()
IAsyncResult System.Net.HttpListenerRequest.BeginGetClientCertificate (AsyncCallback? requestCallback, object? state) inline
Definition at line 800 of file HttpListenerRequest.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, null, "BeginGetClientCertificate");
        }
        if (ClientCertState == ListenerClientCertState.InProgress)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_listener_callinprogress, "GetClientCertificate()/BeginGetClientCertificate()"));
        }
        ClientCertState = ListenerClientCertState.InProgress;
        return BeginGetClientCertificateCore(requestCallback, state);
    }
References System.Net.HttpListenerRequest.BeginGetClientCertificateCore(), System.Net.HttpListenerRequest.ClientCertState, System.SR.Format(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_listener_callinprogress, and System.state.
Referenced by System.Net.HttpListenerRequest.GetClientCertificateAsync().