Terraria: System.Xml.XmlUTF8NodeWriter.WriteEndElementAsync
WriteEndElementAsync()
override async Task System.Xml.XmlUTF8NodeWriter.WriteEndElementAsync (string prefix, string localName) inline virtual
Reimplemented from System.Xml.XmlNodeWriter.
Definition at line 259 of file XmlUTF8NodeWriter.cs.
    {
        await WriteBytesAsync('<', '/').ConfigureAwait(continueOnCapturedContext: false);
        if (!string.IsNullOrEmpty(prefix))
        {
            WritePrefix(prefix);
            await WriteByteAsync(':').ConfigureAwait(continueOnCapturedContext: false);
        }
        WriteLocalName(localName);
        await WriteByteAsync('>').ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.prefix, System.Xml.XmlStreamNodeWriter.WriteByteAsync(), System.Xml.XmlStreamNodeWriter.WriteBytesAsync(), System.Xml.XmlUTF8NodeWriter.WriteLocalName(), and System.Xml.XmlUTF8NodeWriter.WritePrefix().