Terraria: System.Xml.XmlUTF8NodeWriter.WriteEndStartElement
WriteEndStartElement()
override void System.Xml.XmlUTF8NodeWriter.WriteEndStartElement (bool isEmpty) inline
Definition at line 223 of file XmlUTF8NodeWriter.cs.
    {
        if (!isEmpty)
        {
            WriteByte('>');
        }
        else
        {
            WriteBytes('/', '>');
        }
    }
References System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.WriteByte(), and System.Xml.XmlStreamNodeWriter.WriteBytes().
Referenced by System.Xml.XmlCanonicalWriter.WriteEndStartElement().