Terraria: System.Xml.XmlUTF8NodeWriter.WriteDecimalText
WriteDecimalText()
override void System.Xml.XmlUTF8NodeWriter.WriteDecimalText (decimal value) inline
Definition at line 628 of file XmlUTF8NodeWriter.cs.
    {
        int offset;
        byte[] buffer = GetBuffer(40, out offset);
        Advance(XmlConverter.ToChars(value, buffer, offset));
    }
References System.Xml.XmlStreamNodeWriter.Advance(), System.buffer, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.GetBuffer(), System.offset, System.Xml.XmlConverter.ToChars(), and System.value.
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue().