Terraria: System.Xml.XmlUTF8NodeWriter.WriteHexCharEntity
WriteHexCharEntity()
void System.Xml.XmlUTF8NodeWriter.WriteHexCharEntity (int ch) inline private
Definition at line 571 of file XmlUTF8NodeWriter.cs.
    {
        byte[] charEntityBuffer = GetCharEntityBuffer();
        int num = 32;
        charEntityBuffer[--num] = 59;
        num -= ToBase16(charEntityBuffer, num, (uint)ch);
        charEntityBuffer[--num] = 120;
        charEntityBuffer[--num] = 35;
        charEntityBuffer[--num] = 38;
        WriteUTF8Chars(charEntityBuffer, num, 32 - num);
    }
References System.ch, System.Xml.Dictionary, System.Xml.XmlUTF8NodeWriter.GetCharEntityBuffer(), System.Xml.XmlUTF8NodeWriter.ToBase16(), and System.Xml.XmlStreamNodeWriter.WriteUTF8Chars().
Referenced by System.Xml.XmlUTF8NodeWriter.WriteCharEntity().