Terraria: System.Threading.ThreadPool.UnsafeQueueUserWorkItem< TState >
UnsafeQueueUserWorkItem< TState >()
static bool System.Threading.ThreadPool.UnsafeQueueUserWorkItem< TState > (Action< TState > callBack, TState state, bool preferLocal) inline static
Definition at line 527 of file ThreadPool.cs.
    {
        if (callBack == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.callBack);
        }
        if ((object)callBack == s_invokeAsyncStateMachineBox)
        {
            if (!(state is IAsyncStateMachineBox))
            {
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.state);
            }
            UnsafeQueueUserWorkItemInternal(state, preferLocal);
            return true;
        }
        s_workQueue.Enqueue(new QueueUserWorkItemCallbackDefaultContext<TState>(callBack, state), !preferLocal);
        return true;
    }
References System.callBack, System.Threading.ThreadPool.s_invokeAsyncStateMachineBox, System.Threading.ThreadPool.s_workQueue, System.state, System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.Threading.ThreadPool.UnsafeQueueUserWorkItemInternal().