Terraria: System.Threading.ThreadPool.RegisterWaitForSingleObject
RegisterWaitForSingleObject() [1/5]
static RegisteredWaitHandle System.Threading.ThreadPool.RegisterWaitForSingleObject (WaitHandle waitObject, WaitOrTimerCallback callBack, object state, uint millisecondsTimeOutInterval, bool executeOnlyOnce, bool flowExecutionContext) inline static private
Definition at line 203 of file ThreadPool.cs.
    {
        if (waitObject == null)
        {
            throw new ArgumentNullException("waitObject");
        }
        if (callBack == null)
        {
            throw new ArgumentNullException("callBack");
        }
        RegisteredWaitHandle registeredWaitHandle = new RegisteredWaitHandle(waitObject, new _ThreadPoolWaitOrTimerCallback(callBack, state, flowExecutionContext), (int)millisecondsTimeOutInterval, !executeOnlyOnce);
        registeredWaitHandle.OnBeforeRegister();
        if (UsePortableThreadPool)
        {
            PortableThreadPool.ThreadPoolInstance.RegisterWaitHandle(registeredWaitHandle);
        }
        else
        {
            IntPtr nativeRegisteredWaitHandle = RegisterWaitForSingleObjectNative(waitObject, registeredWaitHandle.Callback, (uint)registeredWaitHandle.TimeoutDurationMs, !registeredWaitHandle.Repeating, registeredWaitHandle);
            registeredWaitHandle.SetNativeRegisteredWaitHandle(nativeRegisteredWaitHandle);
        }
        return registeredWaitHandle;
    }
References System.callBack, System.Threading.ThreadPool.RegisterWaitForSingleObjectNative(), System.state, System.Threading.PortableThreadPool.ThreadPoolInstance, and System.Threading.ThreadPool.UsePortableThreadPool.
Referenced by System.Diagnostics.Process.EnsureWatchingForExit(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Net.NetworkInformation.Ping.RegisterWaitHandle(), System.Net.NetworkInformation.NetworkChange.AddressChangeListener.StartHelper(), System.Threading.ThreadPool.UnsafeRegisterWaitForSingleObject(), System.Threading.ThreadPool.UnsafeRegisterWaitForSingleObject(), System.Threading.ThreadPool.UnsafeRegisterWaitForSingleObject(), and System.Threading.ThreadPool.UnsafeRegisterWaitForSingleObject().