Terraria: System.Threading.ThreadPool.UsePortableThreadPool
UsePortableThreadPool
readonly bool System.Threading.ThreadPool.UsePortableThreadPool = InitializeConfigAndDetermineUsePortableThreadPool() static package
Definition at line 12 of file ThreadPool.cs.
Referenced by System.Threading.RegisteredWaitHandle.~RegisteredWaitHandle(), System.Threading.ThreadPool.GetAvailableThreads(), System.Threading.ThreadPool.GetEnableWorkerTracking(), System.Threading.ThreadPool.GetMaxThreads(), System.Threading.ThreadPool.GetMinThreads(), System.Threading.ThreadPool.GetOrCreateThreadLocalCompletionCountObject(), System.Threading.ThreadPool.NotifyThreadBlocked(), System.Threading.ThreadPool.NotifyWorkItemComplete(), System.Threading.ThreadPool.NotifyWorkItemProgress(), System.Threading.RegisteredWaitHandle.OnBeforeRegister(), System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Threading.ThreadPool.ReportThreadStatus(), System.Threading.ThreadPool.RequestWorkerThread(), System.Threading.Thread.ResetThreadPoolThread(), System.Threading.ThreadPool.SetMaxThreads(), System.Threading.ThreadPool.SetMinThreads(), and System.Threading.RegisteredWaitHandle.Unregister().