Terraria: System.Threading.ThreadPool.QueueUserWorkItem
QueueUserWorkItem() [1/2]
static bool System.Threading.ThreadPool.QueueUserWorkItem (WaitCallback callBack) inline static
Definition at line 498 of file ThreadPool.cs.
    {
        return QueueUserWorkItem(callBack, null);
    }
References System.callBack, and System.Threading.ThreadPool.QueueUserWorkItem().
Referenced by System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.CompleteTaskAsync(), System.Transactions.TransactionStatePromotedEnded.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCEnded.EnterState(), System.Diagnostics.AsyncStreamReader.FlushMessageQueue(), ReLogic.Threading.FastParallel.For(), Microsoft.Xna.Framework.UserAsyncDispatcher.HandleFinishedOperation(), Terraria.Social.WeGame.CoreSocialModule.Initialize(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.InvokeContinuationWithContext(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.OnCompleted(), System.Net.NetworkInformation.TeredoHelper.OnStabilized(), Terraria.WorldGen.playWorld(), System.Threading.SynchronizationContext.Post(), System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.QueueContinuation(), System.Threading.Channels.AsyncOperation< TResult >.QueueUserWorkItem(), System.Threading.ThreadPool.QueueUserWorkItem(), Terraria.WorldGen.RenameWorld(), Terraria.WorldGen.saveAndPlay(), Terraria.WorldGen.SaveAndQuit(), Terraria.WorldGen.saveToonWhilePlaying(), Terraria.WorldGen.StartHardmode(), System.Threading.Tasks.Dataflow.Internal.Common.ThrowAsync(), System.Threading.Tasks.Task< TResult >.ThrowAsync(), and ReLogic.Peripherals.RGB.ChromaEngine.Update().