Terraria: System.AppContextConfigHelper.GetInt32Config
GetInt32Config()
static int System.AppContextConfigHelper.GetInt32Config (string configName, int defaultValue, bool allowNegative = true) inline static package
Definition at line 26 of file AppContextConfigHelper.cs.
    {
        try
        {
            object data = AppContext.GetData(configName);
            int num = defaultValue;
            if (!(data is uint num2))
            {
                if (data is string text)
                {
                    num = ((!text.StartsWith('0')) ? int.Parse(text, NumberStyles.AllowLeadingSign, NumberFormatInfo.InvariantInfo) : ((text.Length < 2 || text[1] != 'x') ? Convert.ToInt32(text, 8) : Convert.ToInt32(text, 16)));
                }
                else if (data is IConvertible convertible)
                {
                    num = convertible.ToInt32(NumberFormatInfo.InvariantInfo);
                }
            }
            else
            {
                num = (int)num2;
            }
            return (!allowNegative && num < 0) ? defaultValue : num;
        }
        catch (FormatException)
        {
            return defaultValue;
        }
        catch (OverflowException)
        {
            return defaultValue;
        }
    }
References System.AppContext.GetData(), System.Globalization.NumberFormatInfo.InvariantInfo, System.text, and System.Convert.ToInt32().
Referenced by System.Threading.PortableThreadPool.BlockingConfig.BlockingConfig(), and System.Threading.PortableThreadPool.HillClimbing.HillClimbing().