Terraria: System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode
Decode() [4/8]
static void System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode (ref AsnValueReader reader, ReadOnlyMemory< byte > rebind, out AlgorithmIdentifierAsn decoded) inline static package
Definition at line 13 of file AlgorithmIdentifierAsn.cs.
    {
        Decode(ref reader, Asn1Tag.Sequence, rebind, out decoded);
    }
References System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(), and System.Formats.Asn1.Asn1Tag.Sequence.
Referenced by System.Security.Cryptography.X509Certificates.CertificateRequest.Create(), System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(), System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(), System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(), System.Security.Cryptography.Asn1.EncryptedPrivateKeyInfoAsn.DecodeCore(), System.Security.Cryptography.Asn1.PBES2Params.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2Params.DecodeCore(), System.Security.Cryptography.Asn1.PrivateKeyInfoAsn.DecodeCore(), System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.DecodeCore(), System.Security.Cryptography.X509Certificates.Asn1.CertificateAsn.DecodeCore(), System.Security.Cryptography.Asn1.EncryptedPrivateKeyInfoAsn.DecodeCore(), System.Security.Cryptography.Asn1.PBES2Params.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2Params.DecodeCore(), System.Security.Cryptography.Asn1.PrivateKeyInfoAsn.DecodeCore(), System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.DecodeCore(), System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.DecodeCore(), and System.Security.Cryptography.X509Certificates.Pkcs10CertificationRequestInfo.ToPkcs10Request().