Terraria: System.Net.Http.DelegatingHandler.SetOperationStarted
SetOperationStarted()
void System.Net.Http.DelegatingHandler.SetOperationStarted () inline private inherited
Definition at line 96 of file DelegatingHandler.cs.
    {
        CheckDisposed();
        if (_innerHandler == null)
        {
            throw new InvalidOperationException(System.SR.net_http_handler_not_assigned);
        }
        if (!_operationStarted)
        {
            _operationStarted = true;
        }
    }
References System.Net.Http.DelegatingHandler._innerHandler, System.Net.Http.DelegatingHandler._operationStarted, System.Net.Http.DelegatingHandler.CheckDisposed(), and System.SR.net_http_handler_not_assigned.
Referenced by System.Net.Http.DelegatingHandler.Send(), and System.Net.Http.DelegatingHandler.SendAsync().