Terraria: System.Xml.Xsl.Runtime.TokenInfo.CreateFormat
CreateFormat()
static TokenInfo System.Xml.Xsl.Runtime.TokenInfo.CreateFormat (string formatString, int startIdx, int tokLen) inline static
Definition at line 26 of file TokenInfo.cs.
    {
        TokenInfo tokenInfo = new TokenInfo();
        tokenInfo.formatString = null;
        tokenInfo.length = 1;
        bool flag = false;
        char c = formatString[startIdx];
        switch (c)
        {
        default:
            if (CharUtil.IsDecimalDigitOne(c))
            {
                break;
            }
            if (CharUtil.IsDecimalDigitOne((char)(c + 1)))
            {
                int num = startIdx;
                do
                {
                    tokenInfo.length++;
                }
                while (--tokLen > 0 && c == formatString[++num]);
                if (formatString[num] == (c = (char)(c + 1)))
                {
                    break;
                }
            }
            flag = true;
            break;
        case '1':
        case 'A':
        case 'I':
        case 'a':
        case 'i':
            break;
        }
        if (tokLen != 1)
        {
            flag = true;
        }
        if (flag)
        {
            tokenInfo.startChar = '1';
            tokenInfo.length = 1;
        }
        else
        {
            tokenInfo.startChar = c;
        }
        return tokenInfo;
    }
References System.Xml.Xsl.Runtime.TokenInfo.TokenInfo(), System.Xml.Dictionary, System.Xml.Xsl.Runtime.TokenInfo.formatString, System.Xml.Xsl.Runtime.CharUtil.IsDecimalDigitOne(), and System.Xml.Xsl.Runtime.TokenInfo.startIdx.
Referenced by System.Xml.Xsl.Runtime.NumberFormatter.NumberFormatter().