Terraria: System.DBNull.Value
Value
readonly DBNull System.DBNull.Value = new DBNull() static
Definition at line 8 of file DBNull.cs.
Referenced by System.Data.ConstNode.ConstNode(), System.Net.LazyAsyncResult.LazyAsyncResult(), System.Variant.Variant(), System.Data.DataRow.AcceptChanges(), System.Data.ProviderBase.SchemaMapping.AddAdditionalProperties(), System.Data.DataRowComparer< TRow >.AreElementEqual(), System.Data.DataRowComparer< TRow >.AreEqual(), System.DefaultBinder.BindToMethod(), System.Data.DataColumnPropertyDescriptor.CanResetValue(), System.Data.ForeignKeyConstraint.CascadeDelete(), System.Data.ForeignKeyConstraint.CascadeUpdate(), System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.SqlConvert.ChangeTypeForDefaultValue(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Reflection.MethodBase.CheckArguments(), System.Data.DataColumn.CheckNotAllowNull(), System.Data.Common.SqlUdtStorage.CompareValueTo(), System.Data.DefaultValueTypeConverter.ConvertFrom(), System.Data.DefaultValueTypeConverter.ConvertTo(), System.Data.Common.SqlConvert.ConvertToSqlBinary(), System.Data.Common.SqlConvert.ConvertToSqlBoolean(), System.Data.Common.SqlConvert.ConvertToSqlByte(), System.Data.Common.SqlConvert.ConvertToSqlBytes(), System.Data.Common.SqlConvert.ConvertToSqlChars(), System.Data.Common.SqlConvert.ConvertToSqlDateTime(), System.Data.Common.SqlConvert.ConvertToSqlDecimal(), System.Data.Common.SqlConvert.ConvertToSqlDouble(), System.Data.Common.SqlConvert.ConvertToSqlGuid(), System.Data.Common.SqlConvert.ConvertToSqlInt16(), System.Data.Common.SqlConvert.ConvertToSqlInt32(), System.Data.Common.SqlConvert.ConvertToSqlInt64(), System.Data.Common.SqlConvert.ConvertToSqlMoney(), System.Data.Common.SqlConvert.ConvertToSqlSingle(), System.Data.Common.SqlConvert.ConvertToSqlString(), System.Data.DataTable.CreateEmptyRow(), System.Data.ZeroOpNode.Eval(), System.Data.Select.Eval(), System.Data.FunctionNode.Eval(), System.Data.LikeNode.Eval(), System.Data.LookupNode.Eval(), System.Data.BinaryNode.EvalBinaryOp(), System.Data.FunctionNode.EvalFunction(), System.Data.DataExpression.Evaluate(), System.Data.DataExpression.Evaluate(), System.Data.UnaryNode.EvalUnaryOp(), System.Xml.Serialization.XmlSchemaExporter.ExportDefaultValue(), System.Data.NewDiffgramGen.GenerateColumn(), System.Data.DataColumn.GetAggregateValue(), System.Reflection.RuntimePropertyInfo.GetConstantValue(), System.Reflection.RuntimeParameterInfo.GetDefaultValue(), System.Text.Json.Reflection.ReflectionExtensions.GetDefaultValue(), System.Xml.Serialization.SoapReflectionImporter.GetDefaultValue(), System.Xml.Serialization.XmlReflectionImporter.GetDefaultValue(), System.Reflection.RuntimeParameterInfo.GetDefaultValueInternal(), System.Data.ProviderBase.SchemaMapping.GetMappedValues(), System.Reflection.RuntimeParameterInfo.GetRawConstant(), System.UnitySerializationHolder.GetRealObject(), System.Data.DataTableReader.GetSchemaTableFromDataTable(), System.Reflection.MdFieldInfo.GetValue(), System.Reflection.MdConstant.GetValue(), System.Convert.IsDBNull(), System.Data.DataColumn.IsMaxLengthViolated(), System.Data.DataColumn.IsNotAllowDBNullViolated(), System.Data.Common.ADP.IsNull(), System.Data.Common.DataStorage.IsObjectNull(), System.Data.XmlDataLoader.LoadColumn(), System.Data.XmlDataLoader.LoadRowData(), System.Data.XmlDataLoader.LoadTable(), System.Data.XmlDataLoader.LoadTopMostTable(), System.Data.DataRowExtensions.UnboxT< T >.NullableField< TElem >(), System.Data.BinaryNode.Optimize(), System.Net.LazyAsyncResult.ProtectedInvokeCallback(), System.Data.XMLDiffLoader.ReadOldRowData(), System.Data.DataRowExtensions.UnboxT< T >.ReferenceField(), System.Data.DataRow.RejectChanges(), System.Data.DataColumnPropertyDescriptor.ResetValue(), System.Data.Common.SqlBytesStorage.Set(), System.Data.Common.SqlCharsStorage.Set(), System.Data.Common.SqlUdtStorage.Set(), System.Data.DataRowExtensions.SetField< T >(), System.Data.DataRowExtensions.SetField< T >(), System.Data.DataRowExtensions.SetField< T >(), System.Data.DataRow.SetNull(), System.Xml.XmlDataDocument.SetRowValueToNull(), System.Xml.XmlDataDocument.SynchronizeRowFromRowElementEx(), System.Runtime.InteropServices.Variant.ToObject(), System.Variant.ToObject(), System.Data.DataRowExtensions.UnboxT< T >.ValueField(), System.Net.LazyAsyncResult.WaitForCompletion(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WritePrimitive(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteQualifiedNameElement(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteQualifiedNameElement(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteQualifiedNameElement(), and System.Data.XmlDataTreeWriter.XmlDataRowWriter().