Terraria: System.Net.Mime.HeaderCollection.Set
Set() [1/2]
override void System.Net.Mime.HeaderCollection.Set (string name, string value) inline
Definition at line 75 of file HeaderCollection.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (name.Length == 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_emptystringcall, "name"), "name");
        }
        if (value.Length == 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_emptystringcall, "value"), "value");
        }
        if (!MimeBasePart.IsAscii(name, permitCROrLF: false))
        {
            throw new FormatException(System.SR.InvalidHeaderName);
        }
        name = MailHeaderInfo.NormalizeCase(name);
        value = value.Normalize(NormalizationForm.FormC);
        base.Set(name, value);
    }
References System.SR.Format(), System.SR.InvalidHeaderName, System.Net.Mime.MimeBasePart.IsAscii(), System.SR.net_emptystringcall, System.Net.Mail.MailHeaderInfo.NormalizeCase(), and System.value.
Referenced by System.Net.Mail.Message.EncodeHeaders().