Terraria: Terraria.ID.ContentSamples.NpcsByNetId
NpcsByNetId
Dictionary<int, NPC> Terraria.ID.ContentSamples.NpcsByNetId = new Dictionary<int, NPC>() static
Referenced by Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddEmptyEntries_CrittersAndEnemies_Automated(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddNPCBiomeRelationships_AddDecorations_Automated(), Terraria.GameContent.TownRoomManager.CanNPCsLiveWithEachOther(), Terraria.GameContent.Bestiary.SortingSteps.Alphabetical.Compare(), Terraria.GameContent.Bestiary.BestiaryEntry.Critter(), Terraria.GameContent.NetModules.NetBestiaryModule.Deserialize(), Terraria.GameContent.Bestiary.BestiaryEntry.Enemy(), Terraria.GameContent.Bestiary.CommonEnemyUICollectionInfoProvider.GetKillCountNeeded(), Terraria.ID.ContentSamples.BestiaryHelper.GetSortedBestiaryEntriesList(), Terraria.ID.ContentSamples.Initialize(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.PrepareNPCNetIDsByTypeDictionary(), and Terraria.GameContent.Bestiary.BestiaryEntry.TownNPC().