Terraria: System.Diagnostics.ActivitySource.ActivitySource
ActivitySource()
System.Diagnostics.ActivitySource.ActivitySource (string name, string? version = "") inline
Definition at line 21 of file ActivitySource.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        Name = name;
        Version = version;
        s_activeSources.Add(this);
        if (s_allListeners.Count > 0)
        {
            s_allListeners.EnumWithAction(delegate(ActivityListener listener, object source)
            {
                Func<ActivitySource, bool> shouldListenTo = listener.ShouldListenTo;
                if (shouldListenTo != null)
                {
                    ActivitySource activitySource = (ActivitySource)source;
                    if (shouldListenTo(activitySource))
                    {
                        activitySource.AddListener(listener);
                    }
                }
            }, this);
        }
        GC.KeepAlive(DiagnosticSourceEventSource.Log);
    }
References System.Diagnostics.ActivitySource.ActivitySource(), System.GC.KeepAlive(), System.Diagnostics.DiagnosticSourceEventSource.Log, System.Diagnostics.ActivitySource.Name, System.Diagnostics.ActivitySource.s_activeSources, System.Diagnostics.ActivitySource.s_allListeners, System.Diagnostics.ActivityListener.ShouldListenTo, and System.source.
Referenced by System.Diagnostics.ActivitySource.ActivitySource().