Terraria: System.Reflection.Emit.IgnoreAccessChecksToAttributeBuilder.AddToModule
AddToModule()
static ConstructorInfo System.Reflection.Emit.IgnoreAccessChecksToAttributeBuilder.AddToModule (ModuleBuilder mb) inline static
Definition at line 7 of file IgnoreAccessChecksToAttributeBuilder.cs.
    {
        TypeBuilder typeBuilder = mb.DefineType("System.Runtime.CompilerServices.IgnoresAccessChecksToAttribute", TypeAttributes.Public, typeof(Attribute));
        FieldBuilder fieldBuilder = typeBuilder.DefineField("assemblyName", typeof(string), FieldAttributes.Private);
        ConstructorBuilder constructorBuilder = typeBuilder.DefineConstructor(MethodAttributes.Public, CallingConventions.HasThis, new Type[1] { fieldBuilder.FieldType });
        ILGenerator iLGenerator = constructorBuilder.GetILGenerator();
        iLGenerator.Emit(OpCodes.Ldarg_0);
        iLGenerator.Emit(OpCodes.Ldarg, 1);
        iLGenerator.Emit(OpCodes.Stfld, fieldBuilder);
        iLGenerator.Emit(OpCodes.Ret);
        PropertyBuilder propertyBuilder = typeBuilder.DefineProperty("AssemblyName", PropertyAttributes.None, CallingConventions.HasThis, typeof(string), null);
        MethodBuilder methodBuilder = typeBuilder.DefineMethod("get_AssemblyName", MethodAttributes.Public, CallingConventions.HasThis, typeof(string), null);
        propertyBuilder.SetGetMethod(methodBuilder);
        iLGenerator = methodBuilder.GetILGenerator();
        iLGenerator.Emit(OpCodes.Ldarg_0);
        iLGenerator.Emit(OpCodes.Ldfld, fieldBuilder);
        iLGenerator.Emit(OpCodes.Ret);
        TypeInfo typeInfo = typeof(AttributeUsageAttribute).GetTypeInfo();
        ConstructorInfo con = typeInfo.DeclaredConstructors.Single((ConstructorInfo c) => c.GetParameters().Length == 1 && c.GetParameters()[0].ParameterType == typeof(AttributeTargets));
        PropertyInfo propertyInfo = typeInfo.DeclaredProperties.Single((PropertyInfo f) => string.Equals(f.Name, "AllowMultiple"));
        CustomAttributeBuilder customAttribute = new CustomAttributeBuilder(con, new object[1] { AttributeTargets.Assembly }, new PropertyInfo[1] { propertyInfo }, new object[1] { true });
        typeBuilder.SetCustomAttribute(customAttribute);
        return typeBuilder.CreateTypeInfo().DeclaredConstructors.Single();
    }
References System.Reflection.Emit.TypeBuilder.CreateTypeInfo(), System.Reflection.TypeInfo.DeclaredConstructors, System.Reflection.TypeInfo.DeclaredProperties, System.Reflection.Emit.TypeBuilder.DefineConstructor(), System.Reflection.Emit.TypeBuilder.DefineField(), System.Reflection.Emit.TypeBuilder.DefineMethod(), System.Reflection.Emit.TypeBuilder.DefineProperty(), System.Reflection.Emit.ModuleBuilder.DefineType(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ConstructorBuilder.GetILGenerator(), System.Reflection.Emit.MethodBuilder.GetILGenerator(), System.Reflection.MethodBase.GetParameters(), System.Reflection.TypeInfo.GetTypeInfo(), System.Reflection.Emit.OpCodes.Ldarg, System.Reflection.Emit.OpCodes.Ldarg_0, System.Reflection.Emit.OpCodes.Ldfld, System.Reflection.MemberInfo.Name, System.Reflection.ParameterInfo.ParameterType, System.Reflection.Emit.OpCodes.Ret, System.Reflection.Emit.TypeBuilder.SetCustomAttribute(), System.Reflection.Emit.PropertyBuilder.SetGetMethod(), and System.Reflection.Emit.OpCodes.Stfld.