Terraria: WorldGen.PlaceBamboo
PlaceBamboo()
static bool WorldGen.PlaceBamboo (int x, int y) inline static private
     {
         int num = 2;
         int num2 = 5;
         int num3 = genRand.Next(1, 21);
         Tile tile = Main.tile[x, y];
         if (tile.wall > 0 && (double)y <= Main.worldSurface)
         {
             return false;
         }
         if (tile.active() && tile.type == 314)
         {
             return false;
         }
         Tile tile2 = Main.tile[x, y + 1];
         if (tile2.type == 571 || tile2.type == 60)
         {
             int waterDepth = GetWaterDepth(x, y);
             if (waterDepth < num || waterDepth > num2)
             {
                 return false;
             }
             int num4 = CountGrowingPlantTiles(x, y, 5, 571);
             int i = 1;
             if (tile2.type == 571)
             {
                 for (; !SolidTile(x, y + i); i++)
                 {
                 }
                 if (i + num4 / genRand.Next(1, 21) > num3)
                 {
                     return false;
                 }
             }
             else
             {
                 num4 += 25;
             }
             num4 += i * 2;
             if (num4 > genRand.Next(40, 61))
             {
                 return false;
             }
             tile = Main.tile[x, y];
             tile.active(active: true);
             tile.type = 571;
             tile.frameX = 0;
             tile.frameY = 0;
             tile.slope(0);
             tile.halfBrick(halfBrick: false);
             SquareTileFrame(x, y);
             return true;
         }
         return false;
     }
References Tile.active(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.slope(), SolidTile, Main.tile, Tile.type, Tile.wall, and Main.worldSurface.