Terraria: WorldGen.Check3x2
Check3x2()
static void WorldGen.Check3x2 (int i, int j, int type) inline static
     {
         if (destroyObject)
         {
             return;
         }
         bool flag = false;
         bool flag2 = false;
         int num = j;
         if (Main.tile[i, j] == null)
         {
             Main.tile[i, j] = new Tile();
         }
         int num2 = 36;
         int num3 = Main.tile[i, j].frameY / num2;
         int num4 = Main.tile[i, j].frameY % num2;
         num -= num4 / 18;
         int num5 = Main.tile[i, j].frameX / 18;
         int num6 = 0;
         while (num5 > 2)
         {
             num5 -= 3;
             num6++;
         }
         num5 = i - num5;
         int num7 = num6 * 54;
         if (type == 14 && num6 == 25)
         {
             flag2 = true;
         }
         int num8 = num + 2;
         if (flag2)
         {
             num8--;
         }
         for (int k = num5; k < num5 + 3; k++)
         {
             for (int l = num; l < num8; l++)
             {
                 if (Main.tile[k, l] == null)
                 {
                     Main.tile[k, l] = new Tile();
                 }
                 if (!Main.tile[k, l].active() || Main.tile[k, l].type != type || Main.tile[k, l].frameX != (k - num5) * 18 + num7 || Main.tile[k, l].frameY != (l - num) * 18 + num3 * 36)
                 {
                     flag = true;
                 }
             }
             if (type == 285 || type == 286 || type == 298 || type == 299 || type == 310 || type == 339 || type == 538 || (type >= 361 && type <= 364) || type == 532 || type == 544 || type == 533 || type == 555 || type == 556 || type == 582 || type == 619 || type == 629)
             {
                 if (!SolidTileAllowBottomSlope(k, num8) && (Main.tile[k, num8] == null || !Main.tile[k, num8].nactive() || !Main.tileSolidTop[Main.tile[k, num8].type] || Main.tile[k, num8].frameY != 0) && (Main.tile[k, num8] == null || !Main.tile[k, num8].active() || !TileID.Sets.Platforms[Main.tile[k, num8].type]))
                 {
                     flag = true;
                 }
             }
             else
             {
                 switch (type)
                 {
                 case 488:
                 {
                     int num9 = 0;
                     if (Main.tile[k, num8] != null && Main.tile[k, num8].active())
                     {
                         num9 = Main.tile[k, num8].type;
                     }
                     if (num9 != 2 && num9 != 477 && num9 != 109 && num9 != 492)
                     {
                         flag = true;
                     }
                     break;
                 }
                 case 26:
                 {
                     Tile tile2 = Main.tile[k, num8];
                     if (!SolidTileAllowBottomSlope(k, num8) || (tile2 != null && tile2.active() && TileID.Sets.Boulders[tile2.type]))
                     {
                         flag = true;
                     }
                     break;
                 }
                 case 186:
                 {
                     if (!SolidTileAllowBottomSlope(k, num8))
                     {
                         flag = true;
                         break;
                     }
                     Tile tile = Main.tile[k, num8];
                     if (tile == null || !tile.active())
                     {
                         break;
                     }
                     switch (num6)
                     {
                     case 26:
                     case 27:
                     case 28:
                     case 29:
                     case 30:
                     case 31:
                         if (!TileID.Sets.Snow[tile.type] && !TileID.Sets.Conversion.Ice[tile.type] && tile.type != 162 && tile.type != 224)
{
                             flag = true;
                         }
                         break;
                     case 32:
                     case 33:
                     case 34:
                         if (!TileID.Sets.Mud[tile.type] && tile.type != 70)
{
                             flag = true;
                         }
                         break;
                     }
                     break;
                 }
                 }
             }
             if (type == 187)
             {
                 if (!SolidTileAllowBottomSlope(k, num8))
                 {
                     flag = true;
                     continue;
                 }
                 Tile tile3 = Main.tile[k, num8];
                 if (tile3 == null || !tile3.active())
                 {
                     continue;
                 }
                 switch (num6)
                 {
                 case 0:
                 case 1:
                 case 2:
                 case 3:
                 case 4:
                 case 5:
                     if (!TileID.Sets.Mud[tile3.type] && tile3.type != 60 && tile3.type != 226)
                     {
                         flag = true;
                     }
                     break;
                 case 6:
                 case 7:
                 case 8:
                     if (tile3.type != 57 && tile3.type != 58 && tile3.type != 75 && tile3.type != 76)
                     {
                         flag = true;
                     }
                     break;
                 case 29:
                 case 30:
                 case 31:
                 case 32:
                 case 33:
                 case 34:
                     if (!TileID.Sets.Conversion.Sand[tile3.type] && !TileID.Sets.Conversion.HardenedSand[tile3.type] && !TileID.Sets.Conversion.Sandstone[tile3.type])
                     {
                         flag = true;
                     }
                     break;
                 }
             }
             else if (!SolidTileAllowBottomSlope(k, num8))
             {
                 flag = true;
             }
         }
         if (type == 187 && Main.tile[num5, num] != null && Main.tile[num5, num].frameX >= 756 && Main.tile[num5, num].frameX <= 900 && Main.tile[num5, num + 2].type != 2 && Main.tile[num5 + 1, num + 2].type != 2 && Main.tile[num5 + 2, num + 2].type != 2 && Main.tile[num5, num + 2].type != 477 && Main.tile[num5 + 1, num + 2].type != 477 && Main.tile[num5 + 2, num + 2].type != 477 && Main.tile[num5, num + 2].type != 492 && Main.tile[num5 + 1, num + 2].type != 492 && Main.tile[num5 + 2, num + 2].type != 492)
         {
             Main.tile[num5, num].frameX -= 378;
             Main.tile[num5 + 1, num].frameX -= 378;
             Main.tile[num5 + 2, num].frameX -= 378;
             Main.tile[num5, num + 1].frameX -= 378;
             Main.tile[num5 + 1, num + 1].frameX -= 378;
             Main.tile[num5 + 2, num + 1].frameX -= 378;
             Main.tile[num5, num].type = 186;
             Main.tile[num5 + 1, num].type = 186;
             Main.tile[num5 + 2, num].type = 186;
             Main.tile[num5, num + 1].type = 186;
             Main.tile[num5 + 1, num + 1].type = 186;
             Main.tile[num5 + 2, num + 1].type = 186;
         }
         if (flag && type == 488 && gen)
         {
             for (int m = num5; m < num5 + 3; m++)
             {
                 for (int n = num; n < num + 2; n++)
                 {
                     Main.tile[m, n].active(active: true);
                     Main.tile[m, n].type = 488;
                     Main.tile[m, n].frameX = (short)((m - num5) * 18);
                     Main.tile[m, n].frameY = (short)((n - num) * 18);
                 }
                 Main.tile[m, num + 2].active(active: true);
                 Main.tile[m, num + 2].type = 2;
                 Main.tile[m, num + 2].slope(0);
                 Main.tile[m, num + 2].halfBrick(halfBrick: false);
             }
             flag = false;
         }
         if (!flag)
         {
             return;
         }
         int frameX = Main.tile[i, j].frameX;
         destroyObject = true;
         num8 = num + 3;
         if (flag2)
         {
             num8--;
         }
         for (int num10 = num5; num10 < num5 + 3; num10++)
         {
             for (int num11 = num; num11 < num + 3; num11++)
             {
                 if (Main.tile[num10, num11] == null)
                 {
                     Main.tile[num10, num11] = new Tile();
                 }
                 if (Main.tile[num10, num11].type == type && Main.tile[num10, num11].active())
                 {
                     KillTile(num10, num11);
                 }
             }
         }
         if (type == 14)
         {
             int type2 = ((num6 >= 1 && num6 <= 3) ? (637 + num6) : ((num6 >= 15 && num6 <= 20) ? (1698 + num6) : ((num6 >= 4 && num6 <= 7) ? (823 + num6) : (num6 switch
             {
                 8 => 917,
                 9 => 1144,
                 10 => 1397,
                 11 => 1400,
                 12 => 1403,
                 13 => 1460,
                 14 => 1510,
                 23 => 1926,
                 21 => 1794,
                 22 => 1816,
                 24 => 2248,
                 25 => 2259,
                 26 => 2532,
                 27 => 2550,
                 28 => 677,
                 29 => 2583,
                 30 => 2743,
                 31 => 2824,
                 32 => 3153,
                 33 => 3155,
                 34 => 3154,
                 _ => 32,
             }))));
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, type2);
         }
         switch (type)
         {
         case 469:
         {
             int type4 = 3920;
             if (num6 == 1)
             {
                 type4 = 3948;
             }
             if (num6 == 2)
             {
                 type4 = 3974;
             }
             if (num6 == 3)
             {
                 type4 = 4162;
             }
             if (num6 == 4)
             {
                 type4 = 4183;
             }
             if (num6 == 5)
             {
                 type4 = 4204;
             }
             if (num6 == 6)
             {
                 type4 = 4225;
             }
             if (num6 == 7)
             {
                 type4 = 4314;
             }
             if (num6 == 8)
             {
                 type4 = 4583;
             }
             if (num6 == 9)
             {
                 type4 = 5165;
             }
             if (num6 == 10)
             {
                 type4 = 5186;
             }
             if (num6 == 11)
             {
                 type4 = 5207;
             }
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, type4);
             break;
         }
         case 114:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 398);
             break;
         case 26:
             if (!noTileActions && !IsGeneratingHardMode)
             {
                 SmashAltar(i, j);
             }
             break;
         case 298:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2190);
             break;
         case 299:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2191);
             break;
         case 361:
         case 362:
         case 363:
         case 364:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3073 + type - 361);
             break;
         default:
             if (type >= 391 && type <= 394)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 48, 32, 3254 + type - 391);
                 break;
             }
             switch (type)
             {
             case 285:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2174);
                 break;
             case 286:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2175);
                 break;
             case 582:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4850);
                 break;
             case 619:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4963);
                 break;
             case 310:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2207);
                 break;
             case 339:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2741);
                 break;
             case 538:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4380);
                 break;
             case 544:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4399);
                 break;
             case 532:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4364);
                 break;
             case 533:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4376);
                 break;
             case 555:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4475);
                 break;
             case 556:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4476);
                 break;
             case 629:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5133);
                 break;
             case 217:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 995);
                 break;
             case 218:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 996);
                 break;
             case 219:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 997);
                 break;
             case 642:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5296);
                 break;
             case 220:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 998);
                 break;
             case 377:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3198);
                 break;
             case 228:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1120);
                 break;
             case 405:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3364);
                 break;
             case 486:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4063);
                 break;
             case 488:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 9, genRand.Next(10, 21));
                 break;
             case 215:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, GetCampfireItemDrop(num6));
                 break;
             case 244:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1449);
                 break;
             case 647:
             {
                 int num13 = 0;
                 if (num6 < 7)
                 {
                     num13 = 154;
                 }
                 else if (num6 < 13)
                 {
                     num13 = 3;
                 }
                 else if (num6 < 16)
                 {
                     num13 = 3;
                 }
                 else if (num6 < 18)
                 {
                     num13 = 71;
                 }
                 else if (num6 < 20)
                 {
                     num13 = 72;
                 }
                 else if (num6 < 22)
                 {
                     num13 = 73;
                 }
                 else if (num6 < 26)
                 {
                     num13 = 9;
                 }
                 else if (num6 < 32)
                 {
                     num13 = 593;
                 }
                 else if (num6 < 35)
                 {
                     num13 = 183;
                 }
                 if (num13 != 0)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num13);
                 }
                 break;
             }
             case 648:
             {
                 num6 += num3 * 35;
                 int num12 = 0;
                 if (num6 < 6)
                 {
                     num12 = 195;
                 }
                 else if (num6 < 9)
                 {
                     num12 = 174;
                 }
                 else if (num6 < 14)
                 {
                     num12 = 150;
                 }
                 else if (num6 < 17)
                 {
                     num12 = 3;
                 }
                 else if (num6 < 18)
                 {
                     num12 = 989;
                 }
                 else if (num6 < 21)
                 {
                     num12 = 1101;
                 }
                 else if (num6 < 29)
                 {
                     num12 = 9;
                 }
                 else if (num6 < 35)
                 {
                     num12 = 3271;
                 }
                 else if (num6 < 41)
                 {
                     num12 = 3086;
                 }
                 else if (num6 < 47)
                 {
                     num12 = 3081;
                 }
                 else if (num6 < 52)
                 {
                     num12 = 62;
                 }
                 else if (num6 < 55)
                 {
                     num12 = 154;
                 }
                 if (num12 != 0)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num12);
                 }
                 break;
             }
             case 651:
             {
                 int num14 = 0;
                 num14 = ((num6 < 3) ? 195 : ((num6 >= 6) ? 331 : 62));
                 if (num14 != 0)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num14);
                 }
                 break;
             }
             case 17:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 33);
                 break;
             case 77:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 221);
                 break;
             case 86:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 332);
                 break;
             case 237:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1292);
                 break;
             case 87:
             {
                 int type3;
                 if (num6 >= 1 && num6 <= 3)
                 {
                     type3 = 640 + num6;
                 }
                 else
                 {
                     switch (num6)
                     {
                     case 4:
                         type3 = 919;
                         break;
                     case 5:
                     case 6:
                     case 7:
                         type3 = 2245 + num6 - 5;
                         break;
                     default:
                         type3 = ((num6 >= 8 && num6 <= 10) ? (2254 + num6 - 8) : ((num6 >= 11 && num6 <= 20) ? (2376 + num6 - 11) : (num6 switch
{
                             21 => 2531,
                             22 => 2548,
                             23 => 2565,
                             24 => 2580,
                             25 => 2671,
                             26 => 2821,
                             27 => 3141,
                             28 => 3143,
                             29 => 3142,
                             30 => 3915,
                             31 => 3916,
                             32 => 3944,
                             33 => 3971,
                             34 => 4158,
                             35 => 4179,
                             36 => 4200,
                             37 => 4221,
                             38 => 4310,
                             39 => 4579,
                             40 => 5161,
                             41 => 5182,
                             42 => 5203,
                             _ => 333,
                         })));
                         break;
                     }
                 }
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, type3);
                 break;
             }
             case 88:
             {
                 int dresserItemDrop = GetDresserItemDrop(num6);
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, dresserItemDrop);
                 break;
             }
             case 89:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, GetItemDrop_Benches(num6));
                 break;
             case 133:
                 if (frameX >= 54)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1221);
                 }
                 else
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 524);
                 }
                 break;
             case 186:
                 if (frameX < 864)
                 {
                     break;
                 }
                 if (frameX <= 954)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                     if (genRand.Next(3) != 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                     }
                     if (genRand.Next(3) != 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                     }
                     if (genRand.Next(3) != 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                     }
                     if (genRand.Next(2) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                     }
                     if (genRand.Next(2) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                     }
                     if (genRand.Next(2) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                     }
                     if (genRand.Next(3) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                     }
                     if (genRand.Next(3) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                     }
                     if (genRand.Next(3) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                     }
                     if (genRand.Next(4) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                     }
                     if (genRand.Next(4) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                     }
                     if (genRand.Next(4) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                     }
                     if (genRand.Next(5) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                     }
                     if (genRand.Next(5) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                     }
                     if (genRand.Next(5) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                     }
                 }
                 else if (frameX <= 1062)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, genRand.Next(10, 100));
                     if (genRand.Next(2) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, genRand.Next(20, 100));
                     }
                     if (genRand.Next(3) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, genRand.Next(30, 100));
                     }
                     if (genRand.Next(4) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, genRand.Next(40, 100));
                     }
                     if (genRand.Next(5) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, genRand.Next(50, 100));
                     }
                 }
                 else if (frameX <= 1170)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73, genRand.Next(1, 7));
                     if (genRand.Next(2) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73, genRand.Next(2, 7));
                     }
                     if (genRand.Next(3) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73, genRand.Next(3, 7));
                     }
                     if (genRand.Next(4) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73, genRand.Next(4, 7));
                     }
                     if (genRand.Next(5) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73, genRand.Next(5, 7));
                     }
                 }
                 break;
             case 187:
                 if (frameX >= 918 && frameX <= 970)
                 {
                     if (Main.rand.Next(50) == 0)
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4144);
                     }
                     else
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 989);
                     }
                 }
                 break;
             }
             break;
         }
         destroyObject = false;
         for (int num15 = num5 - 1; num15 < num5 + 4; num15++)
         {
             for (int num16 = num - 1; num16 < num + 4; num16++)
             {
                 TileFrame(num15, num16);
             }
         }
         if (type == 488)
         {
             mysticLogsEvent.FallenLogDestroyed();
         }
     }
References Tile.active(), TileID.Sets.Boulders, MysticLogFairiesEvent.FallenLogDestroyed(), Tile.frameX, Tile.frameY, Tile.halfBrick(), TileID.Sets.Conversion.HardenedSand, TileID.Sets.Conversion.Ice, TileID.Sets.Mud, Tile.nactive(), Item.NewItem(), UnifiedRandom.Next(), TileID.Sets.Platforms, Main.rand, TileID.Sets.Conversion.Sand, TileID.Sets.Conversion.Sandstone, Tile.slope(), TileID.Sets.Snow, Main.tile, Main.tileSolidTop, and Tile.type.