Terraria: WorldGen.paintWall
paintWall()
static bool WorldGen.paintWall (int x, int y, byte color, bool broadCast = false) inline static
     {
         Tile tile = Main.tile[x, y];
         if (tile == null || tile.wall == 0)
         {
             return false;
         }
         byte b = tile.wallColor();
         if (b == color)
         {
             return false;
         }
         tile.wallColor(color);
         if (broadCast)
         {
             NetMessage.SendData(64, -1, -1, null, x, y, (int)color);
         }
         paintEffect(x, y, color, b);
         return true;
     }
References NetMessage.SendData(), Main.tile, Tile.wall, and Tile.wallColor().
Referenced by Player.ApplyPaint(), MessageBuffer.GetData(), and Player.PlaceThing_PaintScrapper_TryScrapping().