Terraria: WorldGen.PlaceWall
PlaceWall()
static void WorldGen.PlaceWall (int i, int j, int type, bool mute = false) inline static
     {
         if (i <= 1 || j <= 1 || i >= Main.maxTilesX - 2 || j >= Main.maxTilesY - 2)
         {
             return;
         }
         if (Main.tile[i, j] == null)
         {
             Main.tile[i, j] = new Tile();
         }
         if (Main.tile[i, j].wall == 0)
         {
             Main.tile[i, j].wall = (ushort)type;
             SquareWallFrame(i, j);
             if (!mute)
             {
                 SoundEngine.PlaySound(0, i * 16, j * 16);
             }
         }
     }
References Main.maxTilesX, Main.maxTilesY, SoundEngine.PlaySound(), Main.tile, and Tile.wall.
Referenced by MessageBuffer.GetData(), Player.PlaceThing_Walls(), and Player.PlaceThing_Walls_FillEmptySpace().