Terraria: WorldGen.playWorldCallBack
playWorldCallBack()
static void WorldGen.playWorldCallBack (object threadContext) inline static
     {
         if (Main.rand == null)
         {
             Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
         }
         for (int i = 0; i < 255; i++)
         {
             if (i != Main.myPlayer)
             {
                 Main.player[i].active = false;
             }
         }
         noMapUpdate = true;
         Main.ToggleGameplayUpdates(state: false);
         WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
         if (loadFailed || !loadSuccess)
         {
             WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
             if (loadFailed || !loadSuccess)
             {
                 bool isCloudSave = Main.ActiveWorldFileData.IsCloudSave;
                 if (FileUtilities.Exists(Main.worldPathName + ".bak", isCloudSave))
                 {
                     worldBackup = true;
                 }
                 else
                 {
                     worldBackup = false;
                 }
                 if (!Main.dedServ)
                 {
                     if (worldBackup)
                     {
                         Main.menuMode = 200;
                     }
                     else
                     {
                         Main.menuMode = 201;
                     }
                     return;
                 }
                 if (!worldBackup)
                 {
                     Console.WriteLine(Language.GetTextValue("Error.LoadFailedNoBackup"));
                     return;
                 }
                 FileUtilities.Copy(Main.worldPathName, Main.worldPathName + ".bad", isCloudSave);
                 FileUtilities.Copy(Main.worldPathName + ".bak", Main.worldPathName, isCloudSave);
                 FileUtilities.Delete(Main.worldPathName + ".bak", isCloudSave);
                 WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
                 if (loadFailed || !loadSuccess)
                 {
                     WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
                     if (loadFailed || !loadSuccess)
                     {
                         FileUtilities.Copy(Main.worldPathName, Main.worldPathName + ".bak", isCloudSave);
                         FileUtilities.Copy(Main.worldPathName + ".bad", Main.worldPathName, isCloudSave);
                         FileUtilities.Delete(Main.worldPathName + ".bad", isCloudSave);
                         Console.WriteLine(Language.GetTextValue("Error.LoadFailed"));
                         return;
                     }
                 }
             }
         }
         if (Main.mapEnabled)
         {
             Main.Map.Load();
         }
         if (Main.netMode != 2)
         {
             Main.sectionManager.SetAllSectionsLoaded();
         }
         while (Main.loadMapLock)
         {
             float num = (float)Main.loadMapLastX / (float)Main.maxTilesX;
             Main.statusText = Lang.gen[68].Value + " " + (int)(num * 100f + 1f) + "%";
             Thread.Sleep(0);
             if (!Main.mapEnabled)
             {
                 break;
             }
         }
         if (Main.gameMenu)
         {
             Main.gameMenu = false;
         }
         if (Main.netMode == 0 && Main.anglerWhoFinishedToday.Contains(Main.player[Main.myPlayer].name))
         {
             Main.anglerQuestFinished = true;
         }
         Main.player[Main.myPlayer].Spawn(PlayerSpawnContext.SpawningIntoWorld);
         _lastSeed = Main.ActiveWorldFileData.Seed;
         WorldFile.SetOngoingToTemps();
         SoundEngine.PlaySound(11);
         Main.resetClouds = true;
         noMapUpdate = false;
     }
References _lastSeed, Entity.active, Main.ActiveWorldFileData, Main.anglerQuestFinished, Main.anglerWhoFinishedToday, FileUtilities.Copy(), Main.dedServ, FileUtilities.Delete(), FileUtilities.Exists(), Main.gameMenu, Lang.gen, Language.GetTextValue(), FileData.IsCloudSave, WorldMap.Load(), loadFailed, Main.loadMapLastX, Main.loadMapLock, loadSuccess, WorldFile.LoadWorld(), Main.Map, Main.mapEnabled, Main.maxTilesX, Main.menuMode, Main.myPlayer, Player.name, Main.netMode, noMapUpdate, Main.player, SoundEngine.PlaySound(), Main.rand, Main.resetClouds, Main.sectionManager, WorldFileData.Seed, WorldSections.SetAllSectionsLoaded(), WorldFile.SetOngoingToTemps(), Player.Spawn(), Main.statusText, Main.ToggleGameplayUpdates(), LocalizedText.Value, worldBackup, and Main.worldPathName.
Referenced by playWorld().