Terraria: WorldGen.IsBelowANonHammeredPlatform
IsBelowANonHammeredPlatform()
static bool WorldGen.IsBelowANonHammeredPlatform (int x, int y) inline static
     {
         if (y < 1)
         {
             return false;
         }
         Tile tile = Main.tile[x, y - 1];
         if (tile == null || !tile.active() || !TileID.Sets.Platforms[tile.type] || tile.halfBrick() || tile.slope() != 0)
         {
             return false;
         }
         return true;
     }
References Tile.active(), Tile.halfBrick(), TileID.Sets.Platforms, Tile.slope(), Main.tile, and Tile.type.
Referenced by TileDrawing.DrawMultiTileVinesInWind().