Terraria: WorldGen.PaintTheTemple
PaintTheTemple()
static void WorldGen.PaintTheTemple (byte tilePaintColor, byte wallPaintColor) inline static private
     {
         for (int i = 0; i < Main.maxTilesX; i++)
         {
             for (int j = 0; j < Main.maxTilesY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile.active())
                 {
                     bool flag = false;
                     if (tile.type == 226)
                     {
                         flag = true;
                     }
                     if (tile.type == 137)
                     {
                         int num = tile.frameY / 18;
                         if (num >= 1 && num <= 4)
{
                             flag = true;
                         }
                     }
                     if (flag)
                     {
                         tile.color(tilePaintColor);
                     }
                 }
                 if (tile.wall == 87)
                 {
                     tile.wallColor(wallPaintColor);
                 }
             }
         }
     }
References Tile.active(), Tile.color(), Tile.frameY, Main.maxTilesX, Main.maxTilesY, Main.tile, Tile.type, Tile.wall, and Tile.wallColor().