Terraria: WorldGen.SlopeTile
SlopeTile()
static bool WorldGen.SlopeTile (int i, int j, int slope = 0, bool noEffects = false) inline static
     {
         if (!CanPoundTile(i, j))
         {
             return false;
         }
         Main.tile[i, j].halfBrick(halfBrick: false);
         Main.tile[i, j].slope((byte)slope);
         if (!gen)
         {
             if (!noEffects)
             {
                 KillTile(i, j, fail: true, effectOnly: true);
             }
             SoundEngine.PlaySound(0, i * 16, j * 16);
             SquareTileFrame(i, j);
             if (Main.tile[i, j].slope() == 0)
             {
                 Rectangle rectangle = new Rectangle(i * 16, j * 16, 16, 16);
                 for (int k = 0; k < 255; k++)
                 {
                     if (Main.player[k].active && !Main.player[k].dead && rectangle.Intersects(new Rectangle((int)Main.player[k].position.X, (int)Main.player[k].position.Y, Main.player[k].width, Main.player[k].height)))
                     {
                         Main.player[k].gfxOffY += Main.player[k].position.Y + (float)Main.player[k].height - (float)rectangle.Y;
                         Main.player[k].position.Y = rectangle.Y - Main.player[k].height;
                     }
                 }
             }
         }
         return true;
     }
References Entity.active, Player.dead, Player.gfxOffY, Tile.halfBrick(), Entity.height, Main.player, SoundEngine.PlaySound(), Entity.position, Tile.slope(), Main.tile, and Entity.width.
Referenced by Projectile.AI_010(), Actions.SetSlope.Apply(), MessageBuffer.GetData(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), TileObject.Place(), Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), and DelegateMethods.SpreadDirt().