Terraria: WorldGen.PaintTheClouds
PaintTheClouds()
static void WorldGen.PaintTheClouds (byte tilePaintColor, byte wallPaintColor) inline static private
     {
         for (int i = 0; i < Main.maxTilesX; i++)
         {
             for (int j = 0; j < Main.maxTilesY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile.active() && (tile.type == 189 || tile.type == 196 || tile.type == 460))
                 {
                     tile.color(tilePaintColor);
                 }
                 if (tile.wall == 73)
                 {
                     tile.wallColor(wallPaintColor);
                 }
             }
         }
     }
References Tile.active(), Tile.color(), Main.maxTilesX, Main.maxTilesY, Main.tile, Tile.type, Tile.wall, and Tile.wallColor().