Terraria: WorldGen.PlaceSunflower
PlaceSunflower()
static void WorldGen.PlaceSunflower (int x, int y, ushort type = 27) inline static
     {
         if ((double)y > Main.worldSurface - 1.0 && !Main.remixWorld)
         {
             return;
         }
         bool flag = true;
         for (int i = x; i < x + 2; i++)
         {
             for (int j = y - 3; j < y + 1; j++)
             {
                 if (Main.tile[i, j] == null)
                 {
                     Main.tile[i, j] = new Tile();
                 }
                 if (Main.tile[i, j].active() || Main.tile[i, j].wall > 0)
                 {
                     flag = false;
                 }
             }
             if (Main.tile[i, y + 1] == null)
             {
                 Main.tile[i, y + 1] = new Tile();
             }
             if (!Main.tile[i, y + 1].nactive() || Main.tile[i, y + 1].halfBrick() || Main.tile[i, y + 1].slope() != 0 || (Main.tile[i, y + 1].type != 2 && Main.tile[i, y + 1].type != 109))
             {
                 flag = false;
             }
         }
         if (!flag)
         {
             return;
         }
         int num = genRand.Next(3);
         for (int k = 0; k < 2; k++)
         {
             for (int l = -3; l < 1; l++)
             {
                 int num2 = k * 18 + genRand.Next(3) * 36;
                 if (l <= -2)
                 {
                     num2 = k * 18 + num * 36;
                 }
                 int num3 = (l + 3) * 18;
                 Main.tile[x + k, y + l].active(active: true);
                 Main.tile[x + k, y + l].frameX = (short)num2;
                 Main.tile[x + k, y + l].frameY = (short)num3;
                 Main.tile[x + k, y + l].type = type;
             }
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.nactive(), Main.remixWorld, Tile.slope(), Main.tile, Tile.type, Tile.wall, and Main.worldSurface.