Terraria: WorldGen.ShiftTrapdoor
ShiftTrapdoor()
static bool WorldGen.ShiftTrapdoor (int x, int y, bool playerAbove, int onlyCloseOrOpen = -1) inline static
     {
         Tile tileSafely = Framing.GetTileSafely(x, y);
         if (tileSafely.type == 386 && onlyCloseOrOpen != 1)
         {
             Point topLeftAndStyles = GetTopLeftAndStyles(ref x, ref y, 2, 2, 18, 18);
             if (topLeftAndStyles.X == 0)
             {
                 if (Main.netMode != 1 && Wiring.running)
                 {
                     Wiring.SkipWire(x, y);
                     Wiring.SkipWire(x, y + 1);
                     Wiring.SkipWire(x + 1, y);
                     Wiring.SkipWire(x + 1, y + 1);
                 }
                 if (!Collision.EmptyTile(x, y + 1, ignoreTiles: true) || !Collision.EmptyTile(x + 1, y + 1, ignoreTiles: true))
                 {
                     return false;
                 }
                 SoundEngine.PlaySound(8, x * 16 + 16, y * 16 + 16);
                 for (int i = 0; i < 2; i++)
                 {
                     tileSafely = Framing.GetTileSafely(x + i, y);
                     tileSafely.ClearTile();
                 }
                 for (int j = 0; j < 2; j++)
                 {
                     tileSafely = Framing.GetTileSafely(x + j, y + 1);
                     tileSafely.type = 387;
                     tileSafely.frameX = (short)(j * 18);
                     tileSafely.frameY = (short)(topLeftAndStyles.Y * 18);
                 }
                 for (int k = -1; k < 3; k++)
                 {
                     for (int l = 0; l < 3; l++)
                     {
                         TileFrame(x + k, y + l);
                     }
                 }
                 return true;
             }
             if (topLeftAndStyles.X == 1)
             {
                 if (Main.netMode != 1 && Wiring.running)
                 {
                     Wiring.SkipWire(x, y - 1);
                     Wiring.SkipWire(x, y);
                     Wiring.SkipWire(x + 1, y - 1);
                     Wiring.SkipWire(x + 1, y);
                 }
                 if (!Collision.EmptyTile(x, y, ignoreTiles: true) || !Collision.EmptyTile(x + 1, y, ignoreTiles: true))
                 {
                     return false;
                 }
                 SoundEngine.PlaySound(8, x * 16 + 16, y * 16);
                 for (int m = 0; m < 2; m++)
                 {
                     tileSafely = Framing.GetTileSafely(x + m, y + 1);
                     tileSafely.ClearTile();
                 }
                 for (int n = 0; n < 2; n++)
                 {
                     tileSafely = Framing.GetTileSafely(x + n, y);
                     tileSafely.type = 387;
                     tileSafely.frameX = (short)(n * 18);
                     tileSafely.frameY = (short)(topLeftAndStyles.Y * 18);
                 }
                 for (int num = -1; num < 3; num++)
                 {
                     for (int num2 = -1; num2 < 2; num2++)
                     {
                         TileFrame(x + num, y + num2);
                     }
                 }
                 return true;
             }
         }
         if (tileSafely.type == 387 && onlyCloseOrOpen != 0)
         {
             GetTopLeftAndStyles(ref x, ref y, 2, 1, 18, 18);
             int num3 = playerAbove.ToDirectionInt();
             for (int num4 = 0; num4 < 2; num4++)
             {
                 tileSafely = Framing.GetTileSafely(x + num4, y + num3);
                 if (tileSafely.active() && !Main.tileCut[tileSafely.type])
                 {
                     return false;
                 }
             }
             if (Main.netMode != 1 && Wiring.running)
             {
                 Wiring.SkipWire(x, y);
                 Wiring.SkipWire(x, y + num3);
                 Wiring.SkipWire(x + 1, y);
                 Wiring.SkipWire(x + 1, y + num3);
             }
             SoundEngine.PlaySound(8, x * 16 + 16, y * 16);
             for (int num5 = 0; num5 < 2; num5++)
             {
                 tileSafely = Framing.GetTileSafely(x + num5, y + num3);
                 if (tileSafely.active() && Main.tileCut[tileSafely.type])
                 {
                     KillTile(x + num5, y + num3);
                 }
             }
             for (int num6 = 0; num6 < 2; num6++)
             {
                 tileSafely = Framing.GetTileSafely(x + num6, y);
                 TileColorCache cache = tileSafely.BlockColorAndCoating();
                 for (int num7 = 0; num7 < 2; num7++)
                 {
                     tileSafely = Framing.GetTileSafely(x + num6, y + num7 - (!playerAbove).ToInt());
                     tileSafely.type = 386;
                     tileSafely.frameX = (short)(num6 * 18 + playerAbove.ToInt() * 36);
                     tileSafely.frameY = (short)(num7 * 18);
                     tileSafely.UseBlockColors(cache);
                     tileSafely.active(active: true);
                 }
             }
             for (int num8 = -1; num8 < 3; num8++)
             {
                 for (int num9 = -1; num9 < 3; num9++)
                 {
                     TileFrame(x + num8, y + num9 - (!playerAbove).ToInt() * 2);
                 }
             }
             return true;
         }
         SoundEngine.PlaySound(9, x * 16, y * 16);
         return false;
     }
References Tile.active(), Tile.BlockColorAndCoating(), Tile.ClearTile(), Collision.EmptyTile(), Tile.frameX, Tile.frameY, Framing.GetTileSafely(), Main.netMode, SoundEngine.PlaySound(), Wiring.running, Wiring.SkipWire(), Main.tileCut, Tile.type, and Tile.UseBlockColors().
Referenced by MessageBuffer.GetData(), Wiring.HitWireSingle(), and Player.TileInteractionsUse().