Terraria: WorldGen.TryGrowingAbigailsFlower
TryGrowingAbigailsFlower()
static bool WorldGen.TryGrowingAbigailsFlower (int i, int j) inline static private
     {
         if (Main.rand.Next(30) != 0)
         {
             return false;
         }
         int num = 1;
         if (Main.dontStarveWorld)
         {
             num = 2;
         }
         for (int k = 0; k < num; k++)
         {
             int num2 = genRand.Next(Math.Max(10, i - 10), Math.Min(Main.maxTilesX - 10, i + 10));
             int num3 = genRand.Next(Math.Max(10, j - 10), Math.Min(Main.maxTilesY - 10, j + 10));
             if (HasValidGroundForAbigailsFlowerBelowSpot(num2, num3) && NoNearbyAbigailsFlower(num2, num3) && PlaceTile(num2, num3, 624, mute: true))
             {
                 if (Main.netMode == 2 && Main.tile[num2, num3] != null && Main.tile[num2, num3].active())
                 {
                     NetMessage.SendTileSquare(-1, num2, num3);
                 }
                 return true;
             }
         }
         return false;
     }
References Tile.active(), Main.dontStarveWorld, Main.maxTilesX, Main.maxTilesY, Main.netMode, UnifiedRandom.Next(), Main.rand, NetMessage.SendTileSquare(), and Main.tile.