Terraria: WorldGen.GrowShroom
GrowShroom()
static bool WorldGen.GrowShroom (int i, int y) inline static
     {
         if (Main.tile[i - 1, y - 1].lava() || Main.tile[i - 1, y - 1].lava() || Main.tile[i + 1, y - 1].lava())
         {
             return false;
         }
         if (Main.tile[i, y].nactive() && Main.tile[i, y].type == 70 && Main.tile[i, y - 1].wall == 0 && Main.tile[i - 1, y].active() && Main.tile[i - 1, y].type == 70 && Main.tile[i + 1, y].active() && Main.tile[i + 1, y].type == 70 && EmptyTileCheck(i - 2, i + 2, y - 13, y - 3, 71) && EmptyTileCheck(i - 1, i + 1, y - 3, y - 1, 71))
         {
             if (gen && genRand.Next(3) != 0)
             {
                 Main.tile[i, y].halfBrick(halfBrick: false);
                 Main.tile[i, y].slope(0);
             }
             if (!Main.tile[i, y].halfBrick() && Main.tile[i, y].slope() == 0)
             {
                 int num = genRand.Next(4, 11);
                 for (int j = y - num; j < y; j++)
                 {
                     Main.tile[i, j].frameNumber((byte)genRand.Next(3));
                     Main.tile[i, j].active(active: true);
                     Main.tile[i, j].type = 72;
                     int num2 = genRand.Next(3);
                     if (num2 == 0)
                     {
                         Main.tile[i, j].frameX = 0;
                         Main.tile[i, j].frameY = 0;
                     }
                     if (num2 == 1)
                     {
                         Main.tile[i, j].frameX = 0;
                         Main.tile[i, j].frameY = 18;
                     }
                     if (num2 == 2)
                     {
                         Main.tile[i, j].frameX = 0;
                         Main.tile[i, j].frameY = 36;
                     }
                 }
                 int num3 = genRand.Next(3);
                 if (num3 == 0)
                 {
                     Main.tile[i, y - num].frameX = 36;
                     Main.tile[i, y - num].frameY = 0;
                 }
                 if (num3 == 1)
                 {
                     Main.tile[i, y - num].frameX = 36;
                     Main.tile[i, y - num].frameY = 18;
                 }
                 if (num3 == 2)
                 {
                     Main.tile[i, y - num].frameX = 36;
                     Main.tile[i, y - num].frameY = 36;
                 }
                 RangeFrame(i - 2, y - num - 1, i + 2, y + 1);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, i - 1, y - num, 3, num);
                 }
                 return true;
             }
         }
         return false;
     }
References Tile.active(), Tile.frameNumber(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.lava(), Tile.nactive(), Main.netMode, NetMessage.SendTileSquare(), Tile.slope(), Main.tile, Tile.type, and Tile.wall.