Terraria: WorldGen.SwitchFountain
SwitchFountain()
static void WorldGen.SwitchFountain (int i, int j) inline static
     {
         int num = i;
         int num2 = j;
         int num3;
         for (num3 = Main.tile[i, j].frameX / 18; num3 >= 2; num3 -= 2)
         {
         }
         int num4 = Main.tile[i, j].frameY / 18;
         if (num4 >= 4)
         {
             num4 -= 4;
         }
         num = i - num3;
         num2 = j - num4;
         for (int k = num; k < num + 2; k++)
         {
             for (int l = num2; l < num2 + 4; l++)
             {
                 if (Main.tile[k, l] == null)
                 {
                     Main.tile[k, l] = new Tile();
                 }
                 if (Main.tile[k, l].active() && Main.tile[k, l].type == 207)
                 {
                     if (Main.tile[k, l].frameY < 72)
                     {
                         Main.tile[k, l].frameY += 72;
                     }
                     else
                     {
                         Main.tile[k, l].frameY -= 72;
                     }
                 }
             }
         }
         if (Wiring.running)
         {
             Wiring.SkipWire(num, num2);
             Wiring.SkipWire(num, num2 + 1);
             Wiring.SkipWire(num, num2 + 2);
             Wiring.SkipWire(num, num2 + 3);
             Wiring.SkipWire(num + 1, num2);
             Wiring.SkipWire(num + 1, num2 + 1);
             Wiring.SkipWire(num + 1, num2 + 2);
             Wiring.SkipWire(num + 1, num2 + 3);
         }
         NetMessage.SendTileSquare(-1, num, num2, 2, 4);
     }
References Tile.active(), Tile.frameX, Tile.frameY, Wiring.running, NetMessage.SendTileSquare(), Wiring.SkipWire(), Main.tile, and Tile.type.
Referenced by Wiring.HitWireSingle(), and Player.TileInteractionsUse().