Terraria: WorldGen.EmptyLiquid
EmptyLiquid()
static bool WorldGen.EmptyLiquid (int x, int y) inline static
     {
         if (!InWorld(x, y))
         {
             return false;
         }
         Tile tile = Main.tile[x, y];
         if (tile == null)
         {
             return false;
         }
         tile.liquidType();
         if (tile.nactive() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
         {
             return false;
         }
         tile.Clear(TileDataType.Liquid);
         SquareTileFrame(x, y, resetFrame: false);
         if (Main.netMode != 0)
         {
             NetMessage.sendWater(x, y);
         }
         else
         {
             Liquid.AddWater(x, y);
         }
         return true;
     }
References Tile.Clear(), InWorld(), Liquid, Tile.liquidType(), Tile.nactive(), Main.netMode, NetMessage.sendWater(), SquareTileFrame(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by DelegateMethods.SpreadDry().