Terraria: WorldGen.SectionTileFrameWithCheck
SectionTileFrameWithCheck()
static void WorldGen.SectionTileFrameWithCheck (int startX, int startY, int endX, int endY) inline static
     {
         int sectionX = Netplay.GetSectionX(startX);
         int sectionY = Netplay.GetSectionY(startY);
         int sectionX2 = Netplay.GetSectionX(endX);
         int sectionY2 = Netplay.GetSectionY(endY);
         for (int i = sectionX; i <= sectionX2; i++)
         {
             for (int j = sectionY; j <= sectionY2; j++)
             {
                 if (Main.sectionManager.SectionLoaded(i, j) && !Main.sectionManager.SectionFramed(i, j))
                 {
                     SectionTileFrame(i, j, i, j);
                     if (!Main.sectionManager.AnyUnfinishedSections)
                     {
                         return;
                     }
                 }
             }
         }
     }
References WorldSections.AnyUnfinishedSections, Netplay.GetSectionX(), Netplay.GetSectionY(), WorldSections.SectionFramed(), WorldSections.SectionLoaded(), and Main.sectionManager.
Referenced by Main.DrawCapture(), and TileDrawing.GetScreenDrawArea().