Terraria: WorldGen.OpenDoor
OpenDoor()
static bool WorldGen.OpenDoor (int i, int j, int direction) inline static
     {
         int num = 0;
         if (Main.tile[i, j - 1] == null)
         {
             Main.tile[i, j - 1] = new Tile();
         }
         if (Main.tile[i, j - 2] == null)
         {
             Main.tile[i, j - 2] = new Tile();
         }
         if (Main.tile[i, j + 1] == null)
         {
             Main.tile[i, j + 1] = new Tile();
         }
         if (Main.tile[i, j] == null)
         {
             Main.tile[i, j] = new Tile();
         }
         Tile tile = Main.tile[i, j];
         if (tile.type != 10)
         {
             return false;
         }
         if (IsLockedDoor(tile))
         {
             return false;
         }
         short num2 = 0;
         int num3 = tile.frameY;
         int num4 = 0;
         while (num3 >= 54)
         {
             num3 -= 54;
             num4++;
         }
         if (tile.frameX >= 54)
         {
             int num5 = tile.frameX / 54;
             num4 += 36 * num5;
             num2 += (short)(72 * num5);
         }
         num = j - num3 / 18;
         int num6 = i;
         TileColorCache cache = Main.tile[num6, num].BlockColorAndCoating();
         if (Main.tile[num6, num + 1] == null)
         {
             Main.tile[num6, num + 1] = new Tile();
         }
         TileColorCache cache2 = Main.tile[num6, num + 1].BlockColorAndCoating();
         if (Main.tile[num6, num + 2] == null)
         {
             Main.tile[num6, num + 2] = new Tile();
         }
         TileColorCache cache3 = Main.tile[num6, num + 2].BlockColorAndCoating();
         int num7;
         if (direction == -1)
         {
             num6 = i - 1;
             num2 += 36;
             num7 = i - 1;
         }
         else
         {
             num6 = i;
             num7 = i + 1;
         }
         for (int k = num; k < num + 3; k++)
         {
             if (Main.tile[num7, k] == null)
             {
                 Main.tile[num7, k] = new Tile();
             }
             if (Main.tile[num7, k].active())
             {
                 if (!Main.tileCut[Main.tile[num7, k].type] && Main.tile[num7, k].type != 3 && Main.tile[num7, k].type != 24 && Main.tile[num7, k].type != 52 && Main.tile[num7, k].type != 61 && Main.tile[num7, k].type != 62 && Main.tile[num7, k].type != 69 && Main.tile[num7, k].type != 655 && Main.tile[num7, k].type != 71 && Main.tile[num7, k].type != 73 && Main.tile[num7, k].type != 74 && Main.tile[num7, k].type != 110 && Main.tile[num7, k].type != 113 && Main.tile[num7, k].type != 115 && Main.tile[num7, k].type != 165)
                 {
                     return false;
                 }
                 KillTile(num7, k);
             }
         }
         if (Main.netMode != 1 && Wiring.running)
         {
             Wiring.SkipWire(num6, num);
             Wiring.SkipWire(num6, num + 1);
             Wiring.SkipWire(num6, num + 2);
             Wiring.SkipWire(num6 + 1, num);
             Wiring.SkipWire(num6 + 1, num + 1);
             Wiring.SkipWire(num6 + 1, num + 2);
         }
         int num8 = num4 % 36 * 54;
         SoundEngine.PlaySound(8, i * 16, j * 16);
         Main.tile[num6, num].active(active: true);
         Main.tile[num6, num].type = 11;
         Main.tile[num6, num].frameY = (short)num8;
         Main.tile[num6, num].frameX = num2;
         Main.tile[num6, num].UseBlockColors(cache);
         if (Main.tile[num6 + 1, num] == null)
         {
             Main.tile[num6 + 1, num] = new Tile();
         }
         Main.tile[num6 + 1, num].active(active: true);
         Main.tile[num6 + 1, num].type = 11;
         Main.tile[num6 + 1, num].frameY = (short)num8;
         Main.tile[num6 + 1, num].frameX = (short)(num2 + 18);
         Main.tile[num6 + 1, num].UseBlockColors(cache);
         if (Main.tile[num6, num + 1] == null)
         {
             Main.tile[num6, num + 1] = new Tile();
         }
         Main.tile[num6, num + 1].active(active: true);
         Main.tile[num6, num + 1].type = 11;
         Main.tile[num6, num + 1].frameY = (short)(num8 + 18);
         Main.tile[num6, num + 1].frameX = num2;
         Main.tile[num6, num + 1].UseBlockColors(cache2);
         if (Main.tile[num6 + 1, num + 1] == null)
         {
             Main.tile[num6 + 1, num + 1] = new Tile();
         }
         Main.tile[num6 + 1, num + 1].active(active: true);
         Main.tile[num6 + 1, num + 1].type = 11;
         Main.tile[num6 + 1, num + 1].frameY = (short)(num8 + 18);
         Main.tile[num6 + 1, num + 1].frameX = (short)(num2 + 18);
         Main.tile[num6 + 1, num + 1].UseBlockColors(cache2);
         if (Main.tile[num6, num + 2] == null)
         {
             Main.tile[num6, num + 2] = new Tile();
         }
         Main.tile[num6, num + 2].active(active: true);
         Main.tile[num6, num + 2].type = 11;
         Main.tile[num6, num + 2].frameY = (short)(num8 + 36);
         Main.tile[num6, num + 2].frameX = num2;
         Main.tile[num6, num + 2].UseBlockColors(cache3);
         if (Main.tile[num6 + 1, num + 2] == null)
         {
             Main.tile[num6 + 1, num + 2] = new Tile();
         }
         Main.tile[num6 + 1, num + 2].active(active: true);
         Main.tile[num6 + 1, num + 2].type = 11;
         Main.tile[num6 + 1, num + 2].frameY = (short)(num8 + 36);
         Main.tile[num6 + 1, num + 2].frameX = (short)(num2 + 18);
         Main.tile[num6 + 1, num + 2].UseBlockColors(cache3);
         for (int l = num6 - 1; l <= num6 + 2; l++)
         {
             for (int m = num - 1; m <= num + 2; m++)
             {
                 TileFrame(l, m);
             }
         }
         return true;
     }
References Tile.active(), Tile.BlockColorAndCoating(), Tile.frameX, Tile.frameY, Main.netMode, SoundEngine.PlaySound(), Wiring.running, Wiring.SkipWire(), Main.tile, Main.tileCut, Tile.type, and Tile.UseBlockColors().
Referenced by NPC.AI_003_Fighters(), NPC.AI_007_TownEntities(), NPC.AI_107_ImprovedWalkers(), MessageBuffer.GetData(), Wiring.HitWireSingle(), Player.TileInteractionsUse(), and DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryOpenDoor().