Terraria: System.Xml.XmlSubtreeReader.FinishReadContentAsBinaryAsync
FinishReadContentAsBinaryAsync()
async Task< bool > System.Xml.XmlSubtreeReader.FinishReadContentAsBinaryAsync () inline private
Definition at line 1881 of file XmlSubtreeReader.cs.
    {
        byte[] bytes = new byte[256];
        if (_state == State.ReadContentAsBase64)
        {
            while (await reader.ReadContentAsBase64Async(bytes, 0, 256).ConfigureAwait(continueOnCapturedContext: false) > 0)
            {
            }
        }
        else
        {
            while (await reader.ReadContentAsBinHexAsync(bytes, 0, 256).ConfigureAwait(continueOnCapturedContext: false) > 0)
            {
            }
        }
        _state = State.Interactive;
        ProcessNamespaces();
        if (reader.Depth == _initialDepth)
        {
            _state = State.EndOfFile;
            SetEmptyNode();
            return false;
        }
        return true;
    }
References System.Xml.XmlSubtreeReader._initialDepth, System.Xml.XmlSubtreeReader._state, System.bytes, System.Xml.XmlReader.Depth, System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlReader.ReadContentAsBase64Async(), System.Xml.XmlReader.ReadContentAsBinHexAsync(), System.Xml.XmlWrappingReader.reader, and System.Xml.XmlSubtreeReader.SetEmptyNode().
Referenced by System.Xml.XmlSubtreeReader.ReadAsync(), and System.Xml.XmlSubtreeReader.SkipAsync().