Terraria: WorldGen.TryKillingTreesAboveIfTheyWouldBecomeInvalid
TryKillingTreesAboveIfTheyWouldBecomeInvalid()
static bool WorldGen.TryKillingTreesAboveIfTheyWouldBecomeInvalid (int i, int j, int newFloorType) inline static
     {
         if (newFloorType < 0 || newFloorType >= TileID.Count)
         {
             return false;
         }
         if (!InWorld(i, j, 2))
         {
             return false;
         }
         Tile tile = Main.tile[i, j - 1];
         if (tile == null || !tile.active())
         {
             return false;
         }
         int type = tile.type;
         if (!IsTreeType(tile.type) && tile.type != 323)
         {
             return false;
         }
         bool flag = true;
         flag = type switch
         {
             72 => newFloorType == 70,
             323 => TileID.Sets.Conversion.Sand[newFloorType],
             _ => TileID.Sets.Conversion.Grass[newFloorType] || TileID.Sets.Conversion.JungleGrass[newFloorType] || TileID.Sets.Conversion.Snow[newFloorType],
         };
         if (flag && GrowTreeSettings.Profiles.TryGetFromTreeId(type, out var profile))
         {
             flag = profile.GroundTest(newFloorType);
         }
         if (!flag)
         {
             KillTile(i, j - 1);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, i, j - 1);
             }
         }
         return true;
     }
References Tile.active(), TileID.Count, TileID.Sets.Conversion.Grass, TileID.Sets.Conversion.JungleGrass, Main.netMode, TileID.Sets.Conversion.Sand, NetMessage.SendData(), TileID.Sets.Conversion.Snow, Main.tile, WorldGen.GrowTreeSettings.Profiles.TryGetFromTreeId(), and Tile.type.