Terraria: WorldGen.TileFrame
TileFrame()
static void WorldGen.TileFrame (int i, int j, bool resetFrame = false, bool noBreak = false) inline static
     {
         bool addToList = false;
         try
         {
             if (i > 5 && j > 5 && i < Main.maxTilesX - 5 && j < Main.maxTilesY - 5 && Main.tile[i, j] != null)
             {
                 if (SkipFramingBecauseOfGen && !Main.tileFrameImportant[Main.tile[i, j].type])
                 {
                     return;
                 }
                 addToList = UpdateMapTile(i, j);
                 Tile tile = Main.tile[i, j];
                 if (!tile.active())
                 {
                     tile.halfBrick(halfBrick: false);
                     tile.ClearBlockPaintAndCoating();
                     tile.slope(0);
                 }
                 if (tile.liquid > 0 && Main.netMode != 1 && !noLiquidCheck)
                 {
                     Liquid.AddWater(i, j);
                 }
                 if (tile.active())
                 {
                     if (noBreak && Main.tileFrameImportant[tile.type] && tile.type != 4)
                     {
                         return;
                     }
                     int num = tile.type;
                     if (Main.tileStone[num])
                     {
                         num = 1;
                     }
                     int frameX = tile.frameX;
                     int frameY = tile.frameY;
                     Rectangle rectangle = new Rectangle(-1, -1, 0, 0);
                     if (Main.tileFrameImportant[tile.type])
                     {
                         switch (num)
{
                         case 518:
                             CheckLilyPad(i, j);
                             break;
                         case 519:
                             CheckCatTail(i, j);
                             break;
                         case 549:
                             CheckUnderwaterPlant(549, i, j);
                             break;
                         case 571:
                             CheckBamboo(i, j);
                             break;
                         case 4:
                             CheckTorch(i, j);
                             break;
                         case 442:
                             CheckProjectilePressurePad(i, j);
                             break;
                         case 136:
{
                             Tile tile2 = Main.tile[i, j - 1];
                             Tile tile3 = Main.tile[i, j + 1];
                             Tile tile4 = Main.tile[i - 1, j];
                             Tile tile5 = Main.tile[i + 1, j];
                             Tile tile6 = Main.tile[i - 1, j + 1];
                             Tile tile7 = Main.tile[i + 1, j + 1];
                             Tile tile8 = Main.tile[i - 1, j - 1];
                             Tile tile9 = Main.tile[i + 1, j - 1];
                             int num20 = -1;
                             int num21 = -1;
                             int num22 = -1;
                             int tree = -1;
                             int tree2 = -1;
                             int tree3 = -1;
                             int tree4 = -1;
                             if (tile2 != null && tile2.nactive())
{
                                 _ = tile2.type;
                             }
                             if (tile3 != null && tile3.nactive() && !tile3.halfBrick() && !tile3.topSlope())
{
                                 num20 = tile3.type;
                             }
                             if (tile4 != null && tile4.nactive())
{
                                 num21 = tile4.type;
                             }
                             if (tile5 != null && tile5.nactive())
{
                                 num22 = tile5.type;
                             }
                             if (tile6 != null && tile6.nactive())
{
                                 tree = tile6.type;
                             }
                             if (tile7 != null && tile7.nactive())
{
                                 tree2 = tile7.type;
                             }
                             if (tile8 != null && tile8.nactive())
{
                                 tree3 = tile8.type;
                             }
                             if (tile9 != null && tile9.nactive())
{
                                 tree4 = tile9.type;
                             }
                             if (num20 >= 0 && Main.tileSolid[num20] && !Main.tileNoAttach[num20] && tile3 != null && !tile3.halfBrick() && (tile3.slope() == 0 || tile3.bottomSlope()))
{
                                 tile.frameX = 0;
                             }
                             else if ((num21 >= 0 && Main.tileSolid[num21] && !Main.tileNoAttach[num21] && tile4 != null && (tile4.leftSlope() || tile4.slope() == 0) && !tile4.halfBrick()) || (num21 >= 0 && TileID.Sets.IsBeam[num21]) || (IsTreeType(num21) && IsTreeType(tree3) && IsTreeType(tree)))
{
                                 tile.frameX = 18;
                             }
                             else if ((num22 >= 0 && Main.tileSolid[num22] && !Main.tileNoAttach[num22] && tile5 != null && (tile5.rightSlope() || tile5.slope() == 0) && !tile5.halfBrick()) || (num22 >= 0 && TileID.Sets.IsBeam[num22]) || (IsTreeType(num22) && IsTreeType(tree4) && IsTreeType(tree2)))
{
                                 tile.frameX = 36;
                             }
                             else if (tile.wall > 0)
{
                                 tile.frameX = 54;
                             }
                             else
{
                                 KillTile(i, j);
                             }
                             break;
                         }
                         case 129:
                         case 149:
{
                             Tile tile2 = Main.tile[i, j - 1];
                             Tile tile3 = Main.tile[i, j + 1];
                             Tile tile4 = Main.tile[i - 1, j];
                             Tile tile5 = Main.tile[i + 1, j];
                             int num23 = -1;
                             int num24 = -1;
                             int num25 = -1;
                             int num26 = -1;
                             if (tile2 != null && tile2.nactive() && !tile2.bottomSlope())
{
                                 num24 = tile2.type;
                             }
                             if (tile3 != null && tile3.nactive() && !tile3.halfBrick() && !tile3.topSlope())
{
                                 num23 = tile3.type;
                             }
                             if (tile4 != null && tile4.nactive() && !tile5.rightSlope())
{
                                 num25 = tile4.type;
                             }
                             if (tile5 != null && tile5.nactive() && !tile5.leftSlope())
{
                                 num26 = tile5.type;
                             }
                             if (num23 >= 0 && Main.tileSolid[num23] && !Main.tileSolidTop[num23])
{
                                 tile.frameY = 0;
                             }
                             else if (num25 >= 0 && Main.tileSolid[num25] && !Main.tileSolidTop[num25])
{
                                 tile.frameY = 54;
                             }
                             else if (num26 >= 0 && Main.tileSolid[num26] && !Main.tileSolidTop[num26])
{
                                 tile.frameY = 36;
                             }
                             else if (num24 >= 0 && Main.tileSolid[num24] && !Main.tileSolidTop[num24])
{
                                 tile.frameY = 18;
                             }
                             else
{
                                 KillTile(i, j);
                             }
                             break;
                         }
                         default:
                             if (num != 461)
{
                                 switch (num)
{
                                 case 178:
{
                                     Tile tile2 = Main.tile[i, j - 1];
                                     Tile tile3 = Main.tile[i, j + 1];
                                     Tile tile4 = Main.tile[i - 1, j];
                                     Tile tile5 = Main.tile[i + 1, j];
                                     int num15 = -1;
                                     int num16 = -1;
                                     int num17 = -1;
                                     int num18 = -1;
                                     if (tile2 != null && tile2.nactive() && !tile2.bottomSlope())
{
                                         num16 = tile2.type;
                                     }
                                     if (tile3 != null && tile3.nactive() && !tile3.halfBrick() && !tile3.topSlope())
{
                                         num15 = tile3.type;
                                     }
                                     if (tile4 != null && tile4.nactive() && !tile4.halfBrick() && !tile4.rightSlope())
{
                                         num17 = tile4.type;
                                     }
                                     if (tile5 != null && tile5.nactive() && !tile5.halfBrick() && !tile5.leftSlope())
{
                                         num18 = tile5.type;
                                     }
                                     if (num17 == 10)
{
                                         num17 = -1;
                                     }
                                     if (num18 == 10)
{
                                         num18 = -1;
                                     }
                                     short num19 = (short)(genRand.Next(3) * 18);
                                     if (num15 >= 0 && Main.tileSolid[num15] && !Main.tileSolidTop[num15])
{
                                         if (tile.frameY < 0 || tile.frameY > 36)
{
                                             tile.frameY = num19;
                                         }
                                     }
                                     else if (num17 >= 0 && Main.tileSolid[num17] && !Main.tileSolidTop[num17])
{
                                         if (tile.frameY < 108 || tile.frameY > 54)
{
                                             tile.frameY = (short)(108 + num19);
                                         }
                                     }
                                     else if (num18 >= 0 && Main.tileSolid[num18] && !Main.tileSolidTop[num18])
{
                                         if (tile.frameY < 162 || tile.frameY > 198)
{
                                             tile.frameY = (short)(162 + num19);
                                         }
                                     }
                                     else if (num16 >= 0 && Main.tileSolid[num16] && !Main.tileSolidTop[num16])
{
                                         if (tile.frameY < 54 || tile.frameY > 90)
{
                                             tile.frameY = (short)(54 + num19);
                                         }
                                     }
                                     else
{
                                         KillTile(i, j);
                                     }
                                     break;
                                 }
                                 case 184:
{
                                     Tile tile2 = Main.tile[i, j - 1];
                                     Tile tile3 = Main.tile[i, j + 1];
                                     Tile tile4 = Main.tile[i - 1, j];
                                     Tile tile5 = Main.tile[i + 1, j];
                                     int num10 = -1;
                                     int num11 = -1;
                                     int num12 = -1;
                                     int num13 = -1;
                                     if (tile2 != null && tile2.active() && !tile2.bottomSlope())
{
                                         num11 = tile2.type;
                                     }
                                     if (tile3 != null && tile3.active() && !tile3.halfBrick() && !tile3.topSlope())
{
                                         num10 = tile3.type;
                                     }
                                     if (tile4 != null && tile4.active())
{
                                         num12 = tile4.type;
                                     }
                                     if (tile5 != null && tile5.active())
{
                                         num13 = tile5.type;
                                     }
                                     short num14 = (short)(genRand.Next(3) * 18);
                                     if (num10 >= 0 && GetTileMossColor(num10) != -1)
{
                                         tile.frameX = (short)(22 * GetTileMossColor(num10));
                                         if (tile.frameY < 0 || tile.frameY > 36)
{
                                             tile.frameY = num14;
                                         }
                                     }
                                     else if (num11 >= 0 && GetTileMossColor(num11) != -1)
{
                                         tile.frameX = (short)(22 * GetTileMossColor(num11));
                                         if (tile.frameY < 54 || tile.frameY > 90)
{
                                             tile.frameY = (short)(54 + num14);
                                         }
                                     }
                                     else if (num12 >= 0 && GetTileMossColor(num12) != -1)
{
                                         tile.frameX = (short)(22 * GetTileMossColor(num12));
                                         if (tile.frameY < 108 || tile.frameY > 144)
{
                                             tile.frameY = (short)(108 + num14);
                                         }
                                     }
                                     else if (num13 >= 0 && GetTileMossColor(num13) != -1)
{
                                         tile.frameX = (short)(22 * GetTileMossColor(num13));
                                         if (tile.frameY < 162 || tile.frameY > 198)
{
                                             tile.frameY = (short)(162 + num14);
                                         }
                                     }
                                     else
{
                                         KillTile(i, j);
                                     }
                                     break;
                                 }
                                 case 529:
{
                                     if (!SolidTileAllowBottomSlope(i, j + 1))
{
                                         KillTile(i, j);
                                         break;
                                     }
                                     Tile tile3 = Main.tile[i, j + 1];
                                     _ = Main.tile[i, j].frameY / 34;
                                     if (tile3 == null || !tile3.active() || (tile3.type >= 0 && tile3.type < TileID.Count && !TileID.Sets.Conversion.Sand[tile3.type]))
{
                                         KillTile(i, j);
                                     }
                                     break;
                                 }
                                 case 3:
                                 case 24:
                                 case 61:
                                 case 71:
                                 case 73:
                                 case 74:
                                 case 110:
                                 case 113:
                                 case 201:
                                 case 637:
                                     PlantCheck(i, j);
                                     break;
                                 case 227:
                                     CheckDye(i, j);
                                     break;
                                 case 579:
                                     CheckRockGolemHead(i, j);
                                     break;
                                 case 12:
                                 case 31:
                                 case 639:
                                     CheckOrb(i, j, num);
                                     break;
                                 case 165:
                                     CheckTight(i, j);
                                     break;
                                 case 324:
                                     if (!SolidTileAllowBottomSlope(i, j + 1))
{
                                         KillTile(i, j);
                                     }
                                     break;
                                 case 235:
                                     Check3x1(i, j, num);
                                     break;
                                 case 185:
                                     CheckPile(i, j);
                                     break;
                                 default:
                                     if (num != 296 && num != 297 && num != 309 && num != 358 && num != 359 && num != 413 && num != 414 && num != 542 && num != 550 && num != 551 && num != 553 && num != 554 && num != 558 && num != 559 && num != 599 && num != 600 && num != 601 && num != 602 && num != 603 && num != 604 && num != 605 && num != 606 && num != 607 && num != 608 && num != 609 && num != 610 && num != 611 && num != 612 && num != 632 && num != 640 && num != 643 && num != 644 && num != 645)
{
                                         if (num == 10)
{
                                             CheckDoorClosed(i, j, tile, num);
                                             break;
                                         }
                                         if (num == 11)
{
                                             CheckDoorOpen(i, j, tile);
                                             break;
                                         }
                                         if (num == 314)
{
                                             Minecart.FrameTrack(i, j, pound: false);
                                             Tile tile2 = Main.tile[i, j - 1];
                                             Tile tile3 = Main.tile[i, j + 1];
                                             if (tile2 != null && tile2.type >= 0 && tile2.type < TileID.Count && Main.tileRope[tile2.type])
{
                                                 TileFrame(i, j - 1);
                                             }
                                             if (tile3 != null && tile3.type >= 0 && tile3.type < TileID.Count && Main.tileRope[tile3.type])
{
                                                 TileFrame(i, j + 1);
                                             }
                                             break;
                                         }
                                         if (num == 380)
{
                                             Tile tile4 = Main.tile[i - 1, j];
                                             if (tile4 == null)
{
                                                 break;
                                             }
                                             Tile tile5 = Main.tile[i + 1, j];
                                             if (tile5 == null)
{
                                                 break;
                                             }
                                             Tile tile6 = Main.tile[i - 1, j + 1];
                                             if (tile6 == null)
{
                                                 break;
                                             }
                                             Tile tile7 = Main.tile[i + 1, j + 1];
                                             if (tile7 == null)
{
                                                 break;
                                             }
                                             Tile tile8 = Main.tile[i - 1, j - 1];
                                             if (tile8 == null)
{
                                                 break;
                                             }
                                             Tile tile9 = Main.tile[i + 1, j - 1];
                                             if (tile9 != null)
{
                                                 int num2 = -1;
                                                 int num3 = -1;
                                                 if (tile4 != null && tile4.active())
{
                                                     num3 = (Main.tileStone[tile4.type] ? 1 : tile4.type);
                                                 }
                                                 if (tile5 != null && tile5.active())
{
                                                     num2 = (Main.tileStone[tile5.type] ? 1 : tile5.type);
                                                 }
                                                 if (num2 >= 0 && !Main.tileSolid[num2])
{
                                                     num2 = -1;
                                                 }
                                                 if (num3 >= 0 && !Main.tileSolid[num3])
{
                                                     num3 = -1;
                                                 }
                                                 if (num3 == num && num2 == num)
{
                                                     rectangle.X = 18;
                                                 }
                                                 else if (num3 == num && num2 != num)
{
                                                     rectangle.X = 36;
                                                 }
                                                 else if (num3 != num && num2 == num)
{
                                                     rectangle.X = 0;
                                                 }
                                                 else
{
                                                     rectangle.X = 54;
                                                 }
                                                 tile.frameX = (short)rectangle.X;
                                             }
                                             break;
                                         }
                                         if (num >= 0 && TileID.Sets.Platforms[num])
{
                                             Tile tile4 = Main.tile[i - 1, j];
                                             if (tile4 == null)
{
                                                 break;
                                             }
                                             Tile tile5 = Main.tile[i + 1, j];
                                             if (tile5 == null)
{
                                                 break;
                                             }
                                             Tile tile6 = Main.tile[i - 1, j + 1];
                                             if (tile6 == null)
{
                                                 break;
                                             }
                                             Tile tile7 = Main.tile[i + 1, j + 1];
                                             if (tile7 == null)
{
                                                 break;
                                             }
                                             Tile tile8 = Main.tile[i - 1, j - 1];
                                             if (tile8 == null)
{
                                                 break;
                                             }
                                             Tile tile9 = Main.tile[i + 1, j - 1];
                                             if (tile9 == null)
{
                                                 break;
                                             }
                                             int num4 = -1;
                                             int num5 = -1;
                                             if (tile4 != null && tile4.active())
{
                                                 num5 = (Main.tileStone[tile4.type] ? 1 : ((!TileID.Sets.Platforms[tile4.type]) ? tile4.type : num));
                                             }
                                             if (tile5 != null && tile5.active())
{
                                                 num4 = (Main.tileStone[tile5.type] ? 1 : ((!TileID.Sets.Platforms[tile5.type]) ? tile5.type : num));
                                             }
                                             if (num4 >= 0 && !Main.tileSolid[num4])
{
                                                 num4 = -1;
                                             }
                                             if (num5 >= 0 && !Main.tileSolid[num5])
{
                                                 num5 = -1;
                                             }
                                             if (num5 == num && tile4.halfBrick() != tile.halfBrick())
{
                                                 num5 = -1;
                                             }
                                             if (num4 == num && tile5.halfBrick() != tile.halfBrick())
{
                                                 num4 = -1;
                                             }
                                             if (num5 != -1 && num5 != num && tile.halfBrick())
{
                                                 num5 = -1;
                                             }
                                             if (num4 != -1 && num4 != num && tile.halfBrick())
{
                                                 num4 = -1;
                                             }
                                             if (num5 == -1 && tile8.active() && tile8.type == num && tile8.slope() == 1)
{
                                                 num5 = num;
                                             }
                                             if (num4 == -1 && tile9.active() && tile9.type == num && tile9.slope() == 2)
{
                                                 num4 = num;
                                             }
                                             if (num5 == num && tile4.slope() == 2 && num4 != num)
{
                                                 num4 = -1;
                                             }
                                             if (num4 == num && tile5.slope() == 1 && num5 != num)
{
                                                 num5 = -1;
                                             }
                                             if (tile.slope() == 1)
{
                                                 if (TileID.Sets.Platforms[tile5.type] && tile5.slope() == 0 && !tile5.halfBrick())
{
                                                     rectangle.X = 468;
                                                 }
                                                 else if (!tile7.active() && (!TileID.Sets.Platforms[tile7.type] || tile7.slope() == 2))
{
                                                     if (!tile4.active() && (!TileID.Sets.Platforms[tile8.type] || tile8.slope() != 1))
{
                                                         rectangle.X = 432;
                                                     }
                                                     else
{
                                                         rectangle.X = 360;
                                                     }
                                                 }
                                                 else if (!tile4.active() && (!TileID.Sets.Platforms[tile8.type] || tile8.slope() != 1))
{
                                                     rectangle.X = 396;
                                                 }
                                                 else
{
                                                     rectangle.X = 180;
                                                 }
                                             }
                                             else if (tile.slope() == 2)
{
                                                 if (TileID.Sets.Platforms[tile4.type] && tile4.slope() == 0 && !tile4.halfBrick())
{
                                                     rectangle.X = 450;
                                                 }
                                                 else if (!tile6.active() && (!TileID.Sets.Platforms[tile6.type] || tile6.slope() == 1))
{
                                                     if (!tile5.active() && (!TileID.Sets.Platforms[tile9.type] || tile9.slope() != 2))
{
                                                         rectangle.X = 414;
                                                     }
                                                     else
{
                                                         rectangle.X = 342;
                                                     }
                                                 }
                                                 else if (!tile5.active() && (!TileID.Sets.Platforms[tile9.type] || tile9.slope() != 2))
{
                                                     rectangle.X = 378;
                                                 }
                                                 else
{
                                                     rectangle.X = 144;
                                                 }
                                             }
                                             else if (num5 == num && num4 == num)
{
                                                 if (tile4.slope() == 2 && tile5.slope() == 1)
{
                                                     rectangle.X = 252;
                                                 }
                                                 else if (tile4.slope() == 2)
{
                                                     rectangle.X = 216;
                                                 }
                                                 else if (tile5.slope() == 1)
{
                                                     rectangle.X = 234;
                                                 }
                                                 else
{
                                                     rectangle.X = 0;
                                                 }
                                             }
                                             else if (num5 == num && num4 == -1)
{
                                                 if (tile4.slope() == 2)
{
                                                     rectangle.X = 270;
                                                 }
                                                 else
{
                                                     rectangle.X = 18;
                                                 }
                                             }
                                             else if (num5 == -1 && num4 == num)
{
                                                 if (tile5.slope() == 1)
{
                                                     rectangle.X = 288;
                                                 }
                                                 else
{
                                                     rectangle.X = 36;
                                                 }
                                             }
                                             else if (num5 != num && num4 == num)
{
                                                 rectangle.X = 54;
                                             }
                                             else if (num5 == num && num4 != num)
{
                                                 rectangle.X = 72;
                                             }
                                             else if (num5 != num && num5 != -1 && num4 == -1)
{
                                                 rectangle.X = 108;
                                             }
                                             else if (num5 == -1 && num4 != num && num4 != -1)
{
                                                 rectangle.X = 126;
                                             }
                                             else
{
                                                 rectangle.X = 90;
                                             }
                                             tile.frameX = (short)rectangle.X;
                                             if (Main.tile[i, j - 1] != null && Main.tileRope[Main.tile[i, j - 1].type])
{
                                                 TileFrame(i, j - 1);
                                             }
                                             if (Main.tile[i, j + 1] != null && Main.tileRope[Main.tile[i, j + 1].type])
{
                                                 TileFrame(i, j + 1);
                                             }
                                             break;
                                         }
                                         switch (num)
{
                                         case 233:
                                         case 236:
                                         case 238:
                                             CheckJunglePlant(i, j, num);
                                             break;
                                         case 530:
                                             CheckOasisPlant(i, j);
                                             break;
                                         case 240:
                                         case 440:
                                             Check3x3Wall(i, j);
                                             break;
                                         case 245:
                                             Check2x3Wall(i, j);
                                             break;
                                         case 246:
                                             Check3x2Wall(i, j);
                                             break;
                                         case 241:
                                             Check4x3Wall(i, j);
                                             break;
                                         case 242:
                                             Check6x4Wall(i, j);
                                             break;
                                         case 464:
                                         case 466:
                                             Check5x4(i, j, num);
                                             break;
                                         case 334:
                                             CheckWeaponsRack(i, j);
                                             break;
                                         case 471:
                                             TEWeaponsRack.Framing_CheckTile(i, j);
                                             break;
                                         case 34:
                                         case 454:
                                             CheckChand(i, j, num);
                                             break;
                                         case 547:
                                         case 623:
                                             Check2x5(i, j, num);
                                             break;
                                         case 548:
                                         case 614:
                                             Check3x6(i, j, num);
                                             break;
                                         case 613:
                                             Check3x5(i, j, num);
                                             break;
                                         default:
                                             if (num != 354 && num != 406 && num != 412 && num != 355 && num != 452 && num != 455 && num != 491 && num != 499 && num != 642)
{
                                                 switch (num)
{
                                                 case 15:
                                                 case 20:
                                                 case 216:
                                                 case 338:
                                                 case 390:
                                                 case 493:
                                                 case 497:
                                                 case 590:
                                                 case 595:
                                                 case 615:
                                                     Check1x2(i, j, (ushort)num);
                                                     break;
                                                 default:
                                                     if (num < 391 || num > 394)
{
                                                         switch (num)
{
                                                         case 405:
                                                         case 486:
                                                         case 488:
                                                         case 532:
                                                         case 533:
                                                         case 544:
                                                         case 552:
                                                         case 555:
                                                         case 556:
                                                         case 582:
                                                         case 619:
                                                         case 629:
                                                         case 647:
                                                         case 648:
                                                         case 651:
                                                             break;
                                                         case 36:
                                                         case 135:
                                                         case 141:
                                                         case 144:
                                                         case 210:
                                                         case 239:
                                                         case 428:
                                                         case 593:
                                                         case 624:
                                                         case 650:
                                                         case 656:
                                                             Check1x1(i, j, num);
                                                             return;
                                                         case 476:
                                                             CheckGolf1x1(i, j, num);
                                                             return;
                                                         case 494:
                                                             CheckGolf1x1(i, j, num);
                                                             return;
                                                         case 419:
                                                         case 420:
                                                         case 423:
                                                         case 424:
                                                         case 429:
                                                         case 445:
                                                             CheckLogicTiles(i, j, num);
                                                             return;
                                                         case 16:
                                                         case 18:
                                                         case 29:
                                                         case 103:
                                                         case 134:
                                                         case 462:
                                                         case 649:
                                                             Check2x1(i, j, (ushort)num);
                                                             return;
                                                         case 13:
                                                         case 33:
                                                         case 49:
                                                         case 50:
                                                         case 78:
                                                         case 174:
                                                         case 372:
                                                         case 646:
                                                             CheckOnTable1x1(i, j, num);
                                                             return;
                                                         default:
                                                             if (TileID.Sets.BasicChest[num])
{
                                                                 CheckChest(i, j, num);
                                                                 return;
                                                             }
                                                             switch (num)
{
                                                             case 128:
                                                                 CheckMan(i, j);
                                                                 break;
                                                             case 269:
                                                                 CheckWoman(i, j);
                                                                 break;
                                                             case 470:
                                                                 TEDisplayDoll.Framing_CheckTile(i, j);
                                                                 break;
                                                             case 475:
                                                                 TEHatRack.Framing_CheckTile(i, j);
                                                                 break;
                                                             case 597:
                                                                 TETeleportationPylon.Framing_CheckTile(i, j);
                                                                 break;
                                                             case 27:
                                                                 CheckSunflower(i, j);
                                                                 break;
                                                             case 28:
                                                             case 653:
                                                                 CheckPot(i, j, num);
                                                                 break;
                                                             case 171:
                                                                 CheckXmasTree(i, j);
                                                                 break;
                                                             default:
                                                                 if (!TileID.Sets.BasicChestFake[num] && num != 457)
{
                                                                     switch (num)
{
                                                                     case 335:
                                                                     case 411:
                                                                     case 490:
                                                                     case 564:
                                                                     case 565:
                                                                     case 594:
                                                                         Check2x2(i, j, num);
                                                                         break;
                                                                     default:
                                                                         if (num < 316 || num > 318)
{
                                                                             switch (num)
{
                                                                             case 172:
                                                                             case 360:
                                                                             case 505:
                                                                             case 521:
                                                                             case 522:
                                                                             case 523:
                                                                             case 524:
                                                                             case 525:
                                                                             case 526:
                                                                             case 527:
                                                                             case 543:
                                                                             case 568:
                                                                             case 569:
                                                                             case 570:
                                                                             case 580:
                                                                             case 598:
                                                                             case 620:
                                                                             case 652:
                                                                             case 654:
                                                                                 break;
                                                                             case 376:
                                                                             case 443:
                                                                             case 444:
                                                                             case 485:
                                                                                 CheckSuper(i, j, num);
                                                                                 return;
                                                                             case 91:
                                                                                 CheckBanner(i, j, (byte)num);
                                                                                 return;
                                                                             case 35:
                                                                             case 139:
                                                                                 CheckMB(i, j, (byte)num);
                                                                                 return;
                                                                             case 386:
                                                                             case 387:
                                                                                 CheckTrapDoor(i, j, num);
                                                                                 return;
                                                                             case 388:
                                                                             case 389:
                                                                                 CheckTallGate(i, j, num);
                                                                                 return;
                                                                             case 92:
                                                                             case 93:
                                                                             case 453:
                                                                                 Check1xX(i, j, (short)num);
                                                                                 return;
                                                                             case 104:
                                                                             case 105:
                                                                             case 207:
                                                                             case 320:
                                                                             case 337:
                                                                             case 349:
                                                                             case 356:
                                                                             case 378:
                                                                             case 410:
                                                                             case 456:
                                                                             case 465:
                                                                             case 480:
                                                                             case 489:
                                                                             case 506:
                                                                             case 509:
                                                                             case 531:
                                                                             case 545:
                                                                             case 560:
                                                                             case 591:
                                                                             case 592:
                                                                             case 657:
                                                                             case 658:
                                                                             case 663:
                                                                                 Check2xX(i, j, (ushort)num);
                                                                                 return;
                                                                             case 101:
                                                                             case 102:
                                                                             case 463:
                                                                             case 617:
                                                                                 Check3x4(i, j, num);
                                                                                 return;
                                                                             case 42:
                                                                             case 270:
                                                                             case 271:
                                                                             case 572:
                                                                             case 581:
                                                                             case 660:
                                                                                 Check1x2Top(i, j, (ushort)num);
                                                                                 return;
                                                                             case 55:
                                                                             case 85:
                                                                             case 395:
                                                                             case 425:
                                                                             case 510:
                                                                             case 511:
                                                                             case 573:
                                                                                 CheckSign(i, j, (ushort)num);
                                                                                 return;
                                                                             case 520:
                                                                                 CheckFoodPlatter(i, j, (ushort)num);
                                                                                 return;
                                                                             case 209:
                                                                                 CheckCannon(i, j, num);
                                                                                 return;
                                                                             case 79:
                                                                             case 90:
                                                                             case 487:
                                                                                 Check4x2(i, j, num);
                                                                                 return;
                                                                             case 94:
                                                                             case 95:
                                                                             case 97:
                                                                             case 98:
                                                                             case 99:
                                                                             case 100:
                                                                             case 125:
                                                                             case 126:
                                                                             case 173:
                                                                             case 282:
                                                                             case 287:
                                                                             case 319:
                                                                             case 621:
                                                                             case 622:
                                                                                 Check2x2(i, j, num);
                                                                                 return;
                                                                             case 96:
                                                                                 Check2x2Style(i, j, num);
                                                                                 return;
                                                                             case 81:
{
                                                                                 Tile tile2 = Main.tile[i, j - 1];
                                                                                 Tile tile3 = Main.tile[i, j + 1];
                                                                                 Tile tile4 = Main.tile[i - 1, j];
                                                                                 Tile tile5 = Main.tile[i + 1, j];
                                                                                 int num8 = -1;
                                                                                 int num9 = -1;
                                                                                 if (tile2 != null && tile2.active())
{
                                                                                     num9 = tile2.type;
                                                                                 }
                                                                                 if (tile3 != null && tile3.active())
{
                                                                                     num8 = tile3.type;
                                                                                 }
                                                                                 if (num9 != -1)
{
                                                                                     KillTile(i, j);
                                                                                 }
                                                                                 else if (num8 < 0 || !Main.tileSolid[num8] || (tile3 != null && (tile3.halfBrick() || tile3.topSlope())))
{
                                                                                     KillTile(i, j);
                                                                                 }
                                                                                 return;
                                                                             }
                                                                             default:
                                                                                 if (Main.tileAlch[num])
{
                                                                                     CheckAlch(i, j);
                                                                                     return;
                                                                                 }
                                                                                 switch (num)
{
                                                                                 case 72:
{
                                                                                     Tile tile2 = Main.tile[i, j - 1];
                                                                                     Tile tile3 = Main.tile[i, j + 1];
                                                                                     int num6 = -1;
                                                                                     int num7 = -1;
                                                                                     if (tile2 != null && tile2.active())
{
                                                                                         num7 = tile2.type;
                                                                                     }
                                                                                     if (tile3 != null && tile3.active())
{
                                                                                         num6 = tile3.type;
                                                                                     }
                                                                                     if (num6 != num && num6 != 70)
{
                                                                                         KillTile(i, j);
                                                                                     }
                                                                                     else if (num7 != num && tile.frameX == 0)
{
                                                                                         tile.frameNumber((byte)genRand.Next(3));
                                                                                         if (tile.frameNumber() == 0)
{
                                                                                             tile.frameX = 18;
                                                                                             tile.frameY = 0;
                                                                                         }
                                                                                         if (tile.frameNumber() == 1)
{
                                                                                             tile.frameX = 18;
                                                                                             tile.frameY = 18;
                                                                                         }
                                                                                         if (tile.frameNumber() == 2)
{
                                                                                             tile.frameX = 18;
                                                                                             tile.frameY = 36;
                                                                                         }
                                                                                     }
                                                                                     break;
                                                                                 }
                                                                                 case 5:
                                                                                     CheckTree(i, j);
                                                                                     break;
                                                                                 case 583:
                                                                                 case 584:
                                                                                 case 585:
                                                                                 case 586:
                                                                                 case 587:
                                                                                 case 588:
                                                                                 case 589:
                                                                                     CheckTreeWithSettings(i, j, new CheckTreeSettings
{
                                                                                         IsGroundValid = GemTreeGroundTest
                                                                                     });
                                                                                     break;
                                                                                 case 596:
                                                                                     CheckTreeWithSettings(i, j, new CheckTreeSettings
{
                                                                                         IsGroundValid = VanityTreeGroundTest
                                                                                     });
                                                                                     break;
                                                                                 case 616:
                                                                                     CheckTreeWithSettings(i, j, new CheckTreeSettings
{
                                                                                         IsGroundValid = VanityTreeGroundTest
                                                                                     });
                                                                                     break;
                                                                                 case 634:
                                                                                     CheckTreeWithSettings(i, j, new CheckTreeSettings
{
                                                                                         IsGroundValid = AshTreeGroundTest
                                                                                     });
                                                                                     break;
                                                                                 case 323:
                                                                                     CheckPalmTree(i, j);
                                                                                     break;
                                                                                 case 567:
                                                                                     CheckGnome(i, j);
                                                                                     break;
                                                                                 case 630:
                                                                                 case 631:
                                                                                     CheckStinkbugBlocker(i, j);
                                                                                     break;
                                                                                 }
                                                                                 return;
                                                                             }
                                                                         }
                                                                         goto case 132;
                                                                     case 132:
                                                                     case 138:
                                                                     case 142:
                                                                     case 143:
                                                                     case 288:
                                                                     case 289:
                                                                     case 290:
                                                                     case 291:
                                                                     case 292:
                                                                     case 293:
                                                                     case 294:
                                                                     case 295:
                                                                     case 484:
                                                                     case 664:
                                                                     case 665:
                                                                         Check2x2(i, j, num);
                                                                         break;
                                                                     }
                                                                     break;
                                                                 }
                                                                 goto case 254;
                                                             case 254:
                                                                 Check2x2Style(i, j, num);
                                                                 break;
                                                             }
                                                             return;
                                                         }
                                                     }
                                                     goto case 14;
                                                 case 14:
                                                 case 17:
                                                 case 26:
                                                 case 77:
                                                 case 86:
                                                 case 87:
                                                 case 88:
                                                 case 89:
                                                 case 114:
                                                 case 133:
                                                 case 186:
                                                 case 187:
                                                 case 215:
                                                 case 217:
                                                 case 218:
                                                 case 237:
                                                 case 244:
                                                 case 285:
                                                 case 286:
                                                 case 298:
                                                 case 299:
                                                 case 310:
                                                 case 339:
                                                 case 361:
                                                 case 362:
                                                 case 363:
                                                 case 364:
                                                 case 377:
                                                 case 469:
                                                 case 538:
                                                     Check3x2(i, j, (ushort)num);
                                                     break;
                                                 }
                                                 break;
                                             }
                                             goto case 106;
                                         case 106:
                                         case 212:
                                         case 219:
                                         case 220:
                                         case 228:
                                         case 231:
                                         case 243:
                                         case 247:
                                         case 283:
                                         case 300:
                                         case 301:
                                         case 302:
                                         case 303:
                                         case 304:
                                         case 305:
                                         case 306:
                                         case 307:
                                         case 308:
                                             Check3x3(i, j, (ushort)num);
                                             break;
                                         }
                                         break;
                                     }
                                     goto case 275;
                                 case 275:
                                 case 276:
                                 case 277:
                                 case 278:
                                 case 279:
                                 case 280:
                                 case 281:
                                     Check6x3(i, j, num);
                                     break;
                                 }
                                 break;
                             }
                             goto case 373;
                         case 373:
                         case 374:
                         case 375:
{
                             Tile tile2 = Main.tile[i, j - 1];
                             if (tile2 == null || !tile2.active() || tile2.bottomSlope() || !Main.tileSolid[tile2.type] || Main.tileSolidTop[tile2.type])
{
                                 KillTile(i, j);
                             }
                             break;
                         }
                         }
                         return;
                     }
                     if (num < 255 || num > 268)
                     {
                         switch (num)
{
                         case 385:
                         case 446:
                         case 447:
                         case 448:
                             break;
                         default:
{
                             Tile tile2 = Main.tile[i, j - 1];
                             Tile tile3 = Main.tile[i, j + 1];
                             Tile tile4 = Main.tile[i - 1, j];
                             Tile tile5 = Main.tile[i + 1, j];
                             Tile tile6 = Main.tile[i - 1, j + 1];
                             Tile tile7 = Main.tile[i + 1, j + 1];
                             Tile tile8 = Main.tile[i - 1, j - 1];
                             Tile tile9 = Main.tile[i + 1, j - 1];
                             int upLeft = -1;
                             int up = -1;
                             int upRight = -1;
                             int left = -1;
                             int right = -1;
                             int downLeft = -1;
                             int down = -1;
                             int downRight = -1;
                             if (tile4 != null && tile4.active())
{
                                 left = (Main.tileStone[tile4.type] ? 1 : tile4.type);
                                 if (tile4.slope() == 1 || tile4.slope() == 3)
{
                                     left = -1;
                                 }
                             }
                             if (tile5 != null && tile5.active())
{
                                 right = (Main.tileStone[tile5.type] ? 1 : tile5.type);
                                 if (tile5.slope() == 2 || tile5.slope() == 4)
{
                                     right = -1;
                                 }
                             }
                             if (tile2 != null && tile2.active())
{
                                 up = (Main.tileStone[tile2.type] ? 1 : tile2.type);
                                 if (tile2.slope() == 3 || tile2.slope() == 4)
{
                                     up = -1;
                                 }
                             }
                             if (tile3 != null && tile3.active())
{
                                 down = (Main.tileStone[tile3.type] ? 1 : tile3.type);
                                 if (tile3.slope() == 1 || tile3.slope() == 2)
{
                                     down = -1;
                                 }
                             }
                             if (tile8 != null && tile8.active())
{
                                 upLeft = (Main.tileStone[tile8.type] ? 1 : tile8.type);
                             }
                             if (tile9 != null && tile9.active())
{
                                 upRight = (Main.tileStone[tile9.type] ? 1 : tile9.type);
                             }
                             if (tile6 != null && tile6.active())
{
                                 downLeft = (Main.tileStone[tile6.type] ? 1 : tile6.type);
                             }
                             if (tile7 != null && tile7.active())
{
                                 downRight = (Main.tileStone[tile7.type] ? 1 : tile7.type);
                             }
                             if (tile.slope() == 2)
{
                                 up = -1;
                                 left = -1;
                             }
                             if (tile.slope() == 1)
{
                                 up = -1;
                                 right = -1;
                             }
                             if (tile.slope() == 4)
{
                                 down = -1;
                                 left = -1;
                             }
                             if (tile.slope() == 3)
{
                                 down = -1;
                                 right = -1;
                             }
                             if (num == 668)
{
                                 num = 0;
                             }
                             TileMergeAttempt(0, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             switch (num)
{
                             case 147:
                                 TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Ices, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 break;
                             case 161:
                             case 163:
                             case 164:
                             case 200:
                                 TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Snow, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 break;
                             case 162:
                                 TileMergeAttempt(num, Main.tileBrick, TileID.Sets.IcesSnow, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 break;
                             default:
                                 if (Main.tileBrick[num])
{
                                     switch (num)
{
                                     case 60:
                                     case 70:
                                     case 661:
                                     case 662:
                                         TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                         break;
                                     case 633:
                                         TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Ash, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                         break;
                                     default:
                                         TileMergeAttempt(num, Main.tileBrick, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                         break;
                                     }
                                 }
                                 else if (Main.tilePile[num])
{
                                     TileMergeAttempt(num, Main.tilePile, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 }
                                 break;
                             }
                             if ((num == 1 || Main.tileMoss[num] || num == 117 || num == 25 || num == 203) && down == 165)
{
                                 if (tile3 != null && tile3.frameY == 72)
{
                                     down = num;
                                 }
                                 else if (tile3 != null && tile3.frameY == 0)
{
                                     down = num;
                                 }
                             }
                             if ((num == 1 || Main.tileMoss[num] || num == 117 || num == 25 || num == 203) && up == 165)
{
                                 if (tile2 != null && tile2.frameY == 90)
{
                                     up = num;
                                 }
                                 else if (tile2 != null && tile2.frameY == 54)
{
                                     up = num;
                                 }
                             }
                             if (num == 225)
{
                                 if (down == 165)
{
                                     down = num;
                                 }
                                 if (up == 165)
{
                                     up = num;
                                 }
                             }
                             if ((num == 200 || num == 161 || num == 147 || num == 163 || num == 164) && down == 165)
{
                                 down = num;
                             }
                             if ((tile.slope() == 1 || tile.slope() == 2) && down > -1 && !TileID.Sets.Platforms[down])
{
                                 down = num;
                             }
                             if (up > -1 && tile2 != null && (tile2.slope() == 1 || tile2.slope() == 2) && !TileID.Sets.Platforms[up])
{
                                 up = num;
                             }
                             if ((tile.slope() == 3 || tile.slope() == 4) && up > -1 && !TileID.Sets.Platforms[up])
{
                                 up = num;
                             }
                             if (down > -1 && tile3 != null && (tile3.slope() == 3 || tile3.slope() == 4) && !TileID.Sets.Platforms[down])
{
                                 down = num;
                             }
                             if (num == 124)
{
                                 if (up > -1 && Main.tileSolid[up] && !TileID.Sets.Platforms[up])
{
                                     up = num;
                                 }
                                 if (down > -1 && Main.tileSolid[down] && !TileID.Sets.Platforms[down])
{
                                     down = num;
                                 }
                             }
                             if (up > -1 && tile2 != null && tile2.halfBrick() && !TileID.Sets.Platforms[up])
{
                                 up = num;
                             }
                             if (left > -1 && tile4 != null && tile4.halfBrick())
{
                                 if (tile.halfBrick())
{
                                     left = num;
                                 }
                                 else if (tile4.type != num)
{
                                     left = -1;
                                 }
                             }
                             if (right > -1 && tile5 != null && tile5.halfBrick())
{
                                 if (tile.halfBrick())
{
                                     right = num;
                                 }
                                 else if (tile5.type != num)
{
                                     right = -1;
                                 }
                             }
                             if (tile.halfBrick())
{
                                 if (left != num)
{
                                     left = -1;
                                 }
                                 if (right != num)
{
                                     right = -1;
                                 }
                                 up = -1;
                             }
                             if (tile3 != null && tile3.halfBrick())
{
                                 down = -1;
                             }
                             if (!Main.tileSolid[num])
{
                                 switch (num)
{
                                 case 49:
                                     CheckOnTable1x1(i, j, (byte)num);
                                     return;
                                 case 80:
                                     CactusFrame(i, j);
                                     return;
                                 }
                             }
                             mergeUp = false;
                             mergeDown = false;
                             mergeLeft = false;
                             mergeRight = false;
                             int num27 = 0;
                             if (resetFrame)
{
                                 num27 = genRand.Next(0, 3);
                                 tile.frameNumber((byte)num27);
                             }
                             else
{
                                 num27 = tile.frameNumber();
                             }
                             if (Main.tileLargeFrames[num] == 1)
{
                                 int num28 = j % 4;
                                 int num29 = i % 3;
                                 num27 = (new int[4, 3]
{
                                     { 2, 4, 2 },
                                     { 1, 3, 1 },
                                     { 2, 2, 4 },
                                     { 1, 1, 3 }
                                 })[num28, num29] - 1;
                             }
                             if (Main.tileLargeFrames[num] == 2)
{
                                 int num30 = i % 2;
                                 int num31 = j % 2;
                                 num27 = num30 + num31 * 2;
                             }
                             if (!Main.tileRope[num] && TileID.Sets.BlockMergesWithMergeAllBlock[num])
{
                                 TileMergeAttempt(num, Main.tileBlendAll, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             if (Main.tileBlendAll[num])
{
                                 TileMergeAttempt(num, TileID.Sets.BlockMergesWithMergeAllBlock, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             if (TileID.Sets.ForcedDirtMerging[num])
{
                                 TileMergeAttempt(num, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             if (TileID.Sets.Dirt[num])
{
                                 if (up > -1 && Main.tileMergeDirt[up])
{
                                     TileFrame(i, j - 1);
                                     if (mergeDown)
{
                                         up = num;
                                     }
                                 }
                                 else if (up == 147)
{
                                     TileFrame(i, j - 1);
                                     if (mergeDown)
{
                                         up = num;
                                     }
                                 }
                                 if (down > -1 && Main.tileMergeDirt[down])
{
                                     TileFrame(i, j + 1);
                                     if (mergeUp)
{
                                         down = num;
                                     }
                                 }
                                 else if (down == 147)
{
                                     TileFrame(i, j + 1);
                                     if (mergeUp)
{
                                         down = num;
                                     }
                                 }
                                 if (left > -1 && Main.tileMergeDirt[left])
{
                                     TileFrame(i - 1, j);
                                     if (mergeRight)
{
                                         left = num;
                                     }
                                 }
                                 else if (left == 147)
{
                                     TileFrame(i - 1, j);
                                     if (mergeRight)
{
                                         left = num;
                                     }
                                 }
                                 if (right > -1 && Main.tileMergeDirt[right])
{
                                     TileFrame(i + 1, j);
                                     if (mergeLeft)
{
                                         right = num;
                                     }
                                 }
                                 else if (right == 147)
{
                                     TileFrame(i + 1, j);
                                     if (mergeLeft)
{
                                         right = num;
                                     }
                                 }
                                 bool[] mergesWithDirtInASpecialWay = TileID.Sets.Conversion.MergesWithDirtInASpecialWay;
                                 if (up > -1 && mergesWithDirtInASpecialWay[up])
{
                                     up = num;
                                 }
                                 if (down > -1 && mergesWithDirtInASpecialWay[down])
{
                                     down = num;
                                 }
                                 if (left > -1 && mergesWithDirtInASpecialWay[left])
{
                                     left = num;
                                 }
                                 if (right > -1 && mergesWithDirtInASpecialWay[right])
{
                                     right = num;
                                 }
                                 if (upLeft > -1 && Main.tileMergeDirt[upLeft])
{
                                     upLeft = num;
                                 }
                                 else if (upLeft > -1 && mergesWithDirtInASpecialWay[upLeft])
{
                                     upLeft = num;
                                 }
                                 if (upRight > -1 && Main.tileMergeDirt[upRight])
{
                                     upRight = num;
                                 }
                                 else if (upRight > -1 && mergesWithDirtInASpecialWay[upRight])
{
                                     upRight = num;
                                 }
                                 if (downLeft > -1 && Main.tileMergeDirt[downLeft])
{
                                     downLeft = num;
                                 }
                                 else if (downLeft > -1 && mergesWithDirtInASpecialWay[downLeft])
{
                                     downLeft = num;
                                 }
                                 if (downRight > -1 && Main.tileMergeDirt[downRight])
{
                                     downRight = num;
                                 }
                                 else if (downRight > -1 && mergesWithDirtInASpecialWay[downRight])
{
                                     downRight = num;
                                 }
                                 TileMergeAttempt(0, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 TileMergeAttempt(-2, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 TileMergeAttempt(0, 191, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 if (up > -1 && TileID.Sets.ForcedDirtMerging[up])
{
                                     up = num;
                                 }
                                 if (down > -1 && TileID.Sets.ForcedDirtMerging[down])
{
                                     down = num;
                                 }
                                 if (left > -1 && TileID.Sets.ForcedDirtMerging[left])
{
                                     left = num;
                                 }
                                 if (right > -1 && TileID.Sets.ForcedDirtMerging[right])
{
                                     right = num;
                                 }
                                 if (upLeft > -1 && TileID.Sets.ForcedDirtMerging[upLeft])
{
                                     upLeft = num;
                                 }
                                 if (upRight > -1 && TileID.Sets.ForcedDirtMerging[upRight])
{
                                     upRight = num;
                                 }
                                 if (downLeft > -1 && TileID.Sets.ForcedDirtMerging[downLeft])
{
                                     downLeft = num;
                                 }
                                 if (downRight > -1 && TileID.Sets.ForcedDirtMerging[downRight])
{
                                     downRight = num;
                                 }
                             }
                             else if (Main.tileRope[num])
{
                                 if (num != 504 && up != num && IsRope(i, j - 1))
{
                                     up = num;
                                 }
                                 if (down != num && IsRope(i, j + 1))
{
                                     down = num;
                                 }
                                 if (num != 504 && up > -1 && Main.tileSolid[up] && !Main.tileSolidTop[up])
{
                                     up = num;
                                 }
                                 if (down > -1 && Main.tileSolid[down])
{
                                     down = num;
                                 }
                                 if (num != 504 && up != num)
{
                                     if (left > -1 && Main.tileSolid[left])
{
                                         left = num;
                                     }
                                     if (right > -1 && Main.tileSolid[right])
{
                                         right = num;
                                     }
                                 }
                             }
                             else
{
                                 switch (num)
{
                                 case 53:
                                     TileMergeAttemptFrametest(i, j, num, 397, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, 396, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 234:
                                     TileMergeAttemptFrametest(i, j, num, 399, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, 401, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 112:
                                     TileMergeAttemptFrametest(i, j, num, 398, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, 400, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 116:
                                     TileMergeAttemptFrametest(i, j, num, 402, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, 403, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 }
                             }
                             if (Main.tileMergeDirt[num])
{
                                 TileMergeAttempt(-2, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 if (num == 1)
{
                                     if ((double)j > Main.rockLayer)
{
                                         TileMergeAttemptFrametest(i, j, num, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     }
                                     TileMergeAttemptFrametest(i, j, num, TileID.Sets.Ash, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 }
                             }
                             else
{
                                 switch (num)
{
                                 case 58:
                                 case 75:
                                 case 76:
                                     TileMergeAttempt(-2, TileID.Sets.Ash, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 57:
                                     TileMergeAttempt(-2, 1, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttempt(num, 633, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, TileID.Sets.HellSpecial, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 59:
                                     if ((double)j > Main.rockLayer)
{
                                         TileMergeAttempt(-2, 1, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     }
                                     TileMergeAttempt(num, TileID.Sets.GrassSpecial, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, TileID.Sets.JungleSpecial, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     if ((double)j < Main.rockLayer)
{
                                         TileMergeAttemptFrametest(i, j, num, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     }
                                     else
{
                                         TileMergeAttempt(num, TileID.Sets.Dirt, ref up, ref down, ref left, ref right);
                                     }
                                     break;
                                 case 211:
                                     TileMergeAttempt(59, 60, ref up, ref down, ref left, ref right);
                                     TileMergeAttempt(-2, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 225:
                                 case 226:
                                     TileMergeAttempt(-2, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 60:
                                     TileMergeAttempt(59, 211, ref up, ref down, ref left, ref right);
                                     break;
                                 case 189:
                                     TileMergeAttemptFrametest(i, j, num, TileID.Sets.MergesWithClouds, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 196:
                                     TileMergeAttempt(-2, 189, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttempt(num, 460, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 460:
                                     TileMergeAttempt(-2, 189, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttempt(num, 196, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 147:
                                     TileMergeAttemptFrametest(i, j, num, TileID.Sets.IcesSlush, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 161:
                                 case 163:
                                 case 164:
                                 case 200:
                                 case 224:
                                     TileMergeAttempt(-2, 147, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 162:
                                     TileMergeAttempt(-2, TileID.Sets.IcesSnow, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 32:
                                     if (down == 23)
{
                                         down = num;
                                     }
                                     break;
                                 case 352:
                                     if (down == 199)
{
                                         down = num;
                                     }
                                     break;
                                 case 69:
                                     if (down == 60)
{
                                         down = num;
                                     }
                                     break;
                                 case 655:
                                     if (down == 60)
{
                                         down = num;
                                     }
                                     break;
                                 case 51:
                                     TileMergeAttempt(num, TileID.Sets.AllTiles, Main.tileNoAttach, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 192:
                                     TileMergeAttemptFrametest(i, j, num, 191, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 191:
                                     TileMergeAttempt(-2, 192, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttempt(num, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 384:
                                     TileMergeAttemptFrametest(i, j, num, 383, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 383:
                                     TileMergeAttempt(-2, 384, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttempt(num, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 407:
                                     TileMergeAttempt(-2, 404, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 404:
                                     TileMergeAttempt(-2, 396, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, 407, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 397:
                                     TileMergeAttempt(-2, 53, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, 396, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 396:
                                     TileMergeAttempt(-2, 397, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttempt(-2, 53, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, 404, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 398:
                                     TileMergeAttempt(-2, 112, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, 400, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 400:
                                     TileMergeAttempt(-2, 398, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttempt(-2, 112, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 399:
                                     TileMergeAttempt(-2, 234, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, 401, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 401:
                                     TileMergeAttempt(-2, 399, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttempt(-2, 234, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 402:
                                     TileMergeAttempt(-2, 116, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttemptFrametest(i, j, num, 403, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 case 403:
                                     TileMergeAttempt(-2, 402, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     TileMergeAttempt(-2, 116, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     break;
                                 }
                             }
                             if (num == 0)
{
                                 TileMergeAttempt(num, Main.tileMoss, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 TileMergeAttempt(num, TileID.Sets.tileMossBrick, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             else if (Main.tileMoss[num] || TileID.Sets.tileMossBrick[num])
{
                                 TileMergeAttempt(num, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             else if (Main.tileStone[num] || num == 1)
{
                                 TileMergeAttempt(num, Main.tileMoss, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             else if (num == 38)
{
                                 TileMergeAttempt(num, TileID.Sets.tileMossBrick, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             if (TileID.Sets.Conversion.Grass[num])
{
                                 TileMergeAttempt(num, TileID.Sets.Ore, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             else if (TileID.Sets.Ore[num])
{
                                 TileMergeAttempt(num, TileID.Sets.Conversion.Grass, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             if (num >= 0 && num < TileID.Count && TileID.Sets.Mud[num])
{
                                 TileMergeAttempt(num, TileID.Sets.OreMergesWithMud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             else if (TileID.Sets.OreMergesWithMud[num])
{
                                 TileMergeAttempt(num, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             bool flag = false;
                             TileMergeCullCache tileMergeCullCache = default(TileMergeCullCache);
                             if (!Main.ShouldShowInvisibleWalls())
{
                                 bool flag2 = tile.invisibleBlock();
                                 tileMergeCullCache.CullTop |= tile2 != null && tile2.invisibleBlock() != flag2;
                                 tileMergeCullCache.CullBottom |= tile3 != null && tile3.invisibleBlock() != flag2;
                                 tileMergeCullCache.CullLeft |= tile4 != null && tile4.invisibleBlock() != flag2;
                                 tileMergeCullCache.CullRight |= tile5 != null && tile5.invisibleBlock() != flag2;
                                 tileMergeCullCache.CullTopLeft |= tile8 != null && tile8.invisibleBlock() != flag2;
                                 tileMergeCullCache.CullTopRight |= tile9 != null && tile9.invisibleBlock() != flag2;
                                 tileMergeCullCache.CullBottomLeft |= tile6 != null && tile6.invisibleBlock() != flag2;
                                 tileMergeCullCache.CullBottomRight |= tile7 != null && tile7.invisibleBlock() != flag2;
                             }
                             if (num == 2 || num == 23 || num == 661 || num == 662 || num == 60 || num == 477 || num == 492 || num == 70 || num == 109 || num == 199 || Main.tileMoss[num] || TileID.Sets.NeedsGrassFraming[num] || TileID.Sets.tileMossBrick[num])
{
                                 flag = true;
                                 TileMergeAttemptWeird(num, -1, Main.tileSolid, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 int num32 = TileID.Sets.NeedsGrassFramingDirt[num];
                                 if (num == 60 || num == 70 || num == 661 || num == 662)
{
                                     num32 = 59;
                                 }
                                 else if (Main.tileMoss[num])
{
                                     num32 = 1;
                                 }
                                 else if (TileID.Sets.tileMossBrick[num])
{
                                     num32 = 38;
                                 }
                                 else
{
                                     switch (num)
{
                                     case 2:
                                     case 477:
                                         TileMergeAttempt(num32, 23, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                         break;
                                     case 23:
                                         TileMergeAttempt(num32, 2, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                         break;
                                     }
                                 }
                                 tileMergeCullCache.Cull(ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 if (up != num && up != num32 && (down == num || down == num32))
{
                                     if (left == num32 && right == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 0;
                                             rectangle.Y = 198;
                                             break;
                                         case 1:
                                             rectangle.X = 18;
                                             rectangle.Y = 198;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 198;
                                             break;
                                         }
                                     }
                                     else if (left == num && right == num32)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 198;
                                             break;
                                         case 1:
                                             rectangle.X = 72;
                                             rectangle.Y = 198;
                                             break;
                                         default:
                                             rectangle.X = 90;
                                             rectangle.Y = 198;
                                             break;
                                         }
                                     }
                                 }
                                 else if (down != num && down != num32 && (up == num || up == num32))
{
                                     if (left == num32 && right == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 0;
                                             rectangle.Y = 216;
                                             break;
                                         case 1:
                                             rectangle.X = 18;
                                             rectangle.Y = 216;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 216;
                                             break;
                                         }
                                     }
                                     else if (left == num && right == num32)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 216;
                                             break;
                                         case 1:
                                             rectangle.X = 72;
                                             rectangle.Y = 216;
                                             break;
                                         default:
                                             rectangle.X = 90;
                                             rectangle.Y = 216;
                                             break;
                                         }
                                     }
                                 }
                                 else if (left != num && left != num32 && (right == num || right == num32))
{
                                     if (up == num32 && down == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 72;
                                             rectangle.Y = 144;
                                             break;
                                         case 1:
                                             rectangle.X = 72;
                                             rectangle.Y = 162;
                                             break;
                                         default:
                                             rectangle.X = 72;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                     }
                                     else if (down == num && up == num32)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 72;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 72;
                                             rectangle.Y = 108;
                                             break;
                                         default:
                                             rectangle.X = 72;
                                             rectangle.Y = 126;
                                             break;
                                         }
                                     }
                                 }
                                 else if (right != num && right != num32 && (left == num || left == num32))
{
                                     if (up == num32 && down == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 90;
                                             rectangle.Y = 144;
                                             break;
                                         case 1:
                                             rectangle.X = 90;
                                             rectangle.Y = 162;
                                             break;
                                         default:
                                             rectangle.X = 90;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                     }
                                     else if (down == num && right == up)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 90;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 90;
                                             rectangle.Y = 108;
                                             break;
                                         default:
                                             rectangle.X = 90;
                                             rectangle.Y = 126;
                                             break;
                                         }
                                     }
                                 }
                                 else if (up == num && down == num && left == num && right == num)
{
                                     if (upLeft != num && upRight != num && downLeft != num && downRight != num)
{
                                         if (downRight == num32)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 108;
                                                 rectangle.Y = 324;
                                                 break;
                                             case 1:
                                                 rectangle.X = 126;
                                                 rectangle.Y = 324;
                                                 break;
                                             default:
                                                 rectangle.X = 144;
                                                 rectangle.Y = 324;
                                                 break;
                                             }
                                         }
                                         else if (upRight == num32)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 108;
                                                 rectangle.Y = 342;
                                                 break;
                                             case 1:
                                                 rectangle.X = 126;
                                                 rectangle.Y = 342;
                                                 break;
                                             default:
                                                 rectangle.X = 144;
                                                 rectangle.Y = 342;
                                                 break;
                                             }
                                         }
                                         else if (downLeft == num32)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 108;
                                                 rectangle.Y = 360;
                                                 break;
                                             case 1:
                                                 rectangle.X = 126;
                                                 rectangle.Y = 360;
                                                 break;
                                             default:
                                                 rectangle.X = 144;
                                                 rectangle.Y = 360;
                                                 break;
                                             }
                                         }
                                         else if (upLeft == num32)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 108;
                                                 rectangle.Y = 378;
                                                 break;
                                             case 1:
                                                 rectangle.X = 126;
                                                 rectangle.Y = 378;
                                                 break;
                                             default:
                                                 rectangle.X = 144;
                                                 rectangle.Y = 378;
                                                 break;
                                             }
                                         }
                                         else
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 144;
                                                 rectangle.Y = 234;
                                                 break;
                                             case 1:
                                                 rectangle.X = 198;
                                                 rectangle.Y = 234;
                                                 break;
                                             default:
                                                 rectangle.X = 252;
                                                 rectangle.Y = 234;
                                                 break;
                                             }
                                         }
                                     }
                                     else if (upLeft != num && downRight != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 36;
                                             rectangle.Y = 306;
                                             break;
                                         case 1:
                                             rectangle.X = 54;
                                             rectangle.Y = 306;
                                             break;
                                         default:
                                             rectangle.X = 72;
                                             rectangle.Y = 306;
                                             break;
                                         }
                                     }
                                     else if (upRight != num && downLeft != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 90;
                                             rectangle.Y = 306;
                                             break;
                                         case 1:
                                             rectangle.X = 108;
                                             rectangle.Y = 306;
                                             break;
                                         default:
                                             rectangle.X = 126;
                                             rectangle.Y = 306;
                                             break;
                                         }
                                     }
                                     else if (upLeft != num && upRight == num && downLeft == num && downRight == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 108;
                                             break;
                                         case 1:
                                             rectangle.X = 54;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                     }
                                     else if (upLeft == num && upRight != num && downLeft == num && downRight == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 36;
                                             rectangle.Y = 108;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                     }
                                     else if (upLeft == num && upRight == num && downLeft != num && downRight == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 54;
                                             rectangle.Y = 126;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                     }
                                     else if (upLeft == num && upRight == num && downLeft == num && downRight != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 36;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 126;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                     }
                                 }
                                 else if (up == num && down == num32 && left == num && right == num && upLeft == -1 && upRight == -1)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 108;
                                         rectangle.Y = 18;
                                         break;
                                     case 1:
                                         rectangle.X = 126;
                                         rectangle.Y = 18;
                                         break;
                                     default:
                                         rectangle.X = 144;
                                         rectangle.Y = 18;
                                         break;
                                     }
                                 }
                                 else if (up == num32 && down == num && left == num && right == num && downLeft == -1 && downRight == -1)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 108;
                                         rectangle.Y = 36;
                                         break;
                                     case 1:
                                         rectangle.X = 126;
                                         rectangle.Y = 36;
                                         break;
                                     default:
                                         rectangle.X = 144;
                                         rectangle.Y = 36;
                                         break;
                                     }
                                 }
                                 else if (up == num && down == num && left == num32 && right == num && upRight == -1 && downRight == -1)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 198;
                                         rectangle.Y = 0;
                                         break;
                                     case 1:
                                         rectangle.X = 198;
                                         rectangle.Y = 18;
                                         break;
                                     default:
                                         rectangle.X = 198;
                                         rectangle.Y = 36;
                                         break;
                                     }
                                 }
                                 else if (up == num && down == num && left == num && right == num32 && upLeft == -1 && downLeft == -1)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 180;
                                         rectangle.Y = 0;
                                         break;
                                     case 1:
                                         rectangle.X = 180;
                                         rectangle.Y = 18;
                                         break;
                                     default:
                                         rectangle.X = 180;
                                         rectangle.Y = 36;
                                         break;
                                     }
                                 }
                                 else if (up == num && down == num32 && left == num && right == num)
{
                                     if (upRight != -1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 108;
                                             break;
                                         case 1:
                                             rectangle.X = 54;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                     }
                                     else if (upLeft != -1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 36;
                                             rectangle.Y = 108;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                     }
                                 }
                                 else if (up == num32 && down == num && left == num && right == num)
{
                                     if (downRight != -1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 54;
                                             rectangle.Y = 126;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                     }
                                     else if (downLeft != -1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 36;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 126;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                     }
                                 }
                                 else if (up == num && down == num && left == num && right == num32)
{
                                     if (upLeft != -1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 54;
                                             rectangle.Y = 126;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                     }
                                     else if (downLeft != -1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 108;
                                             break;
                                         case 1:
                                             rectangle.X = 54;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                     }
                                 }
                                 else if (up == num && down == num && left == num32 && right == num)
{
                                     if (upRight != -1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 36;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 126;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                     }
                                     else if (downRight != -1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 36;
                                             rectangle.Y = 108;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                     }
                                 }
                                 else if ((up == num32 && down == num && left == num && right == num) || (up == num && down == num32 && left == num && right == num) || (up == num && down == num && left == num32 && right == num) || (up == num && down == num && left == num && right == num32))
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 18;
                                         rectangle.Y = 18;
                                         break;
                                     case 1:
                                         rectangle.X = 36;
                                         rectangle.Y = 18;
                                         break;
                                     default:
                                         rectangle.X = 54;
                                         rectangle.Y = 18;
                                         break;
                                     }
                                 }
                                 if ((up == num || up == num32) && (down == num || down == num32) && (left == num || left == num32) && (right == num || right == num32))
{
                                     if (upLeft != num && upLeft != num32 && (upRight == num || upRight == num32) && (downLeft == num || downLeft == num32) && (downRight == num || downRight == num32))
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 108;
                                             break;
                                         case 1:
                                             rectangle.X = 54;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                     }
                                     else if (upRight != num && upRight != num32 && (upLeft == num || upLeft == num32) && (downLeft == num || downLeft == num32) && (downRight == num || downRight == num32))
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 36;
                                             rectangle.Y = 108;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                     }
                                     else if (downLeft != num && downLeft != num32 && (upLeft == num || upLeft == num32) && (upRight == num || upRight == num32) && (downRight == num || downRight == num32))
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 54;
                                             rectangle.Y = 126;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                     }
                                     else if (downRight != num && downRight != num32 && (upLeft == num || upLeft == num32) && (downLeft == num || downLeft == num32) && (upRight == num || upRight == num32))
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 36;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 126;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                     }
                                 }
                                 if (up != num32 && up != num && down == num && left != num32 && left != num && right == num && downRight != num32 && downRight != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 90;
                                         rectangle.Y = 270;
                                         break;
                                     case 1:
                                         rectangle.X = 108;
                                         rectangle.Y = 270;
                                         break;
                                     default:
                                         rectangle.X = 126;
                                         rectangle.Y = 270;
                                         break;
                                     }
                                 }
                                 else if (up != num32 && up != num && down == num && left == num && right != num32 && right != num && downLeft != num32 && downLeft != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 144;
                                         rectangle.Y = 270;
                                         break;
                                     case 1:
                                         rectangle.X = 162;
                                         rectangle.Y = 270;
                                         break;
                                     default:
                                         rectangle.X = 180;
                                         rectangle.Y = 270;
                                         break;
                                     }
                                 }
                                 else if (down != num32 && down != num && up == num && left != num32 && left != num && right == num && upRight != num32 && upRight != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 90;
                                         rectangle.Y = 288;
                                         break;
                                     case 1:
                                         rectangle.X = 108;
                                         rectangle.Y = 288;
                                         break;
                                     default:
                                         rectangle.X = 126;
                                         rectangle.Y = 288;
                                         break;
                                     }
                                 }
                                 else if (down != num32 && down != num && up == num && left == num && right != num32 && right != num && upLeft != num32 && upLeft != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 144;
                                         rectangle.Y = 288;
                                         break;
                                     case 1:
                                         rectangle.X = 162;
                                         rectangle.Y = 288;
                                         break;
                                     default:
                                         rectangle.X = 180;
                                         rectangle.Y = 288;
                                         break;
                                     }
                                 }
                                 else if (up != num && up != num32 && down == num && left == num && right == num && downLeft != num && downLeft != num32 && downRight != num && downRight != num32)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 144;
                                         rectangle.Y = 216;
                                         break;
                                     case 1:
                                         rectangle.X = 198;
                                         rectangle.Y = 216;
                                         break;
                                     default:
                                         rectangle.X = 252;
                                         rectangle.Y = 216;
                                         break;
                                     }
                                 }
                                 else if (down != num && down != num32 && up == num && left == num && right == num && upLeft != num && upLeft != num32 && upRight != num && upRight != num32)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 144;
                                         rectangle.Y = 252;
                                         break;
                                     case 1:
                                         rectangle.X = 198;
                                         rectangle.Y = 252;
                                         break;
                                     default:
                                         rectangle.X = 252;
                                         rectangle.Y = 252;
                                         break;
                                     }
                                 }
                                 else if (left != num && left != num32 && down == num && up == num && right == num && upRight != num && upRight != num32 && downRight != num && downRight != num32)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 126;
                                         rectangle.Y = 234;
                                         break;
                                     case 1:
                                         rectangle.X = 180;
                                         rectangle.Y = 234;
                                         break;
                                     default:
                                         rectangle.X = 234;
                                         rectangle.Y = 234;
                                         break;
                                     }
                                 }
                                 else if (right != num && right != num32 && down == num && up == num && left == num && upLeft != num && upLeft != num32 && downLeft != num && downLeft != num32)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 162;
                                         rectangle.Y = 234;
                                         break;
                                     case 1:
                                         rectangle.X = 216;
                                         rectangle.Y = 234;
                                         break;
                                     default:
                                         rectangle.X = 270;
                                         rectangle.Y = 234;
                                         break;
                                     }
                                 }
                                 else if (up != num32 && up != num && (down == num32 || down == num) && left == num32 && right == num32)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 36;
                                         rectangle.Y = 270;
                                         break;
                                     case 1:
                                         rectangle.X = 54;
                                         rectangle.Y = 270;
                                         break;
                                     default:
                                         rectangle.X = 72;
                                         rectangle.Y = 270;
                                         break;
                                     }
                                 }
                                 else if (down != num32 && down != num && (up == num32 || up == num) && left == num32 && right == num32)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 36;
                                         rectangle.Y = 288;
                                         break;
                                     case 1:
                                         rectangle.X = 54;
                                         rectangle.Y = 288;
                                         break;
                                     default:
                                         rectangle.X = 72;
                                         rectangle.Y = 288;
                                         break;
                                     }
                                 }
                                 else if (left != num32 && left != num && (right == num32 || right == num) && up == num32 && down == num32)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 0;
                                         rectangle.Y = 270;
                                         break;
                                     case 1:
                                         rectangle.X = 0;
                                         rectangle.Y = 288;
                                         break;
                                     default:
                                         rectangle.X = 0;
                                         rectangle.Y = 306;
                                         break;
                                     }
                                 }
                                 else if (right != num32 && right != num && (left == num32 || left == num) && up == num32 && down == num32)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 18;
                                         rectangle.Y = 270;
                                         break;
                                     case 1:
                                         rectangle.X = 18;
                                         rectangle.Y = 288;
                                         break;
                                     default:
                                         rectangle.X = 18;
                                         rectangle.Y = 306;
                                         break;
                                     }
                                 }
                                 else if (up == num && down == num32 && left == num32 && right == num32)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 198;
                                         rectangle.Y = 288;
                                         break;
                                     case 1:
                                         rectangle.X = 216;
                                         rectangle.Y = 288;
                                         break;
                                     default:
                                         rectangle.X = 234;
                                         rectangle.Y = 288;
                                         break;
                                     }
                                 }
                                 else if (up == num32 && down == num && left == num32 && right == num32)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 198;
                                         rectangle.Y = 270;
                                         break;
                                     case 1:
                                         rectangle.X = 216;
                                         rectangle.Y = 270;
                                         break;
                                     default:
                                         rectangle.X = 234;
                                         rectangle.Y = 270;
                                         break;
                                     }
                                 }
                                 else if (up == num32 && down == num32 && left == num && right == num32)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 198;
                                         rectangle.Y = 306;
                                         break;
                                     case 1:
                                         rectangle.X = 216;
                                         rectangle.Y = 306;
                                         break;
                                     default:
                                         rectangle.X = 234;
                                         rectangle.Y = 306;
                                         break;
                                     }
                                 }
                                 else if (up == num32 && down == num32 && left == num32 && right == num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 144;
                                         rectangle.Y = 306;
                                         break;
                                     case 1:
                                         rectangle.X = 162;
                                         rectangle.Y = 306;
                                         break;
                                     default:
                                         rectangle.X = 180;
                                         rectangle.Y = 306;
                                         break;
                                     }
                                 }
                                 if (up != num && up != num32 && down == num && left == num && right == num)
{
                                     if ((downLeft == num32 || downLeft == num) && downRight != num32 && downRight != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 0;
                                             rectangle.Y = 324;
                                             break;
                                         case 1:
                                             rectangle.X = 18;
                                             rectangle.Y = 324;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 324;
                                             break;
                                         }
                                     }
                                     else if ((downRight == num32 || downRight == num) && downLeft != num32 && downLeft != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 324;
                                             break;
                                         case 1:
                                             rectangle.X = 72;
                                             rectangle.Y = 324;
                                             break;
                                         default:
                                             rectangle.X = 90;
                                             rectangle.Y = 324;
                                             break;
                                         }
                                     }
                                 }
                                 else if (down != num && down != num32 && up == num && left == num && right == num)
{
                                     if ((upLeft == num32 || upLeft == num) && upRight != num32 && upRight != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 0;
                                             rectangle.Y = 342;
                                             break;
                                         case 1:
                                             rectangle.X = 18;
                                             rectangle.Y = 342;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 342;
                                             break;
                                         }
                                     }
                                     else if ((upRight == num32 || upRight == num) && upLeft != num32 && upLeft != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 342;
                                             break;
                                         case 1:
                                             rectangle.X = 72;
                                             rectangle.Y = 342;
                                             break;
                                         default:
                                             rectangle.X = 90;
                                             rectangle.Y = 342;
                                             break;
                                         }
                                     }
                                 }
                                 else if (left != num && left != num32 && up == num && down == num && right == num)
{
                                     if ((upRight == num32 || upRight == num) && downRight != num32 && downRight != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 360;
                                             break;
                                         case 1:
                                             rectangle.X = 72;
                                             rectangle.Y = 360;
                                             break;
                                         default:
                                             rectangle.X = 90;
                                             rectangle.Y = 360;
                                             break;
                                         }
                                     }
                                     else if ((downRight == num32 || downRight == num) && upRight != num32 && upRight != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 0;
                                             rectangle.Y = 360;
                                             break;
                                         case 1:
                                             rectangle.X = 18;
                                             rectangle.Y = 360;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 360;
                                             break;
                                         }
                                     }
                                 }
                                 else if (right != num && right != num32 && up == num && down == num && left == num)
{
                                     if ((upLeft == num32 || upLeft == num) && downLeft != num32 && downLeft != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 0;
                                             rectangle.Y = 378;
                                             break;
                                         case 1:
                                             rectangle.X = 18;
                                             rectangle.Y = 378;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 378;
                                             break;
                                         }
                                     }
                                     else if ((downLeft == num32 || downLeft == num) && upLeft != num32 && upLeft != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 378;
                                             break;
                                         case 1:
                                             rectangle.X = 72;
                                             rectangle.Y = 378;
                                             break;
                                         default:
                                             rectangle.X = 90;
                                             rectangle.Y = 378;
                                             break;
                                         }
                                     }
                                 }
                                 if ((up == num || up == num32) && (down == num || down == num32) && (left == num || left == num32) && (right == num || right == num32) && upLeft != -1 && upRight != -1 && downLeft != -1 && downRight != -1)
{
                                     if ((i + j) % 2 == 1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 108;
                                             rectangle.Y = 198;
                                             break;
                                         case 1:
                                             rectangle.X = 126;
                                             rectangle.Y = 198;
                                             break;
                                         default:
                                             rectangle.X = 144;
                                             rectangle.Y = 198;
                                             break;
                                         }
                                     }
                                     else
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 18;
                                             rectangle.Y = 18;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 18;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 18;
                                             break;
                                         }
                                     }
                                 }
                                 if (num32 >= 0 && num32 < TileID.Count && TileID.Sets.Dirt[num32])
{
                                     TileMergeAttempt(-2, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 }
                                 else if (num32 >= 0 && num32 < TileID.Count && TileID.Sets.Mud[num32])
{
                                     TileMergeAttempt(-2, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 }
                                 else
{
                                     TileMergeAttempt(-2, num32, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 }
                                 tileMergeCullCache.Cull(ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             }
                             TileMergeAttempt(num, Main.tileMerge[num], ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                             if (rectangle.X == -1 && rectangle.Y == -1 && (Main.tileMergeDirt[num] || (num > -1 && TileID.Sets.ChecksForMerge[num])))
{
                                 if (!flag)
{
                                     flag = true;
                                     TileMergeAttemptWeird(num, -1, Main.tileSolid, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 }
                                 if (up > -1 && up != num)
{
                                     up = -1;
                                 }
                                 if (down > -1 && down != num)
{
                                     down = -1;
                                 }
                                 if (left > -1 && left != num)
{
                                     left = -1;
                                 }
                                 if (right > -1 && right != num)
{
                                     right = -1;
                                 }
                                 tileMergeCullCache.Cull(ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 if (up != -1 && down != -1 && left != -1 && right != -1)
{
                                     if (up == -2 && down == num && left == num && right == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 144;
                                             rectangle.Y = 108;
                                             break;
                                         case 1:
                                             rectangle.X = 162;
                                             rectangle.Y = 108;
                                             break;
                                         default:
                                             rectangle.X = 180;
                                             rectangle.Y = 108;
                                             break;
                                         }
                                         mergeUp = true;
                                     }
                                     else if (up == num && down == -2 && left == num && right == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 144;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 162;
                                             rectangle.Y = 90;
                                             break;
                                         default:
                                             rectangle.X = 180;
                                             rectangle.Y = 90;
                                             break;
                                         }
                                         mergeDown = true;
                                     }
                                     else if (up == num && down == num && left == -2 && right == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 162;
                                             rectangle.Y = 126;
                                             break;
                                         case 1:
                                             rectangle.X = 162;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 162;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                         mergeLeft = true;
                                     }
                                     else if (up == num && down == num && left == num && right == -2)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 144;
                                             rectangle.Y = 126;
                                             break;
                                         case 1:
                                             rectangle.X = 144;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 144;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                         mergeRight = true;
                                     }
                                     else if (up == -2 && down == num && left == -2 && right == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 36;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 126;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                         mergeUp = true;
                                         mergeLeft = true;
                                     }
                                     else if (up == -2 && down == num && left == num && right == -2)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 54;
                                             rectangle.Y = 126;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                         mergeUp = true;
                                         mergeRight = true;
                                     }
                                     else if (up == num && down == -2 && left == -2 && right == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 36;
                                             rectangle.Y = 108;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                         mergeDown = true;
                                         mergeLeft = true;
                                     }
                                     else if (up == num && down == -2 && left == num && right == -2)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 108;
                                             break;
                                         case 1:
                                             rectangle.X = 54;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                         mergeDown = true;
                                         mergeRight = true;
                                     }
                                     else if (up == num && down == num && left == -2 && right == -2)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 180;
                                             rectangle.Y = 126;
                                             break;
                                         case 1:
                                             rectangle.X = 180;
                                             rectangle.Y = 144;
                                             break;
                                         default:
                                             rectangle.X = 180;
                                             rectangle.Y = 162;
                                             break;
                                         }
                                         mergeLeft = true;
                                         mergeRight = true;
                                     }
                                     else if (up == -2 && down == -2 && left == num && right == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 144;
                                             rectangle.Y = 180;
                                             break;
                                         case 1:
                                             rectangle.X = 162;
                                             rectangle.Y = 180;
                                             break;
                                         default:
                                             rectangle.X = 180;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                         mergeUp = true;
                                         mergeDown = true;
                                     }
                                     else if (up == -2 && down == num && left == -2 && right == -2)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 198;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 198;
                                             rectangle.Y = 108;
                                             break;
                                         default:
                                             rectangle.X = 198;
                                             rectangle.Y = 126;
                                             break;
                                         }
                                         mergeUp = true;
                                         mergeLeft = true;
                                         mergeRight = true;
                                     }
                                     else if (up == num && down == -2 && left == -2 && right == -2)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 198;
                                             rectangle.Y = 144;
                                             break;
                                         case 1:
                                             rectangle.X = 198;
                                             rectangle.Y = 162;
                                             break;
                                         default:
                                             rectangle.X = 198;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                         mergeDown = true;
                                         mergeLeft = true;
                                         mergeRight = true;
                                     }
                                     else if (up == -2 && down == -2 && left == num && right == -2)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 216;
                                             rectangle.Y = 144;
                                             break;
                                         case 1:
                                             rectangle.X = 216;
                                             rectangle.Y = 162;
                                             break;
                                         default:
                                             rectangle.X = 216;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                         mergeUp = true;
                                         mergeDown = true;
                                         mergeRight = true;
                                     }
                                     else if (up == -2 && down == -2 && left == -2 && right == num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 216;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 216;
                                             rectangle.Y = 108;
                                             break;
                                         default:
                                             rectangle.X = 216;
                                             rectangle.Y = 126;
                                             break;
                                         }
                                         mergeUp = true;
                                         mergeDown = true;
                                         mergeLeft = true;
                                     }
                                     else if (up == -2 && down == -2 && left == -2 && right == -2)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 108;
                                             rectangle.Y = 198;
                                             break;
                                         case 1:
                                             rectangle.X = 126;
                                             rectangle.Y = 198;
                                             break;
                                         default:
                                             rectangle.X = 144;
                                             rectangle.Y = 198;
                                             break;
                                         }
                                         mergeUp = true;
                                         mergeDown = true;
                                         mergeLeft = true;
                                         mergeRight = true;
                                     }
                                     else if (up == num && down == num && left == num && right == num)
{
                                         if (upLeft == -2)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 18;
                                                 rectangle.Y = 108;
                                                 break;
                                             case 1:
                                                 rectangle.X = 18;
                                                 rectangle.Y = 144;
                                                 break;
                                             default:
                                                 rectangle.X = 18;
                                                 rectangle.Y = 180;
                                                 break;
                                             }
                                         }
                                         if (upRight == -2)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 0;
                                                 rectangle.Y = 108;
                                                 break;
                                             case 1:
                                                 rectangle.X = 0;
                                                 rectangle.Y = 144;
                                                 break;
                                             default:
                                                 rectangle.X = 0;
                                                 rectangle.Y = 180;
                                                 break;
                                             }
                                         }
                                         if (downLeft == -2)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 18;
                                                 rectangle.Y = 90;
                                                 break;
                                             case 1:
                                                 rectangle.X = 18;
                                                 rectangle.Y = 126;
                                                 break;
                                             default:
                                                 rectangle.X = 18;
                                                 rectangle.Y = 162;
                                                 break;
                                             }
                                         }
                                         if (downRight == -2)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 0;
                                                 rectangle.Y = 90;
                                                 break;
                                             case 1:
                                                 rectangle.X = 0;
                                                 rectangle.Y = 126;
                                                 break;
                                             default:
                                                 rectangle.X = 0;
                                                 rectangle.Y = 162;
                                                 break;
                                             }
                                         }
                                     }
                                 }
                                 else
{
                                     if (num != 2 && num != 23 && num != 60 && num != 70 && num != 109 && num != 199 && num != 477 && num != 492 && num != 633 && num != 661 && num != 662)
{
                                         if (up == -1 && down == -2 && left == num && right == num)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 234;
                                                 rectangle.Y = 0;
                                                 break;
                                             case 1:
                                                 rectangle.X = 252;
                                                 rectangle.Y = 0;
                                                 break;
                                             default:
                                                 rectangle.X = 270;
                                                 rectangle.Y = 0;
                                                 break;
                                             }
                                             mergeDown = true;
                                         }
                                         else if (up == -2 && down == -1 && left == num && right == num)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 234;
                                                 rectangle.Y = 18;
                                                 break;
                                             case 1:
                                                 rectangle.X = 252;
                                                 rectangle.Y = 18;
                                                 break;
                                             default:
                                                 rectangle.X = 270;
                                                 rectangle.Y = 18;
                                                 break;
                                             }
                                             mergeUp = true;
                                         }
                                         else if (up == num && down == num && left == -1 && right == -2)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 234;
                                                 rectangle.Y = 36;
                                                 break;
                                             case 1:
                                                 rectangle.X = 252;
                                                 rectangle.Y = 36;
                                                 break;
                                             default:
                                                 rectangle.X = 270;
                                                 rectangle.Y = 36;
                                                 break;
                                             }
                                             mergeRight = true;
                                         }
                                         else if (up == num && down == num && left == -2 && right == -1)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 234;
                                                 rectangle.Y = 54;
                                                 break;
                                             case 1:
                                                 rectangle.X = 252;
                                                 rectangle.Y = 54;
                                                 break;
                                             default:
                                                 rectangle.X = 270;
                                                 rectangle.Y = 54;
                                                 break;
                                             }
                                             mergeLeft = true;
                                         }
                                     }
                                     if (up != -1 && down != -1 && left == -1 && right == num)
{
                                         if (up == -2 && down == num)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 72;
                                                 rectangle.Y = 144;
                                                 break;
                                             case 1:
                                                 rectangle.X = 72;
                                                 rectangle.Y = 162;
                                                 break;
                                             default:
                                                 rectangle.X = 72;
                                                 rectangle.Y = 180;
                                                 break;
                                             }
                                             mergeUp = true;
                                         }
                                         else if (down == -2 && up == num)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 72;
                                                 rectangle.Y = 90;
                                                 break;
                                             case 1:
                                                 rectangle.X = 72;
                                                 rectangle.Y = 108;
                                                 break;
                                             default:
                                                 rectangle.X = 72;
                                                 rectangle.Y = 126;
                                                 break;
                                             }
                                             mergeDown = true;
                                         }
                                     }
                                     else if (up != -1 && down != -1 && left == num && right == -1)
{
                                         if (up == -2 && down == num)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 90;
                                                 rectangle.Y = 144;
                                                 break;
                                             case 1:
                                                 rectangle.X = 90;
                                                 rectangle.Y = 162;
                                                 break;
                                             default:
                                                 rectangle.X = 90;
                                                 rectangle.Y = 180;
                                                 break;
                                             }
                                             mergeUp = true;
                                         }
                                         else if (down == -2 && up == num)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 90;
                                                 rectangle.Y = 90;
                                                 break;
                                             case 1:
                                                 rectangle.X = 90;
                                                 rectangle.Y = 108;
                                                 break;
                                             default:
                                                 rectangle.X = 90;
                                                 rectangle.Y = 126;
                                                 break;
                                             }
                                             mergeDown = true;
                                         }
                                     }
                                     else if (up == -1 && down == num && left != -1 && right != -1)
{
                                         if (left == -2 && right == num)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 0;
                                                 rectangle.Y = 198;
                                                 break;
                                             case 1:
                                                 rectangle.X = 18;
                                                 rectangle.Y = 198;
                                                 break;
                                             default:
                                                 rectangle.X = 36;
                                                 rectangle.Y = 198;
                                                 break;
                                             }
                                             mergeLeft = true;
                                         }
                                         else if (right == -2 && left == num)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 54;
                                                 rectangle.Y = 198;
                                                 break;
                                             case 1:
                                                 rectangle.X = 72;
                                                 rectangle.Y = 198;
                                                 break;
                                             default:
                                                 rectangle.X = 90;
                                                 rectangle.Y = 198;
                                                 break;
                                             }
                                             mergeRight = true;
                                         }
                                     }
                                     else if (up == num && down == -1 && left != -1 && right != -1)
{
                                         if (left == -2 && right == num)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 0;
                                                 rectangle.Y = 216;
                                                 break;
                                             case 1:
                                                 rectangle.X = 18;
                                                 rectangle.Y = 216;
                                                 break;
                                             default:
                                                 rectangle.X = 36;
                                                 rectangle.Y = 216;
                                                 break;
                                             }
                                             mergeLeft = true;
                                         }
                                         else if (right == -2 && left == num)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 54;
                                                 rectangle.Y = 216;
                                                 break;
                                             case 1:
                                                 rectangle.X = 72;
                                                 rectangle.Y = 216;
                                                 break;
                                             default:
                                                 rectangle.X = 90;
                                                 rectangle.Y = 216;
                                                 break;
                                             }
                                             mergeRight = true;
                                         }
                                     }
                                     else if (up != -1 && down != -1 && left == -1 && right == -1)
{
                                         if (up == -2 && down == -2)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 108;
                                                 rectangle.Y = 216;
                                                 break;
                                             case 1:
                                                 rectangle.X = 108;
                                                 rectangle.Y = 234;
                                                 break;
                                             default:
                                                 rectangle.X = 108;
                                                 rectangle.Y = 252;
                                                 break;
                                             }
                                             mergeUp = true;
                                             mergeDown = true;
                                         }
                                         else if (up == -2)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 126;
                                                 rectangle.Y = 144;
                                                 break;
                                             case 1:
                                                 rectangle.X = 126;
                                                 rectangle.Y = 162;
                                                 break;
                                             default:
                                                 rectangle.X = 126;
                                                 rectangle.Y = 180;
                                                 break;
                                             }
                                             mergeUp = true;
                                         }
                                         else if (down == -2)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 126;
                                                 rectangle.Y = 90;
                                                 break;
                                             case 1:
                                                 rectangle.X = 126;
                                                 rectangle.Y = 108;
                                                 break;
                                             default:
                                                 rectangle.X = 126;
                                                 rectangle.Y = 126;
                                                 break;
                                             }
                                             mergeDown = true;
                                         }
                                     }
                                     else if (up == -1 && down == -1 && left != -1 && right != -1)
{
                                         if (left == -2 && right == -2)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 162;
                                                 rectangle.Y = 198;
                                                 break;
                                             case 1:
                                                 rectangle.X = 180;
                                                 rectangle.Y = 198;
                                                 break;
                                             default:
                                                 rectangle.X = 198;
                                                 rectangle.Y = 198;
                                                 break;
                                             }
                                             mergeLeft = true;
                                             mergeRight = true;
                                         }
                                         else if (left == -2)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 0;
                                                 rectangle.Y = 252;
                                                 break;
                                             case 1:
                                                 rectangle.X = 18;
                                                 rectangle.Y = 252;
                                                 break;
                                             default:
                                                 rectangle.X = 36;
                                                 rectangle.Y = 252;
                                                 break;
                                             }
                                             mergeLeft = true;
                                         }
                                         else if (right == -2)
{
                                             switch (num27)
{
                                             case 0:
                                                 rectangle.X = 54;
                                                 rectangle.Y = 252;
                                                 break;
                                             case 1:
                                                 rectangle.X = 72;
                                                 rectangle.Y = 252;
                                                 break;
                                             default:
                                                 rectangle.X = 90;
                                                 rectangle.Y = 252;
                                                 break;
                                             }
                                             mergeRight = true;
                                         }
                                     }
                                     else if (up == -2 && down == -1 && left == -1 && right == -1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 108;
                                             rectangle.Y = 144;
                                             break;
                                         case 1:
                                             rectangle.X = 108;
                                             rectangle.Y = 162;
                                             break;
                                         default:
                                             rectangle.X = 108;
                                             rectangle.Y = 180;
                                             break;
                                         }
                                         mergeUp = true;
                                     }
                                     else if (up == -1 && down == -2 && left == -1 && right == -1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 108;
                                             rectangle.Y = 90;
                                             break;
                                         case 1:
                                             rectangle.X = 108;
                                             rectangle.Y = 108;
                                             break;
                                         default:
                                             rectangle.X = 108;
                                             rectangle.Y = 126;
                                             break;
                                         }
                                         mergeDown = true;
                                     }
                                     else if (up == -1 && down == -1 && left == -2 && right == -1)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 0;
                                             rectangle.Y = 234;
                                             break;
                                         case 1:
                                             rectangle.X = 18;
                                             rectangle.Y = 234;
                                             break;
                                         default:
                                             rectangle.X = 36;
                                             rectangle.Y = 234;
                                             break;
                                         }
                                         mergeLeft = true;
                                     }
                                     else if (up == -1 && down == -1 && left == -1 && right == -2)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 54;
                                             rectangle.Y = 234;
                                             break;
                                         case 1:
                                             rectangle.X = 72;
                                             rectangle.Y = 234;
                                             break;
                                         default:
                                             rectangle.X = 90;
                                             rectangle.Y = 234;
                                             break;
                                         }
                                         mergeRight = true;
                                     }
                                 }
                             }
                             int num33 = tile.blockType();
                             if (TileID.Sets.HasSlopeFrames[num])
{
                                 if (num33 == 0)
{
                                     bool flag3 = num == up && tile2 != null && tile2.topSlope();
                                     bool flag4 = num == left && tile4 != null && tile4.leftSlope();
                                     bool flag5 = num == right && tile5 != null && tile5.rightSlope();
                                     bool flag6 = num == down && tile3 != null && tile3.bottomSlope();
                                     int num34 = 0;
                                     int num35 = 0;
                                     if (flag3.ToInt() + flag4.ToInt() + flag5.ToInt() + flag6.ToInt() > 2)
{
                                         int num36 = (tile2 != null && tile2.slope() == 1).ToInt() + (tile5 != null && tile5.slope() == 1).ToInt() + (tile3 != null && tile3.slope() == 4).ToInt() + (tile4 != null && tile4.slope() == 4).ToInt();
                                         int num37 = (tile2 != null && tile2.slope() == 2).ToInt() + (tile5 != null && tile5.slope() == 3).ToInt() + (tile3 != null && tile3.slope() == 3).ToInt() + (tile4 != null && tile4.slope() == 2).ToInt();
                                         if (num36 == num37)
{
                                             num34 = 2;
                                             num35 = 4;
                                         }
                                         else if (num36 > num37)
{
                                             bool num38 = num == upLeft && tile8 != null && tile8.slope() == 0;
                                             bool flag7 = num == downRight && tile7 != null && tile7.slope() == 0;
                                             if (num38 && flag7)
{
                                                 num35 = 4;
                                             }
                                             else if (flag7)
{
                                                 num34 = 6;
                                             }
                                             else
{
                                                 num34 = 7;
                                                 num35 = 1;
                                             }
                                         }
                                         else
{
                                             bool num39 = num == upRight && tile9 != null && tile9.slope() == 0;
                                             bool flag8 = num == downLeft && tile6 != null && tile6.slope() == 0;
                                             if (num39 && flag8)
{
                                                 num35 = 4;
                                                 num34 = 1;
                                             }
                                             else if (flag8)
{
                                                 num34 = 7;
                                             }
                                             else
{
                                                 num34 = 6;
                                                 num35 = 1;
                                             }
                                         }
                                         rectangle.X = (18 + num34) * 18;
                                         rectangle.Y = num35 * 18;
                                     }
                                     else
{
                                         if (flag3 && flag4 && num == down && num == right)
{
                                             num35 = 2;
                                         }
                                         else if (flag3 && flag5 && num == down && num == left)
{
                                             num34 = 1;
                                             num35 = 2;
                                         }
                                         else if (flag5 && flag6 && num == up && num == left)
{
                                             num34 = 1;
                                             num35 = 3;
                                         }
                                         else if (flag6 && flag4 && num == up && num == right)
{
                                             num35 = 3;
                                         }
                                         if (num34 != 0 || num35 != 0)
{
                                             rectangle.X = (18 + num34) * 18;
                                             rectangle.Y = num35 * 18;
                                         }
                                     }
                                 }
                                 if (num33 >= 2 && (rectangle.X < 0 || rectangle.Y < 0))
{
                                     int num40 = -1;
                                     int num41 = -1;
                                     int num42 = -1;
                                     int num43 = 0;
                                     int num44 = 0;
                                     switch (num33)
{
                                     case 2:
                                         num40 = left;
                                         num41 = down;
                                         num42 = downLeft;
                                         num43++;
                                         break;
                                     case 3:
                                         num40 = right;
                                         num41 = down;
                                         num42 = downRight;
                                         break;
                                     case 4:
                                         num40 = left;
                                         num41 = up;
                                         num42 = upLeft;
                                         num43++;
                                         num44++;
                                         break;
                                     case 5:
                                         num40 = right;
                                         num41 = up;
                                         num42 = upRight;
                                         num44++;
                                         break;
                                     }
                                     if (num != num40 || num != num41 || num != num42)
{
                                         if (num == num40 && num == num41)
{
                                             num43 += 2;
                                         }
                                         else if (num == num40)
{
                                             num43 += 4;
                                         }
                                         else if (num == num41)
{
                                             num43 += 4;
                                             num44 += 2;
                                         }
                                         else
{
                                             num43 += 2;
                                             num44 += 2;
                                         }
                                     }
                                     rectangle.X = (18 + num43) * 18;
                                     rectangle.Y = num44 * 18;
                                 }
                             }
                             if (rectangle.X < 0 || rectangle.Y < 0)
{
                                 if (!flag)
{
                                     flag = true;
                                     TileMergeAttemptWeird(num, -1, Main.tileSolid, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     tileMergeCullCache.Cull(ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 }
                                 if (num == 2 || num == 23 || num == 60 || num == 70 || num == 109 || num == 199 || num == 477 || num == 492 || num == 633 || num == 661 || num == 662 || Main.tileMoss[num] || TileID.Sets.tileMossBrick[num])
{
                                     TileMergeAttempt(num, -2, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                     tileMergeCullCache.Cull(ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                 }
                                 if (up == num && down == num && left == num && right == num)
{
                                     if (upLeft != num && upRight != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 108;
                                             rectangle.Y = 18;
                                             break;
                                         case 1:
                                             rectangle.X = 126;
                                             rectangle.Y = 18;
                                             break;
                                         default:
                                             rectangle.X = 144;
                                             rectangle.Y = 18;
                                             break;
                                         }
                                     }
                                     else if (downLeft != num && downRight != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 108;
                                             rectangle.Y = 36;
                                             break;
                                         case 1:
                                             rectangle.X = 126;
                                             rectangle.Y = 36;
                                             break;
                                         default:
                                             rectangle.X = 144;
                                             rectangle.Y = 36;
                                             break;
                                         }
                                     }
                                     else if (upLeft != num && downLeft != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 180;
                                             rectangle.Y = 0;
                                             break;
                                         case 1:
                                             rectangle.X = 180;
                                             rectangle.Y = 18;
                                             break;
                                         default:
                                             rectangle.X = 180;
                                             rectangle.Y = 36;
                                             break;
                                         }
                                     }
                                     else if (upRight != num && downRight != num)
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 198;
                                             rectangle.Y = 0;
                                             break;
                                         case 1:
                                             rectangle.X = 198;
                                             rectangle.Y = 18;
                                             break;
                                         default:
                                             rectangle.X = 198;
                                             rectangle.Y = 36;
                                             break;
                                         }
                                     }
                                     else
{
                                         switch (num27)
{
                                         case 0:
                                             rectangle.X = 18;
                                             rectangle.Y = 18;
                                             break;
                                         case 1:
                                             rectangle.X = 36;
                                             rectangle.Y = 18;
                                             break;
                                         default:
                                             rectangle.X = 54;
                                             rectangle.Y = 18;
                                             break;
                                         }
                                     }
                                 }
                                 else if (up != num && down == num && left == num && right == num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 18;
                                         rectangle.Y = 0;
                                         break;
                                     case 1:
                                         rectangle.X = 36;
                                         rectangle.Y = 0;
                                         break;
                                     default:
                                         rectangle.X = 54;
                                         rectangle.Y = 0;
                                         break;
                                     }
                                 }
                                 else if (up == num && down != num && left == num && right == num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 18;
                                         rectangle.Y = 36;
                                         break;
                                     case 1:
                                         rectangle.X = 36;
                                         rectangle.Y = 36;
                                         break;
                                     default:
                                         rectangle.X = 54;
                                         rectangle.Y = 36;
                                         break;
                                     }
                                 }
                                 else if (up == num && down == num && left != num && right == num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 0;
                                         rectangle.Y = 0;
                                         break;
                                     case 1:
                                         rectangle.X = 0;
                                         rectangle.Y = 18;
                                         break;
                                     default:
                                         rectangle.X = 0;
                                         rectangle.Y = 36;
                                         break;
                                     }
                                 }
                                 else if (up == num && down == num && left == num && right != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 72;
                                         rectangle.Y = 0;
                                         break;
                                     case 1:
                                         rectangle.X = 72;
                                         rectangle.Y = 18;
                                         break;
                                     default:
                                         rectangle.X = 72;
                                         rectangle.Y = 36;
                                         break;
                                     }
                                 }
                                 else if (up != num && down == num && left != num && right == num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 0;
                                         rectangle.Y = 54;
                                         break;
                                     case 1:
                                         rectangle.X = 36;
                                         rectangle.Y = 54;
                                         break;
                                     default:
                                         rectangle.X = 72;
                                         rectangle.Y = 54;
                                         break;
                                     }
                                 }
                                 else if (up != num && down == num && left == num && right != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 18;
                                         rectangle.Y = 54;
                                         break;
                                     case 1:
                                         rectangle.X = 54;
                                         rectangle.Y = 54;
                                         break;
                                     default:
                                         rectangle.X = 90;
                                         rectangle.Y = 54;
                                         break;
                                     }
                                 }
                                 else if (up == num && down != num && left != num && right == num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 0;
                                         rectangle.Y = 72;
                                         break;
                                     case 1:
                                         rectangle.X = 36;
                                         rectangle.Y = 72;
                                         break;
                                     default:
                                         rectangle.X = 72;
                                         rectangle.Y = 72;
                                         break;
                                     }
                                 }
                                 else if (up == num && down != num && left == num && right != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 18;
                                         rectangle.Y = 72;
                                         break;
                                     case 1:
                                         rectangle.X = 54;
                                         rectangle.Y = 72;
                                         break;
                                     default:
                                         rectangle.X = 90;
                                         rectangle.Y = 72;
                                         break;
                                     }
                                 }
                                 else if (up == num && down == num && left != num && right != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 90;
                                         rectangle.Y = 0;
                                         break;
                                     case 1:
                                         rectangle.X = 90;
                                         rectangle.Y = 18;
                                         break;
                                     default:
                                         rectangle.X = 90;
                                         rectangle.Y = 36;
                                         break;
                                     }
                                 }
                                 else if (up != num && down != num && left == num && right == num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 108;
                                         rectangle.Y = 72;
                                         break;
                                     case 1:
                                         rectangle.X = 126;
                                         rectangle.Y = 72;
                                         break;
                                     default:
                                         rectangle.X = 144;
                                         rectangle.Y = 72;
                                         break;
                                     }
                                 }
                                 else if (up != num && down == num && left != num && right != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 108;
                                         rectangle.Y = 0;
                                         break;
                                     case 1:
                                         rectangle.X = 126;
                                         rectangle.Y = 0;
                                         break;
                                     default:
                                         rectangle.X = 144;
                                         rectangle.Y = 0;
                                         break;
                                     }
                                 }
                                 else if (up == num && down != num && left != num && right != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 108;
                                         rectangle.Y = 54;
                                         break;
                                     case 1:
                                         rectangle.X = 126;
                                         rectangle.Y = 54;
                                         break;
                                     default:
                                         rectangle.X = 144;
                                         rectangle.Y = 54;
                                         break;
                                     }
                                 }
                                 else if (up != num && down != num && left != num && right == num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 162;
                                         rectangle.Y = 0;
                                         break;
                                     case 1:
                                         rectangle.X = 162;
                                         rectangle.Y = 18;
                                         break;
                                     default:
                                         rectangle.X = 162;
                                         rectangle.Y = 36;
                                         break;
                                     }
                                 }
                                 else if (up != num && down != num && left == num && right != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 216;
                                         rectangle.Y = 0;
                                         break;
                                     case 1:
                                         rectangle.X = 216;
                                         rectangle.Y = 18;
                                         break;
                                     default:
                                         rectangle.X = 216;
                                         rectangle.Y = 36;
                                         break;
                                     }
                                 }
                                 else if (up != num && down != num && left != num && right != num)
{
                                     switch (num27)
{
                                     case 0:
                                         rectangle.X = 162;
                                         rectangle.Y = 54;
                                         break;
                                     case 1:
                                         rectangle.X = 180;
                                         rectangle.Y = 54;
                                         break;
                                     default:
                                         rectangle.X = 198;
                                         rectangle.Y = 54;
                                         break;
                                     }
                                 }
                             }
                             if (rectangle.X <= -1 || rectangle.Y <= -1)
{
                                 if (num27 <= 0)
{
                                     rectangle.X = 18;
                                     rectangle.Y = 18;
                                 }
                                 else if (num27 == 1)
{
                                     rectangle.X = 36;
                                     rectangle.Y = 18;
                                 }
                                 if (num27 >= 2)
{
                                     rectangle.X = 54;
                                     rectangle.Y = 18;
                                 }
                             }
                             if (Main.tileLargeFrames[num] == 1 && num27 == 3)
{
                                 rectangle.Y += 90;
                             }
                             if (Main.tileLargeFrames[num] == 2 && num27 == 3)
{
                                 rectangle.Y += 90;
                             }
                             tile.frameX = (short)rectangle.X;
                             tile.frameY = (short)rectangle.Y;
                             if (TileID.Sets.IsVine[num])
{
                                 up = ((tile2 == null) ? num : ((!tile2.nactive()) ? (-1) : ((!tile2.bottomSlope()) ? tile2.type : (-1))));
                                 if (num != up)
{
                                     bool num45 = up == 60 || up == 62;
                                     bool num46 = up == 109 || up == 115;
                                     bool flag9 = up == 23 || up == 636 || up == 661;
                                     bool flag10 = up == 199 || up == 205 || up == 662;
                                     bool flag11 = up == 2 || up == 52;
                                     bool flag12 = up == 382;
                                     bool num47 = up == 70 || up == 528;
                                     bool num48 = up == 633 || up == 638;
                                     ushort num49 = 0;
                                     if (num48)
{
                                         num49 = 638;
                                     }
                                     if (num47)
{
                                         num49 = 528;
                                     }
                                     if (num46)
{
                                         num49 = 115;
                                     }
                                     if (num45)
{
                                         num49 = 62;
                                     }
                                     if (flag9)
{
                                         num49 = 636;
                                     }
                                     if (flag10)
{
                                         num49 = 205;
                                     }
                                     if (flag11 && num != 382)
{
                                         num49 = 52;
                                     }
                                     if (flag12)
{
                                         num49 = 382;
                                     }
                                     if (num49 != 0 && num49 != num)
{
                                         tile.type = num49;
                                         SquareTileFrame(i, j);
                                         return;
                                     }
                                 }
                                 if (up != num)
{
                                     bool flag13 = false;
                                     if (up == -1)
{
                                         flag13 = true;
                                     }
                                     if (num == 52 && up != 2 && up != 192)
{
                                         flag13 = true;
                                     }
                                     if (num == 382 && up != 2 && up != 192)
{
                                         flag13 = true;
                                     }
                                     if (num == 62 && up != 60)
{
                                         flag13 = true;
                                     }
                                     if (num == 115 && up != 109)
{
                                         flag13 = true;
                                     }
                                     if (num == 528 && up != 70)
{
                                         flag13 = true;
                                     }
                                     if (num == 636 && up != 23 && up != 661)
{
                                         flag13 = true;
                                     }
                                     if (num == 205 && up != 199 && up != 662)
{
                                         flag13 = true;
                                     }
                                     if (num == 638 && up != 633)
{
                                         flag13 = true;
                                     }
                                     if (flag13)
{
                                         KillTile(i, j);
                                     }
                                 }
                             }
                             bool flag14 = false;
                             if (!noTileActions && tile.active() && TileID.Sets.Falling[num])
{
                                 SpawnFallingBlockProjectile(i, j, tile, tile2, tile3, num);
                             }
                             if ((rectangle.X != frameX && rectangle.Y != frameY && frameX >= 0 && frameY >= 0) || flag14)
{
                                 tileReframeCount++;
                                 if (tileReframeCount < 25)
{
                                     bool num50 = mergeUp;
                                     bool flag15 = mergeDown;
                                     bool flag16 = mergeLeft;
                                     bool flag17 = mergeRight;
                                     TileFrame(i - 1, j);
                                     TileFrame(i + 1, j);
                                     TileFrame(i, j - 1);
                                     TileFrame(i, j + 1);
                                     mergeUp = num50;
                                     mergeDown = flag15;
                                     mergeLeft = flag16;
                                     mergeRight = flag17;
                                 }
                                 tileReframeCount--;
                             }
                             goto end_IL_0002;
                         }
                         }
                     }
                     Framing.SelfFrame8Way(i, j, tile, resetFrame);
                     return;
                 }
             }
             end_IL_0002:;
         }
         catch
         {
         }
         if (i > 0 && j > 0)
         {
             UpdateMapTile(i, j, addToList);
         }
     }
References Tile.active(), TileID.Sets.AllTiles, TileID.Sets.Ash, TileID.Sets.BasicChest, TileID.Sets.BasicChestFake, TileID.Sets.BlockMergesWithMergeAllBlock, Tile.blockType(), Tile.bottomSlope(), TileID.Sets.ChecksForMerge, Tile.ClearBlockPaintAndCoating(), TileID.Count, WorldGen.TileMergeCullCache.Cull(), WorldGen.TileMergeCullCache.CullBottom, WorldGen.TileMergeCullCache.CullBottomLeft, WorldGen.TileMergeCullCache.CullBottomRight, WorldGen.TileMergeCullCache.CullLeft, WorldGen.TileMergeCullCache.CullRight, WorldGen.TileMergeCullCache.CullTop, WorldGen.TileMergeCullCache.CullTopLeft, WorldGen.TileMergeCullCache.CullTopRight, TileID.Sets.Dirt, TileID.Sets.Falling, TileID.Sets.ForcedDirtMerging, Tile.frameNumber(), Minecart.FrameTrack(), Tile.frameX, Tile.frameY, TEDisplayDoll.Framing_CheckTile(), TEHatRack.Framing_CheckTile(), TETeleportationPylon.Framing_CheckTile(), TEWeaponsRack.Framing_CheckTile(), TileID.Sets.Conversion.Grass, TileID.Sets.GrassSpecial, Tile.halfBrick(), TileID.Sets.HasSlopeFrames, TileID.Sets.HellSpecial, TileID.Sets.Ices, TileID.Sets.IcesSlush, TileID.Sets.IcesSnow, Tile.invisibleBlock(), TileID.Sets.IsBeam, TileID.Sets.IsVine, TileID.Sets.JungleSpecial, Tile.leftSlope(), Liquid, Tile.liquid, Main.maxTilesX, Main.maxTilesY, TileID.Sets.MergesWithClouds, TileID.Sets.Conversion.MergesWithDirtInASpecialWay, TileID.Sets.Mud, Tile.nactive(), TileID.Sets.NeedsGrassFraming, TileID.Sets.NeedsGrassFramingDirt, Main.netMode, TileID.Sets.Ore, TileID.Sets.OreMergesWithMud, TileID.Sets.Platforms, Tile.rightSlope(), Main.rockLayer, TileID.Sets.Conversion.Sand, Framing.SelfFrame8Way(), Main.ShouldShowInvisibleWalls(), Tile.slope(), TileID.Sets.Snow, Main.tile, Main.tileAlch, Main.tileBlendAll, Main.tileBrick, Main.tileFrameImportant, Main.tileLargeFrames, Main.tileMerge, Main.tileMergeDirt, Main.tileMoss, TileID.Sets.tileMossBrick, Main.tileNoAttach, Main.tilePile, Main.tileRope, Main.tileSolid, Main.tileSolidTop, Main.tileStone, Tile.topSlope(), Tile.type, and Tile.wall.
Referenced by DeadMansChestBiome.ActuallyPlaceBoulderTrap(), DeadMansChestBiome.ActuallyPlaceDartTrap(), DeadMansChestBiome.ActuallyPlaceExplosive(), WorldUtils.ClearTile(), TileFont.DrawChar(), Wiring.HitSwitch(), TileFont.HLineLabel(), WorldUtils.TileFrame(), and TileFont.VLineLabel().