Terraria: WorldGen.ReplaceWall
ReplaceWall()
static bool WorldGen.ReplaceWall (int x, int y, ushort targetWall) inline static
     {
         if (targetWall >= WallID.Count)
         {
             return false;
         }
         Tile tile = Main.tile[x, y];
         if (tile.wall == 0 || targetWall == 0)
         {
             return false;
         }
         if (KillWall_CheckFailure(fail: false, tile))
         {
             return false;
         }
         int num = 10;
         for (int i = 0; i < num; i++)
         {
             KillWall_MakeWallDust(x, y, tile);
         }
         KillWall_PlaySounds(x, y, tile);
         KillWall_DropItems(x, y, tile);
         tile.wall = targetWall;
         tile.ClearWallPaintAndCoating();
         SquareWallFrame(x, y);
         return true;
     }
References Tile.ClearWallPaintAndCoating(), WallID.Count, Main.tile, and Tile.wall.
Referenced by MessageBuffer.GetData(), and Player.PlaceThing_TryReplacingWalls().