Terraria: WorldGen.CheckOnTable1x1
CheckOnTable1x1()
static void WorldGen.CheckOnTable1x1 (int x, int y, int type) inline static
     {
         if (Main.tile[x, y + 1] == null)
         {
             return;
         }
         if (Main.tile[x, y + 1].topSlope())
         {
             if (TileID.Sets.Platforms[Main.tile[x, y + 1].type])
             {
                 if ((Main.tile[x, y + 1].blockType() != 3 || !Main.tile[x - 1, y + 1].active() || Main.tile[x - 1, y + 1].blockType() != 0 || !TileID.Sets.Platforms[Main.tile[x - 1, y + 1].type]) && (Main.tile[x, y + 1].blockType() != 2 || !Main.tile[x + 1, y + 1].active() || Main.tile[x + 1, y + 1].blockType() != 0 || !TileID.Sets.Platforms[Main.tile[x + 1, y + 1].type]))
                 {
                     KillTile(x, y);
                 }
             }
             else
             {
                 KillTile(x, y);
             }
         }
         else
         {
             if (Main.tile[x, y + 1].active() && Main.tileTable[Main.tile[x, y + 1].type] && !Main.tile[x, y + 1].halfBrick())
             {
                 return;
             }
             if (type == 78)
             {
                 if (!SolidTileAllowBottomSlope(x, y + 1))
                 {
                     KillTile(x, y);
                 }
             }
             else
             {
                 KillTile(x, y);
             }
         }
     }
References Tile.active(), Tile.blockType(), Tile.halfBrick(), TileID.Sets.Platforms, Main.tile, Main.tileTable, Tile.topSlope(), and Tile.type.