Terraria: WorldGen.CheckLilyPad
CheckLilyPad()
static void WorldGen.CheckLilyPad (int x, int y) inline static
     {
         if (Main.netMode == 1)
         {
             return;
         }
         if (Main.tile[x, y].liquidType() != 0)
         {
             KillTile(x, y);
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, x, y);
             }
             return;
         }
         int num = y;
         while ((!Main.tile[x, num].active() || !Main.tileSolid[Main.tile[x, num].type] || Main.tileSolidTop[Main.tile[x, num].type]) && num < Main.maxTilesY - 50)
         {
             num++;
             if (Main.tile[x, num] == null)
             {
                 return;
             }
         }
         int type = Main.tile[x, num].type;
         int num2 = -1;
         if (type == 2 || type == 477)
         {
             num2 = 0;
         }
         if (type == 109 || type == 109 || type == 116)
         {
             num2 = 18;
         }
         if (type == 60)
         {
             num2 = 36;
         }
         if (num2 >= 0)
         {
             if (num2 != Main.tile[x, y].frameY)
             {
                 Main.tile[x, y].frameY = (short)num2;
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
             }
             if (Main.tile[x, y - 1].liquid > 0 && !Main.tile[x, y - 1].active())
             {
                 Main.tile[x, y - 1].active(active: true);
                 Main.tile[x, y - 1].type = 518;
                 Main.tile[x, y - 1].frameX = Main.tile[x, y].frameX;
                 Main.tile[x, y - 1].frameY = Main.tile[x, y].frameY;
                 Main.tile[x, y - 1].halfBrick(halfBrick: false);
                 Main.tile[x, y - 1].slope(0);
                 Main.tile[x, y].active(active: false);
                 Main.tile[x, y].type = 0;
                 SquareTileFrame(x, y - 1, resetFrame: false);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y - 1, 1, 2);
                 }
             }
             else
             {
                 if (Main.tile[x, y].liquid != 0)
                 {
                     return;
                 }
                 Tile tileSafely = Framing.GetTileSafely(x, y + 1);
                 if (!tileSafely.active())
                 {
                     Main.tile[x, y + 1].active(active: true);
                     Main.tile[x, y + 1].type = 518;
                     Main.tile[x, y + 1].frameX = Main.tile[x, y].frameX;
                     Main.tile[x, y + 1].frameY = Main.tile[x, y].frameY;
                     Main.tile[x, y + 1].halfBrick(halfBrick: false);
                     Main.tile[x, y + 1].slope(0);
                     Main.tile[x, y].active(active: false);
                     Main.tile[x, y].type = 0;
                     SquareTileFrame(x, y + 1, resetFrame: false);
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendTileSquare(-1, x, y, 1, 2);
                     }
                 }
                 else if (tileSafely.active() && !TileID.Sets.Platforms[tileSafely.type] && (!Main.tileSolid[tileSafely.type] || Main.tileSolidTop[tileSafely.type]))
                 {
                     KillTile(x, y);
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendData(17, -1, -1, null, 0, x, y);
                     }
                 }
             }
         }
         else
         {
             KillTile(x, y);
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, x, y);
             }
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Framing.GetTileSafely(), Tile.halfBrick(), Tile.liquid, Tile.liquidType(), Main.maxTilesY, Main.netMode, TileID.Sets.Platforms, NetMessage.SendData(), NetMessage.SendTileSquare(), Tile.slope(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by Liquid.DelWater().