Terraria: System.Xml.XmlSubtreeReader.SkipAsync
SkipAsync()
override async Task System.Xml.XmlSubtreeReader.SkipAsync () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 1433 of file XmlSubtreeReader.cs.
    {
        switch (_state)
        {
        case State.Initial:
            await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
            break;
        case State.Interactive:
            _curNsAttr = -1;
            _useCurNode = false;
            reader.MoveToElement();
            if (reader.Depth == _initialDepth)
            {
                if (reader.NodeType == XmlNodeType.Element && !reader.IsEmptyElement && await reader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false))
                {
                    while (reader.NodeType != XmlNodeType.EndElement && reader.Depth > _initialDepth)
                    {
                        await reader.SkipAsync().ConfigureAwait(continueOnCapturedContext: false);
                    }
                }
                _state = State.EndOfFile;
                SetEmptyNode();
            }
            else
            {
                if (reader.NodeType == XmlNodeType.Element && !reader.IsEmptyElement)
                {
                    _nsManager.PopScope();
                }
                await reader.SkipAsync().ConfigureAwait(continueOnCapturedContext: false);
                ProcessNamespaces();
            }
            break;
        case State.EndOfFile:
        case State.Closed:
            break;
        case State.PopNamespaceScope:
            _nsManager.PopScope();
            goto case State.ClearNsAttributes;
        case State.ClearNsAttributes:
            _nsAttrCount = 0;
            _state = State.Interactive;
            goto case State.Interactive;
        case State.ReadElementContentAsBase64:
        case State.ReadElementContentAsBinHex:
            if (await FinishReadElementContentAsBinaryAsync().ConfigureAwait(continueOnCapturedContext: false))
            {
                await SkipAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            break;
        case State.ReadContentAsBase64:
        case State.ReadContentAsBinHex:
            if (await FinishReadContentAsBinaryAsync().ConfigureAwait(continueOnCapturedContext: false))
            {
                await SkipAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            break;
        case State.Error:
            break;
        }
    }
References System.Xml.XmlSubtreeReader._curNsAttr, System.Xml.XmlSubtreeReader._initialDepth, System.Xml.XmlSubtreeReader._nsAttrCount, System.Xml.XmlSubtreeReader._nsManager, System.Xml.XmlSubtreeReader._state, System.Xml.XmlSubtreeReader._useCurNode, System.Xml.XmlReader.Depth, System.Xml.XmlSubtreeReader.FinishReadContentAsBinaryAsync(), System.Xml.XmlSubtreeReader.FinishReadElementContentAsBinaryAsync(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.NodeType, System.Xml.XmlNamespaceManager.PopScope(), System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlReader.ReadAsync(), System.Xml.XmlSubtreeReader.ReadAsync(), System.Xml.XmlWrappingReader.reader, System.Xml.XmlSubtreeReader.SetEmptyNode(), System.Xml.XmlReader.SkipAsync(), and System.Xml.XmlSubtreeReader.SkipAsync().
Referenced by System.Xml.XmlSubtreeReader.SkipAsync().