Terraria: WorldGen.serverLoadWorldCallBack
serverLoadWorldCallBack()
static void WorldGen.serverLoadWorldCallBack () inline static
     {
         Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
         WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
         if (loadFailed || !loadSuccess)
         {
             WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
             if (loadFailed || !loadSuccess)
             {
                 bool isCloudSave = Main.ActiveWorldFileData.IsCloudSave;
                 if (FileUtilities.Exists(Main.worldPathName + ".bak", isCloudSave))
                 {
                     worldBackup = true;
                 }
                 else
                 {
                     worldBackup = false;
                 }
                 if (!Main.dedServ)
                 {
                     if (worldBackup)
                     {
                         Main.menuMode = 200;
                     }
                     else
                     {
                         Main.menuMode = 201;
                     }
                     return;
                 }
                 if (!worldBackup)
                 {
                     Console.WriteLine(Language.GetTextValue("Error.LoadFailedNoBackup"));
                     return;
                 }
                 FileUtilities.Copy(Main.worldPathName + ".bak", Main.worldPathName, isCloudSave);
                 FileUtilities.Delete(Main.worldPathName + ".bak", isCloudSave);
                 WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
                 if (loadFailed || !loadSuccess)
                 {
                     WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
                     if (loadFailed || !loadSuccess)
                     {
                         Console.WriteLine(Language.GetTextValue("Error.LoadFailed"));
                         return;
                     }
                 }
             }
         }
         _lastSeed = Main.ActiveWorldFileData.Seed;
         SoundEngine.PlaySound(10);
         WorldFile.SetOngoingToTemps();
         Hooks.WorldLoaded();
     }
References _lastSeed, Main.ActiveWorldFileData, FileUtilities.Copy(), Main.dedServ, FileUtilities.Delete(), FileUtilities.Exists(), Language.GetTextValue(), FileData.IsCloudSave, loadFailed, loadSuccess, WorldFile.LoadWorld(), Main.menuMode, SoundEngine.PlaySound(), Main.rand, WorldFileData.Seed, WorldFile.SetOngoingToTemps(), worldBackup, WorldGen.Hooks.WorldLoaded(), and Main.worldPathName.
Referenced by serverLoadWorld().