Terraria: WorldGen.Place3x2
Place3x2()
static void WorldGen.Place3x2 (int x, int y, ushort type, int style = 0) inline static
     {
         if (x < 5 || x > Main.maxTilesX - 5 || y < 5 || y > Main.maxTilesY - 5)
         {
             return;
         }
         bool flag = false;
         bool flag2 = true;
         if (type == 14 && style == 25)
         {
             flag = true;
         }
         int num = y - 1;
         if (flag)
         {
             num = y;
         }
         for (int i = x - 1; i < x + 2; i++)
         {
             for (int j = num; j < y + 1; j++)
             {
                 if (Main.tile[i, j] == null)
                 {
                     Main.tile[i, j] = new Tile();
                 }
                 if (Main.tile[i, j].active())
                 {
                     flag2 = false;
                 }
                 if (type == 215 && Main.tile[i, j].liquid > 0)
                 {
                     flag2 = false;
                 }
             }
             if (Main.tile[i, y + 1] == null)
             {
                 Main.tile[i, y + 1] = new Tile();
             }
             switch (type)
             {
             default:
                 if (type != 582 && type != 619)
                 {
                     if (type == 26 && TileID.Sets.Boulders[Main.tile[i, y + 1].type])
                     {
                         flag2 = false;
                     }
                     if (!SolidTile2(i, y + 1))
                     {
                         flag2 = false;
                     }
                     break;
                 }
                 goto case 285;
             case 285:
             case 286:
             case 298:
             case 299:
             case 310:
             case 361:
             case 362:
             case 363:
             case 364:
                 if (!SolidTile2(i, y + 1) && (!Main.tile[i, y + 1].nactive() || !Main.tileSolidTop[Main.tile[i, y + 1].type] || Main.tile[i, y + 1].frameY != 0))
                 {
                     flag2 = false;
                 }
                 break;
             }
         }
         if (type == 88)
         {
             if (Chest.CreateChest(x - 1, y - 1) == -1)
             {
                 flag2 = false;
             }
             else if (Main.netMode == 1)
             {
                 NetMessage.SendData(34, -1, -1, null, 2, x, y, style);
             }
         }
         if (flag2)
         {
             short num2 = (short)(54 * style);
             if (flag)
             {
                 Main.tile[x - 1, y].active(active: true);
                 Main.tile[x - 1, y].frameY = 0;
                 Main.tile[x - 1, y].frameX = num2;
                 Main.tile[x - 1, y].type = type;
                 Main.tile[x, y].active(active: true);
                 Main.tile[x, y].frameY = 0;
                 Main.tile[x, y].frameX = (short)(num2 + 18);
                 Main.tile[x, y].type = type;
                 Main.tile[x + 1, y].active(active: true);
                 Main.tile[x + 1, y].frameY = 0;
                 Main.tile[x + 1, y].frameX = (short)(num2 + 36);
                 Main.tile[x + 1, y].type = type;
                 return;
             }
             Main.tile[x - 1, y - 1].active(active: true);
             Main.tile[x - 1, y - 1].frameY = 0;
             Main.tile[x - 1, y - 1].frameX = num2;
             Main.tile[x - 1, y - 1].type = type;
             Main.tile[x, y - 1].active(active: true);
             Main.tile[x, y - 1].frameY = 0;
             Main.tile[x, y - 1].frameX = (short)(num2 + 18);
             Main.tile[x, y - 1].type = type;
             Main.tile[x + 1, y - 1].active(active: true);
             Main.tile[x + 1, y - 1].frameY = 0;
             Main.tile[x + 1, y - 1].frameX = (short)(num2 + 36);
             Main.tile[x + 1, y - 1].type = type;
             Main.tile[x - 1, y].active(active: true);
             Main.tile[x - 1, y].frameY = 18;
             Main.tile[x - 1, y].frameX = num2;
             Main.tile[x - 1, y].type = type;
             Main.tile[x, y].active(active: true);
             Main.tile[x, y].frameY = 18;
             Main.tile[x, y].frameX = (short)(num2 + 18);
             Main.tile[x, y].type = type;
             Main.tile[x + 1, y].active(active: true);
             Main.tile[x + 1, y].frameY = 18;
             Main.tile[x + 1, y].frameX = (short)(num2 + 36);
             Main.tile[x + 1, y].type = type;
         }
     }
References Tile.active(), TileID.Sets.Boulders, Chest.CreateChest(), Tile.frameX, Tile.frameY, Tile.liquid, Main.maxTilesX, Main.maxTilesY, Tile.nactive(), Main.netMode, NetMessage.SendData(), Main.tile, Main.tileSolidTop, and Tile.type.