Terraria: WorldGen.KillWall
KillWall()
static void WorldGen.KillWall (int i, int j, bool fail = false) inline static
     {
         if (i < 0 || j < 0 || i >= Main.maxTilesX || j >= Main.maxTilesY)
         {
             return;
         }
         Tile tile = Main.tile[i, j];
         if (tile == null)
         {
             tile = new Tile();
             Main.tile[i, j] = tile;
         }
         if (tile.wall <= 0)
         {
             return;
         }
         fail = KillWall_CheckFailure(fail, tile);
         KillWall_PlaySounds(i, j, tile);
         int num = 10;
         if (fail)
         {
             num = 3;
         }
         for (int k = 0; k < num; k++)
         {
             KillWall_MakeWallDust(i, j, tile);
         }
         if (fail)
         {
             SquareWallFrame(i, j);
             return;
         }
         KillWall_DropItems(i, j, tile);
         tile.wall = 0;
         tile.ClearWallPaintAndCoating();
         SquareWallFrame(i, j);
         if (tile.type >= 0 && tile.type < TileID.Count && TileID.Sets.FramesOnKillWall[tile.type])
         {
             TileFrame(i, j);
         }
     }
References Tile.ClearWallPaintAndCoating(), TileID.Count, TileID.Sets.FramesOnKillWall, Main.maxTilesX, Main.maxTilesY, Main.tile, Tile.type, and Tile.wall.
Referenced by Projectile.ExplodeTiles(), MessageBuffer.GetData(), and Player.PickWall().