Terraria: WorldGen.PlantCheck
PlantCheck()
static void WorldGen.PlantCheck (int x, int y) inline static
     {
         x = Utils.Clamp(x, 1, Main.maxTilesX - 2);
         y = Utils.Clamp(y, 1, Main.maxTilesY - 2);
         for (int i = x - 1; i <= x + 1; i++)
         {
             for (int j = y - 1; j <= y + 1; j++)
             {
                 if (Main.tile[i, j] == null)
                 {
                     return;
                 }
             }
         }
         int num = -1;
         int num2 = Main.tile[x, y].type;
         _ = x - 1;
         _ = 0;
         _ = x + 1;
         _ = Main.maxTilesX;
         _ = y - 1;
         _ = 0;
         if (y + 1 >= Main.maxTilesY)
         {
             num = num2;
         }
         if (x - 1 >= 0 && Main.tile[x - 1, y] != null && Main.tile[x - 1, y].nactive())
         {
             _ = Main.tile[x - 1, y].type;
         }
         if (x + 1 < Main.maxTilesX && Main.tile[x + 1, y] != null && Main.tile[x + 1, y].nactive())
         {
             _ = Main.tile[x + 1, y].type;
         }
         if (y - 1 >= 0 && Main.tile[x, y - 1] != null && Main.tile[x, y - 1].nactive())
         {
             _ = Main.tile[x, y - 1].type;
         }
         if (y + 1 < Main.maxTilesY && Main.tile[x, y + 1] != null && Main.tile[x, y + 1].nactive() && !Main.tile[x, y + 1].halfBrick() && Main.tile[x, y + 1].slope() == 0)
         {
             num = Main.tile[x, y + 1].type;
         }
         if (x - 1 >= 0 && y - 1 >= 0 && Main.tile[x - 1, y - 1] != null && Main.tile[x - 1, y - 1].nactive())
         {
             _ = Main.tile[x - 1, y - 1].type;
         }
         if (x + 1 < Main.maxTilesX && y - 1 >= 0 && Main.tile[x + 1, y - 1] != null && Main.tile[x + 1, y - 1].nactive())
         {
             _ = Main.tile[x + 1, y - 1].type;
         }
         if (x - 1 >= 0 && y + 1 < Main.maxTilesY && Main.tile[x - 1, y + 1] != null && Main.tile[x - 1, y + 1].nactive())
         {
             _ = Main.tile[x - 1, y + 1].type;
         }
         if (x + 1 < Main.maxTilesX && y + 1 < Main.maxTilesY && Main.tile[x + 1, y + 1] != null && Main.tile[x + 1, y + 1].nactive())
         {
             _ = Main.tile[x + 1, y + 1].type;
         }
         if ((num2 != 3 || num == 2 || num == 477 || num == 78 || num == 380 || num == 579) && (num2 != 73 || num == 2 || num == 477 || num == 78 || num == 380 || num == 579) && (num2 != 24 || num == 23 || num == 661) && (num2 != 61 || num == 60) && (num2 != 74 || num == 60) && (num2 != 71 || num == 70) && (num2 != 110 || num == 109 || num == 492) && (num2 != 113 || num == 109 || num == 492) && (num2 != 201 || num == 199 || num == 662) && (num2 != 637 || num == 633))
         {
             return;
         }
         bool flag = false;
         if (num2 == 3 || num2 == 110 || num2 == 24)
         {
             flag = Main.tile[x, y].frameX == 144;
         }
         if (num2 == 201)
         {
             flag = Main.tile[x, y].frameX == 270;
         }
         if ((num2 == 3 || num2 == 73) && num != 2 && num != 477 && Main.tile[x, y].frameX >= 162)
         {
             Main.tile[x, y].frameX = 126;
         }
         if (num2 == 74 && num != 60 && Main.tile[x, y].frameX >= 162)
         {
             Main.tile[x, y].frameX = 126;
         }
         switch (num)
         {
         case 23:
         case 661:
             num2 = 24;
             if (Main.tile[x, y].frameX >= 162)
             {
                 Main.tile[x, y].frameX = 126;
             }
             break;
         case 2:
         case 477:
             num2 = ((num2 != 113) ? 3 : 73);
             break;
         case 109:
         case 492:
             num2 = ((num2 != 73) ? 110 : 113);
             break;
         case 199:
         case 662:
             num2 = 201;
             break;
         case 60:
             num2 = 61;
             while (Main.tile[x, y].frameX > 126)
             {
                 Main.tile[x, y].frameX -= 126;
             }
             break;
         case 70:
             num2 = 71;
             while (Main.tile[x, y].frameX > 72)
             {
                 Main.tile[x, y].frameX -= 72;
             }
             break;
         }
         if (num2 != Main.tile[x, y].type)
         {
             Main.tile[x, y].type = (ushort)num2;
             if (flag)
             {
                 Main.tile[x, y].frameX = 144;
                 if (num2 == 201)
                 {
                     Main.tile[x, y].frameX = 270;
                 }
             }
         }
         else
         {
             KillTile(x, y);
         }
     }
References Tile.frameX, Tile.halfBrick(), Main.maxTilesX, Main.maxTilesY, Tile.nactive(), Tile.slope(), Main.tile, and Tile.type.