Terraria: System.Xml.XmlSubtreeReader.ReadElementContentAsBase64Async
ReadElementContentAsBase64Async()
override async Task< int > System.Xml.XmlSubtreeReader.ReadElementContentAsBase64Async (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 1615 of file XmlSubtreeReader.cs.
    {
        switch (_state)
        {
        case State.Initial:
        case State.Error:
        case State.EndOfFile:
        case State.Closed:
            return 0;
        case State.Interactive:
        case State.PopNamespaceScope:
        case State.ClearNsAttributes:
            if (!(await InitReadElementContentAsBinaryAsync(State.ReadElementContentAsBase64).ConfigureAwait(continueOnCapturedContext: false)))
            {
                return 0;
            }
            goto case State.ReadElementContentAsBase64;
        case State.ReadElementContentAsBase64:
        {
            int num = await reader.ReadContentAsBase64Async(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
            if (num > 0 || count == 0)
            {
                return num;
            }
            if (NodeType != XmlNodeType.EndElement)
            {
                throw new XmlException(System.SR.Xml_InvalidNodeType, reader.NodeType.ToString(), reader as IXmlLineInfo);
            }
            _state = State.Interactive;
            ProcessNamespaces();
            if (reader.Depth != _initialDepth)
            {
                await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            else
            {
                _state = State.EndOfFile;
                SetEmptyNode();
            }
            return 0;
        }
        case State.ReadElementContentAsBinHex:
        case State.ReadContentAsBase64:
        case State.ReadContentAsBinHex:
            throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
        default:
            return 0;
        }
    }
References System.Xml.XmlSubtreeReader._initialDepth, System.Xml.XmlSubtreeReader._state, System.buffer, System.count, System.Xml.XmlReader.Depth, System.index, System.Xml.XmlSubtreeReader.InitReadElementContentAsBinaryAsync(), System.Xml.XmlReader.NodeType, System.Xml.XmlSubtreeReader.NodeType, System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlSubtreeReader.ReadAsync(), System.Xml.XmlReader.ReadContentAsBase64Async(), System.Xml.XmlWrappingReader.reader, System.Xml.XmlSubtreeReader.SetEmptyNode(), System.SR.Xml_InvalidNodeType, System.SR.Xml_MixingBinaryContentMethods, and System.Xml.XmlException.