Terraria: WorldGen.nextCount
nextCount()
static void WorldGen.nextCount (int x, int y, bool jungle = false, bool lavaOk = false) inline static
     {
         if (numTileCount >= maxTileCount)
         {
             return;
         }
         if (x <= 1 || x >= Main.maxTilesX - 1 || y <= 1 || y >= Main.maxTilesY - 1)
         {
             numTileCount = maxTileCount;
         }
         else
         {
             if (CountedTiles.ContainsKey(new Point(x, y)))
             {
                 return;
             }
             if (Main.tile[x, y].wall == 244)
             {
                 numTileCount = maxTileCount;
                 return;
             }
             if (Main.tile[x, y].shimmer() && Main.tile[x, y].liquid > 0)
             {
                 numTileCount = maxTileCount;
                 return;
             }
             if (!jungle)
             {
                 if (Main.tile[x, y].wall != 0)
                 {
                     numTileCount = maxTileCount;
                     return;
                 }
                 if (!lavaOk)
                 {
                     if (Main.tile[x, y].lava() && Main.tile[x, y].liquid > 0)
                     {
                         lavaCount++;
                         numTileCount = maxTileCount;
                         return;
                     }
                 }
                 else if (Main.tile[x, y].lava() && Main.tile[x, y].liquid > 0)
                 {
                     lavaCount++;
                 }
             }
             if (Main.tile[x, y].active())
             {
                 if (Main.tile[x, y].type == 70)
                 {
                     shroomCount++;
                 }
                 if (Main.tile[x, y].type == 1)
                 {
                     rockCount++;
                 }
                 if (Main.tile[x, y].type == 147 || Main.tile[x, y].type == 161)
                 {
                     iceCount++;
                 }
                 if (Main.tile[x, y].type == 53 || Main.tile[x, y].type == 396 || Main.tile[x, y].type == 397)
                 {
                     sandCount++;
                 }
             }
             if (!SolidTile(x, y))
             {
                 CountedTiles.Add(new Point(x, y), value: true);
                 numTileCount++;
                 nextCount(x - 1, y, jungle, lavaOk);
                 nextCount(x + 1, y, jungle, lavaOk);
                 nextCount(x, y - 1, jungle, lavaOk);
                 nextCount(x, y + 1, jungle, lavaOk);
             }
         }
     }
References Tile.active(), CountedTiles, iceCount, Tile.lava(), lavaCount, Tile.liquid, maxTileCount, Main.maxTilesX, Main.maxTilesY, numTileCount, rockCount, sandCount, Tile.shimmer(), shroomCount, SolidTile(), Main.tile, Tile.type, and Tile.wall.
Referenced by countTiles().