Terraria: WorldGen.StartImpendingDoom
StartImpendingDoom()
static void WorldGen.StartImpendingDoom (int countdownTime) inline static
     {
         NPC.LunarApocalypseIsUp = false;
         NPC.MaxMoonLordCountdown = countdownTime;
         NPC.MoonLordCountdown = NPC.MaxMoonLordCountdown;
         NetMessage.SendData(103);
         BroadcastText(NetworkText.FromKey(Lang.misc[52].Key), 50, 255, 130);
         if (Main.netMode != 1)
         {
             GetRidOfCultists();
         }
     }
References NetworkText.FromKey(), LocalizedText.Key, NPC.LunarApocalypseIsUp, NPC.MaxMoonLordCountdown, Lang.misc, NPC.MoonLordCountdown, Main.netMode, and NetMessage.SendData().
Referenced by MessageBuffer.GetData(), and Player.ItemCheck_UseEventItems().