Terraria: WorldGen.SpawnTravelNPC
SpawnTravelNPC()
static void WorldGen.SpawnTravelNPC () inline static
     {
         if (Main.eclipse || !Main.dayTime || (Main.invasionType > 0 && Main.invasionDelay == 0 && Main.invasionSize > 0))
         {
             return;
         }
         for (int i = 0; i < 200; i++)
         {
             if (Main.npc[i].active && Main.npc[i].type == 368)
             {
                 return;
             }
         }
         Chest.SetupTravelShop();
         NetMessage.SendTravelShop(-1);
         int num = 0;
         int[] array = new int[200];
         int num2 = 0;
         for (int j = 0; j < 200; j++)
         {
             if (Main.npc[j].active && Main.npc[j].townNPC && Main.npc[j].type != 37 && !Main.npc[j].homeless)
             {
                 array[num2] = j;
                 num2++;
             }
         }
         if (num2 == 0)
         {
             return;
         }
         num = array[Main.rand.Next(num2)];
         bestX = Main.npc[num].homeTileX;
         bestY = Main.npc[num].homeTileY;
         int minValue = bestX;
         int num3 = bestX;
         int num4 = bestY;
         int num5 = bestX;
         while (num5 > bestX - 10 && (SolidTile(num5, num4) || Main.tileSolidTop[Main.tile[num5, num4].type]) && (!Main.tile[num5, num4 - 1].active() || !Main.tileSolid[Main.tile[num5, num4 - 1].type] || Main.tileSolidTop[Main.tile[num5, num4 - 1].type]) && (!Main.tile[num5, num4 - 2].active() || !Main.tileSolid[Main.tile[num5, num4 - 2].type] || Main.tileSolidTop[Main.tile[num5, num4 - 2].type]) && (!Main.tile[num5, num4 - 3].active() || !Main.tileSolid[Main.tile[num5, num4 - 3].type] || Main.tileSolidTop[Main.tile[num5, num4 - 3].type]))
         {
             minValue = num5;
             num5--;
         }
         for (int k = bestX; k < bestX + 10 && (SolidTile(k, num4) || Main.tileSolidTop[Main.tile[k, num4].type]) && (!Main.tile[k, num4 - 1].active() || !Main.tileSolid[Main.tile[k, num4 - 1].type] || Main.tileSolidTop[Main.tile[k, num4 - 1].type]) && (!Main.tile[k, num4 - 2].active() || !Main.tileSolid[Main.tile[k, num4 - 2].type] || Main.tileSolidTop[Main.tile[k, num4 - 2].type]) && (!Main.tile[k, num4 - 3].active() || !Main.tileSolid[Main.tile[k, num4 - 3].type] || Main.tileSolidTop[Main.tile[k, num4 - 3].type]); k++)
         {
             num3 = k;
         }
         for (int l = 0; l < 30; l++)
         {
             int num6 = Main.rand.Next(minValue, num3 + 1);
             if (l < 20)
             {
                 if (num6 < bestX - 1 || num6 > bestX + 1)
                 {
                     bestX = num6;
                     break;
                 }
             }
             else if (num6 != bestX)
             {
                 bestX = num6;
                 break;
             }
         }
         int num7 = bestX;
         int num8 = bestY;
         bool flag = false;
         if (!flag && !((double)num8 > Main.worldSurface))
         {
             for (int m = 20; m < 500; m++)
             {
                 for (int n = 0; n < 2; n++)
                 {
                     num7 = ((n != 0) ? (bestX - m * 2) : (bestX + m * 2));
                     if (num7 > 10 && num7 < Main.maxTilesX - 10)
                     {
                         int num9 = bestY - m;
                         double num10 = bestY + m;
                         if (num9 < 10)
{
                             num9 = 10;
                         }
                         if (num10 > Main.worldSurface)
{
                             num10 = Main.worldSurface;
                         }
                         for (int num11 = num9; (double)num11 < num10; num11++)
{
                             num8 = num11;
                             if (!Main.tile[num7, num8].nactive() || !Main.tileSolid[Main.tile[num7, num8].type])
{
                                 continue;
                             }
                             if (Main.tile[num7, num8 - 3].liquid != 0 || Main.tile[num7, num8 - 2].liquid != 0 || Main.tile[num7, num8 - 1].liquid != 0 || Collision.SolidTiles(num7 - 1, num7 + 1, num8 - 3, num8 - 1))
{
                                 break;
                             }
                             flag = true;
                             Rectangle value = new Rectangle(num7 * 16 + 8 - NPC.sWidth / 2 - NPC.safeRangeX, num8 * 16 + 8 - NPC.sHeight / 2 - NPC.safeRangeY, NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                             for (int num12 = 0; num12 < 255; num12++)
{
                                 if (Main.player[num12].active && new Rectangle((int)Main.player[num12].position.X, (int)Main.player[num12].position.Y, Main.player[num12].width, Main.player[num12].height).Intersects(value))
{
                                     flag = false;
                                     break;
                                 }
                             }
                             break;
                         }
                     }
                     if (flag)
                     {
                         break;
                     }
                 }
                 if (flag)
                 {
                     break;
                 }
             }
         }
         int num13 = NPC.NewNPC(NPC.GetSpawnSourceForTownSpawn(), num7 * 16, num8 * 16, 368, 1);
         Main.npc[num13].homeTileX = bestX;
         Main.npc[num13].homeTileY = bestY;
         Main.npc[num13].homeless = true;
         if (num7 < bestX)
         {
             Main.npc[num13].direction = 1;
         }
         else if (num7 > bestX)
         {
             Main.npc[num13].direction = -1;
         }
         Main.npc[num13].netUpdate = true;
         string fullName = Main.npc[num13].FullName;
         if (Main.netMode == 0)
         {
             Main.NewText(Language.GetTextValue("Announcement.HasArrived", fullName), 50, 125);
         }
         else if (Main.netMode == 2)
         {
             ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasArrived", Main.npc[num13].GetFullNetName()), new Color(50, 125, 255));
         }
     }
References Entity.active, Tile.active(), bestX, bestY, ChatHelper.BroadcastChatMessage(), Color, Main.dayTime, Entity.direction, Main.eclipse, NetworkText.FromKey(), NPC.FullName, NPC.GetFullNetName(), NPC.GetSpawnSourceForTownSpawn(), Language.GetTextValue(), Entity.height, NPC.homeless, NPC.homeTileX, NPC.homeTileY, Main.invasionDelay, Main.invasionSize, Main.invasionType, Tile.liquid, Main.maxTilesX, Tile.nactive(), Main.netMode, NPC.netUpdate, NPC.NewNPC(), Main.NewText(), UnifiedRandom.Next(), Main.npc, Main.player, Entity.position, Main.rand, NPC.safeRangeX, NPC.safeRangeY, NetMessage.SendTravelShop(), Chest.SetupTravelShop(), NPC.sHeight, SolidTile(), Collision.SolidTiles(), NPC.sWidth, Main.tile, Main.tileSolid, Main.tileSolidTop, NPC.townNPC, NPC.type, Tile.type, Entity.width, and Main.worldSurface.
Referenced by Main.UpdateTime().