Terraria: System.Xml.XmlSubtreeReader.FinishReadContentAsType
FinishReadContentAsType()
void System.Xml.XmlSubtreeReader.FinishReadContentAsType () inline private
Definition at line 1335 of file XmlSubtreeReader.cs.
    {
        switch (NodeType)
        {
        case XmlNodeType.Element:
            ProcessNamespaces();
            break;
        case XmlNodeType.EndElement:
            _state = State.PopNamespaceScope;
            break;
        }
    }
References System.Xml.XmlSubtreeReader._state, System.Xml.XmlSubtreeReader.NodeType, and System.Xml.XmlSubtreeReader.ProcessNamespaces().
Referenced by System.Xml.XmlSubtreeReader.ReadContentAs(), System.Xml.XmlSubtreeReader.ReadContentAsAsync(), System.Xml.XmlSubtreeReader.ReadContentAsBoolean(), System.Xml.XmlSubtreeReader.ReadContentAsDateTime(), System.Xml.XmlSubtreeReader.ReadContentAsDecimal(), System.Xml.XmlSubtreeReader.ReadContentAsDouble(), System.Xml.XmlSubtreeReader.ReadContentAsFloat(), System.Xml.XmlSubtreeReader.ReadContentAsInt(), System.Xml.XmlSubtreeReader.ReadContentAsLong(), System.Xml.XmlSubtreeReader.ReadContentAsObject(), System.Xml.XmlSubtreeReader.ReadContentAsObjectAsync(), System.Xml.XmlSubtreeReader.ReadContentAsString(), and System.Xml.XmlSubtreeReader.ReadContentAsStringAsync().