Terraria: WorldGen.randGemTile
randGemTile()
static ushort WorldGen.randGemTile () inline static
     {
         if (genRand.Next(20) != 0)
         {
             return 1;
         }
         return (ushort)randGem() switch
         {
             0 => 67,
             1 => 66,
             2 => 63,
             3 => 65,
             4 => 64,
             _ => 68,
         };
     }
References genRand, UnifiedRandom.Next(), and randGem().
Referenced by WorldGen.Spread.Gem().