Terraria: System.Xml.XmlSubtreeReader.InitReadContentAsType
InitReadContentAsType()
void System.Xml.XmlSubtreeReader.InitReadContentAsType (string methodName) inline private
Definition at line 1311 of file XmlSubtreeReader.cs.
    {
        switch (_state)
        {
        case State.Initial:
        case State.Error:
        case State.EndOfFile:
        case State.Closed:
            throw new InvalidOperationException(System.SR.Xml_ClosedOrErrorReader);
        case State.Interactive:
            break;
        case State.PopNamespaceScope:
        case State.ClearNsAttributes:
            break;
        case State.ReadElementContentAsBase64:
        case State.ReadElementContentAsBinHex:
        case State.ReadContentAsBase64:
        case State.ReadContentAsBinHex:
            throw new InvalidOperationException(System.SR.Xml_MixingReadValueChunkWithBinary);
        default:
            throw CreateReadContentAsException(methodName);
        }
    }
References System.Xml.XmlSubtreeReader._state, System.Xml.XmlReader.CreateReadContentAsException(), System.SR.Xml_ClosedOrErrorReader, and System.SR.Xml_MixingReadValueChunkWithBinary.
Referenced by System.Xml.XmlSubtreeReader.ReadContentAs(), System.Xml.XmlSubtreeReader.ReadContentAsAsync(), System.Xml.XmlSubtreeReader.ReadContentAsBoolean(), System.Xml.XmlSubtreeReader.ReadContentAsDateTime(), System.Xml.XmlSubtreeReader.ReadContentAsDecimal(), System.Xml.XmlSubtreeReader.ReadContentAsDouble(), System.Xml.XmlSubtreeReader.ReadContentAsFloat(), System.Xml.XmlSubtreeReader.ReadContentAsInt(), System.Xml.XmlSubtreeReader.ReadContentAsLong(), System.Xml.XmlSubtreeReader.ReadContentAsObject(), System.Xml.XmlSubtreeReader.ReadContentAsObjectAsync(), System.Xml.XmlSubtreeReader.ReadContentAsString(), and System.Xml.XmlSubtreeReader.ReadContentAsStringAsync().