Terraria: WorldGen.paintCoatWall
paintCoatWall()
static bool WorldGen.paintCoatWall (int x, int y, byte paintCoatId, bool broadcast = false) inline static
     {
         Tile tile = Main.tile[x, y];
         if (tile == null || tile.wall == 0)
         {
             return false;
         }
         List<Color> oldColors = coatingColors(tile, block: false);
         switch (paintCoatId)
         {
         default:
             return false;
         case 0:
             if (!tile.fullbrightWall() && !tile.invisibleWall())
             {
                 return false;
             }
             tile.fullbrightWall(fullbrightWall: false);
             tile.invisibleWall(invisibleWall: false);
             SquareWallFrame(x, y, resetFrame: false);
             break;
         case 1:
             if (tile.fullbrightWall())
             {
                 return false;
             }
             tile.fullbrightWall(fullbrightWall: true);
             break;
         case 2:
             if (tile.invisibleWall())
             {
                 return false;
             }
             tile.invisibleWall(invisibleWall: true);
             SquareWallFrame(x, y, resetFrame: false);
             break;
         }
         if (broadcast)
         {
             NetMessage.SendData(64, -1, -1, null, x, y, (int)paintCoatId, 1f);
         }
         paintCoatEffect(x, y, paintCoatId, oldColors);
         return true;
     }
References Tile.fullbrightWall(), Tile.invisibleWall(), NetMessage.SendData(), Main.tile, and Tile.wall.
Referenced by Player.ApplyCoating(), MessageBuffer.GetData(), and Player.PlaceThing_PaintScrapper_TryScrapping().