Terraria: WorldGen.RandomizeWeather
RandomizeWeather()
static void WorldGen.RandomizeWeather () inline static
     {
         Main.numClouds = genRand.Next(10, 200);
         Main.windSpeedCurrent = 0f;
         while (Main.windSpeedCurrent == 0f)
         {
             Main.windSpeedCurrent = (float)genRand.Next(-400, 401) * 0.001f;
             Main.windSpeedTarget = Main.windSpeedCurrent;
         }
         Cloud.resetClouds();
     }
References genRand, UnifiedRandom.Next(), Main.numClouds, Cloud.resetClouds(), Main.windSpeedCurrent, and Main.windSpeedTarget.
Referenced by GenerateWorld(), and WorldFile.LoadWorld_Version1_Old_BeforeRelease88().