Terraria: WorldGen.ShimmerMakeBiome
ShimmerMakeBiome()
static bool WorldGen.ShimmerMakeBiome (int X, int Y) inline static
     {
         int num = genRand.Next(2);
         double num2 = 0.6;
         double num3 = 1.3;
         double num4 = 0.3;
         if (num == 0)
         {
             num2 = 0.55;
             num3 = 2.0;
         }
         num2 *= 1.05 - genRand.NextDouble() * 0.1;
         num3 *= 1.05 - genRand.NextDouble() * 0.1;
         num4 *= 1.0 - genRand.NextDouble() * 0.1;
         int num5 = genRand.Next(105, 125);
         int num6 = (int)((double)num5 * num4);
         int num7 = (int)((double)num5 * num2);
         int num8 = genRand.Next(9, 13);
         int num9 = X - num5;
         int num10 = X + num5;
         int num11 = Y - num5;
         int num12 = Y + num5;
         for (int i = num11; i <= num12; i++)
         {
             for (int j = num9; j <= num10; j++)
             {
                 if (!InWorld(j, i, 50))
                 {
                     return false;
                 }
                 if (Main.tile[j, i].type == 203 || Main.tile[j, i].type == 25)
                 {
                     return false;
                 }
             }
         }
         int num13 = Y;
         if (genRand.Next(4) == 0)
         {
             num13 = Y - genRand.Next(2);
         }
         int num14 = Y - num8;
         if (genRand.Next(4) == 0)
         {
             num14 = Y - num8 - genRand.Next(2);
         }
         for (int k = num11; k <= num12; k++)
         {
             for (int l = num9; l <= num10; l++)
             {
                 Main.tile[l, k].liquid = 0;
                 if (genRand.Next(4) == 0)
                 {
                     num13 = Y - genRand.Next(2);
                 }
                 if (genRand.Next(4) == 0)
                 {
                     num14 = Y - num8 + genRand.Next(2);
                 }
                 int num15 = ((k <= Y) ? ((int)Math.Sqrt(Math.Pow((double)Math.Abs(l - X) * (1.0 + genRand.NextDouble() * 0.02), 2.0) + Math.Pow((double)Math.Abs(k - Y) * 1.4 * (1.0 + genRand.NextDouble() * 0.02), 2.0))) : ((int)Math.Sqrt(Math.Pow((double)Math.Abs(l - X) * (1.0 + genRand.NextDouble() * 0.02), 2.0) + Math.Pow((double)Math.Abs(k - Y) * 1.2 * (1.0 + genRand.NextDouble() * 0.02), 2.0))));
                 if (num15 < num5)
                 {
                     Main.tile[l, k].color(0);
                     Main.tile[l, k].wallColor(0);
                     Main.tile[l, k].slope(0);
                     Main.tile[l, k].halfBrick(halfBrick: false);
                     Main.tile[l, k].type = 1;
                     if (l > num9 + 5 + genRand.Next(2) && l < num10 - 5 - genRand.Next(2))
                     {
                         Main.tile[l, k].active(active: true);
                     }
                     if ((double)num15 < (double)num5 * 0.9)
                     {
                         Main.tile[l, k].wall = 0;
                     }
                 }
                 num15 = (int)Math.Sqrt(Math.Pow((double)Math.Abs(l - X) * (1.0 + genRand.NextDouble() * 0.02), 2.0) + Math.Pow((double)Math.Abs(k - Y) * num3 * (1.0 + genRand.NextDouble() * 0.02), 2.0));
                 if (k > num14 && k < num13)
                 {
                     Main.tile[l, k].active(active: false);
                 }
                 if (k < num13 && num15 < (int)((double)num7 * (1.0 + genRand.NextDouble() * 0.02)))
                 {
                     Main.tile[l, k].active(active: false);
                 }
                 num15 = (int)Math.Sqrt(Math.Pow((double)Math.Abs(l - X) * (1.0 + genRand.NextDouble() * 0.02), 2.0) + Math.Pow((double)(Math.Abs(k - Y) * 2) * (1.0 + genRand.NextDouble() * 0.02), 2.0));
                 if (k < Y - 1 || num15 >= (int)((double)num6 * (1.0 + genRand.NextDouble() * 0.025)))
                 {
                     continue;
                 }
                 if (k <= Y + 2 || num15 != num6 - 1 || genRand.Next(2) != 0)
                 {
                     Main.tile[l, k].active(active: false);
                 }
                 if (k >= Y)
                 {
                     if (k == Y)
                     {
                         Main.tile[l, k].liquid = 127;
                     }
                     else
                     {
                         Main.tile[l, k].liquid = byte.MaxValue;
                     }
                     Main.tile[l, k].shimmer(shimmer: true);
                 }
             }
         }
         if (num == 0)
         {
             num9 = (int)((double)X - (double)num5 * num4) - genRand.Next(-15, 1) - 5;
             num10 = (int)((double)X + (double)num5 * num4) + genRand.Next(0, 16);
             int m = num9;
             int num16 = 0;
             for (; m < num10; m += genRand.Next(9, 14))
             {
                 int num17 = Y - 3;
                 while (!Main.tile[m, num17].active())
                 {
                     num17--;
                 }
                 num17 -= 4;
                 int num18 = genRand.Next(5, 10);
                 int num19 = genRand.Next(15, 21);
                 int n = m - num18;
                 while (num18 > 0)
                 {
                     for (n = m - num18; n < m + num18; n++)
                     {
                         Main.tile[n, num17].active(active: true);
                         Main.tile[n, num17].type = 1;
                     }
                     num16++;
                     if (genRand.Next(3) < num16)
                     {
                         num16 = 0;
                         num18--;
                         m += genRand.Next(-1, 2);
                     }
                     if (num19 <= 0)
                     {
                         num18--;
                     }
                     num19--;
                     num17++;
                 }
                 n -= genRand.Next(1, 3);
                 Main.tile[n, num17 - 2].active(active: true);
                 Main.tile[n, num17 - 2].type = 1;
                 Main.tile[n, num17 - 1].active(active: true);
                 Main.tile[n, num17 - 1].type = 1;
                 Main.tile[n, num17].active(active: true);
                 Main.tile[n, num17].type = 1;
                 if (genRand.Next(2) == 0)
                 {
                     Main.tile[n, num17 + 1].active(active: true);
                     Main.tile[n, num17 + 1].type = 1;
                     PlaceTight(n, num17 + 2);
                 }
                 else
                 {
                     PlaceTight(n, num17 + 1);
                 }
             }
         }
         ShimmerMakeBiomeOpening(-1, X - num5, Y, num8);
         ShimmerMakeBiomeOpening(1, X + num5, Y, num8);
         int num20 = 70;
         for (int num21 = 0; num21 < 500; num21++)
         {
             int num22 = genRand.Next(X - num20, X + num20);
             int num23 = genRand.Next(Y - 2, Y + 3);
             int num24 = genRand.Next(7);
             int treeTileType = 0;
             switch (num24)
             {
             case 0:
                 treeTileType = 583;
                 break;
             case 1:
                 treeTileType = 584;
                 break;
             case 2:
                 treeTileType = 585;
                 break;
             case 3:
                 treeTileType = 586;
                 break;
             case 4:
                 treeTileType = 587;
                 break;
             case 5:
                 treeTileType = 588;
                 break;
             case 6:
                 treeTileType = 589;
                 break;
             }
             if (SolidTile(num22 - 1, num23) && SolidTile(num22 + 1, num23))
             {
                 TryGrowingTreeByType(treeTileType, num22, num23);
             }
         }
         return true;
     }
References Tile.active(), Tile.color(), Tile.halfBrick(), Tile.liquid, Tile.shimmer(), Tile.slope(), SolidTile, Main.tile, Tile.type, Tile.wall, Tile.wallColor(), X, and Y.