Terraria: WorldGen.SpawnPlanteraThorns
SpawnPlanteraThorns()
static void WorldGen.SpawnPlanteraThorns (Vector2 position) inline static
     {
         if (Main.netMode == 1)
         {
             return;
         }
         int num = Main.rand.Next(3, 6);
         for (int i = 0; i < num; i++)
         {
             int num2 = Main.rand.Next(15, 31);
             int num3 = (int)(position.X / 16f);
             int num4 = (int)(position.Y / 16f);
             int num5 = 0;
             int num6 = 0;
             if (Main.rand.Next(2) != 0)
             {
                 num6 = ((Main.rand.Next(2) == 0) ? 1 : (-1));
             }
             else
             {
                 num5 = ((Main.rand.Next(2) == 0) ? 1 : (-1));
             }
             while (num2 > 0)
             {
                 num2--;
                 if (!Main.tile[num3, num4].active())
                 {
                     PlaceTile(num3, num4, 655);
                     if (Main.tile[num3, num4].active() && Main.netMode == 2)
                     {
                         NetMessage.SendTileSquare(-1, num3, num4);
                     }
                 }
                 num3 += num5;
                 num4 += num6;
                 if (!InWorld(num3, num4))
                 {
                     return;
                 }
                 if (Main.rand.Next(5) == 0)
                 {
                     if (num6 == 0)
                     {
                         num5 = 0;
                         num6 = ((Main.rand.Next(2) == 0) ? 1 : (-1));
                     }
                     else
                     {
                         num6 = 0;
                         num5 = ((Main.rand.Next(2) == 0) ? 1 : (-1));
                     }
                 }
             }
         }
     }
References Tile.active(), Main.netMode, UnifiedRandom.Next(), Main.rand, NetMessage.SendTileSquare(), and Main.tile.
Referenced by NPC.AI().