Terraria: WorldGen.StartRoomCheck
StartRoomCheck()
static bool WorldGen.StartRoomCheck (int x, int y) inline static
     {
         roomHasStinkbug = false;
         roomHasEchoStinkbug = false;
         roomX1 = x;
         roomX2 = x;
         roomY1 = y;
         roomY2 = y;
         numRoomTiles = 0;
         roomCeilingsCount = 0;
         for (int i = 0; i < TileID.Count; i++)
         {
             houseTile[i] = false;
         }
         canSpawn = true;
         if (Main.tile[x, y].nactive() && Main.tileSolid[Main.tile[x, y].type])
         {
             roomCheckFailureReason = TownNPCRoomCheckFailureReason.RoomCheckStartedInASolidTile;
             canSpawn = false;
             return false;
         }
         roomCheckFailureReason = TownNPCRoomCheckFailureReason.None;
         CheckRoom(x, y);
         if (!canSpawn)
         {
             return false;
         }
         if (numRoomTiles < 60)
         {
             roomCheckFailureReason = TownNPCRoomCheckFailureReason.RoomIsTooSmall;
             canSpawn = false;
             return false;
         }
         if (canSpawn)
         {
             return true;
         }
         return false;
     }
References canSpawn, CheckRoom(), TileID.Count, houseTile, Tile.nactive(), numRoomTiles, roomCeilingsCount, roomCheckFailureReason, roomHasEchoStinkbug, roomHasStinkbug, roomX1, roomX2, roomY1, roomY2, Main.tile, Main.tileSolid, and Tile.type.
Referenced by Player.CheckSpawn_Internal(), MoveTownNPC(), QuickFindHome(), and SpawnTownNPC().