Terraria: WorldGen.GenerateWorld
GenerateWorld()
static void WorldGen.GenerateWorld (int seed, GenerationProgress customProgressObject = null) inline static
References _generator, _genRand, _lastSeed, Tile.active(), AddGenerationPass(), Main.afterPartyOfDoom, GenVars.beachBordersWidth, GenVars.beachSandDungeonExtraWidth, GenVars.beachSandJungleExtraWidth, GenVars.beachSandRandomCenter, GenVars.beachSandRandomWidthRange, Caverer(), Main.checkHalloween(), Main.checkXMas(), Main.cloudAlpha, Main.cloudBGActive, CloudIsland(), CloudLake(), GenVars.configuration, GenVars.copper, WorldGen.SavedOreTiers.Copper, GenVars.copperBar, TreeTopsInfo.CopyExistingWorldInfoForWorldGeneration(), crimson, GenVars.crimsonLeft, Main.dayTime, DesertCloudIsland(), GenVars.desertHiveHigh, GenVars.desertHiveLeft, GenVars.desertHiveLow, GenVars.desertHiveRight, Vector2D.Distance(), Main.dontStarveWorld, dontStarveWorldGen, Main.drunkWorld, drunkWorldGen, drunkWorldGenText, GenVars.dungeonLocation, GenVars.dungeonSide, E, everythingWorldGen, GenVars.evilBiomeAvoidanceMidFixer, GenVars.evilBiomeBeachAvoidance, Main.expertMode, GenVars.extraBastStatueCount, GenVars.extraBastStatueCountMax, GenVars.floatingIslandHouseX, GenVars.floatingIslandHouseY, GenVars.floatingIslandStyle, WorldGenConfiguration.FromEmbeddedPath(), Lang.gen, gen, genRand, Main.getGoodWorld, getGoodWorldGen, Language.GetTextValue(), GenVars.gold, WorldGen.SavedOreTiers.Gold, GenVars.goldBar, grassSpread, growGrassUnderground, heartCount, GenVars.hellChestItem, InWorld(), GenVars.iron, WorldGen.SavedOreTiers.Iron, GenVars.ironBar, GenVars.jungleHut, GenVars.jungleMaxX, GenVars.jungleMinX, GenVars.jungleOriginX, KillTile(), GenVars.lakesBeachAvoidance, GenVars.lavaLine, GenVars.leftBeachEnd, Liquid, Main.lockMenuBGChange, GenVars.logX, GenVars.logY, GenVars.maxMushroomBiomes, Main.maxRaining, Main.maxTilesX, Main.maxTilesY, GenVars.maxTunnels, GenVars.mCaveX, GenVars.mCaveY, GenerationProgress.Message, Mountinater(), GenVars.mushroomBiomesPosition, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), noTileActions, Main.noTrapsWorld, noTrapsWorldGen, notTheBees, NotTheBees(), Main.notTheBeesWorld, GenVars.numIslandHouses, GenVars.numLarva, GenVars.numMCaves, GenVars.numMushroomBiomes, GenVars.numOceanCaveTreasure, GenVars.numPyr, GenVars.numTunnels, GenVars.oceanWaterForcedJungleLength, GenVars.oceanWaterStartRandomMax, GenVars.oceanWaterStartRandomMin, DesertBiome.Place(), PlaceTile(), WorldGen.Hooks.ProcessWorldGenConfig(), GenVars.PyrX, GenVars.PyrY, Main.raining, Main.rand, RandomizeBackgrounds(), RandomizeCaveBackgrounds(), RandomizeMoonState(), RandomizeTreeStyle(), RandomizeWeather(), RandomWorldPoint(), Main.remixWorld, remixWorldGen, ResetGenerator(), GenVars.rightBeachStart, GenVars.rockLayer, Main.rockLayer, GenVars.rockLayerHigh, GenVars.rockLayerLow, ScanTileColumnAndRemoveClumps(), GenerationProgress.Set(), SetupStatueList(), GenVars.shellStartXLeft, GenVars.shellStartXRight, GenVars.shellStartYLeft, GenVars.shellStartYRight, ShroomPatch(), GenVars.silver, WorldGen.SavedOreTiers.Silver, GenVars.silverBar, GenVars.skipDesertTileCheck, skipFramingDuringGen, GenVars.skyIslandHouseCount, GenVars.skyLake, GenVars.skyLakes, Main.slimeRainTime, SmallConsecutivesEliminated, SmallConsecutivesFound, GenVars.smallHolesBeachAvoidance, GenVars.snowBottom, SnowCloudIsland(), GenVars.snowMaxX, GenVars.snowMinX, GenVars.snowOriginLeft, GenVars.snowOriginRight, GenVars.snowTop, SolidTile(), SpreadGrass(), Main.starGame, GenVars.structures, GenVars.surfaceCavesBeachAvoidance, GenVars.surfaceCavesBeachAvoidance2, tempRemixWorldGen, tempTenthAnniversaryWorldGen, Main.tenthAnniversaryWorld, tenthAnniversaryWorldGen, Main.tile, TileRunner(), Main.tileSolid, Main.time, TreeTops, GenVars.tunnelX, Tile.type, GenVars.UndergroundDesertHiveLocation, GenVars.UndergroundDesertLocation, Main.UnderworldLayer, LocalizedText.Value, Tile.wall, WavyCaverer(), WorldGenParam_Evil, Main.worldID, GenVars.worldSurface, Main.worldSurface, GenVars.worldSurfaceHigh, GenVars.worldSurfaceLow, and Main.zenithWorld.
Referenced by WorldUtils.DebugRegen(), Main.Initialize_AlmostEverything(), WorldFile.LoadWorld(), and worldGenCallback().