Terraria: WorldGen.countWires
countWires()
static int WorldGen.countWires (int x, int y, int size) inline static
     {
         int num = 0;
         for (int i = x - size; i <= x + size; i++)
         {
             for (int j = y - size; j <= y + size; j++)
             {
                 if (InWorld(i, j))
                 {
                     if (Main.tile[i, j].wire())
                     {
                         num++;
                     }
                     if (Main.tile[i, j].wire2())
                     {
                         num++;
                     }
                     if (Main.tile[i, j].wire3())
                     {
                         num++;
                     }
                     if (Main.tile[i, j].wire4())
                     {
                         num++;
                     }
                 }
             }
         }
         return num;
     }
References InWorld(), Main.tile, Tile.wire(), Tile.wire2(), Tile.wire3(), and Tile.wire4().
Referenced by DeadMansChestBiome.IsAGoodSpot().