Terraria: WorldGen.GrowCheckSeaweed
GrowCheckSeaweed()
static void WorldGen.GrowCheckSeaweed (int x, int y) inline static
     {
         int maxValue = 1;
         if (Main.netMode == 1)
         {
             return;
         }
         if ((Main.tile[x, y].type == 549 && Main.tile[x, y].liquid < 200) || Main.tile[x, y - 1].liquid < 200)
         {
             if (Main.tile[x, y].active() && Main.tile[x, y].type == 549 && genRand.Next(2) == 0)
             {
                 KillTile(x, y);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendData(17, -1, -1, null, 0, x, y);
                 }
             }
         }
         else
         {
             if (Main.tile[x, y - 1].active() || Main.tile[x, y - 2].active() || genRand.Next(maxValue) != 0 || Main.tile[x, y - 2].liquid != byte.MaxValue || Main.tile[x, y - 3].liquid != byte.MaxValue)
             {
                 return;
             }
             int num = 17;
             int num2 = 4;
             int num3 = 30;
             int num4 = 0;
             for (int i = x - num2; i <= x + num2; i++)
             {
                 for (int j = y; j <= y + num2 * 3; j++)
                 {
                     if (Main.tile[i, j].active() && Main.tile[i, j].type == 549)
                     {
                         num4++;
                         if (num4 > num3)
{
                             return;
                         }
                     }
                 }
             }
             int k;
             for (k = y; !SolidTile(x, k) && k < Main.maxTilesY - 50; k++)
             {
             }
             if (k - y < num - genRand.Next(20))
             {
                 PlaceTile(x, y - 1, 549, mute: true);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y - 1);
                 }
             }
         }
     }
References Tile.active(), Tile.liquid, Main.maxTilesY, Main.netMode, NetMessage.SendData(), NetMessage.SendTileSquare(), SolidTile, Main.tile, and Tile.type.