Terraria: System.Xml.XmlSubtreeReader.ReadContentAsInt
ReadContentAsInt()
override int System.Xml.XmlSubtreeReader.ReadContentAsInt () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 707 of file XmlSubtreeReader.cs.
    {
        try
        {
            InitReadContentAsType("ReadContentAsInt");
            int result = reader.ReadContentAsInt();
            FinishReadContentAsType();
            return result;
        }
        catch
        {
            _state = State.Error;
            throw;
        }
    }
References System.Xml.XmlSubtreeReader._state, System.Xml.XmlSubtreeReader.FinishReadContentAsType(), System.Xml.XmlSubtreeReader.InitReadContentAsType(), System.Xml.XmlReader.ReadContentAsInt(), and System.Xml.XmlWrappingReader.reader.