Terraria: WorldGen.TreeGrowFX_AshShake
TreeGrowFX_AshShake()
static void WorldGen.TreeGrowFX_AshShake (int x, int y, int height, bool hitTree = false) inline static private
     {
         Vector2 vector = new Vector2(x, y) * 16f + new Vector2(8f, 8f);
         for (int num = 0; num > -height; num--)
         {
             if (num >= -height / 2 && Main.rand.Next(3) != 0)
             {
                 int num2 = (hitTree ? 10 : 5);
                 for (int i = 0; i < num2; i++)
                 {
                     Dust.NewDustDirect(vector + new Vector2(-16f, num * 16) + Utils.RandomVector2(Main.rand, -30f, 30f), 4, 4, 31, 0f, -3f, 100).velocity = Main.rand.NextVector2Circular(2f, 2f) + new Vector2(0f, -0.6f);
                 }
             }
             if ((float)num >= (float)(-height) * 0.7f && Main.rand.Next(3) != 0)
             {
                 int num3 = (hitTree ? 16 : 10);
                 for (int j = 0; j < num3; j++)
                 {
                     Dust dust = Dust.NewDustDirect(vector + new Vector2(-16f, num * 16) + Utils.RandomVector2(Main.rand, -30f, 30f), 4, 4, 6, 0f, -4f, 0, default(Color), 1f + 0.7f * Main.rand.NextFloat());
                     dust.velocity = Main.rand.NextVector2Circular(2f, 2f) + new Vector2(0f, -0.6f);
                     if (Main.rand.Next(2) == 0)
                     {
                         dust.velocity *= 2f;
                         dust.noGravity = true;
                     }
                     dust.velocity += new Vector2(0f, hitTree ? (-1f) : (-2f));
                 }
             }
             if (!hitTree)
             {
                 Gore.NewGoreDirect(vector + new Vector2(-16f, num * 16 - 40) + Utils.RandomVector2(Main.rand, -40f, 40f) * new Vector2(0.5f, 1f), Vector2.Zero, 61 + Main.rand.Next(3)).velocity *= 0.5f;
             }
         }
     }
References Color, Dust.NewDustDirect(), Gore.NewGoreDirect(), UnifiedRandom.Next(), Dust.noGravity, Main.rand, Utils.RandomVector2(), Dust.velocity, and Gore.velocity.