Terraria: WorldGen.PlaceChest
PlaceChest()
static int WorldGen.PlaceChest (int x, int y, ushort type = 21, bool notNearOtherChests = false, int style = 0) inline static
     {
         int num = -1;
         if (TileID.Sets.Boulders[Main.tile[x, y + 1].type] || TileID.Sets.Boulders[Main.tile[x + 1, y + 1].type])
         {
             return -1;
         }
         if (TileObject.CanPlace(x, y, type, style, 1, out var objectData))
         {
             bool flag = true;
             if (notNearOtherChests && Chest.NearOtherChests(x - 1, y - 1))
             {
                 flag = false;
             }
             if (flag)
             {
                 TileObject.Place(objectData);
                 num = Chest.CreateChest(objectData.xCoord, objectData.yCoord);
             }
         }
         else
         {
             num = -1;
         }
         if (num != -1 && Main.netMode == 1 && type == 21)
         {
             NetMessage.SendData(34, -1, -1, null, 0, x, y, style);
         }
         if (num != -1 && Main.netMode == 1 && type == 467)
         {
             NetMessage.SendData(34, -1, -1, null, 4, x, y, style);
         }
         return num;
     }
References TileID.Sets.Boulders, TileObject.CanPlace(), Chest.CreateChest(), Chest.NearOtherChests(), Main.netMode, TileObject.Place(), NetMessage.SendData(), Main.tile, and Tile.type.
Referenced by MessageBuffer.GetData().