Terraria: WorldGen.GetTileVisualHitbox
GetTileVisualHitbox()
static ? Rectangle WorldGen.GetTileVisualHitbox (int x, int y) inline static
     {
         Tile tile = Main.tile[x, y];
         if (tile == null || !tile.nactive())
         {
             return null;
         }
         Rectangle value = new Rectangle(x * 16, y * 16, 16, 16);
         ushort type = tile.type;
         if (type == 323)
         {
             value.X += tile.frameY;
         }
         if (tile.halfBrick())
         {
             value.Y += 8;
             value.Height = 8;
         }
         return value;
     }
References Tile.frameY, Tile.halfBrick(), Tile.nactive(), Main.tile, and Tile.type.
Referenced by Projectile.AI_007_GrapplingHooks().