Terraria: WorldGen.LaunchRocketSmall
LaunchRocketSmall()
static void WorldGen.LaunchRocketSmall (int x, int y, bool fromWiring) inline static
     {
         if (Main.tile[x, y].frameX == 18)
         {
             x--;
         }
         if (Main.tile[x, y].frameY == 18)
         {
             y--;
         }
         Vector2 vector = new Vector2(x * 16 + 16, y * 16);
         int type = 415 + Main.rand.Next(4);
         int damage = 0;
         int num = 0;
         int num2 = Projectile.NewProjectile(GetProjectileSource_PlayerOrWires(x, y, fromWiring, Main.LocalPlayer), vector.X, vector.Y + 2f, 0f, -8f, type, damage, num, Main.myPlayer);
         Main.projectile[num2].originatedFromActivableTile = true;
     }
References Tile.frameX, Tile.frameY, Main.LocalPlayer, Main.myPlayer, Projectile.NewProjectile(), UnifiedRandom.Next(), Projectile.originatedFromActivableTile, Main.projectile, Main.rand, and Main.tile.
Referenced by Wiring.HitWireSingle(), and Player.TileInteractionsUse().