Terraria: WorldGen.AttemptToGeneratePlanteraBulbAt
AttemptToGeneratePlanteraBulbAt()
static bool WorldGen.AttemptToGeneratePlanteraBulbAt (int i, int j, bool forceBulb) inline static private
     {
         if (forceBulb)
         {
             int num = 0;
             for (int k = -2; k < 2; k++)
             {
                 for (int l = -2; l < 2; l++)
                 {
                     int num2 = i + k;
                     int num3 = j + l;
                     Tile tile = Main.tile[num2, num3];
                     if (tile.type == 59 || tile.type == 60)
                     {
                         num++;
                     }
                     else if (tile.active())
                     {
                         num--;
                     }
                     if (IsAContainer(tile) || tile.type == 226 || tile.type == 237 || tile.type == 10 || tile.type == 11 || tile.type == 26 || tile.type == 16 || tile.type == 15 || tile.type == 14 || tile.type == 104 || TileID.Sets.Paintings[tile.type] || tile.type == 158 || tile.type == 105 || tile.type == 531 || tile.type == 349 || tile.type == 138 || tile.type == 664 || tile.type == 665 || tile.type == 137 || tile.type == 443 || tile.type == 12 || tile.type == 665 || tile.type == 314)
                     {
                         num = -1;
                         break;
                     }
                 }
                 if (num <= -1)
                 {
                     break;
                 }
             }
             if (num < 12)
             {
                 return false;
             }
             for (int m = -2; m < 2; m++)
             {
                 for (int n = -2; n < 2; n++)
                 {
                     int num4 = i + m;
                     int num5 = j + n;
                     bool num6 = m == -2 || m == 1 || n == -2 || n == 1;
                     Tile tile2 = Main.tile[num4, num5];
                     tile2.ClearTile();
                     if (num6)
                     {
                         tile2.type = 60;
                         tile2.active(active: true);
                     }
                     SquareTileFrame(num4, num5);
                 }
             }
             PlaceJunglePlant(i, j, 238, 0, 0);
             if (Main.tile[i, j].type == 238)
             {
                 SquareTileFrame(i, j);
                 SquareTileFrame(i + 2, j);
                 SquareTileFrame(i - 1, j);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, i, j, 8);
                 }
                 return true;
             }
         }
         else
         {
             PlaceJunglePlant(i, j, 238, 0, 0);
             if (Main.tile[i, j].type == 238)
             {
                 SquareTileFrame(i, j);
                 SquareTileFrame(i + 2, j);
                 SquareTileFrame(i - 1, j);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, i, j, 5);
                 }
                 return true;
             }
         }
         return false;
     }
References Tile.active(), Tile.ClearTile(), Main.netMode, TileID.Sets.Paintings, NetMessage.SendTileSquare(), Main.tile, and Tile.type.