Terraria: WorldGen.OreRunner
OreRunner()
static void WorldGen.OreRunner (int i, int j, double strength, int steps, ushort type) inline static
     {
         //IL_005e: Unknown result type (might be due to invalid IL or missing references)
         //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
         //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
         //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
         //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
         //IL_05a7: Unknown result type (might be due to invalid IL or missing references)
         //IL_05a8: Unknown result type (might be due to invalid IL or missing references)
         //IL_05a9: Unknown result type (might be due to invalid IL or missing references)
         //IL_05ae: Unknown result type (might be due to invalid IL or missing references)
         //IL_05d3: Unknown result type (might be due to invalid IL or missing references)
         //IL_05f4: Unknown result type (might be due to invalid IL or missing references)
         //IL_0139: Unknown result type (might be due to invalid IL or missing references)
         //IL_0148: Unknown result type (might be due to invalid IL or missing references)
         double num = strength;
         double num2 = steps;
         Vector2D val = default(Vector2D);
         val.X = i;
         val.Y = j;
         Vector2D val2 = default(Vector2D);
         val2.X = (double)genRand.Next(-10, 11) * 0.1;
         val2.Y = (double)genRand.Next(-10, 11) * 0.1;
         while (num > 0.0 && num2 > 0.0)
         {
             if (val.Y < 0.0 && num2 > 0.0 && type == 59)
             {
                 num2 = 0.0;
             }
             num = strength * (num2 / (double)steps);
             num2 -= 1.0;
             int num3 = (int)(val.X - num * 0.5);
             int num4 = (int)(val.X + num * 0.5);
             int num5 = (int)(val.Y - num * 0.5);
             int num6 = (int)(val.Y + num * 0.5);
             if (num3 < 0)
             {
                 num3 = 0;
             }
             if (num4 > Main.maxTilesX)
             {
                 num4 = Main.maxTilesX;
             }
             if (num5 < 0)
             {
                 num5 = 0;
             }
             if (num6 > Main.maxTilesY)
             {
                 num6 = Main.maxTilesY;
             }
             for (int k = num3; k < num4; k++)
             {
                 for (int l = num5; l < num6; l++)
                 {
                     if (Math.Abs((double)k - val.X) + Math.Abs((double)l - val.Y) < strength * 0.5 * (1.0 + (double)genRand.Next(-10, 11) * 0.015) && Main.tile[k, l].active() && (Main.tile[k, l].type == 0 || Main.tile[k, l].type == 1 || Main.tile[k, l].type == 23 || Main.tile[k, l].type == 25 || Main.tile[k, l].type == 40 || Main.tile[k, l].type == 53 || Main.tile[k, l].type == 57 || Main.tile[k, l].type == 59 || Main.tile[k, l].type == 60 || Main.tile[k, l].type == 70 || Main.tile[k, l].type == 109 || Main.tile[k, l].type == 112 || Main.tile[k, l].type == 116 || Main.tile[k, l].type == 117 || Main.tile[k, l].type == 147 || Main.tile[k, l].type == 161 || Main.tile[k, l].type == 163 || Main.tile[k, l].type == 164 || Main.tileMoss[Main.tile[k, l].type] || Main.tile[k, l].type == 199 || Main.tile[k, l].type == 200 || Main.tile[k, l].type == 203 || Main.tile[k, l].type == 234 || Main.tile[k, l].type == 396 || Main.tile[k, l].type == 397 || Main.tile[k, l].type == 401 || Main.tile[k, l].type == 403 || Main.tile[k, l].type == 400 || Main.tile[k, l].type == 398 || Main.tile[k, l].type == 399 || Main.tile[k, l].type == 402 || (Main.remixWorld && Main.tile[k, l].type == 230) || (Main.tile[k, l].type == 225 && Main.tile[k, l].wall != 108)))
                     {
                         Main.tile[k, l].type = type;
                         Main.tile[k, l].ClearBlockPaintAndCoating();
                         SquareTileFrame(k, l);
                         if (Main.netMode == 2)
{
                             NetMessage.SendTileSquare(-1, k, l);
                         }
                     }
                 }
             }
             val += val2;
             val2.X += (double)genRand.Next(-10, 11) * 0.05;
             if (val2.X > 1.0)
             {
                 val2.X = 1.0;
             }
             if (val2.X < -1.0)
             {
                 val2.X = -1.0;
             }
         }
     }
References Tile.active(), Tile.ClearBlockPaintAndCoating(), Main.maxTilesX, Main.maxTilesY, Main.netMode, Main.remixWorld, NetMessage.SendTileSquare(), Main.tile, Main.tileMoss, Tile.type, Tile.wall, Vector2D.X, and Vector2D.Y.