Terraria: System.Xml.XmlSubtreeReader.AddNamespace
AddNamespace()
void System.Xml.XmlSubtreeReader.AddNamespace (string prefix, string ns) inline private
Definition at line 1149 of file XmlSubtreeReader.cs.
    {
        _nsManager.AddNamespace(prefix, ns);
        int num = _nsAttrCount++;
        if (_nsAttributes == null)
        {
            _nsAttributes = new NodeData[InitialNamespaceAttributeCount];
        }
        if (num == _nsAttributes.Length)
        {
            NodeData[] array = new NodeData[_nsAttributes.Length * 2];
            Array.Copy(_nsAttributes, array, num);
            _nsAttributes = array;
        }
        string localName;
        string prefix2;
        string name;
        if (prefix.Length == 0)
        {
            localName = _xmlns;
            prefix2 = string.Empty;
            name = _xmlns;
        }
        else
        {
            localName = prefix;
            prefix2 = _xmlns;
            name = reader.NameTable.Add(_xmlns + ":" + prefix);
        }
        if (_nsAttributes[num] == null)
        {
            _nsAttributes[num] = new NodeData(XmlNodeType.Attribute, localName, prefix2, name, _xmlnsUri, ns);
        }
        else
        {
            _nsAttributes[num].Set(XmlNodeType.Attribute, localName, prefix2, name, _xmlnsUri, ns);
        }
        _state = State.ClearNsAttributes;
        _curNsAttr = -1;
    }
References System.Xml.XmlSubtreeReader._curNsAttr, System.Xml.XmlSubtreeReader._nsAttrCount, System.Xml.XmlSubtreeReader._nsAttributes, System.Xml.XmlSubtreeReader._nsManager, System.Xml.XmlSubtreeReader._state, System.Xml.XmlSubtreeReader._xmlns, System.Xml.XmlSubtreeReader._xmlnsUri, System.Xml.XmlNameTable.Add(), System.Xml.XmlNamespaceManager.AddNamespace(), System.array, System.Array.Copy(), System.Xml.Dictionary, System.Xml.XmlSubtreeReader.InitialNamespaceAttributeCount, System.Xml.XmlReader.NameTable, System.prefix, System.Xml.XmlWrappingReader.reader, and System.Xml.XmlSubtreeReader.NodeData.Set().
Referenced by System.Xml.XmlSubtreeReader.ProcessNamespaces().