Terraria: WorldGen.CheckChand
CheckChand()
static void WorldGen.CheckChand (int i, int j, int type) inline static
     {
         if (destroyObject)
         {
             return;
         }
         bool flag = false;
         int num = i;
         int num2 = j;
         int num3 = 3;
         if (type == 454)
         {
             num3 = 4;
         }
         num = Main.tile[i, j].frameX / 18;
         int num4 = 0;
         while (num >= num3)
         {
             num4++;
             num -= num3;
         }
         int num5 = i - num;
         int num6 = 18 * num3 * num4;
         if (num >= num3)
         {
             num -= num3;
         }
         num = i - num;
         num2 = Main.tile[i, j].frameY / 18;
         int num7 = 0;
         while (num2 >= 3)
         {
             num7++;
             num2 -= 3;
         }
         if (num6 >= 108)
         {
             num7 += 37 * (num6 / 108);
         }
         int num8 = 54 * num7;
         if (num6 >= 108)
         {
             num8 -= 54 * (num6 / 108) * 37;
         }
         if (num2 >= 3)
         {
             num2 -= 3;
         }
         num2 = j - num2;
         for (int k = num; k < num + num3; k++)
         {
             for (int l = num2; l < num2 + 3; l++)
             {
                 if (Main.tile[k, l] == null)
                 {
                     Main.tile[k, l] = new Tile();
                 }
                 if (!Main.tile[k, l].active() || Main.tile[k, l].type != type || Main.tile[k, l].frameX != (k - num5) * 18 + num6 || Main.tile[k, l].frameY != (l - num2) * 18 + num8)
                 {
                     flag = true;
                 }
             }
         }
         if (Main.tile[num + 1, num2 - 1] == null)
         {
             Main.tile[num + 1, num2 - 1] = new Tile();
         }
         if (!Main.tile[num + 1, num2 - 1].nactive() || !Main.tileSolid[Main.tile[num + 1, num2 - 1].type] || Main.tileSolidTop[Main.tile[num + 1, num2 - 1].type])
         {
             flag = true;
         }
         if (!flag)
         {
             return;
         }
         destroyObject = true;
         for (int m = num; m < num + num3; m++)
         {
             for (int n = num2; n < num2 + 3; n++)
             {
                 if (Main.tile[m, n].type == type && Main.tile[m, n].active())
                 {
                     KillTile(m, n);
                 }
             }
         }
         if (type == 454)
         {
             switch (Main.rand.Next(9))
             {
             case 2:
             case 3:
             case 4:
             {
                 int num13 = Main.rand.Next(10, 31);
                 while (num13 > 0)
                 {
                     int num14 = Main.rand.Next(2, 11);
                     if (num14 > num13)
                     {
                         num14 = num13;
                     }
                     num13 -= num14;
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, num14);
                 }
                 break;
             }
             case 5:
             case 6:
             {
                 int num17 = Main.rand.Next(60, 80);
                 while (num17 > 0)
                 {
                     int num18 = Main.rand.Next(3, 16);
                     if (num18 > num17)
                     {
                         num18 = num17;
                     }
                     num17 -= num18;
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16 - 10, j * 16 - 10, 52, 52, 72, num18);
                 }
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1358);
                 break;
             }
             case 7:
             {
                 int num15 = Main.rand.Next(10, 31);
                 while (num15 > 0)
                 {
                     int num16 = Main.rand.Next(2, 9);
                     if (num16 > num15)
                     {
                         num16 = num15;
                     }
                     num15 -= num16;
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16 - 10, j * 16 - 10, 52, 52, 72, num16);
                 }
                 if (Main.rand.Next(8) == 0)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3532);
                 }
                 if (Main.rand.Next(8) == 0)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3532);
                 }
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73);
                 break;
             }
             case 8:
             {
                 int num9 = 100;
                 while (num9 > 0)
                 {
                     int num10 = Main.rand.Next(3, 16);
                     if (num10 > num9)
                     {
                         num10 = num9;
                     }
                     num9 -= num10;
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16 - 10, j * 16 - 10, 52, 52, 72, num10);
                 }
                 int num11 = Main.rand.Next(30, 91);
                 while (num11 > 0)
                 {
                     int num12 = Main.rand.Next(7, 14);
                     if (num12 > num11)
                     {
                         num12 = num11;
                     }
                     num11 -= num12;
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16 - 10, j * 16 - 10, 52, 52, 1349, num12);
                 }
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1358);
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73);
                 break;
             }
             }
         }
         if (type == 34)
         {
             int type2;
             switch (num7)
             {
             case 1:
                 type2 = 107;
                 break;
             case 2:
                 type2 = 108;
                 break;
             case 3:
                 type2 = 710;
                 break;
             case 4:
                 type2 = 711;
                 break;
             case 5:
                 type2 = 712;
                 break;
             case 6:
                 type2 = 1812;
                 break;
             case 7:
             case 8:
             case 9:
             case 10:
             case 11:
             case 12:
             case 13:
             case 14:
             case 15:
             case 16:
             case 17:
                 type2 = 2055 + num7 - 7;
                 break;
             default:
                 type2 = ((num7 >= 18 && num7 <= 21) ? (2141 + num7 - 18) : (num7 switch
                 {
                     22 => 2224,
                     23 => 2525,
                     24 => 2543,
                     25 => 2558,
                     26 => 2573,
                     27 => 2652,
                     28 => 2653,
                     29 => 2654,
                     30 => 2655,
                     31 => 2656,
                     32 => 2657,
                     33 => 2813,
                     34 => 3177,
                     35 => 3179,
                     36 => 3178,
                     37 => 3894,
                     38 => 3938,
                     39 => 3964,
                     40 => 4152,
                     41 => 4173,
                     42 => 4194,
                     43 => 4215,
                     44 => 4305,
                     45 => 4573,
                     46 => 5155,
                     47 => 5176,
                     48 => 5197,
                     _ => 106,
                 }));
                 break;
             }
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, type2);
         }
         destroyObject = false;
         for (int num19 = num - 1; num19 < num + num3 + 1; num19++)
         {
             for (int num20 = num2 - 1; num20 < num2 + 4; num20++)
             {
                 TileFrame(num19, num20);
             }
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Tile.nactive(), Item.NewItem(), UnifiedRandom.Next(), Main.rand, Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.