Terraria: WorldGen.PaintTheDungeon
PaintTheDungeon()
static void WorldGen.PaintTheDungeon (byte tilePaintColor, byte wallPaintColor) inline static private
     {
         for (int i = 0; i < Main.maxTilesX; i++)
         {
             for (int j = 0; j < Main.maxTilesY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile.active())
                 {
                     if (Main.tileDungeon[tile.type] || TileID.Sets.CrackedBricks[tile.type])
                     {
                         tile.color(tilePaintColor);
                     }
                     if (tile.type == 19)
                     {
                         int num = tile.frameY / 18;
                         if (num >= 6 && num <= 12)
{
                             tile.color(tilePaintColor);
                         }
                     }
                 }
                 if (Main.wallDungeon[tile.wall])
                 {
                     tile.wallColor(wallPaintColor);
                 }
             }
         }
     }
References Tile.active(), Tile.color(), TileID.Sets.CrackedBricks, Tile.frameY, Main.maxTilesX, Main.maxTilesY, Main.tile, Main.tileDungeon, Tile.type, Tile.wall, Tile.wallColor(), and Main.wallDungeon.