Terraria: WorldGen.SolidTile
SolidTile() [3/3]
static bool WorldGen.SolidTile (Tile testTile) inline static
     {
         try
         {
             if (testTile == null)
             {
                 return true;
             }
             if (testTile.active() && Main.tileSolid[testTile.type] && !Main.tileSolidTop[testTile.type] && !testTile.halfBrick() && testTile.slope() == 0 && !testTile.inActive())
             {
                 return true;
             }
         }
         catch
         {
         }
         return false;
     }
References Tile.active(), Tile.halfBrick(), Tile.inActive(), Tile.slope(), Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by DesertHive.AddTileVariance(), NPC.AI(), Projectile.AI_001(), NPC.AI_001_Slimes(), NPC.AI_003_Fighters(), NPC.AI_005_EaterOfSouls(), NPC.AI_007_TownEntities(), Projectile.AI_026(), Projectile.AI_067_FreakingPirates(), NPC.AI_107_ImprovedWalkers(), NPC.AI_111_DD2LightningBug(), NPC.AI_112_FairyCritter(), NPC.AI_114_Dragonflies(), Projectile.AI_121_StardustDragon(), NPC.AI_123_Deerclops_ShootRubbleUp(), NPC.AI_123_Deerclops_TryMakingSpike_FindBestY(), Projectile.AI_137_CanHit(), Projectile.AI_137_LightningAura(), Projectile.AI_170_FairyGlowstick(), Actions.SwapSolidTile.Apply(), GraniteBiome.BuildMagmaMap(), TrackGenerator.CalculateStateForLocation(), Player.CheckCrackedBrickBreak(), NPC.checkDead(), CultistRitual.CheckFloor(), Player.CheckIceBreak(), CultistRitual.CheckRitual(), checkUnderground(), GraniteBiome.CleanupTiles(), TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint(), TileDrawing.CrawlToTopOfVineAndAddSpecialPoint(), HiveBiome.CreateDentForHoneyFall(), Player.DoBootsEffect_PlaceFlowersOnTile(), Main.DrawBlack(), TileObject.DrawPreview(), TileDrawing.DrawTile_LiquidBehindTile(), Main.DrawTileInWater(), WallDrawing.DrawWalls(), WaterfallManager.DrawWaterfall(), dropMeteor(), Mount.EmitGolfCartWheelDust(), TileDrawing.EmitLivingTreeLeaf_Below(), TileDrawing.EmitLivingTreeLeaf_Sideways(), TileDrawing.EmitTreeLeaves(), DSTFilm.FindFloorAt(), Player.FindSharpTearsOpening(), WaterfallManager.FindWaterfalls(), WorldGen.Spread.Gem(), GenerateWorld(), Projectile.GetAlpha(), Projectile.GetFishingPondState(), Projectile.GetFishingPondWidth(), TileDrawing.GetTileDrawData(), Gore.Gore_UpdateLeaf(), Player.ItemCheck_CheckCanUse(), Player.ItemCheck_ReleaseCritter(), Player.ItemCheck_Shoot(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), Projectile.Kill(), Liquid.LiquidCheck(), Rain.MakeRain(), MarblePileWithStatues(), mayanTrap(), meteor(), WorldGen.Spread.Moss(), Player.MowTheLawn(), nextCount(), nextDirtCount(), Main.oldDrawWater(), OrePatch(), CorruptionPitBiome.Place(), HoneyPatchBiome.Place(), MiningExplosivesBiome.Place(), GraniteBiome.PlaceGranite(), DD2Film.PlaceNPCOnGround(), MarbleBiome.PlaceSlab(), Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), placeTrap(), Projectile.ReduceRemainingChumsInPool(), ShellPile(), NPC.SpawnNPC(), NPC.SpawnNPC_CheckToSpawnRockGolem(), NPC.SpawnOnPlayer(), SpawnTravelNPC(), NPC.SpawnWOF(), WorldGen.Spread.Spider(), DelegateMethods.SpreadDirt(), DelegateMethods.SpreadTest(), SmartCursorHelper.Step_Pigronata(), StonePatch(), AmbientWindSystem.TrySpawningWind(), Gore.UpdateAmbientAirborneCloud(), Gore.UpdateAmbientFloorCloud(), Player.UpdateBlacklistedTilesForGrappling(), Dust.UpdateDust(), Mount.UpdateEffects(), Gore.UpdateFogMachineCloud(), WorldGen.Spread.Wall(), WorldGen.Spread.Wall2(), WorldGen.Spread.WallDungeon(), and Player.WallslideMovement().