Terraria: System.Xml.XmlSubtreeReader.CheckBuffer
CheckBuffer()
void System.Xml.XmlSubtreeReader.CheckBuffer (Array buffer, int index, int count) inline private
Definition at line 1348 of file XmlSubtreeReader.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
    }
References System.buffer, System.count, and System.index.
Referenced by System.Xml.XmlSubtreeReader.ReadContentAsBase64(), System.Xml.XmlSubtreeReader.ReadContentAsBase64Async(), System.Xml.XmlSubtreeReader.ReadContentAsBinHex(), System.Xml.XmlSubtreeReader.ReadContentAsBinHexAsync(), System.Xml.XmlSubtreeReader.ReadValueChunk(), and System.Xml.XmlSubtreeReader.ReadValueChunkAsync().