Terraria: WorldGen.WaterCheck
WaterCheck()
static void WorldGen.WaterCheck () inline static
     {
         Liquid.tilesIgnoreWater(ignoreSolids: true);
         Liquid.numLiquid = 0;
         LiquidBuffer.numLiquidBuffer = 0;
         for (int i = 1; i < Main.maxTilesX - 1; i++)
         {
             for (int num = Main.maxTilesY - 2; num > 0; num--)
             {
                 Tile tile = Main.tile[i, num];
                 tile.checkingLiquid(checkingLiquid: false);
                 if (tile.liquid > 0 && tile.nactive() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
                 {
                     tile.liquid = 0;
                 }
                 else if (tile.liquid > 0)
                 {
                     if (tile.active())
                     {
                         if (tile.lava())
{
                             if (TileObjectData.CheckLavaDeath(tile))
{
                                 KillTile(i, num);
                             }
                         }
                         else if (TileObjectData.CheckWaterDeath(tile))
{
                             KillTile(i, num);
                         }
                     }
                     Tile tile2 = Main.tile[i, num + 1];
                     if ((!tile2.nactive() || !Main.tileSolid[tile2.type] || Main.tileSolidTop[tile2.type]) && tile2.liquid < byte.MaxValue)
                     {
                         if (tile2.liquid > 250)
{
                             tile2.liquid = byte.MaxValue;
                         }
                         else
{
                             Liquid.AddWater(i, num);
                         }
                     }
                     Tile tile3 = Main.tile[i - 1, num];
                     Tile tile4 = Main.tile[i + 1, num];
                     if ((!tile3.nactive() || !Main.tileSolid[tile3.type] || Main.tileSolidTop[tile3.type]) && tile3.liquid != tile.liquid)
                     {
                         Liquid.AddWater(i, num);
                     }
                     else if ((!tile4.nactive() || !Main.tileSolid[tile4.type] || Main.tileSolidTop[tile4.type]) && tile4.liquid != tile.liquid)
                     {
                         Liquid.AddWater(i, num);
                     }
                     if (tile.lava())
                     {
                         if (tile3.liquid > 0 && !tile3.lava())
{
                             Liquid.AddWater(i, num);
                         }
                         else if (tile4.liquid > 0 && !tile4.lava())
{
                             Liquid.AddWater(i, num);
                         }
                         else if (Main.tile[i, num - 1].liquid > 0 && !Main.tile[i, num - 1].lava())
{
                             Liquid.AddWater(i, num);
                         }
                         else if (tile2.liquid > 0 && !tile2.lava())
{
                             Liquid.AddWater(i, num);
                         }
                     }
                 }
             }
         }
         Liquid.tilesIgnoreWater(ignoreSolids: false);
     }
References Tile.active(), Tile.checkingLiquid(), TileObjectData.CheckLavaDeath(), TileObjectData.CheckWaterDeath(), Tile.lava(), Liquid, Tile.liquid, Main.maxTilesX, Main.maxTilesY, Tile.nactive(), LiquidBuffer.numLiquidBuffer, Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by WorldFile.LoadWorld(), and Liquid.UpdateLiquid().