Terraria: WorldGen.GetCommonTreeFoliageData
GetCommonTreeFoliageData()
static bool WorldGen.GetCommonTreeFoliageData (int i, int j, int xoffset, ref int treeFrame, ref int treeStyle, out int floorY, out int topTextureFrameWidth, out int topTextureFrameHeight) inline static
     {
         _ = Main.tile[i, j];
         int num = i + xoffset;
         topTextureFrameWidth = 80;
         topTextureFrameHeight = 80;
         floorY = j;
         int num2 = 0;
         for (int k = 0; k < 100; k++)
         {
             floorY = j + k;
             Tile tile = Main.tile[num, floorY];
             if (tile == null)
             {
                 return false;
             }
             switch (tile.type)
             {
             case 2:
             case 477:
             {
                 int num4 = 0;
                 num4 = ((num <= Main.treeX[0]) ? TreeTops.GetTreeStyle(0) : ((num <= Main.treeX[1]) ? TreeTops.GetTreeStyle(1) : ((num > Main.treeX[2]) ? TreeTops.GetTreeStyle(3) : TreeTops.GetTreeStyle(2))));
                 switch (num4)
                 {
                 case 0:
                     treeStyle = 0;
                     break;
                 case 5:
                     treeStyle = 10;
                     break;
                 default:
                     treeStyle = 5 + num4;
                     break;
                 }
                 return true;
             }
             case 23:
             case 661:
                 treeStyle = 1;
                 return true;
             case 70:
                 treeStyle = 14;
                 return true;
             case 199:
             case 662:
                 treeStyle = 5;
                 return true;
             case 60:
                 topTextureFrameHeight = 96;
                 topTextureFrameWidth = 114;
                 treeStyle = 2;
                 num2 = TreeTops.GetTreeStyle(5);
                 if (num2 == 1)
                 {
                     treeStyle = 11;
                     topTextureFrameWidth = 116;
                 }
                 if ((double)floorY > Main.worldSurface)
                 {
                     treeStyle = 13;
                     topTextureFrameWidth = 116;
                 }
                 return true;
             case 147:
                 treeStyle = 4;
                 num2 = TreeTops.GetTreeStyle(6);
                 if (num2 == 0)
                 {
                     treeStyle = 12;
                     if (i % 10 == 0)
                     {
                         treeStyle = 18;
                     }
                 }
                 if (num2 == 2 || num2 == 3 || num2 == 32 || num2 == 4 || num2 == 42 || num2 == 5 || num2 == 7)
                 {
                     if (num2 % 2 == 0)
                     {
                         if (i < Main.maxTilesX / 2)
{
                             treeStyle = 16;
                         }
                         else
{
                             treeStyle = 17;
                         }
                     }
                     else if (i > Main.maxTilesX / 2)
                     {
                         treeStyle = 16;
                     }
                     else
                     {
                         treeStyle = 17;
                     }
                 }
                 return true;
             case 109:
             case 492:
             {
                 topTextureFrameHeight = 140;
                 int num3 = (treeStyle = GetHollowTreeFoliageStyle());
                 if (num3 == 19)
                 {
                     topTextureFrameWidth = 120;
                 }
                 if (num3 == 20)
                 {
                     treeStyle = 20;
                     if (i % 6 == 1)
                     {
                         treeFrame += 3;
                     }
                     else if (i % 6 == 2)
                     {
                         treeFrame += 6;
                     }
                     else if (i % 6 == 3)
                     {
                         treeFrame += 9;
                     }
                     else if (i % 6 == 4)
                     {
                         treeFrame += 12;
                     }
                     else if (i % 6 == 5)
                     {
                         treeFrame += 15;
                     }
                 }
                 else if (i % 3 == 1)
                 {
                     treeFrame += 3;
                 }
                 else if (i % 3 == 2)
                 {
                     treeFrame += 6;
                 }
                 return true;
             }
             }
         }
         return false;
     }
References TreeTopsInfo.GetTreeStyle(), Main.maxTilesX, Main.tile, Main.treeX, Tile.type, and Main.worldSurface.
Referenced by TileDrawing.DrawTrees(), and TileDrawing.MakeExtraPreparations().