Terraria: System.Xml.XmlSubtreeReader.FinishReadContentAsBinary
FinishReadContentAsBinary()
bool System.Xml.XmlSubtreeReader.FinishReadContentAsBinary () inline private
Definition at line 1271 of file XmlSubtreeReader.cs.
    {
        byte[] buffer = new byte[256];
        if (_state == State.ReadContentAsBase64)
        {
            while (reader.ReadContentAsBase64(buffer, 0, 256) > 0)
            {
            }
        }
        else
        {
            while (reader.ReadContentAsBinHex(buffer, 0, 256) > 0)
            {
            }
        }
        _state = State.Interactive;
        ProcessNamespaces();
        if (reader.Depth == _initialDepth)
        {
            _state = State.EndOfFile;
            SetEmptyNode();
            return false;
        }
        return true;
    }
References System.Xml.XmlSubtreeReader._initialDepth, System.Xml.XmlSubtreeReader._state, System.buffer, System.Xml.XmlReader.Depth, System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlReader.ReadContentAsBase64(), System.Xml.XmlReader.ReadContentAsBinHex(), System.Xml.XmlWrappingReader.reader, and System.Xml.XmlSubtreeReader.SetEmptyNode().
Referenced by System.Xml.XmlSubtreeReader.Read(), and System.Xml.XmlSubtreeReader.Skip().