Terraria: WorldGen.BroadcastText
BroadcastText() [2/5]
static void WorldGen.BroadcastText (NetworkText text, Color color) inline static
     {
         if (Main.netMode == 0)
         {
             Main.NewText(text.ToString(), color.R, color.G, color.B);
         }
         else if (Main.netMode == 2)
         {
             ChatHelper.BroadcastChatMessage(text, color);
         }
     }
References ChatHelper.BroadcastChatMessage(), Main.netMode, Main.NewText(), and NetworkText.ToString().