Terraria: WorldGen.PlayLiquidChangeSound
PlayLiquidChangeSound()
static void WorldGen.PlayLiquidChangeSound (TileChangeType eventType, int x, int y, int count = 1) inline static
     {
         switch (eventType)
         {
         case TileChangeType.LavaWater:
             SoundEngine.PlaySound(SoundID.LiquidsWaterLava, x * 16 + count * 8, y * 16 + count * 8);
             break;
         case TileChangeType.HoneyWater:
             SoundEngine.PlaySound(SoundID.LiquidsHoneyWater, x * 16 + count * 8, y * 16 + count * 8);
             break;
         case TileChangeType.HoneyLava:
             SoundEngine.PlaySound(SoundID.LiquidsHoneyLava, x * 16 + count * 8, y * 16 + count * 8);
             break;
         case TileChangeType.ShimmerWater:
             SoundEngine.PlaySound(19, x * 16 + count * 8, y * 16 + count * 8, 4);
             break;
         case TileChangeType.ShimmerLava:
             SoundEngine.PlaySound(19, x * 16 + count * 8, y * 16 + count * 8, 4);
             break;
         case TileChangeType.ShimmerHoney:
             SoundEngine.PlaySound(19, x * 16 + count * 8, y * 16 + count * 8, 4);
             break;
         }
     }
References SoundID.LiquidsHoneyLava, SoundID.LiquidsHoneyWater, SoundID.LiquidsWaterLava, and SoundEngine.PlaySound().
Referenced by Liquid.LiquidCheck(), and Main.OnTileChangeEvent().