Terraria: WorldGen.SmashAltar
SmashAltar()
static void WorldGen.SmashAltar (int i, int j) inline static
     {
         if (Main.netMode == 1 || !Main.hardMode || noTileActions || gen)
         {
             return;
         }
         int num = altarCount % 3;
         int num2 = altarCount / 3 + 1;
         double num3 = (double)Main.maxTilesX / 4200.0;
         int num4 = 1 - num;
         num3 = num3 * 310.0 - (double)(85 * num);
         num3 *= 0.85;
         num3 /= (double)num2;
         bool flag = false;
         if (Main.drunkWorld)
         {
             if (SavedOreTiers.Adamantite == 111)
             {
                 SavedOreTiers.Adamantite = 223;
             }
             else if (SavedOreTiers.Adamantite == 223)
             {
                 SavedOreTiers.Adamantite = 111;
             }
         }
         switch (num)
         {
         case 0:
         {
             if (SavedOreTiers.Cobalt == -1)
             {
                 flag = true;
                 SavedOreTiers.Cobalt = 107;
                 if (genRand.Next(2) == 0)
                 {
                     SavedOreTiers.Cobalt = 221;
                 }
             }
             int num6 = 12;
             if (SavedOreTiers.Cobalt == 221)
             {
                 num6 += 9;
                 num3 *= 0.8999999761581421;
             }
             if (Main.netMode == 0)
             {
                 Main.NewText(Lang.misc[num6].Value, 50, byte.MaxValue, 130);
             }
             else if (Main.netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[num6].Key), new Color(50, 255, 130));
             }
             num = SavedOreTiers.Cobalt;
             num3 *= 1.0499999523162842;
             break;
         }
         case 1:
         {
             if (Main.drunkWorld)
             {
                 if (SavedOreTiers.Mythril == 108)
                 {
                     SavedOreTiers.Mythril = 222;
                 }
                 else if (SavedOreTiers.Mythril == 222)
                 {
                     SavedOreTiers.Mythril = 108;
                 }
             }
             if (SavedOreTiers.Mythril == -1)
             {
                 flag = true;
                 SavedOreTiers.Mythril = 108;
                 if (genRand.Next(2) == 0)
                 {
                     SavedOreTiers.Mythril = 222;
                 }
             }
             int num7 = 13;
             if (SavedOreTiers.Mythril == 222)
             {
                 num7 += 9;
                 num3 *= 0.8999999761581421;
             }
             if (Main.netMode == 0)
             {
                 Main.NewText(Lang.misc[num7].Value, 50, byte.MaxValue, 130);
             }
             else if (Main.netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[num7].Key), new Color(50, 255, 130));
             }
             num = SavedOreTiers.Mythril;
             break;
         }
         default:
         {
             if (Main.drunkWorld)
             {
                 if (SavedOreTiers.Cobalt == 107)
                 {
                     SavedOreTiers.Cobalt = 221;
                 }
                 else if (SavedOreTiers.Cobalt == 221)
                 {
                     SavedOreTiers.Cobalt = 107;
                 }
             }
             if (SavedOreTiers.Adamantite == -1)
             {
                 flag = true;
                 SavedOreTiers.Adamantite = 111;
                 if (genRand.Next(2) == 0)
                 {
                     SavedOreTiers.Adamantite = 223;
                 }
             }
             int num5 = 14;
             if (SavedOreTiers.Adamantite == 223)
             {
                 num5 += 9;
                 num3 *= 0.8999999761581421;
             }
             if (Main.netMode == 0)
             {
                 Main.NewText(Lang.misc[num5].Value, 50, byte.MaxValue, 130);
             }
             else if (Main.netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[num5].Key), new Color(50, 255, 130));
             }
             num = SavedOreTiers.Adamantite;
             break;
         }
         }
         if (flag)
         {
             NetMessage.SendData(7);
         }
         for (int k = 0; (double)k < num3; k++)
         {
             int i2 = genRand.Next(100, Main.maxTilesX - 100);
             double num8 = Main.worldSurface;
             if (num == 108 || num == 222)
             {
                 num8 = Main.rockLayer;
             }
             if (num == 111 || num == 223)
             {
                 num8 = (Main.rockLayer + Main.rockLayer + (double)Main.maxTilesY) / 3.0;
             }
             int j2 = genRand.Next((int)num8, Main.maxTilesY - 150);
             if (Main.remixWorld)
             {
                 double num9 = Main.maxTilesX - 350;
                 if (num == 108 || num == 222)
                 {
                     num9 = (Main.rockLayer + Main.rockLayer + (double)Main.maxTilesY - 350.0) / 3.0;
                 }
                 if (num == 111 || num == 223)
                 {
                     num9 = Main.rockLayer - 25.0;
                 }
                 j2 = genRand.Next((int)Main.worldSurface + 15, (int)num9);
             }
             if (Main.tenthAnniversaryWorld)
             {
                 OreRunner(i2, j2, genRand.Next(5, 11 + num4), genRand.Next(5, 11 + num4), (ushort)num);
             }
             else
             {
                 OreRunner(i2, j2, genRand.Next(5, 9 + num4), genRand.Next(5, 9 + num4), (ushort)num);
             }
         }
         if (Main.netMode != 1)
         {
             int num10 = Main.rand.Next(2) + 1;
             for (int l = 0; l < num10; l++)
             {
                 NPC.SpawnOnPlayer(Player.FindClosest(new Vector2(i * 16, j * 16), 16, 16), 82);
             }
         }
         altarCount++;
         AchievementsHelper.NotifyProgressionEvent(6);
     }
References WorldGen.SavedOreTiers.Adamantite, ChatHelper.BroadcastChatMessage(), WorldGen.SavedOreTiers.Cobalt, Color, Main.drunkWorld, Player.FindClosest(), NetworkText.FromKey(), Main.hardMode, LocalizedText.Key, Main.maxTilesX, Main.maxTilesY, Lang.misc, WorldGen.SavedOreTiers.Mythril, Main.netMode, Main.NewText(), UnifiedRandom.Next(), AchievementsHelper.NotifyProgressionEvent(), Main.rand, Main.remixWorld, Main.rockLayer, NetMessage.SendData(), NPC.SpawnOnPlayer(), Main.tenthAnniversaryWorld, LocalizedText.Value, and Main.worldSurface.