Terraria: System.Xml.XmlSubtreeReader.Close
Close()
override void System.Xml.XmlSubtreeReader.Close () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 517 of file XmlSubtreeReader.cs.
    {
        if (_state == State.Closed)
        {
            return;
        }
        try
        {
            if (_state != State.EndOfFile)
            {
                reader.MoveToElement();
                if (reader.Depth == _initialDepth && reader.NodeType == XmlNodeType.Element && !reader.IsEmptyElement)
                {
                    reader.Read();
                }
                while (reader.Depth > _initialDepth && reader.Read())
                {
                }
            }
        }
        catch
        {
        }
        finally
        {
            _curNsAttr = -1;
            _useCurNode = false;
            _state = State.Closed;
            SetEmptyNode();
        }
    }
References System.Xml.XmlSubtreeReader._curNsAttr, System.Xml.XmlSubtreeReader._initialDepth, System.Xml.XmlSubtreeReader._state, System.Xml.XmlSubtreeReader._useCurNode, System.Xml.XmlReader.Depth, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.XmlWrappingReader.reader, and System.Xml.XmlSubtreeReader.SetEmptyNode().
Referenced by System.Xml.XmlSubtreeReader.Dispose().