Terraria: WorldGen.dropXmasTree
dropXmasTree()
static void WorldGen.dropXmasTree (int x, int y, int obj) inline static
     {
         int num = x;
         int num2 = y;
         if (Main.tile[x, y].frameX < 10)
         {
             num -= Main.tile[x, y].frameX;
             num2 -= Main.tile[x, y].frameY;
         }
         int num3 = 0;
         if ((Main.tile[num, num2].frameY & 1) == 1)
         {
             num3++;
         }
         if ((Main.tile[num, num2].frameY & 2) == 2)
         {
             num3 += 2;
         }
         if ((Main.tile[num, num2].frameY & 4) == 4)
         {
             num3 += 4;
         }
         int num4 = 0;
         if ((Main.tile[num, num2].frameY & 8) == 8)
         {
             num4++;
         }
         if ((Main.tile[num, num2].frameY & 0x10) == 16)
         {
             num4 += 2;
         }
         if ((Main.tile[num, num2].frameY & 0x20) == 32)
         {
             num4 += 4;
         }
         int num5 = 0;
         if ((Main.tile[num, num2].frameY & 0x40) == 64)
         {
             num5++;
         }
         if ((Main.tile[num, num2].frameY & 0x80) == 128)
         {
             num5 += 2;
         }
         if ((Main.tile[num, num2].frameY & 0x100) == 256)
         {
             num5 += 4;
         }
         if ((Main.tile[num, num2].frameY & 0x200) == 512)
         {
             num5 += 8;
         }
         int num6 = 0;
         if ((Main.tile[num, num2].frameY & 0x400) == 1024)
         {
             num6++;
         }
         if ((Main.tile[num, num2].frameY & 0x800) == 2048)
         {
             num6 += 2;
         }
         if ((Main.tile[num, num2].frameY & 0x1000) == 4096)
         {
             num6 += 4;
         }
         if ((Main.tile[num, num2].frameY & 0x2000) == 8192)
         {
             num6 += 8;
         }
         if (obj == 0 && num3 > 0)
         {
             int number = Item.NewItem(GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, 1874 + num3 - 1);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(21, -1, -1, null, number, 1f);
             }
         }
         else if (obj == 1 && num4 > 0)
         {
             int number2 = Item.NewItem(GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, 1878 + num4 - 1);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(21, -1, -1, null, number2, 1f);
             }
         }
         else if (obj == 2 && num5 > 0)
         {
             int number3 = Item.NewItem(GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, 1884 + num5 - 1);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(21, -1, -1, null, number3, 1f);
             }
         }
         else if (obj == 3 && num6 > 0)
         {
             int number4 = Item.NewItem(GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, 1895 + num6 - 1);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(21, -1, -1, null, number4, 1f);
             }
         }
     }
References Tile.frameX, Tile.frameY, Main.netMode, Item.NewItem(), NetMessage.SendData(), and Main.tile.
Referenced by Player.PlaceThing_XMasTreeTops().