Terraria: WorldGen.JustQuit
JustQuit()
static void WorldGen.JustQuit () inline static
     {
         try
         {
             SoundEngine.PlaySound(34, -1, -1, 0);
             SoundEngine.PlaySound(35, -1, -1, 0);
         }
         catch
         {
         }
         Main.invasionProgress = -1;
         Main.invasionProgressDisplayLeft = 0;
         Main.invasionProgressAlpha = 0f;
         Main.invasionProgressIcon = 0;
         Main.menuMode = 10;
         Main.gameMenu = true;
         SoundEngine.StopTrackedSounds();
         CaptureInterface.ResetFocus();
         Main.ActivePlayerFileData.StopPlayTimer();
         Main.fastForwardTimeToDawn = false;
         Main.fastForwardTimeToDusk = false;
         Main.UpdateTimeRate();
         if (Main.netMode == 0)
         {
             Main.GoToWorldSelect();
             Main.player[Main.myPlayer].position = new Vector2(0f, 0f);
         }
         else if (Main.netMode == 1)
         {
             Main.menuMode = 0;
             Netplay.Disconnect = true;
             Main.netMode = 0;
         }
     }
References Main.ActivePlayerFileData, Netplay.Disconnect, Main.fastForwardTimeToDawn, Main.fastForwardTimeToDusk, Main.gameMenu, Main.GoToWorldSelect(), Main.invasionProgress, Main.invasionProgressAlpha, Main.invasionProgressDisplayLeft, Main.invasionProgressIcon, Main.menuMode, Main.myPlayer, Main.netMode, Main.player, SoundEngine.PlaySound(), Entity.position, CaptureInterface.ResetFocus(), PlayerFileData.StopPlayTimer(), SoundEngine.StopTrackedSounds(), and Main.UpdateTimeRate().