Terraria: WorldGen.MineHouse
MineHouse()
static void WorldGen.MineHouse (int i, int j) inline static
     {
         if (i < 50 || i > Main.maxTilesX - 50 || j < 50 || j > Main.maxTilesY - 50)
         {
             return;
         }
         int num = genRand.Next(6, 12);
         int num2 = genRand.Next(3, 6);
         int num3 = genRand.Next(15, 30);
         int num4 = genRand.Next(15, 30);
         if (SolidTile(i, j) || Main.tile[i, j].wall > 0)
         {
             return;
         }
         int num5 = j - num;
         int num6 = j + num2;
         for (int k = 0; k < 2; k++)
         {
             bool flag = true;
             int num7 = i;
             int num8 = j;
             int num9 = -1;
             int num10 = num3;
             if (k == 1)
             {
                 num9 = 1;
                 num10 = num4;
                 num7++;
             }
             while (flag)
             {
                 if (num8 - num < num5)
                 {
                     num5 = num8 - num;
                 }
                 if (num8 + num2 > num6)
                 {
                     num6 = num8 + num2;
                 }
                 for (int l = 0; l < 2; l++)
                 {
                     int num11 = num8;
                     bool flag2 = true;
                     int num12 = num;
                     int num13 = -1;
                     if (l == 1)
                     {
                         num11++;
                         num12 = num2;
                         num13 = 1;
                     }
                     while (flag2)
                     {
                         if (num7 != i && Main.tile[num7 - num9, num11].wall != 27 && (SolidTile(num7 - num9, num11) || !Main.tile[num7 - num9, num11].active() || Main.tile[num7 - num9, num11].halfBrick() || Main.tile[num7 - num9, num11].slope() != 0))
{
                             Main.tile[num7 - num9, num11].active(active: true);
                             Main.tile[num7 - num9, num11].type = 30;
                         }
                         if (SolidTile(num7 - 1, num11) || Main.tile[num7 - 1, num11].halfBrick() || Main.tile[num7 - 1, num11].slope() != 0)
{
                             Main.tile[num7 - 1, num11].type = 30;
                         }
                         if (SolidTile(num7 + 1, num11) || Main.tile[num7 + 1, num11].halfBrick() || Main.tile[num7 + 1, num11].slope() != 0)
{
                             Main.tile[num7 + 1, num11].type = 30;
                         }
                         if (SolidTile(num7, num11) || Main.tile[num7, num11].halfBrick() || Main.tile[num7, num11].slope() != 0)
{
                             int num14 = 0;
                             if (SolidTile(num7 - 1, num11))
{
                                 num14++;
                             }
                             if (SolidTile(num7 + 1, num11))
{
                                 num14++;
                             }
                             if (SolidTile(num7, num11 - 1))
{
                                 num14++;
                             }
                             if (SolidTile(num7, num11 + 1))
{
                                 num14++;
                             }
                             if (num14 < 2)
{
                                 Main.tile[num7, num11].active(active: false);
                             }
                             else
{
                                 flag2 = false;
                                 Main.tile[num7, num11].type = 30;
                             }
                         }
                         else
{
                             Main.tile[num7, num11].wall = 27;
                             Main.tile[num7, num11].liquid = 0;
                             Main.tile[num7, num11].lava(lava: false);
                         }
                         num11 += num13;
                         num12--;
                         if (num12 <= 0)
{
                             if (!Main.tile[num7, num11].active())
{
                                 Main.tile[num7, num11].active(active: true);
                                 Main.tile[num7, num11].type = 30;
                             }
                             flag2 = false;
                         }
                     }
                 }
                 num10--;
                 num7 += num9;
                 if (SolidTile(num7, num8))
                 {
                     int num15 = 0;
                     int num16 = 0;
                     int num17 = num8;
                     bool flag3 = true;
                     while (flag3)
                     {
                         num17--;
                         num15++;
                         if (SolidTile(num7 - num9, num17))
{
                             num15 = 999;
                             flag3 = false;
                         }
                         else if (!SolidTile(num7, num17))
{
                             flag3 = false;
                         }
                     }
                     num17 = num8;
                     flag3 = true;
                     while (flag3)
                     {
                         num17++;
                         num16++;
                         if (SolidTile(num7 - num9, num17))
{
                             num16 = 999;
                             flag3 = false;
                         }
                         else if (!SolidTile(num7, num17))
{
                             flag3 = false;
                         }
                     }
                     if (num16 <= num15)
                     {
                         if (num16 > num2)
{
                             num10 = 0;
                         }
                         else
{
                             num8 += num16 + 1;
                         }
                     }
                     else if (num15 > num)
                     {
                         num10 = 0;
                     }
                     else
                     {
                         num8 -= num15 + 1;
                     }
                 }
                 if (num10 <= 0)
                 {
                     flag = false;
                 }
             }
         }
         int num18 = i - num3 - 1;
         int num19 = i + num4 + 2;
         int num20 = num5 - 1;
         int num21 = num6 + 2;
         for (int m = num18; m < num19; m++)
         {
             for (int n = num20; n < num21; n++)
             {
                 if (Main.tile[m, n].wall == 27 && !Main.tile[m, n].active())
                 {
                     if (Main.tile[m - 1, n].wall != 27 && m < i && !SolidTile(m - 1, n))
                     {
                         PlaceTile(m, n, 30, mute: true);
                         Main.tile[m, n].wall = 0;
                     }
                     if (Main.tile[m + 1, n].wall != 27 && m > i && !SolidTile(m + 1, n))
                     {
                         PlaceTile(m, n, 30, mute: true);
                         Main.tile[m, n].wall = 0;
                     }
                     for (int num22 = m - 1; num22 <= m + 1; num22++)
                     {
                         for (int num23 = n - 1; num23 <= n + 1; num23++)
{
                             if (SolidTile(num22, num23))
{
                                 Main.tile[num22, num23].type = 30;
                             }
                         }
                     }
                 }
                 if (Main.tile[m, n].type == 30 && Main.tile[m - 1, n].wall == 27 && Main.tile[m + 1, n].wall == 27 && (Main.tile[m, n - 1].wall == 27 || Main.tile[m, n - 1].active()) && (Main.tile[m, n + 1].wall == 27 || Main.tile[m, n + 1].active()))
                 {
                     Main.tile[m, n].active(active: false);
                     Main.tile[m, n].wall = 27;
                 }
             }
         }
         for (int num24 = num18; num24 < num19; num24++)
         {
             for (int num25 = num20; num25 < num21; num25++)
             {
                 if (Main.tile[num24, num25].type == 30)
                 {
                     if (Main.tile[num24 - 1, num25].wall == 27 && Main.tile[num24 + 1, num25].wall == 27 && !Main.tile[num24 - 1, num25].active() && !Main.tile[num24 + 1, num25].active())
                     {
                         Main.tile[num24, num25].active(active: false);
                         Main.tile[num24, num25].wall = 27;
                     }
                     if (!TileID.Sets.BasicChest[Main.tile[num24, num25 - 1].type] && Main.tile[num24 - 1, num25].wall == 27 && Main.tile[num24 + 1, num25].type == 30 && Main.tile[num24 + 2, num25].wall == 27 && !Main.tile[num24 - 1, num25].active() && !Main.tile[num24 + 2, num25].active())
                     {
                         Main.tile[num24, num25].active(active: false);
                         Main.tile[num24, num25].wall = 27;
                         Main.tile[num24 + 1, num25].active(active: false);
                         Main.tile[num24 + 1, num25].wall = 27;
                     }
                     if (Main.tile[num24, num25 - 1].wall == 27 && Main.tile[num24, num25 + 1].wall == 27 && !Main.tile[num24, num25 - 1].active() && !Main.tile[num24, num25 + 1].active())
                     {
                         Main.tile[num24, num25].active(active: false);
                         Main.tile[num24, num25].wall = 27;
                     }
                 }
             }
         }
         for (int num26 = num18; num26 < num19; num26++)
         {
             for (int num27 = num21; num27 > num20; num27--)
             {
                 bool flag4 = false;
                 if (Main.tile[num26, num27].active() && Main.tile[num26, num27].type == 30)
                 {
                     int num28 = -1;
                     for (int num29 = 0; num29 < 2; num29++)
                     {
                         if (!SolidTile(num26 + num28, num27) && Main.tile[num26 + num28, num27].wall == 0)
{
                             int num30 = 0;
                             int num31 = num27;
                             int num32 = num27;
                             while (Main.tile[num26, num31].active() && Main.tile[num26, num31].type == 30 && !SolidTile(num26 + num28, num31) && Main.tile[num26 + num28, num31].wall == 0)
{
                                 num31--;
                                 num30++;
                             }
                             num31++;
                             int num33 = num31 + 1;
                             if (num30 > 4)
{
                                 if (genRand.Next(2) == 0)
{
                                     num31 = num32 - 1;
                                     bool flag5 = true;
                                     for (int num34 = num26 - 2; num34 <= num26 + 2; num34++)
{
                                         for (int num35 = num31 - 2; num35 <= num31; num35++)
{
                                             if (num34 != num26 && Main.tile[num34, num35].active())
{
                                                 flag5 = false;
                                             }
                                         }
                                     }
                                     if (flag5)
{
                                         Main.tile[num26, num31].active(active: false);
                                         Main.tile[num26, num31 - 1].active(active: false);
                                         Main.tile[num26, num31 - 2].active(active: false);
                                         PlaceTile(num26, num31, 10, mute: true);
                                         flag4 = true;
                                     }
                                 }
                                 if (!flag4)
{
                                     for (int num36 = num33; num36 < num32; num36++)
{
                                         Main.tile[num26, num36].type = 124;
                                     }
                                 }
                             }
                         }
                         num28 = 1;
                     }
                 }
                 if (flag4)
                 {
                     break;
                 }
             }
         }
         int num37 = genRand.Next(1, 2);
         if (genRand.Next(4) == 0)
         {
             num37 = 0;
         }
         if (genRand.Next(6) == 0)
         {
             num37++;
         }
         if (genRand.Next(10) == 0)
         {
             num37++;
         }
         for (int num38 = 0; num38 < num37; num38++)
         {
             int num39 = 0;
             int num40 = genRand.Next(num18, num19);
             int num41 = genRand.Next(num20, num21);
             while (!Main.wallHouse[Main.tile[num40, num41].wall] || Main.tile[num40, num41].active())
             {
                 num39++;
                 if (num39 > 1000)
                 {
                     break;
                 }
                 num40 = genRand.Next(num18, num19);
                 num41 = genRand.Next(num20, num21);
             }
             if (num39 > 1000)
             {
                 break;
             }
             int num42 = num40;
             int num43 = num40;
             int num44 = num41;
             int num45 = num41;
             int num46 = 0;
             for (int num47 = 0; num47 < 2; num47++)
             {
                 num42 = num40;
                 num43 = num40;
                 while (!Main.tile[num42, num41].active() && Main.wallHouse[Main.tile[num42, num41].wall])
                 {
                     num42--;
                 }
                 num42++;
                 for (; !Main.tile[num43, num41].active() && Main.wallHouse[Main.tile[num43, num41].wall]; num43++)
                 {
                 }
                 num43--;
                 i = (num42 + num43) / 2;
                 num44 = num41;
                 num45 = num41;
                 while (!Main.tile[num40, num44].active() && Main.wallHouse[Main.tile[num40, num44].wall])
                 {
                     num44--;
                 }
                 num44++;
                 for (; !Main.tile[num40, num45].active() && Main.wallHouse[Main.tile[num40, num45].wall]; num45++)
                 {
                 }
                 num45--;
                 num41 = (num44 + num45) / 2;
             }
             num42 = num40;
             num43 = num40;
             while (!Main.tile[num42, num41].active() && !Main.tile[num42, num41 - 1].active() && !Main.tile[num42, num41 + 1].active())
             {
                 num42--;
             }
             num42++;
             for (; !Main.tile[num43, num41].active() && !Main.tile[num43, num41 - 1].active() && !Main.tile[num43, num41 + 1].active(); num43++)
             {
             }
             num43--;
             num44 = num41;
             num45 = num41;
             while (!Main.tile[num40, num44].active() && !Main.tile[num40 - 1, num44].active() && !Main.tile[num40 + 1, num44].active())
             {
                 num44--;
             }
             num44++;
             for (; !Main.tile[num40, num45].active() && !Main.tile[num40 - 1, num45].active() && !Main.tile[num40 + 1, num45].active(); num45++)
             {
             }
             num45--;
             num40 = (num42 + num43) / 2;
             num41 = (num44 + num45) / 2;
             int num48 = num43 - num42;
             num46 = num45 - num44;
             if (num48 <= 7 || num46 <= 5)
             {
                 continue;
             }
             int num49 = 0;
             if (nearPicture2(i, num41))
             {
                 num49 = -1;
             }
             if (num49 == 0)
             {
                 PaintingEntry paintingEntry = RandHousePicture();
                 if (!nearPicture(num40, num41))
                 {
                     PlaceTile(num40, num41, paintingEntry.tileType, mute: true, forced: false, -1, paintingEntry.style);
                 }
             }
         }
         int num50;
         for (num50 = num18; num50 < num19; num50++)
         {
             bool flag6 = true;
             for (int num51 = num20; num51 < num21; num51++)
             {
                 for (int num52 = num50 - 3; num52 <= num50 + 3; num52++)
                 {
                     if (Main.tile[num52, num51].active() && (!SolidTile(num52, num51) || Main.tile[num52, num51].type == 10))
                     {
                         flag6 = false;
                     }
                 }
             }
             if (flag6)
             {
                 for (int num53 = num20; num53 < num21; num53++)
                 {
                     if (Main.tile[num50, num53].wall == 27 && !Main.tile[num50, num53].active())
                     {
                         PlaceTile(num50, num53, 124, mute: true);
                     }
                 }
             }
             num50 += genRand.Next(4);
         }
         for (int num54 = 0; num54 < 4; num54++)
         {
             int num55 = genRand.Next(num18 + 2, num19 - 1);
             int num56 = genRand.Next(num20 + 2, num21 - 1);
             while (Main.tile[num55, num56].wall != 27)
             {
                 num55 = genRand.Next(num18 + 2, num19 - 1);
                 num56 = genRand.Next(num20 + 2, num21 - 1);
             }
             while (Main.tile[num55, num56].active())
             {
                 num56--;
             }
             for (; !Main.tile[num55, num56].active(); num56++)
             {
             }
             num56--;
             if (Main.tile[num55, num56].wall != 27)
             {
                 continue;
             }
             if (genRand.Next(3) == 0)
             {
                 int num57 = genRand.Next(9);
                 if (num57 == 0)
                 {
                     num57 = 14;
                 }
                 if (num57 == 1)
                 {
                     num57 = 16;
                 }
                 if (num57 == 2)
                 {
                     num57 = 18;
                 }
                 if (num57 == 3)
                 {
                     num57 = 86;
                 }
                 if (num57 == 4)
                 {
                     num57 = 87;
                 }
                 if (num57 == 5)
                 {
                     num57 = 94;
                 }
                 if (num57 == 6)
                 {
                     num57 = 101;
                 }
                 if (num57 == 7)
                 {
                     num57 = 104;
                 }
                 if (num57 == 8)
                 {
                     num57 = 106;
                 }
                 PlaceTile(num55, num56, num57, mute: true);
             }
             else if (GenVars.statueList != null)
             {
                 int num58 = genRand.Next(2, GenVars.statueList.Length);
                 PlaceTile(num55, num56, GenVars.statueList[num58].X, mute: true, forced: true, -1, GenVars.statueList[num58].Y);
             }
         }
         for (int num59 = 0; num59 < 40; num59++)
         {
             int num60 = genRand.Next(num18 + 2, num19 - 1);
             int num61 = genRand.Next(num20 + 2, num21 - 1);
             while (Main.tile[num60, num61].wall != 27)
             {
                 num60 = genRand.Next(num18 + 2, num19 - 1);
                 num61 = genRand.Next(num20 + 2, num21 - 1);
             }
             while (Main.tile[num60, num61].active())
             {
                 num61--;
             }
             for (; !Main.tile[num60, num61].active(); num61++)
             {
             }
             num61--;
             if (Main.tile[num60, num61].wall == 27 && genRand.Next(2) == 0)
             {
                 int style = genRand.Next(22, 26);
                 PlaceTile(num60, num61, 186, mute: true, forced: false, -1, style);
             }
         }
         for (int num62 = 0; num62 < 20; num62++)
         {
             int num63 = genRand.Next(num18 + 2, num19 - 1);
             int num64 = genRand.Next(num20 + 2, num21 - 1);
             while (Main.tile[num63, num64].wall != 27)
             {
                 num63 = genRand.Next(num18 + 2, num19 - 1);
                 num64 = genRand.Next(num20 + 2, num21 - 1);
             }
             while (Main.tile[num63, num64].active())
             {
                 num64--;
             }
             for (; !Main.tile[num63, num64].active(); num64++)
             {
             }
             num64--;
             if (Main.tile[num63, num64].wall == 27 && genRand.Next(2) == 0)
             {
                 int x = genRand.Next(31, 34);
                 PlaceSmallPile(num63, num64, x, 1, 185);
             }
         }
         for (int num65 = 0; num65 < 15; num65++)
         {
             int num66 = genRand.Next(num18 + 2, num19 - 1);
             int num67 = genRand.Next(num20 + 2, num21 - 1);
             while (Main.tile[num66, num67].wall != 27)
             {
                 num66 = genRand.Next(num18 + 2, num19 - 1);
                 num67 = genRand.Next(num20 + 2, num21 - 1);
             }
             while (Main.tile[num66, num67].active())
             {
                 num67--;
             }
             while (num67 > 0 && !Main.tile[num66, num67 - 1].active())
             {
                 num67--;
             }
             if (Main.tile[num66, num67].wall != 27)
             {
                 continue;
             }
             int num68 = 4;
             int style2 = 0;
             if (genRand.Next(10) < 9)
             {
                 num68 = -1;
             }
             else
             {
                 num68 = 34;
                 style2 = genRand.Next(6);
             }
             if (num68 <= 0)
             {
                 continue;
             }
             PlaceTile(num66, num67, num68, mute: true, forced: false, -1, style2);
             if (Main.tile[num66, num67].type != num68)
             {
                 continue;
             }
             if (num68 == 4)
             {
                 Main.tile[num66, num67].frameX += 54;
                 continue;
             }
             int num69 = num66;
             int num70 = num67;
             num67 = num70 - Main.tile[num69, num70].frameY % 54 / 18;
             num66 = Main.tile[num69, num70].frameX / 18;
             if (num66 > 2)
             {
                 num66 -= 3;
             }
             num66 = num69 - num66;
             short num71 = 54;
             if (Main.tile[num66, num67].frameX > 0)
             {
                 num71 = -54;
             }
             for (int num72 = num66; num72 < num66 + 3; num72++)
             {
                 for (int num73 = num67; num73 < num67 + 3; num73++)
                 {
                     Main.tile[num72, num73].frameX += num71;
                 }
             }
         }
     }
References Tile.active(), TileID.Sets.BasicChest, Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.lava(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Tile.slope(), SolidTile, GenVars.statueList, PaintingEntry.style, Main.tile, PaintingEntry.tileType, Tile.type, Tile.wall, Main.wallHouse, Point16.X, and Point16.Y.