Terraria: WorldGen.FillWallHolesInSpot
FillWallHolesInSpot()
static bool WorldGen.FillWallHolesInSpot (int originX, int originY, int maxWallsThreshold) inline static private
     {
         if (!InWorld(originX, originY, 2))
         {
             return false;
         }
         List<Point> list = new List<Point>();
         List<Point> list2 = new List<Point>();
         HashSet<Point> hashSet = new HashSet<Point>();
         Dictionary<ushort, int> dictionary = new Dictionary<ushort, int>();
         list2.Add(new Point(originX, originY));
         while (list2.Count > 0)
         {
             list.Clear();
             list.AddRange(list2);
             list2.Clear();
             while (list.Count > 0)
             {
                 if (hashSet.Count >= maxWallsThreshold)
                 {
                     return false;
                 }
                 Point item = list[0];
                 if (hashSet.Contains(item))
                 {
                     list.Remove(item);
                     continue;
                 }
                 if (!InWorld(item.X, item.Y, 1))
                 {
                     list.Remove(item);
                     continue;
                 }
                 hashSet.Add(item);
                 list.Remove(item);
                 Tile tile = Main.tile[item.X, item.Y];
                 if (tile.wall != 0)
                 {
                     if (dictionary.ContainsKey(tile.wall))
                     {
                         dictionary[tile.wall] = dictionary[tile.wall] + 1;
                     }
                     else
                     {
                         dictionary[tile.wall] = 1;
                     }
                     continue;
                 }
                 bool flag = false;
                 if (!flag)
                 {
                     int y = item.Y;
                     for (int i = item.X - 1; i <= item.X + 1; i++)
                     {
                         if (!Main.tile[i, y].active())
{
                             flag = true;
                             break;
                         }
                     }
                 }
                 if (!flag)
                 {
                     int x = item.X;
                     for (int j = item.Y - 1; j <= item.Y + 1; j++)
                     {
                         if (!Main.tile[x, j].active())
{
                             flag = true;
                             break;
                         }
                     }
                 }
                 if (flag)
                 {
                     Point item2 = new Point(item.X - 1, item.Y);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                     item2 = new Point(item.X + 1, item.Y);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                     item2 = new Point(item.X, item.Y - 1);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                     item2 = new Point(item.X, item.Y + 1);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                 }
             }
         }
         if (hashSet.Count == 1)
         {
             return false;
         }
         ushort wall = 0;
         int num = -1;
         foreach (KeyValuePair<ushort, int> item3 in dictionary)
         {
             if (item3.Value > num)
             {
                 wall = item3.Key;
                 num = item3.Value;
             }
         }
         if (num == -1)
         {
             wall = 2;
         }
         foreach (Point item4 in hashSet)
         {
             Tile tile2 = Main.tile[item4.X, item4.Y];
             if (tile2.wall == 0)
             {
                 tile2.wall = wall;
             }
         }
         return true;
     }
References Tile.active(), InWorld(), Main.tile, and Tile.wall.
Referenced by FillWallHolesInColumn().