Terraria: System.Xml.XmlSubtreeReader.ProcessNamespaces
ProcessNamespaces()
void System.Xml.XmlSubtreeReader.ProcessNamespaces () inline private
Definition at line 1096 of file XmlSubtreeReader.cs.
    {
        switch (reader.NodeType)
        {
        case XmlNodeType.Element:
        {
            _nsManager.PushScope();
            string prefix = reader.Prefix;
            string namespaceURI = reader.NamespaceURI;
            if (_nsManager.LookupNamespace(prefix) != namespaceURI)
            {
                AddNamespace(prefix, namespaceURI);
            }
            if (reader.MoveToFirstAttribute())
            {
                do
                {
                    prefix = reader.Prefix;
                    namespaceURI = reader.NamespaceURI;
                    if (Ref.Equal(namespaceURI, _xmlnsUri))
                    {
                        if (prefix.Length == 0)
{
                            _nsManager.AddNamespace(string.Empty, reader.Value);
                            RemoveNamespace(string.Empty, _xmlns);
                        }
                        else
{
                            prefix = reader.LocalName;
                            _nsManager.AddNamespace(prefix, reader.Value);
                            RemoveNamespace(_xmlns, prefix);
                        }
                    }
                    else if (prefix.Length != 0 && _nsManager.LookupNamespace(prefix) != namespaceURI)
                    {
                        AddNamespace(prefix, namespaceURI);
                    }
                }
                while (reader.MoveToNextAttribute());
                reader.MoveToElement();
            }
            if (reader.IsEmptyElement)
            {
                _state = State.PopNamespaceScope;
            }
            break;
        }
        case XmlNodeType.EndElement:
            _state = State.PopNamespaceScope;
            break;
        }
    }
References System.Xml.XmlSubtreeReader._nsManager, System.Xml.XmlSubtreeReader._state, System.Xml.XmlSubtreeReader._xmlns, System.Xml.XmlSubtreeReader._xmlnsUri, System.Xml.XmlSubtreeReader.AddNamespace(), System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.Ref.Equal(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlNamespaceManager.LookupNamespace(), System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.prefix, System.Xml.XmlReader.Prefix, System.Xml.XmlNamespaceManager.PushScope(), System.Xml.XmlWrappingReader.reader, System.Xml.XmlSubtreeReader.RemoveNamespace(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.XmlSubtreeReader.FinishReadContentAsBinary(), System.Xml.XmlSubtreeReader.FinishReadContentAsBinaryAsync(), System.Xml.XmlSubtreeReader.FinishReadContentAsType(), System.Xml.XmlSubtreeReader.FinishReadElementContentAsBinary(), System.Xml.XmlSubtreeReader.FinishReadElementContentAsBinaryAsync(), System.Xml.XmlSubtreeReader.InitReadElementContentAsBinary(), System.Xml.XmlSubtreeReader.InitReadElementContentAsBinaryAsync(), System.Xml.XmlSubtreeReader.Read(), System.Xml.XmlSubtreeReader.ReadAsync(), System.Xml.XmlSubtreeReader.ReadContentAsBase64(), System.Xml.XmlSubtreeReader.ReadContentAsBase64Async(), System.Xml.XmlSubtreeReader.ReadContentAsBinHex(), System.Xml.XmlSubtreeReader.ReadContentAsBinHexAsync(), System.Xml.XmlSubtreeReader.ReadElementContentAsBase64(), System.Xml.XmlSubtreeReader.ReadElementContentAsBase64Async(), System.Xml.XmlSubtreeReader.ReadElementContentAsBinHex(), System.Xml.XmlSubtreeReader.ReadElementContentAsBinHexAsync(), System.Xml.XmlSubtreeReader.Skip(), and System.Xml.XmlSubtreeReader.SkipAsync().