Terraria: System.Xml.XmlSubtreeReader.ReadContentAsBinHexAsync
ReadContentAsBinHexAsync()
override async Task< int > System.Xml.XmlSubtreeReader.ReadContentAsBinHexAsync (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 1665 of file XmlSubtreeReader.cs.
    {
        switch (_state)
        {
        case State.Initial:
        case State.Error:
        case State.EndOfFile:
        case State.Closed:
            return 0;
        case State.PopNamespaceScope:
        case State.ClearNsAttributes:
            switch (NodeType)
            {
            case XmlNodeType.Element:
                throw CreateReadContentAsException("ReadContentAsBinHex");
            case XmlNodeType.EndElement:
                return 0;
            case XmlNodeType.Attribute:
                if (_curNsAttr != -1 && reader.CanReadBinaryContent)
                {
                    CheckBuffer(buffer, index, count);
                    if (count == 0)
                    {
                        return 0;
                    }
                    if (_nsIncReadOffset == 0)
                    {
                        if (_binDecoder != null && _binDecoder is BinHexDecoder)
{
                            _binDecoder.Reset();
                        }
                        else
{
                            _binDecoder = new BinHexDecoder();
                        }
                    }
                    if (_nsIncReadOffset == _curNode.value.Length)
                    {
                        return 0;
                    }
                    _binDecoder.SetNextOutputBuffer(buffer, index, count);
                    _nsIncReadOffset += _binDecoder.Decode(_curNode.value, _nsIncReadOffset, _curNode.value.Length - _nsIncReadOffset);
                    return _binDecoder.DecodedCount;
                }
                goto case XmlNodeType.Text;
            case XmlNodeType.Text:
                return await reader.ReadContentAsBinHexAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
            default:
                return 0;
            }
        case State.Interactive:
            _state = State.ReadContentAsBinHex;
            goto case State.ReadContentAsBinHex;
        case State.ReadContentAsBinHex:
        {
            int num = await reader.ReadContentAsBinHexAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
            if (num == 0)
            {
                _state = State.Interactive;
                ProcessNamespaces();
            }
            return num;
        }
        case State.ReadElementContentAsBase64:
        case State.ReadElementContentAsBinHex:
        case State.ReadContentAsBase64:
            throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
        default:
            return 0;
        }
    }
References System.Xml.XmlSubtreeReader._binDecoder, System.Xml.XmlSubtreeReader._curNode, System.Xml.XmlSubtreeReader._curNsAttr, System.Xml.XmlSubtreeReader._nsIncReadOffset, System.Xml.XmlSubtreeReader._state, System.buffer, System.Xml.XmlReader.CanReadBinaryContent, System.Xml.XmlSubtreeReader.CheckBuffer(), System.count, System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.IncrementalReadDecoder.Decode(), System.Xml.IncrementalReadDecoder.DecodedCount, System.index, System.Xml.XmlSubtreeReader.NodeType, System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlReader.ReadContentAsBinHexAsync(), System.Xml.XmlWrappingReader.reader, System.Xml.IncrementalReadDecoder.Reset(), System.Xml.IncrementalReadDecoder.SetNextOutputBuffer(), System.Xml.XmlSubtreeReader.NodeData.value, and System.SR.Xml_MixingBinaryContentMethods.