Terraria: WorldGen.ShellPile
ShellPile()
static bool WorldGen.ShellPile (int X, int Y) inline static
     {
         //IL_03ef: Unknown result type (might be due to invalid IL or missing references)
         //IL_03f0: Unknown result type (might be due to invalid IL or missing references)
         //IL_03f1: Unknown result type (might be due to invalid IL or missing references)
         //IL_03f6: Unknown result type (might be due to invalid IL or missing references)
         //IL_0449: Unknown result type (might be due to invalid IL or missing references)
         //IL_0467: Unknown result type (might be due to invalid IL or missing references)
         //IL_0123: Unknown result type (might be due to invalid IL or missing references)
         //IL_012a: Unknown result type (might be due to invalid IL or missing references)
         //IL_012f: Unknown result type (might be due to invalid IL or missing references)
         //IL_0134: Unknown result type (might be due to invalid IL or missing references)
         int num = Y;
         while (!SolidTile(X, num))
         {
             num++;
             if ((double)num > Main.worldSurface)
             {
                 return false;
             }
         }
         if (Main.tile[X, num].type != 53)
         {
             return false;
         }
         if (Main.tile[X, num].wall > 0)
         {
             return false;
         }
         num--;
         Vector2D val = default(Vector2D);
         ((Vector2D)(ref val))._002Ector((double)X, (double)num);
         Vector2D val2 = default(Vector2D);
         val2.X = genRand.NextDouble() * 0.6 - 0.3;
         val2.Y = genRand.NextDouble() * 0.5 + 0.5;
         double num2 = genRand.Next(2, 4);
         if (genRand.Next(10) == 0)
         {
             num2 += 1.0;
         }
         int num3 = genRand.Next(3, 6);
         while (num3 > 0)
         {
             num3--;
             for (int i = X - (int)num2 * 4; (double)i <= (double)X + num2 * 4.0; i++)
             {
                 int num4 = num + (int)num2 * 4;
                 while ((double)num4 > (double)num - num2 * 4.0)
                 {
                     double num5 = num2 * (double)genRand.Next(70, 91) * 0.01;
                     Vector2D val3 = val - new Vector2D((double)i, (double)num4);
                     val3.X *= 0.6;
                     if (((Vector2D)(ref val3)).Length() < num5)
                     {
                         if (num4 <= num + 1 || genRand.Next(6) == 0)
{
                             Main.tile[i, num4].type = 495;
                             Main.tile[i, num4].active(active: true);
                             Main.tile[i, num4].halfBrick(halfBrick: false);
                             Main.tile[i, num4].slope(0);
                             if (!Main.tile[i, num4 + 1].active())
{
                                 Main.tile[i, num4 + 1].type = 495;
                                 Main.tile[i, num4 + 1].active(active: true);
                                 Main.tile[i, num4 + 1].halfBrick(halfBrick: false);
                                 Main.tile[i, num4 + 1].slope(0);
                                 if (!Main.tile[i, num4 + 2].active())
{
                                     Main.tile[i, num4 + 2].type = 53;
                                     Main.tile[i, num4 + 2].active(active: true);
                                     Main.tile[i, num4 + 2].halfBrick(halfBrick: false);
                                     Main.tile[i, num4 + 2].slope(0);
                                     if (!Main.tile[i, num4 + 3].active())
{
                                         Main.tile[i, num4 + 3].type = 397;
                                         Main.tile[i, num4 + 3].active(active: true);
                                         Main.tile[i, num4 + 3].halfBrick(halfBrick: false);
                                         Main.tile[i, num4 + 3].slope(0);
                                     }
                                 }
                             }
                             if (!gen)
{
                                 SquareTileFrame(i, num4);
                             }
                         }
                         else if (Main.tile[i, num4].type != 495)
{
                             Main.tile[i, num4].active(active: true);
                             Main.tile[i, num4].halfBrick(halfBrick: false);
                             Main.tile[i, num4].slope(0);
                             Main.tile[i, num4].type = 53;
                             if (!gen)
{
                                 SquareTileFrame(i, num4);
                             }
                         }
                     }
                     num4--;
                 }
             }
             val += val2;
             val2.X += genRand.NextDouble() * 0.2 - 0.1;
             val2.Y += genRand.NextDouble() * 0.2 - 0.1;
             Utils.Clamp(val2.X, -0.3, 0.3);
             Utils.Clamp(val2.Y, 0.5, 1.0);
         }
         return true;
     }
References Tile.active(), gen, genRand, Tile.halfBrick(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Tile.slope(), SolidTile(), SquareTileFrame(), Main.tile, Tile.type, Tile.wall, Main.worldSurface, X, Vector2D.X, Y, and Vector2D.Y.