Terraria: WorldGen.StonePatch
StonePatch()
static bool WorldGen.StonePatch (int X, int Y) inline static
     {
         //IL_042f: Unknown result type (might be due to invalid IL or missing references)
         //IL_0430: Unknown result type (might be due to invalid IL or missing references)
         //IL_0431: Unknown result type (might be due to invalid IL or missing references)
         //IL_0436: Unknown result type (might be due to invalid IL or missing references)
         //IL_0489: Unknown result type (might be due to invalid IL or missing references)
         //IL_04a7: Unknown result type (might be due to invalid IL or missing references)
         //IL_0291: Unknown result type (might be due to invalid IL or missing references)
         //IL_0298: Unknown result type (might be due to invalid IL or missing references)
         //IL_029d: Unknown result type (might be due to invalid IL or missing references)
         //IL_02a2: Unknown result type (might be due to invalid IL or missing references)
         int num = Y;
         while (!SolidTile(X, num))
         {
             num++;
             if ((double)num > Main.worldSurface)
             {
                 return false;
             }
         }
         if (!TileID.Sets.Conversion.Grass[Main.tile[X, num].type] || !TileID.Sets.Conversion.Grass[Main.tile[X - 1, num].type] || !TileID.Sets.Conversion.Grass[Main.tile[X + 1, num].type])
         {
             return false;
         }
         if (Main.tile[X, num].wall > 0)
         {
             return false;
         }
         for (int i = X - 10; i <= X + 10; i++)
         {
             for (int j = num + 7; j <= num + 30; j++)
             {
                 if (!Main.tile[i, j].active() || Main.tileDungeon[Main.tile[i, j].type] || TileID.Sets.Clouds[Main.tile[i, j].type] || TileID.Sets.Conversion.Sand[Main.tile[i, j].type] || Main.tile[i, j].wall == 0 || Main.tile[i, j].type == 199 || Main.tile[i, j].type == 23)
                 {
                     return false;
                 }
             }
         }
         Vector2D val = default(Vector2D);
         ((Vector2D)(ref val))._002Ector((double)X, (double)num);
         Vector2D val2 = default(Vector2D);
         val2.X = genRand.NextDouble() * 0.6 - 0.3;
         val2.Y = genRand.NextDouble() * 0.5 + 0.5;
         double num2 = genRand.Next(13, 18);
         int num3 = genRand.Next(13, 19);
         if (genRand.Next(3) == 0)
         {
             num2 += (double)genRand.Next(3);
         }
         if (genRand.Next(3) == 0)
         {
             num3 += genRand.Next(3);
         }
         while (num3 > 0)
         {
             num3--;
             for (int k = X - (int)num2 * 4; (double)k <= (double)X + num2 * 4.0; k++)
             {
                 for (int l = num - (int)num2 * 4; (double)l <= (double)num + num2 * 4.0; l++)
                 {
                     double num4 = num2 * (0.7 + genRand.NextDouble() * 0.6) * 0.3;
                     if (genRand.Next(8) == 0)
                     {
                         num4 *= 2.0;
                     }
                     Vector2D val3 = val - new Vector2D((double)k, (double)l);
                     if (((Vector2D)(ref val3)).Length() < num4 * 2.0 && !Main.tile[k, l].active() && Main.tile[k, l + 1].active() && Main.tile[k, l + 1].type == 1 && genRand.Next(7) == 0 && SolidTile(k - 1, l + 1) && SolidTile(k + 1, l + 1))
                     {
                         if (genRand.Next(3) != 0)
{
                             PlaceTile(k, l, 186, mute: true, forced: false, -1, genRand.Next(7, 13));
                         }
                         if (genRand.Next(3) != 0)
{
                             PlaceSmallPile(k, l, genRand.Next(6), 1, 185);
                         }
                         PlaceSmallPile(k, l, genRand.Next(6), 0, 185);
                     }
                     if (((Vector2D)(ref val3)).Length() < num4)
                     {
                         if (Main.tileSolid[Main.tile[k, l].type])
{
                             Main.tile[k, l].type = 1;
                         }
                         if (!gen)
{
                             SquareTileFrame(k, l);
                         }
                     }
                 }
             }
             val += val2;
             val2.X += genRand.NextDouble() * 0.2 - 0.1;
             val2.Y += genRand.NextDouble() * 0.2 - 0.1;
             Utils.Clamp(val2.X, -0.3, 0.3);
             Utils.Clamp(val2.Y, 0.5, 1.0);
         }
         return true;
     }
References Tile.active(), TileID.Sets.Clouds, gen, genRand, TileID.Sets.Conversion.Grass, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), PlaceSmallPile(), PlaceTile(), TileID.Sets.Conversion.Sand, SolidTile(), SquareTileFrame(), Main.tile, Main.tileDungeon, Main.tileSolid, Tile.type, Tile.wall, Main.worldSurface, X, Vector2D.X, Y, and Vector2D.Y.