Terraria: System.Xml.XmlSubtreeReader.SetCurrentNode
SetCurrentNode()
void System.Xml.XmlSubtreeReader.SetCurrentNode (NodeData node) inline private
Definition at line 1305 of file XmlSubtreeReader.cs.
    {
        _curNode = node;
        _useCurNode = true;
    }
References System.Xml.XmlSubtreeReader._curNode, System.Xml.XmlSubtreeReader._useCurNode, and System.Xml.Dictionary.
Referenced by System.Xml.XmlSubtreeReader.XmlSubtreeReader(), System.Xml.XmlSubtreeReader.MoveToNsAttribute(), and System.Xml.XmlSubtreeReader.ReadAttributeValue().