Terraria: WorldGen.SquareTileFrame
SquareTileFrame()
static void WorldGen.SquareTileFrame (int i, int j, bool resetFrame = true) inline static
     {
         TileFrame(i - 1, j - 1);
         TileFrame(i - 1, j);
         TileFrame(i - 1, j + 1);
         TileFrame(i, j - 1);
         TileFrame(i, j, resetFrame);
         TileFrame(i, j + 1);
         TileFrame(i + 1, j - 1);
         TileFrame(i + 1, j);
         TileFrame(i + 1, j + 1);
     }
Referenced by Wiring.CheckLogicGate(), NPC.CreateBrickBoxForWallOfFlesh(), Wiring.DeActive(), Liquid.DelWater(), EmptyLiquid(), HiveBiome.FrameOutAllHiveContents(), MessageBuffer.GetData(), Wiring.HitWireSingle(), Player.ItemCheck_UseBuckets(), Liquid.LiquidCheck(), MarblePileWithStatues(), meteor(), OrePatch(), PlaceLiquid(), Player.PlaceThing_Tiles_PlaceIt(), Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck(), Wiring.ReActive(), ShellPile(), Player.Spawn_ForceClearArea(), StonePatch(), Player.TryReplantingTree(), and Wiring.XferWater().