Terraria: System.Xml.XmlSubtreeReader.InitReadElementContentAsBinaryAsync
InitReadElementContentAsBinaryAsync()
async Task< bool > System.Xml.XmlSubtreeReader.InitReadElementContentAsBinaryAsync (State binaryState) inline private
Definition at line 1826 of file XmlSubtreeReader.cs.
    {
        if (NodeType != XmlNodeType.Element)
        {
            throw reader.CreateReadElementContentAsException("ReadElementContentAsBase64");
        }
        bool isEmpty = IsEmptyElement;
        if (!(await ReadAsync().ConfigureAwait(continueOnCapturedContext: false)) || isEmpty)
        {
            return false;
        }
        switch (NodeType)
        {
        case XmlNodeType.Element:
            throw new XmlException(System.SR.Xml_InvalidNodeType, reader.NodeType.ToString(), reader as IXmlLineInfo);
        case XmlNodeType.EndElement:
            ProcessNamespaces();
            await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
            return false;
        default:
            _state = binaryState;
            return true;
        }
    }
References System.Xml.XmlSubtreeReader._state, System.Xml.XmlReader.CreateReadElementContentAsException(), System.Xml.Dictionary, System.Xml.XmlSubtreeReader.IsEmptyElement, System.Xml.XmlReader.NodeType, System.Xml.XmlSubtreeReader.NodeType, System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlSubtreeReader.ReadAsync(), System.Xml.XmlWrappingReader.reader, System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Xml.XmlSubtreeReader.ReadElementContentAsBase64Async(), and System.Xml.XmlSubtreeReader.ReadElementContentAsBinHexAsync().