Terraria: WorldGen.setWorldSize
setWorldSize()
static void WorldGen.setWorldSize () inline static
     {
         Main.bottomWorld = Main.maxTilesY * 16;
         Main.rightWorld = Main.maxTilesX * 16;
         Main.maxSectionsX = Main.maxTilesX / 200;
         Main.maxSectionsY = Main.maxTilesY / 150;
     }
References Main.bottomWorld, Main.maxSectionsX, Main.maxSectionsY, Main.maxTilesX, Main.maxTilesY, and Main.rightWorld.
Referenced by clearWorld(), Main.DrawMenu(), and UIWorldCreation.FinishCreatingWorld().