Terraria: WorldGen.templeCleaner
templeCleaner()
static void WorldGen.templeCleaner (int x, int y) inline static
     {
         int num = 0;
         if (Main.tile[x + 1, y].active() && Main.tile[x + 1, y].type == 226)
         {
             num++;
         }
         if (Main.tile[x - 1, y].active() && Main.tile[x - 1, y].type == 226)
         {
             num++;
         }
         if (Main.tile[x, y + 1].active() && Main.tile[x, y + 1].type == 226)
         {
             num++;
         }
         if (Main.tile[x, y - 1].active() && Main.tile[x, y - 1].type == 226)
         {
             num++;
         }
         if (Main.tile[x, y].active() && Main.tile[x, y].type == 226)
         {
             if (num <= 1)
             {
                 Main.tile[x, y].active(active: false);
                 Main.tile[x, y].wall = 87;
             }
         }
         else if (!Main.tile[x, y].active() && num == 3)
         {
             Main.tile[x, y].active(active: true);
             Main.tile[x, y].type = 226;
             Main.tile[x, y].liquid = 0;
             Main.tile[x, y].slope(0);
             Main.tile[x, y].halfBrick(halfBrick: false);
         }
     }
References Tile.active(), Tile.halfBrick(), Tile.liquid, Tile.slope(), Main.tile, Tile.type, and Tile.wall.