Terraria: WorldGen.FinishDrunkGen
FinishDrunkGen()
static void WorldGen.FinishDrunkGen () inline static private
     {
         byte color = (byte)genRand.Next(13, 25);
         byte b = 16;
         for (int i = 0; i < Main.maxTilesX; i++)
         {
             bool flag = false;
             for (int j = 0; j < Main.maxTilesY; j++)
             {
                 if (!Main.tile[i, j].active() || !Main.tileDungeon[Main.tile[i, j].type])
                 {
                     continue;
                 }
                 if (Main.tile[i, j].type == 44)
                 {
                     color = (byte)genRand.Next(13, 15);
                     if (genRand.Next(2) == 0)
                     {
                         color = (byte)genRand.Next(23, 25);
                     }
                 }
                 if (Main.tile[i, j].type == 43)
                 {
                     color = (byte)genRand.Next(15, 19);
                 }
                 if (Main.tile[i, j].type == 41)
                 {
                     color = (byte)genRand.Next(19, 23);
                 }
             }
             if (flag)
             {
                 break;
             }
         }
         for (int k = 10; k < Main.maxTilesX - 10; k++)
         {
             for (int l = 10; l < Main.maxTilesY - 10; l++)
             {
                 if (Main.tile[k, l].active() && (Main.tileDungeon[Main.tile[k, l].type] || TileID.Sets.CrackedBricks[Main.tile[k, l].type]))
                 {
                     Main.tile[k, l].color(color);
                 }
                 if (Main.wallDungeon[Main.tile[k, l].wall])
                 {
                     Main.tile[k, l].wallColor(25);
                 }
                 if (Main.tile[k, l].active())
                 {
                     if (Main.tile[k, l].type == 60)
                     {
                         int num = 1;
                         for (int m = k - num; m <= k + num; m++)
{
                             for (int n = l - num; n <= l + num; n++)
{
                                 if (Main.tile[m, n].type == 147 || Main.tile[m, n].type == 161)
{
                                     Main.tile[m, n].type = 59;
                                 }
                             }
                         }
                     }
                     bool flag2 = false;
                     if (Main.tile[k, l].type == 226)
                     {
                         flag2 = true;
                     }
                     if (Main.tile[k, l].type == 137)
                     {
                         int num2 = Main.tile[k, l].frameY / 18;
                         if (num2 >= 1 && num2 <= 4)
{
                             flag2 = true;
                         }
                     }
                     if (flag2)
                     {
                         Main.tile[k, l].color(b);
                     }
                 }
                 if (Main.tile[k, l].wall == 87)
                 {
                     Main.tile[k, l].wallColor(b);
                 }
             }
         }
         for (int num3 = 0; num3 < 8000 && Main.chest[num3] != null; num3++)
         {
             if (genRand.Next(15) == 0 && Main.chest[num3].item[1].stack != 0)
             {
                 for (int num4 = 1; num4 < 40; num4++)
                 {
                     if (Main.chest[num3].item[num4].stack == 0)
                     {
                         Main.chest[num3].item[num4].SetDefaults(5001);
                         break;
                     }
                 }
             }
             if (genRand.Next(30) != 0 || Main.chest[num3].item[1].stack == 0)
             {
                 continue;
             }
             for (int num5 = 1; num5 < 40; num5++)
             {
                 if (Main.chest[num3].item[num5].stack == 0)
                 {
                     Main.chest[num3].item[num5].SetDefaults(678);
                     break;
                 }
             }
         }
     }
References Tile.active(), Main.chest, Tile.color(), TileID.Sets.CrackedBricks, Tile.frameY, Chest.item, Main.maxTilesX, Main.maxTilesY, Item.SetDefaults(), Item.stack, Main.tile, Main.tileDungeon, Tile.type, Tile.wall, Tile.wallColor(), and Main.wallDungeon.