Terraria: WorldGen.ShootFromCannon
ShootFromCannon()
static void WorldGen.ShootFromCannon (int x, int y, int angle, int ammo, int Damage, float KnockBack, int owner, bool fromWire) inline static
     {
         float num = 14f;
         float num2 = 0f;
         float num3 = 0f;
         int type = 162;
         if (ammo == 2)
         {
             type = 281;
         }
         if (ammo == 3)
         {
             type = 178;
         }
         if (ammo == 4)
         {
             type = 601;
             num = 3f;
         }
         if (ammo == 5)
         {
             type = 601;
             num = 3f;
         }
         int num4 = 0;
         int num5 = 0;
         if (ammo == 5)
         {
             num4 = 1;
         }
         if (ammo == 2)
         {
             num5 = owner + 1;
         }
         if (angle == 0)
         {
             num2 = 10f;
             num3 = 0f;
         }
         if (angle == 1)
         {
             num2 = 7.5f;
             num3 = -2.5f;
         }
         if (angle == 2)
         {
             num2 = 5f;
             num3 = -5f;
         }
         if (angle == 3)
         {
             num2 = 2.75f;
             num3 = -6f;
         }
         if (angle == 4)
         {
             num2 = 0f;
             num3 = -10f;
         }
         if (angle == 5)
         {
             num2 = -2.75f;
             num3 = -6f;
         }
         if (angle == 6)
         {
             num2 = -5f;
             num3 = -5f;
         }
         if (angle == 7)
         {
             num2 = -7.5f;
             num3 = -2.5f;
         }
         if (angle == 8)
         {
             num2 = -10f;
             num3 = 0f;
         }
         Vector2 vector = new Vector2((x + 2) * 16, (y + 2) * 16);
         float num6 = num2;
         float num7 = num3;
         float num8 = (float)Math.Sqrt(num6 * num6 + num7 * num7);
         if (ammo == 4 || ammo == 5)
         {
             if (angle == 4)
             {
                 vector.X += 5f;
             }
             vector.Y += 5f;
         }
         bool flag = true;
         if (ammo == 2 && !BunnyCannonCanFire())
         {
             flag = false;
         }
         if (!flag)
         {
             return;
         }
         num8 = num / num8;
         num6 *= num8;
         num7 *= num8;
         if (Main.myPlayer != owner && Main.netMode == 2 && (ammo == 4 || ammo == 5))
         {
             NetMessage.SendData(108, owner, -1, null, Damage, KnockBack, x, y, angle, ammo, owner);
             return;
         }
         if (Main.netMode == 2)
         {
             owner = Main.myPlayer;
         }
         int num9 = Projectile.NewProjectile(GetProjectileSource_PlayerOrWires(x, y, fromWire, Main.player[owner]), vector.X, vector.Y, num6, num7, type, Damage, KnockBack, owner, num4, num5);
         Main.projectile[num9].originatedFromActivableTile = true;
     }
References Damage, Main.myPlayer, Main.netMode, Projectile.NewProjectile(), Projectile.originatedFromActivableTile, Main.player, Main.projectile, and NetMessage.SendData().
Referenced by MessageBuffer.GetData(), Wiring.HitWireSingle(), Player.ShootFromCannon(), and Player.TileInteractionsUse().