Terraria: WorldGen.CheckOrb
CheckOrb()
static void WorldGen.CheckOrb (int i, int j, int type) inline static
     {
         if (Main.tile[i, j] == null)
         {
             return;
         }
         short frameX = Main.tile[i, j].frameX;
         bool flag = false;
         if (frameX >= 36)
         {
             flag = true;
         }
         if (destroyObject)
         {
             return;
         }
         int num = i;
         int num2 = j;
         num = ((Main.tile[i, j].frameX != 0 && Main.tile[i, j].frameX != 36) ? (i - 1) : i);
         num2 = ((Main.tile[i, j].frameY != 0) ? (j - 1) : j);
         for (int k = 0; k < 2; k++)
         {
             for (int l = 0; l < 2; l++)
             {
                 Tile tile = Main.tile[num + k, num2 + l];
                 if (tile != null && (!tile.nactive() || tile.type != type))
                 {
                     destroyObject = true;
                     break;
                 }
             }
             if (destroyObject)
             {
                 break;
             }
             if (type == 12 || type == 639)
             {
                 Tile tile = Main.tile[num + k, num2 + 2];
                 if (tile != null && !SolidTileAllowBottomSlope(num + k, num2 + 2))
                 {
                     destroyObject = true;
                     break;
                 }
             }
         }
         if (!destroyObject)
         {
             return;
         }
         for (int m = num; m < num + 2; m++)
         {
             for (int n = num2; n < num2 + 2; n++)
             {
                 if (Main.tile[m, n] != null && Main.tile[m, n].type == type)
                 {
                     KillTile(m, n);
                 }
             }
         }
         if (Main.netMode != 1 && !noTileActions)
         {
             switch (type)
             {
             case 12:
                 Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 29);
                 break;
             case 639:
                 Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 109);
                 break;
             case 31:
                 if (flag)
                 {
                     int num3 = Main.rand.Next(5);
                     if (!shadowOrbSmashed)
                     {
                         num3 = 0;
                     }
                     switch (num3)
                     {
                     case 0:
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 800, 1, noBroadcast: false, -1);
                         int stack = genRand.Next(100, 101);
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 97, stack);
                         break;
                     }
                     case 1:
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 1256, 1, noBroadcast: false, -1);
                         break;
                     case 2:
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 802, 1, noBroadcast: false, -1);
                         break;
                     case 3:
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 3062, 1, noBroadcast: false, -1);
                         break;
                     case 4:
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 1290, 1, noBroadcast: false, -1);
                         break;
                     }
                 }
                 else
                 {
                     int num4 = Main.rand.Next(5);
                     if (!shadowOrbSmashed)
                     {
                         num4 = 0;
                     }
                     switch (num4)
                     {
                     case 0:
                     {
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 96, 1, noBroadcast: false, -1);
                         int stack2 = genRand.Next(100, 101);
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 97, stack2);
                         break;
                     }
                     case 1:
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 64, 1, noBroadcast: false, -1);
                         break;
                     case 2:
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 162, 1, noBroadcast: false, -1);
                         break;
                     case 3:
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 115, 1, noBroadcast: false, -1);
                         break;
                     case 4:
                         Item.NewItem(GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 111, 1, noBroadcast: false, -1);
                         break;
                     }
                 }
                 shadowOrbSmashed = true;
                 shadowOrbCount++;
                 if (shadowOrbCount >= 3)
                 {
                     if (!(NPC.AnyNPCs(266) && flag) && (!NPC.AnyNPCs(13) || flag))
                     {
                         shadowOrbCount = 0;
                         float num5 = num * 16;
                         float num6 = num2 * 16;
                         float num7 = -1f;
                         int plr = 0;
                         for (int num8 = 0; num8 < 255; num8++)
{
                             float num9 = Math.Abs(Main.player[num8].position.X - num5) + Math.Abs(Main.player[num8].position.Y - num6);
                             if (num9 < num7 || num7 == -1f)
{
                                 plr = num8;
                                 num7 = num9;
                             }
                         }
                         if (flag)
{
                             NPC.SpawnOnPlayer(plr, 266);
                         }
                         else
{
                             NPC.SpawnOnPlayer(plr, 13);
                         }
                     }
                 }
                 else
                 {
                     LocalizedText localizedText = Lang.misc[10];
                     if (shadowOrbCount == 2)
                     {
                         localizedText = Lang.misc[11];
                     }
                     if (Main.netMode == 0)
                     {
                         Main.NewText(localizedText.ToString(), 50, byte.MaxValue, 130);
                     }
                     else if (Main.netMode == 2)
                     {
                         ChatHelper.BroadcastChatMessage(NetworkText.FromKey(localizedText.Key), new Color(50, 255, 130));
                     }
                 }
                 AchievementsHelper.NotifyProgressionEvent(7);
                 break;
             }
         }
         if (flag)
         {
             SoundEngine.PlaySound(4, i * 16, j * 16);
         }
         else
         {
             SoundEngine.PlaySound(13, i * 16, j * 16);
         }
         destroyObject = false;
     }
References NPC.AnyNPCs(), ChatHelper.BroadcastChatMessage(), Color, Tile.frameX, Tile.frameY, NetworkText.FromKey(), LocalizedText.Key, Lang.misc, Tile.nactive(), Main.netMode, Item.NewItem(), Main.NewText(), UnifiedRandom.Next(), AchievementsHelper.NotifyProgressionEvent(), Main.player, SoundEngine.PlaySound(), Entity.position, Main.rand, NPC.SpawnOnPlayer(), Main.tile, LocalizedText.ToString(), and Tile.type.