Terraria: WorldGen.SaveAndQuitCallBack
SaveAndQuitCallBack()
static void WorldGen.SaveAndQuitCallBack (object threadContext) inline static
     {
         int netMode = Main.netMode;
         try
         {
             SoundEngine.PlaySound(34, -1, -1, 0);
             SoundEngine.PlaySound(35, -1, -1, 0);
         }
         catch
         {
         }
         if (netMode == 0)
         {
             WorldFile.CacheSaveTime();
         }
         Main.invasionProgress = -1;
         Main.invasionProgressDisplayLeft = 0;
         Main.invasionProgressAlpha = 0f;
         Main.invasionProgressIcon = 0;
         Main.menuMode = 10;
         Main.gameMenu = true;
         SoundEngine.StopTrackedSounds();
         CaptureInterface.ResetFocus();
         Main.ActivePlayerFileData.StopPlayTimer();
         Player.SavePlayer(Main.ActivePlayerFileData);
         Player.ClearPlayerTempInfo();
         Rain.ClearRain();
         if (netMode == 0)
         {
             WorldFile.SaveWorld();
             SoundEngine.PlaySound(10);
         }
         else
         {
             Netplay.Disconnect = true;
             Main.netMode = 0;
         }
         Main.fastForwardTimeToDawn = false;
         Main.fastForwardTimeToDusk = false;
         Main.UpdateTimeRate();
         Main.menuMode = 0;
         if (threadContext != null)
         {
             ((Action)threadContext)();
         }
     }
References Main.ActivePlayerFileData, WorldFile.CacheSaveTime(), Player.ClearPlayerTempInfo(), Rain.ClearRain(), Netplay.Disconnect, Main.fastForwardTimeToDawn, Main.fastForwardTimeToDusk, Main.gameMenu, Main.invasionProgress, Main.invasionProgressAlpha, Main.invasionProgressDisplayLeft, Main.invasionProgressIcon, Main.menuMode, Main.netMode, SoundEngine.PlaySound(), CaptureInterface.ResetFocus(), Player.SavePlayer(), WorldFile.SaveWorld(), PlayerFileData.StopPlayTimer(), SoundEngine.StopTrackedSounds(), and Main.UpdateTimeRate().
Referenced by SaveAndQuit().