Terraria: WorldGen.CheckTallGate
CheckTallGate()
static void WorldGen.CheckTallGate (int x, int y, int type) inline static
     {
         if (destroyObject)
         {
             return;
         }
         bool flag = false;
         Tile tileSafely = Framing.GetTileSafely(x, y);
         Point point = new Point(tileSafely.frameX / 18, 0);
         TileObjectData tileData = TileObjectData.GetTileData(type, point.X);
         point.Y = tileSafely.frameY / tileData.CoordinateFullHeight;
         int width = tileData.Width;
         int height = tileData.Height;
         int i = 0;
         for (int num = tileSafely.frameY % tileData.CoordinateFullHeight; i < height && num - tileData.CoordinateHeights[i] >= 0; i++)
         {
             num -= tileData.CoordinateHeights[i];
         }
         _ = tileData.CoordinateFullHeight;
         y -= i;
         int num2 = point.Y * tileData.CoordinateFullHeight;
         for (int j = 0; j < height; j++)
         {
             tileSafely = Framing.GetTileSafely(x, y + j);
             if (tileSafely.frameX != point.X * tileData.CoordinateFullWidth || tileSafely.frameY != num2)
             {
                 flag = true;
                 break;
             }
             num2 += tileData.CoordinateHeights[j] + tileData.CoordinatePadding;
         }
         if (!flag && CheckTileAnchors(x, y, width, height, 2, AnchorType.SolidTile))
         {
             return;
         }
         destroyObject = true;
         for (int k = x; k < x + width; k++)
         {
             for (int l = y; l < y + height; l++)
             {
                 KillTile(k, l);
             }
         }
         int type2 = 3240;
         if (point.Y == 0)
         {
             type2 = 3240;
         }
         Item.NewItem(GetItemSource_FromTileBreak(x, y), x * 16, y * 16, width * 16, height * 16, type2);
         for (int m = x - 1; m < x + width + 1; m++)
         {
             for (int n = y - 1; n < y + height + 1; n++)
             {
                 TileFrame(m, n);
             }
         }
         destroyObject = false;
     }
References TileObjectData.CoordinateFullHeight, TileObjectData.CoordinateFullWidth, TileObjectData.CoordinateHeights, TileObjectData.CoordinatePadding, Tile.frameX, Tile.frameY, TileObjectData.GetTileData(), Framing.GetTileSafely(), TileObjectData.Height, Item.NewItem(), and TileObjectData.Width.