Terraria: WorldGen.ShiftTallGate
ShiftTallGate()
static bool WorldGen.ShiftTallGate (int x, int y, bool closing, bool forced = false) inline static
     {
         ushort type = (ushort)(closing ? 388 : 389);
         ushort num = (ushort)(closing ? 389 : 388);
         Tile tileSafely = Framing.GetTileSafely(x, y);
         if (tileSafely.type != num)
         {
             return false;
         }
         Point point = new Point(tileSafely.frameX / 18, 0);
         TileObjectData tileData = TileObjectData.GetTileData(388, point.X);
         point.Y = tileSafely.frameY / tileData.CoordinateFullHeight;
         _ = tileData.Width;
         int height = tileData.Height;
         int i = 0;
         for (int num2 = tileSafely.frameY % tileData.CoordinateFullHeight; i < height && num2 - tileData.CoordinateHeights[i] >= 0; i++)
         {
             num2 -= tileData.CoordinateHeights[i];
         }
         _ = tileData.CoordinateFullHeight;
         y -= i;
         if (Main.netMode != 1 && Wiring.running)
         {
             for (int j = 0; j < height; j++)
             {
                 Wiring.SkipWire(x, y + j);
             }
         }
         for (int k = 0; k < height; k++)
         {
             if (!forced && !Collision.EmptyTile(x, y + k, ignoreTiles: true))
             {
                 return false;
             }
         }
         SoundEngine.PlaySound(8, x * 16 + 16, y * 16 + 16);
         for (int l = 0; l < height; l++)
         {
             tileSafely = Framing.GetTileSafely(x, y + l);
             tileSafely.type = type;
         }
         for (int m = -1; m < 2; m++)
         {
             for (int n = -1; n < height + 1; n++)
             {
                 TileFrame(x + m, y + n);
             }
         }
         return true;
     }
References TileObjectData.CoordinateFullHeight, TileObjectData.CoordinateHeights, Collision.EmptyTile(), Tile.frameX, Tile.frameY, TileObjectData.GetTileData(), Framing.GetTileSafely(), TileObjectData.Height, Main.netMode, SoundEngine.PlaySound(), Wiring.running, Wiring.SkipWire(), Tile.type, and TileObjectData.Width.
Referenced by NPC.AI_003_Fighters(), NPC.AI_007_TownEntities(), NPC.AI_107_ImprovedWalkers(), MessageBuffer.GetData(), Wiring.HitWireSingle(), Player.TileInteractionsUse(), DoorOpeningHelper.TallGateOpeningInfoProvider.TryCloseDoor(), and DoorOpeningHelper.TallGateOpeningInfoProvider.TryOpenDoor().