Terraria: WorldGen.HasAnyWireNearby
HasAnyWireNearby()
static bool WorldGen.HasAnyWireNearby (int sourceX, int sourceY, int boxSpread) inline static
     {
         int num = Utils.Clamp(sourceX - boxSpread, 0, Main.maxTilesX - 1);
         int num2 = Utils.Clamp(sourceX + boxSpread, 0, Main.maxTilesX - 1);
         int num3 = Utils.Clamp(sourceY - boxSpread, 0, Main.maxTilesY - 1);
         int num4 = Utils.Clamp(sourceY + boxSpread, 0, Main.maxTilesY - 1);
         for (int i = num; i <= num2; i++)
         {
             for (int j = num3; j <= num4; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile != null && (tile.wire() || tile.wire2() || tile.wire3() || tile.wire4()))
                 {
                     return true;
                 }
             }
         }
         return false;
     }
References Main.maxTilesX, Main.maxTilesY, Main.tile, Tile.wire(), Tile.wire2(), Tile.wire3(), and Tile.wire4().