Terraria: WorldGen.TreeGrowFX
TreeGrowFX()
static void WorldGen.TreeGrowFX (int x, int y, int height, int treeGore, bool hitTree = false) inline static
     {
         Vector2 vector = new Vector2(x, y) * 16f + new Vector2(8f, 8f);
         if (treeGore == 1278)
         {
             TreeGrowFX_AshShake(x, y, height, hitTree);
             return;
         }
         for (int num = 0; num > -height; num--)
         {
             float num2 = 10f;
             Vector2 vector2 = new Vector2(5f, 7f);
             Gore.NewGore(vector + new Vector2(-16f, num * 16) - vector2, Utils.RandomVector2(Main.rand, 0f - num2, num2), treeGore, 0.7f + Main.rand.NextFloat() * 0.6f);
             Gore.NewGore(vector + new Vector2(0f, num * 16) - vector2, Utils.RandomVector2(Main.rand, 0f - num2, num2), treeGore, 0.7f + Main.rand.NextFloat() * 0.6f);
             Gore.NewGore(vector + new Vector2(16f, num * 16) - vector2, Utils.RandomVector2(Main.rand, 0f - num2, num2), treeGore, 0.7f + Main.rand.NextFloat() * 0.6f);
             if (num == -height + 1)
             {
                 int num3 = 20;
                 if (hitTree)
                 {
                     num3 = 5;
                 }
                 for (int i = 0; i < num3; i++)
                 {
                     Gore.NewGore(vector + new Vector2(0f, num * 16 - 40) + Utils.RandomVector2(Main.rand, -40f, 40f) - vector2, Utils.RandomVector2(Main.rand, -10f, 10f), treeGore, 0.7f + Main.rand.NextFloat() * 0.6f);
                 }
             }
         }
     }
References Gore.NewGore(), Main.rand, and Utils.RandomVector2().
Referenced by MessageBuffer.GetData().