Terraria: WorldGen.IsSafeFromRain
IsSafeFromRain()
static bool WorldGen.IsSafeFromRain (int startX, int startY) inline static
     {
         //IL_0019: Unknown result type (might be due to invalid IL or missing references)
         //IL_001e: Unknown result type (might be due to invalid IL or missing references)
         //IL_0023: Unknown result type (might be due to invalid IL or missing references)
         //IL_0028: Unknown result type (might be due to invalid IL or missing references)
         //IL_0036: Unknown result type (might be due to invalid IL or missing references)
         //IL_003b: Unknown result type (might be due to invalid IL or missing references)
         //IL_0049: Unknown result type (might be due to invalid IL or missing references)
         //IL_004e: Unknown result type (might be due to invalid IL or missing references)
         //IL_0063: Unknown result type (might be due to invalid IL or missing references)
         //IL_0064: Unknown result type (might be due to invalid IL or missing references)
         //IL_006e: Unknown result type (might be due to invalid IL or missing references)
         //IL_0074: Unknown result type (might be due to invalid IL or missing references)
         //IL_0079: Unknown result type (might be due to invalid IL or missing references)
         Vector2D val = -Rain.GetRainFallVelocity().SafeNormalize(new Vector2(0f, 1f)).ToVector2D();
         Vector2D val2 = new Vector2D((double)startX, (double)startY) * 16.0 + Vector2D.One * 8.0;
         double num = 85.0;
         DelegateMethods.CheckResultOut = false;
         Utils.PlotTileLine(val2, val2 + val * 16.0 * num, 4.0, DelegateMethods.CheckStopForSolids);
         return DelegateMethods.CheckResultOut;
     }
References DelegateMethods.CheckResultOut, DelegateMethods.CheckStopForSolids(), Rain.GetRainFallVelocity(), Vector2D.One, and Utils.PlotTileLine().