Terraria: System.Xml.XmlSubtreeReader.ReadElementContentAsBase64
ReadElementContentAsBase64()
override int System.Xml.XmlSubtreeReader.ReadElementContentAsBase64 (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 843 of file XmlSubtreeReader.cs.
    {
        switch (_state)
        {
        case State.Initial:
        case State.Error:
        case State.EndOfFile:
        case State.Closed:
            return 0;
        case State.Interactive:
        case State.PopNamespaceScope:
        case State.ClearNsAttributes:
            if (!InitReadElementContentAsBinary(State.ReadElementContentAsBase64))
            {
                return 0;
            }
            goto case State.ReadElementContentAsBase64;
        case State.ReadElementContentAsBase64:
        {
            int num = reader.ReadContentAsBase64(buffer, index, count);
            if (num > 0 || count == 0)
            {
                return num;
            }
            if (NodeType != XmlNodeType.EndElement)
            {
                throw new XmlException(System.SR.Xml_InvalidNodeType, reader.NodeType.ToString(), reader as IXmlLineInfo);
            }
            _state = State.Interactive;
            ProcessNamespaces();
            if (reader.Depth == _initialDepth)
            {
                _state = State.EndOfFile;
                SetEmptyNode();
            }
            else
            {
                Read();
            }
            return 0;
        }
        case State.ReadElementContentAsBinHex:
        case State.ReadContentAsBase64:
        case State.ReadContentAsBinHex:
            throw new InvalidOperationException(System.SR.Xml_MixingBinaryContentMethods);
        default:
            return 0;
        }
    }
References System.Xml.XmlSubtreeReader._initialDepth, System.Xml.XmlSubtreeReader._state, System.buffer, System.count, System.Xml.XmlReader.Depth, System.index, System.Xml.XmlSubtreeReader.InitReadElementContentAsBinary(), System.Xml.XmlReader.NodeType, System.Xml.XmlSubtreeReader.NodeType, System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlSubtreeReader.Read(), System.Xml.XmlReader.ReadContentAsBase64(), System.Xml.XmlWrappingReader.reader, System.Xml.XmlSubtreeReader.SetEmptyNode(), System.SR.Xml_InvalidNodeType, System.SR.Xml_MixingBinaryContentMethods, and System.Xml.XmlException.