Terraria: WorldGen.ScanTileColumnAndRemoveClumps
ScanTileColumnAndRemoveClumps()
static void WorldGen.ScanTileColumnAndRemoveClumps (int x) inline static private
     {
         int num = 0;
         int y = 0;
         for (int i = 10; i < Main.maxTilesY - 10; i++)
         {
             if (Main.tile[x, i].active() && Main.tileSolid[Main.tile[x, i].type] && TileID.Sets.CanBeClearedDuringGeneration[Main.tile[x, i].type])
             {
                 if (num == 0)
                 {
                     y = i;
                 }
                 num++;
                 continue;
             }
             if (num > 0 && num < tileCounterMax)
             {
                 SmallConsecutivesFound++;
                 if (tileCounter(x, y) < tileCounterMax)
                 {
                     SmallConsecutivesEliminated++;
                     tileCounterKill();
                 }
             }
             num = 0;
         }
     }
References Tile.active(), TileID.Sets.CanBeClearedDuringGeneration, Main.maxTilesY, SmallConsecutivesEliminated, SmallConsecutivesFound, Main.tile, tileCounter(), tileCounterKill(), tileCounterMax, Main.tileSolid, and Tile.type.
Referenced by GenerateWorld().