Terraria: WorldGen.CanKillTile
CanKillTile() [3/3]
static bool WorldGen.CanKillTile (int i, int j, SpecialKillTileContext context) inline static
     {
         if (context == SpecialKillTileContext.MowingTheGrass)
         {
             Tile tile = Main.tile[i, j];
             if (tile == null)
             {
                 return false;
             }
             if (tile.type == 2 || tile.type == 109)
             {
                 return true;
             }
         }
         return CanKillTile(i, j);
     }
References Main.tile, and Tile.type.
Referenced by MinecartDiggerHelper.CanGetPastTile(), Wiring.DeActive(), Mount.DrillSmartCursor_Blocks(), Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Player.MowGrassTile(), Player.PickTile(), SmartCursorHelper.Step_ForceCursorToAnyMinableThing(), and SmartCursorHelper.Step_Pickaxe_MineSolids().