Terraria: System.Xml.XmlSubtreeReader.Skip
Skip()
override void System.Xml.XmlSubtreeReader.Skip () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 549 of file XmlSubtreeReader.cs.
    {
        switch (_state)
        {
        case State.Initial:
            Read();
            break;
        case State.Interactive:
            _curNsAttr = -1;
            _useCurNode = false;
            reader.MoveToElement();
            if (reader.Depth == _initialDepth)
            {
                if (reader.NodeType == XmlNodeType.Element && !reader.IsEmptyElement && reader.Read())
                {
                    while (reader.NodeType != XmlNodeType.EndElement && reader.Depth > _initialDepth)
                    {
                        reader.Skip();
                    }
                }
                _state = State.EndOfFile;
                SetEmptyNode();
            }
            else
            {
                if (reader.NodeType == XmlNodeType.Element && !reader.IsEmptyElement)
                {
                    _nsManager.PopScope();
                }
                reader.Skip();
                ProcessNamespaces();
            }
            break;
        case State.EndOfFile:
        case State.Closed:
            break;
        case State.PopNamespaceScope:
            _nsManager.PopScope();
            goto case State.ClearNsAttributes;
        case State.ClearNsAttributes:
            _nsAttrCount = 0;
            _state = State.Interactive;
            goto case State.Interactive;
        case State.ReadElementContentAsBase64:
        case State.ReadElementContentAsBinHex:
            if (FinishReadElementContentAsBinary())
            {
                Skip();
            }
            break;
        case State.ReadContentAsBase64:
        case State.ReadContentAsBinHex:
            if (FinishReadContentAsBinary())
            {
                Skip();
            }
            break;
        case State.Error:
            break;
        }
    }
References System.Xml.XmlSubtreeReader._curNsAttr, System.Xml.XmlSubtreeReader._initialDepth, System.Xml.XmlSubtreeReader._nsAttrCount, System.Xml.XmlSubtreeReader._nsManager, System.Xml.XmlSubtreeReader._state, System.Xml.XmlSubtreeReader._useCurNode, System.Xml.XmlReader.Depth, System.Xml.XmlSubtreeReader.FinishReadContentAsBinary(), System.Xml.XmlSubtreeReader.FinishReadElementContentAsBinary(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.NodeType, System.Xml.XmlNamespaceManager.PopScope(), System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlReader.Read(), System.Xml.XmlSubtreeReader.Read(), System.Xml.XmlWrappingReader.reader, System.Xml.XmlSubtreeReader.SetEmptyNode(), System.Xml.XmlReader.Skip(), and System.Xml.XmlSubtreeReader.Skip().
Referenced by System.Xml.XmlSubtreeReader.Skip().