Terraria: WorldGen.PlaceSandTrap
PlaceSandTrap()
static bool WorldGen.PlaceSandTrap (int i, int j) inline static
     {
         int num = 6;
         int num2 = 4;
         int num3 = 25;
         int k;
         for (k = j; !Main.tile[i, k].active() && k < Main.UnderworldLayer; k++)
         {
         }
         if (!Main.tileSolid[Main.tile[i, k].type] || Main.tile[i, k].halfBrick() || Main.tile[i, k].topSlope())
         {
             return false;
         }
         if ((Main.tile[i, k].type != 53 && Main.tile[i, k].type != 397 && Main.tile[i, k].type != 396) || (Main.tile[i, k].wall != 216 && Main.tile[i, k].wall != 187))
         {
             return false;
         }
         k--;
         int num4 = -1;
         int num5 = genRand.Next(6, 12);
         int num6 = genRand.Next(6, 14);
         for (int l = i - num3; l <= i + num3; l++)
         {
             for (int m = k - num3; m < k + num3; m++)
             {
                 if (Main.tile[l, m].wire())
                 {
                     return false;
                 }
                 if (TileID.Sets.BasicChest[Main.tile[l, m].type])
                 {
                     return false;
                 }
                 if (TileID.Sets.Paintings[Main.tile[l, m].type])
                 {
                     return false;
                 }
                 if (Main.tile[l, m].type == 10)
                 {
                     return false;
                 }
                 if (Main.tile[l, m].type == 19)
                 {
                     return false;
                 }
                 if (Main.tile[l, m].type == 15)
                 {
                     return false;
                 }
                 if (Main.tile[l, m].type == 219)
                 {
                     return false;
                 }
             }
         }
         for (int n = i - 2; n <= i + 2; n++)
         {
             for (int num7 = k + 1; num7 <= k + 3; num7++)
             {
                 if (!Main.tile[n, num7].active() || !Main.tileSolid[Main.tile[n, num7].type])
                 {
                     return false;
                 }
             }
         }
         if (Main.tile[i, k + 1].type == 162)
         {
             return false;
         }
         for (int num8 = k; num8 > k - 30; num8--)
         {
             if (Main.tile[i, num8].active())
             {
                 if (Main.tile[i, num8].type == 396)
                 {
                     num4 = num8;
                     break;
                 }
                 return false;
             }
         }
         if (num4 <= -1)
         {
             return false;
         }
         if (k - num4 < num6 + num2)
         {
             return false;
         }
         int num9 = 0;
         int num10 = (k + num4) / 2;
         for (int num11 = i - num5; num11 <= i + num5; num11++)
         {
             if (Main.tile[num11, num10].active() && Main.tileSolid[Main.tile[num11, num10].type])
             {
                 return false;
             }
             for (int num12 = num4 - num6; num12 <= num4; num12++)
             {
                 if (Main.tile[num11, num12].active())
                 {
                     if (TileID.Sets.Ore[Main.tile[num11, num12].type] || Main.tile[num11, num12].type == 404)
                     {
                         return false;
                     }
                     if (Main.tileSolid[Main.tile[num11, num12].type])
                     {
                         num9++;
                     }
                 }
             }
         }
         double num13 = (double)((num5 * 2 + 1) * (num6 + 1)) * 0.75;
         if ((double)num9 < num13)
         {
             return false;
         }
         for (int num14 = i - num5 - 1; num14 <= i + num5 + 1; num14++)
         {
             for (int num15 = num4 - num6; num15 <= num4; num15++)
             {
                 bool flag = false;
                 if (Main.tile[num14, num15].active() && Main.tileSolid[Main.tile[num14, num15].type])
                 {
                     flag = true;
                 }
                 if (num15 == num4)
                 {
                     Main.tile[num14, num15].slope(0);
                     Main.tile[num14, num15].halfBrick(halfBrick: false);
                     if (!flag)
                     {
                         Main.tile[num14, num15].active(active: true);
                         Main.tile[num14, num15].type = 396;
                     }
                 }
                 else if (num15 == num4 - num6)
                 {
                     Main.tile[num14, num15].ClearTile();
                     Main.tile[num14, num15].active(active: true);
                     if (flag && Main.tile[num14, num15 - 1].active() && Main.tileSolid[Main.tile[num14, num15 - 1].type])
                     {
                         Main.tile[num14, num15].type = 397;
                     }
                     else
                     {
                         Main.tile[num14, num15].type = 396;
                     }
                 }
                 else if (num14 == i - num5 - 1 || num14 == i + num5 + 1)
                 {
                     if (!flag)
                     {
                         Main.tile[num14, num15].ClearTile();
                         Main.tile[num14, num15].active(active: true);
                         Main.tile[num14, num15].type = 396;
                     }
                     else
                     {
                         Main.tile[num14, num15].slope(0);
                         Main.tile[num14, num15].halfBrick(halfBrick: false);
                     }
                 }
                 else
                 {
                     Main.tile[num14, num15].ClearTile();
                     Main.tile[num14, num15].active(active: true);
                     Main.tile[num14, num15].type = 53;
                 }
             }
         }
         for (int num16 = (int)((double)num4 - (double)num6 * 0.666); (double)num16 <= (double)num4 - (double)num6 * 0.333; num16++)
         {
             if ((double)num16 < (double)num4 - (double)num6 * 0.4)
             {
                 if (Main.tile[i - num5 - 2, num16].bottomSlope())
                 {
                     Main.tile[i - num5 - 2, num16].slope(0);
                 }
             }
             else if ((double)num16 > (double)num4 - (double)num6 * 0.6)
             {
                 if (Main.tile[i - num5 - 2, num16].topSlope())
                 {
                     Main.tile[i - num5 - 2, num16].slope(0);
                 }
                 Main.tile[i - num5 - 2, num16].halfBrick(halfBrick: false);
             }
             else
             {
                 Main.tile[i - num5 - 2, num16].halfBrick(halfBrick: false);
                 Main.tile[i - num5 - 2, num16].slope(0);
             }
             if (!Main.tile[i - num5 - 2, num16].active() || !Main.tileSolid[Main.tile[i - num5 - 2, num16].type])
             {
                 Main.tile[i - num5 - 2, num16].active(active: true);
                 Main.tile[i - num5 - 2, num16].type = 396;
             }
             if (!Main.tile[i + num5 + 2, num16].active() || !Main.tileSolid[Main.tile[i + num5 + 2, num16].type])
             {
                 Main.tile[i + num5 + 2, num16].active(active: true);
                 Main.tile[i + num5 + 2, num16].type = 396;
             }
         }
         for (int num17 = num4 - num6; num17 <= num4; num17++)
         {
             Main.tile[i - num5 - 2, num17].slope(0);
             Main.tile[i - num5 - 2, num17].halfBrick(halfBrick: false);
             Main.tile[i - num5 - 1, num17].slope(0);
             Main.tile[i - num5 - 1, num17].halfBrick(halfBrick: false);
             Main.tile[i - num5 + 1, num17].slope(0);
             Main.tile[i - num5 + 1, num17].halfBrick(halfBrick: false);
             Main.tile[i - num5 + 2, num17].slope(0);
             Main.tile[i - num5 + 2, num17].halfBrick(halfBrick: false);
         }
         for (int num18 = i - num5 - 1; num18 < i + num5 + 1; num18++)
         {
             int num19 = k - num6 - 1;
             if (Main.tile[num18, num19].bottomSlope())
             {
                 Main.tile[num18, num19].slope(0);
             }
             Main.tile[num18, num19].halfBrick(halfBrick: false);
         }
         KillTile(i - 2, k);
         KillTile(i - 1, k);
         KillTile(i + 1, k);
         KillTile(i + 2, k);
         PlaceTile(i, k, 135, mute: true, forced: false, -1, 7);
         for (int num20 = i - num5; num20 <= i + num5; num20++)
         {
             int num21 = k;
             if ((double)num20 < (double)i - (double)num5 * 0.8 || (double)num20 > (double)i + (double)num5 * 0.8)
             {
                 num21 = k - 3;
             }
             else if ((double)num20 < (double)i - (double)num5 * 0.6 || (double)num20 > (double)i + (double)num5 * 0.6)
             {
                 num21 = k - 2;
             }
             else if ((double)num20 < (double)i - (double)num5 * 0.4 || (double)num20 > (double)i + (double)num5 * 0.4)
             {
                 num21 = k - 1;
             }
             for (int num22 = num4; num22 <= k; num22++)
             {
                 if (num20 == i && num22 <= k)
                 {
                     Main.tile[i, num22].wire(wire: true);
                 }
                 if (Main.tile[num20, num22].active() && Main.tileSolid[Main.tile[num20, num22].type])
                 {
                     if (num22 < num4 + num - 4)
                     {
                         Main.tile[num20, num22].actuator(actuator: true);
                         Main.tile[num20, num22].wire(wire: true);
                     }
                     else if (num22 < num21)
                     {
                         KillTile(num20, num22);
                     }
                 }
             }
         }
         return true;
     }
References Tile.active(), Tile.actuator(), TileID.Sets.BasicChest, Tile.bottomSlope(), Tile.ClearTile(), Tile.halfBrick(), TileID.Sets.Ore, TileID.Sets.Paintings, Tile.slope(), Main.tile, Main.tileSolid, Tile.topSlope(), Tile.type, Main.UnderworldLayer, Tile.wall, and Tile.wire().