Terraria: WorldGen.PlaceObject
PlaceObject()
static bool WorldGen.PlaceObject (int x, int y, int type, bool mute = false, int style = 0, int alternate = 0, int random = -1, int direction = -1) inline static
     {
         if (type >= TileID.Count)
         {
             return false;
         }
         if (!TileObject.CanPlace(x, y, type, style, direction, out var objectData))
         {
             return false;
         }
         objectData.random = random;
         if (TileObject.Place(objectData))
         {
             SquareTileFrame(x, y);
             if (!mute)
             {
                 SoundEngine.PlaySound(0, x * 16, y * 16);
             }
         }
         return true;
     }
References TileObject.CanPlace(), TileID.Count, TileObject.Place(), and SoundEngine.PlaySound().
Referenced by MessageBuffer.GetData().