Terraria: WorldGen.GrowCatTail
GrowCatTail()
static void WorldGen.GrowCatTail (int x, int j) inline static
     {
         if (Main.netMode == 1)
         {
             return;
         }
         int num = j;
         while (Main.tile[x, num].liquid > 0 && num > 50)
         {
             num--;
         }
         num++;
         int i;
         for (i = num; (!Main.tile[x, i].active() || !Main.tileSolid[Main.tile[x, i].type] || Main.tileSolidTop[Main.tile[x, i].type]) && i < Main.maxTilesY - 50; i++)
         {
         }
         num = i - 1;
         while (Main.tile[x, num].active() && Main.tile[x, num].type == 519)
         {
             num--;
         }
         num++;
         if (Main.tile[x, num].frameX == 90 && Main.tile[x, num - 1].active() && Main.tileCut[Main.tile[x, num - 1].type])
         {
             KillTile(x, num - 1);
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, x, num - 1);
             }
         }
         if (Main.tile[x, num - 1].active())
         {
             return;
         }
         if (Main.tile[x, num].frameX == 0)
         {
             Main.tile[x, num].frameX = 18;
             SquareTileFrame(x, num);
             if (Main.netMode == 2)
             {
                 NetMessage.SendTileSquare(-1, x, num);
             }
         }
         else if (Main.tile[x, num].frameX == 18)
         {
             Main.tile[x, num].frameX = (short)(18 * genRand.Next(2, 5));
             Main.tile[x, num - 1].active(active: true);
             Main.tile[x, num - 1].type = 519;
             Main.tile[x, num - 1].frameX = 90;
             Main.tile[x, num - 1].frameY = Main.tile[x, num].frameY;
             Main.tile[x, num - 1].halfBrick(halfBrick: false);
             Main.tile[x, num - 1].slope(0);
             Main.tile[x, num - 1].CopyPaintAndCoating(Main.tile[x, num]);
             SquareTileFrame(x, num);
             if (Main.netMode == 2)
             {
                 NetMessage.SendTileSquare(-1, x, num);
             }
         }
         else if (Main.tile[x, num].frameX == 90)
         {
             if (Main.tile[x, num - 1].liquid == 0)
             {
                 if (!Main.tile[x, num - 2].active() && (Main.tile[x, num].liquid > 0 || Main.tile[x, num + 1].liquid > 0 || Main.tile[x, num + 2].liquid > 0) && genRand.Next(3) == 0)
                 {
                     Main.tile[x, num].frameX = 108;
                     Main.tile[x, num - 1].active(active: true);
                     Main.tile[x, num - 1].type = 519;
                     Main.tile[x, num - 1].frameX = 90;
                     Main.tile[x, num - 1].frameY = Main.tile[x, num].frameY;
                     Main.tile[x, num - 1].halfBrick(halfBrick: false);
                     Main.tile[x, num - 1].slope(0);
                     Main.tile[x, num - 1].CopyPaintAndCoating(Main.tile[x, num]);
                     SquareTileFrame(x, num);
                 }
                 else
                 {
                     int num2 = genRand.Next(3);
                     Main.tile[x, num].frameX = (short)(126 + num2 * 18);
                     Main.tile[x, num - 1].active(active: true);
                     Main.tile[x, num - 1].type = 519;
                     Main.tile[x, num - 1].frameX = (short)(180 + num2 * 18);
                     Main.tile[x, num - 1].frameY = Main.tile[x, num].frameY;
                     Main.tile[x, num - 1].halfBrick(halfBrick: false);
                     Main.tile[x, num - 1].slope(0);
                     Main.tile[x, num - 1].CopyPaintAndCoating(Main.tile[x, num]);
                     SquareTileFrame(x, num);
                 }
             }
             else
             {
                 Main.tile[x, num].frameX = 108;
                 Main.tile[x, num - 1].active(active: true);
                 Main.tile[x, num - 1].type = 519;
                 Main.tile[x, num - 1].frameX = 90;
                 Main.tile[x, num - 1].frameY = Main.tile[x, num].frameY;
                 Main.tile[x, num - 1].halfBrick(halfBrick: false);
                 Main.tile[x, num - 1].slope(0);
                 Main.tile[x, num - 1].CopyPaintAndCoating(Main.tile[x, num]);
                 SquareTileFrame(x, num);
             }
         }
         SquareTileFrame(x, num - 1, resetFrame: false);
         if (Main.netMode == 2)
         {
             NetMessage.SendTileSquare(-1, x, num - 1, 1, 2);
         }
     }
References Tile.active(), Tile.CopyPaintAndCoating(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.liquid, Main.maxTilesY, Main.netMode, NetMessage.SendData(), NetMessage.SendTileSquare(), Tile.slope(), Main.tile, Main.tileCut, Main.tileSolid, Main.tileSolidTop, and Tile.type.