Terraria: System.Xml.XmlSubtreeReader.FinishReadElementContentAsBinary
FinishReadElementContentAsBinary()
bool System.Xml.XmlSubtreeReader.FinishReadElementContentAsBinary () inline private
Definition at line 1241 of file XmlSubtreeReader.cs.
    {
        byte[] buffer = new byte[256];
        if (_state == State.ReadElementContentAsBase64)
        {
            while (reader.ReadContentAsBase64(buffer, 0, 256) > 0)
            {
            }
        }
        else
        {
            while (reader.ReadContentAsBinHex(buffer, 0, 256) > 0)
            {
            }
        }
        if (NodeType != XmlNodeType.EndElement)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, reader.NodeType.ToString(), reader as IXmlLineInfo);
        }
        _state = State.Interactive;
        ProcessNamespaces();
        if (reader.Depth == _initialDepth)
        {
            _state = State.EndOfFile;
            SetEmptyNode();
            return false;
        }
        return Read();
    }
References System.Xml.XmlSubtreeReader._initialDepth, System.Xml.XmlSubtreeReader._state, System.buffer, System.Xml.XmlReader.Depth, System.Xml.XmlReader.NodeType, System.Xml.XmlSubtreeReader.NodeType, System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlSubtreeReader.Read(), System.Xml.XmlReader.ReadContentAsBase64(), System.Xml.XmlReader.ReadContentAsBinHex(), System.Xml.XmlWrappingReader.reader, System.Xml.XmlSubtreeReader.SetEmptyNode(), System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Xml.XmlSubtreeReader.Read(), and System.Xml.XmlSubtreeReader.Skip().