Terraria: WorldGen.FinishGetGoodWorld
FinishGetGoodWorld()
static void WorldGen.FinishGetGoodWorld () inline static private
     {
         int num = 0;
         for (int i = 20; (double)i < Main.worldSurface; i++)
         {
             for (int j = 20; j < Main.maxTilesX - 20; j++)
             {
                 if (Main.tile[j, i].active() && TileID.Sets.Clouds[Main.tile[j, i].type])
                 {
                     num = i;
                     break;
                 }
             }
         }
         byte b = (byte)genRand.Next(13, 25);
         for (int k = 0; k < Main.maxTilesX; k++)
         {
             bool flag = false;
             for (int l = 0; l < Main.maxTilesY; l++)
             {
                 if (!Main.tile[k, l].active() || !Main.tileDungeon[Main.tile[k, l].type])
                 {
                     continue;
                 }
                 if (Main.tile[k, l].type == 44)
                 {
                     b = (byte)genRand.Next(13, 15);
                     if (genRand.Next(2) == 0)
                     {
                         b = (byte)genRand.Next(23, 25);
                     }
                 }
                 if (Main.tile[k, l].type == 43)
                 {
                     b = (byte)genRand.Next(15, 19);
                 }
                 if (Main.tile[k, l].type == 41)
                 {
                     b = (byte)genRand.Next(19, 23);
                 }
             }
             if (flag)
             {
                 break;
             }
         }
         for (int m = 0; m < Main.maxTilesX; m++)
         {
             for (int n = 5; n < Main.maxTilesY - 5; n++)
             {
                 if (Main.tile[m, n].active() && (Main.tileDungeon[Main.tile[m, n].type] || TileID.Sets.CrackedBricks[Main.tile[m, n].type]))
                 {
                     Main.tile[m, n].color(b);
                 }
                 if (Main.wallDungeon[Main.tile[m, n].wall])
                 {
                     Main.tile[m, n].wallColor(b);
                 }
                 if (Main.tile[m, n].active())
                 {
                     bool flag2 = false;
                     if (Main.tile[m, n].type == 226)
                     {
                         flag2 = true;
                     }
                     if (Main.tile[m, n].type == 137)
                     {
                         int num2 = Main.tile[m, n].frameY / 18;
                         if (num2 >= 1 && num2 <= 4)
{
                             flag2 = true;
                         }
                     }
                     if (flag2)
                     {
                         Main.tile[m, n].color(17);
                     }
                 }
                 if (Main.tile[m, n].wall == 87)
                 {
                     Main.tile[m, n].wallColor(25);
                 }
                 if (!Main.tile[m, n].active())
                 {
                     continue;
                 }
                 if (!remixWorldGen && Main.tile[m, n].type == 57 && genRand.Next(15) == 0)
                 {
                     if (Main.tile[m, n - 1].type == 57)
                     {
                         Main.tile[m, n].active(active: false);
                     }
                     Main.tile[m, n].liquid = byte.MaxValue;
                     Main.tile[m, n].lava(lava: true);
                 }
                 if (n < num && Main.tile[m, n].type == 2)
                 {
                     if (crimson)
                     {
                         Main.tile[m, n].type = 199;
                     }
                     else
                     {
                         Main.tile[m, n].type = 23;
                     }
                     if (Main.tile[m, n - 1].type == 3)
                     {
                         Main.tile[m, n - 1].active(active: false);
                     }
                     if (Main.tile[m, n - 1].type == 73)
                     {
                         Main.tile[m, n - 1].active(active: false);
                     }
                     if (Main.tile[m, n - 1].type == 27)
                     {
                         KillTile(m, n - 1);
                     }
                     if (Main.tile[m, n - 1].type == 596)
                     {
                         KillTile(m, n - 1);
                     }
                     if (Main.tile[m, n - 1].type == 616)
                     {
                         KillTile(m, n - 1);
                     }
                     if (Main.tile[m, n - 1].type == 82)
                     {
                         KillTile(m, n - 1);
                     }
                     if (Main.tile[m, n - 1].type == 83)
                     {
                         KillTile(m, n - 1);
                     }
                     if (Main.tile[m, n - 1].type == 186)
                     {
                         KillTile(m, n - 1);
                     }
                     if (Main.tile[m, n - 1].type == 187)
                     {
                         KillTile(m, n - 1);
                     }
                     if (Main.tile[m, n - 1].type == 185)
                     {
                         KillTile(m, n - 1);
                     }
                     if (Main.tile[m, n - 1].type == 227)
                     {
                         KillTile(m, n - 1);
                     }
                 }
             }
         }
         for (int num3 = 0; num3 < 8000 && Main.chest[num3] != null; num3++)
         {
             if (genRand.Next(10) != 0 || Main.chest[num3].item[1].stack == 0)
             {
                 continue;
             }
             for (int num4 = 1; num4 < 40; num4++)
             {
                 if (Main.chest[num3].item[num4].stack == 0)
                 {
                     Main.chest[num3].item[num4].SetDefaults(678);
                     break;
                 }
             }
         }
     }
References Tile.active(), Main.chest, TileID.Sets.Clouds, Tile.color(), TileID.Sets.CrackedBricks, Tile.frameY, Chest.item, Tile.lava(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Item.SetDefaults(), Item.stack, Main.tile, Main.tileDungeon, Tile.type, Tile.wall, Tile.wallColor(), Main.wallDungeon, and Main.worldSurface.