Terraria: System.Xml.XmlSubtreeReader.ReadContentAsBoolean
ReadContentAsBoolean()
override bool System.Xml.XmlSubtreeReader.ReadContentAsBoolean () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 627 of file XmlSubtreeReader.cs.
    {
        try
        {
            InitReadContentAsType("ReadContentAsBoolean");
            bool result = reader.ReadContentAsBoolean();
            FinishReadContentAsType();
            return result;
        }
        catch
        {
            _state = State.Error;
            throw;
        }
    }
References System.Xml.XmlSubtreeReader._state, System.Xml.XmlSubtreeReader.FinishReadContentAsType(), System.Xml.XmlSubtreeReader.InitReadContentAsType(), System.Xml.XmlReader.ReadContentAsBoolean(), and System.Xml.XmlWrappingReader.reader.