Terraria: WorldGen.RenameWorldCallBack
RenameWorldCallBack()
static void WorldGen.RenameWorldCallBack (object threadContext) inline static
     {
         if (threadContext != null && threadContext is Tuple<string, Action<string>> { Item1: var item, Item2: var item2 })
         {
             noMapUpdate = true;
             Main.ToggleGameplayUpdates(state: false);
             WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
             noMapUpdate = false;
             if (loadFailed || !loadSuccess)
             {
                 Main.LoadWorlds();
                 Main.GoToWorldSelect();
                 return;
             }
             Main.sectionManager.SetAllSectionsLoaded();
             double time = Main.time;
             bool dayTime = Main.dayTime;
             WorldFile.SetOngoingToTemps();
             WorldFile.CacheSaveTime();
             Main.time = time;
             Main.dayTime = dayTime;
             Main.worldName = item;
             WorldFile.SaveWorld();
             Rain.ClearRain();
             Main.fastForwardTimeToDawn = false;
             Main.fastForwardTimeToDusk = false;
             Main.UpdateTimeRate();
             item2?.Invoke(item);
         }
     }
References Main.ActiveWorldFileData, WorldFile.CacheSaveTime(), Rain.ClearRain(), Main.dayTime, Main.fastForwardTimeToDawn, Main.fastForwardTimeToDusk, Main.GoToWorldSelect(), FileData.IsCloudSave, loadFailed, loadSuccess, WorldFile.LoadWorld(), Main.LoadWorlds(), noMapUpdate, WorldFile.SaveWorld(), Main.sectionManager, WorldSections.SetAllSectionsLoaded(), WorldFile.SetOngoingToTemps(), Main.time, Main.ToggleGameplayUpdates(), Main.UpdateTimeRate(), and Main.worldName.
Referenced by RenameWorld().