Terraria: WorldGen.Statue
Statue()
static bool WorldGen.Statue (int x, int y, byte paint) inline static
     {
         int num = genRand.Next(2, GenVars.statueList.Length);
         int x2 = GenVars.statueList[num].X;
         int y2 = GenVars.statueList[num].Y;
         while (!Main.tile[x, y].active())
         {
             y++;
             if (y >= Main.maxTilesY)
             {
                 break;
             }
         }
         if (y >= Main.maxTilesY)
         {
             return false;
         }
         y--;
         if (PlaceTile(x, y, x2, mute: true, forced: true, -1, y2))
         {
             for (int i = 0; i < 2; i++)
             {
                 for (int j = 0; j < 3; j++)
                 {
                     Main.tile[x + i, y + j - 2].color(paint);
                 }
             }
             return true;
         }
         return false;
     }
References Tile.active(), Tile.color(), genRand, Main.maxTilesY, UnifiedRandom.Next(), PlaceTile(), GenVars.statueList, Main.tile, Point16.X, and Point16.Y.
Referenced by MarblePileWithStatues().