Terraria: WorldGen.CheckTileBreakability2_ShouldTileSurvive
CheckTileBreakability2_ShouldTileSurvive()
static bool WorldGen.CheckTileBreakability2_ShouldTileSurvive (int x, int y) inline static
     {
         if (Main.netMode == 1)
         {
             return false;
         }
         if (Main.tile[x, y] == null)
         {
             Main.tile[x, y] = new Tile();
         }
         Tile tile = Main.tile[x, y];
         if (TileID.Sets.BasicChest[tile.type])
         {
             int num = tile.frameX / 18;
             int y2 = y - tile.frameY / 18;
             while (num > 1)
             {
                 num -= 2;
             }
             num = x - num;
             if (!Chest.DestroyChest(num, y2))
             {
                 return true;
             }
         }
         if (tile.type == 88)
         {
             int num2 = tile.frameX / 18;
             int y3 = y - tile.frameY / 18;
             num2 %= 3;
             num2 = x - num2;
             if (!Chest.DestroyChest(num2, y3))
             {
                 return true;
             }
         }
         if (tile.type == 470)
         {
             return !TEDisplayDoll.IsBreakable(x, y);
         }
         if (tile.type == 475)
         {
             return !TEHatRack.IsBreakable(x, y);
         }
         return false;
     }
References TileID.Sets.BasicChest, Chest.DestroyChest(), Tile.frameX, Tile.frameY, TEDisplayDoll.IsBreakable(), TEHatRack.IsBreakable(), Main.netMode, Main.tile, and Tile.type.
Referenced by MinecartDiggerHelper.CanGetPastTile(), and MessageBuffer.GetData().