Terraria: WorldGen.UnspawnTravelNPC
UnspawnTravelNPC()
static void WorldGen.UnspawnTravelNPC () inline static
     {
         int num = -1;
         for (int i = 0; i < 200; i++)
         {
             if (Main.npc[i].active && Main.npc[i].type == 368)
             {
                 num = i;
                 break;
             }
         }
         if (num < 0)
         {
             return;
         }
         int num2 = (int)(Main.npc[num].Center.X / 16f);
         int num3 = (int)(Main.npc[num].Center.Y / 16f);
         bool flag = true;
         Rectangle value = new Rectangle(num2 * 16 + 8 - NPC.sWidth / 2 - NPC.safeRangeX, num3 * 16 + 8 - NPC.sHeight / 2 - NPC.safeRangeY, NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
         for (int j = 0; j < 255; j++)
         {
             if (Main.player[j].active && new Rectangle((int)Main.player[j].position.X, (int)Main.player[j].position.Y, Main.player[j].width, Main.player[j].height).Intersects(value))
             {
                 flag = false;
                 break;
             }
         }
         if (flag)
         {
             string fullName = Main.npc[num].FullName;
             if (Main.netMode == 0)
             {
                 Main.NewText(Lang.misc[35].Format(fullName), 50, 125);
             }
             else if (Main.netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[35].Key, Main.npc[num].GetFullNetName()), new Color(50, 125, 255));
             }
             Main.npc[num].active = false;
             Main.npc[num].netSkip = -1;
             Main.npc[num].life = 0;
             NetMessage.SendData(23, -1, -1, null, num);
         }
     }
References Entity.active, ChatHelper.BroadcastChatMessage(), Entity.Center, Color, LocalizedText.Format(), NetworkText.FromKey(), NPC.FullName, NPC.GetFullNetName(), Entity.height, LocalizedText.Key, NPC.life, Lang.misc, Main.netMode, NPC.netSkip, Main.NewText(), Main.npc, Main.player, Entity.position, NPC.safeRangeX, NPC.safeRangeY, NetMessage.SendData(), NPC.sHeight, NPC.sWidth, NPC.type, and Entity.width.
Referenced by Main.UpdateTime().