Terraria: WorldGen.CheckJunglePlant
CheckJunglePlant()
static void WorldGen.CheckJunglePlant (int i, int j, int type) inline static
     {
         if (destroyObject)
         {
             return;
         }
         if (Main.tile[i, j].frameY >= 36 || Main.tile[i, j].type == 236 || Main.tile[i, j].type == 238)
         {
             bool flag = false;
             int num = Main.tile[i, j].frameX / 18;
             int num2 = 0;
             while (num > 1)
             {
                 num -= 2;
                 num2++;
             }
             num = i - num;
             int num3 = 36;
             if (type == 236 || type == 238)
             {
                 num3 = 0;
             }
             int num4;
             for (num4 = Main.tile[i, j].frameY / 18; num4 > 1; num4 -= 2)
             {
             }
             num4 = j - num4;
             int num5 = num2 * 36;
             for (int k = num; k < num + 2; k++)
             {
                 for (int l = num4; l < num4 + 2; l++)
                 {
                     if (Main.tile[k, l] == null)
                     {
                         Main.tile[k, l] = new Tile();
                     }
                     if (!Main.tile[k, l].active() || Main.tile[k, l].type != type || Main.tile[k, l].frameX != (k - num) * 18 + num5 || Main.tile[k, l].frameY != (l - num4) * 18 + num3)
                     {
                         flag = true;
                     }
                 }
                 if (Main.tile[k, num4 + 2] == null)
                 {
                     Main.tile[k, num4 + 2] = new Tile();
                 }
                 if (!SolidTile(k, num4 + 2) || Main.tile[k, num4 + 2].type != 60)
                 {
                     flag = true;
                 }
             }
             if (!flag)
             {
                 return;
             }
             if (type == 238)
             {
                 float num6 = i * 16;
                 float num7 = j * 16;
                 float num8 = -1f;
                 int plr = 0;
                 for (int m = 0; m < 255; m++)
                 {
                     float num9 = Math.Abs(Main.player[m].position.X - num6) + Math.Abs(Main.player[m].position.Y - num7);
                     if (num9 < num8 || num8 == -1f)
                     {
                         plr = m;
                         num8 = num9;
                     }
                 }
                 if (num8 / 16f < 50f)
                 {
                     NPC.SpawnOnPlayer(plr, 262);
                 }
             }
             if (type == 236)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1291);
             }
             _ = Main.tile[i, j].frameX;
             destroyObject = true;
             for (int n = num; n < num + 2; n++)
             {
                 for (int num10 = num4; num10 < num4 + 2; num10++)
                 {
                     if (Main.tile[n, num10] == null)
                     {
                         Main.tile[n, num10] = new Tile();
                     }
                     if (Main.tile[n, num10].type == type && Main.tile[n, num10].active())
                     {
                         KillTile(n, num10);
                     }
                 }
             }
             destroyObject = false;
             return;
         }
         bool flag2 = false;
         int num11 = j;
         num11 += Main.tile[i, j].frameY / 18 * -1;
         int num12 = Main.tile[i, j].frameX / 18;
         int num13 = 0;
         while (num12 > 2)
         {
             num12 -= 3;
             num13++;
         }
         num12 = i - num12;
         int num14 = num13 * 54;
         for (int num15 = num12; num15 < num12 + 3; num15++)
         {
             for (int num16 = num11; num16 < num11 + 2; num16++)
             {
                 if (Main.tile[num15, num16] == null)
                 {
                     Main.tile[num15, num16] = new Tile();
                 }
                 if (!Main.tile[num15, num16].active() || Main.tile[num15, num16].type != type || Main.tile[num15, num16].frameX != (num15 - num12) * 18 + num14 || Main.tile[num15, num16].frameY != (num16 - num11) * 18)
                 {
                     flag2 = true;
                 }
             }
             if (Main.tile[num15, num11 + 2] == null)
             {
                 Main.tile[num15, num11 + 2] = new Tile();
             }
             if (!SolidTile(num15, num11 + 2) || Main.tile[num15, num11 + 2].type != 60)
             {
                 flag2 = true;
             }
         }
         if (!flag2)
         {
             return;
         }
         _ = Main.tile[i, j].frameX;
         destroyObject = true;
         for (int num17 = num12; num17 < num12 + 3; num17++)
         {
             for (int num18 = num11; num18 < num11 + 3; num18++)
             {
                 if (Main.tile[num17, num18] == null)
                 {
                     Main.tile[num17, num18] = new Tile();
                 }
                 if (Main.tile[num17, num18].type == type && Main.tile[num17, num18].active())
                 {
                     KillTile(num17, num18);
                 }
             }
         }
         destroyObject = false;
     }
References Tile.active(), Tile.frameX, Tile.frameY, Item.NewItem(), Main.player, Entity.position, SolidTile, NPC.SpawnOnPlayer(), Main.tile, and Tile.type.