Terraria: WorldGen.PlaceDye
PlaceDye()
static void WorldGen.PlaceDye (int x, int y, int style) inline static
     {
         bool flag = false;
         if (Main.tile[x, y + 1] == null || Main.tile[x, y - 1] == null)
         {
             return;
         }
         if (style == 7)
         {
             if (Main.tile[x, y + 1].active() && Main.tile[x, y + 1].type != 3 && Main.tile[x, y + 1].type != 51 && Main.tile[x, y + 1].type != 61 && Main.tile[x, y + 1].type != 73 && Main.tile[x, y + 1].type != 74 && Main.tile[x, y + 1].type != 184)
             {
                 return;
             }
             if (SolidTile(x, y - 1) && !Main.tile[x, y + 1].active())
             {
                 flag = true;
             }
         }
         else
         {
             if (Main.tile[x, y - 1].active() && Main.tile[x, y - 1].type != 3 && Main.tile[x, y - 1].type != 51 && Main.tile[x, y - 1].type != 61 && Main.tile[x, y - 1].type != 73 && Main.tile[x, y - 1].type != 74 && Main.tile[x, y - 1].type != 184)
             {
                 return;
             }
             if (style == 6)
             {
                 if (Main.tile[x, y + 1].nactive() && Main.tile[x, y + 1].type == 80 && !Main.tile[x - 1, y + 1].active() && !Main.tile[x + 1, y + 1].active())
                 {
                     flag = true;
                 }
             }
             else if (SolidTile(x, y + 1) && !Main.tile[x, y - 1].active())
             {
                 switch (style)
                 {
                 case 5:
                     if (Main.tile[x, y].liquid == byte.MaxValue && !Main.tile[x, y].lava() && !Main.tile[x, y].honey() && !Main.tile[x, y].shimmer())
                     {
                         flag = true;
                     }
                     break;
                 case 8:
                 case 9:
                 case 10:
                 case 11:
                     flag = true;
                     break;
                 default:
                     if (Main.tile[x, y].liquid != 0)
                     {
                         break;
                     }
                     if (style == 3 || style == 4)
                     {
                         if (Main.tile[x, y].wall == 0)
{
                             flag = true;
                         }
                     }
                     else
                     {
                         flag = true;
                     }
                     break;
                 }
             }
         }
         if (flag)
         {
             Main.tile[x, y].type = 227;
             Main.tile[x, y].active(active: true);
             Main.tile[x, y].halfBrick(halfBrick: false);
             Main.tile[x, y].slope(0);
             Main.tile[x, y].frameY = 0;
             Main.tile[x, y].frameX = (short)(34 * style);
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.honey(), Tile.lava(), Tile.liquid, Tile.nactive(), Tile.shimmer(), Tile.slope(), SolidTile, Main.tile, Tile.type, and Tile.wall.