Terraria: WorldGen.FixHeart
FixHeart()
static void WorldGen.FixHeart (int i, int j) inline static
     {
         if (i < Main.offLimitBorderTiles || i >= Main.maxTilesX - Main.offLimitBorderTiles || j < Main.offLimitBorderTiles || j >= Main.maxTilesY - Main.offLimitBorderTiles)
         {
             DestroyHeart(i, j);
             return;
         }
         Tile tile = Main.tile[i, j + 2];
         Tile tile2 = Main.tile[i + 1, j + 2];
         if (tile.active() && !Main.tileSolid[tile.type] && Main.tileCut[tile.type])
         {
             KillTile(i, j + 2);
         }
         if (tile2.active() && !Main.tileSolid[tile2.type] && Main.tileCut[tile2.type])
         {
             KillTile(i + 1, j + 2);
         }
         if (!tile.active())
         {
             if (!tile2.active())
             {
                 DestroyHeart(i, j);
                 return;
             }
             if (Main.tileSolid[tile2.type])
             {
                 tile.type = tile2.type;
                 tile.active(active: true);
             }
         }
         if (!tile2.active() && Main.tileSolid[tile.type])
         {
             tile2.type = tile.type;
             tile2.active(active: true);
         }
         if (!tile.nactive() || !Main.tileSolid[tile.type] || !tile2.nactive() || !Main.tileSolid[tile2.type])
         {
             DestroyHeart(i, j);
             return;
         }
         if (tile.blockType() != 0)
         {
             tile.slope(0);
             tile.halfBrick(halfBrick: false);
         }
         if (tile2.blockType() != 0)
         {
             tile2.slope(0);
             tile2.halfBrick(halfBrick: false);
         }
     }
References Tile.active(), Tile.blockType(), Tile.halfBrick(), Main.maxTilesX, Main.maxTilesY, Tile.nactive(), Main.offLimitBorderTiles, Tile.slope(), Main.tile, Main.tileCut, Main.tileSolid, and Tile.type.