Terraria: WorldGen.CheckCactus
CheckCactus()
static bool WorldGen.CheckCactus (int i, int j) inline static
     {
         int num = j;
         int num2 = i;
         while (Main.tile[num2, num] != null && Main.tile[num2, num].active() && Main.tile[num2, num].type == 80)
         {
             num++;
             if (Main.tile[num2, num] == null)
             {
                 return false;
             }
             if (!Main.tile[num2, num].active() || Main.tile[num2, num].type != 80)
             {
                 if (Main.tile[num2 - 1, num] != null && Main.tile[num2 - 1, num].active() && Main.tile[num2 - 1, num].type == 80 && Main.tile[num2 - 1, num - 1] != null && Main.tile[num2 - 1, num - 1].active() && Main.tile[num2 - 1, num - 1].type == 80 && num2 >= i)
                 {
                     num2--;
                 }
                 if (Main.tile[num2 + 1, num] != null && Main.tile[num2 + 1, num].active() && Main.tile[num2 + 1, num].type == 80 && Main.tile[num2 + 1, num - 1] != null && Main.tile[num2 + 1, num - 1].active() && Main.tile[num2 + 1, num - 1].type == 80 && num2 <= i)
                 {
                     num2++;
                 }
             }
         }
         if (!Main.tile[num2, num].nactive() || Main.tile[num2, num].halfBrick() || Main.tile[num2, num].slope() != 0 || (Main.tile[num2, num].type != 53 && Main.tile[num2, num].type != 112 && Main.tile[num2, num].type != 116 && Main.tile[num2, num].type != 234))
         {
             KillTile(i, j);
             return true;
         }
         if (i != num2)
         {
             if ((!Main.tile[i, j + 1].active() || Main.tile[i, j + 1].type != 80) && (!Main.tile[i - 1, j].active() || Main.tile[i - 1, j].type != 80) && (!Main.tile[i + 1, j].active() || Main.tile[i + 1, j].type != 80))
             {
                 KillTile(i, j);
                 return true;
             }
         }
         else if (i == num2 && (!Main.tile[i, j + 1].active() || (Main.tile[i, j + 1].type != 80 && Main.tile[i, j + 1].type != 53 && Main.tile[i, j + 1].type != 112 && Main.tile[i, j + 1].type != 116 && Main.tile[i, j + 1].type != 234)))
         {
             KillTile(i, j);
             return true;
         }
         return false;
     }
References Tile.active(), Tile.halfBrick(), Tile.nactive(), Tile.slope(), Main.tile, and Tile.type.