Terraria: WorldGen.PlatformProperSides
PlatformProperSides()
static int WorldGen.PlatformProperSides (int x, int y, bool acceptNonOpposing = false) inline static
     {
         Tile tile = Main.tile[x, y];
         if (!tile.active() || !TileID.Sets.Platforms[tile.type])
         {
             return 0;
         }
         int num = tile.slope();
         int num2 = -1;
         if (num == 1)
         {
             num2 = 2;
         }
         if (num == 2)
         {
             num2 = 1;
         }
         int num3 = 0;
         int num4 = 1;
         int num5 = 0;
         if (num == 1)
         {
             num5 = 1;
         }
         if (num == 2)
         {
             num5 = -1;
         }
         if (acceptNonOpposing)
         {
             if (Main.tile[x + num4, y + num5].active() && TileID.Sets.Platforms[Main.tile[x + num4, y + num5].type] && Main.tile[x + num4, y + num5].slope() != num2)
             {
                 num3++;
             }
         }
         else if (Main.tile[x + num4, y + num5].active() && TileID.Sets.Platforms[Main.tile[x + num4, y + num5].type] && Main.tile[x + num4, y + num5].slope() == num)
         {
             num3++;
         }
         num4 *= -1;
         num5 *= -1;
         if (acceptNonOpposing)
         {
             if (Main.tile[x + num4, y + num5].active() && TileID.Sets.Platforms[Main.tile[x + num4, y + num5].type] && Main.tile[x + num4, y + num5].slope() != num2)
             {
                 num3++;
             }
         }
         else if (Main.tile[x + num4, y + num5].active() && TileID.Sets.Platforms[Main.tile[x + num4, y + num5].type] && Main.tile[x + num4, y + num5].slope() == num)
         {
             num3++;
         }
         return num3;
     }
References Tile.active(), TileID.Sets.Platforms, Tile.slope(), Main.tile, and Tile.type.
Referenced by Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform().