Terraria: WorldGen.CheckWeaponsRack
CheckWeaponsRack()
static void WorldGen.CheckWeaponsRack (int i, int j) inline static
     {
         if (destroyObject)
         {
             return;
         }
         int num = i;
         int num2 = j - Main.tile[i, j].frameY / 18;
         int num3 = Main.tile[i, j].frameX;
         int num4 = 0;
         while (num3 >= 5000)
         {
             num3 -= 5000;
             num4++;
         }
         if (num4 != 0)
         {
             num3 = (num4 - 1) * 18;
         }
         num3 %= 54;
         num -= num3 / 18;
         bool flag = false;
         for (int k = 0; k < 3; k++)
         {
             for (int l = 0; l < 3; l++)
             {
                 int num5 = num + k;
                 int num6 = num2 + l;
                 int num7 = Main.tile[num5, num6].frameX;
                 int num8 = 0;
                 while (num7 >= 5000)
                 {
                     num7 -= 5000;
                     num8++;
                 }
                 if (num8 != 0)
                 {
                     num7 = (num8 - 1) * 18;
                 }
                 num7 %= 54;
                 if (!Main.tile[num5, num6].active() || Main.tile[num5, num6].type != 334 || Main.tile[num5, num6].wall <= 0 || Main.tile[num5, num6].frameY != l * 18 || num7 != k * 18)
                 {
                     flag = true;
                 }
             }
         }
         if (!flag)
         {
             return;
         }
         int num9 = TEWeaponsRack.Find(num, num2);
         if (num9 != -1 && ((TEWeaponsRack)TileEntity.ByID[num9]).item.stack > 0)
         {
             ((TEWeaponsRack)TileEntity.ByID[num9]).DropItem();
             if (Main.netMode != 2)
             {
                 Main.LocalPlayer.InterruptItemUsageIfOverTile(471);
             }
         }
         destroyObject = true;
         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 48, 48, 2699);
         TEWeaponsRack.Kill(num, num2);
         for (int m = 0; m < 3; m++)
         {
             for (int n = 0; n < 3; n++)
             {
                 int num10 = num + m;
                 int num11 = num2 + n;
                 if (Main.tile[num10, num11].active() && Main.tile[num10, num11].type == 334)
                 {
                     KillTile(num10, num11);
                 }
             }
         }
         destroyObject = false;
     }
References Tile.active(), TileEntity.ByID, TEWeaponsRack.Find(), Tile.frameX, Tile.frameY, Player.InterruptItemUsageIfOverTile(), TEWeaponsRack.Kill(), Main.LocalPlayer, Main.netMode, Item.NewItem(), Main.tile, Tile.type, and Tile.wall.