Terraria: WorldGen.CheckUnderwaterPlant
CheckUnderwaterPlant()
static void WorldGen.CheckUnderwaterPlant (ushort type, int x, int y) inline static
     {
         if (!CanUnderwaterPlantGrowHere(type, x, y, ignoreSelf: true))
         {
             KillTile(x, y);
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, x, y);
             }
             SquareTileFrame(x, y);
             return;
         }
         Tile tileSafely = Framing.GetTileSafely(x, y - 1);
         Tile tileSafely2 = Framing.GetTileSafely(x, y);
         Tile tileSafely3 = Framing.GetTileSafely(x, y + 1);
         bool num = tileSafely.active() && tileSafely.type == type;
         bool flag = tileSafely3.active() && tileSafely3.type == type;
         int num2 = tileSafely2.frameX / 18;
         tileSafely2.frameY = 0;
         if (num)
         {
             if (1 > num2 || num2 > 7)
             {
                 tileSafely2.frameX = (short)(genRand.Next(1, 8) * 18);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
             }
         }
         else if (flag)
         {
             if (7 > num2 || num2 > 12)
             {
                 tileSafely2.frameX = (short)(genRand.Next(7, 13) * 18);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
             }
         }
         else if (num2 != 0)
         {
             tileSafely2.frameX = 0;
             if (Main.netMode == 2)
             {
                 NetMessage.SendTileSquare(-1, x, y);
             }
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Framing.GetTileSafely(), Main.netMode, NetMessage.SendData(), NetMessage.SendTileSquare(), and Tile.type.