Terraria: WorldGen.RandomizeBackgrounds
RandomizeBackgrounds()
static void WorldGen.RandomizeBackgrounds (UnifiedRandom random) inline static
     {
         treeBG1 = RollRandomForestBGStyle(random);
         for (treeBG2 = RollRandomForestBGStyle(random); treeBG2 == treeBG1; treeBG2 = RollRandomForestBGStyle(random))
         {
         }
         treeBG3 = RollRandomForestBGStyle(random);
         while (treeBG3 == treeBG1 || treeBG3 == treeBG2)
         {
             treeBG3 = RollRandomForestBGStyle(random);
         }
         treeBG4 = RollRandomForestBGStyle(random);
         while (treeBG4 == treeBG1 || treeBG4 == treeBG2 || treeBG4 == treeBG3)
         {
             treeBG4 = RollRandomForestBGStyle(random);
         }
         setBG(0, treeBG1);
         setBG(10, treeBG2);
         setBG(11, treeBG3);
         setBG(12, treeBG4);
         setBG(1, random.Next(5));
         setBG(2, random.Next(6));
         snowBG = random.Next(8);
         if (snowBG == 2 && random.Next(2) == 0)
         {
             if (random.Next(2) == 0)
             {
                 snowBG = 21;
             }
             else
             {
                 snowBG = 22;
             }
         }
         if (snowBG == 3 && random.Next(2) == 0)
         {
             if (random.Next(2) == 0)
             {
                 snowBG = 31;
             }
             else
             {
                 snowBG = 32;
             }
         }
         if (snowBG == 4 && random.Next(2) == 0)
         {
             if (random.Next(2) == 0)
             {
                 snowBG = 41;
             }
             else
             {
                 snowBG = 42;
             }
         }
         setBG(3, snowBG);
         setBG(4, random.Next(5));
         setBG(5, random.Next(6));
         setBG(6, random.Next(5));
         setBG(7, random.Next(6));
         setBG(8, random.Next(4));
         setBG(9, random.Next(3));
     }
References UnifiedRandom.Next(), RollRandomForestBGStyle(), setBG(), snowBG, treeBG1, treeBG2, treeBG3, and treeBG4.
Referenced by GenerateWorld(), Main.Initialize_AlmostEverything(), and Main.UpdateMenu().