Terraria: WorldGen.Check2xX
Check2xX()
static void WorldGen.Check2xX (int i, int j, ushort type) inline static
     {
         if (destroyObject)
         {
             return;
         }
         int num = i;
         int num2;
         for (num2 = Main.tile[i, j].frameX; num2 >= 36; num2 -= 36)
         {
         }
         if (num2 == 18)
         {
             num--;
         }
         if (Main.tile[num, j] == null)
         {
             Main.tile[num, j] = new Tile();
         }
         int num3 = Main.tile[num, j].frameY / 18;
         int num4 = 3;
         if (type == 104)
         {
             num4 = 5;
         }
         if (type == 207)
         {
             num4 = 4;
         }
         int num5 = 0;
         while (num3 >= num4)
         {
             num3 -= num4;
             num5 += num4 * 18;
         }
         int num6 = j - num3;
         if (type == 410 && num5 != 0)
         {
             num5 += 2;
         }
         if (Main.tile[num, num6] == null)
         {
             Main.tile[num, num6] = new Tile();
         }
         int frameX = Main.tile[num, j].frameX;
         int frameY = Main.tile[num, j].frameY;
         bool flag = false;
         for (int k = 0; k < num4; k++)
         {
             if (Main.tile[num, num6 + k] == null)
             {
                 Main.tile[num, num6 + k] = new Tile();
             }
             if (!Main.tile[num, num6 + k].active())
             {
                 flag = true;
             }
             else if (Main.tile[num, num6 + k].type != type)
             {
                 flag = true;
             }
             else if (Main.tile[num, num6 + k].frameY != k * 18 + num5)
             {
                 flag = true;
             }
             else if (Main.tile[num, num6 + k].frameX != frameX)
             {
                 flag = true;
             }
             if (Main.tile[num + 1, num6 + k] == null)
             {
                 Main.tile[num + 1, num6 + k] = new Tile();
             }
             if (!Main.tile[num + 1, num6 + k].active())
             {
                 flag = true;
             }
             else if (Main.tile[num + 1, num6 + k].type != type)
             {
                 flag = true;
             }
             else if (Main.tile[num + 1, num6 + k].frameY != k * 18 + num5)
             {
                 flag = true;
             }
             else if (Main.tile[num + 1, num6 + k].frameX != frameX + 18)
             {
                 flag = true;
             }
         }
         if (type == 465 || type == 531 || type == 591 || type == 592)
         {
             bool flag2 = false;
             for (int l = 0; l < 2; l++)
             {
                 bool flag3 = false;
                 Tile tileSafely = Framing.GetTileSafely(num + l, num6 - 1);
                 if (type != 531 && tileSafely.type == 380)
                 {
                     flag3 = true;
                 }
                 else if (type != 531 && TileID.Sets.Platforms[tileSafely.type])
                 {
                     if (l == 0)
                     {
                         flag2 = IsBelowANonHammeredPlatform(num + l, num6);
                         flag3 = true;
                     }
                     else if (flag2 == IsBelowANonHammeredPlatform(num + l, num6))
                     {
                         flag3 = true;
                     }
                 }
                 else
                 {
                     flag3 = SolidTileAllowTopSlope(num + l, num6 - 1);
                 }
                 if (!flag3)
                 {
                     flag = true;
                     break;
                 }
             }
         }
         else
         {
             if (!SolidTileAllowBottomSlope(num, num6 + num4))
             {
                 flag = true;
             }
             if (!SolidTileAllowBottomSlope(num + 1, num6 + num4))
             {
                 flag = true;
             }
         }
         if (!flag)
         {
             return;
         }
         destroyObject = true;
         for (int m = 0; m < num4; m++)
         {
             if (Main.tile[num, num6 + m].type == type)
             {
                 KillTile(num, num6 + m);
             }
             if (Main.tile[num + 1, num6 + m].type == type)
             {
                 KillTile(num + 1, num6 + m);
             }
         }
         if (type == 104)
         {
             int num7 = frameX / 36;
             int num8 = 0;
             if (num7 >= 1 && num7 <= 5)
             {
                 num8 = 2237 + num7 - 1;
             }
             else
             {
                 switch (num7)
                 {
                 case 6:
                     num8 = 2560;
                     break;
                 case 7:
                     num8 = 2575;
                     break;
                 case 8:
                 case 9:
                 case 10:
                 case 11:
                 case 12:
                 case 13:
                 case 14:
                 case 15:
                 case 16:
                 case 17:
                 case 18:
                 case 19:
                 case 20:
                 case 21:
                 case 22:
                 case 23:
                     num8 = 2591 + num7 - 8;
                     break;
                 default:
                     num8 = num7 switch
                     {
                         24 => 2809,
                         25 => 3126,
                         26 => 3128,
                         27 => 3127,
                         28 => 3898,
                         29 => 3899,
                         30 => 3900,
                         31 => 3901,
                         32 => 3902,
                         33 => 3940,
                         34 => 3966,
                         35 => 4154,
                         36 => 4175,
                         37 => 4196,
                         38 => 4217,
                         39 => 4306,
                         40 => 4575,
                         41 => 5157,
                         42 => 5178,
                         43 => 5199,
                         _ => 359,
                     };
                     break;
                 }
             }
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num8);
         }
         if (type == 105)
         {
             int num9 = frameX / 36;
             int num10 = frameY / 54;
             num10 %= 3;
             num9 += num10 * 55;
             switch (num9)
             {
             case 0:
                 num9 = 360;
                 break;
             case 1:
                 num9 = 52;
                 break;
             case 43:
                 num9 = 1152;
                 break;
             case 44:
                 num9 = 1153;
                 break;
             case 45:
                 num9 = 1154;
                 break;
             case 46:
                 num9 = 1408;
                 break;
             case 47:
                 num9 = 1409;
                 break;
             case 48:
                 num9 = 1410;
                 break;
             case 49:
                 num9 = 1462;
                 break;
             case 50:
                 num9 = 2672;
                 break;
             case 51:
             case 52:
             case 53:
             case 54:
             case 55:
             case 56:
             case 57:
             case 58:
             case 59:
             case 60:
             case 61:
             case 62:
                 num9 = 3651 + num9 - 51;
                 break;
             default:
                 num9 = ((num9 >= 63 && num9 <= 75) ? (3708 + num9 - 63) : (num9 switch
                 {
                     76 => 4397,
                     77 => 4360,
                     78 => 4342,
                     79 => 4466,
                     80 => 5317,
                     81 => 5318,
                     82 => 5319,
                     _ => 438 + num9 - 2,
                 }));
                 break;
             }
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num9);
         }
         if (type == 356)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 3064);
         }
         if (type == 663)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 5381);
         }
         if (type == 456)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 3748);
         }
         if (type == 337)
         {
             int num11 = frameX / 36;
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 2702 + num11);
         }
         if (type == 207)
         {
             int num12 = frameX / 36;
             switch (num12)
             {
             case 0:
                 num12 = 909;
                 break;
             case 1:
                 num12 = 910;
                 break;
             case 2:
             case 3:
             case 4:
             case 5:
             case 6:
             case 7:
                 num12 = 938 + num12;
                 break;
             default:
                 switch (num12)
                 {
                 case 8:
                     num12 = 4922;
                     break;
                 case 9:
                     num12 = 4417;
                     break;
                 }
                 break;
             }
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num12);
         }
         if (type == 410)
         {
             int num13 = frameX / 36;
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num13 + 3536);
         }
         if (type == 480)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4054);
         }
         if (type == 509)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4318);
         }
         if (type == 657)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 5345);
         }
         if (type == 658)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 5347);
         }
         if (type == 489)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4074);
         }
         if (type == 320)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 2496);
         }
         if (type == 349)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 470);
         }
         if (type == 506)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4276);
         }
         if (type == 545)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4420);
         }
         if (type == 465)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 3815);
         }
         if (type == 531)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4355);
         }
         if (type == 378)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 48, 3202);
             TETrainingDummy.Kill(num, num6);
         }
         if (type == 560)
         {
             int num14 = frameX / 36;
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num14 + 4599);
         }
         if (type == 591)
         {
             int num15 = frameX / 36;
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num15 + 4858);
         }
         if (type == 592)
         {
             Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4867);
         }
         destroyObject = false;
     }
References Tile.active(), Tile.frameX, Tile.frameY, Framing.GetTileSafely(), TETrainingDummy.Kill(), Item.NewItem(), TileID.Sets.Platforms, Main.tile, and Tile.type.