Terraria: WorldGen.worldGenCallback
worldGenCallback()
static void WorldGen.worldGenCallback (object threadContext) inline static
     {
         SoundEngine.PlaySound(10);
         clearWorld();
         GenerateWorld(Main.ActiveWorldFileData.Seed, threadContext as GenerationProgress);
         WorldFile.SaveWorld(Main.ActiveWorldFileData.IsCloudSave, resetTime: true);
         if (Main.menuMode == 10 || Main.menuMode == 888)
         {
             Main.menuMode = 6;
         }
         SoundEngine.PlaySound(10);
         generatingWorld = false;
     }
References Main.ActiveWorldFileData, clearWorld(), GenerateWorld(), generatingWorld, FileData.IsCloudSave, Main.menuMode, SoundEngine.PlaySound(), WorldFile.SaveWorld(), and WorldFileData.Seed.
Referenced by CreateNewWorld().