Terraria: WorldGen.CheckSunflower
CheckSunflower()
static void WorldGen.CheckSunflower (int i, int j, int type = 27) inline static
     {
         if (destroyObject)
         {
             return;
         }
         bool flag = false;
         int num = 0;
         int num2 = j;
         num += Main.tile[i, j].frameX / 18;
         num2 += Main.tile[i, j].frameY / 18 * -1;
         while (num > 1)
         {
             num -= 2;
         }
         num *= -1;
         num += i;
         for (int k = num; k < num + 2; k++)
         {
             for (int l = num2; l < num2 + 4; l++)
             {
                 if (Main.tile[k, l] == null)
                 {
                     Main.tile[k, l] = new Tile();
                 }
                 int num3;
                 for (num3 = Main.tile[k, l].frameX / 18; num3 > 1; num3 -= 2)
                 {
                 }
                 if (!Main.tile[k, l].nactive() || Main.tile[k, l].type != type || num3 != k - num || Main.tile[k, l].frameY != (l - num2) * 18)
                 {
                     flag = true;
                 }
             }
             if (Main.tile[k, num2 + 4] == null)
             {
                 Main.tile[k, num2 + 4] = new Tile();
             }
             if (!Main.tile[k, num2 + 4].nactive() || (Main.tile[k, num2 + 4].type != 2 && Main.tile[k, num2 + 4].type != 477 && Main.tile[k, num2 + 4].type != 492 && Main.tile[k, num2 + 4].type != 109 && Main.tile[k, num2 + 4].type != 60 && Main.tile[k, num2 + 4].type != 633))
             {
                 flag = true;
             }
             if (!SolidTile(k, num2 + 4))
             {
                 flag = true;
             }
         }
         if (!flag)
         {
             return;
         }
         destroyObject = true;
         for (int m = num; m < num + 2; m++)
         {
             for (int n = num2; n < num2 + 4; n++)
             {
                 if (Main.tile[m, n].type == type && Main.tile[m, n].active())
                 {
                     KillTile(m, n);
                 }
             }
         }
         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 63);
         destroyObject = false;
     }
References Tile.active(), Tile.frameX, Tile.frameY, Tile.nactive(), Item.NewItem(), SolidTile, Main.tile, and Tile.type.