Terraria: System.Xml.XmlSubtreeReader.ReadContentAsAsync
ReadContentAsAsync() [1/2]
override async Task< object > System.Xml.XmlSubtreeReader.ReadContentAsAsync (Type returnType, IXmlNamespaceResolver namespaceResolver) inline
Definition at line 1527 of file XmlSubtreeReader.cs.
    {
        try
        {
            InitReadContentAsType("ReadContentAs");
            object result = await reader.ReadContentAsAsync(returnType, namespaceResolver).ConfigureAwait(continueOnCapturedContext: false);
            FinishReadContentAsType();
            return result;
        }
        catch
        {
            _state = State.Error;
            throw;
        }
    }
References System.Xml.XmlSubtreeReader._state, System.Xml.XmlSubtreeReader.FinishReadContentAsType(), System.Xml.XmlSubtreeReader.InitReadContentAsType(), System.Xml.XmlReader.ReadContentAsAsync(), and System.Xml.XmlWrappingReader.reader.