Terraria: WorldGen.CheckSpecialTownNPCSpawningConditions
CheckSpecialTownNPCSpawningConditions()
static bool WorldGen.CheckSpecialTownNPCSpawningConditions (int type) inline static
     {
         if (type == 160)
         {
             if (!NPC.unlockedTruffleSpawn && (double)roomY2 > Main.worldSurface)
             {
                 return false;
             }
             Housing_GetTestedRoomBounds(out var startX, out var endX, out var startY, out var endY);
             int num = 0;
             for (int i = startX + 1; i < endX; i++)
             {
                 for (int j = startY + 2; j < endY + 2; j++)
                 {
                     Tile tile = Main.tile[i, j];
                     if (tile.active() && (tile.type == 70 || tile.type == 71 || tile.type == 72 || tile.type == 528))
                     {
                         num++;
                     }
                 }
             }
             if (num >= SceneMetrics.MushroomTileThreshold)
             {
                 return true;
             }
             return false;
         }
         return true;
     }
References Tile.active(), Housing_GetTestedRoomBounds(), SceneMetrics.MushroomTileThreshold, roomY2, Main.tile, Tile.type, NPC.unlockedTruffleSpawn, and Main.worldSurface.
Referenced by FindAHomelessNPC(), IsThereASpawnablePrioritizedTownNPC(), IsThereASpawnablePrioritizedTownNPC_Old(), and MoveTownNPC().