Terraria: WorldGen.SonOfLakinater
SonOfLakinater()
static void WorldGen.SonOfLakinater (int i, int j, double strengthMultiplier = 1.0) inline static
     {
         //IL_0176: Unknown result type (might be due to invalid IL or missing references)
         //IL_018b: Unknown result type (might be due to invalid IL or missing references)
         //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
         //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
         //IL_0661: Unknown result type (might be due to invalid IL or missing references)
         //IL_0662: Unknown result type (might be due to invalid IL or missing references)
         //IL_0663: Unknown result type (might be due to invalid IL or missing references)
         //IL_0668: Unknown result type (might be due to invalid IL or missing references)
         //IL_06aa: Unknown result type (might be due to invalid IL or missing references)
         //IL_06cb: Unknown result type (might be due to invalid IL or missing references)
         //IL_020f: Unknown result type (might be due to invalid IL or missing references)
         //IL_022a: Unknown result type (might be due to invalid IL or missing references)
         //IL_0245: Unknown result type (might be due to invalid IL or missing references)
         //IL_0260: Unknown result type (might be due to invalid IL or missing references)
         //IL_06ec: Unknown result type (might be due to invalid IL or missing references)
         //IL_0728: Unknown result type (might be due to invalid IL or missing references)
         //IL_040e: Unknown result type (might be due to invalid IL or missing references)
         bool lava = false;
         if (getGoodWorldGen && genRand.Next(3) == 0)
         {
             lava = true;
         }
         double num = (double)genRand.Next(15, 31) * strengthMultiplier;
         double num2 = genRand.Next(30, 61);
         if (genRand.Next(5) == 0)
         {
             num *= 1.3;
             num2 *= 1.3;
         }
         if (drunkWorldGen)
         {
             num *= 1.3;
             num2 *= 1.3;
         }
         Vector2D val = default(Vector2D);
         val.X = i;
         val.Y = j;
         double num3 = genRand.NextDouble() * 0.002;
         Vector2D val2 = default(Vector2D);
         if (genRand.Next(4) != 0)
         {
             val2.X = (double)genRand.Next(-15, 16) * 0.01;
         }
         else
         {
             val2.X = (double)genRand.Next(-50, 51) * 0.01;
             num3 = genRand.NextDouble() * 0.004 + 0.001;
         }
         val2.Y = (double)genRand.Next(101) * 0.01;
         double num4 = num;
         double num5 = num2;
         while (num > 3.0 && num2 > 0.0)
         {
             num -= (double)genRand.Next(11) * 0.1;
             num2 -= 1.0;
             int num6 = (int)(val.X - num * 4.0);
             int num7 = (int)(val.X + num * 4.0);
             int num8 = (int)(val.Y - num * 3.0);
             int num9 = (int)(val.Y + num * 2.0);
             if (num6 < 0)
             {
                 num6 = 0;
             }
             if (num7 > Main.maxTilesX)
             {
                 num7 = Main.maxTilesX;
             }
             if (num8 < 0)
             {
                 num8 = 0;
             }
             if (num9 > Main.maxTilesY)
             {
                 num9 = Main.maxTilesY;
             }
             num4 = num;
             for (int k = num6; k < num7; k++)
             {
                 for (int l = num8; l < num9; l++)
                 {
                     double value = Math.Abs((double)k - val.X) * 0.6;
                     double value2 = Math.Abs((double)l - val.Y) * 1.4;
                     double value3 = Math.Abs((double)k - val.X) * 0.3;
                     double value4 = Math.Abs((double)l - val.Y) * 5.0;
                     value = Utils.Lerp(value, value3, num2 / num5);
                     value2 = Utils.Lerp(value2, value4, num2 / num5);
                     double num10 = Math.Sqrt(value * value + value2 * value2);
                     int num11 = j + 5;
                     if (num10 < num4 * 0.4)
                     {
                         if (l >= j)
{
                             if (l <= j + 1)
{
                                 if (WillWaterPlacedHereStayPut(k, l))
{
                                     Main.tile[k, l].liquid = byte.MaxValue;
                                     Main.tile[k, l].lava(lava);
                                 }
                             }
                             else
{
                                 Main.tile[k, l].liquid = byte.MaxValue;
                                 Main.tile[k, l].lava(lava);
                             }
                         }
                         Main.tile[k, l].active(active: false);
                         if (!gen)
{
                             SquareTileFrame(k, l);
                         }
                         if (Main.tile[k, l].type == 59 || Main.tile[k, l].type == 60)
{
                             SpreadGrass(k - 1, l, 59, 60);
                             SpreadGrass(k + 1, l, 59, 60);
                             SpreadGrass(k, l + 1, 59, 60);
                         }
                     }
                     else if (l > j + 1 && num10 < num4 && Main.tile[k, l].liquid == 0)
                     {
                         if (Math.Abs((double)k - val.X) * 0.8 < num4 && Main.tile[k, l].wall > 0 && Main.tile[k - 1, l].wall > 0 && Main.tile[k + 1, l].wall > 0 && Main.tile[k, l + 1].wall > 0)
{
                             Main.tile[k, l].active(active: true);
                         }
                     }
                     else
                     {
                         if (l >= j || num2 != num5 - 1.0 || !((double)l > GenVars.worldSurfaceLow - 20.0) || TileID.Sets.Clouds[Main.tile[k, l].type])
{
                             continue;
                         }
                         value = (double)Math.Abs(k - i) * 0.7;
                         value2 = (double)Math.Abs(l - num11) * 1.35;
                         num10 = Math.Sqrt(value * value + value2 * value2);
                         double num12 = num4 * 0.4;
                         double num13 = (double)Math.Abs(k - i) / (double)(num7 - i);
                         num13 = 1.0 - num13;
                         num13 *= 2.3;
                         num13 *= num13;
                         num13 *= num13;
                         if (l < num11 && value < num12 + (double)Math.Abs(l - num11) * 0.5 * num13)
{
                             Main.tile[k, l].active(active: false);
                             if (Main.tile[k, l].type == 59 || Main.tile[k, l].type == 60)
{
                                 SpreadGrass(k - 1, l, 59, 60);
                                 SpreadGrass(k + 1, l, 59, 60);
                                 SpreadGrass(k, l + 1, 59, 60);
                             }
                         }
                     }
                 }
             }
             val += val2;
             val2.X += (double)genRand.Next(-100, 101) * num3;
             val2.Y += (double)genRand.Next(-100, 101) * 0.01;
             if (val2.X > 1.0)
             {
                 val2.X = 1.0;
             }
             if (val2.X < -1.0)
             {
                 val2.X = -1.0;
             }
             if (val2.Y > 1.0)
             {
                 val2.Y = 1.0;
             }
             double num14 = 0.5 * (1.0 - num2 / num5);
             if (val2.Y < num14)
             {
                 val2.Y = num14;
             }
         }
     }
References Tile.active(), TileID.Sets.Clouds, Tile.lava(), Utils.Lerp(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Main.tile, Tile.type, Tile.wall, GenVars.worldSurfaceLow, Vector2D.X, and Vector2D.Y.