Terraria: System.Xml.XmlSubtreeReader.ReadContentAsObject
ReadContentAsObject()
override object System.Xml.XmlSubtreeReader.ReadContentAsObject () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 611 of file XmlSubtreeReader.cs.
    {
        try
        {
            InitReadContentAsType("ReadContentAsObject");
            object result = reader.ReadContentAsObject();
            FinishReadContentAsType();
            return result;
        }
        catch
        {
            _state = State.Error;
            throw;
        }
    }
References System.Xml.XmlSubtreeReader._state, System.Xml.XmlSubtreeReader.FinishReadContentAsType(), System.Xml.XmlSubtreeReader.InitReadContentAsType(), System.Xml.XmlReader.ReadContentAsObject(), and System.Xml.XmlWrappingReader.reader.