Terraria: WorldGen.PoundPlatform
PoundPlatform()
static void WorldGen.PoundPlatform (int x, int y) inline static
     {
         if (Main.tile[x, y].halfBrick())
         {
             PoundTile(x, y);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 7, x, y, 1f);
             }
             return;
         }
         int num = 1;
         int slope = 2;
         if (TileID.Sets.Platforms[Main.tile[x + 1, y - 1].type] || TileID.Sets.Platforms[Main.tile[x - 1, y + 1].type] || (SolidTile(x + 1, y) && !SolidTile(x - 1, y)))
         {
             num = 2;
             slope = 1;
         }
         if (Main.tile[x, y].slope() == 0)
         {
             SlopeTile(x, y, num);
             int num2 = Main.tile[x, y].slope();
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 14, x, y, num2);
             }
             return;
         }
         if (Main.tile[x, y].slope() == num)
         {
             SlopeTile(x, y, slope);
             int num3 = Main.tile[x, y].slope();
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 14, x, y, num3);
             }
             return;
         }
         SlopeTile(x, y);
         int num4 = Main.tile[x, y].slope();
         if (Main.netMode == 1)
         {
             NetMessage.SendData(17, -1, -1, null, 14, x, y, num4);
         }
         PoundTile(x, y);
         if (Main.netMode == 1)
         {
             NetMessage.SendData(17, -1, -1, null, 7, x, y, 1f);
         }
     }
References Tile.halfBrick(), Main.netMode, TileID.Sets.Platforms, NetMessage.SendData(), Tile.slope(), SolidTile, Main.tile, and Tile.type.