Terraria: UISearchBar.DrawSelf
DrawSelf()
override void UISearchBar.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         base.DrawSelf(spriteBatch);
         if (!isWritingText)
         {
             return;
         }
         PlayerInput.WritingText = true;
         Main.instance.HandleIME();
         Vector2 position = new Vector2(Main.screenWidth / 2, _text.GetDimensions().ToRectangle().Bottom + 32);
         Main.instance.DrawWindowsIMEPanel(position, 0.5f);
         string inputText = Main.GetInputText(actualContents);
         if (Main.inputTextEnter)
         {
             ToggleTakingText();
         }
         else if (Main.inputTextEscape)
         {
             ToggleTakingText();
             if (this.OnCanceledTakingInput != null)
             {
                 this.OnCanceledTakingInput();
             }
         }
         SetContents(inputText);
         position = new Vector2(Main.screenWidth / 2, _text.GetDimensions().ToRectangle().Bottom + 32);
         Main.instance.DrawWindowsIMEPanel(position, 0.5f);
     }
References _text, actualContents, Main.DrawWindowsIMEPanel(), Main.GetInputText(), Main.HandleIME(), Main.inputTextEnter, Main.inputTextEscape, Main.instance, isWritingText, OnCanceledTakingInput, Main.screenWidth, SetContents(), ToggleTakingText(), and PlayerInput.WritingText.