Terraria: DebugKeyboard.DebugDraw
DebugDraw()
override void DebugKeyboard.DebugDraw (IDebugDrawer drawer, Vector2 position, float scale) inline virtual
Reimplemented from RgbDevice.
     {
         for (int i = 0; i < ((RgbDevice)this).LedCount; i++)
         {
             Vector2 ledCanvasPosition = ((RgbDevice)this).GetLedCanvasPosition(i);
             drawer.DrawSquare(new Vector4(ledCanvasPosition * scale + position, scale / 100f, scale / 100f), new Color(((RgbDevice)this).GetUnprocessedLedColor(i)));
         }
     }
References RgbDevice.RgbDevice(), Color, IDebugDrawer.DrawSquare(), and RgbDevice.GetUnprocessedLedColor().