Terraria: DropRateInfoChainFeed.With
With()
DropRateInfoChainFeed DropRateInfoChainFeed.With (float multiplier) inline
     {
         DropRateInfoChainFeed result = new DropRateInfoChainFeed(parentDroprateChance * multiplier);
         if (conditions != null)
         {
             result.conditions = new List<IItemDropRuleCondition>(conditions);
         }
         return result;
     }
References DropRateInfoChainFeed(), conditions, and parentDroprateChance.
Referenced by Chains.TryIfFailedRandomRoll.ReportDroprates(), Chains.TryIfSucceeded.ReportDroprates(), Chains.TryIfDoesntFillConditions.ReportDroprates(), DropBasedOnExpertMode.ReportDroprates(), DropBasedOnMasterAndExpertMode.ReportDroprates(), DropBasedOnMasterMode.ReportDroprates(), ItemDropWithConditionRule.ReportDroprates(), and OneFromRulesRule.ReportDroprates().