Terraria: System.Data.XmlTreeGen.FillDataSetElement
FillDataSetElement()
XmlElement System.Data.XmlTreeGen.FillDataSetElement (XmlDocument xd, DataSet ds, DataTable dt) inline package
Definition at line 870 of file XmlTreeGen.cs.
    {
        DataSet dataSet = ((ds != null) ? ds : dt.DataSet);
        if (dataSet != null)
        {
            _dsElement.SetAttribute("name", XmlConvert.EncodeLocalName(dataSet.DataSetName));
            _dsElement.SetAttribute("IsDataSet", "urn:schemas-microsoft-com:xml-msdata", "true");
            if (ds == null)
            {
                _dsElement.SetAttribute("MainDataTable", "urn:schemas-microsoft-com:xml-msdata", XmlConvert.EncodeLocalName((dt.Namespace.Length == 0) ? dt.TableName : (dt.Namespace + ":" + dt.TableName)));
            }
            if (dataSet.CaseSensitive)
            {
                _dsElement.SetAttribute("CaseSensitive", "urn:schemas-microsoft-com:xml-msdata", "true");
            }
            if (dataSet.ShouldSerializeLocale() || !dataSet.Locale.Equals(CultureInfo.CurrentCulture))
            {
                _dsElement.SetAttribute("Locale", "urn:schemas-microsoft-com:xml-msdata", dataSet.Locale.ToString());
            }
            else
            {
                _dsElement.SetAttribute("UseCurrentLocale", "urn:schemas-microsoft-com:xml-msdata", "true");
            }
        }
        else if (dt != null)
        {
            _dsElement.SetAttribute("name", XmlConvert.EncodeLocalName("NewDataSet"));
            _dsElement.SetAttribute("IsDataSet", "urn:schemas-microsoft-com:xml-msdata", "true");
            _dsElement.SetAttribute("MainDataTable", "urn:schemas-microsoft-com:xml-msdata", XmlConvert.EncodeLocalName((dt.Namespace.Length == 0) ? dt.TableName : (dt.Namespace + ":" + dt.TableName)));
            if (dt.CaseSensitive)
            {
                _dsElement.SetAttribute("CaseSensitive", "urn:schemas-microsoft-com:xml-msdata", "true");
            }
            if (dt.ShouldSerializeLocale() || !dt.Locale.Equals(CultureInfo.CurrentCulture))
            {
                _dsElement.SetAttribute("Locale", "urn:schemas-microsoft-com:xml-msdata", dt.Locale.ToString());
            }
            else
            {
                _dsElement.SetAttribute("UseCurrentLocale", "urn:schemas-microsoft-com:xml-msdata", "true");
            }
        }
        XmlElement xmlElement = xd.CreateElement("xs", "complexType", "http://www.w3.org/2001/XMLSchema");
        _dsElement.AppendChild(xmlElement);
        XmlElement xmlElement2 = xd.CreateElement("xs", "choice", "http://www.w3.org/2001/XMLSchema");
        xmlElement2.SetAttribute("minOccurs", "0");
        xmlElement2.SetAttribute("maxOccurs", "unbounded");
        xmlElement.AppendChild(xmlElement2);
        return xmlElement2;
    }
References System.Data.XmlTreeGen._dsElement, System.Xml.XmlNode.AppendChild(), System.Globalization.CultureInfo.CurrentCulture, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), and System.Xml.XmlElement.SetAttribute().
Referenced by System.Data.XmlTreeGen.SchemaTree(), and System.Data.XmlTreeGen.SchemaTree().