Terraria: System.Data.XmlTreeGen.HandleColumnType
HandleColumnType()
void System.Data.XmlTreeGen.HandleColumnType (DataColumn col, XmlDocument dc, XmlElement root, XmlElement schema) inline package
Definition at line 1080 of file XmlTreeGen.cs.
    {
        string name = "type";
        if (col.ColumnMapping == MappingType.SimpleContent)
        {
            name = "base";
        }
        if (col.SimpleType != null)
        {
            for (SimpleType simpleType = col.SimpleType; simpleType != null; simpleType = simpleType.BaseSimpleType)
            {
                string name2 = simpleType.Name;
                if (name2 != null && name2.Length != 0)
                {
                    string text = ((_schFormat != SchemaFormat.Remoting) ? simpleType.Namespace : ((col.Table.DataSet != null) ? col.Table.DataSet.Namespace : col.Table.Namespace));
                    XmlElement schema2 = GetSchema(text);
                    if (simpleType.BaseSimpleType != null && simpleType.BaseSimpleType.Namespace != null && simpleType.BaseSimpleType.Namespace.Length > 0)
                    {
                        GetSchema(simpleType.BaseSimpleType.Namespace);
                    }
                    XmlNode newChild = simpleType.ToNode(dc, _prefixes, _schFormat == SchemaFormat.Remoting);
                    if (simpleType == col.SimpleType)
                    {
                        string text2 = (string)_prefixes[text];
                        if (text2 != null && text2.Length > 0)
{
                            if (_schFormat != SchemaFormat.Remoting)
{
                                root.SetAttribute(name, text2 + ":" + name2);
                            }
                            else
{
                                root.SetAttribute(name, name2);
                            }
                        }
                        else
{
                            root.SetAttribute(name, name2);
                        }
                    }
                    XmlElement xmlElement = FindSimpleType(schema2, name2);
                    if (xmlElement == null)
                    {
                        schema2.AppendChild(newChild);
                    }
                }
                else
                {
                    if (simpleType.BaseSimpleType != null && simpleType.BaseSimpleType.Namespace != null && simpleType.BaseSimpleType.Namespace.Length > 0)
                    {
                        GetSchema(simpleType.BaseSimpleType.Namespace);
                    }
                    XmlNode newChild = simpleType.ToNode(dc, _prefixes, _schFormat == SchemaFormat.Remoting);
                    root.AppendChild(newChild);
                }
            }
            return;
        }
        if (col.XmlDataType != null && col.XmlDataType.Length != 0 && XSDSchema.IsXsdType(col.XmlDataType))
        {
            root.SetAttribute(name, XSDSchema.QualifiedName(col.XmlDataType));
            return;
        }
        string text3 = XmlDataTypeName(col.DataType);
        if (text3 == null || text3.Length == 0)
        {
            if (col.DataType == typeof(Guid) || col.DataType == typeof(Type))
            {
                text3 = "string";
            }
            else
            {
                if (col.ColumnMapping == MappingType.Attribute)
                {
                    ValidateColumnMapping(col.DataType);
                }
                text3 = "anyType";
            }
        }
        root.SetAttribute(name, XSDSchema.QualifiedName(text3));
    }
References System.Data.SimpleType.SimpleType(), System.Data.XmlTreeGen._prefixes, System.Data.XmlTreeGen._schFormat, System.Xml.XmlNode.AppendChild(), System.Xml.Dictionary, System.Data.XmlTreeGen.FindSimpleType(), System.Data.XmlTreeGen.GetSchema(), System.Data.XSDSchema.IsXsdType(), System.Data.XSDSchema.QualifiedName(), System.Xml.XmlElement.SetAttribute(), System.text, System.Data.XmlTreeGen.ValidateColumnMapping(), and System.Data.XmlTreeGen.XmlDataTypeName().
Referenced by System.Data.XmlTreeGen.HandleColumn(), and System.Data.XmlTreeGen.HandleTable().