Terraria: System.Data.XmlTreeGen.SchemaTree
SchemaTree() [2/2]
void System.Data.XmlTreeGen.SchemaTree (XmlDocument xd, XmlWriter xmlWriter, DataSet ds, DataTable dt, bool writeHierarchy) inline package
Definition at line 496 of file XmlTreeGen.cs.
    {
        _constraintNames = new ArrayList();
        _autogenerated = new Hashtable();
        bool flag = _filePath != null;
        _dsElement = xd.CreateElement("xs", "element", "http://www.w3.org/2001/XMLSchema");
        bool flag2 = false;
        if (ds != null)
        {
            _ds = ds;
            foreach (DataTable table in ds.Tables)
            {
                _tables.Add(table);
            }
        }
        else
        {
            if (dt.DataSet != null)
            {
                _ds = dt.DataSet;
            }
            _tables.Add(dt);
            if (writeHierarchy)
            {
                CreateTablesHierarchy(dt);
            }
        }
        _dc = xd;
        _namespaces = new Hashtable();
        _prefixes = new Hashtable();
        XmlElement xmlElement = (_sRoot = xd.CreateElement("xs", "schema", "http://www.w3.org/2001/XMLSchema"));
        if (_ds != null)
        {
            xmlElement.SetAttribute("id", XmlConvert.EncodeLocalName(_ds.DataSetName));
        }
        else
        {
            xmlElement.SetAttribute("id", XmlConvert.EncodeLocalName("NewDataSet"));
        }
        if (_ds != null)
        {
            WriteSchemaRoot(xd, xmlElement, _ds.Namespace);
        }
        else
        {
            WriteSchemaRoot(xd, xmlElement, dt.Namespace);
        }
        if (_schFormat == SchemaFormat.Remoting)
        {
            if (_ds != null)
            {
                _namespaces[_ds.Namespace] = xmlElement;
            }
            else
            {
                _namespaces[dt.Namespace] = xmlElement;
            }
        }
        if (_schFormat != SchemaFormat.Remoting && _ds != null)
        {
            _namespaces[_ds.Namespace] = xmlElement;
            if (_ds.Namespace.Length == 0)
            {
                _prefixes[_ds.Namespace] = null;
            }
            else
            {
                xmlElement.SetAttribute("xmlns:mstns", _ds.Namespace);
                _prefixes[_ds.Namespace] = "mstns";
            }
        }
        if (ds != null)
        {
            GenerateConstraintNames(ds);
        }
        else
        {
            GenerateConstraintNames(_tables);
        }
        if (_schFormat != SchemaFormat.Remoting)
        {
            if (ds != null)
            {
                SetupAutoGenerated(ds);
            }
            else
            {
                SetupAutoGenerated(_tables);
            }
        }
        DataTable[] array = ((ds != null) ? ds.TopLevelTables(forSchema: true) : CreateToplevelTables());
        if (array.Length == 0 || _schFormat == SchemaFormat.WebServiceSkipSchema || _schFormat == SchemaFormat.RemotingSkipSchema)
        {
            FillDataSetElement(xd, ds, dt);
            xmlElement.AppendChild(_dsElement);
            AddXdoProperties(_ds, _dsElement, xd);
            AddExtendedProperties(ds._extendedProperties, _dsElement);
            xd.AppendChild(xmlElement);
            xd.Save(xmlWriter);
            xmlWriter.Flush();
            return;
        }
        XmlElement xmlElement2 = FillDataSetElement(xd, ds, dt);
        _constraintSeparator = xd.CreateElement("xs", "SHOULDNOTBEHERE", "http://www.w3.org/2001/XMLSchema");
        _dsElement.AppendChild(_constraintSeparator);
        if (_ds != null)
        {
            AddXdoProperties(_ds, _dsElement, xd);
            AddExtendedProperties(_ds._extendedProperties, _dsElement);
        }
        for (int i = 0; i < array.Length; i++)
        {
            XmlElement xmlElement3 = HandleTable(array[i], xd, xmlElement);
            if ((_ds != null && _ds.Namespace == array[i].Namespace) || string.IsNullOrEmpty(array[i].Namespace) || _schFormat == SchemaFormat.Remoting)
            {
                bool flag3 = array[i]._fNestedInDataset;
                if (_ds != null && _ds.Namespace.Length != 0 && string.IsNullOrEmpty(array[i].Namespace))
                {
                    flag3 = true;
                }
                if (array[i].SelfNested)
                {
                    flag3 = false;
                }
                if (array[i].NestedParentsCount > 1)
                {
                    flag3 = false;
                }
                if (flag3)
                {
                    if (array[i].MinOccurs != 1m)
                    {
                        xmlElement3.SetAttribute("minOccurs", array[i].MinOccurs.ToString(CultureInfo.InvariantCulture));
                    }
                    if (array[i].MaxOccurs == -1m)
                    {
                        xmlElement3.SetAttribute("maxOccurs", "unbounded");
                    }
                    else if (array[i].MaxOccurs != 1m)
                    {
                        xmlElement3.SetAttribute("maxOccurs", array[i].MaxOccurs.ToString(CultureInfo.InvariantCulture));
                    }
                }
                if (!flag3)
                {
                    xmlElement.AppendChild(xmlElement3);
                    XmlElement xmlElement4 = xd.CreateElement("xs", "element", "http://www.w3.org/2001/XMLSchema");
                    if ((_ds != null && _ds.Namespace == array[i].Namespace) || string.IsNullOrEmpty(array[i].Namespace) || _schFormat == SchemaFormat.Remoting)
                    {
                        xmlElement4.SetAttribute("ref", array[i].EncodedTableName);
                    }
                    else
                    {
                        xmlElement4.SetAttribute("ref", (string)_prefixes[array[i].Namespace] + ":" + array[i].EncodedTableName);
                    }
                    xmlElement2.AppendChild(xmlElement4);
                }
                else
                {
                    xmlElement2.AppendChild(xmlElement3);
                }
            }
            else
            {
                AppendChildWithoutRef(xmlElement, array[i].Namespace, xmlElement3, "element");
                XmlElement xmlElement5 = xd.CreateElement("xs", "element", "http://www.w3.org/2001/XMLSchema");
                xmlElement5.SetAttribute("ref", (string)_prefixes[array[i].Namespace] + ":" + array[i].EncodedTableName);
                xmlElement2.AppendChild(xmlElement5);
            }
        }
        _dsElement.RemoveChild(_constraintSeparator);
        xmlElement.AppendChild(_dsElement);
        DataRelation[] array2 = Array.Empty<DataRelation>();
        if (ds != null && _tables.Count > 0)
        {
            array2 = new DataRelation[ds.Relations.Count];
            for (int j = 0; j < ds.Relations.Count; j++)
            {
                array2[j] = ds.Relations[j];
            }
        }
        else if (writeHierarchy && _tables.Count > 0)
        {
            CreateRelations((DataTable)_tables[0]);
            array2 = new DataRelation[_relations.Count];
            _relations.CopyTo(array2, 0);
        }
        XmlElement xmlElement6 = null;
        XmlElement xmlElement7 = null;
        foreach (DataRelation dataRelation in array2)
        {
            if ((!dataRelation.Nested || flag2) && dataRelation.ChildKeyConstraint == null)
            {
                if (xmlElement6 == null)
                {
                    xmlElement6 = xd.CreateElement("xs", "annotation", "http://www.w3.org/2001/XMLSchema");
                    xmlElement.AppendChild(xmlElement6);
                    xmlElement7 = xd.CreateElement("xs", "appinfo", "http://www.w3.org/2001/XMLSchema");
                    xmlElement6.AppendChild(xmlElement7);
                }
                xmlElement7.AppendChild(HandleRelation(dataRelation, xd));
            }
        }
        XmlComment xmlComment = null;
        bool flag4 = _namespaces.Count > 1 && !flag;
        if (_schFormat != SchemaFormat.Remoting && _schFormat != SchemaFormat.RemotingSkipSchema)
        {
            foreach (string key in _namespaces.Keys)
            {
                if (!(key == ((_ds != null) ? _ds.Namespace : dt.Namespace)) && !string.IsNullOrEmpty(key))
                {
                    XmlElement xmlElement8 = xd.CreateElement("xs", "import", "http://www.w3.org/2001/XMLSchema");
                    xmlElement8.SetAttribute("namespace", key);
                    if (_schFormat != SchemaFormat.WebService && !flag4)
                    {
                        xmlElement8.SetAttribute("schemaLocation", _fileName + "_" + _prefixes[key]?.ToString() + ".xsd");
                    }
                    xmlElement.PrependChild(xmlElement8);
                }
            }
            if (_schFormat != SchemaFormat.WebService && flag4)
            {
                xmlElement.SetAttribute("schemafragmentcount", "urn:schemas-microsoft-com:xml-msdata", _namespaces.Count.ToString(CultureInfo.InvariantCulture));
            }
            xd.AppendChild(xmlElement);
            if (_schFormat != SchemaFormat.WebService && flag4)
            {
                xd.WriteTo(xmlWriter);
            }
            else
            {
                xd.Save(xmlWriter);
            }
            xd.RemoveChild(xmlElement);
            foreach (string key2 in _namespaces.Keys)
            {
                if (key2 == ((_ds != null) ? _ds.Namespace : dt.Namespace) || string.IsNullOrEmpty(key2))
                {
                    continue;
                }
                XmlWriter xmlWriter2 = null;
                xmlWriter2 = (flag ? new XmlTextWriter(_filePath + _fileName + "_" + _prefixes[key2]?.ToString() + ".xsd", null) : xmlWriter);
                try
                {
                    if (flag)
                    {
                        if (xmlWriter2 is XmlTextWriter)
{
                            ((XmlTextWriter)xmlWriter2).Formatting = Formatting.Indented;
                        }
                        xmlWriter2.WriteStartDocument(standalone: true);
                    }
                    XmlElement xmlElement9 = (XmlElement)_namespaces[key2];
                    _dc.AppendChild(xmlElement9);
                    foreach (string key3 in _namespaces.Keys)
                    {
                        if (key2 == key3)
{
                            continue;
                        }
                        string text4 = (string)_prefixes[key3];
                        if (text4 == null)
{
                            continue;
                        }
                        xmlElement9.SetAttribute("xmlns:" + text4, key3);
                        XmlElement xmlElement10 = _dc.CreateElement("xs", "import", "http://www.w3.org/2001/XMLSchema");
                        xmlElement10.SetAttribute("namespace", key3);
                        if (_schFormat != SchemaFormat.WebService && !flag4)
{
                            if (key3 == ((_ds != null) ? _ds.Namespace : dt.Namespace))
{
                                xmlElement10.SetAttribute("schemaLocation", _fileName + _fileExt);
                            }
                            else
{
                                xmlElement10.SetAttribute("schemaLocation", _fileName + "_" + text4 + ".xsd");
                            }
                        }
                        xmlElement9.PrependChild(xmlElement10);
                    }
                    if (_schFormat != SchemaFormat.WebService && flag4)
                    {
                        _dc.WriteTo(xmlWriter2);
                    }
                    else
                    {
                        _dc.Save(xmlWriter2);
                    }
                    _dc.RemoveChild(xmlElement9);
                    if (flag)
                    {
                        xmlWriter2.WriteEndDocument();
                    }
                }
                finally
                {
                    if (flag)
                    {
                        xmlWriter2.Close();
                    }
                }
            }
        }
        else
        {
            xd.AppendChild(xmlElement);
            xd.Save(xmlWriter);
        }
        if (xmlComment != null)
        {
            xmlElement.PrependChild(xmlComment);
        }
        if (!flag)
        {
            xmlWriter.Flush();
        }
    }
References System.Data.DataSet.DataSet(), System.Data.XmlTreeGen._autogenerated, System.Data.XmlTreeGen._constraintNames, System.Data.XmlTreeGen._constraintSeparator, System.Data.XmlTreeGen._dc, System.Data.XmlTreeGen._ds, System.Data.XmlTreeGen._dsElement, System.Data.DataSet._extendedProperties, System.Data.XmlTreeGen._fileExt, System.Data.XmlTreeGen._fileName, System.Data.XmlTreeGen._filePath, System.Data.XmlTreeGen._namespaces, System.Data.XmlTreeGen._prefixes, System.Data.XmlTreeGen._relations, System.Data.XmlTreeGen._schFormat, System.Data.XmlTreeGen._sRoot, System.Data.XmlTreeGen._tables, System.Collections.ArrayList.Add(), System.Data.XmlTreeGen.AddExtendedProperties(), System.Data.XmlTreeGen.AddXdoProperties(), System.Xml.XmlNode.AppendChild(), System.Data.XmlTreeGen.AppendChildWithoutRef(), System.array, System.Collections.ArrayList.CopyTo(), System.Collections.ArrayList.Count, System.Collections.Hashtable.Count, System.Xml.XmlDocument.CreateElement(), System.Data.XmlTreeGen.CreateRelations(), System.Data.XmlTreeGen.CreateTablesHierarchy(), System.Data.XmlTreeGen.CreateToplevelTables(), System.Data.DataSet.DataSetName, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Data.XmlTreeGen.FillDataSetElement(), System.Data.XmlTreeGen.GenerateConstraintNames(), System.Data.XmlTreeGen.HandleRelation(), System.Data.XmlTreeGen.HandleTable(), System.Globalization.CultureInfo.InvariantCulture, System.key, System.Collections.Hashtable.Keys, System.Data.DataSet.Namespace, System.Xml.XmlNode.PrependChild(), System.Xml.XmlNode.RemoveChild(), System.Xml.XmlDocument.Save(), System.Xml.XmlElement.SetAttribute(), System.Data.XmlTreeGen.SetupAutoGenerated(), System.ToString, System.Data.XmlTreeGen.WriteSchemaRoot(), System.Xml.XmlWriter.WriteStartDocument(), and System.Xml.XmlDocument.WriteTo().
Referenced by System.Data.XmlTreeGen.Save(), and System.Data.XmlTreeGen.Save().