Terraria: System.Data.XmlTreeGen.FindTargetNamespace
FindTargetNamespace()
string System.Data.XmlTreeGen.FindTargetNamespace (DataTable table) inline private
Definition at line 1210 of file XmlTreeGen.cs.
    {
        string text = (table.TypeName.IsEmpty ? table.Namespace : table.TypeName.Namespace);
        if (string.IsNullOrEmpty(text))
        {
            DataRelation[] nestedParentRelations = table.NestedParentRelations;
            if (nestedParentRelations.Length != 0)
            {
                for (int i = 0; i < nestedParentRelations.Length; i++)
                {
                    DataTable parentTable = nestedParentRelations[i].ParentTable;
                    if (table != parentTable)
                    {
                        text = FindTargetNamespace(parentTable);
                        if (!string.IsNullOrEmpty(text))
{
                            break;
                        }
                    }
                }
            }
            else
            {
                text = _ds.Namespace;
            }
        }
        return text;
    }
References System.Data.XmlTreeGen._ds, System.Xml.Dictionary, System.Data.XmlTreeGen.FindTargetNamespace(), System.Data.DataSet.Namespace, System.Xml.XmlQualifiedName.Namespace, System.Data.DataTable.NestedParentRelations, System.text, and System.Data.DataTable.TypeName.
Referenced by System.Data.XmlTreeGen.FindTargetNamespace(), and System.Data.XmlTreeGen.HandleColumn().