Terraria: System.Data.XmlTreeGen.SetMSDataAttribute
SetMSDataAttribute()
void System.Data.XmlTreeGen.SetMSDataAttribute (XmlElement root, Type type) inline private
Definition at line 1962 of file XmlTreeGen.cs.
    {
        string value = DataStorage.GetQualifiedName(type);
        try
        {
            if (_targetConverter != null)
            {
                value = _targetConverter(type);
            }
            if (!string.IsNullOrEmpty(value))
            {
                root.SetAttribute("DataType", "urn:schemas-microsoft-com:xml-msdata", value);
            }
        }
        catch (Exception ex) when (ADP.IsCatchableExceptionType(ex))
        {
            ExceptionBuilder.ThrowMultipleTargetConverter(ex);
        }
        if (string.IsNullOrEmpty(value))
        {
            ExceptionBuilder.ThrowMultipleTargetConverter(null);
        }
    }
References System.Data.XmlTreeGen._targetConverter, System.Xml.Dictionary, System.Data.Common.DataStorage.GetQualifiedName(), System.Data.Common.ADP.IsCatchableExceptionType(), System.Xml.XmlElement.SetAttribute(), System.Data.ExceptionBuilder.ThrowMultipleTargetConverter(), System.type, and System.value.
Referenced by System.Data.XmlTreeGen.AddColumnProperties(), and System.Data.XmlTreeGen.AddXdoProperty().