Terraria: System.Data.XmlTreeGen.AutoGenerated
AutoGenerated() [1/5]
static bool System.Data.XmlTreeGen.AutoGenerated (DataColumn col) inline static package
Definition at line 1423 of file XmlTreeGen.cs.
    {
        if (col.ColumnMapping != MappingType.Hidden)
        {
            return false;
        }
        if (col.DataType != typeof(int))
        {
            return false;
        }
        string text = col.Table.TableName + "_Id";
        if (col.ColumnName == text || col.ColumnName == text + "_0")
        {
            return true;
        }
        text = string.Empty;
        foreach (DataRelation parentRelation in col.Table.ParentRelations)
        {
            if (parentRelation.Nested && parentRelation.ChildColumnsReference.Length == 1 && parentRelation.ChildColumnsReference[0] == col && parentRelation.ParentColumnsReference.Length == 1)
            {
                text = parentRelation.ParentColumnsReference[0].Table.TableName + "_Id";
            }
        }
        if (col.ColumnName == text || col.ColumnName == text + "_0")
        {
            return true;
        }
        return false;
    }
References System.Xml.Dictionary, and System.text.
Referenced by System.Data.ConstraintCollection.AutoGenerated(), System.Data.XmlTreeGen.AutoGenerated(), System.Data.XmlTreeGen.AutoGenerated(), System.Data.XmlTreeGen.AutoGenerated(), System.Data.XmlTreeGen.HasMixedColumns(), System.Data.XmlTreeGen.SetupAutoGenerated(), and System.Data.DataRelation.ValidateMultipleNestedRelations().