Terraria: System.Data.XmlTreeGen.SchemaTree
SchemaTree() [1/2]
XmlElement System.Data.XmlTreeGen.SchemaTree (XmlDocument xd, DataTable dt) inline package
Definition at line 816 of file XmlTreeGen.cs.
    {
        _dsElement = xd.CreateElement("xs", "element", "http://www.w3.org/2001/XMLSchema");
        _constraintNames = new ArrayList();
        _ds = dt.DataSet;
        _dc = xd;
        _namespaces = new Hashtable();
        _prefixes = new Hashtable();
        if (_schFormat != SchemaFormat.Remoting)
        {
            _autogenerated = new Hashtable();
        }
        XmlElement xmlElement = (_sRoot = xd.CreateElement("xs", "schema", "http://www.w3.org/2001/XMLSchema"));
        WriteSchemaRoot(xd, xmlElement, dt.Namespace);
        FillDataSetElement(xd, null, dt);
        _constraintSeparator = xd.CreateElement("xs", "SHOULDNOTBEHERE", "http://www.w3.org/2001/XMLSchema");
        _dsElement.AppendChild(_constraintSeparator);
        if (_schFormat != SchemaFormat.Remoting)
        {
            if (_ds != null)
            {
                _namespaces[_ds.Namespace] = xmlElement;
                if (_ds.Namespace.Length == 0)
                {
                    _prefixes[_ds.Namespace] = null;
                }
                else
                {
                    xmlElement.SetAttribute("xmlns:mstns", _ds.Namespace);
                    _prefixes[_ds.Namespace] = "mstns";
                }
            }
            else
            {
                _namespaces[dt.Namespace] = xmlElement;
                if (dt.Namespace.Length == 0)
                {
                    _prefixes[dt.Namespace] = null;
                }
                else
                {
                    xmlElement.SetAttribute("xmlns:mstns", dt.Namespace);
                    _prefixes[dt.Namespace] = "mstns";
                }
            }
        }
        GenerateConstraintNames(dt, fromTable: true);
        XmlElement newChild = HandleTable(dt, xd, xmlElement, genNested: false);
        xmlElement.AppendChild(newChild);
        _dsElement.RemoveChild(_constraintSeparator);
        xmlElement.AppendChild(_dsElement);
        return xmlElement;
    }
References System.Data.DataSet.DataSet(), System.Data.XmlTreeGen._autogenerated, System.Data.XmlTreeGen._constraintNames, System.Data.XmlTreeGen._constraintSeparator, System.Data.XmlTreeGen._dc, System.Data.XmlTreeGen._ds, System.Data.XmlTreeGen._dsElement, System.Data.XmlTreeGen._namespaces, System.Data.XmlTreeGen._prefixes, System.Data.XmlTreeGen._schFormat, System.Data.XmlTreeGen._sRoot, System.Xml.XmlNode.AppendChild(), System.Xml.Dictionary, System.Data.XmlTreeGen.FillDataSetElement(), System.Data.XmlTreeGen.GenerateConstraintNames(), System.Data.XmlTreeGen.HandleTable(), System.Data.DataSet.Namespace, System.Xml.XmlNode.RemoveChild(), and System.Data.XmlTreeGen.WriteSchemaRoot().