Terraria: System.Data.XmlTreeGen.AddColumnProperties
AddColumnProperties()
void System.Data.XmlTreeGen.AddColumnProperties (DataColumn col, XmlElement root) inline package
Definition at line 1162 of file XmlTreeGen.cs.
    {
        if (col.DataType != typeof(string))
        {
            string text = XmlDataTypeName(col.DataType);
            if ((col.IsSqlType && (text.Length == 0 || col.ImplementsINullable)) || typeof(SqlXml) == col.DataType || col.DataType == typeof(DateTimeOffset) || col.DataType == typeof(BigInteger))
            {
                root.SetAttribute("DataType", "urn:schemas-microsoft-com:xml-msdata", col.DataType.FullName);
            }
            else if (text.Length == 0 || col.ImplementsINullable || (text == "anyType" && col.XmlDataType != "anyType"))
            {
                SetMSDataAttribute(root, col.DataType);
            }
        }
        if (col.ReadOnly)
        {
            root.SetAttribute("ReadOnly", "urn:schemas-microsoft-com:xml-msdata", "true");
        }
        if (col.Expression.Length != 0)
        {
            root.SetAttribute("Expression", "urn:schemas-microsoft-com:xml-msdata", col.Expression);
        }
        if (col.AutoIncrement)
        {
            root.SetAttribute("AutoIncrement", "urn:schemas-microsoft-com:xml-msdata", "true");
        }
        if (col.AutoIncrementSeed != 0L)
        {
            root.SetAttribute("AutoIncrementSeed", "urn:schemas-microsoft-com:xml-msdata", col.AutoIncrementSeed.ToString(CultureInfo.InvariantCulture));
        }
        if (col.AutoIncrementStep != 1)
        {
            root.SetAttribute("AutoIncrementStep", "urn:schemas-microsoft-com:xml-msdata", col.AutoIncrementStep.ToString(CultureInfo.InvariantCulture));
        }
        if (col.Caption != col.ColumnName)
        {
            root.SetAttribute("Caption", "urn:schemas-microsoft-com:xml-msdata", col.Caption);
        }
        if (col.Prefix.Length != 0)
        {
            root.SetAttribute("Prefix", "urn:schemas-microsoft-com:xml-msdata", col.Prefix);
        }
        if (col.DataType == typeof(DateTime) && col.DateTimeMode != DataSetDateTime.UnspecifiedLocal)
        {
            root.SetAttribute("DateTimeMode", "urn:schemas-microsoft-com:xml-msdata", col.DateTimeMode.ToString());
        }
    }
References System.Xml.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.L, System.Xml.XmlElement.SetAttribute(), System.Data.XmlTreeGen.SetMSDataAttribute(), System.text, and System.Data.XmlTreeGen.XmlDataTypeName().
Referenced by System.Data.XmlTreeGen.HandleColumn(), and System.Data.XmlTreeGen.HandleTable().