Terraria: System.Data.XmlTreeGen.AddExtendedProperties
AddExtendedProperties() [1/2]
static void System.Data.XmlTreeGen.AddExtendedProperties (PropertyCollection props, XmlElement node) inline static package
Definition at line 55 of file XmlTreeGen.cs.
    {
        AddExtendedProperties(props, node, null);
    }
References System.Data.XmlTreeGen.AddExtendedProperties(), and System.Xml.Dictionary.
Referenced by System.Data.XmlTreeGen.AddExtendedProperties(), System.Data.XmlTreeGen.HandleColumn(), System.Data.XmlTreeGen.HandleRelation(), System.Data.XmlTreeGen.HandleTable(), and System.Data.XmlTreeGen.SchemaTree().