Terraria: System.Data.XmlTreeGen.HandleRelation
HandleRelation()
XmlElement System.Data.XmlTreeGen.HandleRelation (DataRelation rel, XmlDocument dc) inline package
Definition at line 993 of file XmlTreeGen.cs.
    {
        XmlElement xmlElement = dc.CreateElement("msdata", "Relationship", "urn:schemas-microsoft-com:xml-msdata");
        xmlElement.SetAttribute("name", XmlConvert.EncodeLocalName(rel.RelationName));
        xmlElement.SetAttribute("parent", "urn:schemas-microsoft-com:xml-msdata", rel.ParentKey.Table.EncodedTableName);
        xmlElement.SetAttribute("child", "urn:schemas-microsoft-com:xml-msdata", rel.ChildKey.Table.EncodedTableName);
        if (_ds == null || _ds.Tables.InternalIndexOf(rel.ParentKey.Table.TableName) == -3)
        {
            xmlElement.SetAttribute("ParentTableNamespace", "urn:schemas-microsoft-com:xml-msdata", rel.ParentKey.Table.Namespace);
        }
        if (_ds == null || _ds.Tables.InternalIndexOf(rel.ChildKey.Table.TableName) == -3)
        {
            xmlElement.SetAttribute("ChildTableNamespace", "urn:schemas-microsoft-com:xml-msdata", rel.ChildKey.Table.Namespace);
        }
        DataColumn[] columnsReference = rel.ParentKey.ColumnsReference;
        string value = columnsReference[0].EncodedColumnName;
        StringBuilder stringBuilder = null;
        if (1 < columnsReference.Length)
        {
            stringBuilder = new StringBuilder();
            stringBuilder.Append(value);
            for (int i = 1; i < columnsReference.Length; i++)
            {
                stringBuilder.Append(' ').Append(columnsReference[i].EncodedColumnName);
            }
            value = stringBuilder.ToString();
        }
        xmlElement.SetAttribute("parentkey", "urn:schemas-microsoft-com:xml-msdata", value);
        columnsReference = rel.ChildKey.ColumnsReference;
        value = columnsReference[0].EncodedColumnName;
        if (1 < columnsReference.Length)
        {
            if (stringBuilder != null)
            {
                stringBuilder.Length = 0;
            }
            else
            {
                stringBuilder = new StringBuilder();
            }
            stringBuilder.Append(value);
            for (int j = 1; j < columnsReference.Length; j++)
            {
                stringBuilder.Append(' ').Append(columnsReference[j].EncodedColumnName);
            }
            value = stringBuilder.ToString();
        }
        xmlElement.SetAttribute("childkey", "urn:schemas-microsoft-com:xml-msdata", value);
        AddExtendedProperties(rel._extendedProperties, xmlElement);
        return xmlElement;
    }
References System.Data.XmlTreeGen._ds, System.Data.XmlTreeGen.AddExtendedProperties(), System.Xml.Dictionary, System.Data.DataColumn.EncodedColumnName, System.Xml.XmlConvert.EncodeLocalName(), System.Data.DataTableCollection.InternalIndexOf(), System.Xml.XmlElement.SetAttribute(), System.Data.DataSet.Tables, and System.value.
Referenced by System.Data.XmlTreeGen.HandleTable(), and System.Data.XmlTreeGen.SchemaTree().