Terraria: System.Data.XmlTreeGen.GetSchema
GetSchema()
XmlElement System.Data.XmlTreeGen.GetSchema (string NamespaceURI) inline package
Definition at line 1061 of file XmlTreeGen.cs.
    {
        XmlElement xmlElement = (XmlElement)_namespaces[NamespaceURI];
        if (xmlElement == null)
        {
            xmlElement = _dc.CreateElement("xs", "schema", "http://www.w3.org/2001/XMLSchema");
            WriteSchemaRoot(_dc, xmlElement, NamespaceURI);
            if (!string.IsNullOrEmpty(NamespaceURI))
            {
                string text = "app" + Convert.ToString(++_prefixCount, CultureInfo.InvariantCulture);
                _sRoot.SetAttribute("xmlns:" + text, NamespaceURI);
                xmlElement.SetAttribute("xmlns:" + text, NamespaceURI);
                _prefixes[NamespaceURI] = text;
            }
            _namespaces[NamespaceURI] = xmlElement;
        }
        return xmlElement;
    }
References System.Data.XmlTreeGen._dc, System.Data.XmlTreeGen._namespaces, System.Data.XmlTreeGen._prefixCount, System.Data.XmlTreeGen._prefixes, System.Data.XmlTreeGen._sRoot, System.Xml.XmlDocument.CreateElement(), System.Xml.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlElement.SetAttribute(), System.text, System.Convert.ToString(), and System.Data.XmlTreeGen.WriteSchemaRoot().
Referenced by System.Data.XmlTreeGen.AppendChildWithoutRef(), System.Data.XmlTreeGen.HandleColumn(), System.Data.XmlTreeGen.HandleColumnType(), and System.Data.XmlTreeGen.HandleTable().