Terraria: System.Data.XmlTreeGen.HandleColumn
HandleColumn()
XmlElement System.Data.XmlTreeGen.HandleColumn (DataColumn col, XmlDocument dc, XmlElement schema, bool fWriteOrdinal) inline package
Definition at line 1240 of file XmlTreeGen.cs.
    {
        string localName = ((col.ColumnMapping != MappingType.Element) ? "attribute" : "element");
        XmlElement xmlElement = dc.CreateElement("xs", localName, "http://www.w3.org/2001/XMLSchema");
        xmlElement.SetAttribute("name", col.EncodedColumnName);
        if (col.Namespace.Length == 0)
        {
            DataTable table = col.Table;
            string text = FindTargetNamespace(table);
            if (col.Namespace != text)
            {
                xmlElement.SetAttribute("form", "unqualified");
            }
        }
        if (col.GetType() != typeof(DataColumn))
        {
            AddXdoProperties(col, xmlElement, dc);
        }
        else
        {
            AddColumnProperties(col, xmlElement);
        }
        AddExtendedProperties(col._extendedProperties, xmlElement);
        HandleColumnType(col, dc, xmlElement, schema);
        if (col.ColumnMapping == MappingType.Hidden)
        {
            if (!col.AllowDBNull)
            {
                xmlElement.SetAttribute("AllowDBNull", "urn:schemas-microsoft-com:xml-msdata", "false");
            }
            if (!col.DefaultValueIsNull)
            {
                if (col.DataType == typeof(bool))
                {
                    xmlElement.SetAttribute("DefaultValue", "urn:schemas-microsoft-com:xml-msdata", ((bool)col.DefaultValue) ? "true" : "false");
                }
                else
                {
                    ValidateColumnMapping(col.DataType);
                    xmlElement.SetAttribute("DefaultValue", "urn:schemas-microsoft-com:xml-msdata", col.ConvertObjectToXml(col.DefaultValue));
                }
            }
        }
        if (!col.DefaultValueIsNull && col.ColumnMapping != MappingType.Hidden)
        {
            ValidateColumnMapping(col.DataType);
            if (col.ColumnMapping == MappingType.Attribute && !col.AllowDBNull)
            {
                if (col.DataType == typeof(bool))
                {
                    xmlElement.SetAttribute("DefaultValue", "urn:schemas-microsoft-com:xml-msdata", ((bool)col.DefaultValue) ? "true" : "false");
                }
                else
                {
                    xmlElement.SetAttribute("DefaultValue", "urn:schemas-microsoft-com:xml-msdata", col.ConvertObjectToXml(col.DefaultValue));
                }
            }
            else if (col.DataType == typeof(bool))
            {
                xmlElement.SetAttribute("default", ((bool)col.DefaultValue) ? "true" : "false");
            }
            else if (!col.IsCustomType)
            {
                xmlElement.SetAttribute("default", col.ConvertObjectToXml(col.DefaultValue));
            }
        }
        if (_schFormat == SchemaFormat.Remoting)
        {
            xmlElement.SetAttribute("targetNamespace", "urn:schemas-microsoft-com:xml-msdata", col.Namespace);
        }
        else if (col.Namespace != (col.Table.TypeName.IsEmpty ? col.Table.Namespace : col.Table.TypeName.Namespace) && col.Namespace.Length != 0)
        {
            XmlElement schema2 = GetSchema(col.Namespace);
            if (FindTypeNode(schema2, col.EncodedColumnName) == null)
            {
                schema2.AppendChild(xmlElement);
            }
            xmlElement = _dc.CreateElement("xs", localName, "http://www.w3.org/2001/XMLSchema");
            xmlElement.SetAttribute("ref", _prefixes[col.Namespace]?.ToString() + ":" + col.EncodedColumnName);
            if (col.Table.Namespace != _ds.Namespace)
            {
                GetSchema(col.Table.Namespace);
            }
        }
        int num = ((!col.AllowDBNull) ? 1 : 0);
        if (col.ColumnMapping == MappingType.Attribute && num != 0)
        {
            xmlElement.SetAttribute("use", "required");
        }
        if (col.ColumnMapping == MappingType.Hidden)
        {
            xmlElement.SetAttribute("use", "prohibited");
        }
        else if (col.ColumnMapping != MappingType.Attribute && num != 1)
        {
            xmlElement.SetAttribute("minOccurs", num.ToString(CultureInfo.InvariantCulture));
        }
        if (col.ColumnMapping == MappingType.Element && fWriteOrdinal)
        {
            xmlElement.SetAttribute("Ordinal", "urn:schemas-microsoft-com:xml-msdata", col.Ordinal.ToString(CultureInfo.InvariantCulture));
        }
        return xmlElement;
    }
References System.Data.XmlTreeGen._dc, System.Data.XmlTreeGen._ds, System.Data.XmlTreeGen._prefixes, System.Data.XmlTreeGen._schFormat, System.Data.XmlTreeGen.AddColumnProperties(), System.Data.XmlTreeGen.AddExtendedProperties(), System.Data.XmlTreeGen.AddXdoProperties(), System.Xml.XmlDocument.CreateElement(), System.Xml.Dictionary, System.Data.XmlTreeGen.FindTargetNamespace(), System.Data.XmlTreeGen.FindTypeNode(), System.Data.XmlTreeGen.GetSchema(), System.Data.XmlTreeGen.HandleColumnType(), System.Globalization.CultureInfo.InvariantCulture, System.Data.DataSet.Namespace, System.Xml.XmlElement.SetAttribute(), System.text, and System.Data.XmlTreeGen.ValidateColumnMapping().
Referenced by System.Data.XmlTreeGen.HandleTable().