Terraria: System.Data.XmlTreeGen.AddXdoProperty
AddXdoProperty()
void System.Data.XmlTreeGen.AddXdoProperty (PropertyDescriptor pd, object instance, XmlElement root, XmlDocument xd) inline package
Definition at line 100 of file XmlTreeGen.cs.
    {
        Type propertyType = pd.PropertyType;
        bool flag = false;
        DataColumn dataColumn = null;
        bool flag2 = false;
        bool flag3 = false;
        if (instance is DataColumn)
        {
            dataColumn = (DataColumn)instance;
            flag = true;
            flag2 = dataColumn.IsSqlType;
            flag3 = dataColumn.ImplementsINullable;
        }
        if ((!flag3 && propertyType != typeof(string) && propertyType != typeof(bool) && propertyType != typeof(Type) && propertyType != typeof(object) && propertyType != typeof(CultureInfo) && propertyType != typeof(long) && propertyType != typeof(int)) || ((!pd.ShouldSerializeValue(instance) || !ContainsDesignerSerializationVisibleAttribute(pd)) && !flag2))
        {
            return;
        }
        object value = pd.GetValue(instance);
        if (value is InternalDataCollectionBase || value is PropertyCollection || string.Equals(pd.Name, "Namespace", StringComparison.Ordinal) || string.Equals(pd.Name, "PrimaryKey", StringComparison.Ordinal) || string.Equals(pd.Name, "ColumnName", StringComparison.Ordinal) || string.Equals(pd.Name, "DefaultValue", StringComparison.Ordinal) || string.Equals(pd.Name, "TableName", StringComparison.Ordinal) || string.Equals(pd.Name, "DataSetName", StringComparison.Ordinal) || string.Equals(pd.Name, "AllowDBNull", StringComparison.Ordinal) || string.Equals(pd.Name, "Unique", StringComparison.Ordinal) || string.Equals(pd.Name, "NestedInDataSet", StringComparison.Ordinal) || string.Equals(pd.Name, "Locale", StringComparison.Ordinal) || string.Equals(pd.Name, "CaseSensitive", StringComparison.Ordinal) || string.Equals(pd.Name, "RemotingFormat", StringComparison.Ordinal))
        {
            return;
        }
        if (flag)
        {
            if (string.Equals(pd.Name, "DataType", StringComparison.Ordinal))
            {
                string text = XmlDataTypeName(dataColumn.DataType);
                if (flag2 || dataColumn.DataType == typeof(BigInteger))
                {
                    root.SetAttribute("DataType", "urn:schemas-microsoft-com:xml-msdata", dataColumn.DataType.FullName);
                }
                else if (text.Length == 0 || flag3 || (text == "anyType" && dataColumn.XmlDataType != "anyType") || dataColumn.DataType == typeof(DateTimeOffset))
                {
                    SetMSDataAttribute(root, dataColumn.DataType);
                }
                return;
            }
            if (string.Equals(pd.Name, "Attribute", StringComparison.Ordinal))
            {
                return;
            }
        }
        string value2 = pd.Converter.ConvertToString(value);
        root.SetAttribute(pd.Name, "urn:schemas-microsoft-com:xml-msdata", value2);
    }
References System.Data.XmlTreeGen.ContainsDesignerSerializationVisibleAttribute(), System.Xml.Dictionary, System.Xml.XmlElement.SetAttribute(), System.Data.XmlTreeGen.SetMSDataAttribute(), System.text, System.value, and System.Data.XmlTreeGen.XmlDataTypeName().
Referenced by System.Data.XmlTreeGen.AddXdoProperties().