Terraria: System.Data.XmlTreeGen.GenerateConstraintNames
GenerateConstraintNames() [3/3]
void System.Data.XmlTreeGen.GenerateConstraintNames (DataTable table, bool fromTable) inline private
Definition at line 247 of file XmlTreeGen.cs.
    {
        StringBuilder stringBuilder = null;
        foreach (Constraint constraint in table.Constraints)
        {
            if (fromTable && constraint is ForeignKeyConstraint && !_tables.Contains(((ForeignKeyConstraint)constraint).RelatedTable))
            {
                continue;
            }
            int num = 0;
            string text = constraint.ConstraintName;
            while (_constraintNames.Contains(text))
            {
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder();
                }
                stringBuilder.Append(table.TableName).Append('_').Append(constraint.ConstraintName);
                if (0 < num)
                {
                    stringBuilder.Append('_').Append(num);
                }
                num++;
                text = stringBuilder.ToString();
                stringBuilder.Length = 0;
            }
            _constraintNames.Add(text);
            constraint.SchemaName = text;
        }
    }
References System.Data.XmlTreeGen._constraintNames, System.Data.XmlTreeGen._tables, System.Collections.ArrayList.Add(), System.Data.Constraint.ConstraintName, System.Collections.ArrayList.Contains(), System.Xml.Dictionary, and System.text.
Referenced by System.Data.XmlTreeGen.GenerateConstraintNames(), System.Data.XmlTreeGen.GenerateConstraintNames(), System.Data.XmlTreeGen.SchemaTree(), and System.Data.XmlTreeGen.SchemaTree().