Terraria: System.Data.XmlTreeGen.SetPath
SetPath()
void System.Data.XmlTreeGen.SetPath (XmlWriter xw) inline package
Definition at line 921 of file XmlTreeGen.cs.
    {
        FileStream fileStream = null;
        fileStream = ((xw is DataTextWriter dataTextWriter) ? (dataTextWriter.BaseStream as FileStream) : null);
        if (fileStream == null)
        {
            if (!(xw is XmlTextWriter xmlTextWriter))
            {
                return;
            }
            fileStream = xmlTextWriter.BaseStream as FileStream;
            if (fileStream == null)
            {
                return;
            }
        }
        _filePath = Path.GetDirectoryName(fileStream.Name);
        _fileName = Path.GetFileNameWithoutExtension(fileStream.Name);
        _fileExt = Path.GetExtension(fileStream.Name);
        if (!string.IsNullOrEmpty(_filePath))
        {
            _filePath += "\\";
        }
    }
References System.Data.XmlTreeGen._fileExt, System.Data.XmlTreeGen._fileName, System.Data.XmlTreeGen._filePath, System.Xml.Dictionary, System.IO.Path.GetDirectoryName(), System.IO.Path.GetExtension(), and System.IO.Path.GetFileNameWithoutExtension().
Referenced by System.Data.XmlTreeGen.Save(), and System.Data.XmlTreeGen.Save().