Terraria: System.Data.XmlTreeGen.HandleTable
HandleTable() [2/2]
XmlElement System.Data.XmlTreeGen.HandleTable (DataTable table, XmlDocument dc, XmlElement schema, bool genNested) inline package
Definition at line 1540 of file XmlTreeGen.cs.
    {
        XmlElement xmlElement = dc.CreateElement("xs", "element", "http://www.w3.org/2001/XMLSchema");
        bool flag = false;
        bool flag2 = false;
        if ((table.DataSet == null || (_ds != null && table.Namespace != _ds.Namespace)) && _schFormat == SchemaFormat.Remoting)
        {
            xmlElement.SetAttribute("targetNamespace", "urn:schemas-microsoft-com:xml-msdata", table.Namespace);
        }
        xmlElement.SetAttribute("name", table.EncodedTableName);
        if (table.Namespace.Length == 0)
        {
            DataTable dataTable = table;
            string text = dataTable.Namespace;
            while (string.IsNullOrEmpty(text))
            {
                DataRelation[] nestedParentRelations = dataTable.NestedParentRelations;
                if (nestedParentRelations.Length == 0)
                {
                    text = ((_ds != null) ? _ds.Namespace : "");
                    break;
                }
                int num = -1;
                for (int i = 0; i < nestedParentRelations.Length; i++)
                {
                    if (nestedParentRelations[i].ParentTable != dataTable)
                    {
                        num = i;
                        break;
                    }
                }
                if (num == -1)
                {
                    break;
                }
                dataTable = nestedParentRelations[num].ParentTable;
                text = dataTable.Namespace;
            }
            if (table.Namespace != text)
            {
                xmlElement.SetAttribute("form", "unqualified");
                flag2 = true;
            }
        }
        if (table.ShouldSerializeCaseSensitive())
        {
            xmlElement.SetAttribute("CaseSensitive", "urn:schemas-microsoft-com:xml-msdata", table.CaseSensitive.ToString());
        }
        if (table.ShouldSerializeLocale())
        {
            xmlElement.SetAttribute("Locale", "urn:schemas-microsoft-com:xml-msdata", table.Locale.ToString());
        }
        AddXdoProperties(table, xmlElement, dc);
        DataColumnCollection columns = table.Columns;
        int count = columns.Count;
        int num2 = 0;
        if (count == 1 || count == 2)
        {
            for (int j = 0; j < count; j++)
            {
                DataColumn dataColumn = columns[j];
                if (dataColumn.ColumnMapping == MappingType.Hidden)
                {
                    DataRelationCollection childRelations = table.ChildRelations;
                    for (int k = 0; k < childRelations.Count; k++)
                    {
                        if (childRelations[k].Nested && childRelations[k].ParentKey.ColumnsReference.Length == 1 && childRelations[k].ParentKey.ColumnsReference[0] == dataColumn)
{
                            num2++;
                        }
                    }
                }
                if (dataColumn.ColumnMapping == MappingType.Element)
                {
                    num2++;
                }
            }
        }
        if (table._repeatableElement && num2 == 1)
        {
            DataColumn dataColumn2 = table.Columns[0];
            string text2 = XmlDataTypeName(dataColumn2.DataType);
            if (text2 == null || text2.Length == 0)
            {
                text2 = "anyType";
            }
            xmlElement.SetAttribute("type", XSDSchema.QualifiedName(text2));
            return xmlElement;
        }
        XmlElement xmlElement2 = dc.CreateElement("xs", "complexType", "http://www.w3.org/2001/XMLSchema");
        if (!table.TypeName.IsEmpty && _schFormat != SchemaFormat.Remoting)
        {
            XmlElement xmlElement3 = GetSchema(table.TypeName.Namespace);
            if (string.IsNullOrEmpty(table.TypeName.Namespace))
            {
                xmlElement3 = ((_ds != null) ? (flag2 ? GetSchema(_ds.Namespace) : GetSchema(table.Namespace)) : GetSchema(table.Namespace));
            }
            if (FindTypeNode(xmlElement3, table.TypeName.Name) == null)
            {
                xmlElement3.AppendChild(xmlElement2);
            }
            xmlElement2.SetAttribute("name", table.TypeName.Name);
        }
        else
        {
            xmlElement.AppendChild(xmlElement2);
        }
        if (!table.TypeName.IsEmpty && _schFormat != SchemaFormat.Remoting)
        {
            xmlElement.SetAttribute("type", NewDiffgramGen.QualifiedName((string)_prefixes[table.TypeName.Namespace], table.TypeName.Name));
        }
        XmlElement xmlElement4 = null;
        DataColumn xmlText = table.XmlText;
        if (xmlText != null)
        {
            XmlElement xmlElement5 = dc.CreateElement("xs", "simpleContent", "http://www.w3.org/2001/XMLSchema");
            if (xmlText.GetType() != typeof(DataColumn))
            {
                AddXdoProperties(xmlText, xmlElement5, dc);
            }
            else
            {
                AddColumnProperties(xmlText, xmlElement5);
            }
            AddExtendedProperties(xmlText._extendedProperties, xmlElement5);
            if (xmlText.AllowDBNull)
            {
                xmlElement.SetAttribute("nillable", string.Empty, "true");
            }
            if (!xmlText.DefaultValueIsNull)
            {
                ValidateColumnMapping(xmlText.DataType);
                xmlElement5.SetAttribute("DefaultValue", "urn:schemas-microsoft-com:xml-msdata", xmlText.ConvertObjectToXml(xmlText.DefaultValue));
            }
            xmlElement5.SetAttribute("ColumnName", "urn:schemas-microsoft-com:xml-msdata", xmlText.ColumnName);
            xmlElement5.SetAttribute("Ordinal", "urn:schemas-microsoft-com:xml-msdata", xmlText.Ordinal.ToString(CultureInfo.InvariantCulture));
            xmlElement2.AppendChild(xmlElement5);
            XmlElement xmlElement6 = dc.CreateElement("xs", "extension", "http://www.w3.org/2001/XMLSchema");
            xmlElement5.AppendChild(xmlElement6);
            HandleColumnType(xmlText, dc, xmlElement6, schema);
            xmlElement2 = xmlElement6;
        }
        xmlElement4 = dc.CreateElement("xs", "sequence", "http://www.w3.org/2001/XMLSchema");
        xmlElement2.AppendChild(xmlElement4);
        flag = HasMixedColumns(table);
        for (int l = 0; l < count; l++)
        {
            DataColumn dataColumn3 = columns[l];
            if (dataColumn3.ColumnMapping != MappingType.SimpleContent && (dataColumn3.ColumnMapping == MappingType.Attribute || dataColumn3.ColumnMapping == MappingType.Element || dataColumn3.ColumnMapping == MappingType.Hidden) && !IsAutoGenerated(dataColumn3))
            {
                bool flag3 = dataColumn3.ColumnMapping != MappingType.Element;
                XmlElement newChild = HandleColumn(dataColumn3, dc, schema, flag);
                XmlElement xmlElement7 = (flag3 ? xmlElement2 : xmlElement4);
                xmlElement7.AppendChild(newChild);
            }
        }
        if (table.XmlText == null && genNested)
        {
            DataRelationCollection childRelations2 = table.ChildRelations;
            for (int m = 0; m < childRelations2.Count; m++)
            {
                if (!childRelations2[m].Nested)
                {
                    continue;
                }
                DataTable childTable = childRelations2[m].ChildTable;
                XmlElement xmlElement8;
                if (childTable == table)
                {
                    xmlElement8 = dc.CreateElement("xs", "element", "http://www.w3.org/2001/XMLSchema");
                    xmlElement8.SetAttribute("ref", table.EncodedTableName);
                }
                else if (childTable.NestedParentsCount > 1)
                {
                    xmlElement8 = dc.CreateElement("xs", "element", "http://www.w3.org/2001/XMLSchema");
                    xmlElement8.SetAttribute("ref", childTable.EncodedTableName);
                }
                else
                {
                    xmlElement8 = HandleTable(childTable, dc, schema);
                }
                if (childTable.Namespace == table.Namespace)
                {
                    xmlElement8.SetAttribute("minOccurs", "0");
                    xmlElement8.SetAttribute("maxOccurs", "unbounded");
                }
                if (childTable.Namespace == table.Namespace || childTable.Namespace.Length == 0 || _schFormat == SchemaFormat.Remoting)
                {
                    xmlElement4.AppendChild(xmlElement8);
                }
                else
                {
                    if (childTable.NestedParentsCount <= 1)
                    {
                        GetSchema(childTable.Namespace).AppendChild(xmlElement8);
                    }
                    xmlElement8 = dc.CreateElement("xs", "element", "http://www.w3.org/2001/XMLSchema");
                    xmlElement8.SetAttribute("ref", (string)_prefixes[childTable.Namespace] + ":" + childTable.EncodedTableName);
                    xmlElement4.AppendChild(xmlElement8);
                }
                if (childRelations2[m].ChildKeyConstraint == null)
                {
                    XmlElement xmlElement9 = _dc.CreateElement("xs", "annotation", "http://www.w3.org/2001/XMLSchema");
                    xmlElement8.PrependChild(xmlElement9);
                    XmlElement xmlElement10 = _dc.CreateElement("xs", "appinfo", "http://www.w3.org/2001/XMLSchema");
                    xmlElement9.AppendChild(xmlElement10);
                    xmlElement10.AppendChild(HandleRelation(childRelations2[m], dc));
                }
            }
        }
        if (xmlElement4 != null && !xmlElement4.HasChildNodes)
        {
            xmlElement2.RemoveChild(xmlElement4);
        }
        ConstraintCollection constraints = table.Constraints;
        string text3 = ((_ds == null) ? string.Empty : ((_ds.Namespace.Length != 0) ? "mstns:" : string.Empty));
        if (_schFormat != SchemaFormat.Remoting)
        {
            GetSchema(table.Namespace);
            text3 = ((table.Namespace.Length != 0) ? ((string)_prefixes[table.Namespace] + ":") : string.Empty);
        }
        for (int n = 0; n < constraints.Count; n++)
        {
            XmlElement xmlElement11 = null;
            if (constraints[n] is UniqueConstraint)
            {
                UniqueConstraint uniqueConstraint = (UniqueConstraint)constraints[n];
                if (IsAutoGenerated(uniqueConstraint))
                {
                    continue;
                }
                DataColumn[] columnsReference = uniqueConstraint.Key.ColumnsReference;
                xmlElement11 = dc.CreateElement("xs", "unique", "http://www.w3.org/2001/XMLSchema");
                if (_ds == null || _ds.Tables.InternalIndexOf(table.TableName) == -3)
                {
                    xmlElement11.SetAttribute("TableNamespace", "urn:schemas-microsoft-com:xml-msdata", table.Namespace);
                }
                xmlElement11.SetAttribute("name", XmlConvert.EncodeLocalName(uniqueConstraint.SchemaName));
                if (uniqueConstraint.ConstraintName != uniqueConstraint.SchemaName)
                {
                    xmlElement11.SetAttribute("ConstraintName", "urn:schemas-microsoft-com:xml-msdata", uniqueConstraint.ConstraintName);
                }
                AddExtendedProperties(uniqueConstraint._extendedProperties, xmlElement11);
                XmlElement xmlElement12 = dc.CreateElement("xs", "selector", "http://www.w3.org/2001/XMLSchema");
                xmlElement12.SetAttribute("xpath", ".//" + text3 + table.EncodedTableName);
                xmlElement11.AppendChild(xmlElement12);
                if (uniqueConstraint.IsPrimaryKey)
                {
                    xmlElement11.SetAttribute("PrimaryKey", "urn:schemas-microsoft-com:xml-msdata", "true");
                }
                if (columnsReference.Length != 0)
                {
                    StringBuilder stringBuilder = new StringBuilder();
                    for (int num3 = 0; num3 < columnsReference.Length; num3++)
                    {
                        stringBuilder.Length = 0;
                        if (_schFormat != SchemaFormat.Remoting)
{
                            GetSchema(columnsReference[num3].Namespace);
                            if (!string.IsNullOrEmpty(columnsReference[num3].Namespace))
{
                                stringBuilder.Append(_prefixes[columnsReference[num3].Namespace]).Append(':');
                            }
                            stringBuilder.Append(columnsReference[num3].EncodedColumnName);
                        }
                        else
{
                            stringBuilder.Append(text3).Append(columnsReference[num3].EncodedColumnName);
                        }
                        if (columnsReference[num3].ColumnMapping == MappingType.Attribute || columnsReference[num3].ColumnMapping == MappingType.Hidden)
{
                            stringBuilder.Insert(0, '@');
                        }
                        XmlElement xmlElement13 = dc.CreateElement("xs", "field", "http://www.w3.org/2001/XMLSchema");
                        xmlElement13.SetAttribute("xpath", stringBuilder.ToString());
                        xmlElement11.AppendChild(xmlElement13);
                    }
                }
                _dsElement.InsertBefore(xmlElement11, _constraintSeparator);
            }
            else
            {
                if (!(constraints[n] is ForeignKeyConstraint && genNested))
                {
                    continue;
                }
                ForeignKeyConstraint foreignKeyConstraint = (ForeignKeyConstraint)constraints[n];
                if ((_tables.Count > 0 && (!_tables.Contains(foreignKeyConstraint.RelatedTable) || !_tables.Contains(foreignKeyConstraint.Table))) || IsAutoGenerated(foreignKeyConstraint))
                {
                    continue;
                }
                DataRelation dataRelation = foreignKeyConstraint.FindParentRelation();
                DataColumn[] columnsReference = foreignKeyConstraint.RelatedColumnsReference;
                UniqueConstraint uniqueConstraint2 = (UniqueConstraint)foreignKeyConstraint.RelatedTable.Constraints.FindConstraint(new UniqueConstraint("TEMP", columnsReference));
                XmlElement xmlElement12;
                if (uniqueConstraint2 == null)
                {
                    xmlElement11 = dc.CreateElement("xs", "key", "http://www.w3.org/2001/XMLSchema");
                    xmlElement11.SetAttribute("name", XmlConvert.EncodeLocalName(foreignKeyConstraint.SchemaName));
                    if (_ds == null || _ds.Tables.InternalIndexOf(table.TableName) == -3)
                    {
                        xmlElement11.SetAttribute("TableNamespace", "urn:schemas-microsoft-com:xml-msdata", table.Namespace);
                    }
                    xmlElement12 = dc.CreateElement("xs", "selector", "http://www.w3.org/2001/XMLSchema");
                    xmlElement12.SetAttribute("xpath", ".//" + text3 + foreignKeyConstraint.RelatedTable.EncodedTableName);
                    xmlElement11.AppendChild(xmlElement12);
                    if (columnsReference.Length != 0)
                    {
                        StringBuilder stringBuilder2 = new StringBuilder();
                        for (int num4 = 0; num4 < columnsReference.Length; num4++)
{
                            stringBuilder2.Length = 0;
                            if (_schFormat != SchemaFormat.Remoting)
{
                                GetSchema(columnsReference[num4].Namespace);
                                if (!string.IsNullOrEmpty(columnsReference[num4].Namespace))
{
                                    stringBuilder2.Append(_prefixes[columnsReference[num4].Namespace]).Append(':');
                                }
                                stringBuilder2.Append(columnsReference[num4].EncodedColumnName);
                            }
                            else
{
                                stringBuilder2.Append(text3).Append(columnsReference[num4].EncodedColumnName);
                            }
                            if (columnsReference[num4].ColumnMapping == MappingType.Attribute || columnsReference[num4].ColumnMapping == MappingType.Hidden)
{
                                stringBuilder2.Insert(0, '@');
                            }
                            XmlElement xmlElement13 = dc.CreateElement("xs", "field", "http://www.w3.org/2001/XMLSchema");
                            xmlElement13.SetAttribute("xpath", stringBuilder2.ToString());
                            xmlElement11.AppendChild(xmlElement13);
                        }
                    }
                    _dsElement.InsertBefore(xmlElement11, _constraintSeparator);
                }
                xmlElement11 = dc.CreateElement("xs", "keyref", "http://www.w3.org/2001/XMLSchema");
                xmlElement11.SetAttribute("name", XmlConvert.EncodeLocalName(foreignKeyConstraint.SchemaName));
                if (_ds == null || _ds.Tables.InternalIndexOf(foreignKeyConstraint.RelatedTable.TableName) == -3)
                {
                    xmlElement11.SetAttribute("TableNamespace", "urn:schemas-microsoft-com:xml-msdata", foreignKeyConstraint.Table.Namespace);
                }
                if (uniqueConstraint2 == null)
                {
                    xmlElement11.SetAttribute("refer", XmlConvert.EncodeLocalName(foreignKeyConstraint.SchemaName));
                }
                else
                {
                    xmlElement11.SetAttribute("refer", XmlConvert.EncodeLocalName(uniqueConstraint2.SchemaName));
                }
                AddExtendedProperties(foreignKeyConstraint._extendedProperties, xmlElement11, typeof(ForeignKeyConstraint));
                if (foreignKeyConstraint.ConstraintName != foreignKeyConstraint.SchemaName)
                {
                    xmlElement11.SetAttribute("ConstraintName", "urn:schemas-microsoft-com:xml-msdata", foreignKeyConstraint.ConstraintName);
                }
                if (dataRelation == null)
                {
                    xmlElement11.SetAttribute("ConstraintOnly", "urn:schemas-microsoft-com:xml-msdata", "true");
                }
                else
                {
                    if (dataRelation.Nested)
                    {
                        xmlElement11.SetAttribute("IsNested", "urn:schemas-microsoft-com:xml-msdata", "true");
                    }
                    AddExtendedProperties(dataRelation._extendedProperties, xmlElement11, typeof(DataRelation));
                    if (foreignKeyConstraint.ConstraintName != dataRelation.RelationName)
                    {
                        xmlElement11.SetAttribute("RelationName", "urn:schemas-microsoft-com:xml-msdata", XmlConvert.EncodeLocalName(dataRelation.RelationName));
                    }
                }
                xmlElement12 = dc.CreateElement("xs", "selector", "http://www.w3.org/2001/XMLSchema");
                xmlElement12.SetAttribute("xpath", ".//" + text3 + table.EncodedTableName);
                xmlElement11.AppendChild(xmlElement12);
                if (foreignKeyConstraint.AcceptRejectRule != 0)
                {
                    xmlElement11.SetAttribute("AcceptRejectRule", "urn:schemas-microsoft-com:xml-msdata", TranslateAcceptRejectRule(foreignKeyConstraint.AcceptRejectRule));
                }
                if (foreignKeyConstraint.UpdateRule != Rule.Cascade)
                {
                    xmlElement11.SetAttribute("UpdateRule", "urn:schemas-microsoft-com:xml-msdata", TranslateRule(foreignKeyConstraint.UpdateRule));
                }
                if (foreignKeyConstraint.DeleteRule != Rule.Cascade)
                {
                    xmlElement11.SetAttribute("DeleteRule", "urn:schemas-microsoft-com:xml-msdata", TranslateRule(foreignKeyConstraint.DeleteRule));
                }
                columnsReference = foreignKeyConstraint.Columns;
                if (columnsReference.Length != 0)
                {
                    StringBuilder stringBuilder3 = new StringBuilder();
                    for (int num5 = 0; num5 < columnsReference.Length; num5++)
                    {
                        stringBuilder3.Length = 0;
                        if (_schFormat != SchemaFormat.Remoting)
{
                            GetSchema(columnsReference[num5].Namespace);
                            if (!string.IsNullOrEmpty(columnsReference[num5].Namespace))
{
                                stringBuilder3.Append(_prefixes[columnsReference[num5].Namespace]).Append(':');
                            }
                            stringBuilder3.Append(columnsReference[num5].EncodedColumnName);
                        }
                        else
{
                            stringBuilder3.Append(text3).Append(columnsReference[num5].EncodedColumnName);
                        }
                        if (columnsReference[num5].ColumnMapping == MappingType.Attribute || columnsReference[num5].ColumnMapping == MappingType.Hidden)
{
                            stringBuilder3.Insert(0, '@');
                        }
                        XmlElement xmlElement13 = dc.CreateElement("xs", "field", "http://www.w3.org/2001/XMLSchema");
                        xmlElement13.SetAttribute("xpath", stringBuilder3.ToString());
                        xmlElement11.AppendChild(xmlElement13);
                    }
                }
                _dsElement.InsertAfter(xmlElement11, _constraintSeparator);
            }
        }
        AddExtendedProperties(table._extendedProperties, xmlElement);
        return xmlElement;
    }
References System.Data.XmlTreeGen._constraintSeparator, System.Data.XmlTreeGen._dc, System.Data.XmlTreeGen._ds, System.Data.XmlTreeGen._dsElement, System.Data.DataTable._extendedProperties, System.Data.XmlTreeGen._prefixes, System.Data.DataTable._repeatableElement, System.Data.XmlTreeGen._schFormat, System.Data.XmlTreeGen._tables, System.Data.XmlTreeGen.AddColumnProperties(), System.Data.XmlTreeGen.AddExtendedProperties(), System.Data.XmlTreeGen.AddXdoProperties(), System.Xml.XmlNode.AppendChild(), System.Data.DataTable.CaseSensitive, System.Data.DataTable.ChildRelations, System.Data.DataTable.Columns, System.Data.DataTable.Constraints, System.Collections.ArrayList.Contains(), System.Data.InternalDataCollectionBase.Count, System.count, System.Collections.ArrayList.Count, System.Xml.XmlDocument.CreateElement(), System.Data.DataTable.DataSet, System.Xml.Dictionary, System.Data.DataTable.EncodedTableName, System.Xml.XmlConvert.EncodeLocalName(), System.Data.XmlTreeGen.FindTypeNode(), System.Data.XmlTreeGen.GetSchema(), System.Data.XmlTreeGen.HandleColumn(), System.Data.XmlTreeGen.HandleColumnType(), System.Data.XmlTreeGen.HandleRelation(), System.Data.XmlTreeGen.HandleTable(), System.Data.XmlTreeGen.HasMixedColumns(), System.Xml.XmlNode.InsertAfter(), System.Xml.XmlNode.InsertBefore(), System.Data.DataTableCollection.InternalIndexOf(), System.Globalization.CultureInfo.InvariantCulture, System.Data.XmlTreeGen.IsAutoGenerated(), System.Xml.XmlQualifiedName.IsEmpty, System.Data.DataTable.Locale, System.Xml.XmlQualifiedName.Name, System.Data.DataSet.Namespace, System.Data.DataTable.Namespace, System.Xml.XmlQualifiedName.Namespace, System.Xml.XmlNode.PrependChild(), System.Data.XSDSchema.QualifiedName(), System.Data.NewDiffgramGen.QualifiedName(), System.Xml.XmlNode.RemoveChild(), System.Xml.XmlElement.SetAttribute(), System.Data.DataTable.ShouldSerializeCaseSensitive(), System.Data.DataTable.ShouldSerializeLocale(), System.Data.DataTable.TableName, System.Data.DataSet.Tables, System.text, System.Globalization.CultureInfo.ToString(), System.Data.XmlTreeGen.TranslateAcceptRejectRule(), System.Data.XmlTreeGen.TranslateRule(), System.Data.DataTable.TypeName, System.Data.XmlTreeGen.ValidateColumnMapping(), System.Data.XmlTreeGen.XmlDataTypeName(), and System.Data.DataTable.XmlText.