Terraria: System.Data.XmlTreeGen.WriteSchemaRoot
WriteSchemaRoot()
void System.Data.XmlTreeGen.WriteSchemaRoot (XmlDocument xd, XmlElement rootSchema, string targetNamespace) inline package
Definition at line 334 of file XmlTreeGen.cs.
    {
        if (!string.IsNullOrEmpty(targetNamespace))
        {
            rootSchema.SetAttribute("targetNamespace", targetNamespace);
            rootSchema.SetAttribute("xmlns:mstns", targetNamespace);
        }
        rootSchema.SetAttribute("xmlns", targetNamespace);
        rootSchema.SetAttribute("xmlns:xs", "http://www.w3.org/2001/XMLSchema");
        rootSchema.SetAttribute("xmlns:msdata", "urn:schemas-microsoft-com:xml-msdata");
        if (_ds != null && HaveExtendedProperties(_ds))
        {
            rootSchema.SetAttribute("xmlns:msprop", "urn:schemas-microsoft-com:xml-msprop");
        }
        if (!string.IsNullOrEmpty(targetNamespace))
        {
            rootSchema.SetAttribute("attributeFormDefault", "qualified");
            rootSchema.SetAttribute("elementFormDefault", "qualified");
        }
    }
References System.Data.XmlTreeGen._ds, System.Xml.Dictionary, and System.Data.XmlTreeGen.HaveExtendedProperties().
Referenced by System.Data.XmlTreeGen.GetSchema(), System.Data.XmlTreeGen.SchemaTree(), and System.Data.XmlTreeGen.SchemaTree().