Terraria: GolfHelper.IsPlayerHoldingClub
IsPlayerHoldingClub()
static bool GolfHelper.IsPlayerHoldingClub (Player player) inline static
     {
         if (player == null || player.HeldItem == null)
         {
             return false;
         }
         int type = player.HeldItem.type;
         if (type == 4039 || (uint)(type - 4092) <= 2u || (uint)(type - 4587) <= 11u)
         {
             return true;
         }
         return false;
     }
References Player.HeldItem, and Item.type.
Referenced by PlayerDrawSet.BoringSetup(), Main.DrawProjDirect(), and Player.ItemCheck().