Terraria: System.Xml.Xsl.Runtime.DescendantIterator.Create
Create()
void System.Xml.Xsl.Runtime.DescendantIterator.Create (XPathNavigator input, XmlNavigatorFilter filter, bool orSelf) inline
Definition at line 19 of file DescendantIterator.cs.
    {
        _navCurrent = XmlQueryRuntime.SyncToNavigator(_navCurrent, input);
        _filter = filter;
        if (input.NodeType == XPathNodeType.Root)
        {
            _navEnd = null;
        }
        else
        {
            _navEnd = XmlQueryRuntime.SyncToNavigator(_navEnd, input);
            _navEnd.MoveToNonDescendant();
        }
        _hasFirst = orSelf && !_filter.IsFiltered(_navCurrent);
    }
References System.Xml.Xsl.Runtime.DescendantIterator._filter, System.Xml.Xsl.Runtime.DescendantIterator._hasFirst, System.Xml.Xsl.Runtime.DescendantIterator._navCurrent, System.Xml.Xsl.Runtime.DescendantIterator._navEnd, System.Xml.Dictionary, System.input, System.Xml.Xsl.Runtime.XmlNavigatorFilter.IsFiltered(), System.Xml.XPath.XPathNavigator.MoveToNonDescendant(), and System.Xml.Xsl.Runtime.XmlQueryRuntime.SyncToNavigator().