Terraria: Microsoft.Xna.Framework.Gjk.AddSupportPoint
AddSupportPoint()
bool Microsoft.Xna.Framework.Gjk.AddSupportPoint (ref Vector3 newPoint) inline
Definition at line 67 of file Gjk.cs.
    {
        int num = (BitsToIndices[simplexBits ^ 0xF] & 7) - 1;
        ref Vector3 reference = ref y[num];
        reference = newPoint;
        yLengthSq[num] = newPoint.LengthSquared();
        for (int num2 = BitsToIndices[simplexBits]; num2 != 0; num2 >>= 3)
        {
            int num3 = (num2 & 7) - 1;
            Vector3 vector = y[num3] - newPoint;
            edges[num3][num] = vector;
            ref Vector3 reference2 = ref edges[num][num3];
            reference2 = -vector;
            edgeLengthSq[num][num3] = (edgeLengthSq[num3][num] = vector.LengthSquared());
        }
        UpdateDeterminant(num);
        return UpdateSimplex(num);
    }
References Microsoft.Xna.Framework.Gjk.BitsToIndices, Microsoft.Xna.Framework.Gjk.edgeLengthSq, Microsoft.Xna.Framework.Gjk.edges, Microsoft.Xna.Framework.Vector3.LengthSquared(), Microsoft.Xna.Framework.Gjk.simplexBits, Microsoft.Xna.Framework.Gjk.UpdateDeterminant(), Microsoft.Xna.Framework.Gjk.UpdateSimplex(), Microsoft.Xna.Framework.Gjk.y, and Microsoft.Xna.Framework.Gjk.yLengthSq.
Referenced by Microsoft.Xna.Framework.BoundingFrustum.Intersects(), Microsoft.Xna.Framework.BoundingFrustum.Intersects(), and Microsoft.Xna.Framework.BoundingFrustum.Intersects().