Terraria: Terraria.Tile.color
color() [1/2]
byte Terraria.Tile.color () inline
Definition at line 555 of file Tile.cs.
    {
        return (byte)(sTileHeader & 0x1Fu);
    }
References Terraria.Tile.sTileHeader.
Referenced by Terraria.WorldBuilding.Actions.SetTileAndWallRainbowPaint.Apply(), Terraria.Player.ApplyPaint(), Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), Terraria.TileColorCache.ApplyToBlock(), Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.Tile.color(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.IO.WorldFile.ConvertIlluminantPaintToNewField(), Terraria.Tile.CopyPaintAndCoating(), Terraria.Map.MapHelper.CreateMapTile(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw(), Terraria.HitTile.DrawFreshAnimations(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Below(), Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Sideways(), Terraria.GameContent.Drawing.TileDrawing.EmitTreeLeaves(), Terraria.WorldGen.FinishDrunkGen(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishRemixWorld(), Terraria.Player.FloorVisuals(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.WorldGen.GrowDungeonTree(), Terraria.WorldGen.GrowPalmTree(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.GameContent.Drawing.TileDrawing.MakeExtraPreparations(), Terraria.WorldGen.NotTheBees(), Terraria.WorldGen.PaintTheClouds(), Terraria.WorldGen.PaintTheDungeon(), Terraria.WorldGen.PaintTheLivingTrees(), Terraria.WorldGen.PaintTheMushrooms(), Terraria.WorldGen.PaintThePurityGrass(), Terraria.WorldGen.PaintThePyramids(), Terraria.WorldGen.PaintTheSand(), Terraria.WorldGen.PaintTheTemple(), Terraria.WorldGen.PaintTheTrees(), Terraria.WorldGen.paintTile(), Terraria.Player.PlaceThing_PaintScrapper_TryScrapping(), Terraria.WorldGen.PlaceTile(), Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldGen.Statue(), Terraria.GameContent.SmartCursorHelper.Step_PaintBrush(), Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper(), and Terraria.Minecart.TrackColors().