Terraria: Terraria.Tile.frameNumber
frameNumber() [1/2]
byte Terraria.Tile.frameNumber () inline
Definition at line 440 of file Tile.cs.
    {
        return (byte)((bTileHeader2 & 0x30) >> 4);
    }
References Terraria.Tile.bTileHeader2.
Referenced by Terraria.WorldGen.CheckTree(), Terraria.WorldGen.CheckTreeWithSettings(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_MinecartTrack(), Terraria.Tile.frameNumber(), Terraria.WorldGen.GrowEpicTree(), Terraria.WorldGen.GrowShroom(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowUndergroundTree(), Terraria.WorldGen.KillTile(), Terraria.Framing.SelfFrame8Way(), and Terraria.WorldGen.TileFrame().