Terraria: Terraria.Tile.CopyPaintAndCoating
CopyPaintAndCoating()
void Terraria.Tile.CopyPaintAndCoating (Tile other) inline
    {
        color(other.color());
        invisibleBlock(other.invisibleBlock());
        fullbrightBlock(other.fullbrightBlock());
    }
References Terraria.Tile.color(), Terraria.Tile.fullbrightBlock(), and Terraria.Tile.invisibleBlock().
Referenced by Terraria.Player.DoBootsEffect_PlaceFlowersOnTile(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowSpike(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().