Terraria: Terraria.Tile.topSlope
topSlope()
bool Terraria.Tile.topSlope () inline
Definition at line 307 of file Tile.cs.
    {
        byte b = slope();
        if (b != 1)
        {
            return b == 2;
        }
        return true;
    }
References Terraria.Tile.slope().
Referenced by Terraria.WorldGen.AddBuriedChest(), Terraria.Projectile.AI_010(), Terraria.WorldGen.AnchorValid(), Terraria.TileObject.CanPlace(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckOnTable1x1(), Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), Terraria.WorldGen.CheckTorch(), Terraria.Collision.HurtTiles(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.WorldGen.meteor(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceSandTrap(), Terraria.Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DelegateMethods.SpreadDirt(), Terraria.WorldGen.TileFrame(), Terraria.WorldGen.TopEdgeCanBeAttachedTo(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().