Terraria: Terraria.Tile.ResetToType
ResetToType()
void Terraria.Tile.ResetToType (ushort type) inline
    {
        liquid = 0;
        sTileHeader = 32;
        bTileHeader = 0;
        bTileHeader2 = 0;
        bTileHeader3 = 0;
        frameX = 0;
        frameY = 0;
        this.type = type;
    }
References Terraria.Tile.bTileHeader, Terraria.Tile.bTileHeader2, Terraria.Tile.bTileHeader3, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.liquid, Terraria.Tile.sTileHeader, and Terraria.Tile.type.
Referenced by Terraria.WorldBuilding.Actions.SwapSolidTile.Apply(), Terraria.WorldBuilding.TileFont.DrawChar(), Terraria.WorldBuilding.TileFont.HLineLabel(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), Terraria.GameContent.Biomes.Desert.PitEntrance.PlaceAt(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine(), Terraria.GameContent.Biomes.GraniteBiome.PlaceGranite(), Terraria.GameContent.Generation.TrackGenerator.PlacePath(), Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab(), and Terraria.WorldBuilding.TileFont.VLineLabel().