Terraria: Terraria.Tile.wallColor
wallColor() [1/2]
byte Terraria.Tile.wallColor () inline
Definition at line 352 of file Tile.cs.
    {
        return (byte)(bTileHeader & 0x1Fu);
    }
References Terraria.Tile.bTileHeader.
Referenced by Terraria.WorldBuilding.Actions.SetTileAndWallRainbowPaint.Apply(), Terraria.Player.ApplyPaint(), Terraria.TileColorCache.ApplyToWall(), Terraria.Tile.ClearWallPaintAndCoating(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.IO.WorldFile.ConvertIlluminantPaintToNewField(), Terraria.Map.MapHelper.CreateMapTile(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.WorldGen.FinishDrunkGen(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishRemixWorld(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Drawing.WallDrawing.GetTileDrawTexture(), Terraria.Tile.isTheSameAs(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.WorldGen.NotTheBees(), Terraria.WorldGen.PaintTheClouds(), Terraria.WorldGen.PaintTheDungeon(), Terraria.WorldGen.PaintTheLivingTrees(), Terraria.WorldGen.PaintTheMushrooms(), Terraria.WorldGen.PaintThePurityGrass(), Terraria.WorldGen.PaintThePyramids(), Terraria.WorldGen.PaintTheSand(), Terraria.WorldGen.PaintTheTemple(), Terraria.WorldGen.paintWall(), Terraria.Player.PlaceThing_PaintScrapper_TryScrapping(), Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.GameContent.SmartCursorHelper.Step_PaintRoller(), Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper(), Terraria.Tile.wallColor(), Terraria.Tile.WallColorAndCoating(), and Terraria.Framing.WallFrame().