Terraria: Terraria.Tile.wire4
wire4() [1/2]
bool Terraria.Tile.wire4 () inline
Definition at line 413 of file Tile.cs.
    {
        return (bTileHeader & 0x80) == 128;
    }
References Terraria.Tile.bTileHeader.
Referenced by Terraria.Tile.Clear(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.WorldGen.countWires(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.MessageBuffer.GetData(), Terraria.WorldGen.HasAnyWireNearby(), Terraria.Wiring.HitWire(), Terraria.Tile.isTheSameAs(), Terraria.WorldGen.KillWire4(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.Wiring.MassWireOperationStep(), Terraria.WorldGen.PlaceWire4(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.GameContent.SmartCursorHelper.Step_Actuators(), Terraria.GameContent.SmartCursorHelper.Step_ColoredWrenches(), Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench(), Terraria.GameContent.SmartCursorHelper.Step_WireCutter(), Terraria.Wiring.TripWire(), and Terraria.Tile.wire4().