Terraria: Terraria.Tile.wallFrameY
wallFrameY() [1/2]
int Terraria.Tile.wallFrameY () inline
    {
        return (bTileHeader3 & 7) * 36;
    }
References Terraria.Tile.bTileHeader3.
Referenced by Terraria.WorldBuilding.Actions.SetTileKeepWall.Apply(), Terraria.Tile.Clear(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.Framing.WallFrame(), and Terraria.Tile.wallFrameY().