Terraria: Terraria.Tile.active
active() [1/2]
bool Terraria.Tile.active () inline
Definition at line 565 of file Tile.cs.
    {
        return (sTileHeader & 0x20) == 32;
    }
References Terraria.Tile.sTileHeader.
Referenced by Terraria.Tile.active(), Terraria.WorldGen.ActiveAndWalkableTile(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap(), Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.AddHellHouses(), Terraria.WorldGen.AddLifeCrystal(), Terraria.WorldGen.AddShadowOrb(), Terraria.GameContent.Biomes.Desert.DesertHive.AddTileVariance(), Terraria.Liquid.AddWater(), Terraria.Player.AdjTiles(), Terraria.Collision.AdvancedTileCollision(), Terraria.NPC.AI_007_FindGoodRestingSpot(), Terraria.NPC.AI_007_TryForcingSitting(), Terraria.Projectile.AI_010(), Terraria.Projectile.AI_016(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_062(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_149_GolfBall(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.Projectile.AI_155_RemoveRope(), Terraria.WorldGen.AllowsSandfall(), Terraria.GameContent.MinecartDiggerHelper.AlreadyLeadsIntoWantedTrack(), Terraria.Collision.AnyCollision(), Terraria.Collision.AnyCollisionWithSpecificTiles(), Terraria.GameContent.Generation.ActionGrass.Apply(), Terraria.GameContent.Generation.ActionVines.Apply(), Terraria.WorldBuilding.Actions.TileScanner.Apply(), Terraria.WorldBuilding.Actions.SetTile.Apply(), Terraria.WorldBuilding.Actions.SetTileKeepWall.Apply(), Terraria.WorldBuilding.Modifiers.OnlyTiles.Apply(), Terraria.WorldBuilding.Modifiers.IsTouching.Apply(), Terraria.WorldBuilding.Modifiers.NotTouching.Apply(), Terraria.WorldBuilding.Modifiers.IsTouchingAir.Apply(), Terraria.WorldBuilding.Modifiers.SkipTiles.Apply(), Terraria.WorldBuilding.Modifiers.IsEmpty.Apply(), Terraria.WorldBuilding.Modifiers.IsSolid.Apply(), Terraria.WorldBuilding.Modifiers.IsNotSolid.Apply(), Terraria.Graphics.Light.TileLightScanner.ApplyHellLight(), Terraria.Graphics.Light.TileLightScanner.ApplySurfaceLight(), Terraria.Player.ApplyTouchDamage(), Terraria.WorldGen.AttemptFossilShattering(), Terraria.WorldGen.AttemptToGeneratePlanteraBulbAt(), Terraria.WorldGen.AttemptToGrowTreeFromSapling(), Terraria.GameContent.Biomes.HiveBiome.BadSpotForHoneyFall(), Terraria.WorldGen.BiomeTileCheck(), Terraria.WorldGen.BlockBelowMakesSandFall(), Terraria.GameContent.PortalHelper.BlockPortals(), Terraria.WorldGen.BottomEdgeCanBeAttachedTo(), Terraria.WorldGen.CactusFrame(), Terraria.GameContent.MinecartDiggerHelper.CanGetPastTile(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Collision.CanHitWithCheck(), Terraria.WorldGen.CanKillTile(), Terraria.Player.CanMoveForwardOnRope(), Terraria.TileObject.CanPlace(), Terraria.GameContent.Biomes.GraniteBiome.CanPlace(), Terraria.WorldBuilding.StructureMap.CanPlace(), Terraria.WorldGen.CanPlaceSink(), Terraria.WorldGen.CanPoundTile(), Terraria.WorldGen.CanUnderwaterPlantGrowHere(), Terraria.DelegateMethods.CastLightOpen(), Terraria.DelegateMethods.CastLightOpen_StopForSolids(), Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Terraria.WorldGen.CaveOpenater(), Terraria.WorldGen.Cavinator(), Terraria.WorldGen.ChasmRunner(), Terraria.WorldGen.ChasmRunnerSideways(), Terraria.WorldGen.Check1x2Top(), Terraria.WorldGen.Check1xX(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check2x2Style(), Terraria.WorldGen.Check2x3Wall(), Terraria.WorldGen.Check2x5(), Terraria.WorldGen.Check2xX(), Terraria.WorldGen.Check3x1(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.Check3x2Wall(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.Check3x3Wall(), Terraria.WorldGen.Check3x4(), Terraria.WorldGen.Check3x5(), Terraria.WorldGen.Check3x6(), Terraria.WorldGen.Check4x2(), Terraria.WorldGen.Check4x3Wall(), Terraria.WorldGen.Check5x4(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.Check6x4Wall(), Terraria.WorldGen.CheckBamboo(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckCactus(), Terraria.WorldGen.CheckCannon(), Terraria.WorldGen.CheckCatTail(), Terraria.WorldGen.CheckChand(), Terraria.WorldGen.CheckChest(), Terraria.WorldGen.CheckDoorClosed(), Terraria.WorldGen.CheckDoorOpen(), Terraria.Player.CheckDrowning(), Terraria.Player.CheckForGoodTeleportationSpot(), Terraria.WorldGen.CheckJunglePlant(), Terraria.ObjectData.TileObjectData.CheckLavaDeath(), Terraria.WorldGen.CheckLilyPad(), Terraria.Wiring.CheckLogicGate(), Terraria.WorldGen.CheckLogicTiles(), Terraria.WorldGen.CheckMan(), Terraria.WorldGen.CheckMB(), Terraria.WorldGen.CheckOasisPlant(), Terraria.WorldGen.CheckOnTable1x1(), Terraria.WorldGen.CheckPalmTree(), Terraria.WorldGen.CheckPile(), Terraria.WorldGen.CheckPot(), Terraria.WorldGen.CheckSign(), Terraria.Player.CheckSpawn_Internal(), Terraria.WorldGen.CheckSpecialTownNPCSpawningConditions(), Terraria.GameContent.SpelunkerProjectileHelper.CheckSpot(), Terraria.DelegateMethods.CheckStopForSolids(), Terraria.WorldGen.CheckSunflower(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTileBreakability(), Terraria.WorldGen.CheckTileFrames(), Terraria.WorldGen.CheckTorch(), Terraria.WorldGen.CheckTree(), Terraria.WorldGen.CheckTreeWithSettings(), Terraria.WorldGen.CheckUnderwaterPlant(), Terraria.WorldBuilding.Conditions.IsTile.CheckValidity(), Terraria.WorldBuilding.Conditions.MysticSnake.CheckValidity(), Terraria.WorldBuilding.Conditions.IsSolid.CheckValidity(), Terraria.ObjectData.TileObjectData.CheckWaterDeath(), Terraria.WorldGen.CheckWeaponsRack(), Terraria.WorldGen.CheckWoman(), Terraria.WorldGen.CheckXmasTree(), Terraria.WorldGen.Chlorophyte(), Terraria.Tile.Clear(), Terraria.Tile.ClearTile(), Terraria.GameContent.Drawing.TileDrawing.ClimbCatTail(), Terraria.WorldGen.CloseDoor(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.IO.WorldFile.ConvertIlluminantPaintToNewField(), Terraria.WorldGen.ConvertSkyIslands(), Terraria.GameContent.MinecartDiggerHelper.CorrectTrackConnections(), Terraria.WorldGen.CountGrowingPlantTiles(), Terraria.WorldGen.CountNearBlocksTypes(), Terraria.StrayMethods.CountSandHorizontally(), Terraria.WorldGen.CountTiles(), Terraria.WorldGen.CountTileTypesInArea(), Terraria.WorldGen.CountTileTypesInWorld(), Terraria.GameContent.Drawing.TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint(), Terraria.GameContent.Drawing.TileDrawing.CrawlToTopOfVineAndAddSpecialPoint(), Terraria.GameContent.Biomes.HiveBiome.CreateBlockedHoneyCube(), Terraria.GameContent.Biomes.HiveBiome.CreateDentForHoneyFall(), Terraria.Projectile.CreateGroundExplosion(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.Projectile.CreateImpactExplosion(), Terraria.Map.MapHelper.CreateMapTile(), Terraria.GameContent.Biomes.HiveBiome.CreateStandForLarva(), Terraria.WorldGen.CrimEnt(), Terraria.WorldGen.CrimPlaceHearts(), Terraria.WorldGen.CrimStart(), Terraria.WorldGen.CrimVein(), Terraria.Player.DamageTileWithShovel(), Terraria.Wiring.DeActive(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.Liquid.DelWater(), Terraria.WorldGen.DesertCloudIsland(), Terraria.WorldGen.DestroyHeart(), Terraria.WorldGen.digTunnel(), Terraria.Player.DoBootsEffect_PlaceFlamesOnTile(), Terraria.Player.DoBootsEffect_PlaceFlowersOnTile(), Terraria.GameContent.AmbientWindSystem.DoesTileAllowWind(), Terraria.WorldGen.DontStarveTryWateringTile(), Terraria.GameContent.Drawing.TileDrawing.Draw(), Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.HitTile.DrawFreshAnimations(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVines(), Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.WorldGen.dropMeteor(), Terraria.Collision.DrownCollision(), Terraria.WorldGen.DungeonEnt(), Terraria.WorldGen.DungeonHalls(), Terraria.WorldGen.DungeonPitTrap(), Terraria.WorldGen.DungeonRoom(), Terraria.WorldGen.DungeonStairs(), Terraria.DelegateMethods.EmitGolfCartDust_StopForSolids(), Terraria.Collision.EmptyTile(), Terraria.WorldGen.EmptyTileCheck(), Terraria.WorldGen.EveryTileFrame(), Terraria.Projectile.ExplodeCrackedTiles(), Terraria.Projectile.ExplodeTiles(), Terraria.Player.FigureOutWhatToPlace(), Terraria.GameContent.Biomes.TerrainPass.FillColumn(), Terraria.GameContent.ObjectInteractions.TileSmartInteractCandidateProvider.FillPotentialTargetTiles(), Terraria.WorldGen.FillWallHolesInSpot(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindBoulderTrapSpot(), Terraria.NPC.FindCattailTop(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpotSingle(), Terraria.Player.FindPulley(), Terraria.Mount.FindTileHeight(), Terraria.NPC.FindTreeBranch(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.WorldGen.FinishDrunkGen(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishNoTraps(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FinishRemixWorld(), Terraria.WorldGen.FinishTenthAnniversaryWorld(), Terraria.WorldGen.FixChand(), Terraria.WorldGen.FixChands(), Terraria.IO.WorldFile.FixDresserChests(), Terraria.WorldGen.FixHeart(), Terraria.WorldGen.FixHearts(), Terraria.WorldGen.FixSunflowers(), Terraria.WorldGen.FloatingIsland(), Terraria.GameContent.Biomes.HiveBiome.FrameOutAllHiveContents(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEHatRack.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile(), Terraria.GameContent.Biomes.Desert.SurfaceMap.FromArea(), Terraria.GameContent.Drawing.WallDrawing.FullTile(), Terraria.WorldGen.Spread.Gem(), Terraria.WorldGen.GeneratePlanteraBulbOnAllMechsDefeated(), Terraria.GameContent.Biomes.JunglePass.GenerateTunnelToSurface(), Terraria.WorldGen.GenerateWorld(), Terraria.WorldGen.GERunner(), Terraria.WorldGen.GetCactusType(), Terraria.MessageBuffer.GetData(), Terraria.NPC.GetFairyTreasureCoords(), Terraria.Player.GetHurtTile(), Terraria.GameContent.Drawing.TileDrawing.GetPalmTreeBiome(), Terraria.GameContent.Drawing.TileDrawing.GetPalmTreeVariant(), Terraria.GameContent.PlayerSittingHelper.GetSittingTargetInfo(), Terraria.GameContent.PlayerSleepingHelper.GetSleepingTargetInfo(), Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Graphics.Light.TileLightScanner.GetTileLight(), Terraria.Collision.GetTileRotation(), Terraria.GameContent.Drawing.TileDrawing.GetTreeBiome(), Terraria.WorldGen.GetTreeBottom(), Terraria.GameContent.Drawing.TileDrawing.GetTreeVariant(), Terraria.WorldGen.GetVineTop(), Terraria.WorldGen.GrowAlch(), Terraria.WorldGen.GrowCactus(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowCheckSeaweed(), Terraria.WorldGen.GrowDungeonTree(), Terraria.WorldGen.GrowDungeonTree_MakePassage(), Terraria.WorldGen.GrowEpicTree(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowLivingTree_HorizontalTunnel(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.WorldGen.GrowLivingTreePassageRoom(), Terraria.WorldGen.GrowPalmTree(), Terraria.WorldGen.GrowPumpkin(), Terraria.WorldGen.GrowShroom(), Terraria.WorldGen.GrowSpike(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowUndergroundTree(), Terraria.WorldGen.GrowWeb(), Terraria.Player.HandleBeingInChestRange(), Terraria.WorldGen.hardUpdateWorld(), Terraria.WorldGen.HasValidGroundForAbigailsFlowerBelowSpot(), Terraria.WorldGen.HasValidGroundForGlowTulipBelowSpot(), Terraria.NPC.HaveDryadDoStardewAnimation(), Terraria.WorldGen.HellFort(), Terraria.WorldGen.HellHouse(), Terraria.WorldGen.HellRoom(), Terraria.GameContent.Golf.GolfHelper.HitGolfBall(), Terraria.Collision.HitTiles(), Terraria.Collision.HitWallSubstep(), Terraria.Wiring.HitWireSingle(), Terraria.Collision.HurtTiles(), Terraria.Player.InterruptItemUsageIfOverTile(), Terraria.WorldGen.IsBelowANonHammeredPlatform(), Terraria.Player.IsBottomOfTreeTrunkNoRoots(), Terraria.WorldGen.IsFitToPlaceFlowerIn(), Terraria.GameContent.Biomes.DeadMansChestBiome.IsGoodSpotsForExplosive(), Terraria.GameContent.SmartCursorHelper.IsHoveringOverAnInteractibleTileThatBlocksSmartCursor(), Terraria.WorldGen.IsItATrap(), Terraria.WorldGen.IsItATrigger(), Terraria.WorldGen.IslandHouse(), Terraria.GameContent.Generation.TrackGenerator.IsLocationInvalid(), Terraria.GameContent.Generation.TrackGenerator.IsMinecartTrack(), Terraria.WorldGen.IsOpenDoorAnchorFrame(), Terraria.Minecart.IsPressurePlate(), Terraria.WorldGen.IsRope(), Terraria.Tile.isTheSameAs(), Terraria.WorldGen.IsTileALeafyTreeTop(), Terraria.WorldGen.IsTileNearby(), Terraria.WorldGen.IsTileReplacable(), Terraria.Player.IsTileTypeInInteractionRange(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.IsTileValidForEntity(), Terraria.GameContent.Tile_Entities.TEHatRack.IsTileValidForEntity(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.IsTileValidForEntity(), Terraria.Collision.IsWorldPointSolid(), Terraria.Player.ItemCheck_ApplyHoldStyle(), Terraria.Player.ItemCheck_CheckCanUse(), Terraria.Player.ItemCheck_CutTiles(), Terraria.Player.ItemCheck_IsValidDirtRodTarget(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_TryPlacingWearablesOnMannequins(), Terraria.Player.ItemCheck_UseMiningTools(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.ItemCheck_UseMiningTools_TryFindingWallToHammer(), Terraria.Player.ItemCheck_UseMiningTools_TryHittingWall(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.Projectile.Kill(), Terraria.Projectile.Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillTile_DropItems(), Terraria.WorldGen.KillTile_GetItemDrops(), Terraria.WorldGen.KillTile_GetTreeDrops(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.WorldGen.Lakinater(), Terraria.WorldGen.LaunchRocket(), Terraria.WorldGen.LeftEdgeCanBeAttachedTo(), Terraria.Graphics.Light.TileLightScanner.LightIsBlocked(), Terraria.Liquid.LiquidCheck(), Terraria.IO.WorldFile.LoadSigns(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.WorldGen.MakeDungeon(), Terraria.WorldGen.MakeDungeon_Banners(), Terraria.WorldGen.MakeDungeon_GroundFurniture(), Terraria.WorldGen.MakeDungeon_Lights(), Terraria.WorldGen.MakeDungeon_Pictures(), Terraria.WorldGen.makeTemple(), Terraria.WorldGen.MakeWateryIceThing(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.MatureTheHerbPlants(), Terraria.WorldGen.meteor(), Terraria.WorldGen.MineHouse(), Terraria.GameContent.MinecartDiggerHelper.MineTheTileIfNecessary(), Terraria.WorldGen.Spread.Moss(), Terraria.WorldGen.Mountinater(), Terraria.WorldGen.nearbyChlorophyte(), Terraria.Chest.NearOtherChests(), Terraria.WorldGen.nearPicture(), Terraria.WorldGen.nearPicture2(), Terraria.WorldGen.neonMossBiome(), Terraria.WorldGen.nextCount(), Terraria.WorldGen.nextDirtCount(), Terraria.WorldGen.NoNearbyAbigailsFlower(), Terraria.WorldGen.NoNearbyGlowTulips(), Terraria.Collision.noSlopeCollision(), Terraria.DelegateMethods.NotDoorStand(), Terraria.WorldGen.oceanCave(), Terraria.WorldGen.OpenDoor(), Terraria.WorldGen.OrePatch(), Terraria.WorldGen.OreRunner(), Terraria.WorldGen.outerTempled(), Terraria.WorldGen.paintCoatTile(), Terraria.WorldGen.PaintTheClouds(), Terraria.WorldGen.PaintTheDungeon(), Terraria.WorldGen.PaintTheLivingTrees(), Terraria.WorldGen.PaintTheMushrooms(), Terraria.WorldGen.PaintThePurityGrass(), Terraria.WorldGen.PaintThePyramids(), Terraria.WorldGen.PaintTheSand(), Terraria.WorldGen.PaintTheTemple(), Terraria.WorldGen.PaintTheTrees(), Terraria.WorldGen.paintTile(), Terraria.Player.PickTile(), Terraria.GameContent.Biomes.Desert.SandMound.Place(), Terraria.GameContent.Biomes.CampsiteBiome.Place(), Terraria.GameContent.Biomes.GraniteBiome.Place(), Terraria.GameContent.Biomes.HiveBiome.Place(), Terraria.GameContent.Biomes.HoneyPatchBiome.Place(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), Terraria.TileObject.Place(), Terraria.WorldGen.Place1x1(), Terraria.WorldGen.Place1x2(), Terraria.WorldGen.Place1x2Top(), Terraria.WorldGen.Place1xX(), Terraria.WorldGen.Place2x1(), Terraria.WorldGen.Place2x2(), Terraria.WorldGen.Place2x2Horizontal(), Terraria.WorldGen.Place2x2Style(), Terraria.WorldGen.Place2x3Wall(), Terraria.WorldGen.Place2xX(), Terraria.WorldGen.Place3x1(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.Place3x2Wall(), Terraria.WorldGen.Place3x3(), Terraria.WorldGen.Place3x3Wall(), Terraria.WorldGen.Place3x4(), Terraria.WorldGen.Place4x2(), Terraria.WorldGen.Place4x3Wall(), Terraria.WorldGen.Place5x4(), Terraria.WorldGen.Place6x3(), Terraria.WorldGen.Place6x4Wall(), Terraria.WorldGen.PlaceAlch(), Terraria.WorldGen.PlaceBamboo(), Terraria.WorldGen.PlaceBanner(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceBoulderTrapSpot(), Terraria.WorldGen.PlaceCannon(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceChand(), Terraria.WorldGen.PlaceChestDirect(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine(), Terraria.GameContent.Biomes.GraniteBiome.PlaceDecorations(), Terraria.WorldGen.PlaceDoor(), Terraria.WorldGen.PlaceDresserDirect(), Terraria.WorldGen.PlaceDye(), Terraria.WorldGen.PlaceJunglePlant(), Terraria.WorldGen.placeLavaTrap(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceLogicTiles(), Terraria.WorldGen.PlaceMan(), Terraria.WorldGen.PlaceMB(), Terraria.WorldGen.PlaceOasis(), Terraria.WorldGen.PlaceOasisPlant(), Terraria.WorldGen.PlaceOnTable1x1(), Terraria.WorldGen.PlacePot(), Terraria.WorldGen.PlacePumpkin(), Terraria.GameContent.Biomes.Desert.SandMound.PlaceSandColumn(), Terraria.WorldGen.PlaceSandTrap(), Terraria.WorldGen.PlaceSign(), Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab(), Terraria.WorldGen.PlaceSmallPile(), Terraria.WorldGen.PlaceStatueTrap(), Terraria.WorldGen.PlaceSunflower(), Terraria.Player.PlaceThing_CannonBall(), Terraria.Player.PlaceThing_CheckSpecificValidtyCaseForBlockSwap(), Terraria.Player.PlaceThing_ItemInExtractinator(), Terraria.Player.PlaceThing_LockChest(), Terraria.Player.PlaceThing_Paintbrush(), Terraria.Player.PlaceThing_PaintScrapper_LongMoss(), Terraria.Player.PlaceThing_PaintScrapper_TryScrapping(), Terraria.Player.PlaceThing_Tiles(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForRepeatedCoralAndBeachPiles(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForRepeatedPigronatas(), Terraria.Player.PlaceThing_Tiles_CheckRopeUsability(), Terraria.Player.PlaceThing_Tiles_GetAutoAccessoryCache(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Terraria.Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Terraria.Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck(), Terraria.Player.PlaceThing_TryReplacingTiles(), Terraria.Player.PlaceThing_Walls(), Terraria.Player.PlaceThing_XMasTreeTops(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.placeTNTBarrel(), Terraria.Minecart.PlaceTrack(), Terraria.WorldGen.placeTrap(), Terraria.WorldGen.PlaceUncheckedStalactite(), Terraria.WorldGen.PlaceUnderwaterPlant(), Terraria.Player.PlaceWeapon(), Terraria.WorldGen.PlaceWoman(), Terraria.WorldGen.PlaceXmasTree(), Terraria.WorldGen.PlaceXmasTree_Direct(), Terraria.WorldGen.PlantAlch(), Terraria.WorldGen.plantDye(), Terraria.WorldGen.PlantSeaOat(), Terraria.WorldGen.PlatformProperSides(), Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing(), Terraria.HitTile.Prune(), Terraria.WorldGen.Pyramid(), Terraria.Player.QuickGrapple(), Terraria.Player.QuickMinecart(), Terraria.Player.QuickMinecartSnap(), Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition(), Terraria.WorldGen.ReplaceTile_EliminateNaturalExtras(), Terraria.GameContent.Biomes.TerrainPass.RetargetColumn(), Terraria.WorldGen.RightEdgeCanBeAttachedTo(), Terraria.GameContent.Tile_Entities.TELogicSensor.SanityCheck(), Terraria.IO.WorldFile.SaveChests(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.SceneMetrics.ScanAndExportToMain(), Terraria.WorldGen.ScanTileColumnAndRemoveClumps(), Terraria.GameContent.Events.MysticLogFairiesEvent.ScanWholeOverworldForLogs(), Terraria.WorldGen.ScoreRoom(), Terraria.WorldGen.ScoreRoom_CanBeHomeSpot(), Terraria.DelegateMethods.SearchAvoidedByNPCs(), Terraria.Framing.SelfFrame8Way(), Terraria.NetMessage.SendData(), Terraria.WorldGen.ShakeTree(), Terraria.WorldGen.ShellPile(), Terraria.WorldGen.ShiftTrapdoor(), Terraria.WorldGen.ShimmeratorNext(), Terraria.WorldGen.ShimmerCleanUp(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldGen.ShimmerMakeBiomeOpening(), Terraria.GameContent.ObjectInteractions.BlockBecauseYouAreOverAnImportantTile.ShouldBlockSmartInteract(), Terraria.GameContent.Biomes.GraniteBiome.ShouldUseLava(), Terraria.WorldGen.ShroomPatch(), Terraria.Collision.SlopeCollision(), Terraria.Player.SmartSelect_GetToolStrategy(), Terraria.WorldGen.smCallBack(), Terraria.WorldGen.SnowCloudIsland(), Terraria.Collision.SolidCollision(), Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidOrSlopedTile(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTile3(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.WorldGen.SolidTileAllowLeftSlope(), Terraria.WorldGen.SolidTileAllowRightSlope(), Terraria.WorldGen.SolidTileAllowTopSlope(), Terraria.WorldGen.SolidTileNoAttach(), Terraria.Collision.SolidTiles(), Terraria.Collision.SolidTiles(), Terraria.WorldGen.SonOfLakinater(), Terraria.NPC.Spawning_SandstoneCheck(), Terraria.WorldGen.SpawnPlanteraThorns(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.Projectile.SpawnWebs(), Terraria.WorldGen.Spread.Spider(), Terraria.Player.SporeSac(), Terraria.GameContent.Biomes.HiveBiome.SpotActuallyNotInHive(), Terraria.WorldGen.SpreadDesertWalls(), Terraria.DelegateMethods.SpreadDirt(), Terraria.WorldGen.SpreadGrass(), Terraria.DelegateMethods.SpreadLightOpen_StopForSolids(), Terraria.DelegateMethods.SpreadTest(), Terraria.WorldGen.Statue(), Terraria.GameContent.SmartCursorHelper.Step_Acorns(), Terraria.GameContent.SmartCursorHelper.Step_ActuationRod(), Terraria.GameContent.SmartCursorHelper.Step_Actuators(), Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds(), Terraria.GameContent.SmartCursorHelper.Step_Axe(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_BlocksLines(), Terraria.GameContent.SmartCursorHelper.Step_Boulders(), Terraria.GameContent.SmartCursorHelper.Step_ClayPots(), Terraria.GameContent.SmartCursorHelper.Step_ForceCursorToAnyMinableThing(), Terraria.GameContent.SmartCursorHelper.Step_GemCorns(), Terraria.GameContent.SmartCursorHelper.Step_GrassSeeds(), Terraria.GameContent.SmartCursorHelper.Step_Hammers(), Terraria.GameContent.SmartCursorHelper.Step_LawnMower(), Terraria.GameContent.SmartCursorHelper.Step_MinecartTracks(), Terraria.GameContent.SmartCursorHelper.Step_PaintBrush(), Terraria.GameContent.SmartCursorHelper.Step_PaintRoller(), Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineShinies(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.GameContent.SmartCursorHelper.Step_Pigronata(), Terraria.GameContent.SmartCursorHelper.Step_PlanterBox(), Terraria.GameContent.SmartCursorHelper.Step_Platforms(), Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds(), Terraria.GameContent.SmartCursorHelper.Step_StaffOfRegrowth(), Terraria.GameContent.SmartCursorHelper.Step_Torch(), Terraria.GameContent.SmartCursorHelper.Step_Walls(), Terraria.Collision.StepConveyorBelt(), Terraria.Player.StickyMovement(), Terraria.Collision.StickyTiles(), Terraria.WorldGen.StonePatch(), Terraria.GameContent.Events.DD2Event.SummonCrystalDirect(), Terraria.WorldGen.SwitchCannon(), Terraria.WorldGen.SwitchFountain(), Terraria.WorldGen.SwitchMB(), Terraria.WorldGen.SwitchMonolith(), Terraria.Collision.SwitchTiles(), Terraria.WorldGen.templeCleaner(), Terraria.WorldGen.templePart2(), Terraria.WorldGen.templePather(), Terraria.Sign.TextSign(), Terraria.Collision.TileCollision(), Terraria.WorldGen.tileCountAndDestroy(), Terraria.WorldGen.tileCounterKill(), Terraria.WorldGen.tileCounterNext(), Terraria.WorldGen.TileEmpty(), Terraria.WorldGen.TileFrame(), Terraria.Player.TileInteractionsCheck(), Terraria.Player.TileInteractionsCheckLongDistance(), Terraria.WorldGen.TileIsExposedToAir(), Terraria.WorldGen.TileRunner(), Terraria.WorldGen.TileType(), Terraria.WorldGen.ToggleGemLock(), Terraria.GameContent.Biomes.HiveBiome.TooCloseToImportantLocations(), Terraria.WorldGen.TopEdgeCanBeAttachedTo(), Terraria.Player.TorchAttack(), Terraria.Tile.ToString(), Terraria.Minecart.TrackColors(), Terraria.WorldGen.TreeGrowFXCheck(), Terraria.Player.TryBouncingBlocks(), Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryCloseDoor(), Terraria.GameContent.DoorOpeningHelper.TallGateOpeningInfoProvider.TryCloseDoor(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.TryGetPylonTypeFromTileCoords(), Terraria.WorldGen.TryGrowingAbigailsFlower(), Terraria.WorldGen.TryGrowingGlowTulip(), Terraria.Player.TryInteractingWithMinecartTrackInNearbyArea(), Terraria.WorldGen.TryKillingReplaceableTile(), Terraria.WorldGen.TryKillingTreesAboveIfTheyWouldBecomeInvalid(), Terraria.Player.TryLandingOnDetonator(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.Player.TryRecalculatingTorchLuck(), Terraria.GameContent.AmbientWindSystem.TrySpawningWind(), Terraria.WorldGen.TryToggleLight(), Terraria.Graphics.Light.LegacyLighting.TryUpdatingMapWithLight(), Terraria.Player.TryUsingDiggerCart(), Terraria.Collision.TupleHitLine(), Terraria.Gore.Update(), Terraria.Player.Update(), Terraria.Mount.UpdateFrame(), Terraria.Graphics.Light.LegacyLighting.UpdateLightToSkyColor(), Terraria.Wiring.UpdateMech(), Terraria.GameContent.PressurePlateHelper.UpdatePlayerPosition(), Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.ValidTile(), Terraria.GameContent.Tile_Entities.TEItemFrame.ValidTile(), Terraria.GameContent.Tile_Entities.TELogicSensor.ValidTile(), Terraria.GameContent.Tile_Entities.TETrainingDummy.ValidTile(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.ValidTile(), Terraria.WorldGen.Spread.Wall(), Terraria.WorldGen.Spread.Wall2(), Terraria.WorldGen.Spread.WallDungeon(), Terraria.Framing.WallFrame(), Terraria.WorldGen.WaterCheck(), Terraria.Collision.WetCollision(), Terraria.WorldGen.WillWaterPlacedHereStayPut(), and Terraria.WorldGen.WouldTileReplacementWork().