Terraria: Terraria.Tile.CopyFrom
CopyFrom()
void Terraria.Tile.CopyFrom (Tile from) inline
    {
        type = from.type;
        wall = from.wall;
        liquid = from.liquid;
        sTileHeader = from.sTileHeader;
        bTileHeader = from.bTileHeader;
        bTileHeader2 = from.bTileHeader2;
        bTileHeader3 = from.bTileHeader3;
        frameX = from.frameX;
        frameY = from.frameY;
    }
References Terraria.Tile.bTileHeader, Terraria.Tile.bTileHeader2, Terraria.Tile.bTileHeader3, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.liquid, Terraria.Tile.sTileHeader, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), and Terraria.IO.WorldFile.LoadWorldTiles().