Terraria: Terraria.Tile.ClearWallPaintAndCoating
ClearWallPaintAndCoating()
void Terraria.Tile.ClearWallPaintAndCoating () inline
Definition at line 876 of file Tile.cs.
    {
        wallColor(0);
        fullbrightWall(fullbrightWall: false);
        invisibleWall(invisibleWall: false);
    }
References Terraria.Tile.fullbrightWall(), Terraria.Tile.invisibleWall(), and Terraria.Tile.wallColor().
Referenced by Terraria.Tile.Clear(), Terraria.WorldGen.KillWall(), Terraria.WorldGen.ReplaceWall(), and Terraria.Framing.WallFrame().