Terraria: Terraria.Tile.invisibleWall
invisibleWall() [1/2]
bool Terraria.Tile.invisibleWall () inline
Definition at line 521 of file Tile.cs.
    {
        return (bTileHeader3 & 0x40) == 64;
    }
References Terraria.Tile.bTileHeader3.
Referenced by Terraria.Graphics.Light.TileLightScanner.ApplyHellLight(), Terraria.Graphics.Light.TileLightScanner.ApplySurfaceLight(), Terraria.TileColorCache.ApplyToWall(), Terraria.Tile.ClearWallPaintAndCoating(), Terraria.WorldGen.coatingColors(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.Map.MapHelper.CreateMapTile(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.HitTile.DrawFreshAnimations(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.Tile.invisibleWall(), Terraria.Tile.isTheSameAs(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.WorldGen.paintCoatWall(), Terraria.Player.PlaceThing_PaintScrapper_TryScrapping(), Terraria.WorldGen.RefreshStrip(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.GameContent.SmartCursorHelper.Step_PaintRoller(), Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper(), Terraria.Tile.WallColorAndCoating(), and Terraria.Framing.WallFrame().