Terraria: System.Formats.Asn1.AsnCharacterStringEncodings.GetEncoding
GetEncoding()
static Encoding System.Formats.Asn1.AsnCharacterStringEncodings.GetEncoding (UniversalTagNumber encodingType) inline static package
Definition at line 21 of file AsnCharacterStringEncodings.cs.
    {
        return encodingType switch
        {
            UniversalTagNumber.UTF8String => s_utf8Encoding,
            UniversalTagNumber.NumericString => s_numericStringEncoding,
            UniversalTagNumber.PrintableString => s_printableStringEncoding,
            UniversalTagNumber.IA5String => s_ia5Encoding,
            UniversalTagNumber.VisibleString => s_visibleStringEncoding,
            UniversalTagNumber.BMPString => s_bmpEncoding,
            UniversalTagNumber.TeletexString => s_t61Encoding,
            _ => throw new ArgumentOutOfRangeException("encodingType", encodingType, null),
        };
    }
References System.Formats.Asn1.AsnCharacterStringEncodings.s_bmpEncoding, System.Formats.Asn1.AsnCharacterStringEncodings.s_ia5Encoding, System.Formats.Asn1.AsnCharacterStringEncodings.s_numericStringEncoding, System.Formats.Asn1.AsnCharacterStringEncodings.s_printableStringEncoding, System.Formats.Asn1.AsnCharacterStringEncodings.s_t61Encoding, System.Formats.Asn1.AsnCharacterStringEncodings.s_utf8Encoding, and System.Formats.Asn1.AsnCharacterStringEncodings.s_visibleStringEncoding.
Referenced by System.Formats.Asn1.AsnDecoder.ReadCharacterString(), System.Formats.Asn1.AsnDecoder.TryReadCharacterString(), and System.Formats.Asn1.AsnWriter.WriteCharacterString().