Terraria: System.Threading.Tasks.Dataflow.Internal.ReorderingBuffer.OutputNextItem
OutputNextItem()
void System.Threading.Tasks.Dataflow.Internal.ReorderingBuffer< TOutput >.OutputNextItem (TOutput theNextItem, bool itemIsValid) inline private
Definition at line 79 of file ReorderingBuffer.cs.
    {
        _nextReorderedIdToOutput++;
        if (itemIsValid)
        {
            _outputAction(_owningSource, theNextItem);
        }
        KeyValuePair<bool, TOutput> value;
        while (_reorderingBuffer.TryGetValue(_nextReorderedIdToOutput, out value))
        {
            _reorderingBuffer.Remove(_nextReorderedIdToOutput);
            _nextReorderedIdToOutput++;
            if (value.Key)
            {
                _outputAction(_owningSource, value.Value);
            }
        }
    }
References System.Threading.Tasks.Dataflow.Internal.ReorderingBuffer< TOutput >._nextReorderedIdToOutput, System.Threading.Tasks.Dataflow.Internal.ReorderingBuffer< TOutput >._outputAction, System.Threading.Tasks.Dataflow.Internal.ReorderingBuffer< TOutput >._owningSource, System.Threading.Tasks.Dataflow.Internal.ReorderingBuffer< TOutput >._reorderingBuffer, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Threading.Tasks.Dataflow.Internal.ReorderingBuffer< TOutput >.AddItem(), and System.Threading.Tasks.Dataflow.Internal.ReorderingBuffer< TOutput >.AddItemIfNextAndTrusted().