Terraria: Terraria.Chat.Commands.PartyChatCommand.ProcessIncomingMessage
ProcessIncomingMessage()
void Terraria.Chat.Commands.PartyChatCommand.ProcessIncomingMessage (string text, byte clientId) inline
Implements Terraria.Chat.Commands.IChatCommand.
Definition at line 11 of file PartyChatCommand.cs.
    {
        int team = Main.player[clientId].team;
        Color color = Main.teamColor[team];
        if (team == 0)
        {
            SendNoTeamError(clientId);
        }
        else
        {
            if (text == "")
            {
                return;
            }
            for (int i = 0; i < 255; i++)
            {
                if (Main.player[i].team == team)
                {
                    ChatHelper.SendChatMessageToClientAs(clientId, NetworkText.FromLiteral(text), color, i);
                }
            }
        }
    }
References Terraria.Localization.NetworkText.FromLiteral(), Terraria.Main.player, Terraria.Chat.ChatHelper.SendChatMessageToClientAs(), Terraria.Chat.Commands.PartyChatCommand.SendNoTeamError(), and Terraria.Main.teamColor.