Terraria: System.IO.PathInternal.TrimEndingDirectorySeparator
TrimEndingDirectorySeparator() [1/3]
static ReadOnlySpan< char > System.IO.PathInternal.TrimEndingDirectorySeparator (ReadOnlySpan< char > path) inline static package
Definition at line 227 of file PathInternal.cs.
    {
        if (!EndsInDirectorySeparator(path) || IsRoot(path))
        {
            return path;
        }
        return path.Slice(0, path.Length - 1);
    }
References System.IO.PathInternal.EndsInDirectorySeparator(), System.IO.PathInternal.IsRoot(), System.ReadOnlySpan< T >.Length, and System.ReadOnlySpan< T >.Slice().