Terraria: System.IO.PathInternal.IsEffectivelyEmpty
IsEffectivelyEmpty()
static bool System.IO.PathInternal.IsEffectivelyEmpty (ReadOnlySpan< char > path) inline static package
Definition at line 457 of file PathInternal.cs.
    {
        if (path.IsEmpty)
        {
            return true;
        }
        ReadOnlySpan<char> readOnlySpan = path;
        for (int i = 0; i < readOnlySpan.Length; i++)
        {
            char c = readOnlySpan[i];
            if (c != ' ')
            {
                return false;
            }
        }
        return true;
    }
References System.ReadOnlySpan< T >.IsEmpty, and System.ReadOnlySpan< T >.Length.
Referenced by System.IO.DirectoryInfo.CreateSubdirectory(), System.IO.Path.GetDirectoryName(), System.IO.Path.GetDirectoryName(), System.IO.Path.GetFullPath(), System.IO.Path.GetFullPath(), System.IO.Path.GetPathRoot(), System.IO.Path.GetPathRoot(), and System.IO.Path.GetRelativePath().