Terraria: System.IO.PathInternal.RemoveRelativeSegments
RemoveRelativeSegments() [2/2]
static string System.IO.PathInternal.RemoveRelativeSegments (string path, int rootLength) inline static package
Definition at line 133 of file PathInternal.cs.
    {
        Span<char> initialBuffer = stackalloc char[260];
        ValueStringBuilder sb = new ValueStringBuilder(initialBuffer);
        if (RemoveRelativeSegments(path.AsSpan(), rootLength, ref sb))
        {
            path = sb.ToString();
        }
        sb.Dispose();
        return path;
    }
References System.Text.ValueStringBuilder.Dispose(), System.IO.PathInternal.RemoveRelativeSegments(), and System.Text.ValueStringBuilder.ToString().
Referenced by System.IO.Path.GetFullPath(), and System.IO.PathInternal.RemoveRelativeSegments().