Terraria: System.IO.PathInternal.NormalizeDirectorySeparators
NormalizeDirectorySeparators()
static string System.IO.PathInternal.NormalizeDirectorySeparators (string path) inline static package
Definition at line 413 of file PathInternal.cs.
    {
        if (string.IsNullOrEmpty(path))
        {
            return path;
        }
        bool flag = true;
        for (int i = 0; i < path.Length; i++)
        {
            char c = path[i];
            if (IsDirectorySeparator(c) && (c != '\\' || (i > 0 && i + 1 < path.Length && IsDirectorySeparator(path[i + 1]))))
            {
                flag = false;
                break;
            }
        }
        if (flag)
        {
            return path;
        }
        Span<char> initialBuffer = stackalloc char[260];
        ValueStringBuilder valueStringBuilder = new ValueStringBuilder(initialBuffer);
        int num = 0;
        if (IsDirectorySeparator(path[num]))
        {
            num++;
            valueStringBuilder.Append('\\');
        }
        for (int j = num; j < path.Length; j++)
        {
            char c = path[j];
            if (IsDirectorySeparator(c))
            {
                if (j + 1 < path.Length && IsDirectorySeparator(path[j + 1]))
                {
                    continue;
                }
                c = '\\';
            }
            valueStringBuilder.Append(c);
        }
        return valueStringBuilder.ToString();
    }
References System.Text.ValueStringBuilder.Append(), System.IO.PathInternal.IsDirectorySeparator(), and System.Text.ValueStringBuilder.ToString().
Referenced by System.IO.Path.GetDirectoryName(), and System.IO.Path.GetPathRoot().