Terraria: System.IO.PathInternal.GetRootLength
GetRootLength() [2/2]
static int System.IO.PathInternal.GetRootLength (ReadOnlySpan< char > path) inline static package
Definition at line 335 of file PathInternal.cs.
    {
        int length = path.Length;
        int i = 0;
        bool flag = IsDevice(path);
        bool flag2 = flag && IsDeviceUNC(path);
        if ((!flag || flag2) && length > 0 && IsDirectorySeparator(path[0]))
        {
            if (flag2 || (length > 1 && IsDirectorySeparator(path[1])))
            {
                i = (flag2 ? 8 : 2);
                int num = 2;
                for (; i < length; i++)
                {
                    if (IsDirectorySeparator(path[i]) && --num <= 0)
                    {
                        break;
                    }
                }
            }
            else
            {
                i = 1;
            }
        }
        else if (flag)
        {
            for (i = 4; i < length && !IsDirectorySeparator(path[i]); i++)
            {
            }
            if (i < length && i > 4 && IsDirectorySeparator(path[i]))
            {
                i++;
            }
        }
        else if (length >= 2 && path[1] == ':' && IsValidDriveChar(path[0]))
        {
            i = 2;
            if (length > 2 && IsDirectorySeparator(path[2]))
            {
                i++;
            }
        }
        return i;
    }
References System.IO.PathInternal.IsDevice(), System.IO.PathInternal.IsDeviceUNC(), System.IO.PathInternal.IsDirectorySeparator(), System.IO.PathInternal.IsValidDriveChar(), System.length, and System.ReadOnlySpan< T >.Length.