Terraria: Utils.GetChaseResults
GetChaseResults()
static ChaseResults Utils.GetChaseResults (Vector2 chaserPosition, float chaserSpeed, Vector2 runnerPosition, Vector2 runnerVelocity) inline static
     {
         ChaseResults result = default(ChaseResults);
         if (chaserPosition == runnerPosition)
         {
             ChaseResults result2 = default(ChaseResults);
             result2.InterceptionHappens = true;
             result2.InterceptionPosition = chaserPosition;
             result2.InterceptionTime = 0f;
             result2.ChaserVelocity = Vector2.Zero;
             return result2;
         }
         if (chaserSpeed <= 0f)
         {
             return default(ChaseResults);
         }
         Vector2 value = chaserPosition - runnerPosition;
         float num = value.Length();
         float num2 = runnerVelocity.Length();
         if (num2 == 0f)
         {
             result.InterceptionTime = num / chaserSpeed;
             result.InterceptionPosition = runnerPosition;
         }
         else
         {
             float a = chaserSpeed * chaserSpeed - num2 * num2;
             float b = 2f * Vector2.Dot(value, runnerVelocity);
             float c = (0f - num) * num;
             if (!SolveQuadratic(a, b, c, out var result3, out var result4))
             {
                 return default(ChaseResults);
             }
             if (result3 < 0f && result4 < 0f)
             {
                 return default(ChaseResults);
             }
             if (result3 > 0f && result4 > 0f)
             {
                 result.InterceptionTime = Math.Min(result3, result4);
             }
             else
             {
                 result.InterceptionTime = Math.Max(result3, result4);
             }
             result.InterceptionPosition = runnerPosition + runnerVelocity * result.InterceptionTime;
         }
         result.ChaserVelocity = (result.InterceptionPosition - chaserPosition) / result.InterceptionTime;
         result.InterceptionHappens = true;
         return result;
     }
References Utils.ChaseResults.ChaserVelocity, Utils.ChaseResults.InterceptionHappens, Utils.ChaseResults.InterceptionPosition, Utils.ChaseResults.InterceptionTime, and SolveQuadratic().
Referenced by NPC.AI_003_Fighters(), Projectile.AI_066_TryInterceptingTarget(), and Player.OnHit().