Terraria: Utils.OpenFolder
OpenFolder()
static void Utils.OpenFolder (string folderPath) inline static
     {
         if (TryCreatingDirectory(folderPath))
         {
             if (Platform.IsLinux)
             {
                 Process.Start(new ProcessStartInfo(folderPath)
                 {
                     FileName = "open-folder",
                     Arguments = folderPath,
                     UseShellExecute = true,
                     CreateNoWindow = true
                 });
             }
             else
             {
                 Process.Start(folderPath);
             }
         }
     }
References Platform.IsLinux, and TryCreatingDirectory().
Referenced by UIResourcePackSelectionMenu.OpenFoldersClick(), and CaptureInterface.UpdateButtons().