Terraria: Utils.DrawBorderString
DrawBorderString()
static Vector2 Utils.DrawBorderString (SpriteBatch sb, string text, Vector2 pos, Color color, float scale = 1f, float anchorx = 0f, float anchory = 0f, int maxCharactersDisplayed = -1) inline static
     {
         if (maxCharactersDisplayed != -1 && text.Length > maxCharactersDisplayed)
         {
             text.Substring(0, maxCharactersDisplayed);
         }
         DynamicSpriteFont value = FontAssets.MouseText.Value;
         Vector2 vector = value.MeasureString(text);
         ChatManager.DrawColorCodedStringWithShadow(sb, value, text, pos, color, 0f, new Vector2(anchorx, anchory) * vector, new Vector2(scale), -1f, 1.5f);
         return vector * scale;
     }
References ChatManager.DrawColorCodedStringWithShadow(), DynamicSpriteFont.MeasureString(), FontAssets.MouseText, and Asset< T >.Value.
Referenced by IngameOptions.Draw(), InGamePopups.AchievementUnlockedPopup.DrawInGame(), InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame(), InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea(), Main.DrawInterface_33_MouseText(), Main.DrawInvasionProgress(), IngameOptions.DrawRightSide(), UIBestiaryInfoLine< T >.DrawSelf(), UICharacterListItem.DrawSelf(), UITextBox.DrawSelf(), UIWorkshopImportWorldListItem.DrawSelf(), UIWorkshopPublishResourcePackListItem.DrawSelf(), UIWorkshopPublishWorldListItem.DrawSelf(), UIWorldListItem.DrawSelf(), UITextPanel< T >.DrawText(), IngameOptions.DrawValue(), and Main.DrawWindowsIMEPanel().