Terraria: Utils.Remap
Remap()
static float Utils.Remap (float fromValue, float fromMin, float fromMax, float toMin, float toMax, bool clamped = true) inline static
References GetLerpValue().
Referenced by Projectile.AI(), Projectile.AI_001(), NPC.AI_006_Worms(), NPC.AI_007_TownEntities(), Projectile.AI_019_Spears_GetExtensionHitbox(), Projectile.AI_120_StardustGuardian(), NPC.AI_123_Deerclops(), Projectile.AI_152_SuperStarSlash(), Projectile.AI_155_MysticSnakeCoil(), Projectile.AI_186_PrincessWeapon(), Projectile.AI_187_ShadowHand(), Projectile.AI_189_Volcano(), Projectile.AI_190_NightsEdge(), Projectile.AI_191_TrueNightsEdge(), Projectile.AI_192_JuminoAnimation(), Projectile.AI_193_Flamethrower(), Projectile.AI_195_JimsDrone(), Projectile.Colliding(), Projectile.Damage_GetHitbox(), ItemTransferParticle.Draw(), LittleFlyingCritterParticle.Draw(), WorkshopPublishingIndicator.Draw(), NetDiagnosticsUI.DrawCounter(), Main.DrawNPCDirect(), Main.DrawNPCDirect_Deerclops(), Main.DrawNPCDirect_Faeling(), PlayerDrawLayers.DrawPlayer_27_HeldItem(), Main.DrawProj_Excalibur(), Main.DrawProj_Flamethrower(), Main.DrawProj_LightsBane(), Main.DrawProj_NightsEdge(), Main.DrawProj_Spear(), Main.DrawProj_TerraBlade2(), Main.DrawProj_TerraBlade2Shot(), Main.DrawProj_TheHorsemansBlade(), Main.DrawProj_TrueExcalibur(), Main.DrawProj_TrueNightsEdge(), Main.DrawProjDirect(), Main.DrawStar(), Main.DrawTrail(), NPC.GetAlpha(), ItemSlot.GetColorByLoadout(), SepiaScreenShaderData.GetDaylightPowers(), LiquidRenderer.GetShimmerGlitterOpacity(), Projectile.Kill(), DontStarveSeed.ModifyNightColor(), CreativePowers.SpawnRateSliderPerPlayerPower.RemapSliderValueToPowerValue(), NPC.ScaleStats_UseStrengthMultiplier(), ParticleOrchestrator.Spawn_PooFly(), NPC.SpawnPassiveShadowHands(), ScreenDarkness.Update(), PunchCameraModifier.Update(), GasParticle.Update(), Dust.UpdateDust(), CreativePowers.ModifyTimeRate.UpdateInfoFromSliderValueCache(), and CreativePowers.DifficultySliderPower.UpdateInfoFromSliderValueCache().