Terraria: Utils.CoinsCount
CoinsCount()
static long Utils.CoinsCount (out bool overFlowing, Item[] inv, params int[] ignoreSlots) inline static
     {
         List<int> list = new List<int>(ignoreSlots);
         long num = 0L;
         for (int i = 0; i < inv.Length; i++)
         {
             if (!list.Contains(i))
             {
                 switch (inv[i].type)
                 {
                 case 71:
                     num += inv[i].stack;
                     break;
                 case 72:
                     num += (long)inv[i].stack * 100L;
                     break;
                 case 73:
                     num += (long)inv[i].stack * 10000L;
                     break;
                 case 74:
                     num += (long)inv[i].stack * 1000000L;
                     break;
                 }
             }
         }
         overFlowing = false;
         return num;
     }
References L, and Item.stack.
Referenced by Player.BuyItem(), ItemSlot.DrawSavings(), Player.KillMe(), ChestUI.MoveCoins(), and ItemSorting.SortCoins().