Terraria: Utils.PlotTileArea
PlotTileArea()
static bool Utils.PlotTileArea (int x, int y, TileActionAttempt plot) inline static
     {
         if (!WorldGen.InWorld(x, y))
         {
             return false;
         }
         List<Point> list = new List<Point>();
         List<Point> list2 = new List<Point>();
         HashSet<Point> hashSet = new HashSet<Point>();
         list2.Add(new Point(x, y));
         while (list2.Count > 0)
         {
             list.Clear();
             list.AddRange(list2);
             list2.Clear();
             while (list.Count > 0)
             {
                 Point item = list[0];
                 if (!WorldGen.InWorld(item.X, item.Y, 1))
                 {
                     list.Remove(item);
                     continue;
                 }
                 hashSet.Add(item);
                 list.Remove(item);
                 if (plot(item.X, item.Y))
                 {
                     Point item2 = new Point(item.X - 1, item.Y);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                     item2 = new Point(item.X + 1, item.Y);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                     item2 = new Point(item.X, item.Y - 1);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                     item2 = new Point(item.X, item.Y + 1);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                 }
             }
         }
         return true;
     }
References WorldGen.InWorld().
Referenced by Player.ItemCheck_EmitHeldItemLight(), Projectile.Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks(), and Projectile.ProjLight().