Terraria: System.Numerics.BigNumber.TryParseBigInteger
TryParseBigInteger() [1/2]
static bool System.Numerics.BigNumber.TryParseBigInteger (ReadOnlySpan< char > value, NumberStyles style, NumberFormatInfo info, out BigInteger result) inline static package
Definition at line 57 of file BigNumber.cs.
    {
        if (!TryValidateParseStyleInteger(style, out var e))
        {
            throw e;
        }
        BigNumberBuffer number = BigNumberBuffer.Create();
        if (!FormatProvider.TryStringToBigInteger(value, style, info, number.digits, out number.precision, out number.scale, out number.sign))
        {
            result = default(BigInteger);
            return false;
        }
        if ((style & NumberStyles.AllowHexSpecifier) != 0)
        {
            return HexNumberToBigInteger(ref number, out result);
        }
        return NumberToBigInteger(ref number, out result);
    }
References System.Numerics.BigNumber.BigNumberBuffer.Create(), System.Numerics.BigNumber.BigNumberBuffer.digits, System.Numerics.BigNumber.HexNumberToBigInteger(), System.info, System.Numerics.BigNumber.NumberToBigInteger(), System.Numerics.BigNumber.BigNumberBuffer.precision, System.Numerics.BigNumber.BigNumberBuffer.scale, System.Numerics.BigNumber.BigNumberBuffer.sign, System.Globalization.FormatProvider.TryStringToBigInteger(), System.Numerics.BigNumber.TryValidateParseStyleInteger(), and System.value.