Terraria: System.Numerics.BigNumber.FormatBigInteger
FormatBigInteger() [1/2]
static string System.Numerics.BigNumber.FormatBigInteger (BigInteger value, string format, NumberFormatInfo info) inline static package
Definition at line 420 of file BigNumber.cs.
    {
        int charsWritten;
        bool spanSuccess;
        return FormatBigInteger(targetSpan: false, value, format, format, info, default(Span<char>), out charsWritten, out spanSuccess);
    }
References System.format, System.Numerics.BigNumber.FormatBigInteger(), System.info, and System.value.
Referenced by System.Numerics.BigNumber.FormatBigInteger(), System.Numerics.BigInteger.ToString(), System.Numerics.BigInteger.ToString(), System.Numerics.BigInteger.ToString(), System.Numerics.BigInteger.ToString(), and System.Numerics.BigNumber.TryFormatBigInteger().