Terraria: System.Numerics.BigNumber.TryParseBigInteger
TryParseBigInteger() [2/2]
static bool System.Numerics.BigNumber.TryParseBigInteger (string value, NumberStyles style, NumberFormatInfo info, out BigInteger result) inline static package
Definition at line 47 of file BigNumber.cs.
    {
        if (value == null)
        {
            result = default(BigInteger);
            return false;
        }
        return TryParseBigInteger(value.AsSpan(), style, info, out result);
    }
References System.info, System.Numerics.BigNumber.TryParseBigInteger(), and System.value.
Referenced by System.Numerics.BigNumber.ParseBigInteger(), System.Numerics.BigInteger.TryParse(), System.Numerics.BigInteger.TryParse(), and System.Numerics.BigNumber.TryParseBigInteger().