Terraria: System.Numerics.BigNumber.HexNumberToBigInteger
HexNumberToBigInteger()
static bool System.Numerics.BigNumber.HexNumberToBigInteger (ref BigNumberBuffer number, out BigInteger result) inline static private
Definition at line 98 of file BigNumber.cs.
    {
        if (number.digits == null || number.digits.Length == 0)
        {
            result = default(BigInteger);
            return false;
        }
        int a = number.digits.Length - 1;
        int result2;
        int num = Math.DivRem(a, 8, out result2);
        int num2;
        if (result2 == 0)
        {
            num2 = 0;
        }
        else
        {
            num++;
            num2 = 8 - result2;
        }
        bool flag = System.HexConverter.FromChar(number.digits[0]) >= 8;
        uint num3 = ((flag && num2 > 0) ? uint.MaxValue : 0u);
        int[] array = null;
        Span<uint> span = ((num > 64) ? MemoryMarshal.Cast<int, uint>((array = ArrayPool<int>.Shared.Rent(num)).AsSpan(0, num)) : stackalloc uint[num]);
        Span<uint> span2 = span;
        int num4 = num - 1;
        try
        {
            StringBuilder.ChunkEnumerator enumerator = number.digits.GetChunks().GetEnumerator();
            while (enumerator.MoveNext())
            {
                ReadOnlySpan<char> span3 = enumerator.Current.Span;
                for (int i = 0; i < span3.Length; i++)
                {
                    char c = span3[i];
                    if (c == '\0')
                    {
                        break;
                    }
                    int num5 = System.HexConverter.FromChar(c);
                    num3 = (num3 << 4) | (uint)num5;
                    num2++;
                    if (num2 == 8)
                    {
                        span2[num4] = num3;
                        num4--;
                        num3 = 0u;
                        num2 = 0;
                    }
                }
            }
            span2 = span2.TrimEnd(0u);
            int num6;
            uint[] array2;
            if (span2.IsEmpty)
            {
                num6 = 0;
                array2 = null;
            }
            else if (span2.Length == 1)
            {
                num6 = (int)span2[0];
                array2 = null;
                if ((!flag && num6 < 0) || num6 == int.MinValue)
                {
                    array2 = new uint[1] { (uint)num6 };
                    num6 = ((!flag) ? 1 : (-1));
                }
            }
            else
            {
                num6 = ((!flag) ? 1 : (-1));
                array2 = span2.ToArray();
                if (flag)
                {
                    NumericsHelpers.DangerousMakeTwosComplement(array2);
                }
            }
            result = new BigInteger(num6, array2);
            return true;
        }
        finally
        {
            if (array != null)
            {
                ArrayPool<int>.Shared.Return(array);
            }
        }
    }
References System.array, System.Text.StringBuilder.ChunkEnumerator.Current, System.Numerics.NumericsHelpers.DangerousMakeTwosComplement(), System.Math.DivRem(), System.HexConverter.FromChar(), System.Text.StringBuilder.ChunkEnumerator.GetEnumerator(), System.Span< T >.IsEmpty, System.ReadOnlySpan< T >.Length, System.Span< T >.Length, System.Text.StringBuilder.ChunkEnumerator.MoveNext(), System.Buffers.ArrayPool< T >.Shared, System.ReadOnlyMemory< T >.Span, and System.Span< T >.ToArray().
Referenced by System.Numerics.BigNumber.TryParseBigInteger().