Terraria: System.Numerics.BigNumber.TryValidateParseStyleInteger
TryValidateParseStyleInteger()
static bool System.Numerics.BigNumber.TryValidateParseStyleInteger (NumberStyles style, [NotNullWhen(false)] out ArgumentException e) inline static package
Definition at line 31 of file BigNumber.cs.
    {
        if (((uint)style & 0xFFFFFC00u) != 0)
        {
            e = new ArgumentException(System.SR.Format(System.SR.Argument_InvalidNumberStyles, "style"));
            return false;
        }
        if ((style & NumberStyles.AllowHexSpecifier) != 0 && ((uint)style & 0xFFFFFDFCu) != 0)
        {
            e = new ArgumentException(System.SR.Argument_InvalidHexStyle);
            return false;
        }
        e = null;
        return true;
    }
References System.SR.Argument_InvalidHexStyle, System.SR.Argument_InvalidNumberStyles, and System.SR.Format().
Referenced by System.Numerics.BigNumber.ParseBigInteger(), and System.Numerics.BigNumber.TryParseBigInteger().