Terraria: System.Numerics.BigNumber.FormatBigIntegerToHex
FormatBigIntegerToHex()
static string System.Numerics.BigNumber.FormatBigIntegerToHex (bool targetSpan, BigInteger value, char format, int digits, NumberFormatInfo info, Span< char > destination, out int charsWritten, out bool spanSuccess) inline static private
Definition at line 362 of file BigNumber.cs.
    {
        byte[] array = null;
        Span<byte> destination2 = stackalloc byte[64];
        if (!value.TryWriteOrCountBytes(destination2, out var bytesWritten))
        {
            destination2 = (array = ArrayPool<byte>.Shared.Rent(bytesWritten));
            bool flag = value.TryWriteBytes(destination2, out bytesWritten);
        }
        destination2 = destination2.Slice(0, bytesWritten);
        Span<char> initialBuffer = stackalloc char[128];
        System.Text.ValueStringBuilder valueStringBuilder = new System.Text.ValueStringBuilder(initialBuffer);
        int num = destination2.Length - 1;
        if (num > -1)
        {
            bool flag2 = false;
            byte b = destination2[num];
            if (b > 247)
            {
                b -= 240;
                flag2 = true;
            }
            if (b < 8 || flag2)
            {
                valueStringBuilder.Append((b < 10) ? ((char)(b + 48)) : ((format == 'X') ? ((char)((b & 0xF) - 10 + 65)) : ((char)((b & 0xF) - 10 + 97))));
                num--;
            }
        }
        if (num > -1)
        {
            Span<char> span = valueStringBuilder.AppendSpan((num + 1) * 2);
            int num2 = 0;
            string text = ((format == 'x') ? "0123456789abcdef" : "0123456789ABCDEF");
            while (num > -1)
            {
                byte b2 = destination2[num--];
                span[num2++] = text[b2 >> 4];
                span[num2++] = text[b2 & 0xF];
            }
        }
        if (digits > valueStringBuilder.Length)
        {
            valueStringBuilder.Insert(0, (value._sign >= 0) ? '0' : ((format == 'x') ? 'f' : 'F'), digits - valueStringBuilder.Length);
        }
        if (array != null)
        {
            ArrayPool<byte>.Shared.Return(array);
        }
        if (targetSpan)
        {
            spanSuccess = valueStringBuilder.TryCopyTo(destination, out charsWritten);
            return null;
        }
        charsWritten = 0;
        spanSuccess = false;
        return valueStringBuilder.ToString();
    }
References System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.AppendSpan(), System.array, System.destination, System.format, System.Text.ValueStringBuilder.Insert(), System.Text.ValueStringBuilder.Length, System.Buffers.ArrayPool< T >.Shared, System.Span< T >.Slice(), System.text, System.Text.ValueStringBuilder.ToString(), System.Text.ValueStringBuilder.TryCopyTo(), and System.value.
Referenced by System.Numerics.BigNumber.FormatBigInteger().