Terraria: System.Buffers.Text.Utf8Parser.TimeSpanSplitter.TrySplitTimeSpan
TrySplitTimeSpan()
bool System.Buffers.Text.Utf8Parser.TimeSpanSplitter.TrySplitTimeSpan (ReadOnlySpan< byte > source, bool periodUsedToSeparateDay, out int bytesConsumed) inline
Definition at line 38 of file Utf8Parser.cs.
        {
            int i = 0;
            byte b = 0;
            for (; i != source.Length; i++)
            {
                b = source[i];
                if (b != 32 && b != 9)
                {
                    break;
                }
            }
            if (i == source.Length)
            {
                bytesConsumed = 0;
                return false;
            }
            if (b == 45)
            {
                IsNegative = true;
                i++;
                if (i == source.Length)
                {
                    bytesConsumed = 0;
                    return false;
                }
            }
            if (!TryParseUInt32D(source.Slice(i), out V1, out var bytesConsumed2))
            {
                bytesConsumed = 0;
                return false;
            }
            i += bytesConsumed2;
            ComponentParseResult componentParseResult = ParseComponent(source, periodUsedToSeparateDay, ref i, out V2);
            switch (componentParseResult)
            {
            case ComponentParseResult.ParseFailure:
                bytesConsumed = 0;
                return false;
            case ComponentParseResult.NoMoreData:
                bytesConsumed = i;
                return true;
            default:
                Separators |= (uint)componentParseResult << 24;
                componentParseResult = ParseComponent(source, neverParseAsFraction: false, ref i, out V3);
                switch (componentParseResult)
                {
                case ComponentParseResult.ParseFailure:
                    bytesConsumed = 0;
                    return false;
                case ComponentParseResult.NoMoreData:
                    bytesConsumed = i;
                    return true;
                default:
                    Separators |= (uint)componentParseResult << 16;
                    componentParseResult = ParseComponent(source, neverParseAsFraction: false, ref i, out V4);
                    switch (componentParseResult)
                    {
                    case ComponentParseResult.ParseFailure:
                        bytesConsumed = 0;
                        return false;
                    case ComponentParseResult.NoMoreData:
                        bytesConsumed = i;
                        return true;
                    default:
                        Separators |= (uint)componentParseResult << 8;
                        componentParseResult = ParseComponent(source, neverParseAsFraction: false, ref i, out V5);
                        switch (componentParseResult)
{
                        case ComponentParseResult.ParseFailure:
                            bytesConsumed = 0;
                            return false;
                        case ComponentParseResult.NoMoreData:
                            bytesConsumed = i;
                            return true;
                        default:
                            Separators |= (uint)componentParseResult;
                            if (i != source.Length && (source[i] == 46 || source[i] == 58))
{
                                bytesConsumed = 0;
                                return false;
                            }
                            bytesConsumed = i;
                            return true;
                        }
                    }
                }
            }
        }
References System.Buffers.Text.Utf8Parser.TimeSpanSplitter.IsNegative, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.ParseComponent(), System.Buffers.Text.Utf8Parser.TimeSpanSplitter.Separators, System.source, System.Buffers.Text.Utf8Parser.TryParseUInt32D(), System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V1, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V2, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V3, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V4, and System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V5.
Referenced by System.Buffers.Text.Utf8Parser.TryParseTimeSpanC(), and System.Buffers.Text.Utf8Parser.TryParseTimeSpanLittleG().