Terraria: System.Buffers.Text.Utf8Parser.TimeSpanSplitter.ParseComponent
ParseComponent()
static ComponentParseResult System.Buffers.Text.Utf8Parser.TimeSpanSplitter.ParseComponent (ReadOnlySpan< byte > source, bool neverParseAsFraction, ref int srcIndex, out uint value) inline static private
Definition at line 128 of file Utf8Parser.cs.
        {
            if (srcIndex == source.Length)
            {
                value = 0u;
                return ComponentParseResult.NoMoreData;
            }
            byte b = source[srcIndex];
            if (b == 58 || (b == 46 && neverParseAsFraction))
            {
                srcIndex++;
                if (!TryParseUInt32D(source.Slice(srcIndex), out value, out var bytesConsumed))
                {
                    value = 0u;
                    return ComponentParseResult.ParseFailure;
                }
                srcIndex += bytesConsumed;
                if (b != 58)
                {
                    return ComponentParseResult.Period;
                }
                return ComponentParseResult.Colon;
            }
            if (b == 46)
            {
                srcIndex++;
                if (!TryParseTimeSpanFraction(source.Slice(srcIndex), out value, out var bytesConsumed2))
                {
                    value = 0u;
                    return ComponentParseResult.ParseFailure;
                }
                srcIndex += bytesConsumed2;
                return ComponentParseResult.Period;
            }
            value = 0u;
            return ComponentParseResult.NoMoreData;
        }
References System.source, System.Buffers.Text.Utf8Parser.TryParseTimeSpanFraction(), System.Buffers.Text.Utf8Parser.TryParseUInt32D(), and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TimeSpanSplitter.TrySplitTimeSpan().