Terraria: System.Reflection.DispatchProxyGenerator.ProxyBuilder.ParametersArray.EndSet
EndSet()
void System.Reflection.DispatchProxyGenerator.ProxyBuilder.ParametersArray.EndSet (int i, Type stackType) inline package
Definition at line 109 of file DispatchProxyGenerator.cs.
            {
                Type elementType = _paramTypes[i].GetElementType();
                Convert(_il, stackType, elementType, isAddress: false);
                Stind(_il, elementType);
            }
References System.Reflection.DispatchProxyGenerator.ProxyBuilder.ParametersArray._il, System.Reflection.DispatchProxyGenerator.ProxyBuilder.ParametersArray._paramTypes, System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert(), System.elementType, System.Type.GetElementType(), and System.Reflection.DispatchProxyGenerator.ProxyBuilder.Stind().