Terraria: Terraria.GameContent.Skies.SolarSky.Activate
Activate()
override void Terraria.GameContent.Skies.SolarSky.Activate (Vector2 position, params object[] args) inline
Definition at line 124 of file SolarSky.cs.
    {
        _fadeOpacity = 0.002f;
        _isActive = true;
        _meteors = new Meteor[150];
        for (int i = 0; i < _meteors.Length; i++)
        {
            float num = (float)i / (float)_meteors.Length;
            _meteors[i].Position.X = num * ((float)Main.maxTilesX * 16f) + _random.NextFloat() * 40f - 20f;
            _meteors[i].Position.Y = _random.NextFloat() * (0f - ((float)Main.worldSurface * 16f + 10000f)) - 10000f;
            if (_random.Next(3) != 0)
            {
                _meteors[i].Depth = _random.NextFloat() * 3f + 1.8f;
            }
            else
            {
                _meteors[i].Depth = _random.NextFloat() * 5f + 4.8f;
            }
            _meteors[i].FrameCounter = _random.Next(12);
            _meteors[i].Scale = _random.NextFloat() * 0.5f + 1f;
            _meteors[i].StartX = _meteors[i].Position.X;
        }
        Array.Sort(_meteors, SortMethod);
    }
References Terraria.GameContent.Skies.SolarSky._fadeOpacity, Terraria.GameContent.Skies.SolarSky._isActive, Terraria.GameContent.Skies.SolarSky._meteors, Terraria.GameContent.Skies.SolarSky._random, Terraria.GameContent.Skies.SolarSky.Meteor.Depth, Terraria.GameContent.Skies.SolarSky.Meteor.FrameCounter, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Skies.SolarSky.Meteor.Position, Terraria.GameContent.Skies.SolarSky.Meteor.Scale, System.Array.Sort(), Terraria.GameContent.Skies.SolarSky.SortMethod(), Terraria.GameContent.Skies.SolarSky.Meteor.StartX, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.