Terraria: System.Diagnostics.TagList.IndexOf
IndexOf() [1/2]
readonly int System.Diagnostics.TagList.IndexOf (KeyValuePair< string, object?> item) inline
Definition at line 442 of file TagList.cs.
    {
        if (_overflowTags != null)
        {
            for (int i = 0; i < _tagsCount; i++)
            {
                if (TagsEqual(_overflowTags[i], item))
                {
                    return i;
                }
            }
            return -1;
        }
        switch (_tagsCount)
        {
        case 1:
            if (TagsEqual(Tag1, item))
            {
                return 0;
            }
            break;
        case 2:
            if (TagsEqual(Tag1, item))
            {
                return 0;
            }
            if (TagsEqual(Tag2, item))
            {
                return 1;
            }
            break;
        case 3:
            if (TagsEqual(Tag1, item))
            {
                return 0;
            }
            if (TagsEqual(Tag2, item))
            {
                return 1;
            }
            if (TagsEqual(Tag3, item))
            {
                return 2;
            }
            break;
        case 4:
            if (TagsEqual(Tag1, item))
            {
                return 0;
            }
            if (TagsEqual(Tag2, item))
            {
                return 1;
            }
            if (TagsEqual(Tag3, item))
            {
                return 2;
            }
            if (TagsEqual(Tag4, item))
            {
                return 3;
            }
            break;
        case 5:
            if (TagsEqual(Tag1, item))
            {
                return 0;
            }
            if (TagsEqual(Tag2, item))
            {
                return 1;
            }
            if (TagsEqual(Tag3, item))
            {
                return 2;
            }
            if (TagsEqual(Tag4, item))
            {
                return 3;
            }
            if (TagsEqual(Tag5, item))
            {
                return 4;
            }
            break;
        case 6:
            if (TagsEqual(Tag1, item))
            {
                return 0;
            }
            if (TagsEqual(Tag2, item))
            {
                return 1;
            }
            if (TagsEqual(Tag3, item))
            {
                return 2;
            }
            if (TagsEqual(Tag4, item))
            {
                return 3;
            }
            if (TagsEqual(Tag5, item))
            {
                return 4;
            }
            if (TagsEqual(Tag6, item))
            {
                return 5;
            }
            break;
        case 7:
            if (TagsEqual(Tag1, item))
            {
                return 0;
            }
            if (TagsEqual(Tag2, item))
            {
                return 1;
            }
            if (TagsEqual(Tag3, item))
            {
                return 2;
            }
            if (TagsEqual(Tag4, item))
            {
                return 3;
            }
            if (TagsEqual(Tag5, item))
            {
                return 4;
            }
            if (TagsEqual(Tag6, item))
            {
                return 5;
            }
            if (TagsEqual(Tag7, item))
            {
                return 6;
            }
            break;
        case 8:
            if (TagsEqual(Tag1, item))
            {
                return 0;
            }
            if (TagsEqual(Tag2, item))
            {
                return 1;
            }
            if (TagsEqual(Tag3, item))
            {
                return 2;
            }
            if (TagsEqual(Tag4, item))
            {
                return 3;
            }
            if (TagsEqual(Tag5, item))
            {
                return 4;
            }
            if (TagsEqual(Tag6, item))
            {
                return 5;
            }
            if (TagsEqual(Tag7, item))
            {
                return 6;
            }
            if (TagsEqual(Tag8, item))
            {
                return 7;
            }
            break;
        }
        return -1;
    }
References System.Diagnostics.TagList._overflowTags, System.Diagnostics.TagList._tagsCount, System.item, System.Diagnostics.TagList.Tag1, System.Diagnostics.TagList.Tag2, System.Diagnostics.TagList.Tag3, System.Diagnostics.TagList.Tag4, System.Diagnostics.TagList.Tag5, System.Diagnostics.TagList.Tag6, System.Diagnostics.TagList.Tag7, System.Diagnostics.TagList.Tag8, and System.Diagnostics.TagList.TagsEqual().
Referenced by System.Diagnostics.TagList.Contains(), and System.Diagnostics.TagList.Remove().