Terraria: System.Runtime.Intrinsics.X86.Sse2.LoadVector128
LoadVector128() [6/10]
static unsafe Vector128< sbyte > System.Runtime.Intrinsics.X86.Sse2.LoadVector128 (sbyte * address) inline static inherited
Definition at line 582 of file Sse2.cs.
    {
        return LoadVector128(address);
    }
References System.Runtime.Intrinsics.X86.Sse2.LoadVector128().
Referenced by System.Collections.BitArray.BitArray(), System.Collections.BitArray.And(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeSsse3(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Intrinsified(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiChar_Sse2(), System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char_Sse2(), System.Text.Unicode.Utf8Utility.GetPointerToFirstInvalidByte(), System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidChar(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(), System.Text.Latin1Utility.NarrowUtf16ToLatin1_Sse2(), System.Collections.BitArray.Not(), System.Collections.BitArray.Or(), System.Buffers.Text.Base64.Ssse3Decode(), System.Buffers.Text.Base64.Ssse3Encode(), System.Text.ASCIIUtility.WidenAsciiToUtf16_Intrinsified(), System.Text.Latin1Utility.WidenLatin1ToUtf16_Sse2(), and System.Collections.BitArray.Xor().