Terraria: System.Runtime.Intrinsics.X86.Sse2.ConvertToUInt32
ConvertToUInt32()
static uint System.Runtime.Intrinsics.X86.Sse2.ConvertToUInt32 (Vector128< uint > value) inline static inherited
Definition at line 512 of file Sse2.cs.
    {
        return ConvertToUInt32(value);
    }
References System.Runtime.Intrinsics.X86.Sse2.ConvertToUInt32(), and System.value.
Referenced by System.Runtime.Intrinsics.X86.Sse2.ConvertToUInt32(), System.String.MakeSeparatorListVectorized(), System.Text.ASCIIUtility.NarrowFourUtf16CharsToAsciiAndWriteToBuffer(), System.Text.Latin1Utility.NarrowFourUtf16CharsToLatin1AndWriteToBuffer(), and System.Text.Unicode.Utf8Utility.TranscodeToUtf8().