Terraria: System.Runtime.Intrinsics.X86.Sse2.MoveScalar
MoveScalar() [1/4]
static Vector128< double > System.Runtime.Intrinsics.X86.Sse2.MoveScalar (Vector128< double > upper, Vector128< double > value) inline static inherited
Definition at line 767 of file Sse2.cs.
    {
        return MoveScalar(upper, value);
    }
References System.Runtime.Intrinsics.X86.Sse2.MoveScalar(), and System.value.
Referenced by System.Runtime.Intrinsics.Vector128< T >.CreateScalar(), System.Runtime.Intrinsics.X86.Sse2.MoveScalar(), System.Runtime.Intrinsics.X86.Sse2.MoveScalar(), and System.Runtime.Intrinsics.X86.Sse2.MoveScalar().