Terraria: System.Runtime.Intrinsics.X86.Sse2.Or
Or() [1/10]
static Vector128< byte > System.Runtime.Intrinsics.X86.Sse2.Or (Vector128< byte > left, Vector128< byte > right) inline static inherited
Definition at line 837 of file Sse2.cs.
    {
        return Or(left, right);
    }
References System.Runtime.Intrinsics.X86.Sse2.Or().
Referenced by System.Numerics.VectorMath.ConditionalSelectBitwise(), System.HexConverter.EncodeToUtf16_Ssse3(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiChar_Sse2(), System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char_Sse2(), System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidChar(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.String.MakeSeparatorListVectorized(), System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(), System.Text.Latin1Utility.NarrowUtf16ToLatin1_Sse2(), System.Collections.BitArray.Or(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse2.Or(), and System.Buffers.Text.Base64.Ssse3Encode().