Terraria: System.Runtime.Intrinsics.X86.Sse2.AddSaturate
AddSaturate() [2/4]
static Vector128< sbyte > System.Runtime.Intrinsics.X86.Sse2.AddSaturate (Vector128< sbyte > left, Vector128< sbyte > right) inline static inherited
Definition at line 112 of file Sse2.cs.
    {
        return AddSaturate(left, right);
    }
References System.Runtime.Intrinsics.X86.Sse2.AddSaturate().
Referenced by System.Runtime.Intrinsics.X86.Sse2.AddSaturate(), System.Runtime.Intrinsics.X86.Sse2.AddSaturate(), System.Runtime.Intrinsics.X86.Sse2.AddSaturate(), System.Runtime.Intrinsics.X86.Sse2.AddSaturate(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiChar_Sse2(), System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char_Sse2(), System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidChar(), System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(), and System.Text.Latin1Utility.NarrowUtf16ToLatin1_Sse2().