Terraria: System.Runtime.Intrinsics.X86.Sse2.MoveMask
MoveMask() [4/4]
static int System.Runtime.Intrinsics.X86.Sse2.MoveMask (Vector128< sbyte > value) inline static inherited
Definition at line 772 of file Sse2.cs.
    {
        return MoveMask(value);
    }
References System.Runtime.Intrinsics.X86.Sse2.MoveMask(), and System.value.
Referenced by System.Collections.BitArray.BitArray(), System.Runtime.Intrinsics.Vector128< T >.Equals(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeSsse3(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Intrinsified(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiChar_Sse2(), System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char_Sse2(), System.Text.Unicode.Utf8Utility.GetPointerToFirstInvalidByte(), System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidChar(), System.SpanHelpers.IndexOf(), System.SpanHelpers.IndexOf(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(), System.Text.Latin1Utility.NarrowUtf16ToLatin1_Sse2(), System.SpanHelpers.SequenceCompareTo(), System.SpanHelpers.SequenceEqual(), System.Buffers.Text.Base64.Ssse3Decode(), and System.Text.ASCIIUtility.WidenAsciiToUtf16_Intrinsified().