Terraria: System.Runtime.Intrinsics.X86.Sse2.AndNot
AndNot() [1/10]
static Vector128< byte > System.Runtime.Intrinsics.X86.Sse2.AndNot (Vector128< byte > left, Vector128< byte > right) inline static inherited
Definition at line 177 of file Sse2.cs.
    {
        return AndNot(left, right);
    }
References System.Runtime.Intrinsics.X86.Sse2.AndNot().
Referenced by System.Runtime.Intrinsics.X86.Sse2.AndNot(), System.Runtime.Intrinsics.X86.Sse2.AndNot(), System.Runtime.Intrinsics.X86.Sse2.AndNot(), System.Runtime.Intrinsics.X86.Sse2.AndNot(), System.Runtime.Intrinsics.X86.Sse2.AndNot(), System.Runtime.Intrinsics.X86.Sse2.AndNot(), System.Runtime.Intrinsics.X86.Sse2.AndNot(), System.Runtime.Intrinsics.X86.Sse2.AndNot(), System.Runtime.Intrinsics.X86.Sse2.AndNot(), and System.Numerics.VectorMath.ConditionalSelectBitwise().