Terraria: System.Runtime.Intrinsics.X86.Sse2.StoreAligned
StoreAligned() [6/10]
static unsafe void System.Runtime.Intrinsics.X86.Sse2.StoreAligned (sbyte * address, Vector128< sbyte > source) inline static inherited
Definition at line 1197 of file Sse2.cs.
    {
        StoreAligned(address, source);
    }
References System.source, and System.Runtime.Intrinsics.X86.Sse2.StoreAligned().
Referenced by System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(), System.Text.Latin1Utility.NarrowUtf16ToLatin1_Sse2(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Runtime.Intrinsics.X86.Sse2.StoreAligned(), System.Text.ASCIIUtility.WidenAsciiToUtf16_Intrinsified(), and System.Text.Latin1Utility.WidenLatin1ToUtf16_Sse2().