Terraria: System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical
ShiftRightLogical() [6/12]
static Vector128< short > System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical (Vector128< short > value, Vector128< short > count) inline static inherited
Definition at line 1057 of file Sse2.cs.
    {
        return ShiftRightLogical(value, count);
    }
References System.count, System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), and System.value.
Referenced by System.HexConverter.EncodeToUtf16_Ssse3(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeSsse3(), System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidChar(), System.String.MakeSeparatorListVectorized(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), and System.Buffers.Text.Base64.Ssse3Decode().