Terraria: System.Data.EnumerableRowCollection.GetLinqDataView
GetLinqDataView()
LinqDataView System.Data.EnumerableRowCollection< TRow >.GetLinqDataView () inline package inherited
Definition at line 89 of file EnumerableRowCollection.cs.
    {
        if (_table == null || !typeof(DataRow).IsAssignableFrom(typeof(TRow)))
        {
            throw DataSetUtil.NotSupported(System.SR.ToLDVUnsupported);
        }
        LinqDataView linqDataView = null;
        Func<DataRow, bool> finalPredicate = null;
        if (_selector != null && 0 < _listOfPredicates.Count)
        {
            finalPredicate = delegate(DataRow row)
            {
                if (row != (object)_selector((TRow)(object)row))
                {
                    throw DataSetUtil.NotSupported(System.SR.ToLDVUnsupported);
                }
                foreach (Func<TRow, bool> listOfPredicate in _listOfPredicates)
                {
                    if (!listOfPredicate((TRow)(object)row))
                    {
                        return false;
                    }
                }
                return true;
            };
        }
        else if (_selector != null)
        {
            finalPredicate = delegate(DataRow row)
            {
                if (row != (object)_selector((TRow)(object)row))
                {
                    throw DataSetUtil.NotSupported(System.SR.ToLDVUnsupported);
                }
                return true;
            };
        }
        else if (0 < _listOfPredicates.Count)
        {
            finalPredicate = delegate(DataRow row)
            {
                foreach (Func<TRow, bool> listOfPredicate2 in _listOfPredicates)
                {
                    if (!listOfPredicate2((TRow)(object)row))
                    {
                        return false;
                    }
                }
                return true;
            };
        }
        if (finalPredicate != null && 0 < _sortExpression.Count)
        {
            return new LinqDataView(_table, (DataRow row) => finalPredicate(row), (DataRow a, DataRow b) => _sortExpression.Compare(_sortExpression.Select((TRow)(object)a), _sortExpression.Select((TRow)(object)b)), (object key, DataRow row) => _sortExpression.Compare((List<object>)key, _sortExpression.Select((TRow)(object)row)), _sortExpression.CloneCast<DataRow>());
        }
        if (finalPredicate != null)
        {
            return new LinqDataView(_table, (DataRow row) => finalPredicate(row), null, null, _sortExpression.CloneCast<DataRow>());
        }
        if (0 < _sortExpression.Count)
        {
            return new LinqDataView(_table, null, (DataRow a, DataRow b) => _sortExpression.Compare(_sortExpression.Select((TRow)(object)a), _sortExpression.Select((TRow)(object)b)), (object key, DataRow row) => _sortExpression.Compare((List<object>)key, _sortExpression.Select((TRow)(object)row)), _sortExpression.CloneCast<DataRow>());
        }
        return new LinqDataView(_table, _sortExpression.CloneCast<DataRow>());
    }
References System.Data.EnumerableRowCollection< TRow >._listOfPredicates, System.Data.EnumerableRowCollection< TRow >._selector, System.Data.EnumerableRowCollection< TRow >._sortExpression, System.Data.EnumerableRowCollection< TRow >._table, System.Data.SortExpressionBuilder< T >.Compare(), System.Data.SortExpressionBuilder< T >.Count, System.Collections.Generic.List< T >.Count, System.key, DataSetUtil.NotSupported(), System.Data.SortExpressionBuilder< T >.Select(), and System.SR.ToLDVUnsupported.