Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteMemberObjectRef
WriteMemberObjectRef()
void System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteMemberObjectRef (NameInfo memberNameInfo, int idRef) inline package
Definition at line 447 of file BinaryFormatterWriter.cs.
    {
        InternalWriteItemNull();
        if (_memberReference == null)
        {
            _memberReference = new MemberReference();
        }
        _memberReference.Set(idRef);
        _memberReference.Write(this);
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._memberReference, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.MemberReference, System.Runtime.Serialization.Formatters.Binary.MemberReference.Set(), and System.Runtime.Serialization.Formatters.Binary.MemberReference.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteItemObjectRef(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteObjectRef().