Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteItemObjectRef
WriteItemObjectRef()
void System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteItemObjectRef (NameInfo nameInfo, int idRef) inline package
Definition at line 505 of file BinaryFormatterWriter.cs.
    {
        InternalWriteItemNull();
        WriteMemberObjectRef(nameInfo, idRef);
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.InternalWriteItemNull(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteMemberObjectRef().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember().