Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteObjectString
WriteObjectString()
void System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteObjectString (int objectId, string value) inline package
Definition at line 271 of file BinaryFormatterWriter.cs.
    {
        InternalWriteItemNull();
        if (_binaryObjectString == null)
        {
            _binaryObjectString = new BinaryObjectString();
        }
        _binaryObjectString.Set(objectId, value);
        _binaryObjectString.Write(this);
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._binaryObjectString, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectString.Set(), System.value, and System.Runtime.Serialization.Formatters.Binary.BinaryObjectString.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteMemberString().