Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.InternalWriteItemNull
InternalWriteItemNull()
void System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.InternalWriteItemNull () inline private
Definition at line 491 of file BinaryFormatterWriter.cs.
    {
        if (_consecutiveNullArrayEntryCount > 0)
        {
            if (_objectNull == null)
            {
                _objectNull = new ObjectNull();
            }
            _objectNull.SetNullCount(_consecutiveNullArrayEntryCount);
            _objectNull.Write(this);
            _consecutiveNullArrayEntryCount = 0;
        }
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._consecutiveNullArrayEntryCount, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._objectNull, System.Runtime.Serialization.Formatters.Binary.ObjectNull, System.Runtime.Serialization.Formatters.Binary.ObjectNull.SetNullCount(), and System.Runtime.Serialization.Formatters.Binary.ObjectNull.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteArrayAsBytes(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteAssembly(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteItem(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteItemEnd(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteItemObjectRef(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteJaggedArray(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteMember(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteMemberNested(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteMemberObjectRef(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteMemberString(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteNullItem(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteNullMember(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteObject(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteObjectByteArray(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteObjectString(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteRectangleArray(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteSingleArray().