Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue
WriteValue()
void System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue (InternalPrimitiveTypeE code, object value) inline package
Definition at line 529 of file BinaryFormatterWriter.cs.
    {
        switch (code)
        {
        case InternalPrimitiveTypeE.Boolean:
            WriteBoolean(Convert.ToBoolean(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.Byte:
            WriteByte(Convert.ToByte(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.Char:
            WriteChar(Convert.ToChar(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.Double:
            WriteDouble(Convert.ToDouble(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.Int16:
            WriteInt16(Convert.ToInt16(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.Int32:
            WriteInt32(Convert.ToInt32(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.Int64:
            WriteInt64(Convert.ToInt64(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.SByte:
            WriteSByte(Convert.ToSByte(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.Single:
            WriteSingle(Convert.ToSingle(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.UInt16:
            WriteUInt16(Convert.ToUInt16(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.UInt32:
            WriteUInt32(Convert.ToUInt32(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.UInt64:
            WriteUInt64(Convert.ToUInt64(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.Decimal:
            WriteDecimal(Convert.ToDecimal(value, CultureInfo.InvariantCulture));
            break;
        case InternalPrimitiveTypeE.TimeSpan:
            WriteTimeSpan((TimeSpan)value);
            break;
        case InternalPrimitiveTypeE.DateTime:
            WriteDateTime((DateTime)value);
            break;
        default:
            throw new SerializationException(System.SR.Format(System.SR.Serialization_TypeCode, code.ToString()));
        }
    }
References System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.SR.Serialization_TypeCode, System.Convert.ToBoolean(), System.Convert.ToByte(), System.Convert.ToChar(), System.Convert.ToDecimal(), System.Convert.ToDouble(), System.Convert.ToInt16(), System.Convert.ToInt32(), System.Convert.ToInt64(), System.Convert.ToSByte(), System.Convert.ToSingle(), System.Convert.ToUInt16(), System.Convert.ToUInt32(), System.Convert.ToUInt64(), System.value, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteBoolean(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteByte(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteChar(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteDateTime(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteDecimal(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteDouble(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteInt16(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteInt32(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteInt64(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteSByte(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteSingle(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteTimeSpan(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteUInt16(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteUInt32(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteUInt64().