Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteObject
WriteObject()
void System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteObject (NameInfo nameInfo, NameInfo typeNameInfo, int numMembers, string[] memberNames, Type[] memberTypes, WriteObjectInfo[] memberObjectInfos) inline package
Definition at line 213 of file BinaryFormatterWriter.cs.
    {
        InternalWriteItemNull();
        int num = (int)nameInfo._objectId;
        string text = ((num < 0) ? typeNameInfo.NIname : nameInfo.NIname);
        if (_objectMapTable == null)
        {
            _objectMapTable = new Dictionary<string, ObjectMapInfo>();
        }
        if (_objectMapTable.TryGetValue(text, out var value) && value.IsCompatible(numMembers, memberNames, memberTypes))
        {
            if (_binaryObject == null)
            {
                _binaryObject = new BinaryObject();
            }
            _binaryObject.Set(num, value._objectId);
            _binaryObject.Write(this);
            return;
        }
        int assemId;
        if (!typeNameInfo._transmitTypeOnObject)
        {
            if (_binaryObjectWithMap == null)
            {
                _binaryObjectWithMap = new BinaryObjectWithMap();
            }
            assemId = (int)typeNameInfo._assemId;
            _binaryObjectWithMap.Set(num, text, numMembers, memberNames, assemId);
            _binaryObjectWithMap.Write(this);
            if (value == null)
            {
                _objectMapTable.Add(text, new ObjectMapInfo(num, numMembers, memberNames, memberTypes));
            }
            return;
        }
        BinaryTypeEnum[] array = new BinaryTypeEnum[numMembers];
        object[] array2 = new object[numMembers];
        int[] array3 = new int[numMembers];
        for (int i = 0; i < numMembers; i++)
        {
            object typeInformation = null;
            array[i] = BinaryTypeConverter.GetBinaryTypeInfo(memberTypes[i], memberObjectInfos[i], null, _objectWriter, out typeInformation, out assemId);
            array2[i] = typeInformation;
            array3[i] = assemId;
        }
        if (_binaryObjectWithMapTyped == null)
        {
            _binaryObjectWithMapTyped = new BinaryObjectWithMapTyped();
        }
        assemId = (int)typeNameInfo._assemId;
        _binaryObjectWithMapTyped.Set(num, text, numMembers, memberNames, array, array2, array3, assemId);
        _binaryObjectWithMapTyped.Write(this);
        if (value == null)
        {
            _objectMapTable.Add(text, new ObjectMapInfo(num, numMembers, memberNames, memberTypes));
        }
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._binaryObject, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._binaryObjectWithMap, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._binaryObjectWithMapTyped, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._objectMapTable, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._objectWriter, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.GetBinaryTypeInfo(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.BinaryObject.Set(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.Set(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.Set(), System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, System.Runtime.Serialization.Formatters.Binary.BinaryObject.Write(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.Write(), and System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write().