Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteSingleArray
WriteSingleArray()
void System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteSingleArray (NameInfo memberNameInfo, NameInfo arrayNameInfo, WriteObjectInfo objectInfo, NameInfo arrayElemTypeNameInfo, int length, int lowerBound, Array array) inline package
Definition at line 282 of file BinaryFormatterWriter.cs.
    {
        InternalWriteItemNull();
        int[] lengthA = new int[1] { length };
        int[] lowerBoundA = null;
        object typeInformation = null;
        BinaryArrayTypeEnum binaryArrayTypeEnum;
        if (lowerBound == 0)
        {
            binaryArrayTypeEnum = BinaryArrayTypeEnum.Single;
        }
        else
        {
            binaryArrayTypeEnum = BinaryArrayTypeEnum.SingleOffset;
            lowerBoundA = new int[1] { lowerBound };
        }
        int assemId;
        BinaryTypeEnum binaryTypeInfo = BinaryTypeConverter.GetBinaryTypeInfo(arrayElemTypeNameInfo._type, objectInfo, arrayElemTypeNameInfo.NIname, _objectWriter, out typeInformation, out assemId);
        if (_binaryArray == null)
        {
            _binaryArray = new BinaryArray();
        }
        _binaryArray.Set((int)arrayNameInfo._objectId, 1, lengthA, lowerBoundA, binaryTypeInfo, typeInformation, binaryArrayTypeEnum, assemId);
        _binaryArray.Write(this);
        if (Converter.IsWriteAsByteArray(arrayElemTypeNameInfo._primitiveTypeEnum) && lowerBound == 0)
        {
            if (arrayElemTypeNameInfo._primitiveTypeEnum == InternalPrimitiveTypeE.Byte)
            {
                WriteBytes((byte[])array);
            }
            else if (arrayElemTypeNameInfo._primitiveTypeEnum == InternalPrimitiveTypeE.Char)
            {
                WriteChars((char[])array);
            }
            else
            {
                WriteArrayAsBytes(array, Converter.TypeLength(arrayElemTypeNameInfo._primitiveTypeEnum));
            }
        }
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._binaryArray, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._objectWriter, System.array, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.GetBinaryTypeInfo(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.Converter.IsWriteAsByteArray(), System.length, System.Runtime.Serialization.Formatters.Binary.BinaryArray.Set(), System.Runtime.Serialization.Formatters.Binary.Converter.TypeLength(), System.Runtime.Serialization.Formatters.Binary.BinaryArray.Write(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteArrayAsBytes(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteBytes(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteChars().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteObjectByteArray().