Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteAssembly
WriteAssembly()
void System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteAssembly (Type type, string assemblyString, int assemId, bool isNew) inline package
Definition at line 511 of file BinaryFormatterWriter.cs.
    {
        InternalWriteItemNull();
        if (assemblyString == null)
        {
            assemblyString = string.Empty;
        }
        if (isNew)
        {
            if (_binaryAssembly == null)
            {
                _binaryAssembly = new BinaryAssembly();
            }
            _binaryAssembly.Set(assemId, assemblyString);
            _binaryAssembly.Write(this);
        }
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._binaryAssembly, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.BinaryAssembly.Set(), and System.Runtime.Serialization.Formatters.Binary.BinaryAssembly.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId().