Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteMember
WriteMember()
void System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteMember (NameInfo memberNameInfo, NameInfo typeNameInfo, object value) inline package
Definition at line 408 of file BinaryFormatterWriter.cs.
    {
        InternalWriteItemNull();
        InternalPrimitiveTypeE primitiveTypeEnum = typeNameInfo._primitiveTypeEnum;
        if (memberNameInfo._transmitTypeOnMember)
        {
            if (_memberPrimitiveTyped == null)
            {
                _memberPrimitiveTyped = new MemberPrimitiveTyped();
            }
            _memberPrimitiveTyped.Set(primitiveTypeEnum, value);
            _memberPrimitiveTyped.Write(this);
        }
        else
        {
            if (_memberPrimitiveUnTyped == null)
            {
                _memberPrimitiveUnTyped = new MemberPrimitiveUnTyped();
            }
            _memberPrimitiveUnTyped.Set(primitiveTypeEnum, value);
            _memberPrimitiveUnTyped.Write(this);
        }
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._memberPrimitiveTyped, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter._memberPrimitiveUnTyped, System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.InternalWriteItemNull(), System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.Set(), System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.Set(), System.value, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.Write(), and System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.Write().
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteItem(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteKnownValueClass().