Terraria: UIImageFramed.SetFrame
SetFrame() [2/2]
void UIImageFramed.SetFrame (Rectangle frame) inline
     {
         _frame = frame;
         Width.Set(_frame.Width, 0f);
         Height.Set(_frame.Height, 0f);
     }
References _frame, UIElement.Height, StyleDimension.Set(), and UIElement.Width.
Referenced by UIManageControls.GamepadButtonClick(), UIManageControls.KeyboardButtonClick(), SetFrame(), UIAchievementListItem.UpdateIconFrame(), UICreativeInfiniteItemsDisplay.UpdateVisualFrame(), UICreativeItemsInfiniteFilteringOptions.UpdateVisuals(), UIManageControls.VsGameplayButtonClick(), and UIManageControls.VsMenuButtonClick().