Terraria: System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian
WriteInt32LittleEndian()
static void System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian (Span< byte > destination, int value) inline static
Definition at line 570 of file BinaryPrimitives.cs.
    {
        if (!BitConverter.IsLittleEndian)
        {
        }
        MemoryMarshal.Write(destination, ref value);
    }
References System.destination, System.BitConverter.IsLittleEndian, and System.value.
Referenced by System.Reflection.Emit.ILGenerator.BakeByteArray(), System.Collections.BitArray.CopyTo(), System.Reflection.Emit.ILGenerator.Emit(), System.Decimal.GetBytes(), System.Reflection.Emit.ILGenerator.PutInteger4(), and System.IO.BinaryWriter.Write().