Terraria: System.Xml.Schema.RangeContentValidator.InitValidation
InitValidation()
override void System.Xml.Schema.RangeContentValidator.InitValidation (ValidationState context) inline virtual
Reimplemented from System.Xml.Schema.ContentValidator.
Definition at line 34 of file RangeContentValidator.cs.
    {
        List<RangePositionInfo> list = context.RunningPositions;
        if (list == null)
        {
            list = (context.RunningPositions = new List<RangePositionInfo>());
        }
        else
        {
            list.Clear();
        }
        RangePositionInfo item = default(RangePositionInfo);
        item.curpos = _firstpos.Clone();
        item.rangeCounters = new decimal[_minMaxNodesCount];
        list.Add(item);
        context.CurrentState.NumberOfRunningPos = 1;
        context.HasMatched = item.curpos.Get(_endMarkerPos);
    }
References System.Xml.Schema.RangeContentValidator._endMarkerPos, System.Xml.Schema.RangeContentValidator._firstpos, System.Xml.Schema.RangeContentValidator._minMaxNodesCount, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Xml.Schema.BitSet.Clone(), System.Xml.Dictionary, System.Xml.Schema.BitSet.Get(), System.item, System.list, and System.Xml.Schema.ValidationState.RunningPositions.