Terraria: System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian
WriteInt32BigEndian()
static void System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian (Span< byte > destination, int value) inline static
Definition at line 417 of file BinaryPrimitives.cs.
    {
        _ = BitConverter.IsLittleEndian;
        value = ReverseEndianness(value);
        MemoryMarshal.Write(destination, ref value);
    }
References System.destination, System.BitConverter.IsLittleEndian, System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), and System.value.
Referenced by System.Reflection.Emit.SignatureHelper.AddData(), System.Security.Cryptography.RsaPaddingProcessor.Mgf1(), System.Net.Http.Http2Connection.SendRstStreamAsync(), System.Net.Http.Http2Connection.SendWindowUpdateAsync(), System.Security.Cryptography.XmlKeyHelper.WriteCryptoBinary(), and System.Net.Http.Http2Connection.FrameHeader.WriteTo().