Terraria: System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian
ReadInt32LittleEndian()
static int System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian (ReadOnlySpan< byte > source) inline static
Definition at line 262 of file BinaryPrimitives.cs.
    {
        int result = MemoryMarshal.Read<int>(source);
        if (!BitConverter.IsLittleEndian)
        {
        }
        return result;
    }
References System.BitConverter.IsLittleEndian, and System.source.
Referenced by System.Collections.BitArray.BitArray(), System.Diagnostics.Tracing.EventPipePayloadDecoder.DecodePayload(), System.Net.Internals.SocketAddress.GetHashCode(), System.Net.NetworkInformation.PhysicalAddress.GetHashCode(), System.Net.SocketAddress.GetHashCode(), System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.GetInt32(), System.Xml.XmlSqlBinaryReader.GetInt32(), Internal.NativeCrypto.CapiHelper.GetKeyPairHelper(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadSingle(), System.Resources.ResourceReader.ReadUnalignedI4(), System.Decimal.ToDecimal(), System.Buffers.Text.Utf8Parser.TryParse(), and System.Buffers.Text.Utf8Parser.TryParseAsSpecialFloatingPoint< T >().