Terraria: System.Xml.Schema.RangeContentValidator.ExpectedElements
ExpectedElements()
override ArrayList System.Xml.Schema.RangeContentValidator.ExpectedElements (ValidationState context, bool isRequiredOnly) inline virtual
Reimplemented from System.Xml.Schema.ContentValidator.
Definition at line 199 of file RangeContentValidator.cs.
    {
        ArrayList arrayList = null;
        if (context.RunningPositions != null)
        {
            List<RangePositionInfo> runningPositions = context.RunningPositions;
            BitSet bitSet = new BitSet(_positions.Count);
            for (int num = context.CurrentState.NumberOfRunningPos - 1; num >= 0; num--)
            {
                bitSet.Or(runningPositions[num].curpos);
            }
            for (int num2 = bitSet.NextSet(-1); num2 != -1; num2 = bitSet.NextSet(num2))
            {
                if (arrayList == null)
                {
                    arrayList = new ArrayList();
                }
                int symbol = _positions[num2].symbol;
                if (symbol >= 0)
                {
                    if (!(_positions[num2].particle is XmlSchemaParticle xmlSchemaParticle))
                    {
                        string text = _symbols.NameOf(_positions[num2].symbol);
                        if (text.Length != 0)
{
                            arrayList.Add(text);
                        }
                    }
                    else
                    {
                        string nameString = xmlSchemaParticle.NameString;
                        if (!arrayList.Contains(nameString))
{
                            arrayList.Add(nameString);
                        }
                    }
                }
            }
        }
        return arrayList;
    }
References System.Xml.Schema.RangeContentValidator._positions, System.Xml.Schema.RangeContentValidator._symbols, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Xml.Schema.Positions.Count, System.Xml.Schema.ValidationState.CurrentState, System.Xml.Dictionary, System.Xml.Schema.SymbolsDictionary.NameOf(), System.Xml.Schema.StateUnion.NumberOfRunningPos, System.Xml.Schema.ValidationState.RunningPositions, and System.text.