Terraria: Terraria.GameContent.ItemDropRules.OneFromRulesRule.ReportDroprates
ReportDroprates()
void Terraria.GameContent.ItemDropRules.OneFromRulesRule.ReportDroprates (List< DropRateInfo > drops, DropRateInfoChainFeed ratesInfo) inline
Implements Terraria.GameContent.ItemDropRules.IItemDropRule.
    {
        float num = 1f / (float)chanceDenominator;
        float num2 = num * ratesInfo.parentDroprateChance;
        float multiplier = 1f / (float)options.Length * num2;
        for (int i = 0; i < options.Length; i++)
        {
            options[i].ReportDroprates(drops, ratesInfo.With(multiplier));
        }
        Chains.ReportDroprates(ChainedRules, num, drops, ratesInfo);
    }
References Terraria.GameContent.ItemDropRules.OneFromRulesRule.ChainedRules, Terraria.GameContent.ItemDropRules.OneFromRulesRule.chanceDenominator, Terraria.GameContent.ItemDropRules.OneFromRulesRule.options, Terraria.GameContent.ItemDropRules.DropRateInfoChainFeed.parentDroprateChance, Terraria.GameContent.ItemDropRules.IItemDropRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.Chains.ReportDroprates(), and Terraria.GameContent.ItemDropRules.DropRateInfoChainFeed.With().