Terraria: System.Xml.Xsl.Xslt.AstFactory.XslNode
XslNode()
static XslNode System.Xml.Xsl.Xslt.AstFactory.XslNode (XslNodeType nodeType, QilName name, string arg, XslVersion xslVer) inline static
Definition at line 9 of file AstFactory.cs.
    {
        return new XslNode(nodeType, name, arg, xslVer);
    }
References System.Xml.Dictionary, and System.Xml.Xsl.Xslt.AstFactory.XslNode().
Referenced by System.Xml.Xsl.Xslt.AstFactory.ApplyImports(), System.Xml.Xsl.Xslt.AstFactory.Choose(), System.Xml.Xsl.Xslt.AstFactory.Comment(), System.Xml.Xsl.Xslt.AstFactory.Copy(), System.Xml.Xsl.Xslt.AstFactory.CopyOf(), System.Xml.Xsl.Xslt.AstFactory.Error(), System.Xml.Xsl.Xslt.AstFactory.If(), System.Xml.Xsl.Xslt.AstFactory.List(), System.Xml.Xsl.Xslt.AstFactory.LiteralAttribute(), System.Xml.Xsl.Xslt.AstFactory.LiteralElement(), System.Xml.Xsl.Xslt.AstFactory.Message(), System.Xml.Xsl.Xslt.AstFactory.Nop(), System.Xml.Xsl.Xslt.AstFactory.Otherwise(), System.Xml.Xsl.Xslt.AstFactory.PI(), System.Xml.Xsl.Xslt.AstFactory.UseAttributeSet(), System.Xml.Xsl.Xslt.AstFactory.XslNode(), and System.Xml.Xsl.Xslt.XsltLoader.XslValueOf().