Terraria: WorldSections.SetTilesLoaded
SetTilesLoaded()
void WorldSections.SetTilesLoaded (int startX, int startY, int endXInclusive, int endYInclusive) inline
     {
         int sectionX = Netplay.GetSectionX(startX);
         int sectionY = Netplay.GetSectionY(startY);
         int sectionX2 = Netplay.GetSectionX(endXInclusive);
         int sectionY2 = Netplay.GetSectionY(endYInclusive);
         for (int i = sectionX; i <= sectionX2; i++)
         {
             for (int j = sectionY; j <= sectionY2; j++)
             {
                 SetSectionLoaded(i, j);
             }
         }
     }
References Netplay.GetSectionX(), Netplay.GetSectionY(), and SetSectionLoaded().
Referenced by NetMessage.DecompressTileBlock_Inner().