Terraria: WorldSections.GetNextMapDraw
GetNextMapDraw()
bool WorldSections.GetNextMapDraw (Vector2 playerPos, out int x, out int y) inline
     {
         if (mapSectionsLeft <= 0)
         {
             x = -1;
             y = -1;
             return false;
         }
         Stopwatch stopwatch = new Stopwatch();
         stopwatch.Start();
         int num = 0;
         int num2 = 0;
         Vector2 vector = prevMap.centerPos;
         playerPos *= 0.0625f;
         int sectionX = Netplay.GetSectionX((int)playerPos.X);
         int sectionY = Netplay.GetSectionY((int)playerPos.Y);
         int num3 = Netplay.GetSectionX((int)vector.X);
         int num4 = Netplay.GetSectionY((int)vector.Y);
         int num5;
         if (num3 != sectionX || num4 != sectionY)
         {
             vector = playerPos;
             num3 = sectionX;
             num4 = sectionY;
             num5 = 4;
             x = sectionX;
             y = sectionY;
         }
         else
         {
             num5 = prevMap.leg;
             x = prevMap.X;
             y = prevMap.Y;
             num = prevMap.xDir;
             num2 = prevMap.yDir;
         }
         int num6 = (int)(playerPos.X - ((float)num3 + 0.5f) * 200f);
         int num7 = (int)(playerPos.Y - ((float)num4 + 0.5f) * 150f);
         if (num == 0)
         {
             num = ((num6 <= 0) ? 1 : (-1));
             num2 = ((num7 <= 0) ? 1 : (-1));
         }
         int num8 = 0;
         bool flag = false;
         bool flag2 = false;
         while (true)
         {
             if (num8 == 4)
             {
                 if (flag2)
                 {
                     throw new Exception("Infinite loop in WorldSections.GetNextMapDraw");
                 }
                 flag2 = true;
                 x = num3;
                 y = num4;
                 num6 = (int)(vector.X - ((float)num3 + 0.5f) * 200f);
                 num7 = (int)(vector.Y - ((float)num4 + 0.5f) * 150f);
                 num = ((num6 <= 0) ? 1 : (-1));
                 num2 = ((num7 <= 0) ? 1 : (-1));
                 num5 = 4;
                 num8 = 0;
             }
             if (y >= 0 && y < height && x >= 0 && x < width)
             {
                 flag = false;
                 if (!data[y * width + x][2])
                 {
                     break;
                 }
             }
             int num9 = x - num3;
             int num10 = y - num4;
             if (num9 == 0 || num10 == 0)
             {
                 if (num5 == 4)
                 {
                     if (num9 == 0 && num10 == 0)
                     {
                         if (Math.Abs(num6) > Math.Abs(num7))
{
                             y -= num2;
                         }
                         else
{
                             x -= num;
                         }
                     }
                     else
                     {
                         if (num9 != 0)
{
                             x += num9 / Math.Abs(num9);
                         }
                         if (num10 != 0)
{
                             y += num10 / Math.Abs(num10);
                         }
                     }
                     num5 = 0;
                     num8 = -2;
                     flag = true;
                 }
                 else
                 {
                     if (num9 != 0)
                     {
                         num = ((num9 <= 0) ? 1 : (-1));
                     }
                     else
                     {
                         num2 = ((num10 <= 0) ? 1 : (-1));
                     }
                     x += num;
                     y += num2;
                     num5++;
                 }
                 if (flag)
                 {
                     num8++;
                 }
                 else
                 {
                     flag = true;
                 }
             }
             else
             {
                 x += num;
                 y += num2;
             }
         }
         data[y * width + x][2] = true;
         mapSectionsLeft--;
         prevMap.centerPos = playerPos;
         prevMap.X = x;
         prevMap.Y = y;
         prevMap.leg = num5;
         prevMap.xDir = num;
         prevMap.yDir = num2;
         stopwatch.Stop();
         return true;
     }
References WorldSections.IterationState.centerPos, data, Netplay.GetSectionX(), Netplay.GetSectionY(), WorldSections.IterationState.leg, mapSectionsLeft, prevMap, width, WorldSections.IterationState.X, WorldSections.IterationState.xDir, WorldSections.IterationState.Y, and WorldSections.IterationState.yDir.
Referenced by Main.DoDraw().