Terraria: System.Text.Decoder.Convert
Convert() [2/3]
virtual void System.Text.Decoder.Convert (byte[] bytes, int byteIndex, int byteCount, char[] chars, int charIndex, int charCount, bool flush, out int bytesUsed, out int charsUsed, out bool completed) inline virtual inherited
Reimplemented in System.Text.DecoderDBCS, System.Text.DecoderDBCS, System.Text.DecoderNLS, System.Xml.SafeAsciiDecoder, System.Xml.Ucs4Decoder, System.Xml.UTF16Decoder, and System.Text.DecoderNLS.
Definition at line 142 of file Decoder.cs.
    {
        if (bytes == null || chars == null)
        {
            throw new ArgumentNullException((bytes == null) ? "bytes" : "chars", SR.ArgumentNull_Array);
        }
        if (byteIndex < 0 || byteCount < 0)
        {
            throw new ArgumentOutOfRangeException((byteIndex < 0) ? "byteIndex" : "byteCount", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (charIndex < 0 || charCount < 0)
        {
            throw new ArgumentOutOfRangeException((charIndex < 0) ? "charIndex" : "charCount", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (bytes.Length - byteIndex < byteCount)
        {
            throw new ArgumentOutOfRangeException("bytes", SR.ArgumentOutOfRange_IndexCountBuffer);
        }
        if (chars.Length - charIndex < charCount)
        {
            throw new ArgumentOutOfRangeException("chars", SR.ArgumentOutOfRange_IndexCountBuffer);
        }
        for (bytesUsed = byteCount; bytesUsed > 0; bytesUsed /= 2)
        {
            if (GetCharCount(bytes, byteIndex, bytesUsed, flush) <= charCount)
            {
                charsUsed = GetChars(bytes, byteIndex, bytesUsed, chars, charIndex, flush);
                completed = bytesUsed == byteCount && (_fallbackBuffer == null || _fallbackBuffer.Remaining == 0);
                return;
            }
            flush = false;
        }
        throw new ArgumentException(SR.Argument_ConversionOverflow);
    }
References System.Text.Decoder._fallbackBuffer, System.SR.Argument_ConversionOverflow, System.SR.ArgumentNull_Array, System.SR.ArgumentOutOfRange_IndexCountBuffer, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.byteCount, System.byteIndex, System.bytes, System.charCount, System.charIndex, System.chars, System.Text.Decoder.GetCharCount(), and System.Text.Decoder.GetChars().
Referenced by System.Text.Decoder.Convert(), System.Text.EncodingExtensions.Convert(), System.Text.EncodingExtensions.Convert(), System.Xml.XmlTextReaderImpl.GetChars(), System.Xml.XmlTextReaderImpl.InvalidCharRecovery(), System.Text.TranscodingStream.Write(), and System.Text.TranscodingStream.WriteAsync().