Terraria: System.Globalization.SurrogateCasing.ToUpper
ToUpper()
static void System.Globalization.SurrogateCasing.ToUpper (char h, char l, out char hr, out char lr) inline static package
Definition at line 9 of file SurrogateCasing.cs.
    {
        UnicodeUtility.GetUtf16SurrogatesFromSupplementaryPlaneScalar(CharUnicodeInfo.ToUpper(UnicodeUtility.GetScalarFromUtf16SurrogatePair(h, l)), out hr, out lr);
    }
References System.Text.UnicodeUtility.GetScalarFromUtf16SurrogatePair(), System.Text.UnicodeUtility.GetUtf16SurrogatesFromSupplementaryPlaneScalar(), and System.Globalization.CharUnicodeInfo.ToUpper().
Referenced by System.Globalization.TextInfo.AddTitlecaseLetter(), System.Globalization.SurrogateCasing.Equal(), System.Globalization.CompareInfo.InvariantCreateSortKeyOrdinalIgnoreCase(), System.Globalization.InvariantModeCasing.ToUpper(), System.Globalization.InvariantModeCasing.ToUpper(), and System.Globalization.OrdinalCasing.ToUpperOrdinal().