Terraria: System.Globalization.SurrogateCasing.Equal
Equal()
static bool System.Globalization.SurrogateCasing.Equal (char h1, char l1, char h2, char l2) inline static package
Definition at line 21 of file SurrogateCasing.cs.
    {
        ToUpper(h1, l1, out var hr, out var lr);
        ToUpper(h2, l2, out var hr2, out var lr2);
        if (hr == hr2)
        {
            return lr == lr2;
        }
        return false;
    }
References System.Globalization.SurrogateCasing.ToUpper().
Referenced by System.Globalization.OrdinalCasing.IndexOf(), System.Globalization.InvariantModeCasing.IndexOfIgnoreCase(), System.Globalization.OrdinalCasing.LastIndexOf(), and System.Globalization.InvariantModeCasing.LastIndexOfIgnoreCase().