Terraria: System.Text.Decoder.GetChars
GetChars() [2/4]
int System.Text.Decoder.GetChars (byte[] bytes, int byteIndex, int byteCount, char[] chars, int charIndex) abstract
Referenced by System.Text.Decoder.Convert(), System.Text.Decoder.Convert(), System.Text.TranscodingStream.FinalFlushWriteBuffers(), System.Text.Decoder.GetChars(), System.Text.Decoder.GetChars(), System.Text.Decoder.GetChars(), System.Text.EncodingExtensions.GetChars(), System.Text.EncodingExtensions.GetString(), System.IO.BinaryReader.InternalReadChars(), System.IO.BinaryReader.Read(), System.Text.TranscodingStream.Read(), System.Text.TranscodingStream.ReadAsync(), System.IO.StreamReader.ReadAsyncInternal(), System.IO.StreamReader.ReadBuffer(), System.IO.StreamReader.ReadBuffer(), System.Diagnostics.AsyncStreamReader.ReadBufferAsync(), System.IO.StreamReader.ReadBufferAsync(), System.IO.BinaryReader.ReadString(), System.Net.CommandStream.ReceiveCommandResponseCallback(), System.Text.Decoder.Reset(), System.Xml.ValueHandle.TryReadChars(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Write(), and System.Xml.EncodingStreamWrapper.Write().