Terraria: System.Threading.ThreadPoolBoundHandle.BindHandle
BindHandle()
static ThreadPoolBoundHandle System.Threading.ThreadPoolBoundHandle.BindHandle (SafeHandle handle) inline static
Definition at line 18 of file ThreadPoolBoundHandle.cs.
    {
        if (handle == null)
        {
            throw new ArgumentNullException("handle");
        }
        if (handle.IsClosed || handle.IsInvalid)
        {
            throw new ArgumentException(SR.Argument_InvalidHandle, "handle");
        }
        return BindHandleCore(handle);
    }
References System.SR.Argument_InvalidHandle, System.Threading.ThreadPoolBoundHandle.BindHandleCore(), and System.handle.
Referenced by System.Net.Sockets.SafeSocketHandle.GetOrAllocateThreadPoolBoundHandle(), System.IO.Pipes.PipeStream.InitializeAsyncHandle(), Microsoft.Win32.SafeHandles.SafeFileHandle.InitThreadPoolBinding(), and System.IO.FileSystemWatcher.StartRaisingEvents().