Terraria: TeleportPylonsSystem.SpawnInWorldDust
SpawnInWorldDust()
static void TeleportPylonsSystem.SpawnInWorldDust (int tileStyle, Rectangle dustBox) inline static
     {
         float r = 1f;
         float g = 1f;
         float b = 1f;
         switch ((TeleportPylonType)(byte)tileStyle)
         {
         case TeleportPylonType.SurfacePurity:
             r = 0.05f;
             g = 0.8f;
             b = 0.3f;
             break;
         case TeleportPylonType.Jungle:
             r = 0.7f;
             g = 0.8f;
             b = 0.05f;
             break;
         case TeleportPylonType.Hallow:
             r = 0.5f;
             g = 0.3f;
             b = 0.7f;
             break;
         case TeleportPylonType.Underground:
             r = 0.4f;
             g = 0.4f;
             b = 0.6f;
             break;
         case TeleportPylonType.Beach:
             r = 0.2f;
             g = 0.2f;
             b = 0.95f;
             break;
         case TeleportPylonType.Desert:
             r = 0.85f;
             g = 0.45f;
             b = 0.1f;
             break;
         case TeleportPylonType.Snow:
             r = 1f;
             g = 1f;
             b = 1.2f;
             break;
         case TeleportPylonType.GlowingMushroom:
             r = 0.4f;
             g = 0.7f;
             b = 1.2f;
             break;
         case TeleportPylonType.Victory:
             r = 0.7f;
             g = 0.7f;
             b = 0.7f;
             break;
         }
         int num = Dust.NewDust(dustBox.TopLeft(), dustBox.Width, dustBox.Height, 43, 0f, 0f, 254, new Color(r, g, b, 1f), 0.5f);
         Main.dust[num].velocity *= 0.1f;
         Main.dust[num].velocity.Y -= 0.2f;
     }
References Color, Main.dust, Dust.NewDust(), and Dust.velocity.
Referenced by TileDrawing.DrawTeleportationPylons(), Main.TeleportEffect(), and Player.UpdateTeleportVisuals().