Terraria: System.Threading.ThreadPoolBoundHandle.FreeNativeOverlapped
FreeNativeOverlapped()
unsafe void System.Threading.ThreadPoolBoundHandle.FreeNativeOverlapped (NativeOverlapped * overlapped) inline
Definition at line 82 of file ThreadPoolBoundHandle.cs.
    {
        if (overlapped == null)
        {
            throw new ArgumentNullException("overlapped");
        }
        ThreadPoolBoundHandleOverlapped overlappedWrapper = GetOverlappedWrapper(overlapped);
        if (overlappedWrapper._boundHandle != this)
        {
            throw new ArgumentException(SR.Argument_NativeOverlappedWrongBoundHandle, "overlapped");
        }
        if (overlappedWrapper._preAllocated != null)
        {
            overlappedWrapper._preAllocated.Release();
        }
        else
        {
            Overlapped.Free(overlapped);
        }
    }
References System.Threading.ThreadPoolBoundHandleOverlapped._boundHandle, System.Threading.ThreadPoolBoundHandleOverlapped._preAllocated, System.SR.Argument_NativeOverlappedWrongBoundHandle, System.Threading.Overlapped.Free(), System.Threading.ThreadPoolBoundHandle.GetOverlappedWrapper(), and System.Threading.PreAllocatedOverlapped.Release().
Referenced by System.Net.ListenerClientCertAsyncResult.~ListenerClientCertAsyncResult(), System.Net.AsyncRequestContext.Allocate(), System.Net.HttpRequestStream.HttpRequestStreamAsyncResult.Cleanup(), System.Net.HttpResponseStreamAsyncResult.Cleanup(), System.Net.ListenerClientCertAsyncResult.Cleanup(), System.Net.AsyncRequestContext.Dispose(), System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlapped(), System.IO.RandomAccess.CallbackResetEvent.FreeNativeOverlapped(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.FreeOverlapped(), System.Net.AsyncRequestContext.OnReleasePins(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.ReleaseNativeResource(), System.IO.Pipes.PipeStream.PipeValueTaskSource.ReleaseResources(), Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.ReleaseResources(), and System.Net.ListenerClientCertAsyncResult.Reset().