Terraria: System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState
GetNativeOverlappedState()
static unsafe? object System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState (NativeOverlapped * overlapped) inline static
Definition at line 104 of file ThreadPoolBoundHandle.cs.
    {
        if (overlapped == null)
        {
            throw new ArgumentNullException("overlapped");
        }
        ThreadPoolBoundHandleOverlapped overlappedWrapper = GetOverlappedWrapper(overlapped);
        return overlappedWrapper._userState;
    }
References System.Threading.ThreadPoolBoundHandleOverlapped._userState, and System.Threading.ThreadPoolBoundHandle.GetOverlappedWrapper().
Referenced by System.IO.RandomAccess.AllocateCallback(), System.Net.HttpRequestStream.HttpRequestStreamAsyncResult.Callback(), System.Net.HttpResponseStreamAsyncResult.Callback(), System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.IOCallback(), System.IO.Pipes.PipeStream.PipeValueTaskSource.IOCallback(), Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.IOCallback(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.IOCallback(), System.IO.FileSystemWatcher.StartRaisingEvents(), System.Net.HttpListener.DisconnectAsyncResult.WaitCallback(), System.Net.ListenerAsyncResult.WaitCallback(), and System.Net.ListenerClientCertAsyncResult.WaitCallback().