Terraria: System.Threading.ThreadPoolBoundHandle.AllocateNativeOverlapped
AllocateNativeOverlapped() [3/3]
unsafe NativeOverlapped * System.Threading.ThreadPoolBoundHandle.AllocateNativeOverlapped (PreAllocatedOverlapped preAllocated) inline
Definition at line 56 of file ThreadPoolBoundHandle.cs.
    {
        if (preAllocated == null)
        {
            throw new ArgumentNullException("preAllocated");
        }
        EnsureNotDisposed();
        preAllocated.AddRef();
        try
        {
            ThreadPoolBoundHandleOverlapped overlapped = preAllocated._overlapped;
            if (overlapped._boundHandle != null)
            {
                throw new ArgumentException(SR.Argument_PreAllocatedAlreadyAllocated, "preAllocated");
            }
            overlapped._boundHandle = this;
            return overlapped._nativeOverlapped;
        }
        catch
        {
            preAllocated.Release();
            throw;
        }
    }
References System.Threading.ThreadPoolBoundHandleOverlapped._boundHandle, System.Threading.ThreadPoolBoundHandleOverlapped._nativeOverlapped, System.Threading.PreAllocatedOverlapped._overlapped, System.Threading.PreAllocatedOverlapped.AddRef(), System.SR.Argument_PreAllocatedAlreadyAllocated, System.Threading.ThreadPoolBoundHandle.EnsureNotDisposed(), and System.Threading.PreAllocatedOverlapped.Release().