Terraria: Terraria.Map.MapTile.Equals
Equals()
bool Terraria.Map.MapTile.Equals (ref MapTile other) inline
Definition at line 49 of file MapTile.cs.
    {
        if (Light == other.Light && Type == other.Type)
        {
            return Color == other.Color;
        }
        return false;
    }
References Terraria.Map.MapTile.Color, and Terraria.Map.MapTile.Type.
Referenced by Terraria.Map.MapHelper.InternalSaveMap(), Terraria.Map.WorldMap.UpdateLighting(), and Terraria.Map.WorldMap.UpdateType().