Terraria: UIHairStyleButton.DrawSelf
DrawSelf()
override void UIHairStyleButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         if (_hovered)
         {
             if (!_soundedHover)
             {
                 SoundEngine.PlaySound(12);
             }
             _soundedHover = true;
         }
         else
         {
             _soundedHover = false;
         }
         Vector2 vector = new Vector2(-5f, -5f);
         base.DrawSelf(spriteBatch);
         if (_player.hair == HairStyleId)
         {
             spriteBatch.Draw(_selectedBorderTexture.Value, GetDimensions().Center() - _selectedBorderTexture.Size() / 2f, Color.White);
         }
         if (_hovered)
         {
             spriteBatch.Draw(_hoveredBorderTexture.Value, GetDimensions().Center() - _hoveredBorderTexture.Size() / 2f, Color.White);
         }
         if (_framesToSkip > 0)
         {
             _framesToSkip--;
             return;
         }
         int hair = _player.hair;
         _player.hair = HairStyleId;
         Main.PlayerRenderer.DrawPlayerHead(Main.Camera, _player, GetDimensions().Center() + vector);
         _player.hair = hair;
     }
References _framesToSkip, _hovered, _hoveredBorderTexture, _player, _selectedBorderTexture, _soundedHover, Main.Camera, Color, IPlayerRenderer.DrawPlayerHead(), UIElement.GetDimensions(), Player.hair, HairStyleId, Main.PlayerRenderer, SoundEngine.PlaySound(), and Asset< T >.Value.