Terraria: System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.MoveNext
MoveNext()
bool System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.MoveNext () inline
Definition at line 24 of file XPathPrecedingDocOrderIterator.cs.
    {
        if (!_navStack.IsEmpty)
        {
            do
            {
                if (_filter.MoveToFollowing(_navCurrent, _navStack.Peek()))
                {
                    return true;
                }
                _navCurrent.MoveTo(_navStack.Pop());
            }
            while (!_navStack.IsEmpty);
        }
        return false;
    }
References System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator._filter, System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator._navCurrent, System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator._navStack, System.Xml.Xsl.Runtime.XmlNavigatorStack.IsEmpty, System.Xml.XPath.XPathNavigator.MoveTo(), System.Xml.Xsl.Runtime.XmlNavigatorFilter.MoveToFollowing(), System.Xml.Xsl.Runtime.XmlNavigatorStack.Peek(), and System.Xml.Xsl.Runtime.XmlNavigatorStack.Pop().