Terraria: System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.Create
Create()
void System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.Create (XPathNavigator input, XmlNavigatorFilter filter) inline
Definition at line 17 of file XPathPrecedingDocOrderIterator.cs.
    {
        _navCurrent = XmlQueryRuntime.SyncToNavigator(_navCurrent, input);
        _filter = filter;
        PushAncestors();
    }
References System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator._filter, System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator._navCurrent, System.Xml.Dictionary, System.input, System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.PushAncestors(), and System.Xml.Xsl.Runtime.XmlQueryRuntime.SyncToNavigator().
Referenced by System.Xml.Xsl.Runtime.XPathPrecedingIterator.Create().