Terraria: PlayerDrawLayers.DrawPlayer_12_Skin_Composite
DrawPlayer_12_Skin_Composite()
static void PlayerDrawLayers.DrawPlayer_12_Skin_Composite (ref PlayerDrawSet drawinfo) inline static
     {
         if (!drawinfo.hidesTopSkin && !drawinfo.drawPlayer.invis)
         {
             Vector2 vector = new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2);
             vector.Y += drawinfo.torsoOffset;
             Vector2 vector2 = Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height];
             vector2.Y -= 2f;
             vector += vector2 * -drawinfo.playerEffect.HasFlag(SpriteEffects.FlipVertically).ToDirectionInt();
             float bodyRotation = drawinfo.drawPlayer.bodyRotation;
             Vector2 vector3 = vector;
             Vector2 vector4 = vector;
             Vector2 bodyVect = drawinfo.bodyVect;
             Vector2 bodyVect2 = drawinfo.bodyVect;
             Vector2 compositeOffset_BackArm = GetCompositeOffset_BackArm(ref drawinfo);
             vector3 += compositeOffset_BackArm;
             _ = bodyVect + compositeOffset_BackArm;
             Vector2 compositeOffset_FrontArm = GetCompositeOffset_FrontArm(ref drawinfo);
             bodyVect2 += compositeOffset_FrontArm;
             _ = vector4 + compositeOffset_FrontArm;
             if (drawinfo.drawFloatingTube)
             {
                 drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Extra[105].Value, vector, new Rectangle(0, 0, 40, 56), drawinfo.floatingTubeColor, bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect)
                 {
                     shader = drawinfo.cFloatingTube
                 });
             }
             drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 3].Value, vector, drawinfo.compTorsoFrame, drawinfo.colorBodySkin, bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect)
             {
                 shader = drawinfo.skinDyePacked
             });
         }
         if (!drawinfo.hidesBottomSkin && !drawinfo.drawPlayer.invis && !IsBottomOverridden(ref drawinfo))
         {
             if (drawinfo.isSitting)
             {
                 DrawSittingLegs(ref drawinfo, TextureAssets.Players[drawinfo.skinVar, 10].Value, drawinfo.colorLegs, drawinfo.skinDyePacked);
             }
             else
             {
                 DrawData drawData = new DrawData(TextureAssets.Players[drawinfo.skinVar, 10].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2), drawinfo.drawPlayer.legFrame, drawinfo.colorLegs, drawinfo.drawPlayer.legRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
                 drawData.shader = drawinfo.skinDyePacked;
                 DrawData item = drawData;
                 drawinfo.DrawDataCache.Add(item);
             }
         }
         DrawPlayer_12_SkinComposite_BackArmShirt(ref drawinfo);
     }
References DrawPlayer_12_SkinComposite_BackArmShirt(), DrawSittingLegs(), TextureAssets.Extra, GetCompositeOffset_BackArm(), GetCompositeOffset_FrontArm(), IsBottomOverridden(), Main.OffsetsPlayerHeadgear, TextureAssets.Players, Main.screenPosition, DrawData.shader, and Asset< T >.Value.
Referenced by DrawPlayer_12_Skin().