Terraria: PlayerDrawLayers.DrawPlayer_27_HeldItem
DrawPlayer_27_HeldItem()
static void PlayerDrawLayers.DrawPlayer_27_HeldItem (ref PlayerDrawSet drawinfo) inline static
     {
         if (drawinfo.drawPlayer.JustDroppedAnItem)
         {
             return;
         }
         if (drawinfo.drawPlayer.heldProj >= 0 && drawinfo.shadow == 0f && !drawinfo.heldProjOverHand)
         {
             drawinfo.projectileDrawPosition = drawinfo.DrawDataCache.Count;
         }
         Item heldItem = drawinfo.heldItem;
         int num = heldItem.type;
         if (drawinfo.drawPlayer.UsingBiomeTorches)
         {
             switch (num)
             {
             case 8:
                 num = drawinfo.drawPlayer.BiomeTorchHoldStyle(num);
                 break;
             case 966:
                 num = drawinfo.drawPlayer.BiomeCampfireHoldStyle(num);
                 break;
             }
         }
         float adjustedItemScale = drawinfo.drawPlayer.GetAdjustedItemScale(heldItem);
         Main.instance.LoadItem(num);
         Texture2D value = TextureAssets.Item[num].Value;
         Vector2 position = new Vector2((int)(drawinfo.ItemLocation.X - Main.screenPosition.X), (int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y));
         Rectangle itemDrawFrame = drawinfo.drawPlayer.GetItemDrawFrame(num);
         drawinfo.itemColor = Lighting.GetColor((int)((double)drawinfo.Position.X + (double)drawinfo.drawPlayer.width * 0.5) / 16, (int)(((double)drawinfo.Position.Y + (double)drawinfo.drawPlayer.height * 0.5) / 16.0));
         if (num == 678)
         {
             drawinfo.itemColor = Color.White;
         }
         if (drawinfo.drawPlayer.shroomiteStealth && heldItem.ranged)
         {
             float num2 = drawinfo.drawPlayer.stealth;
             if ((double)num2 < 0.03)
             {
                 num2 = 0.03f;
             }
             float num3 = (1f + num2 * 10f) / 11f;
             drawinfo.itemColor = new Color((byte)((float)(int)drawinfo.itemColor.R * num2), (byte)((float)(int)drawinfo.itemColor.G * num2), (byte)((float)(int)drawinfo.itemColor.B * num3), (byte)((float)(int)drawinfo.itemColor.A * num2));
         }
         if (drawinfo.drawPlayer.setVortex && heldItem.ranged)
         {
             float num4 = drawinfo.drawPlayer.stealth;
             if ((double)num4 < 0.03)
             {
                 num4 = 0.03f;
             }
             _ = (1f + num4 * 10f) / 11f;
             drawinfo.itemColor = drawinfo.itemColor.MultiplyRGBA(new Color(Vector4.Lerp(Vector4.One, new Vector4(0f, 0.12f, 0.16f, 0f), 1f - num4)));
         }
         bool flag = drawinfo.drawPlayer.itemAnimation > 0 && heldItem.useStyle != 0;
         bool flag2 = heldItem.holdStyle != 0 && !drawinfo.drawPlayer.pulley;
         if (!drawinfo.drawPlayer.CanVisuallyHoldItem(heldItem))
         {
             flag2 = false;
         }
         if (drawinfo.shadow != 0f || drawinfo.drawPlayer.frozen || !(flag || flag2) || num <= 0 || drawinfo.drawPlayer.dead || heldItem.noUseGraphic || (drawinfo.drawPlayer.wet && heldItem.noWet) || (drawinfo.drawPlayer.happyFunTorchTime && drawinfo.drawPlayer.inventory[drawinfo.drawPlayer.selectedItem].createTile == 4 && drawinfo.drawPlayer.itemAnimation == 0))
         {
             return;
         }
         _ = drawinfo.drawPlayer.name;
         Color color = new Color(250, 250, 250, heldItem.alpha);
         Vector2 vector = Vector2.Zero;
         switch (num)
         {
         case 104:
         case 5094:
         case 5095:
             vector = new Vector2(4f, -4f) * drawinfo.drawPlayer.Directions;
             break;
         case 426:
         case 797:
         case 1506:
         case 5096:
         case 5097:
             vector = new Vector2(6f, -6f) * drawinfo.drawPlayer.Directions;
             break;
         case 46:
         {
             float amount = Utils.Remap(drawinfo.itemColor.ToVector3().Length() / 1.731f, 0.3f, 0.5f, 1f, 0f);
             color = Color.Lerp(Color.Transparent, new Color(255, 255, 255, 127) * 0.7f, amount);
             break;
         }
         case 204:
             vector = new Vector2(4f, -6f) * drawinfo.drawPlayer.Directions;
             break;
         case 3349:
             vector = new Vector2(2f, -2f) * drawinfo.drawPlayer.Directions;
             break;
         }
         if (num == 3823)
         {
             vector = new Vector2(7 * drawinfo.drawPlayer.direction, -7f * drawinfo.drawPlayer.gravDir);
         }
         if (num == 3827)
         {
             vector = new Vector2(13 * drawinfo.drawPlayer.direction, -13f * drawinfo.drawPlayer.gravDir);
             color = heldItem.GetAlpha(drawinfo.itemColor);
             color = Color.Lerp(color, Color.White, 0.6f);
             color.A = 66;
         }
         Vector2 origin = new Vector2((float)itemDrawFrame.Width * 0.5f - (float)itemDrawFrame.Width * 0.5f * (float)drawinfo.drawPlayer.direction, itemDrawFrame.Height);
         if (heldItem.useStyle == 9 && drawinfo.drawPlayer.itemAnimation > 0)
         {
             Vector2 vector2 = new Vector2(0.5f, 0.4f);
             if (heldItem.type == 5009 || heldItem.type == 5042)
             {
                 vector2 = new Vector2(0.26f, 0.5f);
                 if (drawinfo.drawPlayer.direction == -1)
                 {
                     vector2.X = 1f - vector2.X;
                 }
             }
             origin = itemDrawFrame.Size() * vector2;
         }
         if (drawinfo.drawPlayer.gravDir == -1f)
         {
             origin.Y = (float)itemDrawFrame.Height - origin.Y;
         }
         origin += vector;
         float num5 = drawinfo.drawPlayer.itemRotation;
         if (heldItem.useStyle == 8)
         {
             ref float x = ref position.X;
             float num6 = x;
             _ = drawinfo.drawPlayer.direction;
             x = num6 - 0f;
             num5 -= (float)Math.PI / 2f * (float)drawinfo.drawPlayer.direction;
             origin.Y = 2f;
             origin.X += 2 * drawinfo.drawPlayer.direction;
         }
         if (num == 425 || num == 507)
         {
             if (drawinfo.drawPlayer.gravDir == 1f)
             {
                 if (drawinfo.drawPlayer.direction == 1)
                 {
                     drawinfo.itemEffect = SpriteEffects.FlipVertically;
                 }
                 else
                 {
                     drawinfo.itemEffect = SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
                 }
             }
             else if (drawinfo.drawPlayer.direction == 1)
             {
                 drawinfo.itemEffect = SpriteEffects.None;
             }
             else
             {
                 drawinfo.itemEffect = SpriteEffects.FlipHorizontally;
             }
         }
         if ((num == 946 || num == 4707) && num5 != 0f)
         {
             position.Y -= 22f * drawinfo.drawPlayer.gravDir;
             num5 = -1.57f * (float)(-drawinfo.drawPlayer.direction) * drawinfo.drawPlayer.gravDir;
         }
         ItemSlot.GetItemLight(ref drawinfo.itemColor, heldItem);
         DrawData item;
         switch (num)
         {
         case 3476:
         {
             Texture2D value3 = TextureAssets.Extra[64].Value;
             Rectangle rectangle2 = value3.Frame(1, 9, 0, drawinfo.drawPlayer.miscCounter % 54 / 6);
             Vector2 vector4 = new Vector2(rectangle2.Width / 2 * drawinfo.drawPlayer.direction, 0f);
             Vector2 origin3 = rectangle2.Size() / 2f;
             item = new DrawData(value3, (drawinfo.ItemLocation - Main.screenPosition + vector4).Floor(), rectangle2, heldItem.GetAlpha(drawinfo.itemColor).MultiplyRGBA(new Color(new Vector4(0.5f, 0.5f, 0.5f, 0.8f))), drawinfo.drawPlayer.itemRotation, origin3, adjustedItemScale, drawinfo.itemEffect);
             drawinfo.DrawDataCache.Add(item);
             value3 = TextureAssets.GlowMask[195].Value;
             item = new DrawData(value3, (drawinfo.ItemLocation - Main.screenPosition + vector4).Floor(), rectangle2, new Color(250, 250, 250, heldItem.alpha) * 0.5f, drawinfo.drawPlayer.itemRotation, origin3, adjustedItemScale, drawinfo.itemEffect);
             drawinfo.DrawDataCache.Add(item);
             return;
         }
         case 4049:
         {
             Texture2D value2 = TextureAssets.Extra[92].Value;
             Rectangle rectangle = value2.Frame(1, 4, 0, drawinfo.drawPlayer.miscCounter % 20 / 5);
             Vector2 vector3 = new Vector2(rectangle.Width / 2 * drawinfo.drawPlayer.direction, 0f);
             vector3 += new Vector2(-10 * drawinfo.drawPlayer.direction, 8f * drawinfo.drawPlayer.gravDir);
             Vector2 origin2 = rectangle.Size() / 2f;
             item = new DrawData(value2, (drawinfo.ItemLocation - Main.screenPosition + vector3).Floor(), rectangle, heldItem.GetAlpha(drawinfo.itemColor), drawinfo.drawPlayer.itemRotation, origin2, adjustedItemScale, drawinfo.itemEffect);
             drawinfo.DrawDataCache.Add(item);
             return;
         }
         case 3779:
         {
             Texture2D texture2D = value;
             Rectangle rectangle3 = texture2D.Frame();
             Vector2 vector5 = new Vector2(rectangle3.Width / 2 * drawinfo.drawPlayer.direction, 0f);
             Vector2 origin4 = rectangle3.Size() / 2f;
             float num7 = ((float)drawinfo.drawPlayer.miscCounter / 75f * ((float)Math.PI * 2f)).ToRotationVector2().X * 1f + 0f;
             Color color2 = new Color(120, 40, 222, 0) * (num7 / 2f * 0.3f + 0.85f) * 0.5f;
             num7 = 2f;
             for (float num8 = 0f; num8 < 4f; num8 += 1f)
             {
                 item = new DrawData(TextureAssets.GlowMask[218].Value, (drawinfo.ItemLocation - Main.screenPosition + vector5).Floor() + (num8 * ((float)Math.PI / 2f)).ToRotationVector2() * num7, rectangle3, color2, drawinfo.drawPlayer.itemRotation, origin4, adjustedItemScale, drawinfo.itemEffect);
                 drawinfo.DrawDataCache.Add(item);
             }
             item = new DrawData(texture2D, (drawinfo.ItemLocation - Main.screenPosition + vector5).Floor(), rectangle3, heldItem.GetAlpha(drawinfo.itemColor).MultiplyRGBA(new Color(new Vector4(0.5f, 0.5f, 0.5f, 0.8f))), drawinfo.drawPlayer.itemRotation, origin4, adjustedItemScale, drawinfo.itemEffect);
             drawinfo.DrawDataCache.Add(item);
             return;
         }
         }
         if (heldItem.useStyle == 5)
         {
             if (Item.staff[num])
             {
                 float num9 = drawinfo.drawPlayer.itemRotation + 0.785f * (float)drawinfo.drawPlayer.direction;
                 float num10 = 0f;
                 float num11 = 0f;
                 Vector2 origin5 = new Vector2(0f, itemDrawFrame.Height);
                 if (num == 3210)
                 {
                     num10 = 8 * -drawinfo.drawPlayer.direction;
                     num11 = 2 * (int)drawinfo.drawPlayer.gravDir;
                 }
                 if (num == 3870)
                 {
                     Vector2 vector6 = (drawinfo.drawPlayer.itemRotation + (float)Math.PI / 4f * (float)drawinfo.drawPlayer.direction).ToRotationVector2() * new Vector2((float)(-drawinfo.drawPlayer.direction) * 1.5f, drawinfo.drawPlayer.gravDir) * 3f;
                     num10 = (int)vector6.X;
                     num11 = (int)vector6.Y;
                 }
                 if (num == 3787)
                 {
                     num11 = (int)((float)(8 * (int)drawinfo.drawPlayer.gravDir) * (float)Math.Cos(num9));
                 }
                 if (num == 3209)
                 {
                     Vector2 vector7 = (new Vector2(-8f, 0f) * drawinfo.drawPlayer.Directions).RotatedBy(drawinfo.drawPlayer.itemRotation);
                     num10 = vector7.X;
                     num11 = vector7.Y;
                 }
                 if (drawinfo.drawPlayer.gravDir == -1f)
                 {
                     if (drawinfo.drawPlayer.direction == -1)
                     {
                         num9 += 1.57f;
                         origin5 = new Vector2(itemDrawFrame.Width, 0f);
                         num10 -= (float)itemDrawFrame.Width;
                     }
                     else
                     {
                         num9 -= 1.57f;
                         origin5 = Vector2.Zero;
                     }
                 }
                 else if (drawinfo.drawPlayer.direction == -1)
                 {
                     origin5 = new Vector2(itemDrawFrame.Width, itemDrawFrame.Height);
                     num10 -= (float)itemDrawFrame.Width;
                 }
                 item = new DrawData(value, new Vector2((int)(drawinfo.ItemLocation.X - Main.screenPosition.X + origin5.X + num10), (int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + num11)), itemDrawFrame, heldItem.GetAlpha(drawinfo.itemColor), num9, origin5, adjustedItemScale, drawinfo.itemEffect);
                 drawinfo.DrawDataCache.Add(item);
                 if (num == 3870)
                 {
                     item = new DrawData(TextureAssets.GlowMask[238].Value, new Vector2((int)(drawinfo.ItemLocation.X - Main.screenPosition.X + origin5.X + num10), (int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + num11)), itemDrawFrame, new Color(255, 255, 255, 127), num9, origin5, adjustedItemScale, drawinfo.itemEffect);
                     drawinfo.DrawDataCache.Add(item);
                 }
                 return;
             }
             if (num == 5118)
             {
                 float rotation = drawinfo.drawPlayer.itemRotation + 1.57f * (float)drawinfo.drawPlayer.direction;
                 Vector2 vector8 = new Vector2((float)itemDrawFrame.Width * 0.5f, (float)itemDrawFrame.Height * 0.5f);
                 Vector2 origin6 = new Vector2((float)itemDrawFrame.Width * 0.5f, itemDrawFrame.Height);
                 Vector2 spinningpoint = new Vector2(10f, 4f) * drawinfo.drawPlayer.Directions;
                 spinningpoint = spinningpoint.RotatedBy(drawinfo.drawPlayer.itemRotation);
                 item = new DrawData(value, new Vector2((int)(drawinfo.ItemLocation.X - Main.screenPosition.X + vector8.X + spinningpoint.X), (int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + vector8.Y + spinningpoint.Y)), itemDrawFrame, heldItem.GetAlpha(drawinfo.itemColor), rotation, origin6, adjustedItemScale, drawinfo.itemEffect);
                 drawinfo.DrawDataCache.Add(item);
                 return;
             }
             int num12 = 10;
             Vector2 vector9 = new Vector2(itemDrawFrame.Width / 2, itemDrawFrame.Height / 2);
             Vector2 vector10 = Main.DrawPlayerItemPos(drawinfo.drawPlayer.gravDir, num);
             num12 = (int)vector10.X;
             vector9.Y = vector10.Y;
             Vector2 origin7 = new Vector2(-num12, itemDrawFrame.Height / 2);
             if (drawinfo.drawPlayer.direction == -1)
             {
                 origin7 = new Vector2(itemDrawFrame.Width + num12, itemDrawFrame.Height / 2);
             }
             item = new DrawData(value, new Vector2((int)(drawinfo.ItemLocation.X - Main.screenPosition.X + vector9.X), (int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + vector9.Y)), itemDrawFrame, heldItem.GetAlpha(drawinfo.itemColor), drawinfo.drawPlayer.itemRotation, origin7, adjustedItemScale, drawinfo.itemEffect);
             drawinfo.DrawDataCache.Add(item);
             if (heldItem.color != default(Color))
             {
                 item = new DrawData(value, new Vector2((int)(drawinfo.ItemLocation.X - Main.screenPosition.X + vector9.X), (int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + vector9.Y)), itemDrawFrame, heldItem.GetColor(drawinfo.itemColor), drawinfo.drawPlayer.itemRotation, origin7, adjustedItemScale, drawinfo.itemEffect);
                 drawinfo.DrawDataCache.Add(item);
             }
             if (heldItem.glowMask != -1)
             {
                 item = new DrawData(TextureAssets.GlowMask[heldItem.glowMask].Value, new Vector2((int)(drawinfo.ItemLocation.X - Main.screenPosition.X + vector9.X), (int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + vector9.Y)), itemDrawFrame, new Color(250, 250, 250, heldItem.alpha), drawinfo.drawPlayer.itemRotation, origin7, adjustedItemScale, drawinfo.itemEffect);
                 drawinfo.DrawDataCache.Add(item);
             }
             if (num == 3788)
             {
                 float num13 = ((float)drawinfo.drawPlayer.miscCounter / 75f * ((float)Math.PI * 2f)).ToRotationVector2().X * 1f + 0f;
                 Color color3 = new Color(80, 40, 252, 0) * (num13 / 2f * 0.3f + 0.85f) * 0.5f;
                 for (float num14 = 0f; num14 < 4f; num14 += 1f)
                 {
                     item = new DrawData(TextureAssets.GlowMask[220].Value, new Vector2((int)(drawinfo.ItemLocation.X - Main.screenPosition.X + vector9.X), (int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + vector9.Y)) + (num14 * ((float)Math.PI / 2f) + drawinfo.drawPlayer.itemRotation).ToRotationVector2() * num13, null, color3, drawinfo.drawPlayer.itemRotation, origin7, adjustedItemScale, drawinfo.itemEffect);
                     drawinfo.DrawDataCache.Add(item);
                 }
             }
             return;
         }
         if (drawinfo.drawPlayer.gravDir == -1f)
         {
             item = new DrawData(value, position, itemDrawFrame, heldItem.GetAlpha(drawinfo.itemColor), num5, origin, adjustedItemScale, drawinfo.itemEffect);
             drawinfo.DrawDataCache.Add(item);
             if (heldItem.color != default(Color))
             {
                 item = new DrawData(value, position, itemDrawFrame, heldItem.GetColor(drawinfo.itemColor), num5, origin, adjustedItemScale, drawinfo.itemEffect);
                 drawinfo.DrawDataCache.Add(item);
             }
             if (heldItem.glowMask != -1)
             {
                 item = new DrawData(TextureAssets.GlowMask[heldItem.glowMask].Value, position, itemDrawFrame, new Color(250, 250, 250, heldItem.alpha), num5, origin, adjustedItemScale, drawinfo.itemEffect);
                 drawinfo.DrawDataCache.Add(item);
             }
             return;
         }
         item = new DrawData(value, position, itemDrawFrame, heldItem.GetAlpha(drawinfo.itemColor), num5, origin, adjustedItemScale, drawinfo.itemEffect);
         drawinfo.DrawDataCache.Add(item);
         if (heldItem.color != default(Color))
         {
             item = new DrawData(value, position, itemDrawFrame, heldItem.GetColor(drawinfo.itemColor), num5, origin, adjustedItemScale, drawinfo.itemEffect);
             drawinfo.DrawDataCache.Add(item);
         }
         if (heldItem.glowMask != -1)
         {
             item = new DrawData(TextureAssets.GlowMask[heldItem.glowMask].Value, position, itemDrawFrame, color, num5, origin, adjustedItemScale, drawinfo.itemEffect);
             drawinfo.DrawDataCache.Add(item);
         }
         if (!heldItem.flame || drawinfo.shadow != 0f)
         {
             return;
         }
         try
         {
             Main.instance.LoadItemFlames(num);
             if (TextureAssets.ItemFlame[num].IsLoaded)
             {
                 Color color4 = new Color(100, 100, 100, 0);
                 int num15 = 7;
                 float num16 = 1f;
                 float num17 = 0f;
                 switch (num)
                 {
                 case 3045:
                     color4 = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB, 0);
                     break;
                 case 5293:
                     color4 = new Color(50, 50, 100, 20);
                     break;
                 case 5353:
                     color4 = new Color(255, 255, 255, 200);
                     break;
                 case 4952:
                     num15 = 3;
                     num16 = 0.6f;
                     color4 = new Color(50, 50, 50, 0);
                     break;
                 case 5322:
                     color4 = new Color(100, 100, 100, 150);
                     num17 = -2 * drawinfo.drawPlayer.direction;
                     break;
                 }
                 for (int i = 0; i < num15; i++)
                 {
                     float num18 = drawinfo.drawPlayer.itemFlamePos[i].X * adjustedItemScale * num16;
                     float num19 = drawinfo.drawPlayer.itemFlamePos[i].Y * adjustedItemScale * num16;
                     item = new DrawData(TextureAssets.ItemFlame[num].Value, new Vector2((int)(position.X + num18 + num17), (int)(position.Y + num19)), itemDrawFrame, color4, num5, origin, adjustedItemScale, drawinfo.itemEffect);
                     drawinfo.DrawDataCache.Add(item);
                 }
             }
         }
         catch
         {
         }
     }
References Item.alpha, Color, Item.color, Main.DiscoB, Main.DiscoG, Main.DiscoR, Main.DrawPlayerItemPos(), TextureAssets.Extra, Item.flame, Item.GetAlpha(), Item.GetColor(), Lighting.GetColor(), ItemSlot.GetItemLight(), TextureAssets.GlowMask, Item.glowMask, Item.holdStyle, Main.instance, Asset< T >.IsLoaded, TextureAssets.Item, TextureAssets.ItemFlame, Main.LoadItem(), Main.LoadItemFlames(), Item.noUseGraphic, Item.noWet, Item.ranged, Utils.Remap(), Main.screenPosition, Item.staff, Item.type, Item.useStyle, and Asset< T >.Value.
Referenced by LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().