Terraria: PlayerDrawLayers.DrawPlayer_09_Wings
DrawPlayer_09_Wings()
static void PlayerDrawLayers.DrawPlayer_09_Wings (ref PlayerDrawSet drawinfo) inline static
     {
         if (drawinfo.drawPlayer.dead || drawinfo.hideEntirePlayer)
         {
             return;
         }
         Vector2 directions = drawinfo.drawPlayer.Directions;
         Vector2 vector = drawinfo.Position - Main.screenPosition + drawinfo.drawPlayer.Size / 2f;
         Vector2 vector2 = new Vector2(0f, 7f);
         vector = drawinfo.Position - Main.screenPosition + new Vector2(drawinfo.drawPlayer.width / 2, drawinfo.drawPlayer.height - drawinfo.drawPlayer.bodyFrame.Height / 2) + vector2;
         if (drawinfo.drawPlayer.wings <= 0)
         {
             return;
         }
         Main.instance.LoadWings(drawinfo.drawPlayer.wings);
         DrawData item;
         if (drawinfo.drawPlayer.wings == 22)
         {
             if (!drawinfo.drawPlayer.ShouldDrawWingsThatAreAlwaysAnimated())
             {
                 return;
             }
             Main.instance.LoadItemFlames(1866);
             Color colorArmorBody = drawinfo.colorArmorBody;
             int num = 26;
             int num2 = -9;
             Vector2 vector3 = vector + new Vector2(num2, num) * directions;
             if (drawinfo.shadow == 0f && drawinfo.drawPlayer.grappling[0] == -1)
             {
                 for (int i = 0; i < 7; i++)
                 {
                     Color color = new Color(250 - i * 10, 250 - i * 10, 250 - i * 10, 150 - i * 10);
                     Vector2 vector4 = new Vector2((float)Main.rand.Next(-10, 11) * 0.2f, (float)Main.rand.Next(-10, 11) * 0.2f);
                     drawinfo.stealth *= drawinfo.stealth;
                     drawinfo.stealth *= 1f - drawinfo.shadow;
                     color = new Color((int)((float)(int)color.R * drawinfo.stealth), (int)((float)(int)color.G * drawinfo.stealth), (int)((float)(int)color.B * drawinfo.stealth), (int)((float)(int)color.A * drawinfo.stealth));
                     vector4.X = drawinfo.drawPlayer.itemFlamePos[i].X;
                     vector4.Y = 0f - drawinfo.drawPlayer.itemFlamePos[i].Y;
                     vector4 *= 0.5f;
                     Vector2 position = (vector3 + vector4).Floor();
                     item = new DrawData(TextureAssets.ItemFlame[1866].Value, position, new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7 - 2), color, drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 14), 1f, drawinfo.playerEffect);
                     item.shader = drawinfo.cWings;
                     drawinfo.DrawDataCache.Add(item);
                 }
             }
             item = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector3.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7), colorArmorBody, drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 14), 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cWings;
             drawinfo.DrawDataCache.Add(item);
             return;
         }
         if (drawinfo.drawPlayer.wings == 28)
         {
             if (drawinfo.drawPlayer.ShouldDrawWingsThatAreAlwaysAnimated())
             {
                 Color colorArmorBody2 = drawinfo.colorArmorBody;
                 Vector2 vector5 = new Vector2(0f, 19f);
                 Vector2 vec = vector + vector5 * directions;
                 Texture2D value = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                 Rectangle rectangle = value.Frame(1, 4, 0, drawinfo.drawPlayer.miscCounter / 5 % 4);
                 rectangle.Width -= 2;
                 rectangle.Height -= 2;
                 item = new DrawData(value, vec.Floor(), rectangle, Color.Lerp(colorArmorBody2, Color.White, 1f), drawinfo.drawPlayer.bodyRotation, rectangle.Size() / 2f, 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.cWings;
                 drawinfo.DrawDataCache.Add(item);
                 value = TextureAssets.Extra[38].Value;
                 item = new DrawData(value, vec.Floor(), rectangle, Color.Lerp(colorArmorBody2, Color.White, 0.5f), drawinfo.drawPlayer.bodyRotation, rectangle.Size() / 2f, 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.cWings;
                 drawinfo.DrawDataCache.Add(item);
             }
             return;
         }
         if (drawinfo.drawPlayer.wings == 45)
         {
             if (!drawinfo.drawPlayer.ShouldDrawWingsThatAreAlwaysAnimated())
             {
                 return;
             }
             DrawStarboardRainbowTrail(ref drawinfo, vector, directions);
             Color color2 = new Color(255, 255, 255, 255);
             int num3 = 22;
             int num4 = 0;
             Vector2 vec2 = vector + new Vector2(num4, num3) * directions;
             Color color3 = color2 * (1f - drawinfo.shadow);
             item = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vec2.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 6 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 6), color3, drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 12), 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cWings;
             drawinfo.DrawDataCache.Add(item);
             if (drawinfo.shadow == 0f)
             {
                 float num5 = ((float)drawinfo.drawPlayer.miscCounter / 75f * ((float)Math.PI * 2f)).ToRotationVector2().X * 4f;
                 Color color4 = new Color(70, 70, 70, 0) * (num5 / 8f + 0.5f) * 0.4f;
                 for (float num6 = 0f; num6 < (float)Math.PI * 2f; num6 += (float)Math.PI / 2f)
                 {
                     item = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vec2.Floor() + num6.ToRotationVector2() * num5, new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 6 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 6), color4, drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 12), 1f, drawinfo.playerEffect);
                     item.shader = drawinfo.cWings;
                     drawinfo.DrawDataCache.Add(item);
                 }
             }
             return;
         }
         if (drawinfo.drawPlayer.wings == 34)
         {
             if (drawinfo.drawPlayer.ShouldDrawWingsThatAreAlwaysAnimated())
             {
                 drawinfo.stealth *= drawinfo.stealth;
                 drawinfo.stealth *= 1f - drawinfo.shadow;
                 Color color5 = new Color((int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(100f * drawinfo.stealth));
                 Vector2 vector6 = new Vector2(0f, 0f);
                 Texture2D value2 = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                 Vector2 vec3 = drawinfo.Position + drawinfo.drawPlayer.Size / 2f - Main.screenPosition + vector6 * drawinfo.drawPlayer.Directions - Vector2.UnitX * drawinfo.drawPlayer.direction * 4f;
                 Rectangle rectangle2 = value2.Frame(1, 6, 0, drawinfo.drawPlayer.wingFrame);
                 rectangle2.Width -= 2;
                 rectangle2.Height -= 2;
                 item = new DrawData(value2, vec3.Floor(), rectangle2, color5, drawinfo.drawPlayer.bodyRotation, rectangle2.Size() / 2f, 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.cWings;
                 drawinfo.DrawDataCache.Add(item);
             }
             return;
         }
         if (drawinfo.drawPlayer.wings == 40)
         {
             drawinfo.stealth *= drawinfo.stealth;
             drawinfo.stealth *= 1f - drawinfo.shadow;
             Color color6 = new Color((int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(100f * drawinfo.stealth));
             Vector2 vector7 = new Vector2(-4f, 0f);
             Texture2D value3 = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
             Vector2 vector8 = vector + vector7 * directions;
             for (int j = 0; j < 1; j++)
             {
                 SpriteEffects spriteEffects = drawinfo.playerEffect;
                 Vector2 scale = new Vector2(1f);
                 Vector2 zero = Vector2.Zero;
                 zero.X = drawinfo.drawPlayer.direction * 3;
                 if (j == 1)
                 {
                     spriteEffects ^= SpriteEffects.FlipHorizontally;
                     scale = new Vector2(0.7f, 1f);
                     zero.X += (float)(-drawinfo.drawPlayer.direction) * 6f;
                 }
                 Vector2 vector9 = drawinfo.drawPlayer.velocity * -1.5f;
                 int num7 = 0;
                 int num8 = 8;
                 float num9 = 4f;
                 if (drawinfo.drawPlayer.velocity.Y == 0f)
                 {
                     num7 = 8;
                     num8 = 14;
                     num9 = 3f;
                 }
                 for (int k = num7; k < num8; k++)
                 {
                     Vector2 vec4 = vector8;
                     Rectangle rectangle3 = value3.Frame(1, 14, 0, k);
                     rectangle3.Width -= 2;
                     rectangle3.Height -= 2;
                     int num10 = (k - num7) % (int)num9;
                     Vector2 vector10 = new Vector2(0f, 0.5f).RotatedBy((drawinfo.drawPlayer.miscCounterNormalized * (2f + (float)num10) + (float)num10 * 0.5f + (float)j * 1.3f) * ((float)Math.PI * 2f)) * (num10 + 1);
                     vec4 += vector10;
                     vec4 += vector9 * ((float)num10 / num9);
                     vec4 += zero;
                     item = new DrawData(value3, vec4.Floor(), rectangle3, color6, drawinfo.drawPlayer.bodyRotation, rectangle3.Size() / 2f, scale, spriteEffects);
                     item.shader = drawinfo.cWings;
                     drawinfo.DrawDataCache.Add(item);
                 }
             }
             return;
         }
         if (drawinfo.drawPlayer.wings == 39)
         {
             if (drawinfo.drawPlayer.ShouldDrawWingsThatAreAlwaysAnimated())
             {
                 drawinfo.stealth *= drawinfo.stealth;
                 drawinfo.stealth *= 1f - drawinfo.shadow;
                 Color colorArmorBody3 = drawinfo.colorArmorBody;
                 Vector2 vector11 = new Vector2(-6f, -7f);
                 Texture2D value4 = TextureAssets.Wings[drawinfo.drawPlayer.wings].Value;
                 Vector2 vec5 = vector + vector11 * directions;
                 Rectangle rectangle4 = value4.Frame(1, 6, 0, drawinfo.drawPlayer.wingFrame);
                 rectangle4.Width -= 2;
                 rectangle4.Height -= 2;
                 item = new DrawData(value4, vec5.Floor(), rectangle4, colorArmorBody3, drawinfo.drawPlayer.bodyRotation, rectangle4.Size() / 2f, 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.cWings;
                 drawinfo.DrawDataCache.Add(item);
             }
             return;
         }
         int num11 = 0;
         int num12 = 0;
         int num13 = 4;
         if (drawinfo.drawPlayer.wings == 43)
         {
             num12 = -5;
             num11 = -7;
             num13 = 7;
         }
         else if (drawinfo.drawPlayer.wings == 44)
         {
             num13 = 7;
         }
         else if (drawinfo.drawPlayer.wings == 5)
         {
             num12 = 4;
             num11 -= 4;
         }
         else if (drawinfo.drawPlayer.wings == 27)
         {
             num12 = 4;
         }
         Color color7 = drawinfo.colorArmorBody;
         if (drawinfo.drawPlayer.wings == 9 || drawinfo.drawPlayer.wings == 29)
         {
             drawinfo.stealth *= drawinfo.stealth;
             drawinfo.stealth *= 1f - drawinfo.shadow;
             color7 = new Color((int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(100f * drawinfo.stealth));
         }
         if (drawinfo.drawPlayer.wings == 10)
         {
             drawinfo.stealth *= drawinfo.stealth;
             drawinfo.stealth *= 1f - drawinfo.shadow;
             color7 = new Color((int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(250f * drawinfo.stealth), (int)(175f * drawinfo.stealth));
         }
         if (drawinfo.drawPlayer.wings == 11 && color7.A > Main.gFade)
         {
             color7.A = Main.gFade;
         }
         if (drawinfo.drawPlayer.wings == 31)
         {
             color7.A = (byte)(220f * drawinfo.stealth);
         }
         if (drawinfo.drawPlayer.wings == 32)
         {
             color7.A = (byte)(127f * drawinfo.stealth);
         }
         if (drawinfo.drawPlayer.wings == 6)
         {
             color7.A = (byte)(160f * drawinfo.stealth);
             color7 *= 0.9f;
         }
         Vector2 vector12 = vector + new Vector2(num12 - 9, num11 + 2) * directions;
         item = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector12.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num13 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num13), color7, drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num13 / 2), 1f, drawinfo.playerEffect);
         item.shader = drawinfo.cWings;
         drawinfo.DrawDataCache.Add(item);
         if (drawinfo.drawPlayer.wings == 43 && drawinfo.shadow == 0f)
         {
             Vector2 vector13 = vector12;
             Vector2 origin = new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num13 / 2);
             Rectangle value5 = new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num13 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / num13);
             for (int l = 0; l < 2; l++)
             {
                 item = new DrawData(position: vector13 + new Vector2((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f), texture: TextureAssets.GlowMask[272].Value, sourceRect: value5, color: new Color(230, 230, 230, 60), rotation: drawinfo.drawPlayer.bodyRotation, origin: origin, scale: 1f, effect: drawinfo.playerEffect);
                 item.shader = drawinfo.cWings;
                 drawinfo.DrawDataCache.Add(item);
             }
         }
         if (drawinfo.drawPlayer.wings == 23)
         {
             drawinfo.stealth *= drawinfo.stealth;
             drawinfo.stealth *= 1f - drawinfo.shadow;
             item = new DrawData(color: new Color((int)(200f * drawinfo.stealth), (int)(200f * drawinfo.stealth), (int)(200f * drawinfo.stealth), (int)(200f * drawinfo.stealth)), texture: TextureAssets.Flames[8].Value, position: vector12.Floor(), sourceRect: new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4), rotation: drawinfo.drawPlayer.bodyRotation, origin: new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8), scale: 1f, effect: drawinfo.playerEffect);
             item.shader = drawinfo.cWings;
             drawinfo.DrawDataCache.Add(item);
         }
         else if (drawinfo.drawPlayer.wings == 27)
         {
             item = new DrawData(TextureAssets.GlowMask[92].Value, vector12.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4), new Color(255, 255, 255, 127) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8), 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cWings;
             drawinfo.DrawDataCache.Add(item);
         }
         else if (drawinfo.drawPlayer.wings == 44)
         {
             PlayerRainbowWingsTextureContent playerRainbowWings = TextureAssets.RenderTargets.PlayerRainbowWings;
             playerRainbowWings.Request();
             if (playerRainbowWings.IsReady)
             {
                 RenderTarget2D target = playerRainbowWings.GetTarget();
                 item = new DrawData(target, vector12.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 7), new Color(255, 255, 255, 255) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 14), 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.cWings;
                 drawinfo.DrawDataCache.Add(item);
             }
         }
         else if (drawinfo.drawPlayer.wings == 30)
         {
             item = new DrawData(TextureAssets.GlowMask[181].Value, vector12.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4), new Color(255, 255, 255, 127) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8), 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cWings;
             drawinfo.DrawDataCache.Add(item);
         }
         else if (drawinfo.drawPlayer.wings == 38)
         {
             Color color9 = drawinfo.ArkhalisColor * drawinfo.stealth * (1f - drawinfo.shadow);
             item = new DrawData(TextureAssets.GlowMask[251].Value, vector12.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4), color9, drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8), 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cWings;
             drawinfo.DrawDataCache.Add(item);
             for (int num14 = drawinfo.drawPlayer.shadowPos.Length - 2; num14 >= 0; num14--)
             {
                 Color color10 = color9;
                 color10.A = 0;
                 color10 *= MathHelper.Lerp(1f, 0f, (float)num14 / 3f);
                 color10 *= 0.1f;
                 Vector2 vector14 = drawinfo.drawPlayer.shadowPos[num14] - drawinfo.drawPlayer.position;
                 for (float num15 = 0f; num15 < 1f; num15 += 0.01f)
                 {
                     Vector2 vector15 = new Vector2(2f, 0f).RotatedBy(num15 / 0.04f * ((float)Math.PI * 2f));
                     item = new DrawData(TextureAssets.GlowMask[251].Value, vector15 + vector14 * num15 + vector12, new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4), color10 * (1f - num15), drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8), 1f, drawinfo.playerEffect);
                     item.shader = drawinfo.cWings;
                     drawinfo.DrawDataCache.Add(item);
                 }
             }
         }
         else if (drawinfo.drawPlayer.wings == 29)
         {
             item = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector12.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4), new Color(255, 255, 255, 0) * drawinfo.stealth * (1f - drawinfo.shadow) * 0.5f, drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8), 1.06f, drawinfo.playerEffect);
             item.shader = drawinfo.cWings;
             drawinfo.DrawDataCache.Add(item);
         }
         else if (drawinfo.drawPlayer.wings == 36)
         {
             item = new DrawData(TextureAssets.GlowMask[213].Value, vector12.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4), new Color(255, 255, 255, 0) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8), 1.06f, drawinfo.playerEffect);
             item.shader = drawinfo.cWings;
             drawinfo.DrawDataCache.Add(item);
             Vector2 spinningpoint = new Vector2(0f, 2f - drawinfo.shadow * 2f);
             for (int m = 0; m < 4; m++)
             {
                 item = new DrawData(TextureAssets.GlowMask[213].Value, spinningpoint.RotatedBy((float)Math.PI / 2f * (float)m) + vector12.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4), new Color(127, 127, 127, 127) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8), 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.cWings;
                 drawinfo.DrawDataCache.Add(item);
             }
         }
         else if (drawinfo.drawPlayer.wings == 31)
         {
             Color color11 = new Color(255, 255, 255, 0);
             color11 = Color.Lerp(Color.HotPink, Color.Crimson, (float)Math.Cos((float)Math.PI * 2f * ((float)drawinfo.drawPlayer.miscCounter / 100f)) * 0.4f + 0.5f);
             color11.A = 0;
             for (int n = 0; n < 4; n++)
             {
                 Vector2 vector16 = new Vector2((float)Math.Cos((float)Math.PI * 2f * ((float)drawinfo.drawPlayer.miscCounter / 60f)) * 0.5f + 0.5f, 0f).RotatedBy((float)n * ((float)Math.PI / 2f)) * 1f;
                 item = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector12.Floor() + vector16, new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4), color11 * drawinfo.stealth * (1f - drawinfo.shadow) * 0.5f, drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8), 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.cWings;
                 drawinfo.DrawDataCache.Add(item);
             }
             item = new DrawData(TextureAssets.Wings[drawinfo.drawPlayer.wings].Value, vector12.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4), color11 * drawinfo.stealth * (1f - drawinfo.shadow) * 1f, drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8), 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cWings;
             drawinfo.DrawDataCache.Add(item);
         }
         else if (drawinfo.drawPlayer.wings == 32)
         {
             item = new DrawData(TextureAssets.GlowMask[183].Value, vector12.Floor(), new Rectangle(0, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4 * drawinfo.drawPlayer.wingFrame, TextureAssets.Wings[drawinfo.drawPlayer.wings].Width(), TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 4), new Color(255, 255, 255, 0) * drawinfo.stealth * (1f - drawinfo.shadow), drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.Wings[drawinfo.drawPlayer.wings].Width() / 2, TextureAssets.Wings[drawinfo.drawPlayer.wings].Height() / 8), 1.06f, drawinfo.playerEffect);
             item.shader = drawinfo.cWings;
             drawinfo.DrawDataCache.Add(item);
         }
     }
References Color, DrawStarboardRainbowTrail(), TextureAssets.Extra, TextureAssets.Flames, ARenderTargetContentByRequest.GetTarget(), Main.gFade, TextureAssets.GlowMask, Main.instance, ARenderTargetContentByRequest.IsReady, TextureAssets.ItemFlame, Main.LoadItemFlames(), Main.LoadWings(), UnifiedRandom.Next(), TextureAssets.RenderTargets.PlayerRainbowWings, Main.rand, ARenderTargetContentByRequest.Request(), Main.screenPosition, DrawData.shader, Asset< T >.Value, and TextureAssets.Wings.
Referenced by LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().