Terraria: PlayerDrawLayers.DrawPlayer_21_Head
DrawPlayer_21_Head()
static void PlayerDrawLayers.DrawPlayer_21_Head (ref PlayerDrawSet drawinfo) inline static
     {
         Vector2 helmetOffset = drawinfo.helmetOffset;
         DrawPlayer_21_Head_TheFace(ref drawinfo);
         bool flag = drawinfo.drawPlayer.head == 14 || drawinfo.drawPlayer.head == 56 || drawinfo.drawPlayer.head == 114 || drawinfo.drawPlayer.head == 158 || drawinfo.drawPlayer.head == 69 || drawinfo.drawPlayer.head == 180;
         bool flag2 = drawinfo.drawPlayer.head == 28;
         bool flag3 = drawinfo.drawPlayer.head == 39 || drawinfo.drawPlayer.head == 38;
         Vector2 vector = new Vector2(-drawinfo.drawPlayer.bodyFrame.Width / 2 + drawinfo.drawPlayer.width / 2, drawinfo.drawPlayer.height - drawinfo.drawPlayer.bodyFrame.Height + 4);
         Vector2 position = (drawinfo.Position - Main.screenPosition + vector).Floor() + drawinfo.drawPlayer.headPosition + drawinfo.headVect;
         if (drawinfo.playerEffect.HasFlag(SpriteEffects.FlipVertically))
         {
             int num = drawinfo.drawPlayer.bodyFrame.Height - drawinfo.hairFrontFrame.Height;
             position.Y += num;
         }
         position += drawinfo.hairOffset;
         if (drawinfo.fullHair)
         {
             Color color = drawinfo.colorArmorHead;
             int shader = drawinfo.cHead;
             if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
             {
                 color = ((!drawinfo.drawPlayer.isDisplayDollOrInanimate) ? drawinfo.colorHead : drawinfo.colorDisplayDollSkin);
                 shader = drawinfo.skinDyePacked;
             }
             DrawData item = new DrawData(TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, drawinfo.drawPlayer.bodyFrame, color, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             item.shader = shader;
             drawinfo.DrawDataCache.Add(item);
             if (!drawinfo.drawPlayer.invis)
             {
                 item = new DrawData(TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, position, drawinfo.hairFrontFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.hairDyePacked;
                 drawinfo.DrawDataCache.Add(item);
             }
         }
         if (drawinfo.hatHair && !drawinfo.drawPlayer.invis)
         {
             DrawData item = new DrawData(TextureAssets.PlayerHairAlt[drawinfo.drawPlayer.hair].Value, position, drawinfo.hairFrontFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             item.shader = drawinfo.hairDyePacked;
             drawinfo.DrawDataCache.Add(item);
         }
         if (drawinfo.drawPlayer.head == 270)
         {
             Rectangle bodyFrame = drawinfo.drawPlayer.bodyFrame;
             bodyFrame.Width += 2;
             DrawData item = new DrawData(TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, bodyFrame, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cHead;
             drawinfo.DrawDataCache.Add(item);
             item = new DrawData(TextureAssets.GlowMask[drawinfo.headGlowMask].Value, helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, bodyFrame, drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cHead;
             drawinfo.DrawDataCache.Add(item);
         }
         else if (flag)
         {
             Rectangle bodyFrame2 = drawinfo.drawPlayer.bodyFrame;
             Vector2 headVect = drawinfo.headVect;
             if (drawinfo.drawPlayer.gravDir == 1f)
             {
                 if (bodyFrame2.Y != 0)
                 {
                     bodyFrame2.Y -= 2;
                     headVect.Y += 2f;
                 }
                 bodyFrame2.Height -= 8;
             }
             else if (bodyFrame2.Y != 0)
             {
                 bodyFrame2.Y -= 2;
                 headVect.Y -= 10f;
                 bodyFrame2.Height -= 8;
             }
             Color color2 = drawinfo.colorArmorHead;
             int shader2 = drawinfo.cHead;
             if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
             {
                 color2 = ((!drawinfo.drawPlayer.isDisplayDollOrInanimate) ? drawinfo.colorHead : drawinfo.colorDisplayDollSkin);
                 shader2 = drawinfo.skinDyePacked;
             }
             DrawData item = new DrawData(TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, bodyFrame2, color2, drawinfo.drawPlayer.headRotation, headVect, 1f, drawinfo.playerEffect);
             item.shader = shader2;
             drawinfo.DrawDataCache.Add(item);
         }
         else if (drawinfo.drawPlayer.head == 259)
         {
             int verticalFrames = 27;
             Texture2D value = TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value;
             Rectangle rectangle = value.Frame(1, verticalFrames, 0, drawinfo.drawPlayer.rabbitOrderFrame.DisplayFrame);
             Vector2 origin = rectangle.Size() / 2f;
             int num2 = drawinfo.drawPlayer.babyBird.ToInt();
             Vector2 vector2 = DrawPlayer_21_Head_GetSpecialHatDrawPosition(ref drawinfo, ref helmetOffset, new Vector2(1 + num2 * 2, -26 + drawinfo.drawPlayer.babyBird.ToInt() * -6));
             int hatStacks = GetHatStacks(ref drawinfo, 4955);
             float num3 = (float)Math.PI / 60f;
             float num4 = num3 * drawinfo.drawPlayer.position.X % ((float)Math.PI * 2f);
             for (int num5 = hatStacks - 1; num5 >= 0; num5--)
             {
                 float x = Vector2.UnitY.RotatedBy(num4 + num3 * (float)num5).X * ((float)num5 / 30f) * 2f - (float)(num5 * 2 * drawinfo.drawPlayer.direction);
                 DrawData item = new DrawData(value, vector2 + new Vector2(x, (float)(num5 * -14) * drawinfo.drawPlayer.gravDir), rectangle, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, origin, 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.cHead;
                 drawinfo.DrawDataCache.Add(item);
             }
             if (!drawinfo.drawPlayer.invis)
             {
                 DrawData item = new DrawData(TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, position, drawinfo.hairFrontFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.hairDyePacked;
                 drawinfo.DrawDataCache.Add(item);
             }
         }
         else if (drawinfo.drawPlayer.head > 0 && drawinfo.drawPlayer.head < ArmorIDs.Head.Count && !flag2)
         {
             if (!(drawinfo.drawPlayer.invis && flag3))
             {
                 if (drawinfo.drawPlayer.head == 13)
                 {
                     int hatStacks2 = GetHatStacks(ref drawinfo, 205);
                     float num6 = (float)Math.PI / 60f;
                     float num7 = num6 * drawinfo.drawPlayer.position.X % ((float)Math.PI * 2f);
                     for (int i = 0; i < hatStacks2; i++)
                     {
                         float num8 = Vector2.UnitY.RotatedBy(num7 + num6 * (float)i).X * ((float)i / 30f) * 2f;
                         DrawData item = new DrawData(TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)) + num8, (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f - (float)(4 * i))) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, drawinfo.drawPlayer.bodyFrame, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                         item.shader = drawinfo.cHead;
                         drawinfo.DrawDataCache.Add(item);
                     }
                 }
                 else if (drawinfo.drawPlayer.head == 265)
                 {
                     int verticalFrames2 = 6;
                     Texture2D value2 = TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value;
                     Rectangle rectangle2 = value2.Frame(1, verticalFrames2, 0, drawinfo.drawPlayer.rabbitOrderFrame.DisplayFrame);
                     Vector2 origin2 = rectangle2.Size() / 2f;
                     Vector2 vector3 = DrawPlayer_21_Head_GetSpecialHatDrawPosition(ref drawinfo, ref helmetOffset, new Vector2(0f, -9f));
                     int hatStacks3 = GetHatStacks(ref drawinfo, 5004);
                     float num9 = (float)Math.PI / 60f;
                     float num10 = num9 * drawinfo.drawPlayer.position.X % ((float)Math.PI * 2f);
                     int num11 = hatStacks3 * 4 + 2;
                     int num12 = 0;
                     bool flag4 = (Main.GlobalTimeWrappedHourly + 180f) % 600f < 60f;
                     for (int num13 = num11 - 1; num13 >= 0; num13--)
                     {
                         int num14 = 0;
                         if (num13 == num11 - 1)
{
                             rectangle2.Y = 0;
                             num14 = 2;
                         }
                         else if (num13 == 0)
{
                             rectangle2.Y = rectangle2.Height * 5;
                         }
                         else
{
                             rectangle2.Y = rectangle2.Height * (num12++ % 4 + 1);
                         }
                         if (!(rectangle2.Y == rectangle2.Height * 3 && flag4))
{
                             float x2 = Vector2.UnitY.RotatedBy(num10 + num9 * (float)num13).X * ((float)num13 / 10f) * 4f - (float)num13 * 0.1f * (float)drawinfo.drawPlayer.direction;
                             DrawData item = new DrawData(value2, vector3 + new Vector2(x2, (float)(num13 * -4 + num14) * drawinfo.drawPlayer.gravDir), rectangle2, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, origin2, 1f, drawinfo.playerEffect);
                             item.shader = drawinfo.cHead;
                             drawinfo.DrawDataCache.Add(item);
                         }
                     }
                 }
                 else
                 {
                     Rectangle bodyFrame3 = drawinfo.drawPlayer.bodyFrame;
                     Vector2 headVect2 = drawinfo.headVect;
                     if (drawinfo.drawPlayer.gravDir == 1f)
                     {
                         bodyFrame3.Height -= 4;
                     }
                     else
                     {
                         headVect2.Y -= 4f;
                         bodyFrame3.Height -= 4;
                     }
                     Color color3 = drawinfo.colorArmorHead;
                     int shader3 = drawinfo.cHead;
                     if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
                     {
                         color3 = ((!drawinfo.drawPlayer.isDisplayDollOrInanimate) ? drawinfo.colorHead : drawinfo.colorDisplayDollSkin);
                         shader3 = drawinfo.skinDyePacked;
                     }
                     DrawData item = new DrawData(TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, bodyFrame3, color3, drawinfo.drawPlayer.headRotation, headVect2, 1f, drawinfo.playerEffect);
                     item.shader = shader3;
                     drawinfo.DrawDataCache.Add(item);
                     if (drawinfo.headGlowMask != -1)
                     {
                         if (drawinfo.headGlowMask == 309)
{
                             int num15 = DrawPlayer_Head_GetTVScreen(drawinfo.drawPlayer);
                             if (num15 != 0)
{
                                 int num16 = 0;
                                 num16 += drawinfo.drawPlayer.bodyFrame.Y / 56;
                                 if (num16 >= Main.OffsetsPlayerHeadgear.Length)
{
                                     num16 = 0;
                                 }
                                 Vector2 vector4 = Main.OffsetsPlayerHeadgear[num16];
                                 vector4.Y -= 2f;
                                 vector4 *= (float)(-drawinfo.playerEffect.HasFlag(SpriteEffects.FlipVertically).ToDirectionInt());
                                 Texture2D value3 = TextureAssets.GlowMask[drawinfo.headGlowMask].Value;
                                 int frameY = drawinfo.drawPlayer.miscCounter % 20 / 5;
                                 if (num15 == 5)
{
                                     frameY = 0;
                                     if (drawinfo.drawPlayer.eyeHelper.EyeFrameToShow > 0)
{
                                         frameY = 2;
                                     }
                                 }
                                 Rectangle value4 = value3.Frame(6, 4, num15, frameY, -2);
                                 item = new DrawData(value3, vector4 + helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, value4, drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                                 item.shader = drawinfo.cHead;
                                 drawinfo.DrawDataCache.Add(item);
                             }
                         }
                         else if (drawinfo.headGlowMask == 273)
{
                             for (int j = 0; j < 2; j++)
{
                                 item = new DrawData(position: new Vector2((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f) + helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, texture: TextureAssets.GlowMask[drawinfo.headGlowMask].Value, sourceRect: bodyFrame3, color: drawinfo.headGlowColor, rotation: drawinfo.drawPlayer.headRotation, origin: headVect2, scale: 1f, effect: drawinfo.playerEffect);
                                 item.shader = drawinfo.cHead;
                                 drawinfo.DrawDataCache.Add(item);
                             }
                         }
                         else
{
                             item = new DrawData(TextureAssets.GlowMask[drawinfo.headGlowMask].Value, helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, bodyFrame3, drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, headVect2, 1f, drawinfo.playerEffect);
                             item.shader = drawinfo.cHead;
                             drawinfo.DrawDataCache.Add(item);
                         }
                     }
                     if (drawinfo.drawPlayer.head == 211)
                     {
                         Color color4 = new Color(100, 100, 100, 0);
                         ulong seed = (ulong)(drawinfo.drawPlayer.miscCounter / 4 + 100);
                         int num17 = 4;
                         for (int k = 0; k < num17; k++)
{
                             float x3 = (float)Utils.RandomInt(ref seed, -10, 11) * 0.2f;
                             float y = (float)Utils.RandomInt(ref seed, -14, 1) * 0.15f;
                             item = new DrawData(TextureAssets.GlowMask[241].Value, helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect + new Vector2(x3, y), drawinfo.drawPlayer.bodyFrame, color4, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                             item.shader = drawinfo.cHead;
                             drawinfo.DrawDataCache.Add(item);
                         }
                     }
                 }
             }
         }
         else if (!drawinfo.drawPlayer.invis && (drawinfo.drawPlayer.face < 0 || !ArmorIDs.Face.Sets.PreventHairDraw[drawinfo.drawPlayer.face]))
         {
             DrawData item = new DrawData(TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, position, drawinfo.hairFrontFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             item.shader = drawinfo.hairDyePacked;
             drawinfo.DrawDataCache.Add(item);
         }
         if (drawinfo.drawPlayer.beard > 0 && (drawinfo.drawPlayer.head < 0 || !ArmorIDs.Head.Sets.PreventBeardDraw[drawinfo.drawPlayer.head]))
         {
             Vector2 beardDrawOffsetFromHelmet = drawinfo.drawPlayer.GetBeardDrawOffsetFromHelmet();
             Color color5 = drawinfo.colorArmorHead;
             if (ArmorIDs.Beard.Sets.UseHairColor[drawinfo.drawPlayer.beard])
             {
                 color5 = drawinfo.colorHair;
             }
             DrawData item = new DrawData(TextureAssets.AccBeard[drawinfo.drawPlayer.beard].Value, beardDrawOffsetFromHelmet + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, drawinfo.drawPlayer.bodyFrame, color5, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cBeard;
             drawinfo.DrawDataCache.Add(item);
         }
         if (drawinfo.drawPlayer.head == 205)
         {
             DrawData drawData = new DrawData(TextureAssets.Extra[77].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, drawinfo.drawPlayer.bodyFrame, drawinfo.colorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             drawData.shader = drawinfo.skinDyePacked;
             DrawData item = drawData;
             drawinfo.DrawDataCache.Add(item);
         }
         if (drawinfo.drawPlayer.head == 214 && !drawinfo.drawPlayer.invis)
         {
             Rectangle bodyFrame4 = drawinfo.drawPlayer.bodyFrame;
             bodyFrame4.Y = 0;
             float num18 = (float)drawinfo.drawPlayer.miscCounter / 300f;
             Color color6 = new Color(0, 0, 0, 0);
             float num19 = 0.8f;
             float num20 = 0.9f;
             if (num18 >= num19)
             {
                 color6 = Color.Lerp(Color.Transparent, new Color(200, 200, 200, 0), Utils.GetLerpValue(num19, num20, num18, clamped: true));
             }
             if (num18 >= num20)
             {
                 color6 = Color.Lerp(Color.Transparent, new Color(200, 200, 200, 0), Utils.GetLerpValue(1f, num20, num18, clamped: true));
             }
             color6 *= drawinfo.stealth * (1f - drawinfo.shadow);
             DrawData item = new DrawData(TextureAssets.Extra[90].Value, helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect - Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height], bodyFrame4, color6, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             drawinfo.DrawDataCache.Add(item);
         }
         if (drawinfo.drawPlayer.head == 137)
         {
             DrawData item = new DrawData(TextureAssets.JackHat.Value, helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, drawinfo.drawPlayer.bodyFrame, new Color(255, 255, 255, 255), drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             drawinfo.DrawDataCache.Add(item);
             for (int l = 0; l < 7; l++)
             {
                 Color color7 = new Color(110 - l * 10, 110 - l * 10, 110 - l * 10, 110 - l * 10);
                 Vector2 vector5 = new Vector2((float)Main.rand.Next(-10, 11) * 0.2f, (float)Main.rand.Next(-10, 11) * 0.2f);
                 vector5.X = drawinfo.drawPlayer.itemFlamePos[l].X;
                 vector5.Y = drawinfo.drawPlayer.itemFlamePos[l].Y;
                 vector5 *= 0.5f;
                 item = new DrawData(TextureAssets.JackHat.Value, helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect + vector5, drawinfo.drawPlayer.bodyFrame, color7, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                 drawinfo.DrawDataCache.Add(item);
             }
         }
         if (drawinfo.drawPlayer.babyBird)
         {
             Rectangle bodyFrame5 = drawinfo.drawPlayer.bodyFrame;
             bodyFrame5.Y = 0;
             Vector2 vector6 = Vector2.Zero;
             Color color8 = drawinfo.colorArmorHead;
             if (drawinfo.drawPlayer.mount.Active && drawinfo.drawPlayer.mount.Type == 52)
             {
                 Vector2 mountedCenter = drawinfo.drawPlayer.MountedCenter;
                 color8 = drawinfo.drawPlayer.GetImmuneAlphaPure(Lighting.GetColorClamped((int)mountedCenter.X / 16, (int)mountedCenter.Y / 16, Color.White), drawinfo.shadow);
                 vector6 = new Vector2(0f, 6f) * drawinfo.drawPlayer.Directions;
             }
             DrawData item = new DrawData(TextureAssets.Extra[100].Value, vector6 + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect + Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height] * drawinfo.drawPlayer.gravDir, bodyFrame5, color8, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             drawinfo.DrawDataCache.Add(item);
         }
     }
References TextureAssets.AccBeard, TextureAssets.ArmorHead, Color, ArmorIDs.Head.Count, DrawPlayer_21_Head_GetSpecialHatDrawPosition(), DrawPlayer_21_Head_TheFace(), DrawPlayer_Head_GetTVScreen(), TextureAssets.Extra, Lighting.GetColorClamped(), GetHatStacks(), Utils.GetLerpValue(), Main.GlobalTimeWrappedHourly, TextureAssets.GlowMask, TextureAssets.JackHat, UnifiedRandom.Next(), Main.OffsetsPlayerHeadgear, TextureAssets.PlayerHair, TextureAssets.PlayerHairAlt, ArmorIDs.Head.Sets.PreventBeardDraw, ArmorIDs.Face.Sets.PreventHairDraw, Main.rand, Utils.RandomInt(), Main.screenPosition, DrawData.shader, ArmorIDs.Beard.Sets.UseHairColor, ArmorIDs.Head.Sets.UseSkinColor, Asset< T >.Value, and X.
Referenced by LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().