Terraria: PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt
DrawPlayer_12_SkinComposite_BackArmShirt()
static void PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt (ref PlayerDrawSet drawinfo) inline static
     {
         Vector2 vector = new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2);
         Vector2 vector2 = Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height];
         vector2.Y -= 2f;
         vector += vector2 * -drawinfo.playerEffect.HasFlag(SpriteEffects.FlipVertically).ToDirectionInt();
         vector.Y += drawinfo.torsoOffset;
         float bodyRotation = drawinfo.drawPlayer.bodyRotation;
         Vector2 vector3 = vector;
         Vector2 position = vector;
         Vector2 bodyVect = drawinfo.bodyVect;
         Vector2 compositeOffset_BackArm = GetCompositeOffset_BackArm(ref drawinfo);
         vector3 += compositeOffset_BackArm;
         position += drawinfo.backShoulderOffset;
         bodyVect += compositeOffset_BackArm;
         float rotation = bodyRotation + drawinfo.compositeBackArmRotation;
         bool flag = !drawinfo.drawPlayer.invis;
         bool flag2 = !drawinfo.drawPlayer.invis;
         bool flag3 = drawinfo.drawPlayer.body > 0 && drawinfo.drawPlayer.body < ArmorIDs.Body.Count;
         bool flag4 = !drawinfo.hidesTopSkin;
         bool flag5 = false;
         if (flag3)
         {
             flag &= drawinfo.missingHand;
             if (flag2 && drawinfo.missingArm)
             {
                 if (flag4)
                 {
                     drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
                     {
                         shader = drawinfo.skinDyePacked
                     });
                 }
                 if (!flag5 && flag4)
                 {
                     drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 5].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
                     {
                         shader = drawinfo.skinDyePacked
                     });
                     flag5 = true;
                 }
                 flag2 = false;
             }
             if (!drawinfo.drawPlayer.invis || IsArmorDrawnWhenInvisible(drawinfo.drawPlayer.body))
             {
                 Texture2D value = TextureAssets.ArmorBodyComposite[drawinfo.drawPlayer.body].Value;
                 if (!drawinfo.hideCompositeShoulders)
                 {
                     DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.BackShoulder, new DrawData(value, position, drawinfo.compBackShoulderFrame, drawinfo.colorArmorBody, bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect)
                     {
                         shader = drawinfo.cBody
                     });
                 }
                 DrawPlayer_12_1_BalloonFronts(ref drawinfo);
                 DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.BackArm, new DrawData(value, vector3, drawinfo.compBackArmFrame, drawinfo.colorArmorBody, rotation, bodyVect, 1f, drawinfo.playerEffect)
                 {
                     shader = drawinfo.cBody
                 });
             }
         }
         if (flag)
         {
             if (flag4)
             {
                 if (flag2)
                 {
                     drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
                     {
                         shader = drawinfo.skinDyePacked
                     });
                 }
                 if (!flag5 && flag4)
                 {
                     drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 5].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
                     {
                         shader = drawinfo.skinDyePacked
                     });
                     flag5 = true;
                 }
             }
             if (!flag3)
             {
                 drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 8].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorUnderShirt, rotation, bodyVect, 1f, drawinfo.playerEffect));
                 DrawPlayer_12_1_BalloonFronts(ref drawinfo);
                 drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 13].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorShirt, rotation, bodyVect, 1f, drawinfo.playerEffect));
             }
         }
         if (drawinfo.drawPlayer.handoff > 0 && drawinfo.drawPlayer.handoff < ArmorIDs.HandOff.Count)
         {
             Texture2D value2 = TextureAssets.AccHandsOffComposite[drawinfo.drawPlayer.handoff].Value;
             DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.BackArmAccessory, new DrawData(value2, vector3, drawinfo.compBackArmFrame, drawinfo.colorArmorBody, rotation, bodyVect, 1f, drawinfo.playerEffect)
             {
                 shader = drawinfo.cHandOff
             });
         }
         if (drawinfo.drawPlayer.drawingFootball)
         {
             Main.instance.LoadProjectile(861);
             Texture2D value3 = TextureAssets.Projectile[861].Value;
             Rectangle rectangle = value3.Frame(1, 4);
             Vector2 origin = rectangle.Size() / 2f;
             Vector2 position2 = vector3 + new Vector2(drawinfo.drawPlayer.direction * -2, drawinfo.drawPlayer.gravDir * 4f);
             drawinfo.DrawDataCache.Add(new DrawData(value3, position2, rectangle, drawinfo.colorArmorBody, bodyRotation + (float)Math.PI / 4f * (float)drawinfo.drawPlayer.direction, origin, 0.8f, drawinfo.playerEffect));
         }
     }
References TextureAssets.AccHandsOffComposite, TextureAssets.ArmorBodyComposite, ArmorIDs.Body.Count, ArmorIDs.HandOff.Count, DrawCompositeArmorPiece(), DrawPlayer_12_1_BalloonFronts(), GetCompositeOffset_BackArm(), Main.instance, IsArmorDrawnWhenInvisible(), Main.LoadProjectile(), Main.OffsetsPlayerHeadgear, TextureAssets.Players, TextureAssets.Projectile, Main.screenPosition, and Asset< T >.Value.
Referenced by DrawPlayer_12_Skin_Composite().