Terraria: PlayerDrawLayers.DrawCompositeArmorPiece
DrawCompositeArmorPiece()
static void PlayerDrawLayers.DrawCompositeArmorPiece (ref PlayerDrawSet drawinfo, CompositePlayerDrawContext context, DrawData data) inline static
     {
         drawinfo.DrawDataCache.Add(data);
         switch (context)
         {
         case CompositePlayerDrawContext.BackShoulder:
         case CompositePlayerDrawContext.BackArm:
         case CompositePlayerDrawContext.FrontArm:
         case CompositePlayerDrawContext.FrontShoulder:
         {
             if (drawinfo.armGlowColor.PackedValue == 0)
             {
                 break;
             }
             DrawData item2 = data;
             item2.color = drawinfo.armGlowColor;
             Rectangle value2 = item2.sourceRect.Value;
             value2.Y += 224;
             item2.sourceRect = value2;
             if (drawinfo.drawPlayer.body == 227)
             {
                 Vector2 position2 = item2.position;
                 for (int j = 0; j < 2; j++)
                 {
                     Vector2 vector2 = new Vector2((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f);
                     item2.position = position2 + vector2;
                     if (j == 0)
                     {
                         drawinfo.DrawDataCache.Add(item2);
                     }
                 }
             }
             drawinfo.DrawDataCache.Add(item2);
             break;
         }
         case CompositePlayerDrawContext.Torso:
         {
             if (drawinfo.bodyGlowColor.PackedValue == 0)
             {
                 break;
             }
             DrawData item = data;
             item.color = drawinfo.bodyGlowColor;
             Rectangle value = item.sourceRect.Value;
             value.Y += 224;
             item.sourceRect = value;
             if (drawinfo.drawPlayer.body == 227)
             {
                 Vector2 position = item.position;
                 for (int i = 0; i < 2; i++)
                 {
                     Vector2 vector = new Vector2((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f);
                     item.position = position + vector;
                     if (i == 0)
                     {
                         drawinfo.DrawDataCache.Add(item);
                     }
                 }
             }
             drawinfo.DrawDataCache.Add(item);
             break;
         }
         }
         if (context == CompositePlayerDrawContext.FrontShoulder && drawinfo.drawPlayer.head == 269)
         {
             Vector2 position3 = drawinfo.helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect;
             DrawData item3 = new DrawData(TextureAssets.Extra[214].Value, position3, drawinfo.drawPlayer.bodyFrame, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             item3.shader = drawinfo.cHead;
             drawinfo.DrawDataCache.Add(item3);
             item3 = new DrawData(TextureAssets.GlowMask[308].Value, position3, drawinfo.drawPlayer.bodyFrame, drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
             item3.shader = drawinfo.cHead;
             drawinfo.DrawDataCache.Add(item3);
         }
         if (context == CompositePlayerDrawContext.FrontArm && drawinfo.drawPlayer.body == 205)
         {
             Color color = new Color(100, 100, 100, 0);
             ulong seed = (ulong)(drawinfo.drawPlayer.miscCounter / 4);
             int num = 4;
             for (int k = 0; k < num; k++)
             {
                 float num2 = (float)Utils.RandomInt(ref seed, -10, 11) * 0.2f;
                 float num3 = (float)Utils.RandomInt(ref seed, -10, 1) * 0.15f;
                 DrawData item4 = data;
                 Rectangle value3 = item4.sourceRect.Value;
                 value3.Y += 224;
                 item4.sourceRect = value3;
                 item4.position.X += num2;
                 item4.position.Y += num3;
                 item4.color = color;
                 drawinfo.DrawDataCache.Add(item4);
             }
         }
     }
References DrawData.color, Color, TextureAssets.Extra, TextureAssets.GlowMask, UnifiedRandom.Next(), DrawData.position, Main.rand, Utils.RandomInt(), Main.screenPosition, DrawData.shader, DrawData.sourceRect, and Asset< T >.Value.
Referenced by DrawPlayer_12_SkinComposite_BackArmShirt(), DrawPlayer_17_TorsoComposite(), and DrawPlayer_28_ArmOverItemComposite().