Terraria: PlayerDrawLayers.DrawPlayer_Head_GetTVScreen
DrawPlayer_Head_GetTVScreen()
static int PlayerDrawLayers.DrawPlayer_Head_GetTVScreen (Player plr) inline static
     {
         if (NPC.AnyDanger())
         {
             return 4;
         }
         if (plr.statLife <= plr.statLifeMax2 / 4)
         {
             return 1;
         }
         if (plr.ZoneCorrupt || plr.ZoneCrimson || plr.ZoneGraveyard)
         {
             return 0;
         }
         if (plr.wet)
         {
             return 2;
         }
         if (plr.townNPCs >= 3f || BirthdayParty.PartyIsUp || LanternNight.LanternsUp)
         {
             return 5;
         }
         return 3;
     }
References NPC.AnyDanger(), LanternNight.LanternsUp, BirthdayParty.PartyIsUp, Player.statLife, Player.statLifeMax2, Player.townNPCs, Entity.wet, Player.ZoneCorrupt, Player.ZoneCrimson, and Player.ZoneGraveyard.
Referenced by PlayerDrawHeadLayers.DrawPlayer_06_NormalHats(), and DrawPlayer_21_Head().