Terraria: System.ConsolePal.MoveBufferArea
MoveBufferArea()
static unsafe void System.ConsolePal.MoveBufferArea (int sourceLeft, int sourceTop, int sourceWidth, int sourceHeight, int targetLeft, int targetTop, char sourceChar, ConsoleColor sourceForeColor, ConsoleColor sourceBackColor) inline static
Definition at line 716 of file ConsolePal.cs.
    {
        if (sourceForeColor < ConsoleColor.Black || sourceForeColor > ConsoleColor.White)
        {
            throw new ArgumentException(System.SR.Arg_InvalidConsoleColor, "sourceForeColor");
        }
        if (sourceBackColor < ConsoleColor.Black || sourceBackColor > ConsoleColor.White)
        {
            throw new ArgumentException(System.SR.Arg_InvalidConsoleColor, "sourceBackColor");
        }
        global::Interop.Kernel32.COORD dwSize = GetBufferInfo().dwSize;
        if (sourceLeft < 0 || sourceLeft > dwSize.X)
        {
            throw new ArgumentOutOfRangeException("sourceLeft", sourceLeft, System.SR.ArgumentOutOfRange_ConsoleBufferBoundaries);
        }
        if (sourceTop < 0 || sourceTop > dwSize.Y)
        {
            throw new ArgumentOutOfRangeException("sourceTop", sourceTop, System.SR.ArgumentOutOfRange_ConsoleBufferBoundaries);
        }
        if (sourceWidth < 0 || sourceWidth > dwSize.X - sourceLeft)
        {
            throw new ArgumentOutOfRangeException("sourceWidth", sourceWidth, System.SR.ArgumentOutOfRange_ConsoleBufferBoundaries);
        }
        if (sourceHeight < 0 || sourceTop > dwSize.Y - sourceHeight)
        {
            throw new ArgumentOutOfRangeException("sourceHeight", sourceHeight, System.SR.ArgumentOutOfRange_ConsoleBufferBoundaries);
        }
        if (targetLeft < 0 || targetLeft > dwSize.X)
        {
            throw new ArgumentOutOfRangeException("targetLeft", targetLeft, System.SR.ArgumentOutOfRange_ConsoleBufferBoundaries);
        }
        if (targetTop < 0 || targetTop > dwSize.Y)
        {
            throw new ArgumentOutOfRangeException("targetTop", targetTop, System.SR.ArgumentOutOfRange_ConsoleBufferBoundaries);
        }
        if (sourceWidth == 0 || sourceHeight == 0)
        {
            return;
        }
        global::Interop.Kernel32.CHAR_INFO[] array = new global::Interop.Kernel32.CHAR_INFO[sourceWidth * sourceHeight];
        dwSize.X = (short)sourceWidth;
        dwSize.Y = (short)sourceHeight;
        global::Interop.Kernel32.COORD bufferCoord = default(global::Interop.Kernel32.COORD);
        global::Interop.Kernel32.SMALL_RECT readRegion = default(global::Interop.Kernel32.SMALL_RECT);
        readRegion.Left = (short)sourceLeft;
        readRegion.Right = (short)(sourceLeft + sourceWidth - 1);
        readRegion.Top = (short)sourceTop;
        readRegion.Bottom = (short)(sourceTop + sourceHeight - 1);
        bool flag;
        fixed (global::Interop.Kernel32.CHAR_INFO* pBuffer = array)
        {
            flag = global::Interop.Kernel32.ReadConsoleOutput(OutputHandle, pBuffer, dwSize, bufferCoord, ref readRegion);
        }
        if (!flag)
        {
            throw System.IO.Win32Marshal.GetExceptionForWin32Error(Marshal.GetLastPInvokeError());
        }
        global::Interop.Kernel32.COORD cOORD = default(global::Interop.Kernel32.COORD);
        cOORD.X = (short)sourceLeft;
        global::Interop.Kernel32.Color color = ConsoleColorToColorAttribute(sourceBackColor, isBackground: true);
        color |= ConsoleColorToColorAttribute(sourceForeColor, isBackground: false);
        short wColorAttribute = (short)color;
        for (int i = sourceTop; i < sourceTop + sourceHeight; i++)
        {
            cOORD.Y = (short)i;
            if (!global::Interop.Kernel32.FillConsoleOutputCharacter(OutputHandle, sourceChar, sourceWidth, cOORD, out var pNumCharsWritten))
            {
                throw System.IO.Win32Marshal.GetExceptionForWin32Error(Marshal.GetLastPInvokeError());
            }
            if (!global::Interop.Kernel32.FillConsoleOutputAttribute(OutputHandle, wColorAttribute, sourceWidth, cOORD, out pNumCharsWritten))
            {
                throw System.IO.Win32Marshal.GetExceptionForWin32Error(Marshal.GetLastPInvokeError());
            }
        }
        global::Interop.Kernel32.SMALL_RECT writeRegion = default(global::Interop.Kernel32.SMALL_RECT);
        writeRegion.Left = (short)targetLeft;
        writeRegion.Right = (short)(targetLeft + sourceWidth);
        writeRegion.Top = (short)targetTop;
        writeRegion.Bottom = (short)(targetTop + sourceHeight);
        fixed (global::Interop.Kernel32.CHAR_INFO* buffer = array)
        {
            global::Interop.Kernel32.WriteConsoleOutput(OutputHandle, buffer, dwSize, bufferCoord, ref writeRegion);
        }
    }
References System.SR.Arg_InvalidConsoleColor, System.SR.ArgumentOutOfRange_ConsoleBufferBoundaries, System.array, System.buffer, System.ConsolePal.ConsoleColorToColorAttribute(), System.ConsolePal.GetBufferInfo(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), and System.ConsolePal.OutputHandle.
Referenced by System.Console.MoveBufferArea(), and System.Console.MoveBufferArea().