Terraria: System.ConsolePal.SetWindowSize
SetWindowSize()
static unsafe void System.ConsolePal.SetWindowSize (int width, int height) inline static
Definition at line 893 of file ConsolePal.cs.
    {
        if (width <= 0)
        {
            throw new ArgumentOutOfRangeException("width", width, System.SR.ArgumentOutOfRange_NeedPosNum);
        }
        if (height <= 0)
        {
            throw new ArgumentOutOfRangeException("height", height, System.SR.ArgumentOutOfRange_NeedPosNum);
        }
        global::Interop.Kernel32.CONSOLE_SCREEN_BUFFER_INFO bufferInfo = GetBufferInfo();
        bool flag = false;
        global::Interop.Kernel32.COORD size = default(global::Interop.Kernel32.COORD);
        size.X = bufferInfo.dwSize.X;
        size.Y = bufferInfo.dwSize.Y;
        if (bufferInfo.dwSize.X < bufferInfo.srWindow.Left + width)
        {
            if (bufferInfo.srWindow.Left >= 32767 - width)
            {
                throw new ArgumentOutOfRangeException("width", System.SR.Format(System.SR.ArgumentOutOfRange_ConsoleWindowBufferSize, 32767 - width));
            }
            size.X = (short)(bufferInfo.srWindow.Left + width);
            flag = true;
        }
        if (bufferInfo.dwSize.Y < bufferInfo.srWindow.Top + height)
        {
            if (bufferInfo.srWindow.Top >= 32767 - height)
            {
                throw new ArgumentOutOfRangeException("height", System.SR.Format(System.SR.ArgumentOutOfRange_ConsoleWindowBufferSize, 32767 - height));
            }
            size.Y = (short)(bufferInfo.srWindow.Top + height);
            flag = true;
        }
        if (flag && !global::Interop.Kernel32.SetConsoleScreenBufferSize(OutputHandle, size))
        {
            throw System.IO.Win32Marshal.GetExceptionForWin32Error(Marshal.GetLastPInvokeError());
        }
        global::Interop.Kernel32.SMALL_RECT srWindow = bufferInfo.srWindow;
        srWindow.Bottom = (short)(srWindow.Top + height - 1);
        srWindow.Right = (short)(srWindow.Left + width - 1);
        if (!global::Interop.Kernel32.SetConsoleWindowInfo(OutputHandle, absolute: true, &srWindow))
        {
            int lastPInvokeError = Marshal.GetLastPInvokeError();
            if (flag)
            {
                global::Interop.Kernel32.SetConsoleScreenBufferSize(OutputHandle, bufferInfo.dwSize);
            }
            global::Interop.Kernel32.COORD largestConsoleWindowSize = global::Interop.Kernel32.GetLargestConsoleWindowSize(OutputHandle);
            if (width > largestConsoleWindowSize.X)
            {
                throw new ArgumentOutOfRangeException("width", width, System.SR.Format(System.SR.ArgumentOutOfRange_ConsoleWindowSize_Size, largestConsoleWindowSize.X));
            }
            if (height > largestConsoleWindowSize.Y)
            {
                throw new ArgumentOutOfRangeException("height", height, System.SR.Format(System.SR.ArgumentOutOfRange_ConsoleWindowSize_Size, largestConsoleWindowSize.Y));
            }
            throw System.IO.Win32Marshal.GetExceptionForWin32Error(lastPInvokeError);
        }
    }
References System.SR.ArgumentOutOfRange_ConsoleWindowBufferSize, System.SR.ArgumentOutOfRange_ConsoleWindowSize_Size, System.SR.ArgumentOutOfRange_NeedPosNum, System.SR.Format(), System.ConsolePal.GetBufferInfo(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), and System.ConsolePal.OutputHandle.
Referenced by System.Console.SetWindowSize().