Terraria: System.ConsolePal.ReadKey
ReadKey()
static ConsoleKeyInfo System.ConsolePal.ReadKey (bool intercept) inline static
Definition at line 605 of file ConsolePal.cs.
    {
        int numEventsRead = -1;
        global::Interop.InputRecord buffer;
        lock (s_readKeySyncObject)
        {
            if (_cachedInputRecord.eventType == 1)
            {
                buffer = _cachedInputRecord;
                if (_cachedInputRecord.keyEvent.repeatCount == 0)
                {
                    _cachedInputRecord.eventType = -1;
                }
                else
                {
                    _cachedInputRecord.keyEvent.repeatCount--;
                }
            }
            else
            {
                while (true)
                {
                    if (!global::Interop.Kernel32.ReadConsoleInput(InputHandle, out buffer, 1, out numEventsRead) || numEventsRead == 0)
                    {
                        throw new InvalidOperationException(System.SR.InvalidOperation_ConsoleReadKeyOnFile);
                    }
                    short virtualKeyCode = buffer.keyEvent.virtualKeyCode;
                    if ((!IsKeyDownEvent(buffer) && virtualKeyCode != 18) || (buffer.keyEvent.uChar == '\0' && IsModKey(buffer)))
                    {
                        continue;
                    }
                    ConsoleKey consoleKey = (ConsoleKey)virtualKeyCode;
                    if (!IsAltKeyDown(buffer))
                    {
                        break;
                    }
                    if (consoleKey < ConsoleKey.NumPad0 || consoleKey > ConsoleKey.NumPad9)
                    {
                        switch (consoleKey)
{
                        case ConsoleKey.Clear:
                        case ConsoleKey.PageUp:
                        case ConsoleKey.PageDown:
                        case ConsoleKey.End:
                        case ConsoleKey.Home:
                        case ConsoleKey.LeftArrow:
                        case ConsoleKey.UpArrow:
                        case ConsoleKey.RightArrow:
                        case ConsoleKey.DownArrow:
                        case ConsoleKey.Insert:
                            continue;
                        }
                        break;
                    }
                }
                if (buffer.keyEvent.repeatCount > 1)
                {
                    buffer.keyEvent.repeatCount--;
                    _cachedInputRecord = buffer;
                }
            }
        }
        ControlKeyState controlKeyState = (ControlKeyState)buffer.keyEvent.controlKeyState;
        bool shift = (controlKeyState & ControlKeyState.ShiftPressed) != 0;
        bool alt = (controlKeyState & (ControlKeyState.RightAltPressed | ControlKeyState.LeftAltPressed)) != 0;
        bool control = (controlKeyState & (ControlKeyState.RightCtrlPressed | ControlKeyState.LeftCtrlPressed)) != 0;
        ConsoleKeyInfo result = new ConsoleKeyInfo(buffer.keyEvent.uChar, (ConsoleKey)buffer.keyEvent.virtualKeyCode, shift, alt, control);
        if (!intercept)
        {
            Console.Write(buffer.keyEvent.uChar);
        }
        return result;
    }
References System.ConsolePal._cachedInputRecord, System.buffer, System.ConsolePal.InputHandle, System.SR.InvalidOperation_ConsoleReadKeyOnFile, System.ConsolePal.IsAltKeyDown(), System.ConsolePal.IsKeyDownEvent(), System.ConsolePal.IsModKey(), System.ConsolePal.s_readKeySyncObject, and System.Console.Write().
Referenced by System.Console.ReadKey(), and System.Console.ReadKey().