Terraria: System.ConsolePal.GetBufferInfo
GetBufferInfo() [1/2]
static global.Interop.Kernel32.CONSOLE_SCREEN_BUFFER_INFO System.ConsolePal.GetBufferInfo () inline static private
Definition at line 976 of file ConsolePal.cs.
    {
        bool succeeded;
        return GetBufferInfo(throwOnNoConsole: true, out succeeded);
    }
References System.ConsolePal.GetBufferInfo().
Referenced by System.ConsolePal.Clear(), System.ConsolePal.GetBufferInfo(), System.ConsolePal.GetCursorPosition(), System.ConsolePal.MoveBufferArea(), System.ConsolePal.ResetColor(), System.ConsolePal.SetBufferSize(), System.ConsolePal.SetCursorPosition(), System.ConsolePal.SetWindowPosition(), and System.ConsolePal.SetWindowSize().