Terraria: System.ConsolePal.GetStandardFile
GetStandardFile()
static Stream System.ConsolePal.GetStandardFile (int handleType, FileAccess access, bool useFileAPIs) inline static private
Definition at line 516 of file ConsolePal.cs.
    {
        IntPtr stdHandle = global::Interop.Kernel32.GetStdHandle(handleType);
        if (stdHandle == IntPtr.Zero || stdHandle == InvalidHandleValue || (access != FileAccess.Read && !ConsoleHandleIsWritable(stdHandle)))
        {
            return Stream.Null;
        }
        return new WindowsConsoleStream(stdHandle, access, useFileAPIs);
    }
References System.ConsolePal.ConsoleHandleIsWritable(), System.ConsolePal.InvalidHandleValue, System.IO.Stream.Null, and System.IntPtr.Zero.
Referenced by System.ConsolePal.OpenStandardError(), System.ConsolePal.OpenStandardInput(), and System.ConsolePal.OpenStandardOutput().