Terraria: Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar.ValidateAndCollectNecessaryInfo
ValidateAndCollectNecessaryInfo()
bool Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar.ValidateAndCollectNecessaryInfo (ref BigProgressBarInfo info) inline
Implements Terraria.GameContent.UI.BigProgressBar.IBigProgressBar.
Definition at line 21 of file GolemHeadProgressBar.cs.
    {
        if (info.npcIndexToAimAt < 0 || info.npcIndexToAimAt > 200)
        {
            return false;
        }
        NPC nPC = Main.npc[info.npcIndexToAimAt];
        if (!nPC.active && !TryFindingAnotherGolemPiece(ref info))
        {
            return false;
        }
        int num = 0;
        _referenceDummy.SetDefaults(245, nPC.GetMatchingSpawnParams());
        num += _referenceDummy.lifeMax;
        _referenceDummy.SetDefaults(246, nPC.GetMatchingSpawnParams());
        num += _referenceDummy.lifeMax;
        float num2 = 0f;
        for (int i = 0; i < 200; i++)
        {
            NPC nPC2 = Main.npc[i];
            if (nPC2.active && ValidIds.Contains(nPC2.type))
            {
                num2 += (float)nPC2.life;
            }
        }
        _cache.SetLife(num2, num);
        return true;
    }
References Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar._cache, Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar._referenceDummy, System.Collections.Generic.HashSet< T >.Contains(), Terraria.NPC.lifeMax, Terraria.Main.npc, Terraria.NPC.SetDefaults(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarCache.SetLife(), Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar.TryFindingAnotherGolemPiece(), and Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar.ValidIds.