Terraria: System.Threading.Tasks.Dataflow.TransformManyBlock.StoreOutputItemsReordered
StoreOutputItemsReordered()
void System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.StoreOutputItemsReordered (long id, IEnumerable< TOutput > item) inline private
Definition at line 285 of file TransformManyBlock.cs.
    {
        TargetCore<TInput> target = _target;
        bool isBounded = target.IsBounded;
        if (item == null)
        {
            _reorderingBuffer.AddItem(id, null, itemIsValid: false);
            if (isBounded)
            {
                target.ChangeBoundingCount(-1);
            }
            return;
        }
        IList<TOutput> list = item as TOutput[];
        if (list == null)
        {
            list = item as List<TOutput>;
        }
        if (list != null && isBounded)
        {
            UpdateBoundingCountWithOutputCount(list.Count);
        }
        bool? flag = _reorderingBuffer.AddItemIfNextAndTrusted(id, list, list != null);
        if (!flag.HasValue)
        {
            return;
        }
        bool value = flag.Value;
        List<TOutput> list2 = null;
        try
        {
            if (value)
            {
                StoreOutputItemsNonReorderedWithIteration(item);
                return;
            }
            if (list != null)
            {
                list2 = list.ToList();
                return;
            }
            int count = 0;
            try
            {
                list2 = item.ToList();
                count = list2.Count;
            }
            finally
            {
                if (isBounded)
                {
                    UpdateBoundingCountWithOutputCount(count);
                }
            }
        }
        finally
        {
            _reorderingBuffer.AddItem(id, list2, list2 != null);
        }
    }
References System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >._reorderingBuffer, System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >._target, System.Threading.Tasks.Dataflow.Internal.ReorderingBuffer< TOutput >.AddItem(), System.Threading.Tasks.Dataflow.Internal.ReorderingBuffer< TOutput >.AddItemIfNextAndTrusted(), System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.item, System.list, System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.StoreOutputItemsNonReorderedWithIteration(), System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.UpdateBoundingCountWithOutputCount(), and System.value.
Referenced by System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.StoreOutputItems().