Terraria: System.Threading.Tasks.Dataflow.TransformManyBlock.StoreOutputItems
StoreOutputItems()
void System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.StoreOutputItems (KeyValuePair< TInput, long > messageWithId, IEnumerable< TOutput > outputItems) inline private
Definition at line 262 of file TransformManyBlock.cs.
    {
        if (_reorderingBuffer != null)
        {
            StoreOutputItemsReordered(messageWithId.Value, outputItems);
        }
        else if (outputItems != null)
        {
            if (outputItems is TOutput[] || outputItems is List<TOutput>)
            {
                StoreOutputItemsNonReorderedAtomic(outputItems);
            }
            else
            {
                StoreOutputItemsNonReorderedWithIteration(outputItems);
            }
        }
        else if (_target.IsBounded)
        {
            _target.ChangeBoundingCount(-1);
        }
    }
References System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >._reorderingBuffer, System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >._target, System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.StoreOutputItemsNonReorderedAtomic(), System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.StoreOutputItemsNonReorderedWithIteration(), and System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.StoreOutputItemsReordered().
Referenced by System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.AsyncCompleteProcessMessageWithTask(), System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.ProcessMessage(), and System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.ProcessMessageWithTask().