Terraria: System.Xml.Schema.StringFacetsChecker.CheckBuiltInFacets
CheckBuiltInFacets()
Exception System.Xml.Schema.StringFacetsChecker.CheckBuiltInFacets (string s, XmlTypeCode typeCode, bool verifyUri) inline private
Definition at line 97 of file StringFacetsChecker.cs.
    {
        Exception result = null;
        switch (typeCode)
        {
        case XmlTypeCode.AnyUri:
            if (verifyUri)
            {
                result = XmlConvert.TryToUri(s, out var _);
            }
            break;
        case XmlTypeCode.NormalizedString:
            result = XmlConvert.TryVerifyNormalizedString(s);
            break;
        case XmlTypeCode.Token:
            result = XmlConvert.TryVerifyTOKEN(s);
            break;
        case XmlTypeCode.Language:
            if (s == null || s.Length == 0)
            {
                return new XmlSchemaException(System.SR.Sch_EmptyAttributeValue, string.Empty);
            }
            if (!LanguagePattern.IsMatch(s))
            {
                return new XmlSchemaException(System.SR.Sch_InvalidLanguageId, string.Empty);
            }
            break;
        case XmlTypeCode.NmToken:
            result = XmlConvert.TryVerifyNMTOKEN(s);
            break;
        case XmlTypeCode.Name:
            result = XmlConvert.TryVerifyName(s);
            break;
        case XmlTypeCode.NCName:
        case XmlTypeCode.Id:
        case XmlTypeCode.Idref:
        case XmlTypeCode.Entity:
            result = XmlConvert.TryVerifyNCName(s);
            break;
        }
        return result;
    }
References System.Xml.Dictionary, System.Xml.Schema.StringFacetsChecker.LanguagePattern, System.s, System.SR.Sch_EmptyAttributeValue, System.SR.Sch_InvalidLanguageId, System.Xml.XmlConvert.TryToUri(), System.Xml.XmlConvert.TryVerifyName(), System.Xml.XmlConvert.TryVerifyNCName(), System.Xml.XmlConvert.TryVerifyNMTOKEN(), System.Xml.XmlConvert.TryVerifyNormalizedString(), and System.Xml.XmlConvert.TryVerifyTOKEN().
Referenced by System.Xml.Schema.StringFacetsChecker.CheckValueFacets().