Terraria: System.Threading.Tasks.Dataflow.TransformManyBlock.ProcessMessageWithTask
ProcessMessageWithTask()
void System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.ProcessMessageWithTask (Func< TInput, Task< IEnumerable< TOutput > > > function, KeyValuePair< TInput, long > messageWithId) inline private
Definition at line 188 of file TransformManyBlock.cs.
    {
        Task<IEnumerable<TOutput>> task = null;
        Exception ex = null;
        try
        {
            task = function(messageWithId.Key);
        }
        catch (Exception ex2)
        {
            ex = ex2;
        }
        if (task == null)
        {
            if (ex != null && !Common.IsCooperativeCancellation(ex))
            {
                Common.StoreDataflowMessageValueIntoExceptionData(ex, messageWithId.Key);
                _target.Complete(ex, dropPendingMessages: true, storeExceptionEvenIfAlreadyCompleting: true);
            }
            if (_reorderingBuffer != null)
            {
                StoreOutputItems(messageWithId, null);
                _target.SignalOneAsyncMessageCompleted();
            }
            else
            {
                _target.SignalOneAsyncMessageCompleted(-1);
            }
        }
        else
        {
            task.ContinueWith(delegate(Task<IEnumerable<TOutput>> completed, object state)
            {
                Tuple<TransformManyBlock<TInput, TOutput>, KeyValuePair<TInput, long>> tuple = (Tuple<TransformManyBlock<TInput, TOutput>, KeyValuePair<TInput, long>>)state;
                tuple.Item1.AsyncCompleteProcessMessageWithTask(completed, tuple.Item2);
            }, Tuple.Create(this, messageWithId), CancellationToken.None, Common.GetContinuationOptions(TaskContinuationOptions.ExecuteSynchronously), _source.DataflowBlockOptions.TaskScheduler);
        }
    }
References System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >._reorderingBuffer, System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >._source, System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >._target, System.Threading.Tasks.Dataflow.Internal.Common.GetContinuationOptions(), System.Threading.Tasks.Dataflow.Internal.Common.IsCooperativeCancellation(), System.Threading.CancellationToken.None, System.state, System.Threading.Tasks.Dataflow.TransformManyBlock< TInput, TOutput >.StoreOutputItems(), and System.task.