Terraria: CreativePowers.ASharedSliderPower.SetValueGamepad
SetValueGamepad()
void CreativePowers.ASharedSliderPower.SetValueGamepad () inline package inherited
         {
             float sliderValue = GetSliderValue();
             float num = UILinksInitializer.HandleSliderVerticalInput(sliderValue, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
             if (num != sliderValue)
             {
                 SetValueKeyboard(num);
             }
         }
References PlayerInput.CurrentProfile, CreativePowers.ASharedSliderPower.GetSliderValue(), UILinksInitializer.HandleSliderVerticalInput(), PlayerInputProfile.InterfaceDeadzoneX, and CreativePowers.ASharedSliderPower.SetValueKeyboard().