Terraria: CreativePowers.ASharedSliderPower.categoryButton_OnUpdate
categoryButton_OnUpdate()
void CreativePowers.ASharedSliderPower.categoryButton_OnUpdate (UIElement affectedElement) inline private inherited
         {
             if (affectedElement.IsMouseHovering)
             {
                 GroupOptionButton<int> groupOptionButton = affectedElement as GroupOptionButton<int>;
                 string originalText = Language.GetTextValue(_powerNameKey + (groupOptionButton.IsSelected ? "_Opened" : "_Closed"));
                 CreativePowersHelper.AddDescriptionIfNeeded(ref originalText, _powerNameKey + "_Description");
                 CreativePowersHelper.AddUnlockTextIfNeeded(ref originalText, GetIsUnlocked(), _powerNameKey + "_Unlock");
                 CreativePowersHelper.AddPermissionTextIfNeeded(this, ref originalText);
                 Main.instance.MouseTextNoOverride(originalText, 0, 0);
             }
             AttemptPushingChange();
         }
References CreativePowers.ASharedSliderPower._powerNameKey, CreativePowersHelper.AddDescriptionIfNeeded(), CreativePowersHelper.AddPermissionTextIfNeeded(), CreativePowersHelper.AddUnlockTextIfNeeded(), CreativePowers.ASharedSliderPower.AttemptPushingChange(), CreativePowers.ASharedSliderPower.GetIsUnlocked(), Language.GetTextValue(), Main.instance, UIElement.IsMouseHovering, GroupOptionButton< T >.IsSelected, and Main.MouseTextNoOverride().
Referenced by CreativePowers.ASharedSliderPower.GetOptionButton().