Terraria: CreativePowers.ASharedSliderPower.GetOptionButton
GetOptionButton()
GroupOptionButton<int> CreativePowers.ASharedSliderPower.GetOptionButton (CreativePowerUIElementRequestInfo info, int optionIndex, int currentOptionIndex) inline inherited
Implements IPowerSubcategoryElement.
         {
             GroupOptionButton<int> groupOptionButton = CreativePowersHelper.CreateCategoryButton(info, optionIndex, currentOptionIndex);
             CreativePowersHelper.UpdateUnlockStateByPower(this, groupOptionButton, CreativePowersHelper.CommonSelectedColor);
             groupOptionButton.Append(CreativePowersHelper.GetIconImage(_iconLocation));
             groupOptionButton.OnUpdate += categoryButton_OnUpdate;
             return groupOptionButton;
         }
References CreativePowers.ASharedSliderPower._iconLocation, UIElement.Append(), CreativePowers.ASharedSliderPower.categoryButton_OnUpdate(), CreativePowersHelper.CommonSelectedColor, CreativePowersHelper.GetIconImage(), UIElement.OnUpdate, and CreativePowersHelper.UpdateUnlockStateByPower().