Terraria: System.Net.Mail.MailCommand.EndSend
EndSend()
static void System.Net.Mail.MailCommand.EndSend (IAsyncResult result) inline static package
Definition at line 28 of file MailCommand.cs.
    {
        string response;
        SmtpStatusCode statusCode = (SmtpStatusCode)CheckCommand.EndSend(result, out response);
        CheckResponse(statusCode, response);
    }
References System.Net.Mail.MailCommand.CheckResponse(), and System.Net.Mail.CheckCommand.EndSend().
Referenced by System.Net.Mail.SendMailAsyncResult.SendMailFrom(), and System.Net.Mail.SendMailAsyncResult.SendMailFromCompleted().