Terraria: System.Net.Mail.MailCommand.PrepareCommand
PrepareCommand()
static void System.Net.Mail.MailCommand.PrepareCommand (SmtpConnection conn, byte[] command, MailAddress from, bool allowUnicode) inline static private
Definition at line 35 of file MailCommand.cs.
    {
        if (conn.IsStreamOpen)
        {
            throw new InvalidOperationException(System.SR.SmtpDataStreamOpen);
        }
        conn.BufferBuilder.Append(command);
        string smtpAddress = from.GetSmtpAddress(allowUnicode);
        conn.BufferBuilder.Append(smtpAddress, allowUnicode);
        if (allowUnicode)
        {
            conn.BufferBuilder.Append(" BODY=8BITMIME SMTPUTF8");
        }
        conn.BufferBuilder.Append(SmtpCommands.CRLF);
    }
References System.Net.Mail.BufferBuilder.Append(), System.Net.Mail.SmtpConnection.BufferBuilder, System.Net.Mail.SmtpCommands.CRLF, System.Net.Mail.MailAddress.GetSmtpAddress(), System.Net.Mail.SmtpConnection.IsStreamOpen, and System.SR.SmtpDataStreamOpen.
Referenced by System.Net.Mail.MailCommand.BeginSend(), and System.Net.Mail.MailCommand.Send().