Terraria: MS.Internal.Xml.XPath.PreSiblingQuery.NotVisited
NotVisited()
static bool MS.Internal.Xml.XPath.PreSiblingQuery.NotVisited (XPathNavigator nav, List< XPathNavigator > parentStk) inline static private
Definition at line 20 of file PreSiblingQuery.cs.
    {
        XPathNavigator xPathNavigator = nav.Clone();
        xPathNavigator.MoveToParent();
        for (int i = 0; i < parentStk.Count; i++)
        {
            if (xPathNavigator.IsSamePosition(parentStk[i]))
            {
                return false;
            }
        }
        parentStk.Add(xPathNavigator);
        return true;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XPath.XPathNavigator.Clone(), and System.Collections.Generic.Dictionary< TKey, TValue >.Count.
Referenced by MS.Internal.Xml.XPath.PreSiblingQuery.Evaluate().