Terraria: MS.Internal.Xml.XPath.PreSiblingQuery.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.PreSiblingQuery.Evaluate (XPathNodeIterator context) inline
Definition at line 35 of file PreSiblingQuery.cs.
    {
        base.Evaluate(context);
        List<XPathNavigator> parentStk = new List<XPathNavigator>();
        Stack<XPathNavigator> stack = new Stack<XPathNavigator>();
        while ((currentNode = qyInput.Advance()) != null)
        {
            stack.Push(currentNode.Clone());
        }
        while (stack.Count != 0)
        {
            XPathNavigator xPathNavigator = stack.Pop();
            if (xPathNavigator.NodeType == XPathNodeType.Attribute || xPathNavigator.NodeType == XPathNodeType.Namespace || !NotVisited(xPathNavigator, parentStk))
            {
                continue;
            }
            XPathNavigator xPathNavigator2 = xPathNavigator.Clone();
            if (!xPathNavigator2.MoveToParent())
            {
                continue;
            }
            bool flag = xPathNavigator2.MoveToFirstChild();
            while (!xPathNavigator2.IsSamePosition(xPathNavigator))
            {
                if (matches(xPathNavigator2))
                {
                    Query.Insert(outputBuffer, xPathNavigator2);
                }
                if (!xPathNavigator2.MoveToNext())
                {
                    break;
                }
            }
        }
        return this;
    }
References MS.Internal.Xml.XPath.Query.Advance(), System.Xml.XPath.XPathNavigator.Clone(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, MS.Internal.Xml.XPath.BaseAxisQuery.currentNode, MS.Internal.Xml.XPath.Query.Insert(), MS.Internal.Xml.XPath.BaseAxisQuery.matches(), MS.Internal.Xml.XPath.PreSiblingQuery.NotVisited(), MS.Internal.Xml.XPath.CacheAxisQuery.outputBuffer, and MS.Internal.Xml.XPath.BaseAxisQuery.qyInput.