Terraria: System.Xml.Serialization.CodeIdentifiers.Clone
Clone()
CodeIdentifiers System.Xml.Serialization.CodeIdentifiers.Clone () inline package
Definition at line 133 of file CodeIdentifiers.cs.
    {
        CodeIdentifiers codeIdentifiers = new CodeIdentifiers();
        codeIdentifiers._identifiers = (Hashtable)_identifiers.Clone();
        codeIdentifiers._reservedIdentifiers = (Hashtable)_reservedIdentifiers.Clone();
        codeIdentifiers._list = (ArrayList)_list.Clone();
        codeIdentifiers._camelCase = _camelCase;
        return codeIdentifiers;
    }
References System.Xml.Serialization.CodeIdentifiers.CodeIdentifiers(), System.Xml.Serialization.CodeIdentifiers._camelCase, System.Xml.Serialization.CodeIdentifiers._identifiers, System.Xml.Serialization.CodeIdentifiers._list, System.Xml.Serialization.CodeIdentifiers._reservedIdentifiers, System.Collections.ArrayList.Clone(), System.Collections.Hashtable.Clone(), and System.Xml.Dictionary.