Terraria: System.Xml.Serialization.CodeIdentifiers.MakeUnique
MakeUnique()
string System.Xml.Serialization.CodeIdentifiers.MakeUnique (string identifier) inline
Definition at line 64 of file CodeIdentifiers.cs.
    {
        if (IsInUse(identifier))
        {
            int num = 1;
            string text;
            while (true)
            {
                text = identifier + num.ToString(CultureInfo.InvariantCulture);
                if (!IsInUse(text))
                {
                    break;
                }
                num++;
            }
            identifier = text;
        }
        if (identifier.Length > 511)
        {
            return MakeUnique("Item");
        }
        return identifier;
    }
References System.Xml.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.CodeIdentifiers.IsInUse(), System.Xml.Serialization.CodeIdentifiers.MakeUnique(), and System.text.
Referenced by System.Xml.Serialization.CodeIdentifiers.AddUnique(), and System.Xml.Serialization.CodeIdentifiers.MakeUnique().