Terraria: System.Reflection.Internal.MemoryBlockProvider.GetMemoryBlock
GetMemoryBlock() [1/2]
AbstractMemoryBlock System.Reflection.Internal.MemoryBlockProvider.GetMemoryBlock () inline inherited
Definition at line 9 of file MemoryBlockProvider.cs.
    {
        return GetMemoryBlockImpl(0, Size);
    }
References System.Reflection.Internal.MemoryBlockProvider.GetMemoryBlockImpl(), and System.Reflection.Internal.MemoryBlockProvider.Size.
Referenced by System.Reflection.PortableExecutable.PEReader.GetDebugDirectoryEntryDataBlock(), System.Reflection.PortableExecutable.PEReader.GetEntireImageBlock(), System.Reflection.Metadata.MetadataReaderProvider.GetMetadataBlock(), System.Reflection.PortableExecutable.PEReader.GetMetadataBlock(), System.Reflection.PortableExecutable.PEReader.GetPESectionBlock(), and System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory().