Terraria: System.Diagnostics.AsyncStreamReader.MoveLinesFromStringBuilderToMessageQueue
MoveLinesFromStringBuilderToMessageQueue()
void System.Diagnostics.AsyncStreamReader.MoveLinesFromStringBuilderToMessageQueue () inline private
Definition at line 110 of file AsyncStreamReader.cs.
    {
        int i = _currentLinePos;
        int num = 0;
        int length = _sb.Length;
        if (_bLastCarriageReturn && length > 0 && _sb[0] == '\n')
        {
            i = 1;
            num = 1;
            _bLastCarriageReturn = false;
        }
        for (; i < length; i++)
        {
            char c = _sb[i];
            if (c == '\r' || c == '\n')
            {
                string item = _sb.ToString(num, i - num);
                num = i + 1;
                if (c == '\r' && num < length && _sb[num] == '\n')
                {
                    num++;
                    i++;
                }
                lock (_messageQueue)
                {
                    _messageQueue.Enqueue(item);
                }
            }
        }
        if (length > 0 && _sb[length - 1] == '\r')
        {
            _bLastCarriageReturn = true;
        }
        if (num < length)
        {
            if (num == 0)
            {
                _currentLinePos = i;
                return;
            }
            _sb.Remove(0, num);
            _currentLinePos = 0;
        }
        else
        {
            _sb.Length = 0;
            _currentLinePos = 0;
        }
    }
References System.Diagnostics.AsyncStreamReader._bLastCarriageReturn, System.Diagnostics.AsyncStreamReader._currentLinePos, System.Diagnostics.AsyncStreamReader._messageQueue, System.Diagnostics.AsyncStreamReader._sb, System.Collections.Generic.Queue< T >.Enqueue(), System.item, System.length, System.Text.StringBuilder.Length, System.Text.StringBuilder.Remove(), and System.Text.StringBuilder.ToString().
Referenced by System.Diagnostics.AsyncStreamReader.ReadBufferAsync().