Terraria: System.Net.WebUtility.HtmlEncode
HtmlEncode() [2/3]
static ? string System.Net.WebUtility.HtmlEncode (string? value) inline static
Definition at line 378 of file WebUtility.cs.
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }
        ReadOnlySpan<char> input = value.AsSpan();
        int num = IndexOfHtmlEncodingChars(input);
        if (num == -1)
        {
            return value;
        }
        ValueStringBuilder valueStringBuilder;
        if (value.Length < 80)
        {
            Span<char> initialBuffer = stackalloc char[256];
            valueStringBuilder = new ValueStringBuilder(initialBuffer);
        }
        else
        {
            valueStringBuilder = new ValueStringBuilder(value.Length + 200);
        }
        ValueStringBuilder output = valueStringBuilder;
        output.Append(input.Slice(0, num));
        HtmlEncode(input.Slice(num), ref output);
        return output.ToString();
    }
References System.Net.WebUtility.HtmlEncode(), System.Net.WebUtility.IndexOfHtmlEncodingChars(), System.input, and System.value.
Referenced by System.Web.Util.HttpEncoder.HtmlEncode(), System.Web.Util.HttpEncoder.HtmlEncode(), System.Net.WebUtility.HtmlEncode(), and System.Net.WebUtility.HtmlEncode().