Terraria: System.Diagnostics.AsyncStreamReader.FlushMessageQueue
FlushMessageQueue()
bool System.Diagnostics.AsyncStreamReader.FlushMessageQueue (bool rethrowInNewThread) inline private
Definition at line 160 of file AsyncStreamReader.cs.
    {
        try
        {
            while (true)
            {
                string obj;
                lock (_messageQueue)
                {
                    if (_messageQueue.Count == 0)
                    {
                        break;
                    }
                    obj = _messageQueue.Dequeue();
                    goto IL_0038;
                }
                IL_0038:
                if (!_cancelOperation)
                {
                    _userCallBack(obj);
                }
            }
            return false;
        }
        catch (Exception source)
        {
            if (rethrowInNewThread)
            {
                ThreadPool.QueueUserWorkItem(delegate(object edi)
                {
                    ((ExceptionDispatchInfo)edi).Throw();
                }, ExceptionDispatchInfo.Capture(source));
                return true;
            }
            throw;
        }
    }
References System.Diagnostics.AsyncStreamReader._cancelOperation, System.Diagnostics.AsyncStreamReader._messageQueue, System.Diagnostics.AsyncStreamReader._userCallBack, System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.Collections.Generic.Queue< T >.Count, System.Collections.Generic.Queue< T >.Dequeue(), System.obj, System.Threading.ThreadPool.QueueUserWorkItem(), and System.source.
Referenced by System.Diagnostics.AsyncStreamReader.BeginReadLine(), and System.Diagnostics.AsyncStreamReader.ReadBufferAsync().