Terraria: System.Diagnostics.AsyncStreamReader.ReadBufferAsync
ReadBufferAsync()
async Task System.Diagnostics.AsyncStreamReader.ReadBufferAsync () inline private
Definition at line 69 of file AsyncStreamReader.cs.
    {
        while (true)
        {
            try
            {
                int num = await _stream.ReadAsync(new Memory<byte>(_byteBuffer), _cts.Token).ConfigureAwait(continueOnCapturedContext: false);
                if (num == 0)
                {
                    break;
                }
                int chars = _decoder.GetChars(_byteBuffer, 0, num, _charBuffer, 0);
                _sb.Append(_charBuffer, 0, chars);
                MoveLinesFromStringBuilderToMessageQueue();
                goto IL_00e2;
            }
            catch (IOException)
            {
            }
            catch (OperationCanceledException)
            {
            }
            break;
            IL_00e2:
            if (FlushMessageQueue(rethrowInNewThread: true))
            {
                return;
            }
        }
        lock (_messageQueue)
        {
            if (_sb.Length != 0)
            {
                _messageQueue.Enqueue(_sb.ToString());
                _sb.Length = 0;
            }
            _messageQueue.Enqueue(null);
        }
        FlushMessageQueue(rethrowInNewThread: true);
    }
References System.Diagnostics.AsyncStreamReader._byteBuffer, System.Diagnostics.AsyncStreamReader._charBuffer, System.Diagnostics.AsyncStreamReader._cts, System.Diagnostics.AsyncStreamReader._decoder, System.Diagnostics.AsyncStreamReader._messageQueue, System.Diagnostics.AsyncStreamReader._sb, System.Diagnostics.AsyncStreamReader._stream, System.Text.StringBuilder.Append(), System.chars, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Collections.Generic.Queue< T >.Enqueue(), System.Diagnostics.AsyncStreamReader.FlushMessageQueue(), System.Text.Decoder.GetChars(), System.Text.StringBuilder.Length, System.Diagnostics.AsyncStreamReader.MoveLinesFromStringBuilderToMessageQueue(), System.IO.Stream.ReadAsync(), System.Threading.CancellationTokenSource.Token, and System.Text.StringBuilder.ToString().
Referenced by System.Diagnostics.AsyncStreamReader.BeginReadLine().