Terraria: System.Net.WebUtility.UrlEncode
UrlEncode()
static ? string System.Net.WebUtility.UrlEncode (string? value) inline static
Definition at line 678 of file WebUtility.cs.
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }
        int num = 0;
        int num2 = 0;
        foreach (char c in value)
        {
            if (IsUrlSafeChar(c))
            {
                num++;
            }
            else if (c == ' ')
            {
                num2++;
            }
        }
        int num3 = num + num2;
        if (num3 == value.Length)
        {
            if (num2 != 0)
            {
                return value.Replace(' ', '+');
            }
            return value;
        }
        int byteCount = Encoding.UTF8.GetByteCount(value);
        int num4 = byteCount - num3;
        int num5 = num4 * 2;
        byte[] array = new byte[byteCount + num5];
        Encoding.UTF8.GetBytes(value, 0, value.Length, array, num5);
        GetEncodedBytes(array, num5, byteCount, array);
        return Encoding.UTF8.GetString(array);
    }
References System.array, System.byteCount, System.Net.WebUtility.GetEncodedBytes(), System.Net.WebUtility.IsUrlSafeChar(), System.Text.Encoding.UTF8, and System.value.
Referenced by System.Diagnostics.DistributedContextPropagator.InjectBaggage().