Terraria: UIAchievementListItem.GetTrackerValues
GetTrackerValues()
Tuple<decimal, decimal> UIAchievementListItem.GetTrackerValues () inline private
     {
         if (!_achievement.HasTracker)
         {
             return Tuple.Create(0m, 0m);
         }
         IAchievementTracker tracker = _achievement.GetTracker();
         if (tracker.GetTrackerType() == TrackerType.Int)
         {
             AchievementTracker<int> achievementTracker = (AchievementTracker<int>)tracker;
             return Tuple.Create((decimal)achievementTracker.Value, (decimal)achievementTracker.MaxValue);
         }
         if (tracker.GetTrackerType() == TrackerType.Float)
         {
             AchievementTracker<float> achievementTracker2 = (AchievementTracker<float>)tracker;
             return Tuple.Create((decimal)achievementTracker2.Value, (decimal)achievementTracker2.MaxValue);
         }
         return Tuple.Create(0m, 0m);
     }
References _achievement, Achievement.GetTracker(), IAchievementTracker.GetTrackerType(), Achievement.HasTracker, AchievementTracker< T >.MaxValue, and AchievementTracker< T >.Value.
Referenced by DrawSelf().