Terraria: System.Xml.XmlUtf8RawTextWriter.RawText
RawText() [2/2]
unsafe void System.Xml.XmlUtf8RawTextWriter.RawText (string s) inline protected inherited
Definition at line 736 of file XmlUtf8RawTextWriter.cs.
    {
        fixed (char* ptr = s)
        {
            RawText(ptr, ptr + s.Length);
        }
    }
References System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.RawText(), and System.s.
Referenced by System.Xml.XmlUtf8RawTextWriter.RawText(), System.Xml.XmlUtf8RawTextWriter.WriteCharEntity(), System.Xml.HtmlUtf8RawTextWriter.WriteDocType(), System.Xml.XmlUtf8RawTextWriter.WriteDocType(), System.Xml.HtmlUtf8RawTextWriter.WriteEndElement(), System.Xml.XmlUtf8RawTextWriter.WriteEndElement(), System.Xml.XmlUtf8RawTextWriter.WriteEntityRef(), System.Xml.HtmlUtf8RawTextWriter.WriteFullEndElement(), System.Xml.XmlUtf8RawTextWriter.WriteFullEndElement(), System.Xml.HtmlUtf8RawTextWriter.WriteHtmlElementTextBlock(), System.Xml.HtmlUtf8RawTextWriterIndent.WriteIndent(), System.Xml.XmlUtf8RawTextWriterIndent.WriteIndent(), System.Xml.HtmlUtf8RawTextWriter.WriteMetaElement(), System.Xml.XmlUtf8RawTextWriter.WriteNewLine(), System.Xml.XmlUtf8RawTextWriter.WriteProcessingInstruction(), System.Xml.HtmlUtf8RawTextWriter.WriteProcessingInstruction(), System.Xml.HtmlUtf8RawTextWriter.WriteStartAttribute(), System.Xml.HtmlUtf8RawTextWriterIndent.WriteStartAttribute(), System.Xml.XmlUtf8RawTextWriter.WriteStartAttribute(), System.Xml.HtmlUtf8RawTextWriter.WriteStartElement(), System.Xml.HtmlUtf8RawTextWriterIndent.WriteStartElement(), System.Xml.XmlUtf8RawTextWriter.WriteStartElement(), System.Xml.XmlUtf8RawTextWriter.WriteStartNamespaceDeclaration(), System.Xml.XmlUtf8RawTextWriter.WriteSurrogateCharEntity(), and System.Xml.XmlUtf8RawTextWriter.WriteXmlDeclaration().