Terraria: System.Xml.XmlUtf8RawTextWriter.EncodeMultibyteUTF8
EncodeMultibyteUTF8()
static unsafe byte * System.Xml.XmlUtf8RawTextWriter.EncodeMultibyteUTF8 (int ch, byte * pDst) inline static package inherited
Definition at line 1204 of file XmlUtf8RawTextWriter.cs.
    {
        if (ch < 2048)
        {
            *pDst = (byte)(0xFFFFFFC0u | (uint)(ch >> 6));
        }
        else
        {
            *pDst = (byte)(0xFFFFFFE0u | (uint)(ch >> 12));
            pDst++;
            *pDst = (byte)(0xFFFFFF80u | ((uint)(ch >> 6) & 0x3Fu));
        }
        pDst++;
        *pDst = (byte)(0x80u | ((uint)ch & 0x3Fu));
        return pDst + 1;
    }
References System.ch, and System.Xml.Dictionary.
Referenced by System.Xml.XmlUtf8RawTextWriter.CharToUTF8(), System.Xml.XmlUtf8RawTextWriter.EncodeChar(), System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(), System.Xml.XmlUtf8RawTextWriter.RawText(), System.Xml.XmlUtf8RawTextWriter.RawTextNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSection(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSectionNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPi(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPiNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking(), and System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingNoFlush().