Terraria: System.Xml.XmlUtf8RawTextWriter.DisposeAsyncCore
DisposeAsyncCore() [1/2]
override async ValueTask System.Xml.XmlUtf8RawTextWriter.DisposeAsyncCore () inline protected virtual inherited
Reimplemented from System.Xml.XmlWriter.
Definition at line 1468 of file XmlUtf8RawTextWriter.cs.
    {
        try
        {
            await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            _writeToNull = true;
            if (_stream != null)
            {
                try
                {
                    await _stream.FlushAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
                finally
                {
                    try
                    {
                        if (_closeOutput)
{
                            await _stream.DisposeAsync().ConfigureAwait(continueOnCapturedContext: false);
                        }
                    }
                    finally
                    {
                        _stream = null;
                    }
                }
            }
        }
    }
References System.Xml.XmlUtf8RawTextWriter._closeOutput, System.Xml.XmlUtf8RawTextWriter._stream, System.Xml.XmlUtf8RawTextWriter._writeToNull, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.IO.Stream.DisposeAsync(), System.IO.Stream.FlushAsync(), and System.Xml.XmlUtf8RawTextWriter.FlushBufferAsync().