Terraria: System.Xml.XmlUtf8RawTextWriter.WriteDocTypeAsync
WriteDocTypeAsync() [1/2]
override async Task System.Xml.XmlUtf8RawTextWriter.WriteDocTypeAsync (string name, string pubid, string sysid, string subset) inline
Definition at line 1501 of file XmlUtf8RawTextWriter.cs.
    {
        CheckAsyncCall();
        await RawTextAsync("<!DOCTYPE ").ConfigureAwait(continueOnCapturedContext: false);
        await RawTextAsync(name).ConfigureAwait(continueOnCapturedContext: false);
        if (pubid != null)
        {
            await RawTextAsync(" PUBLIC \"").ConfigureAwait(continueOnCapturedContext: false);
            await RawTextAsync(pubid).ConfigureAwait(continueOnCapturedContext: false);
            await RawTextAsync("\" \"").ConfigureAwait(continueOnCapturedContext: false);
            if (sysid != null)
            {
                await RawTextAsync(sysid).ConfigureAwait(continueOnCapturedContext: false);
            }
            _bufBytes[_bufPos++] = 34;
        }
        else if (sysid != null)
        {
            await RawTextAsync(" SYSTEM \"").ConfigureAwait(continueOnCapturedContext: false);
            await RawTextAsync(sysid).ConfigureAwait(continueOnCapturedContext: false);
            _bufBytes[_bufPos++] = 34;
        }
        else
        {
            _bufBytes[_bufPos++] = 32;
        }
        if (subset != null)
        {
            _bufBytes[_bufPos++] = 91;
            await RawTextAsync(subset).ConfigureAwait(continueOnCapturedContext: false);
            _bufBytes[_bufPos++] = 93;
        }
        _bufBytes[_bufPos++] = 62;
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, and System.Xml.XmlUtf8RawTextWriter.RawTextAsync().