Terraria: System.Xml.XmlUtf8RawTextWriter._WriteElementTextBlockAsync
_WriteElementTextBlockAsync()
async Task System.Xml.XmlUtf8RawTextWriter._WriteElementTextBlockAsync (bool newLine, string text, int curIndex, int leftCount) inline private inherited
Definition at line 2198 of file XmlUtf8RawTextWriter.cs.
    {
        bool needWriteNewLine = false;
        if (!newLine)
        {
            await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            await RawTextAsync(_newLineChars).ConfigureAwait(continueOnCapturedContext: false);
            curIndex++;
            leftCount--;
        }
        int writeLen;
        do
        {
            writeLen = WriteElementTextBlockNoFlush(text, curIndex, leftCount, out needWriteNewLine);
            curIndex += writeLen;
            leftCount -= writeLen;
            if (needWriteNewLine)
            {
                await RawTextAsync(_newLineChars).ConfigureAwait(continueOnCapturedContext: false);
                curIndex++;
                leftCount--;
            }
            else if (writeLen >= 0)
            {
                await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        while (writeLen >= 0 || needWriteNewLine);
    }
References System.Xml.XmlUtf8RawTextWriter._newLineChars, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.FlushBufferAsync(), System.Xml.XmlUtf8RawTextWriter.RawTextAsync(), System.text, and System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockNoFlush().
Referenced by System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockAsync().