Terraria: System.Xml.XmlUtf8RawTextWriter.EncodeSurrogate
EncodeSurrogate()
static unsafe byte * System.Xml.XmlUtf8RawTextWriter.EncodeSurrogate (char * pSrc, char * pSrcEnd, byte * pDst) inline static private inherited
Definition at line 1137 of file XmlUtf8RawTextWriter.cs.
    {
        int num = *pSrc;
        if (num <= 56319)
        {
            if (pSrc + 1 < pSrcEnd)
            {
                int num2 = pSrc[1];
                if (num2 >= 56320 && (System.LocalAppContextSwitches.DontThrowOnInvalidSurrogatePairs || num2 <= 57343))
                {
                    num = XmlCharType.CombineSurrogateChar(num2, num);
                    *pDst = (byte)(0xF0u | (uint)(num >> 18));
                    pDst[1] = (byte)(0x80u | ((uint)(num >> 12) & 0x3Fu));
                    pDst[2] = (byte)(0x80u | ((uint)(num >> 6) & 0x3Fu));
                    pDst[3] = (byte)(0x80u | ((uint)num & 0x3Fu));
                    pDst += 4;
                    return pDst;
                }
                throw XmlConvert.CreateInvalidSurrogatePairException((char)num2, (char)num);
            }
            throw new ArgumentException(System.SR.Xml_InvalidSurrogateMissingLowChar);
        }
        throw XmlConvert.CreateInvalidHighSurrogateCharException((char)num);
    }
References System.Xml.ArgumentException, System.Xml.XmlCharType.CombineSurrogateChar(), System.Xml.XmlConvert.CreateInvalidHighSurrogateCharException(), System.Xml.XmlConvert.CreateInvalidSurrogatePairException(), System.Xml.Dictionary, System.LocalAppContextSwitches.DontThrowOnInvalidSurrogatePairs, and System.SR.Xml_InvalidSurrogateMissingLowChar.
Referenced by System.Xml.XmlUtf8RawTextWriter.CharToUTF8(), System.Xml.XmlUtf8RawTextWriter.EncodeChar(), System.Xml.XmlUtf8RawTextWriter.RawText(), System.Xml.XmlUtf8RawTextWriter.RawTextNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSection(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSectionNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPi(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPiNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking(), and System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingNoFlush().