Terraria: System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar
InvalidXmlChar()
unsafe byte * System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar (int ch, byte * pDst, bool entitize) inline private inherited
Definition at line 1162 of file XmlUtf8RawTextWriter.cs.
    {
        if (_checkCharacters)
        {
            throw XmlConvert.CreateInvalidCharException((char)ch, '\0');
        }
        if (entitize)
        {
            return CharEntity(pDst, (char)ch);
        }
        if (ch < 128)
        {
            *pDst = (byte)ch;
            pDst++;
        }
        else
        {
            pDst = EncodeMultibyteUTF8(ch, pDst);
        }
        return pDst;
    }
References System.Xml.XmlUtf8RawTextWriter._checkCharacters, System.ch, System.Xml.XmlUtf8RawTextWriter.CharEntity(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.Dictionary, and System.Xml.XmlUtf8RawTextWriter.EncodeMultibyteUTF8().
Referenced by System.Xml.XmlUtf8RawTextWriter.EncodeChar(), System.Xml.XmlUtf8RawTextWriter.RawText(), System.Xml.XmlUtf8RawTextWriter.RawTextNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSection(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSectionNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPi(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPiNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking(), and System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingNoFlush().