Terraria: System.Xml.XmlUtf8RawTextWriter.WriteXmlDeclarationAsync
WriteXmlDeclarationAsync() [2/2]
override async Task System.Xml.XmlUtf8RawTextWriter.WriteXmlDeclarationAsync (XmlStandalone standalone) inline package virtual inherited
Reimplemented from System.Xml.XmlRawWriter.
Definition at line 1437 of file XmlUtf8RawTextWriter.cs.
    {
        CheckAsyncCall();
        if (!_omitXmlDeclaration && !_autoXmlDeclaration)
        {
            await RawTextAsync("<?xml version=\"").ConfigureAwait(continueOnCapturedContext: false);
            await RawTextAsync("1.0").ConfigureAwait(continueOnCapturedContext: false);
            if (_encoding != null)
            {
                await RawTextAsync("\" encoding=\"").ConfigureAwait(continueOnCapturedContext: false);
                await RawTextAsync(_encoding.WebName).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (standalone != 0)
            {
                await RawTextAsync("\" standalone=\"").ConfigureAwait(continueOnCapturedContext: false);
                await RawTextAsync((standalone == XmlStandalone.Yes) ? "yes" : "no").ConfigureAwait(continueOnCapturedContext: false);
            }
            await RawTextAsync("\"?>").ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Xml.XmlUtf8RawTextWriter._autoXmlDeclaration, System.Xml.XmlUtf8RawTextWriter._encoding, System.Xml.XmlUtf8RawTextWriter._omitXmlDeclaration, System.Xml.XmlUtf8RawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.RawTextAsync(), and System.Text.Encoding.WebName.