Terraria: System.Xml.XmlUtf8RawTextWriter.CharToUTF8
CharToUTF8()
static unsafe void System.Xml.XmlUtf8RawTextWriter.CharToUTF8 (ref char * pSrc, char * pSrcEnd, ref byte * pDst) inline static package inherited
Definition at line 1221 of file XmlUtf8RawTextWriter.cs.
    {
        int num = *pSrc;
        if (num <= 127)
        {
            *pDst = (byte)num;
            pDst++;
            pSrc++;
        }
        else if (XmlCharType.IsSurrogate(num))
        {
            pDst = EncodeSurrogate(pSrc, pSrcEnd, pDst);
            pSrc += 2;
        }
        else
        {
            pDst = EncodeMultibyteUTF8(num, pDst);
            pSrc++;
        }
    }
References System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.EncodeMultibyteUTF8(), System.Xml.XmlUtf8RawTextWriter.EncodeSurrogate(), and System.Xml.XmlCharType.IsSurrogate().
Referenced by System.Xml.HtmlEncodedRawTextWriter.WriteUriAttributeText(), and System.Xml.HtmlUtf8RawTextWriter.WriteUriAttributeText().