Terraria: System.Xml.XmlUtf8RawTextWriter.RawTextNoFlush
RawTextNoFlush() [1/2]
unsafe int System.Xml.XmlUtf8RawTextWriter.RawTextNoFlush (char * pSrcBegin, char * pSrcEnd) inline protected inherited
Definition at line 2231 of file XmlUtf8RawTextWriter.cs.
    {
        fixed (byte* ptr = _bufBytes)
        {
            byte* ptr2 = ptr + _bufPos;
            char* ptr3 = pSrcBegin;
            int num = 0;
            while (true)
            {
                byte* ptr4 = ptr2 + (pSrcEnd - ptr3);
                if (ptr4 > ptr + _bufLen)
                {
                    ptr4 = ptr + _bufLen;
                }
                for (; ptr2 < ptr4; ptr2++)
                {
                    if ((num = *ptr3) > 127)
                    {
                        break;
                    }
                    ptr3++;
                    *ptr2 = (byte)num;
                }
                if (ptr3 >= pSrcEnd)
                {
                    break;
                }
                if (ptr2 >= ptr4)
                {
                    _bufPos = (int)(ptr2 - ptr);
                    return (int)(ptr3 - pSrcBegin);
                }
                if (XmlCharType.IsSurrogate(num))
                {
                    ptr2 = EncodeSurrogate(ptr3, pSrcEnd, ptr2);
                    ptr3 += 2;
                }
                else if (num <= 127 || num >= 65534)
                {
                    ptr2 = InvalidXmlChar(num, ptr2, entitize: false);
                    ptr3++;
                }
                else
                {
                    ptr2 = EncodeMultibyteUTF8(num, ptr2);
                    ptr3++;
                }
            }
            _bufPos = (int)(ptr2 - ptr);
        }
        return -1;
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.EncodeMultibyteUTF8(), System.Xml.XmlUtf8RawTextWriter.EncodeSurrogate(), System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(), and System.Xml.XmlCharType.IsSurrogate().
Referenced by System.Xml.XmlUtf8RawTextWriter._RawTextAsync(), System.Xml.XmlUtf8RawTextWriter.RawTextAsync(), System.Xml.XmlUtf8RawTextWriter.RawTextAsync(), and System.Xml.XmlUtf8RawTextWriter.RawTextNoFlush().