Terraria: System.Xml.XmlUtf8RawTextWriter.WriteNamespaceDeclaration
WriteNamespaceDeclaration()
override void System.Xml.XmlUtf8RawTextWriter.WriteNamespaceDeclaration (string prefix, string namespaceName) inline package inherited
Definition at line 261 of file XmlUtf8RawTextWriter.cs.
    {
        WriteStartNamespaceDeclaration(prefix);
        WriteString(namespaceName);
        WriteEndNamespaceDeclaration();
    }
References System.Xml.Dictionary, System.prefix, System.Xml.XmlUtf8RawTextWriter.WriteEndNamespaceDeclaration(), System.Xml.XmlUtf8RawTextWriter.WriteStartNamespaceDeclaration(), and System.Xml.XmlUtf8RawTextWriter.WriteString().