Terraria: System.Xml.XmlUtf8RawTextWriter.FlushBuffer
FlushBuffer()
virtual void System.Xml.XmlUtf8RawTextWriter.FlushBuffer () inline protected virtual inherited
Reimplemented in System.Xml.HtmlUtf8RawTextWriterIndent.
Definition at line 495 of file XmlUtf8RawTextWriter.cs.
    {
        try
        {
            if (!_writeToNull && _bufPos - 1 > 0)
            {
                _stream.Write(_bufBytes, 1, _bufPos - 1);
            }
        }
        catch
        {
            _writeToNull = true;
            throw;
        }
        finally
        {
            _bufBytes[0] = _bufBytes[_bufPos - 1];
            if (IsSurrogateByte(_bufBytes[0]))
            {
                _bufBytes[1] = _bufBytes[_bufPos];
                _bufBytes[2] = _bufBytes[_bufPos + 1];
                _bufBytes[3] = _bufBytes[_bufPos + 2];
            }
            _textPos = ((_textPos == _bufPos) ? 1 : 0);
            _attrEndPos = ((_attrEndPos == _bufPos) ? 1 : 0);
            _contentPos = 0;
            _cdataPos = 0;
            _bufPos = 1;
        }
    }
References System.Xml.XmlUtf8RawTextWriter._attrEndPos, System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._cdataPos, System.Xml.XmlUtf8RawTextWriter._contentPos, System.Xml.XmlUtf8RawTextWriter._stream, System.Xml.XmlUtf8RawTextWriter._textPos, System.Xml.XmlUtf8RawTextWriter._writeToNull, System.Xml.XmlUtf8RawTextWriter.IsSurrogateByte(), and System.IO.Stream.Write().
Referenced by System.Xml.XmlUtf8RawTextWriter.Close(), System.Xml.XmlUtf8RawTextWriter.Flush(), System.Xml.XmlUtf8RawTextWriter.RawText(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSection(), System.Xml.XmlUtf8RawTextWriter.WriteCharEntity(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPi(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteEntityRef(), System.Xml.HtmlUtf8RawTextWriter.WriteHtmlAttributeText(), System.Xml.HtmlUtf8RawTextWriter.WriteProcessingInstruction(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking(), and System.Xml.HtmlUtf8RawTextWriter.WriteUriAttributeText().