Terraria: System.Xml.XmlUtf8RawTextWriter.WriteCharEntityAsync
WriteCharEntityAsync()
override async Task System.Xml.XmlUtf8RawTextWriter.WriteCharEntityAsync (char ch) inline virtual
Reimplemented from System.Xml.XmlRawWriter.
Reimplemented in System.Xml.XmlUtf8RawTextWriterIndent.
Definition at line 1716 of file XmlUtf8RawTextWriter.cs.
    {
        CheckAsyncCall();
        int num = ch;
        string text = num.ToString("X", NumberFormatInfo.InvariantInfo);
        if (_checkCharacters && !XmlCharType.IsCharData(ch))
        {
            throw XmlConvert.CreateInvalidCharException(ch, '\0');
        }
        _bufBytes[_bufPos++] = 38;
        _bufBytes[_bufPos++] = 35;
        _bufBytes[_bufPos++] = 120;
        await RawTextAsync(text).ConfigureAwait(continueOnCapturedContext: false);
        _bufBytes[_bufPos++] = 59;
        if (_bufPos > _bufLen)
        {
            await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        _textPos = _bufPos;
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._checkCharacters, System.Xml.XmlUtf8RawTextWriter._textPos, System.ch, System.Xml.XmlUtf8RawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.FlushBufferAsync(), System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.XmlCharType.IsCharData(), System.Xml.XmlUtf8RawTextWriter.RawTextAsync(), and System.text.