Terraria: System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock
WriteAttributeTextBlock()
unsafe void System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock (char * pSrc, char * pSrcEnd) inline protected inherited
Definition at line 530 of file XmlUtf8RawTextWriter.cs.
    {
        fixed (byte* ptr = _bufBytes)
        {
            byte* ptr2 = ptr + _bufPos;
            int num = 0;
            while (true)
            {
                byte* ptr3 = ptr2 + (pSrcEnd - pSrc);
                if (ptr3 > ptr + _bufLen)
                {
                    ptr3 = ptr + _bufLen;
                }
                while (ptr2 < ptr3 && XmlCharType.IsAttributeValueChar((char)(num = *pSrc)) && num <= 127)
                {
                    *ptr2 = (byte)num;
                    ptr2++;
                    pSrc++;
                }
                if (pSrc >= pSrcEnd)
                {
                    break;
                }
                if (ptr2 >= ptr3)
                {
                    _bufPos = (int)(ptr2 - ptr);
                    FlushBuffer();
                    ptr2 = ptr + 1;
                    continue;
                }
                switch (num)
                {
                case 38:
                    ptr2 = AmpEntity(ptr2);
                    break;
                case 60:
                    ptr2 = LtEntity(ptr2);
                    break;
                case 62:
                    ptr2 = GtEntity(ptr2);
                    break;
                case 34:
                    ptr2 = QuoteEntity(ptr2);
                    break;
                case 39:
                    *ptr2 = (byte)num;
                    ptr2++;
                    break;
                case 9:
                    if (_newLineHandling == NewLineHandling.None)
                    {
                        *ptr2 = (byte)num;
                        ptr2++;
                    }
                    else
                    {
                        ptr2 = TabEntity(ptr2);
                    }
                    break;
                case 13:
                    if (_newLineHandling == NewLineHandling.None)
                    {
                        *ptr2 = (byte)num;
                        ptr2++;
                    }
                    else
                    {
                        ptr2 = CarriageReturnEntity(ptr2);
                    }
                    break;
                case 10:
                    if (_newLineHandling == NewLineHandling.None)
                    {
                        *ptr2 = (byte)num;
                        ptr2++;
                    }
                    else
                    {
                        ptr2 = LineFeedEntity(ptr2);
                    }
                    break;
                default:
                    if (XmlCharType.IsSurrogate(num))
                    {
                        ptr2 = EncodeSurrogate(pSrc, pSrcEnd, ptr2);
                        pSrc += 2;
                    }
                    else if (num <= 127 || num >= 65534)
                    {
                        ptr2 = InvalidXmlChar(num, ptr2, entitize: true);
                        pSrc++;
                    }
                    else
                    {
                        ptr2 = EncodeMultibyteUTF8(num, ptr2);
                        pSrc++;
                    }
                    continue;
                }
                pSrc++;
            }
            _bufPos = (int)(ptr2 - ptr);
        }
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._newLineHandling, System.Xml.XmlUtf8RawTextWriter.AmpEntity(), System.Xml.XmlUtf8RawTextWriter.CarriageReturnEntity(), System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.EncodeMultibyteUTF8(), System.Xml.XmlUtf8RawTextWriter.EncodeSurrogate(), System.Xml.XmlUtf8RawTextWriter.FlushBuffer(), System.Xml.XmlUtf8RawTextWriter.GtEntity(), System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsSurrogate(), System.Xml.XmlUtf8RawTextWriter.LineFeedEntity(), System.Xml.XmlUtf8RawTextWriter.LtEntity(), System.Xml.XmlUtf8RawTextWriter.QuoteEntity(), and System.Xml.XmlUtf8RawTextWriter.TabEntity().
Referenced by System.Xml.HtmlUtf8RawTextWriter.WriteChars(), System.Xml.XmlUtf8RawTextWriter.WriteChars(), System.Xml.HtmlUtf8RawTextWriter.WriteHtmlAttributeTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteString(), and System.Xml.XmlUtf8RawTextWriter.WriteWhitespace().