Terraria: System.Xml.XmlUtf8RawTextWriter.WriteEntityRefAsync
WriteEntityRefAsync()
override async Task System.Xml.XmlUtf8RawTextWriter.WriteEntityRefAsync (string name) inline virtual
Reimplemented from System.Xml.XmlWriter.
Reimplemented in System.Xml.XmlUtf8RawTextWriterIndent.
Definition at line 1703 of file XmlUtf8RawTextWriter.cs.
    {
        CheckAsyncCall();
        _bufBytes[_bufPos++] = 38;
        await RawTextAsync(name).ConfigureAwait(continueOnCapturedContext: false);
        _bufBytes[_bufPos++] = 59;
        if (_bufPos > _bufLen)
        {
            await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        _textPos = _bufPos;
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._textPos, System.Xml.XmlUtf8RawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.FlushBufferAsync(), and System.Xml.XmlUtf8RawTextWriter.RawTextAsync().