Terraria: System.Xml.XmlUtf8RawTextWriter.WriteStartNamespaceDeclarationAsync
WriteStartNamespaceDeclarationAsync()
override async Task System.Xml.XmlUtf8RawTextWriter.WriteStartNamespaceDeclarationAsync (string prefix) inline package virtual inherited
Reimplemented from System.Xml.XmlRawWriter.
Definition at line 1622 of file XmlUtf8RawTextWriter.cs.
    {
        CheckAsyncCall();
        if (prefix.Length == 0)
        {
            await RawTextAsync(" xmlns=\"").ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            await RawTextAsync(" xmlns:").ConfigureAwait(continueOnCapturedContext: false);
            await RawTextAsync(prefix).ConfigureAwait(continueOnCapturedContext: false);
            _bufBytes[_bufPos++] = 61;
            _bufBytes[_bufPos++] = 34;
        }
        _inAttributeValue = true;
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._inAttributeValue, System.Xml.XmlUtf8RawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.prefix, and System.Xml.XmlUtf8RawTextWriter.RawTextAsync().
Referenced by System.Xml.XmlUtf8RawTextWriter.WriteNamespaceDeclarationAsync().