Terraria: System.Xml.XmlUtf8RawTextWriter.RawTextAsync
RawTextAsync() [1/2]
Task System.Xml.XmlUtf8RawTextWriter.RawTextAsync (string text) inline protected inherited
Definition at line 2298 of file XmlUtf8RawTextWriter.cs.
    {
        int num = RawTextNoFlush(text, 0, text.Length);
        if (num < 0)
        {
            return Task.CompletedTask;
        }
        return _RawTextAsync(text, num, text.Length - num);
    }
References System.Xml.XmlUtf8RawTextWriter._RawTextAsync(), System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.XmlUtf8RawTextWriter.RawTextNoFlush(), and System.text.
Referenced by System.Xml.XmlUtf8RawTextWriter._RawTextAsync(), System.Xml.XmlUtf8RawTextWriter._WriteElementTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSectionAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCharEntityAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPiAsync(), System.Xml.XmlUtf8RawTextWriter.WriteDocTypeAsync(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter.WriteEndElementAsync(), System.Xml.XmlUtf8RawTextWriter.WriteEntityRefAsync(), System.Xml.XmlUtf8RawTextWriter.WriteFullEndElementAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteIndentAsync(), System.Xml.XmlUtf8RawTextWriter.WriteProcessingInstructionAsync(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingAsync(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingAsync(), System.Xml.XmlUtf8RawTextWriter.WriteStartAttributeAsync(), System.Xml.XmlUtf8RawTextWriter.WriteStartElementAsync(), System.Xml.XmlUtf8RawTextWriter.WriteStartNamespaceDeclarationAsync(), System.Xml.XmlUtf8RawTextWriter.WriteSurrogateCharEntityAsync(), and System.Xml.XmlUtf8RawTextWriter.WriteXmlDeclarationAsync().