Terraria: System.Xml.XmlUtf8RawTextWriter.WriteCDataSectionAsync
WriteCDataSectionAsync()
async Task System.Xml.XmlUtf8RawTextWriter.WriteCDataSectionAsync (string text) inline protected inherited
Definition at line 2807 of file XmlUtf8RawTextWriter.cs.
    {
        if (text.Length == 0)
        {
            if (_bufPos >= _bufLen)
            {
                await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            return;
        }
        int curIndex = 0;
        int leftCount = text.Length;
        bool needWriteNewLine = false;
        int writeLen;
        do
        {
            writeLen = WriteCDataSectionNoFlush(text, curIndex, leftCount, out needWriteNewLine);
            curIndex += writeLen;
            leftCount -= writeLen;
            if (needWriteNewLine)
            {
                await RawTextAsync(_newLineChars).ConfigureAwait(continueOnCapturedContext: false);
                curIndex++;
                leftCount--;
            }
            else if (writeLen >= 0)
            {
                await FlushBufferAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        while (writeLen >= 0 || needWriteNewLine);
    }
References System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._newLineChars, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.FlushBufferAsync(), System.Xml.XmlUtf8RawTextWriter.RawTextAsync(), System.text, and System.Xml.XmlUtf8RawTextWriter.WriteCDataSectionNoFlush().
Referenced by System.Xml.XmlUtf8RawTextWriter.WriteCDataAsync().