Terraria: System.Xml.XmlUtf8RawTextWriter.WriteRawAsync
WriteRawAsync() [2/2]
override async Task System.Xml.XmlUtf8RawTextWriter.WriteRawAsync (string data) inline virtual
Reimplemented from System.Xml.XmlRawWriter.
Reimplemented in System.Xml.XmlUtf8RawTextWriterIndent.
Definition at line 1786 of file XmlUtf8RawTextWriter.cs.
    {
        CheckAsyncCall();
        await WriteRawWithCharCheckingAsync(data).ConfigureAwait(continueOnCapturedContext: false);
        _textPos = _bufPos;
    }
References System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._textPos, System.Xml.XmlUtf8RawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, and System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingAsync().