Terraria: System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingNoFlush
WriteRawWithCharCheckingNoFlush() [1/3]
unsafe int System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingNoFlush (char * pSrcBegin, char * pSrcEnd, out bool needWriteNewLine) inline protected inherited
Definition at line 2363 of file XmlUtf8RawTextWriter.cs.
    {
        needWriteNewLine = false;
        fixed (byte* ptr2 = _bufBytes)
        {
            char* ptr = pSrcBegin;
            byte* ptr3 = ptr2 + _bufPos;
            int num = 0;
            while (true)
            {
                byte* ptr4 = ptr3 + (pSrcEnd - ptr);
                if (ptr4 > ptr2 + _bufLen)
                {
                    ptr4 = ptr2 + _bufLen;
                }
                while (ptr3 < ptr4 && XmlCharType.IsTextChar((char)(num = *ptr)) && num <= 127)
                {
                    *ptr3 = (byte)num;
                    ptr3++;
                    ptr++;
                }
                if (ptr >= pSrcEnd)
                {
                    break;
                }
                if (ptr3 >= ptr4)
                {
                    _bufPos = (int)(ptr3 - ptr2);
                    return (int)(ptr - pSrcBegin);
                }
                switch (num)
                {
                case 9:
                case 38:
                case 60:
                case 93:
                    *ptr3 = (byte)num;
                    ptr3++;
                    break;
                case 13:
                    if (_newLineHandling == NewLineHandling.Replace)
                    {
                        if (ptr + 1 < pSrcEnd && ptr[1] == '\n')
{
                            ptr++;
                        }
                        _bufPos = (int)(ptr3 - ptr2);
                        needWriteNewLine = true;
                        return (int)(ptr - pSrcBegin);
                    }
                    *ptr3 = (byte)num;
                    ptr3++;
                    break;
                case 10:
                    if (_newLineHandling == NewLineHandling.Replace)
                    {
                        _bufPos = (int)(ptr3 - ptr2);
                        needWriteNewLine = true;
                        return (int)(ptr - pSrcBegin);
                    }
                    *ptr3 = (byte)num;
                    ptr3++;
                    break;
                default:
                    if (XmlCharType.IsSurrogate(num))
                    {
                        ptr3 = EncodeSurrogate(ptr, pSrcEnd, ptr3);
                        ptr += 2;
                    }
                    else if (num <= 127 || num >= 65534)
                    {
                        ptr3 = InvalidXmlChar(num, ptr3, entitize: false);
                        ptr++;
                    }
                    else
                    {
                        ptr3 = EncodeMultibyteUTF8(num, ptr3);
                        ptr++;
                    }
                    continue;
                }
                ptr++;
            }
            _bufPos = (int)(ptr3 - ptr2);
        }
        return -1;
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._newLineHandling, System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.EncodeMultibyteUTF8(), System.Xml.XmlUtf8RawTextWriter.EncodeSurrogate(), System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(), System.Xml.XmlCharType.IsSurrogate(), and System.Xml.XmlCharType.IsTextChar().
Referenced by System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingAsync(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingAsync(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingNoFlush(), and System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingNoFlush().