Terraria: System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockNoFlush
WriteAttributeTextBlockNoFlush() [1/3]
unsafe int System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockNoFlush (char * pSrc, char * pSrcEnd) inline protected inherited
Definition at line 1834 of file XmlUtf8RawTextWriter.cs.
    {
        char* ptr = pSrc;
        fixed (byte* ptr2 = _bufBytes)
        {
            byte* ptr3 = ptr2 + _bufPos;
            int num = 0;
            while (true)
            {
                byte* ptr4 = ptr3 + (pSrcEnd - pSrc);
                if (ptr4 > ptr2 + _bufLen)
                {
                    ptr4 = ptr2 + _bufLen;
                }
                while (ptr3 < ptr4 && XmlCharType.IsAttributeValueChar((char)(num = *pSrc)) && num <= 127)
                {
                    *ptr3 = (byte)num;
                    ptr3++;
                    pSrc++;
                }
                if (pSrc >= pSrcEnd)
                {
                    break;
                }
                if (ptr3 >= ptr4)
                {
                    _bufPos = (int)(ptr3 - ptr2);
                    return (int)(pSrc - ptr);
                }
                switch (num)
                {
                case 38:
                    ptr3 = AmpEntity(ptr3);
                    break;
                case 60:
                    ptr3 = LtEntity(ptr3);
                    break;
                case 62:
                    ptr3 = GtEntity(ptr3);
                    break;
                case 34:
                    ptr3 = QuoteEntity(ptr3);
                    break;
                case 39:
                    *ptr3 = (byte)num;
                    ptr3++;
                    break;
                case 9:
                    if (_newLineHandling == NewLineHandling.None)
                    {
                        *ptr3 = (byte)num;
                        ptr3++;
                    }
                    else
                    {
                        ptr3 = TabEntity(ptr3);
                    }
                    break;
                case 13:
                    if (_newLineHandling == NewLineHandling.None)
                    {
                        *ptr3 = (byte)num;
                        ptr3++;
                    }
                    else
                    {
                        ptr3 = CarriageReturnEntity(ptr3);
                    }
                    break;
                case 10:
                    if (_newLineHandling == NewLineHandling.None)
                    {
                        *ptr3 = (byte)num;
                        ptr3++;
                    }
                    else
                    {
                        ptr3 = LineFeedEntity(ptr3);
                    }
                    break;
                default:
                    if (XmlCharType.IsSurrogate(num))
                    {
                        ptr3 = EncodeSurrogate(pSrc, pSrcEnd, ptr3);
                        pSrc += 2;
                    }
                    else if (num <= 127 || num >= 65534)
                    {
                        ptr3 = InvalidXmlChar(num, ptr3, entitize: true);
                        pSrc++;
                    }
                    else
                    {
                        ptr3 = EncodeMultibyteUTF8(num, ptr3);
                        pSrc++;
                    }
                    continue;
                }
                pSrc++;
            }
            _bufPos = (int)(ptr3 - ptr2);
        }
        return -1;
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._newLineHandling, System.Xml.XmlUtf8RawTextWriter.AmpEntity(), System.Xml.XmlUtf8RawTextWriter.CarriageReturnEntity(), System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.EncodeMultibyteUTF8(), System.Xml.XmlUtf8RawTextWriter.EncodeSurrogate(), System.Xml.XmlUtf8RawTextWriter.GtEntity(), System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsSurrogate(), System.Xml.XmlUtf8RawTextWriter.LineFeedEntity(), System.Xml.XmlUtf8RawTextWriter.LtEntity(), System.Xml.XmlUtf8RawTextWriter.QuoteEntity(), and System.Xml.XmlUtf8RawTextWriter.TabEntity().
Referenced by System.Xml.XmlUtf8RawTextWriter._WriteAttributeTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockNoFlush(), and System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockNoFlush().