Terraria: System.Xml.XmlUtf8RawTextWriter.CheckAsyncCall
CheckAsyncCall()
void System.Xml.XmlUtf8RawTextWriter.CheckAsyncCall () inline protected inherited
Definition at line 1429 of file XmlUtf8RawTextWriter.cs.
    {
        if (!_useAsync)
        {
            throw new InvalidOperationException(System.SR.Xml_WriterAsyncNotSetException);
        }
    }
References System.Xml.XmlUtf8RawTextWriter._useAsync, and System.SR.Xml_WriterAsyncNotSetException.
Referenced by System.Xml.XmlUtf8RawTextWriter.FlushAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteBase64Async(), System.Xml.XmlUtf8RawTextWriter.WriteCDataAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteCDataAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCharEntityAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteCharEntityAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCharsAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteCharsAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCommentAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteCommentAsync(), System.Xml.XmlUtf8RawTextWriter.WriteDocTypeAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteDocTypeAsync(), System.Xml.XmlUtf8RawTextWriter.WriteEndAttributeAsync(), System.Xml.XmlUtf8RawTextWriter.WriteEndElementAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteEndElementAsync(), System.Xml.XmlUtf8RawTextWriter.WriteEndNamespaceDeclarationAsync(), System.Xml.XmlUtf8RawTextWriter.WriteEntityRefAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteEntityRefAsync(), System.Xml.XmlUtf8RawTextWriter.WriteFullEndElementAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteFullEndElementAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteIndentAsync(), System.Xml.XmlUtf8RawTextWriter.WriteNamespaceDeclarationAsync(), System.Xml.XmlUtf8RawTextWriter.WriteProcessingInstructionAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteProcessingInstructionAsync(), System.Xml.XmlUtf8RawTextWriter.WriteRawAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteRawAsync(), System.Xml.XmlUtf8RawTextWriter.WriteRawAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteRawAsync(), System.Xml.XmlUtf8RawTextWriter.WriteStartAttributeAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteStartAttributeAsync(), System.Xml.XmlUtf8RawTextWriter.WriteStartElementAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteStartElementAsync(), System.Xml.XmlUtf8RawTextWriter.WriteStartNamespaceDeclarationAsync(), System.Xml.XmlUtf8RawTextWriter.WriteStringAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteStringAsync(), System.Xml.XmlUtf8RawTextWriter.WriteSurrogateCharEntityAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteSurrogateCharEntityAsync(), System.Xml.XmlUtf8RawTextWriter.WriteWhitespaceAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteWhitespaceAsync(), System.Xml.XmlUtf8RawTextWriter.WriteXmlDeclarationAsync(), and System.Xml.XmlUtf8RawTextWriter.WriteXmlDeclarationAsync().