Terraria: System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockNoFlush
WriteElementTextBlockNoFlush() [1/3]
unsafe int System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockNoFlush (char * pSrc, char * pSrcEnd, out bool needWriteNewLine) inline protected inherited
Definition at line 2017 of file XmlUtf8RawTextWriter.cs.
    {
        needWriteNewLine = false;
        char* ptr = pSrc;
        fixed (byte* ptr2 = _bufBytes)
        {
            byte* ptr3 = ptr2 + _bufPos;
            int num = 0;
            while (true)
            {
                byte* ptr4 = ptr3 + (pSrcEnd - pSrc);
                if (ptr4 > ptr2 + _bufLen)
                {
                    ptr4 = ptr2 + _bufLen;
                }
                while (ptr3 < ptr4 && XmlCharType.IsAttributeValueChar((char)(num = *pSrc)) && num <= 127)
                {
                    *ptr3 = (byte)num;
                    ptr3++;
                    pSrc++;
                }
                if (pSrc >= pSrcEnd)
                {
                    break;
                }
                if (ptr3 >= ptr4)
                {
                    _bufPos = (int)(ptr3 - ptr2);
                    return (int)(pSrc - ptr);
                }
                switch (num)
                {
                case 38:
                    ptr3 = AmpEntity(ptr3);
                    break;
                case 60:
                    ptr3 = LtEntity(ptr3);
                    break;
                case 62:
                    ptr3 = GtEntity(ptr3);
                    break;
                case 9:
                case 34:
                case 39:
                    *ptr3 = (byte)num;
                    ptr3++;
                    break;
                case 10:
                    if (_newLineHandling == NewLineHandling.Replace)
                    {
                        _bufPos = (int)(ptr3 - ptr2);
                        needWriteNewLine = true;
                        return (int)(pSrc - ptr);
                    }
                    *ptr3 = (byte)num;
                    ptr3++;
                    break;
                case 13:
                    switch (_newLineHandling)
                    {
                    case NewLineHandling.Replace:
                        if (pSrc + 1 < pSrcEnd && pSrc[1] == '\n')
{
                            pSrc++;
                        }
                        _bufPos = (int)(ptr3 - ptr2);
                        needWriteNewLine = true;
                        return (int)(pSrc - ptr);
                    case NewLineHandling.Entitize:
                        ptr3 = CarriageReturnEntity(ptr3);
                        break;
                    case NewLineHandling.None:
                        *ptr3 = (byte)num;
                        ptr3++;
                        break;
                    }
                    break;
                default:
                    if (XmlCharType.IsSurrogate(num))
                    {
                        ptr3 = EncodeSurrogate(pSrc, pSrcEnd, ptr3);
                        pSrc += 2;
                    }
                    else if (num <= 127 || num >= 65534)
                    {
                        ptr3 = InvalidXmlChar(num, ptr3, entitize: true);
                        pSrc++;
                    }
                    else
                    {
                        ptr3 = EncodeMultibyteUTF8(num, ptr3);
                        pSrc++;
                    }
                    continue;
                }
                pSrc++;
            }
            _bufPos = (int)(ptr3 - ptr2);
            _textPos = _bufPos;
            _contentPos = 0;
        }
        return -1;
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._contentPos, System.Xml.XmlUtf8RawTextWriter._newLineHandling, System.Xml.XmlUtf8RawTextWriter._textPos, System.Xml.XmlUtf8RawTextWriter.AmpEntity(), System.Xml.XmlUtf8RawTextWriter.CarriageReturnEntity(), System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.EncodeMultibyteUTF8(), System.Xml.XmlUtf8RawTextWriter.EncodeSurrogate(), System.Xml.XmlUtf8RawTextWriter.GtEntity(), System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsSurrogate(), and System.Xml.XmlUtf8RawTextWriter.LtEntity().
Referenced by System.Xml.XmlUtf8RawTextWriter._WriteElementTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockAsync(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockNoFlush(), and System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockNoFlush().