Terraria: System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking
WriteRawWithCharChecking()
unsafe void System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking (char * pSrcBegin, char * pSrcEnd) inline protected inherited
Definition at line 797 of file XmlUtf8RawTextWriter.cs.
    {
        fixed (byte* ptr2 = _bufBytes)
        {
            char* ptr = pSrcBegin;
            byte* ptr3 = ptr2 + _bufPos;
            int num = 0;
            while (true)
            {
                byte* ptr4 = ptr3 + (pSrcEnd - ptr);
                if (ptr4 > ptr2 + _bufLen)
                {
                    ptr4 = ptr2 + _bufLen;
                }
                while (ptr3 < ptr4 && XmlCharType.IsTextChar((char)(num = *ptr)) && num <= 127)
                {
                    *ptr3 = (byte)num;
                    ptr3++;
                    ptr++;
                }
                if (ptr >= pSrcEnd)
                {
                    break;
                }
                if (ptr3 >= ptr4)
                {
                    _bufPos = (int)(ptr3 - ptr2);
                    FlushBuffer();
                    ptr3 = ptr2 + 1;
                    continue;
                }
                switch (num)
                {
                case 9:
                case 38:
                case 60:
                case 93:
                    *ptr3 = (byte)num;
                    ptr3++;
                    break;
                case 13:
                    if (_newLineHandling == NewLineHandling.Replace)
                    {
                        if (ptr + 1 < pSrcEnd && ptr[1] == '\n')
{
                            ptr++;
                        }
                        ptr3 = WriteNewLine(ptr3);
                    }
                    else
                    {
                        *ptr3 = (byte)num;
                        ptr3++;
                    }
                    break;
                case 10:
                    if (_newLineHandling == NewLineHandling.Replace)
                    {
                        ptr3 = WriteNewLine(ptr3);
                        break;
                    }
                    *ptr3 = (byte)num;
                    ptr3++;
                    break;
                default:
                    if (XmlCharType.IsSurrogate(num))
                    {
                        ptr3 = EncodeSurrogate(ptr, pSrcEnd, ptr3);
                        ptr += 2;
                    }
                    else if (num <= 127 || num >= 65534)
                    {
                        ptr3 = InvalidXmlChar(num, ptr3, entitize: false);
                        ptr++;
                    }
                    else
                    {
                        ptr3 = EncodeMultibyteUTF8(num, ptr3);
                        ptr++;
                    }
                    continue;
                }
                ptr++;
            }
            _bufPos = (int)(ptr3 - ptr2);
        }
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._newLineHandling, System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.EncodeMultibyteUTF8(), System.Xml.XmlUtf8RawTextWriter.EncodeSurrogate(), System.Xml.XmlUtf8RawTextWriter.FlushBuffer(), System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(), System.Xml.XmlCharType.IsSurrogate(), System.Xml.XmlCharType.IsTextChar(), and System.Xml.XmlUtf8RawTextWriter.WriteNewLine().
Referenced by System.Xml.XmlUtf8RawTextWriter.WriteRaw(), and System.Xml.XmlUtf8RawTextWriter.WriteRaw().