Terraria: System.Xml.XmlUtf8RawTextWriter.WriteNewLine
WriteNewLine()
unsafe byte * System.Xml.XmlUtf8RawTextWriter.WriteNewLine (byte * pDst) inline protected inherited
Definition at line 1242 of file XmlUtf8RawTextWriter.cs.
    {
        fixed (byte* ptr = _bufBytes)
        {
            _bufPos = (int)(pDst - ptr);
            RawText(_newLineChars);
            return ptr + _bufPos;
        }
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter._newLineChars, System.Xml.Dictionary, and System.Xml.XmlUtf8RawTextWriter.RawText().
Referenced by System.Xml.XmlUtf8RawTextWriter.WriteCDataSection(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPi(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(), and System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking().