Terraria: System.Threading.CancellationTokenRegistration.Unregister
Unregister()
bool System.Threading.CancellationTokenRegistration.Unregister () inline
Definition at line 67 of file CancellationTokenRegistration.cs.
    {
        CancellationTokenSource.CallbackNode node = _node;
        return node?.Registrations.Unregister(_id, node) ?? false;
    }
References System.Threading.CancellationTokenRegistration._id, System.Threading.CancellationTokenRegistration._node, System.Threading.CancellationTokenSource.CallbackNode.Registrations, and System.Threading.CancellationTokenSource.Registrations.Unregister().
Referenced by System.Threading.AsyncMutex.EnterAsync(), System.Threading.AsyncMutex.Exit(), System.Net.NameResolutionPal.GetAddrInfoExState.UnregisterAndGetCancellationToken(), and System.Net.Http.CreditWaiter.UnregisterAndOwnCompletion().