Terraria: System.Reflection.Assembly.GetTypes
GetTypes()
virtual Type[] System.Reflection.Assembly.GetTypes () inline virtual inherited
Definition at line 237 of file Assembly.cs.
    {
        Module[] modules = GetModules(getResourceModules: false);
        if (modules.Length == 1)
        {
            return modules[0].GetTypes();
        }
        int num = 0;
        Type[][] array = new Type[modules.Length][];
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = modules[i].GetTypes();
            num += array[i].Length;
        }
        int num2 = 0;
        Type[] array2 = new Type[num];
        for (int j = 0; j < array.Length; j++)
        {
            int num3 = array[j].Length;
            Array.Copy(array[j], 0, array2, num2, num3);
            num2 += num3;
        }
        return array2;
    }
References System.array, System.Array.Copy(), System.Runtime.Serialization.Dictionary, and System.Reflection.Assembly.GetModules().
Referenced by System.Reflection.Metadata.RuntimeTypeMetadataUpdateHandler.ClearCache(), and System.Reflection.AssemblyExtensions.GetTypes().