Terraria: System.Reflection.Assembly.LoadFromResolveHandler
LoadFromResolveHandler()
static Assembly System.Reflection.Assembly.LoadFromResolveHandler (object sender, ResolveEventArgs args) inline static private inherited
Definition at line 544 of file Assembly.cs.
    {
        Assembly requestingAssembly = args.RequestingAssembly;
        if (requestingAssembly == null)
        {
            return null;
        }
        if (AssemblyLoadContext.Default != AssemblyLoadContext.GetLoadContext(requestingAssembly))
        {
            return null;
        }
        string fullPath = Path.GetFullPath(requestingAssembly.Location);
        if (string.IsNullOrEmpty(fullPath))
        {
            return null;
        }
        lock (s_loadFromAssemblyList)
        {
            if (!s_loadFromAssemblyList.Contains(fullPath))
            {
                if (AssemblyLoadContext.IsTracingEnabled())
                {
                    AssemblyLoadContext.TraceAssemblyLoadFromResolveHandlerInvoked(args.Name, isTrackedAssembly: false, fullPath, null);
                }
                return null;
            }
        }
        AssemblyName assemblyName = new AssemblyName(args.Name);
        string text = Path.Combine(Path.GetDirectoryName(fullPath), assemblyName.Name + ".dll");
        if (AssemblyLoadContext.IsTracingEnabled())
        {
            AssemblyLoadContext.TraceAssemblyLoadFromResolveHandlerInvoked(args.Name, isTrackedAssembly: true, fullPath, text);
        }
        try
        {
            return LoadFrom(text);
        }
        catch (FileNotFoundException)
        {
            return null;
        }
    }
References System.IO.Path.Combine(), System.Runtime.Loader.AssemblyLoadContext.Default, System.Runtime.Serialization.Dictionary, System.IO.Path.GetDirectoryName(), System.IO.Path.GetFullPath(), System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(), System.Runtime.Loader.AssemblyLoadContext.IsTracingEnabled(), System.Reflection.Assembly.LoadFrom(), System.Reflection.Assembly.s_loadFromAssemblyList, System.text, and System.Runtime.Loader.AssemblyLoadContext.TraceAssemblyLoadFromResolveHandlerInvoked().
Referenced by System.Reflection.Assembly.LoadFrom().