Terraria: System.Reflection.Assembly.Load
Load() [4/4]
static Assembly System.Reflection.Assembly.Load (string assemblyString) inline static inherited
Definition at line 157 of file Assembly.cs.
    {
        StackCrawlMark stackMark = StackCrawlMark.LookForMyCaller;
        return RuntimeAssembly.InternalLoad(assemblyString, ref stackMark, AssemblyLoadContext.CurrentContextualReflectionContext);
    }
References System.Runtime.Loader.AssemblyLoadContext.CurrentContextualReflectionContext, and System.Reflection.RuntimeAssembly.InternalLoad().
Referenced by System.Xml.Serialization.Compiler.AddImport(), System.AppDomain.ExecuteAssemblyByName(), System.AppDomain.ExecuteAssemblyByName(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.FastBindToType(), Terraria.Program.ForceLoadAssembly(), System.ComponentModel.PropertyTabAttribute.InitializeTabClasses(), System.AppDomain.Load(), System.Reflection.Assembly.Load(), System.AppDomain.Load(), System.AppDomain.Load(), System.AppDomain.Load(), System.Runtime.Serialization.FormatterServices.LoadAssemblyFromString(), System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly(), Terraria.WindowsLaunch.Main(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.ResolveSimpleAssemblyName().