Terraria: System.Reflection.Assembly.LoadFrom
LoadFrom() [1/2]
static Assembly System.Reflection.Assembly.LoadFrom (string assemblyFile) inline static inherited
Definition at line 588 of file Assembly.cs.
    {
        if (assemblyFile == null)
        {
            throw new ArgumentNullException("assemblyFile");
        }
        string fullPath = Path.GetFullPath(assemblyFile);
        if (!s_loadFromHandlerSet)
        {
            lock (s_loadFromAssemblyList)
            {
                if (!s_loadFromHandlerSet)
                {
                    AssemblyLoadContext.AssemblyResolve += LoadFromResolveHandler;
                    s_loadFromHandlerSet = true;
                }
            }
        }
        lock (s_loadFromAssemblyList)
        {
            if (!s_loadFromAssemblyList.Contains(fullPath))
            {
                s_loadFromAssemblyList.Add(fullPath);
            }
        }
        return AssemblyLoadContext.Default.LoadFromAssemblyPath(fullPath);
    }
References System.Runtime.Loader.AssemblyLoadContext.Default, System.Runtime.Serialization.Dictionary, System.IO.Path.GetFullPath(), System.Reflection.Assembly.LoadFromResolveHandler(), System.Reflection.Assembly.s_loadFromAssemblyList, and System.Reflection.Assembly.s_loadFromHandlerSet.
Referenced by System.Activator.CreateInstanceFrom(), System.Reflection.Assembly.LoadFromResolveHandler(), System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly(), and System.Reflection.Assembly.UnsafeLoadFrom().