Terraria: System.Reflection.Assembly.GetType
GetType() [2/4]
virtual ? Type System.Reflection.Assembly.GetType (string name) inline virtual inherited
Definition at line 305 of file Assembly.cs.
    {
        return GetType(name, throwOnError: false, ignoreCase: false);
    }
References System.Runtime.Serialization.Dictionary, and System.Reflection.Assembly.GetType().
Referenced by System.StartupHookProvider.CallStartupHook(), System.Reflection.Assembly.CreateInstance(), System.Activator.CreateInstanceFrom(), System.Activator.CreateInstanceInternal(), System.Reflection.Assembly.GetType(), System.Reflection.Assembly.GetType(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetTypeFromName(), System.ComponentModel.PropertyDescriptor.GetTypeFromName(), System.ComponentModel.PropertyTabAttribute.InitializeTabClasses(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.TopLevelAssemblyTypeResolver.ResolveType(), and System.TypeNameParser.ResolveType().