Terraria: System.Xml.Serialization.XmlSerializerFactory.CreateSerializer
CreateSerializer() [5/8]
XmlSerializer System.Xml.Serialization.XmlSerializerFactory.CreateSerializer (Type type, XmlAttributeOverrides? overrides, Type?[] extraTypes, XmlRootAttribute? root, string? defaultNamespace) inline
Definition at line 8 of file XmlSerializerFactory.cs.
    {
        return CreateSerializer(type, overrides, extraTypes, root, defaultNamespace, null);
    }
References System.Xml.Serialization.XmlSerializerFactory.CreateSerializer(), System.Xml.Dictionary, and System.type.
Referenced by System.Xml.Serialization.XmlSerializerFactory.CreateSerializer(), System.Xml.Serialization.XmlSerializerFactory.CreateSerializer(), System.Xml.Serialization.XmlSerializerFactory.CreateSerializer(), System.Xml.Serialization.XmlSerializerFactory.CreateSerializer(), and System.Xml.Serialization.XmlSerializerFactory.CreateSerializer().