Terraria: System.Xml.Schema.XmlAnyConverter.ChangeType
ChangeType() [8/9]
override object System.Xml.Schema.XmlAnyConverter.ChangeType (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline
Definition at line 251 of file XmlAnyConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        Type type = value.GetType();
        if (destinationType == XmlBaseConverter.ObjectType)
        {
            destinationType = base.DefaultClrType;
        }
        if (destinationType == XmlBaseConverter.BooleanType && type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAsBoolean;
        }
        if (destinationType == XmlBaseConverter.DateTimeType && type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAsDateTime;
        }
        if (destinationType == XmlBaseConverter.DateTimeOffsetType && type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAs(XmlBaseConverter.DateTimeOffsetType);
        }
        if (destinationType == XmlBaseConverter.DecimalType && type == XmlBaseConverter.XmlAtomicValueType)
        {
            return (decimal)((XmlAtomicValue)value).ValueAs(XmlBaseConverter.DecimalType);
        }
        if (destinationType == XmlBaseConverter.DoubleType && type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAsDouble;
        }
        if (destinationType == XmlBaseConverter.Int32Type && type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAsInt;
        }
        if (destinationType == XmlBaseConverter.Int64Type && type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAsLong;
        }
        if (destinationType == XmlBaseConverter.SingleType && type == XmlBaseConverter.XmlAtomicValueType)
        {
            return (float)((XmlAtomicValue)value).ValueAs(XmlBaseConverter.SingleType);
        }
        if (destinationType == XmlBaseConverter.XmlAtomicValueType)
        {
            if (type == XmlBaseConverter.XmlAtomicValueType)
            {
                return (XmlAtomicValue)value;
            }
            if (type == XmlBaseConverter.BooleanType)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Boolean), (bool)value);
            }
            if (type == XmlBaseConverter.ByteType)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.UnsignedByte), value);
            }
            if (type == XmlBaseConverter.ByteArrayType)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Base64Binary), value);
            }
            if (type == XmlBaseConverter.DateTimeType)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.DateTime), (DateTime)value);
            }
            if (type == XmlBaseConverter.DateTimeOffsetType)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.DateTime), (DateTimeOffset)value);
            }
            if (type == XmlBaseConverter.DecimalType)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Decimal), value);
            }
            if (type == XmlBaseConverter.DoubleType)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Double), (double)value);
            }
            if (type == XmlBaseConverter.Int16Type)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Short), value);
            }
            if (type == XmlBaseConverter.Int32Type)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Int), (int)value);
            }
            if (type == XmlBaseConverter.Int64Type)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Long), (long)value);
            }
            if (type == XmlBaseConverter.SByteType)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Byte), value);
            }
            if (type == XmlBaseConverter.SingleType)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Float), value);
            }
            if (type == XmlBaseConverter.StringType)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String), (string)value);
            }
            if (type == XmlBaseConverter.TimeSpanType)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Duration), value);
            }
            if (type == XmlBaseConverter.UInt16Type)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.UnsignedShort), value);
            }
            if (type == XmlBaseConverter.UInt32Type)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.UnsignedInt), value);
            }
            if (type == XmlBaseConverter.UInt64Type)
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.UnsignedLong), value);
            }
            if (XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.UriType))
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.AnyUri), value);
            }
            if (XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.XmlQualifiedNameType))
            {
                return new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.QName), value, nsResolver);
            }
        }
        if (destinationType == XmlBaseConverter.XPathItemType)
        {
            if (type == XmlBaseConverter.XmlAtomicValueType)
            {
                return (XmlAtomicValue)value;
            }
            if (XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.XPathNavigatorType))
            {
                return (XPathNavigator)value;
            }
        }
        if (destinationType == XmlBaseConverter.XPathNavigatorType && XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.XPathNavigatorType))
        {
            return ToNavigator((XPathNavigator)value);
        }
        if (destinationType == XmlBaseConverter.XPathItemType)
        {
            return (XPathItem)ChangeType(value, XmlBaseConverter.XmlAtomicValueType, nsResolver);
        }
        if (type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAs(destinationType, nsResolver);
        }
        return ChangeListType(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.BooleanType, System.Xml.Schema.XmlBaseConverter.ByteArrayType, System.Xml.Schema.XmlBaseConverter.ByteType, System.Xml.Schema.XmlBaseConverter.ChangeListType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlBaseConverter.DateTimeOffsetType, System.Xml.Schema.XmlBaseConverter.DateTimeType, System.Xml.Schema.XmlBaseConverter.DecimalType, System.Xml.Dictionary, System.Xml.Schema.XmlBaseConverter.DoubleType, System.Xml.Schema.XmlSchemaType.GetBuiltInSimpleType(), System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.Int16Type, System.Xml.Schema.XmlBaseConverter.Int32Type, System.Xml.Schema.XmlBaseConverter.Int64Type, System.Xml.Schema.XmlBaseConverter.IsDerivedFrom(), System.Xml.Schema.XmlBaseConverter.ObjectType, System.Xml.Schema.XmlBaseConverter.SByteType, System.Xml.Schema.XmlBaseConverter.SingleType, System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlBaseConverter.TimeSpanType, System.Xml.Schema.XmlAnyConverter.ToNavigator(), System.type, System.Xml.Schema.XmlBaseConverter.UInt16Type, System.Xml.Schema.XmlBaseConverter.UInt32Type, System.Xml.Schema.XmlBaseConverter.UInt64Type, System.Xml.Schema.XmlBaseConverter.UriType, System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, System.Xml.Schema.XmlBaseConverter.XmlQualifiedNameType, System.Xml.Schema.XmlBaseConverter.XPathItemType, and System.Xml.Schema.XmlBaseConverter.XPathNavigatorType.