Terraria: TeleportPylonsMapLayer.Draw
Draw()
void TeleportPylonsMapLayer.Draw (ref MapOverlayDrawContext context, ref string text) inline
Implements IMapLayer.
     {
         List<TeleportPylonInfo> pylons = Main.PylonSystem.Pylons;
         float num = 1f;
         float scaleIfSelected = num * 2f;
         Texture2D value = TextureAssets.Extra[182].Value;
         bool num2 = TeleportPylonsSystem.IsPlayerNearAPylon(Main.LocalPlayer) && (Main.DroneCameraTracker == null || !Main.DroneCameraTracker.IsInUse());
         Color color = Color.White;
         if (!num2)
         {
             color = Color.Gray * 0.5f;
         }
         for (int i = 0; i < pylons.Count; i++)
         {
             TeleportPylonInfo info = pylons[i];
             if (context.Draw(value, info.PositionInTiles.ToVector2() + new Vector2(1.5f, 2f), color, new SpriteFrame(9, 1, (byte)info.TypeOfPylon, 0)
             {
                 PaddingY = 0
             }, num, scaleIfSelected, Alignment.Center).IsMouseOver)
             {
                 Main.cancelWormHole = true;
                 string itemNameValue = Lang.GetItemNameValue(TETeleportationPylon.GetPylonItemTypeFromTileStyle((int)info.TypeOfPylon));
                 text = itemNameValue;
                 if (Main.mouseLeft && Main.mouseLeftRelease)
                 {
                     Main.mouseLeftRelease = false;
                     Main.mapFullscreen = false;
                     PlayerInput.LockGamepadButtons("MouseLeft");
                     Main.PylonSystem.RequestTeleportation(info, Main.LocalPlayer);
                     SoundEngine.PlaySound(11);
                 }
             }
         }
     }
References Main.cancelWormHole, Alignment.Center, Color, Main.DroneCameraTracker, TextureAssets.Extra, Lang.GetItemNameValue(), TETeleportationPylon.GetPylonItemTypeFromTileStyle(), DroneCameraTracker.IsInUse(), TeleportPylonsSystem.IsPlayerNearAPylon(), Main.LocalPlayer, PlayerInput.LockGamepadButtons(), Main.mapFullscreen, Main.mouseLeft, Main.mouseLeftRelease, SoundEngine.PlaySound(), TeleportPylonInfo.PositionInTiles, TeleportPylonsSystem.Pylons, Main.PylonSystem, TeleportPylonsSystem.RequestTeleportation(), TeleportPylonInfo.TypeOfPylon, and Asset< T >.Value.