Terraria: System.Security.Cryptography.RSAImplementation.RSACng.ExportEncryptedPkcs8
ExportEncryptedPkcs8()
byte[] System.Security.Cryptography.RSAImplementation.RSACng.ExportEncryptedPkcs8 (ReadOnlySpan< char > pkcs8Password, int kdfCount) inline private
Definition at line 63 of file RSAImplementation.cs.
        {
            using SafeNCryptKeyHandle keyHandle = GetDuplicatedKeyHandle();
            return CngKeyLite.ExportPkcs8KeyBlob(keyHandle, pkcs8Password, kdfCount);
        }
References System.Security.Cryptography.CngKeyLite.ExportPkcs8KeyBlob(), and System.Security.Cryptography.RSAImplementation.RSACng.GetDuplicatedKeyHandle().
Referenced by System.Security.Cryptography.RSAImplementation.RSACng.ExportEncryptedPkcs8PrivateKey().