Terraria: System.Security.Cryptography.RSAImplementation.RSACng.ImportEncryptedPkcs8PrivateKey
ImportEncryptedPkcs8PrivateKey() [2/2]
override void System.Security.Cryptography.RSAImplementation.RSACng.ImportEncryptedPkcs8PrivateKey (ReadOnlySpan< char > password, ReadOnlySpan< byte > source, out int bytesRead) inline virtual
Reimplemented from System.Security.Cryptography.RSA.
Definition at line 450 of file RSAImplementation.cs.
        {
            ThrowIfDisposed();
            int bytesRead2;
            CngPkcs8.Pkcs8Response response = CngPkcs8.ImportEncryptedPkcs8PrivateKey(password, source, out bytesRead2);
            ProcessPkcs8Response(response);
            bytesRead = bytesRead2;
        }
References System.Security.Cryptography.CngPkcs8.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.RSAImplementation.RSACng.ProcessPkcs8Response(), System.source, and System.Security.Cryptography.RSAImplementation.RSACng.ThrowIfDisposed().