Terraria: System.Security.Cryptography.RSAImplementation.RSACng.VerifyHash
VerifyHash() [2/2]
unsafe override bool System.Security.Cryptography.RSAImplementation.RSACng.VerifyHash (ReadOnlySpan< byte > hash, ReadOnlySpan< byte > signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) inline virtual
Reimplemented from System.Security.Cryptography.RSA.
Definition at line 684 of file RSAImplementation.cs.
        {
            string name = hashAlgorithm.Name;
            if (string.IsNullOrEmpty(name))
            {
                throw new ArgumentException(System.SR.Cryptography_HashAlgorithmNameNullOrEmpty, "hashAlgorithm");
            }
            if (padding == null)
            {
                throw new ArgumentNullException("padding");
            }
            using SafeNCryptKeyHandle keyHandle = GetDuplicatedKeyHandle();
            if (hash.Length != GetHashSizeInBytes(hashAlgorithm))
            {
                return false;
            }
            IntPtr intPtr = Marshal.StringToHGlobalUni(name);
            try
            {
                switch (padding.Mode)
                {
                case RSASignaturePaddingMode.Pkcs1:
                {
                    global::Interop.BCrypt.BCRYPT_PKCS1_PADDING_INFO bCRYPT_PKCS1_PADDING_INFO = default(global::Interop.BCrypt.BCRYPT_PKCS1_PADDING_INFO);
                    bCRYPT_PKCS1_PADDING_INFO.pszAlgId = intPtr;
                    global::Interop.BCrypt.BCRYPT_PKCS1_PADDING_INFO bCRYPT_PKCS1_PADDING_INFO2 = bCRYPT_PKCS1_PADDING_INFO;
                    return keyHandle.VerifyHash(hash, signature, global::Interop.NCrypt.AsymmetricPaddingMode.NCRYPT_PAD_PKCS1_FLAG, &bCRYPT_PKCS1_PADDING_INFO2);
                }
                case RSASignaturePaddingMode.Pss:
                {
                    global::Interop.BCrypt.BCRYPT_PSS_PADDING_INFO bCRYPT_PSS_PADDING_INFO = default(global::Interop.BCrypt.BCRYPT_PSS_PADDING_INFO);
                    bCRYPT_PSS_PADDING_INFO.pszAlgId = intPtr;
                    bCRYPT_PSS_PADDING_INFO.cbSalt = hash.Length;
                    global::Interop.BCrypt.BCRYPT_PSS_PADDING_INFO bCRYPT_PSS_PADDING_INFO2 = bCRYPT_PSS_PADDING_INFO;
                    return keyHandle.VerifyHash(hash, signature, global::Interop.NCrypt.AsymmetricPaddingMode.NCRYPT_PAD_PSS_FLAG, &bCRYPT_PSS_PADDING_INFO2);
                }
                default:
                    throw new CryptographicException(System.SR.Cryptography_UnsupportedPaddingMode);
                }
            }
            finally
            {
                Marshal.FreeHGlobal(intPtr);
            }
        }
References System.SR.Cryptography_HashAlgorithmNameNullOrEmpty, System.SR.Cryptography_UnsupportedPaddingMode, System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Security.Cryptography.RSAImplementation.RSACng.GetDuplicatedKeyHandle(), System.Security.Cryptography.RSAImplementation.RSACng.GetHashSizeInBytes(), System.Security.Cryptography.RSASignaturePadding.Mode, System.Security.Cryptography.HashAlgorithmName.Name, and System.Runtime.InteropServices.Marshal.StringToHGlobalUni().