Terraria: System.Security.Cryptography.RSAImplementation.RSACng.ImportKeyBlob
ImportKeyBlob()
void System.Security.Cryptography.RSAImplementation.RSACng.ImportKeyBlob (byte[] rsaBlob, bool includePrivate) inline private
Definition at line 75 of file RSAImplementation.cs.
        {
            ThrowIfDisposed();
            string blobType = (includePrivate ? "RSAPRIVATEBLOB" : "RSAPUBLICBLOB");
            SafeNCryptKeyHandle keyHandle = CngKeyLite.ImportKeyBlob(blobType, rsaBlob);
            SetKeyHandle(keyHandle);
        }
References System.Security.Cryptography.CngKeyLite.ImportKeyBlob(), System.Security.Cryptography.RSAImplementation.RSACng.SetKeyHandle(), and System.Security.Cryptography.RSAImplementation.RSACng.ThrowIfDisposed().
Referenced by System.Security.Cryptography.RSAImplementation.RSACng.ImportParameters().