Terraria: System.Security.Cryptography.RSAImplementation.RSACng.GetDuplicatedKeyHandle
GetDuplicatedKeyHandle()
SafeNCryptKeyHandle System.Security.Cryptography.RSAImplementation.RSACng.GetDuplicatedKeyHandle () inline private
Definition at line 40 of file RSAImplementation.cs.
        {
            ThrowIfDisposed();
            int keySize = KeySize;
            if (_lastKeySize != keySize)
            {
                if (_keyHandle != null)
                {
                    _keyHandle.Dispose();
                }
                _keyHandle = CngKeyLite.GenerateNewExportableKey("RSA", keySize);
                _lastKeySize = keySize;
            }
            return new DuplicateSafeNCryptKeyHandle(_keyHandle);
        }
References System.Security.Cryptography.RSAImplementation.RSACng._keyHandle, System.Security.Cryptography.RSAImplementation.RSACng._lastKeySize, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey(), System.Security.Cryptography.AsymmetricAlgorithm.KeySize, and System.Security.Cryptography.RSAImplementation.RSACng.ThrowIfDisposed().
Referenced by System.Security.Cryptography.RSAImplementation.RSACng.EncryptOrDecrypt(), System.Security.Cryptography.RSAImplementation.RSACng.ExportEncryptedPkcs8(), System.Security.Cryptography.RSAImplementation.RSACng.ExportKeyBlob(), System.Security.Cryptography.RSAImplementation.RSACng.SignHash(), System.Security.Cryptography.RSAImplementation.RSACng.TryEncryptOrDecrypt(), System.Security.Cryptography.RSAImplementation.RSACng.TryExportEncryptedPkcs8(), System.Security.Cryptography.RSAImplementation.RSACng.TrySignHash(), and System.Security.Cryptography.RSAImplementation.RSACng.VerifyHash().