Terraria: System.Net.Mail.MailAddressCollection.Add
Add() [1/2]
void System.Net.Mail.MailAddressCollection.Add (string addresses) inline
Definition at line 8 of file MailAddressCollection.cs.
    {
        if (addresses == null)
        {
            throw new ArgumentNullException("addresses");
        }
        if (addresses.Length == 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_emptystringcall, "addresses"), "addresses");
        }
        ParseValue(addresses);
    }
References System.SR.Format(), System.SR.net_emptystringcall, and System.Net.Mail.MailAddressCollection.ParseValue().
Referenced by System.Net.Mail.Message.Message(), System.Net.Mail.SmtpClient.Send(), and System.Net.Mail.SmtpClient.SendAsync().