Terraria: System.Security.Cryptography.RSAImplementation.RSACng.TryEncryptOrDecrypt
TryEncryptOrDecrypt() [1/2]
unsafe bool System.Security.Cryptography.RSAImplementation.RSACng.TryEncryptOrDecrypt (ReadOnlySpan< byte > data, Span< byte > destination, RSAEncryptionPadding padding, bool encrypt, out int bytesWritten) inline private
Definition at line 232 of file RSAImplementation.cs.
        {
            if (padding == null)
            {
                throw new ArgumentNullException("padding");
            }
            int num = RsaPaddingProcessor.BytesRequiredForBitCount(KeySize);
            if (!encrypt && data.Length != num)
            {
                throw new CryptographicException(System.SR.Cryptography_RSA_DecryptWrongSize);
            }
            if (encrypt && padding.Mode == RSAEncryptionPaddingMode.Pkcs1 && data.Length > num - 11)
            {
                throw new CryptographicException(System.SR.Format(System.SR.Cryptography_Encryption_MessageTooLong, num - 11));
            }
            using SafeNCryptKeyHandle key = GetDuplicatedKeyHandle();
            if (encrypt && data.Length == 0)
            {
                byte[] array = System.Security.Cryptography.CryptoPool.Rent(num);
                Span<byte> span = new Span<byte>(array, 0, num);
                try
                {
                    if (padding == RSAEncryptionPadding.Pkcs1)
                    {
                        RsaPaddingProcessor.PadPkcs1Encryption(data, span);
                    }
                    else
                    {
                        if (padding.Mode != RSAEncryptionPaddingMode.Oaep)
{
                            throw new CryptographicException(System.SR.Cryptography_UnsupportedPaddingMode);
                        }
                        RsaPaddingProcessor rsaPaddingProcessor = RsaPaddingProcessor.OpenProcessor(padding.OaepHashAlgorithm);
                        rsaPaddingProcessor.PadOaep(data, span);
                    }
                    return TryEncryptOrDecrypt(key, span, destination, global::Interop.NCrypt.AsymmetricPaddingMode.NCRYPT_NO_PADDING_FLAG, null, encrypt, out bytesWritten);
                }
                finally
                {
                    CryptographicOperations.ZeroMemory(span);
                    System.Security.Cryptography.CryptoPool.Return(array, 0);
                }
            }
            switch (padding.Mode)
            {
            case RSAEncryptionPaddingMode.Pkcs1:
                return TryEncryptOrDecrypt(key, data, destination, global::Interop.NCrypt.AsymmetricPaddingMode.NCRYPT_PAD_PKCS1_FLAG, null, encrypt, out bytesWritten);
            case RSAEncryptionPaddingMode.Oaep:
            {
                IntPtr intPtr = Marshal.StringToHGlobalUni(padding.OaepHashAlgorithm.Name);
                try
                {
                    global::Interop.BCrypt.BCRYPT_OAEP_PADDING_INFO bCRYPT_OAEP_PADDING_INFO = default(global::Interop.BCrypt.BCRYPT_OAEP_PADDING_INFO);
                    bCRYPT_OAEP_PADDING_INFO.pszAlgId = intPtr;
                    bCRYPT_OAEP_PADDING_INFO.pbLabel = IntPtr.Zero;
                    bCRYPT_OAEP_PADDING_INFO.cbLabel = 0;
                    global::Interop.BCrypt.BCRYPT_OAEP_PADDING_INFO bCRYPT_OAEP_PADDING_INFO2 = bCRYPT_OAEP_PADDING_INFO;
                    return TryEncryptOrDecrypt(key, data, destination, global::Interop.NCrypt.AsymmetricPaddingMode.NCRYPT_PAD_OAEP_FLAG, &bCRYPT_OAEP_PADDING_INFO2, encrypt, out bytesWritten);
                }
                finally
                {
                    Marshal.FreeHGlobal(intPtr);
                }
            }
            default:
                throw new CryptographicException(System.SR.Cryptography_UnsupportedPaddingMode);
            }
        }
References System.array, System.Security.Cryptography.RsaPaddingProcessor.BytesRequiredForBitCount(), System.SR.Cryptography_Encryption_MessageTooLong, System.SR.Cryptography_RSA_DecryptWrongSize, System.SR.Cryptography_UnsupportedPaddingMode, System.destination, System.SR.Format(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Security.Cryptography.RSAImplementation.RSACng.GetDuplicatedKeyHandle(), System.key, System.Security.Cryptography.AsymmetricAlgorithm.KeySize, System.Security.Cryptography.RSAEncryptionPadding.Mode, System.Security.Cryptography.HashAlgorithmName.Name, System.Security.Cryptography.RSAEncryptionPadding.OaepHashAlgorithm, System.Security.Cryptography.RsaPaddingProcessor.OpenProcessor(), System.Security.Cryptography.RsaPaddingProcessor.PadPkcs1Encryption(), System.Security.Cryptography.RSAEncryptionPadding.Pkcs1, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Runtime.InteropServices.Marshal.StringToHGlobalUni(), System.Security.Cryptography.RSAImplementation.RSACng.TryEncryptOrDecrypt(), System.IntPtr.Zero, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().
Referenced by System.Security.Cryptography.RSAImplementation.RSACng.TryDecrypt(), System.Security.Cryptography.RSAImplementation.RSACng.TryEncrypt(), and System.Security.Cryptography.RSAImplementation.RSACng.TryEncryptOrDecrypt().