Terraria: ItemTagHandler.ItemSnippet.UniqueDraw
UniqueDraw()
override bool ItemTagHandler.ItemSnippet.UniqueDraw (bool justCheckingString, out Vector2 size, SpriteBatch spriteBatch, Vector2 position = default(Vector2), Color color = default(Color), float scale = 1f) inline virtual
Reimplemented from TextSnippet.
         {
             float num = 1f;
             float num2 = 1f;
             if (Main.netMode != 2 && !Main.dedServ)
             {
                 Main.instance.LoadItem(_item.type);
                 Texture2D value = TextureAssets.Item[_item.type].Value;
                 if (Main.itemAnimations[_item.type] != null)
                 {
                     Main.itemAnimations[_item.type].GetFrame(value);
                 }
                 else
                 {
                     value.Frame();
                 }
             }
             num2 *= scale;
             num *= num2;
             if (num > 0.75f)
             {
                 num = 0.75f;
             }
             if (!justCheckingString && color != Color.Black)
             {
                 float inventoryScale = Main.inventoryScale;
                 Main.inventoryScale = scale * num;
                 ItemSlot.Draw(spriteBatch, ref _item, 14, position - new Vector2(10f) * scale * num, Color.White);
                 Main.inventoryScale = inventoryScale;
             }
             size = new Vector2(32f) * scale * num;
             return true;
         }
References ItemTagHandler.ItemSnippet._item, TextSnippet.Color, Main.dedServ, ItemSlot.Draw(), DrawAnimation.GetFrame(), Main.instance, Main.inventoryScale, TextureAssets.Item, Main.itemAnimations, Main.LoadItem(), Main.netMode, Item.type, and Asset< T >.Value.