Terraria: System.Xml.Schema.XmlSchemaInference.InferSchema1
InferSchema1()
XmlSchemaSet System.Xml.Schema.XmlSchemaInference.InferSchema1 (XmlReader instanceDocument, XmlSchemaSet schemas) inline package
Definition at line 123 of file XmlSchemaInference.cs.
    {
        if (instanceDocument == null)
        {
            throw new ArgumentNullException("instanceDocument");
        }
        _rootSchema = null;
        _xtr = instanceDocument;
        schemas.Compile();
        _schemaSet = schemas;
        while (_xtr.NodeType != XmlNodeType.Element && _xtr.Read())
        {
        }
        if (_xtr.NodeType == XmlNodeType.Element)
        {
            _targetNamespace = _xtr.NamespaceURI;
            if (_xtr.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
            {
                throw new XmlSchemaInferenceException(System.SR.SchInf_schema, 0, 0);
            }
            XmlSchemaElement xse = null;
            foreach (XmlSchemaElement value in schemas.GlobalElements.Values)
            {
                if (value.Name == _xtr.LocalName && value.QualifiedName.Namespace == _xtr.NamespaceURI)
                {
                    _rootSchema = value.Parent as XmlSchema;
                    xse = value;
                    break;
                }
            }
            if (_rootSchema == null)
            {
                xse = AddElement(_xtr.LocalName, _xtr.Prefix, _xtr.NamespaceURI, null, null, -1);
            }
            else
            {
                InferElement(xse, bCreatingNewType: false, _rootSchema);
            }
            foreach (string item in _namespaceManager)
            {
                if (!item.Equals("xml") && !item.Equals("xmlns"))
                {
                    string text2 = _namespaceManager.LookupNamespace(_nametable.Get(item));
                    if (text2.Length != 0)
                    {
                        _rootSchema.Namespaces.Add(item, text2);
                    }
                }
            }
            schemas.Reprocess(_rootSchema);
            schemas.Compile();
            return schemas;
        }
        throw new XmlSchemaInferenceException(System.SR.SchInf_NoElement, 0, 0);
    }
References System.Xml.Schema.XmlSchemaInference._namespaceManager, System.Xml.Schema.XmlSchemaInference._nametable, System.Xml.Schema.XmlSchemaInference._rootSchema, System.Xml.Schema.XmlSchemaInference._schemaSet, System.Xml.Schema.XmlSchemaInference._targetNamespace, System.Xml.Schema.XmlSchemaInference._xtr, System.Xml.Schema.XmlSchemaInference.AddElement(), System.Xml.Schema.XmlSchemaSet.Compile(), System.Xml.Dictionary, System.Xml.NameTable.Get(), System.Xml.Schema.XmlSchemaSet.GlobalElements, System.Xml.Schema.XmlSchemaInference.InferElement(), System.item, System.Xml.XmlReader.LocalName, System.Xml.XmlNamespaceManager.LookupNamespace(), System.Xml.Schema.XmlSchemaObject.Namespaces, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Xml.Schema.XmlSchemaSet.Reprocess(), System.SR.SchInf_NoElement, System.SR.SchInf_schema, System.value, and System.Xml.Schema.XmlSchemaObjectTable.Values.
Referenced by System.Xml.Schema.XmlSchemaInference.InferSchema(), and System.Xml.Schema.XmlSchemaInference.InferSchema().