Terraria: System.Xml.Schema.XmlSchemaInference.InferElement
InferElement()
void System.Xml.Schema.XmlSchemaInference.InferElement (XmlSchemaElement xse, bool bCreatingNewType, XmlSchema parentSchema) inline package
Definition at line 495 of file XmlSchemaInference.cs.
    {
        bool isEmptyElement = _xtr.IsEmptyElement;
        int lastUsedSeqItem = -1;
        Hashtable hashtable = new Hashtable();
        XmlSchemaType effectiveSchemaType = GetEffectiveSchemaType(xse, bCreatingNewType);
        XmlSchemaComplexType xmlSchemaComplexType = effectiveSchemaType as XmlSchemaComplexType;
        if (_xtr.MoveToFirstAttribute())
        {
            ProcessAttributes(ref xse, effectiveSchemaType, bCreatingNewType, parentSchema);
        }
        else if (!bCreatingNewType && xmlSchemaComplexType != null)
        {
            MakeExistingAttributesOptional(xmlSchemaComplexType, null);
        }
        if (xmlSchemaComplexType == null || xmlSchemaComplexType == XmlSchemaComplexType.AnyType)
        {
            xmlSchemaComplexType = xse.SchemaType as XmlSchemaComplexType;
        }
        if (isEmptyElement)
        {
            if (!bCreatingNewType)
            {
                if (xmlSchemaComplexType != null)
                {
                    if (xmlSchemaComplexType.Particle != null)
                    {
                        xmlSchemaComplexType.Particle.MinOccurs = 0m;
                    }
                    else if (xmlSchemaComplexType.ContentModel != null)
                    {
                        XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension = CheckSimpleContentExtension(xmlSchemaComplexType);
                        xmlSchemaSimpleContentExtension.BaseTypeName = ST_string;
                        xmlSchemaSimpleContentExtension.LineNumber = 262144;
                    }
                }
                else if (!xse.SchemaTypeName.IsEmpty)
                {
                    xse.LineNumber = 262144;
                    xse.SchemaTypeName = ST_string;
                }
            }
            else
            {
                xse.LineNumber = 262144;
            }
            return;
        }
        bool flag = false;
        do
        {
            _xtr.Read();
            if (_xtr.NodeType == XmlNodeType.Whitespace)
            {
                flag = true;
            }
            if (_xtr.NodeType == XmlNodeType.EntityReference)
            {
                throw new XmlSchemaInferenceException(System.SR.SchInf_entity, 0, 0);
            }
        }
        while (!_xtr.EOF && _xtr.NodeType != XmlNodeType.EndElement && _xtr.NodeType != XmlNodeType.CDATA && _xtr.NodeType != XmlNodeType.Element && _xtr.NodeType != XmlNodeType.Text);
        if (_xtr.NodeType == XmlNodeType.EndElement)
        {
            if (flag)
            {
                if (xmlSchemaComplexType != null)
                {
                    if (xmlSchemaComplexType.ContentModel != null)
                    {
                        XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension2 = CheckSimpleContentExtension(xmlSchemaComplexType);
                        xmlSchemaSimpleContentExtension2.BaseTypeName = ST_string;
                        xmlSchemaSimpleContentExtension2.LineNumber = 262144;
                    }
                    else if (bCreatingNewType)
                    {
                        XmlSchemaSimpleContent xmlSchemaSimpleContent = (XmlSchemaSimpleContent)(xmlSchemaComplexType.ContentModel = new XmlSchemaSimpleContent());
                        XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension3 = (XmlSchemaSimpleContentExtension)(xmlSchemaSimpleContent.Content = new XmlSchemaSimpleContentExtension());
                        MoveAttributes(xmlSchemaComplexType, xmlSchemaSimpleContentExtension3, bCreatingNewType);
                        xmlSchemaSimpleContentExtension3.BaseTypeName = ST_string;
                        xmlSchemaSimpleContentExtension3.LineNumber = 262144;
                    }
                    else
                    {
                        xmlSchemaComplexType.IsMixed = true;
                    }
                }
                else
                {
                    xse.SchemaTypeName = ST_string;
                    xse.LineNumber = 262144;
                }
            }
            if (bCreatingNewType)
            {
                xse.LineNumber = 262144;
            }
            else if (xmlSchemaComplexType != null)
            {
                if (xmlSchemaComplexType.Particle != null)
                {
                    xmlSchemaComplexType.Particle.MinOccurs = 0m;
                }
                else if (xmlSchemaComplexType.ContentModel != null)
                {
                    XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension4 = CheckSimpleContentExtension(xmlSchemaComplexType);
                    xmlSchemaSimpleContentExtension4.BaseTypeName = ST_string;
                    xmlSchemaSimpleContentExtension4.LineNumber = 262144;
                }
            }
            else if (!xse.SchemaTypeName.IsEmpty)
            {
                xse.LineNumber = 262144;
                xse.SchemaTypeName = ST_string;
            }
            return;
        }
        int num = 0;
        bool flag2 = false;
        while (!_xtr.EOF && _xtr.NodeType != XmlNodeType.EndElement)
        {
            bool flag3 = false;
            num++;
            if (_xtr.NodeType == XmlNodeType.Text || _xtr.NodeType == XmlNodeType.CDATA)
            {
                if (xmlSchemaComplexType != null)
                {
                    if (xmlSchemaComplexType.Particle != null)
                    {
                        xmlSchemaComplexType.IsMixed = true;
                        if (num == 1)
{
                            do
{
                                _xtr.Read();
                            }
                            while (!_xtr.EOF && (_xtr.NodeType == XmlNodeType.CDATA || _xtr.NodeType == XmlNodeType.Text || _xtr.NodeType == XmlNodeType.Comment || _xtr.NodeType == XmlNodeType.ProcessingInstruction || _xtr.NodeType == XmlNodeType.Whitespace || _xtr.NodeType == XmlNodeType.SignificantWhitespace || _xtr.NodeType == XmlNodeType.XmlDeclaration));
                            flag3 = true;
                            if (_xtr.NodeType == XmlNodeType.EndElement)
{
                                xmlSchemaComplexType.Particle.MinOccurs = 0m;
                            }
                        }
                    }
                    else if (xmlSchemaComplexType.ContentModel != null)
                    {
                        XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension5 = CheckSimpleContentExtension(xmlSchemaComplexType);
                        if (_xtr.NodeType == XmlNodeType.Text && num == 1)
{
                            int num2 = -1;
                            if (xse.Parent == null)
{
                                num2 = xmlSchemaSimpleContentExtension5.LineNumber;
                            }
                            else
{
                                num2 = GetSchemaType(xmlSchemaSimpleContentExtension5.BaseTypeName);
                                xse.Parent = null;
                            }
                            xmlSchemaSimpleContentExtension5.BaseTypeName = RefineSimpleType(_xtr.Value, ref num2);
                            xmlSchemaSimpleContentExtension5.LineNumber = num2;
                        }
                        else
{
                            xmlSchemaSimpleContentExtension5.BaseTypeName = ST_string;
                            xmlSchemaSimpleContentExtension5.LineNumber = 262144;
                        }
                    }
                    else
                    {
                        XmlSchemaSimpleContent xmlSchemaSimpleContent2 = (XmlSchemaSimpleContent)(xmlSchemaComplexType.ContentModel = new XmlSchemaSimpleContent());
                        XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension6 = (XmlSchemaSimpleContentExtension)(xmlSchemaSimpleContent2.Content = new XmlSchemaSimpleContentExtension());
                        MoveAttributes(xmlSchemaComplexType, xmlSchemaSimpleContentExtension6, bCreatingNewType);
                        if (_xtr.NodeType == XmlNodeType.Text)
{
                            int iTypeFlags = (bCreatingNewType ? (-1) : 262144);
                            xmlSchemaSimpleContentExtension6.BaseTypeName = RefineSimpleType(_xtr.Value, ref iTypeFlags);
                            xmlSchemaSimpleContentExtension6.LineNumber = iTypeFlags;
                        }
                        else
{
                            xmlSchemaSimpleContentExtension6.BaseTypeName = ST_string;
                            xmlSchemaSimpleContentExtension6.LineNumber = 262144;
                        }
                    }
                }
                else if (num > 1)
                {
                    xse.SchemaTypeName = ST_string;
                    xse.LineNumber = 262144;
                }
                else
                {
                    int iTypeFlags2 = -1;
                    if (bCreatingNewType)
                    {
                        if (_xtr.NodeType == XmlNodeType.Text)
{
                            xse.SchemaTypeName = RefineSimpleType(_xtr.Value, ref iTypeFlags2);
                            xse.LineNumber = iTypeFlags2;
                        }
                        else
{
                            xse.SchemaTypeName = ST_string;
                            xse.LineNumber = 262144;
                        }
                    }
                    else if (_xtr.NodeType == XmlNodeType.Text)
                    {
                        if (xse.Parent == null)
{
                            iTypeFlags2 = xse.LineNumber;
                        }
                        else
{
                            iTypeFlags2 = GetSchemaType(xse.SchemaTypeName);
                            if (iTypeFlags2 == -1 && xse.LineNumber == 262144)
{
                                iTypeFlags2 = 262144;
                            }
                            xse.Parent = null;
                        }
                        xse.SchemaTypeName = RefineSimpleType(_xtr.Value, ref iTypeFlags2);
                        xse.LineNumber = iTypeFlags2;
                    }
                    else
                    {
                        xse.SchemaTypeName = ST_string;
                        xse.LineNumber = 262144;
                    }
                }
            }
            else if (_xtr.NodeType == XmlNodeType.Element)
            {
                XmlQualifiedName key = new XmlQualifiedName(_xtr.LocalName, _xtr.NamespaceURI);
                bool setMaxoccurs = false;
                if (hashtable.Contains(key))
                {
                    setMaxoccurs = true;
                }
                else
                {
                    hashtable.Add(key, null);
                }
                if (xmlSchemaComplexType == null)
                {
                    xmlSchemaComplexType = (XmlSchemaComplexType)(xse.SchemaType = new XmlSchemaComplexType());
                    if (!xse.SchemaTypeName.IsEmpty)
                    {
                        xmlSchemaComplexType.IsMixed = true;
                        xse.SchemaTypeName = XmlQualifiedName.Empty;
                    }
                }
                if (xmlSchemaComplexType.ContentModel != null)
                {
                    XmlSchemaSimpleContentExtension scExtension = CheckSimpleContentExtension(xmlSchemaComplexType);
                    MoveAttributes(scExtension, xmlSchemaComplexType);
                    xmlSchemaComplexType.ContentModel = null;
                    xmlSchemaComplexType.IsMixed = true;
                    if (xmlSchemaComplexType.Particle != null)
                    {
                        throw new XmlSchemaInferenceException(System.SR.SchInf_particle, 0, 0);
                    }
                    xmlSchemaComplexType.Particle = new XmlSchemaSequence();
                    flag2 = true;
                    AddElement(_xtr.LocalName, _xtr.Prefix, _xtr.NamespaceURI, parentSchema, ((XmlSchemaSequence)xmlSchemaComplexType.Particle).Items, -1);
                    lastUsedSeqItem = 0;
                    if (!bCreatingNewType)
                    {
                        xmlSchemaComplexType.Particle.MinOccurs = 0m;
                    }
                }
                else if (xmlSchemaComplexType.Particle == null)
                {
                    xmlSchemaComplexType.Particle = new XmlSchemaSequence();
                    flag2 = true;
                    AddElement(_xtr.LocalName, _xtr.Prefix, _xtr.NamespaceURI, parentSchema, ((XmlSchemaSequence)xmlSchemaComplexType.Particle).Items, -1);
                    if (!bCreatingNewType)
                    {
                        ((XmlSchemaSequence)xmlSchemaComplexType.Particle).MinOccurs = 0m;
                    }
                    lastUsedSeqItem = 0;
                }
                else
                {
                    bool bParticleChanged = false;
                    FindMatchingElement(bCreatingNewType || flag2, _xtr, xmlSchemaComplexType, ref lastUsedSeqItem, ref bParticleChanged, parentSchema, setMaxoccurs);
                }
            }
            else if (_xtr.NodeType == XmlNodeType.Text)
            {
                if (xmlSchemaComplexType == null)
                {
                    throw new XmlSchemaInferenceException(System.SR.SchInf_ct, 0, 0);
                }
                xmlSchemaComplexType.IsMixed = true;
            }
            do
            {
                if (_xtr.NodeType == XmlNodeType.EntityReference)
                {
                    throw new XmlSchemaInferenceException(System.SR.SchInf_entity, 0, 0);
                }
                if (!flag3)
                {
                    _xtr.Read();
                }
                else
                {
                    flag3 = false;
                }
            }
            while (!_xtr.EOF && _xtr.NodeType != XmlNodeType.EndElement && _xtr.NodeType != XmlNodeType.CDATA && _xtr.NodeType != XmlNodeType.Element && _xtr.NodeType != XmlNodeType.Text);
        }
        if (lastUsedSeqItem == -1)
        {
            return;
        }
        while (++lastUsedSeqItem < ((XmlSchemaSequence)xmlSchemaComplexType.Particle).Items.Count)
        {
            if (((XmlSchemaSequence)xmlSchemaComplexType.Particle).Items[lastUsedSeqItem].GetType() != typeof(XmlSchemaElement))
            {
                throw new XmlSchemaInferenceException(System.SR.SchInf_seq, 0, 0);
            }
            XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)((XmlSchemaSequence)xmlSchemaComplexType.Particle).Items[lastUsedSeqItem];
            xmlSchemaElement.MinOccurs = 0m;
        }
    }
References System.Collections.Hashtable.Add(), System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Schema.XmlSchemaSimpleContentExtension.BaseTypeName, System.Collections.Hashtable.Contains(), System.Xml.Schema.XmlSchemaSimpleContent.Content, System.Xml.Schema.XmlSchemaComplexType.ContentModel, System.Xml.XmlQualifiedName.Empty, System.Xml.XmlReader.EOF, System.Xml.XmlQualifiedName.IsEmpty, System.Xml.XmlReader.IsEmptyElement, System.Xml.Schema.XmlSchema.Items, System.key, System.Xml.Schema.XmlSchemaObject.LineNumber, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.Schema.XmlSchemaObject.Parent, System.Xml.Schema.XmlSchemaComplexType.Particle, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Xml.Schema.XmlSchemaElement.SchemaType, System.Xml.Schema.XmlSchemaElement.SchemaTypeName, System.SR.SchInf_ct, System.SR.SchInf_entity, System.SR.SchInf_particle, System.SR.SchInf_seq, and System.Xml.XmlReader.Value.
Referenced by System.Xml.Schema.XmlSchemaInference.InferSchema1().