Terraria: System.Xml.Schema.XmlSchemaInference.AddElement
AddElement()
XmlSchemaElement System.Xml.Schema.XmlSchemaInference.AddElement (string localName, string prefix, string childURI, XmlSchema parentSchema, XmlSchemaObjectCollection addLocation, int positionWithinCollection) inline private
Definition at line 378 of file XmlSchemaInference.cs.
    {
        if (childURI == "http://www.w3.org/2001/XMLSchema")
        {
            throw new XmlSchemaInferenceException(System.SR.SchInf_schema, 0, 0);
        }
        XmlSchemaElement xmlSchemaElement = null;
        XmlSchemaElement xmlSchemaElement2 = xmlSchemaElement;
        XmlSchema parentSchema2 = null;
        bool bCreatingNewType = true;
        if (childURI == string.Empty)
        {
            childURI = null;
        }
        if (parentSchema != null && childURI == parentSchema.TargetNamespace)
        {
            xmlSchemaElement = new XmlSchemaElement();
            xmlSchemaElement.Name = localName;
            parentSchema2 = parentSchema;
            if (parentSchema2.ElementFormDefault != XmlSchemaForm.Qualified && addLocation != null)
            {
                xmlSchemaElement.Form = XmlSchemaForm.Qualified;
            }
        }
        else if (_schemaSet.Contains(childURI))
        {
            xmlSchemaElement = FindGlobalElement(childURI, localName, out parentSchema2);
            if (xmlSchemaElement == null)
            {
                if (_schemaSet.Schemas(childURI) is ArrayList { Count: >0 } arrayList)
                {
                    parentSchema2 = arrayList[0] as XmlSchema;
                }
                xmlSchemaElement = new XmlSchemaElement();
                xmlSchemaElement.Name = localName;
                parentSchema2.Items.Add(xmlSchemaElement);
            }
            else
            {
                bCreatingNewType = false;
            }
        }
        else
        {
            parentSchema2 = CreateXmlSchema(childURI);
            if (prefix.Length != 0)
            {
                _namespaceManager.AddNamespace(prefix, childURI);
            }
            xmlSchemaElement = new XmlSchemaElement();
            xmlSchemaElement.Name = localName;
            parentSchema2.Items.Add(xmlSchemaElement);
        }
        if (parentSchema == null)
        {
            parentSchema = parentSchema2;
            _rootSchema = parentSchema;
        }
        if (childURI != parentSchema.TargetNamespace)
        {
            bool flag = true;
            for (int i = 0; i < parentSchema.Includes.Count; i++)
            {
                if (parentSchema.Includes[i] is XmlSchemaImport xmlSchemaImport && xmlSchemaImport.Namespace == childURI)
                {
                    flag = false;
                }
            }
            if (flag)
            {
                XmlSchemaImport xmlSchemaImport2 = new XmlSchemaImport();
                xmlSchemaImport2.Schema = parentSchema2;
                xmlSchemaImport2.Namespace = childURI;
                parentSchema.Includes.Add(xmlSchemaImport2);
            }
        }
        xmlSchemaElement2 = xmlSchemaElement;
        if (addLocation != null)
        {
            if (childURI == parentSchema.TargetNamespace)
            {
                if (Occurrence == InferenceOption.Relaxed)
                {
                    xmlSchemaElement.MinOccurs = 0m;
                }
                if (positionWithinCollection == -1)
                {
                    positionWithinCollection = addLocation.Add(xmlSchemaElement);
                }
                else
                {
                    addLocation.Insert(positionWithinCollection, xmlSchemaElement);
                }
            }
            else
            {
                XmlSchemaElement xmlSchemaElement3 = new XmlSchemaElement();
                xmlSchemaElement3.RefName = new XmlQualifiedName(localName, childURI);
                if (Occurrence == InferenceOption.Relaxed)
                {
                    xmlSchemaElement3.MinOccurs = 0m;
                }
                if (positionWithinCollection == -1)
                {
                    positionWithinCollection = addLocation.Add(xmlSchemaElement3);
                }
                else
                {
                    addLocation.Insert(positionWithinCollection, xmlSchemaElement3);
                }
                xmlSchemaElement2 = xmlSchemaElement3;
            }
        }
        InferElement(xmlSchemaElement, bCreatingNewType, parentSchema2);
        return xmlSchemaElement2;
    }
References System.Xml.Schema.XmlSchemaObjectCollection.Add(), System.Xml.Schema.XmlSchemaSet.Contains(), System.Collections.CollectionBase.Count, System.Xml.Schema.XmlSchema.ElementFormDefault, System.Xml.Schema.XmlSchema.Includes, System.Xml.Schema.XmlSchemaObjectCollection.Insert(), System.Xml.Schema.XmlSchema.Items, System.Xml.Schema.XmlSchemaImport.Namespace, System.prefix, System.Xml.Schema.XmlSchemaSet.Schemas(), System.SR.SchInf_schema, and System.Xml.Schema.XmlSchema.TargetNamespace.
Referenced by System.Xml.Schema.XmlSchemaInference.InferSchema1().