Terraria: System.Data.ProviderBase.SchemaMapping.GetMappedValues
GetMappedValues()
object[] System.Data.ProviderBase.SchemaMapping.GetMappedValues () inline private
Definition at line 250 of file SchemaMapping.cs.
    {
        if (_xmlMap != null)
        {
            for (int i = 0; i < _xmlMap.Length; i++)
            {
                if (_xmlMap[i] == 0)
                {
                    continue;
                }
                string text = _readerDataValues[i] as string;
                if (text == null && _readerDataValues[i] is SqlString sqlString)
                {
                    if (!sqlString.IsNull)
                    {
                        text = sqlString.Value;
                    }
                    else
                    {
                        object[] readerDataValues = _readerDataValues;
                        int num = i;
                        int num2 = _xmlMap[i];
                        object obj = ((num2 != 1) ? ((object)DBNull.Value) : ((object)SqlXml.Null));
                        readerDataValues[num] = obj;
                    }
                }
                if (text != null)
                {
                    switch (_xmlMap[i])
                    {
                    case 1:
                    {
                        XmlReaderSettings xmlReaderSettings = new XmlReaderSettings();
                        xmlReaderSettings.ConformanceLevel = ConformanceLevel.Fragment;
                        XmlReader value = XmlReader.Create((TextReader)new StringReader(text), xmlReaderSettings, (string?)null);
                        _readerDataValues[i] = new SqlXml(value);
                        break;
                    }
                    case 2:
                    {
                        XmlDocument xmlDocument = new XmlDocument();
                        xmlDocument.LoadXml(text);
                        _readerDataValues[i] = xmlDocument;
                        break;
                    }
                    }
                }
            }
        }
        switch (_mappedMode)
        {
        default:
            return _readerDataValues;
        case 1:
            MappedValues();
            break;
        case 2:
            MappedIndex();
            break;
        case 3:
            MappedChapter();
            break;
        case 4:
            MappedChapterIndex();
            break;
        }
        return _mappedDataValues;
    }
References System.Data.ProviderBase.SchemaMapping._mappedDataValues, System.Data.ProviderBase.SchemaMapping._mappedMode, System.Data.ProviderBase.SchemaMapping._readerDataValues, System.Data.ProviderBase.SchemaMapping._xmlMap, System.Xml.XmlReader.Create(), System.Xml.Dictionary, System.Data.ProviderBase.SchemaMapping.MappedChapter(), System.Data.ProviderBase.SchemaMapping.MappedChapterIndex(), System.Data.ProviderBase.SchemaMapping.MappedIndex(), System.Data.ProviderBase.SchemaMapping.MappedValues(), System.Data.SqlTypes.SqlXml.Null, System.obj, System.text, System.DBNull.Value, and System.value.
Referenced by System.Data.ProviderBase.SchemaMapping.ApplyToDataRow(), and System.Data.ProviderBase.SchemaMapping.LoadDataRow().