Terraria: System.Data.ProviderBase.SchemaMapping.SchemaMapping
SchemaMapping()
System.Data.ProviderBase.SchemaMapping.SchemaMapping (DataAdapter adapter, DataSet dataset, DataTable datatable, DataReaderContainer dataReader, bool keyInfo, SchemaType schemaType, string sourceTableName, bool gettingData, DataColumn parentChapterColumn, object parentChapterValue) inline package
Definition at line 50 of file SchemaMapping.cs.
    {
        _dataSet = dataset;
        _dataTable = datatable;
        _adapter = adapter;
        _dataReader = dataReader;
        if (keyInfo)
        {
            _schemaTable = dataReader.GetSchemaTable();
        }
        if (adapter.ShouldSerializeFillLoadOption())
        {
            _loadOption = adapter.FillLoadOption;
        }
        else if (adapter.AcceptChangesDuringFill)
        {
            _loadOption = (LoadOption)4;
        }
        else
        {
            _loadOption = (LoadOption)5;
        }
        MissingMappingAction missingMappingAction;
        MissingSchemaAction schemaAction;
        if (SchemaType.Mapped == schemaType)
        {
            missingMappingAction = _adapter.MissingMappingAction;
            schemaAction = _adapter.MissingSchemaAction;
            if (!string.IsNullOrEmpty(sourceTableName))
            {
                _tableMapping = _adapter.GetTableMappingBySchemaAction(sourceTableName, sourceTableName, missingMappingAction);
            }
            else if (_dataTable != null)
            {
                int num = _adapter.IndexOfDataSetTable(_dataTable.TableName);
                if (-1 != num)
                {
                    _tableMapping = _adapter.TableMappings[num];
                }
                else
                {
                    _tableMapping = missingMappingAction switch
                    {
                        MissingMappingAction.Passthrough => new DataTableMapping(_dataTable.TableName, _dataTable.TableName),
                        MissingMappingAction.Ignore => null,
                        MissingMappingAction.Error => throw ADP.MissingTableMappingDestination(_dataTable.TableName),
                        _ => throw ADP.InvalidMissingMappingAction(missingMappingAction),
                    };
                }
            }
        }
        else
        {
            if (SchemaType.Source != schemaType)
            {
                throw ADP.InvalidSchemaType(schemaType);
            }
            missingMappingAction = MissingMappingAction.Passthrough;
            schemaAction = MissingSchemaAction.Add;
            if (!string.IsNullOrEmpty(sourceTableName))
            {
                _tableMapping = DataTableMappingCollection.GetTableMappingBySchemaAction(null, sourceTableName, sourceTableName, missingMappingAction);
            }
            else if (_dataTable != null)
            {
                int num2 = _adapter.IndexOfDataSetTable(_dataTable.TableName);
                if (-1 != num2)
                {
                    _tableMapping = _adapter.TableMappings[num2];
                }
                else
                {
                    _tableMapping = new DataTableMapping(_dataTable.TableName, _dataTable.TableName);
                }
            }
        }
        if (_tableMapping == null)
        {
            return;
        }
        if (_dataTable == null)
        {
            _dataTable = _tableMapping.GetDataTableBySchemaAction(_dataSet, schemaAction);
        }
        if (_dataTable != null)
        {
            _fieldNames = GenerateFieldNames(dataReader);
            if (_schemaTable == null)
            {
                _readerDataValues = SetupSchemaWithoutKeyInfo(missingMappingAction, schemaAction, gettingData, parentChapterColumn, parentChapterValue);
            }
            else
            {
                _readerDataValues = SetupSchemaWithKeyInfo(missingMappingAction, schemaAction, gettingData, parentChapterColumn, parentChapterValue);
            }
        }
    }
References System.Data.ProviderBase.SchemaMapping._adapter, System.Data.ProviderBase.SchemaMapping._dataReader, System.Data.ProviderBase.SchemaMapping._dataSet, System.Data.ProviderBase.SchemaMapping._dataTable, System.Data.ProviderBase.SchemaMapping._fieldNames, System.Data.ProviderBase.SchemaMapping._loadOption, System.Data.ProviderBase.SchemaMapping._readerDataValues, System.Data.ProviderBase.SchemaMapping._schemaTable, System.Data.ProviderBase.SchemaMapping._tableMapping, System.Data.Common.DataAdapter.AcceptChangesDuringFill, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Data.Common.DataAdapter.FillLoadOption, System.Data.ProviderBase.SchemaMapping.GenerateFieldNames(), System.Data.Common.DataTableMapping.GetDataTableBySchemaAction(), System.Data.Common.DataTableMappingCollection.GetTableMappingBySchemaAction(), System.Data.Common.DataAdapter.GetTableMappingBySchemaAction(), System.Data.Common.DataAdapter.IndexOfDataSetTable(), System.Data.Common.ADP.InvalidMissingMappingAction(), System.Data.Common.ADP.InvalidSchemaType(), System.Data.Common.DataAdapter.MissingMappingAction, System.Data.Common.DataAdapter.MissingSchemaAction, System.Data.Common.ADP.MissingTableMappingDestination(), System.Data.ProviderBase.SchemaMapping.SetupSchemaWithKeyInfo(), System.Data.ProviderBase.SchemaMapping.SetupSchemaWithoutKeyInfo(), System.Data.Common.DataAdapter.ShouldSerializeFillLoadOption(), System.Data.Common.DataAdapter.TableMappings, and System.Data.DataTable.TableName.