Terraria: System.Data.ProviderBase.SchemaMapping.AddRelation
AddRelation()
void System.Data.ProviderBase.SchemaMapping.AddRelation (DataColumn parentChapterColumn, DataColumn chapterColumn) inline private
Definition at line 1011 of file SchemaMapping.cs.
    {
        if (_dataSet != null)
        {
            string columnName = chapterColumn.ColumnName;
            DataRelation dataRelation = new DataRelation(columnName, new DataColumn[1] { parentChapterColumn }, new DataColumn[1] { chapterColumn }, createConstraints: false);
            int num = 1;
            string relationName = columnName;
            DataRelationCollection relations = _dataSet.Relations;
            while (-1 != relations.IndexOf(relationName))
            {
                relationName = columnName + num;
                num++;
            }
            dataRelation.RelationName = relationName;
            relations.Add(dataRelation);
        }
    }
References System.Data.ProviderBase.SchemaMapping._dataSet, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, and System.Data.DataSet.Relations.
Referenced by System.Data.ProviderBase.SchemaMapping.SetupSchemaWithKeyInfo(), and System.Data.ProviderBase.SchemaMapping.SetupSchemaWithoutKeyInfo().