Terraria: System.Data.ProviderBase.SchemaMapping.ApplyToDataRow
ApplyToDataRow()
void System.Data.ProviderBase.SchemaMapping.ApplyToDataRow (DataRow dataRow) inline package
Definition at line 148 of file SchemaMapping.cs.
    {
        DataColumnCollection columns = dataRow.Table.Columns;
        _dataReader.GetValues(_readerDataValues);
        object[] mappedValues = GetMappedValues();
        bool[] array = new bool[mappedValues.Length];
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = columns[i].ReadOnly;
        }
        try
        {
            try
            {
                for (int j = 0; j < array.Length; j++)
                {
                    if (columns[j].Expression.Length == 0)
                    {
                        columns[j].ReadOnly = false;
                    }
                }
                for (int k = 0; k < mappedValues.Length; k++)
                {
                    object obj = mappedValues[k];
                    if (obj != null)
                    {
                        dataRow[k] = obj;
                    }
                }
            }
            finally
            {
                for (int l = 0; l < array.Length; l++)
                {
                    if (columns[l].Expression.Length == 0)
                    {
                        columns[l].ReadOnly = array[l];
                    }
                }
            }
        }
        finally
        {
            if (_chapterMap != null)
            {
                FreeDataRowChapters();
            }
        }
    }
References System.Data.ProviderBase.SchemaMapping._chapterMap, System.Data.ProviderBase.SchemaMapping._dataReader, System.Data.ProviderBase.SchemaMapping._readerDataValues, System.array, System.Xml.Dictionary, System.Data.ProviderBase.SchemaMapping.FreeDataRowChapters(), System.Data.ProviderBase.SchemaMapping.GetMappedValues(), System.Data.ProviderBase.DataReaderContainer.GetValues(), and System.obj.