Terraria: System.Data.ProviderBase.SchemaMapping.LoadDataRowChapters
LoadDataRowChapters()
int System.Data.ProviderBase.SchemaMapping.LoadDataRowChapters (DataRow dataRow) inline package
Definition at line 380 of file SchemaMapping.cs.
    {
        int num = 0;
        int num2 = _chapterMap.Length;
        for (int i = 0; i < num2; i++)
        {
            if (!_chapterMap[i])
            {
                continue;
            }
            object obj = _readerDataValues[i];
            if (obj == null || Convert.IsDBNull(obj))
            {
                continue;
            }
            _readerDataValues[i] = null;
            using IDataReader dataReader = (IDataReader)obj;
            if (!dataReader.IsClosed)
            {
                DataColumn dataColumn;
                object parentChapterValue;
                if (_indexMap == null)
                {
                    dataColumn = _dataTable.Columns[i];
                    parentChapterValue = dataRow[dataColumn];
                }
                else
                {
                    dataColumn = _dataTable.Columns[_indexMap[i]];
                    parentChapterValue = dataRow[dataColumn];
                }
                string srcTable = _tableMapping.SourceTable + _fieldNames[i];
                DataReaderContainer dataReader2 = DataReaderContainer.Create(dataReader, _dataReader.ReturnProviderSpecificTypes);
                num += _adapter.FillFromReader(_dataSet, null, srcTable, dataReader2, 0, 0, dataColumn, parentChapterValue);
            }
        }
        return num;
    }
References System.Data.ProviderBase.SchemaMapping._adapter, System.Data.ProviderBase.SchemaMapping._chapterMap, System.Data.ProviderBase.SchemaMapping._dataReader, System.Data.ProviderBase.SchemaMapping._dataSet, System.Data.ProviderBase.SchemaMapping._dataTable, System.Data.ProviderBase.SchemaMapping._fieldNames, System.Data.ProviderBase.SchemaMapping._indexMap, System.Data.ProviderBase.SchemaMapping._readerDataValues, System.Data.DataTable.Columns, System.Data.ProviderBase.DataReaderContainer.Create(), System.Xml.Dictionary, System.Data.Common.DataAdapter.FillFromReader(), System.Convert.IsDBNull(), System.obj, and System.Data.ProviderBase.DataReaderContainer.ReturnProviderSpecificTypes.
Referenced by System.Data.ProviderBase.SchemaMapping.LoadDataRow().