Terraria: System.Xml.Schema.XmlSchemaInference.RefineSimpleType
RefineSimpleType()
XmlQualifiedName System.Xml.Schema.XmlSchemaInference.RefineSimpleType (string s, ref int iTypeFlags) inline package
Definition at line 1215 of file XmlSchemaInference.cs.
    {
        bool bNeedsRangeCheck = false;
        s = s.Trim();
        if (iTypeFlags == 262144 || _typeInference == InferenceOption.Relaxed)
        {
            return ST_string;
        }
        iTypeFlags &= InferSimpleType(s, ref bNeedsRangeCheck);
        if (iTypeFlags == 262144)
        {
            return ST_string;
        }
        if (bNeedsRangeCheck)
        {
            if (((uint)iTypeFlags & 2u) != 0)
            {
                try
                {
                    XmlConvert.ToSByte(s);
                    if (((uint)iTypeFlags & 4u) != 0)
                    {
                        return ST_unsignedByte;
                    }
                    return ST_byte;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags &= -3;
            }
            if (((uint)iTypeFlags & 4u) != 0)
            {
                try
                {
                    XmlConvert.ToByte(s);
                    return ST_unsignedByte;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags &= -5;
            }
            if (((uint)iTypeFlags & 8u) != 0)
            {
                try
                {
                    XmlConvert.ToInt16(s);
                    if (((uint)iTypeFlags & 0x10u) != 0)
                    {
                        return ST_unsignedShort;
                    }
                    return ST_short;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags &= -9;
            }
            if (((uint)iTypeFlags & 0x10u) != 0)
            {
                try
                {
                    XmlConvert.ToUInt16(s);
                    return ST_unsignedShort;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags &= -17;
            }
            if (((uint)iTypeFlags & 0x20u) != 0)
            {
                try
                {
                    XmlConvert.ToInt32(s);
                    if (((uint)iTypeFlags & 0x40u) != 0)
                    {
                        return ST_unsignedInt;
                    }
                    return ST_int;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags &= -33;
            }
            if (((uint)iTypeFlags & 0x40u) != 0)
            {
                try
                {
                    XmlConvert.ToUInt32(s);
                    return ST_unsignedInt;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags &= -65;
            }
            if (((uint)iTypeFlags & 0x80u) != 0)
            {
                try
                {
                    XmlConvert.ToInt64(s);
                    if (((uint)iTypeFlags & 0x100u) != 0)
                    {
                        return ST_unsignedLong;
                    }
                    return ST_long;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags &= -129;
            }
            if (((uint)iTypeFlags & 0x100u) != 0)
            {
                try
                {
                    XmlConvert.ToUInt64(s);
                    return ST_unsignedLong;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags &= -257;
            }
            if (((uint)iTypeFlags & 0x1000u) != 0)
            {
                try
                {
                    double num = XmlConvert.ToDouble(s);
                    if (((uint)iTypeFlags & 0x200u) != 0)
                    {
                        return ST_integer;
                    }
                    if (((uint)iTypeFlags & 0x400u) != 0)
                    {
                        return ST_decimal;
                    }
                    if (((uint)iTypeFlags & 0x800u) != 0)
                    {
                        try
{
                            float num2 = XmlConvert.ToSingle(s);
                            if (string.Equals(XmlConvert.ToString(num2), XmlConvert.ToString(num), StringComparison.OrdinalIgnoreCase))
{
                                return ST_float;
                            }
                        }
                        catch (FormatException)
{
                        }
                        catch (OverflowException)
{
                        }
                    }
                    iTypeFlags &= -2049;
                    return ST_double;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags &= -4097;
            }
            if (((uint)iTypeFlags & 0x800u) != 0)
            {
                try
                {
                    XmlConvert.ToSingle(s);
                    if (((uint)iTypeFlags & 0x200u) != 0)
                    {
                        return ST_integer;
                    }
                    if (((uint)iTypeFlags & 0x400u) != 0)
                    {
                        return ST_decimal;
                    }
                    return ST_float;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags &= -2049;
            }
            if (((uint)iTypeFlags & 0x200u) != 0)
            {
                return ST_integer;
            }
            if (((uint)iTypeFlags & 0x400u) != 0)
            {
                return ST_decimal;
            }
            if (iTypeFlags == 393216)
            {
                try
                {
                    XmlConvert.ToDateTime(s, XmlDateTimeSerializationMode.RoundtripKind);
                    return ST_gYearMonth;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags = 262144;
                return ST_string;
            }
            if (iTypeFlags == 270336)
            {
                try
                {
                    XmlConvert.ToTimeSpan(s);
                    return ST_duration;
                }
                catch (FormatException)
                {
                }
                catch (OverflowException)
                {
                }
                iTypeFlags = 262144;
                return ST_string;
            }
            if (iTypeFlags == 262145)
            {
                return ST_boolean;
            }
        }
        return iTypeFlags switch
        {
            262144 => ST_string,
            1 => ST_boolean,
            2 => ST_byte,
            4 => ST_unsignedByte,
            8 => ST_short,
            16 => ST_unsignedShort,
            32 => ST_int,
            64 => ST_unsignedInt,
            128 => ST_long,
            256 => ST_unsignedLong,
            512 => ST_integer,
            1024 => ST_decimal,
            2048 => ST_float,
            4096 => ST_double,
            8192 => ST_duration,
            16384 => ST_dateTime,
            32768 => ST_time,
            65536 => ST_date,
            131072 => ST_gYearMonth,
            262145 => ST_boolean,
            278528 => ST_dateTime,
            327680 => ST_date,
            294912 => ST_time,
            268288 => ST_float,
            266240 => ST_double,
            _ => ST_string,
        };
    }
References System.s, System.Xml.XmlConvert.ToByte(), System.Xml.XmlConvert.ToDateTime(), System.Xml.XmlConvert.ToDouble(), System.Xml.XmlConvert.ToInt16(), System.Xml.XmlConvert.ToInt32(), System.Xml.XmlConvert.ToInt64(), System.Xml.XmlConvert.ToSByte(), System.Xml.XmlConvert.ToSingle(), System.Xml.XmlConvert.ToString(), System.Xml.XmlConvert.ToTimeSpan(), System.Xml.XmlConvert.ToUInt16(), System.Xml.XmlConvert.ToUInt32(), and System.Xml.XmlConvert.ToUInt64().
Referenced by System.Xml.Schema.XmlSchemaInference.AddAttribute().