Terraria: System.Data.ProviderBase.SchemaMapping.RollbackAddedItems
RollbackAddedItems()
void System.Data.ProviderBase.SchemaMapping.RollbackAddedItems (List< object > items) inline private
Definition at line 456 of file SchemaMapping.cs.
    {
        if (items == null)
        {
            return;
        }
        int num = items.Count - 1;
        while (0 <= num)
        {
            if (items[num] != null)
            {
                if (items[num] is DataColumn dataColumn)
                {
                    if (dataColumn.Table != null)
                    {
                        dataColumn.Table.Columns.Remove(dataColumn);
                    }
                }
                else if (items[num] is DataTable { DataSet: not null } dataTable)
                {
                    dataTable.DataSet.Tables.Remove(dataTable);
                }
            }
            num--;
        }
    }
References System.Xml.Dictionary, and System.Collections.Generic.Dictionary< TKey, TValue >.Remove().
Referenced by System.Data.ProviderBase.SchemaMapping.SetupSchemaWithKeyInfo(), and System.Data.ProviderBase.SchemaMapping.SetupSchemaWithoutKeyInfo().