Terraria: System.Data.ProviderBase.SchemaMapping.LoadDataRow
LoadDataRow()
void System.Data.ProviderBase.SchemaMapping.LoadDataRow () inline package
Definition at line 330 of file SchemaMapping.cs.
    {
        try
        {
            _dataReader.GetValues(_readerDataValues);
            object[] mappedValues = GetMappedValues();
            DataRow dataRow;
            switch (_loadOption)
            {
            case LoadOption.OverwriteChanges:
            case LoadOption.PreserveChanges:
            case LoadOption.Upsert:
                dataRow = _dataTable.LoadDataRow(mappedValues, _loadOption);
                break;
            case (LoadOption)4:
                dataRow = _dataTable.LoadDataRow(mappedValues, fAcceptChanges: true);
                break;
            case (LoadOption)5:
                dataRow = _dataTable.LoadDataRow(mappedValues, fAcceptChanges: false);
                break;
            default:
                throw ADP.InvalidLoadOption(_loadOption);
            }
            if (_chapterMap != null && _dataSet != null)
            {
                LoadDataRowChapters(dataRow);
            }
        }
        finally
        {
            if (_chapterMap != null)
            {
                FreeDataRowChapters();
            }
        }
    }
References System.Data.ProviderBase.SchemaMapping._chapterMap, System.Data.ProviderBase.SchemaMapping._dataReader, System.Data.ProviderBase.SchemaMapping._dataSet, System.Data.ProviderBase.SchemaMapping._dataTable, System.Data.ProviderBase.SchemaMapping._loadOption, System.Data.ProviderBase.SchemaMapping._readerDataValues, System.Xml.Dictionary, System.Data.ProviderBase.SchemaMapping.FreeDataRowChapters(), System.Data.ProviderBase.SchemaMapping.GetMappedValues(), System.Data.ProviderBase.DataReaderContainer.GetValues(), System.Data.Common.ADP.InvalidLoadOption(), System.Data.DataTable.LoadDataRow(), and System.Data.ProviderBase.SchemaMapping.LoadDataRowChapters().
Referenced by System.Data.Common.DataAdapter.FillLoadDataRow(), System.Data.Common.DataAdapter.FillLoadDataRowChunk(), and System.Data.ProviderBase.SchemaMapping.LoadDataRowWithClear().