Terraria: System.Data.ProviderBase.SchemaMapping.SetupSchemaWithoutKeyInfo
SetupSchemaWithoutKeyInfo()
object[] System.Data.ProviderBase.SchemaMapping.SetupSchemaWithoutKeyInfo (MissingMappingAction mappingAction, MissingSchemaAction schemaAction, bool gettingData, DataColumn parentChapterColumn, object chapterValue) inline private
Definition at line 484 of file SchemaMapping.cs.
    {
        int[] array = null;
        bool[] array2 = null;
        int num = 0;
        int fieldCount = _dataReader.FieldCount;
        object[] result = null;
        List<object> items = null;
        try
        {
            DataColumnCollection columns = _dataTable.Columns;
            columns.EnsureAdditionalCapacity(fieldCount + ((chapterValue != null) ? 1 : 0));
            bool flag = _dataTable.Columns.Count == 0 && (_tableMapping.ColumnMappings == null || _tableMapping.ColumnMappings.Count == 0) && mappingAction == MissingMappingAction.Passthrough;
            for (int i = 0; i < fieldCount; i++)
            {
                bool flag2 = false;
                Type type = _dataReader.GetFieldType(i);
                if (null == type)
                {
                    throw ADP.MissingDataReaderFieldType(i);
                }
                if (typeof(IDataReader).IsAssignableFrom(type))
                {
                    if (array2 == null)
                    {
                        array2 = new bool[fieldCount];
                    }
                    flag2 = (array2[i] = true);
                    type = typeof(int);
                }
                else if (typeof(SqlXml).IsAssignableFrom(type))
                {
                    if (_xmlMap == null)
                    {
                        _xmlMap = new int[fieldCount];
                    }
                    _xmlMap[i] = 1;
                }
                else if (typeof(XmlReader).IsAssignableFrom(type))
                {
                    type = typeof(string);
                    if (_xmlMap == null)
                    {
                        _xmlMap = new int[fieldCount];
                    }
                    _xmlMap[i] = 2;
                }
                DataColumn dataColumn = ((!flag) ? _tableMapping.GetDataColumn(_fieldNames[i], type, _dataTable, mappingAction, schemaAction) : DataColumnMapping.CreateDataColumnBySchemaAction(_fieldNames[i], _fieldNames[i], _dataTable, type, schemaAction));
                if (dataColumn == null)
                {
                    if (array == null)
                    {
                        array = CreateIndexMap(fieldCount, i);
                    }
                    array[i] = -1;
                    continue;
                }
                if (_xmlMap != null && _xmlMap[i] != 0)
                {
                    if (typeof(SqlXml) == dataColumn.DataType)
                    {
                        _xmlMap[i] = 1;
                    }
                    else if (typeof(XmlDocument) == dataColumn.DataType)
                    {
                        _xmlMap[i] = 2;
                    }
                    else
                    {
                        _xmlMap[i] = 0;
                        int num2 = 0;
                        for (int j = 0; j < _xmlMap.Length; j++)
{
                            num2 += _xmlMap[j];
                        }
                        if (num2 == 0)
{
                            _xmlMap = null;
                        }
                    }
                }
                if (dataColumn.Table == null)
                {
                    if (flag2)
                    {
                        dataColumn.AllowDBNull = false;
                        dataColumn.AutoIncrement = true;
                        dataColumn.ReadOnly = true;
                    }
                    AddItemToAllowRollback(ref items, dataColumn);
                    columns.Add(dataColumn);
                }
                else if (flag2 && !dataColumn.AutoIncrement)
                {
                    throw ADP.FillChapterAutoIncrement();
                }
                if (array != null)
                {
                    array[i] = dataColumn.Ordinal;
                }
                else if (i != dataColumn.Ordinal)
                {
                    array = CreateIndexMap(fieldCount, i);
                    array[i] = dataColumn.Ordinal;
                }
                num++;
            }
            bool flag3 = false;
            DataColumn dataColumn2 = null;
            if (chapterValue != null)
            {
                Type type2 = chapterValue.GetType();
                dataColumn2 = _tableMapping.GetDataColumn(_tableMapping.SourceTable, type2, _dataTable, mappingAction, schemaAction);
                if (dataColumn2 != null)
                {
                    if (dataColumn2.Table == null)
                    {
                        AddItemToAllowRollback(ref items, dataColumn2);
                        columns.Add(dataColumn2);
                        flag3 = parentChapterColumn != null;
                    }
                    num++;
                }
            }
            if (0 < num)
            {
                if (_dataSet != null && _dataTable.DataSet == null)
                {
                    AddItemToAllowRollback(ref items, _dataTable);
                    _dataSet.Tables.Add(_dataTable);
                }
                if (gettingData)
                {
                    if (columns == null)
                    {
                        columns = _dataTable.Columns;
                    }
                    _indexMap = array;
                    _chapterMap = array2;
                    result = SetupMapping(fieldCount, columns, dataColumn2, chapterValue);
                }
                else
                {
                    _mappedMode = -1;
                }
            }
            else
            {
                _dataTable = null;
            }
            if (flag3)
            {
                AddRelation(parentChapterColumn, dataColumn2);
            }
        }
        catch (Exception e) when (ADP.IsCatchableOrSecurityExceptionType(e))
        {
            RollbackAddedItems(items);
            throw;
        }
        return result;
    }
References System.Data.ProviderBase.SchemaMapping._chapterMap, System.Data.ProviderBase.SchemaMapping._dataReader, System.Data.ProviderBase.SchemaMapping._dataSet, System.Data.ProviderBase.SchemaMapping._dataTable, System.Data.ProviderBase.SchemaMapping._fieldNames, System.Data.ProviderBase.SchemaMapping._indexMap, System.Data.ProviderBase.SchemaMapping._mappedMode, System.Data.ProviderBase.SchemaMapping._tableMapping, System.Data.ProviderBase.SchemaMapping._xmlMap, System.Data.DataTableCollection.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.ProviderBase.SchemaMapping.AddItemToAllowRollback(), System.Data.ProviderBase.SchemaMapping.AddRelation(), System.array, System.Data.DataTable.Columns, System.Data.Common.DataColumnMapping.CreateDataColumnBySchemaAction(), System.Data.ProviderBase.SchemaMapping.CreateIndexMap(), System.Data.DataTable.DataSet, System.Xml.Dictionary, System.Data.ProviderBase.DataReaderContainer.FieldCount, System.Data.Common.ADP.FillChapterAutoIncrement(), System.Data.Common.DataTableMapping.GetDataColumn(), System.Data.ProviderBase.DataReaderContainer.GetFieldType(), System.Data.Common.ADP.IsCatchableOrSecurityExceptionType(), System.Data.Common.ADP.MissingDataReaderFieldType(), System.Data.ProviderBase.SchemaMapping.RollbackAddedItems(), System.Data.ProviderBase.SchemaMapping.SetupMapping(), System.Data.Common.DataTableMapping.SourceTable, System.Data.DataSet.Tables, and System.type.
Referenced by System.Data.ProviderBase.SchemaMapping.SchemaMapping().