Terraria: System.Xml.Schema.XmlSchemaInference.AddAttribute
AddAttribute()
XmlSchemaAttribute System.Xml.Schema.XmlSchemaInference.AddAttribute (string localName, string prefix, string childURI, string attrValue, bool bCreatingNewType, XmlSchema parentSchema, XmlSchemaObjectCollection addLocation, XmlSchemaObjectTable compiledAttributes) inline private
Definition at line 179 of file XmlSchemaInference.cs.
    {
        if (childURI == "http://www.w3.org/2001/XMLSchema")
        {
            throw new XmlSchemaInferenceException(System.SR.SchInf_schema, 0, 0);
        }
        XmlSchemaAttribute xmlSchemaAttribute = null;
        int iTypeFlags = -1;
        XmlSchemaAttribute xmlSchemaAttribute2 = null;
        XmlSchema xmlSchema = null;
        bool flag = true;
        ICollection attributes;
        ICollection collection;
        if (compiledAttributes.Count > 0)
        {
            attributes = compiledAttributes.Values;
            collection = addLocation;
        }
        else
        {
            attributes = addLocation;
            collection = null;
        }
        if (childURI == "http://www.w3.org/XML/1998/namespace")
        {
            XmlSchemaAttribute xmlSchemaAttribute3 = null;
            xmlSchemaAttribute3 = FindAttributeRef(attributes, localName, childURI);
            if (xmlSchemaAttribute3 == null && collection != null)
            {
                xmlSchemaAttribute3 = FindAttributeRef(collection, localName, childURI);
            }
            if (xmlSchemaAttribute3 == null)
            {
                xmlSchemaAttribute3 = new XmlSchemaAttribute();
                xmlSchemaAttribute3.RefName = new XmlQualifiedName(localName, childURI);
                if (bCreatingNewType && Occurrence == InferenceOption.Restricted)
                {
                    xmlSchemaAttribute3.Use = XmlSchemaUse.Required;
                }
                else
                {
                    xmlSchemaAttribute3.Use = XmlSchemaUse.Optional;
                }
                addLocation.Add(xmlSchemaAttribute3);
            }
            xmlSchemaAttribute2 = xmlSchemaAttribute3;
        }
        else
        {
            if (childURI.Length == 0)
            {
                xmlSchema = parentSchema;
                flag = false;
            }
            else if (childURI != null && !_schemaSet.Contains(childURI))
            {
                xmlSchema = new XmlSchema();
                xmlSchema.AttributeFormDefault = XmlSchemaForm.Unqualified;
                xmlSchema.ElementFormDefault = XmlSchemaForm.Qualified;
                if (childURI.Length != 0)
                {
                    xmlSchema.TargetNamespace = childURI;
                }
                _schemaSet.Add(xmlSchema);
                if (prefix.Length != 0 && !string.Equals(prefix, "xml", StringComparison.OrdinalIgnoreCase))
                {
                    _namespaceManager.AddNamespace(prefix, childURI);
                }
            }
            else if (_schemaSet.Schemas(childURI) is ArrayList { Count: >0 } arrayList)
            {
                xmlSchema = arrayList[0] as XmlSchema;
            }
            if (childURI.Length != 0)
            {
                XmlSchemaAttribute xmlSchemaAttribute4 = null;
                xmlSchemaAttribute4 = FindAttributeRef(attributes, localName, childURI);
                if (xmlSchemaAttribute4 == null && collection != null)
                {
                    xmlSchemaAttribute4 = FindAttributeRef(collection, localName, childURI);
                }
                if (xmlSchemaAttribute4 == null)
                {
                    xmlSchemaAttribute4 = new XmlSchemaAttribute();
                    xmlSchemaAttribute4.RefName = new XmlQualifiedName(localName, childURI);
                    if (bCreatingNewType && Occurrence == InferenceOption.Restricted)
                    {
                        xmlSchemaAttribute4.Use = XmlSchemaUse.Required;
                    }
                    else
                    {
                        xmlSchemaAttribute4.Use = XmlSchemaUse.Optional;
                    }
                    addLocation.Add(xmlSchemaAttribute4);
                }
                xmlSchemaAttribute2 = xmlSchemaAttribute4;
                xmlSchemaAttribute = FindAttribute(xmlSchema.Items, localName);
                if (xmlSchemaAttribute == null)
                {
                    xmlSchemaAttribute = new XmlSchemaAttribute();
                    xmlSchemaAttribute.Name = localName;
                    xmlSchemaAttribute.SchemaTypeName = RefineSimpleType(attrValue, ref iTypeFlags);
                    xmlSchemaAttribute.LineNumber = iTypeFlags;
                    xmlSchema.Items.Add(xmlSchemaAttribute);
                }
                else
                {
                    if (xmlSchemaAttribute.Parent == null)
                    {
                        iTypeFlags = xmlSchemaAttribute.LineNumber;
                    }
                    else
                    {
                        iTypeFlags = GetSchemaType(xmlSchemaAttribute.SchemaTypeName);
                        xmlSchemaAttribute.Parent = null;
                    }
                    xmlSchemaAttribute.SchemaTypeName = RefineSimpleType(attrValue, ref iTypeFlags);
                    xmlSchemaAttribute.LineNumber = iTypeFlags;
                }
            }
            else
            {
                xmlSchemaAttribute = FindAttribute(attributes, localName);
                if (xmlSchemaAttribute == null && collection != null)
                {
                    xmlSchemaAttribute = FindAttribute(collection, localName);
                }
                if (xmlSchemaAttribute == null)
                {
                    xmlSchemaAttribute = new XmlSchemaAttribute();
                    xmlSchemaAttribute.Name = localName;
                    xmlSchemaAttribute.SchemaTypeName = RefineSimpleType(attrValue, ref iTypeFlags);
                    xmlSchemaAttribute.LineNumber = iTypeFlags;
                    if (bCreatingNewType && Occurrence == InferenceOption.Restricted)
                    {
                        xmlSchemaAttribute.Use = XmlSchemaUse.Required;
                    }
                    else
                    {
                        xmlSchemaAttribute.Use = XmlSchemaUse.Optional;
                    }
                    addLocation.Add(xmlSchemaAttribute);
                    if (xmlSchema.AttributeFormDefault != XmlSchemaForm.Unqualified)
                    {
                        xmlSchemaAttribute.Form = XmlSchemaForm.Unqualified;
                    }
                }
                else
                {
                    if (xmlSchemaAttribute.Parent == null)
                    {
                        iTypeFlags = xmlSchemaAttribute.LineNumber;
                    }
                    else
                    {
                        iTypeFlags = GetSchemaType(xmlSchemaAttribute.SchemaTypeName);
                        xmlSchemaAttribute.Parent = null;
                    }
                    xmlSchemaAttribute.SchemaTypeName = RefineSimpleType(attrValue, ref iTypeFlags);
                    xmlSchemaAttribute.LineNumber = iTypeFlags;
                }
                xmlSchemaAttribute2 = xmlSchemaAttribute;
            }
        }
        string @namespace = null;
        if (flag && childURI != parentSchema.TargetNamespace)
        {
            for (int i = 0; i < parentSchema.Includes.Count; i++)
            {
                if (parentSchema.Includes[i] is XmlSchemaImport xmlSchemaImport && xmlSchemaImport.Namespace == childURI)
                {
                    flag = false;
                }
            }
            if (flag)
            {
                XmlSchemaImport xmlSchemaImport2 = new XmlSchemaImport();
                xmlSchemaImport2.Schema = xmlSchema;
                if (childURI.Length != 0)
                {
                    @namespace = childURI;
                }
                xmlSchemaImport2.Namespace = @namespace;
                parentSchema.Includes.Add(xmlSchemaImport2);
            }
        }
        return xmlSchemaAttribute2;
    }
References System.Xml.Schema.XmlSchemaInference._namespaceManager, System.Xml.Schema.XmlSchemaInference._schemaSet, System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.Schema.XmlSchemaObjectCollection.Add(), System.Xml.XmlNamespaceManager.AddNamespace(), System.collection, System.Xml.Schema.XmlSchemaSet.Contains(), System.Collections.CollectionBase.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaInference.FindAttribute(), System.Xml.Schema.XmlSchemaInference.FindAttributeRef(), System.Xml.Schema.XmlSchemaInference.GetSchemaType(), System.Xml.Schema.XmlSchema.Includes, System.Xml.Schema.XmlSchemaImport.Namespace, System.Xml.Schema.XmlSchemaInference.Occurrence, System.prefix, System.Xml.Schema.XmlSchemaInference.RefineSimpleType(), System.Xml.Schema.XmlSchemaSet.Schemas(), System.SR.SchInf_schema, and System.Xml.Schema.XmlSchema.TargetNamespace.