Terraria: System.Data.ProviderBase.SchemaMapping.SetupMapping
SetupMapping()
object[] System.Data.ProviderBase.SchemaMapping.SetupMapping (int count, DataColumnCollection columnCollection, DataColumn chapterColumn, object chapterValue) inline private
Definition at line 1030 of file SchemaMapping.cs.
    {
        object[] result = new object[count];
        if (_indexMap == null)
        {
            int count2 = columnCollection.Count;
            bool flag = _chapterMap != null;
            if (count != count2 || flag)
            {
                _mappedDataValues = new object[count2];
                if (flag)
                {
                    _mappedMode = 3;
                    _mappedLength = count;
                }
                else
                {
                    _mappedMode = 1;
                    _mappedLength = Math.Min(count, count2);
                }
            }
            else
            {
                _mappedMode = 0;
            }
        }
        else
        {
            _mappedDataValues = new object[columnCollection.Count];
            _mappedMode = ((_chapterMap == null) ? 2 : 4);
            _mappedLength = count;
        }
        if (chapterColumn != null)
        {
            _mappedDataValues[chapterColumn.Ordinal] = chapterValue;
        }
        return result;
    }
References System.Data.ProviderBase.SchemaMapping._chapterMap, System.Data.ProviderBase.SchemaMapping._indexMap, System.Data.ProviderBase.SchemaMapping._mappedDataValues, System.Data.ProviderBase.SchemaMapping._mappedLength, System.Data.ProviderBase.SchemaMapping._mappedMode, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, and System.Math.Min().
Referenced by System.Data.ProviderBase.SchemaMapping.SetupSchemaWithKeyInfo(), and System.Data.ProviderBase.SchemaMapping.SetupSchemaWithoutKeyInfo().