Terraria: System.Data.ProviderBase.SchemaMapping.SetupSchemaWithKeyInfo
SetupSchemaWithKeyInfo()
object[] System.Data.ProviderBase.SchemaMapping.SetupSchemaWithKeyInfo (MissingMappingAction mappingAction, MissingSchemaAction schemaAction, bool gettingData, DataColumn parentChapterColumn, object chapterValue) inline private
Definition at line 648 of file SchemaMapping.cs.
    {
        DbSchemaRow[] sortedSchemaRows = DbSchemaRow.GetSortedSchemaRows(_schemaTable, _dataReader.ReturnProviderSpecificTypes);
        if (sortedSchemaRows.Length == 0)
        {
            _dataTable = null;
            return null;
        }
        bool flag = (_dataTable.PrimaryKey.Length == 0 && ((LoadOption)4 <= _loadOption || _dataTable.Rows.Count == 0)) || _dataTable.Columns.Count == 0;
        DataColumn[] array = null;
        int num = 0;
        bool flag2 = true;
        string text = null;
        string text2 = null;
        bool flag3 = false;
        bool flag4 = false;
        int[] array2 = null;
        bool[] array3 = null;
        int num2 = 0;
        object[] result = null;
        List<object> items = null;
        DataColumnCollection columns = _dataTable.Columns;
        try
        {
            for (int i = 0; i < sortedSchemaRows.Length; i++)
            {
                DbSchemaRow dbSchemaRow = sortedSchemaRows[i];
                int unsortedIndex = dbSchemaRow.UnsortedIndex;
                bool flag5 = false;
                Type type = dbSchemaRow.DataType;
                if (null == type)
                {
                    type = _dataReader.GetFieldType(i);
                }
                if (null == type)
                {
                    throw ADP.MissingDataReaderFieldType(i);
                }
                if (typeof(IDataReader).IsAssignableFrom(type))
                {
                    if (array3 == null)
                    {
                        array3 = new bool[sortedSchemaRows.Length];
                    }
                    flag5 = (array3[unsortedIndex] = true);
                    type = typeof(int);
                }
                else if (typeof(SqlXml).IsAssignableFrom(type))
                {
                    if (_xmlMap == null)
                    {
                        _xmlMap = new int[sortedSchemaRows.Length];
                    }
                    _xmlMap[i] = 1;
                }
                else if (typeof(XmlReader).IsAssignableFrom(type))
                {
                    type = typeof(string);
                    if (_xmlMap == null)
                    {
                        _xmlMap = new int[sortedSchemaRows.Length];
                    }
                    _xmlMap[i] = 2;
                }
                DataColumn dataColumn = null;
                if (!dbSchemaRow.IsHidden)
                {
                    dataColumn = _tableMapping.GetDataColumn(_fieldNames[i], type, _dataTable, mappingAction, schemaAction);
                }
                string baseTableName = dbSchemaRow.BaseTableName;
                if (dataColumn == null)
                {
                    if (array2 == null)
                    {
                        array2 = CreateIndexMap(sortedSchemaRows.Length, unsortedIndex);
                    }
                    array2[unsortedIndex] = -1;
                    if (dbSchemaRow.IsKey && (flag3 || dbSchemaRow.BaseTableName == text))
                    {
                        flag = false;
                        array = null;
                    }
                    continue;
                }
                if (_xmlMap != null && _xmlMap[i] != 0)
                {
                    if (typeof(SqlXml) == dataColumn.DataType)
                    {
                        _xmlMap[i] = 1;
                    }
                    else if (typeof(XmlDocument) == dataColumn.DataType)
                    {
                        _xmlMap[i] = 2;
                    }
                    else
                    {
                        _xmlMap[i] = 0;
                        int num3 = 0;
                        for (int j = 0; j < _xmlMap.Length; j++)
{
                            num3 += _xmlMap[j];
                        }
                        if (num3 == 0)
{
                            _xmlMap = null;
                        }
                    }
                }
                if (dbSchemaRow.IsKey && baseTableName != text)
                {
                    if (text == null)
                    {
                        text = baseTableName;
                    }
                    else
                    {
                        flag3 = true;
                    }
                }
                if (flag5)
                {
                    if (dataColumn.Table == null)
                    {
                        dataColumn.AllowDBNull = false;
                        dataColumn.AutoIncrement = true;
                        dataColumn.ReadOnly = true;
                    }
                    else if (!dataColumn.AutoIncrement)
                    {
                        throw ADP.FillChapterAutoIncrement();
                    }
                }
                else
                {
                    if (!flag4 && baseTableName != text2 && !string.IsNullOrEmpty(baseTableName))
                    {
                        if (text2 == null)
{
                            text2 = baseTableName;
                        }
                        else
{
                            flag4 = true;
                        }
                    }
                    if ((LoadOption)4 <= _loadOption)
                    {
                        if (dbSchemaRow.IsAutoIncrement && DataColumn.IsAutoIncrementType(type))
{
                            dataColumn.AutoIncrement = true;
                            if (!dbSchemaRow.AllowDBNull)
{
                                dataColumn.AllowDBNull = false;
                            }
                        }
                        if (type == typeof(string))
{
                            dataColumn.MaxLength = ((dbSchemaRow.Size > 0) ? dbSchemaRow.Size : (-1));
                        }
                        if (dbSchemaRow.IsReadOnly)
{
                            dataColumn.ReadOnly = true;
                        }
                        if (!dbSchemaRow.AllowDBNull && (!dbSchemaRow.IsReadOnly || dbSchemaRow.IsKey))
{
                            dataColumn.AllowDBNull = false;
                        }
                        if (dbSchemaRow.IsUnique && !dbSchemaRow.IsKey && !type.IsArray)
{
                            dataColumn.Unique = true;
                            if (!dbSchemaRow.AllowDBNull)
{
                                dataColumn.AllowDBNull = false;
                            }
                        }
                    }
                    else if (dataColumn.Table == null)
                    {
                        dataColumn.AutoIncrement = dbSchemaRow.IsAutoIncrement;
                        dataColumn.AllowDBNull = dbSchemaRow.AllowDBNull;
                        dataColumn.ReadOnly = dbSchemaRow.IsReadOnly;
                        dataColumn.Unique = dbSchemaRow.IsUnique;
                        if (type == typeof(string) || type == typeof(SqlString))
{
                            dataColumn.MaxLength = dbSchemaRow.Size;
                        }
                    }
                }
                if (dataColumn.Table == null)
                {
                    if ((LoadOption)4 > _loadOption)
                    {
                        AddAdditionalProperties(dataColumn, dbSchemaRow.DataRow);
                    }
                    AddItemToAllowRollback(ref items, dataColumn);
                    columns.Add(dataColumn);
                }
                if (flag && dbSchemaRow.IsKey)
                {
                    if (array == null)
                    {
                        array = new DataColumn[sortedSchemaRows.Length];
                    }
                    array[num++] = dataColumn;
                    if (flag2 && dataColumn.AllowDBNull)
                    {
                        flag2 = false;
                    }
                }
                if (array2 != null)
                {
                    array2[unsortedIndex] = dataColumn.Ordinal;
                }
                else if (unsortedIndex != dataColumn.Ordinal)
                {
                    array2 = CreateIndexMap(sortedSchemaRows.Length, unsortedIndex);
                    array2[unsortedIndex] = dataColumn.Ordinal;
                }
                num2++;
            }
            bool flag6 = false;
            DataColumn dataColumn2 = null;
            if (chapterValue != null)
            {
                Type type2 = chapterValue.GetType();
                dataColumn2 = _tableMapping.GetDataColumn(_tableMapping.SourceTable, type2, _dataTable, mappingAction, schemaAction);
                if (dataColumn2 != null)
                {
                    if (dataColumn2.Table == null)
                    {
                        dataColumn2.ReadOnly = true;
                        dataColumn2.AllowDBNull = false;
                        AddItemToAllowRollback(ref items, dataColumn2);
                        columns.Add(dataColumn2);
                        flag6 = parentChapterColumn != null;
                    }
                    num2++;
                }
            }
            if (0 < num2)
            {
                if (_dataSet != null && _dataTable.DataSet == null)
                {
                    AddItemToAllowRollback(ref items, _dataTable);
                    _dataSet.Tables.Add(_dataTable);
                }
                if (flag && array != null)
                {
                    if (num < array.Length)
                    {
                        array = ResizeColumnArray(array, num);
                    }
                    if (flag2)
                    {
                        _dataTable.PrimaryKey = array;
                    }
                    else
                    {
                        UniqueConstraint uniqueConstraint = new UniqueConstraint("", array);
                        ConstraintCollection constraints = _dataTable.Constraints;
                        int count = constraints.Count;
                        for (int k = 0; k < count; k++)
{
                            if (uniqueConstraint.Equals(constraints[k]))
{
                                uniqueConstraint = null;
                                break;
                            }
                        }
                        if (uniqueConstraint != null)
{
                            constraints.Add(uniqueConstraint);
                        }
                    }
                }
                if (!flag4 && !string.IsNullOrEmpty(text2) && string.IsNullOrEmpty(_dataTable.TableName))
                {
                    _dataTable.TableName = text2;
                }
                if (gettingData)
                {
                    _indexMap = array2;
                    _chapterMap = array3;
                    result = SetupMapping(sortedSchemaRows.Length, columns, dataColumn2, chapterValue);
                }
                else
                {
                    _mappedMode = -1;
                }
            }
            else
            {
                _dataTable = null;
            }
            if (flag6)
            {
                AddRelation(parentChapterColumn, dataColumn2);
            }
        }
        catch (Exception e) when (ADP.IsCatchableOrSecurityExceptionType(e))
        {
            RollbackAddedItems(items);
            throw;
        }
        return result;
    }
References System.Data.ProviderBase.SchemaMapping._chapterMap, System.Data.ProviderBase.SchemaMapping._dataReader, System.Data.ProviderBase.SchemaMapping._dataSet, System.Data.ProviderBase.SchemaMapping._dataTable, System.Data.ProviderBase.SchemaMapping._fieldNames, System.Data.ProviderBase.SchemaMapping._indexMap, System.Data.ProviderBase.SchemaMapping._loadOption, System.Data.ProviderBase.SchemaMapping._mappedMode, System.Data.ProviderBase.SchemaMapping._schemaTable, System.Data.ProviderBase.SchemaMapping._tableMapping, System.Data.ProviderBase.SchemaMapping._xmlMap, System.Data.DataTableCollection.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.ProviderBase.SchemaMapping.AddAdditionalProperties(), System.Data.ProviderBase.SchemaMapping.AddItemToAllowRollback(), System.Data.ProviderBase.SchemaMapping.AddRelation(), System.array, System.Data.DataTable.Columns, System.Data.DataTable.Constraints, System.Data.DataRowCollection.Count, System.Data.InternalDataCollectionBase.Count, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.ProviderBase.SchemaMapping.CreateIndexMap(), System.Data.DataTable.DataSet, System.Xml.Dictionary, System.Data.Common.ADP.FillChapterAutoIncrement(), System.Data.Common.DataTableMapping.GetDataColumn(), System.Data.ProviderBase.DataReaderContainer.GetFieldType(), System.Data.Common.DbSchemaRow.GetSortedSchemaRows(), System.Data.DataColumn.IsAutoIncrementType(), System.Data.Common.ADP.IsCatchableOrSecurityExceptionType(), System.Collections.Generic.Dictionary< TKey, TValue >.IsReadOnly, System.Data.Common.ADP.MissingDataReaderFieldType(), System.Data.ProviderBase.SchemaMapping.ResizeColumnArray(), System.Data.ProviderBase.DataReaderContainer.ReturnProviderSpecificTypes, System.Data.ProviderBase.SchemaMapping.RollbackAddedItems(), System.Data.DataTable.Rows, System.Data.ProviderBase.SchemaMapping.SetupMapping(), System.Data.Common.DataTableMapping.SourceTable, System.Data.DataTable.TableName, System.Data.DataSet.Tables, System.text, and System.type.
Referenced by System.Data.ProviderBase.SchemaMapping.SchemaMapping().