Terraria: WoodHouseBuilder.RainbowifyOnTenthAnniversaryWorlds
RainbowifyOnTenthAnniversaryWorlds()
void WoodHouseBuilder.RainbowifyOnTenthAnniversaryWorlds () inline private
     {
         if (!Main.tenthAnniversaryWorld || (base.TileType == 160 && WorldGen.genRand.Next(2) == 0))
         {
             return;
         }
         foreach (Rectangle room in base.Rooms)
         {
             WorldUtils.Gen(new Point(room.X, room.Y), new Shapes.Rectangle(room.Width, room.Height), new Actions.SetTileAndWallRainbowPaint());
         }
     }
References WorldUtils.Gen(), WorldGen.genRand, UnifiedRandom.Next(), and Main.tenthAnniversaryWorld.
Referenced by Place().