Terraria: System.Xml.UniqueId.TryGetGuid
TryGetGuid() [1/2]
unsafe bool System.Xml.UniqueId.TryGetGuid (byte[] buffer, int offset) inline
Definition at line 319 of file UniqueId.cs.
    {
        if (!IsGuid)
        {
            return false;
        }
        if (buffer == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("buffer"));
        }
        if (offset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative));
        }
        if (offset > buffer.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.Format(System.SR.OffsetExceedsBufferSize, buffer.Length)));
        }
        if (16 > buffer.Length - offset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("buffer", System.SR.Format(System.SR.XmlArrayTooSmallOutput, 16)));
        }
        fixed (byte* ptr = &buffer[offset])
        {
            UnsafeSetInt64(_idLow, ptr);
            UnsafeSetInt64(_idHigh, ptr + 8);
        }
        return true;
    }
References System.Xml.UniqueId._idHigh, System.Xml.UniqueId._idLow, System.buffer, System.Xml.Dictionary, System.SR.Format(), System.Xml.UniqueId.IsGuid, System.offset, System.SR.OffsetExceedsBufferSize, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.UniqueId.UnsafeSetInt64(), System.SR.ValueMustBeNonNegative, and System.SR.XmlArrayTooSmallOutput.