Terraria: System.Xml.UniqueId.ToCharArray
ToCharArray()
int System.Xml.UniqueId.ToCharArray (char[] chars, int offset) inline
Definition at line 239 of file UniqueId.cs.
    {
        int charArrayLength = CharArrayLength;
        if (chars == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("chars"));
        }
        if (offset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative));
        }
        if (offset > chars.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.Format(System.SR.OffsetExceedsBufferSize, chars.Length)));
        }
        if (charArrayLength > chars.Length - offset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("chars", System.SR.Format(System.SR.XmlArrayTooSmallOutput, charArrayLength)));
        }
        ToSpan(chars.AsSpan(offset, charArrayLength));
        return charArrayLength;
    }
References System.Xml.UniqueId.CharArrayLength, System.chars, System.Xml.Dictionary, System.SR.Format(), System.offset, System.SR.OffsetExceedsBufferSize, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.UniqueId.ToSpan(), System.SR.ValueMustBeNonNegative, and System.SR.XmlArrayTooSmallOutput.