Terraria: System.Xml.UniqueId.UnsafeParse
UnsafeParse()
unsafe void System.Xml.UniqueId.UnsafeParse (char * chars, int charCount) inline private
Definition at line 170 of file UniqueId.cs.
    {
        if (charCount != 45 || *chars != 'u' || chars[1] != 'r' || chars[2] != 'n' || chars[3] != ':' || chars[4] != 'u' || chars[5] != 'u' || chars[6] != 'i' || chars[7] != 'd' || chars[8] != ':' || chars[17] != '-' || chars[22] != '-' || chars[27] != '-' || chars[32] != '-')
        {
            return;
        }
        byte* ptr = stackalloc byte[16];
        int num = 0;
        int num2 = 0;
        fixed (short* ptr2 = &s_char2val[0])
        {
            short* char2val = ptr2;
            num = UnsafeDecode(char2val, chars[15], chars[16]);
            *ptr = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[13], chars[14]);
            ptr[1] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[11], chars[12]);
            ptr[2] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[9], chars[10]);
            ptr[3] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[20], chars[21]);
            ptr[4] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[18], chars[19]);
            ptr[5] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[25], chars[26]);
            ptr[6] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[23], chars[24]);
            ptr[7] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[28], chars[29]);
            ptr[8] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[30], chars[31]);
            ptr[9] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[33], chars[34]);
            ptr[10] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[35], chars[36]);
            ptr[11] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[37], chars[38]);
            ptr[12] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[39], chars[40]);
            ptr[13] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[41], chars[42]);
            ptr[14] = (byte)num;
            num2 |= num;
            num = UnsafeDecode(char2val, chars[43], chars[44]);
            ptr[15] = (byte)num;
            num2 |= num;
            if (num2 >= 256)
            {
                return;
            }
            _idLow = UnsafeGetInt64(ptr);
            _idHigh = UnsafeGetInt64(ptr + 8);
        }
    }
References System.Xml.UniqueId._idHigh, System.Xml.UniqueId._idLow, System.charCount, System.chars, System.Xml.Dictionary, System.Xml.UniqueId.s_char2val, System.Xml.UniqueId.UnsafeDecode(), and System.Xml.UniqueId.UnsafeGetInt64().
Referenced by System.Xml.UniqueId.UniqueId(), and System.Xml.UniqueId.UniqueId().