Terraria: System.Xml.UniqueId.UniqueId
UniqueId() [6/6]
unsafe System.Xml.UniqueId.UniqueId (char[] chars, int offset, int count) inline
Definition at line 119 of file UniqueId.cs.
    {
        if (chars == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("chars"));
        }
        if (offset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative));
        }
        if (offset > chars.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.Format(System.SR.OffsetExceedsBufferSize, chars.Length)));
        }
        if (count < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative));
        }
        if (count > chars.Length - offset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, chars.Length - offset)));
        }
        if (count == 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new FormatException(System.SR.XmlInvalidUniqueId));
        }
        fixed (char* chars2 = &chars[offset])
        {
            UnsafeParse(chars2, count);
        }
        if (!IsGuid)
        {
            _s = new string(chars, offset, count);
        }
    }
References System.Xml.UniqueId._s, System.chars, System.count, System.Xml.Dictionary, System.SR.Format(), System.Xml.UniqueId.IsGuid, System.offset, System.SR.OffsetExceedsBufferSize, System.SR.SizeExceedsRemainingBufferSpace, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.UniqueId.UnsafeParse(), System.SR.ValueMustBeNonNegative, and System.SR.XmlInvalidUniqueId.