Terraria: System.Threading.ExecutionContext.RestoreFlow
RestoreFlow()
static void System.Threading.ExecutionContext.RestoreFlow () inline static
Definition at line 91 of file ExecutionContext.cs.
    {
        Thread currentThread = Thread.CurrentThread;
        ExecutionContext executionContext = currentThread._executionContext;
        if (executionContext == null || !executionContext.m_isFlowSuppressed)
        {
            throw new InvalidOperationException(SR.InvalidOperation_CannotRestoreUnsupressedFlow);
        }
        currentThread._executionContext = executionContext.ShallowClone(isFlowSuppressed: false);
    }
References System.Threading.Thread._executionContext, System.Threading.Thread.CurrentThread, System.Runtime.Serialization.Dictionary, and System.SR.InvalidOperation_CannotRestoreUnsupressedFlow.
Referenced by System.Net.Http.HttpConnectionPoolManager.HttpConnectionPoolManager(), System.Net.Http.HttpConnectionPool.HandleAltSvc(), and System.Threading.AsyncFlowControl.Undo().