Terraria: System.Threading.ExecutionContext.Run
Run()
static void System.Threading.ExecutionContext.Run (ExecutionContext executionContext, ContextCallback callback, object? state) inline static
Definition at line 107 of file ExecutionContext.cs.
    {
        if (executionContext == null)
        {
            ThrowNullContext();
        }
        RunInternal(executionContext, callback, state);
    }
References System.Runtime.Serialization.Dictionary, System.Threading.ExecutionContext.RunInternal(), System.state, and System.Threading.ExecutionContext.ThrowNullContext().
Referenced by System.Net.NetworkInformation.NetworkChange.AddressChangeListener.AddressChangedCallback(), System.Net.NetworkInformation.NetworkChange.AvailabilityChangeListener.ChangedAddress(), System.Net.ContextAwareResult.Complete(), System.Threading.Tasks.Parallel.ForEachAsyncState< TSource >.Execute(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(), System.Threading.Barrier.FinishPhase(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(), System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(), System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(), System.Threading.Channels.AsyncOperation< TResult >.SetCompletionAndInvokeContinuation(), and System.Net.Mail.SmtpConnection.SetContextAndTryAuthenticate().