Terraria: System.Threading.ExecutionContext.RestoreInternal
RestoreInternal()
static void System.Threading.ExecutionContext.RestoreInternal (ExecutionContext executionContext) inline static package
Definition at line 164 of file ExecutionContext.cs.
    {
        Thread currentThread = Thread.CurrentThread;
        ExecutionContext executionContext2 = currentThread._executionContext;
        if (executionContext2 != null && executionContext2.m_isDefault)
        {
            executionContext2 = null;
        }
        if (executionContext != null && executionContext.m_isDefault)
        {
            executionContext = null;
        }
        if (executionContext2 != executionContext)
        {
            RestoreChangedContextToThread(currentThread, executionContext, executionContext2);
        }
    }
References System.Threading.Thread._executionContext, System.Threading.Thread.CurrentThread, System.Runtime.Serialization.Dictionary, and System.Threading.ExecutionContext.RestoreChangedContextToThread().
Referenced by System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.InvokeContinuationWithContext(), and System.Threading.ExecutionContext.Restore().