Terraria: System.Threading.ExecutionContext.SuppressFlow
SuppressFlow()
static AsyncFlowControl System.Threading.ExecutionContext.SuppressFlow () inline static
Definition at line 76 of file ExecutionContext.cs.
    {
        Thread currentThread = Thread.CurrentThread;
        ExecutionContext executionContext = currentThread._executionContext ?? Default;
        if (executionContext.m_isFlowSuppressed)
        {
            throw new InvalidOperationException(SR.InvalidOperation_CannotSupressFlowMultipleTimes);
        }
        executionContext = executionContext.ShallowClone(isFlowSuppressed: true);
        AsyncFlowControl result = default(AsyncFlowControl);
        currentThread._executionContext = executionContext;
        result.Initialize(currentThread);
        return result;
    }
References System.Threading.Thread.CurrentThread, System.Threading.ExecutionContext.Default, System.Runtime.Serialization.Dictionary, System.Threading.AsyncFlowControl.Initialize(), and System.SR.InvalidOperation_CannotSupressFlowMultipleTimes.
Referenced by System.Net.Http.HttpConnectionPoolManager.HttpConnectionPoolManager(), System.Net.Http.HttpConnectionPool.HandleAltSvc(), and System.Net.Http.HttpConnectionPoolManager.StartMonitoringNetworkChanges().