Terraria: System.Threading.ExecutionContext.Capture
Capture()
static ? ExecutionContext System.Threading.ExecutionContext.Capture () inline static
Definition at line 44 of file ExecutionContext.cs.
    {
        ExecutionContext executionContext = Thread.CurrentThread._executionContext;
        if (executionContext == null)
        {
            executionContext = Default;
        }
        else if (executionContext.m_isFlowSuppressed)
        {
            executionContext = null;
        }
        return executionContext;
    }
References System.Threading.Thread.CurrentThread, System.Threading.ExecutionContext.Default, and System.Runtime.Serialization.Dictionary.
Referenced by System.Threading._ThreadPoolWaitOrTimerCallback._ThreadPoolWaitOrTimerCallback(), System.Threading.Tasks.AwaitTaskContinuation.AwaitTaskContinuation(), System.Threading.Barrier.Barrier(), System.Threading.Tasks.Parallel.ForEachAsyncState< TSource >.ForEachAsyncState(), System.IO.Stream.ReadWriteTask.ReadWriteTask(), System.Threading.Tasks.Task< TResult >.Task(), System.Threading.TimerQueueTimer.TimerQueueTimer(), System.Net.ContextAwareResult.CaptureOrComplete(), System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.GetStateMachineBox< TStateMachine >(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.GetStateMachineBox< TStateMachine >(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(), System.Threading.Channels.AsyncOperation< TResult >.OnCompleted(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.OnCompleted(), System.Threading.OverlappedData.Pack(), Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.QueueToThreadPool(), System.Threading.ThreadPool.QueueUserWorkItem(), System.Threading.ThreadPool.QueueUserWorkItem< TState >(), System.Threading.CancellationToken.Register(), System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(), System.Threading.Thread.Start(), System.Net.NetworkInformation.NetworkChange.AvailabilityChangeListener.Start(), System.Threading.Thread.Start(), System.Net.NetworkInformation.NetworkChange.AddressChangeListener.StartHelper(), and System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon().