Terraria: System.Threading.ExecutionContext.RunInternal
RunInternal()
static void System.Threading.ExecutionContext.RunInternal (ExecutionContext executionContext, ContextCallback callback, object state) inline static package
Definition at line 116 of file ExecutionContext.cs.
    {
        Thread currentThread = Thread.CurrentThread;
        ExecutionContext executionContext2 = currentThread._executionContext;
        if (executionContext2 != null && executionContext2.m_isDefault)
        {
            executionContext2 = null;
        }
        ExecutionContext executionContext3 = executionContext2;
        SynchronizationContext synchronizationContext = currentThread._synchronizationContext;
        if (executionContext != null && executionContext.m_isDefault)
        {
            executionContext = null;
        }
        if (executionContext3 != executionContext)
        {
            RestoreChangedContextToThread(currentThread, executionContext, executionContext3);
        }
        ExceptionDispatchInfo exceptionDispatchInfo = null;
        try
        {
            callback(state);
        }
        catch (Exception source)
        {
            exceptionDispatchInfo = ExceptionDispatchInfo.Capture(source);
        }
        if (currentThread._synchronizationContext != synchronizationContext)
        {
            currentThread._synchronizationContext = synchronizationContext;
        }
        ExecutionContext executionContext4 = currentThread._executionContext;
        if (executionContext4 != executionContext3)
        {
            RestoreChangedContextToThread(currentThread, executionContext3, executionContext4);
        }
        exceptionDispatchInfo?.Throw();
    }
References System.Threading.Thread._executionContext, System.Threading.Thread._synchronizationContext, System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.Threading.Thread.CurrentThread, System.Runtime.Serialization.Dictionary, System.Threading.ExecutionContext.RestoreChangedContextToThread(), System.source, and System.state.
Referenced by System.Threading.TimerQueueTimer.CallCallback(), System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback(), System.Threading.Tasks.Task< TResult >.ExecuteWithThreadLocal(), System.IO.Stream.ReadWriteTask.Invoke(), System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.StateMachineBox< TStateMachine >.MoveNext(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.MoveNext(), System.Threading._IOCompletionCallback.PerformIOCompletionCallback(), System.Threading.Thread.StartHelper.Run(), System.Threading.ExecutionContext.Run(), and System.Threading.Tasks.AwaitTaskContinuation.RunCallback().