Terraria: System.Threading.ExecutionContext.OnValuesChanged
OnValuesChanged()
static void System.Threading.ExecutionContext.OnValuesChanged (ExecutionContext previousExecutionCtx, ExecutionContext nextExecutionCtx) inline static package
Definition at line 239 of file ExecutionContext.cs.
    {
        IAsyncLocal[] array = previousExecutionCtx?.m_localChangeNotifications;
        IAsyncLocal[] array2 = nextExecutionCtx?.m_localChangeNotifications;
        try
        {
            if (array != null && array2 != null)
            {
                IAsyncLocal[] array3 = array;
                foreach (IAsyncLocal asyncLocal in array3)
                {
                    previousExecutionCtx.m_localValues.TryGetValue(asyncLocal, out var value);
                    nextExecutionCtx.m_localValues.TryGetValue(asyncLocal, out var value2);
                    if (value != value2)
                    {
                        asyncLocal.OnValueChanged(value, value2, contextChanged: true);
                    }
                }
                if (array2 == array)
                {
                    return;
                }
                IAsyncLocal[] array4 = array2;
                foreach (IAsyncLocal asyncLocal2 in array4)
                {
                    if (!previousExecutionCtx.m_localValues.TryGetValue(asyncLocal2, out var value3))
                    {
                        nextExecutionCtx.m_localValues.TryGetValue(asyncLocal2, out var value4);
                        if (value3 != value4)
{
                            asyncLocal2.OnValueChanged(value3, value4, contextChanged: true);
                        }
                    }
                }
                return;
            }
            if (array != null)
            {
                IAsyncLocal[] array5 = array;
                foreach (IAsyncLocal asyncLocal3 in array5)
                {
                    previousExecutionCtx.m_localValues.TryGetValue(asyncLocal3, out var value5);
                    if (value5 != null)
                    {
                        asyncLocal3.OnValueChanged(value5, null, contextChanged: true);
                    }
                }
                return;
            }
            IAsyncLocal[] array6 = array2;
            foreach (IAsyncLocal asyncLocal4 in array6)
            {
                nextExecutionCtx.m_localValues.TryGetValue(asyncLocal4, out var value6);
                if (value6 != null)
                {
                    asyncLocal4.OnValueChanged(null, value6, contextChanged: true);
                }
            }
        }
        catch (Exception exception)
        {
            Environment.FailFast(SR.ExecutionContext_ExceptionInAsyncLocalNotification, exception);
        }
    }
References System.array, System.Runtime.Serialization.Dictionary, System.exception, System.SR.ExecutionContext_ExceptionInAsyncLocalNotification, System.Environment.FailFast(), System.Threading.IAsyncLocal.OnValueChanged(), and System.value.
Referenced by System.Threading.ExecutionContext.ResetThreadPoolThread(), System.Threading.ExecutionContext.RestoreChangedContextToThread(), and System.Threading.ExecutionContext.RunForThreadPoolUnsafe< TState >().