Terraria: ColorSlidersSet.SetHSL
SetHSL() [1/2]
void ColorSlidersSet.SetHSL (Color color) inline
     {
         Vector3 vector = Main.rgbToHsl(color);
         Hue = vector.X;
         Saturation = vector.Y;
         Luminance = vector.Z;
     }
References Hue, Luminance, Main.rgbToHsl(), and Saturation.
Referenced by Main.DrawMenu(), and Main.LoadSettings().