Terraria: System.Threading.ExecutionContext.SetLocalValue
SetLocalValue()
static void System.Threading.ExecutionContext.SetLocalValue (IAsyncLocal local, object newValue, bool needChangeNotifications) inline static package
Definition at line 322 of file ExecutionContext.cs.
    {
        ExecutionContext executionContext = Thread.CurrentThread._executionContext;
        object value = null;
        bool flag = false;
        if (executionContext != null)
        {
            flag = executionContext.m_localValues.TryGetValue(local, out value);
        }
        if (value == newValue)
        {
            return;
        }
        IAsyncLocal[] array = null;
        bool flag2 = false;
        IAsyncLocalValueMap asyncLocalValueMap;
        if (executionContext != null)
        {
            flag2 = executionContext.m_isFlowSuppressed;
            asyncLocalValueMap = executionContext.m_localValues.Set(local, newValue, !needChangeNotifications);
            array = executionContext.m_localChangeNotifications;
        }
        else
        {
            asyncLocalValueMap = AsyncLocalValueMap.Create(local, newValue, !needChangeNotifications);
        }
        if (needChangeNotifications && !flag)
        {
            if (array == null)
            {
                array = new IAsyncLocal[1] { local };
            }
            else
            {
                int num = array.Length;
                Array.Resize(ref array, num + 1);
                array[num] = local;
            }
        }
        Thread.CurrentThread._executionContext = ((!flag2 && AsyncLocalValueMap.IsEmpty(asyncLocalValueMap)) ? null : new ExecutionContext(asyncLocalValueMap, array, flag2));
        if (needChangeNotifications)
        {
            local.OnValueChanged(value, newValue, contextChanged: false);
        }
    }
References System.Threading.ExecutionContext.ExecutionContext(), System.array, System.Threading.AsyncLocalValueMap.Create(), System.Threading.Thread.CurrentThread, System.Runtime.Serialization.Dictionary, System.Threading.AsyncLocalValueMap.IsEmpty(), System.Threading.IAsyncLocalValueMap.Set(), and System.value.