Terraria: System.Reflection.Metadata.PEReaderExtensions.GetMethodBody
GetMethodBody()
static MethodBodyBlock System.Reflection.Metadata.PEReaderExtensions.GetMethodBody (this PEReader peReader, int relativeVirtualAddress) inline static
Definition at line 9 of file PEReaderExtensions.cs.
    {
        if (peReader == null)
        {
            throw new ArgumentNullException("peReader");
        }
        PEMemoryBlock sectionData = peReader.GetSectionData(relativeVirtualAddress);
        if (sectionData.Length == 0)
        {
            throw new BadImageFormatException(System.SR.Format(System.SR.InvalidMethodRva, relativeVirtualAddress));
        }
        return MethodBodyBlock.Create(sectionData.GetReader());
    }
References System.Reflection.Metadata.MethodBodyBlock.Create(), System.SR.Format(), System.Reflection.PortableExecutable.PEMemoryBlock.GetReader(), System.Reflection.PortableExecutable.PEReader.GetSectionData(), System.SR.InvalidMethodRva, and System.Reflection.PortableExecutable.PEMemoryBlock.Length.