Terraria: UITextPanel.DrawText
DrawText()
void UITextPanel< T >.DrawText (SpriteBatch spriteBatch) inline protected
     {
         CalculatedStyle innerDimensions = GetInnerDimensions();
         Vector2 pos = innerDimensions.Position();
         if (_isLarge)
         {
             pos.Y -= 10f * _textScale * _textScale;
         }
         else
         {
             pos.Y -= 2f * _textScale;
         }
         pos.X += (innerDimensions.Width - _textSize.X) * TextHAlign;
         string text = Text;
         if (HideContents)
         {
             if (_asterisks == null || _asterisks.Length != text.Length)
             {
                 _asterisks = new string('*', text.Length);
             }
             text = _asterisks;
         }
         if (_isLarge)
         {
             Utils.DrawBorderStringBig(spriteBatch, text, pos, _color, _textScale);
         }
         else
         {
             Utils.DrawBorderString(spriteBatch, text, pos, _color, _textScale);
         }
     }
References UITextPanel< T >._asterisks, UITextPanel< T >._color, UITextPanel< T >._isLarge, UITextPanel< T >._textScale, UITextPanel< T >._textSize, Utils.DrawBorderString(), Utils.DrawBorderStringBig(), UIElement.GetInnerDimensions(), UITextPanel< T >.HideContents, CalculatedStyle.Position(), UITextPanel< T >.Text, UITextPanel< T >.TextHAlign, and CalculatedStyle.Width.
Referenced by UIResourcePackInfoButton< T >.DrawSelf(), UISelectableTextPanel< T >.DrawSelf(), and UITextPanel< T >.DrawSelf().