Terraria: System.Number.NumberToSingleFloatingPointBits
NumberToSingleFloatingPointBits()
static unsafe uint System.Number.NumberToSingleFloatingPointBits (ref NumberBuffer number, in FloatingPointInfo info) inline static private
Definition at line 3736 of file Number.cs.
    {
        uint digitsCount = (uint)number.DigitsCount;
        uint num = (uint)Math.Max(0, number.Scale);
        uint num2 = Math.Min(num, digitsCount);
        uint num3 = digitsCount - num2;
        uint num4 = (uint)Math.Abs(number.Scale - num2 - num3);
        byte* digitsPointer = number.GetDigitsPointer();
        if (digitsCount <= 7 && num4 <= 10)
        {
            float num5 = DigitsToUInt32(digitsPointer, (int)digitsCount);
            float num6 = s_Pow10SingleTable[num4];
            num5 = ((num3 == 0) ? (num5 * num6) : (num5 / num6));
            return BitConverter.SingleToUInt32Bits(num5);
        }
        if (digitsCount <= 15 && num4 <= 22)
        {
            double num7 = DigitsToUInt64(digitsPointer, (int)digitsCount);
            double num8 = s_Pow10DoubleTable[num4];
            num7 = ((num3 == 0) ? (num7 * num8) : (num7 / num8));
            return BitConverter.SingleToUInt32Bits((float)num7);
        }
        return (uint)NumberToFloatingPointBitsSlow(ref number, in info, num, num2, num3);
    }
References System.Math.Abs(), System.Number.DigitsToUInt32(), System.Number.DigitsToUInt64(), System.info, System.Math.Max(), System.Math.Min(), System.Number.NumberToFloatingPointBitsSlow(), System.Number.s_Pow10DoubleTable, System.Number.s_Pow10SingleTable, and System.BitConverter.SingleToUInt32Bits().
Referenced by System.Number.NumberToSingle().