Terraria: System.Number.TryParseInt64IntegerStyle
TryParseInt64IntegerStyle()
static ParsingStatus System.Number.TryParseInt64IntegerStyle (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out long result) inline static package
Definition at line 4492 of file Number.cs.
    {
        int i;
        int num;
        if (!value.IsEmpty)
        {
            i = 0;
            num = value[0];
            if ((styles & NumberStyles.AllowLeadingWhite) == 0 || !IsWhite(num))
            {
                goto IL_0048;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (IsWhite(num))
                {
                    continue;
                }
                goto IL_0048;
            }
        }
        goto IL_029f;
        IL_0292:
        long num2;
        int num3;
        result = num2 * num3;
        return ParsingStatus.OK;
        IL_02a8:
        result = 0L;
        return ParsingStatus.Overflow;
        IL_01a0:
        if (IsDigit(num))
        {
            goto IL_01ab;
        }
        goto IL_02b1;
        IL_028f:
        bool flag;
        if (!flag)
        {
            goto IL_0292;
        }
        goto IL_02a8;
        IL_0048:
        num3 = 1;
        if ((styles & NumberStyles.AllowLeadingSign) != 0)
        {
            if (info.HasInvariantNumberSigns)
            {
                if (num == 45)
                {
                    num3 = -1;
                    i++;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_029f;
                    }
                    num = value[i];
                }
                else if (num == 43)
                {
                    i++;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_029f;
                    }
                    num = value[i];
                }
            }
            else if (info.AllowHyphenDuringParsing && num == 45)
            {
                num3 = -1;
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    goto IL_029f;
                }
                num = value[i];
            }
            else
            {
                value = value.Slice(i);
                i = 0;
                string positiveSign = info.PositiveSign;
                string negativeSign = info.NegativeSign;
                if (!string.IsNullOrEmpty(positiveSign) && value.StartsWith(positiveSign))
                {
                    i += positiveSign.Length;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_029f;
                    }
                    num = value[i];
                }
                else if (!string.IsNullOrEmpty(negativeSign) && value.StartsWith(negativeSign))
                {
                    num3 = -1;
                    i += negativeSign.Length;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_029f;
                    }
                    num = value[i];
                }
            }
        }
        flag = false;
        num2 = 0L;
        if (IsDigit(num))
        {
            if (num != 48)
            {
                goto IL_01ab;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (num == 48)
                {
                    continue;
                }
                goto IL_01a0;
            }
            goto IL_0292;
        }
        goto IL_029f;
        IL_01ab:
        num2 = num - 48;
        i++;
        int num4 = 0;
        while (num4 < 17)
        {
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_0292;
            }
            num = value[i];
            if (IsDigit(num))
            {
                i++;
                num2 = 10 * num2 + num - 48;
                num4++;
                continue;
            }
            goto IL_02b1;
        }
        if ((uint)i >= (uint)value.Length)
        {
            goto IL_0292;
        }
        num = value[i];
        if (IsDigit(num))
        {
            i++;
            flag = num2 > 922337203685477580L;
            num2 = num2 * 10 + num - 48;
            flag = flag || (ulong)num2 > (ulong)(long.MaxValue + (long)(uint)(num3 >>> 31));
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_028f;
            }
            num = value[i];
            while (IsDigit(num))
            {
                flag = true;
                i++;
                if ((uint)i < (uint)value.Length)
                {
                    num = value[i];
                    continue;
                }
                goto IL_02a8;
            }
        }
        goto IL_02b1;
        IL_02b1:
        if (IsWhite(num))
        {
            if ((styles & NumberStyles.AllowTrailingWhite) == 0)
            {
                goto IL_029f;
            }
            for (i++; i < value.Length && IsWhite(value[i]); i++)
            {
            }
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_028f;
            }
        }
        if (TrailingZeros(value, i))
        {
            goto IL_028f;
        }
        goto IL_029f;
        IL_029f:
        result = 0L;
        return ParsingStatus.Failed;
    }
References System.info, System.Number.IsDigit(), System.Number.IsWhite(), System.L, System.Number.TrailingZeros(), and System.value.
Referenced by System.Int64.TryParse(), System.Int64.TryParse(), System.Number.TryParseInt64(), and System.Enum.TryParseInt64Enum().