Terraria: System.Number.NumberToDouble
NumberToDouble()
static double System.Number.NumberToDouble (ref NumberBuffer number) inline static package
Definition at line 5949 of file Number.cs.
    {
        double num;
        if (number.DigitsCount == 0 || number.Scale < -324)
        {
            num = 0.0;
        }
        else if (number.Scale > 309)
        {
            num = double.PositiveInfinity;
        }
        else
        {
            ulong value = NumberToDoubleFloatingPointBits(ref number, in FloatingPointInfo.Double);
            num = BitConverter.UInt64BitsToDouble(value);
        }
        if (!number.IsNegative)
        {
            return num;
        }
        return 0.0 - num;
    }
References System.Number.FloatingPointInfo.Double, System.Number.NumberToDoubleFloatingPointBits(), System.BitConverter.UInt64BitsToDouble(), and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), and System.Number.TryParseDouble().