Terraria: System.Number.UInt32ToDecStr
UInt32ToDecStr() [2/2]
static unsafe string System.Number.UInt32ToDecStr (uint value, int digits) inline static private
Definition at line 2404 of file Number.cs.
    {
        if (digits <= 1)
        {
            return UInt32ToDecStr(value);
        }
        int num = Math.Max(digits, FormattingHelpers.CountDigits(value));
        string text = string.FastAllocateString(num);
        fixed (char* ptr = text)
        {
            char* bufferEnd = ptr + num;
            bufferEnd = UInt32ToDecChars(bufferEnd, value, digits);
        }
        return text;
    }
References System.Buffers.Text.FormattingHelpers.CountDigits(), System.Math.Max(), System.text, System.Number.UInt32ToDecChars(), System.Number.UInt32ToDecStr(), and System.value.