Terraria: System.Number.FormatUInt64
FormatUInt64()
static string System.Number.FormatUInt64 (ulong value, string format, IFormatProvider provider) inline static
Definition at line 2145 of file Number.cs.
    {
        if (string.IsNullOrEmpty(format))
        {
            return UInt64ToDecStr(value, -1);
        }
        return FormatUInt64Slow(value, format, provider);
        unsafe static string FormatUInt64Slow(ulong value, string format, IFormatProvider provider)
        {
            ReadOnlySpan<char> format2 = format;
            int digits;
            char c = ParseFormatSpecifier(format2, out digits);
            char c2 = (char)(c & 0xFFDFu);
            if ((c2 == 'G') ? (digits < 1) : (c2 == 'D'))
            {
                return UInt64ToDecStr(value, digits);
            }
            if (c2 == 'X')
            {
                return Int64ToHexStr((long)value, GetHexBase(c), digits);
            }
            NumberFormatInfo instance = NumberFormatInfo.GetInstance(provider);
            byte* digits2 = stackalloc byte[21];
            NumberBuffer number = new NumberBuffer(NumberBufferKind.Integer, digits2, 21);
            UInt64ToNumber(value, ref number);
            char* pointer = stackalloc char[32];
            ValueStringBuilder sb = new ValueStringBuilder(new Span<char>(pointer, 32));
            if (c != 0)
            {
                NumberToString(ref sb, ref number, c, digits, instance);
            }
            else
            {
                NumberToStringFormat(ref sb, ref number, format2, instance);
            }
            return sb.ToString();
        }
    }
References System.format, System.Number.GetHexBase(), System.Globalization.NumberFormatInfo.GetInstance(), System.Number.Int64ToHexStr(), System.Number.NumberToString(), System.Number.NumberToStringFormat(), System.Number.ParseFormatSpecifier(), System.pointer, System.Text.ValueStringBuilder.ToString(), System.Number.UInt64ToDecStr(), System.Number.UInt64ToNumber(), and System.value.
Referenced by System.UInt64.ToString(), and System.UInt64.ToString().