Terraria: System.Number.ThrowOverflowOrFormatException
ThrowOverflowOrFormatException()
static void System.Number.ThrowOverflowOrFormatException (ParsingStatus status, TypeCode type = TypeCode::Empty) inline static package
Definition at line 5918 of file Number.cs.
    {
        throw GetException(status, type);
    }
References System.Number.GetException(), and System.type.
Referenced by System.Byte.Parse(), System.Int16.Parse(), System.SByte.Parse(), System.UInt16.Parse(), System.Number.ParseDecimal(), System.Number.ParseDouble(), System.Number.ParseHalf(), System.Number.ParseInt32(), System.Number.ParseInt64(), System.Number.ParseSingle(), System.Number.ParseUInt32(), and System.Number.ParseUInt64().