Terraria: System.Number.NegativeInt32ToDecStr
NegativeInt32ToDecStr()
static unsafe string System.Number.NegativeInt32ToDecStr (int value, int digits, string sNegative) inline static private
Definition at line 2255 of file Number.cs.
    {
        if (digits < 1)
        {
            digits = 1;
        }
        int num = Math.Max(digits, FormattingHelpers.CountDigits((uint)(-value))) + sNegative.Length;
        string text = string.FastAllocateString(num);
        fixed (char* ptr = text)
        {
            char* ptr2 = UInt32ToDecChars(ptr + num, (uint)(-value), digits);
            for (int num2 = sNegative.Length - 1; num2 >= 0; num2--)
            {
                *(--ptr2) = sNegative[num2];
            }
        }
        return text;
    }
References System.Buffers.Text.FormattingHelpers.CountDigits(), System.Math.Max(), System.text, System.Number.UInt32ToDecChars(), and System.value.
Referenced by System.Number.FormatInt32(), and System.Number.Int32ToDecStr().