Terraria: System.Number.TryFormatUInt64
TryFormatUInt64()
static bool System.Number.TryFormatUInt64 (ulong value, ReadOnlySpan< char > format, IFormatProvider provider, Span< char > destination, out int charsWritten) inline static
Definition at line 2184 of file Number.cs.
    {
        if (format.Length == 0)
        {
            return TryUInt64ToDecStr(value, -1, destination, out charsWritten);
        }
        return TryFormatUInt64Slow(value, format, provider, destination, out charsWritten);
        unsafe static bool TryFormatUInt64Slow(ulong value, ReadOnlySpan<char> format, IFormatProvider provider, Span<char> destination, out int charsWritten)
        {
            int digits;
            char c = ParseFormatSpecifier(format, out digits);
            char c2 = (char)(c & 0xFFDFu);
            if ((c2 == 'G') ? (digits < 1) : (c2 == 'D'))
            {
                return TryUInt64ToDecStr(value, digits, destination, out charsWritten);
            }
            if (c2 == 'X')
            {
                return TryInt64ToHexStr((long)value, GetHexBase(c), digits, destination, out charsWritten);
            }
            NumberFormatInfo instance = NumberFormatInfo.GetInstance(provider);
            byte* digits2 = stackalloc byte[21];
            NumberBuffer number = new NumberBuffer(NumberBufferKind.Integer, digits2, 21);
            UInt64ToNumber(value, ref number);
            char* pointer = stackalloc char[32];
            ValueStringBuilder sb = new ValueStringBuilder(new Span<char>(pointer, 32));
            if (c != 0)
            {
                NumberToString(ref sb, ref number, c, digits, instance);
            }
            else
            {
                NumberToStringFormat(ref sb, ref number, format, instance);
            }
            return sb.TryCopyTo(destination, out charsWritten);
        }
    }
References System.destination, System.format, System.Number.GetHexBase(), System.Globalization.NumberFormatInfo.GetInstance(), System.Number.NumberToString(), System.Number.NumberToStringFormat(), System.Number.ParseFormatSpecifier(), System.pointer, System.Text.ValueStringBuilder.TryCopyTo(), System.Number.TryInt64ToHexStr(), System.Number.TryUInt64ToDecStr(), System.Number.UInt64ToNumber(), and System.value.
Referenced by System.UInt64.TryFormat().