Terraria: System.Number.AssembleFloatingPointBits
AssembleFloatingPointBits()
static ulong System.Number.AssembleFloatingPointBits (in FloatingPointInfo info, ulong initialMantissa, int initialExponent, bool hasZeroTail) inline static private
Definition at line 3577 of file Number.cs.
    {
        uint num = BigInteger.CountSignificantBits(initialMantissa);
        int num2 = (int)(info.NormalMantissaBits - num);
        int num3 = initialExponent - num2;
        ulong num4 = initialMantissa;
        int num5 = num3;
        if (num3 > info.MaxBinaryExponent)
        {
            return info.InfinityBits;
        }
        if (num3 < info.MinBinaryExponent)
        {
            int num6 = num2 + num3 + info.ExponentBias - 1;
            num5 = -info.ExponentBias;
            if (num6 < 0)
            {
                num4 = RightShiftWithRounding(num4, -num6, hasZeroTail);
                if (num4 == 0L)
                {
                    return info.ZeroBits;
                }
                if (num4 > info.DenormalMantissaMask)
                {
                    num5 = initialExponent - (num6 + 1) - num2;
                }
            }
            else
            {
                num4 <<= num6;
            }
        }
        else if (num2 < 0)
        {
            num4 = RightShiftWithRounding(num4, -num2, hasZeroTail);
            if (num4 > info.NormalMantissaMask)
            {
                num4 >>= 1;
                num5++;
                if (num5 > info.MaxBinaryExponent)
                {
                    return info.InfinityBits;
                }
            }
        }
        else if (num2 > 0)
        {
            num4 <<= num2;
        }
        num4 &= info.DenormalMantissaMask;
        ulong num7 = (ulong)((long)(num5 + info.ExponentBias) << (int)info.DenormalMantissaBits);
        return num7 | num4;
    }
References System.Number.BigInteger.CountSignificantBits(), System.info, System.L, and System.Number.RightShiftWithRounding().
Referenced by System.Number.ConvertBigIntegerToFloatingPointBits(), and System.Number.NumberToFloatingPointBitsSlow().