Terraria: System.Number.IsWhite
IsWhite()
static bool System.Number.IsWhite (int ch) inline static private
Definition at line 5903 of file Number.cs.
    {
        if (ch != 32 && (uint)(ch - 9) > 4u)
        {
            return false;
        }
        return true;
    }
References System.ch.
Referenced by System.Number.TryParseInt32IntegerStyle(), System.Number.TryParseInt64IntegerStyle(), System.Number.TryParseNumber(), System.Number.TryParseUInt32HexNumberStyle(), System.Number.TryParseUInt32IntegerStyle(), System.Number.TryParseUInt64HexNumberStyle(), and System.Number.TryParseUInt64IntegerStyle().