Terraria: System.Number.TryParseSingle
TryParseSingle()
static unsafe bool System.Number.TryParseSingle (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out float result) inline static package
Definition at line 5775 of file Number.cs.
    {
        byte* digits = stackalloc byte[114];
        NumberBuffer number = new NumberBuffer(NumberBufferKind.FloatingPoint, digits, 114);
        if (!TryStringToNumber(value, styles, ref number, info))
        {
            ReadOnlySpan<char> span = value.Trim();
            if (span.EqualsOrdinalIgnoreCase(info.PositiveInfinitySymbol))
            {
                result = float.PositiveInfinity;
            }
            else if (span.EqualsOrdinalIgnoreCase(info.NegativeInfinitySymbol))
            {
                result = float.NegativeInfinity;
            }
            else if (span.EqualsOrdinalIgnoreCase(info.NaNSymbol))
            {
                result = float.NaN;
            }
            else if (span.StartsWith(info.PositiveSign, StringComparison.OrdinalIgnoreCase))
            {
                span = span.Slice(info.PositiveSign.Length);
                if (!info.PositiveInfinitySymbol.StartsWith(info.PositiveSign, StringComparison.OrdinalIgnoreCase) && span.EqualsOrdinalIgnoreCase(info.PositiveInfinitySymbol))
                {
                    result = float.PositiveInfinity;
                }
                else
                {
                    if (info.NaNSymbol.StartsWith(info.PositiveSign, StringComparison.OrdinalIgnoreCase) || !span.EqualsOrdinalIgnoreCase(info.NaNSymbol))
                    {
                        result = 0f;
                        return false;
                    }
                    result = float.NaN;
                }
            }
            else if (span.StartsWith(info.NegativeSign, StringComparison.OrdinalIgnoreCase) && !info.NaNSymbol.StartsWith(info.NegativeSign, StringComparison.OrdinalIgnoreCase) && span.Slice(info.NegativeSign.Length).EqualsOrdinalIgnoreCase(info.NaNSymbol))
            {
                result = float.NaN;
            }
            else
            {
                if (!info.AllowHyphenDuringParsing || !SpanStartsWith(span, '-') || info.NaNSymbol.StartsWith(info.NegativeSign, StringComparison.OrdinalIgnoreCase) || info.NaNSymbol.StartsWith('-') || !span.Slice(1).EqualsOrdinalIgnoreCase(info.NaNSymbol))
                {
                    result = 0f;
                    return false;
                }
                result = float.NaN;
            }
        }
        else
        {
            result = NumberToSingle(ref number);
        }
        return true;
    }
References System.info, System.Number.NumberToSingle(), System.ReadOnlySpan< T >.Slice(), System.Number.SpanStartsWith(), System.Number.TryStringToNumber(), and System.value.
Referenced by System.Number.ParseSingle(), and System.Single.TryParse().