Terraria: System.Number.TryParseUInt64IntegerStyle
TryParseUInt64IntegerStyle()
static ParsingStatus System.Number.TryParseUInt64IntegerStyle (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out ulong result) inline static package
Definition at line 5148 of file Number.cs.
    {
        int i;
        int num;
        if (!value.IsEmpty)
        {
            i = 0;
            num = value[0];
            if ((styles & NumberStyles.AllowLeadingWhite) == 0 || !IsWhite(num))
            {
                goto IL_0048;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (IsWhite(num))
                {
                    continue;
                }
                goto IL_0048;
            }
        }
        goto IL_0295;
        IL_01a8:
        long num2 = num - 48;
        i++;
        int num3 = 0;
        while (num3 < 18)
        {
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_0289;
            }
            num = value[i];
            if (IsDigit(num))
            {
                i++;
                num2 = 10 * num2 + num - 48;
                num3++;
                continue;
            }
            goto IL_02a9;
        }
        if ((uint)i >= (uint)value.Length)
        {
            goto IL_0289;
        }
        num = value[i];
        bool flag;
        if (IsDigit(num))
        {
            i++;
            flag = flag || (ulong)num2 > 1844674407370955161uL || (num2 == 1844674407370955161L && num > 53);
            num2 = num2 * 10 + num - 48;
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_0289;
            }
            num = value[i];
            while (IsDigit(num))
            {
                flag = true;
                i++;
                if ((uint)i < (uint)value.Length)
                {
                    num = value[i];
                    continue;
                }
                goto IL_029e;
            }
        }
        goto IL_02a9;
        IL_028c:
        result = (ulong)num2;
        return ParsingStatus.OK;
        IL_019d:
        if (IsDigit(num))
        {
            goto IL_01a8;
        }
        flag = false;
        goto IL_02a9;
        IL_0289:
        if (!flag)
        {
            goto IL_028c;
        }
        goto IL_029e;
        IL_0048:
        flag = false;
        if ((styles & NumberStyles.AllowLeadingSign) != 0)
        {
            if (info.HasInvariantNumberSigns)
            {
                if (num == 43)
                {
                    i++;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0295;
                    }
                    num = value[i];
                }
                else if (num == 45)
                {
                    flag = true;
                    i++;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0295;
                    }
                    num = value[i];
                }
            }
            else if (info.AllowHyphenDuringParsing && num == 45)
            {
                flag = true;
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    goto IL_0295;
                }
                num = value[i];
            }
            else
            {
                value = value.Slice(i);
                i = 0;
                string positiveSign = info.PositiveSign;
                string negativeSign = info.NegativeSign;
                if (!string.IsNullOrEmpty(positiveSign) && value.StartsWith(positiveSign))
                {
                    i += positiveSign.Length;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0295;
                    }
                    num = value[i];
                }
                else if (!string.IsNullOrEmpty(negativeSign) && value.StartsWith(negativeSign))
                {
                    flag = true;
                    i += negativeSign.Length;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0295;
                    }
                    num = value[i];
                }
            }
        }
        num2 = 0L;
        if (IsDigit(num))
        {
            if (num != 48)
            {
                goto IL_01a8;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (num == 48)
                {
                    continue;
                }
                goto IL_019d;
            }
            goto IL_028c;
        }
        goto IL_0295;
        IL_02a9:
        if (IsWhite(num))
        {
            if ((styles & NumberStyles.AllowTrailingWhite) == 0)
            {
                goto IL_0295;
            }
            for (i++; i < value.Length && IsWhite(value[i]); i++)
            {
            }
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_0289;
            }
        }
        if (TrailingZeros(value, i))
        {
            goto IL_0289;
        }
        goto IL_0295;
        IL_029e:
        result = 0uL;
        return ParsingStatus.Overflow;
        IL_0295:
        result = 0uL;
        return ParsingStatus.Failed;
    }
References System.info, System.Number.IsDigit(), System.Number.IsWhite(), System.L, System.Number.TrailingZeros(), and System.value.
Referenced by System.UInt64.TryParse(), System.UInt64.TryParse(), System.Number.TryParseUInt64(), and System.Enum.TryParseUInt64Enum().