Terraria: System.Number.TryParseUInt32HexNumberStyle
TryParseUInt32HexNumberStyle()
static ParsingStatus System.Number.TryParseUInt32HexNumberStyle (ReadOnlySpan< char > value, NumberStyles styles, out uint result) inline static package
Definition at line 4972 of file Number.cs.
    {
        int i;
        int num;
        if (!value.IsEmpty)
        {
            i = 0;
            num = value[0];
            if ((styles & NumberStyles.AllowLeadingWhite) == 0 || !IsWhite(num))
            {
                goto IL_0048;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (IsWhite(num))
                {
                    continue;
                }
                goto IL_0048;
            }
        }
        goto IL_011f;
        IL_0087:
        uint num2 = (uint)HexConverter.FromChar(num);
        i++;
        int num3 = 0;
        while (num3 < 7)
        {
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_0116;
            }
            num = value[i];
            uint num4 = (uint)HexConverter.FromChar(num);
            if (num4 != 255)
            {
                i++;
                num2 = 16 * num2 + num4;
                num3++;
                continue;
            }
            goto IL_012f;
        }
        if ((uint)i >= (uint)value.Length)
        {
            goto IL_0116;
        }
        num = value[i];
        if (HexConverter.IsHexChar(num))
        {
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (HexConverter.IsHexChar(num))
                {
                    continue;
                }
                goto IL_010f;
            }
            goto IL_0127;
        }
        goto IL_012f;
        IL_0127:
        result = 0u;
        return ParsingStatus.Overflow;
        IL_0113:
        bool flag;
        if (!flag)
        {
            goto IL_0116;
        }
        goto IL_0127;
        IL_011f:
        result = 0u;
        return ParsingStatus.Failed;
        IL_0048:
        flag = false;
        num2 = 0u;
        if (HexConverter.IsHexChar(num))
        {
            if (num != 48)
            {
                goto IL_0087;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (num == 48)
                {
                    continue;
                }
                goto IL_007c;
            }
            goto IL_0116;
        }
        goto IL_011f;
        IL_010f:
        flag = true;
        goto IL_012f;
        IL_012f:
        if (IsWhite(num))
        {
            if ((styles & NumberStyles.AllowTrailingWhite) == 0)
            {
                goto IL_011f;
            }
            for (i++; i < value.Length && IsWhite(value[i]); i++)
            {
            }
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_0113;
            }
        }
        if (TrailingZeros(value, i))
        {
            goto IL_0113;
        }
        goto IL_011f;
        IL_0116:
        result = num2;
        return ParsingStatus.OK;
        IL_007c:
        if (HexConverter.IsHexChar(num))
        {
            goto IL_0087;
        }
        goto IL_012f;
    }
References System.HexConverter.FromChar(), System.HexConverter.IsHexChar(), System.Number.IsWhite(), System.Number.TrailingZeros(), and System.value.
Referenced by System.Guid.TryParseExactD(), System.Number.TryParseInt32(), and System.Number.TryParseUInt32().