Terraria: System.Number.ParseUInt64
ParseUInt64()
static ulong System.Number.ParseUInt64 (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info) inline static package
Definition at line 4030 of file Number.cs.
    {
        ulong result;
        ParsingStatus parsingStatus = TryParseUInt64(value, styles, info, out result);
        if (parsingStatus != 0)
        {
            ThrowOverflowOrFormatException(parsingStatus, TypeCode.UInt64);
        }
        return result;
    }
References System.info, System.Number.ThrowOverflowOrFormatException(), System.Number.TryParseUInt64(), and System.value.
Referenced by System.UInt64.Parse(), System.UInt64.Parse(), System.UInt64.Parse(), System.UInt64.Parse(), and System.UInt64.Parse().