Terraria: System.Number.TryParseUInt32IntegerStyle
TryParseUInt32IntegerStyle()
static ParsingStatus System.Number.TryParseUInt32IntegerStyle (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out uint result) inline static package
Definition at line 4764 of file Number.cs.
    {
        int i;
        int num;
        if (!value.IsEmpty)
        {
            i = 0;
            num = value[0];
            if ((styles & NumberStyles.AllowLeadingWhite) == 0 || !IsWhite(num))
            {
                goto IL_0048;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (IsWhite(num))
                {
                    continue;
                }
                goto IL_0048;
            }
        }
        goto IL_0281;
        IL_01a7:
        int num2 = num - 48;
        i++;
        int num3 = 0;
        while (num3 < 8)
        {
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_0275;
            }
            num = value[i];
            if (IsDigit(num))
            {
                i++;
                num2 = 10 * num2 + num - 48;
                num3++;
                continue;
            }
            goto IL_0293;
        }
        if ((uint)i >= (uint)value.Length)
        {
            goto IL_0275;
        }
        num = value[i];
        bool flag;
        if (IsDigit(num))
        {
            i++;
            flag = flag || (uint)num2 > 429496729u || (num2 == 429496729 && num > 53);
            num2 = num2 * 10 + num - 48;
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_0275;
            }
            num = value[i];
            while (IsDigit(num))
            {
                flag = true;
                i++;
                if ((uint)i < (uint)value.Length)
                {
                    num = value[i];
                    continue;
                }
                goto IL_0289;
            }
        }
        goto IL_0293;
        IL_0278:
        result = (uint)num2;
        return ParsingStatus.OK;
        IL_019c:
        if (IsDigit(num))
        {
            goto IL_01a7;
        }
        flag = false;
        goto IL_0293;
        IL_0275:
        if (!flag)
        {
            goto IL_0278;
        }
        goto IL_0289;
        IL_0048:
        flag = false;
        if ((styles & NumberStyles.AllowLeadingSign) != 0)
        {
            if (info.HasInvariantNumberSigns)
            {
                if (num == 43)
                {
                    i++;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0281;
                    }
                    num = value[i];
                }
                else if (num == 45)
                {
                    flag = true;
                    i++;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0281;
                    }
                    num = value[i];
                }
            }
            else if (info.AllowHyphenDuringParsing && num == 45)
            {
                flag = true;
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    goto IL_0281;
                }
                num = value[i];
            }
            else
            {
                value = value.Slice(i);
                i = 0;
                string positiveSign = info.PositiveSign;
                string negativeSign = info.NegativeSign;
                if (!string.IsNullOrEmpty(positiveSign) && value.StartsWith(positiveSign))
                {
                    i += positiveSign.Length;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0281;
                    }
                    num = value[i];
                }
                else if (!string.IsNullOrEmpty(negativeSign) && value.StartsWith(negativeSign))
                {
                    flag = true;
                    i += negativeSign.Length;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0281;
                    }
                    num = value[i];
                }
            }
        }
        num2 = 0;
        if (IsDigit(num))
        {
            if (num != 48)
            {
                goto IL_01a7;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (num == 48)
                {
                    continue;
                }
                goto IL_019c;
            }
            goto IL_0278;
        }
        goto IL_0281;
        IL_0293:
        if (IsWhite(num))
        {
            if ((styles & NumberStyles.AllowTrailingWhite) == 0)
            {
                goto IL_0281;
            }
            for (i++; i < value.Length && IsWhite(value[i]); i++)
            {
            }
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_0275;
            }
        }
        if (TrailingZeros(value, i))
        {
            goto IL_0275;
        }
        goto IL_0281;
        IL_0289:
        result = 0u;
        return ParsingStatus.Overflow;
        IL_0281:
        result = 0u;
        return ParsingStatus.Failed;
    }
References System.info, System.Number.IsDigit(), System.Number.IsWhite(), System.Number.TrailingZeros(), and System.value.
Referenced by System.UInt32.TryParse(), System.UInt32.TryParse(), System.Number.TryParseUInt32(), and System.Enum.TryParseUInt32Enum().