Terraria: System.Number.ParseFormatSpecifier
ParseFormatSpecifier()
static char System.Number.ParseFormatSpecifier (ReadOnlySpan< char > format, out int digits) inline static package
Definition at line 2657 of file Number.cs.
    {
        char c = '\0';
        if (format.Length > 0)
        {
            c = format[0];
            if ((uint)(c - 65) <= 25u || (uint)(c - 97) <= 25u)
            {
                if (format.Length == 1)
                {
                    digits = -1;
                    return c;
                }
                if (format.Length == 2)
                {
                    int num = format[1] - 48;
                    if ((uint)num < 10u)
                    {
                        digits = num;
                        return c;
                    }
                }
                else if (format.Length == 3)
                {
                    int num2 = format[1] - 48;
                    int num3 = format[2] - 48;
                    if ((uint)num2 < 10u && (uint)num3 < 10u)
                    {
                        digits = num2 * 10 + num3;
                        return c;
                    }
                }
                int num4 = 0;
                int num5 = 1;
                while (num5 < format.Length && (uint)(format[num5] - 48) < 10u)
                {
                    int num6 = num4 * 10 + format[num5++] - 48;
                    if (num6 < num4)
                    {
                        throw new FormatException(SR.Argument_BadFormatSpecifier);
                    }
                    num4 = num6;
                }
                if (num5 == format.Length || format[num5] == '\0')
                {
                    digits = num4;
                    return c;
                }
            }
        }
        digits = -1;
        if (format.Length != 0 && c != 0)
        {
            return '\0';
        }
        return 'G';
    }
References System.SR.Argument_BadFormatSpecifier, and System.format.
Referenced by System.Number.FormatDecimal(), System.Number.FormatDouble(), System.Number.FormatHalf(), System.Number.FormatInt32(), System.Number.FormatInt64(), System.Number.FormatSingle(), System.Number.FormatUInt32(), System.Number.FormatUInt64(), System.Number.TryFormatDecimal(), System.Number.TryFormatInt32(), System.Number.TryFormatInt64(), System.Number.TryFormatUInt32(), and System.Number.TryFormatUInt64().