Terraria: System.Number.FormatInt32
FormatInt32()
static string System.Number.FormatInt32 (int value, int hexMask, string format, IFormatProvider provider) inline static
Definition at line 1882 of file Number.cs.
    {
        if (string.IsNullOrEmpty(format))
        {
            if (value < 0)
            {
                return NegativeInt32ToDecStr(value, -1, NumberFormatInfo.GetInstance(provider).NegativeSign);
            }
            return UInt32ToDecStr((uint)value);
        }
        return FormatInt32Slow(value, hexMask, format, provider);
        unsafe static string FormatInt32Slow(int value, int hexMask, string format, IFormatProvider provider)
        {
            ReadOnlySpan<char> format2 = format;
            int digits;
            char c = ParseFormatSpecifier(format2, out digits);
            char c2 = (char)(c & 0xFFDFu);
            if ((c2 == 'G') ? (digits < 1) : (c2 == 'D'))
            {
                if (value < 0)
                {
                    return NegativeInt32ToDecStr(value, digits, NumberFormatInfo.GetInstance(provider).NegativeSign);
                }
                return UInt32ToDecStr((uint)value, digits);
            }
            if (c2 == 'X')
            {
                return Int32ToHexStr(value & hexMask, GetHexBase(c), digits);
            }
            NumberFormatInfo instance = NumberFormatInfo.GetInstance(provider);
            byte* digits2 = stackalloc byte[11];
            NumberBuffer number = new NumberBuffer(NumberBufferKind.Integer, digits2, 11);
            Int32ToNumber(value, ref number);
            char* pointer = stackalloc char[32];
            ValueStringBuilder sb = new ValueStringBuilder(new Span<char>(pointer, 32));
            if (c != 0)
            {
                NumberToString(ref sb, ref number, c, digits, instance);
            }
            else
            {
                NumberToStringFormat(ref sb, ref number, format2, instance);
            }
            return sb.ToString();
        }
    }
References System.format, System.Number.GetHexBase(), System.Globalization.NumberFormatInfo.GetInstance(), System.Number.Int32ToHexStr(), System.Number.Int32ToNumber(), System.Number.NegativeInt32ToDecStr(), System.Number.NumberToString(), System.Number.NumberToStringFormat(), System.Number.ParseFormatSpecifier(), System.pointer, System.Text.ValueStringBuilder.ToString(), System.Number.UInt32ToDecStr(), and System.value.
Referenced by System.Int16.ToString(), System.Int32.ToString(), System.SByte.ToString(), System.Int16.ToString(), System.Int32.ToString(), and System.SByte.ToString().