Terraria: System.Number.ConvertBigIntegerToFloatingPointBits
ConvertBigIntegerToFloatingPointBits()
static ulong System.Number.ConvertBigIntegerToFloatingPointBits (ref BigInteger value, in FloatingPointInfo info, uint integerBitsOfPrecision, bool hasNonZeroFractionalPart) inline static private
Definition at line 3631 of file Number.cs.
    {
        int denormalMantissaBits = info.DenormalMantissaBits;
        if (integerBitsOfPrecision <= 64)
        {
            return AssembleFloatingPointBits(in info, value.ToUInt64(), denormalMantissaBits, !hasNonZeroFractionalPart);
        }
        (uint Quotient, uint Remainder) tuple = Math.DivRem(integerBitsOfPrecision, 32u);
        uint item = tuple.Quotient;
        uint item2 = tuple.Remainder;
        uint num = item - 1;
        uint num2 = num - 1;
        int num3 = denormalMantissaBits + (int)(num2 * 32);
        bool flag = !hasNonZeroFractionalPart;
        ulong initialMantissa;
        if (item2 == 0)
        {
            initialMantissa = ((ulong)value.GetBlock(num) << 32) + value.GetBlock(num2);
        }
        else
        {
            int num4 = (int)item2;
            int num5 = 64 - num4;
            int num6 = num5 - 32;
            num3 += (int)item2;
            uint block = value.GetBlock(num2);
            uint num7 = block >> num4;
            ulong num8 = (ulong)value.GetBlock(num) << num6;
            ulong num9 = (ulong)value.GetBlock(item) << num5;
            initialMantissa = num9 + num8 + num7;
            uint num10 = (uint)((1 << (int)item2) - 1);
            flag = flag && (block & num10) == 0;
        }
        for (uint num11 = 0u; num11 != num2; num11++)
        {
            flag &= value.GetBlock(num11) == 0;
        }
        return AssembleFloatingPointBits(in info, initialMantissa, num3, flag);
    }
References System.Number.AssembleFloatingPointBits(), System.Math.DivRem(), System.info, System.item, and System.value.
Referenced by System.Number.NumberToFloatingPointBitsSlow().