Terraria: System.Number.FormatExponent
FormatExponent()
static unsafe void System.Number.FormatExponent (ref ValueStringBuilder sb, NumberFormatInfo info, int value, char expChar, int minDigits, bool positiveSign) inline static private
Definition at line 3298 of file Number.cs.
    {
        sb.Append(expChar);
        if (value < 0)
        {
            sb.Append(info.NegativeSign);
            value = -value;
        }
        else if (positiveSign)
        {
            sb.Append(info.PositiveSign);
        }
        char* ptr = stackalloc char[10];
        char* ptr2 = UInt32ToDecChars(ptr + 10, (uint)value, minDigits);
        sb.Append(ptr2, (int)(ptr + 10 - ptr2));
    }
References System.info, System.Number.UInt32ToDecChars(), and System.value.
Referenced by System.Number.FormatGeneral(), System.Number.FormatScientific(), and System.Number.NumberToStringFormat().