Terraria: System.Number.FormatInt64
FormatInt64()
static string System.Number.FormatInt64 (long value, string format, IFormatProvider provider) inline static
Definition at line 2052 of file Number.cs.
    {
        if (string.IsNullOrEmpty(format))
        {
            if (value < 0)
            {
                return NegativeInt64ToDecStr(value, -1, NumberFormatInfo.GetInstance(provider).NegativeSign);
            }
            return UInt64ToDecStr((ulong)value, -1);
        }
        return FormatInt64Slow(value, format, provider);
        unsafe static string FormatInt64Slow(long value, string format, IFormatProvider provider)
        {
            ReadOnlySpan<char> format2 = format;
            int digits;
            char c = ParseFormatSpecifier(format2, out digits);
            char c2 = (char)(c & 0xFFDFu);
            if ((c2 == 'G') ? (digits < 1) : (c2 == 'D'))
            {
                if (value < 0)
                {
                    return NegativeInt64ToDecStr(value, digits, NumberFormatInfo.GetInstance(provider).NegativeSign);
                }
                return UInt64ToDecStr((ulong)value, digits);
            }
            if (c2 == 'X')
            {
                return Int64ToHexStr(value, GetHexBase(c), digits);
            }
            NumberFormatInfo instance = NumberFormatInfo.GetInstance(provider);
            byte* digits2 = stackalloc byte[20];
            NumberBuffer number = new NumberBuffer(NumberBufferKind.Integer, digits2, 20);
            Int64ToNumber(value, ref number);
            char* pointer = stackalloc char[32];
            ValueStringBuilder sb = new ValueStringBuilder(new Span<char>(pointer, 32));
            if (c != 0)
            {
                NumberToString(ref sb, ref number, c, digits, instance);
            }
            else
            {
                NumberToStringFormat(ref sb, ref number, format2, instance);
            }
            return sb.ToString();
        }
    }
References System.format, System.Number.GetHexBase(), System.Globalization.NumberFormatInfo.GetInstance(), System.Number.Int64ToHexStr(), System.Number.Int64ToNumber(), System.Number.NegativeInt64ToDecStr(), System.Number.NumberToString(), System.Number.NumberToStringFormat(), System.Number.ParseFormatSpecifier(), System.pointer, System.Text.ValueStringBuilder.ToString(), System.Number.UInt64ToDecStr(), and System.value.
Referenced by System.Int64.ToString(), System.Int64.ToString(), and System.Int64.ToString().