Terraria: System.Number.Int32ToHexStr
Int32ToHexStr()
static unsafe string System.Number.Int32ToHexStr (int value, char hexBase, int digits) inline static private
Definition at line 2298 of file Number.cs.
    {
        if (digits < 1)
        {
            digits = 1;
        }
        int num = Math.Max(digits, FormattingHelpers.CountHexDigits((uint)value));
        string text = string.FastAllocateString(num);
        fixed (char* ptr = text)
        {
            char* ptr2 = Int32ToHexChars(ptr + num, (uint)value, hexBase, digits);
        }
        return text;
    }
References System.Buffers.Text.FormattingHelpers.CountHexDigits(), System.Number.Int32ToHexChars(), System.Math.Max(), System.text, and System.value.
Referenced by System.Number.FormatInt32(), and System.Number.FormatUInt32().