Terraria: System.Number.TryParseDouble
TryParseDouble()
static unsafe bool System.Number.TryParseDouble (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out double result) inline static package
Definition at line 5665 of file Number.cs.
    {
        byte* digits = stackalloc byte[769];
        NumberBuffer number = new NumberBuffer(NumberBufferKind.FloatingPoint, digits, 769);
        if (!TryStringToNumber(value, styles, ref number, info))
        {
            ReadOnlySpan<char> span = value.Trim();
            if (span.EqualsOrdinalIgnoreCase(info.PositiveInfinitySymbol))
            {
                result = double.PositiveInfinity;
            }
            else if (span.EqualsOrdinalIgnoreCase(info.NegativeInfinitySymbol))
            {
                result = double.NegativeInfinity;
            }
            else if (span.EqualsOrdinalIgnoreCase(info.NaNSymbol))
            {
                result = double.NaN;
            }
            else if (span.StartsWith(info.PositiveSign, StringComparison.OrdinalIgnoreCase))
            {
                span = span.Slice(info.PositiveSign.Length);
                if (span.EqualsOrdinalIgnoreCase(info.PositiveInfinitySymbol))
                {
                    result = double.PositiveInfinity;
                }
                else
                {
                    if (!span.EqualsOrdinalIgnoreCase(info.NaNSymbol))
                    {
                        result = 0.0;
                        return false;
                    }
                    result = double.NaN;
                }
            }
            else
            {
                if ((!span.StartsWith(info.NegativeSign, StringComparison.OrdinalIgnoreCase) || !span.Slice(info.NegativeSign.Length).EqualsOrdinalIgnoreCase(info.NaNSymbol)) && (!info.AllowHyphenDuringParsing || !SpanStartsWith(span, '-') || !span.Slice(1).EqualsOrdinalIgnoreCase(info.NaNSymbol)))
                {
                    result = 0.0;
                    return false;
                }
                result = double.NaN;
            }
        }
        else
        {
            result = NumberToDouble(ref number);
        }
        return true;
    }
References System.info, System.Number.NumberToDouble(), System.ReadOnlySpan< T >.Slice(), System.Number.SpanStartsWith(), System.Number.TryStringToNumber(), and System.value.
Referenced by System.Number.ParseDouble(), and System.Double.TryParse().