Terraria: System.Number.Int64ToHexStr
Int64ToHexStr()
static unsafe string System.Number.Int64ToHexStr (long value, char hexBase, int digits) inline static private
Definition at line 2541 of file Number.cs.
    {
        int num = Math.Max(digits, FormattingHelpers.CountHexDigits((ulong)value));
        string text = string.FastAllocateString(num);
        fixed (char* ptr = text)
        {
            char* buffer = ptr + num;
            if (High32((ulong)value) != 0)
            {
                buffer = Int32ToHexChars(buffer, Low32((ulong)value), hexBase, 8);
                buffer = Int32ToHexChars(buffer, High32((ulong)value), hexBase, digits - 8);
            }
            else
            {
                buffer = Int32ToHexChars(buffer, Low32((ulong)value), hexBase, Math.Max(digits, 1));
            }
        }
        return text;
    }
References System.buffer, System.Buffers.Text.FormattingHelpers.CountHexDigits(), System.Number.High32(), System.Number.Int32ToHexChars(), System.Number.Low32(), System.Math.Max(), System.text, and System.value.
Referenced by System.Number.FormatInt64(), and System.Number.FormatUInt64().