Terraria: System.Number.TryParseInt64
TryParseInt64()
static ParsingStatus System.Number.TryParseInt64 (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out long result) inline static package
Definition at line 4704 of file Number.cs.
    {
        if ((styles & ~NumberStyles.Integer) == 0)
        {
            return TryParseInt64IntegerStyle(value, styles, info, out result);
        }
        if ((styles & NumberStyles.AllowHexSpecifier) != 0)
        {
            result = 0L;
            return TryParseUInt64HexNumberStyle(value, styles, out Unsafe.As<long, ulong>(ref result));
        }
        return TryParseInt64Number(value, styles, info, out result);
    }
References System.info, System.L, System.Number.TryParseInt64IntegerStyle(), System.Number.TryParseInt64Number(), System.Number.TryParseUInt64HexNumberStyle(), and System.value.
Referenced by System.Number.ParseInt64(), System.Int64.TryParse(), and System.Int64.TryParse().