Terraria: System.Number.FormatFixed
FormatFixed()
static unsafe void System.Number.FormatFixed (ref ValueStringBuilder sb, ref NumberBuffer number, int nMaxDigits, int[] groupDigits, string sDecimal, string sGroup) inline static private
Definition at line 3170 of file Number.cs.
    {
        int num = number.Scale;
        byte* ptr = number.GetDigitsPointer();
        if (num > 0)
        {
            if (groupDigits != null)
            {
                int num2 = 0;
                int num3 = num;
                int num4 = 0;
                if (groupDigits.Length != 0)
                {
                    int num5 = groupDigits[num2];
                    while (num > num5 && groupDigits[num2] != 0)
                    {
                        num3 += sGroup.Length;
                        if (num2 < groupDigits.Length - 1)
{
                            num2++;
                        }
                        num5 += groupDigits[num2];
                        if (num5 < 0 || num3 < 0)
{
                            throw new ArgumentOutOfRangeException();
                        }
                    }
                    num4 = ((num5 != 0) ? groupDigits[0] : 0);
                }
                num2 = 0;
                int num6 = 0;
                int digitsCount = number.DigitsCount;
                int num7 = ((num < digitsCount) ? num : digitsCount);
                fixed (char* ptr2 = &MemoryMarshal.GetReference(sb.AppendSpan(num3)))
                {
                    char* ptr3 = ptr2 + num3 - 1;
                    for (int num8 = num - 1; num8 >= 0; num8--)
                    {
                        *(ptr3--) = (char)((num8 < num7) ? ptr[num8] : 48);
                        if (num4 > 0)
{
                            num6++;
                            if (num6 == num4 && num8 != 0)
{
                                for (int num9 = sGroup.Length - 1; num9 >= 0; num9--)
{
                                    *(ptr3--) = sGroup[num9];
                                }
                                if (num2 < groupDigits.Length - 1)
{
                                    num2++;
                                    num4 = groupDigits[num2];
                                }
                                num6 = 0;
                            }
                        }
                    }
                    ptr += num7;
                }
            }
            else
            {
                do
                {
                    sb.Append((char)((*ptr != 0) ? (*(ptr++)) : 48));
                }
                while (--num > 0);
            }
        }
        else
        {
            sb.Append('0');
        }
        if (nMaxDigits > 0)
        {
            sb.Append(sDecimal);
            if (num < 0 && nMaxDigits > 0)
            {
                int num10 = Math.Min(-num, nMaxDigits);
                sb.Append('0', num10);
                num += num10;
                nMaxDigits -= num10;
            }
            while (nMaxDigits > 0)
            {
                sb.Append((char)((*ptr != 0) ? (*(ptr++)) : 48));
                nMaxDigits--;
            }
        }
    }
References System.Math.Min().
Referenced by System.Number.FormatCurrency(), System.Number.FormatNumber(), System.Number.FormatPercent(), and System.Number.NumberToString().