Terraria: System.Number.TrailingZeros
TrailingZeros()
static bool System.Number.TrailingZeros (ReadOnlySpan< char > value, int index) inline static private
Definition at line 5845 of file Number.cs.
    {
        for (int i = index; (uint)i < (uint)value.Length; i++)
        {
            if (value[i] != 0)
            {
                return false;
            }
        }
        return true;
    }
References System.index, and System.value.
Referenced by System.Number.TryParseInt32IntegerStyle(), System.Number.TryParseInt64IntegerStyle(), System.Number.TryParseUInt32HexNumberStyle(), System.Number.TryParseUInt32IntegerStyle(), System.Number.TryParseUInt64HexNumberStyle(), System.Number.TryParseUInt64IntegerStyle(), and System.Number.TryStringToNumber().