Terraria: System.Number.UInt32ToDecStr
UInt32ToDecStr() [1/2]
static unsafe string System.Number.UInt32ToDecStr (uint value) inline static package
Definition at line 2382 of file Number.cs.
    {
        int num = FormattingHelpers.CountDigits(value);
        if (num == 1)
        {
            return s_singleDigitStringCache[value];
        }
        string text = string.FastAllocateString(num);
        fixed (char* ptr = text)
        {
            char* ptr2 = ptr + num;
            do
            {
                uint num2;
                (value, num2) = Math.DivRem(value, 10u);
                *(--ptr2) = (char)(num2 + 48);
            }
            while (value != 0);
        }
        return text;
    }
References System.Buffers.Text.FormattingHelpers.CountDigits(), System.Math.DivRem(), System.Number.s_singleDigitStringCache, System.text, and System.value.
Referenced by System.Number.FormatInt32(), System.Number.FormatUInt32(), System.Number.Int32ToDecStr(), System.Byte.ToString(), System.UInt16.ToString(), System.UInt32.ToString(), System.Byte.ToString(), System.UInt16.ToString(), System.UInt32.ToString(), and System.Number.UInt32ToDecStr().