Terraria: System.Number.ExtractFractionAndBiasedExponent
ExtractFractionAndBiasedExponent() [1/3]
static ulong System.Number.ExtractFractionAndBiasedExponent (double value, out int exponent) inline static private
Definition at line 3510 of file Number.cs.
    {
        ulong num = BitConverter.DoubleToUInt64Bits(value);
        ulong num2 = num & 0xFFFFFFFFFFFFFuL;
        exponent = (int)(num >> 52) & 0x7FF;
        if (exponent != 0)
        {
            num2 |= 0x10000000000000uL;
            exponent -= 1075;
        }
        else
        {
            exponent = -1074;
        }
        return num2;
    }
References System.BitConverter.DoubleToUInt64Bits(), and System.value.
Referenced by System.Number.DiyFp.DiyFp(), System.Number.DiyFp.DiyFp(), System.Number.DiyFp.DiyFp(), System.Number.Dragon4Double(), System.Number.Dragon4Half(), and System.Number.Dragon4Single().