Terraria: System.Number.Int32ToNumber
Int32ToNumber()
static unsafe void System.Number.Int32ToNumber (int value, ref NumberBuffer number) inline static private
Definition at line 2223 of file Number.cs.
    {
        number.DigitsCount = 10;
        if (value >= 0)
        {
            number.IsNegative = false;
        }
        else
        {
            number.IsNegative = true;
            value = -value;
        }
        byte* digitsPointer = number.GetDigitsPointer();
        byte* ptr = UInt32ToDecChars(digitsPointer + 10, (uint)value, 0);
        int num = (number.Scale = (number.DigitsCount = (int)(digitsPointer + 10 - ptr)));
        byte* digitsPointer2 = number.GetDigitsPointer();
        while (--num >= 0)
        {
            *(digitsPointer2++) = *(ptr++);
        }
        *digitsPointer2 = 0;
    }
References System.Number.UInt32ToDecChars(), and System.value.
Referenced by System.Number.FormatInt32(), and System.Number.TryFormatInt32().