Terraria: System.Number.AccumulateDecimalDigitsIntoBigInteger
AccumulateDecimalDigitsIntoBigInteger()
static unsafe void System.Number.AccumulateDecimalDigitsIntoBigInteger (ref NumberBuffer number, uint firstIndex, uint lastIndex, out BigInteger result) inline static private
Definition at line 3561 of file Number.cs.
    {
        BigInteger.SetZero(out result);
        byte* ptr = number.GetDigitsPointer() + firstIndex;
        uint num = lastIndex - firstIndex;
        while (num != 0)
        {
            uint num2 = Math.Min(num, 9u);
            uint value = DigitsToUInt32(ptr, (int)num2);
            result.MultiplyPow10(num2);
            result.Add(value);
            ptr += num2;
            num -= num2;
        }
    }
References System.Number.DigitsToUInt32(), System.Math.Min(), System.Number.BigInteger.SetZero(), and System.value.
Referenced by System.Number.NumberToFloatingPointBitsSlow().