Terraria: System.Number.UInt32ToNumber
UInt32ToNumber()
static unsafe void System.Number.UInt32ToNumber (uint value, ref NumberBuffer number) inline static private
Definition at line 2345 of file Number.cs.
    {
        number.DigitsCount = 10;
        number.IsNegative = false;
        byte* digitsPointer = number.GetDigitsPointer();
        byte* ptr = UInt32ToDecChars(digitsPointer + 10, value, 0);
        int num = (number.Scale = (number.DigitsCount = (int)(digitsPointer + 10 - ptr)));
        byte* digitsPointer2 = number.GetDigitsPointer();
        while (--num >= 0)
        {
            *(digitsPointer2++) = *(ptr++);
        }
        *digitsPointer2 = 0;
    }
References System.Number.UInt32ToDecChars(), and System.value.
Referenced by System.Number.FormatUInt32(), and System.Number.TryFormatUInt32().