Terraria: System.Number.Dragon4Double
Dragon4Double()
static void System.Number.Dragon4Double (double value, int cutoffNumber, bool isSignificantDigits, ref NumberBuffer number) inline static
Definition at line 1266 of file Number.cs.
    {
        double num = (double.IsNegative(value) ? (0.0 - value) : value);
        int exponent;
        ulong num2 = ExtractFractionAndBiasedExponent(value, out exponent);
        bool hasUnequalMargins = false;
        uint mantissaHighBitIdx;
        if (num2 >> 52 != 0L)
        {
            mantissaHighBitIdx = 52u;
            hasUnequalMargins = num2 == 4503599627370496L;
        }
        else
        {
            mantissaHighBitIdx = (uint)BitOperations.Log2(num2);
        }
        int decimalExponent;
        int num3 = (int)Dragon4(num2, exponent, mantissaHighBitIdx, hasUnequalMargins, cutoffNumber, isSignificantDigits, number.Digits, out decimalExponent);
        number.Scale = decimalExponent + 1;
        number.Digits[num3] = 0;
        number.DigitsCount = num3;
    }
References System.Number.Dragon4(), System.Number.ExtractFractionAndBiasedExponent(), System.L, System.Numerics.BitOperations.Log2(), and System.value.
Referenced by System.Number.FormatDouble().