Terraria: System.Number.TryParseHalf
TryParseHalf()
static unsafe bool System.Number.TryParseHalf (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out Half result) inline static package
Definition at line 5718 of file Number.cs.
    {
        byte* digits = stackalloc byte[21];
        NumberBuffer number = new NumberBuffer(NumberBufferKind.FloatingPoint, digits, 21);
        if (!TryStringToNumber(value, styles, ref number, info))
        {
            ReadOnlySpan<char> span = value.Trim();
            if (span.EqualsOrdinalIgnoreCase(info.PositiveInfinitySymbol))
            {
                result = Half.PositiveInfinity;
            }
            else if (span.EqualsOrdinalIgnoreCase(info.NegativeInfinitySymbol))
            {
                result = Half.NegativeInfinity;
            }
            else if (span.EqualsOrdinalIgnoreCase(info.NaNSymbol))
            {
                result = Half.NaN;
            }
            else if (span.StartsWith(info.PositiveSign, StringComparison.OrdinalIgnoreCase))
            {
                span = span.Slice(info.PositiveSign.Length);
                if (!info.PositiveInfinitySymbol.StartsWith(info.PositiveSign, StringComparison.OrdinalIgnoreCase) && span.EqualsOrdinalIgnoreCase(info.PositiveInfinitySymbol))
                {
                    result = Half.PositiveInfinity;
                }
                else
                {
                    if (info.NaNSymbol.StartsWith(info.PositiveSign, StringComparison.OrdinalIgnoreCase) || !span.EqualsOrdinalIgnoreCase(info.NaNSymbol))
                    {
                        result = (Half)0f;
                        return false;
                    }
                    result = Half.NaN;
                }
            }
            else if (span.StartsWith(info.NegativeSign, StringComparison.OrdinalIgnoreCase) && !info.NaNSymbol.StartsWith(info.NegativeSign, StringComparison.OrdinalIgnoreCase) && span.Slice(info.NegativeSign.Length).EqualsOrdinalIgnoreCase(info.NaNSymbol))
            {
                result = Half.NaN;
            }
            else
            {
                if (!info.AllowHyphenDuringParsing || !SpanStartsWith(span, '-') || info.NaNSymbol.StartsWith(info.NegativeSign, StringComparison.OrdinalIgnoreCase) || info.NaNSymbol.StartsWith('-') || !span.Slice(1).EqualsOrdinalIgnoreCase(info.NaNSymbol))
                {
                    result = (Half)0f;
                    return false;
                }
                result = Half.NaN;
            }
        }
        else
        {
            result = NumberToHalf(ref number);
        }
        return true;
    }
References System.info, System.Half.NaN, System.Half.NegativeInfinity, System.Number.NumberToHalf(), System.Half.PositiveInfinity, System.ReadOnlySpan< T >.Slice(), System.Number.SpanStartsWith(), System.Number.TryStringToNumber(), and System.value.
Referenced by System.Number.ParseHalf(), and System.Half.TryParse().