Terraria: System.Number.TryUInt32ToDecStr
TryUInt32ToDecStr()
static unsafe bool System.Number.TryUInt32ToDecStr (uint value, int digits, Span< char > destination, out int charsWritten) inline static private
Definition at line 2420 of file Number.cs.
    {
        int num = Math.Max(digits, FormattingHelpers.CountDigits(value));
        if (num > destination.Length)
        {
            charsWritten = 0;
            return false;
        }
        charsWritten = num;
        fixed (char* ptr = &MemoryMarshal.GetReference(destination))
        {
            char* ptr2 = ptr + num;
            if (digits <= 1)
            {
                do
                {
                    uint num2;
                    (value, num2) = Math.DivRem(value, 10u);
                    *(--ptr2) = (char)(num2 + 48);
                }
                while (value != 0);
            }
            else
            {
                ptr2 = UInt32ToDecChars(ptr2, value, digits);
            }
        }
        return true;
    }
References System.Buffers.Text.FormattingHelpers.CountDigits(), System.destination, System.Math.DivRem(), System.Math.Max(), System.Number.UInt32ToDecChars(), and System.value.
Referenced by System.Number.TryFormatInt32(), and System.Number.TryFormatUInt32().