Terraria: System.Number.TryFormatUInt32
TryFormatUInt32()
static bool System.Number.TryFormatUInt32 (uint value, ReadOnlySpan< char > format, IFormatProvider provider, Span< char > destination, out int charsWritten) inline static
Definition at line 2014 of file Number.cs.
    {
        if (format.Length == 0)
        {
            return TryUInt32ToDecStr(value, -1, destination, out charsWritten);
        }
        return TryFormatUInt32Slow(value, format, provider, destination, out charsWritten);
        unsafe static bool TryFormatUInt32Slow(uint value, ReadOnlySpan<char> format, IFormatProvider provider, Span<char> destination, out int charsWritten)
        {
            int digits;
            char c = ParseFormatSpecifier(format, out digits);
            char c2 = (char)(c & 0xFFDFu);
            if ((c2 == 'G') ? (digits < 1) : (c2 == 'D'))
            {
                return TryUInt32ToDecStr(value, digits, destination, out charsWritten);
            }
            if (c2 == 'X')
            {
                return TryInt32ToHexStr((int)value, GetHexBase(c), digits, destination, out charsWritten);
            }
            NumberFormatInfo instance = NumberFormatInfo.GetInstance(provider);
            byte* digits2 = stackalloc byte[11];
            NumberBuffer number = new NumberBuffer(NumberBufferKind.Integer, digits2, 11);
            UInt32ToNumber(value, ref number);
            char* pointer = stackalloc char[32];
            ValueStringBuilder sb = new ValueStringBuilder(new Span<char>(pointer, 32));
            if (c != 0)
            {
                NumberToString(ref sb, ref number, c, digits, instance);
            }
            else
            {
                NumberToStringFormat(ref sb, ref number, format, instance);
            }
            return sb.TryCopyTo(destination, out charsWritten);
        }
    }
References System.destination, System.format, System.Number.GetHexBase(), System.Globalization.NumberFormatInfo.GetInstance(), System.Number.NumberToString(), System.Number.NumberToStringFormat(), System.Number.ParseFormatSpecifier(), System.pointer, System.Text.ValueStringBuilder.TryCopyTo(), System.Number.TryInt32ToHexStr(), System.Number.TryUInt32ToDecStr(), System.Number.UInt32ToNumber(), and System.value.
Referenced by System.Byte.TryFormat(), System.UInt16.TryFormat(), and System.UInt32.TryFormat().