Terraria: System.Number.FormatUInt32
FormatUInt32()
static string System.Number.FormatUInt32 (uint value, string format, IFormatProvider provider) inline static
Definition at line 1975 of file Number.cs.
    {
        if (string.IsNullOrEmpty(format))
        {
            return UInt32ToDecStr(value);
        }
        return FormatUInt32Slow(value, format, provider);
        unsafe static string FormatUInt32Slow(uint value, string format, IFormatProvider provider)
        {
            ReadOnlySpan<char> format2 = format;
            int digits;
            char c = ParseFormatSpecifier(format2, out digits);
            char c2 = (char)(c & 0xFFDFu);
            if ((c2 == 'G') ? (digits < 1) : (c2 == 'D'))
            {
                return UInt32ToDecStr(value, digits);
            }
            if (c2 == 'X')
            {
                return Int32ToHexStr((int)value, GetHexBase(c), digits);
            }
            NumberFormatInfo instance = NumberFormatInfo.GetInstance(provider);
            byte* digits2 = stackalloc byte[11];
            NumberBuffer number = new NumberBuffer(NumberBufferKind.Integer, digits2, 11);
            UInt32ToNumber(value, ref number);
            char* pointer = stackalloc char[32];
            ValueStringBuilder sb = new ValueStringBuilder(new Span<char>(pointer, 32));
            if (c != 0)
            {
                NumberToString(ref sb, ref number, c, digits, instance);
            }
            else
            {
                NumberToStringFormat(ref sb, ref number, format2, instance);
            }
            return sb.ToString();
        }
    }
References System.format, System.Number.GetHexBase(), System.Globalization.NumberFormatInfo.GetInstance(), System.Number.Int32ToHexStr(), System.Number.NumberToString(), System.Number.NumberToStringFormat(), System.Number.ParseFormatSpecifier(), System.pointer, System.Text.ValueStringBuilder.ToString(), System.Number.UInt32ToDecStr(), System.Number.UInt32ToNumber(), and System.value.
Referenced by System.Byte.ToString(), System.UInt16.ToString(), System.UInt32.ToString(), System.Byte.ToString(), System.UInt16.ToString(), and System.UInt32.ToString().