Terraria: System.Number.TryParseInt32IntegerStyle
TryParseInt32IntegerStyle()
static ParsingStatus System.Number.TryParseInt32IntegerStyle (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out int result) inline static package
Definition at line 4281 of file Number.cs.
    {
        int i;
        int num;
        if (!value.IsEmpty)
        {
            i = 0;
            num = value[0];
            if ((styles & NumberStyles.AllowLeadingWhite) == 0 || !IsWhite(num))
            {
                goto IL_0048;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (IsWhite(num))
                {
                    continue;
                }
                goto IL_0048;
            }
        }
        goto IL_0289;
        IL_027d:
        int num2;
        int num3;
        result = num2 * num3;
        return ParsingStatus.OK;
        IL_0291:
        result = 0;
        return ParsingStatus.Overflow;
        IL_019f:
        if (IsDigit(num))
        {
            goto IL_01aa;
        }
        goto IL_0299;
        IL_027a:
        bool flag;
        if (!flag)
        {
            goto IL_027d;
        }
        goto IL_0291;
        IL_0048:
        num3 = 1;
        if ((styles & NumberStyles.AllowLeadingSign) != 0)
        {
            if (info.HasInvariantNumberSigns)
            {
                if (num == 45)
                {
                    num3 = -1;
                    i++;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0289;
                    }
                    num = value[i];
                }
                else if (num == 43)
                {
                    i++;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0289;
                    }
                    num = value[i];
                }
            }
            else if (info.AllowHyphenDuringParsing && num == 45)
            {
                num3 = -1;
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    goto IL_0289;
                }
                num = value[i];
            }
            else
            {
                value = value.Slice(i);
                i = 0;
                string positiveSign = info.PositiveSign;
                string negativeSign = info.NegativeSign;
                if (!string.IsNullOrEmpty(positiveSign) && value.StartsWith(positiveSign))
                {
                    i += positiveSign.Length;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0289;
                    }
                    num = value[i];
                }
                else if (!string.IsNullOrEmpty(negativeSign) && value.StartsWith(negativeSign))
                {
                    num3 = -1;
                    i += negativeSign.Length;
                    if ((uint)i >= (uint)value.Length)
                    {
                        goto IL_0289;
                    }
                    num = value[i];
                }
            }
        }
        flag = false;
        num2 = 0;
        if (IsDigit(num))
        {
            if (num != 48)
            {
                goto IL_01aa;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (num == 48)
                {
                    continue;
                }
                goto IL_019f;
            }
            goto IL_027d;
        }
        goto IL_0289;
        IL_01aa:
        num2 = num - 48;
        i++;
        int num4 = 0;
        while (num4 < 8)
        {
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_027d;
            }
            num = value[i];
            if (IsDigit(num))
            {
                i++;
                num2 = 10 * num2 + num - 48;
                num4++;
                continue;
            }
            goto IL_0299;
        }
        if ((uint)i >= (uint)value.Length)
        {
            goto IL_027d;
        }
        num = value[i];
        if (IsDigit(num))
        {
            i++;
            flag = num2 > 214748364;
            num2 = num2 * 10 + num - 48;
            flag = flag || (uint)num2 > (uint)(int.MaxValue + (num3 >>> 31));
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_027a;
            }
            num = value[i];
            while (IsDigit(num))
            {
                flag = true;
                i++;
                if ((uint)i < (uint)value.Length)
                {
                    num = value[i];
                    continue;
                }
                goto IL_0291;
            }
        }
        goto IL_0299;
        IL_0299:
        if (IsWhite(num))
        {
            if ((styles & NumberStyles.AllowTrailingWhite) == 0)
            {
                goto IL_0289;
            }
            for (i++; i < value.Length && IsWhite(value[i]); i++)
            {
            }
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_027a;
            }
        }
        if (TrailingZeros(value, i))
        {
            goto IL_027a;
        }
        goto IL_0289;
        IL_0289:
        result = 0;
        return ParsingStatus.Failed;
    }
References System.info, System.Number.IsDigit(), System.Number.IsWhite(), System.Number.TrailingZeros(), and System.value.
Referenced by System.Int32.TryParse(), System.Int32.TryParse(), System.Number.TryParseInt32(), and System.Enum.TryParseInt32Enum().