Terraria: System.Number.TryParseDecimal
TryParseDecimal()
static unsafe ParsingStatus System.Number.TryParseDecimal (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out decimal result) inline static package
Definition at line 5640 of file Number.cs.
    {
        byte* digits = stackalloc byte[31];
        NumberBuffer number = new NumberBuffer(NumberBufferKind.Decimal, digits, 31);
        result = default(decimal);
        if (!TryStringToNumber(value, styles, ref number, info))
        {
            return ParsingStatus.Failed;
        }
        if (!TryNumberToDecimal(ref number, ref result))
        {
            return ParsingStatus.Overflow;
        }
        return ParsingStatus.OK;
    }
References System.info, System.Number.TryNumberToDecimal(), System.Number.TryStringToNumber(), and System.value.
Referenced by System.Number.ParseDecimal(), System.Decimal.TryParse(), System.Decimal.TryParse(), System.Decimal.TryParse(), and System.Decimal.TryParse().