Terraria: System.Number.UInt64ToDecStr
UInt64ToDecStr()
static unsafe string System.Number.UInt64ToDecStr (ulong value, int digits) inline static package
Definition at line 2606 of file Number.cs.
    {
        if (digits < 1)
        {
            digits = 1;
        }
        int num = Math.Max(digits, FormattingHelpers.CountDigits(value));
        if (num == 1)
        {
            return s_singleDigitStringCache[value];
        }
        string text = string.FastAllocateString(num);
        fixed (char* ptr = text)
        {
            char* bufferEnd = ptr + num;
            while (High32(value) != 0)
            {
                bufferEnd = UInt32ToDecChars(bufferEnd, Int64DivMod1E9(ref value), 9);
                digits -= 9;
            }
            bufferEnd = UInt32ToDecChars(bufferEnd, Low32(value), digits);
        }
        return text;
    }
References System.Buffers.Text.FormattingHelpers.CountDigits(), System.Number.High32(), System.Number.Int64DivMod1E9(), System.Number.Low32(), System.Math.Max(), System.Number.s_singleDigitStringCache, System.text, System.Number.UInt32ToDecChars(), and System.value.
Referenced by System.Number.FormatInt64(), System.Number.FormatUInt64(), System.Number.Int64ToDecStr(), System.UInt64.ToString(), and System.UInt64.ToString().