Terraria: System.Number.TryCopyTo
TryCopyTo()
static bool System.Number.TryCopyTo (string source, Span< char > destination, out int charsWritten) inline static private
Definition at line 1866 of file Number.cs.
    {
        if (source.TryCopyTo(destination))
        {
            charsWritten = source.Length;
            return true;
        }
        charsWritten = 0;
        return false;
    }
References System.destination, and System.source.
Referenced by System.Number.TryFormatDouble(), System.Number.TryFormatHalf(), and System.Number.TryFormatSingle().