Terraria: System.Number.FormatSingle
FormatSingle() [1/2]
static string System.Number.FormatSingle (float value, string format, NumberFormatInfo info) inline static
Definition at line 1740 of file Number.cs.
    {
        Span<char> initialBuffer = stackalloc char[32];
        ValueStringBuilder sb = new ValueStringBuilder(initialBuffer);
        return FormatSingle(ref sb, value, format, info) ?? sb.ToString();
    }
References System.format, System.Number.FormatSingle(), System.info, System.Text.ValueStringBuilder.ToString(), and System.value.
Referenced by System.Number.FormatSingle(), System.Single.ToString(), System.Single.ToString(), System.Single.ToString(), System.Single.ToString(), and System.Number.TryFormatSingle().