Terraria: System.Number.FormatSingle
FormatSingle() [2/2]
static unsafe string System.Number.FormatSingle (ref ValueStringBuilder sb, float value, ReadOnlySpan< char > format, NumberFormatInfo info) inline static private
Definition at line 1759 of file Number.cs.
    {
        if (!float.IsFinite(value))
        {
            if (float.IsNaN(value))
            {
                return info.NaNSymbol;
            }
            if (!float.IsNegative(value))
            {
                return info.PositiveInfinitySymbol;
            }
            return info.NegativeInfinitySymbol;
        }
        int digits;
        char c = ParseFormatSpecifier(format, out digits);
        byte* digits2 = stackalloc byte[114];
        if (c == '\0')
        {
            digits = 7;
        }
        NumberBuffer number = new NumberBuffer(NumberBufferKind.FloatingPoint, digits2, 114);
        number.IsNegative = float.IsNegative(value);
        bool isSignificantDigits;
        int nMaxDigits = GetFloatingPointMaxDigitsAndPrecision(c, ref digits, info, out isSignificantDigits);
        if (value != 0f && (!isSignificantDigits || !Grisu3.TryRunSingle(value, digits, ref number)))
        {
            Dragon4Single(value, digits, isSignificantDigits, ref number);
        }
        if (c != 0)
        {
            if (digits == -1)
            {
                nMaxDigits = Math.Max(number.DigitsCount, 9);
            }
            NumberToString(ref sb, ref number, c, nMaxDigits, info);
        }
        else
        {
            NumberToStringFormat(ref sb, ref number, format, info);
        }
        return null;
    }
References System.Number.NumberBuffer.DigitsCount, System.Number.Dragon4Single(), System.format, System.Number.GetFloatingPointMaxDigitsAndPrecision(), System.info, System.Math.Max(), System.Number.NumberToString(), System.Number.NumberToStringFormat(), System.Number.ParseFormatSpecifier(), System.Number.Grisu3.TryRunSingle(), and System.value.