Terraria: System.Number.TryParseUInt64HexNumberStyle
TryParseUInt64HexNumberStyle()
static ParsingStatus System.Number.TryParseUInt64HexNumberStyle (ReadOnlySpan< char > value, NumberStyles styles, out ulong result) inline static private
Definition at line 5356 of file Number.cs.
    {
        int i;
        int num;
        if (!value.IsEmpty)
        {
            i = 0;
            num = value[0];
            if ((styles & NumberStyles.AllowLeadingWhite) == 0 || !IsWhite(num))
            {
                goto IL_0048;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (IsWhite(num))
                {
                    continue;
                }
                goto IL_0048;
            }
        }
        goto IL_0124;
        IL_0088:
        ulong num2 = (uint)HexConverter.FromChar(num);
        i++;
        int num3 = 0;
        while (num3 < 15)
        {
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_011b;
            }
            num = value[i];
            uint num4 = (uint)HexConverter.FromChar(num);
            if (num4 != 255)
            {
                i++;
                num2 = 16 * num2 + num4;
                num3++;
                continue;
            }
            goto IL_0136;
        }
        if ((uint)i >= (uint)value.Length)
        {
            goto IL_011b;
        }
        num = value[i];
        if (HexConverter.IsHexChar(num))
        {
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (HexConverter.IsHexChar(num))
                {
                    continue;
                }
                goto IL_0114;
            }
            goto IL_012d;
        }
        goto IL_0136;
        IL_012d:
        result = 0uL;
        return ParsingStatus.Overflow;
        IL_0118:
        bool flag;
        if (!flag)
        {
            goto IL_011b;
        }
        goto IL_012d;
        IL_0124:
        result = 0uL;
        return ParsingStatus.Failed;
        IL_0048:
        flag = false;
        num2 = 0uL;
        if (HexConverter.IsHexChar(num))
        {
            if (num != 48)
            {
                goto IL_0088;
            }
            while (true)
            {
                i++;
                if ((uint)i >= (uint)value.Length)
                {
                    break;
                }
                num = value[i];
                if (num == 48)
                {
                    continue;
                }
                goto IL_007d;
            }
            goto IL_011b;
        }
        goto IL_0124;
        IL_0114:
        flag = true;
        goto IL_0136;
        IL_0136:
        if (IsWhite(num))
        {
            if ((styles & NumberStyles.AllowTrailingWhite) == 0)
            {
                goto IL_0124;
            }
            for (i++; i < value.Length && IsWhite(value[i]); i++)
            {
            }
            if ((uint)i >= (uint)value.Length)
            {
                goto IL_0118;
            }
        }
        if (TrailingZeros(value, i))
        {
            goto IL_0118;
        }
        goto IL_0124;
        IL_011b:
        result = num2;
        return ParsingStatus.OK;
        IL_007d:
        if (HexConverter.IsHexChar(num))
        {
            goto IL_0088;
        }
        goto IL_0136;
    }
References System.HexConverter.FromChar(), System.HexConverter.IsHexChar(), System.Number.IsWhite(), System.Number.TrailingZeros(), and System.value.
Referenced by System.Number.TryParseInt64(), and System.Number.TryParseUInt64().