Terraria: System.Number.RoundNumber
RoundNumber()
static unsafe void System.Number.RoundNumber (ref NumberBuffer number, int pos, bool isCorrectlyRounded) inline static package
Definition at line 3379 of file Number.cs.
    {
        byte* digitsPointer = number.GetDigitsPointer();
        int j;
        for (j = 0; j < pos && digitsPointer[j] != 0; j++)
        {
        }
        if (j == pos && ShouldRoundUp(digitsPointer, j, number.Kind, isCorrectlyRounded))
        {
            while (j > 0 && digitsPointer[j - 1] == 57)
            {
                j--;
            }
            if (j > 0)
            {
                byte* num = digitsPointer + (j - 1);
                (*num)++;
            }
            else
            {
                number.Scale++;
                *digitsPointer = 49;
                j = 1;
            }
        }
        else
        {
            while (j > 0 && digitsPointer[j - 1] == 48)
            {
                j--;
            }
        }
        if (j == 0)
        {
            if (number.Kind != NumberBufferKind.FloatingPoint)
            {
                number.IsNegative = false;
            }
            number.Scale = 0;
        }
        digitsPointer[j] = 0;
        number.DigitsCount = j;
        unsafe static bool ShouldRoundUp(byte* dig, int i, NumberBufferKind numberKind, bool isCorrectlyRounded)
        {
            byte b = dig[i];
            if (b == 0 || isCorrectlyRounded)
            {
                return false;
            }
            return b >= 53;
        }
    }
References System.Number.ShouldRoundUp().
Referenced by System.Number.NumberToString(), System.Number.NumberToStringFormat(), and System.Buffers.Text.Utf8Formatter.TryFormat().