Terraria: System.Number.GetFloatingPointMaxDigitsAndPrecision
GetFloatingPointMaxDigitsAndPrecision()
static int System.Number.GetFloatingPointMaxDigitsAndPrecision (char fmt, ref int precision, NumberFormatInfo info, out bool isSignificantDigits) inline static private
Definition at line 1631 of file Number.cs.
    {
        if (fmt == '\0')
        {
            isSignificantDigits = true;
            return precision;
        }
        int result = precision;
        switch (fmt)
        {
        case 'C':
        case 'c':
            if (precision == -1)
            {
                precision = info.CurrencyDecimalDigits;
            }
            isSignificantDigits = false;
            break;
        case 'E':
        case 'e':
            if (precision == -1)
            {
                precision = 6;
            }
            precision++;
            isSignificantDigits = true;
            break;
        case 'F':
        case 'N':
        case 'f':
        case 'n':
            if (precision == -1)
            {
                precision = info.NumberDecimalDigits;
            }
            isSignificantDigits = false;
            break;
        case 'G':
        case 'g':
            if (precision == 0)
            {
                precision = -1;
            }
            isSignificantDigits = true;
            break;
        case 'P':
        case 'p':
            if (precision == -1)
            {
                precision = info.PercentDecimalDigits;
            }
            precision += 2;
            isSignificantDigits = false;
            break;
        case 'R':
        case 'r':
            precision = -1;
            isSignificantDigits = true;
            break;
        default:
            throw new FormatException(SR.Argument_BadFormatSpecifier);
        }
        return result;
    }
References System.SR.Argument_BadFormatSpecifier, and System.info.
Referenced by System.Number.FormatDouble(), System.Number.FormatHalf(), and System.Number.FormatSingle().