Terraria: System.Number.ParseHalf
ParseHalf()
static Half System.Number.ParseHalf (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info) inline static package
Definition at line 5631 of file Number.cs.
    {
        if (!TryParseHalf(value, styles, info, out var result))
        {
            ThrowOverflowOrFormatException(ParsingStatus.Failed);
        }
        return result;
    }
References System.info, System.Number.ThrowOverflowOrFormatException(), System.Number.TryParseHalf(), and System.value.
Referenced by System.Half.Parse(), System.Half.Parse(), System.Half.Parse(), System.Half.Parse(), and System.Half.Parse().