Terraria: System.Number.Int32ToDecStr
Int32ToDecStr()
static string System.Number.Int32ToDecStr (int value) inline static
Definition at line 2246 of file Number.cs.
    {
        if (value < 0)
        {
            return NegativeInt32ToDecStr(value, -1, NumberFormatInfo.CurrentInfo.NegativeSign);
        }
        return UInt32ToDecStr((uint)value);
    }
References System.Globalization.NumberFormatInfo.CurrentInfo, System.Number.NegativeInt32ToDecStr(), System.Number.UInt32ToDecStr(), and System.value.
Referenced by System.Int16.ToString(), System.Int32.ToString(), and System.SByte.ToString().