Terraria: System.Number.TryFormatDecimal
TryFormatDecimal()
static unsafe bool System.Number.TryFormatDecimal (decimal value, ReadOnlySpan< char > format, NumberFormatInfo info, Span< char > destination, out int charsWritten) inline static
Definition at line 1571 of file Number.cs.
    {
        int digits;
        char c = ParseFormatSpecifier(format, out digits);
        byte* digits2 = stackalloc byte[31];
        NumberBuffer number = new NumberBuffer(NumberBufferKind.Decimal, digits2, 31);
        DecimalToNumber(ref value, ref number);
        char* pointer = stackalloc char[32];
        ValueStringBuilder sb = new ValueStringBuilder(new Span<char>(pointer, 32));
        if (c != 0)
        {
            NumberToString(ref sb, ref number, c, digits, info);
        }
        else
        {
            NumberToStringFormat(ref sb, ref number, format, info);
        }
        return sb.TryCopyTo(destination, out charsWritten);
    }
References System.Number.DecimalToNumber(), System.destination, System.format, System.info, System.Number.NumberToString(), System.Number.NumberToStringFormat(), System.Number.ParseFormatSpecifier(), System.pointer, System.Text.ValueStringBuilder.TryCopyTo(), and System.value.
Referenced by System.Decimal.TryFormat().