Terraria: System.Number.Int64ToDecStr
Int64ToDecStr()
static string System.Number.Int64ToDecStr (long value) inline static
Definition at line 2475 of file Number.cs.
    {
        if (value < 0)
        {
            return NegativeInt64ToDecStr(value, -1, NumberFormatInfo.CurrentInfo.NegativeSign);
        }
        return UInt64ToDecStr((ulong)value, -1);
    }
References System.Globalization.NumberFormatInfo.CurrentInfo, System.Number.NegativeInt64ToDecStr(), System.Number.UInt64ToDecStr(), and System.value.
Referenced by System.Int64.ToString().