Terraria: System.Number.TryNumberToDecimal
TryNumberToDecimal()
static unsafe bool System.Number.TryNumberToDecimal (ref NumberBuffer number, ref decimal value) inline static package
Definition at line 5513 of file Number.cs.
    {
        byte* ptr = number.GetDigitsPointer();
        int num = number.Scale;
        bool isNegative = number.IsNegative;
        uint num2 = *ptr;
        if (num2 == 0)
        {
            value = new decimal(0, 0, 0, isNegative, (byte)Math.Clamp(-num, 0, 28));
            return true;
        }
        if (num > 29)
        {
            return false;
        }
        ulong num3 = 0uL;
        while (num > -28)
        {
            num--;
            num3 *= 10;
            num3 += num2 - 48;
            num2 = *(++ptr);
            if (num3 >= 1844674407370955161L)
            {
                break;
            }
            if (num2 != 0)
            {
                continue;
            }
            while (num > 0)
            {
                num--;
                num3 *= 10;
                if (num3 >= 1844674407370955161L)
                {
                    break;
                }
            }
            break;
        }
        uint num4 = 0u;
        while ((num > 0 || (num2 != 0 && num > -28)) && (num4 < 429496729 || (num4 == 429496729 && (num3 < 11068046444225730969uL || (num3 == 11068046444225730969uL && num2 <= 53)))))
        {
            ulong num5 = (ulong)(uint)num3 * 10uL;
            ulong num6 = (ulong)((long)(uint)(num3 >> 32) * 10L) + (num5 >> 32);
            num3 = (uint)num5 + (num6 << 32);
            num4 = (uint)(int)(num6 >> 32) + num4 * 10;
            if (num2 != 0)
            {
                num2 -= 48;
                num3 += num2;
                if (num3 < num2)
                {
                    num4++;
                }
                num2 = *(++ptr);
            }
            num--;
        }
        if (num2 >= 53)
        {
            if (num2 == 53 && (num3 & 1) == 0L)
            {
                num2 = *(++ptr);
                bool flag = !number.HasNonZeroTail;
                while (num2 != 0 && flag)
                {
                    flag = flag && num2 == 48;
                    num2 = *(++ptr);
                }
                if (flag)
                {
                    goto IL_01a8;
                }
            }
            if (++num3 == 0L && ++num4 == 0)
            {
                num3 = 11068046444225730970uL;
                num4 = 429496729u;
                num++;
            }
        }
        goto IL_01a8;
        IL_01a8:
        if (num > 0)
        {
            return false;
        }
        if (num <= -29)
        {
            value = new decimal(0, 0, 0, isNegative, 28);
        }
        else
        {
            value = new decimal((int)num3, (int)(num3 >> 32), (int)num4, isNegative, (byte)(-num));
        }
        return true;
    }
References System.Math.Clamp(), System.L, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), and System.Number.TryParseDecimal().