Terraria: System.Number.FormatHalf
FormatHalf() [1/2]
static string System.Number.FormatHalf (Half value, string format, NumberFormatInfo info) inline static
Definition at line 1803 of file Number.cs.
    {
        Span<char> initialBuffer = stackalloc char[32];
        ValueStringBuilder sb = new ValueStringBuilder(initialBuffer);
        return FormatHalf(ref sb, value, format, info) ?? sb.ToString();
    }
References System.format, System.Number.FormatHalf(), System.info, System.Text.ValueStringBuilder.ToString(), and System.value.
Referenced by System.Number.FormatHalf(), System.Half.ToString(), System.Half.ToString(), System.Half.ToString(), System.Half.ToString(), and System.Number.TryFormatHalf().