Terraria: System.Number.NumberToDoubleFloatingPointBits
NumberToDoubleFloatingPointBits()
static unsafe ulong System.Number.NumberToDoubleFloatingPointBits (ref NumberBuffer number, in FloatingPointInfo info) inline static private
Definition at line 3693 of file Number.cs.
    {
        uint digitsCount = (uint)number.DigitsCount;
        uint num = (uint)Math.Max(0, number.Scale);
        uint num2 = Math.Min(num, digitsCount);
        uint num3 = digitsCount - num2;
        uint num4 = (uint)Math.Abs(number.Scale - num2 - num3);
        byte* digitsPointer = number.GetDigitsPointer();
        if (digitsCount <= 15 && num4 <= 22)
        {
            double num5 = DigitsToUInt64(digitsPointer, (int)digitsCount);
            double num6 = s_Pow10DoubleTable[num4];
            num5 = ((num3 == 0) ? (num5 * num6) : (num5 / num6));
            return BitConverter.DoubleToUInt64Bits(num5);
        }
        return NumberToFloatingPointBitsSlow(ref number, in info, num, num2, num3);
    }
References System.Math.Abs(), System.Number.DigitsToUInt64(), System.BitConverter.DoubleToUInt64Bits(), System.info, System.Math.Max(), System.Math.Min(), System.Number.NumberToFloatingPointBitsSlow(), and System.Number.s_Pow10DoubleTable.
Referenced by System.Number.NumberToDouble().