Terraria: System.Number.Dragon4Single
Dragon4Single()
static void System.Number.Dragon4Single (float value, int cutoffNumber, bool isSignificantDigits, ref NumberBuffer number) inline static
Definition at line 1312 of file Number.cs.
    {
        float num = (float.IsNegative(value) ? (0f - value) : value);
        int exponent;
        uint num2 = ExtractFractionAndBiasedExponent(value, out exponent);
        bool hasUnequalMargins = false;
        uint mantissaHighBitIdx;
        if (num2 >> 23 != 0)
        {
            mantissaHighBitIdx = 23u;
            hasUnequalMargins = num2 == 8388608;
        }
        else
        {
            mantissaHighBitIdx = (uint)BitOperations.Log2(num2);
        }
        int decimalExponent;
        int num3 = (int)Dragon4(num2, exponent, mantissaHighBitIdx, hasUnequalMargins, cutoffNumber, isSignificantDigits, number.Digits, out decimalExponent);
        number.Scale = decimalExponent + 1;
        number.Digits[num3] = 0;
        number.DigitsCount = num3;
    }
References System.Number.Dragon4(), System.Number.ExtractFractionAndBiasedExponent(), System.Numerics.BitOperations.Log2(), and System.value.
Referenced by System.Number.FormatSingle().