Terraria: System.Number.TryParseInt32
TryParseInt32()
static ParsingStatus System.Number.TryParseInt32 (ReadOnlySpan< char > value, NumberStyles styles, NumberFormatInfo info, out int result) inline static package
Definition at line 4251 of file Number.cs.
    {
        if ((styles & ~NumberStyles.Integer) == 0)
        {
            return TryParseInt32IntegerStyle(value, styles, info, out result);
        }
        if ((styles & NumberStyles.AllowHexSpecifier) != 0)
        {
            result = 0;
            return TryParseUInt32HexNumberStyle(value, styles, out Unsafe.As<int, uint>(ref result));
        }
        return TryParseInt32Number(value, styles, info, out result);
    }
References System.info, System.Number.TryParseInt32IntegerStyle(), System.Number.TryParseInt32Number(), System.Number.TryParseUInt32HexNumberStyle(), and System.value.
Referenced by System.Int16.Parse(), System.SByte.Parse(), System.Number.ParseInt32(), System.Int32.TryParse(), System.Int32.TryParse(), System.SByte.TryParse(), and System.Int16.TryParse().