Terraria: System.Number.Low32
Low32()
static uint System.Number.Low32 (ulong value) inline static private
Definition at line 3493 of file Number.cs.
    {
        return (uint)value;
    }
References System.value.
Referenced by System.Number.Int64ToHexStr(), System.Number.Int64ToNumber(), System.Number.NegativeInt64ToDecStr(), System.Number.TryInt64ToHexStr(), System.Number.TryNegativeInt64ToDecStr(), System.Number.TryUInt64ToDecStr(), System.Number.UInt64ToDecStr(), and System.Number.UInt64ToNumber().