Terraria: System.Number.FormatHalf
FormatHalf() [2/2]
static unsafe string System.Number.FormatHalf (ref ValueStringBuilder sb, Half value, ReadOnlySpan< char > format, NumberFormatInfo info) inline static private
Definition at line 1810 of file Number.cs.
    {
        if (!Half.IsFinite(value))
        {
            if (Half.IsNaN(value))
            {
                return info.NaNSymbol;
            }
            if (!Half.IsNegative(value))
            {
                return info.PositiveInfinitySymbol;
            }
            return info.NegativeInfinitySymbol;
        }
        int digits;
        char c = ParseFormatSpecifier(format, out digits);
        byte* digits2 = stackalloc byte[21];
        if (c == '\0')
        {
            digits = 5;
        }
        NumberBuffer number = new NumberBuffer(NumberBufferKind.FloatingPoint, digits2, 21);
        number.IsNegative = Half.IsNegative(value);
        bool isSignificantDigits;
        int nMaxDigits = GetFloatingPointMaxDigitsAndPrecision(c, ref digits, info, out isSignificantDigits);
        if (value != default(Half) && (!isSignificantDigits || !Grisu3.TryRunHalf(value, digits, ref number)))
        {
            Dragon4Half(value, digits, isSignificantDigits, ref number);
        }
        if (c != 0)
        {
            if (digits == -1)
            {
                nMaxDigits = Math.Max(number.DigitsCount, 5);
            }
            NumberToString(ref sb, ref number, c, nMaxDigits, info);
        }
        else
        {
            NumberToStringFormat(ref sb, ref number, format, info);
        }
        return null;
    }
References System.Number.NumberBuffer.DigitsCount, System.Number.Dragon4Half(), System.format, System.Number.GetFloatingPointMaxDigitsAndPrecision(), System.info, System.Half.IsFinite(), System.Half.IsNaN(), System.Half.IsNegative(), System.Math.Max(), System.Number.NumberToString(), System.Number.NumberToStringFormat(), System.Number.ParseFormatSpecifier(), System.Number.Grisu3.TryRunHalf(), and System.value.