Terraria: System.Number.TryFormatInt64
TryFormatInt64()
static bool System.Number.TryFormatInt64 (long value, ReadOnlySpan< char > format, IFormatProvider provider, Span< char > destination, out int charsWritten) inline static
Definition at line 2099 of file Number.cs.
    {
        if (format.Length == 0)
        {
            if (value < 0)
            {
                return TryNegativeInt64ToDecStr(value, -1, NumberFormatInfo.GetInstance(provider).NegativeSign, destination, out charsWritten);
            }
            return TryUInt64ToDecStr((ulong)value, -1, destination, out charsWritten);
        }
        return TryFormatInt64Slow(value, format, provider, destination, out charsWritten);
        unsafe static bool TryFormatInt64Slow(long value, ReadOnlySpan<char> format, IFormatProvider provider, Span<char> destination, out int charsWritten)
        {
            int digits;
            char c = ParseFormatSpecifier(format, out digits);
            char c2 = (char)(c & 0xFFDFu);
            if ((c2 == 'G') ? (digits < 1) : (c2 == 'D'))
            {
                if (value < 0)
                {
                    return TryNegativeInt64ToDecStr(value, digits, NumberFormatInfo.GetInstance(provider).NegativeSign, destination, out charsWritten);
                }
                return TryUInt64ToDecStr((ulong)value, digits, destination, out charsWritten);
            }
            if (c2 == 'X')
            {
                return TryInt64ToHexStr(value, GetHexBase(c), digits, destination, out charsWritten);
            }
            NumberFormatInfo instance = NumberFormatInfo.GetInstance(provider);
            byte* digits2 = stackalloc byte[20];
            NumberBuffer number = new NumberBuffer(NumberBufferKind.Integer, digits2, 20);
            Int64ToNumber(value, ref number);
            char* pointer = stackalloc char[32];
            ValueStringBuilder sb = new ValueStringBuilder(new Span<char>(pointer, 32));
            if (c != 0)
            {
                NumberToString(ref sb, ref number, c, digits, instance);
            }
            else
            {
                NumberToStringFormat(ref sb, ref number, format, instance);
            }
            return sb.TryCopyTo(destination, out charsWritten);
        }
    }
References System.destination, System.format, System.Number.GetHexBase(), System.Globalization.NumberFormatInfo.GetInstance(), System.Number.Int64ToNumber(), System.Number.NumberToString(), System.Number.NumberToStringFormat(), System.Number.ParseFormatSpecifier(), System.pointer, System.Text.ValueStringBuilder.TryCopyTo(), System.Number.TryInt64ToHexStr(), System.Number.TryNegativeInt64ToDecStr(), System.Number.TryUInt64ToDecStr(), and System.value.
Referenced by System.Int64.TryFormat().