Terraria: System.Number.NumberToString
NumberToString()
static void System.Number.NumberToString (ref ValueStringBuilder sb, ref NumberBuffer number, char format, int nMaxDigits, NumberFormatInfo info) inline static package
Definition at line 2715 of file Number.cs.
    {
        bool isCorrectlyRounded = number.Kind == NumberBufferKind.FloatingPoint;
        bool bSuppressScientific;
        switch (format)
        {
        case 'C':
        case 'c':
            if (nMaxDigits < 0)
            {
                nMaxDigits = info.CurrencyDecimalDigits;
            }
            RoundNumber(ref number, number.Scale + nMaxDigits, isCorrectlyRounded);
            FormatCurrency(ref sb, ref number, nMaxDigits, info);
            return;
        case 'F':
        case 'f':
            if (nMaxDigits < 0)
            {
                nMaxDigits = info.NumberDecimalDigits;
            }
            RoundNumber(ref number, number.Scale + nMaxDigits, isCorrectlyRounded);
            if (number.IsNegative)
            {
                sb.Append(info.NegativeSign);
            }
            FormatFixed(ref sb, ref number, nMaxDigits, null, info.NumberDecimalSeparator, null);
            return;
        case 'N':
        case 'n':
            if (nMaxDigits < 0)
            {
                nMaxDigits = info.NumberDecimalDigits;
            }
            RoundNumber(ref number, number.Scale + nMaxDigits, isCorrectlyRounded);
            FormatNumber(ref sb, ref number, nMaxDigits, info);
            return;
        case 'E':
        case 'e':
            if (nMaxDigits < 0)
            {
                nMaxDigits = 6;
            }
            nMaxDigits++;
            RoundNumber(ref number, nMaxDigits, isCorrectlyRounded);
            if (number.IsNegative)
            {
                sb.Append(info.NegativeSign);
            }
            FormatScientific(ref sb, ref number, nMaxDigits, info, format);
            return;
        case 'G':
        case 'g':
            bSuppressScientific = false;
            if (nMaxDigits < 1)
            {
                if (number.Kind == NumberBufferKind.Decimal && nMaxDigits == -1)
                {
                    bSuppressScientific = true;
                    if (number.Digits[0] != 0)
                    {
                        goto IL_0189;
                    }
                    goto IL_019e;
                }
                nMaxDigits = number.DigitsCount;
            }
            RoundNumber(ref number, nMaxDigits, isCorrectlyRounded);
            goto IL_0189;
        case 'P':
        case 'p':
            if (nMaxDigits < 0)
            {
                nMaxDigits = info.PercentDecimalDigits;
            }
            number.Scale += 2;
            RoundNumber(ref number, number.Scale + nMaxDigits, isCorrectlyRounded);
            FormatPercent(ref sb, ref number, nMaxDigits, info);
            return;
        case 'R':
        case 'r':
            {
                if (number.Kind != NumberBufferKind.FloatingPoint)
                {
                    break;
                }
                format = (char)(format - 11);
                goto case 'G';
            }
            IL_0189:
            if (number.IsNegative)
            {
                sb.Append(info.NegativeSign);
            }
            goto IL_019e;
            IL_019e:
            FormatGeneral(ref sb, ref number, nMaxDigits, info, (char)(format - 2), bSuppressScientific);
            return;
        }
        throw new FormatException(SR.Argument_BadFormatSpecifier);
    }
References System.SR.Argument_BadFormatSpecifier, System.format, System.Number.FormatCurrency(), System.Number.FormatFixed(), System.Number.FormatGeneral(), System.Number.FormatNumber(), System.Number.FormatPercent(), System.Number.FormatScientific(), System.info, and System.Number.RoundNumber().
Referenced by System.Number.FormatDecimal(), System.Number.FormatDouble(), System.Number.FormatHalf(), System.Number.FormatInt32(), System.Number.FormatInt64(), System.Number.FormatSingle(), System.Number.FormatUInt32(), System.Number.FormatUInt64(), System.Number.TryFormatDecimal(), System.Number.TryFormatInt32(), System.Number.TryFormatInt64(), System.Number.TryFormatUInt32(), and System.Number.TryFormatUInt64().