Terraria: System.Number.UInt32ToDecChars
UInt32ToDecChars() [1/2]
static unsafe byte * System.Number.UInt32ToDecChars (byte * bufferEnd, uint value, int digits) inline static package
Definition at line 2360 of file Number.cs.
    {
        while (--digits >= 0 || value != 0)
        {
            uint num;
            (value, num) = Math.DivRem(value, 10u);
            *(--bufferEnd) = (byte)(num + 48);
        }
        return bufferEnd;
    }
References System.Math.DivRem(), and System.value.
Referenced by System.Number.DecimalToNumber(), System.Number.FormatExponent(), System.Number.Int32ToNumber(), System.Number.Int64ToNumber(), System.Number.NegativeInt32ToDecStr(), System.Number.NegativeInt64ToDecStr(), System.Number.TryNegativeInt32ToDecStr(), System.Number.TryNegativeInt64ToDecStr(), System.Number.TryUInt32ToDecStr(), System.Number.TryUInt64ToDecStr(), System.Number.UInt32ToDecStr(), System.Number.UInt32ToNumber(), System.Number.UInt64ToDecStr(), and System.Number.UInt64ToNumber().