Terraria: System.Number.TryFormatDouble
TryFormatDouble()
static bool System.Number.TryFormatDouble (double value, ReadOnlySpan< char > format, NumberFormatInfo info, Span< char > destination, out int charsWritten) inline static
Definition at line 1619 of file Number.cs.
    {
        Span<char> initialBuffer = stackalloc char[32];
        ValueStringBuilder sb = new ValueStringBuilder(initialBuffer);
        string text = FormatDouble(ref sb, value, format, info);
        if (text == null)
        {
            return sb.TryCopyTo(destination, out charsWritten);
        }
        return TryCopyTo(text, destination, out charsWritten);
    }
References System.destination, System.format, System.Number.FormatDouble(), System.info, System.text, System.Text.ValueStringBuilder.TryCopyTo(), System.Number.TryCopyTo(), and System.value.
Referenced by System.Double.TryFormat().