Terraria: System.Xml.Schema.XmlSchemaDatatype.ConcatenatedToString
ConcatenatedToString()
static string System.Xml.Schema.XmlSchemaDatatype.ConcatenatedToString (object value) inline static package
Definition at line 162 of file XmlSchemaDatatype.cs.
    {
        Type type = value.GetType();
        string result = string.Empty;
        if (!(type == typeof(IEnumerable)) || !(type != typeof(string)))
        {
            result = ((!(value is IFormattable)) ? value.ToString() : ((IFormattable)value).ToString("", CultureInfo.InvariantCulture));
        }
        else
        {
            StringBuilder stringBuilder = new StringBuilder();
            IEnumerator enumerator = (value as IEnumerable).GetEnumerator();
            if (enumerator.MoveNext())
            {
                stringBuilder.Append('{');
                object current = enumerator.Current;
                if (current is IFormattable)
                {
                    stringBuilder.Append(((IFormattable)current).ToString("", CultureInfo.InvariantCulture));
                }
                else
                {
                    stringBuilder.Append(current.ToString());
                }
                while (enumerator.MoveNext())
                {
                    stringBuilder.Append(" , ");
                    current = enumerator.Current;
                    if (current is IFormattable)
                    {
                        stringBuilder.Append(((IFormattable)current).ToString("", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        stringBuilder.Append(current.ToString());
                    }
                }
                stringBuilder.Append('}');
                result = stringBuilder.ToString();
            }
        }
        return result;
    }
References System.Collections.IEnumerator.Current, System.Xml.Dictionary, System.Type.GetType(), System.Globalization.CultureInfo.InvariantCulture, System.type, and System.value.
Referenced by System.Xml.Schema.XmlSchemaValidator.CheckAttributeValue(), and System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue().