Terraria: System.Xml.Schema.XmlSchemaDatatype.XdrCanonizeUri
XdrCanonizeUri()
static string System.Xml.Schema.XmlSchemaDatatype.XdrCanonizeUri (string uri, XmlNameTable nameTable, SchemaNames schemaNames) inline static package
Definition at line 226 of file XmlSchemaDatatype.cs.
    {
        int num = 5;
        bool flag = false;
        if (uri.Length > 5 && uri.StartsWith("uuid:", StringComparison.Ordinal))
        {
            flag = true;
        }
        else if (uri.Length > 9 && uri.StartsWith("urn:uuid:", StringComparison.Ordinal))
        {
            flag = true;
            num = 9;
        }
        string text = ((!flag) ? uri : nameTable.Add(string.Concat(uri.AsSpan(0, num), uri.Substring(num, uri.Length - num).ToUpperInvariant())));
        if (Ref.Equal(schemaNames.NsDataTypeAlias, text) || Ref.Equal(schemaNames.NsDataTypeOld, text))
        {
            text = schemaNames.NsDataType;
        }
        else if (Ref.Equal(schemaNames.NsXdrAlias, text))
        {
            text = schemaNames.NsXdr;
        }
        return text;
    }
References System.Xml.Dictionary, System.Xml.Ref.Equal(), and System.text.
Referenced by System.Xml.Schema.XdrBuilder.ProcessAttribute(), System.Xml.Schema.XdrBuilder.ProcessElement(), System.Xml.Schema.XdrValidator.QualifiedName(), System.Xml.Schema.SchemaNames.SchemaTypeFromRoot(), and System.Xml.Schema.XdrValidator.ValidateElement().