Terraria: System.Data.DataCommonEventSource.EnterScope
EnterScope() [2/2]
long System.Data.DataCommonEventSource.EnterScope (string message) inline package
Definition at line 74 of file DataCommonEventSource.cs.
    {
        long num = 0L;
        if (Log.IsEnabled())
        {
            num = Interlocked.Increment(ref s_nextScopeId);
            EnterScope(num, message);
        }
        return num;
    }
References System.Data.DataCommonEventSource.EnterScope(), System.Threading.Interlocked.Increment(), System.L, System.Data.DataCommonEventSource.Log, and System.Data.DataCommonEventSource.s_nextScopeId.
Referenced by System.Data.DataCommonEventSource.EnterScope(), System.Data.DataCommonEventSource.EnterScope< T1 >(), System.Data.DataCommonEventSource.EnterScope< T1, T2 >(), System.Data.DataCommonEventSource.EnterScope< T1, T2, T3 >(), and System.Data.DataCommonEventSource.EnterScope< T1, T2, T3, T4 >().