Terraria: System.Data.DataCommonEventSource.Log
Log
readonly DataCommonEventSource System.Data.DataCommonEventSource.Log = new DataCommonEventSource() static package
Definition at line 9 of file DataCommonEventSource.cs.
Referenced by System.Data.DataColumn.DataColumn(), System.Data.DataRelation.DataRelation(), System.Data.DataSet.DataSet(), System.Data.DataTable.DataTable(), System.Data.DataTableCollection.DataTableCollection(), System.Data.DataView.DataView(), System.Data.DataView.DataView(), System.Data.DataView.DataView(), System.Data.Index.Index(), System.Data.DataRow.AcceptChanges(), System.Data.DataSet.AcceptChanges(), System.Data.DataTable.AcceptChanges(), System.Data.Index.AcceptRecord(), System.Data.DataRelationCollection.Add(), System.Data.DataTableCollection.Add(), System.Data.DataRelationCollection.AddCore(), System.Data.DataView.AddNew(), System.Data.DataTableCollection.AddRange(), System.Data.Index.AddRef(), System.Data.DataTable.BeginLoadData(), System.Data.DataTableCollection.CanRemove(), System.Data.DataRelation.CheckNestedRelations(), System.Data.Common.DbConnectionStringBuilder.Clear(), System.Data.DataRelationCollection.Clear(), System.Data.DataSet.Clear(), System.Data.DataTableCollection.Clear(), System.Data.DataTable.Clear(), System.Data.DataSet.Clone(), System.Data.DataTable.Clone(), System.Data.DataRelation.Clone(), System.Data.DataSet.Copy(), System.Data.DataTable.Copy(), System.Data.Common.DbConnectionStringBuilder.CopyTo(), System.Data.DataRelation.Create(), System.Data.DataSet.CreateDataReader(), System.Data.Common.DataAdapter.CreateTableMappings(), System.Data.DataView.Delete(), System.Data.Index.DeleteRecord(), System.Data.DataSet.EnableConstraints(), System.Data.DataTable.EndLoadData(), System.Data.DataCommonEventSource.EnterScope(), System.Data.DataCommonEventSource.EnterScope< T1 >(), System.Data.DataCommonEventSource.EnterScope< T1, T2 >(), System.Data.DataCommonEventSource.EnterScope< T1, T2, T3 >(), System.Data.DataCommonEventSource.EnterScope< T1, T2, T3, T4 >(), System.Data.Common.DbConnectionStringBuilder.EquivalentTo(), System.Data.Common.DbDataAdapter.Fill(), System.Data.Common.DbDataAdapter.Fill(), System.Data.Common.DbDataAdapter.Fill(), System.Data.Common.DbDataAdapter.Fill(), System.Data.Common.DataAdapter.Fill(), System.Data.Common.DbDataAdapter.Fill(), System.Data.Common.DbDataAdapter.Fill(), System.Data.Common.DataAdapter.Fill(), System.Data.Common.DbDataAdapter.Fill(), System.Data.Common.DbDataAdapter.Fill(), System.Data.Common.DbDataAdapter.FillSchema(), System.Data.Common.DbDataAdapter.FillSchema(), System.Data.Common.DbDataAdapter.FillSchema(), System.Data.Common.DataAdapter.FillSchema(), System.Data.Common.DbDataAdapter.FillSchema(), System.Data.Common.DataAdapter.FillSchema(), System.Data.Common.DbDataAdapter.FillSchema(), System.Data.DataView.FindRowsByKey(), System.Data.DataView.FinishAddNew(), System.Data.Index.FireResetEvent(), System.Data.DataTable.GetChanges(), System.Data.DataSet.GetChanges(), System.Data.DataTable.GetChanges(), System.Data.Common.DbConnectionStringBuilder.GetEnumerator(), System.Data.Common.DbConnectionStringBuilder.GetProperties(), System.Data.Common.DbConnectionStringBuilder.GetProperties(), System.Data.DataSet.GetXml(), System.Data.DataSet.GetXmlSchema(), System.Data.DataSet.HasChanges(), System.Data.DataTable.ImportRow(), System.Data.DataSet.InferSchema(), System.Data.DataSet.InferXmlSchema(), System.Data.Index.InsertRecord(), System.Data.DataTable.InsertRow(), System.Data.DataTable.Load(), System.Data.DataSet.Load(), System.Data.DataTable.LoadDataRow(), System.Data.DataTable.LoadDataRow(), System.Data.DataSet.Merge(), System.Data.DataSet.Merge(), System.Data.DataSet.Merge(), System.Data.DataSet.Merge(), System.Data.DataSet.Merge(), System.Data.DataSet.Merge(), System.Data.DataSet.Merge(), System.Data.DataTable.Merge(), System.Data.DataRelationCollection.OnCollectionChanged(), System.Data.DataTableCollection.OnCollectionChanged(), System.Data.DataRelationCollection.OnCollectionChanging(), System.Data.DataTableCollection.OnCollectionChanging(), System.Data.DataTable.OnColumnChanged(), System.Data.DataTable.OnColumnChanging(), System.Data.DataTable.OnInitialized(), System.Data.DataView.OnListChanged(), System.Data.Index.OnListChanged(), System.Data.DataRelation.OnPropertyChanging(), System.Data.DataTable.OnPropertyChanging(), System.Data.DataTable.OnRowChanged(), System.Data.DataTable.OnRowChanging(), System.Data.DataTable.OnRowDeleted(), System.Data.DataTable.OnRowDeleting(), System.Data.DataTable.OnTableCleared(), System.Data.DataTable.OnTableClearing(), System.Data.DataTable.OnTableNewRow(), System.Data.DataSet.ReadXml(), System.Data.DataTable.ReadXml(), System.Data.DataSet.ReadXml(), System.Data.DataSet.ReadXmlDiffgram(), System.Data.DataSet.ReadXmlSchema(), System.Data.DataTable.ReadXmlSchema(), System.Data.Index.RecordChanged(), System.Data.Index.RecordChanged(), System.Data.Index.RecordStateChanged(), System.Data.Index.RecordStateChanged(), System.Data.DataRelationCollection.RegisterName(), System.Data.DataTableCollection.RegisterName(), System.Data.DataRow.RejectChanges(), System.Data.DataSet.RejectChanges(), System.Data.DataTable.RejectChanges(), System.Data.DataRelationCollection.Remove(), System.Data.DataTableCollection.Remove(), System.Data.Common.DbConnectionStringBuilder.Remove(), System.Data.DataTableCollection.Remove(), System.Data.DataTableCollection.RemoveAt(), System.Data.DataRelationCollection.RemoveCore(), System.Data.DataView.RemoveFilter(), System.Data.Index.RemoveRef(), System.Data.DataView.RemoveSort(), System.Data.DataSet.Reset(), System.Data.DataTable.Reset(), System.Data.Index.Reset(), System.Data.DataTable.RestoreIndexEvents(), System.Data.DataTable.Select(), System.Data.DataTable.Select(), System.Data.DataTable.Select(), System.Data.DataTable.Select(), System.Data.DataRow.SetColumnError(), System.Data.DataView.SetIndex2(), System.Data.DataTable.SuspendIndexEvents(), System.Data.DataView.ToTable(), System.Data.DataCommonEventSource.Trace< T0 >(), System.Data.DataCommonEventSource.Trace< T0, T1 >(), System.Data.DataCommonEventSource.Trace< T0, T1, T2 >(), System.Data.DataCommonEventSource.Trace< T0, T1, T2, T3 >(), System.Data.DataCommonEventSource.Trace< T0, T1, T2, T3, T4 >(), System.Data.DataCommonEventSource.Trace< T0, T1, T2, T3, T4, T5, T6 >(), System.Data.Common.ADP.TraceException(), System.Data.ExceptionBuilder.TraceException(), System.Data.DataRelationCollection.UnregisterName(), System.Data.DataTableCollection.UnregisterName(), System.Data.Common.DbDataAdapter.Update(), System.Data.Common.DbDataAdapter.Update(), System.Data.Common.DbDataAdapter.Update(), System.Data.Common.DbDataAdapter.Update(), System.Data.DataView.UpdateIndex(), System.Data.DataSet.ValidateCaseConstraint(), System.Data.DataSet.ValidateLocaleConstraint(), System.Data.DataSet.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataSet.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataSet.WriteXmlSchema(), and System.Data.DataTable.WriteXmlSchema().