Terraria: System.Xml.XmlNamespaceManager.LookupNamespace
LookupNamespace()
virtual ? string System.Xml.XmlNamespaceManager.LookupNamespace (string prefix) inline virtual inherited
Implements System.Xml.IXmlNamespaceResolver.
Reimplemented in MS.Internal.Xml.XPath.CompiledXpathExpr.UndefinedXsltContext, System.Xml.Schema.DtdValidator.NamespaceManager, System.Xml.Schema.SchemaNamespaceManager, System.Xml.Schema.XsdBuilder.BuilderNamespaceManager, System.Xml.Xsl.XsltOld.XsltCompileContext, and System.Xml.XmlTextReaderImpl.NoNamespaceManager.
Definition at line 227 of file XmlNamespaceManager.cs.
    {
        int num = LookupNamespaceDecl(prefix);
        if (num != -1)
        {
            return _nsdecls[num].uri;
        }
        return null;
    }
References System.Xml.XmlNamespaceManager._nsdecls, System.Xml.XmlNamespaceManager.LookupNamespaceDecl(), System.prefix, and System.Xml.XmlNamespaceManager.NamespaceDeclaration.uri.
Referenced by System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal(), System.Xml.Xsl.Runtime.XmlQueryOutput.CheckAttributePrefix(), System.Xml.Schema.XmlSchemaInference.InferSchema1(), System.Xml.XmlTextReaderImpl.InitFragmentReader(), System.Xml.Xsl.XsltOld.XsltCompileContext.FuncKey.Invoke(), System.Xml.Schema.Parser.LoadElementNode(), System.Xml.XmlTextReaderImpl.LookupNamespace(), System.Xml.Schema.XsdBuilder.BuilderNamespaceManager.LookupNamespace(), System.Xml.DocumentSchemaValidator.LookupNamespace(), System.Xml.DocumentXmlWriter.LookupNamespace(), System.Xml.XmlSubtreeReader.LookupNamespace(), System.Xml.XmlTextReaderImpl.LookupNamespace(), System.Xml.XsdValidatingReader.LookupNamespace(), System.Xml.XmlNamespaceManager.LookupPrefix(), System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlTextReaderImpl.SetupFromParserContext(), MS.Internal.Xml.XPath.BaseAxisQuery.SetXsltContext(), System.Xml.Schema.XmlSchema.Write(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclaration(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclarationUnchecked().