Terraria: System.Xml.XmlNamespaceManager.AddNamespace
AddNamespace()
virtual void System.Xml.XmlNamespaceManager.AddNamespace (string prefix, string uri) inline virtual inherited
Reimplemented in System.Xml.XmlTextReaderImpl.NoNamespaceManager.
Definition at line 102 of file XmlNamespaceManager.cs.
    {
        if (uri == null)
        {
            throw new ArgumentNullException("uri");
        }
        if (prefix == null)
        {
            throw new ArgumentNullException("prefix");
        }
        prefix = _nameTable.Add(prefix);
        uri = _nameTable.Add(uri);
        if (Ref.Equal(_xml, prefix) && !uri.Equals("http://www.w3.org/XML/1998/namespace"))
        {
            throw new ArgumentException(System.SR.Xml_XmlPrefix);
        }
        if (Ref.Equal(_xmlNs, prefix))
        {
            throw new ArgumentException(System.SR.Xml_XmlnsPrefix);
        }
        int num = LookupNamespaceDecl(prefix);
        int previousNsIndex = -1;
        if (num != -1)
        {
            if (_nsdecls[num].scopeId == _scopeId)
            {
                _nsdecls[num].uri = uri;
                return;
            }
            previousNsIndex = num;
        }
        if (_lastDecl == _nsdecls.Length - 1)
        {
            NamespaceDeclaration[] array = new NamespaceDeclaration[_nsdecls.Length * 2];
            Array.Copy(_nsdecls, array, _nsdecls.Length);
            _nsdecls = array;
        }
        _nsdecls[++_lastDecl].Set(prefix, uri, _scopeId, previousNsIndex);
        if (_useHashtable)
        {
            _hashTable[prefix] = _lastDecl;
        }
        else if (_lastDecl >= 16)
        {
            _hashTable = new Dictionary<string, int>(_lastDecl);
            for (int i = 0; i <= _lastDecl; i++)
            {
                _hashTable[_nsdecls[i].prefix] = i;
            }
            _useHashtable = true;
        }
    }
References System.Xml.XmlNamespaceManager._hashTable, System.Xml.XmlNamespaceManager._lastDecl, System.Xml.XmlNamespaceManager._nameTable, System.Xml.XmlNamespaceManager._nsdecls, System.Xml.XmlNamespaceManager._scopeId, System.Xml.XmlNamespaceManager._useHashtable, System.Xml.XmlNamespaceManager._xml, System.Xml.XmlNamespaceManager._xmlNs, System.Xml.XmlNameTable.Add(), System.Xml.ArgumentException, System.array, System.Array.Copy(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.XmlNamespaceManager.LookupNamespaceDecl(), System.prefix, System.Xml.XmlNamespaceManager.NamespaceDeclaration.prefix, System.Xml.XmlNamespaceManager.NamespaceDeclaration.Set(), System.Xml.XmlNamespaceManager.NamespaceDeclaration.uri, System.SR.Xml_XmlnsPrefix, and System.SR.Xml_XmlPrefix.
Referenced by System.Xml.Schema.XmlSchemaInference.XmlSchemaInference(), System.Xml.Schema.XmlSchemaInference.AddAttribute(), System.Xml.Xsl.Runtime.XmlQueryOutput.AddNamespace(), System.Xml.XmlSubtreeReader.AddNamespace(), System.Xml.XmlTextReaderImpl.AddNamespace(), System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.Analyze(), System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.CheckNamespaceInScope(), System.Xml.Schema.Parser.CreateXmlNsAttribute(), System.Xml.Schema.Parser.LoadElementNode(), System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.XsdValidatingReader.ProcessElementEvent(), System.Xml.XsdValidatingReader.ProcessElementEventAsync(), System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.Schema.XsdValidator.ProcessXsiAttributes(), System.Xml.Schema.XNodeValidator.PushAncestorsAndSelf(), System.Xml.Schema.XNodeValidator.PushElement(), System.Runtime.Serialization.XPathQueryGenerator.ExportContext.SetNamespace(), System.Xml.Schema.XdrValidator.ThoroughGetElementDecl(), System.Xml.DocumentSchemaValidator.ValidateElement(), and System.Xml.DocumentSchemaValidator.ValidateSingleElement().