Terraria: System.Xml.XmlNamespaceManager.GetNamespacesInScope
GetNamespacesInScope()
virtual IDictionary< string, string > System.Xml.XmlNamespaceManager.GetNamespacesInScope (XmlNamespaceScope scope) inline virtual inherited
Implements System.Xml.IXmlNamespaceResolver.
Reimplemented in System.Xml.XmlTextReaderImpl.NoNamespaceManager.
Definition at line 187 of file XmlNamespaceManager.cs.
    {
        int i = 0;
        switch (scope)
        {
        case XmlNamespaceScope.All:
            i = 2;
            break;
        case XmlNamespaceScope.ExcludeXml:
            i = 3;
            break;
        case XmlNamespaceScope.Local:
            i = _lastDecl;
            while (_nsdecls[i].scopeId == _scopeId)
            {
                i--;
            }
            i++;
            break;
        }
        Dictionary<string, string> dictionary = new Dictionary<string, string>(_lastDecl - i + 1);
        for (; i <= _lastDecl; i++)
        {
            string prefix = _nsdecls[i].prefix;
            string uri = _nsdecls[i].uri;
            if (uri != null)
            {
                if (uri.Length > 0 || prefix.Length > 0 || scope == XmlNamespaceScope.Local)
                {
                    dictionary[prefix] = uri;
                }
                else
                {
                    dictionary.Remove(prefix);
                }
            }
        }
        return dictionary;
    }
References System.Xml.XmlNamespaceManager._lastDecl, System.Xml.XmlNamespaceManager._nsdecls, System.Xml.XmlNamespaceManager._scopeId, System.dictionary, System.prefix, System.Xml.XmlNamespaceManager.NamespaceDeclaration.prefix, and System.Xml.XmlNamespaceManager.NamespaceDeclaration.uri.
Referenced by System.Xml.DocumentSchemaValidator.GetNamespacesInScope(), System.Xml.DocumentXmlWriter.GetNamespacesInScope(), System.Xml.XmlSubtreeReader.GetNamespacesInScope(), System.Xml.XmlTextReaderImpl.GetNamespacesInScope(), System.Xml.XsdValidatingReader.GetNamespacesInScope(), and System.Xml.Schema.XsdValidator.ProcessXsiAttributes().