Terraria: System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder.AddGeneralName
AddGeneralName()
void System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder.AddGeneralName (GeneralNameAsn generalName) inline private
Definition at line 96 of file SubjectAlternativeNameBuilder.cs.
    {
        try
        {
            AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
            generalName.Encode(asnWriter);
            _encodedNames.Add(asnWriter.Encode());
        }
        catch (EncoderFallbackException)
        {
            throw new CryptographicException(System.SR.Cryptography_Invalid_IA5String);
        }
    }
References System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder._encodedNames, System.Collections.Generic.List< T >.Add(), and System.SR.Cryptography_Invalid_IA5String.
Referenced by System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder.AddDnsName(), System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder.AddEmailAddress(), System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder.AddIpAddress(), System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder.AddUri(), and System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder.AddUserPrincipalName().