Terraria: System.Xml.XmlNamespaceManager.LookupNamespaceDecl
LookupNamespaceDecl()
int System.Xml.XmlNamespaceManager.LookupNamespaceDecl (string prefix) inline private inherited
Definition at line 237 of file XmlNamespaceManager.cs.
    {
        if (_useHashtable)
        {
            if (_hashTable.TryGetValue(prefix, out var value))
            {
                while (value != -1 && _nsdecls[value].uri == null)
                {
                    value = _nsdecls[value].previousNsIndex;
                }
                return value;
            }
            return -1;
        }
        for (int num = _lastDecl; num >= 0; num--)
        {
            if ((object)_nsdecls[num].prefix == prefix && _nsdecls[num].uri != null)
            {
                return num;
            }
        }
        for (int num2 = _lastDecl; num2 >= 0; num2--)
        {
            if (string.Equals(_nsdecls[num2].prefix, prefix) && _nsdecls[num2].uri != null)
            {
                return num2;
            }
        }
        return -1;
    }
References System.Xml.XmlNamespaceManager._hashTable, System.Xml.XmlNamespaceManager._lastDecl, System.Xml.XmlNamespaceManager._nsdecls, System.Xml.XmlNamespaceManager._useHashtable, System.Xml.Dictionary, System.prefix, System.Xml.XmlNamespaceManager.NamespaceDeclaration.previousNsIndex, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.XmlNamespaceManager.LookupNamespace(), and System.Xml.XmlNamespaceManager.RemoveNamespace().