Terraria: System.Xml.XmlNamespaceManager.LookupPrefix
LookupPrefix()
virtual ? string System.Xml.XmlNamespaceManager.LookupPrefix (string uri) inline virtual inherited
Implements System.Xml.IXmlNamespaceResolver.
Reimplemented in System.Xml.Schema.SchemaNamespaceManager, and System.Xml.XmlTextReaderImpl.NoNamespaceManager.
Definition at line 268 of file XmlNamespaceManager.cs.
    {
        for (int num = _lastDecl; num >= 0; num--)
        {
            if (string.Equals(_nsdecls[num].uri, uri))
            {
                string prefix = _nsdecls[num].prefix;
                if (string.Equals(LookupNamespace(prefix), uri))
                {
                    return prefix;
                }
            }
        }
        return null;
    }
References System.Xml.XmlNamespaceManager._lastDecl, System.Xml.XmlNamespaceManager._nsdecls, System.Xml.XmlNamespaceManager.LookupNamespace(), System.prefix, and System.Xml.XmlNamespaceManager.NamespaceDeclaration.prefix.
Referenced by System.Xml.XmlTextReaderImpl.AddDefaultAttributeNonDtd(), System.Xml.Schema.XsdValidator.LoadSchema(), System.Xml.DocumentSchemaValidator.LookupPrefix(), System.Xml.DocumentXmlWriter.LookupPrefix(), System.Xml.XmlSubtreeReader.LookupPrefix(), System.Xml.XmlTextReaderImpl.LookupPrefix(), System.Xml.XsdValidatingReader.LookupPrefix(), System.Xml.Xsl.Runtime.XmlQueryOutput.RemapPrefix(), System.Runtime.Serialization.XPathQueryGenerator.ExportContext.SetNamespace(), and System.Xml.Schema.XmlSchema.Write().