Terraria: System.Xml.XmlNamespaceManager.PopScope
PopScope()
virtual bool System.Xml.XmlNamespaceManager.PopScope () inline virtual inherited
Reimplemented in System.Xml.XmlTextReaderImpl.NoNamespaceManager.
Definition at line 82 of file XmlNamespaceManager.cs.
    {
        int num = _lastDecl;
        if (_scopeId == 1)
        {
            return false;
        }
        while (_nsdecls[num].scopeId == _scopeId)
        {
            if (_useHashtable)
            {
                _hashTable[_nsdecls[num].prefix] = _nsdecls[num].previousNsIndex;
            }
            num--;
        }
        _lastDecl = num;
        _scopeId--;
        return true;
    }
References System.Xml.XmlNamespaceManager._hashTable, System.Xml.XmlNamespaceManager._lastDecl, System.Xml.XmlNamespaceManager._nsdecls, System.Xml.XmlNamespaceManager._scopeId, System.Xml.XmlNamespaceManager._useHashtable, System.Xml.XmlNamespaceManager.NamespaceDeclaration.prefix, and System.Xml.XmlNamespaceManager.NamespaceDeclaration.previousNsIndex.
Referenced by System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.Analyze(), System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.AnalyzeContent(), System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.XmlTextReaderImpl.PopElementContext(), System.Xml.Schema.Parser.ProcessAppInfoDocMarkup(), System.Xml.Schema.XdrValidator.ProcessElement(), System.Xml.XsdValidatingReader.ProcessEndElementEvent(), System.Xml.XsdValidatingReader.ProcessEndElementEventAsync(), System.Xml.XmlSubtreeReader.Read(), System.Xml.XmlSubtreeReader.ReadAsync(), System.Xml.XsdValidatingReader.ReadTillEndElement(), System.Xml.XsdValidatingReader.ReadTillEndElementAsync(), System.Xml.XmlTextReaderImpl.ResetState(), System.Xml.XmlSubtreeReader.Skip(), System.Xml.XmlSubtreeReader.SkipAsync(), System.Xml.DocumentSchemaValidator.ValidateElement(), System.Xml.Schema.XNodeValidator.ValidateElement(), System.Xml.Schema.XdrValidator.ValidateEndElement(), System.Xml.Schema.XsdValidator.ValidateEndElement(), System.Xml.DocumentSchemaValidator.ValidateSingleElement(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndElementUnchecked().