Terraria: System.Text.RegularExpressions.Match.Result
Result()
virtual string System.Text.RegularExpressions.Match.Result (string replacement) inline virtual inherited
Definition at line 67 of file Match.cs.
    {
        if (replacement == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.replacement);
        }
        Regex regex = _regex;
        if (regex == null)
        {
            throw new NotSupportedException(System.SR.NoResultOnFailed);
        }
        RegexReplacement orCreate = RegexReplacement.GetOrCreate(regex._replref, replacement, regex.caps, regex.capsize, regex.capnames, regex.roptions);
        SegmentStringBuilder segments = SegmentStringBuilder.Create();
        orCreate.ReplacementImpl(ref segments, this);
        return segments.ToString();
    }
References System.Text.RegularExpressions.Match._regex, System.Text.RegularExpressions.Regex._replref, System.Text.RegularExpressions.Regex.capnames, System.Text.RegularExpressions.Regex.caps, System.Text.RegularExpressions.Regex.capsize, System.Text.SegmentStringBuilder.Create(), System.Text.RegularExpressions.RegexReplacement.GetOrCreate(), System.SR.NoResultOnFailed, System.Text.RegularExpressions.replacement, System.Text.RegularExpressions.RegexReplacement.ReplacementImpl(), System.Text.RegularExpressions.Regex.roptions, System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(), and System.Text.SegmentStringBuilder.ToString().