Terraria: System.Xml.XmlNamespaceManager.PushScope
PushScope()
virtual void System.Xml.XmlNamespaceManager.PushScope () inline virtual inherited
Reimplemented in System.Xml.XmlTextReaderImpl.NoNamespaceManager.
Definition at line 77 of file XmlNamespaceManager.cs.
    {
        _scopeId++;
    }
References System.Xml.XmlNamespaceManager._scopeId.
Referenced by System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.Analyze(), System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.AnalyzeContent(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync_SetElement(), System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.Schema.Parser.ProcessAppInfoDocMarkup(), System.Xml.Schema.XsdValidator.ProcessElement(), System.Xml.XsdValidatingReader.ProcessElementEvent(), System.Xml.XsdValidatingReader.ProcessElementEventAsync(), System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.Schema.XNodeValidator.PushElement(), System.Xml.Xsl.Runtime.XmlQueryOutput.RemapPrefix(), System.Xml.DocumentSchemaValidator.ValidateElement(), System.Xml.DocumentSchemaValidator.ValidateSingleElement(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclarationUnchecked(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElementUnchecked().