Terraria: HouseBuilder.PlaceBiomeSpecificTool
PlaceBiomeSpecificTool()
void HouseBuilder.PlaceBiomeSpecificTool (HouseBuilderContext context) inline private inherited
     {
         if (Type == HouseType.Jungle && context.SharpenerCount < _random.Next(2, 5))
         {
             bool flag = false;
             foreach (Rectangle room in Rooms)
             {
                 int num = room.Height - 2 + room.Y;
                 for (int i = 0; i < 10; i++)
                 {
                     int num2 = _random.Next(2, room.Width - 2) + room.X;
                     WorldGen.PlaceTile(num2, num, 377, mute: true, forced: true);
                     if (flag = _tiles[num2, num].active() && _tiles[num2, num].type == 377)
                     {
                         break;
                     }
                 }
                 if (flag)
                 {
                     break;
                 }
                 for (int j = room.X + 2; j <= room.X + room.Width - 2; j++)
                 {
                     if (flag = WorldGen.PlaceTile(j, num, 377, mute: true, forced: true))
                     {
                         break;
                     }
                 }
                 if (flag)
                 {
                     break;
                 }
             }
             if (flag)
             {
                 context.SharpenerCount++;
             }
         }
         if (Type != HouseType.Desert || context.ExtractinatorCount >= _random.Next(2, 5))
         {
             return;
         }
         bool flag2 = false;
         foreach (Rectangle room2 in Rooms)
         {
             int num3 = room2.Height - 2 + room2.Y;
             for (int k = 0; k < 10; k++)
             {
                 int num4 = _random.Next(2, room2.Width - 2) + room2.X;
                 WorldGen.PlaceTile(num4, num3, 219, mute: true, forced: true);
                 if (flag2 = _tiles[num4, num3].active() && _tiles[num4, num3].type == 219)
                 {
                     break;
                 }
             }
             if (flag2)
             {
                 break;
             }
             for (int l = room2.X + 2; l <= room2.X + room2.Width - 2; l++)
             {
                 if (flag2 = WorldGen.PlaceTile(l, num3, 219, mute: true, forced: true))
                 {
                     break;
                 }
             }
             if (flag2)
             {
                 break;
             }
         }
         if (flag2)
         {
             context.ExtractinatorCount++;
         }
     }
References HouseBuilder._random, HouseBuilder._tiles, HouseBuilderContext.ExtractinatorCount, UnifiedRandom.Next(), WorldGen.PlaceTile(), HouseBuilder.Rooms, HouseBuilderContext.SharpenerCount, and HouseBuilder.Type.
Referenced by HouseBuilder.Place().