Terraria: HouseBuilder.PlaceStairs
PlaceStairs()
void HouseBuilder.PlaceStairs () inline private inherited
     {
         foreach (Tuple<Point, Point> item3 in CreateStairsList())
         {
             Point item = item3.Item1;
             Point item2 = item3.Item2;
             int num = ((item2.X > item.X) ? 1 : (-1));
             ShapeData shapeData = new ShapeData();
             for (int i = 0; i < item2.Y - item.Y; i++)
             {
                 shapeData.Add(num * (i + 1), i);
             }
             WorldUtils.Gen(item, new ModShapes.All(shapeData), Actions.Chain(new Actions.PlaceTile(19, PlatformStyle), new Actions.SetSlope((num == 1) ? 1 : 2), new Actions.SetFrames(frameNeighbors: true)));
             WorldUtils.Gen(new Point(item.X + ((num == 1) ? 1 : (-4)), item.Y - 1), new Shapes.Rectangle(4, 1), Actions.Chain(new Actions.Clear(), new Actions.PlaceWall(WallType), new Actions.PlaceTile(19, PlatformStyle), new Actions.SetFrames(frameNeighbors: true)));
         }
     }
References ShapeData.Add(), Actions.Chain(), HouseBuilder.CreateStairsList(), WorldUtils.Gen(), HouseBuilder.PlatformStyle, and HouseBuilder.WallType.
Referenced by HouseBuilder.Place().