Terraria: HouseBuilder.Place
Place()
virtual void HouseBuilder.Place (HouseBuilderContext context, StructureMap structures) inline virtual inherited
Reimplemented in WoodHouseBuilder.
     {
         PlaceEmptyRooms();
         foreach (Rectangle room in Rooms)
         {
             structures.AddProtectedStructure(room, 8);
         }
         PlaceStairs();
         PlaceDoors();
         PlacePlatforms();
         PlaceSupportBeams();
         PlaceBiomeSpecificPriorityTool(context);
         FillRooms();
         foreach (Rectangle room2 in Rooms)
         {
             AgeRoom(room2);
         }
         PlaceChests();
         PlaceBiomeSpecificTool(context);
     }
References HouseBuilder.AgeRoom(), HouseBuilder.FillRooms(), HouseBuilder.PlaceBiomeSpecificPriorityTool(), HouseBuilder.PlaceBiomeSpecificTool(), HouseBuilder.PlaceChests(), HouseBuilder.PlaceDoors(), HouseBuilder.PlaceEmptyRooms(), HouseBuilder.PlacePlatforms(), HouseBuilder.PlaceStairs(), HouseBuilder.PlaceSupportBeams(), and HouseBuilder.Rooms.
Referenced by CaveHouseBiome.Place().