Terraria: HouseBuilder.PlaceSupportBeams
PlaceSupportBeams()
void HouseBuilder.PlaceSupportBeams () inline private inherited
     {
         foreach (Rectangle item in CreateSupportBeamList())
         {
             if (item.Height > 1 && _tiles[item.X, item.Y - 1].type != 19)
             {
                 WorldUtils.Gen(new Point(item.X, item.Y), new Shapes.Rectangle(item.Width, item.Height), Actions.Chain(new Actions.SetTileKeepWall(BeamType), new Actions.SetFrames(frameNeighbors: true)));
                 Tile tile = _tiles[item.X, item.Y + item.Height];
                 tile.slope(0);
                 tile.halfBrick(halfBrick: false);
             }
         }
     }
References HouseBuilder._tiles, HouseBuilder.BeamType, Actions.Chain(), HouseBuilder.CreateSupportBeamList(), WorldUtils.Gen(), Tile.halfBrick(), Tile.slope(), and Tile.type.
Referenced by HouseBuilder.Place().