Terraria: HouseBuilder.PlaceBiomeSpecificPriorityTool
PlaceBiomeSpecificPriorityTool()
void HouseBuilder.PlaceBiomeSpecificPriorityTool (HouseBuilderContext context) inline private inherited
     {
         if (Type != HouseType.Desert || GenVars.extraBastStatueCount >= GenVars.extraBastStatueCountMax)
         {
             return;
         }
         bool flag = false;
         foreach (Rectangle room in Rooms)
         {
             int num = room.Height - 2 + room.Y;
             if (WorldGen.remixWorldGen && (double)num > Main.rockLayer)
             {
                 return;
             }
             for (int i = 0; i < 10; i++)
             {
                 int num2 = _random.Next(2, room.Width - 2) + room.X;
                 WorldGen.PlaceTile(num2, num, 506, mute: true, forced: true);
                 if (flag = _tiles[num2, num].active() && _tiles[num2, num].type == 506)
                 {
                     break;
                 }
             }
             if (flag)
             {
                 break;
             }
             for (int j = room.X + 2; j <= room.X + room.Width - 2; j++)
             {
                 if (flag = WorldGen.PlaceTile(j, num, 506, mute: true, forced: true))
                 {
                     break;
                 }
             }
             if (flag)
             {
                 break;
             }
         }
         if (!flag)
         {
             foreach (Rectangle room2 in Rooms)
             {
                 int num3 = room2.Y - 1;
                 for (int k = 0; k < 10; k++)
                 {
                     int num4 = _random.Next(2, room2.Width - 2) + room2.X;
                     WorldGen.PlaceTile(num4, num3, 506, mute: true, forced: true);
                     if (flag = _tiles[num4, num3].active() && _tiles[num4, num3].type == 506)
                     {
                         break;
                     }
                 }
                 if (flag)
                 {
                     break;
                 }
                 for (int l = room2.X + 2; l <= room2.X + room2.Width - 2; l++)
                 {
                     if (flag = WorldGen.PlaceTile(l, num3, 506, mute: true, forced: true))
                     {
                         break;
                     }
                 }
                 if (flag)
                 {
                     break;
                 }
             }
         }
         if (flag)
         {
             GenVars.extraBastStatueCount++;
         }
     }
References HouseBuilder._random, HouseBuilder._tiles, GenVars.extraBastStatueCount, GenVars.extraBastStatueCountMax, UnifiedRandom.Next(), WorldGen.PlaceTile(), WorldGen.remixWorldGen, Main.rockLayer, HouseBuilder.Rooms, and HouseBuilder.Type.
Referenced by HouseBuilder.Place().