Terraria: HouseBuilder.FindSideExit
FindSideExit()
static bool HouseBuilder.FindSideExit (Rectangle wall, bool isLeft, out int exitY) inline static private inherited
     {
         Point result;
         bool result2 = WorldUtils.Find(new Point(wall.X + (isLeft ? (-4) : 0), wall.Y + wall.Height - 3), Searches.Chain(new Searches.Up(wall.Height - 3), new Conditions.IsSolid().Not().AreaOr(4, 3)), out result);
         exitY = result.Y;
         return result2;
     }
References GenCondition.AreaOr(), Searches.Chain(), WorldUtils.Find(), and GenCondition.Not().
Referenced by HouseBuilder.CreateDoorList().