Terraria: Player.GetFishingConditions
GetFishingConditions()
PlayerFishingConditions Player.GetFishingConditions () inline
     {
         PlayerFishingConditions result = default(PlayerFishingConditions);
         Fishing_GetBestFishingPole(out result.PolePower, out result.PoleItemType);
         Fishing_GetBait(out result.BaitPower, out result.BaitItemType);
         if (result.BaitItemType == 2673)
         {
             return result;
         }
         if (result.BaitPower == 0 || result.PolePower == 0)
         {
             return result;
         }
         int num = 0;
         if (FindBuffIndex(25) != -1)
         {
             num += 5;
         }
         if (canFloatInWater && wet)
         {
             num += 5;
         }
         if (sitting.TryGetSittingBlock(this, out var tile) && ((tile.type == 15 && tile.frameY / 40 == 1) || tile.type == 497))
         {
             num += 5;
         }
         int num2 = result.BaitPower + result.PolePower + fishingSkill + num;
         result.LevelMultipliers = Fishing_GetPowerMultiplier();
         result.FinalFishingLevel = (int)((float)num2 * result.LevelMultipliers);
         return result;
     }
References PlayerFishingConditions.BaitItemType, PlayerFishingConditions.BaitPower, PlayerFishingConditions.FinalFishingLevel, PlayerFishingConditions.LevelMultipliers, PlayerFishingConditions.PoleItemType, and PlayerFishingConditions.PolePower.
Referenced by Projectile.AI_061_FishingBobber(), Projectile.AI_061_FishingBobber_GiveItemToPlayer(), Main.DrawInfoAccs(), and Projectile.FishingCheck().