Terraria: Player.WOFTongue
WOFTongue()
void Player.WOFTongue () inline
     {
         if (Main.wofNPCIndex < 0 || !Main.npc[Main.wofNPCIndex].active)
         {
             return;
         }
         float num = Main.npc[Main.wofNPCIndex].position.X + 40f;
         if (Main.npc[Main.wofNPCIndex].direction > 0)
         {
             num -= 96f;
         }
         if (position.X + (float)width > num && position.X < num + 140f && gross)
         {
             noKnockback = false;
             int attackDamage_ScaledByStrength = Main.npc[Main.wofNPCIndex].GetAttackDamage_ScaledByStrength(50f);
             Hurt(PlayerDeathReason.LegacyDefault(), attackDamage_ScaledByStrength, Main.npc[Main.wofNPCIndex].direction);
         }
         if (!gross && position.Y > (float)((Main.maxTilesY - 250) * 16) && position.X > num - 1920f && position.X < num + 1920f)
         {
             AddBuff(37, 10);
             SoundEngine.PlaySound(4, (int)Main.npc[Main.wofNPCIndex].position.X, (int)Main.npc[Main.wofNPCIndex].position.Y, 10);
         }
         if (gross)
         {
             if (position.Y < (float)(Main.UnderworldLayer * 16))
             {
                 AddBuff(38, 10);
             }
             if (Main.npc[Main.wofNPCIndex].direction < 0)
             {
                 if (position.X + (float)(width / 2) > Main.npc[Main.wofNPCIndex].position.X + (float)(Main.npc[Main.wofNPCIndex].width / 2) + 40f)
                 {
                     AddBuff(38, 10);
                 }
             }
             else if (position.X + (float)(width / 2) < Main.npc[Main.wofNPCIndex].position.X + (float)(Main.npc[Main.wofNPCIndex].width / 2) - 40f)
             {
                 AddBuff(38, 10);
             }
         }
         if (!tongued)
         {
             return;
         }
         controlHook = false;
         controlUseItem = false;
         for (int i = 0; i < 1000; i++)
         {
             if (Main.projectile[i].active && Main.projectile[i].owner == Main.myPlayer && Main.projectile[i].aiStyle == 7)
             {
                 Main.projectile[i].Kill();
             }
         }
         Vector2 center = base.Center;
         float num2 = Main.npc[Main.wofNPCIndex].position.X + (float)(Main.npc[Main.wofNPCIndex].width / 2) - center.X;
         float num3 = Main.npc[Main.wofNPCIndex].position.Y + (float)(Main.npc[Main.wofNPCIndex].height / 2) - center.Y;
         if ((float)Math.Sqrt(num2 * num2 + num3 * num3) > 3000f)
         {
             KillMe(PlayerDeathReason.ByOther(11), 1000.0, 0);
         }
         else if (Main.npc[Main.wofNPCIndex].position.X < 608f || Main.npc[Main.wofNPCIndex].position.X > (float)((Main.maxTilesX - 38) * 16))
         {
             KillMe(PlayerDeathReason.ByOther(12), 1000.0, 0);
         }
     }
References Entity.active, Projectile.aiStyle, PlayerDeathReason.ByOther(), Entity.direction, NPC.GetAttackDamage_ScaledByStrength(), Entity.height, Projectile.Kill(), PlayerDeathReason.LegacyDefault(), Main.maxTilesX, Main.maxTilesY, Main.myPlayer, Main.npc, Projectile.owner, SoundEngine.PlaySound(), Entity.position, Main.projectile, Main.UnderworldLayer, Entity.width, and Main.wofNPCIndex.