Terraria: Player.TileInteractionsUse
TileInteractionsUse()
void Player.TileInteractionsUse (int myX, int myY) inline private
     {
         if (WiresUI.Open || ownedProjectileCounts[651] > 0)
         {
             return;
         }
         bool flag = releaseUseTile;
         if (!tileInteractAttempted)
         {
             return;
         }
         bool flag2 = false;
         if (Main.tile[myX, myY].type == 212 && snowBallLauncherInteractionCooldown <= 0)
         {
             flag2 = true;
             snowBallLauncherInteractionCooldown = 7;
             SoundEngine.PlaySound(SoundID.Item11, position);
             int num = Main.tile[myX, myY].frameX / 18;
             int num2 = 0;
             while (num >= 3)
             {
                 num2++;
                 num -= 3;
             }
             num = myX - num;
             int num3;
             for (num3 = Main.tile[myX, myY].frameY / 18; num3 >= 3; num3 -= 3)
             {
             }
             num3 = myY - num3;
             float num4 = 12f + (float)Main.rand.Next(450) * 0.01f;
             float num5 = Main.rand.Next(85, 105);
             float num6 = Main.rand.Next(-35, 11);
             int type = 166;
             int damage = 35;
             float knockBack = 3.5f;
             Vector2 vector = new Vector2((num + 2) * 16 - 8, (num3 + 2) * 16 - 8 - 4);
             if (num2 == 0)
             {
                 num5 *= -1f;
                 vector.X -= 14f;
                 vector.X -= 2f;
             }
             else
             {
                 vector.X += 14f;
             }
             float num7 = num5;
             float num8 = num6;
             float num9 = (float)Math.Sqrt(num7 * num7 + num8 * num8);
             num9 = num4 / num9;
             num7 *= num9;
             num8 *= num9;
             int num10 = Projectile.NewProjectile(GetProjectileSource_TileInteraction(num, num3), vector.X, vector.Y, num7, num8, type, damage, knockBack, Main.myPlayer, -Main.rand.Next(0, 16));
             Main.projectile[num10].originatedFromActivableTile = true;
         }
         if (flag)
         {
             if (Main.tile[myX, myY].type == 132 || Main.tile[myX, myY].type == 136 || Main.tile[myX, myY].type == 144)
             {
                 flag2 = true;
                 Wiring.HitSwitch(myX, myY);
                 NetMessage.SendData(59, -1, -1, null, myX, myY);
             }
             else if (Main.tile[myX, myY].type == 597)
             {
                 flag2 = true;
                 TryOpeningFullscreenMap();
             }
             else if (Main.tile[myX, myY].type == 441 || Main.tile[myX, myY].type == 468)
             {
                 flag2 = true;
                 int num11;
                 for (num11 = Main.tile[myX, myY].frameX / 18; num11 > 1; num11 -= 2)
                 {
                 }
                 num11 = myX - num11;
                 int num12 = myY - Main.tile[myX, myY].frameY / 18;
                 Animation.NewTemporaryAnimation(2, Main.tile[myX, myY].type, num11, num12);
                 NetMessage.SendTemporaryAnimation(-1, 2, Main.tile[myX, myY].type, num11, num12);
                 Wiring.HitSwitch(myX, myY);
                 NetMessage.SendData(59, -1, -1, null, myX, myY);
             }
             else if (Main.tile[myX, myY].type == 139)
             {
                 flag2 = true;
                 SoundEngine.PlaySound(28, myX * 16, myY * 16, 0);
                 WorldGen.SwitchMB(myX, myY);
             }
             else if (Main.tile[myX, myY].type == 215)
             {
                 flag2 = true;
                 SoundEngine.PlaySound(28, myX * 16, myY * 16, 0);
                 int num13 = Main.tile[myX, myY].frameX % 54 / 18;
                 int num14 = Main.tile[myX, myY].frameY % 36 / 18;
                 int num15 = myX - num13;
                 int num16 = myY - num14;
                 int num17 = 36;
                 if (Main.tile[num15, num16].frameY >= 36)
                 {
                     num17 = -36;
                 }
                 for (int i = num15; i < num15 + 3; i++)
                 {
                     for (int j = num16; j < num16 + 2; j++)
                     {
                         Main.tile[i, j].frameY = (short)(Main.tile[i, j].frameY + num17);
                     }
                 }
                 NetMessage.SendTileSquare(-1, num15, num16, 3, 2);
             }
             else if (Main.tile[myX, myY].type == 207)
             {
                 flag2 = true;
                 SoundEngine.PlaySound(28, myX * 16, myY * 16, 0);
                 WorldGen.SwitchFountain(myX, myY);
             }
             else if (Main.tile[myX, myY].type == 410 || Main.tile[myX, myY].type == 480 || Main.tile[myX, myY].type == 509 || Main.tile[myX, myY].type == 657 || Main.tile[myX, myY].type == 658)
             {
                 flag2 = true;
                 SoundEngine.PlaySound(28, myX * 16, myY * 16, 0);
                 GamepadEnableGrappleCooldown();
                 WorldGen.SwitchMonolith(myX, myY);
             }
             else if (Main.tile[myX, myY].type == 455)
             {
                 flag2 = true;
                 SoundEngine.PlaySound(28, myX * 16, myY * 16, 0);
                 GamepadEnableGrappleCooldown();
                 BirthdayParty.ToggleManualParty();
             }
             else if (Main.tile[myX, myY].type == 216)
             {
                 flag2 = true;
                 WorldGen.LaunchRocket(myX, myY, fromWiring: false);
             }
             else if (Main.tile[myX, myY].type == 386 || Main.tile[myX, myY].type == 387)
             {
                 flag2 = true;
                 bool flag3 = Main.tile[myX, myY].type == 387;
                 int num18 = WorldGen.ShiftTrapdoor(myX, myY, (float)(myY * 16) > base.Center.Y).ToInt();
                 if (num18 == 0)
                 {
                     num18 = -WorldGen.ShiftTrapdoor(myX, myY, (float)(myY * 16) <= base.Center.Y).ToInt();
                 }
                 if (num18 != 0)
                 {
                     NetMessage.SendData(19, -1, -1, null, 2 + (!flag3).ToInt(), myX, myY, num18 * Math.Sign((float)(myY * 16) - base.Center.Y));
                 }
             }
             else if (Main.tile[myX, myY].type == 388 || Main.tile[myX, myY].type == 389)
             {
                 flag2 = true;
                 bool flag4 = Main.tile[myX, myY].type == 389;
                 if (WorldGen.ShiftTallGate(myX, myY, flag4))
                 {
                     NetMessage.SendData(19, -1, -1, null, 4 + flag4.ToInt(), myX, myY);
                 }
             }
             else if (Main.tile[myX, myY].type == 15 || Main.tile[myX, myY].type == 497)
             {
                 if (IsWithinSnappngRangeToTile(myX, myY, 40))
                 {
                     flag2 = true;
                     GamepadEnableGrappleCooldown();
                     sitting.SitDown(this, myX, myY);
                 }
             }
             else if (Main.tile[myX, myY].type == 89 || Main.tile[myX, myY].type == 102 || Main.tile[myX, myY].type == 487)
             {
                 if (IsWithinSnappngRangeToTile(myX, myY, 40))
                 {
                     flag2 = true;
                     GamepadEnableGrappleCooldown();
                     sitting.SitDown(this, myX, myY);
                 }
             }
             else if (Main.tile[myX, myY].type == 335)
             {
                 flag2 = true;
                 WorldGen.LaunchRocketSmall(myX, myY, fromWiring: false);
             }
             else if (Main.tile[myX, myY].type == 411 && Main.tile[myX, myY].frameX < 36)
             {
                 flag2 = true;
                 Wiring.HitSwitch(myX, myY);
                 NetMessage.SendData(59, -1, -1, null, myX, myY);
             }
             else if (Main.tile[myX, myY].type == 494)
             {
                 flag2 = true;
                 for (int k = 0; k < 1000; k++)
                 {
                     if (ProjectileID.Sets.IsAGolfBall[Main.projectile[k].type] && Main.projectile[k].owner == whoAmI)
                     {
                         Main.projectile[k].Kill();
                     }
                 }
                 GetPreferredGolfBallToUse(out var projType);
                 Projectile.NewProjectile(GetProjectileSource_TileInteraction(myX, myY), (float)(myX * 16) + 8.5f, myY * 16 + 6, 0f, 0f, projType, 0, 0f, whoAmI, 0f, -1f);
             }
             else if (Main.tile[myX, myY].type == 338)
             {
                 flag2 = true;
                 int num19 = myY;
                 if (Main.tile[myX, num19].frameY == 18)
                 {
                     num19--;
                 }
                 bool flag5 = false;
                 for (int l = 0; l < 1000; l++)
                 {
                     if (Main.projectile[l].active && Main.projectile[l].aiStyle == 73 && Main.projectile[l].ai[0] == (float)myX && Main.projectile[l].ai[1] == (float)num19)
                     {
                         flag5 = true;
                         break;
                     }
                 }
                 if (!flag5)
                 {
                     int num20 = Projectile.NewProjectile(GetProjectileSource_TileInteraction(myX, num19), myX * 16 + 8, num19 * 16 + 2, 0f, 0f, 419 + Main.rand.Next(4), 0, 0f, whoAmI, myX, num19);
                     Main.projectile[num20].originatedFromActivableTile = true;
                 }
             }
             else if (Main.tile[myX, myY].type == 33 || Main.tile[myX, myY].type == 49 || Main.tile[myX, myY].type == 372 || Main.tile[myX, myY].type == 174 || Main.tile[myX, myY].type == 646)
             {
                 short num21 = 18;
                 Tile tile = Main.tile[myX, myY];
                 if (tile.frameX > 0)
                 {
                     num21 = -18;
                 }
                 tile.frameX += num21;
                 NetMessage.SendTileSquare(-1, myX, myY);
                 flag2 = true;
                 GamepadEnableGrappleCooldown();
             }
             else if (Main.tile[myX, myY].type == 4 || Main.tile[myX, myY].type == 13 || (Main.tile[myX, myY].type == 50 && Main.tile[myX, myY].frameX == 90))
             {
                 WorldGen.KillTile(myX, myY);
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(17, -1, -1, null, 0, myX, myY);
                 }
                 flag2 = true;
                 GamepadEnableGrappleCooldown();
             }
             else if (Main.tile[myX, myY].type == 466)
             {
                 flag2 = true;
                 GamepadEnableGrappleCooldown();
                 int num22 = myY;
                 Tile tileSafely = Framing.GetTileSafely(myX, myY);
                 if (tileSafely.frameY == 0)
                 {
                     num22 += 3;
                 }
                 if (tileSafely.frameY == 18)
                 {
                     num22 += 2;
                 }
                 if (tileSafely.frameY == 36)
                 {
                     num22++;
                 }
                 if (DD2Event.Ongoing)
                 {
                     DD2Event.RequestToSkipWaitTime(myX, myY);
                 }
                 else
                 {
                     bool flag6 = !DD2Event.Ongoing && !NPC.AnyNPCs(548) && !Main.pumpkinMoon && !Main.snowMoon;
                     if (flag6)
                     {
                         flag6 = HasItem(3828);
                     }
                     if (flag6)
                     {
                         flag6 = !DD2Event.WouldFailSpawningHere(myX, num22);
                         if (!flag6)
{
                             DD2Event.FailureMessage(-1);
                         }
                     }
                     if (flag6)
                     {
                         flag6 = ConsumeItem(3828, reverseOrder: true);
                     }
                     if (flag6)
                     {
                         DD2Event.SummonCrystal(myX, num22, whoAmI);
                     }
                 }
             }
             else if (Main.tile[myX, myY].type == 334)
             {
                 flag2 = true;
                 if (ItemFitsWeaponRack(inventory[selectedItem]))
                 {
                     GamepadEnableGrappleCooldown();
                     PlaceWeapon(myX, myY);
                 }
                 else
                 {
                     int num23 = myX;
                     int num24 = myY;
                     if (Main.tile[myX, myY].frameY == 0)
                     {
                         num24++;
                     }
                     if (Main.tile[myX, myY].frameY == 36)
                     {
                         num24--;
                     }
                     int frameX = Main.tile[myX, num24].frameX;
                     int num25 = Main.tile[myX, num24].frameX;
                     int num26 = 0;
                     while (num25 >= 5000)
                     {
                         num25 -= 5000;
                         num26++;
                     }
                     if (num26 != 0)
                     {
                         num25 = (num26 - 1) * 18;
                     }
                     num25 %= 54;
                     if (num25 == 18)
                     {
                         frameX = Main.tile[myX - 1, num24].frameX;
                         num23--;
                     }
                     if (num25 == 36)
                     {
                         frameX = Main.tile[myX - 2, num24].frameX;
                         num23 -= 2;
                     }
                     if (frameX >= 5000)
                     {
                         GamepadEnableGrappleCooldown();
                         WorldGen.KillTile(myX, num24, fail: true);
                         if (Main.netMode == 1)
{
                             NetMessage.SendData(17, -1, -1, null, 0, myX, num24, 1f);
                         }
                     }
                 }
             }
             else if (Main.tile[myX, myY].type == 440)
             {
                 flag2 = true;
                 int num27 = Main.tile[myX, myY].frameX / 54;
                 int num28 = Main.tile[myX, myY].frameY / 54;
                 _ = Main.tile[myX, myY].frameX % 54 / 18;
                 _ = Main.tile[myX, myY].frameY % 54 / 18;
                 int num29 = -1;
                 switch (num27)
                 {
                 case 0:
                     num29 = 1526;
                     break;
                 case 1:
                     num29 = 1524;
                     break;
                 case 2:
                     num29 = 1525;
                     break;
                 case 3:
                     num29 = 1523;
                     break;
                 case 4:
                     num29 = 1522;
                     break;
                 case 5:
                     num29 = 1527;
                     break;
                 case 6:
                     num29 = 3643;
                     break;
                 }
                 if (num29 != -1)
                 {
                     if (num28 == 0 && HasItem(num29) && selectedItem != 58)
                     {
                         GamepadEnableGrappleCooldown();
                         if (Main.netMode != 1)
{
                             ConsumeItem(num29);
                             WorldGen.ToggleGemLock(myX, myY, on: true);
                         }
                         else
{
                             ConsumeItem(num29);
                             NetMessage.SendData(105, -1, -1, null, myX, myY, 1f);
                         }
                     }
                     else if (num28 == 1)
                     {
                         GamepadEnableGrappleCooldown();
                         if (Main.netMode != 1)
{
                             WorldGen.ToggleGemLock(myX, myY, on: false);
                         }
                         else
{
                             NetMessage.SendData(105, -1, -1, null, myX, myY);
                         }
                     }
                 }
             }
             else if (Main.tile[myX, myY].type == 395)
             {
                 flag2 = true;
                 TEItemFrame.OnPlayerInteraction(this, myX, myY);
             }
             else if (Main.tile[myX, myY].type == 520)
             {
                 flag2 = true;
                 TEFoodPlatter.OnPlayerInteraction(this, myX, myY);
             }
             else if (Main.tile[myX, myY].type == 471)
             {
                 flag2 = true;
                 TEWeaponsRack.OnPlayerInteraction(this, myX, myY);
             }
             else if (Main.tile[myX, myY].type == 470)
             {
                 flag2 = true;
                 TEDisplayDoll.OnPlayerInteraction(this, myX, myY);
             }
             else if (Main.tile[myX, myY].type == 475)
             {
                 flag2 = true;
                 TEHatRack.OnPlayerInteraction(this, myX, myY);
             }
             else if (Main.tile[myX, myY].type == 125)
             {
                 flag2 = true;
                 AddBuff(29, 108000);
                 SoundEngine.PlaySound(SoundID.Item4, position);
             }
             else if (Main.tile[myX, myY].type == 621)
             {
                 flag2 = true;
                 AddBuff(192, 7200);
                 SoundEngine.PlaySound(SoundID.Item2, position);
             }
             else if (Main.tile[myX, myY].type == 464)
             {
                 flag2 = true;
                 AddBuff(348, 108000);
                 SoundEngine.PlaySound(SoundID.Item4, position);
             }
             else if (Main.tile[myX, myY].type == 377)
             {
                 flag2 = true;
                 AddBuff(159, 108000);
                 SoundEngine.PlaySound(SoundID.Item37, position);
             }
             else if (Main.tile[myX, myY].type == 354)
             {
                 flag2 = true;
                 AddBuff(150, 108000);
                 SoundEngine.PlaySound(SoundID.Item4, position);
             }
             else if (Main.tile[myX, myY].type == 287)
             {
                 flag2 = true;
                 AddBuff(93, 108000);
                 SoundEngine.PlaySound(SoundID.Item149, position);
             }
             else if (Main.tile[myX, myY].type == 356)
             {
                 flag2 = true;
                 if (!Main.fastForwardTimeToDawn && (Main.netMode == 1 || Main.sundialCooldown == 0))
                 {
                     Main.Sundialing();
                     SoundEngine.PlaySound(SoundID.Item4, position);
                 }
             }
             else if (Main.tile[myX, myY].type == 663)
             {
                 flag2 = true;
                 if (!Main.fastForwardTimeToDusk && (Main.netMode == 1 || Main.moondialCooldown == 0))
                 {
                     Main.Moondialing();
                     SoundEngine.PlaySound(SoundID.Item4, position);
                 }
             }
             else if (Main.tile[myX, myY].type == 79)
             {
                 flag2 = true;
                 int num30 = myX;
                 int num31 = myY;
                 num30 += Main.tile[myX, myY].frameX / 18 * -1;
                 if (Main.tile[myX, myY].frameX >= 72)
                 {
                     num30 += 4;
                     num30++;
                 }
                 else
                 {
                     num30 += 2;
                 }
                 int num32 = Main.tile[myX, myY].frameY / 18;
                 int num33 = 0;
                 while (num32 > 1)
                 {
                     num32 -= 2;
                     num33++;
                 }
                 num31 -= num32;
                 num31 += 2;
                 if (!IsHoveringOverABottomSideOfABed(myX, myY))
                 {
                     if (IsWithinSnappngRangeToTile(myX, myY, 96))
                     {
                         flag2 = true;
                         GamepadEnableGrappleCooldown();
                         sleeping.StartSleeping(this, myX, myY);
                     }
                 }
                 else
                 {
                     FindSpawn();
                     if (SpawnX == num30 && SpawnY == num31)
                     {
                         RemoveSpawn();
                         Main.NewText(Language.GetTextValue("Game.SpawnPointRemoved"), byte.MaxValue, 240, 20);
                     }
                     else if (CheckSpawn(num30, num31))
                     {
                         ChangeSpawn(num30, num31);
                         Main.NewText(Language.GetTextValue("Game.SpawnPointSet"), byte.MaxValue, 240, 20);
                     }
                 }
             }
             else if (Main.tileSign[Main.tile[myX, myY].type])
             {
                 flag2 = true;
                 bool flag7 = true;
                 if (sign >= 0 && Sign.ReadSign(myX, myY, CreateIfMissing: false) == sign)
                 {
                     sign = -1;
                     Main.npcChatText = "";
                     Main.editSign = false;
                     SoundEngine.PlaySound(11);
                     flag7 = false;
                 }
                 if (flag7)
                 {
                     if (Main.netMode == 0)
                     {
                         SetTalkNPC(-1);
                         Main.npcChatCornerItem = 0;
                         Main.playerInventory = false;
                         Main.editSign = false;
                         int num34 = Sign.ReadSign(myX, myY);
                         if (num34 < 0)
{
                             return;
                         }
                         SoundEngine.PlaySound(10);
                         sign = num34;
                         Main.npcChatText = Main.sign[num34].text;
                     }
                     else
                     {
                         int num35 = Main.tile[myX, myY].frameX / 18;
                         int num36 = Main.tile[myX, myY].frameY / 18;
                         while (num35 > 1)
{
                             num35 -= 2;
                         }
                         int num37 = myX - num35;
                         int num38 = myY - num36;
                         if (Main.tileSign[Main.tile[num37, num38].type])
{
                             NetMessage.SendData(46, -1, -1, null, num37, num38);
                         }
                     }
                 }
             }
             else if (Main.tile[myX, myY].type == 104)
             {
                 flag2 = true;
                 string textValue = Language.GetTextValue("GameUI.TimeAtMorning");
                 double num39 = Main.time;
                 if (!Main.dayTime)
                 {
                     num39 += 54000.0;
                 }
                 num39 = num39 / 86400.0 * 24.0;
                 double num40 = 7.5;
                 num39 = num39 - num40 - 12.0;
                 if (num39 < 0.0)
                 {
                     num39 += 24.0;
                 }
                 if (num39 >= 12.0)
                 {
                     textValue = Language.GetTextValue("GameUI.TimePastMorning");
                 }
                 int num41 = (int)num39;
                 double num42 = (int)((num39 - (double)num41) * 60.0);
                 string text = string.Concat(num42);
                 if (num42 < 10.0)
                 {
                     text = "0" + text;
                 }
                 if (num41 > 12)
                 {
                     num41 -= 12;
                 }
                 if (num41 == 0)
                 {
                     num41 = 12;
                 }
                 Main.NewText(Language.GetTextValue("Game.Time", num41 + ":" + text + " " + textValue), byte.MaxValue, 240, 20);
             }
             else if (Main.tile[myX, myY].type == 237)
             {
                 flag2 = true;
                 bool flag8 = false;
                 if (!NPC.AnyNPCs(245) && Main.hardMode && NPC.downedPlantBoss)
                 {
                     for (int m = 0; m < 58; m++)
                     {
                         if (inventory[m].type == 1293)
{
                             inventory[m].stack--;
                             if (inventory[m].stack <= 0)
{
                                 inventory[m].SetDefaults();
                             }
                             flag8 = true;
                             break;
                         }
                     }
                 }
                 if (flag8)
                 {
                     SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
                     if (Main.netMode != 1)
                     {
                         NPC.SpawnOnPlayer(whoAmI, 245);
                     }
                     else
                     {
                         NetMessage.SendData(61, -1, -1, null, whoAmI, 245f);
                     }
                 }
             }
             else if (Main.tile[myX, myY].type == 10)
             {
                 flag2 = true;
                 if (WorldGen.IsLockedDoor(myX, myY))
                 {
                     int num43 = 1141;
                     bool flag9 = false;
                     for (int n = 0; n < 58; n++)
                     {
                         if (inventory[n].type == num43 && inventory[n].stack > 0)
{
                             flag9 = true;
                             inventory[n].stack--;
                             if (inventory[n].stack <= 0)
{
                                 inventory[n] = new Item();
                             }
                             WorldGen.UnlockDoor(myX, myY);
                             if (Main.netMode == 1)
{
                                 NetMessage.SendData(52, -1, -1, null, whoAmI, 2f, myX, myY);
                             }
                         }
                     }
                     if (!flag9 && useVoidBag())
                     {
                         for (int num44 = 0; num44 < 40; num44++)
{
                             if (bank4.item[num44].type == num43 && bank4.item[num44].stack > 0)
{
                                 bank4.item[num44].stack--;
                                 if (bank4.item[num44].stack <= 0)
{
                                     bank4.item[num44] = new Item();
                                 }
                                 WorldGen.UnlockDoor(myX, myY);
                                 if (Main.netMode == 1)
{
                                     NetMessage.SendData(52, -1, -1, null, whoAmI, 2f, myX, myY);
                                 }
                             }
                         }
                     }
                 }
                 else
                 {
                     WorldGen.OpenDoor(myX, myY, direction);
                     if (Main.tile[myX, myY].type != 10)
                     {
                         NetMessage.SendData(19, -1, -1, null, 0, myX, myY, direction);
                     }
                     else
                     {
                         WorldGen.OpenDoor(myX, myY, -direction);
                         if (Main.tile[myX, myY].type != 10)
{
                             NetMessage.SendData(19, -1, -1, null, 0, myX, myY, -direction);
                         }
                     }
                 }
             }
             else if (Main.tile[myX, myY].type == 11)
             {
                 flag2 = true;
                 if (WorldGen.CloseDoor(myX, myY))
                 {
                     NetMessage.SendData(19, -1, -1, null, 1, myX, myY, direction);
                 }
             }
             else if (Main.tile[myX, myY].type == 88)
             {
                 flag2 = true;
                 int num45 = Main.tile[myX, myY].frameX / 18;
                 num45 %= 3;
                 num45 = myX - num45;
                 int num46 = myY - Main.tile[myX, myY].frameY / 18;
                 if (Main.tile[myX, myY].frameY == 0)
                 {
                     Main.CancelClothesWindow(quiet: true);
                     Main.mouseRightRelease = false;
                     CloseSign();
                     SetTalkNPC(-1);
                     Main.npcChatCornerItem = 0;
                     Main.npcChatText = "";
                     if (Main.editChest)
                     {
                         SoundEngine.PlaySound(12);
                         Main.editChest = false;
                         Main.npcChatText = string.Empty;
                     }
                     if (editedChestName)
                     {
                         NetMessage.SendData(33, -1, -1, NetworkText.FromLiteral(Main.chest[chest].name), chest, 1f);
                         editedChestName = false;
                     }
                     if (Main.netMode == 1)
                     {
                         if (num45 == chestX && num46 == chestY && chest != -1)
{
                             chest = -1;
                             Recipe.FindRecipes();
                             SoundEngine.PlaySound(11);
                         }
                         else
{
                             NetMessage.SendData(31, -1, -1, null, num45, num46);
                             Main.stackSplit = 600;
                         }
                     }
                     else
                     {
                         piggyBankProjTracker.Clear();
                         voidLensChest.Clear();
                         int num47 = Chest.FindChest(num45, num46);
                         if (num47 != -1)
{
                             Main.stackSplit = 600;
                             if (num47 == chest)
{
                                 chest = -1;
                                 Recipe.FindRecipes();
                                 SoundEngine.PlaySound(11);
                             }
                             else if (num47 != chest && chest == -1)
{
                                 OpenChest(num45, num46, num47);
                                 SoundEngine.PlaySound(10);
                             }
                             else
{
                                 OpenChest(num45, num46, num47);
                                 SoundEngine.PlaySound(12);
                             }
                             Recipe.FindRecipes();
                         }
                     }
                 }
                 else
                 {
                     Main.playerInventory = false;
                     chest = -1;
                     Recipe.FindRecipes();
                     SetTalkNPC(-1);
                     Main.npcChatCornerItem = 0;
                     Main.npcChatText = "";
                     Main.interactedDresserTopLeftX = num45;
                     Main.interactedDresserTopLeftY = num46;
                     Main.OpenClothesWindow();
                 }
             }
             else if (Main.tile[myX, myY].type == 209)
             {
                 flag2 = true;
                 Tile tile2 = Main.tile[myX, myY];
                 int num48 = tile2.frameX % 72 / 18;
                 int num49 = tile2.frameY % 54 / 18;
                 int num50 = myX - num48;
                 int num51 = myY - num49;
                 int num52 = tile2.frameY / 54;
                 int num53 = tile2.frameX / 72;
                 int num54 = -1;
                 if (num48 == 1 || num48 == 2)
                 {
                     num54 = num49;
                 }
                 int num55 = 0;
                 if (num48 == 3 || (num48 == 2 && num53 != 3 && num53 != 4))
                 {
                     num55 = -54;
                 }
                 if (num48 == 0 || (num48 == 1 && num53 != 3 && num53 != 4))
                 {
                     num55 = 54;
                 }
                 if (num52 >= 8 && num55 > 0)
                 {
                     num55 = 0;
                 }
                 if (num52 == 0 && num55 < 0)
                 {
                     num55 = 0;
                 }
                 bool flag10 = false;
                 if (num55 != 0)
                 {
                     for (int num56 = num50; num56 < num50 + 4; num56++)
                     {
                         for (int num57 = num51; num57 < num51 + 3; num57++)
{
                             Main.tile[num56, num57].frameY = (short)(Main.tile[num56, num57].frameY + num55);
                         }
                     }
                     flag10 = true;
                 }
                 if ((num53 == 3 || num53 == 4) && (num54 == 1 || num54 == 0))
                 {
                     num55 = ((num53 == 3) ? 72 : (-72));
                     for (int num58 = num50; num58 < num50 + 4; num58++)
                     {
                         for (int num59 = num51; num59 < num51 + 3; num59++)
{
                             Main.tile[num58, num59].frameX = (short)(Main.tile[num58, num59].frameX + num55);
                         }
                     }
                     flag10 = true;
                 }
                 if (flag10)
                 {
                     NetMessage.SendTileSquare(-1, num50, num51, 4, 3);
                 }
                 if (num54 != -1)
                 {
                     bool flag11 = false;
                     if ((num53 == 3 || num53 == 4) && num54 == 2)
                     {
                         flag11 = true;
                     }
                     if (flag11)
                     {
                         WorldGen.ShootFromCannon(num50, num51, num52, num53 + 1, 0, 0f, whoAmI, fromWire: false);
                     }
                 }
             }
             else if (Main.tile[myX, myY].type == 510 || Main.tile[myX, myY].type == 511)
             {
                 flag2 = true;
                 Tile tile3 = Main.tile[myX, myY];
                 int num60 = tile3.frameX % 36 / 18;
                 int num61 = tile3.frameY % 36 / 18;
                 int num62 = myX - num60;
                 int num63 = myY - num61;
                 int num64 = tile3.frameY / 36;
                 _ = tile3.frameX / 36;
                 int num65 = 0;
                 if (num60 == 0)
                 {
                     num65 = -36;
                 }
                 if (num60 == 1)
                 {
                     num65 = 36;
                 }
                 if (num64 >= 7 && num65 > 0)
                 {
                     num65 = -252;
                 }
                 if (num64 == 0 && num65 < 0)
                 {
                     num65 = 252;
                 }
                 bool flag12 = false;
                 if (num65 != 0)
                 {
                     for (int num66 = num62; num66 < num62 + 2; num66++)
                     {
                         for (int num67 = num63; num67 < num63 + 2; num67++)
{
                             Main.tile[num66, num67].frameY = (short)(Main.tile[num66, num67].frameY + num65);
                         }
                     }
                     flag12 = true;
                 }
                 if (flag12)
                 {
                     NetMessage.SendTileSquare(-1, num62, num63, 2, 2);
                 }
             }
             else if (TileID.Sets.BasicChest[Main.tile[myX, myY].type] || Main.tile[myX, myY].type == 29 || Main.tile[myX, myY].type == 97 || Main.tile[myX, myY].type == 463 || Main.tile[myX, myY].type == 491)
             {
                 flag2 = true;
                 Main.mouseRightRelease = false;
                 int num68 = 0;
                 int num69;
                 for (num69 = Main.tile[myX, myY].frameX / 18; num69 > 1; num69 -= 2)
                 {
                 }
                 num69 = myX - num69;
                 int num70 = myY - Main.tile[myX, myY].frameY / 18;
                 if (Main.tile[myX, myY].type == 29)
                 {
                     num68 = 1;
                 }
                 else if (Main.tile[myX, myY].type == 97)
                 {
                     num68 = 2;
                 }
                 else if (Main.tile[myX, myY].type == 463)
                 {
                     num68 = 3;
                     num69 = ((Main.tile[myX, myY].frameX != 36) ? (num69 + 1) : (num69 - 1));
                     num70 += 2;
                 }
                 else if (Main.tile[myX, myY].type == 491)
                 {
                     num68 = 4;
                     num69 = ((Main.tile[myX, myY].frameX != 36) ? (num69 + 1) : (num69 - 1));
                     num70 += 2;
                 }
                 CloseSign();
                 SetTalkNPC(-1);
                 Main.npcChatCornerItem = 0;
                 Main.npcChatText = "";
                 if (Main.editChest)
                 {
                     SoundEngine.PlaySound(12);
                     Main.editChest = false;
                     Main.npcChatText = string.Empty;
                 }
                 if (editedChestName)
                 {
                     NetMessage.SendData(33, -1, -1, NetworkText.FromLiteral(Main.chest[chest].name), chest, 1f);
                     editedChestName = false;
                 }
                 bool flag13 = Chest.IsLocked(Main.tile[num69, num70]);
                 if (Main.netMode == 1 && num68 == 0 && !flag13)
                 {
                     if (num69 == chestX && num70 == chestY && chest != -1)
                     {
                         chest = -1;
                         Recipe.FindRecipes();
                         SoundEngine.PlaySound(11);
                     }
                     else
                     {
                         if (WorldGen.IsChestRigged(num69, num70))
{
                             _framesLeftEligibleForDeadmansChestDeathAchievement = 600;
                         }
                         NetMessage.SendData(31, -1, -1, null, num69, num70);
                         Main.stackSplit = 600;
                     }
                 }
                 else
                 {
                     int num71 = -1;
                     switch (num68)
                     {
                     case 1:
                         num71 = -2;
                         break;
                     case 2:
                         num71 = -3;
                         break;
                     case 3:
                         num71 = -4;
                         break;
                     case 4:
                         if (disableVoidBag < 0)
{
                             num71 = -5;
                         }
                         break;
                     default:
                     {
                         bool flag14 = false;
                         if (Chest.IsLocked(num69, num70))
{
                             int type2 = Main.tile[num69, num70].type;
                             int num72 = 327;
                             switch (type2)
{
                             case 21:
                                 if (Main.tile[num69, num70].frameX >= 144 && Main.tile[num69, num70].frameX <= 178)
{
                                     num72 = 329;
                                 }
                                 if (Main.tile[num69, num70].frameX >= 828 && Main.tile[num69, num70].frameX <= 1006)
{
                                     int num74 = Main.tile[num69, num70].frameX / 18;
                                     int num75 = 0;
                                     while (num74 >= 2)
{
                                         num74 -= 2;
                                         num75++;
                                     }
                                     num75 -= 23;
                                     num72 = 1533 + num75;
                                 }
                                 break;
                             case 467:
{
                                 int num73 = Main.tile[num69, num70].frameX / 36;
                                 if (num73 == 13)
{
                                     num72 = 4714;
                                 }
                                 break;
                             }
                             }
                             flag14 = true;
                             bool flag15 = false;
                             bool flag16 = num72 != 329;
                             for (int num76 = 0; num76 < 58; num76++)
{
                                 if (inventory[num76].type != num72 || inventory[num76].stack <= 0 || !Chest.Unlock(num69, num70))
{
                                     continue;
                                 }
                                 flag15 = true;
                                 if (flag16)
{
                                     inventory[num76].stack--;
                                     if (inventory[num76].stack <= 0)
{
                                         inventory[num76] = new Item();
                                     }
                                 }
                                 if (Main.netMode == 1)
{
                                     NetMessage.SendData(52, -1, -1, null, whoAmI, 1f, num69, num70);
                                 }
                             }
                             if (!flag15 && useVoidBag())
{
                                 for (int num77 = 0; num77 < 40; num77++)
{
                                     if (bank4.item[num77].type != num72 || bank4.item[num77].stack <= 0 || !Chest.Unlock(num69, num70))
{
                                         continue;
                                     }
                                     if (num72 != 329)
{
                                         bank4.item[num77].stack--;
                                         if (bank4.item[num77].stack <= 0)
{
                                             bank4.item[num77] = new Item();
                                         }
                                     }
                                     if (Main.netMode == 1)
{
                                         NetMessage.SendData(52, -1, -1, null, whoAmI, 1f, num69, num70);
                                     }
                                 }
                             }
                         }
                         if (!flag14)
{
                             num71 = Chest.FindChest(num69, num70);
                         }
                         break;
                     }
                     }
                     if (num71 != -1)
                     {
                         Main.stackSplit = 600;
                         bool num78 = WorldGen.IsChestRigged(num69, num70);
                         if (num71 == chest)
{
                             chest = -1;
                             SoundEngine.PlaySound(11);
                         }
                         else if (num71 != chest && chest == -1)
{
                             OpenChest(num69, num70, num71);
                             SoundEngine.PlaySound(10);
                             if (Main.tile[num69, num70].frameX >= 36 && Main.tile[num69, num70].frameX < 72)
{
                                 AchievementsHelper.HandleSpecialEvent(this, 16);
                             }
                         }
                         else
{
                             OpenChest(num69, num70, num71);
                             SoundEngine.PlaySound(12);
                         }
                         if (num78)
{
                             Wiring.HitSwitch(myX, myY);
                             NetMessage.SendData(59, -1, -1, null, myX, myY);
                             _framesLeftEligibleForDeadmansChestDeathAchievement = 600;
                         }
                         Recipe.FindRecipes();
                     }
                 }
             }
             else if (Main.tile[myX, myY].type == 314 && gravDir == 1f)
             {
                 flag2 = true;
                 bool flag17 = true;
                 if (mount.Active)
                 {
                     if (mount.Cart)
                     {
                         flag17 = false;
                     }
                     else
                     {
                         mount.Dismount(this);
                     }
                 }
                 if (flag17)
                 {
                     LaunchMinecartHook(myX, myY);
                 }
             }
         }
         if (flag2)
         {
             tileInteractionHappened = true;
         }
     }
References Entity.active, Projectile.ai, Projectile.aiStyle, NPC.AnyNPCs(), TileID.Sets.BasicChest, Main.CancelClothesWindow(), Main.chest, WorldGen.CloseDoor(), Main.dayTime, NPC.downedPlantBoss, Main.editChest, Main.editSign, DD2Event.FailureMessage(), Main.fastForwardTimeToDawn, Main.fastForwardTimeToDusk, Chest.FindChest(), Recipe.FindRecipes(), Tile.frameX, Tile.frameY, NetworkText.FromLiteral(), Language.GetTextValue(), Framing.GetTileSafely(), AchievementsHelper.HandleSpecialEvent(), Main.hardMode, Wiring.HitSwitch(), Main.interactedDresserTopLeftX, Main.interactedDresserTopLeftY, ProjectileID.Sets.IsAGolfBall, WorldGen.IsChestRigged(), Chest.IsLocked(), WorldGen.IsLockedDoor(), SoundID.Item11, SoundID.Item149, SoundID.Item2, SoundID.Item37, SoundID.Item4, Projectile.Kill(), WorldGen.KillTile(), WorldGen.LaunchRocket(), WorldGen.LaunchRocketSmall(), Main.moondialCooldown, Main.Moondialing(), Main.mouseRightRelease, Main.myPlayer, Chest.name, Main.netMode, Projectile.NewProjectile(), Animation.NewTemporaryAnimation(), Main.NewText(), UnifiedRandom.Next(), Main.npcChatCornerItem, Main.npcChatText, DD2Event.Ongoing, TEDisplayDoll.OnPlayerInteraction(), TEFoodPlatter.OnPlayerInteraction(), TEHatRack.OnPlayerInteraction(), TEItemFrame.OnPlayerInteraction(), TEWeaponsRack.OnPlayerInteraction(), WiresUI.Open, Main.OpenClothesWindow(), WorldGen.OpenDoor(), Projectile.originatedFromActivableTile, Projectile.owner, Main.playerInventory, SoundEngine.PlaySound(), Main.projectile, Main.pumpkinMoon, Main.rand, Sign.ReadSign(), DD2Event.RequestToSkipWaitTime(), NetMessage.SendData(), NetMessage.SendTemporaryAnimation(), NetMessage.SendTileSquare(), WorldGen.ShiftTallGate(), WorldGen.ShiftTrapdoor(), WorldGen.ShootFromCannon(), Main.sign, Main.snowMoon, NPC.SpawnOnPlayer(), Main.stackSplit, DD2Event.SummonCrystal(), Main.sundialCooldown, Main.Sundialing(), WorldGen.SwitchFountain(), WorldGen.SwitchMB(), WorldGen.SwitchMonolith(), Sign.text, Main.tile, Main.tileSign, Main.time, WorldGen.ToggleGemLock(), BirthdayParty.ToggleManualParty(), Projectile.type, Tile.type, Chest.Unlock(), WorldGen.UnlockDoor(), and DD2Event.WouldFailSpawningHere().