Terraria: Player.SetPlayerDataToOutOfClassFields
SetPlayerDataToOutOfClassFields()
void Player.SetPlayerDataToOutOfClassFields () inline
     {
         Item mouseItem = new Item();
         if (_temporaryItemSlots[0] != null)
         {
             mouseItem = _temporaryItemSlots[0].Clone();
         }
         Main.mouseItem = mouseItem;
         mouseItem = new Item();
         if (_temporaryItemSlots[1] != null)
         {
             mouseItem = _temporaryItemSlots[1].Clone();
         }
         Main.CreativeMenu.SetItembyIndex(mouseItem, 0);
         mouseItem = new Item();
         if (_temporaryItemSlots[2] != null)
         {
             mouseItem = _temporaryItemSlots[2].Clone();
         }
         Main.guideItem = mouseItem;
         mouseItem = new Item();
         if (_temporaryItemSlots[3] != null)
         {
             mouseItem = _temporaryItemSlots[3].Clone();
         }
         Main.reforgeItem = mouseItem;
         CreativePowerManager.Instance.ApplyLoadedDataToPlayer(this);
     }
References CreativePowerManager.ApplyLoadedDataToPlayer(), Item.Clone(), Main.CreativeMenu, Main.guideItem, CreativePowerManager.Instance, Main.mouseItem, Main.reforgeItem, and CreativeUI.SetItembyIndex().