Terraria: Player.ItemCheck_UseTorchGodsFavor
ItemCheck_UseTorchGodsFavor()
void Player.ItemCheck_UseTorchGodsFavor (Item sItem) inline private
     {
         if (sItem.type == 5043 && itemAnimation > 0 && !unlockedBiomeTorches && ItemTimeIsZero)
         {
             ApplyItemTime(sItem);
             unlockedBiomeTorches = true;
             UsingBiomeTorches = true;
             AchievementsHelper.HandleSpecialEvent(this, 24);
             if (Main.netMode == 0)
             {
                 NPC nPC = new NPC();
                 nPC.SetDefaults(664);
                 Main.BestiaryTracker.Kills.RegisterKill(nPC);
             }
             NetMessage.SendData(4, -1, -1, null, whoAmI);
             NetMessage.SendData(51, -1, -1, null, whoAmI, 5f);
         }
     }
References Main.BestiaryTracker, AchievementsHelper.HandleSpecialEvent(), BestiaryUnlocksTracker.Kills, Main.netMode, NPCKillsTracker.RegisterKill(), NetMessage.SendData(), NPC.SetDefaults(), and Item.type.