Terraria: Player.RotatedRelativePoint
RotatedRelativePoint()
Vector2 Player.RotatedRelativePoint (Vector2 pos, bool reverseRotation = false, bool addGfxOffY = true) inline
     {
         float num = (reverseRotation ? (0f - fullRotation) : fullRotation);
         if (sleeping.isSleeping)
         {
             num = 0f;
         }
         Vector2 vector = base.Bottom + new Vector2(0f, gfxOffY);
         int num2 = mount.PlayerOffset / 2 + 4;
         Vector2 vector2 = new Vector2(0f, -num2) + new Vector2(0f, num2).RotatedBy(num);
         if (addGfxOffY)
         {
             pos.Y += gfxOffY;
         }
         pos = vector + (pos - vector).RotatedBy(num) + vector2;
         if (sleeping.isSleeping)
         {
             sleeping.GetSleepingOffsetInfo(this, out var posOffset);
             pos += posOffset;
         }
         if (sitting.isSitting)
         {
             sitting.GetSittingOffsetInfo(this, out var posOffset2, out var seatAdjustment);
             pos += posOffset2 + new Vector2(0f, seatAdjustment);
         }
         return pos;
     }
Referenced by Projectile.AI_019_Spears(), Projectile.AI_019_Spears_Old(), Projectile.AI_075(), Projectile.AI_140_MonkStaffT1(), Projectile.AI_142_MonkStaffT2And3(), Projectile.AI_158_GetHomeLocation(), Projectile.AI_160_Kites(), Projectile.AI_161_RapierStabs(), Projectile.AI_190_NightsEdge(), Projectile.AI_191_TrueNightsEdge(), Mount.DoConfettiMinecartEffect(), Mount.DoExhaustMinecartEffect(), Mount.DoGemMinecartEffect(), Mount.DoSteamMinecartEffect(), Main.DrawProj_FishingLine(), Main.DrawProj_Spear(), Main.DrawProjDirect(), Projectile.FishingCheck(), Main.GetPlayerArmPosition(), Mount.UpdateEffects(), and DelegateMethods.Mount.WolfMouthPosition().