Terraria: Player.GetClosestRollLuck
GetClosestRollLuck() [2/2]
static float Player.GetClosestRollLuck (Vector2 position, int range) inline static
     {
         return Main.player[FindClosest(position, 1, 1)].RollLuck(range);
     }
References Main.player, and RollLuck().
Referenced by WorldGen.KillTile_DropBait(), WorldGen.ShakeTree(), and WorldGen.SpawnThingsFromPot().