Terraria: Player.IsProjectileInteractibleAndInInteractionRange
IsProjectileInteractibleAndInInteractionRange()
bool Player.IsProjectileInteractibleAndInInteractionRange (Projectile proj, ref Vector2 compareSpot) inline
     {
         if (!proj.active)
         {
             return false;
         }
         if (!proj.IsInteractible())
         {
             return false;
         }
         Point point = proj.Hitbox.ClosestPointInRect(compareSpot).ToTileCoordinates();
         if (!IsInTileInteractionRange(point.X, point.Y, TileReachCheckSettings.Simple))
         {
             return false;
         }
         return true;
     }
References Entity.active, Entity.Hitbox, Projectile.IsInteractible(), and TileReachCheckSettings.Simple.
Referenced by Main.TryInteractingWithMoneyTrough(), and Main.TryInteractingWithVoidLens().