Terraria: Player.Yoraiz0rEye
Yoraiz0rEye()
void Player.Yoraiz0rEye () inline
     {
         int num = 0;
         num += bodyFrame.Y / 56;
         if (num >= Main.OffsetsPlayerHeadgear.Length)
         {
             num = 0;
         }
         Vector2 vector = Main.OffsetsPlayerHeadgear[num];
         vector *= Directions;
         Vector2 vector2 = new Vector2(width / 2, height / 2) + vector + (MountedCenter - base.Center);
         sitting.GetSittingOffsetInfo(this, out var posOffset, out var seatAdjustment);
         vector2 += posOffset + new Vector2(0f, seatAdjustment);
         if (face == 19)
         {
             vector2.Y -= 5f * gravDir;
         }
         if (head == 276)
         {
             vector2.X += 2.5f * (float)direction;
         }
         if (mount.Active && mount.Type == 52)
         {
             vector2.X += 14f * (float)direction;
             vector2.Y -= 2f * gravDir;
         }
         float y = -11.5f * gravDir;
         Vector2 vector3 = new Vector2(3 * direction - ((direction == 1) ? 1 : 0), y) + Vector2.UnitY * gfxOffY + vector2;
         Vector2 vector4 = new Vector2(3 * shadowDirection[1] - ((direction == 1) ? 1 : 0), y) + vector2;
         Vector2 vector5 = Vector2.Zero;
         if (mount.Active && mount.Cart)
         {
             int num2 = Math.Sign(velocity.X);
             if (num2 == 0)
             {
                 num2 = direction;
             }
             vector5 = new Vector2(MathHelper.Lerp(0f, -8f, fullRotation / ((float)Math.PI / 4f)), MathHelper.Lerp(0f, 2f, Math.Abs(fullRotation / ((float)Math.PI / 4f)))).RotatedBy(fullRotation);
             if (num2 == Math.Sign(fullRotation))
             {
                 vector5 *= MathHelper.Lerp(1f, 0.6f, Math.Abs(fullRotation / ((float)Math.PI / 4f)));
             }
         }
         if (fullRotation != 0f)
         {
             vector3 = vector3.RotatedBy(fullRotation, fullRotationOrigin);
             vector4 = vector4.RotatedBy(fullRotation, fullRotationOrigin);
         }
         float num3 = 0f;
         Vector2 vector6 = position + vector3 + vector5;
         Vector2 vector7 = oldPosition + vector4 + vector5;
         vector7.Y -= num3 / 2f;
         vector6.Y -= num3 / 2f;
         float num4 = 1f;
         switch (yoraiz0rEye % 10)
         {
         case 1:
             return;
         case 2:
             num4 = 0.5f;
             break;
         case 3:
             num4 = 0.625f;
             break;
         case 4:
             num4 = 0.75f;
             break;
         case 5:
             num4 = 0.875f;
             break;
         case 6:
             num4 = 1f;
             break;
         case 7:
             num4 = 1.1f;
             break;
         }
         if (yoraiz0rEye < 7)
         {
             DelegateMethods.v3_1 = Main.hslToRgb(Main.rgbToHsl(eyeColor).X, 1f, 0.5f).ToVector3() * 0.5f * num4;
             if (velocity != Vector2.Zero)
             {
                 Utils.PlotTileLine(base.Center, base.Center + velocity * 2f, 4f, DelegateMethods.CastLightOpen);
             }
             else
             {
                 Utils.PlotTileLine(base.Left, base.Right, 4f, DelegateMethods.CastLightOpen);
             }
         }
         int num5 = (int)Vector2.Distance(vector6, vector7) / 3 + 1;
         if (Vector2.Distance(vector6, vector7) % 3f != 0f)
         {
             num5++;
         }
         for (float num6 = 1f; num6 <= (float)num5; num6 += 1f)
         {
             Dust obj = Main.dust[Dust.NewDust(base.Center, 0, 0, 182)];
             obj.position = Vector2.Lerp(vector7, vector6, num6 / (float)num5);
             obj.noGravity = true;
             obj.velocity = Vector2.Zero;
             obj.customData = this;
             obj.scale = num4;
             obj.shader = GameShaders.Armor.GetSecondaryShader(cYorai, this);
         }
     }
References GameShaders.Armor, DelegateMethods.CastLightOpen(), Dust.customData, Main.dust, ArmorShaderDataSet.GetSecondaryShader(), Main.hslToRgb(), Dust.NewDust(), Dust.noGravity, Main.OffsetsPlayerHeadgear, Utils.PlotTileLine(), Dust.position, Main.rgbToHsl(), Dust.scale, Dust.shader, DelegateMethods.v3_1, and Dust.velocity.