Terraria: Player.AddBuff
AddBuff()
void Player.AddBuff (int type, int timeToAdd, bool quiet = true, bool foodHack = false) inline
     {
         if (buffImmune[type])
         {
             return;
         }
         bool flag = !quiet && Main.netMode == 1 && Main.pvpBuff[type] && Main.myPlayer != whoAmI;
         if (!flag && BuffID.Sets.IsFedState[type])
         {
             for (int i = 0; i < maxBuffs; i++)
             {
                 if (BuffID.Sets.IsFedState[buffType[i]])
                 {
                     DelBuff(i);
                 }
             }
         }
         int num = AddBuff_DetermineBuffTimeToAdd(type, timeToAdd);
         if (AddBuff_TryUpdatingExistingBuffTime(type, num))
         {
             return;
         }
         if (!quiet && Main.netMode == 1)
         {
             NetMessage.SendData(55, -1, -1, null, whoAmI, type, num);
             if (flag)
             {
                 return;
             }
         }
         AddBuff_RemoveOldPetBuffsOfMatchingType(type);
         AddBuff_RemoveOldMeleeBuffsOfMatchingType(type);
         AddBuff_ActuallyTryToAddTheBuff(type, num);
     }
References BuffID.Sets.IsFedState, Main.myPlayer, Main.netMode, Main.pvpBuff, and NetMessage.SendData().
Referenced by NPC.AI(), NPC.AI_003_Fighters(), Projectile.AI_061_FishingBobber(), NPC.AI_107_ImprovedWalkers(), Projectile.AI_111_DryadsWard(), NPC.AI_123_Deerclops(), ApplyEquipFunctional(), Projectile.Damage(), MessageBuffer.GetData(), Projectile.Kill(), Mount.SetMount(), UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty(), Projectile.StatusPlayer(), Projectile.StatusPvP(), StatusToPlayerPvP(), and UpdateBuffs().