Terraria: Player.ItemCheck_EmitUseVisuals
ItemCheck_EmitUseVisuals()
Rectangle Player.ItemCheck_EmitUseVisuals (Item sItem, Rectangle itemRectangle) inline private
     {
         if (sItem.type == 989 && Main.rand.Next(5) == 0)
         {
             int num = Main.rand.Next(3);
             int num2 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, num switch
             {
                 0 => 15,
                 1 => 57,
                 _ => 58,
             }, direction * 2, 0f, 150, default(Color), 1.3f);
             Main.dust[num2].velocity *= 0.2f;
         }
         if (sItem.type == 2880 && Main.rand.Next(2) == 0)
         {
             int type = Utils.SelectRandom<int>(Main.rand, 226, 229);
             int num3 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, type, direction * 2, 0f, 150);
             Main.dust[num3].velocity *= 0.2f;
             Main.dust[num3].noGravity = true;
         }
         if ((sItem.type == 44 || sItem.type == 45 || sItem.type == 103 || sItem.type == 104) && Main.rand.Next(15) == 0)
         {
             Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 14, direction * 2, 0f, 150, default(Color), 1.3f);
         }
         if (sItem.type == 46 && Main.rand.Next(15) == 0)
         {
             Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 14, direction * 2, 0f, 150, default(Color), 1.3f);
         }
         if (sItem.type == 273 || sItem.type == 675)
         {
             if (Main.rand.Next(5) == 0)
             {
                 Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 14, direction * 2, 0f, 150, default(Color), 1.4f);
             }
             int num4 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 27, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.2f);
             Main.dust[num4].noGravity = true;
             Main.dust[num4].velocity.X /= 2f;
             Main.dust[num4].velocity.Y /= 2f;
         }
         if (sItem.type == 723 && Main.rand.Next(2) == 0)
         {
             int num5 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 64, 0f, 0f, 150, default(Color), 1.2f);
             Main.dust[num5].noGravity = true;
         }
         if (sItem.type == 65)
         {
             if (Main.rand.Next(5) == 0)
             {
                 Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 58, 0f, 0f, 150, default(Color), 1.2f);
             }
             if (Main.rand.Next(10) == 0)
             {
                 Gore.NewGore(new Vector2(itemRectangle.X, itemRectangle.Y), default(Vector2), Main.rand.Next(16, 18));
             }
         }
         if (sItem.type == 3065)
         {
             int num6 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 58, 0f, 0f, 150, default(Color), 1.2f);
             Main.dust[num6].velocity *= 0.5f;
             if (Main.rand.Next(8) == 0)
             {
                 int num7 = Gore.NewGore(new Vector2(itemRectangle.Center.X, itemRectangle.Center.Y), default(Vector2), 16);
                 Main.gore[num7].velocity *= 0.5f;
                 Main.gore[num7].velocity += new Vector2(direction, 0f);
             }
         }
         if (sItem.type == 190)
         {
             int num8 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 40, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 0, default(Color), 1.2f);
             Main.dust[num8].noGravity = true;
         }
         else if (sItem.type == 213 || sItem.type == 5295)
         {
             int num9 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 3, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 0, default(Color), 1.2f);
             Main.dust[num9].noGravity = true;
         }
         if (sItem.type == 121)
         {
             for (int i = 0; i < 2; i++)
             {
                 GetPointOnSwungItemPath(70f, 70f, 0.2f + 0.8f * Main.rand.NextFloat(), GetAdjustedItemScale(sItem), out var location, out var outwardDirection);
                 Vector2 vector = outwardDirection.RotatedBy((float)Math.PI / 2f * (float)direction * gravDir);
                 Dust.NewDustPerfect(location, 6, vector * 4f, 100, default(Color), 2.5f).noGravity = true;
             }
         }
         if (sItem.type == 122 || sItem.type == 217)
         {
             int num10 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 6, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.9f);
             Main.dust[num10].noGravity = true;
         }
         if (sItem.type == 155)
         {
             int num11 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 172, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 0.9f);
             Main.dust[num11].noGravity = true;
             Main.dust[num11].velocity *= 0.1f;
         }
         if (sItem.type == 676 && Main.rand.Next(3) == 0)
         {
             int num12 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 67, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 90, default(Color), 1.5f);
             Main.dust[num12].noGravity = true;
             Main.dust[num12].velocity *= 0.2f;
         }
         if (sItem.type == 3063)
         {
             int num13 = Dust.NewDust(itemRectangle.TopLeft(), itemRectangle.Width, itemRectangle.Height, 66, 0f, 0f, 150, Color.Transparent, 0.85f);
             Main.dust[num13].color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f);
             Main.dust[num13].noGravity = true;
             Main.dust[num13].velocity /= 2f;
         }
         if (sItem.type == 3823)
         {
             Dust dust = Dust.NewDustDirect(itemRectangle.TopLeft(), itemRectangle.Width, itemRectangle.Height, 6, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, Color.Transparent, 0.7f);
             dust.noGravity = true;
             dust.velocity *= 2f;
             dust.fadeIn = 0.9f;
         }
         if (sItem.type == 724 && Main.rand.Next(5) == 0)
         {
             int num14 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 67, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 90, default(Color), 1.5f);
             Main.dust[num14].noGravity = true;
             Main.dust[num14].velocity *= 0.2f;
         }
         if (sItem.type >= 795 && sItem.type <= 802)
         {
             for (int j = 0; j < 2; j++)
             {
                 GetPointOnSwungItemPath(60f, 60f, 0.2f + 0.8f * Main.rand.NextFloat(), GetAdjustedItemScale(sItem), out var location2, out var outwardDirection2);
                 Vector2 vector2 = outwardDirection2.RotatedBy((float)Math.PI / 2f * (float)direction * gravDir);
                 Dust.NewDustPerfect(location2, 5, vector2 * 2f, 100, default(Color), 0.7f + Main.rand.NextFloat() * 0.6f);
                 if (Main.rand.Next(20) == 0)
                 {
                     int num15 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 115, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 140, default(Color), 0.7f);
                     Main.dust[num15].position = location2;
                     Main.dust[num15].fadeIn = 1.2f;
                     Main.dust[num15].noGravity = true;
                     Main.dust[num15].velocity *= 0.25f;
                     Main.dust[num15].velocity += vector2 * 5f;
                 }
             }
         }
         if (sItem.type == 367)
         {
             int num16 = 0;
             if (Main.rand.Next(3) == 0)
             {
                 num16 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 57, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.1f);
                 Main.dust[num16].noGravity = true;
                 Main.dust[num16].velocity.X /= 2f;
                 Main.dust[num16].velocity.Y /= 2f;
                 Main.dust[num16].velocity.X += direction * 2;
             }
             if (Main.rand.Next(4) == 0)
             {
                 num16 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 43, 0f, 0f, 254, default(Color), 0.3f);
                 Main.dust[num16].velocity *= 0f;
             }
         }
         else if (sItem.type != 368)
         {
             _ = sItem.type;
             _ = 674;
         }
         if (sItem.type == 4258 || sItem.type == 4259 || (sItem.type >= 198 && sItem.type <= 203) || (sItem.type >= 3764 && sItem.type <= 3769))
         {
             float num17 = 0.5f;
             float num18 = 0.5f;
             float num19 = 0.5f;
             if (sItem.type == 198 || sItem.type == 3764)
             {
                 num17 *= 0.1f;
                 num18 *= 0.5f;
                 num19 *= 1.2f;
             }
             else if (sItem.type == 199 || sItem.type == 3765)
             {
                 num17 *= 1f;
                 num18 *= 0.2f;
                 num19 *= 0.1f;
             }
             else if (sItem.type == 200 || sItem.type == 3766)
             {
                 num17 *= 0.1f;
                 num18 *= 1f;
                 num19 *= 0.2f;
             }
             else if (sItem.type == 201 || sItem.type == 3767)
             {
                 num17 *= 0.8f;
                 num18 *= 0.1f;
                 num19 *= 1f;
             }
             else if (sItem.type == 202 || sItem.type == 3768)
             {
                 num17 *= 0.8f;
                 num18 *= 0.9f;
                 num19 *= 1f;
             }
             else if (sItem.type == 203 || sItem.type == 3769)
             {
                 num17 *= 0.8f;
                 num18 *= 0.8f;
                 num19 *= 0f;
             }
             else if (sItem.type == 4258 || sItem.type == 4259)
             {
                 num17 *= 0.9f;
                 num18 *= 0.5f;
                 num19 *= 0f;
             }
             Lighting.AddLight((int)((itemLocation.X + 6f + velocity.X) / 16f), (int)((itemLocation.Y - 14f) / 16f), num17, num18, num19);
         }
         if (frostBurn && sItem.melee && !sItem.noMelee && !sItem.noUseGraphic && Main.rand.Next(2) == 0)
         {
             int num20 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 135, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
             Main.dust[num20].noGravity = true;
             Main.dust[num20].velocity *= 0.7f;
             Main.dust[num20].velocity.Y -= 0.5f;
         }
         if (sItem.melee && !sItem.noMelee && !sItem.noUseGraphic && meleeEnchant > 0)
         {
             if (meleeEnchant == 1)
             {
                 if (Main.rand.Next(3) == 0)
                 {
                     int num21 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 171, 0f, 0f, 100);
                     Main.dust[num21].noGravity = true;
                     Main.dust[num21].fadeIn = 1.5f;
                     Main.dust[num21].velocity *= 0.25f;
                 }
             }
             else if (meleeEnchant == 2)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     int num22 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 75, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
                     Main.dust[num22].noGravity = true;
                     Main.dust[num22].velocity *= 0.7f;
                     Main.dust[num22].velocity.Y -= 0.5f;
                 }
             }
             else if (meleeEnchant == 3)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     int num23 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 6, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
                     Main.dust[num23].noGravity = true;
                     Main.dust[num23].velocity *= 0.7f;
                     Main.dust[num23].velocity.Y -= 0.5f;
                 }
             }
             else if (meleeEnchant == 4)
             {
                 int num24 = 0;
                 if (Main.rand.Next(2) == 0)
                 {
                     num24 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 57, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.1f);
                     Main.dust[num24].noGravity = true;
                     Main.dust[num24].velocity.X /= 2f;
                     Main.dust[num24].velocity.Y /= 2f;
                 }
             }
             else if (meleeEnchant == 5)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     int num25 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 169, 0f, 0f, 100);
                     Main.dust[num25].velocity.X += direction;
                     Main.dust[num25].velocity.Y += 0.2f;
                     Main.dust[num25].noGravity = true;
                 }
             }
             else if (meleeEnchant == 6)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     int num26 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 135, 0f, 0f, 100);
                     Main.dust[num26].velocity.X += direction;
                     Main.dust[num26].velocity.Y += 0.2f;
                     Main.dust[num26].noGravity = true;
                 }
             }
             else if (meleeEnchant == 7)
             {
                 if (Main.rand.Next(20) == 0)
                 {
                     int type2 = Main.rand.Next(139, 143);
                     int num27 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, type2, velocity.X, velocity.Y, 0, default(Color), 1.2f);
                     Main.dust[num27].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                     Main.dust[num27].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                     Main.dust[num27].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                     Main.dust[num27].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                     Main.dust[num27].scale *= 1f + (float)Main.rand.Next(-30, 31) * 0.01f;
                 }
                 if (Main.rand.Next(40) == 0)
                 {
                     int type3 = Main.rand.Next(276, 283);
                     int num28 = Gore.NewGore(new Vector2(itemRectangle.X, itemRectangle.Y), velocity, type3);
                     Main.gore[num28].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                     Main.gore[num28].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                     Main.gore[num28].scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                     Main.gore[num28].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                     Main.gore[num28].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                 }
             }
             else if (meleeEnchant == 8 && Main.rand.Next(4) == 0)
             {
                 int num29 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 46, 0f, 0f, 100);
                 Main.dust[num29].noGravity = true;
                 Main.dust[num29].fadeIn = 1.5f;
                 Main.dust[num29].velocity *= 0.25f;
             }
         }
         if (magmaStone && sItem.melee && !sItem.noMelee && !sItem.noUseGraphic && Main.rand.Next(3) != 0)
         {
             int num30 = Dust.NewDust(new Vector2(itemRectangle.X, itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 6, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
             Main.dust[num30].noGravity = true;
             Main.dust[num30].velocity.X *= 2f;
             Main.dust[num30].velocity.Y *= 2f;
         }
         return itemRectangle;
     }
References Lighting.AddLight(), Color, Dust.color, Main.dust, Dust.fadeIn, Main.gore, Main.hslToRgb(), Item.melee, Dust.NewDust(), Dust.NewDustDirect(), Dust.NewDustPerfect(), Gore.NewGore(), UnifiedRandom.Next(), Dust.noGravity, Item.noMelee, Item.noUseGraphic, Dust.position, Main.rand, Dust.scale, Gore.scale, Item.type, Dust.velocity, and Gore.velocity.