Terraria: Player.MowGrassTile
MowGrassTile()
void Player.MowGrassTile (Vector2 thePos) inline private
     {
         Point point = thePos.ToTileCoordinates();
         Tile tile = Main.tile[point.X, point.Y];
         if (tile == null || !WorldGen.CanKillTile(point.X, point.Y, WorldGen.SpecialKillTileContext.MowingTheGrass))
         {
             return;
         }
         ushort num = 0;
         switch (tile.type)
         {
         case 2:
             num = 477;
             break;
         case 109:
             num = 492;
             break;
         }
         if (num != 0)
         {
             int num2 = WorldGen.KillTile_GetTileDustAmount(fail: true, tile);
             for (int i = 0; i < num2; i++)
             {
                 WorldGen.KillTile_MakeTileDust(point.X, point.Y, tile);
             }
             tile.type = num;
             if (Main.netMode == 1)
             {
                 NetMessage.SendTileSquare(-1, point.X, point.Y);
             }
         }
     }
References WorldGen.CanKillTile(), WorldGen.KillTile_GetTileDustAmount(), WorldGen.KillTile_MakeTileDust(), Main.netMode, NetMessage.SendTileSquare(), Main.tile, and Tile.type.