Terraria: Player.TryPlacingAGolfBallNearANearbyTee
TryPlacingAGolfBallNearANearbyTee()
bool Player.TryPlacingAGolfBallNearANearbyTee (Vector2 placePosition) inline
     {
         int num = 0;
         int value = (int)(placePosition.X / 16f) - tileRangeX - num + 1;
         int value2 = (int)(placePosition.X / 16f) + tileRangeX + num - 1;
         int value3 = (int)(placePosition.Y / 16f) - tileRangeY - num + 1;
         int value4 = (int)(placePosition.Y / 16f) + tileRangeY + num - 2;
         value = Utils.Clamp(value, 10, Main.maxTilesX - 10);
         value2 = Utils.Clamp(value2, 10, Main.maxTilesX - 10);
         value3 = Utils.Clamp(value3, 10, Main.maxTilesY - 10);
         value4 = Utils.Clamp(value4, 10, Main.maxTilesY - 10);
         Vector2 value5 = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY);
         if (gravDir == -1f)
         {
             value5.Y = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY;
         }
         Point point = placePosition.ToTileCoordinates();
         List<Tuple<int, int>> list = new List<Tuple<int, int>>();
         for (int i = -2; i <= 2; i++)
         {
             for (int j = -2; j <= 2; j++)
             {
                 int num2 = point.X + i;
                 int num3 = point.Y + j;
                 if (WorldGen.InWorld(num2, num3, 1))
                 {
                     Tile tileSafely = Framing.GetTileSafely(num2, num3);
                     if (tileSafely.active() && tileSafely.type == 494)
                     {
                         list.Add(new Tuple<int, int>(num2, num3));
                         break;
                     }
                 }
             }
         }
         bool result = false;
         if (list.Count > 0)
         {
             float num4 = -1f;
             Tuple<int, int> tuple = list[0];
             for (int k = 0; k < list.Count; k++)
             {
                 float num5 = Vector2.Distance(new Vector2(list[k].Item1, list[k].Item2) * 16f + Vector2.One * 8f, value5);
                 if (num4 == -1f || num5 < num4)
                 {
                     num4 = num5;
                     tuple = list[k];
                 }
             }
             if (Collision.InTileBounds(tuple.Item1, tuple.Item2, value, value3, value2, value4))
             {
                 result = true;
                 for (int l = 0; l < 1000; l++)
                 {
                     if (ProjectileID.Sets.IsAGolfBall[Main.projectile[l].type] && Main.projectile[l].owner == whoAmI)
                     {
                         Main.projectile[l].Kill();
                     }
                 }
                 GetPreferredGolfBallToUse(out var projType);
                 Projectile.NewProjectile(GetProjectileSource_TileInteraction(tuple.Item1, tuple.Item2), (float)(tuple.Item1 * 16) + 8.5f, tuple.Item2 * 16 + 6, 0f, 0f, projType, 0, 0f, whoAmI, 0f, -1f);
             }
         }
         return result;
     }
References Tile.active(), Framing.GetTileSafely(), Collision.InTileBounds(), WorldGen.InWorld(), ProjectileID.Sets.IsAGolfBall, Projectile.Kill(), Main.maxTilesX, Main.maxTilesY, Main.mouseX, Main.mouseY, Projectile.NewProjectile(), Projectile.owner, Main.projectile, Main.screenHeight, Main.screenPosition, Projectile.type, and Tile.type.
Referenced by Projectile.AI_150_GolfClubHelper().