Terraria: Player.Deserialize
Deserialize()
static void Player.Deserialize (PlayerFileData data, Player newPlayer, BinaryReader fileIO, int release, out bool gotToReadName) inline static private
     {
         gotToReadName = false;
         newPlayer.name = fileIO.ReadString();
         gotToReadName = true;
         if (release >= 10)
         {
             if (release >= 17)
             {
                 newPlayer.difficulty = fileIO.ReadByte();
             }
             else if (fileIO.ReadBoolean())
             {
                 newPlayer.difficulty = 2;
             }
         }
         if (release >= 138)
         {
             data.SetPlayTime(new TimeSpan(fileIO.ReadInt64()));
         }
         else
         {
             data.SetPlayTime(TimeSpan.Zero);
         }
         newPlayer.hair = fileIO.ReadInt32();
         if (release >= 82)
         {
             newPlayer.hairDye = fileIO.ReadByte();
         }
         if (release >= 124)
         {
             BitsByte bitsByte = fileIO.ReadByte();
             for (int i = 0; i < 8; i++)
             {
                 newPlayer.hideVisibleAccessory[i] = bitsByte[i];
             }
             bitsByte = fileIO.ReadByte();
             for (int j = 0; j < 2; j++)
             {
                 newPlayer.hideVisibleAccessory[j + 8] = bitsByte[j];
             }
         }
         else if (release >= 83)
         {
             BitsByte bitsByte2 = fileIO.ReadByte();
             for (int k = 0; k < 8; k++)
             {
                 newPlayer.hideVisibleAccessory[k] = bitsByte2[k];
             }
         }
         if (release >= 119)
         {
             newPlayer.hideMisc = fileIO.ReadByte();
         }
         if (release <= 17)
         {
             if (newPlayer.hair == 5 || newPlayer.hair == 6 || newPlayer.hair == 9 || newPlayer.hair == 11)
             {
                 newPlayer.Male = false;
             }
             else
             {
                 newPlayer.Male = true;
             }
         }
         else if (release < 107)
         {
             newPlayer.Male = fileIO.ReadBoolean();
         }
         else
         {
             newPlayer.skinVariant = fileIO.ReadByte();
         }
         if (release < 161 && newPlayer.skinVariant == 7)
         {
             newPlayer.skinVariant = 9;
         }
         newPlayer.statLife = fileIO.ReadInt32();
         newPlayer.statLifeMax = fileIO.ReadInt32();
         if (newPlayer.statLifeMax > 500)
         {
             newPlayer.statLifeMax = 500;
         }
         newPlayer.statMana = fileIO.ReadInt32();
         newPlayer.statManaMax = fileIO.ReadInt32();
         if (newPlayer.statManaMax > 200)
         {
             newPlayer.statManaMax = 200;
         }
         if (newPlayer.statMana > 400)
         {
             newPlayer.statMana = 400;
         }
         if (release >= 125)
         {
             newPlayer.extraAccessory = fileIO.ReadBoolean();
         }
         if (release >= 229)
         {
             newPlayer.unlockedBiomeTorches = fileIO.ReadBoolean();
             newPlayer.UsingBiomeTorches = fileIO.ReadBoolean();
             if (release >= 256)
             {
                 newPlayer.ateArtisanBread = fileIO.ReadBoolean();
             }
             if (release >= 260)
             {
                 newPlayer.usedAegisCrystal = fileIO.ReadBoolean();
                 newPlayer.usedAegisFruit = fileIO.ReadBoolean();
                 newPlayer.usedArcaneCrystal = fileIO.ReadBoolean();
                 newPlayer.usedGalaxyPearl = fileIO.ReadBoolean();
                 newPlayer.usedGummyWorm = fileIO.ReadBoolean();
                 newPlayer.usedAmbrosia = fileIO.ReadBoolean();
             }
         }
         if (release >= 182)
         {
             newPlayer.downedDD2EventAnyDifficulty = fileIO.ReadBoolean();
         }
         if (release >= 128)
         {
             newPlayer.taxMoney = fileIO.ReadInt32();
         }
         if (release >= 254)
         {
             newPlayer.numberOfDeathsPVE = fileIO.ReadInt32();
         }
         if (release >= 254)
         {
             newPlayer.numberOfDeathsPVP = fileIO.ReadInt32();
         }
         newPlayer.hairColor = fileIO.ReadRGB();
         newPlayer.skinColor = fileIO.ReadRGB();
         newPlayer.eyeColor = fileIO.ReadRGB();
         newPlayer.shirtColor = fileIO.ReadRGB();
         newPlayer.underShirtColor = fileIO.ReadRGB();
         newPlayer.pantsColor = fileIO.ReadRGB();
         newPlayer.shoeColor = fileIO.ReadRGB();
         Main.player[Main.myPlayer].hairColor = newPlayer.hairColor;
         Main.player[Main.myPlayer].skinColor = newPlayer.skinColor;
         Main.player[Main.myPlayer].eyeColor = newPlayer.eyeColor;
         Main.player[Main.myPlayer].shirtColor = newPlayer.shirtColor;
         Main.player[Main.myPlayer].underShirtColor = newPlayer.underShirtColor;
         Main.player[Main.myPlayer].pantsColor = newPlayer.pantsColor;
         Main.player[Main.myPlayer].shoeColor = newPlayer.shoeColor;
         if (release >= 38)
         {
             if (release < 124)
             {
                 int num = 11;
                 if (release >= 81)
                 {
                     num = 16;
                 }
                 for (int l = 0; l < num; l++)
                 {
                     int num2 = l;
                     if (num2 >= 8)
                     {
                         num2 += 2;
                     }
                     newPlayer.armor[num2].netDefaults(fileIO.ReadInt32());
                     newPlayer.armor[num2].Prefix(fileIO.ReadByte());
                 }
             }
             else
             {
                 int num3 = 20;
                 for (int m = 0; m < num3; m++)
                 {
                     newPlayer.armor[m].netDefaults(fileIO.ReadInt32());
                     newPlayer.armor[m].Prefix(fileIO.ReadByte());
                 }
             }
             if (release >= 47)
             {
                 int num4 = 3;
                 if (release >= 81)
                 {
                     num4 = 8;
                 }
                 if (release >= 124)
                 {
                     num4 = 10;
                 }
                 for (int n = 0; n < num4; n++)
                 {
                     int num5 = n;
                     newPlayer.dye[num5].netDefaults(fileIO.ReadInt32());
                     newPlayer.dye[num5].Prefix(fileIO.ReadByte());
                 }
             }
             if (release >= 58)
             {
                 for (int num6 = 0; num6 < 58; num6++)
                 {
                     int num7 = fileIO.ReadInt32();
                     if (num7 >= ItemID.Count)
                     {
                         newPlayer.inventory[num6].netDefaults(0);
                         fileIO.ReadInt32();
                         fileIO.ReadByte();
                         if (release >= 114)
{
                             fileIO.ReadBoolean();
                         }
                     }
                     else
                     {
                         newPlayer.inventory[num6].netDefaults(num7);
                         newPlayer.inventory[num6].stack = fileIO.ReadInt32();
                         newPlayer.inventory[num6].Prefix(fileIO.ReadByte());
                         if (release >= 114)
{
                             newPlayer.inventory[num6].favorited = fileIO.ReadBoolean();
                         }
                     }
                 }
             }
             else
             {
                 for (int num8 = 0; num8 < 48; num8++)
                 {
                     int num9 = fileIO.ReadInt32();
                     if (num9 >= ItemID.Count)
                     {
                         newPlayer.inventory[num8].netDefaults(0);
                         fileIO.ReadInt32();
                         fileIO.ReadByte();
                     }
                     else
                     {
                         newPlayer.inventory[num8].netDefaults(num9);
                         newPlayer.inventory[num8].stack = fileIO.ReadInt32();
                         newPlayer.inventory[num8].Prefix(fileIO.ReadByte());
                     }
                 }
             }
             if (release >= 117)
             {
                 if (release < 136)
                 {
                     for (int num10 = 0; num10 < 5; num10++)
                     {
                         if (num10 != 1)
{
                             int num11 = fileIO.ReadInt32();
                             if (num11 >= ItemID.Count)
{
                                 newPlayer.miscEquips[num10].netDefaults(0);
                                 fileIO.ReadByte();
                             }
                             else
{
                                 newPlayer.miscEquips[num10].netDefaults(num11);
                                 newPlayer.miscEquips[num10].Prefix(fileIO.ReadByte());
                             }
                             num11 = fileIO.ReadInt32();
                             if (num11 >= ItemID.Count)
{
                                 newPlayer.miscDyes[num10].netDefaults(0);
                                 fileIO.ReadByte();
                             }
                             else
{
                                 newPlayer.miscDyes[num10].netDefaults(num11);
                                 newPlayer.miscDyes[num10].Prefix(fileIO.ReadByte());
                             }
                         }
                     }
                 }
                 else
                 {
                     for (int num12 = 0; num12 < 5; num12++)
                     {
                         int num13 = fileIO.ReadInt32();
                         if (num13 >= ItemID.Count)
{
                             newPlayer.miscEquips[num12].netDefaults(0);
                             fileIO.ReadByte();
                         }
                         else
{
                             newPlayer.miscEquips[num12].netDefaults(num13);
                             newPlayer.miscEquips[num12].Prefix(fileIO.ReadByte());
                         }
                         num13 = fileIO.ReadInt32();
                         if (num13 >= ItemID.Count)
{
                             newPlayer.miscDyes[num12].netDefaults(0);
                             fileIO.ReadByte();
                         }
                         else
{
                             newPlayer.miscDyes[num12].netDefaults(num13);
                             newPlayer.miscDyes[num12].Prefix(fileIO.ReadByte());
                         }
                     }
                 }
             }
             if (release >= 58)
             {
                 for (int num14 = 0; num14 < 40; num14++)
                 {
                     newPlayer.bank.item[num14].netDefaults(fileIO.ReadInt32());
                     newPlayer.bank.item[num14].stack = fileIO.ReadInt32();
                     newPlayer.bank.item[num14].Prefix(fileIO.ReadByte());
                 }
                 for (int num15 = 0; num15 < 40; num15++)
                 {
                     newPlayer.bank2.item[num15].netDefaults(fileIO.ReadInt32());
                     newPlayer.bank2.item[num15].stack = fileIO.ReadInt32();
                     newPlayer.bank2.item[num15].Prefix(fileIO.ReadByte());
                 }
             }
             else
             {
                 for (int num16 = 0; num16 < 20; num16++)
                 {
                     newPlayer.bank.item[num16].netDefaults(fileIO.ReadInt32());
                     newPlayer.bank.item[num16].stack = fileIO.ReadInt32();
                     newPlayer.bank.item[num16].Prefix(fileIO.ReadByte());
                 }
                 for (int num17 = 0; num17 < 20; num17++)
                 {
                     newPlayer.bank2.item[num17].netDefaults(fileIO.ReadInt32());
                     newPlayer.bank2.item[num17].stack = fileIO.ReadInt32();
                     newPlayer.bank2.item[num17].Prefix(fileIO.ReadByte());
                 }
             }
             if (release >= 182)
             {
                 for (int num18 = 0; num18 < 40; num18++)
                 {
                     newPlayer.bank3.item[num18].netDefaults(fileIO.ReadInt32());
                     newPlayer.bank3.item[num18].stack = fileIO.ReadInt32();
                     newPlayer.bank3.item[num18].Prefix(fileIO.ReadByte());
                 }
             }
             if (release >= 198)
             {
                 for (int num19 = 0; num19 < 40; num19++)
                 {
                     newPlayer.bank4.item[num19].netDefaults(fileIO.ReadInt32());
                     newPlayer.bank4.item[num19].stack = fileIO.ReadInt32();
                     newPlayer.bank4.item[num19].Prefix(fileIO.ReadByte());
                     if (release >= 255)
                     {
                         newPlayer.bank4.item[num19].favorited = fileIO.ReadBoolean();
                     }
                 }
             }
             if (release >= 199)
             {
                 newPlayer.voidVaultInfo = fileIO.ReadByte();
             }
         }
         else
         {
             for (int num20 = 0; num20 < 8; num20++)
             {
                 newPlayer.armor[num20].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                 if (release >= 36)
                 {
                     newPlayer.armor[num20].Prefix(fileIO.ReadByte());
                 }
             }
             if (release >= 6)
             {
                 for (int num21 = 8; num21 < 11; num21++)
                 {
                     newPlayer.armor[num21].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                     if (release >= 36)
                     {
                         newPlayer.armor[num21].Prefix(fileIO.ReadByte());
                     }
                 }
             }
             for (int num22 = 0; num22 < 44; num22++)
             {
                 newPlayer.inventory[num22].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                 newPlayer.inventory[num22].stack = fileIO.ReadInt32();
                 if (release >= 36)
                 {
                     newPlayer.inventory[num22].Prefix(fileIO.ReadByte());
                 }
             }
             if (release >= 15)
             {
                 for (int num23 = 44; num23 < 48; num23++)
                 {
                     newPlayer.inventory[num23].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                     newPlayer.inventory[num23].stack = fileIO.ReadInt32();
                     if (release >= 36)
                     {
                         newPlayer.inventory[num23].Prefix(fileIO.ReadByte());
                     }
                 }
             }
             for (int num24 = 0; num24 < 20; num24++)
             {
                 newPlayer.bank.item[num24].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                 newPlayer.bank.item[num24].stack = fileIO.ReadInt32();
                 if (release >= 36)
                 {
                     newPlayer.bank.item[num24].Prefix(fileIO.ReadByte());
                 }
             }
             if (release >= 20)
             {
                 for (int num25 = 0; num25 < 20; num25++)
                 {
                     newPlayer.bank2.item[num25].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                     newPlayer.bank2.item[num25].stack = fileIO.ReadInt32();
                     if (release >= 36)
                     {
                         newPlayer.bank2.item[num25].Prefix(fileIO.ReadByte());
                     }
                 }
             }
         }
         if (release < 58)
         {
             for (int num26 = 40; num26 < 48; num26++)
             {
                 newPlayer.inventory[num26 + 10] = newPlayer.inventory[num26].Clone();
                 newPlayer.inventory[num26].SetDefaults();
             }
         }
         if (release >= 11)
         {
             int num27 = 22;
             if (release < 74)
             {
                 num27 = 10;
             }
             if (release >= 252)
             {
                 num27 = 44;
             }
             for (int num28 = 0; num28 < num27; num28++)
             {
                 newPlayer.buffType[num28] = fileIO.ReadInt32();
                 newPlayer.buffTime[num28] = fileIO.ReadInt32();
                 if (newPlayer.buffType[num28] == 0)
                 {
                     num28--;
                     num27--;
                 }
             }
         }
         for (int num29 = 0; num29 < 200; num29++)
         {
             int num30 = fileIO.ReadInt32();
             if (num30 == -1)
             {
                 break;
             }
             newPlayer.spX[num29] = num30;
             newPlayer.spY[num29] = fileIO.ReadInt32();
             newPlayer.spI[num29] = fileIO.ReadInt32();
             newPlayer.spN[num29] = fileIO.ReadString();
         }
         if (release >= 16)
         {
             newPlayer.hbLocked = fileIO.ReadBoolean();
         }
         if (release >= 115)
         {
             int num31 = 13;
             for (int num32 = 0; num32 < num31; num32++)
             {
                 newPlayer.hideInfo[num32] = fileIO.ReadBoolean();
             }
         }
         if (release >= 98)
         {
             newPlayer.anglerQuestsFinished = fileIO.ReadInt32();
         }
         if (release >= 162)
         {
             for (int num33 = 0; num33 < 4; num33++)
             {
                 newPlayer.DpadRadial.Bindings[num33] = fileIO.ReadInt32();
             }
         }
         if (release >= 164)
         {
             int num34 = 8;
             if (release >= 167)
             {
                 num34 = 10;
             }
             if (release >= 197)
             {
                 num34 = 11;
             }
             if (release >= 230)
             {
                 num34 = 12;
             }
             for (int num35 = 0; num35 < num34; num35++)
             {
                 newPlayer.builderAccStatus[num35] = fileIO.ReadInt32();
             }
             if (release < 210)
             {
                 newPlayer.builderAccStatus[0] = 1;
             }
             if (release < 249)
             {
                 bool flag = false;
                 for (int num36 = 0; num36 < 58; num36++)
                 {
                     if (newPlayer.inventory[num36].type == 3611)
                     {
                         flag = true;
                         break;
                     }
                 }
                 if (flag)
                 {
                     newPlayer.builderAccStatus[1] = 1;
                 }
             }
         }
         if (release >= 181)
         {
             newPlayer.bartenderQuestLog = fileIO.ReadInt32();
         }
         if (release >= 200)
         {
             newPlayer.dead = fileIO.ReadBoolean();
             if (newPlayer.dead)
             {
                 newPlayer.respawnTimer = Utils.Clamp(fileIO.ReadInt32(), 0, 60000);
             }
         }
         newPlayer.lastTimePlayerWasSaved = 0L;
         if (release >= 202)
         {
             newPlayer.lastTimePlayerWasSaved = fileIO.ReadInt64();
         }
         else
         {
             newPlayer.lastTimePlayerWasSaved = DateTime.UtcNow.ToBinary();
         }
         if (release >= 206)
         {
             newPlayer.golferScoreAccumulated = fileIO.ReadInt32();
         }
         if (release >= 218)
         {
             newPlayer.creativeTracker.Load(fileIO, release);
         }
         if (release >= 214)
         {
             newPlayer.LoadTemporaryItemSlotContents(fileIO);
         }
         newPlayer.savedPerPlayerFieldsThatArentInThePlayerClass = new SavedPlayerDataWithAnnoyingRules();
         CreativePowerManager.Instance.ResetDataForNewPlayer(newPlayer);
         if (release >= 220)
         {
             CreativePowerManager.Instance.LoadToPlayer(newPlayer, fileIO, release);
         }
         if (release >= 253)
         {
             BitsByte bitsByte3 = fileIO.ReadByte();
             newPlayer.unlockedSuperCart = bitsByte3[0];
             newPlayer.enabledSuperCart = bitsByte3[1];
         }
         else
         {
             newPlayer.unlockedSuperCart = newPlayer.HasItemInAnyInventory(3353);
         }
         if (release >= 262)
         {
             int value = fileIO.ReadInt32();
             newPlayer.CurrentLoadoutIndex = Utils.Clamp(value, 0, newPlayer.Loadouts.Length - 1);
             for (int num37 = 0; num37 < newPlayer.Loadouts.Length; num37++)
             {
                 newPlayer.Loadouts[num37].Deserialize(fileIO, release);
             }
         }
         LoadPlayer_LastMinuteFixes(newPlayer);
     }
References anglerQuestsFinished, armor, ateArtisanBread, bank, bank2, bank3, bank4, bartenderQuestLog, Player.SelectionRadial.Bindings, buffTime, buffType, builderAccStatus, Item.Clone(), ItemID.Count, creativeTracker, CurrentLoadoutIndex, dead, EquipmentLoadout.Deserialize(), difficulty, downedDD2EventAnyDifficulty, DpadRadial, dye, enabledSuperCart, extraAccessory, eyeColor, Item.favorited, ItemID.FromLegacyName(), golferScoreAccumulated, hair, hairColor, hairDye, HasItemInAnyInventory(), hbLocked, hideInfo, hideMisc, hideVisibleAccessory, CreativePowerManager.Instance, inventory, Chest.item, L, lastTimePlayerWasSaved, CreativeUnlocksTracker.Load(), Loadouts, LoadTemporaryItemSlotContents(), CreativePowerManager.LoadToPlayer(), Male, miscDyes, miscEquips, Main.myPlayer, name, Item.netDefaults(), numberOfDeathsPVE, numberOfDeathsPVP, pantsColor, Main.player, Item.Prefix(), CreativePowerManager.ResetDataForNewPlayer(), respawnTimer, savedPerPlayerFieldsThatArentInThePlayerClass, Item.SetDefaults(), PlayerFileData.SetPlayTime(), shirtColor, shoeColor, skinColor, skinVariant, spI, spN, spX, spY, Item.stack, statLife, statLifeMax, statMana, statManaMax, taxMoney, Item.type, underShirtColor, unlockedBiomeTorches, unlockedSuperCart, usedAegisCrystal, usedAegisFruit, usedAmbrosia, usedArcaneCrystal, usedGalaxyPearl, usedGummyWorm, UsingBiomeTorches, and voidVaultInfo.