Terraria: Player.TryBouncingBlocks
TryBouncingBlocks()
void Player.TryBouncingBlocks (bool Falling) inline private
     {
         bool num = !wet && !shimmering && (velocity.Y >= 5f || velocity.Y <= -5f);
         bool flag = false;
         bool flag2 = false;
         float num2 = 1f;
         if (!num)
         {
             return;
         }
         bool flag3 = false;
         int num3 = 0;
         foreach (Point touchedTile in TouchedTiles)
         {
             Tile tile = Main.tile[touchedTile.X, touchedTile.Y];
             if (tile != null && tile.active() && tile.nactive() && (flag || Main.tileBouncy[tile.type]))
             {
                 flag3 = true;
                 num3 = touchedTile.Y;
                 break;
             }
         }
         if (!flag3)
         {
             return;
         }
         velocity.Y *= -0.8f;
         if (controlJump)
         {
             velocity.Y = MathHelper.Clamp(velocity.Y, -13f, 13f);
         }
         position.Y = num3 * 16 - ((velocity.Y < 0f) ? height : (-16));
         FloorVisuals(Falling);
         if (flag2)
         {
             Vector2 vector = (fullRotation - (float)Math.PI / 2f).ToRotationVector2();
             if (vector.Y > 0f)
             {
                 vector.Y *= -1f;
             }
             vector.Y = vector.Y * 0.5f + -0.5f;
             float num4 = 0f - vector.Y;
             if (num4 < 0f)
             {
                 num4 = 0f;
             }
             float num5 = num4 * 1.5f + 1f;
             float value = Math.Abs(velocity.Y) * num5 * num2;
             value = MathHelper.Clamp(value, 2f, 16f);
             velocity = vector * value;
             float num6 = 20f;
             Vector2 vector2 = base.Center + (fullRotation + (float)Math.PI / 2f).ToRotationVector2() * num6;
             vector2 = base.Bottom;
             ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.Keybrand, new ParticleOrchestraSettings
             {
                 PositionInWorld = vector2
             }, whoAmI);
         }
         velocity.Y = MathHelper.Clamp(velocity.Y, -20f, 20f);
         if (velocity.Y * gravDir < 0f)
         {
             fallStart = (int)position.Y / 16;
         }
     }
References Tile.active(), Tile.nactive(), ParticleOrchestrator.RequestParticleSpawn(), Main.tile, Main.tileBouncy, and Tile.type.