Terraria: Player.IsItemSlotUnlockedAndUsable
IsItemSlotUnlockedAndUsable()
bool Player.IsItemSlotUnlockedAndUsable (int slot) inline
     {
         switch (slot)
         {
         default:
             return true;
         case 8:
         case 18:
         {
             bool result2 = extraAccessory;
             if (!Main.expertMode && !Main.gameMenu)
             {
                 result2 = false;
             }
             return result2;
         }
         case 9:
         case 19:
         {
             bool result = true;
             if (!Main.masterMode && !Main.gameMenu)
             {
                 result = false;
             }
             return result;
         }
         }
     }
References Main.expertMode, Main.gameMenu, and Main.masterMode.
Referenced by ItemSlot.ArmorSwap(), Main.DrawInventory(), AchievementsHelper.HandleOnEquip(), and AchievementsHelper.OnPlayerEnteredWorld().