Terraria: Player.HorsemansBlade_SpawnPumpkin
HorsemansBlade_SpawnPumpkin()
void Player.HorsemansBlade_SpawnPumpkin (int npcIndex, int dmg, float kb) inline
     {
         Vector2 center = Main.npc[npcIndex].Center;
         int logicCheckScreenHeight = Main.LogicCheckScreenHeight;
         int logicCheckScreenWidth = Main.LogicCheckScreenWidth;
         int num = Main.rand.Next(100, 300);
         int num2 = Main.rand.Next(100, 300);
         num = ((Main.rand.Next(2) != 0) ? (num + (logicCheckScreenWidth / 2 - num)) : (num - (logicCheckScreenWidth / 2 + num)));
         num2 = ((Main.rand.Next(2) != 0) ? (num2 + (logicCheckScreenHeight / 2 - num2)) : (num2 - (logicCheckScreenHeight / 2 + num2)));
         num += (int)position.X;
         num2 += (int)position.Y;
         Vector2 vector = new Vector2(num, num2);
         float num3 = center.X - vector.X;
         float num4 = center.Y - vector.Y;
         float num5 = (float)Math.Sqrt(num3 * num3 + num4 * num4);
         num5 = 8f / num5;
         num3 *= num5;
         num4 *= num5;
         Projectile.NewProjectile(GetProjectileSource_Item(HeldItem), num, num2, num3, num4, 321, dmg, kb, whoAmI, npcIndex);
     }
References Entity.Center, Main.LogicCheckScreenHeight, Main.LogicCheckScreenWidth, Projectile.NewProjectile(), UnifiedRandom.Next(), Main.npc, and Main.rand.
Referenced by Projectile.Damage().