Terraria: Player.UpdateTeleportVisuals
UpdateTeleportVisuals()
void Player.UpdateTeleportVisuals () inline
     {
         if (!(teleportTime > 0f))
         {
             return;
         }
         if (teleportStyle == 0)
         {
             if ((float)Main.rand.Next(100) <= 100f * teleportTime * 2f)
             {
                 int num = Dust.NewDust(new Vector2(getRect().X, getRect().Y), getRect().Width, getRect().Height, 159);
                 Main.dust[num].scale = teleportTime * 1.5f;
                 Main.dust[num].noGravity = true;
                 Main.dust[num].velocity *= 1.1f;
             }
         }
         else if (teleportStyle == 1)
         {
             if ((float)Main.rand.Next(100) <= 100f * teleportTime)
             {
                 int num2 = Dust.NewDust(new Vector2(getRect().X, getRect().Y), getRect().Width, getRect().Height, 164);
                 Main.dust[num2].scale = teleportTime * 1.5f;
                 Main.dust[num2].noGravity = true;
                 Main.dust[num2].velocity *= 1.1f;
             }
         }
         else if (teleportStyle == 2)
         {
             teleportTime = 0.005f;
         }
         else if (teleportStyle == 3)
         {
             teleportTime = 0.005f;
         }
         else if (teleportStyle == 4)
         {
             teleportTime -= 0.02f;
             if ((float)Main.rand.Next(100) <= 100f * teleportTime)
             {
                 Dust obj = Main.dust[Dust.NewDust(position, width, height, 263)];
                 obj.color = PortalHelper.GetPortalColor(lastPortalColorIndex);
                 obj.noLight = true;
                 obj.noGravity = true;
                 obj.scale = 1.2f;
                 obj.fadeIn = 0.4f;
             }
         }
         else if (teleportStyle == 9)
         {
             Rectangle hitbox = base.Hitbox;
             hitbox.Inflate(5, 5);
             if ((float)Main.rand.Next(100) <= 100f * teleportTime)
             {
                 TeleportPylonsSystem.SpawnInWorldDust(lastTeleportPylonStyleUsed, hitbox);
             }
         }
         teleportTime -= 0.005f;
     }
References Dust.color, Main.dust, Dust.fadeIn, PortalHelper.GetPortalColor(), Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.rand, Dust.scale, TeleportPylonsSystem.SpawnInWorldDust(), Dust.velocity, X, and Y.