Terraria: Player.BuyItem
BuyItem()
bool Player.BuyItem (long price, int customCurrency = -1) inline
     {
         if (customCurrency != -1)
         {
             return CustomCurrencyManager.BuyItem(this, price, customCurrency);
         }
         bool overFlowing;
         long num = Utils.CoinsCount(out overFlowing, inventory, 58, 57, 56, 55, 54);
         long num2 = Utils.CoinsCount(out overFlowing, bank.item);
         long num3 = Utils.CoinsCount(out overFlowing, bank2.item);
         long num4 = Utils.CoinsCount(out overFlowing, bank3.item);
         long num5 = Utils.CoinsCount(out overFlowing, bank4.item);
         if (Utils.CoinsCombineStacks(out overFlowing, num, num2, num3, num4, num5) < price)
         {
             return false;
         }
         List<Item[]> list = new List<Item[]>();
         Dictionary<int, List<int>> dictionary = new Dictionary<int, List<int>>();
         List<Point> list2 = new List<Point>();
         List<Point> list3 = new List<Point>();
         List<Point> list4 = new List<Point>();
         List<Point> list5 = new List<Point>();
         List<Point> list6 = new List<Point>();
         List<Point> list7 = new List<Point>();
         list.Add(inventory);
         list.Add(bank.item);
         list.Add(bank2.item);
         list.Add(bank3.item);
         list.Add(bank4.item);
         for (int i = 0; i < list.Count; i++)
         {
             dictionary[i] = new List<int>();
         }
         dictionary[0] = new List<int> { 58, 57, 56, 55, 54 };
         for (int j = 0; j < list.Count; j++)
         {
             for (int k = 0; k < list[j].Length; k++)
             {
                 if (!dictionary[j].Contains(k) && list[j][k].IsACoin)
                 {
                     list3.Add(new Point(j, k));
                 }
             }
         }
         int num6 = 0;
         for (int num7 = list[num6].Length - 1; num7 >= 0; num7--)
         {
             if (!dictionary[num6].Contains(num7) && (list[num6][num7].type == 0 || list[num6][num7].stack == 0))
             {
                 list2.Add(new Point(num6, num7));
             }
         }
         num6 = 1;
         for (int num8 = list[num6].Length - 1; num8 >= 0; num8--)
         {
             if (!dictionary[num6].Contains(num8) && (list[num6][num8].type == 0 || list[num6][num8].stack == 0))
             {
                 list4.Add(new Point(num6, num8));
             }
         }
         num6 = 2;
         for (int num9 = list[num6].Length - 1; num9 >= 0; num9--)
         {
             if (!dictionary[num6].Contains(num9) && (list[num6][num9].type == 0 || list[num6][num9].stack == 0))
             {
                 list5.Add(new Point(num6, num9));
             }
         }
         num6 = 3;
         for (int num10 = list[num6].Length - 1; num10 >= 0; num10--)
         {
             if (!dictionary[num6].Contains(num10) && (list[num6][num10].type == 0 || list[num6][num10].stack == 0))
             {
                 list6.Add(new Point(num6, num10));
             }
         }
         num6 = 4;
         for (int num11 = list[num6].Length - 1; num11 >= 0; num11--)
         {
             if (!dictionary[num6].Contains(num11) && (list[num6][num11].type == 0 || list[num6][num11].stack == 0))
             {
                 list7.Add(new Point(num6, num11));
             }
         }
         if (TryPurchasing(price, list, list3, list2, list4, list5, list6, list7))
         {
             return false;
         }
         return true;
     }
References CustomCurrencyManager.BuyItem(), Utils.CoinsCombineStacks(), and Utils.CoinsCount().
Referenced by ItemSlot.HandleShopSlot().