Terraria: Player.CopyVisuals
CopyVisuals()
void Player.CopyVisuals (Player other) inline
     {
         skinVariant = other.skinVariant;
         direction = other.direction;
         selectedItem = other.selectedItem;
         extraAccessory = other.extraAccessory;
         skinColor = other.skinColor;
         eyeColor = other.eyeColor;
         hair = other.hair;
         hairColor = other.hairColor;
         shirtColor = other.shirtColor;
         underShirtColor = other.underShirtColor;
         pantsColor = other.pantsColor;
         shoeColor = other.shoeColor;
         position = other.position;
         velocity = other.velocity;
         statLife = other.statLife;
         statLifeMax = other.statLifeMax;
         statLifeMax2 = other.statLifeMax2;
         statMana = other.statMana;
         statManaMax = other.statManaMax;
         statManaMax2 = other.statManaMax2;
         hideMisc = other.hideMisc;
         for (int i = 0; i < 59; i++)
         {
             inventory[i] = other.inventory[i].Clone();
             if (i < armor.Length)
             {
                 armor[i] = other.armor[i].Clone();
             }
             if (i < dye.Length)
             {
                 dye[i] = other.dye[i].Clone();
             }
             if (i < miscEquips.Length)
             {
                 miscEquips[i] = other.miscEquips[i].Clone();
             }
             if (i < miscDyes.Length)
             {
                 miscDyes[i] = other.miscDyes[i].Clone();
             }
             if (i < hideVisibleAccessory.Length)
             {
                 hideVisibleAccessory[i] = other.hideVisibleAccessory[i];
             }
         }
     }
References armor, Item.Clone(), Entity.direction, dye, extraAccessory, eyeColor, hair, hairColor, hideMisc, hideVisibleAccessory, inventory, miscDyes, miscEquips, pantsColor, Entity.position, selectedItem, shirtColor, shoeColor, skinColor, skinVariant, statLife, statLifeMax, statLifeMax2, statMana, statManaMax, statManaMax2, underShirtColor, and Entity.velocity.
Referenced by Main.DrawSuperSpecialProjectiles(), and Segments.PlayerSegment.ResetPlayerAnimation().