Terraria: Player.SavePlayer
SavePlayer()
static void Player.SavePlayer (PlayerFileData playerFile, bool skipMapSave = false) inline static
     {
         try
         {
             Main.Achievements.Save();
             InternalSaveMap(playerFile.IsCloudSave);
             if (!Main.ServerSideCharacter)
             {
                 FileUtilities.ProtectedInvoke(delegate
                 {
                     InternalSavePlayerFile(playerFile);
                 });
             }
         }
         catch (Exception exception)
         {
             FancyErrorPrinter.ShowFileSavingFailError(exception, playerFile.Path);
             throw;
         }
     }
References Main.Achievements, FileData.IsCloudSave, FileData.Path, FileUtilities.ProtectedInvoke(), AchievementManager.Save(), Main.ServerSideCharacter, and FancyErrorPrinter.ShowFileSavingFailError().
Referenced by PlayerFileData.CreateAndSave(), Netplay.InnerClientLoop(), PlayerFileData.Rename(), WorldGen.SaveAndQuitCallBack(), and WorldGen.saveToonWhilePlayingCallBack().