Terraria: Player.CheckCrackedBrickBreak
CheckCrackedBrickBreak()
void Player.CheckCrackedBrickBreak () inline
     {
         if (shimmering)
         {
             return;
         }
         bool flag = false;
         if ((float)Main.rand.Next(2, 12) < Math.Abs(velocity.X))
         {
             flag = true;
         }
         if ((float)Main.rand.Next(2, 12) < velocity.Y)
         {
             flag = true;
         }
         if (flag && velocity.Y < 1f)
         {
             Point point = (base.Bottom + Vector2.UnitY).ToTileCoordinates();
             Point point2 = (base.BottomLeft + Vector2.UnitY).ToTileCoordinates();
             Point point3 = (base.BottomRight + Vector2.UnitY).ToTileCoordinates();
             if ((WorldGen.SolidTileAllowBottomSlope(point.X, point.Y) && !TileID.Sets.CrackedBricks[Main.tile[point.X, point.Y].type]) || (WorldGen.SolidTileAllowBottomSlope(point2.X, point2.Y) && !TileID.Sets.CrackedBricks[Main.tile[point2.X, point2.Y].type]) || (WorldGen.SolidTileAllowBottomSlope(point3.X, point3.Y) && !TileID.Sets.CrackedBricks[Main.tile[point3.X, point3.Y].type]))
             {
                 flag = false;
             }
         }
         if (!flag)
         {
             return;
         }
         Vector2 vector = position + velocity;
         flag = false;
         int num = (int)(vector.X / 16f);
         int num2 = (int)((vector.X + (float)width) / 16f);
         int num3 = (int)((position.Y + (float)height + 1f) / 16f);
         Rectangle rect = getRect();
         rect.Inflate(1, 1);
         for (int i = num; i <= num2; i++)
         {
             for (int j = num3; j <= num3 + 1 && Main.tile[i, j] != null; j++)
             {
                 if (Main.tile[i, j].nactive() && !WorldGen.SolidTile(i, j - 1) && TileID.Sets.CrackedBricks[Main.tile[i, j].type] && new Rectangle(i * 16, j * 16, 16, 16).Intersects(rect))
                 {
                     flag = true;
                     if (velocity.Y > 1f)
                     {
                         velocity.Y = 1f;
                     }
                     NetMessage.SendData(13, -1, -1, null, whoAmI);
                 }
             }
         }
         if (!flag)
         {
             return;
         }
         num = (int)((vector.X - 16f - 8f) / 16f);
         num2 = (int)((vector.X + (float)width + 16f + 8f) / 16f);
         for (int k = num; k <= num2; k++)
         {
             for (int l = num3; l <= num3 + 2; l++)
             {
                 if (Main.tile[k, l].nactive() && !WorldGen.SolidTile(k, l - 1) && TileID.Sets.CrackedBricks[Main.tile[k, l].type])
                 {
                     WorldGen.KillTile(k, l);
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 20, k, l);
                     }
                 }
             }
         }
     }
References TileID.Sets.CrackedBricks, WorldGen.KillTile(), Tile.nactive(), Main.netMode, UnifiedRandom.Next(), Main.rand, NetMessage.SendData(), WorldGen.SolidTile(), WorldGen.SolidTileAllowBottomSlope(), Main.tile, and Tile.type.