Terraria: Player.ApplyCoating
ApplyCoating()
void Player.ApplyCoating (int x, int y, bool paintingAWall, bool applyItemAnimation, Item targetItem) inline private
     {
         byte paintCoating = targetItem.paintCoating;
         if (paintingAWall)
         {
             if (WorldGen.paintCoatWall(x, y, paintCoating, broadcast: true))
             {
                 targetItem.stack--;
                 if (targetItem.stack <= 0)
                 {
                     targetItem.SetDefaults();
                 }
                 if (applyItemAnimation)
                 {
                     ApplyItemTime(inventory[selectedItem], wallSpeed);
                 }
             }
         }
         else if (WorldGen.paintCoatTile(x, y, paintCoating, broadcast: true))
         {
             targetItem.stack--;
             if (targetItem.stack <= 0)
             {
                 targetItem.SetDefaults();
             }
             if (applyItemAnimation)
             {
                 ApplyItemTime(inventory[selectedItem], tileSpeed);
             }
         }
     }
References Item.paintCoating, WorldGen.paintCoatTile(), WorldGen.paintCoatWall(), Item.SetDefaults(), and Item.stack.