Terraria: Player.InternalSavePlayerFile
InternalSavePlayerFile()
static void Player.InternalSavePlayerFile (PlayerFileData playerFile) inline static private
     {
         if (playerFile.ServerSideCharacter)
         {
             return;
         }
         string path = playerFile.Path;
         Player player = playerFile.Player;
         bool isCloudSave = playerFile.IsCloudSave;
         if (string.IsNullOrEmpty(path))
         {
             return;
         }
         if (FileUtilities.Exists(path, isCloudSave))
         {
             FileUtilities.Copy(path, path + ".bak", isCloudSave);
         }
         RijndaelManaged rijndaelManaged = new RijndaelManaged();
         using Stream stream = (isCloudSave ? ((Stream)new MemoryStream(2000)) : ((Stream)new FileStream(path, FileMode.Create)));
         using CryptoStream cryptoStream = new CryptoStream(stream, rijndaelManaged.CreateEncryptor(ENCRYPTION_KEY, ENCRYPTION_KEY), CryptoStreamMode.Write);
         using BinaryWriter binaryWriter = new BinaryWriter(cryptoStream);
         binaryWriter.Write(279);
         playerFile.Metadata.Write(binaryWriter);
         Serialize(playerFile, player, binaryWriter);
         binaryWriter.Flush();
         cryptoStream.FlushFinalBlock();
         stream.Flush();
         if (isCloudSave && SocialAPI.Cloud != null)
         {
             SocialAPI.Cloud.Write(playerFile.Path, ((MemoryStream)stream).ToArray());
         }
     }
References SocialAPI.Cloud, FileUtilities.Copy(), FileUtilities.Exists(), FileData.IsCloudSave, FileData.Metadata, FileData.Path, PlayerFileData.Player, PlayerFileData.ServerSideCharacter, FileMetadata.Write(), and CloudSocialModule.Write().