Terraria: Player.UpdateLifeRegen
UpdateLifeRegen()
void Player.UpdateLifeRegen () inline
     {
         bool flag = false;
         if (shinyStone && IsStandingStillForSpecialEffects && itemAnimation == 0)
         {
             flag = true;
         }
         if (poisoned)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegenTime = 0f;
             lifeRegen -= 4;
         }
         if (venom)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegenTime = 0f;
             lifeRegen -= 30;
         }
         if (onFire)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegenTime = 0f;
             lifeRegen -= 8;
         }
         if (onFire3)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegenTime = 0f;
             lifeRegen -= 8;
         }
         if (onFrostBurn)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegenTime = 0f;
             lifeRegen -= 16;
         }
         if (onFrostBurn2)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegenTime = 0f;
             lifeRegen -= 16;
         }
         if (onFire2)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegenTime = 0f;
             lifeRegen -= 24;
         }
         if (burned)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegenTime = 0f;
             lifeRegen -= 60;
             moveSpeed *= 0.5f;
         }
         if (suffocating)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegenTime = 0f;
             lifeRegen -= 40;
         }
         if (electrified)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegenTime = 0f;
             lifeRegen -= 8;
             if (controlLeft || controlRight)
             {
                 lifeRegen -= 32;
             }
         }
         if (tongued && Main.expertMode)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             lifeRegenTime = 0f;
             lifeRegen -= 100;
         }
         if (honey && lifeRegen < 0)
         {
             lifeRegen += 4;
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
         }
         if (lifeRegen < 0 && nebulaLevelLife > 0)
         {
             lifeRegen = 0;
         }
         if (flag && lifeRegen < 0)
         {
             lifeRegen /= 2;
         }
         lifeRegenTime += 1f;
         if (usedAegisCrystal)
         {
             lifeRegenTime += 0.2f;
         }
         if (crimsonRegen)
         {
             lifeRegenTime += 1f;
         }
         if (soulDrain > 0)
         {
             lifeRegenTime += 2f;
         }
         if (flag)
         {
             if (lifeRegenTime > 90f && lifeRegenTime < 1800f)
             {
                 lifeRegenTime = 1800f;
             }
             lifeRegenTime += 4f;
             lifeRegen += 4;
         }
         if (honey)
         {
             lifeRegenTime += 2f;
             lifeRegen += 2;
         }
         if (starving)
         {
             if (lifeRegen > 0)
             {
                 lifeRegen = 0;
             }
             if (lifeRegenCount > 0)
             {
                 lifeRegenCount = 0;
             }
             if (lifeRegenTime > 0f)
             {
                 lifeRegenTime = 0f;
             }
             int num = 3000;
             int num2 = 120 * statLifeMax2 / num;
             if (num2 < 4)
             {
                 num2 = 4;
             }
             lifeRegen = -num2;
         }
         if (soulDrain > 0)
         {
             int num3 = (5 + soulDrain) / 2;
             lifeRegenTime += num3;
             lifeRegen += num3;
         }
         if (heartyMeal)
         {
             int num4 = 3 * 120 / 60;
             lifeRegen += num4;
         }
         if (whoAmI == Main.myPlayer && Main.SceneMetrics.HasCampfire)
         {
             lifeRegen++;
         }
         if (whoAmI == Main.myPlayer && Main.SceneMetrics.HasHeartLantern)
         {
             lifeRegen += 2;
         }
         if (bleed)
         {
             lifeRegenTime = 0f;
         }
         float num5 = 0f;
         if (lifeRegenTime >= 300f)
         {
             num5 += 1f;
         }
         if (lifeRegenTime >= 600f)
         {
             num5 += 1f;
         }
         if (lifeRegenTime >= 900f)
         {
             num5 += 1f;
         }
         if (lifeRegenTime >= 1200f)
         {
             num5 += 1f;
         }
         if (lifeRegenTime >= 1500f)
         {
             num5 += 1f;
         }
         if (lifeRegenTime >= 1800f)
         {
             num5 += 1f;
         }
         if (lifeRegenTime >= 2400f)
         {
             num5 += 1f;
         }
         if (lifeRegenTime >= 3000f)
         {
             num5 += 1f;
         }
         if (flag)
         {
             float num6 = lifeRegenTime - 3000f;
             num6 /= 300f;
             if (num6 > 0f)
             {
                 if (num6 > 30f)
                 {
                     num6 = 30f;
                 }
                 num5 += num6;
             }
         }
         else if (lifeRegenTime >= 3600f)
         {
             num5 += 1f;
             lifeRegenTime = 3600f;
         }
         if (sitting.isSitting || sleeping.isSleeping)
         {
             lifeRegenTime += 3f;
             num5 *= 1.3f;
         }
         if (sitting.isSitting && sitting.details.IsAToilet)
         {
             TryToPoop();
         }
         num5 = ((velocity.X != 0f && grappling[0] <= 0) ? (num5 * 0.5f) : (num5 * 1.25f));
         if (crimsonRegen)
         {
             num5 *= 1.5f;
         }
         if (shinyStone)
         {
             num5 *= 1.1f;
         }
         if (whoAmI == Main.myPlayer && Main.SceneMetrics.HasCampfire)
         {
             num5 *= 1.1f;
         }
         if (Main.expertMode && !wellFed)
         {
             num5 = ((!shinyStone) ? (num5 / 2f) : (num5 * 0.75f));
         }
         if (rabid)
         {
             num5 = ((!shinyStone) ? (num5 / 2f) : (num5 * 0.75f));
         }
         float num7 = (float)statLifeMax2 / 400f * 0.85f + 0.15f;
         num5 *= num7;
         lifeRegen += (int)Math.Round(num5);
         lifeRegenCount += lifeRegen;
         if (palladiumRegen)
         {
             lifeRegenCount += 4;
         }
         if (flag && lifeRegen > 0 && statLife < statLifeMax2)
         {
             lifeRegenCount++;
             if (flag && ((float)Main.rand.Next(30000) < lifeRegenTime || Main.rand.Next(30) == 0))
             {
                 int num8 = Dust.NewDust(position, width, height, 55, 0f, 0f, 200, default(Color), 0.5f);
                 Main.dust[num8].noGravity = true;
                 Main.dust[num8].velocity *= 0.75f;
                 Main.dust[num8].fadeIn = 1.3f;
                 Vector2 vector = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                 vector.Normalize();
                 vector *= (float)Main.rand.Next(50, 100) * 0.04f;
                 Main.dust[num8].velocity = vector;
                 vector.Normalize();
                 vector *= 34f;
                 Main.dust[num8].position = base.Center - vector;
             }
         }
         while (lifeRegenCount >= 120)
         {
             lifeRegenCount -= 120;
             if (statLife < statLifeMax2)
             {
                 statLife++;
                 if (crimsonRegen)
                 {
                     for (int i = 0; i < 10; i++)
                     {
                         int num9 = Dust.NewDust(position, width, height, 5, 0f, 0f, 175, default(Color), 1.75f);
                         Main.dust[num9].noGravity = true;
                         Main.dust[num9].velocity *= 0.75f;
                         int num10 = Main.rand.Next(-40, 41);
                         int num11 = Main.rand.Next(-40, 41);
                         Main.dust[num9].position.X += num10;
                         Main.dust[num9].position.Y += num11;
                         Main.dust[num9].velocity.X = (float)(-num10) * 0.075f;
                         Main.dust[num9].velocity.Y = (float)(-num11) * 0.075f;
                     }
                 }
             }
             if (statLife > statLifeMax2)
             {
                 statLife = statLifeMax2;
             }
         }
         if (burned || suffocating || (tongued && Main.expertMode))
         {
             while (lifeRegenCount <= -600)
             {
                 lifeRegenCount += 600;
                 statLife -= 5;
                 CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, 5, dramatic: false, dot: true);
                 if (statLife <= 0 && whoAmI == Main.myPlayer)
                 {
                     if (suffocating)
                     {
                         KillMe(PlayerDeathReason.ByOther(7), 10.0, 0);
                     }
                     else if (tongued)
                     {
                         KillMe(PlayerDeathReason.ByOther(12), 10.0, 0);
                     }
                     else
                     {
                         KillMe(PlayerDeathReason.ByOther(8), 10.0, 0);
                     }
                 }
             }
             return;
         }
         if (starving)
         {
             int num12 = statLifeMax2 / 50;
             if (num12 < 2)
             {
                 num12 = 2;
             }
             int num13 = ((ZoneDesert || ZoneSnow) ? (num12 * 2) : num12);
             int num14 = 120 * num12;
             while (lifeRegenCount <= -num14)
             {
                 lifeRegenCount += num14;
                 statLife -= num13;
                 CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, num13, dramatic: false, dot: true);
                 if (statLife <= 0 && whoAmI == Main.myPlayer)
                 {
                     KillMe(PlayerDeathReason.ByOther(18), 10.0, 0);
                 }
             }
             return;
         }
         while (lifeRegenCount <= -120)
         {
             if (lifeRegenCount <= -480)
             {
                 lifeRegenCount += 480;
                 statLife -= 4;
                 CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, 4, dramatic: false, dot: true);
             }
             else if (lifeRegenCount <= -360)
             {
                 lifeRegenCount += 360;
                 statLife -= 3;
                 CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, 3, dramatic: false, dot: true);
             }
             else if (lifeRegenCount <= -240)
             {
                 lifeRegenCount += 240;
                 statLife -= 2;
                 CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, 2, dramatic: false, dot: true);
             }
             else
             {
                 lifeRegenCount += 120;
                 statLife--;
                 CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, 1, dramatic: false, dot: true);
             }
             if (statLife <= 0 && whoAmI == Main.myPlayer)
             {
                 if (poisoned || venom)
                 {
                     KillMe(PlayerDeathReason.ByOther(9), 10.0, 0);
                 }
                 else if (electrified)
                 {
                     KillMe(PlayerDeathReason.ByOther(10), 10.0, 0);
                 }
                 else
                 {
                     KillMe(PlayerDeathReason.ByOther(8), 10.0, 0);
                 }
             }
         }
     }
References PlayerDeathReason.ByOther(), Color, Main.dust, Main.expertMode, Dust.fadeIn, SceneMetrics.HasCampfire, SceneMetrics.HasHeartLantern, CombatText.LifeRegen, Main.myPlayer, Dust.NewDust(), CombatText.NewText(), UnifiedRandom.Next(), Dust.noGravity, Dust.position, Main.rand, Main.SceneMetrics, and Dust.velocity.