Terraria: Player.GetItem_FillIntoOccupiedSlot
GetItem_FillIntoOccupiedSlot()
bool Player.GetItem_FillIntoOccupiedSlot (int plr, Item newItem, GetItemSettings settings, Item returnItem, int i) inline private
     {
         if (inventory[i].type > 0 && inventory[i].stack < inventory[i].maxStack && returnItem.IsTheSameAs(inventory[i]))
         {
             if (newItem.IsACoin)
             {
                 SoundEngine.PlaySound(38, (int)position.X, (int)position.Y);
             }
             else
             {
                 SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
             }
             if (returnItem.stack + inventory[i].stack <= inventory[i].maxStack)
             {
                 inventory[i].stack += returnItem.stack;
                 if (!settings.NoText)
                 {
                     PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, returnItem.stack, noStack: false, settings.LongText);
                 }
                 DoCoins(i);
                 if (plr == Main.myPlayer)
                 {
                     Recipe.FindRecipes();
                 }
                 AchievementsHelper.NotifyItemPickup(this, returnItem);
                 settings.HandlePostAction(inventory[i]);
                 return true;
             }
             AchievementsHelper.NotifyItemPickup(this, returnItem, inventory[i].maxStack - inventory[i].stack);
             returnItem.stack -= inventory[i].maxStack - inventory[i].stack;
             if (!settings.NoText)
             {
                 PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, inventory[i].maxStack - inventory[i].stack, noStack: false, settings.LongText);
             }
             inventory[i].stack = inventory[i].maxStack;
             DoCoins(i);
             if (plr == Main.myPlayer)
             {
                 Recipe.FindRecipes();
             }
             settings.HandlePostAction(inventory[i]);
         }
         return false;
     }
References Recipe.FindRecipes(), GetItemSettings.HandlePostAction(), Item.IsACoin, Item.IsTheSameAs(), GetItemSettings.LongText, Item.maxStack, Main.myPlayer, PopupText.NewText(), GetItemSettings.NoText, AchievementsHelper.NotifyItemPickup(), SoundEngine.PlaySound(), and Item.stack.