Terraria: Player.TryDroppingSingleItem
TryDroppingSingleItem()
void Player.TryDroppingSingleItem (IEntitySource source, Item theItem) inline
     {
         if (theItem.stack > 0)
         {
             int num = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, theItem.type);
             Item obj = Main.item[num];
             obj.netDefaults(theItem.netID);
             obj.Prefix(theItem.prefix);
             obj.stack = theItem.stack;
             obj.velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
             obj.velocity.X = (float)Main.rand.Next(-20, 21) * 0.2f;
             obj.noGrabDelay = 100;
             obj.newAndShiny = false;
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(21, -1, -1, null, num);
             }
         }
         theItem.TurnToAir(fullReset: true);
     }
References Main.item, Item.netDefaults(), Item.netID, Main.netMode, Item.newAndShiny, Item.NewItem(), UnifiedRandom.Next(), Item.noGrabDelay, Item.prefix, Item.Prefix(), Main.rand, NetMessage.SendData(), Item.stack, Item.TurnToAir(), Item.type, and Entity.velocity.
Referenced by EquipmentLoadout.TryDroppingItems().