Terraria: Player.CheckDrowning
CheckDrowning()
void Player.CheckDrowning () inline
     {
         bool flag = Collision.DrownCollision(position, width, height, gravDir);
         if (armor[0].type == 250 || armor[0].type == 4275)
         {
             flag = true;
         }
         if (inventory[selectedItem].type == 186 && itemAnimation == 0)
         {
             try
             {
                 int num = (int)((position.X + (float)(width / 2) + (float)(6 * direction)) / 16f);
                 int num2 = 0;
                 if (gravDir == -1f)
                 {
                     num2 = height;
                 }
                 int num3 = (int)((position.Y + (float)num2 - 44f * gravDir) / 16f);
                 if (Main.tile[num, num3] != null && Main.tile[num, num3].liquid < 128)
                 {
                     if (Main.tile[num, num3] == null)
                     {
                         Main.tile[num, num3] = new Tile();
                     }
                     if (!Main.tile[num, num3].active() || !Main.tileSolid[Main.tile[num, num3].type] || Main.tileSolidTop[Main.tile[num, num3].type])
                     {
                         flag = false;
                     }
                 }
             }
             catch
             {
             }
         }
         if (gills)
         {
             flag = Main.getGoodWorld && !flag;
         }
         if (shimmering)
         {
             flag = false;
         }
         if (mount.Active && mount.Type == 4)
         {
             flag = false;
         }
         if (Main.myPlayer == whoAmI)
         {
             if (accMerman)
             {
                 if (flag)
                 {
                     merman = true;
                 }
                 flag = false;
             }
             if (flag)
             {
                 breathCD++;
                 if (breathCD >= breathCDMax)
                 {
                     breathCD = 0;
                     breath--;
                     if (breath == 0)
                     {
                         SoundEngine.PlaySound(23);
                     }
                     if (breath <= 0)
                     {
                         lifeRegenTime = 0f;
                         breath = 0;
                         statLife -= 2;
                         if (statLife <= 0)
{
                             statLife = 0;
                             KillMe(PlayerDeathReason.ByOther(1), 10.0, 0);
                         }
                     }
                 }
             }
             else
             {
                 breath += 3;
                 if (breath > breathMax)
                 {
                     breath = breathMax;
                 }
                 breathCD = 0;
             }
         }
         if (flag && Main.rand.Next(20) == 0 && !lavaWet && !honeyWet)
         {
             int num4 = 0;
             if (gravDir == -1f)
             {
                 num4 += height - 12;
             }
             if (inventory[selectedItem].type == 186)
             {
                 Dust.NewDust(new Vector2(position.X + (float)(10 * direction) + 4f, position.Y + (float)num4 - 54f * gravDir), width - 8, 8, 34, 0f, 0f, 0, default(Color), 1.2f);
             }
             else
             {
                 Dust.NewDust(new Vector2(position.X + (float)(12 * direction), position.Y + (float)num4 + 4f * gravDir), width - 8, 8, 34, 0f, 0f, 0, default(Color), 1.2f);
             }
         }
     }
References Tile.active(), PlayerDeathReason.ByOther(), Color, Collision.DrownCollision(), Main.getGoodWorld, Tile.liquid, Main.myPlayer, Dust.NewDust(), UnifiedRandom.Next(), SoundEngine.PlaySound(), Main.rand, Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.