Terraria: Player.PlaceThing_Tiles_PlaceIt
PlaceThing_Tiles_PlaceIt()
TileObject Player.PlaceThing_Tiles_PlaceIt (bool newObjectType, TileObject data, int tileToCreate) inline private
     {
         int num = inventory[selectedItem].placeStyle;
         if (!newObjectType)
         {
             num = PlaceThing_Tiles_PlaceIt_GetLegacyTileStyle(num);
         }
         int[,] typeCaches = PlaceThing_Tiles_GetAutoAccessoryCache();
         bool forced = false;
         bool flag;
         if (newObjectType)
         {
             flag = TileObject.Place(data);
             WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
             if (Main.netMode != 1 || !TileID.Sets.IsAContainer[tileToCreate])
             {
                 SoundEngine.PlaySound(0, tileTargetX * 16, tileTargetY * 16);
             }
         }
         else
         {
             if (UsingBiomeTorches && tileToCreate == 4 && num == 0)
             {
                 num = BiomeTorchPlaceStyle(num);
             }
             flag = WorldGen.PlaceTile(tileTargetX, tileTargetY, tileToCreate, mute: false, forced, whoAmI, num);
         }
         if (flag)
         {
             ApplyItemTime(inventory[selectedItem], tileSpeed);
             if (newObjectType)
             {
                 TileObjectData.CallPostPlacementPlayerHook(tileTargetX, tileTargetY, tileToCreate, num, direction, data.alternate, data);
                 if (Main.netMode == 1 && !Main.tileContainer[tileToCreate] && tileToCreate != 423)
                 {
                     NetMessage.SendObjectPlacement(-1, tileTargetX, tileTargetY, data.type, data.style, data.alternate, data.random, direction);
                 }
             }
             else
             {
                 NetMessage.SendData(17, -1, -1, null, 1, tileTargetX, tileTargetY, tileToCreate, num);
                 PlaceThing_Tiles_PlaceIt_SpinChairs();
                 PlaceThing_Tiles_PlaceIt_SpinBedsAndBaths();
             }
             PlaceThing_Tiles_PlaceIt_AdjustPlants();
             PlaceThing_Tiles_PlaceIt_SpinTraps();
             PlaceThing_Tiles_PlaceIt_TriggerLogicLamp();
             PlaceThing_Tiles_PlaceIt_SpinSmartPlatform();
             PlaceThing_Tiles_PlaceIt_ConsumeFlexibleWandMaterial();
             PlaceThing_Tiles_PlaceIt_UnslopeForSolids();
             PlaceThing_Tiles_PlaceIt_KillGrassForSolids();
             PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(typeCaches, tileToCreate);
             if (PlayerInput.UsingGamepad && ItemID.Sets.SingleUseInGamepad[inventory[selectedItem].type] && Main.myPlayer == whoAmI && !Main.SmartCursorIsUsed)
             {
                 Main.blockMouse = true;
             }
         }
         return data;
     }
References TileObject.alternate, Main.blockMouse, TileObjectData.CallPostPlacementPlayerHook(), TileID.Sets.IsAContainer, Main.myPlayer, Main.netMode, TileObject.Place(), WorldGen.PlaceTile(), SoundEngine.PlaySound(), TileObject.random, NetMessage.SendData(), NetMessage.SendObjectPlacement(), ItemID.Sets.SingleUseInGamepad, Main.SmartCursorIsUsed, WorldGen.SquareTileFrame(), TileObject.style, Main.tileContainer, TileObject.type, and PlayerInput.UsingGamepad.