Terraria: Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids
PlaceThing_Tiles_PlaceIt_KillGrassForSolids()
void Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids () inline private
     {
         if (!Main.tileSolid[inventory[selectedItem].createTile])
         {
             return;
         }
         for (int i = tileTargetX - 1; i <= tileTargetX + 1; i++)
         {
             for (int j = tileTargetY - 1; j <= tileTargetY + 1; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (!tile.active() || inventory[selectedItem].createTile == tile.type || (tile.type != 2 && tile.type != 23 && tile.type != 60 && tile.type != 70 && tile.type != 109 && tile.type != 199 && tile.type != 477 && tile.type != 492 && tile.type != 633))
                 {
                     continue;
                 }
                 bool flag = true;
                 for (int k = i - 1; k <= i + 1; k++)
                 {
                     for (int l = j - 1; l <= j + 1; l++)
                     {
                         if (!WorldGen.SolidTile(k, l))
{
                             flag = false;
                         }
                     }
                 }
                 if (flag)
                 {
                     WorldGen.KillTile(i, j, fail: true);
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 0, i, j, 1f);
                     }
                 }
             }
         }
     }
References Tile.active(), WorldGen.KillTile(), Main.netMode, NetMessage.SendData(), WorldGen.SolidTile(), Main.tile, Main.tileSolid, and Tile.type.