Terraria: Player.KillMe
KillMe()
void Player.KillMe (PlayerDeathReason damageSource, double dmg, int hitDirection, bool pvp = false) inline
     {
         if (creativeGodMode || dead)
         {
             return;
         }
         StopVanityActions();
         if (pvp)
         {
             pvpDeath = true;
         }
         if (trapDebuffSource)
         {
             AchievementsHelper.HandleSpecialEvent(this, 4);
         }
         if (Main.myPlayer == whoAmI && _framesLeftEligibleForDeadmansChestDeathAchievement > 0)
         {
             AchievementsHelper.HandleSpecialEvent(this, 23);
         }
         if (whoAmI == Main.myPlayer)
         {
             Main.NotifyOfEvent(GameNotificationType.SpawnOrDeath);
         }
         if (pvpDeath)
         {
             numberOfDeathsPVP++;
         }
         else
         {
             numberOfDeathsPVE++;
         }
         lastDeathPostion = base.Center;
         lastDeathTime = DateTime.Now;
         showLastDeath = true;
         bool overFlowing;
         long coinsOwned = Utils.CoinsCount(out overFlowing, inventory);
         if (Main.myPlayer == whoAmI)
         {
             lostCoins = coinsOwned;
             lostCoinString = Main.ValueToCoins(lostCoins);
         }
         if (Main.myPlayer == whoAmI)
         {
             EndOngoingTorchGodEvent();
         }
         if (Main.myPlayer == whoAmI)
         {
             Main.mapFullscreen = false;
         }
         if (Main.myPlayer == whoAmI)
         {
             trashItem.SetDefaults();
             if (difficulty == 0 || difficulty == 3)
             {
                 for (int i = 0; i < 59; i++)
                 {
                     if (inventory[i].stack > 0 && ((inventory[i].type >= 1522 && inventory[i].type <= 1527) || inventory[i].type == 3643))
                     {
                         int num = Item.NewItem(GetItemSource_Death(), (int)position.X, (int)position.Y, width, height, inventory[i].type);
                         Main.item[num].netDefaults(inventory[i].netID);
                         Main.item[num].Prefix(inventory[i].prefix);
                         Main.item[num].stack = inventory[i].stack;
                         Main.item[num].velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
                         Main.item[num].velocity.X = (float)Main.rand.Next(-20, 21) * 0.2f;
                         Main.item[num].noGrabDelay = 100;
                         Main.item[num].favorited = false;
                         Main.item[num].newAndShiny = false;
                         if (Main.netMode == 1)
{
                             NetMessage.SendData(21, -1, -1, null, num);
                         }
                         inventory[i].SetDefaults();
                     }
                 }
             }
             else if (difficulty == 1)
             {
                 DropItems();
             }
             else if (difficulty == 2)
             {
                 DropItems();
                 KillMeForGood();
             }
         }
         if (Main.dontStarveWorld || Main.tenthAnniversaryWorld)
         {
             SoundEngine.PlaySound(Male ? SoundID.DSTMaleHurt : SoundID.DSTFemaleHurt, position);
         }
         else
         {
             SoundEngine.PlaySound(5, (int)position.X, (int)position.Y);
         }
         if (Main.tenthAnniversaryWorld)
         {
             for (int j = 0; j < 85; j++)
             {
                 int type = Main.rand.Next(139, 143);
                 int num2 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, type, 0f, -10f, 0, default(Color), 1.2f);
                 Main.dust[num2].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.dust[num2].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.dust[num2].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.dust[num2].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.dust[num2].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                 Main.dust[num2].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                 Main.dust[num2].scale *= 1f + (float)Main.rand.Next(-30, 31) * 0.01f;
             }
             for (int k = 0; k < 40; k++)
             {
                 int type2 = Main.rand.Next(276, 283);
                 int num3 = Gore.NewGore(position, new Vector2(0f, -10f), type2);
                 Main.gore[num3].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.gore[num3].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.gore[num3].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.gore[num3].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.gore[num3].scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                 Main.gore[num3].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                 Main.gore[num3].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
             }
         }
         headVelocity.Y = (float)Main.rand.Next(-40, -10) * 0.1f;
         bodyVelocity.Y = (float)Main.rand.Next(-40, -10) * 0.1f;
         legVelocity.Y = (float)Main.rand.Next(-40, -10) * 0.1f;
         headVelocity.X = (float)Main.rand.Next(-20, 21) * 0.1f + (float)(2 * hitDirection);
         bodyVelocity.X = (float)Main.rand.Next(-20, 21) * 0.1f + (float)(2 * hitDirection);
         legVelocity.X = (float)Main.rand.Next(-20, 21) * 0.1f + (float)(2 * hitDirection);
         if (stoned)
         {
             headPosition = Vector2.Zero;
             bodyPosition = Vector2.Zero;
             legPosition = Vector2.Zero;
         }
         for (int l = 0; l < 100; l++)
         {
             if (stoned)
             {
                 Dust.NewDust(position, width, height, 1, 2 * hitDirection, -2f);
             }
             else if (frostArmor)
             {
                 int num4 = Dust.NewDust(position, width, height, 135, 2 * hitDirection, -2f);
                 Main.dust[num4].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
             }
             else if (boneArmor)
             {
                 int num5 = Dust.NewDust(position, width, height, 26, 2 * hitDirection, -2f);
                 Main.dust[num5].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
             }
             else
             {
                 Dust.NewDust(position, width, height, 5, 2 * hitDirection, -2f);
             }
         }
         mount.Dismount(this);
         dead = true;
         respawnTimer = GetRespawnTime(pvp);
         immuneAlpha = 0;
         if (!ChildSafety.Disabled)
         {
             immuneAlpha = 255;
         }
         palladiumRegen = false;
         iceBarrier = false;
         crystalLeaf = false;
         NetworkText deathText = damageSource.GetDeathText(name);
         if (Main.netMode == 2)
         {
             ChatHelper.BroadcastChatMessage(deathText, new Color(225, 25, 25));
         }
         else if (Main.netMode == 0)
         {
             Main.NewText(deathText.ToString(), 225, 25, 25);
         }
         if (Main.netMode == 1 && whoAmI == Main.myPlayer)
         {
             NetMessage.SendPlayerDeath(whoAmI, damageSource, (int)dmg, hitDirection, pvp);
         }
         if (whoAmI == Main.myPlayer && (difficulty == 0 || difficulty == 3))
         {
             if (!pvp)
             {
                 DropCoins();
             }
             else
             {
                 lostCoins = 0L;
                 lostCoinString = Main.ValueToCoins(lostCoins);
             }
         }
         DropTombstone(coinsOwned, deathText, hitDirection);
         if (whoAmI != Main.myPlayer)
         {
             return;
         }
         try
         {
             WorldGen.saveToonWhilePlaying();
         }
         catch
         {
         }
     }
References GameShaders.Armor, ChatHelper.BroadcastChatMessage(), Utils.CoinsCount(), Color, ChildSafety.Disabled, Main.dontStarveWorld, SoundID.DSTFemaleHurt, SoundID.DSTMaleHurt, Main.dust, Item.favorited, PlayerDeathReason.GetDeathText(), ArmorShaderDataSet.GetSecondaryShader(), Main.gore, AchievementsHelper.HandleSpecialEvent(), Main.item, L, Main.mapFullscreen, Main.myPlayer, Item.netDefaults(), Main.netMode, Item.newAndShiny, Dust.NewDust(), Gore.NewGore(), Item.NewItem(), Main.NewText(), UnifiedRandom.Next(), Item.noGrabDelay, Main.NotifyOfEvent(), SoundEngine.PlaySound(), Item.Prefix(), Main.rand, WorldGen.saveToonWhilePlaying(), Dust.scale, Gore.scale, NetMessage.SendData(), NetMessage.SendPlayerDeath(), Dust.shader, Item.stack, Main.tenthAnniversaryWorld, NetworkText.ToString(), Main.ValueToCoins(), Dust.velocity, Entity.velocity, and Gore.velocity.
Referenced by MessageBuffer.GetData().