Terraria: Player.PlaceThing_Walls
PlaceThing_Walls()
void Player.PlaceThing_Walls () inline private
     {
         if (inventory[selectedItem].createWall < 0 || !(position.X / 16f - (float)tileRangeX - (float)inventory[selectedItem].tileBoost - (float)blockRange <= (float)tileTargetX) || !((position.X + (float)width) / 16f + (float)tileRangeX + (float)inventory[selectedItem].tileBoost - 1f + (float)blockRange >= (float)tileTargetX) || !(position.Y / 16f - (float)tileRangeY - (float)inventory[selectedItem].tileBoost - (float)blockRange <= (float)tileTargetY) || !((position.Y + (float)height) / 16f + (float)tileRangeY + (float)inventory[selectedItem].tileBoost - 2f + (float)blockRange >= (float)tileTargetY))
         {
             return;
         }
         cursorItemIconEnabled = true;
         if (!ItemTimeIsZero || itemAnimation <= 0 || !controlUseItem || (!Main.tile[tileTargetX + 1, tileTargetY].active() && Main.tile[tileTargetX + 1, tileTargetY].wall <= 0 && !Main.tile[tileTargetX - 1, tileTargetY].active() && Main.tile[tileTargetX - 1, tileTargetY].wall <= 0 && !Main.tile[tileTargetX, tileTargetY + 1].active() && Main.tile[tileTargetX, tileTargetY + 1].wall <= 0 && !Main.tile[tileTargetX, tileTargetY - 1].active() && Main.tile[tileTargetX, tileTargetY - 1].wall <= 0) || Main.tile[tileTargetX, tileTargetY].wall == inventory[selectedItem].createWall)
         {
             return;
         }
         bool flag = true;
         if (TileReplacementEnabled)
         {
             flag = PlaceThing_TryReplacingWalls(flag);
         }
         if (!flag)
         {
             return;
         }
         WorldGen.PlaceWall(tileTargetX, tileTargetY, inventory[selectedItem].createWall);
         if (Main.tile[tileTargetX, tileTargetY].wall == inventory[selectedItem].createWall)
         {
             ApplyItemTime(inventory[selectedItem], wallSpeed);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 3, tileTargetX, tileTargetY, inventory[selectedItem].createWall);
             }
             PlaceThing_Walls_FillEmptySpace();
             if (autoPaint && builderAccStatus[3] == 0)
             {
                 TryPainting(tileTargetX, tileTargetY, paintingAWall: true, applyItemAnimation: false);
             }
         }
     }
References Tile.active(), Main.netMode, WorldGen.PlaceWall(), NetMessage.SendData(), Main.tile, and Tile.wall.