Terraria: Player.WingAirVisuals
WingAirVisuals()
void Player.WingAirVisuals () inline private
     {
         bool noLightEmittence = wingsLogic != wings;
         if (wings == 10 && Main.rand.Next(2) == 0)
         {
             int num = 4;
             if (direction == 1)
             {
                 num = -40;
             }
             int num2 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num, position.Y + (float)(height / 2) - 15f), 30, 30, 76, 0f, 0f, 50, default(Color), 0.6f);
             Main.dust[num2].fadeIn = 1.1f;
             Main.dust[num2].noGravity = true;
             Main.dust[num2].noLight = true;
             Main.dust[num2].velocity *= 0.3f;
             Main.dust[num2].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
         }
         if (wings == 34 && Main.rand.Next(2) == 0)
         {
             int num3 = 4;
             if (direction == 1)
             {
                 num3 = -40;
             }
             int num4 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num3, position.Y + (float)(height / 2) - 15f), 30, 30, 261, 0f, 0f, 50, default(Color), 0.6f);
             Main.dust[num4].fadeIn = 1.1f;
             Main.dust[num4].noGravity = true;
             Main.dust[num4].noLight = true;
             Main.dust[num4].noLightEmittence = noLightEmittence;
             Main.dust[num4].velocity *= 0.3f;
             Main.dust[num4].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
         }
         _ = wings;
         _ = 40;
         _ = wings;
         _ = 44;
         if (wings == 9 && Main.rand.Next(2) == 0)
         {
             int num5 = 4;
             if (direction == 1)
             {
                 num5 = -40;
             }
             int num6 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num5, position.Y + (float)(height / 2) - 15f), 30, 30, 6, 0f, 0f, 200, default(Color), 2f);
             Main.dust[num6].noGravity = true;
             Main.dust[num6].noLightEmittence = noLightEmittence;
             Main.dust[num6].velocity *= 0.3f;
             Main.dust[num6].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
         }
         if (wings == 6 && Main.rand.Next(4) == 0)
         {
             int num7 = 4;
             if (direction == 1)
             {
                 num7 = -40;
             }
             int num8 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num7, position.Y + (float)(height / 2) - 15f), 30, 30, 55, 0f, 0f, 200);
             Main.dust[num8].velocity *= 0.3f;
             Main.dust[num8].noLightEmittence = noLightEmittence;
             Main.dust[num8].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
         }
         if (wings == 5 && Main.rand.Next(3) == 0)
         {
             int num9 = 6;
             if (direction == 1)
             {
                 num9 = -30;
             }
             int num10 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num9, position.Y), 18, height, 58, 0f, 0f, 255, default(Color), 1.2f);
             Main.dust[num10].noLightEmittence = noLightEmittence;
             Main.dust[num10].velocity *= 0.3f;
             Main.dust[num10].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
         }
         if (wings == 26)
         {
             int num11 = 6;
             if (direction == 1)
             {
                 num11 = -30;
             }
             int num12 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num11, position.Y), 18, height, 217, 0f, 0f, 100, default(Color), 1.4f);
             Main.dust[num12].noGravity = true;
             Main.dust[num12].noLight = true;
             Main.dust[num12].velocity /= 4f;
             Main.dust[num12].velocity -= velocity;
             Main.dust[num12].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
             if (Main.rand.Next(2) == 0)
             {
                 num11 = -24;
                 if (direction == 1)
                 {
                     num11 = 12;
                 }
                 float num13 = position.Y;
                 if (gravDir == -1f)
                 {
                     num13 += (float)(height / 2);
                 }
                 num12 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num11, num13), 12, height / 2, 217, 0f, 0f, 100, default(Color), 1.4f);
                 Main.dust[num12].noGravity = true;
                 Main.dust[num12].noLight = true;
                 Main.dust[num12].velocity /= 4f;
                 Main.dust[num12].velocity -= velocity;
                 Main.dust[num12].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
             }
         }
         if (wings == 37)
         {
             int num14 = 6;
             if (direction == 1)
             {
                 num14 = -30;
             }
             Dust dust = Dust.NewDustDirect(new Vector2(position.X + (float)(width / 2) + (float)num14, position.Y), 24, height, Utils.SelectRandom<int>(Main.rand, 31, 31, 31), 0f, 0f, 100);
             dust.noGravity = true;
             dust.noLight = true;
             dust.velocity /= 4f;
             dust.velocity -= velocity / 2f;
             dust.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
             if (dust.type == 55)
             {
                 dust.noGravity = true;
                 dust.velocity *= 2f;
                 dust.color = Color.Red;
             }
             if (Main.rand.Next(3) == 0)
             {
                 num14 = -24;
                 if (direction == 1)
                 {
                     num14 = 12;
                 }
                 float num15 = position.Y;
                 if (gravDir == -1f)
                 {
                     num15 += (float)(height / 2);
                 }
                 dust = Dust.NewDustDirect(new Vector2(position.X + (float)(width / 2) + (float)num14, num15), 16, height / 2, Utils.SelectRandom<int>(Main.rand, 31, 31, 31), 0f, 0f, 100);
                 dust.noGravity = true;
                 dust.noLight = true;
                 dust.velocity /= 4f;
                 dust.velocity -= velocity / 2f;
                 dust.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                 if (dust.type == 55)
                 {
                     dust.noGravity = true;
                     dust.velocity *= 2f;
                     dust.color = Color.Red;
                 }
             }
         }
         if (wings == 29 && Main.rand.Next(3) == 0)
         {
             int num16 = 4;
             if (direction == 1)
             {
                 num16 = -40;
             }
             int num17 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num16, position.Y + (float)(height / 2) - 15f), 30, 30, 6, 0f, 0f, 100, default(Color), 2.4f);
             Main.dust[num17].noGravity = true;
             Main.dust[num17].velocity *= 0.3f;
             Main.dust[num17].noLightEmittence = noLightEmittence;
             if (Main.rand.Next(10) == 0)
             {
                 Main.dust[num17].fadeIn = 2f;
             }
             Main.dust[num17].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
         }
         if (wings != 31)
         {
             return;
         }
         if (Main.rand.Next(6) == 0)
         {
             int num18 = 4;
             if (direction == 1)
             {
                 num18 = -40;
             }
             Dust obj = Main.dust[Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num18, position.Y + (float)(height / 2) - 15f), 30, 30, 86)];
             obj.noGravity = true;
             obj.scale = 1f;
             obj.fadeIn = 1.2f;
             obj.velocity *= 0.2f;
             obj.noLight = true;
             obj.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
         }
         if (Main.rand.Next(3) == 0)
         {
             int num19 = 4;
             if (direction == 1)
             {
                 num19 = -40;
             }
             Dust obj2 = Main.dust[Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num19, position.Y + (float)(height / 2) - 15f), 30, 30, 240)];
             obj2.noGravity = true;
             obj2.scale = 1.2f;
             obj2.velocity *= 0.2f;
             obj2.alpha = 200;
             obj2.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
         }
         if (Main.rand.Next(2) != 0)
         {
             return;
         }
         if (Main.rand.Next(6) == 0)
         {
             int num20 = -24;
             if (direction == 1)
             {
                 num20 = 12;
             }
             float num21 = position.Y;
             if (gravDir == -1f)
             {
                 num21 += (float)(height / 2);
             }
             Dust obj3 = Main.dust[Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num20, num21), 12, height / 2, 86)];
             obj3.noGravity = true;
             obj3.scale = 1f;
             obj3.fadeIn = 1.2f;
             obj3.velocity *= 0.2f;
             obj3.noLight = true;
             obj3.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
         }
         if (Main.rand.Next(3) == 0)
         {
             int num20 = -24;
             if (direction == 1)
             {
                 num20 = 12;
             }
             float num22 = position.Y;
             if (gravDir == -1f)
             {
                 num22 += (float)(height / 2);
             }
             Dust obj4 = Main.dust[Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num20, num22), 12, height / 2, 240)];
             obj4.noGravity = true;
             obj4.scale = 1.2f;
             obj4.velocity *= 0.2f;
             obj4.alpha = 200;
             obj4.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
         }
     }
References Dust.alpha, GameShaders.Armor, Color, Dust.color, Main.dust, Dust.fadeIn, ArmorShaderDataSet.GetSecondaryShader(), Dust.NewDust(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, Main.rand, Dust.scale, Dust.shader, Dust.type, and Dust.velocity.