Terraria: Player.InterruptItemUsageIfOverTile
InterruptItemUsageIfOverTile()
void Player.InterruptItemUsageIfOverTile (int tileTypeToBeOver) inline
     {
         Tile tile = Main.tile[tileTargetX, tileTargetY];
         if (tile != null && tile.active() && tile.type == tileTypeToBeOver)
         {
             Main.blockMouse = true;
         }
     }
References Tile.active(), Main.blockMouse, Main.tile, and Tile.type.
Referenced by WorldGen.CheckFoodPlatter(), WorldGen.CheckSign(), WorldGen.CheckWeaponsRack(), TEWeaponsRack.Framing_CheckTile(), and WorldGen.KillTile().