Terraria: Player.DropTombstone
DropTombstone()
void Player.DropTombstone (long coinsOwned, NetworkText deathText, int hitDirection) inline
     {
         if (Main.netMode != 1)
         {
             float num;
             for (num = (float)Main.rand.Next(-35, 36) * 0.1f; num < 2f && num > -2f; num += (float)Main.rand.Next(-30, 31) * 0.1f)
             {
             }
             int num2 = Main.rand.Next(6);
             if (coinsOwned <= 100000)
             {
                 num2 = ((num2 != 0) ? (200 + num2) : 43);
             }
             else
             {
                 num2 = Main.rand.Next(5);
                 num2 += 527;
             }
             IEntitySource projectileSource_Misc = GetProjectileSource_Misc(9);
             int damage = 0;
             int num3 = 0;
             if (Main.getGoodWorld)
             {
                 damage = 70;
                 num3 = 10;
             }
             int num4 = whoAmI;
             int num5 = ((!Main.getGoodWorld) ? Projectile.NewProjectile(projectileSource_Misc, position.X + (float)(width / 2), position.Y + (float)(height / 2), (float)Main.rand.Next(10, 30) * 0.1f * (float)hitDirection + num, (float)Main.rand.Next(-40, -20) * 0.1f, num2, damage, num3, Main.myPlayer, num4) : Projectile.NewProjectile(projectileSource_Misc, position.X + (float)(width / 2), position.Y + (float)(height / 2), ((float)Main.rand.Next(10, 30) * 0.1f * (float)hitDirection + num) * 1.5f, (float)Main.rand.Next(-40, -20) * 0.1f * 1.5f, num2, damage, num3, Main.myPlayer, num4));
             DateTime now = DateTime.Now;
             string text = now.ToString("D");
             if (GameCulture.FromCultureName(GameCulture.CultureName.English).IsActive)
             {
                 text = now.ToString("MMMM d, yyy");
             }
             string miscText = deathText.ToString() + "\n" + text;
             Main.projectile[num5].miscText = miscText;
         }
     }
References GameCulture.FromCultureName(), Main.getGoodWorld, GameCulture.IsActive, Projectile.miscText, Main.myPlayer, Main.netMode, Projectile.NewProjectile(), UnifiedRandom.Next(), Main.projectile, Main.rand, and NetworkText.ToString().