Terraria: Player.CheckForGoodTeleportationSpot
CheckForGoodTeleportationSpot()
Vector2 Player.CheckForGoodTeleportationSpot (ref bool canSpawn, int teleportStartX, int teleportRangeX, int teleportStartY, int teleportRangeY, RandomTeleportationAttemptSettings settings) inline
     {
         int num = 0;
         int num2 = 0;
         int num3 = 0;
         int num4 = width;
         Vector2 vector = new Vector2(num2, num3) * 16f + new Vector2(-num4 / 2 + 8, -height);
         while (!canSpawn && num < settings.attemptsBeforeGivingUp)
         {
             num++;
             num2 = teleportStartX + Main.rand.Next(teleportRangeX);
             num3 = teleportStartY + Main.rand.Next(teleportRangeY);
             int num5 = 5;
             num2 = (int)MathHelper.Clamp(num2, num5, Main.maxTilesX - num5);
             num3 = (int)MathHelper.Clamp(num3, num5, Main.maxTilesY - num5);
             vector = new Vector2(num2, num3) * 16f + new Vector2(-num4 / 2 + 8, -height);
             if (Collision.SolidCollision(vector, num4, height))
             {
                 continue;
             }
             if (Main.tile[num2, num3] == null)
             {
                 Main.tile[num2, num3] = new Tile();
             }
             if ((settings.avoidWalls && Main.tile[num2, num3].wall > 0) || (Main.tile[num2, num3].wall == 87 && (double)num3 > Main.worldSurface && !NPC.downedPlantBoss) || (Main.wallDungeon[Main.tile[num2, num3].wall] && (double)num3 > Main.worldSurface && !NPC.downedBoss3))
             {
                 continue;
             }
             int num6 = 0;
             while (num6 < settings.maximumFallDistanceFromOrignalPoint)
             {
                 if (Main.tile[num2, num3 + num6] == null)
                 {
                     Main.tile[num2, num3 + num6] = new Tile();
                 }
                 Tile tile = Main.tile[num2, num3 + num6];
                 vector = new Vector2(num2, num3 + num6) * 16f + new Vector2(-num4 / 2 + 8, -height);
                 Collision.SlopeCollision(vector, velocity, num4, height, gravDir);
                 if (!Collision.SolidCollision(vector, num4, height))
                 {
                     num6++;
                     continue;
                 }
                 if (tile.active() && !tile.inActive() && Main.tileSolid[tile.type])
                 {
                     break;
                 }
                 num6++;
             }
             vector.Y -= 16f;
             int i = (int)vector.X / 16;
             int j = (int)vector.Y / 16;
             int num7 = (int)(vector.X + (float)num4 * 0.5f) / 16;
             int j2 = (int)(vector.Y + (float)height) / 16;
             Tile tileSafely = Framing.GetTileSafely(i, j);
             Tile tileSafely2 = Framing.GetTileSafely(num7, j2);
             if (settings.avoidAnyLiquid && tileSafely2.liquid > 0)
             {
                 continue;
             }
             if (settings.mostlySolidFloor)
             {
                 Tile tileSafely3 = Framing.GetTileSafely(num7 - 1, j2);
                 Tile tileSafely4 = Framing.GetTileSafely(num7 + 1, j2);
                 if (!tileSafely3.active() || tileSafely3.inActive() || !Main.tileSolid[tileSafely3.type] || Main.tileSolidTop[tileSafely3.type] || !tileSafely4.active() || tileSafely4.inActive() || !Main.tileSolid[tileSafely4.type] || Main.tileSolidTop[tileSafely4.type])
                 {
                     continue;
                 }
             }
             if ((settings.avoidWalls && tileSafely.wall > 0) || (settings.avoidAnyLiquid && Collision.WetCollision(vector, num4, height)) || (settings.avoidLava && Collision.LavaCollision(vector, num4, height)) || (settings.avoidHurtTiles && Collision.AnyHurtingTiles(vector, num4, height)) || Collision.SolidCollision(vector, num4, height) || num6 >= settings.maximumFallDistanceFromOrignalPoint - 1)
             {
                 continue;
             }
             Vector2 vector2 = Vector2.UnitX * 16f;
             if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: false, fall2: false, (int)gravDir) != vector2)
             {
                 continue;
             }
             vector2 = -Vector2.UnitX * 16f;
             if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: false, fall2: false, (int)gravDir) != vector2)
             {
                 continue;
             }
             vector2 = Vector2.UnitY * 16f;
             if (!(Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: false, fall2: false, (int)gravDir) != vector2))
             {
                 vector2 = -Vector2.UnitY * 16f;
                 if (!(Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: false, fall2: false, (int)gravDir) != vector2))
                 {
                     canSpawn = true;
                     num3 += num6;
                     break;
                 }
             }
         }
         return vector;
     }
References Tile.active(), Collision.AnyHurtingTiles(), Player.RandomTeleportationAttemptSettings.attemptsBeforeGivingUp, Player.RandomTeleportationAttemptSettings.avoidAnyLiquid, Player.RandomTeleportationAttemptSettings.avoidHurtTiles, Player.RandomTeleportationAttemptSettings.avoidLava, Player.RandomTeleportationAttemptSettings.avoidWalls, NPC.downedBoss3, NPC.downedPlantBoss, Framing.GetTileSafely(), Tile.inActive(), Collision.LavaCollision(), Tile.liquid, Player.RandomTeleportationAttemptSettings.maximumFallDistanceFromOrignalPoint, Main.maxTilesX, Main.maxTilesY, Player.RandomTeleportationAttemptSettings.mostlySolidFloor, UnifiedRandom.Next(), Main.rand, Collision.SlopeCollision(), Collision.SolidCollision(), Main.tile, Collision.TileCollision(), Main.tileSolid, Main.tileSolidTop, Tile.type, Tile.wall, Main.wallDungeon, Collision.WetCollision(), and Main.worldSurface.