Terraria: Player.PlaceThing_LockChest
PlaceThing_LockChest()
void Player.PlaceThing_LockChest () inline private
     {
         Tile tile = Main.tile[tileTargetX, tileTargetY];
         Item item = inventory[selectedItem];
         if (!tile.active() || item.type != 5328 || !TileID.Sets.IsAContainer[tile.type] || !(position.X / 16f - (float)tileRangeX - (float)item.tileBoost - (float)blockRange <= (float)tileTargetX) || !((position.X + (float)width) / 16f + (float)tileRangeX + (float)item.tileBoost - 1f + (float)blockRange >= (float)tileTargetX) || !(position.Y / 16f - (float)tileRangeY - (float)item.tileBoost - (float)blockRange <= (float)tileTargetY) || !((position.Y + (float)height) / 16f + (float)tileRangeY + (float)item.tileBoost - 2f + (float)blockRange >= (float)tileTargetY) || !ItemTimeIsZero || itemAnimation <= 0 || !controlUseItem)
         {
             return;
         }
         Tile tileSafely = Framing.GetTileSafely(tileTargetX, tileTargetY);
         int type = tileSafely.type;
         int num = tileSafely.frameX / 36;
         switch (type)
         {
         case 21:
             switch (num)
             {
             default:
                 return;
             case 1:
             case 3:
             case 18:
             case 19:
             case 20:
             case 21:
             case 22:
             case 35:
             case 37:
             case 39:
                 break;
             }
             break;
         case 467:
             if (num != 12)
             {
                 return;
             }
             break;
         }
         if (inventory[selectedItem].stack <= 0)
         {
             return;
         }
         int num2;
         for (num2 = Main.tile[tileTargetX, tileTargetY].frameX / 18; num2 > 1; num2 -= 2)
         {
         }
         num2 = tileTargetX - num2;
         int num3 = tileTargetY - Main.tile[tileTargetX, tileTargetY].frameY / 18;
         if (Chest.Lock(num2, num3))
         {
             inventory[selectedItem].stack--;
             if (inventory[selectedItem].stack <= 0)
             {
                 inventory[selectedItem] = new Item();
             }
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(52, -1, -1, null, whoAmI, 3f, num2, num3);
             }
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Framing.GetTileSafely(), TileID.Sets.IsAContainer, Chest.Lock(), Main.netMode, NetMessage.SendData(), Main.tile, Item.tileBoost, Item.type, and Tile.type.