Terraria: Player.UpdateManaRegen
UpdateManaRegen()
void Player.UpdateManaRegen () inline
     {
         if (nebulaLevelMana > 0)
         {
             int num = 6;
             nebulaManaCounter += nebulaLevelMana;
             if (nebulaManaCounter >= num)
             {
                 nebulaManaCounter -= num;
                 statMana++;
                 if (statMana >= statManaMax2)
                 {
                     statMana = statManaMax2;
                 }
             }
         }
         else
         {
             nebulaManaCounter = 0;
         }
         if (manaRegenDelay > 0f)
         {
             manaRegenDelay -= 1f;
             manaRegenDelay -= manaRegenDelayBonus;
             if (IsStandingStillForSpecialEffects || grappling[0] >= 0 || manaRegenBuff)
             {
                 manaRegenDelay -= 1f;
             }
             if (usedArcaneCrystal)
             {
                 manaRegenDelay -= 0.05f;
             }
         }
         if (manaRegenBuff && manaRegenDelay > 20f)
         {
             manaRegenDelay = 20f;
         }
         if (manaRegenDelay <= 0f)
         {
             manaRegenDelay = 0f;
             manaRegen = statManaMax2 / 3 + 1 + manaRegenBonus;
             if (IsStandingStillForSpecialEffects || grappling[0] >= 0 || manaRegenBuff)
             {
                 manaRegen += statManaMax2 / 3;
             }
             if (usedArcaneCrystal)
             {
                 manaRegen += statManaMax2 / 50;
             }
             float num2 = (float)statMana / (float)statManaMax2 * 0.8f + 0.2f;
             if (manaRegenBuff)
             {
                 num2 = 1f;
             }
             manaRegen = (int)((double)((float)manaRegen * num2) * 1.15);
         }
         else
         {
             manaRegen = 0;
         }
         manaRegenCount += manaRegen;
         while (manaRegenCount >= 120)
         {
             bool flag = false;
             manaRegenCount -= 120;
             if (statMana < statManaMax2)
             {
                 statMana++;
                 flag = true;
             }
             if (statMana < statManaMax2)
             {
                 continue;
             }
             if (whoAmI == Main.myPlayer && flag)
             {
                 SoundEngine.PlaySound(25);
                 for (int i = 0; i < 5; i++)
                 {
                     int num3 = Dust.NewDust(position, width, height, 45, 0f, 0f, 255, default(Color), (float)Main.rand.Next(20, 26) * 0.1f);
                     Main.dust[num3].noLight = true;
                     Main.dust[num3].noGravity = true;
                     Main.dust[num3].velocity *= 0.5f;
                 }
             }
             statMana = statManaMax2;
         }
     }
References Color, Main.dust, Main.myPlayer, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, SoundEngine.PlaySound(), Main.rand, and Dust.velocity.