Terraria: Player.UpdateMinionTarget
UpdateMinionTarget()
void Player.UpdateMinionTarget () inline
     {
         if (whoAmI != Main.myPlayer)
         {
             return;
         }
         if (Distance(MinionRestTargetPoint) > 1000f)
         {
             MinionRestTargetPoint = Vector2.Zero;
         }
         if (MinionAttackTargetNPC != -1 && (!Main.npc[MinionAttackTargetNPC].CanBeChasedBy(this) || Main.npc[MinionAttackTargetNPC].Hitbox.Distance(base.Center) > 3000f))
         {
             MinionAttackTargetNPC = -1;
         }
         if (stardustGuardian && HasMinionRestTarget)
         {
             Vector2 minionRestTargetPoint = MinionRestTargetPoint;
             float num = (float)miscCounter / 150f;
             float num2 = (float)Math.PI * 2f / 3f;
             for (int i = 0; i < 3; i++)
             {
                 int num3 = Dust.NewDust(minionRestTargetPoint, 0, 0, 135, 0f, 0f, 100, default(Color), 1.5f);
                 Main.dust[num3].noGravity = true;
                 Main.dust[num3].velocity = Vector2.Zero;
                 Main.dust[num3].noLight = true;
                 Main.dust[num3].position = minionRestTargetPoint + (num * ((float)Math.PI * 2f) + num2 * (float)i).ToRotationVector2() * 4f;
                 Main.dust[num3].shader = GameShaders.Armor.GetSecondaryShader(cPet, this);
             }
         }
     }
References GameShaders.Armor, NPC.CanBeChasedBy(), Color, Main.dust, ArmorShaderDataSet.GetSecondaryShader(), Entity.Hitbox, Main.myPlayer, Dust.NewDust(), Dust.noGravity, Dust.noLight, Main.npc, Dust.position, Dust.shader, and Dust.velocity.