Terraria: Player.ItemCheck_UseBuckets
ItemCheck_UseBuckets()
void Player.ItemCheck_UseBuckets (Item sItem) inline private
     {
         if (((sItem.type < 205 || sItem.type > 207) && sItem.type != 1128 && sItem.type != 3031 && sItem.type != 3032 && sItem.type != 4820 && sItem.type != 4872 && sItem.type != 5302 && sItem.type != 5303 && sItem.type != 5304 && sItem.type != 5364) || noBuilding || !(position.X / 16f - (float)tileRangeX - (float)sItem.tileBoost <= (float)tileTargetX) || !((position.X + (float)width) / 16f + (float)tileRangeX + (float)sItem.tileBoost - 1f >= (float)tileTargetX) || !(position.Y / 16f - (float)tileRangeY - (float)sItem.tileBoost <= (float)tileTargetY) || !((position.Y + (float)height) / 16f + (float)tileRangeY + (float)sItem.tileBoost - 2f >= (float)tileTargetY))
         {
             return;
         }
         if (!Main.GamepadDisableCursorItemIcon)
         {
             cursorItemIconEnabled = true;
             Main.ItemIconCacheUpdate(sItem.type);
         }
         if (!ItemTimeIsZero || itemAnimation <= 0 || !controlUseItem)
         {
             return;
         }
         if ((sItem.type == 205 && !Main.tile[tileTargetX, tileTargetY].shimmer()) || (sItem.type == 3032 && Main.tile[tileTargetX, tileTargetY].liquidType() == 0) || (sItem.type == 3032 && Main.tile[tileTargetX, tileTargetY].shimmer()) || (sItem.type == 4872 && Main.tile[tileTargetX, tileTargetY].lava()) || (sItem.type == 5303 && Main.tile[tileTargetX, tileTargetY].honey()) || sItem.type == 5304)
         {
             int num = Main.tile[tileTargetX, tileTargetY].liquidType();
             int num2 = 0;
             for (int i = tileTargetX - 1; i <= tileTargetX + 1; i++)
             {
                 for (int j = tileTargetY - 1; j <= tileTargetY + 1; j++)
                 {
                     if (Main.tile[i, j].liquidType() == num)
                     {
                         num2 += Main.tile[i, j].liquid;
                     }
                 }
             }
             if (Main.tile[tileTargetX, tileTargetY].liquid <= 0 || (num2 <= 100 && sItem.type != 3032 && sItem.type != 4872 && sItem.type != 5303 && sItem.type != 5304))
             {
                 return;
             }
             int liquidType = Main.tile[tileTargetX, tileTargetY].liquidType();
             if (sItem.type != 3032 && sItem.type != 4872 && sItem.type != 5303 && sItem.type != 5304)
             {
                 if (Main.tile[tileTargetX, tileTargetY].honey() && sItem.type == 205)
                 {
                     sItem.stack--;
                     PutItemInInventoryFromItemUsage(1128, selectedItem);
                 }
                 else if (Main.tile[tileTargetX, tileTargetY].lava() && sItem.type == 205)
                 {
                     sItem.stack--;
                     PutItemInInventoryFromItemUsage(207, selectedItem);
                 }
                 else
                 {
                     if (Main.tile[tileTargetX, tileTargetY].shimmer() && sItem.type == 205)
                     {
                         return;
                     }
                     sItem.stack--;
                     PutItemInInventoryFromItemUsage(206, selectedItem);
                 }
             }
             SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
             ApplyItemTime(sItem);
             int num3 = Main.tile[tileTargetX, tileTargetY].liquid;
             Main.tile[tileTargetX, tileTargetY].liquid = 0;
             Main.tile[tileTargetX, tileTargetY].lava(lava: false);
             Main.tile[tileTargetX, tileTargetY].honey(honey: false);
             WorldGen.SquareTileFrame(tileTargetX, tileTargetY, resetFrame: false);
             if (Main.netMode == 1)
             {
                 NetMessage.sendWater(tileTargetX, tileTargetY);
             }
             else
             {
                 Liquid.AddWater(tileTargetX, tileTargetY);
             }
             if (num3 >= 255)
             {
                 return;
             }
             for (int k = tileTargetX - 1; k <= tileTargetX + 1; k++)
             {
                 for (int l = tileTargetY - 1; l <= tileTargetY + 1; l++)
                 {
                     if ((k != tileTargetX || l != tileTargetY) && Main.tile[k, l].liquid > 0 && Main.tile[k, l].liquidType() == num)
                     {
                         int num4 = Main.tile[k, l].liquid;
                         if (num4 + num3 > 255)
{
                             num4 = 255 - num3;
                         }
                         num3 += num4;
                         Main.tile[k, l].liquid -= (byte)num4;
                         Main.tile[k, l].liquidType(liquidType);
                         if (Main.tile[k, l].liquid == 0)
{
                             Main.tile[k, l].lava(lava: false);
                             Main.tile[k, l].honey(honey: false);
                         }
                         WorldGen.SquareTileFrame(k, l, resetFrame: false);
                         if (Main.netMode == 1)
{
                             NetMessage.sendWater(k, l);
                         }
                         else
{
                             Liquid.AddWater(k, l);
                         }
                     }
                 }
             }
         }
         else
         {
             if (Main.tile[tileTargetX, tileTargetY].liquid >= 200 || (Main.tile[tileTargetX, tileTargetY].nactive() && Main.tileSolid[Main.tile[tileTargetX, tileTargetY].type] && !Main.tileSolidTop[Main.tile[tileTargetX, tileTargetY].type] && Main.tile[tileTargetX, tileTargetY].type != 546))
             {
                 return;
             }
             if (sItem.type == 207 || sItem.type == 4820)
             {
                 if (Main.tile[tileTargetX, tileTargetY].liquid == 0 || Main.tile[tileTargetX, tileTargetY].liquidType() == 1)
                 {
                     SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                     Main.tile[tileTargetX, tileTargetY].liquidType(1);
                     Main.tile[tileTargetX, tileTargetY].liquid = byte.MaxValue;
                     WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
                     if (sItem.type != 4820)
                     {
                         sItem.stack--;
                         PutItemInInventoryFromItemUsage(205, selectedItem);
                     }
                     ApplyItemTime(sItem);
                     if (Main.netMode == 1)
                     {
                         NetMessage.sendWater(tileTargetX, tileTargetY);
                     }
                 }
             }
             else if (sItem.type == 206 || sItem.type == 3031)
             {
                 if (Main.tile[tileTargetX, tileTargetY].liquid == 0 || Main.tile[tileTargetX, tileTargetY].liquidType() == 0)
                 {
                     SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                     Main.tile[tileTargetX, tileTargetY].liquidType(0);
                     Main.tile[tileTargetX, tileTargetY].liquid = byte.MaxValue;
                     WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
                     if (sItem.type != 3031)
                     {
                         sItem.stack--;
                         PutItemInInventoryFromItemUsage(205, selectedItem);
                     }
                     ApplyItemTime(sItem);
                     if (Main.netMode == 1)
                     {
                         NetMessage.sendWater(tileTargetX, tileTargetY);
                     }
                 }
             }
             else if (sItem.type == 1128 || sItem.type == 5302)
             {
                 if (Main.tile[tileTargetX, tileTargetY].liquid == 0 || Main.tile[tileTargetX, tileTargetY].liquidType() == 2)
                 {
                     SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                     Main.tile[tileTargetX, tileTargetY].liquidType(2);
                     Main.tile[tileTargetX, tileTargetY].liquid = byte.MaxValue;
                     WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
                     if (sItem.type != 5302)
                     {
                         sItem.stack--;
                         PutItemInInventoryFromItemUsage(205, selectedItem);
                     }
                     ApplyItemTime(sItem);
                     if (Main.netMode == 1)
                     {
                         NetMessage.sendWater(tileTargetX, tileTargetY);
                     }
                 }
             }
             else if (sItem.type == 5364 && (Main.tile[tileTargetX, tileTargetY].liquid == 0 || Main.tile[tileTargetX, tileTargetY].liquidType() == 3))
             {
                 SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                 Main.tile[tileTargetX, tileTargetY].liquidType(3);
                 Main.tile[tileTargetX, tileTargetY].liquid = byte.MaxValue;
                 WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
                 ApplyItemTime(sItem);
                 if (Main.netMode == 1)
                 {
                     NetMessage.sendWater(tileTargetX, tileTargetY);
                 }
             }
         }
     }
References Main.GamepadDisableCursorItemIcon, Tile.honey(), Main.ItemIconCacheUpdate(), Tile.lava(), Liquid, Tile.liquid, Tile.liquidType(), Tile.nactive(), Main.netMode, SoundEngine.PlaySound(), NetMessage.sendWater(), Tile.shimmer(), WorldGen.SquareTileFrame(), Item.stack, Main.tile, Item.tileBoost, Main.tileSolid, Main.tileSolidTop, Item.type, and Tile.type.