Terraria: Player.TorchAttack
TorchAttack()
void Player.TorchAttack () inline private
     {
         if (whoAmI != Main.myPlayer)
         {
             return;
         }
         if ((double)position.Y < Main.worldSurface * 16.0)
         {
             EndOngoingTorchGodEvent();
             return;
         }
         AddBuff(80, 2);
         torchFunTimer++;
         if (torchFunTimer <= 20)
         {
             return;
         }
         torchFunTimer = 0;
         int num = 0;
         int num2 = 100;
         int value = (int)base.Center.X / 16 - num2;
         int value2 = (int)base.Center.X / 16 + num2;
         int value3 = (int)base.Center.Y / 16 - num2;
         int value4 = (int)base.Center.Y / 16 + num2;
         int num3 = Utils.Clamp(value, 10, Main.maxTilesX - 10);
         value2 = Utils.Clamp(value2, 10, Main.maxTilesX - 10);
         value3 = Utils.Clamp(value3, 10, Main.maxTilesY - 10);
         value4 = Utils.Clamp(value4, 10, Main.maxTilesY - 10);
         for (int i = num3; i <= value2; i++)
         {
             for (int j = value3; j <= value4; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile != null && (tile.active() & (tile.type == 4)) && tile.frameX < 66)
                 {
                     _torchAttackPosX[num] = i;
                     _torchAttackPosY[num] = j;
                     num++;
                     if (num >= _torchAttackPosX.Length)
                     {
                         break;
                     }
                 }
             }
             if (num >= _torchAttackPosX.Length)
             {
                 break;
             }
         }
         if (num == 0 || numberOfTorchAttacksMade >= maxTorchAttacks)
         {
             RelightTorches();
             happyFunTorchTime = false;
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(4, -1, -1, null, whoAmI);
             }
             if (numberOfTorchAttacksMade >= 95)
             {
                 int number = Item.NewItem(new EntitySource_ByItemSourceId(this, 6), (int)position.X, (int)position.Y, width, height, 5043);
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(21, -1, -1, null, number, 1f);
                 }
             }
         }
         else
         {
             if (num <= 0)
             {
                 return;
             }
             int num4 = Main.rand.Next(num);
             int num5 = _torchAttackPosX[num4];
             int num6 = _torchAttackPosY[num4];
             if (Main.tile[num5, num6].type == 4 && Main.tile[num5, num6].frameX < 66)
             {
                 float num7 = 8f;
                 int num8 = 20;
                 if (num8 < 10)
                 {
                     num8 = 10;
                 }
                 int num9 = (int)MathHelper.Clamp(Main.tile[num5, num6].frameY / 22, 0f, TorchID.Count - 1);
                 num9 = TorchID.Dust[num9];
                 Main.tile[num5, num6].frameX += 66;
                 unlitTorchX[numberOfTorchAttacksMade] = num5;
                 unlitTorchY[numberOfTorchAttacksMade] = num6;
                 numberOfTorchAttacksMade++;
                 NetMessage.SendTileSquare(-1, num5, num6);
                 Vector2 vector = new Vector2(num5 * 16 + 8, num6 * 16);
                 Vector2 vector2 = base.Center - vector;
                 float num10 = vector2.Length();
                 vector2.Normalize();
                 vector2 *= num7;
                 int num11 = Projectile.NewProjectile(GetProjectileSource_Misc(10), vector, vector2, 949, num8, 1f, whoAmI, num9, num10);
                 Main.projectile[num11].ai[0] = num9;
                 Main.projectile[num11].ai[1] = num10;
                 Main.projectile[num11].netUpdate = true;
                 if ((num == 1 && numberOfTorchAttacksMade >= 95) || numberOfTorchAttacksMade >= maxTorchAttacks)
                 {
                     torchFunTimer = -180;
                 }
             }
         }
     }
References Tile.active(), Projectile.ai, TorchID.Count, TorchID.Dust, Tile.frameX, Tile.frameY, Main.maxTilesX, Main.maxTilesY, Main.myPlayer, Main.netMode, Projectile.netUpdate, Item.NewItem(), Projectile.NewProjectile(), UnifiedRandom.Next(), Main.projectile, Main.rand, NetMessage.SendData(), NetMessage.SendTileSquare(), Main.tile, Tile.type, and Main.worldSurface.