Terraria: Player.DropItemFromExtractinator
DropItemFromExtractinator()
void Player.DropItemFromExtractinator (int itemType, int stack) inline private
     {
         Vector2 vector = Main.ReverseGravitySupport(Main.MouseScreen) + Main.screenPosition;
         if (Main.SmartCursorIsUsed || PlayerInput.UsingGamepad)
         {
             vector = base.Center;
         }
         int number = Item.NewItem(GetItemSource_TileInteraction(tileTargetX, tileTargetY), (int)vector.X, (int)vector.Y, 1, 1, itemType, stack, noBroadcast: false, -1);
         if (Main.netMode == 1)
         {
             NetMessage.SendData(21, -1, -1, null, number, 1f);
         }
     }
References Main.MouseScreen, Main.netMode, Item.NewItem(), Main.ReverseGravitySupport(), Main.screenPosition, NetMessage.SendData(), Main.SmartCursorIsUsed, and PlayerInput.UsingGamepad.