Terraria: Player.SpawnFastRunParticles
SpawnFastRunParticles()
void Player.SpawnFastRunParticles () inline private
     {
         int num = 0;
         if (gravDir == -1f)
         {
             num -= height;
         }
         if (runSoundDelay == 0 && velocity.Y == 0f)
         {
             SoundEngine.PlaySound(hermesStepSound.SoundType, (int)position.X, (int)position.Y, hermesStepSound.SoundStyle);
             runSoundDelay = hermesStepSound.IntendedCooldown;
         }
         if (wings == 3)
         {
             int num2 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, 186, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 50, default(Color), 1.5f);
             Main.dust[num2].velocity *= 0.025f;
             Main.dust[num2].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
             num2 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, 186, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 50, default(Color), 1.5f);
             Main.dust[num2].velocity *= 0.2f;
             Main.dust[num2].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
         }
         else if (sailDash)
         {
             for (int i = 0; i < 4; i++)
             {
                 int num3 = Dust.NewDust(new Vector2(position.X - 4f, position.Y), width + 8, height, 253, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 100, default(Color), 1.5f);
                 Main.dust[num3].noGravity = true;
                 Main.dust[num3].velocity.X = Main.dust[num3].velocity.X * 0.2f;
                 Main.dust[num3].velocity.Y = Main.dust[num3].velocity.Y * 0.2f;
                 Main.dust[num3].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
                 Main.dust[num3].scale += (float)Main.rand.Next(-5, 3) * 0.1f;
                 Vector2 vector = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                 vector.Normalize();
                 vector *= (float)Main.rand.Next(81) * 0.1f;
             }
         }
         else if (desertDash)
         {
             Dust dust = Dust.NewDustDirect(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, 32, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f);
             dust.velocity *= 0.2f;
             dust.velocity.Y -= gravDir * 2f;
             dust.shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
         }
         else if (coldDash)
         {
             for (int j = 0; j < 2; j++)
             {
                 int num4 = ((j != 0) ? Dust.NewDust(new Vector2(position.X + (float)(width / 2), position.Y + (float)height + gfxOffY), width / 2, 6, 76, 0f, 0f, 0, default(Color), 1.35f) : Dust.NewDust(new Vector2(position.X, position.Y + (float)height + gfxOffY), width / 2, 6, 76, 0f, 0f, 0, default(Color), 1.35f));
                 Main.dust[num4].scale *= 1f + (float)Main.rand.Next(20, 40) * 0.01f;
                 Main.dust[num4].noGravity = true;
                 Main.dust[num4].noLight = true;
                 Main.dust[num4].velocity *= 0.001f;
                 Main.dust[num4].velocity.Y -= 0.003f;
                 Main.dust[num4].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
             }
         }
         else if (fairyBoots)
         {
             int type = Main.rand.NextFromList(new short[6] { 61, 61, 61, 242, 64, 63 });
             int alpha = 0;
             for (int k = 1; k < 3; k++)
             {
                 float scale = 1.5f;
                 if (k == 2)
                 {
                     scale = 1f;
                 }
                 int num5 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, type, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, alpha, default(Color), scale);
                 Main.dust[num5].velocity *= 1.5f;
                 if (k == 2)
                 {
                     Main.dust[num5].position += Main.dust[num5].velocity;
                 }
                 Main.dust[num5].noGravity = true;
                 Main.dust[num5].noLightEmittence = true;
                 Main.dust[num5].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
             }
         }
         else if (hellfireTreads)
         {
             int num6 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, 6, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 50, default(Color), 2f);
             Main.dust[num6].velocity.X = Main.dust[num6].velocity.X * 0.2f;
             Main.dust[num6].velocity.Y = -1.5f - Main.rand.NextFloat() * 0.5f;
             Main.dust[num6].fadeIn = 0.5f;
             Main.dust[num6].noGravity = true;
             Main.dust[num6].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
         }
         else
         {
             int num7 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, 16, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 50, default(Color), 1.5f);
             Main.dust[num7].velocity.X = Main.dust[num7].velocity.X * 0.2f;
             Main.dust[num7].velocity.Y = Main.dust[num7].velocity.Y * 0.2f;
             Main.dust[num7].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
         }
     }
References GameShaders.Armor, Color, Main.dust, Dust.fadeIn, ArmorShaderDataSet.GetSecondaryShader(), Dust.NewDust(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, SoundEngine.PlaySound(), Dust.position, Main.rand, Dust.scale, Dust.shader, and Dust.velocity.