Terraria: Player.TryLandingOnDetonator
TryLandingOnDetonator()
void Player.TryLandingOnDetonator () inline private
     {
         if (whoAmI == Main.myPlayer && velocity.Y >= 3f)
         {
             Point point = (base.Bottom + new Vector2(0f, 0.01f)).ToTileCoordinates();
             Tile tileSafely = Framing.GetTileSafely(point.X, point.Y);
             if (tileSafely.active() && tileSafely.type == 411 && tileSafely.frameY == 0 && tileSafely.frameX < 36)
             {
                 Wiring.HitSwitch(point.X, point.Y);
                 NetMessage.SendData(59, -1, -1, null, point.X, point.Y);
             }
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Framing.GetTileSafely(), Wiring.HitSwitch(), Main.myPlayer, NetMessage.SendData(), and Tile.type.