Terraria: Player.PickWall
PickWall()
void Player.PickWall (int x, int y, int damage) inline
     {
         int tileId = hitTile.HitObject(x, y, 2);
         if (hitTile.AddDamage(tileId, damage) >= 100)
         {
             hitTile.Clear(tileId);
             ClearMiningCacheAt(x, y, 2);
             WorldGen.KillWall(x, y);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 2, x, y);
             }
         }
         else
         {
             WorldGen.KillWall(x, y, fail: true);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 2, x, y, 1f);
             }
         }
         if (damage != 0)
         {
             hitTile.Prune();
         }
     }
References WorldGen.KillWall(), Main.netMode, and NetMessage.SendData().
Referenced by Mount.UseDrill().