Terraria: Player.Spawn_ForceClearArea
Spawn_ForceClearArea()
static void Player.Spawn_ForceClearArea (int floorX, int floorY) inline static private
     {
         for (int i = floorX - 1; i < floorX + 2; i++)
         {
             for (int j = floorY - 3; j < floorY; j++)
             {
                 if (Main.tile[i, j] != null)
                 {
                     if (Main.tile[i, j].nactive() && Main.tileSolid[Main.tile[i, j].type] && !Main.tileSolidTop[Main.tile[i, j].type])
                     {
                         WorldGen.KillTile(i, j);
                     }
                     if (Main.tile[i, j].liquid > 0)
                     {
                         Main.tile[i, j].lava(lava: false);
                         Main.tile[i, j].liquid = 0;
                         WorldGen.SquareTileFrame(i, j);
                     }
                 }
             }
         }
     }
References WorldGen.KillTile(), Tile.lava(), Tile.liquid, Tile.nactive(), WorldGen.SquareTileFrame(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.