Terraria: Player.ItemCheck
ItemCheck()
void Player.ItemCheck () inline
     {
         if (CCed)
         {
             channel = false;
             itemAnimation = (itemAnimationMax = 0);
             return;
         }
         float heightOffsetHitboxCenter = HeightOffsetHitboxCenter;
         Item item = inventory[selectedItem];
         ItemCheckContext context = default(ItemCheckContext);
         bool flag = false;
         if (Main.myPlayer == whoAmI)
         {
             if (PlayerInput.ShouldFastUseItem)
             {
                 controlUseItem = true;
                 flag = true;
             }
             if (!cursorItemIconEnabled && item.stack > 0 && item.fishingPole > 0)
             {
                 Fishing_GetBait(out var _, out var baitType);
                 if (baitType > 0)
                 {
                     cursorItemIconEnabled = true;
                     cursorItemIconID = baitType;
                     cursorItemIconPush = 6;
                 }
             }
             if (!cursorItemIconEnabled && item.stack > 0 && (item.type == 779 || item.type == 5134))
             {
                 for (int i = 54; i < 58; i++)
                 {
                     if (inventory[i].ammo == item.useAmmo && inventory[i].stack > 0)
                     {
                         cursorItemIconEnabled = true;
                         cursorItemIconID = inventory[i].type;
                         cursorItemIconPush = 10;
                         break;
                     }
                 }
                 if (!cursorItemIconEnabled)
                 {
                     for (int j = 0; j < 54; j++)
                     {
                         if (inventory[j].ammo == item.useAmmo && inventory[j].stack > 0)
{
                             cursorItemIconEnabled = true;
                             cursorItemIconID = inventory[j].type;
                             cursorItemIconPush = 10;
                             break;
                         }
                     }
                 }
             }
         }
         ItemCheck_HandleMount();
         int weaponDamage = GetWeaponDamage(item);
         ItemCheck_HandleMPItemAnimation(item);
         ItemCheck_HackHoldStyles(item);
         if (itemAnimation < 0)
         {
             itemAnimation = 0;
         }
         if (itemTime < 0)
         {
             itemTime = 0;
         }
         if (itemAnimation == 0 && reuseDelay > 0)
         {
             ApplyReuseDelay();
         }
         UpdatePlacementPreview(item);
         if (itemAnimation == 0 && altFunctionUse == 2)
         {
             altFunctionUse = 0;
         }
         bool flag2 = true;
         if (gravDir == -1f && GolfHelper.IsPlayerHoldingClub(this))
         {
             flag2 = false;
         }
         if (flag2 && controlUseItem && releaseUseItem && itemAnimation == 0 && item.useStyle != 0)
         {
             if (altFunctionUse == 1)
             {
                 altFunctionUse = 2;
             }
             if (item.shoot == 0)
             {
                 itemRotation = 0f;
             }
             bool flag3 = ItemCheck_CheckCanUse(item);
             if (item.potion && flag3)
             {
                 ApplyPotionDelay(item);
             }
             if (item.mana > 0 && flag3 && whoAmI == Main.myPlayer && item.buffType != 0 && item.buffTime != 0)
             {
                 AddBuff(item.buffType, item.buffTime);
             }
             if (item.shoot <= 0 || !ProjectileID.Sets.MinionTargettingFeature[item.shoot] || altFunctionUse != 2)
             {
                 ItemCheck_ApplyPetBuffs(item);
             }
             if (whoAmI == Main.myPlayer && gravDir == 1f && item.mountType != -1 && mount.CanMount(item.mountType, this))
             {
                 mount.SetMount(item.mountType, this);
             }
             if ((item.shoot <= 0 || !ProjectileID.Sets.MinionTargettingFeature[item.shoot] || altFunctionUse != 2) && flag3 && whoAmI == Main.myPlayer && item.shoot >= 0 && item.shoot < ProjectileID.Count && (ProjectileID.Sets.LightPet[item.shoot] || Main.projPet[item.shoot]))
             {
                 FreeUpPetsAndMinions(item);
             }
             if (flag3)
             {
                 ItemCheck_StartActualUse(item);
             }
         }
         bool flag4 = controlUseItem;
         if (mount.Active && mount.Type == 8)
         {
             flag4 = controlUseItem || controlUseTile;
         }
         if (!flag4)
         {
             channel = false;
         }
         Item item2 = ((itemAnimation > 0) ? lastVisualizedSelectedItem : item);
         Rectangle drawHitbox = Item.GetDrawHitbox(item2.type, this);
         compositeFrontArm.enabled = false;
         compositeBackArm.enabled = false;
         if (itemAnimation > 0)
         {
             if (item.mana > 0)
             {
                 ItemCheck_ApplyManaRegenDelay(item);
             }
             if (Main.dedServ)
             {
                 itemHeight = item.height;
                 itemWidth = item.width;
             }
             else
             {
                 itemHeight = drawHitbox.Height;
                 itemWidth = drawHitbox.Width;
             }
             itemAnimation--;
             if (itemAnimation == 0 && whoAmI == Main.myPlayer)
             {
                 PlayerInput.TryEndingFastUse();
             }
         }
         releaseUseItem = !controlUseItem;
         if (itemTime > 0)
         {
             itemTime--;
             if (ItemTimeIsZero && whoAmI == Main.myPlayer && !JustDroppedAnItem)
             {
                 int type = item.type;
                 if (type == 65 || type == 724 || type == 989 || type == 1226)
                 {
                     EmitMaxManaEffect();
                 }
             }
         }
         if (itemAnimation > 0)
         {
             ItemCheck_ApplyUseStyle(heightOffsetHitboxCenter, item2, drawHitbox);
         }
         else
         {
             ItemCheck_ApplyHoldStyle(heightOffsetHitboxCenter, item2, drawHitbox);
         }
         if (!JustDroppedAnItem)
         {
             ItemCheck_EmitHeldItemLight(item);
             ItemCheck_EmitFoodParticles(item);
             ItemCheck_EmitDrinkParticles(item);
             if (whoAmI == Main.myPlayer)
             {
                 ItemCheck_OwnerOnlyCode(ref context, item, weaponDamage, drawHitbox);
             }
             if (ItemTimeIsZero && itemAnimation > 0)
             {
                 if (item.hairDye >= 0)
                 {
                     ApplyItemTime(item);
                     if (whoAmI == Main.myPlayer)
                     {
                         hairDye = (byte)item.hairDye;
                         NetMessage.SendData(4, -1, -1, null, whoAmI);
                     }
                 }
                 if (item.healLife > 0 || item.healMana > 0)
                 {
                     ApplyLifeAndOrMana(item);
                     ApplyItemTime(item);
                     if (Main.myPlayer == whoAmI && item.type == 126 && breath == 0)
                     {
                         AchievementsHelper.HandleSpecialEvent(this, 25);
                     }
                 }
                 if (item.buffType > 0)
                 {
                     if (whoAmI == Main.myPlayer && item.buffType != 90 && item.buffType != 27)
                     {
                         AddBuff(item.buffType, item.buffTime);
                     }
                     ApplyItemTime(item);
                 }
                 if (item.type == 678)
                 {
                     if (Main.getGoodWorld)
                     {
                         ApplyItemTime(item);
                         if (whoAmI == Main.myPlayer)
{
                             for (int k = 0; k < 3; k++)
{
                                 int type2 = 0;
                                 int timeToAdd = 108000;
                                 switch (Main.rand.Next(18))
{
                                 case 0:
                                     type2 = 16;
                                     break;
                                 case 1:
                                     type2 = 111;
                                     break;
                                 case 2:
                                     type2 = 114;
                                     break;
                                 case 3:
                                     type2 = 8;
                                     break;
                                 case 4:
                                     type2 = 105;
                                     break;
                                 case 5:
                                     type2 = 17;
                                     break;
                                 case 6:
                                     type2 = 116;
                                     break;
                                 case 7:
                                     type2 = 5;
                                     break;
                                 case 8:
                                     type2 = 113;
                                     break;
                                 case 9:
                                     type2 = 7;
                                     break;
                                 case 10:
                                     type2 = 6;
                                     break;
                                 case 11:
                                     type2 = 104;
                                     break;
                                 case 12:
                                     type2 = 115;
                                     break;
                                 case 13:
                                     type2 = 2;
                                     break;
                                 case 14:
                                     type2 = 9;
                                     break;
                                 case 15:
                                     type2 = 3;
                                     break;
                                 case 16:
                                     type2 = 117;
                                     break;
                                 case 17:
                                     type2 = 1;
                                     break;
                                 }
                                 AddBuff(type2, timeToAdd);
                             }
                         }
                     }
                     else
                     {
                         ApplyItemTime(item);
                         if (whoAmI == Main.myPlayer)
{
                             AddBuff(20, 216000);
                             AddBuff(22, 216000);
                             AddBuff(23, 216000);
                             AddBuff(24, 216000);
                             AddBuff(30, 216000);
                             AddBuff(31, 216000);
                             AddBuff(32, 216000);
                             AddBuff(33, 216000);
                             AddBuff(35, 216000);
                             AddBuff(36, 216000);
                             AddBuff(68, 216000);
                         }
                     }
                 }
             }
             if ((item.type == 50 || item.type == 3124 || item.type == 3199 || item.type == 5358) && itemAnimation > 0)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     Dust.NewDust(position, width, height, 15, 0f, 0f, 150, default(Color), 1.1f);
                 }
                 if (ItemTimeIsZero)
                 {
                     ApplyItemTime(item);
                 }
                 else if (itemTime == item.useTime / 2)
                 {
                     for (int l = 0; l < 70; l++)
                     {
                         Dust.NewDust(position, width, height, 15, velocity.X * 0.5f, velocity.Y * 0.5f, 150, default(Color), 1.5f);
                     }
                     RemoveAllGrapplingHooks();
                     Spawn(PlayerSpawnContext.RecallFromItem);
                     for (int m = 0; m < 70; m++)
                     {
                         Dust.NewDust(position, width, height, 15, 0f, 0f, 150, default(Color), 1.5f);
                     }
                 }
             }
             if ((item.type == 4263 || item.type == 5360) && itemAnimation > 0)
             {
                 Vector2 vector = Vector2.UnitY.RotatedBy((float)itemAnimation * ((float)Math.PI * 2f) / 30f) * new Vector2(15f, 0f);
                 for (int n = 0; n < 2; n++)
                 {
                     if (Main.rand.Next(3) == 0)
                     {
                         Dust dust = Dust.NewDustPerfect(base.Bottom + vector, Dust.dustWater());
                         dust.velocity.Y *= 0f;
                         dust.velocity.Y -= 4.5f;
                         dust.velocity.X *= 1.5f;
                         dust.scale = 0.8f;
                         dust.alpha = 130;
                         dust.noGravity = true;
                         dust.fadeIn = 1.1f;
                     }
                 }
                 if (ItemTimeIsZero)
                 {
                     ApplyItemTime(item);
                 }
                 else if (itemTime == item.useTime / 2)
                 {
                     if (Main.netMode == 0)
                     {
                         MagicConch();
                     }
                     else if (Main.netMode == 1 && whoAmI == Main.myPlayer)
                     {
                         NetMessage.SendData(73, -1, -1, null, 1);
                     }
                 }
             }
             if ((item.type == 4819 || item.type == 5361) && itemAnimation > 0)
             {
                 Vector2 vector2 = Vector2.UnitY.RotatedBy((float)itemAnimation * ((float)Math.PI * 2f) / 30f) * new Vector2(15f, 0f);
                 for (int num = 0; num < 2; num++)
                 {
                     if (Main.rand.Next(3) == 0)
                     {
                         Dust dust2 = Dust.NewDustPerfect(base.Bottom + vector2, 35);
                         dust2.velocity.Y *= 0f;
                         dust2.velocity.Y -= 4.5f;
                         dust2.velocity.X *= 1.5f;
                         dust2.scale = 0.8f;
                         dust2.alpha = 130;
                         dust2.noGravity = true;
                         dust2.fadeIn = 1.1f;
                     }
                 }
                 if (ItemTimeIsZero)
                 {
                     ApplyItemTime(item);
                 }
                 else if (itemTime == item.useTime / 2)
                 {
                     if (Main.netMode == 0)
                     {
                         DemonConch();
                     }
                     else if (Main.netMode == 1 && whoAmI == Main.myPlayer)
                     {
                         NetMessage.SendData(73, -1, -1, null, 2);
                     }
                 }
             }
             if (item.type == 5359 && itemAnimation > 0)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     int num2 = Main.rand.Next(4);
                     Color color = Color.Green;
                     switch (num2)
                     {
                     case 0:
                     case 1:
                         color = new Color(100, 255, 100);
                         break;
                     case 2:
                         color = Color.Yellow;
                         break;
                     case 3:
                         color = Color.White;
                         break;
                     }
                     Dust dust3 = Dust.NewDustPerfect(Main.rand.NextVector2FromRectangle(base.Hitbox), 267);
                     dust3.noGravity = true;
                     dust3.color = color;
                     dust3.velocity *= 2f;
                     dust3.scale = 0.8f + Main.rand.NextFloat() * 0.6f;
                 }
                 if (ItemTimeIsZero)
                 {
                     ApplyItemTime(item);
                 }
                 else if (itemTime == item.useTime / 2)
                 {
                     if (Main.netMode == 0)
                     {
                         Shellphone_Spawn();
                     }
                     else if (Main.netMode == 1 && whoAmI == Main.myPlayer)
                     {
                         NetMessage.SendData(73, -1, -1, null, 3);
                     }
                 }
             }
             if (item.type == 2350 && itemAnimation > 0)
             {
                 if (ItemTimeIsZero)
                 {
                     ApplyItemTime(item);
                     SoundEngine.PlaySound(SoundID.Item3, position);
                     for (int num3 = 0; num3 < 10; num3++)
                     {
                         Main.dust[Dust.NewDust(position, width, height, 15, velocity.X * 0.2f, velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                     }
                 }
                 else if (itemTime == 20)
                 {
                     SoundEngine.PlaySound(HeldItem.UseSound, position);
                     for (int num4 = 0; num4 < 70; num4++)
                     {
                         Main.dust[Dust.NewDust(position, width, height, 15, velocity.X * 0.2f, velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                     }
                     RemoveAllGrapplingHooks();
                     bool flag5 = immune;
                     int num5 = immuneTime;
                     Spawn(PlayerSpawnContext.RecallFromItem);
                     immune = flag5;
                     immuneTime = num5;
                     for (int num6 = 0; num6 < 70; num6++)
                     {
                         Main.dust[Dust.NewDust(position, width, height, 15, 0f, 0f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                     }
                     if (item.stack > 0)
                     {
                         item.stack--;
                     }
                 }
             }
             if (item.type == 4870 && itemAnimation > 0)
             {
                 if (ItemTimeIsZero)
                 {
                     ApplyItemTime(item);
                     SoundEngine.PlaySound(SoundID.Item3, position);
                     for (int num7 = 0; num7 < 10; num7++)
                     {
                         Main.dust[Dust.NewDust(position, width, height, 15, velocity.X * 0.2f, velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                     }
                 }
                 else if (itemTime == 20)
                 {
                     SoundEngine.PlaySound(HeldItem.UseSound, position);
                     for (int num8 = 0; num8 < 70; num8++)
                     {
                         Main.dust[Dust.NewDust(position, width, height, 15, velocity.X * 0.2f, velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                     }
                     if (whoAmI == Main.myPlayer)
                     {
                         DoPotionOfReturnTeleportationAndSetTheComebackPoint();
                     }
                     for (int num9 = 0; num9 < 70; num9++)
                     {
                         Main.dust[Dust.NewDust(position, width, height, 15, 0f, 0f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                     }
                     if (item.stack > 0)
                     {
                         item.stack--;
                     }
                 }
             }
             if (item.type == 2351 && itemAnimation > 0)
             {
                 if (ItemTimeIsZero)
                 {
                     ApplyItemTime(item);
                 }
                 else if (itemTime == 2)
                 {
                     if (Main.netMode == 0)
                     {
                         TeleportationPotion();
                     }
                     else if (Main.netMode == 1 && whoAmI == Main.myPlayer)
                     {
                         NetMessage.SendData(73);
                     }
                     if (item.stack > 0)
                     {
                         item.stack--;
                     }
                 }
             }
             if (item.type == 2756 && itemAnimation > 0)
             {
                 if (ItemTimeIsZero)
                 {
                     ApplyItemTime(item);
                 }
                 else if (itemTime == 2)
                 {
                     if (whoAmI == Main.myPlayer)
                     {
                         Male = !Male;
                         if (Main.netMode == 1)
{
                             NetMessage.SendData(4, -1, -1, null, whoAmI);
                         }
                     }
                     if (item.stack > 0)
                     {
                         item.stack--;
                     }
                 }
                 else
                 {
                     float num10 = item.useTime;
                     num10 = (num10 - (float)itemTime) / num10;
                     float num11 = 44f;
                     float num12 = (float)Math.PI * 3f;
                     Vector2 vector3 = new Vector2(15f, 0f).RotatedBy(num12 * num10);
                     vector3.X *= direction;
                     for (int num13 = 0; num13 < 2; num13++)
                     {
                         int type3 = 221;
                         if (num13 == 1)
{
                             vector3.X *= -1f;
                             type3 = 219;
                         }
                         Vector2 vector4 = new Vector2(vector3.X, num11 * (1f - num10) - num11 + (float)(height / 2));
                         vector4 += base.Center;
                         int num14 = Dust.NewDust(vector4, 0, 0, type3, 0f, 0f, 100);
                         Main.dust[num14].position = vector4;
                         Main.dust[num14].noGravity = true;
                         Main.dust[num14].velocity = Vector2.Zero;
                         Main.dust[num14].scale = 1.3f;
                         Main.dust[num14].customData = this;
                     }
                 }
             }
             if (whoAmI == Main.myPlayer)
             {
                 if ((itemTimeMax != 0 && itemTime == itemTimeMax) | (!item.IsAir && item.IsNotTheSameAs(lastVisualizedSelectedItem)))
                 {
                     lastVisualizedSelectedItem = item.Clone();
                 }
             }
             else
             {
                 lastVisualizedSelectedItem = item.Clone();
             }
             if (whoAmI == Main.myPlayer)
             {
                 if (!dontConsumeWand && itemTime == (int)((float)item.useTime * tileSpeed) && item.tileWand > 0)
                 {
                     int tileWand = item.tileWand;
                     for (int num15 = 0; num15 < 58; num15++)
                     {
                         if (tileWand == inventory[num15].type && inventory[num15].stack > 0)
{
                             inventory[num15].stack--;
                             if (inventory[num15].stack <= 0)
{
                                 inventory[num15] = new Item();
                             }
                             break;
                         }
                     }
                 }
                 if (itemTimeMax != 0 && itemTime == itemTimeMax && item.consumable && !context.SkipItemConsumption)
                 {
                     bool flag6 = true;
                     if (item.ranged)
                     {
                         if (huntressAmmoCost90 && Main.rand.Next(10) == 0)
{
                             flag6 = false;
                         }
                         if (chloroAmmoCost80 && Main.rand.Next(5) == 0)
{
                             flag6 = false;
                         }
                         if (ammoCost80 && Main.rand.Next(5) == 0)
{
                             flag6 = false;
                         }
                         if (ammoCost75 && Main.rand.Next(4) == 0)
{
                             flag6 = false;
                         }
                     }
                     if (item.IsACoin)
                     {
                         flag6 = true;
                     }
                     bool? flag7 = ItemID.Sets.ForceConsumption[item.type];
                     if (flag7.HasValue)
                     {
                         flag6 = flag7.Value;
                     }
                     if (flag6)
                     {
                         if (item.stack > 0)
{
                             item.stack--;
                         }
                         if (item.stack <= 0)
{
                             itemTime = itemAnimation;
                             Main.blockMouse = true;
                         }
                     }
                 }
                 if (item.stack <= 0 && itemAnimation == 0)
                 {
                     inventory[selectedItem] = new Item();
                 }
                 if (selectedItem == 58 && itemAnimation != 0)
                 {
                     Main.mouseItem = item.Clone();
                 }
             }
         }
         if (itemAnimation == 0)
         {
             JustDroppedAnItem = false;
         }
         if (whoAmI == Main.myPlayer && flag)
         {
             PlayerInput.TryEndingFastUse();
         }
     }
References Dust.alpha, Main.blockMouse, Item.buffTime, Item.buffType, Item.Clone(), Color, Dust.color, Item.consumable, ProjectileID.Count, Dust.customData, Main.dedServ, Main.dust, Dust.dustWater(), Dust.fadeIn, Item.fishingPole, ItemID.Sets.ForceConsumption, Item.GetDrawHitbox(), Main.getGoodWorld, Item.hairDye, AchievementsHelper.HandleSpecialEvent(), Item.healLife, Item.healMana, Entity.height, Item.IsACoin, Item.IsAir, Item.IsNotTheSameAs(), GolfHelper.IsPlayerHoldingClub(), SoundID.Item3, ProjectileID.Sets.LightPet, Item.mana, ProjectileID.Sets.MinionTargettingFeature, Item.mountType, Main.mouseItem, Main.myPlayer, Main.netMode, Dust.NewDust(), Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, SoundEngine.PlaySound(), Dust.position, Item.potion, Main.projPet, Main.rand, Item.ranged, Dust.scale, NetMessage.SendData(), Item.shoot, PlayerInput.ShouldFastUseItem, Player.ItemCheckContext.SkipItemConsumption, Item.stack, Item.tileWand, PlayerInput.TryEndingFastUse(), Item.type, Item.useAmmo, Item.UseSound, Item.useStyle, Item.useTime, Dust.velocity, and Entity.width.