Terraria: Player.TrySwitchingLoadout
TrySwitchingLoadout()
void Player.TrySwitchingLoadout (int loadoutIndex) inline
     {
         bool flag = itemTime > 0 || itemAnimation > 0;
         if ((whoAmI != Main.myPlayer || (!flag && !CCed && !dead)) && loadoutIndex != CurrentLoadoutIndex && loadoutIndex >= 0 && loadoutIndex < Loadouts.Length)
         {
             Loadouts[CurrentLoadoutIndex].Swap(this);
             Loadouts[loadoutIndex].Swap(this);
             CurrentLoadoutIndex = loadoutIndex;
             if (whoAmI == Main.myPlayer)
             {
                 CloneLoadouts(Main.clientPlayer);
                 Main.mouseLeftRelease = false;
                 ItemSlot.RecordLoadoutChange();
                 SoundEngine.PlaySound(12);
                 NetMessage.TrySendData(147, -1, -1, null, whoAmI, loadoutIndex);
                 ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.LoadoutChange, new ParticleOrchestraSettings
                 {
                     PositionInWorld = base.Center,
                     UniqueInfoPiece = loadoutIndex
                 }, whoAmI);
             }
         }
     }
References Main.clientPlayer, Main.mouseLeftRelease, Main.myPlayer, SoundEngine.PlaySound(), ItemSlot.RecordLoadoutChange(), ParticleOrchestrator.RequestParticleSpawn(), and NetMessage.TrySendData().
Referenced by TriggersSet.CopyInto(), Main.DrawLoadoutButtons(), and MessageBuffer.GetData().