Terraria: Player.ItemCheck_UseBossSpawners
ItemCheck_UseBossSpawners()
void Player.ItemCheck_UseBossSpawners (int onWhichPlayer, Item sItem) inline private
     {
         if (!ItemTimeIsZero || itemAnimation <= 0 || (sItem.type != 43 && sItem.type != 70 && sItem.type != 544 && sItem.type != 556 && sItem.type != 557 && sItem.type != 560 && sItem.type != 1133 && sItem.type != 1331 && sItem.type != 4988 && sItem.type != 5120 && sItem.type != 5334) || !SummonItemCheck(sItem))
         {
             return;
         }
         if (sItem.type == 560)
         {
             ApplyItemTime(sItem);
             SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             if (Main.netMode != 1)
             {
                 NPC.SpawnOnPlayer(onWhichPlayer, 50);
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, 50f);
             }
         }
         else if (sItem.type == 43)
         {
             if (!Main.IsItDay())
             {
                 ApplyItemTime(sItem);
                 SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
                 if (Main.netMode != 1)
                 {
                     NPC.SpawnOnPlayer(onWhichPlayer, 4);
                 }
                 else
                 {
                     NetMessage.SendData(61, -1, -1, null, whoAmI, 4f);
                 }
             }
         }
         else if (sItem.type == 70)
         {
             if (ZoneCorrupt)
             {
                 ApplyItemTime(sItem);
                 SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
                 if (Main.netMode != 1)
                 {
                     NPC.SpawnOnPlayer(onWhichPlayer, 13);
                 }
                 else
                 {
                     NetMessage.SendData(61, -1, -1, null, whoAmI, 13f);
                 }
             }
         }
         else if (sItem.type == 544)
         {
             if (!Main.IsItDay() && sItem.Variant != ItemVariants.DisabledBossSummonVariant)
             {
                 ApplyItemTime(sItem);
                 SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
                 if (Main.netMode != 1)
                 {
                     NPC.SpawnOnPlayer(onWhichPlayer, 125);
                     NPC.SpawnOnPlayer(onWhichPlayer, 126);
                 }
                 else
                 {
                     NetMessage.SendData(61, -1, -1, null, whoAmI, 125f);
                     NetMessage.SendData(61, -1, -1, null, whoAmI, 126f);
                 }
             }
         }
         else if (sItem.type == 556)
         {
             if (!Main.IsItDay() && sItem.Variant != ItemVariants.DisabledBossSummonVariant)
             {
                 ApplyItemTime(sItem);
                 SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
                 if (Main.netMode != 1)
                 {
                     NPC.SpawnOnPlayer(onWhichPlayer, 134);
                 }
                 else
                 {
                     NetMessage.SendData(61, -1, -1, null, whoAmI, 134f);
                 }
             }
         }
         else if (sItem.type == 557)
         {
             if (!Main.IsItDay() && sItem.Variant != ItemVariants.DisabledBossSummonVariant)
             {
                 ApplyItemTime(sItem);
                 SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
                 if (Main.netMode != 1)
                 {
                     NPC.SpawnOnPlayer(onWhichPlayer, 127);
                 }
                 else
                 {
                     NetMessage.SendData(61, -1, -1, null, whoAmI, 127f);
                 }
             }
         }
         else if (sItem.type == 5334)
         {
             if (NPC.SpawnMechQueen(whoAmI))
             {
                 ApplyItemTime(sItem);
                 SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             }
         }
         else if (sItem.type == 1133)
         {
             ApplyItemTime(sItem);
             SoundEngine.PlaySound(SoundID.Item173, (int)position.X, (int)position.Y);
             if (Main.netMode != 1)
             {
                 NPC.SpawnOnPlayer(onWhichPlayer, 222);
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, 222f);
             }
         }
         else if (sItem.type == 1331)
         {
             if (ZoneCrimson)
             {
                 ApplyItemTime(sItem);
                 SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
                 if (Main.netMode != 1)
                 {
                     NPC.SpawnOnPlayer(onWhichPlayer, 266);
                 }
                 else
                 {
                     NetMessage.SendData(61, -1, -1, null, whoAmI, 266f);
                 }
             }
         }
         else if (sItem.type == 4988)
         {
             if (ZoneHallow)
             {
                 ApplyItemTime(sItem);
                 SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
                 if (Main.netMode != 1)
                 {
                     NPC.SpawnOnPlayer(onWhichPlayer, 657);
                 }
                 else
                 {
                     NetMessage.SendData(61, -1, -1, null, whoAmI, 657f);
                 }
             }
         }
         else if (sItem.type == 5120 && ZoneSnow)
         {
             ApplyItemTime(sItem);
             SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
             if (Main.netMode != 1)
             {
                 NPC.SpawnOnPlayer(onWhichPlayer, 668);
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, 668f);
             }
         }
     }
References ItemVariants.DisabledBossSummonVariant, Main.IsItDay(), SoundID.Item173, Main.netMode, SoundEngine.PlaySound(), NetMessage.SendData(), NPC.SpawnMechQueen(), NPC.SpawnOnPlayer(), Item.type, and Item.Variant.