Terraria: Player.CheckSpawn_Internal
CheckSpawn_Internal()
static bool Player.CheckSpawn_Internal (int x, int y) inline static private
     {
         if (x < 10 || x > Main.maxTilesX - 10 || y < 10 || y > Main.maxTilesX - 10)
         {
             return false;
         }
         if (Main.tile[x, y - 1] == null)
         {
             return false;
         }
         if (!Main.tile[x, y - 1].active() || Main.tile[x, y - 1].type != 79)
         {
             return false;
         }
         for (int i = x - 1; i <= x + 1; i++)
         {
             for (int j = y - 3; j < y; j++)
             {
                 if (Main.tile[i, j] == null)
                 {
                     return false;
                 }
                 if (Main.tile[i, j].nactive() && Main.tileSolid[Main.tile[i, j].type] && !Main.tileSolidTop[Main.tile[i, j].type])
                 {
                     Main.NewText(Language.GetTextValue("Game.BedObstructed"), byte.MaxValue, 240, 20);
                     return false;
                 }
             }
         }
         if (!WorldGen.StartRoomCheck(x, y - 1))
         {
             return false;
         }
         return true;
     }
References Tile.active(), Language.GetTextValue(), Main.maxTilesX, Tile.nactive(), Main.NewText(), WorldGen.StartRoomCheck(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.