Terraria: Player.clientClone
clientClone()
Player Player.clientClone () inline
     {
         Player player = new Player();
         player.zone1 = zone1;
         player.zone2 = zone2;
         player.zone3 = zone3;
         player.zone4 = zone4;
         player.zone5 = zone5;
         player.voidVaultInfo = voidVaultInfo;
         player.luck = luck;
         player.extraAccessory = extraAccessory;
         player.MinionRestTargetPoint = MinionRestTargetPoint;
         player.MinionAttackTargetNPC = MinionAttackTargetNPC;
         player.direction = direction;
         player.selectedItem = selectedItem;
         player.controlUp = controlUp;
         player.controlDown = controlDown;
         player.controlLeft = controlLeft;
         player.controlRight = controlRight;
         player.controlJump = controlJump;
         player.controlUseItem = controlUseItem;
         player.controlDownHold = controlDownHold;
         player.isOperatingAnotherEntity = isOperatingAnotherEntity;
         player.autoReuseAllWeapons = autoReuseAllWeapons;
         player.statLife = statLife;
         player.statLifeMax = statLifeMax;
         player.statMana = statMana;
         player.statManaMax = statManaMax;
         player.position.X = position.X;
         player.tileEntityAnchor = tileEntityAnchor;
         player.chest = chest;
         player.talkNPC = talkNPC;
         player.piggyBankProjTracker = piggyBankProjTracker;
         player.voidLensChest = voidLensChest;
         player.hideVisibleAccessory = hideVisibleAccessory;
         player.hideMisc = hideMisc;
         player.shieldRaised = shieldRaised;
         for (int i = 0; i < 59; i++)
         {
             player.inventory[i] = inventory[i].Clone();
             if (i < armor.Length)
             {
                 player.armor[i] = armor[i].Clone();
             }
             if (i < dye.Length)
             {
                 player.dye[i] = dye[i].Clone();
             }
             if (i < miscEquips.Length)
             {
                 player.miscEquips[i] = miscEquips[i].Clone();
             }
             if (i < miscDyes.Length)
             {
                 player.miscDyes[i] = miscDyes[i].Clone();
             }
             if (i < bank.item.Length)
             {
                 player.bank.item[i] = bank.item[i].Clone();
             }
             if (i < bank2.item.Length)
             {
                 player.bank2.item[i] = bank2.item[i].Clone();
             }
             if (i < bank3.item.Length)
             {
                 player.bank3.item[i] = bank3.item[i].Clone();
             }
             if (i < bank4.item.Length)
             {
                 player.bank4.item[i] = bank4.item[i].Clone();
             }
         }
         CloneLoadouts(player);
         player.trashItem = trashItem.Clone();
         for (int j = 0; j < maxBuffs; j++)
         {
             player.buffType[j] = buffType[j];
             player.buffTime[j] = buffTime[j];
         }
         DpadRadial.CopyTo(player.DpadRadial);
         CircularRadial.CopyTo(player.CircularRadial);
         return player;
     }
References armor, autoReuseAllWeapons, bank, bank2, bank3, bank4, buffTime, buffType, chest, CircularRadial, Item.Clone(), controlDown, controlDownHold, controlJump, controlLeft, controlRight, controlUp, controlUseItem, Entity.direction, DpadRadial, dye, extraAccessory, hideMisc, hideVisibleAccessory, inventory, isOperatingAnotherEntity, Chest.item, luck, MinionAttackTargetNPC, MinionRestTargetPoint, miscDyes, miscEquips, piggyBankProjTracker, Entity.position, selectedItem, shieldRaised, statLife, statLifeMax, statMana, statManaMax, talkNPC, tileEntityAnchor, trashItem, voidLensChest, voidVaultInfo, zone1, zone2, zone3, zone4, and zone5.
Referenced by Netplay.ClientLoopSetup(), and Main.TrySyncingMyPlayer().