Terraria: Player.LoadPlayer
LoadPlayer()
static PlayerFileData Player.LoadPlayer (string playerPath, bool cloudSave) inline static
     {
         PlayerFileData playerFileData = new PlayerFileData(playerPath, cloudSave);
         if (cloudSave && SocialAPI.Cloud == null)
         {
             return playerFileData;
         }
         if (Main.rand == null)
         {
             Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
         }
         Player player = new Player();
         bool gotToReadName = false;
         try
         {
             RijndaelManaged rijndaelManaged = new RijndaelManaged();
             rijndaelManaged.Padding = PaddingMode.None;
             using (MemoryStream stream = new MemoryStream(FileUtilities.ReadAllBytes(playerPath, cloudSave)))
             {
                 using CryptoStream input = new CryptoStream(stream, rijndaelManaged.CreateDecryptor(ENCRYPTION_KEY, ENCRYPTION_KEY), CryptoStreamMode.Read);
                 using BinaryReader binaryReader = new BinaryReader(input);
                 int num = binaryReader.ReadInt32();
                 if (num >= 135)
                 {
                     playerFileData.Metadata = FileMetadata.Read(binaryReader, FileType.Player);
                 }
                 else
                 {
                     playerFileData.Metadata = FileMetadata.FromCurrentSettings(FileType.Player);
                 }
                 if (num > 279)
                 {
                     player.loadStatus = 1;
                     player.name = binaryReader.ReadString();
                     playerFileData.Player = player;
                     return playerFileData;
                 }
                 Deserialize(playerFileData, player, binaryReader, num, out gotToReadName);
             }
             player.PlayerFrame();
             player.loadStatus = 0;
             playerFileData.Player = player;
             return playerFileData;
         }
         catch
         {
         }
         Player player2 = new Player();
         player2.loadStatus = 2;
         if (gotToReadName && player.name.Length <= nameLen)
         {
             player2.name = player.name;
         }
         else
         {
             string[] array = playerPath.Replace('/', Path.DirectorySeparatorChar).Split(Path.DirectorySeparatorChar);
             player2.name = array[array.Length - 1].Split('.')[0];
         }
         playerFileData.Player = player2;
         return playerFileData;
     }
References SocialAPI.Cloud, FileMetadata.FromCurrentSettings(), loadStatus, FileData.Metadata, name, PlayerFileData.Player, PlayerFrame(), Main.rand, FileMetadata.Read(), and FileUtilities.ReadAllBytes().