Terraria: Player.QuickHeal
QuickHeal()
void Player.QuickHeal () inline
     {
         if (cursed || CCed || dead || statLife == statLifeMax2 || potionDelay > 0)
         {
             return;
         }
         Item item = QuickHeal_GetItemToUse();
         if (item == null || !ItemCheck_CheckCanUse(item))
         {
             return;
         }
         SoundEngine.PlaySound(item.UseSound, position);
         if (item.potion)
         {
             ApplyPotionDelay(item);
         }
         ApplyLifeAndOrMana(item);
         if (item.type == 5)
         {
             TryToResetHungerToNeutral();
         }
         if (item.buffType > 0)
         {
             int num = item.buffTime;
             if (num == 0)
             {
                 num = 3600;
             }
             AddBuff(item.buffType, num);
         }
         item.stack--;
         if (item.stack <= 0)
         {
             item.TurnToAir();
         }
         if (Main.myPlayer == whoAmI && item.type == 126 && breath == 0)
         {
             AchievementsHelper.HandleSpecialEvent(this, 25);
         }
         Recipe.FindRecipes();
     }
References Item.buffTime, Item.buffType, Recipe.FindRecipes(), AchievementsHelper.HandleSpecialEvent(), Main.myPlayer, SoundEngine.PlaySound(), Item.potion, Item.stack, Item.TurnToAir(), Item.type, and Item.UseSound.