Terraria: Player.TryReplantingTree
TryReplantingTree()
void Player.TryReplantingTree () inline private
     {
         ushort type = 20;
         int style = 0;
         if (!TileObject.CanPlace(tileTargetX, tileTargetY, type, style, direction, out var objectData))
         {
             return;
         }
         bool num = TileObject.Place(objectData);
         WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
         if (num)
         {
             TileObjectData.CallPostPlacementPlayerHook(tileTargetX, tileTargetY, type, style, direction, objectData.alternate, objectData);
             if (Main.netMode == 1)
             {
                 NetMessage.SendObjectPlacement(-1, tileTargetX, tileTargetY, objectData.type, objectData.style, objectData.alternate, objectData.random, direction);
             }
         }
     }
References TileObjectData.CallPostPlacementPlayerHook(), TileObject.CanPlace(), Main.netMode, TileObject.Place(), NetMessage.SendObjectPlacement(), and WorldGen.SquareTileFrame().