Terraria: Player.PlaceThing_TryReplacingTiles
PlaceThing_TryReplacingTiles()
bool Player.PlaceThing_TryReplacingTiles (bool canUse) inline private
     {
         bool flag = PlaceThing_ValidTileForReplacement();
         if (flag)
         {
             TileObject.objectPreview.Reset();
         }
         if (controlUseItem && canUse && Main.tile[tileTargetX, tileTargetY].active() && itemAnimation > 0 && ItemTimeIsZero && flag)
         {
             Item bestPickaxe = GetBestPickaxe();
             if (bestPickaxe == null)
             {
                 return false;
             }
             Tile tile = Main.tile[tileTargetX, tileTargetY];
             _ = tile.type;
             int num = hitReplace.HitObject(tileTargetX, tileTargetY, 1);
             int pickaxeDamage = GetPickaxeDamage(tileTargetX, tileTargetY, bestPickaxe.pick, num, tile);
             if (pickaxeDamage == 0)
             {
                 return false;
             }
             if (!WorldGen.IsTileReplacable(tileTargetX, tileTargetY))
             {
                 return false;
             }
             if (0 == 0)
             {
                 if (hitReplace.AddDamage(num, pickaxeDamage) < 100)
                 {
                     int num2 = WorldGen.KillTile_GetTileDustAmount(fail: true, tile);
                     for (int i = 0; i < num2; i++)
                     {
                         WorldGen.KillTile_MakeTileDust(tileTargetX, tileTargetY, tile);
                     }
                     WorldGen.KillTile_PlaySounds(tileTargetX, tileTargetY, fail: true, tile);
                     if (HeldItem.consumable)
                     {
                         HeldItem.stack++;
                     }
                     dontConsumeWand = true;
                     ApplyItemTime(bestPickaxe, pickSpeed);
                     SetItemAnimation((int)((float)bestPickaxe.useTime * pickSpeed));
                     return false;
                 }
                 ClearMiningCacheAt(tileTargetX, tileTargetY, 1);
             }
             int[,] typeCaches = PlaceThing_Tiles_GetAutoAccessoryCache();
             ushort num3 = (ushort)HeldItem.createTile;
             int num4 = HeldItem.placeStyle;
             if (UsingBiomeTorches && num3 == 4)
             {
                 num4 = BiomeTorchPlaceStyle(num4);
             }
             if (UsingBiomeTorches && num3 == 215)
             {
                 num4 = BiomeCampfirePlaceStyle(num4);
             }
             if (WorldGen.ReplaceTile(tileTargetX, tileTargetY, num3, num4))
             {
                 canUse = false;
                 NetMessage.SendData(17, -1, -1, null, 21, tileTargetX, tileTargetY, (int)num3, num4);
                 ApplyItemTime(HeldItem);
                 SetItemAnimation(HeldItem.useAnimation);
                 PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(typeCaches, num3);
             }
         }
         return canUse;
     }
References Tile.active(), Item.consumable, Item.createTile, WorldGen.IsTileReplacable(), WorldGen.KillTile_GetTileDustAmount(), WorldGen.KillTile_MakeTileDust(), WorldGen.KillTile_PlaySounds(), TileObject.objectPreview, Item.pick, Item.placeStyle, WorldGen.ReplaceTile(), TileObjectPreviewData.Reset(), NetMessage.SendData(), Item.stack, Main.tile, Tile.type, Item.useAnimation, and Item.useTime.