Terraria: Player.EmitMaxManaEffect
EmitMaxManaEffect()
void Player.EmitMaxManaEffect () inline private
     {
         SoundEngine.PlaySound(25);
         for (int i = 0; i < 5; i++)
         {
             int num = Dust.NewDust(position, width, height, 45, 0f, 0f, 255, default(Color), (float)Main.rand.Next(20, 26) * 0.1f);
             Main.dust[num].noLight = true;
             Main.dust[num].noGravity = true;
             Main.dust[num].velocity *= 0.5f;
         }
     }
References Color, Main.dust, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, SoundEngine.PlaySound(), Main.rand, and Dust.velocity.