Terraria: Player.ChangeDir
ChangeDir()
void Player.ChangeDir (int dir) inline
     {
         if (!pulley || pulleyDir != 2)
         {
             direction = dir;
         }
         else
         {
             if (pulleyDir == 2 && dir == direction)
             {
                 return;
             }
             int num = (int)(position.X + (float)(width / 2)) / 16 * 16 + 8 - width / 2;
             if (!Collision.SolidCollision(new Vector2(num, position.Y), width, height))
             {
                 if (whoAmI == Main.myPlayer)
                 {
                     Main.cameraX = Main.cameraX + position.X - (float)num;
                 }
                 pulleyDir = 1;
                 position.X = num;
                 direction = dir;
             }
         }
     }
References Main.cameraX, Main.myPlayer, and Collision.SolidCollision().
Referenced by Projectile.AI_015_Flails(), Projectile.AI_015_Flails_Old(), Projectile.AI_075(), Projectile.AI_099_1(), Projectile.AI_099_2(), Projectile.AI_100_Medusa(), Projectile.AI_140_MonkStaffT1(), Projectile.AI_150_GolfClubHelper(), Projectile.AI_160_Kites(), PlayerSittingHelper.SitDown(), PlayerSleepingHelper.StartSleeping(), and DSTFilm.TurnPlayerToTheLeft().