Terraria: Player.Serialize
Serialize()
static void Player.Serialize (PlayerFileData playerFile, Player newPlayer, BinaryWriter fileIO) inline static private
     {
         fileIO.Write(newPlayer.name);
         fileIO.Write(newPlayer.difficulty);
         fileIO.Write(playerFile.GetPlayTime().Ticks);
         fileIO.Write(newPlayer.hair);
         fileIO.Write(newPlayer.hairDye);
         BitsByte bitsByte = (byte)0;
         for (int i = 0; i < 8; i++)
         {
             bitsByte[i] = newPlayer.hideVisibleAccessory[i];
         }
         fileIO.Write(bitsByte);
         bitsByte = (byte)0;
         for (int j = 0; j < 2; j++)
         {
             bitsByte[j] = newPlayer.hideVisibleAccessory[j + 8];
         }
         fileIO.Write(bitsByte);
         fileIO.Write(newPlayer.hideMisc);
         fileIO.Write((byte)newPlayer.skinVariant);
         fileIO.Write(newPlayer.statLife);
         fileIO.Write(newPlayer.statLifeMax);
         fileIO.Write(newPlayer.statMana);
         fileIO.Write(newPlayer.statManaMax);
         fileIO.Write(newPlayer.extraAccessory);
         fileIO.Write(newPlayer.unlockedBiomeTorches);
         fileIO.Write(newPlayer.UsingBiomeTorches);
         fileIO.Write(newPlayer.ateArtisanBread);
         fileIO.Write(newPlayer.usedAegisCrystal);
         fileIO.Write(newPlayer.usedAegisFruit);
         fileIO.Write(newPlayer.usedArcaneCrystal);
         fileIO.Write(newPlayer.usedGalaxyPearl);
         fileIO.Write(newPlayer.usedGummyWorm);
         fileIO.Write(newPlayer.usedAmbrosia);
         fileIO.Write(newPlayer.downedDD2EventAnyDifficulty);
         fileIO.Write(newPlayer.taxMoney);
         fileIO.Write(newPlayer.numberOfDeathsPVE);
         fileIO.Write(newPlayer.numberOfDeathsPVP);
         fileIO.Write(newPlayer.hairColor.R);
         fileIO.Write(newPlayer.hairColor.G);
         fileIO.Write(newPlayer.hairColor.B);
         fileIO.Write(newPlayer.skinColor.R);
         fileIO.Write(newPlayer.skinColor.G);
         fileIO.Write(newPlayer.skinColor.B);
         fileIO.Write(newPlayer.eyeColor.R);
         fileIO.Write(newPlayer.eyeColor.G);
         fileIO.Write(newPlayer.eyeColor.B);
         fileIO.Write(newPlayer.shirtColor.R);
         fileIO.Write(newPlayer.shirtColor.G);
         fileIO.Write(newPlayer.shirtColor.B);
         fileIO.Write(newPlayer.underShirtColor.R);
         fileIO.Write(newPlayer.underShirtColor.G);
         fileIO.Write(newPlayer.underShirtColor.B);
         fileIO.Write(newPlayer.pantsColor.R);
         fileIO.Write(newPlayer.pantsColor.G);
         fileIO.Write(newPlayer.pantsColor.B);
         fileIO.Write(newPlayer.shoeColor.R);
         fileIO.Write(newPlayer.shoeColor.G);
         fileIO.Write(newPlayer.shoeColor.B);
         for (int k = 0; k < newPlayer.armor.Length; k++)
         {
             fileIO.Write(newPlayer.armor[k].netID);
             fileIO.Write(newPlayer.armor[k].prefix);
         }
         for (int l = 0; l < newPlayer.dye.Length; l++)
         {
             fileIO.Write(newPlayer.dye[l].netID);
             fileIO.Write(newPlayer.dye[l].prefix);
         }
         for (int m = 0; m < 58; m++)
         {
             fileIO.Write(newPlayer.inventory[m].netID);
             fileIO.Write(newPlayer.inventory[m].stack);
             fileIO.Write(newPlayer.inventory[m].prefix);
             fileIO.Write(newPlayer.inventory[m].favorited);
         }
         for (int n = 0; n < newPlayer.miscEquips.Length; n++)
         {
             fileIO.Write(newPlayer.miscEquips[n].netID);
             fileIO.Write(newPlayer.miscEquips[n].prefix);
             fileIO.Write(newPlayer.miscDyes[n].netID);
             fileIO.Write(newPlayer.miscDyes[n].prefix);
         }
         for (int num = 0; num < 40; num++)
         {
             fileIO.Write(newPlayer.bank.item[num].netID);
             fileIO.Write(newPlayer.bank.item[num].stack);
             fileIO.Write(newPlayer.bank.item[num].prefix);
         }
         for (int num2 = 0; num2 < 40; num2++)
         {
             fileIO.Write(newPlayer.bank2.item[num2].netID);
             fileIO.Write(newPlayer.bank2.item[num2].stack);
             fileIO.Write(newPlayer.bank2.item[num2].prefix);
         }
         for (int num3 = 0; num3 < 40; num3++)
         {
             fileIO.Write(newPlayer.bank3.item[num3].netID);
             fileIO.Write(newPlayer.bank3.item[num3].stack);
             fileIO.Write(newPlayer.bank3.item[num3].prefix);
         }
         for (int num4 = 0; num4 < 40; num4++)
         {
             fileIO.Write(newPlayer.bank4.item[num4].netID);
             fileIO.Write(newPlayer.bank4.item[num4].stack);
             fileIO.Write(newPlayer.bank4.item[num4].prefix);
             fileIO.Write(newPlayer.bank4.item[num4].favorited);
         }
         fileIO.Write(newPlayer.voidVaultInfo);
         for (int num5 = 0; num5 < maxBuffs; num5++)
         {
             if (Main.buffNoSave[newPlayer.buffType[num5]])
             {
                 fileIO.Write(0);
                 fileIO.Write(0);
             }
             else
             {
                 fileIO.Write(newPlayer.buffType[num5]);
                 fileIO.Write(newPlayer.buffTime[num5]);
             }
         }
         for (int num6 = 0; num6 < 200; num6++)
         {
             if (newPlayer.spN[num6] == null)
             {
                 fileIO.Write(-1);
                 break;
             }
             fileIO.Write(newPlayer.spX[num6]);
             fileIO.Write(newPlayer.spY[num6]);
             fileIO.Write(newPlayer.spI[num6]);
             fileIO.Write(newPlayer.spN[num6]);
         }
         fileIO.Write(newPlayer.hbLocked);
         for (int num7 = 0; num7 < newPlayer.hideInfo.Length; num7++)
         {
             fileIO.Write(newPlayer.hideInfo[num7]);
         }
         fileIO.Write(newPlayer.anglerQuestsFinished);
         for (int num8 = 0; num8 < newPlayer.DpadRadial.Bindings.Length; num8++)
         {
             fileIO.Write(newPlayer.DpadRadial.Bindings[num8]);
         }
         for (int num9 = 0; num9 < newPlayer.builderAccStatus.Length; num9++)
         {
             fileIO.Write(newPlayer.builderAccStatus[num9]);
         }
         fileIO.Write(newPlayer.bartenderQuestLog);
         fileIO.Write(newPlayer.dead);
         if (newPlayer.dead)
         {
             fileIO.Write(newPlayer.respawnTimer);
         }
         long value = DateTime.UtcNow.ToBinary();
         fileIO.Write(value);
         fileIO.Write(newPlayer.golferScoreAccumulated);
         newPlayer.creativeTracker.Save(fileIO);
         newPlayer.SaveTemporaryItemSlotContents(fileIO);
         CreativePowerManager.Instance.SaveToPlayer(newPlayer, fileIO);
         BitsByte bitsByte2 = default(BitsByte);
         bitsByte2[0] = newPlayer.unlockedSuperCart;
         bitsByte2[1] = newPlayer.enabledSuperCart;
         fileIO.Write(bitsByte2);
         fileIO.Write(newPlayer.CurrentLoadoutIndex);
         for (int num10 = 0; num10 < newPlayer.Loadouts.Length; num10++)
         {
             newPlayer.Loadouts[num10].Serialize(fileIO);
         }
     }
References anglerQuestsFinished, armor, ateArtisanBread, bank, bank2, bank3, bank4, bartenderQuestLog, Player.SelectionRadial.Bindings, Main.buffNoSave, buffTime, buffType, builderAccStatus, creativeTracker, CurrentLoadoutIndex, dead, difficulty, downedDD2EventAnyDifficulty, DpadRadial, dye, enabledSuperCart, extraAccessory, eyeColor, Item.favorited, PlayerFileData.GetPlayTime(), golferScoreAccumulated, hair, hairColor, hairDye, hbLocked, hideInfo, hideMisc, hideVisibleAccessory, CreativePowerManager.Instance, inventory, Chest.item, Loadouts, miscDyes, miscEquips, name, Item.netID, numberOfDeathsPVE, numberOfDeathsPVP, pantsColor, Item.prefix, respawnTimer, CreativeUnlocksTracker.Save(), SaveTemporaryItemSlotContents(), CreativePowerManager.SaveToPlayer(), EquipmentLoadout.Serialize(), shirtColor, shoeColor, skinColor, skinVariant, spI, spN, spX, spY, Item.stack, statLife, statLifeMax, statMana, statManaMax, taxMoney, underShirtColor, unlockedBiomeTorches, unlockedSuperCart, usedAegisCrystal, usedAegisFruit, usedAmbrosia, usedArcaneCrystal, usedGalaxyPearl, usedGummyWorm, UsingBiomeTorches, and voidVaultInfo.