Terraria: Player.PlaceThing_TryReplacingWalls
PlaceThing_TryReplacingWalls()
bool Player.PlaceThing_TryReplacingWalls (bool canUse) inline private
     {
         if (canUse && itemAnimation > 0 && ItemTimeIsZero && controlUseItem && PlaceThing_ValidWallForReplacement() && WorldGen.NearFriendlyWall(tileTargetX, tileTargetY) && WorldGen.ReplaceWall(tileTargetX, tileTargetY, (ushort)HeldItem.createWall))
         {
             canUse = false;
             ApplyItemTime(HeldItem, wallSpeed);
             NetMessage.SendData(17, -1, -1, null, 22, tileTargetX, tileTargetY, HeldItem.createWall);
             if (autoPaint && builderAccStatus[3] == 0)
             {
                 TryPainting(tileTargetX, tileTargetY, paintingAWall: true, applyItemAnimation: false);
             }
         }
         return canUse;
     }
References Item.createWall, WorldGen.NearFriendlyWall(), WorldGen.ReplaceWall(), and NetMessage.SendData().