Terraria: Player.PetAnimal
PetAnimal()
void Player.PetAnimal (int animalNpcIndex) inline
     {
         GetPettingInfo(animalNpcIndex, out var targetDirection, out var playerPositionWhenPetting, out var isPetSmall);
         playerPositionWhenPetting = playerPositionWhenPetting.Floor();
         Vector2 offset = playerPositionWhenPetting - base.Bottom;
         bool flag = CanSnapToPosition(offset);
         if (flag && !WorldGen.SolidTileAllowBottomSlope((int)playerPositionWhenPetting.X / 16, (int)playerPositionWhenPetting.Y / 16))
         {
             flag = false;
         }
         if (!flag)
         {
             return;
         }
         if (isPettingAnimal && base.Bottom == playerPositionWhenPetting)
         {
             StopPettingAnimal();
             return;
         }
         StopVanityActions();
         RemoveAllGrapplingHooks();
         if (mount.Active)
         {
             mount.Dismount(this);
         }
         base.Bottom = playerPositionWhenPetting;
         ChangeDir(targetDirection);
         isPettingAnimal = true;
         isTheAnimalBeingPetSmall = isPetSmall;
         velocity = Vector2.Zero;
         gravDir = 1f;
         if (whoAmI == Main.myPlayer)
         {
             AchievementsHelper.HandleSpecialEvent(this, 21);
         }
     }
References AchievementsHelper.HandleSpecialEvent(), Main.myPlayer, and WorldGen.SolidTileAllowBottomSlope().
Referenced by Main.GUIChatDrawInner().