Terraria: Player.ItemCheck_OwnerOnlyCode
ItemCheck_OwnerOnlyCode()
void Player.ItemCheck_OwnerOnlyCode (ref ItemCheckContext context, Item sItem, int weaponDamage, Rectangle heldItemFrame) inline private
     {
         bool flag = true;
         int type = sItem.type;
         if ((type == 65 || type == 676 || type == 723 || type == 724 || type == 757 || type == 674 || type == 675 || type == 989 || type == 1226 || type == 1227) && !ItemAnimationJustStarted)
         {
             flag = false;
         }
         if (type == 5097 && ItemAnimationJustStarted)
         {
             _batbatCanHeal = true;
         }
         if (type == 5094 && ItemAnimationJustStarted)
         {
             _spawnTentacleSpikes = true;
         }
         if (type == 795 && ItemAnimationJustStarted)
         {
             _spawnBloodButcherer = true;
         }
         if (type == 121 && ItemAnimationJustStarted)
         {
             _spawnVolcanoExplosion = true;
         }
         if (type == 155 && ItemAnimationJustStarted)
         {
             _spawnMuramasaCut = true;
         }
         if (type == 3852)
         {
             if (itemAnimation < itemAnimationMax - 12)
             {
                 flag = false;
             }
             if (altFunctionUse == 2 && !ItemAnimationJustStarted)
             {
                 flag = false;
             }
         }
         if (type == 4956 && itemAnimation < itemAnimationMax - 3 * sItem.useTime)
         {
             flag = false;
         }
         if (type == 4952 && itemAnimation < itemAnimationMax - 8)
         {
             flag = false;
         }
         if (type == 4953 && itemAnimation < itemAnimationMax - 10)
         {
             flag = false;
         }
         if (type == 5451 && ownedProjectileCounts[1020] > 0)
         {
             flag = false;
         }
         ItemCheck_TurretAltFeatureUse(sItem, flag);
         ItemCheck_MinionAltFeatureUse(sItem, flag);
         bool flag2 = itemAnimation > 0 && ItemTimeIsZero && flag;
         if (sItem.shootsEveryUse)
         {
             flag2 = ItemAnimationJustStarted;
         }
         if (sItem.shoot > 0 && flag2)
         {
             ItemCheck_Shoot(whoAmI, sItem, weaponDamage);
         }
         ItemCheck_UseWiringTools(sItem);
         ItemCheck_UseLawnMower(sItem);
         ItemCheck_PlayInstruments(sItem);
         ItemCheck_UseBuckets(sItem);
         if (!channel)
         {
             toolTime = itemTime;
         }
         else
         {
             toolTime--;
             if (toolTime < 0)
             {
                 toolTime = sItem.useTime;
             }
         }
         ItemCheck_TryDestroyingDrones(sItem);
         ItemCheck_UseMiningTools(sItem);
         ItemCheck_UseTeleportRod(sItem);
         ItemCheck_UseLifeCrystal(sItem);
         ItemCheck_UseLifeFruit(sItem);
         ItemCheck_UseManaCrystal(sItem);
         ItemCheck_UseDemonHeart(sItem);
         ItemCheck_UseMinecartPowerUp(sItem);
         ItemCheck_UseTorchGodsFavor(sItem);
         ItemCheck_UseArtisanLoaf(sItem);
         ItemCheck_UseEventItems(sItem);
         ItemCheck_UseBossSpawners(whoAmI, sItem);
         ItemCheck_UseCombatBook(sItem);
         ItemCheck_UsePeddlersSatchel(sItem);
         ItemCheck_UsePetLicenses(sItem);
         ItemCheck_UseShimmerPermanentItems(sItem);
         if (sItem.type == 4095 && itemAnimation == 2)
         {
             Main.LocalGolfState.ResetGolfBall();
         }
         PlaceThing(ref context);
         if (sItem.makeNPC > 0)
         {
             if (!Main.GamepadDisableCursorItemIcon && position.X / 16f - (float)tileRangeX - (float)sItem.tileBoost <= (float)tileTargetX && (position.X + (float)width) / 16f + (float)tileRangeX + (float)sItem.tileBoost - 1f >= (float)tileTargetX && position.Y / 16f - (float)tileRangeY - (float)sItem.tileBoost <= (float)tileTargetY && (position.Y + (float)height) / 16f + (float)tileRangeY + (float)sItem.tileBoost - 2f >= (float)tileTargetY)
             {
                 cursorItemIconEnabled = true;
                 Main.ItemIconCacheUpdate(sItem.type);
             }
             if (ItemTimeIsZero && itemAnimation > 0 && controlUseItem)
             {
                 ItemCheck_ReleaseCritter(sItem);
             }
         }
         if (boneGloveItem != null && !boneGloveItem.IsAir && boneGloveTimer == 0 && itemAnimation > 0 && sItem.damage > 0)
         {
             boneGloveTimer = 60;
             Vector2 center = base.Center;
             Vector2 vector = DirectionTo(ApplyRangeCompensation(0.2f, center, Main.MouseWorld)) * 10f;
             Projectile.NewProjectile(GetProjectileSource_Accessory(boneGloveItem), center.X, center.Y, vector.X, vector.Y, 532, 25, 5f, whoAmI);
         }
         if (((sItem.damage < 0 || sItem.type <= 0 || sItem.noMelee) && sItem.type != 1450 && sItem.type != 1991 && sItem.type != 3183 && sItem.type != 4821 && sItem.type != 3542 && sItem.type != 3779) || itemAnimation <= 0)
         {
             return;
         }
         ItemCheck_GetMeleeHitbox(sItem, heldItemFrame, out var dontAttack, out var itemRectangle);
         if (dontAttack)
         {
             return;
         }
         itemRectangle = ItemCheck_EmitUseVisuals(sItem, itemRectangle);
         if (Main.myPlayer == whoAmI && (sItem.type == 1991 || sItem.type == 3183 || sItem.type == 4821))
         {
             itemRectangle = ItemCheck_CatchCritters(sItem, itemRectangle);
         }
         if (sItem.type == 3183 || sItem.type == 4821)
         {
             bool[] shouldIgnore = ItemCheck_GetTileCutIgnoreList(sItem);
             ItemCheck_CutTiles(sItem, itemRectangle, shouldIgnore);
         }
         if (sItem.damage > 0)
         {
             UpdateMeleeHitCooldowns();
             float knockBack = sItem.knockBack;
             float num = 1f;
             if (kbGlove)
             {
                 num += 1f;
             }
             if (kbBuff)
             {
                 num += 0.5f;
             }
             knockBack *= num;
             if (inventory[selectedItem].type == 3106)
             {
                 knockBack += knockBack * (1f - stealth);
             }
             bool[] shouldIgnore2 = ItemCheck_GetTileCutIgnoreList(sItem);
             ItemCheck_CutTiles(sItem, itemRectangle, shouldIgnore2);
             ItemCheck_MeleeHitNPCs(sItem, itemRectangle, weaponDamage, knockBack);
             ItemCheck_MeleeHitPVP(sItem, itemRectangle, weaponDamage, knockBack);
             ItemCheck_EmitHammushProjectiles(whoAmI, sItem, itemRectangle, weaponDamage);
         }
     }
References Item.damage, Main.GamepadDisableCursorItemIcon, Main.ItemIconCacheUpdate(), Item.knockBack, Main.LocalGolfState, Item.makeNPC, Main.MouseWorld, Main.myPlayer, Projectile.NewProjectile(), Item.noMelee, GolfState.ResetGolfBall(), Item.shoot, Item.shootsEveryUse, Item.tileBoost, Item.type, and Item.useTime.