Terraria: Player.GrappleMovement
GrappleMovement()
void Player.GrappleMovement () inline
     {
         if (grappling[0] < 0)
         {
             return;
         }
         StopVanityActions();
         if (Main.myPlayer == whoAmI && mount.Active)
         {
             mount.Dismount(this);
         }
         canCarpet = true;
         carpetFrame = -1;
         wingFrame = 1;
         if (velocity.Y == 0f || (wet && (double)velocity.Y > -0.02 && (double)velocity.Y < 0.02))
         {
             wingFrame = 0;
         }
         if (wings == 4)
         {
             wingFrame = 3;
         }
         if (wings == 30)
         {
             wingFrame = 0;
         }
         RefreshMovementAbilities();
         rocketFrame = false;
         canRocket = false;
         rocketRelease = false;
         fallStart = (int)(position.Y / 16f);
         int num = -1;
         for (int i = 0; i < grapCount; i++)
         {
             if (Main.projectile[grappling[i]].type == 403)
             {
                 num = i;
             }
         }
         GetGrapplingForces(base.Center, out var preferredPlayerDirectionToSet, out var preferedPlayerVelocityX, out var preferedPlayerVelocityY);
         if (preferedPlayerVelocityY > 0f)
         {
             GoingDownWithGrapple = true;
         }
         velocity.X = preferedPlayerVelocityX;
         velocity.Y = preferedPlayerVelocityY;
         if (num != -1)
         {
             Projectile projectile = Main.projectile[grappling[num]];
             if (projectile.position.X < position.X + (float)width && projectile.position.X + (float)projectile.width >= position.X && projectile.position.Y < position.Y + (float)height && projectile.position.Y + (float)projectile.height >= position.Y)
             {
                 int num2 = (int)(projectile.position.X + (float)(projectile.width / 2)) / 16;
                 int num3 = (int)(projectile.position.Y + (float)(projectile.height / 2)) / 16;
                 velocity = Vector2.Zero;
                 if (Main.tile[num2, num3].type == 314)
                 {
                     Vector2 Position = default(Vector2);
                     Position.X = projectile.position.X + (float)(projectile.width / 2) - (float)(width / 2);
                     Position.Y = projectile.position.Y + (float)(projectile.height / 2) - (float)(height / 2);
                     RemoveAllGrapplingHooks();
                     int num4 = 13;
                     if (miscEquips[2].stack > 0 && miscEquips[2].mountType >= 0 && MountID.Sets.Cart[miscEquips[2].mountType] && (!miscEquips[2].expertOnly || Main.expertMode))
                     {
                         num4 = miscEquips[2].mountType;
                     }
                     int num5 = height + Mount.GetHeightBoost(num4);
                     if (Minecart.GetOnTrack(num2, num3, ref Position, width, num5) && !Collision.SolidCollision(Position, width, num5 - 20))
                     {
                         position = Position;
                         DelegateMethods.Minecart.rotation = fullRotation;
                         DelegateMethods.Minecart.rotationOrigin = fullRotationOrigin;
                         mount.SetMount(num4, this, minecartLeft);
                         Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 25);
                     }
                 }
             }
         }
         if (itemAnimation == 0)
         {
             if (velocity.X == 0f && preferredPlayerDirectionToSet.HasValue)
             {
                 ChangeDir(preferredPlayerDirectionToSet.Value);
             }
             if (velocity.X > 0f)
             {
                 ChangeDir(1);
             }
             if (velocity.X < 0f)
             {
                 ChangeDir(-1);
             }
         }
         if (controlJump)
         {
             if (releaseJump)
             {
                 if ((velocity.Y == 0f || (wet && (double)velocity.Y > -0.02 && (double)velocity.Y < 0.02)) && !controlDown)
                 {
                     velocity.Y = 0f - jumpSpeed;
                     jump = jumpHeight / 2;
                     releaseJump = false;
                 }
                 else
                 {
                     velocity.Y += 0.01f;
                     releaseJump = false;
                 }
                 RefreshDoubleJumps();
                 RemoveAllGrapplingHooks();
             }
         }
         else
         {
             releaseJump = true;
         }
     }
References MountID.Sets.Cart, Main.expertMode, Mount.GetHeightBoost(), Minecart.GetOnTrack(), Entity.height, Main.myPlayer, Entity.position, Main.projectile, DelegateMethods.Minecart.rotation, DelegateMethods.Minecart.rotationOrigin, Collision.SolidCollision(), Main.tile, Projectile.type, Tile.type, Minecart.WheelSparks(), and Entity.width.