Terraria: Player.PlaceThing_Tiles_BlockPlacementForAssortedThings
PlaceThing_Tiles_BlockPlacementForAssortedThings()
bool Player.PlaceThing_Tiles_BlockPlacementForAssortedThings (bool canPlace) inline private
     {
         bool flag = inventory[selectedItem].type == 213 || inventory[selectedItem].type == 5295;
         if (flag)
         {
             if (Main.tile[tileTargetX, tileTargetY].type == 0 || Main.tile[tileTargetX, tileTargetY].type == 1 || Main.tile[tileTargetX, tileTargetY].type == 38)
             {
                 canPlace = true;
             }
         }
         else if (inventory[selectedItem].createTile == 2 || inventory[selectedItem].createTile == 109)
         {
             if (Main.tile[tileTargetX, tileTargetY].nactive() && Main.tile[tileTargetX, tileTargetY].type == 0)
             {
                 canPlace = true;
             }
         }
         else if (inventory[selectedItem].createTile == 23 || inventory[selectedItem].createTile == 199)
         {
             if (Main.tile[tileTargetX, tileTargetY].nactive())
             {
                 if (Main.tile[tileTargetX, tileTargetY].type == 0)
                 {
                     canPlace = true;
                 }
                 else if (Main.tile[tileTargetX, tileTargetY].type == 59)
                 {
                     canPlace = true;
                 }
             }
         }
         else if (inventory[selectedItem].createTile == 227)
         {
             canPlace = true;
         }
         else if (inventory[selectedItem].createTile >= 373 && inventory[selectedItem].createTile <= 375)
         {
             int num = tileTargetX;
             int num2 = tileTargetY - 1;
             if (Main.tile[num, num2].nactive() && Main.tileSolid[Main.tile[num, num2].type] && !Main.tileSolidTop[Main.tile[num, num2].type])
             {
                 canPlace = true;
             }
         }
         else if (inventory[selectedItem].createTile == 461)
         {
             int num3 = tileTargetX;
             int num4 = tileTargetY - 1;
             if (Main.tile[num3, num4].nactive() && Main.tileSolid[Main.tile[num3, num4].type] && !Main.tileSolidTop[Main.tile[num3, num4].type])
             {
                 canPlace = true;
             }
         }
         else if (inventory[selectedItem].createTile == 60 || inventory[selectedItem].createTile == 70 || inventory[selectedItem].createTile == 661 || inventory[selectedItem].createTile == 662)
         {
             if (Main.tile[tileTargetX, tileTargetY].nactive() && Main.tile[tileTargetX, tileTargetY].type == 59)
             {
                 canPlace = true;
             }
         }
         else if (inventory[selectedItem].createTile == 4 || inventory[selectedItem].createTile == 136)
         {
             if (Main.tile[tileTargetX, tileTargetY].wall > 0)
             {
                 canPlace = true;
             }
             else
             {
                 if (!WorldGen.SolidTileNoAttach(tileTargetX, tileTargetY + 1) && !WorldGen.SolidTileNoAttach(tileTargetX - 1, tileTargetY) && !WorldGen.SolidTileNoAttach(tileTargetX + 1, tileTargetY))
                 {
                     if (!WorldGen.SolidTileNoAttach(tileTargetX, tileTargetY + 1) && (Main.tile[tileTargetX, tileTargetY + 1].halfBrick() || Main.tile[tileTargetX, tileTargetY + 1].slope() != 0))
                     {
                         if (!TileID.Sets.Platforms[Main.tile[tileTargetX, tileTargetY + 1].type])
{
                             WorldGen.SlopeTile(tileTargetX, tileTargetY + 1);
                             if (Main.netMode == 1)
{
                                 NetMessage.SendData(17, -1, -1, null, 14, tileTargetX, tileTargetY + 1);
                             }
                         }
                     }
                     else if (!WorldGen.SolidTileNoAttach(tileTargetX, tileTargetY + 1) && !WorldGen.SolidTileNoAttach(tileTargetX - 1, tileTargetY) && (Main.tile[tileTargetX - 1, tileTargetY].halfBrick() || Main.tile[tileTargetX - 1, tileTargetY].slope() != 0))
                     {
                         if (!TileID.Sets.Platforms[Main.tile[tileTargetX - 1, tileTargetY].type])
{
                             WorldGen.SlopeTile(tileTargetX - 1, tileTargetY);
                             if (Main.netMode == 1)
{
                                 NetMessage.SendData(17, -1, -1, null, 14, tileTargetX - 1, tileTargetY);
                             }
                         }
                     }
                     else if (!WorldGen.SolidTileNoAttach(tileTargetX, tileTargetY + 1) && !WorldGen.SolidTileNoAttach(tileTargetX + 1, tileTargetY) && (Main.tile[tileTargetX + 1, tileTargetY].halfBrick() || Main.tile[tileTargetX + 1, tileTargetY].slope() != 0) && !TileID.Sets.Platforms[Main.tile[tileTargetX + 1, tileTargetY].type])
                     {
                         WorldGen.SlopeTile(tileTargetX + 1, tileTargetY);
                         if (Main.netMode == 1)
{
                             NetMessage.SendData(17, -1, -1, null, 14, tileTargetX + 1, tileTargetY);
                         }
                     }
                 }
                 int num5 = Main.tile[tileTargetX, tileTargetY + 1].type;
                 if (Main.tile[tileTargetX, tileTargetY].halfBrick())
                 {
                     num5 = -1;
                 }
                 int num6 = Main.tile[tileTargetX - 1, tileTargetY].type;
                 int num7 = Main.tile[tileTargetX + 1, tileTargetY].type;
                 int tree = Main.tile[tileTargetX - 1, tileTargetY - 1].type;
                 int tree2 = Main.tile[tileTargetX + 1, tileTargetY - 1].type;
                 int tree3 = Main.tile[tileTargetX - 1, tileTargetY - 1].type;
                 int tree4 = Main.tile[tileTargetX + 1, tileTargetY + 1].type;
                 if (!Main.tile[tileTargetX, tileTargetY + 1].nactive())
                 {
                     num5 = -1;
                 }
                 if (!Main.tile[tileTargetX - 1, tileTargetY].nactive())
                 {
                     num6 = -1;
                 }
                 if (!Main.tile[tileTargetX + 1, tileTargetY].nactive())
                 {
                     num7 = -1;
                 }
                 if (!Main.tile[tileTargetX - 1, tileTargetY - 1].nactive())
                 {
                     tree = -1;
                 }
                 if (!Main.tile[tileTargetX + 1, tileTargetY - 1].nactive())
                 {
                     tree2 = -1;
                 }
                 if (!Main.tile[tileTargetX - 1, tileTargetY + 1].nactive())
                 {
                     tree3 = -1;
                 }
                 if (!Main.tile[tileTargetX + 1, tileTargetY + 1].nactive())
                 {
                     tree4 = -1;
                 }
                 if (num5 >= 0 && Main.tileSolid[num5] && (!Main.tileNoAttach[num5] || (num5 >= 0 && TileID.Sets.Platforms[num5])))
                 {
                     canPlace = true;
                 }
                 else if ((num6 >= 0 && Main.tileSolid[num6] && !Main.tileNoAttach[num6]) || (WorldGen.IsTreeType(num6) && WorldGen.IsTreeType(tree) && WorldGen.IsTreeType(tree3)) || (num6 >= 0 && TileID.Sets.IsBeam[num6]))
                 {
                     canPlace = true;
                 }
                 else if ((num7 >= 0 && Main.tileSolid[num7] && !Main.tileNoAttach[num7]) || (WorldGen.IsTreeType(num7) && WorldGen.IsTreeType(tree2) && WorldGen.IsTreeType(tree4)) || (num7 >= 0 && TileID.Sets.IsBeam[num7]))
                 {
                     canPlace = true;
                 }
             }
         }
         else if (inventory[selectedItem].createTile == 78 || inventory[selectedItem].createTile == 98 || inventory[selectedItem].createTile == 100 || inventory[selectedItem].createTile == 173 || inventory[selectedItem].createTile == 174 || inventory[selectedItem].createTile == 324)
         {
             if (Main.tile[tileTargetX, tileTargetY + 1].nactive() && (Main.tileSolid[Main.tile[tileTargetX, tileTargetY + 1].type] || Main.tileTable[Main.tile[tileTargetX, tileTargetY + 1].type]))
             {
                 canPlace = true;
             }
         }
         else if (inventory[selectedItem].createTile == 419)
         {
             if (Main.tile[tileTargetX, tileTargetY + 1].active() && (Main.tile[tileTargetX, tileTargetY + 1].type == 419 || (inventory[selectedItem].placeStyle != 2 && Main.tile[tileTargetX, tileTargetY + 1].type == 420)))
             {
                 canPlace = true;
             }
         }
         else if (inventory[selectedItem].createTile == 13 || inventory[selectedItem].createTile == 29 || inventory[selectedItem].createTile == 33 || inventory[selectedItem].createTile == 49 || inventory[selectedItem].createTile == 50 || inventory[selectedItem].createTile == 103)
         {
             if (Main.tile[tileTargetX, tileTargetY + 1].nactive() && Main.tileTable[Main.tile[tileTargetX, tileTargetY + 1].type])
             {
                 canPlace = true;
             }
         }
         else if (inventory[selectedItem].createTile == 275 || inventory[selectedItem].createTile == 276 || inventory[selectedItem].createTile == 277)
         {
             canPlace = true;
         }
         else if (inventory[selectedItem].createTile == 51 || inventory[selectedItem].createTile == 330 || inventory[selectedItem].createTile == 331 || inventory[selectedItem].createTile == 332 || inventory[selectedItem].createTile == 333 || inventory[selectedItem].createTile == 336 || inventory[selectedItem].createTile == 340 || inventory[selectedItem].createTile == 342 || inventory[selectedItem].createTile == 341 || inventory[selectedItem].createTile == 343 || inventory[selectedItem].createTile == 344 || inventory[selectedItem].createTile == 379 || inventory[selectedItem].createTile == 351)
         {
             if (Main.tile[tileTargetX + 1, tileTargetY].active() || Main.tile[tileTargetX + 1, tileTargetY].wall > 0 || Main.tile[tileTargetX - 1, tileTargetY].active() || Main.tile[tileTargetX - 1, tileTargetY].wall > 0 || Main.tile[tileTargetX, tileTargetY + 1].active() || Main.tile[tileTargetX, tileTargetY + 1].wall > 0 || Main.tile[tileTargetX, tileTargetY - 1].active() || Main.tile[tileTargetX, tileTargetY - 1].wall > 0)
             {
                 canPlace = true;
             }
         }
         else if (inventory[selectedItem].createTile == 314)
         {
             for (int i = tileTargetX - 1; i <= tileTargetX + 1; i++)
             {
                 for (int j = tileTargetY - 1; j <= tileTargetY + 1; j++)
                 {
                     Tile tile = Main.tile[i, j];
                     if (tile.active() || tile.wall > 0)
                     {
                         canPlace = true;
                         break;
                     }
                 }
             }
         }
         else
         {
             Tile tile2 = Main.tile[tileTargetX - 1, tileTargetY];
             Tile tile3 = Main.tile[tileTargetX + 1, tileTargetY];
             Tile tile4 = Main.tile[tileTargetX, tileTargetY - 1];
             Tile tile5 = Main.tile[tileTargetX, tileTargetY + 1];
             if ((tile3.active() && (Main.tileSolid[tile3.type] || TileID.Sets.IsBeam[tile3.type] || Main.tileRope[tile3.type] || tile3.type == 314)) || tile3.wall > 0 || (tile2.active() && (Main.tileSolid[tile2.type] || TileID.Sets.IsBeam[tile2.type] || Main.tileRope[tile2.type] || tile2.type == 314)) || tile2.wall > 0 || (tile5.active() && (Main.tileSolid[tile5.type] || TileID.Sets.IsBeam[tile5.type] || Main.tileRope[tile5.type] || tile5.type == 314)) || tile5.wall > 0 || (tile4.active() && (Main.tileSolid[tile4.type] || TileID.Sets.IsBeam[tile4.type] || Main.tileRope[tile4.type] || tile4.type == 314)) || tile4.wall > 0)
             {
                 canPlace = true;
             }
             else if (Main.tile[tileTargetX, tileTargetY].wall > 0)
             {
                 canPlace = true;
             }
         }
         if (flag && Main.tile[tileTargetX, tileTargetY].active())
         {
             int num8 = tileTargetX;
             int num9 = tileTargetY;
             if (Main.tile[num8, num9].type == 3 || Main.tile[num8, num9].type == 73 || Main.tile[num8, num9].type == 84)
             {
                 WorldGen.KillTile(tileTargetX, tileTargetY);
                 if (!Main.tile[tileTargetX, tileTargetY].active() && Main.netMode == 1)
                 {
                     NetMessage.SendData(17, -1, -1, null, 0, tileTargetX, tileTargetY);
                 }
             }
             else if (Main.tile[num8, num9].type == 83)
             {
                 bool flag2 = false;
                 int num10 = Main.tile[num8, num9].frameX / 18;
                 if (num10 == 0 && Main.dayTime)
                 {
                     flag2 = true;
                 }
                 if (num10 == 1 && !Main.dayTime)
                 {
                     flag2 = true;
                 }
                 if (num10 == 3 && !Main.dayTime && (Main.bloodMoon || Main.moonPhase == 0))
                 {
                     flag2 = true;
                 }
                 if (num10 == 4 && (Main.raining || Main.cloudAlpha > 0f))
                 {
                     flag2 = true;
                 }
                 if (num10 == 5 && !Main.raining && Main.dayTime && Main.time > 40500.0)
                 {
                     flag2 = true;
                 }
                 if (flag2)
                 {
                     WorldGen.KillTile(tileTargetX, tileTargetY);
                     NetMessage.SendData(17, -1, -1, null, 0, tileTargetX, tileTargetY);
                 }
             }
         }
         if (Main.tileAlch[inventory[selectedItem].createTile])
         {
             canPlace = true;
         }
         if (Main.tile[tileTargetX, tileTargetY].active() && (Main.tileCut[Main.tile[tileTargetX, tileTargetY].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[tileTargetX, tileTargetY].type] || (Main.tile[tileTargetX, tileTargetY].type >= 373 && Main.tile[tileTargetX, tileTargetY].type <= 375) || Main.tile[tileTargetX, tileTargetY].type == 461))
         {
             if (Main.tile[tileTargetX, tileTargetY].type != inventory[selectedItem].createTile)
             {
                 bool num11 = Main.tile[tileTargetX, tileTargetY + 1].type != 78 && Main.tile[tileTargetX, tileTargetY + 1].type != 380 && Main.tile[tileTargetX, tileTargetY + 1].type != 579;
                 bool flag3 = Main.tile[tileTargetX, tileTargetY].type == 3 || Main.tile[tileTargetX, tileTargetY].type == 73;
                 bool flag4 = Main.tileAlch[Main.tile[tileTargetX, tileTargetY].type] && WorldGen.IsHarvestableHerbWithSeed(Main.tile[tileTargetX, tileTargetY].type, Main.tile[tileTargetX, tileTargetY].frameX / 18);
                 bool flag5 = Main.tileAlch[inventory[selectedItem].createTile];
                 if (num11 || ((flag3 || flag4) && flag5))
                 {
                     WorldGen.KillTile(tileTargetX, tileTargetY);
                     if (!Main.tile[tileTargetX, tileTargetY].active() && Main.netMode == 1)
                     {
                         NetMessage.SendData(17, -1, -1, null, 0, tileTargetX, tileTargetY);
                     }
                 }
                 else
                 {
                     canPlace = false;
                 }
             }
             else
             {
                 canPlace = false;
             }
         }
         if (!canPlace && inventory[selectedItem].createTile >= 0 && TileID.Sets.Platforms[inventory[selectedItem].createTile])
         {
             for (int k = tileTargetX - 1; k <= tileTargetX + 1; k++)
             {
                 for (int l = tileTargetY - 1; l <= tileTargetY + 1; l++)
                 {
                     if (Main.tile[k, l].active())
                     {
                         canPlace = true;
                         break;
                     }
                 }
             }
         }
         if (inventory[selectedItem].createTile == 3)
         {
             canPlace = WorldGen.IsFitToPlaceFlowerIn(tileTargetX, tileTargetY, 3);
             if (canPlace)
             {
                 WorldGen.KillTile(tileTargetX, tileTargetY);
                 if (Main.netMode == 1 && !Main.tile[tileTargetX, tileTargetY].active())
                 {
                     NetMessage.SendData(17, -1, -1, null, 0, tileTargetX, tileTargetY);
                 }
             }
         }
         return canPlace;
     }
References Tile.active(), Main.bloodMoon, TileID.Sets.BreakableWhenPlacing, Main.cloudAlpha, Main.dayTime, Tile.frameX, Tile.halfBrick(), TileID.Sets.IsBeam, WorldGen.IsFitToPlaceFlowerIn(), WorldGen.IsHarvestableHerbWithSeed(), WorldGen.IsTreeType(), WorldGen.KillTile(), Main.moonPhase, Tile.nactive(), Main.netMode, TileID.Sets.Platforms, Main.raining, NetMessage.SendData(), Tile.slope(), WorldGen.SlopeTile(), WorldGen.SolidTileNoAttach(), Main.tile, Main.tileAlch, Main.tileCut, Main.tileNoAttach, Main.tileRope, Main.tileSolid, Main.tileSolidTop, Main.tileTable, Main.time, Tile.type, and Tile.wall.