Terraria: Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids
PlaceThing_Tiles_PlaceIt_UnslopeForSolids()
void Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids () inline private
     {
         if (!Main.tileSolid[inventory[selectedItem].createTile] || (inventory[selectedItem].createTile >= 0 && TileID.Sets.Platforms[inventory[selectedItem].createTile]))
         {
             return;
         }
         int num = tileTargetX;
         int num2 = tileTargetY + 1;
         if (Main.tile[num, num2] != null && !TileID.Sets.Platforms[Main.tile[num, num2].type] && (Main.tile[num, num2].topSlope() || Main.tile[num, num2].halfBrick()))
         {
             WorldGen.SlopeTile(num, num2);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 14, num, num2);
             }
         }
         num = tileTargetX;
         num2 = tileTargetY - 1;
         if (Main.tile[num, num2] != null && !TileID.Sets.Platforms[Main.tile[num, num2].type] && Main.tile[num, num2].bottomSlope())
         {
             WorldGen.SlopeTile(num, num2);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 14, num, num2);
             }
         }
     }
References Tile.bottomSlope(), Tile.halfBrick(), Main.netMode, TileID.Sets.Platforms, NetMessage.SendData(), WorldGen.SlopeTile(), Main.tile, Main.tileSolid, Tile.topSlope(), and Tile.type.