Terraria: Player.ItemCheck_Shoot
ItemCheck_Shoot()
void Player.ItemCheck_Shoot (int i, Item sItem, int weaponDamage) inline private
     {
         int projToShoot = sItem.shoot;
         float speed = sItem.shootSpeed;
         int damage = sItem.damage;
         if (sItem.melee && !ProjectileID.Sets.NoMeleeSpeedVelocityScaling[projToShoot])
         {
             speed /= meleeSpeed;
         }
         bool canShoot = false;
         int Damage = weaponDamage;
         float KnockBack = sItem.knockBack;
         int usedAmmoItemId = 0;
         if (sItem.useAmmo > 0)
         {
             PickAmmo(sItem, ref projToShoot, ref speed, ref canShoot, ref Damage, ref KnockBack, out usedAmmoItemId, ItemID.Sets.gunProj[sItem.type]);
         }
         else
         {
             canShoot = true;
         }
         if (ItemID.Sets.gunProj[sItem.type])
         {
             KnockBack = sItem.knockBack;
             Damage = weaponDamage;
             speed = sItem.shootSpeed;
         }
         if (sItem.IsACoin)
         {
             canShoot = false;
         }
         if (sItem.type == 1254 && projToShoot == 14)
         {
             projToShoot = 242;
         }
         if (sItem.type == 1255 && projToShoot == 14)
         {
             projToShoot = 242;
         }
         if (sItem.type == 1265 && projToShoot == 14)
         {
             projToShoot = 242;
         }
         if (sItem.type == 3542)
         {
             if (Main.rand.Next(100) < 20)
             {
                 projToShoot++;
                 Damage *= 3;
             }
             else
             {
                 speed -= 1f;
             }
         }
         if (sItem.type == 1928)
         {
             Damage = (int)((float)Damage * 1f);
         }
         if (sItem.type == 3063)
         {
             Damage = (int)((float)Damage * 1.25f);
         }
         if (sItem.type == 1306)
         {
             Damage = (int)((double)Damage * 0.67);
         }
         if (sItem.type == 1227)
         {
             Damage = (int)((double)Damage * 0.7);
         }
         if (!canShoot)
         {
             return;
         }
         KnockBack = GetWeaponKnockback(sItem, KnockBack);
         IEntitySource projectileSource_Item_WithPotentialAmmo = GetProjectileSource_Item_WithPotentialAmmo(sItem, usedAmmoItemId);
         if (projToShoot == 228)
         {
             KnockBack = 0f;
         }
         if (projToShoot == 1 && sItem.type == 120)
         {
             projToShoot = 2;
         }
         if (sItem.type == 682)
         {
             projToShoot = 117;
         }
         if (sItem.type == 725)
         {
             projToShoot = 120;
         }
         if (sItem.type == 2796)
         {
             projToShoot = 442;
         }
         if (sItem.type == 2223)
         {
             projToShoot = 357;
         }
         if (sItem.type == 5117)
         {
             projToShoot = 968;
         }
         if (sItem.fishingPole > 0 && overrideFishingBobber > -1)
         {
             projToShoot = overrideFishingBobber;
         }
         ApplyItemTime(sItem);
         Vector2 pointPoisition = RotatedRelativePoint(MountedCenter);
         bool flag = true;
         int type = sItem.type;
         if (type == 723 || type == 3611)
         {
             flag = false;
         }
         Vector2 value = Vector2.UnitX.RotatedBy(fullRotation);
         Vector2 vector = Main.MouseWorld - pointPoisition;
         Vector2 v = itemRotation.ToRotationVector2() * direction;
         if (sItem.type == 3852 && !ItemAnimationJustStarted)
         {
             vector = (v.ToRotation() + fullRotation).ToRotationVector2();
         }
         if (vector != Vector2.Zero)
         {
             vector.Normalize();
         }
         float num = Vector2.Dot(value, vector);
         if (flag)
         {
             if (num > 0f)
             {
                 ChangeDir(1);
             }
             else
             {
                 ChangeDir(-1);
             }
         }
         if (sItem.type == 3094 || sItem.type == 3378 || sItem.type == 3543)
         {
             pointPoisition.Y = position.Y + (float)(height / 3);
         }
         if (sItem.type == 5117)
         {
             pointPoisition.Y = position.Y + (float)(height / 3);
         }
         if (sItem.type == 517)
         {
             pointPoisition.X += (float)Main.rand.Next(-3, 4) * 3.5f;
             pointPoisition.Y += (float)Main.rand.Next(-3, 4) * 3.5f;
         }
         if (sItem.type == 2611)
         {
             Vector2 vector2 = vector;
             if (vector2 != Vector2.Zero)
             {
                 vector2.Normalize();
             }
             pointPoisition += vector2;
         }
         if (sItem.type == 3827)
         {
             pointPoisition += vector.SafeNormalize(Vector2.Zero).RotatedBy((float)direction * (-(float)Math.PI / 2f)) * 24f;
         }
         if (projToShoot == 9)
         {
             pointPoisition = new Vector2(position.X + (float)width * 0.5f + (float)(Main.rand.Next(201) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - position.X), MountedCenter.Y - 600f);
             KnockBack = 0f;
             Damage = (int)((float)Damage * 1.5f);
         }
         if (sItem.type == 986 || sItem.type == 281)
         {
             pointPoisition.X += 6 * direction;
             pointPoisition.Y -= 6f * gravDir;
         }
         if (sItem.type == 3007)
         {
             pointPoisition.X -= 4 * direction;
             pointPoisition.Y -= 2f * gravDir;
         }
         float num2 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
         float num3 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
         if (sItem.type == 3852 && !ItemAnimationJustStarted)
         {
             Vector2 vector3 = vector;
             num2 = vector3.X;
             num3 = vector3.Y;
         }
         if (gravDir == -1f)
         {
             num3 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - pointPoisition.Y;
         }
         float num4 = (float)Math.Sqrt(num2 * num2 + num3 * num3);
         float num5 = num4;
         if ((float.IsNaN(num2) && float.IsNaN(num3)) || (num2 == 0f && num3 == 0f))
         {
             num2 = direction;
             num3 = 0f;
             num4 = speed;
         }
         else
         {
             num4 = speed / num4;
         }
         if (sItem.type == 1929 || sItem.type == 2270)
         {
             num2 += (float)Main.rand.Next(-50, 51) * 0.03f / num4;
             num3 += (float)Main.rand.Next(-50, 51) * 0.03f / num4;
         }
         num2 *= num4;
         num3 *= num4;
         if (projToShoot == 250)
         {
             for (int j = 0; j < 1000; j++)
             {
                 if (Main.projectile[j].active && Main.projectile[j].owner == whoAmI && (Main.projectile[j].type == 250 || Main.projectile[j].type == 251))
                 {
                     Main.projectile[j].Kill();
                 }
             }
         }
         if (projToShoot == 12 && Collision.CanHitLine(base.Center, 0, 0, pointPoisition + new Vector2(num2, num3) * 4f, 0, 0))
         {
             pointPoisition += new Vector2(num2, num3) * 3f;
         }
         if (projToShoot == 728 && !Collision.CanHitLine(base.Center, 0, 0, pointPoisition + new Vector2(num2, num3) * 2f, 0, 0))
         {
             Vector2 vector4 = new Vector2(num2, num3) * 0.25f;
             pointPoisition = base.Center - vector4;
         }
         if (projToShoot == 85)
         {
             pointPoisition += new Vector2(0f, -6f * (float)direction * Directions.Y).RotatedBy(vector.ToRotation());
             if (Collision.CanHitLine(pointPoisition, 0, 0, pointPoisition + new Vector2(num2, num3) * 5f, 0, 0))
             {
                 pointPoisition += new Vector2(num2, num3) * 4f;
             }
         }
         if (projToShoot == 802 || projToShoot == 842)
         {
             Vector2 v2 = new Vector2(num2, num3);
             float num6 = (float)Math.PI / 4f;
             Vector2 vector5 = v2.SafeNormalize(Vector2.Zero).RotatedBy(num6 * (Main.rand.NextFloat() - 0.5f)) * (v2.Length() - Main.rand.NextFloatDirection() * 0.7f);
             num2 = vector5.X;
             num3 = vector5.Y;
         }
         if (sItem.useStyle == 5)
         {
             if (sItem.type == 3029)
             {
                 Vector2 vector6 = new Vector2(num2, num3);
                 vector6.X = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                 vector6.Y = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y - 1000f;
                 itemRotation = (float)Math.Atan2(vector6.Y * (float)direction, vector6.X * (float)direction);
                 NetMessage.SendData(13, -1, -1, null, whoAmI);
                 NetMessage.SendData(41, -1, -1, null, whoAmI);
             }
             else if (sItem.type == 4381)
             {
                 Vector2 vector7 = new Vector2(num2, num3);
                 vector7.X = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                 vector7.Y = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y - 1000f;
                 itemRotation = (float)Math.Atan2(vector7.Y * (float)direction, vector7.X * (float)direction);
                 NetMessage.SendData(13, -1, -1, null, whoAmI);
                 NetMessage.SendData(41, -1, -1, null, whoAmI);
             }
             else if (sItem.type == 3779)
             {
                 itemRotation = 0f;
                 NetMessage.SendData(13, -1, -1, null, whoAmI);
                 NetMessage.SendData(41, -1, -1, null, whoAmI);
             }
             else
             {
                 itemRotation = (float)Math.Atan2(num3 * (float)direction, num2 * (float)direction) - fullRotation;
                 NetMessage.SendData(13, -1, -1, null, whoAmI);
                 NetMessage.SendData(41, -1, -1, null, whoAmI);
             }
         }
         if (sItem.useStyle == 13)
         {
             itemRotation = (float)Math.Atan2(num3 * (float)direction, num2 * (float)direction) - fullRotation;
             NetMessage.SendData(13, -1, -1, null, whoAmI);
             NetMessage.SendData(41, -1, -1, null, whoAmI);
         }
         if (projToShoot == 17)
         {
             pointPoisition.X = (float)Main.mouseX + Main.screenPosition.X;
             pointPoisition.Y = (float)Main.mouseY + Main.screenPosition.Y;
             if (gravDir == -1f)
             {
                 pointPoisition.Y = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY;
             }
             LimitPointToPlayerReachableArea(ref pointPoisition);
         }
         if (projToShoot == 76)
         {
             projToShoot += Main.rand.Next(3);
             float num7 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
             num5 /= num7 / 2f;
             if (num5 > 1f)
             {
                 num5 = 1f;
             }
             float num8 = num2 + (float)Main.rand.Next(-40, 41) * 0.01f;
             float num9 = num3 + (float)Main.rand.Next(-40, 41) * 0.01f;
             num8 *= num5 + 0.25f;
             num9 *= num5 + 0.25f;
             int num10 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num8, num9, projToShoot, Damage, KnockBack, i);
             Main.projectile[num10].ai[1] = 1f;
             num5 = num5 * 2f - 1f;
             if (num5 < -1f)
             {
                 num5 = -1f;
             }
             if (num5 > 1f)
             {
                 num5 = 1f;
             }
             num5 = (float)Math.Round(num5 * (float)musicNotes);
             num5 /= (float)musicNotes;
             Main.projectile[num10].ai[0] = num5;
             NetMessage.SendData(27, -1, -1, null, num10);
         }
         else if (sItem.type == 3029)
         {
             int num11 = 3;
             if (projToShoot == 91 || projToShoot == 4 || projToShoot == 5 || projToShoot == 41)
             {
                 if (Main.rand.Next(3) == 0)
                 {
                     num11--;
                 }
             }
             else if (Main.rand.Next(3) == 0)
             {
                 num11++;
             }
             for (int k = 0; k < num11; k++)
             {
                 pointPoisition = new Vector2(position.X + (float)width * 0.5f + (float)(Main.rand.Next(201) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - position.X), MountedCenter.Y - 600f);
                 pointPoisition.X = (pointPoisition.X * 10f + base.Center.X) / 11f + (float)Main.rand.Next(-100, 101);
                 pointPoisition.Y -= 150 * k;
                 num2 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                 num3 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
                 if (num3 < 0f)
                 {
                     num3 *= -1f;
                 }
                 if (num3 < 20f)
                 {
                     num3 = 20f;
                 }
                 num4 = (float)Math.Sqrt(num2 * num2 + num3 * num3);
                 num4 = speed / num4;
                 num2 *= num4;
                 num3 *= num4;
                 float num12 = num2 + (float)Main.rand.Next(-40, 41) * 0.03f;
                 float speedY = num3 + (float)Main.rand.Next(-40, 41) * 0.03f;
                 num12 *= (float)Main.rand.Next(75, 150) * 0.01f;
                 pointPoisition.X += Main.rand.Next(-50, 51);
                 int num13 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num12, speedY, projToShoot, Damage, KnockBack, i);
                 Main.projectile[num13].noDropItem = true;
             }
         }
         else if (sItem.type == 4381)
         {
             int num14 = Main.rand.Next(1, 3);
             if (Main.rand.Next(3) == 0)
             {
                 num14++;
             }
             for (int l = 0; l < num14; l++)
             {
                 pointPoisition = new Vector2(position.X + (float)width * 0.5f + (float)(Main.rand.Next(61) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - position.X), MountedCenter.Y - 600f);
                 pointPoisition.X = (pointPoisition.X * 10f + base.Center.X) / 11f + (float)Main.rand.Next(-30, 31);
                 pointPoisition.Y -= 150f * Main.rand.NextFloat();
                 num2 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                 num3 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
                 if (num3 < 0f)
                 {
                     num3 *= -1f;
                 }
                 if (num3 < 20f)
                 {
                     num3 = 20f;
                 }
                 num4 = (float)Math.Sqrt(num2 * num2 + num3 * num3);
                 num4 = speed / num4;
                 num2 *= num4;
                 num3 *= num4;
                 float num15 = num2 + (float)Main.rand.Next(-20, 21) * 0.03f;
                 float speedY2 = num3 + (float)Main.rand.Next(-40, 41) * 0.03f;
                 num15 *= (float)Main.rand.Next(55, 80) * 0.01f;
                 pointPoisition.X += Main.rand.Next(-50, 51);
                 int num16 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num15, speedY2, projToShoot, Damage, KnockBack, i);
                 Main.projectile[num16].noDropItem = true;
             }
         }
         else if (sItem.type == 98 || sItem.type == 533)
         {
             float speedX = num2 + (float)Main.rand.Next(-40, 41) * 0.01f;
             float speedY3 = num3 + (float)Main.rand.Next(-40, 41) * 0.01f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX, speedY3, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 1319)
         {
             float speedX2 = num2 + (float)Main.rand.Next(-40, 41) * 0.02f;
             float speedY4 = num3 + (float)Main.rand.Next(-40, 41) * 0.02f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX2, speedY4, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 3107)
         {
             float speedX3 = num2 + (float)Main.rand.Next(-40, 41) * 0.02f;
             float speedY5 = num3 + (float)Main.rand.Next(-40, 41) * 0.02f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX3, speedY5, projToShoot, Damage, KnockBack, i);
         }
         else if (ProjectileID.Sets.IsAGolfBall[projToShoot])
         {
             Vector2 vector8 = new Vector2((float)Main.mouseX + Main.screenPosition.X, (float)Main.mouseY + Main.screenPosition.Y);
             Vector2 vector9 = vector8 - base.Center;
             bool flag2 = false;
             if (vector9.Length() < 100f)
             {
                 flag2 = TryPlacingAGolfBallNearANearbyTee(vector8);
             }
             if (!flag2)
             {
                 if (vector9.Length() > 100f || !Collision.CanHit(base.Center, 1, 1, vector8, 1, 1))
                 {
                     Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, Damage, KnockBack, i);
                 }
                 else
                 {
                     Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector8.X, vector8.Y, 0f, 0f, projToShoot, Damage, KnockBack, i);
                 }
             }
         }
         else if (sItem.type == 3053)
         {
             bool flag3 = false;
             if (itemAnimation <= sItem.useTime + 1)
             {
                 flag3 = true;
             }
             Vector2 vector10 = new Vector2(num2, num3);
             vector10.Normalize();
             vector10 *= 4f;
             if (!flag3)
             {
                 Vector2 vector11 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                 vector11.Normalize();
                 vector10 += vector11;
             }
             vector10.Normalize();
             vector10 *= sItem.shootSpeed;
             float num17 = (float)Main.rand.Next(10, 80) * 0.001f;
             if (Main.rand.Next(2) == 0)
             {
                 num17 *= -1f;
             }
             float num18 = (float)Main.rand.Next(10, 80) * 0.001f;
             if (Main.rand.Next(2) == 0)
             {
                 num18 *= -1f;
             }
             if (flag3)
             {
                 num18 = (num17 = 0f);
             }
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector10.X, vector10.Y, projToShoot, Damage, KnockBack, i, num18, num17);
         }
         else if (sItem.type == 3019)
         {
             Vector2 vector12 = new Vector2(num2, num3);
             float num19 = vector12.Length();
             vector12.X += (float)Main.rand.Next(-100, 101) * 0.01f * num19 * 0.15f;
             vector12.Y += (float)Main.rand.Next(-100, 101) * 0.01f * num19 * 0.15f;
             float num20 = num2 + (float)Main.rand.Next(-40, 41) * 0.03f;
             float num21 = num3 + (float)Main.rand.Next(-40, 41) * 0.03f;
             vector12.Normalize();
             vector12 *= num19;
             num20 *= (float)Main.rand.Next(50, 150) * 0.01f;
             num21 *= (float)Main.rand.Next(50, 150) * 0.01f;
             Vector2 vector13 = new Vector2(num20, num21);
             vector13.X += (float)Main.rand.Next(-100, 101) * 0.025f;
             vector13.Y += (float)Main.rand.Next(-100, 101) * 0.025f;
             vector13.Normalize();
             vector13 *= num19;
             num20 = vector13.X;
             num21 = vector13.Y;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num20, num21, projToShoot, Damage, KnockBack, i, vector12.X, vector12.Y);
         }
         else if (sItem.type == 2797)
         {
             Vector2 vector14 = Vector2.Normalize(new Vector2(num2, num3)) * 40f * sItem.scale;
             if (Collision.CanHit(pointPoisition, 0, 0, pointPoisition + vector14, 0, 0))
             {
                 pointPoisition += vector14;
             }
             float ai = new Vector2(num2, num3).ToRotation();
             float num22 = (float)Math.PI * 2f / 3f;
             int num23 = Main.rand.Next(4, 5);
             if (Main.rand.Next(4) == 0)
             {
                 num23++;
             }
             for (int m = 0; m < num23; m++)
             {
                 float num24 = (float)Main.rand.NextDouble() * 0.2f + 0.05f;
                 Vector2 vector15 = new Vector2(num2, num3).RotatedBy(num22 * (float)Main.rand.NextDouble() - num22 / 2f) * num24;
                 int num25 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector15.X, vector15.Y, 444, Damage, KnockBack, i, ai);
                 Main.projectile[num25].localAI[0] = projToShoot;
                 Main.projectile[num25].localAI[1] = speed;
             }
         }
         else if (sItem.type == 2270)
         {
             float num26 = num2 + (float)Main.rand.Next(-40, 41) * 0.05f;
             float num27 = num3 + (float)Main.rand.Next(-40, 41) * 0.05f;
             if (Main.rand.Next(3) == 0)
             {
                 num26 *= 1f + (float)Main.rand.Next(-30, 31) * 0.02f;
                 num27 *= 1f + (float)Main.rand.Next(-30, 31) * 0.02f;
             }
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num26, num27, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 5117)
         {
             float speedX4 = num2 + (float)Main.rand.Next(-15, 16) * 0.075f;
             float speedY6 = num3 + (float)Main.rand.Next(-15, 16) * 0.075f;
             int num28 = Main.rand.Next(Main.projFrames[sItem.shoot]);
             int damage2 = Damage;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX4, speedY6, projToShoot, damage2, KnockBack, i, 0f, num28);
         }
         else if (sItem.type == 1930)
         {
             int num29 = 2 + Main.rand.Next(3);
             for (int n = 0; n < num29; n++)
             {
                 float num30 = num2;
                 float num31 = num3;
                 float num32 = 0.025f * (float)n;
                 num30 += (float)Main.rand.Next(-35, 36) * num32;
                 num31 += (float)Main.rand.Next(-35, 36) * num32;
                 num4 = (float)Math.Sqrt(num30 * num30 + num31 * num31);
                 num4 = speed / num4;
                 num30 *= num4;
                 num31 *= num4;
                 float x = pointPoisition.X + num2 * (float)(num29 - n) * 1.75f;
                 float y = pointPoisition.Y + num3 * (float)(num29 - n) * 1.75f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, x, y, num30, num31, projToShoot, Damage, KnockBack, i, Main.rand.Next(0, 10 * (n + 1)));
             }
         }
         else if (sItem.type == 1931)
         {
             int num33 = 2;
             for (int num34 = 0; num34 < num33; num34++)
             {
                 pointPoisition = new Vector2(position.X + (float)width * 0.5f + (float)(Main.rand.Next(201) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - position.X), MountedCenter.Y - 600f);
                 pointPoisition.X = (pointPoisition.X + base.Center.X) / 2f + (float)Main.rand.Next(-200, 201);
                 pointPoisition.Y -= 100 * num34;
                 num2 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                 num3 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
                 if (gravDir == -1f)
                 {
                     num3 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - pointPoisition.Y;
                 }
                 if (num3 < 0f)
                 {
                     num3 *= -1f;
                 }
                 if (num3 < 20f)
                 {
                     num3 = 20f;
                 }
                 num4 = (float)Math.Sqrt(num2 * num2 + num3 * num3);
                 num4 = speed / num4;
                 num2 *= num4;
                 num3 *= num4;
                 float speedX5 = num2 + (float)Main.rand.Next(-40, 41) * 0.02f;
                 float speedY7 = num3 + (float)Main.rand.Next(-40, 41) * 0.02f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX5, speedY7, projToShoot, Damage, KnockBack, i, 0f, Main.rand.Next(5));
             }
         }
         else if (sItem.type == 2750)
         {
             int num35 = 1;
             for (int num36 = 0; num36 < num35; num36++)
             {
                 pointPoisition = new Vector2(position.X + (float)width * 0.5f + (float)(Main.rand.Next(201) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - position.X), MountedCenter.Y - 600f);
                 pointPoisition.X = (pointPoisition.X + base.Center.X) / 2f + (float)Main.rand.Next(-200, 201);
                 pointPoisition.Y -= 100 * num36;
                 num2 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X + (float)Main.rand.Next(-40, 41) * 0.03f;
                 num3 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
                 if (gravDir == -1f)
                 {
                     num3 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - pointPoisition.Y;
                 }
                 if (num3 < 0f)
                 {
                     num3 *= -1f;
                 }
                 if (num3 < 20f)
                 {
                     num3 = 20f;
                 }
                 num4 = (float)Math.Sqrt(num2 * num2 + num3 * num3);
                 num4 = speed / num4;
                 num2 *= num4;
                 num3 *= num4;
                 float num37 = num2;
                 float num38 = num3 + (float)Main.rand.Next(-40, 41) * 0.02f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num37 * 0.75f, num38 * 0.75f, projToShoot + Main.rand.Next(3), Damage, KnockBack, i, 0f, 0.5f + (float)Main.rand.NextDouble() * 0.3f);
             }
         }
         else if (sItem.type == 3570)
         {
             int num39 = 3;
             for (int num40 = 0; num40 < num39; num40++)
             {
                 pointPoisition = new Vector2(position.X + (float)width * 0.5f + (float)(Main.rand.Next(201) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - position.X), MountedCenter.Y - 600f);
                 pointPoisition.X = (pointPoisition.X + base.Center.X) / 2f + (float)Main.rand.Next(-200, 201);
                 pointPoisition.Y -= 100 * num40;
                 num2 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                 num3 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
                 float ai2 = num3 + pointPoisition.Y;
                 if (num3 < 0f)
                 {
                     num3 *= -1f;
                 }
                 if (num3 < 20f)
                 {
                     num3 = 20f;
                 }
                 num4 = (float)Math.Sqrt(num2 * num2 + num3 * num3);
                 num4 = speed / num4;
                 num2 *= num4;
                 num3 *= num4;
                 Vector2 vector16 = new Vector2(num2, num3) / 2f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector16.X, vector16.Y, projToShoot, Damage, KnockBack, i, 0f, ai2);
             }
         }
         else if (sItem.type == 5065)
         {
             Vector2 farthestSpawnPositionOnLine = GetFarthestSpawnPositionOnLine(pointPoisition, num2, num3);
             Vector2 zero = Vector2.Zero;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, farthestSpawnPositionOnLine, zero, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 3065)
         {
             Vector2 vector17 = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY);
             float num41 = vector17.Y;
             if (num41 > base.Center.Y - 200f)
             {
                 num41 = base.Center.Y - 200f;
             }
             for (int num42 = 0; num42 < 3; num42++)
             {
                 pointPoisition = base.Center + new Vector2(-Main.rand.Next(0, 401) * direction, -600f);
                 pointPoisition.Y -= 100 * num42;
                 Vector2 vector18 = vector17 - pointPoisition;
                 if (vector18.Y < 0f)
                 {
                     vector18.Y *= -1f;
                 }
                 if (vector18.Y < 20f)
                 {
                     vector18.Y = 20f;
                 }
                 vector18.Normalize();
                 vector18 *= speed;
                 num2 = vector18.X;
                 num3 = vector18.Y;
                 float speedX6 = num2;
                 float speedY8 = num3 + (float)Main.rand.Next(-40, 41) * 0.02f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX6, speedY8, projToShoot, Damage, KnockBack, i, 0f, num41);
             }
         }
         else if (sItem.type == 2624)
         {
             float num43 = (float)Math.PI / 10f;
             int num44 = 5;
             Vector2 vector19 = new Vector2(num2, num3);
             vector19.Normalize();
             vector19 *= 40f;
             bool flag4 = Collision.CanHit(pointPoisition, 0, 0, pointPoisition + vector19, 0, 0);
             for (int num45 = 0; num45 < num44; num45++)
             {
                 float num46 = (float)num45 - ((float)num44 - 1f) / 2f;
                 Vector2 vector20 = vector19.RotatedBy(num43 * num46);
                 if (!flag4)
                 {
                     vector20 -= vector19;
                 }
                 int num47 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X + vector20.X, pointPoisition.Y + vector20.Y, num2, num3, projToShoot, Damage, KnockBack, i);
                 Main.projectile[num47].noDropItem = true;
             }
         }
         else if (sItem.type == 1929)
         {
             float speedX7 = num2 + (float)Main.rand.Next(-40, 41) * 0.03f;
             float speedY9 = num3 + (float)Main.rand.Next(-40, 41) * 0.03f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX7, speedY9, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 1553)
         {
             float speedX8 = num2 + (float)Main.rand.Next(-40, 41) * 0.005f;
             float speedY10 = num3 + (float)Main.rand.Next(-40, 41) * 0.005f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX8, speedY10, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 518)
         {
             float num48 = num2;
             float num49 = num3;
             num48 += (float)Main.rand.Next(-40, 41) * 0.04f;
             num49 += (float)Main.rand.Next(-40, 41) * 0.04f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num48, num49, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 1265)
         {
             float num50 = num2;
             float num51 = num3;
             num50 += (float)Main.rand.Next(-30, 31) * 0.03f;
             num51 += (float)Main.rand.Next(-30, 31) * 0.03f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num50, num51, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 4262)
         {
             float num52 = 2.6666667f;
             _ = base.Bottom;
             _ = (int)base.Bottom.X / 16;
             int num53 = 4;
             float num54 = Math.Abs((float)Main.mouseX + Main.screenPosition.X - position.X) / 16f;
             if (direction < 0)
             {
                 num54 += 1f;
             }
             num53 = (int)num54;
             if (num53 > 15)
             {
                 num53 = 15;
             }
             Point point = base.Center.ToTileCoordinates();
             int maxDistance = 31;
             for (int num55 = num53; num55 >= 0; num55--)
             {
                 if (Collision.CanHitLine(base.Center, 1, 1, base.Center + new Vector2(16 * num55 * direction, 0f), 1, 1) && WorldUtils.Find(new Point(point.X + direction * num55, point.Y), Searches.Chain(new Searches.Down(maxDistance), new Conditions.MysticSnake()), out var result))
                 {
                     int num56 = result.Y;
                     while (Main.tile[result.X, num56 - 1].active())
                     {
                         num56--;
                         if (Main.tile[result.X, num56 - 1] == null || num56 < 10 || result.Y - num56 > 7)
{
                             num56 = -1;
                             break;
                         }
                     }
                     if (num56 >= 10)
                     {
                         result.Y = num56;
                         for (int num57 = 0; num57 < 1000; num57++)
{
                             Projectile projectile = Main.projectile[num57];
                             if (projectile.active && projectile.owner == whoAmI && projectile.type == projToShoot)
{
                                 if (projectile.ai[1] == 2f)
{
                                     projectile.timeLeft = 4;
                                 }
                                 else
{
                                     projectile.Kill();
                                 }
                             }
                         }
                         Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, result.X * 16 + 8, result.Y * 16 + 8 - 16, 0f, 0f - num52, projToShoot, Damage, KnockBack, i, result.Y * 16 + 8 - 16);
                         break;
                     }
                 }
             }
         }
         else if (sItem.type == 4952)
         {
             Vector2 vector21 = Main.rand.NextVector2Circular(1f, 1f) + Main.rand.NextVector2CircularEdge(3f, 3f);
             if (vector21.Y > 0f)
             {
                 vector21.Y *= -1f;
             }
             float num58 = (float)itemAnimation / (float)itemAnimationMax * 0.66f + miscCounterNormalized;
             pointPoisition = MountedCenter + new Vector2(direction * 15, gravDir * 3f);
             Point point2 = pointPoisition.ToTileCoordinates();
             Tile tile = Main.tile[point2.X, point2.Y];
             if (tile != null && tile.nactive() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type] && !TileID.Sets.Platforms[tile.type])
             {
                 pointPoisition = MountedCenter;
             }
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector21.X, vector21.Y, projToShoot, Damage, KnockBack, i, -1f, num58 % 1f);
         }
         else if (sItem.type == 4953)
         {
             float num59 = (float)Math.PI / 10f;
             int num60 = 5;
             Vector2 vector22 = new Vector2(num2, num3);
             vector22.Normalize();
             vector22 *= 40f;
             bool num61 = Collision.CanHit(pointPoisition, 0, 0, pointPoisition + vector22, 0, 0);
             int num62 = (itemAnimationMax - itemAnimation) / 2;
             int num63 = num62;
             if (direction == 1)
             {
                 num63 = 4 - num62;
             }
             float num64 = (float)num63 - ((float)num60 - 1f) / 2f;
             Vector2 vector23 = vector22.RotatedBy(num59 * num64);
             if (!num61)
             {
                 vector23 -= vector22;
             }
             Vector2 mouseWorld = Main.MouseWorld;
             Vector2 origin = pointPoisition + vector23;
             Vector2 vector24 = origin.DirectionTo(mouseWorld).SafeNormalize(-Vector2.UnitY);
             Vector2 value2 = base.Center.DirectionTo(base.Center + new Vector2(num2, num3)).SafeNormalize(-Vector2.UnitY);
             float lerpValue = Utils.GetLerpValue(100f, 40f, mouseWorld.Distance(base.Center), clamped: true);
             if (lerpValue > 0f)
             {
                 vector24 = Vector2.Lerp(vector24, value2, lerpValue).SafeNormalize(new Vector2(num2, num3).SafeNormalize(-Vector2.UnitY));
             }
             Vector2 v3 = vector24 * speed;
             if (num62 == 2)
             {
                 projToShoot = 932;
                 Damage *= 2;
             }
             if (projToShoot == 932)
             {
                 float ai3 = miscCounterNormalized * 12f % 1f;
                 v3 = v3.SafeNormalize(Vector2.Zero) * (speed * 2f);
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, origin, v3, projToShoot, Damage, KnockBack, i, 0f, ai3);
             }
             else
             {
                 int num65 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, origin, v3, projToShoot, Damage, KnockBack, i);
                 Main.projectile[num65].noDropItem = true;
             }
         }
         else if (sItem.type == 534)
         {
             int num66 = Main.rand.Next(4, 6);
             for (int num67 = 0; num67 < num66; num67++)
             {
                 float num68 = num2;
                 float num69 = num3;
                 num68 += (float)Main.rand.Next(-40, 41) * 0.05f;
                 num69 += (float)Main.rand.Next(-40, 41) * 0.05f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num68, num69, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 4703)
         {
             float num70 = (float)Math.PI / 2f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, Damage, KnockBack, i);
             for (int num71 = 0; num71 < 7; num71++)
             {
                 Vector2 v4 = new Vector2(num2, num3);
                 float num72 = v4.Length();
                 v4 += v4.SafeNormalize(Vector2.Zero).RotatedBy(num70 * Main.rand.NextFloat()) * Main.rand.NextFloatDirection() * 5f;
                 v4 = v4.SafeNormalize(Vector2.Zero) * num72;
                 float x2 = v4.X;
                 float y2 = v4.Y;
                 x2 += (float)Main.rand.Next(-40, 41) * 0.05f;
                 y2 += (float)Main.rand.Next(-40, 41) * 0.05f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, x2, y2, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 4270)
         {
             Vector2 pointPoisition2 = Main.MouseWorld;
             LimitPointToPlayerReachableArea(ref pointPoisition2);
             Vector2 vector25 = pointPoisition2 + Main.rand.NextVector2Circular(8f, 8f);
             Vector2 vector26 = FindSharpTearsSpot(vector25).ToWorldCoordinates(Main.rand.Next(17), Main.rand.Next(17));
             Vector2 vector27 = (vector25 - vector26).SafeNormalize(-Vector2.UnitY) * 16f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector26.X, vector26.Y, vector27.X, vector27.Y, projToShoot, Damage, KnockBack, i, 0f, Main.rand.NextFloat() * 0.5f + 0.6f);
         }
         else if (sItem.type == 4715)
         {
             Vector2 vector28 = Main.MouseWorld;
             List<NPC> validTargets;
             bool sparkleGuitarTarget = GetSparkleGuitarTarget(out validTargets);
             if (sparkleGuitarTarget)
             {
                 NPC nPC = validTargets[Main.rand.Next(validTargets.Count)];
                 vector28 = nPC.Center + nPC.velocity * 20f;
             }
             Vector2 vector29 = vector28 - base.Center;
             if (!sparkleGuitarTarget)
             {
                 vector28 += Main.rand.NextVector2Circular(24f, 24f);
                 if (vector29.Length() > 700f)
                 {
                     vector29 *= 700f / vector29.Length();
                     vector28 = base.Center + vector29;
                 }
             }
             Vector2 vector30 = Main.rand.NextVector2CircularEdge(1f, 1f);
             if (vector30.Y > 0f)
             {
                 vector30 *= -1f;
             }
             if (Math.Abs(vector30.Y) < 0.5f)
             {
                 vector30.Y = (0f - Main.rand.NextFloat()) * 0.5f - 0.5f;
             }
             vector30 *= vector29.Length() * 2f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector30.X, vector30.Y, projToShoot, Damage, KnockBack, i, vector28.X, vector28.Y);
         }
         else if (sItem.type == 4722)
         {
             Vector2 vector31 = Main.MouseWorld;
             List<NPC> validTargets2;
             bool sparkleGuitarTarget2 = GetSparkleGuitarTarget(out validTargets2);
             if (sparkleGuitarTarget2)
             {
                 NPC nPC2 = validTargets2[Main.rand.Next(validTargets2.Count)];
                 vector31 = nPC2.Center + nPC2.velocity * 20f;
             }
             Vector2 vector32 = vector31 - base.Center;
             Vector2 vector33 = Main.rand.NextVector2CircularEdge(1f, 1f);
             float num73 = 1f;
             int num74 = 1;
             for (int num75 = 0; num75 < num74; num75++)
             {
                 if (!sparkleGuitarTarget2)
                 {
                     vector31 += Main.rand.NextVector2Circular(24f, 24f);
                     if (vector32.Length() > 700f)
                     {
                         vector32 *= 700f / vector32.Length();
                         vector31 = base.Center + vector32;
                     }
                     float num76 = Utils.GetLerpValue(0f, 6f, velocity.Length(), clamped: true) * 0.8f;
                     vector33 *= 1f - num76;
                     vector33 += velocity * num76;
                     vector33 = vector33.SafeNormalize(Vector2.UnitX);
                 }
                 float num77 = 60f;
                 float num78 = Main.rand.NextFloatDirection() * (float)Math.PI * (1f / num77) * 0.5f * num73;
                 float num79 = num77 / 2f;
                 float num80 = 12f + Main.rand.NextFloat() * 2f;
                 Vector2 vector34 = vector33 * num80;
                 Vector2 vector35 = new Vector2(0f, 0f);
                 Vector2 vector36 = vector34;
                 for (int num81 = 0; (float)num81 < num79; num81++)
                 {
                     vector35 += vector36;
                     vector36 = vector36.RotatedBy(num78);
                 }
                 Vector2 vector37 = -vector35;
                 Vector2 vector38 = vector31 + vector37;
                 float lerpValue2 = Utils.GetLerpValue(itemAnimationMax, 0f, itemAnimation, clamped: true);
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector38, vector34, projToShoot, Damage, KnockBack, i, num78, lerpValue2);
             }
         }
         else if (sItem.type == 4607)
         {
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot, damage, KnockBack);
         }
         else if (sItem.type == 5069)
         {
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot, damage, KnockBack);
         }
         else if (sItem.type == 5114)
         {
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot, damage, KnockBack);
         }
         else if (sItem.type == 2188)
         {
             int num82 = 4;
             if (Main.rand.Next(3) == 0)
             {
                 num82++;
             }
             if (Main.rand.Next(4) == 0)
             {
                 num82++;
             }
             if (Main.rand.Next(5) == 0)
             {
                 num82++;
             }
             for (int num83 = 0; num83 < num82; num83++)
             {
                 float num84 = num2;
                 float num85 = num3;
                 float num86 = 0.05f * (float)num83;
                 num84 += (float)Main.rand.Next(-35, 36) * num86;
                 num85 += (float)Main.rand.Next(-35, 36) * num86;
                 num4 = (float)Math.Sqrt(num84 * num84 + num85 * num85);
                 num4 = speed / num4;
                 num84 *= num4;
                 num85 *= num4;
                 float x3 = pointPoisition.X;
                 float y3 = pointPoisition.Y;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, x3, y3, num84, num85, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 1308)
         {
             int num87 = 3;
             if (Main.rand.Next(3) == 0)
             {
                 num87++;
             }
             for (int num88 = 0; num88 < num87; num88++)
             {
                 float num89 = num2;
                 float num90 = num3;
                 float num91 = 0.05f * (float)num88;
                 num89 += (float)Main.rand.Next(-35, 36) * num91;
                 num90 += (float)Main.rand.Next(-35, 36) * num91;
                 num4 = (float)Math.Sqrt(num89 * num89 + num90 * num90);
                 num4 = speed / num4;
                 num89 *= num4;
                 num90 *= num4;
                 float x4 = pointPoisition.X;
                 float y4 = pointPoisition.Y;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, x4, y4, num89, num90, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 1258)
         {
             float num92 = num2;
             float num93 = num3;
             num92 += (float)Main.rand.Next(-40, 41) * 0.01f;
             num93 += (float)Main.rand.Next(-40, 41) * 0.01f;
             pointPoisition.X += (float)Main.rand.Next(-40, 41) * 0.05f;
             pointPoisition.Y += (float)Main.rand.Next(-45, 36) * 0.05f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num92, num93, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 964)
         {
             int num94 = Main.rand.Next(3, 5);
             for (int num95 = 0; num95 < num94; num95++)
             {
                 float num96 = num2;
                 float num97 = num3;
                 num96 += (float)Main.rand.Next(-35, 36) * 0.04f;
                 num97 += (float)Main.rand.Next(-35, 36) * 0.04f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num96, num97, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 1569)
         {
             int num98 = 4;
             if (Main.rand.Next(2) == 0)
             {
                 num98++;
             }
             if (Main.rand.Next(4) == 0)
             {
                 num98++;
             }
             if (Main.rand.Next(8) == 0)
             {
                 num98++;
             }
             if (Main.rand.Next(16) == 0)
             {
                 num98++;
             }
             for (int num99 = 0; num99 < num98; num99++)
             {
                 float num100 = num2;
                 float num101 = num3;
                 float num102 = 0.05f * (float)num99;
                 num100 += (float)Main.rand.Next(-35, 36) * num102;
                 num101 += (float)Main.rand.Next(-35, 36) * num102;
                 num4 = (float)Math.Sqrt(num100 * num100 + num101 * num101);
                 num4 = speed / num4;
                 num100 *= num4;
                 num101 *= num4;
                 float x5 = pointPoisition.X;
                 float y5 = pointPoisition.Y;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, x5, y5, num100, num101, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 1572 || sItem.type == 2366 || sItem.type == 3571 || sItem.type == 3569 || sItem.type == 5119)
         {
             bool num103 = sItem.type == 3571 || sItem.type == 3569;
             int num104 = (int)((float)Main.mouseX + Main.screenPosition.X) / 16;
             int num105 = (int)((float)Main.mouseY + Main.screenPosition.Y) / 16;
             if (gravDir == -1f)
             {
                 num105 = (int)(Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY) / 16;
             }
             if (!num103)
             {
                 for (; num105 < Main.maxTilesY - 10 && Main.tile[num104, num105] != null && !WorldGen.SolidTile2(num104, num105) && Main.tile[num104 - 1, num105] != null && !WorldGen.SolidTile2(num104 - 1, num105) && Main.tile[num104 + 1, num105] != null && !WorldGen.SolidTile2(num104 + 1, num105); num105++)
                 {
                 }
                 num105--;
             }
             int num106 = 0;
             switch (sItem.type)
             {
             case 1572:
                 num106 = 60;
                 break;
             case 5119:
                 num106 = 90;
                 break;
             }
             int num107 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, (float)Main.mouseX + Main.screenPosition.X, num105 * 16 - 24, 0f, 15f, projToShoot, Damage, KnockBack, i, num106);
             Main.projectile[num107].originalDamage = damage;
             UpdateMaxTurrets();
         }
         else if (sItem.type == 1244 || sItem.type == 1256)
         {
             int num108 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, Damage, KnockBack, i);
             Main.projectile[num108].ai[0] = (float)Main.mouseX + Main.screenPosition.X;
             Main.projectile[num108].ai[1] = (float)Main.mouseY + Main.screenPosition.Y;
         }
         else if (sItem.type == 1229)
         {
             int num109 = 2;
             if (Main.rand.Next(3) == 0)
             {
                 num109++;
             }
             for (int num110 = 0; num110 < num109; num110++)
             {
                 float num111 = num2;
                 float num112 = num3;
                 if (num110 > 0)
                 {
                     num111 += (float)Main.rand.Next(-35, 36) * 0.04f;
                     num112 += (float)Main.rand.Next(-35, 36) * 0.04f;
                 }
                 if (num110 > 1)
                 {
                     num111 += (float)Main.rand.Next(-35, 36) * 0.04f;
                     num112 += (float)Main.rand.Next(-35, 36) * 0.04f;
                 }
                 if (num110 > 2)
                 {
                     num111 += (float)Main.rand.Next(-35, 36) * 0.04f;
                     num112 += (float)Main.rand.Next(-35, 36) * 0.04f;
                 }
                 int num113 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num111, num112, projToShoot, Damage, KnockBack, i);
                 Main.projectile[num113].noDropItem = true;
             }
         }
         else if (sItem.type == 1121)
         {
             int num114 = Main.rand.Next(1, 4);
             if (Main.rand.Next(6) == 0)
             {
                 num114++;
             }
             if (Main.rand.Next(6) == 0)
             {
                 num114++;
             }
             if (strongBees && Main.rand.Next(3) == 0)
             {
                 num114++;
             }
             for (int num115 = 0; num115 < num114; num115++)
             {
                 float num116 = num2;
                 float num117 = num3;
                 num116 += (float)Main.rand.Next(-35, 36) * 0.02f;
                 num117 += (float)Main.rand.Next(-35, 36) * 0.02f;
                 int num118 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num116, num117, beeType(), beeDamage(Damage), beeKB(KnockBack), i);
                 Main.projectile[num118].magic = true;
             }
         }
         else if (sItem.type == 1155)
         {
             int num119 = Main.rand.Next(2, 5);
             for (int num120 = 0; num120 < num119; num120++)
             {
                 float num121 = num2;
                 float num122 = num3;
                 num121 += (float)Main.rand.Next(-35, 36) * 0.02f;
                 num122 += (float)Main.rand.Next(-35, 36) * 0.02f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num121, num122, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 1801)
         {
             int num123 = Main.rand.Next(2, 4);
             for (int num124 = 0; num124 < num123; num124++)
             {
                 float num125 = num2;
                 float num126 = num3;
                 num125 += (float)Main.rand.Next(-35, 36) * 0.05f;
                 num126 += (float)Main.rand.Next(-35, 36) * 0.05f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num125, num126, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 679)
         {
             for (int num127 = 0; num127 < 6; num127++)
             {
                 float num128 = num2;
                 float num129 = num3;
                 num128 += (float)Main.rand.Next(-40, 41) * 0.05f;
                 num129 += (float)Main.rand.Next(-40, 41) * 0.05f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num128, num129, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 1156)
         {
             for (int num130 = 0; num130 < 3; num130++)
             {
                 float num131 = num2;
                 float num132 = num3;
                 num131 += (float)Main.rand.Next(-40, 41) * 0.05f;
                 num132 += (float)Main.rand.Next(-40, 41) * 0.05f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num131, num132, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 4682)
         {
             for (int num133 = 0; num133 < 3; num133++)
             {
                 float num134 = num2;
                 float num135 = num3;
                 num134 += (float)Main.rand.Next(-20, 21) * 0.1f;
                 num135 += (float)Main.rand.Next(-20, 21) * 0.1f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num134, num135, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 2623)
         {
             for (int num136 = 0; num136 < 3; num136++)
             {
                 float num137 = num2;
                 float num138 = num3;
                 num137 += (float)Main.rand.Next(-40, 41) * 0.1f;
                 num138 += (float)Main.rand.Next(-40, 41) * 0.1f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num137, num138, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 3210)
         {
             Vector2 vector39 = new Vector2(num2, num3);
             vector39.X += (float)Main.rand.Next(-30, 31) * 0.04f;
             vector39.Y += (float)Main.rand.Next(-30, 31) * 0.03f;
             vector39.Normalize();
             vector39 *= (float)Main.rand.Next(70, 91) * 0.1f;
             vector39.X += (float)Main.rand.Next(-30, 31) * 0.04f;
             vector39.Y += (float)Main.rand.Next(-30, 31) * 0.03f;
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector39.X, vector39.Y, projToShoot, Damage, KnockBack, i, Main.rand.Next(20));
         }
         else if (sItem.type == 434)
         {
             float num139 = num2;
             float num140 = num3;
             if (itemAnimation < 5)
             {
                 num139 += (float)Main.rand.Next(-40, 41) * 0.01f;
                 num140 += (float)Main.rand.Next(-40, 41) * 0.01f;
                 num139 *= 1.1f;
                 num140 *= 1.1f;
             }
             else if (itemAnimation < 10)
             {
                 num139 += (float)Main.rand.Next(-20, 21) * 0.01f;
                 num140 += (float)Main.rand.Next(-20, 21) * 0.01f;
                 num139 *= 1.05f;
                 num140 *= 1.05f;
             }
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num139, num140, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 1157)
         {
             projToShoot = Main.rand.Next(191, 195);
             int num141 = SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot, damage, KnockBack);
             Main.projectile[num141].localAI[0] = 30f;
         }
         else if (sItem.type == 1802)
         {
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot, damage, KnockBack);
         }
         else if (sItem.type == 2364 || sItem.type == 2365)
         {
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot, damage, KnockBack);
         }
         else if (sItem.type == 2535)
         {
             num2 = 0f;
             num3 = 0f;
             Vector2 spinningpoint = new Vector2(num2, num3);
             spinningpoint = spinningpoint.RotatedBy(1.5707963705062866);
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot, damage, KnockBack, spinningpoint, spinningpoint);
             spinningpoint = spinningpoint.RotatedBy(-3.1415927410125732);
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot + 1, damage, KnockBack, spinningpoint, spinningpoint);
         }
         else if (sItem.type == 2551)
         {
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot + nextCycledSpiderMinionType, damage, KnockBack);
             nextCycledSpiderMinionType++;
             nextCycledSpiderMinionType %= 3;
         }
         else if (sItem.type == 2584)
         {
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot + Main.rand.Next(3), damage, KnockBack);
         }
         else if (sItem.type == 2621)
         {
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot, damage, KnockBack);
         }
         else if (sItem.type == 2749 || sItem.type == 3249 || sItem.type == 3474 || sItem.type == 4273 || sItem.type == 4281)
         {
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot, damage, KnockBack);
         }
         else if (sItem.type == 3531)
         {
             int num142 = -1;
             int num143 = -1;
             for (int num144 = 0; num144 < 1000; num144++)
             {
                 if (Main.projectile[num144].active && Main.projectile[num144].owner == Main.myPlayer)
                 {
                     if (num142 == -1 && Main.projectile[num144].type == 625)
                     {
                         num142 = num144;
                     }
                     if (num143 == -1 && Main.projectile[num144].type == 628)
                     {
                         num143 = num144;
                     }
                     if (num142 != -1 && num143 != -1)
                     {
                         break;
                     }
                 }
             }
             if (num142 == -1 && num143 == -1)
             {
                 num2 = 0f;
                 num3 = 0f;
                 pointPoisition.X = (float)Main.mouseX + Main.screenPosition.X;
                 pointPoisition.Y = (float)Main.mouseY + Main.screenPosition.Y;
                 int num145 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, Damage, KnockBack, i);
                 int num146 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot + 1, Damage, KnockBack, i, num145);
                 int num147 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot + 2, Damage, KnockBack, i, num146);
                 int num148 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot + 3, Damage, KnockBack, i, num147);
                 Main.projectile[num146].localAI[1] = num147;
                 Main.projectile[num147].localAI[1] = num148;
                 Main.projectile[num145].originalDamage = damage;
                 Main.projectile[num146].originalDamage = damage;
                 Main.projectile[num147].originalDamage = damage;
                 Main.projectile[num148].originalDamage = damage;
             }
             else if (num142 != -1 && num143 != -1)
             {
                 int num149 = (int)Main.projectile[num143].ai[0];
                 int num150 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot + 1, Damage, KnockBack, i, num149);
                 int num151 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot + 2, Damage, KnockBack, i, num150);
                 Main.projectile[num150].localAI[1] = num151;
                 Main.projectile[num150].netUpdate = true;
                 Main.projectile[num150].ai[1] = 1f;
                 Main.projectile[num151].localAI[1] = num143;
                 Main.projectile[num151].netUpdate = true;
                 Main.projectile[num151].ai[1] = 1f;
                 Main.projectile[num143].ai[0] = num151;
                 Main.projectile[num143].netUpdate = true;
                 Main.projectile[num143].ai[1] = 1f;
                 Main.projectile[num150].originalDamage = damage;
                 Main.projectile[num151].originalDamage = damage;
                 Main.projectile[num143].originalDamage = damage;
             }
         }
         else if (sItem.type == 1309 || sItem.type == 4758 || sItem.type == 4269 || sItem.type == 5005)
         {
             SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot, damage, KnockBack);
         }
         else if (sItem.shoot > 0 && (Main.projPet[sItem.shoot] || sItem.shoot == 72 || sItem.shoot == 18 || sItem.shoot == 500 || sItem.shoot == 650) && !sItem.summon)
         {
             for (int num152 = 0; num152 < 1000; num152++)
             {
                 Projectile projectile2 = Main.projectile[num152];
                 if (projectile2.active && projectile2.owner == whoAmI)
                 {
                     if (sItem.shoot == 72 && (projectile2.type == 72 || projectile2.type == 86 || projectile2.type == 87))
                     {
                         projectile2.Kill();
                     }
                     else if (sItem.type == 5131 && (projectile2.type == 881 || projectile2.type == 934))
                     {
                         projectile2.Kill();
                     }
                     else if (sItem.shoot == projectile2.type)
                     {
                         projectile2.Kill();
                     }
                 }
             }
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, 0, 0f, i);
         }
         else if (sItem.type == 3006)
         {
             pointPoisition = GetFarthestSpawnPositionOnLine(pointPoisition, num2, num3);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, 0f, 0f, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 3014)
         {
             Vector2 pointPoisition3 = default(Vector2);
             pointPoisition3.X = Main.MouseWorld.X;
             pointPoisition3.Y = Main.MouseWorld.Y;
             LimitPointToPlayerReachableArea(ref pointPoisition3);
             while (Collision.CanHitLine(position, width, height, pointPoisition, 1, 1))
             {
                 pointPoisition.X += num2;
                 pointPoisition.Y += num3;
                 if ((pointPoisition - pointPoisition3).Length() < 20f + Math.Abs(num2) + Math.Abs(num3))
                 {
                     pointPoisition = pointPoisition3;
                     break;
                 }
             }
             bool flag5 = false;
             int num153 = (int)pointPoisition.Y / 16;
             int num154 = (int)pointPoisition.X / 16;
             int num155;
             for (num155 = num153; num153 < Main.maxTilesY - 10 && num153 - num155 < 30 && !WorldGen.SolidTile(num154, num153) && !TileID.Sets.Platforms[Main.tile[num154, num153].type]; num153++)
             {
             }
             if (!WorldGen.SolidTile(num154, num153) && !TileID.Sets.Platforms[Main.tile[num154, num153].type])
             {
                 flag5 = true;
             }
             float num156 = num153 * 16;
             num153 = num155;
             while (num153 > 10 && num155 - num153 < 30 && !WorldGen.SolidTile(num154, num153))
             {
                 num153--;
             }
             float num157 = num153 * 16 + 16;
             float num158 = num156 - num157;
             int num159 = 15;
             if (num158 > (float)(16 * num159))
             {
                 num158 = 16 * num159;
             }
             num157 = num156 - num158;
             pointPoisition.X = (int)(pointPoisition.X / 16f) * 16;
             if (!flag5)
             {
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, 0f, 0f, projToShoot, Damage, KnockBack, i, num157, num158);
             }
         }
         else if (sItem.type == 3384)
         {
             int num160 = ((altFunctionUse == 2) ? 1 : 0);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, Damage, KnockBack, i, 0f, num160);
         }
         else if (sItem.type == 3473)
         {
             float ai4 = (Main.rand.NextFloat() - 0.5f) * ((float)Math.PI / 4f);
             Vector2 vector40 = new Vector2(num2, num3);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector40.X, vector40.Y, projToShoot, Damage, KnockBack, i, 0f, ai4);
         }
         else if (sItem.type == 4956)
         {
             int num161 = (itemAnimationMax - itemAnimation) / itemTime;
             Vector2 vector41 = new Vector2(num2, num3);
             int num162 = FinalFractalHelper.GetRandomProfileIndex();
             if (num161 == 0)
             {
                 num162 = 4956;
             }
             Vector2 pointPoisition4 = Main.MouseWorld;
             LimitPointToPlayerReachableArea(ref pointPoisition4);
             Vector2 vector42 = pointPoisition4 - MountedCenter;
             if (num161 == 1 || num161 == 2)
             {
                 int npcTargetIndex;
                 bool zenithTarget = GetZenithTarget(pointPoisition4, 400f, out npcTargetIndex);
                 if (zenithTarget)
                 {
                     vector42 = Main.npc[npcTargetIndex].Center - MountedCenter;
                 }
                 bool flag6 = num161 == 2;
                 if (num161 == 1 && !zenithTarget)
                 {
                     flag6 = true;
                 }
                 if (flag6)
                 {
                     vector42 += Main.rand.NextVector2Circular(150f, 150f);
                 }
             }
             vector41 = vector42 / 2f;
             float ai5 = Main.rand.Next(-100, 101);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector41, projToShoot, Damage, KnockBack, i, ai5, num162);
         }
         else if (sItem.type == 3836)
         {
             float ai6 = Main.rand.NextFloat() * speed * 0.75f * (float)direction;
             Projectile.NewProjectile(velocity: new Vector2(num2, num3), spawnSource: projectileSource_Item_WithPotentialAmmo, position: pointPoisition, Type: projToShoot, Damage: Damage, KnockBack: KnockBack, Owner: i, ai0: ai6);
         }
         else if (sItem.type == 3858)
         {
             bool num163 = altFunctionUse == 2;
             Vector2 vector43 = new Vector2(num2, num3);
             if (num163)
             {
                 vector43 *= 1.5f;
                 float ai7 = (0.3f + 0.7f * Main.rand.NextFloat()) * speed * 1.75f * (float)direction;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector43, 708, (int)((float)Damage * 0.5f), KnockBack + 4f, i, ai7);
             }
             else
             {
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector43, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 3859)
         {
             Vector2 vector44 = new Vector2(num2, num3);
             projToShoot = 710;
             vector44 *= 0.8f;
             Vector2 vector45 = vector44.SafeNormalize(-Vector2.UnitY);
             float num164 = (float)Math.PI / 180f * (float)(-direction);
             for (float num165 = -2.5f; num165 < 3f; num165 += 1f)
             {
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, (vector44 + vector45 * num165 * 0.5f).RotatedBy(num165 * num164), projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 3870)
         {
             Vector2 vector46 = Vector2.Normalize(new Vector2(num2, num3)) * 40f * sItem.scale;
             if (Collision.CanHit(pointPoisition, 0, 0, pointPoisition + vector46, 0, 0))
             {
                 pointPoisition += vector46;
             }
             Vector2 vector47 = new Vector2(num2, num3);
             vector47 *= 0.8f;
             Vector2 vector48 = vector47.SafeNormalize(-Vector2.UnitY);
             float num166 = (float)Math.PI / 180f * (float)(-direction);
             for (int num167 = 0; num167 <= 2; num167++)
             {
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, (vector47 + vector48 * num167 * 1f).RotatedBy((float)num167 * num166), projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 3542)
         {
             float num168 = (Main.rand.NextFloat() - 0.5f) * ((float)Math.PI / 4f) * 0.7f;
             for (int num169 = 0; num169 < 10; num169++)
             {
                 if (Collision.CanHit(pointPoisition, 0, 0, pointPoisition + new Vector2(num2, num3).RotatedBy(num168) * 100f, 0, 0))
                 {
                     break;
                 }
                 num168 = (Main.rand.NextFloat() - 0.5f) * ((float)Math.PI / 4f) * 0.7f;
             }
             Vector2 vector49 = new Vector2(num2, num3).RotatedBy(num168) * (0.95f + Main.rand.NextFloat() * 0.3f);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector49.X, vector49.Y, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 3779)
         {
             float num170 = Main.rand.NextFloat() * ((float)Math.PI * 2f);
             for (int num171 = 0; num171 < 10; num171++)
             {
                 if (Collision.CanHit(pointPoisition, 0, 0, pointPoisition + new Vector2(num2, num3).RotatedBy(num170) * 100f, 0, 0))
                 {
                     break;
                 }
                 num170 = Main.rand.NextFloat() * ((float)Math.PI * 2f);
             }
             Vector2 vector50 = new Vector2(num2, num3).RotatedBy(num170) * (0.95f + Main.rand.NextFloat() * 0.3f);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition + vector50 * 30f, Vector2.Zero, projToShoot, Damage, KnockBack, i, -2f);
         }
         else if (sItem.type == 3787)
         {
             float f = Main.rand.NextFloat() * ((float)Math.PI * 2f);
             float value3 = 20f;
             float value4 = 60f;
             Vector2 vector51 = pointPoisition + f.ToRotationVector2() * MathHelper.Lerp(value3, value4, Main.rand.NextFloat());
             for (int num172 = 0; num172 < 50; num172++)
             {
                 vector51 = pointPoisition + f.ToRotationVector2() * MathHelper.Lerp(value3, value4, Main.rand.NextFloat());
                 if (Collision.CanHit(pointPoisition, 0, 0, vector51 + (vector51 - pointPoisition).SafeNormalize(Vector2.UnitX) * 8f, 0, 0))
                 {
                     break;
                 }
                 f = Main.rand.NextFloat() * ((float)Math.PI * 2f);
             }
             Vector2 v5 = Main.MouseWorld - vector51;
             Vector2 vector52 = new Vector2(num2, num3).SafeNormalize(Vector2.UnitY) * speed;
             v5 = v5.SafeNormalize(vector52) * speed;
             v5 = Vector2.Lerp(v5, vector52, 0.25f);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector51, v5, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 3788)
         {
             Vector2 vector53 = new Vector2(num2, num3);
             float num173 = (float)Math.PI / 4f;
             for (int num174 = 0; num174 < 2; num174++)
             {
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector53 + vector53.SafeNormalize(Vector2.Zero).RotatedBy(num173 * (Main.rand.NextFloat() * 0.5f + 0.5f)) * Main.rand.NextFloatDirection() * 2f, projToShoot, Damage, KnockBack, i);
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector53 + vector53.SafeNormalize(Vector2.Zero).RotatedBy((0f - num173) * (Main.rand.NextFloat() * 0.5f + 0.5f)) * Main.rand.NextFloatDirection() * 2f, projToShoot, Damage, KnockBack, i);
             }
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector53.SafeNormalize(Vector2.UnitX * direction) * (speed * 1.3f), 661, Damage * 2, KnockBack, i);
         }
         else if (sItem.type == 4463 || sItem.type == 486)
         {
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, new Vector2(num2, num3), projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 46)
         {
             Vector2 vector54 = new Vector2(direction, gravDir * 4f).SafeNormalize(Vector2.UnitY).RotatedBy((float)Math.PI * 2f * Main.rand.NextFloatDirection() * 0.05f);
             Vector2 searchCenter = MountedCenter + new Vector2(70f, -40f) * Directions + vector54 * -10f;
             if (GetZenithTarget(searchCenter, 50f, out var npcTargetIndex2))
             {
                 NPC nPC3 = Main.npc[npcTargetIndex2];
                 searchCenter = nPC3.Center + Main.rand.NextVector2Circular(nPC3.width / 2, nPC3.height / 2);
             }
             else
             {
                 searchCenter += Main.rand.NextVector2Circular(20f, 20f);
             }
             float ai8 = 1f;
             if (Main.rand.Next(100) < meleeCrit)
             {
                 ai8 = 2f;
                 Damage *= 2;
             }
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, searchCenter, vector54 * 0.001f, projToShoot, (int)((double)Damage * 0.5), KnockBack, i, ai8);
             NetMessage.SendData(13, -1, -1, null, whoAmI);
         }
         else if (sItem.type == 273)
         {
             float adjustedItemScale = GetAdjustedItemScale(sItem);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(direction, 0f), projToShoot, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(num2, num3), projToShoot, Damage, KnockBack, i, (float)direction * gravDir * 0.1f, 30f, adjustedItemScale);
             NetMessage.SendData(13, -1, -1, null, whoAmI);
         }
         else if (sItem.type == 368)
         {
             float adjustedItemScale2 = GetAdjustedItemScale(sItem);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(direction, 0f), projToShoot, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale2);
             NetMessage.SendData(13, -1, -1, null, whoAmI);
         }
         else if (sItem.type == 1826)
         {
             float adjustedItemScale3 = GetAdjustedItemScale(sItem);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(direction, 0f), projToShoot, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale3);
             NetMessage.SendData(13, -1, -1, null, whoAmI);
         }
         else if (sItem.type == 675)
         {
             float adjustedItemScale4 = GetAdjustedItemScale(sItem);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(direction, 0f), 972, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale4);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(num2, num3), projToShoot, Damage / 2, KnockBack, i, (float)direction * gravDir, 32f, adjustedItemScale4);
             NetMessage.SendData(13, -1, -1, null, whoAmI);
         }
         else if (sItem.type == 674)
         {
             float adjustedItemScale5 = GetAdjustedItemScale(sItem);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(direction, 0f), projToShoot, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale5);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(direction, 0f), 982, 0, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale5);
             NetMessage.SendData(13, -1, -1, null, whoAmI);
         }
         else if (sItem.type == 757)
         {
             float adjustedItemScale6 = GetAdjustedItemScale(sItem);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(direction, 0f), 984, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale6);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(num2, num3) * 5f, projToShoot, Damage, KnockBack, i, (float)direction * gravDir, 18f, adjustedItemScale6);
             NetMessage.SendData(13, -1, -1, null, whoAmI);
         }
         else if (sItem.type == 190)
         {
             Vector2 vector55 = MountedCenter + new Vector2(70f, -40f) * Directions;
             int npcTargetIndex3;
             bool zenithTarget2 = GetZenithTarget(vector55, 150f, out npcTargetIndex3);
             if (zenithTarget2)
             {
                 NPC nPC4 = Main.npc[npcTargetIndex3];
                 vector55 = Main.rand.NextVector2FromRectangle(nPC4.Hitbox);
             }
             else
             {
                 vector55 += Main.rand.NextVector2Circular(20f, 20f);
             }
             Vector2 vector56 = base.Center + new Vector2(Main.rand.NextFloatDirection() * (float)width / 2f, height / 2) * Directions;
             Vector2 v6 = vector55 - vector56;
             float num175 = ((float)Math.PI + (float)Math.PI * 2f * Main.rand.NextFloat() * 1.5f) * ((float)(-direction) * gravDir);
             int num176 = 60;
             float num177 = num175 / (float)num176;
             float num178 = 16f;
             float num179 = v6.Length();
             if (Math.Abs(num177) >= 0.17f)
             {
                 num177 *= 0.7f;
             }
             _ = direction;
             _ = gravDir;
             Vector2 vector57 = Vector2.UnitX * num178;
             Vector2 v7 = vector57;
             int num180 = 0;
             while (v7.Length() < num179 && num180 < num176)
             {
                 num180++;
                 v7 += vector57;
                 vector57 = vector57.RotatedBy(num177);
             }
             float num181 = v7.ToRotation();
             Vector2 spinningpoint2 = v6.SafeNormalize(Vector2.UnitY).RotatedBy(0f - num181 - num177) * num178;
             if (num180 == num176)
             {
                 spinningpoint2 = new Vector2(direction, 0f) * num178;
             }
             if (!zenithTarget2)
             {
                 vector56.Y -= gravDir * 24f;
                 spinningpoint2 = spinningpoint2.RotatedBy((float)direction * gravDir * ((float)Math.PI * 2f) * 0.14f);
             }
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector56, spinningpoint2, projToShoot, (int)((double)Damage * 0.25), KnockBack, i, num177, num180);
             NetMessage.SendData(13, -1, -1, null, whoAmI);
         }
         else if (sItem.type == 3475)
         {
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, 615, Damage, KnockBack, i, 5 * Main.rand.Next(0, 20));
         }
         else if (sItem.type == 3930)
         {
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, 714, Damage, KnockBack, i, 5 * Main.rand.Next(0, 20));
         }
         else if (sItem.type == 3540)
         {
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, 630, Damage, KnockBack, i);
         }
         else if (sItem.type == 5451)
         {
             for (int num182 = 0; num182 < 1000; num182++)
             {
                 Projectile projectile3 = Main.projectile[num182];
                 if (projectile3.type == projToShoot && projectile3.owner == whoAmI)
                 {
                     projectile3.Kill();
                 }
             }
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, Damage, KnockBack, i);
         }
         else if (sItem.type == 3854)
         {
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, 705, Damage, KnockBack, i);
         }
         else if (sItem.type == 3546)
         {
             for (int num183 = 0; num183 < 2; num183++)
             {
                 float num184 = num2;
                 float num185 = num3;
                 num184 += (float)Main.rand.Next(-40, 41) * 0.05f;
                 num185 += (float)Main.rand.Next(-40, 41) * 0.05f;
                 Vector2 vector58 = pointPoisition + Vector2.Normalize(new Vector2(num184, num185).RotatedBy(-(float)Math.PI / 2f * (float)direction)) * 6f;
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector58.X, vector58.Y, num184, num185, 167 + Main.rand.Next(4), Damage, KnockBack, i, 0f, 1f);
             }
         }
         else if (sItem.type == 3350)
         {
             float num186 = num2;
             float num187 = num3;
             num186 += (float)Main.rand.Next(-1, 2) * 0.5f;
             num187 += (float)Main.rand.Next(-1, 2) * 0.5f;
             if (Collision.CanHitLine(base.Center, 0, 0, pointPoisition + new Vector2(num186, num187) * 2f, 0, 0))
             {
                 pointPoisition += new Vector2(num186, num187);
             }
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y - gravDir * 4f, num186, num187, projToShoot, Damage, KnockBack, i, 0f, (float)Main.rand.Next(12) / 6f);
         }
         else if (sItem.type == 3852)
         {
             if (altFunctionUse == 2)
             {
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, base.Bottom.Y - 100f, (float)direction * speed, 0f, 704, (int)((float)Damage * 1.75f), KnockBack, i);
             }
             else
             {
                 Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, Damage, KnockBack, i);
             }
         }
         else if (sItem.type == 3818 || sItem.type == 3819 || sItem.type == 3820 || sItem.type == 3824 || sItem.type == 3825 || sItem.type == 3826 || sItem.type == 3829 || sItem.type == 3830 || sItem.type == 3831 || sItem.type == 3832 || sItem.type == 3833 || sItem.type == 3834)
         {
             PayDD2CrystalsBeforeUse(sItem);
             FindSentryRestingSpot(sItem.shoot, out var worldX, out var worldY, out var pushYUp);
             int num188 = 0;
             int num189 = 0;
             int num190 = 0;
             switch (sItem.type)
             {
             case 3824:
             case 3825:
             case 3826:
                 num188 = 1;
                 num189 = Projectile.GetBallistraShotDelay(this);
                 break;
             case 3832:
             case 3833:
             case 3834:
                 num190 = Projectile.GetExplosiveTrapCooldown(this);
                 break;
             case 3818:
                 num188 = 1;
                 num189 = 80;
                 break;
             case 3819:
                 num188 = 1;
                 num189 = 70;
                 break;
             case 3820:
                 num188 = 1;
                 num189 = 60;
                 break;
             }
             int num191 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, worldX, worldY - pushYUp, 0f, 0f, projToShoot, Damage, KnockBack, i, num188, num189);
             Main.projectile[num191].originalDamage = damage;
             Main.projectile[num191].localAI[0] = num190;
             UpdateMaxTurrets();
         }
         else if (sItem.type == 65)
         {
             Vector2 vector59 = new Vector2(num2, num3);
             new Vector2(100f, 0f);
             Vector2 mouseWorld2 = Main.MouseWorld;
             Vector2 vec = mouseWorld2;
             Vector2 vector60 = (pointPoisition - mouseWorld2).SafeNormalize(new Vector2(0f, -1f));
             while (vec.Y > pointPoisition.Y && WorldGen.SolidTile(vec.ToTileCoordinates()))
             {
                 vec += vector60 * 16f;
             }
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector59, projToShoot, Damage, KnockBack, i, 0f, vec.Y);
         }
         else if (sItem.type == 4923)
         {
             float adjustedItemScale7 = GetAdjustedItemScale(sItem);
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, Damage, KnockBack, i, 0f, adjustedItemScale7);
         }
         else if (sItem.type == 1910)
         {
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, Damage, KnockBack, i, 1f);
         }
         else if (sItem.type == 5134)
         {
             Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, Damage, KnockBack, i, 0f, 1f);
         }
         else
         {
             int num192 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num2, num3, projToShoot, Damage, KnockBack, i);
             if (sItem.type == 726)
             {
                 Main.projectile[num192].magic = true;
             }
             if (sItem.type == 724 || sItem.type == 676)
             {
                 Main.projectile[num192].melee = true;
             }
             if (projToShoot == 80)
             {
                 Main.projectile[num192].ai[0] = tileTargetX;
                 Main.projectile[num192].ai[1] = tileTargetY;
             }
             if (sItem.type == 760)
             {
                 DestroyOldestProximityMinesOverMinesCap(20);
             }
             if (projToShoot == 442)
             {
                 Main.projectile[num192].ai[0] = tileTargetX;
                 Main.projectile[num192].ai[1] = tileTargetY;
             }
             if (projToShoot == 826)
             {
                 Main.projectile[num192].ai[1] = Main.rand.Next(3);
             }
             if (sItem.type == 949)
             {
                 Main.projectile[num192].ai[1] = 1f;
             }
             if (Main.projectile[num192].aiStyle == 99)
             {
                 AchievementsHelper.HandleSpecialEvent(this, 7);
             }
             if (Main.projectile[num192].aiStyle == 160 && Main.IsItAHappyWindyDay)
             {
                 AchievementsHelper.HandleSpecialEvent(this, 17);
             }
             NetMessage.SendData(13, -1, -1, null, whoAmI);
         }
     }
References Entity.active, Tile.active(), Projectile.ai, Projectile.aiStyle, Collision.CanHit(), Collision.CanHitLine(), Entity.Center, Searches.Chain(), Damage, Item.damage, WorldUtils.Find(), Item.fishingPole, Main.GameViewMatrix, Projectile.GetBallistraShotDelay(), Projectile.GetExplosiveTrapCooldown(), Utils.GetLerpValue(), FinalFractalHelper.GetRandomProfileIndex(), ItemID.Sets.gunProj, AchievementsHelper.HandleSpecialEvent(), Entity.height, Entity.Hitbox, Item.IsACoin, ProjectileID.Sets.IsAGolfBall, Main.IsItAHappyWindyDay, Projectile.Kill(), Item.knockBack, Projectile.localAI, Projectile.magic, Main.maxTilesY, Item.melee, Projectile.melee, Main.MouseWorld, Main.mouseX, Main.mouseY, Main.myPlayer, Tile.nactive(), Projectile.netUpdate, Projectile.NewProjectile(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Projectile.noDropItem, ProjectileID.Sets.NoMeleeSpeedVelocityScaling, Main.npc, Projectile.originalDamage, Projectile.owner, TileID.Sets.Platforms, Main.projectile, Main.projFrames, Main.projPet, Main.rand, Item.scale, Main.screenHeight, Main.screenPosition, NetMessage.SendData(), Item.shoot, Item.shootSpeed, WorldGen.SolidTile(), WorldGen.SolidTile2(), Item.summon, Main.tile, Main.tileSolid, Main.tileSolidTop, Projectile.timeLeft, Item.type, Projectile.type, Tile.type, Item.useAmmo, Item.useStyle, Item.useTime, Entity.velocity, Entity.width, and SpriteViewMatrix.Zoom.