Terraria: Player.DoEyebrellaRainEffect
DoEyebrellaRainEffect()
void Player.DoEyebrellaRainEffect () inline private
     {
         if (Main.netMode == 2 || Main.dedServ || Main.rand.Next(4) != 0)
         {
             return;
         }
         Vector2 vector = MountedCenter - new Vector2(0f, (float)height * 0.5f) + new Vector2((-0.5f + Main.rand.NextFloat()) * (float)(width + 18), -30f);
         int num = (int)(vector.X / 16f);
         int num2 = (int)(vector.Y / 16f);
         if (WorldGen.InWorld(num, num2))
         {
             Tile tile = Main.tile[num, num2];
             if (tile != null && !WorldGen.SolidTile3(tile) && tile.liquid <= 0)
             {
                 Rain.NewRainForced(Velocity: new Vector2(Main.windSpeedCurrent * 3f, 9f), Position: vector);
             }
         }
     }
References Main.dedServ, WorldGen.InWorld(), Tile.liquid, Main.netMode, Rain.NewRainForced(), UnifiedRandom.Next(), Main.rand, WorldGen.SolidTile3(), Main.tile, and Main.windSpeedCurrent.