Terraria: Player.ForceUpdateBiomes
ForceUpdateBiomes()
void Player.ForceUpdateBiomes () inline
     {
         if (whoAmI == Main.myPlayer)
         {
             Main.GetAreaToLight(out var firstTileX, out var lastTileX, out var firstTileY, out var lastTileY);
             Rectangle value = new Rectangle(firstTileX, firstTileY, lastTileX - firstTileX, lastTileY - firstTileY);
             int num = 28;
             value.Inflate(num, num);
             Main.SceneMetrics.ScanAndExportToMain(new SceneMetricsScanSettings
             {
                 VisualScanArea = value,
                 BiomeScanCenterPositionInWorld = base.Center,
                 ScanOreFinderData = accOreFinder
             });
             UpdateBiomes();
         }
     }
References Main.GetAreaToLight(), Main.myPlayer, SceneMetrics.ScanAndExportToMain(), and Main.SceneMetrics.
Referenced by Main.DoDraw_UpdateCameraPosition().