Terraria: Player.PlaceThing_PaintScrapper_LongMoss
PlaceThing_PaintScrapper_LongMoss()
void Player.PlaceThing_PaintScrapper_LongMoss (int x, int y) inline private
     {
         if (Main.tile[x, y].type != 184)
         {
             return;
         }
         cursorItemIconEnabled = true;
         if (!ItemTimeIsZero || itemAnimation <= 0 || !controlUseItem)
         {
             return;
         }
         _ = Main.tile[x, y].type;
         int frameX = Main.tile[x, y].frameX;
         WorldGen.KillTile(x, y);
         if (Main.tile[x, y].active())
         {
             return;
         }
         ApplyItemTime(inventory[selectedItem]);
         if (Main.netMode == 1)
         {
             NetMessage.SendData(17, -1, -1, null, 0, x, y);
         }
         if (Main.rand.Next(9) == 0)
         {
             int type = 4349 + frameX / 22;
             switch (frameX / 22)
             {
             case 6:
                 type = 4377;
                 break;
             case 7:
                 type = 4378;
                 break;
             case 8:
                 type = 4389;
                 break;
             case 9:
                 type = 5127;
                 break;
             case 10:
                 type = 5128;
                 break;
             }
             int number = Item.NewItem(new EntitySource_ItemUse(this, HeldItem), x * 16, y * 16, 16, 16, type);
             NetMessage.SendData(21, -1, -1, null, number, 1f);
         }
     }
References Tile.active(), Tile.frameX, WorldGen.KillTile(), Main.netMode, Item.NewItem(), UnifiedRandom.Next(), Main.rand, NetMessage.SendData(), Main.tile, and Tile.type.