Terraria: Player.WingFrame
WingFrame()
void Player.WingFrame (bool wingFlap) inline
     {
         bool flag = wingsLogic != wings;
         if (wings == 4)
         {
             if (wingFlap || jump > 0)
             {
                 rocketDelay2--;
                 if (rocketDelay2 <= 0)
                 {
                     SoundEngine.PlaySound(SoundID.Item13, position);
                     rocketDelay2 = 60;
                 }
                 int num = 2;
                 if (TryingToHoverUp)
                 {
                     num = 4;
                 }
                 for (int i = 0; i < num; i++)
                 {
                     int type = 6;
                     if (head == 41)
                     {
                         _ = body;
                         _ = 24;
                     }
                     float scale = 1.75f;
                     int alpha = 100;
                     float x = position.X + (float)(width / 2) + 16f;
                     if (direction > 0)
                     {
                         x = position.X + (float)(width / 2) - 26f;
                     }
                     float num2 = position.Y + (float)height - 18f;
                     if (i == 1 || i == 3)
                     {
                         x = position.X + (float)(width / 2) + 8f;
                         if (direction > 0)
{
                             x = position.X + (float)(width / 2) - 20f;
                         }
                         num2 += 6f;
                     }
                     if (i > 1)
                     {
                         num2 += velocity.Y;
                     }
                     int num3 = Dust.NewDust(new Vector2(x, num2), 8, 8, type, 0f, 0f, alpha, default(Color), scale);
                     Main.dust[num3].velocity.X *= 0.1f;
                     Main.dust[num3].velocity.Y = Main.dust[num3].velocity.Y * 1f + 2f * gravDir - velocity.Y * 0.3f;
                     Main.dust[num3].noGravity = true;
                     Main.dust[num3].noLightEmittence = flag;
                     Main.dust[num3].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                     if (num == 4)
                     {
                         Main.dust[num3].velocity.Y += 6f;
                     }
                 }
                 wingFrameCounter++;
                 if (wingFrameCounter > 4)
                 {
                     wingFrame++;
                     wingFrameCounter = 0;
                     if (wingFrame >= 3)
                     {
                         wingFrame = 0;
                     }
                 }
             }
             else if (!controlJump || velocity.Y == 0f)
             {
                 wingFrame = 3;
             }
             return;
         }
         if (wings == 28 && ShouldDrawWingsThatAreAlwaysAnimated())
         {
             if (!flag && velocity.Y != 0f)
             {
                 Lighting.AddLight(base.Bottom, 0.3f, 0.1f, 0.4f);
             }
             return;
         }
         if (wings == 22)
         {
             if (!controlJump)
             {
                 wingFrame = 0;
                 wingFrameCounter = 0;
             }
             else if (wingTime > 0f)
             {
                 if (TryingToHoverDown)
                 {
                     if (velocity.X != 0f)
                     {
                         wingFrameCounter++;
                         int num4 = 2;
                         if (wingFrameCounter < num4)
{
                             wingFrame = 1;
                             return;
                         }
                         if (wingFrameCounter < num4 * 2)
{
                             wingFrame = 2;
                             return;
                         }
                         if (wingFrameCounter < num4 * 3)
{
                             wingFrame = 3;
                             return;
                         }
                         if (wingFrameCounter < num4 * 4 - 1)
{
                             wingFrame = 2;
                             return;
                         }
                         wingFrame = 2;
                         wingFrameCounter = 0;
                     }
                     else
                     {
                         wingFrameCounter++;
                         int num5 = 6;
                         if (wingFrameCounter < num5)
{
                             wingFrame = 4;
                             return;
                         }
                         if (wingFrameCounter < num5 * 2)
{
                             wingFrame = 5;
                             return;
                         }
                         if (wingFrameCounter < num5 * 3 - 1)
{
                             wingFrame = 4;
                             return;
                         }
                         wingFrame = 4;
                         wingFrameCounter = 0;
                     }
                 }
                 else
                 {
                     wingFrameCounter++;
                     int num6 = 2;
                     if (wingFrameCounter < num6)
                     {
                         wingFrame = 4;
                         return;
                     }
                     if (wingFrameCounter < num6 * 2)
                     {
                         wingFrame = 5;
                         return;
                     }
                     if (wingFrameCounter < num6 * 3)
                     {
                         wingFrame = 6;
                         return;
                     }
                     if (wingFrameCounter < num6 * 4 - 1)
                     {
                         wingFrame = 5;
                         return;
                     }
                     wingFrame = 5;
                     wingFrameCounter = 0;
                 }
             }
             else
             {
                 wingFrameCounter++;
                 int num7 = 6;
                 if (wingFrameCounter < num7)
                 {
                     wingFrame = 4;
                     return;
                 }
                 if (wingFrameCounter < num7 * 2)
                 {
                     wingFrame = 5;
                     return;
                 }
                 if (wingFrameCounter < num7 * 3 - 1)
                 {
                     wingFrame = 4;
                     return;
                 }
                 wingFrame = 4;
                 wingFrameCounter = 0;
             }
             return;
         }
         if (wings == 12)
         {
             if (wingFlap || jump > 0)
             {
                 wingFrameCounter++;
                 int num8 = 5;
                 if (wingFrameCounter < num8)
                 {
                     wingFrame = 1;
                     return;
                 }
                 if (wingFrameCounter < num8 * 2)
                 {
                     wingFrame = 2;
                     return;
                 }
                 if (wingFrameCounter < num8 * 3)
                 {
                     wingFrame = 3;
                     return;
                 }
                 if (wingFrameCounter < num8 * 4 - 1)
                 {
                     wingFrame = 2;
                     return;
                 }
                 wingFrame = 2;
                 wingFrameCounter = 0;
             }
             else if (velocity.Y != 0f)
             {
                 wingFrame = 2;
             }
             else
             {
                 wingFrame = 0;
             }
             return;
         }
         if (wings == 24)
         {
             if (wingFlap || jump > 0)
             {
                 wingFrameCounter++;
                 int num9 = 1;
                 if (wingFrameCounter < num9)
                 {
                     wingFrame = 1;
                     return;
                 }
                 if (wingFrameCounter < num9 * 2)
                 {
                     wingFrame = 2;
                     return;
                 }
                 if (wingFrameCounter < num9 * 3)
                 {
                     wingFrame = 3;
                     return;
                 }
                 wingFrame = 2;
                 if (wingFrameCounter >= num9 * 4 - 1)
                 {
                     wingFrameCounter = 0;
                 }
             }
             else if (velocity.Y != 0f)
             {
                 if (controlJump)
                 {
                     wingFrameCounter++;
                     int num10 = 3;
                     if (wingFrameCounter < num10)
                     {
                         wingFrame = 1;
                         return;
                     }
                     if (wingFrameCounter < num10 * 2)
                     {
                         wingFrame = 2;
                         return;
                     }
                     if (wingFrameCounter < num10 * 3)
                     {
                         wingFrame = 3;
                         return;
                     }
                     wingFrame = 2;
                     if (wingFrameCounter >= num10 * 4 - 1)
                     {
                         wingFrameCounter = 0;
                     }
                 }
                 else if (wingTime == 0f)
                 {
                     wingFrame = 0;
                 }
                 else
                 {
                     wingFrame = 1;
                 }
             }
             else
             {
                 wingFrame = 0;
             }
             return;
         }
         if (wings == 30)
         {
             bool flag2 = false;
             if (wingFlap || jump > 0)
             {
                 wingFrameCounter++;
                 int num11 = 2;
                 if (wingFrameCounter >= num11 * 3)
                 {
                     wingFrameCounter = 0;
                 }
                 wingFrame = 1 + wingFrameCounter / num11;
                 flag2 = true;
             }
             else if (velocity.Y != 0f)
             {
                 if (controlJump)
                 {
                     wingFrameCounter++;
                     int num12 = 2;
                     if (wingFrameCounter >= num12 * 3)
                     {
                         wingFrameCounter = 0;
                     }
                     wingFrame = 1 + wingFrameCounter / num12;
                     flag2 = true;
                 }
                 else if (wingTime == 0f)
                 {
                     wingFrame = 0;
                 }
                 else
                 {
                     wingFrame = 0;
                 }
             }
             else
             {
                 wingFrame = 0;
             }
             if (!flag2)
             {
                 return;
             }
             for (int j = 0; j < 4; j++)
             {
                 if (Main.rand.Next(4) == 0)
                 {
                     Vector2 vector = (-0.74539816f + (float)Math.PI / 8f * (float)j + 0.03f * (float)j).ToRotationVector2() * new Vector2(-direction * 20, 20f);
                     Dust dust = Main.dust[Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100, Color.White, 0.8f)];
                     dust.noGravity = true;
                     dust.noLightEmittence = flag;
                     dust.position = base.Center + vector;
                     dust.velocity = DirectionTo(dust.position) * 2f;
                     if (Main.rand.Next(10) != 0)
                     {
                         dust.customData = this;
                     }
                     else
                     {
                         dust.fadeIn = 0.5f;
                     }
                     dust.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                 }
             }
             for (int k = 0; k < 4; k++)
             {
                 if (Main.rand.Next(8) == 0)
                 {
                     Vector2 vector2 = (-0.7053982f + (float)Math.PI / 8f * (float)k + 0.03f * (float)k).ToRotationVector2() * new Vector2(direction * 20, 24f) + new Vector2((float)(-direction) * 16f, 0f);
                     Dust dust2 = Main.dust[Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100, Color.White, 0.5f)];
                     dust2.noGravity = true;
                     dust2.noLightEmittence = flag;
                     dust2.position = base.Center + vector2;
                     dust2.velocity = Vector2.Normalize(dust2.position - base.Center - new Vector2((float)(-direction) * 16f, 0f)) * 2f;
                     dust2.position += dust2.velocity * 5f;
                     if (Main.rand.Next(10) != 0)
                     {
                         dust2.customData = this;
                     }
                     else
                     {
                         dust2.fadeIn = 0.5f;
                     }
                     dust2.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                 }
             }
             return;
         }
         if (wings == 34 && ShouldDrawWingsThatAreAlwaysAnimated())
         {
             if (wingFlap || jump > 0)
             {
                 wingFrameCounter++;
                 int num13 = 4;
                 if (wingFrameCounter >= num13 * 6)
                 {
                     wingFrameCounter = 0;
                 }
                 wingFrame = wingFrameCounter / num13;
             }
             else if (velocity.Y != 0f)
             {
                 if (controlJump)
                 {
                     wingFrameCounter++;
                     int num14 = 9;
                     if (wingFrameCounter >= num14 * 6)
                     {
                         wingFrameCounter = 0;
                     }
                     wingFrame = wingFrameCounter / num14;
                 }
                 else
                 {
                     wingFrameCounter++;
                     int num15 = 6;
                     if (wingFrameCounter >= num15 * 6)
                     {
                         wingFrameCounter = 0;
                     }
                     wingFrame = wingFrameCounter / num15;
                 }
             }
             else
             {
                 wingFrameCounter++;
                 int num16 = 4;
                 if (wingFrameCounter >= num16 * 6)
                 {
                     wingFrameCounter = 0;
                 }
                 wingFrame = wingFrameCounter / num16;
             }
             return;
         }
         if (wings == 45 && ShouldDrawWingsThatAreAlwaysAnimated())
         {
             if (wingTime > 0f)
             {
                 rocketDelay2--;
                 if (rocketDelay2 <= 0)
                 {
                     SoundEngine.PlaySound(SoundID.Item24, position);
                     rocketDelay2 = 30;
                 }
             }
             if (velocity.Y == 0f)
             {
                 wingFrameCounter = 0;
                 wingFrame = 0;
             }
             else
             {
                 wingFrameCounter++;
                 int num17 = 3;
                 if (wingTime == 0f)
                 {
                     num17 = 5;
                 }
                 if (wingFrameCounter >= num17 * 6)
                 {
                     wingFrameCounter = 0;
                 }
                 wingFrame = wingFrameCounter / num17;
             }
             if (Main.netMode != 2 && Main.rand.Next(8) == 0)
             {
                 Rectangle r = Utils.CenteredRectangle(Main.ReverseGravitySupport(base.Bottom - Main.screenPosition) + Main.screenPosition, new Vector2(40f, 24f));
                 Dust dust3 = Dust.NewDustDirect(r.TopLeft(), r.Width, r.Height, 43, 0f, 0f, 0, Color.White * 0.5f, 0.2f);
                 dust3.fadeIn = 0.4f;
                 dust3.velocity += velocity;
                 dust3.velocity *= 0.35f;
                 dust3.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
             }
             return;
         }
         if (wings == 44 && ShouldDrawWingsThatAreAlwaysAnimated())
         {
             int num18 = 5;
             if (wingFlap || jump > 0)
             {
                 wingFrameCounter++;
                 if (wingFrameCounter >= num18 * 6)
                 {
                     wingFrameCounter = 0;
                 }
                 wingFrame = 1 + wingFrameCounter / num18;
             }
             else if (velocity.Y != 0f)
             {
                 if (controlJump)
                 {
                     wingFrame = 2;
                 }
                 else if (ShouldFloatInWater && wet)
                 {
                     wingFrame = 0;
                 }
                 else
                 {
                     wingFrame = 3;
                 }
             }
             else
             {
                 wingFrameCounter++;
                 if (wingFrameCounter >= num18 * 6)
                 {
                     wingFrameCounter = 0;
                 }
                 wingFrame = 1 + wingFrameCounter / num18;
             }
             return;
         }
         if (wings == 39 && ShouldDrawWingsThatAreAlwaysAnimated())
         {
             if (wingFlap || jump > 0)
             {
                 wingFrameCounter++;
                 int num19 = 4;
                 if (wingFrameCounter >= num19 * 6)
                 {
                     wingFrameCounter = 0;
                 }
                 wingFrame = wingFrameCounter / num19;
             }
             else if (velocity.Y != 0f)
             {
                 if (controlJump)
                 {
                     wingFrameCounter++;
                     int num20 = 9;
                     if (wingFrameCounter >= num20 * 6)
                     {
                         wingFrameCounter = 0;
                     }
                     wingFrame = wingFrameCounter / num20;
                 }
                 else
                 {
                     wingFrameCounter++;
                     int num21 = 6;
                     if (wingFrameCounter >= num21 * 6)
                     {
                         wingFrameCounter = 0;
                     }
                     wingFrame = wingFrameCounter / num21;
                 }
             }
             else
             {
                 wingFrameCounter++;
                 int num22 = 4;
                 if (wingFrameCounter >= num22 * 6)
                 {
                     wingFrameCounter = 0;
                 }
                 wingFrame = wingFrameCounter / num22;
             }
             int num23 = 1;
             if (wingFrame == 3)
             {
                 num23 = 5;
             }
             if (velocity.Y == 0f)
             {
                 num23 = 0;
             }
             Rectangle r2 = Utils.CenteredRectangle((gravDir == 1f) ? (base.Bottom + new Vector2(0f, -10f)) : (base.Top + new Vector2(0f, 10f)), new Vector2(50f, 20f));
             for (int l = 0; l < num23; l++)
             {
                 Dust dust4 = Dust.NewDustDirect(r2.TopLeft(), r2.Width, r2.Height, 31, 0f, 0f, 0, Color.Black);
                 dust4.scale = 0.7f;
                 dust4.velocity *= 0.4f;
                 dust4.velocity.Y += gravDir * 0.5f;
                 dust4.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
             }
             return;
         }
         if (wings == 33)
         {
             bool flag3 = false;
             if (wingFlap || jump > 0)
             {
                 flag3 = true;
             }
             else if (velocity.Y != 0f && controlJump)
             {
                 flag3 = true;
             }
             if (!flag3)
             {
                 return;
             }
             Color newColor = Main.hslToRgb(Main.rgbToHsl(eyeColor).X, 1f, 0.5f);
             int num24 = ((direction != 1) ? (-4) : 0);
             int num25 = ((gravDir == 1f) ? height : 0);
             for (int m = 0; m < 2; m++)
             {
                 Dust dust5 = Main.dust[Dust.NewDust(position, width, height, 182, velocity.X, velocity.Y, 127, newColor)];
                 dust5.noGravity = true;
                 dust5.fadeIn = 1f;
                 dust5.scale = 1f;
                 dust5.noLight = true;
                 dust5.noLightEmittence = flag;
                 dust5.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                 switch (m)
                 {
                 case 0:
                     dust5.position = new Vector2(position.X + (float)num24, position.Y + (float)num25);
                     dust5.velocity.X = dust5.velocity.X * 1f - 2f - velocity.X * 0.3f;
                     dust5.velocity.Y = dust5.velocity.Y * 1f + 2f * gravDir - velocity.Y * 0.3f;
                     break;
                 case 1:
                     dust5.position = new Vector2(position.X + (float)width + (float)num24, position.Y + (float)num25);
                     dust5.velocity.X = dust5.velocity.X * 1f + 2f - velocity.X * 0.3f;
                     dust5.velocity.Y = dust5.velocity.Y * 1f + 2f * gravDir - velocity.Y * 0.3f;
                     break;
                 }
                 if (dust5.dustIndex != 6000)
                 {
                     Dust dust6 = Dust.CloneDust(dust5);
                     dust6.scale *= 0.65f;
                     dust6.fadeIn *= 0.65f;
                     dust6.color = new Color(255, 255, 255, 255);
                     dust5.noLight = true;
                     dust5.noLightEmittence = flag;
                     dust5.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                 }
             }
             return;
         }
         if (wings == 38)
         {
             bool flag4 = false;
             if (wingFlap || jump > 0)
             {
                 wingFrameCounter++;
                 if (wingFrameCounter >= 32)
                 {
                     wingFrameCounter = 0;
                 }
                 wingFrame = 1 + wingFrameCounter / 8;
                 if (wingFrame == 4)
                 {
                     wingFrame = 2;
                 }
                 flag4 = true;
             }
             else if (velocity.Y != 0f)
             {
                 if (controlJump)
                 {
                     wingFrameCounter++;
                     if (wingFrameCounter >= 32)
                     {
                         wingFrameCounter = 0;
                     }
                     wingFrame = 1 + wingFrameCounter / 8;
                     if (wingFrame == 4)
                     {
                         wingFrame = 2;
                     }
                     flag4 = true;
                 }
                 else
                 {
                     wingFrame = 0;
                 }
             }
             else
             {
                 wingFrame = 0;
             }
             if (!flag4)
             {
                 return;
             }
             Vector2 vector3 = new Vector2(direction, gravDir);
             Vector2 value = velocity * 0.5f;
             int type2 = 267;
             int num26 = miscCounter * direction;
             for (int n = 0; n < 3; n++)
             {
                 Vector2 vector4 = Vector2.Zero;
                 switch (n)
                 {
                 case 1:
                     vector4 = velocity * -0.33f;
                     break;
                 case 2:
                     vector4 = velocity * -0.66f;
                     break;
                 }
                 Vector2 vector5 = new Vector2(-39f, 6f) * vector3 + new Vector2(2f, 0f).RotatedBy((float)num26 / -15f * ((float)Math.PI * 2f));
                 Dust dust7 = Dust.NewDustPerfect(base.Center + vector5 + vector4, type2, value, 0, underShirtColor);
                 dust7.noGravity = true;
                 dust7.noLight = true;
                 dust7.noLightEmittence = flag;
                 dust7.scale = 0.47f;
                 dust7.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                 vector5 = new Vector2(-23f, 2f) * vector3 + new Vector2(2f, 0f).RotatedBy((float)num26 / -15f * ((float)Math.PI * 2f));
                 Dust dust8 = Dust.NewDustPerfect(base.Center + vector5 + vector4, type2, value, 0, underShirtColor);
                 dust8.noGravity = true;
                 dust8.noLight = true;
                 dust8.noLightEmittence = flag;
                 dust8.scale = 0.35f;
                 dust8.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                 vector5 = new Vector2(-31f, -6f) * vector3 + new Vector2(2f, 0f).RotatedBy((float)num26 / -20f * ((float)Math.PI * 2f));
                 Dust dust9 = Dust.NewDustPerfect(base.Center + vector5 + vector4, type2, value, 0, underShirtColor);
                 dust9.noGravity = true;
                 dust9.noLight = true;
                 dust9.noLightEmittence = flag;
                 dust9.scale = 0.49f;
                 dust9.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
             }
             return;
         }
         int num27 = 4;
         int num28 = 4;
         int num29 = 0;
         if (wings == 43)
         {
             num28 = 7;
             num29 = 1;
             num27 = 3;
         }
         if (wings == 32)
         {
             num27 = 3;
         }
         if (wingFlap || jump > 0)
         {
             wingFrameCounter++;
             if (wingFrameCounter > num27)
             {
                 wingFrame++;
                 wingFrameCounter = 0;
                 if (wingFrame >= num28)
                 {
                     wingFrame = num29;
                 }
             }
         }
         else if (velocity.Y != 0f)
         {
             wingFrame = 1;
             if (wings == 32)
             {
                 wingFrame = 3;
             }
             if (wings == 43)
             {
                 wingFrame = 2;
                 if (ShouldFloatInWater && wet)
                 {
                     wingFrame = 0;
                 }
             }
             if (wings == 29 && Main.rand.Next(5) == 0)
             {
                 int num30 = 4;
                 if (direction == 1)
                 {
                     num30 = -40;
                 }
                 int num31 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num30, position.Y + (float)(height / 2) - 15f), 30, 30, 6, 0f, 0f, 100, default(Color), 2.4f);
                 Main.dust[num31].noGravity = true;
                 Main.dust[num31].noLightEmittence = flag;
                 Main.dust[num31].velocity *= 0.3f;
                 if (Main.rand.Next(10) == 0)
                 {
                     Main.dust[num31].fadeIn = 2f;
                 }
                 Main.dust[num31].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
             }
         }
         else
         {
             wingFrame = 0;
         }
     }
References Lighting.AddLight(), GameShaders.Armor, Utils.CenteredRectangle(), Dust.CloneDust(), Color, Dust.color, Dust.customData, Main.dust, Dust.dustIndex, Dust.fadeIn, ArmorShaderDataSet.GetSecondaryShader(), Main.hslToRgb(), SoundID.Item13, SoundID.Item24, Main.netMode, Dust.NewDust(), Dust.NewDustDirect(), Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, SoundEngine.PlaySound(), Dust.position, Main.rand, Main.ReverseGravitySupport(), Main.rgbToHsl(), Dust.scale, Main.screenPosition, Dust.shader, and Dust.velocity.
Referenced by UICharacter.UpdateAnim().