Terraria: Player.ItemCheck_TryPlacingWearablesOnMannequins
ItemCheck_TryPlacingWearablesOnMannequins()
void Player.ItemCheck_TryPlacingWearablesOnMannequins (Item sItem) inline private
     {
         if (!controlUseItem || !releaseUseItem || (sItem.headSlot <= 0 && sItem.bodySlot <= 0 && sItem.legSlot <= 0))
         {
             return;
         }
         if (sItem.useStyle == 0)
         {
             releaseUseItem = false;
         }
         if (!(position.X / 16f - (float)tileRangeX - (float)sItem.tileBoost <= (float)tileTargetX) || !((position.X + (float)width) / 16f + (float)tileRangeX + (float)sItem.tileBoost - 1f >= (float)tileTargetX) || !(position.Y / 16f - (float)tileRangeY - (float)sItem.tileBoost <= (float)tileTargetY) || !((position.Y + (float)height) / 16f + (float)tileRangeY + (float)sItem.tileBoost - 2f >= (float)tileTargetY))
         {
             return;
         }
         int num = tileTargetX;
         int num2 = tileTargetY;
         if (!Main.tile[num, num2].active() || (Main.tile[num, num2].type != 128 && Main.tile[num, num2].type != 269))
         {
             return;
         }
         int frameY = Main.tile[num, num2].frameY;
         int num3 = 0;
         if (sItem.bodySlot >= 0)
         {
             num3 = 1;
         }
         if (sItem.legSlot >= 0)
         {
             num3 = 2;
         }
         frameY /= 18;
         while (num3 > frameY)
         {
             num2++;
             frameY = Main.tile[num, num2].frameY;
             frameY /= 18;
         }
         while (num3 < frameY)
         {
             num2--;
             frameY = Main.tile[num, num2].frameY;
             frameY /= 18;
         }
         int num4;
         for (num4 = Main.tile[num, num2].frameX; num4 >= 100; num4 -= 100)
         {
         }
         if (num4 >= 36)
         {
             num4 -= 36;
         }
         num -= num4 / 18;
         int num5 = Main.tile[num, num2].frameX;
         WorldGen.KillTile(num, num2, fail: true);
         if (Main.netMode == 1)
         {
             NetMessage.SendData(17, -1, -1, null, 0, num, num2, 1f);
         }
         while (num5 >= 100)
         {
             num5 -= 100;
         }
         if (frameY == 0 && sItem.headSlot >= 0)
         {
             Main.blockMouse = true;
             Main.tile[num, num2].frameX = (short)(num5 + sItem.headSlot * 100);
             if (Main.netMode == 1)
             {
                 NetMessage.SendTileSquare(-1, num, num2);
             }
             sItem.stack--;
             if (sItem.stack <= 0)
             {
                 sItem.SetDefaults();
                 Main.mouseItem.SetDefaults();
             }
             if (selectedItem == 58)
             {
                 Main.mouseItem = sItem.Clone();
             }
             releaseUseItem = false;
             mouseInterface = true;
         }
         else if (frameY == 1 && sItem.bodySlot >= 0)
         {
             Main.blockMouse = true;
             Main.tile[num, num2].frameX = (short)(num5 + sItem.bodySlot * 100);
             if (Main.netMode == 1)
             {
                 NetMessage.SendTileSquare(-1, num, num2);
             }
             sItem.stack--;
             if (sItem.stack <= 0)
             {
                 sItem.SetDefaults();
                 Main.mouseItem.SetDefaults();
             }
             if (selectedItem == 58)
             {
                 Main.mouseItem = sItem.Clone();
             }
             releaseUseItem = false;
             mouseInterface = true;
         }
         else if (frameY == 2 && sItem.legSlot >= 0 && !ArmorIDs.Legs.Sets.MannequinIncompatible.Contains(sItem.legSlot))
         {
             Main.blockMouse = true;
             Main.tile[num, num2].frameX = (short)(num5 + sItem.legSlot * 100);
             if (Main.netMode == 1)
             {
                 NetMessage.SendTileSquare(-1, num, num2);
             }
             sItem.stack--;
             if (sItem.stack <= 0)
             {
                 sItem.SetDefaults();
                 Main.mouseItem.SetDefaults();
             }
             if (selectedItem == 58)
             {
                 Main.mouseItem = sItem.Clone();
             }
             releaseUseItem = false;
             mouseInterface = true;
         }
     }
References Tile.active(), Main.blockMouse, Item.bodySlot, Item.Clone(), Tile.frameX, Tile.frameY, Item.headSlot, WorldGen.KillTile(), Item.legSlot, ArmorIDs.Legs.Sets.MannequinIncompatible, Main.mouseItem, Main.netMode, NetMessage.SendData(), NetMessage.SendTileSquare(), Item.SetDefaults(), Item.stack, Main.tile, Item.tileBoost, Tile.type, and Item.useStyle.