Terraria: Player.MagicConch
MagicConch()
void Player.MagicConch () inline
     {
         bool flag = position.X / 16f < (float)(Main.maxTilesX / 2);
         bool flag2 = false;
         int num = 50;
         int num2 = 50;
         int num3 = WorldGen.beachDistance - num - num2;
         if (flag)
         {
             num3 = Main.maxTilesX - num3 - 1 - num2;
         }
         else
         {
             num3 -= num2 / 2;
         }
         _ = (float)Main.maxTilesY / 1200f;
         _ = (float)Main.maxTilesY / 1200f;
         new RandomTeleportationAttemptSettings
         {
             avoidAnyLiquid = true,
             avoidHurtTiles = true,
             attemptsBeforeGivingUp = 1000,
             maximumFallDistanceFromOrignalPoint = 300
         };
         Vector2 vector = Vector2.Zero;
         int num4 = flag.ToDirectionInt();
         int startX = (flag ? (Main.maxTilesX - 50) : 50);
         flag2 = true;
         if (!TeleportHelpers.RequestMagicConchTeleportPosition(this, -num4, startX, out var landingPoint))
         {
             flag2 = false;
             startX = ((!flag) ? (Main.maxTilesX - 50) : 50);
             if (TeleportHelpers.RequestMagicConchTeleportPosition(this, num4, startX, out landingPoint))
             {
                 flag2 = true;
             }
         }
         if (flag2)
         {
             vector = landingPoint.ToWorldCoordinates(8f, 16f) - new Vector2(width / 2, height);
         }
         if (flag2)
         {
             Vector2 newPos = vector;
             Teleport(newPos, 5);
             velocity = Vector2.Zero;
             if (Main.netMode == 2)
             {
                 RemoteClient.CheckSection(whoAmI, position);
                 NetMessage.SendData(65, -1, -1, null, 0, whoAmI, newPos.X, newPos.Y, 5);
             }
         }
         else
         {
             Vector2 newPos2 = position;
             Teleport(newPos2, 5);
             velocity = Vector2.Zero;
             if (Main.netMode == 2)
             {
                 RemoteClient.CheckSection(whoAmI, position);
                 NetMessage.SendData(65, -1, -1, null, 0, whoAmI, newPos2.X, newPos2.Y, 5, 1);
             }
         }
     }
References WorldGen.beachDistance, RemoteClient.CheckSection(), Main.maxTilesX, Main.maxTilesY, Main.netMode, TeleportHelpers.RequestMagicConchTeleportPosition(), and NetMessage.SendData().
Referenced by MessageBuffer.GetData().