Terraria: Player.JumpMovement
JumpMovement()
void Player.JumpMovement () inline
     {
         if (mount.Active && mount.IsConsideredASlimeMount && wetSlime == 0 && velocity.Y > 0f)
         {
             Rectangle rect = getRect();
             rect.Offset(0, height - 1);
             rect.Height = 2;
             rect.Inflate(12, 6);
             for (int i = 0; i < 200; i++)
             {
                 NPC nPC = Main.npc[i];
                 if (!nPC.active || nPC.dontTakeDamage || nPC.friendly || nPC.immune[whoAmI] != 0 || !CanNPCBeHitByPlayerOrPlayerProjectile(nPC))
                 {
                     continue;
                 }
                 Rectangle rect2 = nPC.getRect();
                 if (rect.Intersects(rect2) && (nPC.noTileCollide || Collision.CanHit(position, width, height, nPC.position, nPC.width, nPC.height)))
                 {
                     float num = 40f * minionDamage;
                     float knockback = 5f;
                     int num2 = direction;
                     if (velocity.X < 0f)
                     {
                         num2 = -1;
                     }
                     if (velocity.X > 0f)
                     {
                         num2 = 1;
                     }
                     if (whoAmI == Main.myPlayer)
                     {
                         ApplyDamageToNPC(nPC, (int)num, knockback, num2, crit: false);
                     }
                     nPC.immune[whoAmI] = 10;
                     velocity.Y = -10f;
                     GiveImmuneTimeForCollisionAttack(6);
                     break;
                 }
             }
         }
         if (mount.Active && mount.Type == 17 && velocity.Y > 0f)
         {
             Rectangle rect3 = getRect();
             rect3.Offset(0, height - 1);
             rect3.Height = 2;
             rect3.Inflate(12, 6);
             for (int j = 0; j < 200; j++)
             {
                 NPC nPC2 = Main.npc[j];
                 if (!nPC2.active || nPC2.dontTakeDamage || nPC2.friendly || nPC2.immune[whoAmI] != 0 || !CanNPCBeHitByPlayerOrPlayerProjectile(nPC2))
                 {
                     continue;
                 }
                 Rectangle rect4 = nPC2.getRect();
                 if (rect3.Intersects(rect4) && (nPC2.noTileCollide || Collision.CanHit(position, width, height, nPC2.position, nPC2.width, nPC2.height)))
                 {
                     float num3 = 40f;
                     float knockback2 = 5f;
                     int num4 = direction;
                     if (velocity.X < 0f)
                     {
                         num4 = -1;
                     }
                     if (velocity.X > 0f)
                     {
                         num4 = 1;
                     }
                     if (whoAmI == Main.myPlayer)
                     {
                         ApplyDamageToNPC(nPC2, (int)num3, knockback2, num4, crit: false);
                     }
                     nPC2.immune[whoAmI] = 12;
                     GiveImmuneTimeForCollisionAttack(12);
                     break;
                 }
             }
         }
         if (controlJump)
         {
             if (sliding)
             {
                 autoJump = false;
             }
             bool flag = false;
             bool flag2 = wet && accFlipper;
             bool flag3 = !mount.Active || !mount.Cart;
             if (mount.Active && mount.IsConsideredASlimeMount && wetSlime > 0)
             {
                 wetSlime = 0;
                 flag = true;
             }
             if (mount.Active && mount.Type == 43 && releaseJump && velocity.Y != 0f)
             {
                 isPerformingPogostickTricks = true;
             }
             if (jump > 0)
             {
                 if (velocity.Y == 0f)
                 {
                     jump = 0;
                 }
                 else
                 {
                     velocity.Y = (0f - jumpSpeed) * gravDir;
                     if (merman && (!mount.Active || !mount.Cart))
                     {
                         if (swimTime <= 10)
{
                             swimTime = 30;
                         }
                     }
                     else
                     {
                         jump--;
                     }
                 }
             }
             else if ((sliding || velocity.Y == 0f || flag || canJumpAgain_Cloud || canJumpAgain_Sandstorm || canJumpAgain_Blizzard || canJumpAgain_Fart || canJumpAgain_Sail || canJumpAgain_Unicorn || canJumpAgain_Santank || canJumpAgain_WallOfFleshGoat || canJumpAgain_Basilisk || (flag2 && flag3)) && (releaseJump || (autoJump && (velocity.Y == 0f || sliding))))
             {
                 if (mount.Active && MountID.Sets.Cart[mount.Type])
                 {
                     position.Y -= 0.001f;
                 }
                 if (sliding || velocity.Y == 0f)
                 {
                     justJumped = true;
                 }
                 bool flag4 = false;
                 if (wet && accFlipper)
                 {
                     if (swimTime == 0)
                     {
                         swimTime = 30;
                     }
                     flag4 = true;
                 }
                 bool flag5 = false;
                 bool flag6 = false;
                 bool flag7 = false;
                 bool flag8 = false;
                 bool flag9 = false;
                 bool flag10 = false;
                 bool flag11 = false;
                 bool flag12 = false;
                 if (!flag2 && !flag)
                 {
                     if (canJumpAgain_Basilisk)
                     {
                         flag12 = true;
                         canJumpAgain_Basilisk = false;
                     }
                     if (canJumpAgain_WallOfFleshGoat)
                     {
                         flag11 = true;
                         canJumpAgain_WallOfFleshGoat = false;
                     }
                     else if (canJumpAgain_Santank)
                     {
                         flag10 = true;
                         canJumpAgain_Santank = false;
                     }
                     else if (canJumpAgain_Unicorn)
                     {
                         flag9 = true;
                         canJumpAgain_Unicorn = false;
                     }
                     else if (canJumpAgain_Sandstorm)
                     {
                         flag5 = true;
                         canJumpAgain_Sandstorm = false;
                     }
                     else if (canJumpAgain_Blizzard)
                     {
                         flag6 = true;
                         canJumpAgain_Blizzard = false;
                     }
                     else if (canJumpAgain_Fart)
                     {
                         canJumpAgain_Fart = false;
                         flag7 = true;
                     }
                     else if (canJumpAgain_Sail)
                     {
                         canJumpAgain_Sail = false;
                         flag8 = true;
                     }
                     else
                     {
                         canJumpAgain_Cloud = false;
                     }
                 }
                 canRocket = false;
                 rocketRelease = false;
                 if (velocity.Y == 0f || sliding || (autoJump && justJumped))
                 {
                     RefreshDoubleJumps();
                 }
                 if (velocity.Y == 0f || flag4 || sliding || flag)
                 {
                     if (mount.Active && mount.Type == 43)
                     {
                         SoundEngine.PlaySound(SoundID.Item168, base.Center);
                     }
                     velocity.Y = (0f - jumpSpeed) * gravDir;
                     jump = jumpHeight;
                     if (portableStoolInfo.IsInUse)
                     {
                         position.Y -= portableStoolInfo.HeightBoost;
                         gfxOffY += portableStoolInfo.HeightBoost;
                     }
                     if (sliding)
                     {
                         velocity.X = 3 * -slideDir;
                     }
                 }
                 else if (flag5)
                 {
                     isPerformingJump_Sandstorm = true;
                     _ = height;
                     _ = gravDir;
                     _ = -1f;
                     SoundEngine.PlaySound(16, (int)position.X, (int)position.Y);
                     velocity.Y = (0f - jumpSpeed) * gravDir;
                     jump = jumpHeight * 3;
                 }
                 else if (flag6)
                 {
                     isPerformingJump_Blizzard = true;
                     _ = height;
                     _ = gravDir;
                     _ = -1f;
                     SoundEngine.PlaySound(16, (int)position.X, (int)position.Y);
                     velocity.Y = (0f - jumpSpeed) * gravDir;
                     jump = (int)((double)jumpHeight * 1.5);
                 }
                 else if (flag8)
                 {
                     isPerformingJump_Sail = true;
                     int num5 = height;
                     if (gravDir == -1f)
                     {
                         num5 = 0;
                     }
                     SoundEngine.PlaySound(16, (int)position.X, (int)position.Y);
                     velocity.Y = (0f - jumpSpeed) * gravDir;
                     jump = (int)((double)jumpHeight * 1.25);
                     for (int k = 0; k < 30; k++)
                     {
                         int num6 = Dust.NewDust(new Vector2(position.X, position.Y + (float)num5), width, 12, 253, velocity.X * 0.3f, velocity.Y * 0.3f, 100, default(Color), 1.5f);
                         if (k % 2 == 0)
{
                             Main.dust[num6].velocity.X += (float)Main.rand.Next(30, 71) * 0.1f;
                         }
                         else
{
                             Main.dust[num6].velocity.X -= (float)Main.rand.Next(30, 71) * 0.1f;
                         }
                         Main.dust[num6].velocity.Y += (float)Main.rand.Next(-10, 31) * 0.1f;
                         Main.dust[num6].noGravity = true;
                         Main.dust[num6].scale += (float)Main.rand.Next(-10, 41) * 0.01f;
                         Main.dust[num6].velocity *= Main.dust[num6].scale * 0.7f;
                         Vector2 vector = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                         vector.Normalize();
                         vector *= (float)Main.rand.Next(81) * 0.1f;
                     }
                 }
                 else if (flag7)
                 {
                     isPerformingJump_Fart = true;
                     int num7 = height;
                     if (gravDir == -1f)
                     {
                         num7 = 0;
                     }
                     SoundEngine.PlaySound(SoundID.Item16, position);
                     velocity.Y = (0f - jumpSpeed) * gravDir;
                     jump = jumpHeight * 2;
                     for (int l = 0; l < 10; l++)
                     {
                         int num8 = Dust.NewDust(new Vector2(position.X - 34f, position.Y + (float)num7 - 16f), 102, 32, 188, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 100, default(Color), 1.5f);
                         Main.dust[num8].velocity.X = Main.dust[num8].velocity.X * 0.5f - velocity.X * 0.1f;
                         Main.dust[num8].velocity.Y = Main.dust[num8].velocity.Y * 0.5f - velocity.Y * 0.3f;
                     }
                     int num9 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 16f, position.Y + (float)num7 - 16f), new Vector2(0f - velocity.X, 0f - velocity.Y), Main.rand.Next(435, 438));
                     Main.gore[num9].velocity.X = Main.gore[num9].velocity.X * 0.1f - velocity.X * 0.1f;
                     Main.gore[num9].velocity.Y = Main.gore[num9].velocity.Y * 0.1f - velocity.Y * 0.05f;
                     num9 = Gore.NewGore(new Vector2(position.X - 36f, position.Y + (float)num7 - 16f), new Vector2(0f - velocity.X, 0f - velocity.Y), Main.rand.Next(435, 438));
                     Main.gore[num9].velocity.X = Main.gore[num9].velocity.X * 0.1f - velocity.X * 0.1f;
                     Main.gore[num9].velocity.Y = Main.gore[num9].velocity.Y * 0.1f - velocity.Y * 0.05f;
                     num9 = Gore.NewGore(new Vector2(position.X + (float)width + 4f, position.Y + (float)num7 - 16f), new Vector2(0f - velocity.X, 0f - velocity.Y), Main.rand.Next(435, 438));
                     Main.gore[num9].velocity.X = Main.gore[num9].velocity.X * 0.1f - velocity.X * 0.1f;
                     Main.gore[num9].velocity.Y = Main.gore[num9].velocity.Y * 0.1f - velocity.Y * 0.05f;
                 }
                 else if (flag9)
                 {
                     isPerformingJump_Unicorn = true;
                     _ = height;
                     _ = gravDir;
                     _ = -1f;
                     SoundEngine.PlaySound(16, (int)position.X, (int)position.Y);
                     velocity.Y = (0f - jumpSpeed) * gravDir;
                     jump = jumpHeight * 2;
                     Vector2 center = base.Center;
                     Vector2 vector2 = new Vector2(50f, 20f);
                     float num10 = (float)Math.PI * 2f * Main.rand.NextFloat();
                     for (int m = 0; m < 5; m++)
                     {
                         for (float num11 = 0f; num11 < 14f; num11 += 1f)
{
                             Dust obj = Main.dust[Dust.NewDust(center, 0, 0, Utils.SelectRandom<int>(Main.rand, 176, 177, 179))];
                             Vector2 vector3 = Vector2.UnitY.RotatedBy(num11 * ((float)Math.PI * 2f) / 14f + num10);
                             vector3 *= 0.2f * (float)m;
                             obj.position = center + vector3 * vector2;
                             obj.velocity = vector3 + new Vector2(0f, gravDir * 4f);
                             obj.noGravity = true;
                             obj.scale = 1f + Main.rand.NextFloat() * 0.8f;
                             obj.fadeIn = Main.rand.NextFloat() * 2f;
                             obj.shader = GameShaders.Armor.GetSecondaryShader(cMount, this);
                         }
                     }
                 }
                 else if (flag11)
                 {
                     isPerformingJump_WallOfFleshGoat = true;
                     _ = height;
                     _ = gravDir;
                     _ = -1f;
                     SoundEngine.PlaySound(16, (int)position.X, (int)position.Y);
                     velocity.Y = (0f - jumpSpeed) * gravDir;
                     jump = jumpHeight * 2;
                     Vector2 center2 = base.Center;
                     Vector2 vector4 = new Vector2(50f, 20f);
                     float num12 = (float)Math.PI * 2f * Main.rand.NextFloat();
                     for (int n = 0; n < 5; n++)
                     {
                         for (float num13 = 0f; num13 < 14f; num13 += 1f)
{
                             Dust obj2 = Main.dust[Dust.NewDust(center2, 0, 0, 6)];
                             Vector2 vector5 = Vector2.UnitY.RotatedBy(num13 * ((float)Math.PI * 2f) / 14f + num12);
                             vector5 *= 0.2f * (float)n;
                             obj2.position = center2 + vector5 * vector4;
                             obj2.velocity = vector5 + new Vector2(0f, gravDir * 4f);
                             obj2.noGravity = true;
                             obj2.scale = 1f + Main.rand.NextFloat() * 0.8f;
                             obj2.fadeIn = Main.rand.NextFloat() * 2f;
                             obj2.shader = GameShaders.Armor.GetSecondaryShader(cMount, this);
                         }
                     }
                 }
                 else if (flag12)
                 {
                     isPerformingJump_Basilisk = true;
                     _ = height;
                     _ = gravDir;
                     _ = -1f;
                     SoundEngine.PlaySound(16, (int)position.X, (int)position.Y);
                     velocity.Y = (0f - jumpSpeed) * gravDir;
                     jump = (int)((double)jumpHeight * 0.75);
                     Vector2 center3 = base.Center;
                     Vector2 vector6 = new Vector2(50f, 20f);
                     float num14 = (float)Math.PI * 2f * Main.rand.NextFloat();
                     for (int num15 = 0; num15 < 5; num15++)
                     {
                         for (float num16 = 0f; num16 < 14f; num16 += 1f)
{
                             Dust obj3 = Main.dust[Dust.NewDust(center3, 0, 0, 31)];
                             Vector2 vector7 = Vector2.UnitY.RotatedBy(num16 * ((float)Math.PI * 2f) / 14f + num14);
                             vector7 *= 0.2f * (float)num15;
                             obj3.position = center3 + vector7 * vector6;
                             obj3.velocity = vector7 + new Vector2(0f, gravDir * 4f);
                             obj3.noGravity = true;
                             obj3.scale = 1f + Main.rand.NextFloat() * 0.8f;
                             obj3.fadeIn = Main.rand.NextFloat() * 2f;
                             obj3.shader = GameShaders.Armor.GetSecondaryShader(cMount, this);
                         }
                     }
                 }
                 else if (flag10)
                 {
                     isPerformingJump_Santank = true;
                     int num17 = height;
                     if (gravDir == -1f)
                     {
                         num17 = 0;
                     }
                     SoundEngine.PlaySound(16, (int)position.X, (int)position.Y);
                     velocity.Y = (0f - jumpSpeed) * gravDir;
                     jump = jumpHeight * 2;
                     for (int num18 = 0; num18 < 15; num18++)
                     {
                         int num19 = Dust.NewDust(new Vector2(position.X - 34f, position.Y + (float)num17 - 16f), 102, 32, 4, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 100, new Color(250, 230, 230, 150), 1.5f);
                         Main.dust[num19].velocity.X = Main.dust[num19].velocity.X * 0.5f - velocity.X * 0.1f;
                         Main.dust[num19].velocity.Y = Main.dust[num19].velocity.Y * 0.5f - velocity.Y * 0.3f;
                         Main.dust[num19].noGravity = true;
                         num19 = Dust.NewDust(new Vector2(position.X - 34f, position.Y + (float)num17 - 16f), 102, 32, 6, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 20, default(Color), 1.5f);
                         Main.dust[num19].velocity.Y -= 1f;
                         if (num18 % 2 == 0)
{
                             Main.dust[num19].fadeIn = Main.rand.NextFloat() * 2f;
                         }
                     }
                     float y = base.Bottom.Y - 22f;
                     for (int num20 = 0; num20 < 3; num20++)
                     {
                         Vector2 vector8 = base.Center;
                         switch (num20)
{
                         case 0:
                             vector8 = new Vector2(base.Center.X - 16f, y);
                             break;
                         case 1:
                             vector8 = new Vector2(position.X - 36f, y);
                             break;
                         case 2:
                             vector8 = new Vector2(base.Right.X + 4f, y);
                             break;
                         }
                         int num21 = Gore.NewGore(vector8, new Vector2(0f - velocity.X, 0f - velocity.Y), Main.rand.Next(61, 63));
                         Main.gore[num21].velocity *= 0.1f;
                         Main.gore[num21].velocity.X -= velocity.X * 0.1f;
                         Main.gore[num21].velocity.Y -= velocity.Y * 0.05f;
                         Main.gore[num21].velocity += Main.rand.NextVector2Circular(1f, 1f) * 0.5f;
                     }
                 }
                 else
                 {
                     isPerformingJump_Cloud = true;
                     int num22 = height;
                     if (gravDir == -1f)
                     {
                         num22 = 0;
                     }
                     SoundEngine.PlaySound(16, (int)position.X, (int)position.Y);
                     velocity.Y = (0f - jumpSpeed) * gravDir;
                     jump = (int)((double)jumpHeight * 0.75);
                     for (int num23 = 0; num23 < 10; num23++)
                     {
                         int num24 = Dust.NewDust(new Vector2(position.X - 34f, position.Y + (float)num22 - 16f), 102, 32, 16, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 100, default(Color), 1.5f);
                         Main.dust[num24].velocity.X = Main.dust[num24].velocity.X * 0.5f - velocity.X * 0.1f;
                         Main.dust[num24].velocity.Y = Main.dust[num24].velocity.Y * 0.5f - velocity.Y * 0.3f;
                     }
                     int num25 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 16f, position.Y + (float)num22 - 16f), new Vector2(0f - velocity.X, 0f - velocity.Y), Main.rand.Next(11, 14));
                     Main.gore[num25].velocity.X = Main.gore[num25].velocity.X * 0.1f - velocity.X * 0.1f;
                     Main.gore[num25].velocity.Y = Main.gore[num25].velocity.Y * 0.1f - velocity.Y * 0.05f;
                     num25 = Gore.NewGore(new Vector2(position.X - 36f, position.Y + (float)num22 - 16f), new Vector2(0f - velocity.X, 0f - velocity.Y), Main.rand.Next(11, 14));
                     Main.gore[num25].velocity.X = Main.gore[num25].velocity.X * 0.1f - velocity.X * 0.1f;
                     Main.gore[num25].velocity.Y = Main.gore[num25].velocity.Y * 0.1f - velocity.Y * 0.05f;
                     num25 = Gore.NewGore(new Vector2(position.X + (float)width + 4f, position.Y + (float)num22 - 16f), new Vector2(0f - velocity.X, 0f - velocity.Y), Main.rand.Next(11, 14));
                     Main.gore[num25].velocity.X = Main.gore[num25].velocity.X * 0.1f - velocity.X * 0.1f;
                     Main.gore[num25].velocity.Y = Main.gore[num25].velocity.Y * 0.1f - velocity.Y * 0.05f;
                 }
             }
             releaseJump = false;
         }
         else
         {
             jump = 0;
             releaseJump = true;
             rocketRelease = true;
         }
     }
References Entity.active, GameShaders.Armor, Collision.CanHit(), MountID.Sets.Cart, Color, NPC.dontTakeDamage, Main.dust, Dust.fadeIn, NPC.friendly, NPC.getRect(), ArmorShaderDataSet.GetSecondaryShader(), Main.gore, Entity.height, NPC.immune, SoundID.Item16, SoundID.Item168, Main.myPlayer, Dust.NewDust(), Gore.NewGore(), UnifiedRandom.Next(), Dust.noGravity, NPC.noTileCollide, Main.npc, SoundEngine.PlaySound(), Dust.position, Entity.position, Main.rand, Dust.scale, Dust.shader, Dust.velocity, Gore.velocity, and Entity.width.