Terraria: Player.ItemCheck_UseCombatBook
ItemCheck_UseCombatBook()
void Player.ItemCheck_UseCombatBook (Item sItem) inline private
     {
         if (!NPC.combatBookWasUsed && sItem.type == 4382 && itemAnimation > 0 && ItemTimeIsZero)
         {
             ApplyItemTime(sItem);
             if (Main.netMode == 0)
             {
                 NPC.combatBookWasUsed = true;
                 Main.NewText(Language.GetTextValue("Misc.CombatBookUsed"), 50, byte.MaxValue, 130);
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, -11f);
             }
         }
         if (!NPC.combatBookVolumeTwoWasUsed && sItem.type == 5336 && itemAnimation > 0 && ItemTimeIsZero)
         {
             ApplyItemTime(sItem);
             if (Main.netMode == 0)
             {
                 NPC.combatBookVolumeTwoWasUsed = true;
                 Main.NewText(Language.GetTextValue("Misc.CombatBookVolumeTwoUsed"), 50, byte.MaxValue, 130);
             }
             else
             {
                 NetMessage.SendData(61, -1, -1, null, whoAmI, -17f);
             }
         }
     }
References NPC.combatBookVolumeTwoWasUsed, NPC.combatBookWasUsed, Language.GetTextValue(), Main.netMode, Main.NewText(), NetMessage.SendData(), and Item.type.