Terraria: Player.VolatileGelatin
VolatileGelatin()
void Player.VolatileGelatin (Item sourceItem) inline
     {
         if (Main.myPlayer != whoAmI)
         {
             return;
         }
         volatileGelatinCounter++;
         if (volatileGelatinCounter <= 40)
         {
             return;
         }
         volatileGelatinCounter = 0;
         int damage = 65;
         float knockBack = 7f;
         float num = 640f;
         NPC nPC = null;
         for (int i = 0; i < 200; i++)
         {
             NPC nPC2 = Main.npc[i];
             if (nPC2 != null && nPC2.active && nPC2.CanBeChasedBy(this) && Collision.CanHit(this, nPC2))
             {
                 float num2 = Vector2.Distance(nPC2.Center, base.Center);
                 if (num2 < num)
                 {
                     num = num2;
                     nPC = nPC2;
                 }
             }
         }
         if (nPC != null)
         {
             Vector2 v = nPC.Center - base.Center;
             v = v.SafeNormalize(Vector2.Zero) * 12f;
             v.Y -= 1.3f;
             Projectile.NewProjectile(GetProjectileSource_Accessory(sourceItem), base.Center.X, base.Center.Y, v.X, v.Y, 937, damage, knockBack, whoAmI);
         }
     }
References Entity.active, NPC.CanBeChasedBy(), Collision.CanHit(), Entity.Center, Entity.Distance(), Main.myPlayer, Projectile.NewProjectile(), and Main.npc.