Terraria: Player.HorizontalMovement
HorizontalMovement()
void Player.HorizontalMovement () inline
     {
         if (chilled)
         {
             accRunSpeed = maxRunSpeed;
         }
         bool flag = (itemAnimation == 0 || inventory[selectedItem].useTurn) && mount.AllowDirectionChange;
         bool flag2 = controlLeft || controlRight;
         float num = (accRunSpeed + maxRunSpeed) / 2f;
         float num2 = 0f;
         bool flag3 = false;
         if (flag2 && mount.Active && mount.Type == 43 && velocity.Y == 0f && !controlJump)
         {
             SoundEngine.PlaySound(SoundID.Item168, base.Center);
             float num3 = jumpSpeed * gravDir * 0.5f;
             if (num3 < 2f)
             {
                 num3 = 2f;
             }
             num3 += 0.01f;
             velocity.Y = 0f - num3;
             jump = jumpHeight;
             fullRotation = 0f;
             return;
         }
         if (windPushed && !isLockedToATile && !(mount.Active && velocity.Y == 0f && flag2))
         {
             num2 = (float)Math.Sign(Main.windSpeedCurrent) * 0.06f;
             if (Math.Abs(Main.windSpeedCurrent) > 0.5f)
             {
                 num2 *= 1.37f;
             }
             if (velocity.Y != 0f)
             {
                 num2 *= 1.5f;
             }
             if (flag2)
             {
                 num2 *= 0.8f;
                 float num4 = 0.072f;
                 num2 = MathHelper.Clamp(num2, 0f - num4, num4);
             }
             flag3 = true;
             if (Math.Sign(direction) != Math.Sign(num2))
             {
                 num -= Math.Abs(num2) * 40f;
             }
         }
         if (trackBoost != 0f)
         {
             velocity.X += trackBoost;
             trackBoost = 0f;
             if (velocity.X < 0f)
             {
                 if (velocity.X < 0f - maxRunSpeed)
                 {
                     velocity.X = 0f - maxRunSpeed;
                 }
             }
             else if (velocity.X > maxRunSpeed)
             {
                 velocity.X = maxRunSpeed;
             }
         }
         if (controlLeft && velocity.X > 0f - maxRunSpeed)
         {
             if (!mount.Active || !mount.Cart || velocity.Y == 0f)
             {
                 if (velocity.X > runSlowdown)
                 {
                     velocity.X -= runSlowdown;
                 }
                 velocity.X -= runAcceleration;
             }
             if (onWrongGround)
             {
                 if (velocity.X < 0f - runSlowdown)
                 {
                     velocity.X += runSlowdown;
                 }
                 else
                 {
                     velocity.X = 0f;
                 }
             }
             if (mount.Active && mount.Cart && !onWrongGround)
             {
                 if (velocity.X < 0f && flag)
                 {
                     direction = -1;
                 }
                 else if (itemAnimation <= 0 && velocity.Y == 0f)
                 {
                     SoundEngine.PlaySound(SoundID.Item55, (int)position.X + width / 2, (int)position.Y + height / 2);
                     DelegateMethods.Minecart.rotation = fullRotation;
                     DelegateMethods.Minecart.rotationOrigin = fullRotationOrigin;
                     if ((double)Math.Abs(velocity.X) > (double)maxRunSpeed * 0.66)
                     {
                         if (Main.rand.Next(2) == 0)
{
                             Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.66f, width, height, 1);
                         }
                         if (Main.rand.Next(2) == 0)
{
                             Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.33f, width, height, 1);
                         }
                         if (Main.rand.Next(2) == 0)
{
                             Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                         }
                     }
                     else if ((double)Math.Abs(velocity.X) > (double)maxRunSpeed * 0.33)
                     {
                         if (Main.rand.Next(3) != 0)
{
                             Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.5f, width, height, 1);
                         }
                         if (Main.rand.Next(3) != 0)
{
                             Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                         }
                     }
                     else
                     {
                         Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                     }
                 }
             }
             else if (!sandStorm && (itemAnimation == 0 || inventory[selectedItem].useTurn) && mount.AllowDirectionChange)
             {
                 direction = -1;
             }
         }
         else if (controlRight && velocity.X < maxRunSpeed)
         {
             if (!mount.Active || !mount.Cart || velocity.Y == 0f)
             {
                 if (velocity.X < 0f - runSlowdown)
                 {
                     velocity.X += runSlowdown;
                 }
                 velocity.X += runAcceleration;
             }
             if (onWrongGround)
             {
                 if (velocity.X > runSlowdown)
                 {
                     velocity.X -= runSlowdown;
                 }
                 else
                 {
                     velocity.X = 0f;
                 }
             }
             if (mount.Active && mount.Cart && !onWrongGround)
             {
                 if (velocity.X > 0f && flag)
                 {
                     direction = 1;
                 }
                 else if (itemAnimation <= 0 && velocity.Y == 0f)
                 {
                     SoundEngine.PlaySound(SoundID.Item55, (int)position.X + width / 2, (int)position.Y + height / 2);
                     DelegateMethods.Minecart.rotation = fullRotation;
                     DelegateMethods.Minecart.rotationOrigin = fullRotationOrigin;
                     if ((double)Math.Abs(velocity.X) > (double)maxRunSpeed * 0.66)
                     {
                         if (Main.rand.Next(2) == 0)
{
                             Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.66f, width, height, 1);
                         }
                         if (Main.rand.Next(2) == 0)
{
                             Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.33f, width, height, 1);
                         }
                         if (Main.rand.Next(2) == 0)
{
                             Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                         }
                     }
                     else if ((double)Math.Abs(velocity.X) > (double)maxRunSpeed * 0.33)
                     {
                         if (Main.rand.Next(3) != 0)
{
                             Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.5f, width, height, 1);
                         }
                         if (Main.rand.Next(3) != 0)
{
                             Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                         }
                     }
                     else
                     {
                         Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                     }
                 }
             }
             else if (!sandStorm && (itemAnimation == 0 || inventory[selectedItem].useTurn) && mount.AllowDirectionChange)
             {
                 direction = 1;
             }
         }
         else if (controlLeft && velocity.X > 0f - accRunSpeed && dashDelay >= 0)
         {
             if (mount.Active && mount.Cart)
             {
                 if (velocity.X < 0f)
                 {
                     direction = -1;
                 }
             }
             else if ((itemAnimation == 0 || inventory[selectedItem].useTurn) && mount.AllowDirectionChange)
             {
                 direction = -1;
             }
             if (velocity.Y == 0f || wingsLogic > 0 || mount.CanFly())
             {
                 if (velocity.X > runSlowdown)
                 {
                     velocity.X -= runSlowdown;
                 }
                 velocity.X -= runAcceleration * 0.2f;
                 if (wingsLogic > 0)
                 {
                     velocity.X -= runAcceleration * 0.2f;
                 }
             }
             if (onWrongGround)
             {
                 if (velocity.X < runSlowdown)
                 {
                     velocity.X += runSlowdown;
                 }
                 else
                 {
                     velocity.X = 0f;
                 }
             }
             if (velocity.X < 0f - num && velocity.Y == 0f && !mount.Active)
             {
                 SpawnFastRunParticles();
             }
         }
         else if (controlRight && velocity.X < accRunSpeed && dashDelay >= 0)
         {
             if (mount.Active && mount.Cart)
             {
                 if (velocity.X > 0f)
                 {
                     direction = -1;
                 }
             }
             else if ((itemAnimation == 0 || inventory[selectedItem].useTurn) && mount.AllowDirectionChange)
             {
                 direction = 1;
             }
             if (velocity.Y == 0f || wingsLogic > 0 || mount.CanFly())
             {
                 if (velocity.X < 0f - runSlowdown)
                 {
                     velocity.X += runSlowdown;
                 }
                 velocity.X += runAcceleration * 0.2f;
                 if (wingsLogic > 0)
                 {
                     velocity.X += runAcceleration * 0.2f;
                 }
             }
             if (onWrongGround)
             {
                 if (velocity.X > runSlowdown)
                 {
                     velocity.X -= runSlowdown;
                 }
                 else
                 {
                     velocity.X = 0f;
                 }
             }
             if (velocity.X > num && velocity.Y == 0f && !mount.Active)
             {
                 SpawnFastRunParticles();
             }
         }
         else if (mount.Active && mount.Cart && Math.Abs(velocity.X) >= 1f)
         {
             if (onWrongGround)
             {
                 if (velocity.X > 0f)
                 {
                     if (velocity.X > runSlowdown)
                     {
                         velocity.X -= runSlowdown;
                     }
                     else
                     {
                         velocity.X = 0f;
                     }
                 }
                 else if (velocity.X < 0f)
                 {
                     if (velocity.X < 0f - runSlowdown)
                     {
                         velocity.X += runSlowdown;
                     }
                     else
                     {
                         velocity.X = 0f;
                     }
                 }
             }
             if (velocity.X > maxRunSpeed)
             {
                 velocity.X = maxRunSpeed;
             }
             if (velocity.X < 0f - maxRunSpeed)
             {
                 velocity.X = 0f - maxRunSpeed;
             }
         }
         else if (velocity.Y == 0f)
         {
             if (velocity.X > runSlowdown)
             {
                 velocity.X -= runSlowdown;
             }
             else if (velocity.X < 0f - runSlowdown)
             {
                 velocity.X += runSlowdown;
             }
             else
             {
                 velocity.X = 0f;
             }
         }
         else if (!PortalPhysicsEnabled)
         {
             if ((double)velocity.X > (double)runSlowdown * 0.5)
             {
                 velocity.X -= runSlowdown * 0.5f;
             }
             else if ((double)velocity.X < (double)(0f - runSlowdown) * 0.5)
             {
                 velocity.X += runSlowdown * 0.5f;
             }
             else
             {
                 velocity.X = 0f;
             }
         }
         if (flag3)
         {
             if (num2 < 0f && velocity.X > num2)
             {
                 velocity.X += num2;
                 if (velocity.X < num2)
                 {
                     velocity.X = num2;
                 }
             }
             if (num2 > 0f && velocity.X < num2)
             {
                 velocity.X += num2;
                 if (velocity.X > num2)
                 {
                     velocity.X = num2;
                 }
             }
         }
         bool flag4 = mount.Type == 40 || mount.Type == 41 || mount.Type == 42;
         if (mount.Active && (mount.Type == 10 || mount.Type == 47 || flag4) && Math.Abs(velocity.X) > mount.DashSpeed - mount.RunSpeed / 2f)
         {
             Rectangle rect = getRect();
             if (direction == 1)
             {
                 rect.Offset(width - 1, 0);
             }
             rect.Width = 2;
             rect.Inflate(6, 12);
             int num5 = 60;
             if (flag4)
             {
                 num5 = 30;
             }
             float damage = (float)num5 * minionDamage;
             float knockback = 10f;
             if (flag4)
             {
                 knockback = 7f;
             }
             int nPCImmuneTime = 30;
             int playerImmuneTime = 6;
             CollideWithNPCs(rect, damage, knockback, nPCImmuneTime, playerImmuneTime);
         }
         if (mount.Active && mount.Type == 44 && Math.Abs(velocity.X) > mount.DashSpeed - mount.RunSpeed / 4f)
         {
             Rectangle rect2 = getRect();
             if (direction == 1)
             {
                 rect2.Offset(width - 1, 0);
             }
             rect2.Width = 2;
             rect2.Inflate(6, 12);
             float damage2 = 100f * minionDamage;
             float knockback2 = 12f;
             int nPCImmuneTime2 = 30;
             int playerImmuneTime2 = 6;
             CollideWithNPCs(rect2, damage2, knockback2, nPCImmuneTime2, playerImmuneTime2);
         }
         if (mount.Active && mount.Type == 45 && Math.Abs(velocity.X) > mount.DashSpeed * 0.9f)
         {
             Rectangle rect3 = getRect();
             if (direction == 1)
             {
                 rect3.Offset(width - 1, 0);
             }
             rect3.Width = 2;
             rect3.Inflate(6, 12);
             float damage3 = 120f * minionDamage;
             float knockback3 = 12f;
             int nPCImmuneTime3 = 30;
             int playerImmuneTime3 = 6;
             CollideWithNPCs(rect3, damage3, knockback3, nPCImmuneTime3, playerImmuneTime3);
         }
         if (mount.Active && mount.Type == 14 && Math.Abs(velocity.X) > mount.RunSpeed / 2f)
         {
             Rectangle rect4 = getRect();
             if (direction == 1)
             {
                 rect4.Offset(width - 1, 0);
             }
             rect4.Width = 2;
             rect4.Inflate(6, 12);
             float damage4 = 90f * minionDamage;
             float knockback4 = 10f;
             int nPCImmuneTime4 = 30;
             int playerImmuneTime4 = 6;
             CollideWithNPCs(rect4, damage4, knockback4, nPCImmuneTime4, playerImmuneTime4);
         }
         if (mount.Active && mount.Type == 17 && Math.Abs(velocity.X) > mount.RunSpeed / 2f)
         {
             Rectangle rect5 = getRect();
             if (direction == 1)
             {
                 rect5.Offset(width - 1, 0);
             }
             rect5.Width = 2;
             rect5.Inflate(6, 12);
             float damage5 = 40f * minionDamage;
             float knockback5 = 10f;
             int nPCImmuneTime5 = 30;
             int playerImmuneTime5 = 12;
             CollideWithNPCs(rect5, damage5, knockback5, nPCImmuneTime5, playerImmuneTime5);
         }
         TryUsingDiggerCart();
         if (HeldItem.type == 4049 && whoAmI == Main.myPlayer)
         {
             MowTheLawn();
         }
     }
References SoundID.Item168, SoundID.Item55, Main.myPlayer, UnifiedRandom.Next(), SoundEngine.PlaySound(), Main.rand, DelegateMethods.Minecart.rotation, DelegateMethods.Minecart.rotationOrigin, Item.type, Minecart.WheelSparks(), and Main.windSpeedCurrent.