Terraria: Player.GetHairColor
GetHairColor()
Color Player.GetHairColor (bool useLighting = true) inline
     {
         Color color = Lighting.GetColor((int)((double)position.X + (double)width * 0.5) / 16, (int)(((double)position.Y + (double)height * 0.25) / 16.0));
         return GameShaders.Hair.GetColor(hairDye, this, useLighting ? color : Color.White);
     }
References Color, Lighting.GetColor(), HairShaderDataSet.GetColor(), and GameShaders.Hair.
Referenced by PlayerDrawHeadSet.BoringSetup(), and PlayerDrawSet.BoringSetup().