Terraria: Player.TileInteractionsCheckLongDistance
TileInteractionsCheckLongDistance()
void Player.TileInteractionsCheckLongDistance (int myX, int myY) inline private
     {
         if (!WorldGen.InWorld(myX, myY, 10) || Main.tile[myX, myY] == null || !Main.tile[myX, myY].active())
         {
             return;
         }
         if (TileID.Sets.BasicChest[Main.tile[myX, myY].type])
         {
             TileInteractionsMouseOver_Containers(myX, myY);
             if (cursorItemIconText == "")
             {
                 cursorItemIconEnabled = false;
                 cursorItemIconID = 0;
             }
         }
         if (Main.tile[myX, myY].type == 88)
         {
             Tile tile = Main.tile[myX, myY];
             int num = myY;
             int x = myX - tile.frameX % 54 / 18;
             if (tile.frameY % 36 != 0)
             {
                 num--;
             }
             int num2 = Chest.FindChest(x, num);
             cursorItemIconID = -1;
             if (num2 < 0)
             {
                 cursorItemIconText = Lang.dresserType[0].Value;
             }
             else
             {
                 if (Main.chest[num2].name != "")
                 {
                     cursorItemIconText = Main.chest[num2].name;
                 }
                 else
                 {
                     cursorItemIconText = Lang.dresserType[tile.frameX / 54].Value;
                 }
                 if (cursorItemIconText == Lang.dresserType[tile.frameX / 54].Value)
                 {
                     cursorItemIconID = Chest.dresserTypeToIcon[tile.frameX / 54];
                     cursorItemIconText = "";
                 }
             }
             noThrow = 2;
             cursorItemIconEnabled = true;
             if (cursorItemIconText == "")
             {
                 cursorItemIconEnabled = false;
                 cursorItemIconID = 0;
             }
         }
         if (Main.tileSign[Main.tile[myX, myY].type])
         {
             noThrow = 2;
             int num3 = Main.tile[myX, myY].frameX / 18;
             int num4 = Main.tile[myX, myY].frameY / 18;
             num3 %= 2;
             int num5 = myX - num3;
             int num6 = myY - num4;
             Main.signBubble = true;
             Main.signX = num5 * 16 + 16;
             Main.signY = num6 * 16;
             int num7 = Sign.ReadSign(num5, num6, CreateIfMissing: false);
             if (num7 != -1 && tileTargetX >= num5 && tileTargetY >= num6 && tileTargetX <= num5 + 1 && tileTargetY <= num6 + 1)
             {
                 Main.signHover = num7;
                 cursorItemIconEnabled = false;
                 cursorItemIconID = -1;
             }
         }
     }
References Tile.active(), TileID.Sets.BasicChest, Main.chest, Lang.dresserType, Chest.dresserTypeToIcon, Chest.FindChest(), Tile.frameX, Tile.frameY, WorldGen.InWorld(), Chest.name, Sign.ReadSign(), Main.signBubble, Main.signHover, Main.signX, Main.signY, Main.tile, Main.tileSign, Tile.type, and LocalizedText.Value.