Terraria: Player.ItemCheck_MeleeHitPVP
ItemCheck_MeleeHitPVP()
void Player.ItemCheck_MeleeHitPVP (Item sItem, Rectangle itemRectangle, int damage, float knockBack) inline private
     {
         if (!hostile)
         {
             return;
         }
         for (int i = 0; i < 255; i++)
         {
             Player player = Main.player[i];
             if (i == whoAmI || !player.active || !player.hostile || player.immune || player.dead || (team != 0 && team == player.team) || !itemRectangle.Intersects(player.Hitbox) || !CanHit(player))
             {
                 continue;
             }
             bool flag = false;
             if (Main.rand.Next(1, 101) <= 10)
             {
                 flag = true;
             }
             int num = Main.DamageVar(damage, luck);
             StatusToPlayerPvP(sItem.type, i);
             OnHit(player.Center.X, player.Center.Y, player);
             PlayerDeathReason playerDeathReason = PlayerDeathReason.ByPlayer(whoAmI);
             int num2 = (int)player.Hurt(playerDeathReason, num, direction, pvp: true, quiet: false, flag);
             if (inventory[selectedItem].type == 3211)
             {
                 Vector2 vector = new Vector2(direction * 100 + Main.rand.Next(-25, 26), Main.rand.Next(-75, 76));
                 vector.Normalize();
                 vector *= (float)Main.rand.Next(30, 41) * 0.1f;
                 Vector2 vector2 = new Vector2(itemRectangle.X + Main.rand.Next(itemRectangle.Width), itemRectangle.Y + Main.rand.Next(itemRectangle.Height));
                 vector2 = (vector2 + player.Center * 2f) / 3f;
                 Projectile.NewProjectile(GetProjectileSource_Item(HeldItem), vector2.X, vector2.Y, vector.X, vector.Y, 524, (int)((double)damage * 0.7), knockBack * 0.7f, whoAmI);
             }
             if (sItem.type == 5097)
             {
                 BatBat_TryLifeLeeching(player);
             }
             if (beetleOffense)
             {
                 beetleCounter += num2;
                 beetleCountdown = 0;
             }
             if (meleeEnchant == 7)
             {
                 Projectile.NewProjectile(GetProjectileSource_Misc(8), player.Center.X, player.Center.Y, player.velocity.X, player.velocity.Y, 289, 0, 0f, whoAmI);
             }
             if (sItem.type == 1123)
             {
                 int num3 = Main.rand.Next(1, 4);
                 if (strongBees && Main.rand.Next(3) == 0)
                 {
                     num3++;
                 }
                 for (int j = 0; j < num3; j++)
                 {
                     float num4 = (float)(direction * 2) + (float)Main.rand.Next(-35, 36) * 0.02f;
                     float num5 = (float)Main.rand.Next(-35, 36) * 0.02f;
                     num4 *= 0.2f;
                     num5 *= 0.2f;
                     int num6 = Projectile.NewProjectile(GetProjectileSource_Item(sItem), itemRectangle.X + itemRectangle.Width / 2, itemRectangle.Y + itemRectangle.Height / 2, num4, num5, beeType(), beeDamage(num / 3), beeKB(0f), whoAmI);
                     Main.projectile[num6].melee = true;
                 }
             }
             if (inventory[selectedItem].type == 3106)
             {
                 stealth = 1f;
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(84, -1, -1, null, whoAmI);
                 }
             }
             if (Main.netMode != 0)
             {
                 NetMessage.SendPlayerHurt(i, playerDeathReason, num, direction, flag, pvp: true, -1);
             }
             ApplyAttackCooldown();
         }
     }
References Entity.active, PlayerDeathReason.ByPlayer(), Entity.Center, Main.DamageVar(), dead, Entity.Hitbox, hostile, Hurt(), immune, Projectile.melee, Main.netMode, Projectile.NewProjectile(), UnifiedRandom.Next(), Main.player, Main.projectile, Main.rand, NetMessage.SendData(), NetMessage.SendPlayerHurt(), team, Item.type, and Entity.velocity.