Terraria: Player.MowTheLawn
MowTheLawn()
void Player.MowTheLawn () inline private
     {
         if (miscCounter % 2 != 0 || velocity.Y != 0f || grappling[0] != -1 || itemAnimation < 1)
         {
             return;
         }
         Vector2 vector = base.Center + new Vector2(direction * 38, (float)(height / 2 + 4) * gravDir);
         float num = 1f - (float)itemAnimation / (float)itemAnimationMax;
         num *= 2f;
         num = ((!(num < 1f)) ? (num - 1f) : (1f - num));
         Vector2 value = vector + new Vector2(direction * -16, gravDir * -4f);
         Vector2 value2 = vector + new Vector2(direction * -6, gravDir * -4f);
         Dust dust = Dust.NewDustDirect(Vector2.Lerp(value, value2, num), 0, 0, 31, 0f, (0f - gravDir) * 0.25f, 127);
         dust.scale = 0.9f;
         dust.position -= new Vector2(4f);
         if (dust.velocity.Y > 0f)
         {
             dust.velocity.Y *= -1f;
         }
         dust.velocity *= 0.25f;
         Rectangle rectangle = Utils.CenteredRectangle(vector, new Vector2(8f, 20f));
         if (velocity.X * (float)direction > 0f || velocity.Y * gravDir > 0f)
         {
             Rectangle myRect = rectangle;
             myRect.Height -= 4;
             myRect.Y += 2;
             float damage = 8f;
             float knockback = 2f;
             int nPCImmuneTime = 12;
             int playerImmuneTime = 6;
             CollideWithNPCs(myRect, damage, knockback, nPCImmuneTime, playerImmuneTime);
         }
         rectangle.X -= direction * 10;
         if (whoAmI == Main.myPlayer)
         {
             bool[] shouldIgnore = ItemCheck_GetTileCutIgnoreList(HeldItem);
             ItemCheck_CutTiles(HeldItem, rectangle, shouldIgnore);
             MowGrassTile(vector);
             if (!WorldGen.SolidTile(Framing.GetTileSafely(vector.ToTileCoordinates())))
             {
                 MowGrassTile(vector + new Vector2(0f, 16f * gravDir));
             }
         }
     }
References Utils.CenteredRectangle(), Framing.GetTileSafely(), Main.myPlayer, Dust.NewDustDirect(), Dust.position, Dust.scale, WorldGen.SolidTile(), and Dust.velocity.