Terraria: Player.QuickMinecart
QuickMinecart()
void Player.QuickMinecart () inline private
     {
         int num = 0;
         int value = (int)(position.X / 16f) - tileRangeX - num + 1;
         int value2 = (int)((position.X + (float)width) / 16f) + tileRangeX + num - 1;
         int value3 = (int)(position.Y / 16f) - tileRangeY - num + 1;
         int value4 = (int)((position.Y + (float)height) / 16f) + tileRangeY + num - 2;
         int num2 = Utils.Clamp(value, 10, Main.maxTilesX - 10);
         value2 = Utils.Clamp(value2, 10, Main.maxTilesX - 10);
         value3 = Utils.Clamp(value3, 10, Main.maxTilesY - 10);
         List<Point> list = Collision.GetTilesIn(BottomRight: new Vector2(value2 + 1, Utils.Clamp(value4, 10, Main.maxTilesY - 10) + 1) * 16f, TopLeft: new Vector2(num2, value3) * 16f);
         if (list.Count <= 0)
         {
             return;
         }
         Point? point = null;
         _ = base.Hitbox;
         for (int i = 0; i < list.Count; i++)
         {
             Point point2 = list[i];
             Tile tileSafely = Framing.GetTileSafely(point2.X, point2.Y);
             if (tileSafely.active() && tileSafely.type == 314)
             {
                 Vector2 vector = list[i].ToVector2() * 16f + new Vector2(8f);
                 if (!point.HasValue || (Distance(vector) < Distance(point.Value.ToVector2() * 16f + new Vector2(8f)) && Collision.CanHitLine(base.Center, 0, 0, vector, 0, 0)))
                 {
                     point = list[i];
                 }
             }
         }
         if (point.HasValue)
         {
             LaunchMinecartHook(point.Value.X, point.Value.Y);
         }
     }
References Tile.active(), Collision.CanHitLine(), Framing.GetTileSafely(), Collision.GetTilesIn(), Main.maxTilesX, Main.maxTilesY, and Tile.type.