Terraria: Player.FloorVisuals
FloorVisuals()
void Player.FloorVisuals (bool Falling) inline
     {
         int num = (int)((position.X + (float)(width / 2)) / 16f);
         int num2 = (int)((position.Y + (float)height) / 16f);
         if (gravDir == -1f)
         {
             num2 = (int)(position.Y - 0.1f) / 16;
         }
         Tile floorTile = GetFloorTile(num, num2);
         int num3 = -1;
         if (floorTile != null)
         {
             num3 = floorTile.type;
         }
         if (num3 <= -1)
         {
             ResetFloorFlags();
             return;
         }
         sticky = num3 == 229;
         slippy = TileID.Sets.IceSkateSlippery[num3];
         slippy2 = num3 == 197;
         powerrun = num3 == 198;
         runningOnSand = TileID.Sets.Conversion.Sand[num3] || TileID.Sets.Conversion.Sandstone[num3] || TileID.Sets.Conversion.HardenedSand[num3];
         if (num3 == 666 && whoAmI == Main.myPlayer)
         {
             AddBuff(120, 180);
         }
         if (Main.tile[num - 1, num2].slope() != 0 || Main.tile[num, num2].slope() != 0 || Main.tile[num + 1, num2].slope() != 0)
         {
             num3 = -1;
         }
         if (!wet && !mount.Cart)
         {
             MakeFloorDust(Falling, num3, floorTile.color());
         }
     }
References Tile.color(), TileID.Sets.Conversion.HardenedSand, TileID.Sets.IceSkateSlippery, Main.myPlayer, TileID.Sets.Conversion.Sand, TileID.Sets.Conversion.Sandstone, Tile.slope(), Main.tile, and Tile.type.
Referenced by Mount.UpdateFrame().