Terraria: Player.ItemCheck_UseWiringTools
ItemCheck_UseWiringTools()
void Player.ItemCheck_UseWiringTools (Item sItem) inline private
     {
         if ((sItem.type != 509 && sItem.type != 510 && sItem.type != 849 && sItem.type != 850 && sItem.type != 851 && sItem.type != 3612 && sItem.type != 3620 && sItem.type != 3625) || !(position.X / 16f - (float)tileRangeX - (float)sItem.tileBoost - (float)blockRange <= (float)tileTargetX) || !((position.X + (float)width) / 16f + (float)tileRangeX + (float)sItem.tileBoost - 1f + (float)blockRange >= (float)tileTargetX) || !(position.Y / 16f - (float)tileRangeY - (float)sItem.tileBoost - (float)blockRange <= (float)tileTargetY) || !((position.Y + (float)height) / 16f + (float)tileRangeY + (float)sItem.tileBoost - 2f + (float)blockRange >= (float)tileTargetY))
         {
             return;
         }
         if (!Main.GamepadDisableCursorItemIcon)
         {
             cursorItemIconEnabled = true;
             Main.ItemIconCacheUpdate(sItem.type);
         }
         if (!CanDoWireStuffHere(tileTargetX, tileTargetY) || itemAnimation <= 0 || !ItemTimeIsZero || !controlUseItem)
         {
             return;
         }
         int num = tileTargetX;
         int num2 = tileTargetY;
         if (sItem.type == 509)
         {
             int num3 = -1;
             for (int i = 0; i < 58; i++)
             {
                 if (inventory[i].stack > 0 && inventory[i].type == 530)
                 {
                     num3 = i;
                     break;
                 }
             }
             if (num3 >= 0 && WorldGen.PlaceWire(num, num2))
             {
                 inventory[num3].stack--;
                 if (inventory[num3].stack <= 0)
                 {
                     inventory[num3].SetDefaults();
                 }
                 ApplyItemTime(sItem);
                 NetMessage.SendData(17, -1, -1, null, 5, tileTargetX, tileTargetY);
             }
         }
         else if (sItem.type == 850)
         {
             int num4 = -1;
             for (int j = 0; j < 58; j++)
             {
                 if (inventory[j].stack > 0 && inventory[j].type == 530)
                 {
                     num4 = j;
                     break;
                 }
             }
             if (num4 >= 0 && WorldGen.PlaceWire2(num, num2))
             {
                 inventory[num4].stack--;
                 if (inventory[num4].stack <= 0)
                 {
                     inventory[num4].SetDefaults();
                 }
                 ApplyItemTime(sItem);
                 NetMessage.SendData(17, -1, -1, null, 10, tileTargetX, tileTargetY);
             }
         }
         if (sItem.type == 851)
         {
             int num5 = -1;
             for (int k = 0; k < 58; k++)
             {
                 if (inventory[k].stack > 0 && inventory[k].type == 530)
                 {
                     num5 = k;
                     break;
                 }
             }
             if (num5 >= 0 && WorldGen.PlaceWire3(num, num2))
             {
                 inventory[num5].stack--;
                 if (inventory[num5].stack <= 0)
                 {
                     inventory[num5].SetDefaults();
                 }
                 ApplyItemTime(sItem);
                 NetMessage.SendData(17, -1, -1, null, 12, tileTargetX, tileTargetY);
             }
         }
         if (sItem.type == 3612)
         {
             int num6 = -1;
             for (int l = 0; l < 58; l++)
             {
                 if (inventory[l].stack > 0 && inventory[l].type == 530)
                 {
                     num6 = l;
                     break;
                 }
             }
             if (num6 >= 0 && WorldGen.PlaceWire4(num, num2))
             {
                 inventory[num6].stack--;
                 if (inventory[num6].stack <= 0)
                 {
                     inventory[num6].SetDefaults();
                 }
                 ApplyItemTime(sItem);
                 NetMessage.SendData(17, -1, -1, null, 16, tileTargetX, tileTargetY);
             }
         }
         else if (sItem.type == 510)
         {
             if (WorldGen.KillActuator(num, num2))
             {
                 ApplyItemTime(sItem);
                 NetMessage.SendData(17, -1, -1, null, 9, tileTargetX, tileTargetY);
             }
             else if (WorldGen.KillWire4(num, num2))
             {
                 ApplyItemTime(sItem);
                 NetMessage.SendData(17, -1, -1, null, 17, tileTargetX, tileTargetY);
             }
             else if (WorldGen.KillWire3(num, num2))
             {
                 ApplyItemTime(sItem);
                 NetMessage.SendData(17, -1, -1, null, 13, tileTargetX, tileTargetY);
             }
             else if (WorldGen.KillWire2(num, num2))
             {
                 ApplyItemTime(sItem);
                 NetMessage.SendData(17, -1, -1, null, 11, tileTargetX, tileTargetY);
             }
             else if (WorldGen.KillWire(num, num2))
             {
                 ApplyItemTime(sItem);
                 NetMessage.SendData(17, -1, -1, null, 6, tileTargetX, tileTargetY);
             }
         }
         else if (sItem.type == 849 && sItem.stack > 0 && WorldGen.PlaceActuator(num, num2))
         {
             ApplyItemTime(sItem);
             NetMessage.SendData(17, -1, -1, null, 8, tileTargetX, tileTargetY);
             sItem.stack--;
             if (sItem.stack <= 0)
             {
                 sItem.SetDefaults();
             }
         }
         if (sItem.type == 3620)
         {
             Tile tile = Main.tile[num, num2];
             if (tile != null && tile.actuator())
             {
                 bool flag = tile.inActive();
                 if ((!ActuationRodLock || ActuationRodLockSetting == tile.inActive()) && Wiring.Actuate(num, num2) && flag != tile.inActive())
                 {
                     ActuationRodLock = true;
                     ActuationRodLockSetting = !tile.inActive();
                     ApplyItemTime(sItem);
                     NetMessage.SendData(17, -1, -1, null, 19, tileTargetX, tileTargetY);
                 }
             }
         }
         if (sItem.type == 3625)
         {
             Point point = new Point(tileTargetX, tileTargetY);
             ApplyItemTime(sItem);
             WiresUI.Settings.MultiToolMode toolMode = WiresUI.Settings.ToolMode;
             WiresUI.Settings.ToolMode &= ~WiresUI.Settings.MultiToolMode.Actuator;
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(109, -1, -1, null, point.X, point.Y, point.X, point.Y, (int)WiresUI.Settings.ToolMode);
             }
             else
             {
                 Wiring.MassWireOperation(point, point, this);
             }
             WiresUI.Settings.ToolMode = toolMode;
         }
     }
References Wiring.Actuate(), Tile.actuator(), Main.GamepadDisableCursorItemIcon, Tile.inActive(), Main.ItemIconCacheUpdate(), WorldGen.KillActuator(), WorldGen.KillWire(), WorldGen.KillWire2(), WorldGen.KillWire3(), WorldGen.KillWire4(), Wiring.MassWireOperation(), Main.netMode, WorldGen.PlaceActuator(), WorldGen.PlaceWire(), WorldGen.PlaceWire2(), WorldGen.PlaceWire3(), WorldGen.PlaceWire4(), NetMessage.SendData(), Item.SetDefaults(), Item.stack, Main.tile, Item.tileBoost, WiresUI.Settings.ToolMode, and Item.type.