Terraria: Player.SellItem
SellItem()
bool Player.SellItem (Item item, int stack = -1) inline
     {
         GetItemExpectedPrice(item, out var calcForSelling, out var calcForBuying);
         if (calcForSelling <= 0)
         {
             return false;
         }
         if (stack == -1)
         {
             stack = item.stack;
         }
         Item[] array = new Item[58];
         for (int i = 0; i < 58; i++)
         {
             array[i] = new Item();
             array[i] = inventory[i].Clone();
         }
         long num = calcForSelling / 5;
         if (num < 1)
         {
             num = 1L;
         }
         long num2 = num;
         num *= stack;
         int amount = Main.shopSellbackHelper.GetAmount(item);
         if (amount > 0)
         {
             num += (-num2 + calcForBuying) * Math.Min(amount, item.stack);
         }
         bool flag = false;
         while (num >= 1000000 && !flag)
         {
             int num3 = -1;
             for (int num4 = 53; num4 >= 0; num4--)
             {
                 if (num3 == -1 && (inventory[num4].type == 0 || inventory[num4].stack == 0))
                 {
                     num3 = num4;
                 }
                 while (inventory[num4].type == 74 && inventory[num4].stack < inventory[num4].maxStack && num >= 1000000)
                 {
                     inventory[num4].stack++;
                     num -= 1000000;
                     DoCoins(num4);
                     if (inventory[num4].stack == 0 && num3 == -1)
                     {
                         num3 = num4;
                     }
                 }
             }
             if (num >= 1000000)
             {
                 if (num3 == -1)
                 {
                     flag = true;
                     continue;
                 }
                 inventory[num3].SetDefaults(74);
                 num -= 1000000;
             }
         }
         while (num >= 10000 && !flag)
         {
             int num5 = -1;
             for (int num6 = 53; num6 >= 0; num6--)
             {
                 if (num5 == -1 && (inventory[num6].type == 0 || inventory[num6].stack == 0))
                 {
                     num5 = num6;
                 }
                 while (inventory[num6].type == 73 && inventory[num6].stack < inventory[num6].maxStack && num >= 10000)
                 {
                     inventory[num6].stack++;
                     num -= 10000;
                     DoCoins(num6);
                     if (inventory[num6].stack == 0 && num5 == -1)
                     {
                         num5 = num6;
                     }
                 }
             }
             if (num >= 10000)
             {
                 if (num5 == -1)
                 {
                     flag = true;
                     continue;
                 }
                 inventory[num5].SetDefaults(73);
                 num -= 10000;
             }
         }
         while (num >= 100 && !flag)
         {
             int num7 = -1;
             for (int num8 = 53; num8 >= 0; num8--)
             {
                 if (num7 == -1 && (inventory[num8].type == 0 || inventory[num8].stack == 0))
                 {
                     num7 = num8;
                 }
                 while (inventory[num8].type == 72 && inventory[num8].stack < inventory[num8].maxStack && num >= 100)
                 {
                     inventory[num8].stack++;
                     num -= 100;
                     DoCoins(num8);
                     if (inventory[num8].stack == 0 && num7 == -1)
                     {
                         num7 = num8;
                     }
                 }
             }
             if (num >= 100)
             {
                 if (num7 == -1)
                 {
                     flag = true;
                     continue;
                 }
                 inventory[num7].SetDefaults(72);
                 num -= 100;
             }
         }
         while (num >= 1 && !flag)
         {
             int num9 = -1;
             for (int num10 = 53; num10 >= 0; num10--)
             {
                 if (num9 == -1 && (inventory[num10].type == 0 || inventory[num10].stack == 0))
                 {
                     num9 = num10;
                 }
                 while (inventory[num10].type == 71 && inventory[num10].stack < inventory[num10].maxStack && num >= 1)
                 {
                     inventory[num10].stack++;
                     num--;
                     DoCoins(num10);
                     if (inventory[num10].stack == 0 && num9 == -1)
                     {
                         num9 = num10;
                     }
                 }
             }
             if (num >= 1)
             {
                 if (num9 == -1)
                 {
                     flag = true;
                     continue;
                 }
                 inventory[num9].SetDefaults(71);
                 num--;
             }
         }
         if (flag)
         {
             for (int j = 0; j < 58; j++)
             {
                 inventory[j] = array[j].Clone();
             }
             return false;
         }
         return true;
     }
References Item.Clone(), ItemShopSellbackHelper.GetAmount(), L, Main.shopSellbackHelper, and Item.stack.
Referenced by ItemSlot.LeftClick(), and ItemSlot.SellOrTrash().