Terraria: Player.RemoveAllGrapplingHooks
RemoveAllGrapplingHooks()
void Player.RemoveAllGrapplingHooks () inline
     {
         ClearGrapplingBlacklist();
         grappling[0] = -1;
         grapCount = 0;
         for (int i = 0; i < 1000; i++)
         {
             if (Main.projectile[i].active && Main.projectile[i].owner == whoAmI && Main.projectile[i].aiStyle == 7)
             {
                 Main.projectile[i].Kill();
             }
         }
     }
References Entity.active, Projectile.aiStyle, Projectile.Kill(), Projectile.owner, and Main.projectile.
Referenced by PlayerSittingHelper.SitDown(), and PlayerSleepingHelper.StartSleeping().