Terraria: Player.UpdateHairDyeDust
UpdateHairDyeDust()
void Player.UpdateHairDyeDust () inline
     {
         if (Main.netMode != 2 && !Main.gamePaused && !dead && !ghost && !stoned && !frozen && hairDye == ContentSamples.CommonlyUsedContentSamples.TeamDyeShaderIndex)
         {
             if (Main.rand.Next(45) == 0)
             {
                 int type = Main.rand.Next(139, 143);
                 int num = Dust.NewDust(position, width, 8, type, 0f, 0f, 0, default(Color), 1.2f);
                 Main.dust[num].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.dust[num].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.dust[num].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.dust[num].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.dust[num].velocity.Y -= 1f;
                 Main.dust[num].scale *= 0.7f + (float)Main.rand.Next(-30, 31) * 0.01f;
                 Main.dust[num].velocity += velocity * 0.2f;
             }
             if (Main.rand.Next(225) == 0)
             {
                 int type2 = Main.rand.Next(276, 283);
                 int num2 = Gore.NewGore(new Vector2(position.X + (float)Main.rand.Next(width), position.Y + (float)Main.rand.Next(8)), velocity, type2);
                 Main.gore[num2].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.gore[num2].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.gore[num2].scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                 Main.gore[num2].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.gore[num2].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.gore[num2].velocity.Y -= 1f;
                 Main.gore[num2].velocity += velocity * 0.2f;
             }
         }
     }
References Color, Main.dust, Main.gamePaused, Main.gore, Main.netMode, Dust.NewDust(), Gore.NewGore(), UnifiedRandom.Next(), Main.rand, Dust.scale, Gore.scale, ContentSamples.CommonlyUsedContentSamples.TeamDyeShaderIndex, Dust.velocity, and Gore.velocity.