Terraria: Player.CheckMana
CheckMana()
bool Player.CheckMana (int amount, bool pay = false, bool blockQuickMana = false) inline
     {
         int num = (int)((float)amount * manaCost);
         if (statMana >= num)
         {
             if (pay)
             {
                 statMana -= num;
             }
             return true;
         }
         if (manaFlower && !blockQuickMana)
         {
             QuickMana();
             if (statMana >= num)
             {
                 if (pay)
                 {
                     statMana -= num;
                 }
                 return true;
             }
             return false;
         }
         return false;
     }
Referenced by Projectile.AI_075(), Projectile.AI_100_Medusa(), and Projectile.AI_185_LifeDrain().