Terraria: Player.DoubleJumpVisuals
DoubleJumpVisuals()
void Player.DoubleJumpVisuals () inline
     {
         if (isPerformingJump_Cloud && hasJumpOption_Cloud && !canJumpAgain_Cloud && (canJumpAgain_Sandstorm || !hasJumpOption_Sandstorm) && ((gravDir == 1f && velocity.Y < 0f) || (gravDir == -1f && velocity.Y > 0f)))
         {
             int num = height;
             if (gravDir == -1f)
             {
                 num = -6;
             }
             int num2 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)num), width + 8, 4, 16, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 100, default(Color), 1.5f);
             Main.dust[num2].velocity.X = Main.dust[num2].velocity.X * 0.5f - velocity.X * 0.1f;
             Main.dust[num2].velocity.Y = Main.dust[num2].velocity.Y * 0.5f - velocity.Y * 0.3f;
         }
         if (isPerformingJump_Sandstorm && hasJumpOption_Sandstorm && !canJumpAgain_Sandstorm && ((gravDir == 1f && velocity.Y < 0f) || (gravDir == -1f && velocity.Y > 0f)))
         {
             int num3 = height;
             if (gravDir == -1f)
             {
                 num3 = -6;
             }
             float num4 = ((float)jump / 75f + 1f) / 2f;
             for (int i = 0; i < 3; i++)
             {
                 int num5 = Dust.NewDust(new Vector2(position.X, position.Y + (float)(num3 / 2)), width, 32, 124, velocity.X * 0.3f, velocity.Y * 0.3f, 150, default(Color), 1f * num4);
                 Main.dust[num5].velocity *= 0.5f * num4;
                 Main.dust[num5].fadeIn = 1.5f * num4;
             }
             sandStorm = true;
             if (miscCounter % 3 == 0)
             {
                 int num6 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 18f, position.Y + (float)(num3 / 2)), new Vector2(0f - velocity.X, 0f - velocity.Y), Main.rand.Next(220, 223), num4);
                 Main.gore[num6].velocity = velocity * 0.3f * num4;
                 Main.gore[num6].alpha = 100;
             }
         }
         if (isPerformingJump_Fart && hasJumpOption_Fart && !canJumpAgain_Fart && ((gravDir == 1f && velocity.Y < 0f) || (gravDir == -1f && velocity.Y > 0f)))
         {
             int num7 = height;
             if (gravDir == -1f)
             {
                 num7 = -6;
             }
             int num8 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)num7), width + 8, 4, 188, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 100, default(Color), 1.5f);
             Main.dust[num8].velocity.X = Main.dust[num8].velocity.X * 0.5f - velocity.X * 0.1f;
             Main.dust[num8].velocity.Y = Main.dust[num8].velocity.Y * 0.5f - velocity.Y * 0.3f;
             Main.dust[num8].velocity *= 0.5f;
         }
         if (isPerformingJump_Unicorn && hasJumpOption_Unicorn && !canJumpAgain_Unicorn && ((gravDir == 1f && velocity.Y < 0f) || (gravDir == -1f && velocity.Y > 0f)))
         {
             Dust obj = Main.dust[Dust.NewDust(position, width, height, Utils.SelectRandom<int>(Main.rand, 176, 177, 179))];
             obj.velocity = Vector2.Zero;
             obj.noGravity = true;
             obj.scale = 0.5f + Main.rand.NextFloat() * 0.8f;
             obj.fadeIn = 1f + Main.rand.NextFloat() * 2f;
             obj.shader = GameShaders.Armor.GetSecondaryShader(cMount, this);
         }
         if (isPerformingJump_Sail && hasJumpOption_Sail && !canJumpAgain_Sail && ((gravDir == 1f && velocity.Y < 1f) || (gravDir == -1f && velocity.Y > 1f)))
         {
             int num9 = 1;
             if (jump > 0)
             {
                 num9 = 2;
             }
             int num10 = height - 6;
             if (gravDir == -1f)
             {
                 num10 = 6;
             }
             for (int j = 0; j < num9; j++)
             {
                 int num11 = Dust.NewDust(new Vector2(position.X, position.Y + (float)num10), width, 12, 253, velocity.X * 0.3f, velocity.Y * 0.3f, 100, default(Color), 1.5f);
                 Main.dust[num11].scale += (float)Main.rand.Next(-5, 3) * 0.1f;
                 if (jump <= 0)
                 {
                     Main.dust[num11].scale *= 0.8f;
                 }
                 else
                 {
                     Main.dust[num11].velocity -= velocity / 5f;
                 }
                 Main.dust[num11].noGravity = true;
                 Vector2 vector = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                 vector.Normalize();
                 vector *= (float)Main.rand.Next(81) * 0.1f;
             }
         }
         if (!isPerformingJump_Blizzard || !hasJumpOption_Blizzard || canJumpAgain_Blizzard || ((gravDir != 1f || !(velocity.Y < 0f)) && (gravDir != -1f || !(velocity.Y > 0f))))
         {
             return;
         }
         int num12 = height - 6;
         if (gravDir == -1f)
         {
             num12 = 6;
         }
         for (int k = 0; k < 2; k++)
         {
             int num13 = Dust.NewDust(new Vector2(position.X, position.Y + (float)num12), width, 12, 76, velocity.X * 0.3f, velocity.Y * 0.3f);
             Main.dust[num13].velocity *= 0.1f;
             if (k == 0)
             {
                 Main.dust[num13].velocity += velocity * 0.03f;
             }
             else
             {
                 Main.dust[num13].velocity -= velocity * 0.03f;
             }
             Main.dust[num13].velocity -= velocity * 0.1f;
             Main.dust[num13].noGravity = true;
             Main.dust[num13].noLight = true;
         }
         for (int l = 0; l < 3; l++)
         {
             int num14 = Dust.NewDust(new Vector2(position.X, position.Y + (float)num12), width, 12, 76, velocity.X * 0.3f, velocity.Y * 0.3f);
             Main.dust[num14].fadeIn = 1.5f;
             Main.dust[num14].velocity *= 0.6f;
             Main.dust[num14].velocity += velocity * 0.8f;
             Main.dust[num14].noGravity = true;
             Main.dust[num14].noLight = true;
         }
         for (int m = 0; m < 3; m++)
         {
             int num15 = Dust.NewDust(new Vector2(position.X, position.Y + (float)num12), width, 12, 76, velocity.X * 0.3f, velocity.Y * 0.3f);
             Main.dust[num15].fadeIn = 1.5f;
             Main.dust[num15].velocity *= 0.6f;
             Main.dust[num15].velocity -= velocity * 0.8f;
             Main.dust[num15].noGravity = true;
             Main.dust[num15].noLight = true;
         }
     }
References Gore.alpha, GameShaders.Armor, Color, Main.dust, Dust.fadeIn, ArmorShaderDataSet.GetSecondaryShader(), Main.gore, Dust.NewDust(), Gore.NewGore(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.rand, Dust.scale, Dust.shader, Dust.velocity, and Gore.velocity.