Terraria: Player.ItemCheck_EmitHeldItemLight
ItemCheck_EmitHeldItemLight()
void Player.ItemCheck_EmitHeldItemLight (Item sItem) inline private
     {
         Vector2? handPosition = HandPosition;
         if (((ItemID.Sets.Torches[sItem.type] && !wet) || ItemID.Sets.WaterTorches[sItem.type]) && !pulley && !happyFunTorchTime)
         {
             float R = 1f;
             float G = 0.95f;
             float B = 0.8f;
             int num = 0;
             int num2 = BiomeTorchHoldStyle(sItem.type);
             if (num2 == 523)
             {
                 num = 8;
             }
             else if (num2 == 974)
             {
                 num = 9;
             }
             else if (num2 == 1245)
             {
                 num = 10;
             }
             else if (num2 == 1333)
             {
                 num = 11;
             }
             else if (num2 == 2274)
             {
                 num = 12;
             }
             else if (num2 == 3004)
             {
                 num = 13;
             }
             else if (num2 == 3045)
             {
                 num = 14;
             }
             else if (num2 == 3114)
             {
                 num = 15;
             }
             else if (num2 == 4383)
             {
                 num = 16;
             }
             else if (num2 == 4384)
             {
                 num = 17;
             }
             else if (num2 == 4385)
             {
                 num = 18;
             }
             else if (num2 == 4386)
             {
                 num = 19;
             }
             else if (num2 == 4387)
             {
                 num = 20;
             }
             else if (num2 == 4388)
             {
                 num = 21;
             }
             else if (num2 == 5293)
             {
                 num = 22;
             }
             else if (num2 == 5353)
             {
                 num = 23;
             }
             else if (num2 >= 427)
             {
                 num = num2 - 426;
             }
             num = (int)MathHelper.Clamp(num, 0f, TorchID.Count - 1);
             TorchID.TorchColor(num, out R, out G, out B);
             int num3 = TorchID.Dust[num];
             int maxValue = 30;
             if (itemAnimation > 0)
             {
                 maxValue = 7;
             }
             if (direction == -1)
             {
                 if (Main.rand.Next(maxValue) == 0)
                 {
                     int num4 = Dust.NewDust(new Vector2(itemLocation.X - 16f, itemLocation.Y - 14f * gravDir), 4, 4, num3, 0f, 0f, 100);
                     if (Main.rand.Next(3) != 0)
                     {
                         Main.dust[num4].noGravity = true;
                     }
                     Main.dust[num4].velocity *= 0.3f;
                     Main.dust[num4].velocity.Y -= 1.5f;
                     Main.dust[num4].position = RotatedRelativePoint(Main.dust[num4].position);
                     if (num3 == 66)
                     {
                         Main.dust[num4].color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                         Main.dust[num4].noGravity = true;
                     }
                 }
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 12f + velocity.X, itemLocation.Y - 14f + velocity.Y)), R, G, B);
             }
             else
             {
                 if (Main.rand.Next(maxValue) == 0)
                 {
                     int num5 = Dust.NewDust(new Vector2(itemLocation.X + 6f, itemLocation.Y - 14f * gravDir), 4, 4, num3, 0f, 0f, 100);
                     if (Main.rand.Next(3) != 0)
                     {
                         Main.dust[num5].noGravity = true;
                     }
                     Main.dust[num5].velocity *= 0.3f;
                     Main.dust[num5].velocity.Y -= 1.5f;
                     Main.dust[num5].position = RotatedRelativePoint(Main.dust[num5].position);
                     if (num3 == 66)
                     {
                         Main.dust[num5].color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                         Main.dust[num5].noGravity = true;
                     }
                 }
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 12f + velocity.X, itemLocation.Y - 14f + velocity.Y)), R, G, B);
             }
         }
         if ((sItem.type == 105 || sItem.type == 713) && !wet && !pulley)
         {
             int maxValue2 = 20;
             if (itemAnimation > 0)
             {
                 maxValue2 = 7;
             }
             if (direction == -1)
             {
                 if (Main.rand.Next(maxValue2) == 0)
                 {
                     int num6 = Dust.NewDust(new Vector2(itemLocation.X - 12f, itemLocation.Y - 20f * gravDir), 4, 4, 6, 0f, 0f, 100);
                     if (Main.rand.Next(3) != 0)
                     {
                         Main.dust[num6].noGravity = true;
                     }
                     Main.dust[num6].velocity *= 0.3f;
                     Main.dust[num6].velocity.Y -= 1.5f;
                     Main.dust[num6].position = RotatedRelativePoint(Main.dust[num6].position);
                 }
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 1f, 0.95f, 0.8f);
             }
             else
             {
                 if (Main.rand.Next(maxValue2) == 0)
                 {
                     int num7 = Dust.NewDust(new Vector2(itemLocation.X + 4f, itemLocation.Y - 20f * gravDir), 4, 4, 6, 0f, 0f, 100);
                     if (Main.rand.Next(3) != 0)
                     {
                         Main.dust[num7].noGravity = true;
                     }
                     Main.dust[num7].velocity *= 0.3f;
                     Main.dust[num7].velocity.Y -= 1.5f;
                     Main.dust[num7].position = RotatedRelativePoint(Main.dust[num7].position);
                 }
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 1f, 0.95f, 0.8f);
             }
         }
         else if (sItem.type == 148 && !wet && !pulley)
         {
             int maxValue3 = 10;
             if (itemAnimation > 0)
             {
                 maxValue3 = 7;
             }
             if (direction == -1)
             {
                 if (Main.rand.Next(maxValue3) == 0)
                 {
                     int num8 = Dust.NewDust(new Vector2(itemLocation.X - 12f, itemLocation.Y - 20f * gravDir), 4, 4, 172, 0f, 0f, 100);
                     if (Main.rand.Next(3) != 0)
                     {
                         Main.dust[num8].noGravity = true;
                     }
                     Main.dust[num8].velocity *= 0.3f;
                     Main.dust[num8].velocity.Y -= 1.5f;
                     Main.dust[num8].position = RotatedRelativePoint(Main.dust[num8].position);
                 }
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 0f, 0.5f, 1f);
             }
             else
             {
                 if (Main.rand.Next(maxValue3) == 0)
                 {
                     int num9 = Dust.NewDust(new Vector2(itemLocation.X + 4f, itemLocation.Y - 20f * gravDir), 4, 4, 172, 0f, 0f, 100);
                     if (Main.rand.Next(3) != 0)
                     {
                         Main.dust[num9].noGravity = true;
                     }
                     Main.dust[num9].velocity *= 0.3f;
                     Main.dust[num9].velocity.Y -= 1.5f;
                     Main.dust[num9].position = RotatedRelativePoint(Main.dust[num9].position);
                 }
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 0f, 0.5f, 1f);
             }
         }
         else if (sItem.type == 3117 && !wet && !pulley)
         {
             itemLocation.X -= direction * 4;
             int maxValue4 = 10;
             if (itemAnimation > 0)
             {
                 maxValue4 = 7;
             }
             if (direction == -1)
             {
                 if (Main.rand.Next(maxValue4) == 0)
                 {
                     int num10 = Dust.NewDust(new Vector2(itemLocation.X - 10f, itemLocation.Y - 20f * gravDir), 4, 4, 242, 0f, 0f, 100);
                     if (Main.rand.Next(3) != 0)
                     {
                         Main.dust[num10].noGravity = true;
                     }
                     Main.dust[num10].velocity *= 0.3f;
                     Main.dust[num10].velocity.Y -= 1.5f;
                     Main.dust[num10].position = RotatedRelativePoint(Main.dust[num10].position);
                 }
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 0.9f, 0.1f, 0.75f);
             }
             else
             {
                 if (Main.rand.Next(maxValue4) == 0)
                 {
                     int num11 = Dust.NewDust(new Vector2(itemLocation.X + 6f, itemLocation.Y - 20f * gravDir), 4, 4, 242, 0f, 0f, 100);
                     if (Main.rand.Next(3) != 0)
                     {
                         Main.dust[num11].noGravity = true;
                     }
                     Main.dust[num11].velocity *= 0.3f;
                     Main.dust[num11].velocity.Y -= 1.5f;
                     Main.dust[num11].position = RotatedRelativePoint(Main.dust[num11].position);
                 }
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 0.9f, 0.1f, 0.75f);
             }
         }
         else if (sItem.type == 5322 && !wet && !pulley)
         {
             float r = 0.2f;
             float g = 0.3f;
             float b = 0.32f;
             if (direction == -1)
             {
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), r, g, b);
             }
             else
             {
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), r, g, b);
             }
         }
         if (sItem.type == 282 && !pulley)
         {
             if (direction == -1)
             {
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 0.7f, 1f, 0.8f);
             }
             else
             {
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 0.7f, 1f, 0.8f);
             }
         }
         if (sItem.type == 3002 && !pulley)
         {
             float r2 = 1.05f;
             float g2 = 0.95f;
             float b2 = 0.55f;
             if (direction == -1)
             {
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), r2, g2, b2);
             }
             else
             {
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), r2, g2, b2);
             }
             spelunkerTimer++;
             if (spelunkerTimer >= 10)
             {
                 spelunkerTimer = 0;
                 Main.instance.SpelunkerProjectileHelper.AddSpotToCheck(base.Center);
             }
         }
         if (sItem.type == 286 && !pulley)
         {
             if (direction == -1)
             {
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 0.7f, 0.8f, 1f);
             }
             else
             {
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 0.7f, 0.8f, 1f);
             }
         }
         if (sItem.type == 3112 && !pulley)
         {
             if (direction == -1)
             {
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 1f, 0.6f, 0.85f);
             }
             else
             {
                 Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 1f, 0.6f, 0.85f);
             }
         }
         if (sItem.type == 4776 && !pulley)
         {
             Vector2 vec = RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f));
             if (direction == -1)
             {
                 vec = RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f));
             }
             Vector3 rgb = (DelegateMethods.v3_1 = new Vector3(0.9f, 0.35f, 1f));
             Point p = vec.ToTileCoordinates();
             DelegateMethods.v2_1 = p.ToVector2();
             DelegateMethods.f_1 = 4.5f;
             Utils.PlotTileArea(p.X, p.Y, DelegateMethods.SpreadLightOpen_StopForSolids);
             Lighting.AddLight(vec, rgb);
         }
         if (sItem.type == 3542 && handPosition.HasValue)
         {
             Vector2 vector = handPosition.Value - velocity;
             for (int i = 0; i < 4; i++)
             {
                 Dust dust = Main.dust[Dust.NewDust(base.Center, 0, 0, 242, direction * 2, 0f, 150, default(Color), 1.3f)];
                 dust.position = vector;
                 dust.velocity *= 0f;
                 dust.noGravity = true;
                 dust.fadeIn = 1f;
                 dust.velocity += velocity;
                 if (Main.rand.Next(2) == 0)
                 {
                     dust.position += Utils.RandomVector2(Main.rand, -4f, 4f);
                     dust.scale += Main.rand.NextFloat();
                     if (Main.rand.Next(2) == 0)
                     {
                         dust.customData = this;
                     }
                 }
             }
         }
         if (sItem.type != 4952 || pulley || isPettingAnimal)
         {
             return;
         }
         Vector2 pos = itemLocation + new Vector2(8 * direction, -10f * gravDir);
         Vector3 rgb2 = new Vector3(1f, 0.7f, 0.8f) * 1.3f;
         Vector2 vector2 = RotatedRelativePoint(pos);
         Lighting.AddLight(vector2, rgb2);
         if (Main.rand.Next(40) == 0)
         {
             Vector2 vector3 = Main.rand.NextVector2Circular(4f, 4f);
             Dust dust2 = Dust.NewDustPerfect(vector2 + vector3, 43, Vector2.Zero, 254, new Color(255, 255, 0, 255), 0.3f);
             if (vector3 != Vector2.Zero)
             {
                 dust2.velocity = vector2.DirectionTo(dust2.position) * 0.2f;
             }
             dust2.fadeIn = 0.3f;
             dust2.noLightEmittence = true;
             dust2.customData = this;
         }
     }
References Lighting.AddLight(), SpelunkerProjectileHelper.AddSpotToCheck(), B, Color, Dust.color, TorchID.Count, Dust.customData, Main.DiscoB, Main.DiscoG, Main.DiscoR, TorchID.Dust, Main.dust, DelegateMethods.f_1, Dust.fadeIn, G, Main.instance, Dust.NewDust(), Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLightEmittence, Utils.PlotTileArea(), Dust.position, R, Main.rand, Utils.RandomVector2(), Dust.scale, Main.SpelunkerProjectileHelper, DelegateMethods.SpreadLightOpen_StopForSolids(), TorchID.TorchColor(), ItemID.Sets.Torches, Item.type, DelegateMethods.v2_1, DelegateMethods.v3_1, Dust.velocity, and ItemID.Sets.WaterTorches.