Terraria: Player.ItemCheck_PlayInstruments
ItemCheck_PlayInstruments()
void Player.ItemCheck_PlayInstruments (Item sItem) inline private
     {
         Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
         float num = (float)Main.mouseX + Main.screenPosition.X - vector.X;
         float num2 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
         float num3 = (float)Math.Sqrt(num * num + num2 * num2);
         float num4 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
         num3 /= num4 / 2f;
         if (num3 > 1f)
         {
             num3 = 1f;
         }
         musicDist = num3;
         if (itemAnimation > 0 && ItemTimeIsZero && (sItem.type == 508 || sItem.type == 507))
         {
             ApplyItemTime(sItem);
             Vector2 vector2 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num5 = (float)Main.mouseX + Main.screenPosition.X - vector2.X;
             float num6 = (float)Main.mouseY + Main.screenPosition.Y - vector2.Y;
             float num7 = (float)Math.Sqrt(num5 * num5 + num6 * num6);
             float num8 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
             num7 /= num8 / 2f;
             if (num7 > 1f)
             {
                 num7 = 1f;
             }
             num7 = num7 * 2f - 1f;
             if (num7 < -1f)
             {
                 num7 = -1f;
             }
             if (num7 > 1f)
             {
                 num7 = 1f;
             }
             num7 = (float)Math.Round(num7 * (float)musicNotes);
             num7 = (Main.musicPitch = num7 / (float)musicNotes);
             LegacySoundStyle type = SoundID.Item26;
             if (sItem.type == 507)
             {
                 type = SoundID.Item35;
             }
             SoundEngine.PlaySound(type, position);
             NetMessage.SendData(58, -1, -1, null, whoAmI, num7);
         }
         if (itemAnimation <= 0 || mouseInterface)
         {
             return;
         }
         if (Main.mouseLeft && Main.mouseLeftRelease)
         {
             if (sItem.type == 1305)
             {
                 Vector2 vector3 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 float num9 = (float)Main.mouseX + Main.screenPosition.X - vector3.X;
                 float num10 = (float)Main.mouseY + Main.screenPosition.Y - vector3.Y;
                 float num11 = (float)Math.Sqrt(num9 * num9 + num10 * num10);
                 float num12 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
                 num11 /= num12 / 2f;
                 if (num11 > 1f)
                 {
                     num11 = 1f;
                 }
                 num11 = num11 * 2f - 1f;
                 if (num11 < -1f)
                 {
                     num11 = -1f;
                 }
                 if (num11 > 1f)
                 {
                     num11 = 1f;
                 }
                 num11 = (float)Math.Round(num11 * (float)musicNotes);
                 num11 = (Main.musicPitch = num11 / (float)musicNotes);
                 SoundEngine.PlaySound(SoundID.Item47, position);
                 NetMessage.SendData(58, -1, -1, null, whoAmI, num11);
             }
             else if (sItem.type == 4057 || sItem.type == 4372)
             {
                 Vector2 vector4 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 float num13 = (float)Main.mouseX + Main.screenPosition.X - vector4.X;
                 float num14 = (float)Main.mouseY + Main.screenPosition.Y - vector4.Y;
                 float num15 = (float)Math.Sqrt(num13 * num13 + num14 * num14);
                 float num16 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
                 num15 /= num16 / 2f;
                 if (num15 > 1f)
                 {
                     num15 = 1f;
                 }
                 PlayGuitarChord(num15);
                 NetMessage.SendData(58, -1, -1, null, whoAmI, num15);
             }
         }
         if (sItem.type == 4715 && ((Main.mouseLeft && Main.mouseLeftRelease) | ItemAnimationJustStarted))
         {
             Vector2 vector5 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num17 = (float)Main.mouseX + Main.screenPosition.X - vector5.X;
             float num18 = (float)Main.mouseY + Main.screenPosition.Y - vector5.Y;
             float num19 = (float)Math.Sqrt(num17 * num17 + num18 * num18);
             float num20 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
             num19 /= num20 / 2f;
             if (num19 > 1f)
             {
                 num19 = 1f;
             }
             PlayGuitarChord(num19);
             NetMessage.SendData(58, -1, -1, null, whoAmI, num19);
         }
         if (sItem.type != 4673)
         {
             return;
         }
         int num21 = (int)base.Center.X / 16;
         int num22 = (int)base.Center.Y / 16;
         if (WorldGen.InWorld(num21, num22) && Main.tile[num21, num22] != null && Main.tile[num21, num22].type == 486 && ((Main.mouseLeft && Main.mouseLeftRelease) || (Main.mouseRight && Main.mouseRightRelease)))
         {
             Vector2 vector6 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num23 = (float)Main.mouseX + Main.screenPosition.X - vector6.X;
             float num24 = (float)Main.mouseY + Main.screenPosition.Y - vector6.Y;
             float num25 = (float)Math.Sqrt(num23 * num23 + num24 * num24);
             float num26 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
             num25 /= num26 / 2f;
             if (num25 > 1f)
             {
                 num25 = 1f;
             }
             PlayDrums(num25);
             NetMessage.SendData(58, -1, -1, null, whoAmI, num25);
         }
     }
References Main.GameViewMatrix, WorldGen.InWorld(), SoundID.Item26, SoundID.Item35, SoundID.Item47, Main.mouseLeft, Main.mouseLeftRelease, Main.mouseRight, Main.mouseRightRelease, Main.mouseX, Main.mouseY, Main.musicPitch, SoundEngine.PlaySound(), Main.screenHeight, Main.screenPosition, NetMessage.SendData(), Main.tile, Item.type, Tile.type, and SpriteViewMatrix.Zoom.