Terraria: Player.ApplyDamageToNPC
ApplyDamageToNPC()
void Player.ApplyDamageToNPC (NPC npc, int damage, float knockback, int direction, bool crit) inline
     {
         int num = Item.NPCtoBanner(npc.BannerID());
         if (num > 0 && HasNPCBannerBuff(num))
         {
             damage = ((!Main.expertMode) ? ((int)((float)damage * ItemID.Sets.BannerStrength[Item.BannerToItem(num)].NormalDamageDealt)) : ((int)((float)damage * ItemID.Sets.BannerStrength[Item.BannerToItem(num)].ExpertDamageDealt)));
         }
         OnHit(npc.Center.X, npc.Center.Y, npc);
         damage += npc.checkArmorPenetration(armorPenetration, 0f);
         NPCKillAttempt attempt = new NPCKillAttempt(npc);
         int dmg = (int)npc.StrikeNPC(damage, knockback, direction, crit);
         if (accDreamCatcher)
         {
             addDPS(dmg);
         }
         if (Main.netMode != 0)
         {
             NetMessage.SendData(28, -1, -1, null, npc.whoAmI, damage, knockback, direction, crit.ToInt());
         }
         int num2 = Item.NPCtoBanner(npc.BannerID());
         if (num2 >= 0)
         {
             lastCreatureHit = num2;
         }
         if (attempt.DidNPCDie())
         {
             OnKillNPC(ref attempt, null);
         }
     }
References NPC.BannerID(), ItemID.Sets.BannerStrength, Item.BannerToItem(), Entity.Center, NPC.checkArmorPenetration(), NPCKillAttempt.DidNPCDie(), ItemID.BannerEffect.ExpertDamageDealt, Main.expertMode, Main.netMode, ItemID.BannerEffect.NormalDamageDealt, Item.NPCtoBanner(), NetMessage.SendData(), NPC.StrikeNPC(), and Entity.whoAmI.