Terraria: Player.ResetVisibleAccessories
ResetVisibleAccessories()
void Player.ResetVisibleAccessories () inline
     {
         handon = -1;
         handoff = -1;
         back = -1;
         front = -1;
         shoe = -1;
         waist = -1;
         shield = -1;
         neck = -1;
         face = -1;
         balloon = -1;
         backpack = -1;
         tail = -1;
         faceHead = -1;
         faceFlower = -1;
         balloonFront = -1;
         beard = -1;
     }
Referenced by TEDisplayDoll.Draw(), TEHatRack.Draw(), Segments.PlayerSegment.Draw(), Main.DrawSuperSpecialProjectiles(), and UICharacter.Update().