Terraria: CreativePowers.SpawnRateSliderPerPlayerPower.UpdateSliderAndShowMultiplierMouseOver
UpdateSliderAndShowMultiplierMouseOver()
void CreativePowers.SpawnRateSliderPerPlayerPower.UpdateSliderAndShowMultiplierMouseOver (UIElement affectedElement) inline private
         {
             if (affectedElement.IsMouseHovering)
             {
                 string originalText = "x" + RemapSliderValueToPowerValue(GetSliderValue()).ToString("F2");
                 if (GetShouldDisableSpawnsFor(Main.myPlayer))
                 {
                     originalText = Language.GetTextValue(_powerNameKey + "EnemySpawnsDisabled");
                 }
                 CreativePowersHelper.AddPermissionTextIfNeeded(this, ref originalText);
                 Main.instance.MouseTextNoOverride(originalText, 0, 0);
             }
         }
References CreativePowers.APerPlayerSliderPower._powerNameKey, CreativePowersHelper.AddPermissionTextIfNeeded(), CreativePowers.SpawnRateSliderPerPlayerPower.GetShouldDisableSpawnsFor(), CreativePowers.APerPlayerSliderPower.GetSliderValue(), Language.GetTextValue(), Main.instance, UIElement.IsMouseHovering, Main.MouseTextNoOverride(), Main.myPlayer, and CreativePowers.SpawnRateSliderPerPlayerPower.RemapSliderValueToPowerValue().
Referenced by CreativePowers.SpawnRateSliderPerPlayerPower.ProvideSlider().