Terraria: System.Globalization.Ordinal.IndexOfOrdinalIgnoreCase
IndexOfOrdinalIgnoreCase()
static int System.Globalization.Ordinal.IndexOfOrdinalIgnoreCase (ReadOnlySpan< char > source, ReadOnlySpan< char > value) inline static package
Definition at line 151 of file Ordinal.cs.
    {
        if (value.Length == 0)
        {
            return 0;
        }
        if (value.Length > source.Length)
        {
            return -1;
        }
        if (GlobalizationMode.Invariant)
        {
            return InvariantModeCasing.IndexOfIgnoreCase(source, value);
        }
        if (GlobalizationMode.UseNls)
        {
            return CompareInfo.NlsIndexOfOrdinalCore(source, value, ignoreCase: true, fromBeginning: true);
        }
        return OrdinalCasing.IndexOf(source, value);
    }
References System.Globalization.OrdinalCasing.IndexOf(), System.Globalization.InvariantModeCasing.IndexOfIgnoreCase(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.CompareInfo.NlsIndexOfOrdinalCore(), System.source, System.Globalization.GlobalizationMode.UseNls, and System.value.
Referenced by System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.Ordinal.IndexOf(), and System.MemoryExtensions.IndexOf().