Terraria: System.Globalization.Ordinal.IndexOf
IndexOf()
static int System.Globalization.Ordinal.IndexOf (string source, string value, int startIndex, int count, bool ignoreCase) inline static package
Definition at line 122 of file Ordinal.cs.
    {
        if (source == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
        }
        if (value == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.value);
        }
        if (!source.TryGetSpan(startIndex, count, out var slice))
        {
            if ((uint)startIndex > (uint)source.Length)
            {
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.startIndex, ExceptionResource.ArgumentOutOfRange_Index);
            }
            else
            {
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.count, ExceptionResource.ArgumentOutOfRange_Count);
            }
        }
        int num = (ignoreCase ? IndexOfOrdinalIgnoreCase(slice, value) : slice.IndexOf(value));
        if (num < 0)
        {
            return num;
        }
        return num + startIndex;
    }
References System.count, System.Globalization.Ordinal.IndexOfOrdinalIgnoreCase(), System.source, System.startIndex, System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.value.
Referenced by System.String.IndexOf().