Terraria: System.Globalization.Ordinal.CompareStringIgnoreCase
CompareStringIgnoreCase()
static int System.Globalization.Ordinal.CompareStringIgnoreCase (ref char strA, int lengthA, ref char strB, int lengthB) inline static package
Definition at line 8 of file Ordinal.cs.
    {
        int num = Math.Min(lengthA, lengthB);
        int num2 = num;
        ref char reference = ref strA;
        ref char reference2 = ref strB;
        char c = '\u007f';
        while (num != 0 && reference <= c && reference2 <= c)
        {
            if (reference == reference2 || ((reference | 0x20) == (reference2 | 0x20) && (uint)((reference | 0x20) - 97) <= 25u))
            {
                num--;
                reference = ref Unsafe.Add(ref reference, 1);
                reference2 = ref Unsafe.Add(ref reference2, 1);
                continue;
            }
            int num3 = reference;
            int num4 = reference2;
            if ((uint)(reference - 97) <= 25u)
            {
                num3 -= 32;
            }
            if ((uint)(reference2 - 97) <= 25u)
            {
                num4 -= 32;
            }
            return num3 - num4;
        }
        if (num == 0)
        {
            return lengthA - lengthB;
        }
        num2 -= num;
        return CompareStringIgnoreCaseNonAscii(ref reference, lengthA - num2, ref reference2, lengthB - num2);
    }
References System.Globalization.Ordinal.CompareStringIgnoreCaseNonAscii(), and System.Math.Min().
Referenced by System.Globalization.CompareInfo.Compare(), System.String.Compare(), System.String.Compare(), System.MemoryExtensions.CompareTo(), System.String.EndsWith(), and System.Globalization.Ordinal.EqualsIgnoreCase().