Terraria: System.Globalization.Ordinal.CompareStringIgnoreCaseNonAscii
CompareStringIgnoreCaseNonAscii()
static int System.Globalization.Ordinal.CompareStringIgnoreCaseNonAscii (ref char strA, int lengthA, ref char strB, int lengthB) inline static package
Definition at line 44 of file Ordinal.cs.
    {
        if (GlobalizationMode.Invariant)
        {
            return InvariantModeCasing.CompareStringIgnoreCase(ref strA, lengthA, ref strB, lengthB);
        }
        if (GlobalizationMode.UseNls)
        {
            return CompareInfo.NlsCompareStringOrdinalIgnoreCase(ref strA, lengthA, ref strB, lengthB);
        }
        return OrdinalCasing.CompareStringIgnoreCase(ref strA, lengthA, ref strB, lengthB);
    }
References System.Globalization.InvariantModeCasing.CompareStringIgnoreCase(), System.Globalization.OrdinalCasing.CompareStringIgnoreCase(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.CompareInfo.NlsCompareStringOrdinalIgnoreCase(), and System.Globalization.GlobalizationMode.UseNls.
Referenced by System.Globalization.Ordinal.CompareStringIgnoreCase().