Terraria: Terraria.GameContent.Ambience.AmbienceServer.FindPlayerThatCanSeeBackgroundAmbience
FindPlayerThatCanSeeBackgroundAmbience()
static void Terraria.GameContent.Ambience.AmbienceServer.FindPlayerThatCanSeeBackgroundAmbience (out Player player) inline static private
    {
        player = null;
        int num = Main.player.Count((Player plr) => plr.active && IsPlayerInAPlaceWhereTheyCanSeeAmbience(plr));
        if (num != 0)
        {
            player = Main.player.Where((Player plr) => plr.active && IsPlayerInAPlaceWhereTheyCanSeeAmbience(plr)).ElementAt(Main.rand.Next(num));
        }
    }
References Terraria.Entity.active, Terraria.GameContent.Ambience.AmbienceServer.IsPlayerInAPlaceWhereTheyCanSeeAmbience(), Terraria.Main.player, and Terraria.Main.rand.
Referenced by Terraria.GameContent.Ambience.AmbienceServer.SpawnForcedEntities(), and Terraria.GameContent.Ambience.AmbienceServer.Update().