Terraria: System.Globalization.Ordinal.ToUpperOrdinal
ToUpperOrdinal()
static int System.Globalization.Ordinal.ToUpperOrdinal (ReadOnlySpan< char > source, Span< char > destination) inline static package
Definition at line 193 of file Ordinal.cs.
    {
        if (source.Overlaps(destination))
        {
            throw new InvalidOperationException(SR.InvalidOperation_SpanOverlappedOperation);
        }
        if (destination.Length < source.Length)
        {
            return -1;
        }
        if (GlobalizationMode.Invariant)
        {
            InvariantModeCasing.ToUpper(source, destination);
            return source.Length;
        }
        if (GlobalizationMode.UseNls)
        {
            TextInfo.Invariant.ChangeCaseToUpper(source, destination);
            return source.Length;
        }
        OrdinalCasing.ToUpperOrdinal(source, destination);
        return source.Length;
    }
References System.destination, System.SR.InvalidOperation_SpanOverlappedOperation, System.Globalization.GlobalizationMode.Invariant, System.Globalization.TextInfo.Invariant, System.source, System.Globalization.InvariantModeCasing.ToUpper(), System.Globalization.OrdinalCasing.ToUpperOrdinal(), and System.Globalization.GlobalizationMode.UseNls.
Referenced by System.Marvin.ComputeHash32OrdinalIgnoreCaseSlow(), and System.String.GetNonRandomizedHashCodeOrdinalIgnoreCase().