Terraria: System.Globalization.Ordinal.LastIndexOfOrdinalIgnoreCase
LastIndexOfOrdinalIgnoreCase()
static int System.Globalization.Ordinal.LastIndexOfOrdinalIgnoreCase (ReadOnlySpan< char > source, ReadOnlySpan< char > value) inline static package
Definition at line 172 of file Ordinal.cs.
    {
        if (value.Length == 0)
        {
            return source.Length;
        }
        if (value.Length > source.Length)
        {
            return -1;
        }
        if (GlobalizationMode.Invariant)
        {
            return InvariantModeCasing.LastIndexOfIgnoreCase(source, value);
        }
        if (GlobalizationMode.UseNls)
        {
            return CompareInfo.NlsIndexOfOrdinalCore(source, value, ignoreCase: true, fromBeginning: false);
        }
        return OrdinalCasing.LastIndexOf(source, value);
    }
References System.Globalization.GlobalizationMode.Invariant, System.Globalization.OrdinalCasing.LastIndexOf(), System.Globalization.InvariantModeCasing.LastIndexOfIgnoreCase(), System.Globalization.CompareInfo.NlsIndexOfOrdinalCore(), System.source, System.Globalization.GlobalizationMode.UseNls, and System.value.
Referenced by System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.LastIndexOf(), and System.MemoryExtensions.LastIndexOf().