Terraria: System.Globalization.Ordinal.EqualsIgnoreCase
EqualsIgnoreCase()
static bool System.Globalization.Ordinal.EqualsIgnoreCase (ref char charA, ref char charB, int length) inline static package
Definition at line 57 of file Ordinal.cs.
    {
        IntPtr zero = IntPtr.Zero;
        while (true)
        {
            if ((uint)length >= 4u)
            {
                ulong num = Unsafe.ReadUnaligned<ulong>(ref Unsafe.As<char, byte>(ref Unsafe.AddByteOffset(ref charA, zero)));
                ulong num2 = Unsafe.ReadUnaligned<ulong>(ref Unsafe.As<char, byte>(ref Unsafe.AddByteOffset(ref charB, zero)));
                ulong num3 = num | num2;
                if (!Utf16Utility.AllCharsInUInt32AreAscii((uint)((int)num3 | (int)(num3 >> 32))))
                {
                    break;
                }
                if (!Utf16Utility.UInt64OrdinalIgnoreCaseAscii(num, num2))
                {
                    return false;
                }
                zero += 8;
                length -= 4;
                continue;
            }
            if ((uint)length >= 2u)
            {
                uint num4 = Unsafe.ReadUnaligned<uint>(ref Unsafe.As<char, byte>(ref Unsafe.AddByteOffset(ref charA, zero)));
                uint num5 = Unsafe.ReadUnaligned<uint>(ref Unsafe.As<char, byte>(ref Unsafe.AddByteOffset(ref charB, zero)));
                if (!Utf16Utility.AllCharsInUInt32AreAscii(num4 | num5))
                {
                    break;
                }
                if (!Utf16Utility.UInt32OrdinalIgnoreCaseAscii(num4, num5))
                {
                    return false;
                }
                zero += 4;
                length -= 2;
            }
            if (length != 0)
            {
                uint num6 = Unsafe.AddByteOffset(ref charA, zero);
                uint num7 = Unsafe.AddByteOffset(ref charB, zero);
                if ((num6 | num7) > 127)
                {
                    break;
                }
                if (num6 == num7)
                {
                    return true;
                }
                num6 |= 0x20u;
                if (num6 - 97 > 25)
                {
                    return false;
                }
                if (num6 != (num7 | 0x20))
                {
                    return false;
                }
                return true;
            }
            return true;
        }
        return CompareStringIgnoreCase(ref Unsafe.AddByteOffset(ref charA, zero), length, ref Unsafe.AddByteOffset(ref charB, zero), length) == 0;
    }
References System.Text.Unicode.Utf16Utility.AllCharsInUInt32AreAscii(), System.Globalization.Ordinal.CompareStringIgnoreCase(), System.length, System.Text.Unicode.Utf16Utility.UInt32OrdinalIgnoreCaseAscii(), System.Text.Unicode.Utf16Utility.UInt64OrdinalIgnoreCaseAscii(), and System.IntPtr.Zero.
Referenced by System.MemoryExtensions.EndsWithOrdinalIgnoreCase(), System.OrdinalIgnoreCaseComparer.Equals(), System.OrdinalComparer.Equals(), System.MemoryExtensions.EqualsOrdinalIgnoreCase(), System.String.EqualsOrdinalIgnoreCaseNoLengthCheck(), System.Globalization.IdnMapping.GetStringForOutput(), System.String.StartsWith(), and System.MemoryExtensions.StartsWithOrdinalIgnoreCase().