Terraria: ReLogic.Utilities.Vector2D.Vector2D
Vector2D() [1/2]
ReLogic.Utilities.Vector2D.Vector2D (double x, double y) inline
Definition at line 34 of file Vector2D.cs.
    {
        X = x;
        Y = y;
    }
References ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by ReLogic.Utilities.Vector2D.Barycentric(), ReLogic.Utilities.Vector2D.CatmullRom(), ReLogic.Utilities.Vector2D.Clamp(), ReLogic.Utilities.Vector2D.Lerp(), ReLogic.Utilities.Vector2D.Max(), ReLogic.Utilities.Vector2D.Min(), and ReLogic.Utilities.Vector2D.SmoothStep().