Terraria: Terraria.Audio.SoundEngine.GetActiveSound
GetActiveSound()
static ActiveSound Terraria.Audio.SoundEngine.GetActiveSound (SlotId id) inline static
Definition at line 99 of file SoundEngine.cs.
    {
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        if (Main.dedServ || !IsAudioSupported)
        {
            return null;
        }
        return SoundPlayer.GetActiveSound(id);
    }
References Terraria.Main.dedServ, Terraria.Audio.SoundPlayer.GetActiveSound(), and Terraria.Audio.SoundEngine.IsAudioSupported.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_110_Betsy(), Terraria.Projectile.AI_143_MonkStaffT2Ghast(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_187_ShadowHand(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.NPC.HitEffect(), Terraria.Projectile.Kill(), and Terraria.Player.UpdateBiomes().