Terraria: System.Threading.Tasks.Dataflow.Internal.SourceCore.OfferAsyncIfNecessary_Slow
OfferAsyncIfNecessary_Slow()
void System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessary_Slow (bool isReplacementReplica, bool outgoingLockKnownAcquired) inline private
Definition at line 535 of file SourceCore.cs.
    {
        bool flag = true;
        if (outgoingLockKnownAcquired || Monitor.IsEntered(OutgoingLock))
        {
            flag = _targetRegistry.FirstTargetNode != null;
        }
        if (!flag || CanceledOrFaulted)
        {
            return;
        }
        _taskForOutputProcessing = new Task(delegate(object thisSourceCore)
        {
            ((SourceCore<TOutput>)thisSourceCore).OfferMessagesLoopCore();
        }, this, Common.GetCreationOptionsForTask(isReplacementReplica));
        DataflowEtwProvider log = DataflowEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TaskLaunchedForMessageHandling(_owningSource, _taskForOutputProcessing, DataflowEtwProvider.TaskLaunchedReason.OfferingOutputMessages, _messages.Count);
        }
        Exception ex = Common.StartTaskSafe(_taskForOutputProcessing, _dataflowBlockOptions.TaskScheduler);
        if (ex == null)
        {
            return;
        }
        AddException(ex);
        _taskForOutputProcessing = null;
        _decliningPermanently = true;
        Task.Factory.StartNew(delegate(object state)
        {
            SourceCore<TOutput> sourceCore = (SourceCore<TOutput>)state;
            lock (sourceCore.OutgoingLock)
            {
                lock (sourceCore.ValueLock)
                {
                    sourceCore.CompleteBlockIfPossible();
                }
            }
        }, this, CancellationToken.None, Common.GetCreationOptionsForTask(), TaskScheduler.Default);
    }
References System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._dataflowBlockOptions, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._messages, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._owningSource, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._taskForOutputProcessing, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.AddException(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.CanceledOrFaulted, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask(), System.Threading.Monitor.IsEntered(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.Log, System.Threading.CancellationToken.None, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OutgoingLock, System.Threading.Tasks.Dataflow.Internal.Common.StartTaskSafe(), System.state, and System.Threading.Tasks.Dataflow.DataflowBlockOptions.TaskScheduler.
Referenced by System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessary().