Terraria: System.Threading.Tasks.Dataflow.Internal.SourceCore.OfferMessagesLoopCore
OfferMessagesLoopCore()
void System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferMessagesLoopCore () inline private
Definition at line 576 of file SourceCore.cs.
    {
        try
        {
            int actualMaxMessagesPerTask = _dataflowBlockOptions.ActualMaxMessagesPerTask;
            int num = ((_dataflowBlockOptions.MaxMessagesPerTask == -1) ? 10 : actualMaxMessagesPerTask);
            int num2 = 0;
            while (num2 < actualMaxMessagesPerTask && !CanceledOrFaulted)
            {
                lock (OutgoingLock)
                {
                    int num3 = 0;
                    while (num2 < actualMaxMessagesPerTask && num3 < num && !CanceledOrFaulted)
                    {
                        if (!OfferToTargets())
{
                            return;
                        }
                        num2++;
                        num3++;
                    }
                }
            }
        }
        catch (Exception exception)
        {
            AddException(exception);
            _completeAction(_owningSource);
        }
        finally
        {
            lock (OutgoingLock)
            {
                lock (ValueLock)
                {
                    _taskForOutputProcessing = null;
                    Interlocked.MemoryBarrier();
                    OfferAsyncIfNecessary(isReplacementReplica: true, outgoingLockKnownAcquired: true);
                    CompleteBlockIfPossible();
                }
            }
        }
    }
References System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._completeAction, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._dataflowBlockOptions, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._owningSource, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._taskForOutputProcessing, System.Threading.Tasks.Dataflow.DataflowBlockOptions.ActualMaxMessagesPerTask, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.AddException(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.CanceledOrFaulted, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.CompleteBlockIfPossible(), System.exception, System.Threading.Interlocked.MemoryBarrier(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessary(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferToTargets(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OutgoingLock, and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ValueLock.