Terraria: System.Threading.Tasks.Dataflow.Internal.SourceCore.TryReceive
TryReceive()
bool System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.TryReceive (Predicate< TOutput > filter, [MaybeNullWhen(false)] out TOutput item) inline package
Definition at line 261 of file SourceCore.cs.
    {
        item = default(TOutput);
        bool flag = false;
        lock (OutgoingLock)
        {
            if (_nextMessageReservedFor == null)
            {
                lock (ValueLock)
                {
                    if (_messages.TryDequeueIf(filter, out item))
                    {
                        _nextMessageId.Value++;
                        _enableOffering = true;
                        CompleteBlockIfPossible();
                        OfferAsyncIfNecessary(isReplacementReplica: false, outgoingLockKnownAcquired: true);
                        flag = true;
                    }
                }
            }
        }
        if (flag && _itemsRemovedAction != null)
        {
            int arg = ((_itemCountingFunc == null) ? 1 : _itemCountingFunc(_owningSource, item, null));
            _itemsRemovedAction(_owningSource, arg);
        }
        return flag;
    }
References System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._enableOffering, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._itemCountingFunc, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._itemsRemovedAction, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._messages, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._nextMessageId, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._nextMessageReservedFor, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._owningSource, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.CompleteBlockIfPossible(), System.item, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessary(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OutgoingLock, System.Threading.Tasks.Dataflow.Internal.PaddedInt64.Value, and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ValueLock.
Referenced by System.Threading.Tasks.Dataflow.BufferBlock< T >.TryReceive(), and System.Threading.Tasks.Dataflow.BatchBlock< T >.TryReceive().