Terraria: System.Threading.Tasks.Dataflow.Internal.SourceCore.LinkTo
LinkTo()
IDisposable System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.LinkTo (ITargetBlock< TOutput > target, DataflowLinkOptions linkOptions) inline package
Definition at line 127 of file SourceCore.cs.
    {
        if (target == null)
        {
            throw new ArgumentNullException("target");
        }
        if (linkOptions == null)
        {
            throw new ArgumentNullException("linkOptions");
        }
        if (_completionTask.Task.IsCompleted)
        {
            if (linkOptions.PropagateCompletion)
            {
                Common.PropagateCompletion(_completionTask.Task, target, null);
            }
            return Disposables.Nop;
        }
        lock (OutgoingLock)
        {
            if (!_completionReserved)
            {
                _targetRegistry.Add(ref target, linkOptions);
                OfferToTargets(target);
                return Common.CreateUnlinker(OutgoingLock, _targetRegistry, target);
            }
        }
        if (linkOptions.PropagateCompletion)
        {
            Common.PropagateCompletionOnceCompleted(_completionTask.Task, target);
        }
        return Disposables.Nop;
    }
References System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._completionReserved, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._completionTask, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._targetRegistry, System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >.Add(), System.Threading.Tasks.Dataflow.Internal.Disposables.Nop, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferToTargets(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OutgoingLock, System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletion(), and System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletionOnceCompleted().
Referenced by System.Threading.Tasks.Dataflow.BufferBlock< T >.LinkTo(), and System.Threading.Tasks.Dataflow.BatchBlock< T >.LinkTo().