Terraria: Terraria.Audio.SoundEngine.PlayTrackedSound
PlayTrackedSound() [2/2]
static SlotId Terraria.Audio.SoundEngine.PlayTrackedSound (SoundStyle style, Vector2 position) inline static
Definition at line 109 of file SoundEngine.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        if (Main.dedServ || !IsAudioSupported)
        {
            return SlotId.Invalid;
        }
        return SoundPlayer.Play(style, position);
    }
References Terraria.Main.dedServ, ReLogic.Utilities.SlotId.Invalid, Terraria.Audio.SoundEngine.IsAudioSupported, and Terraria.Audio.SoundPlayer.Play().
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.Projectile.AI_131_FlameBurstShot(), Terraria.Projectile.AI_134_Ballista(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_138_ExplosiveTrap(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_143_MonkStaffT2Ghast(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_187_ShadowHand(), Terraria.Projectile.Kill(), Terraria.Initializers.AchievementInitializer.OnAchievementCompleted(), and Terraria.Player.UpdateBiomes().