Terraria: System.Threading.Tasks.Dataflow.Internal.SourceCore.OfferAsyncIfNecessary
OfferAsyncIfNecessary()
void System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessary (bool isReplacementReplica, bool outgoingLockKnownAcquired) inline private
Definition at line 527 of file SourceCore.cs.
    {
        if (_taskForOutputProcessing == null && _enableOffering && !_messages.IsEmpty)
        {
            OfferAsyncIfNecessary_Slow(isReplacementReplica, outgoingLockKnownAcquired);
        }
    }
References System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._enableOffering, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._messages, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._taskForOutputProcessing, and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessary_Slow().
Referenced by System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ConsumeMessage(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessaryWithValueLock(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferMessagesLoopCore(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferToTargets(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ReleaseReservation(), and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.TryReceive().