Terraria: System.Threading.Tasks.Dataflow.Internal.SourceCore.Complete
Complete()
void System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.Complete () inline package
Definition at line 403 of file SourceCore.cs.
    {
        lock (ValueLock)
        {
            _decliningPermanently = true;
            Task.Factory.StartNew(delegate(object state)
            {
                SourceCore<TOutput> sourceCore = (SourceCore<TOutput>)state;
                lock (sourceCore.OutgoingLock)
                {
                    lock (sourceCore.ValueLock)
                    {
                        sourceCore.CompleteBlockIfPossible();
                    }
                }
            }, this, CancellationToken.None, Common.GetCreationOptionsForTask(), TaskScheduler.Default);
        }
    }
References System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._decliningPermanently, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask(), System.Threading.CancellationToken.None, System.state, and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ValueLock.
Referenced by System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlock(), and System.Threading.Tasks.Dataflow.BufferBlock< T >.CompleteTargetIfPossible().