Terraria: System.Threading.Tasks.Dataflow.Internal.SourceCore.AddException
AddException()
void System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.AddException (Exception exception) inline package
Definition at line 376 of file SourceCore.cs.
    {
        lock (ValueLock)
        {
            Common.AddException(ref _exceptions, exception);
        }
    }
References System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._exceptions, System.Threading.Tasks.Dataflow.Internal.Common.AddException(), System.exception, and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ValueLock.
Referenced by System.Threading.Tasks.Dataflow.BufferBlock< T >.CompleteCore(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessary_Slow(), and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferMessagesLoopCore().