Terraria: System.Threading.Tasks.Dataflow.Internal.SourceCore.AddMessage
AddMessage()
void System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.AddMessage (TOutput item) inline package
Definition at line 329 of file SourceCore.cs.
    {
        if (!_decliningPermanently)
        {
            _messages.Enqueue(item);
            Interlocked.MemoryBarrier();
            if (_taskForOutputProcessing == null)
            {
                OfferAsyncIfNecessaryWithValueLock();
            }
        }
    }
References System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._messages, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._taskForOutputProcessing, System.item, System.Threading.Interlocked.MemoryBarrier(), and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessaryWithValueLock().
Referenced by System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlock(), System.Threading.Tasks.Dataflow.BufferBlock< T >.ConsumeAndStoreOneMessageIfAvailable(), and System.Threading.Tasks.Dataflow.BufferBlock< T >.OfferMessage().