Terraria: System.Threading.Tasks.Dataflow.Internal.SourceCore.OfferToTargets
OfferToTargets()
bool System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferToTargets (ITargetBlock< TOutput > linkToTarget = null) inline private
Definition at line 422 of file SourceCore.cs.
    {
        if (_nextMessageReservedFor != null)
        {
            return false;
        }
        DataflowMessageHeader header = default(DataflowMessageHeader);
        TOutput result = default(TOutput);
        bool flag = false;
        if (!Volatile.Read(ref _enableOffering))
        {
            if (linkToTarget == null)
            {
                return false;
            }
            flag = true;
        }
        if (_messages.TryPeek(out result))
        {
            header = new DataflowMessageHeader(_nextMessageId.Value);
        }
        bool messageWasAccepted = false;
        if (header.IsValid)
        {
            if (flag)
            {
                OfferMessageToTarget(header, result, linkToTarget, out messageWasAccepted);
            }
            else
            {
                TargetRegistry<TOutput>.LinkedTargetInfo linkedTargetInfo = _targetRegistry.FirstTargetNode;
                while (linkedTargetInfo != null)
                {
                    TargetRegistry<TOutput>.LinkedTargetInfo next = linkedTargetInfo.Next;
                    if (OfferMessageToTarget(header, result, linkedTargetInfo.Target, out messageWasAccepted))
                    {
                        break;
                    }
                    linkedTargetInfo = next;
                }
                if (!messageWasAccepted)
                {
                    lock (ValueLock)
                    {
                        _enableOffering = false;
                    }
                }
            }
        }
        if (messageWasAccepted)
        {
            lock (ValueLock)
            {
                if (_nextMessageId.Value == header.Id)
                {
                    _messages.TryDequeue(out var _);
                }
                _nextMessageId.Value++;
                _enableOffering = true;
                if (linkToTarget != null)
                {
                    CompleteBlockIfPossible();
                    OfferAsyncIfNecessary(isReplacementReplica: false, outgoingLockKnownAcquired: true);
                }
            }
            if (_itemsRemovedAction != null)
            {
                int arg = ((_itemCountingFunc == null) ? 1 : _itemCountingFunc(_owningSource, result, null));
                _itemsRemovedAction(_owningSource, arg);
            }
        }
        return messageWasAccepted;
    }
References System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._enableOffering, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._itemCountingFunc, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._itemsRemovedAction, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._messages, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._nextMessageId, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._nextMessageReservedFor, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._owningSource, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._targetRegistry, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.CompleteBlockIfPossible(), System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >.FirstTargetNode, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessary(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferMessageToTarget(), System.Threading.Volatile.Read(), System.Threading.Tasks.Dataflow.Internal.PaddedInt64.Value, and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ValueLock.
Referenced by System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.LinkTo(), and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferMessagesLoopCore().