Terraria: System.Threading.Tasks.Dataflow.Internal.SourceCore.ReleaseReservation
ReleaseReservation()
void System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ReleaseReservation (DataflowMessageHeader messageHeader, ITargetBlock< TOutput > target) inline package
Definition at line 231 of file SourceCore.cs.
    {
        if (!messageHeader.IsValid)
        {
            throw new ArgumentException(System.SR.Argument_InvalidMessageHeader, "messageHeader");
        }
        if (target == null)
        {
            throw new ArgumentNullException("target");
        }
        lock (OutgoingLock)
        {
            if (_nextMessageReservedFor != target)
            {
                throw new InvalidOperationException(System.SR.InvalidOperation_MessageNotReservedByTarget);
            }
            lock (ValueLock)
            {
                if (messageHeader.Id != _nextMessageId.Value || _messages.IsEmpty)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_MessageNotReservedByTarget);
                }
                _nextMessageReservedFor = null;
                _enableOffering = true;
                OfferAsyncIfNecessary(isReplacementReplica: false, outgoingLockKnownAcquired: true);
                CompleteBlockIfPossible();
            }
        }
    }
References System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._enableOffering, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._messages, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._nextMessageId, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._nextMessageReservedFor, System.SR.Argument_InvalidMessageHeader, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.CompleteBlockIfPossible(), System.SR.InvalidOperation_MessageNotReservedByTarget, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferAsyncIfNecessary(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OutgoingLock, System.Threading.Tasks.Dataflow.Internal.PaddedInt64.Value, and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ValueLock.
Referenced by System.Threading.Tasks.Dataflow.BufferBlock< T >.ReleaseReservation(), and System.Threading.Tasks.Dataflow.BatchBlock< T >.ReleaseReservation().