Terraria: System.Threading.Tasks.Dataflow.Internal.SourceCore.CompleteBlockIfPossible
CompleteBlockIfPossible()
void System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.CompleteBlockIfPossible () inline private
Definition at line 620 of file SourceCore.cs.
    {
        if (!_completionReserved && _decliningPermanently && _taskForOutputProcessing == null && _nextMessageReservedFor == null)
        {
            CompleteBlockIfPossible_Slow();
        }
    }
References System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._completionReserved, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._nextMessageReservedFor, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >._taskForOutputProcessing, and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.CompleteBlockIfPossible_Slow().
Referenced by System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ConsumeMessage(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferMessagesLoopCore(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferToTargets(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ReleaseReservation(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.TryReceive(), and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.TryReceiveAll().