Terraria: Terraria.GameContent.UI.CustomCurrencySingleCoin.TryPurchasing
TryPurchasing()
override bool Terraria.GameContent.UI.CustomCurrencySingleCoin.TryPurchasing (long price, List< Item[]> inv, List< Point > slotCoins, List< Point > slotsEmpty, List< Point > slotEmptyBank, List< Point > slotEmptyBank2, List< Point > slotEmptyBank3, List< Point > slotEmptyBank4) inline virtual
Reimplemented from Terraria.GameContent.UI.CustomCurrencySystem.
Definition at line 25 of file CustomCurrencySingleCoin.cs.
    {
        List<Tuple<Point, Item>> cache = ItemCacheCreate(inv);
        long num = price;
        for (int i = 0; i < slotCoins.Count; i++)
        {
            Point item = slotCoins[i];
            long num2 = num;
            if (inv[item.X][item.Y].stack < num2)
            {
                num2 = inv[item.X][item.Y].stack;
            }
            num -= num2;
            inv[item.X][item.Y].stack -= (int)num2;
            if (inv[item.X][item.Y].stack == 0)
            {
                switch (item.X)
                {
                case 0:
                    slotsEmpty.Add(item);
                    break;
                case 1:
                    slotEmptyBank.Add(item);
                    break;
                case 2:
                    slotEmptyBank2.Add(item);
                    break;
                case 3:
                    slotEmptyBank3.Add(item);
                    break;
                case 4:
                    slotEmptyBank4.Add(item);
                    break;
                }
                slotCoins.Remove(item);
                i--;
            }
            if (num == 0L)
            {
                break;
            }
        }
        if (num != 0L)
        {
            ItemCacheRestore(cache, inv);
            return false;
        }
        return true;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.item, Terraria.GameContent.UI.CustomCurrencySystem.ItemCacheCreate(), Terraria.GameContent.UI.CustomCurrencySystem.ItemCacheRestore(), System.L, and System.Collections.Generic.Dictionary< TKey, TValue >.Remove().