Terraria: System.Text.Json.Serialization.Converters.EnumConverter.ReadAsPropertyNameCore
ReadAsPropertyNameCore()
override T System.Text.Json.Serialization.Converters.EnumConverter< T >.ReadAsPropertyNameCore (ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) inline package virtual
Reimplemented from System.Text.Json.Serialization.JsonConverter< T >.
Definition at line 256 of file EnumConverter.cs.
    {
        string @string = reader.GetString();
        if (!Enum.TryParse<T>(@string, out var result) && !Enum.TryParse<T>(@string, ignoreCase: true, out result))
        {
            ThrowHelper.ThrowJsonException();
        }
        return result;
    }
References System.Text.Json.Dictionary, System.Text.Json.ThrowHelper.ThrowJsonException(), and System.Enum.TryParse().
Referenced by System.Text.Json.Serialization.Converters.EnumConverter< T >.Read().