Terraria: System.Text.Json.Serialization.Converters.EnumConverter.WriteAsPropertyNameCore
WriteAsPropertyNameCore()
override void System.Text.Json.Serialization.Converters.EnumConverter< T >.WriteAsPropertyNameCore (Utf8JsonWriter writer, T value, JsonSerializerOptions options, bool isWritingExtensionDataProperty) inline package virtual
Reimplemented from System.Text.Json.Serialization.JsonConverter< T >.
Definition at line 266 of file EnumConverter.cs.
    {
        ulong key = ConvertToUInt64(value);
        JsonEncodedText value3;
        if (options.DictionaryKeyPolicy != null)
        {
            if (_dictionaryKeyPolicyCache != null && _dictionaryKeyPolicyCache.TryGetValue(key, out var value2))
            {
                writer.WritePropertyName(value2);
                return;
            }
        }
        else if (_nameCache.TryGetValue(key, out value3))
        {
            writer.WritePropertyName(value3);
            return;
        }
        string text = value.ToString();
        if (IsValidIdentifier(text))
        {
            if (options.DictionaryKeyPolicy != null)
            {
                text = options.DictionaryKeyPolicy.ConvertName(text);
                if (text == null)
                {
                    ThrowHelper.ThrowInvalidOperationException_NamingPolicyReturnNull(options.DictionaryKeyPolicy);
                }
                if (_dictionaryKeyPolicyCache == null)
                {
                    _dictionaryKeyPolicyCache = new ConcurrentDictionary<ulong, JsonEncodedText>();
                }
                if (_dictionaryKeyPolicyCache.Count < 64)
                {
                    JavaScriptEncoder encoder = options.Encoder;
                    JsonEncodedText jsonEncodedText = JsonEncodedText.Encode(text, encoder);
                    writer.WritePropertyName(jsonEncodedText);
                    _dictionaryKeyPolicyCache.TryAdd(key, jsonEncodedText);
                }
                else
                {
                    writer.WritePropertyName(text);
                }
            }
            else
            {
                JavaScriptEncoder encoder2 = options.Encoder;
                if (_nameCache.Count < 64)
                {
                    JsonEncodedText jsonEncodedText2 = JsonEncodedText.Encode(text, encoder2);
                    writer.WritePropertyName(jsonEncodedText2);
                    _nameCache.TryAdd(key, jsonEncodedText2);
                }
                else
                {
                    writer.WritePropertyName(text);
                }
            }
            return;
        }
        switch (s_enumTypeCode)
        {
        case TypeCode.Int32:
            writer.WritePropertyName(Unsafe.As<T, int>(ref value));
            break;
        case TypeCode.UInt32:
            writer.WritePropertyName(Unsafe.As<T, uint>(ref value));
            break;
        case TypeCode.UInt64:
            writer.WritePropertyName(Unsafe.As<T, ulong>(ref value));
            break;
        case TypeCode.Int64:
            writer.WritePropertyName(Unsafe.As<T, long>(ref value));
            break;
        case TypeCode.Int16:
            writer.WritePropertyName(Unsafe.As<T, short>(ref value));
            break;
        case TypeCode.UInt16:
            writer.WritePropertyName(Unsafe.As<T, ushort>(ref value));
            break;
        case TypeCode.Byte:
            writer.WritePropertyName(Unsafe.As<T, byte>(ref value));
            break;
        case TypeCode.SByte:
            writer.WritePropertyName(Unsafe.As<T, sbyte>(ref value));
            break;
        default:
            ThrowHelper.ThrowJsonException();
            break;
        }
    }
References System.Text.Json.Serialization.Converters.EnumConverter< T >._dictionaryKeyPolicyCache, System.Text.Json.Serialization.Converters.EnumConverter< T >._nameCache, System.Text.Json.Serialization.Converters.EnumConverter< T >.ConvertToUInt64(), System.Text.Json.Dictionary, System.Text.Json.JsonEncodedText.Encode(), System.Text.Json.Serialization.Converters.EnumConverter< T >.IsValidIdentifier(), System.key, System.options, System.Text.Json.Serialization.Converters.EnumConverter< T >.s_enumTypeCode, System.text, System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NamingPolicyReturnNull(), System.Text.Json.ThrowHelper.ThrowJsonException(), System.Text.Json.JsonEncodedText.ToString(), System.value, and System.writer.