Terraria: System.Text.Json.Serialization.Converters.EnumConverter.Write
Write()
override void System.Text.Json.Serialization.Converters.EnumConverter< T >.Write (Utf8JsonWriter writer, T value, JsonSerializerOptions options) inline
Definition at line 144 of file EnumConverter.cs.
    {
        if (_converterOptions.HasFlag(EnumConverterOptions.AllowStrings))
        {
            ulong key = ConvertToUInt64(value);
            if (_nameCache.TryGetValue(key, out var value2))
            {
                writer.WriteStringValue(value2);
                return;
            }
            string text = value.ToString();
            if (IsValidIdentifier(text))
            {
                JavaScriptEncoder encoder = options.Encoder;
                if (_nameCache.Count < 64)
                {
                    value2 = ((_namingPolicy == null) ? JsonEncodedText.Encode(text, encoder) : FormatEnumValue(text, encoder));
                    writer.WriteStringValue(value2);
                    _nameCache.TryAdd(key, value2);
                }
                else
                {
                    writer.WriteStringValue((_namingPolicy == null) ? text : FormatEnumValueToString(text, encoder));
                }
                return;
            }
        }
        if (!_converterOptions.HasFlag(EnumConverterOptions.AllowNumbers))
        {
            ThrowHelper.ThrowJsonException();
        }
        switch (s_enumTypeCode)
        {
        case TypeCode.Int32:
            writer.WriteNumberValue(Unsafe.As<T, int>(ref value));
            break;
        case TypeCode.UInt32:
            writer.WriteNumberValue(Unsafe.As<T, uint>(ref value));
            break;
        case TypeCode.UInt64:
            writer.WriteNumberValue(Unsafe.As<T, ulong>(ref value));
            break;
        case TypeCode.Int64:
            writer.WriteNumberValue(Unsafe.As<T, long>(ref value));
            break;
        case TypeCode.Int16:
            writer.WriteNumberValue(Unsafe.As<T, short>(ref value));
            break;
        case TypeCode.UInt16:
            writer.WriteNumberValue(Unsafe.As<T, ushort>(ref value));
            break;
        case TypeCode.Byte:
            writer.WriteNumberValue(Unsafe.As<T, byte>(ref value));
            break;
        case TypeCode.SByte:
            writer.WriteNumberValue(Unsafe.As<T, sbyte>(ref value));
            break;
        default:
            ThrowHelper.ThrowJsonException();
            break;
        }
    }
References System.Text.Json.Serialization.Converters.EnumConverter< T >._converterOptions, System.Text.Json.Serialization.Converters.EnumConverter< T >._nameCache, System.Text.Json.Serialization.Converters.EnumConverter< T >._namingPolicy, System.Text.Json.Serialization.Converters.EnumConverter< T >.ConvertToUInt64(), System.Text.Json.Dictionary, System.Text.Json.JsonEncodedText.Encode(), System.Text.Json.Serialization.Converters.EnumConverter< T >.FormatEnumValue(), System.Text.Json.Serialization.Converters.EnumConverter< T >.FormatEnumValueToString(), System.Text.Json.Serialization.Converters.EnumConverter< T >.IsValidIdentifier(), System.key, System.options, System.Text.Json.Serialization.Converters.EnumConverter< T >.s_enumTypeCode, System.text, System.Text.Json.ThrowHelper.ThrowJsonException(), System.value, and System.writer.