Terraria: System.Text.Json.Serialization.Converters.EnumConverter.EnumConverter
EnumConverter() [2/2]
System.Text.Json.Serialization.Converters.EnumConverter< T >.EnumConverter (EnumConverterOptions converterOptions, JsonNamingPolicy namingPolicy, JsonSerializerOptions serializerOptions) inline
Definition at line 32 of file EnumConverter.cs.
    {
        _converterOptions = converterOptions;
        _namingPolicy = namingPolicy;
        _nameCache = new ConcurrentDictionary<ulong, JsonEncodedText>();
        string[] names = Enum.GetNames(TypeToConvert);
        Array values = Enum.GetValues(TypeToConvert);
        JavaScriptEncoder encoder = serializerOptions.Encoder;
        for (int i = 0; i < names.Length; i++)
        {
            if (_nameCache.Count >= 64)
            {
                break;
            }
            T val = (T)values.GetValue(i);
            ulong key = ConvertToUInt64(val);
            string value = names[i];
            _nameCache.TryAdd(key, (namingPolicy == null) ? JsonEncodedText.Encode(value, encoder) : FormatEnumValue(value, encoder));
        }
    }
References System.Text.Json.Serialization.Converters.EnumConverter< T >._converterOptions, System.Text.Json.Serialization.Converters.EnumConverter< T >._nameCache, System.Text.Json.Serialization.Converters.EnumConverter< T >._namingPolicy, System.Text.Json.Serialization.Converters.EnumConverter< T >.ConvertToUInt64(), System.Text.Json.Dictionary, System.Text.Json.JsonEncodedText.Encode(), System.Text.Json.Serialization.Converters.EnumConverter< T >.FormatEnumValue(), System.Enum.GetNames(), System.Enum.GetValues(), System.key, System.T, System.Text.Json.Serialization.JsonConverter< T >.TypeToConvert, System.value, and System.values.