Terraria: System.Text.Json.Serialization.Converters.EnumConverter.FormatEnumValueToString
FormatEnumValueToString()
string System.Text.Json.Serialization.Converters.EnumConverter< T >.FormatEnumValueToString (string value, JavaScriptEncoder encoder) inline private
Definition at line 242 of file EnumConverter.cs.
    {
        if (!value.Contains(", "))
        {
            return _namingPolicy.ConvertName(value);
        }
        string[] array = value.Split(", ");
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = _namingPolicy.ConvertName(array[i]);
        }
        return string.Join(", ", array);
    }
References System.Text.Json.Serialization.Converters.EnumConverter< T >._namingPolicy, System.array, System.Text.Json.JsonNamingPolicy.ConvertName(), and System.value.
Referenced by System.Text.Json.Serialization.Converters.EnumConverter< T >.FormatEnumValue(), and System.Text.Json.Serialization.Converters.EnumConverter< T >.Write().