Terraria: BackgroundChangeFlashInfo.UpdateCache
UpdateCache()
void BackgroundChangeFlashInfo.UpdateCache () inline
     {
         UpdateVariation(0, WorldGen.treeBG1);
         UpdateVariation(1, WorldGen.treeBG2);
         UpdateVariation(2, WorldGen.treeBG3);
         UpdateVariation(3, WorldGen.treeBG4);
         UpdateVariation(4, WorldGen.corruptBG);
         UpdateVariation(5, WorldGen.jungleBG);
         UpdateVariation(6, WorldGen.snowBG);
         UpdateVariation(7, WorldGen.hallowBG);
         UpdateVariation(8, WorldGen.crimsonBG);
         UpdateVariation(9, WorldGen.desertBG);
         UpdateVariation(10, WorldGen.oceanBG);
         UpdateVariation(11, WorldGen.mushroomBG);
         UpdateVariation(12, WorldGen.underworldBG);
     }
References WorldGen.corruptBG, WorldGen.crimsonBG, WorldGen.desertBG, WorldGen.hallowBG, WorldGen.jungleBG, WorldGen.mushroomBG, WorldGen.oceanBG, WorldGen.snowBG, WorldGen.treeBG1, WorldGen.treeBG2, WorldGen.treeBG3, WorldGen.treeBG4, WorldGen.underworldBG, and UpdateVariation().
Referenced by MessageBuffer.GetData(), and WorldGen.RandomizeBackgroundBasedOnPlayer().