Terraria: Terraria.GameContent.NetModules.NetParticlesModule.Deserialize
Deserialize()
override bool Terraria.GameContent.NetModules.NetParticlesModule.Deserialize (BinaryReader reader, int userId) inline
Definition at line 17 of file NetParticlesModule.cs.
    {
        ParticleOrchestraType particleOrchestraType = (ParticleOrchestraType)reader.ReadByte();
        ParticleOrchestraSettings settings = default(ParticleOrchestraSettings);
        settings.DeserializeFrom(reader);
        if (Main.netMode == 2)
        {
            NetManager.Instance.Broadcast(Serialize(particleOrchestraType, settings), userId);
        }
        else
        {
            ParticleOrchestrator.SpawnParticlesDirect(particleOrchestraType, settings);
        }
        return true;
    }
References Terraria.GameContent.Drawing.ParticleOrchestraSettings.DeserializeFrom(), Terraria.Net.NetManager.Instance, Terraria.Main.netMode, System.IO.BinaryReader.ReadByte(), Terraria.GameContent.NetModules.NetParticlesModule.Serialize(), and Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().