Terraria: Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.Deserialize_SyncEveryone
Deserialize_SyncEveryone()
void Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.Deserialize_SyncEveryone (BinaryReader reader, int userId) inline private inherited
Definition at line 78 of file CreativePowers.cs.
        {
            int num = (int)Math.Ceiling((float)_perPlayerIsEnabled.Length / 8f);
            if (Main.netMode == 2 && !CreativePowersHelper.IsAvailableForPlayer(this, userId))
            {
                reader.ReadBytes(num);
                return;
            }
            for (int i = 0; i < num; i++)
            {
                BitsByte bitsByte = reader.ReadByte();
                for (int j = 0; j < 8; j++)
                {
                    int num2 = i * 8 + j;
                    if (num2 != Main.myPlayer)
                    {
                        if (num2 >= _perPlayerIsEnabled.Length)
{
                            break;
                        }
                        SetEnabledState(num2, bitsByte[j]);
                    }
                }
            }
        }
References Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower._perPlayerIsEnabled, System.Math.Ceiling(), Terraria.GameContent.Creative.CreativePowersHelper.IsAvailableForPlayer(), Terraria.Main.myPlayer, Terraria.Main.netMode, System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadBytes(), and Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.SetEnabledState().
Referenced by Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.DeserializeNetMessage().