Terraria: System.Collections.Immutable.ImmutableArray.Builder.IndexOf
IndexOf() [2/5]
int System.Collections.Immutable.ImmutableArray< T >.Builder.IndexOf (T item) inline
Definition at line 515 of file ImmutableArray.cs.
        {
            return IndexOf(item, 0, _count, EqualityComparer<T>.Default);
        }
References System.Collections.Immutable.ImmutableArray< T >.Builder._count, System.Default, System.Collections.Immutable.ImmutableArray< T >.Builder.IndexOf(), and System.item.
Referenced by System.Collections.Immutable.ImmutableArray< T >.Builder.Contains(), System.Collections.Immutable.ImmutableArray< T >.Builder.IndexOf(), System.Collections.Immutable.ImmutableArray< T >.Builder.IndexOf(), System.Collections.Immutable.ImmutableArray< T >.Builder.IndexOf(), and System.Collections.Immutable.ImmutableArray< T >.Builder.Remove().