Terraria: System.Collections.Immutable.ImmutableArray.Builder.AddRange
AddRange() [2/6]
void System.Collections.Immutable.ImmutableArray< T >.Builder.AddRange (IEnumerable< T > items) inline
Definition at line 385 of file ImmutableArray.cs.
        {
            Requires.NotNull(items, "items");
            if (items.TryGetCount(out var count))
            {
                EnsureCapacity(Count + count);
                if (items.TryCopyTo(_elements, _count))
                {
                    _count += count;
                    return;
                }
            }
            foreach (T item in items)
            {
                Add(item);
            }
        }
References System.Collections.Immutable.ImmutableArray< T >.Builder._count, System.Collections.Immutable.ImmutableArray< T >.Builder._elements, System.Add, System.Collections.Immutable.ImmutableArray< T >.Builder.Count, System.count, System.Collections.Immutable.ImmutableArray< T >.Builder.EnsureCapacity(), and System.item.
Referenced by System.Collections.Immutable.ImmutableArray< T >.Builder.AddRange(), System.Collections.Immutable.ImmutableArray< T >.Builder.AddRange(), and System.Collections.Immutable.ImmutableArray< T >.Builder.AddRange().