Terraria: System.Collections.Immutable.ImmutableArray.Builder.EnsureCapacity
EnsureCapacity()
void System.Collections.Immutable.ImmutableArray< T >.Builder.EnsureCapacity (int capacity) inline private
Definition at line 506 of file ImmutableArray.cs.
        {
            if (_elements.Length < capacity)
            {
                int newSize = Math.Max(_elements.Length * 2, capacity);
                Array.Resize(ref _elements, newSize);
            }
        }
References System.Collections.Immutable.ImmutableArray< T >.Builder._elements, System.capacity, System.Math.Max(), and System.newSize.
Referenced by System.Collections.Immutable.ImmutableArray< T >.Builder.Add(), System.Collections.Immutable.ImmutableArray< T >.Builder.AddRange(), System.Collections.Immutable.ImmutableArray< T >.Builder.AddRange< TDerived >(), and System.Collections.Immutable.ImmutableArray< T >.Builder.Insert().