Terraria: Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.ProvidePowerButtons
ProvidePowerButtons()
void Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.ProvidePowerButtons (CreativePowerUIElementRequestInfo info, List< UIElement > elements) inline inherited
Implements Terraria.GameContent.Creative.ICreativePower.
Definition at line 161 of file CreativePowers.cs.
        {
            GroupOptionButton<bool> groupOptionButton = CreativePowersHelper.CreateToggleButton(info);
            CreativePowersHelper.UpdateUnlockStateByPower(this, groupOptionButton, Main.OurFavoriteColor);
            groupOptionButton.Append(CreativePowersHelper.GetIconImage(_iconLocation));
            groupOptionButton.OnLeftClick += button_OnClick;
            groupOptionButton.OnUpdate += button_OnUpdate;
            elements.Add(groupOptionButton);
        }
References Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower._iconLocation, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.button_OnClick(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowersHelper.CreateToggleButton(), Terraria.GameContent.Creative.CreativePowersHelper.GetIconImage(), System.info, Terraria.Main.OurFavoriteColor, and Terraria.GameContent.Creative.CreativePowersHelper.UpdateUnlockStateByPower().