Terraria: System.StubHelpers.AsAnyMarshaler.ConvertToManaged
ConvertToManaged()
unsafe void System.StubHelpers.AsAnyMarshaler.ConvertToManaged (object pManagedHome, IntPtr pNativeHome) inline package
Definition at line 252 of file AsAnyMarshaler.cs.
    {
        switch (backPropAction)
        {
        case BackPropAction.Array:
            MngdNativeArrayMarshaler.ConvertContentsToManaged(pvArrayMarshaler, ref pManagedHome, new IntPtr(&pNativeHome));
            break;
        case BackPropAction.Layout:
            StubHelpers.FmtClassUpdateCLRInternal(pManagedHome, (byte*)(void*)pNativeHome);
            break;
        case BackPropAction.StringBuilderAnsi:
        {
            int newLength2 = ((!(pNativeHome == IntPtr.Zero)) ? string.strlen((byte*)(void*)pNativeHome) : 0);
            ((StringBuilder)pManagedHome).ReplaceBufferAnsiInternal((sbyte*)(void*)pNativeHome, newLength2);
            break;
        }
        case BackPropAction.StringBuilderUnicode:
        {
            int newLength = ((!(pNativeHome == IntPtr.Zero)) ? string.wcslen((char*)(void*)pNativeHome) : 0);
            ((StringBuilder)pManagedHome).ReplaceBufferInternal((char*)(void*)pNativeHome, newLength);
            break;
        }
        }
    }
References System.StubHelpers.AsAnyMarshaler.backPropAction, System.StubHelpers.MngdNativeArrayMarshaler.ConvertContentsToManaged(), System.StubHelpers.StubHelpers.FmtClassUpdateCLRInternal(), System.StubHelpers.AsAnyMarshaler.pvArrayMarshaler, and System.IntPtr.Zero.
Referenced by System.Runtime.InteropServices.Marshal.WriteValueSlow< T >().