Terraria: System.StubHelpers.AsAnyMarshaler.ClearNative
ClearNative()
void System.StubHelpers.AsAnyMarshaler.ClearNative (IntPtr pNativeHome) inline package
Definition at line 277 of file AsAnyMarshaler.cs.
    {
        if (pNativeHome != IntPtr.Zero)
        {
            if (layoutType != null)
            {
                Marshal.DestroyStructure(pNativeHome, layoutType);
            }
            Marshal.FreeCoTaskMem(pNativeHome);
        }
        StubHelpers.DestroyCleanupList(ref cleanupWorkList);
    }
References System.StubHelpers.AsAnyMarshaler.cleanupWorkList, System.StubHelpers.StubHelpers.DestroyCleanupList(), System.Runtime.InteropServices.Marshal.DestroyStructure(), System.Runtime.InteropServices.Marshal.FreeCoTaskMem(), System.StubHelpers.AsAnyMarshaler.layoutType, and System.IntPtr.Zero.
Referenced by System.Runtime.InteropServices.Marshal.ReadValueSlow< T >(), and System.Runtime.InteropServices.Marshal.WriteValueSlow< T >().