Terraria: System.StubHelpers.AsAnyMarshaler.ConvertArrayToNative
ConvertArrayToNative()
unsafe IntPtr System.StubHelpers.AsAnyMarshaler.ConvertArrayToNative (object pManagedHome, int dwFlags) inline private
Definition at line 59 of file AsAnyMarshaler.cs.
    {
        Type elementType = pManagedHome.GetType().GetElementType();
        VarEnum varEnum = VarEnum.VT_EMPTY;
        switch (Type.GetTypeCode(elementType))
        {
        case TypeCode.SByte:
            varEnum = VarEnum.VT_I1;
            break;
        case TypeCode.Byte:
            varEnum = VarEnum.VT_UI1;
            break;
        case TypeCode.Int16:
            varEnum = VarEnum.VT_I2;
            break;
        case TypeCode.UInt16:
            varEnum = VarEnum.VT_UI2;
            break;
        case TypeCode.Int32:
            varEnum = VarEnum.VT_I4;
            break;
        case TypeCode.UInt32:
            varEnum = VarEnum.VT_UI4;
            break;
        case TypeCode.Int64:
            varEnum = VarEnum.VT_I8;
            break;
        case TypeCode.UInt64:
            varEnum = VarEnum.VT_UI8;
            break;
        case TypeCode.Single:
            varEnum = VarEnum.VT_R4;
            break;
        case TypeCode.Double:
            varEnum = VarEnum.VT_R8;
            break;
        case TypeCode.Char:
            varEnum = (IsAnsi(dwFlags) ? ((VarEnum)253) : VarEnum.VT_UI2);
            break;
        case TypeCode.Boolean:
            varEnum = (VarEnum)254;
            break;
        case TypeCode.Object:
            if (elementType == typeof(IntPtr))
            {
                _ = IntPtr.Size;
                varEnum = VarEnum.VT_I8;
                break;
            }
            if (elementType == typeof(UIntPtr))
            {
                _ = IntPtr.Size;
                varEnum = VarEnum.VT_UI8;
                break;
            }
            goto default;
        default:
            throw new ArgumentException(SR.Arg_NDirectBadObject);
        }
        int num = (int)varEnum;
        if (IsBestFit(dwFlags))
        {
            num |= 0x10000;
        }
        if (IsThrowOn(dwFlags))
        {
            num |= 0x1000000;
        }
        MngdNativeArrayMarshaler.CreateMarshaler(pvArrayMarshaler, IntPtr.Zero, num, IntPtr.Zero);
        System.Runtime.CompilerServices.Unsafe.SkipInit(out IntPtr result);
        IntPtr pNativeHome = new IntPtr(&result);
        MngdNativeArrayMarshaler.ConvertSpaceToNative(pvArrayMarshaler, ref pManagedHome, pNativeHome);
        if (IsIn(dwFlags))
        {
            MngdNativeArrayMarshaler.ConvertContentsToNative(pvArrayMarshaler, ref pManagedHome, pNativeHome);
        }
        if (IsOut(dwFlags))
        {
            backPropAction = BackPropAction.Array;
        }
        return result;
    }
References System.SR.Arg_NDirectBadObject, System.StubHelpers.AsAnyMarshaler.backPropAction, System.StubHelpers.MngdNativeArrayMarshaler.ConvertContentsToNative(), System.StubHelpers.MngdNativeArrayMarshaler.ConvertSpaceToNative(), System.StubHelpers.MngdNativeArrayMarshaler.CreateMarshaler(), System.elementType, System.Type.GetTypeCode(), System.StubHelpers.AsAnyMarshaler.IsAnsi(), System.StubHelpers.AsAnyMarshaler.IsBestFit(), System.StubHelpers.AsAnyMarshaler.IsIn(), System.StubHelpers.AsAnyMarshaler.IsOut(), System.StubHelpers.AsAnyMarshaler.IsThrowOn(), System.StubHelpers.AsAnyMarshaler.pvArrayMarshaler, System.IntPtr.Size, and System.IntPtr.Zero.
Referenced by System.StubHelpers.AsAnyMarshaler.ConvertToNative().