Terraria: System.StubHelpers.AsAnyMarshaler.ConvertStringToNative
ConvertStringToNative()
static unsafe IntPtr System.StubHelpers.AsAnyMarshaler.ConvertStringToNative (string pManagedHome, int dwFlags) inline static private
Definition at line 142 of file AsAnyMarshaler.cs.
    {
        IntPtr intPtr;
        if (IsAnsi(dwFlags))
        {
            intPtr = CSTRMarshaler.ConvertToNative(dwFlags & 0xFFFF, pManagedHome, IntPtr.Zero);
        }
        else
        {
            int cb = (pManagedHome.Length + 1) * 2;
            intPtr = Marshal.AllocCoTaskMem(cb);
            Buffer.Memmove(ref *(char*)(void*)intPtr, ref pManagedHome.GetRawStringData(), (nuint)pManagedHome.Length + (nuint)1u);
        }
        return intPtr;
    }
References System.Runtime.InteropServices.Marshal.AllocCoTaskMem(), System.StubHelpers.CSTRMarshaler.ConvertToNative(), System.StubHelpers.AsAnyMarshaler.IsAnsi(), System.Buffer.Memmove(), and System.IntPtr.Zero.
Referenced by System.StubHelpers.AsAnyMarshaler.ConvertToNative().