Terraria: System.StubHelpers.AsAnyMarshaler.ConvertStringBuilderToNative
ConvertStringBuilderToNative()
unsafe IntPtr System.StubHelpers.AsAnyMarshaler.ConvertStringBuilderToNative (StringBuilder pManagedHome, int dwFlags) inline private
Definition at line 158 of file AsAnyMarshaler.cs.
    {
        int capacity = pManagedHome.Capacity;
        int length = pManagedHome.Length;
        if (length > capacity)
        {
            ThrowHelper.ThrowInvalidOperationException();
        }
        IntPtr intPtr;
        if (IsAnsi(dwFlags))
        {
            StubHelpers.CheckStringLength(capacity);
            int num = checked(capacity * Marshal.SystemMaxDBCSCharSize + 4);
            intPtr = Marshal.AllocCoTaskMem(num);
            byte* ptr = (byte*)(void*)intPtr;
            *(ptr + num - 3) = 0;
            *(ptr + num - 2) = 0;
            *(ptr + num - 1) = 0;
            if (IsIn(dwFlags))
            {
                int num2 = Marshal.StringToAnsiString(pManagedHome.ToString(), ptr, num, IsBestFit(dwFlags), IsThrowOn(dwFlags));
            }
            if (IsOut(dwFlags))
            {
                backPropAction = BackPropAction.StringBuilderAnsi;
            }
        }
        else
        {
            int num3 = checked(capacity * 2 + 4);
            intPtr = Marshal.AllocCoTaskMem(num3);
            byte* ptr2 = (byte*)(void*)intPtr;
            *(ptr2 + num3 - 1) = 0;
            *(ptr2 + num3 - 2) = 0;
            if (IsIn(dwFlags))
            {
                pManagedHome.InternalCopy(intPtr, length);
                int num4 = length * 2;
                ptr2[num4] = 0;
                (ptr2 + num4)[1] = 0;
            }
            if (IsOut(dwFlags))
            {
                backPropAction = BackPropAction.StringBuilderUnicode;
            }
        }
        return intPtr;
    }
References System.Runtime.InteropServices.Marshal.AllocCoTaskMem(), System.StubHelpers.AsAnyMarshaler.backPropAction, System.Text.StringBuilder.Capacity, System.capacity, System.StubHelpers.StubHelpers.CheckStringLength(), System.Text.StringBuilder.InternalCopy(), System.StubHelpers.AsAnyMarshaler.IsAnsi(), System.StubHelpers.AsAnyMarshaler.IsBestFit(), System.StubHelpers.AsAnyMarshaler.IsIn(), System.StubHelpers.AsAnyMarshaler.IsOut(), System.StubHelpers.AsAnyMarshaler.IsThrowOn(), System.length, System.Text.StringBuilder.Length, System.Runtime.InteropServices.Marshal.StringToAnsiString(), System.Runtime.InteropServices.Marshal.SystemMaxDBCSCharSize, System.ThrowHelper.ThrowInvalidOperationException(), and System.Text.StringBuilder.ToString().
Referenced by System.StubHelpers.AsAnyMarshaler.ConvertToNative().