Terraria: System.StubHelpers.AsAnyMarshaler.ConvertLayoutToNative
ConvertLayoutToNative()
unsafe IntPtr System.StubHelpers.AsAnyMarshaler.ConvertLayoutToNative (object pManagedHome, int dwFlags) inline private
Definition at line 207 of file AsAnyMarshaler.cs.
    {
        int cb = Marshal.SizeOfHelper(pManagedHome.GetType(), throwIfNotMarshalable: false);
        IntPtr intPtr = Marshal.AllocCoTaskMem(cb);
        if (IsIn(dwFlags))
        {
            StubHelpers.FmtClassUpdateNativeInternal(pManagedHome, (byte*)(void*)intPtr, ref cleanupWorkList);
        }
        if (IsOut(dwFlags))
        {
            backPropAction = BackPropAction.Layout;
        }
        layoutType = pManagedHome.GetType();
        return intPtr;
    }
References System.Runtime.InteropServices.Marshal.AllocCoTaskMem(), System.StubHelpers.AsAnyMarshaler.backPropAction, System.StubHelpers.AsAnyMarshaler.cleanupWorkList, System.StubHelpers.StubHelpers.FmtClassUpdateNativeInternal(), System.StubHelpers.AsAnyMarshaler.IsIn(), System.StubHelpers.AsAnyMarshaler.IsOut(), System.StubHelpers.AsAnyMarshaler.layoutType, and System.Runtime.InteropServices.Marshal.SizeOfHelper().
Referenced by System.StubHelpers.AsAnyMarshaler.ConvertToNative().