Terraria: System.Reflection.Metadata.Ecma335.MethodSignatureEncoder.Parameters
Parameters() [2/2]
void System.Reflection.Metadata.Ecma335.MethodSignatureEncoder.Parameters (int parameterCount, out ReturnTypeEncoder returnType, out ParametersEncoder parameters) inline
Definition at line 15 of file MethodSignatureEncoder.cs.
    {
        if ((uint)parameterCount > 536870911u)
        {
            Throw.ArgumentOutOfRange("parameterCount");
        }
        Builder.WriteCompressedInteger(parameterCount);
        returnType = new ReturnTypeEncoder(Builder);
        parameters = new ParametersEncoder(Builder, HasVarArgs);
    }
References System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.Metadata.Ecma335.MethodSignatureEncoder.Builder, System.Reflection.Metadata.Ecma335.MethodSignatureEncoder.HasVarArgs, and System.Reflection.Metadata.BlobBuilder.WriteCompressedInteger().
Referenced by System.Reflection.Metadata.Ecma335.MethodSignatureEncoder.Parameters().