Terraria: System.Xml.AsyncHelper.DoneTaskTrue
DoneTaskTrue
readonly Task<bool> System.Xml.AsyncHelper.DoneTaskTrue = Task.FromResult(result: true) static
Definition at line 7 of file AsyncHelper.cs.
Referenced by System.Xml.AsyncHelper.ContinueBoolTaskFuncWhenFalseAsync< TArg >(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_CData(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_WhiteSpace(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.ParseTextAsync_IgnoreNode(), System.Xml.XmlTextReaderImpl.ReadAsync(), System.Xml.XsdValidatingReader.ReadAsync_ReadAhead(), System.Xml.XmlTextReaderImpl.ReadAsync_SwitchToInteractiveXmlDecl_Helper(), and System.Xml.AsyncHelper.ReturnTrueTaskWhenFinishAsync().