Terraria: System.ComponentModel.ICustomTypeDescriptor.GetComponentName
GetComponentName()
string? System.ComponentModel.ICustomTypeDescriptor.GetComponentName ()
Implemented in System.ComponentModel.CustomTypeDescriptor, System.ComponentModel.TypeDescriptor.ComNativeDescriptionProvider.ComNativeTypeDescriptor, System.ComponentModel.TypeDescriptor.MergedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor, System.Data.Common.DataRecordInternal, System.Data.Common.DbConnectionStringBuilder, System.Data.Common.DbDataRecord, System.Data.DataRowView, and System.Data.DataViewManagerListItemTypeDescriptor.
Referenced by System.ComponentModel.CustomTypeDescriptor.GetComponentName(), System.ComponentModel.TypeDescriptor.MergedTypeDescriptor.GetComponentName(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor.GetComponentName(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.GetComponentName(), and System.ComponentModel.TypeDescriptionProvider.GetFullComponentName().