Terraria: System.ComponentModel.ICustomTypeDescriptor.GetDefaultEvent
GetDefaultEvent()
EventDescriptor? System.ComponentModel.ICustomTypeDescriptor.GetDefaultEvent ()
Implemented in System.ComponentModel.CustomTypeDescriptor, System.ComponentModel.TypeDescriptor.ComNativeDescriptionProvider.ComNativeTypeDescriptor, System.ComponentModel.TypeDescriptor.MergedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor, System.Data.Common.DataRecordInternal, System.Data.Common.DbConnectionStringBuilder, System.Data.Common.DbDataRecord, System.Data.DataRowView, and System.Data.DataViewManagerListItemTypeDescriptor.
Referenced by System.ComponentModel.CustomTypeDescriptor.GetDefaultEvent(), System.ComponentModel.TypeDescriptor.MergedTypeDescriptor.GetDefaultEvent(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor.GetDefaultEvent(), and System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.GetDefaultEvent().