Terraria: System.ComponentModel.ICustomTypeDescriptor.GetConverter
GetConverter()
TypeConverter System.ComponentModel.ICustomTypeDescriptor.GetConverter ()
Implemented in System.ComponentModel.CustomTypeDescriptor, System.ComponentModel.TypeDescriptor.ComNativeDescriptionProvider.ComNativeTypeDescriptor, System.ComponentModel.TypeDescriptor.MergedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor, System.Data.Common.DataRecordInternal, System.Data.Common.DbConnectionStringBuilder, System.Data.Common.DbDataRecord, System.Data.DataRowView, and System.Data.DataViewManagerListItemTypeDescriptor.
Referenced by System.ComponentModel.CustomTypeDescriptor.GetConverter(), System.ComponentModel.TypeDescriptor.MergedTypeDescriptor.GetConverter(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor.GetConverter(), and System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.GetConverter().