Terraria: System.ComponentModel.ICustomTypeDescriptor.GetDefaultProperty
GetDefaultProperty()
PropertyDescriptor? System.ComponentModel.ICustomTypeDescriptor.GetDefaultProperty ()
Implemented in System.ComponentModel.CustomTypeDescriptor, System.ComponentModel.TypeDescriptor.ComNativeDescriptionProvider.ComNativeTypeDescriptor, System.ComponentModel.TypeDescriptor.MergedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor, System.Data.Common.DataRecordInternal, System.Data.Common.DbConnectionStringBuilder, System.Data.Common.DbDataRecord, System.Data.DataRowView, and System.Data.DataViewManagerListItemTypeDescriptor.
Referenced by System.ComponentModel.CustomTypeDescriptor.GetDefaultProperty(), System.ComponentModel.TypeDescriptor.MergedTypeDescriptor.GetDefaultProperty(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor.GetDefaultProperty(), and System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.GetDefaultProperty().