Terraria: System.ComponentModel.ICustomTypeDescriptor.GetAttributes
GetAttributes()
AttributeCollection System.ComponentModel.ICustomTypeDescriptor.GetAttributes ()
Implemented in System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptor, System.ComponentModel.CustomTypeDescriptor, System.ComponentModel.TypeDescriptor.ComNativeDescriptionProvider.ComNativeTypeDescriptor, System.ComponentModel.TypeDescriptor.AttributeProvider.AttributeTypeDescriptor, System.ComponentModel.TypeDescriptor.MergedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor, System.Data.Common.DataRecordInternal, System.Data.Common.DbConnectionStringBuilder, System.Data.Common.DbDataRecord, System.Data.DataRowView, and System.Data.DataViewManagerListItemTypeDescriptor.
Referenced by System.ComponentModel.CustomTypeDescriptor.GetAttributes(), System.ComponentModel.TypeDescriptor.MergedTypeDescriptor.GetAttributes(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor.GetAttributes(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.GetAttributes(), and System.ComponentModel.TypeDescriptor.GetAttributes().