Terraria: System.ComponentModel.ICustomTypeDescriptor.GetEvents
GetEvents() [1/2]
EventDescriptorCollection System.ComponentModel.ICustomTypeDescriptor.GetEvents ()
Implemented in System.ComponentModel.CustomTypeDescriptor, System.ComponentModel.TypeDescriptor.ComNativeDescriptionProvider.ComNativeTypeDescriptor, System.ComponentModel.TypeDescriptor.MergedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor, System.Data.Common.DataRecordInternal, System.Data.Common.DbConnectionStringBuilder, System.Data.Common.DbDataRecord, System.Data.DataRowView, and System.Data.DataViewManagerListItemTypeDescriptor.
Referenced by System.ComponentModel.CustomTypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.MergedTypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.MergedTypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.GetEvents(), System.ComponentModel.CustomTypeDescriptor.GetEvents(), and System.ComponentModel.TypeDescriptor.GetEvents().