Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.PopulateInterfaces
PopulateInterfaces()
RuntimeType[] System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateInterfaces (Filter filter) inline private
Definition at line 829 of file RuntimeType.cs.
            {
                ListBuilder<RuntimeType> list = default(ListBuilder<RuntimeType>);
                RuntimeType reflectedType = ReflectedType;
                if (!RuntimeTypeHandle.IsGenericVariable(reflectedType))
                {
                    Type[] interfaces = RuntimeTypeHandle.GetInterfaces(reflectedType);
                    if (interfaces != null)
                    {
                        for (int i = 0; i < interfaces.Length; i++)
{
                            RuntimeType runtimeType = (RuntimeType)interfaces[i];
                            if (!filter.RequiresStringComparison() || filter.Match(RuntimeTypeHandle.GetUtf8Name(runtimeType)))
{
                                list.Add(runtimeType);
                            }
                        }
                    }
                    if (ReflectedType.IsSZArray)
                    {
                        RuntimeType runtimeType2 = (RuntimeType)ReflectedType.GetElementType();
                        if (!runtimeType2.IsPointer)
{
                            AddSpecialInterface(ref list, filter, (RuntimeType)typeof(IList<>).MakeGenericType(runtimeType2), addSubInterface: true);
                            AddSpecialInterface(ref list, filter, (RuntimeType)typeof(IReadOnlyList<>).MakeGenericType(runtimeType2), addSubInterface: false);
                            AddSpecialInterface(ref list, filter, (RuntimeType)typeof(IReadOnlyCollection<>).MakeGenericType(runtimeType2), addSubInterface: false);
                        }
                    }
                }
                else
                {
                    HashSet<RuntimeType> hashSet = new HashSet<RuntimeType>();
                    Type[] genericParameterConstraints = reflectedType.GetGenericParameterConstraints();
                    for (int j = 0; j < genericParameterConstraints.Length; j++)
                    {
                        RuntimeType runtimeType3 = (RuntimeType)genericParameterConstraints[j];
                        if (runtimeType3.IsInterface)
{
                            hashSet.Add(runtimeType3);
                        }
                        Type[] interfaces2 = runtimeType3.GetInterfaces();
                        for (int k = 0; k < interfaces2.Length; k++)
{
                            hashSet.Add((RuntimeType)interfaces2[k]);
                        }
                    }
                    foreach (RuntimeType item in hashSet)
                    {
                        if (!filter.RequiresStringComparison() || filter.Match(RuntimeTypeHandle.GetUtf8Name(item)))
{
                            list.Add(item);
                        }
                    }
                }
                return list.ToArray();
            }
References System.RuntimeType.RuntimeType(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.AddSpecialInterface(), System.RuntimeType.GetElementType(), System.RuntimeTypeHandle.GetInterfaces(), System.RuntimeTypeHandle.GetUtf8Name(), System.RuntimeTypeHandle.IsGenericVariable(), System.RuntimeType.IsSZArray, System.item, System.list, System.RuntimeType.MakeGenericType(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.ReflectedType.
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.GetListByName().