Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.PopulateProperties
PopulateProperties() [1/2]
RuntimePropertyInfo[] System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateProperties (Filter filter) inline private
Definition at line 988 of file RuntimeType.cs.
            {
                RuntimeType runtimeType = ReflectedType;
                ListBuilder<RuntimePropertyInfo> list = default(ListBuilder<RuntimePropertyInfo>);
                if (!RuntimeTypeHandle.IsInterface(runtimeType))
                {
                    while (RuntimeTypeHandle.IsGenericVariable(runtimeType))
                    {
                        runtimeType = runtimeType.GetBaseType();
                    }
                    Dictionary<string, List<RuntimePropertyInfo>> csPropertyInfos = (filter.CaseSensitive() ? null : new Dictionary<string, List<RuntimePropertyInfo>>());
                    bool[] usedSlots = new bool[RuntimeTypeHandle.GetNumVirtuals(runtimeType)];
                    do
                    {
                        PopulateProperties(filter, runtimeType, csPropertyInfos, usedSlots, ref list);
                        runtimeType = RuntimeTypeHandle.GetBaseType(runtimeType);
                    }
                    while (runtimeType != null);
                }
                else
                {
                    PopulateProperties(filter, runtimeType, null, null, ref list);
                }
                return list.ToArray();
            }
References System.RuntimeTypeHandle.GetBaseType(), System.RuntimeTypeHandle.GetNumVirtuals(), System.RuntimeTypeHandle.IsGenericVariable(), System.RuntimeTypeHandle.IsInterface(), System.list, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateProperties(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.ReflectedType.
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.GetListByName(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateProperties().