Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.PopulateProperties
PopulateProperties() [2/2]
void System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateProperties (Filter filter, RuntimeType declaringType, Dictionary< string, List< RuntimePropertyInfo > > csPropertyInfos, bool[] usedSlots, ref ListBuilder< RuntimePropertyInfo > list) inline private
Definition at line 1014 of file RuntimeType.cs.
            {
                int token = RuntimeTypeHandle.GetToken(declaringType);
                if (System.Reflection.MetadataToken.IsNullToken(token))
                {
                    return;
                }
                RuntimeTypeHandle.GetMetadataImport(declaringType).EnumProperties(token, out var result);
                RuntimeModule module = RuntimeTypeHandle.GetModule(declaringType);
                int numVirtuals = RuntimeTypeHandle.GetNumVirtuals(declaringType);
                for (int i = 0; i < result.Length; i++)
                {
                    int num = result[i];
                    if (filter.RequiresStringComparison())
                    {
                        if (!ModuleHandle.ContainsPropertyMatchingHash(module, num, filter.GetHashToMatch()))
{
                            continue;
                        }
                        MdUtf8String name = declaringType.GetRuntimeModule().MetadataImport.GetName(num);
                        if (!filter.Match(name))
{
                            continue;
                        }
                    }
                    bool isPrivate;
                    RuntimePropertyInfo runtimePropertyInfo = new RuntimePropertyInfo(num, declaringType, m_runtimeTypeCache, out isPrivate);
                    if (usedSlots != null)
                    {
                        if (declaringType != ReflectedType && isPrivate)
{
                            continue;
                        }
                        MethodInfo methodInfo = runtimePropertyInfo.GetGetMethod() ?? runtimePropertyInfo.GetSetMethod();
                        if (methodInfo != null)
{
                            int slot = RuntimeMethodHandle.GetSlot((RuntimeMethodInfo)methodInfo);
                            if (slot < numVirtuals)
{
                                if (usedSlots[slot])
{
                                    continue;
                                }
                                usedSlots[slot] = true;
                            }
                        }
                        if (csPropertyInfos != null)
{
                            string name2 = runtimePropertyInfo.Name;
                            if (!csPropertyInfos.TryGetValue(name2, out var value))
{
                                value = (csPropertyInfos[name2] = new List<RuntimePropertyInfo>(1));
                            }
                            for (int j = 0; j < value.Count; j++)
{
                                if (runtimePropertyInfo.EqualsSig(value[j]))
{
                                    value = null;
                                    break;
                                }
                            }
                            if (value == null)
{
                                continue;
                            }
                            value.Add(runtimePropertyInfo);
                        }
                        else
{
                            bool flag = false;
                            for (int k = 0; k < list.Count; k++)
{
                                if (runtimePropertyInfo.EqualsSig(list[k]))
{
                                    flag = true;
                                    break;
                                }
                            }
                            if (flag)
{
                                continue;
                            }
                        }
                    }
                    list.Add(runtimePropertyInfo);
                }
            }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.ModuleHandle.ContainsPropertyMatchingHash(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.RuntimeTypeHandle.GetMetadataImport(), System.RuntimeTypeHandle.GetModule(), System.RuntimeTypeHandle.GetNumVirtuals(), System.RuntimeMethodHandle.GetSlot(), System.RuntimeTypeHandle.GetToken(), System.Reflection.MetadataToken.IsNullToken(), System.list, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.m_runtimeTypeCache, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.ReflectedType, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.