Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.PopulateMethods
PopulateMethods()
unsafe RuntimeMethodInfo[] System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateMethods (Filter filter) inline private
Definition at line 559 of file RuntimeType.cs.
            {
                ListBuilder<RuntimeMethodInfo> listBuilder = default(ListBuilder<RuntimeMethodInfo>);
                RuntimeType runtimeType = ReflectedType;
                if (RuntimeTypeHandle.IsInterface(runtimeType))
                {
                    RuntimeTypeHandle.IntroducedMethodEnumerator enumerator = RuntimeTypeHandle.GetIntroducedMethods(runtimeType).GetEnumerator();
                    while (enumerator.MoveNext())
                    {
                        RuntimeMethodHandleInternal current = enumerator.Current;
                        if (!filter.RequiresStringComparison() || (RuntimeMethodHandle.MatchesNameHash(current, filter.GetHashToMatch()) && filter.Match(RuntimeMethodHandle.GetUtf8Name(current))))
{
                            MethodAttributes attributes = RuntimeMethodHandle.GetAttributes(current);
                            if ((attributes & MethodAttributes.RTSpecialName) == 0)
{
                                bool isPublic = (attributes & MethodAttributes.MemberAccessMask) == MethodAttributes.Public;
                                bool isStatic = (attributes & MethodAttributes.Static) != 0;
                                BindingFlags bindingFlags = FilterPreCalculate(isPublic, isInherited: false, isStatic);
                                RuntimeMethodHandleInternal stubIfNeeded = RuntimeMethodHandle.GetStubIfNeeded(current, runtimeType, null);
                                RuntimeMethodInfo item = new RuntimeMethodInfo(stubIfNeeded, runtimeType, m_runtimeTypeCache, attributes, bindingFlags, null);
                                listBuilder.Add(item);
                            }
                        }
                    }
                }
                else
                {
                    while (RuntimeTypeHandle.IsGenericVariable(runtimeType))
                    {
                        runtimeType = runtimeType.GetBaseType();
                    }
                    int numVirtuals = RuntimeTypeHandle.GetNumVirtuals(runtimeType);
                    bool* ptr = stackalloc bool[(int)(uint)numVirtuals];
                    new Span<bool>(ptr, numVirtuals).Clear();
                    bool isValueType = runtimeType.IsValueType;
                    do
                    {
                        int numVirtuals2 = RuntimeTypeHandle.GetNumVirtuals(runtimeType);
                        RuntimeTypeHandle.IntroducedMethodEnumerator enumerator2 = RuntimeTypeHandle.GetIntroducedMethods(runtimeType).GetEnumerator();
                        while (enumerator2.MoveNext())
{
                            RuntimeMethodHandleInternal current2 = enumerator2.Current;
                            if (filter.RequiresStringComparison() && (!RuntimeMethodHandle.MatchesNameHash(current2, filter.GetHashToMatch()) || !filter.Match(RuntimeMethodHandle.GetUtf8Name(current2))))
{
                                continue;
                            }
                            MethodAttributes attributes2 = RuntimeMethodHandle.GetAttributes(current2);
                            MethodAttributes methodAttributes = attributes2 & MethodAttributes.MemberAccessMask;
                            if ((attributes2 & MethodAttributes.RTSpecialName) != 0)
{
                                continue;
                            }
                            bool flag = false;
                            int num = 0;
                            if ((attributes2 & MethodAttributes.Virtual) != 0)
{
                                num = RuntimeMethodHandle.GetSlot(current2);
                                flag = num < numVirtuals2;
                            }
                            bool flag2 = runtimeType != ReflectedType;
                            bool flag3 = methodAttributes == MethodAttributes.Private;
                            if (flag2 && flag3 && !flag)
{
                                continue;
                            }
                            if (flag)
{
                                if (ptr[num])
{
                                    continue;
                                }
                                ptr[num] = true;
                            }
                            else if (isValueType && (attributes2 & (MethodAttributes.Virtual | MethodAttributes.Abstract)) != 0)
{
                                continue;
                            }
                            bool isPublic2 = methodAttributes == MethodAttributes.Public;
                            bool isStatic2 = (attributes2 & MethodAttributes.Static) != 0;
                            BindingFlags bindingFlags2 = FilterPreCalculate(isPublic2, flag2, isStatic2);
                            RuntimeMethodHandleInternal stubIfNeeded2 = RuntimeMethodHandle.GetStubIfNeeded(current2, runtimeType, null);
                            RuntimeMethodInfo item2 = new RuntimeMethodInfo(stubIfNeeded2, runtimeType, m_runtimeTypeCache, attributes2, bindingFlags2, null);
                            listBuilder.Add(item2);
                        }
                        runtimeType = RuntimeTypeHandle.GetBaseType(runtimeType);
                    }
                    while (runtimeType != null);
                }
                return listBuilder.ToArray();
            }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.RuntimeType.FilterPreCalculate(), System.RuntimeMethodHandle.GetAttributes(), System.RuntimeTypeHandle.GetBaseType(), System.RuntimeTypeHandle.GetIntroducedMethods(), System.RuntimeTypeHandle.GetNumVirtuals(), System.RuntimeMethodHandle.GetSlot(), System.RuntimeMethodHandle.GetStubIfNeeded(), System.RuntimeMethodHandle.GetUtf8Name(), System.RuntimeTypeHandle.IsGenericVariable(), System.RuntimeTypeHandle.IsInterface(), System.item, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.m_runtimeTypeCache, System.RuntimeMethodHandle.MatchesNameHash(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.ReflectedType.
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.GetListByName().