Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.PopulateRtFields
PopulateRtFields() [2/2]
unsafe void System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateRtFields (Filter filter, RuntimeType declaringType, ref ListBuilder< RuntimeFieldInfo > list) inline private
Definition at line 718 of file RuntimeType.cs.
            {
                IntPtr* ptr = stackalloc IntPtr[64];
                int num = 64;
                if (!RuntimeTypeHandle.GetFields(declaringType, ptr, &num))
                {
                    fixed (IntPtr* ptr2 = new IntPtr[num])
                    {
                        RuntimeTypeHandle.GetFields(declaringType, ptr2, &num);
                        PopulateRtFields(filter, ptr2, num, declaringType, ref list);
                    }
                }
                else if (num > 0)
                {
                    PopulateRtFields(filter, ptr, num, declaringType, ref list);
                }
            }
References System.RuntimeTypeHandle.GetFields(), System.list, and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateRtFields().
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateFields(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateRtFields().