Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.AddMethod
AddMethod()
MethodBase System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.AddMethod (RuntimeType declaringType, RuntimeMethodHandleInternal method, CacheType cacheType) inline package
Definition at line 281 of file RuntimeType.cs.
            {
                T[] allMembers = m_allMembers;
                if (allMembers != null)
                {
                    switch (cacheType)
                    {
                    case CacheType.Method:
                    {
                        T[] array2 = allMembers;
                        foreach (T val2 in array2)
{
                            if ((object)val2 == null)
{
                                break;
                            }
                            if (val2 is RuntimeMethodInfo { MethodHandle: var methodHandle2 } runtimeMethodInfo && methodHandle2.Value == method.Value)
{
                                return runtimeMethodInfo;
                            }
                        }
                        break;
                    }
                    case CacheType.Constructor:
                    {
                        T[] array = allMembers;
                        foreach (T val in array)
{
                            if ((object)val == null)
{
                                break;
                            }
                            if (val is RuntimeConstructorInfo { MethodHandle: var methodHandle } runtimeConstructorInfo && methodHandle.Value == method.Value)
{
                                return runtimeConstructorInfo;
                            }
                        }
                        break;
                    }
                    }
                }
                T[] list = null;
                MethodAttributes attributes = RuntimeMethodHandle.GetAttributes(method);
                bool isPublic = (attributes & MethodAttributes.MemberAccessMask) == MethodAttributes.Public;
                bool isStatic = (attributes & MethodAttributes.Static) != 0;
                bool isInherited = declaringType != ReflectedType;
                BindingFlags bindingFlags = FilterPreCalculate(isPublic, isInherited, isStatic);
                switch (cacheType)
                {
                case CacheType.Method:
                    list = (T[])(object)new RuntimeMethodInfo[1]
                    {
                        new RuntimeMethodInfo(method, declaringType, m_runtimeTypeCache, attributes, bindingFlags, null)
                    };
                    break;
                case CacheType.Constructor:
                    list = (T[])(object)new RuntimeConstructorInfo[1]
                    {
                        new RuntimeConstructorInfo(method, declaringType, m_runtimeTypeCache, attributes, bindingFlags)
                    };
                    break;
                }
                Insert(ref list, null, MemberListType.HandleToInfo);
                return (MethodBase)(object)list[0];
            }
References System.array, System.RuntimeType.FilterPreCalculate(), System.RuntimeMethodHandle.GetAttributes(), System.Insert, System.list, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.m_allMembers, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.m_runtimeTypeCache, and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.ReflectedType.
Referenced by System.RuntimeType.RuntimeTypeCache.GetConstructor(), and System.RuntimeType.RuntimeTypeCache.GetMethod().