Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.PopulateConstructors
PopulateConstructors()
RuntimeConstructorInfo[] System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateConstructors (Filter filter) inline private
Definition at line 650 of file RuntimeType.cs.
            {
                if (ReflectedType.IsGenericParameter)
                {
                    return Array.Empty<RuntimeConstructorInfo>();
                }
                ListBuilder<RuntimeConstructorInfo> listBuilder = default(ListBuilder<RuntimeConstructorInfo>);
                RuntimeType reflectedType = ReflectedType;
                RuntimeTypeHandle.IntroducedMethodEnumerator enumerator = RuntimeTypeHandle.GetIntroducedMethods(reflectedType).GetEnumerator();
                while (enumerator.MoveNext())
                {
                    RuntimeMethodHandleInternal current = enumerator.Current;
                    if (!filter.RequiresStringComparison() || (RuntimeMethodHandle.MatchesNameHash(current, filter.GetHashToMatch()) && filter.Match(RuntimeMethodHandle.GetUtf8Name(current))))
                    {
                        MethodAttributes attributes = RuntimeMethodHandle.GetAttributes(current);
                        if ((attributes & MethodAttributes.RTSpecialName) != 0)
{
                            bool isPublic = (attributes & MethodAttributes.MemberAccessMask) == MethodAttributes.Public;
                            bool isStatic = (attributes & MethodAttributes.Static) != 0;
                            BindingFlags bindingFlags = FilterPreCalculate(isPublic, isInherited: false, isStatic);
                            RuntimeMethodHandleInternal stubIfNeeded = RuntimeMethodHandle.GetStubIfNeeded(current, reflectedType, null);
                            RuntimeConstructorInfo item = new RuntimeConstructorInfo(stubIfNeeded, ReflectedType, m_runtimeTypeCache, attributes, bindingFlags);
                            listBuilder.Add(item);
                        }
                    }
                }
                return listBuilder.ToArray();
            }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.RuntimeType.FilterPreCalculate(), System.RuntimeMethodHandle.GetAttributes(), System.RuntimeTypeHandle.GetIntroducedMethods(), System.RuntimeMethodHandle.GetStubIfNeeded(), System.RuntimeMethodHandle.GetUtf8Name(), System.RuntimeType.IsGenericParameter, System.item, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.m_runtimeTypeCache, System.RuntimeMethodHandle.MatchesNameHash(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.ReflectedType.
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.GetListByName().