Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.PopulateFields
PopulateFields()
RuntimeFieldInfo[] System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateFields (Filter filter) inline private
Definition at line 680 of file RuntimeType.cs.
            {
                ListBuilder<RuntimeFieldInfo> list = default(ListBuilder<RuntimeFieldInfo>);
                RuntimeType runtimeType = ReflectedType;
                while (RuntimeTypeHandle.IsGenericVariable(runtimeType))
                {
                    runtimeType = runtimeType.GetBaseType();
                }
                while (runtimeType != null)
                {
                    PopulateRtFields(filter, runtimeType, ref list);
                    PopulateLiteralFields(filter, runtimeType, ref list);
                    runtimeType = RuntimeTypeHandle.GetBaseType(runtimeType);
                }
                if (ReflectedType.IsGenericParameter)
                {
                    Type[] interfaces = ReflectedType.BaseType.GetInterfaces();
                    for (int i = 0; i < interfaces.Length; i++)
                    {
                        PopulateLiteralFields(filter, (RuntimeType)interfaces[i], ref list);
                        PopulateRtFields(filter, (RuntimeType)interfaces[i], ref list);
                    }
                }
                else
                {
                    Type[] interfaces2 = RuntimeTypeHandle.GetInterfaces(ReflectedType);
                    if (interfaces2 != null)
                    {
                        for (int j = 0; j < interfaces2.Length; j++)
{
                            PopulateLiteralFields(filter, (RuntimeType)interfaces2[j], ref list);
                            PopulateRtFields(filter, (RuntimeType)interfaces2[j], ref list);
                        }
                    }
                }
                return list.ToArray();
            }
References System.RuntimeType.BaseType, System.RuntimeTypeHandle.GetBaseType(), System.RuntimeTypeHandle.GetInterfaces(), System.RuntimeType.IsGenericParameter, System.RuntimeTypeHandle.IsGenericVariable(), System.list, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateLiteralFields(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateRtFields(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.ReflectedType.
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.GetListByName().