Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.PopulateRtFields
PopulateRtFields() [1/2]
unsafe void System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateRtFields (Filter filter, IntPtr * ppFieldHandles, int count, RuntimeType declaringType, ref ListBuilder< RuntimeFieldInfo > list) inline private
Definition at line 736 of file RuntimeType.cs.
            {
                bool flag = RuntimeTypeHandle.HasInstantiation(declaringType) && !RuntimeTypeHandle.ContainsGenericVariables(declaringType);
                bool flag2 = declaringType != ReflectedType;
                for (int i = 0; i < count; i++)
                {
                    RuntimeFieldHandleInternal runtimeFieldHandleInternal = new RuntimeFieldHandleInternal(ppFieldHandles[i]);
                    if (filter.RequiresStringComparison() && (!RuntimeFieldHandle.MatchesNameHash(runtimeFieldHandleInternal, filter.GetHashToMatch()) || !filter.Match(RuntimeFieldHandle.GetUtf8Name(runtimeFieldHandleInternal))))
                    {
                        continue;
                    }
                    FieldAttributes attributes = RuntimeFieldHandle.GetAttributes(runtimeFieldHandleInternal);
                    FieldAttributes fieldAttributes = attributes & FieldAttributes.FieldAccessMask;
                    if (!flag2 || fieldAttributes != FieldAttributes.Private)
                    {
                        bool isPublic = fieldAttributes == FieldAttributes.Public;
                        bool flag3 = (attributes & FieldAttributes.Static) != 0;
                        BindingFlags bindingFlags = FilterPreCalculate(isPublic, flag2, flag3);
                        if (flag && flag3)
{
                            runtimeFieldHandleInternal = RuntimeFieldHandle.GetStaticFieldForGenericType(runtimeFieldHandleInternal, declaringType);
                        }
                        RuntimeFieldInfo item = new RtFieldInfo(runtimeFieldHandleInternal, declaringType, m_runtimeTypeCache, bindingFlags);
                        list.Add(item);
                    }
                }
            }
References System.RuntimeTypeHandle.ContainsGenericVariables(), System.count, System.RuntimeType.FilterPreCalculate(), System.RuntimeFieldHandle.GetAttributes(), System.RuntimeFieldHandle.GetStaticFieldForGenericType(), System.RuntimeFieldHandle.GetUtf8Name(), System.RuntimeTypeHandle.HasInstantiation(), System.item, System.list, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.m_runtimeTypeCache, System.RuntimeFieldHandle.MatchesNameHash(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.ReflectedType.