Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.GetListByName
GetListByName()
unsafe T[] System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.GetListByName (char * pName, int cNameLen, byte * pUtf8Name, int cUtf8Name, MemberListType listType, CacheType cacheType) inline private
Definition at line 411 of file RuntimeType.cs.
            {
                if (cNameLen != 0)
                {
                    Encoding.UTF8.GetBytes(pName, cNameLen, pUtf8Name, cUtf8Name);
                }
                Filter filter = new Filter(pUtf8Name, cUtf8Name, listType);
                object obj = null;
                switch (cacheType)
                {
                case CacheType.Method:
                    obj = PopulateMethods(filter);
                    break;
                case CacheType.Field:
                    obj = PopulateFields(filter);
                    break;
                case CacheType.Constructor:
                    obj = PopulateConstructors(filter);
                    break;
                case CacheType.Property:
                    obj = PopulateProperties(filter);
                    break;
                case CacheType.Event:
                    obj = PopulateEvents(filter);
                    break;
                case CacheType.NestedType:
                    obj = PopulateNestedClasses(filter);
                    break;
                case CacheType.Interface:
                    obj = PopulateInterfaces(filter);
                    break;
                }
                return (T[])obj;
            }
References System.Reflection.Filter, System.obj, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateConstructors(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateEvents(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateFields(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateInterfaces(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateMethods(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateNestedClasses(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateProperties(), and System.Text.Encoding.UTF8.
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.Populate().