Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.PopulateLiteralFields
PopulateLiteralFields()
void System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateLiteralFields (Filter filter, RuntimeType declaringType, ref ListBuilder< RuntimeFieldInfo > list) inline private
Definition at line 764 of file RuntimeType.cs.
            {
                int token = RuntimeTypeHandle.GetToken(declaringType);
                if (System.Reflection.MetadataToken.IsNullToken(token))
                {
                    return;
                }
                MetadataImport metadataImport = RuntimeTypeHandle.GetMetadataImport(declaringType);
                metadataImport.EnumFields(token, out var result);
                for (int i = 0; i < result.Length; i++)
                {
                    int num = result[i];
                    metadataImport.GetFieldDefProps(num, out var fieldAttributes);
                    FieldAttributes fieldAttributes2 = fieldAttributes & FieldAttributes.FieldAccessMask;
                    if ((fieldAttributes & FieldAttributes.Literal) == 0)
                    {
                        continue;
                    }
                    bool flag = declaringType != ReflectedType;
                    if (flag && fieldAttributes2 == FieldAttributes.Private)
                    {
                        continue;
                    }
                    if (filter.RequiresStringComparison())
                    {
                        MdUtf8String name = metadataImport.GetName(num);
                        if (!filter.Match(name))
{
                            continue;
                        }
                    }
                    bool isPublic = fieldAttributes2 == FieldAttributes.Public;
                    bool isStatic = (fieldAttributes & FieldAttributes.Static) != 0;
                    BindingFlags bindingFlags = FilterPreCalculate(isPublic, flag, isStatic);
                    RuntimeFieldInfo item = new MdFieldInfo(num, fieldAttributes, declaringType.GetTypeHandleInternal(), m_runtimeTypeCache, bindingFlags);
                    list.Add(item);
                }
            }
References System.RuntimeType.FilterPreCalculate(), System.RuntimeTypeHandle.GetMetadataImport(), System.RuntimeTypeHandle.GetToken(), System.Reflection.MetadataToken.IsNullToken(), System.item, System.list, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.m_runtimeTypeCache, and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.ReflectedType.
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateFields().