Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.AddField
AddField()
FieldInfo System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.AddField (RuntimeFieldHandleInternal field) inline package
Definition at line 347 of file RuntimeType.cs.
            {
                T[] allMembers = m_allMembers;
                if (allMembers != null)
                {
                    T[] array = allMembers;
                    foreach (T val in array)
                    {
                        if ((object)val == null)
{
                            break;
                        }
                        if (val is RtFieldInfo rtFieldInfo && rtFieldInfo.GetFieldHandle() == field.Value)
{
                            return rtFieldInfo;
                        }
                    }
                }
                FieldAttributes attributes = RuntimeFieldHandle.GetAttributes(field);
                bool isPublic = (attributes & FieldAttributes.FieldAccessMask) == FieldAttributes.Public;
                bool isStatic = (attributes & FieldAttributes.Static) != 0;
                RuntimeType approxDeclaringType = RuntimeFieldHandle.GetApproxDeclaringType(field);
                bool isInherited = (RuntimeFieldHandle.AcquiresContextFromThis(field) ? (!RuntimeTypeHandle.CompareCanonicalHandles(approxDeclaringType, ReflectedType)) : (approxDeclaringType != ReflectedType));
                BindingFlags bindingFlags = FilterPreCalculate(isPublic, isInherited, isStatic);
                T[] list = (T[])(object)new RuntimeFieldInfo[1]
                {
                    new RtFieldInfo(field, ReflectedType, m_runtimeTypeCache, bindingFlags)
                };
                Insert(ref list, null, MemberListType.HandleToInfo);
                return (FieldInfo)(object)list[0];
            }
References System.RuntimeFieldHandle.AcquiresContextFromThis(), System.array, System.RuntimeTypeHandle.CompareCanonicalHandles(), System.RuntimeType.FilterPreCalculate(), System.RuntimeFieldHandle.GetApproxDeclaringType(), System.RuntimeFieldHandle.GetAttributes(), System.Insert, System.list, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.m_allMembers, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.m_runtimeTypeCache, and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.ReflectedType.
Referenced by System.RuntimeType.RuntimeTypeCache.GetField().