Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.MergeWithGlobalList
MergeWithGlobalList()
void System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.MergeWithGlobalList (T[] list) inline private
Definition at line 510 of file RuntimeType.cs.
            {
                T[] array = m_allMembers;
                if (array == null)
                {
                    m_allMembers = list;
                    return;
                }
                int num = array.Length;
                int num2 = 0;
                for (int i = 0; i < list.Length; i++)
                {
                    T val = list[i];
                    bool flag = false;
                    int j;
                    for (j = 0; j < num; j++)
                    {
                        T val2 = array[j];
                        if (val2 == null)
{
                            break;
                        }
                        if (val.CacheEquals(val2))
{
                            list[i] = val2;
                            flag = true;
                            break;
                        }
                    }
                    if (!flag)
                    {
                        if (num2 == 0)
{
                            num2 = j;
                        }
                        if (num2 >= array.Length)
{
                            int newSize = ((!m_cacheComplete) ? Math.Max(Math.Max(4, 2 * array.Length), list.Length) : (array.Length + 1));
                            T[] array2 = array;
                            Array.Resize(ref array2, newSize);
                            array = array2;
                        }
                        Volatile.Write(ref array[num2], val);
                        num2++;
                    }
                }
                m_allMembers = array;
            }
References System.array, System.list, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.m_allMembers, System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.m_cacheComplete, System.Math.Max(), System.newSize, and System.Threading.Volatile.Write().
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.Insert().