Terraria: System.RuntimeType.RuntimeTypeCache.MemberInfoCache.PopulateNestedClasses
PopulateNestedClasses()
RuntimeType[] System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateNestedClasses (Filter filter) inline private
Definition at line 887 of file RuntimeType.cs.
            {
                RuntimeType runtimeType = ReflectedType;
                while (RuntimeTypeHandle.IsGenericVariable(runtimeType))
                {
                    runtimeType = runtimeType.GetBaseType();
                }
                int token = RuntimeTypeHandle.GetToken(runtimeType);
                if (System.Reflection.MetadataToken.IsNullToken(token))
                {
                    return Array.Empty<RuntimeType>();
                }
                ListBuilder<RuntimeType> listBuilder = default(ListBuilder<RuntimeType>);
                ModuleHandle moduleHandle = new ModuleHandle(RuntimeTypeHandle.GetModule(runtimeType));
                ModuleHandle.GetMetadataImport(moduleHandle.GetRuntimeModule()).EnumNestedTypes(token, out var result);
                for (int i = 0; i < result.Length; i++)
                {
                    RuntimeType runtimeType2;
                    try
                    {
                        runtimeType2 = moduleHandle.ResolveTypeHandle(result[i]).GetRuntimeType();
                    }
                    catch (TypeLoadException)
                    {
                        continue;
                    }
                    if (!filter.RequiresStringComparison() || filter.Match(RuntimeTypeHandle.GetUtf8Name(runtimeType2)))
                    {
                        listBuilder.Add(runtimeType2);
                    }
                }
                return listBuilder.ToArray();
            }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.ModuleHandle.GetMetadataImport(), System.RuntimeTypeHandle.GetModule(), System.RuntimeTypeHandle.GetToken(), System.RuntimeTypeHandle.GetUtf8Name(), System.RuntimeTypeHandle.IsGenericVariable(), System.Reflection.MetadataToken.IsNullToken(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.ReflectedType.
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.GetListByName().