Terraria: Terraria.GameContent.Animations.Segments.SpriteSegment.Draw
Draw()
override void Terraria.GameContent.Animations.Segments.SpriteSegment.Draw (ref GameAnimationSegment info) inline
Definition at line 397 of file Segments.cs.
        {
            if (!((float)info.TimeInAnimation > (float)_targetTime + base.DedicatedTimeNeeded) && info.TimeInAnimation >= _targetTime)
            {
                ResetSpriteAnimation(ref info);
                float localTimeForObject = info.TimeInAnimation - _targetTime;
                ProcessActions(_sprite, localTimeForObject);
                DrawData drawData = _sprite.CurrentDrawData;
                drawData.position += info.AnchorPositionOnScreen + _anchorOffset;
                drawData.color *= _sprite.CurrentOpacity * info.DisplayOpacity;
                if (_shaderEffect != null)
                {
                    _shaderEffect.BeforeDrawing(ref info, ref drawData);
                }
                drawData.Draw(info.SpriteBatch);
                if (_shaderEffect != null)
                {
                    _shaderEffect.AfterDrawing(ref info, ref drawData);
                }
            }
        }
References Terraria.GameContent.Animations.Segments.SpriteSegment._anchorOffset, Terraria.GameContent.Animations.Segments.SpriteSegment._shaderEffect, Terraria.GameContent.Animations.Segments.SpriteSegment._sprite, Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< LooseSprite >._targetTime, Terraria.GameContent.Animations.Segments.SpriteSegment.IShaderEffect.AfterDrawing(), Terraria.GameContent.Animations.Segments.SpriteSegment.IShaderEffect.BeforeDrawing(), Terraria.GameContent.Animations.Segments.LooseSprite.CurrentDrawData, Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< LooseSprite >.ProcessActions(), and Terraria.GameContent.Animations.Segments.SpriteSegment.ResetSpriteAnimation().