Terraria: LootSimulator.TryGettingLootFor
TryGettingLootFor()
bool LootSimulator.TryGettingLootFor (int npcNetId, int timesMultiplier, out string outputText) inline private
     {
         SimulatorInfo simulatorInfo = new SimulatorInfo();
         NPC nPC = new NPC();
         nPC.SetDefaults(npcNetId);
         simulatorInfo.npcVictim = nPC;
         LootSimulationItemCounter lootSimulationItemCounter = (simulatorInfo.itemCounter = new LootSimulationItemCounter());
         foreach (ISimulationConditionSetter neededTestCondition in _neededTestConditions)
         {
             neededTestCondition.Setup(simulatorInfo);
             int num = neededTestCondition.GetTimesToRunMultiplier(simulatorInfo) * timesMultiplier;
             for (int i = 0; i < num; i++)
             {
                 nPC.NPCLoot();
             }
             lootSimulationItemCounter.IncreaseTimesAttempted(num, simulatorInfo.runningExpertMode);
             neededTestCondition.TearDown(simulatorInfo);
             SetCleanSlateWorldConditions();
         }
         lootSimulationItemCounter.Exclude(_excludedItemIds.ToArray());
         string text = lootSimulationItemCounter.PrintCollectedItems(expert: false);
         string text2 = lootSimulationItemCounter.PrintCollectedItems(expert: true);
         string name = NPCID.Search.GetName(npcNetId);
         string text3 = $"FindEntryByNPCID(NPCID.{name})";
         if (text.Length > 0)
         {
             text3 = $"{text3}\n.AddDropsNormalMode({text})";
         }
         if (text2.Length > 0)
         {
             text3 = $"{text3}\n.AddDropsExpertMode({text2})";
         }
         text3 += ";";
         outputText = text3;
         if (text.Length <= 0)
         {
             return text2.Length > 0;
         }
         return true;
     }
References _excludedItemIds, _neededTestConditions, IdDictionary.GetName(), ISimulationConditionSetter.GetTimesToRunMultiplier(), SimulatorInfo.itemCounter, NPC, SimulatorInfo.npcVictim, NPCID.Search, SetCleanSlateWorldConditions(), NPC.SetDefaults(), ISimulationConditionSetter.Setup(), and ISimulationConditionSetter.TearDown().
Referenced by Run().