Terraria: Terraria.GameContent.UI.Elements.UICharacter.Update
Update()
override void Terraria.GameContent.UI.Elements.UICharacter.Update (GameTime gameTime) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 73 of file UICharacter.cs.
    {
        _player.ResetEffects();
        _player.ResetVisibleAccessories();
        _player.UpdateMiscCounter();
        _player.UpdateDyes();
        _player.PlayerFrame();
        if (_animated)
        {
            _animationCounter++;
        }
        base.Update(gameTime);
    }
References Terraria.GameContent.UI.Elements.UICharacter._animated, Terraria.GameContent.UI.Elements.UICharacter._animationCounter, Terraria.GameContent.UI.Elements.UICharacter._player, Terraria.Player.PlayerFrame(), Terraria.Player.ResetEffects(), Terraria.Player.ResetVisibleAccessories(), Terraria.Player.UpdateDyes(), and Terraria.Player.UpdateMiscCounter().