Terraria: Terraria.GameContent.UI.Elements.UICharacter.UICharacter
UICharacter()
Terraria.GameContent.UI.Elements.UICharacter.UICharacter (Player player, bool animated = false, bool hasBackPanel = true, float characterScale = 1f, bool useAClone = false) inline
Definition at line 31 of file UICharacter.cs.
    {
        _player = player;
        if (useAClone)
        {
            _player = player.SerializedClone();
            _player.dead = false;
            _player.PlayerFrame();
        }
        Width.Set(59f, 0f);
        Height.Set(58f, 0f);
        _texture = Main.Assets.Request<Texture2D>("Images/UI/PlayerBackground", (AssetRequestMode)1);
        UseImmediateMode = true;
        _animated = animated;
        _drawsBackPanel = hasBackPanel;
        _characterScale = characterScale;
        OverrideSamplerState = SamplerState.PointClamp;
        _petProjectiles = NoPets;
        PreparePetProjectiles();
    }
References Terraria.GameContent.UI.Elements.UICharacter._animated, Terraria.GameContent.UI.Elements.UICharacter._characterScale, Terraria.GameContent.UI.Elements.UICharacter._drawsBackPanel, Terraria.GameContent.UI.Elements.UICharacter._petProjectiles, Terraria.GameContent.UI.Elements.UICharacter._player, Terraria.GameContent.UI.Elements.UICharacter._texture, Terraria.Main.Assets, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.Elements.UICharacter.NoPets, Terraria.UI.UIElement.OverrideSamplerState, Terraria.Player.PlayerFrame(), Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Terraria.GameContent.UI.Elements.UICharacter.PreparePetProjectiles(), Terraria.Player.SerializedClone(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.UseImmediateMode, and Terraria.UI.UIElement.Width.