Terraria: ReLogic.Graphics.DynamicSpriteFont.InternalDraw
InternalDraw()
void ReLogic.Graphics.DynamicSpriteFont.InternalDraw (string text, SpriteBatch spriteBatch, Vector2 startPosition, Color color, float rotation, Vector2 origin, ref Vector2 scale, SpriteEffects spriteEffects, float depth) inline package
Definition at line 111 of file DynamicSpriteFont.cs.
    {
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_024f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0255: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_027d: Unknown result type (might be due to invalid IL or missing references)
        //IL_028f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0296: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
        Matrix matrix = Matrix.CreateTranslation((0f - origin.X) * scale.X, (0f - origin.Y) * scale.Y, 0f) * Matrix.CreateRotationZ(rotation);
        Vector2 zero = Vector2.Zero;
        Vector2 one = Vector2.One;
        bool flag = true;
        float x = 0f;
        if ((int)spriteEffects != 0)
        {
            Vector2 vector = MeasureString(text);
            if (((Enum)spriteEffects).HasFlag((Enum)(object)(SpriteEffects)1))
            {
                x = vector.X * scale.X;
                one.X = -1f;
            }
            if (((Enum)spriteEffects).HasFlag((Enum)(object)(SpriteEffects)2))
            {
                zero.Y = (vector.Y - (float)LineSpacing) * scale.Y;
                one.Y = -1f;
            }
        }
        zero.X = x;
        foreach (char c in text)
        {
            switch (c)
            {
            case '\n':
                zero.X = x;
                zero.Y += (float)LineSpacing * scale.Y * one.Y;
                flag = true;
                continue;
            case '\r':
                continue;
            }
            SpriteCharacterData characterData = GetCharacterData(c);
            Vector3 kerning = characterData.Kerning;
            Rectangle padding = characterData.Padding;
            if (((Enum)spriteEffects).HasFlag((Enum)(object)(SpriteEffects)1))
            {
                padding.X -= padding.Width;
            }
            if (((Enum)spriteEffects).HasFlag((Enum)(object)(SpriteEffects)2))
            {
                padding.Y = LineSpacing - characterData.Glyph.Height - padding.Y;
            }
            if (flag)
            {
                kerning.X = Math.Max(kerning.X, 0f);
            }
            else
            {
                zero.X += CharacterSpacing * scale.X * one.X;
            }
            zero.X += kerning.X * scale.X * one.X;
            Vector2 position = zero;
            position.X += (float)padding.X * scale.X;
            position.Y += (float)padding.Y * scale.Y;
            Vector2.Transform(ref position, ref matrix, ref position);
            position += startPosition;
            spriteBatch.Draw(characterData.Texture, position, (Rectangle?)characterData.Glyph, color, rotation, Vector2.Zero, scale, spriteEffects, depth);
            zero.X += (kerning.Y + kerning.Z) * scale.X * one.X;
            flag = false;
        }
    }
References ReLogic.Graphics.DynamicSpriteFont.CharacterSpacing, Microsoft.Xna.Framework.Matrix.CreateRotationZ(), Microsoft.Xna.Framework.Matrix.CreateTranslation(), ReLogic.Graphics.DynamicSpriteFont.GetCharacterData(), ReLogic.Graphics.DynamicSpriteFont.LineSpacing, System.Math.Max(), ReLogic.Graphics.DynamicSpriteFont.MeasureString(), Microsoft.Xna.Framework.Vector2.One, System.text, Microsoft.Xna.Framework.Vector2.Transform(), Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Rectangle.Y, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector3.Z, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), and ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString().