Terraria: Terraria.GameContent.Biomes.Desert.SandMound.PlaceSandColumn
PlaceSandColumn()
static void Terraria.GameContent.Biomes.Desert.SandMound.PlaceSandColumn (int startX, int startY, int height) inline static private
    {
        for (int num = startY + height - 1; num >= startY; num--)
        {
            int num2 = num;
            Tile tile = Main.tile[startX, num2];
            if (!WorldGen.remixWorldGen)
            {
                tile.liquid = 0;
            }
            _ = Main.tile[startX, num2 + 1];
            _ = Main.tile[startX, num2 + 2];
            tile.type = 53;
            tile.slope(0);
            tile.halfBrick(halfBrick: false);
            tile.active(active: true);
            if (num < startY)
            {
                tile.active(active: false);
            }
            WorldGen.SquareWallFrame(startX, num2);
        }
    }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.WorldGen.remixWorldGen, Terraria.Tile.slope(), Terraria.WorldGen.SquareWallFrame(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.Biomes.Desert.SandMound.Place().