Terraria: ReLogic.Graphics.DynamicSpriteFont.MeasureString
MeasureString()
Vector2 ReLogic.Graphics.DynamicSpriteFont.MeasureString (string text) inline
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        if (text.Length == 0)
        {
            return Vector2.Zero;
        }
        Vector2 zero = Vector2.Zero;
        zero.Y = LineSpacing;
        float val = 0f;
        int num = 0;
        float num2 = 0f;
        bool flag = true;
        foreach (char c in text)
        {
            switch (c)
            {
            case '\n':
                val = Math.Max(zero.X + Math.Max(num2, 0f), val);
                num2 = 0f;
                zero = Vector2.Zero;
                zero.Y = LineSpacing;
                flag = true;
                num++;
                continue;
            case '\r':
                continue;
            }
            SpriteCharacterData characterData = GetCharacterData(c);
            Vector3 kerning = characterData.Kerning;
            if (flag)
            {
                kerning.X = Math.Max(kerning.X, 0f);
            }
            else
            {
                zero.X += CharacterSpacing + num2;
            }
            zero.X += kerning.X + kerning.Y;
            num2 = kerning.Z;
            zero.Y = Math.Max(zero.Y, characterData.Padding.Height);
            flag = false;
        }
        zero.X += Math.Max(num2, 0f);
        zero.Y += num * LineSpacing;
        zero.X = Math.Max(zero.X, val);
        return zero;
    }
References ReLogic.Graphics.DynamicSpriteFont.CharacterSpacing, ReLogic.Graphics.DynamicSpriteFont.GetCharacterData(), ReLogic.Graphics.DynamicSpriteFont.SpriteCharacterData.Kerning, ReLogic.Graphics.DynamicSpriteFont.LineSpacing, and ReLogic.Graphics.DynamicSpriteFont.SpriteCharacterData.Padding.
Referenced by ReLogic.Graphics.DynamicSpriteFont.CreateCroppedText(), Terraria.GameContent.UI.GameTipsDisplay.Draw(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.Draw(), Terraria.Utils.DrawBorderString(), Terraria.Utils.DrawBorderStringBig(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawHealthText(), Terraria.Main.DrawInterface_14_EntityHealthBars(), Terraria.GameContent.UI.Elements.UIText.DrawSelf(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.GetDistance(), Terraria.UI.Chat.TextSnippet.GetStringLength(), Terraria.UI.Chat.ChatManager.GetStringSize(), ReLogic.Graphics.DynamicSpriteFont.InternalDraw(), and Terraria.GameContent.UI.Elements.UIText.InternalSetText().