Terraria: System.Net.AsyncRequestContext.Allocate
Allocate()
unsafe global.Interop.HttpApi.HTTP_REQUEST * System.Net.AsyncRequestContext.Allocate (ThreadPoolBoundHandle boundHandle, uint size) inline private
Definition at line 21 of file AsyncRequestContext.cs.
    {
        uint num = ((size != 0) ? size : ((base.RequestBuffer == IntPtr.Zero) ? 4096u : base.Size));
        if (_nativeOverlapped != null)
        {
            NativeOverlapped* nativeOverlapped = _nativeOverlapped;
            _nativeOverlapped = null;
            _boundHandle.FreeNativeOverlapped(nativeOverlapped);
        }
        SetBuffer(checked((int)num));
        _boundHandle = boundHandle;
        _nativeOverlapped = boundHandle.AllocateNativeOverlapped(ListenerAsyncResult.IOCallback, _result, base.RequestBuffer);
        return (global::Interop.HttpApi.HTTP_REQUEST*)base.RequestBuffer.ToPointer();
    }
References System.Net.AsyncRequestContext._boundHandle, System.Net.AsyncRequestContext._nativeOverlapped, System.Net.AsyncRequestContext._result, System.Threading.ThreadPoolBoundHandle.AllocateNativeOverlapped(), System.Threading.ThreadPoolBoundHandle.FreeNativeOverlapped(), System.Net.ListenerAsyncResult.IOCallback, System.Net.RequestContextBase.SetBuffer(), and System.IntPtr.Zero.
Referenced by System.Net.AsyncRequestContext.AsyncRequestContext(), and System.Net.AsyncRequestContext.Reset().