Terraria: System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Impl.AddNonscalar
AddNonscalar()
void System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Impl.AddNonscalar () inline
Definition at line 37 of file TraceLoggingMetadataCollector.cs.
        {
            checked
            {
                if (bufferNesting == 0)
                {
                    scalar = false;
                    pinCount++;
                    dataCount++;
                }
            }
        }
References System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Impl.bufferNesting, System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Impl.dataCount, System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Impl.pinCount, and System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Impl.scalar.
Referenced by System.Diagnostics.Tracing.TraceLoggingMetadataCollector.AddArray(), System.Diagnostics.Tracing.TraceLoggingMetadataCollector.AddNullTerminatedString(), and System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Impl.BeginBuffered().