Terraria: CorsairDeviceGroup.AddDeviceIfSupported
AddDeviceIfSupported()
void CorsairDeviceGroup.AddDeviceIfSupported (int deviceIndex, CorsairDeviceInfo deviceInfo) inline private
     {
         if (deviceInfo.CapsMask.HasFlag(CorsairDeviceCaps.CDC_Lighting))
         {
             RgbDevice rgbDevice = null;
             switch (deviceInfo.Type)
             {
             case CorsairDeviceType.CDT_Headset:
                 rgbDevice = CorsairHeadset.Create(deviceIndex, _colorProfiles.Headset);
                 break;
             case CorsairDeviceType.CDT_Mouse:
                 rgbDevice = CorsairMouse.Create(deviceIndex, deviceInfo, _colorProfiles.Mouse);
                 break;
             case CorsairDeviceType.CDT_Keyboard:
                 rgbDevice = CorsairKeyboard.Create(deviceIndex, _colorProfiles.Keyboard);
                 break;
             case CorsairDeviceType.CDT_MouseMat:
                 rgbDevice = CorsairMousepad.Create(deviceIndex, _colorProfiles.Mousepad);
                 break;
             }
             if (rgbDevice != null && rgbDevice.LedCount > 0)
             {
                 _devices.Add(rgbDevice);
                 _state = State.AnyDevicesAdded;
             }
         }
     }
References _colorProfiles, _devices, _state, CorsairDeviceInfo.CapsMask, CorsairMouse.Create(), CorsairHeadset.Create(), CorsairKeyboard.Create(), CorsairMousepad.Create(), VendorColorProfile.Headset, VendorColorProfile.Keyboard, RgbDevice.LedCount, VendorColorProfile.Mouse, VendorColorProfile.Mousepad, and CorsairDeviceInfo.Type.
Referenced by Initialize().