Terraria: System.Net.CertificateValidation.BuildChainAndVerifyProperties
BuildChainAndVerifyProperties() [2/2]
static unsafe SslPolicyErrors System.Net.CertificateValidation.BuildChainAndVerifyProperties (X509Chain chain, X509Certificate2 remoteCertificate, bool checkCertName, bool isServer, string hostName) inline static package
Definition at line 11 of file CertificateValidation.cs.
    {
        SslPolicyErrors sslPolicyErrors = SslPolicyErrors.None;
        bool flag = chain.Build(remoteCertificate);
        if (!flag && chain.SafeHandle.DangerousGetHandle() == IntPtr.Zero)
        {
            throw new CryptographicException(Marshal.GetLastPInvokeError());
        }
        if (checkCertName)
        {
            uint num = 0u;
            global::Interop.Crypt32.SSL_EXTRA_CERT_CHAIN_POLICY_PARA sSL_EXTRA_CERT_CHAIN_POLICY_PARA = default(global::Interop.Crypt32.SSL_EXTRA_CERT_CHAIN_POLICY_PARA);
            sSL_EXTRA_CERT_CHAIN_POLICY_PARA.cbSize = (uint)sizeof(global::Interop.Crypt32.SSL_EXTRA_CERT_CHAIN_POLICY_PARA);
            sSL_EXTRA_CERT_CHAIN_POLICY_PARA.dwAuthType = (isServer ? 1u : 2u);
            sSL_EXTRA_CERT_CHAIN_POLICY_PARA.fdwChecks = 0u;
            sSL_EXTRA_CERT_CHAIN_POLICY_PARA.pwszServerName = null;
            global::Interop.Crypt32.SSL_EXTRA_CERT_CHAIN_POLICY_PARA sSL_EXTRA_CERT_CHAIN_POLICY_PARA2 = sSL_EXTRA_CERT_CHAIN_POLICY_PARA;
            global::Interop.Crypt32.CERT_CHAIN_POLICY_PARA cERT_CHAIN_POLICY_PARA = default(global::Interop.Crypt32.CERT_CHAIN_POLICY_PARA);
            cERT_CHAIN_POLICY_PARA.cbSize = (uint)sizeof(global::Interop.Crypt32.CERT_CHAIN_POLICY_PARA);
            cERT_CHAIN_POLICY_PARA.dwFlags = 0u;
            cERT_CHAIN_POLICY_PARA.pvExtraPolicyPara = &sSL_EXTRA_CERT_CHAIN_POLICY_PARA2;
            global::Interop.Crypt32.CERT_CHAIN_POLICY_PARA cpp = cERT_CHAIN_POLICY_PARA;
            fixed (char* pwszServerName = hostName)
            {
                sSL_EXTRA_CERT_CHAIN_POLICY_PARA2.pwszServerName = pwszServerName;
                cpp.dwFlags |= 4031u;
                SafeX509ChainHandle safeHandle = chain.SafeHandle;
                num = Verify(safeHandle, ref cpp);
                if (num == 2148204815u)
                {
                    sslPolicyErrors |= SslPolicyErrors.RemoteCertificateNameMismatch;
                }
            }
        }
        if (!flag)
        {
            sslPolicyErrors |= SslPolicyErrors.RemoteCertificateChainErrors;
        }
        return sslPolicyErrors;
    }
References System.Security.Cryptography.X509Certificates.X509Chain.Build(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.Security.Cryptography.X509Certificates.X509Chain.SafeHandle, System.Net.CertificateValidation.Verify(), and System.IntPtr.Zero.