Terraria: System.Net.Http.Headers.HttpHeaders.ContainsNewLine
ContainsNewLine()
static bool System.Net.Http.Headers.HttpHeaders.ContainsNewLine (string value, string name) inline static private inherited
Definition at line 900 of file HttpHeaders.cs.
    {
        if (HttpRuleParser.ContainsNewLine(value))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(null, System.SR.Format(System.SR.net_http_log_headers_no_newlines, name, value), "ContainsNewLine");
            }
            return true;
        }
        return false;
    }
References System.Net.Http.HttpRuleParser.ContainsNewLine(), System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.NetEventSource.Log, System.SR.net_http_log_headers_no_newlines, and System.value.
Referenced by System.Net.Http.Headers.HttpHeaders.ParseMultipleRawHeaderValues(), System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(), and System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue().