Terraria: System.Net.Http.Headers.HttpHeaders.ParseMultipleRawHeaderValues
ParseMultipleRawHeaderValues()
static void System.Net.Http.Headers.HttpHeaders.ParseMultipleRawHeaderValues (HeaderDescriptor descriptor, HeaderStoreItemInfo info, List< string > rawValues) inline static private inherited
Definition at line 643 of file HttpHeaders.cs.
    {
        if (descriptor.Parser == null)
        {
            foreach (string rawValue in rawValues)
            {
                if (!ContainsNewLine(rawValue, descriptor.Name))
                {
                    AddParsedValue(info, rawValue);
                }
            }
            return;
        }
        foreach (string rawValue2 in rawValues)
        {
            if (!TryParseAndAddRawHeaderValue(descriptor, info, rawValue2, addWhenInvalid: true) && System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Log.HeadersInvalidValue(descriptor.Name, rawValue2);
            }
        }
    }
References System.Net.Http.Headers.HttpHeaders.AddParsedValue(), System.Net.Http.Headers.HttpHeaders.ContainsNewLine(), System.info, System.Net.NetEventSource.Log, System.Net.Http.Headers.HeaderDescriptor.Name, System.Net.Http.Headers.HeaderDescriptor.Parser, and System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue().
Referenced by System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues().