Terraria: System.Net.Http.Headers.HttpHeaders.RemoveParsedValue
RemoveParsedValue()
bool System.Net.Http.Headers.HttpHeaders.RemoveParsedValue (HeaderDescriptor descriptor, object value) inline package inherited
Definition at line 380 of file HttpHeaders.cs.
    {
        if (_headerStore == null)
        {
            return false;
        }
        if (TryGetAndParseHeaderInfo(descriptor, out var info))
        {
            if (info.ParsedValue == null)
            {
                return false;
            }
            bool result = false;
            IEqualityComparer comparer = descriptor.Parser.Comparer;
            if (!(info.ParsedValue is List<object> list))
            {
                if (AreEqual(value, info.ParsedValue, comparer))
                {
                    info.ParsedValue = null;
                    result = true;
                }
            }
            else
            {
                foreach (object item in list)
                {
                    if (AreEqual(value, item, comparer))
                    {
                        result = list.Remove(item);
                        break;
                    }
                }
                if (list.Count == 0)
                {
                    info.ParsedValue = null;
                }
            }
            if (info.IsEmpty)
            {
                bool flag = Remove(descriptor);
            }
            return result;
        }
        return false;
    }
References System.Net.Http.Headers.HttpHeaders._headerStore, System.Net.Http.Headers.HttpHeaders.AreEqual(), System.comparer, System.Net.Http.Headers.HttpHeaderParser.Comparer, System.info, System.item, System.list, System.Net.Http.Headers.HeaderDescriptor.Parser, System.Net.Http.Headers.HttpHeaders.Remove(), System.Net.Http.Headers.HttpHeaders.TryGetAndParseHeaderInfo(), and System.value.
Referenced by System.Net.Http.Headers.HttpHeaderValueCollection< T >.Remove(), and System.Net.Http.Headers.HttpHeaderValueCollection< T >.RemoveSpecialValue().