Terraria: System.Net.Http.Headers.HttpHeaders.GetEnumeratorCore
GetEnumeratorCore()
IEnumerator< KeyValuePair< string, IEnumerable< string > > > System.Net.Http.Headers.HttpHeaders.GetEnumeratorCore () inline private inherited
Definition at line 306 of file HttpHeaders.cs.
    {
        foreach (KeyValuePair<HeaderDescriptor, object> item in _headerStore)
        {
            HeaderDescriptor key = item.Key;
            object value = item.Value;
            HeaderStoreItemInfo headerStoreItemInfo = value as HeaderStoreItemInfo;
            if (headerStoreItemInfo == null)
            {
                Dictionary<HeaderDescriptor, object> headerStore = _headerStore;
                HeaderDescriptor key2 = key;
                HeaderStoreItemInfo obj = new HeaderStoreItemInfo
                {
                    RawValue = value
                };
                headerStoreItemInfo = obj;
                headerStore[key2] = obj;
            }
            if (!ParseRawHeaderValues(key, headerStoreItemInfo, removeEmptyHeader: false))
            {
                _headerStore.Remove(key);
                continue;
            }
            string[] storeValuesAsStringArray = GetStoreValuesAsStringArray(key, headerStoreItemInfo);
            yield return new KeyValuePair<string, IEnumerable<string>>(key.Name, storeValuesAsStringArray);
        }
    }
References System.Net.Http.Headers.HttpHeaders._headerStore, System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringArray(), System.item, System.key, System.obj, System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.value.
Referenced by System.Net.Http.Headers.HttpHeaders.GetEnumerator().