Terraria: System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue
TryParseAndAddRawHeaderValue()
static bool System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue (HeaderDescriptor descriptor, HeaderStoreItemInfo info, string value, bool addWhenInvalid) inline static private inherited
Definition at line 692 of file HttpHeaders.cs.
    {
        if (!info.CanAddParsedValue(descriptor.Parser))
        {
            if (addWhenInvalid)
            {
                AddInvalidValue(info, value ?? string.Empty);
            }
            return false;
        }
        int index = 0;
        if (descriptor.Parser.TryParseValue(value, info.ParsedValue, ref index, out var parsedValue))
        {
            if (value == null || index == value.Length)
            {
                if (parsedValue != null)
                {
                    AddParsedValue(info, parsedValue);
                }
                return true;
            }
            List<object> list = new List<object>();
            if (parsedValue != null)
            {
                list.Add(parsedValue);
            }
            while (index < value.Length)
            {
                if (descriptor.Parser.TryParseValue(value, info.ParsedValue, ref index, out parsedValue))
                {
                    if (parsedValue != null)
                    {
                        list.Add(parsedValue);
                    }
                    continue;
                }
                if (!ContainsNewLine(value, descriptor.Name) && addWhenInvalid)
                {
                    AddInvalidValue(info, value);
                }
                return false;
            }
            foreach (object item in list)
            {
                AddParsedValue(info, item);
            }
            return true;
        }
        if (!ContainsNewLine(value, descriptor.Name) && addWhenInvalid)
        {
            AddInvalidValue(info, value ?? string.Empty);
        }
        return false;
    }
References System.Net.Http.Headers.HttpHeaders.AddInvalidValue(), System.Net.Http.Headers.HttpHeaders.AddParsedValue(), System.Net.Http.Headers.HttpHeaders.ContainsNewLine(), System.index, System.info, System.item, System.list, System.Net.Http.Headers.HeaderDescriptor.Name, System.Net.Http.Headers.HeaderDescriptor.Parser, System.Net.Http.Headers.HttpHeaderParser.TryParseValue(), and System.value.
Referenced by System.Net.Http.Headers.HttpHeaders.ParseMultipleRawHeaderValues(), System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(), and System.Net.Http.Headers.HttpHeaders.TryParseAndAddValue().