Terraria: System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringOrStringArray
GetStoreValuesAsStringOrStringArray()
static void System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringOrStringArray (HeaderDescriptor descriptor, object sourceValues, out string singleValue, out string[] multiValue) inline static package inherited
Definition at line 919 of file HttpHeaders.cs.
    {
        if (!(sourceValues is HeaderStoreItemInfo headerStoreItemInfo))
        {
            singleValue = (string)sourceValues;
            multiValue = null;
            return;
        }
        int valueCount = GetValueCount(headerStoreItemInfo);
        singleValue = null;
        Span<string> values;
        if (valueCount == 1)
        {
            multiValue = null;
            values = MemoryMarshal.CreateSpan(ref singleValue, 1);
        }
        else
        {
            values = (multiValue = ((valueCount != 0) ? new string[valueCount] : Array.Empty<string>()));
        }
        int currentIndex = 0;
        ReadStoreValues<string>(values, headerStoreItemInfo.RawValue, null, ref currentIndex);
        ReadStoreValues<object>(values, headerStoreItemInfo.ParsedValue, descriptor.Parser, ref currentIndex);
        ReadStoreValues<string>(values, headerStoreItemInfo.InvalidValue, null, ref currentIndex);
    }
References System.Net.Http.Headers.HttpHeaders.GetValueCount(), System.Net.Http.Headers.HeaderDescriptor.Parser, and System.values.
Referenced by System.Net.Http.Headers.HttpHeaders.GetHeaderString(), System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringArray(), System.Net.Http.Headers.HttpHeadersNonValidated.Enumerator.MoveNext(), System.Net.Http.Headers.HttpHeaders.ToString(), and System.Net.Http.Headers.HttpHeadersNonValidated.TryGetValues().