Terraria: System.Net.Http.Headers.HttpHeaders.GetOrCreateHeaderInfo
GetOrCreateHeaderInfo()
HeaderStoreItemInfo System.Net.Http.Headers.HttpHeaders.GetOrCreateHeaderInfo (HeaderDescriptor descriptor, bool parseRawValues) inline private inherited
Definition at line 535 of file HttpHeaders.cs.
    {
        HeaderStoreItemInfo info = null;
        bool flag;
        if (parseRawValues)
        {
            flag = TryGetAndParseHeaderInfo(descriptor, out info);
        }
        else
        {
            flag = TryGetHeaderValue(descriptor, out var value);
            if (flag)
            {
                if (value is HeaderStoreItemInfo headerStoreItemInfo)
                {
                    info = headerStoreItemInfo;
                }
                else
                {
                    Dictionary<HeaderDescriptor, object> headerStore = _headerStore;
                    HeaderStoreItemInfo obj = new HeaderStoreItemInfo
                    {
                        RawValue = value
                    };
                    info = obj;
                    headerStore[descriptor] = obj;
                }
            }
        }
        if (!flag)
        {
            info = CreateAndAddHeaderToStore(descriptor);
        }
        return info;
    }
References System.Net.Http.Headers.HttpHeaders._headerStore, System.Net.Http.Headers.HttpHeaders.CreateAndAddHeaderToStore(), System.info, System.obj, System.Net.Http.Headers.HttpHeaders.TryGetAndParseHeaderInfo(), System.Net.Http.Headers.HttpHeaders.TryGetHeaderValue(), and System.value.
Referenced by System.Net.Http.Headers.HttpHeaders.AddParsedValue(), System.Net.Http.Headers.HttpHeaders.SetParsedValue(), and System.Net.Http.Headers.HttpHeaders.TryAddWithoutValidation().