Terraria: System.Net.Http.Headers.HttpHeaders.AddHeaderToStore
AddHeaderToStore()
void System.Net.Http.Headers.HttpHeaders.AddHeaderToStore (HeaderDescriptor descriptor, object value) inline private inherited
Definition at line 578 of file HttpHeaders.cs.
    {
        (_headerStore ?? (_headerStore = new Dictionary<HeaderDescriptor, object>())).Add(descriptor, value);
    }
References System.Net.Http.Headers.HttpHeaders._headerStore, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), and System.value.
Referenced by System.Net.Http.Headers.HttpHeaders.Add(), System.Net.Http.Headers.HttpHeaders.Add(), System.Net.Http.Headers.HttpHeaders.CreateAndAddHeaderToStore(), and System.Net.Http.Headers.HttpHeaders.TryParseAndAddValue().