Terraria: System.Net.Http.Headers.HttpHeaders.CheckContainsNewLine
CheckContainsNewLine()
static void System.Net.Http.Headers.HttpHeaders.CheckContainsNewLine (string value) inline static package inherited
Definition at line 891 of file HttpHeaders.cs.
    {
        if (value == null || !HttpRuleParser.ContainsNewLine(value))
        {
            return;
        }
        throw new FormatException(System.SR.net_http_headers_no_newlines);
    }
References System.Net.Http.HttpRuleParser.ContainsNewLine(), System.SR.net_http_headers_no_newlines, and System.value.
Referenced by System.Net.Http.Headers.AuthenticationHeaderValue.AuthenticationHeaderValue(), and System.Net.Http.Headers.HttpHeaders.ParseAndAddValue().