Terraria: System.Net.Http.Headers.HttpHeaders.PrepareHeaderInfoForAdd
PrepareHeaderInfoForAdd()
void System.Net.Http.Headers.HttpHeaders.PrepareHeaderInfoForAdd (HeaderDescriptor descriptor, out HeaderStoreItemInfo info, out bool addToStore) inline private inherited
Definition at line 793 of file HttpHeaders.cs.
    {
        if (!IsAllowedHeaderName(descriptor))
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_http_headers_not_allowed_header_name, descriptor.Name));
        }
        addToStore = false;
        if (!TryGetAndParseHeaderInfo(descriptor, out info))
        {
            info = new HeaderStoreItemInfo();
            addToStore = true;
        }
    }
References System.SR.Format(), System.info, System.Net.Http.Headers.HttpHeaders.IsAllowedHeaderName(), System.Net.Http.Headers.HeaderDescriptor.Name, System.SR.net_http_headers_not_allowed_header_name, and System.Net.Http.Headers.HttpHeaders.TryGetAndParseHeaderInfo().
Referenced by System.Net.Http.Headers.HttpHeaders.Add(), System.Net.Http.Headers.HttpHeaders.Add(), and System.Net.Http.Headers.HttpHeaders.TryParseAndAddValue().