Terraria: System.Net.Http.Headers.HttpHeaders.Add
Add() [1/4]
void System.Net.Http.Headers.HttpHeaders.Add (HeaderDescriptor descriptor, IEnumerable< string > values) inline package inherited
Definition at line 91 of file HttpHeaders.cs.
    {
        if (values == null)
        {
            throw new ArgumentNullException("values");
        }
        PrepareHeaderInfoForAdd(descriptor, out var info, out var addToStore);
        try
        {
            foreach (string value in values)
            {
                ParseAndAddValue(descriptor, info, value);
            }
        }
        finally
        {
            if (addToStore && info.ParsedValue != null)
            {
                AddHeaderToStore(descriptor, info);
            }
        }
    }
References System.Net.Http.Headers.HttpHeaders.AddHeaderToStore(), System.info, System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(), System.Net.Http.Headers.HttpHeaders.PrepareHeaderInfoForAdd(), System.value, and System.values.