Terraria: System.Net.Http.Headers.HttpHeaders.ContainsParsedValue
ContainsParsedValue()
bool System.Net.Http.Headers.HttpHeaders.ContainsParsedValue (HeaderDescriptor descriptor, object value) inline package inherited
Definition at line 426 of file HttpHeaders.cs.
    {
        if (_headerStore == null)
        {
            return false;
        }
        if (TryGetAndParseHeaderInfo(descriptor, out var info))
        {
            if (info.ParsedValue == null)
            {
                return false;
            }
            List<object> list = info.ParsedValue as List<object>;
            IEqualityComparer comparer = descriptor.Parser.Comparer;
            if (list == null)
            {
                return AreEqual(value, info.ParsedValue, comparer);
            }
            foreach (object item in list)
            {
                if (AreEqual(value, item, comparer))
                {
                    return true;
                }
            }
            return false;
        }
        return false;
    }
References System.Net.Http.Headers.HttpHeaders._headerStore, System.Net.Http.Headers.HttpHeaders.AreEqual(), System.comparer, System.Net.Http.Headers.HttpHeaderParser.Comparer, System.info, System.item, System.list, System.Net.Http.Headers.HeaderDescriptor.Parser, System.Net.Http.Headers.HttpHeaders.TryGetAndParseHeaderInfo(), and System.value.
Referenced by System.Net.Http.Headers.HttpHeaderValueCollection< T >.Contains(), System.Net.Http.Headers.HttpGeneralHeaders.GetConnectionClose(), System.Net.Http.Headers.HttpGeneralHeaders.GetTransferEncodingChunked(), and System.Net.Http.Headers.HttpHeaderValueCollection< T >.SetSpecialValue().