Terraria: System.Net.Http.Headers.HttpHeaders.AddHeaders
AddHeaders()
virtual void System.Net.Http.Headers.HttpHeaders.AddHeaders (HttpHeaders sourceHeaders) inline package virtual inherited
Reimplemented in System.Net.Http.Headers.HttpRequestHeaders, and System.Net.Http.Headers.HttpResponseHeaders.
Definition at line 456 of file HttpHeaders.cs.
    {
        Dictionary<HeaderDescriptor, object> headerStore = sourceHeaders._headerStore;
        if (headerStore == null || headerStore.Count == 0)
        {
            return;
        }
        if (_headerStore == null)
        {
            _headerStore = new Dictionary<HeaderDescriptor, object>();
        }
        foreach (KeyValuePair<HeaderDescriptor, object> item in headerStore)
        {
            if (!_headerStore.ContainsKey(item.Key))
            {
                object value = item.Value;
                if (value is HeaderStoreItemInfo sourceInfo)
                {
                    AddHeaderInfo(item.Key, sourceInfo);
                }
                else
                {
                    _headerStore.Add(item.Key, value);
                }
            }
        }
    }
References System.Net.Http.Headers.HttpHeaders._headerStore, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Http.Headers.HttpHeaders.AddHeaderInfo(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.item, and System.value.