Terraria: System.Net.Http.Headers.HttpHeaders.GetStoreValuesIntoStringArray
GetStoreValuesIntoStringArray()
static int System.Net.Http.Headers.HttpHeaders.GetStoreValuesIntoStringArray (HeaderDescriptor descriptor, object sourceValues, [NotNull] ref string[] values) inline static package inherited
Definition at line 945 of file HttpHeaders.cs.
    {
        if (values == null)
        {
            values = Array.Empty<string>();
        }
        if (!(sourceValues is HeaderStoreItemInfo headerStoreItemInfo))
        {
            if (values.Length == 0)
            {
                values = new string[1];
            }
            values[0] = (string)sourceValues;
            return 1;
        }
        int valueCount = GetValueCount(headerStoreItemInfo);
        if (valueCount > 0)
        {
            if (values.Length < valueCount)
            {
                values = new string[valueCount];
            }
            int currentIndex = 0;
            ReadStoreValues<string>(values, headerStoreItemInfo.RawValue, null, ref currentIndex);
            ReadStoreValues<object>(values, headerStoreItemInfo.ParsedValue, descriptor.Parser, ref currentIndex);
            ReadStoreValues<string>(values, headerStoreItemInfo.InvalidValue, null, ref currentIndex);
        }
        return valueCount;
    }
References System.Net.Http.Headers.HttpHeaders.GetValueCount(), System.Net.Http.Headers.HeaderDescriptor.Parser, and System.values.
Referenced by System.Net.Http.Http3RequestStream.BufferHeaderCollection(), System.Net.Http.Http2Connection.WriteHeaderCollection(), and System.Net.Http.HttpConnection.WriteHeadersAsync().