Terraria: System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor
GetHeaderDescriptor()
HeaderDescriptor System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor (string name) inline private inherited
Definition at line 848 of file HttpHeaders.cs.
    {
        if (string.IsNullOrEmpty(name))
        {
            throw new ArgumentException(System.SR.net_http_argument_empty_string, "name");
        }
        if (!HeaderDescriptor.TryGet(name, out var descriptor))
        {
            throw new FormatException(System.SR.net_http_headers_invalid_header_name);
        }
        if ((descriptor.HeaderType & _allowedHeaderTypes) != 0)
        {
            return descriptor;
        }
        if ((descriptor.HeaderType & _treatAsCustomHeaderTypes) != 0)
        {
            return descriptor.AsCustomHeader();
        }
        throw new InvalidOperationException(System.SR.Format(System.SR.net_http_headers_not_allowed_header_name, name));
    }
References System.Net.Http.Headers.HttpHeaders._allowedHeaderTypes, System.Net.Http.Headers.HttpHeaders._treatAsCustomHeaderTypes, System.SR.Format(), System.SR.net_http_argument_empty_string, System.SR.net_http_headers_invalid_header_name, System.SR.net_http_headers_not_allowed_header_name, and System.Net.Http.Headers.HeaderDescriptor.TryGet().
Referenced by System.Net.Http.Headers.HttpHeaders.Add(), System.Net.Http.Headers.HttpHeaders.Add(), System.Net.Http.Headers.HttpHeaders.Contains(), System.Net.Http.Headers.HttpHeaders.GetValues(), and System.Net.Http.Headers.HttpHeaders.Remove().