Terraria: System.Net.Http.Headers.HttpHeaders.GetEnumerator
GetEnumerator() [1/2]
IEnumerator< KeyValuePair< string, IEnumerable< string > > > System.Net.Http.Headers.HttpHeaders.GetEnumerator () inline inherited
Implements System.Collections.Generic.IEnumerable< out T >.
Definition at line 297 of file HttpHeaders.cs.
    {
        if (_headerStore == null || _headerStore.Count <= 0)
        {
            return ((IEnumerable<KeyValuePair<string, IEnumerable<string>>>)Array.Empty<KeyValuePair<string, IEnumerable<string>>>()).GetEnumerator();
        }
        return GetEnumeratorCore();
    }
References System.Net.Http.Headers.HttpHeaders._headerStore, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), and System.Net.Http.Headers.HttpHeaders.GetEnumeratorCore().
Referenced by System.Net.Http.Headers.HttpHeaders.GetEnumerator().