Terraria: System.Net.Http.Headers.HttpHeaders.ParseAndAddValue
ParseAndAddValue()
void System.Net.Http.Headers.HttpHeaders.ParseAndAddValue (HeaderDescriptor descriptor, HeaderStoreItemInfo info, string value) inline private inherited
Definition at line 807 of file HttpHeaders.cs.
    {
        if (descriptor.Parser == null)
        {
            CheckContainsNewLine(value);
            AddParsedValue(info, value ?? string.Empty);
            return;
        }
        if (!info.CanAddParsedValue(descriptor.Parser))
        {
            throw new FormatException(System.SR.Format(CultureInfo.InvariantCulture, System.SR.net_http_headers_single_value_header, descriptor.Name));
        }
        int index = 0;
        object obj = descriptor.Parser.ParseValue(value, info.ParsedValue, ref index);
        if (value == null || index == value.Length)
        {
            if (obj != null)
            {
                AddParsedValue(info, obj);
            }
            return;
        }
        List<object> list = new List<object>();
        if (obj != null)
        {
            list.Add(obj);
        }
        while (index < value.Length)
        {
            obj = descriptor.Parser.ParseValue(value, info.ParsedValue, ref index);
            if (obj != null)
            {
                list.Add(obj);
            }
        }
        foreach (object item in list)
        {
            AddParsedValue(info, item);
        }
    }
References System.Net.Http.Headers.HttpHeaders.AddParsedValue(), System.Net.Http.Headers.HttpHeaders.CheckContainsNewLine(), System.SR.Format(), System.index, System.info, System.Globalization.CultureInfo.InvariantCulture, System.item, System.list, System.Net.Http.Headers.HeaderDescriptor.Name, System.SR.net_http_headers_single_value_header, System.obj, System.Net.Http.Headers.HeaderDescriptor.Parser, System.Net.Http.Headers.HttpHeaderParser.ParseValue(), and System.value.
Referenced by System.Net.Http.Headers.HttpHeaders.Add(), and System.Net.Http.Headers.HttpHeaders.Add().