Terraria: System.Net.Http.Headers.HttpHeaders.AddHeaderInfo
AddHeaderInfo()
void System.Net.Http.Headers.HttpHeaders.AddHeaderInfo (HeaderDescriptor descriptor, HeaderStoreItemInfo sourceInfo) inline private inherited
Definition at line 484 of file HttpHeaders.cs.
    {
        HeaderStoreItemInfo headerStoreItemInfo = CreateAndAddHeaderToStore(descriptor);
        headerStoreItemInfo.RawValue = CloneStringHeaderInfoValues(sourceInfo.RawValue);
        if (descriptor.Parser == null)
        {
            headerStoreItemInfo.ParsedValue = CloneStringHeaderInfoValues(sourceInfo.ParsedValue);
            return;
        }
        headerStoreItemInfo.InvalidValue = CloneStringHeaderInfoValues(sourceInfo.InvalidValue);
        if (sourceInfo.ParsedValue == null)
        {
            return;
        }
        if (!(sourceInfo.ParsedValue is List<object> list))
        {
            CloneAndAddValue(headerStoreItemInfo, sourceInfo.ParsedValue);
            return;
        }
        foreach (object item in list)
        {
            CloneAndAddValue(headerStoreItemInfo, item);
        }
    }
References System.Net.Http.Headers.HttpHeaders.CloneAndAddValue(), System.Net.Http.Headers.HttpHeaders.CloneStringHeaderInfoValues(), System.Net.Http.Headers.HttpHeaders.CreateAndAddHeaderToStore(), System.item, System.list, and System.Net.Http.Headers.HeaderDescriptor.Parser.
Referenced by System.Net.Http.Headers.HttpHeaders.AddHeaders().