Terraria: Terraria.GameContent.UI.BigProgressBar.BigProgressBarCache.SetLife
SetLife()
void Terraria.GameContent.UI.BigProgressBar.BigProgressBarCache.SetLife (float current, float max) inline
Definition at line 13 of file BigProgressBarCache.cs.
    {
        LifeCurrent = current;
        LifeMax = max;
    }
References Terraria.GameContent.UI.BigProgressBar.BigProgressBarCache.LifeCurrent, and Terraria.GameContent.UI.BigProgressBar.BigProgressBarCache.LifeMax.
Referenced by Terraria.GameContent.UI.BigProgressBar.BrainOfCthuluBigProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.CommonBossBigProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.DeerclopsBigProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.EaterOfWorldsProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.LunarPillarBigProgessBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.MartianSaucerBigProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.MoonLordProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.PirateShipBigProgressBar.ValidateAndCollectNecessaryInfo(), and Terraria.GameContent.UI.BigProgressBar.TwinsBigProgressBar.ValidateAndCollectNecessaryInfo().