Terraria: System.Net.Http.Http3RequestStream.ReadResponseContent
ReadResponseContent()
int System.Net.Http.Http3RequestStream.ReadResponseContent (HttpResponseMessage response, Span< byte > buffer) inline private
Definition at line 967 of file Http3RequestStream.cs.
    {
        try
        {
            int num = 0;
            while (buffer.Length != 0 && (_responseDataPayloadRemaining > 0 || ReadNextDataFrameAsync(response, CancellationToken.None).AsTask().GetAwaiter().GetResult()))
            {
                if (_recvBuffer.ActiveLength != 0)
                {
                    int num2 = (int)Math.Min(buffer.Length, Math.Min(_responseDataPayloadRemaining, _recvBuffer.ActiveLength));
                    Span<byte> span = _recvBuffer.ActiveSpan;
                    span = span.Slice(0, num2);
                    span.CopyTo(buffer);
                    num += num2;
                    _responseDataPayloadRemaining -= num2;
                    _recvBuffer.Discard(num2);
                    buffer = buffer.Slice(num2);
                    if (_responseDataPayloadRemaining == 0L && _recvBuffer.ActiveLength == 0)
                    {
                        break;
                    }
                    continue;
                }
                int length = (int)Math.Min(buffer.Length, _responseDataPayloadRemaining);
                int num3 = _stream.Read(buffer.Slice(0, length));
                if (num3 == 0)
                {
                    throw new HttpRequestException(System.SR.Format(System.SR.net_http_invalid_response_premature_eof_bytecount, _responseDataPayloadRemaining));
                }
                num += num3;
                _responseDataPayloadRemaining -= num3;
                buffer = buffer.Slice(num3);
                break;
            }
            return num;
        }
        catch (Exception ex)
        {
            HandleReadResponseContentException(ex, CancellationToken.None);
            return 0;
        }
    }
References System.Net.Http.Http3RequestStream._recvBuffer, System.Net.Http.Http3RequestStream._responseDataPayloadRemaining, System.Net.Http.Http3RequestStream._stream, System.buffer, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.SR.Format(), System.Net.Http.Http3RequestStream.HandleReadResponseContentException(), System.L, System.length, System.Math.Min(), System.SR.net_http_invalid_response_premature_eof_bytecount, System.Threading.CancellationToken.None, System.Net.Quic.QuicStream.Read(), and System.Net.Http.Http3RequestStream.ReadNextDataFrameAsync().
Referenced by System.Net.Http.Http3RequestStream.Http3ReadStream.Read().