Terraria: System.Net.Http.Http3RequestStream.OnHeader
OnHeader() [2/2]
void IHttpHeadersHandler. System.Net.Http.Http3RequestStream.OnHeader (ReadOnlySpan< byte > name, ReadOnlySpan< byte > value) inline private
Implements System.Net.Http.IHttpHeadersHandler.
Definition at line 801 of file Http3RequestStream.cs.
    {
        if (!HeaderDescriptor.TryGet(name, out var descriptor))
        {
            throw new HttpRequestException(System.SR.Format(System.SR.net_http_invalid_response_header_name, Encoding.ASCII.GetString(name)));
        }
        OnHeader(null, descriptor, null, value);
    }
References System.Text.Encoding.ASCII, System.SR.Format(), System.SR.net_http_invalid_response_header_name, System.Net.Http.Http3RequestStream.OnHeader(), System.Net.Http.Headers.HeaderDescriptor.TryGet(), and System.value.
Referenced by System.Net.Http.Http3RequestStream.OnHeader(), System.Net.Http.Http3RequestStream.OnStaticIndexedHeader(), and System.Net.Http.Http3RequestStream.OnStaticIndexedHeader().