Terraria: System.Net.Http.Http3RequestStream.ReadResponseContentAsync
ReadResponseContentAsync()
async ValueTask< int > System.Net.Http.Http3RequestStream.ReadResponseContentAsync (HttpResponseMessage response, Memory< byte > buffer, CancellationToken cancellationToken) inline private
Definition at line 1010 of file Http3RequestStream.cs.
    {
        _ = 1;
        try
        {
            int totalBytesRead = 0;
            while (buffer.Length != 0)
            {
                bool flag = _responseDataPayloadRemaining <= 0;
                bool flag2 = flag;
                if (flag2)
                {
                    flag2 = !(await ReadNextDataFrameAsync(response, cancellationToken).ConfigureAwait(continueOnCapturedContext: false));
                }
                if (flag2)
                {
                    break;
                }
                if (_recvBuffer.ActiveLength != 0)
                {
                    int num = (int)Math.Min(buffer.Length, Math.Min(_responseDataPayloadRemaining, _recvBuffer.ActiveLength));
                    Span<byte> span = _recvBuffer.ActiveSpan;
                    span = span.Slice(0, num);
                    span.CopyTo(buffer.Span);
                    totalBytesRead += num;
                    _responseDataPayloadRemaining -= num;
                    _recvBuffer.Discard(num);
                    buffer = buffer.Slice(num);
                    if (_responseDataPayloadRemaining == 0L && _recvBuffer.ActiveLength == 0)
                    {
                        break;
                    }
                    continue;
                }
                int length = (int)Math.Min(buffer.Length, _responseDataPayloadRemaining);
                int num2 = await _stream.ReadAsync(buffer.Slice(0, length), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                if (num2 == 0)
                {
                    throw new HttpRequestException(System.SR.Format(System.SR.net_http_invalid_response_premature_eof_bytecount, _responseDataPayloadRemaining));
                }
                totalBytesRead += num2;
                _responseDataPayloadRemaining -= num2;
                buffer = buffer.Slice(num2);
                break;
            }
            return totalBytesRead;
        }
        catch (Exception ex)
        {
            HandleReadResponseContentException(ex, cancellationToken);
            return 0;
        }
    }
References System.Net.Http.Http3RequestStream._recvBuffer, System.Net.Http.Http3RequestStream._responseDataPayloadRemaining, System.Net.Http.Http3RequestStream._stream, System.buffer, System.cancellationToken, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.SR.Format(), System.Net.Http.Http3RequestStream.HandleReadResponseContentException(), System.L, System.length, System.Math.Min(), System.SR.net_http_invalid_response_premature_eof_bytecount, System.Net.Quic.QuicStream.ReadAsync(), and System.Net.Http.Http3RequestStream.ReadNextDataFrameAsync().
Referenced by System.Net.Http.Http3RequestStream.Http3ReadStream.ReadAsync().