Terraria: System.Net.Http.Http3RequestStream.BufferHeaders
BufferHeaders()
void System.Net.Http.Http3RequestStream.BufferHeaders (HttpRequestMessage request) inline private
Definition at line 538 of file Http3RequestStream.cs.
    {
        _sendBuffer.Commit(9);
        _sendBuffer.EnsureAvailableSpace(2);
        _sendBuffer.AvailableSpan[0] = 0;
        _sendBuffer.AvailableSpan[1] = 0;
        _sendBuffer.Commit(2);
        HttpMethod httpMethod = HttpMethod.Normalize(request.Method);
        BufferBytes(httpMethod.Http3EncodedBytes);
        BufferIndexedHeader(23);
        if (request.HasHeaders && request.Headers.Host != null)
        {
            BufferLiteralHeaderWithStaticNameReference(0, request.Headers.Host);
        }
        else
        {
            BufferBytes(_connection.Pool._http3EncodedAuthorityHostHeader);
        }
        string pathAndQuery = request.RequestUri.PathAndQuery;
        if (pathAndQuery == "/")
        {
            BufferIndexedHeader(1);
        }
        else
        {
            BufferLiteralHeaderWithStaticNameReference(1, pathAndQuery);
        }
        BufferBytes(_connection.AltUsedEncodedHeaderBytes);
        if (request.HasHeaders)
        {
            if (request.HasHeaders && request.Headers.TransferEncodingChunked == true)
            {
                request.Headers.TransferEncodingChunked = false;
            }
            BufferHeaderCollection(request.Headers);
        }
        if (_connection.Pool.Settings._useCookies)
        {
            string cookieHeader = _connection.Pool.Settings._cookieContainer.GetCookieHeader(request.RequestUri);
            if (cookieHeader != string.Empty)
            {
                Encoding valueEncoding = _connection.Pool.Settings._requestHeaderEncodingSelector?.Invoke("Cookie", request);
                BufferLiteralHeaderWithStaticNameReference(5, cookieHeader, valueEncoding);
            }
        }
        if (request.Content == null)
        {
            if (httpMethod.MustHaveRequestBody)
            {
                BufferIndexedHeader(4);
            }
        }
        else
        {
            BufferHeaderCollection(request.Content.Headers);
        }
        int num = _sendBuffer.ActiveLength - 9;
        int byteCount = VariableLengthIntegerHelper.GetByteCount(num);
        _sendBuffer.Discard(9 - byteCount - 1);
        _sendBuffer.ActiveSpan[0] = 1;
        int num2 = VariableLengthIntegerHelper.WriteInteger(_sendBuffer.ActiveSpan.Slice(1, byteCount), num);
    }
References System.Net.Http.Http3RequestStream._connection, System.Net.Http.HttpConnectionSettings._cookieContainer, System.Net.Http.HttpConnectionPool._http3EncodedAuthorityHostHeader, System.Net.Http.HttpConnectionSettings._requestHeaderEncodingSelector, System.Net.Http.Http3RequestStream._sendBuffer, System.Net.Http.HttpConnectionSettings._useCookies, System.Net.Http.Http3Connection.AltUsedEncodedHeaderBytes, System.Net.Http.Http3RequestStream.BufferBytes(), System.Net.Http.Http3RequestStream.BufferHeaderCollection(), System.Net.Http.Http3RequestStream.BufferIndexedHeader(), System.Net.Http.Http3RequestStream.BufferLiteralHeaderWithStaticNameReference(), System.byteCount, System.Net.Http.VariableLengthIntegerHelper.GetByteCount(), System.Net.CookieContainer.GetCookieHeader(), System.Net.Http.HttpMethod.Normalize(), System.Net.Http.Http3Connection.Pool, System.Net.Http.HttpConnectionPool.Settings, and System.Net.Http.VariableLengthIntegerHelper.WriteInteger().
Referenced by System.Net.Http.Http3RequestStream.SendAsync().