Terraria: System.Net.Http.Http3RequestStream.Trace
Trace()
void System.Net.Http.Http3RequestStream.Trace (string message, [CallerMemberName] string memberName = null) inline
Definition at line 1125 of file Http3RequestStream.cs.
    {
        _connection.Trace(StreamId, message, memberName);
    }
References System.Net.Http.Http3RequestStream._connection, System.Net.Http.Http3RequestStream.StreamId, and System.Net.Http.Http3Connection.Trace().
Referenced by System.Net.Http.Http3RequestStream.DrainContentLength0Frames(), System.Net.Http.Http3RequestStream.GetStaticQPackHeader(), System.Net.Http.Http3RequestStream.OnHeader(), System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync(), System.Net.Http.Http3RequestStream.ReadHeadersAsync(), and System.Net.Http.Http3RequestStream.ReadResponseAsync().