Terraria: System.Net.Http.Http3RequestStream.BufferHeaderCollection
BufferHeaderCollection()
void System.Net.Http.Http3RequestStream.BufferHeaderCollection (HttpHeaders headers) inline private
Definition at line 601 of file Http3RequestStream.cs.
    {
        if (headers.HeaderStore == null)
        {
            return;
        }
        HeaderEncodingSelector<HttpRequestMessage> requestHeaderEncodingSelector = _connection.Pool.Settings._requestHeaderEncodingSelector;
        foreach (KeyValuePair<HeaderDescriptor, object> item in headers.HeaderStore)
        {
            int storeValuesIntoStringArray = HttpHeaders.GetStoreValuesIntoStringArray(item.Key, item.Value, ref _headerValues);
            ReadOnlySpan<string> readOnlySpan = _headerValues.AsSpan(0, storeValuesIntoStringArray);
            Encoding valueEncoding = requestHeaderEncodingSelector?.Invoke(item.Key.Name, _request);
            KnownHeader knownHeader = item.Key.KnownHeader;
            if (knownHeader != null)
            {
                if (knownHeader == KnownHeaders.Host || knownHeader == KnownHeaders.Connection || knownHeader == KnownHeaders.Upgrade || knownHeader == KnownHeaders.ProxyConnection)
                {
                    continue;
                }
                if (item.Key.KnownHeader == KnownHeaders.TE)
                {
                    ReadOnlySpan<string> readOnlySpan2 = readOnlySpan;
                    for (int i = 0; i < readOnlySpan2.Length; i++)
                    {
                        string text = readOnlySpan2[i];
                        if (string.Equals(text, "trailers", StringComparison.OrdinalIgnoreCase))
{
                            BufferLiteralHeaderWithoutNameReference("TE", text, valueEncoding);
                            break;
                        }
                    }
                }
                else
                {
                    BufferBytes(knownHeader.Http3EncodedName);
                    string separator = null;
                    if (readOnlySpan.Length > 1)
                    {
                        HttpHeaderParser parser = item.Key.Parser;
                        separator = ((parser == null || !parser.SupportsMultipleValues) ? ", " : parser.Separator);
                    }
                    BufferLiteralHeaderValues(readOnlySpan, separator, valueEncoding);
                }
            }
            else
            {
                BufferLiteralHeaderWithoutNameReference(item.Key.Name, readOnlySpan, ", ", valueEncoding);
            }
        }
    }
References System.Net.Http.Http3RequestStream._connection, System.Net.Http.Http3RequestStream._headerValues, System.Net.Http.Http3RequestStream._request, System.Net.Http.HttpConnectionSettings._requestHeaderEncodingSelector, System.Net.Http.Http3RequestStream.BufferBytes(), System.Net.Http.Http3RequestStream.BufferLiteralHeaderValues(), System.Net.Http.Http3RequestStream.BufferLiteralHeaderWithoutNameReference(), System.Net.Http.Headers.KnownHeaders.Connection, System.Net.Equals, System.Net.Http.Headers.HttpHeaders.GetStoreValuesIntoStringArray(), System.Net.Http.Headers.KnownHeaders.Host, System.item, System.Net.Http.Http3Connection.Pool, System.Net.Http.Headers.KnownHeaders.ProxyConnection, System.Net.Http.HttpConnectionPool.Settings, System.Net.Http.Headers.KnownHeaders.TE, System.text, and System.Net.Http.Headers.KnownHeaders.Upgrade.
Referenced by System.Net.Http.Http3RequestStream.BufferHeaders().