Terraria: System.Net.Http.Http3RequestStream.ReadHeadersAsync
ReadHeadersAsync()
async ValueTask System.Net.Http.Http3RequestStream.ReadHeadersAsync (long headersLength, CancellationToken cancellationToken) inline private
Definition at line 769 of file Http3RequestStream.cs.
    {
        if (headersLength > _headerBudgetRemaining)
        {
            _stream.AbortWrite(263L);
            throw new HttpRequestException(System.SR.Format(System.SR.net_http_response_headers_exceeded_length, (long)_connection.Pool.Settings._maxResponseHeadersLength * 1024L));
        }
        _headerBudgetRemaining -= headersLength;
        while (headersLength != 0L)
        {
            if (_recvBuffer.ActiveLength == 0)
            {
                _recvBuffer.EnsureAvailableSpace(1);
                int num = await _stream.ReadAsync(_recvBuffer.AvailableMemory, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                if (num == 0)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        Trace($"Server closed response stream before entire header payload could be read. {headersLength:N0} bytes remaining.", "ReadHeadersAsync");
                    }
                    throw new HttpRequestException(System.SR.net_http_invalid_response_premature_eof);
                }
                _recvBuffer.Commit(num);
            }
            int num2 = (int)Math.Min(headersLength, _recvBuffer.ActiveLength);
            _headerDecoder.Decode(_recvBuffer.ActiveSpan.Slice(0, num2), this);
            _recvBuffer.Discard(num2);
            headersLength -= num2;
        }
        _headerDecoder.Reset();
    }
References System.Net.Http.Http3RequestStream._connection, System.Net.Http.Http3RequestStream._headerBudgetRemaining, System.Net.Http.Http3RequestStream._headerDecoder, System.Net.Http.HttpConnectionSettings._maxResponseHeadersLength, System.Net.Http.Http3RequestStream._recvBuffer, System.Net.Http.Http3RequestStream._stream, System.Net.Quic.QuicStream.AbortWrite(), System.cancellationToken, System.Net.Http.QPack.QPackDecoder.Decode(), System.SR.Format(), System.L, System.Net.NetEventSource.Log, System.Math.Min(), System.SR.net_http_invalid_response_premature_eof, System.SR.net_http_response_headers_exceeded_length, System.Net.Http.Http3Connection.Pool, System.Net.Quic.QuicStream.ReadAsync(), System.Net.Http.QPack.QPackDecoder.Reset(), System.Net.Http.HttpConnectionPool.Settings, and System.Net.Http.Http3RequestStream.Trace().
Referenced by System.Net.Http.Http3RequestStream.DrainContentLength0Frames(), System.Net.Http.Http3RequestStream.ReadNextDataFrameAsync(), and System.Net.Http.Http3RequestStream.ReadResponseAsync().