Terraria: System.Net.Http.Http3RequestStream.HandleReadResponseContentException
HandleReadResponseContentException()
void System.Net.Http.Http3RequestStream.HandleReadResponseContentException (Exception ex, CancellationToken cancellationToken) inline private
Definition at line 1064 of file Http3RequestStream.cs.
    {
        if (!(ex is QuicStreamAbortedException) && !(ex is QuicOperationAbortedException))
        {
            if (!(ex is QuicConnectionAbortedException))
            {
                if (!(ex is Http3ConnectionException))
                {
                    if (ex is OperationCanceledException ex2 && ex2.CancellationToken == cancellationToken)
                    {
                        _stream.AbortRead(268L);
                        ExceptionDispatchInfo.Throw(ex);
                        return;
                    }
                    _stream.AbortRead(258L);
                    throw new IOException(System.SR.net_http_client_execution_error, new HttpRequestException(System.SR.net_http_client_execution_error, ex));
                }
                _connection.Abort(ex);
                throw new IOException(System.SR.net_http_client_execution_error, new HttpRequestException(System.SR.net_http_client_execution_error, ex));
            }
            Exception inner = _connection.Abort(ex);
            throw new IOException(System.SR.net_http_client_execution_error, new HttpRequestException(System.SR.net_http_client_execution_error, inner));
        }
        throw new IOException(System.SR.net_http_client_execution_error, new HttpRequestException(System.SR.net_http_client_execution_error, ex));
    }
References System.Net.Http.Http3RequestStream._connection, System.Net.Http.Http3RequestStream._stream, System.Net.Http.Http3Connection.Abort(), System.Net.Quic.QuicStream.AbortRead(), System.cancellationToken, System.L, System.SR.net_http_client_execution_error, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Net.Http.Http3RequestStream.ReadResponseContent(), and System.Net.Http.Http3RequestStream.ReadResponseContentAsync().