Terraria: System.Net.Http.Http3RequestStream.DrainContentLength0Frames
DrainContentLength0Frames()
async ValueTask System.Net.Http.Http3RequestStream.DrainContentLength0Frames (CancellationToken cancellationToken) inline private
Definition at line 492 of file Http3RequestStream.cs.
    {
        while (true)
        {
            var (http3FrameType, num) = await ReadFrameEnvelopeAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            if (http3FrameType.HasValue)
            {
                Http3FrameType valueOrDefault = http3FrameType.GetValueOrDefault();
                if (valueOrDefault == Http3FrameType.Data)
                {
                    if (num != 0L)
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            Trace("Response content exceeded Content-Length.", "DrainContentLength0Frames");
                        }
                        throw new HttpRequestException(System.SR.net_http_invalid_response);
                    }
                    continue;
                }
                if (valueOrDefault != Http3FrameType.Headers)
                {
                    break;
                }
                _trailingHeaders = new List<(HeaderDescriptor, string)>();
                await ReadHeadersAsync(num, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            CopyTrailersToResponseMessage(_response);
            break;
        }
    }
References System.Net.Http.Http3RequestStream._response, System.Net.Http.Http3RequestStream._trailingHeaders, System.cancellationToken, System.Net.Http.Http3RequestStream.CopyTrailersToResponseMessage(), System.L, System.Net.NetEventSource.Log, System.SR.net_http_invalid_response, System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync(), System.Net.Http.Http3RequestStream.ReadHeadersAsync(), and System.Net.Http.Http3RequestStream.Trace().
Referenced by System.Net.Http.Http3RequestStream.SendAsync().