Terraria: System.Net.Http.Http3RequestStream.ReadResponseAsync
ReadResponseAsync()
async Task System.Net.Http.Http3RequestStream.ReadResponseAsync (CancellationToken cancellationToken) inline private
Definition at line 383 of file Http3RequestStream.cs.
    {
        do
        {
            _headerState = HeaderState.StatusHeader;
            var (http3FrameType, headersLength) = await ReadFrameEnvelopeAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            if (http3FrameType != Http3FrameType.Headers)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Expected HEADERS as first response frame; received {http3FrameType}.", "ReadResponseAsync");
                }
                throw new HttpRequestException(System.SR.net_http_invalid_response);
            }
            await ReadHeadersAsync(headersLength, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        while (_response.StatusCode < HttpStatusCode.OK);
        _headerState = HeaderState.TrailingHeaders;
    }
References System.Net.Http.Http3RequestStream._headerState, System.Net.Http.Http3RequestStream._response, System.cancellationToken, System.Net.NetEventSource.Log, System.SR.net_http_invalid_response, System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync(), System.Net.Http.Http3RequestStream.ReadHeadersAsync(), System.Net.Http.HttpResponseMessage.StatusCode, and System.Net.Http.Http3RequestStream.Trace().
Referenced by System.Net.Http.Http3RequestStream.SendAsync().