Terraria: System.Net.Http.Http3RequestStream.OnHeader
OnHeader() [1/2]
void System.Net.Http.Http3RequestStream.OnHeader (int? staticIndex, HeaderDescriptor descriptor, string staticValue, ReadOnlySpan< byte > literalValue) inline private
Definition at line 834 of file Http3RequestStream.cs.
    {
        if (descriptor.Name[0] == ':')
        {
            if (descriptor.KnownHeader != KnownHeaders.PseudoStatus)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace("Received unknown pseudo-header '" + descriptor.Name + "'.", "OnHeader");
                }
                throw new Http3ConnectionException(Http3ErrorCode.ProtocolError);
            }
            if (_headerState != 0)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace("Received extra status header.", "OnHeader");
                }
                throw new Http3ConnectionException(Http3ErrorCode.ProtocolError);
            }
            int num = ((staticValue == null) ? HttpConnectionBase.ParseStatusCode(literalValue) : (staticIndex switch
            {
                24 => 103,
                25 => 200,
                26 => 304,
                27 => 404,
                28 => 503,
                63 => 100,
                64 => 204,
                65 => 206,
                66 => 302,
                67 => 400,
                68 => 403,
                69 => 421,
                70 => 425,
                71 => 500,
                _ => ParseStatusCode(staticIndex, staticValue),
            }));
            _response = new HttpResponseMessage
            {
                Version = HttpVersion.Version30,
                RequestMessage = _request,
                Content = new HttpConnectionResponseContent(),
                StatusCode = (HttpStatusCode)num
            };
            if (num < 200)
            {
                _headerState = HeaderState.SkipExpect100Headers;
                if (_response.StatusCode == HttpStatusCode.Continue && _expect100ContinueCompletionSource != null)
                {
                    _expect100ContinueCompletionSource.TrySetResult(result: true);
                }
                return;
            }
            _headerState = HeaderState.ResponseHeaders;
            if (_expect100ContinueCompletionSource != null)
            {
                bool result = num < 300;
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Expecting 100 Continue but received final status {num}.", "OnHeader");
                }
                _expect100ContinueCompletionSource.TrySetResult(result);
            }
        }
        else
        {
            if (_headerState == HeaderState.SkipExpect100Headers)
            {
                return;
            }
            string text = staticValue;
            if (text == null)
            {
                Encoding valueEncoding = _connection.Pool.Settings._responseHeaderEncodingSelector?.Invoke(descriptor.Name, _request);
                text = _connection.GetResponseHeaderValueWithCaching(descriptor, literalValue, valueEncoding);
            }
            switch (_headerState)
            {
            case HeaderState.StatusHeader:
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace("Received headers without :status.", "OnHeader");
                }
                throw new Http3ConnectionException(Http3ErrorCode.ProtocolError);
            case HeaderState.ResponseHeaders:
                if (descriptor.HeaderType.HasFlag(HttpHeaderType.Content))
                {
                    _response.Content.Headers.TryAddWithoutValidation(descriptor, text);
                }
                else
                {
                    _response.Headers.TryAddWithoutValidation(descriptor.HeaderType.HasFlag(HttpHeaderType.Request) ? descriptor.AsCustomHeader() : descriptor, text);
                }
                break;
            case HeaderState.TrailingHeaders:
                _trailingHeaders.Add((descriptor.HeaderType.HasFlag(HttpHeaderType.Request) ? descriptor.AsCustomHeader() : descriptor, text));
                break;
            case HeaderState.SkipExpect100Headers:
                break;
            }
        }
        int ParseStatusCode(int? index, string value)
        {
            string message = $"Unexpected QPACK table reference for Status code: index={index} value='{value}'";
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace(message, "OnHeader");
            }
            return HttpConnectionBase.ParseStatusCode(Encoding.ASCII.GetBytes(value));
        }
    }
References System.Net.Http.Http3RequestStream._connection, System.Net.Http.Http3RequestStream._expect100ContinueCompletionSource, System.Net.Http.Http3RequestStream._headerState, System.Net.Http.Http3RequestStream._request, System.Net.Http.Http3RequestStream._response, System.Net.Http.HttpConnectionSettings._responseHeaderEncodingSelector, System.Net.Http.Http3RequestStream._trailingHeaders, System.Collections.Generic.List< T >.Add(), System.Text.Encoding.ASCII, System.Net.Http.Headers.HeaderDescriptor.AsCustomHeader(), System.Net.Http.HttpResponseMessage.Content, System.Net.Http.HttpConnectionBase.GetResponseHeaderValueWithCaching(), System.Net.Http.HttpContent.Headers, System.Net.Http.HttpResponseMessage.Headers, System.Net.Http.Headers.HeaderDescriptor.HeaderType, System.index, System.Net.Http.Headers.HeaderDescriptor.KnownHeader, System.Net.NetEventSource.Log, System.Net.Http.Headers.HeaderDescriptor.Name, System.Net.Http.HttpConnectionBase.ParseStatusCode(), System.Net.Http.Http3Connection.Pool, System.Net.Http.Headers.KnownHeaders.PseudoStatus, System.Net.Http.HttpConnectionPool.Settings, System.Net.Http.HttpResponseMessage.StatusCode, System.text, System.Net.Http.Http3RequestStream.Trace(), System.Net.Http.Headers.HttpHeaders.TryAddWithoutValidation(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetResult(), System.value, and System.Net.HttpVersion.Version30.