Terraria: System.Net.Http.Http3RequestStream.DisposeAsync
DisposeAsync()
async ValueTask System.Net.Http.Http3RequestStream.DisposeAsync () inline
Implements System.IAsyncDisposable.
Definition at line 227 of file Http3RequestStream.cs.
    {
        if (!_disposed)
        {
            _disposed = true;
            AbortStream();
            await _stream.DisposeAsync().ConfigureAwait(continueOnCapturedContext: false);
            DisposeSyncHelper();
        }
    }
References System.Net.Http.Http3RequestStream._disposed, System.Net.Http.Http3RequestStream._stream, System.Net.Http.Http3RequestStream.AbortStream(), System.IO.Stream.DisposeAsync(), and System.Net.Http.Http3RequestStream.DisposeSyncHelper().
Referenced by System.Net.Http.Http3RequestStream.SendAsync().