Terraria: System.Net.Http.Http3RequestStream.Dispose
Dispose()
void System.Net.Http.Http3RequestStream.Dispose () inline
Implements System.IDisposable.
Definition at line 216 of file Http3RequestStream.cs.
    {
        if (!_disposed)
        {
            _disposed = true;
            AbortStream();
            _stream.Dispose();
            DisposeSyncHelper();
        }
    }
References System.Net.Http.Http3RequestStream._disposed, System.Net.Http.Http3RequestStream._stream, System.Net.Http.Http3RequestStream.AbortStream(), System.Net.Quic.QuicStream.Dispose(), and System.Net.Http.Http3RequestStream.DisposeSyncHelper().
Referenced by System.Net.Http.Http3RequestStream.Http3ReadStream.~Http3ReadStream().