Terraria: System.Net.Http.Http3RequestStream.DisposeSyncHelper
DisposeSyncHelper()
void System.Net.Http.Http3RequestStream.DisposeSyncHelper () inline private
Definition at line 238 of file Http3RequestStream.cs.
    {
        _connection.RemoveStream(_stream);
        _sendBuffer.Dispose();
        _recvBuffer.Dispose();
        Interlocked.Exchange(ref _goawayCancellationSource, null)?.Dispose();
    }
References System.Net.Http.Http3RequestStream._connection, System.Net.Http.Http3RequestStream._goawayCancellationSource, System.Net.Http.Http3RequestStream._recvBuffer, System.Net.Http.Http3RequestStream._sendBuffer, System.Net.Http.Http3RequestStream._stream, System.Threading.Interlocked.Exchange(), and System.Net.Http.Http3Connection.RemoveStream().
Referenced by System.Net.Http.Http3RequestStream.Dispose(), and System.Net.Http.Http3RequestStream.DisposeAsync().