Terraria: System.Net.Http.Http3RequestStream.SendContentAsync
SendContentAsync()
async Task System.Net.Http.Http3RequestStream.SendContentAsync (HttpContent content, CancellationToken cancellationToken) inline private
Definition at line 403 of file Http3RequestStream.cs.
    {
        if (_expect100ContinueCompletionSource != null)
        {
            Timer timer = null;
            try
            {
                if (_connection.Pool.Settings._expect100ContinueTimeout != Timeout.InfiniteTimeSpan)
                {
                    timer = new Timer(delegate(object o)
                    {
                        ((Http3RequestStream)o)._expect100ContinueCompletionSource.TrySetResult(result: true);
                    }, this, _connection.Pool.Settings._expect100ContinueTimeout, Timeout.InfiniteTimeSpan);
                }
                if (!(await _expect100ContinueCompletionSource.Task.ConfigureAwait(continueOnCapturedContext: false)))
                {
                    return;
                }
            }
            finally
            {
                if (timer != null)
                {
                    await timer.DisposeAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
            }
        }
        _requestContentLengthRemaining = content.Headers.ContentLength ?? (-1);
        using (Http3WriteStream writeStream = new Http3WriteStream(this))
        {
            await content.CopyToAsync(writeStream, null, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        _requestContentLengthRemaining = 0L;
        if (_sendBuffer.ActiveLength != 0)
        {
            await FlushSendBufferAsync(endStream: true, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            _stream.Shutdown();
        }
    }
References System.Net.Http.Http3RequestStream.Http3RequestStream(), System.Net.Http.Http3RequestStream._connection, System.Net.Http.Http3RequestStream._expect100ContinueCompletionSource, System.Net.Http.HttpConnectionSettings._expect100ContinueTimeout, System.Net.Http.Http3RequestStream._requestContentLengthRemaining, System.Net.Http.Http3RequestStream._sendBuffer, System.Net.Http.Http3RequestStream._stream, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.HttpContent.CopyToAsync(), System.Net.Http.Http3RequestStream.FlushSendBufferAsync(), System.Threading.Timeout.InfiniteTimeSpan, System.L, System.Net.Http.Http3Connection.Pool, System.Net.Http.HttpConnectionPool.Settings, System.Net.Quic.QuicStream.Shutdown(), and System.Threading.Tasks.TaskCompletionSource< TResult >.Task.
Referenced by System.Net.Http.Http3RequestStream.SendAsync().