Terraria: System.Net.Http.Http3RequestStream.BufferBytes
BufferBytes()
void System.Net.Http.Http3RequestStream.BufferBytes (ReadOnlySpan< byte > span) inline private
Definition at line 712 of file Http3RequestStream.cs.
    {
        _sendBuffer.EnsureAvailableSpace(span.Length);
        span.CopyTo(_sendBuffer.AvailableSpan);
        _sendBuffer.Commit(span.Length);
    }
References System.Net.Http.Http3RequestStream._sendBuffer, and System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo().
Referenced by System.Net.Http.Http3RequestStream.BufferHeaderCollection(), and System.Net.Http.Http3RequestStream.BufferHeaders().