Terraria: System.Net.Http.Http3RequestStream.ReadNextDataFrameAsync
ReadNextDataFrameAsync()
async ValueTask< bool > System.Net.Http.Http3RequestStream.ReadNextDataFrameAsync (HttpResponseMessage response, CancellationToken cancellationToken) inline private
Definition at line 1090 of file Http3RequestStream.cs.
    {
        if (_responseDataPayloadRemaining == -1)
        {
            return false;
        }
        while (true)
        {
            var (http3FrameType, num) = await ReadFrameEnvelopeAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            switch (http3FrameType)
            {
            default:
                continue;
            case Http3FrameType.Data:
                goto IL_00d6;
            case Http3FrameType.Headers:
                _trailingHeaders = new List<(HeaderDescriptor, string)>();
                await ReadHeadersAsync(num, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                break;
            case null:
                break;
            }
            break;
            IL_00d6:
            if (num != 0L)
            {
                _responseDataPayloadRemaining = num;
                return true;
            }
        }
        CopyTrailersToResponseMessage(response);
        _responseDataPayloadRemaining = -1L;
        return false;
    }
References System.Net.Http.Http3RequestStream._responseDataPayloadRemaining, System.Net.Http.Http3RequestStream._trailingHeaders, System.cancellationToken, System.Net.Http.Http3RequestStream.CopyTrailersToResponseMessage(), System.L, System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync(), and System.Net.Http.Http3RequestStream.ReadHeadersAsync().
Referenced by System.Net.Http.Http3RequestStream.ReadResponseContent(), and System.Net.Http.Http3RequestStream.ReadResponseContentAsync().