Terraria: System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync
ReadFrameEnvelopeAsync()
async ValueTask<(Http3FrameType? frameType, long payloadLength)> System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync (CancellationToken cancellationToken) inline private
Definition at line 719 of file Http3RequestStream.cs.
    {
        while (true)
        {
            if (!Http3Frame.TryReadIntegerPair(_recvBuffer.ActiveSpan, out var a, out var b, out var bytesRead))
            {
                _recvBuffer.EnsureAvailableSpace(16);
                bytesRead = await _stream.ReadAsync(_recvBuffer.AvailableMemory, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                if (bytesRead == 0)
                {
                    break;
                }
                _recvBuffer.Commit(bytesRead);
                continue;
            }
            _recvBuffer.Discard(bytesRead);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace($"Received frame {a} of length {b}.", "ReadFrameEnvelopeAsync");
            }
            Http3FrameType http3FrameType = (Http3FrameType)a;
            if ((ulong)http3FrameType <= 13uL)
            {
                switch (http3FrameType)
                {
                case Http3FrameType.Data:
                case Http3FrameType.Headers:
                    return ((Http3FrameType)a, b);
                case Http3FrameType.ReservedHttp2Priority:
                case Http3FrameType.Settings:
                case Http3FrameType.ReservedHttp2Ping:
                case Http3FrameType.GoAway:
                case Http3FrameType.ReservedHttp2WindowUpdate:
                case Http3FrameType.ReservedHttp2Continuation:
                case Http3FrameType.MaxPushId:
                    throw new Http3ConnectionException(Http3ErrorCode.UnexpectedFrame);
                case Http3FrameType.CancelPush:
                case Http3FrameType.PushPromise:
                    throw new Http3ConnectionException(Http3ErrorCode.IdError);
                }
            }
            await SkipUnknownPayloadAsync(b, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        if (_recvBuffer.ActiveLength == 0)
        {
            return (null, 0L);
        }
        throw new HttpRequestException(System.SR.net_http_invalid_response_premature_eof);
    }
References System.Net.Http.Http3RequestStream._recvBuffer, System.Net.Http.Http3RequestStream._stream, System.cancellationToken, System.L, System.Net.NetEventSource.Log, System.SR.net_http_invalid_response_premature_eof, System.Net.Quic.QuicStream.ReadAsync(), System.Net.Http.Http3RequestStream.SkipUnknownPayloadAsync(), System.Net.Http.Http3RequestStream.Trace(), and System.Net.Http.Http3Frame.TryReadIntegerPair().
Referenced by System.Net.Http.Http3RequestStream.DrainContentLength0Frames(), System.Net.Http.Http3RequestStream.ReadNextDataFrameAsync(), and System.Net.Http.Http3RequestStream.ReadResponseAsync().