Terraria: System.Net.Http.Http3RequestStream.GetStaticQPackHeader
GetStaticQPackHeader()
void System.Net.Http.Http3RequestStream.GetStaticQPackHeader (int index, out HeaderDescriptor descriptor, out string knownValue) inline private
Definition at line 822 of file Http3RequestStream.cs.
    {
        if (!HeaderDescriptor.TryGetStaticQPackHeader(index, out descriptor, out knownValue))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace($"Response contains invalid static header index '{index}'.", "GetStaticQPackHeader");
            }
            throw new Http3ConnectionException(Http3ErrorCode.ProtocolError);
        }
    }
References System.index, System.Net.NetEventSource.Log, System.Net.Http.Http3RequestStream.Trace(), and System.Net.Http.Headers.HeaderDescriptor.TryGetStaticQPackHeader().
Referenced by System.Net.Http.Http3RequestStream.OnStaticIndexedHeader(), and System.Net.Http.Http3RequestStream.OnStaticIndexedHeader().