Terraria: UIKeybindingListItem.DrawSelf
DrawSelf()
override void UIKeybindingListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         float num = 6f;
         base.DrawSelf(spriteBatch);
         CalculatedStyle dimensions = GetDimensions();
         float num2 = dimensions.Width + 1f;
         Vector2 vector = new Vector2(dimensions.X, dimensions.Y);
         bool flag = PlayerInput.ListeningTrigger == _keybind;
         Vector2 baseScale = new Vector2(0.8f);
         Color value = (flag ? Color.Gold : (base.IsMouseHovering ? Color.White : Color.Silver));
         value = Color.Lerp(value, Color.White, base.IsMouseHovering ? 0.5f : 0f);
         Color color = (base.IsMouseHovering ? _color : _color.MultiplyRGBA(new Color(180, 180, 180)));
         Vector2 position = vector;
         Utils.DrawSettingsPanel(spriteBatch, position, num2, color);
         position.X += 8f;
         position.Y += 2f + num;
         ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, GetFriendlyName(), position, value, 0f, Vector2.Zero, baseScale, num2);
         position.X -= 17f;
         List<string> list = PlayerInput.CurrentProfile.InputModes[_inputmode].KeyStatus[_keybind];
         string text = GenInput(list);
         if (string.IsNullOrEmpty(text))
         {
             text = Lang.menu[195].Value;
             if (!flag)
             {
                 value = new Color(80, 80, 80);
             }
         }
         Vector2 stringSize = ChatManager.GetStringSize(FontAssets.ItemStack.Value, text, baseScale);
         position = new Vector2(dimensions.X + dimensions.Width - stringSize.X - 10f, dimensions.Y + 2f + num);
         if (_inputmode == InputMode.XBoxGamepad || _inputmode == InputMode.XBoxGamepadUI)
         {
             position += new Vector2(0f, -3f);
         }
         GlyphTagHandler.GlyphsScale = 0.85f;
         ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, text, position, value, 0f, Vector2.Zero, baseScale, num2);
         GlyphTagHandler.GlyphsScale = 1f;
     }
References _color, _inputmode, _keybind, Color, PlayerInput.CurrentProfile, ChatManager.DrawColorCodedStringWithShadow(), Utils.DrawSettingsPanel(), GenInput(), UIElement.GetDimensions(), GetFriendlyName(), ChatManager.GetStringSize(), GlyphTagHandler.GlyphsScale, PlayerInputProfile.InputModes, FontAssets.ItemStack, PlayerInput.ListeningTrigger, Lang.menu, Asset< T >.Value, LocalizedText.Value, CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.