Terraria: Terraria.DelegateMethods.CastLightOpen
CastLightOpen()
static bool Terraria.DelegateMethods.CastLightOpen (int x, int y) inline static
    {
        if (x < 0 || x >= Main.maxTilesX || y < 0 || y >= Main.maxTilesY)
        {
            return false;
        }
        if (Main.tile[x, y] == null)
        {
            return false;
        }
        if (!Main.tile[x, y].active() || Main.tile[x, y].inActive() || Main.tileSolidTop[Main.tile[x, y].type] || !Main.tileSolid[Main.tile[x, y].type])
        {
            Lighting.AddLight(x, y, v3_1.X, v3_1.Y, v3_1.Z);
        }
        return true;
    }
References Terraria.Tile.active(), Terraria.Lighting.AddLight(), Terraria.Tile.inActive(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, and Terraria.DelegateMethods.v3_1.
Referenced by Terraria.Projectile.AI_001(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_109_DarkMage(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_139_ExplosiveTrapExplosion(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_156_BatOfLight(), Terraria.Projectile.AI_180_FairyQueenSunDance(), Terraria.Player.ApplyEquipFunctional(), Terraria.Mount.UpdateEffects(), and Terraria.Player.Yoraiz0rEye().