Terraria: Terraria.Graphics.Capture.CaptureBiome.GetCaptureBiome
GetCaptureBiome()
static CaptureBiome Terraria.Graphics.Capture.CaptureBiome.GetCaptureBiome (int biomeChoice) inline static
Definition at line 108 of file CaptureBiome.cs.
    {
        switch ((BiomeChoiceIndex)biomeChoice)
        {
        case BiomeChoiceIndex.Purity:
            return GetPurityForPlayer();
        case BiomeChoiceIndex.Corruption:
            return Styles.Corruption;
        case BiomeChoiceIndex.Jungle:
            return Styles.Jungle;
        case BiomeChoiceIndex.Hallow:
            return Styles.Hallow;
        case BiomeChoiceIndex.Snow:
            return Styles.Snow;
        case BiomeChoiceIndex.Desert:
            return Styles.Desert;
        case BiomeChoiceIndex.DirtLayer:
            return Styles.DirtLayer;
        case BiomeChoiceIndex.RockLayer:
            return Styles.RockLayer;
        case BiomeChoiceIndex.Crimson:
            return Styles.Crimson;
        case BiomeChoiceIndex.UndergroundDesert:
            return Styles.UndergroundDesert;
        case BiomeChoiceIndex.Ocean:
            return Styles.Ocean;
        case BiomeChoiceIndex.Mushroom:
            return Styles.Mushroom;
        default:
        {
            CaptureBiome biomeByLocation = GetBiomeByLocation();
            if (biomeByLocation != null)
            {
                return biomeByLocation;
            }
            CaptureBiome biomeByWater = GetBiomeByWater();
            if (biomeByWater != null)
            {
                return biomeByWater;
            }
            return GetPurityForPlayer();
        }
        }
    }
References Terraria.Graphics.Capture.CaptureBiome.Styles.Corruption, Terraria.Graphics.Capture.CaptureBiome.Styles.Crimson, Terraria.Graphics.Capture.CaptureBiome.Styles.Desert, Terraria.Graphics.Capture.CaptureBiome.Styles.DirtLayer, Terraria.Graphics.Capture.CaptureBiome.GetBiomeByLocation(), Terraria.Graphics.Capture.CaptureBiome.GetBiomeByWater(), Terraria.Graphics.Capture.CaptureBiome.GetPurityForPlayer(), Terraria.Graphics.Capture.CaptureBiome.Styles.Hallow, Terraria.Graphics.Capture.CaptureBiome.Styles.Jungle, Terraria.Graphics.Capture.CaptureBiome.Styles.Mushroom, Terraria.Graphics.Capture.CaptureBiome.Styles.Ocean, Terraria.Graphics.Capture.CaptureBiome.Styles.RockLayer, Terraria.Graphics.Capture.CaptureBiome.Styles.Snow, and Terraria.Graphics.Capture.CaptureBiome.Styles.UndergroundDesert.
Referenced by Terraria.Graphics.Capture.CaptureInterface.QuickScreenshot(), and Terraria.Graphics.Capture.CaptureInterface.UpdateButtons().