Terraria: Terraria.DelegateMethods.SpreadLightOpen_StopForSolids
SpreadLightOpen_StopForSolids()
static bool Terraria.DelegateMethods.SpreadLightOpen_StopForSolids (int x, int y) inline static
Definition at line 688 of file DelegateMethods.cs.
    {
        if (Vector2.Distance(v2_1, new Vector2(x, y)) > f_1)
        {
            return false;
        }
        if (!Main.tile[x, y].active() || Main.tile[x, y].inActive() || Main.tileSolidTop[Main.tile[x, y].type] || !Main.tileSolid[Main.tile[x, y].type])
        {
            Vector3 vector = v3_1;
            new Vector2(x, y);
            Lighting.AddLight(x, y, vector.X, vector.Y, vector.Z);
            return true;
        }
        return false;
    }
References Terraria.Lighting.AddLight(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.DelegateMethods.f_1, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.DelegateMethods.v2_1, Terraria.DelegateMethods.v3_1, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.Player.ItemCheck_EmitHeldItemLight(), and Terraria.Projectile.ProjLight().