Terraria: Terraria.DelegateMethods.SearchAvoidedByNPCs
SearchAvoidedByNPCs()
static bool Terraria.DelegateMethods.SearchAvoidedByNPCs (int x, int y) inline static
    {
        if (!WorldGen.InWorld(x, y, 1))
        {
            return false;
        }
        if (Main.tile[x, y] == null)
        {
            return false;
        }
        if (!Main.tile[x, y].active() || !TileID.Sets.AvoidedByNPCs[Main.tile[x, y].type])
        {
            return true;
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.AvoidedByNPCs, Terraria.WorldGen.InWorld(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.NPC.AI_007_TownEntities(), and Terraria.NPC.AI_007_TownEntities_GetWalkPrediction().