Terraria: Terraria.DelegateMethods.SpreadHoney
SpreadHoney()
static bool Terraria.DelegateMethods.SpreadHoney (int x, int y) inline static
Definition at line 509 of file DelegateMethods.cs.
    {
        if (Vector2.Distance(v2_1, new Vector2(x, y)) > f_1)
        {
            return false;
        }
        if (WorldGen.PlaceLiquid(x, y, 2, byte.MaxValue))
        {
            Vector2 position = new Vector2(x * 16, y * 16);
            int type = 152;
            for (int i = 0; i < 3; i++)
            {
                Dust dust = Dust.NewDustDirect(position, 16, 16, type, 0f, 0f, 100, Color.Transparent, 2.2f);
                dust.velocity.Y -= 1.2f;
                dust.velocity *= 7f;
                Dust dust2 = Dust.NewDustDirect(position, 16, 16, type, 0f, 0f, 100, Color.Transparent, 1.3f);
                dust2.velocity.Y -= 1.2f;
                dust2.velocity *= 4f;
            }
            return true;
        }
        return false;
    }
References Microsoft.Xna.Framework.Vector2.Distance(), Terraria.DelegateMethods.f_1, Terraria.Dust.NewDustDirect(), Terraria.WorldGen.PlaceLiquid(), Microsoft.Xna.Framework.Color.Transparent, System.type, and Terraria.DelegateMethods.v2_1.
Referenced by Terraria.Projectile.Kill().