Terraria: NetMessage.ReceiveBytes
ReceiveBytes()
static void NetMessage.ReceiveBytes (byte[] bytes, int streamLength, int i = 256) inline static
     {
         lock (buffer[i])
         {
             try
             {
                 Buffer.BlockCopy(bytes, 0, buffer[i].readBuffer, buffer[i].totalData, streamLength);
                 buffer[i].totalData += streamLength;
                 buffer[i].checkBytes = true;
             }
             catch
             {
                 if (Main.netMode == 1)
                 {
                     Main.menuMode = 15;
                     Main.statusText = Language.GetTextValue("Error.BadHeaderBufferOverflow");
                     Netplay.Disconnect = true;
                 }
                 else
                 {
                     Netplay.Clients[i].PendingTermination = true;
                 }
             }
         }
     }
References buffer, MessageBuffer.checkBytes, Netplay.Clients, Netplay.Disconnect, Language.GetTextValue(), Main.menuMode, Main.netMode, RemoteClient.PendingTermination, Main.statusText, and MessageBuffer.totalData.
Referenced by RemoteServer.ClientReadCallBack(), and RemoteClient.ServerReadCallBack().