Terraria: NetMessage.EnsureLocalPlayerIsPresent
EnsureLocalPlayerIsPresent()
static void NetMessage.EnsureLocalPlayerIsPresent () inline static private
     {
         if (!Main.autoShutdown)
         {
             return;
         }
         bool flag = false;
         for (int i = 0; i < 255; i++)
         {
             if (DoesPlayerSlotCountAsAHost(i))
             {
                 flag = true;
                 break;
             }
         }
         if (!flag)
         {
             Console.WriteLine(Language.GetTextValue("Net.ServerAutoShutdown"));
             Netplay.Disconnect = true;
         }
     }
References Main.autoShutdown, Netplay.Disconnect, DoesPlayerSlotCountAsAHost(), and Language.GetTextValue().
Referenced by SyncConnectedPlayer(), and SyncDisconnectedPlayer().