Terraria: NetMessage.sendWater
sendWater()
static void NetMessage.sendWater (int x, int y) inline static
     {
         if (Main.netMode == 1)
         {
             SendData(48, -1, -1, null, x, y);
             return;
         }
         for (int i = 0; i < 256; i++)
         {
             if ((buffer[i].broadcast || Netplay.Clients[i].State >= 3) && Netplay.Clients[i].IsConnected())
             {
                 int num = x / 200;
                 int num2 = y / 150;
                 if (Netplay.Clients[i].TileSections[num, num2])
                 {
                     SendData(48, i, -1, null, x, y);
                 }
             }
         }
     }
References buffer, Netplay.Clients, RemoteClient.IsConnected(), Main.netMode, SendData(), RemoteClient.State, and RemoteClient.TileSections.
Referenced by WorldGen.EmptyLiquid(), Player.ItemCheck_UseBuckets(), and WorldGen.PlaceLiquid().