Terraria: NetMessage.CheckBytes
CheckBytes()
static void NetMessage.CheckBytes (int bufferIndex = 256) inline static
     {
         lock (buffer[bufferIndex])
         {
             if (Main.dedServ && Netplay.Clients[bufferIndex].PendingTermination)
             {
                 Netplay.Clients[bufferIndex].PendingTerminationApproved = true;
                 buffer[bufferIndex].checkBytes = false;
                 return;
             }
             int num = 0;
             int num2 = buffer[bufferIndex].totalData;
             try
             {
                 while (num2 >= 2)
                 {
                     int num3 = BitConverter.ToUInt16(buffer[bufferIndex].readBuffer, num);
                     if (num2 >= num3)
                     {
                         long position = buffer[bufferIndex].reader.BaseStream.Position;
                         buffer[bufferIndex].GetData(num + 2, num3 - 2, out var _);
                         if (Main.dedServ && Netplay.Clients[bufferIndex].PendingTermination)
{
                             Netplay.Clients[bufferIndex].PendingTerminationApproved = true;
                             buffer[bufferIndex].checkBytes = false;
                             break;
                         }
                         buffer[bufferIndex].reader.BaseStream.Position = position + num3;
                         num2 -= num3;
                         num += num3;
                         continue;
                     }
                     break;
                 }
             }
             catch (Exception)
             {
                 if (Main.dedServ && num < buffer.Length - 100)
                 {
                     Console.WriteLine(Language.GetTextValue("Error.NetMessageError", buffer[num + 2]));
                 }
                 num2 = 0;
                 num = 0;
             }
             if (num2 != buffer[bufferIndex].totalData)
             {
                 for (int i = 0; i < num2; i++)
                 {
                     buffer[bufferIndex].readBuffer[i] = buffer[bufferIndex].readBuffer[i + num];
                 }
                 buffer[bufferIndex].totalData = num2;
             }
             buffer[bufferIndex].checkBytes = false;
         }
     }
References buffer, MessageBuffer.checkBytes, Netplay.Clients, Main.dedServ, MessageBuffer.GetData(), Language.GetTextValue(), RemoteClient.PendingTermination, RemoteClient.PendingTerminationApproved, MessageBuffer.readBuffer, MessageBuffer.reader, and MessageBuffer.totalData.
Referenced by Netplay.InnerClientLoop(), Netplay.UpdateClientInMainThread(), and Netplay.UpdateServerInMainThread().