Terraria: NetMessage.CompressTileBlock_Inner
CompressTileBlock_Inner()
static void NetMessage.CompressTileBlock_Inner (BinaryWriter writer, int xStart, int yStart, int width, int height) inline static
     {
         short num = 0;
         short num2 = 0;
         short num3 = 0;
         short num4 = 0;
         int num5 = 0;
         int num6 = 0;
         byte b = 0;
         byte[] array = new byte[16];
         Tile tile = null;
         for (int i = yStart; i < yStart + height; i++)
         {
             for (int j = xStart; j < xStart + width; j++)
             {
                 Tile tile2 = Main.tile[j, i];
                 if (tile2.isTheSameAs(tile) && TileID.Sets.AllowsSaveCompressionBatching[tile2.type])
                 {
                     num4++;
                     continue;
                 }
                 if (tile != null)
                 {
                     if (num4 > 0)
                     {
                         array[num5] = (byte)((uint)num4 & 0xFFu);
                         num5++;
                         if (num4 > 255)
{
                             b = (byte)(b | 0x80u);
                             array[num5] = (byte)((num4 & 0xFF00) >> 8);
                             num5++;
                         }
                         else
{
                             b = (byte)(b | 0x40u);
                         }
                     }
                     array[num6] = b;
                     writer.Write(array, num6, num5 - num6);
                     num4 = 0;
                 }
                 num5 = 4;
                 byte b3;
                 byte b2;
                 byte b4;
                 b = (b4 = (b3 = (b2 = 0)));
                 if (tile2.active())
                 {
                     b = (byte)(b | 2u);
                     array[num5] = (byte)tile2.type;
                     num5++;
                     if (tile2.type > 255)
                     {
                         array[num5] = (byte)(tile2.type >> 8);
                         num5++;
                         b = (byte)(b | 0x20u);
                     }
                     if (TileID.Sets.BasicChest[tile2.type] && tile2.frameX % 36 == 0 && tile2.frameY % 36 == 0)
                     {
                         short num7 = (short)Chest.FindChest(j, i);
                         if (num7 != -1)
{
                             _compressChestList[num] = num7;
                             num++;
                         }
                     }
                     if (tile2.type == 88 && tile2.frameX % 54 == 0 && tile2.frameY % 36 == 0)
                     {
                         short num8 = (short)Chest.FindChest(j, i);
                         if (num8 != -1)
{
                             _compressChestList[num] = num8;
                             num++;
                         }
                     }
                     if (tile2.type == 85 && tile2.frameX % 36 == 0 && tile2.frameY % 36 == 0)
                     {
                         short num9 = (short)Sign.ReadSign(j, i);
                         if (num9 != -1)
{
                             _compressSignList[num2++] = num9;
                         }
                     }
                     if (tile2.type == 55 && tile2.frameX % 36 == 0 && tile2.frameY % 36 == 0)
                     {
                         short num10 = (short)Sign.ReadSign(j, i);
                         if (num10 != -1)
{
                             _compressSignList[num2++] = num10;
                         }
                     }
                     if (tile2.type == 425 && tile2.frameX % 36 == 0 && tile2.frameY % 36 == 0)
                     {
                         short num11 = (short)Sign.ReadSign(j, i);
                         if (num11 != -1)
{
                             _compressSignList[num2++] = num11;
                         }
                     }
                     if (tile2.type == 573 && tile2.frameX % 36 == 0 && tile2.frameY % 36 == 0)
                     {
                         short num12 = (short)Sign.ReadSign(j, i);
                         if (num12 != -1)
{
                             _compressSignList[num2++] = num12;
                         }
                     }
                     if (tile2.type == 378 && tile2.frameX % 36 == 0 && tile2.frameY == 0)
                     {
                         int num13 = TETrainingDummy.Find(j, i);
                         if (num13 != -1)
{
                             _compressEntities[num3++] = (short)num13;
                         }
                     }
                     if (tile2.type == 395 && tile2.frameX % 36 == 0 && tile2.frameY == 0)
                     {
                         int num14 = TEItemFrame.Find(j, i);
                         if (num14 != -1)
{
                             _compressEntities[num3++] = (short)num14;
                         }
                     }
                     if (tile2.type == 520 && tile2.frameX % 18 == 0 && tile2.frameY == 0)
                     {
                         int num15 = TEFoodPlatter.Find(j, i);
                         if (num15 != -1)
{
                             _compressEntities[num3++] = (short)num15;
                         }
                     }
                     if (tile2.type == 471 && tile2.frameX % 54 == 0 && tile2.frameY == 0)
                     {
                         int num16 = TEWeaponsRack.Find(j, i);
                         if (num16 != -1)
{
                             _compressEntities[num3++] = (short)num16;
                         }
                     }
                     if (tile2.type == 470 && tile2.frameX % 36 == 0 && tile2.frameY == 0)
                     {
                         int num17 = TEDisplayDoll.Find(j, i);
                         if (num17 != -1)
{
                             _compressEntities[num3++] = (short)num17;
                         }
                     }
                     if (tile2.type == 475 && tile2.frameX % 54 == 0 && tile2.frameY == 0)
                     {
                         int num18 = TEHatRack.Find(j, i);
                         if (num18 != -1)
{
                             _compressEntities[num3++] = (short)num18;
                         }
                     }
                     if (tile2.type == 597 && tile2.frameX % 54 == 0 && tile2.frameY % 72 == 0)
                     {
                         int num19 = TETeleportationPylon.Find(j, i);
                         if (num19 != -1)
{
                             _compressEntities[num3++] = (short)num19;
                         }
                     }
                     if (Main.tileFrameImportant[tile2.type])
                     {
                         array[num5] = (byte)((uint)tile2.frameX & 0xFFu);
                         num5++;
                         array[num5] = (byte)((tile2.frameX & 0xFF00) >> 8);
                         num5++;
                         array[num5] = (byte)((uint)tile2.frameY & 0xFFu);
                         num5++;
                         array[num5] = (byte)((tile2.frameY & 0xFF00) >> 8);
                         num5++;
                     }
                     if (tile2.color() != 0)
                     {
                         b3 = (byte)(b3 | 8u);
                         array[num5] = tile2.color();
                         num5++;
                     }
                 }
                 if (tile2.wall != 0)
                 {
                     b = (byte)(b | 4u);
                     array[num5] = (byte)tile2.wall;
                     num5++;
                     if (tile2.wallColor() != 0)
                     {
                         b3 = (byte)(b3 | 0x10u);
                         array[num5] = tile2.wallColor();
                         num5++;
                     }
                 }
                 if (tile2.liquid != 0)
                 {
                     if (!tile2.shimmer())
                     {
                         b = (tile2.lava() ? ((byte)(b | 0x10u)) : ((!tile2.honey()) ? ((byte)(b | 8u)) : ((byte)(b | 0x18u))));
                     }
                     else
                     {
                         b3 = (byte)(b3 | 0x80u);
                         b = (byte)(b | 8u);
                     }
                     array[num5] = tile2.liquid;
                     num5++;
                 }
                 if (tile2.wire())
                 {
                     b4 = (byte)(b4 | 2u);
                 }
                 if (tile2.wire2())
                 {
                     b4 = (byte)(b4 | 4u);
                 }
                 if (tile2.wire3())
                 {
                     b4 = (byte)(b4 | 8u);
                 }
                 int num20 = (tile2.halfBrick() ? 16 : ((tile2.slope() != 0) ? (tile2.slope() + 1 << 4) : 0));
                 b4 |= (byte)num20;
                 if (tile2.actuator())
                 {
                     b3 = (byte)(b3 | 2u);
                 }
                 if (tile2.inActive())
                 {
                     b3 = (byte)(b3 | 4u);
                 }
                 if (tile2.wire4())
                 {
                     b3 = (byte)(b3 | 0x20u);
                 }
                 if (tile2.wall > 255)
                 {
                     array[num5] = (byte)(tile2.wall >> 8);
                     num5++;
                     b3 = (byte)(b3 | 0x40u);
                 }
                 if (tile2.invisibleBlock())
                 {
                     b2 = (byte)(b2 | 2u);
                 }
                 if (tile2.invisibleWall())
                 {
                     b2 = (byte)(b2 | 4u);
                 }
                 if (tile2.fullbrightBlock())
                 {
                     b2 = (byte)(b2 | 8u);
                 }
                 if (tile2.fullbrightWall())
                 {
                     b2 = (byte)(b2 | 0x10u);
                 }
                 num6 = 3;
                 if (b2 != 0)
                 {
                     b3 = (byte)(b3 | 1u);
                     array[num6] = b2;
                     num6--;
                 }
                 if (b3 != 0)
                 {
                     b4 = (byte)(b4 | 1u);
                     array[num6] = b3;
                     num6--;
                 }
                 if (b4 != 0)
                 {
                     b = (byte)(b | 1u);
                     array[num6] = b4;
                     num6--;
                 }
                 tile = tile2;
             }
         }
         if (num4 > 0)
         {
             array[num5] = (byte)((uint)num4 & 0xFFu);
             num5++;
             if (num4 > 255)
             {
                 b = (byte)(b | 0x80u);
                 array[num5] = (byte)((num4 & 0xFF00) >> 8);
                 num5++;
             }
             else
             {
                 b = (byte)(b | 0x40u);
             }
         }
         array[num6] = b;
         writer.Write(array, num6, num5 - num6);
         writer.Write(num);
         for (int k = 0; k < num; k++)
         {
             Chest chest = Main.chest[_compressChestList[k]];
             writer.Write(_compressChestList[k]);
             writer.Write((short)chest.x);
             writer.Write((short)chest.y);
             writer.Write(chest.name);
         }
         writer.Write(num2);
         for (int l = 0; l < num2; l++)
         {
             Sign sign = Main.sign[_compressSignList[l]];
             writer.Write(_compressSignList[l]);
             writer.Write((short)sign.x);
             writer.Write((short)sign.y);
             writer.Write(sign.text);
         }
         writer.Write(num3);
         for (int m = 0; m < num3; m++)
         {
             TileEntity.Write(writer, TileEntity.ByID[_compressEntities[m]]);
         }
     }
References _compressChestList, _compressEntities, _compressSignList, Tile.active(), Tile.actuator(), TileID.Sets.AllowsSaveCompressionBatching, TileID.Sets.BasicChest, TileEntity.ByID, Main.chest, Tile.color(), TEDisplayDoll.Find(), TEFoodPlatter.Find(), TEHatRack.Find(), TEItemFrame.Find(), TETeleportationPylon.Find(), TETrainingDummy.Find(), TEWeaponsRack.Find(), Chest.FindChest(), Tile.frameX, Tile.frameY, Tile.fullbrightBlock(), Tile.fullbrightWall(), Tile.halfBrick(), Tile.honey(), Tile.inActive(), Tile.invisibleBlock(), Tile.invisibleWall(), Tile.isTheSameAs(), Tile.lava(), Tile.liquid, Chest.name, Sign.ReadSign(), Tile.shimmer(), Main.sign, Tile.slope(), Sign.text, Main.tile, Main.tileFrameImportant, Tile.type, Tile.wall, Tile.wallColor(), Tile.wire(), Tile.wire2(), Tile.wire3(), Tile.wire4(), TileEntity.Write(), Chest.x, Sign.x, Chest.y, and Sign.y.
Referenced by CompressTileBlock().