Terraria: NetMessage.greetPlayer
greetPlayer()
static void NetMessage.greetPlayer (int plr) inline static
     {
         if (Main.motd == "")
         {
             ChatHelper.SendChatMessageToClient(NetworkText.FromFormattable("{0} {1}!", Lang.mp[18].ToNetworkText(), Main.worldName), new Color(255, 240, 20), plr);
         }
         else
         {
             ChatHelper.SendChatMessageToClient(NetworkText.FromLiteral(Main.motd), new Color(255, 240, 20), plr);
         }
         string text = "";
         for (int i = 0; i < 255; i++)
         {
             if (Main.player[i].active)
             {
                 text = ((!(text == "")) ? (text + ", " + Main.player[i].name) : (text + Main.player[i].name));
             }
         }
         ChatHelper.SendChatMessageToClient(NetworkText.FromKey("Game.JoinGreeting", text), new Color(255, 240, 20), plr);
     }
References Entity.active, Color, NetworkText.FromFormattable(), NetworkText.FromKey(), NetworkText.FromLiteral(), Main.motd, Lang.mp, Player.name, Main.player, ChatHelper.SendChatMessageToClient(), LocalizedText.ToNetworkText(), and Main.worldName.
Referenced by MessageBuffer.GetData().