Terraria: NetMessage.SendAnglerQuest
SendAnglerQuest()
static void NetMessage.SendAnglerQuest (int remoteClient) inline static
     {
         if (Main.netMode != 2)
         {
             return;
         }
         if (remoteClient == -1)
         {
             for (int i = 0; i < 255; i++)
             {
                 if (Netplay.Clients[i].State == 10)
                 {
                     SendData(74, i, -1, NetworkText.FromLiteral(Main.player[i].name), Main.anglerQuest);
                 }
             }
         }
         else if (Netplay.Clients[remoteClient].State == 10)
         {
             SendData(74, remoteClient, -1, NetworkText.FromLiteral(Main.player[remoteClient].name), Main.anglerQuest);
         }
     }
References Main.anglerQuest, Netplay.Clients, NetworkText.FromLiteral(), Player.name, Main.netMode, Main.player, SendData(), and RemoteClient.State.
Referenced by Main.AnglerQuestSwap(), and SyncConnectedPlayer().