Terraria: NetMessage.SyncConnectedPlayer
SyncConnectedPlayer()
static void NetMessage.SyncConnectedPlayer (int plr) inline static
     {
         SyncOnePlayer(plr, -1, plr);
         for (int i = 0; i < 255; i++)
         {
             if (plr != i && Main.player[i].active)
             {
                 SyncOnePlayer(i, plr, -1);
             }
         }
         SendNPCHousesAndTravelShop(plr);
         SendAnglerQuest(plr);
         CreditsRollEvent.SendCreditsRollRemainingTimeToPlayer(plr);
         NPC.RevengeManager.SendAllMarkersToPlayer(plr);
         EnsureLocalPlayerIsPresent();
     }
References Entity.active, EnsureLocalPlayerIsPresent(), Main.player, NPC.RevengeManager, CoinLossRevengeSystem.SendAllMarkersToPlayer(), SendAnglerQuest(), CreditsRollEvent.SendCreditsRollRemainingTimeToPlayer(), SendNPCHousesAndTravelShop(), and SyncOnePlayer().
Referenced by MessageBuffer.GetData().