Terraria: System.Data.LikeNode.Eval
Eval() [2/3]
override object System.Data.LikeNode.Eval (DataRow row, DataRowVersion version) inline package
Definition at line 21 of file LikeNode.cs.
    {
        object obj = _left.Eval(row, version);
        if (obj == DBNull.Value || (_left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)))
        {
            return DBNull.Value;
        }
        string text;
        if (_pattern == null)
        {
            object obj2 = _right.Eval(row, version);
            if (!(obj2 is string) && !(obj2 is SqlString))
            {
                SetTypeMismatchError(_op, obj.GetType(), obj2.GetType());
            }
            if (obj2 == DBNull.Value || DataStorage.IsObjectSqlNull(obj2))
            {
                return DBNull.Value;
            }
            string pat = (string)SqlConvert.ChangeType2(obj2, StorageType.String, typeof(string), base.FormatProvider);
            text = AnalyzePattern(pat);
            if (_right.IsConstant())
            {
                _pattern = text;
            }
        }
        else
        {
            text = _pattern;
        }
        if (!(obj is string) && !(obj is SqlString))
        {
            SetTypeMismatchError(_op, obj.GetType(), typeof(string));
        }
        string text2 = ((obj is SqlString sqlString) ? sqlString.Value : ((string)obj));
        string s = text2.TrimEnd(s_trimChars);
        switch (_kind)
        {
        case 5:
            return true;
        case 4:
            return base.table.Compare(s, text) == 0;
        case 3:
            return 0 <= base.table.IndexOf(s, text);
        case 1:
            return base.table.IndexOf(s, text) == 0;
        case 2:
        {
            string s2 = text.TrimEnd(s_trimChars);
            return base.table.IsSuffix(s, s2);
        }
        default:
            return DBNull.Value;
        }
    }
References System.Data.LikeNode._kind, System.Data.BinaryNode._left, System.Data.BinaryNode._op, System.Data.LikeNode._pattern, System.Data.BinaryNode._right, System.Data.LikeNode.AnalyzePattern(), System.Data.Common.SqlConvert.ChangeType2(), System.Data.ExpressionNode.Eval(), System.Data.ExpressionNode.IsConstant(), System.Data.Common.DataStorage.IsObjectSqlNull(), System.Data.ExpressionNode.IsSqlColumn, System.obj, System.s, System.Data.LikeNode.s_trimChars, System.Data.BinaryNode.SetTypeMismatchError(), System.text, and System.DBNull.Value.