Terraria: System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync
GetHttp2ConnectionAsync()
async ValueTask< Http2Connection > System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync (HttpRequestMessage request, bool async, CancellationToken cancellationToken) inline private
Definition at line 591 of file HttpConnectionPool.cs.
    {
        TaskCompletionSourceWithCancellation<Http2Connection> taskCompletionSourceWithCancellation;
        while (true)
        {
            Http2Connection http2Connection;
            lock (SyncObj)
            {
                _usedSinceLastCleanup = true;
                if (!_http2Enabled)
                {
                    return null;
                }
                int num = _availableHttp2Connections?.Count ?? 0;
                if (num > 0)
                {
                    http2Connection = _availableHttp2Connections[num - 1];
                    goto IL_0099;
                }
                taskCompletionSourceWithCancellation = _http2RequestQueue.EnqueueRequest(request);
                CheckForHttp2ConnectionInjection();
            }
            break;
            IL_0099:
            if (CheckExpirationOnGet(http2Connection))
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    http2Connection.Trace("Found expired HTTP/2 connection in pool.", "GetHttp2ConnectionAsync");
                }
                InvalidateHttp2Connection(http2Connection);
                continue;
            }
            if (!http2Connection.TryReserveStream())
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    http2Connection.Trace("Found HTTP/2 connection in pool without available streams.", "GetHttp2ConnectionAsync");
                }
                bool flag = false;
                lock (SyncObj)
                {
                    int num2 = _availableHttp2Connections.IndexOf(http2Connection);
                    if (num2 != -1)
                    {
                        flag = true;
                        _availableHttp2Connections.RemoveAt(num2);
                    }
                }
                if (flag)
                {
                    DisableHttp2Connection(http2Connection);
                }
                continue;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                http2Connection.Trace("Found usable HTTP/2 connection in pool.", "GetHttp2ConnectionAsync");
            }
            return http2Connection;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("No available HTTP/2 connections; request queued.", "GetHttp2ConnectionAsync");
        }
        Microsoft.Extensions.Internal.ValueStopwatch stopwatch = Microsoft.Extensions.Internal.ValueStopwatch.StartNew();
        try
        {
            return await taskCompletionSourceWithCancellation.WaitWithCancellationAsync(async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            if (HttpTelemetry.Log.IsEnabled())
            {
                HttpTelemetry.Log.Http20RequestLeftQueue(stopwatch.GetElapsedTime().TotalMilliseconds);
            }
        }
    }
References System.Net.Http.HttpConnectionPool._availableHttp2Connections, System.Net.Http.HttpConnectionPool._http2Enabled, System.Net.Http.HttpConnectionPool._http2RequestQueue, System.Net.Http.HttpConnectionPool._usedSinceLastCleanup, System.cancellationToken, System.Net.Http.HttpConnectionPool.CheckExpirationOnGet(), System.Net.Http.HttpConnectionPool.CheckForHttp2ConnectionInjection(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Http.HttpConnectionPool.DisableHttp2Connection(), System.Net.Http.HttpConnectionPool.InvalidateHttp2Connection(), System.Net.Http.HttpTelemetry.Log, System.Net.NetEventSource.Log, Microsoft.Extensions.Internal.ValueStopwatch.StartNew(), System.Net.Http.HttpConnectionPool.SyncObj, and System.Net.Http.HttpConnectionPool.Trace().
Referenced by System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync().