Terraria: System.Net.Http.HttpConnectionPool.SendWithProxyAuthAsync
SendWithProxyAuthAsync()
ValueTask< HttpResponseMessage > System.Net.Http.HttpConnectionPool.SendWithProxyAuthAsync (HttpRequestMessage request, bool async, bool doRequestAuth, CancellationToken cancellationToken) inline
Definition at line 1059 of file HttpConnectionPool.cs.
    {
        if (DoProxyAuth && ProxyCredentials != null)
        {
            return AuthenticationHelper.SendWithProxyAuthAsync(request, _proxyUri, async, ProxyCredentials, doRequestAuth, this, cancellationToken);
        }
        return SendWithVersionDetectionAndRetryAsync(request, async, doRequestAuth, cancellationToken);
    }
References System.Net.Http.HttpConnectionPool._proxyUri, System.cancellationToken, System.Net.Http.HttpConnectionPool.DoProxyAuth, System.Net.Http.HttpConnectionPool.ProxyCredentials, System.Net.Http.AuthenticationHelper.SendWithProxyAuthAsync(), and System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync().
Referenced by System.Net.Http.HttpConnectionPool.SendAsync().