Terraria: System.Net.Http.HttpConnectionPool.HandleHttp11Downgrade
HandleHttp11Downgrade()
async Task System.Net.Http.HttpConnectionPool.HandleHttp11Downgrade (HttpRequestMessage request, Socket socket, Stream stream, TransportContext transportContext, CancellationToken cancellationToken) inline private
Definition at line 475 of file HttpConnectionPool.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("Server does not support HTTP2; disabling HTTP2 use and proceeding with HTTP/1.1 connection", "HandleHttp11Downgrade");
        }
        bool flag = true;
        lock (SyncObj)
        {
            _http2Enabled = false;
            _associatedHttp2ConnectionCount--;
            _pendingHttp2Connection = false;
            while (_http2RequestQueue.TryDequeueNextRequest(null))
            {
            }
            if (_associatedHttp11ConnectionCount < _maxHttp11Connections)
            {
                _associatedHttp11ConnectionCount++;
                _pendingHttp11ConnectionCount++;
            }
            else
            {
                flag = false;
            }
        }
        if (!flag)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace("Discarding downgraded HTTP/1.1 connection because HTTP/1.1 connection limit is exceeded", "HandleHttp11Downgrade");
            }
            stream.Dispose();
        }
        HttpConnection connection;
        try
        {
            connection = await ConstructHttp11ConnectionAsync(async: true, socket, stream, transportContext, request, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (OperationCanceledException ex) when (ex.CancellationToken == cancellationToken)
        {
            HandleHttp11ConnectionFailure(CreateConnectTimeoutException(ex));
            return;
        }
        catch (Exception e)
        {
            HandleHttp11ConnectionFailure(e);
            return;
        }
        ReturnHttp11Connection(connection, isNewConnection: true);
    }
References System.Net.Http.HttpConnectionPool._associatedHttp11ConnectionCount, System.Net.Http.HttpConnectionPool._associatedHttp2ConnectionCount, System.Net.Http.HttpConnectionPool._http2Enabled, System.Net.Http.HttpConnectionPool._http2RequestQueue, System.Net.Http.HttpConnectionPool._maxHttp11Connections, System.Net.Http.HttpConnectionPool._pendingHttp11ConnectionCount, System.Net.Http.HttpConnectionPool._pendingHttp2Connection, System.cancellationToken, System.Net.Http.HttpConnectionPool.ConstructHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.CreateConnectTimeoutException(), System.Net.Http.HttpConnectionPool.HandleHttp11ConnectionFailure(), System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionPool.ReturnHttp11Connection(), System.stream, System.Net.Http.HttpConnectionPool.SyncObj, and System.Net.Http.HttpConnectionPool.Trace().
Referenced by System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync().