Terraria: System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync
AddHttp2ConnectionAsync()
async Task System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync (HttpRequestMessage request) inline private
Definition at line 526 of file HttpConnectionPool.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("Creating new HTTP/2 connection for pool.", "AddHttp2ConnectionAsync");
        }
        Http2Connection connection;
        using (CancellationTokenSource cts = GetConnectTimeoutCancellationTokenSource())
        {
            _ = 3;
            try
            {
                var (socket, stream, transportContext) = await ConnectAsync(request, async: true, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
                if (IsSecure)
                {
                    SslStream sslStream = (SslStream)stream;
                    if (!(sslStream.NegotiatedApplicationProtocol == SslApplicationProtocol.Http2))
                    {
                        await HandleHttp11Downgrade(request, socket, stream, transportContext, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
                        return;
                    }
                    if (sslStream.SslProtocol < SslProtocols.Tls12)
                    {
                        stream.Dispose();
                        throw new HttpRequestException(System.SR.Format(System.SR.net_ssl_http2_requires_tls12, sslStream.SslProtocol));
                    }
                    connection = await ConstructHttp2ConnectionAsync(stream, request, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
                }
                else
                {
                    connection = await ConstructHttp2ConnectionAsync(stream, request, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            catch (OperationCanceledException ex) when (ex.CancellationToken == cts.Token)
            {
                HandleHttp2ConnectionFailure(CreateConnectTimeoutException(ex));
                return;
            }
            catch (Exception e)
            {
                HandleHttp2ConnectionFailure(e);
                return;
            }
        }
        ValueTask valueTask = connection.WaitForShutdownAsync();
        ReturnHttp2Connection(connection, isNewConnection: true);
        await valueTask.ConfigureAwait(continueOnCapturedContext: false);
        InvalidateHttp2Connection(connection);
    }
References System.Net.Http.HttpConnectionPool.ConnectAsync(), System.Net.Http.HttpConnectionPool.ConstructHttp2ConnectionAsync(), System.Net.Http.HttpConnectionPool.CreateConnectTimeoutException(), System.SR.Format(), System.Net.Http.HttpConnectionPool.GetConnectTimeoutCancellationTokenSource(), System.Net.Http.HttpConnectionPool.HandleHttp11Downgrade(), System.Net.Http.HttpConnectionPool.HandleHttp2ConnectionFailure(), System.Net.Security.SslApplicationProtocol.Http2, System.Net.Http.HttpConnectionPool.InvalidateHttp2Connection(), System.Net.Http.HttpConnectionPool.IsSecure, System.Net.NetEventSource.Log, System.SR.net_ssl_http2_requires_tls12, System.Net.Http.HttpConnectionPool.ReturnHttp2Connection(), System.stream, System.Net.Http.HttpConnectionPool.Trace(), and System.Net.Http.Http2Connection.WaitForShutdownAsync().
Referenced by System.Net.Http.HttpConnectionPool.CheckForHttp2ConnectionInjection().