Terraria: System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync
CreateHttp11ConnectionAsync()
async ValueTask< HttpConnection > System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync (HttpRequestMessage request, bool async, CancellationToken cancellationToken) inline package
Definition at line 1167 of file HttpConnectionPool.cs.
    {
        var (socket, stream, transportContext) = await ConnectAsync(request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        return await ConstructHttp11ConnectionAsync(async, socket, stream, transportContext, request, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
    }
References System.cancellationToken, System.Net.Http.HttpConnectionPool.ConnectAsync(), System.Net.Http.HttpConnectionPool.ConstructHttp11ConnectionAsync(), and System.stream.
Referenced by System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync().