Terraria: System.Net.Http.HttpConnectionPool.InvalidateHttp3Connection
InvalidateHttp3Connection()
void System.Net.Http.HttpConnectionPool.InvalidateHttp3Connection (Http3Connection connection) inline
Definition at line 1531 of file HttpConnectionPool.cs.
    {
        lock (SyncObj)
        {
            if (_http3Connection == connection)
            {
                _http3Connection = null;
            }
        }
    }
References System.Net.Http.HttpConnectionPool._http3Connection, and System.Net.Http.HttpConnectionPool.SyncObj.
Referenced by System.Net.Http.Http3Connection.Abort(), System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(), and System.Net.Http.Http3Connection.OnServerGoAway().