Terraria: System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async
TrySendUsingHttp3Async()
async ValueTask< HttpResponseMessage > System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async (HttpRequestMessage request, bool async, CancellationToken cancellationToken) inline private
Definition at line 745 of file HttpConnectionPool.cs.
    {
        HttpResponseMessage httpResponseMessage;
        while (true)
        {
            HttpAuthority httpAuthority = _http3Authority;
            if (request.Version.Major >= 3 && request.VersionPolicy != 0 && httpAuthority == null)
            {
                httpAuthority = _originAuthority;
            }
            if (httpAuthority == null)
            {
                return null;
            }
            if (IsAltSvcBlocked(httpAuthority))
            {
                ThrowGetVersionException(request, 3);
            }
            Http3Connection connection = await GetHttp3ConnectionAsync(request, httpAuthority, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            httpResponseMessage = await connection.SendAsync(request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            if (httpResponseMessage.StatusCode != HttpStatusCode.MisdirectedRequest || connection.Authority == _originAuthority)
            {
                break;
            }
            httpResponseMessage.Dispose();
            BlocklistAuthority(connection.Authority);
        }
        return httpResponseMessage;
    }
References System.Net.Http.HttpConnectionPool._http3Authority, System.Net.Http.HttpConnectionPool._originAuthority, System.Net.Http.Http3Connection.Authority, System.Net.Http.HttpConnectionPool.BlocklistAuthority(), System.cancellationToken, System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(), System.Net.Http.HttpConnectionPool.IsAltSvcBlocked(), System.Net.Http.Http3Connection.SendAsync(), and System.Net.Http.HttpConnectionPool.ThrowGetVersionException().
Referenced by System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync().