Terraria: System.Net.Http.HttpConnectionPool.Trace
Trace()
void System.Net.Http.HttpConnectionPool.Trace (string message, [CallerMemberName] string memberName = null) inline private
Definition at line 1718 of file HttpConnectionPool.cs.
    {
        System.Net.NetEventSource.Log.HandlerMessage(GetHashCode(), 0, 0, memberName, message);
    }
References System.Net.NetEventSource.Log.
Referenced by System.Net.Http.HttpConnectionPool.HttpConnectionPool(), System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(), System.Net.Http.HttpConnectionPool.ApplyPlaintextFilterAsync(), System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(), System.Net.Http.HttpConnectionPool.Dispose(), System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(), System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(), System.Net.Http.HttpConnectionPool.HandleHttp11ConnectionFailure(), System.Net.Http.HttpConnectionPool.HandleHttp11Downgrade(), System.Net.Http.HttpConnectionPool.HandleHttp2ConnectionFailure(), and System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync().