Terraria: System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync
EstablishProxyTunnelAsync()
async ValueTask< Stream > System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync (bool async, HttpRequestHeaders headers, CancellationToken cancellationToken) inline private
Definition at line 1248 of file HttpConnectionPool.cs.
    {
        HttpRequestMessage httpRequestMessage = new HttpRequestMessage(HttpMethod.Connect, _proxyUri);
        httpRequestMessage.Headers.Host = $"{_originAuthority.IdnHost}:{_originAuthority.Port}";
        if (headers != null && headers.TryGetValues("User-Agent", out IEnumerable<string> values))
        {
            httpRequestMessage.Headers.TryAddWithoutValidation("User-Agent", values);
        }
        HttpResponseMessage httpResponseMessage = await _poolManager.SendProxyConnectAsync(httpRequestMessage, _proxyUri, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        if (httpResponseMessage.StatusCode != HttpStatusCode.OK)
        {
            httpResponseMessage.Dispose();
            throw new HttpRequestException(System.SR.Format(System.SR.net_http_proxy_tunnel_returned_failure_status_code, _proxyUri, (int)httpResponseMessage.StatusCode));
        }
        try
        {
            return httpResponseMessage.Content.ReadAsStream(cancellationToken);
        }
        catch
        {
            httpResponseMessage.Dispose();
            throw;
        }
    }
References System.Net.Http.HttpConnectionPool._poolManager, System.Net.Http.HttpConnectionPool._proxyUri, System.cancellationToken, System.Net.Http.HttpMethod.Connect, System.SR.Format(), System.SR.net_http_proxy_tunnel_returned_failure_status_code, System.Net.Http.HttpConnectionPoolManager.SendProxyConnectAsync(), and System.values.
Referenced by System.Net.Http.HttpConnectionPool.ConnectAsync().