Terraria: System.Net.Http.HttpConnectionPool.CheckForHttp2ConnectionInjection
CheckForHttp2ConnectionInjection()
void System.Net.Http.HttpConnectionPool.CheckForHttp2ConnectionInjection () inline private
Definition at line 576 of file HttpConnectionPool.cs.
    {
        if (!_http2RequestQueue.TryPeekNextRequest(out var request))
        {
            return;
        }
        List<Http2Connection> availableHttp2Connections = _availableHttp2Connections;
        if ((availableHttp2Connections == null || availableHttp2Connections.Count == 0) && !_pendingHttp2Connection && (_associatedHttp2ConnectionCount == 0 || EnableMultipleHttp2Connections))
        {
            _associatedHttp2ConnectionCount++;
            _pendingHttp2Connection = true;
            Task.Run(() => AddHttp2ConnectionAsync(request));
        }
    }
References System.Net.Http.HttpConnectionPool._associatedHttp2ConnectionCount, System.Net.Http.HttpConnectionPool._availableHttp2Connections, System.Net.Http.HttpConnectionPool._http2RequestQueue, System.Net.Http.HttpConnectionPool._pendingHttp2Connection, System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Http.HttpConnectionPool.EnableMultipleHttp2Connections, and System.Threading.Tasks.Task< TResult >.Run().
Referenced by System.Net.Http.HttpConnectionPool.DisableHttp2Connection(), System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(), System.Net.Http.HttpConnectionPool.HandleHttp2ConnectionFailure(), System.Net.Http.HttpConnectionPool.InvalidateHttp2Connection(), and System.Net.Http.HttpConnectionPool.ReturnHttp2Connection().