Terraria: System.Net.Http.HttpConnectionPool.Dispose
Dispose()
void System.Net.Http.HttpConnectionPool.Dispose () inline
Implements System.IDisposable.
Definition at line 1542 of file HttpConnectionPool.cs.
    {
        List<HttpConnectionBase> list = null;
        lock (SyncObj)
        {
            if (!_disposed)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace("Disposing pool.", "Dispose");
                }
                _disposed = true;
                list = new List<HttpConnectionBase>(_availableHttp11Connections.Count + (_availableHttp2Connections?.Count ?? 0));
                list.AddRange(_availableHttp11Connections);
                if (_availableHttp2Connections != null)
                {
                    list.AddRange(_availableHttp2Connections);
                }
                _availableHttp11Connections.Clear();
                _associatedHttp2ConnectionCount -= _availableHttp2Connections?.Count ?? 0;
                _availableHttp2Connections?.Clear();
                if (_http3Connection != null)
                {
                    list.Add(_http3Connection);
                    _http3Connection = null;
                }
                if (_authorityExpireTimer != null)
                {
                    _authorityExpireTimer.Dispose();
                    _authorityExpireTimer = null;
                }
                if (_altSvcBlocklistTimerCancellation != null)
                {
                    _altSvcBlocklistTimerCancellation.Cancel();
                    _altSvcBlocklistTimerCancellation.Dispose();
                    _altSvcBlocklistTimerCancellation = null;
                }
            }
        }
        list?.ForEach(delegate(HttpConnectionBase c)
        {
            c.Dispose();
        });
    }
References System.Net.Http.HttpConnectionPool._altSvcBlocklistTimerCancellation, System.Net.Http.HttpConnectionPool._associatedHttp2ConnectionCount, System.Net.Http.HttpConnectionPool._authorityExpireTimer, System.Net.Http.HttpConnectionPool._availableHttp11Connections, System.Net.Http.HttpConnectionPool._availableHttp2Connections, System.Net.Http.HttpConnectionPool._disposed, System.Net.Http.HttpConnectionPool._http3Connection, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.CancellationTokenSource.Cancel(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Http.HttpConnectionBase.Dispose(), System.Threading.CancellationTokenSource.Dispose(), System.Threading.Timer.Dispose(), System.list, System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionPool.SyncObj, and System.Net.Http.HttpConnectionPool.Trace().