Terraria: System.Net.Http.HttpConnectionPool.ConnectAsync
ConnectAsync()
async ValueTask<(Socket, Stream, TransportContext)> System.Net.Http.HttpConnectionPool.ConnectAsync (HttpRequestMessage request, bool async, CancellationToken cancellationToken) inline private
Definition at line 1082 of file HttpConnectionPool.cs.
    {
        Stream stream = null;
        Socket socket = null;
        switch (_kind)
        {
        case HttpConnectionKind.Http:
        case HttpConnectionKind.Https:
        case HttpConnectionKind.ProxyConnect:
            (socket, stream) = await ConnectToTcpHostAsync(_originAuthority.IdnHost, _originAuthority.Port, request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            break;
        case HttpConnectionKind.Proxy:
            (socket, stream) = await ConnectToTcpHostAsync(_proxyUri.IdnHost, _proxyUri.Port, request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            break;
        case HttpConnectionKind.ProxyTunnel:
        case HttpConnectionKind.SslProxyTunnel:
            stream = await EstablishProxyTunnelAsync(async, request.HasHeaders ? request.Headers : null, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            break;
        case HttpConnectionKind.SocksTunnel:
        case HttpConnectionKind.SslSocksTunnel:
            (socket, stream) = await EstablishSocksTunnel(request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            break;
        }
        if (socket == null && stream is NetworkStream networkStream)
        {
            socket = networkStream.Socket;
        }
        TransportContext item = null;
        if (IsSecure)
        {
            SslStream sslStream = await ConnectHelper.EstablishSslConnectionAsync(GetSslOptionsForRequest(request), request, async, stream, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            item = sslStream.TransportContext;
            stream = sslStream;
        }
        return (socket, stream, item);
    }
References System.Net.Http.HttpConnectionPool._kind, System.Net.Http.HttpConnectionPool._originAuthority, System.Net.Http.HttpConnectionPool._proxyUri, System.cancellationToken, System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(), System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(), System.Net.Http.HttpConnectionPool.EstablishSocksTunnel(), System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(), System.Net.Http.HttpConnectionPool.GetSslOptionsForRequest(), System.Net.Http.HttpAuthority.IdnHost, System.Uri.IdnHost, System.Net.Http.HttpConnectionPool.IsSecure, System.item, System.Net.Http.HttpAuthority.Port, System.Uri.Port, and System.stream.
Referenced by System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(), and System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync().