Terraria: System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync
GetHttp11ConnectionAsync()
async ValueTask< HttpConnection > System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync (HttpRequestMessage request, bool async, CancellationToken cancellationToken) inline private
Definition at line 412 of file HttpConnectionPool.cs.
    {
        TaskCompletionSourceWithCancellation<HttpConnection> taskCompletionSourceWithCancellation;
        while (true)
        {
            HttpConnection httpConnection = null;
            lock (SyncObj)
            {
                _usedSinceLastCleanup = true;
                int count = _availableHttp11Connections.Count;
                if (count > 0)
                {
                    httpConnection = _availableHttp11Connections[count - 1];
                    _availableHttp11Connections.RemoveAt(count - 1);
                    goto IL_0095;
                }
                taskCompletionSourceWithCancellation = _http11RequestQueue.EnqueueRequest(request);
                CheckForHttp11ConnectionInjection();
            }
            break;
            IL_0095:
            if (CheckExpirationOnGet(httpConnection))
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    httpConnection.Trace("Found expired HTTP/1.1 connection in pool.", "GetHttp11ConnectionAsync");
                }
                httpConnection.Dispose();
                continue;
            }
            if (!httpConnection.PrepareForReuse(async))
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    httpConnection.Trace("Found invalid HTTP/1.1 connection in pool.", "GetHttp11ConnectionAsync");
                }
                httpConnection.Dispose();
                continue;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                httpConnection.Trace("Found usable HTTP/1.1 connection in pool.", "GetHttp11ConnectionAsync");
            }
            return httpConnection;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("No available HTTP/1.1 connections; request queued.", "GetHttp11ConnectionAsync");
        }
        Microsoft.Extensions.Internal.ValueStopwatch stopwatch = Microsoft.Extensions.Internal.ValueStopwatch.StartNew();
        try
        {
            return await taskCompletionSourceWithCancellation.WaitWithCancellationAsync(async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            if (HttpTelemetry.Log.IsEnabled())
            {
                HttpTelemetry.Log.Http11RequestLeftQueue(stopwatch.GetElapsedTime().TotalMilliseconds);
            }
        }
    }
References System.Net.Http.HttpConnectionPool._availableHttp11Connections, System.Net.Http.HttpConnectionPool._http11RequestQueue, System.Net.Http.HttpConnectionPool._usedSinceLastCleanup, System.cancellationToken, System.Net.Http.HttpConnectionPool.CheckExpirationOnGet(), System.Net.Http.HttpConnectionPool.CheckForHttp11ConnectionInjection(), System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Http.HttpTelemetry.Log, System.Net.NetEventSource.Log, Microsoft.Extensions.Internal.ValueStopwatch.StartNew(), System.Net.Http.HttpConnectionPool.SyncObj, and System.Net.Http.HttpConnectionPool.Trace().
Referenced by System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync().