Terraria: System.Net.Http.HttpConnectionPool.HandleAltSvc
HandleAltSvc()
void System.Net.Http.HttpConnectionPool.HandleAltSvc (IEnumerable< string > altSvcHeaderValues, TimeSpan? responseAge) inline package
Definition at line 868 of file HttpConnectionPool.cs.
    {
        HttpAuthority httpAuthority = null;
        TimeSpan dueTime = default(TimeSpan);
        bool flag = false;
        foreach (string altSvcHeaderValue2 in altSvcHeaderValues)
        {
            int index = 0;
            if (!AltSvcHeaderParser.Parser.TryParseValue(altSvcHeaderValue2, null, ref index, out var parsedValue))
            {
                continue;
            }
            AltSvcHeaderValue altSvcHeaderValue = (AltSvcHeaderValue)parsedValue;
            if (altSvcHeaderValue == AltSvcHeaderValue.Clear)
            {
                ExpireAltSvcAuthority();
                _authorityExpireTimer.Change(-1, -1);
                break;
            }
            if (httpAuthority != null || altSvcHeaderValue == null || !(altSvcHeaderValue.AlpnProtocolName == "h3"))
            {
                continue;
            }
            HttpAuthority httpAuthority2 = new HttpAuthority(altSvcHeaderValue.Host ?? _originAuthority.IdnHost, altSvcHeaderValue.Port);
            if (!IsAltSvcBlocked(httpAuthority2))
            {
                TimeSpan maxAge = altSvcHeaderValue.MaxAge;
                if (responseAge.HasValue)
                {
                    maxAge -= responseAge.GetValueOrDefault();
                }
                if (maxAge > TimeSpan.Zero)
                {
                    httpAuthority = httpAuthority2;
                    dueTime = maxAge;
                    flag = altSvcHeaderValue.Persist;
                }
            }
        }
        if (httpAuthority == null || httpAuthority.Equals(_http3Authority))
        {
            return;
        }
        if (dueTime.Ticks > 25920000000000L)
        {
            dueTime = TimeSpan.FromTicks(25920000000000L);
        }
        lock (SyncObj)
        {
            if (_authorityExpireTimer == null)
            {
                WeakReference<HttpConnectionPool> state = new WeakReference<HttpConnectionPool>(this);
                bool flag2 = false;
                try
                {
                    if (!ExecutionContext.IsFlowSuppressed())
                    {
                        ExecutionContext.SuppressFlow();
                        flag2 = true;
                    }
                    _authorityExpireTimer = new Timer(delegate(object o)
                    {
                        WeakReference<HttpConnectionPool> weakReference = (WeakReference<HttpConnectionPool>)o;
                        if (weakReference.TryGetTarget(out var target))
{
                            target.ExpireAltSvcAuthority();
                        }
                    }, state, dueTime, Timeout.InfiniteTimeSpan);
                }
                finally
                {
                    if (flag2)
                    {
                        ExecutionContext.RestoreFlow();
                    }
                }
            }
            else
            {
                _authorityExpireTimer.Change(dueTime, Timeout.InfiniteTimeSpan);
            }
            _http3Authority = httpAuthority;
            _persistAuthority = flag;
        }
        if (!flag)
        {
            _poolManager.StartMonitoringNetworkChanges();
        }
    }
References System.Net.Http.HttpConnectionPool._authorityExpireTimer, System.Net.Http.HttpConnectionPool._http3Authority, System.Net.Http.HttpConnectionPool._originAuthority, System.Net.Http.HttpConnectionPool._persistAuthority, System.Net.Http.HttpConnectionPool._poolManager, System.Threading.Timer.Change(), System.Net.Http.Headers.AltSvcHeaderValue.Clear, System.Net.Http.HttpConnectionPool.ExpireAltSvcAuthority(), System.TimeSpan.FromTicks(), System.Net.Http.HttpAuthority.IdnHost, System.index, System.Threading.Timeout.InfiniteTimeSpan, System.Net.Http.HttpConnectionPool.IsAltSvcBlocked(), System.Threading.ExecutionContext.IsFlowSuppressed(), System.L, System.Net.Http.Headers.AltSvcHeaderParser.Parser, System.Threading.ExecutionContext.RestoreFlow(), System.Net.Http.HttpConnectionPoolManager.StartMonitoringNetworkChanges(), System.state, System.Threading.ExecutionContext.SuppressFlow(), System.Net.Http.HttpConnectionPool.SyncObj, and System.TimeSpan.Zero.
Referenced by System.Net.Http.HttpConnectionPool.ProcessAltSvc(), and System.Net.Http.Http2Connection.ProcessAltSvcFrame().