Terraria: System.Net.Http.HttpConnectionPool.DisableHttp2Connection
DisableHttp2Connection()
void System.Net.Http.HttpConnectionPool.DisableHttp2Connection (Http2Connection connection) inline private
Definition at line 1498 of file HttpConnectionPool.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            connection.Trace("", "DisableHttp2Connection");
        }
        Task.Run(async delegate
        {
            bool flag = await connection.WaitForAvailableStreamsAsync().ConfigureAwait(continueOnCapturedContext: false);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                connection.Trace($"WaitForAvailableStreamsAsync completed, {"usable"}={flag}", "DisableHttp2Connection");
            }
            if (flag)
            {
                ReturnHttp2Connection(connection, isNewConnection: false);
            }
            else
            {
                lock (SyncObj)
                {
                    _associatedHttp2ConnectionCount--;
                    CheckForHttp2ConnectionInjection();
                }
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    connection.Trace("HTTP2 connection no longer usable", "DisableHttp2Connection");
                }
                connection.Dispose();
            }
        });
    }
References System.Net.Http.HttpConnectionPool._associatedHttp2ConnectionCount, System.Net.Http.HttpConnectionPool.CheckForHttp2ConnectionInjection(), System.Net.Http.Http2Connection.Dispose(), System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionPool.ReturnHttp2Connection(), System.Threading.Tasks.Task< TResult >.Run(), System.Net.Http.HttpConnectionPool.SyncObj, System.Net.Http.Http2Connection.Trace(), and System.Net.Http.Http2Connection.WaitForAvailableStreamsAsync().
Referenced by System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(), and System.Net.Http.HttpConnectionPool.ReturnHttp2Connection().