Terraria: System.Net.Http.HttpConnectionPool.ApplyPlaintextFilterAsync
ApplyPlaintextFilterAsync()
async ValueTask< Stream > System.Net.Http.HttpConnectionPool.ApplyPlaintextFilterAsync (bool async, Stream stream, Version httpVersion, HttpRequestMessage request, CancellationToken cancellationToken) inline private
Definition at line 1189 of file HttpConnectionPool.cs.
    {
        if (Settings._plaintextStreamFilter == null)
        {
            return stream;
        }
        Stream stream2;
        try
        {
            ValueTask<Stream> valueTask = Settings._plaintextStreamFilter(new SocketsHttpPlaintextStreamFilterContext(stream, httpVersion, request), cancellationToken);
            if (!async && !valueTask.IsCompleted)
            {
                Trace("PlaintextStreamFilter completing asynchronously for a synchronous request.", "ApplyPlaintextFilterAsync");
            }
            stream2 = await valueTask.ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (OperationCanceledException ex) when (ex.CancellationToken == cancellationToken)
        {
            stream.Dispose();
            throw;
        }
        catch (Exception inner)
        {
            stream.Dispose();
            throw new HttpRequestException(System.SR.net_http_exception_during_plaintext_filter, inner);
        }
        if (stream2 == null)
        {
            stream.Dispose();
            throw new HttpRequestException(System.SR.net_http_null_from_plaintext_filter);
        }
        return stream2;
    }
References System.Net.Http.HttpConnectionSettings._plaintextStreamFilter, System.cancellationToken, System.SR.net_http_exception_during_plaintext_filter, System.SR.net_http_null_from_plaintext_filter, System.Net.Http.HttpConnectionPool.Settings, System.stream, and System.Net.Http.HttpConnectionPool.Trace().
Referenced by System.Net.Http.HttpConnectionPool.ConstructHttp11ConnectionAsync(), and System.Net.Http.HttpConnectionPool.ConstructHttp2ConnectionAsync().