Terraria: System.Net.Http.HttpConnectionPool.CreateConnectTimeoutException
CreateConnectTimeoutException()
static Exception System.Net.Http.HttpConnectionPool.CreateConnectTimeoutException (OperationCanceledException oce) inline static private
Definition at line 367 of file HttpConnectionPool.cs.
    {
        TimeoutException innerException = new TimeoutException(System.SR.net_http_connect_timedout, oce.InnerException);
        Exception ex = CancellationHelper.CreateOperationCanceledException(innerException, oce.CancellationToken);
        ExceptionDispatchInfo.SetCurrentStackTrace(ex);
        return ex;
    }
References System.Net.Http.CancellationHelper.CreateOperationCanceledException(), System.SR.net_http_connect_timedout, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace().
Referenced by System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(), and System.Net.Http.HttpConnectionPool.HandleHttp11Downgrade().