Terraria: System.Net.Http.HttpConnectionPool.CleanCacheAndDisposeIfUnused
CleanCacheAndDisposeIfUnused()
bool System.Net.Http.HttpConnectionPool.CleanCacheAndDisposeIfUnused () inline
Definition at line 1587 of file HttpConnectionPool.cs.
    {
        TimeSpan pooledConnectionLifetime2 = _poolManager.Settings._pooledConnectionLifetime;
        TimeSpan pooledConnectionIdleTimeout2 = _poolManager.Settings._pooledConnectionIdleTimeout;
        List<HttpConnectionBase> toDispose2 = null;
        lock (SyncObj)
        {
            if (!_usedSinceLastCleanup && _associatedHttp11ConnectionCount == 0 && _associatedHttp2ConnectionCount == 0)
            {
                _disposed = true;
                return true;
            }
            _usedSinceLastCleanup = false;
            long tickCount = Environment.TickCount64;
            ScavengeConnectionList<HttpConnection>(_availableHttp11Connections, ref toDispose2, tickCount, pooledConnectionLifetime2, pooledConnectionIdleTimeout2);
            if (_availableHttp2Connections != null)
            {
                int num = ScavengeConnectionList<Http2Connection>(_availableHttp2Connections, ref toDispose2, tickCount, pooledConnectionLifetime2, pooledConnectionIdleTimeout2);
                _associatedHttp2ConnectionCount -= num;
            }
        }
        toDispose2?.ForEach(delegate(HttpConnectionBase c)
        {
            c.Dispose();
        });
        return false;
        static bool IsUsableConnection(HttpConnectionBase connection, long nowTicks, TimeSpan pooledConnectionLifetime, TimeSpan pooledConnectionIdleTimeout)
        {
            if (pooledConnectionIdleTimeout != Timeout.InfiniteTimeSpan)
            {
                long idleTicks = connection.GetIdleTicks(nowTicks);
                if ((double)idleTicks > pooledConnectionIdleTimeout.TotalMilliseconds)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        connection.Trace($"Scavenging connection. Idle {TimeSpan.FromMilliseconds(idleTicks)} > {pooledConnectionIdleTimeout}.", "CleanCacheAndDisposeIfUnused");
                    }
                    return false;
                }
            }
            if (pooledConnectionLifetime != Timeout.InfiniteTimeSpan)
            {
                long lifetimeTicks = connection.GetLifetimeTicks(nowTicks);
                if ((double)lifetimeTicks > pooledConnectionLifetime.TotalMilliseconds)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        connection.Trace($"Scavenging connection. Lifetime {TimeSpan.FromMilliseconds(lifetimeTicks)} > {pooledConnectionLifetime}.", "CleanCacheAndDisposeIfUnused");
                    }
                    return false;
                }
            }
            if (!connection.CheckUsabilityOnScavenge())
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    connection.Trace("Scavenging connection. Unexpected data or EOF received.", "CleanCacheAndDisposeIfUnused");
                }
                return false;
            }
            return true;
        }
        static int ScavengeConnectionList<T>(List<T> list, ref List<HttpConnectionBase> toDispose, long nowTicks, TimeSpan pooledConnectionLifetime, TimeSpan pooledConnectionIdleTimeout) where T : HttpConnectionBase
        {
            int i;
            for (i = 0; i < list.Count && IsUsableConnection(list[i], nowTicks, pooledConnectionLifetime, pooledConnectionIdleTimeout); i++)
            {
            }
            int num2 = 0;
            if (i < list.Count)
            {
                if (toDispose == null)
                {
                    toDispose = new List<HttpConnectionBase> { list[i] };
                }
                int j = i + 1;
                while (j < list.Count)
                {
                    for (; j < list.Count && !IsUsableConnection(list[j], nowTicks, pooledConnectionLifetime, pooledConnectionIdleTimeout); j++)
                    {
                        toDispose.Add(list[j]);
                    }
                    if (j < list.Count)
                    {
                        list[i++] = list[j++];
                    }
                }
                num2 = list.Count - i;
                list.RemoveRange(i, num2);
            }
            return num2;
        }
    }
References System.Net.Http.HttpConnectionPool._associatedHttp11ConnectionCount, System.Net.Http.HttpConnectionPool._associatedHttp2ConnectionCount, System.Net.Http.HttpConnectionPool._availableHttp11Connections, System.Net.Http.HttpConnectionPool._availableHttp2Connections, System.Net.Http.HttpConnectionPool._disposed, System.Net.Http.HttpConnectionSettings._pooledConnectionIdleTimeout, System.Net.Http.HttpConnectionSettings._pooledConnectionLifetime, System.Net.Http.HttpConnectionPool._poolManager, System.Net.Http.HttpConnectionPool._usedSinceLastCleanup, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Http.HttpConnectionBase.CheckUsabilityOnScavenge(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Http.HttpConnectionBase.Dispose(), System.Net.Http.HttpConnectionBase.GetIdleTicks(), System.Net.Http.HttpConnectionBase.GetLifetimeTicks(), System.Threading.Timeout.InfiniteTimeSpan, System.list, System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionPoolManager.Settings, System.Net.Http.HttpConnectionPool.SyncObj, System.T, System.Environment.TickCount64, and System.Net.Http.HttpConnectionBase.Trace().