Terraria: System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync
SendWithVersionDetectionAndRetryAsync()
async ValueTask< HttpResponseMessage > System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync (HttpRequestMessage request, bool async, bool doRequestAuth, CancellationToken cancellationToken) inline
Definition at line 783 of file HttpConnectionPool.cs.
    {
        int retryCount = 0;
        while (true)
        {
            try
            {
                HttpResponseMessage response = null;
                if (IsHttp3Supported() && _http3Enabled && (request.Version.Major >= 3 || (request.VersionPolicy == HttpVersionPolicy.RequestVersionOrHigher && IsSecure)))
                {
                    response = await TrySendUsingHttp3Async(request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
                if (response == null)
                {
                    if (request.Version.Major >= 3 && request.VersionPolicy != 0)
                    {
                        ThrowGetVersionException(request, 3);
                    }
                    if (_http2Enabled && (request.Version.Major >= 2 || (request.VersionPolicy == HttpVersionPolicy.RequestVersionOrHigher && IsSecure)) && (request.VersionPolicy != 0 || IsSecure))
                    {
                        Http2Connection http2Connection = await GetHttp2ConnectionAsync(request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                        if (http2Connection != null)
{
                            response = await http2Connection.SendAsync(request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                        }
                    }
                    if (response == null)
                    {
                        if (request.Version.Major >= 2 && request.VersionPolicy != 0)
{
                            ThrowGetVersionException(request, 2);
                        }
                        HttpConnection connection = await GetHttp11ConnectionAsync(request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                        connection.Acquire();
                        try
{
                            response = await SendWithNtConnectionAuthAsync(connection, request, async, doRequestAuth, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                        }
                        finally
{
                            connection.Release();
                        }
                    }
                }
                ProcessAltSvc(response);
                return response;
            }
            catch (HttpRequestException ex) when (ex.AllowRetry == RequestRetryType.RetryOnConnectionFailure)
            {
                if (retryCount == 3)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        Trace($"MaxConnectionFailureRetries limit of {3} hit. Retryable request will not be retried. Exception: {ex}", "SendWithVersionDetectionAndRetryAsync");
                    }
                    throw;
                }
                retryCount++;
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Retry attempt {retryCount} after connection failure. Connection exception: {ex}", "SendWithVersionDetectionAndRetryAsync");
                }
            }
            catch (HttpRequestException ex2) when (ex2.AllowRetry == RequestRetryType.RetryOnLowerHttpVersion)
            {
                if (request.VersionPolicy != 0)
                {
                    throw new HttpRequestException(System.SR.Format(System.SR.net_http_requested_version_server_refused, request.Version, request.VersionPolicy), ex2);
                }
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Retrying request because server requested version fallback: {ex2}", "SendWithVersionDetectionAndRetryAsync");
                }
                request.Version = HttpVersion.Version11;
            }
            catch (HttpRequestException ex3) when (ex3.AllowRetry == RequestRetryType.RetryOnStreamLimitReached)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Retrying request on another HTTP/2 connection after active streams limit is reached on existing one: {ex3}", "SendWithVersionDetectionAndRetryAsync");
                }
            }
        }
    }
References System.Net.Http.HttpConnectionPool._http2Enabled, System.Net.Http.HttpConnectionPool._http3Enabled, System.Net.Http.HttpConnection.Acquire(), System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.SR.Format(), System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(), System.Net.Http.HttpConnectionPool.IsHttp3Supported(), System.Net.Http.HttpConnectionPool.IsSecure, System.Net.NetEventSource.Log, System.SR.net_http_requested_version_server_refused, System.Net.Http.HttpConnectionPool.ProcessAltSvc(), System.Net.Http.HttpConnection.Release(), System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(), System.Net.Http.HttpConnectionPool.ThrowGetVersionException(), System.Net.Http.HttpConnectionPool.Trace(), System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(), and System.Net.HttpVersion.Version11.
Referenced by System.Net.Http.HttpConnectionPool.SendWithProxyAuthAsync().