Terraria: System.Net.Http.HttpConnectionPool.ReturnHttp2Connection
ReturnHttp2Connection()
void System.Net.Http.HttpConnectionPool.ReturnHttp2Connection (Http2Connection connection, bool isNewConnection) inline
Definition at line 1413 of file HttpConnectionPool.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            connection.Trace($"{"isNewConnection"}={isNewConnection}", "ReturnHttp2Connection");
        }
        if (!isNewConnection && CheckExpirationOnReturn(connection))
        {
            lock (SyncObj)
            {
                _associatedHttp2ConnectionCount--;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                connection.Trace("Disposing HTTP/2 connection return to pool. Connection lifetime expired.", "ReturnHttp2Connection");
            }
            connection.Dispose();
            return;
        }
        bool flag = true;
        bool flag2 = false;
        lock (SyncObj)
        {
            if (isNewConnection)
            {
                _pendingHttp2Connection = false;
            }
            while (!_http2RequestQueue.IsEmpty)
            {
                if (!connection.TryReserveStream())
                {
                    flag = false;
                    if (isNewConnection)
                    {
                        HttpRequestException ex = new HttpRequestException(System.SR.net_http_http2_connection_not_established);
                        ExceptionDispatchInfo.SetCurrentStackTrace(ex);
                        _http2RequestQueue.TryFailNextRequest(ex);
                    }
                    break;
                }
                isNewConnection = false;
                if (!_http2RequestQueue.TryDequeueNextRequest(connection))
                {
                    connection.ReleaseStream();
                    break;
                }
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    connection.Trace("Dequeued waiting HTTP/2 request.", "ReturnHttp2Connection");
                }
            }
            CheckForHttp2ConnectionInjection();
            if (_disposed)
            {
                _associatedHttp2ConnectionCount--;
                flag2 = true;
            }
            else if (flag)
            {
                if (_availableHttp2Connections == null)
                {
                    _availableHttp2Connections = new List<Http2Connection>();
                }
                _availableHttp2Connections.Add(connection);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    connection.Trace("Put HTTP/2 connection in pool.", "ReturnHttp2Connection");
                }
                return;
            }
        }
        if (flag2)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                connection.Trace("Disposing HTTP/2 connection returned to pool. Pool was disposed.", "ReturnHttp2Connection");
            }
            connection.Dispose();
        }
        else
        {
            DisableHttp2Connection(connection);
        }
    }
References System.Net.Http.HttpConnectionPool._associatedHttp2ConnectionCount, System.Net.Http.HttpConnectionPool._availableHttp2Connections, System.Net.Http.HttpConnectionPool._disposed, System.Net.Http.HttpConnectionPool._http2RequestQueue, System.Net.Http.HttpConnectionPool._pendingHttp2Connection, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Http.HttpConnectionPool.CheckExpirationOnReturn(), System.Net.Http.HttpConnectionPool.CheckForHttp2ConnectionInjection(), System.Net.Http.HttpConnectionPool.DisableHttp2Connection(), System.Net.Http.Http2Connection.Dispose(), System.Net.NetEventSource.Log, System.SR.net_http_http2_connection_not_established, System.Net.Http.Http2Connection.ReleaseStream(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.Net.Http.HttpConnectionPool.SyncObj, System.Net.Http.Http2Connection.Trace(), and System.Net.Http.Http2Connection.TryReserveStream().
Referenced by System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(), and System.Net.Http.HttpConnectionPool.DisableHttp2Connection().