Terraria: System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync
ConnectToTcpHostAsync()
async ValueTask<(Socket, Stream)> System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync (string host, int port, HttpRequestMessage initialRequest, bool async, CancellationToken cancellationToken) inline private
Definition at line 1119 of file HttpConnectionPool.cs.
    {
        cancellationToken.ThrowIfCancellationRequested();
        DnsEndPoint endPoint = new DnsEndPoint(host, port);
        Socket socket = null;
        try
        {
            Stream item;
            if (Settings._connectCallback != null)
            {
                ValueTask<Stream> valueTask = Settings._connectCallback(new SocketsHttpConnectionContext(endPoint, initialRequest), cancellationToken);
                if (!async && !valueTask.IsCompleted)
                {
                    Trace("ConnectCallback completing asynchronously for a synchronous request.", "ConnectToTcpHostAsync");
                }
                item = (await valueTask.ConfigureAwait(continueOnCapturedContext: false)) ?? throw new HttpRequestException(System.SR.net_http_null_from_connect_callback);
            }
            else
            {
                socket = new Socket(SocketType.Stream, ProtocolType.Tcp)
                {
                    NoDelay = true
                };
                if (async)
                {
                    await socket.ConnectAsync(endPoint, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
                else
                {
                    using (cancellationToken.UnsafeRegister(delegate(object s)
                    {
                        ((Socket)s).Dispose();
                    }, socket))
                    {
                        socket.Connect(endPoint);
                    }
                }
                item = new NetworkStream(socket, ownsSocket: true);
            }
            return (socket, item);
        }
        catch (Exception ex)
        {
            socket?.Dispose();
            throw (ex is OperationCanceledException ex2 && ex2.CancellationToken == cancellationToken) ? CancellationHelper.CreateOperationCanceledException(null, cancellationToken) : ConnectHelper.CreateWrappedException(ex, endPoint.Host, endPoint.Port, cancellationToken);
        }
    }
References System.Net.Http.HttpConnectionSettings._connectCallback, System.cancellationToken, System.Net.Http.CancellationHelper.CreateOperationCanceledException(), System.Net.Http.ConnectHelper.CreateWrappedException(), System.item, System.SR.net_http_null_from_connect_callback, System.Net.Sockets.NoDelay, System.s, System.Net.Http.HttpConnectionPool.Settings, System.Net.Sockets.Socket, and System.Net.Http.HttpConnectionPool.Trace().
Referenced by System.Net.Http.HttpConnectionPool.ConnectAsync(), and System.Net.Http.HttpConnectionPool.EstablishSocksTunnel().