Terraria: System.Net.Http.HttpConnectionPool.IsHttp3Supported
IsHttp3Supported()
static bool System.Net.Http.HttpConnectionPool.IsHttp3Supported () inline static package
Definition at line 327 of file HttpConnectionPool.cs.
    {
        if ((!OperatingSystem.IsLinux() || OperatingSystem.IsAndroid()) && !OperatingSystem.IsWindows())
        {
            return OperatingSystem.IsMacOS();
        }
        return true;
    }
References System.OperatingSystem.IsAndroid(), System.OperatingSystem.IsLinux(), System.OperatingSystem.IsMacOS(), and System.OperatingSystem.IsWindows().
Referenced by System.Net.Http.HttpConnectionPool.HttpConnectionPool(), System.Net.Http.HttpConnectionSettings.CloneAndNormalize(), and System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync().