Terraria: System.Net.Http.HttpConnectionPool.EstablishSocksTunnel
EstablishSocksTunnel()
async ValueTask<(Socket socket, Stream stream)> System.Net.Http.HttpConnectionPool.EstablishSocksTunnel (HttpRequestMessage request, bool async, CancellationToken cancellationToken) inline private
Definition at line 1273 of file HttpConnectionPool.cs.
    {
        var (socket, stream) = await ConnectToTcpHostAsync(_proxyUri.IdnHost, _proxyUri.Port, request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        try
        {
            await SocksHelper.EstablishSocksTunnelAsync(stream, _originAuthority.IdnHost, _originAuthority.Port, _proxyUri, ProxyCredentials, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (Exception ex) when (!(ex is OperationCanceledException))
        {
            throw new HttpRequestException(System.SR.net_http_request_aborted, ex);
        }
        return (socket, stream);
    }
References System.Net.Http.HttpConnectionPool._originAuthority, System.Net.Http.HttpConnectionPool._proxyUri, System.cancellationToken, System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(), System.Net.Http.SocksHelper.EstablishSocksTunnelAsync(), System.Net.Http.HttpAuthority.IdnHost, System.Uri.IdnHost, System.SR.net_http_request_aborted, System.Net.Http.HttpAuthority.Port, System.Uri.Port, System.Net.Http.HttpConnectionPool.ProxyCredentials, and System.stream.
Referenced by System.Net.Http.HttpConnectionPool.ConnectAsync().