Terraria: System.Net.Http.HttpConnectionPool.BlocklistAuthority
BlocklistAuthority()
void System.Net.Http.HttpConnectionPool.BlocklistAuthority (HttpAuthority badAuthority) inline package
Definition at line 975 of file HttpConnectionPool.cs.
    {
        HashSet<HttpAuthority> altSvcBlocklist = _altSvcBlocklist;
        if (altSvcBlocklist == null)
        {
            lock (SyncObj)
            {
                altSvcBlocklist = _altSvcBlocklist;
                if (altSvcBlocklist == null)
                {
                    altSvcBlocklist = new HashSet<HttpAuthority>();
                    _altSvcBlocklistTimerCancellation = new CancellationTokenSource();
                    _altSvcBlocklist = altSvcBlocklist;
                }
            }
        }
        bool flag = false;
        bool flag2;
        lock (altSvcBlocklist)
        {
            flag2 = altSvcBlocklist.Add(badAuthority);
            if (flag2 && altSvcBlocklist.Count >= 8 && _altSvcEnabled)
            {
                _altSvcEnabled = false;
                flag = true;
            }
        }
        lock (SyncObj)
        {
            if (_http3Authority == badAuthority)
            {
                ExpireAltSvcAuthority();
                _authorityExpireTimer.Change(-1, -1);
            }
        }
        if (flag2)
        {
            Task.Delay(600000).ContinueWith(delegate
            {
                lock (altSvcBlocklist)
                {
                    altSvcBlocklist.Remove(badAuthority);
                }
            }, _altSvcBlocklistTimerCancellation.Token, TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);
        }
        if (flag)
        {
            Task.Delay(600000).ContinueWith(delegate
            {
                _altSvcEnabled = true;
            }, _altSvcBlocklistTimerCancellation.Token, TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);
        }
    }
References System.Net.Http.HttpConnectionPool._altSvcBlocklist, System.Net.Http.HttpConnectionPool._altSvcBlocklistTimerCancellation, System.Net.Http.HttpConnectionPool._altSvcEnabled, System.Net.Http.HttpConnectionPool._authorityExpireTimer, System.Net.Http.HttpConnectionPool._http3Authority, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.Timer.Change(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Delay(), System.Net.Http.HttpConnectionPool.ExpireAltSvcAuthority(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Net.Http.HttpConnectionPool.SyncObj, and System.Threading.CancellationTokenSource.Token.
Referenced by System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(), and System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async().