Terraria: System.Net.Http.HttpConnectionPool.HttpConnectionPool
HttpConnectionPool()
System.Net.Http.HttpConnectionPool.HttpConnectionPool (HttpConnectionPoolManager poolManager, HttpConnectionKind kind, string host, int port, string sslHostName, Uri proxyUri) inline
Definition at line 239 of file HttpConnectionPool.cs.
    {
        _poolManager = poolManager;
        _kind = kind;
        _proxyUri = proxyUri;
        _maxHttp11Connections = Settings._maxConnectionsPerServer;
        if (host != null)
        {
            _originAuthority = new HttpAuthority(host, port);
        }
        _http2Enabled = _poolManager.Settings._maxHttpVersion >= HttpVersion.Version20;
        if (IsHttp3Supported())
        {
            _http3Enabled = _poolManager.Settings._maxHttpVersion >= HttpVersion.Version30 && (_poolManager.Settings._quicImplementationProvider ?? QuicImplementationProviders.Default).IsSupported;
        }
        switch (kind)
        {
        case HttpConnectionKind.Http:
            _http3Enabled = false;
            break;
        case HttpConnectionKind.Proxy:
            _http2Enabled = false;
            _http3Enabled = false;
            break;
        case HttpConnectionKind.ProxyTunnel:
            _http2Enabled = false;
            _http3Enabled = false;
            break;
        case HttpConnectionKind.SslProxyTunnel:
            _http3Enabled = false;
            break;
        case HttpConnectionKind.ProxyConnect:
            _maxHttp11Connections = int.MaxValue;
            _http2Enabled = false;
            _http3Enabled = false;
            break;
        case HttpConnectionKind.SocksTunnel:
        case HttpConnectionKind.SslSocksTunnel:
            _http3Enabled = false;
            break;
        }
        if (!_http3Enabled)
        {
            _altSvcEnabled = false;
        }
        string text = null;
        if (_originAuthority != null)
        {
            text = ((_originAuthority.Port != ((sslHostName == null) ? 80 : 443)) ? $"{_originAuthority.IdnHost}:{_originAuthority.Port}" : _originAuthority.IdnHost);
            _hostHeaderValueBytes = Encoding.ASCII.GetBytes(text);
            if (sslHostName == null)
            {
                _http2EncodedAuthorityHostHeader = HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingToAllocatedArray(1, text);
                _http3EncodedAuthorityHostHeader = QPackEncoder.EncodeLiteralHeaderFieldWithStaticNameReferenceToArray(0, text);
            }
        }
        if (sslHostName != null)
        {
            _sslOptionsHttp11 = ConstructSslOptions(poolManager, sslHostName);
            _sslOptionsHttp11.ApplicationProtocols = null;
            if (_http2Enabled)
            {
                _sslOptionsHttp2 = ConstructSslOptions(poolManager, sslHostName);
                _sslOptionsHttp2.ApplicationProtocols = s_http2ApplicationProtocols;
                _sslOptionsHttp2Only = ConstructSslOptions(poolManager, sslHostName);
                _sslOptionsHttp2Only.ApplicationProtocols = s_http2OnlyApplicationProtocols;
                _http2EncodedAuthorityHostHeader = HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingToAllocatedArray(1, text);
                _http3EncodedAuthorityHostHeader = QPackEncoder.EncodeLiteralHeaderFieldWithStaticNameReferenceToArray(0, text);
            }
            if (IsHttp3Supported() && _http3Enabled)
            {
                _sslOptionsHttp3 = ConstructSslOptions(poolManager, sslHostName);
                _sslOptionsHttp3.ApplicationProtocols = s_http3ApplicationProtocols;
            }
        }
        if (_poolManager.Settings._preAuthenticate)
        {
            PreAuthCredentials = new CredentialCache();
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"{this}", ".ctor");
        }
    }
References System.Net.Http.HttpConnectionPool._altSvcEnabled, System.Net.Http.HttpConnectionPool._hostHeaderValueBytes, System.Net.Http.HttpConnectionPool._http2Enabled, System.Net.Http.HttpConnectionPool._http2EncodedAuthorityHostHeader, System.Net.Http.HttpConnectionPool._http3Enabled, System.Net.Http.HttpConnectionPool._http3EncodedAuthorityHostHeader, System.Net.Http.HttpConnectionPool._kind, System.Net.Http.HttpConnectionSettings._maxConnectionsPerServer, System.Net.Http.HttpConnectionPool._maxHttp11Connections, System.Net.Http.HttpConnectionPool._originAuthority, System.Net.Http.HttpConnectionPool._poolManager, System.Net.Http.HttpConnectionSettings._preAuthenticate, System.Net.Http.HttpConnectionPool._proxyUri, System.Net.Http.HttpConnectionPool._sslOptionsHttp11, System.Net.Http.HttpConnectionPool._sslOptionsHttp2, System.Net.Http.HttpConnectionPool._sslOptionsHttp2Only, System.Net.Http.HttpConnectionPool._sslOptionsHttp3, System.Text.Encoding.ASCII, System.Net.Http.HttpConnectionPool.ConstructSslOptions(), System.Net.Quic.QuicImplementationProviders.Default, System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingToAllocatedArray(), System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithStaticNameReferenceToArray(), System.Net.Http.HttpAuthority.IdnHost, System.Net.Http.HttpConnectionPool.IsHttp3Supported(), System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionPool.PreAuthCredentials, System.Net.Http.HttpConnectionPool.s_http2ApplicationProtocols, System.Net.Http.HttpConnectionPool.s_http2OnlyApplicationProtocols, System.Net.Http.HttpConnectionPool.s_http3ApplicationProtocols, System.Net.Http.HttpConnectionPool.Settings, System.Net.Http.HttpConnectionPoolManager.Settings, System.text, System.Net.Http.HttpConnectionPool.Trace(), and System.Net.HttpVersion.Version20.