Terraria: System.Net.Http.HttpConnectionPool.CheckForHttp11ConnectionInjection
CheckForHttp11ConnectionInjection()
void System.Net.Http.HttpConnectionPool.CheckForHttp11ConnectionInjection () inline private
Definition at line 402 of file HttpConnectionPool.cs.
    {
        if (_http11RequestQueue.TryPeekNextRequest(out var request) && _availableHttp11Connections.Count == 0 && _http11RequestQueue.Count > _pendingHttp11ConnectionCount && _associatedHttp11ConnectionCount < _maxHttp11Connections)
        {
            _associatedHttp11ConnectionCount++;
            _pendingHttp11ConnectionCount++;
            Task.Run(() => AddHttp11ConnectionAsync(request));
        }
    }
References System.Net.Http.HttpConnectionPool._associatedHttp11ConnectionCount, System.Net.Http.HttpConnectionPool._availableHttp11Connections, System.Net.Http.HttpConnectionPool._http11RequestQueue, System.Net.Http.HttpConnectionPool._maxHttp11Connections, System.Net.Http.HttpConnectionPool._pendingHttp11ConnectionCount, System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Threading.Tasks.Task< TResult >.Run().
Referenced by System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.HandleHttp11ConnectionFailure(), and System.Net.Http.HttpConnectionPool.InvalidateHttp11Connection().