Terraria: System.Net.Http.HttpConnectionPool.HandleHttp2ConnectionFailure
HandleHttp2ConnectionFailure()
void System.Net.Http.HttpConnectionPool.HandleHttp2ConnectionFailure (Exception e) inline private
Definition at line 1302 of file HttpConnectionPool.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("HTTP2 connection failed", "HandleHttp2ConnectionFailure");
        }
        lock (SyncObj)
        {
            _associatedHttp2ConnectionCount--;
            _pendingHttp2Connection = false;
            _http2RequestQueue.TryFailNextRequest(e);
            CheckForHttp2ConnectionInjection();
        }
    }
References System.Net.Http.HttpConnectionPool._associatedHttp2ConnectionCount, System.Net.Http.HttpConnectionPool._http2RequestQueue, System.Net.Http.HttpConnectionPool._pendingHttp2Connection, System.Net.Http.HttpConnectionPool.CheckForHttp2ConnectionInjection(), System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionPool.SyncObj, and System.Net.Http.HttpConnectionPool.Trace().
Referenced by System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync().