Terraria: System.Net.Http.HttpConnectionPool.ReturnHttp11Connection
ReturnHttp11Connection()
void System.Net.Http.HttpConnectionPool.ReturnHttp11Connection (HttpConnection connection, bool isNewConnection = false) inline
Definition at line 1367 of file HttpConnectionPool.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            connection.Trace($"{"isNewConnection"}={isNewConnection}", "ReturnHttp11Connection");
        }
        if (!isNewConnection && CheckExpirationOnReturn(connection))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                connection.Trace("Disposing HTTP/1.1 connection return to pool. Connection lifetime expired.", "ReturnHttp11Connection");
            }
            connection.Dispose();
            return;
        }
        lock (SyncObj)
        {
            if (isNewConnection)
            {
                _pendingHttp11ConnectionCount--;
            }
            if (_http11RequestQueue.TryDequeueNextRequest(connection))
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    connection.Trace("Dequeued waiting HTTP/1.1 request.", "ReturnHttp11Connection");
                }
                return;
            }
            if (!_disposed)
            {
                _availableHttp11Connections.Add(connection);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    connection.Trace("Put connection in pool.", "ReturnHttp11Connection");
                }
                return;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                connection.Trace("Disposing connection returned to pool. Pool was disposed.", "ReturnHttp11Connection");
            }
        }
        connection.Dispose();
    }
References System.Net.Http.HttpConnectionPool._availableHttp11Connections, System.Net.Http.HttpConnectionPool._disposed, System.Net.Http.HttpConnectionPool._http11RequestQueue, System.Net.Http.HttpConnectionPool._pendingHttp11ConnectionCount, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Http.HttpConnectionPool.CheckExpirationOnReturn(), System.Net.Http.HttpConnection.Dispose(), System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionPool.SyncObj, and System.Net.Http.HttpConnection.Trace().
Referenced by System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.HandleHttp11Downgrade(), and System.Net.Http.HttpConnection.ReturnConnectionToPool().