Terraria: System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync
GetHttp3ConnectionAsync()
async ValueTask< Http3Connection > System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync (HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken) inline private
Definition at line 673 of file HttpConnectionPool.cs.
    {
        Http3Connection http3Connection = Volatile.Read(ref _http3Connection);
        if (http3Connection != null)
        {
            if (!CheckExpirationOnGet(http3Connection) && http3Connection.Authority == authority)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace("Using existing HTTP3 connection.", "GetHttp3ConnectionAsync");
                }
                _usedSinceLastCleanup = true;
                return http3Connection;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                http3Connection.Trace("Found expired HTTP3 connection.", "GetHttp3ConnectionAsync");
            }
            http3Connection.Dispose();
            InvalidateHttp3Connection(http3Connection);
        }
        if (_http3ConnectionCreateLock == null)
        {
            lock (SyncObj)
            {
                if (_http3ConnectionCreateLock == null)
                {
                    _http3ConnectionCreateLock = new SemaphoreSlim(1);
                }
            }
        }
        await _http3ConnectionCreateLock.WaitAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        try
        {
            if (_http3Connection != null)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace("Using existing HTTP3 connection.", "GetHttp3ConnectionAsync");
                }
                return _http3Connection;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace("Attempting new HTTP3 connection.", "GetHttp3ConnectionAsync");
            }
            QuicConnection connection;
            try
            {
                connection = await ConnectHelper.ConnectQuicAsync(request, Settings._quicImplementationProvider ?? QuicImplementationProviders.Default, new DnsEndPoint(authority.IdnHost, authority.Port), _sslOptionsHttp3, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            catch
            {
                BlocklistAuthority(authority);
                throw;
            }
            http3Connection = (_http3Connection = new Http3Connection(this, _originAuthority, authority, connection));
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace("New HTTP3 connection established.", "GetHttp3ConnectionAsync");
            }
            return http3Connection;
        }
        finally
        {
            _http3ConnectionCreateLock.Release();
        }
    }
References System.Net.Http.HttpConnectionPool._http3Connection, System.Net.Http.HttpConnectionPool._http3ConnectionCreateLock, System.Net.Http.HttpConnectionPool._originAuthority, System.Net.Http.HttpConnectionSettings._quicImplementationProvider, System.Net.Http.HttpConnectionPool._sslOptionsHttp3, System.Net.Http.HttpConnectionPool._usedSinceLastCleanup, System.Net.Http.HttpConnectionPool.BlocklistAuthority(), System.cancellationToken, System.Net.Http.HttpConnectionPool.CheckExpirationOnGet(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.ConnectHelper.ConnectQuicAsync(), System.Net.Quic.QuicImplementationProviders.Default, System.Net.Http.HttpConnectionPool.InvalidateHttp3Connection(), System.Net.NetEventSource.Log, System.Threading.Volatile.Read(), System.Threading.SemaphoreSlim.Release(), System.Net.Http.HttpConnectionPool.Settings, System.Net.Http.HttpConnectionPool.SyncObj, System.Net.Http.HttpConnectionPool.Trace(), and System.Threading.SemaphoreSlim.WaitAsync().
Referenced by System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async().