Terraria: System.Net.Http.HttpConnectionPool.CheckExpirationOnReturn
CheckExpirationOnReturn()
bool System.Net.Http.HttpConnectionPool.CheckExpirationOnReturn (HttpConnectionBase connection) inline private
Definition at line 1353 of file HttpConnectionPool.cs.
    {
        TimeSpan pooledConnectionLifetime = _poolManager.Settings._pooledConnectionLifetime;
        if (pooledConnectionLifetime != Timeout.InfiniteTimeSpan)
        {
            if (!(pooledConnectionLifetime == TimeSpan.Zero))
            {
                return (double)connection.GetLifetimeTicks(Environment.TickCount64) > pooledConnectionLifetime.TotalMilliseconds;
            }
            return true;
        }
        return false;
    }
References System.Net.Http.HttpConnectionSettings._pooledConnectionLifetime, System.Net.Http.HttpConnectionPool._poolManager, System.Net.Http.HttpConnectionBase.GetLifetimeTicks(), System.Threading.Timeout.InfiniteTimeSpan, System.Net.Http.HttpConnectionPoolManager.Settings, System.Environment.TickCount64, and System.TimeSpan.Zero.
Referenced by System.Net.Http.HttpConnectionPool.ReturnHttp11Connection(), and System.Net.Http.HttpConnectionPool.ReturnHttp2Connection().