Terraria: System.Net.Http.HttpConnectionPool._availableHttp11Connections
_availableHttp11Connections
readonly List<HttpConnection> System.Net.Http.HttpConnectionPool._availableHttp11Connections = new List<HttpConnection>() private
Definition at line 120 of file HttpConnectionPool.cs.
Referenced by System.Net.Http.HttpConnectionPool.CheckForHttp11ConnectionInjection(), System.Net.Http.HttpConnectionPool.CleanCacheAndDisposeIfUnused(), System.Net.Http.HttpConnectionPool.Dispose(), System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(), and System.Net.Http.HttpConnectionPool.ReturnHttp11Connection().