Terraria: System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync
AddHttp11ConnectionAsync()
async Task System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync (HttpRequestMessage request) inline private
Definition at line 375 of file HttpConnectionPool.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("Creating new HTTP/1.1 connection for pool.", "AddHttp11ConnectionAsync");
        }
        HttpConnection connection;
        using (CancellationTokenSource cts = GetConnectTimeoutCancellationTokenSource())
        {
            try
            {
                connection = await CreateHttp11ConnectionAsync(request, async: true, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
            }
            catch (OperationCanceledException ex) when (ex.CancellationToken == cts.Token)
            {
                HandleHttp11ConnectionFailure(CreateConnectTimeoutException(ex));
                return;
            }
            catch (Exception e)
            {
                HandleHttp11ConnectionFailure(e);
                return;
            }
        }
        ReturnHttp11Connection(connection, isNewConnection: true);
    }
References System.Net.Http.HttpConnectionPool.CreateConnectTimeoutException(), System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.GetConnectTimeoutCancellationTokenSource(), System.Net.Http.HttpConnectionPool.HandleHttp11ConnectionFailure(), System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionPool.ReturnHttp11Connection(), and System.Net.Http.HttpConnectionPool.Trace().
Referenced by System.Net.Http.HttpConnectionPool.CheckForHttp11ConnectionInjection().