Terraria: System.Dynamic.UpdateDelegates.UpdateAndExecute10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TRet >
UpdateAndExecute10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TRet >()
static TRet System.Dynamic.UpdateDelegates.UpdateAndExecute10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TRet > (CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9) inline static package
Definition at line 764 of file UpdateDelegates.cs.
    {
        CallSite<Func<CallSite, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TRet>> callSite = (CallSite<Func<CallSite, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TRet>>)site;
        Func<CallSite, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TRet> target = callSite.Target;
        site = callSite.GetMatchmaker();
        Func<CallSite, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TRet>[] rules;
        Func<CallSite, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TRet> func;
        if ((rules = CallSiteOps.GetRules(callSite)) != null)
        {
            for (int i = 0; i < rules.Length; i++)
            {
                func = rules[i];
                if ((object)func != target)
                {
                    callSite.Target = func;
                    TRet result = func(site, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                    if (CallSiteOps.GetMatch(site))
                    {
                        CallSiteOps.UpdateRules(callSite, i);
                        callSite.ReleaseMatchmaker(site);
                        return result;
                    }
                    CallSiteOps.ClearMatch(site);
                }
            }
        }
        RuleCache<Func<CallSite, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TRet>> ruleCache = CallSiteOps.GetRuleCache(callSite);
        rules = ruleCache.GetRules();
        for (int j = 0; j < rules.Length; j++)
        {
            func = (callSite.Target = rules[j]);
            try
            {
                TRet result = func(site, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                if (CallSiteOps.GetMatch(site))
                {
                    callSite.ReleaseMatchmaker(site);
                    return result;
                }
            }
            finally
            {
                if (CallSiteOps.GetMatch(site))
                {
                    CallSiteOps.AddRule(callSite, func);
                    CallSiteOps.MoveRule(ruleCache, func, j);
                }
            }
            CallSiteOps.ClearMatch(site);
        }
        func = null;
        object[] args = new object[10] { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 };
        while (true)
        {
            callSite.Target = target;
            func = (callSite.Target = callSite.Binder.BindCore(callSite, args));
            try
            {
                TRet result = func(site, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                if (CallSiteOps.GetMatch(site))
                {
                    callSite.ReleaseMatchmaker(site);
                    return result;
                }
            }
            finally
            {
                if (CallSiteOps.GetMatch(site))
                {
                    CallSiteOps.AddRule(callSite, func);
                }
            }
            CallSiteOps.ClearMatch(site);
        }
    }
References System.Runtime.CompilerServices.CallSite< T >.Binder, System.Runtime.CompilerServices.CallSiteOps.ClearMatch(), System.Runtime.CompilerServices.CallSiteOps.GetMatch(), System.Runtime.CompilerServices.CallSite< T >.GetMatchmaker(), System.Runtime.CompilerServices.RuleCache< T >.GetRules(), System.Runtime.CompilerServices.CallSite< T >.ReleaseMatchmaker(), and System.Runtime.CompilerServices.CallSite< T >.Target.