Terraria: System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6< T0, T1, T2, T3, T4, T5 >
UpdateAndExecuteVoid6< T0, T1, T2, T3, T4, T5 >()
static void System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6< T0, T1, T2, T3, T4, T5 > (CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) inline static package
Definition at line 1263 of file UpdateDelegates.cs.
    {
        CallSite<Action<CallSite, T0, T1, T2, T3, T4, T5>> callSite = (CallSite<Action<CallSite, T0, T1, T2, T3, T4, T5>>)site;
        Action<CallSite, T0, T1, T2, T3, T4, T5> target = callSite.Target;
        site = callSite.GetMatchmaker();
        Action<CallSite, T0, T1, T2, T3, T4, T5>[] rules;
        Action<CallSite, T0, T1, T2, T3, T4, T5> action;
        if ((rules = CallSiteOps.GetRules(callSite)) != null)
        {
            for (int i = 0; i < rules.Length; i++)
            {
                action = rules[i];
                if ((object)action != target)
                {
                    callSite.Target = action;
                    action(site, arg0, arg1, arg2, arg3, arg4, arg5);
                    if (CallSiteOps.GetMatch(site))
                    {
                        CallSiteOps.UpdateRules(callSite, i);
                        callSite.ReleaseMatchmaker(site);
                        return;
                    }
                    CallSiteOps.ClearMatch(site);
                }
            }
        }
        RuleCache<Action<CallSite, T0, T1, T2, T3, T4, T5>> ruleCache = CallSiteOps.GetRuleCache(callSite);
        rules = ruleCache.GetRules();
        for (int j = 0; j < rules.Length; j++)
        {
            action = (callSite.Target = rules[j]);
            try
            {
                action(site, arg0, arg1, arg2, arg3, arg4, arg5);
                if (CallSiteOps.GetMatch(site))
                {
                    callSite.ReleaseMatchmaker(site);
                    return;
                }
            }
            finally
            {
                if (CallSiteOps.GetMatch(site))
                {
                    CallSiteOps.AddRule(callSite, action);
                    CallSiteOps.MoveRule(ruleCache, action, j);
                }
            }
            CallSiteOps.ClearMatch(site);
        }
        action = null;
        object[] args = new object[6] { arg0, arg1, arg2, arg3, arg4, arg5 };
        while (true)
        {
            callSite.Target = target;
            action = (callSite.Target = callSite.Binder.BindCore(callSite, args));
            try
            {
                action(site, arg0, arg1, arg2, arg3, arg4, arg5);
                if (CallSiteOps.GetMatch(site))
                {
                    callSite.ReleaseMatchmaker(site);
                    break;
                }
            }
            finally
            {
                if (CallSiteOps.GetMatch(site))
                {
                    CallSiteOps.AddRule(callSite, action);
                }
            }
            CallSiteOps.ClearMatch(site);
        }
    }
References System.action, System.Runtime.CompilerServices.CallSite< T >.Binder, System.Runtime.CompilerServices.CallSiteOps.ClearMatch(), System.Runtime.CompilerServices.CallSiteOps.GetMatch(), System.Runtime.CompilerServices.CallSite< T >.GetMatchmaker(), System.Runtime.CompilerServices.RuleCache< T >.GetRules(), System.Runtime.CompilerServices.CallSite< T >.ReleaseMatchmaker(), and System.Runtime.CompilerServices.CallSite< T >.Target.