Terraria: NetManager.SendToSelf
SendToSelf()
void NetManager.SendToSelf (NetPacket packet) inline
     {
         packet.Reader.BaseStream.Position = 3L;
         Read(packet.Reader, Main.myPlayer, packet.Length);
         SendCallback(packet);
         Main.ActiveNetDiagnosticsUI.CountSentModuleMessage(packet.Id, packet.Length);
     }
References Main.ActiveNetDiagnosticsUI, INetDiagnosticsUI.CountSentModuleMessage(), NetPacket.Id, L, NetPacket.Length, Main.myPlayer, Read(), NetPacket.Reader, and SendCallback().
Referenced by BroadcastOrLoopback(), SendToServerAndSelf(), and SendToServerOrLoopback().