Terraria: CreativePowers.DifficultySliderPower.UpdateSliderColorAndShowMultiplierMouseOver
UpdateSliderColorAndShowMultiplierMouseOver()
void CreativePowers.DifficultySliderPower.UpdateSliderColorAndShowMultiplierMouseOver (UIElement affectedElement) inline private
         {
             if (affectedElement.IsMouseHovering)
             {
                 string originalText = "x" + StrengthMultiplierToGiveNPCs.ToString("F2");
                 CreativePowersHelper.AddPermissionTextIfNeeded(this, ref originalText);
                 Main.instance.MouseTextNoOverride(originalText, 0, 0);
             }
             if (affectedElement is UIVerticalSlider uIVerticalSlider)
             {
                 uIVerticalSlider.EmptyColor = Color.Black;
                 Color filledColor = (Main.masterMode ? Main.hcColor : (Main.expertMode ? Main.mcColor : ((!(StrengthMultiplierToGiveNPCs < 1f)) ? Color.White : Main.creativeModeColor)));
                 uIVerticalSlider.FilledColor = filledColor;
             }
         }
References CreativePowersHelper.AddPermissionTextIfNeeded(), Color, Main.creativeModeColor, Main.expertMode, Main.hcColor, Main.instance, UIElement.IsMouseHovering, Main.masterMode, Main.mcColor, Main.MouseTextNoOverride(), and CreativePowers.DifficultySliderPower.StrengthMultiplierToGiveNPCs.
Referenced by CreativePowers.DifficultySliderPower.ProvideSlider().