Terraria: ResourceDrawSettings.Draw
Draw()
void ResourceDrawSettings.Draw (SpriteBatch spriteBatch, ref bool isHovered) inline
     {
         int elementCount = ElementCount;
         Vector2 topLeftAnchor = TopLeftAnchor;
         Point value = Main.MouseScreen.ToPoint();
         for (int i = 0; i < elementCount; i++)
         {
             int elementIndex = i + ElementIndexOffset;
             GetTextureMethod(elementIndex, ElementIndexOffset, ElementIndexOffset + elementCount - 1, out var texture, out var drawOffset, out var drawScale, out var sourceRect);
             Rectangle rectangle = texture.Frame();
             if (sourceRect.HasValue)
             {
                 rectangle = sourceRect.Value;
             }
             Vector2 position = topLeftAnchor + drawOffset;
             Vector2 origin = OffsetSpriteAnchor + rectangle.Size() * OffsetSpriteAnchorByTexturePercentile;
             Rectangle rectangle2 = rectangle;
             rectangle2.X += (int)(position.X - origin.X);
             rectangle2.Y += (int)(position.Y - origin.Y);
             if (rectangle2.Contains(value))
             {
                 isHovered = true;
             }
             spriteBatch.Draw(texture.Value, position, rectangle, Color.White, 0f, origin, drawScale, SpriteEffects.None, 0f);
             topLeftAnchor += OffsetPerDraw + rectangle.Size() * OffsetPerDrawByTexturePercentile;
         }
     }
References Color, ElementCount, ElementIndexOffset, GetTextureMethod, Main.MouseScreen, OffsetPerDraw, OffsetPerDrawByTexturePercentile, OffsetSpriteAnchor, OffsetSpriteAnchorByTexturePercentile, and TopLeftAnchor.
Referenced by HorizontalBarsPlayerResourcesDisplaySet.Draw(), FancyClassicPlayerResourcesDisplaySet.DrawLifeBar(), and FancyClassicPlayerResourcesDisplaySet.DrawManaBar().