Terraria: UIBestiaryEntryGrid.FillBestiarySpaceWithEntries
FillBestiarySpaceWithEntries()
void UIBestiaryEntryGrid.FillBestiarySpaceWithEntries () inline
     {
         RemoveAllChildren();
         UpdateEntries();
         GetEntriesToShow(out var maxEntriesWidth, out var maxEntriesHeight, out var maxEntriesToHave);
         FixBestiaryRange(0, maxEntriesToHave);
         int atEntryIndex = _atEntryIndex;
         int num = Math.Min(_lastEntry, atEntryIndex + maxEntriesToHave);
         List<BestiaryEntry> list = new List<BestiaryEntry>();
         for (int i = atEntryIndex; i < num; i++)
         {
             list.Add(_workingSetEntries[i]);
         }
         int num2 = 0;
         float num3 = 0.5f / (float)maxEntriesWidth;
         float num4 = 0.5f / (float)maxEntriesHeight;
         for (int j = 0; j < maxEntriesHeight; j++)
         {
             for (int k = 0; k < maxEntriesWidth; k++)
             {
                 if (num2 >= list.Count)
                 {
                     break;
                 }
                 UIElement uIElement = new UIBestiaryEntryButton(list[num2], isAPrettyPortrait: false);
                 num2++;
                 uIElement.OnLeftClick += _clickOnEntryEvent;
                 uIElement.VAlign = (uIElement.HAlign = 0.5f);
                 uIElement.Left.Set(0f, (float)k / (float)maxEntriesWidth - 0.5f + num3);
                 uIElement.Top.Set(0f, (float)j / (float)maxEntriesHeight - 0.5f + num4);
                 uIElement.SetSnapPoint("Entries", num2, new Vector2(0.2f, 0.7f));
                 Append(uIElement);
             }
         }
     }
References _atEntryIndex, _clickOnEntryEvent, _lastEntry, _workingSetEntries, UIElement.Append(), FixBestiaryRange(), GetEntriesToShow(), UIElement.HAlign, UIElement.Left, UIElement.OnLeftClick, UIElement.RemoveAllChildren(), StyleDimension.Set(), UIElement.SetSnapPoint(), UIElement.Top, UpdateEntries(), and UIElement.VAlign.
Referenced by UIBestiaryEntryGrid(), UIBestiaryTest.FillBestiarySpaceWithEntries(), OffsetLibrary(), and Recalculate().