Terraria: System.Xml.XmlSigningNodeWriter.WriteBase64Text
WriteBase64Text() [1/2]
void System.Xml.XmlSigningNodeWriter.WriteBase64Text (byte[] buffer, int offset, int count) inline private
Definition at line 388 of file XmlSigningNodeWriter.cs.
    {
        if (_base64Chars == null)
        {
            _base64Chars = new byte[512];
        }
        Base64Encoding base64Encoding = XmlConverter.Base64Encoding;
        while (count >= 3)
        {
            int num = Math.Min(_base64Chars.Length / 4 * 3, count - count % 3);
            int count2 = num / 3 * 4;
            base64Encoding.GetChars(buffer, offset, num, _base64Chars, 0);
            _signingWriter.WriteText(_base64Chars, 0, count2);
            if (_text)
            {
                _writer.WriteText(_base64Chars, 0, count2);
            }
            offset += num;
            count -= num;
        }
        if (count > 0)
        {
            base64Encoding.GetChars(buffer, offset, count, _base64Chars, 0);
            _signingWriter.WriteText(_base64Chars, 0, 4);
            if (_text)
            {
                _writer.WriteText(_base64Chars, 0, 4);
            }
        }
    }
References System.Xml.XmlSigningNodeWriter._base64Chars, System.Xml.XmlSigningNodeWriter._signingWriter, System.Xml.XmlSigningNodeWriter._text, System.Xml.XmlSigningNodeWriter._writer, System.Xml.XmlConverter.Base64Encoding, System.buffer, System.count, System.Xml.Dictionary, System.Math.Min(), System.offset, System.Xml.XmlCanonicalWriter.WriteText(), and System.Xml.XmlNodeWriter.WriteText().