Terraria: UIBestiaryEntryGrid.OffsetLibrary
OffsetLibrary()
void UIBestiaryEntryGrid.OffsetLibrary (int offset) inline
     {
         GetEntriesToShow(out var _, out var _, out var maxEntriesToHave);
         FixBestiaryRange(offset, maxEntriesToHave);
         FillBestiarySpaceWithEntries();
     }
References FillBestiarySpaceWithEntries(), FixBestiaryRange(), and GetEntriesToShow().
Referenced by OffsetLibraryByPages().