Terraria: LarvaHoleEntrance.Place
Place()
static void LarvaHoleEntrance.Place (DesertDescription description) inline static
     {
         int num = WorldGen.genRand.Next(2, 4);
         for (int i = 0; i < num; i++)
         {
             int holeRadius = WorldGen.genRand.Next(13, 16);
             int num2 = (int)((double)(i + 1) / (double)(num + 1) * (double)description.Surface.Width);
             num2 += description.Desert.Left;
             int y = description.Surface[num2];
             PlaceAt(description, new Point(num2, y), holeRadius);
         }
     }
References DesertDescription.Desert, WorldGen.genRand, UnifiedRandom.Next(), PlaceAt(), DesertDescription.Surface, and SurfaceMap.Width.
Referenced by DesertBiome.Place().