Terraria: System.Linq.Parallel.GroupByElementSelectorQueryOperatorEnumerator.BuildHashLookup
BuildHashLookup()
override HashLookup< Wrapper< TGroupKey >, ListChunk< TElement > > System.Linq.Parallel.GroupByElementSelectorQueryOperatorEnumerator< TSource, TGroupKey, TElement, TOrderKey >.BuildHashLookup () inline protected
Definition at line 16 of file GroupByElementSelectorQueryOperatorEnumerator.cs.
    {
        HashLookup<Wrapper<TGroupKey>, ListChunk<TElement>> hashLookup = new HashLookup<Wrapper<TGroupKey>, ListChunk<TElement>>(new WrapperEqualityComparer<TGroupKey>(_keyComparer));
        Pair<TSource, TGroupKey> currentElement = default(Pair<TSource, TGroupKey>);
        TOrderKey currentKey = default(TOrderKey);
        int num = 0;
        while (_source.MoveNext(ref currentElement, ref currentKey))
        {
            if ((num++ & 0x3F) == 0)
            {
                _cancellationToken.ThrowIfCancellationRequested();
            }
            Wrapper<TGroupKey> key = new Wrapper<TGroupKey>(currentElement.Second);
            ListChunk<TElement> value = null;
            if (!hashLookup.TryGetValue(key, ref value))
            {
                value = new ListChunk<TElement>(2);
                hashLookup.Add(key, value);
            }
            value.Add(_elementSelector(currentElement.First));
        }
        return hashLookup;
    }
References System.Linq.Parallel.GroupByQueryOperatorEnumerator< TSource, TGroupKey, TElement, TOrderKey >._cancellationToken, System.Linq.Parallel.GroupByElementSelectorQueryOperatorEnumerator< TSource, TGroupKey, TElement, TOrderKey >._elementSelector, System.Linq.Parallel.GroupByQueryOperatorEnumerator< TSource, TGroupKey, TElement, TOrderKey >._keyComparer, System.Linq.Parallel.GroupByQueryOperatorEnumerator< TSource, TGroupKey, TElement, TOrderKey >._source, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.key, System.Threading.CancellationToken.ThrowIfCancellationRequested(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.