Terraria: System.Xml.Linq.XNodeReader.MoveToAttribute
MoveToAttribute() [3/4]
override bool System.Xml.Linq.XNodeReader.MoveToAttribute (string name) inline
Definition at line 623 of file XNodeReader.cs.
    {
        if (!IsInteractive)
        {
            return false;
        }
        XElement elementInAttributeScope = GetElementInAttributeScope();
        if (elementInAttributeScope != null)
        {
            GetNameInAttributeScope(name, elementInAttributeScope, out var localName, out var namespaceName);
            XAttribute xAttribute = elementInAttributeScope.lastAttr;
            if (xAttribute != null)
            {
                do
                {
                    xAttribute = xAttribute.next;
                    if (xAttribute.Name.LocalName == localName && xAttribute.Name.NamespaceName == namespaceName)
                    {
                        if (_omitDuplicateNamespaces && IsDuplicateNamespaceAttribute(xAttribute))
{
                            return false;
                        }
                        _source = xAttribute;
                        _parent = null;
                        return true;
                    }
                }
                while (xAttribute != elementInAttributeScope.lastAttr);
            }
        }
        return false;
    }
References System.Xml.Linq.XNodeReader._omitDuplicateNamespaces, System.Xml.Linq.XNodeReader._parent, System.Xml.Linq.XNodeReader._source, System.Xml.Dictionary, System.Xml.Linq.XNodeReader.GetElementInAttributeScope(), System.Xml.Linq.XNodeReader.GetNameInAttributeScope(), System.Xml.Linq.XNodeReader.IsDuplicateNamespaceAttribute(), System.Xml.Linq.XNodeReader.IsInteractive, and System.Xml.Linq.XAttribute.next.