Terraria: System.Xml.Linq.XNodeReader.ReadToNextSibling
ReadToNextSibling() [1/2]
override bool System.Xml.Linq.XNodeReader.ReadToNextSibling (string localName, string namespaceName) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 904 of file XNodeReader.cs.
    {
        if (!IsInteractive)
        {
            return false;
        }
        MoveToElement();
        if (_source != _root)
        {
            if (_source is XNode xNode)
            {
                foreach (XElement item in xNode.ElementsAfterSelf())
                {
                    if (item.Name.LocalName == localName && item.Name.NamespaceName == namespaceName)
                    {
                        _source = item;
                        IsEndElement = false;
                        return true;
                    }
                }
                if (xNode.parent is XElement)
                {
                    _source = xNode.parent;
                    IsEndElement = true;
                    return false;
                }
            }
            else if (_parent is XElement)
            {
                _source = _parent;
                _parent = null;
                IsEndElement = true;
                return false;
            }
        }
        return ReadToEnd();
    }
References System.Xml.Linq.XNodeReader._parent, System.Xml.Linq.XNodeReader._root, System.Xml.Linq.XNodeReader._source, System.Xml.Dictionary, System.Xml.Linq.XNode.ElementsAfterSelf(), System.Xml.Linq.XNodeReader.IsEndElement, System.Xml.Linq.XNodeReader.IsInteractive, System.item, System.Xml.Linq.XNodeReader.MoveToElement(), and System.Xml.Linq.XNodeReader.ReadToEnd().