Terraria: System.Xml.Linq.XNodeReader.ReadOverNode
ReadOverNode()
bool System.Xml.Linq.XNodeReader.ReadOverNode (XNode n) inline private
Definition at line 1133 of file XNodeReader.cs.
    {
        if (n == _root)
        {
            return ReadToEnd();
        }
        XNode next = n.next;
        if (next == null || next == n || n == n.parent.content)
        {
            if (n.parent == null || (n.parent.parent == null && n.parent is XDocument))
            {
                return ReadToEnd();
            }
            _source = n.parent;
            IsEndElement = true;
        }
        else
        {
            _source = next;
            IsEndElement = false;
        }
        return true;
    }
References System.Xml.Linq.XNodeReader._root, System.Xml.Linq.XNodeReader._source, System.Xml.Linq.XContainer.content, System.Xml.Dictionary, System.Xml.Linq.XNodeReader.IsEndElement, System.Xml.Linq.XNode.next, System.Xml.Linq.XObject.parent, and System.Xml.Linq.XNodeReader.ReadToEnd().
Referenced by System.Xml.Linq.XNodeReader.Read(), and System.Xml.Linq.XNodeReader.ReadOverAttribute().