Terraria: System.Xml.Linq.XNodeReader.Read
Read() [2/2]
bool System.Xml.Linq.XNodeReader.Read (bool skipContent) inline private
Definition at line 1051 of file XNodeReader.cs.
    {
        if (_source is XElement xElement)
        {
            if (xElement.IsEmpty || IsEndElement || skipContent)
            {
                return ReadOverNode(xElement);
            }
            return ReadIntoElement(xElement);
        }
        if (_source is XNode n)
        {
            return ReadOverNode(n);
        }
        if (_source is XAttribute a)
        {
            return ReadOverAttribute(a, skipContent);
        }
        return ReadOverText(skipContent);
    }
References System.Xml.Linq.XNodeReader._source, System.Xml.Dictionary, System.Xml.Linq.XNodeReader.IsEndElement, System.Xml.Linq.XNodeReader.ReadIntoElement(), System.Xml.Linq.XNodeReader.ReadOverAttribute(), System.Xml.Linq.XNodeReader.ReadOverNode(), and System.Xml.Linq.XNodeReader.ReadOverText().