Terraria: System.Xml.Linq.XNodeReader.ReadIntoElement
ReadIntoElement()
bool System.Xml.Linq.XNodeReader.ReadIntoElement (XElement e) inline private
Definition at line 1088 of file XNodeReader.cs.
    {
        if (e.content is XNode xNode)
        {
            _source = xNode.next;
            return true;
        }
        if (e.content is string text)
        {
            if (text.Length > 0)
            {
                _source = text;
                _parent = e;
            }
            else
            {
                _source = e;
                IsEndElement = true;
            }
            return true;
        }
        return ReadToEnd();
    }
References System.Xml.Linq.XNodeReader._parent, System.Xml.Linq.XNodeReader._source, System.Xml.Linq.XContainer.content, System.Xml.Dictionary, System.Xml.Linq.XNodeReader.IsEndElement, System.Xml.Linq.XNodeReader.ReadToEnd(), and System.text.
Referenced by System.Xml.Linq.XNodeReader.Read(), and System.Xml.Linq.XNodeReader.ReadOverAttribute().