Terraria: WindowsMessageHook.WndProc
WndProc()
IntPtr WindowsMessageHook.WndProc (IntPtr hWnd, int msg, IntPtr wParam, IntPtr lParam) inline private
     {
         Message message = Message.Create(hWnd, msg, wParam, lParam);
         if (InternalWndProc(ref message))
         {
             return message.Result;
         }
         return NativeMethods.CallWindowProc(_previousWndProc, message.HWnd, message.Msg, message.WParam, message.LParam);
     }
References _previousWndProc, NativeMethods.CallWindowProc(), Message.Create(), Message.HWnd, InternalWndProc(), Message.LParam, Message.Msg, Message.Result, and Message.WParam.
Referenced by WindowsMessageHook().