Terraria: System.Security.Cryptography.AsymmetricAlgorithm.ExportArray
ExportArray()
static unsafe byte[] System.Security.Cryptography.AsymmetricAlgorithm.ExportArray (TryExport exporter) inline static private inherited
Definition at line 200 of file AsymmetricAlgorithm.cs.
    {
        int minimumLength = 4096;
        while (true)
        {
            byte[] array = CryptoPool.Rent(minimumLength);
            int bytesWritten = 0;
            minimumLength = array.Length;
            fixed (byte* ptr = array)
            {
                try
                {
                    if (exporter(array, out bytesWritten))
                    {
                        return new Span<byte>(array, 0, bytesWritten).ToArray();
                    }
                }
                finally
                {
                    CryptoPool.Return(array, bytesWritten);
                }
                minimumLength = checked(minimumLength * 2);
            }
        }
    }
References System.array, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), and System.Span< T >.ToArray().
Referenced by System.Security.Cryptography.AsymmetricAlgorithm.ExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.AsymmetricAlgorithm.ExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.AsymmetricAlgorithm.ExportPkcs8PrivateKey(), and System.Security.Cryptography.AsymmetricAlgorithm.ExportSubjectPublicKeyInfo().