Terraria: System.Xml.Schema.DatatypeImplementation.IsEqual
IsEqual()
override bool System.Xml.Schema.DatatypeImplementation.IsEqual (object o1, object o2) inline package
Definition at line 749 of file DatatypeImplementation.cs.
    {
        return Compare(o1, o2) == 0;
    }
References System.Xml.Schema.DatatypeImplementation.Compare(), and System.Xml.Dictionary.
Referenced by System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileLengthFacet(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMaxExclusiveFacet(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMaxInclusiveFacet(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMaxLengthFacet(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMinExclusiveFacet(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMinInclusiveFacet(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileMinLengthFacet(), and System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileWhitespaceFacet().