Terraria: System.Xml.Schema.DatatypeImplementation.TryParseValue
TryParseValue() [1/2]
override Exception System.Xml.Schema.DatatypeImplementation.TryParseValue (object value, XmlNameTable nameTable, IXmlNamespaceResolver namespaceResolver, out object typedValue) inline package
Definition at line 816 of file DatatypeImplementation.cs.
    {
        Exception ex = null;
        typedValue = null;
        if (value == null)
        {
            return new ArgumentNullException("value");
        }
        if (value is string s)
        {
            return TryParseValue(s, nameTable, namespaceResolver, out typedValue);
        }
        try
        {
            object obj = value;
            if (value.GetType() != ValueType)
            {
                obj = ValueConverter.ChangeType(value, ValueType, namespaceResolver);
            }
            if (!HasLexicalFacets)
            {
                goto IL_008d;
            }
            string parseString = (string)ValueConverter.ChangeType(value, typeof(string), namespaceResolver);
            ex = FacetsChecker.CheckLexicalFacets(ref parseString, this);
            if (ex == null)
            {
                goto IL_008d;
            }
            goto end_IL_002b;
            IL_008d:
            if (!HasValueFacets)
            {
                goto IL_00a8;
            }
            ex = FacetsChecker.CheckValueFacets(obj, this);
            if (ex == null)
            {
                goto IL_00a8;
            }
            goto end_IL_002b;
            IL_00a8:
            typedValue = obj;
            return null;
            end_IL_002b:;
        }
        catch (FormatException ex2)
        {
            ex = ex2;
        }
        catch (InvalidCastException ex3)
        {
            ex = ex3;
        }
        catch (OverflowException ex4)
        {
            ex = ex4;
        }
        catch (ArgumentException ex5)
        {
            ex = ex5;
        }
        return ex;
    }
References System.Xml.Schema.XmlValueConverter.ChangeType(), System.Xml.Schema.FacetsChecker.CheckLexicalFacets(), System.Xml.Schema.FacetsChecker.CheckValueFacets(), System.Xml.Dictionary, System.Xml.Schema.DatatypeImplementation.HasLexicalFacets, System.Xml.Schema.DatatypeImplementation.HasValueFacets, System.obj, System.s, System.Xml.Schema.DatatypeImplementation.TryParseValue(), System.value, and System.Xml.Schema.DatatypeImplementation.ValueConverter.
Referenced by System.Xml.Schema.DatatypeImplementation.ParseValue(), System.Xml.Schema.DatatypeImplementation.ParseValue(), System.Xml.Schema.DatatypeImplementation.TryParseValue(), and System.Xml.Schema.Datatype_List.TryParseValue().