Terraria: System.Xml.Schema.DatatypeImplementation.Compare
Compare() [1/2]
int System.Xml.Schema.DatatypeImplementation.Compare (byte[] value1, byte[] value2) inline protected
Definition at line 891 of file DatatypeImplementation.cs.
    {
        int num = value1.Length;
        if (num != value2.Length)
        {
            return -1;
        }
        for (int i = 0; i < num; i++)
        {
            if (value1[i] != value2[i])
            {
                return -1;
            }
        }
        return 0;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.Schema.FacetsChecker.FacetsCompiler.CheckValue(), System.Xml.Schema.Datatype_List.Compare(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileFacetCombinations(), and System.Xml.Schema.DatatypeImplementation.IsEqual().