Terraria: System.Xml.Schema.DatatypeImplementation.DatatypeImplementation
DatatypeImplementation()
static System.Xml.Schema.DatatypeImplementation.DatatypeImplementation () inline static private
Definition at line 289 of file DatatypeImplementation.cs.
    {
        s_builtinTypes = new Hashtable();
        s_enumToTypeCode = new XmlSchemaSimpleType[55];
        s__anySimpleType = null;
        s__anyAtomicType = null;
        s__untypedAtomicType = null;
        s_yearMonthDurationType = null;
        s_dayTimeDurationType = null;
        QnAnySimpleType = new XmlQualifiedName("anySimpleType", "http://www.w3.org/2001/XMLSchema");
        QnAnyType = new XmlQualifiedName("anyType", "http://www.w3.org/2001/XMLSchema");
        stringFacetsChecker = new StringFacetsChecker();
        miscFacetsChecker = new MiscFacetsChecker();
        numeric2FacetsChecker = new Numeric2FacetsChecker();
        binaryFacetsChecker = new BinaryFacetsChecker();
        dateTimeFacetsChecker = new DateTimeFacetsChecker();
        durationFacetsChecker = new DurationFacetsChecker();
        listFacetsChecker = new ListFacetsChecker();
        qnameFacetsChecker = new QNameFacetsChecker();
        unionFacetsChecker = new UnionFacetsChecker();
        s_anySimpleType = new Datatype_anySimpleType();
        s_anyURI = new Datatype_anyURI();
        s_base64Binary = new Datatype_base64Binary();
        s_boolean = new Datatype_boolean();
        s_byte = new Datatype_byte();
        s_char = new Datatype_char();
        s_date = new Datatype_date();
        s_dateTime = new Datatype_dateTime();
        s_dateTimeNoTz = new Datatype_dateTimeNoTimeZone();
        s_dateTimeTz = new Datatype_dateTimeTimeZone();
        s_day = new Datatype_day();
        s_decimal = new Datatype_decimal();
        s_double = new Datatype_double();
        s_doubleXdr = new Datatype_doubleXdr();
        s_duration = new Datatype_duration();
        s_ENTITY = new Datatype_ENTITY();
        s_ENTITIES = (DatatypeImplementation)s_ENTITY.DeriveByList(1, null);
        s_ENUMERATION = new Datatype_ENUMERATION();
        s_fixed = new Datatype_fixed();
        s_float = new Datatype_float();
        s_floatXdr = new Datatype_floatXdr();
        s_hexBinary = new Datatype_hexBinary();
        s_ID = new Datatype_ID();
        s_IDREF = new Datatype_IDREF();
        s_IDREFS = (DatatypeImplementation)s_IDREF.DeriveByList(1, null);
        s_int = new Datatype_int();
        s_integer = new Datatype_integer();
        s_language = new Datatype_language();
        s_long = new Datatype_long();
        s_month = new Datatype_month();
        s_monthDay = new Datatype_monthDay();
        s_name = new Datatype_Name();
        s_NCName = new Datatype_NCName();
        s_negativeInteger = new Datatype_negativeInteger();
        s_NMTOKEN = new Datatype_NMTOKEN();
        s_NMTOKENS = (DatatypeImplementation)s_NMTOKEN.DeriveByList(1, null);
        s_nonNegativeInteger = new Datatype_nonNegativeInteger();
        s_nonPositiveInteger = new Datatype_nonPositiveInteger();
        s_normalizedString = new Datatype_normalizedString();
        s_NOTATION = new Datatype_NOTATION();
        s_positiveInteger = new Datatype_positiveInteger();
        s_QName = new Datatype_QName();
        s_QNameXdr = new Datatype_QNameXdr();
        s_short = new Datatype_short();
        s_string = new Datatype_string();
        s_time = new Datatype_time();
        s_timeNoTz = new Datatype_timeNoTimeZone();
        s_timeTz = new Datatype_timeTimeZone();
        s_token = new Datatype_token();
        s_unsignedByte = new Datatype_unsignedByte();
        s_unsignedInt = new Datatype_unsignedInt();
        s_unsignedLong = new Datatype_unsignedLong();
        s_unsignedShort = new Datatype_unsignedShort();
        s_uuid = new Datatype_uuid();
        s_year = new Datatype_year();
        s_yearMonth = new Datatype_yearMonth();
        c_normalizedStringV1Compat = new Datatype_normalizedStringV1Compat();
        c_tokenV1Compat = new Datatype_tokenV1Compat();
        s_anyAtomicType = new Datatype_anyAtomicType();
        s_dayTimeDuration = new Datatype_dayTimeDuration();
        s_untypedAtomicType = new Datatype_untypedAtomicType();
        s_yearMonthDuration = new Datatype_yearMonthDuration();
        s_tokenizedTypes = new DatatypeImplementation[13]
        {
            s_string, s_ID, s_IDREF, s_IDREFS, s_ENTITY, s_ENTITIES, s_NMTOKEN, s_NMTOKENS, s_NOTATION, s_ENUMERATION,
            s_QNameXdr, s_NCName, null
        };
        s_tokenizedTypesXsd = new DatatypeImplementation[13]
        {
            s_string, s_ID, s_IDREF, s_IDREFS, s_ENTITY, s_ENTITIES, s_NMTOKEN, s_NMTOKENS, s_NOTATION, s_ENUMERATION,
            s_QName, s_NCName, null
        };
        s_xdrTypes = new SchemaDatatypeMap[38]
        {
            new SchemaDatatypeMap("bin.base64", s_base64Binary),
            new SchemaDatatypeMap("bin.hex", s_hexBinary),
            new SchemaDatatypeMap("boolean", s_boolean),
            new SchemaDatatypeMap("char", s_char),
            new SchemaDatatypeMap("date", s_date),
            new SchemaDatatypeMap("dateTime", s_dateTimeNoTz),
            new SchemaDatatypeMap("dateTime.tz", s_dateTimeTz),
            new SchemaDatatypeMap("decimal", s_decimal),
            new SchemaDatatypeMap("entities", s_ENTITIES),
            new SchemaDatatypeMap("entity", s_ENTITY),
            new SchemaDatatypeMap("enumeration", s_ENUMERATION),
            new SchemaDatatypeMap("fixed.14.4", s_fixed),
            new SchemaDatatypeMap("float", s_doubleXdr),
            new SchemaDatatypeMap("float.ieee.754.32", s_floatXdr),
            new SchemaDatatypeMap("float.ieee.754.64", s_doubleXdr),
            new SchemaDatatypeMap("i1", s_byte),
            new SchemaDatatypeMap("i2", s_short),
            new SchemaDatatypeMap("i4", s_int),
            new SchemaDatatypeMap("i8", s_long),
            new SchemaDatatypeMap("id", s_ID),
            new SchemaDatatypeMap("idref", s_IDREF),
            new SchemaDatatypeMap("idrefs", s_IDREFS),
            new SchemaDatatypeMap("int", s_int),
            new SchemaDatatypeMap("nmtoken", s_NMTOKEN),
            new SchemaDatatypeMap("nmtokens", s_NMTOKENS),
            new SchemaDatatypeMap("notation", s_NOTATION),
            new SchemaDatatypeMap("number", s_doubleXdr),
            new SchemaDatatypeMap("r4", s_floatXdr),
            new SchemaDatatypeMap("r8", s_doubleXdr),
            new SchemaDatatypeMap("string", s_string),
            new SchemaDatatypeMap("time", s_timeNoTz),
            new SchemaDatatypeMap("time.tz", s_timeTz),
            new SchemaDatatypeMap("ui1", s_unsignedByte),
            new SchemaDatatypeMap("ui2", s_unsignedShort),
            new SchemaDatatypeMap("ui4", s_unsignedInt),
            new SchemaDatatypeMap("ui8", s_unsignedLong),
            new SchemaDatatypeMap("uri", s_anyURI),
            new SchemaDatatypeMap("uuid", s_uuid)
        };
        s_xsdTypes = new SchemaDatatypeMap[45]
        {
            new SchemaDatatypeMap("ENTITIES", s_ENTITIES, 11),
            new SchemaDatatypeMap("ENTITY", s_ENTITY, 11),
            new SchemaDatatypeMap("ID", s_ID, 5),
            new SchemaDatatypeMap("IDREF", s_IDREF, 5),
            new SchemaDatatypeMap("IDREFS", s_IDREFS, 11),
            new SchemaDatatypeMap("NCName", s_NCName, 9),
            new SchemaDatatypeMap("NMTOKEN", s_NMTOKEN, 40),
            new SchemaDatatypeMap("NMTOKENS", s_NMTOKENS, 11),
            new SchemaDatatypeMap("NOTATION", s_NOTATION, 11),
            new SchemaDatatypeMap("Name", s_name, 40),
            new SchemaDatatypeMap("QName", s_QName, 11),
            new SchemaDatatypeMap("anySimpleType", s_anySimpleType, -1),
            new SchemaDatatypeMap("anyURI", s_anyURI, 11),
            new SchemaDatatypeMap("base64Binary", s_base64Binary, 11),
            new SchemaDatatypeMap("boolean", s_boolean, 11),
            new SchemaDatatypeMap("byte", s_byte, 37),
            new SchemaDatatypeMap("date", s_date, 11),
            new SchemaDatatypeMap("dateTime", s_dateTime, 11),
            new SchemaDatatypeMap("decimal", s_decimal, 11),
            new SchemaDatatypeMap("double", s_double, 11),
            new SchemaDatatypeMap("duration", s_duration, 11),
            new SchemaDatatypeMap("float", s_float, 11),
            new SchemaDatatypeMap("gDay", s_day, 11),
            new SchemaDatatypeMap("gMonth", s_month, 11),
            new SchemaDatatypeMap("gMonthDay", s_monthDay, 11),
            new SchemaDatatypeMap("gYear", s_year, 11),
            new SchemaDatatypeMap("gYearMonth", s_yearMonth, 11),
            new SchemaDatatypeMap("hexBinary", s_hexBinary, 11),
            new SchemaDatatypeMap("int", s_int, 31),
            new SchemaDatatypeMap("integer", s_integer, 18),
            new SchemaDatatypeMap("language", s_language, 40),
            new SchemaDatatypeMap("long", s_long, 29),
            new SchemaDatatypeMap("negativeInteger", s_negativeInteger, 34),
            new SchemaDatatypeMap("nonNegativeInteger", s_nonNegativeInteger, 29),
            new SchemaDatatypeMap("nonPositiveInteger", s_nonPositiveInteger, 29),
            new SchemaDatatypeMap("normalizedString", s_normalizedString, 38),
            new SchemaDatatypeMap("positiveInteger", s_positiveInteger, 33),
            new SchemaDatatypeMap("short", s_short, 28),
            new SchemaDatatypeMap("string", s_string, 11),
            new SchemaDatatypeMap("time", s_time, 11),
            new SchemaDatatypeMap("token", s_token, 35),
            new SchemaDatatypeMap("unsignedByte", s_unsignedByte, 44),
            new SchemaDatatypeMap("unsignedInt", s_unsignedInt, 43),
            new SchemaDatatypeMap("unsignedLong", s_unsignedLong, 33),
            new SchemaDatatypeMap("unsignedShort", s_unsignedShort, 42)
        };
        CreateBuiltinTypes();
    }
References System.Xml.Schema.DatatypeImplementation.DatatypeImplementation(), System.Xml.Schema.DatatypeImplementation.binaryFacetsChecker, System.Xml.Schema.DatatypeImplementation.c_normalizedStringV1Compat, System.Xml.Schema.DatatypeImplementation.c_tokenV1Compat, System.Xml.Schema.DatatypeImplementation.CreateBuiltinTypes(), System.Xml.Schema.DatatypeImplementation.dateTimeFacetsChecker, System.Xml.Schema.DatatypeImplementation.durationFacetsChecker, System.Xml.Schema.DatatypeImplementation.listFacetsChecker, System.Xml.Schema.DatatypeImplementation.miscFacetsChecker, System.Xml.Schema.DatatypeImplementation.numeric2FacetsChecker, System.Xml.Schema.DatatypeImplementation.qnameFacetsChecker, System.Xml.Schema.DatatypeImplementation.QnAnySimpleType, System.Xml.Schema.DatatypeImplementation.QnAnyType, System.Xml.Schema.DatatypeImplementation.s__anyAtomicType, System.Xml.Schema.DatatypeImplementation.s__anySimpleType, System.Xml.Schema.DatatypeImplementation.s__untypedAtomicType, System.Xml.Schema.DatatypeImplementation.s_anyAtomicType, System.Xml.Schema.DatatypeImplementation.s_anySimpleType, System.Xml.Schema.DatatypeImplementation.s_anyURI, System.Xml.Schema.DatatypeImplementation.s_base64Binary, System.Xml.Schema.DatatypeImplementation.s_boolean, System.Xml.Schema.DatatypeImplementation.s_builtinTypes, System.Xml.Schema.DatatypeImplementation.s_byte, System.Xml.Schema.DatatypeImplementation.s_char, System.Xml.Schema.DatatypeImplementation.s_date, System.Xml.Schema.DatatypeImplementation.s_dateTime, System.Xml.Schema.DatatypeImplementation.s_dateTimeNoTz, System.Xml.Schema.DatatypeImplementation.s_dateTimeTz, System.Xml.Schema.DatatypeImplementation.s_day, System.Xml.Schema.DatatypeImplementation.s_dayTimeDuration, System.Xml.Schema.DatatypeImplementation.s_dayTimeDurationType, System.Xml.Schema.DatatypeImplementation.s_decimal, System.Xml.Schema.DatatypeImplementation.s_double, System.Xml.Schema.DatatypeImplementation.s_doubleXdr, System.Xml.Schema.DatatypeImplementation.s_duration, System.Xml.Schema.DatatypeImplementation.s_ENTITIES, System.Xml.Schema.DatatypeImplementation.s_ENTITY, System.Xml.Schema.DatatypeImplementation.s_ENUMERATION, System.Xml.Schema.DatatypeImplementation.s_enumToTypeCode, System.Xml.Schema.DatatypeImplementation.s_fixed, System.Xml.Schema.DatatypeImplementation.s_float, System.Xml.Schema.DatatypeImplementation.s_floatXdr, System.Xml.Schema.DatatypeImplementation.s_hexBinary, System.Xml.Schema.DatatypeImplementation.s_ID, System.Xml.Schema.DatatypeImplementation.s_IDREF, System.Xml.Schema.DatatypeImplementation.s_IDREFS, System.Xml.Schema.DatatypeImplementation.s_int, System.Xml.Schema.DatatypeImplementation.s_integer, System.Xml.Schema.DatatypeImplementation.s_language, System.Xml.Schema.DatatypeImplementation.s_long, System.Xml.Schema.DatatypeImplementation.s_month, System.Xml.Schema.DatatypeImplementation.s_monthDay, System.Xml.Schema.DatatypeImplementation.s_name, System.Xml.Schema.DatatypeImplementation.s_NCName, System.Xml.Schema.DatatypeImplementation.s_negativeInteger, System.Xml.Schema.DatatypeImplementation.s_NMTOKEN, System.Xml.Schema.DatatypeImplementation.s_NMTOKENS, System.Xml.Schema.DatatypeImplementation.s_nonNegativeInteger, System.Xml.Schema.DatatypeImplementation.s_nonPositiveInteger, System.Xml.Schema.DatatypeImplementation.s_normalizedString, System.Xml.Schema.DatatypeImplementation.s_NOTATION, System.Xml.Schema.DatatypeImplementation.s_positiveInteger, System.Xml.Schema.DatatypeImplementation.s_QName, System.Xml.Schema.DatatypeImplementation.s_QNameXdr, System.Xml.Schema.DatatypeImplementation.s_short, System.Xml.Schema.DatatypeImplementation.s_string, System.Xml.Schema.DatatypeImplementation.s_time, System.Xml.Schema.DatatypeImplementation.s_timeNoTz, System.Xml.Schema.DatatypeImplementation.s_timeTz, System.Xml.Schema.DatatypeImplementation.s_token, System.Xml.Schema.DatatypeImplementation.s_tokenizedTypes, System.Xml.Schema.DatatypeImplementation.s_tokenizedTypesXsd, System.Xml.Schema.DatatypeImplementation.s_unsignedByte, System.Xml.Schema.DatatypeImplementation.s_unsignedInt, System.Xml.Schema.DatatypeImplementation.s_unsignedLong, System.Xml.Schema.DatatypeImplementation.s_unsignedShort, System.Xml.Schema.DatatypeImplementation.s_untypedAtomicType, System.Xml.Schema.DatatypeImplementation.s_uuid, System.Xml.Schema.DatatypeImplementation.s_xdrTypes, System.Xml.Schema.DatatypeImplementation.s_xsdTypes, System.Xml.Schema.DatatypeImplementation.s_year, System.Xml.Schema.DatatypeImplementation.s_yearMonth, System.Xml.Schema.DatatypeImplementation.s_yearMonthDuration, System.Xml.Schema.DatatypeImplementation.s_yearMonthDurationType, System.Xml.Schema.DatatypeImplementation.stringFacetsChecker, and System.Xml.Schema.DatatypeImplementation.unionFacetsChecker.
Referenced by System.Xml.Schema.DatatypeImplementation.DatatypeImplementation(), and System.Xml.Schema.DatatypeImplementation.DeriveByRestriction().