Terraria: System.Xml.Schema.DatatypeImplementation.CreateBuiltinTypes
CreateBuiltinTypes()
static void System.Xml.Schema.DatatypeImplementation.CreateBuiltinTypes () inline static package
Definition at line 552 of file DatatypeImplementation.cs.
    {
        SchemaDatatypeMap schemaDatatypeMap = s_xsdTypes[11];
        XmlQualifiedName xmlQualifiedName = new XmlQualifiedName(schemaDatatypeMap.Name, "http://www.w3.org/2001/XMLSchema");
        DatatypeImplementation datatypeImplementation = FromTypeName(xmlQualifiedName.Name);
        s__anySimpleType = StartBuiltinType(xmlQualifiedName, datatypeImplementation);
        datatypeImplementation._parentSchemaType = s__anySimpleType;
        s_builtinTypes.Add(xmlQualifiedName, s__anySimpleType);
        for (int i = 0; i < s_xsdTypes.Length; i++)
        {
            if (i != 11)
            {
                schemaDatatypeMap = s_xsdTypes[i];
                xmlQualifiedName = new XmlQualifiedName(schemaDatatypeMap.Name, "http://www.w3.org/2001/XMLSchema");
                datatypeImplementation = FromTypeName(xmlQualifiedName.Name);
                XmlSchemaSimpleType xmlSchemaSimpleType = (XmlSchemaSimpleType)(datatypeImplementation._parentSchemaType = StartBuiltinType(xmlQualifiedName, datatypeImplementation));
                s_builtinTypes.Add(xmlQualifiedName, xmlSchemaSimpleType);
                if (datatypeImplementation._variety == XmlSchemaDatatypeVariety.Atomic)
                {
                    s_enumToTypeCode[(int)datatypeImplementation.TypeCode] = xmlSchemaSimpleType;
                }
            }
        }
        for (int j = 0; j < s_xsdTypes.Length; j++)
        {
            if (j != 11)
            {
                schemaDatatypeMap = s_xsdTypes[j];
                XmlSchemaSimpleType derivedType = (XmlSchemaSimpleType)s_builtinTypes[new XmlQualifiedName(schemaDatatypeMap.Name, "http://www.w3.org/2001/XMLSchema")];
                if (schemaDatatypeMap.ParentIndex == 11)
                {
                    FinishBuiltinType(derivedType, s__anySimpleType);
                    continue;
                }
                XmlSchemaSimpleType baseType = (XmlSchemaSimpleType)s_builtinTypes[new XmlQualifiedName(s_xsdTypes[schemaDatatypeMap.ParentIndex].Name, "http://www.w3.org/2001/XMLSchema")];
                FinishBuiltinType(derivedType, baseType);
            }
        }
        xmlQualifiedName = new XmlQualifiedName("anyAtomicType", "http://www.w3.org/2003/11/xpath-datatypes");
        s__anyAtomicType = StartBuiltinType(xmlQualifiedName, s_anyAtomicType);
        s_anyAtomicType._parentSchemaType = s__anyAtomicType;
        FinishBuiltinType(s__anyAtomicType, s__anySimpleType);
        s_builtinTypes.Add(xmlQualifiedName, s__anyAtomicType);
        s_enumToTypeCode[10] = s__anyAtomicType;
        xmlQualifiedName = new XmlQualifiedName("untypedAtomic", "http://www.w3.org/2003/11/xpath-datatypes");
        s__untypedAtomicType = StartBuiltinType(xmlQualifiedName, s_untypedAtomicType);
        s_untypedAtomicType._parentSchemaType = s__untypedAtomicType;
        FinishBuiltinType(s__untypedAtomicType, s__anyAtomicType);
        s_builtinTypes.Add(xmlQualifiedName, s__untypedAtomicType);
        s_enumToTypeCode[11] = s__untypedAtomicType;
        xmlQualifiedName = new XmlQualifiedName("yearMonthDuration", "http://www.w3.org/2003/11/xpath-datatypes");
        s_yearMonthDurationType = StartBuiltinType(xmlQualifiedName, s_yearMonthDuration);
        s_yearMonthDuration._parentSchemaType = s_yearMonthDurationType;
        FinishBuiltinType(s_yearMonthDurationType, s_enumToTypeCode[17]);
        s_builtinTypes.Add(xmlQualifiedName, s_yearMonthDurationType);
        s_enumToTypeCode[53] = s_yearMonthDurationType;
        xmlQualifiedName = new XmlQualifiedName("dayTimeDuration", "http://www.w3.org/2003/11/xpath-datatypes");
        s_dayTimeDurationType = StartBuiltinType(xmlQualifiedName, s_dayTimeDuration);
        s_dayTimeDuration._parentSchemaType = s_dayTimeDurationType;
        FinishBuiltinType(s_dayTimeDurationType, s_enumToTypeCode[17]);
        s_builtinTypes.Add(xmlQualifiedName, s_dayTimeDurationType);
        s_enumToTypeCode[54] = s_dayTimeDurationType;
    }
References System.Xml.Dictionary, System.Xml.Schema.DatatypeImplementation.FinishBuiltinType(), System.Xml.Schema.DatatypeImplementation.FromTypeName(), System.Xml.Schema.DatatypeImplementation.s__anyAtomicType, System.Xml.Schema.DatatypeImplementation.s__anySimpleType, System.Xml.Schema.DatatypeImplementation.s__untypedAtomicType, System.Xml.Schema.DatatypeImplementation.s_anyAtomicType, System.Xml.Schema.DatatypeImplementation.s_builtinTypes, System.Xml.Schema.DatatypeImplementation.s_dayTimeDuration, System.Xml.Schema.DatatypeImplementation.s_dayTimeDurationType, System.Xml.Schema.DatatypeImplementation.s_enumToTypeCode, System.Xml.Schema.DatatypeImplementation.s_untypedAtomicType, System.Xml.Schema.DatatypeImplementation.s_xsdTypes, System.Xml.Schema.DatatypeImplementation.s_yearMonthDuration, System.Xml.Schema.DatatypeImplementation.s_yearMonthDurationType, and System.Xml.Schema.DatatypeImplementation.StartBuiltinType().
Referenced by System.Xml.Schema.DatatypeImplementation.DatatypeImplementation().