Terraria: System.Xml.Schema.DatatypeImplementation.GetNormalizedStringTypeV1Compat
GetNormalizedStringTypeV1Compat()
static XmlSchemaSimpleType System.Xml.Schema.DatatypeImplementation.GetNormalizedStringTypeV1Compat () inline static package
Definition at line 626 of file DatatypeImplementation.cs.
    {
        if (s_normalizedStringTypeV1Compat == null)
        {
            XmlSchemaSimpleType simpleTypeFromTypeCode = GetSimpleTypeFromTypeCode(XmlTypeCode.NormalizedString);
            XmlSchemaSimpleType xmlSchemaSimpleType = simpleTypeFromTypeCode.Clone() as XmlSchemaSimpleType;
            xmlSchemaSimpleType.SetDatatype(c_normalizedStringV1Compat);
            xmlSchemaSimpleType.ElementDecl = new SchemaElementDecl(c_normalizedStringV1Compat);
            xmlSchemaSimpleType.ElementDecl.SchemaType = xmlSchemaSimpleType;
            s_normalizedStringTypeV1Compat = xmlSchemaSimpleType;
        }
        return s_normalizedStringTypeV1Compat;
    }
References System.Xml.Schema.DatatypeImplementation.c_normalizedStringV1Compat, System.Xml.Schema.XmlSchemaSimpleType.Clone(), System.Xml.Dictionary, System.Xml.Schema.DatatypeImplementation.GetSimpleTypeFromTypeCode(), System.Xml.Schema.DatatypeImplementation.s_normalizedStringTypeV1Compat, and System.Xml.Schema.XmlSchemaType.SetDatatype().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.GetSimpleType().