Terraria: System.Data.Common.ObjectStorage.CompareTo
CompareTo()
int System.Data.Common.ObjectStorage.CompareTo (object valueNo1, object valueNo2) inline private
Definition at line 131 of file ObjectStorage.cs.
    {
        if (valueNo1 == null)
        {
            return -1;
        }
        if (valueNo2 == null)
        {
            return 1;
        }
        if (valueNo1 == valueNo2)
        {
            return 0;
        }
        if (valueNo1 == _nullValue)
        {
            return -1;
        }
        if (valueNo2 == _nullValue)
        {
            return 1;
        }
        if (valueNo1 is IComparable)
        {
            try
            {
                return ((IComparable)valueNo1).CompareTo(valueNo2);
            }
            catch (ArgumentException e)
            {
                ExceptionBuilder.TraceExceptionWithoutRethrow(e);
            }
        }
        return CompareWithFamilies(valueNo1, valueNo2);
    }
References System.Data.Common.DataStorage._nullValue, System.Data.Common.ObjectStorage.CompareWithFamilies(), and System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow().
Referenced by System.Data.Common.ObjectStorage.CompareWithFamilies().