Terraria: System.Data.Common.ObjectStorage.CompareWithFamilies
CompareWithFamilies()
int System.Data.Common.ObjectStorage.CompareWithFamilies (object valueNo1, object valueNo2) inline private
Definition at line 167 of file ObjectStorage.cs.
    {
        Families family = GetFamily(valueNo1.GetType());
        Families family2 = GetFamily(valueNo2.GetType());
        if (family < family2)
        {
            return -1;
        }
        if (family > family2)
        {
            return 1;
        }
        switch (family)
        {
        case Families.BOOLEAN:
            valueNo1 = Convert.ToBoolean(valueNo1, base.FormatProvider);
            valueNo2 = Convert.ToBoolean(valueNo2, base.FormatProvider);
            break;
        case Families.DATETIME:
            valueNo1 = Convert.ToDateTime(valueNo1, base.FormatProvider);
            valueNo2 = Convert.ToDateTime(valueNo1, base.FormatProvider);
            break;
        case Families.NUMBER:
            valueNo1 = Convert.ToDouble(valueNo1, base.FormatProvider);
            valueNo2 = Convert.ToDouble(valueNo2, base.FormatProvider);
            break;
        case Families.ARRAY:
        {
            Array array = (Array)valueNo1;
            Array array2 = (Array)valueNo2;
            if (array.Length > array2.Length)
            {
                return 1;
            }
            if (array.Length < array2.Length)
            {
                return -1;
            }
            for (int i = 0; i < array.Length; i++)
            {
                int num = CompareTo(array.GetValue(i), array2.GetValue(i));
                if (num != 0)
                {
                    return num;
                }
            }
            return 0;
        }
        default:
            valueNo1 = valueNo1.ToString();
            valueNo2 = valueNo2.ToString();
            break;
        }
        return ((IComparable)valueNo1).CompareTo(valueNo2);
    }
References System.array, System.Xml.Array, System.Data.Common.ObjectStorage.CompareTo(), System.Data.Common.ObjectStorage.GetFamily(), System.Convert.ToBoolean(), System.Convert.ToDateTime(), and System.Convert.ToDouble().
Referenced by System.Data.Common.ObjectStorage.Compare(), System.Data.Common.ObjectStorage.CompareTo(), and System.Data.Common.ObjectStorage.CompareValueTo().