Terraria: System.Data.Common.ObjectStorage.ConvertXmlToObject
ConvertXmlToObject() [2/2]
override object System.Data.Common.ObjectStorage.ConvertXmlToObject (XmlReader xmlReader, XmlRootAttribute xmlAttrib) inline virtual
Reimplemented from System.Data.Common.DataStorage.
Definition at line 411 of file ObjectStorage.cs.
    {
        object obj = null;
        bool flag = false;
        bool flag2 = false;
        if (xmlAttrib == null)
        {
            Type type = null;
            string attribute = xmlReader.GetAttribute("InstanceType", "urn:schemas-microsoft-com:xml-msdata");
            if (attribute == null || attribute.Length == 0)
            {
                string text = xmlReader.GetAttribute("type", "http://www.w3.org/2001/XMLSchema-instance");
                if (text != null && text.Length > 0)
                {
                    string[] array = text.Split(':');
                    if (array.Length == 2 && xmlReader.LookupNamespace(array[0]) == "http://www.w3.org/2001/XMLSchema")
                    {
                        text = array[1];
                    }
                    type = XSDSchema.XsdtoClr(text);
                    flag = true;
                }
                else if (_dataType == typeof(object))
                {
                    flag2 = true;
                }
            }
            if (flag2)
            {
                obj = xmlReader.ReadString();
            }
            else if (attribute == "Type")
            {
                obj = Type.GetType(xmlReader.ReadString());
                xmlReader.Read();
            }
            else
            {
                if (null == type)
                {
                    type = ((attribute == null) ? _dataType : DataStorage.GetType(attribute));
                }
                if (type == typeof(char) || type == typeof(Guid))
                {
                    flag = true;
                }
                if (type == typeof(object))
                {
                    throw ExceptionBuilder.CanNotDeserializeObjectType();
                }
                TypeLimiter.EnsureTypeIsAllowed(type);
                if (!flag)
                {
                    obj = Activator.CreateInstance(type, nonPublic: true);
                    ((IXmlSerializable)obj).ReadXml(xmlReader);
                }
                else
                {
                    if (type == typeof(string) && xmlReader.NodeType == XmlNodeType.Element && xmlReader.IsEmptyElement)
                    {
                        obj = string.Empty;
                    }
                    else
                    {
                        obj = xmlReader.ReadString();
                        obj = ((!(type != typeof(byte[]))) ? Convert.FromBase64String(obj.ToString()) : SqlConvert.ChangeTypeForXML(obj, type));
                    }
                    xmlReader.Read();
                }
            }
        }
        else
        {
            XmlSerializer xmlSerializer = GetXmlSerializer(_dataType, xmlAttrib);
            obj = xmlSerializer.Deserialize(xmlReader);
        }
        return obj;
    }
References System.Data.Common.DataStorage._dataType, System.array, System.Data.ExceptionBuilder.CanNotDeserializeObjectType(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Activator.CreateInstance(), System.Xml.Dictionary, System.Data.TypeLimiter.EnsureTypeIsAllowed(), System.Convert.FromBase64String(), System.Type.GetType(), System.Data.Common.DataStorage.GetType(), System.Data.Common.ObjectStorage.GetXmlSerializer(), System.obj, System.text, System.type, and System.Data.XSDSchema.XsdtoClr().