Terraria: System.Data.Common.ObjectStorage.ConvertXmlToObject
ConvertXmlToObject() [1/2]
override object System.Data.Common.ObjectStorage.ConvertXmlToObject (string s) inline
Definition at line 377 of file ObjectStorage.cs.
    {
        Type dataType = _dataType;
        if (dataType == typeof(byte[]))
        {
            return Convert.FromBase64String(s);
        }
        if (dataType == typeof(Type))
        {
            return Type.GetType(s);
        }
        if (dataType == typeof(Guid))
        {
            return new Guid(s);
        }
        if (dataType == typeof(Uri))
        {
            return new Uri(s);
        }
        if (_implementsIXmlSerializable)
        {
            object obj = Activator.CreateInstance(_dataType, nonPublic: true);
            StringReader input = new StringReader(s);
            using XmlTextReader reader = new XmlTextReader(input);
            ((IXmlSerializable)obj).ReadXml(reader);
            return obj;
        }
        StringReader textReader = new StringReader(s);
        XmlSerializer xmlSerializer = GetXmlSerializer(dataType);
        return xmlSerializer.Deserialize(textReader);
    }
References System.Data.Common.DataStorage._dataType, System.Data.Common.ObjectStorage._implementsIXmlSerializable, System.Activator.CreateInstance(), System.Xml.Dictionary, System.Convert.FromBase64String(), System.Type.GetType(), System.Data.Common.ObjectStorage.GetXmlSerializer(), System.Data.Common.Guid, System.input, System.obj, System.s, and System.Data.Common.Uri.