Terraria: System.Data.Common.ObjectStorage.Set
Set()
override void System.Data.Common.ObjectStorage.Set (int recordNo, object value) inline
Definition at line 290 of file ObjectStorage.cs.
    {
        if (_nullValue == value)
        {
            _values[recordNo] = null;
            return;
        }
        if (_dataType == typeof(object) || _dataType.IsInstanceOfType(value))
        {
            _values[recordNo] = value;
            return;
        }
        Type type = value.GetType();
        if (_dataType == typeof(Guid) && type == typeof(string))
        {
            _values[recordNo] = new Guid((string)value);
            return;
        }
        if (_dataType == typeof(byte[]))
        {
            if (type == typeof(bool))
            {
                _values[recordNo] = BitConverter.GetBytes((bool)value);
                return;
            }
            if (type == typeof(char))
            {
                _values[recordNo] = BitConverter.GetBytes((char)value);
                return;
            }
            if (type == typeof(short))
            {
                _values[recordNo] = BitConverter.GetBytes((short)value);
                return;
            }
            if (type == typeof(int))
            {
                _values[recordNo] = BitConverter.GetBytes((int)value);
                return;
            }
            if (type == typeof(long))
            {
                _values[recordNo] = BitConverter.GetBytes((long)value);
                return;
            }
            if (type == typeof(ushort))
            {
                _values[recordNo] = BitConverter.GetBytes((ushort)value);
                return;
            }
            if (type == typeof(uint))
            {
                _values[recordNo] = BitConverter.GetBytes((uint)value);
                return;
            }
            if (type == typeof(ulong))
            {
                _values[recordNo] = BitConverter.GetBytes((ulong)value);
                return;
            }
            if (type == typeof(float))
            {
                _values[recordNo] = BitConverter.GetBytes((float)value);
                return;
            }
            if (type == typeof(double))
            {
                _values[recordNo] = BitConverter.GetBytes((double)value);
                return;
            }
            throw ExceptionBuilder.StorageSetFailed();
        }
        throw ExceptionBuilder.StorageSetFailed();
    }
References System.Data.Common.DataStorage._dataType, System.Data.Common.DataStorage._nullValue, System.Data.Common.ObjectStorage._values, System.Xml.Dictionary, System.BitConverter.GetBytes(), System.Type.GetType(), System.Data.Common.Guid, System.Type.IsInstanceOfType(), System.Data.ExceptionBuilder.StorageSetFailed(), System.type, and System.value.