Terraria: System.Data.Common.ObjectStorage.ConvertObjectToXml
ConvertObjectToXml() [1/2]
override string System.Data.Common.ObjectStorage.ConvertObjectToXml (object value) inline
Definition at line 491 of file ObjectStorage.cs.
    {
        if (value == null || value == _nullValue)
        {
            return string.Empty;
        }
        Type dataType = _dataType;
        if (dataType == typeof(byte[]) || (dataType == typeof(object) && value is byte[]))
        {
            return Convert.ToBase64String((byte[])value);
        }
        if (dataType == typeof(Type) || (dataType == typeof(object) && value is Type))
        {
            return ((Type)value).AssemblyQualifiedName;
        }
        if (!DataStorage.IsTypeCustomType(value.GetType()))
        {
            return (string)SqlConvert.ChangeTypeForXML(value, typeof(string));
        }
        if (Type.GetTypeCode(value.GetType()) != TypeCode.Object)
        {
            return value.ToString();
        }
        StringWriter stringWriter = new StringWriter(base.FormatProvider);
        if (_implementsIXmlSerializable)
        {
            using (XmlTextWriter writer = new XmlTextWriter(stringWriter))
            {
                ((IXmlSerializable)value).WriteXml(writer);
            }
            return stringWriter.ToString();
        }
        XmlSerializer xmlSerializer = GetXmlSerializer(value.GetType());
        xmlSerializer.Serialize(stringWriter, value);
        return stringWriter.ToString();
    }
References System.Data.Common.DataStorage._dataType, System.Data.Common.ObjectStorage._implementsIXmlSerializable, System.Data.Common.DataStorage._nullValue, System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Xml.Dictionary, System.Type.GetTypeCode(), System.Data.Common.ObjectStorage.GetXmlSerializer(), System.Data.Common.DataStorage.IsTypeCustomType(), System.Convert.ToBase64String(), System.value, and System.writer.