Terraria: System.Data.Common.ObjectStorage.GetXmlSerializer
GetXmlSerializer() [1/2]
static XmlSerializer System.Data.Common.ObjectStorage.GetXmlSerializer (Type type) inline static package
Definition at line 578 of file ObjectStorage.cs.
    {
        VerifyIDynamicMetaObjectProvider(type);
        return s_serializerFactory.CreateSerializer(type);
    }
References System.Data.Common.ObjectStorage.s_serializerFactory, System.type, and System.Data.Common.ObjectStorage.VerifyIDynamicMetaObjectProvider().
Referenced by System.Data.Common.ObjectStorage.ConvertObjectToXml(), System.Data.Common.SqlUdtStorage.ConvertObjectToXml(), System.Data.Common.ObjectStorage.ConvertObjectToXml(), System.Data.Common.SqlUdtStorage.ConvertObjectToXml(), System.Data.Common.ObjectStorage.ConvertXmlToObject(), System.Data.Common.SqlUdtStorage.ConvertXmlToObject(), System.Data.Common.ObjectStorage.ConvertXmlToObject(), and System.Data.Common.SqlUdtStorage.ConvertXmlToObject().