Terraria: System.DateTimeOffset.ValidateDate
ValidateDate()
static DateTime System.DateTimeOffset.ValidateDate (DateTime dateTime, TimeSpan offset) inline static private
Definition at line 623 of file DateTimeOffset.cs.
    {
        long num = dateTime.Ticks - offset.Ticks;
        if (num < 0 || num > 3155378975999999999L)
        {
            throw new ArgumentOutOfRangeException("offset", SR.Argument_UTCOutOfRange);
        }
        return new DateTime(num, DateTimeKind.Unspecified);
    }
References System.SR.Argument_UTCOutOfRange, System.DateTimeOffset.DateTime, System.Runtime.Serialization.Dictionary, System.L, and System.offset.
Referenced by System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), and System.DateTimeOffset.OnDeserialization().