Terraria: System.DateTimeOffset.ParseExact
ParseExact() [2/5]
static DateTimeOffset System.DateTimeOffset.ParseExact (ReadOnlySpan< char > input, string[] formats, IFormatProvider? formatProvider, DateTimeStyles styles = DateTimeStyles::None) inline static
Definition at line 427 of file DateTimeOffset.cs.
    {
        styles = ValidateStyles(styles, "styles");
        TimeSpan offset;
        return new DateTimeOffset(DateTimeParse.ParseExactMultiple(input, formats, DateTimeFormatInfo.GetInstance(formatProvider), styles, out offset).Ticks, offset);
    }
References System.DateTimeOffset.DateTimeOffset(), System.Runtime.Serialization.Dictionary, System.formats, System.input, System.offset, System.DateTimeParse.ParseExactMultiple(), and System.DateTimeOffset.ValidateStyles().