Terraria: System.DateTimeOffset.ValidateStyles
ValidateStyles()
static DateTimeStyles System.DateTimeOffset.ValidateStyles (DateTimeStyles style, string parameterName) inline static private
Definition at line 633 of file DateTimeOffset.cs.
    {
        if (((uint)style & 0xFFFFFF00u) != 0)
        {
            throw new ArgumentException(SR.Argument_InvalidDateTimeStyles, parameterName);
        }
        if ((style & DateTimeStyles.AssumeLocal) != 0 && (style & DateTimeStyles.AssumeUniversal) != 0)
        {
            throw new ArgumentException(SR.Argument_ConflictingDateTimeStyles, parameterName);
        }
        if ((style & DateTimeStyles.NoCurrentDateDefault) != 0)
        {
            throw new ArgumentException(SR.Argument_DateTimeOffsetInvalidDateTimeStyles, parameterName);
        }
        style &= ~DateTimeStyles.RoundtripKind;
        style &= ~DateTimeStyles.AssumeLocal;
        return style;
    }
References System.SR.Argument_ConflictingDateTimeStyles, System.SR.Argument_DateTimeOffsetInvalidDateTimeStyles, System.SR.Argument_InvalidDateTimeStyles, and System.Runtime.Serialization.Dictionary.
Referenced by System.DateTimeOffset.Parse(), System.DateTimeOffset.Parse(), System.DateTimeOffset.ParseExact(), System.DateTimeOffset.ParseExact(), System.DateTimeOffset.ParseExact(), System.DateTimeOffset.ParseExact(), System.DateTimeOffset.TryParse(), System.DateTimeOffset.TryParse(), System.DateTimeOffset.TryParseExact(), System.DateTimeOffset.TryParseExact(), System.DateTimeOffset.TryParseExact(), and System.DateTimeOffset.TryParseExact().