Terraria: System.DateTimeOffset.DateTimeOffset
DateTimeOffset() [1/8]
System.DateTimeOffset.DateTimeOffset (short validOffsetMinutes, DateTime validDateTime) inline private
Definition at line 81 of file DateTimeOffset.cs.
    {
        _dateTime = validDateTime;
        _offsetMinutes = validOffsetMinutes;
    }
References System.DateTimeOffset._dateTime, System.DateTimeOffset._offsetMinutes, and System.Runtime.Serialization.Dictionary.
Referenced by System.DateTimeOffset.Add(), System.DateTimeOffset.AddDays(), System.DateTimeOffset.AddHours(), System.DateTimeOffset.AddMilliseconds(), System.DateTimeOffset.AddMinutes(), System.DateTimeOffset.AddMonths(), System.DateTimeOffset.AddSeconds(), System.DateTimeOffset.AddTicks(), System.DateTimeOffset.AddYears(), System.DateTimeOffset.FromUnixTimeMilliseconds(), System.DateTimeOffset.FromUnixTimeSeconds(), System.DateTimeOffset.operator DateTimeOffset(), System.DateTimeOffset.operator+(), System.DateTimeOffset.operator-(), System.DateTimeOffset.Parse(), System.DateTimeOffset.Parse(), System.DateTimeOffset.Parse(), System.DateTimeOffset.ParseExact(), System.DateTimeOffset.ParseExact(), System.DateTimeOffset.ParseExact(), System.DateTimeOffset.ParseExact(), System.DateTimeOffset.Subtract(), System.DateTimeOffset.ToLocalTime(), System.DateTimeOffset.ToOffset(), System.DateTimeOffset.ToUniversalTime(), System.DateTimeOffset.TryParse(), System.DateTimeOffset.TryParse(), System.DateTimeOffset.TryParse(), System.DateTimeOffset.TryParse(), System.DateTimeOffset.TryParseExact(), System.DateTimeOffset.TryParseExact(), System.DateTimeOffset.TryParseExact(), and System.DateTimeOffset.TryParseExact().