Terraria: System.DateTimeOffset.ParseExact
ParseExact() [3/5]
static DateTimeOffset System.DateTimeOffset.ParseExact (string input, string format, IFormatProvider? formatProvider) inline static
Definition at line 381 of file DateTimeOffset.cs.
    {
        if (input == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.input);
        }
        if (format == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.format);
        }
        return ParseExact(input, format, formatProvider, DateTimeStyles.None);
    }
References System.Runtime.Serialization.Dictionary, System.format, System.input, System.DateTimeOffset.ParseExact(), and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.DateTimeOffset.ParseExact(), System.Xml.XmlConvert.ToDateTimeOffset(), and System.Xml.XmlConvert.ToDateTimeOffset().