Terraria: System.DateTimeOffset.DateTimeOffset
DateTimeOffset() [5/8]
System.DateTimeOffset.DateTimeOffset (int year, int month, int day, int hour, int minute, int second, TimeSpan offset) inline
Definition at line 116 of file DateTimeOffset.cs.
    {
        _offsetMinutes = ValidateOffset(offset);
        int num = second;
        if (second == 60 && DateTime.s_systemSupportsLeapSeconds)
        {
            second = 59;
        }
        _dateTime = ValidateDate(new DateTime(year, month, day, hour, minute, second), offset);
        if (num == 60 && !DateTime.IsValidTimeWithLeapSeconds(_dateTime.Year, _dateTime.Month, _dateTime.Day, _dateTime.Hour, _dateTime.Minute, DateTimeKind.Utc))
        {
            throw new ArgumentOutOfRangeException(null, SR.ArgumentOutOfRange_BadHourMinuteSecond);
        }
    }
References System.DateTimeOffset._dateTime, System.DateTimeOffset._offsetMinutes, System.SR.ArgumentOutOfRange_BadHourMinuteSecond, System.DateTimeOffset.DateTime, System.DateTime.Day, System.DateTime.Hour, System.DateTime.IsValidTimeWithLeapSeconds(), System.DateTime.Minute, System.DateTime.Month, System.offset, System.DateTime.s_systemSupportsLeapSeconds, System.DateTimeOffset.ValidateDate(), System.DateTimeOffset.ValidateOffset(), System.DateTime.Year, and System.year.