Terraria: System.DateTimeOffset.DateTimeOffset
DateTimeOffset() [4/8]
System.DateTimeOffset.DateTimeOffset (DateTime dateTime, TimeSpan offset) inline
Definition at line 99 of file DateTimeOffset.cs.
    {
        if (dateTime.Kind == DateTimeKind.Local)
        {
            if (offset != TimeZoneInfo.GetLocalUtcOffset(dateTime, TimeZoneInfoOptions.NoThrowOnInvalidTime))
            {
                throw new ArgumentException(SR.Argument_OffsetLocalMismatch, "offset");
            }
        }
        else if (dateTime.Kind == DateTimeKind.Utc && offset != TimeSpan.Zero)
        {
            throw new ArgumentException(SR.Argument_OffsetUtcMismatch, "offset");
        }
        _offsetMinutes = ValidateOffset(offset);
        _dateTime = ValidateDate(dateTime, offset);
    }
References System.DateTimeOffset._dateTime, System.DateTimeOffset._offsetMinutes, System.SR.Argument_OffsetLocalMismatch, System.SR.Argument_OffsetUtcMismatch, System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.GetLocalUtcOffset(), System.offset, System.DateTimeOffset.ValidateDate(), System.DateTimeOffset.ValidateOffset(), and System.TimeSpan.Zero.