Terraria: System.DateTimeOffset.TryParseExact
TryParseExact() [2/4]
static bool System.DateTimeOffset.TryParseExact ([NotNullWhen(true)] string? input, [NotNullWhen(true)] string??[] formats, IFormatProvider? formatProvider, DateTimeStyles styles, out DateTimeOffset result) inline static
Definition at line 584 of file DateTimeOffset.cs.
    {
        styles = ValidateStyles(styles, "styles");
        if (input == null)
        {
            result = default(DateTimeOffset);
            return false;
        }
        DateTime result2;
        TimeSpan offset;
        bool result3 = DateTimeParse.TryParseExactMultiple(input, formats, DateTimeFormatInfo.GetInstance(formatProvider), styles, out result2, out offset);
        result = new DateTimeOffset(result2.Ticks, offset);
        return result3;
    }
References System.DateTimeOffset.DateTimeOffset(), System.Runtime.Serialization.Dictionary, System.formats, System.input, System.offset, System.DateTimeParse.TryParseExactMultiple(), and System.DateTimeOffset.ValidateStyles().