Terraria: System.DateTimeOffset.DateTimeOffset
DateTimeOffset() [3/8]
System.DateTimeOffset.DateTimeOffset (DateTime dateTime) inline
Definition at line 92 of file DateTimeOffset.cs.
    {
        TimeSpan offset = ((dateTime.Kind == DateTimeKind.Utc) ? new TimeSpan(0L) : TimeZoneInfo.GetLocalUtcOffset(dateTime, TimeZoneInfoOptions.NoThrowOnInvalidTime));
        _offsetMinutes = ValidateOffset(offset);
        _dateTime = ValidateDate(dateTime, offset);
    }
References System.DateTimeOffset._dateTime, System.DateTimeOffset._offsetMinutes, System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.GetLocalUtcOffset(), System.L, System.offset, System.DateTimeOffset.ValidateDate(), and System.DateTimeOffset.ValidateOffset().