Terraria: System.DateTimeOffset.ToFileTime
ToFileTime()
long System.DateTimeOffset.ToFileTime () inline
Definition at line 444 of file DateTimeOffset.cs.
    {
        return UtcDateTime.ToFileTime();
    }
References System.DateTime.ToFileTime(), and System.DateTimeOffset.UtcDateTime.
Referenced by System.IO.FileSystem.SetCreationTime(), System.IO.FileSystem.SetLastAccessTime(), and System.IO.FileSystem.SetLastWriteTime().