Terraria: System.Security.Cryptography.CryptoConfig.CreateFromName
CreateFromName() [2/2]
static ? object System.Security.Cryptography.CryptoConfig.CreateFromName (string name, params object??[] args) inline static
Definition at line 228 of file CryptoConfig.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        appNameHT.TryGetValue(name, out var value);
        if (value == null && DefaultNameHT.TryGetValue(name, out object value2))
        {
            value = value2 as Type;
            if (value == null && value2 is string typeName)
            {
                value = Type.GetType(typeName, throwOnError: false, ignoreCase: false);
                if (value != null && !value.IsVisible)
                {
                    value = null;
                }
                if (value != null)
                {
                    appNameHT[name] = value;
                }
            }
        }
        if (value == null && (args == null || args.Length == 1) && name == "ECDsa")
        {
            return ECDsa.Create();
        }
        if (value == null)
        {
            value = Type.GetType(name, throwOnError: false, ignoreCase: false);
            if (value != null && !value.IsVisible)
            {
                value = null;
            }
        }
        if (value == null)
        {
            return null;
        }
        MethodBase[] constructors = value.GetConstructors(BindingFlags.Instance | BindingFlags.Public | BindingFlags.CreateInstance);
        MethodBase[] array = constructors;
        if (array == null)
        {
            return null;
        }
        if (args == null)
        {
            args = Array.Empty<object>();
        }
        List<MethodBase> list = new List<MethodBase>();
        foreach (MethodBase methodBase in array)
        {
            if (methodBase.GetParameters().Length == args.Length)
            {
                list.Add(methodBase);
            }
        }
        if (list.Count == 0)
        {
            return null;
        }
        array = list.ToArray();
        object state;
        ConstructorInfo constructorInfo = Type.DefaultBinder.BindToMethod(BindingFlags.Instance | BindingFlags.Public | BindingFlags.CreateInstance, array, ref args, null, null, null, out state) as ConstructorInfo;
        if (constructorInfo == null || typeof(Delegate).IsAssignableFrom(constructorInfo.DeclaringType))
        {
            return null;
        }
        object result = constructorInfo.Invoke(BindingFlags.Instance | BindingFlags.Public | BindingFlags.CreateInstance, Type.DefaultBinder, args, null);
        if (state != null)
        {
            Type.DefaultBinder.ReorderArgumentArray(ref args, state);
        }
        return result;
    }
References System.Security.Cryptography.CryptoConfig.appNameHT, System.array, System.Security.Cryptography.ECDsa.Create(), System.Type.DefaultBinder, System.Security.Cryptography.CryptoConfig.DefaultNameHT, System.Type.GetType(), System.list, System.state, System.Reflection.Type, and System.value.
Referenced by System.Security.Cryptography.DES.Create(), System.Security.Cryptography.DSA.Create(), System.Security.Cryptography.MD5.Create(), System.Security.Cryptography.RC2.Create(), System.Security.Cryptography.Rijndael.Create(), System.Security.Cryptography.RSA.Create(), System.Security.Cryptography.ECDiffieHellman.Create(), System.Security.Cryptography.ECDsa.Create(), System.Security.Cryptography.Aes.Create(), System.Security.Cryptography.SHA1.Create(), System.Security.Cryptography.SHA256.Create(), System.Security.Cryptography.SHA384.Create(), System.Security.Cryptography.SHA512.Create(), System.Security.Cryptography.RandomNumberGenerator.Create(), System.Security.Cryptography.TripleDES.Create(), System.Security.Cryptography.SignatureDescription.CreateDeformatter(), System.Security.Cryptography.SignatureDescription.CreateDigest(), System.Security.Cryptography.SignatureDescription.CreateFormatter(), System.Security.Cryptography.CryptoConfig.CreateFromName(), and System.Security.Cryptography.PKCS1MaskGenerationMethod.GenerateMask().