Terraria: System.Security.Cryptography.CryptoConfig.MapNameToOID
MapNameToOID()
static ? string System.Security.Cryptography.CryptoConfig.MapNameToOID (string name) inline static
Definition at line 339 of file CryptoConfig.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        appOidHT.TryGetValue(name, out var value);
        if (string.IsNullOrEmpty(value) && !DefaultOidHT.TryGetValue(name, out value))
        {
            try
            {
                Oid oid = Oid.FromFriendlyName(name, OidGroup.All);
                value = oid.Value;
                return value;
            }
            catch (CryptographicException)
            {
            }
        }
        return value;
    }
References System.Security.Cryptography.CryptoConfig.appOidHT, System.Security.Cryptography.CryptoConfig.DefaultOidHT, System.Security.Cryptography.Oid.FromFriendlyName(), and System.value.
Referenced by Internal.NativeCrypto.CapiHelper.NameOrOidToHashAlgId(), System.Security.Cryptography.RSAPKCS1SignatureDeformatter.SetHashAlgorithm(), and System.Security.Cryptography.RSAPKCS1SignatureFormatter.SetHashAlgorithm().