Terraria: System.Net.Mail.AttachmentBase.SetContentFromString
SetContentFromString() [2/2]
void System.Net.Mail.AttachmentBase.SetContentFromString (string content, Encoding encoding, string mediaType) inline package inherited
Definition at line 205 of file AttachmentBase.cs.
    {
        if (content == null)
        {
            throw new ArgumentNullException("content");
        }
        if (_part.Stream != null)
        {
            _part.Stream.Close();
        }
        if (string.IsNullOrEmpty(mediaType))
        {
            mediaType = "text/plain";
        }
        int offset = 0;
        try
        {
            string text = MailBnfHelper.ReadToken(mediaType, ref offset, null);
            if (text.Length == 0 || offset >= mediaType.Length || mediaType[offset++] != '/')
            {
                throw new ArgumentException(System.SR.MediaTypeInvalid, "mediaType");
            }
            text = MailBnfHelper.ReadToken(mediaType, ref offset, null);
            if (text.Length == 0 || offset < mediaType.Length)
            {
                throw new ArgumentException(System.SR.MediaTypeInvalid, "mediaType");
            }
        }
        catch (FormatException)
        {
            throw new ArgumentException(System.SR.MediaTypeInvalid, "mediaType");
        }
        ContentType contentType = new ContentType(mediaType);
        if (encoding == null)
        {
            encoding = ((!MimeBasePart.IsAscii(content, permitCROrLF: false)) ? Encoding.GetEncoding("utf-8") : Encoding.ASCII);
        }
        contentType.CharSet = encoding.BodyName;
        byte[] bytes = encoding.GetBytes(content);
        _part.SetContent(new MemoryStream(bytes), contentType);
        if (MimeBasePart.ShouldUseBase64Encoding(encoding))
        {
            _part.TransferEncoding = TransferEncoding.Base64;
        }
        else
        {
            _part.TransferEncoding = TransferEncoding.QuotedPrintable;
        }
    }
References System.Net.Mail.AttachmentBase._part, System.Text.Encoding.ASCII, System.Text.Encoding.BodyName, System.bytes, System.IO.Stream.Close(), System.Net.Mail.AttachmentBase.ContentType, System.Text.Encoding.GetBytes(), System.Text.Encoding.GetEncoding(), System.Net.Mime.MimeBasePart.IsAscii(), System.SR.MediaTypeInvalid, System.offset, System.Net.Mime.MailBnfHelper.ReadToken(), System.Net.Mime.MimePart.SetContent(), System.Net.Mime.MimeBasePart.ShouldUseBase64Encoding(), System.Net.Mime.MimePart.Stream, and System.text.