Terraria: System.Xml.Linq.XContainer.ContentReader.ReadContentFrom
ReadContentFrom() [2/2]
bool System.Xml.Linq.XContainer.ContentReader.ReadContentFrom (XContainer rootContainer, XmlReader r, LoadOptions o) inline
Definition at line 189 of file XContainer.cs.
        {
            XNode xNode = null;
            string baseURI = r.BaseURI;
            switch (r.NodeType)
            {
            case XmlNodeType.Element:
            {
                XElement xElement2 = new XElement(_eCache.Get(r.NamespaceURI).GetName(r.LocalName));
                if (_baseUri != null && _baseUri != baseURI)
                {
                    xElement2.SetBaseUri(baseURI);
                }
                if (_lineInfo != null && _lineInfo.HasLineInfo())
                {
                    xElement2.SetLineInfo(_lineInfo.LineNumber, _lineInfo.LinePosition);
                }
                if (r.MoveToFirstAttribute())
                {
                    do
                    {
                        XAttribute xAttribute = new XAttribute(_aCache.Get((r.Prefix.Length == 0) ? string.Empty : r.NamespaceURI).GetName(r.LocalName), r.Value);
                        if (_lineInfo != null && _lineInfo.HasLineInfo())
{
                            xAttribute.SetLineInfo(_lineInfo.LineNumber, _lineInfo.LinePosition);
                        }
                        xElement2.AppendAttributeSkipNotify(xAttribute);
                    }
                    while (r.MoveToNextAttribute());
                    r.MoveToElement();
                }
                _currentContainer.AddNodeSkipNotify(xElement2);
                if (!r.IsEmptyElement)
                {
                    _currentContainer = xElement2;
                    if (_baseUri != null)
                    {
                        _baseUri = baseURI;
                    }
                }
                break;
            }
            case XmlNodeType.EndElement:
                if (_currentContainer.content == null)
                {
                    _currentContainer.content = string.Empty;
                }
                if (_currentContainer is XElement xElement && _lineInfo != null && _lineInfo.HasLineInfo())
                {
                    xElement.SetEndElementLineInfo(_lineInfo.LineNumber, _lineInfo.LinePosition);
                }
                if (_currentContainer == rootContainer)
                {
                    return false;
                }
                if (_baseUri != null && _currentContainer.HasBaseUri)
                {
                    _baseUri = _currentContainer.parent.BaseUri;
                }
                _currentContainer = _currentContainer.parent;
                break;
            case XmlNodeType.Text:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                if ((_baseUri != null && _baseUri != baseURI) || (_lineInfo != null && _lineInfo.HasLineInfo()))
                {
                    xNode = new XText(r.Value);
                }
                else
                {
                    _currentContainer.AddStringSkipNotify(r.Value);
                }
                break;
            case XmlNodeType.CDATA:
                xNode = new XCData(r.Value);
                break;
            case XmlNodeType.Comment:
                xNode = new XComment(r.Value);
                break;
            case XmlNodeType.ProcessingInstruction:
                xNode = new XProcessingInstruction(r.Name, r.Value);
                break;
            case XmlNodeType.DocumentType:
                xNode = new XDocumentType(r.LocalName, r.GetAttribute("PUBLIC"), r.GetAttribute("SYSTEM"), r.Value);
                break;
            case XmlNodeType.EntityReference:
                if (!r.CanResolveEntity)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_UnresolvedEntityReference);
                }
                r.ResolveEntity();
                break;
            default:
                throw new InvalidOperationException(System.SR.Format(System.SR.InvalidOperation_UnexpectedNodeType, r.NodeType));
            case XmlNodeType.EndEntity:
                break;
            }
            if (xNode != null)
            {
                if (_baseUri != null && _baseUri != baseURI)
                {
                    xNode.SetBaseUri(baseURI);
                }
                if (_lineInfo != null && _lineInfo.HasLineInfo())
                {
                    xNode.SetLineInfo(_lineInfo.LineNumber, _lineInfo.LinePosition);
                }
                _currentContainer.AddNodeSkipNotify(xNode);
                xNode = null;
            }
            return true;
        }
References System.Xml.Linq.XContainer.ContentReader._aCache, System.Xml.Linq.XContainer.ContentReader._baseUri, System.Xml.Linq.XContainer.ContentReader._currentContainer, System.Xml.Linq.XContainer.ContentReader._eCache, System.Xml.Linq.XContainer.ContentReader._lineInfo, System.Xml.Linq.XContainer.AddNodeSkipNotify(), System.Xml.Linq.XContainer.AddStringSkipNotify(), System.Xml.Linq.XObject.BaseUri, System.Xml.Linq.XContainer.content, System.Xml.Dictionary, System.SR.Format(), System.Xml.Linq.NamespaceCache.Get(), System.Xml.Linq.XNamespace.GetName(), System.Xml.Linq.XObject.HasBaseUri, System.Xml.IXmlLineInfo.HasLineInfo(), System.SR.InvalidOperation_UnexpectedNodeType, System.SR.InvalidOperation_UnresolvedEntityReference, System.Xml.IXmlLineInfo.LineNumber, System.Xml.IXmlLineInfo.LinePosition, and System.Xml.Linq.XObject.parent.