Terraria: System.Xml.Linq.XContainer.ContentReader.ReadContentFromAsync
ReadContentFromAsync() [2/2]
async ValueTask< bool > System.Xml.Linq.XContainer.ContentReader.ReadContentFromAsync (XContainer rootContainer, XmlReader r, LoadOptions o) inline
Definition at line 302 of file XContainer.cs.
        {
            XNode newNode = null;
            string baseUri = r.BaseURI;
            switch (r.NodeType)
            {
            case XmlNodeType.Element:
            {
                XElement e = new XElement(_eCache.Get(r.NamespaceURI).GetName(r.LocalName));
                if (_baseUri != null && _baseUri != baseUri)
                {
                    e.SetBaseUri(baseUri);
                }
                if (_lineInfo != null && _lineInfo.HasLineInfo())
                {
                    e.SetLineInfo(_lineInfo.LineNumber, _lineInfo.LinePosition);
                }
                if (r.MoveToFirstAttribute())
                {
                    do
                    {
                        XName name = _aCache.Get((r.Prefix.Length == 0) ? string.Empty : r.NamespaceURI).GetName(r.LocalName);
                        XAttribute xAttribute = new XAttribute(name, await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                        if (_lineInfo != null && _lineInfo.HasLineInfo())
{
                            xAttribute.SetLineInfo(_lineInfo.LineNumber, _lineInfo.LinePosition);
                        }
                        e.AppendAttributeSkipNotify(xAttribute);
                    }
                    while (r.MoveToNextAttribute());
                    r.MoveToElement();
                }
                _currentContainer.AddNodeSkipNotify(e);
                if (!r.IsEmptyElement)
                {
                    _currentContainer = e;
                    if (_baseUri != null)
                    {
                        _baseUri = baseUri;
                    }
                }
                break;
            }
            case XmlNodeType.EndElement:
                if (_currentContainer.content == null)
                {
                    _currentContainer.content = string.Empty;
                }
                if (_currentContainer is XElement xElement && _lineInfo != null && _lineInfo.HasLineInfo())
                {
                    xElement.SetEndElementLineInfo(_lineInfo.LineNumber, _lineInfo.LinePosition);
                }
                if (_currentContainer == rootContainer)
                {
                    return false;
                }
                if (_baseUri != null && _currentContainer.HasBaseUri)
                {
                    _baseUri = _currentContainer.parent.BaseUri;
                }
                _currentContainer = _currentContainer.parent;
                break;
            case XmlNodeType.Text:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
            {
                if ((_baseUri != null && _baseUri != baseUri) || (_lineInfo != null && _lineInfo.HasLineInfo()))
                {
                    newNode = new XText(await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                    break;
                }
                XContainer currentContainer = _currentContainer;
                currentContainer.AddStringSkipNotify(await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                break;
            }
            case XmlNodeType.CDATA:
                newNode = new XCData(await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                break;
            case XmlNodeType.Comment:
                newNode = new XComment(await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                break;
            case XmlNodeType.ProcessingInstruction:
            {
                string localName = r.Name;
                newNode = new XProcessingInstruction(localName, await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                break;
            }
            case XmlNodeType.DocumentType:
            {
                string localName = r.LocalName;
                string attribute = r.GetAttribute("PUBLIC");
                string attribute2 = r.GetAttribute("SYSTEM");
                newNode = new XDocumentType(localName, attribute, attribute2, await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                break;
            }
            case XmlNodeType.EntityReference:
                if (!r.CanResolveEntity)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_UnresolvedEntityReference);
                }
                r.ResolveEntity();
                break;
            default:
                throw new InvalidOperationException(System.SR.Format(System.SR.InvalidOperation_UnexpectedNodeType, r.NodeType));
            case XmlNodeType.EndEntity:
                break;
            }
            if (newNode != null)
            {
                if (_baseUri != null && _baseUri != baseUri)
                {
                    newNode.SetBaseUri(baseUri);
                }
                if (_lineInfo != null && _lineInfo.HasLineInfo())
                {
                    newNode.SetLineInfo(_lineInfo.LineNumber, _lineInfo.LinePosition);
                }
                _currentContainer.AddNodeSkipNotify(newNode);
            }
            return true;
        }
References System.Xml.Linq.XContainer.ContentReader._aCache, System.Xml.Linq.XContainer.ContentReader._baseUri, System.Xml.Linq.XContainer.ContentReader._currentContainer, System.Xml.Linq.XContainer.ContentReader._eCache, System.Xml.Linq.XContainer.ContentReader._lineInfo, System.Xml.Linq.XContainer.AddNodeSkipNotify(), System.Xml.Linq.XElement.AppendAttributeSkipNotify(), System.Xml.Linq.XObject.BaseUri, System.Xml.Linq.XContainer.content, System.Xml.Dictionary, System.SR.Format(), System.Xml.Linq.NamespaceCache.Get(), System.Xml.Linq.XNamespace.GetName(), System.Xml.Linq.XObject.HasBaseUri, System.Xml.IXmlLineInfo.HasLineInfo(), System.SR.InvalidOperation_UnexpectedNodeType, System.SR.InvalidOperation_UnresolvedEntityReference, System.Xml.IXmlLineInfo.LineNumber, System.Xml.IXmlLineInfo.LinePosition, System.Xml.Linq.XObject.parent, System.Xml.Linq.XObject.SetBaseUri(), and System.Xml.Linq.XObject.SetLineInfo().