Terraria: System.Xml.Linq.XContainer.ContentReader.ReadContentFromAsync
ReadContentFromAsync() [1/2]
async ValueTask< bool > System.Xml.Linq.XContainer.ContentReader.ReadContentFromAsync (XContainer rootContainer, XmlReader r) inline
Definition at line 102 of file XContainer.cs.
        {
            switch (r.NodeType)
            {
            case XmlNodeType.Element:
            {
                XElement e = new XElement(_eCache.Get(r.NamespaceURI).GetName(r.LocalName));
                if (r.MoveToFirstAttribute())
                {
                    do
                    {
                        XElement xElement = e;
                        XName name = _aCache.Get((r.Prefix.Length == 0) ? string.Empty : r.NamespaceURI).GetName(r.LocalName);
                        xElement.AppendAttributeSkipNotify(new XAttribute(name, await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false)));
                    }
                    while (r.MoveToNextAttribute());
                    r.MoveToElement();
                }
                _currentContainer.AddNodeSkipNotify(e);
                if (!r.IsEmptyElement)
                {
                    _currentContainer = e;
                }
                break;
            }
            case XmlNodeType.EndElement:
                if (_currentContainer.content == null)
                {
                    _currentContainer.content = string.Empty;
                }
                if (_currentContainer == rootContainer)
                {
                    return false;
                }
                _currentContainer = _currentContainer.parent;
                break;
            case XmlNodeType.Text:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
            {
                XContainer currentContainer = _currentContainer;
                currentContainer.AddStringSkipNotify(await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                break;
            }
            case XmlNodeType.CDATA:
            {
                XContainer currentContainer = _currentContainer;
                currentContainer.AddNodeSkipNotify(new XCData(await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false)));
                break;
            }
            case XmlNodeType.Comment:
            {
                XContainer currentContainer = _currentContainer;
                currentContainer.AddNodeSkipNotify(new XComment(await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false)));
                break;
            }
            case XmlNodeType.ProcessingInstruction:
            {
                XContainer currentContainer = _currentContainer;
                string localName = r.Name;
                currentContainer.AddNodeSkipNotify(new XProcessingInstruction(localName, await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false)));
                break;
            }
            case XmlNodeType.DocumentType:
            {
                XContainer currentContainer = _currentContainer;
                string localName = r.LocalName;
                string attribute = r.GetAttribute("PUBLIC");
                string attribute2 = r.GetAttribute("SYSTEM");
                currentContainer.AddNodeSkipNotify(new XDocumentType(localName, attribute, attribute2, await r.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false)));
                break;
            }
            case XmlNodeType.EntityReference:
                if (!r.CanResolveEntity)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_UnresolvedEntityReference);
                }
                r.ResolveEntity();
                break;
            default:
                throw new InvalidOperationException(System.SR.Format(System.SR.InvalidOperation_UnexpectedNodeType, r.NodeType));
            case XmlNodeType.EndEntity:
                break;
            }
            return true;
        }
References System.Xml.Linq.XContainer.ContentReader._aCache, System.Xml.Linq.XContainer.ContentReader._currentContainer, System.Xml.Linq.XContainer.ContentReader._eCache, System.Xml.Linq.XContainer.AddNodeSkipNotify(), System.Xml.Linq.XContainer.content, System.Xml.Dictionary, System.SR.Format(), System.Xml.Linq.NamespaceCache.Get(), System.Xml.Linq.XNamespace.GetName(), System.SR.InvalidOperation_UnexpectedNodeType, System.SR.InvalidOperation_UnresolvedEntityReference, and System.Xml.Linq.XObject.parent.