Terraria: WorkshopHelper.UGCBased.Downloader.Refresh
Refresh()
bool WorkshopHelper.UGCBased.Downloader.Refresh (WorkshopIssueReporter issueReporter) inline
             {
                 ResourcePackPaths.Clear();
                 WorldPaths.Clear();
                 foreach (string listOfSubscribedItemsPath in GetListOfSubscribedItemsPaths())
                 {
                     if (listOfSubscribedItemsPath == null)
                     {
                         continue;
                     }
                     try
                     {
                         string path = listOfSubscribedItemsPath + Path.DirectorySeparatorChar + "workshop.json";
                         if (!File.Exists(path))
{
                             continue;
                         }
                         string text = AWorkshopEntry.ReadHeader(File.ReadAllText(path));
                         if (!(text == "World"))
{
                             if (text == "ResourcePack")
{
                                 ResourcePackPaths.Add(listOfSubscribedItemsPath);
                             }
                         }
                         else
{
                             WorldPaths.Add(listOfSubscribedItemsPath);
                         }
                     }
                     catch (Exception exception)
                     {
                         issueReporter.ReportDownloadProblem("Workshop.ReportIssue_FailedToLoadSubscribedFile", listOfSubscribedItemsPath, exception);
                         return false;
                     }
                 }
                 return true;
             }
References WorkshopHelper.UGCBased.Downloader.GetListOfSubscribedItemsPaths(), AWorkshopEntry.ReadHeader(), WorkshopHelper.UGCBased.Downloader.ResourcePackPaths, and WorkshopHelper.UGCBased.Downloader.WorldPaths.
Referenced by WorkshopHelper.UGCBased.Downloader.Prepare().