Terraria: System.Xml.Xsl.XsltOld.OutputScopeManager.OutputScopeManager
OutputScopeManager()
System.Xml.Xsl.XsltOld.OutputScopeManager.OutputScopeManager (XmlNameTable nameTable, OutKeywords atoms) inline package
Definition at line 25 of file OutputScopeManager.cs.
    {
        _elementScopesStack = new HWStack(10);
        _nameTable = nameTable;
        _atoms = atoms;
        _defaultNS = _atoms.Empty;
        OutputScope outputScope = (OutputScope)_elementScopesStack.Push();
        if (outputScope == null)
        {
            outputScope = new OutputScope();
            _elementScopesStack.AddToTop(outputScope);
        }
        outputScope.Init(string.Empty, string.Empty, string.Empty, XmlSpace.None, string.Empty, mixed: false);
    }
References System.Empty.Empty(), System.Xml.Xsl.XsltOld.OutputScopeManager._atoms, System.Xml.Xsl.XsltOld.OutputScopeManager._defaultNS, System.Xml.Xsl.XsltOld.OutputScopeManager._elementScopesStack, System.Xml.Xsl.XsltOld.OutputScopeManager._nameTable, System.Xml.HWStack.AddToTop(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.OutKeywords.Empty, and System.Xml.HWStack.Push().