Terraria: System.Xml.Xsl.XsltOld.OutputScopeManager.GeneratePrefix
GeneratePrefix()
string System.Xml.Xsl.XsltOld.OutputScopeManager.GeneratePrefix (string format) inline package
Definition at line 127 of file OutputScopeManager.cs.
    {
        string array;
        do
        {
            array = string.Format(CultureInfo.InvariantCulture, format, _prefixIndex++);
        }
        while (_nameTable.Get(array) != null);
        return _nameTable.Add(array);
    }
References System.Xml.Xsl.XsltOld.OutputScopeManager._nameTable, System.Xml.Xsl.XsltOld.OutputScopeManager._prefixIndex, System.Xml.XmlNameTable.Add(), System.array, System.format, System.Xml.XmlNameTable.Get(), and System.Globalization.CultureInfo.InvariantCulture.
Referenced by System.Xml.Xsl.XsltOld.RecordBuilder.DeclareNewNamespace().