Terraria: Language.GetTextValue
GetTextValue() [1/5]
static string Language.GetTextValue (string key) inline static
     {
         return LanguageManager.Instance.GetTextValue(key);
     }
References LanguageManager.GetTextValue(), and LanguageManager.Instance.
Referenced by CreativePowersHelper.AddDescriptionIfNeeded(), CreativePowersHelper.AddPermissionTextIfNeeded(), CreativePowersHelper.AddUnlockTextIfNeeded(), Projectile.AI_061_FishingBobber(), UIWorldCreation.AssignRandomWorldName(), ShopHelper.BiomeNameByKey(), UIResourcePack.BuildChildren(), UIReportsPage.BuildPage(), UIResourcePackInfoMenu.BuildPage(), CreativePowers.APerPlayerTogglePower.button_OnUpdate(), CreativePowers.ASharedButtonPower.button_OnUpdate(), CreativePowers.ASharedTogglePower.button_OnUpdate(), CreativePowers.APerPlayerSliderPower.categoryButton_OnUpdate(), CreativePowers.ASharedSliderPower.categoryButton_OnUpdate(), UICreativePowersMenu.CategoryButton_OnUpdate_DisplayTooltips(), NetMessage.CheckBytes(), NetClientSocialModule.CheckParameters(), RemoteClient.CheckSection(), Player.CheckSpawn_Internal(), UIWorldCreation.Click_SetSeed(), Netplay.ClientLoopSetup(), RemoteServer.ClientReadCallBack(), UICharacterListItem.CloudButtonClick(), UIWorldListItem.CloudButtonClick(), UICharacterListItem.CloudMouseOver(), UIWorldListItem.CloudMouseOver(), SortingSteps.Alphabetical.Compare(), NetClientSocialModule.ConnectToLobby(), Lang.CreateDialogSubstitutionObject(), Main.DedServ(), UICharacterListItem.DeleteMouseOver(), UIWorldListItem.DeleteMouseOver(), Program.DisplayException(), UIResourcePackSelectionMenu.DisplayMouseTextIfHovered(), NPC.DoDeathEvents_CelebrateBossDeath(), LegacyMultiplayerClosePlayersOverlay.Draw(), NewMultiplayerClosePlayersOverlay.Draw(), IngameOptions.Draw(), SpawnMapLayer.Draw(), UIAchievementsMenu.Draw(), UICharacterCreation.Draw(), IssueReportsIndicator.Draw(), Main.DrawBestiaryIcon(), Main.DrawBlockReplacementIcon(), Main.DrawBuilderAccToggles(), ChestUI.DrawButton(), Main.DrawClothesWindow(), Main.DrawEmoteBubblesButton(), Main.DrawHairWindow(), Main.DrawInfoAccs(), Main.DrawInterface_35_YouDied(), Main.DrawInterface_InstrumentMouseText(), Main.DrawInvasionProgress(), Main.DrawInventory(), Main.DrawLoadoutButtons(), Main.DrawMap(), Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition(), Main.DrawMapIcons_PotionOfReturnHomePosition(), Main.DrawMenu(), Main.DrawMouseOver(), Main.DrawNPCChatButtons(), EmoteButton.DrawSelf(), UICharacterListItem.DrawSelf(), UIWorkshopImportWorldListItem.DrawSelf(), UIWorkshopPublishResourcePackListItem.DrawSelf(), UIWorkshopPublishWorldListItem.DrawSelf(), UIWorldListItem.DrawSelf(), UIWorldLoad.DrawSelf(), CreativeUI.DrawToggleButton(), TitleLinkButton.DrawTooltip(), Main.DrawTorchBiomeSwapIcon(), CaptureInterface.ModeChangeSettings.DrawWaterChoices(), NetMessage.EnsureLocalPlayerIsPresent(), UICharacterListItem.FavoriteButtonClick(), UIWorldListItem.FavoriteButtonClick(), UICharacterListItem.FavoriteMouseOver(), UIWorldListItem.FavoriteMouseOver(), CaptureCamera.FinishCapture(), Projectile.FishingCheck(), WorldGen.GenerateWorld(), Main.GetBuffTooltip(), NPC.GetChat(), Conditions.FrostMoonDropGatingChance.GetConditionDescription(), Conditions.PumpkinMoonDropGatingChance.GetConditionDescription(), Conditions.FromCertainWaveAndAbove.GetConditionDescription(), Conditions.PirateMap.GetConditionDescription(), Conditions.IsChristmas.GetConditionDescription(), Conditions.NotExpert.GetConditionDescription(), Conditions.NotMasterMode.GetConditionDescription(), Conditions.EmpressOfLightIsGenuinelyEnraged.GetConditionDescription(), Conditions.PlayerNeedsHealing.GetConditionDescription(), Conditions.LegacyHack_IsBossAndExpert.GetConditionDescription(), Conditions.LegacyHack_IsBossAndNotExpert.GetConditionDescription(), Conditions.IsExpert.GetConditionDescription(), Conditions.IsMasterMode.GetConditionDescription(), Conditions.IsCrimson.GetConditionDescription(), Conditions.IsCorruption.GetConditionDescription(), Conditions.IsCrimsonAndNotExpert.GetConditionDescription(), Conditions.IsCorruptionAndNotExpert.GetConditionDescription(), Conditions.HalloweenWeapons.GetConditionDescription(), Conditions.SoulOfNight.GetConditionDescription(), Conditions.SoulOfLight.GetConditionDescription(), Conditions.NotFromStatue.GetConditionDescription(), Conditions.HalloweenGoodieBagDrop.GetConditionDescription(), Conditions.XmasPresentDrop.GetConditionDescription(), Conditions.LivingFlames.GetConditionDescription(), Conditions.NamedNPC.GetConditionDescription(), Conditions.HallowKeyCondition.GetConditionDescription(), Conditions.JungleKeyCondition.GetConditionDescription(), Conditions.CorruptKeyCondition.GetConditionDescription(), Conditions.CrimsonKeyCondition.GetConditionDescription(), Conditions.FrozenKeyCondition.GetConditionDescription(), Conditions.DesertKeyCondition.GetConditionDescription(), Conditions.BeatAnyMechBoss.GetConditionDescription(), Conditions.YoyoCascade.GetConditionDescription(), Conditions.YoyosAmarok.GetConditionDescription(), Conditions.YoyosYelets.GetConditionDescription(), Conditions.YoyosKraken.GetConditionDescription(), Conditions.YoyosHelFire.GetConditionDescription(), Conditions.WindyEnoughForKiteDrops.GetConditionDescription(), MessageBuffer.GetData(), AWorldListItem.GetDifficulty(), EntrySorter< TEntryType, TStepType >.GetDisplayName(), Lang.GetDryadWorldStatusDialog(), UIKeybindingListItem.GetFriendlyName(), ItemSlot.GetGamepadInstructions(), UnlockableNPCEntryIcon.GetHoverText(), Lang.GetNPCHouseBannerText(), Main.GUIChatDrawInner(), Main.HelpText(), UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles(), CoreSocialModule.Initialize(), NetServerSocialModule.Initialize(), Netplay.InitializeServer(), Netplay.InnerClientLoop(), Player.ItemCheck_UseCombatBook(), Player.ItemCheck_UsePeddlersSatchel(), Netplay.KickClient(), NetClientSocialModule.LaunchLocalServer(), TcpSocket.ListenLoop(), WorldFile.LoadFileFormatHeader(), Lang.LocalizedDuration(), CreativePowers.DifficultySliderPower.MouseOver_Expert(), CreativePowers.DifficultySliderPower.MouseOver_Journey(), CreativePowers.DifficultySliderPower.MouseOver_Master(), CreativePowers.DifficultySliderPower.MouseOver_Normal(), Main.MouseText_DrawBuffTooltip(), Main.MouseText_DrawItemTooltip_GetLinesInfo(), WorldGen.MoveTownNPC(), NPC.NewNPC(), AchievementInitializer.OnAchievementCompleted(), NetClientSocialModule.OnAuthSuccess(), NetServerSocialModule.OnLobbyCreated(), NetClientSocialModule.OnLobbyEntered(), NetClientSocialModule.OnLobbyJoinRequest(), NetClientSocialModule.OnRailRespondInvation(), Main.OnSubmitServerPort(), IngameFancyUI.OpenVirtualKeyboard(), UICharacterListItem.PlayMouseOver(), UIWorkshopImportWorldListItem.PlayMouseOver(), UIWorldListItem.PlayMouseOver(), WorldGen.playWorldCallBack(), UIReportsPage.PopulateLogs(), NetMessage.ReceiveBytes(), UICharacterListItem.RenameMouseOver(), UIWorldListItem.RenameMouseOver(), WorkshopIssueReporter.ReportDelayedUploadProblem(), WorkshopIssueReporter.ReportInstantUploadProblem(), UICreativeInfiniteItemsDisplay.research_OnUpdate(), Preferences.Save(), UIWorldListItem.SeedButtonClick(), UIWorldListItem.SeedMouseOver(), NetMessage.SendData(), WorldGen.serverLoadWorldCallBack(), Main.SetDisplayMode(), Recipe.SetupRecipeGroups(), FilterProviderInfoElement.ShowButtonName(), UIBestiaryFilteringOptionsGrid.ShowButtonName(), UICreativeItemsInfiniteFilteringOptions.ShowButtonName(), NPCKillCounterInfoElement.ShowDescription(), NPCStatsReportInfoElement.ShowStats_Attack(), NPCStatsReportInfoElement.ShowStats_Defense(), NPCStatsReportInfoElement.ShowStats_Knockback(), NPCStatsReportInfoElement.ShowStats_Life(), NPC.SpawnBoss(), NPC.SpawnOnPlayer(), NPC.SpawnSkeletron(), WorldGen.SpawnTownNPC(), WorldGen.SpawnTravelNPC(), NPC.SpawnWOF(), Main.startDedInputCallBack(), Liquid.StartPanic(), Lang.SupportGlyphs(), Player.TileInteractionsUse(), NetworkText.ToString(), ItemSlot.TryEnteringFastUseMode(), UIWorkshopPublishResourcePackListItem.TryMovingToRejectionMenuIfNeeded(), UIWorldListItem.TryMovingToRejectionMenuIfNeeded(), Player.UpdateArmorSets(), DontStarveDarknessDamageDealer.UpdateDarknessState(), Liquid.UpdateLiquid(), CreativePowers.ModifyWindDirectionAndStrength.UpdateSliderAndShowMultiplierMouseOver(), CreativePowers.SpawnRateSliderPerPlayerPower.UpdateSliderAndShowMultiplierMouseOver(), RemoteClient.UpdateStatusText(), Main.ValueToCoins(), and PopupText.ValueToName().