Terraria: System.Xml.Xsl.Qil.QilTypeChecker.DistinctType
DistinctType()
XmlQueryType System.Xml.Xsl.Qil.QilTypeChecker.DistinctType (XmlQueryType type) inline private
Definition at line 689 of file QilTypeChecker.cs.
    {
        if (type.Cardinality == XmlQueryCardinality.More)
        {
            return XmlQueryTypeFactory.PrimeProduct(type, XmlQueryCardinality.OneOrMore);
        }
        if (type.Cardinality == XmlQueryCardinality.NotOne)
        {
            return XmlQueryTypeFactory.PrimeProduct(type, XmlQueryCardinality.ZeroOrMore);
        }
        return type;
    }
References System.Xml.Xsl.XmlQueryCardinality.More, System.Xml.Xsl.XmlQueryCardinality.NotOne, System.Xml.Xsl.XmlQueryCardinality.OneOrMore, System.Xml.Xsl.XmlQueryTypeFactory.PrimeProduct(), System.type, and System.Xml.Xsl.XmlQueryCardinality.ZeroOrMore.
Referenced by System.Xml.Xsl.Qil.QilTypeChecker.CheckDocOrderDistinct(), and System.Xml.Xsl.Qil.QilTypeChecker.CheckUnion().