Terraria: TimeLogger.UpdateTime
UpdateTime()
static void TimeLogger.UpdateTime (TimeLogData[] times, int type, double time) inline static private
     {
         bool flag = false;
         if (times[type].resetMaxTime > 0)
         {
             times[type].resetMaxTime--;
         }
         else
         {
             times[type].timeMax = 0f;
         }
         times[type].time = (float)time;
         if ((double)times[type].timeMax < time)
         {
             flag = true;
             times[type].timeMax = (float)time;
             times[type].resetMaxTime = 100;
         }
         times[type].usedLastDraw = true;
         if (currentFrame != 0)
         {
             logBuilder.AppendLine(string.Format("    {0} : {1:F4}ms {2}", times[type].logText, time, flag ? " - New Maximum" : string.Empty));
         }
     }
References currentFrame, Empty, logBuilder, TimeLogger.TimeLogData.resetMaxTime, TimeLogger.TimeLogData.time, TimeLogger.TimeLogData.timeMax, and TimeLogger.TimeLogData.usedLastDraw.
Referenced by DetailedDrawTime(), DrawTime(), LightingTime(), and RenderTime().