Terraria: TimeLogger.DetailedDrawReset
DetailedDrawReset()
static void TimeLogger.DetailedDrawReset () inline static
     {
         lastDetailedDrawTime = detailedDrawTimer.Elapsed.TotalMilliseconds;
     }
References detailedDrawTimer, and lastDetailedDrawTime.
Referenced by Main.DoDraw(), Main.DoDraw_Tiles_NonSolid(), Main.DoDraw_WallsTilesNPCs(), TileDrawing.GetScreenDrawArea(), Main.RenderBackground(), Main.RenderBlack(), Main.RenderTiles(), Main.RenderTiles2(), Main.RenderWalls(), and Main.RenderWater().