Terraria: System.Xml.Xsl.Qil.QilTypeChecker.Check
Check()
XmlQueryType System.Xml.Xsl.Qil.QilTypeChecker.Check (QilNode n) inline
Definition at line 7 of file QilTypeChecker.cs.
    {
        return n.NodeType switch
        {
            QilNodeType.QilExpression => CheckQilExpression((QilExpression)n),
            QilNodeType.FunctionList => CheckFunctionList((QilList)n),
            QilNodeType.GlobalVariableList => CheckGlobalVariableList((QilList)n),
            QilNodeType.GlobalParameterList => CheckGlobalParameterList((QilList)n),
            QilNodeType.ActualParameterList => CheckActualParameterList((QilList)n),
            QilNodeType.FormalParameterList => CheckFormalParameterList((QilList)n),
            QilNodeType.SortKeyList => CheckSortKeyList((QilList)n),
            QilNodeType.BranchList => CheckBranchList((QilList)n),
            QilNodeType.OptimizeBarrier => CheckOptimizeBarrier((QilUnary)n),
            QilNodeType.Unknown => CheckUnknown(n),
            QilNodeType.DataSource => CheckDataSource((QilDataSource)n),
            QilNodeType.Nop => CheckNop((QilUnary)n),
            QilNodeType.Error => CheckError((QilUnary)n),
            QilNodeType.Warning => CheckWarning((QilUnary)n),
            QilNodeType.For => CheckFor((QilIterator)n),
            QilNodeType.Let => CheckLet((QilIterator)n),
            QilNodeType.Parameter => CheckParameter((QilParameter)n),
            QilNodeType.PositionOf => CheckPositionOf((QilUnary)n),
            QilNodeType.True => CheckTrue(n),
            QilNodeType.False => CheckFalse(n),
            QilNodeType.LiteralString => CheckLiteralString((QilLiteral)n),
            QilNodeType.LiteralInt32 => CheckLiteralInt32((QilLiteral)n),
            QilNodeType.LiteralInt64 => CheckLiteralInt64((QilLiteral)n),
            QilNodeType.LiteralDouble => CheckLiteralDouble((QilLiteral)n),
            QilNodeType.LiteralDecimal => CheckLiteralDecimal((QilLiteral)n),
            QilNodeType.LiteralQName => CheckLiteralQName((QilName)n),
            QilNodeType.LiteralType => CheckLiteralType((QilLiteral)n),
            QilNodeType.LiteralObject => CheckLiteralObject((QilLiteral)n),
            QilNodeType.And => CheckAnd((QilBinary)n),
            QilNodeType.Or => CheckOr((QilBinary)n),
            QilNodeType.Not => CheckNot((QilUnary)n),
            QilNodeType.Conditional => CheckConditional((QilTernary)n),
            QilNodeType.Choice => CheckChoice((QilChoice)n),
            QilNodeType.Length => CheckLength((QilUnary)n),
            QilNodeType.Sequence => CheckSequence((QilList)n),
            QilNodeType.Union => CheckUnion((QilBinary)n),
            QilNodeType.Intersection => CheckIntersection((QilBinary)n),
            QilNodeType.Difference => CheckDifference((QilBinary)n),
            QilNodeType.Average => CheckAverage((QilUnary)n),
            QilNodeType.Sum => CheckSum((QilUnary)n),
            QilNodeType.Minimum => CheckMinimum((QilUnary)n),
            QilNodeType.Maximum => CheckMaximum((QilUnary)n),
            QilNodeType.Negate => CheckNegate((QilUnary)n),
            QilNodeType.Add => CheckAdd((QilBinary)n),
            QilNodeType.Subtract => CheckSubtract((QilBinary)n),
            QilNodeType.Multiply => CheckMultiply((QilBinary)n),
            QilNodeType.Divide => CheckDivide((QilBinary)n),
            QilNodeType.Modulo => CheckModulo((QilBinary)n),
            QilNodeType.StrLength => CheckStrLength((QilUnary)n),
            QilNodeType.StrConcat => CheckStrConcat((QilStrConcat)n),
            QilNodeType.StrParseQName => CheckStrParseQName((QilBinary)n),
            QilNodeType.Ne => CheckNe((QilBinary)n),
            QilNodeType.Eq => CheckEq((QilBinary)n),
            QilNodeType.Gt => CheckGt((QilBinary)n),
            QilNodeType.Ge => CheckGe((QilBinary)n),
            QilNodeType.Lt => CheckLt((QilBinary)n),
            QilNodeType.Le => CheckLe((QilBinary)n),
            QilNodeType.Is => CheckIs((QilBinary)n),
            QilNodeType.After => CheckAfter((QilBinary)n),
            QilNodeType.Before => CheckBefore((QilBinary)n),
            QilNodeType.Loop => CheckLoop((QilLoop)n),
            QilNodeType.Filter => CheckFilter((QilLoop)n),
            QilNodeType.Sort => CheckSort((QilLoop)n),
            QilNodeType.SortKey => CheckSortKey((QilSortKey)n),
            QilNodeType.DocOrderDistinct => CheckDocOrderDistinct((QilUnary)n),
            QilNodeType.Function => CheckFunction((QilFunction)n),
            QilNodeType.Invoke => CheckInvoke((QilInvoke)n),
            QilNodeType.Content => CheckContent((QilUnary)n),
            QilNodeType.Attribute => CheckAttribute((QilBinary)n),
            QilNodeType.Parent => CheckParent((QilUnary)n),
            QilNodeType.Root => CheckRoot((QilUnary)n),
            QilNodeType.XmlContext => CheckXmlContext(n),
            QilNodeType.Descendant => CheckDescendant((QilUnary)n),
            QilNodeType.DescendantOrSelf => CheckDescendantOrSelf((QilUnary)n),
            QilNodeType.Ancestor => CheckAncestor((QilUnary)n),
            QilNodeType.AncestorOrSelf => CheckAncestorOrSelf((QilUnary)n),
            QilNodeType.Preceding => CheckPreceding((QilUnary)n),
            QilNodeType.FollowingSibling => CheckFollowingSibling((QilUnary)n),
            QilNodeType.PrecedingSibling => CheckPrecedingSibling((QilUnary)n),
            QilNodeType.NodeRange => CheckNodeRange((QilBinary)n),
            QilNodeType.Deref => CheckDeref((QilBinary)n),
            QilNodeType.ElementCtor => CheckElementCtor((QilBinary)n),
            QilNodeType.AttributeCtor => CheckAttributeCtor((QilBinary)n),
            QilNodeType.CommentCtor => CheckCommentCtor((QilUnary)n),
            QilNodeType.PICtor => CheckPICtor((QilBinary)n),
            QilNodeType.TextCtor => CheckTextCtor((QilUnary)n),
            QilNodeType.RawTextCtor => CheckRawTextCtor((QilUnary)n),
            QilNodeType.DocumentCtor => CheckDocumentCtor((QilUnary)n),
            QilNodeType.NamespaceDecl => CheckNamespaceDecl((QilBinary)n),
            QilNodeType.RtfCtor => CheckRtfCtor((QilBinary)n),
            QilNodeType.NameOf => CheckNameOf((QilUnary)n),
            QilNodeType.LocalNameOf => CheckLocalNameOf((QilUnary)n),
            QilNodeType.NamespaceUriOf => CheckNamespaceUriOf((QilUnary)n),
            QilNodeType.PrefixOf => CheckPrefixOf((QilUnary)n),
            QilNodeType.TypeAssert => CheckTypeAssert((QilTargetType)n),
            QilNodeType.IsType => CheckIsType((QilTargetType)n),
            QilNodeType.IsEmpty => CheckIsEmpty((QilUnary)n),
            QilNodeType.XPathNodeValue => CheckXPathNodeValue((QilUnary)n),
            QilNodeType.XPathFollowing => CheckXPathFollowing((QilUnary)n),
            QilNodeType.XPathPreceding => CheckXPathPreceding((QilUnary)n),
            QilNodeType.XPathNamespace => CheckXPathNamespace((QilUnary)n),
            QilNodeType.XsltGenerateId => CheckXsltGenerateId((QilUnary)n),
            QilNodeType.XsltInvokeLateBound => CheckXsltInvokeLateBound((QilInvokeLateBound)n),
            QilNodeType.XsltInvokeEarlyBound => CheckXsltInvokeEarlyBound((QilInvokeEarlyBound)n),
            QilNodeType.XsltCopy => CheckXsltCopy((QilBinary)n),
            QilNodeType.XsltCopyOf => CheckXsltCopyOf((QilUnary)n),
            QilNodeType.XsltConvert => CheckXsltConvert((QilTargetType)n),
            _ => CheckUnknown(n),
        };
    }
References System.Xml.Xsl.Qil.QilTypeChecker.CheckActualParameterList(), System.Xml.Xsl.Qil.QilTypeChecker.CheckAdd(), System.Xml.Xsl.Qil.QilTypeChecker.CheckAfter(), System.Xml.Xsl.Qil.QilTypeChecker.CheckAncestor(), System.Xml.Xsl.Qil.QilTypeChecker.CheckAncestorOrSelf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckAnd(), System.Xml.Xsl.Qil.QilTypeChecker.CheckAttribute(), System.Xml.Xsl.Qil.QilTypeChecker.CheckAttributeCtor(), System.Xml.Xsl.Qil.QilTypeChecker.CheckAverage(), System.Xml.Xsl.Qil.QilTypeChecker.CheckBefore(), System.Xml.Xsl.Qil.QilTypeChecker.CheckBranchList(), System.Xml.Xsl.Qil.QilTypeChecker.CheckChoice(), System.Xml.Xsl.Qil.QilTypeChecker.CheckCommentCtor(), System.Xml.Xsl.Qil.QilTypeChecker.CheckConditional(), System.Xml.Xsl.Qil.QilTypeChecker.CheckContent(), System.Xml.Xsl.Qil.QilTypeChecker.CheckDataSource(), System.Xml.Xsl.Qil.QilTypeChecker.CheckDeref(), System.Xml.Xsl.Qil.QilTypeChecker.CheckDescendant(), System.Xml.Xsl.Qil.QilTypeChecker.CheckDescendantOrSelf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckDifference(), System.Xml.Xsl.Qil.QilTypeChecker.CheckDivide(), System.Xml.Xsl.Qil.QilTypeChecker.CheckDocOrderDistinct(), System.Xml.Xsl.Qil.QilTypeChecker.CheckDocumentCtor(), System.Xml.Xsl.Qil.QilTypeChecker.CheckElementCtor(), System.Xml.Xsl.Qil.QilTypeChecker.CheckEq(), System.Xml.Xsl.Qil.QilTypeChecker.CheckError(), System.Xml.Xsl.Qil.QilTypeChecker.CheckFalse(), System.Xml.Xsl.Qil.QilTypeChecker.CheckFilter(), System.Xml.Xsl.Qil.QilTypeChecker.CheckFollowingSibling(), System.Xml.Xsl.Qil.QilTypeChecker.CheckFor(), System.Xml.Xsl.Qil.QilTypeChecker.CheckFormalParameterList(), System.Xml.Xsl.Qil.QilTypeChecker.CheckFunction(), System.Xml.Xsl.Qil.QilTypeChecker.CheckFunctionList(), System.Xml.Xsl.Qil.QilTypeChecker.CheckGe(), System.Xml.Xsl.Qil.QilTypeChecker.CheckGlobalParameterList(), System.Xml.Xsl.Qil.QilTypeChecker.CheckGlobalVariableList(), System.Xml.Xsl.Qil.QilTypeChecker.CheckGt(), System.Xml.Xsl.Qil.QilTypeChecker.CheckIntersection(), System.Xml.Xsl.Qil.QilTypeChecker.CheckInvoke(), System.Xml.Xsl.Qil.QilTypeChecker.CheckIs(), System.Xml.Xsl.Qil.QilTypeChecker.CheckIsEmpty(), System.Xml.Xsl.Qil.QilTypeChecker.CheckIsType(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLe(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLength(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLet(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralDecimal(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralDouble(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralInt32(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralInt64(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralObject(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralQName(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralString(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralType(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLocalNameOf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLoop(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLt(), System.Xml.Xsl.Qil.QilTypeChecker.CheckMaximum(), System.Xml.Xsl.Qil.QilTypeChecker.CheckMinimum(), System.Xml.Xsl.Qil.QilTypeChecker.CheckModulo(), System.Xml.Xsl.Qil.QilTypeChecker.CheckMultiply(), System.Xml.Xsl.Qil.QilTypeChecker.CheckNameOf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckNamespaceDecl(), System.Xml.Xsl.Qil.QilTypeChecker.CheckNamespaceUriOf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckNe(), System.Xml.Xsl.Qil.QilTypeChecker.CheckNegate(), System.Xml.Xsl.Qil.QilTypeChecker.CheckNodeRange(), System.Xml.Xsl.Qil.QilTypeChecker.CheckNop(), System.Xml.Xsl.Qil.QilTypeChecker.CheckNot(), System.Xml.Xsl.Qil.QilTypeChecker.CheckOptimizeBarrier(), System.Xml.Xsl.Qil.QilTypeChecker.CheckOr(), System.Xml.Xsl.Qil.QilTypeChecker.CheckParameter(), System.Xml.Xsl.Qil.QilTypeChecker.CheckParent(), System.Xml.Xsl.Qil.QilTypeChecker.CheckPICtor(), System.Xml.Xsl.Qil.QilTypeChecker.CheckPositionOf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckPreceding(), System.Xml.Xsl.Qil.QilTypeChecker.CheckPrecedingSibling(), System.Xml.Xsl.Qil.QilTypeChecker.CheckPrefixOf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckQilExpression(), System.Xml.Xsl.Qil.QilTypeChecker.CheckRawTextCtor(), System.Xml.Xsl.Qil.QilTypeChecker.CheckRoot(), System.Xml.Xsl.Qil.QilTypeChecker.CheckRtfCtor(), System.Xml.Xsl.Qil.QilTypeChecker.CheckSequence(), System.Xml.Xsl.Qil.QilTypeChecker.CheckSort(), System.Xml.Xsl.Qil.QilTypeChecker.CheckSortKey(), System.Xml.Xsl.Qil.QilTypeChecker.CheckSortKeyList(), System.Xml.Xsl.Qil.QilTypeChecker.CheckStrConcat(), System.Xml.Xsl.Qil.QilTypeChecker.CheckStrLength(), System.Xml.Xsl.Qil.QilTypeChecker.CheckStrParseQName(), System.Xml.Xsl.Qil.QilTypeChecker.CheckSubtract(), System.Xml.Xsl.Qil.QilTypeChecker.CheckSum(), System.Xml.Xsl.Qil.QilTypeChecker.CheckTextCtor(), System.Xml.Xsl.Qil.QilTypeChecker.CheckTrue(), System.Xml.Xsl.Qil.QilTypeChecker.CheckTypeAssert(), System.Xml.Xsl.Qil.QilTypeChecker.CheckUnion(), System.Xml.Xsl.Qil.QilTypeChecker.CheckUnknown(), System.Xml.Xsl.Qil.QilTypeChecker.CheckWarning(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXmlContext(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXPathFollowing(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXPathNamespace(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXPathNodeValue(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXPathPreceding(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXsltConvert(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXsltCopy(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXsltCopyOf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXsltGenerateId(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXsltInvokeEarlyBound(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXsltInvokeLateBound(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Qil.QilReplaceVisitor.RecalculateType().