Terraria: System.Xml.Xsl.Qil.QilTypeChecker.CheckDescendantOrSelf
CheckDescendantOrSelf()
XmlQueryType System.Xml.Xsl.Qil.QilTypeChecker.CheckDescendantOrSelf (QilUnary node) inline
Definition at line 515 of file QilTypeChecker.cs.
    {
        return XmlQueryTypeFactory.Choice(node.Child.XmlType, XmlQueryTypeFactory.ContentS);
    }
References System.Xml.Xsl.XmlQueryTypeFactory.Choice(), System.Xml.Xsl.XmlQueryTypeFactory.ContentS, and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Qil.QilTypeChecker.Check(), and System.Xml.Xsl.Qil.QilFactory.DescendantOrSelf().