Terraria: System.Xml.Xsl.Qil.QilTypeChecker.CheckAverage
CheckAverage()
XmlQueryType System.Xml.Xsl.Qil.QilTypeChecker.CheckAverage (QilUnary node) inline
Definition at line 327 of file QilTypeChecker.cs.
    {
        XmlQueryType xmlType = node.Child.XmlType;
        return XmlQueryTypeFactory.PrimeProduct(xmlType, xmlType.MaybeEmpty ? XmlQueryCardinality.ZeroOrOne : XmlQueryCardinality.One);
    }
References System.Xml.Dictionary, System.Xml.Xsl.XmlQueryType.MaybeEmpty, System.Xml.Xsl.XmlQueryCardinality.One, System.Xml.Xsl.XmlQueryTypeFactory.PrimeProduct(), and System.Xml.Xsl.XmlQueryCardinality.ZeroOrOne.
Referenced by System.Xml.Xsl.Qil.QilTypeChecker.Check(), System.Xml.Xsl.Qil.QilTypeChecker.CheckMaximum(), System.Xml.Xsl.Qil.QilTypeChecker.CheckMinimum(), and System.Xml.Xsl.Qil.QilTypeChecker.CheckSum().