Terraria: System.Xml.Xsl.Qil.QilTypeChecker.FindFilterType
FindFilterType()
XmlQueryType System.Xml.Xsl.Qil.QilTypeChecker.FindFilterType (QilIterator variable, QilNode body) inline private
Definition at line 702 of file QilTypeChecker.cs.
    {
        if (body.XmlType.TypeCode == XmlTypeCode.None)
        {
            return XmlQueryTypeFactory.None;
        }
        switch (body.NodeType)
        {
        case QilNodeType.False:
            return XmlQueryTypeFactory.Empty;
        case QilNodeType.IsType:
            if (((QilTargetType)body).Source == variable)
            {
                return XmlQueryTypeFactory.AtMost(((QilTargetType)body).TargetType, variable.Binding.XmlType.Cardinality);
            }
            break;
        case QilNodeType.And:
        {
            XmlQueryType xmlQueryType = FindFilterType(variable, ((QilBinary)body).Left);
            if (xmlQueryType != null)
            {
                return xmlQueryType;
            }
            return FindFilterType(variable, ((QilBinary)body).Right);
        }
        case QilNodeType.Eq:
        {
            QilBinary qilBinary = (QilBinary)body;
            if (qilBinary.Left.NodeType == QilNodeType.PositionOf && ((QilUnary)qilBinary.Left).Child == variable)
            {
                return XmlQueryTypeFactory.AtMost(variable.Binding.XmlType, XmlQueryCardinality.ZeroOrOne);
            }
            break;
        }
        }
        return null;
    }
References System.Xml.Xsl.XmlQueryTypeFactory.AtMost(), System.Xml.Dictionary, System.Xml.Xsl.XmlQueryTypeFactory.Empty, System.Xml.Xsl.Qil.QilTypeChecker.FindFilterType(), System.Xml.Xsl.Qil.QilNode.NodeType, System.Xml.Xsl.XmlQueryTypeFactory.None, System.Xml.Xsl.XmlQueryType.TypeCode, System.Xml.Xsl.Qil.QilNode.XmlType, and System.Xml.Xsl.XmlQueryCardinality.ZeroOrOne.
Referenced by System.Xml.Xsl.Qil.QilTypeChecker.CheckFilter(), and System.Xml.Xsl.Qil.QilTypeChecker.FindFilterType().