Terraria: Terraria.GameContent.UI.States.UIManageControls.FillList
FillList()
void Terraria.GameContent.UI.States.UIManageControls.FillList () inline private
    {
        List<UIElement> list = _bindsKeyboard;
        if (!OnKeyboard)
        {
            list = _bindsGamepad;
        }
        if (!OnGameplay)
        {
            list = (OnKeyboard ? _bindsKeyboardUI : _bindsGamepadUI);
        }
        _uilist.Clear();
        foreach (UIElement item in list)
        {
            _uilist.Add(item);
        }
    }
References Terraria.GameContent.UI.States.UIManageControls._bindsGamepad, Terraria.GameContent.UI.States.UIManageControls._bindsGamepadUI, Terraria.GameContent.UI.States.UIManageControls._bindsKeyboard, Terraria.GameContent.UI.States.UIManageControls._bindsKeyboardUI, Terraria.GameContent.UI.States.UIManageControls._uilist, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.GameContent.UI.States.UIManageControls.OnGameplay, and Terraria.GameContent.UI.States.UIManageControls.OnKeyboard.
Referenced by Terraria.GameContent.UI.States.UIManageControls.GamepadButtonClick(), Terraria.GameContent.UI.States.UIManageControls.KeyboardButtonClick(), Terraria.GameContent.UI.States.UIManageControls.OnInitialize(), Terraria.GameContent.UI.States.UIManageControls.VsGameplayButtonClick(), and Terraria.GameContent.UI.States.UIManageControls.VsMenuButtonClick().