Terraria: System.TimeZoneInfo.StringSerializer.GetNextInt32Value
GetNextInt32Value()
int System.TimeZoneInfo.StringSerializer.GetNextInt32Value () inline private
Definition at line 570 of file TimeZoneInfo.cs.
        {
            string nextStringValue = GetNextStringValue();
            if (!int.TryParse(nextStringValue, NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out var result))
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            return result;
        }
References System.TimeZoneInfo.StringSerializer.GetNextStringValue(), System.Globalization.CultureInfo.InvariantCulture, and System.SR.Serialization_InvalidData.
Referenced by System.TimeZoneInfo.StringSerializer.GetNextAdjustmentRuleValue(), System.TimeZoneInfo.StringSerializer.GetNextTimeSpanValue(), and System.TimeZoneInfo.StringSerializer.GetNextTransitionTimeValue().