Terraria: System.TimeZoneInfo.StringSerializer.GetNextAdjustmentRuleValue
GetNextAdjustmentRuleValue()
AdjustmentRule System.TimeZoneInfo.StringSerializer.GetNextAdjustmentRuleValue () inline private
Definition at line 604 of file TimeZoneInfo.cs.
        {
            if (_state == State.EndOfLine)
            {
                return null;
            }
            if (_currentTokenStartIndex < 0 || _currentTokenStartIndex >= _serializedText.Length)
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            if (_serializedText[_currentTokenStartIndex] == ';')
            {
                return null;
            }
            if (_serializedText[_currentTokenStartIndex] != '[')
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            _currentTokenStartIndex++;
            DateTime nextDateTimeValue = GetNextDateTimeValue("MM:dd:yyyy");
            DateTime nextDateTimeValue2 = GetNextDateTimeValue("MM:dd:yyyy");
            TimeSpan nextTimeSpanValue = GetNextTimeSpanValue();
            TransitionTime nextTransitionTimeValue = GetNextTransitionTimeValue();
            TransitionTime nextTransitionTimeValue2 = GetNextTransitionTimeValue();
            TimeSpan baseUtcOffsetDelta = TimeSpan.Zero;
            int num = 0;
            if (_state == State.EndOfLine || _currentTokenStartIndex >= _serializedText.Length)
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            if ((_serializedText[_currentTokenStartIndex] >= '0' && _serializedText[_currentTokenStartIndex] <= '9') || _serializedText[_currentTokenStartIndex] == '-' || _serializedText[_currentTokenStartIndex] == '+')
            {
                baseUtcOffsetDelta = GetNextTimeSpanValue();
            }
            if (_serializedText[_currentTokenStartIndex] >= '0' && _serializedText[_currentTokenStartIndex] <= '1')
            {
                num = GetNextInt32Value();
            }
            if (_state == State.EndOfLine || _currentTokenStartIndex >= _serializedText.Length)
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            if (_serializedText[_currentTokenStartIndex] != ']')
            {
                SkipVersionNextDataFields(1);
            }
            else
            {
                _currentTokenStartIndex++;
            }
            AdjustmentRule result;
            try
            {
                result = AdjustmentRule.CreateAdjustmentRule(nextDateTimeValue, nextDateTimeValue2, nextTimeSpanValue, nextTransitionTimeValue, nextTransitionTimeValue2, baseUtcOffsetDelta, num > 0);
            }
            catch (ArgumentException innerException)
            {
                throw new SerializationException(SR.Serialization_InvalidData, innerException);
            }
            if (_currentTokenStartIndex >= _serializedText.Length)
            {
                _state = State.EndOfLine;
            }
            else
            {
                _state = State.StartOfToken;
            }
            return result;
        }
References System.TimeZoneInfo.StringSerializer._currentTokenStartIndex, System.TimeZoneInfo.StringSerializer._serializedText, System.TimeZoneInfo.StringSerializer._state, System.TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(), System.TimeZoneInfo.StringSerializer.GetNextDateTimeValue(), System.TimeZoneInfo.StringSerializer.GetNextInt32Value(), System.TimeZoneInfo.StringSerializer.GetNextTimeSpanValue(), System.TimeZoneInfo.StringSerializer.GetNextTransitionTimeValue(), System.SR.Serialization_InvalidData, System.TimeZoneInfo.StringSerializer.SkipVersionNextDataFields(), and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.StringSerializer.GetNextAdjustmentRuleArrayValue().