Terraria: System.TimeZoneInfo.StringSerializer.GetNextTransitionTimeValue
GetNextTransitionTimeValue()
TransitionTime System.TimeZoneInfo.StringSerializer.GetNextTransitionTimeValue () inline private
Definition at line 674 of file TimeZoneInfo.cs.
        {
            if (_state == State.EndOfLine || (_currentTokenStartIndex < _serializedText.Length && _serializedText[_currentTokenStartIndex] == ']'))
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            if (_currentTokenStartIndex < 0 || _currentTokenStartIndex >= _serializedText.Length)
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            if (_serializedText[_currentTokenStartIndex] != '[')
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            _currentTokenStartIndex++;
            int nextInt32Value = GetNextInt32Value();
            if (nextInt32Value != 0 && nextInt32Value != 1)
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            DateTime nextDateTimeValue = GetNextDateTimeValue("HH:mm:ss.FFF");
            nextDateTimeValue = new DateTime(1, 1, 1, nextDateTimeValue.Hour, nextDateTimeValue.Minute, nextDateTimeValue.Second, nextDateTimeValue.Millisecond);
            int nextInt32Value2 = GetNextInt32Value();
            TransitionTime result;
            if (nextInt32Value == 1)
            {
                int nextInt32Value3 = GetNextInt32Value();
                try
                {
                    result = TransitionTime.CreateFixedDateRule(nextDateTimeValue, nextInt32Value2, nextInt32Value3);
                }
                catch (ArgumentException innerException)
                {
                    throw new SerializationException(SR.Serialization_InvalidData, innerException);
                }
            }
            else
            {
                int nextInt32Value4 = GetNextInt32Value();
                int nextInt32Value5 = GetNextInt32Value();
                try
                {
                    result = TransitionTime.CreateFloatingDateRule(nextDateTimeValue, nextInt32Value2, nextInt32Value4, (DayOfWeek)nextInt32Value5);
                }
                catch (ArgumentException innerException2)
                {
                    throw new SerializationException(SR.Serialization_InvalidData, innerException2);
                }
            }
            if (_state == State.EndOfLine || _currentTokenStartIndex >= _serializedText.Length)
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            if (_serializedText[_currentTokenStartIndex] != ']')
            {
                SkipVersionNextDataFields(1);
            }
            else
            {
                _currentTokenStartIndex++;
            }
            bool flag = false;
            if (_currentTokenStartIndex < _serializedText.Length && _serializedText[_currentTokenStartIndex] == ';')
            {
                _currentTokenStartIndex++;
                flag = true;
            }
            if (!flag)
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            if (_currentTokenStartIndex >= _serializedText.Length)
            {
                _state = State.EndOfLine;
            }
            else
            {
                _state = State.StartOfToken;
            }
            return result;
        }
References System.TimeZoneInfo.StringSerializer._currentTokenStartIndex, System.TimeZoneInfo.StringSerializer._serializedText, System.TimeZoneInfo.StringSerializer._state, System.TimeZoneInfo.TransitionTime.CreateFixedDateRule(), System.TimeZoneInfo.TransitionTime.CreateFloatingDateRule(), System.DateTime, System.TimeZoneInfo.StringSerializer.GetNextDateTimeValue(), System.TimeZoneInfo.StringSerializer.GetNextInt32Value(), System.SR.Serialization_InvalidData, and System.TimeZoneInfo.StringSerializer.SkipVersionNextDataFields().
Referenced by System.TimeZoneInfo.StringSerializer.GetNextAdjustmentRuleValue().