Terraria: System.TimeZoneInfo.StringSerializer.GetNextDateTimeValue
GetNextDateTimeValue()
DateTime System.TimeZoneInfo.StringSerializer.GetNextDateTimeValue (string format) inline private
Definition at line 547 of file TimeZoneInfo.cs.
        {
            string nextStringValue = GetNextStringValue();
            if (!DateTime.TryParseExact(nextStringValue, format, DateTimeFormatInfo.InvariantInfo, DateTimeStyles.None, out var result))
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            return result;
        }
References System.format, System.TimeZoneInfo.StringSerializer.GetNextStringValue(), System.Globalization.DateTimeFormatInfo.InvariantInfo, System.SR.Serialization_InvalidData, and System.DateTime.TryParseExact().
Referenced by System.TimeZoneInfo.StringSerializer.GetNextAdjustmentRuleValue(), and System.TimeZoneInfo.StringSerializer.GetNextTransitionTimeValue().