Terraria: System.TimeZoneInfo.StringSerializer.SkipVersionNextDataFields
SkipVersionNextDataFields()
void System.TimeZoneInfo.StringSerializer.SkipVersionNextDataFields (int depth) inline private
Definition at line 439 of file TimeZoneInfo.cs.
        {
            if (_currentTokenStartIndex < 0 || _currentTokenStartIndex >= _serializedText.Length)
            {
                throw new SerializationException(SR.Serialization_InvalidData);
            }
            State state = State.NotEscaped;
            for (int i = _currentTokenStartIndex; i < _serializedText.Length; i++)
            {
                switch (state)
                {
                case State.Escaped:
                    VerifyIsEscapableCharacter(_serializedText[i]);
                    state = State.NotEscaped;
                    break;
                case State.NotEscaped:
                    switch (_serializedText[i])
                    {
                    case '\\':
                        state = State.Escaped;
                        break;
                    case '[':
                        depth++;
                        break;
                    case ']':
                        depth--;
                        if (depth == 0)
{
                            _currentTokenStartIndex = i + 1;
                            if (_currentTokenStartIndex >= _serializedText.Length)
{
                                _state = State.EndOfLine;
                            }
                            else
{
                                _state = State.StartOfToken;
                            }
                            return;
                        }
                        break;
                    case '\0':
                        throw new SerializationException(SR.Serialization_InvalidData);
                    }
                    break;
                }
            }
            throw new SerializationException(SR.Serialization_InvalidData);
        }
References System.TimeZoneInfo.StringSerializer._currentTokenStartIndex, System.TimeZoneInfo.StringSerializer._serializedText, System.TimeZoneInfo.StringSerializer._state, System.SR.Serialization_InvalidData, System.state, and System.TimeZoneInfo.StringSerializer.VerifyIsEscapableCharacter().
Referenced by System.TimeZoneInfo.StringSerializer.GetNextAdjustmentRuleValue(), and System.TimeZoneInfo.StringSerializer.GetNextTransitionTimeValue().