Terraria: System.Linq.Enumerable.EnumerablePartition.ToArray
ToArray()
TSource[] System.Linq.Enumerable.EnumerablePartition< TSource >.ToArray () inline
Definition at line 1184 of file Enumerable.cs.
        {
            using (IEnumerator<TSource> enumerator = _source.GetEnumerator())
            {
                if (SkipBeforeFirst(enumerator) && enumerator.MoveNext())
                {
                    int num = Limit - 1;
                    int num2 = ((!HasLimit) ? int.MinValue : 0);
                    int maxCapacity = (HasLimit ? Limit : int.MaxValue);
                    LargeArrayBuilder<TSource> largeArrayBuilder = new LargeArrayBuilder<TSource>(maxCapacity);
                    do
                    {
                        num--;
                        largeArrayBuilder.Add(enumerator.Current);
                    }
                    while (num >= num2 && enumerator.MoveNext());
                    return largeArrayBuilder.ToArray();
                }
            }
            return Array.Empty<TSource>();
        }
References System.Linq.Enumerable.EnumerablePartition< TSource >._source, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.IEnumerable.GetEnumerator(), System.Linq.Enumerable.EnumerablePartition< TSource >.HasLimit, System.Linq.Enumerable.EnumerablePartition< TSource >.Limit, and System.Linq.Enumerable.EnumerablePartition< TSource >.SkipBeforeFirst().