Terraria: System.Linq.Enumerable.EnumerablePartition.MoveNext
MoveNext()
override bool System.Linq.Enumerable.EnumerablePartition< TSource >.MoveNext () inline
Implements System.Collections.IEnumerator.
Definition at line 1050 of file Enumerable.cs.
        {
            int num = _state - 3;
            if (num < -2)
            {
                Dispose();
                return false;
            }
            int state = _state;
            if (state != 1)
            {
                if (state != 2)
                {
                    goto IL_0054;
                }
            }
            else
            {
                _enumerator = _source.GetEnumerator();
                _state = 2;
            }
            if (SkipBeforeFirst(_enumerator))
            {
                _state = 3;
                goto IL_0054;
            }
            goto IL_009b;
            IL_009b:
            Dispose();
            return false;
            IL_0054:
            if ((!HasLimit || num < Limit) && _enumerator.MoveNext())
            {
                if (HasLimit)
                {
                    _state++;
                }
                _current = _enumerator.Current;
                return true;
            }
            goto IL_009b;
        }
References System.Linq.Enumerable.Iterator< TSource >._current, System.Linq.Enumerable.EnumerablePartition< TSource >._enumerator, System.Linq.Enumerable.EnumerablePartition< TSource >._source, System.Linq.Enumerable.Iterator< TSource >._state, System.Collections.IEnumerator.Current, System.Linq.Enumerable.EnumerablePartition< TSource >.Dispose(), System.Collections.IEnumerable.GetEnumerator(), System.Linq.Enumerable.EnumerablePartition< TSource >.HasLimit, System.Linq.Enumerable.EnumerablePartition< TSource >.Limit, System.Collections.IEnumerator.MoveNext(), System.Linq.Enumerable.EnumerablePartition< TSource >.SkipBeforeFirst(), and System.state.