Terraria: System.Xml.Serialization.Compiler.GetTempAssemblyName
GetTempAssemblyName()
static string System.Xml.Serialization.Compiler.GetTempAssemblyName (AssemblyName parent, string ns) inline static package
Definition at line 82 of file Compiler.cs.
    {
        return parent.Name + ".XmlSerializers" + (string.IsNullOrEmpty(ns) ? "" : $".{GetPersistentHashCode(ns)}");
    }
References System.Xml.Dictionary.
Referenced by System.Xml.Serialization.XmlSerializer.XmlSerializer(), System.Xml.Serialization.XmlSerializer.FromMappings(), System.Xml.Serialization.XmlSerializer.GetXmlSerializerAssemblyName(), and System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly().