Terraria: System.Xml.Serialization.Compiler.AddImport
AddImport() [2/2]
void System.Xml.Serialization.Compiler.AddImport (Type type, Hashtable types) inline package
Definition at line 20 of file Compiler.cs.
    {
        if (type == null || TypeScope.IsKnownType(type) || types[type] != null)
        {
            return;
        }
        types[type] = type;
        Type baseType = type.BaseType;
        if (baseType != null)
        {
            AddImport(baseType, types);
        }
        Type declaringType = type.DeclaringType;
        if (declaringType != null)
        {
            AddImport(declaringType, types);
        }
        Type[] interfaces = type.GetInterfaces();
        foreach (Type type2 in interfaces)
        {
            AddImport(type2, types);
        }
        ConstructorInfo[] constructors = type.GetConstructors();
        for (int j = 0; j < constructors.Length; j++)
        {
            ParameterInfo[] parameters = constructors[j].GetParameters();
            for (int k = 0; k < parameters.Length; k++)
            {
                AddImport(parameters[k].ParameterType, types);
            }
        }
        if (type.IsGenericType)
        {
            Type[] genericArguments = type.GetGenericArguments();
            for (int l = 0; l < genericArguments.Length; l++)
            {
                AddImport(genericArguments[l], types);
            }
        }
        Module module = type.Module;
        Assembly assembly = module.Assembly;
        if (DynamicAssemblies.IsTypeDynamic(type))
        {
            DynamicAssemblies.Add(assembly);
            return;
        }
        object[] customAttributes = type.GetCustomAttributes(typeof(TypeForwardedFromAttribute), inherit: false);
        if (customAttributes.Length != 0)
        {
            TypeForwardedFromAttribute typeForwardedFromAttribute = customAttributes[0] as TypeForwardedFromAttribute;
            Assembly.Load(new AssemblyName(typeForwardedFromAttribute.AssemblyFullName));
        }
    }
References System.Xml.Serialization.DynamicAssemblies.Add(), System.Xml.Serialization.Compiler.AddImport(), System.Type.BaseType, System.Type.DeclaringType, System.Xml.Dictionary, System.Type.GetGenericArguments(), System.Type.GetInterfaces(), System.Xml.Serialization.TypeScope.IsKnownType(), System.Xml.Serialization.DynamicAssemblies.IsTypeDynamic(), System.Reflection.Assembly.Load(), and System.type.
Referenced by System.Xml.Serialization.Compiler.AddImport().