Terraria: System.Linq.Enumerable.EnumerablePartition.GetCount
GetCount()
int System.Linq.Enumerable.EnumerablePartition< TSource >.GetCount (bool onlyIfCheap) inline
Definition at line 1035 of file Enumerable.cs.
        {
            if (onlyIfCheap)
            {
                return -1;
            }
            if (!HasLimit)
            {
                return Math.Max(_source.Count() - _minIndexInclusive, 0);
            }
            using IEnumerator<TSource> en = _source.GetEnumerator();
            uint num = SkipAndCount((uint)(_maxIndexInclusive + 1), en);
            return Math.Max((int)num - _minIndexInclusive, 0);
        }
References System.Linq.Enumerable.EnumerablePartition< TSource >._maxIndexInclusive, System.Linq.Enumerable.EnumerablePartition< TSource >._minIndexInclusive, System.Linq.Enumerable.EnumerablePartition< TSource >._source, System.Collections.IEnumerable.GetEnumerator(), System.Linq.Enumerable.EnumerablePartition< TSource >.HasLimit, System.Math.Max(), and System.Linq.Enumerable.EnumerablePartition< TSource >.SkipAndCount().