Terraria: IceShader.ProcessHighDetail
ProcessHighDetail()
void IceShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
     {
         for (int i = 0; i < fragment.Count; i++)
         {
             Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
             float dynamicNoise = NoiseHelper.GetDynamicNoise(new Vector2((canvasPositionOfIndex.X - canvasPositionOfIndex.Y) * 0.2f, 0f), time / 5f);
             dynamicNoise = Math.Max(0f, 1f - dynamicNoise * 1.5f);
             float dynamicNoise2 = NoiseHelper.GetDynamicNoise(new Vector2((canvasPositionOfIndex.X - canvasPositionOfIndex.Y) * 0.3f, 0.3f), time / 20f);
             dynamicNoise2 = Math.Max(0f, 1f - dynamicNoise2 * 5f);
             Vector4 value = Vector4.Lerp(_baseColor, _iceColor, dynamicNoise);
             value = Vector4.Lerp(value, _shineColor, dynamicNoise2);
             fragment.SetColor(i, value);
         }
     }
References _baseColor, _iceColor, _shineColor, Fragment.Count, Fragment.GetCanvasPositionOfIndex(), NoiseHelper.GetDynamicNoise(), and Fragment.SetColor().