Terraria: System.IO.Path.GetFileName
GetFileName() [1/2]
static ReadOnlySpan< char > System.IO.Path.GetFileName (ReadOnlySpan< char > path) inline static
Definition at line 214 of file Path.cs.
    {
        int length = GetPathRoot(path).Length;
        int num = path.Length;
        while (--num >= 0)
        {
            if (num < length || PathInternal.IsDirectorySeparator(path[num]))
            {
                return path.Slice(num + 1, path.Length - num - 1);
            }
        }
        return path;
    }
References System.IO.Path.GetPathRoot(), System.IO.PathInternal.IsDirectorySeparator(), System.length, System.ReadOnlySpan< T >.Length, and System.ReadOnlySpan< T >.Slice().