Terraria: System.IO.Path.Join
Join() [2/7]
static string System.IO.Path.Join (ReadOnlySpan< char > path1, ReadOnlySpan< char > path2) inline static
Definition at line 387 of file Path.cs.
    {
        if (path1.Length == 0)
        {
            return path2.ToString();
        }
        if (path2.Length == 0)
        {
            return path1.ToString();
        }
        return JoinInternal(path1, path2);
    }
References System.IO.Path.JoinInternal(), System.ReadOnlySpan< T >.Length, and System.ReadOnlySpan< T >.ToString().
Referenced by System.IO.Path.GetFullPath(), System.IO.FileSystem.GetImmediateLinkTarget(), System.IO.PathInternal.GetLinkTargetFullPath(), System.TimeZoneInfo.GetLocalizedNameByMuiNativeResource(), System.IO.Path.Join(), System.IO.Path.Join(), System.IO.Path.Join(), System.IO.Path.Join(), System.IO.Path.Join(), System.IO.Enumeration.FileSystemEnumerator< TResult >.MoveNext(), System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs(), System.IO.FileSystem.RemoveDirectoryRecursive(), System.IO.Enumeration.FileSystemEntry.ToFileSystemInfo(), System.IO.Enumeration.FileSystemEntry.ToFullPath(), and System.IO.Enumeration.FileSystemEntry.ToSpecifiedFullPath().