Terraria: System.IO.Path.GetFullPath
GetFullPath() [1/2]
static string System.IO.Path.GetFullPath (string path) inline static
Definition at line 881 of file Path.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (PathInternal.IsEffectivelyEmpty(path.AsSpan()))
        {
            throw new ArgumentException(SR.Arg_PathEmpty, "path");
        }
        if (path.Contains('\0'))
        {
            throw new ArgumentException(SR.Argument_InvalidPathChars, "path");
        }
        return GetFullPathInternal(path);
    }
References System.SR.Arg_PathEmpty, System.SR.Argument_InvalidPathChars, System.IO.Path.GetFullPathInternal(), and System.IO.PathInternal.IsEffectivelyEmpty().
Referenced by System.IO.DirectoryInfo.DirectoryInfo(), System.IO.FileInfo.FileInfo(), ReLogic.Content.Sources.FileSystemContentSource.FileSystemContentSource(), System.IO.Enumeration.FileSystemEnumerator< TResult >.FileSystemEnumerator(), System.IO.Strategies.Net5CompatFileStreamStrategy.Net5CompatFileStreamStrategy(), System.IO.Strategies.OSFileStreamStrategy.OSFileStreamStrategy(), ReLogic.Content.Sources.FileSystemContentSource.BuildNameToAbsolutePathDictionary(), System.IO.File.Copy(), System.IO.FileInfo.CopyTo(), System.IO.Pipes.NamedPipeServerStream.Create(), System.Net.Sockets.UnixDomainSocketEndPoint.CreateBoundEndPoint(), System.IO.Directory.CreateDirectory(), System.IO.DirectoryInfo.CreateSubdirectory(), System.IO.Directory.CreateSymbolicLink(), System.IO.File.CreateSymbolicLink(), System.IO.FileSystem.Decrypt(), System.IO.Directory.Delete(), System.IO.File.Delete(), System.IO.Directory.Delete(), System.IO.Compression.ZipFile.DoCreateFromDirectory(), System.IO.FileSystem.Encrypt(), System.Diagnostics.TextWriterTraceListener.EnsureWriter(), System.AppDomain.ExecuteAssembly(), System.IO.Directory.Exists(), System.IO.File.Exists(), System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory(), System.IO.File.GetAttributes(), System.Security.Cryptography.X509Certificates.X509Certificate2.GetCertContentType(), System.IO.File.GetCreationTime(), System.IO.File.GetCreationTimeUtc(), System.IO.Directory.GetDirectoryRoot(), System.Reflection.AssemblyName.GetFileInformationCore(), Terraria.Utilities.FileUtilities.GetFullPath(), System.IO.File.GetLastAccessTime(), System.IO.File.GetLastAccessTimeUtc(), System.IO.File.GetLastWriteTime(), System.IO.File.GetLastWriteTimeUtc(), System.IO.Directory.GetParent(), System.IO.Pipes.PipeStream.GetPipePath(), System.IO.Path.GetRelativePath(), System.Net.WebClient.GetUri(), System.Diagnostics.FileVersionInfo.GetVersionInfo(), System.IO.DirectoryInfo.Init(), System.Reflection.Assembly.LoadFile(), System.Reflection.Assembly.LoadFrom(), System.Reflection.Assembly.LoadFromResolveHandler(), System.IO.Directory.Move(), System.IO.File.Move(), System.IO.DirectoryInfo.MoveTo(), System.IO.FileInfo.MoveTo(), System.Net.WebClient.OpenFileInternal(), System.IO.File.OpenHandle(), System.IO.FileInfo.Replace(), System.IO.File.Replace(), System.Xml.XmlResolver.ResolveUri(), System.IO.FileSystemAclExtensions.SetAccessControl(), System.IO.FileSystemAclExtensions.SetAccessControl(), System.IO.File.SetAttributes(), System.IO.Directory.SetCreationTime(), System.IO.File.SetCreationTime(), System.IO.Directory.SetCreationTimeUtc(), System.IO.File.SetCreationTimeUtc(), System.IO.Directory.SetCurrentDirectory(), System.IO.Directory.SetLastAccessTime(), System.IO.File.SetLastAccessTime(), System.IO.Directory.SetLastAccessTimeUtc(), System.IO.File.SetLastAccessTimeUtc(), System.IO.Directory.SetLastWriteTime(), System.IO.File.SetLastWriteTime(), System.IO.Directory.SetLastWriteTimeUtc(), and System.IO.File.SetLastWriteTimeUtc().