Terraria: System.IO.Path.GetFullPath
GetFullPath() [2/2]
static string System.IO.Path.GetFullPath (string path, string basePath) inline static
Definition at line 898 of file Path.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (basePath == null)
        {
            throw new ArgumentNullException("basePath");
        }
        if (!IsPathFullyQualified(basePath))
        {
            throw new ArgumentException(SR.Arg_BasePathNotFullyQualified, "basePath");
        }
        if (basePath.Contains('\0') || path.Contains('\0'))
        {
            throw new ArgumentException(SR.Argument_InvalidPathChars);
        }
        if (IsPathFullyQualified(path))
        {
            return GetFullPathInternal(path);
        }
        if (PathInternal.IsEffectivelyEmpty(path.AsSpan()))
        {
            return basePath;
        }
        int length = path.Length;
        string text = ((length >= 1 && PathInternal.IsDirectorySeparator(path[0])) ? Join(GetPathRoot(basePath.AsSpan()), path.AsSpan(1)) : ((length < 2 || !PathInternal.IsValidDriveChar(path[0]) || path[1] != ':') ? JoinInternal(basePath.AsSpan(), path.AsSpan()) : ((!GetVolumeName(path.AsSpan()).EqualsOrdinal(GetVolumeName(basePath.AsSpan()))) ? ((!PathInternal.IsDevice(basePath.AsSpan())) ? path.Insert(2, "\\") : ((length == 2) ? JoinInternal(basePath.AsSpan(0, 4), path.AsSpan(), "\\".AsSpan()) : JoinInternal(basePath.AsSpan(0, 4), path.AsSpan(0, 2), "\\".AsSpan(), path.AsSpan(2)))) : Join(basePath.AsSpan(), path.AsSpan(2)))));
        if (!PathInternal.IsDevice(text.AsSpan()))
        {
            return GetFullPathInternal(text);
        }
        return PathInternal.RemoveRelativeSegments(text, PathInternal.GetRootLength(text.AsSpan()));
    }
References System.SR.Arg_BasePathNotFullyQualified, System.SR.Argument_InvalidPathChars, System.IO.Path.GetFullPathInternal(), System.IO.Path.GetPathRoot(), System.IO.PathInternal.GetRootLength(), System.IO.Path.GetVolumeName(), System.IO.PathInternal.IsDevice(), System.IO.PathInternal.IsDirectorySeparator(), System.IO.PathInternal.IsEffectivelyEmpty(), System.IO.Path.IsPathFullyQualified(), System.IO.PathInternal.IsValidDriveChar(), System.IO.Path.Join(), System.IO.Path.JoinInternal(), System.length, System.IO.PathInternal.RemoveRelativeSegments(), and System.text.