Terraria: System.IO.Path.GetRandomFileName
GetRandomFileName()
static unsafe string System.IO.Path.GetRandomFileName () inline static
Definition at line 254 of file Path.cs.
    {
        byte* ptr = stackalloc byte[8];
        Interop.GetRandomBytes(ptr, 8);
        return string.Create(12, (IntPtr)ptr, delegate(Span<char> span, IntPtr key)
        {
            Populate83FileNameFromRandomBytes((byte*)(void*)key, 8, span);
        });
    }
References Interop.GetRandomBytes(), System.key, and System.IO.Path.Populate83FileNameFromRandomBytes().
Referenced by System.IO.IsolatedStorage.Helper.GetRandomDirectory().