Terraria: System.IO.Path.TryJoin
TryJoin() [1/2]
static bool System.IO.Path.TryJoin (ReadOnlySpan< char > path1, ReadOnlySpan< char > path2, ReadOnlySpan< char > path3, Span< char > destination, out int charsWritten) inline static
Definition at line 526 of file Path.cs.
    {
        charsWritten = 0;
        if (path1.Length == 0 && path2.Length == 0 && path3.Length == 0)
        {
            return true;
        }
        if (path1.Length == 0)
        {
            return TryJoin(path2, path3, destination, out charsWritten);
        }
        if (path2.Length == 0)
        {
            return TryJoin(path1, path3, destination, out charsWritten);
        }
        if (path3.Length == 0)
        {
            return TryJoin(path1, path2, destination, out charsWritten);
        }
        int num = ((!EndsInDirectorySeparator(path1) && !PathInternal.StartsWithDirectorySeparator(path2)) ? 1 : 0);
        bool flag = !EndsInDirectorySeparator(path2) && !PathInternal.StartsWithDirectorySeparator(path3);
        if (flag)
        {
            num++;
        }
        int num2 = path1.Length + path2.Length + path3.Length + num;
        if (destination.Length < num2)
        {
            return false;
        }
        bool flag2 = TryJoin(path1, path2, destination, out charsWritten);
        if (flag)
        {
            destination[charsWritten++] = DirectorySeparatorChar;
        }
        path3.CopyTo(destination.Slice(charsWritten));
        charsWritten += path3.Length;
        return true;
    }
References System.ReadOnlySpan< T >.CopyTo(), System.destination, System.IO.Path.DirectorySeparatorChar, System.IO.Path.EndsInDirectorySeparator(), System.ReadOnlySpan< T >.Length, System.IO.PathInternal.StartsWithDirectorySeparator(), and System.IO.Path.TryJoin().