Terraria: System.IO.Path.IsPathFullyQualified
IsPathFullyQualified() [2/2]
static bool System.IO.Path.IsPathFullyQualified (string path) inline static
Definition at line 264 of file Path.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        return IsPathFullyQualified(path.AsSpan());
    }
References System.IO.Path.IsPathFullyQualified().
Referenced by System.IO.Path.GetFullPath(), System.Diagnostics.FileVersionInfo.GetVersionInfo(), System.IO.Path.IsPathFullyQualified(), System.StartupHookProvider.ProcessStartupHooks(), and System.Runtime.Loader.AssemblyDependencyResolver.ResolveUnmanagedDllToPath().