Terraria: System.IO.Path.Combine
Combine() [1/4]
static string System.IO.Path.Combine (params string[] paths) inline static
Definition at line 331 of file Path.cs.
    {
        if (paths == null)
        {
            throw new ArgumentNullException("paths");
        }
        int num = 0;
        int num2 = 0;
        for (int i = 0; i < paths.Length; i++)
        {
            if (paths[i] == null)
            {
                throw new ArgumentNullException("paths");
            }
            if (paths[i].Length != 0)
            {
                if (IsPathRooted(paths[i]))
                {
                    num2 = i;
                    num = paths[i].Length;
                }
                else
                {
                    num += paths[i].Length;
                }
                char c = paths[i][paths[i].Length - 1];
                if (!PathInternal.IsDirectorySeparator(c))
                {
                    num++;
                }
            }
        }
        Span<char> initialBuffer = stackalloc char[260];
        ValueStringBuilder valueStringBuilder = new ValueStringBuilder(initialBuffer);
        valueStringBuilder.EnsureCapacity(num);
        for (int j = num2; j < paths.Length; j++)
        {
            if (paths[j].Length == 0)
            {
                continue;
            }
            if (valueStringBuilder.Length == 0)
            {
                valueStringBuilder.Append(paths[j]);
                continue;
            }
            char c2 = valueStringBuilder[valueStringBuilder.Length - 1];
            if (!PathInternal.IsDirectorySeparator(c2))
            {
                valueStringBuilder.Append('\\');
            }
            valueStringBuilder.Append(paths[j]);
        }
        return valueStringBuilder.ToString();
    }
References System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.EnsureCapacity(), System.IO.PathInternal.IsDirectorySeparator(), System.IO.Path.IsPathRooted(), System.Text.ValueStringBuilder.Length, and System.Text.ValueStringBuilder.ToString().