Terraria: System.ComponentModel.DataAnnotations.RegularExpressionAttribute.SetupRegex
SetupRegex()
void System.ComponentModel.DataAnnotations.RegularExpressionAttribute.SetupRegex () inline private
Definition at line 44 of file RegularExpressionAttribute.cs.
    {
        if (Regex == null)
        {
            if (string.IsNullOrEmpty(Pattern))
            {
                throw new InvalidOperationException(System.SR.RegularExpressionAttribute_Empty_Pattern);
            }
            Regex = ((MatchTimeoutInMilliseconds == -1) ? new Regex(Pattern) : new Regex(Pattern, RegexOptions.None, TimeSpan.FromMilliseconds(MatchTimeoutInMilliseconds)));
        }
    }
References System.TimeSpan.FromMilliseconds(), System.ComponentModel.DataAnnotations.RegularExpressionAttribute.MatchTimeoutInMilliseconds, System.ComponentModel.DataAnnotations.RegularExpressionAttribute.Pattern, System.ComponentModel.DataAnnotations.RegularExpressionAttribute.Regex, and System.SR.RegularExpressionAttribute_Empty_Pattern.
Referenced by System.ComponentModel.DataAnnotations.RegularExpressionAttribute.FormatErrorMessage(), and System.ComponentModel.DataAnnotations.RegularExpressionAttribute.IsValid().