Terraria: System.IO.Path.GetFileName
GetFileName() [2/2]
static ? string System.IO.Path.GetFileName (string? path) inline static
Definition at line 200 of file Path.cs.
    {
        if (path == null)
        {
            return null;
        }
        ReadOnlySpan<char> fileName = GetFileName(path.AsSpan());
        if (path.Length == fileName.Length)
        {
            return path;
        }
        return fileName.ToString();
    }
References System.IO.Path.GetFileName(), System.ReadOnlySpan< T >.Length, and System.ReadOnlySpan< T >.ToString().
Referenced by System.Net.Mail.Attachment.Attachment(), System.Net.Mail.Attachment.Attachment(), System.Net.Mail.Attachment.Attachment(), System.IO.FileInfo.FileInfo(), Terraria.IO.ResourcePack.ResourcePack(), Terraria.IO.ResourcePackList.CreatePacksFromDirectories(), Terraria.IO.ResourcePackList.CreatePacksFromWorkshopFolders(), Terraria.IO.ResourcePackList.CreatePacksFromZips(), System.Diagnostics.TextWriterTraceListener.EnsureWriter(), System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory(), System.IO.IsolatedStorage.Helper.GetExistingRandomDirectory(), System.IO.Path.GetFileName(), System.IO.IsolatedStorage.IsolatedStorageFile.GetFileNames(), System.IO.Path.GetFileNameWithoutExtension(), System.ComponentModel.Design.RuntimeLicenseContext.GetSavedLicenseKey(), System.IO.DirectoryInfo.Init(), System.IO.IsolatedStorage.IsolatedStorageFile.IsIdFile(), System.IO.IsolatedStorage.IsolatedStorageFile.IsInfoFile(), System.IO.IsolatedStorage.IsolatedStorageFile.IsMatchingScopeDirectory(), System.IO.FileSystemWatcher.MatchPattern(), System.IO.Directory.Move(), System.IO.FileInfo.MoveTo(), and System.Net.WebClient.OpenFileInternal().