Terraria: System.IO.Path.GetPathRoot
GetPathRoot() [2/2]
static ? string System.IO.Path.GetPathRoot (string? path) inline static
Definition at line 1008 of file Path.cs.
    {
        if (PathInternal.IsEffectivelyEmpty(path.AsSpan()))
        {
            return null;
        }
        ReadOnlySpan<char> pathRoot = GetPathRoot(path.AsSpan());
        if (path.Length == pathRoot.Length)
        {
            return PathInternal.NormalizeDirectorySeparators(path);
        }
        return PathInternal.NormalizeDirectorySeparators(pathRoot.ToString());
    }
References System.IO.Path.GetPathRoot(), System.IO.PathInternal.IsEffectivelyEmpty(), System.ReadOnlySpan< T >.Length, System.IO.PathInternal.NormalizeDirectorySeparators(), and System.ReadOnlySpan< T >.ToString().
Referenced by System.IO.FileSystem.CreateDirectory(), System.IO.Directory.GetDirectoryRoot(), System.IO.Path.GetFileName(), System.IO.Path.GetFullPath(), System.IO.Path.GetPathRoot(), System.IO.Path.GetVolumeName(), System.IO.Directory.Move(), System.IO.DirectoryInfo.MoveTo(), System.IO.DriveInfoInternal.NormalizeDriveName(), System.IO.FileSystem.ThrowExceptionEncryptDecryptFail(), and System.IO.FileSystemAclExtensions.ValidateFileHandle().