Terraria: System.IO.Path.GetDirectoryName
GetDirectoryName() [2/2]
static ? string System.IO.Path.GetDirectoryName (string? path) inline static
Definition at line 121 of file Path.cs.
    {
        if (path == null || PathInternal.IsEffectivelyEmpty(path.AsSpan()))
        {
            return null;
        }
        int directoryNameOffset = GetDirectoryNameOffset(path.AsSpan());
        if (directoryNameOffset < 0)
        {
            return null;
        }
        return PathInternal.NormalizeDirectorySeparators(path.Substring(0, directoryNameOffset));
    }
References System.IO.Path.GetDirectoryNameOffset(), System.IO.PathInternal.IsEffectivelyEmpty(), and System.IO.PathInternal.NormalizeDirectorySeparators().
Referenced by System.Runtime.Loader.AssemblyDependencyResolver.AssemblyDependencyResolver(), System.Diagnostics.TextWriterTraceListener.EnsureWriter(), System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory(), System.AppContext.GetBaseDirectoryCore(), System.IO.IsolatedStorage.IsolatedStorageFile.GetDirectoryNames(), System.IO.FileSystem.GetImmediateLinkTarget(), System.ComponentModel.LicFileLicenseProvider.GetLicense(), System.IO.PathInternal.GetLinkTargetFullPath(), System.IO.Directory.GetParent(), System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory(), System.Xml.Serialization.TempAssembly.LoadAssemblyByPath(), System.Reflection.Assembly.LoadFromResolveHandler(), System.IO.FileInfo.MoveTo(), System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs(), System.IO.IsolatedStorage.IsolatedStorageFile.Remove(), System.Runtime.Loader.AssemblyLoadContext.ResolveSatelliteAssembly(), System.Data.XmlTreeGen.SetPath(), and System.Reflection.PortableExecutable.PEReader.TryOpenAssociatedPortablePdb().