Terraria: System.IO.Path.GetRelativePath
GetRelativePath() [2/2]
static string System.IO.Path.GetRelativePath (string relativeTo, string path, StringComparison comparisonType) inline static private
Definition at line 759 of file Path.cs.
    {
        if (relativeTo == null)
        {
            throw new ArgumentNullException("relativeTo");
        }
        if (PathInternal.IsEffectivelyEmpty(relativeTo.AsSpan()))
        {
            throw new ArgumentException(SR.Arg_PathEmpty, "relativeTo");
        }
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (PathInternal.IsEffectivelyEmpty(path.AsSpan()))
        {
            throw new ArgumentException(SR.Arg_PathEmpty, "path");
        }
        relativeTo = GetFullPath(relativeTo);
        path = GetFullPath(path);
        if (!PathInternal.AreRootsEqual(relativeTo, path, comparisonType))
        {
            return path;
        }
        int num = PathInternal.GetCommonPathLength(relativeTo, path, comparisonType == StringComparison.OrdinalIgnoreCase);
        if (num == 0)
        {
            return path;
        }
        int num2 = relativeTo.Length;
        if (EndsInDirectorySeparator(relativeTo.AsSpan()))
        {
            num2--;
        }
        bool flag = EndsInDirectorySeparator(path.AsSpan());
        int num3 = path.Length;
        if (flag)
        {
            num3--;
        }
        if (num2 == num3 && num >= num2)
        {
            return ".";
        }
        Span<char> initialBuffer = stackalloc char[260];
        ValueStringBuilder valueStringBuilder = new ValueStringBuilder(initialBuffer);
        valueStringBuilder.EnsureCapacity(Math.Max(relativeTo.Length, path.Length));
        if (num < num2)
        {
            valueStringBuilder.Append("..");
            for (int i = num + 1; i < num2; i++)
            {
                if (PathInternal.IsDirectorySeparator(relativeTo[i]))
                {
                    valueStringBuilder.Append(DirectorySeparatorChar);
                    valueStringBuilder.Append("..");
                }
            }
        }
        else if (PathInternal.IsDirectorySeparator(path[num]))
        {
            num++;
        }
        int num4 = num3 - num;
        if (flag)
        {
            num4++;
        }
        if (num4 > 0)
        {
            if (valueStringBuilder.Length > 0)
            {
                valueStringBuilder.Append(DirectorySeparatorChar);
            }
            valueStringBuilder.Append(path.AsSpan(num, num4));
        }
        return valueStringBuilder.ToString();
    }
References System.Text.ValueStringBuilder.Append(), System.IO.PathInternal.AreRootsEqual(), System.SR.Arg_PathEmpty, System.comparisonType, System.IO.Path.DirectorySeparatorChar, System.IO.Path.EndsInDirectorySeparator(), System.Text.ValueStringBuilder.EnsureCapacity(), System.IO.PathInternal.GetCommonPathLength(), System.IO.Path.GetFullPath(), System.IO.PathInternal.IsDirectorySeparator(), System.IO.PathInternal.IsEffectivelyEmpty(), System.Text.ValueStringBuilder.Length, System.Math.Max(), and System.Text.ValueStringBuilder.ToString().