Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadKey
LoadKey()
void System.Xml.Xsl.Xslt.XsltLoader.LoadKey (NsDecl stylesheetNsList) inline private
Definition at line 896 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_keyAttributes);
        attributes.nsList = MergeNamespaces(attributes.nsList, stylesheetNsList);
        QilName qilName = ParseQNameAttribute(0);
        string match = ParseStringAttribute(1, "match");
        string text = ParseStringAttribute(2, "use");
        ParseCollationAttribute(3);
        _input.MoveToElement();
        List<XslNode> list = null;
        if (V1)
        {
            if (text == null)
            {
                _input.SkipNode();
            }
            else
            {
                CheckNoContent();
            }
        }
        else
        {
            list = LoadInstructions();
            if (list.Count != 0)
            {
                list = LoadEndTag(list);
            }
            if (text == null == (list.Count == 0))
            {
                ReportError(System.SR.Xslt_KeyCntUse);
            }
            else if (text == null)
            {
                ReportNYI("xsl:key[count(@use) = 0]");
            }
        }
        Key item = (Key)SetInfo(AstFactory.Key(qilName, match, text, _input.XslVersion), null, attributes);
        if (_compiler.Keys.Contains(qilName))
        {
            _compiler.Keys[qilName].Add(item);
            return;
        }
        List<Key> list2 = new List<Key>();
        list2.Add(item);
        _compiler.Keys.Add(list2);
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._keyAttributes, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.Contains(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.item, System.Xml.Xsl.Xslt.AstFactory.Key(), System.Xml.Xsl.Xslt.Key, System.Xml.Xsl.Xslt.Compiler.Keys, System.list, System.Xml.Xsl.Xslt.XsltLoader.LoadEndTag(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.match, System.Xml.Xsl.Xslt.XsltLoader.MergeNamespaces(), System.Xml.Xsl.Xslt.XsltInput.MoveToElement(), System.Xml.Xsl.Xslt.XsltInput.ContextInfo.nsList, System.Xml.Xsl.Xslt.XsltLoader.ParseCollationAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseQNameAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.text, System.Xml.Xsl.Xslt.XsltLoader.V1, System.SR.Xslt_KeyCntUse, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().