Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadOutput
LoadOutput()
void System.Xml.Xsl.Xslt.XsltLoader.LoadOutput () inline private
Definition at line 684 of file XsltLoader.cs.
    {
        _input.GetAttributes(_outputAttributes);
        Output output = _compiler.Output;
        XmlWriterSettings settings = output.Settings;
        int currentPrecedence = _compiler.CurrentPrecedence;
        QilName qilName = ParseQNameAttribute(0);
        if (qilName != null)
        {
            ReportNYI("xsl:output/@name");
        }
        if (_input.MoveToXsltAttribute(1, "method") && output.MethodPrec <= currentPrecedence)
        {
            _compiler.EnterForwardsCompatible();
            XmlOutputMethod method;
            XmlQualifiedName xmlQualifiedName = ParseOutputMethod(_input.Value, out method);
            if (_compiler.ExitForwardsCompatible(_input.ForwardCompatibility) && xmlQualifiedName != null)
            {
                if (currentPrecedence == output.MethodPrec && !output.Method.Equals(xmlQualifiedName))
                {
                    ReportWarning(System.SR.Xslt_AttributeRedefinition, "method");
                }
                settings.OutputMethod = method;
                output.Method = xmlQualifiedName;
                output.MethodPrec = currentPrecedence;
            }
        }
        TriState triState = ParseYesNoAttribute(2, "byte-order-mark");
        if (triState != TriState.Unknown)
        {
            ReportNYI("xsl:output/@byte-order-mark");
        }
        if (_input.MoveToXsltAttribute(3, "cdata-section-elements"))
        {
            _compiler.EnterForwardsCompatible();
            string[] array = XmlConvert.SplitString(_input.Value);
            List<XmlQualifiedName> list = new List<XmlQualifiedName>();
            for (int i = 0; i < array.Length; i++)
            {
                list.Add(ResolveQName(ignoreDefaultNs: false, array[i]));
            }
            if (_compiler.ExitForwardsCompatible(_input.ForwardCompatibility))
            {
                settings.CDataSectionElements.AddRange(list);
            }
        }
        if (_input.MoveToXsltAttribute(4, "doctype-public") && output.DocTypePublicPrec <= currentPrecedence)
        {
            if (currentPrecedence == output.DocTypePublicPrec && settings.DocTypePublic != _input.Value)
            {
                ReportWarning(System.SR.Xslt_AttributeRedefinition, "doctype-public");
            }
            settings.DocTypePublic = _input.Value;
            output.DocTypePublicPrec = currentPrecedence;
        }
        if (_input.MoveToXsltAttribute(5, "doctype-system") && output.DocTypeSystemPrec <= currentPrecedence)
        {
            if (currentPrecedence == output.DocTypeSystemPrec && settings.DocTypeSystem != _input.Value)
            {
                ReportWarning(System.SR.Xslt_AttributeRedefinition, "doctype-system");
            }
            settings.DocTypeSystem = _input.Value;
            output.DocTypeSystemPrec = currentPrecedence;
        }
        if (_input.MoveToXsltAttribute(6, "encoding") && output.EncodingPrec <= currentPrecedence)
        {
            try
            {
                Encoding encoding = Encoding.GetEncoding(_input.Value);
                if (currentPrecedence == output.EncodingPrec && output.Encoding != _input.Value)
                {
                    ReportWarning(System.SR.Xslt_AttributeRedefinition, "encoding");
                }
                settings.Encoding = encoding;
                output.Encoding = _input.Value;
                output.EncodingPrec = currentPrecedence;
            }
            catch (ArgumentException)
            {
                if (!_input.ForwardCompatibility)
                {
                    ReportWarning(System.SR.Xslt_InvalidEncoding, _input.Value);
                }
            }
        }
        if (ParseYesNoAttribute(7, "escape-uri-attributes") == TriState.False)
        {
            ReportNYI("xsl:output/@escape-uri-attributes == flase()");
        }
        if (ParseYesNoAttribute(8, "include-content-type") == TriState.False)
        {
            ReportNYI("xsl:output/@include-content-type == flase()");
        }
        TriState triState2 = ParseYesNoAttribute(9, "indent");
        if (triState2 != TriState.Unknown && output.IndentPrec <= currentPrecedence)
        {
            bool flag = triState2 == TriState.True;
            if (currentPrecedence == output.IndentPrec && settings.Indent != flag)
            {
                ReportWarning(System.SR.Xslt_AttributeRedefinition, "indent");
            }
            settings.Indent = flag;
            output.IndentPrec = currentPrecedence;
        }
        if (_input.MoveToXsltAttribute(10, "media-type") && output.MediaTypePrec <= currentPrecedence)
        {
            if (currentPrecedence == output.MediaTypePrec && settings.MediaType != _input.Value)
            {
                ReportWarning(System.SR.Xslt_AttributeRedefinition, "media-type");
            }
            settings.MediaType = _input.Value;
            output.MediaTypePrec = currentPrecedence;
        }
        if (_input.MoveToXsltAttribute(11, "normalization-form"))
        {
            ReportNYI("xsl:output/@normalization-form");
        }
        triState2 = ParseYesNoAttribute(12, "omit-xml-declaration");
        if (triState2 != TriState.Unknown && output.OmitXmlDeclarationPrec <= currentPrecedence)
        {
            bool flag2 = triState2 == TriState.True;
            if (currentPrecedence == output.OmitXmlDeclarationPrec && settings.OmitXmlDeclaration != flag2)
            {
                ReportWarning(System.SR.Xslt_AttributeRedefinition, "omit-xml-declaration");
            }
            settings.OmitXmlDeclaration = flag2;
            output.OmitXmlDeclarationPrec = currentPrecedence;
        }
        triState2 = ParseYesNoAttribute(13, "standalone");
        if (triState2 != TriState.Unknown && output.StandalonePrec <= currentPrecedence)
        {
            XmlStandalone xmlStandalone = ((triState2 == TriState.True) ? XmlStandalone.Yes : XmlStandalone.No);
            if (currentPrecedence == output.StandalonePrec && settings.Standalone != xmlStandalone)
            {
                ReportWarning(System.SR.Xslt_AttributeRedefinition, "standalone");
            }
            settings.Standalone = xmlStandalone;
            output.StandalonePrec = currentPrecedence;
        }
        if (ParseYesNoAttribute(14, "undeclare-prefixes") == TriState.True)
        {
            ReportNYI("xsl:output/@undeclare-prefixes == true()");
        }
        List<QilName> list2 = ParseUseCharacterMaps(15);
        if (list2.Count != 0)
        {
            ReportNYI("xsl:output/@use-character-maps");
        }
        if (_input.MoveToXsltAttribute(16, "version") && output.VersionPrec <= currentPrecedence)
        {
            if (currentPrecedence == output.VersionPrec && output.Version != _input.Value)
            {
                ReportWarning(System.SR.Xslt_AttributeRedefinition, "version");
            }
            output.Version = _input.Value;
            output.VersionPrec = currentPrecedence;
        }
        CheckNoContent();
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._outputAttributes, System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), System.array, System.Xml.XmlWriterSettings.CDataSectionElements, System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Xslt.Compiler.CurrentPrecedence, System.Xml.Dictionary, System.Xml.XmlWriterSettings.DocTypePublic, System.Xml.XmlWriterSettings.DocTypeSystem, System.Xml.Xsl.Xslt.Compiler.EnterForwardsCompatible(), System.Xml.Xsl.Xslt.Compiler.ExitForwardsCompatible(), System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Text.Encoding.GetEncoding(), System.Xml.XmlWriterSettings.Indent, System.list, System.Xml.XmlWriterSettings.MediaType, System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.XmlWriterSettings.OmitXmlDeclaration, System.Xml.Xsl.Xslt.Compiler.Output, System.Xml.Xsl.Xslt.XsltLoader.ParseOutputMethod(), System.Xml.Xsl.Xslt.XsltLoader.ParseQNameAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseUseCharacterMaps(), System.Xml.Xsl.Xslt.XsltLoader.ParseYesNoAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.ReportWarning(), System.Xml.Xsl.Xslt.XsltLoader.ResolveQName(), System.Xml.XmlConvert.SplitString(), System.Xml.XmlWriterSettings.Standalone, System.Xml.Xsl.Xslt.XsltInput.Value, System.SR.Xslt_AttributeRedefinition, and System.SR.Xslt_InvalidEncoding.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().