Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet
LoadRealStylesheet()
void System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet () inline private
Definition at line 515 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_stylesheetAttributes);
        ParseValidationAttribute(2, defVal: true);
        ParseInputTypeAnnotationsAttribute(3);
        XsltInput.DelayedQName elementName = _input.ElementName;
        if (!_input.MoveToFirstChild())
        {
            return;
        }
        bool flag = true;
        do
        {
            bool flag2 = false;
            switch (_input.NodeType)
            {
            case XmlNodeType.Element:
                if (_input.IsXsltNamespace())
                {
                    if (_input.IsKeyword(_atoms.Import))
                    {
                        if (!flag)
{
                            ReportError(System.SR.Xslt_NotAtTop, _input.QualifiedName, elementName);
                            _input.SkipNode();
                        }
                        else
{
                            flag2 = true;
                            LoadImport();
                        }
                    }
                    else if (_input.IsKeyword(_atoms.Include))
                    {
                        LoadInclude();
                    }
                    else if (_input.IsKeyword(_atoms.StripSpace))
                    {
                        LoadStripSpace(attributes.nsList);
                    }
                    else if (_input.IsKeyword(_atoms.PreserveSpace))
                    {
                        LoadPreserveSpace(attributes.nsList);
                    }
                    else if (_input.IsKeyword(_atoms.Output))
                    {
                        LoadOutput();
                    }
                    else if (_input.IsKeyword(_atoms.Key))
                    {
                        LoadKey(attributes.nsList);
                    }
                    else if (_input.IsKeyword(_atoms.DecimalFormat))
                    {
                        LoadDecimalFormat(attributes.nsList);
                    }
                    else if (_input.IsKeyword(_atoms.NamespaceAlias))
                    {
                        LoadNamespaceAlias(attributes.nsList);
                    }
                    else if (_input.IsKeyword(_atoms.AttributeSet))
                    {
                        LoadAttributeSet(attributes.nsList);
                    }
                    else if (_input.IsKeyword(_atoms.Variable))
                    {
                        LoadGlobalVariableOrParameter(attributes.nsList, XslNodeType.Variable);
                    }
                    else if (_input.IsKeyword(_atoms.Param))
                    {
                        LoadGlobalVariableOrParameter(attributes.nsList, XslNodeType.Param);
                    }
                    else if (_input.IsKeyword(_atoms.Template))
                    {
                        LoadTemplate(attributes.nsList);
                    }
                    else
                    {
                        _input.GetVersionAttribute();
                        if (!_input.ForwardCompatibility)
{
                            ReportError(System.SR.Xslt_UnexpectedElement, _input.QualifiedName, elementName);
                        }
                        _input.SkipNode();
                    }
                }
                else if (_input.IsNs(_atoms.UrnMsxsl) && _input.IsKeyword(_atoms.Script))
                {
                    LoadMsScript(attributes.nsList);
                }
                else
                {
                    if (_input.IsNullNamespace())
                    {
                        ReportError(System.SR.Xslt_NullNsAtTopLevel, _input.LocalName);
                    }
                    _input.SkipNode();
                }
                flag = flag2;
                break;
            default:
                ReportError(System.SR.Xslt_TextNodesNotAllowed, elementName);
                break;
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                break;
            }
        }
        while (_input.MoveToNextSibling());
    }
References System.Xml.Xsl.Xslt.XsltLoader._atoms, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._stylesheetAttributes, System.Xml.Xsl.Xslt.KeywordsTable.AttributeSet, System.Xml.Xsl.Xslt.KeywordsTable.DecimalFormat, System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.ElementName, System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.GetVersionAttribute(), System.Xml.Xsl.Xslt.KeywordsTable.Import, System.Xml.Xsl.Xslt.KeywordsTable.Include, System.Xml.Xsl.Xslt.XsltInput.IsKeyword(), System.Xml.Xsl.Xslt.XsltInput.IsNs(), System.Xml.Xsl.Xslt.XsltInput.IsNullNamespace(), System.Xml.Xsl.Xslt.XsltInput.IsXsltNamespace(), System.Xml.Xsl.Xslt.KeywordsTable.Key, System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet(), System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat(), System.Xml.Xsl.Xslt.XsltLoader.LoadGlobalVariableOrParameter(), System.Xml.Xsl.Xslt.XsltLoader.LoadImport(), System.Xml.Xsl.Xslt.XsltLoader.LoadInclude(), System.Xml.Xsl.Xslt.XsltLoader.LoadKey(), System.Xml.Xsl.Xslt.XsltLoader.LoadMsScript(), System.Xml.Xsl.Xslt.XsltLoader.LoadNamespaceAlias(), System.Xml.Xsl.Xslt.XsltLoader.LoadOutput(), System.Xml.Xsl.Xslt.XsltLoader.LoadPreserveSpace(), System.Xml.Xsl.Xslt.XsltLoader.LoadStripSpace(), System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate(), System.Xml.Xsl.Xslt.XsltInput.LocalName, System.Xml.Xsl.Xslt.XsltInput.MoveToFirstChild(), System.Xml.Xsl.Xslt.XsltInput.MoveToNextSibling(), System.Xml.Xsl.Xslt.KeywordsTable.NamespaceAlias, System.Xml.Xsl.Xslt.XsltInput.NodeType, System.Xml.Xsl.Xslt.XsltInput.ContextInfo.nsList, System.Xml.Xsl.Xslt.KeywordsTable.Output, System.Xml.Xsl.Xslt.KeywordsTable.Param, System.Xml.Xsl.Xslt.XsltLoader.ParseInputTypeAnnotationsAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseValidationAttribute(), System.Xml.Xsl.Xslt.KeywordsTable.PreserveSpace, System.Xml.Xsl.Xslt.XsltInput.QualifiedName, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.KeywordsTable.Script, System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.Xml.Xsl.Xslt.KeywordsTable.StripSpace, System.Xml.Xsl.Xslt.KeywordsTable.Template, System.Xml.Xsl.Xslt.KeywordsTable.UrnMsxsl, System.Xml.Xsl.Xslt.KeywordsTable.Variable, System.SR.Xslt_NotAtTop, System.SR.Xslt_NullNsAtTopLevel, System.SR.Xslt_TextNodesNotAllowed, and System.SR.Xslt_UnexpectedElement.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadDocument().