Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslOtherwise
XslOtherwise()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslOtherwise () inline private
Definition at line 1490 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes();
        return SetInfo(AstFactory.Otherwise(), LoadInstructions(), attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.Xml.Xsl.Xslt.AstFactory.Otherwise(), and System.Xml.Xsl.Xslt.XsltLoader.SetInfo().
Referenced by System.Xml.Xsl.Xslt.XsltLoader.XslChoose().