Terraria: System.Xml.Xsl.Xslt.XsltLoader.Load
Load() [1/2]
void System.Xml.Xsl.Xslt.XsltLoader.Load (Compiler compiler, object stylesheet, XmlResolver xmlResolver) inline
Definition at line 290 of file XsltLoader.cs.
    {
        _compiler = compiler;
        _xmlResolver = xmlResolver ?? XmlNullResolver.Singleton;
        if (stylesheet is XmlReader reader)
        {
            _readerSettings = new QueryReaderSettings(reader);
            Load(reader);
        }
        else if (stylesheet is string text)
        {
            XmlResolver xmlResolver2 = xmlResolver;
            if (xmlResolver == null || xmlResolver == XmlNullResolver.Singleton)
            {
                xmlResolver2 = new XmlUrlResolver();
            }
            Uri uri = xmlResolver2.ResolveUri(null, text);
            if (uri == null)
            {
                throw new XslLoadException(System.SR.Xslt_CantResolve, text);
            }
            _readerSettings = new QueryReaderSettings(new NameTable());
            XmlReader reader2;
            using (reader2 = CreateReader(uri, xmlResolver2))
            {
                Load(reader2);
            }
        }
        else if (stylesheet is IXPathNavigable iXPathNavigable)
        {
            XmlReader reader2 = XPathNavigatorReader.Create(iXPathNavigable.CreateNavigator());
            _readerSettings = new QueryReaderSettings(reader2.NameTable);
            Load(reader2);
        }
        compiler.StartApplyTemplates = AstFactory.ApplyTemplates(nullMode);
        ProcessOutputSettings();
        foreach (AttributeSet value in compiler.AttributeSets.Values)
        {
            CheckAttributeSetsDfs(value);
        }
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._readerSettings, System.Xml.Xsl.Xslt.XsltLoader._xmlResolver, System.Xml.Xsl.Xslt.AstFactory.ApplyTemplates(), System.Xml.Xsl.Xslt.XsltLoader.CheckAttributeSetsDfs(), System.Xml.XPath.XPathNavigatorReader.Create(), System.Xml.Xsl.Xslt.XsltLoader.CreateReader(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltLoader.Load(), System.Xml.Xsl.Xslt.XsltLoader.nullMode, System.Xml.Xsl.Xslt.XsltLoader.ProcessOutputSettings(), System.Xml.XmlNullResolver.Singleton, System.text, System.value, System.Collections.Generic.Dictionary< TKey, TValue >.Values, and System.SR.Xslt_CantResolve.
Referenced by System.Xml.Xsl.Xslt.Compiler.Compile(), and System.Xml.Xsl.Xslt.XsltLoader.Load().