Terraria: System.Xml.Xsl.Xslt.XsltLoader.AddUseAttributeSets
AddUseAttributeSets()
void System.Xml.Xsl.Xslt.XsltLoader.AddUseAttributeSets (List< XslNode > list) inline private
Definition at line 2154 of file XsltLoader.cs.
    {
        _compiler.EnterForwardsCompatible();
        string[] array = XmlConvert.SplitString(_input.Value);
        foreach (string qname in array)
        {
            AddInstruction(list, SetLineInfo(AstFactory.UseAttributeSet(CreateXPathQName(qname)), _input.BuildLineInfo()));
        }
        if (!_compiler.ExitForwardsCompatible(_input.ForwardCompatibility))
        {
            list.Clear();
        }
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader.AddInstruction(), System.array, System.Xml.Xsl.Xslt.XsltInput.BuildLineInfo(), System.Xml.Xsl.Xslt.XsltLoader.CreateXPathQName(), System.Xml.Xsl.Xslt.Compiler.EnterForwardsCompatible(), System.Xml.Xsl.Xslt.Compiler.ExitForwardsCompatible(), System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.list, System.Xml.Xsl.Xslt.XsltLoader.SetLineInfo(), System.Xml.XmlConvert.SplitString(), System.Xml.Xsl.Xslt.AstFactory.UseAttributeSet(), and System.Xml.Xsl.Xslt.XsltInput.Value.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet(), System.Xml.Xsl.Xslt.XsltLoader.LoadLiteralResultElement(), System.Xml.Xsl.Xslt.XsltLoader.XslCopy(), and System.Xml.Xsl.Xslt.XsltLoader.XslElement().