Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslChoose
XslChoose()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslChoose () inline private
Definition at line 1424 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes();
        List<XslNode> content = new List<XslNode>();
        bool flag = false;
        bool flag2 = false;
        XsltInput.DelayedQName elementName = _input.ElementName;
        if (_input.MoveToFirstChild())
        {
            do
            {
                switch (_input.NodeType)
                {
                case XmlNodeType.Element:
                {
                    XslNode xslNode = null;
                    if (Ref.Equal(_input.NamespaceUri, _atoms.UriXsl))
                    {
                        if (Ref.Equal(_input.LocalName, _atoms.When))
{
                            if (flag)
{
                                ReportError(System.SR.Xslt_WhenAfterOtherwise);
                                _input.SkipNode();
                                break;
                            }
                            flag2 = true;
                            xslNode = XslIf();
                        }
                        else if (Ref.Equal(_input.LocalName, _atoms.Otherwise))
{
                            if (flag)
{
                                ReportError(System.SR.Xslt_DupOtherwise);
                                _input.SkipNode();
                                break;
                            }
                            flag = true;
                            xslNode = XslOtherwise();
                        }
                    }
                    if (xslNode == null)
                    {
                        ReportError(System.SR.Xslt_UnexpectedElement, _input.QualifiedName, elementName);
                        _input.SkipNode();
                    }
                    else
                    {
                        AddInstruction(content, xslNode);
                    }
                    break;
                }
                default:
                    ReportError(System.SR.Xslt_TextNodesNotAllowed, elementName);
                    break;
                case XmlNodeType.Whitespace:
                case XmlNodeType.SignificantWhitespace:
                    break;
                }
            }
            while (_input.MoveToNextSibling());
        }
        CheckError(!flag2, System.SR.Xslt_NoWhen);
        return SetInfo(AstFactory.Choose(), content, attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._atoms, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader.AddInstruction(), System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Xsl.Xslt.AstFactory.Choose(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.ElementName, System.Xml.Ref.Equal(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.LocalName, System.Xml.Xsl.Xslt.XsltInput.MoveToFirstChild(), System.Xml.Xsl.Xslt.XsltInput.MoveToNextSibling(), System.Xml.Xsl.Xslt.XsltInput.NamespaceUri, System.Xml.Xsl.Xslt.XsltInput.NodeType, System.Xml.Xsl.Xslt.KeywordsTable.Otherwise, System.Xml.Xsl.Xslt.XsltInput.QualifiedName, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.Xml.Xsl.Xslt.KeywordsTable.UriXsl, System.Xml.Xsl.Xslt.KeywordsTable.When, System.Xml.Xsl.Xslt.XsltLoader.XslIf(), System.Xml.Xsl.Xslt.XsltLoader.XslOtherwise(), System.SR.Xslt_DupOtherwise, System.SR.Xslt_NoWhen, System.SR.Xslt_TextNodesNotAllowed, System.SR.Xslt_UnexpectedElement, and System.SR.Xslt_WhenAfterOtherwise.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().