Terraria: System.Xml.Xsl.Xslt.XsltLoader.ParseInputTypeAnnotationsAttribute
ParseInputTypeAnnotationsAttribute()
void System.Xml.Xsl.Xslt.XsltLoader.ParseInputTypeAnnotationsAttribute (int attNum) inline private
Definition at line 2273 of file XsltLoader.cs.
    {
        if (!_input.MoveToXsltAttribute(attNum, "input-type-annotations"))
        {
            return;
        }
        string value = _input.Value;
        switch (value)
        {
        case "strip":
        case "preserve":
            if (_compiler.inputTypeAnnotations == null)
            {
                _compiler.inputTypeAnnotations = value;
            }
            else
            {
                CheckError(_compiler.inputTypeAnnotations != value, System.SR.Xslt_InputTypeAnnotations);
            }
            return;
        }
        if (!_input.ForwardCompatibility)
        {
            ReportError(System.SR.Xslt_InvalidAttrValue, "input-type-annotations", value);
        }
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.Compiler.inputTypeAnnotations, System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.value, System.Xml.Xsl.Xslt.XsltInput.Value, System.SR.Xslt_InputTypeAnnotations, and System.SR.Xslt_InvalidAttrValue.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().