Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat
LoadDecimalFormat()
void System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat (NsDecl stylesheetNsList) inline private
Definition at line 944 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_decimalFormatAttributes);
        attributes.nsList = MergeNamespaces(attributes.nsList, stylesheetNsList);
        XmlQualifiedName xmlQualifiedName;
        if (_input.MoveToXsltAttribute(0, "name"))
        {
            _compiler.EnterForwardsCompatible();
            xmlQualifiedName = ResolveQName(ignoreDefaultNs: true, _input.Value);
            if (!_compiler.ExitForwardsCompatible(_input.ForwardCompatibility))
            {
                xmlQualifiedName = new XmlQualifiedName();
            }
        }
        else
        {
            xmlQualifiedName = new XmlQualifiedName();
        }
        string text = DecimalFormatDecl.Default.InfinitySymbol;
        if (_input.MoveToXsltAttribute(1, "infinity"))
        {
            text = _input.Value;
        }
        string text2 = DecimalFormatDecl.Default.NanSymbol;
        if (_input.MoveToXsltAttribute(2, "NaN"))
        {
            text2 = _input.Value;
        }
        char[] characters = DecimalFormatDecl.Default.Characters;
        char[] array = new char[8];
        for (int i = 0; i < 8; i++)
        {
            array[i] = ParseCharAttribute(3 + i, _decimalFormatAttributes[3 + i].name, characters[i]);
        }
        for (int j = 0; j < 7; j++)
        {
            for (int k = j + 1; k < 7; k++)
            {
                if (array[j] == array[k])
                {
                    bool flag = _input.MoveToXsltAttribute(3 + k, _decimalFormatAttributes[3 + k].name) || _input.MoveToXsltAttribute(3 + j, _decimalFormatAttributes[3 + j].name);
                    ReportError(System.SR.Xslt_DecimalFormatSignsNotDistinct, _decimalFormatAttributes[3 + j].name, _decimalFormatAttributes[3 + k].name);
                    break;
                }
            }
        }
        if (_compiler.DecimalFormats.Contains(xmlQualifiedName))
        {
            DecimalFormatDecl decimalFormatDecl = _compiler.DecimalFormats[xmlQualifiedName];
            _input.MoveToXsltAttribute(1, "infinity");
            CheckError(text != decimalFormatDecl.InfinitySymbol, System.SR.Xslt_DecimalFormatRedefined, "infinity", text);
            _input.MoveToXsltAttribute(2, "NaN");
            CheckError(text2 != decimalFormatDecl.NanSymbol, System.SR.Xslt_DecimalFormatRedefined, "NaN", text2);
            for (int l = 0; l < 8; l++)
            {
                _input.MoveToXsltAttribute(3 + l, _decimalFormatAttributes[3 + l].name);
                CheckError(array[l] != decimalFormatDecl.Characters[l], System.SR.Xslt_DecimalFormatRedefined, _decimalFormatAttributes[3 + l].name, char.ToString(array[l]));
            }
        }
        else
        {
            DecimalFormatDecl item = new DecimalFormatDecl(xmlQualifiedName, text, text2, new string(array));
            _compiler.DecimalFormats.Add(item);
        }
        CheckNoContent();
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._decimalFormatAttributes, System.Xml.Xsl.Xslt.XsltLoader._input, System.array, System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.Contains(), System.Xml.Xsl.Xslt.Compiler.DecimalFormats, System.Xml.Xsl.Xslt.DecimalFormatDecl.Default, System.Xml.Dictionary, System.Xml.Xsl.Xslt.Compiler.EnterForwardsCompatible(), System.Xml.Xsl.Xslt.Compiler.ExitForwardsCompatible(), System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.item, System.Xml.Xsl.Xslt.XsltLoader.MergeNamespaces(), System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltInput.ContextInfo.nsList, System.Xml.Xsl.Xslt.XsltLoader.ParseCharAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ResolveQName(), System.text, System.Xml.Xsl.Xslt.XsltInput.Value, System.SR.Xslt_DecimalFormatRedefined, and System.SR.Xslt_DecimalFormatSignsNotDistinct.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().