Terraria: System.Xml.Xsl.Xslt.XsltLoader.ParseValidationAttribute
ParseValidationAttribute()
void System.Xml.Xsl.Xslt.XsltLoader.ParseValidationAttribute (int attNum, bool defVal) inline private
Definition at line 2241 of file XsltLoader.cs.
    {
        string text = (defVal ? _atoms.DefaultValidation : "validation");
        if (!_input.MoveToXsltAttribute(attNum, text))
        {
            return;
        }
        string value = _input.Value;
        switch (value)
        {
        case "strict":
            if (defVal)
            {
                goto default;
            }
            goto case "preserve";
        default:
            if (!(value == "lax") || defVal)
            {
                break;
            }
            goto case "preserve";
        case "preserve":
            ReportError(System.SR.Xslt_SchemaAttributeValue, text, value);
            return;
        }
        if (!_input.ForwardCompatibility)
        {
            ReportError(System.SR.Xslt_InvalidAttrValue, text, value);
        }
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.text, System.value, System.Xml.Xsl.Xslt.XsltInput.Value, System.SR.Xslt_InvalidAttrValue, and System.SR.Xslt_SchemaAttributeValue.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet(), System.Xml.Xsl.Xslt.XsltLoader.XslAttribute(), System.Xml.Xsl.Xslt.XsltLoader.XslCopy(), System.Xml.Xsl.Xslt.XsltLoader.XslCopyOf(), and System.Xml.Xsl.Xslt.XsltLoader.XslElement().