Terraria: System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent
CheckNoContent()
void System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent () inline private
Definition at line 2300 of file XsltLoader.cs.
    {
        _input.MoveToElement();
        XsltInput.DelayedQName elementName = _input.ElementName;
        ISourceLineInfo sourceLineInfo = SkipEmptyContent();
        if (sourceLineInfo != null)
        {
            _compiler.ReportError(sourceLineInfo, System.SR.Xslt_NotEmptyContents, elementName);
        }
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltInput.ElementName, System.Xml.Xsl.Xslt.XsltInput.MoveToElement(), System.Xml.Xsl.Xslt.Compiler.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.SkipEmptyContent(), and System.SR.Xslt_NotEmptyContents.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat(), System.Xml.Xsl.Xslt.XsltLoader.LoadImport(), System.Xml.Xsl.Xslt.XsltLoader.LoadInclude(), System.Xml.Xsl.Xslt.XsltLoader.LoadKey(), System.Xml.Xsl.Xslt.XsltLoader.LoadNamespaceAlias(), System.Xml.Xsl.Xslt.XsltLoader.LoadOutput(), System.Xml.Xsl.Xslt.XsltLoader.LoadPreserveSpace(), System.Xml.Xsl.Xslt.XsltLoader.LoadStripSpace(), System.Xml.Xsl.Xslt.XsltLoader.XslCopyOf(), System.Xml.Xsl.Xslt.XsltLoader.XslNumber(), System.Xml.Xsl.Xslt.XsltLoader.XslSort(), and System.Xml.Xsl.Xslt.XsltLoader.XslValueOf().