Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslApplyImports
XslApplyImports()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslApplyImports () inline private
Definition at line 1315 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes();
        if (!_input.CanHaveApplyImports)
        {
            ReportError(System.SR.Xslt_InvalidApplyImports);
            _input.SkipNode();
            return null;
        }
        List<XslNode> list = LoadWithParams(InstructionFlags.None);
        attributes.SaveExtendedLineInfo(_input);
        if (V1)
        {
            if (list.Count != 0)
            {
                ISourceLineInfo sourceLine = list[0].SourceLine;
                if (_input.ForwardCompatibility)
                {
                    return SetInfo(AstFactory.Error(XslLoadException.CreateMessage(sourceLine, System.SR.Xslt_NotEmptyContents, _atoms.ApplyImports)), null, attributes);
                }
                _compiler.ReportError(sourceLine, System.SR.Xslt_NotEmptyContents, _atoms.ApplyImports);
            }
            list = null;
        }
        else
        {
            if (list.Count != 0)
            {
                ReportNYI("xsl:apply-imports/xsl:with-param");
            }
            list = null;
        }
        return SetInfo(AstFactory.ApplyImports(_curTemplate.Mode, _curStylesheet, _input.XslVersion), list, attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._atoms, System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._curStylesheet, System.Xml.Xsl.Xslt.XsltLoader._curTemplate, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.AstFactory.ApplyImports(), System.Xml.Xsl.Xslt.KeywordsTable.ApplyImports, System.Xml.Xsl.Xslt.XsltInput.CanHaveApplyImports, System.Xml.Xsl.XslLoadException.CreateMessage(), System.Xml.Xsl.Xslt.AstFactory.Error(), System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.list, System.Xml.Xsl.Xslt.XsltLoader.LoadWithParams(), System.Xml.Xsl.Xslt.Template.Mode, System.Xml.Xsl.Xslt.Compiler.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltInput.ContextInfo.SaveExtendedLineInfo(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.Xml.Xsl.Xslt.XsltLoader.V1, System.SR.Xslt_InvalidApplyImports, System.SR.Xslt_NotEmptyContents, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().