Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate
LoadTemplate()
void System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate (NsDecl stylesheetNsList) inline private
Definition at line 1104 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_templateAttributes);
        attributes.nsList = MergeNamespaces(attributes.nsList, stylesheetNsList);
        string text = ParseStringAttribute(0, "match");
        QilName name = ParseQNameAttribute(1);
        double num = double.NaN;
        if (_input.MoveToXsltAttribute(2, "priority"))
        {
            num = XPathConvert.StringToDouble(_input.Value);
            if (double.IsNaN(num) && !_input.ForwardCompatibility)
            {
                ReportError(System.SR.Xslt_InvalidAttrValue, "priority", _input.Value);
            }
        }
        QilName mode = (V1 ? ParseModeAttribute(3) : ParseModeListAttribute(3));
        if (text == null)
        {
            CheckError(!_input.AttributeExists(1, "name"), System.SR.Xslt_BothMatchNameAbsent);
            CheckError(_input.AttributeExists(3, "mode"), System.SR.Xslt_ModeWithoutMatch);
            mode = nullMode;
            if (_input.AttributeExists(2, "priority"))
            {
                if (V1)
                {
                    ReportWarning(System.SR.Xslt_PriorityWithoutMatch);
                }
                else
                {
                    ReportError(System.SR.Xslt_PriorityWithoutMatch);
                }
            }
        }
        if (_input.MoveToXsltAttribute(4, "as"))
        {
            ReportNYI("xsl:template/@as");
        }
        _curTemplate = AstFactory.Template(name, text, mode, num, _input.XslVersion);
        _input.CanHaveApplyImports = text != null;
        SetInfo(_curTemplate, LoadEndTag(LoadInstructions(InstructionFlags.AllowParam)), attributes);
        if (!_curStylesheet.AddTemplate(_curTemplate))
        {
            ReportError(System.SR.Xslt_DupTemplateName, _curTemplate.Name.QualifiedName);
        }
        _curTemplate = null;
    }
References System.Xml.Xsl.Xslt.XsltLoader._curStylesheet, System.Xml.Xsl.Xslt.XsltLoader._curTemplate, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._templateAttributes, System.Xml.Xsl.Xslt.Stylesheet.AddTemplate(), System.Xml.Xsl.Xslt.XsltInput.AttributeExists(), System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltLoader.LoadEndTag(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.Xml.Xsl.Xslt.XsltLoader.MergeNamespaces(), System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XslNode.Name, System.Xml.Xsl.Xslt.XsltInput.ContextInfo.nsList, System.Xml.Xsl.Xslt.XsltLoader.nullMode, System.Xml.Xsl.Xslt.XsltLoader.ParseModeAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseModeListAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseQNameAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Qil.QilName.QualifiedName, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.ReportWarning(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.Xml.Xsl.XPathConvert.StringToDouble(), System.Xml.Xsl.Xslt.AstFactory.Template(), System.text, System.Xml.Xsl.Xslt.XsltLoader.V1, System.Xml.Xsl.Xslt.XsltInput.Value, System.SR.Xslt_BothMatchNameAbsent, System.SR.Xslt_DupTemplateName, System.SR.Xslt_InvalidAttrValue, System.SR.Xslt_ModeWithoutMatch, System.SR.Xslt_PriorityWithoutMatch, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().