Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslCallTemplate
XslCallTemplate()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslCallTemplate () inline private
Definition at line 1364 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_callTemplateAttributes);
        QilName name = ParseQNameAttribute(0);
        List<XslNode> content = LoadWithParams(InstructionFlags.None);
        attributes.SaveExtendedLineInfo(_input);
        return SetInfo(AstFactory.CallTemplate(name, attributes), content, attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._callTemplateAttributes, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.AstFactory.CallTemplate(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltLoader.LoadWithParams(), System.Xml.Xsl.Xslt.XsltLoader.ParseQNameAttribute(), System.Xml.Xsl.Xslt.XsltInput.ContextInfo.SaveExtendedLineInfo(), and System.Xml.Xsl.Xslt.XsltLoader.SetInfo().
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().