Terraria: System.Xml.Xsl.Xslt.XsltLoader.ReportError
ReportError()
void System.Xml.Xsl.Xslt.XsltLoader.ReportError (string res, params string[] args) inline
Implements System.Xml.Xsl.IErrorHelper.
Definition at line 2385 of file XsltLoader.cs.
    {
        _compiler.ReportError(_input.BuildNameLineInfo(), res, args);
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltInput.BuildNameLineInfo(), and System.Xml.Xsl.Xslt.Compiler.ReportError().
Referenced by System.Xml.Xsl.Xslt.XsltLoader.CheckWithParam(), System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet(), System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat(), System.Xml.Xsl.Xslt.XsltLoader.LoadDocument(), System.Xml.Xsl.Xslt.XsltLoader.LoadImport(), System.Xml.Xsl.Xslt.XsltLoader.LoadInclude(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.Xml.Xsl.Xslt.XsltLoader.LoadKey(), System.Xml.Xsl.Xslt.XsltLoader.LoadMsScript(), System.Xml.Xsl.Xslt.XsltLoader.LoadNamespaceAlias(), System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet(), System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate(), System.Xml.Xsl.Xslt.XsltLoader.LoadUnknownXsltInstruction(), System.Xml.Xsl.Xslt.XsltLoader.LoadWithParams(), System.Xml.Xsl.Xslt.XsltLoader.ParseCharAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseInputTypeAnnotationsAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseModeAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseModeListAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseOutputMethod(), System.Xml.Xsl.Xslt.XsltLoader.ParseValidationAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseYesNoAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.XslApplyImports(), System.Xml.Xsl.Xslt.XsltLoader.XslChoose(), System.Xml.Xsl.Xslt.XsltLoader.XslNumber(), System.Xml.Xsl.Xslt.XsltLoader.XslText(), and System.Xml.Xsl.Xslt.XsltLoader.XslVarPar().