Terraria: System.Xml.Xsl.Xslt.XsltLoader.ParseUseCharacterMaps
ParseUseCharacterMaps()
List< QilName > System.Xml.Xsl.Xslt.XsltLoader.ParseUseCharacterMaps (int attNum) inline private
Definition at line 2168 of file XsltLoader.cs.
    {
        List<QilName> list = new List<QilName>();
        if (_input.MoveToXsltAttribute(attNum, "use-character-maps"))
        {
            _compiler.EnterForwardsCompatible();
            string[] array = XmlConvert.SplitString(_input.Value);
            foreach (string qname in array)
            {
                list.Add(CreateXPathQName(qname));
            }
            if (!_compiler.ExitForwardsCompatible(_input.ForwardCompatibility))
            {
                list.Clear();
            }
        }
        return list;
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.array, System.Xml.Xsl.Xslt.XsltLoader.CreateXPathQName(), System.Xml.Xsl.Xslt.Compiler.EnterForwardsCompatible(), System.Xml.Xsl.Xslt.Compiler.ExitForwardsCompatible(), System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.list, System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.XmlConvert.SplitString(), and System.Xml.Xsl.Xslt.XsltInput.Value.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadOutput().