Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadNamespaceAlias
LoadNamespaceAlias()
void System.Xml.Xsl.Xslt.XsltLoader.LoadNamespaceAlias (NsDecl stylesheetNsList) inline private
Definition at line 1011 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_namespaceAliasAttributes);
        attributes.nsList = MergeNamespaces(attributes.nsList, stylesheetNsList);
        string text = null;
        string text2 = null;
        string text3 = null;
        if (_input.MoveToXsltAttribute(0, "stylesheet-prefix"))
        {
            if (_input.Value.Length == 0)
            {
                ReportError(System.SR.Xslt_EmptyNsAlias, "stylesheet-prefix");
            }
            else
            {
                text = _input.LookupXmlNamespace((_input.Value == "#default") ? string.Empty : _input.Value);
            }
        }
        if (_input.MoveToXsltAttribute(1, "result-prefix"))
        {
            if (_input.Value.Length == 0)
            {
                ReportError(System.SR.Xslt_EmptyNsAlias, "result-prefix");
            }
            else
            {
                text2 = ((_input.Value == "#default") ? string.Empty : _input.Value);
                text3 = _input.LookupXmlNamespace(text2);
            }
        }
        CheckNoContent();
        if (text != null && text3 != null && _compiler.SetNsAlias(text, text3, text2, _curStylesheet.ImportPrecedence))
        {
            _input.MoveToElement();
            ReportWarning(System.SR.Xslt_DupNsAlias, text);
        }
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._curStylesheet, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._namespaceAliasAttributes, System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.Stylesheet.ImportPrecedence, System.Xml.Xsl.Xslt.XsltInput.LookupXmlNamespace(), System.Xml.Xsl.Xslt.XsltLoader.MergeNamespaces(), System.Xml.Xsl.Xslt.XsltInput.MoveToElement(), System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltInput.ContextInfo.nsList, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportWarning(), System.Xml.Xsl.Xslt.Compiler.SetNsAlias(), System.text, System.Xml.Xsl.Xslt.XsltInput.Value, System.SR.Xslt_DupNsAlias, and System.SR.Xslt_EmptyNsAlias.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().