Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadSimplifiedStylesheet
LoadSimplifiedStylesheet()
void System.Xml.Xsl.Xslt.XsltLoader.LoadSimplifiedStylesheet () inline private
Definition at line 499 of file XsltLoader.cs.
    {
        _curTemplate = AstFactory.Template(null, "/", nullMode, double.NaN, _input.XslVersion);
        _input.CanHaveApplyImports = true;
        XslNode xslNode = LoadLiteralResultElement(asStylesheet: true);
        if (xslNode != null)
        {
            SetLineInfo(_curTemplate, xslNode.SourceLine);
            List<XslNode> list = new List<XslNode>();
            list.Add(xslNode);
            SetContent(_curTemplate, list);
            _curStylesheet.AddTemplate(_curTemplate);
        }
        _curTemplate = null;
    }
References System.Xml.Xsl.Xslt.XsltLoader._curStylesheet, System.Xml.Xsl.Xslt.XsltLoader._curTemplate, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.Stylesheet.AddTemplate(), System.Xml.Dictionary, System.list, System.Xml.Xsl.Xslt.XsltLoader.LoadLiteralResultElement(), System.Xml.Xsl.Xslt.XsltLoader.nullMode, System.Xml.Xsl.Xslt.XsltLoader.SetContent(), System.Xml.Xsl.Xslt.XsltLoader.SetLineInfo(), System.Xml.Xsl.Xslt.AstFactory.Template(), and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadDocument().