Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions
LoadInstructions() [4/4]
List< XslNode > System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions (List< XslNode > content, InstructionFlags flags) inline private
Definition at line 1205 of file XsltLoader.cs.
    {
        if (++_loadInstructionsDepth > 1024 && System.LocalAppContextSwitches.LimitXPathComplexity)
        {
            throw XsltException.Create(System.SR.Xslt_InputTooComplex);
        }
        XsltInput.DelayedQName elementName = _input.ElementName;
        if (_input.MoveToFirstChild())
        {
            bool flag = true;
            int num = 0;
            do
            {
                XmlNodeType nodeType = _input.NodeType;
                XslNode instruction;
                if (nodeType != XmlNodeType.Element)
                {
                    if (nodeType == XmlNodeType.Whitespace)
                    {
                        continue;
                    }
                    if (nodeType != XmlNodeType.SignificantWhitespace)
                    {
                        flag = false;
                    }
                    instruction = SetLineInfo(AstFactory.Text(_input.Value), _input.BuildLineInfo());
                }
                else
                {
                    string namespaceUri = _input.NamespaceUri;
                    string localName = _input.LocalName;
                    if (namespaceUri == _atoms.UriXsl)
                    {
                        InstructionFlags instructionFlags = (Ref.Equal(localName, _atoms.Param) ? InstructionFlags.AllowParam : (Ref.Equal(localName, _atoms.Sort) ? InstructionFlags.AllowSort : InstructionFlags.None));
                        if (instructionFlags != 0)
{
                            string text = (((flags & instructionFlags) == 0) ? System.SR.Xslt_UnexpectedElement : ((!flag) ? System.SR.Xslt_NotAtTop : null));
                            if (text != null)
{
                                ReportError(text, _input.QualifiedName, elementName);
                                flag = false;
                                _input.SkipNode();
                                continue;
                            }
                        }
                        else
{
                            flag = false;
                        }
                        instruction = (Ref.Equal(localName, _atoms.ApplyImports) ? XslApplyImports() : (Ref.Equal(localName, _atoms.ApplyTemplates) ? XslApplyTemplates() : (Ref.Equal(localName, _atoms.CallTemplate) ? XslCallTemplate() : (Ref.Equal(localName, _atoms.Copy) ? XslCopy() : (Ref.Equal(localName, _atoms.CopyOf) ? XslCopyOf() : (Ref.Equal(localName, _atoms.Fallback) ? XslFallback() : (Ref.Equal(localName, _atoms.If) ? XslIf() : (Ref.Equal(localName, _atoms.Choose) ? XslChoose() : (Ref.Equal(localName, _atoms.ForEach) ? XslForEach() : (Ref.Equal(localName, _atoms.Message) ? XslMessage() : (Ref.Equal(localName, _atoms.Number) ? XslNumber() : (Ref.Equal(localName, _atoms.ValueOf) ? XslValueOf() : (Ref.Equal(localName, _atoms.Comment) ? XslComment() : (Ref.Equal(localName, _atoms.ProcessingInstruction) ? XslProcessingInstruction() : (Ref.Equal(localName, _atoms.Text) ? XslText() : (Ref.Equal(localName, _atoms.Element) ? XslElement() : (Ref.Equal(localName, _atoms.Attribute) ? XslAttribute() : (Ref.Equal(localName, _atoms.Variable) ? XslVarPar() : (Ref.Equal(localName, _atoms.Param) ? XslVarPar() : (Ref.Equal(localName, _atoms.Sort) ? XslSort(num++) : LoadUnknownXsltInstruction(elementName)))))))))))))))))))));
                    }
                    else
                    {
                        flag = false;
                        instruction = LoadLiteralResultElement(asStylesheet: false);
                    }
                }
                AddInstruction(content, instruction);
            }
            while (_input.MoveToNextSibling());
        }
        _loadInstructionsDepth--;
        return content;
    }
References System.Xml.Xsl.Xslt.XsltLoader._atoms, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._loadInstructionsDepth, System.Xml.Xsl.Xslt.XsltLoader.AddInstruction(), System.Xml.Xsl.Xslt.KeywordsTable.ApplyImports, System.Xml.Xsl.Xslt.KeywordsTable.ApplyTemplates, System.Xml.Xsl.Xslt.KeywordsTable.Attribute, System.Xml.Xsl.Xslt.XsltInput.BuildLineInfo(), System.Xml.Xsl.Xslt.KeywordsTable.CallTemplate, System.Xml.Xsl.Xslt.KeywordsTable.Choose, System.Xml.Xsl.Xslt.KeywordsTable.Comment, System.Xml.Xsl.Xslt.KeywordsTable.Copy, System.Xml.Xsl.Xslt.KeywordsTable.CopyOf, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.KeywordsTable.Element, System.Xml.Xsl.Xslt.XsltInput.ElementName, System.Xml.Ref.Equal(), System.Xml.Xsl.Xslt.KeywordsTable.Fallback, System.Xml.Xsl.Xslt.KeywordsTable.ForEach, System.Xml.Xsl.Xslt.KeywordsTable.If, System.LocalAppContextSwitches.LimitXPathComplexity, System.Xml.Xsl.Xslt.XsltLoader.LoadLiteralResultElement(), System.Xml.Xsl.Xslt.XsltLoader.LoadUnknownXsltInstruction(), System.Xml.Xsl.Xslt.XsltInput.LocalName, System.Xml.Xsl.Xslt.KeywordsTable.Message, System.Xml.Xsl.Xslt.XsltInput.MoveToFirstChild(), System.Xml.Xsl.Xslt.XsltInput.MoveToNextSibling(), System.Xml.Xsl.Xslt.XsltInput.NamespaceUri, System.Xml.Xsl.Xslt.XsltInput.NodeType, System.Xml.Xsl.Xslt.KeywordsTable.Number, System.Xml.Xsl.Xslt.KeywordsTable.Param, System.Xml.Xsl.Xslt.KeywordsTable.ProcessingInstruction, System.Xml.Xsl.Xslt.XsltInput.QualifiedName, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.SetLineInfo(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.Xml.Xsl.Xslt.KeywordsTable.Sort, System.text, System.Xml.Xsl.Xslt.AstFactory.Text(), System.Xml.Xsl.Xslt.KeywordsTable.Text, System.Xml.Xsl.Xslt.KeywordsTable.UriXsl, System.Xml.Xsl.Xslt.XsltInput.Value, System.Xml.Xsl.Xslt.KeywordsTable.ValueOf, System.Xml.Xsl.Xslt.KeywordsTable.Variable, System.Xml.Xsl.Xslt.XsltLoader.XslApplyImports(), System.Xml.Xsl.Xslt.XsltLoader.XslApplyTemplates(), System.Xml.Xsl.Xslt.XsltLoader.XslAttribute(), System.Xml.Xsl.Xslt.XsltLoader.XslCallTemplate(), System.Xml.Xsl.Xslt.XsltLoader.XslChoose(), System.Xml.Xsl.Xslt.XsltLoader.XslComment(), System.Xml.Xsl.Xslt.XsltLoader.XslCopy(), System.Xml.Xsl.Xslt.XsltLoader.XslCopyOf(), System.Xml.Xsl.Xslt.XsltLoader.XslElement(), System.Xml.Xsl.Xslt.XsltLoader.XslFallback(), System.Xml.Xsl.Xslt.XsltLoader.XslForEach(), System.Xml.Xsl.Xslt.XsltLoader.XslIf(), System.Xml.Xsl.Xslt.XsltLoader.XslMessage(), System.Xml.Xsl.Xslt.XsltLoader.XslNumber(), System.Xml.Xsl.Xslt.XsltLoader.XslProcessingInstruction(), System.Xml.Xsl.Xslt.XsltLoader.XslSort(), System.SR.Xslt_InputTooComplex, System.SR.Xslt_NotAtTop, System.Xml.Xsl.Xslt.XsltLoader.XslText(), System.Xml.Xsl.Xslt.XsltLoader.XslValueOf(), and System.Xml.Xsl.Xslt.XsltLoader.XslVarPar().