Terraria: System.Xml.Xsl.Xslt.XsltLoader.ParseOutputMethod
ParseOutputMethod()
XmlQualifiedName System.Xml.Xsl.Xslt.XsltLoader.ParseOutputMethod (string attValue, out XmlOutputMethod method) inline private
Definition at line 2121 of file XsltLoader.cs.
    {
        ResolveQName(ignoreDefaultNs: true, attValue, out var localName, out var namespaceName, out var prefix);
        method = XmlOutputMethod.AutoDetect;
        if (_compiler.IsPhantomNamespace(namespaceName))
        {
            return null;
        }
        if (prefix.Length == 0)
        {
            switch (localName)
            {
            case "xml":
                method = XmlOutputMethod.Xml;
                break;
            case "html":
                method = XmlOutputMethod.Html;
                break;
            case "text":
                method = XmlOutputMethod.Text;
                break;
            default:
                ReportError(System.SR.Xslt_InvalidAttrValue, "method", attValue);
                return null;
            }
        }
        else if (!_input.ForwardCompatibility)
        {
            ReportWarning(System.SR.Xslt_InvalidMethod, attValue);
        }
        return new XmlQualifiedName(localName, namespaceName);
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.Compiler.IsPhantomNamespace(), System.prefix, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportWarning(), System.Xml.Xsl.Xslt.XsltLoader.ResolveQName(), System.SR.Xslt_InvalidAttrValue, and System.SR.Xslt_InvalidMethod.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadOutput().