Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadLiteralResultElement
LoadLiteralResultElement()
XslNode System.Xml.Xsl.Xslt.XsltLoader.LoadLiteralResultElement (bool asStylesheet) inline private
Definition at line 1794 of file XsltLoader.cs.
    {
        string prefix = _input.Prefix;
        string localName = _input.LocalName;
        string namespaceUri = _input.NamespaceUri;
        XsltInput.ContextInfo literalAttributes = _input.GetLiteralAttributes(asStylesheet);
        if (_input.IsExtensionNamespace(namespaceUri))
        {
            return SetInfo(AstFactory.List(), LoadFallbacks(localName), literalAttributes);
        }
        List<XslNode> list = new List<XslNode>();
        for (int i = 1; _input.MoveToLiteralAttribute(i); i++)
        {
            if (_input.IsXsltNamespace() && _input.IsKeyword(_atoms.UseAttributeSets))
            {
                AddUseAttributeSets(list);
            }
        }
        for (int j = 1; _input.MoveToLiteralAttribute(j); j++)
        {
            if (!_input.IsXsltNamespace())
            {
                XslNode node = AstFactory.LiteralAttribute(AstFactory.QName(_input.LocalName, _input.NamespaceUri, _input.Prefix), _input.Value, _input.XslVersion);
                AddInstruction(list, SetLineInfo(node, literalAttributes.lineInfo));
            }
        }
        list = LoadEndTag(LoadInstructions(list));
        return SetInfo(AstFactory.LiteralElement(AstFactory.QName(localName, namespaceUri, prefix)), list, literalAttributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._atoms, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader.AddInstruction(), System.Xml.Xsl.Xslt.XsltLoader.AddUseAttributeSets(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.GetLiteralAttributes(), System.Xml.Xsl.Xslt.XsltInput.IsExtensionNamespace(), System.Xml.Xsl.Xslt.XsltInput.IsKeyword(), System.Xml.Xsl.Xslt.XsltInput.IsXsltNamespace(), System.list, System.Xml.Xsl.Xslt.AstFactory.List(), System.Xml.Xsl.Xslt.AstFactory.LiteralAttribute(), System.Xml.Xsl.Xslt.AstFactory.LiteralElement(), System.Xml.Xsl.Xslt.XsltLoader.LoadEndTag(), System.Xml.Xsl.Xslt.XsltLoader.LoadFallbacks(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.Xml.Xsl.Xslt.XsltInput.LocalName, System.Xml.Xsl.Xslt.XsltInput.MoveToLiteralAttribute(), System.Xml.Xsl.Xslt.XsltInput.NamespaceUri, System.prefix, System.Xml.Xsl.Xslt.XsltInput.Prefix, System.Xml.Xsl.Xslt.AstFactory.QName(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.Xml.Xsl.Xslt.XsltLoader.SetLineInfo(), System.Xml.Xsl.Xslt.KeywordsTable.UseAttributeSets, System.Xml.Xsl.Xslt.XsltInput.Value, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), and System.Xml.Xsl.Xslt.XsltLoader.LoadSimplifiedStylesheet().