Terraria: System.Xml.Xsl.Xslt.XsltLoader.ParseCharAttribute
ParseCharAttribute()
char System.Xml.Xsl.Xslt.XsltLoader.ParseCharAttribute (int attNum, string attName, char defVal) inline private
Definition at line 2196 of file XsltLoader.cs.
    {
        if (_input.MoveToXsltAttribute(attNum, attName))
        {
            if (_input.Value.Length == 1)
            {
                return _input.Value[0];
            }
            if (_input.IsRequiredAttribute(attNum) || !_input.ForwardCompatibility)
            {
                ReportError(System.SR.Xslt_CharAttribute, attName);
            }
        }
        return defVal;
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.IsRequiredAttribute(), System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltInput.Value, and System.SR.Xslt_CharAttribute.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat().