Terraria: System.Xml.Xsl.Xslt.XsltLoader.CheckUseAttrubuteSetInList
CheckUseAttrubuteSetInList()
void System.Xml.Xsl.Xslt.XsltLoader.CheckUseAttrubuteSetInList (IList< XslNode > list) inline private
Definition at line 858 of file XsltLoader.cs.
    {
        foreach (XslNode item in list)
        {
            switch (item.NodeType)
            {
            case XslNodeType.UseAttributeSet:
            {
                if (_compiler.AttributeSets.TryGetValue(item.Name, out var value))
                {
                    CheckAttributeSetsDfs(value);
                }
                break;
            }
            case XslNodeType.List:
                CheckUseAttrubuteSetInList(item.Content);
                break;
            }
        }
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.Compiler.AttributeSets, System.Xml.Xsl.Xslt.XsltLoader.CheckAttributeSetsDfs(), System.Xml.Xsl.Xslt.XsltLoader.CheckUseAttrubuteSetInList(), System.item, System.list, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.CheckAttributeSetsDfs(), and System.Xml.Xsl.Xslt.XsltLoader.CheckUseAttrubuteSetInList().