Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadDocument
LoadDocument()
void System.Xml.Xsl.Xslt.XsltLoader.LoadDocument () inline private
Definition at line 473 of file XsltLoader.cs.
    {
        if (!_input.FindStylesheetElement())
        {
            ReportError(System.SR.Xslt_WrongStylesheetElement);
            return;
        }
        if (_input.IsXsltNamespace())
        {
            if (_input.IsKeyword(_atoms.Stylesheet) || _input.IsKeyword(_atoms.Transform))
            {
                LoadRealStylesheet();
            }
            else
            {
                ReportError(System.SR.Xslt_WrongStylesheetElement);
                _input.SkipNode();
            }
        }
        else
        {
            LoadSimplifiedStylesheet();
        }
        _input.Finish();
    }
References System.Xml.Xsl.Xslt.XsltLoader._atoms, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltInput.FindStylesheetElement(), System.Xml.Xsl.Xslt.XsltInput.Finish(), System.Xml.Xsl.Xslt.XsltInput.IsKeyword(), System.Xml.Xsl.Xslt.XsltInput.IsXsltNamespace(), System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet(), System.Xml.Xsl.Xslt.XsltLoader.LoadSimplifiedStylesheet(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.Xml.Xsl.Xslt.KeywordsTable.Stylesheet, System.Xml.Xsl.Xslt.KeywordsTable.Transform, and System.SR.Xslt_WrongStylesheetElement.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet().