Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadEndTag
LoadEndTag()
List< XslNode > System.Xml.Xsl.Xslt.XsltLoader.LoadEndTag (List< XslNode > content) inline private
Definition at line 1844 of file XsltLoader.cs.
    {
        if (_compiler.IsDebug && !_input.IsEmptyElement)
        {
            AddInstruction(content, SetLineInfo(AstFactory.Nop(), _input.BuildLineInfo()));
        }
        return content;
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader.AddInstruction(), System.Xml.Xsl.Xslt.XsltInput.BuildLineInfo(), System.Xml.Xsl.Xslt.Compiler.IsDebug, System.Xml.Xsl.Xslt.XsltInput.IsEmptyElement, System.Xml.Xsl.Xslt.AstFactory.Nop(), and System.Xml.Xsl.Xslt.XsltLoader.SetLineInfo().
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet(), System.Xml.Xsl.Xslt.XsltLoader.LoadContent(), System.Xml.Xsl.Xslt.XsltLoader.LoadKey(), System.Xml.Xsl.Xslt.XsltLoader.LoadLiteralResultElement(), System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate(), System.Xml.Xsl.Xslt.XsltLoader.XslCopy(), System.Xml.Xsl.Xslt.XsltLoader.XslElement(), and System.Xml.Xsl.Xslt.XsltLoader.XslMessage().