Terraria: System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute
ParseStringAttribute()
string System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute (int attNum, string attName) inline private
Definition at line 2187 of file XsltLoader.cs.
    {
        if (_input.MoveToXsltAttribute(attNum, attName))
        {
            return _input.Value;
        }
        return null;
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), and System.Xml.Xsl.Xslt.XsltInput.Value.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadKey(), System.Xml.Xsl.Xslt.XsltLoader.LoadMsScript(), System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate(), System.Xml.Xsl.Xslt.XsltLoader.XslApplyTemplates(), System.Xml.Xsl.Xslt.XsltLoader.XslAttribute(), System.Xml.Xsl.Xslt.XsltLoader.XslComment(), System.Xml.Xsl.Xslt.XsltLoader.XslCopyOf(), System.Xml.Xsl.Xslt.XsltLoader.XslElement(), System.Xml.Xsl.Xslt.XsltLoader.XslForEach(), System.Xml.Xsl.Xslt.XsltLoader.XslIf(), System.Xml.Xsl.Xslt.XsltLoader.XslMessage(), System.Xml.Xsl.Xslt.XsltLoader.XslNumber(), System.Xml.Xsl.Xslt.XsltLoader.XslProcessingInstruction(), System.Xml.Xsl.Xslt.XsltLoader.XslSort(), System.Xml.Xsl.Xslt.XsltLoader.XslValueOf(), and System.Xml.Xsl.Xslt.XsltLoader.XslVarPar().