Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadGlobalVariableOrParameter
LoadGlobalVariableOrParameter()
void System.Xml.Xsl.Xslt.XsltLoader.LoadGlobalVariableOrParameter (NsDecl stylesheetNsList, XslNodeType nodeType) inline private
Definition at line 1097 of file XsltLoader.cs.
    {
        VarPar varPar = XslVarPar();
        varPar.Namespaces = MergeNamespaces(varPar.Namespaces, stylesheetNsList);
        CheckError(!_curStylesheet.AddVarPar(varPar), System.SR.Xslt_DupGlobalVariable, varPar.Name.QualifiedName);
    }
References System.Xml.Xsl.Xslt.XsltLoader._curStylesheet, System.Xml.Xsl.Xslt.Stylesheet.AddVarPar(), System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltLoader.MergeNamespaces(), System.SR.Xslt_DupGlobalVariable, and System.Xml.Xsl.Xslt.XsltLoader.XslVarPar().
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().