Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslValueOf
XslValueOf()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslValueOf () inline private
Definition at line 1574 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_valueOfAttributes);
        string text = ParseStringAttribute(0, "select");
        string text2 = ParseStringAttribute(1, "separator");
        bool flag = ParseYesNoAttribute(2, "disable-output-escaping") == TriState.True;
        if (text2 == null)
        {
            if (!_input.BackwardCompatibility)
            {
                text2 = ((text != null) ? " " : string.Empty);
            }
        }
        else
        {
            ReportNYI("xsl:value-of/@separator");
        }
        List<XslNode> list = null;
        if (V1)
        {
            if (text == null)
            {
                _input.SkipNode();
                return SetInfo(AstFactory.Error(XslLoadException.CreateMessage(attributes.lineInfo, System.SR.Xslt_MissingAttribute, "select")), null, attributes);
            }
            CheckNoContent();
        }
        else
        {
            list = LoadContent(text != null);
            CheckError(text == null && list.Count == 0, System.SR.Xslt_NoSelectNoContent, _input.ElementName);
            if (list.Count != 0)
            {
                ReportNYI("xsl:value-of/*");
                list = null;
            }
        }
        return SetInfo(AstFactory.XslNode(flag ? XslNodeType.ValueOfDoe : XslNodeType.ValueOf, null, text, _input.XslVersion), null, attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._valueOfAttributes, System.Xml.Xsl.Xslt.XsltInput.BackwardCompatibility, System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent(), System.Xml.Xsl.XslLoadException.CreateMessage(), System.Xml.Xsl.Xslt.XsltInput.ElementName, System.Xml.Xsl.Xslt.AstFactory.Error(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.ContextInfo.lineInfo, System.list, System.Xml.Xsl.Xslt.XsltLoader.LoadContent(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseYesNoAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.text, System.Xml.Xsl.Xslt.XsltLoader.V1, System.Xml.Xsl.Xslt.AstFactory.XslNode(), System.SR.Xslt_MissingAttribute, System.SR.Xslt_NoSelectNoContent, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().