Terraria: System.Xml.Xsl.Xslt.XsltLoader.ParseCollationAttribute
ParseCollationAttribute()
string System.Xml.Xsl.Xslt.XsltLoader.ParseCollationAttribute (int attNum) inline private
Definition at line 2007 of file XsltLoader.cs.
    {
        if (_input.MoveToXsltAttribute(attNum, "collation"))
        {
            ReportNYI("@collation");
        }
        return null;
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), and System.Xml.Xsl.Xslt.XsltLoader.ReportNYI().
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadKey(), and System.Xml.Xsl.Xslt.XsltLoader.XslSort().