Terraria: System.Xml.Xsl.Xslt.XsltLoader.ReportNYI
ReportNYI()
void System.Xml.Xsl.Xslt.XsltLoader.ReportNYI (string arg) inline private
Definition at line 2395 of file XsltLoader.cs.
    {
        if (!_input.ForwardCompatibility)
        {
            ReportError(System.SR.Xslt_NotYetImplemented, arg);
        }
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), and System.SR.Xslt_NotYetImplemented.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadKey(), System.Xml.Xsl.Xslt.XsltLoader.LoadOutput(), System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate(), System.Xml.Xsl.Xslt.XsltLoader.ParseCollationAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseModeAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseModeListAttribute(), System.Xml.Xsl.Xslt.XsltLoader.XslApplyImports(), System.Xml.Xsl.Xslt.XsltLoader.XslAttribute(), System.Xml.Xsl.Xslt.XsltLoader.XslComment(), System.Xml.Xsl.Xslt.XsltLoader.XslCopy(), System.Xml.Xsl.Xslt.XsltLoader.XslCopyOf(), System.Xml.Xsl.Xslt.XsltLoader.XslElement(), System.Xml.Xsl.Xslt.XsltLoader.XslNumber(), System.Xml.Xsl.Xslt.XsltLoader.XslProcessingInstruction(), System.Xml.Xsl.Xslt.XsltLoader.XslSort(), System.Xml.Xsl.Xslt.XsltLoader.XslValueOf(), and System.Xml.Xsl.Xslt.XsltLoader.XslVarPar().