Terraria: Internal.Win32.RegistryKey.Win32Error
Win32Error()
static void Internal.Win32.RegistryKey.Win32Error (int errorCode, string str) inline static package
Definition at line 301 of file RegistryKey.cs.
    {
        switch (errorCode)
        {
        case 5:
            if (str != null)
            {
                throw new UnauthorizedAccessException(SR.Format(SR.UnauthorizedAccess_RegistryKeyGeneric_Key, str));
            }
            throw new UnauthorizedAccessException();
        case 2:
            throw new IOException(SR.Arg_RegKeyNotFound, errorCode);
        default:
            throw new IOException(Interop.Kernel32.GetMessage(errorCode), errorCode);
        }
    }
References System.SR.Arg_RegKeyNotFound, System.SR.Format(), Interop.Kernel32.GetMessage(), System.str, and System.SR.UnauthorizedAccess_RegistryKeyGeneric_Key.
Referenced by Internal.Win32.RegistryKey.GetSubKeyNames(), Internal.Win32.RegistryKey.GetValueNames(), and Internal.Win32.RegistryKey.SetValue().