Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadStripSpace
LoadStripSpace()
void System.Xml.Xsl.Xslt.XsltLoader.LoadStripSpace (NsDecl stylesheetNsList) inline private
Definition at line 662 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_loadStripSpaceAttributes);
        attributes.nsList = MergeNamespaces(attributes.nsList, stylesheetNsList);
        if (_input.MoveToXsltAttribute(0, _atoms.Elements))
        {
            ParseWhitespaceRules(_input.Value, preserveSpace: false);
        }
        CheckNoContent();
    }
References System.Xml.Xsl.Xslt.XsltLoader._atoms, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._loadStripSpaceAttributes, System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.KeywordsTable.Elements, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltLoader.MergeNamespaces(), System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltInput.ContextInfo.nsList, System.Xml.Xsl.Xslt.XsltLoader.ParseWhitespaceRules(), and System.Xml.Xsl.Xslt.XsltInput.Value.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().