Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslText
XslText()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslText () inline private
Definition at line 1693 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_textAttributes);
        SerializationHints hints = ((ParseYesNoAttribute(0, "disable-output-escaping") == TriState.True) ? SerializationHints.DisableOutputEscaping : SerializationHints.None);
        List<XslNode> list = new List<XslNode>();
        XsltInput.DelayedQName elementName = _input.ElementName;
        if (_input.MoveToFirstChild())
        {
            do
            {
                XmlNodeType nodeType = _input.NodeType;
                if (nodeType == XmlNodeType.Text || (uint)(nodeType - 13) <= 1u)
                {
                    list.Add(AstFactory.Text(_input.Value, hints));
                    continue;
                }
                ReportError(System.SR.Xslt_UnexpectedElement, _input.QualifiedName, elementName);
                _input.SkipNode();
            }
            while (_input.MoveToNextSibling());
        }
        return SetInfo(AstFactory.List(), list, attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._textAttributes, System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.ElementName, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.list, System.Xml.Xsl.Xslt.AstFactory.List(), System.Xml.Xsl.Xslt.XsltInput.MoveToFirstChild(), System.Xml.Xsl.Xslt.XsltInput.MoveToNextSibling(), System.Xml.Xsl.Xslt.XsltInput.NodeType, System.Xml.Xsl.Xslt.XsltLoader.ParseYesNoAttribute(), System.Xml.Xsl.Xslt.XsltInput.QualifiedName, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.Xml.Xsl.Xslt.AstFactory.Text(), System.Xml.Xsl.Xslt.XsltInput.Value, and System.SR.Xslt_UnexpectedElement.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().