Terraria: System.Xml.Xsl.Xslt.XsltLoader.MergeNamespaces
MergeNamespaces()
static NsDecl System.Xml.Xsl.Xslt.XsltLoader.MergeNamespaces (NsDecl thisList, NsDecl parentList) inline static private
Definition at line 2355 of file XsltLoader.cs.
    {
        if (parentList == null)
        {
            return thisList;
        }
        if (thisList == null)
        {
            return parentList;
        }
        while (parentList != null)
        {
            bool flag = false;
            for (NsDecl nsDecl = thisList; nsDecl != null; nsDecl = nsDecl.Prev)
            {
                if (Ref.Equal(nsDecl.Prefix, parentList.Prefix) && (nsDecl.Prefix != null || nsDecl.NsUri == parentList.NsUri))
                {
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                thisList = new NsDecl(thisList, parentList.Prefix, parentList.NsUri);
            }
            parentList = parentList.Prev;
        }
        return thisList;
    }
References System.Xml.Dictionary, and System.Xml.Ref.Equal().
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet(), System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat(), System.Xml.Xsl.Xslt.XsltLoader.LoadGlobalVariableOrParameter(), System.Xml.Xsl.Xslt.XsltLoader.LoadKey(), System.Xml.Xsl.Xslt.XsltLoader.LoadMsScript(), System.Xml.Xsl.Xslt.XsltLoader.LoadNamespaceAlias(), System.Xml.Xsl.Xslt.XsltLoader.LoadPreserveSpace(), System.Xml.Xsl.Xslt.XsltLoader.LoadStripSpace(), and System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate().