Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslComment
XslComment()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslComment () inline private
Definition at line 1658 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_commentAttributes);
        string text = ParseStringAttribute(0, "select");
        if (text != null)
        {
            ReportNYI("xsl:comment/@select");
        }
        return SetInfo(AstFactory.Comment(), LoadContent(text != null), attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._commentAttributes, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.AstFactory.Comment(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltLoader.LoadContent(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), and System.text.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().