Terraria: System.Xml.Xsl.Xslt.XsltLoader.CreateReader
CreateReader()
XmlReader System.Xml.Xsl.Xslt.XsltLoader.CreateReader (Uri uri, XmlResolver xmlResolver) inline private
Definition at line 392 of file XsltLoader.cs.
    {
        object entity = xmlResolver.GetEntity(uri, null, null);
        if (entity is Stream stream)
        {
            return _readerSettings.CreateReader(stream, uri.ToString());
        }
        if (entity is XmlReader result)
        {
            return result;
        }
        if (entity is IXPathNavigable iXPathNavigable)
        {
            return XPathNavigatorReader.Create(iXPathNavigable.CreateNavigator());
        }
        throw new XslLoadException(System.SR.Xslt_CannotLoadStylesheet, uri.ToString(), (entity == null) ? "null" : entity.GetType().ToString());
    }
References System.Xml.Xsl.Xslt.XsltLoader._readerSettings, System.Xml.XPath.XPathNavigatorReader.Create(), System.Xml.Xsl.QueryReaderSettings.CreateReader(), System.stream, System.Uri.ToString(), and System.SR.Xslt_CannotLoadStylesheet.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.Load(), and System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet().