Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslForEach
XslForEach()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslForEach () inline private
Definition at line 1496 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_forEachAttributes);
        string select = ParseStringAttribute(0, "select");
        _input.CanHaveApplyImports = false;
        List<XslNode> content = LoadInstructions(InstructionFlags.AllowSort);
        attributes.SaveExtendedLineInfo(_input);
        return SetInfo(AstFactory.ForEach(select, attributes, _input.XslVersion), content, attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._forEachAttributes, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Dictionary, System.Xml.Xsl.Xslt.AstFactory.ForEach(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltInput.ContextInfo.SaveExtendedLineInfo(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().