Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslSort
XslSort()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslSort (int sortNumber) inline private
Definition at line 1759 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_sortAttributes);
        string text = ParseStringAttribute(0, "select");
        string lang = ParseStringAttribute(1, "lang");
        string order = ParseStringAttribute(2, "order");
        ParseCollationAttribute(3);
        TriState triState = ParseYesNoAttribute(4, "stable");
        string caseOrder = ParseStringAttribute(5, "case-order");
        string dataType = ParseStringAttribute(6, "data-type");
        if (triState != TriState.Unknown)
        {
            CheckError(sortNumber != 0, System.SR.Xslt_SortStable);
        }
        List<XslNode> list = null;
        if (V1)
        {
            CheckNoContent();
        }
        else
        {
            list = LoadContent(text != null);
            if (list.Count != 0)
            {
                ReportNYI("xsl:sort/*");
                list = null;
            }
        }
        if (text == null)
        {
            text = ".";
        }
        return SetInfo(AstFactory.Sort(text, lang, dataType, order, caseOrder, _input.XslVersion), null, attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._sortAttributes, System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.list, System.Xml.Xsl.Xslt.XsltLoader.LoadContent(), System.Xml.Xsl.Xslt.XsltLoader.ParseCollationAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseYesNoAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.Xml.Xsl.Xslt.AstFactory.Sort(), System.text, System.Xml.Xsl.Xslt.XsltLoader.V1, System.SR.Xslt_SortStable, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), and System.Xml.Xsl.Xslt.XsltLoader.LoadWithParams().