Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslNumber
XslNumber()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslNumber () inline private
Definition at line 1523 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_numberAttributes);
        string value = ParseStringAttribute(0, "value");
        string text = ParseStringAttribute(1, "select");
        if (text != null)
        {
            ReportNYI("xsl:number/@select");
        }
        NumberLevel level = NumberLevel.Single;
        if (_input.MoveToXsltAttribute(2, "level"))
        {
            switch (_input.Value)
            {
            case "single":
                level = NumberLevel.Single;
                break;
            case "multiple":
                level = NumberLevel.Multiple;
                break;
            case "any":
                level = NumberLevel.Any;
                break;
            default:
                if (!_input.ForwardCompatibility)
                {
                    ReportError(System.SR.Xslt_InvalidAttrValue, "level", _input.Value);
                }
                break;
            }
        }
        string count = ParseStringAttribute(3, "count");
        string from = ParseStringAttribute(4, "from");
        string text2 = ParseStringAttribute(5, "format");
        string lang = ParseStringAttribute(6, "lang");
        string letterValue = ParseStringAttribute(7, "letter-value");
        string value2 = ParseStringAttribute(8, "ordinal");
        if (!string.IsNullOrEmpty(value2))
        {
            ReportNYI("xsl:number/@ordinal");
        }
        string groupingSeparator = ParseStringAttribute(9, "grouping-separator");
        string groupingSize = ParseStringAttribute(10, "grouping-size");
        if (text2 == null)
        {
            text2 = "1";
        }
        CheckNoContent();
        return SetInfo(AstFactory.Number(level, count, from, value, text2, lang, letterValue, groupingSeparator, groupingSize, _input.XslVersion), null, attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._numberAttributes, System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent(), System.count, System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.AstFactory.Number(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.text, System.value, System.Xml.Xsl.Xslt.XsltInput.Value, System.SR.Xslt_InvalidAttrValue, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().