Terraria: System.Xml.Xsl.Xslt.XsltLoader.ResolveQName
ResolveQName() [2/2]
bool System.Xml.Xsl.Xslt.XsltLoader.ResolveQName (bool ignoreDefaultNs, string qname, out string localName, out string namespaceName, out string prefix) inline private
Definition at line 2016 of file XsltLoader.cs.
    {
        if (qname == null)
        {
            prefix = _compiler.PhantomNCName;
            localName = _compiler.PhantomNCName;
            namespaceName = _compiler.CreatePhantomNamespace();
            return false;
        }
        if (!_compiler.ParseQName(qname, out prefix, out localName, this))
        {
            namespaceName = _compiler.CreatePhantomNamespace();
            return false;
        }
        if (ignoreDefaultNs && prefix.Length == 0)
        {
            namespaceName = string.Empty;
        }
        else
        {
            namespaceName = _input.LookupXmlNamespace(prefix);
            if (namespaceName == null)
            {
                namespaceName = _compiler.CreatePhantomNamespace();
                return false;
            }
        }
        return true;
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.Compiler.CreatePhantomNamespace(), System.Xml.Xsl.Xslt.XsltInput.LookupXmlNamespace(), System.Xml.Xsl.Xslt.Compiler.ParseQName(), System.Xml.Xsl.Xslt.Compiler.PhantomNCName, and System.prefix.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.CreateXPathQName(), System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat(), System.Xml.Xsl.Xslt.XsltLoader.LoadOutput(), System.Xml.Xsl.Xslt.XsltLoader.ParseOutputMethod(), System.Xml.Xsl.Xslt.XsltLoader.ParseQNameAttribute(), and System.Xml.Xsl.Xslt.XsltLoader.ResolveQName().