Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadInclude
LoadInclude()
void System.Xml.Xsl.Xslt.XsltLoader.LoadInclude () inline private
Definition at line 644 of file XsltLoader.cs.
    {
        _input.GetAttributes(_importIncludeAttributes);
        if (_input.MoveToXsltAttribute(0, "href"))
        {
            Uri uri = ResolveUri(_input.Value, _input.BaseUri);
            if (_documentUriInUse.Contains(uri.ToString()))
            {
                ReportError(System.SR.Xslt_CircularInclude, _input.Value);
            }
            else
            {
                LoadStylesheet(uri, include: true);
            }
        }
        CheckNoContent();
    }
References System.Xml.Xsl.Xslt.XsltLoader._documentUriInUse, System.Xml.Xsl.Xslt.XsltLoader._importIncludeAttributes, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltInput.BaseUri, System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent(), System.Collections.Specialized.HybridDictionary.Contains(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet(), System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ResolveUri(), System.Uri.ToString(), System.Xml.Xsl.Xslt.XsltInput.Value, and System.SR.Xslt_CircularInclude.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().