Terraria: Internal.Win32.RegistryKey.GetValueNames
GetValueNames()
string[] Internal.Win32.RegistryKey.GetValueNames () inline
Definition at line 94 of file RegistryKey.cs.
    {
        List<string> list = new List<string>();
        char[] array = ArrayPool<char>.Shared.Rent(100);
        try
        {
            int lpcbValueName = array.Length;
            int num;
            while ((num = Interop.Advapi32.RegEnumValue(_hkey, list.Count, array, ref lpcbValueName, IntPtr.Zero, null, null, null)) != 259)
            {
                switch (num)
                {
                case 0:
                    list.Add(new string(array, 0, lpcbValueName));
                    break;
                case 234:
                {
                    char[] array2 = array;
                    int num2 = array2.Length;
                    array = null;
                    ArrayPool<char>.Shared.Return(array2);
                    array = ArrayPool<char>.Shared.Rent(checked(num2 * 2));
                    break;
                }
                default:
                    Win32Error(num, null);
                    break;
                }
                lpcbValueName = array.Length;
            }
        }
        finally
        {
            if (array != null)
            {
                ArrayPool<char>.Shared.Return(array);
            }
        }
        return list.ToArray();
    }
References Internal.Win32.RegistryKey._hkey, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.list, Interop.Advapi32.RegEnumValue(), Internal.Win32.RegistryKey.Win32Error(), and System.IntPtr.Zero.
Referenced by System.Environment.GetEnvironmentVariablesFromRegistry().