Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet
LoadAttributeSet()
void System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet (NsDecl stylesheetNsList) inline private
Definition at line 1049 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_attributeSetAttributes);
        attributes.nsList = MergeNamespaces(attributes.nsList, stylesheetNsList);
        QilName qilName = ParseQNameAttribute(0);
        if (!_curStylesheet.AttributeSets.TryGetValue(qilName, out var value))
        {
            value = AstFactory.AttributeSet(qilName);
            _curStylesheet.AttributeSets[qilName] = value;
            if (!_compiler.AttributeSets.ContainsKey(qilName))
            {
                _compiler.AllTemplates.Add(value);
            }
        }
        List<XslNode> list = new List<XslNode>();
        if (_input.MoveToXsltAttribute(1, "use-attribute-sets"))
        {
            AddUseAttributeSets(list);
        }
        XsltInput.DelayedQName elementName = _input.ElementName;
        if (_input.MoveToFirstChild())
        {
            do
            {
                switch (_input.NodeType)
                {
                case XmlNodeType.Element:
                    if (_input.IsXsltKeyword(_atoms.Attribute))
                    {
                        AddInstruction(list, XslAttribute());
                        break;
                    }
                    ReportError(System.SR.Xslt_UnexpectedElement, _input.QualifiedName, elementName);
                    _input.SkipNode();
                    break;
                default:
                    ReportError(System.SR.Xslt_TextNodesNotAllowed, elementName);
                    break;
                case XmlNodeType.Whitespace:
                case XmlNodeType.SignificantWhitespace:
                    break;
                }
            }
            while (_input.MoveToNextSibling());
        }
        value.AddContent(SetInfo(AstFactory.List(), LoadEndTag(list), attributes));
    }
References System.Xml.Xsl.Xslt.XsltLoader._atoms, System.Xml.Xsl.Xslt.XsltLoader._attributeSetAttributes, System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._curStylesheet, System.Xml.Xsl.Xslt.XsltLoader._input, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.XsltLoader.AddInstruction(), System.Xml.Xsl.Xslt.XsltLoader.AddUseAttributeSets(), System.Xml.Xsl.Xslt.Compiler.AllTemplates, System.Xml.Xsl.Xslt.KeywordsTable.Attribute, System.Xml.Xsl.Xslt.AstFactory.AttributeSet(), System.Xml.Xsl.Xslt.Compiler.AttributeSets, System.Xml.Xsl.Xslt.Stylesheet.AttributeSets, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XsltInput.ElementName, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.IsXsltKeyword(), System.list, System.Xml.Xsl.Xslt.AstFactory.List(), System.Xml.Xsl.Xslt.XsltLoader.LoadEndTag(), System.Xml.Xsl.Xslt.XsltLoader.MergeNamespaces(), System.Xml.Xsl.Xslt.XsltInput.MoveToFirstChild(), System.Xml.Xsl.Xslt.XsltInput.MoveToNextSibling(), System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltInput.NodeType, System.Xml.Xsl.Xslt.XsltInput.ContextInfo.nsList, System.Xml.Xsl.Xslt.XsltLoader.ParseQNameAttribute(), System.Xml.Xsl.Xslt.XsltInput.QualifiedName, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, System.Xml.Xsl.Xslt.XsltLoader.XslAttribute(), System.SR.Xslt_TextNodesNotAllowed, and System.SR.Xslt_UnexpectedElement.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().