Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet
LoadStylesheet() [2/2]
Stylesheet System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet (XmlReader reader, bool include) inline private
Definition at line 416 of file XsltLoader.cs.
    {
        string baseURI = reader.BaseURI;
        _documentUriInUse.Add(baseURI, null);
        _compiler.AddModule(baseURI);
        Stylesheet curStylesheet = _curStylesheet;
        XsltInput input = _input;
        Stylesheet stylesheet = (include ? _curStylesheet : _compiler.CreateStylesheet());
        _input = new XsltInput(reader, _compiler, _atoms);
        _curStylesheet = stylesheet;
        try
        {
            LoadDocument();
            if (!include)
            {
                _compiler.MergeWithStylesheet(_curStylesheet);
                List<Uri> importHrefs = _curStylesheet.ImportHrefs;
                _curStylesheet.Imports = new Stylesheet[importHrefs.Count];
                int num = importHrefs.Count;
                while (0 <= --num)
                {
                    _curStylesheet.Imports[num] = LoadStylesheet(importHrefs[num], include: false);
                }
            }
        }
        catch (XslLoadException)
        {
            throw;
        }
        catch (Exception ex2)
        {
            if (!XmlException.IsCatchableException(ex2))
            {
                throw;
            }
            ISourceLineInfo sourceLineInfo;
            if (!(ex2 is XmlException { SourceUri: not null } ex3))
            {
                sourceLineInfo = _input.BuildReaderLineInfo();
            }
            else
            {
                ISourceLineInfo sourceLineInfo2 = new SourceLineInfo(ex3.SourceUri, ex3.LineNumber, ex3.LinePosition, ex3.LineNumber, ex3.LinePosition);
                sourceLineInfo = sourceLineInfo2;
            }
            ISourceLineInfo lineInfo = sourceLineInfo;
            throw new XslLoadException(ex2, lineInfo);
        }
        finally
        {
            _documentUriInUse.Remove(baseURI);
            _input = input;
            _curStylesheet = curStylesheet;
        }
        return stylesheet;
    }
References System.Xml.Xsl.Xslt.XsltLoader._atoms, System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._curStylesheet, System.Xml.Xsl.Xslt.XsltLoader._documentUriInUse, System.Xml.Xsl.Xslt.XsltLoader._input, System.Collections.Specialized.HybridDictionary.Add(), System.Xml.Xsl.Xslt.Compiler.AddModule(), System.Xml.XmlReader.BaseURI, System.Xml.Xsl.Xslt.XsltInput.BuildReaderLineInfo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Xslt.Compiler.CreateStylesheet(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.Stylesheet.ImportHrefs, System.Xml.Xsl.Xslt.StylesheetLevel.Imports, System.input, System.Xml.XmlException.IsCatchableException(), System.Xml.Xsl.Xslt.XsltLoader.LoadDocument(), System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet(), System.Xml.Xsl.Xslt.Compiler.MergeWithStylesheet(), and System.Collections.Specialized.HybridDictionary.Remove().