Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadContent
LoadContent()
List< XslNode > System.Xml.Xsl.Xslt.XsltLoader.LoadContent (bool hasSelect) inline private
Definition at line 1669 of file XsltLoader.cs.
    {
        XsltInput.DelayedQName elementName = _input.ElementName;
        List<XslNode> list = LoadInstructions();
        CheckError(hasSelect && list.Count != 0, System.SR.Xslt_ElementCntSel, elementName);
        if (list.Count != 0)
        {
            list = LoadEndTag(list);
        }
        return list;
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Xslt.XsltInput.ElementName, System.list, System.Xml.Xsl.Xslt.XsltLoader.LoadEndTag(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), and System.SR.Xslt_ElementCntSel.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.XslAttribute(), System.Xml.Xsl.Xslt.XsltLoader.XslComment(), System.Xml.Xsl.Xslt.XsltLoader.XslProcessingInstruction(), System.Xml.Xsl.Xslt.XsltLoader.XslSort(), System.Xml.Xsl.Xslt.XsltLoader.XslValueOf(), and System.Xml.Xsl.Xslt.XsltLoader.XslVarPar().