Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslAttribute
XslAttribute()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslAttribute () inline private
Definition at line 1737 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_attributeAttributes);
        string nameAvt = ParseNCNameAttribute(0);
        string text = ParseStringAttribute(1, "namespace");
        CheckError(text == "http://www.w3.org/2000/xmlns/", System.SR.Xslt_ReservedNS, text);
        string text2 = ParseStringAttribute(2, "select");
        if (text2 != null)
        {
            ReportNYI("xsl:attribute/@select");
        }
        string text3 = ParseStringAttribute(3, "separator");
        if (text3 != null)
        {
            ReportNYI("xsl:attribute/@separator");
        }
        text3 = ((text3 != null) ? text3 : ((text2 != null) ? " " : string.Empty));
        ParseTypeAttribute(4);
        ParseValidationAttribute(5, defVal: false);
        return SetInfo(AstFactory.Attribute(nameAvt, text, _input.XslVersion), LoadContent(text2 != null), attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._attributeAttributes, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.AstFactory.Attribute(), System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltLoader.LoadContent(), System.Xml.Xsl.Xslt.XsltLoader.ParseNCNameAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseTypeAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseValidationAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.text, System.SR.Xslt_ReservedNS, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadAttributeSet(), and System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().