Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslProcessingInstruction
XslProcessingInstruction()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslProcessingInstruction () inline private
Definition at line 1681 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_processingInstructionAttributes);
        string name = ParseNCNameAttribute(0);
        string text = ParseStringAttribute(1, "select");
        if (text != null)
        {
            ReportNYI("xsl:processing-instruction/@select");
        }
        return SetInfo(AstFactory.PI(name, _input.XslVersion), LoadContent(text != null), attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._processingInstructionAttributes, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltLoader.LoadContent(), System.Xml.Xsl.Xslt.XsltLoader.ParseNCNameAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.AstFactory.PI(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.text, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().