Terraria: System.Xml.Xsl.Xslt.XsltLoader.ParseModeAttribute
ParseModeAttribute()
QilName System.Xml.Xsl.Xslt.XsltLoader.ParseModeAttribute (int attNum) inline private
Definition at line 1895 of file XsltLoader.cs.
    {
        if (!_input.MoveToXsltAttribute(attNum, "mode"))
        {
            return nullMode;
        }
        _compiler.EnterForwardsCompatible();
        string value = _input.Value;
        QilName result;
        if (!V1 && value == "#default")
        {
            result = nullMode;
        }
        else if (!V1 && value == "#current")
        {
            ReportNYI("xsl:apply-templates[@mode='#current']");
            result = nullMode;
        }
        else if (!V1 && value == "#all")
        {
            ReportError(System.SR.Xslt_ModeListAll);
            result = nullMode;
        }
        else
        {
            result = CreateXPathQName(value);
        }
        if (!_compiler.ExitForwardsCompatible(_input.ForwardCompatibility))
        {
            result = nullMode;
        }
        return result;
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader.CreateXPathQName(), System.Xml.Xsl.Xslt.Compiler.EnterForwardsCompatible(), System.Xml.Xsl.Xslt.Compiler.ExitForwardsCompatible(), System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltLoader.nullMode, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.V1, System.value, System.Xml.Xsl.Xslt.XsltInput.Value, and System.SR.Xslt_ModeListAll.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate(), and System.Xml.Xsl.Xslt.XsltLoader.XslApplyTemplates().