Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslVarPar
XslVarPar()
VarPar System.Xml.Xsl.Xslt.XsltLoader.XslVarPar () inline private
Definition at line 1614 of file XsltLoader.cs.
    {
        string localName = _input.LocalName;
        XslNodeType xslNodeType = (Ref.Equal(localName, _atoms.Variable) ? XslNodeType.Variable : (Ref.Equal(localName, _atoms.Param) ? XslNodeType.Param : (Ref.Equal(localName, _atoms.WithParam) ? XslNodeType.WithParam : XslNodeType.Unknown)));
        XsltInput.ContextInfo attributes = _input.GetAttributes(xslNodeType switch
        {
            XslNodeType.Param => _paramAttributes,
            XslNodeType.Variable => _variableAttributes,
            _ => _withParamAttributes,
        });
        QilName qilName = ParseQNameAttribute(0);
        string text = ParseStringAttribute(1, "select");
        string text2 = ParseStringAttribute(2, "as");
        TriState triState = ParseYesNoAttribute(3, "required");
        if (triState == TriState.True)
        {
            ReportNYI("xsl:param/@required == true()");
        }
        if (text2 != null)
        {
            ReportNYI("xsl:param/@as");
        }
        TriState triState2 = ParseYesNoAttribute(4, "tunnel");
        if (triState2 != TriState.Unknown)
        {
            if (xslNodeType == XslNodeType.Param && _curTemplate == null)
            {
                if (!_input.ForwardCompatibility)
                {
                    ReportError(System.SR.Xslt_NonTemplateTunnel, qilName.ToString());
                }
            }
            else if (triState2 == TriState.True)
            {
                ReportNYI("xsl:param/@tunnel == true()");
            }
        }
        List<XslNode> list = LoadContent(text != null);
        CheckError(triState == TriState.True && (text != null || list.Count != 0), System.SR.Xslt_RequiredAndSelect, qilName.ToString());
        VarPar varPar = AstFactory.VarPar(xslNodeType, qilName, text, _input.XslVersion);
        SetInfo(varPar, list, attributes);
        return varPar;
    }
References System.Xml.Xsl.Xslt.XsltLoader._atoms, System.Xml.Xsl.Xslt.XsltLoader._curTemplate, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._paramAttributes, System.Xml.Xsl.Xslt.XsltLoader._variableAttributes, System.Xml.Xsl.Xslt.XsltLoader._withParamAttributes, System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.list, System.Xml.Xsl.Xslt.XsltLoader.LoadContent(), System.Xml.Xsl.Xslt.XsltInput.LocalName, System.Xml.Xsl.Xslt.KeywordsTable.Param, System.Xml.Xsl.Xslt.XsltLoader.ParseQNameAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseYesNoAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.text, System.Xml.Xsl.Xslt.KeywordsTable.Variable, System.Xml.Xsl.Xslt.AstFactory.VarPar(), System.Xml.Xsl.Xslt.KeywordsTable.WithParam, System.SR.Xslt_NonTemplateTunnel, System.SR.Xslt_RequiredAndSelect, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadGlobalVariableOrParameter(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), and System.Xml.Xsl.Xslt.XsltLoader.LoadWithParams().