Terraria: Internal.Win32.RegistryKey.GetSubKeyNames
GetSubKeyNames()
string[] Internal.Win32.RegistryKey.GetSubKeyNames () inline
Definition at line 66 of file RegistryKey.cs.
    {
        List<string> list = new List<string>();
        char[] array = ArrayPool<char>.Shared.Rent(256);
        try
        {
            int lpcbName = array.Length;
            int num;
            while ((num = Interop.Advapi32.RegEnumKeyEx(_hkey, list.Count, array, ref lpcbName, null, null, null, null)) != 259)
            {
                if (num == 0)
                {
                    list.Add(new string(array, 0, lpcbName));
                    lpcbName = array.Length;
                }
                else
                {
                    Win32Error(num, null);
                }
            }
        }
        finally
        {
            ArrayPool<char>.Shared.Return(array);
        }
        return list.ToArray();
    }
References Internal.Win32.RegistryKey._hkey, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.list, Interop.Advapi32.RegEnumKeyEx(), and Internal.Win32.RegistryKey.Win32Error().