Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadMsScript
LoadMsScript()
void System.Xml.Xsl.Xslt.XsltLoader.LoadMsScript (NsDecl stylesheetNsList) inline private
Definition at line 1151 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_scriptAttributes);
        attributes.nsList = MergeNamespaces(attributes.nsList, stylesheetNsList);
        string text = null;
        if (_input.MoveToXsltAttribute(0, "implements-prefix"))
        {
            if (_input.Value.Length == 0)
            {
                ReportError(System.SR.Xslt_EmptyAttrValue, "implements-prefix", _input.Value);
            }
            else
            {
                text = _input.LookupXmlNamespace(_input.Value);
                if (text == "http://www.w3.org/1999/XSL/Transform")
                {
                    ReportError(System.SR.Xslt_ScriptXsltNamespace);
                    text = null;
                }
            }
        }
        if (text == null)
        {
            text = _compiler.CreatePhantomNamespace();
        }
        string text2 = ParseStringAttribute(1, "language");
        if (text2 == null)
        {
            text2 = "jscript";
        }
        if (!_compiler.Settings.EnableScript)
        {
            _compiler.Scripts.ScriptClasses[text] = null;
            _input.SkipNode();
            return;
        }
        throw new PlatformNotSupportedException(System.SR.CompilingScriptsNotSupported);
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._scriptAttributes, System.SR.CompilingScriptsNotSupported, System.Xml.Xsl.Xslt.Compiler.CreatePhantomNamespace(), System.Xml.Dictionary, System.Xml.Xsl.XsltSettings.EnableScript, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.LookupXmlNamespace(), System.Xml.Xsl.Xslt.XsltLoader.MergeNamespaces(), System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltInput.ContextInfo.nsList, System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.Scripts.ScriptClasses, System.Xml.Xsl.Xslt.Compiler.Scripts, System.Xml.Xsl.Xslt.Compiler.Settings, System.Xml.Xsl.Xslt.XsltInput.SkipNode(), System.text, System.Xml.Xsl.Xslt.XsltInput.Value, System.SR.Xslt_EmptyAttrValue, and System.SR.Xslt_ScriptXsltNamespace.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadRealStylesheet().