Terraria: System.Xml.Xsl.Xslt.XsltLoader.ParseModeListAttribute
ParseModeListAttribute()
QilName System.Xml.Xsl.Xslt.XsltLoader.ParseModeListAttribute (int attNum) inline private
Definition at line 1929 of file XsltLoader.cs.
    {
        if (!_input.MoveToXsltAttribute(attNum, "mode"))
        {
            return nullMode;
        }
        string value = _input.Value;
        if (value == "#all")
        {
            ReportNYI("xsl:template[@mode='#all']");
            return nullMode;
        }
        string[] array = XmlConvert.SplitString(value);
        List<QilName> list = new List<QilName>(array.Length);
        _compiler.EnterForwardsCompatible();
        if (array.Length == 0)
        {
            ReportError(System.SR.Xslt_ModeListEmpty);
        }
        else
        {
            string[] array2 = array;
            foreach (string text in array2)
            {
                QilName qilName;
                bool flag;
                switch (text)
                {
                case "#default":
                    qilName = nullMode;
                    goto IL_00e6;
                case "#current":
                    ReportNYI("xsl:apply-templates[@mode='#current']");
                    break;
                case "#all":
                    ReportError(System.SR.Xslt_ModeListAll);
                    break;
                default:
                    {
                        qilName = CreateXPathQName(text);
                        goto IL_00e6;
                    }
                    IL_00e6:
                    flag = false;
                    foreach (QilName item in list)
                    {
                        flag |= item.Equals(qilName);
                    }
                    if (flag)
                    {
                        ReportError(System.SR.Xslt_ModeListDup, text);
                    }
                    else
                    {
                        list.Add(qilName);
                    }
                    continue;
                }
                break;
            }
        }
        if (!_compiler.ExitForwardsCompatible(_input.ForwardCompatibility))
        {
            list.Clear();
            list.Add(nullMode);
        }
        if (1 < list.Count)
        {
            ReportNYI("Multipe modes");
            return nullMode;
        }
        if (list.Count == 0)
        {
            return nullMode;
        }
        return list[0];
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.array, System.Xml.Xsl.Xslt.XsltLoader.CreateXPathQName(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.Compiler.EnterForwardsCompatible(), System.Xml.Xsl.Xslt.Compiler.ExitForwardsCompatible(), System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.item, System.list, System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltLoader.nullMode, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.XmlConvert.SplitString(), System.text, System.value, System.Xml.Xsl.Xslt.XsltInput.Value, System.SR.Xslt_ModeListAll, System.SR.Xslt_ModeListDup, and System.SR.Xslt_ModeListEmpty.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate().