Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadUnknownXsltInstruction
LoadUnknownXsltInstruction()
XslNode System.Xml.Xsl.Xslt.XsltLoader.LoadUnknownXsltInstruction (string parentName) inline private
Definition at line 1853 of file XsltLoader.cs.
    {
        _input.GetVersionAttribute();
        if (!_input.ForwardCompatibility)
        {
            ReportError(System.SR.Xslt_UnexpectedElement, _input.QualifiedName, parentName);
            _input.SkipNode();
            return null;
        }
        XsltInput.ContextInfo attributes = _input.GetAttributes();
        List<XslNode> content = LoadFallbacks(_input.LocalName);
        return SetInfo(AstFactory.List(), content, attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltInput.ForwardCompatibility, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.GetVersionAttribute(), System.Xml.Xsl.Xslt.AstFactory.List(), System.Xml.Xsl.Xslt.XsltLoader.LoadFallbacks(), System.Xml.Xsl.Xslt.XsltInput.LocalName, System.Xml.Xsl.Xslt.XsltInput.QualifiedName, System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), and System.SR.Xslt_UnexpectedElement.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().