Terraria: System.Xml.Xsl.Xslt.XsltLoader.LoadFallbacks
LoadFallbacks()
List< XslNode > System.Xml.Xsl.Xslt.XsltLoader.LoadFallbacks (string instrName) inline private
Definition at line 1867 of file XsltLoader.cs.
    {
        _input.MoveToElement();
        ISourceLineInfo lineInfo = _input.BuildNameLineInfo();
        List<XslNode> list = new List<XslNode>();
        if (_input.MoveToFirstChild())
        {
            do
            {
                if (_input.IsXsltKeyword(_atoms.Fallback))
                {
                    XsltInput.ContextInfo attributes = _input.GetAttributes();
                    list.Add(SetInfo(AstFactory.List(), LoadInstructions(), attributes));
                }
                else
                {
                    _input.SkipNode();
                }
            }
            while (_input.MoveToNextSibling());
        }
        if (list.Count == 0)
        {
            list.Add(AstFactory.Error(XslLoadException.CreateMessage(lineInfo, System.SR.Xslt_UnknownExtensionElement, instrName)));
        }
        return list;
    }
References System.Xml.Xsl.Xslt.XsltLoader._atoms, System.Xml.Xsl.Xslt.XsltLoader._input, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.XsltInput.BuildNameLineInfo(), System.Xml.Xsl.XslLoadException.CreateMessage(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.AstFactory.Error(), System.Xml.Xsl.Xslt.KeywordsTable.Fallback, System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.Xsl.Xslt.XsltInput.IsXsltKeyword(), System.list, System.Xml.Xsl.Xslt.AstFactory.List(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.Xml.Xsl.Xslt.XsltInput.MoveToElement(), System.Xml.Xsl.Xslt.XsltInput.MoveToFirstChild(), System.Xml.Xsl.Xslt.XsltInput.MoveToNextSibling(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.Xml.Xsl.Xslt.XsltInput.SkipNode(), and System.SR.Xslt_UnknownExtensionElement.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadLiteralResultElement(), and System.Xml.Xsl.Xslt.XsltLoader.LoadUnknownXsltInstruction().