Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslMessage
XslMessage()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslMessage () inline private
Definition at line 1506 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_messageAttributes);
        string text = ParseStringAttribute(0, "select");
        bool term = ParseYesNoAttribute(1, "terminate") == TriState.True;
        List<XslNode> list = LoadInstructions();
        if (list.Count != 0)
        {
            list = LoadEndTag(list);
        }
        if (text != null)
        {
            list.Insert(0, AstFactory.CopyOf(text, _input.XslVersion));
        }
        return SetInfo(AstFactory.Message(term), list, attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader._messageAttributes, System.Xml.Xsl.Xslt.AstFactory.CopyOf(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.list, System.Xml.Xsl.Xslt.XsltLoader.LoadEndTag(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.Xml.Xsl.Xslt.AstFactory.Message(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseYesNoAttribute(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.text, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().