Terraria: System.Xml.Xsl.Xslt.XsltLoader.AtomizeAttributes
AtomizeAttributes() [1/2]
void System.Xml.Xsl.Xslt.XsltLoader.AtomizeAttributes () inline private
Definition at line 347 of file XsltLoader.cs.
    {
        AtomizeAttributes(_stylesheetAttributes);
        AtomizeAttributes(_importIncludeAttributes);
        AtomizeAttributes(_loadStripSpaceAttributes);
        AtomizeAttributes(_outputAttributes);
        AtomizeAttributes(_keyAttributes);
        AtomizeAttributes(_decimalFormatAttributes);
        AtomizeAttributes(_namespaceAliasAttributes);
        AtomizeAttributes(_attributeSetAttributes);
        AtomizeAttributes(_templateAttributes);
        AtomizeAttributes(_scriptAttributes);
        AtomizeAttributes(_assemblyAttributes);
        AtomizeAttributes(_usingAttributes);
        AtomizeAttributes(_applyTemplatesAttributes);
        AtomizeAttributes(_callTemplateAttributes);
        AtomizeAttributes(_copyAttributes);
        AtomizeAttributes(_copyOfAttributes);
        AtomizeAttributes(_ifAttributes);
        AtomizeAttributes(_forEachAttributes);
        AtomizeAttributes(_messageAttributes);
        AtomizeAttributes(_numberAttributes);
        AtomizeAttributes(_valueOfAttributes);
        AtomizeAttributes(_variableAttributes);
        AtomizeAttributes(_paramAttributes);
        AtomizeAttributes(_withParamAttributes);
        AtomizeAttributes(_commentAttributes);
        AtomizeAttributes(_processingInstructionAttributes);
        AtomizeAttributes(_textAttributes);
        AtomizeAttributes(_elementAttributes);
        AtomizeAttributes(_attributeAttributes);
        AtomizeAttributes(_sortAttributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._applyTemplatesAttributes, System.Xml.Xsl.Xslt.XsltLoader._assemblyAttributes, System.Xml.Xsl.Xslt.XsltLoader._attributeAttributes, System.Xml.Xsl.Xslt.XsltLoader._attributeSetAttributes, System.Xml.Xsl.Xslt.XsltLoader._callTemplateAttributes, System.Xml.Xsl.Xslt.XsltLoader._commentAttributes, System.Xml.Xsl.Xslt.XsltLoader._copyAttributes, System.Xml.Xsl.Xslt.XsltLoader._copyOfAttributes, System.Xml.Xsl.Xslt.XsltLoader._decimalFormatAttributes, System.Xml.Xsl.Xslt.XsltLoader._elementAttributes, System.Xml.Xsl.Xslt.XsltLoader._forEachAttributes, System.Xml.Xsl.Xslt.XsltLoader._ifAttributes, System.Xml.Xsl.Xslt.XsltLoader._importIncludeAttributes, System.Xml.Xsl.Xslt.XsltLoader._keyAttributes, System.Xml.Xsl.Xslt.XsltLoader._loadStripSpaceAttributes, System.Xml.Xsl.Xslt.XsltLoader._messageAttributes, System.Xml.Xsl.Xslt.XsltLoader._namespaceAliasAttributes, System.Xml.Xsl.Xslt.XsltLoader._numberAttributes, System.Xml.Xsl.Xslt.XsltLoader._outputAttributes, System.Xml.Xsl.Xslt.XsltLoader._paramAttributes, System.Xml.Xsl.Xslt.XsltLoader._processingInstructionAttributes, System.Xml.Xsl.Xslt.XsltLoader._scriptAttributes, System.Xml.Xsl.Xslt.XsltLoader._sortAttributes, System.Xml.Xsl.Xslt.XsltLoader._stylesheetAttributes, System.Xml.Xsl.Xslt.XsltLoader._templateAttributes, System.Xml.Xsl.Xslt.XsltLoader._textAttributes, System.Xml.Xsl.Xslt.XsltLoader._usingAttributes, System.Xml.Xsl.Xslt.XsltLoader._valueOfAttributes, System.Xml.Xsl.Xslt.XsltLoader._variableAttributes, System.Xml.Xsl.Xslt.XsltLoader._withParamAttributes, and System.Xml.Xsl.Xslt.XsltLoader.AtomizeAttributes().
Referenced by System.Xml.Xsl.Xslt.XsltLoader.AtomizeAttributes(), and System.Xml.Xsl.Xslt.XsltLoader.Load().