Terraria: System.Xml.Xsl.Xslt.XsltLoader.XslElement
XslElement()
XslNode System.Xml.Xsl.Xslt.XsltLoader.XslElement () inline private
Definition at line 1717 of file XsltLoader.cs.
    {
        XsltInput.ContextInfo attributes = _input.GetAttributes(_elementAttributes);
        string nameAvt = ParseNCNameAttribute(0);
        string text = ParseStringAttribute(1, "namespace");
        CheckError(text == "http://www.w3.org/2000/xmlns/", System.SR.Xslt_ReservedNS, text);
        if (ParseYesNoAttribute(2, "inherit-namespaces") == TriState.False)
        {
            ReportNYI("xsl:copy[@inherit-namespaces = 'no']");
        }
        ParseTypeAttribute(4);
        ParseValidationAttribute(5, defVal: false);
        List<XslNode> list = new List<XslNode>();
        if (_input.MoveToXsltAttribute(3, "use-attribute-sets"))
        {
            AddUseAttributeSets(list);
        }
        return SetInfo(AstFactory.Element(nameAvt, text, _input.XslVersion), LoadEndTag(LoadInstructions(list)), attributes);
    }
References System.Xml.Xsl.Xslt.XsltLoader._elementAttributes, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltLoader.AddUseAttributeSets(), System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.AstFactory.Element(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.list, System.Xml.Xsl.Xslt.XsltLoader.LoadEndTag(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.Xml.Xsl.Xslt.XsltInput.MoveToXsltAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseNCNameAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseStringAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseTypeAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseValidationAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseYesNoAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ReportNYI(), System.Xml.Xsl.Xslt.XsltLoader.SetInfo(), System.text, System.SR.Xslt_ReservedNS, and System.Xml.Xsl.Xslt.XsltInput.XslVersion.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions().