Terraria: System.Xml.Xsl.Xslt.XsltLoader.CheckError
CheckError()
void System.Xml.Xsl.Xslt.XsltLoader.CheckError (bool cond, string res, params string[] args) inline
Definition at line 2403 of file XsltLoader.cs.
    {
        if (cond)
        {
            _compiler.ReportError(_input.BuildNameLineInfo(), res, args);
        }
    }
References System.Xml.Xsl.Xslt.XsltLoader._compiler, System.Xml.Xsl.Xslt.XsltLoader._input, System.Xml.Xsl.Xslt.XsltInput.BuildNameLineInfo(), and System.Xml.Xsl.Xslt.Compiler.ReportError().
Referenced by System.Xml.Xsl.Xslt.XsltLoader.LoadContent(), System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat(), System.Xml.Xsl.Xslt.XsltLoader.LoadGlobalVariableOrParameter(), System.Xml.Xsl.Xslt.XsltLoader.LoadTemplate(), System.Xml.Xsl.Xslt.XsltLoader.ParseInputTypeAnnotationsAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseTypeAttribute(), System.Xml.Xsl.Xslt.XsltLoader.XslAttribute(), System.Xml.Xsl.Xslt.XsltLoader.XslChoose(), System.Xml.Xsl.Xslt.XsltLoader.XslElement(), System.Xml.Xsl.Xslt.XsltLoader.XslSort(), System.Xml.Xsl.Xslt.XsltLoader.XslValueOf(), and System.Xml.Xsl.Xslt.XsltLoader.XslVarPar().