Terraria: Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.AddBackAndFolderButtons
AddBackAndFolderButtons()
void Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.AddBackAndFolderButtons (UIElement outerContainer) inline private
Definition at line 438 of file UIResourcePackSelectionMenu.cs.
    {
        UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true)
        {
            Width = new StyleDimension(-8f, 0.5f),
            Height = new StyleDimension(50f, 0f),
            VAlign = 1f,
            HAlign = 0f,
            Top = new StyleDimension(-45f, 0f)
        };
        uITextPanel.OnMouseOver += FadedMouseOver;
        uITextPanel.OnMouseOut += FadedMouseOut;
        uITextPanel.OnLeftClick += GoBackClick;
        uITextPanel.SetSnapPoint("GoBack", 0);
        outerContainer.Append(uITextPanel);
        UITextPanel<LocalizedText> uITextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("GameUI.OpenFileFolder"), 0.7f, large: true)
        {
            Width = new StyleDimension(-8f, 0.5f),
            Height = new StyleDimension(50f, 0f),
            VAlign = 1f,
            HAlign = 1f,
            Top = new StyleDimension(-45f, 0f)
        };
        uITextPanel2.OnMouseOver += FadedMouseOver;
        uITextPanel2.OnMouseOut += FadedMouseOut;
        uITextPanel2.OnLeftClick += OpenFoldersClick;
        uITextPanel2.SetSnapPoint("OpenFolder", 0);
        outerContainer.Append(uITextPanel2);
    }
References Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.FadedMouseOut(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.FadedMouseOver(), Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.GoBackClick(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.OpenFoldersClick(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.BuildPage().