Terraria: Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.UpdateTitles
UpdateTitles()
void Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.UpdateTitles () inline private
Definition at line 426 of file UIResourcePackSelectionMenu.cs.
    {
        _titleAvailable.SetText(Language.GetText("UI.AvailableResourcePacksTitle").FormatWith(new
        {
            Amount = _availablePacksList.Count
        }));
        _titleEnabled.SetText(Language.GetText("UI.EnabledResourcePacksTitle").FormatWith(new
        {
            Amount = _enabledPacksList.Count
        }));
    }
References Terraria.GameContent.UI.States.UIResourcePackSelectionMenu._titleAvailable, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu._titleEnabled, Terraria.Localization.Language.GetText(), and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList().