Terraria: System.Linq.Parallel.ReverseQueryOperator.ReverseQueryOperatorEnumerator.MoveNext
MoveNext() [2/2]
override bool System.Linq.Parallel.ReverseQueryOperator< TSource >.ReverseQueryOperatorEnumerator< TKey >.MoveNext ([AllowNull] ref TSource currentElement, [AllowNull] ref TKey currentKey) inline package
Definition at line 25 of file ReverseQueryOperator.cs.
        {
            if (_buffer == null)
            {
                _bufferIndex = new Shared<int>(0);
                _buffer = new List<Pair<TSource, TKey>>();
                TSource currentElement2 = default(TSource);
                TKey currentKey2 = default(TKey);
                int num = 0;
                while (_source.MoveNext(ref currentElement2, ref currentKey2))
                {
                    if ((num++ & 0x3F) == 0)
                    {
                        _cancellationToken.ThrowIfCancellationRequested();
                    }
                    _buffer.Add(new Pair<TSource, TKey>(currentElement2, currentKey2));
                    _bufferIndex.Value++;
                }
            }
            if (--_bufferIndex.Value >= 0)
            {
                currentElement = _buffer[_bufferIndex.Value].First;
                currentKey = _buffer[_bufferIndex.Value].Second;
                return true;
            }
            return false;
        }
References System.Linq.Parallel.ReverseQueryOperator< TSource >.ReverseQueryOperatorEnumerator< TKey >._buffer, System.Linq.Parallel.ReverseQueryOperator< TSource >.ReverseQueryOperatorEnumerator< TKey >._bufferIndex, System.Linq.Parallel.ReverseQueryOperator< TSource >.ReverseQueryOperatorEnumerator< TKey >._cancellationToken, System.Linq.Parallel.ReverseQueryOperator< TSource >.ReverseQueryOperatorEnumerator< TKey >._source, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.MoveNext(), System.Threading.CancellationToken.ThrowIfCancellationRequested(), and System.Linq.Parallel.Shared< T >.Value.