Terraria: PitEntrance.Place
Place()
static void PitEntrance.Place (DesertDescription description) inline static
     {
         int holeRadius = WorldGen.genRand.Next(6, 9);
         Point center = description.CombinedArea.Center;
         center.Y = description.Surface[center.X];
         PlaceAt(description, center, holeRadius);
     }
References DesertDescription.CombinedArea, WorldGen.genRand, UnifiedRandom.Next(), PlaceAt(), and DesertDescription.Surface.
Referenced by DesertBiome.Place().