Terraria: System.Net.Http.Headers.EntityTagHeaderValue.GetEntityTagLength
GetEntityTagLength()
static int System.Net.Http.Headers.EntityTagHeaderValue.GetEntityTagLength (string input, int startIndex, out EntityTagHeaderValue parsedValue) inline static package
Definition at line 94 of file EntityTagHeaderValue.cs.
    {
        parsedValue = null;
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        bool isWeak = false;
        int num = startIndex;
        char c = input[startIndex];
        if (c == '*')
        {
            parsedValue = Any;
            num++;
        }
        else
        {
            if (c == 'W' || c == 'w')
            {
                num++;
                if (num + 2 >= input.Length || input[num] != '/')
                {
                    return 0;
                }
                isWeak = true;
                num++;
                num += HttpRuleParser.GetWhitespaceLength(input, num);
            }
            int startIndex2 = num;
            int length = 0;
            if (HttpRuleParser.GetQuotedStringLength(input, num, out length) != 0)
            {
                return 0;
            }
            parsedValue = new EntityTagHeaderValue();
            if (length == input.Length)
            {
                parsedValue = new EntityTagHeaderValue(input);
            }
            else
            {
                parsedValue = new EntityTagHeaderValue(input.Substring(startIndex2, length), isWeak);
            }
            num += length;
        }
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        return num - startIndex;
    }
References System.Net.Http.Headers.EntityTagHeaderValue.EntityTagHeaderValue(), System.Net.Http.Headers.EntityTagHeaderValue.Any, System.Net.Http.HttpRuleParser.GetQuotedStringLength(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), System.input, System.length, and System.startIndex.
Referenced by System.Net.Http.Headers.RangeConditionHeaderValue.GetRangeConditionLength(), System.Net.Http.Headers.GenericHeaderParser.ParseMultipleEntityTags(), and System.Net.Http.Headers.GenericHeaderParser.ParseSingleEntityTag().