Terraria: Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAutomaticResources
ReleaseAutomaticResources()
void Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAutomaticResources () inline
Definition at line 384 of file DeviceResourceManager.cs.
    {
        if (pSyncObject == null)
        {
            return;
        }
        int num = 0;
        bool lockTaken = false;
        try
        {
            Monitor.Enter(pSyncObject, ref lockTaken);
            ulong[] array = new ulong[pResourceData.Keys.Count];
            pResourceData.Keys.CopyTo(array, 0);
            for (int i = 0; i < (nint)array.LongLength; i++)
            {
                ulong key = array[i];
                ResourceData resourceData = pResourceData[key];
                switch (resourceData.dwResourceManagementMode)
                {
                case 1u:
                {
                    WeakReference managedObject2 = resourceData.ManagedObject;
                    if (managedObject2.IsAlive && managedObject2.Target is IGraphicsResource graphicsResource)
                    {
                        if (!resourceData.isDisposed)
{
                            num = graphicsResource.SaveDataForRecreation();
                        }
                        if (num < 0)
{
                            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
                        }
                    }
                    break;
                }
                case 0u:
                {
                    WeakReference managedObject = resourceData.ManagedObject;
                    if (managedObject.IsAlive && managedObject.Target is Effect effect)
                    {
                        if (!resourceData.isDisposed)
{
                            num = effect.SaveDataForRecreation();
                        }
                        if (num < 0)
{
                            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
                        }
                    }
                    break;
                }
                }
            }
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(pSyncObject);
            }
        }
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.Count, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pResourceData, and Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pSyncObject.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset().