Terraria: Microsoft.Xna.Framework.Graphics.DeviceResourceManager.RecreateResources
RecreateResources()
void Microsoft.Xna.Framework.Graphics.DeviceResourceManager.RecreateResources (_D3DPOOL pool, [MarshalAs(UnmanagedType.U1)] bool deviceRecreated) inline
Definition at line 447 of file DeviceResourceManager.cs.
    {
        if (pSyncObject == null)
        {
            return;
        }
        bool lockTaken = false;
        try
        {
            Monitor.Enter(pSyncObject, ref lockTaken);
            ulong[] array = new ulong[pResourceData.Keys.Count];
            pResourceData.Keys.CopyTo(array, 0);
            List<Effect> list = new List<Effect>();
            for (int i = 0; i < (nint)array.LongLength; i++)
            {
                ulong key = array[i];
                ResourceData resourceData = pResourceData[key];
                if (resourceData.dwResourceManagementMode != (uint)pool)
                {
                    continue;
                }
                WeakReference managedObject = resourceData.ManagedObject;
                if (!managedObject.IsAlive)
                {
                    continue;
                }
                Effect effect = managedObject.Target as Effect;
                if (effect != null && !effect.isDisposed && !deviceRecreated)
                {
                    effect.OnResetDevice();
                    continue;
                }
                if (managedObject.Target is IGraphicsResource graphicsResource && !resourceData.isDisposed)
                {
                    if (effect != null)
                    {
                        list.Add(effect);
                    }
                    else
                    {
                        int num = graphicsResource.RecreateAndPopulateObject();
                        if (num < 0)
{
                            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
                        }
                    }
                }
                if (managedObject.Target is IDynamicGraphicsResource dynamicGraphicsResource)
                {
                    dynamicGraphicsResource.SetContentLost(isContentLost: true);
                }
            }
            List<Effect>.Enumerator enumerator = list.GetEnumerator();
            while (enumerator.MoveNext())
            {
                int num2 = enumerator.Current.RecreateAndPopulateObject();
                if (num2 < 0)
                {
                    throw GraphicsHelpers.GetExceptionFromResult((uint)num2);
                }
            }
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(pSyncObject);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.Count, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GraphicsResource.isDisposed, System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, System.list, Microsoft.Xna.Framework.Graphics.Effect.OnResetDevice(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pResourceData, and Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pSyncObject.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset().