Terraria: Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject
AddTrackedObject()
unsafe void Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject (object managedObject, void * pComPtr, uint resourceManagementMode, ulong handle, ref ulong updatedHandle) inline
Definition at line 77 of file DeviceResourceManager.cs.
    {
        bool lockTaken = false;
        try
        {
            Monitor.Enter(pSyncObject, ref lockTaken);
            if (pResourceData.ContainsKey(handle))
            {
                ResourceData value = pResourceData[handle];
                value.pComPtr = pComPtr;
                value.dwResourceManagementMode = resourceManagementMode;
                value.CurrentRefCount = 1;
                value.isDisposed = false;
                pResourceData[handle] = value;
                updatedHandle = handle;
            }
            else
            {
                ResourceData value2 = default(ResourceData);
                value2.ManagedObject = new WeakReference(managedObject);
                value2.pComPtr = pComPtr;
                value2.ResourceName = string.Empty;
                value2.ResourceTag = null;
                value2.dwResourceManagementMode = resourceManagementMode;
                value2.CurrentRefCount = 1;
                value2.isDisposed = false;
                updatedHandle = (value2.objectHandle = ++_currentMaxHandle);
                pResourceData.Add(updatedHandle, value2);
                pParentDevice.FireCreatedEvent(managedObject);
            }
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(pSyncObject);
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.DeviceResourceManager._currentMaxHandle, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.FireCreatedEvent(), System.handle, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pParentDevice, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pResourceData, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pSyncObject, and System.value.
Referenced by Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.DynamicIndexBuffer(), Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.DynamicIndexBuffer(), Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.DynamicVertexBuffer(), Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.DynamicVertexBuffer(), Microsoft.Xna.Framework.Graphics.Effect.Effect(), Microsoft.Xna.Framework.Graphics.IndexBuffer.IndexBuffer(), Microsoft.Xna.Framework.Graphics.IndexBuffer.IndexBuffer(), Microsoft.Xna.Framework.Graphics.OcclusionQuery.OcclusionQuery(), Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D(), Microsoft.Xna.Framework.Graphics.VertexBuffer.VertexBuffer(), Microsoft.Xna.Framework.Graphics.VertexBuffer.VertexBuffer(), Microsoft.Xna.Framework.Graphics.Effect.CreateEffectFromCode(), Microsoft.Xna.Framework.Graphics.TextureCube.CreateTexture(), Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture(), Microsoft.Xna.Framework.Graphics.Texture3D.CreateTexture(), Microsoft.Xna.Framework.Graphics.Effect.GetManagedObject(), Microsoft.Xna.Framework.Graphics.TextureCube.GetManagedObject(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetManagedObject(), Microsoft.Xna.Framework.Graphics.IndexBuffer.GetManagedObject(), Microsoft.Xna.Framework.Graphics.OcclusionQuery.GetManagedObject(), Microsoft.Xna.Framework.Graphics.Texture2D.GetManagedObject(), Microsoft.Xna.Framework.Graphics.VertexBuffer.GetManagedObject(), Microsoft.Xna.Framework.Graphics.Texture3D.GetManagedObject(), Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.RecreateAndPopulateObject(), Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.RecreateAndPopulateObject(), Microsoft.Xna.Framework.Graphics.Effect.RecreateAndPopulateObject(), Microsoft.Xna.Framework.Graphics.IndexBuffer.RecreateAndPopulateObject(), Microsoft.Xna.Framework.Graphics.OcclusionQuery.RecreateAndPopulateObject(), Microsoft.Xna.Framework.Graphics.Texture2D.RecreateAndPopulateObject(), Microsoft.Xna.Framework.Graphics.Texture3D.RecreateAndPopulateObject(), Microsoft.Xna.Framework.Graphics.TextureCube.RecreateAndPopulateObject(), and Microsoft.Xna.Framework.Graphics.VertexBuffer.RecreateAndPopulateObject().