Terraria: Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllDefaultPoolResources
ReleaseAllDefaultPoolResources()
void Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllDefaultPoolResources () inline
Definition at line 305 of file DeviceResourceManager.cs.
    {
        if (pSyncObject == null)
        {
            return;
        }
        bool lockTaken = false;
        try
        {
            Monitor.Enter(pSyncObject, ref lockTaken);
            List<ulong> list = new List<ulong>();
            Dictionary<ulong, ResourceData>.KeyCollection.Enumerator enumerator = pResourceData.Keys.GetEnumerator();
            while (enumerator.MoveNext())
            {
                ulong current = enumerator.Current;
                ResourceData resourceData = pResourceData[current];
                if (resourceData.dwResourceManagementMode == 0)
                {
                    WeakReference managedObject = resourceData.ManagedObject;
                    if (managedObject.IsAlive && managedObject.Target is Effect { isDisposed: false } effect)
                    {
                        effect.OnLostDevice();
                    }
                    else
                    {
                        list.Add(resourceData.objectHandle);
                    }
                }
            }
            List<ulong>.Enumerator enumerator2 = list.GetEnumerator();
            while (enumerator2.MoveNext())
            {
                ulong current2 = enumerator2.Current;
                if (pResourceData[current2].CurrentRefCount > 0 && pResourceData[current2].ManagedObject.Target is IGraphicsResource graphicsResource && !pResourceData[current2].isDisposed)
                {
                    graphicsResource.ReleaseNativeObject(disposeManagedResource: false);
                }
            }
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(pSyncObject);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.GetEnumerator(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Collections.Generic.Dictionary< TKey, TValue >.Keys, System.list, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pResourceData, and Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pSyncObject.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset().