Terraria: Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllReferences
ReleaseAllReferences()
unsafe void Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllReferences (ulong handle, [MarshalAs(UnmanagedType.U1)] bool dispose) inline
Definition at line 255 of file DeviceResourceManager.cs.
    {
        if (pSyncObject == null)
        {
            return;
        }
        bool lockTaken = false;
        try
        {
            Monitor.Enter(pSyncObject, ref lockTaken);
            if (!pResourceData.ContainsKey(handle))
            {
                return;
            }
            ResourceData value = pResourceData[handle];
            value.isDisposed = dispose;
            if (dispose)
            {
                pParentDevice.FireDestroyedEvent(GetCachedName(handle), GetCachedTag(handle));
            }
            while (true)
            {
                int currentRefCount = value.CurrentRefCount;
                if (currentRefCount <= 0)
                {
                    break;
                }
                void* pComPtr = value.pComPtr;
                uint num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)pComPtr + 8)))((nint)pComPtr);
                value.CurrentRefCount = currentRefCount - 1;
            }
            value.pComPtr = null;
            if (dispose)
            {
                pResourceData.Remove(handle);
            }
            else
            {
                pResourceData[handle] = value;
            }
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(pSyncObject);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.FireDestroyedEvent(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.GetCachedName(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.GetCachedTag(), System.handle, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pParentDevice, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pResourceData, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pSyncObject, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.value.
Referenced by Microsoft.Xna.Framework.Graphics.Effect.ReleaseNativeObject(), Microsoft.Xna.Framework.Graphics.IndexBuffer.ReleaseNativeObject(), Microsoft.Xna.Framework.Graphics.OcclusionQuery.ReleaseNativeObject(), Microsoft.Xna.Framework.Graphics.Texture2D.ReleaseNativeObject(), Microsoft.Xna.Framework.Graphics.Texture3D.ReleaseNativeObject(), Microsoft.Xna.Framework.Graphics.TextureCube.ReleaseNativeObject(), and Microsoft.Xna.Framework.Graphics.VertexBuffer.ReleaseNativeObject().