Terraria: Microsoft.Xna.Framework.Graphics.DeviceResourceManager.FindResourceW
FindResourceW()
IntPtr Microsoft.Xna.Framework.Graphics.DeviceResourceManager.FindResourceW (Converter< object, IntPtr > selectionFilter) inline
Definition at line 117 of file DeviceResourceManager.cs.
    {
        bool lockTaken = false;
        try
        {
            Monitor.Enter(pSyncObject, ref lockTaken);
            Dictionary<ulong, ResourceData>.ValueCollection.Enumerator enumerator = pResourceData.Values.GetEnumerator();
            while (enumerator.MoveNext())
            {
                object target = enumerator.Current.ManagedObject.Target;
                if (target != null)
                {
                    IntPtr intPtr = selectionFilter(target);
                    IntPtr intPtr2 = intPtr;
                    IntPtr intPtr3 = intPtr;
                    if (intPtr3 != IntPtr.Zero)
                    {
                        return intPtr3;
                    }
                }
            }
            return IntPtr.Zero;
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(pSyncObject);
            }
        }
    }
References System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.GetEnumerator(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pResourceData, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pSyncObject, System.Collections.Generic.Dictionary< TKey, TValue >.Values, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.RenderTargetHelper.CreateSurfaces().