Terraria: Microsoft.Xna.Framework.Graphics.DeviceResourceManager.GetCachedObject
GetCachedObject()
unsafe object Microsoft.Xna.Framework.Graphics.DeviceResourceManager.GetCachedObject (void * pComPtr) inline
Definition at line 191 of file DeviceResourceManager.cs.
    {
        bool lockTaken = false;
        try
        {
            Monitor.Enter(pSyncObject, ref lockTaken);
            Dictionary<ulong, ResourceData>.KeyCollection.Enumerator enumerator = pResourceData.Keys.GetEnumerator();
            while (enumerator.MoveNext())
            {
                ulong current = enumerator.Current;
                if (pResourceData[current].pComPtr == pComPtr && pResourceData[current].ManagedObject.IsAlive)
                {
                    return pResourceData[current].ManagedObject.Target;
                }
            }
            return null;
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(pSyncObject);
            }
        }
    }
References System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.GetEnumerator(), System.Collections.Generic.Dictionary< TKey, TValue >.Keys, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pResourceData, and Microsoft.Xna.Framework.Graphics.DeviceResourceManager.pSyncObject.
Referenced by Microsoft.Xna.Framework.Graphics.Effect.GetManagedObject(), Microsoft.Xna.Framework.Graphics.TextureCube.GetManagedObject(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetManagedObject(), Microsoft.Xna.Framework.Graphics.IndexBuffer.GetManagedObject(), Microsoft.Xna.Framework.Graphics.OcclusionQuery.GetManagedObject(), Microsoft.Xna.Framework.Graphics.Texture2D.GetManagedObject(), Microsoft.Xna.Framework.Graphics.VertexBuffer.GetManagedObject(), and Microsoft.Xna.Framework.Graphics.Texture3D.GetManagedObject().