Terraria: System.Net.Mime.MultiAsyncResult.End
End()
static object System.Net.Mime.MultiAsyncResult.End (IAsyncResult result) inline static package
Definition at line 53 of file MultiAsyncResult.cs.
    {
        MultiAsyncResult multiAsyncResult = (MultiAsyncResult)result;
        multiAsyncResult.InternalWaitForCompletion();
        return multiAsyncResult.Result;
    }
References System.Net.Mime.MultiAsyncResult.MultiAsyncResult(), System.Net.LazyAsyncResult.InternalWaitForCompletion(), and System.Net.LazyAsyncResult.Result.
Referenced by System.Net.Mime.MimeWriter.EndClose(), System.Net.Mime.BaseWriter.EndGetContentStream(), System.Net.Mail.ReadLinesCommand.EndSend(), and System.Net.Mail.CheckCommand.EndSend().