Terraria: System.Security.Cryptography.RSACng.TrySignHash
TrySignHash()
unsafe override bool System.Security.Cryptography.RSACng.TrySignHash (ReadOnlySpan< byte > hash, Span< byte > destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, out int bytesWritten) inline virtual
Reimplemented from System.Security.Cryptography.RSA.
Definition at line 626 of file RSACng.cs.
    {
        string name = hashAlgorithm.Name;
        if (string.IsNullOrEmpty(name))
        {
            throw new ArgumentException(System.SR.Cryptography_HashAlgorithmNameNullOrEmpty, "hashAlgorithm");
        }
        if (padding == null)
        {
            throw new ArgumentNullException("padding");
        }
        using SafeNCryptKeyHandle keyHandle = GetDuplicatedKeyHandle();
        if (hash.Length != GetHashSizeInBytes(hashAlgorithm))
        {
            throw new CryptographicException(System.SR.Cryptography_SignHash_WrongSize);
        }
        IntPtr intPtr = Marshal.StringToHGlobalUni(name);
        try
        {
            switch (padding.Mode)
            {
            case RSASignaturePaddingMode.Pkcs1:
            {
                global::Interop.BCrypt.BCRYPT_PKCS1_PADDING_INFO bCRYPT_PKCS1_PADDING_INFO = default(global::Interop.BCrypt.BCRYPT_PKCS1_PADDING_INFO);
                bCRYPT_PKCS1_PADDING_INFO.pszAlgId = intPtr;
                global::Interop.BCrypt.BCRYPT_PKCS1_PADDING_INFO bCRYPT_PKCS1_PADDING_INFO2 = bCRYPT_PKCS1_PADDING_INFO;
                return keyHandle.TrySignHash(hash, destination, global::Interop.NCrypt.AsymmetricPaddingMode.NCRYPT_PAD_PKCS1_FLAG, &bCRYPT_PKCS1_PADDING_INFO2, out bytesWritten);
            }
            case RSASignaturePaddingMode.Pss:
            {
                global::Interop.BCrypt.BCRYPT_PSS_PADDING_INFO bCRYPT_PSS_PADDING_INFO = default(global::Interop.BCrypt.BCRYPT_PSS_PADDING_INFO);
                bCRYPT_PSS_PADDING_INFO.pszAlgId = intPtr;
                bCRYPT_PSS_PADDING_INFO.cbSalt = hash.Length;
                global::Interop.BCrypt.BCRYPT_PSS_PADDING_INFO bCRYPT_PSS_PADDING_INFO2 = bCRYPT_PSS_PADDING_INFO;
                return keyHandle.TrySignHash(hash, destination, global::Interop.NCrypt.AsymmetricPaddingMode.NCRYPT_PAD_PSS_FLAG, &bCRYPT_PSS_PADDING_INFO2, out bytesWritten);
            }
            default:
                throw new CryptographicException(System.SR.Cryptography_UnsupportedPaddingMode);
            }
        }
        finally
        {
            Marshal.FreeHGlobal(intPtr);
        }
    }
References System.SR.Cryptography_HashAlgorithmNameNullOrEmpty, System.SR.Cryptography_SignHash_WrongSize, System.SR.Cryptography_UnsupportedPaddingMode, System.destination, System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Security.Cryptography.RSACng.GetDuplicatedKeyHandle(), System.Security.Cryptography.RSACng.GetHashSizeInBytes(), System.Security.Cryptography.RSASignaturePadding.Mode, System.Security.Cryptography.HashAlgorithmName.Name, and System.Runtime.InteropServices.Marshal.StringToHGlobalUni().