Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.Cleanup
Cleanup()
void System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.Cleanup () inline
Definition at line 68 of file MsQuicStream.cs.
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"{TraceId} releasing handles.", "Cleanup");
            }
            ShutdownState = ShutdownState.Finished;
            CleanupSendState(this);
            Handle?.Dispose();
            Marshal.FreeHGlobal(SendQuicBuffers);
            SendQuicBuffers = IntPtr.Zero;
            if (StateGCHandle.IsAllocated)
            {
                StateGCHandle.Free();
            }
            ConnectionState?.RemoveStream(null);
        }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream.CleanupSendState(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ConnectionState, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Runtime.InteropServices.GCHandle.Free(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.Handle, System.Net.NetEventSource.Info(), System.Runtime.InteropServices.GCHandle.IsAllocated, System.Net.NetEventSource.Log, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.SendQuicBuffers, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.StateGCHandle, and System.IntPtr.Zero.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.Dispose().