Terraria: System.Security.Cryptography.RSACng.ImportEncryptedPkcs8PrivateKey
ImportEncryptedPkcs8PrivateKey() [1/2]
override void System.Security.Cryptography.RSACng.ImportEncryptedPkcs8PrivateKey (ReadOnlySpan< byte > passwordBytes, ReadOnlySpan< byte > source, out int bytesRead) inline virtual
Reimplemented from System.Security.Cryptography.RSA.
Definition at line 442 of file RSACng.cs.
    {
        ThrowIfDisposed();
        int bytesRead2;
        System.Security.Cryptography.CngPkcs8.Pkcs8Response response = System.Security.Cryptography.CngPkcs8.ImportEncryptedPkcs8PrivateKey(passwordBytes, source, out bytesRead2);
        ProcessPkcs8Response(response);
        bytesRead = bytesRead2;
    }
References System.Security.Cryptography.CngPkcs8.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.RSACng.ProcessPkcs8Response(), System.source, and System.Security.Cryptography.RSACng.ThrowIfDisposed().