Terraria: System.Collections.Immutable.ImmutableDictionary.HashBucket.Add
Add()
HashBucket System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket.Add (TKey key, TValue value, IEqualityComparer< KeyValuePair< TKey, TValue > > keyOnlyComparer, IEqualityComparer< TValue > valueComparer, KeyCollisionBehavior behavior, out OperationResult result) inline package
Definition at line 747 of file ImmutableDictionary.cs.
        {
            KeyValuePair<TKey, TValue> keyValuePair = new KeyValuePair<TKey, TValue>(key, value);
            if (IsEmpty)
            {
                result = OperationResult.SizeChanged;
                return new HashBucket(keyValuePair);
            }
            if (keyOnlyComparer.Equals(keyValuePair, _firstValue))
            {
                switch (behavior)
                {
                case KeyCollisionBehavior.SetValue:
                    result = OperationResult.AppliedWithoutSizeChange;
                    return new HashBucket(keyValuePair, _additionalElements);
                case KeyCollisionBehavior.Skip:
                    result = OperationResult.NoChangeRequired;
                    return this;
                case KeyCollisionBehavior.ThrowIfValueDifferent:
                    if (!valueComparer.Equals(_firstValue.Value, value))
                    {
                        throw new ArgumentException(System.SR.Format(System.SR.DuplicateKey, key));
                    }
                    result = OperationResult.NoChangeRequired;
                    return this;
                case KeyCollisionBehavior.ThrowAlways:
                    throw new ArgumentException(System.SR.Format(System.SR.DuplicateKey, key));
                default:
                    throw new InvalidOperationException();
                }
            }
            int num = _additionalElements.IndexOf(keyValuePair, keyOnlyComparer);
            if (num < 0)
            {
                result = OperationResult.SizeChanged;
                return new HashBucket(_firstValue, _additionalElements.Add(keyValuePair));
            }
            switch (behavior)
            {
            case KeyCollisionBehavior.SetValue:
                result = OperationResult.AppliedWithoutSizeChange;
                return new HashBucket(_firstValue, _additionalElements.ReplaceAt(num, keyValuePair));
            case KeyCollisionBehavior.Skip:
                result = OperationResult.NoChangeRequired;
                return this;
            case KeyCollisionBehavior.ThrowIfValueDifferent:
                if (!valueComparer.Equals(_additionalElements.ItemRef(num).Value, value))
                {
                    throw new ArgumentException(System.SR.Format(System.SR.DuplicateKey, key));
                }
                result = OperationResult.NoChangeRequired;
                return this;
            case KeyCollisionBehavior.ThrowAlways:
                throw new ArgumentException(System.SR.Format(System.SR.DuplicateKey, key));
            default:
                throw new InvalidOperationException();
            }
        }
References System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket.HashBucket(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket._additionalElements, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket._firstValue, System.Collections.Immutable.ImmutableList< T >.Add(), System.SR.DuplicateKey, System.SR.Format(), System.Collections.Immutable.ImmutableList< T >.IndexOf(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket.IsEmpty, System.Collections.Immutable.ImmutableList< T >.ItemRef(), System.key, and System.value.