Terraria: System.Collections.Immutable.ImmutableDictionary.HashBucket.Remove
Remove()
HashBucket System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket.Remove (TKey key, IEqualityComparer< KeyValuePair< TKey, TValue > > keyOnlyComparer, out OperationResult result) inline package
Definition at line 806 of file ImmutableDictionary.cs.
        {
            if (IsEmpty)
            {
                result = OperationResult.NoChangeRequired;
                return this;
            }
            KeyValuePair<TKey, TValue> keyValuePair = new KeyValuePair<TKey, TValue>(key, default(TValue));
            if (keyOnlyComparer.Equals(_firstValue, keyValuePair))
            {
                if (_additionalElements.IsEmpty)
                {
                    result = OperationResult.SizeChanged;
                    return default(HashBucket);
                }
                int count = _additionalElements.Left.Count;
                result = OperationResult.SizeChanged;
                return new HashBucket(_additionalElements.Key, _additionalElements.RemoveAt(count));
            }
            int num = _additionalElements.IndexOf(keyValuePair, keyOnlyComparer);
            if (num < 0)
            {
                result = OperationResult.NoChangeRequired;
                return this;
            }
            result = OperationResult.SizeChanged;
            return new HashBucket(_firstValue, _additionalElements.RemoveAt(num));
        }
References System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket.HashBucket(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket._additionalElements, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket._firstValue, System.Collections.Immutable.ImmutableList< T >.Count, System.count, System.Collections.Immutable.ImmutableList< T >.IndexOf(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket.IsEmpty, System.Collections.Immutable.ImmutableList< T >.IsEmpty, System.key, and System.Collections.Immutable.ImmutableList< T >.RemoveAt().