Terraria: System.Net.ServiceNameStore.ExtractHostname
ExtractHostname()
string System.Net.ServiceNameStore.ExtractHostname (string uriPrefix, bool allowInvalidUriStrings) inline private
Definition at line 178 of file ServiceNameStore.cs.
    {
        if (Uri.IsWellFormedUriString(uriPrefix, UriKind.Absolute))
        {
            Uri uri = new Uri(uriPrefix);
            return uri.Host;
        }
        if (allowInvalidUriStrings)
        {
            int num = uriPrefix.IndexOf("://", StringComparison.Ordinal) + 3;
            int i = num;
            for (bool flag = false; i < uriPrefix.Length && uriPrefix[i] != '/' && (uriPrefix[i] != ':' || flag); i++)
            {
                if (uriPrefix[i] == '[')
                {
                    if (flag)
                    {
                        i = num;
                        break;
                    }
                    flag = true;
                }
                if (flag && uriPrefix[i] == ']')
                {
                    flag = false;
                }
            }
            return uriPrefix.Substring(num, i - num);
        }
        return null;
    }
References System.Uri.Host, and System.Uri.IsWellFormedUriString().
Referenced by System.Net.ServiceNameStore.BuildServiceNames(), and System.Net.ServiceNameStore.BuildSimpleServiceName().