Terraria: System.Net.ServiceNameStore.Add
Add()
bool System.Net.ServiceNameStore.Add (string uriPrefix) inline
Definition at line 105 of file ServiceNameStore.cs.
    {
        string[] array = BuildServiceNames(uriPrefix);
        bool flag = false;
        string[] array2 = array;
        foreach (string text in array2)
        {
            if (AddSingleServiceName(text))
            {
                flag = true;
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, System.SR.Format(System.SR.net_log_listener_spn_add, text, uriPrefix), "Add");
                }
            }
        }
        if (flag)
        {
            _serviceNameCollection = null;
        }
        else if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, System.SR.Format(System.SR.net_log_listener_spn_not_add, uriPrefix), "Add");
        }
        return flag;
    }
References System.Net.ServiceNameStore._serviceNameCollection, System.Net.ServiceNameStore.AddSingleServiceName(), System.array, System.Net.ServiceNameStore.BuildServiceNames(), System.SR.Format(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_log_listener_spn_add, System.SR.net_log_listener_spn_not_add, and System.text.
Referenced by System.Net.HttpListener.AddPrefix().