Terraria: System.Net.ServiceNameStore.Remove
Remove()
bool System.Net.ServiceNameStore.Remove (string uriPrefix) inline
Definition at line 132 of file ServiceNameStore.cs.
    {
        string inputServiceName = BuildSimpleServiceName(uriPrefix);
        inputServiceName = NormalizeServiceName(inputServiceName);
        bool flag = Contains(inputServiceName);
        if (flag)
        {
            _serviceNames.Remove(inputServiceName);
            _serviceNameCollection = null;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            if (flag)
            {
                System.Net.NetEventSource.Info(this, System.SR.Format(System.SR.net_log_listener_spn_remove, inputServiceName, uriPrefix), "Remove");
            }
            else
            {
                System.Net.NetEventSource.Info(this, System.SR.Format(System.SR.net_log_listener_spn_not_remove, uriPrefix), "Remove");
            }
        }
        return flag;
    }
References System.Net.ServiceNameStore._serviceNameCollection, System.Net.ServiceNameStore._serviceNames, System.Net.ServiceNameStore.BuildSimpleServiceName(), System.Net.ServiceNameStore.Contains(), System.SR.Format(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_log_listener_spn_not_remove, System.SR.net_log_listener_spn_remove, System.Net.ServiceNameStore.NormalizeServiceName(), and System.Collections.Generic.List< T >.Remove().
Referenced by System.Net.HttpListener.RemovePrefix().