Terraria: System.Net.ServiceNameStore.AddSingleServiceName
AddSingleServiceName()
bool System.Net.ServiceNameStore.AddSingleServiceName (string spn) inline private
Definition at line 94 of file ServiceNameStore.cs.
    {
        spn = NormalizeServiceName(spn);
        if (Contains(spn))
        {
            return false;
        }
        _serviceNames.Add(spn);
        return true;
    }
References System.Net.ServiceNameStore._serviceNames, System.Collections.Generic.List< T >.Add(), System.Net.ServiceNameStore.Contains(), and System.Net.ServiceNameStore.NormalizeServiceName().
Referenced by System.Net.ServiceNameStore.Add().