Terraria: System.Net.ServiceNameStore.BuildServiceNames
BuildServiceNames()
string[] System.Net.ServiceNameStore.BuildServiceNames (string uriPrefix) inline
Definition at line 220 of file ServiceNameStore.cs.
    {
        string text = ExtractHostname(uriPrefix, allowInvalidUriStrings: true);
        IPAddress address = null;
        if (string.Equals(text, "*", StringComparison.OrdinalIgnoreCase) || string.Equals(text, "+", StringComparison.OrdinalIgnoreCase) || IPAddress.TryParse(text, out address))
        {
            try
            {
                string hostName = Dns.GetHostEntry(string.Empty).HostName;
                return new string[1] { "HTTP/" + hostName };
            }
            catch (SocketException)
            {
                return Array.Empty<string>();
            }
            catch (SecurityException)
            {
                return Array.Empty<string>();
            }
        }
        if (!text.Contains('.'))
        {
            try
            {
                string hostName2 = Dns.GetHostEntry(text).HostName;
                return new string[2]
                {
                    "HTTP/" + text,
                    "HTTP/" + hostName2
                };
            }
            catch (SocketException)
            {
                return new string[1] { "HTTP/" + text };
            }
            catch (SecurityException)
            {
                return new string[1] { "HTTP/" + text };
            }
        }
        return new string[1] { "HTTP/" + text };
    }
References System.Net.Equals, System.Net.ServiceNameStore.ExtractHostname(), System.Net.Dns.GetHostEntry(), System.text, and System.Net.IPAddress.TryParse().
Referenced by System.Net.ServiceNameStore.Add().