Terraria: LegacyChatMonitor.DrawChat
DrawChat()
void LegacyChatMonitor.DrawChat (bool drawingPlayerChat) inline
Implements IChatMonitor.
     {
         int num = startChatLine;
         int num2 = startChatLine + showCount;
         if (num2 >= numChatLines)
         {
             num2 = --numChatLines;
             num = num2 - showCount;
         }
         int num3 = 0;
         int num4 = -1;
         int num5 = -1;
         for (int i = num; i < num2; i++)
         {
             if (drawingPlayerChat || (chatLine[i].showTime > 0 && chatLine[i].parsedText.Length != 0))
             {
                 int hoveredSnippet = -1;
                 ChatManager.DrawColorCodedStringWithShadow(Main.spriteBatch, FontAssets.MouseText.Value, chatLine[i].parsedText, new Vector2(88f, Main.screenHeight - 30 - 28 - num3 * 21), 0f, Vector2.Zero, Vector2.One, out hoveredSnippet);
                 if (hoveredSnippet >= 0 && chatLine[i].parsedText[hoveredSnippet].CheckForHover)
                 {
                     num4 = i;
                     num5 = hoveredSnippet;
                 }
             }
             num3++;
         }
         if (num4 > -1)
         {
             chatLine[num4].parsedText[num5].OnHover();
             if (Main.mouseLeft && Main.mouseLeftRelease)
             {
                 chatLine[num4].parsedText[num5].OnClick();
             }
         }
     }
References chatLine, ChatManager.DrawColorCodedStringWithShadow(), Main.mouseLeft, Main.mouseLeftRelease, FontAssets.MouseText, numChatLines, TextSnippet.OnClick(), TextSnippet.OnHover(), ChatLine.parsedText, Main.screenHeight, showCount, Main.spriteBatch, startChatLine, and Asset< T >.Value.