Terraria: System.Runtime.CompilerServices.ConditionalWeakTable.Container.VerifyIntegrity
VerifyIntegrity()
void System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.VerifyIntegrity () inline private
Definition at line 323 of file ConditionalWeakTable.cs.
        {
            if (_invalid)
            {
                throw new InvalidOperationException(SR.InvalidOperation_CollectionCorrupted);
            }
        }
References System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container._invalid, and System.SR.InvalidOperation_CollectionCorrupted.
Referenced by System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.CreateEntryNoResize(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.Remove(), and System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.UpdateValue().