Terraria: System.Runtime.MemoryFailPoint.MemFreeAfterAddress
MemFreeAfterAddress()
static unsafe ulong System.Runtime.MemoryFailPoint.MemFreeAfterAddress (void * address, ulong size) inline static private
Definition at line 180 of file MemoryFailPoint.cs.
    {
        if (size >= s_topOfMemory)
        {
            return 0uL;
        }
        ulong num = 0uL;
        Interop.Kernel32.MEMORY_BASIC_INFORMATION lpBuffer = default(Interop.Kernel32.MEMORY_BASIC_INFORMATION);
        UIntPtr dwLength = (UIntPtr)(ulong)sizeof(Interop.Kernel32.MEMORY_BASIC_INFORMATION);
        while ((ulong)((long)address + (long)size) < s_topOfMemory)
        {
            UIntPtr uIntPtr = Interop.Kernel32.VirtualQuery(address, ref lpBuffer, dwLength);
            if (uIntPtr == UIntPtr.Zero)
            {
                throw Win32Marshal.GetExceptionForLastWin32Error();
            }
            ulong num2 = lpBuffer.RegionSize.ToUInt64();
            if (lpBuffer.State == 65536)
            {
                if (num2 >= size)
                {
                    return num2;
                }
                num = Math.Max(num, num2);
            }
            address = (void*)((ulong)address + num2);
        }
        return num;
    }
References System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.Math.Max(), System.Runtime.MemoryFailPoint.s_topOfMemory, Interop.Kernel32.VirtualQuery(), and System.UIntPtr.Zero.
Referenced by System.Runtime.MemoryFailPoint.CheckForFreeAddressSpace().