Terraria: System.Runtime.CompilerServices.ConditionalWeakTable.Container.FindEntry
FindEntry()
int System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.FindEntry (TKey key, out object value) inline package
Definition at line 164 of file ConditionalWeakTable.cs.
        {
            int num = RuntimeHelpers.GetHashCode(key) & 0x7FFFFFFF;
            int num2 = num & (_buckets.Length - 1);
            for (int num3 = Volatile.Read(ref _buckets[num2]); num3 != -1; num3 = _entries[num3].Next)
            {
                if (_entries[num3].HashCode == num && _entries[num3].depHnd.UnsafeGetTargetAndDependent(out value) == key)
                {
                    GC.KeepAlive(this);
                    return num3;
                }
            }
            GC.KeepAlive(this);
            value = null;
            return -1;
        }
References System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container._buckets, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container._entries, System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(), System.GC.KeepAlive(), System.key, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Entry.Next, System.Threading.Volatile.Read(), and System.value.
Referenced by System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.Remove(), and System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.TryGetValueWorker().