Terraria: System.Runtime.CompilerServices.ConditionalWeakTable.Container.TryGetEntry
TryGetEntry()
bool System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.TryGetEntry (int index, [NotNullWhen(true)] out TKey key, [MaybeNullWhen(false)] out TValue value) inline package
Definition at line 181 of file ConditionalWeakTable.cs.
        {
            if (index < _entries.Length)
            {
                object dependent;
                object obj = _entries[index].depHnd.UnsafeGetTargetAndDependent(out dependent);
                GC.KeepAlive(this);
                if (obj != null)
                {
                    key = Unsafe.As<TKey>(obj);
                    value = Unsafe.As<TValue>(dependent);
                    return true;
                }
            }
            key = null;
            value = null;
            return false;
        }
References System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container._entries, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Entry.depHnd, System.index, System.GC.KeepAlive(), System.key, System.obj, System.Runtime.DependentHandle.UnsafeGetTargetAndDependent(), and System.value.
Referenced by System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Enumerator.MoveNext().