Terraria: System.Runtime.CompilerServices.ConditionalWeakTable.Container.RemoveIndex
RemoveIndex()
void System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.RemoveIndex (int entryIndex) inline private
Definition at line 221 of file ConditionalWeakTable.cs.
        {
            ref Entry reference = ref _entries[entryIndex];
            Volatile.Write(ref reference.HashCode, -1);
            reference.depHnd.UnsafeSetTargetToNull();
        }
References System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container._entries, and System.Threading.Volatile.Write().
Referenced by System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.Remove(), and System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.RemoveAllKeys().