Terraria: System.Runtime.CompilerServices.ConditionalWeakTable.Container.Resize
Resize() [2/2]
Container System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.Resize (int newSize) inline package
Definition at line 264 of file ConditionalWeakTable.cs.
        {
            int[] array = new int[newSize];
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = -1;
            }
            Entry[] array2 = new Entry[newSize];
            int j = 0;
            bool flag = _parent != null && _parent._activeEnumeratorRefCount > 0;
            if (flag)
            {
                for (; j < _entries.Length; j++)
                {
                    ref Entry reference = ref _entries[j];
                    ref Entry reference2 = ref array2[j];
                    int num = (reference2.HashCode = reference.HashCode);
                    reference2.depHnd = reference.depHnd;
                    int num2 = num & (array.Length - 1);
                    reference2.Next = array[num2];
                    array[num2] = j;
                }
            }
            else
            {
                for (int k = 0; k < _entries.Length; k++)
                {
                    ref Entry reference3 = ref _entries[k];
                    int hashCode = reference3.HashCode;
                    DependentHandle depHnd = reference3.depHnd;
                    if (hashCode != -1 && depHnd.IsAllocated)
                    {
                        if (depHnd.UnsafeGetTarget() != null)
{
                            ref Entry reference4 = ref array2[j];
                            reference4.HashCode = hashCode;
                            reference4.depHnd = depHnd;
                            int num3 = hashCode & (array.Length - 1);
                            reference4.Next = array[num3];
                            array[num3] = j;
                            j++;
                        }
                        else
{
                            Volatile.Write(ref reference3.HashCode, -1);
                        }
                    }
                }
            }
            Container container = new Container(_parent, array, array2, j);
            if (flag)
            {
                GC.SuppressFinalize(this);
            }
            _oldKeepAlive = container;
            GC.KeepAlive(this);
            return container;
        }
References System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.Container(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container._entries, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container._oldKeepAlive, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container._parent, System.array, System.Runtime.DependentHandle.IsAllocated, System.GC.KeepAlive(), System.newSize, System.GC.SuppressFinalize(), System.Runtime.DependentHandle.UnsafeGetTarget(), and System.Threading.Volatile.Write().