Terraria: System.Runtime.MemoryFailPoint.MemoryFailPoint
MemoryFailPoint()
System.Runtime.MemoryFailPoint.MemoryFailPoint (int sizeInMegabytes) inline
Definition at line 54 of file MemoryFailPoint.cs.
    {
        if (sizeInMegabytes <= 0)
        {
            throw new ArgumentOutOfRangeException("sizeInMegabytes", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        ulong num = (_reservedMemory = (ulong)((long)sizeInMegabytes << 20));
        ulong num2 = (ulong)(Math.Ceiling((double)num / (double)s_GCSegmentSize) * (double)s_GCSegmentSize);
        if (num2 >= s_topOfMemory)
        {
            throw new InsufficientMemoryException(SR.InsufficientMemory_MemFailPoint_TooBig);
        }
        ulong num3 = (ulong)(Math.Ceiling((double)sizeInMegabytes / 16.0) * 16.0);
        num3 <<= 20;
        for (int i = 0; i < 3; i++)
        {
            if (!CheckForAvailableMemory(out var availPageFile, out var totalAddressSpaceFree))
            {
                return;
            }
            ulong memoryFailPointReservedMemory = MemoryFailPointReservedMemory;
            ulong num4 = num2 + memoryFailPointReservedMemory;
            bool flag = num4 < num2 || num4 < memoryFailPointReservedMemory;
            bool flag2 = availPageFile < num3 + memoryFailPointReservedMemory + 16777216 || flag;
            bool flag3 = totalAddressSpaceFree < num4 || flag;
            long num5 = Environment.TickCount;
            if (num5 > LastTimeCheckingAddressSpace + 10000 || num5 < LastTimeCheckingAddressSpace || LastKnownFreeAddressSpace < (long)num2)
            {
                CheckForFreeAddressSpace(num2, shouldThrow: false);
            }
            bool flag4 = (ulong)LastKnownFreeAddressSpace < num2;
            if (!flag2 && !flag3 && !flag4)
            {
                break;
            }
            switch (i)
            {
            case 0:
                GC.Collect();
                break;
            case 1:
                if (flag2)
                {
                    UIntPtr numBytes = new UIntPtr(num2);
                    GrowPageFileIfNecessaryAndPossible(numBytes);
                }
                break;
            case 2:
                if (flag2 || flag3)
                {
                    InsufficientMemoryException ex = new InsufficientMemoryException(SR.InsufficientMemory_MemFailPoint);
                    throw ex;
                }
                if (flag4)
                {
                    InsufficientMemoryException ex2 = new InsufficientMemoryException(SR.InsufficientMemory_MemFailPoint_VAFrag);
                    throw ex2;
                }
                break;
            }
        }
        AddToLastKnownFreeAddressSpace((long)(0L - num));
        if (LastKnownFreeAddressSpace < 0)
        {
            CheckForFreeAddressSpace(num2, shouldThrow: true);
        }
        AddMemoryFailPointReservation((long)num);
        _mustSubtractReservation = true;
    }
References System.Runtime.MemoryFailPoint._mustSubtractReservation, System.Runtime.MemoryFailPoint._reservedMemory, System.Runtime.MemoryFailPoint.AddMemoryFailPointReservation(), System.Runtime.MemoryFailPoint.AddToLastKnownFreeAddressSpace(), System.SR.ArgumentOutOfRange_NeedNonNegNum, System.Math.Ceiling(), System.Runtime.MemoryFailPoint.CheckForAvailableMemory(), System.Runtime.MemoryFailPoint.CheckForFreeAddressSpace(), System.GC.Collect(), System.Runtime.MemoryFailPoint.GrowPageFileIfNecessaryAndPossible(), System.SR.InsufficientMemory_MemFailPoint, System.SR.InsufficientMemory_MemFailPoint_TooBig, System.SR.InsufficientMemory_MemFailPoint_VAFrag, System.L, System.Runtime.MemoryFailPoint.LastKnownFreeAddressSpace, System.Runtime.MemoryFailPoint.LastTimeCheckingAddressSpace, System.Runtime.MemoryFailPoint.MemoryFailPointReservedMemory, System.Runtime.MemoryFailPoint.s_GCSegmentSize, System.Runtime.MemoryFailPoint.s_topOfMemory, and System.Environment.TickCount.