Terraria: ReLogic.Peripherals.RGB.Razer.EffectHandle.Reset
Reset()
void ReLogic.Peripherals.RGB.Razer.EffectHandle.Reset () inline
Definition at line 45 of file EffectHandle.cs.
    {
        if (!(_handle == Guid.Empty))
        {
            ValidateNativeCall(NativeMethods.DeleteEffect(_handle));
            _handle = Guid.Empty;
        }
    }
References ReLogic.Peripherals.RGB.Razer.EffectHandle._handle, ReLogic.Peripherals.RGB.Razer.NativeMethods.DeleteEffect(), System.Guid.Empty, and ReLogic.Peripherals.RGB.Razer.EffectHandle.ValidateNativeCall().
Referenced by ReLogic.Peripherals.RGB.Razer.EffectHandle.SetAsChromaLinkEffect(), ReLogic.Peripherals.RGB.Razer.EffectHandle.SetAsHeadsetEffect(), ReLogic.Peripherals.RGB.Razer.EffectHandle.SetAsKeyboardEffect(), ReLogic.Peripherals.RGB.Razer.EffectHandle.SetAsKeypadEffect(), ReLogic.Peripherals.RGB.Razer.EffectHandle.SetAsMouseEffect(), and ReLogic.Peripherals.RGB.Razer.EffectHandle.SetAsMousepadEffect().