Terraria: ReLogic.Peripherals.RGB.Razer.EffectHandle.Apply
Apply()
void ReLogic.Peripherals.RGB.Razer.EffectHandle.Apply () inline
Definition at line 54 of file EffectHandle.cs.
    {
        if (_handle != Guid.Empty)
        {
            ValidateNativeCall(NativeMethods.SetEffect(_handle));
        }
    }
References ReLogic.Peripherals.RGB.Razer.EffectHandle._handle, System.Guid.Empty, ReLogic.Peripherals.RGB.Razer.NativeMethods.SetEffect(), and ReLogic.Peripherals.RGB.Razer.EffectHandle.ValidateNativeCall().
Referenced by ReLogic.Peripherals.RGB.Razer.RazerHeadset.Present(), ReLogic.Peripherals.RGB.Razer.RazerKeyboard.Present(), ReLogic.Peripherals.RGB.Razer.RazerKeypad.Present(), ReLogic.Peripherals.RGB.Razer.RazerLink.Present(), ReLogic.Peripherals.RGB.Razer.RazerMouse.Present(), and ReLogic.Peripherals.RGB.Razer.RazerMousepad.Present().