Terraria: System.Xml.XmlNodeReaderNavigator.ResetMove
ResetMove()
void System.Xml.XmlNodeReaderNavigator.ResetMove (ref int level, ref XmlNodeType nt) inline
Definition at line 588 of file XmlNodeReaderNavigator.cs.
    {
        LogMove(level);
        if (_bCreatedOnAttribute)
        {
            return;
        }
        if (_nAttrInd != -1)
        {
            if (_bOnAttrVal)
            {
                level--;
                _bOnAttrVal = false;
            }
            _nLogAttrInd = _nAttrInd;
            level--;
            _nAttrInd = -1;
            nt = _curNode.NodeType;
            return;
        }
        if (_bOnAttrVal && _curNode.NodeType != XmlNodeType.Attribute)
        {
            ResetToAttribute(ref level);
        }
        if (_curNode.NodeType == XmlNodeType.Attribute)
        {
            _curNode = ((XmlAttribute)_curNode).OwnerElement;
            _attrIndex = -1;
            level--;
            nt = XmlNodeType.Element;
        }
        if (_curNode.NodeType == XmlNodeType.Element)
        {
            _elemNode = _curNode;
        }
    }
References System.Xml.XmlNodeReaderNavigator._attrIndex, System.Xml.XmlNodeReaderNavigator._bCreatedOnAttribute, System.Xml.XmlNodeReaderNavigator._bOnAttrVal, System.Xml.XmlNodeReaderNavigator._curNode, System.Xml.XmlNodeReaderNavigator._elemNode, System.Xml.XmlNodeReaderNavigator._nAttrInd, System.Xml.XmlNodeReaderNavigator._nLogAttrInd, System.Xml.XmlNodeReaderNavigator.LogMove(), System.Xml.XmlNode.NodeType, and System.Xml.XmlNodeReaderNavigator.ResetToAttribute().
Referenced by System.Xml.XmlNodeReader.MoveToAttribute(), System.Xml.XmlNodeReader.MoveToAttribute(), System.Xml.XmlNodeReader.MoveToAttribute(), System.Xml.XmlNodeReader.MoveToFirstAttribute(), and System.Xml.XmlNodeReader.ReSetReadingMarks().