Terraria: System.Xml.XmlNodeReaderNavigator.InitDecAttr
InitDecAttr()
void System.Xml.XmlNodeReaderNavigator.InitDecAttr () inline private
Definition at line 356 of file XmlNodeReaderNavigator.cs.
    {
        int num = 0;
        string version = _doc.Version;
        if (version != null && version.Length != 0)
        {
            decNodeAttributes[num].name = "version";
            decNodeAttributes[num].value = version;
            num++;
        }
        version = _doc.Encoding;
        if (version != null && version.Length != 0)
        {
            decNodeAttributes[num].name = "encoding";
            decNodeAttributes[num].value = version;
            num++;
        }
        version = _doc.Standalone;
        if (version != null && version.Length != 0)
        {
            decNodeAttributes[num].name = "standalone";
            decNodeAttributes[num].value = version;
            num++;
        }
        _nDeclarationAttrCount = num;
    }
References System.Xml.XmlNodeReaderNavigator._doc, System.Xml.XmlNodeReaderNavigator._nDeclarationAttrCount, System.Xml.XmlNodeReaderNavigator.decNodeAttributes, System.Xml.XmlDocument.Encoding, System.Xml.XmlNodeReaderNavigator.VirtualAttribute.name, System.Xml.XmlDocument.Standalone, System.Xml.XmlNodeReaderNavigator.VirtualAttribute.value, and System.Xml.XmlDocument.Version.
Referenced by System.Xml.XmlNodeReaderNavigator.GetDecAttrInd(), System.Xml.XmlNodeReaderNavigator.GetDeclarationAttr(), and System.Xml.XmlNodeReaderNavigator.MoveToNextAttribute().