Terraria: System.Xml.XmlNodeReaderNavigator.MoveToNextAttribute
MoveToNextAttribute()
bool System.Xml.XmlNodeReaderNavigator.MoveToNextAttribute (ref int level) inline
Definition at line 715 of file XmlNodeReaderNavigator.cs.
    {
        if (_bCreatedOnAttribute)
        {
            return false;
        }
        switch (_curNode.NodeType)
        {
        case XmlNodeType.Attribute:
            if (_attrIndex >= _elemNode.Attributes.Count - 1)
            {
                return false;
            }
            _curNode = _elemNode.Attributes[++_attrIndex];
            return true;
        case XmlNodeType.Element:
            if (_curNode.Attributes.Count > 0)
            {
                level++;
                _elemNode = _curNode;
                _curNode = _curNode.Attributes[0];
                _attrIndex = 0;
                return true;
            }
            break;
        case XmlNodeType.XmlDeclaration:
            if (_nDeclarationAttrCount == -1)
            {
                InitDecAttr();
            }
            _nAttrInd++;
            if (_nAttrInd < _nDeclarationAttrCount)
            {
                if (_nAttrInd == 0)
                {
                    level++;
                }
                _bOnAttrVal = false;
                return true;
            }
            _nAttrInd--;
            break;
        case XmlNodeType.DocumentType:
            if (_nDocTypeAttrCount == -1)
            {
                InitDocTypeAttr();
            }
            _nAttrInd++;
            if (_nAttrInd < _nDocTypeAttrCount)
            {
                if (_nAttrInd == 0)
                {
                    level++;
                }
                _bOnAttrVal = false;
                return true;
            }
            _nAttrInd--;
            break;
        }
        return false;
    }
References System.Xml.XmlNodeReaderNavigator._attrIndex, System.Xml.XmlNodeReaderNavigator._bCreatedOnAttribute, System.Xml.XmlNodeReaderNavigator._bOnAttrVal, System.Xml.XmlNodeReaderNavigator._curNode, System.Xml.XmlNodeReaderNavigator._elemNode, System.Xml.XmlNodeReaderNavigator._nAttrInd, System.Xml.XmlNodeReaderNavigator._nDeclarationAttrCount, System.Xml.XmlNodeReaderNavigator._nDocTypeAttrCount, System.Xml.XmlNode.Attributes, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XmlNodeReaderNavigator.InitDecAttr(), System.Xml.XmlNodeReaderNavigator.InitDocTypeAttr(), and System.Xml.XmlNode.NodeType.
Referenced by System.Xml.XmlNodeReader.MoveToNextAttribute().