Terraria: System.Xml.XmlNodeReaderNavigator.InitDocTypeAttr
InitDocTypeAttr()
void System.Xml.XmlNodeReaderNavigator.InitDocTypeAttr () inline private
Definition at line 419 of file XmlNodeReaderNavigator.cs.
    {
        int num = 0;
        XmlDocumentType documentType = _doc.DocumentType;
        if (documentType == null)
        {
            _nDocTypeAttrCount = 0;
            return;
        }
        string publicId = documentType.PublicId;
        if (publicId != null)
        {
            docTypeNodeAttributes[num].name = "PUBLIC";
            docTypeNodeAttributes[num].value = publicId;
            num++;
        }
        publicId = documentType.SystemId;
        if (publicId != null)
        {
            docTypeNodeAttributes[num].name = "SYSTEM";
            docTypeNodeAttributes[num].value = publicId;
            num++;
        }
        _nDocTypeAttrCount = num;
    }
References System.Xml.XmlNodeReaderNavigator._doc, System.Xml.XmlNodeReaderNavigator._nDocTypeAttrCount, System.Xml.XmlNodeReaderNavigator.docTypeNodeAttributes, System.Xml.XmlDocument.DocumentType, System.Xml.XmlNodeReaderNavigator.VirtualAttribute.name, and System.Xml.XmlNodeReaderNavigator.VirtualAttribute.value.
Referenced by System.Xml.XmlNodeReaderNavigator.GetDocTypeAttrInd(), System.Xml.XmlNodeReaderNavigator.GetDocumentTypeAttr(), and System.Xml.XmlNodeReaderNavigator.MoveToNextAttribute().