Terraria: System.Xml.XmlNodeReaderNavigator.GetAttribute
GetAttribute() [3/3]
string System.Xml.XmlNodeReaderNavigator.GetAttribute (string name, string ns) inline
Definition at line 509 of file XmlNodeReaderNavigator.cs.
    {
        if (_bCreatedOnAttribute)
        {
            return null;
        }
        return _curNode.NodeType switch
        {
            XmlNodeType.Element => GetAttributeFromElement((XmlElement)_curNode, name, ns),
            XmlNodeType.Attribute => GetAttributeFromElement((XmlElement)_elemNode, name, ns),
            XmlNodeType.XmlDeclaration => (ns.Length == 0) ? GetDeclarationAttr((XmlDeclaration)_curNode, name) : null,
            XmlNodeType.DocumentType => (ns.Length == 0) ? GetDocumentTypeAttr((XmlDocumentType)_curNode, name) : null,
            _ => null,
        };
    }
References System.Xml.XmlNodeReaderNavigator._bCreatedOnAttribute, System.Xml.XmlNodeReaderNavigator._curNode, System.Xml.XmlNodeReaderNavigator._elemNode, System.Xml.Dictionary, System.Xml.XmlNodeReaderNavigator.GetAttributeFromElement(), System.Xml.XmlNodeReaderNavigator.GetDeclarationAttr(), and System.Xml.XmlNodeReaderNavigator.GetDocumentTypeAttr().