Terraria: System.Xml.XmlNodeReaderNavigator.RollBackMove
RollBackMove()
void System.Xml.XmlNodeReaderNavigator.RollBackMove (ref int level) inline
Definition at line 559 of file XmlNodeReaderNavigator.cs.
    {
        _curNode = _logNode;
        level = _nLogLevel;
        _nAttrInd = _nLogAttrInd;
        _attrIndex = _logAttrIndex;
        _bOnAttrVal = _bLogOnAttrVal;
    }
References System.Xml.XmlNodeReaderNavigator._attrIndex, System.Xml.XmlNodeReaderNavigator._bLogOnAttrVal, System.Xml.XmlNodeReaderNavigator._bOnAttrVal, System.Xml.XmlNodeReaderNavigator._curNode, System.Xml.XmlNodeReaderNavigator._logAttrIndex, System.Xml.XmlNodeReaderNavigator._logNode, System.Xml.XmlNodeReaderNavigator._nAttrInd, System.Xml.XmlNodeReaderNavigator._nLogAttrInd, and System.Xml.XmlNodeReaderNavigator._nLogLevel.
Referenced by System.Xml.XmlNodeReader.MoveToAttribute(), System.Xml.XmlNodeReader.MoveToAttribute(), System.Xml.XmlNodeReader.MoveToAttribute(), System.Xml.XmlNodeReader.MoveToElement(), System.Xml.XmlNodeReader.MoveToFirstAttribute(), and System.Xml.XmlNodeReader.MoveToNextAttribute().