Terraria: System.Xml.XmlNodeReaderNavigator.LookupPrefix
LookupPrefix()
string System.Xml.XmlNodeReaderNavigator.LookupPrefix (string namespaceName) inline package
Definition at line 928 of file XmlNodeReaderNavigator.cs.
    {
        if (_bCreatedOnAttribute || namespaceName == null)
        {
            return null;
        }
        if (namespaceName == "http://www.w3.org/2000/xmlns/")
        {
            return _nameTable.Add("xmlns");
        }
        if (namespaceName == "http://www.w3.org/XML/1998/namespace")
        {
            return _nameTable.Add("xml");
        }
        if (namespaceName.Length == 0)
        {
            return string.Empty;
        }
        XmlNode xmlNode = _curNode;
        while (xmlNode != null)
        {
            if (xmlNode.NodeType == XmlNodeType.Element)
            {
                XmlElement xmlElement = (XmlElement)xmlNode;
                if (xmlElement.HasAttributes)
                {
                    XmlAttributeCollection attributes = xmlElement.Attributes;
                    for (int i = 0; i < attributes.Count; i++)
                    {
                        XmlAttribute xmlAttribute = attributes[i];
                        if (!(xmlAttribute.Value == namespaceName))
{
                            continue;
                        }
                        if (xmlAttribute.Prefix.Length == 0 && xmlAttribute.LocalName == "xmlns")
{
                            if (LookupNamespace(string.Empty) == namespaceName)
{
                                return string.Empty;
                            }
                        }
                        else if (xmlAttribute.Prefix == "xmlns")
{
                            string localName = xmlAttribute.LocalName;
                            if (LookupNamespace(localName) == namespaceName)
{
                                return _nameTable.Add(localName);
                            }
                        }
                    }
                }
            }
            else if (xmlNode.NodeType == XmlNodeType.Attribute)
            {
                xmlNode = ((XmlAttribute)xmlNode).OwnerElement;
                continue;
            }
            xmlNode = xmlNode.ParentNode;
        }
        return null;
    }
References System.Xml.XmlNodeReaderNavigator._bCreatedOnAttribute, System.Xml.XmlNodeReaderNavigator._curNode, System.Xml.XmlNodeReaderNavigator._nameTable, System.Xml.XmlNameTable.Add(), System.Xml.XmlAttributeCollection.Count, System.Xml.Dictionary, and System.Xml.XmlNodeReaderNavigator.LookupNamespace().
Referenced by System.Xml.XmlNodeReader.LookupPrefix().