Terraria: System.Xml.XmlNodeReaderNavigator.GetNamespacesInScope
GetNamespacesInScope()
IDictionary< string, string > System.Xml.XmlNodeReaderNavigator.GetNamespacesInScope (XmlNamespaceScope scope) inline package
Definition at line 990 of file XmlNodeReaderNavigator.cs.
    {
        Dictionary<string, string> dictionary = new Dictionary<string, string>();
        if (_bCreatedOnAttribute)
        {
            return dictionary;
        }
        XmlNode xmlNode = _curNode;
        while (xmlNode != null)
        {
            if (xmlNode.NodeType == XmlNodeType.Element)
            {
                XmlElement xmlElement = (XmlElement)xmlNode;
                if (xmlElement.HasAttributes)
                {
                    XmlAttributeCollection attributes = xmlElement.Attributes;
                    for (int i = 0; i < attributes.Count; i++)
                    {
                        XmlAttribute xmlAttribute = attributes[i];
                        if (xmlAttribute.LocalName == "xmlns" && xmlAttribute.Prefix.Length == 0)
{
                            if (!dictionary.ContainsKey(string.Empty))
{
                                dictionary.Add(_nameTable.Add(string.Empty), _nameTable.Add(xmlAttribute.Value));
                            }
                        }
                        else if (xmlAttribute.Prefix == "xmlns")
{
                            string localName = xmlAttribute.LocalName;
                            if (!dictionary.ContainsKey(localName))
{
                                dictionary.Add(_nameTable.Add(localName), _nameTable.Add(xmlAttribute.Value));
                            }
                        }
                    }
                }
                if (scope == XmlNamespaceScope.Local)
                {
                    break;
                }
            }
            else if (xmlNode.NodeType == XmlNodeType.Attribute)
            {
                xmlNode = ((XmlAttribute)xmlNode).OwnerElement;
                continue;
            }
            xmlNode = xmlNode.ParentNode;
        }
        if (scope != XmlNamespaceScope.Local)
        {
            if (dictionary.ContainsKey(string.Empty) && dictionary[string.Empty] == string.Empty)
            {
                dictionary.Remove(string.Empty);
            }
            if (scope == XmlNamespaceScope.All)
            {
                dictionary.Add(_nameTable.Add("xml"), _nameTable.Add("http://www.w3.org/XML/1998/namespace"));
            }
        }
        return dictionary;
    }
References System.Xml.XmlNodeReaderNavigator._bCreatedOnAttribute, System.Xml.XmlNodeReaderNavigator._curNode, System.Xml.XmlNodeReaderNavigator._nameTable, System.Xml.XmlNameTable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XmlAttributeCollection.Count, System.dictionary, and System.Collections.Generic.Dictionary< TKey, TValue >.Remove().
Referenced by System.Xml.XmlNodeReader.GetNamespacesInScope().