Terraria: System.Xml.XmlNodeReaderNavigator.LookupNamespace
LookupNamespace()
string System.Xml.XmlNodeReaderNavigator.LookupNamespace (string prefix) inline
Definition at line 860 of file XmlNodeReaderNavigator.cs.
    {
        if (_bCreatedOnAttribute)
        {
            return null;
        }
        if (prefix == "xmlns")
        {
            return _nameTable.Add("http://www.w3.org/2000/xmlns/");
        }
        if (prefix == "xml")
        {
            return _nameTable.Add("http://www.w3.org/XML/1998/namespace");
        }
        if (prefix == null)
        {
            prefix = string.Empty;
        }
        string name = ((prefix.Length != 0) ? ("xmlns:" + prefix) : "xmlns");
        XmlNode xmlNode = _curNode;
        while (xmlNode != null)
        {
            if (xmlNode.NodeType == XmlNodeType.Element)
            {
                XmlElement xmlElement = (XmlElement)xmlNode;
                if (xmlElement.HasAttributes)
                {
                    XmlAttribute attributeNode = xmlElement.GetAttributeNode(name);
                    if (attributeNode != null)
                    {
                        return attributeNode.Value;
                    }
                }
            }
            else if (xmlNode.NodeType == XmlNodeType.Attribute)
            {
                xmlNode = ((XmlAttribute)xmlNode).OwnerElement;
                continue;
            }
            xmlNode = xmlNode.ParentNode;
        }
        if (prefix.Length == 0)
        {
            return string.Empty;
        }
        return null;
    }
References System.Xml.XmlNodeReaderNavigator._bCreatedOnAttribute, System.Xml.XmlNodeReaderNavigator._curNode, System.Xml.XmlNodeReaderNavigator._nameTable, System.Xml.XmlNameTable.Add(), System.Xml.Dictionary, and System.prefix.
Referenced by System.Xml.XmlNodeReader.LookupNamespace(), and System.Xml.XmlNodeReaderNavigator.LookupPrefix().