Terraria: System.Collections.Concurrent.ConcurrentQueueSegment.TryDequeue
TryDequeue()
bool System.Collections.Concurrent.ConcurrentQueueSegment< T >.TryDequeue ([MaybeNullWhen(false)] out T item) inline
Definition at line 56 of file ConcurrentQueueSegment.cs.
    {
        Slot[] slots = _slots;
        SpinWait spinWait = default(SpinWait);
        while (true)
        {
            int num = Volatile.Read(ref _headAndTail.Head);
            int num2 = num & _slotsMask;
            int num3 = Volatile.Read(ref slots[num2].SequenceNumber);
            int num4 = num3 - (num + 1);
            if (num4 == 0)
            {
                if (Interlocked.CompareExchange(ref _headAndTail.Head, num + 1, num) != num)
                {
                    continue;
                }
                item = slots[num2].Item;
                if (!Volatile.Read(ref _preservedForObservation))
                {
                    if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
                    {
                        slots[num2].Item = default(T);
                    }
                    Volatile.Write(ref slots[num2].SequenceNumber, num + slots.Length);
                }
                return true;
            }
            if (num4 < 0)
            {
                bool frozenForEnqueues = _frozenForEnqueues;
                int num5 = Volatile.Read(ref _headAndTail.Tail);
                if (num5 - num <= 0 || (frozenForEnqueues && num5 - FreezeOffset - num <= 0))
                {
                    break;
                }
                spinWait.SpinOnce(-1);
            }
        }
        item = default(T);
        return false;
    }
References System.Collections.Concurrent.ConcurrentQueueSegment< T >._frozenForEnqueues, System.Collections.Concurrent.ConcurrentQueueSegment< T >._headAndTail, System.Collections.Concurrent.ConcurrentQueueSegment< T >._preservedForObservation, System.Collections.Concurrent.ConcurrentQueueSegment< T >._slots, System.Collections.Concurrent.ConcurrentQueueSegment< T >._slotsMask, System.Threading.Interlocked.CompareExchange(), System.Collections.Concurrent.ConcurrentQueueSegment< T >.FreezeOffset, System.Collections.Concurrent.PaddedHeadAndTail.Head, System.Collections.Concurrent.ConcurrentQueueSegment< T >.Slot.Item, System.item, System.Threading.Volatile.Read(), System.Threading.SpinWait.SpinOnce(), System.Collections.Concurrent.PaddedHeadAndTail.Tail, and System.Threading.Volatile.Write().