Terraria: System.Xml.Xsl.Runtime.DodSequenceMerge.MergeSequences
MergeSequences()
IList< XPathNavigator > System.Xml.Xsl.Runtime.DodSequenceMerge.MergeSequences () inline
Definition at line 47 of file DodSequenceMerge.cs.
    {
        if (_firstSequence == null)
        {
            return XmlQueryNodeSequence.Empty;
        }
        if (_sequencesToMerge == null || _sequencesToMerge.Count <= 1)
        {
            return _firstSequence;
        }
        XmlQueryNodeSequence xmlQueryNodeSequence = new XmlQueryNodeSequence(_nodeCount);
        while (_sequencesToMerge.Count != 1)
        {
            IEnumerator<XPathNavigator> enumerator = _sequencesToMerge[_sequencesToMerge.Count - 1];
            _sequencesToMerge.RemoveAt(_sequencesToMerge.Count - 1);
            xmlQueryNodeSequence.Add(enumerator.Current);
            MoveAndInsertSequence(enumerator);
        }
        do
        {
            xmlQueryNodeSequence.Add(_sequencesToMerge[0].Current);
        }
        while (_sequencesToMerge[0].MoveNext());
        return xmlQueryNodeSequence;
    }
References System.Xml.Xsl.Runtime.DodSequenceMerge._firstSequence, System.Xml.Xsl.Runtime.DodSequenceMerge._nodeCount, System.Xml.Xsl.Runtime.DodSequenceMerge._sequencesToMerge, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.List< T >.Count, System.Xml.Xsl.Current, System.Xml.Dictionary, System.Xml.Xsl.Runtime.XmlQueryNodeSequence.Empty, System.Xml.Xsl.Runtime.DodSequenceMerge.MoveAndInsertSequence(), and System.Collections.Generic.List< T >.RemoveAt().