Terraria: Terraria.UI.SnapPoint.Calculate
Calculate()
void Terraria.UI.SnapPoint.Calculate (UIElement element) inline
    {
        CalculatedStyle dimensions = element.GetDimensions();
        Position = dimensions.Position() + _offset + _anchor * new Vector2(dimensions.Width, dimensions.Height);
    }
References Terraria.UI.SnapPoint._anchor, Terraria.UI.SnapPoint._offset, Terraria.UI.UIElement.GetDimensions(), Terraria.UI.CalculatedStyle.Height, Terraria.UI.CalculatedStyle.Position(), Terraria.UI.SnapPoint.Position, and Terraria.UI.CalculatedStyle.Width.
Referenced by Terraria.UI.UIElement.GetSnapPoint(), and Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetSnapPoints().