Terraria: Terraria.Social.WeGame.NetSocialModule._connectionStateMap
_connectionStateMap
ConcurrentDictionary<RailID, ConnectionState> Terraria.Social.WeGame.NetSocialModule._connectionStateMap = new ConcurrentDictionary<RailID, ConnectionState>() protected inherited
Definition at line 25 of file NetSocialModule.cs.
Referenced by Terraria.Social.WeGame.NetClientSocialModule.Close(), Terraria.Social.WeGame.NetServerSocialModule.CloseAndUpdateUserState(), Terraria.Social.WeGame.NetServerSocialModule.IsActiveUser(), Terraria.Social.WeGame.NetSocialModule.IsConnected(), Terraria.Social.WeGame.NetClientSocialModule.JoinServer(), Terraria.Social.WeGame.NetClientSocialModule.OnAuthSuccess(), Terraria.Social.WeGame.NetServerSocialModule.OnAuthSuccess(), Terraria.Social.WeGame.NetServerSocialModule.OnCreateSessionRequest(), Terraria.Social.WeGame.NetClientSocialModule.OnPacketRead(), Terraria.Social.WeGame.NetServerSocialModule.OnPacketRead(), Terraria.Social.WeGame.NetClientSocialModule.OnRailCreateSessionRequest(), and Terraria.Social.WeGame.NetServerSocialModule.UpdateUserStateBySessionAuthResult().