Terraria: System.IO.RandomAccess.ReadAtOffset
ReadAtOffset()
static unsafe int System.IO.RandomAccess.ReadAtOffset (SafeFileHandle handle, Span< byte > buffer, long fileOffset) inline static package
Definition at line 231 of file RandomAccess.cs.
    {
        if (handle.IsAsync)
        {
            return ReadSyncUsingAsyncHandle(handle, buffer, fileOffset);
        }
        NativeOverlapped nativeOverlappedForSyncHandle = GetNativeOverlappedForSyncHandle(handle, fileOffset);
        fixed (byte* bytes = &MemoryMarshal.GetReference(buffer))
        {
            if (Interop.Kernel32.ReadFile(handle, bytes, buffer.Length, out var numBytesRead, &nativeOverlappedForSyncHandle) != 0)
            {
                return numBytesRead;
            }
            int lastWin32ErrorAndDisposeHandleIfInvalid = FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(handle);
            return lastWin32ErrorAndDisposeHandleIfInvalid switch
            {
                38 => numBytesRead,
                109 => 0,
                _ => throw Win32Marshal.GetExceptionForWin32Error(lastWin32ErrorAndDisposeHandleIfInvalid, handle.Path),
            };
        }
    }
References System.IO.RandomAccess.buffer, System.bytes, System.IO.RandomAccess.fileOffset, System.IO.Win32Marshal.GetExceptionForWin32Error(), System.IO.Strategies.FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(), System.IO.RandomAccess.GetNativeOverlappedForSyncHandle(), System.handle, Interop.Kernel32.ReadFile(), and System.IO.RandomAccess.ReadSyncUsingAsyncHandle().
Referenced by Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal(), System.IO.RandomAccess.Read(), System.IO.Strategies.OSFileStreamStrategy.Read(), and System.IO.RandomAccess.ReadScatterAtOffset().