Terraria: System.IO.RandomAccess.WriteAtOffset
WriteAtOffset()
static unsafe void System.IO.RandomAccess.WriteAtOffset (SafeFileHandle handle, ReadOnlySpan< byte > buffer, long fileOffset) inline static package
Definition at line 298 of file RandomAccess.cs.
    {
        if (buffer.IsEmpty)
        {
            return;
        }
        if (handle.IsAsync)
        {
            WriteSyncUsingAsyncHandle(handle, buffer, fileOffset);
            return;
        }
        NativeOverlapped nativeOverlappedForSyncHandle = GetNativeOverlappedForSyncHandle(handle, fileOffset);
        fixed (byte* bytes = &MemoryMarshal.GetReference(buffer))
        {
            if (Interop.Kernel32.WriteFile(handle, bytes, buffer.Length, out var _, &nativeOverlappedForSyncHandle) == 0)
            {
                int lastWin32ErrorAndDisposeHandleIfInvalid = FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(handle);
                if (lastWin32ErrorAndDisposeHandleIfInvalid != 232)
                {
                    throw Win32Marshal.GetExceptionForWin32Error(lastWin32ErrorAndDisposeHandleIfInvalid, handle.Path);
                }
            }
        }
    }
References System.IO.RandomAccess.buffer, System.bytes, System.IO.RandomAccess.fileOffset, System.IO.Win32Marshal.GetExceptionForWin32Error(), System.IO.Strategies.FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(), System.IO.RandomAccess.GetNativeOverlappedForSyncHandle(), System.handle, Interop.Kernel32.WriteFile(), and System.IO.RandomAccess.WriteSyncUsingAsyncHandle().
Referenced by Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal(), System.IO.Strategies.OSFileStreamStrategy.Write(), System.IO.RandomAccess.Write(), System.IO.File.WriteAllBytes(), and System.IO.RandomAccess.WriteGatherAtOffset().