Terraria: System.IO.RandomAccess.ReadSyncUsingAsyncHandle
ReadSyncUsingAsyncHandle()
static unsafe int System.IO.RandomAccess.ReadSyncUsingAsyncHandle (SafeFileHandle handle, Span< byte > buffer, long fileOffset) inline static private
Definition at line 254 of file RandomAccess.cs.
    {
        handle.EnsureThreadPoolBindingInitialized();
        CallbackResetEvent callbackResetEvent = new CallbackResetEvent(handle.ThreadPoolBinding);
        NativeOverlapped* ptr = null;
        try
        {
            ptr = GetNativeOverlappedForAsyncHandle(handle.ThreadPoolBinding, fileOffset, callbackResetEvent);
            fixed (byte* bytes = &MemoryMarshal.GetReference(buffer))
            {
                Interop.Kernel32.ReadFile(handle, bytes, buffer.Length, IntPtr.Zero, ptr);
                int num = FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(handle);
                if (num == 997)
                {
                    callbackResetEvent.WaitOne();
                    num = 0;
                }
                if (num == 0)
                {
                    int lpNumberOfBytesTransferred = 0;
                    if (Interop.Kernel32.GetOverlappedResult(handle, ptr, ref lpNumberOfBytesTransferred, bWait: false))
                    {
                        return lpNumberOfBytesTransferred;
                    }
                    num = FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(handle);
                }
                if (num == 38 || num == 109)
                {
                    ptr->InternalLow = IntPtr.Zero;
                    return 0;
                }
                throw Win32Marshal.GetExceptionForWin32Error(num, handle.Path);
            }
        }
        finally
        {
            if (ptr != null)
            {
                callbackResetEvent.FreeNativeOverlapped(ptr);
            }
            callbackResetEvent.Dispose();
        }
    }
References System.IO.RandomAccess.buffer, System.bytes, System.IO.RandomAccess.fileOffset, System.IO.Win32Marshal.GetExceptionForWin32Error(), System.IO.Strategies.FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(), System.IO.RandomAccess.GetNativeOverlappedForAsyncHandle(), Interop.Kernel32.GetOverlappedResult(), System.handle, Interop.Kernel32.ReadFile(), and System.IntPtr.Zero.
Referenced by System.IO.RandomAccess.ReadAtOffset().