Terraria: System.IO.RandomAccess.WriteGatherAtOffset
WriteGatherAtOffset()
static void System.IO.RandomAccess.WriteGatherAtOffset (SafeFileHandle handle, IReadOnlyList< ReadOnlyMemory< byte > > buffers, long fileOffset) inline static package
Definition at line 511 of file RandomAccess.cs.
    {
        int num = 0;
        int count = buffers.Count;
        for (int i = 0; i < count; i++)
        {
            ReadOnlySpan<byte> span = buffers[i].Span;
            WriteAtOffset(handle, span, fileOffset + num);
            num += span.Length;
        }
    }
References System.buffers, System.count, System.IO.RandomAccess.fileOffset, System.handle, and System.IO.RandomAccess.WriteAtOffset().
Referenced by Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal(), and System.IO.RandomAccess.Write().