Terraria: System.IO.RandomAccess.ValidateInput
ValidateInput()
static void System.IO.RandomAccess.ValidateInput (SafeFileHandle handle, long fileOffset) inline static private
Definition at line 169 of file RandomAccess.cs.
    {
        if (handle == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.handle);
        }
        else if (handle.IsInvalid)
        {
            ThrowHelper.ThrowArgumentException_InvalidHandle("handle");
        }
        else if (!handle.CanSeek)
        {
            if (handle.IsClosed)
            {
                ThrowHelper.ThrowObjectDisposedException_FileClosed();
            }
            ThrowHelper.ThrowNotSupportedException_UnseekableStream();
        }
        else if (fileOffset < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException_NeedNonNegNum("fileOffset");
        }
    }
References System.IO.RandomAccess.fileOffset, System.handle, System.ThrowHelper.ThrowArgumentException_InvalidHandle(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowArgumentOutOfRangeException_NeedNonNegNum(), System.ThrowHelper.ThrowNotSupportedException_UnseekableStream(), and System.ThrowHelper.ThrowObjectDisposedException_FileClosed().
Referenced by System.IO.RandomAccess.GetLength(), System.IO.RandomAccess.Read(), System.IO.RandomAccess.Read(), System.IO.RandomAccess.ReadAsync(), System.IO.RandomAccess.ReadAsync(), System.IO.RandomAccess.Write(), System.IO.RandomAccess.Write(), System.IO.RandomAccess.WriteAsync(), and System.IO.RandomAccess.WriteAsync().