Terraria: System.IO.RandomAccess.WriteGatherAtOffsetAsync
WriteGatherAtOffsetAsync()
static ValueTask System.IO.RandomAccess.WriteGatherAtOffsetAsync (SafeFileHandle handle, IReadOnlyList< ReadOnlyMemory< byte > > buffers, long fileOffset, CancellationToken cancellationToken) inline static private
Definition at line 675 of file RandomAccess.cs.
    {
        if (!handle.IsAsync)
        {
            return ScheduleSyncWriteGatherAtOffsetAsync(handle, buffers, fileOffset, cancellationToken);
        }
        if (CanUseScatterGatherWindowsAPIs(handle) && TryPrepareScatterGatherBuffers(buffers, default(ReadOnlyMemoryHandler), out var handlesToDispose, out var segmentsPtr, out var totalBytes))
        {
            return WriteGatherAtOffsetSingleSyscallAsync(handle, handlesToDispose, segmentsPtr, fileOffset, totalBytes, cancellationToken);
        }
        return WriteGatherAtOffsetMultipleSyscallsAsync(handle, buffers, fileOffset, cancellationToken);
    }
References System.buffers, System.IO.RandomAccess.cancellationToken, System.IO.RandomAccess.CanUseScatterGatherWindowsAPIs(), System.IO.RandomAccess.fileOffset, System.handle, System.IO.RandomAccess.ScheduleSyncWriteGatherAtOffsetAsync(), System.IO.RandomAccess.WriteGatherAtOffsetMultipleSyscallsAsync(), and System.IO.RandomAccess.WriteGatherAtOffsetSingleSyscallAsync().
Referenced by System.IO.RandomAccess.WriteAsync().