Terraria: System.IO.RandomAccess.GetFileLength
GetFileLength()
static unsafe long System.IO.RandomAccess.GetFileLength (SafeFileHandle handle) inline static package
Definition at line 221 of file RandomAccess.cs.
    {
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Interop.Kernel32.FILE_STANDARD_INFO fILE_STANDARD_INFO);
        if (!Interop.Kernel32.GetFileInformationByHandleEx(handle, 1, &fILE_STANDARD_INFO, (uint)sizeof(Interop.Kernel32.FILE_STANDARD_INFO)))
        {
            throw Win32Marshal.GetExceptionForLastWin32Error(handle.Path);
        }
        return fILE_STANDARD_INFO.EndOfFile;
    }
References System.IO.Win32Marshal.GetExceptionForLastWin32Error(), Interop.Kernel32.GetFileInformationByHandleEx(), and System.handle.
Referenced by System.IO.RandomAccess.GetLength().