Terraria: System.IO.RandomAccess.WriteAtOffsetAsync
WriteAtOffsetAsync()
static ValueTask System.IO.RandomAccess.WriteAtOffsetAsync (SafeFileHandle handle, ReadOnlyMemory< byte > buffer, long fileOffset, CancellationToken cancellationToken, OSFileStreamStrategy strategy = null) inline static package
Definition at line 435 of file RandomAccess.cs.
    {
        if (handle.IsAsync)
        {
            var (overlappedValueTaskSource, num) = QueueAsyncWriteFile(handle, buffer, fileOffset, cancellationToken, strategy);
            if (overlappedValueTaskSource != null)
            {
                return new ValueTask(overlappedValueTaskSource, overlappedValueTaskSource.Version);
            }
            if (num == 0)
            {
                return ValueTask.CompletedTask;
            }
            return ValueTask.FromException(Win32Marshal.GetExceptionForWin32Error(num, handle.Path));
        }
        return ScheduleSyncWriteAtOffsetAsync(handle, buffer, fileOffset, cancellationToken, strategy);
    }
References System.IO.RandomAccess.buffer, System.IO.RandomAccess.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.CompletedTask, System.IO.RandomAccess.fileOffset, System.Threading.Tasks.ValueTask< TResult >.FromException(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.handle, System.IO.RandomAccess.ScheduleSyncWriteAtOffsetAsync(), and System.IO.RandomAccess.strategy.
Referenced by System.IO.File.WriteAllBytesAsync(), System.IO.Strategies.OSFileStreamStrategy.WriteAsync(), System.IO.RandomAccess.WriteAsync(), and System.IO.RandomAccess.WriteGatherAtOffsetMultipleSyscallsAsync().