Terraria: System.IO.RandomAccess.WriteFileGatherAsync
WriteFileGatherAsync()
static unsafe ValueTask System.IO.RandomAccess.WriteFileGatherAsync (SafeFileHandle handle, IntPtr segmentsPtr, int bytesToWrite, long fileOffset, CancellationToken cancellationToken) inline static private
Definition at line 700 of file RandomAccess.cs.
    {
        handle.EnsureThreadPoolBindingInitialized();
        SafeFileHandle.OverlappedValueTaskSource overlappedValueTaskSource = handle.GetOverlappedValueTaskSource();
        try
        {
            NativeOverlapped* lpOverlapped = overlappedValueTaskSource.PrepareForOperation(ReadOnlyMemory<byte>.Empty, fileOffset);
            if (Interop.Kernel32.WriteFileGather(handle, (long*)(void*)segmentsPtr, bytesToWrite, IntPtr.Zero, lpOverlapped) == 0)
            {
                int lastWin32ErrorAndDisposeHandleIfInvalid = FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(handle);
                if (lastWin32ErrorAndDisposeHandleIfInvalid != 997)
                {
                    overlappedValueTaskSource.Dispose();
                    return (lastWin32ErrorAndDisposeHandleIfInvalid == 232) ? ValueTask.CompletedTask : ValueTask.FromException(SafeFileHandle.OverlappedValueTaskSource.GetIOError(lastWin32ErrorAndDisposeHandleIfInvalid, null));
                }
                overlappedValueTaskSource.RegisterForCancellation(cancellationToken);
            }
        }
        catch
        {
            overlappedValueTaskSource.Dispose();
            throw;
        }
        overlappedValueTaskSource.FinishedScheduling();
        return new ValueTask(overlappedValueTaskSource, overlappedValueTaskSource.Version);
    }
References System.IO.RandomAccess.cancellationToken, System.IO.RandomAccess.fileOffset, System.Threading.Tasks.ValueTask< TResult >.FromException(), Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.GetIOError(), System.IO.Strategies.FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(), System.handle, Interop.Kernel32.WriteFileGather(), and System.IntPtr.Zero.
Referenced by System.IO.RandomAccess.WriteGatherAtOffsetSingleSyscallAsync().