Terraria: System.IO.RandomAccess.WriteGatherAtOffsetSingleSyscallAsync
WriteGatherAtOffsetSingleSyscallAsync()
static async ValueTask System.IO.RandomAccess.WriteGatherAtOffsetSingleSyscallAsync (SafeFileHandle handle, MemoryHandle[] handlesToDispose, IntPtr segmentsPtr, long fileOffset, int totalBytes, CancellationToken cancellationToken) inline static private
Definition at line 688 of file RandomAccess.cs.
    {
        try
        {
            await WriteFileGatherAsync(handle, segmentsPtr, totalBytes, fileOffset, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            CleanupScatterGatherBuffers(handlesToDispose, segmentsPtr);
        }
    }
References System.IO.RandomAccess.cancellationToken, System.IO.RandomAccess.CleanupScatterGatherBuffers(), System.IO.RandomAccess.fileOffset, System.handle, and System.IO.RandomAccess.WriteFileGatherAsync().
Referenced by System.IO.RandomAccess.WriteGatherAtOffsetAsync().