Terraria: System.Collections.Hashtable.Contains
Contains()
virtual bool System.Collections.Hashtable.Contains (object key) inline virtual inherited
Implements System.Collections.IDictionary.
Reimplemented in System.Collections.Hashtable.SyncHashtable.
Definition at line 719 of file Hashtable.cs.
    {
        return ContainsKey(key);
    }
References System.Collections.Hashtable.ContainsKey(), and System.key.
Referenced by System.Xml.XmlDocument.AddElementWithId(), System.Xml.Xsl.XsltOld.Compiler.AddScript(), System.Xml.Xsl.XsltOld.Stylesheet.AddSpace(), System.Xml.Serialization.XmlSerializationReader.AddTarget(), System.Xml.Serialization.XmlReflectionImporter.CheckAmbiguousChoice(), System.Xml.Schema.NamespaceList.CompareSetToOther(), System.Collections.DictionaryBase.Contains(), System.Collections.Specialized.HybridDictionary.Contains(), System.Collections.Specialized.OrderedDictionary.Contains(), System.Collections.Hashtable.SyncHashtable.Contains(), System.ComponentModel.LicenseManager.LicInfoHelperLicenseContext.Contains(), System.Net.HttpListener.ContainsPrefix(), System.CurrentSystemTimeZone.GetCachedDaylightChanges(), System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes(), System.Xml.Serialization.XmlSerializationReader.HandleUnreferencedObjects(), System.Xml.Schema.XmlSchemaInference.InferElement(), System.Xml.Xsl.XsltOld.InputScope.IsExcludedNamespace(), System.Xml.Xsl.XsltOld.InputScope.IsExtensionNamespace(), System.Xml.Serialization.XmlSerializationWriter.IsIdDefined(), System.Xml.Serialization.CodeIdentifiers.IsInUse(), System.Xml.Xsl.XsltOld.Compiler.IsNamespaceAlias(), System.Xml.Serialization.XmlSchemas.IsReference(), System.Collections.DictionaryBase.Remove(), System.Xml.XmlDocument.RemoveElementWithId(), System.Net.HttpListener.RemovePrefix(), System.Xml.Schema.XsdValidator.ValidateEndStartElement(), and System.Xml.Xsl.XsltOld.SequentialOutput.WriteStartElement().