Terraria: System.Collections.Hashtable.Add
Add()
virtual void System.Collections.Hashtable.Add (object key, object? value) inline virtual inherited
Implements System.Collections.IDictionary.
Definition at line 676 of file Hashtable.cs.
    {
        Insert(key, value, add: true);
    }
References System.Runtime.Serialization.Dictionary, System.Insert, System.key, and System.value.
Referenced by System.Collections.DictionaryBase.Add(), System.Collections.Hashtable.SyncHashtable.Add(), System.Collections.Specialized.HybridDictionary.Add(), System.Collections.Specialized.OrderedDictionary.Add(), System.Xml.Serialization.CodeIdentifiers.Add(), System.Collections.Specialized.StringDictionary.Add(), System.Xml.Serialization.SoapAttributeOverrides.Add(), System.Xml.Serialization.XmlSchemas.Add(), System.Xml.Schema.AllElementsContentValidator.AddElement(), System.Xml.XmlDocument.AddElementWithId(), System.Xml.Xsl.XsltArgumentList.AddExtensionObject(), System.Xml.Schema.DtdValidator.AddID(), System.Xml.Schema.XdrValidator.AddID(), System.Xml.Schema.XsdValidator.AddID(), System.Xml.XmlDocument.AddIdInfo(), System.Xml.Schema.SymbolsDictionary.AddName(), System.Xml.Schema.XmlSchemaCollection.AddNonThreadSafe(), System.Xml.Xsl.XsltArgumentList.AddParam(), System.Xml.Serialization.CodeIdentifiers.AddReserved(), System.Xml.Schema.XmlSchemaSet.AddSchemaToSet(), System.Runtime.Serialization.SurrogateSelector.AddSurrogate(), System.Xml.Serialization.XmlSerializationReader.AddTarget(), System.Xml.Schema.SymbolsDictionary.AddWildcard(), System.Collections.Specialized.NameObjectCollectionBase.BaseAdd(), System.Xml.Schema.Preprocessor.BuildRefNamespaces(), System.Xml.Schema.SchemaCollectionPreprocessor.BuildRefNamespaces(), System.Xml.Schema.ParticleContentValidator.BuildTransitionTable(), System.Collections.Specialized.HybridDictionary.ChangeOver(), System.Xml.Serialization.XmlReflectionImporter.CheckAmbiguousChoice(), System.Xml.Schema.XmlSchemaSet.CopyFromCompiledSet(), MS.Internal.Xml.Cache.XPathDocumentBuilder.CreateIdTables(), System.Xml.Xsl.XsltOld.HtmlAttributeProps.CreatePropsTable(), System.Xml.Xsl.XsltOld.HtmlElementProps.CreatePropsTable(), System.Xml.Serialization.SchemaGraph.Depends(), System.ComponentModel.Design.DesigntimeLicenseContextSerializer.Deserialize(), System.Xml.Xsl.XsltOld.XsltCompileContext.Document(), System.Xml.Serialization.XmlSerializationReader.EnsureCallbackTables(), System.Xml.Schema.Preprocessor.Execute(), System.Xml.Schema.SchemaCollectionPreprocessor.Execute(), System.Xml.Serialization.XmlSchemaExporter.ExportArrayMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportAttributeAccessor(), System.Xml.Serialization.XmlSchemaExporter.ExportDefaultValue(), System.Xml.Serialization.XmlSchemaExporter.ExportElement(), System.Xml.Serialization.XmlSchemaExporter.ExportElementAccessor(), System.Xml.Serialization.XmlSchemaExporter.ExportEnumMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportStructMapping(), System.Xml.Serialization.TypeScope.GetArrayTypeDesc(), System.CurrentSystemTimeZone.GetCachedDaylightChanges(), System.Xml.Schema.Preprocessor.GetChameleonSchema(), System.Xml.Xsl.Runtime.XmlQueryContext.GetDataSource(), System.Environment.GetEnvironmentVariables(), System.Environment.GetEnvironmentVariablesFromRegistry(), System.Xml.Serialization.XmlSerializationWriter.GetId(), System.Data.XSDSchema.HandleConstraint(), System.Xml.Serialization.XmlSchemaImporter.ImportChoiceGroup(), System.Xml.Serialization.XmlReflectionImporter.ImportSpecialMapping(), System.Xml.Serialization.TypeScope.ImportTypeDesc(), System.Xml.Schema.XmlSchemaInference.InferElement(), System.Collections.Specialized.OrderedDictionary.Insert(), System.Xml.Schema.NamespaceList.Intersection(), System.Xml.Schema.Preprocessor.LoadExternals(), System.Xml.Schema.SchemaCollectionPreprocessor.LoadExternals(), System.Xml.Serialization.XmlSchemas.Merge(), System.Text.RegularExpressions.RegexParser.NoteCaptureName(), System.Text.RegularExpressions.RegexParser.NoteCaptureSlot(), System.Xml.Schema.Compiler.Prepare(), System.Xml.Schema.Preprocessor.Preprocess(), System.Xml.Schema.XmlSchemaValidator.ProcessTokenizedType(), System.Collections.DictionaryBase.Remove(), System.Xml.Schema.XmlSchemaSet.RemoveRecursive(), System.Xml.Schema.XmlSchemaSet.Reprocess(), System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(), System.Xml.Schema.XmlSchemaValidator.ValidateElement(), System.Xml.Schema.Preprocessor.ValidateIdAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), System.Xml.Schema.DtdValidator.ValidateStartElement(), System.Xml.Schema.XdrValidator.ValidateStartElement(), System.Xml.Schema.XsdValidator.ValidateStartElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAddCollectionFixup(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteAssemblyInfo(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteDefaultIndexerInit(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteID(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteMemberInfo(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteMethodInfo(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteTypeInfo().