Terraria: System.Collections.Hashtable.Remove
Remove()
virtual void System.Collections.Hashtable.Remove (object key) inline virtual inherited
Implements System.Collections.IDictionary.
Reimplemented in System.Collections.Hashtable.SyncHashtable.
Definition at line 1028 of file Hashtable.cs.
    {
        if (key == null)
        {
            throw new ArgumentNullException("key", SR.ArgumentNull_Key);
        }
        uint seed;
        uint incr;
        uint num = InitHash(key, _buckets.Length, out seed, out incr);
        int num2 = 0;
        int num3 = (int)(seed % (uint)_buckets.Length);
        bucket bucket;
        do
        {
            bucket = _buckets[num3];
            if ((bucket.hash_coll & 0x7FFFFFFF) == num && KeyEquals(bucket.key, key))
            {
                _isWriterInProgress = true;
                _buckets[num3].hash_coll &= int.MinValue;
                if (_buckets[num3].hash_coll != 0)
                {
                    _buckets[num3].key = _buckets;
                }
                else
                {
                    _buckets[num3].key = null;
                }
                _buckets[num3].val = null;
                _count--;
                UpdateVersion();
                _isWriterInProgress = false;
                break;
            }
            num3 = (int)((num3 + incr) % (uint)_buckets.Length);
        }
        while (bucket.hash_coll < 0 && ++num2 < _buckets.Length);
    }
References System.Collections.Hashtable._buckets, System.Collections.Hashtable._count, System.Collections.Hashtable._isWriterInProgress, System.SR.ArgumentNull_Key, System.Runtime.Serialization.Dictionary, System.Collections.Hashtable.bucket.hash_coll, System.Collections.Hashtable.InitHash(), System.Collections.Hashtable.bucket.key, System.key, System.Collections.Hashtable.KeyEquals(), System.Collections.Hashtable.UpdateVersion(), and System.Collections.Hashtable.bucket.val.
Referenced by System.Collections.DictionaryBase.Add(), System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.Schema.XmlSchemaCollection.AddNonThreadSafe(), System.Xml.XmlDataDocument.AddPointer(), System.Collections.Specialized.NameObjectCollectionBase.BaseRemove(), System.Collections.Specialized.NameObjectCollectionBase.BaseRemoveAt(), System.Net.CookieContainer.BuildCookieCollectionFromDomainMatches(), System.Transactions.FinalizedObject.Dispose(), System.Net.CookieContainer.DomainTableCleanup(), System.Transactions.TransactionManager.FindOrCreatePromotedTransaction(), System.Transactions.TransactionManager.FindPromotedTransaction(), System.Data.DataViewSettingCollection.Remove(), System.Collections.DictionaryBase.Remove(), System.Collections.Specialized.HybridDictionary.Remove(), System.Collections.Specialized.OrderedDictionary.Remove(), System.Collections.Hashtable.SyncHashtable.Remove(), System.Xml.Serialization.CodeIdentifiers.Remove(), System.Collections.Specialized.StringDictionary.Remove(), System.Xml.Schema.XmlSchemaSet.Remove(), System.Collections.Specialized.OrderedDictionary.RemoveAt(), System.Xml.XmlDocument.RemoveElementWithId(), System.Xml.Xsl.XsltArgumentList.RemoveExtensionObject(), System.Xml.Schema.NamespaceList.RemoveNamespace(), System.Xml.Xsl.XsltArgumentList.RemoveParam(), System.Net.HttpListener.RemovePrefix(), System.Xml.Serialization.CodeIdentifiers.RemoveReserved(), System.Xml.Schema.XmlSchemaSet.RemoveSchemaFromCaches(), System.Runtime.Serialization.SurrogateSelector.RemoveSurrogate(), System.ComponentModel.PropertyDescriptor.RemoveValueChanged(), System.Xml.Schema.XmlSchemaSet.Reprocess(), and System.Xml.Serialization.XmlSerializationWriter.WriteEndElement().