Terraria: System.Collections.Hashtable.Clone
Clone()
virtual object System.Collections.Hashtable.Clone () inline virtual inherited
Implements System.ICloneable.
Reimplemented in System.Data.PropertyCollection, and System.Collections.Hashtable.SyncHashtable.
Definition at line 699 of file Hashtable.cs.
    {
        bucket[] buckets = _buckets;
        Hashtable hashtable = new Hashtable(_count, _keycomparer);
        hashtable._version = _version;
        hashtable._loadFactor = _loadFactor;
        hashtable._count = 0;
        int num = buckets.Length;
        while (num > 0)
        {
            num--;
            object key = buckets[num].key;
            if (key != null && key != buckets)
            {
                hashtable[key] = buckets[num].val;
            }
        }
        return hashtable;
    }
References System.Collections.Hashtable.Hashtable(), System.Collections.Hashtable._buckets, System.Collections.Hashtable._count, System.Collections.Hashtable._keycomparer, System.Collections.Hashtable._loadFactor, System.Collections.Hashtable._version, System.Runtime.Serialization.Dictionary, System.Collections.Hashtable.bucket.key, System.key, and System.Collections.Hashtable.bucket.val.
Referenced by System.Collections.Hashtable.SyncHashtable.Clone(), System.Xml.Schema.NamespaceList.Clone(), and System.Xml.Serialization.CodeIdentifiers.Clone().