Terraria: System.Collections.Hashtable.InitHash
InitHash()
uint System.Collections.Hashtable.InitHash (object key, int hashsize, out uint seed, out uint incr) inline private inherited
Definition at line 669 of file Hashtable.cs.
    {
        uint result = (seed = (uint)GetHash(key) & 0x7FFFFFFFu);
        incr = 1 + seed * 101 % (uint)(hashsize - 1);
        return result;
    }
References System.Runtime.Serialization.Dictionary, System.Collections.Hashtable.GetHash(), and System.key.
Referenced by System.Collections.Hashtable.ContainsKey(), System.Collections.Hashtable.Insert(), and System.Collections.Hashtable.Remove().