Terraria: System.Collections.Hashtable.Clear
Clear()
virtual void System.Collections.Hashtable.Clear () inline virtual inherited
Implements System.Collections.IDictionary.
Reimplemented in System.Collections.Hashtable.SyncHashtable.
Definition at line 681 of file Hashtable.cs.
    {
        if (_count != 0 || _occupancy != 0)
        {
            _isWriterInProgress = true;
            for (int i = 0; i < _buckets.Length; i++)
            {
                _buckets[i].hash_coll = 0;
                _buckets[i].key = null;
                _buckets[i].val = null;
            }
            _count = 0;
            _occupancy = 0;
            UpdateVersion();
            _isWriterInProgress = false;
        }
    }
References System.Collections.Hashtable._buckets, System.Collections.Hashtable._count, System.Collections.Hashtable._isWriterInProgress, System.Collections.Hashtable._occupancy, System.Collections.Hashtable.bucket.hash_coll, System.Collections.Hashtable.bucket.key, System.Collections.Hashtable.UpdateVersion(), and System.Collections.Hashtable.bucket.val.
Referenced by System.Xml.Schema.Preprocessor.BuildRefNamespaces(), System.Collections.DictionaryBase.Clear(), System.Collections.Specialized.HybridDictionary.Clear(), System.Collections.Specialized.OrderedDictionary.Clear(), System.Collections.Specialized.StringDictionary.Clear(), System.Collections.Hashtable.SyncHashtable.Clear(), System.Xml.Serialization.CodeIdentifiers.Clear(), System.Xml.Xsl.XsltArgumentList.Clear(), System.Xml.Schema.XmlSchemaValidator.ClearPSVI(), System.Xml.Serialization.XmlSchemas.Compile(), System.ComponentModel.Design.DesigntimeLicenseContextSerializer.Deserialize(), System.Xml.Schema.Preprocessor.Preprocess(), System.Net.HttpListener.RemoveAll(), System.Xml.Schema.XmlSchemaValidator.Reset(), System.Xml.Xsl.XsltOld.ActionFrame.ResetParams(), System.Xml.Schema.XmlSchemaValidator.ValidateElement(), System.Xml.Schema.DtdValidator.ValidateStartElement(), System.Xml.Schema.XdrValidator.ValidateStartElement(), and System.Xml.Schema.XsdValidator.ValidateStartElement().