Terraria: System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers
InternalGetSerializableMembers()
static FieldInfo[] System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type) inline static private
Definition at line 16 of file FormatterServices.cs.
    {
        if (type.IsInterface)
        {
            return Array.Empty<FieldInfo>();
        }
        if (!type.IsSerializable)
        {
            throw new SerializationException(System.SR.Format(System.SR.Serialization_NonSerType, type.FullName, type.Assembly.FullName));
        }
        FieldInfo[] array = GetSerializableFields(type);
        Type baseType = type.BaseType;
        if (baseType != null && baseType != typeof(object))
        {
            Type[] parentTypes;
            int parentTypeCount;
            bool parentTypes2 = GetParentTypes(baseType, out parentTypes, out parentTypeCount);
            if (parentTypeCount > 0)
            {
                List<FieldInfo> list = new List<FieldInfo>();
                for (int i = 0; i < parentTypeCount; i++)
                {
                    baseType = parentTypes[i];
                    if (!baseType.IsSerializable)
                    {
                        throw new SerializationException(System.SR.Format(System.SR.Serialization_NonSerType, baseType.FullName, baseType.Module.Assembly.FullName));
                    }
                    FieldInfo[] fields = baseType.GetFields(BindingFlags.Instance | BindingFlags.NonPublic);
                    string namePrefix = (parentTypes2 ? baseType.Name : baseType.FullName);
                    FieldInfo[] array2 = fields;
                    foreach (FieldInfo fieldInfo in array2)
                    {
                        if (!fieldInfo.IsNotSerialized)
{
                            list.Add(new SerializationFieldInfo(fieldInfo, namePrefix));
                        }
                    }
                }
                if (list != null && list.Count > 0)
                {
                    FieldInfo[] array3 = new FieldInfo[list.Count + array.Length];
                    Array.Copy(array, array3, array.Length);
                    list.CopyTo(array3, array.Length);
                    array = array3;
                }
            }
        }
        return array;
    }
References System.array, System.Array.Copy(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.FormatterServices.GetParentTypes(), System.Runtime.Serialization.FormatterServices.GetSerializableFields(), System.list, System.SR.Serialization_NonSerType, and System.type.
Referenced by System.Runtime.Serialization.FormatterServices.GetSerializableMembers().