Terraria: System.Collections.Hashtable.GetEnumerator
GetEnumerator() [1/2]
IEnumerator IEnumerable. System.Collections.Hashtable.GetEnumerator () inline private inherited
Implements System.Collections.IDictionary.
Definition at line 899 of file Hashtable.cs.
    {
        return new HashtableEnumerator(this, 3);
    }
Referenced by System.Text.RegularExpressions.RegexParser.AssignNameSlots(), System.Data.PropertyCollection.Clone(), System.Net.CookieContainer.DomainTableCleanup(), System.Net.CookieContainer.GetAllCookies(), System.Collections.DictionaryBase.GetEnumerator(), System.Collections.Specialized.HybridDictionary.GetEnumerator(), System.Collections.Specialized.StringDictionary.GetEnumerator(), System.Collections.Hashtable.SyncHashtable.GetEnumerator(), System.Text.RegularExpressions.Regex.GetGroupNumbers(), System.ComponentModel.ReflectTypeDescriptionProvider.GetIntrinsicTypeEditor(), System.Xml.Xsl.XsltOld.Stylesheet.ProcessTemplates(), and System.Xml.Xsl.XsltOld.Stylesheet.ReplaceNamespaceAlias().