Terraria: System.Xml.Serialization.XmlAttributes.XmlAttributes
XmlAttributes() [2/2]
System.Xml.Serialization.XmlAttributes.XmlAttributes (ICustomAttributeProvider provider) inline
Definition at line 225 of file XmlAttributes.cs.
    {
        object[] customAttributes = provider.GetCustomAttributes(inherit: false);
        XmlAnyElementAttribute xmlAnyElementAttribute = null;
        for (int i = 0; i < customAttributes.Length; i++)
        {
            if (customAttributes[i] is XmlIgnoreAttribute || customAttributes[i] is ObsoleteAttribute)
            {
                _xmlIgnore = true;
                break;
            }
            if (customAttributes[i] is XmlElementAttribute)
            {
                _xmlElements.Add((XmlElementAttribute)customAttributes[i]);
            }
            else if (customAttributes[i] is XmlArrayItemAttribute)
            {
                _xmlArrayItems.Add((XmlArrayItemAttribute)customAttributes[i]);
            }
            else if (customAttributes[i] is XmlAnyElementAttribute)
            {
                XmlAnyElementAttribute xmlAnyElementAttribute2 = (XmlAnyElementAttribute)customAttributes[i];
                if ((xmlAnyElementAttribute2.Name == null || xmlAnyElementAttribute2.Name.Length == 0) && xmlAnyElementAttribute2.GetNamespaceSpecified() && xmlAnyElementAttribute2.Namespace == null)
                {
                    xmlAnyElementAttribute = xmlAnyElementAttribute2;
                }
                else
                {
                    _xmlAnyElements.Add((XmlAnyElementAttribute)customAttributes[i]);
                }
            }
            else if (customAttributes[i] is DefaultValueAttribute)
            {
                _xmlDefaultValue = ((DefaultValueAttribute)customAttributes[i]).Value;
            }
            else if (customAttributes[i] is XmlAttributeAttribute)
            {
                _xmlAttribute = (XmlAttributeAttribute)customAttributes[i];
            }
            else if (customAttributes[i] is XmlArrayAttribute)
            {
                _xmlArray = (XmlArrayAttribute)customAttributes[i];
            }
            else if (customAttributes[i] is XmlTextAttribute)
            {
                _xmlText = (XmlTextAttribute)customAttributes[i];
            }
            else if (customAttributes[i] is XmlEnumAttribute)
            {
                _xmlEnum = (XmlEnumAttribute)customAttributes[i];
            }
            else if (customAttributes[i] is XmlRootAttribute)
            {
                _xmlRoot = (XmlRootAttribute)customAttributes[i];
            }
            else if (customAttributes[i] is XmlTypeAttribute)
            {
                _xmlType = (XmlTypeAttribute)customAttributes[i];
            }
            else if (customAttributes[i] is XmlAnyAttributeAttribute)
            {
                _xmlAnyAttribute = (XmlAnyAttributeAttribute)customAttributes[i];
            }
            else if (customAttributes[i] is XmlChoiceIdentifierAttribute)
            {
                _xmlChoiceIdentifier = (XmlChoiceIdentifierAttribute)customAttributes[i];
            }
            else if (customAttributes[i] is XmlNamespaceDeclarationsAttribute)
            {
                _xmlns = true;
            }
        }
        if (_xmlIgnore)
        {
            _xmlElements.Clear();
            _xmlArrayItems.Clear();
            _xmlAnyElements.Clear();
            _xmlDefaultValue = null;
            _xmlAttribute = null;
            _xmlArray = null;
            _xmlText = null;
            _xmlEnum = null;
            _xmlType = null;
            _xmlAnyAttribute = null;
            _xmlChoiceIdentifier = null;
            _xmlns = false;
        }
        else if (xmlAnyElementAttribute != null)
        {
            _xmlAnyElements.Add(xmlAnyElementAttribute);
        }
    }
References System.Xml.Serialization.XmlAttributes._xmlAnyAttribute, System.Xml.Serialization.XmlAttributes._xmlAnyElements, System.Xml.Serialization.XmlAttributes._xmlArray, System.Xml.Serialization.XmlAttributes._xmlArrayItems, System.Xml.Serialization.XmlAttributes._xmlAttribute, System.Xml.Serialization.XmlAttributes._xmlChoiceIdentifier, System.Xml.Serialization.XmlAttributes._xmlDefaultValue, System.Xml.Serialization.XmlAttributes._xmlElements, System.Xml.Serialization.XmlAttributes._xmlEnum, System.Xml.Serialization.XmlAttributes._xmlIgnore, System.Xml.Serialization.XmlAttributes._xmlns, System.Xml.Serialization.XmlAttributes._xmlRoot, System.Xml.Serialization.XmlAttributes._xmlText, System.Xml.Serialization.XmlAttributes._xmlType, System.Xml.Serialization.XmlAnyElementAttributes.Add(), System.Xml.Serialization.XmlArrayItemAttributes.Add(), System.Xml.Serialization.XmlElementAttributes.Add(), System.Collections.CollectionBase.Clear(), and System.Xml.Dictionary.