Terraria: System.Xml.Xsl.Qil.QilPatternFactory.Content
Content()
QilNode System.Xml.Xsl.Qil.QilPatternFactory.Content (QilNode context) inline inherited
Definition at line 494 of file QilPatternFactory.cs.
    {
        return _f.Content(context);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._f, and System.Xml.Xsl.Qil.QilFactory.Content().
Referenced by System.Xml.Xsl.XPath.XPathBuilder.BuildAxis(), System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildPredicates(), and System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction().