Terraria: System.Xml.Xsl.Qil.QilPatternFactory.StrConcat
StrConcat() [3/3]
QilNode System.Xml.Xsl.Qil.QilPatternFactory.StrConcat (QilNode values) inline inherited
Definition at line 368 of file QilPatternFactory.cs.
    {
        if (!_debug && values.XmlType.IsSingleton)
        {
            return values;
        }
        return _f.StrConcat(values);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._debug, System.Xml.Xsl.Qil.QilPatternFactory._f, System.Xml.Xsl.Qil.QilFactory.StrConcat(), and System.values.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileGenerateId(), System.Xml.Xsl.Xslt.QilGenerator.CompileSingleDocument(), System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt(), System.Xml.Xsl.XPath.XPathBuilder.Function(), System.Xml.Xsl.XPath.XPathBuilder.LocalNameOfFirstNode(), System.Xml.Xsl.XPath.XPathBuilder.NameOf(), System.Xml.Xsl.XPath.XPathBuilder.NameOfFirstNode(), System.Xml.Xsl.XPath.XPathBuilder.NamespaceOfFirstNode(), and System.Xml.Xsl.Xslt.QilStrConcatenator.ToQil().