Terraria: System.Xml.Xsl.Qil.QilPatternFactory.Boolean
Boolean()
QilNode System.Xml.Xsl.Qil.QilPatternFactory.Boolean (bool b) inline inherited
Definition at line 176 of file QilPatternFactory.cs.
    {
        if (!b)
        {
            return False();
        }
        return True();
    }
References System.Xml.Xsl.Qil.QilPatternFactory.False(), and System.Xml.Xsl.Qil.QilPatternFactory.True().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileElementAvailable(), System.Xml.Xsl.Xslt.QilGenerator.CompileFunctionAvailable(), System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction(), System.Xml.Xsl.Xslt.QilGenerator.PrecompileProtoTemplatesHeaders(), and System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().