Terraria: System.Xml.Xsl.Qil.QilPatternFactory.Not
Not()
QilNode System.Xml.Xsl.Qil.QilPatternFactory.Not (QilNode child) inline inherited
Definition at line 225 of file QilPatternFactory.cs.
    {
        if (!_debug)
        {
            switch (child.NodeType)
            {
            case QilNodeType.True:
                return _f.False();
            case QilNodeType.False:
                return _f.True();
            case QilNodeType.Not:
                return ((QilUnary)child).Child;
            }
        }
        return _f.Not(child);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._debug, System.Xml.Xsl.Qil.QilPatternFactory._f, System.Xml.Xsl.Qil.QilFactory.False(), System.Xml.Xsl.Qil.QilNode.NodeType, System.Xml.Xsl.Qil.QilFactory.Not(), and System.Xml.Xsl.Qil.QilFactory.True().
Referenced by System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildPredicates(), System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndNodeSet(), System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndValue(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnKey(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeys(), System.Xml.Xsl.XPath.XPathBuilder.Function(), System.Xml.Xsl.Xslt.XPathPatternBuilder.Function(), System.Xml.Xsl.Xslt.XPathPatternBuilder.JoinStep(), and System.Xml.Xsl.Xslt.QilGenerator.PlaceMarkerAny().