Terraria: System.Xml.Xsl.Qil.QilPatternFactory.QName
QName() [3/3]
QilName System.Xml.Xsl.Qil.QilPatternFactory.QName (string local, string uri, string prefix) inline inherited
Definition at line 35 of file QilPatternFactory.cs.
    {
        return _f.LiteralQName(local, uri, prefix);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._f, System.Xml.Xsl.Qil.QilFactory.LiteralQName(), and System.prefix.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.QilGenerator(), System.Xml.Xsl.XPath.XPathBuilder.BuildAxisFilter(), System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildAxisFilter(), System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), System.Xml.Xsl.Xslt.QilGenerator.CompileAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate(), System.Xml.Xsl.Xslt.QilGenerator.CompileElement(), System.Xml.Xsl.Xslt.QilGenerator.CompileElementAvailable(), System.Xml.Xsl.Xslt.QilGenerator.CompileFormatNumber(), System.Xml.Xsl.Xslt.QilGenerator.CompileFunctionAvailable(), System.Xml.Xsl.Xslt.QilGenerator.CompileSingleKey(), System.Xml.Xsl.Xslt.QilGenerator.CompileSystemProperty(), System.Xml.Xsl.Xslt.QilGenerator.GetNsVar(), and System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().