Terraria: System.Xml.Xsl.Qil.QilPatternFactory.Loop
Loop()
QilNode System.Xml.Xsl.Qil.QilPatternFactory.Loop (QilIterator variable, QilNode body) inline inherited
Definition at line 442 of file QilPatternFactory.cs.
    {
        if (!_debug && body == variable.Binding)
        {
            return body;
        }
        return _f.Loop(variable, body);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._debug, System.Xml.Xsl.Qil.QilPatternFactory._f, and System.Xml.Xsl.Qil.QilFactory.Loop().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.AddDebugVariable(), System.Xml.Xsl.XPath.XPathBuilder.BuildOnePredicate(), System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildPredicates(), System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndNodeSet(), System.Xml.Xsl.Xslt.QilGenerator.CompileCopyOf(), System.Xml.Xsl.Xslt.QilGenerator.CompileDataTypeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnKey(), System.Xml.Xsl.Xslt.QilGenerator.CompileFormatNumber(), System.Xml.Xsl.Xslt.QilGenerator.CompileGenerateId(), System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSeparatorAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSizeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeys(), System.Xml.Xsl.Xslt.QilGenerator.CompileLangAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileLetterValueAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileMatchPattern(), System.Xml.Xsl.Xslt.QilGenerator.CompileMessage(), System.Xml.Xsl.Xslt.QilGenerator.CompileOrderAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileSingleDocument(), System.Xml.Xsl.Xslt.QilGenerator.CompileSingleKey(), System.Xml.Xsl.Xslt.QilGenerator.CompileSingleKey(), System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.FinishVariables(), System.Xml.Xsl.Xslt.InvokeGenerator.GenerateInvoke(), System.Xml.Xsl.Xslt.QilGenerator.InvokeOnCurrentNodeChanged(), System.Xml.Xsl.XPath.XPathBuilder.JoinStep(), System.Xml.Xsl.XPath.XPathBuilder.LocalNameOfFirstNode(), System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatternsWhosePriorityGreater(), System.Xml.Xsl.XPath.XPathBuilder.NameOf(), System.Xml.Xsl.XPath.XPathBuilder.NameOfFirstNode(), System.Xml.Xsl.XPath.XPathBuilder.NamespaceOfFirstNode(), System.Xml.Xsl.Xslt.QilGenerator.PlaceMarker(), System.Xml.Xsl.Xslt.QilGenerator.PlaceMarkerAny(), System.Xml.Xsl.XPath.XPathBuilder.PredicateToBoolean(), System.Xml.Xsl.XPath.XPathBuilder.Sum(), and System.Xml.Xsl.Xslt.KeyMatchBuilder.PathConvertor.VisitLoop().