Terraria: System.Xml.Xsl.Qil.QilPatternFactory.Conditional
Conditional()
QilNode System.Xml.Xsl.Qil.QilPatternFactory.Conditional (QilNode condition, QilNode trueBranch, QilNode falseBranch) inline inherited
Definition at line 242 of file QilPatternFactory.cs.
    {
        if (!_debug)
        {
            switch (condition.NodeType)
            {
            case QilNodeType.True:
                return trueBranch;
            case QilNodeType.False:
                return falseBranch;
            case QilNodeType.Not:
                return Conditional(((QilUnary)condition).Child, falseBranch, trueBranch);
            }
        }
        return _f.Conditional(condition, trueBranch, falseBranch);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._debug, System.Xml.Xsl.Qil.QilPatternFactory._f, System.Xml.Xsl.Qil.QilFactory.Conditional(), System.Xml.Xsl.Qil.Conditional, System.Xml.Dictionary, and System.Xml.Xsl.Qil.QilNode.NodeType.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileCopyOf(), System.Xml.Xsl.Xslt.QilGenerator.CompileDataTypeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnKey(), System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSeparatorAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSizeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileLangAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileLetterValueAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileOrderAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileWhen(), System.Xml.Xsl.Xslt.QilGenerator.CreateGeneralKeyFunction(), System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction(), System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns(), System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns(), System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns(), System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatternsWhosePriorityGreater(), System.Xml.Xsl.XPath.XPathBuilder.NameOf(), System.Xml.Xsl.Xslt.QilGenerator.PlaceMarkerAny(), and System.Xml.Xsl.XPath.XPathBuilder.PredicateToBoolean().