Terraria: Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw
Draw()
void Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw (ref ParticleRendererSettings settings, SpriteBatch spritebatch) inline
Implements Terraria.Graphics.Renderers.IParticle.
Definition at line 78 of file LittleFlyingCritterParticle.cs.
    {
        Vector2 vector = settings.AnchorPosition + _localPosition;
        if (vector.X < -10f || vector.X > (float)(Main.screenWidth + 10) || vector.Y < -10f || vector.Y > (float)(Main.screenHeight + 10))
        {
            ShouldBeRemovedFromRenderer = true;
            return;
        }
        Texture2D value = TextureAssets.Extra[262].Value;
        int frameY = _lifeTimeCounted % 6 / 3;
        Rectangle value2 = value.Frame(1, 2, 0, frameY);
        Vector2 origin = new Vector2((!(_velocity.X > 0f)) ? 1 : 3, 3f);
        float num = Utils.Remap(_lifeTimeCounted, 0f, 90f, 0f, 1f) * Utils.Remap(_lifeTimeCounted, _lifeTimeTotal - 90, _lifeTimeTotal, 1f, 0f);
        spritebatch.Draw(value, settings.AnchorPosition + _localPosition, value2, Lighting.GetColor(_localPosition.ToTileCoordinates()) * num, 0f, origin, 1f, (_velocity.X > 0f) ? SpriteEffects.FlipHorizontally : SpriteEffects.None, 0f);
    }
References Terraria.Graphics.Renderers.LittleFlyingCritterParticle._lifeTimeCounted, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._lifeTimeTotal, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._localPosition, Terraria.Graphics.Renderers.LittleFlyingCritterParticle._velocity, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Lighting.GetColor(), Terraria.Utils.Remap(), Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Graphics.Renderers.LittleFlyingCritterParticle.ShouldBeRemovedFromRenderer, System.value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.