Terraria: System.Xml.Xsl.Qil.QilPatternFactory.DocOrderDistinct
DocOrderDistinct()
QilNode System.Xml.Xsl.Qil.QilPatternFactory.DocOrderDistinct (QilNode collection) inline inherited
Definition at line 470 of file QilPatternFactory.cs.
    {
        if (collection.NodeType == QilNodeType.DocOrderDistinct)
        {
            return collection;
        }
        return _f.DocOrderDistinct(collection);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._f, System.collection, and System.Xml.Xsl.Qil.QilFactory.DocOrderDistinct().
Referenced by System.Xml.Xsl.XPath.XPathBuilder.BuildOnePredicate(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnKey(), System.Xml.Xsl.XPath.XPathBuilder.EndBuild(), System.Xml.Xsl.XPath.XPathBuilder.Function(), System.Xml.Xsl.XPath.XPathBuilder.JoinStep(), and System.Xml.Xsl.Xslt.QilGenerator.PlaceMarker().