Terraria: System.Xml.Xsl.Qil.QilPatternFactory.For
For()
QilIterator System.Xml.Xsl.Qil.QilPatternFactory.For (QilNode binding) inline inherited
Definition at line 141 of file QilPatternFactory.cs.
    {
        return _f.For(binding);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._f, and System.Xml.Xsl.Qil.QilFactory.For().
Referenced by System.Xml.Xsl.Xslt.XPathPatternBuilder.Axis(), System.Xml.Xsl.XPath.XPathBuilder.BuildAxisFilter(), System.Xml.Xsl.XPath.XPathBuilder.BuildOnePredicate(), System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildPredicates(), System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndNodeSet(), System.Xml.Xsl.XPath.XPathBuilder.CompareNodeSetAndValue(), System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), System.Xml.Xsl.Xslt.QilGenerator.CompileCopyOf(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnKey(), System.Xml.Xsl.Xslt.QilGenerator.CompileForEach(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeys(), System.Xml.Xsl.Xslt.QilGenerator.CompileMatchPattern(), System.Xml.Xsl.Xslt.XPathPatternBuilder.Function(), System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction(), System.Xml.Xsl.XPath.XPathBuilder.JoinStep(), System.Xml.Xsl.Xslt.QilGenerator.PlaceMarker(), System.Xml.Xsl.Xslt.QilGenerator.PlaceMarkerAny(), System.Xml.Xsl.Xslt.LoopFocus.Sort(), System.Xml.Xsl.XPath.XPathBuilder.Sum(), and System.Xml.Xsl.Xslt.KeyMatchBuilder.PathConvertor.VisitLoop().