Terraria: System.Xml.Xsl.Qil.QilPatternFactory.Nop
Nop()
QilNode System.Xml.Xsl.Qil.QilPatternFactory.Nop (QilNode child) inline inherited
Definition at line 126 of file QilPatternFactory.cs.
    {
        return _f.Nop(child);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._f, and System.Xml.Xsl.Qil.QilFactory.Nop().
Referenced by System.Xml.Xsl.Xslt.XPathPatternBuilder.Axis(), System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeyUse(), System.Xml.Xsl.Xslt.QilGenerator.CompileNop(), System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpression(), System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpressionWithinAvt(), and System.Xml.Xsl.Xslt.QilGenerator.WrapLoopBody().