Terraria: System.Xml.Xsl.Qil.QilPatternFactory.Parameter
Parameter() [2/2]
QilParameter System.Xml.Xsl.Qil.QilPatternFactory.Parameter (XmlQueryType t) inline inherited
Definition at line 151 of file QilPatternFactory.cs.
    {
        return _f.Parameter(t);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._f, and System.Xml.Xsl.Qil.QilFactory.Parameter().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileKeys(), System.Xml.Xsl.Xslt.QilGenerator.CreateGeneralKeyFunction(), System.Xml.Xsl.Xslt.QilGenerator.CreateGlobalVarPar(), System.Xml.Xsl.Xslt.QilGenerator.CreateXslParam(), System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction(), and System.Xml.Xsl.Xslt.QilGenerator.PrecompileProtoTemplatesHeaders().