Terraria: System.Xml.Xsl.Qil.QilPatternFactory.Choice
Choice()
QilNode System.Xml.Xsl.Qil.QilPatternFactory.Choice (QilNode expr, QilList branches) inline inherited
Definition at line 259 of file QilPatternFactory.cs.
    {
        if (!_debug)
        {
            switch (branches.Count)
            {
            case 1:
                return _f.Loop(_f.Let(expr), branches[0]);
            case 2:
                return _f.Conditional(_f.Eq(expr, _f.LiteralInt32(0)), branches[0], branches[1]);
            }
        }
        return _f.Choice(expr, branches);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._debug, System.Xml.Xsl.Qil.QilPatternFactory._f, System.Xml.Xsl.Qil.QilFactory.Choice(), System.Xml.Xsl.Qil.QilFactory.Conditional(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Qil.QilFactory.Eq(), System.Xml.Xsl.Qil.QilFactory.Let(), System.Xml.Xsl.Qil.QilFactory.LiteralInt32(), and System.Xml.Xsl.Qil.QilFactory.Loop().
Referenced by System.Xml.Xsl.Xslt.MatcherBuilder.BuildMatcher().