Terraria: System.Xml.Xsl.Qil.QilPatternFactory.String
String()
QilLiteral System.Xml.Xsl.Qil.QilPatternFactory.String (string val) inline inherited
Definition at line 20 of file QilPatternFactory.cs.
    {
        return _f.LiteralString(val);
    }
References System.Xml.Xsl.Qil.QilPatternFactory._f, and System.Xml.Xsl.Qil.QilFactory.LiteralString().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.AddNsDecl(), System.Xml.Xsl.XPath.XPathBuilder.BuildAxisFilter(), System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildAxisFilter(), System.Xml.Xsl.Xslt.QilGenerator.BuildDebuggerNamespaces(), System.Xml.Xsl.Xslt.QilGenerator.CompileDataTypeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileError(), System.Xml.Xsl.Xslt.QilGenerator.CompileFormatNumber(), System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSeparatorAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeyMatch(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeyUse(), System.Xml.Xsl.Xslt.QilGenerator.CompileLangAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileLangToLcid(), System.Xml.Xsl.Xslt.QilGenerator.CompileLetterValueAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileMatchPattern(), System.Xml.Xsl.Xslt.QilGenerator.CompileMessage(), System.Xml.Xsl.Xslt.QilGenerator.CompileNodeSetExpression(), System.Xml.Xsl.Xslt.QilGenerator.CompileNumberPattern(), System.Xml.Xsl.Xslt.QilGenerator.CompileOrderAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileSingleDocument(), System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt(), System.Xml.Xsl.Xslt.QilGenerator.CompileSystemProperty(), System.Xml.Xsl.Xslt.QilGenerator.CompileText(), System.Xml.Xsl.Xslt.QilGenerator.CompileTextAvt(), System.Xml.Xsl.Xslt.QilGenerator.CompileVarParValue(), System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpression(), System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpressionWithinAvt(), System.Xml.Xsl.Xslt.QilGenerator.EXslObjectType(), System.Xml.Xsl.Xslt.QilGenerator.ExtractText(), System.Xml.Xsl.Xslt.QilStrConcatenator.FlushBuilder(), System.Xml.Xsl.XPath.XPathBuilder.NameOf(), System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction(), System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameDynamic(), System.Xml.Xsl.XPath.XPathBuilder.String(), System.Xml.Xsl.Xslt.XPathPatternBuilder.String(), and System.Xml.Xsl.Xslt.QilStrConcatenator.ToQil().