Terraria: System.Xml.Xsl.Runtime.XsltConvert.ToNode
ToNode() [2/2]
static XPathNavigator System.Xml.Xsl.Runtime.XsltConvert.ToNode (XPathItem item) inline static
Definition at line 138 of file XsltConvert.cs.
    {
        if (!item.IsNode)
        {
            XPathDocument xPathDocument = new XPathDocument();
            XmlRawWriter xmlRawWriter = xPathDocument.LoadFromWriter(XPathDocument.LoadFlags.AtomizeNames, string.Empty);
            xmlRawWriter.WriteString(ToString(item));
            xmlRawWriter.Close();
            return xPathDocument.CreateNavigator();
        }
        if (item is RtfNavigator rtfNavigator)
        {
            return rtfNavigator.ToNavigator();
        }
        return (XPathNavigator)item;
    }
References System.item, and System.ToString.
Referenced by System.Xml.Xsl.Runtime.XmlQueryContext.InvokeXsltLateBoundFunction(), System.Xml.Xsl.Runtime.XsltConvert.ToNode(), System.Xml.Xsl.Runtime.XsltConvert.ToNodeSet(), and System.Xml.Xsl.Runtime.XsltConvert.ToNodeSet().