Terraria: System.Xml.Xsl.Runtime.XsltConvert.ConvertToType
ConvertToType()
static XmlAtomicValue System.Xml.Xsl.Runtime.XsltConvert.ConvertToType (XmlAtomicValue value, XmlQueryType destinationType) inline static package
Definition at line 241 of file XsltConvert.cs.
    {
        switch (destinationType.TypeCode)
        {
        case XmlTypeCode.Boolean:
        {
            XmlTypeCode typeCode = value.XmlType.TypeCode;
            if ((uint)(typeCode - 12) <= 1u || typeCode == XmlTypeCode.Double)
            {
                return new XmlAtomicValue(destinationType.SchemaType, ToBoolean(value));
            }
            break;
        }
        case XmlTypeCode.DateTime:
            if (value.XmlType.TypeCode == XmlTypeCode.String)
            {
                return new XmlAtomicValue(destinationType.SchemaType, ToDateTime(value.Value));
            }
            break;
        case XmlTypeCode.Decimal:
            if (value.XmlType.TypeCode == XmlTypeCode.Double)
            {
                return new XmlAtomicValue(destinationType.SchemaType, ToDecimal(value.ValueAsDouble));
            }
            break;
        case XmlTypeCode.Double:
            switch (value.XmlType.TypeCode)
            {
            case XmlTypeCode.String:
            case XmlTypeCode.Boolean:
            case XmlTypeCode.Double:
                return new XmlAtomicValue(destinationType.SchemaType, ToDouble(value));
            case XmlTypeCode.Decimal:
                return new XmlAtomicValue(destinationType.SchemaType, ToDouble((decimal)value.ValueAs(DecimalType, null)));
            case XmlTypeCode.Long:
            case XmlTypeCode.Int:
                return new XmlAtomicValue(destinationType.SchemaType, ToDouble(value.ValueAsLong));
            }
            break;
        case XmlTypeCode.Long:
        case XmlTypeCode.Int:
            if (value.XmlType.TypeCode == XmlTypeCode.Double)
            {
                return new XmlAtomicValue(destinationType.SchemaType, ToLong(value.ValueAsDouble));
            }
            break;
        case XmlTypeCode.String:
            switch (value.XmlType.TypeCode)
            {
            case XmlTypeCode.String:
            case XmlTypeCode.Boolean:
            case XmlTypeCode.Double:
                return new XmlAtomicValue(destinationType.SchemaType, ToString(value));
            case XmlTypeCode.DateTime:
                return new XmlAtomicValue(destinationType.SchemaType, ToString(value.ValueAsDateTime));
            }
            break;
        }
        return value;
    }
References System.Xml.Xsl.Runtime.XsltConvert.DecimalType, System.Xml.Xsl.Runtime.XsltConvert.ToBoolean(), System.Xml.Xsl.Runtime.XsltConvert.ToDateTime(), System.Xml.Xsl.Runtime.XsltConvert.ToDecimal(), System.Xml.Xsl.Runtime.XsltConvert.ToDouble(), System.Xml.Xsl.Runtime.XsltConvert.ToLong(), System.ToString, and System.value.
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldXsltConvert().