Terraria: System.Xml.Xsl.Runtime.XsltConvert.ToBoolean
ToBoolean() [2/2]
static bool System.Xml.Xsl.Runtime.XsltConvert.ToBoolean (XPathItem item) inline static
Definition at line 70 of file XsltConvert.cs.
    {
        if (item.IsNode)
        {
            return true;
        }
        Type valueType = item.ValueType;
        if (valueType == StringType)
        {
            return item.Value.Length != 0;
        }
        if (valueType == DoubleType)
        {
            double valueAsDouble = item.ValueAsDouble;
            if (!(valueAsDouble < 0.0))
            {
                return 0.0 < valueAsDouble;
            }
            return true;
        }
        return item.ValueAsBoolean;
    }
References System.Xml.Dictionary, System.Xml.Xsl.Runtime.XsltConvert.DoubleType, System.item, and System.Xml.Xsl.Runtime.XsltConvert.StringType.
Referenced by System.Xml.Xsl.Runtime.XsltLibrary.CompareNodeSetAndValue(), System.Xml.Xsl.Runtime.XsltLibrary.CompareValues(), System.Xml.Xsl.Runtime.XsltConvert.ConvertToType(), System.Xml.Xsl.Runtime.XmlQueryContext.InvokeXsltLateBoundFunction(), and System.Xml.Xsl.Runtime.XsltConvert.ToBoolean().