Terraria: System.IO.Compression.ZipFileUtils.EntryFromPath
EntryFromPath()
static string System.IO.Compression.ZipFileUtils.EntryFromPath (string entry, int offset, int length, ref char[] buffer, bool appendPathSeparator = false) inline static
Definition at line 8 of file ZipFileUtils.cs.
    {
        while (length > 0 && (entry[offset] == Path.DirectorySeparatorChar || entry[offset] == Path.AltDirectorySeparatorChar))
        {
            offset++;
            length--;
        }
        if (length == 0)
        {
            if (!appendPathSeparator)
            {
                return string.Empty;
            }
            return "/";
        }
        int num = (appendPathSeparator ? (length + 1) : length);
        EnsureCapacity(ref buffer, num);
        entry.CopyTo(offset, buffer, 0, length);
        for (int i = 0; i < length; i++)
        {
            char c = buffer[i];
            if (c == Path.DirectorySeparatorChar || c == Path.AltDirectorySeparatorChar)
            {
                buffer[i] = '/';
            }
        }
        if (appendPathSeparator)
        {
            buffer[length] = '/';
        }
        return new string(buffer, 0, num);
    }
References System.IO.Path.AltDirectorySeparatorChar, System.buffer, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.IO.Path.DirectorySeparatorChar, System.IO.Compression.ZipFileUtils.EnsureCapacity(), System.length, and System.offset.
Referenced by System.IO.Compression.ZipFile.DoCreateFromDirectory().