Terraria: ChatInitializer.PrepareAliases
PrepareAliases()
static void ChatInitializer.PrepareAliases () inline static
     {
         ChatManager.Commands.ClearAliases();
         for (int i = 0; i < EmoteID.Count; i++)
         {
             string name = EmoteID.Search.GetName(i);
             string key = "EmojiCommand." + name;
             ChatManager.Commands.AddAlias(Language.GetText(key), NetworkText.FromFormattable("{0} {1}", Language.GetText("ChatCommand.Emoji_1"), Language.GetText("EmojiName." + name)));
         }
     }
References ChatCommandProcessor.AddAlias(), ChatCommandProcessor.ClearAliases(), ChatManager.Commands, EmoteID.Count, NetworkText.FromFormattable(), IdDictionary.GetName(), Language.GetText(), and EmoteID.Search.
Referenced by Load(), LanguageManager.LoadLanguage(), and LanguageManager.UseSources().