Terraria: Terraria.Social.Base.WorkshopIssueReporter.AddReport
AddReport()
void Terraria.Social.Base.WorkshopIssueReporter.AddReport (string reportText) inline private
    {
        IssueReport item = new IssueReport(reportText);
        _reports.Add(item);
        while (_reports.Count > _maxReports)
        {
            _reports.RemoveAt(0);
        }
    }
References Terraria.Social.Base.WorkshopIssueReporter._maxReports, and Terraria.Social.Base.WorkshopIssueReporter._reports.
Referenced by Terraria.Social.Base.WorkshopIssueReporter.ReportDelayedUploadProblem(), Terraria.Social.Base.WorkshopIssueReporter.ReportDelayedUploadProblemWithoutKnownReason(), Terraria.Social.Base.WorkshopIssueReporter.ReportDownloadProblem(), Terraria.Social.Base.WorkshopIssueReporter.ReportInstantUploadProblem(), Terraria.Social.Base.WorkshopIssueReporter.ReportInstantUploadProblemFromValue(), and Terraria.Social.Base.WorkshopIssueReporter.ReportManifestCreationProblem().