Terraria: System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockCompleted
DataflowBlockCompleted() [1/2]
void System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockCompleted (IDataflowBlock block) inline package
Definition at line 61 of file DataflowEtwProvider.cs.
    {
        if (!IsEnabled(EventLevel.Informational, EventKeywords.All))
        {
            return;
        }
        Task potentiallyNotSupportedCompletionTask = Common.GetPotentiallyNotSupportedCompletionTask(block);
        if (potentiallyNotSupportedCompletionTask == null || !potentiallyNotSupportedCompletionTask.IsCompleted)
        {
            return;
        }
        BlockCompletionReason status = (BlockCompletionReason)potentiallyNotSupportedCompletionTask.Status;
        string exceptionData = string.Empty;
        if (potentiallyNotSupportedCompletionTask.IsFaulted)
        {
            try
            {
                exceptionData = string.Join(Environment.NewLine, potentiallyNotSupportedCompletionTask.Exception.InnerExceptions.Select((Exception e) => e.ToString()));
            }
            catch
            {
            }
        }
        DataflowBlockCompleted(Common.GetBlockId(block), status, exceptionData);
    }
References System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockCompleted(), System.Threading.Tasks.Task< TResult >.Exception, System.Threading.Tasks.Dataflow.Internal.Common.GetBlockId(), System.Threading.Tasks.Dataflow.Internal.Common.GetPotentiallyNotSupportedCompletionTask(), System.AggregateException.InnerExceptions, System.Threading.Tasks.Task< TResult >.IsCompleted, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Threading.Tasks.Task< TResult >.IsFaulted, System.Environment.NewLine, System.Threading.Tasks.Task< TResult >.Status, and System.Exception.ToString().
Referenced by System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockCompleted().