Terraria: System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.TaskLaunchedForMessageHandling
TaskLaunchedForMessageHandling() [1/2]
void System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.TaskLaunchedForMessageHandling (IDataflowBlock block, Task task, TaskLaunchedReason reason, int availableMessages) inline package
Definition at line 45 of file DataflowEtwProvider.cs.
    {
        if (IsEnabled(EventLevel.Informational, EventKeywords.All))
        {
            TaskLaunchedForMessageHandling(Common.GetBlockId(block), reason, availableMessages, task.Id);
        }
    }
References System.Threading.Tasks.Dataflow.Internal.Common.GetBlockId(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.task, and System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.TaskLaunchedForMessageHandling().
Referenced by System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.TaskLaunchedForMessageHandling().