Terraria: System.Net.Security.AuthenticatedStream.DisposeAsync
DisposeAsync()
override ValueTask System.Net.Security.AuthenticatedStream.DisposeAsync () inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.Net.Security.NegotiateStream, and System.Net.Security.SslStream.
Definition at line 62 of file AuthenticatedStream.cs.
    {
        try
        {
            ValueTask result = (_leaveStreamOpen ? new ValueTask(_innerStream.FlushAsync()) : _innerStream.DisposeAsync());
            GC.SuppressFinalize(this);
            return result;
        }
        catch (Exception exception)
        {
            return ValueTask.FromException(exception);
        }
    }
References System.Net.Security.AuthenticatedStream._innerStream, System.Net.Security.AuthenticatedStream._leaveStreamOpen, System.IO.Stream.DisposeAsync(), System.exception, System.IO.Stream.FlushAsync(), System.Threading.Tasks.ValueTask< TResult >.FromException(), and System.GC.SuppressFinalize().