Terraria: System.IO.IsolatedStorage.IsolatedStorageFile.MoveDirectory
MoveDirectory()
void System.IO.IsolatedStorage.IsolatedStorageFile.MoveDirectory (string sourceDirectoryName, string destinationDirectoryName) inline
Definition at line 426 of file IsolatedStorageFile.cs.
    {
        if (sourceDirectoryName == null)
        {
            throw new ArgumentNullException("sourceDirectoryName");
        }
        if (destinationDirectoryName == null)
        {
            throw new ArgumentNullException("destinationDirectoryName");
        }
        if (sourceDirectoryName.Length == 0)
        {
            throw new ArgumentException(System.SR.Argument_EmptyPath, "sourceDirectoryName");
        }
        if (destinationDirectoryName.Length == 0)
        {
            throw new ArgumentException(System.SR.Argument_EmptyPath, "destinationDirectoryName");
        }
        EnsureStoreIsValid();
        string fullPath = GetFullPath(sourceDirectoryName);
        string fullPath2 = GetFullPath(destinationDirectoryName);
        try
        {
            Directory.Move(fullPath, fullPath2);
        }
        catch (DirectoryNotFoundException)
        {
            throw new DirectoryNotFoundException(System.SR.Format(System.SR.PathNotFound_Path, sourceDirectoryName));
        }
        catch (PathTooLongException)
        {
            throw;
        }
        catch (Exception rootCause)
        {
            throw GetIsolatedStorageException(System.SR.IsolatedStorage_Operation, rootCause);
        }
    }
References System.SR.Argument_EmptyPath, System.IO.IsolatedStorage.IsolatedStorageFile.EnsureStoreIsValid(), System.SR.Format(), System.IO.IsolatedStorage.IsolatedStorageFile.GetFullPath(), System.IO.IsolatedStorage.IsolatedStorageFile.GetIsolatedStorageException(), System.SR.IsolatedStorage_Operation, System.IO.Directory.Move(), and System.SR.PathNotFound_Path.