Terraria: System.IO.IsolatedStorage.IsolatedStorageFile.EnsureStoreIsValid
EnsureStoreIsValid()
void System.IO.IsolatedStorage.IsolatedStorageFile.EnsureStoreIsValid () inline package
Definition at line 556 of file IsolatedStorageFile.cs.
    {
        if (Disposed)
        {
            throw new ObjectDisposedException(null, System.SR.IsolatedStorage_StoreNotOpen);
        }
        if (_closed || IsDeleted)
        {
            throw new InvalidOperationException(System.SR.IsolatedStorage_StoreNotOpen);
        }
    }
References System.IO.IsolatedStorage.IsolatedStorageFile._closed, System.IO.IsolatedStorage.IsolatedStorageFile.Disposed, System.IO.IsolatedStorage.IsolatedStorageFile.IsDeleted, and System.SR.IsolatedStorage_StoreNotOpen.
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.CopyFile(), System.IO.IsolatedStorage.IsolatedStorageFile.CreateDirectory(), System.IO.IsolatedStorage.IsolatedStorageFile.CreateFile(), System.IO.IsolatedStorage.IsolatedStorageFile.DeleteDirectory(), System.IO.IsolatedStorage.IsolatedStorageFile.DeleteFile(), System.IO.IsolatedStorage.IsolatedStorageFile.DirectoryExists(), System.IO.IsolatedStorage.IsolatedStorageFile.FileExists(), System.IO.IsolatedStorage.IsolatedStorageFile.GetCreationTime(), System.IO.IsolatedStorage.IsolatedStorageFile.GetDirectoryNames(), System.IO.IsolatedStorage.IsolatedStorageFile.GetFileNames(), System.IO.IsolatedStorage.IsolatedStorageFile.GetLastAccessTime(), System.IO.IsolatedStorage.IsolatedStorageFile.GetLastWriteTime(), System.IO.IsolatedStorage.IsolatedStorageFile.MoveDirectory(), System.IO.IsolatedStorage.IsolatedStorageFile.MoveFile(), System.IO.IsolatedStorage.IsolatedStorageFile.OpenFile(), System.IO.IsolatedStorage.IsolatedStorageFile.OpenFile(), and System.IO.IsolatedStorage.IsolatedStorageFile.OpenFile().