Terraria: System.IO.IsolatedStorage.IsolatedStorageFile.GetFullPath
GetFullPath()
string System.IO.IsolatedStorage.IsolatedStorageFile.GetFullPath (string partialPath) inline package
Definition at line 546 of file IsolatedStorageFile.cs.
    {
        int i;
        for (i = 0; i < partialPath.Length && (partialPath[i] == Path.DirectorySeparatorChar || partialPath[i] == Path.AltDirectorySeparatorChar); i++)
        {
        }
        partialPath = partialPath.Substring(i);
        return Path.Combine(RootDirectory, partialPath);
    }
References System.IO.Path.AltDirectorySeparatorChar, System.IO.Path.Combine(), and System.IO.IsolatedStorage.IsolatedStorageFile.RootDirectory.
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.CopyFile(), System.IO.IsolatedStorage.IsolatedStorageFile.CreateDirectory(), System.IO.IsolatedStorage.IsolatedStorageFile.DeleteDirectory(), System.IO.IsolatedStorage.IsolatedStorageFile.DeleteFile(), System.IO.IsolatedStorage.IsolatedStorageFile.DirectoryExists(), System.IO.IsolatedStorage.IsolatedStorageFile.FileExists(), System.IO.IsolatedStorage.IsolatedStorageFile.GetCreationTime(), System.IO.IsolatedStorage.IsolatedStorageFile.GetLastAccessTime(), System.IO.IsolatedStorage.IsolatedStorageFile.GetLastWriteTime(), System.IO.IsolatedStorage.IsolatedStorageFileStream.InitializeFileStream(), System.IO.IsolatedStorage.IsolatedStorageFile.MoveDirectory(), and System.IO.IsolatedStorage.IsolatedStorageFile.MoveFile().