Terraria: System.IO.IsolatedStorage.IsolatedStorageFile.GetStore
GetStore() [1/5]
static IsolatedStorageFile System.IO.IsolatedStorage.IsolatedStorageFile.GetStore (IsolatedStorageScope scope) inline static private
Definition at line 505 of file IsolatedStorageFile.cs.
    {
        return new IsolatedStorageFile(scope);
    }
References System.IO.IsolatedStorage.IsolatedStorageFile.IsolatedStorageFile().
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.GetMachineStoreForApplication(), System.IO.IsolatedStorage.IsolatedStorageFile.GetMachineStoreForAssembly(), System.IO.IsolatedStorage.IsolatedStorageFile.GetMachineStoreForDomain(), System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(), System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(), System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(), System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(), System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForApplication(), System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForAssembly(), and System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForDomain().