Terraria: System.IO.IsolatedStorage.IsolatedStorageFile.Close
Close()
void System.IO.IsolatedStorage.IsolatedStorageFile.Close () inline
Definition at line 100 of file IsolatedStorageFile.cs.
    {
        if (Helper.IsRoaming(base.Scope))
        {
            return;
        }
        lock (_internalLock)
        {
            if (!_closed)
            {
                _closed = true;
                GC.SuppressFinalize(this);
            }
        }
    }
References System.IO.IsolatedStorage.IsolatedStorageFile._closed, System.IO.IsolatedStorage.IsolatedStorageFile._internalLock, System.IO.IsolatedStorage.Helper.IsRoaming(), and System.GC.SuppressFinalize().
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.Dispose(), and System.IO.IsolatedStorage.IsolatedStorageFile.Remove().