Terraria: System.IO.IsolatedStorage.IsolatedStorageFile.GetCreationTime
GetCreationTime()
DateTimeOffset System.IO.IsolatedStorage.IsolatedStorageFile.GetCreationTime (string path) inline
Definition at line 264 of file IsolatedStorageFile.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (path.Length == 0)
        {
            throw new ArgumentException(System.SR.Argument_EmptyPath, "path");
        }
        EnsureStoreIsValid();
        try
        {
            return new DateTimeOffset(File.GetCreationTime(GetFullPath(path)));
        }
        catch (UnauthorizedAccessException)
        {
            return new DateTimeOffset(1601, 1, 1, 0, 0, 0, TimeSpan.Zero).ToLocalTime();
        }
    }
References System.SR.Argument_EmptyPath, System.IO.IsolatedStorage.IsolatedStorageFile.EnsureStoreIsValid(), System.IO.File.GetCreationTime(), System.IO.IsolatedStorage.IsolatedStorageFile.GetFullPath(), System.DateTimeOffset.ToLocalTime(), and System.TimeSpan.Zero.