Terraria: System.IO.IsolatedStorage.IsolatedStorageFile.MoveFile
MoveFile()
void System.IO.IsolatedStorage.IsolatedStorageFile.MoveFile (string sourceFileName, string destinationFileName) inline
Definition at line 387 of file IsolatedStorageFile.cs.
    {
        if (sourceFileName == null)
        {
            throw new ArgumentNullException("sourceFileName");
        }
        if (destinationFileName == null)
        {
            throw new ArgumentNullException("destinationFileName");
        }
        if (sourceFileName.Length == 0)
        {
            throw new ArgumentException(System.SR.Argument_EmptyPath, "sourceFileName");
        }
        if (destinationFileName.Length == 0)
        {
            throw new ArgumentException(System.SR.Argument_EmptyPath, "destinationFileName");
        }
        EnsureStoreIsValid();
        string fullPath = GetFullPath(sourceFileName);
        string fullPath2 = GetFullPath(destinationFileName);
        try
        {
            File.Move(fullPath, fullPath2);
        }
        catch (FileNotFoundException)
        {
            throw new FileNotFoundException(System.SR.Format(System.SR.PathNotFound_Path, sourceFileName));
        }
        catch (PathTooLongException)
        {
            throw;
        }
        catch (Exception rootCause)
        {
            throw GetIsolatedStorageException(System.SR.IsolatedStorage_Operation, rootCause);
        }
    }
References System.SR.Argument_EmptyPath, System.IO.IsolatedStorage.IsolatedStorageFile.EnsureStoreIsValid(), System.SR.Format(), System.IO.IsolatedStorage.IsolatedStorageFile.GetFullPath(), System.IO.IsolatedStorage.IsolatedStorageFile.GetIsolatedStorageException(), System.SR.IsolatedStorage_Operation, System.IO.File.Move(), and System.SR.PathNotFound_Path.