Terraria: System.Text.RegularExpressions.RegexLWCGCompiler.FactoryInstanceFromCode
FactoryInstanceFromCode()
RegexRunnerFactory System.Text.RegularExpressions.RegexLWCGCompiler.FactoryInstanceFromCode (string pattern, RegexCode code, RegexOptions options, bool hasTimeout) inline
Definition at line 20 of file RegexLWCGCompiler.cs.
    {
        _code = code;
        _codes = code.Codes;
        _strings = code.Strings;
        _leadingCharClasses = code.LeadingCharClasses;
        _boyerMoorePrefix = code.BoyerMoorePrefix;
        _leadingAnchor = code.LeadingAnchor;
        _trackcount = code.TrackCount;
        _options = options;
        _hasTimeout = hasTimeout;
        uint value = (uint)Interlocked.Increment(ref s_regexCount);
        string value2 = string.Empty;
        if (s_includePatternInName)
        {
            value2 = "_" + ((pattern.Length > 100) ? pattern.AsSpan(0, 100) : ((ReadOnlySpan<char>)pattern));
        }
        DynamicMethod goMethod = DefineDynamicMethod($"Regex{value}_Go{value2}", null, typeof(CompiledRegexRunner));
        GenerateGo();
        DynamicMethod findFirstCharMethod = DefineDynamicMethod($"Regex{value}_FindFirstChar{value2}", typeof(bool), typeof(CompiledRegexRunner));
        GenerateFindFirstChar();
        return new CompiledRegexRunnerFactory(goMethod, findFirstCharMethod, _trackcount);
    }
References System.Text.RegularExpressions.RegexCompiler._boyerMoorePrefix, System.Text.RegularExpressions.RegexCompiler._code, System.Text.RegularExpressions.RegexCompiler._codes, System.Text.RegularExpressions.RegexCompiler._hasTimeout, System.Text.RegularExpressions.RegexCompiler._leadingAnchor, System.Text.RegularExpressions.RegexCompiler._leadingCharClasses, System.Text.RegularExpressions.RegexCompiler._options, System.Text.RegularExpressions.RegexCompiler._strings, System.Text.RegularExpressions.RegexCompiler._trackcount, System.Text.RegularExpressions.RegexCode.BoyerMoorePrefix, System.Text.RegularExpressions.RegexCode.Codes, System.Text.RegularExpressions.RegexLWCGCompiler.DefineDynamicMethod(), System.Text.RegularExpressions.RegexCompiler.GenerateFindFirstChar(), System.Text.RegularExpressions.RegexCompiler.GenerateGo(), System.Threading.Interlocked.Increment(), System.Text.RegularExpressions.RegexCode.LeadingAnchor, System.Text.RegularExpressions.options, System.Text.RegularExpressions.pattern, System.Text.RegularExpressions.RegexLWCGCompiler.s_includePatternInName, System.Text.RegularExpressions.RegexLWCGCompiler.s_regexCount, System.Text.RegularExpressions.RegexCode.Strings, System.Text.RegularExpressions.RegexCode.TrackCount, and System.Text.RegularExpressions.value.
Referenced by System.Text.RegularExpressions.RegexCompiler.Compile().