Terraria: System.IO.IsolatedStorage.IsolatedStorageFile.Remove
Remove() [1/2]
override void System.IO.IsolatedStorage.IsolatedStorageFile.Remove () inline
Definition at line 586 of file IsolatedStorageFile.cs.
    {
        try
        {
            Directory.Delete(RootDirectory, recursive: true);
        }
        catch
        {
            throw new IsolatedStorageException(System.SR.IsolatedStorage_DeleteDirectories);
        }
        Close();
        string directoryName = Path.GetDirectoryName(RootDirectory.TrimEnd(Path.DirectorySeparatorChar));
        if (ContainsUnknownFiles(directoryName))
        {
            return;
        }
        try
        {
            Directory.Delete(directoryName, recursive: true);
        }
        catch
        {
            return;
        }
        if (!Helper.IsDomain(base.Scope))
        {
            return;
        }
        directoryName = Path.GetDirectoryName(directoryName);
        if (ContainsUnknownFiles(directoryName))
        {
            return;
        }
        try
        {
            Directory.Delete(directoryName, recursive: true);
        }
        catch
        {
        }
    }
References System.IO.IsolatedStorage.IsolatedStorageFile.Close(), System.IO.IsolatedStorage.IsolatedStorageFile.ContainsUnknownFiles(), System.IO.Directory.Delete(), System.IO.Path.DirectorySeparatorChar, System.IO.Path.GetDirectoryName(), System.IO.IsolatedStorage.Helper.IsDomain(), System.SR.IsolatedStorage_DeleteDirectories, and System.IO.IsolatedStorage.IsolatedStorageFile.RootDirectory.