Terraria: System.IO.IsolatedStorage.IsolatedStorageFile.Remove
Remove() [2/2]
static void System.IO.IsolatedStorage.IsolatedStorageFile.Remove (IsolatedStorageScope scope) inline static
Definition at line 628 of file IsolatedStorageFile.cs.
    {
        VerifyGlobalScope(scope);
        string rootDirectory = Helper.GetRootDirectory(scope);
        try
        {
            Directory.Delete(rootDirectory, recursive: true);
            Directory.CreateDirectory(rootDirectory);
        }
        catch
        {
            throw new IsolatedStorageException(System.SR.IsolatedStorage_DeleteDirectories);
        }
    }
References System.IO.Directory.CreateDirectory(), System.IO.Directory.Delete(), System.IO.IsolatedStorage.Helper.GetRootDirectory(), System.SR.IsolatedStorage_DeleteDirectories, and System.IO.IsolatedStorage.IsolatedStorageFile.VerifyGlobalScope().