Terraria: System.IO.IsolatedStorage.IsolatedStorageFile.IsolatedStorageFile
IsolatedStorageFile()
System.IO.IsolatedStorage.IsolatedStorageFile.IsolatedStorageFile (IsolatedStorageScope scope) inline package
Definition at line 76 of file IsolatedStorageFile.cs.
    {
        InitStore(scope, null, null);
        StringBuilder stringBuilder = new StringBuilder(Helper.GetRootDirectory(scope));
        stringBuilder.Append(SeparatorExternal);
        stringBuilder.Append(base.IdentityHash);
        stringBuilder.Append(SeparatorExternal);
        if (Helper.IsApplication(scope))
        {
            stringBuilder.Append("AppFiles");
        }
        else if (Helper.IsDomain(scope))
        {
            stringBuilder.Append("Files");
        }
        else
        {
            stringBuilder.Append("AssemFiles");
        }
        stringBuilder.Append(SeparatorExternal);
        _rootDirectory = stringBuilder.ToString();
        Helper.CreateDirectory(_rootDirectory, scope);
    }
References System.IO.IsolatedStorage.IsolatedStorageFile._rootDirectory, System.Text.StringBuilder.Append(), System.IO.IsolatedStorage.Helper.CreateDirectory(), System.IO.IsolatedStorage.Helper.GetRootDirectory(), System.IO.IsolatedStorage.IsolatedStorage.InitStore(), System.IO.IsolatedStorage.Helper.IsApplication(), System.IO.IsolatedStorage.Helper.IsDomain(), System.IO.IsolatedStorage.IsolatedStorage.SeparatorExternal, and System.Text.StringBuilder.ToString().
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.GetStore().