Terraria: System.Net.Http.SocksHelper.EstablishSocks5TunnelAsync
EstablishSocks5TunnelAsync()
static async ValueTask System.Net.Http.SocksHelper.EstablishSocks5TunnelAsync (Stream stream, string host, int port, Uri proxyUri, NetworkCredential credentials, bool async) inline static private
Definition at line 45 of file SocksHelper.cs.
    {
        byte[] buffer = ArrayPool<byte>.Shared.Rent(513);
        try
        {
            buffer[0] = 5;
            if (credentials == null)
            {
                buffer[1] = 1;
                buffer[2] = 0;
            }
            else
            {
                buffer[1] = 2;
                buffer[2] = 0;
                buffer[3] = 2;
            }
            await WriteAsync(stream, buffer.AsMemory(0, buffer[1] + 2), async).ConfigureAwait(continueOnCapturedContext: false);
            await ReadToFillAsync(stream, buffer.AsMemory(0, 2), async).ConfigureAwait(continueOnCapturedContext: false);
            VerifyProtocolVersion(5, buffer[0]);
            switch (buffer[1])
            {
            case 2:
            {
                if (credentials == null)
                {
                    throw new SocksException(System.SR.net_socks_auth_required);
                }
                buffer[0] = 1;
                byte b = (buffer[1] = EncodeString(credentials.UserName, buffer.AsSpan(2), "UserName"));
                await WriteAsync(stream, buffer.AsMemory(0, 3 + b + (buffer[2 + b] = EncodeString(credentials.Password, buffer.AsSpan(3 + b), "Password"))), async).ConfigureAwait(continueOnCapturedContext: false);
                await ReadToFillAsync(stream, buffer.AsMemory(0, 2), async).ConfigureAwait(continueOnCapturedContext: false);
                if (buffer[0] != 1 || buffer[1] != 0)
                {
                    throw new SocksException(System.SR.net_socks_auth_failed);
                }
                break;
            }
            default:
                throw new SocksException(System.SR.net_socks_no_auth_method);
            case 0:
                break;
            }
            buffer[0] = 5;
            buffer[1] = 1;
            buffer[2] = 0;
            int num;
            if (IPAddress.TryParse(host, out IPAddress address))
            {
                if (address.AddressFamily == AddressFamily.InterNetwork)
                {
                    buffer[3] = 1;
                    address.TryWriteBytes(buffer.AsSpan(4), out var _);
                    num = 4;
                }
                else
                {
                    buffer[3] = 4;
                    address.TryWriteBytes(buffer.AsSpan(4), out var _);
                    num = 16;
                }
            }
            else
            {
                buffer[3] = 3;
                num = (buffer[4] = EncodeString(host, buffer.AsSpan(5), "host")) + 1;
            }
            BinaryPrimitives.WriteUInt16BigEndian(buffer.AsSpan(num + 4), (ushort)port);
            await WriteAsync(stream, buffer.AsMemory(0, num + 6), async).ConfigureAwait(continueOnCapturedContext: false);
            await ReadToFillAsync(stream, buffer.AsMemory(0, 5), async).ConfigureAwait(continueOnCapturedContext: false);
            VerifyProtocolVersion(5, buffer[0]);
            if (buffer[1] != 0)
            {
                throw new SocksException(System.SR.net_socks_connection_failed);
            }
            await ReadToFillAsync(stream, buffer.AsMemory(0, buffer[3] switch
            {
                1 => 5,
                4 => 17,
                3 => buffer[4] + 2,
                _ => throw new SocksException(System.SR.net_socks_bad_address_type),
            }), async).ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            ArrayPool<byte>.Shared.Return(buffer);
        }
    }
References System.buffer, System.Net.Http.SocksHelper.EncodeString(), System.SR.net_socks_auth_failed, System.SR.net_socks_auth_required, System.SR.net_socks_connection_failed, System.SR.net_socks_no_auth_method, System.Net.NetworkCredential.Password, System.Net.Http.SocksHelper.ReadToFillAsync(), System.Buffers.ArrayPool< T >.Shared, System.stream, System.Net.IPAddress.TryParse(), System.Net.NetworkCredential.UserName, System.Net.Http.SocksHelper.VerifyProtocolVersion(), System.Net.Http.SocksHelper.WriteAsync(), and System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian().
Referenced by System.Net.Http.SocksHelper.EstablishSocksTunnelAsync().