Terraria: System.Net.Http.SocksHelper.EstablishSocksTunnelAsync
EstablishSocksTunnelAsync()
static async ValueTask System.Net.Http.SocksHelper.EstablishSocksTunnelAsync (Stream stream, string host, int port, Uri proxyUri, ICredentials proxyCredentials, bool async, CancellationToken cancellationToken) inline static
Definition at line 13 of file SocksHelper.cs.
    {
        using (cancellationToken.Register(delegate(object s)
        {
            ((Stream)s).Dispose();
        }, stream))
        {
            _ = 2;
            try
            {
                NetworkCredential credentials = proxyCredentials?.GetCredential(proxyUri, proxyUri.Scheme);
                if (string.Equals(proxyUri.Scheme, "socks5", StringComparison.OrdinalIgnoreCase))
                {
                    await EstablishSocks5TunnelAsync(stream, host, port, proxyUri, credentials, async).ConfigureAwait(continueOnCapturedContext: false);
                }
                else if (string.Equals(proxyUri.Scheme, "socks4a", StringComparison.OrdinalIgnoreCase))
                {
                    await EstablishSocks4TunnelAsync(stream, isVersion4a: true, host, port, proxyUri, credentials, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
                else if (string.Equals(proxyUri.Scheme, "socks4", StringComparison.OrdinalIgnoreCase))
                {
                    await EstablishSocks4TunnelAsync(stream, isVersion4a: false, host, port, proxyUri, credentials, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            catch
            {
                stream.Dispose();
                throw;
            }
        }
    }
References System.cancellationToken, System.Net.Equals, System.Net.Http.SocksHelper.EstablishSocks4TunnelAsync(), System.Net.Http.SocksHelper.EstablishSocks5TunnelAsync(), System.Net.ICredentials.GetCredential(), System.s, System.Uri.Scheme, System.Net.Sockets.Stream, and System.stream.
Referenced by System.Net.Http.HttpConnectionPool.EstablishSocksTunnel().