Terraria: System.Net.Http.SocksHelper.EstablishSocks4TunnelAsync
EstablishSocks4TunnelAsync()
static async ValueTask System.Net.Http.SocksHelper.EstablishSocks4TunnelAsync (Stream stream, bool isVersion4a, string host, int port, Uri proxyUri, NetworkCredential credentials, bool async, CancellationToken cancellationToken) inline static private
Definition at line 134 of file SocksHelper.cs.
    {
        byte[] buffer = ArrayPool<byte>.Shared.Rent(513);
        try
        {
            buffer[0] = 4;
            buffer[1] = 1;
            BinaryPrimitives.WriteUInt16BigEndian(buffer.AsSpan(2), (ushort)port);
            IPAddress iPAddress = null;
            if (IPAddress.TryParse(host, out IPAddress address))
            {
                if (address.AddressFamily == AddressFamily.InterNetwork)
                {
                    iPAddress = address;
                }
                else
                {
                    if (!address.IsIPv4MappedToIPv6)
                    {
                        throw new SocksException(System.SR.net_socks_ipv6_notsupported);
                    }
                    iPAddress = address.MapToIPv4();
                }
            }
            else if (!isVersion4a)
            {
                IPAddress[] array2;
                try
                {
                    IPAddress[] array = ((!async) ? Dns.GetHostAddresses(host, AddressFamily.InterNetwork) : (await Dns.GetHostAddressesAsync(host, AddressFamily.InterNetwork, cancellationToken).ConfigureAwait(continueOnCapturedContext: false)));
                    array2 = array;
                }
                catch (Exception innerException)
                {
                    throw new SocksException(System.SR.net_socks_no_ipv4_address, innerException);
                }
                if (array2.Length == 0)
                {
                    throw new SocksException(System.SR.net_socks_no_ipv4_address);
                }
                iPAddress = array2[0];
            }
            if (iPAddress == null)
            {
                buffer[4] = 0;
                buffer[5] = 0;
                buffer[6] = 0;
                buffer[7] = byte.MaxValue;
            }
            else
            {
                iPAddress.TryWriteBytes(buffer.AsSpan(4), out var _);
            }
            byte b = EncodeString(credentials?.UserName, buffer.AsSpan(8), "UserName");
            buffer[8 + b] = 0;
            int num = 9 + b;
            if (iPAddress == null)
            {
                byte b2 = EncodeString(host, buffer.AsSpan(num), "host");
                buffer[num + b2] = 0;
                num += b2 + 1;
            }
            await WriteAsync(stream, buffer.AsMemory(0, num), async).ConfigureAwait(continueOnCapturedContext: false);
            await ReadToFillAsync(stream, buffer.AsMemory(0, 8), async).ConfigureAwait(continueOnCapturedContext: false);
            switch (buffer[1])
            {
            case 93:
                throw new SocksException(System.SR.net_socks_auth_failed);
            default:
                throw new SocksException(System.SR.net_socks_connection_failed);
            case 90:
                break;
            }
        }
        finally
        {
            ArrayPool<byte>.Shared.Return(buffer);
        }
    }
References System.array, System.buffer, System.cancellationToken, System.Net.Http.SocksHelper.EncodeString(), System.Net.Dns.GetHostAddresses(), System.Net.Dns.GetHostAddressesAsync(), System.Net.IPAddress.MapToIPv4(), System.SR.net_socks_auth_failed, System.SR.net_socks_connection_failed, System.SR.net_socks_ipv6_notsupported, System.SR.net_socks_no_ipv4_address, System.Net.Http.SocksHelper.ReadToFillAsync(), System.Buffers.ArrayPool< T >.Shared, System.stream, System.Net.IPAddress.TryParse(), System.Net.IPAddress.TryWriteBytes(), System.Net.Http.SocksHelper.WriteAsync(), and System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian().
Referenced by System.Net.Http.SocksHelper.EstablishSocksTunnelAsync().