Terraria: System.Net.Http.SocksHelper.EncodeString
EncodeString()
static byte System.Net.Http.SocksHelper.EncodeString (ReadOnlySpan< char > chars, Span< byte > buffer, string parameterName) inline static private
Definition at line 214 of file SocksHelper.cs.
    {
        try
        {
            return checked((byte)Encoding.UTF8.GetBytes(chars, buffer));
        }
        catch
        {
            throw new SocksException(System.SR.Format(System.SR.net_socks_string_too_long, parameterName));
        }
    }
References System.buffer, System.chars, System.SR.Format(), System.SR.net_socks_string_too_long, and System.Text.Encoding.UTF8.
Referenced by System.Net.Http.SocksHelper.EstablishSocks4TunnelAsync(), and System.Net.Http.SocksHelper.EstablishSocks5TunnelAsync().