Terraria: System.Collections.Generic.Dictionary.CollectionsMarshalHelper.GetValueRefOrAddDefault
GetValueRefOrAddDefault()
static ref TValue System.Collections.Generic.Dictionary< TKey, TValue >.CollectionsMarshalHelper.GetValueRefOrAddDefault (Dictionary< TKey, TValue > dictionary, TKey key, out bool exists) inline static
Definition at line 17 of file Dictionary.cs.
        {
            if (key == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.key);
            }
            if (dictionary._buckets == null)
            {
                dictionary.Initialize(0);
            }
            Entry[] entries = dictionary._entries;
            IEqualityComparer<TKey> comparer = dictionary._comparer;
            uint num = (uint)(comparer?.GetHashCode(key) ?? key.GetHashCode());
            uint num2 = 0u;
            ref int bucket = ref dictionary.GetBucket(num);
            int num3 = bucket - 1;
            if (comparer == null)
            {
                if (typeof(TKey).IsValueType)
                {
                    while ((uint)num3 < (uint)entries.Length)
                    {
                        if (entries[num3].hashCode == num && EqualityComparer<TKey>.Default.Equals(entries[num3].key, key))
{
                            exists = true;
                            return ref entries[num3].value;
                        }
                        num3 = entries[num3].next;
                        num2++;
                        if (num2 > (uint)entries.Length)
{
                            ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                        }
                    }
                }
                else
                {
                    EqualityComparer<TKey> @default = EqualityComparer<TKey>.Default;
                    while ((uint)num3 < (uint)entries.Length)
                    {
                        if (entries[num3].hashCode == num && @default.Equals(entries[num3].key, key))
{
                            exists = true;
                            return ref entries[num3].value;
                        }
                        num3 = entries[num3].next;
                        num2++;
                        if (num2 > (uint)entries.Length)
{
                            ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                        }
                    }
                }
            }
            else
            {
                while ((uint)num3 < (uint)entries.Length)
                {
                    if (entries[num3].hashCode == num && comparer.Equals(entries[num3].key, key))
                    {
                        exists = true;
                        return ref entries[num3].value;
                    }
                    num3 = entries[num3].next;
                    num2++;
                    if (num2 > (uint)entries.Length)
                    {
                        ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                    }
                }
            }
            int num4;
            if (dictionary._freeCount > 0)
            {
                num4 = dictionary._freeList;
                dictionary._freeList = -3 - entries[dictionary._freeList].next;
                dictionary._freeCount--;
            }
            else
            {
                int count = dictionary._count;
                if (count == entries.Length)
                {
                    dictionary.Resize();
                    bucket = ref dictionary.GetBucket(num);
                }
                num4 = count;
                dictionary._count = count + 1;
                entries = dictionary._entries;
            }
            ref Entry reference = ref entries[num4];
            reference.hashCode = num;
            reference.next = bucket - 1;
            reference.key = key;
            reference.value = default(TValue);
            bucket = num4 + 1;
            dictionary._version++;
            if (!typeof(TKey).IsValueType && num2 > 100 && comparer is NonRandomizedStringEqualityComparer)
            {
                dictionary.Resize(entries.Length, forceNewHashCodes: true);
                exists = false;
                return ref dictionary.FindValue(key);
            }
            exists = false;
            return ref reference.value;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Collections.Generic.Dictionary< TKey, TValue >._comparer, System.Collections.Generic.Dictionary< TKey, TValue >._entries, System.Collections.Generic.Dictionary< TKey, TValue >._freeCount, System.Collections.Generic.Dictionary< TKey, TValue >._freeList, System.Collections.Generic.Dictionary< TKey, TValue >._version, System.comparer, System.count, System.Default, System.dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.FindValue(), System.Collections.Generic.Dictionary< TKey, TValue >.GetBucket(), System.key, System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported().
Referenced by System.Runtime.InteropServices.CollectionsMarshal.GetValueRefOrAddDefault< TKey, TValue >().