Terraria: ShaderSelector.Update
Update()
void ShaderSelector.Update (float timeElapsed) inline
     {
         UpdateShaderVisibility(timeElapsed);
         UpdateShaders(timeElapsed);
         BuildOperationsList();
     }
References BuildOperationsList(), UpdateShaders(), and UpdateShaderVisibility().
Referenced by ChromaEngine.Update().