Terraria: Terraria.GameContent.Bestiary.CustomEntryIcon.CustomEntryIcon
CustomEntryIcon()
Terraria.GameContent.Bestiary.CustomEntryIcon.CustomEntryIcon (string nameLanguageKey, string texturePath, Func< bool > unlockCondition) inline
    {
        _text = Language.GetText(nameLanguageKey);
        _textureAsset = Main.Assets.Request<Texture2D>(texturePath, (AssetRequestMode)1);
        _unlockCondition = unlockCondition;
        UpdateUnlockState(state: false);
    }
References Terraria.GameContent.Bestiary.CustomEntryIcon._text, Terraria.GameContent.Bestiary.CustomEntryIcon._textureAsset, Terraria.GameContent.Bestiary.CustomEntryIcon._unlockCondition, Terraria.Main.Assets, Terraria.Localization.Language.GetText(), and Terraria.GameContent.Bestiary.CustomEntryIcon.UpdateUnlockState().
Referenced by Terraria.GameContent.Bestiary.CustomEntryIcon.CreateClone().