Terraria: System.Net.CookieContainer.GetAllCookies
GetAllCookies()
CookieCollection System.Net.CookieContainer.GetAllCookies () inline
Definition at line 598 of file CookieContainer.cs.
    {
        CookieCollection cookieCollection = new CookieCollection();
        lock (m_domainTable.SyncRoot)
        {
            IDictionaryEnumerator enumerator = m_domainTable.GetEnumerator();
            while (enumerator.MoveNext())
            {
                PathList pathList = (PathList)enumerator.Value;
                lock (pathList.SyncRoot)
                {
                    IDictionaryEnumerator enumerator2 = pathList.List.GetEnumerator();
                    while (enumerator2.MoveNext())
                    {
                        cookieCollection.Add((CookieCollection)enumerator2.Value);
                    }
                }
            }
            return cookieCollection;
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Collections.Hashtable.GetEnumerator(), System.Net.CookieContainer.m_domainTable, System.Collections.Generic.Dictionary< TKey, TValue >.SyncRoot, and System.Collections.Hashtable.SyncRoot.