Terraria: System.Net.CookieContainer.BuildCookieCollectionFromDomainMatches
BuildCookieCollectionFromDomainMatches()
void System.Net.CookieContainer.BuildCookieCollectionFromDomainMatches (Uri uri, bool isSecure, int port, ref CookieCollection cookies, List< string > domainAttribute, bool matchOnlyPlainCookie) inline private
Definition at line 674 of file CookieContainer.cs.
    {
        for (int i = 0; i < domainAttribute.Count; i++)
        {
            PathList pathList;
            lock (m_domainTable.SyncRoot)
            {
                pathList = (PathList)m_domainTable[domainAttribute[i]];
                if (pathList == null)
                {
                    continue;
                }
            }
            lock (pathList.SyncRoot)
            {
                SortedList list = pathList.List;
                int count = list.Count;
                for (int j = 0; j < count; j++)
                {
                    string cookiePath = (string)list.GetKey(j);
                    if (PathMatch(uri.AbsolutePath, cookiePath))
                    {
                        CookieCollection cookieCollection = (CookieCollection)list.GetByIndex(j);
                        cookieCollection.TimeStamp(CookieCollection.Stamp.Set);
                        MergeUpdateCollections(ref cookies, cookieCollection, port, isSecure, matchOnlyPlainCookie);
                    }
                }
            }
            if (pathList.Count == 0)
            {
                lock (m_domainTable.SyncRoot)
                {
                    m_domainTable.Remove(domainAttribute[i]);
                }
            }
        }
    }
References System.Uri.AbsolutePath, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.list, System.Net.CookieContainer.m_domainTable, System.Net.CookieContainer.MergeUpdateCollections(), System.Net.CookieContainer.PathMatch(), System.Collections.Hashtable.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.SyncRoot, and System.Collections.Hashtable.SyncRoot.
Referenced by System.Net.CookieContainer.InternalGetCookies().