Terraria: System.Net.CookieContainer.CookieCutter
CookieCutter()
CookieCollection System.Net.CookieContainer.CookieCutter (Uri uri, string headerName, string setCookieHeader, bool isThrow) inline package
Definition at line 517 of file CookieContainer.cs.
    {
        if (NetEventSource.Log.IsEnabled())
        {
            NetEventSource.Info(this, $"uri:{uri} headerName:{headerName} setCookieHeader:{setCookieHeader} isThrow:{isThrow}", "CookieCutter");
        }
        CookieCollection cookieCollection = new CookieCollection();
        CookieVariant variant = CookieVariant.Unknown;
        if (headerName == null)
        {
            variant = CookieVariant.Rfc2109;
        }
        else
        {
            for (int i = 0; i < s_headerInfo.Length; i++)
            {
                if (string.Equals(headerName, s_headerInfo[i].Name, StringComparison.OrdinalIgnoreCase))
                {
                    variant = s_headerInfo[i].Variant;
                }
            }
        }
        bool isLocalDomain = IsLocalDomain(uri.Host);
        try
        {
            CookieParser cookieParser = new CookieParser(setCookieHeader);
            while (true)
            {
                Cookie cookie = cookieParser.Get();
                if (NetEventSource.Log.IsEnabled())
                {
                    NetEventSource.Info(this, $"CookieParser returned cookie:{cookie}", "CookieCutter");
                }
                if (cookie == null)
                {
                    if (cookieParser.EndofHeader())
                    {
                        break;
                    }
                }
                else if (string.IsNullOrEmpty(cookie.Name))
                {
                    if (isThrow)
                    {
                        throw new CookieException(System.SR.net_cookie_format);
                    }
                }
                else if (cookie.VerifySetDefaults(variant, uri, isLocalDomain, m_fqdnMyDomain, setDefault: true, isThrow))
                {
                    cookieCollection.InternalAdd(cookie, isStrict: true);
                }
            }
        }
        catch (OutOfMemoryException)
        {
            throw;
        }
        catch (Exception inner)
        {
            if (isThrow)
            {
                throw new CookieException(System.SR.Format(System.SR.net_cookie_parse_header, uri.AbsoluteUri), inner);
            }
        }
        int count = cookieCollection.Count;
        for (int j = 0; j < count; j++)
        {
            Add(cookieCollection[j], isThrow);
        }
        return cookieCollection;
    }
References System.Uri.AbsoluteUri, System.Add, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Equals, System.SR.Format(), System.Uri.Host, System.Net.NetEventSource.Info(), System.Net.CookieContainer.IsLocalDomain(), System.Net.NetEventSource.Log, System.Net.CookieContainer.m_fqdnMyDomain, System.Name, System.SR.net_cookie_format, System.SR.net_cookie_parse_header, and System.Net.CookieContainer.s_headerInfo.
Referenced by System.Net.CookieContainer.SetCookies().