Terraria: System.Net.CookieContainer.InternalGetCookies
InternalGetCookies()
CookieCollection System.Net.CookieContainer.InternalGetCookies (Uri uri) inline package
Definition at line 620 of file CookieContainer.cs.
    {
        if (m_count == 0)
        {
            return null;
        }
        bool isSecure = uri.Scheme == "https" || uri.Scheme == "wss";
        int port = uri.Port;
        CookieCollection cookies = null;
        List<string> list = new List<string>();
        List<string> list2 = null;
        string host = uri.Host;
        list.Add(host);
        list.Add("." + host);
        int num = host.IndexOf('.');
        if (num == -1)
        {
            if (m_fqdnMyDomain != null && m_fqdnMyDomain.Length != 0)
            {
                list.Add(host + m_fqdnMyDomain);
                list.Add(m_fqdnMyDomain);
            }
        }
        else
        {
            list.Add(host.Substring(num));
            if (host.Length > 2)
            {
                int num2 = host.LastIndexOf('.', host.Length - 2);
                if (num2 > 0)
                {
                    num2 = host.LastIndexOf('.', num2 - 1);
                }
                if (num2 != -1)
                {
                    while (num < num2 && (num = host.IndexOf('.', num + 1)) != -1)
                    {
                        if (list2 == null)
{
                            list2 = new List<string>();
                        }
                        list2.Add(host.Substring(num));
                    }
                }
            }
        }
        BuildCookieCollectionFromDomainMatches(uri, isSecure, port, ref cookies, list, matchOnlyPlainCookie: false);
        if (list2 != null)
        {
            BuildCookieCollectionFromDomainMatches(uri, isSecure, port, ref cookies, list2, matchOnlyPlainCookie: true);
        }
        return cookies;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.CookieContainer.BuildCookieCollectionFromDomainMatches(), System.Uri.Host, System.list, System.Net.CookieContainer.m_count, System.Net.CookieContainer.m_fqdnMyDomain, and System.Uri.Port.
Referenced by System.Net.CookieContainer.GetCookieHeader(), and System.Net.CookieContainer.GetCookies().