Terraria: System.Net.CookieContainer.AgeCookies
AgeCookies()
bool System.Net.CookieContainer.AgeCookies (string domain) inline private
Definition at line 241 of file CookieContainer.cs.
    {
        int num = 0;
        DateTime dateTime = DateTime.MaxValue;
        CookieCollection cookieCollection = null;
        string text = null;
        int num2 = 0;
        int num3 = 0;
        float num4 = 1f;
        if (m_count > m_maxCookies)
        {
            num4 = (float)m_maxCookies / (float)m_count;
        }
        lock (m_domainTable.SyncRoot)
        {
            foreach (object item in m_domainTable)
            {
                DictionaryEntry dictionaryEntry = (DictionaryEntry)item;
                string text2;
                PathList pathList;
                if (domain == null)
                {
                    text2 = (string)dictionaryEntry.Key;
                    pathList = (PathList)dictionaryEntry.Value;
                }
                else
                {
                    text2 = domain;
                    pathList = (PathList)m_domainTable[domain];
                }
                num2 = 0;
                lock (pathList.SyncRoot)
                {
                    foreach (CookieCollection value in pathList.Values)
                    {
                        num3 = ExpireCollection(value);
                        num += num3;
                        m_count -= num3;
                        num2 += value.Count;
                        DateTime dateTime2;
                        if (value.Count > 0 && (dateTime2 = value.TimeStamp(CookieCollection.Stamp.Check)) < dateTime)
{
                            text = text2;
                            cookieCollection = value;
                            dateTime = dateTime2;
                        }
                    }
                }
                int num5 = Math.Min((int)((float)num2 * num4), Math.Min(m_maxCookiesPerDomain, m_maxCookies) - 1);
                if (num2 <= num5)
                {
                    continue;
                }
                CookieCollection[] array;
                DateTime[] array2;
                lock (pathList.SyncRoot)
                {
                    array = new CookieCollection[pathList.Count];
                    array2 = new DateTime[pathList.Count];
                    foreach (CookieCollection value2 in pathList.Values)
                    {
                        array2[num3] = value2.TimeStamp(CookieCollection.Stamp.Check);
                        array[num3] = value2;
                        num3++;
                    }
                }
                Array.Sort(array2, array);
                num3 = 0;
                foreach (CookieCollection cookieCollection4 in array)
                {
                    lock (cookieCollection4)
                    {
                        while (num2 > num5 && cookieCollection4.Count > 0)
{
                            cookieCollection4.RemoveAt(0);
                            num2--;
                            m_count--;
                            num++;
                        }
                    }
                    if (num2 <= num5)
                    {
                        break;
                    }
                }
                if (num2 > num5 && domain != null)
                {
                    return false;
                }
            }
        }
        if (domain != null)
        {
            return true;
        }
        if (num != 0)
        {
            return true;
        }
        if (dateTime == DateTime.MaxValue)
        {
            return false;
        }
        lock (cookieCollection)
        {
            while (m_count >= m_maxCookies && cookieCollection.Count > 0)
            {
                cookieCollection.RemoveAt(0);
                m_count--;
            }
        }
        return true;
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.CookieContainer.ExpireCollection(), System.item, System.Net.CookieContainer.m_count, System.Net.CookieContainer.m_domainTable, System.Net.CookieContainer.m_maxCookies, System.Net.CookieContainer.m_maxCookiesPerDomain, System.DateTime.MaxValue, System.Math.Min(), System.Array.Sort(), System.Collections.Generic.Dictionary< TKey, TValue >.SyncRoot, System.Collections.Hashtable.SyncRoot, System.text, System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Net.CookieContainer.Add().