Terraria: System.Net.CookieContainer.Add
Add() [1/5]
void System.Net.CookieContainer.Add (Cookie cookie) inline
Definition at line 137 of file CookieContainer.cs.
    {
        if (cookie == null)
        {
            throw new ArgumentNullException("cookie");
        }
        if (cookie.Domain.Length == 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_emptystringcall, "cookie.Domain"), "cookie");
        }
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.Append(cookie.Secure ? "https" : "http").Append("://");
        if (!cookie.DomainImplicit && cookie.Domain[0] == '.')
        {
            stringBuilder.Append('0');
        }
        stringBuilder.Append(cookie.Domain);
        if (cookie.PortList != null)
        {
            stringBuilder.Append(':').Append(cookie.PortList[0]);
        }
        stringBuilder.Append(cookie.Path);
        if (!Uri.TryCreate(stringBuilder.ToString(), UriKind.Absolute, out Uri result))
        {
            throw new CookieException(System.SR.Format(System.SR.net_cookie_attribute, "Domain", cookie.Domain));
        }
        Cookie cookie2 = cookie.Clone();
        cookie2.VerifySetDefaults(cookie2.Variant, result, IsLocalDomain(result.Host), m_fqdnMyDomain, setDefault: true, shouldThrow: true);
        Add(cookie2, throwOnError: true);
    }
References System.Add, System.SR.Format(), System.Net.CookieContainer.IsLocalDomain(), System.Net.CookieContainer.m_fqdnMyDomain, System.SR.net_cookie_attribute, System.SR.net_emptystringcall, and System.Uri.TryCreate().