Terraria: System.Net.CookieContainer.IsLocalDomain
IsLocalDomain()
bool System.Net.CookieContainer.IsLocalDomain (string host) inline package
Definition at line 424 of file CookieContainer.cs.
    {
        int num = host.IndexOf('.');
        if (num == -1)
        {
            return true;
        }
        switch (host)
        {
        case "127.0.0.1":
        case "::1":
        case "0:0:0:0:0:0:0:1":
            return true;
        default:
        {
            if (string.Compare(m_fqdnMyDomain, 0, host, num, m_fqdnMyDomain.Length, StringComparison.OrdinalIgnoreCase) == 0)
            {
                return true;
            }
            string[] array = host.Split('.');
            if (array != null && array.Length == 4 && array[0] == "127")
            {
                int i;
                for (i = 1; i < array.Length; i++)
                {
                    string text = array[i];
                    switch (text.Length)
                    {
                    case 3:
                        if (text[2] < '0' || text[2] > '9')
{
                            break;
                        }
                        goto case 2;
                    case 2:
                        if (text[1] < '0' || text[1] > '9')
{
                            break;
                        }
                        goto case 1;
                    case 1:
                        if (text[0] >= '0' && text[0] <= '9')
{
                            continue;
                        }
                        break;
                    }
                    break;
                }
                if (i == 4)
                {
                    return true;
                }
            }
            return false;
        }
        }
    }
References System.array, System.Net.CookieContainer.m_fqdnMyDomain, and System.text.
Referenced by System.Net.CookieContainer.Add(), System.Net.CookieContainer.Add(), System.Net.CookieContainer.Add(), and System.Net.CookieContainer.CookieCutter().