Terraria: MagicMissileDrawer.Draw
Draw()
void MagicMissileDrawer.Draw (Projectile proj) inline
     {
         MiscShaderData miscShaderData = GameShaders.Misc["MagicMissile"];
         miscShaderData.UseSaturation(-2.8f);
         miscShaderData.UseOpacity(2f);
         miscShaderData.Apply();
         _vertexStrip.PrepareStripWithProceduralPadding(proj.oldPos, proj.oldRot, StripColors, StripWidth, -Main.screenPosition + proj.Size / 2f);
         _vertexStrip.DrawTrail();
         Main.pixelShader.CurrentTechnique.Passes[0].Apply();
     }
References _vertexStrip, MiscShaderData.Apply(), VertexStrip.DrawTrail(), GameShaders.Misc, Projectile.oldPos, Projectile.oldRot, Main.pixelShader, VertexStrip.PrepareStripWithProceduralPadding(), Main.screenPosition, Entity.Size, StripColors(), StripWidth(), MiscShaderData.UseOpacity(), and MiscShaderData.UseSaturation().