Terraria: System.Security.Principal.IdentityReference.Translate
Translate()
IdentityReference System.Security.Principal.IdentityReference.Translate (Type targetType) abstract
Referenced by System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(), System.Security.AccessControl.DirectoryObjectSecurity.ModifyAccess(), System.Security.AccessControl.CommonObjectSecurity.ModifyAudit(), System.Security.AccessControl.DirectoryObjectSecurity.ModifyAudit(), System.Security.AccessControl.ObjectSecurity< T >.PurgeAccessRules(), System.Security.AccessControl.ObjectSecurity< T >.PurgeAuditRules(), System.Security.AccessControl.ObjectSecurity< T >.SetGroup(), and System.Security.AccessControl.ObjectSecurity< T >.SetOwner().