Terraria: System.Random.XoshiroImpl.NextUInt64
NextUInt64()
ulong System.Random.XoshiroImpl.NextUInt64 () inline package
Definition at line 461 of file Random.cs.
        {
            ulong s = _s0;
            ulong s2 = _s1;
            ulong s3 = _s2;
            ulong s4 = _s3;
            ulong result = BitOperations.RotateLeft(s2 * 5, 7) * 9;
            ulong num = s2 << 17;
            s3 ^= s;
            s4 ^= s2;
            s2 ^= s3;
            s ^= s4;
            s3 ^= num;
            s4 = BitOperations.RotateLeft(s4, 45);
            _s0 = s;
            _s1 = s2;
            _s2 = s3;
            _s3 = s4;
            return result;
        }
References System.Random.XoshiroImpl._s0, System.Random.XoshiroImpl._s1, System.Random.XoshiroImpl._s2, System.Random.XoshiroImpl._s3, System.Numerics.BitOperations.RotateLeft(), and System.s.
Referenced by System.Random.XoshiroImpl.Next(), System.Random.XoshiroImpl.Next(), System.Random.XoshiroImpl.Next(), System.Random.XoshiroImpl.NextDouble(), System.Random.XoshiroImpl.NextInt64(), System.Random.XoshiroImpl.NextInt64(), System.Random.XoshiroImpl.NextInt64(), System.Random.XoshiroImpl.NextSingle(), and System.Random.XoshiroImpl.NextUInt32().