Terraria: System.Net.TaskExtensions.ToApm< TResult >
ToApm< TResult >()
static TaskCompletionSource< TResult > System.Net.TaskExtensions.ToApm< TResult > (this Task< TResult > task, AsyncCallback callback, object state) inline static
Definition at line 8 of file TaskExtensions.cs.
    {
        TaskCompletionSource<TResult> tcs = new TaskCompletionSource<TResult>(state);
        task.ContinueWith(delegate(Task<TResult> completedTask)
        {
            bool flag = false;
            flag = (completedTask.IsFaulted ? tcs.TrySetException(completedTask.Exception.InnerExceptions) : ((!completedTask.IsCanceled) ? tcs.TrySetResult(completedTask.Result) : tcs.TrySetCanceled()));
            if (flag && callback != null)
            {
                callback(tcs.Task);
            }
        }, CancellationToken.None, TaskContinuationOptions.None, TaskScheduler.Default);
        return tcs;
    }
References System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Exception, System.AggregateException.InnerExceptions, System.Threading.Tasks.Task< TResult >.IsCanceled, System.Threading.CancellationToken.None, System.Threading.Tasks.Task< TResult >.Result, System.state, System.Threading.Tasks.TaskCompletionSource< TResult >.Task, System.task, System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetCanceled(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetException(), and System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetResult().