Terraria: Terraria.GameContent.Animations.Segments.PlayerSegment.Draw
Draw()
override void Terraria.GameContent.Animations.Segments.PlayerSegment.Draw (ref GameAnimationSegment info) inline
Definition at line 170 of file Segments.cs.
        {
            if ((float)info.TimeInAnimation > (float)_targetTime + base.DedicatedTimeNeeded || info.TimeInAnimation < _targetTime)
            {
                return;
            }
            ResetPlayerAnimation(ref info);
            float localTimeForObject = info.TimeInAnimation - _targetTime;
            ProcessActions(_player, localTimeForObject);
            if (info.DisplayOpacity != 0f)
            {
                _player.ResetEffects();
                _player.ResetVisibleAccessories();
                _player.UpdateMiscCounter();
                _player.UpdateDyes();
                _player.PlayerFrame();
                _player.socialIgnoreLight = true;
                _player.position += Main.screenPosition;
                _player.position -= new Vector2(_player.width / 2, _player.height);
                _player.opacityForAnimation *= info.DisplayOpacity;
                Item item = _player.inventory[_player.selectedItem];
                _player.inventory[_player.selectedItem] = _blankItem;
                float num = 1f - _player.opacityForAnimation;
                num = 0f;
                if (_shaderEffect != null)
                {
                    _shaderEffect.BeforeDrawing(ref info);
                }
                Main.PlayerRenderer.DrawPlayer(Main.Camera, _player, _player.position, 0f, _player.fullRotationOrigin, num);
                if (_shaderEffect != null)
                {
                    _shaderEffect.AfterDrawing(ref info);
                }
                _player.inventory[_player.selectedItem] = item;
            }
        }
References Terraria.GameContent.Animations.Segments.PlayerSegment._blankItem, Terraria.GameContent.Animations.Segments.PlayerSegment._player, Terraria.GameContent.Animations.Segments.PlayerSegment._shaderEffect, Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< Player >._targetTime, Terraria.GameContent.Animations.Segments.PlayerSegment.IShaderEffect.AfterDrawing(), Terraria.GameContent.Animations.Segments.PlayerSegment.IShaderEffect.BeforeDrawing(), Terraria.Main.Camera, Terraria.Player.fullRotationOrigin, Terraria.Entity.height, Terraria.Player.inventory, Terraria.Player.opacityForAnimation, Terraria.Player.PlayerFrame(), Terraria.Main.PlayerRenderer, Terraria.Entity.position, Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< Player >.ProcessActions(), Terraria.Player.ResetEffects(), Terraria.GameContent.Animations.Segments.PlayerSegment.ResetPlayerAnimation(), Terraria.Player.ResetVisibleAccessories(), Terraria.Main.screenPosition, Terraria.Player.selectedItem, Terraria.Player.UpdateDyes(), Terraria.Player.UpdateMiscCounter(), Microsoft.Xna.Framework.Graphics.Vector2, and Terraria.Entity.width.