Terraria: UISearchBar.SetContents
SetContents()
void UISearchBar.SetContents (string contents, bool forced = false) inline
     {
         if (!(actualContents == contents) || forced)
         {
             actualContents = contents;
             if (string.IsNullOrEmpty(actualContents))
             {
                 _text.TextColor = Color.Gray;
                 _text.SetText(_textToShowWhenEmpty.Value, _textScale, large: false);
             }
             else
             {
                 _text.TextColor = Color.White;
                 _text.SetText(actualContents);
                 actualContents = _text.Text;
             }
             TrimDisplayIfOverElementDimensions(0);
             if (this.OnContentsChanged != null)
             {
                 this.OnContentsChanged(contents);
             }
         }
     }
References _text, _textScale, _textToShowWhenEmpty, actualContents, Color, OnContentsChanged, UITextBox.SetText(), UITextPanel< T >.Text, UITextPanel< T >.TextColor, TrimDisplayIfOverElementDimensions(), and LocalizedText.Value.
Referenced by UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents(), UIBestiaryTest.BuildPage(), DrawSelf(), UICreativeInfiniteItemsDisplay.OnFinishedSettingName(), UIBestiaryTest.OnFinishedSettingName(), UICreativeInfiniteItemsDisplay.searchCancelButton_OnClick(), and UIBestiaryTest.searchCancelButton_OnClick().