Terraria: UISearchBar.ToggleTakingText
ToggleTakingText()
void UISearchBar.ToggleTakingText () inline
     {
         isWritingText = !isWritingText;
         _text.ShowInputTicker = isWritingText;
         Main.clrInput();
         if (isWritingText)
         {
             if (this.OnStartTakingInput != null)
             {
                 this.OnStartTakingInput();
             }
         }
         else if (this.OnEndTakingInput != null)
         {
             this.OnEndTakingInput();
         }
     }
References _text, Main.clrInput(), isWritingText, OnEndTakingInput, OnStartTakingInput, and UITextBox.ShowInputTicker.
Referenced by UICreativeInfiniteItemsDisplay.Click_SearchArea(), UIBestiaryTest.Click_SearchArea(), DrawSelf(), UICreativeInfiniteItemsDisplay.EscapeVirtualKeyboard(), UICreativeInfiniteItemsDisplay.GoBackHere(), UIBestiaryTest.GoBackHere(), UICreativeInfiniteItemsDisplay.Update(), and UIBestiaryTest.Update().