Terraria: System.Xml.ValidateNames.ValidateNameInternal
ValidateNameInternal()
static bool System.Xml.ValidateNames.ValidateNameInternal (string prefix, string localName, string ns, XPathNodeType nodeKind, Flags flags, bool throwOnError) inline static private
Definition at line 273 of file ValidateNames.cs.
    {
        if ((flags & Flags.NCNames) != 0)
        {
            if (prefix.Length != 0 && !ParseNCNameInternal(prefix, throwOnError))
            {
                return false;
            }
            if (localName.Length != 0 && !ParseNCNameInternal(localName, throwOnError))
            {
                return false;
            }
        }
        if ((flags & Flags.CheckLocalName) != 0)
        {
            if (nodeKind != XPathNodeType.Element)
            {
                if (nodeKind != XPathNodeType.Attribute)
                {
                    if (nodeKind == XPathNodeType.ProcessingInstruction)
                    {
                        if (localName.Length == 0 || (localName.Length == 3 && StartsWithXml(localName)))
{
                            if (throwOnError)
{
                                throw new XmlException(System.SR.Xml_InvalidPIName, localName);
                            }
                            return false;
                        }
                    }
                    else if (localName.Length != 0)
                    {
                        if (throwOnError)
{
                            throw new XmlException(System.SR.XmlNoNameAllowed, nodeKind.ToString());
                        }
                        return false;
                    }
                    goto IL_00fa;
                }
                if (ns.Length == 0 && localName.Equals("xmlns"))
                {
                    if (throwOnError)
                    {
                        throw new XmlException(System.SR.XmlBadName, new string[2]
{
                            nodeKind.ToString(),
                            localName
                        });
                    }
                    return false;
                }
            }
            if (localName.Length == 0)
            {
                if (throwOnError)
                {
                    throw new XmlException(System.SR.Xdom_Empty_LocalName, string.Empty);
                }
                return false;
            }
        }
        goto IL_00fa;
        IL_00fa:
        if ((flags & Flags.CheckPrefixMapping) != 0)
        {
            switch (nodeKind)
            {
            case XPathNodeType.Element:
            case XPathNodeType.Attribute:
            case XPathNodeType.Namespace:
                if (ns.Length == 0)
                {
                    if (prefix.Length != 0)
                    {
                        if (throwOnError)
{
                            throw new XmlException(System.SR.Xml_PrefixForEmptyNs, string.Empty);
                        }
                        return false;
                    }
                    break;
                }
                if (prefix.Length == 0 && nodeKind == XPathNodeType.Attribute)
                {
                    if (throwOnError)
                    {
                        throw new XmlException(System.SR.XmlBadName, new string[2]
{
                            nodeKind.ToString(),
                            localName
                        });
                    }
                    return false;
                }
                if (prefix.Equals("xml"))
                {
                    if (!ns.Equals("http://www.w3.org/XML/1998/namespace"))
                    {
                        if (throwOnError)
{
                            throw new XmlException(System.SR.Xml_XmlPrefix, string.Empty);
                        }
                        return false;
                    }
                    break;
                }
                if (prefix.Equals("xmlns"))
                {
                    if (throwOnError)
                    {
                        throw new XmlException(System.SR.Xml_XmlnsPrefix, string.Empty);
                    }
                    return false;
                }
                if (IsReservedNamespace(ns))
                {
                    if (throwOnError)
                    {
                        throw new XmlException(System.SR.Xml_NamespaceDeclXmlXmlns, string.Empty);
                    }
                    return false;
                }
                break;
            case XPathNodeType.ProcessingInstruction:
                if (prefix.Length != 0 || ns.Length != 0)
                {
                    if (throwOnError)
                    {
                        throw new XmlException(System.SR.Xml_InvalidPIName, CreateName(prefix, localName));
                    }
                    return false;
                }
                break;
            default:
                if (prefix.Length != 0 || ns.Length != 0)
                {
                    if (throwOnError)
                    {
                        throw new XmlException(System.SR.XmlNoNameAllowed, nodeKind.ToString());
                    }
                    return false;
                }
                break;
            }
        }
        return true;
    }
References System.Xml.ValidateNames.CreateName(), System.Xml.Dictionary, System.Xml.ValidateNames.IsReservedNamespace(), System.Xml.ValidateNames.ParseNCNameInternal(), System.prefix, System.Xml.ValidateNames.StartsWithXml(), System.SR.Xdom_Empty_LocalName, System.SR.Xml_InvalidPIName, System.SR.Xml_NamespaceDeclXmlXmlns, System.SR.Xml_PrefixForEmptyNs, System.SR.Xml_XmlnsPrefix, System.SR.Xml_XmlPrefix, System.SR.XmlBadName, System.Xml.XmlException, and System.SR.XmlNoNameAllowed.
Referenced by System.Xml.ValidateNames.ValidateName(), and System.Xml.ValidateNames.ValidateNameThrow().