Terraria: System.Linq.Expressions.Interpreter.InterpretedFrame.Push
Push() [4/7]
void System.Linq.Expressions.Interpreter.InterpretedFrame.Push (object value) inline
Definition at line 55 of file InterpretedFrame.cs.
    {
        Data[StackIndex++] = value;
    }
References System.Linq.Expressions.Interpreter.InterpretedFrame.StackIndex, and System.value.
Referenced by System.Linq.Expressions.Interpreter.CastInstruction.CastInstructionNoT.Ref.ConvertNull(), System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.FilterPasses(), System.Linq.Expressions.Interpreter.InterpretedFrame.PushPendingContinuation(), System.Linq.Expressions.Interpreter.AndInstruction.AndSByte.Run(), System.Linq.Expressions.Interpreter.AndInstruction.AndInt16.Run(), System.Linq.Expressions.Interpreter.AndInstruction.AndInt32.Run(), System.Linq.Expressions.Interpreter.AndInstruction.AndInt64.Run(), System.Linq.Expressions.Interpreter.AndInstruction.AndByte.Run(), System.Linq.Expressions.Interpreter.AndInstruction.AndUInt16.Run(), System.Linq.Expressions.Interpreter.AndInstruction.AndUInt32.Run(), System.Linq.Expressions.Interpreter.AndInstruction.AndUInt64.Run(), System.Linq.Expressions.Interpreter.AndInstruction.AndBoolean.Run(), System.Linq.Expressions.Interpreter.ArrayLengthInstruction.Run(), System.Linq.Expressions.Interpreter.CastInstruction.CastInstructionT< T >.Run(), System.Linq.Expressions.Interpreter.CastInstruction.CastInstructionNoT.Run(), System.Linq.Expressions.Interpreter.CastReferenceToEnumInstruction.Run(), System.Linq.Expressions.Interpreter.CastToEnumInstruction.Run(), System.Linq.Expressions.Interpreter.CreateDelegateInstruction.Run(), System.Linq.Expressions.Interpreter.DecrementInstruction.DecrementInt16.Run(), System.Linq.Expressions.Interpreter.DecrementInstruction.DecrementInt32.Run(), System.Linq.Expressions.Interpreter.DecrementInstruction.DecrementInt64.Run(), System.Linq.Expressions.Interpreter.DecrementInstruction.DecrementUInt16.Run(), System.Linq.Expressions.Interpreter.DecrementInstruction.DecrementUInt32.Run(), System.Linq.Expressions.Interpreter.DecrementInstruction.DecrementUInt64.Run(), System.Linq.Expressions.Interpreter.DecrementInstruction.DecrementSingle.Run(), System.Linq.Expressions.Interpreter.DecrementInstruction.DecrementDouble.Run(), System.Linq.Expressions.Interpreter.DefaultValueInstruction.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualBoolean.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualSByte.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualInt16.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualChar.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualInt32.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualInt64.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualByte.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualUInt16.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualUInt32.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualUInt64.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualSingle.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualDouble.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualReference.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualBooleanLiftedToNull.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualSByteLiftedToNull.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualInt16LiftedToNull.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualCharLiftedToNull.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualInt32LiftedToNull.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualInt64LiftedToNull.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualByteLiftedToNull.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualUInt16LiftedToNull.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualUInt32LiftedToNull.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualUInt64LiftedToNull.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualSingleLiftedToNull.Run(), System.Linq.Expressions.Interpreter.EqualInstruction.EqualDoubleLiftedToNull.Run(), System.Linq.Expressions.Interpreter.ExclusiveOrInstruction.ExclusiveOrSByte.Run(), System.Linq.Expressions.Interpreter.ExclusiveOrInstruction.ExclusiveOrInt16.Run(), System.Linq.Expressions.Interpreter.ExclusiveOrInstruction.ExclusiveOrInt32.Run(), System.Linq.Expressions.Interpreter.ExclusiveOrInstruction.ExclusiveOrInt64.Run(), System.Linq.Expressions.Interpreter.ExclusiveOrInstruction.ExclusiveOrByte.Run(), System.Linq.Expressions.Interpreter.ExclusiveOrInstruction.ExclusiveOrUInt16.Run(), System.Linq.Expressions.Interpreter.ExclusiveOrInstruction.ExclusiveOrUInt32.Run(), System.Linq.Expressions.Interpreter.ExclusiveOrInstruction.ExclusiveOrUInt64.Run(), System.Linq.Expressions.Interpreter.ExclusiveOrInstruction.ExclusiveOrBoolean.Run(), System.Linq.Expressions.Interpreter.GetArrayItemInstruction.Run(), System.Linq.Expressions.Interpreter.GreaterThanInstruction.GreaterThanSByte.Run(), System.Linq.Expressions.Interpreter.GreaterThanInstruction.GreaterThanInt16.Run(), System.Linq.Expressions.Interpreter.GreaterThanInstruction.GreaterThanChar.Run(), System.Linq.Expressions.Interpreter.GreaterThanInstruction.GreaterThanInt32.Run(), System.Linq.Expressions.Interpreter.GreaterThanInstruction.GreaterThanInt64.Run(), System.Linq.Expressions.Interpreter.GreaterThanInstruction.GreaterThanByte.Run(), System.Linq.Expressions.Interpreter.GreaterThanInstruction.GreaterThanUInt16.Run(), System.Linq.Expressions.Interpreter.GreaterThanInstruction.GreaterThanUInt32.Run(), System.Linq.Expressions.Interpreter.GreaterThanInstruction.GreaterThanUInt64.Run(), System.Linq.Expressions.Interpreter.GreaterThanInstruction.GreaterThanSingle.Run(), System.Linq.Expressions.Interpreter.GreaterThanInstruction.GreaterThanDouble.Run(), System.Linq.Expressions.Interpreter.GreaterThanOrEqualInstruction.GreaterThanOrEqualSByte.Run(), System.Linq.Expressions.Interpreter.GreaterThanOrEqualInstruction.GreaterThanOrEqualInt16.Run(), System.Linq.Expressions.Interpreter.GreaterThanOrEqualInstruction.GreaterThanOrEqualChar.Run(), System.Linq.Expressions.Interpreter.GreaterThanOrEqualInstruction.GreaterThanOrEqualInt32.Run(), System.Linq.Expressions.Interpreter.GreaterThanOrEqualInstruction.GreaterThanOrEqualInt64.Run(), System.Linq.Expressions.Interpreter.GreaterThanOrEqualInstruction.GreaterThanOrEqualByte.Run(), System.Linq.Expressions.Interpreter.GreaterThanOrEqualInstruction.GreaterThanOrEqualUInt16.Run(), System.Linq.Expressions.Interpreter.GreaterThanOrEqualInstruction.GreaterThanOrEqualUInt32.Run(), System.Linq.Expressions.Interpreter.GreaterThanOrEqualInstruction.GreaterThanOrEqualUInt64.Run(), System.Linq.Expressions.Interpreter.GreaterThanOrEqualInstruction.GreaterThanOrEqualSingle.Run(), System.Linq.Expressions.Interpreter.GreaterThanOrEqualInstruction.GreaterThanOrEqualDouble.Run(), System.Linq.Expressions.Interpreter.IncrementInstruction.IncrementInt16.Run(), System.Linq.Expressions.Interpreter.IncrementInstruction.IncrementInt32.Run(), System.Linq.Expressions.Interpreter.IncrementInstruction.IncrementInt64.Run(), System.Linq.Expressions.Interpreter.IncrementInstruction.IncrementUInt16.Run(), System.Linq.Expressions.Interpreter.IncrementInstruction.IncrementUInt32.Run(), System.Linq.Expressions.Interpreter.IncrementInstruction.IncrementUInt64.Run(), System.Linq.Expressions.Interpreter.IncrementInstruction.IncrementSingle.Run(), System.Linq.Expressions.Interpreter.IncrementInstruction.IncrementDouble.Run(), System.Linq.Expressions.Interpreter.LeftShiftInstruction.LeftShiftSByte.Run(), System.Linq.Expressions.Interpreter.LeftShiftInstruction.LeftShiftInt16.Run(), System.Linq.Expressions.Interpreter.LeftShiftInstruction.LeftShiftInt32.Run(), System.Linq.Expressions.Interpreter.LeftShiftInstruction.LeftShiftInt64.Run(), System.Linq.Expressions.Interpreter.LeftShiftInstruction.LeftShiftByte.Run(), System.Linq.Expressions.Interpreter.LeftShiftInstruction.LeftShiftUInt16.Run(), System.Linq.Expressions.Interpreter.LeftShiftInstruction.LeftShiftUInt32.Run(), System.Linq.Expressions.Interpreter.LeftShiftInstruction.LeftShiftUInt64.Run(), System.Linq.Expressions.Interpreter.LessThanInstruction.LessThanSByte.Run(), System.Linq.Expressions.Interpreter.LessThanInstruction.LessThanInt16.Run(), System.Linq.Expressions.Interpreter.LessThanInstruction.LessThanChar.Run(), System.Linq.Expressions.Interpreter.LessThanInstruction.LessThanInt32.Run(), System.Linq.Expressions.Interpreter.LessThanInstruction.LessThanInt64.Run(), System.Linq.Expressions.Interpreter.LessThanInstruction.LessThanByte.Run(), System.Linq.Expressions.Interpreter.LessThanInstruction.LessThanUInt16.Run(), System.Linq.Expressions.Interpreter.LessThanInstruction.LessThanUInt32.Run(), System.Linq.Expressions.Interpreter.LessThanInstruction.LessThanUInt64.Run(), System.Linq.Expressions.Interpreter.LessThanInstruction.LessThanSingle.Run(), System.Linq.Expressions.Interpreter.LessThanInstruction.LessThanDouble.Run(), System.Linq.Expressions.Interpreter.LessThanOrEqualInstruction.LessThanOrEqualSByte.Run(), System.Linq.Expressions.Interpreter.LessThanOrEqualInstruction.LessThanOrEqualInt16.Run(), System.Linq.Expressions.Interpreter.LessThanOrEqualInstruction.LessThanOrEqualChar.Run(), System.Linq.Expressions.Interpreter.LessThanOrEqualInstruction.LessThanOrEqualInt32.Run(), System.Linq.Expressions.Interpreter.LessThanOrEqualInstruction.LessThanOrEqualInt64.Run(), System.Linq.Expressions.Interpreter.LessThanOrEqualInstruction.LessThanOrEqualByte.Run(), System.Linq.Expressions.Interpreter.LessThanOrEqualInstruction.LessThanOrEqualUInt16.Run(), System.Linq.Expressions.Interpreter.LessThanOrEqualInstruction.LessThanOrEqualUInt32.Run(), System.Linq.Expressions.Interpreter.LessThanOrEqualInstruction.LessThanOrEqualUInt64.Run(), System.Linq.Expressions.Interpreter.LessThanOrEqualInstruction.LessThanOrEqualSingle.Run(), System.Linq.Expressions.Interpreter.LessThanOrEqualInstruction.LessThanOrEqualDouble.Run(), System.Linq.Expressions.Interpreter.LoadFieldInstruction.Run(), System.Linq.Expressions.Interpreter.LoadStaticFieldInstruction.Run(), System.Linq.Expressions.Interpreter.NegateCheckedInstruction.NegateCheckedInt32.Run(), System.Linq.Expressions.Interpreter.NegateCheckedInstruction.NegateCheckedInt16.Run(), System.Linq.Expressions.Interpreter.NegateCheckedInstruction.NegateCheckedInt64.Run(), System.Linq.Expressions.Interpreter.NegateInstruction.NegateInt16.Run(), System.Linq.Expressions.Interpreter.NegateInstruction.NegateInt32.Run(), System.Linq.Expressions.Interpreter.NegateInstruction.NegateInt64.Run(), System.Linq.Expressions.Interpreter.NegateInstruction.NegateSingle.Run(), System.Linq.Expressions.Interpreter.NegateInstruction.NegateDouble.Run(), System.Linq.Expressions.Interpreter.NewArrayBoundsInstruction.Run(), System.Linq.Expressions.Interpreter.NewArrayInitInstruction.Run(), System.Linq.Expressions.Interpreter.NewArrayInstruction.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualBoolean.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualSByte.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualInt16.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualChar.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualInt32.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualInt64.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualByte.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualUInt16.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualUInt32.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualUInt64.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualSingle.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualDouble.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualReference.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualSByteLiftedToNull.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualInt16LiftedToNull.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualCharLiftedToNull.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualInt32LiftedToNull.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualInt64LiftedToNull.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualByteLiftedToNull.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualUInt16LiftedToNull.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualUInt32LiftedToNull.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualUInt64LiftedToNull.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualSingleLiftedToNull.Run(), System.Linq.Expressions.Interpreter.NotEqualInstruction.NotEqualDoubleLiftedToNull.Run(), System.Linq.Expressions.Interpreter.NotInstruction.NotBoolean.Run(), System.Linq.Expressions.Interpreter.NotInstruction.NotInt64.Run(), System.Linq.Expressions.Interpreter.NotInstruction.NotInt32.Run(), System.Linq.Expressions.Interpreter.NotInstruction.NotInt16.Run(), System.Linq.Expressions.Interpreter.NotInstruction.NotUInt64.Run(), System.Linq.Expressions.Interpreter.NotInstruction.NotUInt32.Run(), System.Linq.Expressions.Interpreter.NotInstruction.NotUInt16.Run(), System.Linq.Expressions.Interpreter.NotInstruction.NotByte.Run(), System.Linq.Expressions.Interpreter.NotInstruction.NotSByte.Run(), System.Linq.Expressions.Interpreter.NullableMethodCallInstruction.HasValue.Run(), System.Linq.Expressions.Interpreter.NullableMethodCallInstruction.GetValueOrDefault.Run(), System.Linq.Expressions.Interpreter.NullableMethodCallInstruction.GetValueOrDefault1.Run(), System.Linq.Expressions.Interpreter.NullableMethodCallInstruction.EqualsClass.Run(), System.Linq.Expressions.Interpreter.NullableMethodCallInstruction.ToStringClass.Run(), System.Linq.Expressions.Interpreter.NullableMethodCallInstruction.GetHashCodeClass.Run(), System.Linq.Expressions.Interpreter.NumericConvertInstruction.Run(), System.Linq.Expressions.Interpreter.OrInstruction.OrSByte.Run(), System.Linq.Expressions.Interpreter.OrInstruction.OrInt16.Run(), System.Linq.Expressions.Interpreter.OrInstruction.OrInt32.Run(), System.Linq.Expressions.Interpreter.OrInstruction.OrInt64.Run(), System.Linq.Expressions.Interpreter.OrInstruction.OrByte.Run(), System.Linq.Expressions.Interpreter.OrInstruction.OrUInt16.Run(), System.Linq.Expressions.Interpreter.OrInstruction.OrUInt32.Run(), System.Linq.Expressions.Interpreter.OrInstruction.OrUInt64.Run(), System.Linq.Expressions.Interpreter.OrInstruction.OrBoolean.Run(), System.Linq.Expressions.Interpreter.QuoteInstruction.Run(), System.Linq.Expressions.Interpreter.RightShiftInstruction.RightShiftSByte.Run(), System.Linq.Expressions.Interpreter.RightShiftInstruction.RightShiftInt16.Run(), System.Linq.Expressions.Interpreter.RightShiftInstruction.RightShiftInt32.Run(), System.Linq.Expressions.Interpreter.RightShiftInstruction.RightShiftInt64.Run(), System.Linq.Expressions.Interpreter.RightShiftInstruction.RightShiftByte.Run(), System.Linq.Expressions.Interpreter.RightShiftInstruction.RightShiftUInt16.Run(), System.Linq.Expressions.Interpreter.RightShiftInstruction.RightShiftUInt32.Run(), System.Linq.Expressions.Interpreter.RightShiftInstruction.RightShiftUInt64.Run(), System.Linq.Expressions.Interpreter.RuntimeVariablesInstruction.Run(), System.Linq.Expressions.Interpreter.TypeAsInstruction.Run(), System.Linq.Expressions.Interpreter.TypeEqualsInstruction.Run(), System.Linq.Expressions.Interpreter.TypeIsInstruction.Run(), and System.Linq.Expressions.Interpreter.ValueTypeCopyInstruction.Run().