Terraria: System.Xml.ValidateNames.ThrowInvalidName
ThrowInvalidName()
static void System.Xml.ValidateNames.ThrowInvalidName (string s, int offsetStartChar, int offsetBadChar) inline static package
Definition at line 207 of file ValidateNames.cs.
    {
        if (offsetStartChar >= s.Length)
        {
            throw new XmlException(System.SR.Format(System.SR.Xml_EmptyName, string.Empty));
        }
        if (XmlCharType.IsNCNameSingleChar(s[offsetBadChar]) && !XmlCharType.IsStartNCNameSingleChar(s[offsetBadChar]))
        {
            throw new XmlException(System.SR.Xml_BadStartNameChar, XmlException.BuildCharExceptionArgs(s, offsetBadChar));
        }
        throw new XmlException(System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(s, offsetBadChar));
    }
References System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.XmlCharType.IsStartNCNameSingleChar(), System.s, System.SR.Xml_BadNameChar, System.SR.Xml_BadStartNameChar, System.SR.Xml_EmptyName, and System.Xml.XmlException.
Referenced by System.Xml.ValidateNames.ParseNameTestThrow(), System.Xml.ValidateNames.ParseNCNameInternal(), and System.Xml.ValidateNames.ParseQNameThrow().