Terraria: System.Xml.ValidateNames.ParseNameTestThrow
ParseNameTestThrow()
static void System.Xml.ValidateNames.ParseNameTestThrow (string s, out string prefix, out string localName) inline static package
Definition at line 158 of file ValidateNames.cs.
    {
        int num;
        if (s.Length != 0 && s[0] == '*')
        {
            prefix = (localName = null);
            num = 1;
        }
        else
        {
            num = ParseNCName(s, 0);
            if (num != 0)
            {
                localName = s.Substring(0, num);
                if (num < s.Length && s[num] == ':')
                {
                    prefix = localName;
                    int num2 = num + 1;
                    if (num2 < s.Length && s[num2] == '*')
                    {
                        localName = null;
                        num += 2;
                    }
                    else
                    {
                        int num3 = ParseNCName(s, num2);
                        if (num3 != 0)
{
                            localName = s.Substring(num2, num3);
                            num += num3 + 1;
                        }
                    }
                }
                else
                {
                    prefix = string.Empty;
                }
            }
            else
            {
                prefix = (localName = null);
            }
        }
        if (num == 0 || num != s.Length)
        {
            ThrowInvalidName(s, 0, num);
        }
    }
References System.Xml.Dictionary, System.Xml.ValidateNames.ParseNCName(), System.prefix, System.s, and System.Xml.ValidateNames.ThrowInvalidName().
Referenced by System.Xml.Xsl.Xslt.Compiler.ParseNameTest().