Terraria: System.Xml.ValidateNames.SplitQName
SplitQName()
static void System.Xml.ValidateNames.SplitQName (string name, out string prefix, out string lname) inline static package
Definition at line 431 of file ValidateNames.cs.
    {
        int num = name.IndexOf(':');
        if (-1 == num)
        {
            prefix = string.Empty;
            lname = name;
            return;
        }
        if (num == 0 || name.Length - 1 == num)
        {
            string xml_BadNameChar = System.SR.Xml_BadNameChar;
            object[] args = XmlException.BuildCharExceptionArgs(':', '\0');
            throw new ArgumentException(System.SR.Format(xml_BadNameChar, args), "name");
        }
        prefix = name.Substring(0, num);
        num++;
        lname = name.Substring(num, name.Length - num);
    }
References System.Xml.ArgumentException, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.Dictionary, System.SR.Format(), System.prefix, and System.SR.Xml_BadNameChar.
Referenced by System.Xml.XPath.XPathNavigatorReader.GetAttribute(), System.Xml.XsdValidatingReader.GetAttributePSVI(), System.Xml.XsdValidatingReader.GetDefaultAttribute(), System.Xml.XmlSqlBinaryReader.LocateAttribute(), and System.Xml.XPath.XPathNavigatorReader.MoveToAttribute().