Terraria: System.Linq.Expressions.Interpreter.InterpretedFrame.Goto
Goto()
int System.Linq.Expressions.Interpreter.InterpretedFrame.Goto (int labelIndex, object value, bool gotoExceptionHandler) inline
Definition at line 198 of file InterpretedFrame.cs.
    {
        RuntimeLabel runtimeLabel = Interpreter._labels[labelIndex];
        if (_continuationIndex == runtimeLabel.ContinuationStackDepth)
        {
            SetStackDepth(runtimeLabel.StackDepth);
            if (value != Interpreter.NoValue)
            {
                Data[StackIndex - 1] = value;
            }
            return runtimeLabel.Index - InstructionIndex;
        }
        _pendingContinuation = labelIndex;
        _pendingValue = value;
        return YieldToCurrentContinuation();
    }
References System.Linq.Expressions.Interpreter.InterpretedFrame._continuationIndex, System.Linq.Expressions.Interpreter.Interpreter._labels, System.Linq.Expressions.Interpreter.InterpretedFrame._pendingContinuation, System.Linq.Expressions.Interpreter.InterpretedFrame._pendingValue, System.Linq.Expressions.Interpreter.InterpretedFrame.InstructionIndex, System.Linq.Expressions.Interpreter.Interpreter.NoValue, System.Linq.Expressions.Interpreter.InterpretedFrame.SetStackDepth(), System.Linq.Expressions.Interpreter.InterpretedFrame.StackIndex, System.value, and System.Linq.Expressions.Interpreter.InterpretedFrame.YieldToCurrentContinuation().
Referenced by System.Linq.Expressions.Interpreter.EnterTryCatchFinallyInstruction.Run(), and System.Linq.Expressions.Interpreter.GotoInstruction.Run().