Terraria: MS.Internal.Xml.XPath.ExtensionQuery.ProcessResult
ProcessResult()
object MS.Internal.Xml.XPath.ExtensionQuery.ProcessResult (object value) inline protected inherited
Definition at line 107 of file ExtensionQuery.cs.
    {
        if (value is string)
        {
            return value;
        }
        if (value is double)
        {
            return value;
        }
        if (value is bool)
        {
            return value;
        }
        if (value is XPathNavigator)
        {
            return value;
        }
        if (value is int)
        {
            return (double)(int)value;
        }
        if (value == null)
        {
            _queryIterator = XPathEmptyIterator.Instance;
            return this;
        }
        if (value is ResetableIterator resetableIterator)
        {
            _queryIterator = (ResetableIterator)resetableIterator.Clone();
            return this;
        }
        if (value is XPathNodeIterator nodeIterator)
        {
            _queryIterator = new XPathArrayIterator(nodeIterator);
            return this;
        }
        if (value is IXPathNavigable iXPathNavigable)
        {
            return iXPathNavigable.CreateNavigator();
        }
        if (value is short)
        {
            return (double)(short)value;
        }
        if (value is long)
        {
            return (double)(long)value;
        }
        if (value is uint)
        {
            return (double)(uint)value;
        }
        if (value is ushort)
        {
            return (double)(int)(ushort)value;
        }
        if (value is ulong)
        {
            return (double)(ulong)value;
        }
        if (value is float)
        {
            return (double)(float)value;
        }
        if (value is decimal)
        {
            return (double)(decimal)value;
        }
        return value.ToString();
    }
References MS.Internal.Xml.XPath.ResetableIterator.ResetableIterator(), MS.Internal.Xml.XPath.ExtensionQuery._queryIterator, System.Xml.XPath.XPathNodeIterator.Clone(), MS.Internal.Xml.XPath.XPathEmptyIterator.Instance, and System.value.
Referenced by MS.Internal.Xml.XPath.FunctionQuery.Evaluate(), and MS.Internal.Xml.XPath.VariableQuery.Evaluate().