Terraria: MS.Internal.Xml.XPath.ExtensionQuery.Advance
Advance()
override XPathNavigator MS.Internal.Xml.XPath.ExtensionQuery.Advance () inline inherited
Definition at line 94 of file ExtensionQuery.cs.
    {
        if (_queryIterator == null)
        {
            throw XPathException.Create(System.SR.Xp_NodeSetExpected);
        }
        if (_queryIterator.MoveNext())
        {
            return _queryIterator.Current;
        }
        return null;
    }
References MS.Internal.Xml.XPath.ExtensionQuery._queryIterator, System.Xml.XPath.XPathException.Create(), System.Xml.XPath.XPathNodeIterator.Current, System.Xml.XPath.XPathNodeIterator.MoveNext(), and System.SR.Xp_NodeSetExpected.
Referenced by MS.Internal.Xml.XPath.FunctionQuery.MatchNode().