Terraria: System.Xml.ValidateNames.ParseQNameThrow
ParseQNameThrow() [1/2]
static int System.Xml.ValidateNames.ParseQNameThrow (string s) inline static package
Definition at line 132 of file ValidateNames.cs.
    {
        int colonOffset;
        int num = ParseQName(s, 0, out colonOffset);
        if (num == 0 || num != s.Length)
        {
            ThrowInvalidName(s, 0, num);
        }
        return colonOffset;
    }
References System.Xml.Dictionary, System.Xml.ValidateNames.ParseQName(), System.s, and System.Xml.ValidateNames.ThrowInvalidName().
Referenced by System.Xml.XmlQualifiedName.Parse(), System.Xml.Xsl.Xslt.Compiler.ParseQName(), System.Xml.ValidateNames.ParseQNameThrow(), System.Xml.Xsl.Runtime.XmlQueryRuntime.ParseTagName(), System.Xml.Xsl.Runtime.XmlQueryRuntime.ParseTagName(), System.Xml.Schema.XmlBaseConverter.StringToQName(), System.Xml.Schema.XmlUntypedStringConverter.StringToQName(), System.Xml.XmlCharCheckingReader.ValidateQName(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed().