Terraria: System.Linq.Expressions.Interpreter.InterpretedFrame.PushPendingContinuation
PushPendingContinuation()
void System.Linq.Expressions.Interpreter.InterpretedFrame.PushPendingContinuation () inline package
Definition at line 184 of file InterpretedFrame.cs.
    {
        Push(_pendingContinuation);
        Push(_pendingValue);
        _pendingContinuation = -1;
        _pendingValue = Interpreter.NoValue;
    }
References System.Linq.Expressions.Interpreter.InterpretedFrame._pendingContinuation, System.Linq.Expressions.Interpreter.InterpretedFrame._pendingValue, System.Linq.Expressions.Interpreter.Interpreter.NoValue, and System.Linq.Expressions.Interpreter.InterpretedFrame.Push().
Referenced by System.Linq.Expressions.Interpreter.EnterFaultInstruction.Run(), and System.Linq.Expressions.Interpreter.EnterFinallyInstruction.Run().