Terraria: BigProgressBarHelper.DrawFancyBar
DrawFancyBar() [1/2]
static void BigProgressBarHelper.DrawFancyBar (SpriteBatch spriteBatch, float lifeAmount, float lifeMax, Texture2D barIconTexture, Rectangle barIconFrame) inline static
     {
         Texture2D value = Main.Assets.Request<Texture2D>("Images/UI/UI_BossBar", (AssetRequestMode)1).Value;
         Point p = new Point(456, 22);
         Point p2 = new Point(32, 24);
         int verticalFrames = 6;
         Rectangle value2 = value.Frame(1, verticalFrames, 0, 3);
         Color color = Color.White * 0.2f;
         float num = lifeAmount / lifeMax;
         int num2 = (int)((float)p.X * num);
         num2 -= num2 % 2;
         Rectangle value3 = value.Frame(1, verticalFrames, 0, 2);
         value3.X += p2.X;
         value3.Y += p2.Y;
         value3.Width = 2;
         value3.Height = p.Y;
         Rectangle value4 = value.Frame(1, verticalFrames, 0, 1);
         value4.X += p2.X;
         value4.Y += p2.Y;
         value4.Width = 2;
         value4.Height = p.Y;
         Rectangle rectangle = Utils.CenteredRectangle(Main.ScreenSize.ToVector2() * new Vector2(0.5f, 1f) + new Vector2(0f, -50f), p.ToVector2());
         Vector2 vector = rectangle.TopLeft() - p2.ToVector2();
         spriteBatch.Draw(value, vector, value2, color, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
         spriteBatch.Draw(value, rectangle.TopLeft(), value3, Color.White, 0f, Vector2.Zero, new Vector2(num2 / value3.Width, 1f), SpriteEffects.None, 0f);
         spriteBatch.Draw(value, rectangle.TopLeft() + new Vector2(num2 - 2, 0f), value4, Color.White, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
         Rectangle value5 = value.Frame(1, verticalFrames);
         spriteBatch.Draw(value, vector, value5, Color.White, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
         Vector2 vector2 = new Vector2(4f, 20f) + new Vector2(26f, 28f) / 2f;
         spriteBatch.Draw(barIconTexture, vector + vector2, barIconFrame, Color.White, 0f, barIconFrame.Size() / 2f, 1f, SpriteEffects.None, 0f);
         if (BigProgressBarSystem.ShowText)
         {
             DrawHealthText(spriteBatch, rectangle, lifeAmount, lifeMax);
         }
     }
References Main.Assets, Utils.CenteredRectangle(), Color, DrawHealthText(), Main.ScreenSize, and BigProgressBarSystem.ShowText.
Referenced by BrainOfCthuluBigProgressBar.Draw(), CommonBossBigProgressBar.Draw(), DeerclopsBigProgressBar.Draw(), EaterOfWorldsProgressBar.Draw(), GolemHeadProgressBar.Draw(), LunarPillarBigProgessBar.Draw(), MartianSaucerBigProgressBar.Draw(), MoonLordProgressBar.Draw(), PirateShipBigProgressBar.Draw(), and TwinsBigProgressBar.Draw().