Terraria: System.Xml.ValueHandle.TryReadBase64
TryReadBase64()
bool System.Xml.ValueHandle.TryReadBase64 (byte[] buffer, int offset, int count, out int actual) inline
Definition at line 630 of file ValueHandle.cs.
    {
        if (_type == ValueHandleType.Base64)
        {
            actual = Math.Min(_length, count);
            GetBase64(buffer, offset, actual);
            _offset += actual;
            _length -= actual;
            return true;
        }
        if (_type == ValueHandleType.UTF8 && count >= 3 && _length % 4 == 0)
        {
            try
            {
                int num = Math.Min(count / 3 * 4, _length);
                actual = Base64Encoding.GetBytes(_bufferReader.Buffer, _offset, num, buffer, offset);
                _offset += num;
                _length -= num;
                return true;
            }
            catch (FormatException)
            {
            }
        }
        actual = 0;
        return false;
    }
References System.Xml.ValueHandle._bufferReader, System.Xml.ValueHandle._length, System.Xml.ValueHandle._offset, System.Xml.ValueHandle._type, System.buffer, System.Xml.XmlBufferReader.Buffer, System.count, System.Xml.Dictionary, System.Xml.ValueHandle.GetBase64(), System.Text.Base64Encoding.GetBytes(), System.Math.Min(), and System.offset.
Referenced by System.Xml.XmlBaseReader.ReadContentAsBase64(), and System.Xml.XmlBaseReader.ReadValueAsBase64().