Terraria: System.Xml.ValueHandle.TryReadChars
TryReadChars()
bool System.Xml.ValueHandle.TryReadChars (char[] chars, int offset, int count, out int actual) inline
Definition at line 658 of file ValueHandle.cs.
    {
        if (_type == ValueHandleType.Unicode)
        {
            return TryReadUnicodeChars(chars, offset, count, out actual);
        }
        if (_type != ValueHandleType.UTF8)
        {
            actual = 0;
            return false;
        }
        int num = offset;
        int num2 = count;
        byte[] buffer = _bufferReader.Buffer;
        int num3 = _offset;
        int num4 = _length;
        bool flag = false;
        UTF8Encoding uTF8Encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true);
        while (true)
        {
            if (num2 > 0 && num4 > 0)
            {
                byte b = buffer[num3];
                if (b < 128)
                {
                    chars[num] = (char)b;
                    num3++;
                    num4--;
                    num++;
                    num2--;
                    continue;
                }
            }
            if (num2 == 0 || num4 == 0 || flag)
            {
                break;
            }
            int chars2;
            int num5;
            try
            {
                if (num2 >= uTF8Encoding.GetMaxCharCount(num4) || num2 >= uTF8Encoding.GetCharCount(buffer, num3, num4))
                {
                    chars2 = uTF8Encoding.GetChars(buffer, num3, num4, chars, num);
                    num5 = num4;
                }
                else
                {
                    Decoder decoder = uTF8Encoding.GetDecoder();
                    num5 = Math.Min(num2, num4);
                    chars2 = decoder.GetChars(buffer, num3, num5, chars, num);
                    while (chars2 == 0)
                    {
                        if (num5 >= 3 && num2 < 2)
{
                            flag = true;
                            break;
                        }
                        chars2 = decoder.GetChars(buffer, num3 + num5, 1, chars, num);
                        num5++;
                    }
                    num5 = uTF8Encoding.GetByteCount(chars, num, chars2);
                }
            }
            catch (FormatException exception)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateEncodingException(buffer, num3, num4, exception));
            }
            num3 += num5;
            num4 -= num5;
            num += chars2;
            num2 -= chars2;
        }
        _offset = num3;
        _length = num4;
        actual = count - num2;
        return true;
    }
References System.Xml.ValueHandle._bufferReader, System.Xml.ValueHandle._length, System.Xml.ValueHandle._offset, System.Xml.ValueHandle._type, System.buffer, System.Xml.XmlBufferReader.Buffer, System.chars, System.count, System.Xml.XmlExceptionHelper.CreateEncodingException(), System.Xml.Dictionary, System.exception, System.Text.Decoder.GetChars(), System.Math.Min(), System.offset, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Xml.ValueHandle.TryReadUnicodeChars().
Referenced by System.Xml.XmlBaseReader.ReadValueChunk().