Terraria: System.Xml.ValueHandle.GetDictionaryString
GetDictionaryString()
XmlDictionaryString System.Xml.ValueHandle.GetDictionaryString () inline private
Definition at line 863 of file ValueHandle.cs.
    {
        return _bufferReader.GetDictionaryString(_offset);
    }
References System.Xml.ValueHandle._bufferReader, System.Xml.ValueHandle._offset, and System.Xml.XmlBufferReader.GetDictionaryString().
Referenced by System.Xml.ValueHandle.GetString(), and System.Xml.ValueHandle.TryGetDictionaryString().