Terraria: System.Xml.ValueHandle.ToDouble
ToDouble()
double System.Xml.ValueHandle.ToDouble () inline
Definition at line 299 of file ValueHandle.cs.
    {
        return _type switch
        {
            ValueHandleType.Double => GetDouble(),
            ValueHandleType.Single => GetSingle(),
            ValueHandleType.Zero => 0.0,
            ValueHandleType.One => 1.0,
            ValueHandleType.Int8 => GetInt8(),
            ValueHandleType.Int16 => GetInt16(),
            ValueHandleType.Int32 => GetInt32(),
            ValueHandleType.UTF8 => XmlConverter.ToDouble(_bufferReader.Buffer, _offset, _length),
            _ => XmlConverter.ToDouble(GetString()),
        };
    }
References System.Xml.ValueHandle._bufferReader, System.Xml.ValueHandle._length, System.Xml.ValueHandle._offset, System.Xml.ValueHandle._type, System.Xml.XmlBufferReader.Buffer, System.Xml.Dictionary, System.Xml.ValueHandle.GetDouble(), System.Xml.ValueHandle.GetInt16(), System.Xml.ValueHandle.GetInt32(), System.Xml.ValueHandle.GetInt8(), System.Xml.ValueHandle.GetSingle(), System.Xml.ValueHandle.GetString(), and System.Xml.XmlConverter.ToDouble().
Referenced by System.Xml.XmlBaseReader.ReadContentAsDouble(), and System.Xml.ValueHandle.ToObject().