Terraria: System.Xml.ValueHandle.Sign
Sign()
void System.Xml.ValueHandle.Sign (XmlSigningNodeWriter writer) inline
Definition at line 527 of file ValueHandle.cs.
    {
        switch (_type)
        {
        case ValueHandleType.Int8:
        case ValueHandleType.Int16:
        case ValueHandleType.Int32:
            writer.WriteInt32Text(ToInt());
            break;
        case ValueHandleType.Int64:
            writer.WriteInt64Text(GetInt64());
            break;
        case ValueHandleType.UInt64:
            writer.WriteUInt64Text(GetUInt64());
            break;
        case ValueHandleType.Single:
            writer.WriteFloatText(GetSingle());
            break;
        case ValueHandleType.Double:
            writer.WriteDoubleText(GetDouble());
            break;
        case ValueHandleType.Decimal:
            writer.WriteDecimalText(GetDecimal());
            break;
        case ValueHandleType.DateTime:
            writer.WriteDateTimeText(ToDateTime());
            break;
        case ValueHandleType.UTF8:
            writer.WriteEscapedText(_bufferReader.Buffer, _offset, _length);
            break;
        case ValueHandleType.Base64:
            writer.WriteBase64Text(_bufferReader.Buffer, 0, _bufferReader.Buffer, _offset, _length);
            break;
        case ValueHandleType.UniqueId:
            writer.WriteUniqueIdText(ToUniqueId());
            break;
        case ValueHandleType.Guid:
            writer.WriteGuidText(ToGuid());
            break;
        case ValueHandleType.TimeSpan:
            writer.WriteTimeSpanText(ToTimeSpan());
            break;
        default:
            writer.WriteEscapedText(GetString());
            break;
        case ValueHandleType.Empty:
            break;
        }
    }
References System.Xml.ValueHandle._bufferReader, System.Xml.ValueHandle._length, System.Xml.ValueHandle._offset, System.Xml.ValueHandle._type, System.Xml.XmlBufferReader.Buffer, System.Xml.ValueHandle.GetDecimal(), System.Xml.ValueHandle.GetDouble(), System.Xml.ValueHandle.GetInt64(), System.Xml.ValueHandle.GetSingle(), System.Xml.ValueHandle.GetString(), System.Xml.ValueHandle.GetUInt64(), System.Xml.ValueHandle.ToDateTime(), System.Xml.ValueHandle.ToGuid(), System.Xml.ValueHandle.ToInt(), System.Xml.ValueHandle.ToTimeSpan(), System.Xml.ValueHandle.ToUniqueId(), and System.writer.
Referenced by System.Xml.XmlBaseReader.SignNode().