Terraria: System.Xml.ValueHandle.GetInt16
GetInt16()
int System.Xml.ValueHandle.GetInt16 () inline private
Definition at line 813 of file ValueHandle.cs.
    {
        return _bufferReader.GetInt16(_offset);
    }
References System.Xml.ValueHandle._bufferReader, System.Xml.ValueHandle._offset, and System.Xml.XmlBufferReader.GetInt16().
Referenced by System.Xml.ValueHandle.ToDouble(), System.Xml.ValueHandle.ToInt(), System.Xml.ValueHandle.ToLong(), and System.Xml.ValueHandle.ToSingle().