Terraria: System.Xml.ValueHandle.ToByteArray
ToByteArray()
byte[] System.Xml.ValueHandle.ToByteArray () inline
Definition at line 398 of file ValueHandle.cs.
    {
        if (_type == ValueHandleType.Base64)
        {
            byte[] array = new byte[_length];
            GetBase64(array, 0, _length);
            return array;
        }
        if (_type == ValueHandleType.UTF8 && _length % 4 == 0)
        {
            try
            {
                int num = _length / 4 * 3;
                if (_length > 0 && _bufferReader.Buffer[_offset + _length - 1] == 61)
                {
                    num--;
                    if (_bufferReader.Buffer[_offset + _length - 2] == 61)
                    {
                        num--;
                    }
                }
                byte[] array2 = new byte[num];
                int bytes = Base64Encoding.GetBytes(_bufferReader.Buffer, _offset, _length, array2, 0);
                if (bytes != array2.Length)
                {
                    byte[] array3 = new byte[bytes];
                    Buffer.BlockCopy(array2, 0, array3, 0, bytes);
                    array2 = array3;
                }
                return array2;
            }
            catch (FormatException)
            {
            }
        }
        try
        {
            return Base64Encoding.GetBytes(XmlConverter.StripWhitespace(GetString()));
        }
        catch (FormatException ex2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new XmlException(ex2.Message, ex2.InnerException));
        }
    }
References System.Xml.ValueHandle._bufferReader, System.Xml.ValueHandle._length, System.Xml.ValueHandle._offset, System.Xml.ValueHandle._type, System.array, System.Buffer.BlockCopy(), System.Xml.XmlBufferReader.Buffer, System.bytes, System.Xml.Dictionary, System.Xml.ValueHandle.GetBase64(), System.Text.Base64Encoding.GetBytes(), System.Xml.ValueHandle.GetString(), System.Xml.XmlConverter.StripWhitespace(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Xml.XmlException.
Referenced by System.Xml.ValueHandle.GetString(), System.Xml.XmlBaseReader.ReadContentAsBase64(), and System.Xml.ValueHandle.ToObject().