Terraria: System.Xml.ValueHandle.ToObject
ToObject()
object System.Xml.ValueHandle.ToObject () inline
Definition at line 582 of file ValueHandle.cs.
    {
        switch (_type)
        {
        case ValueHandleType.True:
        case ValueHandleType.False:
            return ToBoolean();
        case ValueHandleType.Zero:
        case ValueHandleType.One:
        case ValueHandleType.Int8:
        case ValueHandleType.Int16:
        case ValueHandleType.Int32:
            return ToInt();
        case ValueHandleType.Int64:
            return ToLong();
        case ValueHandleType.UInt64:
            return GetUInt64();
        case ValueHandleType.Single:
            return ToSingle();
        case ValueHandleType.Double:
            return ToDouble();
        case ValueHandleType.Decimal:
            return ToDecimal();
        case ValueHandleType.DateTime:
            return ToDateTime();
        case ValueHandleType.Empty:
        case ValueHandleType.UTF8:
        case ValueHandleType.EscapedUTF8:
        case ValueHandleType.Dictionary:
        case ValueHandleType.Char:
        case ValueHandleType.Unicode:
        case ValueHandleType.ConstString:
            return ToString();
        case ValueHandleType.Base64:
            return ToByteArray();
        case ValueHandleType.List:
            return ToList();
        case ValueHandleType.UniqueId:
            return ToUniqueId();
        case ValueHandleType.Guid:
            return ToGuid();
        case ValueHandleType.TimeSpan:
            return ToTimeSpan();
        default:
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException());
        }
    }
References System.Xml.ValueHandle._type, System.Xml.ValueHandle.GetUInt64(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.ValueHandle.ToBoolean(), System.Xml.ValueHandle.ToByteArray(), System.Xml.ValueHandle.ToDateTime(), System.Xml.ValueHandle.ToDecimal(), System.Xml.ValueHandle.ToDouble(), System.Xml.ValueHandle.ToGuid(), System.Xml.ValueHandle.ToInt(), System.Xml.ValueHandle.ToList(), System.Xml.ValueHandle.ToLong(), System.Xml.ValueHandle.ToSingle(), System.Xml.ValueHandle.ToString(), System.Xml.ValueHandle.ToTimeSpan(), and System.Xml.ValueHandle.ToUniqueId().
Referenced by System.Xml.XmlBufferReader.GetList(), and System.Xml.XmlBaseReader.ReadContentAsObject().