Terraria: System.Xml.ValueHandle.ToSingle
ToSingle()
float System.Xml.ValueHandle.ToSingle () inline
Definition at line 271 of file ValueHandle.cs.
    {
        ValueHandleType type = _type;
        switch (type)
        {
        case ValueHandleType.Single:
            return GetSingle();
        case ValueHandleType.Double:
        {
            double @double = GetDouble();
            if ((@double >= -3.4028234663852886E+38 && @double <= 3.4028234663852886E+38) || !double.IsFinite(@double))
            {
                return (float)@double;
            }
            break;
        }
        }
        return type switch
        {
            ValueHandleType.Zero => 0f,
            ValueHandleType.One => 1f,
            ValueHandleType.Int8 => GetInt8(),
            ValueHandleType.Int16 => GetInt16(),
            ValueHandleType.UTF8 => XmlConverter.ToSingle(_bufferReader.Buffer, _offset, _length),
            _ => XmlConverter.ToSingle(GetString()),
        };
    }
References System.Xml.ValueHandle._bufferReader, System.Xml.ValueHandle._length, System.Xml.ValueHandle._offset, System.Xml.ValueHandle._type, System.Xml.XmlBufferReader.Buffer, System.Xml.Dictionary, System.Xml.E, System.Xml.ValueHandle.GetDouble(), System.Xml.ValueHandle.GetInt16(), System.Xml.ValueHandle.GetInt8(), System.Xml.ValueHandle.GetSingle(), System.Xml.ValueHandle.GetString(), System.Xml.XmlConverter.ToSingle(), and System.type.
Referenced by System.Xml.XmlBaseReader.ReadContentAsFloat(), and System.Xml.ValueHandle.ToObject().