Terraria: System.Xml.ValueHandle.SetValue
SetValue() [1/2]
void System.Xml.ValueHandle.SetValue (ValueHandleType type) inline
Definition at line 35 of file ValueHandle.cs.
    {
        _type = type;
    }
References System.Xml.ValueHandle._type, and System.type.
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.Read(), System.Xml.XmlUTF8TextReader.ReadCData(), System.Xml.XmlUTF8TextReader.ReadComment(), System.Xml.XmlBinaryReader.ReadNode(), System.Runtime.Serialization.Json.XmlJsonReader.ReadNumericalText(), System.Xml.XmlBinaryReader.ReadPartialUnicodeText(), System.Xml.XmlBinaryReader.ReadPartialUTF8Text(), System.Runtime.Serialization.Json.XmlJsonReader.ReadQuotedText(), System.Xml.XmlUTF8TextReader.ReadText(), System.Xml.XmlUTF8TextReader.ReadWhitespace(), System.Xml.ValueHandle.SetCharValue(), System.Xml.ValueHandle.SetDictionaryValue(), and System.Xml.ValueHandle.SetQNameValue().