Terraria: System.Xml.ValueHandle.GetString
GetString()
string System.Xml.ValueHandle.GetString () inline
Definition at line 443 of file ValueHandle.cs.
    {
        switch (_type)
        {
        case ValueHandleType.UTF8:
            return GetCharsText();
        case ValueHandleType.False:
            return "false";
        case ValueHandleType.True:
            return "true";
        case ValueHandleType.Zero:
            return "0";
        case ValueHandleType.One:
            return "1";
        case ValueHandleType.Int8:
        case ValueHandleType.Int16:
        case ValueHandleType.Int32:
            return XmlConverter.ToString(ToInt());
        case ValueHandleType.Int64:
            return XmlConverter.ToString(GetInt64());
        case ValueHandleType.UInt64:
            return XmlConverter.ToString(GetUInt64());
        case ValueHandleType.Single:
            return XmlConverter.ToString(GetSingle());
        case ValueHandleType.Double:
            return XmlConverter.ToString(GetDouble());
        case ValueHandleType.Decimal:
            return XmlConverter.ToString(GetDecimal());
        case ValueHandleType.DateTime:
            return XmlConverter.ToString(ToDateTime());
        case ValueHandleType.Empty:
            return string.Empty;
        case ValueHandleType.Unicode:
            return GetUnicodeCharsText();
        case ValueHandleType.EscapedUTF8:
            return GetEscapedCharsText();
        case ValueHandleType.Char:
            return GetCharText();
        case ValueHandleType.Dictionary:
            return GetDictionaryString().Value;
        case ValueHandleType.Base64:
        {
            byte[] array = ToByteArray();
            return Base64Encoding.GetString(array, 0, array.Length);
        }
        case ValueHandleType.List:
            return XmlConverter.ToString(ToList());
        case ValueHandleType.UniqueId:
            return XmlConverter.ToString(ToUniqueId());
        case ValueHandleType.Guid:
            return XmlConverter.ToString(ToGuid());
        case ValueHandleType.TimeSpan:
            return XmlConverter.ToString(ToTimeSpan());
        case ValueHandleType.QName:
            return GetQNameDictionaryText();
        case ValueHandleType.ConstString:
            return s_constStrings[_offset];
        default:
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException());
        }
    }
References System.Xml.ValueHandle._offset, System.Xml.ValueHandle._type, System.array, System.Xml.ValueHandle.GetCharsText(), System.Xml.ValueHandle.GetCharText(), System.Xml.ValueHandle.GetDecimal(), System.Xml.ValueHandle.GetDictionaryString(), System.Xml.ValueHandle.GetDouble(), System.Xml.ValueHandle.GetEscapedCharsText(), System.Xml.ValueHandle.GetInt64(), System.Xml.ValueHandle.GetQNameDictionaryText(), System.Xml.ValueHandle.GetSingle(), System.Text.Encoding.GetString(), System.Xml.ValueHandle.GetUInt64(), System.Xml.ValueHandle.GetUnicodeCharsText(), System.Xml.ValueHandle.s_constStrings, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.ValueHandle.ToByteArray(), System.Xml.ValueHandle.ToDateTime(), System.Xml.ValueHandle.ToGuid(), System.Xml.ValueHandle.ToInt(), System.Xml.ValueHandle.ToList(), System.Xml.XmlConverter.ToString(), System.Xml.ValueHandle.ToTimeSpan(), System.Xml.ValueHandle.ToUniqueId(), and System.Xml.XmlDictionaryString.Value.
Referenced by System.Xml.ValueHandle.Equals2(), System.Xml.ValueHandle.Sign(), System.Xml.XmlBaseReader.SignNode(), System.Xml.ValueHandle.ToBoolean(), System.Xml.ValueHandle.ToByteArray(), System.Xml.ValueHandle.ToDateTime(), System.Xml.ValueHandle.ToDecimal(), System.Xml.ValueHandle.ToDouble(), System.Xml.ValueHandle.ToGuid(), System.Xml.ValueHandle.ToInt(), System.Xml.ValueHandle.ToLong(), System.Xml.ValueHandle.ToSingle(), System.Xml.ValueHandle.ToString(), System.Xml.ValueHandle.ToTimeSpan(), System.Xml.ValueHandle.ToULong(), and System.Xml.ValueHandle.ToUniqueId().