Terraria: System.Xml.ValueHandle.ToDateTime
ToDateTime()
DateTime System.Xml.ValueHandle.ToDateTime () inline
Definition at line 341 of file ValueHandle.cs.
    {
        if (_type == ValueHandleType.DateTime)
        {
            return XmlConverter.ToDateTime(GetInt64());
        }
        if (_type == ValueHandleType.UTF8)
        {
            return XmlConverter.ToDateTime(_bufferReader.Buffer, _offset, _length);
        }
        return XmlConverter.ToDateTime(GetString());
    }
References System.Xml.ValueHandle._bufferReader, System.Xml.ValueHandle._length, System.Xml.ValueHandle._offset, System.Xml.ValueHandle._type, System.Xml.XmlBufferReader.Buffer, System.Xml.ValueHandle.GetInt64(), System.Xml.ValueHandle.GetString(), and System.Xml.XmlConverter.ToDateTime().
Referenced by System.Xml.ValueHandle.GetString(), System.Xml.ValueHandle.Sign(), and System.Xml.ValueHandle.ToObject().