Terraria: System.Formats.Asn1.AsnWriter.WriteTag
WriteTag()
void System.Formats.Asn1.AsnWriter.WriteTag (Asn1Tag tag) inline private
Definition at line 261 of file AsnWriter.cs.
    {
        int num = tag.CalculateEncodedSize();
        EnsureWriteCapacity(num);
        if (!tag.TryEncode(_buffer.AsSpan(_offset, num), out var bytesWritten) || bytesWritten != num)
        {
            throw new InvalidOperationException();
        }
        _offset += num;
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.Formats.Asn1.Asn1Tag.CalculateEncodedSize(), System.Formats.Asn1.AsnWriter.EnsureWriteCapacity(), and System.Formats.Asn1.Asn1Tag.TryEncode().
Referenced by System.Formats.Asn1.AsnWriter.PushTag(), System.Formats.Asn1.AsnWriter.WriteBitStringCore(), System.Formats.Asn1.AsnWriter.WriteBooleanCore(), System.Formats.Asn1.AsnWriter.WriteCharacterStringCore(), System.Formats.Asn1.AsnWriter.WriteConstructedCerBitString(), System.Formats.Asn1.AsnWriter.WriteConstructedCerOctetString(), System.Formats.Asn1.AsnWriter.WriteGeneralizedTimeCore(), System.Formats.Asn1.AsnWriter.WriteIntegerCore(), System.Formats.Asn1.AsnWriter.WriteIntegerCore(), System.Formats.Asn1.AsnWriter.WriteIntegerCore(), System.Formats.Asn1.AsnWriter.WriteIntegerUnsignedCore(), System.Formats.Asn1.AsnWriter.WriteNonNegativeIntegerCore(), System.Formats.Asn1.AsnWriter.WriteNullCore(), System.Formats.Asn1.AsnWriter.WriteObjectIdentifierCore(), System.Formats.Asn1.AsnWriter.WriteOctetStringCore(), and System.Formats.Asn1.AsnWriter.WriteUtcTimeCore().