Terraria: System.Formats.Asn1.AsnWriter.WriteIntegerUnsignedCore
WriteIntegerUnsignedCore()
void System.Formats.Asn1.AsnWriter.WriteIntegerUnsignedCore (Asn1Tag tag, ReadOnlySpan< byte > value) inline private
Definition at line 735 of file AsnWriter.cs.
    {
        if (value.IsEmpty)
        {
            throw new ArgumentException(System.SR.Argument_IntegerCannotBeEmpty, "value");
        }
        if (value.Length > 1 && value[0] == 0 && value[1] < 128)
        {
            throw new ArgumentException(System.SR.Argument_IntegerRedundantByte, "value");
        }
        WriteTag(tag);
        if (value[0] >= 128)
        {
            WriteLength(checked(value.Length + 1));
            _buffer[_offset] = 0;
            _offset++;
        }
        else
        {
            WriteLength(value.Length);
        }
        value.CopyTo(_buffer.AsSpan(_offset));
        _offset += value.Length;
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.SR.Argument_IntegerCannotBeEmpty, System.SR.Argument_IntegerRedundantByte, System.value, System.Formats.Asn1.AsnWriter.WriteLength(), and System.Formats.Asn1.AsnWriter.WriteTag().
Referenced by System.Formats.Asn1.AsnWriter.WriteIntegerUnsigned().