Terraria: System.Formats.Asn1.AsnWriter.WriteConstructedCerBitString
WriteConstructedCerBitString()
void System.Formats.Asn1.AsnWriter.WriteConstructedCerBitString (Asn1Tag tag, ReadOnlySpan< byte > payload, int unusedBitCount) inline private
Definition at line 533 of file AsnWriter.cs.
    {
        int pendingCount = DetermineCerBitStringTotalLength(tag, payload.Length);
        EnsureWriteCapacity(pendingCount);
        int offset = _offset;
        WriteTag(tag.AsConstructed());
        WriteLength(-1);
        byte[] buffer = _buffer;
        ReadOnlySpan<byte> readOnlySpan = payload;
        Asn1Tag primitiveBitString = Asn1Tag.PrimitiveBitString;
        Span<byte> destination;
        while (readOnlySpan.Length > 999)
        {
            WriteTag(primitiveBitString);
            WriteLength(1000);
            _buffer[_offset] = 0;
            _offset++;
            destination = _buffer.AsSpan(_offset);
            readOnlySpan.Slice(0, 999).CopyTo(destination);
            readOnlySpan = readOnlySpan.Slice(999);
            _offset += 999;
        }
        WriteTag(primitiveBitString);
        WriteLength(readOnlySpan.Length + 1);
        _buffer[_offset] = (byte)unusedBitCount;
        _offset++;
        destination = _buffer.AsSpan(_offset);
        readOnlySpan.CopyTo(destination);
        _offset += readOnlySpan.Length;
        WriteEndOfContents();
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.Formats.Asn1.Asn1Tag.AsConstructed(), System.buffer, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.destination, System.Formats.Asn1.AsnWriter.DetermineCerBitStringTotalLength(), System.Formats.Asn1.AsnWriter.EnsureWriteCapacity(), System.offset, System.Formats.Asn1.Asn1Tag.PrimitiveBitString, System.Formats.Asn1.AsnWriter.WriteEndOfContents(), System.Formats.Asn1.AsnWriter.WriteLength(), and System.Formats.Asn1.AsnWriter.WriteTag().
Referenced by System.Formats.Asn1.AsnWriter.WriteBitStringCore().