Terraria: System.Formats.Asn1.AsnWriter.WriteBitArray
WriteBitArray()
void System.Formats.Asn1.AsnWriter.WriteBitArray (BitArray value, Asn1Tag? tag) inline private
Definition at line 863 of file AsnWriter.cs.
    {
        if (value.Count == 0)
        {
            WriteBitString(ReadOnlySpan<byte>.Empty, 0, tag);
            return;
        }
        int num = checked(value.Count + 7) / 8;
        int unusedBitCount = num * 8 - value.Count;
        byte[] array = System.Security.Cryptography.CryptoPool.Rent(num);
        value.CopyTo(array, 0);
        Span<byte> span = array.AsSpan(0, num);
        AsnDecoder.ReverseBitsPerByte(span);
        WriteBitString(span, unusedBitCount, tag);
        System.Security.Cryptography.CryptoPool.Return(array, num);
    }
References System.array, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Formats.Asn1.AsnDecoder.ReverseBitsPerByte(), System.value, and System.Formats.Asn1.AsnWriter.WriteBitString().
Referenced by System.Formats.Asn1.AsnWriter.WriteNamedBitList().