Terraria: System.Formats.Asn1.AsnWriter.WriteGeneralizedTimeCore
WriteGeneralizedTimeCore()
void System.Formats.Asn1.AsnWriter.WriteGeneralizedTimeCore (Asn1Tag tag, DateTimeOffset value, bool omitFractionalSeconds) inline private
Definition at line 619 of file AsnWriter.cs.
    {
        DateTimeOffset dateTimeOffset = value.ToUniversalTime();
        if (dateTimeOffset.Year > 9999)
        {
            throw new ArgumentOutOfRangeException("value");
        }
        Span<byte> destination = default(Span<byte>);
        if (!omitFractionalSeconds)
        {
            long num = dateTimeOffset.Ticks % 10000000;
            if (num != 0L)
            {
                destination = stackalloc byte[9];
                decimal value2 = num;
                value2 /= 10000000m;
                if (!Utf8Formatter.TryFormat(value2, destination, out var bytesWritten, new StandardFormat('G')))
                {
                    throw new InvalidOperationException();
                }
                destination = destination.Slice(1, bytesWritten - 1);
            }
        }
        int length = 15 + destination.Length;
        WriteTag(tag);
        WriteLength(length);
        int year = dateTimeOffset.Year;
        int month = dateTimeOffset.Month;
        int day = dateTimeOffset.Day;
        int hour = dateTimeOffset.Hour;
        int minute = dateTimeOffset.Minute;
        int second = dateTimeOffset.Second;
        Span<byte> span = _buffer.AsSpan(_offset);
        StandardFormat format = new StandardFormat('D', 4);
        StandardFormat format2 = new StandardFormat('D', 2);
        if (!Utf8Formatter.TryFormat(year, span.Slice(0, 4), out var bytesWritten2, format) || !Utf8Formatter.TryFormat(month, span.Slice(4, 2), out bytesWritten2, format2) || !Utf8Formatter.TryFormat(day, span.Slice(6, 2), out bytesWritten2, format2) || !Utf8Formatter.TryFormat(hour, span.Slice(8, 2), out bytesWritten2, format2) || !Utf8Formatter.TryFormat(minute, span.Slice(10, 2), out bytesWritten2, format2) || !Utf8Formatter.TryFormat(second, span.Slice(12, 2), out bytesWritten2, format2))
        {
            throw new InvalidOperationException();
        }
        _offset += 14;
        destination.CopyTo(span.Slice(14));
        _offset += destination.Length;
        _buffer[_offset] = 90;
        _offset++;
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.destination, System.format, System.L, System.length, System.Buffers.Text.Utf8Formatter.TryFormat(), System.value, System.Formats.Asn1.AsnWriter.WriteLength(), System.Formats.Asn1.AsnWriter.WriteTag(), and System.year.
Referenced by System.Formats.Asn1.AsnWriter.WriteGeneralizedTime().