Terraria: System.Formats.Asn1.AsnWriter.WriteNonNegativeIntegerCore
WriteNonNegativeIntegerCore()
void System.Formats.Asn1.AsnWriter.WriteNonNegativeIntegerCore (Asn1Tag tag, ulong value) inline private
Definition at line 718 of file AsnWriter.cs.
    {
        int num = ((value < 128) ? 1 : ((value < 32768) ? 2 : ((value < 8388608) ? 3 : ((value < 2147483648u) ? 4 : ((value < 549755813888L) ? 5 : ((value < 140737488355328L) ? 6 : ((value < 36028797018963968L) ? 7 : ((value >= 9223372036854775808uL) ? 9 : 8))))))));
        WriteTag(tag);
        WriteLength(num);
        ulong num2 = value;
        int num3 = _offset + num - 1;
        do
        {
            _buffer[num3] = (byte)num2;
            num2 >>= 8;
            num3--;
        }
        while (num3 >= _offset);
        _offset += num;
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.L, System.value, System.Formats.Asn1.AsnWriter.WriteLength(), and System.Formats.Asn1.AsnWriter.WriteTag().
Referenced by System.Formats.Asn1.AsnWriter.WriteEnumeratedValue(), System.Formats.Asn1.AsnWriter.WriteInteger(), and System.Formats.Asn1.AsnWriter.WriteIntegerCore().