Terraria: System.Formats.Asn1.AsnWriter.PopSequence
PopSequence()
void System.Formats.Asn1.AsnWriter.PopSequence (Asn1Tag? tag = null) inline
Definition at line 1078 of file AsnWriter.cs.
    {
        CheckUniversalTag(tag, UniversalTagNumber.Sequence);
        PopSequenceCore(tag?.AsConstructed() ?? Asn1Tag.Sequence);
    }
References System.Formats.Asn1.AsnWriter.CheckUniversalTag(), System.Formats.Asn1.AsnWriter.PopSequenceCore(), and System.Formats.Asn1.Asn1Tag.Sequence.
Referenced by System.Formats.Asn1.AsnWriter.Scope.Dispose(), System.Security.Cryptography.X509Certificates.ECDsaX509SignatureGenerator.GetSignatureAlgorithmIdentifier(), System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.GetSignatureAlgorithmIdentifier(), System.Security.Cryptography.EccKeyFormatHelper.WriteEcPrivateKey(), System.Security.Cryptography.KeyFormatHelper.WriteEncryptedPkcs8(), Internal.Cryptography.AsymmetricAlgorithmHelpers.WriteIeee1363ToDer(), System.Security.Cryptography.RSAKeyFormatHelper.WritePkcs1PrivateKey(), System.Security.Cryptography.RSAKeyFormatHelper.WritePkcs1PublicKey(), System.Security.Cryptography.KeyFormatHelper.WritePkcs8(), System.Security.Cryptography.DSAKeyFormatHelper.WritePkcs8(), System.Security.Cryptography.EccKeyFormatHelper.WriteSubjectPublicKeyInfo(), System.Security.Cryptography.DSAKeyFormatHelper.WriteSubjectPublicKeyInfo(), and System.Security.Cryptography.RSAKeyFormatHelper.WriteSubjectPublicKeyInfo().