Terraria: System.Formats.Asn1.AsnWriter.PopSetOf
PopSetOf()
void System.Formats.Asn1.AsnWriter.PopSetOf (Asn1Tag? tag = null) inline
Definition at line 1100 of file AsnWriter.cs.
    {
        CheckUniversalTag(tag, UniversalTagNumber.Set);
        PopSetOfCore(tag?.AsConstructed() ?? Asn1Tag.SetOf);
    }
References System.Formats.Asn1.AsnWriter.CheckUniversalTag(), System.Formats.Asn1.AsnWriter.PopSetOfCore(), and System.Formats.Asn1.Asn1Tag.SetOf.
Referenced by System.Formats.Asn1.AsnWriter.Scope.Dispose(), System.Security.Cryptography.EccKeyFormatHelper.WritePrivateKeyInfoAttributes(), and System.Security.Cryptography.EccKeyFormatHelper.WritePrivateKeyInfoAttributes().