Terraria: System.Formats.Asn1.AsnWriter.WriteUtcTimeCore
WriteUtcTimeCore()
void System.Formats.Asn1.AsnWriter.WriteUtcTimeCore (Asn1Tag tag, DateTimeOffset value) inline private
Definition at line 1181 of file AsnWriter.cs.
    {
        WriteTag(tag);
        WriteLength(13);
        DateTimeOffset dateTimeOffset = value.ToUniversalTime();
        int year = dateTimeOffset.Year;
        int month = dateTimeOffset.Month;
        int day = dateTimeOffset.Day;
        int hour = dateTimeOffset.Hour;
        int minute = dateTimeOffset.Minute;
        int second = dateTimeOffset.Second;
        Span<byte> span = _buffer.AsSpan(_offset);
        StandardFormat format = new StandardFormat('D', 2);
        if (!Utf8Formatter.TryFormat(year % 100, span.Slice(0, 2), out var bytesWritten, format) || !Utf8Formatter.TryFormat(month, span.Slice(2, 2), out bytesWritten, format) || !Utf8Formatter.TryFormat(day, span.Slice(4, 2), out bytesWritten, format) || !Utf8Formatter.TryFormat(hour, span.Slice(6, 2), out bytesWritten, format) || !Utf8Formatter.TryFormat(minute, span.Slice(8, 2), out bytesWritten, format) || !Utf8Formatter.TryFormat(second, span.Slice(10, 2), out bytesWritten, format))
        {
            throw new InvalidOperationException();
        }
        _buffer[_offset + 12] = 90;
        _offset += 13;
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.format, System.Buffers.Text.Utf8Formatter.TryFormat(), System.value, System.Formats.Asn1.AsnWriter.WriteLength(), System.Formats.Asn1.AsnWriter.WriteTag(), and System.year.
Referenced by System.Formats.Asn1.AsnWriter.WriteUtcTime(), and System.Formats.Asn1.AsnWriter.WriteUtcTime().