Terraria: System.Formats.Asn1.AsnWriter.SortContents
SortContents()
static void System.Formats.Asn1.AsnWriter.SortContents (byte[] buffer, int start, int end) inline static private
Definition at line 430 of file AsnWriter.cs.
    {
        int num = end - start;
        if (num == 0)
        {
            return;
        }
        AsnReader asnReader = new AsnReader(new ReadOnlyMemory<byte>(buffer, start, num), AsnEncodingRules.BER);
        List<(int, int)> list = new List<(int, int)>();
        int num2 = start;
        while (asnReader.HasData)
        {
            ReadOnlyMemory<byte> readOnlyMemory = asnReader.ReadEncodedValue();
            list.Add((num2, readOnlyMemory.Length));
            num2 += readOnlyMemory.Length;
        }
        ArrayIndexSetOfValueComparer comparer = new ArrayIndexSetOfValueComparer(buffer);
        list.Sort(comparer);
        byte[] array = System.Security.Cryptography.CryptoPool.Rent(num);
        num2 = 0;
        foreach (var (srcOffset, num3) in list)
        {
            Buffer.BlockCopy(buffer, srcOffset, array, num2, num3);
            num2 += num3;
        }
        Buffer.BlockCopy(array, 0, buffer, start, num);
        System.Security.Cryptography.CryptoPool.Return(array, num);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Buffer.BlockCopy(), System.buffer, System.comparer, System.list, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), and System.start.
Referenced by System.Formats.Asn1.AsnWriter.PopTag().