Terraria: System.Formats.Asn1.AsnWriter.ParseSubIdentifier
ParseSubIdentifier()
static BigInteger System.Formats.Asn1.AsnWriter.ParseSubIdentifier (ref ReadOnlySpan< char > oidValue) inline static private
Definition at line 1012 of file AsnWriter.cs.
    {
        int num = oidValue.IndexOf('.');
        if (num == -1)
        {
            num = oidValue.Length;
        }
        else if (num == 0 || num == oidValue.Length - 1)
        {
            throw new ArgumentException(System.SR.Argument_InvalidOidValue, "oidValue");
        }
        BigInteger zero = BigInteger.Zero;
        for (int i = 0; i < num; i++)
        {
            if (i > 0 && zero == 0L)
            {
                throw new ArgumentException(System.SR.Argument_InvalidOidValue, "oidValue");
            }
            zero *= (BigInteger)10;
            zero += (BigInteger)AtoI(oidValue[i]);
        }
        oidValue = oidValue.Slice(Math.Min(oidValue.Length, num + 1));
        return zero;
    }
References System.SR.Argument_InvalidOidValue, System.Formats.Asn1.AsnWriter.AtoI(), System.L, System.Math.Min(), and System.Numerics.BigInteger.Zero.
Referenced by System.Formats.Asn1.AsnWriter.WriteObjectIdentifierCore().