Terraria: System.Formats.Asn1.AsnWriter.WriteCharacterString
WriteCharacterString() [1/2]
void System.Formats.Asn1.AsnWriter.WriteCharacterString (UniversalTagNumber encodingType, ReadOnlySpan< char > str, Asn1Tag? tag = null) inline
Definition at line 1126 of file AsnWriter.cs.
    {
        CheckUniversalTag(tag, encodingType);
        Encoding encoding = AsnCharacterStringEncodings.GetEncoding(encodingType);
        WriteCharacterStringCore(tag ?? new Asn1Tag(encodingType), encoding, str);
    }
References System.Formats.Asn1.AsnWriter.CheckUniversalTag(), System.Formats.Asn1.AsnCharacterStringEncodings.GetEncoding(), System.str, and System.Formats.Asn1.AsnWriter.WriteCharacterStringCore().