Terraria: System.Formats.Asn1.AsnWriter.WriteObjectIdentifierCore
WriteObjectIdentifierCore()
void System.Formats.Asn1.AsnWriter.WriteObjectIdentifierCore (Asn1Tag tag, ReadOnlySpan< char > oidValue) inline private
Definition at line 969 of file AsnWriter.cs.
    {
        if (oidValue.Length < 3)
        {
            throw new ArgumentException(System.SR.Argument_InvalidOidValue, "oidValue");
        }
        if (oidValue[1] != '.')
        {
            throw new ArgumentException(System.SR.Argument_InvalidOidValue, "oidValue");
        }
        byte[] array = System.Security.Cryptography.CryptoPool.Rent(oidValue.Length / 2);
        int num = 0;
        try
        {
            int num2 = oidValue[0] switch
            {
                '0' => 0,
                '1' => 1,
                '2' => 2,
                _ => throw new ArgumentException(System.SR.Argument_InvalidOidValue, "oidValue"),
            };
            ReadOnlySpan<char> oidValue2 = oidValue.Slice(2);
            BigInteger subIdentifier = ParseSubIdentifier(ref oidValue2);
            subIdentifier += (BigInteger)(40 * num2);
            int num3 = EncodeSubIdentifier(array.AsSpan(num), ref subIdentifier);
            num += num3;
            while (!oidValue2.IsEmpty)
            {
                subIdentifier = ParseSubIdentifier(ref oidValue2);
                num3 = EncodeSubIdentifier(array.AsSpan(num), ref subIdentifier);
                num += num3;
            }
            WriteTag(tag);
            WriteLength(num);
            Buffer.BlockCopy(array, 0, _buffer, _offset, num);
            _offset += num;
        }
        finally
        {
            System.Security.Cryptography.CryptoPool.Return(array, num);
        }
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.SR.Argument_InvalidOidValue, System.array, System.Buffer.BlockCopy(), System.Formats.Asn1.AsnWriter.EncodeSubIdentifier(), System.Formats.Asn1.AsnWriter.ParseSubIdentifier(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Formats.Asn1.AsnWriter.WriteLength(), and System.Formats.Asn1.AsnWriter.WriteTag().
Referenced by System.Formats.Asn1.AsnWriter.WriteObjectIdentifier().