Terraria: System.Formats.Asn1.AsnWriter.PopOctetString
PopOctetString()
void System.Formats.Asn1.AsnWriter.PopOctetString (Asn1Tag? tag = null) inline
Definition at line 898 of file AsnWriter.cs.
    {
        CheckUniversalTag(tag, UniversalTagNumber.OctetString);
        PopTag(tag?.AsConstructed() ?? Asn1Tag.ConstructedOctetString, UniversalTagNumber.OctetString);
    }
References System.Formats.Asn1.AsnWriter.CheckUniversalTag(), System.Formats.Asn1.Asn1Tag.ConstructedOctetString, and System.Formats.Asn1.AsnWriter.PopTag().
Referenced by System.Formats.Asn1.AsnWriter.Scope.Dispose().