Terraria: System.Formats.Asn1.AsnWriter.WriteLength
WriteLength()
void System.Formats.Asn1.AsnWriter.WriteLength (int length) inline private
Definition at line 272 of file AsnWriter.cs.
    {
        if (length == -1)
        {
            EnsureWriteCapacity(1);
            _buffer[_offset] = 128;
            _offset++;
            return;
        }
        if (length < 128)
        {
            EnsureWriteCapacity(1 + length);
            _buffer[_offset] = (byte)length;
            _offset++;
            return;
        }
        int encodedLengthSubsequentByteCount = GetEncodedLengthSubsequentByteCount(length);
        EnsureWriteCapacity(encodedLengthSubsequentByteCount + 1 + length);
        _buffer[_offset] = (byte)(0x80u | (uint)encodedLengthSubsequentByteCount);
        int num = _offset + encodedLengthSubsequentByteCount;
        int num2 = length;
        do
        {
            _buffer[num] = (byte)num2;
            num2 >>= 8;
            num--;
        }
        while (num2 > 0);
        _offset += encodedLengthSubsequentByteCount + 1;
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.Formats.Asn1.AsnWriter.EnsureWriteCapacity(), System.Formats.Asn1.AsnWriter.GetEncodedLengthSubsequentByteCount(), and System.length.
Referenced by System.Formats.Asn1.AsnWriter.PopTag(), System.Formats.Asn1.AsnWriter.PushTag(), System.Formats.Asn1.AsnWriter.WriteBitStringCore(), System.Formats.Asn1.AsnWriter.WriteBooleanCore(), System.Formats.Asn1.AsnWriter.WriteCharacterStringCore(), System.Formats.Asn1.AsnWriter.WriteConstructedCerBitString(), System.Formats.Asn1.AsnWriter.WriteConstructedCerOctetString(), System.Formats.Asn1.AsnWriter.WriteGeneralizedTimeCore(), System.Formats.Asn1.AsnWriter.WriteIntegerCore(), System.Formats.Asn1.AsnWriter.WriteIntegerCore(), System.Formats.Asn1.AsnWriter.WriteIntegerCore(), System.Formats.Asn1.AsnWriter.WriteIntegerUnsignedCore(), System.Formats.Asn1.AsnWriter.WriteNonNegativeIntegerCore(), System.Formats.Asn1.AsnWriter.WriteNullCore(), System.Formats.Asn1.AsnWriter.WriteObjectIdentifierCore(), System.Formats.Asn1.AsnWriter.WriteOctetStringCore(), and System.Formats.Asn1.AsnWriter.WriteUtcTimeCore().