Terraria: System.Formats.Asn1.AsnWriter.WriteCharacterStringCore
WriteCharacterStringCore()
void System.Formats.Asn1.AsnWriter.WriteCharacterStringCore (Asn1Tag tag, Encoding encoding, ReadOnlySpan< char > str) inline private
Definition at line 1133 of file AsnWriter.cs.
    {
        int byteCount = encoding.GetByteCount(str);
        if (RuleSet == AsnEncodingRules.CER && byteCount > 1000)
        {
            WriteConstructedCerCharacterString(tag, encoding, str, byteCount);
            return;
        }
        WriteTag(tag.AsPrimitive());
        WriteLength(byteCount);
        Span<byte> bytes = _buffer.AsSpan(_offset, byteCount);
        int bytes2 = encoding.GetBytes(str, bytes);
        if (bytes2 != byteCount)
        {
            throw new InvalidOperationException();
        }
        _offset += byteCount;
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.Formats.Asn1.Asn1Tag.AsPrimitive(), System.byteCount, System.bytes, System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetBytes(), System.Formats.Asn1.AsnWriter.RuleSet, System.str, System.Formats.Asn1.AsnWriter.WriteConstructedCerCharacterString(), System.Formats.Asn1.AsnWriter.WriteLength(), and System.Formats.Asn1.AsnWriter.WriteTag().
Referenced by System.Formats.Asn1.AsnWriter.WriteCharacterString().