Terraria: System.Formats.Asn1.AsnWriter.WriteEnumeratedValue
WriteEnumeratedValue() [1/2]
void System.Formats.Asn1.AsnWriter.WriteEnumeratedValue (Asn1Tag tag, Type tEnum, object value) inline private
Definition at line 593 of file AsnWriter.cs.
    {
        CheckUniversalTag(tag, UniversalTagNumber.Enumerated);
        Type enumUnderlyingType = tEnum.GetEnumUnderlyingType();
        if (tEnum.IsDefined(typeof(FlagsAttribute), inherit: false))
        {
            throw new ArgumentException(System.SR.Argument_EnumeratedValueRequiresNonFlagsEnum, "tEnum");
        }
        if (enumUnderlyingType == typeof(ulong))
        {
            ulong value2 = Convert.ToUInt64(value);
            WriteNonNegativeIntegerCore(tag, value2);
        }
        else
        {
            long value3 = Convert.ToInt64(value);
            WriteIntegerCore(tag, value3);
        }
    }
References System.SR.Argument_EnumeratedValueRequiresNonFlagsEnum, System.Formats.Asn1.AsnWriter.CheckUniversalTag(), System.Formats.Asn1.Asn1Tag.Enumerated, System.Convert.ToInt64(), System.Convert.ToUInt64(), System.value, System.Formats.Asn1.AsnWriter.WriteIntegerCore(), and System.Formats.Asn1.AsnWriter.WriteNonNegativeIntegerCore().