Terraria: System.Formats.Asn1.AsnWriter.WriteNull
WriteNull()
void System.Formats.Asn1.AsnWriter.WriteNull (Asn1Tag? tag = null) inline
Definition at line 880 of file AsnWriter.cs.
    {
        CheckUniversalTag(tag, UniversalTagNumber.Null);
        WriteNullCore(tag?.AsPrimitive() ?? Asn1Tag.Null);
    }
References System.Formats.Asn1.AsnWriter.CheckUniversalTag(), System.Formats.Asn1.Asn1Tag.Null, and System.Formats.Asn1.AsnWriter.WriteNullCore().
Referenced by System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.GetSignatureAlgorithmIdentifier().