Terraria: System.Formats.Asn1.AsnWriter.WriteInteger
WriteInteger() [2/4]
void System.Formats.Asn1.AsnWriter.WriteInteger (long value, Asn1Tag? tag = null) inline
Definition at line 665 of file AsnWriter.cs.
    {
        CheckUniversalTag(tag, UniversalTagNumber.Integer);
        WriteIntegerCore(tag?.AsPrimitive() ?? Asn1Tag.Integer, value);
    }
References System.Formats.Asn1.AsnWriter.CheckUniversalTag(), System.Formats.Asn1.Asn1Tag.Integer, System.value, and System.Formats.Asn1.AsnWriter.WriteIntegerCore().
Referenced by System.Security.Cryptography.Asn1.PssParamsAsn.Encode(), System.Security.Cryptography.EccKeyFormatHelper.WriteEcPrivateKey(), System.Security.Cryptography.RSAKeyFormatHelper.WritePkcs1PrivateKey(), System.Security.Cryptography.KeyFormatHelper.WritePkcs8(), System.Security.Cryptography.DSAKeyFormatHelper.WritePkcs8(), and System.Security.Cryptography.RSAKeyFormatHelper.WritePkcs8PrivateKey().