Terraria: System.Formats.Asn1.AsnWriter.WriteConstructedCerOctetString
WriteConstructedCerOctetString()
void System.Formats.Asn1.AsnWriter.WriteConstructedCerOctetString (Asn1Tag tag, ReadOnlySpan< byte > payload) inline private
Definition at line 923 of file AsnWriter.cs.
    {
        WriteTag(tag.AsConstructed());
        WriteLength(-1);
        int result;
        int num = Math.DivRem(payload.Length, 1000, out result);
        int num2 = ((result != 0) ? (2 + result + GetEncodedLengthSubsequentByteCount(result)) : 0);
        int pendingCount = num * 1004 + num2 + 2;
        EnsureWriteCapacity(pendingCount);
        byte[] buffer = _buffer;
        int offset = _offset;
        ReadOnlySpan<byte> readOnlySpan = payload;
        Asn1Tag primitiveOctetString = Asn1Tag.PrimitiveOctetString;
        Span<byte> destination;
        while (readOnlySpan.Length > 1000)
        {
            WriteTag(primitiveOctetString);
            WriteLength(1000);
            destination = _buffer.AsSpan(_offset);
            readOnlySpan.Slice(0, 1000).CopyTo(destination);
            _offset += 1000;
            readOnlySpan = readOnlySpan.Slice(1000);
        }
        WriteTag(primitiveOctetString);
        WriteLength(readOnlySpan.Length);
        destination = _buffer.AsSpan(_offset);
        readOnlySpan.CopyTo(destination);
        _offset += readOnlySpan.Length;
        WriteEndOfContents();
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.Formats.Asn1.Asn1Tag.AsConstructed(), System.buffer, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.destination, System.Math.DivRem(), System.Formats.Asn1.AsnWriter.EnsureWriteCapacity(), System.Formats.Asn1.AsnWriter.GetEncodedLengthSubsequentByteCount(), System.offset, System.Formats.Asn1.Asn1Tag.PrimitiveOctetString, System.Formats.Asn1.AsnWriter.WriteEndOfContents(), System.Formats.Asn1.AsnWriter.WriteLength(), and System.Formats.Asn1.AsnWriter.WriteTag().
Referenced by System.Formats.Asn1.AsnWriter.PopTag(), System.Formats.Asn1.AsnWriter.WriteConstructedCerCharacterString(), and System.Formats.Asn1.AsnWriter.WriteOctetStringCore().