Terraria: System.Formats.Asn1.AsnWriter.Encode
Encode() [2/2]
int System.Formats.Asn1.AsnWriter.Encode (Span< byte > destination) inline
Definition at line 195 of file AsnWriter.cs.
    {
        if (!TryEncode(destination, out var bytesWritten))
        {
            throw new ArgumentException(System.SR.Argument_DestinationTooShort, "destination");
        }
        return bytesWritten;
    }
References System.SR.Argument_DestinationTooShort, System.destination, and System.Formats.Asn1.AsnWriter.TryEncode().
Referenced by System.Security.Cryptography.X509Certificates.ECDsaX509SignatureGenerator.BuildPublicKey(), Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertIeee1363ToDer(), System.Security.Cryptography.ECDiffieHellman.ExportECPrivateKey(), System.Security.Cryptography.ECDsa.ExportECPrivateKey(), System.Security.Cryptography.CngPkcs8.ExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.CngPkcs8.ExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.RSA.ExportRSAPrivateKey(), System.Security.Cryptography.RSA.ExportRSAPublicKey(), System.Security.Cryptography.ECDiffieHellmanPublicKey.ExportSubjectPublicKeyInfo(), System.Security.Cryptography.X509Certificates.PublicKey.ExportSubjectPublicKeyInfo(), System.Security.Cryptography.X509Certificates.ECDsaX509SignatureGenerator.GetSignatureAlgorithmIdentifier(), System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.GetSignatureAlgorithmIdentifier(), and System.Security.Cryptography.X509Certificates.RSAPssX509SignatureGenerator.GetSignatureAlgorithmIdentifier().