Terraria: System.Formats.Asn1.AsnWriter.Reset
Reset()
void System.Formats.Asn1.AsnWriter.Reset () inline
Definition at line 153 of file AsnWriter.cs.
    {
        if (_offset > 0)
        {
            Array.Clear(_buffer, 0, _offset);
            _offset = 0;
            _nestingStack?.Clear();
        }
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._nestingStack, System.Formats.Asn1.AsnWriter._offset, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), and System.Array.Clear().
Referenced by System.Security.Cryptography.X509Certificates.RSAPssX509SignatureGenerator.GetSignatureAlgorithmIdentifier().