Terraria: System.Formats.Asn1.AsnWriter.PopTag
PopTag()
void System.Formats.Asn1.AsnWriter.PopTag (Asn1Tag tag, UniversalTagNumber tagType, bool sortContents = false) inline private
Definition at line 374 of file AsnWriter.cs.
    {
        if (_nestingStack == null || _nestingStack.Count == 0)
        {
            throw new InvalidOperationException(System.SR.AsnWriter_PopWrongTag);
        }
        var (asn1Tag2, num2, universalTagNumber2) = (StackFrame)(ref _nestingStack.Peek());
        if (asn1Tag2 != tag || universalTagNumber2 != tagType)
        {
            throw new InvalidOperationException(System.SR.AsnWriter_PopWrongTag);
        }
        _nestingStack.Pop();
        if (sortContents)
        {
            SortContents(_buffer, num2 + 1, _offset);
        }
        if (RuleSet == AsnEncodingRules.CER && tagType != UniversalTagNumber.OctetString)
        {
            WriteEndOfContents();
            return;
        }
        int num3 = _offset - 1 - num2;
        int num4 = num2 + 1;
        if (tagType == UniversalTagNumber.OctetString)
        {
            if (RuleSet == AsnEncodingRules.CER && num3 > 1000)
            {
                int result;
                int num5 = Math.DivRem(num3, 1000, out result);
                int num6 = 4 * num5 + 2 + GetEncodedLengthSubsequentByteCount(result);
                EnsureWriteCapacity(num6 + 2);
                ReadOnlySpan<byte> readOnlySpan = _buffer.AsSpan(num4, num3);
                Span<byte> span = _buffer.AsSpan(num4 + num6, num3);
                readOnlySpan.CopyTo(span);
                int num7 = num4 + num3 + num6 + 2;
                _offset = num2 - tag.CalculateEncodedSize();
                WriteConstructedCerOctetString(tag, span);
                return;
            }
            int num8 = tag.CalculateEncodedSize();
            tag.AsPrimitive().Encode(_buffer.AsSpan(num2 - num8, num8));
        }
        int encodedLengthSubsequentByteCount = GetEncodedLengthSubsequentByteCount(num3);
        if (encodedLengthSubsequentByteCount == 0)
        {
            _buffer[num2] = (byte)num3;
            return;
        }
        EnsureWriteCapacity(encodedLengthSubsequentByteCount);
        Buffer.BlockCopy(_buffer, num4, _buffer, num4 + encodedLengthSubsequentByteCount, num3);
        int offset = _offset;
        _offset = num2;
        WriteLength(num3);
        _offset = offset + encodedLengthSubsequentByteCount;
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._nestingStack, System.Formats.Asn1.AsnWriter._offset, System.SR.AsnWriter_PopWrongTag, System.Formats.Asn1.Asn1Tag.AsPrimitive(), System.Buffer.BlockCopy(), System.Formats.Asn1.Asn1Tag.CalculateEncodedSize(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Math.DivRem(), System.Formats.Asn1.Asn1Tag.Encode(), System.Formats.Asn1.AsnWriter.EnsureWriteCapacity(), System.Formats.Asn1.AsnWriter.GetEncodedLengthSubsequentByteCount(), System.offset, System.Formats.Asn1.AsnWriter.RuleSet, System.Formats.Asn1.AsnWriter.SortContents(), System.Formats.Asn1.AsnWriter.WriteConstructedCerOctetString(), System.Formats.Asn1.AsnWriter.WriteEndOfContents(), and System.Formats.Asn1.AsnWriter.WriteLength().
Referenced by System.Formats.Asn1.AsnWriter.PopOctetString(), System.Formats.Asn1.AsnWriter.PopSequenceCore(), and System.Formats.Asn1.AsnWriter.PopSetOfCore().