Terraria: System.Formats.Asn1.AsnWriter.WriteBitStringCore
WriteBitStringCore()
void System.Formats.Asn1.AsnWriter.WriteBitStringCore (Asn1Tag tag, ReadOnlySpan< byte > bitString, int unusedBitCount) inline private
Definition at line 491 of file AsnWriter.cs.
    {
        if (unusedBitCount < 0 || unusedBitCount > 7)
        {
            throw new ArgumentOutOfRangeException("unusedBitCount", unusedBitCount, System.SR.Argument_UnusedBitCountRange);
        }
        if (bitString.Length == 0 && unusedBitCount != 0)
        {
            throw new ArgumentException(System.SR.Argument_UnusedBitCountMustBeZero, "unusedBitCount");
        }
        byte lastByte = (byte)((!bitString.IsEmpty) ? bitString[bitString.Length - 1] : 0);
        if (!CheckValidLastByte(lastByte, unusedBitCount))
        {
            throw new ArgumentException(System.SR.Argument_UnusedBitWasSet, "unusedBitCount");
        }
        if (RuleSet == AsnEncodingRules.CER && bitString.Length >= 1000)
        {
            WriteConstructedCerBitString(tag, bitString, unusedBitCount);
            return;
        }
        WriteTag(tag.AsPrimitive());
        WriteLength(bitString.Length + 1);
        _buffer[_offset] = (byte)unusedBitCount;
        _offset++;
        bitString.CopyTo(_buffer.AsSpan(_offset));
        _offset += bitString.Length;
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.SR.Argument_UnusedBitCountMustBeZero, System.SR.Argument_UnusedBitCountRange, System.SR.Argument_UnusedBitWasSet, System.Formats.Asn1.Asn1Tag.AsPrimitive(), System.Formats.Asn1.AsnWriter.CheckValidLastByte(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Formats.Asn1.AsnWriter.RuleSet, System.Formats.Asn1.AsnWriter.WriteConstructedCerBitString(), System.Formats.Asn1.AsnWriter.WriteLength(), and System.Formats.Asn1.AsnWriter.WriteTag().
Referenced by System.Formats.Asn1.AsnWriter.WriteBitString().