Terraria: System.Formats.Asn1.AsnWriter.WriteIntegerCore
WriteIntegerCore() [1/3]
void System.Formats.Asn1.AsnWriter.WriteIntegerCore (Asn1Tag tag, BigInteger value) inline private
Definition at line 781 of file AsnWriter.cs.
    {
        byte[] array = value.ToByteArray();
        Array.Reverse(array);
        WriteTag(tag);
        WriteLength(array.Length);
        Buffer.BlockCopy(array, 0, _buffer, _offset, array.Length);
        _offset += array.Length;
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.array, System.Buffer.BlockCopy(), System.Array.Reverse(), System.value, System.Formats.Asn1.AsnWriter.WriteLength(), and System.Formats.Asn1.AsnWriter.WriteTag().