Terraria: System.Formats.Asn1.AsnWriter.WriteConstructedCerCharacterString
WriteConstructedCerCharacterString()
void System.Formats.Asn1.AsnWriter.WriteConstructedCerCharacterString (Asn1Tag tag, Encoding encoding, ReadOnlySpan< char > str, int size) inline private
Definition at line 1152 of file AsnWriter.cs.
    {
        byte[] array = System.Security.Cryptography.CryptoPool.Rent(size);
        int bytes = encoding.GetBytes(str, array);
        if (bytes != size)
        {
            throw new InvalidOperationException();
        }
        WriteConstructedCerOctetString(tag, array.AsSpan(0, size));
        System.Security.Cryptography.CryptoPool.Return(array, size);
    }
References System.array, System.bytes, System.Text.Encoding.GetBytes(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.str, and System.Formats.Asn1.AsnWriter.WriteConstructedCerOctetString().
Referenced by System.Formats.Asn1.AsnWriter.WriteCharacterStringCore().