Terraria: System.Xml.Xsl.XmlQueryTypeFactory.ItemType.ItemType
ItemType() [1/2]
static System.Xml.Xsl.XmlQueryTypeFactory.ItemType.ItemType () inline static private
Definition at line 78 of file XmlQueryTypeFactory.cs.
        {
            int num = 55;
            s_builtInItemTypes = new XmlQueryType[num];
            s_builtInItemTypesStrict = new XmlQueryType[num];
            for (int i = 0; i < num; i++)
            {
                XmlTypeCode xmlTypeCode = (XmlTypeCode)i;
                switch ((XmlTypeCode)i)
                {
                case XmlTypeCode.None:
                    s_builtInItemTypes[i] = ChoiceType.None;
                    s_builtInItemTypesStrict[i] = ChoiceType.None;
                    break;
                case XmlTypeCode.Item:
                case XmlTypeCode.Node:
                    s_builtInItemTypes[i] = new ItemType(xmlTypeCode, XmlQualifiedNameTest.Wildcard, XmlSchemaComplexType.AnyType, isNillable: false, isStrict: false, isNotRtf: false);
                    s_builtInItemTypesStrict[i] = s_builtInItemTypes[i];
                    break;
                case XmlTypeCode.Document:
                case XmlTypeCode.Element:
                case XmlTypeCode.Namespace:
                case XmlTypeCode.ProcessingInstruction:
                case XmlTypeCode.Comment:
                case XmlTypeCode.Text:
                    s_builtInItemTypes[i] = new ItemType(xmlTypeCode, XmlQualifiedNameTest.Wildcard, XmlSchemaComplexType.AnyType, isNillable: false, isStrict: false, isNotRtf: true);
                    s_builtInItemTypesStrict[i] = s_builtInItemTypes[i];
                    break;
                case XmlTypeCode.Attribute:
                    s_builtInItemTypes[i] = new ItemType(xmlTypeCode, XmlQualifiedNameTest.Wildcard, DatatypeImplementation.AnySimpleType, isNillable: false, isStrict: false, isNotRtf: true);
                    s_builtInItemTypesStrict[i] = s_builtInItemTypes[i];
                    break;
                case XmlTypeCode.AnyAtomicType:
                    s_builtInItemTypes[i] = new ItemType(xmlTypeCode, XmlQualifiedNameTest.Wildcard, DatatypeImplementation.AnyAtomicType, isNillable: false, isStrict: false, isNotRtf: true);
                    s_builtInItemTypesStrict[i] = s_builtInItemTypes[i];
                    break;
                case XmlTypeCode.UntypedAtomic:
                    s_builtInItemTypes[i] = new ItemType(xmlTypeCode, XmlQualifiedNameTest.Wildcard, DatatypeImplementation.UntypedAtomicType, isNillable: false, isStrict: true, isNotRtf: true);
                    s_builtInItemTypesStrict[i] = s_builtInItemTypes[i];
                    break;
                default:
                {
                    XmlSchemaType builtInSimpleType = XmlSchemaType.GetBuiltInSimpleType(xmlTypeCode);
                    s_builtInItemTypes[i] = new ItemType(xmlTypeCode, XmlQualifiedNameTest.Wildcard, builtInSimpleType, isNillable: false, isStrict: false, isNotRtf: true);
                    s_builtInItemTypesStrict[i] = new ItemType(xmlTypeCode, XmlQualifiedNameTest.Wildcard, builtInSimpleType, isNillable: false, isStrict: true, isNotRtf: true);
                    break;
                }
                }
            }
            UntypedDocument = new ItemType(XmlTypeCode.Document, XmlQualifiedNameTest.Wildcard, XmlSchemaComplexType.UntypedAnyType, isNillable: false, isStrict: false, isNotRtf: true);
            UntypedElement = new ItemType(XmlTypeCode.Element, XmlQualifiedNameTest.Wildcard, XmlSchemaComplexType.UntypedAnyType, isNillable: false, isStrict: false, isNotRtf: true);
            UntypedAttribute = new ItemType(XmlTypeCode.Attribute, XmlQualifiedNameTest.Wildcard, DatatypeImplementation.UntypedAtomicType, isNillable: false, isStrict: false, isNotRtf: true);
            NodeNotRtf = new ItemType(XmlTypeCode.Node, XmlQualifiedNameTest.Wildcard, XmlSchemaComplexType.AnyType, isNillable: false, isStrict: false, isNotRtf: true);
            s_specialBuiltInItemTypes = new XmlQueryType[4] { UntypedDocument, UntypedElement, UntypedAttribute, NodeNotRtf };
        }
References System.Xml.Xsl.XmlQueryTypeFactory.ItemType.ItemType(), System.Xml.Schema.DatatypeImplementation.AnyAtomicType, System.Xml.Schema.DatatypeImplementation.AnySimpleType, System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaType.GetBuiltInSimpleType(), System.Xml.Xsl.XmlQueryTypeFactory.ItemType.NodeNotRtf, System.Xml.Xsl.XmlQueryTypeFactory.ChoiceType.None, System.Xml.Xsl.XmlQueryTypeFactory.ItemType.s_builtInItemTypes, System.Xml.Xsl.XmlQueryTypeFactory.ItemType.s_builtInItemTypesStrict, System.Xml.Xsl.XmlQueryTypeFactory.ItemType.s_specialBuiltInItemTypes, System.Xml.Schema.XmlSchemaComplexType.UntypedAnyType, System.Xml.Schema.DatatypeImplementation.UntypedAtomicType, System.Xml.Xsl.XmlQueryTypeFactory.ItemType.UntypedAttribute, System.Xml.Xsl.XmlQueryTypeFactory.ItemType.UntypedDocument, System.Xml.Xsl.XmlQueryTypeFactory.ItemType.UntypedElement, and System.Xml.Xsl.XmlQualifiedNameTest.Wildcard.
Referenced by System.Xml.Xsl.XmlQueryTypeFactory.ItemType.ItemType(), System.Xml.Xsl.XmlQueryTypeFactory.ItemType.Create(), and System.Xml.Xsl.XmlQueryTypeFactory.ItemType.Create().