Terraria: System.Formats.Asn1.AsnWriter.CheckUniversalTag
CheckUniversalTag()
static void System.Formats.Asn1.AsnWriter.CheckUniversalTag (Asn1Tag? tag, UniversalTagNumber universalTagNumber) inline static private
Definition at line 473 of file AsnWriter.cs.
    {
        if (tag.HasValue)
        {
            Asn1Tag value = tag.Value;
            if (value.TagClass == TagClass.Universal && value.TagValue != (int)universalTagNumber)
            {
                throw new ArgumentException(System.SR.Argument_UniversalValueIsFixed, "tag");
            }
        }
    }
References System.SR.Argument_UniversalValueIsFixed, and System.value.
Referenced by System.Formats.Asn1.AsnWriter.PopOctetString(), System.Formats.Asn1.AsnWriter.PopSequence(), System.Formats.Asn1.AsnWriter.PopSetOf(), System.Formats.Asn1.AsnWriter.PushOctetString(), System.Formats.Asn1.AsnWriter.PushSequence(), System.Formats.Asn1.AsnWriter.PushSetOf(), System.Formats.Asn1.AsnWriter.WriteBitString(), System.Formats.Asn1.AsnWriter.WriteBoolean(), System.Formats.Asn1.AsnWriter.WriteCharacterString(), System.Formats.Asn1.AsnWriter.WriteEnumeratedValue(), System.Formats.Asn1.AsnWriter.WriteGeneralizedTime(), System.Formats.Asn1.AsnWriter.WriteInteger(), System.Formats.Asn1.AsnWriter.WriteInteger(), System.Formats.Asn1.AsnWriter.WriteInteger(), System.Formats.Asn1.AsnWriter.WriteInteger(), System.Formats.Asn1.AsnWriter.WriteIntegerUnsigned(), System.Formats.Asn1.AsnWriter.WriteNamedBitList(), System.Formats.Asn1.AsnWriter.WriteNamedBitList(), System.Formats.Asn1.AsnWriter.WriteNamedBitList< TEnum >(), System.Formats.Asn1.AsnWriter.WriteNull(), System.Formats.Asn1.AsnWriter.WriteObjectIdentifier(), System.Formats.Asn1.AsnWriter.WriteOctetString(), System.Formats.Asn1.AsnWriter.WriteUtcTime(), and System.Formats.Asn1.AsnWriter.WriteUtcTime().