Terraria: System.Formats.Asn1.AsnWriter.WriteBooleanCore
WriteBooleanCore()
void System.Formats.Asn1.AsnWriter.WriteBooleanCore (Asn1Tag tag, bool value) inline private
Definition at line 571 of file AsnWriter.cs.
    {
        WriteTag(tag);
        WriteLength(1);
        _buffer[_offset] = (byte)(value ? 255u : 0u);
        _offset++;
    }
References System.Formats.Asn1.AsnWriter._buffer, System.Formats.Asn1.AsnWriter._offset, System.value, System.Formats.Asn1.AsnWriter.WriteLength(), and System.Formats.Asn1.AsnWriter.WriteTag().
Referenced by System.Formats.Asn1.AsnWriter.WriteBoolean().