Terraria: System.Formats.Asn1.AsnWriter.PushTag
PushTag()
Scope System.Formats.Asn1.AsnWriter.PushTag (Asn1Tag tag, UniversalTagNumber tagType) inline private
Definition at line 362 of file AsnWriter.cs.
    {
        if (_nestingStack == null)
        {
            _nestingStack = new Stack<StackFrame>();
        }
        WriteTag(tag);
        _nestingStack.Push(new StackFrame(tag, _offset, tagType));
        WriteLength(-1);
        return new Scope(this);
    }
References System.Formats.Asn1.AsnWriter._nestingStack, System.Formats.Asn1.AsnWriter._offset, System.Formats.Asn1.AsnWriter.WriteLength(), and System.Formats.Asn1.AsnWriter.WriteTag().
Referenced by System.Formats.Asn1.AsnWriter.PushOctetString(), System.Formats.Asn1.AsnWriter.PushSequenceCore(), and System.Formats.Asn1.AsnWriter.PushSetOfCore().