Terraria: System.Security.Cryptography.DESCryptoServiceProvider.CreateTransform
CreateTransform()
ICryptoTransform System.Security.Cryptography.DESCryptoServiceProvider.CreateTransform (byte[] rgbKey, byte[] rgbIV, bool encrypting) inline private
Definition at line 51 of file DESCryptoServiceProvider.cs.
    {
        if (rgbKey == null)
        {
            throw new ArgumentNullException("rgbKey");
        }
        long num = (long)rgbKey.Length * 8L;
        if (num > int.MaxValue || !((int)num).IsLegalSize(LegalKeySizes))
        {
            throw new ArgumentException(System.SR.Cryptography_InvalidKeySize, "rgbKey");
        }
        if (DES.IsWeakKey(rgbKey))
        {
            throw new CryptographicException(System.SR.Cryptography_InvalidKey_Weak, "DES");
        }
        if (DES.IsSemiWeakKey(rgbKey))
        {
            throw new CryptographicException(System.SR.Cryptography_InvalidKey_SemiWeak, "DES");
        }
        if (rgbIV == null)
        {
            if (Mode.UsesIv())
            {
                rgbIV = RandomNumberGenerator.GetBytes(8);
            }
        }
        else if (rgbIV.Length < 8)
        {
            throw new CryptographicException(System.SR.Cryptography_InvalidIVSize);
        }
        Internal.Cryptography.BasicSymmetricCipher cipher = new BasicSymmetricCipherCsp(26113, Mode, BlockSize / 8, rgbKey, 0, addNoSaltFlag: false, rgbIV, encrypting, FeedbackSize, this.GetPaddingSize(Mode, FeedbackSize));
        return Internal.Cryptography.UniversalCryptoTransform.Create(Padding, cipher, encrypting);
    }
References System.Security.Cryptography.SymmetricAlgorithm.BlockSize, Internal.Cryptography.UniversalCryptoTransform.Create(), System.SR.Cryptography_InvalidIVSize, System.SR.Cryptography_InvalidKey_SemiWeak, System.SR.Cryptography_InvalidKey_Weak, System.SR.Cryptography_InvalidKeySize, System.Security.Cryptography.SymmetricAlgorithm.FeedbackSize, System.Security.Cryptography.RandomNumberGenerator.GetBytes(), System.Security.Cryptography.DES.IsSemiWeakKey(), System.Security.Cryptography.DES.IsWeakKey(), System.L, System.Security.Cryptography.SymmetricAlgorithm.LegalKeySizes, and System.Security.Cryptography.SymmetricAlgorithm.Padding.
Referenced by System.Security.Cryptography.DESCryptoServiceProvider.CreateDecryptor(), System.Security.Cryptography.DESCryptoServiceProvider.CreateDecryptor(), System.Security.Cryptography.DESCryptoServiceProvider.CreateEncryptor(), and System.Security.Cryptography.DESCryptoServiceProvider.CreateEncryptor().