Terraria: System.Dynamic.ExpandoObject.KeyCollection.CheckVersion
CheckVersion()
void System.Dynamic.ExpandoObject.KeyCollection.CheckVersion () inline private
Definition at line 70 of file ExpandoObject.cs.
        {
            if (_expando._data.Version != _expandoVersion || _expandoData != _expando._data)
            {
                throw Error.CollectionModifiedWhileEnumerating();
            }
        }
References System.Dynamic.ExpandoObject._data, System.Dynamic.ExpandoObject.KeyCollection._expando, System.Dynamic.ExpandoObject.KeyCollection._expandoData, System.Dynamic.ExpandoObject.KeyCollection._expandoVersion, System.Linq.Expressions.Error.CollectionModifiedWhileEnumerating(), and System.Dynamic.ExpandoObject.ExpandoData.Version.
Referenced by System.Dynamic.ExpandoObject.KeyCollection.Contains(), System.Dynamic.ExpandoObject.KeyCollection.CopyTo(), and System.Dynamic.ExpandoObject.KeyCollection.GetEnumerator().