Terraria: System.Dynamic.Utils.ContractUtils.Requires
Requires()
static void System.Dynamic.Utils.ContractUtils.Requires ([DoesNotReturnIf(false)] bool precondition, string paramName) inline static
Definition at line 12 of file ContractUtils.cs.
    {
        if (!precondition)
        {
            throw Error.InvalidArgumentValue(paramName);
        }
    }
References System.Linq.Expressions.Error.InvalidArgumentValue().
Referenced by System.Dynamic.BinaryOperationBinder.BinaryOperationBinder(), System.Dynamic.UnaryOperationBinder.UnaryOperationBinder(), System.Dynamic.BinaryOperationBinder.Bind(), System.Dynamic.SetIndexBinder.Bind(), System.Dynamic.SetMemberBinder.Bind(), System.Dynamic.ConvertBinder.Bind(), System.Dynamic.DeleteMemberBinder.Bind(), System.Dynamic.GetMemberBinder.Bind(), System.Dynamic.UnaryOperationBinder.Bind(), System.Dynamic.BindingRestrictions.GetExpressionRestriction(), System.Runtime.CompilerServices.CallSite< T >.IsSimpleSignature(), System.Linq.Expressions.Expression< TDelegate >.MakeCatchBlock(), and System.Dynamic.DynamicObject.MetaDynamic.ReferenceArgAssign().