Terraria: NetManager.SendData
SendData()
void NetManager.SendData (ISocket socket, NetPacket packet) inline private
     {
         if (Main.netMode != 0)
         {
             packet.ShrinkToFit();
             try
             {
                 socket.AsyncSend(packet.Buffer.Data, 0, packet.Length, SendCallback, packet);
             }
             catch
             {
             }
             Main.ActiveNetDiagnosticsUI.CountSentModuleMessage(packet.Id, packet.Length);
         }
     }
References Main.ActiveNetDiagnosticsUI, ISocket.AsyncSend(), NetPacket.Buffer, INetDiagnosticsUI.CountSentModuleMessage(), CachedBuffer.Data, NetPacket.Id, NetPacket.Length, Main.netMode, SendCallback(), and NetPacket.ShrinkToFit().
Referenced by Broadcast(), SendToClient(), and SendToServer().