Terraria: CreativePowers.DifficultySliderPower.AddIndication
AddIndication()
static void CreativePowers.DifficultySliderPower.AddIndication (UIPanel panel, float yAnchor, string indicationText, string iconImagePath, UIElement.ElementEvent updateEvent, UIElement.MouseEvent clickEvent) inline static private
         {
             UIImage uIImage = new UIImage(Main.Assets.Request<Texture2D>(iconImagePath, (AssetRequestMode)1))
             {
                 HAlign = 1f,
                 VAlign = yAnchor,
                 Left = new StyleDimension(4f, 0f),
                 Top = new StyleDimension(2f, 0f),
                 RemoveFloatingPointsFromDrawPosition = true
             };
             uIImage.OnMouseOut += Button_OnMouseOut;
             uIImage.OnMouseOver += Button_OnMouseOver;
             if (updateEvent != null)
             {
                 uIImage.OnUpdate += updateEvent;
             }
             if (clickEvent != null)
             {
                 uIImage.OnLeftClick += clickEvent;
             }
             panel.Append(uIImage);
         }
References UIElement.Append(), Main.Assets, CreativePowers.DifficultySliderPower.Button_OnMouseOut(), CreativePowers.DifficultySliderPower.Button_OnMouseOver(), Left, UIElement.OnLeftClick, UIElement.OnMouseOut, UIElement.OnMouseOver, UIElement.OnUpdate, and Top.
Referenced by CreativePowers.DifficultySliderPower.ProvideSlider().