Terraria: NetManager.Read
Read()
void NetManager.Read (BinaryReader reader, int userId, int readLength) inline
     {
         ushort num = reader.ReadUInt16();
         if (_modules.ContainsKey(num))
         {
             _modules[num].Deserialize(reader, userId);
         }
         Main.ActiveNetDiagnosticsUI.CountReadModuleMessage(num, readLength);
     }
References _modules, Main.ActiveNetDiagnosticsUI, and INetDiagnosticsUI.CountReadModuleMessage().
Referenced by MessageBuffer.GetData(), and SendToSelf().