Terraria: NetManager.SendToServer
SendToServer()
void NetManager.SendToServer (NetPacket packet) inline
     {
         SendData(Netplay.Connection.Socket, packet);
     }
References Netplay.Connection, SendData(), and RemoteServer.Socket.
Referenced by ChatHelper.SendChatMessageFromClient(), SendToServerAndSelf(), SendToServerOrLoopback(), and Main.TriggerPing().