Terraria: CreativePowers.DifficultySliderPower.ProvideSlider
ProvideSlider()
override UIElement CreativePowers.DifficultySliderPower.ProvideSlider () inline virtual
Implements CreativePowers.ASharedSliderPower.
         {
             UIVerticalSlider uIVerticalSlider = CreativePowersHelper.CreateSlider(base.GetSliderValue, base.SetValueKeyboard, base.SetValueGamepad);
             UIPanel uIPanel = new UIPanel();
             uIPanel.Width = new StyleDimension(82f, 0f);
             uIPanel.Height = new StyleDimension(180f, 0f);
             uIPanel.HAlign = 0f;
             uIPanel.VAlign = 0.5f;
             uIPanel.Append(uIVerticalSlider);
             uIPanel.OnUpdate += CreativePowersHelper.UpdateUseMouseInterface;
             uIVerticalSlider.OnUpdate += UpdateSliderColorAndShowMultiplierMouseOver;
             AddIndication(uIPanel, 0f, "x3", "Images/UI/WorldCreation/IconDifficultyMaster", MouseOver_Master, Click_Master);
             AddIndication(uIPanel, 1f / 3f, "x2", "Images/UI/WorldCreation/IconDifficultyExpert", MouseOver_Expert, Click_Expert);
             AddIndication(uIPanel, 2f / 3f, "x1", "Images/UI/WorldCreation/IconDifficultyNormal", MouseOver_Normal, Click_Normal);
             AddIndication(uIPanel, 1f, "x0.5", "Images/UI/WorldCreation/IconDifficultyCreative", MouseOver_Journey, Click_Journey);
             return uIPanel;
         }
References CreativePowers.DifficultySliderPower.AddIndication(), UIElement.Append(), CreativePowers.DifficultySliderPower.Click_Expert(), CreativePowers.DifficultySliderPower.Click_Journey(), CreativePowers.DifficultySliderPower.Click_Master(), CreativePowers.DifficultySliderPower.Click_Normal(), CreativePowersHelper.CreateSlider(), UIElement.HAlign, UIElement.Height, CreativePowers.DifficultySliderPower.MouseOver_Expert(), CreativePowers.DifficultySliderPower.MouseOver_Journey(), CreativePowers.DifficultySliderPower.MouseOver_Master(), CreativePowers.DifficultySliderPower.MouseOver_Normal(), UIElement.OnUpdate, CreativePowers.DifficultySliderPower.UpdateSliderColorAndShowMultiplierMouseOver(), CreativePowersHelper.UpdateUseMouseInterface(), UIElement.VAlign, and UIElement.Width.