Terraria: CreativePowers.DifficultySliderPower.UpdateInfoFromSliderValueCache
UpdateInfoFromSliderValueCache()
override void CreativePowers.DifficultySliderPower.UpdateInfoFromSliderValueCache () inline package virtual
Implements CreativePowers.ASharedSliderPower.
         {
             if (_sliderCurrentValueCache <= 0.33f)
             {
                 StrengthMultiplierToGiveNPCs = Utils.Remap(_sliderCurrentValueCache, 0f, 0.33f, 0.5f, 1f);
             }
             else
             {
                 StrengthMultiplierToGiveNPCs = Utils.Remap(_sliderCurrentValueCache, 0.33f, 1f, 1f, 3f);
             }
             float strengthMultiplierToGiveNPCs = (float)Math.Round(StrengthMultiplierToGiveNPCs * 20f) / 20f;
             StrengthMultiplierToGiveNPCs = strengthMultiplierToGiveNPCs;
         }
References CreativePowers.ASharedSliderPower._sliderCurrentValueCache, Utils.Remap(), and CreativePowers.DifficultySliderPower.StrengthMultiplierToGiveNPCs.
Referenced by CreativePowers.DifficultySliderPower.Load(), and CreativePowers.DifficultySliderPower.Reset().