Terraria: System.Buffers.TlsOverPerCoreLockedStacksArrayPool.PerCoreLockedStacks.TryPush
TryPush()
bool System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks.TryPush (T[] array) inline
Definition at line 27 of file TlsOverPerCoreLockedStacksArrayPool.cs.
        {
            LockedStack[] perCoreStacks = _perCoreStacks;
            int num = (int)((uint)Thread.GetCurrentProcessorId() % (uint)s_lockedStackCount);
            for (int i = 0; i < perCoreStacks.Length; i++)
            {
                if (perCoreStacks[num].TryPush(array))
                {
                    return true;
                }
                if (++num == perCoreStacks.Length)
                {
                    num = 0;
                }
            }
            return false;
        }
References System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks._perCoreStacks, System.array, System.Threading.Thread.GetCurrentProcessorId(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks.s_lockedStackCount, and System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks.TryPush().
Referenced by System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks.TryPush().