Terraria: System.Xml.Schema.XmlSchemaComplexType.CloneAttributes
CloneAttributes()
static XmlSchemaObjectCollection System.Xml.Schema.XmlSchemaComplexType.CloneAttributes (XmlSchemaObjectCollection attributes) inline static package
Definition at line 417 of file XmlSchemaComplexType.cs.
    {
        if (HasAttributeQNameRef(attributes))
        {
            XmlSchemaObjectCollection xmlSchemaObjectCollection = attributes.Clone();
            for (int i = 0; i < attributes.Count; i++)
            {
                XmlSchemaObject xmlSchemaObject = attributes[i];
                if (xmlSchemaObject is XmlSchemaAttributeGroupRef xmlSchemaAttributeGroupRef)
                {
                    XmlSchemaAttributeGroupRef xmlSchemaAttributeGroupRef2 = (XmlSchemaAttributeGroupRef)xmlSchemaAttributeGroupRef.Clone();
                    xmlSchemaAttributeGroupRef2.RefName = xmlSchemaAttributeGroupRef.RefName.Clone();
                    xmlSchemaObjectCollection[i] = xmlSchemaAttributeGroupRef2;
                    continue;
                }
                XmlSchemaAttribute xmlSchemaAttribute = xmlSchemaObject as XmlSchemaAttribute;
                if (!xmlSchemaAttribute.RefName.IsEmpty || !xmlSchemaAttribute.SchemaTypeName.IsEmpty)
                {
                    xmlSchemaObjectCollection[i] = xmlSchemaAttribute.Clone();
                }
            }
            return xmlSchemaObjectCollection;
        }
        return attributes;
    }
References System.Xml.Schema.XmlSchemaAttribute.Clone(), System.Xml.Schema.XmlSchemaObject.Clone(), System.Xml.Schema.XmlSchemaObjectCollection.Clone(), System.Collections.CollectionBase.Count, System.Xml.Dictionary, and System.Xml.Schema.XmlSchemaComplexType.HasAttributeQNameRef().
Referenced by System.Xml.Schema.XmlSchemaAttributeGroup.Clone(), and System.Xml.Schema.XmlSchemaComplexType.Clone().