Terraria: System.Xml.Schema.XmlSchemaComplexType.Clone
Clone() [2/2]
XmlSchemaObject System.Xml.Schema.XmlSchemaComplexType.Clone (XmlSchema parentSchema) inline package
Definition at line 341 of file XmlSchemaComplexType.cs.
    {
        XmlSchemaComplexType xmlSchemaComplexType = (XmlSchemaComplexType)MemberwiseClone();
        if (xmlSchemaComplexType.ContentModel != null)
        {
            if (xmlSchemaComplexType.ContentModel is XmlSchemaSimpleContent xmlSchemaSimpleContent)
            {
                XmlSchemaSimpleContent xmlSchemaSimpleContent2 = (XmlSchemaSimpleContent)xmlSchemaSimpleContent.Clone();
                if (xmlSchemaSimpleContent.Content is XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension)
                {
                    XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension2 = (XmlSchemaSimpleContentExtension)xmlSchemaSimpleContentExtension.Clone();
                    xmlSchemaSimpleContentExtension2.BaseTypeName = xmlSchemaSimpleContentExtension.BaseTypeName.Clone();
                    xmlSchemaSimpleContentExtension2.SetAttributes(CloneAttributes(xmlSchemaSimpleContentExtension.Attributes));
                    xmlSchemaSimpleContent2.Content = xmlSchemaSimpleContentExtension2;
                }
                else
                {
                    XmlSchemaSimpleContentRestriction xmlSchemaSimpleContentRestriction = (XmlSchemaSimpleContentRestriction)xmlSchemaSimpleContent.Content;
                    XmlSchemaSimpleContentRestriction xmlSchemaSimpleContentRestriction2 = (XmlSchemaSimpleContentRestriction)xmlSchemaSimpleContentRestriction.Clone();
                    xmlSchemaSimpleContentRestriction2.BaseTypeName = xmlSchemaSimpleContentRestriction.BaseTypeName.Clone();
                    xmlSchemaSimpleContentRestriction2.SetAttributes(CloneAttributes(xmlSchemaSimpleContentRestriction.Attributes));
                    xmlSchemaSimpleContent2.Content = xmlSchemaSimpleContentRestriction2;
                }
                xmlSchemaComplexType.ContentModel = xmlSchemaSimpleContent2;
            }
            else
            {
                XmlSchemaComplexContent xmlSchemaComplexContent = (XmlSchemaComplexContent)xmlSchemaComplexType.ContentModel;
                XmlSchemaComplexContent xmlSchemaComplexContent2 = (XmlSchemaComplexContent)xmlSchemaComplexContent.Clone();
                if (xmlSchemaComplexContent.Content is XmlSchemaComplexContentExtension xmlSchemaComplexContentExtension)
                {
                    XmlSchemaComplexContentExtension xmlSchemaComplexContentExtension2 = (XmlSchemaComplexContentExtension)xmlSchemaComplexContentExtension.Clone();
                    xmlSchemaComplexContentExtension2.BaseTypeName = xmlSchemaComplexContentExtension.BaseTypeName.Clone();
                    xmlSchemaComplexContentExtension2.SetAttributes(CloneAttributes(xmlSchemaComplexContentExtension.Attributes));
                    if (HasParticleRef(xmlSchemaComplexContentExtension.Particle, parentSchema))
                    {
                        xmlSchemaComplexContentExtension2.Particle = CloneParticle(xmlSchemaComplexContentExtension.Particle, parentSchema);
                    }
                    xmlSchemaComplexContent2.Content = xmlSchemaComplexContentExtension2;
                }
                else
                {
                    XmlSchemaComplexContentRestriction xmlSchemaComplexContentRestriction = xmlSchemaComplexContent.Content as XmlSchemaComplexContentRestriction;
                    XmlSchemaComplexContentRestriction xmlSchemaComplexContentRestriction2 = (XmlSchemaComplexContentRestriction)xmlSchemaComplexContentRestriction.Clone();
                    xmlSchemaComplexContentRestriction2.BaseTypeName = xmlSchemaComplexContentRestriction.BaseTypeName.Clone();
                    xmlSchemaComplexContentRestriction2.SetAttributes(CloneAttributes(xmlSchemaComplexContentRestriction.Attributes));
                    if (HasParticleRef(xmlSchemaComplexContentRestriction2.Particle, parentSchema))
                    {
                        xmlSchemaComplexContentRestriction2.Particle = CloneParticle(xmlSchemaComplexContentRestriction2.Particle, parentSchema);
                    }
                    xmlSchemaComplexContent2.Content = xmlSchemaComplexContentRestriction2;
                }
                xmlSchemaComplexType.ContentModel = xmlSchemaComplexContent2;
            }
        }
        else
        {
            if (HasParticleRef(xmlSchemaComplexType.Particle, parentSchema))
            {
                xmlSchemaComplexType.Particle = CloneParticle(xmlSchemaComplexType.Particle, parentSchema);
            }
            xmlSchemaComplexType.SetAttributes(CloneAttributes(xmlSchemaComplexType.Attributes));
        }
        xmlSchemaComplexType.ClearCompiledState();
        return xmlSchemaComplexType;
    }
References System.Xml.Schema.XmlSchemaObject.Clone(), System.Xml.Schema.XmlSchemaComplexType.CloneAttributes(), System.Xml.Schema.XmlSchemaComplexType.CloneParticle(), System.Xml.Dictionary, and System.Xml.Schema.XmlSchemaComplexType.HasParticleRef().