Terraria: System.Buffers.MemoryHandle.Dispose
Dispose()
unsafe void System.Buffers.MemoryHandle.Dispose () inline
Implements System.IDisposable.
Definition at line 24 of file MemoryHandle.cs.
    {
        if (_handle.IsAllocated)
        {
            _handle.Free();
        }
        if (_pinnable != null)
        {
            _pinnable.Unpin();
            _pinnable = null;
        }
        _pointer = null;
    }
References System.Buffers.MemoryHandle._handle, System.Buffers.MemoryHandle._pinnable, System.Buffers.MemoryHandle._pointer, System.Runtime.InteropServices.GCHandle.Free(), System.Runtime.InteropServices.GCHandle.IsAllocated, and System.Buffers.IPinnable.Unpin().
Referenced by System.Net.Sockets.SocketAsyncEventArgs.CompleteCore(), System.IO.Compression.Deflater.DeallocateInputBufferHandle(), System.IO.Compression.Inflater.DeallocateInputBufferHandle(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationConnectEx(), System.Net.Sockets.SocketAsyncEventArgs.FreePinHandles(), System.IO.Strategies.Net5CompatFileStreamStrategy.MemoryFileStreamCompletionSource.ReleaseNativeResource(), System.IO.Pipes.PipeStream.PipeValueTaskSource.ReleaseResources(), and Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.ReleaseResources().