Terraria: System.Xml.Schema.XmlListConverter.ChangeListType
ChangeListType()
override object System.Xml.Schema.XmlListConverter.ChangeListType (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline protected virtual
Reimplemented from System.Xml.Schema.XmlBaseConverter.
Reimplemented in System.Xml.Schema.XmlUntypedConverter.
Definition at line 59 of file XmlListConverter.cs.
    {
        Type type = value.GetType();
        if (destinationType == XmlBaseConverter.ObjectType)
        {
            destinationType = base.DefaultClrType;
        }
        if (!(value is IEnumerable) || !IsListType(destinationType))
        {
            throw CreateInvalidClrMappingException(type, destinationType);
        }
        if (destinationType == XmlBaseConverter.StringType)
        {
            if (type == XmlBaseConverter.StringType)
            {
                return value;
            }
            return ListAsString((IEnumerable)value, nsResolver);
        }
        if (type == XmlBaseConverter.StringType)
        {
            value = StringAsList((string)value);
        }
        if (destinationType.IsArray)
        {
            Type elementType = destinationType.GetElementType();
            if (elementType == XmlBaseConverter.ObjectType)
            {
                return ToArray<object>(value, nsResolver);
            }
            if (type == destinationType)
            {
                return value;
            }
            if (elementType == XmlBaseConverter.BooleanType)
            {
                return ToArray<bool>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.ByteType)
            {
                return ToArray<byte>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.ByteArrayType)
            {
                return ToArray<byte[]>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.DateTimeType)
            {
                return ToArray<DateTime>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.DateTimeOffsetType)
            {
                return ToArray<DateTimeOffset>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.DecimalType)
            {
                return ToArray<decimal>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.DoubleType)
            {
                return ToArray<double>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.Int16Type)
            {
                return ToArray<short>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.Int32Type)
            {
                return ToArray<int>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.Int64Type)
            {
                return ToArray<long>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.SByteType)
            {
                return ToArray<sbyte>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.SingleType)
            {
                return ToArray<float>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.StringType)
            {
                return ToArray<string>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.TimeSpanType)
            {
                return ToArray<TimeSpan>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.UInt16Type)
            {
                return ToArray<ushort>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.UInt32Type)
            {
                return ToArray<uint>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.UInt64Type)
            {
                return ToArray<ulong>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.UriType)
            {
                return ToArray<Uri>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.XmlAtomicValueType)
            {
                return ToArray<XmlAtomicValue>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.XmlQualifiedNameType)
            {
                return ToArray<XmlQualifiedName>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.XPathItemType)
            {
                return ToArray<XPathItem>(value, nsResolver);
            }
            if (elementType == XmlBaseConverter.XPathNavigatorType)
            {
                return ToArray<XPathNavigator>(value, nsResolver);
            }
            throw CreateInvalidClrMappingException(type, destinationType);
        }
        if (type == base.DefaultClrType && type != XmlBaseConverter.ObjectArrayType)
        {
            return value;
        }
        return ToList(value, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.BooleanType, System.Xml.Schema.XmlBaseConverter.ByteArrayType, System.Xml.Schema.XmlBaseConverter.ByteType, System.Xml.Schema.XmlListConverter.CreateInvalidClrMappingException(), System.Xml.Schema.XmlBaseConverter.DateTimeOffsetType, System.Xml.Schema.XmlBaseConverter.DateTimeType, System.Xml.Schema.XmlBaseConverter.DecimalType, System.Xml.Dictionary, System.Xml.Schema.XmlBaseConverter.DoubleType, System.elementType, System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.Int16Type, System.Xml.Schema.XmlBaseConverter.Int32Type, System.Xml.Schema.XmlBaseConverter.Int64Type, System.Xml.Schema.XmlListConverter.IsListType(), System.Xml.Schema.XmlListConverter.ListAsString(), System.Xml.Schema.XmlBaseConverter.ObjectArrayType, System.Xml.Schema.XmlBaseConverter.ObjectType, System.Xml.Schema.XmlBaseConverter.SByteType, System.Xml.Schema.XmlBaseConverter.SingleType, System.Xml.Schema.XmlListConverter.StringAsList(), System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlBaseConverter.TimeSpanType, System.Xml.Schema.XmlListConverter.ToList(), System.type, System.Xml.Schema.XmlBaseConverter.UInt16Type, System.Xml.Schema.XmlBaseConverter.UInt32Type, System.Xml.Schema.XmlBaseConverter.UInt64Type, System.Xml.Schema.XmlBaseConverter.UriType, System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, System.Xml.Schema.XmlBaseConverter.XmlQualifiedNameType, System.Xml.Schema.XmlBaseConverter.XPathItemType, and System.Xml.Schema.XmlBaseConverter.XPathNavigatorType.
Referenced by System.Xml.Schema.XmlAnyListConverter.ChangeType(), and System.Xml.Schema.XmlListConverter.ChangeType().