Terraria: WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult
CreateItemResult()
void WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult (CreateItemResult_t param, bool bIOFailure) inline private inherited
             {
                 //IL_0000: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0025: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0026: Unknown result type (might be due to invalid IL or missing references)
                 //IL_002c: Invalid comparison between Unknown and I4
                 //IL_002f: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0030: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0035: Unknown result type (might be due to invalid IL or missing references)
                 if (param.m_bUserNeedsToAcceptWorkshopLegalAgreement)
                 {
                     _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_UserDidNotAcceptWorkshopTermsOfService");
                     _endAction(this);
                 }
                 else if ((int)param.m_eResult == 1)
                 {
                     _publishedFileID = param.m_nPublishedFileId;
                     UpdateItem();
                 }
                 else
                 {
                     _issueReporter.ReportDelayedUploadProblemWithoutKnownReason("Workshop.ReportIssue_FailedToPublish_WithoutKnownReason", ((object)(EResult)(ref param.m_eResult)).ToString());
                     _endAction(this);
                 }
             }
References WorkshopHelper.UGCBased.APublisherInstance._endAction, WorkshopHelper.UGCBased.APublisherInstance._issueReporter, WorkshopHelper.UGCBased.APublisherInstance._publishedFileID, WorkshopIssueReporter.ReportDelayedUploadProblem(), WorkshopIssueReporter.ReportDelayedUploadProblemWithoutKnownReason(), and WorkshopHelper.UGCBased.APublisherInstance.UpdateItem().
Referenced by WorkshopHelper.UGCBased.APublisherInstance.CreateItem(), and WorkshopHelper.UGCBased.APublisherInstance.PublishContent().