Terraria: WorkshopHelper.UGCBased.APublisherInstance.UpdateItemResult
UpdateItemResult()
void WorkshopHelper.UGCBased.APublisherInstance.UpdateItemResult (SubmitItemUpdateResult_t param, bool bIOFailure) inline private inherited
             {
                 //IL_0000: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0025: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0026: Unknown result type (might be due to invalid IL or missing references)
                 //IL_002b: Unknown result type (might be due to invalid IL or missing references)
                 //IL_002c: Unknown result type (might be due to invalid IL or missing references)
                 //IL_002f: Invalid comparison between Unknown and I4
                 //IL_0043: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0046: Invalid comparison between Unknown and I4
                 //IL_0031: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0033: Invalid comparison between Unknown and I4
                 //IL_0048: Unknown result type (might be due to invalid IL or missing references)
                 //IL_004b: Invalid comparison between Unknown and I4
                 //IL_0035: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0037: Invalid comparison between Unknown and I4
                 //IL_0050: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0053: Invalid comparison between Unknown and I4
                 //IL_0039: Unknown result type (might be due to invalid IL or missing references)
                 //IL_003c: Invalid comparison between Unknown and I4
                 if (param.m_bUserNeedsToAcceptWorkshopLegalAgreement)
                 {
                     _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_UserDidNotAcceptWorkshopTermsOfService");
                     _endAction(this);
                     return;
                 }
                 EResult eResult = param.m_eResult;
                 if ((int)eResult <= 9)
                 {
                     if ((int)eResult != 1)
                     {
                         if ((int)eResult != 8)
{
                             if ((int)eResult != 9)
{
                                 goto IL_0079;
                             }
                             _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_CouldNotFindFolderToUpload");
                         }
                         else
{
                             _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_InvalidParametersForPublishing");
                         }
                     }
                     else
                     {
                         SteamFriends.ActivateGameOverlayToWebPage("steam://url/CommunityFilePage/" + _publishedFileID.m_PublishedFileId, (EActivateGameOverlayToWebPageMode)0);
                     }
                 }
                 else if ((int)eResult != 15)
                 {
                     if ((int)eResult != 25)
                     {
                         if ((int)eResult != 33)
{
                             goto IL_0079;
                         }
                         _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_SteamFileLockFailed");
                     }
                     else
                     {
                         _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_LimitExceeded");
                     }
                 }
                 else
                 {
                     _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_AccessDeniedBecauseUserDoesntOwnLicenseForApp");
                 }
                 goto IL_00f5;
                 IL_00f5:
                 _endAction(this);
                 return;
                 IL_0079:
                 _issueReporter.ReportDelayedUploadProblemWithoutKnownReason("Workshop.ReportIssue_FailedToPublish_WithoutKnownReason", ((object)(EResult)(ref param.m_eResult)).ToString());
                 goto IL_00f5;
             }
References WorkshopHelper.UGCBased.APublisherInstance._endAction, WorkshopHelper.UGCBased.APublisherInstance._issueReporter, WorkshopHelper.UGCBased.APublisherInstance._publishedFileID, WorkshopIssueReporter.ReportDelayedUploadProblem(), and WorkshopIssueReporter.ReportDelayedUploadProblemWithoutKnownReason().
Referenced by WorkshopHelper.UGCBased.APublisherInstance.PublishContent(), and WorkshopHelper.UGCBased.APublisherInstance.UpdateItem().