Terraria: WorkshopHelper.UGCBased.APublisherInstance.CreateItem
CreateItem()
void WorkshopHelper.UGCBased.APublisherInstance.CreateItem () inline private inherited
             {
                 //IL_0006: Unknown result type (might be due to invalid IL or missing references)
                 //IL_000c: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0011: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0018: Unknown result type (might be due to invalid IL or missing references)
                 CoreSocialModule.SetSkipPulsing(shouldSkipPausing: true);
                 SteamAPICall_t val = SteamUGC.CreateItem(SteamUtils.GetAppID(), (EWorkshopFileType)0);
                 _createItemHook.Set(val, (APIDispatchDelegate<CreateItemResult_t>)CreateItemResult);
                 CoreSocialModule.SetSkipPulsing(shouldSkipPausing: false);
             }
References WorkshopHelper.UGCBased.APublisherInstance._createItemHook, WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult(), and CoreSocialModule.SetSkipPulsing().
Referenced by WorkshopHelper.UGCBased.APublisherInstance.PublishContent().