Terraria: DropBasedOnMasterMode.ReportDroprates
ReportDroprates()
void DropBasedOnMasterMode.ReportDroprates (List< DropRateInfo > drops, DropRateInfoChainFeed ratesInfo) inline
Implements IItemDropRule.
     {
         DropRateInfoChainFeed ratesInfo2 = ratesInfo.With(1f);
         ratesInfo2.AddCondition(new Conditions.IsMasterMode());
         ruleForMasterMode.ReportDroprates(drops, ratesInfo2);
         DropRateInfoChainFeed ratesInfo3 = ratesInfo.With(1f);
         ratesInfo3.AddCondition(new Conditions.NotMasterMode());
         ruleForDefault.ReportDroprates(drops, ratesInfo3);
         Chains.ReportDroprates(ChainedRules, 1f, drops, ratesInfo);
     }
References DropRateInfoChainFeed.AddCondition(), ChainedRules, IItemDropRule.ReportDroprates(), Chains.ReportDroprates(), ruleForDefault, ruleForMasterMode, and DropRateInfoChainFeed.With().