Terraria: WorkshopHelper.UGCBased.APublisherInstance.PublishContent
PublishContent()
void WorkshopHelper.UGCBased.APublisherInstance.PublishContent (PublishedItemsFinder finder, WorkshopIssueReporter issueReporter, FinishedPublishingAction endAction, string itemTitle, string itemDescription, string contentFolderPath, string previewImagePath, WorkshopItemPublicSettingId publicity, string[] tags) inline inherited
             {
                 //IL_003f: Unknown result type (might be due to invalid IL or missing references)
                 //IL_0044: Unknown result type (might be due to invalid IL or missing references)
                 //IL_007d: Unknown result type (might be due to invalid IL or missing references)
                 //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
                 //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
                 _issueReporter = issueReporter;
                 _endAction = endAction;
                 _createItemHook = CallResult<CreateItemResult_t>.Create((APIDispatchDelegate<CreateItemResult_t>)CreateItemResult);
                 _updateItemHook = CallResult<SubmitItemUpdateResult_t>.Create((APIDispatchDelegate<SubmitItemUpdateResult_t>)UpdateItemResult);
                 ERemoteStoragePublishedFileVisibility visibility = GetVisibility(publicity);
                 _entryData = new SteamWorkshopItem
                 {
                     Title = itemTitle,
                     Description = itemDescription,
                     ContentFolderPath = contentFolderPath,
                     Tags = tags,
                     PreviewImagePath = previewImagePath,
                     Visibility = visibility
                 };
                 ulong? num = null;
                 if (AWorkshopEntry.TryReadingManifest(contentFolderPath + Path.DirectorySeparatorChar + "workshop.json", out var info))
                 {
                     num = info.workshopEntryId;
                 }
                 if (num.HasValue && finder.HasItemOfId(num.Value))
                 {
                     _publishedFileID = new PublishedFileId_t(num.Value);
                     PreventUpdatingCertainThings();
                     UpdateItem();
                 }
                 else
                 {
                     CreateItem();
                 }
             }
References WorkshopHelper.UGCBased.APublisherInstance._createItemHook, WorkshopHelper.UGCBased.APublisherInstance._endAction, WorkshopHelper.UGCBased.APublisherInstance._entryData, WorkshopHelper.UGCBased.APublisherInstance._issueReporter, WorkshopHelper.UGCBased.APublisherInstance._publishedFileID, WorkshopHelper.UGCBased.APublisherInstance._updateItemHook, WorkshopHelper.UGCBased.APublisherInstance.CreateItem(), WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult(), WorkshopHelper.UGCBased.APublisherInstance.GetVisibility(), WorkshopHelper.UGCBased.PublishedItemsFinder.HasItemOfId(), WorkshopHelper.UGCBased.APublisherInstance.PreventUpdatingCertainThings(), AWorkshopEntry.TryReadingManifest(), WorkshopHelper.UGCBased.APublisherInstance.UpdateItem(), and WorkshopHelper.UGCBased.APublisherInstance.UpdateItemResult().