Terraria: System.Xml.XmlException.IsCatchableException
IsCatchableException()
static bool System.Xml.XmlException.IsCatchableException (Exception e) inline static package
Definition at line 273 of file XmlException.cs.
    {
        if (!(e is OutOfMemoryException))
        {
            return !(e is NullReferenceException);
        }
        return false;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.Compile(), System.Xml.Xsl.Runtime.XmlQueryContext.GetDataSource(), System.Xml.Xsl.Runtime.XmlExtensionFunction.Invoke(), System.Xml.Xsl.XsltOld.XsltCompileContext.FuncDocument.Invoke(), and System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet().