Terraria: System.Xml.XmlException.CreateMessage
CreateMessage()
static string System.Xml.XmlException.CreateMessage (string res, string[] args, int lineNumber, int linePosition) inline static private
Definition at line 206 of file XmlException.cs.
    {
        try
        {
            string text;
            if (args != null)
            {
                object[] args2 = args;
                text = string.Format(res, args2);
            }
            else
            {
                text = res;
            }
            string text2 = text;
            if (lineNumber != 0)
            {
                string text3 = lineNumber.ToString(CultureInfo.InvariantCulture);
                string text4 = linePosition.ToString(CultureInfo.InvariantCulture);
                string xml_MessageWithErrorPosition = System.SR.Xml_MessageWithErrorPosition;
                object[] args2 = new string[3] { text2, text3, text4 };
                text2 = System.SR.Format(xml_MessageWithErrorPosition, args2);
            }
            return text2;
        }
        catch (MissingManifestResourceException)
        {
            return "UNKNOWN(" + res + ")";
        }
    }
References System.Xml.Dictionary, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.text, and System.SR.Xml_MessageWithErrorPosition.
Referenced by System.Xml.XmlException.XmlException(), and System.Xml.XmlException.FormatUserMessage().