Terraria: System.Xml.XmlException.BuildCharExceptionArgs
BuildCharExceptionArgs() [3/3]
static string[] System.Xml.XmlException.BuildCharExceptionArgs (string data, int invCharIndex) inline static package
Definition at line 237 of file XmlException.cs.
    {
        return BuildCharExceptionArgs(data[invCharIndex], (invCharIndex + 1 < data.Length) ? data[invCharIndex + 1] : '\0');
    }
References System.Xml.XmlException.BuildCharExceptionArgs(), and System.Xml.Dictionary.
Referenced by System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlDocument.CheckName(), System.Xml.XmlCharCheckingReader.CheckWhitespace(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.XmlConvert.CreateInvalidNameCharException(), System.Xml.ValidateNames.GetInvalidNameException(), System.Xml.XmlWellFormedWriter.InvalidCharsException(), System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync(), System.Xml.XmlTextReaderImpl.ParseElementAsync_NoAttributes(), System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(), System.Xml.XmlTextReaderImpl.ParsePI(), System.Xml.XmlTextReaderImpl.ParsePIAsync(), System.Xml.XmlTextReaderImpl.ParseQName(), System.Xml.XmlTextReaderImpl.ParseQNameAsync(), System.Xml.XmlCharCheckingReader.Read(), System.Xml.XmlCharCheckingReader.ReadAsync(), System.Xml.DtdParser.ScanLiteral(), System.Xml.DtdParser.ScanLiteralAsync(), System.Xml.DtdParser.ScanNmtoken(), System.Xml.DtdParser.ScanNmtokenAsync(), System.Xml.DtdParser.ScanQName(), System.Xml.DtdParser.ScanQNameAsync(), System.Xml.ValidateNames.SplitQName(), System.Xml.DtdParser.ThrowInvalidChar(), System.Xml.XmlTextReaderImpl.ThrowInvalidChar(), System.Xml.DtdParser.ThrowInvalidChar(), System.Xml.ValidateNames.ThrowInvalidName(), System.Xml.XmlConvert.TryVerifyName(), System.Xml.XmlConvert.TryVerifyNMTOKEN(), System.Xml.XmlEncodedRawTextWriter.ValidateContentChars(), System.Xml.XmlUtf8RawTextWriter.ValidateContentChars(), System.Xml.Schema.Preprocessor.ValidateNameAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateNameAttribute(), System.Xml.XmlCharCheckingWriter.ValidateNCName(), System.Xml.XmlCharCheckingWriter.ValidateQName(), System.Xml.XmlConvert.VerifyNMTOKEN(), System.Xml.XmlConvert.VerifyQName(), System.Xml.XmlConvert.VerifyWhitespace(), System.Xml.XmlWellFormedWriter.WriteDocType(), System.Xml.XmlWellFormedWriter.WriteDocTypeAsync(), System.Xml.XmlCharCheckingWriter.WriteWhitespace(), and System.Xml.XmlCharCheckingWriter.WriteWhitespaceAsync().