Terraria: System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper.Clone
Clone()
object System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper.Clone () inline
Implements System.ICloneable.
Definition at line 58 of file ArrayList.cs.
            {
                IListWrapperEnumWrapper listWrapperEnumWrapper = new IListWrapperEnumWrapper();
                listWrapperEnumWrapper._en = (IEnumerator)((ICloneable)_en).Clone();
                listWrapperEnumWrapper._initialStartIndex = _initialStartIndex;
                listWrapperEnumWrapper._initialCount = _initialCount;
                listWrapperEnumWrapper._remaining = _remaining;
                listWrapperEnumWrapper._firstCall = _firstCall;
                return listWrapperEnumWrapper;
            }
References System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper.IListWrapperEnumWrapper(), System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper._en, System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper._firstCall, System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper._initialCount, System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper._initialStartIndex, System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper._remaining, and System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper.Clone().
Referenced by System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper.Clone().