Terraria: System.Runtime.Serialization.Attributes.Reset
Reset()
void System.Runtime.Serialization.Attributes.Reset () inline package
Definition at line 92 of file Attributes.cs.
    {
        Id = Globals.NewObjectId;
        Ref = Globals.NewObjectId;
        XsiTypeName = null;
        XsiTypeNamespace = null;
        XsiTypePrefix = null;
        XsiNil = false;
        ClrAssembly = null;
        ClrType = null;
        ArraySZSize = -1;
        FactoryTypeName = null;
        FactoryTypeNamespace = null;
        FactoryTypePrefix = null;
        UnrecognizedAttributesFound = false;
    }
References System.Runtime.Serialization.Attributes.ArraySZSize, System.Runtime.Serialization.Attributes.ClrAssembly, System.Runtime.Serialization.Attributes.ClrType, System.Runtime.Serialization.Attributes.FactoryTypeName, System.Runtime.Serialization.Attributes.FactoryTypeNamespace, System.Runtime.Serialization.Attributes.FactoryTypePrefix, System.Runtime.Serialization.Attributes.Id, System.Runtime.Serialization.Globals.NewObjectId, System.Runtime.Serialization.Attributes.UnrecognizedAttributesFound, System.Runtime.Serialization.Attributes.XsiNil, System.Runtime.Serialization.Attributes.XsiTypeName, System.Runtime.Serialization.Attributes.XsiTypeNamespace, and System.Runtime.Serialization.Attributes.XsiTypePrefix.
Referenced by System.Runtime.Serialization.Attributes.Read(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadAttributes(), and System.Runtime.Serialization.XmlObjectSerializerReadContext.ResetAttributes().