Terraria: System.Runtime.Serialization.Attributes.Read
Read()
void System.Runtime.Serialization.Attributes.Read (XmlReaderDelegator reader) inline package
Definition at line 49 of file Attributes.cs.
    {
        Reset();
        while (reader.MoveToNextAttribute())
        {
            switch (reader.IndexOfLocalName(s_serializationLocalNames, DictionaryGlobals.SerializationNamespace))
            {
            case 0:
                ReadId(reader);
                continue;
            case 1:
                ReadArraySize(reader);
                continue;
            case 2:
                ReadRef(reader);
                continue;
            case 3:
                ClrType = reader.Value;
                continue;
            case 4:
                ClrAssembly = reader.Value;
                continue;
            case 5:
                ReadFactoryType(reader);
                continue;
            }
            switch (reader.IndexOfLocalName(s_schemaInstanceLocalNames, DictionaryGlobals.SchemaInstanceNamespace))
            {
            case 0:
                ReadXsiNil(reader);
                continue;
            case 1:
                ReadXsiType(reader);
                continue;
            }
            if (!reader.IsNamespaceUri(DictionaryGlobals.XmlnsNamespace))
            {
                UnrecognizedAttributesFound = true;
            }
        }
        reader.MoveToElement();
    }
References System.Runtime.Serialization.Attributes.ClrAssembly, System.Runtime.Serialization.Attributes.ClrType, System.Runtime.Serialization.XmlReaderDelegator.IndexOfLocalName(), System.Runtime.Serialization.XmlReaderDelegator.IsNamespaceUri(), System.Runtime.Serialization.XmlReaderDelegator.MoveToElement(), System.Runtime.Serialization.XmlReaderDelegator.MoveToNextAttribute(), System.Runtime.Serialization.Attributes.ReadArraySize(), System.Runtime.Serialization.Attributes.ReadFactoryType(), System.Runtime.Serialization.Attributes.ReadId(), System.Runtime.Serialization.Attributes.ReadRef(), System.Runtime.Serialization.Attributes.ReadXsiNil(), System.Runtime.Serialization.Attributes.ReadXsiType(), System.Runtime.Serialization.Attributes.Reset(), System.Runtime.Serialization.Attributes.s_schemaInstanceLocalNames, System.Runtime.Serialization.Attributes.s_serializationLocalNames, System.Runtime.Serialization.DictionaryGlobals.SchemaInstanceNamespace, System.Runtime.Serialization.DictionaryGlobals.SerializationNamespace, System.Runtime.Serialization.Attributes.UnrecognizedAttributesFound, System.Runtime.Serialization.XmlReaderDelegator.Value, and System.Runtime.Serialization.DictionaryGlobals.XmlnsNamespace.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAndResolveUnknownXmlData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAttributes(), and System.Runtime.Serialization.PrimitiveDataContract.TryReadNullAtTopLevel().