Terraria: System.Runtime.CompilerServices.AsyncMethodBuilderCore.SetStateMachine
SetStateMachine()
static void System.Runtime.CompilerServices.AsyncMethodBuilderCore.SetStateMachine (IAsyncStateMachine stateMachine, Task task) inline static
Definition at line 71 of file AsyncMethodBuilderCore.cs.
    {
        if (stateMachine == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.stateMachine);
        }
        if (task != null)
        {
            ThrowHelper.ThrowInvalidOperationException(ExceptionResource.AsyncMethodBuilder_InstanceNotInitialized);
        }
    }
References System.stateMachine, System.task, System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowInvalidOperationException().
Referenced by System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.SetStateMachine(), System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder< TResult >.SetStateMachine(), and System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.SetStateMachine().