Terraria: System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetAsyncStateMachineDescription
GetAsyncStateMachineDescription()
static string System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetAsyncStateMachineDescription (IAsyncStateMachine stateMachine) inline static package
Definition at line 84 of file AsyncMethodBuilderCore.cs.
    {
        Type type = stateMachine.GetType();
        FieldInfo[] fields = type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.AppendLine(type.FullName);
        FieldInfo[] array = fields;
        foreach (FieldInfo fieldInfo in array)
        {
            stringBuilder.Append("    ").Append(fieldInfo.Name).Append(": ")
                .Append(fieldInfo.GetValue(stateMachine))
                .AppendLine();
        }
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.AppendLine(), System.array, System.Type.GetType(), System.Reflection.FieldInfo.GetValue(), System.Reflection.MemberInfo.Name, System.stateMachine, and System.type.
Referenced by System.Threading.Tasks.TplEventSource.IncompleteAsyncMethod().