Terraria: System.Xml.XmlSqlBinaryReader.AttrInfo.Set
Set() [2/2]
void System.Xml.XmlSqlBinaryReader.AttrInfo.Set (QName n, string v) inline
Definition at line 163 of file XmlSqlBinaryReader.cs.
        {
            name = n;
            val = v;
            contentPos = 0;
            hashCode = 0;
            prevHash = 0;
        }
References System.Xml.XmlSqlBinaryReader.AttrInfo.contentPos, System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.AttrInfo.hashCode, System.Xml.XmlSqlBinaryReader.AttrInfo.name, System.Xml.XmlSqlBinaryReader.AttrInfo.prevHash, and System.Xml.XmlSqlBinaryReader.AttrInfo.val.
Referenced by System.Xml.XmlSqlBinaryReader.GenerateImpliedXmlnsAttrs(), System.Xml.XmlSqlBinaryReader.ImplReadDoctype(), System.Xml.XmlSqlBinaryReader.ReadInit(), and System.Xml.XmlSqlBinaryReader.ScanAttributes().