Terraria: System.Linq.Parallel.QueryOpeningEnumerator.OpenQuery
OpenQuery()
void System.Linq.Parallel.QueryOpeningEnumerator< TOutput >.OpenQuery () inline private
Definition at line 79 of file QueryOpeningEnumerator.cs.
    {
        if (_hasQueryOpeningFailed)
        {
            throw new InvalidOperationException(System.SR.PLINQ_EnumerationPreviouslyFailed);
        }
        try
        {
            _querySettings = _queryOperator.SpecifiedQuerySettings.WithPerExecutionSettings(_topLevelCancellationTokenSource, _topLevelDisposedFlag).WithDefaults();
            QueryLifecycle.LogicalQueryExecutionBegin(_querySettings.QueryId);
            _openedQueryEnumerator = _queryOperator.GetOpenedEnumerator(_mergeOptions, _suppressOrderPreservation, forEffect: false, _querySettings);
            CancellationState.ThrowWithStandardMessageIfCanceled(_querySettings.CancellationState.ExternalCancellationToken);
        }
        catch
        {
            _hasQueryOpeningFailed = true;
            throw;
        }
    }
References System.Linq.Parallel.QueryOpeningEnumerator< TOutput >._hasQueryOpeningFailed, System.Linq.Parallel.QueryOpeningEnumerator< TOutput >._mergeOptions, System.Linq.Parallel.QueryOpeningEnumerator< TOutput >._openedQueryEnumerator, System.Linq.Parallel.QueryOpeningEnumerator< TOutput >._queryOperator, System.Linq.Parallel.QueryOpeningEnumerator< TOutput >._querySettings, System.Linq.Parallel.QueryOpeningEnumerator< TOutput >._suppressOrderPreservation, System.Linq.Parallel.QueryOpeningEnumerator< TOutput >._topLevelCancellationTokenSource, System.Linq.Parallel.QueryOpeningEnumerator< TOutput >._topLevelDisposedFlag, System.Linq.Parallel.QuerySettings.CancellationState, System.Linq.Parallel.CancellationState.ExternalCancellationToken, System.Linq.Parallel.QueryLifecycle.LogicalQueryExecutionBegin(), System.SR.PLINQ_EnumerationPreviouslyFailed, System.Linq.Parallel.QuerySettings.QueryId, and System.Linq.Parallel.CancellationState.ThrowWithStandardMessageIfCanceled().
Referenced by System.Linq.Parallel.QueryOpeningEnumerator< TOutput >.MoveNext().