Terraria: System.Net.Http.MultipartContent.SerializeToStream
SerializeToStream()
override void System.Net.Http.MultipartContent.SerializeToStream (Stream stream, TransportContext? context, CancellationToken cancellationToken) inline protected virtual inherited
Reimplemented from System.Net.Http.HttpContent.
Definition at line 356 of file MultipartContent.cs.
    {
        try
        {
            WriteToStream(stream, "--" + _boundary + "\r\n");
            for (int i = 0; i < _nestedContent.Count; i++)
            {
                HttpContent httpContent = _nestedContent[i];
                SerializeHeadersToStream(stream, httpContent, i != 0);
                httpContent.CopyTo(stream, context, cancellationToken);
            }
            WriteToStream(stream, "\r\n--" + _boundary + "--\r\n");
        }
        catch (Exception message)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, message, "SerializeToStream");
            }
            throw;
        }
    }
References System.Net.Http.MultipartContent._boundary, System.Net.Http.MultipartContent._nestedContent, System.cancellationToken, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.NetEventSource.Error(), System.Net.NetEventSource.Log, System.Net.Http.MultipartContent.SerializeHeadersToStream(), System.stream, and System.Net.Http.MultipartContent.WriteToStream().