Terraria: System.Net.Http.MultipartContent.SerializeHeadersToStream
SerializeHeadersToStream()
void System.Net.Http.MultipartContent.SerializeHeadersToStream (Stream stream, HttpContent content, bool writeDivider) inline private inherited
Definition at line 491 of file MultipartContent.cs.
    {
        if (writeDivider)
        {
            WriteToStream(stream, "\r\n--");
            WriteToStream(stream, _boundary);
            WriteToStream(stream, "\r\n");
        }
        foreach (KeyValuePair<string, HeaderStringValues> item in content.Headers.NonValidated)
        {
            Encoding encoding = HeaderEncodingSelector?.Invoke(item.Key, content) ?? HttpRuleParser.DefaultHttpEncoding;
            WriteToStream(stream, item.Key);
            WriteToStream(stream, ": ");
            string content2 = string.Empty;
            foreach (string item2 in item.Value)
            {
                WriteToStream(stream, content2);
                WriteToStream(stream, item2, encoding);
                content2 = ", ";
            }
            WriteToStream(stream, "\r\n");
        }
        WriteToStream(stream, "\r\n");
    }
References System.Net.Http.MultipartContent._boundary, System.Net.Http.HttpRuleParser.DefaultHttpEncoding, System.Net.Http.MultipartContent.HeaderEncodingSelector, System.item, System.stream, and System.Net.Http.MultipartContent.WriteToStream().
Referenced by System.Net.Http.MultipartContent.EncodeHeadersToNewStream(), System.Net.Http.MultipartContent.SerializeToStream(), and System.Net.Http.MultipartContent.SerializeToStreamAsyncCore().