Terraria: System.Net.Http.MultipartContent.SerializeToStreamAsyncCore
SerializeToStreamAsyncCore()
async Task System.Net.Http.MultipartContent.SerializeToStreamAsyncCore (Stream stream, TransportContext context, CancellationToken cancellationToken) inline protected inherited
Definition at line 393 of file MultipartContent.cs.
    {
        _ = 3;
        try
        {
            await EncodeStringToStreamAsync(stream, "--" + _boundary + "\r\n", cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            MemoryStream output = new MemoryStream();
            for (int contentIndex = 0; contentIndex < _nestedContent.Count; contentIndex++)
            {
                HttpContent content = _nestedContent[contentIndex];
                output.SetLength(0L);
                SerializeHeadersToStream(output, content, contentIndex != 0);
                output.Position = 0L;
                await output.CopyToAsync(stream, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                await content.CopyToAsync(stream, context, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            await EncodeStringToStreamAsync(stream, "\r\n--" + _boundary + "--\r\n", cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (Exception message)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, message, "SerializeToStreamAsyncCore");
            }
            throw;
        }
    }
References System.Net.Http.MultipartContent._boundary, System.Net.Http.MultipartContent._nestedContent, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.HttpContent.CopyToAsync(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Http.MultipartContent.EncodeStringToStreamAsync(), System.Net.NetEventSource.Error(), System.L, System.Net.NetEventSource.Log, System.Net.Http.MultipartContent.SerializeHeadersToStream(), and System.stream.
Referenced by System.Net.Http.MultipartContent.SerializeToStreamAsync(), System.Net.Http.MultipartContent.SerializeToStreamAsync(), and System.Net.Http.MultipartFormDataContent.SerializeToStreamAsync().