Terraria: System.Net.Http.MultipartContent.CreateContentReadStreamAsyncCore
CreateContentReadStreamAsyncCore()
async ValueTask< Stream > System.Net.Http.MultipartContent.CreateContentReadStreamAsyncCore (bool async, CancellationToken cancellationToken) inline private inherited
Definition at line 440 of file MultipartContent.cs.
    {
        _ = 1;
        try
        {
            Stream[] streams = new Stream[2 + _nestedContent.Count * 2];
            int streamIndex = 0;
            streams[streamIndex++] = EncodeStringToNewStream("--" + _boundary + "\r\n");
            for (int contentIndex = 0; contentIndex < _nestedContent.Count; contentIndex++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                HttpContent httpContent = _nestedContent[contentIndex];
                streams[streamIndex++] = EncodeHeadersToNewStream(httpContent, contentIndex != 0);
                Stream stream3;
                if (async)
                {
                    Stream stream = httpContent.TryReadAsStream();
                    Stream stream2 = stream;
                    if (stream2 == null)
                    {
                        stream2 = await httpContent.ReadAsStreamAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    }
                    stream3 = stream2;
                }
                else
                {
                    stream3 = httpContent.ReadAsStream(cancellationToken);
                }
                if (stream3 == null)
                {
                    stream3 = new MemoryStream();
                }
                if (!stream3.CanSeek)
                {
                    return (!async) ? base.CreateContentReadStream(cancellationToken) : (await base.CreateContentReadStreamAsync().ConfigureAwait(continueOnCapturedContext: false));
                }
                streams[streamIndex++] = stream3;
            }
            streams[streamIndex] = EncodeStringToNewStream("\r\n--" + _boundary + "--\r\n");
            return new ContentReadStream(streams);
        }
        catch (Exception message)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, message, "CreateContentReadStreamAsyncCore");
            }
            throw;
        }
    }
References System.Net.Http.MultipartContent._boundary, System.Net.Http.MultipartContent._nestedContent, System.cancellationToken, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Http.MultipartContent.EncodeHeadersToNewStream(), System.Net.Http.MultipartContent.EncodeStringToNewStream(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Log, and System.stream.
Referenced by System.Net.Http.MultipartContent.CreateContentReadStream(), System.Net.Http.MultipartContent.CreateContentReadStreamAsync(), and System.Net.Http.MultipartContent.CreateContentReadStreamAsync().