Terraria: MS.Internal.Xml.XPath.ResetableIterator.Reset
Reset()
void MS.Internal.Xml.XPath.ResetableIterator.Reset () abstract
Referenced by MS.Internal.Xml.XPath.BaseAxisQuery.Reset(), MS.Internal.Xml.XPath.ExtensionQuery.Reset(), MS.Internal.Xml.XPath.FilterQuery.Reset(), MS.Internal.Xml.XPath.LogicalExpr.NodeSet.Reset(), MS.Internal.Xml.XPath.UnionExpr.Reset(), MS.Internal.Xml.XPath.XPathMultyIterator.Reset(), and MS.Internal.Xml.XPath.XPathSelectionIterator.Reset().