Terraria: Collision.StepUp
StepUp()
static void Collision.StepUp (ref Vector2 position, ref Vector2 velocity, int width, int height, ref float stepSpeed, ref float gfxOffY, int gravDir = 1, bool holdsMatching = false, int specialChecksMode = 0) inline static
     {
         int num = 0;
         if (velocity.X < 0f)
         {
             num = -1;
         }
         if (velocity.X > 0f)
         {
             num = 1;
         }
         Vector2 vector = position;
         vector.X += velocity.X;
         int num2 = (int)((vector.X + (float)(width / 2) + (float)((width / 2 + 1) * num)) / 16f);
         int num3 = (int)(((double)vector.Y + 0.1) / 16.0);
         if (gravDir == 1)
         {
             num3 = (int)((vector.Y + (float)height - 1f) / 16f);
         }
         int num4 = height / 16 + ((height % 16 != 0) ? 1 : 0);
         bool flag = true;
         bool flag2 = true;
         if (Main.tile[num2, num3] == null)
         {
             return;
         }
         for (int i = 1; i < num4 + 2; i++)
         {
             if (!WorldGen.InWorld(num2, num3 - i * gravDir) || Main.tile[num2, num3 - i * gravDir] == null)
             {
                 return;
             }
         }
         if (!WorldGen.InWorld(num2 - num, num3 - num4 * gravDir) || Main.tile[num2 - num, num3 - num4 * gravDir] == null)
         {
             return;
         }
         Tile tile;
         for (int j = 2; j < num4 + 1; j++)
         {
             if (!WorldGen.InWorld(num2, num3 - j * gravDir) || Main.tile[num2, num3 - j * gravDir] == null)
             {
                 return;
             }
             tile = Main.tile[num2, num3 - j * gravDir];
             flag = flag && (!tile.nactive() || !Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type]);
         }
         tile = Main.tile[num2 - num, num3 - num4 * gravDir];
         flag2 = flag2 && (!tile.nactive() || !Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type]);
         bool flag3 = true;
         bool flag4 = true;
         bool flag5 = true;
         Tile tile2;
         if (gravDir == 1)
         {
             if (Main.tile[num2, num3 - gravDir] == null || Main.tile[num2, num3 - (num4 + 1) * gravDir] == null)
             {
                 return;
             }
             tile = Main.tile[num2, num3 - gravDir];
             tile2 = Main.tile[num2, num3 - (num4 + 1) * gravDir];
             flag3 = flag3 && (!tile.nactive() || !Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type] || (tile.slope() == 1 && position.X + (float)(width / 2) > (float)(num2 * 16)) || (tile.slope() == 2 && position.X + (float)(width / 2) < (float)(num2 * 16 + 16)) || (tile.halfBrick() && (!tile2.nactive() || !Main.tileSolid[tile2.type] || Main.tileSolidTop[tile2.type])));
             tile = Main.tile[num2, num3];
             tile2 = Main.tile[num2, num3 - 1];
             if (specialChecksMode == 1)
             {
                 flag5 = tile.type != 16 && tile.type != 18 && tile.type != 14 && tile.type != 469 && tile.type != 134;
             }
             flag4 = flag4 && ((tile.nactive() && (!tile.topSlope() || (tile.slope() == 1 && position.X + (float)(width / 2) < (float)(num2 * 16)) || (tile.slope() == 2 && position.X + (float)(width / 2) > (float)(num2 * 16 + 16))) && (!tile.topSlope() || position.Y + (float)height > (float)(num3 * 16)) && ((Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type]) || (holdsMatching && ((Main.tileSolidTop[tile.type] && tile.frameY == 0) || TileID.Sets.Platforms[tile.type]) && (!Main.tileSolid[tile2.type] || !tile2.nactive()) && flag5))) || (tile2.halfBrick() && tile2.nactive()));
             flag4 &= !Main.tileSolidTop[tile.type] || !Main.tileSolidTop[tile2.type];
         }
         else
         {
             tile = Main.tile[num2, num3 - gravDir];
             tile2 = Main.tile[num2, num3 - (num4 + 1) * gravDir];
             flag3 = flag3 && (!tile.nactive() || !Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type] || tile.slope() != 0 || (tile.halfBrick() && (!tile2.nactive() || !Main.tileSolid[tile2.type] || Main.tileSolidTop[tile2.type])));
             tile = Main.tile[num2, num3];
             tile2 = Main.tile[num2, num3 + 1];
             flag4 = flag4 && ((tile.nactive() && ((Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type]) || (holdsMatching && Main.tileSolidTop[tile.type] && tile.frameY == 0 && (!Main.tileSolid[tile2.type] || !tile2.nactive())))) || (tile2.halfBrick() && tile2.nactive()));
         }
         if (!((float)(num2 * 16) < vector.X + (float)width) || !((float)(num2 * 16 + 16) > vector.X))
         {
             return;
         }
         if (gravDir == 1)
         {
             if (!(flag4 && flag3 && flag && flag2))
             {
                 return;
             }
             float num5 = num3 * 16;
             if (Main.tile[num2, num3 - 1].halfBrick())
             {
                 num5 -= 8f;
             }
             else if (Main.tile[num2, num3].halfBrick())
             {
                 num5 += 8f;
             }
             if (!(num5 < vector.Y + (float)height))
             {
                 return;
             }
             float num6 = vector.Y + (float)height - num5;
             if ((double)num6 <= 16.1)
             {
                 gfxOffY += position.Y + (float)height - num5;
                 position.Y = num5 - (float)height;
                 if (num6 < 9f)
                 {
                     stepSpeed = 1f;
                 }
                 else
                 {
                     stepSpeed = 2f;
                 }
             }
         }
         else
         {
             if (!(flag4 && flag3 && flag && flag2) || Main.tile[num2, num3].bottomSlope() || TileID.Sets.Platforms[tile2.type])
             {
                 return;
             }
             float num7 = num3 * 16 + 16;
             if (!(num7 > vector.Y))
             {
                 return;
             }
             float num8 = num7 - vector.Y;
             if ((double)num8 <= 16.1)
             {
                 gfxOffY -= num7 - position.Y;
                 position.Y = num7;
                 velocity.Y = 0f;
                 if (num8 < 9f)
                 {
                     stepSpeed = 1f;
                 }
                 else
                 {
                     stepSpeed = 2f;
                 }
             }
         }
     }
References Tile.bottomSlope(), Tile.halfBrick(), WorldGen.InWorld(), Tile.nactive(), TileID.Sets.Platforms, Tile.slope(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by NPC.AI_007_TownEntities(), Projectile.AI_026(), Projectile.AI_067_FreakingPirates(), NPC.AI_107_ImprovedWalkers(), Player.DryCollision(), and Player.Update().