Terraria: Collision.ExpandVertically
ExpandVertically()
static void Collision.ExpandVertically (int startX, int startY, out int topY, out int bottomY, int maxExpandUp = 100, int maxExpandDown = 100) inline static
     {
         topY = startY;
         bottomY = startY;
         if (!WorldGen.InWorld(startX, startY, 10))
         {
             return;
         }
         for (int i = 0; i < maxExpandUp; i++)
         {
             if (topY <= 0)
             {
                 break;
             }
             if (topY < 10)
             {
                 break;
             }
             if (Main.tile[startX, topY] == null)
             {
                 break;
             }
             if (WorldGen.SolidTile3(startX, topY))
             {
                 break;
             }
             topY--;
         }
         for (int j = 0; j < maxExpandDown; j++)
         {
             if (bottomY >= Main.maxTilesY - 10)
             {
                 break;
             }
             if (bottomY > Main.maxTilesY - 10)
             {
                 break;
             }
             if (Main.tile[startX, bottomY] == null)
             {
                 break;
             }
             if (WorldGen.SolidTile3(startX, bottomY))
             {
                 break;
             }
             bottomY++;
         }
     }
References WorldGen.InWorld(), Main.maxTilesY, WorldGen.SolidTile3(), and Main.tile.
Referenced by NPC.AI(), StrayMethods.CanSpawnSandstormFriendly(), StrayMethods.CanSpawnSandstormHostile(), StrayMethods.CheckArenaScore(), Main.DrawProjDirect(), and StrayMethods.SendWalker().