Terraria: Collision.WalkDownSlope
WalkDownSlope()
static Vector4 Collision.WalkDownSlope (Vector2 Position, Vector2 Velocity, int Width, int Height, float gravity = 0f) inline static
     {
         if (Velocity.Y != gravity)
         {
             return new Vector4(Position, Velocity.X, Velocity.Y);
         }
         Vector2 vector = Position;
         int value = (int)(vector.X / 16f);
         int value2 = (int)((vector.X + (float)Width) / 16f);
         int value3 = (int)((Position.Y + (float)Height + 4f) / 16f);
         value = Utils.Clamp(value, 0, Main.maxTilesX - 1);
         value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
         value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 3);
         float num = (value3 + 3) * 16;
         int num2 = -1;
         int num3 = -1;
         int num4 = 1;
         if (Velocity.X < 0f)
         {
             num4 = 2;
         }
         for (int i = value; i <= value2; i++)
         {
             for (int j = value3; j <= value3 + 1; j++)
             {
                 if (Main.tile[i, j] == null)
                 {
                     Main.tile[i, j] = new Tile();
                 }
                 if (!Main.tile[i, j].nactive() || (!Main.tileSolid[Main.tile[i, j].type] && !Main.tileSolidTop[Main.tile[i, j].type]))
                 {
                     continue;
                 }
                 int num5 = j * 16;
                 if (Main.tile[i, j].halfBrick())
                 {
                     num5 += 8;
                 }
                 if (!new Rectangle(i * 16, j * 16 - 17, 16, 16).Intersects(new Rectangle((int)Position.X, (int)Position.Y, Width, Height)) || !((float)num5 <= num))
                 {
                     continue;
                 }
                 if (num == (float)num5)
                 {
                     if (Main.tile[i, j].slope() == 0)
                     {
                         continue;
                     }
                     if (num2 != -1 && num3 != -1 && Main.tile[num2, num3] != null && Main.tile[num2, num3].slope() != 0)
                     {
                         if (Main.tile[i, j].slope() == num4)
{
                             num = num5;
                             num2 = i;
                             num3 = j;
                         }
                     }
                     else
                     {
                         num = num5;
                         num2 = i;
                         num3 = j;
                     }
                 }
                 else
                 {
                     num = num5;
                     num2 = i;
                     num3 = j;
                 }
             }
         }
         int num6 = num2;
         int num7 = num3;
         if (num2 != -1 && num3 != -1 && Main.tile[num6, num7] != null && Main.tile[num6, num7].slope() > 0)
         {
             int num8 = Main.tile[num6, num7].slope();
             Vector2 vector2 = default(Vector2);
             vector2.X = num6 * 16;
             vector2.Y = num7 * 16;
             switch (num8)
             {
             case 2:
             {
                 float num9 = vector2.X + 16f - (Position.X + (float)Width);
                 if (Position.Y + (float)Height >= vector2.Y + num9 && Velocity.X < 0f)
                 {
                     Velocity.Y += Math.Abs(Velocity.X);
                 }
                 break;
             }
             case 1:
             {
                 float num9 = Position.X - vector2.X;
                 if (Position.Y + (float)Height >= vector2.Y + num9 && Velocity.X > 0f)
                 {
                     Velocity.Y += Math.Abs(Velocity.X);
                 }
                 break;
             }
             }
         }
         return new Vector4(Position, Velocity.X, Velocity.Y);
     }
References Tile.halfBrick(), Main.maxTilesX, Main.maxTilesY, Tile.nactive(), Tile.slope(), Tile, Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by NPC.Collision_WalkDownSlopes(), and Player.SlopeDownMovement().