Terraria: Collision.StickyTiles
StickyTiles()
static Vector2 Collision.StickyTiles (Vector2 Position, Vector2 Velocity, int Width, int Height) inline static
     {
         Vector2 vector = Position;
         int num = (int)(Position.X / 16f) - 1;
         int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
         int num3 = (int)(Position.Y / 16f) - 1;
         int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
         if (num < 0)
         {
             num = 0;
         }
         if (num2 > Main.maxTilesX)
         {
             num2 = Main.maxTilesX;
         }
         if (num3 < 0)
         {
             num3 = 0;
         }
         if (num4 > Main.maxTilesY)
         {
             num4 = Main.maxTilesY;
         }
         Vector2 vector2 = default(Vector2);
         for (int i = num; i < num2; i++)
         {
             for (int j = num3; j < num4; j++)
             {
                 if (Main.tile[i, j] == null || !Main.tile[i, j].active() || Main.tile[i, j].inActive())
                 {
                     continue;
                 }
                 if (Main.tile[i, j].type == 51)
                 {
                     int num5 = 0;
                     vector2.X = i * 16;
                     vector2.Y = j * 16;
                     if (vector.X + (float)Width > vector2.X - (float)num5 && vector.X < vector2.X + 16f + (float)num5 && vector.Y + (float)Height > vector2.Y && (double)vector.Y < (double)vector2.Y + 16.01)
                     {
                         if (Main.tile[i, j].type == 51 && (double)(Math.Abs(Velocity.X) + Math.Abs(Velocity.Y)) > 0.7 && Main.rand.Next(30) == 0)
{
                             Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 30);
                         }
                         return new Vector2(i, j);
                     }
                 }
                 else
                 {
                     if (Main.tile[i, j].type != 229 || Main.tile[i, j].slope() != 0)
                     {
                         continue;
                     }
                     int num6 = 1;
                     vector2.X = i * 16;
                     vector2.Y = j * 16;
                     float num7 = 16.01f;
                     if (Main.tile[i, j].halfBrick())
                     {
                         vector2.Y += 8f;
                         num7 -= 8f;
                     }
                     if (vector.X + (float)Width > vector2.X - (float)num6 && vector.X < vector2.X + 16f + (float)num6 && vector.Y + (float)Height > vector2.Y && vector.Y < vector2.Y + num7)
                     {
                         if (Main.tile[i, j].type == 51 && (double)(Math.Abs(Velocity.X) + Math.Abs(Velocity.Y)) > 0.7 && Main.rand.Next(30) == 0)
{
                             Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 30);
                         }
                         return new Vector2(i, j);
                     }
                 }
             }
         }
         return new Vector2(-1f, -1f);
     }
References Tile.active(), Tile.halfBrick(), Tile.inActive(), Main.maxTilesX, Main.maxTilesY, Dust.NewDust(), UnifiedRandom.Next(), Main.rand, Tile.slope(), Main.tile, and Tile.type.
Referenced by Player.StickyMovement().