Terraria: Collision.FindCollisionTile
FindCollisionTile()
static List<Point> Collision.FindCollisionTile (int Direction, Vector2 position, float testMagnitude, int Width, int Height, bool fallThrough = false, bool fall2 = false, int gravDir = 1, bool checkCardinals = true, bool checkSlopes = false) inline static
     {
         List<Point> list = new List<Point>();
         if ((uint)Direction > 1u)
         {
             if ((uint)(Direction - 2) <= 1u)
             {
                 Vector2 vector = ((Direction == 2) ? (Vector2.UnitY * testMagnitude) : (-Vector2.UnitY * testMagnitude));
                 Vector4 vec = new Vector4(position, vector.X, vector.Y);
                 int y = (int)(position.Y + (float)((Direction == 2) ? Height : 0)) / 16;
                 float num = Math.Min(16f - position.X % 16f, Width);
                 float num2 = num;
                 if (checkCardinals && TileCollision(position - vector, vector, (int)num, Height, fallThrough, fall2, gravDir) != vector)
                 {
                     list.Add(new Point((int)position.X / 16, y));
                 }
                 else if (checkSlopes && SlopeCollision(position, vector, (int)num, Height, gravDir, fallThrough).YZW() != vec.YZW())
                 {
                     list.Add(new Point((int)position.X / 16, y));
                 }
                 for (; num2 + 16f <= (float)(Width - 16); num2 += 16f)
                 {
                     if (checkCardinals && TileCollision(position - vector + Vector2.UnitX * num2, vector, 16, Height, fallThrough, fall2, gravDir) != vector)
                     {
                         list.Add(new Point((int)(position.X + num2) / 16, y));
                     }
                     else if (checkSlopes && SlopeCollision(position + Vector2.UnitX * num2, vector, 16, Height, gravDir, fallThrough).YZW() != vec.YZW())
                     {
                         list.Add(new Point((int)(position.X + num2) / 16, y));
                     }
                 }
                 int width = Width - (int)num2;
                 if (checkCardinals && TileCollision(position - vector + Vector2.UnitX * num2, vector, width, Height, fallThrough, fall2, gravDir) != vector)
                 {
                     list.Add(new Point((int)(position.X + num2) / 16, y));
                 }
                 else if (checkSlopes && SlopeCollision(position + Vector2.UnitX * num2, vector, width, Height, gravDir, fallThrough).YZW() != vec.YZW())
                 {
                     list.Add(new Point((int)(position.X + num2) / 16, y));
                 }
             }
         }
         else
         {
             Vector2 vector = ((Direction == 0) ? (Vector2.UnitX * testMagnitude) : (-Vector2.UnitX * testMagnitude));
             Vector4 vec = new Vector4(position, vector.X, vector.Y);
             int y = (int)(position.X + (float)((Direction == 0) ? Width : 0)) / 16;
             float num3 = Math.Min(16f - position.Y % 16f, Height);
             float num4 = num3;
             if (checkCardinals && TileCollision(position - vector, vector, Width, (int)num3, fallThrough, fall2, gravDir) != vector)
             {
                 list.Add(new Point(y, (int)position.Y / 16));
             }
             else if (checkSlopes && SlopeCollision(position, vector, Width, (int)num3, gravDir, fallThrough).XZW() != vec.XZW())
             {
                 list.Add(new Point(y, (int)position.Y / 16));
             }
             for (; num4 + 16f <= (float)(Height - 16); num4 += 16f)
             {
                 if (checkCardinals && TileCollision(position - vector + Vector2.UnitY * num4, vector, Width, 16, fallThrough, fall2, gravDir) != vector)
                 {
                     list.Add(new Point(y, (int)(position.Y + num4) / 16));
                 }
                 else if (checkSlopes && SlopeCollision(position + Vector2.UnitY * num4, vector, Width, 16, gravDir, fallThrough).XZW() != vec.XZW())
                 {
                     list.Add(new Point(y, (int)(position.Y + num4) / 16));
                 }
             }
             int height = Height - (int)num4;
             if (checkCardinals && TileCollision(position - vector + Vector2.UnitY * num4, vector, Width, height, fallThrough, fall2, gravDir) != vector)
             {
                 list.Add(new Point(y, (int)(position.Y + num4) / 16));
             }
             else if (checkSlopes && SlopeCollision(position + Vector2.UnitY * num4, vector, Width, height, gravDir, fallThrough).XZW() != vec.XZW())
             {
                 list.Add(new Point(y, (int)(position.Y + num4) / 16));
             }
         }
         return list;
     }
References SlopeCollision(), and TileCollision().
Referenced by Player.UpdateTouchingTiles().