Terraria: Collision.IsClearSpotTest
IsClearSpotTest()
static bool Collision.IsClearSpotTest (Vector2 position, float testMagnitude, int Width, int Height, bool fallThrough = false, bool fall2 = false, int gravDir = 1, bool checkCardinals = true, bool checkSlopes = false) inline static
     {
         if (checkCardinals)
         {
             Vector2 vector = Vector2.UnitX * testMagnitude;
             if (TileCollision(position - vector, vector, Width, Height, fallThrough, fall2, gravDir) != vector)
             {
                 return false;
             }
             vector = -Vector2.UnitX * testMagnitude;
             if (TileCollision(position - vector, vector, Width, Height, fallThrough, fall2, gravDir) != vector)
             {
                 return false;
             }
             vector = Vector2.UnitY * testMagnitude;
             if (TileCollision(position - vector, vector, Width, Height, fallThrough, fall2, gravDir) != vector)
             {
                 return false;
             }
             vector = -Vector2.UnitY * testMagnitude;
             if (TileCollision(position - vector, vector, Width, Height, fallThrough, fall2, gravDir) != vector)
             {
                 return false;
             }
         }
         if (checkSlopes)
         {
             Vector2 vector = Vector2.UnitX * testMagnitude;
             Vector4 vector2 = new Vector4(position, testMagnitude, 0f);
             if (SlopeCollision(position, vector, Width, Height, gravDir, fallThrough) != vector2)
             {
                 return false;
             }
             vector = -Vector2.UnitX * testMagnitude;
             vector2 = new Vector4(position, 0f - testMagnitude, 0f);
             if (SlopeCollision(position, vector, Width, Height, gravDir, fallThrough) != vector2)
             {
                 return false;
             }
             vector = Vector2.UnitY * testMagnitude;
             vector2 = new Vector4(position, 0f, testMagnitude);
             if (SlopeCollision(position, vector, Width, Height, gravDir, fallThrough) != vector2)
             {
                 return false;
             }
             vector = -Vector2.UnitY * testMagnitude;
             vector2 = new Vector4(position, 0f, 0f - testMagnitude);
             if (SlopeCollision(position, vector, Width, Height, gravDir, fallThrough) != vector2)
             {
                 return false;
             }
         }
         return true;
     }
References SlopeCollision(), and TileCollision().
Referenced by Player.CanFitSpace(), and Player.UpdateTouchingTiles().