Terraria: Collision.SlopeCollision
SlopeCollision()
static Vector4 Collision.SlopeCollision (Vector2 Position, Vector2 Velocity, int Width, int Height, float gravity = 0f, bool fall = false) inline static
     {
         stair = false;
         stairFall = false;
         bool[] array = new bool[5];
         float y = Position.Y;
         float y2 = Position.Y;
         sloping = false;
         Vector2 vector = Position;
         Vector2 vector2 = Position;
         Vector2 vector3 = Velocity;
         int value = (int)(Position.X / 16f) - 1;
         int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
         int value3 = (int)(Position.Y / 16f) - 1;
         int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
         int num = Utils.Clamp(value, 0, Main.maxTilesX - 1);
         value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
         value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
         value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
         Vector2 vector4 = default(Vector2);
         for (int i = num; i < value2; i++)
         {
             for (int j = value3; j < value4; j++)
             {
                 if (Main.tile[i, j] == null || !Main.tile[i, j].active() || Main.tile[i, j].inActive() || (!Main.tileSolid[Main.tile[i, j].type] && (!Main.tileSolidTop[Main.tile[i, j].type] || Main.tile[i, j].frameY != 0)))
                 {
                     continue;
                 }
                 vector4.X = i * 16;
                 vector4.Y = j * 16;
                 int num2 = 16;
                 if (Main.tile[i, j].halfBrick())
                 {
                     vector4.Y += 8f;
                     num2 -= 8;
                 }
                 if (!(Position.X + (float)Width > vector4.X) || !(Position.X < vector4.X + 16f) || !(Position.Y + (float)Height > vector4.Y) || !(Position.Y < vector4.Y + (float)num2))
                 {
                     continue;
                 }
                 bool flag = true;
                 if (TileID.Sets.Platforms[Main.tile[i, j].type])
                 {
                     if (Velocity.Y < 0f)
                     {
                         flag = false;
                     }
                     if (Position.Y + (float)Height < (float)(j * 16) || Position.Y + (float)Height - (1f + Math.Abs(Velocity.X)) > (float)(j * 16 + 16))
                     {
                         flag = false;
                     }
                     if (((Main.tile[i, j].slope() == 1 && Velocity.X >= 0f) || (Main.tile[i, j].slope() == 2 && Velocity.X <= 0f)) && (Position.Y + (float)Height) / 16f - 1f == (float)j)
                     {
                         flag = false;
                     }
                 }
                 if (!flag)
                 {
                     continue;
                 }
                 bool flag2 = false;
                 if (fall && TileID.Sets.Platforms[Main.tile[i, j].type])
                 {
                     flag2 = true;
                 }
                 int num3 = Main.tile[i, j].slope();
                 vector4.X = i * 16;
                 vector4.Y = j * 16;
                 if (!(Position.X + (float)Width > vector4.X) || !(Position.X < vector4.X + 16f) || !(Position.Y + (float)Height > vector4.Y) || !(Position.Y < vector4.Y + 16f))
                 {
                     continue;
                 }
                 float num4 = 0f;
                 if (num3 == 3 || num3 == 4)
                 {
                     if (num3 == 3)
                     {
                         num4 = Position.X - vector4.X;
                     }
                     if (num3 == 4)
                     {
                         num4 = vector4.X + 16f - (Position.X + (float)Width);
                     }
                     if (num4 >= 0f)
                     {
                         if (Position.Y <= vector4.Y + 16f - num4)
{
                             float num5 = vector4.Y + 16f - vector.Y - num4;
                             if (Position.Y + num5 > y2)
{
                                 vector2.Y = Position.Y + num5;
                                 y2 = vector2.Y;
                                 if (vector3.Y < 0.0101f)
{
                                     vector3.Y = 0.0101f;
                                 }
                                 array[num3] = true;
                             }
                         }
                     }
                     else if (Position.Y > vector4.Y)
                     {
                         float num6 = vector4.Y + 16f;
                         if (vector2.Y < num6)
{
                             vector2.Y = num6;
                             if (vector3.Y < 0.0101f)
{
                                 vector3.Y = 0.0101f;
                             }
                         }
                     }
                 }
                 if (num3 != 1 && num3 != 2)
                 {
                     continue;
                 }
                 if (num3 == 1)
                 {
                     num4 = Position.X - vector4.X;
                 }
                 if (num3 == 2)
                 {
                     num4 = vector4.X + 16f - (Position.X + (float)Width);
                 }
                 if (num4 >= 0f)
                 {
                     if (!(Position.Y + (float)Height >= vector4.Y + num4))
                     {
                         continue;
                     }
                     float num7 = vector4.Y - (vector.Y + (float)Height) + num4;
                     if (!(Position.Y + num7 < y))
                     {
                         continue;
                     }
                     if (flag2)
                     {
                         stairFall = true;
                         continue;
                     }
                     if (TileID.Sets.Platforms[Main.tile[i, j].type])
                     {
                         stair = true;
                     }
                     else
                     {
                         stair = false;
                     }
                     vector2.Y = Position.Y + num7;
                     y = vector2.Y;
                     if (vector3.Y > 0f)
                     {
                         vector3.Y = 0f;
                     }
                     array[num3] = true;
                     continue;
                 }
                 if (TileID.Sets.Platforms[Main.tile[i, j].type] && !(Position.Y + (float)Height - 4f - Math.Abs(Velocity.X) <= vector4.Y))
                 {
                     if (flag2)
                     {
                         stairFall = true;
                     }
                     continue;
                 }
                 float num8 = vector4.Y - (float)Height;
                 if (!(vector2.Y > num8))
                 {
                     continue;
                 }
                 if (flag2)
                 {
                     stairFall = true;
                     continue;
                 }
                 if (TileID.Sets.Platforms[Main.tile[i, j].type])
                 {
                     stair = true;
                 }
                 else
                 {
                     stair = false;
                 }
                 vector2.Y = num8;
                 if (vector3.Y > 0f)
                 {
                     vector3.Y = 0f;
                 }
             }
         }
         Vector2 position = Position;
         Vector2 velocity = vector2 - Position;
         Vector2 vector5 = TileCollision(position, velocity, Width, Height);
         if (vector5.Y > velocity.Y)
         {
             float num9 = velocity.Y - vector5.Y;
             vector2.Y = Position.Y + vector5.Y;
             if (array[1])
             {
                 vector2.X = Position.X - num9;
             }
             if (array[2])
             {
                 vector2.X = Position.X + num9;
             }
             vector3.X = 0f;
             vector3.Y = 0f;
             up = false;
         }
         else if (vector5.Y < velocity.Y)
         {
             float num10 = vector5.Y - velocity.Y;
             vector2.Y = Position.Y + vector5.Y;
             if (array[3])
             {
                 vector2.X = Position.X - num10;
             }
             if (array[4])
             {
                 vector2.X = Position.X + num10;
             }
             vector3.X = 0f;
             vector3.Y = 0f;
         }
         return new Vector4(vector2, vector3.X, vector3.Y);
     }
References Tile.active(), Tile.frameY, Tile.halfBrick(), Tile.inActive(), Main.maxTilesX, Main.maxTilesY, TileID.Sets.Platforms, Tile.slope(), sloping, stair, stairFall, Main.tile, TileCollision(), Main.tileSolid, Main.tileSolidTop, Tile.type, and up.
Referenced by Player.CheckForGoodTeleportationSpot(), NPC.Collision_MoveSlopesAndStairFall(), NPC.Collision_MoveSnailOnSlopes(), FindCollisionTile(), Gore.Gore_UpdateLeaf(), Projectile.HandleMovement(), IsClearSpotTest(), Item.MoveInWorld(), Player.SlopingCollision(), Gore.Update(), and Projectile.UpdatePosition().