Terraria: Collision.LavaCollision
LavaCollision()
static bool Collision.LavaCollision (Vector2 Position, int Width, int Height) inline static
     {
         int value = (int)(Position.X / 16f) - 1;
         int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
         int value3 = (int)(Position.Y / 16f) - 1;
         int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
         int num = Utils.Clamp(value, 0, Main.maxTilesX - 1);
         value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
         value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
         value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
         Vector2 vector = default(Vector2);
         for (int i = num; i < value2; i++)
         {
             for (int j = value3; j < value4; j++)
             {
                 if (Main.tile[i, j] != null && Main.tile[i, j].liquid > 0 && Main.tile[i, j].lava())
                 {
                     vector.X = i * 16;
                     vector.Y = j * 16;
                     int num2 = 16;
                     float num3 = 256 - Main.tile[i, j].liquid;
                     num3 /= 32f;
                     vector.Y += num3 * 2f;
                     num2 -= (int)(num3 * 2f);
                     if (Position.X + (float)Width > vector.X && Position.X < vector.X + 16f && Position.Y + (float)Height > vector.Y && Position.Y < vector.Y + (float)num2)
                     {
                         return true;
                     }
                 }
             }
         }
         return false;
     }
References Tile.lava(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, and Main.tile.
Referenced by Projectile.AI_152_SuperStarSlash(), Player.CheckForGoodTeleportationSpot(), NPC.Collision_LavaCollision(), NPC.DoDeathEvents(), WaterShaderData.DrawWaves(), TeleportHelpers.IsInSolidTilesExtended(), Item.MoveInWorld(), Player.Update(), and Projectile.Update().