Terraria: Collision.CanHitLine
CanHitLine()
static bool Collision.CanHitLine (Vector2 Position1, int Width1, int Height1, Vector2 Position2, int Width2, int Height2) inline static
     {
         int num = (int)((Position1.X + (float)(Width1 / 2)) / 16f);
         int num2 = (int)((Position1.Y + (float)(Height1 / 2)) / 16f);
         int num3 = (int)((Position2.X + (float)(Width2 / 2)) / 16f);
         int num4 = (int)((Position2.Y + (float)(Height2 / 2)) / 16f);
         if (num <= 1)
         {
             num = 1;
         }
         if (num >= Main.maxTilesX)
         {
             num = Main.maxTilesX - 1;
         }
         if (num3 <= 1)
         {
             num3 = 1;
         }
         if (num3 >= Main.maxTilesX)
         {
             num3 = Main.maxTilesX - 1;
         }
         if (num2 <= 1)
         {
             num2 = 1;
         }
         if (num2 >= Main.maxTilesY)
         {
             num2 = Main.maxTilesY - 1;
         }
         if (num4 <= 1)
         {
             num4 = 1;
         }
         if (num4 >= Main.maxTilesY)
         {
             num4 = Main.maxTilesY - 1;
         }
         float num5 = Math.Abs(num - num3);
         float num6 = Math.Abs(num2 - num4);
         if (num5 == 0f && num6 == 0f)
         {
             return true;
         }
         float num7 = 1f;
         float num8 = 1f;
         if (num5 == 0f || num6 == 0f)
         {
             if (num5 == 0f)
             {
                 num7 = 0f;
             }
             if (num6 == 0f)
             {
                 num8 = 0f;
             }
         }
         else if (num5 > num6)
         {
             num7 = num5 / num6;
         }
         else
         {
             num8 = num6 / num5;
         }
         float num9 = 0f;
         float num10 = 0f;
         int num11 = 1;
         if (num2 < num4)
         {
             num11 = 2;
         }
         int num12 = (int)num5;
         int num13 = (int)num6;
         int num14 = Math.Sign(num3 - num);
         int num15 = Math.Sign(num4 - num2);
         bool flag = false;
         bool flag2 = false;
         try
         {
             do
             {
                 switch (num11)
                 {
                 case 2:
                 {
                     num9 += num7;
                     int num17 = (int)num9;
                     num9 %= 1f;
                     for (int j = 0; j < num17; j++)
                     {
                         if (Main.tile[num, num2 - 1] == null)
{
                             return false;
                         }
                         if (Main.tile[num, num2] == null)
{
                             return false;
                         }
                         if (Main.tile[num, num2 + 1] == null)
{
                             return false;
                         }
                         Tile tile4 = Main.tile[num, num2 - 1];
                         Tile tile5 = Main.tile[num, num2 + 1];
                         Tile tile6 = Main.tile[num, num2];
                         if ((!tile4.inActive() && tile4.active() && Main.tileSolid[tile4.type] && !Main.tileSolidTop[tile4.type]) || (!tile5.inActive() && tile5.active() && Main.tileSolid[tile5.type] && !Main.tileSolidTop[tile5.type]) || (!tile6.inActive() && tile6.active() && Main.tileSolid[tile6.type] && !Main.tileSolidTop[tile6.type]))
{
                             return false;
                         }
                         if (num12 == 0 && num13 == 0)
{
                             flag = true;
                             break;
                         }
                         num += num14;
                         num12--;
                         if (num12 == 0 && num13 == 0 && num17 == 1)
{
                             flag2 = true;
                         }
                     }
                     if (num13 != 0)
                     {
                         num11 = 1;
                     }
                     break;
                 }
                 case 1:
                 {
                     num10 += num8;
                     int num16 = (int)num10;
                     num10 %= 1f;
                     for (int i = 0; i < num16; i++)
                     {
                         if (Main.tile[num - 1, num2] == null)
{
                             return false;
                         }
                         if (Main.tile[num, num2] == null)
{
                             return false;
                         }
                         if (Main.tile[num + 1, num2] == null)
{
                             return false;
                         }
                         Tile tile = Main.tile[num - 1, num2];
                         Tile tile2 = Main.tile[num + 1, num2];
                         Tile tile3 = Main.tile[num, num2];
                         if ((!tile.inActive() && tile.active() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type]) || (!tile2.inActive() && tile2.active() && Main.tileSolid[tile2.type] && !Main.tileSolidTop[tile2.type]) || (!tile3.inActive() && tile3.active() && Main.tileSolid[tile3.type] && !Main.tileSolidTop[tile3.type]))
{
                             return false;
                         }
                         if (num12 == 0 && num13 == 0)
{
                             flag = true;
                             break;
                         }
                         num2 += num15;
                         num13--;
                         if (num12 == 0 && num13 == 0 && num16 == 1)
{
                             flag2 = true;
                         }
                     }
                     if (num12 != 0)
                     {
                         num11 = 2;
                     }
                     break;
                 }
                 }
                 if (Main.tile[num, num2] == null)
                 {
                     return false;
                 }
                 Tile tile7 = Main.tile[num, num2];
                 if (!tile7.inActive() && tile7.active() && Main.tileSolid[tile7.type] && !Main.tileSolidTop[tile7.type])
                 {
                     return false;
                 }
             }
             while (!(flag || flag2));
             return true;
         }
         catch
         {
             return false;
         }
     }
References Tile.active(), Tile.inActive(), Main.maxTilesX, Main.maxTilesY, Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by NPC.AI(), Projectile.AI_001(), NPC.AI_003_Fighters(), NPC.AI_006_Worms(), NPC.AI_007_TownEntities(), Projectile.AI_026(), Projectile.AI_062(), Projectile.AI_100_Medusa(), NPC.AI_107_ImprovedWalkers(), NPC.AI_109_DarkMage(), NPC.AI_121_QueenSlime(), Projectile.AI_130_FlameBurstTower_FindTarget(), Projectile.AI_134_Ballista_FindTarget(), Projectile.AI_137_CanHit(), NPC.BloodNautilus_CallForHelp(), Player.CanHit(), Projectile.CanHitWithMeleeWeapon(), Projectile.CanHitWithOwnBody(), Mount.CastSuperCartLaser(), EmoteBubble.CheckForNPCsToReactToEmoteBubble(), Projectile.Colliding(), Projectile.Damage(), Projectile.FindTargetWithinRange(), Player.GetFarthestSpawnPositionOnLine(), WorldGen.GrowMoreVines(), Projectile.HandleMovement(), NPC.HitEffect(), Player.ItemCheck_Shoot(), Projectile.Kill(), Player.QuickMinecart(), Player.QuickMinecartSnap(), Player.SpawnHallucination(), LockOnHelper.Update(), and Mount.UpdateEffects().