Terraria: Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSliderButtonBase
CreateHSLSliderButtonBase()
UIColoredSlider Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSliderButtonBase (HSLSliderId id) inline private
Definition at line 633 of file UICharacterCreation.cs.
    {
        return id switch
        {
            HSLSliderId.Saturation => new UIColoredSlider(LocalizedText.Empty, () => GetHSLSliderPosition(HSLSliderId.Saturation), delegate(float x)
            {
                UpdateHSLValue(HSLSliderId.Saturation, x);
            }, UpdateHSL_S, (float x) => GetHSLSliderColorAt(HSLSliderId.Saturation, x), Color.Transparent),
            HSLSliderId.Luminance => new UIColoredSlider(LocalizedText.Empty, () => GetHSLSliderPosition(HSLSliderId.Luminance), delegate(float x)
            {
                UpdateHSLValue(HSLSliderId.Luminance, x);
            }, UpdateHSL_L, (float x) => GetHSLSliderColorAt(HSLSliderId.Luminance, x), Color.Transparent),
            _ => new UIColoredSlider(LocalizedText.Empty, () => GetHSLSliderPosition(HSLSliderId.Hue), delegate(float x)
            {
                UpdateHSLValue(HSLSliderId.Hue, x);
            }, UpdateHSL_H, (float x) => GetHSLSliderColorAt(HSLSliderId.Hue, x), Color.Transparent),
        };
    }
References Terraria.Localization.LocalizedText.Empty, Terraria.GameContent.UI.States.UICharacterCreation.GetHSLSliderColorAt(), Terraria.GameContent.UI.States.UICharacterCreation.GetHSLSliderPosition(), Microsoft.Xna.Framework.Color.Transparent, Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_H(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_L(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_S(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSLValue().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSlider().