Terraria: Terraria.GameContent.UI.States.UICharacterCreation.UpdateHelpGlyphs
UpdateHelpGlyphs()
void Terraria.GameContent.UI.States.UICharacterCreation.UpdateHelpGlyphs (UIElement element) inline private
Definition at line 392 of file UICharacterCreation.cs.
    {
        string text = "";
        string text2 = "";
        if (PlayerInput.UsingGamepad)
        {
            text = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: false, "HotbarMinus");
            text2 = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: false, "HotbarPlus");
        }
        _helpGlyphLeft.SetText(text);
        _helpGlyphRight.SetText(text2);
    }
References Terraria.GameContent.UI.States.UICharacterCreation._helpGlyphLeft, Terraria.GameContent.UI.States.UICharacterCreation._helpGlyphRight, Terraria.GameInput.PlayerInput.GenerateInputTag_ForCurrentGamemode(), Terraria.GameContent.UI.Elements.UIText.SetText(), and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar().