Terraria: Terraria.GameContent.UI.States.UICharacterCreation.UnselectAllCategories
UnselectAllCategories()
void Terraria.GameContent.UI.States.UICharacterCreation.UnselectAllCategories () inline private
Definition at line 1270 of file UICharacterCreation.cs.
    {
        UIColoredImageButton[] colorPickers = _colorPickers;
        for (int i = 0; i < colorPickers.Length; i++)
        {
            colorPickers[i]?.SetSelected(selected: false);
        }
        _clothingStylesCategoryButton.SetSelected(selected: false);
        _hairStylesCategoryButton.SetSelected(selected: false);
        _charInfoCategoryButton.SetSelected(selected: false);
        _hslContainer.Remove();
        _hairstylesContainer.Remove();
        _clothStylesContainer.Remove();
        _infoContainer.Remove();
    }
References Terraria.GameContent.UI.States.UICharacterCreation._charInfoCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._clothingStylesCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._clothStylesContainer, Terraria.GameContent.UI.States.UICharacterCreation._colorPickers, Terraria.GameContent.UI.States.UICharacterCreation._hairStylesCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._hairstylesContainer, Terraria.GameContent.UI.States.UICharacterCreation._hslContainer, Terraria.GameContent.UI.States.UICharacterCreation._infoContainer, Terraria.UI.UIElement.Remove(), and Terraria.GameContent.UI.Elements.UIColoredImageButton.SetSelected().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_CharInfo(), Terraria.GameContent.UI.States.UICharacterCreation.Click_ClothStyles(), Terraria.GameContent.UI.States.UICharacterCreation.Click_HairStyles(), and Terraria.GameContent.UI.States.UICharacterCreation.SelectColorPicker().