Terraria: Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSLValue
UpdateHSLValue()
void Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSLValue (HSLSliderId id, float value) inline private
    {
        switch (id)
        {
        case HSLSliderId.Hue:
            _currentColorHSL.X = value;
            break;
        case HSLSliderId.Saturation:
            _currentColorHSL.Y = value;
            break;
        case HSLSliderId.Luminance:
            _currentColorHSL.Z = value;
            break;
        }
        Color color = ScaledHslToRgb(_currentColorHSL.X, _currentColorHSL.Y, _currentColorHSL.Z);
        ApplyPendingColor(color);
        _colorPickers[(int)_selectedPicker]?.SetColor(color);
        if (_selectedPicker == CategoryId.HairColor)
        {
            _hairStylesCategoryButton.SetColor(color);
        }
        UpdateHexText(color);
    }
References Terraria.GameContent.UI.States.UICharacterCreation._colorPickers, Terraria.GameContent.UI.States.UICharacterCreation._currentColorHSL, Terraria.GameContent.UI.States.UICharacterCreation._hairStylesCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._selectedPicker, Terraria.GameContent.UI.States.UICharacterCreation.ApplyPendingColor(), Terraria.GameContent.UI.States.UICharacterCreation.ScaledHslToRgb(), Terraria.GameContent.UI.Elements.UIColoredImageButton.SetColor(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateHexText().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSliderButtonBase(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_H(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_L(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_S().