Terraria: Terraria.GameContent.UI.States.UICharacterCreation.Click_ClothStyles
Click_ClothStyles()
void Terraria.GameContent.UI.States.UICharacterCreation.Click_ClothStyles (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 816 of file UICharacterCreation.cs.
    {
        SoundEngine.PlaySound(12);
        UnselectAllCategories();
        _selectedPicker = CategoryId.Clothing;
        _middleContainer.Append(_clothStylesContainer);
        _clothingStylesCategoryButton.SetSelected(selected: true);
        UpdateSelectedGender();
    }
References Terraria.GameContent.UI.States.UICharacterCreation._clothingStylesCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._clothStylesContainer, Terraria.GameContent.UI.States.UICharacterCreation._middleContainer, Terraria.GameContent.UI.States.UICharacterCreation._selectedPicker, Terraria.UI.UIElement.Append(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.Elements.UIColoredImageButton.SetSelected(), Terraria.GameContent.UI.States.UICharacterCreation.UnselectAllCategories(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateSelectedGender().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar(), and Terraria.GameContent.UI.States.UICharacterCreation.SelectColorPicker().