Terraria: Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_L
UpdateHSL_L()
void Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_L () inline private
Definition at line 664 of file UICharacterCreation.cs.
    {
        float value = UILinksInitializer.HandleSliderHorizontalInput(_currentColorHSL.Z, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
        UpdateHSLValue(HSLSliderId.Luminance, value);
    }
References Terraria.GameContent.UI.States.UICharacterCreation._currentColorHSL, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.Initializers.UILinksInitializer.HandleSliderHorizontalInput(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSLValue(), and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSliderButtonBase().