Terraria: Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_S
UpdateHSL_S()
void Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSL_S () inline private
    {
        float value = UILinksInitializer.HandleSliderHorizontalInput(_currentColorHSL.Y, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
        UpdateHSLValue(HSLSliderId.Saturation, value);
    }
References Terraria.GameContent.UI.States.UICharacterCreation._currentColorHSL, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.Initializers.UILinksInitializer.HandleSliderHorizontalInput(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateHSLValue().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSliderButtonBase().