Terraria: Terraria.GameContent.UI.States.UICharacterCreation.MakeHairsylesMenu
MakeHairsylesMenu()
void Terraria.GameContent.UI.States.UICharacterCreation.MakeHairsylesMenu (UIElement middleInnerPanel) inline private
Definition at line 184 of file UICharacterCreation.cs.
    {
        Main.Hairstyles.UpdateUnlocks();
        UIElement uIElement = new UIElement
        {
            Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
            Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
            HAlign = 0.5f,
            VAlign = 0.5f,
            Top = StyleDimension.FromPixels(6f)
        };
        middleInnerPanel.Append(uIElement);
        uIElement.SetPadding(0f);
        UIList uIList = new UIList
        {
            Width = StyleDimension.FromPixelsAndPercent(-18f, 1f),
            Height = StyleDimension.FromPixelsAndPercent(-6f, 1f)
        };
        uIList.SetPadding(4f);
        uIElement.Append(uIList);
        UIScrollbar uIScrollbar = new UIScrollbar
        {
            HAlign = 1f,
            Height = StyleDimension.FromPixelsAndPercent(-30f, 1f),
            Top = StyleDimension.FromPixels(10f)
        };
        uIScrollbar.SetView(100f, 1000f);
        uIList.SetScrollbar(uIScrollbar);
        uIElement.Append(uIScrollbar);
        int count = Main.Hairstyles.AvailableHairstyles.Count;
        UIElement uIElement2 = new UIElement
        {
            Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
            Height = StyleDimension.FromPixelsAndPercent(48 * (count / 10 + ((count % 10 != 0) ? 1 : 0)), 0f)
        };
        uIList.Add(uIElement2);
        uIElement2.SetPadding(0f);
        for (int i = 0; i < count; i++)
        {
            UIHairStyleButton uIHairStyleButton = new UIHairStyleButton(_player, Main.Hairstyles.AvailableHairstyles[i])
            {
                Left = StyleDimension.FromPixels((float)(i % 10) * 46f + 6f),
                Top = StyleDimension.FromPixels((float)(i / 10) * 48f + 1f)
            };
            uIHairStyleButton.SetSnapPoint("Middle", i);
            uIHairStyleButton.SkipRenderingContent(i);
            uIElement2.Append(uIHairStyleButton);
        }
        _hairstylesContainer = uIElement;
    }
References Terraria.GameContent.UI.States.UICharacterCreation._hairstylesContainer, Terraria.GameContent.UI.States.UICharacterCreation._player, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.count, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Main.Hairstyles, Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.BuildPage().