Terraria: Terraria.GameContent.UI.States.UICharacterCreation.UpdateDifficultyDescription
UpdateDifficultyDescription()
void Terraria.GameContent.UI.States.UICharacterCreation.UpdateDifficultyDescription (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        LocalizedText text = Lang.menu[31];
        switch (_player.difficulty)
        {
        case 0:
            text = Lang.menu[31];
            break;
        case 1:
            text = Lang.menu[30];
            break;
        case 2:
            text = Lang.menu[29];
            break;
        case 3:
            text = Language.GetText("UI.CreativeDescriptionPlayer");
            break;
        }
        _difficultyDescriptionText.SetText(text);
    }
References Terraria.GameContent.UI.States.UICharacterCreation._difficultyDescriptionText, Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.Localization.Language.GetText(), Terraria.Lang.menu, and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.MakeInfoMenu().