Terraria: Terraria.GameContent.UI.States.UICharacterCreation.Click_Naming
Click_Naming()
void Terraria.GameContent.UI.States.UICharacterCreation.Click_Naming (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 1133 of file UICharacterCreation.cs.
    {
        SoundEngine.PlaySound(10);
        _player.name = "";
        Main.clrInput();
        UIVirtualKeyboard uIVirtualKeyboard = new UIVirtualKeyboard(Lang.menu[45].Value, "", OnFinishedNaming, OnCanceledNaming, 0, allowEmpty: true);
        uIVirtualKeyboard.SetMaxInputLength(20);
        Main.MenuUI.SetState(uIVirtualKeyboard);
    }
References Terraria.Main.clrInput(), Terraria.Lang.menu, Terraria.Main.MenuUI, Terraria.GameContent.UI.States.UICharacterCreation.OnCanceledNaming(), Terraria.GameContent.UI.States.UICharacterCreation.OnFinishedNaming(), and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.MakeInfoMenu().