Terraria: Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSlider
CreateHSLSlider()
UIColoredSlider Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSlider (HSLSliderId id) inline private
    {
        UIColoredSlider uIColoredSlider = CreateHSLSliderButtonBase(id);
        uIColoredSlider.VAlign = 0f;
        uIColoredSlider.HAlign = 0f;
        uIColoredSlider.Width = StyleDimension.FromPixelsAndPercent(-10f, 1f);
        uIColoredSlider.Top.Set(30 * (int)id, 0f);
        uIColoredSlider.OnLeftMouseDown += Click_ColorPicker;
        uIColoredSlider.SetSnapPoint("Middle", (int)id, null, new Vector2(0f, 20f));
        return uIColoredSlider;
    }
References Terraria.GameContent.UI.States.UICharacterCreation.Click_ColorPicker(), Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSliderButtonBase(), and Terraria.UI.StyleDimension.FromPixelsAndPercent().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.MakeHSLMenu().