Terraria: Terraria.GameContent.UI.States.UICharacterCreation.MakeCharPreview
MakeCharPreview()
void Terraria.GameContent.UI.States.UICharacterCreation.MakeCharPreview (UIPanel container) inline private
Definition at line 167 of file UICharacterCreation.cs.
    {
        float num = 70f;
        for (float num2 = 0f; num2 <= 1f; num2 += 1f)
        {
            UICharacter element = new UICharacter(_player, animated: true, hasBackPanel: false, 1.5f)
            {
                Width = StyleDimension.FromPixels(80f),
                Height = StyleDimension.FromPixelsAndPercent(80f, 0f),
                Top = StyleDimension.FromPixelsAndPercent(0f - num, 0f),
                VAlign = 0f,
                HAlign = 0.5f
            };
            container.Append(element);
        }
    }
References Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.BuildPage().