Terraria: Terraria.GameContent.UI.States.UICharacterCreation.Click_CharClothStyle
Click_CharClothStyle()
void Terraria.GameContent.UI.States.UICharacterCreation.Click_CharClothStyle (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        _clothingStylesCategoryButton.SetImageWithoutSettingSize(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/" + (_player.Male ? "ClothStyleMale" : "ClothStyleFemale"), (AssetRequestMode)1));
        UpdateSelectedGender();
    }
References Terraria.GameContent.UI.States.UICharacterCreation._clothingStylesCategoryButton, Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIColoredImageButton.SetImageWithoutSettingSize(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateSelectedGender().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_CharGenderFemale(), Terraria.GameContent.UI.States.UICharacterCreation.Click_CharGenderMale(), Terraria.GameContent.UI.States.UICharacterCreation.Click_PastePlayerTemplate(), Terraria.GameContent.UI.States.UICharacterCreation.Click_RandomizePlayer(), and Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu().