Terraria: Terraria.GameContent.UI.States.UICharacterCreation.OnFinishedNamingAndCreating
OnFinishedNamingAndCreating()
void Terraria.GameContent.UI.States.UICharacterCreation.OnFinishedNamingAndCreating (string name) inline private
    {
        _player.name = name.Trim();
        Main.MenuUI.SetState(this);
        _charName.SetContents(_player.name);
        FinishCreatingCharacter();
    }
References Terraria.GameContent.UI.States.UICharacterCreation._charName, Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.GameContent.UI.States.UICharacterCreation.FinishCreatingCharacter(), Terraria.Main.MenuUI, and Terraria.GameContent.UI.Elements.UICharacterNameButton.SetContents().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_NamingAndCreating().