Terraria: System.Xml.Xsl.Runtime.XmlAttributeCache.WriteValue
WriteValue() [9/11]
override void System.Xml.Xsl.Runtime.XmlAttributeCache.WriteValue (object value) inline virtual
Reimplemented from System.Xml.XmlRawWriter.
Definition at line 160 of file XmlAttributeCache.cs.
    {
        EnsureAttributeCache();
        _arrAttrs[_numEntries++].Init((XmlAtomicValue)value);
    }
References System.Xml.Xsl.Runtime.XmlAttributeCache._arrAttrs, System.Xml.Xsl.Runtime.XmlAttributeCache._numEntries, System.Xml.Xsl.Runtime.XmlAttributeCache.EnsureAttributeCache(), System.Xml.Xsl.Runtime.XmlAttributeCache.AttrNameVal.Init(), and System.value.
Referenced by System.Xml.Xsl.Runtime.XmlAttributeCache.WriteValue().