Terraria: System.Xml.Xsl.Runtime.XmlAttributeCache.FlushAttributes
FlushAttributes()
void System.Xml.Xsl.Runtime.XmlAttributeCache.FlushAttributes () inline private
Definition at line 207 of file XmlAttributeCache.cs.
    {
        int num = 0;
        while (num != _numEntries)
        {
            int num2 = _arrAttrs[num].NextNameIndex;
            if (num2 == 0)
            {
                num2 = _numEntries;
            }
            string localName = _arrAttrs[num].LocalName;
            if (localName != null)
            {
                string prefix = _arrAttrs[num].Prefix;
                string @namespace = _arrAttrs[num].Namespace;
                _wrapped.WriteStartAttribute(prefix, localName, @namespace);
                while (++num != num2)
                {
                    string text = _arrAttrs[num].Text;
                    if (text != null)
                    {
                        _wrapped.WriteString(text);
                    }
                    else
                    {
                        _wrapped.WriteValue(_arrAttrs[num].Value);
                    }
                }
                _wrapped.WriteEndAttribute();
            }
            else
            {
                num = num2;
            }
        }
        if (_onRemove != null)
        {
            _onRemove(_wrapped);
        }
    }
References System.Xml.Xsl.Runtime.XmlAttributeCache._arrAttrs, System.Xml.Xsl.Runtime.XmlAttributeCache._numEntries, System.Xml.Xsl.Runtime.XmlAttributeCache._onRemove, System.Xml.Xsl.Runtime.XmlAttributeCache._wrapped, System.Xml.Dictionary, System.Xml.Xsl.Runtime.XmlAttributeCache.AttrNameVal.LocalName, System.Xml.Xsl.Namespace, System.Xml.Xsl.Runtime.XmlAttributeCache.AttrNameVal.NextNameIndex, System.prefix, System.Xml.Xsl.Runtime.XmlAttributeCache.AttrNameVal.Prefix, System.text, System.Xml.Xsl.Runtime.XmlAttributeCache.AttrNameVal.Text, System.Xml.XmlWriter.WriteEndAttribute(), System.Xml.XmlWriter.WriteStartAttribute(), System.Xml.XmlWriter.WriteString(), and System.Xml.XmlRawWriter.WriteValue().
Referenced by System.Xml.Xsl.Runtime.XmlAttributeCache.StartElementContent(), and System.Xml.Xsl.Runtime.XmlAttributeCache.WriteNamespaceDeclaration().