Terraria: Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.DynamicVertexBuffer
DynamicVertexBuffer() [1/2]
unsafe Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.DynamicVertexBuffer (GraphicsDevice graphicsDevice, Type vertexType, int vertexCount, BufferUsage usage) inline
Definition at line 41 of file DynamicVertexBuffer.cs.
    {
        try
        {
            VertexDeclaration vertexDeclaration = VertexDeclaration.FromType(vertexType);
            if (vertexCount <= 0)
            {
                throw new ArgumentOutOfRangeException("vertexCount", FrameworkResources.ResourcesMustBeGreaterThanZeroSize);
            }
            _parent = graphicsDevice;
            CreateBuffer(vertexDeclaration, (uint)vertexCount, _003CModule_003E.ConvertXnaBufferUsageToDx(usage) | 0x200u, (_D3DPOOL)0);
            graphicsDevice.Resources.AddTrackedObject(this, pComPtr, 0u, _internalHandle, ref _internalHandle);
            return;
        }
        catch
        {
            //try-fault
            Dispose(true);
            throw;
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.Graphics.VertexBuffer.CreateBuffer(), Microsoft.Xna.Framework.Graphics.GraphicsResource.Dispose(), Microsoft.Xna.Framework.Graphics.VertexDeclaration.FromType(), Microsoft.Xna.Framework.Graphics.VertexBuffer.pComPtr, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources, and Microsoft.Xna.Framework.FrameworkResources.ResourcesMustBeGreaterThanZeroSize.