Terraria: Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.RecreateAndPopulateObject
RecreateAndPopulateObject() [1/2]
unsafe override int Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.RecreateAndPopulateObject () inline package virtual
Reimplemented from Microsoft.Xna.Framework.Graphics.VertexBuffer.
Definition at line 109 of file DynamicVertexBuffer.cs.
    {
        if (pComPtr != null)
        {
            return -2147467259;
        }
        if (_size == 0)
        {
            return -2147467259;
        }
        fixed (IDirect3DVertexBuffer9** ptr2 = &pComPtr)
        {
            GraphicsDevice parent = _parent;
            IDirect3DDevice9* ptr = parent.pComPtr;
            GraphicsDevice graphicsDevice = parent;
            int num = *(int*)ptr + 104;
            int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, uint, _D3DPOOL, IDirect3DVertexBuffer9**, void**, int>)(int)(*(uint*)num))((nint)ptr, _size, graphicsDevice.GetBufferUsage(_usage) | 0x200u, 0u, (_D3DPOOL)0, ptr2, null);
            if (num2 >= 0)
            {
                _parent.Resources.AddTrackedObject(this, pComPtr, 0u, _internalHandle, ref _internalHandle);
            }
            return num2;
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.VertexBuffer._size, Microsoft.Xna.Framework.Graphics.VertexBuffer._usage, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBufferUsage(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.VertexBuffer.pComPtr, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources.
Referenced by Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.RecreateAndPopulateObject().