Terraria: System.Text.Encoding.GetCharsWithFallback
GetCharsWithFallback() [2/3]
unsafe int System.Text.Encoding.GetCharsWithFallback (byte * pOriginalBytes, int originalByteCount, char * pOriginalChars, int originalCharCount, int bytesConsumedSoFar, int charsWrittenSoFar, DecoderNLS decoder) inline protected inherited
Definition at line 1443 of file Encoding.cs.
    {
        ReadOnlySpan<byte> readOnlySpan = new ReadOnlySpan<byte>(pOriginalBytes, originalByteCount).Slice(bytesConsumedSoFar);
        Span<char> span = new Span<char>(pOriginalChars, originalCharCount).Slice(charsWrittenSoFar);
        int bytesConsumed;
        int start;
        if (decoder.HasLeftoverData)
        {
            start = decoder.DrainLeftoverDataForGetChars(readOnlySpan, span, out bytesConsumed);
            readOnlySpan = readOnlySpan.Slice(bytesConsumed);
            span = span.Slice(start);
        }
        start = GetCharsFast((byte*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(readOnlySpan)), readOnlySpan.Length, (char*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(span)), span.Length, out bytesConsumed);
        readOnlySpan = readOnlySpan.Slice(bytesConsumed);
        span = span.Slice(start);
        decoder._bytesUsed = originalByteCount;
        if (readOnlySpan.IsEmpty)
        {
            return originalCharCount - span.Length;
        }
        return GetCharsWithFallback(readOnlySpan, originalByteCount, span, originalCharCount, decoder);
    }
References System.Runtime.Serialization.Dictionary, System.Text.DecoderNLS.DrainLeftoverDataForGetChars(), System.Text.Encoding.GetCharsFast(), System.Text.Encoding.GetCharsWithFallback(), System.Text.DecoderNLS.HasLeftoverData, and System.start.