Terraria: System.Text.Encoding.GetEncoder
GetEncoder()
virtual Encoder System.Text.Encoding.GetEncoder () inline virtual
Reimplemented in System.Text.ConsoleEncoding, System.Text.OSEncoding, System.Text.ConsoleEncoding, System.Text.OSEncoding, System.Text.ASCIIEncoding, System.Text.Latin1Encoding, System.Text.UnicodeEncoding, System.Text.UTF32Encoding, System.Text.UTF7Encoding, System.Text.UTF8Encoding, System.Xml.Ucs4Encoding, System.Text.EncodingNLS, System.Text.ISCIIEncoding, and System.Text.ISO2022Encoding.
Definition at line 1009 of file Encoding.cs.
    {
        return new DefaultEncoder(this);
    }
Referenced by System.Xml.EncodingStreamWrapper.EncodingStreamWrapper(), System.IO.StreamWriter.StreamWriter(), System.Xml.XmlEncodedRawTextWriter.XmlEncodedRawTextWriter(), System.Text.TranscodingStream.EnsurePreReadConditions(), System.Text.TranscodingStream.EnsurePreWriteConditions(), System.Text.EncodingExtensions.GetBytes(), System.Text.EncodingExtensions.GetBytes(), System.Text.EncodingExtensions.GetBytes(), System.Text.EncodingExtensions.GetBytes(), System.Text.ConsoleEncoding.GetEncoder(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.InitForWriting(), and System.IO.BinaryWriter.WriteCharsCommonWithoutLengthPrefix().