Terraria: Internal.Cryptography.OidLookup.ToOid
ToOid()
static string Internal.Cryptography.OidLookup.ToOid (string friendlyName, OidGroup oidGroup, bool fallBackToAllGroups) inline static
Definition at line 39 of file OidLookup.cs.
    {
        if (friendlyName == null)
        {
            throw new ArgumentNullException("friendlyName");
        }
        if (friendlyName.Length == 0)
        {
            return null;
        }
        bool flag = ShouldUseCache(oidGroup);
        if (flag && (s_friendlyNameToOid.TryGetValue(friendlyName, out var value) || s_lateBoundFriendlyNameToOid.TryGetValue(friendlyName, out value)))
        {
            return value;
        }
        value = NativeFriendlyNameToOid(friendlyName, oidGroup, fallBackToAllGroups);
        if (flag)
        {
            s_lateBoundFriendlyNameToOid.TryAdd(friendlyName, value);
        }
        return value;
    }
References Internal.Cryptography.OidLookup.NativeFriendlyNameToOid(), Internal.Cryptography.OidLookup.s_friendlyNameToOid, Internal.Cryptography.OidLookup.s_lateBoundFriendlyNameToOid, Internal.Cryptography.OidLookup.ShouldUseCache(), and System.value.
Referenced by System.Security.Cryptography.Oid.Oid(), and System.Security.Cryptography.Oid.FromFriendlyName().