Terraria: System.Text.Encoding.GetCharCount
GetCharCount() [2/5]
virtual unsafe int System.Text.Encoding.GetCharCount (byte * pBytes, int byteCount, DecoderNLS decoder) inline package virtual inherited
Reimplemented in System.Text.UnicodeEncoding, System.Text.UTF32Encoding, System.Text.UTF7Encoding, System.Text.DBCSCodePageEncoding, System.Text.GB18030Encoding, System.Text.ISCIIEncoding, System.Text.ISO2022Encoding, System.Text.EncodingNLS, and System.Text.SBCSCodePageEncoding.
Definition at line 1322 of file Encoding.cs.
    {
        int num = 0;
        int bytesConsumed = 0;
        if (!decoder.HasLeftoverData)
        {
            num = GetCharCountFast(pBytes, byteCount, decoder.Fallback, out bytesConsumed);
            if (bytesConsumed == byteCount)
            {
                return num;
            }
        }
        num += GetCharCountWithFallback(pBytes, byteCount, bytesConsumed, decoder);
        if (num < 0)
        {
            ThrowConversionOverflow();
        }
        return num;
    }
References System.byteCount, System.Text.DecoderNLS.Fallback, System.Text.Encoding.GetCharCountFast(), System.Text.Encoding.GetCharCountWithFallback(), System.Text.DecoderNLS.HasLeftoverData, and System.Text.Encoding.ThrowConversionOverflow().