Terraria: System.Text.Encoding.GetByteCountWithFallback
GetByteCountWithFallback() [2/3]
unsafe int System.Text.Encoding.GetByteCountWithFallback (char * pOriginalChars, int originalCharCount, int charsConsumedSoFar, EncoderNLS encoder) inline private inherited
Definition at line 1155 of file Encoding.cs.
    {
        ReadOnlySpan<char> readOnlySpan = new ReadOnlySpan<char>(pOriginalChars, originalCharCount).Slice(charsConsumedSoFar);
        int num = encoder.DrainLeftoverDataForGetByteCount(readOnlySpan, out var charsConsumed);
        readOnlySpan = readOnlySpan.Slice(charsConsumed);
        num += GetByteCountFast((char*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(readOnlySpan)), readOnlySpan.Length, encoder.Fallback, out charsConsumed);
        if (num < 0)
        {
            ThrowConversionOverflow();
        }
        readOnlySpan = readOnlySpan.Slice(charsConsumed);
        if (!readOnlySpan.IsEmpty)
        {
            num += GetByteCountWithFallback(readOnlySpan, originalCharCount, encoder);
            if (num < 0)
            {
                ThrowConversionOverflow();
            }
        }
        return num;
    }
References System.Text.EncoderNLS.DrainLeftoverDataForGetByteCount(), System.Text.EncoderNLS.Fallback, System.Text.Encoding.GetByteCountFast(), System.Text.Encoding.GetByteCountWithFallback(), and System.Text.Encoding.ThrowConversionOverflow().