Terraria: System.Text.Encoding.GetBytesWithFallback
GetBytesWithFallback() [3/3]
virtual unsafe int System.Text.Encoding.GetBytesWithFallback (ReadOnlySpan< char > chars, int originalCharsLength, Span< byte > bytes, int originalBytesLength, EncoderNLS encoder) inline protected virtual inherited
Reimplemented in System.Text.ASCIIEncoding.
Definition at line 1268 of file Encoding.cs.
    {
        fixed (char* ptr2 = &MemoryMarshal.GetReference(chars))
        {
            fixed (byte* ptr = &MemoryMarshal.GetReference(bytes))
            {
                EncoderFallbackBuffer encoderFallbackBuffer = EncoderFallbackBuffer.CreateAndInitialize(this, encoder, originalCharsLength);
                do
                {
                    Rune result;
                    int charsConsumed;
                    OperationStatus operationStatus = Rune.DecodeFromUtf16(chars, out result, out charsConsumed);
                    if (operationStatus != OperationStatus.NeedMoreData)
                    {
                        if (operationStatus != OperationStatus.InvalidData && EncodeRune(result, bytes, out var _) == OperationStatus.DestinationTooSmall)
{
                            break;
                        }
                    }
                    else if (encoder != null && !encoder.MustFlush)
                    {
                        encoder._charLeftOver = chars[0];
                        chars = ReadOnlySpan<char>.Empty;
                        break;
                    }
                    int bytesWritten2;
                    bool flag = encoderFallbackBuffer.TryInternalFallbackGetBytes(chars, bytes, out charsConsumed, out bytesWritten2);
                    chars = chars.Slice(charsConsumed);
                    bytes = bytes.Slice(bytesWritten2);
                    if (!flag)
                    {
                        break;
                    }
                    if (!chars.IsEmpty)
                    {
                        bytesWritten2 = GetBytesFast((char*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(chars)), chars.Length, (byte*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(bytes)), bytes.Length, out charsConsumed);
                        chars = chars.Slice(charsConsumed);
                        bytes = bytes.Slice(bytesWritten2);
                    }
                }
                while (!chars.IsEmpty);
                if (!chars.IsEmpty || encoderFallbackBuffer.Remaining > 0)
                {
                    ThrowBytesOverflow(encoder, bytes.Length == originalBytesLength);
                }
                if (encoder != null)
                {
                    encoder._charsUsed = originalCharsLength - chars.Length;
                }
                return originalBytesLength - bytes.Length;
            }
        }
    }
References System.bytes, System.chars, System.Text.EncoderFallbackBuffer.CreateAndInitialize(), System.Text.Rune.DecodeFromUtf16(), System.Runtime.Serialization.Dictionary, System.Text.Encoding.EncodeRune(), System.Text.Encoding.GetBytesFast(), System.Text.EncoderNLS.MustFlush, and System.Text.Encoding.ThrowBytesOverflow().