Terraria: System.Text.Encoding.GetCharsWithFallback
GetCharsWithFallback() [3/3]
virtual unsafe int System.Text.Encoding.GetCharsWithFallback (ReadOnlySpan< byte > bytes, int originalBytesLength, Span< char > chars, int originalCharsLength, DecoderNLS decoder) inline protected virtual inherited
Reimplemented in System.Text.ASCIIEncoding, and System.Text.UTF8Encoding.
Definition at line 1466 of file Encoding.cs.
    {
        fixed (byte* ptr2 = &MemoryMarshal.GetReference(bytes))
        {
            fixed (char* ptr = &MemoryMarshal.GetReference(chars))
            {
                DecoderFallbackBuffer decoderFallbackBuffer = DecoderFallbackBuffer.CreateAndInitialize(this, decoder, originalBytesLength);
                do
                {
                    Rune value;
                    int bytesConsumed;
                    OperationStatus operationStatus = DecodeFirstRune(bytes, out value, out bytesConsumed);
                    if (operationStatus != OperationStatus.NeedMoreData)
                    {
                        if (operationStatus != OperationStatus.InvalidData)
{
                            break;
                        }
                    }
                    else if (decoder != null && !decoder.MustFlush)
                    {
                        decoder.SetLeftoverData(bytes);
                        bytes = ReadOnlySpan<byte>.Empty;
                        break;
                    }
                    if (!decoderFallbackBuffer.TryInternalFallbackGetChars(bytes, bytesConsumed, chars, out var charsWritten))
                    {
                        break;
                    }
                    bytes = bytes.Slice(bytesConsumed);
                    chars = chars.Slice(charsWritten);
                    if (!bytes.IsEmpty)
                    {
                        charsWritten = GetCharsFast((byte*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(bytes)), bytes.Length, (char*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(chars)), chars.Length, out bytesConsumed);
                        bytes = bytes.Slice(bytesConsumed);
                        chars = chars.Slice(charsWritten);
                    }
                }
                while (!bytes.IsEmpty);
                if (!bytes.IsEmpty)
                {
                    ThrowCharsOverflow(decoder, chars.Length == originalCharsLength);
                }
                if (decoder != null)
                {
                    decoder._bytesUsed = originalBytesLength - bytes.Length;
                }
                return originalCharsLength - chars.Length;
            }
        }
    }
References System.bytes, System.chars, System.Text.DecoderFallbackBuffer.CreateAndInitialize(), System.Text.Encoding.DecodeFirstRune(), System.Runtime.Serialization.Dictionary, System.Text.Encoding.GetCharsFast(), System.Text.DecoderNLS.MustFlush, System.Text.DecoderNLS.SetLeftoverData(), System.Text.Encoding.ThrowCharsOverflow(), and System.value.