Terraria: System.Text.Encoding.GetBytes
GetBytes() [3/9]
virtual byte[] System.Text.Encoding.GetBytes (char[] chars) inline virtual inherited
Reimplemented in System.Text.ConsoleEncoding, and System.Text.ConsoleEncoding.
Definition at line 781 of file Encoding.cs.
    {
        if (chars == null)
        {
            throw new ArgumentNullException("chars", SR.ArgumentNull_Array);
        }
        return GetBytes(chars, 0, chars.Length);
    }
References System.SR.ArgumentNull_Array, System.chars, and System.Text.Encoding.GetBytes().
Referenced by System.Security.Cryptography.Pkcs.Pkcs12Kdf.CircularCopyUtf16BE(), System.Net.CommandStream.ContinueCommandPipeline(), System.Text.EncoderNLS.Convert(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.IO.Compression.ZipArchiveEntry.EncodeEntryName(), System.Net.Mime.ByteEncoder.EncodeString(), System.Net.Mime.QuotedPrintableStream.EncodeString(), System.Net.Http.HPack.HPackEncoder.EncodeStringLiteral(), System.Net.Http.HPack.HPackEncoder.EncodeStringLiterals(), System.Net.Http.QPack.QPackEncoder.EncodeValueString(), System.Net.Http.QPack.QPackEncoder.EncodeValueString(), System.Security.Cryptography.PasswordBasedEncryption.Encrypt(), System.Text.ConsoleEncoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.EncoderNLS.GetBytes(), System.Text.Encoding.DefaultEncoder.GetBytes(), System.Text.ConsoleEncoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.ConsoleEncoding.GetBytes(), System.Text.Encoding.DefaultEncoder.GetBytes(), System.Text.ConsoleEncoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.ConsoleEncoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.ConsoleEncoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.EncodingExtensions.GetBytes(), System.Text.EncodingExtensions.GetBytes(), System.Text.EncodingExtensions.GetBytes(), System.Text.EncodingExtensions.GetBytes(), System.String.GetBytesFromEncoding(), System.Net.Http.StringContent.GetContentByteArray(), System.Data.SqlTypes.SqlString.GetNonUnicodeBytes(), System.Security.Cryptography.PasswordBasedEncryption.Pbes2Decrypt(), System.Xml.XmlBaseReader.ReadBytes(), System.Net.Mail.AttachmentBase.SetContentFromString(), System.Net.Mail.AttachmentBase.SetContentFromString(), System.Net.WebClient.UploadString(), System.Net.WebClient.UploadStringAsync(), System.Web.HttpUtility.UrlDecodeToBytes(), System.Web.Util.HttpEncoder.UrlEncodeNonAscii(), System.Web.HttpUtility.UrlEncodeToBytes(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.Formats.Asn1.AsnWriter.WriteCharacterStringCore(), System.IO.BinaryWriter.WriteCharsCommonWithoutLengthPrefix(), System.Formats.Asn1.AsnWriter.WriteConstructedCerCharacterString(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteHtmlUri(), System.Net.Http.HttpConnection.WriteStringAsync(), System.Net.Http.HttpConnection.WriteStringWithEncodingAsyncSlow(), and System.Net.Http.MultipartContent.WriteToStream().