Terraria: System.Text.Encoding.GetPreamble
GetPreamble()
virtual byte[] System.Text.Encoding.GetPreamble () inline virtual inherited
Reimplemented in System.Text.ConsoleEncoding, System.Text.ConsoleEncoding, System.Text.UnicodeEncoding, System.Text.UTF32Encoding, System.Text.UTF8Encoding, System.Xml.Ucs4Encoding1234, System.Xml.Ucs4Encoding2143, System.Xml.Ucs4Encoding3412, and System.Xml.Ucs4Encoding4321.
Definition at line 689 of file Encoding.cs.
    {
        return Array.Empty<byte>();
    }
Referenced by System.IO.StreamWriter.FlushAsyncInternal(), System.Net.Http.HttpContent.GetPreambleLength(), and System.Net.WebClient.GetStringUsingEncoding().