Terraria: System.Text.Encoding.GetCharCountFast
GetCharCountFast()
virtual unsafe int System.Text.Encoding.GetCharCountFast (byte * pBytes, int bytesLength, DecoderFallback fallback, out int bytesConsumed) inline protected virtual inherited
Reimplemented in System.Text.ASCIIEncoding, System.Text.Latin1Encoding, and System.Text.UTF8Encoding.
Definition at line 1342 of file Encoding.cs.
    {
        throw NotImplemented.ByDesign;
    }
References System.NotImplemented.ByDesign.
Referenced by System.Text.Encoding.GetCharCount(), System.Text.Encoding.GetCharCountWithFallback(), and System.Text.Encoding.GetCharCountWithFallback().