Terraria: System.Text.Encoding.ThrowConversionOverflow
ThrowConversionOverflow()
static void System.Text.Encoding.ThrowConversionOverflow () inline static package inherited
Definition at line 1084 of file Encoding.cs.
    {
        throw new ArgumentException(SR.Argument_ConversionOverflow);
    }
References System.SR.Argument_ConversionOverflow.
Referenced by System.Text.EncoderFallbackBuffer.DrainRemainingDataForGetByteCount(), System.Text.DecoderFallbackBuffer.DrainRemainingDataForGetCharCount(), System.Text.Encoding.GetByteCount(), System.Text.ASCIIEncoding.GetByteCountCommon(), System.Text.Latin1Encoding.GetByteCountCommon(), System.Text.UTF8Encoding.GetByteCountCommon(), System.Text.UTF8Encoding.GetByteCountFast(), System.Text.Encoding.GetByteCountWithFallback(), System.Text.Encoding.GetByteCountWithFallback(), System.Text.Encoding.GetCharCount(), System.Text.ASCIIEncoding.GetCharCountCommon(), System.Text.UTF8Encoding.GetCharCountCommon(), System.Text.Encoding.GetCharCountWithFallback(), and System.Text.Encoding.GetCharCountWithFallback().