Terraria: System.Text.Encoding.GetByteCount
GetByteCount() [2/7]
virtual unsafe int System.Text.Encoding.GetByteCount (char * pChars, int charCount, EncoderNLS encoder) inline package virtual inherited
Reimplemented in System.Text.UTF7Encoding, System.Text.UnicodeEncoding, System.Text.UTF32Encoding, System.Text.ISCIIEncoding, System.Text.ISO2022Encoding, System.Text.DBCSCodePageEncoding, System.Text.EncodingNLS, System.Text.GB18030Encoding, and System.Text.SBCSCodePageEncoding.
Definition at line 1124 of file Encoding.cs.
    {
        int num = 0;
        int charsConsumed = 0;
        if (!encoder.HasLeftoverData)
        {
            num = GetByteCountFast(pChars, charCount, encoder.Fallback, out charsConsumed);
            if (charsConsumed == charCount)
            {
                return num;
            }
        }
        num += GetByteCountWithFallback(pChars, charCount, charsConsumed, encoder);
        if (num < 0)
        {
            ThrowConversionOverflow();
        }
        return num;
    }
References System.charCount, System.Text.EncoderNLS.Fallback, System.Text.Encoding.GetByteCountFast(), System.Text.Encoding.GetByteCountWithFallback(), System.Text.EncoderNLS.HasLeftoverData, and System.Text.Encoding.ThrowConversionOverflow().