Terraria: System.Text.Encoding.GetCharCountWithFallback
GetCharCountWithFallback() [2/3]
unsafe int System.Text.Encoding.GetCharCountWithFallback (byte * pOriginalBytes, int originalByteCount, int bytesConsumedSoFar, DecoderNLS decoder) inline private inherited
Definition at line 1353 of file Encoding.cs.
    {
        ReadOnlySpan<byte> readOnlySpan = new ReadOnlySpan<byte>(pOriginalBytes, originalByteCount).Slice(bytesConsumedSoFar);
        int num = 0;
        int bytesConsumed;
        if (decoder.HasLeftoverData)
        {
            num = decoder.DrainLeftoverDataForGetCharCount(readOnlySpan, out bytesConsumed);
            readOnlySpan = readOnlySpan.Slice(bytesConsumed);
        }
        num += GetCharCountFast((byte*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(readOnlySpan)), readOnlySpan.Length, decoder.Fallback, out bytesConsumed);
        if (num < 0)
        {
            ThrowConversionOverflow();
        }
        readOnlySpan = readOnlySpan.Slice(bytesConsumed);
        if (!readOnlySpan.IsEmpty)
        {
            num += GetCharCountWithFallback(readOnlySpan, originalByteCount, decoder);
            if (num < 0)
            {
                ThrowConversionOverflow();
            }
        }
        return num;
    }
References System.Runtime.Serialization.Dictionary, System.Text.DecoderNLS.DrainLeftoverDataForGetCharCount(), System.Text.DecoderNLS.Fallback, System.Text.Encoding.GetCharCountFast(), System.Text.Encoding.GetCharCountWithFallback(), System.Text.DecoderNLS.HasLeftoverData, and System.Text.Encoding.ThrowConversionOverflow().