Terraria: System.Text.Encoding.GetByteCount
GetByteCount() [3/7]
virtual int System.Text.Encoding.GetByteCount (char[] chars) inline virtual inherited
Reimplemented in System.Text.ConsoleEncoding, System.Text.ConsoleEncoding, and System.Xml.Ucs4Encoding.
Definition at line 713 of file Encoding.cs.
    {
        if (chars == null)
        {
            throw new ArgumentNullException("chars", SR.ArgumentNull_Array);
        }
        return GetByteCount(chars, 0, chars.Length);
    }
References System.SR.ArgumentNull_Array, System.chars, and System.Text.Encoding.GetByteCount().
Referenced by System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Net.Http.HPack.HPackEncoder.EncodeStringLiteral(), System.Net.Http.HPack.HPackEncoder.EncodeStringLiterals(), System.Net.Http.QPack.QPackEncoder.EncodeValueString(), System.Net.Http.QPack.QPackEncoder.EncodeValueString(), System.Security.Cryptography.PasswordBasedEncryption.Encrypt(), System.Text.ConsoleEncoding.GetByteCount(), System.Text.Encoding.GetByteCount(), System.Text.EncoderNLS.GetByteCount(), System.Text.Encoding.DefaultEncoder.GetByteCount(), System.Text.ConsoleEncoding.GetByteCount(), System.Text.Encoding.GetByteCount(), System.Xml.XmlStreamNodeWriter.GetByteCount(), System.Text.ConsoleEncoding.GetByteCount(), System.Text.Encoding.DefaultEncoder.GetByteCount(), System.Text.Encoding.GetByteCount(), System.Text.ConsoleEncoding.GetByteCount(), System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.EncodingExtensions.GetBytes(), System.Text.EncodingExtensions.GetBytes(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Security.Cryptography.PasswordBasedEncryption.Pbes2Decrypt(), System.Xml.XmlTextReaderImpl.UnDecodeChars(), System.IO.BinaryWriter.Write(), System.Formats.Asn1.AsnWriter.WriteCharacterStringCore(), and System.Net.Http.HttpConnection.WriteStringWithEncodingAsyncSlow().