Terraria: System.Text.Encoding.GetByteCountWithFallback
GetByteCountWithFallback() [3/3]
virtual unsafe int System.Text.Encoding.GetByteCountWithFallback (ReadOnlySpan< char > chars, int originalCharsLength, EncoderNLS encoder) inline protected virtual inherited
Definition at line 1177 of file Encoding.cs.
    {
        fixed (char* ptr = &MemoryMarshal.GetReference(chars))
        {
            EncoderFallbackBuffer encoderFallbackBuffer = EncoderFallbackBuffer.CreateAndInitialize(this, encoder, originalCharsLength);
            int num = 0;
            Rune result;
            int charsConsumed;
            while (Rune.DecodeFromUtf16(chars, out result, out charsConsumed) != OperationStatus.NeedMoreData || encoder == null || encoder.MustFlush)
            {
                int num2 = encoderFallbackBuffer.InternalFallbackGetByteCount(chars, out charsConsumed);
                num += num2;
                if (num < 0)
                {
                    ThrowConversionOverflow();
                }
                chars = chars.Slice(charsConsumed);
                if (!chars.IsEmpty)
                {
                    num2 = GetByteCountFast((char*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(chars)), chars.Length, null, out charsConsumed);
                    num += num2;
                    if (num < 0)
                    {
                        ThrowConversionOverflow();
                    }
                    chars = chars.Slice(charsConsumed);
                }
                if (chars.IsEmpty)
                {
                    break;
                }
            }
            return num;
        }
    }
References System.chars, System.Text.EncoderFallbackBuffer.CreateAndInitialize(), System.Text.Rune.DecodeFromUtf16(), System.Runtime.Serialization.Dictionary, System.Text.Encoding.GetByteCountFast(), System.Text.EncoderNLS.MustFlush, and System.Text.Encoding.ThrowConversionOverflow().