Terraria: System.Text.Encoding.GetBytesWithFallback
GetBytesWithFallback() [2/3]
unsafe int System.Text.Encoding.GetBytesWithFallback (char * pOriginalChars, int originalCharCount, byte * pOriginalBytes, int originalByteCount, int charsConsumedSoFar, int bytesWrittenSoFar, EncoderNLS encoder) inline private inherited
Definition at line 1240 of file Encoding.cs.
    {
        ReadOnlySpan<char> readOnlySpan = new ReadOnlySpan<char>(pOriginalChars, originalCharCount).Slice(charsConsumedSoFar);
        Span<byte> span = new Span<byte>(pOriginalBytes, originalByteCount).Slice(bytesWrittenSoFar);
        int charsConsumed;
        int bytesWritten;
        bool flag = encoder.TryDrainLeftoverDataForGetBytes(readOnlySpan, span, out charsConsumed, out bytesWritten);
        readOnlySpan = readOnlySpan.Slice(charsConsumed);
        span = span.Slice(bytesWritten);
        if (!flag)
        {
            ThrowBytesOverflow(encoder, span.Length == originalByteCount);
        }
        else
        {
            bytesWritten = GetBytesFast((char*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(readOnlySpan)), readOnlySpan.Length, (byte*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(span)), span.Length, out charsConsumed);
            readOnlySpan = readOnlySpan.Slice(charsConsumed);
            span = span.Slice(bytesWritten);
            if (!readOnlySpan.IsEmpty)
            {
                encoder._charsUsed = originalCharCount;
                return GetBytesWithFallback(readOnlySpan, originalCharCount, span, originalByteCount, encoder);
            }
        }
        encoder._charsUsed = originalCharCount - readOnlySpan.Length;
        return originalByteCount - span.Length;
    }
References System.Runtime.Serialization.Dictionary, System.Text.Encoding.GetBytesFast(), System.Text.Encoding.GetBytesWithFallback(), System.Text.Encoding.ThrowBytesOverflow(), and System.Text.EncoderNLS.TryDrainLeftoverDataForGetBytes().