Terraria: System.Text.Encoding.GetChars
GetChars() [3/6]
virtual char[] System.Text.Encoding.GetChars (byte[] bytes) inline virtual inherited
Reimplemented in System.Text.ConsoleEncoding, System.Text.ConsoleEncoding, and System.Text.Latin1Encoding.
Definition at line 921 of file Encoding.cs.
    {
        if (bytes == null)
        {
            throw new ArgumentNullException("bytes", SR.ArgumentNull_Array);
        }
        return GetChars(bytes, 0, bytes.Length);
    }
References System.SR.ArgumentNull_Array, System.bytes, and System.Text.Encoding.GetChars().
Referenced by System.Xml.EncodingStreamWrapper.EncodingStreamWrapper(), System.Text.DecoderNLS.Convert(), System.String.CreateStringFromEncoding(), System.Net.HttpListenerRequest.Helpers.UrlDecoder.FlushBytes(), System.Net.WebUtility.UrlDecoder.FlushBytes(), System.Web.Util.HttpEncoder.UrlDecoder.FlushBytes(), System.Text.ConsoleEncoding.GetChars(), System.Text.Encoding.GetChars(), System.Text.DecoderNLS.GetChars(), System.Text.Encoding.DefaultDecoder.GetChars(), System.Text.ConsoleEncoding.GetChars(), System.Text.Encoding.GetChars(), System.Text.ConsoleEncoding.GetChars(), System.Text.Encoding.DefaultDecoder.GetChars(), System.Text.ConsoleEncoding.GetChars(), System.Text.Encoding.GetChars(), System.Text.Encoding.GetChars(), System.Text.EncodingExtensions.GetChars(), System.Text.EncodingExtensions.GetChars(), System.Text.EncodingExtensions.GetChars(), System.Text.Encoding.GetString(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.InitForReading(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Read(), System.Xml.EncodingStreamWrapper.Read(), and System.Formats.Asn1.AsnDecoder.TryReadCharacterStringCore().