Terraria: System.Text.Encoding.GetCharCountWithFallback
GetCharCountWithFallback() [3/3]
unsafe int System.Text.Encoding.GetCharCountWithFallback (ReadOnlySpan< byte > bytes, int originalBytesLength, DecoderNLS decoder) inline private inherited
Definition at line 1380 of file Encoding.cs.
    {
        fixed (byte* ptr = &MemoryMarshal.GetReference(bytes))
        {
            DecoderFallbackBuffer decoderFallbackBuffer = DecoderFallbackBuffer.CreateAndInitialize(this, decoder, originalBytesLength);
            int num = 0;
            Rune value;
            int bytesConsumed;
            while (DecodeFirstRune(bytes, out value, out bytesConsumed) != OperationStatus.NeedMoreData || decoder == null || decoder.MustFlush)
            {
                int num2 = decoderFallbackBuffer.InternalFallbackGetCharCount(bytes, bytesConsumed);
                num += num2;
                if (num < 0)
                {
                    ThrowConversionOverflow();
                }
                bytes = bytes.Slice(bytesConsumed);
                if (!bytes.IsEmpty)
                {
                    num2 = GetCharCountFast((byte*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(bytes)), bytes.Length, null, out bytesConsumed);
                    num += num2;
                    if (num < 0)
                    {
                        ThrowConversionOverflow();
                    }
                    bytes = bytes.Slice(bytesConsumed);
                }
                if (bytes.IsEmpty)
                {
                    break;
                }
            }
            return num;
        }
    }
References System.bytes, System.Text.DecoderFallbackBuffer.CreateAndInitialize(), System.Text.Encoding.DecodeFirstRune(), System.Runtime.Serialization.Dictionary, System.Text.Encoding.GetCharCountFast(), System.Text.DecoderNLS.MustFlush, System.Text.Encoding.ThrowConversionOverflow(), and System.value.