Terraria: Internal.Cryptography.OidLookup.ToFriendlyName
ToFriendlyName()
static string Internal.Cryptography.OidLookup.ToFriendlyName (string oid, OidGroup oidGroup, bool fallBackToAllGroups) inline static
Definition at line 20 of file OidLookup.cs.
    {
        if (oid == null)
        {
            throw new ArgumentNullException("oid");
        }
        bool flag = ShouldUseCache(oidGroup);
        if (flag && (s_oidToFriendlyName.TryGetValue(oid, out var value) || s_compatOids.TryGetValue(oid, out value) || s_lateBoundOidToFriendlyName.TryGetValue(oid, out value)))
        {
            return value;
        }
        value = NativeOidToFriendlyName(oid, oidGroup, fallBackToAllGroups);
        if (flag && value != null)
        {
            s_lateBoundOidToFriendlyName.TryAdd(oid, value);
        }
        return value;
    }
References Internal.Cryptography.OidLookup.NativeOidToFriendlyName(), Internal.Cryptography.OidLookup.s_compatOids, Internal.Cryptography.OidLookup.s_lateBoundOidToFriendlyName, Internal.Cryptography.OidLookup.s_oidToFriendlyName, Internal.Cryptography.OidLookup.ShouldUseCache(), and System.value.
Referenced by System.Security.Cryptography.Oid.FromOidValue().