Terraria: System.Text.Encoding.Clone
Clone()
virtual object System.Text.Encoding.Clone () inline virtual inherited
Implements System.ICloneable.
Reimplemented in System.Text.ASCIIEncoding.ASCIIEncodingSealed, System.Text.Latin1Encoding.Latin1EncodingSealed, and System.Text.UTF8Encoding.UTF8EncodingSealed.
Definition at line 706 of file Encoding.cs.
    {
        Encoding encoding = (Encoding)MemberwiseClone();
        encoding._isReadOnly = false;
        return encoding;
    }
References System.Text.Encoding.Encoding(), and System.Runtime.Serialization.Dictionary.
Referenced by System.Xml.XmlEncodedRawTextWriter.XmlEncodedRawTextWriter(), System.Text.Encoding.GetEncoding(), System.Text.EncodingProvider.GetEncoding(), System.Text.EncodingProvider.GetEncoding(), and System.Diagnostics.TextWriterTraceListener.GetEncodingWithFallback().