Terraria: DropOneByOne.TryDroppingItem
TryDroppingItem()
ItemDropAttemptResult DropOneByOne.TryDroppingItem (DropAttemptInfo info) inline
Implements IItemDropRule.
     {
         ItemDropAttemptResult result;
         if (info.player.RollLuck(parameters.ChanceDenominator) < parameters.ChanceNumerator)
         {
             int num = info.rng.Next(parameters.MinimumItemDropsCount, parameters.MaximumItemDropsCount + 1);
             int activePlayersCount = Main.CurrentFrameFlags.ActivePlayersCount;
             int minValue = parameters.MinimumStackPerChunkBase + activePlayersCount * parameters.BonusMinDropsPerChunkPerPlayer;
             int num2 = parameters.MaximumStackPerChunkBase + activePlayersCount * parameters.BonusMaxDropsPerChunkPerPlayer;
             for (int i = 0; i < num; i++)
             {
                 CommonCode.DropItemFromNPC(info.npc, itemId, info.rng.Next(minValue, num2 + 1), scattered: true);
             }
             result = default(ItemDropAttemptResult);
             result.State = ItemDropAttemptResultState.Success;
             return result;
         }
         result = default(ItemDropAttemptResult);
         result.State = ItemDropAttemptResultState.FailedRandomRoll;
         return result;
     }
References Main.CurrentFrameFlags.ActivePlayersCount, DropOneByOne.Parameters.BonusMaxDropsPerChunkPerPlayer, DropOneByOne.Parameters.BonusMinDropsPerChunkPerPlayer, DropOneByOne.Parameters.ChanceDenominator, DropOneByOne.Parameters.ChanceNumerator, CommonCode.DropItemFromNPC(), itemId, DropOneByOne.Parameters.MaximumItemDropsCount, DropOneByOne.Parameters.MaximumStackPerChunkBase, DropOneByOne.Parameters.MinimumItemDropsCount, DropOneByOne.Parameters.MinimumStackPerChunkBase, UnifiedRandom.Next(), DropAttemptInfo.npc, parameters, DropAttemptInfo.player, DropAttemptInfo.rng, Player.RollLuck(), and ItemDropAttemptResult.State.