Terraria: System.Net.WebProxy.IsMatchInBypassList
IsMatchInBypassList()
bool System.Net.WebProxy.IsMatchInBypassList (Uri input) inline private
Definition at line 180 of file WebProxy.cs.
    {
        UpdateRegexList(canThrow: false);
        if (_regexBypassList != null)
        {
            Span<char> span = stackalloc char[128];
            string text;
            if (!input.IsDefaultPort)
            {
                IFormatProvider formatProvider = null;
                IFormatProvider provider = formatProvider;
                Span<char> span2 = span;
                Span<char> initialBuffer = span2;
                DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(4, 3, formatProvider, span2);
                handler.AppendFormatted(input.Scheme);
                handler.AppendLiteral("://");
                handler.AppendFormatted(input.Host);
                handler.AppendLiteral(":");
                handler.AppendFormatted((uint)input.Port);
                text = string.Create(provider, initialBuffer, ref handler);
            }
            else
            {
                IFormatProvider formatProvider = null;
                IFormatProvider provider2 = formatProvider;
                Span<char> span2 = span;
                Span<char> initialBuffer2 = span2;
                DefaultInterpolatedStringHandler handler2 = new DefaultInterpolatedStringHandler(3, 2, formatProvider, span2);
                handler2.AppendFormatted(input.Scheme);
                handler2.AppendLiteral("://");
                handler2.AppendFormatted(input.Host);
                text = string.Create(provider2, initialBuffer2, ref handler2);
            }
            string input2 = text;
            Regex[] regexBypassList = _regexBypassList;
            foreach (Regex regex in regexBypassList)
            {
                if (regex.IsMatch(input2))
                {
                    return true;
                }
            }
        }
        return false;
    }
References System.Net.WebProxy._regexBypassList, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Runtime.Serialization.Dictionary, System.input, System.text, and System.Net.WebProxy.UpdateRegexList().
Referenced by System.Net.WebProxy.IsBypassed().