Terraria: System.Net.WebProxy.IsLocal
IsLocal()
bool System.Net.WebProxy.IsLocal (Uri host) inline private
Definition at line 260 of file WebProxy.cs.
    {
        if (host.IsLoopback)
        {
            return true;
        }
        string host2 = host.Host;
        if (IPAddress.TryParse(host2, out IPAddress address))
        {
            EnsureNetworkChangeRegistration();
            IPAddress[] array = s_localAddresses ?? (s_localAddresses = Dns.GetHostEntry(Dns.GetHostName()).AddressList);
            return Array.IndexOf(array, address) != -1;
        }
        int num = host2.IndexOf('.');
        if (num == -1)
        {
            return true;
        }
        EnsureNetworkChangeRegistration();
        string text = s_domainName ?? (s_domainName = "." + IPGlobalProperties.GetIPGlobalProperties().DomainName);
        if (text.Length == host2.Length - num)
        {
            return string.Compare(text, 0, host2, num, text.Length, StringComparison.OrdinalIgnoreCase) == 0;
        }
        return false;
    }
References System.array, System.Runtime.Serialization.Dictionary, System.Net.WebProxy.EnsureNetworkChangeRegistration(), System.Net.Dns.GetHostEntry(), System.Net.Dns.GetHostName(), System.Net.NetworkInformation.IPGlobalProperties.GetIPGlobalProperties(), System.Array.IndexOf(), System.Net.WebProxy.s_domainName, System.Net.WebProxy.s_localAddresses, System.text, and System.Net.IPAddress.TryParse().
Referenced by System.Net.WebProxy.IsBypassed().