Terraria: System.Transactions.Bucket.TimeoutTransactions
TimeoutTransactions()
void System.Transactions.Bucket.TimeoutTransactions () inline package
Definition at line 63 of file Bucket.cs.
    {
        int index = _index;
        _timedOut = true;
        Interlocked.MemoryBarrier();
        for (int i = 0; i <= index && i < _size; i++)
        {
            InternalTransaction internalTransaction = _transactions[i];
            if (internalTransaction != null)
            {
                lock (internalTransaction)
                {
                    internalTransaction.State.Timeout(internalTransaction);
                }
            }
        }
    }
References System.Transactions.Bucket._index, System.Transactions.Bucket._size, System.Transactions.Bucket._timedOut, System.Transactions.Bucket._transactions, System.index, System.Threading.Interlocked.MemoryBarrier(), System.Transactions.InternalTransaction.State, and System.Transactions.TransactionState.Timeout().
Referenced by System.Transactions.BucketSet.TimeoutTransactions().