Terraria: System.Transactions.Bucket.Add
Add()
bool System.Transactions.Bucket.Add (InternalTransaction tx) inline package
Definition at line 30 of file Bucket.cs.
    {
        int num = Interlocked.Increment(ref _index);
        if (num < _size)
        {
            tx._tableBucket = this;
            tx._bucketIndex = num;
            Interlocked.MemoryBarrier();
            _transactions[num] = tx;
            if (_timedOut)
            {
                lock (tx)
                {
                    tx.State.Timeout(tx);
                }
            }
            return true;
        }
        Bucket bucket = new Bucket(_owningSet);
        bucket.nextBucketWeak = new WeakReference(this);
        Bucket bucket2 = Interlocked.CompareExchange(ref _owningSet.headBucket, bucket, this);
        if (bucket2 == this)
        {
            _previous = bucket;
        }
        return false;
    }
References System.Transactions.Bucket.Bucket(), System.Transactions.Bucket._index, System.Transactions.Bucket._owningSet, System.Transactions.Bucket._previous, System.Transactions.Bucket._size, System.Transactions.Bucket._timedOut, System.Transactions.Bucket._transactions, System.Threading.Interlocked.CompareExchange(), System.Transactions.BucketSet.headBucket, System.Threading.Interlocked.Increment(), System.Threading.Interlocked.MemoryBarrier(), System.Transactions.InternalTransaction.State, and System.Transactions.TransactionState.Timeout().
Referenced by System.Transactions.BucketSet.Add().