Terraria: System.Collections.Specialized.OrderedDictionary.Remove
Remove()
void System.Collections.Specialized.OrderedDictionary.Remove (object key) inline
Implements System.Collections.IDictionary.
Definition at line 355 of file OrderedDictionary.cs.
    {
        if (_readOnly)
        {
            throw new NotSupportedException(System.SR.OrderedDictionary_ReadOnly);
        }
        if (key == null)
        {
            throw new ArgumentNullException("key");
        }
        int num = IndexOfKey(key);
        if (num >= 0)
        {
            Hashtable hashtable = EnsureObjectsTable();
            ArrayList arrayList = EnsureObjectsArray();
            hashtable.Remove(key);
            arrayList.RemoveAt(num);
        }
    }
References System.Collections.Specialized.OrderedDictionary._readOnly, System.Runtime.Serialization.Dictionary, System.Collections.Specialized.OrderedDictionary.EnsureObjectsArray(), System.Collections.Specialized.OrderedDictionary.EnsureObjectsTable(), System.Collections.Specialized.OrderedDictionary.IndexOfKey(), System.key, System.SR.OrderedDictionary_ReadOnly, and System.Collections.Hashtable.Remove().
Referenced by System.ComponentModel.TypeDescriptor.PipelineFilter().