Terraria: System.Collections.Specialized.OrderedDictionary.OnDeserialization
OnDeserialization() [2/2]
virtual void System.Collections.Specialized.OrderedDictionary.OnDeserialization (object? sender) inline protected virtual
Implements System.Runtime.Serialization.IDeserializationCallback.
Definition at line 407 of file OrderedDictionary.cs.
    {
        if (_siInfo == null)
        {
            throw new SerializationException(System.SR.Serialization_InvalidOnDeser);
        }
        _comparer = (IEqualityComparer)_siInfo.GetValue("KeyComparer", typeof(IEqualityComparer));
        _readOnly = _siInfo.GetBoolean("ReadOnly");
        _initialCapacity = _siInfo.GetInt32("InitialCapacity");
        object[] array = (object[])_siInfo.GetValue("ArrayList", typeof(object[]));
        if (array == null)
        {
            return;
        }
        Hashtable hashtable = EnsureObjectsTable();
        ArrayList arrayList = EnsureObjectsArray();
        object[] array2 = array;
        foreach (object obj in array2)
        {
            DictionaryEntry dictionaryEntry;
            try
            {
                dictionaryEntry = (DictionaryEntry)obj;
            }
            catch
            {
                throw new SerializationException(System.SR.OrderedDictionary_SerializationMismatch);
            }
            arrayList.Add(dictionaryEntry);
            hashtable.Add(dictionaryEntry.Key, dictionaryEntry.Value);
        }
    }
References System.Collections.Specialized.OrderedDictionary._comparer, System.Collections.Specialized.OrderedDictionary._initialCapacity, System.Collections.Specialized.OrderedDictionary._readOnly, System.Collections.Specialized.OrderedDictionary._siInfo, System.array, System.Runtime.Serialization.Dictionary, System.Collections.Specialized.OrderedDictionary.EnsureObjectsArray(), System.Collections.Specialized.OrderedDictionary.EnsureObjectsTable(), System.Runtime.Serialization.SerializationInfo.GetBoolean(), System.Runtime.Serialization.SerializationInfo.GetInt32(), System.Runtime.Serialization.SerializationInfo.GetValue(), System.obj, System.SR.OrderedDictionary_SerializationMismatch, and System.SR.Serialization_InvalidOnDeser.