Terraria: GolfHelper.ContactListener.OnCollision
OnCollision()
void GolfHelper.ContactListener.OnCollision (PhysicsProperties properties, ref Vector2 position, ref Vector2 velocity, ref BallCollisionEvent collision) inline
Implements IBallContactListener.
         {
             TileMaterial byTileId = TileMaterials.GetByTileId(collision.Tile.type);
             Vector2 vector = velocity * byTileId.GolfPhysics.SideImpactDampening;
             Vector2 vector2 = collision.Normal * Vector2.Dot(velocity, collision.Normal) * (byTileId.GolfPhysics.DirectImpactDampening - byTileId.GolfPhysics.SideImpactDampening);
             velocity = vector + vector2;
             Projectile projectile = collision.Entity as Projectile;
             switch (collision.Tile.type)
             {
             case 421:
             case 422:
             {
                 float num2 = 2.5f * collision.TimeScale;
                 Vector2 vector3 = new Vector2(0f - collision.Normal.Y, collision.Normal.X);
                 if (collision.Tile.type == 422)
                 {
                     vector3 = -vector3;
                 }
                 float num3 = Vector2.Dot(velocity, vector3);
                 if (num3 < num2)
                 {
                     velocity += vector3 * MathHelper.Clamp(num2 - num3, 0f, num2 * 0.5f);
                 }
                 break;
             }
             case 476:
             {
                 float num = velocity.Length() / collision.TimeScale;
                 if (!(collision.Normal.Y > -0.01f) && !(num > 100f))
                 {
                     velocity *= 0f;
                     if (projectile != null && projectile.active)
                     {
                         PutBallInCup(projectile, collision);
                     }
                 }
                 break;
             }
             }
             if (projectile != null && velocity.Y < -0.3f && velocity.Y > -2f && velocity.Length() > 1f)
             {
                 Dust dust = Dust.NewDustPerfect(collision.Entity.Center, 31, collision.Normal, 127);
                 dust.scale = 0.7f;
                 dust.fadeIn = 1f;
                 dust.velocity = dust.velocity * 0.5f + Main.rand.NextVector2CircularEdge(0.5f, 0.4f);
             }
         }
References Entity.active, TileGolfPhysics.DirectImpactDampening, Dust.fadeIn, TileMaterials.GetByTileId(), TileMaterial.GolfPhysics, Dust.NewDustPerfect(), GolfHelper.ContactListener.PutBallInCup(), Main.rand, Dust.scale, TileGolfPhysics.SideImpactDampening, and Dust.velocity.