Terraria: GolfHelper.ContactListener.EmitGolfballExplosion
EmitGolfballExplosion()
static void GolfHelper.ContactListener.EmitGolfballExplosion (Vector2 Center) inline static
         {
             SoundEngine.PlaySound(SoundID.Item129, Center);
             for (float num = 0f; num < 1f; num += 0.085f)
             {
                 Dust dust = Dust.NewDustPerfect(Center, 278, (num * ((float)Math.PI * 2f)).ToRotationVector2() * new Vector2(2f, 0.5f));
                 dust.fadeIn = 1.2f;
                 dust.noGravity = true;
                 dust.velocity.X *= 0.7f;
                 dust.velocity.Y -= 1.5f;
                 dust.position.Y += 8f;
                 dust.velocity.X *= 2f;
                 dust.color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f);
             }
             float num2 = Main.rand.NextFloat();
             float num3 = Main.rand.Next(5, 10);
             for (int i = 0; (float)i < num3; i++)
             {
                 int num4 = Main.rand.Next(5, 22);
                 Vector2 value = (((float)i - num3 / 2f) * ((float)Math.PI * 2f) / 256f - (float)Math.PI / 2f).ToRotationVector2() * new Vector2(5f, 1f) * (0.25f + Main.rand.NextFloat() * 0.05f);
                 Color color = Main.hslToRgb((num2 + (float)i / num3) % 1f, 0.7f, 0.7f);
                 color.A = 127;
                 for (int j = 0; j < num4; j++)
                 {
                     Dust dust2 = Dust.NewDustPerfect(Center + new Vector2((float)i - num3 / 2f, 0f) * 2f, 278, value);
                     dust2.fadeIn = 0.7f;
                     dust2.scale = 0.7f;
                     dust2.noGravity = true;
                     dust2.position.Y += -1f;
                     dust2.velocity *= (float)j;
                     dust2.scale += 0.2f - (float)j * 0.03f;
                     dust2.velocity += Main.rand.NextVector2Circular(0.05f, 0.05f);
                     dust2.color = color;
                 }
             }
             for (float num5 = 0f; num5 < 1f; num5 += 0.2f)
             {
                 Dust dust3 = Dust.NewDustPerfect(Center, 278, (num5 * ((float)Math.PI * 2f)).ToRotationVector2() * new Vector2(1f, 0.5f));
                 dust3.fadeIn = 1.2f;
                 dust3.noGravity = true;
                 dust3.velocity.X *= 0.7f;
                 dust3.velocity.Y -= 0.5f;
                 dust3.position.Y += 8f;
                 dust3.velocity.X *= 2f;
                 dust3.color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.3f);
             }
             float num6 = Main.rand.NextFloatDirection();
             for (float num7 = 0f; num7 < 1f; num7 += 0.15f)
             {
                 Dust dust4 = Dust.NewDustPerfect(Center, 278, (num6 + num7 * ((float)Math.PI * 2f)).ToRotationVector2() * 4f);
                 dust4.fadeIn = 1.5f;
                 dust4.velocity *= 0.5f + num7 * 0.8f;
                 dust4.noGravity = true;
                 dust4.velocity.X *= 0.35f;
                 dust4.velocity.Y *= 2f;
                 dust4.velocity.Y -= 1f;
                 dust4.velocity.Y = 0f - Math.Abs(dust4.velocity.Y);
                 dust4.position += dust4.velocity * 3f;
                 dust4.color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.6f + Main.rand.NextFloat() * 0.2f);
             }
         }
References Color, Dust.color, Dust.fadeIn, Main.hslToRgb(), SoundID.Item129, Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, SoundEngine.PlaySound(), Dust.position, Main.rand, Dust.scale, and Dust.velocity.
Referenced by GolfHelper.ContactListener.EmitGolfballExplosion_Old(), and GolfHelper.ContactListener.PutBallInCup_TextAndEffects().