Terraria: GolfHelper.ContactListener.PutBallInCup_TextAndEffects
PutBallInCup_TextAndEffects()
static void GolfHelper.ContactListener.PutBallInCup_TextAndEffects (Point hitLocation, int plr, int numberOfHits, int projid) inline static
         {
             if (numberOfHits != 0)
             {
                 EmitGolfballExplosion(hitLocation.ToWorldCoordinates(8f, 0f));
                 string key = "Game.BallBounceResultGolf_Single";
                 NetworkText networkText;
                 if (numberOfHits != 1)
                 {
                     key = "Game.BallBounceResultGolf_Plural";
                     networkText = NetworkText.FromKey(key, Main.player[plr].name, NetworkText.FromKey(Lang.GetProjectileName(projid).Key), numberOfHits);
                 }
                 else
                 {
                     networkText = NetworkText.FromKey(key, Main.player[plr].name, NetworkText.FromKey(Lang.GetProjectileName(projid).Key));
                 }
                 if (Main.netMode == 0 || Main.netMode == 1)
                 {
                     Main.NewText(networkText.ToString(), byte.MaxValue, 240, 20);
                 }
                 else if (Main.netMode == 2)
                 {
                     ChatHelper.BroadcastChatMessage(networkText, new Color(255, 240, 20));
                 }
             }
         }
References ChatHelper.BroadcastChatMessage(), Color, GolfHelper.ContactListener.EmitGolfballExplosion(), NetworkText.FromKey(), Lang.GetProjectileName(), LocalizedText.Key, Player.name, Main.netMode, Main.NewText(), Main.player, and NetworkText.ToString().
Referenced by MessageBuffer.GetData(), and GolfHelper.ContactListener.PutBallInCup().