Terraria: System.Reflection.Emit.MethodBuilder.GetModuleBuilder
GetModuleBuilder()
ModuleBuilder System.Reflection.Emit.MethodBuilder.GetModuleBuilder () inline package
Definition at line 395 of file MethodBuilder.cs.
    {
        return m_module;
    }
References System.Reflection.Emit.MethodBuilder.m_module.
Referenced by System.Reflection.Emit.ParameterBuilder.ParameterBuilder(), System.Reflection.Emit.MethodBuilder.GetModule(), System.Reflection.Emit.ParameterBuilder.SetConstant(), and System.Reflection.Emit.ParameterBuilder.SetCustomAttribute().