Terraria: System.Reflection.Emit.MethodBuilder.GetMethodSignature
GetMethodSignature()
SignatureHelper System.Reflection.Emit.MethodBuilder.GetMethodSignature () inline package
Definition at line 328 of file MethodBuilder.cs.
    {
        if (m_parameterTypes == null)
        {
            m_parameterTypes = Type.EmptyTypes;
        }
        m_signature = SignatureHelper.GetMethodSigHelper(m_module, m_callingConvention, (m_inst != null) ? m_inst.Length : 0, m_returnType, m_returnTypeRequiredCustomModifiers, m_returnTypeOptionalCustomModifiers, m_parameterTypes, m_parameterTypeRequiredCustomModifiers, m_parameterTypeOptionalCustomModifiers);
        return m_signature;
    }
References System.Type.EmptyTypes, System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(), System.Reflection.Emit.MethodBuilder.m_callingConvention, System.Reflection.Emit.MethodBuilder.m_inst, System.Reflection.Emit.MethodBuilder.m_module, System.Reflection.Emit.MethodBuilder.m_parameterTypeOptionalCustomModifiers, System.Reflection.Emit.MethodBuilder.m_parameterTypeRequiredCustomModifiers, System.Reflection.Emit.MethodBuilder.m_parameterTypes, System.Reflection.Emit.MethodBuilder.m_returnType, System.Reflection.Emit.MethodBuilder.m_returnTypeOptionalCustomModifiers, System.Reflection.Emit.MethodBuilder.m_returnTypeRequiredCustomModifiers, and System.Reflection.Emit.MethodBuilder.m_signature.
Referenced by System.Reflection.Emit.ConstructorBuilder.ConstructorBuilder(), System.Reflection.Emit.MethodBuilder.Equals(), System.Reflection.Emit.ConstructorBuilder.GetMethodSignature(), System.Reflection.Emit.MethodBuilder.GetTokenNoLock(), and System.Reflection.Emit.MethodBuilder.ToString().