Terraria: System.Reflection.Emit.MethodBuilder.ThrowIfShouldNotHaveBody
ThrowIfShouldNotHaveBody()
void System.Reflection.Emit.MethodBuilder.ThrowIfShouldNotHaveBody () inline private
Definition at line 667 of file MethodBuilder.cs.
    {
        if ((m_dwMethodImplFlags & MethodImplAttributes.CodeTypeMask) != 0 || (m_dwMethodImplFlags & MethodImplAttributes.ManagedMask) != 0 || (m_iAttributes & MethodAttributes.PinvokeImpl) != 0 || m_isDllImport)
        {
            throw new InvalidOperationException(SR.InvalidOperation_ShouldNotHaveMethodBody);
        }
    }
References System.SR.InvalidOperation_ShouldNotHaveMethodBody, System.Reflection.Emit.MethodBuilder.m_dwMethodImplFlags, System.Reflection.Emit.MethodBuilder.m_iAttributes, and System.Reflection.Emit.MethodBuilder.m_isDllImport.
Referenced by System.Reflection.Emit.MethodBuilder.CreateMethodBodyHelper(), System.Reflection.Emit.MethodBuilder.GetILGenerator(), and System.Reflection.Emit.MethodBuilder.GetILGenerator().