Terraria: System.Reflection.Emit.MethodBuilder.GetILGenerator
GetILGenerator() [1/2]
ILGenerator System.Reflection.Emit.MethodBuilder.GetILGenerator () inline
Definition at line 653 of file MethodBuilder.cs.
    {
        ThrowIfGeneric();
        ThrowIfShouldNotHaveBody();
        return m_ilGenerator ?? (m_ilGenerator = new ILGenerator(this));
    }
References System.Reflection.Emit.MethodBuilder.m_ilGenerator, System.Reflection.Emit.MethodBuilder.ThrowIfGeneric(), and System.Reflection.Emit.MethodBuilder.ThrowIfShouldNotHaveBody().
Referenced by System.Reflection.Emit.IgnoreAccessChecksToAttributeBuilder.AddToModule(), System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Xsl.IlGen.XmlILModule.DefineMethodBody(), System.Reflection.Emit.ConstructorBuilder.GetILGenerator(), System.Reflection.Emit.ConstructorBuilder.GetILGenerator(), and System.Reflection.Emit.ILGenerator.UsingNamespace().