Terraria: System.Reflection.Emit.MethodBuilder.GetTokenNoLock
GetTokenNoLock()
int System.Reflection.Emit.MethodBuilder.GetTokenNoLock () inline private
Definition at line 569 of file MethodBuilder.cs.
    {
        int length;
        byte[] signature = GetMethodSignature().InternalGetSignature(out length);
        ModuleBuilder module = m_module;
        int tkMethod = (m_token = TypeBuilder.DefineMethod(new QCallModule(ref module), m_containingType.MetadataToken, m_strName, signature, length, Attributes));
        if (m_inst != null)
        {
            GenericTypeParameterBuilder[] inst = m_inst;
            foreach (GenericTypeParameterBuilder genericTypeParameterBuilder in inst)
            {
                if (!genericTypeParameterBuilder.m_type.IsCreated())
                {
                    genericTypeParameterBuilder.m_type.CreateType();
                }
            }
        }
        TypeBuilder.SetMethodImpl(new QCallModule(ref module), tkMethod, m_dwMethodImplFlags);
        return m_token;
    }
References System.Reflection.Emit.MethodBuilder.Attributes, System.Reflection.Emit.TypeBuilder.CreateType(), System.Reflection.Emit.TypeBuilder.DefineMethod(), System.Reflection.Emit.MethodBuilder.GetMethodSignature(), System.Reflection.Emit.SignatureHelper.InternalGetSignature(), System.Reflection.Emit.TypeBuilder.IsCreated(), System.length, System.Reflection.Emit.MethodBuilder.m_containingType, System.Reflection.Emit.MethodBuilder.m_dwMethodImplFlags, System.Reflection.Emit.MethodBuilder.m_inst, System.Reflection.Emit.MethodBuilder.m_module, System.Reflection.Emit.MethodBuilder.m_strName, System.Reflection.Emit.MethodBuilder.m_token, System.Reflection.Emit.GenericTypeParameterBuilder.m_type, System.Reflection.Emit.TypeBuilder.MetadataToken, and System.Reflection.Emit.TypeBuilder.SetMethodImpl().
Referenced by System.Reflection.Emit.MethodBuilder.GetToken().