Terraria: System.Reflection.Emit.MethodBuilder.DefineParameter
DefineParameter()
ParameterBuilder System.Reflection.Emit.MethodBuilder.DefineParameter (int position, ParameterAttributes attributes, string? strParamName) inline
Definition at line 627 of file MethodBuilder.cs.
    {
        if (position < 0)
        {
            throw new ArgumentOutOfRangeException(SR.ArgumentOutOfRange_ParamSequence);
        }
        ThrowIfGeneric();
        m_containingType.ThrowIfCreated();
        if (position > 0 && (m_parameterTypes == null || position > m_parameterTypes.Length))
        {
            throw new ArgumentOutOfRangeException(SR.ArgumentOutOfRange_ParamSequence);
        }
        attributes &= ~ParameterAttributes.ReservedMask;
        return new ParameterBuilder(this, position, attributes, strParamName);
    }
References System.SR.ArgumentOutOfRange_ParamSequence, System.Reflection.Emit.MethodBuilder.m_containingType, System.Reflection.Emit.MethodBuilder.m_parameterTypes, System.Reflection.Emit.TypeBuilder.ThrowIfCreated(), and System.Reflection.Emit.MethodBuilder.ThrowIfGeneric().
Referenced by System.Reflection.Emit.ConstructorBuilder.DefineParameter(), and System.Xml.Serialization.CodeGenerator.InitILGeneration().