Terraria: System.Reflection.Emit.MethodBuilder.SetSignature
SetSignature()
void System.Reflection.Emit.MethodBuilder.SetSignature (Type? returnType, Type?[] returnTypeRequiredCustomModifiers, Type?[] returnTypeOptionalCustomModifiers, Type?[] parameterTypes, Type? parameterTypeRequiredCustomModifiers[][], Type? parameterTypeOptionalCustomModifiers[][]) inline
Definition at line 602 of file MethodBuilder.cs.
    {
        if (m_token == 0)
        {
            AssemblyBuilder.CheckContext(returnType);
            AssemblyBuilder.CheckContext(returnTypeRequiredCustomModifiers, returnTypeOptionalCustomModifiers, parameterTypes);
            AssemblyBuilder.CheckContext(parameterTypeRequiredCustomModifiers);
            AssemblyBuilder.CheckContext(parameterTypeOptionalCustomModifiers);
            ThrowIfGeneric();
            if (returnType != null)
            {
                m_returnType = returnType;
            }
            if (parameterTypes != null)
            {
                m_parameterTypes = new Type[parameterTypes.Length];
                Array.Copy(parameterTypes, m_parameterTypes, parameterTypes.Length);
            }
            m_returnTypeRequiredCustomModifiers = returnTypeRequiredCustomModifiers;
            m_returnTypeOptionalCustomModifiers = returnTypeOptionalCustomModifiers;
            m_parameterTypeRequiredCustomModifiers = parameterTypeRequiredCustomModifiers;
            m_parameterTypeOptionalCustomModifiers = parameterTypeOptionalCustomModifiers;
        }
    }
References System.Reflection.Emit.AssemblyBuilder.CheckContext(), System.Array.Copy(), System.Reflection.Emit.MethodBuilder.m_parameterTypeOptionalCustomModifiers, System.Reflection.Emit.MethodBuilder.m_parameterTypeRequiredCustomModifiers, System.Reflection.Emit.MethodBuilder.m_parameterTypes, System.Reflection.Emit.MethodBuilder.m_returnType, System.Reflection.Emit.MethodBuilder.m_returnTypeOptionalCustomModifiers, System.Reflection.Emit.MethodBuilder.m_returnTypeRequiredCustomModifiers, System.Reflection.Emit.MethodBuilder.m_token, and System.Reflection.Emit.MethodBuilder.ThrowIfGeneric().
Referenced by System.Reflection.Emit.MethodBuilder.SetParameters(), and System.Reflection.Emit.MethodBuilder.SetReturnType().