Terraria: System.Reflection.Emit.MethodBuilder.SetCustomAttribute
SetCustomAttribute() [2/2]
void System.Reflection.Emit.MethodBuilder.SetCustomAttribute (CustomAttributeBuilder customBuilder) inline
Definition at line 698 of file MethodBuilder.cs.
    {
        if (customBuilder == null)
        {
            throw new ArgumentNullException("customBuilder");
        }
        ThrowIfGeneric();
        customBuilder.CreateCustomAttribute(m_module, MetadataToken);
        if (IsKnownCA(customBuilder.m_con))
        {
            ParseCA(customBuilder.m_con);
        }
    }
References System.Reflection.Emit.CustomAttributeBuilder.CreateCustomAttribute(), System.Reflection.Emit.MethodBuilder.IsKnownCA(), System.Reflection.Emit.CustomAttributeBuilder.m_con, System.Reflection.Emit.MethodBuilder.m_module, System.Reflection.Emit.MethodBuilder.ParseCA(), and System.Reflection.Emit.MethodBuilder.ThrowIfGeneric().