Terraria: System.Reflection.Emit.MethodBuilder.CreateMethodBodyHelper
CreateMethodBodyHelper()
void System.Reflection.Emit.MethodBuilder.CreateMethodBodyHelper (ILGenerator il) inline package
Definition at line 220 of file MethodBuilder.cs.
    {
        if (il == null)
        {
            throw new ArgumentNullException("il");
        }
        int num = 0;
        ModuleBuilder module = m_module;
        m_containingType.ThrowIfCreated();
        if (m_bIsBaked)
        {
            throw new InvalidOperationException(SR.InvalidOperation_MethodHasBody);
        }
        if (il.m_methodBuilder != this && il.m_methodBuilder != null)
        {
            throw new InvalidOperationException(SR.InvalidOperation_BadILGeneratorUsage);
        }
        ThrowIfShouldNotHaveBody();
        if (il.m_ScopeTree.m_iOpenScopeCount != 0)
        {
            throw new InvalidOperationException(SR.InvalidOperation_OpenLocalVariableScope);
        }
        m_ubBody = il.BakeByteArray();
        m_mdMethodFixups = il.GetTokenFixups();
        __ExceptionInfo[] exceptions = il.GetExceptions();
        int num2 = CalculateNumberOfExceptions(exceptions);
        if (num2 > 0)
        {
            m_exceptions = new ExceptionHandler[num2];
            for (int i = 0; i < exceptions.Length; i++)
            {
                int[] filterAddresses = exceptions[i].GetFilterAddresses();
                int[] catchAddresses = exceptions[i].GetCatchAddresses();
                int[] catchEndAddresses = exceptions[i].GetCatchEndAddresses();
                Type[] catchClass = exceptions[i].GetCatchClass();
                int numberOfCatches = exceptions[i].GetNumberOfCatches();
                int startAddress = exceptions[i].GetStartAddress();
                int endAddress = exceptions[i].GetEndAddress();
                int[] exceptionTypes = exceptions[i].GetExceptionTypes();
                for (int j = 0; j < numberOfCatches; j++)
                {
                    int exceptionTypeToken = 0;
                    if (catchClass[j] != null)
                    {
                        exceptionTypeToken = module.GetTypeTokenInternal(catchClass[j]);
                    }
                    switch (exceptionTypes[j])
                    {
                    case 0:
                    case 1:
                    case 4:
                        m_exceptions[num++] = new ExceptionHandler(startAddress, endAddress, filterAddresses[j], catchAddresses[j], catchEndAddresses[j], exceptionTypes[j], exceptionTypeToken);
                        break;
                    case 2:
                        m_exceptions[num++] = new ExceptionHandler(startAddress, exceptions[i].GetFinallyEndAddress(), filterAddresses[j], catchAddresses[j], catchEndAddresses[j], exceptionTypes[j], exceptionTypeToken);
                        break;
                    }
                }
            }
        }
        m_bIsBaked = true;
    }
References System.Reflection.Emit.ILGenerator.BakeByteArray(), System.Reflection.Emit.MethodBuilder.CalculateNumberOfExceptions(), System.exceptions, System.Reflection.Emit.ILGenerator.GetExceptions(), System.Reflection.Emit.ILGenerator.GetTokenFixups(), System.Reflection.Emit.ModuleBuilder.GetTypeTokenInternal(), System.SR.InvalidOperation_BadILGeneratorUsage, System.SR.InvalidOperation_MethodHasBody, System.SR.InvalidOperation_OpenLocalVariableScope, System.Reflection.Emit.MethodBuilder.m_bIsBaked, System.Reflection.Emit.MethodBuilder.m_containingType, System.Reflection.Emit.MethodBuilder.m_exceptions, System.Reflection.Emit.ScopeTree.m_iOpenScopeCount, System.Reflection.Emit.MethodBuilder.m_mdMethodFixups, System.Reflection.Emit.ILGenerator.m_methodBuilder, System.Reflection.Emit.MethodBuilder.m_module, System.Reflection.Emit.ILGenerator.m_ScopeTree, System.Reflection.Emit.MethodBuilder.m_ubBody, System.Reflection.Emit.TypeBuilder.ThrowIfCreated(), and System.Reflection.Emit.MethodBuilder.ThrowIfShouldNotHaveBody().