Terraria: ReLogic.Utilities.MultiTimer.Record
Record()
void ReLogic.Utilities.MultiTimer.Record (string key) inline
Definition at line 62 of file MultiTimer.cs.
    {
        _timer.Stop();
        double totalMilliseconds = _timer.Elapsed.TotalMilliseconds;
        if (!_timerDataMap.TryGetValue(key, out var value))
        {
            _timerDataMap.Add(key, new TimerData(totalMilliseconds));
        }
        else
        {
            _timerDataMap[key] = value.AddTick(totalMilliseconds);
        }
        _timer.Reset();
        _timer.Start();
    }
References ReLogic.Utilities.MultiTimer._timer, ReLogic.Utilities.MultiTimer._timerDataMap, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Diagnostics.Stopwatch.Elapsed, System.key, System.Diagnostics.Stopwatch.Reset(), System.Diagnostics.Stopwatch.Start(), System.Diagnostics.Stopwatch.Stop(), System.TimeSpan.TotalMilliseconds, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.