Terraria: ReLogic.Utilities.MultiTimer.StopAndPrint
StopAndPrint()
bool ReLogic.Utilities.MultiTimer.StopAndPrint () inline
Definition at line 78 of file MultiTimer.cs.
    {
        _timer.Stop();
        _ticksElapsedForPrint++;
        if (_ticksElapsedForPrint == _ticksBetweenPrint)
        {
            _ticksElapsedForPrint = 0;
            Console.WriteLine("Average elapsed time: ");
            double num = 0.0;
            int num2 = 0;
            foreach (KeyValuePair<string, TimerData> item3 in _timerDataMap)
            {
                num2 = Math.Max(item3.Key.Length, num2);
            }
            foreach (KeyValuePair<string, TimerData> item2 in _timerDataMap)
            {
                TimerData value = item2.Value;
                string text = new string(' ', num2 - item2.Key.Length);
                Console.WriteLine(item2.Key + text + " : (Average: " + value.Average.ToString("F4") + " Min: " + value.Min.ToString("F4") + " Max: " + value.Max.ToString("F4") + " from " + (int)value.Ticks + " records)");
                num += value.Total;
            }
            _timerDataMap.Clear();
            Console.WriteLine("Total : " + (float)num / (float)_ticksBetweenPrint + "ms");
            return true;
        }
        return false;
    }
References ReLogic.Utilities.MultiTimer._ticksBetweenPrint, ReLogic.Utilities.MultiTimer._ticksElapsedForPrint, ReLogic.Utilities.MultiTimer._timer, ReLogic.Utilities.MultiTimer._timerDataMap, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Math.Max(), System.Diagnostics.Stopwatch.Stop(), System.text, System.value, and System.Console.WriteLine().