Terraria: BirthdayParty.CheckNight
CheckNight()
static void BirthdayParty.CheckNight () inline static
     {
         bool flag = false;
         if (GenuineParty)
         {
             flag = true;
             GenuineParty = false;
             CelebratingNPCs.Clear();
         }
         if (ManualParty)
         {
             flag = true;
             ManualParty = false;
         }
         if (flag)
         {
             WorldGen.BroadcastText(color: new Color(255, 0, 160), text: NetworkText.FromKey(Lang.misc[99].Key));
         }
     }
References WorldGen.BroadcastText(), CelebratingNPCs, Color, NetworkText.FromKey(), GenuineParty, LocalizedText.Key, ManualParty, and Lang.misc.
Referenced by Main.UpdateTime_StartNight().