Terraria: BirthdayParty.CheckForAchievement
CheckForAchievement()
static void BirthdayParty.CheckForAchievement () inline static private
     {
         if (PartyIsUp)
         {
             AchievementsHelper.NotifyProgressionEvent(25);
         }
     }
References AchievementsHelper.NotifyProgressionEvent(), and PartyIsUp.
Referenced by NaturalAttempt(), and ToggleManualParty().