Terraria: BirthdayParty.UpdateTime
UpdateTime()
static void BirthdayParty.UpdateTime () inline static
     {
         if (_wasCelebrating != PartyIsUp)
         {
             if (Main.netMode != 2)
             {
                 if (PartyIsUp)
                 {
                     SkyManager.Instance.Activate("Party", default(Vector2));
                 }
                 else
                 {
                     SkyManager.Instance.Deactivate("Party");
                 }
             }
             if (Main.netMode != 1 && CelebratingNPCs.Count > 0)
             {
                 for (int i = 0; i < CelebratingNPCs.Count; i++)
                 {
                     if (!CanNPCParty(Main.npc[CelebratingNPCs[i]]))
                     {
                         CelebratingNPCs.RemoveAt(i);
                     }
                 }
                 if (CelebratingNPCs.Count == 0)
                 {
                     GenuineParty = false;
                     if (!ManualParty)
                     {
                         WorldGen.BroadcastText(color: new Color(255, 0, 160), text: NetworkText.FromKey(Lang.misc[99].Key));
                         NetMessage.SendData(7);
                     }
                 }
             }
         }
         _wasCelebrating = PartyIsUp;
     }
References _wasCelebrating, EffectManager< T >.Activate(), WorldGen.BroadcastText(), CanNPCParty(), CelebratingNPCs, Color, EffectManager< T >.Deactivate(), NetworkText.FromKey(), GenuineParty, SkyManager.Instance, LocalizedText.Key, ManualParty, Lang.misc, Main.netMode, Main.npc, PartyIsUp, and NetMessage.SendData().
Referenced by Main.UpdateTime().