Terraria: Terraria.GameContent.ShopHelper.HateNPC
HateNPC()
void Terraria.GameContent.ShopHelper.HateNPC (int npcType) inline
    {
        AddHappinessReportText("HateNPC", new
        {
            NPCName = NPC.GetFullnameByID(npcType)
        });
        _currentPriceAdjustment *= 1.12f;
    }
References Terraria.GameContent.ShopHelper._currentPriceAdjustment, Terraria.GameContent.ShopHelper.AddHappinessReportText(), and Terraria.NPC.GetFullnameByID().
Referenced by Terraria.GameContent.Personalities.NPCPreferenceTrait.ModifyShopPrice(), and Terraria.GameContent.Personalities.AllPersonalitiesModifier.ModifyShopPrice_Relationships().