Terraria: Terraria.GameContent.ShopHelper.AddHappinessReportText
AddHappinessReportText()
void Terraria.GameContent.ShopHelper.AddHappinessReportText (string textKeyInCategory, object substitutes = null) inline private
Definition at line 208 of file ShopHelper.cs.
    {
        string text = "TownNPCMood_" + NPCID.Search.GetName(_currentNPCBeingTalkedTo.netID);
        if (_currentNPCBeingTalkedTo.type == 633 && _currentNPCBeingTalkedTo.altTexture == 2)
        {
            text += "Transformed";
        }
        string textValueWith = Language.GetTextValueWith(text + "." + textKeyInCategory, substitutes);
        _currentHappiness = _currentHappiness + textValueWith + " ";
    }
References Terraria.GameContent.ShopHelper._currentHappiness, Terraria.GameContent.ShopHelper._currentNPCBeingTalkedTo, Terraria.NPC.altTexture, Terraria.Localization.Language.GetTextValueWith(), Terraria.NPC.netID, Terraria.ID.NPCID.Search, and Terraria.NPC.type.
Referenced by Terraria.GameContent.ShopHelper.DislikeBiome(), Terraria.GameContent.ShopHelper.DislikeNPC(), Terraria.GameContent.ShopHelper.HateBiome(), Terraria.GameContent.ShopHelper.HateNPC(), Terraria.GameContent.ShopHelper.IsFarFromHome(), Terraria.GameContent.ShopHelper.IsPlayerInEvilBiomes(), Terraria.GameContent.ShopHelper.LikeBiome(), Terraria.GameContent.ShopHelper.LikeNPC(), Terraria.GameContent.ShopHelper.LikePrincess(), Terraria.GameContent.ShopHelper.LoveBiome(), Terraria.GameContent.ShopHelper.LoveNPC(), Terraria.GameContent.ShopHelper.LoveNPCByTypeName(), Terraria.GameContent.ShopHelper.ProcessMood(), and Terraria.GameContent.ShopHelper.RuinMoodIfHomeless().