Terraria: Terraria.GameContent.Bestiary.FilterProviderInfoElement.ProvideUIElement
ProvideUIElement()
UIElement Terraria.GameContent.Bestiary.FilterProviderInfoElement.ProvideUIElement (BestiaryUICollectionInfo info) inline inherited
Implements Terraria.GameContent.Bestiary.IBestiaryInfoElement.
Definition at line 55 of file FilterProviderInfoElement.cs.
    {
        if (HideInPortraitInfo)
        {
            return null;
        }
        if (info.UnlockState == BestiaryEntryUnlockState.NotKnownAtAll_0)
        {
            return null;
        }
        UIElement uIElement = new UIPanel(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Panel", (AssetRequestMode)1), null, 12, 7)
        {
            Width = new StyleDimension(-14f, 1f),
            Height = new StyleDimension(34f, 0f),
            BackgroundColor = new Color(43, 56, 101),
            BorderColor = Color.Transparent,
            Left = new StyleDimension(5f, 0f)
        };
        uIElement.SetPadding(0f);
        uIElement.PaddingRight = 5f;
        UIElement filterImage = GetFilterImage();
        filterImage.HAlign = 0f;
        filterImage.Left = new StyleDimension(5f, 0f);
        UIText element = new UIText(Language.GetText(GetDisplayNameKey()), 0.8f)
        {
            HAlign = 0f,
            Left = new StyleDimension(38f, 0f),
            TextOriginX = 0f,
            TextOriginY = 0f,
            VAlign = 0.5f,
            DynamicallyScaleDownToWidth = true
        };
        if (filterImage != null)
        {
            uIElement.Append(filterImage);
        }
        uIElement.Append(element);
        AddOnHover(uIElement);
        return uIElement;
    }
References Terraria.GameContent.Bestiary.FilterProviderInfoElement.AddOnHover(), Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.Bestiary.FilterProviderInfoElement.GetDisplayNameKey(), Terraria.GameContent.Bestiary.FilterProviderInfoElement.GetFilterImage(), Terraria.Localization.Language.GetText(), Terraria.GameContent.Bestiary.FilterProviderInfoElement.HideInPortraitInfo, Terraria.UI.UIElement.SetPadding(), and Microsoft.Xna.Framework.Color.Transparent.