Terraria: System.Runtime.Serialization.Formatter.WriteMember
WriteMember()
virtual void System.Runtime.Serialization.Formatter.WriteMember (string memberName, object? data) inline protected virtual
Definition at line 88 of file Formatter.cs.
    {
        if (data == null)
        {
            WriteObjectRef(data, memberName, typeof(object));
            return;
        }
        Type type = data.GetType();
        if (type == typeof(bool))
        {
            WriteBoolean(Convert.ToBoolean(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(char))
        {
            WriteChar(Convert.ToChar(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(sbyte))
        {
            WriteSByte(Convert.ToSByte(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(byte))
        {
            WriteByte(Convert.ToByte(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(short))
        {
            WriteInt16(Convert.ToInt16(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(int))
        {
            WriteInt32(Convert.ToInt32(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(long))
        {
            WriteInt64(Convert.ToInt64(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(float))
        {
            WriteSingle(Convert.ToSingle(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(double))
        {
            WriteDouble(Convert.ToDouble(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(DateTime))
        {
            WriteDateTime(Convert.ToDateTime(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(decimal))
        {
            WriteDecimal(Convert.ToDecimal(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(ushort))
        {
            WriteUInt16(Convert.ToUInt16(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(uint))
        {
            WriteUInt32(Convert.ToUInt32(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type == typeof(ulong))
        {
            WriteUInt64(Convert.ToUInt64(data, CultureInfo.InvariantCulture), memberName);
        }
        else if (type.IsArray)
        {
            WriteArray(data, memberName, type);
        }
        else if (type.IsValueType)
        {
            WriteValueType(data, memberName, type);
        }
        else
        {
            WriteObjectRef(data, memberName, type);
        }
    }
References System.Runtime.Serialization.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Convert.ToBoolean(), System.Convert.ToByte(), System.Convert.ToChar(), System.Convert.ToDateTime(), System.Convert.ToDecimal(), System.Convert.ToDouble(), System.Convert.ToInt16(), System.Convert.ToInt32(), System.Convert.ToInt64(), System.Convert.ToSByte(), System.Convert.ToSingle(), System.Convert.ToUInt16(), System.Convert.ToUInt32(), System.Convert.ToUInt64(), System.type, System.Runtime.Serialization.Formatter.WriteArray(), System.Runtime.Serialization.Formatter.WriteBoolean(), System.Runtime.Serialization.Formatter.WriteByte(), System.Runtime.Serialization.Formatter.WriteChar(), System.Runtime.Serialization.Formatter.WriteDateTime(), System.Runtime.Serialization.Formatter.WriteDecimal(), System.Runtime.Serialization.Formatter.WriteDouble(), System.Runtime.Serialization.Formatter.WriteInt16(), System.Runtime.Serialization.Formatter.WriteInt32(), System.Runtime.Serialization.Formatter.WriteInt64(), System.Runtime.Serialization.Formatter.WriteObjectRef(), System.Runtime.Serialization.Formatter.WriteSByte(), System.Runtime.Serialization.Formatter.WriteSingle(), System.Runtime.Serialization.Formatter.WriteUInt16(), System.Runtime.Serialization.Formatter.WriteUInt32(), System.Runtime.Serialization.Formatter.WriteUInt64(), and System.Runtime.Serialization.Formatter.WriteValueType().