Terraria: System.IO.FileLoadException.ToString
ToString()
override string System.IO.FileLoadException.ToString () inline
Definition at line 79 of file FileLoadException.cs.
    {
        string text = GetType().ToString() + ": " + Message;
        if (!string.IsNullOrEmpty(FileName))
        {
            text = text + "\r\n" + SR.Format(SR.IO_FileName_Name, FileName);
        }
        if (base.InnerException != null)
        {
            text = text + "\r\n ---> " + base.InnerException.ToString();
        }
        if (StackTrace != null)
        {
            text = text + "\r\n" + StackTrace;
        }
        if (FusionLog != null)
        {
            if (text == null)
            {
                text = " ";
            }
            text = text + "\r\n\r\n" + FusionLog;
        }
        return text;
    }
References System.Runtime.Serialization.Dictionary, System.IO.FileLoadException.FileName, System.SR.Format(), System.IO.FileLoadException.FusionLog, System.Exception.GetType(), System.SR.IO_FileName_Name, System.IO.FileLoadException.Message, System.Exception.StackTrace, System.text, and System.Type.ToString().