Terraria: System.IO.FileLoadException.FormatFileLoadExceptionMessage
FormatFileLoadExceptionMessage()
static string System.IO.FileLoadException.FormatFileLoadExceptionMessage (string fileName, int hResult) inline static package
Definition at line 25 of file FileLoadException.cs.
    {
        string s = null;
        GetFileLoadExceptionMessage(hResult, new StringHandleOnStack(ref s));
        string s2 = null;
        if (hResult == -2147024703)
        {
            s2 = SR.Arg_BadImageFormatException;
        }
        else
        {
            GetMessageForHR(hResult, new StringHandleOnStack(ref s2));
        }
        return string.Format(s, fileName, s2);
    }
References System.SR.Arg_BadImageFormatException, System.Runtime.Serialization.Dictionary, System.IO.FileLoadException.GetFileLoadExceptionMessage(), System.IO.FileLoadException.GetMessageForHR(), and System.s.
Referenced by System.IO.FileLoadException.FileLoadException(), System.IO.FileNotFoundException.SetMessageField(), and System.BadImageFormatException.SetMessageField().