Terraria: GenAction.UnitApply
UnitApply()
bool GenAction.UnitApply (Point origin, int x, int y, params object[] args) inline protected inherited
     {
         if (OutputData != null)
         {
             OutputData.Add(x - origin.X, y - origin.Y);
         }
         if (NextAction != null)
         {
             return NextAction.Apply(origin, x, y, args);
         }
         return true;
     }
References ShapeData.Add(), GenAction.Apply(), GenAction.NextAction, and GenAction.OutputData.
Referenced by ActionGrass.Apply(), ActionPlaceStatue.Apply(), ActionStalagtite.Apply(), ActionVines.Apply(), Actions.ContinueWrapper.Apply(), Actions.Count.Apply(), Actions.Scanner.Apply(), Actions.TileScanner.Apply(), Actions.Blank.Apply(), Actions.Custom.Apply(), Actions.ClearMetadata.Apply(), Actions.Clear.Apply(), Actions.ClearTile.Apply(), Actions.ClearWall.Apply(), Actions.HalfBlock.Apply(), Actions.SetTile.Apply(), Actions.SetTileKeepWall.Apply(), Actions.DebugDraw.Apply(), Actions.SetSlope.Apply(), Actions.SetHalfTile.Apply(), Actions.SetTileAndWallRainbowPaint.Apply(), Actions.PlaceTile.Apply(), Actions.RemoveWall.Apply(), Actions.PlaceWall.Apply(), Actions.SetLiquid.Apply(), Actions.SwapSolidTile.Apply(), Actions.SetFrames.Apply(), Actions.Smooth.Apply(), Modifiers.ShapeScale.Apply(), Modifiers.Expand.Apply(), Modifiers.RadialDither.Apply(), Modifiers.Blotches.Apply(), Modifiers.InShape.Apply(), Modifiers.NotInShape.Apply(), Modifiers.Conditions.Apply(), Modifiers.OnlyWalls.Apply(), Modifiers.OnlyTiles.Apply(), Modifiers.IsTouching.Apply(), Modifiers.NotTouching.Apply(), Modifiers.IsTouchingAir.Apply(), Modifiers.SkipTiles.Apply(), Modifiers.HasLiquid.Apply(), Modifiers.SkipWalls.Apply(), Modifiers.IsEmpty.Apply(), Modifiers.IsSolid.Apply(), Modifiers.IsNotSolid.Apply(), Modifiers.RectangleMask.Apply(), Modifiers.Offset.Apply(), Modifiers.Dither.Apply(), and Modifiers.Flip.Apply().