Terraria: System.Resources.RuntimeResourceSet.ReadValue
ReadValue()
static object System.Resources.RuntimeResourceSet.ReadValue (ResourceReader reader, int dataPos, bool isString, out ResourceLocator locator) inline static private
Definition at line 161 of file RuntimeResourceSet.cs.
    {
        object obj;
        ResourceTypeCode typeCode;
        if (isString)
        {
            obj = reader.LoadString(dataPos);
            typeCode = ResourceTypeCode.String;
        }
        else
        {
            obj = reader.LoadObject(dataPos, out typeCode);
        }
        locator = new ResourceLocator(dataPos, ResourceLocator.CanCache(typeCode) ? obj : null);
        return obj;
    }
References System.Resources.ResourceLocator.CanCache(), System.Resources.ResourceReader.LoadObject(), System.Resources.ResourceReader.LoadString(), and System.obj.
Referenced by System.Resources.RuntimeResourceSet.GetObject().