Terraria: System.Runtime.Serialization.Json.JsonWriterDelegator.WriteDateTimeInDefaultFormat
WriteDateTimeInDefaultFormat()
void System.Runtime.Serialization.Json.JsonWriterDelegator.WriteDateTimeInDefaultFormat (DateTime value) inline private
Definition at line 168 of file JsonWriterDelegator.cs.
    {
        if (value.Kind != DateTimeKind.Utc)
        {
            long num = 864000000000L;
            long num2 = 3155378111999999999L;
            long ticks = value.Ticks;
            if (num > ticks || num2 < ticks)
            {
                ticks -= TimeZoneInfo.Local.GetUtcOffset(value).Ticks;
                if (ticks > DateTime.MaxValue.Ticks || ticks < DateTime.MinValue.Ticks)
                {
                    throw XmlObjectSerializer.CreateSerializationException(System.SR.JsonDateTimeOutOfRange, new ArgumentOutOfRangeException("value"));
                }
            }
        }
        writer.WriteString("/Date(");
        writer.WriteValue((value.ToUniversalTime().Ticks - JsonGlobals.unixEpochTicks) / 10000);
        switch (value.Kind)
        {
        case DateTimeKind.Unspecified:
        case DateTimeKind.Local:
        {
            TimeSpan utcOffset = TimeZoneInfo.Local.GetUtcOffset(value.ToLocalTime());
            XmlWriter xmlWriter = writer;
            IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
            DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(0, 2, invariantCulture);
            handler.AppendFormatted(utcOffset.Hours, "+00;-00");
            handler.AppendFormatted(utcOffset.Minutes, "00;00");
            xmlWriter.WriteString(string.Create(invariantCulture, ref handler));
            break;
        }
        }
        writer.WriteString(")/");
    }
References System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.SR.JsonDateTimeOutOfRange, System.L, System.TimeZoneInfo.Local, System.DateTime.MaxValue, System.DateTime.MinValue, System.Runtime.Serialization.Json.JsonGlobals.unixEpochTicks, System.value, System.Runtime.Serialization.XmlWriterDelegator.writer, System.Xml.XmlWriter.WriteString(), and System.Xml.XmlWriter.WriteValue().
Referenced by System.Runtime.Serialization.Json.JsonWriterDelegator.WriteDateTime().