Terraria: System.Runtime.Serialization.Json.JsonWriterDelegator.WriteStartElement
WriteStartElement() [2/4]
override void System.Runtime.Serialization.Json.JsonWriterDelegator.WriteStartElement (string prefix, string localName, string ns) inline package virtual
Reimplemented from System.Runtime.Serialization.XmlWriterDelegator.
Definition at line 220 of file JsonWriterDelegator.cs.
    {
        if (localName != null && localName.Length == 0)
        {
            WriteStartElement("item", "item");
            WriteAttributeString(null, "item", null, localName);
        }
        else
        {
            base.WriteStartElement(prefix, localName, ns);
        }
    }
References System.Runtime.Serialization.Dictionary, System.prefix, System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeString(), and System.Runtime.Serialization.Json.JsonWriterDelegator.WriteStartElement().
Referenced by System.Runtime.Serialization.Json.JsonWriterDelegator.WriteStartElement().