Terraria: GenAction.Apply
Apply()
abstract bool GenAction.Apply (Point origin, int x, int y, params object[] args) pure virtual
Implemented in Modifiers.Flip, Modifiers.Dither, Modifiers.Offset, Modifiers.RectangleMask, Modifiers.IsNotSolid, Modifiers.IsSolid, Modifiers.IsEmpty, Modifiers.SkipWalls, Modifiers.HasLiquid, Modifiers.SkipTiles, Modifiers.IsTouchingAir, Modifiers.NotTouching, Modifiers.IsTouching, Modifiers.OnlyTiles, Modifiers.OnlyWalls, Modifiers.Conditions, Modifiers.NotInShape, Modifiers.InShape, Modifiers.Blotches, Modifiers.RadialDither, Modifiers.Expand, Modifiers.ShapeScale, Actions.Smooth, Actions.SetFrames, Actions.SwapSolidTile, Actions.SetLiquid, Actions.PlaceWall, Actions.RemoveWall, Actions.PlaceTile, Actions.SetTileAndWallRainbowPaint, Actions.SetHalfTile, Actions.SetSlope, Actions.DebugDraw, Actions.SetTileKeepWall, Actions.SetTile, Actions.HalfBlock, Actions.ClearWall, Actions.ClearTile, Actions.Clear, Actions.ClearMetadata, Actions.Custom, Actions.Blank, Actions.TileScanner, Actions.Scanner, Actions.Count, Actions.ContinueWrapper, ActionVines, ActionStalagtite, ActionPlaceStatue, and ActionGrass.
Referenced by Actions.ContinueWrapper.Apply(), GenShape.UnitApply(), and UnitApply().