Terraria: System.Data.Common.DataTableMapping.DataTableMappingConverter.ConvertTo
ConvertTo() [1/3]
override object System.Data.Common.DataTableMapping.DataTableMappingConverter.ConvertTo (ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType) inline
Definition at line 23 of file DataTableMapping.cs.
        {
            if (null == destinationType)
            {
                throw ADP.ArgumentNull("destinationType");
            }
            if (typeof(InstanceDescriptor) == destinationType && value is DataTableMapping)
            {
                DataTableMapping dataTableMapping = (DataTableMapping)value;
                DataColumnMapping[] array = new DataColumnMapping[dataTableMapping.ColumnMappings.Count];
                dataTableMapping.ColumnMappings.CopyTo(array, 0);
                object[] arguments = new object[3] { dataTableMapping.SourceTable, dataTableMapping.DataSetTable, array };
                Type[] types = new Type[3]
                {
                    typeof(string),
                    typeof(string),
                    typeof(DataColumnMapping[])
                };
                ConstructorInfo constructor = typeof(DataTableMapping).GetConstructor(types);
                return new InstanceDescriptor(constructor, arguments);
            }
            return base.ConvertTo(context, culture, value, destinationType);
        }
References System.Data.Common.DataTableMapping.DataTableMapping(), System.Data.Common.ADP.ArgumentNull(), System.array, System.Data.Common.DataTableMapping.ColumnMappings, System.Collections.ICollection.CopyTo(), System.Collections.ICollection.Count, System.culture, System.Data.Common.DataTableMapping.DataSetTable, System.Data.Common.DataTableMapping.SourceTable, and System.value.