Terraria: Internal.Cryptography.Helpers.ValidateDer
ValidateDer()
static void Internal.Cryptography.Helpers.ValidateDer (ReadOnlyMemory< byte > encodedValue) inline static
Definition at line 151 of file Helpers.cs.
    {
        try
        {
            AsnReader asnReader = new AsnReader(encodedValue, AsnEncodingRules.DER);
            while (asnReader.HasData)
            {
                Asn1Tag asn1Tag = asnReader.PeekTag();
                if (asn1Tag.TagClass == TagClass.Universal)
                {
                    switch ((UniversalTagNumber)asn1Tag.TagValue)
                    {
                    case UniversalTagNumber.External:
                    case UniversalTagNumber.Embedded:
                    case UniversalTagNumber.Sequence:
                    case UniversalTagNumber.Set:
                    case UniversalTagNumber.UnrestrictedCharacterString:
                        if (!asn1Tag.IsConstructed)
{
                            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
                        }
                        break;
                    default:
                        if (asn1Tag.IsConstructed)
{
                            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
                        }
                        break;
                    }
                }
                if (asn1Tag.IsConstructed)
                {
                    ValidateDer(asnReader.PeekContentBytes());
                }
                asnReader.ReadEncodedValue();
            }
        }
        catch (AsnContentException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
        }
    }
References System.SR.Cryptography_Der_Invalid_Encoding, and Internal.Cryptography.Helpers.ValidateDer().
Referenced by System.Security.Cryptography.X509Certificates.CertificateRequest.Create(), System.Security.Cryptography.X509Certificates.Pkcs10CertificationRequestInfo.ToPkcs10Request(), and Internal.Cryptography.Helpers.ValidateDer().