Terraria: Terraria.Graphics.Light.TileLightScanner.ApplyLiquidLight
ApplyLiquidLight()
void Terraria.Graphics.Light.TileLightScanner.ApplyLiquidLight (Tile tile, ref Vector3 lightColor) inline private
    {
        if (tile.liquid <= 0)
        {
            return;
        }
        if (tile.lava())
        {
            float num = 0.55f;
            num += (float)(270 - Main.mouseTextColor) / 900f;
            if (lightColor.X < num)
            {
                lightColor.X = num;
            }
            if (lightColor.Y < num)
            {
                lightColor.Y = num * 0.6f;
            }
            if (lightColor.Z < num)
            {
                lightColor.Z = num * 0.2f;
            }
        }
        else if (tile.shimmer())
        {
            float num2 = 0.7f;
            float num3 = 0.7f;
            num2 += (float)(270 - Main.mouseTextColor) / 900f;
            num3 += (float)(270 - Main.mouseTextColor) / 125f;
            if (lightColor.X < num2)
            {
                lightColor.X = num2 * 0.6f;
            }
            if (lightColor.Y < num3)
            {
                lightColor.Y = num3 * 0.25f;
            }
            if (lightColor.Z < num2)
            {
                lightColor.Z = num2 * 0.9f;
            }
        }
    }
References Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.mouseTextColor, and Terraria.Tile.shimmer().
Referenced by Terraria.Graphics.Light.TileLightScanner.GetTileLight().