Terraria: Terraria.Graphics.Light.TileLightScanner.LightIsBlocked
LightIsBlocked()
bool Terraria.Graphics.Light.TileLightScanner.LightIsBlocked (Tile tile) inline private
    {
        if (tile.active() && Main.tileBlockLight[tile.type])
        {
            if (tile.invisibleBlock())
            {
                return _drawInvisibleWalls;
            }
            return true;
        }
        return false;
    }
References Terraria.Graphics.Light.TileLightScanner._drawInvisibleWalls, Terraria.Tile.active(), Terraria.Tile.invisibleBlock(), Terraria.Main.tileBlockLight, and Terraria.Tile.type.
Referenced by Terraria.Graphics.Light.TileLightScanner.ApplyWallLight(), and Terraria.Graphics.Light.TileLightScanner.GetTileMask().