Terraria: Terraria.Graphics.Light.TileLightScanner.GetTileLight
GetTileLight()
void Terraria.Graphics.Light.TileLightScanner.GetTileLight (int x, int y, out Vector3 outputColor) inline
    {
        outputColor = Vector3.Zero;
        Tile tile = Main.tile[x, y];
        FastRandom localRandom = _random.WithModifier(x, y);
        if (y <= (int)Main.worldSurface)
        {
            ApplySurfaceLight(tile, x, y, ref outputColor);
        }
        else if (y > Main.UnderworldLayer)
        {
            ApplyHellLight(tile, x, y, ref outputColor);
        }
        ApplyWallLight(tile, x, y, ref localRandom, ref outputColor);
        if (tile.active())
        {
            ApplyTileLight(tile, x, y, ref localRandom, ref outputColor);
        }
        ApplyLiquidLight(tile, ref outputColor);
    }
References Terraria.Graphics.Light.TileLightScanner._random, Terraria.Tile.active(), Terraria.Graphics.Light.TileLightScanner.ApplyHellLight(), Terraria.Graphics.Light.TileLightScanner.ApplyLiquidLight(), Terraria.Graphics.Light.TileLightScanner.ApplySurfaceLight(), Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), Terraria.Graphics.Light.TileLightScanner.ApplyWallLight(), Terraria.Main.tile, Terraria.Main.UnderworldLayer, Terraria.Utilities.FastRandom.WithModifier(), and Terraria.Main.worldSurface.
Referenced by Terraria.Graphics.Light.TileLightScanner.ExportTo().