Terraria: Terraria.Graphics.Light.TileLightScanner.ExportTo
ExportTo()
void Terraria.Graphics.Light.TileLightScanner.ExportTo (Rectangle area, LightMap outputMap, TileLightScannerOptions options) inline
Definition at line 17 of file TileLightScanner.cs.
    {
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Expected O, but got Unknown
        _drawInvisibleWalls = options.DrawInvisibleWalls;
        FastParallel.For(area.Left, area.Right, (ParallelForAction)delegate(int start, int end, object context)
        {
            for (int i = start; i < end; i++)
            {
                for (int j = area.Top; j <= area.Bottom; j++)
                {
                    if (IsTileNullOrTouchingNull(i, j))
                    {
                        outputMap.SetMaskAt(i - area.X, j - area.Y, LightMaskMode.None);
                        outputMap[i - area.X, j - area.Y] = Vector3.Zero;
                    }
                    else
                    {
                        LightMaskMode tileMask = GetTileMask(Main.tile[i, j]);
                        outputMap.SetMaskAt(i - area.X, j - area.Y, tileMask);
                        GetTileLight(i, j, out var outputColor);
                        outputMap[i - area.X, j - area.Y] = outputColor;
                    }
                }
            }
        }, (object)null);
    }
References Terraria.Graphics.Light.TileLightScanner._drawInvisibleWalls, Microsoft.Xna.Framework.Rectangle.Bottom, ReLogic.Threading.FastParallel.For(), Terraria.Graphics.Light.TileLightScanner.GetTileLight(), Terraria.Graphics.Light.TileLightScanner.GetTileMask(), Terraria.Graphics.Light.TileLightScanner.IsTileNullOrTouchingNull(), Microsoft.Xna.Framework.Rectangle.Left, System.options, ReLogic.Threading.ParallelForAction(), Microsoft.Xna.Framework.Rectangle.Right, Terraria.Graphics.Light.LightMap.SetMaskAt(), System.start, Terraria.Main.tile, Microsoft.Xna.Framework.Rectangle.Top, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector3.Zero.
Referenced by Terraria.Graphics.Light.LegacyLighting.PreRenderPhase(), and Terraria.Graphics.Light.LightingEngine.ProcessScan().