Terraria: System.Linq.Parallel.IndexedSelectQueryOperator.IndexedSelectQueryOperatorResults.NewResults
NewResults()
static QueryResults< TOutput > System.Linq.Parallel.IndexedSelectQueryOperator< TInput, TOutput >.IndexedSelectQueryOperatorResults.NewResults (QueryResults< TInput > childQueryResults, IndexedSelectQueryOperator< TInput, TOutput > op, QuerySettings settings, bool preferStriping) inline static
Definition at line 48 of file IndexedSelectQueryOperator.cs.
        {
            if (childQueryResults.IsIndexible)
            {
                return new IndexedSelectQueryOperatorResults(childQueryResults, op, settings, preferStriping);
            }
            return new UnaryQueryOperatorResults(childQueryResults, op, settings, preferStriping);
        }
References System.Linq.Parallel.IndexedSelectQueryOperator< TInput, TOutput >.IndexedSelectQueryOperatorResults.IndexedSelectQueryOperatorResults(), and System.Linq.Parallel.UnaryQueryOperator< TInput, TOutput >.UnaryQueryOperatorResults.UnaryQueryOperatorResults().
Referenced by System.Linq.Parallel.IndexedSelectQueryOperator< TInput, TOutput >.Open().