Terraria: DesertBiome.Place
Place()
override bool DesertBiome.Place (Point origin, StructureMap structures) inline virtual
Implements GenStructure.
     {
         DesertDescription desertDescription = DesertDescription.CreateFromPlacement(origin);
         if (!desertDescription.IsValid)
         {
             return false;
         }
         ExportDescriptionToEngine(desertDescription);
         SandMound.Place(desertDescription);
         desertDescription.UpdateSurfaceMap();
         if (!Main.tenthAnniversaryWorld && GenBase._random.NextDouble() <= ChanceOfEntrance)
         {
             switch (GenBase._random.Next(4))
             {
             case 0:
                 ChambersEntrance.Place(desertDescription);
                 break;
             case 1:
                 AnthillEntrance.Place(desertDescription);
                 break;
             case 2:
                 LarvaHoleEntrance.Place(desertDescription);
                 break;
             case 3:
                 PitEntrance.Place(desertDescription);
                 break;
             }
         }
         DesertHive.Place(desertDescription);
         CleanupArea(desertDescription.Hive);
         Rectangle area = new Rectangle(desertDescription.CombinedArea.X, 50, desertDescription.CombinedArea.Width, desertDescription.CombinedArea.Bottom - 20);
         structures.AddStructure(area, 10);
         return true;
     }
References GenBase._random, StructureMap.AddStructure(), ChanceOfEntrance, CleanupArea(), DesertDescription.CombinedArea, DesertDescription.CreateFromPlacement(), ExportDescriptionToEngine(), DesertDescription.Hive, DesertDescription.IsValid, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), AnthillEntrance.Place(), ChambersEntrance.Place(), DesertHive.Place(), LarvaHoleEntrance.Place(), PitEntrance.Place(), SandMound.Place(), Main.tenthAnniversaryWorld, and DesertDescription.UpdateSurfaceMap().
Referenced by WorldGen.GenerateWorld().