Terraria: Terraria.UI.Chat.ChatManager.GetStringSize
GetStringSize() [2/2]
static Vector2 Terraria.UI.Chat.ChatManager.GetStringSize (DynamicSpriteFont font, TextSnippet[] snippets, Vector2 baseScale, float maxWidth = -1f) inline static
Definition at line 124 of file ChatManager.cs.
    {
        Vector2 vec = new Vector2(Main.mouseX, Main.mouseY);
        Vector2 zero = Vector2.Zero;
        Vector2 vector = zero;
        Vector2 result = vector;
        float x = font.MeasureString(" ").X;
        float num = 1f;
        float num2 = 0f;
        foreach (TextSnippet textSnippet in snippets)
        {
            textSnippet.Update();
            num = textSnippet.Scale;
            if (textSnippet.UniqueDraw(justCheckingString: true, out var size, null))
            {
                vector.X += size.X * baseScale.X * num;
                result.X = Math.Max(result.X, vector.X);
                result.Y = Math.Max(result.Y, vector.Y + size.Y);
                continue;
            }
            string[] array = textSnippet.Text.Split('\n');
            string[] array2 = array;
            for (int j = 0; j < array2.Length; j++)
            {
                string[] array3 = array2[j].Split(' ');
                for (int k = 0; k < array3.Length; k++)
                {
                    if (k != 0)
                    {
                        vector.X += x * baseScale.X * num;
                    }
                    if (maxWidth > 0f)
                    {
                        float num3 = font.MeasureString(array3[k]).X * baseScale.X * num;
                        if (vector.X - zero.X + num3 > maxWidth)
{
                            vector.X = zero.X;
                            vector.Y += (float)font.LineSpacing * num2 * baseScale.Y;
                            result.Y = Math.Max(result.Y, vector.Y);
                            num2 = 0f;
                        }
                    }
                    if (num2 < num)
                    {
                        num2 = num;
                    }
                    Vector2 vector2 = font.MeasureString(array3[k]);
                    vec.Between(vector, vector + vector2);
                    vector.X += vector2.X * baseScale.X * num;
                    result.X = Math.Max(result.X, vector.X);
                    result.Y = Math.Max(result.Y, vector.Y + vector2.Y);
                }
                if (array.Length > 1)
                {
                    vector.X = zero.X;
                    vector.Y += (float)font.LineSpacing * num2 * baseScale.Y;
                    result.Y = Math.Max(result.Y, vector.Y);
                    num2 = 0f;
                }
            }
        }
        return result;
    }
References ReLogic.Graphics.DynamicSpriteFont.MeasureString(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.UI.Chat.TextSnippet.Scale, Terraria.UI.Chat.TextSnippet.Text, Terraria.UI.Chat.TextSnippet.UniqueDraw(), and Terraria.UI.Chat.TextSnippet.Update().