Terraria: Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow
DrawColorCodedStringWithShadow() [3/3]
static Vector2 Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow (SpriteBatch spriteBatch, DynamicSpriteFont font, TextSnippet[] snippets, Vector2 position, float rotation, Vector2 origin, Vector2 baseScale, out int hoveredSnippet, float maxWidth = -1f, float spread = 2f) inline static
References Terraria.UI.Chat.ChatManager.DrawColorCodedString(), and Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow().
Referenced by Terraria.GameContent.UI.GameTipsDisplay.Draw(), Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.Utils.DrawBorderString(), Terraria.UI.ChestUI.DrawButton(), Terraria.Graphics.Capture.CaptureInterface.DrawCameraLock(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.DrawChat(), Terraria.GameContent.UI.Chat.RemadeChatMonitor.DrawChat(), Terraria.Main.DrawDefenseCounter(), Terraria.Main.DrawGamepadInstructions(), Terraria.Main.DrawInterface_14_EntityHealthBars(), Terraria.Main.DrawInventory(), Terraria.UI.ChestUI.DrawName(), Terraria.Main.DrawNetplayStatusText(), Terraria.Main.DrawPlayerChat(), Terraria.Main.DrawPlayerChatBubbles(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawPlayerName(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingSimpleListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingSliderItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingToggleListItem.DrawSelf(), Terraria.Main.GUIChatDrawInner(), Terraria.Main.MouseText_DrawItemTooltip(), and Terraria.Main.MouseTextInner().