Terraria: Terraria.UI.Chat.ChatManager.AddChatText
AddChatText()
static bool Terraria.UI.Chat.ChatManager.AddChatText (DynamicSpriteFont font, string text, Vector2 baseScale) inline static
Definition at line 106 of file ChatManager.cs.
    {
        int num = 470;
        num = Main.screenWidth - 330;
        if (GetStringSize(font, Main.chatText + text, baseScale).X > (float)num)
        {
            return false;
        }
        Main.chatText += text;
        return true;
    }
References Terraria.Main.chatText, Terraria.UI.Chat.ChatManager.GetStringSize(), and System.text.
Referenced by Terraria.Main.GUIChatDrawInner(), and Terraria.UI.ItemSlot.OverrideLeftClick().