Terraria: Terraria.UI.Chat.ChatManager.ParseMessage
ParseMessage()
static List< TextSnippet > Terraria.UI.Chat.ChatManager.ParseMessage (string text, Color baseColor) inline static
Definition at line 72 of file ChatManager.cs.
    {
        text = text.Replace("\r", "");
        MatchCollection matchCollection = Regexes.Format.Matches(text);
        List<TextSnippet> list = new List<TextSnippet>();
        int num = 0;
        foreach (Match item in matchCollection)
        {
            if (item.Index > num)
            {
                list.Add(new TextSnippet(text.Substring(num, item.Index - num), baseColor));
            }
            num = item.Index + item.Length;
            string value = item.Groups["tag"].Value;
            string value2 = item.Groups["text"].Value;
            string value3 = item.Groups["options"].Value;
            ITagHandler handler = GetHandler(value);
            if (handler != null)
            {
                list.Add(handler.Parse(value2, baseColor, value3));
                list[list.Count - 1].TextOriginal = item.ToString();
            }
            else
            {
                list.Add(new TextSnippet(value2, baseColor));
            }
        }
        if (text.Length > num)
        {
            list.Add(new TextSnippet(text.Substring(num, text.Length - num), baseColor));
        }
        return list;
    }
References Terraria.UI.Chat.ChatManager.Regexes.Format, Terraria.UI.Chat.ChatManager.GetHandler(), System.item, System.list, Terraria.UI.Chat.ITagHandler.Parse(), System.text, and System.value.
Referenced by Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.DrawNetplayStatusText(), Terraria.Main.DrawPlayerChat(), Terraria.GameContent.UI.Elements.UIText.DrawSelf(), Terraria.Main.GetInputText(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Player.OverheadMessage.NewMessage(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextInternal(), and Terraria.Utils.WordwrapStringSmart().