Terraria: NetMessage.SendTileSquare
SendTileSquare() [2/3]
static void NetMessage.SendTileSquare (int whoAmi, int tileX, int tileY, int xSize, int ySize, TileChangeType changeType = TileChangeType.None) inline static
     {
         SendData(20, whoAmi, -1, null, tileX, tileY, xSize, ySize, (int)changeType);
         WorldGen.RangeFrame(tileX, tileY, xSize, ySize);
     }
References WorldGen.RangeFrame(), and SendData().
Referenced by NPC.AI_003_Fighters(), NPC.AI_045_Golem(), NPC.AI_047_GolemFist(), WorldGen.AttemptToGeneratePlanteraBulbAt(), NPC.BigMimicSummonCheck(), TELogicSensor.ChangeState(), WorldGen.CheckAlch(), WorldGen.CheckBamboo(), WorldGen.CheckCatTail(), WorldGen.CheckLilyPad(), Wiring.CheckLogicGate(), WorldGen.CheckUnderwaterPlant(), WorldGen.ChlorophyteDefense(), WorldGen.Convert(), NPC.CreateBrickBoxForWallOfFlesh(), Wiring.DeActive(), Liquid.DelWater(), Player.DoBootsEffect_PlaceFlowersOnTile(), WorldGen.ExplodeMine(), Minecart.FlipSwitchTrack(), MessageBuffer.GetData(), WorldGen.GrowAlch(), WorldGen.GrowCactus(), WorldGen.GrowCatTail(), WorldGen.GrowCheckSeaweed(), WorldGen.GrowEpicTree(), WorldGen.GrowPalmTree(), WorldGen.GrowPumpkin(), WorldGen.GrowSeaOat(), WorldGen.GrowShroom(), WorldGen.GrowSpike(), WorldGen.GrowTree(), WorldGen.GrowTreeWithSettings(), WorldGen.GrowUndergroundTree(), WorldGen.GrowWeb(), WorldGen.hardUpdateWorld(), Wiring.HitWireSingle(), TETrainingDummy.Hook_AfterPlacement(), TEItemFrame.Hook_AfterPlacement(), TELogicSensor.Hook_AfterPlacement(), TEDisplayDoll.Hook_AfterPlacement(), TEWeaponsRack.Hook_AfterPlacement(), TEHatRack.Hook_AfterPlacement(), TEFoodPlatter.Hook_AfterPlacement(), Player.ItemCheck_TryPlacingWearablesOnMannequins(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), WorldGen.KillTile(), WorldGen.LaunchRocket(), Liquid.LiquidCheck(), WorldGen.meteor(), Player.MowGrassTile(), WorldGen.OreRunner(), Wiring.PixelBoxPass(), WorldGen.PlaceLiquid(), TETeleportationPylon.PlacementPreviewHook_AfterPlacement(), Player.PlaceThing_Tiles_PlaceIt_AdjustPlants(), Player.PlaceThing_Tiles_PlaceIt_SpinBedsAndBaths(), Player.PlaceThing_Tiles_PlaceIt_SpinChairs(), Player.PlaceThing_Tiles_PlaceIt_SpinTraps(), Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck(), Player.PlaceThing_XMasTreeTops(), Player.PlaceWeapon(), WorldGen.PlantAlch(), WorldGen.PlantSeaOat(), Wiring.ReActive(), Player.RelightTorches(), SendTileSquare(), WorldGen.SpawnFallingBlockProjectile(), WorldGen.SpawnPlanteraThorns(), Projectile.SpawnWebs(), WorldGen.SpreadDesertWalls(), WorldGen.SwitchCannon(), WorldGen.SwitchFountain(), WorldGen.SwitchMB(), WorldGen.SwitchMonolith(), Player.TileInteractionsUse(), Wiring.Toggle2x2Light(), Wiring.ToggleCampFire(), Wiring.ToggleCandle(), Wiring.ToggleChandelier(), Wiring.ToggleFirePlace(), WorldGen.ToggleGemLock(), Wiring.ToggleHangingLantern(), Wiring.ToggleHolidayLight(), Wiring.ToggleLamp(), Wiring.ToggleLampPost(), Wiring.ToggleTorch(), Player.TorchAttack(), Minecart.TryFittingTileOrientation(), WorldGen.TryGrowingAbigailsFlower(), WorldGen.TryGrowingGlowTulip(), Wiring.UpdateMech(), WorldGen.UpdateStalagtiteStyle(), WorldGen.UpdateWorld_GrassGrowth(), WorldGen.UpdateWorld_OvergroundTile(), and WorldGen.UpdateWorld_UndergroundTile().