Terraria: NetMessage.SendNPCHousesAndTravelShop
SendNPCHousesAndTravelShop()
static void NetMessage.SendNPCHousesAndTravelShop (int plr) inline static private
     {
         bool flag = false;
         for (int i = 0; i < 200; i++)
         {
             NPC nPC = Main.npc[i];
             if (!nPC.active)
             {
                 continue;
             }
             bool flag2 = nPC.townNPC && NPC.TypeToDefaultHeadIndex(nPC.type) > 0;
             if (nPC.aiStyle == 7)
             {
                 flag2 = true;
             }
             if (flag2)
             {
                 if (!flag && nPC.type == 368)
                 {
                     flag = true;
                 }
                 byte householdStatus = WorldGen.TownManager.GetHouseholdStatus(nPC);
                 SendData(60, plr, -1, null, i, nPC.homeTileX, nPC.homeTileY, (int)householdStatus);
             }
         }
         if (flag)
         {
             SendTravelShop(plr);
         }
     }
References Entity.active, NPC.aiStyle, TownRoomManager.GetHouseholdStatus(), NPC.homeTileX, NPC.homeTileY, Main.npc, SendData(), SendTravelShop(), WorldGen.TownManager, NPC.townNPC, NPC.type, and NPC.TypeToDefaultHeadIndex().
Referenced by SyncConnectedPlayer().