Terraria: NetMessage.SendData
SendData()
static void NetMessage.SendData (int msgType, int remoteClient = -1, int ignoreClient = -1, NetworkText text = null, int number = 0, float number2 = 0f, float number3 = 0f, float number4 = 0f, int number5 = 0, int number6 = 0, int number7 = 0) inline static
     {
         if (Main.netMode == 0)
         {
             return;
         }
         if (msgType == 21 && (Main.item[number].shimmerTime > 0f || Main.item[number].shimmered))
         {
             msgType = 145;
         }
         int num = 256;
         if (text == null)
         {
             text = NetworkText.Empty;
         }
         if (Main.netMode == 2 && remoteClient >= 0)
         {
             num = remoteClient;
         }
         lock (buffer[num])
         {
             BinaryWriter writer = buffer[num].writer;
             if (writer == null)
             {
                 buffer[num].ResetWriter();
                 writer = buffer[num].writer;
             }
             writer.BaseStream.Position = 0L;
             long position = writer.BaseStream.Position;
             writer.BaseStream.Position += 2L;
             writer.Write((byte)msgType);
             switch (msgType)
             {
             case 1:
                 writer.Write("Terraria" + 279);
                 break;
             case 2:
                 text.Serialize(writer);
                 if (Main.dedServ)
                 {
                     Console.WriteLine(Language.GetTextValue("CLI.ClientWasBooted", Netplay.Clients[num].Socket.GetRemoteAddress().ToString(), text));
                 }
                 break;
             case 3:
                 writer.Write((byte)remoteClient);
                 writer.Write(value: false);
                 break;
             case 4:
             {
                 Player player4 = Main.player[number];
                 writer.Write((byte)number);
                 writer.Write((byte)player4.skinVariant);
                 writer.Write((byte)player4.hair);
                 writer.Write(player4.name);
                 writer.Write(player4.hairDye);
                 WriteAccessoryVisibility(writer, player4.hideVisibleAccessory);
                 writer.Write(player4.hideMisc);
                 writer.WriteRGB(player4.hairColor);
                 writer.WriteRGB(player4.skinColor);
                 writer.WriteRGB(player4.eyeColor);
                 writer.WriteRGB(player4.shirtColor);
                 writer.WriteRGB(player4.underShirtColor);
                 writer.WriteRGB(player4.pantsColor);
                 writer.WriteRGB(player4.shoeColor);
                 BitsByte bitsByte16 = (byte)0;
                 if (player4.difficulty == 1)
                 {
                     bitsByte16[0] = true;
                 }
                 else if (player4.difficulty == 2)
                 {
                     bitsByte16[1] = true;
                 }
                 else if (player4.difficulty == 3)
                 {
                     bitsByte16[3] = true;
                 }
                 bitsByte16[2] = player4.extraAccessory;
                 writer.Write(bitsByte16);
                 BitsByte bitsByte17 = (byte)0;
                 bitsByte17[0] = player4.UsingBiomeTorches;
                 bitsByte17[1] = player4.happyFunTorchTime;
                 bitsByte17[2] = player4.unlockedBiomeTorches;
                 bitsByte17[3] = player4.unlockedSuperCart;
                 bitsByte17[4] = player4.enabledSuperCart;
                 writer.Write(bitsByte17);
                 BitsByte bitsByte18 = (byte)0;
                 bitsByte18[0] = player4.usedAegisCrystal;
                 bitsByte18[1] = player4.usedAegisFruit;
                 bitsByte18[2] = player4.usedArcaneCrystal;
                 bitsByte18[3] = player4.usedGalaxyPearl;
                 bitsByte18[4] = player4.usedGummyWorm;
                 bitsByte18[5] = player4.usedAmbrosia;
                 bitsByte18[6] = player4.ateArtisanBread;
                 writer.Write(bitsByte18);
                 break;
             }
             case 5:
             {
                 writer.Write((byte)number);
                 writer.Write((short)number2);
                 Player player5 = Main.player[number];
                 Item item6 = null;
                 int num11 = 0;
                 int num12 = 0;
                 item6 = ((number2 >= (float)PlayerItemSlotID.Loadout3_Dye_0) ? player5.Loadouts[2].Dye[(int)number2 - PlayerItemSlotID.Loadout3_Dye_0] : ((number2 >= (float)PlayerItemSlotID.Loadout3_Armor_0) ? player5.Loadouts[2].Armor[(int)number2 - PlayerItemSlotID.Loadout3_Armor_0] : ((number2 >= (float)PlayerItemSlotID.Loadout2_Dye_0) ? player5.Loadouts[1].Dye[(int)number2 - PlayerItemSlotID.Loadout2_Dye_0] : ((number2 >= (float)PlayerItemSlotID.Loadout2_Armor_0) ? player5.Loadouts[1].Armor[(int)number2 - PlayerItemSlotID.Loadout2_Armor_0] : ((number2 >= (float)PlayerItemSlotID.Loadout1_Dye_0) ? player5.Loadouts[0].Dye[(int)number2 - PlayerItemSlotID.Loadout1_Dye_0] : ((number2 >= (float)PlayerItemSlotID.Loadout1_Armor_0) ? player5.Loadouts[0].Armor[(int)number2 - PlayerItemSlotID.Loadout1_Armor_0] : ((number2 >= (float)PlayerItemSlotID.Bank4_0) ? player5.bank4.item[(int)number2 - PlayerItemSlotID.Bank4_0] : ((number2 >= (float)PlayerItemSlotID.Bank3_0) ? player5.bank3.item[(int)number2 - PlayerItemSlotID.Bank3_0] : ((number2 >= (float)PlayerItemSlotID.TrashItem) ? player5.trashItem : ((number2 >= (float)PlayerItemSlotID.Bank2_0) ? player5.bank2.item[(int)number2 - PlayerItemSlotID.Bank2_0] : ((number2 >= (float)PlayerItemSlotID.Bank1_0) ? player5.bank.item[(int)number2 - PlayerItemSlotID.Bank1_0] : ((number2 >= (float)PlayerItemSlotID.MiscDye0) ? player5.miscDyes[(int)number2 - PlayerItemSlotID.MiscDye0] : ((number2 >= (float)PlayerItemSlotID.Misc0) ? player5.miscEquips[(int)number2 - PlayerItemSlotID.Misc0] : ((number2 >= (float)PlayerItemSlotID.Dye0) ? player5.dye[(int)number2 - PlayerItemSlotID.Dye0] : ((!(number2 >= (float)PlayerItemSlotID.Armor0)) ? player5.inventory[(int)number2 - PlayerItemSlotID.Inventory0] : player5.armor[(int)number2 - PlayerItemSlotID.Armor0])))))))))))))));
                 if (item6.Name == "" || item6.stack == 0 || item6.type == 0)
                 {
                     item6.SetDefaults(0, noMatCheck: true);
                 }
                 num11 = item6.stack;
                 num12 = item6.netID;
                 if (num11 < 0)
                 {
                     num11 = 0;
                 }
                 writer.Write((short)num11);
                 writer.Write((byte)number3);
                 writer.Write((short)num12);
                 break;
             }
             case 7:
             {
                 writer.Write((int)Main.time);
                 BitsByte bitsByte5 = (byte)0;
                 bitsByte5[0] = Main.dayTime;
                 bitsByte5[1] = Main.bloodMoon;
                 bitsByte5[2] = Main.eclipse;
                 writer.Write(bitsByte5);
                 writer.Write((byte)Main.moonPhase);
                 writer.Write((short)Main.maxTilesX);
                 writer.Write((short)Main.maxTilesY);
                 writer.Write((short)Main.spawnTileX);
                 writer.Write((short)Main.spawnTileY);
                 writer.Write((short)Main.worldSurface);
                 writer.Write((short)Main.rockLayer);
                 writer.Write(Main.worldID);
                 writer.Write(Main.worldName);
                 writer.Write((byte)Main.GameMode);
                 writer.Write(Main.ActiveWorldFileData.UniqueId.ToByteArray());
                 writer.Write(Main.ActiveWorldFileData.WorldGeneratorVersion);
                 writer.Write((byte)Main.moonType);
                 writer.Write((byte)WorldGen.treeBG1);
                 writer.Write((byte)WorldGen.treeBG2);
                 writer.Write((byte)WorldGen.treeBG3);
                 writer.Write((byte)WorldGen.treeBG4);
                 writer.Write((byte)WorldGen.corruptBG);
                 writer.Write((byte)WorldGen.jungleBG);
                 writer.Write((byte)WorldGen.snowBG);
                 writer.Write((byte)WorldGen.hallowBG);
                 writer.Write((byte)WorldGen.crimsonBG);
                 writer.Write((byte)WorldGen.desertBG);
                 writer.Write((byte)WorldGen.oceanBG);
                 writer.Write((byte)WorldGen.mushroomBG);
                 writer.Write((byte)WorldGen.underworldBG);
                 writer.Write((byte)Main.iceBackStyle);
                 writer.Write((byte)Main.jungleBackStyle);
                 writer.Write((byte)Main.hellBackStyle);
                 writer.Write(Main.windSpeedTarget);
                 writer.Write((byte)Main.numClouds);
                 for (int n = 0; n < 3; n++)
                 {
                     writer.Write(Main.treeX[n]);
                 }
                 for (int num8 = 0; num8 < 4; num8++)
                 {
                     writer.Write((byte)Main.treeStyle[num8]);
                 }
                 for (int num9 = 0; num9 < 3; num9++)
                 {
                     writer.Write(Main.caveBackX[num9]);
                 }
                 for (int num10 = 0; num10 < 4; num10++)
                 {
                     writer.Write((byte)Main.caveBackStyle[num10]);
                 }
                 WorldGen.TreeTops.SyncSend(writer);
                 if (!Main.raining)
                 {
                     Main.maxRaining = 0f;
                 }
                 writer.Write(Main.maxRaining);
                 BitsByte bitsByte6 = (byte)0;
                 bitsByte6[0] = WorldGen.shadowOrbSmashed;
                 bitsByte6[1] = NPC.downedBoss1;
                 bitsByte6[2] = NPC.downedBoss2;
                 bitsByte6[3] = NPC.downedBoss3;
                 bitsByte6[4] = Main.hardMode;
                 bitsByte6[5] = NPC.downedClown;
                 bitsByte6[7] = NPC.downedPlantBoss;
                 writer.Write(bitsByte6);
                 BitsByte bitsByte7 = (byte)0;
                 bitsByte7[0] = NPC.downedMechBoss1;
                 bitsByte7[1] = NPC.downedMechBoss2;
                 bitsByte7[2] = NPC.downedMechBoss3;
                 bitsByte7[3] = NPC.downedMechBossAny;
                 bitsByte7[4] = Main.cloudBGActive >= 1f;
                 bitsByte7[5] = WorldGen.crimson;
                 bitsByte7[6] = Main.pumpkinMoon;
                 bitsByte7[7] = Main.snowMoon;
                 writer.Write(bitsByte7);
                 BitsByte bitsByte8 = (byte)0;
                 bitsByte8[1] = Main.fastForwardTimeToDawn;
                 bitsByte8[2] = Main.slimeRain;
                 bitsByte8[3] = NPC.downedSlimeKing;
                 bitsByte8[4] = NPC.downedQueenBee;
                 bitsByte8[5] = NPC.downedFishron;
                 bitsByte8[6] = NPC.downedMartians;
                 bitsByte8[7] = NPC.downedAncientCultist;
                 writer.Write(bitsByte8);
                 BitsByte bitsByte9 = (byte)0;
                 bitsByte9[0] = NPC.downedMoonlord;
                 bitsByte9[1] = NPC.downedHalloweenKing;
                 bitsByte9[2] = NPC.downedHalloweenTree;
                 bitsByte9[3] = NPC.downedChristmasIceQueen;
                 bitsByte9[4] = NPC.downedChristmasSantank;
                 bitsByte9[5] = NPC.downedChristmasTree;
                 bitsByte9[6] = NPC.downedGolemBoss;
                 bitsByte9[7] = BirthdayParty.PartyIsUp;
                 writer.Write(bitsByte9);
                 BitsByte bitsByte10 = (byte)0;
                 bitsByte10[0] = NPC.downedPirates;
                 bitsByte10[1] = NPC.downedFrost;
                 bitsByte10[2] = NPC.downedGoblins;
                 bitsByte10[3] = Sandstorm.Happening;
                 bitsByte10[4] = DD2Event.Ongoing;
                 bitsByte10[5] = DD2Event.DownedInvasionT1;
                 bitsByte10[6] = DD2Event.DownedInvasionT2;
                 bitsByte10[7] = DD2Event.DownedInvasionT3;
                 writer.Write(bitsByte10);
                 BitsByte bitsByte11 = (byte)0;
                 bitsByte11[0] = NPC.combatBookWasUsed;
                 bitsByte11[1] = LanternNight.LanternsUp;
                 bitsByte11[2] = NPC.downedTowerSolar;
                 bitsByte11[3] = NPC.downedTowerVortex;
                 bitsByte11[4] = NPC.downedTowerNebula;
                 bitsByte11[5] = NPC.downedTowerStardust;
                 bitsByte11[6] = Main.forceHalloweenForToday;
                 bitsByte11[7] = Main.forceXMasForToday;
                 writer.Write(bitsByte11);
                 BitsByte bitsByte12 = (byte)0;
                 bitsByte12[0] = NPC.boughtCat;
                 bitsByte12[1] = NPC.boughtDog;
                 bitsByte12[2] = NPC.boughtBunny;
                 bitsByte12[3] = NPC.freeCake;
                 bitsByte12[4] = Main.drunkWorld;
                 bitsByte12[5] = NPC.downedEmpressOfLight;
                 bitsByte12[6] = NPC.downedQueenSlime;
                 bitsByte12[7] = Main.getGoodWorld;
                 writer.Write(bitsByte12);
                 BitsByte bitsByte13 = (byte)0;
                 bitsByte13[0] = Main.tenthAnniversaryWorld;
                 bitsByte13[1] = Main.dontStarveWorld;
                 bitsByte13[2] = NPC.downedDeerclops;
                 bitsByte13[3] = Main.notTheBeesWorld;
                 bitsByte13[4] = Main.remixWorld;
                 bitsByte13[5] = NPC.unlockedSlimeBlueSpawn;
                 bitsByte13[6] = NPC.combatBookVolumeTwoWasUsed;
                 bitsByte13[7] = NPC.peddlersSatchelWasUsed;
                 writer.Write(bitsByte13);
                 BitsByte bitsByte14 = (byte)0;
                 bitsByte14[0] = NPC.unlockedSlimeGreenSpawn;
                 bitsByte14[1] = NPC.unlockedSlimeOldSpawn;
                 bitsByte14[2] = NPC.unlockedSlimePurpleSpawn;
                 bitsByte14[3] = NPC.unlockedSlimeRainbowSpawn;
                 bitsByte14[4] = NPC.unlockedSlimeRedSpawn;
                 bitsByte14[5] = NPC.unlockedSlimeYellowSpawn;
                 bitsByte14[6] = NPC.unlockedSlimeCopperSpawn;
                 bitsByte14[7] = Main.fastForwardTimeToDusk;
                 writer.Write(bitsByte14);
                 BitsByte bitsByte15 = (byte)0;
                 bitsByte15[0] = Main.noTrapsWorld;
                 bitsByte15[1] = Main.zenithWorld;
                 bitsByte15[2] = NPC.unlockedTruffleSpawn;
                 writer.Write(bitsByte15);
                 writer.Write((byte)Main.sundialCooldown);
                 writer.Write((byte)Main.moondialCooldown);
                 writer.Write((short)WorldGen.SavedOreTiers.Copper);
                 writer.Write((short)WorldGen.SavedOreTiers.Iron);
                 writer.Write((short)WorldGen.SavedOreTiers.Silver);
                 writer.Write((short)WorldGen.SavedOreTiers.Gold);
                 writer.Write((short)WorldGen.SavedOreTiers.Cobalt);
                 writer.Write((short)WorldGen.SavedOreTiers.Mythril);
                 writer.Write((short)WorldGen.SavedOreTiers.Adamantite);
                 writer.Write((sbyte)Main.invasionType);
                 if (SocialAPI.Network != null)
                 {
                     writer.Write(SocialAPI.Network.GetLobbyId());
                 }
                 else
                 {
                     writer.Write(0uL);
                 }
                 writer.Write(Sandstorm.IntendedSeverity);
                 break;
             }
             case 8:
                 writer.Write(number);
                 writer.Write((int)number2);
                 break;
             case 9:
             {
                 writer.Write(number);
                 text.Serialize(writer);
                 BitsByte bitsByte22 = (byte)number2;
                 writer.Write(bitsByte22);
                 break;
             }
             case 10:
                 CompressTileBlock(number, (int)number2, (short)number3, (short)number4, writer.BaseStream);
                 break;
             case 11:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 writer.Write((short)number3);
                 writer.Write((short)number4);
                 break;
             case 12:
             {
                 Player player6 = Main.player[number];
                 writer.Write((byte)number);
                 writer.Write((short)player6.SpawnX);
                 writer.Write((short)player6.SpawnY);
                 writer.Write(player6.respawnTimer);
                 writer.Write((short)player6.numberOfDeathsPVE);
                 writer.Write((short)player6.numberOfDeathsPVP);
                 writer.Write((byte)number2);
                 break;
             }
             case 13:
             {
                 Player player7 = Main.player[number];
                 writer.Write((byte)number);
                 BitsByte bitsByte25 = (byte)0;
                 bitsByte25[0] = player7.controlUp;
                 bitsByte25[1] = player7.controlDown;
                 bitsByte25[2] = player7.controlLeft;
                 bitsByte25[3] = player7.controlRight;
                 bitsByte25[4] = player7.controlJump;
                 bitsByte25[5] = player7.controlUseItem;
                 bitsByte25[6] = player7.direction == 1;
                 writer.Write(bitsByte25);
                 BitsByte bitsByte26 = (byte)0;
                 bitsByte26[0] = player7.pulley;
                 bitsByte26[1] = player7.pulley && player7.pulleyDir == 2;
                 bitsByte26[2] = player7.velocity != Vector2.Zero;
                 bitsByte26[3] = player7.vortexStealthActive;
                 bitsByte26[4] = player7.gravDir == 1f;
                 bitsByte26[5] = player7.shieldRaised;
                 bitsByte26[6] = player7.ghost;
                 writer.Write(bitsByte26);
                 BitsByte bitsByte27 = (byte)0;
                 bitsByte27[0] = player7.tryKeepingHoveringUp;
                 bitsByte27[1] = player7.IsVoidVaultEnabled;
                 bitsByte27[2] = player7.sitting.isSitting;
                 bitsByte27[3] = player7.downedDD2EventAnyDifficulty;
                 bitsByte27[4] = player7.isPettingAnimal;
                 bitsByte27[5] = player7.isTheAnimalBeingPetSmall;
                 bitsByte27[6] = player7.PotionOfReturnOriginalUsePosition.HasValue;
                 bitsByte27[7] = player7.tryKeepingHoveringDown;
                 writer.Write(bitsByte27);
                 BitsByte bitsByte28 = (byte)0;
                 bitsByte28[0] = player7.sleeping.isSleeping;
                 bitsByte28[1] = player7.autoReuseAllWeapons;
                 bitsByte28[2] = player7.controlDownHold;
                 bitsByte28[3] = player7.isOperatingAnotherEntity;
                 bitsByte28[4] = player7.controlUseTile;
                 writer.Write(bitsByte28);
                 writer.Write((byte)player7.selectedItem);
                 writer.WriteVector2(player7.position);
                 if (bitsByte26[2])
                 {
                     writer.WriteVector2(player7.velocity);
                 }
                 if (bitsByte27[6])
                 {
                     writer.WriteVector2(player7.PotionOfReturnOriginalUsePosition.Value);
                     writer.WriteVector2(player7.PotionOfReturnHomePosition.Value);
                 }
                 break;
             }
             case 14:
                 writer.Write((byte)number);
                 writer.Write((byte)number2);
                 break;
             case 16:
                 writer.Write((byte)number);
                 writer.Write((short)Main.player[number].statLife);
                 writer.Write((short)Main.player[number].statLifeMax);
                 break;
             case 17:
                 writer.Write((byte)number);
                 writer.Write((short)number2);
                 writer.Write((short)number3);
                 writer.Write((short)number4);
                 writer.Write((byte)number5);
                 break;
             case 18:
                 writer.Write((byte)(Main.dayTime ? 1u : 0u));
                 writer.Write((int)Main.time);
                 writer.Write(Main.sunModY);
                 writer.Write(Main.moonModY);
                 break;
             case 19:
                 writer.Write((byte)number);
                 writer.Write((short)number2);
                 writer.Write((short)number3);
                 writer.Write((number4 == 1f) ? ((byte)1) : ((byte)0));
                 break;
             case 20:
             {
                 int num13 = number;
                 int num14 = (int)number2;
                 int num15 = (int)number3;
                 if (num15 < 0)
                 {
                     num15 = 0;
                 }
                 int num16 = (int)number4;
                 if (num16 < 0)
                 {
                     num16 = 0;
                 }
                 if (num13 < num15)
                 {
                     num13 = num15;
                 }
                 if (num13 >= Main.maxTilesX + num15)
                 {
                     num13 = Main.maxTilesX - num15 - 1;
                 }
                 if (num14 < num16)
                 {
                     num14 = num16;
                 }
                 if (num14 >= Main.maxTilesY + num16)
                 {
                     num14 = Main.maxTilesY - num16 - 1;
                 }
                 writer.Write((short)num13);
                 writer.Write((short)num14);
                 writer.Write((byte)num15);
                 writer.Write((byte)num16);
                 writer.Write((byte)number5);
                 for (int num17 = num13; num17 < num13 + num15; num17++)
                 {
                     for (int num18 = num14; num18 < num14 + num16; num18++)
                     {
                         BitsByte bitsByte19 = (byte)0;
                         BitsByte bitsByte20 = (byte)0;
                         BitsByte bitsByte21 = (byte)0;
                         byte b3 = 0;
                         byte b4 = 0;
                         Tile tile2 = Main.tile[num17, num18];
                         bitsByte19[0] = tile2.active();
                         bitsByte19[2] = tile2.wall > 0;
                         bitsByte19[3] = tile2.liquid > 0 && Main.netMode == 2;
                         bitsByte19[4] = tile2.wire();
                         bitsByte19[5] = tile2.halfBrick();
                         bitsByte19[6] = tile2.actuator();
                         bitsByte19[7] = tile2.inActive();
                         bitsByte20[0] = tile2.wire2();
                         bitsByte20[1] = tile2.wire3();
                         if (tile2.active() && tile2.color() > 0)
{
                             bitsByte20[2] = true;
                             b3 = tile2.color();
                         }
                         if (tile2.wall > 0 && tile2.wallColor() > 0)
{
                             bitsByte20[3] = true;
                             b4 = tile2.wallColor();
                         }
                         bitsByte20 = (byte)((byte)bitsByte20 + (byte)(tile2.slope() << 4));
                         bitsByte20[7] = tile2.wire4();
                         bitsByte21[0] = tile2.fullbrightBlock();
                         bitsByte21[1] = tile2.fullbrightWall();
                         bitsByte21[2] = tile2.invisibleBlock();
                         bitsByte21[3] = tile2.invisibleWall();
                         writer.Write(bitsByte19);
                         writer.Write(bitsByte20);
                         writer.Write(bitsByte21);
                         if (b3 > 0)
{
                             writer.Write(b3);
                         }
                         if (b4 > 0)
{
                             writer.Write(b4);
                         }
                         if (tile2.active())
{
                             writer.Write(tile2.type);
                             if (Main.tileFrameImportant[tile2.type])
{
                                 writer.Write(tile2.frameX);
                                 writer.Write(tile2.frameY);
                             }
                         }
                         if (tile2.wall > 0)
{
                             writer.Write(tile2.wall);
                         }
                         if (tile2.liquid > 0 && Main.netMode == 2)
{
                             writer.Write(tile2.liquid);
                             writer.Write(tile2.liquidType());
                         }
                     }
                 }
                 break;
             }
             case 21:
             case 90:
             case 145:
             case 148:
             {
                 Item item3 = Main.item[number];
                 writer.Write((short)number);
                 writer.WriteVector2(item3.position);
                 writer.WriteVector2(item3.velocity);
                 writer.Write((short)item3.stack);
                 writer.Write(item3.prefix);
                 writer.Write((byte)number2);
                 short value2 = 0;
                 if (item3.active && item3.stack > 0)
                 {
                     value2 = (short)item3.netID;
                 }
                 writer.Write(value2);
                 if (msgType == 145)
                 {
                     writer.Write(item3.shimmered);
                     writer.Write(item3.shimmerTime);
                 }
                 if (msgType == 148)
                 {
                     writer.Write((byte)MathHelper.Clamp(item3.timeLeftInWhichTheItemCannotBeTakenByEnemies, 0f, 255f));
                 }
                 break;
             }
             case 22:
                 writer.Write((short)number);
                 writer.Write((byte)Main.item[number].playerIndexTheItemIsReservedFor);
                 break;
             case 23:
             {
                 NPC nPC2 = Main.npc[number];
                 writer.Write((short)number);
                 writer.WriteVector2(nPC2.position);
                 writer.WriteVector2(nPC2.velocity);
                 writer.Write((ushort)nPC2.target);
                 int num4 = nPC2.life;
                 if (!nPC2.active)
                 {
                     num4 = 0;
                 }
                 if (!nPC2.active || nPC2.life <= 0)
                 {
                     nPC2.netSkip = 0;
                 }
                 short value3 = (short)nPC2.netID;
                 bool[] array = new bool[4];
                 BitsByte bitsByte3 = (byte)0;
                 bitsByte3[0] = nPC2.direction > 0;
                 bitsByte3[1] = nPC2.directionY > 0;
                 bitsByte3[2] = (array[0] = nPC2.ai[0] != 0f);
                 bitsByte3[3] = (array[1] = nPC2.ai[1] != 0f);
                 bitsByte3[4] = (array[2] = nPC2.ai[2] != 0f);
                 bitsByte3[5] = (array[3] = nPC2.ai[3] != 0f);
                 bitsByte3[6] = nPC2.spriteDirection > 0;
                 bitsByte3[7] = num4 == nPC2.lifeMax;
                 writer.Write(bitsByte3);
                 BitsByte bitsByte4 = (byte)0;
                 bitsByte4[0] = nPC2.statsAreScaledForThisManyPlayers > 1;
                 bitsByte4[1] = nPC2.SpawnedFromStatue;
                 bitsByte4[2] = nPC2.strengthMultiplier != 1f;
                 writer.Write(bitsByte4);
                 for (int m = 0; m < NPC.maxAI; m++)
                 {
                     if (array[m])
                     {
                         writer.Write(nPC2.ai[m]);
                     }
                 }
                 writer.Write(value3);
                 if (bitsByte4[0])
                 {
                     writer.Write((byte)nPC2.statsAreScaledForThisManyPlayers);
                 }
                 if (bitsByte4[2])
                 {
                     writer.Write(nPC2.strengthMultiplier);
                 }
                 if (!bitsByte3[7])
                 {
                     byte b2 = 1;
                     if (nPC2.lifeMax > 32767)
                     {
                         b2 = 4;
                     }
                     else if (nPC2.lifeMax > 127)
                     {
                         b2 = 2;
                     }
                     writer.Write(b2);
                     switch (b2)
                     {
                     case 2:
                         writer.Write((short)num4);
                         break;
                     case 4:
                         writer.Write(num4);
                         break;
                     default:
                         writer.Write((sbyte)num4);
                         break;
                     }
                 }
                 if (nPC2.type >= 0 && nPC2.type < NPCID.Count && Main.npcCatchable[nPC2.type])
                 {
                     writer.Write((byte)nPC2.releaseOwner);
                 }
                 break;
             }
             case 24:
                 writer.Write((short)number);
                 writer.Write((byte)number2);
                 break;
             case 107:
                 writer.Write((byte)number2);
                 writer.Write((byte)number3);
                 writer.Write((byte)number4);
                 text.Serialize(writer);
                 writer.Write((short)number5);
                 break;
             case 27:
             {
                 Projectile projectile = Main.projectile[number];
                 writer.Write((short)projectile.identity);
                 writer.WriteVector2(projectile.position);
                 writer.WriteVector2(projectile.velocity);
                 writer.Write((byte)projectile.owner);
                 writer.Write((short)projectile.type);
                 BitsByte bitsByte23 = (byte)0;
                 BitsByte bitsByte24 = (byte)0;
                 bitsByte23[0] = projectile.ai[0] != 0f;
                 bitsByte23[1] = projectile.ai[1] != 0f;
                 bitsByte24[0] = projectile.ai[2] != 0f;
                 if (projectile.bannerIdToRespondTo != 0)
                 {
                     bitsByte23[3] = true;
                 }
                 if (projectile.damage != 0)
                 {
                     bitsByte23[4] = true;
                 }
                 if (projectile.knockBack != 0f)
                 {
                     bitsByte23[5] = true;
                 }
                 if (projectile.type > 0 && projectile.type < ProjectileID.Count && ProjectileID.Sets.NeedsUUID[projectile.type])
                 {
                     bitsByte23[7] = true;
                 }
                 if (projectile.originalDamage != 0)
                 {
                     bitsByte23[6] = true;
                 }
                 if ((byte)bitsByte24 != 0)
                 {
                     bitsByte23[2] = true;
                 }
                 writer.Write(bitsByte23);
                 if (bitsByte23[2])
                 {
                     writer.Write(bitsByte24);
                 }
                 if (bitsByte23[0])
                 {
                     writer.Write(projectile.ai[0]);
                 }
                 if (bitsByte23[1])
                 {
                     writer.Write(projectile.ai[1]);
                 }
                 if (bitsByte23[3])
                 {
                     writer.Write((ushort)projectile.bannerIdToRespondTo);
                 }
                 if (bitsByte23[4])
                 {
                     writer.Write((short)projectile.damage);
                 }
                 if (bitsByte23[5])
                 {
                     writer.Write(projectile.knockBack);
                 }
                 if (bitsByte23[6])
                 {
                     writer.Write((short)projectile.originalDamage);
                 }
                 if (bitsByte23[7])
                 {
                     writer.Write((short)projectile.projUUID);
                 }
                 if (bitsByte24[0])
                 {
                     writer.Write(projectile.ai[2]);
                 }
                 break;
             }
             case 28:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 writer.Write(number3);
                 writer.Write((byte)(number4 + 1f));
                 writer.Write((byte)number5);
                 break;
             case 29:
                 writer.Write((short)number);
                 writer.Write((byte)number2);
                 break;
             case 30:
                 writer.Write((byte)number);
                 writer.Write(Main.player[number].hostile);
                 break;
             case 31:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 break;
             case 32:
             {
                 Item item7 = Main.chest[number].item[(byte)number2];
                 writer.Write((short)number);
                 writer.Write((byte)number2);
                 short value4 = (short)item7.netID;
                 if (item7.Name == null)
                 {
                     value4 = 0;
                 }
                 writer.Write((short)item7.stack);
                 writer.Write(item7.prefix);
                 writer.Write(value4);
                 break;
             }
             case 33:
             {
                 int num5 = 0;
                 int num6 = 0;
                 int num7 = 0;
                 string text2 = null;
                 if (number > -1)
                 {
                     num5 = Main.chest[number].x;
                     num6 = Main.chest[number].y;
                 }
                 if (number2 == 1f)
                 {
                     string text3 = text.ToString();
                     num7 = (byte)text3.Length;
                     if (num7 == 0 || num7 > 20)
                     {
                         num7 = 255;
                     }
                     else
                     {
                         text2 = text3;
                     }
                 }
                 writer.Write((short)number);
                 writer.Write((short)num5);
                 writer.Write((short)num6);
                 writer.Write((byte)num7);
                 if (text2 != null)
                 {
                     writer.Write(text2);
                 }
                 break;
             }
             case 34:
                 writer.Write((byte)number);
                 writer.Write((short)number2);
                 writer.Write((short)number3);
                 writer.Write((short)number4);
                 if (Main.netMode == 2)
                 {
                     Netplay.GetSectionX((int)number2);
                     Netplay.GetSectionY((int)number3);
                     writer.Write((short)number5);
                 }
                 else
                 {
                     writer.Write((short)0);
                 }
                 break;
             case 35:
                 writer.Write((byte)number);
                 writer.Write((short)number2);
                 break;
             case 36:
             {
                 Player player3 = Main.player[number];
                 writer.Write((byte)number);
                 writer.Write(player3.zone1);
                 writer.Write(player3.zone2);
                 writer.Write(player3.zone3);
                 writer.Write(player3.zone4);
                 writer.Write(player3.zone5);
                 break;
             }
             case 38:
                 writer.Write(Netplay.ServerPassword);
                 break;
             case 39:
                 writer.Write((short)number);
                 break;
             case 40:
                 writer.Write((byte)number);
                 writer.Write((short)Main.player[number].talkNPC);
                 break;
             case 41:
                 writer.Write((byte)number);
                 writer.Write(Main.player[number].itemRotation);
                 writer.Write((short)Main.player[number].itemAnimation);
                 break;
             case 42:
                 writer.Write((byte)number);
                 writer.Write((short)Main.player[number].statMana);
                 writer.Write((short)Main.player[number].statManaMax);
                 break;
             case 43:
                 writer.Write((byte)number);
                 writer.Write((short)number2);
                 break;
             case 45:
                 writer.Write((byte)number);
                 writer.Write((byte)Main.player[number].team);
                 break;
             case 46:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 break;
             case 47:
                 writer.Write((short)number);
                 writer.Write((short)Main.sign[number].x);
                 writer.Write((short)Main.sign[number].y);
                 writer.Write(Main.sign[number].text);
                 writer.Write((byte)number2);
                 writer.Write((byte)number3);
                 break;
             case 48:
             {
                 Tile tile = Main.tile[number, (int)number2];
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 writer.Write(tile.liquid);
                 writer.Write(tile.liquidType());
                 break;
             }
             case 50:
             {
                 writer.Write((byte)number);
                 for (int l = 0; l < Player.maxBuffs; l++)
                 {
                     writer.Write((ushort)Main.player[number].buffType[l]);
                 }
                 break;
             }
             case 51:
                 writer.Write((byte)number);
                 writer.Write((byte)number2);
                 break;
             case 52:
                 writer.Write((byte)number2);
                 writer.Write((short)number3);
                 writer.Write((short)number4);
                 break;
             case 53:
                 writer.Write((short)number);
                 writer.Write((ushort)number2);
                 writer.Write((short)number3);
                 break;
             case 54:
             {
                 writer.Write((short)number);
                 for (int k = 0; k < NPC.maxBuffs; k++)
                 {
                     writer.Write((ushort)Main.npc[number].buffType[k]);
                     writer.Write((short)Main.npc[number].buffTime[k]);
                 }
                 break;
             }
             case 55:
                 writer.Write((byte)number);
                 writer.Write((ushort)number2);
                 writer.Write((int)number3);
                 break;
             case 56:
                 writer.Write((short)number);
                 if (Main.netMode == 2)
                 {
                     string givenName = Main.npc[number].GivenName;
                     writer.Write(givenName);
                     writer.Write(Main.npc[number].townNpcVariationIndex);
                 }
                 break;
             case 57:
                 writer.Write(WorldGen.tGood);
                 writer.Write(WorldGen.tEvil);
                 writer.Write(WorldGen.tBlood);
                 break;
             case 58:
                 writer.Write((byte)number);
                 writer.Write(number2);
                 break;
             case 59:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 break;
             case 60:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 writer.Write((short)number3);
                 writer.Write((byte)number4);
                 break;
             case 61:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 break;
             case 62:
                 writer.Write((byte)number);
                 writer.Write((byte)number2);
                 break;
             case 63:
             case 64:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 writer.Write((byte)number3);
                 writer.Write((byte)number4);
                 break;
             case 65:
             {
                 BitsByte bitsByte29 = (byte)0;
                 bitsByte29[0] = (number & 1) == 1;
                 bitsByte29[1] = (number & 2) == 2;
                 bitsByte29[2] = number6 == 1;
                 bitsByte29[3] = number7 != 0;
                 writer.Write(bitsByte29);
                 writer.Write((short)number2);
                 writer.Write(number3);
                 writer.Write(number4);
                 writer.Write((byte)number5);
                 if (bitsByte29[3])
                 {
                     writer.Write(number7);
                 }
                 break;
             }
             case 66:
                 writer.Write((byte)number);
                 writer.Write((short)number2);
                 break;
             case 68:
                 writer.Write(Main.clientUUID);
                 break;
             case 69:
                 Netplay.GetSectionX((int)number2);
                 Netplay.GetSectionY((int)number3);
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 writer.Write((short)number3);
                 writer.Write(Main.chest[(short)number].name);
                 break;
             case 70:
                 writer.Write((short)number);
                 writer.Write((byte)number2);
                 break;
             case 71:
                 writer.Write(number);
                 writer.Write((int)number2);
                 writer.Write((short)number3);
                 writer.Write((byte)number4);
                 break;
             case 72:
             {
                 for (int num20 = 0; num20 < 40; num20++)
                 {
                     writer.Write((short)Main.travelShop[num20]);
                 }
                 break;
             }
             case 73:
                 writer.Write((byte)number);
                 break;
             case 74:
             {
                 writer.Write((byte)Main.anglerQuest);
                 bool value7 = Main.anglerWhoFinishedToday.Contains(text.ToString());
                 writer.Write(value7);
                 break;
             }
             case 76:
                 writer.Write((byte)number);
                 writer.Write(Main.player[number].anglerQuestsFinished);
                 writer.Write(Main.player[number].golferScoreAccumulated);
                 break;
             case 77:
                 writer.Write((short)number);
                 writer.Write((ushort)number2);
                 writer.Write((short)number3);
                 writer.Write((short)number4);
                 break;
             case 78:
                 writer.Write(number);
                 writer.Write((int)number2);
                 writer.Write((sbyte)number3);
                 writer.Write((sbyte)number4);
                 break;
             case 79:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 writer.Write((short)number3);
                 writer.Write((short)number4);
                 writer.Write((byte)number5);
                 writer.Write((sbyte)number6);
                 writer.Write(number7 == 1);
                 break;
             case 80:
                 writer.Write((byte)number);
                 writer.Write((short)number2);
                 break;
             case 81:
             {
                 writer.Write(number2);
                 writer.Write(number3);
                 Color c2 = default(Color);
                 c2.PackedValue = (uint)number;
                 writer.WriteRGB(c2);
                 writer.Write((int)number4);
                 break;
             }
             case 119:
             {
                 writer.Write(number2);
                 writer.Write(number3);
                 Color c = default(Color);
                 c.PackedValue = (uint)number;
                 writer.WriteRGB(c);
                 text.Serialize(writer);
                 break;
             }
             case 83:
             {
                 int num19 = number;
                 if (num19 < 0 && num19 >= 290)
                 {
                     num19 = 1;
                 }
                 int value6 = NPC.killCount[num19];
                 writer.Write((short)num19);
                 writer.Write(value6);
                 break;
             }
             case 84:
             {
                 byte b5 = (byte)number;
                 float stealth = Main.player[b5].stealth;
                 writer.Write(b5);
                 writer.Write(stealth);
                 break;
             }
             case 85:
             {
                 short value5 = (short)number;
                 writer.Write(value5);
                 break;
             }
             case 86:
             {
                 writer.Write(number);
                 bool flag3 = TileEntity.ByID.ContainsKey(number);
                 writer.Write(flag3);
                 if (flag3)
                 {
                     TileEntity.Write(writer, TileEntity.ByID[number], networkSend: true);
                 }
                 break;
             }
             case 87:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 writer.Write((byte)number3);
                 break;
             case 88:
             {
                 BitsByte bitsByte = (byte)number2;
                 BitsByte bitsByte2 = (byte)number3;
                 writer.Write((short)number);
                 writer.Write(bitsByte);
                 Item item5 = Main.item[number];
                 if (bitsByte[0])
                 {
                     writer.Write(item5.color.PackedValue);
                 }
                 if (bitsByte[1])
                 {
                     writer.Write((ushort)item5.damage);
                 }
                 if (bitsByte[2])
                 {
                     writer.Write(item5.knockBack);
                 }
                 if (bitsByte[3])
                 {
                     writer.Write((ushort)item5.useAnimation);
                 }
                 if (bitsByte[4])
                 {
                     writer.Write((ushort)item5.useTime);
                 }
                 if (bitsByte[5])
                 {
                     writer.Write((short)item5.shoot);
                 }
                 if (bitsByte[6])
                 {
                     writer.Write(item5.shootSpeed);
                 }
                 if (bitsByte[7])
                 {
                     writer.Write(bitsByte2);
                     if (bitsByte2[0])
                     {
                         writer.Write((ushort)item5.width);
                     }
                     if (bitsByte2[1])
                     {
                         writer.Write((ushort)item5.height);
                     }
                     if (bitsByte2[2])
                     {
                         writer.Write(item5.scale);
                     }
                     if (bitsByte2[3])
                     {
                         writer.Write((short)item5.ammo);
                     }
                     if (bitsByte2[4])
                     {
                         writer.Write((short)item5.useAmmo);
                     }
                     if (bitsByte2[5])
                     {
                         writer.Write(item5.notAmmo);
                     }
                 }
                 break;
             }
             case 89:
             {
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 Item item4 = Main.player[(int)number4].inventory[(int)number3];
                 writer.Write((short)item4.netID);
                 writer.Write(item4.prefix);
                 writer.Write((short)number5);
                 break;
             }
             case 91:
                 writer.Write(number);
                 writer.Write((byte)number2);
                 if (number2 != 255f)
                 {
                     writer.Write((ushort)number3);
                     writer.Write((ushort)number4);
                     writer.Write((byte)number5);
                     if (number5 < 0)
                     {
                         writer.Write((short)number6);
                     }
                 }
                 break;
             case 92:
                 writer.Write((short)number);
                 writer.Write((int)number2);
                 writer.Write(number3);
                 writer.Write(number4);
                 break;
             case 95:
                 writer.Write((ushort)number);
                 writer.Write((byte)number2);
                 break;
             case 96:
             {
                 writer.Write((byte)number);
                 Player player2 = Main.player[number];
                 writer.Write((short)number4);
                 writer.Write(number2);
                 writer.Write(number3);
                 writer.WriteVector2(player2.velocity);
                 break;
             }
             case 97:
                 writer.Write((short)number);
                 break;
             case 98:
                 writer.Write((short)number);
                 break;
             case 99:
                 writer.Write((byte)number);
                 writer.WriteVector2(Main.player[number].MinionRestTargetPoint);
                 break;
             case 115:
                 writer.Write((byte)number);
                 writer.Write((short)Main.player[number].MinionAttackTargetNPC);
                 break;
             case 100:
             {
                 writer.Write((ushort)number);
                 NPC nPC = Main.npc[number];
                 writer.Write((short)number4);
                 writer.Write(number2);
                 writer.Write(number3);
                 writer.WriteVector2(nPC.velocity);
                 break;
             }
             case 101:
                 writer.Write((ushort)NPC.ShieldStrengthTowerSolar);
                 writer.Write((ushort)NPC.ShieldStrengthTowerVortex);
                 writer.Write((ushort)NPC.ShieldStrengthTowerNebula);
                 writer.Write((ushort)NPC.ShieldStrengthTowerStardust);
                 break;
             case 102:
                 writer.Write((byte)number);
                 writer.Write((ushort)number2);
                 writer.Write(number3);
                 writer.Write(number4);
                 break;
             case 103:
                 writer.Write(NPC.MaxMoonLordCountdown);
                 writer.Write(NPC.MoonLordCountdown);
                 break;
             case 104:
                 writer.Write((byte)number);
                 writer.Write((short)number2);
                 writer.Write(((short)number3 < 0) ? 0f : number3);
                 writer.Write((byte)number4);
                 writer.Write(number5);
                 writer.Write((byte)number6);
                 break;
             case 105:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 writer.Write(number3 == 1f);
                 break;
             case 106:
                 writer.Write(new HalfVector2(number, number2).PackedValue);
                 break;
             case 108:
                 writer.Write((short)number);
                 writer.Write(number2);
                 writer.Write((short)number3);
                 writer.Write((short)number4);
                 writer.Write((short)number5);
                 writer.Write((short)number6);
                 writer.Write((byte)number7);
                 break;
             case 109:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 writer.Write((short)number3);
                 writer.Write((short)number4);
                 writer.Write((byte)number5);
                 break;
             case 110:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 writer.Write((byte)number3);
                 break;
             case 112:
                 writer.Write((byte)number);
                 writer.Write((int)number2);
                 writer.Write((int)number3);
                 writer.Write((byte)number4);
                 writer.Write((short)number5);
                 break;
             case 113:
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 break;
             case 116:
                 writer.Write(number);
                 break;
             case 117:
                 writer.Write((byte)number);
                 _currentPlayerDeathReason.WriteSelfTo(writer);
                 writer.Write((short)number2);
                 writer.Write((byte)(number3 + 1f));
                 writer.Write((byte)number4);
                 writer.Write((sbyte)number5);
                 break;
             case 118:
                 writer.Write((byte)number);
                 _currentPlayerDeathReason.WriteSelfTo(writer);
                 writer.Write((short)number2);
                 writer.Write((byte)(number3 + 1f));
                 writer.Write((byte)number4);
                 break;
             case 120:
                 writer.Write((byte)number);
                 writer.Write((byte)number2);
                 break;
             case 121:
             {
                 int num3 = (int)number3;
                 bool flag2 = number4 == 1f;
                 if (flag2)
                 {
                     num3 += 8;
                 }
                 writer.Write((byte)number);
                 writer.Write((int)number2);
                 writer.Write((byte)num3);
                 if (TileEntity.ByID[(int)number2] is TEDisplayDoll tEDisplayDoll)
                 {
                     tEDisplayDoll.WriteItem((int)number3, writer, flag2);
                     break;
                 }
                 writer.Write(0);
                 writer.Write((byte)0);
                 break;
             }
             case 122:
                 writer.Write(number);
                 writer.Write((byte)number2);
                 break;
             case 123:
             {
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 Item item2 = Main.player[(int)number4].inventory[(int)number3];
                 writer.Write((short)item2.netID);
                 writer.Write(item2.prefix);
                 writer.Write((short)number5);
                 break;
             }
             case 124:
             {
                 int num2 = (int)number3;
                 bool flag = number4 == 1f;
                 if (flag)
                 {
                     num2 += 2;
                 }
                 writer.Write((byte)number);
                 writer.Write((int)number2);
                 writer.Write((byte)num2);
                 if (TileEntity.ByID[(int)number2] is TEHatRack tEHatRack)
                 {
                     tEHatRack.WriteItem((int)number3, writer, flag);
                     break;
                 }
                 writer.Write(0);
                 writer.Write((byte)0);
                 break;
             }
             case 125:
                 writer.Write((byte)number);
                 writer.Write((short)number2);
                 writer.Write((short)number3);
                 writer.Write((byte)number4);
                 break;
             case 126:
                 _currentRevengeMarker.WriteSelfTo(writer);
                 break;
             case 127:
                 writer.Write(number);
                 break;
             case 128:
                 writer.Write((byte)number);
                 writer.Write((ushort)number5);
                 writer.Write((ushort)number6);
                 writer.Write((ushort)number2);
                 writer.Write((ushort)number3);
                 break;
             case 130:
                 writer.Write((ushort)number);
                 writer.Write((ushort)number2);
                 writer.Write((short)number3);
                 break;
             case 131:
             {
                 writer.Write((ushort)number);
                 writer.Write((byte)number2);
                 byte b = (byte)number2;
                 if (b == 1)
                 {
                     writer.Write((int)number3);
                     writer.Write((short)number4);
                 }
                 break;
             }
             case 132:
                 _currentNetSoundInfo.WriteSelfTo(writer);
                 break;
             case 133:
             {
                 writer.Write((short)number);
                 writer.Write((short)number2);
                 Item item = Main.player[(int)number4].inventory[(int)number3];
                 writer.Write((short)item.netID);
                 writer.Write(item.prefix);
                 writer.Write((short)number5);
                 break;
             }
             case 134:
             {
                 writer.Write((byte)number);
                 Player player = Main.player[number];
                 writer.Write(player.ladyBugLuckTimeLeft);
                 writer.Write(player.torchLuck);
                 writer.Write(player.luckPotion);
                 writer.Write(player.HasGardenGnomeNearby);
                 writer.Write(player.equipmentBasedLuckBonus);
                 writer.Write(player.coinLuck);
                 break;
             }
             case 135:
                 writer.Write((byte)number);
                 break;
             case 136:
             {
                 for (int i = 0; i < 2; i++)
                 {
                     for (int j = 0; j < 3; j++)
                     {
                         writer.Write((ushort)NPC.cavernMonsterType[i, j]);
                     }
                 }
                 break;
             }
             case 137:
                 writer.Write((short)number);
                 writer.Write((ushort)number2);
                 break;
             case 139:
             {
                 writer.Write((byte)number);
                 bool value = number2 == 1f;
                 writer.Write(value);
                 break;
             }
             case 140:
                 writer.Write((byte)number);
                 writer.Write((int)number2);
                 break;
             case 141:
                 writer.Write((byte)number);
                 writer.Write((byte)number2);
                 writer.Write(number3);
                 writer.Write(number4);
                 writer.Write(number5);
                 writer.Write(number6);
                 break;
             case 142:
             {
                 writer.Write((byte)number);
                 Player obj = Main.player[number];
                 obj.piggyBankProjTracker.Write(writer);
                 obj.voidLensChest.Write(writer);
                 break;
             }
             case 146:
                 writer.Write((byte)number);
                 switch (number)
                 {
                 case 0:
                     writer.WriteVector2(new Vector2((int)number2, (int)number3));
                     break;
                 case 1:
                     writer.WriteVector2(new Vector2((int)number2, (int)number3));
                     writer.Write((int)number4);
                     break;
                 case 2:
                     writer.Write((int)number2);
                     break;
                 }
                 break;
             case 147:
                 writer.Write((byte)number);
                 writer.Write((byte)number2);
                 WriteAccessoryVisibility(writer, Main.player[number].hideVisibleAccessory);
                 break;
             }
             int num21 = (int)writer.BaseStream.Position;
             if (num21 > 65535)
             {
                 throw new Exception("Maximum packet length exceeded. id: " + msgType + " length: " + num21);
             }
             writer.BaseStream.Position = position;
             writer.Write((ushort)num21);
             writer.BaseStream.Position = num21;
             if (Main.netMode == 1)
             {
                 if (Netplay.Connection.Socket.IsConnected())
                 {
                     try
                     {
                         buffer[num].spamCount++;
                         Main.ActiveNetDiagnosticsUI.CountSentMessage(msgType, num21);
                         Netplay.Connection.Socket.AsyncSend(buffer[num].writeBuffer, 0, num21, Netplay.Connection.ClientWriteCallBack);
                     }
                     catch
                     {
                     }
                 }
             }
             else if (remoteClient == -1)
             {
                 switch (msgType)
                 {
                 case 34:
                 case 69:
                 {
                     for (int num23 = 0; num23 < 256; num23++)
                     {
                         if (num23 != ignoreClient && buffer[num23].broadcast && Netplay.Clients[num23].IsConnected())
{
                             try
{
                                 buffer[num23].spamCount++;
                                 Main.ActiveNetDiagnosticsUI.CountSentMessage(msgType, num21);
                                 Netplay.Clients[num23].Socket.AsyncSend(buffer[num].writeBuffer, 0, num21, Netplay.Clients[num23].ServerWriteCallBack);
                             }
                             catch
{
                             }
                         }
                     }
                     break;
                 }
                 case 20:
                 {
                     for (int num27 = 0; num27 < 256; num27++)
                     {
                         if (num27 != ignoreClient && buffer[num27].broadcast && Netplay.Clients[num27].IsConnected() && Netplay.Clients[num27].SectionRange((int)Math.Max(number3, number4), number, (int)number2))
{
                             try
{
                                 buffer[num27].spamCount++;
                                 Main.ActiveNetDiagnosticsUI.CountSentMessage(msgType, num21);
                                 Netplay.Clients[num27].Socket.AsyncSend(buffer[num].writeBuffer, 0, num21, Netplay.Clients[num27].ServerWriteCallBack);
                             }
                             catch
{
                             }
                         }
                     }
                     break;
                 }
                 case 23:
                 {
                     NPC nPC4 = Main.npc[number];
                     for (int num28 = 0; num28 < 256; num28++)
                     {
                         if (num28 == ignoreClient || !buffer[num28].broadcast || !Netplay.Clients[num28].IsConnected())
{
                             continue;
                         }
                         bool flag6 = false;
                         if (nPC4.boss || nPC4.netAlways || nPC4.townNPC || !nPC4.active)
{
                             flag6 = true;
                         }
                         else if (nPC4.netSkip <= 0)
{
                             Rectangle rect5 = Main.player[num28].getRect();
                             Rectangle rect6 = nPC4.getRect();
                             rect6.X -= 2500;
                             rect6.Y -= 2500;
                             rect6.Width += 5000;
                             rect6.Height += 5000;
                             if (rect5.Intersects(rect6))
{
                                 flag6 = true;
                             }
                         }
                         else
{
                             flag6 = true;
                         }
                         if (flag6)
{
                             try
{
                                 buffer[num28].spamCount++;
                                 Main.ActiveNetDiagnosticsUI.CountSentMessage(msgType, num21);
                                 Netplay.Clients[num28].Socket.AsyncSend(buffer[num].writeBuffer, 0, num21, Netplay.Clients[num28].ServerWriteCallBack);
                             }
                             catch
{
                             }
                         }
                     }
                     nPC4.netSkip++;
                     if (nPC4.netSkip > 4)
                     {
                         nPC4.netSkip = 0;
                     }
                     break;
                 }
                 case 28:
                 {
                     NPC nPC3 = Main.npc[number];
                     for (int num25 = 0; num25 < 256; num25++)
                     {
                         if (num25 == ignoreClient || !buffer[num25].broadcast || !Netplay.Clients[num25].IsConnected())
{
                             continue;
                         }
                         bool flag5 = false;
                         if (nPC3.life <= 0)
{
                             flag5 = true;
                         }
                         else
{
                             Rectangle rect3 = Main.player[num25].getRect();
                             Rectangle rect4 = nPC3.getRect();
                             rect4.X -= 3000;
                             rect4.Y -= 3000;
                             rect4.Width += 6000;
                             rect4.Height += 6000;
                             if (rect3.Intersects(rect4))
{
                                 flag5 = true;
                             }
                         }
                         if (flag5)
{
                             try
{
                                 buffer[num25].spamCount++;
                                 Main.ActiveNetDiagnosticsUI.CountSentMessage(msgType, num21);
                                 Netplay.Clients[num25].Socket.AsyncSend(buffer[num].writeBuffer, 0, num21, Netplay.Clients[num25].ServerWriteCallBack);
                             }
                             catch
{
                             }
                         }
                     }
                     break;
                 }
                 case 13:
                 {
                     for (int num26 = 0; num26 < 256; num26++)
                     {
                         if (num26 != ignoreClient && buffer[num26].broadcast && Netplay.Clients[num26].IsConnected())
{
                             try
{
                                 buffer[num26].spamCount++;
                                 Main.ActiveNetDiagnosticsUI.CountSentMessage(msgType, num21);
                                 Netplay.Clients[num26].Socket.AsyncSend(buffer[num].writeBuffer, 0, num21, Netplay.Clients[num26].ServerWriteCallBack);
                             }
                             catch
{
                             }
                         }
                     }
                     Main.player[number].netSkip++;
                     if (Main.player[number].netSkip > 2)
                     {
                         Main.player[number].netSkip = 0;
                     }
                     break;
                 }
                 case 27:
                 {
                     Projectile projectile2 = Main.projectile[number];
                     for (int num24 = 0; num24 < 256; num24++)
                     {
                         if (num24 == ignoreClient || !buffer[num24].broadcast || !Netplay.Clients[num24].IsConnected())
{
                             continue;
                         }
                         bool flag4 = false;
                         if (projectile2.type == 12 || Main.projPet[projectile2.type] || projectile2.aiStyle == 11 || projectile2.netImportant)
{
                             flag4 = true;
                         }
                         else
{
                             Rectangle rect = Main.player[num24].getRect();
                             Rectangle rect2 = projectile2.getRect();
                             rect2.X -= 5000;
                             rect2.Y -= 5000;
                             rect2.Width += 10000;
                             rect2.Height += 10000;
                             if (rect.Intersects(rect2))
{
                                 flag4 = true;
                             }
                         }
                         if (flag4)
{
                             try
{
                                 buffer[num24].spamCount++;
                                 Main.ActiveNetDiagnosticsUI.CountSentMessage(msgType, num21);
                                 Netplay.Clients[num24].Socket.AsyncSend(buffer[num].writeBuffer, 0, num21, Netplay.Clients[num24].ServerWriteCallBack);
                             }
                             catch
{
                             }
                         }
                     }
                     break;
                 }
                 default:
                 {
                     for (int num22 = 0; num22 < 256; num22++)
                     {
                         if (num22 != ignoreClient && (buffer[num22].broadcast || (Netplay.Clients[num22].State >= 3 && msgType == 10)) && Netplay.Clients[num22].IsConnected())
{
                             try
{
                                 buffer[num22].spamCount++;
                                 Main.ActiveNetDiagnosticsUI.CountSentMessage(msgType, num21);
                                 Netplay.Clients[num22].Socket.AsyncSend(buffer[num].writeBuffer, 0, num21, Netplay.Clients[num22].ServerWriteCallBack);
                             }
                             catch
{
                             }
                         }
                     }
                     break;
                 }
                 }
             }
             else if (Netplay.Clients[remoteClient].IsConnected())
             {
                 try
                 {
                     buffer[remoteClient].spamCount++;
                     Main.ActiveNetDiagnosticsUI.CountSentMessage(msgType, num21);
                     Netplay.Clients[remoteClient].Socket.AsyncSend(buffer[num].writeBuffer, 0, num21, Netplay.Clients[remoteClient].ServerWriteCallBack);
                 }
                 catch
                 {
                 }
             }
             if (Main.verboseNetplay)
             {
                 for (int num29 = 0; num29 < num21; num29++)
                 {
                 }
                 for (int num30 = 0; num30 < num21; num30++)
                 {
                     _ = buffer[num].writeBuffer[num30];
                 }
             }
             buffer[num].writeLocked = false;
             if (msgType == 2 && Main.netMode == 2)
             {
                 Netplay.Clients[num].PendingTermination = true;
                 Netplay.Clients[num].PendingTerminationApproved = true;
             }
         }
     }
References _currentNetSoundInfo, _currentPlayerDeathReason, _currentRevengeMarker, Entity.active, Tile.active(), Main.ActiveNetDiagnosticsUI, Main.ActiveWorldFileData, Tile.actuator(), WorldGen.SavedOreTiers.Adamantite, NPC.ai, Projectile.ai, Projectile.aiStyle, Item.ammo, Main.anglerQuest, Player.anglerQuestsFinished, Main.anglerWhoFinishedToday, EquipmentLoadout.Armor, Player.armor, PlayerItemSlotID.Armor0, ISocket.AsyncSend(), Player.ateArtisanBread, Player.autoReuseAllWeapons, Player.bank, PlayerItemSlotID.Bank1_0, Player.bank2, PlayerItemSlotID.Bank2_0, Player.bank3, PlayerItemSlotID.Bank3_0, Player.bank4, PlayerItemSlotID.Bank4_0, Projectile.bannerIdToRespondTo, Main.bloodMoon, NPC.boss, NPC.boughtBunny, NPC.boughtCat, NPC.boughtDog, buffer, NPC.buffTime, NPC.buffType, Player.buffType, TileEntity.ByID, Main.caveBackStyle, Main.caveBackX, NPC.cavernMonsterType, Main.chest, Netplay.Clients, Main.clientUUID, RemoteServer.ClientWriteCallBack(), Main.cloudBGActive, WorldGen.SavedOreTiers.Cobalt, Player.coinLuck, Color, Item.color, Tile.color(), NPC.combatBookVolumeTwoWasUsed, NPC.combatBookWasUsed, CompressTileBlock(), Netplay.Connection, Player.controlDown, Player.controlDownHold, Player.controlJump, Player.controlLeft, Player.controlRight, Player.controlUp, Player.controlUseItem, Player.controlUseTile, WorldGen.SavedOreTiers.Copper, WorldGen.corruptBG, NPCID.Count, ProjectileID.Count, INetDiagnosticsUI.CountSentMessage(), WorldGen.crimson, WorldGen.crimsonBG, Item.damage, Projectile.damage, Main.dayTime, Main.dedServ, WorldGen.desertBG, Player.difficulty, Entity.direction, NPC.directionY, Main.dontStarveWorld, NPC.downedAncientCultist, NPC.downedBoss1, NPC.downedBoss2, NPC.downedBoss3, NPC.downedChristmasIceQueen, NPC.downedChristmasSantank, NPC.downedChristmasTree, NPC.downedClown, Player.downedDD2EventAnyDifficulty, NPC.downedDeerclops, NPC.downedEmpressOfLight, NPC.downedFishron, NPC.downedFrost, NPC.downedGoblins, NPC.downedGolemBoss, NPC.downedHalloweenKing, NPC.downedHalloweenTree, DD2Event.DownedInvasionT1, DD2Event.DownedInvasionT2, DD2Event.DownedInvasionT3, NPC.downedMartians, NPC.downedMechBoss1, NPC.downedMechBoss2, NPC.downedMechBoss3, NPC.downedMechBossAny, NPC.downedMoonlord, NPC.downedPirates, NPC.downedPlantBoss, NPC.downedQueenBee, NPC.downedQueenSlime, NPC.downedSlimeKing, NPC.downedTowerNebula, NPC.downedTowerSolar, NPC.downedTowerStardust, NPC.downedTowerVortex, Main.drunkWorld, EquipmentLoadout.Dye, Player.dye, PlayerItemSlotID.Dye0, Main.eclipse, NetworkText.Empty, Player.enabledSuperCart, Player.equipmentBasedLuckBonus, Player.extraAccessory, Player.eyeColor, Main.fastForwardTimeToDawn, Main.fastForwardTimeToDusk, Main.forceHalloweenForToday, Main.forceXMasForToday, Tile.frameX, Tile.frameY, NPC.freeCake, Tile.fullbrightBlock(), Tile.fullbrightWall(), Main.GameMode, Main.getGoodWorld, NetSocialModule.GetLobbyId(), NPC.getRect(), Player.getRect(), Projectile.getRect(), ISocket.GetRemoteAddress(), Netplay.GetSectionX(), Netplay.GetSectionY(), Language.GetTextValue(), Player.ghost, NPC.GivenName, WorldGen.SavedOreTiers.Gold, Player.golferScoreAccumulated, Player.gravDir, Player.hair, Player.hairColor, Player.hairDye, Tile.halfBrick(), WorldGen.hallowBG, Sandstorm.Happening, Player.happyFunTorchTime, Main.hardMode, Player.HasGardenGnomeNearby, Entity.height, Main.hellBackStyle, Player.hideMisc, Player.hideVisibleAccessory, Player.hostile, Main.iceBackStyle, Projectile.identity, Tile.inActive(), Sandstorm.IntendedSeverity, Main.invasionType, Player.inventory, PlayerItemSlotID.Inventory0, Tile.invisibleBlock(), Tile.invisibleWall(), WorldGen.SavedOreTiers.Iron, ISocket.IsConnected(), RemoteClient.IsConnected(), Player.isOperatingAnotherEntity, Player.isPettingAnimal, PlayerSittingHelper.isSitting, PlayerSleepingHelper.isSleeping, Player.isTheAnimalBeingPetSmall, Player.IsVoidVaultEnabled, Chest.item, Main.item, Player.itemAnimation, Player.itemRotation, Main.jungleBackStyle, WorldGen.jungleBG, NPC.killCount, Item.knockBack, Projectile.knockBack, L, Player.ladyBugLuckTimeLeft, LanternNight.LanternsUp, NPC.life, NPC.lifeMax, Tile.liquid, Tile.liquidType(), PlayerItemSlotID.Loadout1_Armor_0, PlayerItemSlotID.Loadout1_Dye_0, PlayerItemSlotID.Loadout2_Armor_0, PlayerItemSlotID.Loadout2_Dye_0, PlayerItemSlotID.Loadout3_Armor_0, PlayerItemSlotID.Loadout3_Dye_0, Player.Loadouts, Player.luckPotion, NPC.maxAI, NPC.maxBuffs, Player.maxBuffs, NPC.MaxMoonLordCountdown, Main.maxRaining, Main.maxTilesX, Main.maxTilesY, Player.MinionAttackTargetNPC, Player.MinionRestTargetPoint, PlayerItemSlotID.Misc0, PlayerItemSlotID.MiscDye0, Player.miscDyes, Player.miscEquips, Main.moondialCooldown, NPC.MoonLordCountdown, Main.moonModY, Main.moonPhase, Main.moonType, WorldGen.mushroomBG, WorldGen.SavedOreTiers.Mythril, Chest.name, Item.Name, Player.name, ProjectileID.Sets.NeedsUUID, NPC.netAlways, Item.netID, NPC.netID, Projectile.netImportant, Main.netMode, NPC.netSkip, Player.netSkip, SocialAPI.Network, Item.notAmmo, Main.noTrapsWorld, Main.notTheBeesWorld, Main.npc, Main.npcCatchable, Player.numberOfDeathsPVE, Player.numberOfDeathsPVP, Main.numClouds, WorldGen.oceanBG, DD2Event.Ongoing, Projectile.originalDamage, Projectile.owner, Player.pantsColor, BirthdayParty.PartyIsUp, NPC.peddlersSatchelWasUsed, RemoteClient.PendingTermination, RemoteClient.PendingTerminationApproved, Player.piggyBankProjTracker, Main.player, Item.playerIndexTheItemIsReservedFor, Entity.position, Player.PotionOfReturnHomePosition, Player.PotionOfReturnOriginalUsePosition, Item.prefix, Main.projectile, Main.projPet, Projectile.projUUID, Player.pulley, Player.pulleyDir, Main.pumpkinMoon, Main.raining, NPC.releaseOwner, Main.remixWorld, MessageBuffer.ResetWriter(), Player.respawnTimer, Main.rockLayer, Item.scale, RemoteClient.SectionRange(), Player.selectedItem, Netplay.ServerPassword, RemoteClient.ServerWriteCallBack(), Item.SetDefaults(), WorldGen.shadowOrbSmashed, Player.shieldRaised, NPC.ShieldStrengthTowerNebula, NPC.ShieldStrengthTowerSolar, NPC.ShieldStrengthTowerStardust, NPC.ShieldStrengthTowerVortex, Item.shimmered, Item.shimmerTime, Player.shirtColor, Player.shoeColor, Item.shoot, Item.shootSpeed, Main.sign, WorldGen.SavedOreTiers.Silver, Player.sitting, Player.skinColor, Player.skinVariant, Player.sleeping, Main.slimeRain, Tile.slope(), WorldGen.snowBG, Main.snowMoon, RemoteClient.Socket, RemoteServer.Socket, MessageBuffer.spamCount, NPC.SpawnedFromStatue, Main.spawnTileX, Main.spawnTileY, Player.SpawnX, Player.SpawnY, NPC.spriteDirection, Item.stack, RemoteClient.State, Player.statLife, Player.statLifeMax, Player.statMana, Player.statManaMax, NPC.statsAreScaledForThisManyPlayers, Player.stealth, NPC.strengthMultiplier, Main.sundialCooldown, Main.sunModY, TreeTopsInfo.SyncSend(), Player.talkNPC, NPC.target, WorldGen.tBlood, Player.team, Main.tenthAnniversaryWorld, WorldGen.tEvil, Sign.text, WorldGen.tGood, Main.tile, Main.tileFrameImportant, Main.time, Item.timeLeftInWhichTheItemCannotBeTakenByEnemies, Player.torchLuck, NPC.townNPC, NPC.townNpcVariationIndex, PlayerItemSlotID.TrashItem, Player.trashItem, Main.travelShop, WorldGen.treeBG1, WorldGen.treeBG2, WorldGen.treeBG3, WorldGen.treeBG4, Main.treeStyle, WorldGen.TreeTops, Main.treeX, Player.tryKeepingHoveringDown, Player.tryKeepingHoveringUp, Item.type, NPC.type, Projectile.type, Tile.type, Player.underShirtColor, WorldGen.underworldBG, WorldFileData.UniqueId, Player.unlockedBiomeTorches, NPC.unlockedSlimeBlueSpawn, NPC.unlockedSlimeCopperSpawn, NPC.unlockedSlimeGreenSpawn, NPC.unlockedSlimeOldSpawn, NPC.unlockedSlimePurpleSpawn, NPC.unlockedSlimeRainbowSpawn, NPC.unlockedSlimeRedSpawn, NPC.unlockedSlimeYellowSpawn, Player.unlockedSuperCart, NPC.unlockedTruffleSpawn, Item.useAmmo, Item.useAnimation, Player.usedAegisCrystal, Player.usedAegisFruit, Player.usedAmbrosia, Player.usedArcaneCrystal, Player.usedGalaxyPearl, Player.usedGummyWorm, Item.useTime, Player.UsingBiomeTorches, Entity.velocity, Main.verboseNetplay, Player.voidLensChest, Player.vortexStealthActive, Tile.wall, Tile.wallColor(), Entity.width, Main.windSpeedTarget, Tile.wire(), Tile.wire2(), Tile.wire3(), Tile.wire4(), WorldFileData.WorldGeneratorVersion, Main.worldID, Main.worldName, Main.worldSurface, TrackedProjectileReference.Write(), TileEntity.Write(), WriteAccessoryVisibility(), MessageBuffer.writeBuffer, MessageBuffer.writeLocked, MessageBuffer.writer, PlayerDeathReason.WriteSelfTo(), NetMessage.NetSoundInfo.WriteSelfTo(), Chest.x, Sign.x, Chest.y, Sign.y, Main.zenithWorld, Player.zone1, Player.zone2, Player.zone3, Player.zone4, and Player.zone5.
Referenced by TETrainingDummy.Activate(), NPC.AddBuff(), Player.AddBuff(), Liquid.AddWater(), Chest.AfterPlacement_Hook(), NPC.AI(), NPC.AI_000_TransformBoundNPC(), NPC.AI_003_Fighters(), NPC.AI_006_Worms(), Projectile.AI_007_GrapplingHooks(), NPC.AI_007_TownEntities(), Projectile.AI_010(), NPC.AI_037_Destroyer(), Projectile.AI_061_FishingBobber_GiveItemToPlayer(), NPC.AI_065_Butterflies(), NPC.AI_084_LunaticCultist(), NPC.AI_107_ImprovedWalkers(), NPC.AI_112_FairyCritter(), NPC.AI_120_HallowBoss(), NPC.AI_121_QueenSlime(), NPC.AI_123_Deerclops(), NPC.AI_124_DeerclopsLeg(), Projectile.AI_150_GolfClubHelper(), Projectile.AI_155_MysticSnakeCoil(), Projectile.AI_155_RemoveRope(), NPC.AI_87_BigMimic_ShootItem(), Player.ApplyDamageToNPC(), Player.ApplyNPCOnHitEffects(), Player.ApplyTouchDamage(), WorldGen.AttemptFossilShattering(), Lang.BartenderHelpText(), TileEntity.BasicOpenCloseInteraction(), NPC.BeHurtByOtherNPC(), NPC.BigMimicSpawnSmoke(), NPC.BigMimicSummonCheck(), BootPlayer(), Player.BrainOfConfusionDodge(), Main.BuyHairWindow(), NPC.CatchNPC(), Sandstorm.ChangeSeverityIntentions(), NPC.CheckActive(), NPC.CheckActive_WormSegments(), WorldGen.CheckBamboo(), WorldGen.CheckCatTail(), Player.CheckCrackedBrickBreak(), NPC.checkDead(), NPC.CheckDrowning(), Player.CheckIceBreak(), Item.CheckLavaDeath(), WorldGen.CheckLilyPad(), Wiring.CheckLogicGate(), DD2Event.CheckProgress(), NPC.CheckProgressFrostMoon(), NPC.CheckProgressPumpkinMoon(), CoinLossRevengeSystem.CheckRespawns(), WorldGen.CheckSeaOat(), RemoteClient.CheckSection(), WorldGen.CheckSuper(), WorldGen.CheckUnderwaterPlant(), DD2Event.ClearAllDD2EnergyCrystalsInChests(), DD2Event.ClearAllDD2EnergyCrystalsInGame(), DD2Event.ClearAllDD2HostilesInGame(), NPC.Collision_LavaCollision(), Item.CombineWithNearbyItems(), WorldGen.Convert(), NPC.CountKillForBannersAndDropThem(), WorldGen.CountTiles(), Recipe.Create(), LucyAxeMessage.Create(), DelegateMethods.CutTiles(), Projectile.CutTilesAt(), Projectile.Damage(), TETrainingDummy.Deactivate(), NPC.DelBuff(), Player.DemonConch(), ChestUI.DepositAll(), Item.DespawnIfMeetingConditions(), DD2Event.Difficulty_1_SpawnMonsterFromGate(), DD2Event.Difficulty_2_SpawnMonsterFromGate(), DD2Event.Difficulty_3_SpawnMonsterFromGate(), Mount.Dismount(), NPC.DoDeathEvents(), WorldGen.DontStarveTryWateringTile(), Player.DoPotionOfReturnReturnToOriginalUsePosition(), Player.DoPotionOfReturnTeleportationAndSetTheComebackPoint(), Player.DoQueenSlimeHookTeleport(), Main.DoUpdateInWorld(), Main.DrawInventory(), Main.DrawPVPIcons(), Player.DropCoins(), Projectile.DropGeodeGems(), Player.dropItemCheck(), Player.DropItemFromExtractinator(), NPC.DropItemInstanced(), CommonCode.DropItemLocalPerClientAndSetNPCMoneyTo0(), Player.DropSelectedItem(), WorldGen.dropXmasTree(), Player.EndOngoingTorchGodEvent(), Projectile.ExplodeCrackedTiles(), Projectile.ExplodeTiles(), Item.FindOwner(), Player.GetAnglerReward_Bait(), Player.GetAnglerReward_Decoration(), Player.GetAnglerReward_MainReward(), Player.GetAnglerReward_Money(), MessageBuffer.GetData(), Player.GetDyeTraderReward(), ItemSlot.GetGamepadInstructions(), Item.GetPickedUpByMonsters_Money(), Item.GetPickedUpByMonsters_Special(), WorldGen.GetRidOfCultists(), Item.GetShimmered(), NPC.GetShimmered(), WorldGen.GrowCatTail(), WorldGen.GrowCheckSeaweed(), Main.GUIChatDrawInner(), Projectile.HandleMovement(), TeleportPylonsSystem.HandleTeleportRequest(), Player.HealEffect(), NPC.HealEffect(), NPC.HitEffect(), Minecart.HitTrackSwitch(), Wiring.HitWireSingle(), TETrainingDummy.Hook_AfterPlacement(), TEItemFrame.Hook_AfterPlacement(), TELogicSensor.Hook_AfterPlacement(), TEDisplayDoll.Hook_AfterPlacement(), TEWeaponsRack.Hook_AfterPlacement(), TEHatRack.Hook_AfterPlacement(), TEFoodPlatter.Hook_AfterPlacement(), Player.Hurt(), Netplay.InnerClientLoop(), Player.ItemCheck(), Player.ItemCheck_CheckCanUse(), Player.ItemCheck_CheckFishingBobber_PullBobber(), Player.ItemCheck_CutTiles(), Player.ItemCheck_MeleeHitPVP(), Player.ItemCheck_PlayInstruments(), Player.ItemCheck_Shoot(), Player.ItemCheck_TryPlacingWearablesOnMannequins(), Player.ItemCheck_UseArtisanLoaf(), Player.ItemCheck_UseBossSpawners(), Player.ItemCheck_UseCombatBook(), Player.ItemCheck_UseDemonHeart(), Player.ItemCheck_UseEventItems(), Player.ItemCheck_UseMinecartPowerUp(), Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), Player.ItemCheck_UsePeddlersSatchel(), Player.ItemCheck_UseShimmerPermanentItems(), Player.ItemCheck_UseTeleportRod(), Player.ItemCheck_UseTorchGodsFavor(), Player.ItemCheck_UseWiringTools(), WorldGen.kickOut(), Projectile.Kill(), TELogicSensor.Kill(), Player.KillMe(), WorldGen.KillTile(), ItemSlot.LeftClick(), Liquid.LiquidCheck(), ChestUI.LootAll(), Player.MagicConch(), EmoteBubble.MakeLocalPlayerEmote(), Player.ManaEffect(), Wiring.MassWireOperation(), Wiring.MassWireOperationStep(), MinecartDiggerHelper.MineTheTileIfNecessary(), CommonCode.ModifyItemDropFromNPC(), Main.Moondialing(), ChestUI.MoveCoins(), WorldGen.moveRoom(), BirthdayParty.NaturalAttempt(), TEFoodPlatter.NetPlaceEntity(), TEItemFrame.NetPlaceEntity(), TELogicSensor.NetPlaceEntity(), TEWeaponsRack.NetPlaceEntity(), TEDisplayDoll.NetPlaceEntityAttempt(), TEHatRack.NetPlaceEntityAttempt(), TETeleportationPylon.NetPlaceEntityAttempt(), EmoteBubble.NewBubble(), EmoteBubble.NewBubbleNPC(), Item.NewItem(), Projectile.NewProjectile(), Player.NinjaDodge(), AchievementsHelper.NotifyNPCKilled(), AchievementsHelper.NotifyProgressionEvent(), TEFoodPlatter.OnPlayerInteraction(), TEItemFrame.OnPlayerInteraction(), TEWeaponsRack.OnPlayerInteraction(), Main.OnSubmitServerPasswordFromRequest(), Player.OpenFishingCrate(), Player.OpenGoodieBag(), Player.OpenHerbBag(), Player.OpenLegacyPresent(), Player.OpenLockBox(), Player.OpenPresent(), Player.OpenShadowLockbox(), TEDisplayDoll.OverrideItemSlotLeftClick(), TEHatRack.OverrideItemSlotLeftClick(), ItemSlot.OverrideLeftClick(), WorldGen.paintCoatTile(), WorldGen.paintCoatWall(), WorldGen.paintTile(), WorldGen.paintWall(), Player.PickTile(), Player.PickupItem(), ItemSlot.PickupItemIntoMouse(), Player.PickWall(), TileObject.Place(), WorldGen.Place3x2(), MinecartDiggerHelper.PlaceATrack(), WorldGen.PlaceChest(), TEFoodPlatter.PlaceItemInFrame(), TEItemFrame.PlaceItemInFrame(), TEWeaponsRack.PlaceItemInFrame(), TETeleportationPylon.PlacementPreviewHook_AfterPlacement(), Player.PlaceThing_LockChest(), Player.PlaceThing_PaintScrapper_LongMoss(), Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Player.PlaceThing_Tiles_PlaceIt(), Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Player.PlaceThing_Tiles_PlaceIt_TriggerLogicLamp(), Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), Player.PlaceThing_TryReplacingTiles(), Player.PlaceThing_TryReplacingWalls(), Player.PlaceThing_Walls(), Player.PlaceThing_Walls_FillEmptySpace(), Player.PlaceWeapon(), PlayNetSound(), PressurePlateHelper.PokeLocation(), WorldGen.PoundPlatform(), MinecartDiggerHelper.PoundTrack(), Player.ProcessHitAgainstNPC(), EmojiCommand.ProcessOutgoingMessage(), RockPaperScissorsCommand.ProcessOutgoingMessage(), Player.PurgeDD2EnergyCrystals(), GolfHelper.ContactListener.PutBallInCup(), Player.PutItemInInventoryFromItemUsage(), Player.QuickGrapple(), Player.QuickSpawnItem(), ChestUI.QuickStack(), Player.QuickStackAllChests(), TreeTopsInfo.RandomizeTreeStyle(), TETeleportationPylon.RejectPlacementFromNet(), NPC.ReleaseNPC(), CoinLossRevengeSystem.RemoveExpiredOrInvalidMarkers(), PortalHelper.RemoveIntersectingPortals(), WorldGen.ReplaceTIle_DoActualReplacement(), NPC.RequestBuffRemoval(), DD2Event.RequestToSkipWaitTime(), ChestUI.Restock(), Main.SaveClothesWindow(), ItemSlot.SellOrTrash(), SendAnglerQuest(), SendCoinLossRevengeMarker(), CreditsRollEvent.SendCreditsRollRemainingTimeToPlayer(), SendNPCHousesAndTravelShop(), SendObjectPlacement(), SendPlayerDeath(), SendPlayerHurt(), SendSection(), SendTemporaryAnimation(), SendTileSquare(), SendTravelShop(), sendWater(), Chest.ServerPlaceItem(), DD2Event.SetEnemySpawningOnHold(), Mount.SetMount(), Player.ShadowDodge(), Player.Shellphone_Spawn(), Projectile.Shimmer(), WorldGen.ShootFromCannon(), PlayerSittingHelper.SitDown(), PlayerSittingHelper.SitUp(), WorldGen.SmashAltar(), Tile.SmoothSlope(), ItemSorting.SortChest(), Player.Spawn(), NPC.SpawnBoss(), CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), NPC.SpawnFaelings(), NPC.SpawnMechQueen(), NPC.SpawnNPC(), NPC.SpawnSkeletron(), WorldGen.SpawnTownNPC(), DelegateMethods.SpreadDirt(), Main.startDedInputCallBack(), WorldGen.StartImpendingDoom(), DD2Event.StartInvasion(), PlayerSleepingHelper.StartSleeping(), Main.StartSlimeRain(), Player.StickyMovement(), DD2Event.StopInvasion(), PlayerSleepingHelper.StopSleeping(), Main.StopSlimeRain(), Main.SubmitSignText(), DD2Event.SummonCrystal(), Main.Sundialing(), ItemSlot.SwapEquip(), Collision.SwitchTiles(), Main.SyncAnInvasion(), DD2Event.SyncInvasionProgress(), TileObjectData.SyncObjectPlacement(), SyncOnePlayer(), SyncOnePlayer_ItemArray(), Wiring.Teleport(), NPC.Teleport(), Player.TeleportationPotion(), Player.TileInteractionsUse(), WorldGen.ToggleGemLock(), LanternNight.ToggleManualLanterns(), BirthdayParty.ToggleManualParty(), Player.TorchAttack(), NPC.Transform(), NPC.TransformCopperSlime(), NPC.TransformElderSlime(), WorldGen.TreeGrowFXCheck(), WorldGen.TriggerLunarApocalypse(), DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryCloseDoor(), DoorOpeningHelper.TallGateOpeningInfoProvider.TryCloseDoor(), Player.TryDroppingSingleItem(), TEDisplayDoll.TryFitting(), TEHatRack.TryFitting(), PortalHelper.TryGoingThroughPortals(), WorldGen.TryKillingReplaceableTile(), WorldGen.TryKillingTreesAboveIfTheyWouldBecomeInvalid(), Player.TryLandingOnDetonator(), DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryOpenDoor(), DoorOpeningHelper.TallGateOpeningInfoProvider.TryOpenDoor(), ItemSlot.TryPickupDyeToCursor(), TEFoodPlatter.TryPlacing(), TEItemFrame.TryPlacing(), TEWeaponsRack.TryPlacing(), ChestUI.TryPlacingInChest(), TrySendData(), MysticLogFairiesEvent.TrySpawningFairies(), CreditsRollEvent.TryStartingCreditsRoll(), Player.TrySyncingInput(), Main.TrySyncingItemArray(), Main.TrySyncingMyPlayer(), NPC.TrySyncingUniqueTownNPCData(), NPC.TryTeleportingCaughtMysticFrog(), Player.TryToPoop(), Player.UnityTeleport(), NPC.UnlockOrExchangePet(), WorldGen.UnspawnTravelNPC(), Player.Update(), Projectile.Update(), Main.UpdateClient(), Main.updateCloudLayer(), TELogicSensor.UpdateEndInternal(), NPC.UpdateHomeTileState(), Main.UpdateInvasion(), Item.UpdateItem(), Player.UpdateLuck(), NPC.UpdateNetworkCode(), NPC.UpdateNPC(), NPC.UpdateNPC_BuffApplyDOTs(), NPC.UpdateNPC_BuffClearExpiredBuffs(), Main.UpdateServer(), BirthdayParty.UpdateTime(), DD2Event.UpdateTime(), LanternNight.UpdateTime(), Main.UpdateTime(), Main.UpdateTime_StartDay(), Main.UpdateTime_StartNight(), Main.UpdateWeather(), WorldGen.UpdateWorld_OvergroundTile(), WorldGen.UpdateWorld_UndergroundTile(), Projectile.UseGasTrapInChest(), and DD2Event.WipeEntities().