Terraria: NetMessage.SyncOnePlayer
SyncOnePlayer()
static void NetMessage.SyncOnePlayer (int plr, int toWho, int fromWho) inline static private
     {
         int num = 0;
         if (Main.player[plr].active)
         {
             num = 1;
         }
         if (Netplay.Clients[plr].State == 10)
         {
             SendData(14, toWho, fromWho, null, plr, num);
             SendData(4, toWho, fromWho, null, plr);
             SendData(13, toWho, fromWho, null, plr);
             if (Main.player[plr].statLife <= 0)
             {
                 SendData(135, toWho, fromWho, null, plr);
             }
             SendData(16, toWho, fromWho, null, plr);
             SendData(30, toWho, fromWho, null, plr);
             SendData(45, toWho, fromWho, null, plr);
             SendData(42, toWho, fromWho, null, plr);
             SendData(50, toWho, fromWho, null, plr);
             SendData(80, toWho, fromWho, null, plr, Main.player[plr].chest);
             SendData(142, toWho, fromWho, null, plr);
             SendData(147, toWho, fromWho, null, plr, Main.player[plr].CurrentLoadoutIndex);
             for (int i = 0; i < 59; i++)
             {
                 SendData(5, toWho, fromWho, null, plr, PlayerItemSlotID.Inventory0 + i, (int)Main.player[plr].inventory[i].prefix);
             }
             for (int j = 0; j < Main.player[plr].armor.Length; j++)
             {
                 SendData(5, toWho, fromWho, null, plr, PlayerItemSlotID.Armor0 + j, (int)Main.player[plr].armor[j].prefix);
             }
             for (int k = 0; k < Main.player[plr].dye.Length; k++)
             {
                 SendData(5, toWho, fromWho, null, plr, PlayerItemSlotID.Dye0 + k, (int)Main.player[plr].dye[k].prefix);
             }
             SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].miscEquips, PlayerItemSlotID.Misc0);
             SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].miscDyes, PlayerItemSlotID.MiscDye0);
             SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[0].Armor, PlayerItemSlotID.Loadout1_Armor_0);
             SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[0].Dye, PlayerItemSlotID.Loadout1_Dye_0);
             SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[1].Armor, PlayerItemSlotID.Loadout2_Armor_0);
             SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[1].Dye, PlayerItemSlotID.Loadout2_Dye_0);
             SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[2].Armor, PlayerItemSlotID.Loadout3_Armor_0);
             SyncOnePlayer_ItemArray(plr, toWho, fromWho, Main.player[plr].Loadouts[2].Dye, PlayerItemSlotID.Loadout3_Dye_0);
             if (!Netplay.Clients[plr].IsAnnouncementCompleted)
             {
                 Netplay.Clients[plr].IsAnnouncementCompleted = true;
                 ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.mp[19].Key, Main.player[plr].name), new Color(255, 240, 20), plr);
                 if (Main.dedServ)
                 {
                     Console.WriteLine(Lang.mp[19].Format(Main.player[plr].name));
                 }
             }
             return;
         }
         num = 0;
         SendData(14, -1, plr, null, plr, num);
         if (Netplay.Clients[plr].IsAnnouncementCompleted)
         {
             Netplay.Clients[plr].IsAnnouncementCompleted = false;
             ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.mp[20].Key, Netplay.Clients[plr].Name), new Color(255, 240, 20), plr);
             if (Main.dedServ)
             {
                 Console.WriteLine(Lang.mp[20].Format(Netplay.Clients[plr].Name));
             }
             Netplay.Clients[plr].Name = "Anonymous";
         }
         Player.Hooks.PlayerDisconnect(plr);
     }
References Entity.active, EquipmentLoadout.Armor, Player.armor, PlayerItemSlotID.Armor0, ChatHelper.BroadcastChatMessage(), Player.chest, Netplay.Clients, Color, Player.CurrentLoadoutIndex, Main.dedServ, EquipmentLoadout.Dye, Player.dye, PlayerItemSlotID.Dye0, LocalizedText.Format(), NetworkText.FromKey(), Player.inventory, PlayerItemSlotID.Inventory0, RemoteClient.IsAnnouncementCompleted, LocalizedText.Key, PlayerItemSlotID.Loadout1_Armor_0, PlayerItemSlotID.Loadout1_Dye_0, PlayerItemSlotID.Loadout2_Armor_0, PlayerItemSlotID.Loadout2_Dye_0, PlayerItemSlotID.Loadout3_Armor_0, PlayerItemSlotID.Loadout3_Dye_0, Player.Loadouts, PlayerItemSlotID.Misc0, PlayerItemSlotID.MiscDye0, Player.miscDyes, Player.miscEquips, Lang.mp, Player.name, RemoteClient.Name, Main.player, Player.Hooks.PlayerDisconnect(), Item.prefix, SendData(), RemoteClient.State, Player.statLife, and SyncOnePlayer_ItemArray().
Referenced by SyncConnectedPlayer(), and SyncDisconnectedPlayer().