Terraria: NetMessage.DoesPlayerSlotCountAsAHost
DoesPlayerSlotCountAsAHost()
static bool NetMessage.DoesPlayerSlotCountAsAHost (int plr) inline static
     {
         if (Netplay.Clients[plr].State == 10)
         {
             return Netplay.Clients[plr].Socket.GetRemoteAddress().IsLocalHost();
         }
         return false;
     }
References Netplay.Clients, ISocket.GetRemoteAddress(), RemoteAddress.IsLocalHost(), RemoteClient.Socket, and RemoteClient.State.
Referenced by EnsureLocalPlayerIsPresent(), and MessageBuffer.GetData().