Terraria: Terraria.GameContent.RGB.TwinsShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.TwinsShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 53 of file TwinsShader.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Invalid comparison between Unknown and I4
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        if ((int)device.Type != 0 && (int)device.Type != 6)
        {
            ProcessLowDetail(device, fragment, quality, time);
            return;
        }
        bool flag = true;
        float num = time * 0.1f % 2f;
        if (num > 1f)
        {
            num = 2f - num;
            flag = false;
        }
        Vector2 vector = new Vector2(num * 7f - 3.5f, 0f) + fragment.CanvasCenter;
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
            Vector4 vector2 = _backgroundColor;
            Vector2 vector3 = canvasPositionOfIndex - vector;
            float num2 = vector3.Length();
            if (num2 < 0.5f)
            {
                float amount = 1f - MathHelper.Clamp((num2 - 0.5f + 0.2f) / 0.2f, 0f, 1f);
                float num3 = MathHelper.Clamp((vector3.X + 0.5f - 0.2f) / 0.6f, 0f, 1f);
                if (flag)
                {
                    num3 = 1f - num3;
                }
                Vector4 value = Vector4.Lerp(_eyeColor, _veinColor, num3);
                float value2 = (float)Math.Atan2(vector3.Y, vector3.X);
                if (!flag && (float)Math.PI - Math.Abs(value2) < 0.6f)
                {
                    value = _mouthColor;
                }
                vector2 = Vector4.Lerp(vector2, value, amount);
            }
            if (flag && gridPositionOfIndex.Y == 3 && canvasPositionOfIndex.X > vector.X)
            {
                float value3 = 1f - Math.Abs(canvasPositionOfIndex.X - vector.X * 2f - 0.5f) / 0.5f;
                vector2 = Vector4.Lerp(vector2, _laserColor, MathHelper.Clamp(value3, 0f, 1f));
            }
            else if (!flag)
            {
                Vector2 vector4 = canvasPositionOfIndex - (vector - new Vector2(1.2f, 0f));
                vector4.Y *= 3.5f;
                float num4 = vector4.Length();
                if (num4 < 0.7f)
                {
                    float dynamicNoise = NoiseHelper.GetDynamicNoise(canvasPositionOfIndex, time);
                    dynamicNoise = dynamicNoise * dynamicNoise * dynamicNoise;
                    dynamicNoise *= 1f - MathHelper.Clamp((num4 - 0.7f + 0.3f) / 0.3f, 0f, 1f);
                    vector2 = Vector4.Lerp(vector2, _flameColor, dynamicNoise);
                }
            }
            fragment.SetColor(i, vector2);
        }
    }
References Terraria.GameContent.RGB.TwinsShader._backgroundColor, Terraria.GameContent.RGB.TwinsShader._eyeColor, Terraria.GameContent.RGB.TwinsShader._flameColor, Terraria.GameContent.RGB.TwinsShader._laserColor, Terraria.GameContent.RGB.TwinsShader._mouthColor, Terraria.GameContent.RGB.TwinsShader._veinColor, System.Math.Abs(), System.Math.Atan2(), ReLogic.Peripherals.RGB.Fragment.CanvasCenter, Microsoft.Xna.Framework.MathHelper.Clamp(), ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise(), ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector4.Lerp(), Terraria.GameContent.RGB.TwinsShader.ProcessLowDetail(), ReLogic.Peripherals.RGB.Fragment.SetColor(), ReLogic.Peripherals.RGB.RgbDevice.Type, System.value, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.