Terraria: LegacySoundPlayer.PlaySound
PlaySound()
SoundEffectInstance LegacySoundPlayer.PlaySound (int type, int x = -1, int y = -1, int Style = 1, float volumeScale = 1f, float pitchOffset = 0f) inline
References Main.ambientVolume, Main.dedServ, DoesSoundScaleWithAmbientVolume(), Main.gameInactive, Main.gameMenu, WorldGen.gen, Main.hasFocus, Main.musicPitch, Main.myPlayer, Main.netMode, UnifiedRandom.Next(), Main.player, Entity.position, Main.rand, Main.screenHeight, Main.screenPosition, Main.screenWidth, Main.shimmerAlpha, SoundCamera, SoundChat, SoundCoin, SoundCoins, SoundDig, SoundDoorClosed, SoundDoorOpen, SoundDoubleJump, SoundDrip, SoundDrown, SoundFemaleHit, SoundGrab, SoundGrass, SoundInstanceCamera, SoundInstanceChat, SoundInstanceCoin, SoundInstanceCoins, SoundInstanceDig, SoundInstanceDoorClosed, SoundInstanceDoorOpen, SoundInstanceDoubleJump, SoundInstanceDrip, SoundInstanceDrown, SoundInstanceFemaleHit, SoundInstanceGrab, SoundInstanceGrass, SoundInstanceItem, SoundInstanceLiquid, SoundInstanceMaxMana, SoundInstanceMech, SoundInstanceMenuClose, SoundInstanceMenuOpen, SoundInstanceMenuTick, SoundInstanceMoonlordCry, SoundInstanceNpcHit, SoundInstanceNpcKilled, SoundInstancePixie, SoundInstancePlayerHit, SoundInstancePlayerKilled, SoundInstanceResearch, SoundInstanceRoar, SoundInstanceRun, SoundInstanceShatter, SoundInstanceSplash, SoundInstanceThunder, SoundInstanceTink, SoundInstanceUnlock, SoundInstanceZombie, SoundItem, SoundLiquid, SoundMaxMana, SoundMech, SoundMenuClose, SoundMenuOpen, SoundMenuTick, SoundNpcHit, SoundNpcKilled, SoundPixie, SoundPlayerHit, SoundPlayerKilled, SoundResearch, SoundRoar, SoundRun, SoundShatter, SoundSplash, SoundThunder, SoundTink, SoundUnlock, Main.soundVolume, SoundZombie, Main.starGame, SoundInstanceGarbageCollector.Track(), TrackableSoundInstances, TrackableSounds, and Asset< T >.Value.
Referenced by SoundEngine.PlaySound().