Terraria: System.Linq.Expressions.TypeBinaryExpression.ByValParameterTypeEqual
ByValParameterTypeEqual()
Expression System.Linq.Expressions.TypeBinaryExpression.ByValParameterTypeEqual (ParameterExpression value) inline private
Definition at line 52 of file TypeBinaryExpression.cs.
    {
        Expression expression = System.Linq.Expressions.Expression.Call(value, CachedReflectionInfo.Object_GetType);
        if (TypeOperand.IsInterface)
        {
            ParameterExpression parameterExpression = System.Linq.Expressions.Expression.Parameter(typeof(Type));
            expression = System.Linq.Expressions.Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression), new TrueReadOnlyCollection<Expression>(System.Linq.Expressions.Expression.Assign(parameterExpression, expression), parameterExpression));
        }
        return System.Linq.Expressions.Expression.AndAlso(System.Linq.Expressions.Expression.ReferenceNotEqual(value, Utils.Null), System.Linq.Expressions.Expression.ReferenceEqual(expression, System.Linq.Expressions.Expression.Constant(TypeOperand.GetNonNullableType(), typeof(Type))));
    }
References System.Linq.Expressions.Expression< TDelegate >.AndAlso(), System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Type.IsInterface, System.Linq.Expressions.Utils.Null, System.Linq.Expressions.CachedReflectionInfo.Object_GetType, System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Linq.Expressions.Expression< TDelegate >.ReferenceEqual(), System.Linq.Expressions.Expression< TDelegate >.ReferenceNotEqual(), System.Linq.Expressions.TypeBinaryExpression.TypeOperand, and System.value.
Referenced by System.Linq.Expressions.TypeBinaryExpression.ReduceTypeEqual().