Terraria: System.Linq.Expressions.TypeBinaryExpression.ReduceTypeEqual
ReduceTypeEqual()
Expression System.Linq.Expressions.TypeBinaryExpression.ReduceTypeEqual () inline package
Definition at line 25 of file TypeBinaryExpression.cs.
    {
        Type type = Expression.Type;
        if (type.IsValueType || TypeOperand.IsPointer)
        {
            if (type.IsNullableType())
            {
                if (type.GetNonNullableType() != TypeOperand.GetNonNullableType())
                {
                    return System.Linq.Expressions.Expression.Block(Expression, Utils.Constant(value: false));
                }
                return System.Linq.Expressions.Expression.NotEqual(Expression, System.Linq.Expressions.Expression.Constant(null, Expression.Type));
            }
            return System.Linq.Expressions.Expression.Block(Expression, Utils.Constant(type == TypeOperand.GetNonNullableType()));
        }
        if (Expression.NodeType == ExpressionType.Constant)
        {
            return ReduceConstantTypeEqual();
        }
        if (Expression is ParameterExpression { IsByRef: false } parameterExpression)
        {
            return ByValParameterTypeEqual(parameterExpression);
        }
        ParameterExpression parameterExpression2 = System.Linq.Expressions.Expression.Parameter(typeof(object));
        return System.Linq.Expressions.Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression2), new TrueReadOnlyCollection<Expression>(System.Linq.Expressions.Expression.Assign(parameterExpression2, Expression), ByValParameterTypeEqual(parameterExpression2)));
    }
References System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.TypeBinaryExpression.ByValParameterTypeEqual(), System.Linq.Expressions.Utils.Constant(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Type.IsPointer, System.Linq.Expressions.Expression< TDelegate >.NodeType, System.Linq.Expressions.Expression< TDelegate >.NotEqual(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Linq.Expressions.TypeBinaryExpression.ReduceConstantTypeEqual(), System.Linq.Expressions.Expression< TDelegate >.Type, System.type, System.Linq.Expressions.TypeBinaryExpression.TypeOperand, and System.value.