Terraria: Terraria.Mount.MountDelegatesData.MountDelegatesData
MountDelegatesData()
Terraria.Mount.MountDelegatesData.MountDelegatesData () inline
Definition at line 97 of file Mount.cs.
        {
            MinecartDust = DelegateMethods.Minecart.Sparks;
            MinecartJumpingSound = DelegateMethods.Minecart.JumpingSound;
            MinecartLandingSound = DelegateMethods.Minecart.LandingSound;
            MinecartBumperSound = DelegateMethods.Minecart.BumperSound;
        }
References Terraria.DelegateMethods.Minecart.BumperSound(), Terraria.DelegateMethods.Minecart.JumpingSound(), Terraria.DelegateMethods.Minecart.LandingSound(), Terraria.Mount.MountDelegatesData.MinecartBumperSound, Terraria.Mount.MountDelegatesData.MinecartDust, Terraria.Mount.MountDelegatesData.MinecartJumpingSound, Terraria.Mount.MountDelegatesData.MinecartLandingSound, and Terraria.DelegateMethods.Minecart.Sparks().