Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncCore
ReadAsyncCore()
async Task< int > System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncCore (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline private
Definition at line 411 of file WebSocketHttpListenerDuplexStream.cs.
    {
        CancellationTokenRegistration cancellationTokenRegistration = default(CancellationTokenRegistration);
        int result = 0;
        try
        {
            if (cancellationToken.CanBeCanceled)
            {
                cancellationTokenRegistration = cancellationToken.Register(s_OnCancel, this, useSynchronizationContext: false);
            }
            if (!_inOpaqueMode)
            {
                result = await _inputStream.ReadAsync(buffer, offset, count, cancellationToken).SuppressContextFlow();
            }
            else
            {
                _readTaskCompletionSource = new TaskCompletionSource<int>();
                _readEventArgs.SetBuffer(buffer, offset, count);
                if (!ReadAsyncFast(_readEventArgs))
                {
                    if (_readEventArgs.Exception != null)
                    {
                        throw _readEventArgs.Exception;
                    }
                    result = _readEventArgs.BytesTransferred;
                }
                else
                {
                    result = await _readTaskCompletionSource.Task.SuppressContextFlow();
                }
            }
        }
        catch (Exception arg)
        {
            if (s_CanHandleException(arg))
            {
                cancellationToken.ThrowIfCancellationRequested();
            }
            throw;
        }
        finally
        {
            cancellationTokenRegistration.Dispose();
        }
        return result;
    }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream._inOpaqueMode, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._inputStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._readEventArgs, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._readTaskCompletionSource, System.buffer, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.BytesTransferred, System.cancellationToken, System.count, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Exception, System.offset, System.IO.Stream.ReadAsync(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncFast(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.s_CanHandleException, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.s_OnCancel, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.SetBuffer(), and System.Threading.Tasks.TaskCompletionSource< TResult >.Task.
Referenced by System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsync().