Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast
WriteAsyncFast()
unsafe bool System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast (HttpListenerAsyncEventArgs eventArgs) inline private
Definition at line 629 of file WebSocketHttpListenerDuplexStream.cs.
    {
        global::Interop.HttpApi.HTTP_FLAGS hTTP_FLAGS = global::Interop.HttpApi.HTTP_FLAGS.NONE;
        eventArgs.StartOperationCommon(this, _outputStream.InternalHttpContext.RequestQueueBoundHandle);
        eventArgs.StartOperationSend();
        bool flag = false;
        try
        {
            if (_outputStream.Closed || (eventArgs.Buffer != null && eventArgs.Count == 0))
            {
                eventArgs.FinishOperationSuccess(eventArgs.Count, syncCompletion: true);
                return false;
            }
            if (eventArgs.ShouldCloseOutput)
            {
                hTTP_FLAGS |= global::Interop.HttpApi.HTTP_FLAGS.HTTP_RECEIVE_REQUEST_FLAG_COPY_BODY;
            }
            else
            {
                hTTP_FLAGS |= global::Interop.HttpApi.HTTP_FLAGS.HTTP_SEND_RESPONSE_FLAG_MORE_DATA;
                hTTP_FLAGS |= global::Interop.HttpApi.HTTP_FLAGS.HTTP_SEND_RESPONSE_FLAG_BUFFER_DATA;
            }
            Unsafe.SkipInit(out uint bytesTransferred);
            uint num = global::Interop.HttpApi.HttpSendResponseEntityBody(_outputStream.InternalHttpContext.RequestQueueHandle, _outputStream.InternalHttpContext.RequestId, (uint)hTTP_FLAGS, eventArgs.EntityChunkCount, (global::Interop.HttpApi.HTTP_DATA_CHUNK*)(void*)eventArgs.EntityChunks, &bytesTransferred, Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero, 0u, eventArgs.NativeOverlapped, null);
            if (num != 0 && num != 997)
            {
                throw new HttpListenerException((int)num);
            }
            if (num == 0 && HttpListener.SkipIOCPCallbackOnSuccess)
            {
                eventArgs.FinishOperationSuccess((int)bytesTransferred, syncCompletion: true);
                return false;
            }
            return true;
        }
        catch (Exception exception)
        {
            _writeEventArgs.FinishOperationFailure(exception, syncCompletion: true);
            _outputStream.SetClosedFlag();
            _outputStream.InternalHttpContext.Abort();
            return true;
        }
    }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream._outputStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._writeEventArgs, System.Net.HttpListenerContext.Abort(), System.Net.HttpResponseStream.Closed, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.exception, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.FinishOperationFailure(), System.Net.HttpResponseStream.InternalHttpContext, System.Net.HttpListenerContext.RequestId, System.Net.HttpListenerContext.RequestQueueBoundHandle, System.Net.HttpListenerContext.RequestQueueHandle, System.Net.HttpResponseStream.SetClosedFlag(), System.Net.HttpListener.SkipIOCPCallbackOnSuccess, and Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero.
Referenced by System.Net.WebSockets.WebSocketHttpListenerDuplexStream.CloseNetworkConnectionAsync(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.MultipleWriteAsyncCore(), and System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncCore().