Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncFast
ReadAsyncFast()
unsafe bool System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncFast (HttpListenerAsyncEventArgs eventArgs) inline private
Definition at line 458 of file WebSocketHttpListenerDuplexStream.cs.
    {
        eventArgs.StartOperationCommon(this, _inputStream.InternalHttpContext.RequestQueueBoundHandle);
        eventArgs.StartOperationReceive();
        uint num = 0u;
        bool flag = false;
        try
        {
            if (eventArgs.Count == 0 || _inputStream.Closed)
            {
                eventArgs.FinishOperationSuccess(0, syncCompletion: true);
                return false;
            }
            uint num2 = 0u;
            int offset = eventArgs.Offset;
            int count = eventArgs.Count;
            if (_inputStream.BufferedDataChunksAvailable)
            {
                num2 = _inputStream.GetChunks(eventArgs.Buffer, eventArgs.Offset, eventArgs.Count);
                if (_inputStream.BufferedDataChunksAvailable && num2 == eventArgs.Count)
                {
                    eventArgs.FinishOperationSuccess(eventArgs.Count, syncCompletion: true);
                    return false;
                }
            }
            if (num2 != 0)
            {
                offset += (int)num2;
                count -= (int)num2;
                if (count > 131072)
                {
                    count = 131072;
                }
                eventArgs.SetBuffer(eventArgs.Buffer, offset, count);
            }
            else if (count > 131072)
            {
                count = 131072;
                eventArgs.SetBuffer(eventArgs.Buffer, offset, count);
            }
            uint flags = 0u;
            uint bytesReturned = 0u;
            num = global::Interop.HttpApi.HttpReceiveRequestEntityBody(_inputStream.InternalHttpContext.RequestQueueHandle, _inputStream.InternalHttpContext.RequestId, flags, (void*)_webSocket.InternalBuffer.ToIntPtr(eventArgs.Offset), (uint)eventArgs.Count, out bytesReturned, eventArgs.NativeOverlapped);
            if (num != 0 && num != 997 && num != 38)
            {
                throw new HttpListenerException((int)num);
            }
            if (num == 0 && HttpListener.SkipIOCPCallbackOnSuccess)
            {
                eventArgs.FinishOperationSuccess((int)bytesReturned, syncCompletion: true);
                return false;
            }
            if (num == 38)
            {
                eventArgs.FinishOperationSuccess(0, syncCompletion: true);
                return false;
            }
            return true;
        }
        catch (Exception exception)
        {
            _readEventArgs.FinishOperationFailure(exception, syncCompletion: true);
            _outputStream.SetClosedFlag();
            _outputStream.InternalHttpContext.Abort();
            return true;
        }
    }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream._inputStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._outputStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._readEventArgs, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._webSocket, System.Net.HttpListenerContext.Abort(), System.Net.HttpRequestStream.BufferedDataChunksAvailable, System.Net.HttpRequestStream.Closed, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.exception, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.FinishOperationFailure(), System.Net.HttpRequestStream.GetChunks(), System.Net.WebSockets.WebSocketBase.InternalBuffer, System.Net.HttpRequestStream.InternalHttpContext, System.Net.HttpResponseStream.InternalHttpContext, System.offset, System.Net.HttpListenerContext.RequestId, System.Net.HttpListenerContext.RequestQueueBoundHandle, System.Net.HttpListenerContext.RequestQueueHandle, System.Net.HttpResponseStream.SetClosedFlag(), System.Net.HttpListener.SkipIOCPCallbackOnSuccess, and System.Net.WebSockets.WebSocketBuffer.ToIntPtr().
Referenced by System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncCore().