Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.Dispose
Dispose() [2/2]
override void System.Net.WebSockets.WebSocketHttpListenerDuplexStream.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.Stream.
Definition at line 739 of file WebSocketHttpListenerDuplexStream.cs.
    {
        if (disposing && Interlocked.Exchange(ref _cleanedUp, 1) == 0)
        {
            if (_readTaskCompletionSource != null)
            {
                _readTaskCompletionSource.TrySetCanceled();
            }
            _writeTaskCompletionSource?.TrySetCanceled();
            if (_readEventArgs != null)
            {
                _readEventArgs.Dispose();
            }
            if (_writeEventArgs != null)
            {
                _writeEventArgs.Dispose();
            }
            try
            {
                _inputStream.Close();
            }
            finally
            {
                _outputStream.Close();
            }
        }
    }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream._cleanedUp, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._inputStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._outputStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._readEventArgs, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._readTaskCompletionSource, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._writeEventArgs, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._writeTaskCompletionSource, System.IO.Stream.Close(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Dispose(), System.Threading.Interlocked.Exchange(), and System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetCanceled().