Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncCore
WriteAsyncCore()
async Task System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncCore (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline private
Definition at line 593 of file WebSocketHttpListenerDuplexStream.cs.
    {
        CancellationTokenRegistration cancellationTokenRegistration = default(CancellationTokenRegistration);
        try
        {
            if (cancellationToken.CanBeCanceled)
            {
                cancellationTokenRegistration = cancellationToken.Register(s_OnCancel, this, useSynchronizationContext: false);
            }
            if (!_inOpaqueMode)
            {
                await _outputStream.WriteAsync(buffer, offset, count, cancellationToken).SuppressContextFlow();
                return;
            }
            _writeTaskCompletionSource = new TaskCompletionSource();
            _writeEventArgs.BufferList = null;
            _writeEventArgs.SetBuffer(buffer, offset, count);
            if (WriteAsyncFast(_writeEventArgs))
            {
                await _writeTaskCompletionSource.Task.SuppressContextFlow();
            }
        }
        catch (Exception arg)
        {
            if (s_CanHandleException(arg))
            {
                cancellationToken.ThrowIfCancellationRequested();
            }
            throw;
        }
        finally
        {
            cancellationTokenRegistration.Dispose();
        }
    }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream._inOpaqueMode, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._outputStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._writeEventArgs, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._writeTaskCompletionSource, System.buffer, System.cancellationToken, System.count, System.offset, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.s_CanHandleException, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.s_OnCancel, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.SetBuffer(), System.Threading.Tasks.TaskCompletionSource< TResult >.Task, System.IO.Stream.WriteAsync(), and System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast().
Referenced by System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsync().