Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.CloseNetworkConnectionAsync
CloseNetworkConnectionAsync()
async Task System.Net.WebSockets.WebSocketHttpListenerDuplexStream.CloseNetworkConnectionAsync (CancellationToken cancellationToken) inline
Implements System.Net.WebSockets.WebSocketBase.IWebSocketStream.
Definition at line 708 of file WebSocketHttpListenerDuplexStream.cs.
    {
        await Task.Yield();
        CancellationTokenRegistration cancellationTokenRegistration = default(CancellationTokenRegistration);
        try
        {
            if (cancellationToken.CanBeCanceled)
            {
                cancellationTokenRegistration = cancellationToken.Register(s_OnCancel, this, useSynchronizationContext: false);
            }
            _writeTaskCompletionSource = new TaskCompletionSource();
            _writeEventArgs.SetShouldCloseOutput();
            if (WriteAsyncFast(_writeEventArgs))
            {
                await _writeTaskCompletionSource.Task.SuppressContextFlow();
            }
        }
        catch (Exception arg)
        {
            if (!s_CanHandleException(arg))
            {
                throw;
            }
            cancellationToken.ThrowIfCancellationRequested();
        }
        finally
        {
            cancellationTokenRegistration.Dispose();
        }
    }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream._writeEventArgs, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._writeTaskCompletionSource, System.cancellationToken, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.s_CanHandleException, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.s_OnCancel, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.SetShouldCloseOutput(), System.Threading.Tasks.TaskCompletionSource< TResult >.Task, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast(), and System.Threading.Tasks.Task< TResult >.Yield().