Terraria: System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromNativeInt
GetSecurityStatusPalFromNativeInt()
static SecurityStatusPal System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromNativeInt (int win32SecurityStatus) inline static package
Definition at line 184 of file SecurityStatusAdapterPal.cs.
    {
        return GetSecurityStatusPalFromInterop((global::Interop.SECURITY_STATUS)win32SecurityStatus);
    }
References System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop().
Referenced by System.Net.Security.SslStreamPal.AcceptSecurityContext(), System.Net.Security.SslStreamPal.EncryptMessage(), and System.Net.Security.SslStreamPal.InitializeSecurityContext().