Terraria: Terraria.Chest.CreateChest
CreateChest()
static int Terraria.Chest.CreateChest (int X, int Y, int id = -1) inline static
Definition at line 645 of file Chest.cs.
    {
        int num = id;
        if (num == -1)
        {
            num = FindEmptyChest(X, Y);
            if (num == -1)
            {
                return -1;
            }
            if (Main.netMode == 1)
            {
                return num;
            }
        }
        Main.chest[num] = new Chest();
        Main.chest[num].x = X;
        Main.chest[num].y = Y;
        for (int i = 0; i < 40; i++)
        {
            Main.chest[num].item[i] = new Item();
        }
        return num;
    }
References Terraria.Chest.Chest(), Terraria.Main.chest, Terraria.Chest.FindEmptyChest(), and Terraria.Main.netMode.
Referenced by Terraria.IO.WorldFile.FixDresserChests(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.PlaceChest(), Terraria.WorldGen.PlaceChestDirect(), and Terraria.WorldGen.PlaceDresserDirect().