Terraria: Terraria.Chest.VisualizeChestTransfer
VisualizeChestTransfer()
static void Terraria.Chest.VisualizeChestTransfer (Vector2 position, Vector2 chestPosition, Item item, int amountMoved) inline static
Definition at line 347 of file Chest.cs.
    {
        ParticleOrchestrator.BroadcastOrRequestParticleSpawn(ParticleOrchestraType.ItemTransfer, new ParticleOrchestraSettings
        {
            PositionInWorld = position,
            MovementVector = chestPosition - position,
            UniqueInfoPiece = item.type
        });
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastOrRequestParticleSpawn().
Referenced by Terraria.Chest.PutItemInNearbyChest(), and Terraria.UI.ChestUI.QuickStack().