Terraria: Terraria.Chest.FindChest
FindChest()
static int Terraria.Chest.FindChest (int X, int Y) inline static
Definition at line 546 of file Chest.cs.
    {
        for (int i = 0; i < 8000; i++)
        {
            if (Main.chest[i] != null && Main.chest[i].x == X && Main.chest[i].y == Y)
            {
                return i;
            }
        }
        return -1;
    }
References Terraria.Main.chest.
Referenced by Terraria.Chest.AskForChestToEatItem(), Terraria.NPC.BigMimicSummonCheck(), Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part2(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.Main.DrawMap(), Terraria.Projectile.GasTrapCheck(), Terraria.MessageBuffer.GetData(), Terraria.Player.TileInteractionsCheckLongDistance(), Terraria.Player.TileInteractionsMouseOver(), Terraria.Player.TileInteractionsMouseOver_Containers(), Terraria.Player.TileInteractionsUse(), and Terraria.GameContent.Biomes.DeadMansChestBiome.TurnGoldChestIntoDeadMansChest().