Terraria: System.Net.Security.SafeFreeContextBuffer.QueryContextAttributes
QueryContextAttributes() [1/3]
static unsafe int System.Net.Security.SafeFreeContextBuffer.QueryContextAttributes (SafeDeleteContext phContext, global::Interop::SspiCli::ContextAttribute contextAttribute, byte * buffer, SafeHandle refHandle) inline static
Definition at line 36 of file SafeFreeContextBuffer.cs.
    {
        int num = -2146893055;
        try
        {
            bool success = false;
            phContext.DangerousAddRef(ref success);
            num = global::Interop.SspiCli.QueryContextAttributesW(ref phContext._handle, contextAttribute, buffer);
        }
        finally
        {
            phContext.DangerousRelease();
        }
        if (num == 0 && refHandle != null)
        {
            if (refHandle is SafeFreeContextBuffer)
            {
                ((SafeFreeContextBuffer)refHandle).Set(*(IntPtr*)buffer);
            }
            else
            {
                ((SafeFreeCertContext)refHandle).Set(*(IntPtr*)buffer);
            }
        }
        if (num != 0)
        {
            refHandle?.SetHandleAsInvalid();
        }
        return num;
    }
References System.Net.Security.SafeFreeContextBuffer.SafeFreeContextBuffer(), System.Net.Security.SafeDeleteContext._handle, System.buffer, System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), and System.Runtime.InteropServices.SafeHandle.SetHandleAsInvalid().