Terraria: System.Reflection.Emit.TypeBuilder.GetInterfaces
GetInterfaces()
override Type[] System.Reflection.Emit.TypeBuilder.GetInterfaces () inline
Definition at line 794 of file TypeBuilder.cs.
    {
        if (m_bakedRuntimeType != null)
        {
            return m_bakedRuntimeType.GetInterfaces();
        }
        if (m_typeInterfaces == null)
        {
            return Type.EmptyTypes;
        }
        return m_typeInterfaces.ToArray();
    }
References System.Type.EmptyTypes, System.RuntimeType.GetInterfaces(), System.Reflection.Emit.TypeBuilder.m_bakedRuntimeType, and System.Reflection.Emit.TypeBuilder.m_typeInterfaces.
Referenced by System.Reflection.Emit.EnumBuilder.GetInterfaces(), and System.Reflection.Emit.TypeBuilder.IsAssignableFrom().