Terraria: System.Reflection.Emit.TypeBuilder.CreateTypeInfo
CreateTypeInfo()
TypeInfo? System.Reflection.Emit.TypeBuilder.CreateTypeInfo () inline
Definition at line 1633 of file TypeBuilder.cs.
    {
        lock (SyncRoot)
        {
            return CreateTypeNoLock();
        }
    }
References System.Reflection.Emit.TypeBuilder.CreateTypeNoLock(), and System.Reflection.Emit.TypeBuilder.SyncRoot.
Referenced by System.Reflection.Emit.IgnoreAccessChecksToAttributeBuilder.AddToModule(), System.Xml.Xsl.IlGen.XmlILModule.BakeMethods(), System.Reflection.Emit.EnumBuilder.CreateTypeInfo(), System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateEnd(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd(), System.Xml.Serialization.XmlSerializationILGen.GenerateSerializerContract(), and System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewCustomDelegate().