Terraria: System.Reflection.Emit.TypeBuilder.GetCustomAttributes
GetCustomAttributes() [1/2]
override object[] System.Reflection.Emit.TypeBuilder.GetCustomAttributes (bool inherit) inline
Implements System.Reflection.ICustomAttributeProvider.
Definition at line 1030 of file TypeBuilder.cs.
    {
        if (!IsCreated())
        {
            throw new NotSupportedException(SR.NotSupported_TypeNotYetCreated);
        }
        return CustomAttribute.GetCustomAttributes(m_bakedRuntimeType, typeof(object) as RuntimeType, inherit);
    }
References System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.Emit.TypeBuilder.IsCreated(), System.Reflection.Emit.TypeBuilder.m_bakedRuntimeType, and System.SR.NotSupported_TypeNotYetCreated.
Referenced by System.Reflection.Emit.EnumBuilder.GetCustomAttributes(), and System.Reflection.Emit.EnumBuilder.GetCustomAttributes().