Terraria: System.Reflection.Emit.TypeBuilder.GetEvents
GetEvents() [1/2]
override EventInfo[] System.Reflection.Emit.TypeBuilder.GetEvents () inline virtual
Reimplemented from System.Type.
Definition at line 818 of file TypeBuilder.cs.
    {
        if (!IsCreated())
        {
            throw new NotSupportedException(SR.NotSupported_TypeNotYetCreated);
        }
        return m_bakedRuntimeType.GetEvents();
    }
References System.RuntimeType.GetEvents(), System.Reflection.Emit.TypeBuilder.IsCreated(), System.Reflection.Emit.TypeBuilder.m_bakedRuntimeType, and System.SR.NotSupported_TypeNotYetCreated.
Referenced by System.Reflection.Emit.EnumBuilder.GetEvents(), and System.Reflection.Emit.EnumBuilder.GetEvents().