Terraria: System.Reflection.Emit.TypeBuilder.DefineMethod
DefineMethod() [1/6]
static int System.Reflection.Emit.TypeBuilder.DefineMethod (QCallModule module, int tkParent, string name, byte[] signature, int sigLength, MethodAttributes attributes) package
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Reflection.Emit.IgnoreAccessChecksToAttributeBuilder.AddToModule(), System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Reflection.Emit.ModuleBuilder.DefineGlobalMethodNoLock(), System.Reflection.Emit.TypeBuilder.DefineMethod(), System.Reflection.Emit.TypeBuilder.DefineMethod(), System.Reflection.Emit.TypeBuilder.DefineMethod(), System.Reflection.Emit.TypeBuilder.DefineMethod(), System.Xml.Xsl.IlGen.XmlILModule.DefineMethod(), System.Xml.Serialization.XmlSerializationILGen.EnsureMethodBuilder(), System.Reflection.Emit.MethodBuilder.GetTokenNoLock(), and System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewCustomDelegate().