Terraria: System.Reflection.Emit.TypeBuilder.ThrowIfCreated
ThrowIfCreated()
void System.Reflection.Emit.TypeBuilder.ThrowIfCreated () inline package
Definition at line 658 of file TypeBuilder.cs.
    {
        if (IsCreated())
        {
            throw new InvalidOperationException(SR.InvalidOperation_TypeHasBeenCreated);
        }
    }
References System.SR.InvalidOperation_TypeHasBeenCreated, and System.Reflection.Emit.TypeBuilder.IsCreated().
Referenced by System.Reflection.Emit.TypeBuilder.AddInterfaceImplementation(), System.Reflection.Emit.MethodBuilder.CreateMethodBodyHelper(), System.Reflection.Emit.TypeBuilder.DefineConstructorNoLock(), System.Reflection.Emit.TypeBuilder.DefineDataHelper(), System.Reflection.Emit.TypeBuilder.DefineEventNoLock(), System.Reflection.Emit.TypeBuilder.DefineFieldNoLock(), System.Reflection.Emit.TypeBuilder.DefineMethodNoLock(), System.Reflection.Emit.TypeBuilder.DefineMethodOverrideNoLock(), System.Reflection.Emit.MethodBuilder.DefineParameter(), System.Reflection.Emit.TypeBuilder.DefinePInvokeMethodHelper(), System.Reflection.Emit.TypeBuilder.DefinePropertyNoLock(), System.Reflection.Emit.TypeBuilder.DefineTypeInitializerNoLock(), System.Reflection.Emit.FieldBuilder.SetConstant(), System.Reflection.Emit.PropertyBuilder.SetConstant(), System.Reflection.Emit.EventBuilder.SetCustomAttribute(), System.Reflection.Emit.FieldBuilder.SetCustomAttribute(), System.Reflection.Emit.PropertyBuilder.SetCustomAttribute(), System.Reflection.Emit.EventBuilder.SetCustomAttribute(), System.Reflection.Emit.FieldBuilder.SetCustomAttribute(), System.Reflection.Emit.PropertyBuilder.SetCustomAttribute(), System.Reflection.Emit.MethodBuilder.SetImplementationFlags(), System.Reflection.Emit.TypeBuilder.SetInterfaces(), System.Reflection.Emit.EventBuilder.SetMethodSemantics(), System.Reflection.Emit.PropertyBuilder.SetMethodSemantics(), System.Reflection.Emit.FieldBuilder.SetOffset(), and System.Reflection.Emit.TypeBuilder.SetParent().