Terraria: System.Reflection.Emit.TypeBuilder.DefinePropertyNoLock
DefinePropertyNoLock()
PropertyBuilder System.Reflection.Emit.TypeBuilder.DefinePropertyNoLock (string name, PropertyAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] returnTypeRequiredCustomModifiers, Type[] returnTypeOptionalCustomModifiers, Type[] parameterTypes, Type parameterTypeRequiredCustomModifiers[][], Type parameterTypeOptionalCustomModifiers[][]) inline private
Definition at line 1579 of file TypeBuilder.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (name.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyName, "name");
        }
        AssemblyBuilder.CheckContext(returnType);
        AssemblyBuilder.CheckContext(returnTypeRequiredCustomModifiers, returnTypeOptionalCustomModifiers, parameterTypes);
        AssemblyBuilder.CheckContext(parameterTypeRequiredCustomModifiers);
        AssemblyBuilder.CheckContext(parameterTypeOptionalCustomModifiers);
        ThrowIfCreated();
        SignatureHelper propertySigHelper = SignatureHelper.GetPropertySigHelper(m_module, callingConvention, returnType, returnTypeRequiredCustomModifiers, returnTypeOptionalCustomModifiers, parameterTypes, parameterTypeRequiredCustomModifiers, parameterTypeOptionalCustomModifiers);
        int length;
        byte[] signature = propertySigHelper.InternalGetSignature(out length);
        ModuleBuilder module = m_module;
        int prToken = DefineProperty(new QCallModule(ref module), m_tdType, name, attributes, signature, length);
        return new PropertyBuilder(m_module, name, propertySigHelper, attributes, returnType, prToken, this);
    }
References System.SR.Argument_EmptyName, System.Reflection.Emit.AssemblyBuilder.CheckContext(), System.Reflection.Emit.TypeBuilder.DefineProperty(), System.Reflection.Emit.SignatureHelper.GetPropertySigHelper(), System.length, System.Reflection.Emit.TypeBuilder.m_module, System.Reflection.Emit.TypeBuilder.m_tdType, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().
Referenced by System.Reflection.Emit.TypeBuilder.DefineProperty().