Terraria: System.Reflection.Emit.TypeBuilder.AddInterfaceImplementation
AddInterfaceImplementation()
void System.Reflection.Emit.TypeBuilder.AddInterfaceImplementation ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type interfaceType) inline
Definition at line 1806 of file TypeBuilder.cs.
    {
        if (interfaceType == null)
        {
            throw new ArgumentNullException("interfaceType");
        }
        AssemblyBuilder.CheckContext(interfaceType);
        ThrowIfCreated();
        int typeTokenInternal = m_module.GetTypeTokenInternal(interfaceType);
        ModuleBuilder module = m_module;
        AddInterfaceImpl(new QCallModule(ref module), m_tdType, typeTokenInternal);
        m_typeInterfaces.Add(interfaceType);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Emit.TypeBuilder.AddInterfaceImpl(), System.Reflection.Emit.AssemblyBuilder.CheckContext(), System.Reflection.Emit.ModuleBuilder.GetTypeTokenInternal(), System.Reflection.Emit.TypeBuilder.m_module, System.Reflection.Emit.TypeBuilder.m_tdType, System.Reflection.Emit.TypeBuilder.m_typeInterfaces, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddInterfaceImpl().