Terraria: System.Reflection.Emit.TypeBuilder.SetCustomAttribute
SetCustomAttribute() [1/2]
void System.Reflection.Emit.TypeBuilder.SetCustomAttribute (ConstructorInfo con, byte[] binaryAttribute) inline
Definition at line 1820 of file TypeBuilder.cs.
    {
        if (con == null)
        {
            throw new ArgumentNullException("con");
        }
        if (binaryAttribute == null)
        {
            throw new ArgumentNullException("binaryAttribute");
        }
        DefineCustomAttribute(m_module, m_tdType, m_module.GetConstructorToken(con), binaryAttribute);
    }
References System.Reflection.Emit.TypeBuilder.DefineCustomAttribute(), System.Reflection.Emit.ModuleBuilder.GetConstructorToken(), System.Reflection.Emit.TypeBuilder.m_module, and System.Reflection.Emit.TypeBuilder.m_tdType.
Referenced by System.Reflection.Emit.IgnoreAccessChecksToAttributeBuilder.AddToModule(), System.Reflection.Emit.EnumBuilder.SetCustomAttribute(), and System.Reflection.Emit.EnumBuilder.SetCustomAttribute().