Terraria: System.Reflection.Emit.TypeBuilder.DefineFieldNoLock
DefineFieldNoLock()
FieldBuilder System.Reflection.Emit.TypeBuilder.DefineFieldNoLock (string fieldName, Type type, Type[] requiredCustomModifiers, Type[] optionalCustomModifiers, FieldAttributes attributes) inline private
Definition at line 1514 of file TypeBuilder.cs.
    {
        ThrowIfCreated();
        AssemblyBuilder.CheckContext(type);
        AssemblyBuilder.CheckContext(requiredCustomModifiers);
        if (m_enumUnderlyingType == null && IsEnum && (attributes & FieldAttributes.Static) == 0)
        {
            m_enumUnderlyingType = type;
        }
        return new FieldBuilder(this, fieldName, type, requiredCustomModifiers, optionalCustomModifiers, attributes);
    }
References System.Reflection.Emit.AssemblyBuilder.CheckContext(), System.Type.IsEnum, System.Reflection.Emit.TypeBuilder.m_enumUnderlyingType, System.Reflection.Emit.TypeBuilder.ThrowIfCreated(), and System.type.
Referenced by System.Reflection.Emit.TypeBuilder.DefineField().