Terraria: System.Reflection.Emit.TypeBuilder.IsTypeEqual
IsTypeEqual()
static bool System.Reflection.Emit.TypeBuilder.IsTypeEqual (Type t1, Type t2) inline static package
Definition at line 371 of file TypeBuilder.cs.
    {
        if (t1 == t2)
        {
            return true;
        }
        TypeBuilder typeBuilder = null;
        TypeBuilder typeBuilder2 = null;
        Type type;
        if (t1 is TypeBuilder)
        {
            typeBuilder = (TypeBuilder)t1;
            type = typeBuilder.m_bakedRuntimeType;
        }
        else
        {
            type = t1;
        }
        Type type2;
        if (t2 is TypeBuilder)
        {
            typeBuilder2 = (TypeBuilder)t2;
            type2 = typeBuilder2.m_bakedRuntimeType;
        }
        else
        {
            type2 = t2;
        }
        if (typeBuilder != null && typeBuilder2 != null && (object)typeBuilder == typeBuilder2)
        {
            return true;
        }
        if (type != null && type2 != null && type == type2)
        {
            return true;
        }
        return false;
    }
References System.Reflection.Emit.TypeBuilder.TypeBuilder(), System.Reflection.Emit.TypeBuilder.m_bakedRuntimeType, and System.type.
Referenced by System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder(), System.Reflection.Emit.TypeBuilder.IsAssignableFrom(), and System.Reflection.Emit.TypeBuilder.IsSubclassOf().