Terraria: System.Reflection.Emit.TypeBuilder.IsAssignableFrom
IsAssignableFrom() [1/2]
override bool System.Reflection.Emit.TypeBuilder.IsAssignableFrom ([NotNullWhen(true)] Type? c) inline virtual
Reimplemented from System.Type.
Definition at line 903 of file TypeBuilder.cs.
    {
        if (IsTypeEqual(c, this))
        {
            return true;
        }
        TypeBuilder typeBuilder = c as TypeBuilder;
        Type type = ((!(typeBuilder != null)) ? c : typeBuilder.m_bakedRuntimeType);
        if (type != null && type is RuntimeType)
        {
            if (m_bakedRuntimeType == null)
            {
                return false;
            }
            return m_bakedRuntimeType.IsAssignableFrom(type);
        }
        if (typeBuilder == null)
        {
            return false;
        }
        if (typeBuilder.IsSubclassOf(this))
        {
            return true;
        }
        if (!base.IsInterface)
        {
            return false;
        }
        Type[] interfaces = typeBuilder.GetInterfaces();
        for (int i = 0; i < interfaces.Length; i++)
        {
            if (IsTypeEqual(interfaces[i], this))
            {
                return true;
            }
            if (interfaces[i].IsSubclassOf(this))
            {
                return true;
            }
        }
        return false;
    }
References System.Reflection.Emit.TypeBuilder.TypeBuilder(), System.Reflection.Emit.TypeBuilder.GetInterfaces(), System.RuntimeType.IsAssignableFrom(), System.Reflection.Emit.TypeBuilder.IsSubclassOf(), System.Reflection.Emit.TypeBuilder.IsTypeEqual(), System.Reflection.Emit.TypeBuilder.m_bakedRuntimeType, and System.type.