Terraria: System.Reflection.Emit.TypeBuilder.DefineMethodOverrideNoLock
DefineMethodOverrideNoLock()
void System.Reflection.Emit.TypeBuilder.DefineMethodOverrideNoLock (MethodInfo methodInfoBody, MethodInfo methodInfoDeclaration) inline private
Definition at line 1148 of file TypeBuilder.cs.
    {
        if (methodInfoBody == null)
        {
            throw new ArgumentNullException("methodInfoBody");
        }
        if (methodInfoDeclaration == null)
        {
            throw new ArgumentNullException("methodInfoDeclaration");
        }
        ThrowIfCreated();
        if ((object)methodInfoBody.DeclaringType != this)
        {
            throw new ArgumentException(SR.ArgumentException_BadMethodImplBody);
        }
        int methodToken = m_module.GetMethodToken(methodInfoBody);
        int methodToken2 = m_module.GetMethodToken(methodInfoDeclaration);
        ModuleBuilder module = m_module;
        DefineMethodImpl(new QCallModule(ref module), m_tdType, methodToken, methodToken2);
    }
References System.SR.ArgumentException_BadMethodImplBody, System.Reflection.Emit.TypeBuilder.DefineMethodImpl(), System.Reflection.Emit.ModuleBuilder.GetMethodToken(), System.Reflection.Emit.TypeBuilder.m_module, System.Reflection.Emit.TypeBuilder.m_tdType, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().
Referenced by System.Reflection.Emit.TypeBuilder.DefineMethodOverride().