Terraria: System.Reflection.Emit.TypeBuilder.DefineMethodNoLock
DefineMethodNoLock()
MethodBuilder System.Reflection.Emit.TypeBuilder.DefineMethodNoLock (string name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] returnTypeRequiredCustomModifiers, Type[] returnTypeOptionalCustomModifiers, Type[] parameterTypes, Type parameterTypeRequiredCustomModifiers[][], Type parameterTypeOptionalCustomModifiers[][]) inline private
Definition at line 1198 of file TypeBuilder.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (name.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyName, "name");
        }
        AssemblyBuilder.CheckContext(returnType);
        AssemblyBuilder.CheckContext(returnTypeRequiredCustomModifiers, returnTypeOptionalCustomModifiers, parameterTypes);
        AssemblyBuilder.CheckContext(parameterTypeRequiredCustomModifiers);
        AssemblyBuilder.CheckContext(parameterTypeOptionalCustomModifiers);
        if (parameterTypes != null)
        {
            if (parameterTypeOptionalCustomModifiers != null && parameterTypeOptionalCustomModifiers.Length != parameterTypes.Length)
            {
                throw new ArgumentException(SR.Format(SR.Argument_MismatchedArrays, "parameterTypeOptionalCustomModifiers", "parameterTypes"));
            }
            if (parameterTypeRequiredCustomModifiers != null && parameterTypeRequiredCustomModifiers.Length != parameterTypes.Length)
            {
                throw new ArgumentException(SR.Format(SR.Argument_MismatchedArrays, "parameterTypeRequiredCustomModifiers", "parameterTypes"));
            }
        }
        ThrowIfCreated();
        MethodBuilder methodBuilder = new MethodBuilder(name, attributes, callingConvention, returnType, returnTypeRequiredCustomModifiers, returnTypeOptionalCustomModifiers, parameterTypes, parameterTypeRequiredCustomModifiers, parameterTypeOptionalCustomModifiers, m_module, this);
        if (!m_isHiddenGlobalType && (methodBuilder.Attributes & MethodAttributes.SpecialName) != 0 && methodBuilder.Name.Equals(ConstructorInfo.ConstructorName))
        {
            m_constructorCount++;
        }
        m_listMethods.Add(methodBuilder);
        return methodBuilder;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.SR.Argument_EmptyName, System.SR.Argument_MismatchedArrays, System.Reflection.Emit.AssemblyBuilder.CheckContext(), System.Reflection.ConstructorInfo.ConstructorName, System.SR.Format(), System.Reflection.Emit.TypeBuilder.m_constructorCount, System.Reflection.Emit.TypeBuilder.m_isHiddenGlobalType, System.Reflection.Emit.TypeBuilder.m_listMethods, System.Reflection.Emit.TypeBuilder.m_module, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().
Referenced by System.Reflection.Emit.TypeBuilder.DefineMethod().