Terraria: System.Reflection.Emit.TypeBuilder.SetInterfaces
SetInterfaces()
void System.Reflection.Emit.TypeBuilder.SetInterfaces (params Type[] interfaces) inline package
Definition at line 1075 of file TypeBuilder.cs.
    {
        ThrowIfCreated();
        m_typeInterfaces = new List<Type>();
        if (interfaces != null)
        {
            m_typeInterfaces.AddRange(interfaces);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), System.Reflection.Emit.TypeBuilder.m_typeInterfaces, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().
Referenced by System.Reflection.Emit.TypeBuilder.TypeBuilder(), and System.Reflection.Emit.GenericTypeParameterBuilder.SetInterfaceConstraints().