Terraria: System.Reflection.Emit.TypeBuilder.DefinePInvokeMethodHelper
DefinePInvokeMethodHelper()
MethodBuilder System.Reflection.Emit.TypeBuilder.DefinePInvokeMethodHelper (string name, string dllName, string importName, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] returnTypeRequiredCustomModifiers, Type[] returnTypeOptionalCustomModifiers, Type[] parameterTypes, Type parameterTypeRequiredCustomModifiers[][], Type parameterTypeOptionalCustomModifiers[][], CallingConvention nativeCallConv, CharSet nativeCharSet) inline private
Definition at line 1252 of file TypeBuilder.cs.
    {
        AssemblyBuilder.CheckContext(returnType);
        AssemblyBuilder.CheckContext(returnTypeRequiredCustomModifiers, returnTypeOptionalCustomModifiers, parameterTypes);
        AssemblyBuilder.CheckContext(parameterTypeRequiredCustomModifiers);
        AssemblyBuilder.CheckContext(parameterTypeOptionalCustomModifiers);
        lock (SyncRoot)
        {
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            if (name.Length == 0)
            {
                throw new ArgumentException(SR.Argument_EmptyName, "name");
            }
            if (dllName == null)
            {
                throw new ArgumentNullException("dllName");
            }
            if (dllName.Length == 0)
            {
                throw new ArgumentException(SR.Argument_EmptyName, "dllName");
            }
            if (importName == null)
            {
                throw new ArgumentNullException("importName");
            }
            if (importName.Length == 0)
            {
                throw new ArgumentException(SR.Argument_EmptyName, "importName");
            }
            if ((attributes & MethodAttributes.Abstract) != 0)
            {
                throw new ArgumentException(SR.Argument_BadPInvokeMethod);
            }
            if ((m_iAttr & TypeAttributes.ClassSemanticsMask) == TypeAttributes.ClassSemanticsMask)
            {
                throw new ArgumentException(SR.Argument_BadPInvokeOnInterface);
            }
            ThrowIfCreated();
            attributes |= MethodAttributes.PinvokeImpl;
            MethodBuilder methodBuilder = new MethodBuilder(name, attributes, callingConvention, returnType, returnTypeRequiredCustomModifiers, returnTypeOptionalCustomModifiers, parameterTypes, parameterTypeRequiredCustomModifiers, parameterTypeOptionalCustomModifiers, m_module, this);
            methodBuilder.GetMethodSignature().InternalGetSignature(out var _);
            if (m_listMethods.Contains(methodBuilder))
            {
                throw new ArgumentException(SR.Argument_MethodRedefined);
            }
            m_listMethods.Add(methodBuilder);
            int metadataToken = methodBuilder.MetadataToken;
            int num = 0;
            switch (nativeCallConv)
            {
            case CallingConvention.Winapi:
                num = 256;
                break;
            case CallingConvention.Cdecl:
                num = 512;
                break;
            case CallingConvention.StdCall:
                num = 768;
                break;
            case CallingConvention.ThisCall:
                num = 1024;
                break;
            case CallingConvention.FastCall:
                num = 1280;
                break;
            }
            switch (nativeCharSet)
            {
            case CharSet.None:
                num |= 0;
                break;
            case CharSet.Ansi:
                num |= 2;
                break;
            case CharSet.Unicode:
                num |= 4;
                break;
            case CharSet.Auto:
                num |= 6;
                break;
            }
            ModuleBuilder module = m_module;
            SetPInvokeData(new QCallModule(ref module), dllName, importName, metadataToken, num);
            methodBuilder.SetToken(metadataToken);
            return methodBuilder;
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.SR.Argument_BadPInvokeMethod, System.SR.Argument_BadPInvokeOnInterface, System.SR.Argument_EmptyName, System.SR.Argument_MethodRedefined, System.Reflection.Emit.AssemblyBuilder.CheckContext(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Reflection.Emit.TypeBuilder.m_iAttr, System.Reflection.Emit.TypeBuilder.m_listMethods, System.Reflection.Emit.TypeBuilder.m_module, System.Reflection.Emit.TypeBuilder.SetPInvokeData(), System.Reflection.Emit.TypeBuilder.SyncRoot, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().
Referenced by System.Reflection.Emit.TypeBuilder.DefinePInvokeMethod(), System.Reflection.Emit.TypeBuilder.DefinePInvokeMethod(), and System.Reflection.Emit.TypeBuilder.DefinePInvokeMethod().