Terraria: System.Reflection.Emit.TypeBuilder.DefineEventNoLock
DefineEventNoLock()
EventBuilder System.Reflection.Emit.TypeBuilder.DefineEventNoLock (string name, EventAttributes attributes, Type eventtype) inline private
Definition at line 1610 of file TypeBuilder.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (name.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyName, "name");
        }
        if (name[0] == '\0')
        {
            throw new ArgumentException(SR.Argument_IllegalName, "name");
        }
        AssemblyBuilder.CheckContext(eventtype);
        ThrowIfCreated();
        int typeTokenInternal = m_module.GetTypeTokenInternal(eventtype);
        ModuleBuilder module = m_module;
        int evToken = DefineEvent(new QCallModule(ref module), m_tdType, name, attributes, typeTokenInternal);
        return new EventBuilder(m_module, name, attributes, this, evToken);
    }
References System.SR.Argument_EmptyName, System.SR.Argument_IllegalName, System.Reflection.Emit.AssemblyBuilder.CheckContext(), System.Reflection.Emit.TypeBuilder.DefineEvent(), System.Reflection.Emit.ModuleBuilder.GetTypeTokenInternal(), System.Reflection.Emit.TypeBuilder.m_module, System.Reflection.Emit.TypeBuilder.m_tdType, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().
Referenced by System.Reflection.Emit.TypeBuilder.DefineEvent().