Terraria: System.Reflection.Emit.TypeBuilder.DefineDataHelper
DefineDataHelper()
FieldBuilder System.Reflection.Emit.TypeBuilder.DefineDataHelper (string name, byte[] data, int size, FieldAttributes attributes) inline private
Definition at line 592 of file TypeBuilder.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (name.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyName, "name");
        }
        if (size <= 0 || size >= 4128768)
        {
            throw new ArgumentException(SR.Argument_BadSizeForData);
        }
        ThrowIfCreated();
        string text = "$ArrayType$" + size;
        Type type = m_module.FindTypeBuilderWithName(text, ignoreCase: false);
        TypeBuilder typeBuilder = type as TypeBuilder;
        if (typeBuilder == null)
        {
            TypeAttributes attr = TypeAttributes.Public | TypeAttributes.ExplicitLayout | TypeAttributes.Sealed;
            typeBuilder = m_module.DefineType(text, attr, typeof(ValueType), PackingSize.Size1, size);
            typeBuilder.CreateType();
        }
        FieldBuilder fieldBuilder = DefineField(name, typeBuilder, attributes | FieldAttributes.Static);
        fieldBuilder.SetData(data, size);
        return fieldBuilder;
    }
References System.Reflection.Emit.TypeBuilder.TypeBuilder(), System.SR.Argument_BadSizeForData, System.SR.Argument_EmptyName, System.Reflection.Emit.TypeBuilder.CreateType(), System.Reflection.Emit.TypeBuilder.DefineField(), System.Reflection.Emit.ModuleBuilder.DefineType(), System.Reflection.Emit.ModuleBuilder.FindTypeBuilderWithName(), System.Reflection.Emit.TypeBuilder.m_module, System.text, System.Reflection.Emit.TypeBuilder.ThrowIfCreated(), and System.type.
Referenced by System.Reflection.Emit.TypeBuilder.DefineInitializedDataNoLock(), and System.Reflection.Emit.TypeBuilder.DefineUninitializedDataNoLock().