Terraria: System.Reflection.Emit.TypeBuilder.DefineDefaultConstructorNoLock
DefineDefaultConstructorNoLock()
ConstructorBuilder System.Reflection.Emit.TypeBuilder.DefineDefaultConstructorNoLock (MethodAttributes attributes) inline private
Definition at line 1372 of file TypeBuilder.cs.
    {
        ConstructorInfo constructorInfo = null;
        if (m_typeParent is TypeBuilderInstantiation)
        {
            Type type = m_typeParent.GetGenericTypeDefinition();
            if (type is TypeBuilder)
            {
                type = ((TypeBuilder)type).m_bakedRuntimeType;
            }
            if (type == null)
            {
                throw new NotSupportedException(SR.NotSupported_DynamicModule);
            }
            Type type2 = type.MakeGenericType(m_typeParent.GetGenericArguments());
            constructorInfo = ((!(type2 is TypeBuilderInstantiation)) ? type2.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, Type.EmptyTypes, null) : GetConstructor(type2, type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, Type.EmptyTypes, null)));
        }
        if (constructorInfo == null)
        {
            constructorInfo = m_typeParent.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, Type.EmptyTypes, null);
        }
        if (constructorInfo == null)
        {
            throw new NotSupportedException(SR.NotSupported_NoParentDefaultConstructor);
        }
        ConstructorBuilder constructorBuilder = DefineConstructor(attributes, CallingConventions.Standard, null);
        m_constructorCount++;
        ILGenerator iLGenerator = constructorBuilder.GetILGenerator();
        iLGenerator.Emit(OpCodes.Ldarg_0);
        iLGenerator.Emit(OpCodes.Call, constructorInfo);
        iLGenerator.Emit(OpCodes.Ret);
        constructorBuilder.m_isDefaultConstructor = true;
        return constructorBuilder;
    }
References System.Reflection.Emit.TypeBuilder.TypeBuilder(), System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.TypeBuilder.DefineConstructor(), System.Type.EmptyTypes, System.Reflection.Emit.TypeBuilder.GetConstructor(), System.Type.GetConstructor(), System.Type.GetGenericArguments(), System.Type.GetGenericTypeDefinition(), System.Reflection.Emit.OpCodes.Ldarg_0, System.Reflection.Emit.TypeBuilder.m_constructorCount, System.Reflection.Emit.TypeBuilder.m_typeParent, System.SR.NotSupported_DynamicModule, System.SR.NotSupported_NoParentDefaultConstructor, System.Reflection.Emit.OpCodes.Ret, and System.type.
Referenced by System.Reflection.Emit.TypeBuilder.DefineDefaultConstructor().