Terraria: System.Reflection.Emit.TypeBuilder.TypeBuilder
TypeBuilder() [4/4]
System.Reflection.Emit.TypeBuilder.TypeBuilder (string fullname, TypeAttributes attr, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, int iTypeSize, TypeBuilder enclosingType) inline package
Definition at line 513 of file TypeBuilder.cs.
    {
        if (fullname == null)
        {
            throw new ArgumentNullException("fullname");
        }
        if (fullname.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyName, "fullname");
        }
        if (fullname[0] == '\0')
        {
            throw new ArgumentException(SR.Argument_IllegalName, "fullname");
        }
        if (fullname.Length > 1023)
        {
            throw new ArgumentException(SR.Argument_TypeNameTooLong, "fullname");
        }
        m_module = module;
        m_DeclaringType = enclosingType;
        AssemblyBuilder containingAssemblyBuilder = m_module.ContainingAssemblyBuilder;
        containingAssemblyBuilder._assemblyData.CheckTypeNameConflict(fullname, enclosingType);
        if (enclosingType != null && ((attr & TypeAttributes.VisibilityMask) == TypeAttributes.Public || (attr & TypeAttributes.VisibilityMask) == 0))
        {
            throw new ArgumentException(SR.Argument_BadNestedTypeFlags, "attr");
        }
        int[] array = null;
        if (interfaces != null)
        {
            for (int i = 0; i < interfaces.Length; i++)
            {
                if (interfaces[i] == null)
                {
                    throw new ArgumentNullException("interfaces");
                }
            }
            array = new int[interfaces.Length + 1];
            for (int i = 0; i < interfaces.Length; i++)
            {
                array[i] = m_module.GetTypeTokenInternal(interfaces[i]);
            }
        }
        int num = fullname.LastIndexOf('.');
        if (num == -1 || num == 0)
        {
            m_strNameSpace = string.Empty;
            m_strName = fullname;
        }
        else
        {
            m_strNameSpace = fullname.Substring(0, num);
            m_strName = fullname.Substring(num + 1);
        }
        VerifyTypeAttributes(attr);
        m_iAttr = attr;
        SetParent(parent);
        m_listMethods = new List<MethodBuilder>();
        m_lastTokenizedMethod = -1;
        SetInterfaces(interfaces);
        int tkParent = 0;
        if (m_typeParent != null)
        {
            tkParent = m_module.GetTypeTokenInternal(m_typeParent);
        }
        int tkEnclosingType = 0;
        if (enclosingType != null)
        {
            tkEnclosingType = enclosingType.m_tdType;
        }
        m_tdType = DefineType(new QCallModule(ref module), fullname, tkParent, m_iAttr, tkEnclosingType, array);
        m_iPackingSize = iPackingSize;
        m_iTypeSize = iTypeSize;
        if (m_iPackingSize != 0 || m_iTypeSize != 0)
        {
            SetClassLayout(new QCallModule(ref module), m_tdType, m_iPackingSize, m_iTypeSize);
        }
        m_module.AddType(FullName, this);
    }
References System.Reflection.Emit.ModuleBuilder.AddType(), System.SR.Argument_BadNestedTypeFlags, System.SR.Argument_EmptyName, System.SR.Argument_IllegalName, System.SR.Argument_TypeNameTooLong, System.array, System.Reflection.Emit.ModuleBuilder.ContainingAssemblyBuilder, System.Reflection.Emit.TypeBuilder.DefineType(), System.Reflection.Emit.TypeBuilder.FullName, System.Reflection.Emit.ModuleBuilder.GetTypeTokenInternal(), System.Reflection.Emit.TypeBuilder.m_DeclaringType, System.Reflection.Emit.TypeBuilder.m_iAttr, System.Reflection.Emit.TypeBuilder.m_iPackingSize, System.Reflection.Emit.TypeBuilder.m_iTypeSize, System.Reflection.Emit.TypeBuilder.m_lastTokenizedMethod, System.Reflection.Emit.TypeBuilder.m_listMethods, System.Reflection.Emit.TypeBuilder.m_module, System.Reflection.Emit.TypeBuilder.m_strName, System.Reflection.Emit.TypeBuilder.m_strNameSpace, System.Reflection.Emit.TypeBuilder.m_tdType, System.Reflection.Emit.TypeBuilder.m_typeParent, System.Reflection.Emit.TypeBuilder.SetClassLayout(), System.Reflection.Emit.TypeBuilder.SetInterfaces(), System.Reflection.Emit.TypeBuilder.SetParent(), and System.Reflection.Emit.TypeBuilder.VerifyTypeAttributes().