Terraria: System.Reflection.Emit.TypeBuilder.CreateTypeNoLock
CreateTypeNoLock()
TypeInfo System.Reflection.Emit.TypeBuilder.CreateTypeNoLock () inline private
Definition at line 1652 of file TypeBuilder.cs.
    {
        if (IsCreated())
        {
            return m_bakedRuntimeType;
        }
        if (m_typeInterfaces == null)
        {
            m_typeInterfaces = new List<Type>();
        }
        int[] array = new int[m_typeInterfaces.Count];
        for (int i = 0; i < m_typeInterfaces.Count; i++)
        {
            array[i] = m_module.GetTypeTokenInternal(m_typeInterfaces[i]);
        }
        int num = 0;
        if (m_typeParent != null)
        {
            num = m_module.GetTypeTokenInternal(m_typeParent);
        }
        ModuleBuilder module = m_module;
        if (IsGenericParameter)
        {
            int[] array2;
            if (m_typeParent != null)
            {
                array2 = new int[m_typeInterfaces.Count + 2];
                array2[^2] = num;
            }
            else
            {
                array2 = new int[m_typeInterfaces.Count + 1];
            }
            for (int j = 0; j < m_typeInterfaces.Count; j++)
            {
                array2[j] = m_module.GetTypeTokenInternal(m_typeInterfaces[j]);
            }
            int tkParent = ((m_declMeth == null) ? m_DeclaringType.m_tdType : m_declMeth.MetadataToken);
            m_tdType = DefineGenericParam(new QCallModule(ref module), m_strName, tkParent, m_genParamAttributes, m_genParamPos, array2);
            if (m_ca != null)
            {
                foreach (CustAttr item in m_ca)
                {
                    item.Bake(m_module, MetadataToken);
                }
            }
            m_hasBeenCreated = true;
            return this;
        }
        if (((uint)m_tdType & 0xFFFFFFu) != 0 && ((uint)num & 0xFFFFFFu) != 0)
        {
            SetParentType(new QCallModule(ref module), m_tdType, num);
        }
        if (m_inst != null)
        {
            GenericTypeParameterBuilder[] inst = m_inst;
            foreach (GenericTypeParameterBuilder genericTypeParameterBuilder in inst)
            {
                genericTypeParameterBuilder.m_type.CreateType();
            }
        }
        if (!m_isHiddenGlobalType && m_constructorCount == 0 && (m_iAttr & TypeAttributes.ClassSemanticsMask) == 0 && !base.IsValueType && (m_iAttr & (TypeAttributes.Abstract | TypeAttributes.Sealed)) != (TypeAttributes.Abstract | TypeAttributes.Sealed))
        {
            DefineDefaultConstructor(MethodAttributes.Public);
        }
        int count = m_listMethods.Count;
        for (int l = 0; l < count; l++)
        {
            MethodBuilder methodBuilder = m_listMethods[l];
            if (methodBuilder.IsGenericMethodDefinition)
            {
                int metadataToken = methodBuilder.MetadataToken;
            }
            MethodAttributes attributes = methodBuilder.Attributes;
            if ((methodBuilder.GetMethodImplementationFlags() & (MethodImplAttributes)135) != 0 || (attributes & MethodAttributes.PinvokeImpl) != 0)
            {
                continue;
            }
            int signatureLength;
            byte[] localSignature = methodBuilder.GetLocalSignature(out signatureLength);
            if ((attributes & MethodAttributes.Abstract) != 0 && (m_iAttr & TypeAttributes.Abstract) == 0)
            {
                throw new InvalidOperationException(SR.InvalidOperation_BadTypeAttributesNotAbstract);
            }
            byte[] body = methodBuilder.GetBody();
            if ((attributes & MethodAttributes.Abstract) != 0)
            {
                if (body != null)
                {
                    throw new InvalidOperationException(SR.Format(SR.InvalidOperation_BadMethodBody, methodBuilder.Name));
                }
            }
            else if (body == null || body.Length == 0)
            {
                if (methodBuilder.m_ilGenerator != null)
                {
                    methodBuilder.CreateMethodBodyHelper(methodBuilder.GetILGenerator());
                }
                body = methodBuilder.GetBody();
                if ((body == null || body.Length == 0) && !methodBuilder.m_canBeRuntimeImpl)
                {
                    throw new InvalidOperationException(SR.Format(SR.InvalidOperation_BadEmptyMethodBody, methodBuilder.Name));
                }
            }
            int maxStack = methodBuilder.GetMaxStack();
            ExceptionHandler[] exceptionHandlers = methodBuilder.GetExceptionHandlers();
            int[] tokenFixups = methodBuilder.GetTokenFixups();
            SetMethodIL(new QCallModule(ref module), methodBuilder.MetadataToken, methodBuilder.InitLocals, body, (body != null) ? body.Length : 0, localSignature, signatureLength, maxStack, exceptionHandlers, (exceptionHandlers != null) ? exceptionHandlers.Length : 0, tokenFixups, (tokenFixups != null) ? tokenFixups.Length : 0);
            if (m_module.ContainingAssemblyBuilder._assemblyData._access == AssemblyBuilderAccess.Run)
            {
                methodBuilder.ReleaseBakedStructures();
            }
        }
        m_hasBeenCreated = true;
        RuntimeType o = null;
        TermCreateClass(new QCallModule(ref module), m_tdType, ObjectHandleOnStack.Create(ref o));
        if (!m_isHiddenGlobalType)
        {
            m_bakedRuntimeType = o;
            if (m_DeclaringType != null && m_DeclaringType.m_bakedRuntimeType != null)
            {
                m_DeclaringType.m_bakedRuntimeType.InvalidateCachedNestedType();
            }
            return o;
        }
        return null;
    }
References System.Reflection.Emit.AssemblyBuilderData._access, System.Reflection.Emit.AssemblyBuilder._assemblyData, System.array, System.Reflection.Emit.ModuleBuilder.ContainingAssemblyBuilder, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Emit.TypeBuilder.DefineDefaultConstructor(), System.Reflection.Emit.TypeBuilder.DefineGenericParam(), System.SR.Format(), System.Reflection.Emit.ModuleBuilder.GetTypeTokenInternal(), System.RuntimeType.InvalidateCachedNestedType(), System.SR.InvalidOperation_BadEmptyMethodBody, System.SR.InvalidOperation_BadMethodBody, System.SR.InvalidOperation_BadTypeAttributesNotAbstract, System.Reflection.Emit.TypeBuilder.IsCreated(), System.Reflection.Emit.TypeBuilder.IsGenericParameter, System.item, System.Reflection.Emit.TypeBuilder.m_bakedRuntimeType, System.Reflection.Emit.TypeBuilder.m_ca, System.Reflection.Emit.TypeBuilder.m_constructorCount, System.Reflection.Emit.TypeBuilder.m_DeclaringType, System.Reflection.Emit.TypeBuilder.m_declMeth, System.Reflection.Emit.TypeBuilder.m_genParamAttributes, System.Reflection.Emit.TypeBuilder.m_genParamPos, System.Reflection.Emit.TypeBuilder.m_hasBeenCreated, System.Reflection.Emit.TypeBuilder.m_iAttr, System.Reflection.Emit.TypeBuilder.m_inst, System.Reflection.Emit.TypeBuilder.m_isHiddenGlobalType, System.Reflection.Emit.TypeBuilder.m_listMethods, System.Reflection.Emit.TypeBuilder.m_module, System.Reflection.Emit.TypeBuilder.m_strName, System.Reflection.Emit.TypeBuilder.m_tdType, System.Reflection.Emit.TypeBuilder.m_typeInterfaces, System.Reflection.Emit.TypeBuilder.m_typeParent, System.Reflection.Emit.MethodBuilder.MetadataToken, System.Reflection.Emit.TypeBuilder.SetMethodIL(), System.Reflection.Emit.TypeBuilder.SetParentType(), and System.Reflection.Emit.TypeBuilder.TermCreateClass().
Referenced by System.Reflection.Emit.TypeBuilder.CreateType(), and System.Reflection.Emit.TypeBuilder.CreateTypeInfo().