Terraria: System.Reflection.Emit.TypeBuilder.SetConstantValue
SetConstantValue() [1/2]
static unsafe void System.Reflection.Emit.TypeBuilder.SetConstantValue (ModuleBuilder module, int tk, Type destType, object value) inline static package
Definition at line 410 of file TypeBuilder.cs.
    {
        if (value != null)
        {
            Type type = value.GetType();
            if (destType.IsByRef)
            {
                destType = destType.GetElementType();
            }
            destType = Nullable.GetUnderlyingType(destType) ?? destType;
            if (destType.IsEnum)
            {
                Type type2;
                if (destType is EnumBuilder enumBuilder)
                {
                    type2 = enumBuilder.GetEnumUnderlyingType();
                    if (type != enumBuilder.m_typeBuilder.m_bakedRuntimeType && type != type2)
                    {
                        throw new ArgumentException(SR.Argument_ConstantDoesntMatch);
                    }
                }
                else if (destType is TypeBuilder typeBuilder)
                {
                    type2 = typeBuilder.m_enumUnderlyingType;
                    if (type2 == null || (type != typeBuilder.UnderlyingSystemType && type != type2))
                    {
                        throw new ArgumentException(SR.Argument_ConstantDoesntMatch);
                    }
                }
                else
                {
                    type2 = Enum.GetUnderlyingType(destType);
                    if (type != destType && type != type2)
                    {
                        throw new ArgumentException(SR.Argument_ConstantDoesntMatch);
                    }
                }
                type = type2;
            }
            else if (!destType.IsAssignableFrom(type))
            {
                throw new ArgumentException(SR.Argument_ConstantDoesntMatch);
            }
            CorElementType corElementType = RuntimeTypeHandle.GetCorElementType((RuntimeType)type);
            if (corElementType - 2 <= CorElementType.ELEMENT_TYPE_U8)
            {
                fixed (byte* pValue = &value.GetRawData())
                {
                    SetConstantValue(new QCallModule(ref module), tk, (int)corElementType, pValue);
                }
                return;
            }
            if (type == typeof(string))
            {
                fixed (char* pValue2 = (string)value)
                {
                    SetConstantValue(new QCallModule(ref module), tk, 14, pValue2);
                }
                return;
            }
            if (!(type == typeof(DateTime)))
            {
                throw new ArgumentException(SR.Format(SR.Argument_ConstantNotSupported, type));
            }
            long ticks = ((DateTime)value).Ticks;
            SetConstantValue(new QCallModule(ref module), tk, 10, &ticks);
        }
        else
        {
            SetConstantValue(new QCallModule(ref module), tk, 18, null);
        }
    }
References System.SR.Argument_ConstantDoesntMatch, System.SR.Argument_ConstantNotSupported, System.DateTime, System.SR.Format(), System.RuntimeTypeHandle.GetCorElementType(), System.Type.GetType(), System.Enum.GetUnderlyingType(), System.Nullable< T >.GetUnderlyingType(), System.Reflection.Emit.TypeBuilder.SetConstantValue(), System.type, and System.value.