Terraria: System.Linq.Parallel.IntersectQueryOperator.OrderedIntersectQueryOperatorEnumerator.MoveNext
MoveNext() [2/2]
override bool System.Linq.Parallel.IntersectQueryOperator< TInputOutput >.OrderedIntersectQueryOperatorEnumerator< TLeftKey >.MoveNext ([AllowNull] ref TInputOutput currentElement, [AllowNull] ref TLeftKey currentKey) inline package
Definition at line 96 of file IntersectQueryOperator.cs.
        {
            int num = 0;
            if (_hashLookup == null)
            {
                _hashLookup = new Dictionary<Wrapper<TInputOutput>, Pair<TInputOutput, TLeftKey>>(_comparer);
                Pair<TInputOutput, NoKeyMemoizationRequired> currentElement2 = default(Pair<TInputOutput, NoKeyMemoizationRequired>);
                TLeftKey currentKey2 = default(TLeftKey);
                while (_leftSource.MoveNext(ref currentElement2, ref currentKey2))
                {
                    if ((num++ & 0x3F) == 0)
                    {
                        _cancellationToken.ThrowIfCancellationRequested();
                    }
                    Wrapper<TInputOutput> key = new Wrapper<TInputOutput>(currentElement2.First);
                    if (!_hashLookup.TryGetValue(key, out var value) || _leftKeyComparer.Compare(currentKey2, value.Second) < 0)
                    {
                        _hashLookup[key] = new Pair<TInputOutput, TLeftKey>(currentElement2.First, currentKey2);
                    }
                }
            }
            Pair<TInputOutput, NoKeyMemoizationRequired> currentElement3 = default(Pair<TInputOutput, NoKeyMemoizationRequired>);
            int currentKey3 = 0;
            while (_rightSource.MoveNext(ref currentElement3, ref currentKey3))
            {
                if ((num++ & 0x3F) == 0)
                {
                    _cancellationToken.ThrowIfCancellationRequested();
                }
                Wrapper<TInputOutput> key2 = new Wrapper<TInputOutput>(currentElement3.First);
                if (_hashLookup.TryGetValue(key2, out var value2))
                {
                    currentElement = value2.First;
                    currentKey = value2.Second;
                    _hashLookup.Remove(new Wrapper<TInputOutput>(value2.First));
                    return true;
                }
            }
            return false;
        }
References System.Linq.Parallel.IntersectQueryOperator< TInputOutput >.OrderedIntersectQueryOperatorEnumerator< TLeftKey >._cancellationToken, System.Linq.Parallel.IntersectQueryOperator< TInputOutput >.OrderedIntersectQueryOperatorEnumerator< TLeftKey >._comparer, System.Linq.Parallel.IntersectQueryOperator< TInputOutput >.OrderedIntersectQueryOperatorEnumerator< TLeftKey >._hashLookup, System.Linq.Parallel.IntersectQueryOperator< TInputOutput >.OrderedIntersectQueryOperatorEnumerator< TLeftKey >._leftKeyComparer, System.Linq.Parallel.IntersectQueryOperator< TInputOutput >.OrderedIntersectQueryOperatorEnumerator< TLeftKey >._leftSource, System.Linq.Parallel.IntersectQueryOperator< TInputOutput >.OrderedIntersectQueryOperatorEnumerator< TLeftKey >._rightSource, System.Collections.Generic.IComparer< in T >.Compare(), System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Threading.CancellationToken.ThrowIfCancellationRequested(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.