Terraria: System.Diagnostics.Activity.Create
Create()
static Activity System.Diagnostics.Activity.Create (ActivitySource source, string name, ActivityKind kind, string parentId, ActivityContext parentContext, IEnumerable< KeyValuePair< string, object > > tags, IEnumerable< ActivityLink > links, DateTimeOffset startTime, ActivityTagsCollection samplerTags, ActivitySamplingResult request, bool startIt, ActivityIdFormat idFormat) inline static package
Definition at line 978 of file Activity.cs.
    {
        Activity activity = new Activity(name);
        activity.Source = source;
        activity.Kind = kind;
        activity.IdFormat = idFormat;
        if (links != null)
        {
            using IEnumerator<ActivityLink> enumerator = links.GetEnumerator();
            if (enumerator.MoveNext())
            {
                activity._links = new DiagLinkedList<ActivityLink>(enumerator);
            }
        }
        if (tags != null)
        {
            using IEnumerator<KeyValuePair<string, object>> enumerator2 = tags.GetEnumerator();
            if (enumerator2.MoveNext())
            {
                activity._tags = new TagsLinkedList(enumerator2);
            }
        }
        if (samplerTags != null)
        {
            if (activity._tags == null)
            {
                activity._tags = new TagsLinkedList(samplerTags);
            }
            else
            {
                activity._tags.Add(samplerTags);
            }
        }
        if (parentId != null)
        {
            activity._parentId = parentId;
        }
        else if (parentContext != default(ActivityContext))
        {
            activity._traceId = parentContext.TraceId.ToString();
            if (parentContext.SpanId != default(ActivitySpanId))
            {
                activity._parentSpanId = parentContext.SpanId.ToString();
            }
            activity.ActivityTraceFlags = parentContext.TraceFlags;
            activity._parentTraceFlags = (byte)parentContext.TraceFlags;
            activity._traceState = parentContext.TraceState;
        }
        activity.IsAllDataRequested = request == ActivitySamplingResult.AllData || request == ActivitySamplingResult.AllDataAndRecorded;
        if (request == ActivitySamplingResult.AllDataAndRecorded)
        {
            activity.ActivityTraceFlags |= ActivityTraceFlags.Recorded;
        }
        if (startTime != default(DateTimeOffset))
        {
            activity.StartTimeUtc = startTime.UtcDateTime;
        }
        if (startIt)
        {
            activity.Start();
        }
        return activity;
    }
References System.Diagnostics.Activity.Activity(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), and System.source.
Referenced by System.Diagnostics.ActivitySource.CreateActivity().