Terraria: System.Diagnostics.Activity.GenerateHierarchicalId
GenerateHierarchicalId()
string System.Diagnostics.Activity.GenerateHierarchicalId () inline private
Definition at line 1066 of file Activity.cs.
    {
        if (Parent != null)
        {
            return AppendSuffix(Parent.Id, Interlocked.Increment(ref Parent._currentChildId).ToString(), '.');
        }
        if (ParentId != null)
        {
            string text = ((ParentId[0] == '|') ? ParentId : ("|" + ParentId));
            char c = text[text.Length - 1];
            if (c != '.' && c != '_')
            {
                text += ".";
            }
            return AppendSuffix(text, Interlocked.Increment(ref s_currentRootId).ToString("x"), '_');
        }
        return GenerateRootId();
    }
References System.Diagnostics.Activity._currentChildId, System.Diagnostics.Activity.AppendSuffix(), System.Diagnostics.Activity.GenerateRootId(), System.Diagnostics.Activity.Id, System.Threading.Interlocked.Increment(), System.Diagnostics.Activity.Parent, System.Diagnostics.Activity.ParentId, System.Diagnostics.Activity.s_currentRootId, and System.text.
Referenced by System.Diagnostics.Activity.Start().