Terraria: System.Diagnostics.Activity.Stop
Stop()
void System.Diagnostics.Activity.Stop () inline
Definition at line 871 of file Activity.cs.
    {
        if (_id == null && _spanId == null)
        {
            NotifyError(new InvalidOperationException(System.SR.ActivityNotStarted));
        }
        else if (!IsFinished)
        {
            IsFinished = true;
            if (Duration == TimeSpan.Zero)
            {
                SetEndTime(GetUtcNow());
            }
            Source.NotifyActivityStop(this);
            SetCurrent(_previousActiveActivity);
        }
    }
References System.Diagnostics.Activity._id, System.Diagnostics.Activity._previousActiveActivity, System.Diagnostics.Activity._spanId, System.SR.ActivityNotStarted, System.Diagnostics.Activity.Duration, System.Diagnostics.Activity.GetUtcNow(), System.Diagnostics.Activity.IsFinished, System.Diagnostics.ActivitySource.NotifyActivityStop(), System.Diagnostics.Activity.NotifyError(), System.Diagnostics.Activity.SetCurrent(), System.Diagnostics.Activity.SetEndTime(), System.Diagnostics.Activity.Source, and System.TimeSpan.Zero.
Referenced by System.Diagnostics.Activity.Dispose(), and System.Diagnostics.DiagnosticSource.StopActivity().