Terraria: System.Diagnostics.Activity.TrySetTraceFlagsFromParent
TrySetTraceFlagsFromParent()
void System.Diagnostics.Activity.TrySetTraceFlagsFromParent () inline private
Definition at line 1154 of file Activity.cs.
    {
        if (W3CIdFlagsSet)
        {
            return;
        }
        if (Parent != null)
        {
            ActivityTraceFlags = Parent.ActivityTraceFlags;
        }
        else if (_parentId != null && IsW3CId(_parentId))
        {
            if (System.HexConverter.IsHexLowerChar(_parentId[53]) && System.HexConverter.IsHexLowerChar(_parentId[54]))
            {
                _w3CIdFlags = (byte)(ActivityTraceId.HexByteFromChars(_parentId[53], _parentId[54]) | 0x80u);
            }
            else
            {
                _w3CIdFlags = 128;
            }
        }
    }
References System.Diagnostics.Activity._parentId, System.Diagnostics.Activity._w3CIdFlags, System.Diagnostics.Activity.ActivityTraceFlags, System.Diagnostics.ActivityTraceId.HexByteFromChars(), System.HexConverter.IsHexLowerChar(), System.Diagnostics.Activity.IsW3CId(), System.Diagnostics.Activity.Parent, and System.Diagnostics.Activity.W3CIdFlagsSet.
Referenced by System.Diagnostics.Activity.GenerateW3CId().