Terraria: System.Diagnostics.Activity.SetEndTime
SetEndTime()
Activity System.Diagnostics.Activity.SetEndTime (DateTime endTimeUtc) inline
Definition at line 819 of file Activity.cs.
    {
        if (endTimeUtc.Kind != DateTimeKind.Utc)
        {
            NotifyError(new InvalidOperationException(System.SR.EndTimeNotUtc));
        }
        else
        {
            Duration = endTimeUtc - StartTimeUtc;
            if (Duration.Ticks <= 0)
            {
                Duration = new TimeSpan(1L);
            }
        }
        return this;
    }
References System.Diagnostics.Activity.Duration, System.SR.EndTimeNotUtc, System.L, System.Diagnostics.Activity.NotifyError(), System.Diagnostics.Activity.StartTimeUtc, and System.TimeSpan.Ticks.
Referenced by System.Diagnostics.Activity.Stop(), and System.Diagnostics.DiagnosticSource.StopActivity().