Terraria: System.Diagnostics.Activity.TrySetTraceIdFromParent
TrySetTraceIdFromParent()
bool System.Diagnostics.Activity.TrySetTraceIdFromParent () inline private
Definition at line 1135 of file Activity.cs.
    {
        if (Parent != null && Parent.IdFormat == ActivityIdFormat.W3C)
        {
            _traceId = Parent.TraceId.ToHexString();
        }
        else if (_parentId != null && IsW3CId(_parentId))
        {
            try
            {
                _traceId = ActivityTraceId.CreateFromString(_parentId.AsSpan(3, 32)).ToHexString();
            }
            catch
            {
            }
        }
        return _traceId != null;
    }
References System.Diagnostics.Activity._parentId, System.Diagnostics.Activity._traceId, System.Diagnostics.ActivityTraceId.CreateFromString(), System.Diagnostics.Activity.IdFormat, System.Diagnostics.Activity.IsW3CId(), System.Diagnostics.Activity.Parent, System.Diagnostics.ActivityTraceId.ToHexString(), and System.Diagnostics.Activity.TraceId.
Referenced by System.Diagnostics.Activity.GenerateW3CId().