Terraria: System.Diagnostics.Activity.TryConvertIdToContext
TryConvertIdToContext()
static bool System.Diagnostics.Activity.TryConvertIdToContext (string traceParent, string traceState, out ActivityContext context) inline static package
Definition at line 915 of file Activity.cs.
    {
        context = default(ActivityContext);
        if (!IsW3CId(traceParent))
        {
            return false;
        }
        ReadOnlySpan<char> idData = traceParent.AsSpan(3, 32);
        ReadOnlySpan<char> idData2 = traceParent.AsSpan(36, 16);
        if (!ActivityTraceId.IsLowerCaseHexAndNotAllZeros(idData) || !ActivityTraceId.IsLowerCaseHexAndNotAllZeros(idData2) || !System.HexConverter.IsHexLowerChar(traceParent[53]) || !System.HexConverter.IsHexLowerChar(traceParent[54]))
        {
            return false;
        }
        context = new ActivityContext(new ActivityTraceId(idData.ToString()), new ActivitySpanId(idData2.ToString()), (ActivityTraceFlags)ActivityTraceId.HexByteFromChars(traceParent[53], traceParent[54]), traceState);
        return true;
    }
References System.Diagnostics.ActivityTraceId.HexByteFromChars(), System.HexConverter.IsHexLowerChar(), System.Diagnostics.ActivityTraceId.IsLowerCaseHexAndNotAllZeros(), and System.Diagnostics.Activity.IsW3CId().
Referenced by System.Diagnostics.PassThroughPropagator.GetRootId(), System.Diagnostics.ActivityContext.Parse(), and System.Diagnostics.ActivityContext.TryParse().