Terraria: System.Diagnostics.Activity.Start
Start()
Activity System.Diagnostics.Activity.Start () inline
Definition at line 836 of file Activity.cs.
    {
        if (_id != null || _spanId != null)
        {
            NotifyError(new InvalidOperationException(System.SR.ActivityStartAlreadyStarted));
        }
        else
        {
            _previousActiveActivity = Current;
            if (_parentId == null && _parentSpanId == null && _previousActiveActivity != null)
            {
                Parent = _previousActiveActivity;
            }
            if (StartTimeUtc == default(DateTime))
            {
                StartTimeUtc = GetUtcNow();
            }
            if (IdFormat == ActivityIdFormat.Unknown)
            {
                IdFormat = (ForceDefaultIdFormat ? DefaultIdFormat : ((Parent != null) ? Parent.IdFormat : ((_parentSpanId != null) ? ActivityIdFormat.W3C : ((_parentId == null) ? DefaultIdFormat : ((!IsW3CId(_parentId)) ? ActivityIdFormat.Hierarchical : ActivityIdFormat.W3C)))));
            }
            if (IdFormat == ActivityIdFormat.W3C)
            {
                GenerateW3CId();
            }
            else
            {
                _id = GenerateHierarchicalId();
            }
            SetCurrent(this);
            Source.NotifyActivityStart(this);
        }
        return this;
    }
References System.Diagnostics.Activity._id, System.Diagnostics.Activity._parentId, System.Diagnostics.Activity._parentSpanId, System.Diagnostics.Activity._previousActiveActivity, System.Diagnostics.Activity._spanId, System.SR.ActivityStartAlreadyStarted, System.Diagnostics.Activity.Current, System.Diagnostics.Activity.DefaultIdFormat, System.Diagnostics.Activity.ForceDefaultIdFormat, System.Diagnostics.Activity.GenerateHierarchicalId(), System.Diagnostics.Activity.GenerateW3CId(), System.Diagnostics.Activity.GetUtcNow(), System.Diagnostics.Activity.IdFormat, System.Diagnostics.Activity.IsW3CId(), System.Diagnostics.ActivitySource.NotifyActivityStart(), System.Diagnostics.Activity.NotifyError(), System.Diagnostics.Activity.Parent, System.Diagnostics.Activity.SetCurrent(), System.Diagnostics.Activity.Source, and System.Diagnostics.Activity.StartTimeUtc.
Referenced by System.Diagnostics.DiagnosticSource.StartActivity().