Terraria: System.Diagnostics.Activity.GenerateW3CId
GenerateW3CId()
void System.Diagnostics.Activity.GenerateW3CId () inline private
Definition at line 1042 of file Activity.cs.
    {
        if (_traceId == null && !TrySetTraceIdFromParent())
        {
            _traceId = (TraceIdGenerator?.Invoke() ?? ActivityTraceId.CreateRandom()).ToHexString();
        }
        if (!W3CIdFlagsSet)
        {
            TrySetTraceFlagsFromParent();
        }
        _spanId = ActivitySpanId.CreateRandom().ToHexString();
    }
References System.Diagnostics.Activity._spanId, System.Diagnostics.Activity._traceId, System.Diagnostics.ActivitySpanId.CreateRandom(), System.Diagnostics.ActivityTraceId.CreateRandom(), System.Diagnostics.Activity.TraceIdGenerator, System.Diagnostics.Activity.TrySetTraceFlagsFromParent(), System.Diagnostics.Activity.TrySetTraceIdFromParent(), and System.Diagnostics.Activity.W3CIdFlagsSet.
Referenced by System.Diagnostics.Activity.Start().