Terraria: System.Diagnostics.Activity.AppendSuffix
AppendSuffix()
string System.Diagnostics.Activity.AppendSuffix (string parentId, string suffix, char delimiter) inline private
Definition at line 1100 of file Activity.cs.
    {
        if (parentId.Length + suffix.Length < 1024)
        {
            return parentId + suffix + delimiter;
        }
        int num = 1015;
        while (num > 1 && parentId[num - 1] != '.' && parentId[num - 1] != '_')
        {
            num--;
        }
        if (num == 1)
        {
            return GenerateRootId();
        }
        string text = ((int)GetRandomNumber()).ToString("x8");
        return parentId.Substring(0, num) + text + "#";
    }
References System.Diagnostics.Activity.GenerateRootId(), System.Diagnostics.Activity.GetRandomNumber(), System.suffix, System.text, and System.ToString.
Referenced by System.Diagnostics.Activity.GenerateHierarchicalId().