Terraria: UICharacterSelect.OnInitialize
OnInitialize()
override void UICharacterSelect.OnInitialize () inline virtual
Reimplemented from UIElement.
     {
         UIElement uIElement = new UIElement();
         uIElement.Width.Set(0f, 0.8f);
         uIElement.MaxWidth.Set(650f, 0f);
         uIElement.Top.Set(220f, 0f);
         uIElement.Height.Set(-220f, 1f);
         uIElement.HAlign = 0.5f;
         UIPanel uIPanel = new UIPanel();
         uIPanel.Width.Set(0f, 1f);
         uIPanel.Height.Set(-110f, 1f);
         uIPanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
         _containerPanel = uIPanel;
         uIElement.Append(uIPanel);
         _playerList = new UIList();
         _playerList.Width.Set(0f, 1f);
         _playerList.Height.Set(0f, 1f);
         _playerList.ListPadding = 5f;
         uIPanel.Append(_playerList);
         _scrollbar = new UIScrollbar();
         _scrollbar.SetView(100f, 1000f);
         _scrollbar.Height.Set(0f, 1f);
         _scrollbar.HAlign = 1f;
         _playerList.SetScrollbar(_scrollbar);
         UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.SelectPlayer"), 0.8f, large: true);
         uITextPanel.HAlign = 0.5f;
         uITextPanel.Top.Set(-40f, 0f);
         uITextPanel.SetPadding(15f);
         uITextPanel.BackgroundColor = new Color(73, 94, 171);
         uIElement.Append(uITextPanel);
         UITextPanel<LocalizedText> uITextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true);
         uITextPanel2.Width.Set(-10f, 0.5f);
         uITextPanel2.Height.Set(50f, 0f);
         uITextPanel2.VAlign = 1f;
         uITextPanel2.Top.Set(-45f, 0f);
         uITextPanel2.OnMouseOver += FadedMouseOver;
         uITextPanel2.OnMouseOut += FadedMouseOut;
         uITextPanel2.OnLeftClick += GoBackClick;
         uITextPanel2.SetSnapPoint("Back", 0);
         uIElement.Append(uITextPanel2);
         _backPanel = uITextPanel2;
         UITextPanel<LocalizedText> uITextPanel3 = new UITextPanel<LocalizedText>(Language.GetText("UI.New"), 0.7f, large: true);
         uITextPanel3.CopyStyle(uITextPanel2);
         uITextPanel3.HAlign = 1f;
         uITextPanel3.OnMouseOver += FadedMouseOver;
         uITextPanel3.OnMouseOut += FadedMouseOut;
         uITextPanel3.OnLeftClick += NewCharacterClick;
         uIElement.Append(uITextPanel3);
         uITextPanel2.SetSnapPoint("New", 0);
         _newPanel = uITextPanel3;
         Append(uIElement);
     }
References UIElement.UIElement(), _backPanel, _containerPanel, _newPanel, _playerList, _scrollbar, UIElement.Append(), UIPanel.BackgroundColor, Color, FadedMouseOut(), FadedMouseOver(), Language.GetText(), GoBackClick(), UIElement.HAlign, UIElement.Height, UIList.ListPadding, UIElement.MaxWidth, NewCharacterClick(), StyleDimension.Set(), UIList.SetScrollbar(), UIScrollbar.SetView(), UIElement.Top, and UIElement.Width.