Terraria: UICharacterSelect.NewCharacterClick
NewCharacterClick()
void UICharacterSelect.NewCharacterClick (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         SoundEngine.PlaySound(10);
         Main.PendingPlayer = new Player();
         Main.menuMode = 888;
         Main.MenuUI.SetState(new UICharacterCreation(Main.PendingPlayer));
     }
References Main.menuMode, Main.MenuUI, Main.PendingPlayer, Player, SoundEngine.PlaySound(), and UserInterface.SetState().
Referenced by OnInitialize().