Terraria: UICharacterSelect.UpdatePlayersList
UpdatePlayersList()
void UICharacterSelect.UpdatePlayersList () inline private
     {
         _playerList.Clear();
         List<PlayerFileData> list = new List<PlayerFileData>(Main.PlayerList);
         list.Sort(delegate(PlayerFileData x, PlayerFileData y)
         {
             if (x.IsFavorite && !y.IsFavorite)
             {
                 return -1;
             }
             if (!x.IsFavorite && y.IsFavorite)
             {
                 return 1;
             }
             return (x.Name.CompareTo(y.Name) != 0) ? x.Name.CompareTo(y.Name) : x.GetFileName().CompareTo(y.GetFileName());
         });
         int num = 0;
         foreach (PlayerFileData item in list)
         {
             _playerList.Add(new UICharacterListItem(item, num++));
         }
     }
References _playerList, UIList.Add(), UIList.Clear(), FileData.GetFileName(), FileData.IsFavorite, FileData.Name, and Main.PlayerList.
Referenced by OnActivate(), and UpdateFavoritesCache().