Terraria: System.Xml.Schema.Parser.FinishParsing
FinishParsing()
SchemaType System.Xml.Schema.Parser.FinishParsing () inline
Definition at line 157 of file Parser.cs.
    {
        return _schemaType;
    }
References System.Xml.Schema.Parser._schemaType.
Referenced by System.Xml.Schema.Parser.Parse(), System.Xml.Schema.XdrValidator.ProcessInlineSchema(), System.Xml.Schema.XsdValidator.ProcessInlineSchema(), System.Xml.XsdValidatingReader.ProcessInlineSchema(), and System.Xml.XsdValidatingReader.ProcessInlineSchemaAsync().