Terraria: System.Xml.Schema.Parser.StartParsing
StartParsing()
void System.Xml.Schema.Parser.StartParsing (XmlReader reader, string targetNamespace) inline
Definition at line 78 of file Parser.cs.
    {
        _reader = reader;
        _positionInfo = PositionInfo.GetPositionInfo(reader);
        _namespaceManager = reader.NamespaceManager;
        if (_namespaceManager == null)
        {
            _namespaceManager = new XmlNamespaceManager(_nameTable);
            _isProcessNamespaces = true;
        }
        else
        {
            _isProcessNamespaces = false;
        }
        while (reader.NodeType != XmlNodeType.Element && reader.Read())
        {
        }
        _markupDepth = int.MaxValue;
        _schemaXmlDepth = reader.Depth;
        SchemaType rootType = _schemaNames.SchemaTypeFromRoot(reader.LocalName, reader.NamespaceURI);
        if (!CheckSchemaRoot(rootType, out var code))
        {
            throw new XmlSchemaException(code, reader.BaseURI, _positionInfo.LineNumber, _positionInfo.LinePosition);
        }
        if (_schemaType == SchemaType.XSD)
        {
            _schema = new XmlSchema();
            _schema.BaseUri = new Uri(reader.BaseURI, UriKind.RelativeOrAbsolute);
            _builder = new XsdBuilder(reader, _namespaceManager, _schema, _nameTable, _schemaNames, _eventHandler);
        }
        else
        {
            _xdrSchema = new SchemaInfo();
            _xdrSchema.SchemaType = SchemaType.XDR;
            _builder = new XdrBuilder(reader, _namespaceManager, _xdrSchema, targetNamespace, _nameTable, _schemaNames, _eventHandler);
            ((XdrBuilder)_builder).XmlResolver = _xmlResolver;
        }
    }
References System.Xml.Schema.Parser._builder, System.Xml.Schema.Parser._eventHandler, System.Xml.Schema.Parser._isProcessNamespaces, System.Xml.Schema.Parser._markupDepth, System.Xml.Schema.Parser._namespaceManager, System.Xml.Schema.Parser._nameTable, System.Xml.Schema.Parser._positionInfo, System.Xml.Schema.Parser._reader, System.Xml.Schema.Parser._schema, System.Xml.Schema.Parser._schemaNames, System.Xml.Schema.Parser._schemaType, System.Xml.Schema.Parser._schemaXmlDepth, System.Xml.Schema.Parser._xdrSchema, System.Xml.Schema.Parser._xmlResolver, System.Xml.XmlReader.BaseURI, System.Xml.Schema.Parser.CheckSchemaRoot(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.PositionInfo.GetPositionInfo(), System.Xml.PositionInfo.LineNumber, System.Xml.PositionInfo.LinePosition, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceManager, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.Schema.SchemaNames.SchemaTypeFromRoot(), and System.Xml.Schema.Parser.XmlSchema.
Referenced by System.Xml.Schema.Parser.Parse(), System.Xml.XsdValidatingReader.ProcessElementEvent(), System.Xml.Schema.XdrValidator.ValidateElement(), and System.Xml.Schema.XsdValidator.ValidateElement().