Terraria: System.Xml.Schema.Parser.ParseReaderNode
ParseReaderNode()
bool System.Xml.Schema.Parser.ParseReaderNode () inline
Definition at line 162 of file Parser.cs.
    {
        if (_reader.Depth > _markupDepth)
        {
            if (_processMarkup)
            {
                ProcessAppInfoDocMarkup(root: false);
            }
            return true;
        }
        if (_reader.NodeType == XmlNodeType.Element)
        {
            if (_builder.ProcessElement(_reader.Prefix, _reader.LocalName, _reader.NamespaceURI))
            {
                _namespaceManager.PushScope();
                if (_reader.MoveToFirstAttribute())
                {
                    do
                    {
                        _builder.ProcessAttribute(_reader.Prefix, _reader.LocalName, _reader.NamespaceURI, _reader.Value);
                        if (Ref.Equal(_reader.NamespaceURI, _schemaNames.NsXmlNs) && _isProcessNamespaces)
{
                            _namespaceManager.AddNamespace((_reader.Prefix.Length == 0) ? string.Empty : _reader.LocalName, _reader.Value);
                        }
                    }
                    while (_reader.MoveToNextAttribute());
                    _reader.MoveToElement();
                }
                _builder.StartChildren();
                if (_reader.IsEmptyElement)
                {
                    _namespaceManager.PopScope();
                    _builder.EndChildren();
                    if (_reader.Depth == _schemaXmlDepth)
                    {
                        return false;
                    }
                }
                else if (!_builder.IsContentParsed())
                {
                    _markupDepth = _reader.Depth;
                    _processMarkup = true;
                    if (_annotationNSManager == null)
                    {
                        _annotationNSManager = new XmlNamespaceManager(_nameTable);
                        _xmlns = _nameTable.Add("xmlns");
                    }
                    ProcessAppInfoDocMarkup(root: true);
                }
            }
            else if (!_reader.IsEmptyElement)
            {
                _markupDepth = _reader.Depth;
                _processMarkup = false;
            }
        }
        else if (_reader.NodeType == XmlNodeType.Text)
        {
            if (!XmlCharType.IsOnlyWhitespace(_reader.Value))
            {
                _builder.ProcessCData(_reader.Value);
            }
        }
        else if (_reader.NodeType == XmlNodeType.EntityReference || _reader.NodeType == XmlNodeType.SignificantWhitespace || _reader.NodeType == XmlNodeType.CDATA)
        {
            _builder.ProcessCData(_reader.Value);
        }
        else if (_reader.NodeType == XmlNodeType.EndElement)
        {
            if (_reader.Depth == _markupDepth)
            {
                if (_processMarkup)
                {
                    XmlNodeList childNodes = _parentNode.ChildNodes;
                    XmlNode[] array = new XmlNode[childNodes.Count];
                    for (int i = 0; i < childNodes.Count; i++)
                    {
                        array[i] = childNodes[i];
                    }
                    _builder.ProcessMarkup(array);
                    _namespaceManager.PopScope();
                    _builder.EndChildren();
                }
                _markupDepth = int.MaxValue;
            }
            else
            {
                _namespaceManager.PopScope();
                _builder.EndChildren();
            }
            if (_reader.Depth == _schemaXmlDepth)
            {
                return false;
            }
        }
        return true;
    }
References System.Xml.Schema.Parser._annotationNSManager, System.Xml.Schema.Parser._builder, System.Xml.Schema.Parser._isProcessNamespaces, System.Xml.Schema.Parser._markupDepth, System.Xml.Schema.Parser._namespaceManager, System.Xml.Schema.Parser._nameTable, System.Xml.Schema.Parser._parentNode, System.Xml.Schema.Parser._processMarkup, System.Xml.Schema.Parser._reader, System.Xml.Schema.Parser._schemaNames, System.Xml.Schema.Parser._schemaXmlDepth, System.Xml.Schema.Parser._xmlns, System.Xml.XmlNameTable.Add(), System.Xml.XmlNamespaceManager.AddNamespace(), System.array, System.Xml.XmlNode.ChildNodes, System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.Schema.SchemaBuilder.EndChildren(), System.Xml.Ref.Equal(), System.Xml.Schema.SchemaBuilder.IsContentParsed(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlCharType.IsOnlyWhitespace(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.Schema.SchemaNames.NsXmlNs, System.Xml.XmlNamespaceManager.PopScope(), System.Xml.XmlReader.Prefix, System.Xml.Schema.Parser.ProcessAppInfoDocMarkup(), System.Xml.Schema.SchemaBuilder.ProcessAttribute(), System.Xml.Schema.SchemaBuilder.ProcessCData(), System.Xml.Schema.SchemaBuilder.ProcessElement(), System.Xml.Schema.SchemaBuilder.ProcessMarkup(), System.Xml.XmlNamespaceManager.PushScope(), System.Xml.Schema.SchemaBuilder.StartChildren(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.Schema.Parser.Parse(), System.Xml.XsdValidatingReader.ProcessElementEvent(), System.Xml.XsdValidatingReader.ProcessElementEventAsync(), System.Xml.Schema.XdrValidator.ProcessInlineSchema(), System.Xml.Schema.XsdValidator.ProcessInlineSchema(), System.Xml.XsdValidatingReader.ProcessInlineSchema(), System.Xml.XsdValidatingReader.ProcessInlineSchemaAsync(), and System.Xml.Schema.XdrValidator.ValidateElement().