Terraria: System.Xml.Schema.Parser.LoadElementNode
LoadElementNode()
XmlElement System.Xml.Schema.Parser.LoadElementNode (bool root) inline private
Definition at line 298 of file Parser.cs.
    {
        XmlReader reader = _reader;
        bool isEmptyElement = reader.IsEmptyElement;
        XmlElement xmlElement = _dummyDocument.CreateElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
        xmlElement.IsEmpty = isEmptyElement;
        if (root)
        {
            _parentNode = xmlElement;
        }
        else
        {
            XmlAttributeCollection attributes = xmlElement.Attributes;
            if (reader.MoveToFirstAttribute())
            {
                do
                {
                    if (Ref.Equal(reader.NamespaceURI, _schemaNames.NsXmlNs))
                    {
                        _annotationNSManager.AddNamespace((reader.Prefix.Length == 0) ? string.Empty : _reader.LocalName, _reader.Value);
                    }
                    XmlAttribute node = LoadAttributeNode();
                    attributes.Append(node);
                }
                while (reader.MoveToNextAttribute());
            }
            reader.MoveToElement();
            string text = _annotationNSManager.LookupNamespace(reader.Prefix);
            if (text == null)
            {
                XmlAttribute node2 = CreateXmlNsAttribute(reader.Prefix, _namespaceManager.LookupNamespace(reader.Prefix));
                attributes.Append(node2);
            }
            else if (text.Length == 0)
            {
                string text2 = _namespaceManager.LookupNamespace(reader.Prefix);
                if (text2 != string.Empty)
                {
                    XmlAttribute node3 = CreateXmlNsAttribute(reader.Prefix, text2);
                    attributes.Append(node3);
                }
            }
            while (reader.MoveToNextAttribute())
            {
                if (reader.Prefix.Length != 0)
                {
                    string text3 = _annotationNSManager.LookupNamespace(reader.Prefix);
                    if (text3 == null)
                    {
                        XmlAttribute node4 = CreateXmlNsAttribute(reader.Prefix, _namespaceManager.LookupNamespace(reader.Prefix));
                        attributes.Append(node4);
                    }
                }
            }
            reader.MoveToElement();
            _parentNode.AppendChild(xmlElement);
            if (!reader.IsEmptyElement)
            {
                _parentNode = xmlElement;
            }
        }
        return xmlElement;
    }
References System.Xml.Schema.Parser._annotationNSManager, System.Xml.Schema.Parser._dummyDocument, System.Xml.Schema.Parser._namespaceManager, System.Xml.Schema.Parser._parentNode, System.Xml.Schema.Parser._reader, System.Xml.Schema.Parser._schemaNames, System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.XmlAttributeCollection.Append(), System.Xml.XmlNode.AppendChild(), System.Xml.XmlDocument.CreateElement(), System.Xml.Schema.Parser.CreateXmlNsAttribute(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.XmlReader.IsEmptyElement, System.Xml.Schema.Parser.LoadAttributeNode(), System.Xml.XmlReader.LocalName, System.Xml.XmlNamespaceManager.LookupNamespace(), System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.NamespaceURI, System.Xml.Schema.SchemaNames.NsXmlNs, System.Xml.XmlReader.Prefix, System.text, and System.Xml.XmlReader.Value.
Referenced by System.Xml.Schema.Parser.ProcessAppInfoDocMarkup().