Terraria: System.Xml.Schema.Parser.CreateXmlNsAttribute
CreateXmlNsAttribute()
XmlAttribute System.Xml.Schema.Parser.CreateXmlNsAttribute (string prefix, string value) inline private
Definition at line 362 of file Parser.cs.
    {
        XmlAttribute xmlAttribute = ((prefix.Length != 0) ? _dummyDocument.CreateAttribute(_xmlns, prefix, "http://www.w3.org/2000/xmlns/") : _dummyDocument.CreateAttribute(string.Empty, _xmlns, "http://www.w3.org/2000/xmlns/"));
        xmlAttribute.AppendChild(_dummyDocument.CreateTextNode(value));
        _annotationNSManager.AddNamespace(prefix, value);
        return xmlAttribute;
    }
References System.Xml.Schema.Parser._annotationNSManager, System.Xml.Schema.Parser._dummyDocument, System.Xml.Schema.Parser._xmlns, System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.XmlAttribute.AppendChild(), System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.prefix, and System.value.
Referenced by System.Xml.Schema.Parser.LoadElementNode().