Terraria: System.Xml.Schema.Parser.LoadEntityReferenceInAttribute
LoadEntityReferenceInAttribute()
XmlEntityReference System.Xml.Schema.Parser.LoadEntityReferenceInAttribute () inline private
Definition at line 391 of file Parser.cs.
    {
        XmlEntityReference xmlEntityReference = _dummyDocument.CreateEntityReference(_reader.LocalName);
        if (!_reader.CanResolveEntity)
        {
            return xmlEntityReference;
        }
        _reader.ResolveEntity();
        while (_reader.ReadAttributeValue())
        {
            switch (_reader.NodeType)
            {
            case XmlNodeType.Text:
                xmlEntityReference.AppendChild(_dummyDocument.CreateTextNode(_reader.Value));
                break;
            case XmlNodeType.EndEntity:
                if (xmlEntityReference.ChildNodes.Count == 0)
                {
                    xmlEntityReference.AppendChild(_dummyDocument.CreateTextNode(string.Empty));
                }
                return xmlEntityReference;
            case XmlNodeType.EntityReference:
                xmlEntityReference.AppendChild(LoadEntityReferenceInAttribute());
                break;
            default:
                throw XmlLoader.UnexpectedNodeType(_reader.NodeType);
            }
        }
        return xmlEntityReference;
    }
References System.Xml.Schema.Parser._dummyDocument, System.Xml.Schema.Parser._reader, System.Xml.XmlReader.CanResolveEntity, System.Xml.XmlDocument.CreateEntityReference(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.Xml.Schema.Parser.LoadEntityReferenceInAttribute(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlReader.ResolveEntity(), System.Xml.XmlLoader.UnexpectedNodeType(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.Schema.Parser.LoadAttributeNode(), and System.Xml.Schema.Parser.LoadEntityReferenceInAttribute().