Terraria: System.Xml.Schema.Parser.LoadAttributeNode
LoadAttributeNode()
XmlAttribute System.Xml.Schema.Parser.LoadAttributeNode () inline private
Definition at line 370 of file Parser.cs.
    {
        XmlReader reader = _reader;
        XmlAttribute xmlAttribute = _dummyDocument.CreateAttribute(reader.Prefix, reader.LocalName, reader.NamespaceURI);
        while (reader.ReadAttributeValue())
        {
            switch (reader.NodeType)
            {
            case XmlNodeType.Text:
                xmlAttribute.AppendChild(_dummyDocument.CreateTextNode(reader.Value));
                break;
            case XmlNodeType.EntityReference:
                xmlAttribute.AppendChild(LoadEntityReferenceInAttribute());
                break;
            default:
                throw XmlLoader.UnexpectedNodeType(reader.NodeType);
            }
        }
        return xmlAttribute;
    }
References System.Xml.Schema.Parser._dummyDocument, System.Xml.Schema.Parser._reader, System.Xml.XmlAttribute.AppendChild(), System.Xml.XmlNode.AppendChild(), System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.Xml.Schema.Parser.LoadEntityReferenceInAttribute(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlLoader.UnexpectedNodeType(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.Schema.Parser.LoadElementNode().