Terraria: System.Xml.Schema.Parser.ProcessAppInfoDocMarkup
ProcessAppInfoDocMarkup()
void System.Xml.Schema.Parser.ProcessAppInfoDocMarkup (bool root) inline private
Definition at line 260 of file Parser.cs.
    {
        XmlNode newChild = null;
        switch (_reader.NodeType)
        {
        case XmlNodeType.Element:
            _annotationNSManager.PushScope();
            newChild = LoadElementNode(root);
            return;
        case XmlNodeType.Text:
            newChild = _dummyDocument.CreateTextNode(_reader.Value);
            break;
        case XmlNodeType.SignificantWhitespace:
            newChild = _dummyDocument.CreateSignificantWhitespace(_reader.Value);
            break;
        case XmlNodeType.CDATA:
            newChild = _dummyDocument.CreateCDataSection(_reader.Value);
            break;
        case XmlNodeType.EntityReference:
            newChild = _dummyDocument.CreateEntityReference(_reader.Name);
            break;
        case XmlNodeType.Comment:
            newChild = _dummyDocument.CreateComment(_reader.Value);
            break;
        case XmlNodeType.ProcessingInstruction:
            newChild = _dummyDocument.CreateProcessingInstruction(_reader.Name, _reader.Value);
            break;
        case XmlNodeType.EndElement:
            _annotationNSManager.PopScope();
            _parentNode = _parentNode.ParentNode;
            return;
        case XmlNodeType.Whitespace:
        case XmlNodeType.EndEntity:
            return;
        }
        _parentNode.AppendChild(newChild);
    }
References System.Xml.Schema.Parser._annotationNSManager, System.Xml.Schema.Parser._dummyDocument, System.Xml.Schema.Parser._parentNode, System.Xml.Schema.Parser._reader, System.Xml.XmlNode.AppendChild(), System.Xml.XmlDocument.CreateCDataSection(), System.Xml.XmlDocument.CreateComment(), System.Xml.XmlDocument.CreateEntityReference(), System.Xml.XmlDocument.CreateProcessingInstruction(), System.Xml.XmlDocument.CreateSignificantWhitespace(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.Xml.Schema.Parser.LoadElementNode(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NodeType, System.Xml.XmlNode.ParentNode, System.Xml.XmlNamespaceManager.PopScope(), System.Xml.XmlNamespaceManager.PushScope(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.Schema.Parser.ParseReaderNode().