Terraria: System.Xml.Schema.Parser.Parse
Parse()
SchemaType System.Xml.Schema.Parser.Parse (XmlReader reader, string targetNamespace) inline
Definition at line 69 of file Parser.cs.
    {
        StartParsing(reader, targetNamespace);
        while (ParseReaderNode() && reader.Read())
        {
        }
        return FinishParsing();
    }
References System.Xml.Dictionary, System.Xml.Schema.Parser.FinishParsing(), System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.XmlReader.Read(), and System.Xml.Schema.Parser.StartParsing().