Terraria: System.BitConverter.UInt16BitsToHalf
UInt16BitsToHalf()
static Half System.BitConverter.UInt16BitsToHalf (ushort value) inline static
Definition at line 579 of file BitConverter.cs.
    {
        return Int16BitsToHalf((short)value);
    }
References System.BitConverter.Int16BitsToHalf(), and System.value.
Referenced by System.Half.BitDecrement(), System.Half.BitIncrement(), System.Half.CreateHalfNaN(), System.Half.operator&(), System.Half.operator^(), System.Half.operator|(), and System.Half.operator~().