Terraria: System.BitConverter.Int64BitsToDouble
Int64BitsToDouble()
static unsafe double System.BitConverter.Int64BitsToDouble (long value) inline static
Definition at line 498 of file BitConverter.cs.
    {
        if (Sse2.X64.IsSupported)
        {
            Vector128<double> vector = Vector128.CreateScalarUnsafe(value).AsDouble();
            return vector.ToScalar();
        }
        return *(double*)(&value);
    }
References System.Runtime.Intrinsics.Vector128< T >.CreateScalarUnsafe(), System.Runtime.Intrinsics.X86.Sse2.X64.IsSupported, and System.value.
Referenced by System.Xml.Xsl.XPathConvert.FloatingDecimal.AdjustDbl(), System.Math.BitDecrement(), System.Math.BitIncrement(), System.Math.CopySign(), System.Xml.Xsl.XPathConvert.BigNumber.DblToRgbPrecise(), System.Diagnostics.Tracing.EventPipePayloadDecoder.DecodePayload(), System.Numerics.Vector< T >.GetAllBitsSetValue(), System.Diagnostics.Metrics.ExponentialHistogramAggregator.GetBucketCanonicalValue(), System.IO.BinaryReader.ReadDouble(), System.IO.UnmanagedMemoryAccessor.ReadDouble(), System.Buffers.Binary.BinaryPrimitives.ReadDoubleBigEndian(), System.Math.ScaleB(), System.BitConverter.ToDouble(), System.Variant.ToObject(), System.Buffers.Binary.BinaryPrimitives.TryReadDoubleBigEndian(), and System.BitConverter.UInt64BitsToDouble().