Terraria: System.BitConverter.SingleToInt32Bits
SingleToInt32Bits()
static unsafe int System.BitConverter.SingleToInt32Bits (float value) inline static
Definition at line 509 of file BitConverter.cs.
    {
        if (Sse2.IsSupported)
        {
            Vector128<int> value2 = Vector128.CreateScalarUnsafe(value).AsInt32();
            return Sse2.ConvertToInt32(value2);
        }
        return *(int*)(&value);
    }
References System.Runtime.Intrinsics.X86.Sse2.ConvertToInt32(), System.Runtime.Intrinsics.Vector128< T >.CreateScalarUnsafe(), System.Runtime.Intrinsics.X86.Sse2.IsSupported, and System.value.
Referenced by System.MathF.BitDecrement(), System.MathF.BitIncrement(), System.MathF.CopySign(), System.Reflection.Emit.ILGenerator.Emit(), System.Single.IsFinite(), System.Single.IsInfinity(), System.Single.IsNegative(), System.Single.IsNormal(), System.Single.IsSubnormal(), System.BitConverter.SingleToUInt32Bits(), System.Buffers.Binary.BinaryPrimitives.TryWriteSingleBigEndian(), System.IO.UnmanagedMemoryAccessor.Write(), and System.Buffers.Binary.BinaryPrimitives.WriteSingleBigEndian().