Terraria: System.BitConverter.Int16BitsToHalf
Int16BitsToHalf()
static unsafe Half System.BitConverter.Int16BitsToHalf (short value) inline static
Definition at line 537 of file BitConverter.cs.
    {
        return *(Half*)(&value);
    }
References System.value.
Referenced by System.IO.BinaryReader.ReadHalf(), System.Buffers.Binary.BinaryPrimitives.ReadHalfBigEndian(), System.BitConverter.ToHalf(), System.Buffers.Binary.BinaryPrimitives.TryReadHalfBigEndian(), and System.BitConverter.UInt16BitsToHalf().