Terraria: System.BitConverter.DoubleToUInt64Bits
DoubleToUInt64Bits()
static ulong System.BitConverter.DoubleToUInt64Bits (double value) inline static
Definition at line 544 of file BitConverter.cs.
    {
        return (ulong)DoubleToInt64Bits(value);
    }
References System.BitConverter.DoubleToInt64Bits(), and System.value.
Referenced by System.Xml.Xsl.XPathConvert.DblHi(), System.Xml.Xsl.XPathConvert.DblLo(), System.Number.ExtractFractionAndBiasedExponent(), System.Double.IsPow2(), System.Number.NumberToDoubleFloatingPointBits(), System.Half.operator Half(), System.Double.operator&(), System.Double.operator^(), System.Double.operator|(), System.Double.operator~(), and System.Math.Round().