Terraria: System.BitConverter.DoubleToInt64Bits
DoubleToInt64Bits()
static unsafe long System.BitConverter.DoubleToInt64Bits (double value) inline static
Definition at line 487 of file BitConverter.cs.
    {
        if (Sse2.X64.IsSupported)
        {
            Vector128<long> value2 = Vector128.CreateScalarUnsafe(value).AsInt64();
            return Sse2.X64.ConvertToInt64(value2);
        }
        return *(long*)(&value);
    }
References System.Runtime.Intrinsics.X86.Sse2.X64.ConvertToInt64(), System.Runtime.Intrinsics.Vector128< T >.CreateScalarUnsafe(), System.Runtime.Intrinsics.X86.Sse2.X64.IsSupported, and System.value.
Referenced by System.Variant.Variant(), System.Xml.Xsl.XPathConvert.FloatingDecimal.AdjustDbl(), System.Math.BitDecrement(), System.Math.BitIncrement(), System.Math.CopySign(), System.BitConverter.DoubleToUInt64Bits(), System.Reflection.Emit.ILGenerator.Emit(), System.Double.IsFinite(), System.Double.IsInfinity(), System.Double.IsNegative(), System.Xml.XmlConvert.IsNegativeZero(), System.Double.IsNormal(), System.Double.IsSubnormal(), System.Buffers.Binary.BinaryPrimitives.TryWriteDoubleBigEndian(), System.Diagnostics.Metrics.ExponentialHistogramAggregator.Update(), System.IO.UnmanagedMemoryAccessor.Write(), and System.Buffers.Binary.BinaryPrimitives.WriteDoubleBigEndian().