Terraria: System.BitConverter.ToInt16
ToInt16() [1/2]
static short System.BitConverter.ToInt16 (byte[] value, int startIndex) inline static
Definition at line 220 of file BitConverter.cs.
    {
        if (value == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.value);
        }
        if ((uint)startIndex >= (uint)value.Length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.startIndex, ExceptionResource.ArgumentOutOfRange_Index);
        }
        if (startIndex > value.Length - 2)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_ArrayPlusOffTooSmall, ExceptionArgument.value);
        }
        return Unsafe.ReadUnaligned<short>(ref value[startIndex]);
    }
References System.startIndex, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.value.
Referenced by System.Net.SocketAddressPal.GetAddressFamily(), System.BitConverter.ToChar(), System.BitConverter.ToHalf(), and System.BitConverter.ToUInt16().