Terraria: System.BitConverter.ToInt32
ToInt32() [1/2]
static int System.BitConverter.ToInt32 (byte[] value, int startIndex) inline static
Definition at line 247 of file BitConverter.cs.
    {
        if (value == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.value);
        }
        if ((uint)startIndex >= (uint)value.Length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.startIndex, ExceptionResource.ArgumentOutOfRange_Index);
        }
        if (startIndex > value.Length - 4)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_ArrayPlusOffTooSmall, ExceptionArgument.value);
        }
        return Unsafe.ReadUnaligned<int>(ref value[startIndex]);
    }
References System.startIndex, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.value.
Referenced by Terraria.Social.WeGame.IPCMessage.BuildFrom(), System.Net.WebSockets.ManagedWebSocket.CombineMaskBytes(), System.Security.Cryptography.ECCng.ExportNamedCurveParameters(), System.Security.Cryptography.DSAImplementation.DSACng.ExportParameters(), System.Security.Cryptography.DSACng.ExportParameters(), System.Security.Cryptography.RSAImplementation.RSACng.ExportParameters(), System.Security.Cryptography.RSACng.ExportParameters(), System.Security.Cryptography.ECCng.ExportPrimeCurveParameters(), Internal.Cryptography.Helpers.GetPropertyAsDword(), Internal.NativeCrypto.CapiHelper.GetProviderParameter(), Internal.NativeCrypto.CapiHelper.GetProviderParameterWorker(), System.Net.Security.NegotiateStream.ReadAsync< TAdapter >(), System.Net.Sockets.IOControlKeepAlive.Set(), System.BitConverter.ToSingle(), and System.BitConverter.ToUInt32().