Terraria: System.BitConverter.ToString
ToString() [3/3]
static string System.BitConverter.ToString (byte[] value, int startIndex, int length) inline static
Definition at line 397 of file BitConverter.cs.
    {
        if (value == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.value);
        }
        if (startIndex < 0 || (startIndex >= value.Length && startIndex > 0))
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.startIndex, ExceptionResource.ArgumentOutOfRange_Index);
        }
        if (length < 0)
        {
            throw new ArgumentOutOfRangeException("length", SR.ArgumentOutOfRange_GenericPositive);
        }
        if (startIndex > value.Length - length)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_ArrayPlusOffTooSmall, ExceptionArgument.value);
        }
        if (length == 0)
        {
            return string.Empty;
        }
        if (length > 715827882)
        {
            throw new ArgumentOutOfRangeException("length", SR.Format(SR.ArgumentOutOfRange_LengthTooLarge, 715827882));
        }
        return string.Create(length * 3 - 1, (value, startIndex, length), delegate(Span<char> dst, (byte[] value, int startIndex, int length) state)
        {
            ReadOnlySpan<byte> readOnlySpan = new ReadOnlySpan<byte>(state.value, state.startIndex, state.length);
            int num = 0;
            int num2 = 0;
            byte b = readOnlySpan[num++];
            dst[num2++] = HexConverter.ToCharUpper(b >> 4);
            dst[num2++] = HexConverter.ToCharUpper(b);
            while (num < readOnlySpan.Length)
            {
                b = readOnlySpan[num++];
                dst[num2++] = '-';
                dst[num2++] = HexConverter.ToCharUpper(b >> 4);
                dst[num2++] = HexConverter.ToCharUpper(b);
            }
        });
    }
References System.SR.ArgumentOutOfRange_GenericPositive, System.SR.ArgumentOutOfRange_LengthTooLarge, System.SR.Format(), System.length, System.ReadOnlySpan< T >.Length, System.startIndex, System.state, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), System.HexConverter.ToCharUpper(), and System.value.
Referenced by System.Reflection.Metadata.BlobBuilder.Display(), System.Reflection.Internal.MemoryBlock.GetDebuggerDisplay(), System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Read(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer(), System.Net.Security.SafeFreeContextBufferChannelBinding.ToString(), and System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ValidateChunkExtension().