Terraria: System.BitConverter.UInt32BitsToSingle
UInt32BitsToSingle()
static float System.BitConverter.UInt32BitsToSingle (uint value) inline static
Definition at line 565 of file BitConverter.cs.
    {
        return Int32BitsToSingle((int)value);
    }
References System.BitConverter.Int32BitsToSingle(), and System.value.
Referenced by System.Half.CreateSingle(), System.Half.CreateSingleNaN(), System.Number.NumberToSingle(), System.Half.operator float(), System.Single.operator&(), System.Single.operator^(), System.Single.operator|(), System.Single.operator~(), System.MathF.Round(), and System.Variant.ToObject().