Terraria: System.BitConverter.SingleToUInt32Bits
SingleToUInt32Bits()
static uint System.BitConverter.SingleToUInt32Bits (float value) inline static
Definition at line 558 of file BitConverter.cs.
    {
        return (uint)SingleToInt32Bits(value);
    }
References System.BitConverter.SingleToInt32Bits(), and System.value.
Referenced by System.Variant.Variant(), System.Number.ExtractFractionAndBiasedExponent(), System.Single.IsPow2(), System.Number.NumberToSingleFloatingPointBits(), System.Half.operator Half(), System.Single.operator&(), System.Single.operator^(), System.Single.operator|(), System.Single.operator~(), and System.MathF.Round().