Terraria: System.BitConverter.UInt64BitsToDouble
UInt64BitsToDouble()
static double System.BitConverter.UInt64BitsToDouble (ulong value) inline static
Definition at line 551 of file BitConverter.cs.
    {
        return Int64BitsToDouble((long)value);
    }
References System.BitConverter.Int64BitsToDouble(), and System.value.
Referenced by System.Half.CreateDouble(), System.Half.CreateDoubleNaN(), System.Xml.Xsl.XPathConvert.BigNumber.DblToRgbPrecise(), System.Number.NumberToDouble(), System.Xml.Xsl.XPathConvert.BigNumber.operator double(), System.Half.operator double(), System.Double.operator&(), System.Double.operator^(), System.Double.operator|(), System.Double.operator~(), and System.Math.Round().