Terraria: WindowService.SetQuickEditEnabled
SetQuickEditEnabled() [3/3]
void WindowService.SetQuickEditEnabled (bool enabled) inline
Implements IWindowService.
     {
         IntPtr stdHandle = NativeMethods.GetStdHandle(NativeMethods.StdHandleType.Input);
         if (NativeMethods.GetConsoleMode(stdHandle, out var lpMode))
         {
             lpMode = ((!enabled) ? (lpMode & ~NativeMethods.ConsoleMode.QuickEditMode) : (lpMode | NativeMethods.ConsoleMode.QuickEditMode));
             NativeMethods.SetConsoleMode(stdHandle, lpMode);
         }
     }
References NativeMethods.GetConsoleMode(), NativeMethods.GetStdHandle(), and NativeMethods.SetConsoleMode().