Terraria: System.Threading.ThreadPoolWorkQueue.WorkStealingQueueList.Remove
Remove()
static void System.Threading.ThreadPoolWorkQueue.WorkStealingQueueList.Remove (WorkStealingQueue queue) inline static
Definition at line 32 of file ThreadPoolWorkQueue.cs.
        {
            WorkStealingQueue[] queues;
            WorkStealingQueue[] array;
            do
            {
                queues = _queues;
                if (queues.Length == 0)
                {
                    break;
                }
                int num = Array.IndexOf(queues, queue);
                if (num == -1)
                {
                    break;
                }
                array = new WorkStealingQueue[queues.Length - 1];
                if (num == 0)
                {
                    Array.Copy(queues, 1, array, 0, array.Length);
                    continue;
                }
                if (num == queues.Length - 1)
                {
                    Array.Copy(queues, array, array.Length);
                    continue;
                }
                Array.Copy(queues, array, num);
                Array.Copy(queues, num + 1, array, num, array.Length - num);
            }
            while (Interlocked.CompareExchange(ref _queues, array, queues) != queues);
        }
References System.Threading.ThreadPoolWorkQueue.WorkStealingQueueList._queues, System.array, System.Threading.Interlocked.CompareExchange(), System.Array.Copy(), and System.Array.IndexOf().
Referenced by System.Threading.ThreadPoolWorkQueueThreadLocals.~ThreadPoolWorkQueueThreadLocals().