Terraria: System.Threading.ThreadPoolWorkQueue.WorkStealingQueueList.Add
Add()
static void System.Threading.ThreadPoolWorkQueue.WorkStealingQueueList.Add (WorkStealingQueue queue) inline static
Definition at line 18 of file ThreadPoolWorkQueue.cs.
        {
            WorkStealingQueue[] queues;
            WorkStealingQueue[] array;
            do
            {
                queues = _queues;
                array = new WorkStealingQueue[queues.Length + 1];
                Array.Copy(queues, array, queues.Length);
                array[^1] = queue;
            }
            while (Interlocked.CompareExchange(ref _queues, array, queues) != queues);
        }
References System.Threading.ThreadPoolWorkQueue.WorkStealingQueueList._queues, System.array, System.Threading.Interlocked.CompareExchange(), and System.Array.Copy().
Referenced by System.Threading.ThreadPoolWorkQueueThreadLocals.ThreadPoolWorkQueueThreadLocals().