Terraria: System.Linq.Expressions.Interpreter.ScriptingRuntimeHelpers.GetPrimitiveDefaultValue
GetPrimitiveDefaultValue()
static object System.Linq.Expressions.Interpreter.ScriptingRuntimeHelpers.GetPrimitiveDefaultValue (Type type) inline static package
Definition at line 20 of file ScriptingRuntimeHelpers.cs.
    {
        object obj;
        switch (type.GetTypeCode())
        {
        case TypeCode.Boolean:
            obj = Utils.BoxedFalse;
            break;
        case TypeCode.SByte:
            obj = Utils.BoxedDefaultSByte;
            break;
        case TypeCode.Byte:
            obj = Utils.BoxedDefaultByte;
            break;
        case TypeCode.Char:
            obj = Utils.BoxedDefaultChar;
            break;
        case TypeCode.Int16:
            obj = Utils.BoxedDefaultInt16;
            break;
        case TypeCode.Int32:
            obj = Utils.BoxedInt0;
            break;
        case TypeCode.Int64:
            obj = Utils.BoxedDefaultInt64;
            break;
        case TypeCode.UInt16:
            obj = Utils.BoxedDefaultUInt16;
            break;
        case TypeCode.UInt32:
            obj = Utils.BoxedDefaultUInt32;
            break;
        case TypeCode.UInt64:
            obj = Utils.BoxedDefaultUInt64;
            break;
        case TypeCode.Single:
            return Utils.BoxedDefaultSingle;
        case TypeCode.Double:
            return Utils.BoxedDefaultDouble;
        case TypeCode.DateTime:
            return Utils.BoxedDefaultDateTime;
        case TypeCode.Decimal:
            return Utils.BoxedDefaultDecimal;
        default:
            return null;
        }
        if (type.IsEnum)
        {
            obj = Enum.ToObject(type, obj);
        }
        return obj;
    }
References System.Linq.Expressions.Utils.BoxedDefaultByte, System.Linq.Expressions.Utils.BoxedDefaultChar, System.Linq.Expressions.Utils.BoxedDefaultDateTime, System.Linq.Expressions.Utils.BoxedDefaultDecimal, System.Linq.Expressions.Utils.BoxedDefaultDouble, System.Linq.Expressions.Utils.BoxedDefaultInt16, System.Linq.Expressions.Utils.BoxedDefaultInt64, System.Linq.Expressions.Utils.BoxedDefaultSByte, System.Linq.Expressions.Utils.BoxedDefaultSingle, System.Linq.Expressions.Utils.BoxedDefaultUInt16, System.Linq.Expressions.Utils.BoxedDefaultUInt32, System.Linq.Expressions.Utils.BoxedDefaultUInt64, System.Linq.Expressions.Utils.BoxedFalse, System.Linq.Expressions.Utils.BoxedInt0, System.obj, System.Enum.ToObject(), and System.type.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileDefaultExpression(), and System.Linq.Expressions.Interpreter.InstructionList.EmitInitializeLocal().