Terraria: System.Linq.Expressions.Interpreter.ScriptingRuntimeHelpers.Int32ToObject
Int32ToObject()
static object System.Linq.Expressions.Interpreter.ScriptingRuntimeHelpers.Int32ToObject (int i) inline static
Definition at line 7 of file ScriptingRuntimeHelpers.cs.
    {
        return i switch
        {
            -1 => Utils.BoxedIntM1,
            0 => Utils.BoxedInt0,
            1 => Utils.BoxedInt1,
            2 => Utils.BoxedInt2,
            3 => Utils.BoxedInt3,
            _ => i,
        };
    }
References System.Linq.Expressions.Utils.BoxedInt0, System.Linq.Expressions.Utils.BoxedInt1, System.Linq.Expressions.Utils.BoxedInt2, System.Linq.Expressions.Utils.BoxedInt3, and System.Linq.Expressions.Utils.BoxedIntM1.
Referenced by System.Linq.Expressions.Interpreter.InterpretedFrame.Push(), System.Linq.Expressions.Interpreter.AddInstruction.AddInt32.Run(), System.Linq.Expressions.Interpreter.AddOvfInstruction.AddOvfInt32.Run(), System.Linq.Expressions.Interpreter.DivInstruction.DivInt32.Run(), System.Linq.Expressions.Interpreter.ModuloInstruction.ModuloInt32.Run(), System.Linq.Expressions.Interpreter.MulInstruction.MulInt32.Run(), System.Linq.Expressions.Interpreter.MulOvfInstruction.MulOvfInt32.Run(), System.Linq.Expressions.Interpreter.SubInstruction.SubInt32.Run(), and System.Linq.Expressions.Interpreter.SubOvfInstruction.SubOvfInt32.Run().