Terraria: System.Xml.Schema.Datatype_List.TryParseValue
TryParseValue() [1/2]
override Exception System.Xml.Schema.Datatype_List.TryParseValue (object value, XmlNameTable nameTable, IXmlNamespaceResolver namespaceResolver, out object typedValue) inline package
Definition at line 105 of file Datatype_List.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        string text = value as string;
        typedValue = null;
        if (text != null)
        {
            return TryParseValue(text, nameTable, namespaceResolver, out typedValue);
        }
        Exception ex;
        try
        {
            object obj = ValueConverter.ChangeType(value, ValueType, namespaceResolver);
            Array array = obj as Array;
            bool hasLexicalFacets = _itemType.HasLexicalFacets;
            bool hasValueFacets = _itemType.HasValueFacets;
            FacetsChecker facetsChecker = _itemType.FacetsChecker;
            XmlValueConverter valueConverter = _itemType.ValueConverter;
            int num = 0;
            while (true)
            {
                if (num < array.Length)
                {
                    object value2 = array.GetValue(num);
                    if (hasLexicalFacets)
                    {
                        string parseString = (string)valueConverter.ChangeType(value2, typeof(string), namespaceResolver);
                        ex = facetsChecker.CheckLexicalFacets(ref parseString, _itemType);
                        if (ex != null)
{
                            break;
                        }
                    }
                    if (hasValueFacets)
                    {
                        ex = facetsChecker.CheckValueFacets(value2, _itemType);
                        if (ex != null)
{
                            break;
                        }
                    }
                    num++;
                    continue;
                }
                if (HasLexicalFacets)
                {
                    string parseString2 = (string)ValueConverter.ChangeType(obj, typeof(string), namespaceResolver);
                    ex = DatatypeImplementation.listFacetsChecker.CheckLexicalFacets(ref parseString2, this);
                    if (ex != null)
                    {
                        break;
                    }
                }
                if (HasValueFacets)
                {
                    ex = DatatypeImplementation.listFacetsChecker.CheckValueFacets(obj, this);
                    if (ex != null)
                    {
                        break;
                    }
                }
                typedValue = obj;
                return null;
            }
        }
        catch (FormatException ex2)
        {
            ex = ex2;
        }
        catch (InvalidCastException ex3)
        {
            ex = ex3;
        }
        catch (OverflowException ex4)
        {
            ex = ex4;
        }
        catch (ArgumentException ex5)
        {
            ex = ex5;
        }
        return ex;
    }
References System.Xml.Schema.Datatype_List._itemType, System.array, System.Xml.Array, System.Xml.Schema.XmlValueConverter.ChangeType(), System.Xml.Dictionary, System.Xml.Schema.DatatypeImplementation.FacetsChecker, System.Xml.Schema.DatatypeImplementation.HasLexicalFacets, System.Xml.Schema.DatatypeImplementation.HasValueFacets, System.Xml.Schema.DatatypeImplementation.listFacetsChecker, System.obj, System.text, System.Xml.Schema.Datatype_List.TryParseValue(), System.value, and System.Xml.Schema.DatatypeImplementation.ValueConverter.
Referenced by System.Xml.Schema.Datatype_List.TryParseValue().