Terraria: System.Threading.PeriodicTimer.State.Signal
Signal()
void System.Threading.PeriodicTimer.State.Signal (bool stopping = false, CancellationToken cancellationToken = default(CancellationToken)) inline
Definition at line 53 of file PeriodicTimer.cs.
        {
            bool flag = false;
            lock (this)
            {
                _stopped |= stopping;
                if (!_signaled)
                {
                    _signaled = true;
                    flag = _activeWait;
                }
            }
            if (flag)
            {
                if (cancellationToken.IsCancellationRequested)
                {
                    _mrvtsc.SetException(ExceptionDispatchInfo.SetCurrentStackTrace(new OperationCanceledException(cancellationToken)));
                }
                else
                {
                    _mrvtsc.SetResult(result: true);
                }
            }
        }
References System.Threading.PeriodicTimer.State._activeWait, System.Threading.PeriodicTimer.State._mrvtsc, System.Threading.PeriodicTimer.State._signaled, System.Threading.PeriodicTimer.State._stopped, System.cancellationToken, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetException(), and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetResult().
Referenced by System.Threading.PeriodicTimer.Dispose().