Terraria: System.Text.EncodingTable.GetCodePageDataItem
GetCodePageDataItem()
static CodePageDataItem System.Text.EncodingTable.GetCodePageDataItem (int codePage) inline static package
Definition at line 133 of file EncodingTable.cs.
    {
        if (s_codePageToCodePageData == null)
        {
            Interlocked.CompareExchange(ref s_codePageToCodePageData, new CodePageDataItem[s_mappedCodePages.Length], null);
        }
        int num;
        switch (codePage)
        {
        case 1200:
            num = 0;
            break;
        case 1201:
            num = 1;
            break;
        case 12000:
            num = 2;
            break;
        case 12001:
            num = 3;
            break;
        case 20127:
            num = 4;
            break;
        case 28591:
            num = 5;
            break;
        case 65000:
            num = 6;
            break;
        case 65001:
            num = 7;
            break;
        default:
            return null;
        }
        CodePageDataItem codePageDataItem = s_codePageToCodePageData[num];
        if (codePageDataItem == null)
        {
            Interlocked.CompareExchange(ref s_codePageToCodePageData[num], InternalGetCodePageDataItem(codePage, num), null);
            codePageDataItem = s_codePageToCodePageData[num];
        }
        return codePageDataItem;
    }
References System.Threading.Interlocked.CompareExchange(), System.Text.EncodingTable.InternalGetCodePageDataItem(), System.Text.EncodingTable.s_codePageToCodePageData, and System.Text.EncodingTable.s_mappedCodePages.
Referenced by System.Text.Encoding.GetDataItem().