Terraria: System.Text.EncodingTable.GetNameFromCodePage
GetNameFromCodePage()
static string System.Text.EncodingTable.GetNameFromCodePage (int codePage, string names, int[] indices, Dictionary< int, string > cache) inline static private
Definition at line 251 of file EncodingTable.cs.
    {
        for (int i = 0; i < s_mappedCodePages.Length; i++)
        {
            if (s_mappedCodePages[i] != codePage)
            {
                continue;
            }
            s_cacheLock.EnterUpgradeableReadLock();
            try
            {
                if (cache.TryGetValue(codePage, out var value))
                {
                    return value;
                }
                value = names.Substring(indices[i], indices[i + 1] - indices[i]);
                s_cacheLock.EnterWriteLock();
                try
                {
                    if (cache.TryGetValue(codePage, out var value2))
                    {
                        return value2;
                    }
                    cache.Add(codePage, value);
                    return value;
                }
                finally
                {
                    s_cacheLock.ExitWriteLock();
                }
            }
            finally
            {
                s_cacheLock.ExitUpgradeableReadLock();
            }
        }
        return null;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.indices, System.Text.EncodingTable.s_cacheLock, System.Text.EncodingTable.s_mappedCodePages, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Text.EncodingTable.GetEnglishNameFromCodePage(), and System.Text.EncodingTable.GetWebNameFromCodePage().