Terraria: System.Text.EncodingTable.GetEncodings
GetEncodings() [2/2]
static EncodingInfo[] System.Text.EncodingTable.GetEncodings (Dictionary< int, EncodingInfo > encodingInfoList) inline static package
Definition at line 107 of file EncodingTable.cs.
    {
        ushort[] array = s_mappedCodePages;
        string text = "utf-16utf-16BEutf-32utf-32BEus-asciiiso-8859-1utf-7utf-8";
        int[] array2 = s_webNameIndices;
        for (int i = 0; i < array.Length; i++)
        {
            int num = array[i];
            if (!encodingInfoList.ContainsKey(num) && (num != 65000 || LocalAppContextSwitches.EnableUnsafeUTF7Encoding))
            {
                encodingInfoList[num] = new EncodingInfo(num, text[array2[i]..array2[i + 1]], GetDisplayName(num, i));
            }
        }
        if (!LocalAppContextSwitches.EnableUnsafeUTF7Encoding)
        {
            encodingInfoList.Remove(65000);
        }
        EncodingInfo[] array3 = new EncodingInfo[encodingInfoList.Count];
        int num2 = 0;
        foreach (KeyValuePair<int, EncodingInfo> encodingInfo in encodingInfoList)
        {
            array3[num2++] = encodingInfo.Value;
        }
        return array3;
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.LocalAppContextSwitches.EnableUnsafeUTF7Encoding, System.Text.EncodingTable.GetDisplayName(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Text.EncodingTable.s_mappedCodePages, System.Text.EncodingTable.s_webNameIndices, and System.text.