Terraria: System.Threading.PeriodicTimer.State.WaitForNextTickAsync
WaitForNextTickAsync()
ValueTask< bool > System.Threading.PeriodicTimer.State.WaitForNextTickAsync (PeriodicTimer owner, CancellationToken cancellationToken) inline
Definition at line 23 of file PeriodicTimer.cs.
        {
            lock (this)
            {
                if (_activeWait)
                {
                    ThrowHelper.ThrowInvalidOperationException();
                }
                if (cancellationToken.IsCancellationRequested)
                {
                    return ValueTask.FromCanceled<bool>(cancellationToken);
                }
                if (_signaled)
                {
                    if (!_stopped)
                    {
                        _signaled = false;
                    }
                    return new ValueTask<bool>(!_stopped);
                }
                _owner = owner;
                _activeWait = true;
                _ctr = cancellationToken.UnsafeRegister(delegate(object state, CancellationToken cancellationToken)
                {
                    ((State)state).Signal(stopping: false, cancellationToken);
                }, this);
                return new ValueTask<bool>(this, _mrvtsc.Version);
            }
        }
References System.Threading.PeriodicTimer.State._activeWait, System.Threading.PeriodicTimer.State._ctr, System.Threading.PeriodicTimer.State._mrvtsc, System.Threading.PeriodicTimer.State._owner, System.Threading.PeriodicTimer.State._signaled, System.Threading.PeriodicTimer.State._stopped, System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.state, System.ThrowHelper.ThrowInvalidOperationException(), and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.Version.
Referenced by System.Threading.PeriodicTimer.WaitForNextTickAsync().