Terraria: System.Threading.PeriodicTimer.State.GetResult
GetResult()
bool IValueTaskSource< bool >. System.Threading.PeriodicTimer.State.GetResult (short token) inline private
Definition at line 78 of file PeriodicTimer.cs.
        {
            _ctr.Dispose();
            lock (this)
            {
                try
                {
                    _mrvtsc.GetResult(token);
                }
                finally
                {
                    _mrvtsc.Reset();
                    _ctr = default(CancellationTokenRegistration);
                    _activeWait = false;
                    _owner = null;
                    if (!_stopped)
                    {
                        _signaled = false;
                    }
                }
                return !_stopped;
            }
        }
References System.Threading.PeriodicTimer.State._activeWait, System.Threading.PeriodicTimer.State._ctr, System.Threading.PeriodicTimer.State._mrvtsc, System.Threading.PeriodicTimer.State._owner, System.Threading.PeriodicTimer.State._signaled, System.Threading.PeriodicTimer.State._stopped, System.Threading.CancellationTokenRegistration.Dispose(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.GetResult(), and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.Reset().