Terraria: SceneMetrics.Reset
Reset()
void SceneMetrics.Reset () inline
     {
         Array.Clear(_tileCounts, 0, _tileCounts.Length);
         Array.Clear(_liquidCounts, 0, _liquidCounts.Length);
         SandTileCount = 0;
         EvilTileCount = 0;
         BloodTileCount = 0;
         GraveyardTileCount = 0;
         MushroomTileCount = 0;
         SnowTileCount = 0;
         HolyTileCount = 0;
         MeteorTileCount = 0;
         JungleTileCount = 0;
         DungeonTileCount = 0;
         HasCampfire = false;
         HasSunflower = false;
         HasGardenGnome = false;
         HasStarInBottle = false;
         HasHeartLantern = false;
         HasClock = false;
         HasCatBast = false;
         ActiveMusicBox = -1;
         WaterCandleCount = 0;
         ActiveFountainColor = -1;
         ActiveMonolithType = -1;
         bestOre = -1;
         BloodMoonMonolith = false;
         MoonLordMonolith = false;
         EchoMonolith = false;
         ShimmerMonolithState = 0;
         Array.Clear(NPCBannerBuff, 0, NPCBannerBuff.Length);
         hasBanner = false;
         CanPlayCreditsRoll = false;
     }
References _liquidCounts, _tileCounts, ActiveFountainColor, ActiveMonolithType, ActiveMusicBox, bestOre, BloodMoonMonolith, BloodTileCount, CanPlayCreditsRoll, DungeonTileCount, EchoMonolith, EvilTileCount, GraveyardTileCount, hasBanner, HasCampfire, HasCatBast, HasClock, HasGardenGnome, HasHeartLantern, HasStarInBottle, HasSunflower, HolyTileCount, JungleTileCount, MeteorTileCount, MoonLordMonolith, MushroomTileCount, NPCBannerBuff, SandTileCount, ShimmerMonolithState, SnowTileCount, and WaterCandleCount.
Referenced by SceneMetrics(), Main.DrawMenu(), and ScanAndExportToMain().