Terraria: System.Xml.XmlReaderSettings.AddConformanceWrapper
AddConformanceWrapper()
XmlReader System.Xml.XmlReaderSettings.AddConformanceWrapper (XmlReader baseReader) inline package
Definition at line 552 of file XmlReaderSettings.cs.
    {
        XmlReaderSettings settings = baseReader.Settings;
        bool checkCharacters = false;
        bool ignoreWhitespace = false;
        bool ignoreComments = false;
        bool ignorePis = false;
        DtdProcessing dtdProcessing = (DtdProcessing)(-1);
        bool flag = false;
        if (settings == null)
        {
            if (_conformanceLevel != 0 && _conformanceLevel != XmlReader.GetV1ConformanceLevel(baseReader))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.Xml_IncompatibleConformanceLevel, _conformanceLevel.ToString()));
            }
            XmlTextReader xmlTextReader = baseReader as XmlTextReader;
            if (xmlTextReader == null && baseReader is XmlValidatingReader xmlValidatingReader)
            {
                xmlTextReader = (XmlTextReader)xmlValidatingReader.Reader;
            }
            if (_ignoreWhitespace)
            {
                WhitespaceHandling whitespaceHandling = WhitespaceHandling.All;
                if (xmlTextReader != null)
                {
                    whitespaceHandling = xmlTextReader.WhitespaceHandling;
                }
                if (whitespaceHandling == WhitespaceHandling.All)
                {
                    ignoreWhitespace = true;
                    flag = true;
                }
            }
            if (_ignoreComments)
            {
                ignoreComments = true;
                flag = true;
            }
            if (_ignorePIs)
            {
                ignorePis = true;
                flag = true;
            }
            DtdProcessing dtdProcessing2 = DtdProcessing.Parse;
            if (xmlTextReader != null)
            {
                dtdProcessing2 = xmlTextReader.DtdProcessing;
            }
            if ((_dtdProcessing == DtdProcessing.Prohibit && dtdProcessing2 != 0) || (_dtdProcessing == DtdProcessing.Ignore && dtdProcessing2 == DtdProcessing.Parse))
            {
                dtdProcessing = _dtdProcessing;
                flag = true;
            }
        }
        else
        {
            if (_conformanceLevel != settings.ConformanceLevel && _conformanceLevel != 0)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.Xml_IncompatibleConformanceLevel, _conformanceLevel.ToString()));
            }
            if (_checkCharacters && !settings.CheckCharacters)
            {
                checkCharacters = true;
                flag = true;
            }
            if (_ignoreWhitespace && !settings.IgnoreWhitespace)
            {
                ignoreWhitespace = true;
                flag = true;
            }
            if (_ignoreComments && !settings.IgnoreComments)
            {
                ignoreComments = true;
                flag = true;
            }
            if (_ignorePIs && !settings.IgnoreProcessingInstructions)
            {
                ignorePis = true;
                flag = true;
            }
            if ((_dtdProcessing == DtdProcessing.Prohibit && settings.DtdProcessing != 0) || (_dtdProcessing == DtdProcessing.Ignore && settings.DtdProcessing == DtdProcessing.Parse))
            {
                dtdProcessing = _dtdProcessing;
                flag = true;
            }
        }
        if (flag)
        {
            if (baseReader is IXmlNamespaceResolver readerAsNSResolver)
            {
                return new XmlCharCheckingReaderWithNS(baseReader, readerAsNSResolver, checkCharacters, ignoreWhitespace, ignoreComments, ignorePis, dtdProcessing);
            }
            return new XmlCharCheckingReader(baseReader, checkCharacters, ignoreWhitespace, ignoreComments, ignorePis, dtdProcessing);
        }
        return baseReader;
    }
References System.Xml.XmlReaderSettings._checkCharacters, System.Xml.XmlReaderSettings._conformanceLevel, System.Xml.XmlReaderSettings._dtdProcessing, System.Xml.XmlReaderSettings._ignoreComments, System.Xml.XmlReaderSettings._ignorePIs, System.Xml.XmlReaderSettings._ignoreWhitespace, System.Xml.XmlReaderSettings.CheckCharacters, System.Xml.XmlReaderSettings.ConformanceLevel, System.Xml.Dictionary, System.Xml.XmlReaderSettings.DtdProcessing, System.SR.Format(), System.Xml.XmlReader.GetV1ConformanceLevel(), System.Xml.XmlReaderSettings.IgnoreComments, System.Xml.XmlReaderSettings.IgnoreProcessingInstructions, System.Xml.XmlReaderSettings.IgnoreWhitespace, and System.SR.Xml_IncompatibleConformanceLevel.
Referenced by System.Xml.XmlReaderSettings.AddValidationAndConformanceInternal(), and System.Xml.XmlReaderSettings.AddValidationInternal().