Terraria: System.Xml.XmlReaderSettings.AddValidationInternal
AddValidationInternal()
XmlReader System.Xml.XmlReaderSettings.AddValidationInternal (XmlReader reader, XmlResolver resolver, bool addConformanceWrapper) inline private
Definition at line 530 of file XmlReaderSettings.cs.
    {
        if (_validationType == ValidationType.DTD)
        {
            reader = CreateDtdValidatingReader(reader);
        }
        if (addConformanceWrapper)
        {
            reader = AddConformanceWrapper(reader);
        }
        if (_validationType == ValidationType.Schema)
        {
            reader = new XsdValidatingReader(reader, GetXmlResolver_CheckConfig(), this);
        }
        return reader;
    }
References System.Xml.XmlReaderSettings._validationType, System.Xml.XmlReaderSettings.AddConformanceWrapper(), System.Xml.XmlReaderSettings.CreateDtdValidatingReader(), System.Xml.Dictionary, and System.Xml.XmlReaderSettings.GetXmlResolver_CheckConfig().