Terraria: System.Xml.XmlReaderSettings.CreateReader
CreateReader() [2/4]
XmlReader System.Xml.XmlReaderSettings.CreateReader (string inputUri, XmlParserContext inputContext) inline package
Definition at line 377 of file XmlReaderSettings.cs.
    {
        if (inputUri == null)
        {
            throw new ArgumentNullException("inputUri");
        }
        if (inputUri.Length == 0)
        {
            throw new ArgumentException(System.SR.XmlConvert_BadUri, "inputUri");
        }
        XmlResolver uriResolver = GetXmlResolver() ?? new XmlUrlResolver();
        XmlReader xmlReader = new XmlTextReaderImpl(inputUri, this, inputContext, uriResolver);
        if (ValidationType != 0)
        {
            xmlReader = AddValidation(xmlReader);
        }
        if (_useAsync)
        {
            xmlReader = XmlAsyncCheckReader.CreateAsyncCheckWrapper(xmlReader);
        }
        return xmlReader;
    }
References System.Xml.XmlReaderSettings._useAsync, System.Xml.XmlReaderSettings.AddValidation(), System.Xml.ArgumentException, System.Xml.XmlAsyncCheckReader.CreateAsyncCheckWrapper(), System.Xml.Dictionary, System.Xml.XmlReaderSettings.GetXmlResolver(), and System.SR.XmlConvert_BadUri.
Referenced by System.Xml.XmlReader.Create(), System.Xml.XmlReader.Create(), System.Xml.XmlReader.Create(), System.Xml.XmlReader.Create(), System.Xml.XmlReader.Create(), and System.Xml.XmlReader.Create().