Terraria: System.Xml.XmlReaderSettings.AddValidationAndConformanceInternal
AddValidationAndConformanceInternal()
XmlReader System.Xml.XmlReaderSettings.AddValidationAndConformanceInternal (XmlReader reader, XmlResolver resolver, bool addConformanceWrapper) inline private
Definition at line 514 of file XmlReaderSettings.cs.
    {
        if (_validationType == ValidationType.None)
        {
            if (addConformanceWrapper)
            {
                reader = AddConformanceWrapper(reader);
            }
        }
        else
        {
            reader = _addValidationFunc(reader, resolver, addConformanceWrapper);
        }
        return reader;
    }
References System.Xml.XmlReaderSettings._addValidationFunc, System.Xml.XmlReaderSettings._validationType, System.Xml.XmlReaderSettings.AddConformanceWrapper(), and System.Xml.Dictionary.
Referenced by System.Xml.XmlReaderSettings.AddValidation(), and System.Xml.XmlReaderSettings.AddValidationAndConformanceWrapper().