Terraria: System.Xml.XmlReaderSettings.AddValidation
AddValidation()
XmlReader System.Xml.XmlReaderSettings.AddValidation (XmlReader reader) inline package
Definition at line 490 of file XmlReaderSettings.cs.
    {
        XmlResolver xmlResolver = null;
        if (_validationType == ValidationType.Schema)
        {
            xmlResolver = GetXmlResolver_CheckConfig();
            if (xmlResolver == null && !IsXmlResolverSet)
            {
                xmlResolver = new XmlUrlResolver();
            }
        }
        return AddValidationAndConformanceInternal(reader, xmlResolver, addConformanceWrapper: false);
    }
References System.Xml.XmlReaderSettings._validationType, System.Xml.XmlReaderSettings.AddValidationAndConformanceInternal(), System.Xml.Dictionary, System.Xml.XmlReaderSettings.GetXmlResolver_CheckConfig(), and System.Xml.XmlReaderSettings.IsXmlResolverSet.
Referenced by System.Xml.XmlReaderSettings.CreateReader(), System.Xml.XmlReaderSettings.CreateReader(), System.Xml.XmlReaderSettings.CreateReader(), and System.Xml.XmlReader.CreateSqlReader().