Terraria: System.Net.Http.SocketsHttpHandler.SetupHandlerChain
SetupHandlerChain()
HttpMessageHandlerStage System.Net.Http.SocketsHttpHandler.SetupHandlerChain () inline private
Definition at line 482 of file SocketsHttpHandler.cs.
    {
        HttpConnectionSettings httpConnectionSettings = _settings.CloneAndNormalize();
        HttpConnectionPoolManager poolManager = new HttpConnectionPoolManager(httpConnectionSettings);
        HttpMessageHandlerStage httpMessageHandlerStage = ((httpConnectionSettings._credentials != null) ? ((HttpMessageHandlerStage)new HttpAuthenticatedConnectionHandler(poolManager)) : ((HttpMessageHandlerStage)new HttpConnectionHandler(poolManager)));
        if (DiagnosticsHandler.IsGloballyEnabled())
        {
            DistributedContextPropagator activityHeadersPropagator = httpConnectionSettings._activityHeadersPropagator;
            if (activityHeadersPropagator != null)
            {
                httpMessageHandlerStage = new DiagnosticsHandler(httpMessageHandlerStage, activityHeadersPropagator, httpConnectionSettings._allowAutoRedirect);
            }
        }
        if (httpConnectionSettings._allowAutoRedirect)
        {
            HttpMessageHandlerStage redirectInnerHandler = ((httpConnectionSettings._credentials == null || httpConnectionSettings._credentials is CredentialCache) ? httpMessageHandlerStage : new HttpConnectionHandler(poolManager));
            httpMessageHandlerStage = new RedirectHandler(httpConnectionSettings._maxAutomaticRedirections, httpMessageHandlerStage, redirectInnerHandler);
        }
        if (httpConnectionSettings._automaticDecompression != 0)
        {
            httpMessageHandlerStage = new DecompressionHandler(httpConnectionSettings._automaticDecompression, httpMessageHandlerStage);
        }
        if (Interlocked.CompareExchange(ref _handler, httpMessageHandlerStage, null) != null)
        {
            httpMessageHandlerStage.Dispose();
        }
        return _handler;
    }
References System.Net.Http.SocketsHttpHandler._handler, System.Net.Http.SocketsHttpHandler._settings, System.Net.Http.HttpConnectionSettings.CloneAndNormalize(), System.Threading.Interlocked.CompareExchange(), and System.Net.Http.DiagnosticsHandler.IsGloballyEnabled().
Referenced by System.Net.Http.SocketsHttpHandler.Send(), and System.Net.Http.SocketsHttpHandler.SendAsync().