Terraria: System.Net.Http.SocketsHttpHandler.SendAsync
SendAsync()
override Task< HttpResponseMessage > System.Net.Http.SocketsHttpHandler.SendAsync (HttpRequestMessage request, CancellationToken cancellationToken) inline package
Definition at line 536 of file SocketsHttpHandler.cs.
    {
        if (request == null)
        {
            throw new ArgumentNullException("request", System.SR.net_http_handler_norequest);
        }
        CheckDisposed();
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled<HttpResponseMessage>(cancellationToken);
        }
        HttpMessageHandler httpMessageHandler = _handler ?? SetupHandlerChain();
        Exception ex = ValidateAndNormalizeRequest(request);
        if (ex != null)
        {
            return Task.FromException<HttpResponseMessage>(ex);
        }
        return httpMessageHandler.SendAsync(request, cancellationToken);
    }
References System.Net.Http.SocketsHttpHandler._handler, System.cancellationToken, System.Net.Http.SocketsHttpHandler.CheckDisposed(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromException(), System.SR.net_http_handler_norequest, System.Net.Http.SocketsHttpHandler.SetupHandlerChain(), and System.Net.Http.SocketsHttpHandler.ValidateAndNormalizeRequest().