Terraria: System.Net.Http.SocketsHttpHandler.Send
Send()
override HttpResponseMessage System.Net.Http.SocketsHttpHandler.Send (HttpRequestMessage request, CancellationToken cancellationToken) inline package virtual
Reimplemented from System.Net.Http.HttpMessageHandler.
Definition at line 511 of file SocketsHttpHandler.cs.
    {
        if (request == null)
        {
            throw new ArgumentNullException("request", System.SR.net_http_handler_norequest);
        }
        if (request.Version.Major >= 2)
        {
            throw new NotSupportedException(System.SR.Format(System.SR.net_http_http2_sync_not_supported, GetType()));
        }
        if (request.VersionPolicy == HttpVersionPolicy.RequestVersionOrHigher)
        {
            throw new NotSupportedException(System.SR.Format(System.SR.net_http_upgrade_not_enabled_sync, "Send", request.VersionPolicy));
        }
        CheckDisposed();
        cancellationToken.ThrowIfCancellationRequested();
        HttpMessageHandlerStage httpMessageHandlerStage = _handler ?? SetupHandlerChain();
        Exception ex = ValidateAndNormalizeRequest(request);
        if (ex != null)
        {
            throw ex;
        }
        return httpMessageHandlerStage.Send(request, cancellationToken);
    }
References System.Net.Http.SocketsHttpHandler._handler, System.cancellationToken, System.Net.Http.SocketsHttpHandler.CheckDisposed(), System.SR.Format(), System.SR.net_http_handler_norequest, System.SR.net_http_http2_sync_not_supported, System.SR.net_http_upgrade_not_enabled_sync, System.Net.Http.SocketsHttpHandler.SetupHandlerChain(), and System.Net.Http.SocketsHttpHandler.ValidateAndNormalizeRequest().