Terraria: System.Net.Http.SocketsHttpHandler.ValidateAndNormalizeRequest
ValidateAndNormalizeRequest()
Exception System.Net.Http.SocketsHttpHandler.ValidateAndNormalizeRequest (HttpRequestMessage request) inline private
Definition at line 556 of file SocketsHttpHandler.cs.
    {
        if (request.Version.Major == 0)
        {
            return new NotSupportedException(System.SR.net_http_unsupported_version);
        }
        if (request.HasHeaders && request.Headers.TransferEncodingChunked.GetValueOrDefault())
        {
            if (request.Content == null)
            {
                return new HttpRequestException(System.SR.net_http_client_execution_error, new InvalidOperationException(System.SR.net_http_chunked_not_allowed_with_empty_content));
            }
            request.Content.Headers.ContentLength = null;
        }
        else if (request.Content != null && !request.Content.Headers.ContentLength.HasValue)
        {
            request.Headers.TransferEncodingChunked = true;
        }
        if (request.Version.Minor == 0 && request.Version.Major == 1 && request.HasHeaders)
        {
            if (request.Headers.TransferEncodingChunked == true)
            {
                return new NotSupportedException(System.SR.net_http_unsupported_chunking);
            }
            if (request.Headers.ExpectContinue == true)
            {
                request.Headers.ExpectContinue = false;
            }
        }
        Uri requestUri = request.RequestUri;
        if ((object)requestUri == null || !requestUri.IsAbsoluteUri)
        {
            return new InvalidOperationException(System.SR.net_http_client_invalid_requesturi);
        }
        if (!HttpUtilities.IsSupportedScheme(requestUri.Scheme))
        {
            return new NotSupportedException(System.SR.Format(System.SR.net_http_unsupported_requesturi_scheme, requestUri.Scheme));
        }
        return null;
    }
References System.SR.Format(), System.Net.Http.HttpUtilities.IsSupportedScheme(), System.SR.net_http_chunked_not_allowed_with_empty_content, System.SR.net_http_client_execution_error, System.SR.net_http_client_invalid_requesturi, System.SR.net_http_unsupported_chunking, System.SR.net_http_unsupported_requesturi_scheme, and System.SR.net_http_unsupported_version.
Referenced by System.Net.Http.SocketsHttpHandler.Send(), and System.Net.Http.SocketsHttpHandler.SendAsync().