Terraria: System.Threading.Tasks.TaskReplicator.Run< TState >
Run< TState >()
static void System.Threading.Tasks.TaskReplicator.Run< TState > (ReplicatableUserAction< TState > action, ParallelOptions options, bool stopOnFirstFailure) inline static
Definition at line 125 of file TaskReplicator.cs.
    {
        if (OperatingSystem.IsBrowser())
        {
            int timeout = 2147483646;
            TState replicaState = default(TState);
            action(ref replicaState, timeout, out var yieldedBeforeCompletion);
            if (yieldedBeforeCompletion)
            {
                throw new Exception("Replicated tasks cannot yield in this single-threaded browser environment");
            }
            return;
        }
        int maxConcurrency = ((options.EffectiveMaxConcurrencyLevel > 0) ? options.EffectiveMaxConcurrencyLevel : int.MaxValue);
        TaskReplicator taskReplicator = new TaskReplicator(options, stopOnFirstFailure);
        new Replica<TState>(taskReplicator, maxConcurrency, 1073741823, action).Start();
        Replica result;
        while (taskReplicator._pendingReplicas.TryDequeue(out result))
        {
            result.Wait();
        }
        if (taskReplicator._exceptions != null)
        {
            throw new AggregateException(taskReplicator._exceptions);
        }
    }
References System.Threading.Tasks.TaskReplicator.TaskReplicator(), System.Threading.Tasks.TaskReplicator._exceptions, System.Threading.Tasks.TaskReplicator._pendingReplicas, System.action, System.OperatingSystem.IsBrowser(), System.options, System.Threading.Tasks.TaskReplicator.Replica< TState >.Start(), System.timeout, and System.Threading.Tasks.TaskReplicator.Replica< TState >.Wait().