Terraria: Internal.Cryptography.AsymmetricAlgorithmHelpers.TryConvertIeee1363ToDer
TryConvertIeee1363ToDer()
static bool Internal.Cryptography.AsymmetricAlgorithmHelpers.TryConvertIeee1363ToDer (ReadOnlySpan< byte > input, Span< byte > destination, out int bytesWritten) inline static package
Definition at line 15 of file AsymmetricAlgorithmHelpers.cs.
    {
        AsnWriter asnWriter = WriteIeee1363ToDer(input);
        return asnWriter.TryEncode(destination, out bytesWritten);
    }
References System.destination, System.input, System.Formats.Asn1.AsnWriter.TryEncode(), and Internal.Cryptography.AsymmetricAlgorithmHelpers.WriteIeee1363ToDer().
Referenced by System.Security.Cryptography.DSAImplementation.DSACng.TryCreateSignatureCore(), and System.Security.Cryptography.ECDsaImplementation.ECDsaCng.TrySignHashCore().