Terraria: Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertSignatureToIeeeP1363
ConvertSignatureToIeeeP1363() [1/3]
static byte[] Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertSignatureToIeeeP1363 (DSASignatureFormat currentFormat, ReadOnlySpan< byte > signature, int fieldSizeBits) inline static package
Definition at line 109 of file AsymmetricAlgorithmHelpers.cs.
    {
        return currentFormat switch
        {
            DSASignatureFormat.IeeeP1363FixedFieldConcatenation => signature.ToArray(),
            DSASignatureFormat.Rfc3279DerSequence => ConvertDerToIeee1363(signature, fieldSizeBits),
            _ => throw new CryptographicException(System.SR.Cryptography_UnknownSignatureFormat, currentFormat.ToString()),
        };
    }
References Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertDerToIeee1363(), System.SR.Cryptography_UnknownSignatureFormat, and System.ReadOnlySpan< T >.ToArray().
Referenced by Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertSignatureToIeeeP1363(), and Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertSignatureToIeeeP1363().