Terraria: Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertDerToIeee1363
ConvertDerToIeee1363() [2/2]
static int Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertDerToIeee1363 (ReadOnlySpan< byte > input, int fieldSizeBits, Span< byte > destination) inline static package
Definition at line 41 of file AsymmetricAlgorithmHelpers.cs.
    {
        int num = BitsToBytes(fieldSizeBits);
        int result = 2 * num;
        try
        {
            AsnValueReader asnValueReader = new AsnValueReader(input, AsnEncodingRules.DER);
            AsnValueReader asnValueReader2 = asnValueReader.ReadSequence();
            asnValueReader.ThrowIfNotEmpty();
            ReadOnlySpan<byte> signatureField = asnValueReader2.ReadIntegerBytes();
            ReadOnlySpan<byte> signatureField2 = asnValueReader2.ReadIntegerBytes();
            asnValueReader2.ThrowIfNotEmpty();
            CopySignatureField(signatureField, destination.Slice(0, num));
            CopySignatureField(signatureField2, destination.Slice(num, num));
            return result;
        }
        catch (AsnContentException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
        }
    }
References Internal.Cryptography.AsymmetricAlgorithmHelpers.BitsToBytes(), Internal.Cryptography.AsymmetricAlgorithmHelpers.CopySignatureField(), System.SR.Cryptography_Der_Invalid_Encoding, System.destination, System.input, System.Formats.Asn1.AsnValueReader.ReadIntegerBytes(), System.Formats.Asn1.AsnValueReader.ReadSequence(), System.ReadOnlySpan< T >.Slice(), and System.Formats.Asn1.AsnValueReader.ThrowIfNotEmpty().