Terraria: Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertFromIeeeP1363Signature
ConvertFromIeeeP1363Signature()
static byte[] Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertFromIeeeP1363Signature (byte[] signature, DSASignatureFormat targetFormat) inline static package
Definition at line 99 of file AsymmetricAlgorithmHelpers.cs.
    {
        return targetFormat switch
        {
            DSASignatureFormat.IeeeP1363FixedFieldConcatenation => signature,
            DSASignatureFormat.Rfc3279DerSequence => ConvertIeee1363ToDer(signature),
            _ => throw new CryptographicException(System.SR.Cryptography_UnknownSignatureFormat, targetFormat.ToString()),
        };
    }
References Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertIeee1363ToDer(), and System.SR.Cryptography_UnknownSignatureFormat.
Referenced by System.Security.Cryptography.DSA.CreateSignatureCore(), System.Security.Cryptography.DSA.SignDataCore(), System.Security.Cryptography.DSA.TryCreateSignatureCore(), and System.Security.Cryptography.ECDsa.TrySignHashCore().