Terraria: Terraria.Graphics.VertexStrip.PrepareStrip
PrepareStrip()
void Terraria.Graphics.VertexStrip.PrepareStrip (Vector2[] positions, float[] rotations, StripColorFunction colorFunction, StripHalfWidthFunction widthFunction, Vector2 offsetForAllPositions = default(Vector2), int? expectedVertexPairsAmount = null, bool includeBacksides = false) inline
Definition at line 46 of file VertexStrip.cs.
    {
        int num = positions.Length;
        int num2 = (_vertexAmountCurrentlyMaintained = num * 2);
        if (_vertices.Length < num2)
        {
            Array.Resize(ref _vertices, num2);
        }
        int num3 = num;
        if (expectedVertexPairsAmount.HasValue)
        {
            num3 = expectedVertexPairsAmount.Value;
        }
        for (int i = 0; i < num; i++)
        {
            if (positions[i] == Vector2.Zero)
            {
                num = i - 1;
                _vertexAmountCurrentlyMaintained = num * 2;
                break;
            }
            Vector2 pos = positions[i] + offsetForAllPositions;
            float rot = MathHelper.WrapAngle(rotations[i]);
            int indexOnVertexArray = i * 2;
            float progressOnStrip = (float)i / (float)(num3 - 1);
            AddVertex(colorFunction, widthFunction, pos, rot, indexOnVertexArray, progressOnStrip);
        }
        PrepareIndices(num, includeBacksides);
    }
References Terraria.Graphics.VertexStrip._vertexAmountCurrentlyMaintained, Terraria.Graphics.VertexStrip._vertices, Terraria.Graphics.VertexStrip.AddVertex(), and Terraria.Graphics.VertexStrip.PrepareIndices().
Referenced by Terraria.Graphics.EmpressBladeDrawer.Draw(), and Terraria.Graphics.FinalFractalHelper.Draw().