Terraria: System.Net.Security.SecureChannel.Close
Close()
void System.Net.Security.SecureChannel.Close () inline package
Definition at line 112 of file SecureChannel.cs.
    {
        if (!_remoteCertificateExposed)
        {
            _remoteCertificate?.Dispose();
            _remoteCertificate = null;
        }
        _securityContext?.Dispose();
        _credentialsHandle?.Dispose();
        _ssl = null;
        GC.SuppressFinalize(this);
    }
References System.Net.Security.SecureChannel._credentialsHandle, System.Net.Security.SecureChannel._remoteCertificate, System.Net.Security.SecureChannel._remoteCertificateExposed, System.Net.Security.SecureChannel._securityContext, System.Net.Security.SecureChannel._ssl, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Security.Cryptography.X509Certificates.X509Certificate.Dispose(), and System.GC.SuppressFinalize().
Referenced by System.Net.Security.SslStream.CloseInternal(), and System.Net.Security.SslStream.SetException().