Terraria: System.Net.Security.SecureChannel.FindCertificateWithPrivateKey
FindCertificateWithPrivateKey()
static X509Certificate2 System.Net.Security.SecureChannel.FindCertificateWithPrivateKey (object instance, bool isServer, X509Certificate certificate) inline static package
Definition at line 125 of file SecureChannel.cs.
    {
        if (certificate == null)
        {
            return null;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Log.LocatingPrivateKey(certificate, instance);
        }
        try
        {
            X509Certificate2 x509Certificate = MakeEx(certificate);
            if (x509Certificate != null)
            {
                if (x509Certificate.HasPrivateKey)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Log.CertIsType2(instance);
                    }
                    return x509Certificate;
                }
                if (certificate != x509Certificate)
                {
                    x509Certificate.Dispose();
                }
            }
            string thumbprint = x509Certificate.Thumbprint;
            X509Store x509Store = CertificateValidationPal.EnsureStoreOpened(isServer);
            if (x509Store != null)
            {
                X509Certificate2Collection x509Certificate2Collection = x509Store.Certificates.Find(X509FindType.FindByThumbprint, thumbprint, validOnly: false);
                if (x509Certificate2Collection.Count > 0 && x509Certificate2Collection[0].HasPrivateKey)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Log.FoundCertInStore(isServer, instance);
                    }
                    return x509Certificate2Collection[0];
                }
            }
            x509Store = CertificateValidationPal.EnsureStoreOpened(!isServer);
            if (x509Store != null)
            {
                X509Certificate2Collection x509Certificate2Collection = x509Store.Certificates.Find(X509FindType.FindByThumbprint, thumbprint, validOnly: false);
                if (x509Certificate2Collection.Count > 0 && x509Certificate2Collection[0].HasPrivateKey)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Log.FoundCertInStore(!isServer, instance);
                    }
                    return x509Certificate2Collection[0];
                }
            }
        }
        catch (CryptographicException)
        {
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Log.NotFoundCertInStore(instance);
        }
        return null;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.CertificateValidationPal.EnsureStoreOpened(), System.Net.NetEventSource.Log, and System.Net.Security.SecureChannel.MakeEx().
Referenced by System.Net.Security.SslAuthenticationOptions.SslAuthenticationOptions(), System.Net.Security.SecureChannel.AcquireClientCredentials(), and System.Net.Security.SecureChannel.AcquireServerCredentials().