Terraria: System.Net.Security.SecureChannel.CreateShutdownToken
CreateShutdownToken()
ProtocolToken System.Net.Security.SecureChannel.CreateShutdownToken () inline
Definition at line 783 of file SecureChannel.cs.
    {
        SecurityStatusPal securityStatusPal = SslStreamPal.ApplyShutdownToken(ref _credentialsHandle, _securityContext);
        if (securityStatusPal.ErrorCode != SecurityStatusPalErrorCode.OK)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"ApplyAlertToken() returned {securityStatusPal.ErrorCode}", "CreateShutdownToken");
            }
            if (securityStatusPal.Exception != null)
            {
                ExceptionDispatchInfo.Throw(securityStatusPal.Exception);
            }
            return null;
        }
        return GenerateAlertToken();
    }
References System.Net.Security.SecureChannel._credentialsHandle, System.Net.Security.SecureChannel._securityContext, System.Net.Security.SslStreamPal.ApplyShutdownToken(), System.Net.Security.SecureChannel.GenerateAlertToken(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Net.Security.SslStream.ShutdownAsync().