Terraria: Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding
PrepareStripWithProceduralPadding()
void Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding (Vector2[] positions, float[] rotations, StripColorFunction colorFunction, StripHalfWidthFunction widthFunction, Vector2 offsetForAllPositions = default(Vector2), bool includeBacksides = false, bool tryStoppingOddBug = true) inline
Definition at line 76 of file VertexStrip.cs.
    {
        int num = positions.Length;
        _temporaryPositionsCache.Clear();
        _temporaryRotationsCache.Clear();
        for (int i = 0; i < num && !(positions[i] == Vector2.Zero); i++)
        {
            Vector2 vector = positions[i];
            float num2 = MathHelper.WrapAngle(rotations[i]);
            _temporaryPositionsCache.Add(vector);
            _temporaryRotationsCache.Add(num2);
            if (i + 1 >= num || !(positions[i + 1] != Vector2.Zero))
            {
                continue;
            }
            Vector2 vector2 = positions[i + 1];
            float num3 = MathHelper.WrapAngle(rotations[i + 1]);
            int num4 = (int)(Math.Abs(MathHelper.WrapAngle(num3 - num2)) / ((float)Math.PI / 12f));
            if (num4 != 0)
            {
                float num5 = vector.Distance(vector2);
                Vector2 value = vector + num2.ToRotationVector2() * num5;
                Vector2 value2 = vector2 + num3.ToRotationVector2() * (0f - num5);
                int num6 = num4 + 2;
                float num7 = 1f / (float)num6;
                Vector2 target = vector;
                for (float num8 = num7; num8 < 1f; num8 += num7)
                {
                    Vector2 vector3 = Vector2.CatmullRom(value, vector, vector2, value2, num8);
                    float item = MathHelper.WrapAngle(vector3.DirectionTo(target).ToRotation());
                    _temporaryPositionsCache.Add(vector3);
                    _temporaryRotationsCache.Add(item);
                    target = vector3;
                }
            }
        }
        int count = _temporaryPositionsCache.Count;
        Vector2 zero = Vector2.Zero;
        for (int j = 0; j < count && (!tryStoppingOddBug || !(_temporaryPositionsCache[j] == zero)); j++)
        {
            Vector2 pos = _temporaryPositionsCache[j] + offsetForAllPositions;
            float rot = _temporaryRotationsCache[j];
            int indexOnVertexArray = j * 2;
            float progressOnStrip = (float)j / (float)(count - 1);
            AddVertex(colorFunction, widthFunction, pos, rot, indexOnVertexArray, progressOnStrip);
        }
        _vertexAmountCurrentlyMaintained = count * 2;
        PrepareIndices(count, includeBacksides);
    }
References Terraria.Graphics.VertexStrip._temporaryPositionsCache, Terraria.Graphics.VertexStrip._temporaryRotationsCache, Terraria.Graphics.VertexStrip._vertexAmountCurrentlyMaintained, System.Math.Abs(), System.Collections.Generic.List< T >.Add(), Terraria.Graphics.VertexStrip.AddVertex(), Microsoft.Xna.Framework.Vector2.CatmullRom(), System.Collections.Generic.List< T >.Clear(), System.count, System.Collections.Generic.List< T >.Count, System.item, Terraria.Graphics.VertexStrip.PrepareIndices(), System.value, Microsoft.Xna.Framework.MathHelper.WrapAngle(), and Microsoft.Xna.Framework.Vector2.Zero.