Terraria: System.Net.Security.SecureChannel.AcquireServerCredentials
AcquireServerCredentials()
bool System.Net.Security.SecureChannel.AcquireServerCredentials (ref byte[] thumbPrint) inline private
Definition at line 468 of file SecureChannel.cs.
    {
        X509Certificate x509Certificate = null;
        X509Certificate2 x509Certificate2 = null;
        bool result = false;
        if (_sslAuthenticationOptions.ServerCertSelectionDelegate != null)
        {
            x509Certificate = _sslAuthenticationOptions.ServerCertSelectionDelegate(_sslAuthenticationOptions.TargetHost);
            if (x509Certificate == null)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(this, $"ServerCertSelectionDelegate returned no certificaete for '{_sslAuthenticationOptions.TargetHost}'.", "AcquireServerCredentials");
                }
                throw new AuthenticationException(System.SR.net_ssl_io_no_server_cert);
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "ServerCertSelectionDelegate selected Cert", "AcquireServerCredentials");
            }
        }
        else if (_sslAuthenticationOptions.CertSelectionDelegate != null)
        {
            X509CertificateCollection x509CertificateCollection = new X509CertificateCollection();
            x509CertificateCollection.Add(_sslAuthenticationOptions.CertificateContext.Certificate);
            x509Certificate = _sslAuthenticationOptions.CertSelectionDelegate(string.Empty, x509CertificateCollection, null, Array.Empty<string>());
            if (x509Certificate == null)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(this, $"CertSelectionDelegate returned no certificaete for '{_sslAuthenticationOptions.TargetHost}'.", "AcquireServerCredentials");
                }
                throw new NotSupportedException(System.SR.net_ssl_io_no_server_cert);
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "CertSelectionDelegate selected Cert", "AcquireServerCredentials");
            }
        }
        else if (_sslAuthenticationOptions.CertificateContext != null)
        {
            x509Certificate2 = _sslAuthenticationOptions.CertificateContext.Certificate;
        }
        if (x509Certificate2 == null)
        {
            if (x509Certificate == null)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(this, "Certiticate callback returned no certificaete.", "AcquireServerCredentials");
                }
                throw new NotSupportedException(System.SR.net_ssl_io_no_server_cert);
            }
            x509Certificate2 = FindCertificateWithPrivateKey(this, _sslAuthenticationOptions.IsServer, x509Certificate);
            if (x509Certificate2 == null)
            {
                throw new NotSupportedException(System.SR.net_ssl_io_no_server_cert);
            }
            _sslAuthenticationOptions.CertificateContext = SslStreamCertificateContext.Create(x509Certificate2);
        }
        byte[] certHash = x509Certificate2.GetCertHash();
        SafeFreeCredentials safeFreeCredentials = SslSessionsCache.TryCachedCredential(certHash, _sslAuthenticationOptions.EnabledSslProtocols, _sslAuthenticationOptions.IsServer, _sslAuthenticationOptions.EncryptionPolicy);
        if (safeFreeCredentials != null)
        {
            _credentialsHandle = safeFreeCredentials;
            result = true;
        }
        else
        {
            _credentialsHandle = SslStreamPal.AcquireCredentialsHandle(_sslAuthenticationOptions.CertificateContext, _sslAuthenticationOptions.EnabledSslProtocols, _sslAuthenticationOptions.EncryptionPolicy, _sslAuthenticationOptions.IsServer);
            thumbPrint = certHash;
        }
        return result;
    }
References System.Net.Security.SecureChannel._credentialsHandle, System.Net.Security.SecureChannel._sslAuthenticationOptions, System.Net.Security.SslStreamPal.AcquireCredentialsHandle(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Security.SslStreamCertificateContext.Certificate, System.Net.Security.SslAuthenticationOptions.CertificateContext, System.Net.Security.SslAuthenticationOptions.CertSelectionDelegate, System.Net.Security.SslStreamCertificateContext.Create(), System.Net.Security.SslAuthenticationOptions.EnabledSslProtocols, System.Net.Security.SslAuthenticationOptions.EncryptionPolicy, System.Net.NetEventSource.Error(), System.Net.Security.SecureChannel.FindCertificateWithPrivateKey(), System.Net.NetEventSource.Info(), System.Net.Security.SslAuthenticationOptions.IsServer, System.Net.NetEventSource.Log, System.SR.net_ssl_io_no_server_cert, System.Net.Security.SslAuthenticationOptions.ServerCertSelectionDelegate, System.Net.Security.SslAuthenticationOptions.TargetHost, and System.Net.Security.SslSessionsCache.TryCachedCredential().
Referenced by System.Net.Security.SecureChannel.GenerateToken().