Terraria: System.Net.Security.SecureChannel.Decrypt
Decrypt()
SecurityStatusPal System.Net.Security.SecureChannel.Decrypt (Span< byte > buffer, out int outputOffset, out int outputCount) inline package
Definition at line 640 of file SecureChannel.cs.
    {
        SecurityStatusPal result = SslStreamPal.DecryptMessage(_securityContext, buffer, out outputOffset, out outputCount);
        if (System.Net.NetEventSource.Log.IsEnabled() && result.ErrorCode == SecurityStatusPalErrorCode.OK)
        {
            System.Net.NetEventSource.DumpBuffer(this, buffer.Slice(outputOffset, outputCount), "Decrypt");
        }
        return result;
    }
References System.Net.Security.SecureChannel._securityContext, System.buffer, System.Net.Security.SslStreamPal.DecryptMessage(), System.Net.NetEventSource.DumpBuffer(), System.Net.SecurityStatusPal.ErrorCode, and System.Net.NetEventSource.Log.
Referenced by System.Net.Security.SslStream.DecryptData().