Terraria: System.Net.Security.SecureChannel.CreateFatalHandshakeAlertToken
CreateFatalHandshakeAlertToken()
ProtocolToken System.Net.Security.SecureChannel.CreateFatalHandshakeAlertToken (SslPolicyErrors sslPolicyErrors, X509Chain chain) inline
Definition at line 755 of file SecureChannel.cs.
    {
        TlsAlertMessage tlsAlertMessage = sslPolicyErrors switch
        {
            SslPolicyErrors.RemoteCertificateChainErrors => GetAlertMessageFromChain(chain),
            SslPolicyErrors.RemoteCertificateNameMismatch => TlsAlertMessage.BadCertificate,
            _ => TlsAlertMessage.CertificateUnknown,
        };
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"alertMessage:{tlsAlertMessage}", "CreateFatalHandshakeAlertToken");
        }
        SecurityStatusPal securityStatusPal = SslStreamPal.ApplyAlertToken(ref _credentialsHandle, _securityContext, TlsAlertType.Fatal, tlsAlertMessage);
        if (securityStatusPal.ErrorCode != SecurityStatusPalErrorCode.OK)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"ApplyAlertToken() returned {securityStatusPal.ErrorCode}", "CreateFatalHandshakeAlertToken");
            }
            if (securityStatusPal.Exception != null)
            {
                ExceptionDispatchInfo.Throw(securityStatusPal.Exception);
            }
            return null;
        }
        return GenerateAlertToken();
    }
References System.Net.Security.SecureChannel._credentialsHandle, System.Net.Security.SecureChannel._securityContext, System.Net.Security.SslStreamPal.ApplyAlertToken(), System.Net.Security.SecureChannel.GenerateAlertToken(), System.Net.Security.SecureChannel.GetAlertMessageFromChain(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Net.Security.SecureChannel.VerifyRemoteCertificate().