Terraria: System.Net.Security.SecureChannel.GenerateToken
GenerateToken()
SecurityStatusPal System.Net.Security.SecureChannel.GenerateToken (ReadOnlySpan< byte > inputBuffer, ref byte[] output) inline private
Definition at line 564 of file SecureChannel.cs.
    {
        byte[] outputBuffer = Array.Empty<byte>();
        SecurityStatusPal result = default(SecurityStatusPal);
        bool flag = false;
        byte[] thumbPrint = null;
        try
        {
            do
            {
                thumbPrint = null;
                if (_refreshCredentialNeeded)
                {
                    flag = (_sslAuthenticationOptions.IsServer ? AcquireServerCredentials(ref thumbPrint) : AcquireClientCredentials(ref thumbPrint));
                }
                result = ((!_sslAuthenticationOptions.IsServer) ? SslStreamPal.InitializeSecurityContext(ref _credentialsHandle, ref _securityContext, _sslAuthenticationOptions.TargetHost, inputBuffer, ref outputBuffer, _sslAuthenticationOptions) : SslStreamPal.AcceptSecurityContext(ref _credentialsHandle, ref _securityContext, inputBuffer, ref outputBuffer, _sslAuthenticationOptions));
            }
            while (flag && _credentialsHandle == null);
        }
        finally
        {
            if (_refreshCredentialNeeded)
            {
                _refreshCredentialNeeded = false;
                _credentialsHandle?.Dispose();
                if (!flag && _securityContext != null && !_securityContext.IsInvalid && _credentialsHandle != null && !_credentialsHandle.IsInvalid)
                {
                    SslSessionsCache.CacheCredential(_credentialsHandle, thumbPrint, _sslAuthenticationOptions.EnabledSslProtocols, _sslAuthenticationOptions.IsServer, _sslAuthenticationOptions.EncryptionPolicy);
                }
            }
        }
        output = outputBuffer;
        return result;
    }
References System.Net.Security.SecureChannel._credentialsHandle, System.Net.Security.SecureChannel._refreshCredentialNeeded, System.Net.Security.SecureChannel._securityContext, System.Net.Security.SecureChannel._sslAuthenticationOptions, System.Net.Security.SslStreamPal.AcceptSecurityContext(), System.Net.Security.SecureChannel.AcquireClientCredentials(), System.Net.Security.SecureChannel.AcquireServerCredentials(), System.Net.Security.SslSessionsCache.CacheCredential(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.Security.SslAuthenticationOptions.EnabledSslProtocols, System.Net.Security.SslAuthenticationOptions.EncryptionPolicy, System.Net.Security.SslStreamPal.InitializeSecurityContext(), System.Net.Security.SafeDeleteContext.IsInvalid, System.Net.Security.SafeFreeCredentials.IsInvalid, System.Net.Security.SslAuthenticationOptions.IsServer, and System.Net.Security.SslAuthenticationOptions.TargetHost.
Referenced by System.Net.Security.SecureChannel.GenerateAlertToken(), and System.Net.Security.SecureChannel.NextMessage().