Terraria: System.Net.Security.SecureChannel.NextMessage
NextMessage()
ProtocolToken System.Net.Security.SecureChannel.NextMessage (ReadOnlySpan< byte > incomingBuffer) inline package
Definition at line 543 of file SecureChannel.cs.
    {
        byte[] output = null;
        SecurityStatusPal securityStatusPal = GenerateToken(incomingBuffer, ref output);
        if (!_sslAuthenticationOptions.IsServer && securityStatusPal.ErrorCode == SecurityStatusPalErrorCode.CredentialsNeeded)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "NextMessage() returned SecurityStatusPal.CredentialsNeeded", "NextMessage");
            }
            SetRefreshCredentialNeeded();
            securityStatusPal = GenerateToken(incomingBuffer, ref output);
        }
        ProtocolToken protocolToken = new ProtocolToken(output, securityStatusPal);
        if (System.Net.NetEventSource.Log.IsEnabled() && protocolToken.Failed)
        {
            System.Net.NetEventSource.Error(this, $"Authentication failed. Status: {securityStatusPal}, Exception message: {protocolToken.GetException().Message}", "NextMessage");
        }
        return protocolToken;
    }
References System.Net.Security.SecureChannel._sslAuthenticationOptions, System.Net.NetEventSource.Error(), System.Net.Security.SecureChannel.GenerateToken(), System.Net.NetEventSource.Info(), System.Net.Security.SslAuthenticationOptions.IsServer, System.Net.NetEventSource.Log, and System.Net.Security.SecureChannel.SetRefreshCredentialNeeded().
Referenced by System.Net.Security.SslStream.ForceAuthenticationAsync< TIOAdapter >(), and System.Net.Security.SslStream.ProcessBlob().