Terraria: Terraria.Graphics.VertexStrip.AddVertex
AddVertex()
void Terraria.Graphics.VertexStrip.AddVertex (StripColorFunction colorFunction, StripHalfWidthFunction widthFunction, Vector2 pos, float rot, int indexOnVertexArray, float progressOnStrip) inline private
Definition at line 157 of file VertexStrip.cs.
    {
        while (indexOnVertexArray + 1 >= _vertices.Length)
        {
            Array.Resize(ref _vertices, _vertices.Length * 2);
        }
        Color color = colorFunction(progressOnStrip);
        float num = widthFunction(progressOnStrip);
        Vector2 vector = MathHelper.WrapAngle(rot - (float)Math.PI / 2f).ToRotationVector2() * num;
        _vertices[indexOnVertexArray].Position = pos + vector;
        _vertices[indexOnVertexArray + 1].Position = pos - vector;
        _vertices[indexOnVertexArray].TexCoord = new Vector2(progressOnStrip, 1f);
        _vertices[indexOnVertexArray + 1].TexCoord = new Vector2(progressOnStrip, 0f);
        _vertices[indexOnVertexArray].Color = color;
        _vertices[indexOnVertexArray + 1].Color = color;
    }
References Terraria.Graphics.VertexStrip._vertices, Terraria.Graphics.VertexStrip.CustomVertexInfo.Color, System.Math.PI, Terraria.Graphics.VertexStrip.CustomVertexInfo.Position, Terraria.Graphics.VertexStrip.CustomVertexInfo.TexCoord, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.MathHelper.WrapAngle().
Referenced by Terraria.Graphics.VertexStrip.PrepareStrip(), and Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding().