Terraria: System.Net.Sockets.SocketAsyncEventArgs.SetupPinHandlesSendPackets
SetupPinHandlesSendPackets()
unsafe global.Interop.Winsock.TransmitPacketsElement[] System.Net.Sockets.SocketAsyncEventArgs.SetupPinHandlesSendPackets (SendPacketsElement[] sendPacketsElementsCopy, int sendPacketsElementsFileCount, int sendPacketsElementsFileStreamCount, int sendPacketsElementsBufferCount) inline private inherited
Definition at line 1615 of file SocketAsyncEventArgs.cs.
    {
        if (_pinState != 0)
        {
            FreePinHandles();
        }
        global::Interop.Winsock.TransmitPacketsElement[] array = GC.AllocateUninitializedArray<global::Interop.Winsock.TransmitPacketsElement>(sendPacketsElementsFileCount + sendPacketsElementsFileStreamCount + sendPacketsElementsBufferCount, pinned: true);
        if (_multipleBufferMemoryHandles == null || _multipleBufferMemoryHandles.Length < sendPacketsElementsBufferCount)
        {
            _multipleBufferMemoryHandles = new MemoryHandle[sendPacketsElementsBufferCount];
        }
        int num = 0;
        foreach (SendPacketsElement sendPacketsElement in sendPacketsElementsCopy)
        {
            if (sendPacketsElement != null && sendPacketsElement.MemoryBuffer.HasValue && sendPacketsElement.Count > 0)
            {
                _multipleBufferMemoryHandles[num] = sendPacketsElement.MemoryBuffer.Value.Pin();
                num++;
            }
        }
        int num2 = 0;
        int num3 = 0;
        int num4 = 0;
        foreach (SendPacketsElement sendPacketsElement2 in sendPacketsElementsCopy)
        {
            if (sendPacketsElement2 != null)
            {
                if (sendPacketsElement2.MemoryBuffer.HasValue && sendPacketsElement2.Count > 0)
                {
                    array[num3].buffer = (IntPtr)_multipleBufferMemoryHandles[num2].Pointer;
                    array[num3].length = (uint)sendPacketsElement2.Count;
                    array[num3].flags = global::Interop.Winsock.TransmitPacketsElementFlags.Memory | (sendPacketsElement2.EndOfPacket ? global::Interop.Winsock.TransmitPacketsElementFlags.EndOfPacket : global::Interop.Winsock.TransmitPacketsElementFlags.None);
                    num2++;
                    num3++;
                }
                else if (sendPacketsElement2.FilePath != null)
                {
                    array[num3].fileHandle = _sendPacketsFileHandles[num4].DangerousGetHandle();
                    array[num3].fileOffset = sendPacketsElement2.OffsetLong;
                    array[num3].length = (uint)sendPacketsElement2.Count;
                    array[num3].flags = global::Interop.Winsock.TransmitPacketsElementFlags.File | (sendPacketsElement2.EndOfPacket ? global::Interop.Winsock.TransmitPacketsElementFlags.EndOfPacket : global::Interop.Winsock.TransmitPacketsElementFlags.None);
                    num4++;
                    num3++;
                }
                else if (sendPacketsElement2.FileStream != null)
                {
                    array[num3].fileHandle = sendPacketsElement2.FileStream.SafeFileHandle.DangerousGetHandle();
                    array[num3].fileOffset = sendPacketsElement2.OffsetLong;
                    array[num3].length = (uint)sendPacketsElement2.Count;
                    array[num3].flags = global::Interop.Winsock.TransmitPacketsElementFlags.File | (sendPacketsElement2.EndOfPacket ? global::Interop.Winsock.TransmitPacketsElementFlags.EndOfPacket : global::Interop.Winsock.TransmitPacketsElementFlags.None);
                    num3++;
                }
            }
        }
        _pinState = PinState.SendPackets;
        return array;
    }
References System.Net.Sockets.SocketAsyncEventArgs._multipleBufferMemoryHandles, System.Net.Sockets.SocketAsyncEventArgs._pinState, System.Net.Sockets.SocketAsyncEventArgs._sendPacketsFileHandles, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), and System.Net.Sockets.SocketAsyncEventArgs.FreePinHandles().
Referenced by System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendPackets().