Terraria: System.Net.Sockets.SocketAsyncEventArgs.DoOperationDisconnect
DoOperationDisconnect()
unsafe SocketError System.Net.Sockets.SocketAsyncEventArgs.DoOperationDisconnect (Socket socket, SafeSocketHandle handle, CancellationToken cancellationToken) inline package inherited
Definition at line 1158 of file SocketAsyncEventArgs.cs.
    {
        NativeOverlapped* overlapped = AllocateNativeOverlapped();
        try
        {
            _asyncProcessingState = AsyncProcessingState.InProcess;
            bool success = socket.DisconnectEx(handle, overlapped, DisconnectReuseSocket ? 2 : 0, 0);
            return ProcessIOCPResultWithDeferredAsyncHandling(success, 0, overlapped, Memory<byte>.Empty, cancellationToken);
        }
        catch
        {
            _asyncProcessingState = AsyncProcessingState.None;
            FreeNativeOverlapped(overlapped);
            throw;
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._asyncProcessingState, System.Net.Sockets.SocketAsyncEventArgs.AllocateNativeOverlapped(), System.cancellationToken, System.Net.Sockets.SocketAsyncEventArgs.DisconnectReuseSocket, System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlapped(), System.handle, and System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResultWithDeferredAsyncHandling().
Referenced by System.Net.Sockets.Socket.DisconnectAsync().