Terraria: System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync
DnsConnectAsync()
bool System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync (DnsEndPoint endPoint, SocketType socketType, ProtocolType protocolType) inline package inherited
Definition at line 704 of file SocketAsyncEventArgs.cs.
    {
        CancellationToken cancellationToken2 = _multipleConnectCancellation?.Token ?? default(CancellationToken);
        Task<IPAddress[]> hostAddressesAsync = Dns.GetHostAddressesAsync(endPoint.Host, endPoint.AddressFamily, cancellationToken2);
        MultiConnectSocketAsyncEventArgs multiConnectSocketAsyncEventArgs = new MultiConnectSocketAsyncEventArgs();
        multiConnectSocketAsyncEventArgs.CopyBufferFrom(this);
        Core(multiConnectSocketAsyncEventArgs, hostAddressesAsync, endPoint.Port, socketType, protocolType, cancellationToken2);
        return multiConnectSocketAsyncEventArgs.ReachedCoordinationPointFirst();
        async Task Core(MultiConnectSocketAsyncEventArgs internalArgs, Task<IPAddress[]> addressesTask, int port, SocketType socketType, ProtocolType protocolType, CancellationToken cancellationToken)
        {
            Socket tempSocketIPv4 = null;
            Socket tempSocketIPv5 = null;
            Exception caughtException = null;
            try
            {
                SocketError lastError = SocketError.NoData;
                IPAddress[] array = await addressesTask.ConfigureAwait(continueOnCapturedContext: false);
                foreach (IPAddress iPAddress in array)
                {
                    Socket socket = null;
                    if (_currentSocket != null)
                    {
                        if (!_currentSocket.CanTryAddressFamily(iPAddress.AddressFamily))
{
                            continue;
                        }
                        socket = _currentSocket;
                    }
                    else
                    {
                        if (iPAddress.AddressFamily == AddressFamily.InterNetworkV6)
{
                            Socket socket2 = tempSocketIPv5;
                            if (socket2 == null)
{
                                Socket socket3;
                                tempSocketIPv5 = (socket3 = (Socket.OSSupportsIPv6 ? new Socket(AddressFamily.InterNetworkV6, socketType, protocolType) : null));
                                socket2 = socket3;
                            }
                            socket = socket2;
                            if (socket != null && iPAddress.IsIPv4MappedToIPv6)
{
                                socket.DualMode = true;
                            }
                        }
                        else if (iPAddress.AddressFamily == AddressFamily.InterNetwork)
{
                            Socket socket4 = tempSocketIPv4;
                            if (socket4 == null)
{
                                Socket socket3;
                                tempSocketIPv4 = (socket3 = (Socket.OSSupportsIPv4 ? new Socket(AddressFamily.InterNetwork, socketType, protocolType) : null));
                                socket4 = socket3;
                            }
                            socket = socket4;
                        }
                        if (socket == null)
{
                            continue;
                        }
                    }
                    socket.ReplaceHandleIfNecessaryAfterFailedConnect();
                    if (internalArgs.RemoteEndPoint is IPEndPoint iPEndPoint)
                    {
                        iPEndPoint.Address = iPAddress;
                    }
                    else
                    {
                        internalArgs.RemoteEndPoint = new IPEndPoint(iPAddress, port);
                    }
                    if (socket.ConnectAsync(internalArgs))
                    {
                        using (cancellationToken.UnsafeRegister(delegate(object s)
{
                            Socket.CancelConnectAsync((SocketAsyncEventArgs)s);
                        }, internalArgs))
{
                            await new ValueTask(internalArgs, internalArgs.Version).ConfigureAwait(continueOnCapturedContext: false);
                        }
                    }
                    if (internalArgs.SocketError == SocketError.Success)
                    {
                        return;
                    }
                    if (cancellationToken.IsCancellationRequested)
                    {
                        throw new SocketException(995);
                    }
                    lastError = internalArgs.SocketError;
                    internalArgs.Reset();
                }
                caughtException = (Exception)(object)new SocketException((int)lastError);
            }
            catch (ObjectDisposedException)
            {
                caughtException = (Exception)(object)new SocketException(995);
            }
            catch (Exception ex2)
            {
                caughtException = ex2;
            }
            finally
            {
                if (tempSocketIPv4 != null && !tempSocketIPv4.Connected)
                {
                    tempSocketIPv4.Dispose();
                }
                if (tempSocketIPv5 != null && !tempSocketIPv5.Connected)
                {
                    tempSocketIPv5.Dispose();
                }
                if (_currentSocket != null && ((!_userSocket && !_currentSocket.Connected) || caughtException is OperationCanceledException || caughtException is SocketException { SocketErrorCode: SocketError.OperationAborted }))
                {
                    _currentSocket.Dispose();
                }
                if (caughtException != null)
                {
                    SetResults(caughtException, 0, SocketFlags.None);
                    _currentSocket?.UpdateStatusAfterSocketError(_socketError);
                }
                else
                {
                    SetResults(SocketError.Success, internalArgs.BytesTransferred, internalArgs.SocketFlags);
                    _connectSocket = (_currentSocket = internalArgs.ConnectSocket);
                }
                if (SocketsTelemetry.Log.IsEnabled())
                {
                    LogBytesTransferEvents(_connectSocket?.SocketType, SocketAsyncOperation.Connect, internalArgs.BytesTransferred);
                }
                Complete();
                internalArgs.Dispose();
                if (!internalArgs.ReachedCoordinationPointFirst())
                {
                    OnCompleted(this);
                }
            }
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._connectSocket, System.Net.Sockets.SocketAsyncEventArgs._currentSocket, System.Net.Sockets.SocketAsyncEventArgs._multipleConnectCancellation, System.Net.Sockets.SocketAsyncEventArgs._socketError, System.Net.Sockets.SocketAsyncEventArgs._userSocket, System.array, System.Net.Sockets.Socket.CancelConnectAsync(), System.cancellationToken, System.Net.Sockets.Socket.CanTryAddressFamily(), System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.Connected, System.Net.Sockets.Socket.Dispose(), System.Net.Dns.GetHostAddressesAsync(), System.Net.Sockets.SocketsTelemetry.Log, System.Net.Sockets.SocketAsyncEventArgs.LogBytesTransferEvents(), System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(), System.s, System.Net.Sockets.SocketAsyncEventArgs.SetResults(), System.Net.Sockets.Socket, System.Threading.CancellationTokenSource.Token, and System.Net.Sockets.Socket.UpdateStatusAfterSocketError().
Referenced by System.Net.Sockets.Socket.ConnectAsync(), and System.Net.Sockets.Socket.ConnectAsync().