Terraria: System.Net.Sockets.SocketAsyncEventArgs.GetIOCPResult
GetIOCPResult()
unsafe SocketError System.Net.Sockets.SocketAsyncEventArgs.GetIOCPResult (bool success, NativeOverlapped * overlapped) inline private inherited
Definition at line 1060 of file SocketAsyncEventArgs.cs.
    {
        if (success)
        {
            if (_currentSocket.SafeHandle.SkipCompletionPortOnSuccess)
            {
                FreeNativeOverlapped(overlapped);
                return SocketError.Success;
            }
            return SocketError.IOPending;
        }
        SocketError lastSocketError = SocketPal.GetLastSocketError();
        if (lastSocketError != SocketError.IOPending)
        {
            FreeNativeOverlapped(overlapped);
            return lastSocketError;
        }
        return SocketError.IOPending;
    }
References System.Net.Sockets.SocketAsyncEventArgs._currentSocket, System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlapped(), System.Net.Sockets.SocketPal.GetLastSocketError(), System.Net.Sockets.Socket.SafeHandle, and System.Net.Sockets.SafeSocketHandle.SkipCompletionPortOnSuccess.
Referenced by System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResult(), and System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResultWithDeferredAsyncHandling().