Terraria: System.Net.Sockets.SocketAsyncEventArgs.Complete
Complete()
void System.Net.Sockets.SocketAsyncEventArgs.Complete () inline package inherited
Definition at line 565 of file SocketAsyncEventArgs.cs.
    {
        CompleteCore();
        _context = null;
        _operating = 0;
        if (_disposeCalled)
        {
            Dispose();
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._context, System.Net.Sockets.SocketAsyncEventArgs._disposeCalled, System.Net.Sockets.SocketAsyncEventArgs._operating, System.Net.Sockets.SocketAsyncEventArgs.CompleteCore(), and System.Net.Sockets.SocketAsyncEventArgs.Dispose().
Referenced by System.Net.Sockets.Socket.AcceptAsync(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.Sockets.SocketAsyncEventArgs.CopyBufferFrom(), System.Net.Sockets.Socket.DisconnectAsync(), System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncFailure(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess(), System.Net.Sockets.Socket.ReceiveAsync(), System.Net.Sockets.Socket.ReceiveFromAsync(), System.Net.Sockets.Socket.ReceiveMessageFromAsync(), System.Net.Sockets.Socket.SendAsync(), System.Net.Sockets.Socket.SendPacketsAsync(), System.Net.Sockets.Socket.SendToAsync(), System.Net.Sockets.SocketAsyncEventArgs.SetBuffer(), System.Net.Sockets.SocketAsyncEventArgs.SetBuffer(), and System.Net.Sockets.SocketAsyncEventArgs.SetBuffer().