Terraria: System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResult
ProcessIOCPResult()
unsafe SocketError System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResult (bool success, int bytesTransferred, NativeOverlapped * overlapped) inline private inherited
Definition at line 1080 of file SocketAsyncEventArgs.cs.
    {
        SocketError iOCPResult = GetIOCPResult(success, overlapped);
        if (iOCPResult != SocketError.IOPending)
        {
            FinishOperationSync(iOCPResult, bytesTransferred, SocketFlags.None);
        }
        return iOCPResult;
    }
References System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSync(), and System.Net.Sockets.SocketAsyncEventArgs.GetIOCPResult().
Referenced by System.Net.Sockets.SocketAsyncEventArgs.DoOperationConnectEx(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveFromMultiBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveMessageFrom(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveMultiBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendMultiBuffer(), and System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendToMultiBuffer().