Terraria: System.Net.Sockets.SocketAsyncEventArgs.StartOperationAccept
StartOperationAccept()
void System.Net.Sockets.SocketAsyncEventArgs.StartOperationAccept () inline package inherited
Definition at line 630 of file SocketAsyncEventArgs.cs.
    {
        _acceptAddressBufferCount = 2 * (Socket.GetAddressSize(_currentSocket._rightEndPoint) + 16);
        if (!_buffer.Equals(default(Memory<byte>)))
        {
            if (_count < _acceptAddressBufferCount)
            {
                throw new ArgumentException(System.SR.Format(System.SR.net_buffercounttoosmall, "Count"));
            }
        }
        else if (_acceptBuffer == null || _acceptBuffer.Length < _acceptAddressBufferCount)
        {
            _acceptBuffer = new byte[_acceptAddressBufferCount];
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._acceptAddressBufferCount, System.Net.Sockets.SocketAsyncEventArgs._acceptBuffer, System.Net.Sockets.SocketAsyncEventArgs._buffer, System.Net.Sockets.SocketAsyncEventArgs._count, System.Net.Sockets.SocketAsyncEventArgs._currentSocket, System.Net.Sockets.Socket._rightEndPoint, System.Memory< T >.Equals(), System.SR.Format(), System.Net.Sockets.Socket.GetAddressSize(), and System.SR.net_buffercounttoosmall.
Referenced by System.Net.Sockets.Socket.AcceptAsync().