Terraria: System.Net.Sockets.SocketAsyncEventArgs.FinishOperationReceiveMessageFrom
FinishOperationReceiveMessageFrom()
unsafe void System.Net.Sockets.SocketAsyncEventArgs.FinishOperationReceiveMessageFrom () inline private inherited
Definition at line 1773 of file SocketAsyncEventArgs.cs.
    {
        global::Interop.Winsock.WSAMsg* ptr = (global::Interop.Winsock.WSAMsg*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(_wsaMessageBufferPinned, 0);
        if (_controlBufferPinned.Length == sizeof(global::Interop.Winsock.ControlData))
        {
            _receiveMessageFromPacketInfo = SocketPal.GetIPPacketInformation((global::Interop.Winsock.ControlData*)(void*)ptr->controlBuffer.Pointer);
        }
        else if (_controlBufferPinned.Length == sizeof(global::Interop.Winsock.ControlDataIPv6))
        {
            _receiveMessageFromPacketInfo = SocketPal.GetIPPacketInformation((global::Interop.Winsock.ControlDataIPv6*)(void*)ptr->controlBuffer.Pointer);
        }
        else
        {
            _receiveMessageFromPacketInfo = default(IPPacketInformation);
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._controlBufferPinned, System.Net.Sockets.SocketAsyncEventArgs._receiveMessageFromPacketInfo, System.Net.Sockets.SocketAsyncEventArgs._wsaMessageBufferPinned, System.Net.Sockets.SocketPal.GetIPPacketInformation(), and System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement().
Referenced by System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess().