Terraria: System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendPackets
DoOperationSendPackets()
unsafe SocketError System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendPackets (Socket socket, SafeSocketHandle handle, CancellationToken cancellationToken) inline package inherited
Definition at line 1405 of file SocketAsyncEventArgs.cs.
    {
        SendPacketsElement[] array = (SendPacketsElement[])_sendPacketsElements.Clone();
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        SendPacketsElement[] array2 = array;
        foreach (SendPacketsElement sendPacketsElement in array2)
        {
            if (sendPacketsElement != null)
            {
                if (sendPacketsElement.FilePath != null)
                {
                    num++;
                }
                else if (sendPacketsElement.FileStream != null)
                {
                    num2++;
                }
                else if (sendPacketsElement.MemoryBuffer.HasValue && sendPacketsElement.Count > 0)
                {
                    num3++;
                }
            }
        }
        if (num + num2 + num3 == 0)
        {
            FinishOperationSyncSuccess(0, SocketFlags.None);
            return SocketError.Success;
        }
        if (num > 0)
        {
            int num4 = 0;
            _sendPacketsFileHandles = new SafeFileHandle[num];
            try
            {
                SendPacketsElement[] array3 = array;
                foreach (SendPacketsElement sendPacketsElement2 in array3)
                {
                    if (sendPacketsElement2 != null && sendPacketsElement2.FilePath != null)
                    {
                        _sendPacketsFileHandles[num4] = File.OpenHandle(sendPacketsElement2.FilePath, FileMode.Open, FileAccess.Read, FileShare.Read, FileOptions.None, 0L);
                        num4++;
                    }
                }
            }
            catch
            {
                for (int num5 = num4 - 1; num5 >= 0; num5--)
                {
                    _sendPacketsFileHandles[num5].Dispose();
                }
                _sendPacketsFileHandles = null;
                throw;
            }
        }
        global::Interop.Winsock.TransmitPacketsElement[] array4 = SetupPinHandlesSendPackets(array, num, num2, num3);
        NativeOverlapped* overlapped = AllocateNativeOverlapped();
        try
        {
            _asyncProcessingState = AsyncProcessingState.InProcess;
            bool success = socket.TransmitPackets(handle, Marshal.UnsafeAddrOfPinnedArrayElement(array4, 0), array4.Length, _sendPacketsSendSize, overlapped, _sendPacketsFlags);
            return ProcessIOCPResultWithDeferredAsyncHandling(success, 0, overlapped, Memory<byte>.Empty, cancellationToken);
        }
        catch
        {
            _asyncProcessingState = AsyncProcessingState.None;
            FreeNativeOverlapped(overlapped);
            throw;
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._asyncProcessingState, System.Net.Sockets.SocketAsyncEventArgs._sendPacketsElements, System.Net.Sockets.SocketAsyncEventArgs._sendPacketsFileHandles, System.Net.Sockets.SocketAsyncEventArgs._sendPacketsFlags, System.Net.Sockets.SocketAsyncEventArgs._sendPacketsSendSize, System.Net.Sockets.SocketAsyncEventArgs.AllocateNativeOverlapped(), System.array, System.cancellationToken, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess(), System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlapped(), System.handle, System.L, System.IO.File.OpenHandle(), System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResultWithDeferredAsyncHandling(), System.Net.Sockets.SocketAsyncEventArgs.SetupPinHandlesSendPackets(), and System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement().
Referenced by System.Net.Sockets.Socket.SendPacketsAsync().