Terraria: System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResultWithDeferredAsyncHandling
ProcessIOCPResultWithDeferredAsyncHandling()
unsafe SocketError System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResultWithDeferredAsyncHandling (bool success, int bytesTransferred, NativeOverlapped * overlapped, Memory< byte > bufferToPin, CancellationToken cancellationToken = default(CancellationToken)) inline private inherited
Definition at line 1090 of file SocketAsyncEventArgs.cs.
    {
        SocketError iOCPResult = GetIOCPResult(success, overlapped);
        if (iOCPResult == SocketError.IOPending)
        {
            RegisterToCancelPendingIO(overlapped, cancellationToken);
            _singleBufferHandle = bufferToPin.Pin();
            _asyncProcessingState = AsyncProcessingState.Set;
        }
        else
        {
            _asyncProcessingState = AsyncProcessingState.None;
            FinishOperationSync(iOCPResult, bytesTransferred, SocketFlags.None);
        }
        return iOCPResult;
    }
References System.Net.Sockets.SocketAsyncEventArgs._asyncProcessingState, System.Net.Sockets.SocketAsyncEventArgs._singleBufferHandle, System.cancellationToken, System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSync(), System.Net.Sockets.SocketAsyncEventArgs.GetIOCPResult(), and System.Net.Sockets.SocketAsyncEventArgs.RegisterToCancelPendingIO().
Referenced by System.Net.Sockets.SocketAsyncEventArgs.DoOperationAccept(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationDisconnect(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveFromSingleBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveMessageFrom(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveSingleBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendPackets(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendSingleBuffer(), and System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendToSingleBuffer().