Terraria: System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncFailure
FinishOperationSyncFailure()
void System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncFailure (SocketError socketError, int bytesTransferred, SocketFlags flags) inline package inherited
Definition at line 669 of file SocketAsyncEventArgs.cs.
    {
        SetResults(socketError, bytesTransferred, flags);
        Socket currentSocket = _currentSocket;
        if (currentSocket != null)
        {
            currentSocket.UpdateStatusAfterSocketError(socketError);
            if (_completedOperation == SocketAsyncOperation.Connect && !_userSocket)
            {
                currentSocket.Dispose();
                _currentSocket = null;
            }
        }
        SocketAsyncOperation completedOperation = _completedOperation;
        if (completedOperation == SocketAsyncOperation.SendPackets)
        {
            FinishOperationSendPackets();
        }
        Complete();
    }
References System.Net.Sockets.SocketAsyncEventArgs._completedOperation, System.Net.Sockets.SocketAsyncEventArgs._currentSocket, System.Net.Sockets.SocketAsyncEventArgs._userSocket, System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSendPackets(), and System.Net.Sockets.SocketAsyncEventArgs.SetResults().
Referenced by System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(), and System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSync().