Terraria: System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlapped
FreeNativeOverlapped()
unsafe void System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlapped (NativeOverlapped * overlapped) inline private inherited
Definition at line 1031 of file SocketAsyncEventArgs.cs.
    {
        _currentSocket.SafeHandle.IOCPBoundHandle.FreeNativeOverlapped(overlapped);
    }
References System.Net.Sockets.SocketAsyncEventArgs._currentSocket, System.Threading.ThreadPoolBoundHandle.FreeNativeOverlapped(), System.Net.Sockets.SafeSocketHandle.IOCPBoundHandle, and System.Net.Sockets.Socket.SafeHandle.
Referenced by System.Net.Sockets.SocketAsyncEventArgs.DoOperationAccept(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationConnectEx(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationDisconnect(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveFromMultiBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveFromSingleBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveMessageFrom(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveMultiBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveSingleBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendMultiBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendPackets(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendSingleBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendToMultiBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendToSingleBuffer(), System.Net.Sockets.SocketAsyncEventArgs.GetIOCPResult(), and System.Net.Sockets.SocketAsyncEventArgs.HandleCompletionPortCallbackError().