Terraria: System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveMessageFrom
DoOperationReceiveMessageFrom()
unsafe SocketError System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveMessageFrom (Socket socket, SafeSocketHandle handle, CancellationToken cancellationToken) inline package inherited
Definition at line 1280 of file SocketAsyncEventArgs.cs.
    {
        PinSocketAddressBuffer();
        if (_wsaMessageBufferPinned == null)
        {
            _wsaMessageBufferPinned = GC.AllocateUninitializedArray<byte>(sizeof(global::Interop.Winsock.WSAMsg), pinned: true);
        }
        IPAddress iPAddress = ((_socketAddress.Family == AddressFamily.InterNetworkV6) ? _socketAddress.GetIPAddress() : null);
        bool flag = _currentSocket.AddressFamily == AddressFamily.InterNetwork || (iPAddress?.IsIPv4MappedToIPv6 ?? false);
        if (_currentSocket.AddressFamily == AddressFamily.InterNetworkV6 && (_controlBufferPinned == null || _controlBufferPinned.Length != sizeof(global::Interop.Winsock.ControlDataIPv6)))
        {
            _controlBufferPinned = GC.AllocateUninitializedArray<byte>(sizeof(global::Interop.Winsock.ControlDataIPv6), pinned: true);
        }
        else if (flag && (_controlBufferPinned == null || _controlBufferPinned.Length != sizeof(global::Interop.Winsock.ControlData)))
        {
            _controlBufferPinned = GC.AllocateUninitializedArray<byte>(sizeof(global::Interop.Winsock.ControlData), pinned: true);
        }
        WSABuffer[] wsaRecvMsgWSABufferArray;
        uint wsaRecvMsgWSABufferCount;
        if (_bufferList == null)
        {
            if (_wsaRecvMsgWSABufferArrayPinned == null)
            {
                _wsaRecvMsgWSABufferArrayPinned = GC.AllocateUninitializedArray<WSABuffer>(1, pinned: true);
            }
            fixed (byte* ptr = &MemoryMarshal.GetReference(_buffer.Span))
            {
                _asyncProcessingState = AsyncProcessingState.InProcess;
                _wsaRecvMsgWSABufferArrayPinned[0].Pointer = (IntPtr)ptr + _offset;
                _wsaRecvMsgWSABufferArrayPinned[0].Length = _count;
                wsaRecvMsgWSABufferArray = _wsaRecvMsgWSABufferArrayPinned;
                wsaRecvMsgWSABufferCount = 1u;
                return Core();
            }
        }
        wsaRecvMsgWSABufferArray = _wsaBufferArrayPinned;
        wsaRecvMsgWSABufferCount = (uint)_bufferListInternal.Count;
        return Core();
        unsafe SocketError Core()
        {
            global::Interop.Winsock.WSAMsg* ptr2 = (global::Interop.Winsock.WSAMsg*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(_wsaMessageBufferPinned, 0);
            ptr2->socketAddress = PtrSocketAddressBuffer;
            ptr2->addressLength = (uint)_socketAddress.Size;
            fixed (WSABuffer* ptr3 = &wsaRecvMsgWSABufferArray[0])
            {
                void* ptr4 = ptr3;
                ptr2->buffers = (IntPtr)ptr4;
            }
            ptr2->count = wsaRecvMsgWSABufferCount;
            if (_controlBufferPinned != null)
            {
                fixed (byte* ptr5 = &_controlBufferPinned[0])
                {
                    void* ptr6 = ptr5;
                    ptr2->controlBuffer.Pointer = (IntPtr)ptr6;
                }
                ptr2->controlBuffer.Length = _controlBufferPinned.Length;
            }
            ptr2->flags = _socketFlags;
            NativeOverlapped* overlapped = AllocateNativeOverlapped();
            try
            {
                int bytesTransferred;
                SocketError socketError = socket.WSARecvMsg(handle, Marshal.UnsafeAddrOfPinnedArrayElement(_wsaMessageBufferPinned, 0), out bytesTransferred, overlapped, IntPtr.Zero);
                return (_bufferList == null) ? ProcessIOCPResultWithDeferredAsyncHandling(socketError == SocketError.Success, bytesTransferred, overlapped, _buffer, cancellationToken) : ProcessIOCPResult(socketError == SocketError.Success, bytesTransferred, overlapped);
            }
            catch
            {
                _asyncProcessingState = AsyncProcessingState.None;
                FreeNativeOverlapped(overlapped);
                throw;
            }
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._asyncProcessingState, System.Net.Sockets.SocketAsyncEventArgs._buffer, System.Net.Sockets.SocketAsyncEventArgs._bufferList, System.Net.Sockets.SocketAsyncEventArgs._bufferListInternal, System.Net.Sockets.SocketAsyncEventArgs._controlBufferPinned, System.Net.Sockets.SocketAsyncEventArgs._count, System.Net.Sockets.SocketAsyncEventArgs._currentSocket, System.Net.Sockets.SocketAsyncEventArgs._offset, System.Net.Sockets.SocketAsyncEventArgs._socketAddress, System.Net.Sockets.SocketAsyncEventArgs._socketFlags, System.Net.Sockets.SocketAsyncEventArgs._wsaBufferArrayPinned, System.Net.Sockets.SocketAsyncEventArgs._wsaMessageBufferPinned, System.Net.Sockets.SocketAsyncEventArgs._wsaRecvMsgWSABufferArrayPinned, System.Net.Sockets.Socket.AddressFamily, System.Net.Sockets.SocketAsyncEventArgs.AllocateNativeOverlapped(), System.cancellationToken, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlapped(), System.handle, System.Net.Sockets.WSABuffer.Length, System.Net.Sockets.SocketAsyncEventArgs.PinSocketAddressBuffer(), System.Net.Sockets.WSABuffer.Pointer, System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResult(), System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResultWithDeferredAsyncHandling(), System.Net.Sockets.SocketAsyncEventArgs.PtrSocketAddressBuffer, System.Memory< T >.Span, System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement(), and System.IntPtr.Zero.
Referenced by System.Net.Sockets.Socket.ReceiveMessageFromAsync().