Terraria: System.Net.Sockets.SocketAsyncEventArgs.SetResults
SetResults() [2/2]
void System.Net.Sockets.SocketAsyncEventArgs.SetResults (SocketError socketError, int bytesTransferred, SocketFlags flags) inline package inherited
Definition at line 532 of file SocketAsyncEventArgs.cs.
    {
        _socketError = socketError;
        _connectByNameError = null;
        _bytesTransferred = bytesTransferred;
        _socketFlags = flags;
    }
References System.Net.Sockets.SocketAsyncEventArgs._bytesTransferred, System.Net.Sockets.SocketAsyncEventArgs._connectByNameError, System.Net.Sockets.SocketAsyncEventArgs._socketError, and System.Net.Sockets.SocketAsyncEventArgs._socketFlags.
Referenced by System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncFailure(), and System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess().