Terraria: System.Net.Sockets.SocketAsyncEventArgs.LogBuffer
LogBuffer()
void System.Net.Sockets.SocketAsyncEventArgs.LogBuffer (int size) inline package inherited
Definition at line 1673 of file SocketAsyncEventArgs.cs.
    {
        if (_bufferList != null)
        {
            for (int i = 0; i < _bufferListInternal.Count; i++)
            {
                WSABuffer wSABuffer = _wsaBufferArrayPinned[i];
                System.Net.NetEventSource.DumpBuffer(this, wSABuffer.Pointer, Math.Min(wSABuffer.Length, size), "LogBuffer");
                if ((size -= wSABuffer.Length) <= 0)
                {
                    break;
                }
            }
        }
        else if (_buffer.Length != 0)
        {
            System.Net.NetEventSource.DumpBuffer(this, _buffer, _offset, size, "LogBuffer");
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._buffer, System.Net.Sockets.SocketAsyncEventArgs._bufferList, System.Net.Sockets.SocketAsyncEventArgs._bufferListInternal, System.Net.Sockets.SocketAsyncEventArgs._offset, System.Net.Sockets.SocketAsyncEventArgs._wsaBufferArrayPinned, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.NetEventSource.DumpBuffer(), System.Memory< T >.Length, and System.Math.Min().
Referenced by System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess().