Terraria: System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess
FinishOperationSyncSuccess()
void System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess (int bytesTransferred, SocketFlags flags) inline package inherited
Definition at line 843 of file SocketAsyncEventArgs.cs.
    {
        SetResults(SocketError.Success, bytesTransferred, flags);
        if (System.Net.NetEventSource.Log.IsEnabled() && bytesTransferred > 0)
        {
            LogBuffer(bytesTransferred);
        }
        SocketError socketError = SocketError.Success;
        switch (_completedOperation)
        {
        case SocketAsyncOperation.Accept:
        {
            System.Net.Internals.SocketAddress socketAddress2 = IPEndPointExtensions.Serialize(_currentSocket._rightEndPoint);
            socketError = FinishOperationAccept(socketAddress2);
            if (socketError == SocketError.Success)
            {
                _acceptSocket = _currentSocket.UpdateAcceptSocket(_acceptSocket, _currentSocket._rightEndPoint.Create(socketAddress2));
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    try
                    {
                        System.Net.NetEventSource.Accepted(_acceptSocket, _acceptSocket.RemoteEndPoint, _acceptSocket.LocalEndPoint);
                    }
                    catch (ObjectDisposedException)
                    {
                    }
                }
            }
            else
            {
                SetResults(socketError, bytesTransferred, flags);
                _acceptSocket = null;
                _currentSocket.UpdateStatusAfterSocketError(socketError);
            }
            break;
        }
        case SocketAsyncOperation.Connect:
            socketError = FinishOperationConnect();
            if (socketError == SocketError.Success)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    try
                    {
                        System.Net.NetEventSource.Connected(_currentSocket, _currentSocket.LocalEndPoint, _currentSocket.RemoteEndPoint);
                    }
                    catch (ObjectDisposedException)
                    {
                    }
                }
                _currentSocket.SetToConnected();
                _connectSocket = _currentSocket;
            }
            else
            {
                SetResults(socketError, bytesTransferred, flags);
                _currentSocket.UpdateStatusAfterSocketError(socketError);
            }
            break;
        case SocketAsyncOperation.Disconnect:
            _currentSocket.SetToDisconnected();
            _currentSocket._remoteEndPoint = null;
            break;
        case SocketAsyncOperation.ReceiveFrom:
        {
            _socketAddress.InternalSize = GetSocketAddressSize();
            System.Net.Internals.SocketAddress socketAddress = IPEndPointExtensions.Serialize(_remoteEndPoint);
            if (!socketAddress.Equals(_socketAddress))
            {
                try
                {
                    _remoteEndPoint = _remoteEndPoint.Create(_socketAddress);
                }
                catch
                {
                }
            }
            break;
        }
        case SocketAsyncOperation.ReceiveMessageFrom:
        {
            _socketAddress.InternalSize = GetSocketAddressSize();
            System.Net.Internals.SocketAddress socketAddress = IPEndPointExtensions.Serialize(_remoteEndPoint);
            if (!socketAddress.Equals(_socketAddress))
            {
                try
                {
                    _remoteEndPoint = _remoteEndPoint.Create(_socketAddress);
                }
                catch
                {
                }
            }
            FinishOperationReceiveMessageFrom();
            break;
        }
        case SocketAsyncOperation.SendPackets:
            FinishOperationSendPackets();
            break;
        }
        if (SocketsTelemetry.Log.IsEnabled())
        {
            LogBytesTransferEvents(_currentSocket?.SocketType, _completedOperation, bytesTransferred);
        }
        Complete();
    }
References System.Net.Sockets.SocketAsyncEventArgs._acceptSocket, System.Net.Sockets.SocketAsyncEventArgs._completedOperation, System.Net.Sockets.SocketAsyncEventArgs._connectSocket, System.Net.Sockets.SocketAsyncEventArgs._currentSocket, System.Net.Sockets.SocketAsyncEventArgs._remoteEndPoint, System.Net.Sockets.Socket._rightEndPoint, System.Net.Sockets.SocketAsyncEventArgs._socketAddress, System.Net.NetEventSource.Accepted(), System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.Net.NetEventSource.Connected(), System.Net.EndPoint.Create(), System.Net.Internals.SocketAddress.Equals(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAccept(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationConnect(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationReceiveMessageFrom(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSendPackets(), System.Net.Sockets.SocketAsyncEventArgs.GetSocketAddressSize(), System.Net.Sockets.Socket.LocalEndPoint, System.Net.NetEventSource.Log, System.Net.Sockets.SocketsTelemetry.Log, System.Net.Sockets.SocketAsyncEventArgs.LogBuffer(), System.Net.Sockets.SocketAsyncEventArgs.LogBytesTransferEvents(), System.Net.Sockets.Socket.RemoteEndPoint, System.Net.Sockets.IPEndPointExtensions.Serialize(), System.Net.Sockets.SocketAsyncEventArgs.SetResults(), System.Net.Sockets.Socket.SetToConnected(), System.Net.Sockets.Socket.SetToDisconnected(), System.Net.Sockets.Socket.UpdateAcceptSocket(), and System.Net.Sockets.Socket.UpdateStatusAfterSocketError().
Referenced by System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendPackets(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(), and System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSync().