Terraria: System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceive
DoOperationReceive()
SocketError System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceive (SafeSocketHandle handle, CancellationToken cancellationToken) inline package inherited
Definition at line 1175 of file SocketAsyncEventArgs.cs.
    {
        if (_bufferList != null)
        {
            return DoOperationReceiveMultiBuffer(handle);
        }
        return DoOperationReceiveSingleBuffer(handle, cancellationToken);
    }
References System.Net.Sockets.SocketAsyncEventArgs._bufferList, System.cancellationToken, System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveMultiBuffer(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveSingleBuffer(), and System.handle.
Referenced by System.Net.Sockets.Socket.ReceiveAsync().