Terraria: System.Net.Sockets.SocketAsyncEventArgs.FreePinHandles
FreePinHandles()
void System.Net.Sockets.SocketAsyncEventArgs.FreePinHandles () inline private inherited
Definition at line 1592 of file SocketAsyncEventArgs.cs.
    {
        _pinState = PinState.None;
        if (_asyncProcessingState != 0)
        {
            _asyncProcessingState = AsyncProcessingState.None;
            _singleBufferHandle.Dispose();
        }
        if (_multipleBufferMemoryHandles != null)
        {
            for (int i = 0; i < _multipleBufferMemoryHandles.Length; i++)
            {
                _multipleBufferMemoryHandles[i].Dispose();
                _multipleBufferMemoryHandles[i] = default(MemoryHandle);
            }
        }
        if (_socketAddressGCHandle.IsAllocated)
        {
            _socketAddressGCHandle.Free();
            _pinnedSocketAddress = null;
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._asyncProcessingState, System.Net.Sockets.SocketAsyncEventArgs._multipleBufferMemoryHandles, System.Net.Sockets.SocketAsyncEventArgs._pinnedSocketAddress, System.Net.Sockets.SocketAsyncEventArgs._pinState, System.Net.Sockets.SocketAsyncEventArgs._singleBufferHandle, System.Net.Sockets.SocketAsyncEventArgs._socketAddressGCHandle, System.Buffers.MemoryHandle.Dispose(), System.Runtime.InteropServices.GCHandle.Free(), and System.Runtime.InteropServices.GCHandle.IsAllocated.
Referenced by System.Net.Sockets.SocketAsyncEventArgs.FreeInternals(), System.Net.Sockets.SocketAsyncEventArgs.SetupMultipleBuffers(), and System.Net.Sockets.SocketAsyncEventArgs.SetupPinHandlesSendPackets().