Terraria: System.Net.Sockets.SocketAsyncEventArgs.SetBuffer
SetBuffer() [1/3]
void System.Net.Sockets.SocketAsyncEventArgs.SetBuffer (byte?[] buffer, int offset, int count) inline inherited
Definition at line 476 of file SocketAsyncEventArgs.cs.
    {
        StartConfiguring();
        try
        {
            if (buffer == null)
            {
                _buffer = default(Memory<byte>);
                _offset = 0;
                _count = 0;
                _bufferIsExplicitArray = false;
                return;
            }
            if (_bufferList != null)
            {
                throw new ArgumentException(System.SR.Format(System.SR.net_ambiguousbuffers, "BufferList"));
            }
            if ((uint)offset > buffer.Length)
            {
                throw new ArgumentOutOfRangeException("offset");
            }
            if ((uint)count > buffer.Length - offset)
            {
                throw new ArgumentOutOfRangeException("count");
            }
            _buffer = buffer;
            _offset = offset;
            _count = count;
            _bufferIsExplicitArray = true;
        }
        finally
        {
            Complete();
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._buffer, System.Net.Sockets.SocketAsyncEventArgs._bufferIsExplicitArray, System.Net.Sockets.SocketAsyncEventArgs._bufferList, System.Net.Sockets.SocketAsyncEventArgs._count, System.Net.Sockets.SocketAsyncEventArgs._offset, System.buffer, System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.count, System.SR.Format(), System.SR.net_ambiguousbuffers, System.offset, and System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring().