Terraria: System.Net.Sockets.SocketAsyncEventArgs.DoOperationAccept
DoOperationAccept()
unsafe SocketError System.Net.Sockets.SocketAsyncEventArgs.DoOperationAccept (Socket socket, SafeSocketHandle handle, SafeSocketHandle acceptHandle, CancellationToken cancellationToken) inline package inherited
Definition at line 1107 of file SocketAsyncEventArgs.cs.
    {
        bool flag = _count != 0;
        Memory<byte> bufferToPin = (flag ? _buffer : ((Memory<byte>)_acceptBuffer));
        fixed (byte* ptr = &MemoryMarshal.GetReference(bufferToPin.Span))
        {
            NativeOverlapped* overlapped = AllocateNativeOverlapped();
            try
            {
                _asyncProcessingState = AsyncProcessingState.InProcess;
                int bytesReceived;
                bool success = socket.AcceptEx(handle, acceptHandle, (IntPtr)(flag ? (ptr + _offset) : ptr), flag ? (_count - _acceptAddressBufferCount) : 0, _acceptAddressBufferCount / 2, _acceptAddressBufferCount / 2, out bytesReceived, overlapped);
                return ProcessIOCPResultWithDeferredAsyncHandling(success, bytesReceived, overlapped, bufferToPin, cancellationToken);
            }
            catch
            {
                _asyncProcessingState = AsyncProcessingState.None;
                FreeNativeOverlapped(overlapped);
                throw;
            }
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._acceptAddressBufferCount, System.Net.Sockets.SocketAsyncEventArgs._acceptBuffer, System.Net.Sockets.SocketAsyncEventArgs._asyncProcessingState, System.Net.Sockets.SocketAsyncEventArgs._buffer, System.Net.Sockets.SocketAsyncEventArgs._count, System.Net.Sockets.SocketAsyncEventArgs._offset, System.Net.Sockets.SocketAsyncEventArgs.AllocateNativeOverlapped(), System.cancellationToken, System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlapped(), System.handle, and System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResultWithDeferredAsyncHandling().
Referenced by System.Net.Sockets.Socket.AcceptAsync().