Terraria: System.Net.Http.HttpMessageInvoker.SendAsync
SendAsync()
virtual Task< HttpResponseMessage > System.Net.Http.HttpMessageInvoker.SendAsync (HttpRequestMessage request, CancellationToken cancellationToken) inline virtual
Reimplemented in System.Net.Http.HttpClient.
Definition at line 61 of file HttpMessageInvoker.cs.
    {
        if (request == null)
        {
            throw new ArgumentNullException("request");
        }
        CheckDisposed();
        if (ShouldSendWithTelemetry(request))
        {
            return SendAsyncWithTelemetry(_handler, request, cancellationToken);
        }
        return _handler.SendAsync(request, cancellationToken);
        static async Task<HttpResponseMessage> SendAsyncWithTelemetry(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken)
        {
            HttpTelemetry.Log.RequestStart(request);
            try
            {
                return await handler.SendAsync(request, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            catch when (LogRequestFailed(telemetryStarted: true))
            {
                throw;
            }
            finally
            {
                HttpTelemetry.Log.RequestStop();
            }
        }
    }
References System.Net.Http.HttpMessageInvoker._handler, System.cancellationToken, System.Net.Http.HttpMessageInvoker.CheckDisposed(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.HttpTelemetry.Log, System.Net.Http.HttpMessageInvoker.LogRequestFailed(), System.Net.Http.HttpMessageHandler.SendAsync(), and System.Net.Http.HttpMessageInvoker.ShouldSendWithTelemetry().
Referenced by System.Net.WebSockets.WebSocketHandle.ConnectAsync().