Terraria: System.Net.Sockets.SocketAsyncEventArgs.SetBuffer
SetBuffer() [2/3]
void System.Net.Sockets.SocketAsyncEventArgs.SetBuffer (int offset, int count) inline inherited
Definition at line 431 of file SocketAsyncEventArgs.cs.
    {
        StartConfiguring();
        try
        {
            if (!_buffer.Equals(default(Memory<byte>)))
            {
                if ((uint)offset > _buffer.Length)
                {
                    throw new ArgumentOutOfRangeException("offset");
                }
                if ((uint)count > _buffer.Length - offset)
                {
                    throw new ArgumentOutOfRangeException("count");
                }
                if (!_bufferIsExplicitArray)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_BufferNotExplicitArray);
                }
                _offset = offset;
                _count = count;
            }
        }
        finally
        {
            Complete();
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._buffer, System.Net.Sockets.SocketAsyncEventArgs._bufferIsExplicitArray, System.Net.Sockets.SocketAsyncEventArgs._count, System.Net.Sockets.SocketAsyncEventArgs._offset, System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.count, System.Memory< T >.Equals(), System.SR.InvalidOperation_BufferNotExplicitArray, System.Memory< T >.Length, System.offset, and System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring().