Terraria: System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAccept
FinishOperationAccept()
unsafe SocketError System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAccept (System::Net::Internals::SocketAddress remoteSocketAddress) inline private inherited
Definition at line 1693 of file SocketAsyncEventArgs.cs.
    {
        bool success = false;
        SafeHandle safeHandle = _currentSocket.SafeHandle;
        SocketError socketError;
        try
        {
            safeHandle.DangerousAddRef(ref success);
            IntPtr pointer = safeHandle.DangerousGetHandle();
            bool flag = _count != 0;
            Memory<byte> memory = (flag ? _buffer : ((Memory<byte>)_acceptBuffer));
            fixed (byte* ptr = &MemoryMarshal.GetReference(memory.Span))
            {
                _currentSocket.GetAcceptExSockaddrs((IntPtr)(flag ? (ptr + _offset) : ptr), flag ? (_count - _acceptAddressBufferCount) : 0, _acceptAddressBufferCount / 2, _acceptAddressBufferCount / 2, out var _, out var _, out var remoteSocketAddress2, out remoteSocketAddress.InternalSize);
                Marshal.Copy(remoteSocketAddress2, remoteSocketAddress.Buffer, 0, remoteSocketAddress.Size);
            }
            socketError = global::Interop.Winsock.setsockopt(_acceptSocket.SafeHandle, SocketOptionLevel.Socket, SocketOptionName.UpdateAcceptContext, ref pointer, IntPtr.Size);
            if (socketError == SocketError.SocketError)
            {
                socketError = SocketPal.GetLastSocketError();
            }
        }
        catch (ObjectDisposedException)
        {
            socketError = SocketError.OperationAborted;
        }
        finally
        {
            if (success)
            {
                safeHandle.DangerousRelease();
            }
        }
        return socketError;
    }
References System.Net.Sockets.SocketAsyncEventArgs._acceptAddressBufferCount, System.Net.Sockets.SocketAsyncEventArgs._acceptBuffer, System.Net.Sockets.SocketAsyncEventArgs._acceptSocket, System.Net.Sockets.SocketAsyncEventArgs._buffer, System.Net.Sockets.SocketAsyncEventArgs._count, System.Net.Sockets.SocketAsyncEventArgs._currentSocket, System.Net.Sockets.SocketAsyncEventArgs._offset, System.Runtime.InteropServices.Marshal.Copy(), System.Net.Sockets.Socket.GetAcceptExSockaddrs(), System.Net.Sockets.SocketPal.GetLastSocketError(), System.pointer, System.Net.Sockets.Socket.SafeHandle, and System.IntPtr.Size.
Referenced by System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess().