Terraria: System.Net.Http.HttpMessageInvoker.Send
Send()
virtual HttpResponseMessage System.Net.Http.HttpMessageInvoker.Send (HttpRequestMessage request, CancellationToken cancellationToken) inline virtual
Reimplemented in System.Net.Http.HttpClient.
Definition at line 35 of file HttpMessageInvoker.cs.
    {
        if (request == null)
        {
            throw new ArgumentNullException("request");
        }
        CheckDisposed();
        if (ShouldSendWithTelemetry(request))
        {
            HttpTelemetry.Log.RequestStart(request);
            try
            {
                return _handler.Send(request, cancellationToken);
            }
            catch when (LogRequestFailed(telemetryStarted: true))
            {
                throw;
            }
            finally
            {
                HttpTelemetry.Log.RequestStop();
            }
        }
        return _handler.Send(request, cancellationToken);
    }
References System.Net.Http.HttpMessageInvoker._handler, System.cancellationToken, System.Net.Http.HttpMessageInvoker.CheckDisposed(), System.Net.Http.HttpTelemetry.Log, System.Net.Http.HttpMessageInvoker.LogRequestFailed(), System.Net.Http.HttpMessageHandler.Send(), and System.Net.Http.HttpMessageInvoker.ShouldSendWithTelemetry().