Terraria: System.Net.Sockets.SocketAsyncEventArgs.PinSocketAddressBuffer
PinSocketAddressBuffer()
void System.Net.Sockets.SocketAsyncEventArgs.PinSocketAddressBuffer () inline private inherited
Definition at line 1569 of file SocketAsyncEventArgs.cs.
    {
        if (_pinnedSocketAddress != _socketAddress)
        {
            if (_socketAddressGCHandle.IsAllocated)
            {
                _socketAddressGCHandle.Free();
            }
            _socketAddressGCHandle = GCHandle.Alloc(_socketAddress.Buffer, GCHandleType.Pinned);
            _socketAddress.CopyAddressSizeIntoBuffer();
            _pinnedSocketAddress = _socketAddress;
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._pinnedSocketAddress, System.Net.Sockets.SocketAsyncEventArgs._socketAddress, System.Net.Sockets.SocketAsyncEventArgs._socketAddressGCHandle, System.Runtime.InteropServices.GCHandle.Alloc(), System.Runtime.InteropServices.GCHandle.Free(), and System.Runtime.InteropServices.GCHandle.IsAllocated.
Referenced by System.Net.Sockets.SocketAsyncEventArgs.DoOperationConnectEx(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveFrom(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveMessageFrom(), and System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendTo().