Terraria: System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendSingleBuffer
DoOperationSendSingleBuffer()
unsafe SocketError System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendSingleBuffer (SafeSocketHandle handle, CancellationToken cancellationToken) inline package inherited
Definition at line 1364 of file SocketAsyncEventArgs.cs.
    {
        fixed (byte* ptr = &MemoryMarshal.GetReference(_buffer.Span))
        {
            NativeOverlapped* overlapped = AllocateNativeOverlapped();
            try
            {
                _asyncProcessingState = AsyncProcessingState.InProcess;
                WSABuffer wSABuffer = default(WSABuffer);
                wSABuffer.Length = _count;
                wSABuffer.Pointer = (IntPtr)(ptr + _offset);
                WSABuffer wSABuffer2 = wSABuffer;
                int bytesTransferred;
                SocketError socketError = global::Interop.Winsock.WSASend(handle, &wSABuffer2, 1, out bytesTransferred, _socketFlags, overlapped, IntPtr.Zero);
                return ProcessIOCPResultWithDeferredAsyncHandling(socketError == SocketError.Success, bytesTransferred, overlapped, _buffer, cancellationToken);
            }
            catch
            {
                _asyncProcessingState = AsyncProcessingState.None;
                FreeNativeOverlapped(overlapped);
                throw;
            }
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._asyncProcessingState, System.Net.Sockets.SocketAsyncEventArgs._buffer, System.Net.Sockets.SocketAsyncEventArgs._count, System.Net.Sockets.SocketAsyncEventArgs._offset, System.Net.Sockets.SocketAsyncEventArgs._socketFlags, System.Net.Sockets.SocketAsyncEventArgs.AllocateNativeOverlapped(), System.cancellationToken, System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlapped(), System.handle, System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResultWithDeferredAsyncHandling(), System.Memory< T >.Span, and System.IntPtr.Zero.
Referenced by System.Net.Sockets.SocketAsyncEventArgs.DoOperationSend().