Terraria: System.Net.Sockets.SocketAsyncEventArgs.DoOperationConnect
DoOperationConnect()
SocketError System.Net.Sockets.SocketAsyncEventArgs.DoOperationConnect (Socket socket, SafeSocketHandle handle) inline package inherited
Definition at line 1130 of file SocketAsyncEventArgs.cs.
    {
        SocketError socketError = SocketPal.Connect(handle, _socketAddress.Buffer, _socketAddress.Size);
        FinishOperationSync(socketError, 0, SocketFlags.None);
        return socketError;
    }
References System.Net.Sockets.SocketAsyncEventArgs._socketAddress, System.Net.Sockets.SocketPal.Connect(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSync(), and System.handle.
Referenced by System.Net.Sockets.Socket.ConnectAsync().