Terraria: System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon
StartOperationCommon()
void System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon (Socket socket, SocketAsyncOperation operation) inline package inherited
Definition at line 609 of file SocketAsyncEventArgs.cs.
    {
        int num = Interlocked.CompareExchange(ref _operating, 1, 0);
        if (num != 0)
        {
            ThrowForNonFreeStatus(num);
        }
        _completedOperation = operation;
        _currentSocket = socket;
        if (_flowExecutionContext || (SocketsTelemetry.Log.IsEnabled() && (operation == SocketAsyncOperation.Connect || operation == SocketAsyncOperation.Accept)))
        {
            _context = ExecutionContext.Capture();
        }
        StartOperationCommonCore();
    }
References System.Net.Sockets.SocketAsyncEventArgs._completedOperation, System.Net.Sockets.SocketAsyncEventArgs._context, System.Net.Sockets.SocketAsyncEventArgs._currentSocket, System.Net.Sockets.SocketAsyncEventArgs._flowExecutionContext, System.Net.Sockets.SocketAsyncEventArgs._operating, System.Threading.ExecutionContext.Capture(), System.Threading.Interlocked.CompareExchange(), System.Net.Sockets.SocketsTelemetry.Log, System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommonCore(), and System.Net.Sockets.SocketAsyncEventArgs.ThrowForNonFreeStatus().
Referenced by System.Net.Sockets.Socket.AcceptAsync(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.Sockets.Socket.DisconnectAsync(), System.Net.Sockets.Socket.ReceiveAsync(), System.Net.Sockets.Socket.ReceiveFromAsync(), System.Net.Sockets.Socket.ReceiveMessageFromAsync(), System.Net.Sockets.Socket.SendAsync(), System.Net.Sockets.Socket.SendPacketsAsync(), and System.Net.Sockets.Socket.SendToAsync().