Terraria: System.Net.Sockets.SocketAsyncEventArgs.InitializeInternals
InitializeInternals()
void System.Net.Sockets.SocketAsyncEventArgs.InitializeInternals () inline private inherited
Definition at line 1010 of file SocketAsyncEventArgs.cs.
    {
        _preAllocatedOverlapped = PreAllocatedOverlapped.UnsafeCreate(s_completionPortCallback, _strongThisRef, null);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"new PreAllocatedOverlapped {_preAllocatedOverlapped}", "InitializeInternals");
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._preAllocatedOverlapped, System.Net.Sockets.SocketAsyncEventArgs._strongThisRef, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.Sockets.SocketAsyncEventArgs.s_completionPortCallback, and System.Threading.PreAllocatedOverlapped.UnsafeCreate().
Referenced by System.Net.Sockets.SocketAsyncEventArgs.SocketAsyncEventArgs().