Terraria: System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendToMultiBuffer
DoOperationSendToMultiBuffer()
unsafe SocketError System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendToMultiBuffer (SafeSocketHandle handle) inline package inherited
Definition at line 1512 of file SocketAsyncEventArgs.cs.
    {
        NativeOverlapped* overlapped = AllocateNativeOverlapped();
        try
        {
            int bytesTransferred;
            SocketError socketError = global::Interop.Winsock.WSASendTo(handle, _wsaBufferArrayPinned, _bufferListInternal.Count, out bytesTransferred, _socketFlags, PtrSocketAddressBuffer, _socketAddress.Size, overlapped, IntPtr.Zero);
            return ProcessIOCPResult(socketError == SocketError.Success, bytesTransferred, overlapped);
        }
        catch
        {
            FreeNativeOverlapped(overlapped);
            throw;
        }
    }
References System.Net.Sockets.SocketAsyncEventArgs._bufferListInternal, System.Net.Sockets.SocketAsyncEventArgs._socketAddress, System.Net.Sockets.SocketAsyncEventArgs._socketFlags, System.Net.Sockets.SocketAsyncEventArgs._wsaBufferArrayPinned, System.Net.Sockets.SocketAsyncEventArgs.AllocateNativeOverlapped(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Sockets.SocketAsyncEventArgs.FreeNativeOverlapped(), System.handle, System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResult(), System.Net.Sockets.SocketAsyncEventArgs.PtrSocketAddressBuffer, and System.IntPtr.Zero.
Referenced by System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendTo().