Terraria: System.Net.Sockets.SocketAsyncEventArgs.RegisterToCancelPendingIO
RegisterToCancelPendingIO()
unsafe void System.Net.Sockets.SocketAsyncEventArgs.RegisterToCancelPendingIO (NativeOverlapped * overlapped, CancellationToken cancellationToken) inline private inherited
Definition at line 1036 of file SocketAsyncEventArgs.cs.
    {
        _pendingOverlappedForCancellation = overlapped;
        _registrationToCancelPendingIO = cancellationToken.UnsafeRegister(delegate(object s)
        {
            SocketAsyncEventArgs socketAsyncEventArgs = (SocketAsyncEventArgs)s;
            SafeSocketHandle safeHandle = socketAsyncEventArgs._currentSocket.SafeHandle;
            if (!safeHandle.IsClosed)
            {
                try
                {
                    bool flag = global::Interop.Kernel32.CancelIoEx(safeHandle, socketAsyncEventArgs._pendingOverlappedForCancellation);
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(socketAsyncEventArgs, flag ? "Socket operation canceled." : $"CancelIoEx failed with error '{Marshal.GetLastWin32Error()}'.", "RegisterToCancelPendingIO");
                    }
                }
                catch (ObjectDisposedException)
                {
                }
            }
        }, this);
    }
References System.Net.Sockets.SocketAsyncEventArgs.SocketAsyncEventArgs(), System.Net.Sockets.SocketAsyncEventArgs._pendingOverlappedForCancellation, System.Net.Sockets.SocketAsyncEventArgs._registrationToCancelPendingIO, System.cancellationToken, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.s.
Referenced by System.Net.Sockets.SocketAsyncEventArgs.ProcessIOCPResultWithDeferredAsyncHandling().