Terraria: System.Xml.XmlNodeReader.LookupNamespace
LookupNamespace() [2/2]
string IXmlNamespaceResolver. System.Xml.XmlNodeReader.LookupNamespace (string prefix) inline private
Implements System.Xml.IXmlNamespaceResolver.
Definition at line 695 of file XmlNodeReader.cs.
    {
        if (!IsInReadingStates())
        {
            return _readerNav.DefaultLookupNamespace(prefix);
        }
        string text = _readerNav.LookupNamespace(prefix);
        if (text != null)
        {
            text = _readerNav.NameTable.Add(text);
        }
        return text;
    }
References System.Xml.XmlNodeReader._readerNav, System.Xml.XmlNameTable.Add(), System.Xml.XmlNodeReaderNavigator.DefaultLookupNamespace(), System.Xml.XmlNodeReader.IsInReadingStates(), System.Xml.XmlNodeReaderNavigator.LookupNamespace(), System.Xml.XmlNodeReaderNavigator.NameTable, System.prefix, and System.text.