Terraria: System.Xml.XmlNodeReader.Read
Read() [2/2]
bool System.Xml.XmlNodeReader.Read (bool fSkipChildren) inline private
Definition at line 399 of file XmlNodeReader.cs.
    {
        if (_fEOF)
        {
            return false;
        }
        if (_readState == ReadState.Initial)
        {
            if (_readerNav.NodeType == XmlNodeType.Document || _readerNav.NodeType == XmlNodeType.DocumentFragment)
            {
                _bStartFromDocument = true;
                if (!ReadNextNode(fSkipChildren))
                {
                    _readState = ReadState.Error;
                    return false;
                }
            }
            ReSetReadingMarks();
            _readState = ReadState.Interactive;
            _nodeType = _readerNav.NodeType;
            _curDepth = 0;
            return true;
        }
        if (_bInReadBinary)
        {
            FinishReadBinary();
        }
        bool flag = false;
        if (_readerNav.CreatedOnAttribute)
        {
            return false;
        }
        ReSetReadingMarks();
        if (ReadNextNode(fSkipChildren))
        {
            return true;
        }
        if (_readState == ReadState.Initial || _readState == ReadState.Interactive)
        {
            _readState = ReadState.Error;
        }
        if (_readState == ReadState.EndOfFile)
        {
            _nodeType = XmlNodeType.None;
        }
        return false;
    }
References System.Xml.XmlNodeReader._bInReadBinary, System.Xml.XmlNodeReader._bStartFromDocument, System.Xml.XmlNodeReader._curDepth, System.Xml.XmlNodeReader._fEOF, System.Xml.XmlNodeReader._nodeType, System.Xml.XmlNodeReader._readerNav, System.Xml.XmlNodeReader._readState, System.Xml.XmlNodeReaderNavigator.CreatedOnAttribute, System.Xml.XmlNodeReader.FinishReadBinary(), System.Xml.XmlNodeReaderNavigator.NodeType, System.Xml.XmlNodeReader.ReadNextNode(), and System.Xml.XmlNodeReader.ReSetReadingMarks().