Terraria: System.Xml.XmlNodeReader.MoveToAttribute
MoveToAttribute() [3/3]
override bool System.Xml.XmlNodeReader.MoveToAttribute (string name, string? namespaceURI) inline
Definition at line 279 of file XmlNodeReader.cs.
    {
        if (!IsInReadingStates())
        {
            return false;
        }
        _readerNav.ResetMove(ref _curDepth, ref _nodeType);
        string namespaceURI2 = ((namespaceURI == null) ? string.Empty : namespaceURI);
        if (_readerNav.MoveToAttribute(name, namespaceURI2))
        {
            _curDepth++;
            _nodeType = _readerNav.NodeType;
            if (_bInReadBinary)
            {
                FinishReadBinary();
            }
            return true;
        }
        _readerNav.RollBackMove(ref _curDepth);
        return false;
    }
References System.Xml.XmlNodeReader._bInReadBinary, System.Xml.XmlNodeReader._curDepth, System.Xml.XmlNodeReader._nodeType, System.Xml.XmlNodeReader._readerNav, System.Xml.Dictionary, System.Xml.XmlNodeReader.FinishReadBinary(), System.Xml.XmlNodeReader.IsInReadingStates(), System.Xml.XmlNodeReaderNavigator.MoveToAttribute(), System.Xml.XmlNodeReaderNavigator.NodeType, System.Xml.XmlNodeReaderNavigator.ResetMove(), and System.Xml.XmlNodeReaderNavigator.RollBackMove().