Terraria: System.Xml.XmlNodeReader.FinishReadBinary
FinishReadBinary()
void System.Xml.XmlNodeReader.FinishReadBinary () inline private
Definition at line 679 of file XmlNodeReader.cs.
    {
        _bInReadBinary = false;
        _readBinaryHelper.Finish();
    }
References System.Xml.XmlNodeReader._bInReadBinary, System.Xml.XmlNodeReader._readBinaryHelper, and System.Xml.ReadContentAsBinaryHelper.Finish().
Referenced by System.Xml.XmlNodeReader.MoveToAttribute(), System.Xml.XmlNodeReader.MoveToAttribute(), System.Xml.XmlNodeReader.MoveToAttribute(), System.Xml.XmlNodeReader.MoveToElement(), System.Xml.XmlNodeReader.MoveToFirstAttribute(), System.Xml.XmlNodeReader.MoveToNextAttribute(), and System.Xml.XmlNodeReader.Read().