Terraria: System.Xml.XmlNodeReader.ReadForward
ReadForward()
bool System.Xml.XmlNodeReader.ReadForward (bool fSkipChildren) inline private
Definition at line 516 of file XmlNodeReader.cs.
    {
        if (_readState == ReadState.Error)
        {
            return false;
        }
        if (!_bStartFromDocument && _curDepth == 0)
        {
            return ReadAtZeroLevel(fSkipChildren);
        }
        if (_readerNav.MoveToNext())
        {
            _nodeType = _readerNav.NodeType;
            return true;
        }
        if (_curDepth == 0)
        {
            return ReadAtZeroLevel(fSkipChildren);
        }
        if (_readerNav.MoveToParent())
        {
            if (_readerNav.NodeType == XmlNodeType.Element)
            {
                _curDepth--;
                _nodeType = XmlNodeType.EndElement;
                return true;
            }
            if (_readerNav.NodeType == XmlNodeType.EntityReference)
            {
                _curDepth--;
                _nodeType = XmlNodeType.EndEntity;
                return true;
            }
            return true;
        }
        return false;
    }
References System.Xml.XmlNodeReader._bStartFromDocument, System.Xml.XmlNodeReader._curDepth, System.Xml.XmlNodeReader._nodeType, System.Xml.XmlNodeReader._readerNav, System.Xml.XmlNodeReader._readState, System.Xml.XmlNodeReaderNavigator.MoveToNext(), System.Xml.XmlNodeReaderNavigator.MoveToParent(), System.Xml.XmlNodeReaderNavigator.NodeType, and System.Xml.XmlNodeReader.ReadAtZeroLevel().
Referenced by System.Xml.XmlNodeReader.ReadNextNode().