Terraria: System.Xml.XmlNodeReader.ReadAttributeValue
ReadAttributeValue()
override bool System.Xml.XmlNodeReader.ReadAttributeValue () inline
Definition at line 601 of file XmlNodeReader.cs.
    {
        if (!IsInReadingStates())
        {
            return false;
        }
        if (_readerNav.ReadAttributeValue(ref _curDepth, ref _bResolveEntity, ref _nodeType))
        {
            _bInReadBinary = false;
            return true;
        }
        return false;
    }
References System.Xml.XmlNodeReader._bInReadBinary, System.Xml.XmlNodeReader._bResolveEntity, System.Xml.XmlNodeReader._curDepth, System.Xml.XmlNodeReader._nodeType, System.Xml.XmlNodeReader._readerNav, System.Xml.XmlNodeReader.IsInReadingStates(), and System.Xml.XmlNodeReaderNavigator.ReadAttributeValue().
Referenced by System.Runtime.Serialization.ExtensionDataReader.ReadAttributeValue().