Terraria: ChatHelper.BroadcastChatMessage
BroadcastChatMessage()
static void ChatHelper.BroadcastChatMessage (NetworkText text, Color color, int excludedPlayer = -1) inline static
     {
         BroadcastChatMessageAs(byte.MaxValue, text, color, excludedPlayer);
     }
References BroadcastChatMessageAs().
Referenced by WorldGen.BroadcastText(), NPC.checkDead(), WorldGen.CheckOrb(), NPC.CheckProgressFrostMoon(), NPC.CheckProgressPumpkinMoon(), NPC.CountKillForBannersAndDropThem(), NPC.DoDeathEvents(), NPC.DoDeathEvents_CelebrateBossDeath(), MessageBuffer.GetData(), Projectile.HandleMovement(), Main.InvasionWarning(), Player.KillMe(), WorldGen.meteor(), NPC.NewNPC(), NPC.NPCLoot(), AllDeathCommand.ProcessIncomingMessage(), AllPVPDeathCommand.ProcessIncomingMessage(), DeathCommand.ProcessIncomingMessage(), EmoteCommand.ProcessIncomingMessage(), PVPDeathCommand.ProcessIncomingMessage(), RollCommand.ProcessIncomingMessage(), GolfHelper.ContactListener.PutBallInCup_TextAndEffects(), WorldGen.SmashAltar(), WorldGen.smCallBack(), NPC.SpawnBoss(), NPC.SpawnOnPlayer(), NPC.SpawnSkeletron(), WorldGen.SpawnTownNPC(), WorldGen.SpawnTravelNPC(), NPC.SpawnWOF(), Main.startDedInputCallBack(), Main.startPumpkinMoon(), Main.startSnowMoon(), NetMessage.SyncOnePlayer(), NPC.UnlockOrExchangePet(), WorldGen.UnspawnTravelNPC(), Main.UpdateSlimeRainWarning(), Main.UpdateTime_StartDay(), and Main.UpdateTime_StartNight().