Terraria: ChatHelper.DisplayMessage
DisplayMessage()
static void ChatHelper.DisplayMessage (NetworkText text, Color color, byte messageAuthor) inline static
     {
         string text2 = text.ToString();
         if (messageAuthor < byte.MaxValue)
         {
             Main.player[messageAuthor].chatOverhead.NewMessage(text2, Main.PlayerOverheadChatMessageDisplayTime);
             Main.player[messageAuthor].chatOverhead.color = color;
             text2 = NameTagHandler.GenerateTag(Main.player[messageAuthor].name) + " " + text2;
         }
         if (ShouldCacheMessage())
         {
             CacheMessage(text2, color);
         }
         else
         {
             Main.NewTextMultiline(text2, force: false, color);
         }
     }
References CacheMessage(), Player.chatOverhead, Player.OverheadMessage.color, NameTagHandler.GenerateTag(), Player.name, Player.OverheadMessage.NewMessage(), Main.NewTextMultiline(), Main.player, Main.PlayerOverheadChatMessageDisplayTime, ShouldCacheMessage(), and NetworkText.ToString().
Referenced by BroadcastChatMessageAs(), NetTextModule.DeserializeAsClient(), DisplayMessageOnClient(), and SendChatMessageToClientAs().