Terraria: System.UInt64.Parse
Parse() [6/12]
static ulong System.UInt64.Parse (string s) inline static
Definition at line 117 of file UInt64.cs.
    {
        if (s == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.s);
        }
        return Number.ParseUInt64(s, NumberStyles.Integer, NumberFormatInfo.CurrentInfo);
    }
References System.Globalization.NumberFormatInfo.CurrentInfo, System.Number.ParseUInt64(), System.s, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.UInt64.Parse(), System.UInt64.Parse(), System.UInt64.Parse(), and System.UInt64.Parse().