Terraria: System.Runtime.Serialization.ObjectIDGenerator.HasId
HasId()
virtual long System.Runtime.Serialization.ObjectIDGenerator.HasId (object obj, out bool firstTime) inline virtual
Definition at line 75 of file ObjectIDGenerator.cs.
    {
        if (obj == null)
        {
            throw new ArgumentNullException("obj");
        }
        bool found;
        int num = FindElement(obj, out found);
        if (found)
        {
            firstTime = false;
            return _ids[num];
        }
        firstTime = true;
        return 0L;
    }
References System.Runtime.Serialization.ObjectIDGenerator._ids, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ObjectIDGenerator.FindElement(), System.L, and System.obj.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetNext(), and System.Runtime.Serialization.Formatter.GetNext().