Terraria: System.Xml.Xsl.XsltOld.SortAction.Compile
Compile()
override void System.Xml.Xsl.XsltOld.SortAction.Compile (Compiler compiler) inline package
Definition at line 115 of file SortAction.cs.
    {
        CompileAttributes(compiler);
        CheckEmpty(compiler);
        if (_selectKey == -1)
        {
            _selectKey = compiler.AddQuery(".");
        }
        _forwardCompatibility = compiler.ForwardCompatibility;
        _manager = compiler.CloneScopeManager();
        _lang = ParseLang(CompiledAction.PrecalculateAvt(ref _langAvt));
        _dataType = ParseDataType(CompiledAction.PrecalculateAvt(ref _dataTypeAvt), _manager);
        _order = ParseOrder(CompiledAction.PrecalculateAvt(ref _orderAvt));
        _caseOrder = ParseCaseOrder(CompiledAction.PrecalculateAvt(ref _caseOrderAvt));
        if (_langAvt == null && _dataTypeAvt == null && _orderAvt == null && _caseOrderAvt == null)
        {
            _sort = new Sort(_selectKey, _lang, _dataType, _order, _caseOrder);
        }
    }
References System.Xml.Xsl.XsltOld.SortAction._caseOrder, System.Xml.Xsl.XsltOld.SortAction._caseOrderAvt, System.Xml.Xsl.XsltOld.SortAction._dataType, System.Xml.Xsl.XsltOld.SortAction._dataTypeAvt, System.Xml.Xsl.XsltOld.SortAction._forwardCompatibility, System.Xml.Xsl.XsltOld.SortAction._lang, System.Xml.Xsl.XsltOld.SortAction._langAvt, System.Xml.Xsl.XsltOld.SortAction._manager, System.Xml.Xsl.XsltOld.SortAction._order, System.Xml.Xsl.XsltOld.SortAction._orderAvt, System.Xml.Xsl.XsltOld.SortAction._selectKey, System.Xml.Xsl.XsltOld.SortAction._sort, System.Xml.Xsl.XsltOld.CompiledAction.CheckEmpty(), System.Xml.Xsl.XsltOld.CompiledAction.CompileAttributes(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.SortAction.ParseCaseOrder(), System.Xml.Xsl.XsltOld.SortAction.ParseDataType(), System.Xml.Xsl.XsltOld.SortAction.ParseLang(), System.Xml.Xsl.XsltOld.SortAction.ParseOrder(), and System.Xml.Xsl.XsltOld.CompiledAction.PrecalculateAvt().