Terraria: LunarPillarBigProgessBar.ValidateAndCollectNecessaryInfo
ValidateAndCollectNecessaryInfo()
bool LunarPillarBigProgessBar.ValidateAndCollectNecessaryInfo (ref BigProgressBarInfo info) inline inherited
Implements IBigProgressBar.
     {
         if (info.npcIndexToAimAt < 0 || info.npcIndexToAimAt > 200)
         {
             return false;
         }
         NPC nPC = Main.npc[info.npcIndexToAimAt];
         if (!nPC.active)
         {
             return false;
         }
         int bossHeadTextureIndex = nPC.GetBossHeadTextureIndex();
         if (bossHeadTextureIndex == -1)
         {
             return false;
         }
         if (!IsPlayerInCombatArea())
         {
             return false;
         }
         if (nPC.ai[2] == 1f)
         {
             return false;
         }
         Utils.Clamp((float)nPC.life / (float)nPC.lifeMax, 0f, 1f);
         _ = (float)(int)MathHelper.Clamp(GetCurrentShieldValue(), 0f, GetMaxShieldValue()) / GetMaxShieldValue();
         _ = 600f * Main.GameModeInfo.EnemyMaxLifeMultiplier * GetMaxShieldValue() / (float)nPC.lifeMax;
         _cache.SetLife(nPC.life, nPC.lifeMax);
         _cache.SetShield(GetCurrentShieldValue(), GetMaxShieldValue());
         _headIndex = bossHeadTextureIndex;
         return true;
     }
References LunarPillarBigProgessBar._cache, LunarPillarBigProgessBar._headIndex, Entity.active, NPC.ai, GameModeData.EnemyMaxLifeMultiplier, Main.GameModeInfo, NPC.GetBossHeadTextureIndex(), LunarPillarBigProgessBar.GetCurrentShieldValue(), LunarPillarBigProgessBar.GetMaxShieldValue(), LunarPillarBigProgessBar.IsPlayerInCombatArea(), NPC.life, NPC.lifeMax, Main.npc, BigProgressBarCache.SetLife(), and BigProgressBarCache.SetShield().