Terraria: System.Xml.Xsl.XsltOld.SortAction.ParseLang
ParseLang()
string System.Xml.Xsl.XsltOld.SortAction.ParseLang (string value) inline private
Definition at line 32 of file SortAction.cs.
    {
        if (value == null)
        {
            return null;
        }
        CultureInfo cultureInfo = new CultureInfo(value);
        if (!XmlComplianceUtil.IsValidLanguageID(value.ToCharArray(), 0, value.Length) && (value.Length == 0 || cultureInfo == null))
        {
            if (_forwardCompatibility)
            {
                return null;
            }
            throw XsltException.Create(System.SR.Xslt_InvalidAttrValue, "lang", value);
        }
        return value;
    }
References System.Xml.Xsl.XsltOld.SortAction._forwardCompatibility, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.XmlComplianceUtil.IsValidLanguageID(), System.value, and System.SR.Xslt_InvalidAttrValue.
Referenced by System.Xml.Xsl.XsltOld.SortAction.Compile(), and System.Xml.Xsl.XsltOld.SortAction.Execute().