Terraria: Terraria.GameContent.UI.Elements.UICharacterListItem.UICharacterListItem
UICharacterListItem()
Terraria.GameContent.UI.Elements.UICharacterListItem.UICharacterListItem (PlayerFileData data, int snapPointIndex) inline
Definition at line 47 of file UICharacterListItem.cs.
    {
        BorderColor = new Color(89, 116, 213) * 0.7f;
        _dividerTexture = Main.Assets.Request<Texture2D>("Images/UI/Divider", (AssetRequestMode)1);
        _innerPanelTexture = Main.Assets.Request<Texture2D>("Images/UI/InnerPanelBackground", (AssetRequestMode)1);
        _buttonCloudActiveTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonCloudActive", (AssetRequestMode)1);
        _buttonCloudInactiveTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonCloudInactive", (AssetRequestMode)1);
        _buttonFavoriteActiveTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonFavoriteActive", (AssetRequestMode)1);
        _buttonFavoriteInactiveTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonFavoriteInactive", (AssetRequestMode)1);
        _buttonPlayTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonPlay", (AssetRequestMode)1);
        _buttonRenameTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonRename", (AssetRequestMode)1);
        _buttonDeleteTexture = Main.Assets.Request<Texture2D>("Images/UI/ButtonDelete", (AssetRequestMode)1);
        Height.Set(96f, 0f);
        Width.Set(0f, 1f);
        SetPadding(6f);
        _data = data;
        _playerPanel = new UICharacter(data.Player, animated: false, hasBackPanel: true, 1f, useAClone: true);
        _playerPanel.Left.Set(4f, 0f);
        _playerPanel.OnLeftDoubleClick += PlayGame;
        base.OnLeftDoubleClick += PlayGame;
        Append(_playerPanel);
        float num = 4f;
        UIImageButton uIImageButton = new UIImageButton(_buttonPlayTexture);
        uIImageButton.VAlign = 1f;
        uIImageButton.Left.Set(num, 0f);
        uIImageButton.OnLeftClick += PlayGame;
        uIImageButton.OnMouseOver += PlayMouseOver;
        uIImageButton.OnMouseOut += ButtonMouseOut;
        Append(uIImageButton);
        num += 24f;
        UIImageButton uIImageButton2 = new UIImageButton(_data.IsFavorite ? _buttonFavoriteActiveTexture : _buttonFavoriteInactiveTexture);
        uIImageButton2.VAlign = 1f;
        uIImageButton2.Left.Set(num, 0f);
        uIImageButton2.OnLeftClick += FavoriteButtonClick;
        uIImageButton2.OnMouseOver += FavoriteMouseOver;
        uIImageButton2.OnMouseOut += ButtonMouseOut;
        uIImageButton2.SetVisibility(1f, _data.IsFavorite ? 0.8f : 0.4f);
        Append(uIImageButton2);
        num += 24f;
        if (SocialAPI.Cloud != null)
        {
            UIImageButton uIImageButton3 = new UIImageButton(_data.IsCloudSave ? _buttonCloudActiveTexture : _buttonCloudInactiveTexture);
            uIImageButton3.VAlign = 1f;
            uIImageButton3.Left.Set(num, 0f);
            uIImageButton3.OnLeftClick += CloudButtonClick;
            uIImageButton3.OnMouseOver += CloudMouseOver;
            uIImageButton3.OnMouseOut += ButtonMouseOut;
            Append(uIImageButton3);
            uIImageButton3.SetSnapPoint("Cloud", snapPointIndex);
            num += 24f;
        }
        UIImageButton uIImageButton4 = new UIImageButton(_buttonRenameTexture);
        uIImageButton4.VAlign = 1f;
        uIImageButton4.Left.Set(num, 0f);
        uIImageButton4.OnLeftClick += RenameButtonClick;
        uIImageButton4.OnMouseOver += RenameMouseOver;
        uIImageButton4.OnMouseOut += ButtonMouseOut;
        Append(uIImageButton4);
        num += 24f;
        UIImageButton uIImageButton5 = new UIImageButton(_buttonDeleteTexture)
        {
            VAlign = 1f,
            HAlign = 1f
        };
        if (!_data.IsFavorite)
        {
            uIImageButton5.OnLeftClick += DeleteButtonClick;
        }
        uIImageButton5.OnMouseOver += DeleteMouseOver;
        uIImageButton5.OnMouseOut += DeleteMouseOut;
        _deleteButton = uIImageButton5;
        Append(uIImageButton5);
        num += 4f;
        _buttonLabel = new UIText("");
        _buttonLabel.VAlign = 1f;
        _buttonLabel.Left.Set(num, 0f);
        _buttonLabel.Top.Set(-3f, 0f);
        Append(_buttonLabel);
        _deleteButtonLabel = new UIText("");
        _deleteButtonLabel.VAlign = 1f;
        _deleteButtonLabel.HAlign = 1f;
        _deleteButtonLabel.Left.Set(-30f, 0f);
        _deleteButtonLabel.Top.Set(-3f, 0f);
        Append(_deleteButtonLabel);
        uIImageButton.SetSnapPoint("Play", snapPointIndex);
        uIImageButton2.SetSnapPoint("Favorite", snapPointIndex);
        uIImageButton4.SetSnapPoint("Rename", snapPointIndex);
        uIImageButton5.SetSnapPoint("Delete", snapPointIndex);
    }
References Terraria.GameContent.UI.Elements.UICharacterListItem._buttonCloudActiveTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonCloudInactiveTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonDeleteTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonFavoriteActiveTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonFavoriteInactiveTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonLabel, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonPlayTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._buttonRenameTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._data, Terraria.GameContent.UI.Elements.UICharacterListItem._deleteButton, Terraria.GameContent.UI.Elements.UICharacterListItem._deleteButtonLabel, Terraria.GameContent.UI.Elements.UICharacterListItem._dividerTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._innerPanelTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._playerPanel, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIPanel.BorderColor, Terraria.GameContent.UI.Elements.UICharacterListItem.ButtonMouseOut(), Terraria.Social.SocialAPI.Cloud, Terraria.GameContent.UI.Elements.UICharacterListItem.CloudButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.CloudMouseOver(), Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteMouseOut(), Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteMouseOver(), Terraria.GameContent.UI.Elements.UICharacterListItem.FavoriteButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.FavoriteMouseOver(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.IO.FileData.IsCloudSave, Terraria.IO.FileData.IsFavorite, Terraria.UI.UIElement.Left, Terraria.IO.PlayerFileData.Player, Terraria.GameContent.UI.Elements.UICharacterListItem.PlayGame(), Terraria.GameContent.UI.Elements.UICharacterListItem.PlayMouseOver(), Terraria.GameContent.UI.Elements.UICharacterListItem.RenameButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.RenameMouseOver(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.