Terraria: MS.Internal.Xml.XPath.NumberFunctions.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.NumberFunctions.Evaluate (XPathNodeIterator nodeIterator) inline
Definition at line 51 of file NumberFunctions.cs.
    {
        return _ftype switch
        {
            Function.FunctionType.FuncNumber => Number(nodeIterator),
            Function.FunctionType.FuncSum => Sum(nodeIterator),
            Function.FunctionType.FuncFloor => Floor(nodeIterator),
            Function.FunctionType.FuncCeiling => Ceiling(nodeIterator),
            Function.FunctionType.FuncRound => Round(nodeIterator),
            _ => throw new InvalidOperationException(),
        };
    }
References MS.Internal.Xml.XPath.NumberFunctions._ftype, MS.Internal.Xml.XPath.NumberFunctions.Ceiling(), System.Xml.Dictionary, MS.Internal.Xml.XPath.NumberFunctions.Floor(), System.Number, MS.Internal.Xml.XPath.NumberFunctions.Round(), and MS.Internal.Xml.XPath.NumberFunctions.Sum().