Terraria: MS.Internal.Xml.XPath.NumberFunctions.Number
Number() [1/3]
static double MS.Internal.Xml.XPath.NumberFunctions.Number (bool arg) inline static package
Definition at line 37 of file NumberFunctions.cs.
    {
        if (!arg)
        {
            return 0.0;
        }
        return 1.0;
    }
References System.Xml.Dictionary.
Referenced by MS.Internal.Xml.XPath.LogicalExpr.cmpBoolBoolO(), MS.Internal.Xml.XPath.LogicalExpr.cmpBoolNumberO(), MS.Internal.Xml.XPath.LogicalExpr.cmpBoolStringO(), MS.Internal.Xml.XPath.LogicalExpr.cmpQueryBoolO(), MS.Internal.Xml.XPath.LogicalExpr.cmpQueryNumber(), MS.Internal.Xml.XPath.LogicalExpr.cmpQueryQueryO(), MS.Internal.Xml.XPath.LogicalExpr.cmpQueryStringO(), MS.Internal.Xml.XPath.LogicalExpr.cmpRtfBoolO(), MS.Internal.Xml.XPath.LogicalExpr.cmpRtfNumber(), MS.Internal.Xml.XPath.LogicalExpr.cmpRtfQueryO(), MS.Internal.Xml.XPath.LogicalExpr.cmpRtfRtfO(), MS.Internal.Xml.XPath.LogicalExpr.cmpRtfStringO(), MS.Internal.Xml.XPath.LogicalExpr.cmpStringNumber(), and MS.Internal.Xml.XPath.LogicalExpr.cmpStringStringO().