Terraria: MS.Internal.Xml.XPath.NumberFunctions.Sum
Sum()
double MS.Internal.Xml.XPath.NumberFunctions.Sum (XPathNodeIterator nodeIterator) inline private
Definition at line 94 of file NumberFunctions.cs.
    {
        double num = 0.0;
        _arg.Evaluate(nodeIterator);
        XPathNavigator xPathNavigator;
        while ((xPathNavigator = _arg.Advance()) != null)
        {
            num += Number(xPathNavigator.Value);
        }
        return num;
    }
References MS.Internal.Xml.XPath.NumberFunctions._arg, MS.Internal.Xml.XPath.Query.Advance(), System.Xml.Dictionary, MS.Internal.Xml.XPath.Query.Evaluate(), and System.Number.
Referenced by MS.Internal.Xml.XPath.NumberFunctions.Evaluate().