Terraria: MS.Internal.Xml.XPath.NumberFunctions.Ceiling
Ceiling()
double MS.Internal.Xml.XPath.NumberFunctions.Ceiling (XPathNodeIterator nodeIterator) inline private
Definition at line 111 of file NumberFunctions.cs.
    {
        return Math.Ceiling((double)_arg.Evaluate(nodeIterator));
    }
References MS.Internal.Xml.XPath.NumberFunctions._arg, System.Math.Ceiling(), System.Xml.Dictionary, and MS.Internal.Xml.XPath.Query.Evaluate().
Referenced by MS.Internal.Xml.XPath.NumberFunctions.Evaluate().