Terraria: System.Xml.Xsl.Qil.QilName.ToString
ToString()
override string System.Xml.Xsl.Qil.QilName.ToString () inline
Definition at line 114 of file QilName.cs.
    {
        if (_prefix.Length == 0)
        {
            if (_uri.Length == 0)
            {
                return _local;
            }
            return "{" + _uri + "}" + _local;
        }
        return "{" + _uri + "}" + _prefix + ":" + _local;
    }
References System.Xml.Xsl.Qil.QilName._local, System.Xml.Xsl.Qil.QilName._prefix, and System.Xml.Xsl.Qil.QilName._uri.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate(), System.Xml.Xsl.Xslt.QilGenerator.CompileFormatNumber(), System.Xml.Xsl.Xslt.QilGenerator.CompileInitializationCode(), and System.Xml.Xsl.Xslt.QilGenerator.GetNsVar().