Terraria: GameTipsDisplay.AddNewTip
AddNewTip()
void GameTipsDisplay.AddNewTip (double currentTime) inline private
     {
         string textKey = "UI.Back";
         List<LocalizedText> list = new List<LocalizedText>();
         list.AddRange(_tipsDefault);
         if (PlayerInput.UsingGamepad)
         {
             list.AddRange(_tipsGamepad);
         }
         else
         {
             list.AddRange(_tipsKeyboard);
         }
         if (_lastTip != null)
         {
             list.Remove(_lastTip);
         }
         string key = (_lastTip = ((list.Count != 0) ? list[Main.rand.Next(list.Count)] : LocalizedText.Empty)).Key;
         if (Language.Exists(key))
         {
             textKey = key;
         }
         _currentTips.Add(new GameTip(textKey, currentTime));
     }
References _currentTips, _lastTip, _tipsDefault, _tipsGamepad, _tipsKeyboard, LocalizedText.Empty, Language.Exists(), UnifiedRandom.Next(), Main.rand, and PlayerInput.UsingGamepad.
Referenced by Update().