Terraria: System.Text.EncoderNLS.TryDrainLeftoverDataForGetBytes
TryDrainLeftoverDataForGetBytes()
bool System.Text.EncoderNLS.TryDrainLeftoverDataForGetBytes (ReadOnlySpan< char > chars, Span< byte > bytes, out int charsConsumed, out int bytesWritten) inline package inherited
Definition at line 229 of file EncoderNLS.cs.
    {
        charsConsumed = 0;
        bytesWritten = 0;
        if (_charLeftOver != 0)
        {
            char c = '\0';
            if (chars.IsEmpty)
            {
                if (!MustFlush)
                {
                    charsConsumed = 0;
                    bytesWritten = 0;
                    return true;
                }
            }
            else
            {
                c = chars[0];
            }
            char charLeftOver = _charLeftOver;
            _charLeftOver = '\0';
            if (Rune.TryCreate(charLeftOver, c, out var result))
            {
                charsConsumed = 1;
                switch (_encoding.EncodeRune(result, bytes, out bytesWritten))
                {
                case OperationStatus.Done:
                    return true;
                case OperationStatus.DestinationTooSmall:
                    _encoding.ThrowBytesOverflow(this, nothingEncoded: true);
                    break;
                case OperationStatus.InvalidData:
                    base.FallbackBuffer.Fallback(charLeftOver, c, -1);
                    break;
                }
            }
            else
            {
                base.FallbackBuffer.Fallback(charLeftOver, -1);
            }
        }
        if (_fallbackBuffer != null && _fallbackBuffer.Remaining > 0)
        {
            return _fallbackBuffer.TryDrainRemainingDataForGetBytes(bytes, out bytesWritten);
        }
        return true;
    }
References System.Text.EncoderNLS._charLeftOver, System.Text.EncoderNLS._encoding, System.Text.Encoder._fallbackBuffer, System.bytes, System.Text.EncoderNLS.charLeftOver, System.chars, System.Text.Encoding.EncodeRune(), System.Text.EncoderNLS.MustFlush, System.Text.EncoderFallbackBuffer.Remaining, System.Text.Encoding.ThrowBytesOverflow(), System.Text.Rune.TryCreate(), and System.Text.EncoderFallbackBuffer.TryDrainRemainingDataForGetBytes().
Referenced by System.Text.Encoding.GetBytesWithFallback().