Terraria: System.Data.DataRow.CheckForLoops
CheckForLoops()
void System.Data.DataRow.CheckForLoops (DataRelation rel) inline package
Definition at line 423 of file DataRow.cs.
    {
        if (_table._fInLoadDiffgram || (_table.DataSet != null && _table.DataSet._fInLoadDiffgram))
        {
            return;
        }
        int count = _table.Rows.Count;
        int num = 0;
        for (DataRow parentRow = GetParentRow(rel); parentRow != null; parentRow = parentRow.GetParentRow(rel))
        {
            if (parentRow == this || num > count)
            {
                throw ExceptionBuilder.NestedCircular(_table.TableName);
            }
            num++;
        }
    }
References System.Data.DataSet._fInLoadDiffgram, System.Data.DataTable._fInLoadDiffgram, System.Data.DataRow._table, System.Data.DataRowCollection.Count, System.count, System.Data.DataTable.DataSet, System.Xml.Dictionary, System.Data.DataRow.GetParentRow(), System.Data.ExceptionBuilder.NestedCircular(), System.Data.DataTable.Rows, and System.Data.DataTable.TableName.
Referenced by System.Data.DataRow.GetNestedParentCount(), System.Data.DataRow.GetNestedParentRow(), and System.Data.DataRow.SetNestedParentRow().