Terraria: System.Data.DataRow.SetParentRow
SetParentRow() [2/2]
void System.Data.DataRow.SetParentRow (DataRow? parentRow, DataRelation? relation) inline
Definition at line 1126 of file DataRow.cs.
    {
        if (relation == null)
        {
            SetParentRow(parentRow);
            return;
        }
        if (parentRow == null)
        {
            SetParentRowToDBNull(relation);
            return;
        }
        if (_table.DataSet != parentRow._table.DataSet)
        {
            throw ExceptionBuilder.ParentRowNotInTheDataSet();
        }
        if (relation.ChildKey.Table != _table)
        {
            throw ExceptionBuilder.SetParentRowTableMismatch(relation.ChildKey.Table.TableName, _table.TableName);
        }
        if (relation.ParentKey.Table != parentRow._table)
        {
            throw ExceptionBuilder.SetParentRowTableMismatch(relation.ParentKey.Table.TableName, parentRow._table.TableName);
        }
        object[] keyValues = parentRow.GetKeyValues(relation.ParentKey);
        SetKeyValues(relation.ChildKey, keyValues);
    }
References System.Data.DataSet.DataSet(), System.Data.DataRow._table, System.Data.DataTable.DataSet, System.Xml.Dictionary, System.Data.ExceptionBuilder.ParentRowNotInTheDataSet(), System.Data.DataRow.SetKeyValues(), System.Data.DataRow.SetParentRow(), System.Data.ExceptionBuilder.SetParentRowTableMismatch(), System.Data.DataRow.SetParentRowToDBNull(), and System.Data.DataTable.TableName.