Terraria: System.Data.DataRow.AcceptChanges
AcceptChanges()
void System.Data.DataRow.AcceptChanges () inline
Definition at line 464 of file DataRow.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataRow.AcceptChanges|API> {0}", _objectID);
        try
        {
            EndEdit();
            if (RowState != DataRowState.Detached && RowState != DataRowState.Deleted && _columns.ColumnsImplementingIChangeTrackingCount > 0)
            {
                DataColumn[] columnsImplementingIChangeTracking = _columns.ColumnsImplementingIChangeTracking;
                foreach (DataColumn column in columnsImplementingIChangeTracking)
                {
                    object obj = this[column];
                    if (DBNull.Value != obj)
                    {
                        IChangeTracking changeTracking = (IChangeTracking)obj;
                        if (changeTracking.IsChanged)
{
                            changeTracking.AcceptChanges();
                        }
                    }
                }
            }
            _table.CommitRow(this);
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataRow._columns, System.Data.DataRow._objectID, System.Data.DataRow._table, System.ComponentModel.IChangeTracking.AcceptChanges(), System.Data.DataColumnCollection.ColumnsImplementingIChangeTracking, System.Data.DataColumnCollection.ColumnsImplementingIChangeTrackingCount, System.Data.DataTable.CommitRow(), System.Xml.Dictionary, System.Data.DataRow.EndEdit(), System.Data.DataCommonEventSource.Log, System.obj, System.Data.DataRow.RowState, and System.DBNull.Value.
Referenced by System.Data.ForeignKeyConstraint.CascadeCommit(), System.Data.DataRowCollection.Remove(), and System.Data.Common.DbCommandBuilder.RowUpdatingHandlerBuilder().