Terraria: System.Data.DataRow.GetParentRow
GetParentRow() [2/4]
DataRow? System.Data.DataRow.GetParentRow (DataRelation? relation, DataRowVersion version) inline
Definition at line 729 of file DataRow.cs.
    {
        if (relation == null)
        {
            return null;
        }
        if (relation.DataSet != _table.DataSet)
        {
            throw ExceptionBuilder.RelationForeignRow();
        }
        if (relation.ChildKey.Table != _table)
        {
            throw ExceptionBuilder.GetParentRowTableMismatch(relation.ChildTable.TableName, _table.TableName);
        }
        return DataRelation.GetParentRow(relation.ParentKey, relation.ChildKey, this, version);
    }
References System.Data.DataRow._table, System.Data.DataTable.DataSet, System.Xml.Dictionary, System.Data.DataRelation.GetParentRow(), System.Data.ExceptionBuilder.GetParentRowTableMismatch(), System.Data.ExceptionBuilder.RelationForeignRow(), and System.Data.DataTable.TableName.