Terraria: System.Data.DataRow.RejectChanges
RejectChanges()
void System.Data.DataRow.RejectChanges () inline
Definition at line 1012 of file DataRow.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataRow.RejectChanges|API> {0}", _objectID);
        try
        {
            if (RowState != DataRowState.Detached)
            {
                if (_columns.ColumnsImplementingIChangeTrackingCount != _columns.ColumnsImplementingIRevertibleChangeTrackingCount)
                {
                    DataColumn[] columnsImplementingIChangeTracking = _columns.ColumnsImplementingIChangeTracking;
                    foreach (DataColumn dataColumn in columnsImplementingIChangeTracking)
                    {
                        if (!dataColumn.ImplementsIRevertibleChangeTracking)
{
                            object obj = null;
                            obj = ((RowState == DataRowState.Deleted) ? this[dataColumn, DataRowVersion.Original] : this[dataColumn]);
                            if (DBNull.Value != obj && ((IChangeTracking)obj).IsChanged)
{
                                throw ExceptionBuilder.UDTImplementsIChangeTrackingButnotIRevertible(dataColumn.DataType.AssemblyQualifiedName);
                            }
                        }
                    }
                }
                DataColumn[] columnsImplementingIChangeTracking2 = _columns.ColumnsImplementingIChangeTracking;
                foreach (DataColumn column in columnsImplementingIChangeTracking2)
                {
                    object obj2 = null;
                    obj2 = ((RowState == DataRowState.Deleted) ? this[column, DataRowVersion.Original] : this[column]);
                    if (DBNull.Value != obj2)
                    {
                        IChangeTracking changeTracking = (IChangeTracking)obj2;
                        if (changeTracking.IsChanged)
{
                            ((IRevertibleChangeTracking)obj2).RejectChanges();
                        }
                    }
                }
            }
            _table.RollbackRow(this);
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataRow._columns, System.Data.DataRow._objectID, System.Data.DataRow._table, System.Data.DataColumnCollection.ColumnsImplementingIChangeTracking, System.Data.DataColumnCollection.ColumnsImplementingIChangeTrackingCount, System.Data.DataColumnCollection.ColumnsImplementingIRevertibleChangeTrackingCount, System.Xml.Dictionary, System.Data.DataCommonEventSource.Log, System.obj, System.Data.DataTable.RollbackRow(), System.Data.DataRow.RowState, System.Data.ExceptionBuilder.UDTImplementsIChangeTrackingButnotIRevertible(), and System.DBNull.Value.
Referenced by System.Data.ForeignKeyConstraint.CascadeRollback().