Terraria: System.Data.DataRow.SetColumnError
SetColumnError() [1/3]
void System.Data.DataRow.SetColumnError (DataColumn column, string? error) inline
Definition at line 603 of file DataRow.cs.
    {
        CheckColumn(column);
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataRow.SetColumnError|API> {0}, column={1}, error='{2}'", _objectID, column.ObjectID, error);
        try
        {
            if (_error == null)
            {
                _error = new DataError();
            }
            if (GetColumnError(column) != error)
            {
                _error.SetColumnError(column, error);
                RowErrorChanged();
            }
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataRow._error, System.Data.DataRow._objectID, System.Data.DataRow.CheckColumn(), System.Xml.Dictionary, System.Data.DataRow.GetColumnError(), System.Data.DataCommonEventSource.Log, System.Data.DataRow.RowErrorChanged(), and System.Data.DataError.SetColumnError().