Terraria: System.Data.DataRow.GetKeyValues
GetKeyValues() [1/2]
object[] System.Data.DataRow.GetKeyValues (DataKey key) inline package
Definition at line 811 of file DataRow.cs.
    {
        int defaultRecord = GetDefaultRecord();
        return key.GetKeyValues(defaultRecord);
    }
References System.Xml.Dictionary, System.Data.DataRow.GetDefaultRecord(), and System.key.
Referenced by System.Data.ForeignKeyConstraint.CascadeCommit(), System.Data.ForeignKeyConstraint.CascadeDelete(), System.Data.ForeignKeyConstraint.CascadeRollback(), System.Data.ForeignKeyConstraint.CascadeUpdate(), System.Data.ForeignKeyConstraint.CheckConstraint(), System.Data.DataRow.GetColumnValues(), and System.Data.RelatedView.Invoke().