Terraria: System.Data.DataRow.GetParentRows
GetParentRows() [2/4]
DataRow[] System.Data.DataRow.GetParentRows (DataRelation? relation, DataRowVersion version) inline
Definition at line 783 of file DataRow.cs.
    {
        if (relation == null)
        {
            return _table.NewRowArray(0);
        }
        if (relation.DataSet != _table.DataSet)
        {
            throw ExceptionBuilder.RowNotInTheDataSet();
        }
        if (relation.ChildKey.Table != _table)
        {
            throw ExceptionBuilder.GetParentRowTableMismatch(relation.ChildTable.TableName, _table.TableName);
        }
        return DataRelation.GetParentRows(relation.ParentKey, relation.ChildKey, this, version);
    }
References System.Data.DataRow._table, System.Data.DataTable.DataSet, System.Xml.Dictionary, System.Data.DataRelation.GetParentRows(), System.Data.ExceptionBuilder.GetParentRowTableMismatch(), System.Data.DataTable.NewRowArray(), System.Data.ExceptionBuilder.RowNotInTheDataSet(), and System.Data.DataTable.TableName.