Terraria: System.Data.DataRow.SetNestedParentRow
SetNestedParentRow()
void System.Data.DataRow.SetNestedParentRow (DataRow parentRow, bool setNonNested) inline package
Definition at line 1092 of file DataRow.cs.
    {
        if (parentRow == null)
        {
            SetParentRowToDBNull();
            return;
        }
        foreach (DataRelation parentRelation in _table.ParentRelations)
        {
            if (!(parentRelation.Nested || setNonNested) || parentRelation.ParentKey.Table != parentRow._table)
            {
                continue;
            }
            object[] keyValues = parentRow.GetKeyValues(parentRelation.ParentKey);
            SetKeyValues(parentRelation.ChildKey, keyValues);
            if (parentRelation.Nested)
            {
                if (parentRow._table == _table)
                {
                    CheckForLoops(parentRelation);
                }
                else
                {
                    GetParentRow(parentRelation);
                }
            }
        }
    }
References System.Data.DataRow._table, System.Data.DataRow.CheckForLoops(), System.Xml.Dictionary, System.Data.DataRow.GetParentRow(), System.Data.DataTable.ParentRelations, System.Data.DataRow.SetKeyValues(), and System.Data.DataRow.SetParentRowToDBNull().
Referenced by System.Data.DataRow.SetParentRow().