Terraria: System.Data.DataRow.CancelEdit
CancelEdit()
void System.Data.DataRow.CancelEdit () inline
Definition at line 524 of file DataRow.cs.
    {
        if (_inChangingEvent)
        {
            throw ExceptionBuilder.CancelEditInRowChanging();
        }
        _table.FreeRecord(ref _tempRecord);
        ResetLastChangedColumn();
    }
References System.Data.DataRow._inChangingEvent, System.Data.DataRow._table, System.Data.DataRow._tempRecord, System.Data.ExceptionBuilder.CancelEditInRowChanging(), System.Xml.Dictionary, System.Data.DataTable.FreeRecord(), and System.Data.DataRow.ResetLastChangedColumn().
Referenced by System.Data.DataRowView.CancelEdit().