Terraria: System.Data.DataRow.CheckColumn
CheckColumn()
void System.Data.DataRow.CheckColumn (DataColumn column) inline private
Definition at line 534 of file DataRow.cs.
    {
        if (column == null)
        {
            throw ExceptionBuilder.ArgumentNull("column");
        }
        if (column.Table != _table)
        {
            throw ExceptionBuilder.ColumnNotInTheTable(column.ColumnName, _table.TableName);
        }
    }
References System.Data.DataRow._table, System.Data.ExceptionBuilder.ArgumentNull(), System.Data.ExceptionBuilder.ColumnNotInTheTable(), System.Xml.Dictionary, and System.Data.DataTable.TableName.
Referenced by System.Data.DataRow.GetColumnError(), System.Data.DataRow.HaveValuesChanged(), System.Data.DataRow.IsNull(), System.Data.DataRow.IsNull(), and System.Data.DataRow.SetColumnError().