Terraria: System.Data.DataRow.GetNestedParentRow
GetNestedParentRow()
DataRow System.Data.DataRow.GetNestedParentRow (DataRowVersion version) inline package
Definition at line 746 of file DataRow.cs.
    {
        DataRelation[] nestedParentRelations = _table.NestedParentRelations;
        DataRelation[] array = nestedParentRelations;
        foreach (DataRelation dataRelation in array)
        {
            if (dataRelation != null)
            {
                if (dataRelation.ParentTable == _table)
                {
                    CheckForLoops(dataRelation);
                }
                DataRow parentRow = GetParentRow(dataRelation, version);
                if (parentRow != null)
                {
                    return parentRow;
                }
            }
        }
        return null;
    }
References System.Data.DataRow._table, System.array, System.Data.DataRow.CheckForLoops(), System.Xml.Dictionary, System.Data.DataRow.GetParentRow(), and System.Data.DataTable.NestedParentRelations.
Referenced by System.Data.NewDiffgramGen.GenerateRow().