Terraria: System.Data.DataRow.GetRecordFromVersion
GetRecordFromVersion()
int System.Data.DataRow.GetRecordFromVersion (DataRowVersion version) inline package
Definition at line 863 of file DataRow.cs.
    {
        return version switch
        {
            DataRowVersion.Original => GetOriginalRecordNo(),
            DataRowVersion.Current => GetCurrentRecordNo(),
            DataRowVersion.Proposed => GetProposedRecordNo(),
            DataRowVersion.Default => GetDefaultRecord(),
            _ => throw ExceptionBuilder.InvalidRowVersion(),
        };
    }
References System.Xml.Dictionary, System.Data.DataRow.GetCurrentRecordNo(), System.Data.DataRow.GetDefaultRecord(), System.Data.DataRow.GetOriginalRecordNo(), System.Data.DataRow.GetProposedRecordNo(), and System.Data.ExceptionBuilder.InvalidRowVersion().
Referenced by System.Data.DataRow.GetKeyValues(), System.Data.DataRowView.GetRecord(), System.Data.DataRow.HasKeyChanged(), and System.Data.DataRow.IsNull().