Terraria: System.Data.DataRow.BeginEditInternal
BeginEditInternal()
bool System.Data.DataRow.BeginEditInternal () inline private
Definition at line 500 of file DataRow.cs.
    {
        if (_inChangingEvent)
        {
            throw ExceptionBuilder.BeginEditInRowChanging();
        }
        if (_tempRecord != -1)
        {
            if (_tempRecord < _table._recordManager.LastFreeRecord)
            {
                return false;
            }
            _tempRecord = -1;
        }
        if (_oldRecord != -1 && _newRecord == -1)
        {
            throw ExceptionBuilder.DeletedRowInaccessible();
        }
        ResetLastChangedColumn();
        _tempRecord = _table.NewRecord(_newRecord);
        return true;
    }
References System.Data.DataRow._inChangingEvent, System.Data.DataRow._newRecord, System.Data.DataRow._oldRecord, System.Data.DataTable._recordManager, System.Data.DataRow._table, System.Data.DataRow._tempRecord, System.Data.ExceptionBuilder.BeginEditInRowChanging(), System.Data.ExceptionBuilder.DeletedRowInaccessible(), System.Data.RecordManager.LastFreeRecord, System.Data.DataTable.NewRecord(), and System.Data.DataRow.ResetLastChangedColumn().
Referenced by System.Data.DataRow.BeginEdit(), and System.Data.DataRow.SetKeyValues().