Terraria: System.Data.XmlDataTreeWriter.Save
Save()
void System.Data.XmlDataTreeWriter.Save (XmlWriter xw, bool writeSchema) inline package
Definition at line 173 of file XmlDataTreeWriter.cs.
    {
        _xmlw = DataTextWriter.CreateWriter(xw);
        int num = _topLevelTables.Length;
        bool flag = true;
        string prefix = ((_ds == null) ? ((_dt.Namespace.Length == 0) ? "" : _dt.Prefix) : ((_ds.Namespace.Length == 0) ? "" : _ds.Prefix));
        if (!writeSchema && _ds != null && _ds._fTopLevelTable && num == 1 && _ds.TopLevelTables()[0].Rows.Count == 1)
        {
            flag = false;
        }
        if (flag)
        {
            if (_ds == null)
            {
                _xmlw.WriteStartElement(prefix, "DocumentElement", _dt.Namespace);
            }
            else if (_ds.DataSetName == null || _ds.DataSetName.Length == 0)
            {
                _xmlw.WriteStartElement(prefix, "DocumentElement", _ds.Namespace);
            }
            else
            {
                _xmlw.WriteStartElement(prefix, XmlConvert.EncodeLocalName(_ds.DataSetName), _ds.Namespace);
            }
            for (int i = 0; i < _dTables.Count; i++)
            {
                if (((DataTable)_dTables[i])._xmlText != null)
                {
                    _xmlw.WriteAttributeString("xmlns", "xsi", "http://www.w3.org/2000/xmlns/", "http://www.w3.org/2001/XMLSchema-instance");
                    break;
                }
            }
            if (writeSchema)
            {
                if (!_fFromTable)
                {
                    new XmlTreeGen(SchemaFormat.Public).Save(_ds, _xmlw);
                }
                else
                {
                    new XmlTreeGen(SchemaFormat.Public).Save(null, _dt, _xmlw, _writeHierarchy);
                }
            }
        }
        for (int j = 0; j < _dTables.Count; j++)
        {
            foreach (DataRow row in ((DataTable)_dTables[j]).Rows)
            {
                if (row.RowState != DataRowState.Deleted)
                {
                    int nestedParentCount = row.GetNestedParentCount();
                    if (nestedParentCount == 0)
                    {
                        XmlDataRowWriter(row, ((DataTable)_dTables[j]).EncodedTableName);
                    }
                    else if (nestedParentCount > 1)
                    {
                        DataTable dataTable = (DataTable)_dTables[j];
                        throw ExceptionBuilder.MultipleParentRows((dataTable.Namespace.Length == 0) ? dataTable.TableName : (dataTable.Namespace + dataTable.TableName));
                    }
                }
            }
        }
        if (flag)
        {
            _xmlw.WriteEndElement();
        }
        _xmlw.Flush();
    }
References System.Data.XmlDataTreeWriter._ds, System.Data.XmlDataTreeWriter._dt, System.Data.XmlDataTreeWriter._dTables, System.Data.XmlDataTreeWriter._fFromTable, System.Data.DataSet._fTopLevelTable, System.Data.XmlDataTreeWriter._topLevelTables, System.Data.XmlDataTreeWriter._writeHierarchy, System.Data.XmlDataTreeWriter._xmlw, System.Data.DataRowCollection.Count, System.Collections.ArrayList.Count, System.Data.DataTextWriter.CreateWriter(), System.Data.DataSet.DataSetName, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Xml.XmlWriter.Flush(), System.Data.ExceptionBuilder.MultipleParentRows(), System.Data.DataSet.Namespace, System.Data.DataTable.Namespace, System.Data.DataSet.Prefix, System.Data.DataTable.Prefix, System.prefix, System.Data.DataTable.Rows, System.Data.XmlTreeGen.Save(), System.Data.DataSet.TopLevelTables(), System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteEndElement(), System.Xml.XmlWriter.WriteStartElement(), and System.Data.XmlDataTreeWriter.XmlDataRowWriter().
Referenced by System.Data.DataSet.GetXml(), System.Data.DataSet.WriteXml(), and System.Data.DataSet.WriteXml().