Terraria: System.Data.XmlDataTreeWriter.XmlDataTreeWriter
XmlDataTreeWriter() [2/2]
System.Data.XmlDataTreeWriter.XmlDataTreeWriter (DataTable dt, bool writeHierarchy) inline package
Definition at line 40 of file XmlDataTreeWriter.cs.
    {
        _dt = dt;
        _fFromTable = true;
        if (dt.DataSet == null)
        {
            _dTables.Add(dt);
            _topLevelTables = new DataTable[1] { dt };
            return;
        }
        _ds = dt.DataSet;
        _dTables.Add(dt);
        if (writeHierarchy)
        {
            _writeHierarchy = true;
            CreateTablesHierarchy(dt);
            _topLevelTables = CreateToplevelTables();
        }
        else
        {
            _topLevelTables = new DataTable[1] { dt };
        }
    }
References System.Data.DataSet.DataSet(), System.Data.XmlDataTreeWriter._ds, System.Data.XmlDataTreeWriter._dt, System.Data.XmlDataTreeWriter._dTables, System.Data.XmlDataTreeWriter._fFromTable, System.Data.XmlDataTreeWriter._topLevelTables, System.Data.XmlDataTreeWriter._writeHierarchy, System.Collections.ArrayList.Add(), System.Data.XmlDataTreeWriter.CreateTablesHierarchy(), System.Data.XmlDataTreeWriter.CreateToplevelTables(), and System.Xml.Dictionary.