Terraria: System.Data.XmlDataTreeWriter.SaveDiffgramData
SaveDiffgramData()
void System.Data.XmlDataTreeWriter.SaveDiffgramData (XmlWriter xw, Hashtable rowsOrder) inline package
Definition at line 134 of file XmlDataTreeWriter.cs.
    {
        _xmlw = DataTextWriter.CreateWriter(xw);
        _isDiffgram = true;
        _rowsOrder = rowsOrder;
        string prefix = ((_ds == null) ? ((_dt.Namespace.Length == 0) ? "" : _dt.Prefix) : ((_ds.Namespace.Length == 0) ? "" : _ds.Prefix));
        if (_ds == null || _ds.DataSetName == null || _ds.DataSetName.Length == 0)
        {
            _xmlw.WriteStartElement(prefix, "DocumentElement", (_dt.Namespace == null) ? "" : _dt.Namespace);
        }
        else
        {
            _xmlw.WriteStartElement(prefix, XmlConvert.EncodeLocalName(_ds.DataSetName), _ds.Namespace);
        }
        for (int i = 0; i < _dTables.Count; i++)
        {
            DataTable dataTable = (DataTable)_dTables[i];
            foreach (DataRow row in dataTable.Rows)
            {
                if (row.RowState != DataRowState.Deleted)
                {
                    int nestedParentCount = row.GetNestedParentCount();
                    if (nestedParentCount == 0)
                    {
                        DataTable dataTable2 = (DataTable)_dTables[i];
                        XmlDataRowWriter(row, dataTable2.EncodedTableName);
                    }
                    else if (nestedParentCount > 1)
                    {
                        throw ExceptionBuilder.MultipleParentRows((dataTable.Namespace.Length == 0) ? dataTable.TableName : (dataTable.Namespace + dataTable.TableName));
                    }
                }
            }
        }
        _xmlw.WriteEndElement();
        _xmlw.Flush();
    }
References System.Data.XmlDataTreeWriter._ds, System.Data.XmlDataTreeWriter._dt, System.Data.XmlDataTreeWriter._dTables, System.Data.XmlDataTreeWriter._isDiffgram, System.Data.XmlDataTreeWriter._rowsOrder, System.Data.XmlDataTreeWriter._xmlw, System.Collections.ArrayList.Count, System.Data.DataTextWriter.CreateWriter(), System.Data.DataSet.DataSetName, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Xml.XmlWriter.Flush(), System.Data.ExceptionBuilder.MultipleParentRows(), System.Data.DataSet.Namespace, System.Data.DataTable.Namespace, System.Data.DataSet.Prefix, System.Data.DataTable.Prefix, System.prefix, System.Xml.XmlWriter.WriteEndElement(), System.Xml.XmlWriter.WriteStartElement(), and System.Data.XmlDataTreeWriter.XmlDataRowWriter().
Referenced by System.Data.NewDiffgramGen.Save().