Terraria: System.Data.XmlDataTreeWriter._dTables
_dTables
readonly ArrayList System.Data.XmlDataTreeWriter._dTables = new ArrayList() private
Definition at line 18 of file XmlDataTreeWriter.cs.
Referenced by System.Data.XmlDataTreeWriter.XmlDataTreeWriter(), System.Data.XmlDataTreeWriter.XmlDataTreeWriter(), System.Data.XmlDataTreeWriter.CreateTablesHierarchy(), System.Data.XmlDataTreeWriter.CreateToplevelTables(), System.Data.XmlDataTreeWriter.Save(), and System.Data.XmlDataTreeWriter.SaveDiffgramData().