Terraria: System.Data.XmlDataTreeWriter.XmlDataRowWriter
XmlDataRowWriter()
void System.Data.XmlDataTreeWriter.XmlDataRowWriter (DataRow row, string encodedTableName) inline package
Definition at line 257 of file XmlDataTreeWriter.cs.
    {
        string prefix = ((row.Table.Namespace.Length == 0) ? "" : row.Table.Prefix);
        _xmlw.WriteStartElement(prefix, encodedTableName, row.Table.Namespace);
        if (_isDiffgram)
        {
            _xmlw.WriteAttributeString("diffgr", "id", "urn:schemas-microsoft-com:xml-diffgram-v1", row.Table.TableName + row.rowID.ToString(CultureInfo.InvariantCulture));
            _xmlw.WriteAttributeString("msdata", "rowOrder", "urn:schemas-microsoft-com:xml-msdata", _rowsOrder[row].ToString());
            if (row.RowState == DataRowState.Added)
            {
                _xmlw.WriteAttributeString("diffgr", "hasChanges", "urn:schemas-microsoft-com:xml-diffgram-v1", "inserted");
            }
            if (row.RowState == DataRowState.Modified)
            {
                _xmlw.WriteAttributeString("diffgr", "hasChanges", "urn:schemas-microsoft-com:xml-diffgram-v1", "modified");
            }
            if (RowHasErrors(row))
            {
                _xmlw.WriteAttributeString("diffgr", "hasErrors", "urn:schemas-microsoft-com:xml-diffgram-v1", "true");
            }
        }
        foreach (DataColumn column in row.Table.Columns)
        {
            if (column._columnMapping == MappingType.Attribute)
            {
                object obj = row[column];
                string prefix2 = ((column.Namespace.Length == 0) ? "" : column.Prefix);
                if (obj != DBNull.Value && (!column.ImplementsINullable || !DataStorage.IsObjectSqlNull(obj)))
                {
                    XmlTreeGen.ValidateColumnMapping(column.DataType);
                    _xmlw.WriteAttributeString(prefix2, column.EncodedColumnName, column.Namespace, column.ConvertObjectToXml(obj));
                }
            }
            if (_isDiffgram && column._columnMapping == MappingType.Hidden)
            {
                object obj = row[column];
                if (obj != DBNull.Value && (!column.ImplementsINullable || !DataStorage.IsObjectSqlNull(obj)))
                {
                    XmlTreeGen.ValidateColumnMapping(column.DataType);
                    _xmlw.WriteAttributeString("msdata", "hidden" + column.EncodedColumnName, "urn:schemas-microsoft-com:xml-msdata", column.ConvertObjectToXml(obj));
                }
            }
        }
        foreach (DataColumn column2 in row.Table.Columns)
        {
            if (column2._columnMapping == MappingType.Hidden)
            {
                continue;
            }
            object obj = row[column2];
            string prefix3 = ((column2.Namespace.Length == 0) ? "" : column2.Prefix);
            bool flag = true;
            if ((obj == DBNull.Value || (column2.ImplementsINullable && DataStorage.IsObjectSqlNull(obj))) && column2.ColumnMapping == MappingType.SimpleContent)
            {
                _xmlw.WriteAttributeString("xsi", "nil", "http://www.w3.org/2001/XMLSchema-instance", "true");
            }
            if (obj == DBNull.Value || (column2.ImplementsINullable && DataStorage.IsObjectSqlNull(obj)) || column2._columnMapping == MappingType.Attribute)
            {
                continue;
            }
            if (column2._columnMapping != MappingType.SimpleContent && (!column2.IsCustomType || !column2.IsValueCustomTypeInstance(obj) || typeof(IXmlSerializable).IsAssignableFrom(obj.GetType())))
            {
                _xmlw.WriteStartElement(prefix3, column2.EncodedColumnName, column2.Namespace);
                flag = false;
            }
            Type type = obj.GetType();
            if (!column2.IsCustomType)
            {
                if ((type == typeof(char) || type == typeof(string)) && PreserveSpace(obj))
                {
                    _xmlw.WriteAttributeString("xml", "space", "http://www.w3.org/XML/1998/namespace", "preserve");
                }
                _xmlw.WriteString(column2.ConvertObjectToXml(obj));
            }
            else if (column2.IsValueCustomTypeInstance(obj))
            {
                if (!flag && type != column2.DataType)
                {
                    _xmlw.WriteAttributeString("msdata", "InstanceType", "urn:schemas-microsoft-com:xml-msdata", DataStorage.GetQualifiedName(type));
                }
                if (!flag)
                {
                    column2.ConvertObjectToXml(obj, _xmlw, null);
                }
                else
                {
                    if (obj.GetType() != column2.DataType)
                    {
                        throw ExceptionBuilder.PolymorphismNotSupported(type.AssemblyQualifiedName);
                    }
                    XmlRootAttribute xmlRootAttribute = new XmlRootAttribute(column2.EncodedColumnName);
                    xmlRootAttribute.Namespace = column2.Namespace;
                    column2.ConvertObjectToXml(obj, _xmlw, xmlRootAttribute);
                }
            }
            else
            {
                if (type == typeof(Type) || type == typeof(Guid) || type == typeof(char) || DataStorage.IsSqlType(type))
                {
                    _xmlw.WriteAttributeString("msdata", "InstanceType", "urn:schemas-microsoft-com:xml-msdata", type.FullName);
                }
                else if (obj is Type)
                {
                    _xmlw.WriteAttributeString("msdata", "InstanceType", "urn:schemas-microsoft-com:xml-msdata", "Type");
                }
                else
                {
                    string value = "xs:" + XmlTreeGen.XmlDataTypeName(type);
                    _xmlw.WriteAttributeString("xsi", "type", "http://www.w3.org/2001/XMLSchema-instance", value);
                    _xmlw.WriteAttributeString("xs", "xmlns", "http://www.w3.org/2001/XMLSchema", value);
                }
                if (!DataStorage.IsSqlType(type))
                {
                    _xmlw.WriteString(column2.ConvertObjectToXml(obj));
                }
                else
                {
                    column2.ConvertObjectToXml(obj, _xmlw, null);
                }
            }
            if (column2._columnMapping != MappingType.SimpleContent && !flag)
            {
                _xmlw.WriteEndElement();
            }
        }
        if (_ds != null)
        {
            foreach (DataRelation nestedChildRelation in GetNestedChildRelations(row))
            {
                DataRow[] childRows = row.GetChildRows(nestedChildRelation);
                foreach (DataRow row2 in childRows)
                {
                    XmlDataRowWriter(row2, nestedChildRelation.ChildTable.EncodedTableName);
                }
            }
        }
        _xmlw.WriteEndElement();
    }
References System.Data.XmlDataTreeWriter._ds, System.Data.XmlDataTreeWriter._isDiffgram, System.Data.XmlDataTreeWriter._rowsOrder, System.Data.XmlDataTreeWriter._xmlw, System.Data.DataTable.Columns, System.Xml.Dictionary, System.Data.DataRow.GetChildRows(), System.Data.XmlDataTreeWriter.GetNestedChildRelations(), System.Data.Common.DataStorage.GetQualifiedName(), System.Type.GetType(), System.Globalization.CultureInfo.InvariantCulture, System.Data.Common.DataStorage.IsObjectSqlNull(), System.Data.Common.DataStorage.IsSqlType(), System.obj, System.Data.ExceptionBuilder.PolymorphismNotSupported(), System.prefix, System.Data.XmlDataTreeWriter.PreserveSpace(), System.Data.XmlDataTreeWriter.RowHasErrors(), System.Data.DataColumn.Table, System.ToString, System.type, System.Data.XmlTreeGen.ValidateColumnMapping(), System.DBNull.Value, System.value, System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteEndElement(), System.Xml.XmlWriter.WriteStartElement(), System.Xml.XmlWriter.WriteString(), System.Data.XmlDataTreeWriter.XmlDataRowWriter(), and System.Data.XmlTreeGen.XmlDataTypeName().
Referenced by System.Data.XmlDataTreeWriter.Save(), System.Data.XmlDataTreeWriter.SaveDiffgramData(), and System.Data.XmlDataTreeWriter.XmlDataRowWriter().