Terraria: Microsoft.Xna.Framework.Graphics.IndexBuffer.CopyData< T >
CopyData< T >()
unsafe void Microsoft.Xna.Framework.Graphics.IndexBuffer.CopyData< T > (int offsetInBytes, T[] data, int startIndex, int elementCount, uint options, [MarshalAs(UnmanagedType.U1)] bool isSetting) inline protected
Type Constraints
T : struct
Definition at line 136 of file IndexBuffer.cs.
                                                                                                                                                                                 : struct
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        if (data != null && data.Length != 0)
        {
            int num = -2147467259;
            if ((options & 0x3010) == 0 && _parent.Indices == this)
            {
                throw GraphicsHelpers.GetExceptionFromResult(2147500036u);
            }
            if (!isSetting && (_usage & 8) == 8)
            {
                throw new NotSupportedException(FrameworkResources.WriteOnlyGetNotSupported);
            }
            Helpers.ValidateCopyParameters(data.Length, startIndex, elementCount);
            try
            {
                uint num2 = (uint)(System.Runtime.CompilerServices.Unsafe.SizeOf<T>() * elementCount);
                if ((uint)((int)num2 + offsetInBytes) > _bufferSize)
                {
                    throw new InvalidOperationException(FrameworkResources.ResourceDataMustBeCorrectSize);
                }
                if (_parent.IsDeviceLost)
                {
                    if (isSetting)
                    {
                        return;
                    }
                    fixed (T* ptr = &data[startIndex])
                    {
                        try
{
                            // IL initblk instruction
                            System.Runtime.CompilerServices.Unsafe.InitBlock(ptr, 0, num2);
                        }
                        catch
{
                            //try-fault
                            ptr = null;
                            throw;
                        }
                    }
                    return;
                }
                void* ptr2 = null;
                byte* ptr3 = (byte*)pBufferData;
                if (IsWriteOnly && _pool == 1)
                {
                    ptr3 = offsetInBytes + ptr3;
                }
                IDirect3DIndexBuffer9* ptr4 = pComPtr;
                num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, void**, uint, int>)(int)(*(uint*)(*(int*)ptr4 + 44)))((nint)ptr4, (uint)offsetInBytes, num2, &ptr2, options);
                if (num >= 0)
                {
                    fixed (T* ptr5 = &data[startIndex])
                    {
                        try
{
                            if (isSetting)
{
                                _003CModule_003E.memcpy_s(ptr2, _bufferSize - (uint)offsetInBytes, ptr5, num2);
                                if (IsWriteOnly && _pool == 1)
{
                                    _003CModule_003E.memcpy_s(ptr3, _bufferSize - (uint)offsetInBytes, ptr5, num2);
                                }
                            }
                            else
{
                                _003CModule_003E.memcpy_s(ptr5, num2, ptr2, num2);
                            }
                        }
                        catch
{
                            //try-fault
                            ptr5 = null;
                            throw;
                        }
                    }
                }
            }
            finally
            {
                if (num >= 0)
                {
                    IDirect3DIndexBuffer9* intPtr2 = pComPtr;
                    num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr2 + 48)))((nint)intPtr2);
                }
            }
            if (num < 0)
            {
                throw GraphicsHelpers.GetExceptionFromResult((uint)num);
            }
            if (isSetting && this is IDynamicGraphicsResource dynamicGraphicsResource)
            {
                dynamicGraphicsResource.SetContentLost(isContentLost: false);
            }
            return;
        }
        throw new ArgumentNullException("data", FrameworkResources.NullNotAllowed);
    }
References Microsoft.Xna.Framework.Graphics.IndexBuffer._bufferSize, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.IndexBuffer._pool, Microsoft.Xna.Framework.Graphics.IndexBuffer._usage, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), System.Runtime.CompilerServices.Unsafe.InitBlock(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.IsDeviceLost, Microsoft.Xna.Framework.Graphics.IndexBuffer.IsWriteOnly, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, System.options, Microsoft.Xna.Framework.Graphics.IndexBuffer.pBufferData, Microsoft.Xna.Framework.Graphics.IndexBuffer.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ResourceDataMustBeCorrectSize, System.startIndex, Microsoft.Xna.Framework.Helpers.ValidateCopyParameters(), and Microsoft.Xna.Framework.FrameworkResources.WriteOnlyGetNotSupported.