Terraria: Microsoft.Xna.Framework.Graphics.IndexBuffer.GetManagedObject
GetManagedObject()
static unsafe IndexBuffer Microsoft.Xna.Framework.Graphics.IndexBuffer.GetManagedObject (IDirect3DIndexBuffer9 * pInterface, GraphicsDevice pDevice, uint pool) inline static package
Definition at line 401 of file IndexBuffer.cs.
    {
        IndexBuffer indexBuffer = pDevice.Resources.GetCachedObject(pInterface) as IndexBuffer;
        if (indexBuffer != null)
        {
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)pInterface + 8)))((nint)pInterface);
            indexBuffer.isDisposed = false;
            GC.ReRegisterForFinalize(indexBuffer);
        }
        else
        {
            indexBuffer = new IndexBuffer(pInterface, pDevice);
            pDevice.Resources.AddTrackedObject(indexBuffer, pInterface, pool, 0uL, ref indexBuffer._internalHandle);
        }
        return indexBuffer;
    }
References Microsoft.Xna.Framework.Graphics.IndexBuffer.IndexBuffer(), Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.GetCachedObject(), System.GC.ReRegisterForFinalize(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources.