Terraria: Microsoft.Xna.Framework.Graphics.IndexBuffer.CreateBuffer
CreateBuffer()
unsafe void Microsoft.Xna.Framework.Graphics.IndexBuffer.CreateBuffer (uint indexCount, uint indexSize, uint usage, _D3DPOOL pool) inline protected
Definition at line 238 of file IndexBuffer.cs.
    {
        isDisposed = false;
        _D3DFORMAT d3DFORMAT;
        if (indexSize == 4)
        {
            d3DFORMAT = (_D3DFORMAT)102;
            if (!_parent._profileCapabilities.IndexElementSize32)
            {
                _parent._profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileNoIndexElementSize32);
            }
        }
        else
        {
            if (indexSize != 2)
            {
                throw new ArgumentException(FrameworkResources.IndexBuffersMustBeSizedCorrectly);
            }
            d3DFORMAT = (_D3DFORMAT)101;
        }
        uint num = (_bufferSize = indexCount * indexSize);
        int maxIndexBufferSize = _parent._profileCapabilities.MaxIndexBufferSize;
        if (num > (uint)maxIndexBufferSize)
        {
            _parent._profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileTooBig, typeof(IndexBuffer).Name, maxIndexBufferSize);
        }
        fixed (IDirect3DIndexBuffer9** ptr = &pComPtr)
        {
            int num2 = *(int*)_parent.pComPtr + 108;
            int num3 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, _D3DFORMAT, _D3DPOOL, IDirect3DIndexBuffer9**, void**, int>)(int)(*(uint*)num2))((nint)_parent.pComPtr, _bufferSize, _parent.GetBufferUsage(usage), d3DFORMAT, pool, ptr, null);
            if (num3 < 0)
            {
                throw GraphicsHelpers.GetExceptionFromResult((uint)num3);
            }
            _usage = usage;
            _indexCount = indexCount;
            _indexSize = indexSize;
            _pool = (uint)pool;
            if ((usage & 8) == 8 && pool == (_D3DPOOL)1 && (pBufferData = _003CModule_003E.new_005B_005D(_bufferSize)) == null)
            {
                throw new InsufficientMemoryException();
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.IndexBuffer._bufferSize, Microsoft.Xna.Framework.Graphics.IndexBuffer._indexCount, Microsoft.Xna.Framework.Graphics.IndexBuffer._indexSize, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.IndexBuffer._pool, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.IndexBuffer._usage, Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBufferUsage(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.FrameworkResources.IndexBuffersMustBeSizedCorrectly, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.IndexElementSize32, Microsoft.Xna.Framework.Graphics.GraphicsResource.isDisposed, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxIndexBufferSize, Microsoft.Xna.Framework.Graphics.IndexBuffer.pBufferData, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.IndexBuffer.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileNoIndexElementSize32, Microsoft.Xna.Framework.FrameworkResources.ProfileTooBig, and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException().
Referenced by Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.DynamicIndexBuffer(), Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.DynamicIndexBuffer(), Microsoft.Xna.Framework.Graphics.IndexBuffer.IndexBuffer(), and Microsoft.Xna.Framework.Graphics.IndexBuffer.IndexBuffer().