Terraria: Microsoft.Xna.Framework.Graphics.IndexBuffer.RecreateAndPopulateObject
RecreateAndPopulateObject() [1/2]
virtual unsafe int Microsoft.Xna.Framework.Graphics.IndexBuffer.RecreateAndPopulateObject () inline package virtual
Implements Microsoft.Xna.Framework.Graphics.IGraphicsResource.
Reimplemented in Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer, and Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.
Definition at line 333 of file IndexBuffer.cs.
    {
        if (pComPtr != null)
        {
            return -2147467259;
        }
        if (pBufferData == null && _bufferSize != 0)
        {
            return -2147467259;
        }
        fixed (IDirect3DIndexBuffer9** ptr2 = &pComPtr)
        {
            _D3DFORMAT d3DFORMAT = ((_indexSize == 4) ? ((_D3DFORMAT)102) : ((_D3DFORMAT)101));
            GraphicsDevice parent = _parent;
            IDirect3DDevice9* ptr = parent.pComPtr;
            GraphicsDevice graphicsDevice = parent;
            int num = *(int*)ptr + 108;
            int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, _D3DFORMAT, _D3DPOOL, IDirect3DIndexBuffer9**, void**, int>)(int)(*(uint*)num))((nint)ptr, _bufferSize, graphicsDevice.GetBufferUsage(_usage), d3DFORMAT, (_D3DPOOL)1, ptr2, null);
            if (num2 >= 0)
            {
                void* ptr3 = null;
                IDirect3DIndexBuffer9* ptr4 = pComPtr;
                num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, void**, uint, int>)(int)(*(uint*)(*(int*)ptr4 + 44)))((nint)ptr4, 0u, 0u, &ptr3, 0u);
                if (num2 >= 0)
                {
                    uint bufferSize = _bufferSize;
                    _003CModule_003E.memcpy_s(ptr3, bufferSize, pBufferData, bufferSize);
                    ptr4 = pComPtr;
                    IDirect3DIndexBuffer9* intPtr = ptr4;
                    num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr + 48)))((nint)intPtr);
                }
                if (!((_usage & 8) == 8))
                {
                    void* ptr5 = pBufferData;
                    if (ptr5 != null)
                    {
                        _003CModule_003E.delete_005B_005D(ptr5);
                        pBufferData = null;
                    }
                }
            }
            _parent.Resources.AddTrackedObject(this, pComPtr, 1u, _internalHandle, ref _internalHandle);
            return num2;
        }
    }
References Microsoft.Xna.Framework.Graphics.IndexBuffer._bufferSize, Microsoft.Xna.Framework.Graphics.IndexBuffer._indexSize, Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.IndexBuffer._usage, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBufferUsage(), Microsoft.Xna.Framework.Graphics.IndexBuffer.pBufferData, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.IndexBuffer.pComPtr, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources.
Referenced by Microsoft.Xna.Framework.Graphics.IndexBuffer.RecreateAndPopulateObject().