Terraria: AchievementManager.Save
Save() [2/2]
void AchievementManager.Save (string path, bool cloud) inline private
     {
         //IL_0047: Unknown result type (might be due to invalid IL or missing references)
         //IL_004e: Expected O, but got Unknown
         lock (_ioLock)
         {
             if (SocialAPI.Achievements != null)
             {
                 SocialAPI.Achievements.StoreStats();
             }
             try
             {
                 using MemoryStream memoryStream = new MemoryStream();
                 using CryptoStream cryptoStream = new CryptoStream(memoryStream, new RijndaelManaged().CreateEncryptor(_cryptoKey, _cryptoKey), CryptoStreamMode.Write);
                 BsonWriter val = new BsonWriter((Stream)cryptoStream);
                 try
                 {
                     JsonSerializer.Create(_serializerSettings).Serialize((JsonWriter)(object)val, (object)_achievements);
                     ((JsonWriter)val).Flush();
                     cryptoStream.FlushFinalBlock();
                     FileUtilities.WriteAllBytes(path, memoryStream.ToArray(), cloud);
                 }
                 finally
                 {
                     ((IDisposable)val)?.Dispose();
                 }
             }
             catch (Exception exception)
             {
                 FancyErrorPrinter.ShowFileSavingFailError(exception, _savePath);
             }
         }
     }
References _achievements, _cryptoKey, _ioLock, _savePath, _serializerSettings, SocialAPI.Achievements, FancyErrorPrinter.ShowFileSavingFailError(), AchievementsSocialModule.StoreStats(), and FileUtilities.WriteAllBytes().