Terraria: AchievementManager.Load
Load() [2/2]
void AchievementManager.Load (string path, bool cloud) inline private
     {
         //IL_0055: Unknown result type (might be due to invalid IL or missing references)
         //IL_005c: Expected O, but got Unknown
         bool flag = false;
         lock (_ioLock)
         {
             if (!FileUtilities.Exists(path, cloud))
             {
                 return;
             }
             byte[] buffer = FileUtilities.ReadAllBytes(path, cloud);
             Dictionary<string, StoredAchievement> dictionary = null;
             try
             {
                 using MemoryStream stream = new MemoryStream(buffer);
                 using CryptoStream cryptoStream = new CryptoStream(stream, new RijndaelManaged().CreateDecryptor(_cryptoKey, _cryptoKey), CryptoStreamMode.Read);
                 BsonReader val = new BsonReader((Stream)cryptoStream);
                 try
                 {
                     dictionary = JsonSerializer.Create(_serializerSettings).Deserialize<Dictionary<string, StoredAchievement>>((JsonReader)(object)val);
                 }
                 finally
                 {
                     ((IDisposable)val)?.Dispose();
                 }
             }
             catch (Exception)
             {
                 FileUtilities.Delete(path, cloud);
                 return;
             }
             if (dictionary == null)
             {
                 return;
             }
             foreach (KeyValuePair<string, StoredAchievement> item in dictionary)
             {
                 if (_achievements.ContainsKey(item.Key))
                 {
                     _achievements[item.Key].Load(item.Value.Conditions);
                 }
             }
             if (SocialAPI.Achievements != null)
             {
                 foreach (KeyValuePair<string, Achievement> achievement in _achievements)
                 {
                     if (achievement.Value.IsCompleted && !SocialAPI.Achievements.IsAchievementCompleted(achievement.Key))
                     {
                         flag = true;
                         achievement.Value.ClearProgress();
                     }
                 }
             }
         }
         if (flag)
         {
             Save();
         }
     }
References _achievements, _cryptoKey, _ioLock, _serializerSettings, SocialAPI.Achievements, FileUtilities.Delete(), FileUtilities.Exists(), AchievementsSocialModule.IsAchievementCompleted(), FileUtilities.ReadAllBytes(), and Save().