Terraria: System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString
WriteQuotedCSharpString()
void System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString (string value) inline package inherited
Definition at line 117 of file XmlSerializationCodeGen.cs.
    {
        _raCodeGen.WriteQuotedCSharpString(value);
    }
References System.Xml.Serialization.XmlSerializationCodeGen._raCodeGen, System.value, and System.Xml.Serialization.ReflectionAwareCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateEnd(), System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateInitCallbacksMethod(), System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateMembersElement(), System.Xml.Serialization.XmlSerializationCodeGen.GeneratePublicMethods(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializers(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAddCollectionFixup(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteArray(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteChoiceTypeCheck(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCreateMapping(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedSerializable(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElementCall(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElements(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEncodedStructMethod(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteMember(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberBegin(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteQualifiedNameElement(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteStructMethod(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteTag(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteTag(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteValue().