Terraria: System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializers
GenerateTypedSerializers()
void System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializers (Hashtable serializers) inline private inherited
Definition at line 314 of file XmlSerializationCodeGen.cs.
    {
        string privateName = "typedSerializers";
        GenerateHashtableGetBegin(privateName, "TypedSerializers");
        foreach (string key in serializers.Keys)
        {
            _writer.Write("_tmp.Add(");
            WriteQuotedCSharpString(key);
            _writer.Write(", new ");
            _writer.Write((string)serializers[key]);
            _writer.WriteLine("());");
        }
        GenerateHashtableGetEnd("typedSerializers");
    }
References System.Xml.Serialization.XmlSerializationCodeGen._writer, System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationCodeGen.GenerateHashtableGetBegin(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateHashtableGetEnd(), System.key, System.Xml.Serialization.IndentedWriter.Write(), System.Xml.Serialization.IndentedWriter.WriteLine(), and System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.XmlSerializationCodeGen.GenerateSerializerContract().