Terraria: System.Xml.Serialization.XmlSerializationCodeGen.GenerateSerializerContract
GenerateSerializerContract()
void System.Xml.Serialization.XmlSerializationCodeGen.GenerateSerializerContract (string className, XmlMapping[] xmlMappings, Type[] types, string readerType, string[] readMethods, string writerType, string[] writerMethods, Hashtable serializers) inline package inherited
Definition at line 357 of file XmlSerializationCodeGen.cs.
    {
        _writer.WriteLine();
        _writer.Write("public class XmlSerializerContract : global::");
        _writer.Write(typeof(XmlSerializerImplementation).FullName);
        _writer.WriteLine(" {");
        _writer.Indent++;
        _writer.Write("public override global::");
        _writer.Write(typeof(XmlSerializationReader).FullName);
        _writer.Write(" Reader { get { return new ");
        _writer.Write(readerType);
        _writer.WriteLine("(); } }");
        _writer.Write("public override global::");
        _writer.Write(typeof(XmlSerializationWriter).FullName);
        _writer.Write(" Writer { get { return new ");
        _writer.Write(writerType);
        _writer.WriteLine("(); } }");
        GeneratePublicMethods("readMethods", "ReadMethods", readMethods, xmlMappings);
        GeneratePublicMethods("writeMethods", "WriteMethods", writerMethods, xmlMappings);
        GenerateTypedSerializers(serializers);
        GenerateSupportedTypes(types);
        GenerateGetSerializer(serializers, xmlMappings);
        _writer.Indent--;
        _writer.WriteLine("}");
    }
References System.Xml.Serialization.XmlSerializationCodeGen._writer, System.Xml.Dictionary, System.FullName, System.Xml.Serialization.XmlSerializationCodeGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializationCodeGen.GeneratePublicMethods(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateSupportedTypes(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializers(), System.Xml.Serialization.IndentedWriter.Indent, System.Xml.Serialization.IndentedWriter.Write(), and System.Xml.Serialization.IndentedWriter.WriteLine().