Terraria: System.Xml.Serialization.XmlSerializationCodeGen.GeneratePublicMethods
GeneratePublicMethods()
void System.Xml.Serialization.XmlSerializationCodeGen.GeneratePublicMethods (string privateName, string publicName, string[] methods, XmlMapping[] xmlMappings) inline package inherited
Definition at line 164 of file XmlSerializationCodeGen.cs.
    {
        GenerateHashtableGetBegin(privateName, publicName);
        if (methods != null && methods.Length != 0 && xmlMappings != null && xmlMappings.Length == methods.Length)
        {
            for (int i = 0; i < methods.Length; i++)
            {
                if (methods[i] != null)
                {
                    _writer.Write("_tmp[");
                    WriteQuotedCSharpString(xmlMappings[i].Key);
                    _writer.Write("] = ");
                    WriteQuotedCSharpString(methods[i]);
                    _writer.WriteLine(";");
                }
            }
        }
        GenerateHashtableGetEnd(privateName);
    }
References System.Xml.Serialization.XmlSerializationCodeGen._writer, System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationCodeGen.GenerateHashtableGetBegin(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateHashtableGetEnd(), System.Xml.Serialization.IndentedWriter.Write(), System.Xml.Serialization.IndentedWriter.WriteLine(), and System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.XmlSerializationCodeGen.GenerateSerializerContract().