Terraria: System.Xml.Serialization.XmlSerializationCodeGen.ReferenceMapping
ReferenceMapping()
string System.Xml.Serialization.XmlSerializationCodeGen.ReferenceMapping (TypeMapping mapping) inline package inherited
Definition at line 92 of file XmlSerializationCodeGen.cs.
    {
        if (!mapping.IsSoap && _generatedMethods[mapping] == null)
        {
            _referencedMethods = EnsureArrayIndex(_referencedMethods, _references);
            _referencedMethods[_references++] = mapping;
        }
        return (string)_methodNames[mapping];
    }
References System.Xml.Serialization.XmlSerializationCodeGen._generatedMethods, System.Xml.Serialization.XmlSerializationCodeGen._methodNames, System.Xml.Serialization.XmlSerializationCodeGen._referencedMethods, System.Xml.Serialization.XmlSerializationCodeGen._references, System.Xml.Dictionary, and System.Xml.Serialization.XmlSerializationCodeGen.EnsureArrayIndex().
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumValue(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WritePrimitive().