Terraria: System.Xml.Xsl.XsltOld.ApplyTemplatesAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.ApplyTemplatesAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 118 of file ApplyTemplatesAction.cs.
    {
        switch (frame.State)
        {
        default:
            return;
        case 0:
            processor.ResetParams();
            processor.InitSortArray();
            if (containedActions != null && containedActions.Count > 0)
            {
                processor.PushActionFrame(frame);
                frame.State = 2;
                return;
            }
            goto case 2;
        case 2:
            if (_selectKey == -1)
            {
                if (!frame.Node.HasChildren)
                {
                    frame.Finished();
                    return;
                }
                frame.InitNewNodeSet(frame.Node.SelectChildren(XPathNodeType.All));
            }
            else
            {
                frame.InitNewNodeSet(processor.StartQuery(frame.NodeSet, _selectKey));
            }
            if (processor.SortArray.Count != 0)
            {
                frame.SortNewNodeSet(processor, processor.SortArray);
            }
            frame.State = 3;
            goto case 3;
        case 3:
            if (frame.NewNextNode(processor))
            {
                frame.State = 4;
                break;
            }
            frame.Finished();
            return;
        case 4:
            break;
        case 5:
            frame.State = 3;
            goto case 3;
        case 1:
            return;
        }
        processor.PushTemplateLookup(frame.NewNodeSet, _mode, null);
        frame.State = 5;
    }
References System.Xml.Xsl.XsltOld.ApplyTemplatesAction._mode, System.Xml.Xsl.XsltOld.ApplyTemplatesAction._selectKey, System.Xml.Xsl.XsltOld.ContainerAction.containedActions, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Xml.XPath.XPathNavigator.HasChildren, System.Xml.Xsl.XsltOld.ActionFrame.InitNewNodeSet(), System.Xml.Xsl.XsltOld.ActionFrame.NewNextNode(), System.Xml.Xsl.XsltOld.ActionFrame.NewNodeSet, System.Xml.Xsl.XsltOld.ActionFrame.Node, System.Xml.Xsl.XsltOld.ActionFrame.NodeSet, System.Xml.XPath.XPathNavigator.SelectChildren(), System.Xml.Xsl.XsltOld.ActionFrame.SortNewNodeSet(), and System.Xml.Xsl.XsltOld.ActionFrame.State.