Terraria: System.Xml.Serialization.XmlSerializationCodeGen.GenerateSupportedTypes
GenerateSupportedTypes()
void System.Xml.Serialization.XmlSerializationCodeGen.GenerateSupportedTypes (Type[] types) inline package inherited
Definition at line 184 of file XmlSerializationCodeGen.cs.
    {
        _writer.Write("public override ");
        _writer.Write(typeof(bool).FullName);
        _writer.Write(" CanSerialize(");
        _writer.Write(typeof(Type).FullName);
        _writer.WriteLine(" type) {");
        _writer.Indent++;
        Hashtable hashtable = new Hashtable();
        foreach (Type type in types)
        {
            if (!(type == null) && (type.IsPublic || type.IsNestedPublic) && hashtable[type] == null && !DynamicAssemblies.IsTypeDynamic(type) && !type.IsGenericType && (!type.ContainsGenericParameters || !DynamicAssemblies.IsTypeDynamic(type.GetGenericArguments())))
            {
                hashtable[type] = type;
                _writer.Write("if (type == typeof(");
                _writer.Write(CodeIdentifier.GetCSharpName(type));
                _writer.WriteLine(")) return true;");
            }
        }
        _writer.WriteLine("return false;");
        _writer.Indent--;
        _writer.WriteLine("}");
    }
References System.Xml.Serialization.XmlSerializationCodeGen._writer, System.Xml.Dictionary, System.FullName, System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Xml.Serialization.IndentedWriter.Indent, System.Xml.Serialization.DynamicAssemblies.IsTypeDynamic(), System.type, System.Xml.Serialization.IndentedWriter.Write(), and System.Xml.Serialization.IndentedWriter.WriteLine().
Referenced by System.Xml.Serialization.XmlSerializationCodeGen.GenerateSerializerContract().