Terraria: System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializer
GenerateTypedSerializer()
string System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializer (string readMethod, string writeMethod, XmlMapping mapping, CodeIdentifiers classes, string baseSerializer, string readerClass, string writerClass) inline package inherited
Definition at line 242 of file XmlSerializationCodeGen.cs.
    {
        string text = CodeIdentifier.MakeValid(Accessor.UnescapeName(mapping.Accessor.Mapping.TypeDesc.Name));
        text = classes.AddUnique(text + "Serializer", mapping);
        _writer.WriteLine();
        _writer.Write("public sealed class ");
        _writer.Write(CodeIdentifier.GetCSharpName(text));
        _writer.Write(" : ");
        _writer.Write(baseSerializer);
        _writer.WriteLine(" {");
        _writer.Indent++;
        _writer.WriteLine();
        _writer.Write("public override ");
        _writer.Write(typeof(bool).FullName);
        _writer.Write(" CanDeserialize(");
        _writer.Write(typeof(XmlReader).FullName);
        _writer.WriteLine(" xmlReader) {");
        _writer.Indent++;
        if (mapping.Accessor.Any)
        {
            _writer.WriteLine("return true;");
        }
        else
        {
            _writer.Write("return xmlReader.IsStartElement(");
            WriteQuotedCSharpString(mapping.Accessor.Name);
            _writer.Write(", ");
            WriteQuotedCSharpString(mapping.Accessor.Namespace);
            _writer.WriteLine(");");
        }
        _writer.Indent--;
        _writer.WriteLine("}");
        if (writeMethod != null)
        {
            _writer.WriteLine();
            _writer.Write("protected override void Serialize(object objectToSerialize, ");
            _writer.Write(typeof(XmlSerializationWriter).FullName);
            _writer.WriteLine(" writer) {");
            _writer.Indent++;
            _writer.Write("((");
            _writer.Write(writerClass);
            _writer.Write(")writer).");
            _writer.Write(writeMethod);
            _writer.Write("(");
            if (mapping is XmlMembersMapping)
            {
                _writer.Write("(object[])");
            }
            _writer.WriteLine("objectToSerialize);");
            _writer.Indent--;
            _writer.WriteLine("}");
        }
        if (readMethod != null)
        {
            _writer.WriteLine();
            _writer.Write("protected override object Deserialize(");
            _writer.Write(typeof(XmlSerializationReader).FullName);
            _writer.WriteLine(" reader) {");
            _writer.Indent++;
            _writer.Write("return ((");
            _writer.Write(readerClass);
            _writer.Write(")reader).");
            _writer.Write(readMethod);
            _writer.WriteLine("();");
            _writer.Indent--;
            _writer.WriteLine("}");
        }
        _writer.Indent--;
        _writer.WriteLine("}");
        return text;
    }
References System.Xml.Serialization.XmlSerializationCodeGen._writer, System.Xml.Dictionary, System.FullName, System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Xml.Serialization.IndentedWriter.Indent, System.Xml.Serialization.CodeIdentifier.MakeValid(), System.text, System.Xml.Serialization.Accessor.UnescapeName(), System.Xml.Serialization.IndentedWriter.Write(), System.Xml.Serialization.IndentedWriter.WriteLine(), and System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString().