Terraria: System.Xml.Serialization.XmlSerializationCodeGen.GenerateBaseSerializer
GenerateBaseSerializer()
string System.Xml.Serialization.XmlSerializationCodeGen.GenerateBaseSerializer (string baseSerializer, string readerClass, string writerClass, CodeIdentifiers classes) inline package inherited
Definition at line 208 of file XmlSerializationCodeGen.cs.
    {
        baseSerializer = CodeIdentifier.MakeValid(baseSerializer);
        baseSerializer = classes.AddUnique(baseSerializer, baseSerializer);
        _writer.WriteLine();
        _writer.Write("public abstract class ");
        _writer.Write(CodeIdentifier.GetCSharpName(baseSerializer));
        _writer.Write(" : ");
        _writer.Write(typeof(XmlSerializer).FullName);
        _writer.WriteLine(" {");
        _writer.Indent++;
        _writer.Write("protected override ");
        _writer.Write(typeof(XmlSerializationReader).FullName);
        _writer.WriteLine(" CreateReader() {");
        _writer.Indent++;
        _writer.Write("return new ");
        _writer.Write(readerClass);
        _writer.WriteLine("();");
        _writer.Indent--;
        _writer.WriteLine("}");
        _writer.Write("protected override ");
        _writer.Write(typeof(XmlSerializationWriter).FullName);
        _writer.WriteLine(" CreateWriter() {");
        _writer.Indent++;
        _writer.Write("return new ");
        _writer.Write(writerClass);
        _writer.WriteLine("();");
        _writer.Indent--;
        _writer.WriteLine("}");
        _writer.Indent--;
        _writer.WriteLine("}");
        return baseSerializer;
    }
References System.Xml.Serialization.XmlSerializationCodeGen._writer, System.Xml.Dictionary, System.FullName, System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Xml.Serialization.IndentedWriter.Indent, System.Xml.Serialization.CodeIdentifier.MakeValid(), System.Xml.Serialization.IndentedWriter.Write(), and System.Xml.Serialization.IndentedWriter.WriteLine().