Terraria: System.Xml.Serialization.XmlSerializationCodeGen.GenerateHashtableGetEnd
GenerateHashtableGetEnd()
void System.Xml.Serialization.XmlSerializationCodeGen.GenerateHashtableGetEnd (string privateName) inline package inherited
Definition at line 146 of file XmlSerializationCodeGen.cs.
    {
        _writer.Write("if (");
        _writer.Write(privateName);
        _writer.Write(" == null) ");
        _writer.Write(privateName);
        _writer.WriteLine(" = _tmp;");
        _writer.Indent--;
        _writer.WriteLine("}");
        _writer.Write("return ");
        _writer.Write(privateName);
        _writer.WriteLine(";");
        _writer.Indent--;
        _writer.WriteLine("}");
        _writer.Indent--;
        _writer.WriteLine("}");
    }
References System.Xml.Serialization.XmlSerializationCodeGen._writer, System.Xml.Dictionary, System.Xml.Serialization.IndentedWriter.Indent, System.Xml.Serialization.IndentedWriter.Write(), and System.Xml.Serialization.IndentedWriter.WriteLine().
Referenced by System.Xml.Serialization.XmlSerializationCodeGen.GeneratePublicMethods(), and System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializers().