Terraria: System.Diagnostics.ActivityContext.Equals
Equals() [2/3]
bool System.Diagnostics.ActivityContext.Equals (ActivityContext value) inline
Definition at line 49 of file ActivityContext.cs.
    {
        if (SpanId.Equals(value.SpanId) && TraceId.Equals(value.TraceId) && TraceFlags == value.TraceFlags && TraceState == value.TraceState)
        {
            return IsRemote == value.IsRemote;
        }
        return false;
    }
References System.Diagnostics.ActivitySpanId.Equals(), System.Diagnostics.ActivityTraceId.Equals(), System.Diagnostics.ActivityContext.IsRemote, System.Diagnostics.ActivityContext.SpanId, System.Diagnostics.ActivityContext.TraceFlags, System.Diagnostics.ActivityContext.TraceId, System.Diagnostics.ActivityContext.TraceState, and System.value.
Referenced by System.Diagnostics.ActivityContext.Equals(), and System.Diagnostics.ActivityContext.operator==().