Terraria: System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable.ObserversState.ProcessItemAsync
ProcessItemAsync()
Task System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.ProcessItemAsync (TOutput item) inline private
Definition at line 951 of file DataflowBlock.cs.
            {
                ImmutableArray<IObserver<TOutput>> observers;
                lock (Observable._SubscriptionLock)
                {
                    observers = Observers;
                }
                try
                {
                    foreach (IObserver<TOutput> item2 in observers)
                    {
                        if (item2 is TargetObserver<TOutput> targetObserver)
{
                            Task<bool> task = targetObserver.SendAsyncToTarget(item);
                            if (task.Status != TaskStatus.RanToCompletion)
{
                                if (_tempSendAsyncTaskList == null)
{
                                    _tempSendAsyncTaskList = new List<Task<bool>>();
                                }
                                _tempSendAsyncTaskList.Add(task);
                            }
                        }
                        else
{
                            item2.OnNext(item);
                        }
                    }
                    if (_tempSendAsyncTaskList != null && _tempSendAsyncTaskList.Count > 0)
                    {
                        Task<bool[]> result = Task.WhenAll(_tempSendAsyncTaskList);
                        _tempSendAsyncTaskList.Clear();
                        return result;
                    }
                }
                catch (Exception exception)
                {
                    return Common.CreateTaskFromException<VoidResult>(exception);
                }
                return Common.CompletedTaskWithTrueResult;
            }
References System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState._tempSendAsyncTaskList, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Threading.Tasks.Dataflow.Internal.Common.CompletedTaskWithTrueResult, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.exception, System.item, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.Observable, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.Observers, System.task, and System.Threading.Tasks.Task< TResult >.WhenAll().
Referenced by System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.ObserversState().