Terraria: System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable.ObserversState.ObserversState
ObserversState()
System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.ObserversState (SourceObservable< TOutput > observable) inline package
Definition at line 932 of file DataflowBlock.cs.
            {
                Observable = observable;
                Target = new ActionBlock<TOutput>((Func<TOutput, Task>)ProcessItemAsync, _nonGreedyExecutionOptions);
                Target.Completion.ContinueWith(delegate(Task t, object state)
                {
                    ((ObserversState)state).NotifyObserversOfCompletion(t.Exception);
                }, this, CancellationToken.None, Common.GetContinuationOptions(TaskContinuationOptions.OnlyOnFaulted | TaskContinuationOptions.ExecuteSynchronously), TaskScheduler.Default);
                Common.GetPotentiallyNotSupportedCompletionTask(Observable._source)?.ContinueWith(delegate(Task _1, object state1)
                {
                    ObserversState observersState = (ObserversState)state1;
                    observersState.Target.Complete();
                    observersState.Target.Completion.ContinueWith(delegate(Task _2, object state2)
                    {
                        ((ObserversState)state2).NotifyObserversOfCompletion();
                    }, state1, CancellationToken.None, Common.GetContinuationOptions(TaskContinuationOptions.NotOnFaulted | TaskContinuationOptions.ExecuteSynchronously), TaskScheduler.Default);
                }, this, Canceler.Token, Common.GetContinuationOptions(TaskContinuationOptions.ExecuteSynchronously), TaskScheduler.Default);
            }
References System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.ObserversState(), System.Threading.Tasks.Dataflow.DataflowBlock._nonGreedyExecutionOptions, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.Canceler, System.Threading.Tasks.Dataflow.ActionBlock< TInput >.Completion, System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Exception, System.Threading.Tasks.Dataflow.Internal.Common.GetContinuationOptions(), System.Threading.Tasks.Dataflow.Internal.Common.GetPotentiallyNotSupportedCompletionTask(), System.Threading.CancellationToken.None, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.Observable, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.ProcessItemAsync(), System.state, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.Target, and System.Threading.CancellationTokenSource.Token.
Referenced by System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.ObserversState().