Terraria: System.Collections.SortedList.Contains
Contains()
virtual bool System.Collections.SortedList.Contains (object key) inline virtual
Implements System.Collections.IDictionary.
Reimplemented in System.Collections.SortedList.SyncSortedList.
Definition at line 741 of file SortedList.cs.
    {
        return IndexOfKey(key) >= 0;
    }
References System.Collections.SortedList.IndexOfKey(), and System.key.
Referenced by System.Xml.Schema.Preprocessor.BuildSchemaList(), System.Collections.SortedList.SyncSortedList.Contains(), and System.Collections.SortedList.KeyList.Contains().