Terraria: System.Collections.SortedList.Remove
Remove()
virtual void System.Collections.SortedList.Remove (object key) inline virtual
Implements System.Collections.IDictionary.
Reimplemented in System.Collections.SortedList.SyncSortedList.
Definition at line 904 of file SortedList.cs.
    {
        int num = IndexOfKey(key);
        if (num >= 0)
        {
            RemoveAt(num);
        }
    }
References System.Collections.SortedList.IndexOfKey(), System.key, and System.Collections.SortedList.RemoveAt().
Referenced by System.Xml.Schema.XmlSchemaSet.Add(), System.Collections.SortedList.SyncSortedList.Remove(), System.Net.PathList.Remove(), and System.Xml.Schema.XmlSchemaSet.Remove().