Terraria: System.Collections.SortedList.Add
Add() [2/2]
virtual void System.Collections.SortedList.Add (object key, object? value) inline virtual inherited
Implements System.Collections.IDictionary.
Definition at line 708 of file SortedList.cs.
    {
        if (key == null)
        {
            throw new ArgumentNullException("key", System.SR.ArgumentNull_Key);
        }
        int num = Array.BinarySearch(keys, 0, _size, key, comparer);
        if (num >= 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.Argument_AddingDuplicate_OldAndNewKeys, GetKey(num), key));
        }
        Insert(~num, key, value);
    }
References System.Collections.SortedList._size, System.SR.Argument_AddingDuplicate_OldAndNewKeys, System.SR.ArgumentNull_Key, System.Array.BinarySearch(), System.Collections.SortedList.comparer, System.SR.Format(), System.Collections.SortedList.GetKey(), System.Insert, System.key, System.Collections.SortedList.keys, and System.value.
Referenced by System.Collections.SortedList.SyncSortedList.Add(), System.Xml.Schema.XmlSchemaSet.AddSchemaToSet(), System.Xml.Schema.Preprocessor.BuildSchemaList(), System.Xml.Schema.XmlSchemaSet.CopyFromCompiledSet(), and System.Xml.Schema.XmlSchemaSet.Reprocess().