Terraria: System.Collections.SortedList.ContainsKey
ContainsKey()
virtual bool System.Collections.SortedList.ContainsKey (object key) inline virtual
Reimplemented in System.Collections.SortedList.SyncSortedList.
Definition at line 746 of file SortedList.cs.
    {
        return IndexOfKey(key) >= 0;
    }
References System.Collections.SortedList.IndexOfKey(), and System.key.
Referenced by System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.Schema.XmlSchemaSet.AddSchemaToSet(), System.Collections.SortedList.SyncSortedList.ContainsKey(), System.Xml.Schema.XmlSchemaSet.CopyFromCompiledSet(), System.Xml.Schema.XmlSchemaSet.IsSchemaLoaded(), System.Xml.Schema.XmlSchemaSet.Remove(), System.Xml.Schema.XmlSchemaSet.RemoveRecursive(), and System.Xml.Schema.XmlSchemaSet.Reprocess().