Terraria: System.Collections.IList.RemoveAt
RemoveAt() [1/2]
void System.Collections.IList.RemoveAt (int index) inherited
Implemented in System.Collections.Immutable.ImmutableArray< T >, System.Collections.Immutable.ImmutableArray< T >, System.Collections.Immutable.ImmutableArray< T >, System.Collections.Immutable.ImmutableArray< T >, System.Collections.Immutable.ImmutableList< T >.Builder, System.Collections.Immutable.ImmutableList< T >, System.Collections.Immutable.ImmutableList< T >, System.Collections.Immutable.ImmutableList< T >, System.Collections.Immutable.ImmutableList< T >, System.Collections.Immutable.ImmutableSortedSet< T >, System.Collections.Immutable.ImmutableSortedSet< T >, System.Collections.CollectionBase, System.Collections.SortedList.KeyList, System.Collections.SortedList.ValueList, System.Collections.Specialized.StringCollection, System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection, System.ComponentModel.ListSortDescriptionCollection, System.Data.Common.DataColumnMappingCollection, System.Data.Common.DataTableMappingCollection, System.Data.Common.DbParameterCollection, System.Data.DataView, System.Data.DataViewManager, System.Collections.Specialized.ReadOnlyList, System.Collections.Specialized.SingleItemReadOnlyList, System.Collections.ObjectModel.Collection< T >, System.Collections.ObjectModel.ReadOnlyCollection< T >, System.Collections.ObjectModel.ReadOnlyCollection< T >, System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.SyncIList, System.Collections.ArrayList.FixedSizeList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyList, System.Collections.ArrayList.ReadOnlyArrayList, System.Collections.ArrayList.Range, and System.Collections.ArrayList.
Referenced by System.Collections.ArrayList.IListWrapper.RemoveAt(), System.Collections.ArrayList.SyncIList.RemoveAt(), System.Collections.ObjectModel.Collection< T >.RemoveItem(), and System.Collections.ArrayList.IListWrapper.RemoveRange().