Terraria: System.Collections.IList.Contains
Contains() [2/2]
bool System.Collections.IList.Contains (object? value) inherited
Implemented in System.Collections.ArrayList, System.ComponentModel.ListSortDescriptionCollection, System.Data.Common.DataColumnMappingCollection, and System.Data.Common.DataTableMappingCollection.
Referenced by System.Collections.ArrayList.SyncIList.Contains(), System.Collections.ArrayList.IListWrapper.Contains(), System.Collections.ArrayList.FixedSizeList.Contains(), System.Collections.ArrayList.ReadOnlyList.Contains(), System.Collections.Specialized.ReadOnlyList.Contains(), System.Collections.ObjectModel.Collection< T >.Contains(), and System.Collections.ObjectModel.ReadOnlyCollection< T >.Contains().