Terraria: UICharacter.DrawSelf
DrawSelf()
override void UICharacter.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         CalculatedStyle dimensions = GetDimensions();
         if (_drawsBackPanel)
         {
             spriteBatch.Draw(_texture.Value, dimensions.Position(), Color.White);
         }
         UpdateAnim();
         DrawPets(spriteBatch);
         Vector2 playerPosition = GetPlayerPosition(ref dimensions);
         Item item = _player.inventory[_player.selectedItem];
         _player.inventory[_player.selectedItem] = _blankItem;
         Main.PlayerRenderer.DrawPlayer(Main.Camera, _player, playerPosition + Main.screenPosition, 0f, Vector2.Zero, 0f, _characterScale);
         _player.inventory[_player.selectedItem] = item;
     }
References _blankItem, _characterScale, _drawsBackPanel, _player, _texture, Main.Camera, Color, DrawPets(), IPlayerRenderer.DrawPlayer(), UIElement.GetDimensions(), GetPlayerPosition(), Player.inventory, Main.PlayerRenderer, CalculatedStyle.Position(), Main.screenPosition, Player.selectedItem, UpdateAnim(), and Asset< T >.Value.