Terraria: UICharacter.Update
Update()
override void UICharacter.Update (GameTime gameTime) inline virtual
Reimplemented from UIElement.
References _animated, _animationCounter, _player, Player.PlayerFrame(), Player.ResetEffects(), Player.ResetVisibleAccessories(), Player.UpdateDyes(), and Player.UpdateMiscCounter().