Terraria: System.Globalization.TimeSpanParse.TimeSpanToken.NormalizeAndValidateFraction
NormalizeAndValidateFraction()
bool System.Globalization.TimeSpanParse.TimeSpanToken.NormalizeAndValidateFraction () inline
Definition at line 59 of file TimeSpanParse.cs.
        {
            if (_num == 0)
            {
                return true;
            }
            if (_zeroes == 0 && _num > 9999999)
            {
                return false;
            }
            int num = (int)Math.Floor(Math.Log10(_num)) + 1 + _zeroes;
            if (num == 7)
            {
                return true;
            }
            if (num < 7)
            {
                _num *= (int)Pow10(7 - num);
                return true;
            }
            _num = (int)Math.Round((double)_num / (double)Pow10(num - 7), MidpointRounding.AwayFromZero);
            return true;
        }
References System.Globalization.TimeSpanParse.TimeSpanToken._num, System.Globalization.TimeSpanParse.TimeSpanToken._zeroes, System.Math.Floor(), System.Math.Log10(), System.Globalization.TimeSpanParse.Pow10(), and System.Math.Round().
Referenced by System.Globalization.TimeSpanParse.TryTimeToTicks().