Terraria: Internal.Runtime.InteropServices.ComActivator.BasicClassFactory.CreateAggregatedObject
CreateAggregatedObject()
static object Internal.Runtime.InteropServices.ComActivator.BasicClassFactory.CreateAggregatedObject (object pUnkOuter, object comObject) inline static
Definition at line 64 of file ComActivator.cs.
        {
            IntPtr iUnknownForObject = Marshal.GetIUnknownForObject(pUnkOuter);
            try
            {
                IntPtr pUnk = Marshal.CreateAggregatedObject(iUnknownForObject, comObject);
                return Marshal.GetObjectForIUnknown(pUnk);
            }
            finally
            {
                Marshal.Release(iUnknownForObject);
            }
        }
References System.Runtime.InteropServices.Marshal.CreateAggregatedObject(), System.Runtime.InteropServices.Marshal.GetIUnknownForObject(), System.Runtime.InteropServices.Marshal.GetObjectForIUnknown(), and System.Runtime.InteropServices.Marshal.Release().
Referenced by Internal.Runtime.InteropServices.ComActivator.BasicClassFactory.CreateInstance(), and Internal.Runtime.InteropServices.ComActivator.LicenseClassFactory.CreateInstanceInner().