Terraria: Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.Recalculate
Recalculate()
override void Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.Recalculate () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 84 of file UIWorkshopSelectResourcePackToPublish.cs.
    {
        if (_scrollbar != null)
        {
            if (_isScrollbarAttached && !_scrollbar.CanScroll)
            {
                _containerPanel.RemoveChild(_scrollbar);
                _isScrollbarAttached = false;
                _entryList.Width.Set(0f, 1f);
            }
            else if (!_isScrollbarAttached && _scrollbar.CanScroll)
            {
                _containerPanel.Append(_scrollbar);
                _isScrollbarAttached = true;
                _entryList.Width.Set(-25f, 1f);
            }
        }
        base.Recalculate();
    }
References Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish._containerPanel, Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish._entryList, Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish._isScrollbarAttached, Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish._scrollbar, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIScrollbar.CanScroll, Terraria.UI.UIElement.RemoveChild(), Terraria.UI.StyleDimension.Set(), and Terraria.UI.UIElement.Width.