Terraria: System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_base64Binary
Read_base64Binary()
object System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_base64Binary () inline package
Definition at line 342 of file XmlSerializationPrimitiveReader.cs.
    {
        object result = null;
        base.Reader.MoveToContent();
        if (base.Reader.NodeType == XmlNodeType.Element)
        {
            if ((object)base.Reader.LocalName != _id16_base64Binary || (object)base.Reader.NamespaceURI != _id2_Item)
            {
                throw CreateUnknownNodeException();
            }
            result = ((!ReadNull()) ? ToByteArrayBase64(isNull: false) : null);
        }
        else
        {
            UnknownNode(null);
        }
        return result;
    }
References System.Xml.Serialization.XmlSerializationPrimitiveReader._id16_base64Binary, System.Xml.Serialization.XmlSerializationPrimitiveReader._id2_Item, System.Xml.Serialization.XmlSerializationReader.CreateUnknownNodeException(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReader.ReadNull(), System.Xml.Serialization.XmlSerializationReader.ToByteArrayBase64(), and System.Xml.Serialization.XmlSerializationReader.UnknownNode().