Terraria: System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_unsignedLong
Read_unsignedLong()
object System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_unsignedLong () inline package
Definition at line 323 of file XmlSerializationPrimitiveReader.cs.
    {
        object result = null;
        base.Reader.MoveToContent();
        if (base.Reader.NodeType == XmlNodeType.Element)
        {
            if ((object)base.Reader.LocalName != _id15_unsignedLong || (object)base.Reader.NamespaceURI != _id2_Item)
            {
                throw CreateUnknownNodeException();
            }
            result = XmlConvert.ToUInt64(base.Reader.ReadElementString());
        }
        else
        {
            UnknownNode(null);
        }
        return result;
    }
References System.Xml.Serialization.XmlSerializationPrimitiveReader._id15_unsignedLong, System.Xml.Serialization.XmlSerializationPrimitiveReader._id2_Item, System.Xml.Serialization.XmlSerializationReader.CreateUnknownNodeException(), System.Xml.Dictionary, System.Xml.XmlConvert.ToUInt64(), and System.Xml.Serialization.XmlSerializationReader.UnknownNode().