Terraria: MS.Internal.Xml.XPath.XPathMultyIterator.Init
Init()
void MS.Internal.Xml.XPath.XPathMultyIterator.Init () inline private
Definition at line 31 of file XPathMultyIterator.cs.
    {
        for (int i = 0; i < arr.Length; i++)
        {
            Advance(i);
        }
        int num = arr.Length - 2;
        while (firstNotEmpty <= num)
        {
            if (SiftItem(num))
            {
                num--;
            }
        }
    }
References MS.Internal.Xml.XPath.XPathMultyIterator.Advance(), MS.Internal.Xml.XPath.XPathMultyIterator.arr, System.Xml.Dictionary, MS.Internal.Xml.XPath.XPathMultyIterator.firstNotEmpty, and MS.Internal.Xml.XPath.XPathMultyIterator.SiftItem().
Referenced by MS.Internal.Xml.XPath.XPathMultyIterator.XPathMultyIterator(), and MS.Internal.Xml.XPath.XPathMultyIterator.Reset().