Terraria: MS.Internal.Xml.XPath.XPathMultyIterator.SiftItem
SiftItem()
bool MS.Internal.Xml.XPath.XPathMultyIterator.SiftItem (int item) inline private
Definition at line 63 of file XPathMultyIterator.cs.
    {
        ResetableIterator resetableIterator = arr[item];
        while (item + 1 < arr.Length)
        {
            ResetableIterator resetableIterator2 = arr[item + 1];
            switch (Query.CompareNodes(resetableIterator.Current, resetableIterator2.Current))
            {
            case XmlNodeOrder.After:
                arr[item] = resetableIterator2;
                item++;
                continue;
            default:
                arr[item] = resetableIterator;
                if (!Advance(item))
                {
                    return false;
                }
                resetableIterator = arr[item];
                continue;
            case XmlNodeOrder.Before:
                break;
            }
            break;
        }
        arr[item] = resetableIterator;
        return true;
    }
References MS.Internal.Xml.XPath.XPathMultyIterator.Advance(), MS.Internal.Xml.XPath.XPathMultyIterator.arr, MS.Internal.Xml.XPath.Query.CompareNodes(), System.Xml.Dictionary, and System.item.
Referenced by MS.Internal.Xml.XPath.XPathMultyIterator.Init(), and MS.Internal.Xml.XPath.XPathMultyIterator.MoveNext().