Terraria: System.IO.Strategies.AsyncWindowsFileStreamStrategy.CopyToAsync
CopyToAsync() [4/4]
override Task System.IO.Strategies.AsyncWindowsFileStreamStrategy.CopyToAsync (Stream destination, int bufferSize, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 21 of file AsyncWindowsFileStreamStrategy.cs.
    {
        if (_fileHandle.IsClosed)
        {
            ThrowHelper.ThrowObjectDisposedException_FileClosed();
        }
        if (!CanRead)
        {
            ThrowHelper.ThrowNotSupportedException_UnreadableStream();
        }
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled<int>(cancellationToken);
        }
        return AsyncModeCopyToAsync(destination, bufferSize, cancellationToken);
    }
References System.IO.Strategies.OSFileStreamStrategy._fileHandle, System.IO.Strategies.AsyncWindowsFileStreamStrategy.AsyncModeCopyToAsync(), System.cancellationToken, System.IO.Strategies.OSFileStreamStrategy.CanRead, System.destination, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.ThrowHelper.ThrowNotSupportedException_UnreadableStream(), and System.ThrowHelper.ThrowObjectDisposedException_FileClosed().