Terraria: System.Diagnostics.Tracing.PropertyValue.ReferenceTypeHelper.GetPropertyGetter
GetPropertyGetter()
override Func< PropertyValue, PropertyValue > System.Diagnostics.Tracing.PropertyValue.ReferenceTypeHelper< TContainer >.GetPropertyGetter (PropertyInfo property) inline
Definition at line 81 of file PropertyValue.cs.
        {
            Type type = property.PropertyType;
            if (!type.IsValueType)
            {
                Func<TContainer, object> getter = (Func<TContainer, object>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(getter((TContainer)container.ReferenceValue));
            }
            if (type.IsEnum)
            {
                type = Enum.GetUnderlyingType(type);
            }
            if (type == typeof(bool))
            {
                Func<TContainer, bool> f = (Func<TContainer, bool>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f((TContainer)container.ReferenceValue));
            }
            if (type == typeof(byte))
            {
                Func<TContainer, byte> f2 = (Func<TContainer, byte>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f2((TContainer)container.ReferenceValue));
            }
            if (type == typeof(sbyte))
            {
                Func<TContainer, sbyte> f3 = (Func<TContainer, sbyte>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f3((TContainer)container.ReferenceValue));
            }
            if (type == typeof(char))
            {
                Func<TContainer, char> f4 = (Func<TContainer, char>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f4((TContainer)container.ReferenceValue));
            }
            if (type == typeof(short))
            {
                Func<TContainer, short> f5 = (Func<TContainer, short>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f5((TContainer)container.ReferenceValue));
            }
            if (type == typeof(ushort))
            {
                Func<TContainer, ushort> f6 = (Func<TContainer, ushort>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f6((TContainer)container.ReferenceValue));
            }
            if (type == typeof(int))
            {
                Func<TContainer, int> f7 = (Func<TContainer, int>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f7((TContainer)container.ReferenceValue));
            }
            if (type == typeof(uint))
            {
                Func<TContainer, uint> f8 = (Func<TContainer, uint>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f8((TContainer)container.ReferenceValue));
            }
            if (type == typeof(long))
            {
                Func<TContainer, long> f9 = (Func<TContainer, long>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f9((TContainer)container.ReferenceValue));
            }
            if (type == typeof(ulong))
            {
                Func<TContainer, ulong> f10 = (Func<TContainer, ulong>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f10((TContainer)container.ReferenceValue));
            }
            if (type == typeof(IntPtr))
            {
                Func<TContainer, IntPtr> f11 = (Func<TContainer, IntPtr>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f11((TContainer)container.ReferenceValue));
            }
            if (type == typeof(UIntPtr))
            {
                Func<TContainer, UIntPtr> f12 = (Func<TContainer, UIntPtr>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f12((TContainer)container.ReferenceValue));
            }
            if (type == typeof(float))
            {
                Func<TContainer, float> f13 = (Func<TContainer, float>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f13((TContainer)container.ReferenceValue));
            }
            if (type == typeof(double))
            {
                Func<TContainer, double> f14 = (Func<TContainer, double>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f14((TContainer)container.ReferenceValue));
            }
            if (type == typeof(Guid))
            {
                Func<TContainer, Guid> f15 = (Func<TContainer, Guid>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f15((TContainer)container.ReferenceValue));
            }
            if (type == typeof(DateTime))
            {
                Func<TContainer, DateTime> f16 = (Func<TContainer, DateTime>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f16((TContainer)container.ReferenceValue));
            }
            if (type == typeof(DateTimeOffset))
            {
                Func<TContainer, DateTimeOffset> f17 = (Func<TContainer, DateTimeOffset>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f17((TContainer)container.ReferenceValue));
            }
            if (type == typeof(TimeSpan))
            {
                Func<TContainer, TimeSpan> f18 = (Func<TContainer, TimeSpan>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f18((TContainer)container.ReferenceValue));
            }
            if (type == typeof(decimal))
            {
                Func<TContainer, decimal> f19 = (Func<TContainer, decimal>)TypeHelper.GetGetMethod(property, type);
                return (PropertyValue container) => new PropertyValue(f19((TContainer)container.ReferenceValue));
            }
            return (PropertyValue container) => new PropertyValue(property.GetValue(container.ReferenceValue));
        }
References System.Diagnostics.Tracing.PropertyValue.PropertyValue(), System.Diagnostics.Tracing.PropertyValue.TypeHelper.GetGetMethod(), System.Enum.GetUnderlyingType(), System.Reflection.PropertyInfo.GetValue(), System.Diagnostics.Tracing.PropertyValue.ReferenceValue, and System.type.