Terraria: TileDrawing.GetHighestWindGridPushComplex
GetHighestWindGridPushComplex()
float TileDrawing.GetHighestWindGridPushComplex (int topLeftX, int topLeftY, int sizeX, int sizeY, int totalPushTime, float pushForcePerFrame, int loops, bool swapLoopDir) inline private
     {
         float result = 0f;
         int num = int.MaxValue;
         for (int i = 0; i < 1; i++)
         {
             for (int j = 0; j < sizeY; j++)
             {
                 _windGrid.GetWindTime(topLeftX + i + sizeX / 2, topLeftY + j, totalPushTime, out var windTimeLeft, out var _, out var _);
                 float windGridPushComplex = GetWindGridPushComplex(topLeftX + i, topLeftY + j, totalPushTime, pushForcePerFrame, loops, swapLoopDir);
                 if (windTimeLeft < num && windTimeLeft != 0)
                 {
                     result = windGridPushComplex;
                     num = windTimeLeft;
                 }
             }
         }
         return result;
     }
References _windGrid, GetWindGridPushComplex(), and WindGrid.GetWindTime().
Referenced by DrawMultiTileVinesInWind().