Terraria: TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint
CrawlToBottomOfReverseVineAndAddSpecialPoint()
void TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint (int j, int i) inline private
     {
         int y = j;
         for (int k = j; k < Main.maxTilesY; k++)
         {
             Tile tile = Main.tile[i, k];
             if (WorldGen.SolidTile(i, k) || !tile.active())
             {
                 y = k - 1;
                 break;
             }
         }
         Point item = new Point(i, y);
         if (!_reverseVineRootsPositions.Contains(item))
         {
             _reverseVineRootsPositions.Add(item);
             AddSpecialPoint(i, y, TileCounterType.ReverseVine);
         }
     }
References _reverseVineRootsPositions, Tile.active(), AddSpecialPoint(), Main.maxTilesY, WorldGen.SolidTile(), and Main.tile.
Referenced by Draw().