Terraria: TileDrawing.DrawTile_MinecartTrack
DrawTile_MinecartTrack()
void TileDrawing.DrawTile_MinecartTrack (Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY, TileDrawInfo drawData) inline private
     {
         drawData.tileLight = GetFinalLight(drawData.tileCache, drawData.typeCache, drawData.tileLight, drawData.colorTint);
         Minecart.TrackColors(tileX, tileY, drawData.tileCache, out var frontColor, out var backColor);
         drawData.drawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY, frontColor);
         Texture2D tileDrawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY, backColor);
         if (WorldGen.IsRope(tileX, tileY) && Main.tile[tileX, tileY - 1] != null)
         {
             _ = Main.tile[tileX, tileY - 1].type;
             int y = (tileY + tileX) % 3 * 18;
             Texture2D tileDrawTexture2 = GetTileDrawTexture(Main.tile[tileX, tileY - 1], tileX, tileY);
             Main.spriteBatch.Draw(tileDrawTexture2, new Vector2(tileX * 16 - (int)screenPosition.X, tileY * 16 - (int)screenPosition.Y) + screenOffset, new Rectangle(90, y, 16, 16), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
         }
         drawData.tileCache.frameNumber();
         if (drawData.tileFrameY != -1)
         {
             Main.spriteBatch.Draw(tileDrawTexture, new Vector2(tileX * 16 - (int)screenPosition.X, tileY * 16 - (int)screenPosition.Y) + screenOffset, Minecart.GetSourceRect(drawData.tileFrameY, Main.tileFrame[314]), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
         }
         Main.spriteBatch.Draw(drawData.drawTexture, new Vector2(tileX * 16 - (int)screenPosition.X, tileY * 16 - (int)screenPosition.Y) + screenOffset, Minecart.GetSourceRect(drawData.tileFrameX, Main.tileFrame[314]), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
         if (Minecart.DrawLeftDecoration(drawData.tileFrameY))
         {
             Main.spriteBatch.Draw(tileDrawTexture, new Vector2(tileX * 16 - (int)screenPosition.X, (tileY + 1) * 16 - (int)screenPosition.Y) + screenOffset, Minecart.GetSourceRect(36), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
         }
         if (Minecart.DrawLeftDecoration(drawData.tileFrameX))
         {
             Main.spriteBatch.Draw(drawData.drawTexture, new Vector2(tileX * 16 - (int)screenPosition.X, (tileY + 1) * 16 - (int)screenPosition.Y) + screenOffset, Minecart.GetSourceRect(36), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
         }
         if (Minecart.DrawRightDecoration(drawData.tileFrameY))
         {
             Main.spriteBatch.Draw(tileDrawTexture, new Vector2(tileX * 16 - (int)screenPosition.X, (tileY + 1) * 16 - (int)screenPosition.Y) + screenOffset, Minecart.GetSourceRect(37, Main.tileFrame[314]), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
         }
         if (Minecart.DrawRightDecoration(drawData.tileFrameX))
         {
             Main.spriteBatch.Draw(drawData.drawTexture, new Vector2(tileX * 16 - (int)screenPosition.X, (tileY + 1) * 16 - (int)screenPosition.Y) + screenOffset, Minecart.GetSourceRect(37), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
         }
         if (Minecart.DrawBumper(drawData.tileFrameX))
         {
             Main.spriteBatch.Draw(drawData.drawTexture, new Vector2(tileX * 16 - (int)screenPosition.X, (tileY - 1) * 16 - (int)screenPosition.Y) + screenOffset, Minecart.GetSourceRect(39), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
         }
         else if (Minecart.DrawBouncyBumper(drawData.tileFrameX))
         {
             Main.spriteBatch.Draw(drawData.drawTexture, new Vector2(tileX * 16 - (int)screenPosition.X, (tileY - 1) * 16 - (int)screenPosition.Y) + screenOffset, Minecart.GetSourceRect(38), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
         }
     }
References TileDrawInfo.colorTint, Minecart.DrawBouncyBumper(), Minecart.DrawBumper(), Minecart.DrawLeftDecoration(), Minecart.DrawRightDecoration(), TileDrawInfo.drawTexture, Tile.frameNumber(), GetFinalLight(), Minecart.GetSourceRect(), GetTileDrawTexture(), WorldGen.IsRope(), Main.spriteBatch, Main.tile, TileDrawInfo.tileCache, Main.tileFrame, TileDrawInfo.tileFrameX, TileDrawInfo.tileFrameY, TileDrawInfo.tileLight, TileDrawInfo.tileSpriteEffect, Minecart.TrackColors(), Tile.type, and TileDrawInfo.typeCache.
Referenced by DrawSingleTile().