Terraria: TileDrawing.GetTreeBiome
GetTreeBiome()
static int TileDrawing.GetTreeBiome (int tileX, int tileY, int tileFrameX, int tileFrameY) inline static private
     {
         int num = tileX;
         int i = tileY;
         int type = Main.tile[num, i].type;
         if (tileFrameX == 66 && tileFrameY <= 45)
         {
             num++;
         }
         if (tileFrameX == 88 && tileFrameY >= 66 && tileFrameY <= 110)
         {
             num--;
         }
         if (tileFrameY >= 198)
         {
             switch (tileFrameX)
             {
             case 66:
                 num--;
                 break;
             case 44:
                 num++;
                 break;
             }
         }
         else if (tileFrameY >= 132)
         {
             switch (tileFrameX)
             {
             case 22:
                 num--;
                 break;
             case 44:
                 num++;
                 break;
             }
         }
         for (; Main.tile[num, i].active() && Main.tile[num, i].type == type; i++)
         {
         }
         return GetTreeVariant(num, i);
     }
References Tile.active(), GetTreeVariant(), Main.tile, and Tile.type.
Referenced by GetTileDrawData(), GetTileDrawTexture(), and PrepareForAreaDrawing().