Terraria: TileDrawing.EnsureWindGridSize
EnsureWindGridSize()
void TileDrawing.EnsureWindGridSize () inline private
     {
         Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
         Vector2 offSet = new Vector2(Main.offScreenRange, Main.offScreenRange);
         if (Main.drawToScreen)
         {
             offSet = Vector2.Zero;
         }
         GetScreenDrawArea(unscaledPosition, offSet, out var firstTileX, out var lastTileX, out var firstTileY, out var lastTileY);
         _windGrid.SetSize(lastTileX - firstTileX, lastTileY - firstTileY);
     }
References _windGrid, Main.Camera, Main.drawToScreen, GetScreenDrawArea(), Main.offScreenRange, WindGrid.SetSize(), and Camera.UnscaledPosition.
Referenced by Draw(), and Update().