Terraria: TileDrawing.DrawTile_LiquidBehindTile
DrawTile_LiquidBehindTile()
void TileDrawing.DrawTile_LiquidBehindTile (bool solidLayer, bool inFrontOfPlayers, int waterStyleOverride, Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY, Tile tileCache) inline private
     {
         Tile tile = Main.tile[tileX + 1, tileY];
         Tile tile2 = Main.tile[tileX - 1, tileY];
         Tile tile3 = Main.tile[tileX, tileY - 1];
         Tile tile4 = Main.tile[tileX, tileY + 1];
         if (tile == null)
         {
             tile = new Tile();
             Main.tile[tileX + 1, tileY] = tile;
         }
         if (tile2 == null)
         {
             tile2 = new Tile();
             Main.tile[tileX - 1, tileY] = tile2;
         }
         if (tile3 == null)
         {
             tile3 = new Tile();
             Main.tile[tileX, tileY - 1] = tile3;
         }
         if (tile4 == null)
         {
             tile4 = new Tile();
             Main.tile[tileX, tileY + 1] = tile4;
         }
         if (!tileCache.active() || tileCache.inActive() || _tileSolidTop[tileCache.type] || (tileCache.halfBrick() && (tile2.liquid > 160 || tile.liquid > 160) && Main.instance.waterfallManager.CheckForWaterfall(tileX, tileY)) || (TileID.Sets.BlocksWaterDrawingBehindSelf[tileCache.type] && tileCache.slope() == 0))
         {
             return;
         }
         int num = 0;
         bool flag = false;
         bool flag2 = false;
         bool flag3 = false;
         bool flag4 = false;
         bool flag5 = false;
         int num2 = 0;
         bool flag6 = false;
         int num3 = tileCache.slope();
         int num4 = tileCache.blockType();
         if (tileCache.type == 546 && tileCache.liquid > 0)
         {
             flag5 = true;
             flag4 = true;
             flag = true;
             flag2 = true;
             switch (tileCache.liquidType())
             {
             case 0:
                 flag6 = true;
                 break;
             case 1:
                 num2 = 1;
                 break;
             case 2:
                 num2 = 11;
                 break;
             case 3:
                 num2 = 14;
                 break;
             }
             num = tileCache.liquid;
         }
         else
         {
             if (tileCache.liquid > 0 && num4 != 0 && (num4 != 1 || tileCache.liquid > 160))
             {
                 flag5 = true;
                 switch (tileCache.liquidType())
                 {
                 case 0:
                     flag6 = true;
                     break;
                 case 1:
                     num2 = 1;
                     break;
                 case 2:
                     num2 = 11;
                     break;
                 case 3:
                     num2 = 14;
                     break;
                 }
                 if (tileCache.liquid > num)
                 {
                     num = tileCache.liquid;
                 }
             }
             if (tile2.liquid > 0 && num3 != 1 && num3 != 3)
             {
                 flag = true;
                 switch (tile2.liquidType())
                 {
                 case 0:
                     flag6 = true;
                     break;
                 case 1:
                     num2 = 1;
                     break;
                 case 2:
                     num2 = 11;
                     break;
                 case 3:
                     num2 = 14;
                     break;
                 }
                 if (tile2.liquid > num)
                 {
                     num = tile2.liquid;
                 }
             }
             if (tile.liquid > 0 && num3 != 2 && num3 != 4)
             {
                 flag2 = true;
                 switch (tile.liquidType())
                 {
                 case 0:
                     flag6 = true;
                     break;
                 case 1:
                     num2 = 1;
                     break;
                 case 2:
                     num2 = 11;
                     break;
                 case 3:
                     num2 = 14;
                     break;
                 }
                 if (tile.liquid > num)
                 {
                     num = tile.liquid;
                 }
             }
             if (tile3.liquid > 0 && num3 != 3 && num3 != 4)
             {
                 flag3 = true;
                 switch (tile3.liquidType())
                 {
                 case 0:
                     flag6 = true;
                     break;
                 case 1:
                     num2 = 1;
                     break;
                 case 2:
                     num2 = 11;
                     break;
                 case 3:
                     num2 = 14;
                     break;
                 }
             }
             if (tile4.liquid > 0 && num3 != 1 && num3 != 2)
             {
                 if (tile4.liquid > 240)
                 {
                     flag4 = true;
                 }
                 switch (tile4.liquidType())
                 {
                 case 0:
                     flag6 = true;
                     break;
                 case 1:
                     num2 = 1;
                     break;
                 case 2:
                     num2 = 11;
                     break;
                 case 3:
                     num2 = 14;
                     break;
                 }
             }
         }
         if (!flag3 && !flag4 && !flag && !flag2 && !flag5)
         {
             return;
         }
         if (waterStyleOverride != -1)
         {
             Main.waterStyle = waterStyleOverride;
         }
         if (num2 == 0)
         {
             num2 = Main.waterStyle;
         }
         Lighting.GetCornerColors(tileX, tileY, out var vertices);
         Vector2 vector = new Vector2(tileX * 16, tileY * 16);
         Rectangle liquidSize = new Rectangle(0, 4, 16, 16);
         if (flag4 && (flag || flag2))
         {
             flag = true;
             flag2 = true;
         }
         if (tileCache.active() && (Main.tileSolidTop[tileCache.type] || !Main.tileSolid[tileCache.type]))
         {
             return;
         }
         if ((!flag3 || !(flag || flag2)) && !(flag4 && flag3))
         {
             if (flag3)
             {
                 liquidSize = new Rectangle(0, 4, 16, 4);
                 if (tileCache.halfBrick() || tileCache.slope() != 0)
                 {
                     liquidSize = new Rectangle(0, 4, 16, 12);
                 }
             }
             else if (flag4 && !flag && !flag2)
             {
                 vector = new Vector2(tileX * 16, tileY * 16 + 12);
                 liquidSize = new Rectangle(0, 4, 16, 4);
             }
             else
             {
                 float num5 = (float)(256 - num) / 32f;
                 int y = 4;
                 if (tile3.liquid == 0 && (num4 != 0 || !WorldGen.SolidTile(tileX, tileY - 1)))
                 {
                     y = 0;
                 }
                 int num6 = (int)num5 * 2;
                 if (tileCache.slope() != 0)
                 {
                     vector = new Vector2(tileX * 16, tileY * 16 + num6);
                     liquidSize = new Rectangle(0, num6, 16, 16 - num6);
                 }
                 else if ((flag && flag2) || tileCache.halfBrick())
                 {
                     vector = new Vector2(tileX * 16, tileY * 16 + num6);
                     liquidSize = new Rectangle(0, y, 16, 16 - num6);
                 }
                 else if (flag)
                 {
                     vector = new Vector2(tileX * 16, tileY * 16 + num6);
                     liquidSize = new Rectangle(0, y, 4, 16 - num6);
                 }
                 else
                 {
                     vector = new Vector2(tileX * 16 + 12, tileY * 16 + num6);
                     liquidSize = new Rectangle(0, y, 4, 16 - num6);
                 }
             }
         }
         Vector2 position = vector - screenPosition + screenOffset;
         float num7 = 0.5f;
         switch (num2)
         {
         case 1:
             num7 = 1f;
             break;
         case 11:
             num7 = Math.Max(num7 * 1.7f, 1f);
             break;
         }
         if ((double)tileY <= Main.worldSurface || num7 > 1f)
         {
             num7 = 1f;
             if (tileCache.wall == 21)
             {
                 num7 = 0.9f;
             }
             else if (tileCache.wall > 0)
             {
                 num7 = 0.6f;
             }
         }
         if (tileCache.halfBrick() && tile3.liquid > 0 && tileCache.wall > 0)
         {
             num7 = 0f;
         }
         if (num3 == 4 && tile2.liquid == 0 && !WorldGen.SolidTile(tileX - 1, tileY))
         {
             num7 = 0f;
         }
         if (num3 == 3 && tile.liquid == 0 && !WorldGen.SolidTile(tileX + 1, tileY))
         {
             num7 = 0f;
         }
         vertices.BottomLeftColor *= num7;
         vertices.BottomRightColor *= num7;
         vertices.TopLeftColor *= num7;
         vertices.TopRightColor *= num7;
         bool flag7 = false;
         if (flag6)
         {
             for (int i = 0; i < 15; i++)
             {
                 if (Main.IsLiquidStyleWater(i) && Main.liquidAlpha[i] > 0f && i != num2)
                 {
                     DrawPartialLiquid(!solidLayer, tileCache, ref position, ref liquidSize, i, ref vertices);
                     flag7 = true;
                     break;
                 }
             }
         }
         VertexColors colors = vertices;
         float num8 = (flag7 ? Main.liquidAlpha[num2] : 1f);
         colors.BottomLeftColor *= num8;
         colors.BottomRightColor *= num8;
         colors.TopLeftColor *= num8;
         colors.TopRightColor *= num8;
         if (num2 == 14)
         {
             LiquidRenderer.SetShimmerVertexColors(ref colors, solidLayer ? 0.75f : 1f, tileX, tileY);
         }
         DrawPartialLiquid(!solidLayer, tileCache, ref position, ref liquidSize, num2, ref colors);
     }
References _tileSolidTop, Tile.active(), TileID.Sets.BlocksWaterDrawingBehindSelf, Tile.blockType(), VertexColors.BottomLeftColor, VertexColors.BottomRightColor, WaterfallManager.CheckForWaterfall(), DrawPartialLiquid(), Lighting.GetCornerColors(), Tile.halfBrick(), Tile.inActive(), Main.instance, Main.IsLiquidStyleWater(), Tile.liquid, Main.liquidAlpha, Tile.liquidType(), LiquidRenderer.SetShimmerVertexColors(), Tile.slope(), WorldGen.SolidTile(), Tile, Main.tile, Main.tileSolid, Main.tileSolidTop, VertexColors.TopLeftColor, VertexColors.TopRightColor, Tile.type, Tile.wall, Main.waterfallManager, and Main.waterStyle.
Referenced by Draw(), and DrawLiquidBehindTiles().