Terraria: TileDrawing.DrawMultiTileVines
DrawMultiTileVines()
void TileDrawing.DrawMultiTileVines () inline private
     {
         Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
         Vector2 zero = Vector2.Zero;
         int num = 5;
         int num2 = _specialsCount[num];
         for (int i = 0; i < num2; i++)
         {
             Point point = _specialPositions[num][i];
             int x = point.X;
             int y = point.Y;
             int sizeX = 1;
             int sizeY = 1;
             Tile tile = Main.tile[x, y];
             if (tile != null && tile.active())
             {
                 switch (Main.tile[x, y].type)
                 {
                 case 34:
                     sizeX = 3;
                     sizeY = 3;
                     break;
                 case 454:
                     sizeX = 4;
                     sizeY = 3;
                     break;
                 case 42:
                 case 270:
                 case 271:
                 case 572:
                 case 581:
                 case 660:
                     sizeX = 1;
                     sizeY = 2;
                     break;
                 case 91:
                     sizeX = 1;
                     sizeY = 3;
                     break;
                 case 95:
                 case 126:
                 case 444:
                     sizeX = 2;
                     sizeY = 2;
                     break;
                 case 465:
                 case 591:
                 case 592:
                     sizeX = 2;
                     sizeY = 3;
                     break;
                 }
                 DrawMultiTileVinesInWind(unscaledPosition, zero, x, y, sizeX, sizeY);
             }
         }
     }
References _specialPositions, _specialsCount, Tile.active(), Main.Camera, DrawMultiTileVinesInWind(), Main.tile, Tile.type, and Camera.UnscaledPosition.
Referenced by PostDrawTiles().