Terraria: TileDrawing.CacheSpecialDraws_Part1
CacheSpecialDraws_Part1()
void TileDrawing.CacheSpecialDraws_Part1 (int tileX, int tileY, int tileType, int drawDataTileFrameX, int drawDataTileFrameY, bool skipDraw) inline private
     {
         if (tileType == 395)
         {
             Point point = new Point(tileX, tileY);
             if (drawDataTileFrameX % 36 != 0)
             {
                 point.X--;
             }
             if (drawDataTileFrameY % 36 != 0)
             {
                 point.Y--;
             }
             if (!_itemFrameTileEntityPositions.ContainsKey(point))
             {
                 _itemFrameTileEntityPositions[point] = TEItemFrame.Find(point.X, point.Y);
                 if (_itemFrameTileEntityPositions[point] != -1)
                 {
                     AddSpecialLegacyPoint(point);
                 }
             }
         }
         if (tileType == 520)
         {
             Point point2 = new Point(tileX, tileY);
             if (!_foodPlatterTileEntityPositions.ContainsKey(point2))
             {
                 _foodPlatterTileEntityPositions[point2] = TEFoodPlatter.Find(point2.X, point2.Y);
                 if (_foodPlatterTileEntityPositions[point2] != -1)
                 {
                     AddSpecialLegacyPoint(point2);
                 }
             }
         }
         if (tileType == 471)
         {
             Point point3 = new Point(tileX, tileY);
             point3.X -= drawDataTileFrameX % 54 / 18;
             point3.Y -= drawDataTileFrameY % 54 / 18;
             if (!_weaponRackTileEntityPositions.ContainsKey(point3))
             {
                 _weaponRackTileEntityPositions[point3] = TEWeaponsRack.Find(point3.X, point3.Y);
                 if (_weaponRackTileEntityPositions[point3] != -1)
                 {
                     AddSpecialLegacyPoint(point3);
                 }
             }
         }
         if (tileType == 470)
         {
             Point point4 = new Point(tileX, tileY);
             point4.X -= drawDataTileFrameX % 36 / 18;
             point4.Y -= drawDataTileFrameY % 54 / 18;
             if (!_displayDollTileEntityPositions.ContainsKey(point4))
             {
                 _displayDollTileEntityPositions[point4] = TEDisplayDoll.Find(point4.X, point4.Y);
                 if (_displayDollTileEntityPositions[point4] != -1)
                 {
                     AddSpecialLegacyPoint(point4);
                 }
             }
         }
         if (tileType == 475)
         {
             Point point5 = new Point(tileX, tileY);
             point5.X -= drawDataTileFrameX % 54 / 18;
             point5.Y -= drawDataTileFrameY % 72 / 18;
             if (!_hatRackTileEntityPositions.ContainsKey(point5))
             {
                 _hatRackTileEntityPositions[point5] = TEHatRack.Find(point5.X, point5.Y);
                 if (_hatRackTileEntityPositions[point5] != -1)
                 {
                     AddSpecialLegacyPoint(point5);
                 }
             }
         }
         if (tileType == 412 && drawDataTileFrameX == 0 && drawDataTileFrameY == 0)
         {
             AddSpecialLegacyPoint(tileX, tileY);
         }
         if (tileType == 620 && drawDataTileFrameX == 0 && drawDataTileFrameY == 0)
         {
             AddSpecialLegacyPoint(tileX, tileY);
         }
         if (tileType == 237 && drawDataTileFrameX == 18 && drawDataTileFrameY == 0)
         {
             AddSpecialLegacyPoint(tileX, tileY);
         }
         if (skipDraw)
         {
             return;
         }
         switch (tileType)
         {
         case 323:
             if (drawDataTileFrameX <= 132 && drawDataTileFrameX >= 88)
             {
                 AddSpecialPoint(tileX, tileY, TileCounterType.Tree);
             }
             break;
         case 5:
         case 583:
         case 584:
         case 585:
         case 586:
         case 587:
         case 588:
         case 589:
         case 596:
         case 616:
         case 634:
             if (drawDataTileFrameY >= 198 && drawDataTileFrameX >= 22)
             {
                 AddSpecialPoint(tileX, tileY, TileCounterType.Tree);
             }
             break;
         }
     }
References _displayDollTileEntityPositions, _foodPlatterTileEntityPositions, _hatRackTileEntityPositions, _itemFrameTileEntityPositions, _weaponRackTileEntityPositions, AddSpecialLegacyPoint(), AddSpecialPoint(), TEDisplayDoll.Find(), TEFoodPlatter.Find(), TEHatRack.Find(), TEItemFrame.Find(), and TEWeaponsRack.Find().
Referenced by DrawSingleTile().