Terraria: TileDrawing.DrawBasicTile
DrawBasicTile()
void TileDrawing.DrawBasicTile (Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY, TileDrawInfo drawData, Rectangle normalTileRect, Vector2 normalTilePosition) inline private
     {
         if (TileID.Sets.Platforms[drawData.typeCache] && WorldGen.IsRope(tileX, tileY) && Main.tile[tileX, tileY - 1] != null)
         {
             _ = Main.tile[tileX, tileY - 1].type;
             int y = (tileY + tileX) % 3 * 18;
             Texture2D tileDrawTexture = GetTileDrawTexture(Main.tile[tileX, tileY - 1], tileX, tileY);
             if (tileDrawTexture != null)
             {
                 Main.spriteBatch.Draw(tileDrawTexture, new Vector2(tileX * 16 - (int)screenPosition.X, tileY * 16 - (int)screenPosition.Y) + screenOffset, new Rectangle(90, y, 16, 16), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
             }
         }
         if (drawData.tileCache.slope() > 0)
         {
             if (TileID.Sets.Platforms[drawData.tileCache.type])
             {
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, normalTileRect, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 if (drawData.tileCache.slope() == 1 && Main.tile[tileX + 1, tileY + 1].active() && Main.tileSolid[Main.tile[tileX + 1, tileY + 1].type] && Main.tile[tileX + 1, tileY + 1].slope() != 2 && !Main.tile[tileX + 1, tileY + 1].halfBrick() && (!Main.tile[tileX, tileY + 1].active() || (Main.tile[tileX, tileY + 1].blockType() != 0 && Main.tile[tileX, tileY + 1].blockType() != 5) || (!TileID.Sets.BlocksStairs[Main.tile[tileX, tileY + 1].type] && !TileID.Sets.BlocksStairsAbove[Main.tile[tileX, tileY + 1].type])))
                 {
                     Rectangle value = new Rectangle(198, drawData.tileFrameY, 16, 16);
                     if (TileID.Sets.Platforms[Main.tile[tileX + 1, tileY + 1].type] && Main.tile[tileX + 1, tileY + 1].slope() == 0)
                     {
                         value.X = 324;
                     }
                     Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 16f), value, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 }
                 else if (drawData.tileCache.slope() == 2 && Main.tile[tileX - 1, tileY + 1].active() && Main.tileSolid[Main.tile[tileX - 1, tileY + 1].type] && Main.tile[tileX - 1, tileY + 1].slope() != 1 && !Main.tile[tileX - 1, tileY + 1].halfBrick() && (!Main.tile[tileX, tileY + 1].active() || (Main.tile[tileX, tileY + 1].blockType() != 0 && Main.tile[tileX, tileY + 1].blockType() != 4) || (!TileID.Sets.BlocksStairs[Main.tile[tileX, tileY + 1].type] && !TileID.Sets.BlocksStairsAbove[Main.tile[tileX, tileY + 1].type])))
                 {
                     Rectangle value2 = new Rectangle(162, drawData.tileFrameY, 16, 16);
                     if (TileID.Sets.Platforms[Main.tile[tileX - 1, tileY + 1].type] && Main.tile[tileX - 1, tileY + 1].slope() == 0)
                     {
                         value2.X = 306;
                     }
                     Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 16f), value2, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 }
                 return;
             }
             if (TileID.Sets.HasSlopeFrames[drawData.tileCache.type])
             {
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, 16, 16), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 return;
             }
             int num = drawData.tileCache.slope();
             int num2 = 2;
             for (int i = 0; i < 8; i++)
             {
                 int num3 = i * -2;
                 int num4 = 16 - i * 2;
                 int num5 = 16 - num4;
                 int num6;
                 switch (num)
                 {
                 case 1:
                     num3 = 0;
                     num6 = i * 2;
                     num4 = 14 - i * 2;
                     num5 = 0;
                     break;
                 case 2:
                     num3 = 0;
                     num6 = 16 - i * 2 - 2;
                     num4 = 14 - i * 2;
                     num5 = 0;
                     break;
                 case 3:
                     num6 = i * 2;
                     break;
                 default:
                     num6 = 16 - i * 2 - 2;
                     break;
                 }
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(num6, i * num2 + num3), new Rectangle(drawData.tileFrameX + drawData.addFrX + num6, drawData.tileFrameY + drawData.addFrY + num5, num2, num4), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
             }
             int num7 = ((num <= 2) ? 14 : 0);
             Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, num7), new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY + num7, 16, 2), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
             return;
         }
         if (!TileID.Sets.Platforms[drawData.typeCache] && !TileID.Sets.IgnoresNearbyHalfbricksWhenDrawn[drawData.typeCache] && _tileSolid[drawData.typeCache] && !TileID.Sets.NotReallySolid[drawData.typeCache] && !drawData.tileCache.halfBrick() && (Main.tile[tileX - 1, tileY].halfBrick() || Main.tile[tileX + 1, tileY].halfBrick()))
         {
             if (Main.tile[tileX - 1, tileY].halfBrick() && Main.tile[tileX + 1, tileY].halfBrick())
             {
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 8f), new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.addFrY + drawData.tileFrameY + 8, drawData.tileWidth, 8), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 Rectangle value3 = new Rectangle(126 + drawData.addFrX, drawData.addFrY, 16, 8);
                 if (Main.tile[tileX, tileY - 1].active() && !Main.tile[tileX, tileY - 1].bottomSlope() && Main.tile[tileX, tileY - 1].type == drawData.typeCache)
                 {
                     value3 = new Rectangle(90 + drawData.addFrX, drawData.addFrY, 16, 8);
                 }
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, value3, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
             }
             else if (Main.tile[tileX - 1, tileY].halfBrick())
             {
                 int num8 = 4;
                 if (TileID.Sets.AllBlocksWithSmoothBordersToResolveHalfBlockIssue[drawData.typeCache])
                 {
                     num8 = 2;
                 }
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 8f), new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.addFrY + drawData.tileFrameY + 8, drawData.tileWidth, 8), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(num8, 0f), new Rectangle(drawData.tileFrameX + num8 + drawData.addFrX, drawData.addFrY + drawData.tileFrameY, drawData.tileWidth - num8, drawData.tileHeight), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, new Rectangle(144 + drawData.addFrX, drawData.addFrY, num8, 8), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 if (num8 == 2)
                 {
                     Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, new Rectangle(148 + drawData.addFrX, drawData.addFrY, 2, 2), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 }
             }
             else if (Main.tile[tileX + 1, tileY].halfBrick())
             {
                 int num9 = 4;
                 if (TileID.Sets.AllBlocksWithSmoothBordersToResolveHalfBlockIssue[drawData.typeCache])
                 {
                     num9 = 2;
                 }
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 8f), new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.addFrY + drawData.tileFrameY + 8, drawData.tileWidth, 8), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.addFrY + drawData.tileFrameY, drawData.tileWidth - num9, drawData.tileHeight), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(16 - num9, 0f), new Rectangle(144 + (16 - num9), 0, num9, 8), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 if (num9 == 2)
                 {
                     Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(14f, 0f), new Rectangle(156, 0, 2, 2), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 }
             }
             return;
         }
         if (Lighting.NotRetro && _tileSolid[drawData.typeCache] && !drawData.tileCache.halfBrick() && !TileID.Sets.DontDrawTileSliced[drawData.tileCache.type])
         {
             DrawSingleTile_SlicedBlock(normalTilePosition, tileX, tileY, drawData);
             return;
         }
         if (drawData.halfBrickHeight == 8 && (!Main.tile[tileX, tileY + 1].active() || !_tileSolid[Main.tile[tileX, tileY + 1].type] || Main.tile[tileX, tileY + 1].halfBrick()))
         {
             if (TileID.Sets.Platforms[drawData.typeCache])
             {
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, normalTileRect, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
             }
             else
             {
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, normalTileRect.Modified(0, 0, 0, -4), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 4f), new Rectangle(144 + drawData.addFrX, 66 + drawData.addFrY, drawData.tileWidth, 4), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
             }
         }
         else if (TileID.Sets.CritterCageLidStyle[drawData.typeCache] >= 0)
         {
             int num10 = TileID.Sets.CritterCageLidStyle[drawData.typeCache];
             if ((num10 < 3 && normalTileRect.Y % 54 == 0) || (num10 >= 3 && normalTileRect.Y % 36 == 0))
             {
                 Vector2 position = normalTilePosition;
                 position.Y += 8f;
                 Rectangle value4 = normalTileRect;
                 value4.Y += 8;
                 value4.Height -= 8;
                 Main.spriteBatch.Draw(drawData.drawTexture, position, value4, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 position = normalTilePosition;
                 position.Y -= 2f;
                 value4 = normalTileRect;
                 value4.Y = 0;
                 value4.Height = 10;
                 Main.spriteBatch.Draw(TextureAssets.CageTop[num10].Value, position, value4, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
             }
             else
             {
                 Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, normalTileRect, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
             }
         }
         else
         {
             Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, normalTileRect, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
         }
         DrawSingleTile_Flames(screenPosition, screenOffset, tileX, tileY, drawData);
     }
References _tileSolid, _zero, Tile.active(), TileDrawInfo.addFrX, TileDrawInfo.addFrY, TileID.Sets.AllBlocksWithSmoothBordersToResolveHalfBlockIssue, TileID.Sets.BlocksStairs, TileID.Sets.BlocksStairsAbove, Tile.blockType(), Tile.bottomSlope(), TextureAssets.CageTop, TileID.Sets.CritterCageLidStyle, TileID.Sets.DontDrawTileSliced, DrawSingleTile_Flames(), DrawSingleTile_SlicedBlock(), TileDrawInfo.drawTexture, TileDrawInfo.finalColor, GetTileDrawTexture(), Tile.halfBrick(), TileDrawInfo.halfBrickHeight, TileID.Sets.HasSlopeFrames, TileID.Sets.IgnoresNearbyHalfbricksWhenDrawn, WorldGen.IsRope(), TileID.Sets.NotReallySolid, Lighting.NotRetro, TileID.Sets.Platforms, Tile.slope(), Main.spriteBatch, Main.tile, TileDrawInfo.tileCache, TileDrawInfo.tileFrameX, TileDrawInfo.tileFrameY, TileDrawInfo.tileHeight, TileDrawInfo.tileLight, Main.tileSolid, TileDrawInfo.tileSpriteEffect, TileDrawInfo.tileWidth, Tile.type, TileDrawInfo.typeCache, and Asset< T >.Value.
Referenced by DrawSingleTile().