Terraria: TileDrawing.IsAlchemyPlantHarvestable
IsAlchemyPlantHarvestable()
bool TileDrawing.IsAlchemyPlantHarvestable (int style) inline private
     {
         if (style == 0 && Main.dayTime)
         {
             return true;
         }
         if (style == 1 && !Main.dayTime)
         {
             return true;
         }
         if (style == 3 && !Main.dayTime && (Main.bloodMoon || Main.moonPhase == 0))
         {
             return true;
         }
         if (style == 4 && (Main.raining || Main.cloudAlpha > 0f))
         {
             return true;
         }
         if (style == 5 && !Main.raining && Main.time > 40500.0)
         {
             return true;
         }
         return false;
     }
References Main.bloodMoon, Main.cloudAlpha, Main.dayTime, Main.moonPhase, Main.raining, and Main.time.
Referenced by DrawAnyDirectionalGrass(), DrawGrass(), DrawTiles_EmitParticles(), DrawTiles_GetLightOverride(), and GetTileDrawTexture().