Terraria: TileDrawing.DrawVoidLenses
DrawVoidLenses()
void TileDrawing.DrawVoidLenses () inline private
     {
         int num = 8;
         int num2 = _specialsCount[num];
         _voidLensData.Clear();
         for (int i = 0; i < num2; i++)
         {
             Point p = _specialPositions[num][i];
             VoidLensHelper voidLensHelper = new VoidLensHelper(p.ToWorldCoordinates(), 1f);
             if (!Main.gamePaused)
             {
                 voidLensHelper.Update();
             }
             int selectionMode = 0;
             if (Main.InSmartCursorHighlightArea(p.X, p.Y, out var actuallySelected))
             {
                 selectionMode = 1;
                 if (actuallySelected)
                 {
                     selectionMode = 2;
                 }
             }
             voidLensHelper.DrawToDrawData(_voidLensData, selectionMode);
         }
         foreach (DrawData voidLensDatum in _voidLensData)
         {
             voidLensDatum.Draw(Main.spriteBatch);
         }
     }
References _specialPositions, _specialsCount, _voidLensData, DrawData.Draw(), VoidLensHelper.DrawToDrawData(), Main.gamePaused, Main.InSmartCursorHighlightArea(), Main.spriteBatch, and VoidLensHelper.Update().
Referenced by PostDrawTiles().