Terraria: TileDrawing.DrawSingleTile
DrawSingleTile()
void TileDrawing.DrawSingleTile (TileDrawInfo drawData, bool solidLayer, int waterStyleOverride, Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY) inline private
     {
         drawData.tileCache = Main.tile[tileX, tileY];
         drawData.typeCache = drawData.tileCache.type;
         drawData.tileFrameX = drawData.tileCache.frameX;
         drawData.tileFrameY = drawData.tileCache.frameY;
         drawData.tileLight = Lighting.GetColor(tileX, tileY);
         if (drawData.tileCache.liquid > 0 && drawData.tileCache.type == 518)
         {
             return;
         }
         GetTileDrawData(tileX, tileY, drawData.tileCache, drawData.typeCache, ref drawData.tileFrameX, ref drawData.tileFrameY, out drawData.tileWidth, out drawData.tileHeight, out drawData.tileTop, out drawData.halfBrickHeight, out drawData.addFrX, out drawData.addFrY, out drawData.tileSpriteEffect, out drawData.glowTexture, out drawData.glowSourceRect, out drawData.glowColor);
         drawData.drawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY);
         Texture2D highlightTexture = null;
         Rectangle empty = Rectangle.Empty;
         Color highlightColor = Color.Transparent;
         if (TileID.Sets.HasOutlines[drawData.typeCache])
         {
             GetTileOutlineInfo(tileX, tileY, drawData.typeCache, ref drawData.tileLight, ref highlightTexture, ref highlightColor);
         }
         if (_localPlayer.dangerSense && IsTileDangerous(_localPlayer, drawData.tileCache, drawData.typeCache))
         {
             if (drawData.tileLight.R < byte.MaxValue)
             {
                 drawData.tileLight.R = byte.MaxValue;
             }
             if (drawData.tileLight.G < 50)
             {
                 drawData.tileLight.G = 50;
             }
             if (drawData.tileLight.B < 50)
             {
                 drawData.tileLight.B = 50;
             }
             if (_isActiveAndNotPaused && _rand.Next(30) == 0)
             {
                 int num = Dust.NewDust(new Vector2(tileX * 16, tileY * 16), 16, 16, 60, 0f, 0f, 100, default(Color), 0.3f);
                 _dust[num].fadeIn = 1f;
                 _dust[num].velocity *= 0.1f;
                 _dust[num].noLight = true;
                 _dust[num].noGravity = true;
             }
         }
         if (_localPlayer.findTreasure && Main.IsTileSpelunkable(drawData.typeCache, drawData.tileFrameX, drawData.tileFrameY))
         {
             if (drawData.tileLight.R < 200)
             {
                 drawData.tileLight.R = 200;
             }
             if (drawData.tileLight.G < 170)
             {
                 drawData.tileLight.G = 170;
             }
             if (_isActiveAndNotPaused && _rand.Next(60) == 0)
             {
                 int num2 = Dust.NewDust(new Vector2(tileX * 16, tileY * 16), 16, 16, 204, 0f, 0f, 150, default(Color), 0.3f);
                 _dust[num2].fadeIn = 1f;
                 _dust[num2].velocity *= 0.1f;
                 _dust[num2].noLight = true;
             }
         }
         if (_localPlayer.biomeSight)
         {
             Color sightColor = Color.White;
             if (Main.IsTileBiomeSightable(drawData.typeCache, drawData.tileFrameX, drawData.tileFrameY, ref sightColor))
             {
                 if (drawData.tileLight.R < sightColor.R)
                 {
                     drawData.tileLight.R = sightColor.R;
                 }
                 if (drawData.tileLight.G < sightColor.G)
                 {
                     drawData.tileLight.G = sightColor.G;
                 }
                 if (drawData.tileLight.B < sightColor.B)
                 {
                     drawData.tileLight.B = sightColor.B;
                 }
                 if (_isActiveAndNotPaused && _rand.Next(480) == 0)
                 {
                     Color newColor = sightColor;
                     int num3 = Dust.NewDust(new Vector2(tileX * 16, tileY * 16), 16, 16, 267, 0f, 0f, 150, newColor, 0.3f);
                     _dust[num3].noGravity = true;
                     _dust[num3].fadeIn = 1f;
                     _dust[num3].velocity *= 0.1f;
                     _dust[num3].noLightEmittence = true;
                 }
             }
         }
         if (_isActiveAndNotPaused)
         {
             if (!Lighting.UpdateEveryFrame || new FastRandom(Main.TileFrameSeed).WithModifier(tileX, tileY).Next(4) == 0)
             {
                 DrawTiles_EmitParticles(tileY, tileX, drawData.tileCache, drawData.typeCache, drawData.tileFrameX, drawData.tileFrameY, drawData.tileLight);
             }
             drawData.tileLight = DrawTiles_GetLightOverride(tileY, tileX, drawData.tileCache, drawData.typeCache, drawData.tileFrameX, drawData.tileFrameY, drawData.tileLight);
         }
         bool flag = false;
         if (drawData.tileLight.R >= 1 || drawData.tileLight.G >= 1 || drawData.tileLight.B >= 1)
         {
             flag = true;
         }
         if (drawData.tileCache.wall > 0 && (drawData.tileCache.wall == 318 || drawData.tileCache.fullbrightWall()))
         {
             flag = true;
         }
         flag &= IsVisible(drawData.tileCache);
         CacheSpecialDraws_Part1(tileX, tileY, drawData.typeCache, drawData.tileFrameX, drawData.tileFrameY, !flag);
         CacheSpecialDraws_Part2(tileX, tileY, drawData, !flag);
         if (drawData.typeCache == 72 && drawData.tileFrameX >= 36)
         {
             int num4 = 0;
             if (drawData.tileFrameY == 18)
             {
                 num4 = 1;
             }
             else if (drawData.tileFrameY == 36)
             {
                 num4 = 2;
             }
             Main.spriteBatch.Draw(TextureAssets.ShroomCap.Value, new Vector2(tileX * 16 - (int)screenPosition.X - 22, tileY * 16 - (int)screenPosition.Y - 26) + screenOffset, new Rectangle(num4 * 62, 0, 60, 42), Lighting.GetColor(tileX, tileY), 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
         }
         Rectangle rectangle = new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, drawData.tileWidth, drawData.tileHeight - drawData.halfBrickHeight);
         Vector2 vector = new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)drawData.tileWidth - 16f) / 2f, tileY * 16 - (int)screenPosition.Y + drawData.tileTop + drawData.halfBrickHeight) + screenOffset;
         if (!flag)
         {
             return;
         }
         drawData.colorTint = Color.White;
         drawData.finalColor = GetFinalLight(drawData.tileCache, drawData.typeCache, drawData.tileLight, drawData.colorTint);
         switch (drawData.typeCache)
         {
         case 136:
             switch (drawData.tileFrameX / 18)
             {
             case 1:
                 vector.X += -2f;
                 break;
             case 2:
                 vector.X += 2f;
                 break;
             }
             break;
         case 442:
         {
             int num7 = drawData.tileFrameX / 22;
             if (num7 == 3)
             {
                 vector.X += 2f;
             }
             break;
         }
         case 51:
             drawData.finalColor = drawData.tileLight * 0.5f;
             break;
         case 160:
         case 692:
         {
             Color color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB, 255);
             if (drawData.tileCache.inActive())
             {
                 color = drawData.tileCache.actColor(color);
             }
             drawData.finalColor = color;
             break;
         }
         case 129:
         {
             drawData.finalColor = new Color(255, 255, 255, 100);
             int num6 = 2;
             if (drawData.tileFrameX >= 324)
             {
                 drawData.finalColor = Color.Transparent;
             }
             if (drawData.tileFrameY < 36)
             {
                 vector.Y += num6 * (drawData.tileFrameY == 0).ToDirectionInt();
             }
             else
             {
                 vector.X += num6 * (drawData.tileFrameY == 36).ToDirectionInt();
             }
             break;
         }
         case 272:
         {
             int num5 = Main.tileFrame[drawData.typeCache];
             num5 += tileX % 2;
             num5 += tileY % 2;
             num5 += tileX % 3;
             num5 += tileY % 3;
             num5 %= 2;
             num5 *= 90;
             drawData.addFrY += num5;
             rectangle.Y += num5;
             break;
         }
         case 80:
         {
             WorldGen.GetCactusType(tileX, tileY, drawData.tileFrameX, drawData.tileFrameY, out var evil, out var good, out var crimson);
             if (evil)
             {
                 rectangle.Y += 54;
             }
             if (good)
             {
                 rectangle.Y += 108;
             }
             if (crimson)
             {
                 rectangle.Y += 162;
             }
             break;
         }
         case 83:
             drawData.drawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY);
             break;
         case 323:
             if (drawData.tileCache.frameX <= 132 && drawData.tileCache.frameX >= 88)
             {
                 return;
             }
             vector.X += drawData.tileCache.frameY;
             break;
         case 114:
             if (drawData.tileFrameY > 0)
             {
                 rectangle.Height += 2;
             }
             break;
         }
         if (drawData.typeCache == 314)
         {
             DrawTile_MinecartTrack(screenPosition, screenOffset, tileX, tileY, drawData);
         }
         else if (drawData.typeCache == 171)
         {
             DrawXmasTree(screenPosition, screenOffset, tileX, tileY, drawData);
         }
         else
         {
             DrawBasicTile(screenPosition, screenOffset, tileX, tileY, drawData, rectangle, vector);
         }
         if (Main.tileGlowMask[drawData.tileCache.type] != -1)
         {
             short num8 = Main.tileGlowMask[drawData.tileCache.type];
             if (TextureAssets.GlowMask.IndexInRange(num8))
             {
                 drawData.drawTexture = TextureAssets.GlowMask[num8].Value;
             }
             double num9 = Main.timeForVisualEffects * 0.08;
             Color color2 = Color.White;
             bool flag2 = false;
             switch (drawData.tileCache.type)
             {
             case 633:
                 color2 = Color.Lerp(Color.White, drawData.finalColor, 0.75f);
                 break;
             case 659:
             case 667:
                 color2 = LiquidRenderer.GetShimmerGlitterColor(top: true, tileX, tileY);
                 break;
             case 350:
                 color2 = new Color(new Vector4((float)((0.0 - Math.Cos(((int)(num9 / 6.283) % 3 == 1) ? num9 : 0.0)) * 0.2 + 0.2)));
                 break;
             case 381:
             case 517:
             case 687:
                 color2 = _lavaMossGlow;
                 break;
             case 534:
             case 535:
             case 689:
                 color2 = _kryptonMossGlow;
                 break;
             case 536:
             case 537:
             case 690:
                 color2 = _xenonMossGlow;
                 break;
             case 539:
             case 540:
             case 688:
                 color2 = _argonMossGlow;
                 break;
             case 625:
             case 626:
             case 691:
                 color2 = _violetMossGlow;
                 break;
             case 627:
             case 628:
             case 692:
                 color2 = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                 break;
             case 370:
             case 390:
                 color2 = _meteorGlow;
                 break;
             case 391:
                 color2 = new Color(250, 250, 250, 200);
                 break;
             case 209:
                 color2 = PortalHelper.GetPortalColor(Main.myPlayer, (drawData.tileCache.frameX >= 288) ? 1 : 0);
                 break;
             case 429:
             case 445:
                 drawData.drawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY);
                 drawData.addFrY = 18;
                 break;
             case 129:
             {
                 if (drawData.tileFrameX < 324)
                 {
                     flag2 = true;
                     break;
                 }
                 drawData.drawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY);
                 color2 = Main.hslToRgb(0.7f + (float)Math.Sin((float)Math.PI * 2f * Main.GlobalTimeWrappedHourly * 0.16f + (float)tileX * 0.3f + (float)tileY * 0.7f) * 0.16f, 1f, 0.5f);
                 color2.A /= 2;
                 color2 *= 0.3f;
                 int num10 = 72;
                 for (float num11 = 0f; num11 < (float)Math.PI * 2f; num11 += (float)Math.PI / 2f)
                 {
                     Main.spriteBatch.Draw(drawData.drawTexture, vector + num11.ToRotationVector2() * 2f, new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY + num10, drawData.tileWidth, drawData.tileHeight), color2, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                 }
                 color2 = new Color(255, 255, 255, 100);
                 break;
             }
             }
             if (!flag2)
             {
                 if (drawData.tileCache.slope() == 0 && !drawData.tileCache.halfBrick())
                 {
                     Main.spriteBatch.Draw(drawData.drawTexture, vector, new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, drawData.tileWidth, drawData.tileHeight), color2, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
                 }
                 else if (drawData.tileCache.halfBrick())
                 {
                     Main.spriteBatch.Draw(drawData.drawTexture, vector, rectangle, color2, 0f, _zero, 1f, SpriteEffects.None, 0f);
                 }
                 else if (TileID.Sets.Platforms[drawData.tileCache.type])
                 {
                     Main.spriteBatch.Draw(drawData.drawTexture, vector, rectangle, color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                     if (drawData.tileCache.slope() == 1 && Main.tile[tileX + 1, tileY + 1].active() && Main.tileSolid[Main.tile[tileX + 1, tileY + 1].type] && Main.tile[tileX + 1, tileY + 1].slope() != 2 && !Main.tile[tileX + 1, tileY + 1].halfBrick() && (!Main.tile[tileX, tileY + 1].active() || (Main.tile[tileX, tileY + 1].blockType() != 0 && Main.tile[tileX, tileY + 1].blockType() != 5) || (!TileID.Sets.BlocksStairs[Main.tile[tileX, tileY + 1].type] && !TileID.Sets.BlocksStairsAbove[Main.tile[tileX, tileY + 1].type])))
                     {
                         Rectangle value = new Rectangle(198, drawData.tileFrameY, 16, 16);
                         if (TileID.Sets.Platforms[Main.tile[tileX + 1, tileY + 1].type] && Main.tile[tileX + 1, tileY + 1].slope() == 0)
{
                             value.X = 324;
                         }
                         Main.spriteBatch.Draw(drawData.drawTexture, vector + new Vector2(0f, 16f), value, color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                     }
                     else if (drawData.tileCache.slope() == 2 && Main.tile[tileX - 1, tileY + 1].active() && Main.tileSolid[Main.tile[tileX - 1, tileY + 1].type] && Main.tile[tileX - 1, tileY + 1].slope() != 1 && !Main.tile[tileX - 1, tileY + 1].halfBrick() && (!Main.tile[tileX, tileY + 1].active() || (Main.tile[tileX, tileY + 1].blockType() != 0 && Main.tile[tileX, tileY + 1].blockType() != 4) || (!TileID.Sets.BlocksStairs[Main.tile[tileX, tileY + 1].type] && !TileID.Sets.BlocksStairsAbove[Main.tile[tileX, tileY + 1].type])))
                     {
                         Rectangle value2 = new Rectangle(162, drawData.tileFrameY, 16, 16);
                         if (TileID.Sets.Platforms[Main.tile[tileX - 1, tileY + 1].type] && Main.tile[tileX - 1, tileY + 1].slope() == 0)
{
                             value2.X = 306;
                         }
                         Main.spriteBatch.Draw(drawData.drawTexture, vector + new Vector2(0f, 16f), value2, color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                     }
                 }
                 else if (TileID.Sets.HasSlopeFrames[drawData.tileCache.type])
                 {
                     Main.spriteBatch.Draw(drawData.drawTexture, vector, new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, 16, 16), color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 }
                 else
                 {
                     int num12 = drawData.tileCache.slope();
                     int num13 = 2;
                     for (int i = 0; i < 8; i++)
                     {
                         int num14 = i * -2;
                         int num15 = 16 - i * 2;
                         int num16 = 16 - num15;
                         int num17;
                         switch (num12)
{
                         case 1:
                             num14 = 0;
                             num17 = i * 2;
                             num15 = 14 - i * 2;
                             num16 = 0;
                             break;
                         case 2:
                             num14 = 0;
                             num17 = 16 - i * 2 - 2;
                             num15 = 14 - i * 2;
                             num16 = 0;
                             break;
                         case 3:
                             num17 = i * 2;
                             break;
                         default:
                             num17 = 16 - i * 2 - 2;
                             break;
                         }
                         Main.spriteBatch.Draw(drawData.drawTexture, vector + new Vector2(num17, i * num13 + num14), new Rectangle(drawData.tileFrameX + drawData.addFrX + num17, drawData.tileFrameY + drawData.addFrY + num16, num13, num15), color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                     }
                     int num18 = ((num12 <= 2) ? 14 : 0);
                     Main.spriteBatch.Draw(drawData.drawTexture, vector + new Vector2(0f, num18), new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY + num18, 16, 2), color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                 }
             }
         }
         if (drawData.glowTexture != null)
         {
             Vector2 position = new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)drawData.tileWidth - 16f) / 2f, tileY * 16 - (int)screenPosition.Y + drawData.tileTop) + screenOffset;
             if (TileID.Sets.Platforms[drawData.typeCache])
             {
                 position = vector;
             }
             Main.spriteBatch.Draw(drawData.glowTexture, position, drawData.glowSourceRect, drawData.glowColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
         }
         if (highlightTexture != null)
         {
             empty = new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, drawData.tileWidth, drawData.tileHeight);
             int num19 = 0;
             int num20 = 0;
             Main.spriteBatch.Draw(highlightTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)drawData.tileWidth - 16f) / 2f + (float)num19, tileY * 16 - (int)screenPosition.Y + drawData.tileTop + num20) + screenOffset, empty, highlightColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
         }
     }
References _argonMossGlow, _dust, _isActiveAndNotPaused, _kryptonMossGlow, _lavaMossGlow, _localPlayer, _meteorGlow, _rand, _violetMossGlow, _xenonMossGlow, _zero, Tile.actColor(), Tile.active(), TileDrawInfo.addFrX, TileDrawInfo.addFrY, Player.biomeSight, TileID.Sets.BlocksStairs, TileID.Sets.BlocksStairsAbove, Tile.blockType(), CacheSpecialDraws_Part1(), CacheSpecialDraws_Part2(), Color, TileDrawInfo.colorTint, Player.dangerSense, Main.DiscoB, Main.DiscoG, Main.DiscoR, DrawBasicTile(), TileDrawInfo.drawTexture, DrawTile_MinecartTrack(), DrawTiles_EmitParticles(), DrawTiles_GetLightOverride(), DrawXmasTree(), Dust.fadeIn, TileDrawInfo.finalColor, Player.findTreasure, Tile.frameX, Tile.frameY, Tile.fullbrightWall(), WorldGen.GetCactusType(), Lighting.GetColor(), GetFinalLight(), PortalHelper.GetPortalColor(), LiquidRenderer.GetShimmerGlitterColor(), GetTileDrawData(), GetTileDrawTexture(), GetTileOutlineInfo(), Main.GlobalTimeWrappedHourly, TileDrawInfo.glowColor, TextureAssets.GlowMask, TileDrawInfo.glowSourceRect, TileDrawInfo.glowTexture, Tile.halfBrick(), TileDrawInfo.halfBrickHeight, TileID.Sets.HasOutlines, TileID.Sets.HasSlopeFrames, Main.hslToRgb(), Tile.inActive(), Main.IsTileBiomeSightable(), IsTileDangerous(), Main.IsTileSpelunkable(), IsVisible(), Tile.liquid, Main.myPlayer, Dust.NewDust(), UnifiedRandom.Next(), FastRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, TileID.Sets.Platforms, TextureAssets.ShroomCap, Tile.slope(), Main.spriteBatch, Main.tile, TileDrawInfo.tileCache, Main.tileFrame, Main.TileFrameSeed, TileDrawInfo.tileFrameX, TileDrawInfo.tileFrameY, Main.tileGlowMask, TileDrawInfo.tileHeight, TileDrawInfo.tileLight, Main.tileSolid, TileDrawInfo.tileSpriteEffect, TileDrawInfo.tileTop, TileDrawInfo.tileWidth, Main.timeForVisualEffects, Tile.type, TileDrawInfo.typeCache, Lighting.UpdateEveryFrame, Asset< T >.Value, Dust.velocity, Tile.wall, and FastRandom.WithModifier().
Referenced by Draw().