Terraria: TileDrawing.DrawSingleTile_Flames
DrawSingleTile_Flames()
void TileDrawing.DrawSingleTile_Flames (Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY, TileDrawInfo drawData) inline private
References _zero, TileDrawInfo.addFrX, TileDrawInfo.addFrY, Main.cageFrames, Color, Main.DiscoB, Main.DiscoG, Main.DiscoR, TextureAssets.FireflyJar, TileDrawing.TileFlameData.flameColor, TileDrawing.TileFlameData.flameCount, TileDrawing.TileFlameData.flameRangeMultX, TileDrawing.TileFlameData.flameRangeMultY, TileDrawing.TileFlameData.flameRangeXMax, TileDrawing.TileFlameData.flameRangeXMin, TileDrawing.TileFlameData.flameRangeYMax, TileDrawing.TileFlameData.flameRangeYMin, TextureAssets.Flames, TileDrawing.TileFlameData.flameSeed, TileDrawing.TileFlameData.flameTexture, Tile.frameY, GetTileFlameData(), TextureAssets.GlowMask, TextureAssets.GlowSnail, Main.GraveyardVisualIntensity, TextureAssets.JellyfishBowl, Main.jellyfishCageFrame, L, TextureAssets.LightningbugJar, Main.moondialCooldown, Main.moonPhase, Main.mouseTextColor, Utils.RandomInt(), Main.spriteBatch, TextureAssets.SunAltar, Main.sundialCooldown, Main.tile, TileDrawInfo.tileCache, Main.tileFlame, Main.TileFrameSeed, TileDrawInfo.tileFrameX, TileDrawInfo.tileFrameY, TileDrawInfo.tileHeight, TileDrawInfo.tileSpriteEffect, TileDrawInfo.tileTop, TileDrawInfo.tileWidth, TextureAssets.Timer, Tile.type, TileDrawInfo.typeCache, Asset< T >.Value, and TextureAssets.XmasLight.
Referenced by DrawBasicTile().