Terraria: TileDrawing.EmitLiquidDrops
EmitLiquidDrops()
void TileDrawing.EmitLiquidDrops (int j, int i, Tile tileCache, ushort typeCache) inline private
     {
         int num = 60;
         switch (typeCache)
         {
         case 374:
             num = 120;
             break;
         case 375:
             num = 180;
             break;
         case 461:
             num = 180;
             break;
         }
         if (tileCache.liquid != 0 || _rand.Next(num * 2) != 0)
         {
             return;
         }
         Rectangle rectangle = new Rectangle(i * 16, j * 16, 16, 16);
         rectangle.X -= 34;
         rectangle.Width += 68;
         rectangle.Y -= 100;
         rectangle.Height = 400;
         for (int k = 0; k < 600; k++)
         {
             if (_gore[k].active && ((_gore[k].type >= 706 && _gore[k].type <= 717) || _gore[k].type == 943 || _gore[k].type == 1147 || (_gore[k].type >= 1160 && _gore[k].type <= 1162)))
             {
                 Rectangle value = new Rectangle((int)_gore[k].position.X, (int)_gore[k].position.Y, 16, 16);
                 if (rectangle.Intersects(value))
                 {
                     return;
                 }
             }
         }
         Vector2 position = new Vector2(i * 16, j * 16);
         int type = 706;
         if (Main.waterStyle == 14)
         {
             type = 706;
         }
         else if (Main.waterStyle == 13)
         {
             type = 706;
         }
         else if (Main.waterStyle == 12)
         {
             type = 1147;
         }
         else if (Main.waterStyle > 1)
         {
             type = 706 + Main.waterStyle - 1;
         }
         if (typeCache == 374)
         {
             type = 716;
         }
         if (typeCache == 375)
         {
             type = 717;
         }
         if (typeCache == 461)
         {
             type = 943;
             if (Main.player[Main.myPlayer].ZoneCorrupt)
             {
                 type = 1160;
             }
             if (Main.player[Main.myPlayer].ZoneCrimson)
             {
                 type = 1161;
             }
             if (Main.player[Main.myPlayer].ZoneHallow)
             {
                 type = 1162;
             }
         }
         int num2 = Gore.NewGore(position, default(Vector2), type);
         _gore[num2].velocity *= 0f;
     }
References _gore, _rand, Tile.liquid, Main.myPlayer, Gore.NewGore(), UnifiedRandom.Next(), Main.player, Gore.position, Gore.velocity, Main.waterStyle, Player.ZoneCorrupt, Player.ZoneCrimson, and Player.ZoneHallow.
Referenced by Draw().