Terraria: TileDrawing.PostDrawTiles
PostDrawTiles()
void TileDrawing.PostDrawTiles (bool solidLayer, bool forRenderTargets, bool intoRenderTargets) inline
     {
         if (!solidLayer && !intoRenderTargets)
         {
             Main.spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
             DrawMultiTileVines();
             DrawMultiTileGrass();
             DrawVoidLenses();
             DrawTeleportationPylons();
             DrawMasterTrophies();
             DrawGrass();
             DrawAnyDirectionalGrass();
             DrawTrees();
             DrawVines();
             DrawReverseVines();
             Main.spriteBatch.End();
         }
         if (solidLayer && !intoRenderTargets)
         {
             DrawEntities_HatRacks();
             DrawEntities_DisplayDolls();
         }
     }
References Main.DefaultSamplerState, DrawAnyDirectionalGrass(), DrawEntities_DisplayDolls(), DrawEntities_HatRacks(), DrawGrass(), DrawMasterTrophies(), DrawMultiTileGrass(), DrawMultiTileVines(), DrawReverseVines(), DrawTeleportationPylons(), DrawTrees(), DrawVines(), DrawVoidLenses(), Main.Rasterizer, Main.spriteBatch, and Main.Transform.
Referenced by Main.DrawTileEntities().