Terraria: System.Security.Cryptography.IncrementalHash.Dispose
Dispose()
void System.Security.Cryptography.IncrementalHash.Dispose () inline
Implements System.IDisposable.
Definition at line 180 of file IncrementalHash.cs.
    {
        _disposed = true;
        if (_hash != null)
        {
            _hash.Dispose();
            _hash = null;
        }
        if (_hmac != null)
        {
            _hmac.Dispose(disposing: true);
            _hmac = null;
        }
    }
References System.Security.Cryptography.IncrementalHash._disposed, System.Security.Cryptography.IncrementalHash._hash, System.Security.Cryptography.IncrementalHash._hmac, Internal.Cryptography.HashProvider.Dispose(), and Internal.Cryptography.HMACCommon.Dispose().
Referenced by System.Security.Cryptography.Pkcs.Pkcs12Kdf.Derive(), System.Security.Cryptography.MD5CryptoServiceProvider.Dispose(), System.Security.Cryptography.SHA1CryptoServiceProvider.Dispose(), System.Security.Cryptography.SHA256CryptoServiceProvider.Dispose(), System.Security.Cryptography.SHA384CryptoServiceProvider.Dispose(), and System.Security.Cryptography.SHA512CryptoServiceProvider.Dispose().