Terraria: System.Security.Cryptography.IncrementalHash.CreateHash
CreateHash()
static IncrementalHash System.Security.Cryptography.IncrementalHash.CreateHash (HashAlgorithmName hashAlgorithm) inline static
Definition at line 195 of file IncrementalHash.cs.
    {
        if (string.IsNullOrEmpty(hashAlgorithm.Name))
        {
            throw new ArgumentException(System.SR.Cryptography_HashAlgorithmNameNullOrEmpty, "hashAlgorithm");
        }
        return new IncrementalHash(hashAlgorithm, HashProviderDispenser.CreateHashProvider(hashAlgorithm.Name));
    }
References System.Security.Cryptography.IncrementalHash.IncrementalHash(), Internal.Cryptography.HashProviderDispenser.CreateHashProvider(), System.SR.Cryptography_HashAlgorithmNameNullOrEmpty, and System.Security.Cryptography.HashAlgorithmName.Name.
Referenced by System.Security.Cryptography.MD5CryptoServiceProvider.MD5CryptoServiceProvider(), System.Security.Cryptography.SHA1CryptoServiceProvider.SHA1CryptoServiceProvider(), System.Security.Cryptography.SHA256CryptoServiceProvider.SHA256CryptoServiceProvider(), System.Security.Cryptography.SHA384CryptoServiceProvider.SHA384CryptoServiceProvider(), System.Security.Cryptography.SHA512CryptoServiceProvider.SHA512CryptoServiceProvider(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.Derive(), System.Security.Cryptography.X509Certificates.X509Certificate.GetCertHash(), System.Security.Cryptography.RsaPaddingProcessor.OpenProcessor(), System.Security.Cryptography.RsaPaddingProcessor.PadOaep(), and System.Security.Cryptography.X509Certificates.X509Certificate.TryGetCertHash().