Terraria: System.Security.Cryptography.IncrementalHash.AppendData
AppendData() [1/3]
void System.Security.Cryptography.IncrementalHash.AppendData (byte[] data) inline
Definition at line 34 of file IncrementalHash.cs.
    {
        if (data == null)
        {
            throw new ArgumentNullException("data");
        }
        AppendData(new ReadOnlySpan<byte>(data));
    }
References System.Security.Cryptography.IncrementalHash.AppendData().
Referenced by System.Security.Cryptography.IncrementalHash.AppendData(), System.Security.Cryptography.IncrementalHash.AppendData(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.Derive(), System.Security.Cryptography.HKDF.Expand(), System.Security.Cryptography.MD5CryptoServiceProvider.HashCore(), System.Security.Cryptography.SHA1CryptoServiceProvider.HashCore(), System.Security.Cryptography.SHA256CryptoServiceProvider.HashCore(), System.Security.Cryptography.SHA384CryptoServiceProvider.HashCore(), System.Security.Cryptography.SHA512CryptoServiceProvider.HashCore(), System.Security.Cryptography.MD5CryptoServiceProvider.HashCore(), System.Security.Cryptography.SHA1CryptoServiceProvider.HashCore(), System.Security.Cryptography.SHA256CryptoServiceProvider.HashCore(), System.Security.Cryptography.SHA384CryptoServiceProvider.HashCore(), System.Security.Cryptography.SHA512CryptoServiceProvider.HashCore(), System.Security.Cryptography.RsaPaddingProcessor.Mgf1(), and System.Security.Cryptography.PasswordBasedEncryption.Pbkdf1().