Terraria: System.IO.FileStream.ValidateReadWriteArgs
ValidateReadWriteArgs()
void System.IO.FileStream.ValidateReadWriteArgs (byte[] buffer, int offset, int count) inline private inherited
Definition at line 374 of file FileStream.cs.
    {
        Stream.ValidateBufferArguments(buffer, offset, count);
        if (_strategy.IsClosed)
        {
            ThrowHelper.ThrowObjectDisposedException_FileClosed();
        }
    }
References System.IO.FileStream._strategy, System.buffer, System.count, System.IO.Strategies.FileStreamStrategy.IsClosed, System.offset, System.ThrowHelper.ThrowObjectDisposedException_FileClosed(), and System.IO.Stream.ValidateBufferArguments().
Referenced by System.IO.FileStream.Read(), and System.IO.FileStream.Write().