Terraria: System.IO.FileStream.FileStream
FileStream() [14/15]
System.IO.FileStream.FileStream (string path, FileStreamOptions options) inline
Definition at line 187 of file FileStream.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path", SR.ArgumentNull_Path);
        }
        if (path.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyPath, "path");
        }
        if (options == null)
        {
            throw new ArgumentNullException("options");
        }
        if ((options.Access & FileAccess.Read) != 0 && options.Mode == FileMode.Append)
        {
            throw new ArgumentException(SR.Argument_InvalidAppendMode, "options");
        }
        if ((options.Access & FileAccess.Write) == 0 && (options.Mode == FileMode.Truncate || options.Mode == FileMode.CreateNew || options.Mode == FileMode.Create || options.Mode == FileMode.Append))
        {
            throw new ArgumentException(SR.Format(SR.Argument_InvalidFileModeAndAccessCombo, options.Mode, options.Access), "options");
        }
        if (options.PreallocationSize > 0)
        {
            FileStreamHelpers.ValidateArgumentsForPreallocation(options.Mode, options.Access);
        }
        FileStreamHelpers.SerializationGuard(options.Access);
        _strategy = FileStreamHelpers.ChooseStrategy(this, path, options.Mode, options.Access, options.Share, options.BufferSize, options.Options, options.PreallocationSize);
    }
References System.IO.FileStream._strategy, System.SR.Argument_EmptyPath, System.SR.Argument_InvalidAppendMode, System.SR.Argument_InvalidFileModeAndAccessCombo, System.SR.ArgumentNull_Path, System.IO.Strategies.FileStreamHelpers.ChooseStrategy(), System.SR.Format(), System.options, System.IO.Strategies.FileStreamHelpers.SerializationGuard(), and System.IO.Strategies.FileStreamHelpers.ValidateArgumentsForPreallocation().