Terraria: System.IO.FileStream.SetLength
SetLength()
override void System.IO.FileStream.SetLength (long value) inline inherited
Definition at line 383 of file FileStream.cs.
    {
        if (value < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.value, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        else if (_strategy.IsClosed)
        {
            ThrowHelper.ThrowObjectDisposedException_FileClosed();
        }
        else if (!CanSeek)
        {
            ThrowHelper.ThrowNotSupportedException_UnseekableStream();
        }
        else if (!CanWrite)
        {
            ThrowHelper.ThrowNotSupportedException_UnwritableStream();
        }
        _strategy.SetLength(value);
    }
References System.IO.FileStream._strategy, System.IO.FileStream.CanSeek, System.IO.FileStream.CanWrite, System.IO.Strategies.FileStreamStrategy.IsClosed, System.IO.Stream.SetLength(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), System.ThrowHelper.ThrowNotSupportedException_UnseekableStream(), System.ThrowHelper.ThrowNotSupportedException_UnwritableStream(), System.ThrowHelper.ThrowObjectDisposedException_FileClosed(), and System.value.
Referenced by System.IO.IsolatedStorage.IsolatedStorageFileStream.SetLength().