Terraria: System.IO.FileStream.ValidateHandle
ValidateHandle() [1/2]
static void System.IO.FileStream.ValidateHandle (SafeFileHandle handle, FileAccess access, int bufferSize) inline static private inherited
Definition at line 107 of file FileStream.cs.
    {
        if (handle.IsInvalid)
        {
            throw new ArgumentException(SR.Arg_InvalidHandle, "handle");
        }
        if (access < FileAccess.Read || access > FileAccess.ReadWrite)
        {
            throw new ArgumentOutOfRangeException("access", SR.ArgumentOutOfRange_Enum);
        }
        if (bufferSize < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException_NeedNonNegNum("bufferSize");
        }
        else if (handle.IsClosed)
        {
            ThrowHelper.ThrowObjectDisposedException_FileClosed();
        }
    }
References System.SR.Arg_InvalidHandle, System.SR.ArgumentOutOfRange_Enum, System.handle, System.ThrowHelper.ThrowArgumentOutOfRangeException_NeedNonNegNum(), and System.ThrowHelper.ThrowObjectDisposedException_FileClosed().
Referenced by System.IO.FileStream.FileStream(), System.IO.FileStream.FileStream(), System.IO.FileStream.FileStream(), and System.IO.FileStream.ValidateHandle().