Terraria: System.Xml.Xsl.XmlQualifiedNameTest.HasIntersection
HasIntersection()
bool System.Xml.Xsl.XmlQualifiedNameTest.HasIntersection (XmlQualifiedNameTest other) inline
Definition at line 63 of file XmlQualifiedNameTest.cs.
    {
        if (IsNamespaceSubsetOf(other) || other.IsNamespaceSubsetOf(this))
        {
            if (!IsNameSubsetOf(other))
            {
                return other.IsNameSubsetOf(this);
            }
            return true;
        }
        return false;
    }
References System.Xml.Xsl.XmlQualifiedNameTest.IsNamespaceSubsetOf(), System.Xml.Xsl.XmlQualifiedNameTest.IsNameSubsetOf(), and System.other.
Referenced by System.Xml.Xsl.XmlQueryType.HasIntersectionItemType().