Terraria: System.IO.FileStream.BeginRead
BeginRead() [1/2]
override IAsyncResult System.IO.FileStream.BeginRead (byte[] buffer, int offset, int count, AsyncCallback? callback, object? state) inline virtual inherited
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.IsolatedStorage.IsolatedStorageFileStream.
Definition at line 441 of file FileStream.cs.
    {
        Stream.ValidateBufferArguments(buffer, offset, count);
        if (_strategy.IsClosed)
        {
            ThrowHelper.ThrowObjectDisposedException_FileClosed();
        }
        else if (!CanRead)
        {
            ThrowHelper.ThrowNotSupportedException_UnreadableStream();
        }
        return _strategy.BeginRead(buffer, offset, count, callback, state);
    }
References System.IO.FileStream._strategy, System.IO.Stream.BeginRead(), System.buffer, System.IO.FileStream.CanRead, System.count, System.IO.Strategies.FileStreamStrategy.IsClosed, System.offset, System.state, System.ThrowHelper.ThrowNotSupportedException_UnreadableStream(), System.ThrowHelper.ThrowObjectDisposedException_FileClosed(), and System.IO.Stream.ValidateBufferArguments().
Referenced by System.IO.IsolatedStorage.IsolatedStorageFileStream.BeginRead().