Terraria: System.IO.FileStream.FileStream
FileStream() [4/15]
System.IO.FileStream.FileStream (IntPtr handle, FileAccess access, bool ownsHandle, int bufferSize, bool isAsync) inline
Definition at line 92 of file FileStream.cs.
    {
        SafeFileHandle safeFileHandle = new SafeFileHandle(handle, ownsHandle);
        try
        {
            ValidateHandle(safeFileHandle, access, bufferSize, isAsync);
            _strategy = FileStreamHelpers.ChooseStrategy(this, safeFileHandle, access, bufferSize, isAsync);
        }
        catch
        {
            GC.SuppressFinalize(safeFileHandle);
            throw;
        }
    }
References System.IO.FileStream._strategy, System.IO.Strategies.FileStreamHelpers.ChooseStrategy(), System.handle, System.IO.FileStream.SafeFileHandle, System.GC.SuppressFinalize(), and System.IO.FileStream.ValidateHandle().