Terraria: System.IO.FileStream.WriteAsync
WriteAsync() [3/3]
override ValueTask System.IO.FileStream.WriteAsync (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual inherited
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.IsolatedStorage.IsolatedStorageFileStream.
Definition at line 343 of file FileStream.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            return ValueTask.FromCanceled(cancellationToken);
        }
        if (!_strategy.CanWrite)
        {
            if (_strategy.IsClosed)
            {
                ThrowHelper.ThrowObjectDisposedException_FileClosed();
            }
            ThrowHelper.ThrowNotSupportedException_UnwritableStream();
        }
        return _strategy.WriteAsync(buffer, cancellationToken);
    }
References System.IO.FileStream._strategy, System.buffer, System.cancellationToken, System.IO.Stream.CanWrite, System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.IO.Strategies.FileStreamStrategy.IsClosed, System.ThrowHelper.ThrowNotSupportedException_UnwritableStream(), System.ThrowHelper.ThrowObjectDisposedException_FileClosed(), and System.IO.Stream.WriteAsync().