Terraria: System.IO.FileStream.WriteAsync
WriteAsync() [2/3]
override Task System.IO.FileStream.WriteAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.IsolatedStorage.IsolatedStorageFileStream, and System.Net.WebFileStream.
Definition at line 325 of file FileStream.cs.
    {
        Stream.ValidateBufferArguments(buffer, offset, count);
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled(cancellationToken);
        }
        if (!_strategy.CanWrite)
        {
            if (_strategy.IsClosed)
            {
                ThrowHelper.ThrowObjectDisposedException_FileClosed();
            }
            ThrowHelper.ThrowNotSupportedException_UnwritableStream();
        }
        return _strategy.WriteAsync(buffer, offset, count, cancellationToken);
    }
References System.IO.FileStream._strategy, System.buffer, System.cancellationToken, System.IO.Stream.CanWrite, System.count, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.IO.Strategies.FileStreamStrategy.IsClosed, System.offset, System.ThrowHelper.ThrowNotSupportedException_UnwritableStream(), System.ThrowHelper.ThrowObjectDisposedException_FileClosed(), System.IO.Stream.ValidateBufferArguments(), and System.IO.Stream.WriteAsync().
Referenced by System.IO.IsolatedStorage.IsolatedStorageFileStream.WriteAsync(), and System.IO.IsolatedStorage.IsolatedStorageFileStream.WriteAsync().