Terraria: System.Text.RegularExpressions.ThrowHelper.GetStringForExceptionArgument
GetStringForExceptionArgument()
static string System.Text.RegularExpressions.ThrowHelper.GetStringForExceptionArgument (ExceptionArgument arg) inline static private
Definition at line 37 of file ThrowHelper.cs.
    {
        return arg switch
        {
            ExceptionArgument.assemblyname => "assemblyname",
            ExceptionArgument.array => "array",
            ExceptionArgument.arrayIndex => "arrayIndex",
            ExceptionArgument.count => "count",
            ExceptionArgument.evaluator => "evaluator",
            ExceptionArgument.i => "i",
            ExceptionArgument.inner => "inner",
            ExceptionArgument.input => "input",
            ExceptionArgument.length => "length",
            ExceptionArgument.matchTimeout => "matchTimeout",
            ExceptionArgument.name => "name",
            ExceptionArgument.options => "options",
            ExceptionArgument.pattern => "pattern",
            ExceptionArgument.regexinfos => "regexinfos",
            ExceptionArgument.replacement => "replacement",
            ExceptionArgument.startat => "startat",
            ExceptionArgument.str => "str",
            ExceptionArgument.value => "value",
            _ => null,
        };
    }
Referenced by System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(), System.Text.RegularExpressions.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.Text.RegularExpressions.ThrowHelper.ThrowArgumentOutOfRangeException().