Terraria: System.Text.RegularExpressions.ThrowHelper.GetStringForExceptionResource
GetStringForExceptionResource()
static string System.Text.RegularExpressions.ThrowHelper.GetStringForExceptionResource (ExceptionResource resource) inline static private
Definition at line 63 of file ThrowHelper.cs.
    {
        return resource switch
        {
            ExceptionResource.BeginIndexNotNegative => System.SR.BeginIndexNotNegative,
            ExceptionResource.CountTooSmall => System.SR.CountTooSmall,
            ExceptionResource.LengthNotNegative => System.SR.LengthNotNegative,
            ExceptionResource.OnlyAllowedOnce => System.SR.OnlyAllowedOnce,
            ExceptionResource.ReplacementError => System.SR.ReplacementError,
            _ => null,
        };
    }
References System.SR.BeginIndexNotNegative, System.SR.CountTooSmall, System.SR.LengthNotNegative, System.SR.OnlyAllowedOnce, and System.SR.ReplacementError.
Referenced by System.Text.RegularExpressions.ThrowHelper.CreateArgumentException(), System.Text.RegularExpressions.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.Text.RegularExpressions.ThrowHelper.ThrowNotSupportedException().