Terraria: System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException
ThrowArgumentNullException()
static void System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException (ExceptionArgument arg) inline static package
Definition at line 14 of file ThrowHelper.cs.
    {
        throw new ArgumentNullException(GetStringForExceptionArgument(arg));
    }
References System.Text.RegularExpressions.ThrowHelper.GetStringForExceptionArgument().
Referenced by System.Text.RegularExpressions.Regex.CompileToAssembly(), System.Text.RegularExpressions.CaptureCollection.CopyTo(), System.Text.RegularExpressions.GroupCollection.CopyTo(), System.Text.RegularExpressions.CaptureCollection.CopyTo(), System.Text.RegularExpressions.GroupCollection.CopyTo(), System.Text.RegularExpressions.Regex.Escape(), System.Text.RegularExpressions.Regex.GroupNumberFromName(), System.Text.RegularExpressions.Regex.IsMatch(), System.Text.RegularExpressions.Regex.IsMatch(), System.Text.RegularExpressions.Regex.Match(), System.Text.RegularExpressions.Regex.Match(), System.Text.RegularExpressions.Regex.Match(), System.Text.RegularExpressions.Regex.Matches(), System.Text.RegularExpressions.Regex.Matches(), System.Text.RegularExpressions.Regex.Replace(), System.Text.RegularExpressions.Regex.Replace(), System.Text.RegularExpressions.Regex.Replace(), System.Text.RegularExpressions.Regex.Replace(), System.Text.RegularExpressions.Regex.Replace(), System.Text.RegularExpressions.Regex.Replace(), System.Text.RegularExpressions.Regex.Replace(), System.Text.RegularExpressions.Match.Result(), System.Text.RegularExpressions.Regex.Split(), System.Text.RegularExpressions.Regex.Split(), System.Text.RegularExpressions.Regex.Split(), System.Text.RegularExpressions.Group.Synchronized(), System.Text.RegularExpressions.Match.Synchronized(), System.Text.RegularExpressions.Regex.Unescape(), and System.Text.RegularExpressions.Regex.ValidatePattern().