Terraria: Tile.color
color() [1/2]
byte Tile.color () inline
     {
         return (byte)(sTileHeader & 0x1Fu);
     }
References sTileHeader.
Referenced by Actions.SetTileAndWallRainbowPaint.Apply(), Player.ApplyPaint(), TileLightScanner.ApplyTileLight(), TileColorCache.ApplyToBlock(), BlockColorAndCoating(), ClearBlockPaintAndCoating(), color(), NetMessage.CompressTileBlock_Inner(), WorldFile.ConvertIlluminantPaintToNewField(), CopyPaintAndCoating(), MapHelper.CreateMapTile(), NetMessage.DecompressTileBlock_Inner(), TEDisplayDoll.Draw(), HitTile.DrawFreshAnimations(), TileDrawing.DrawTiles_EmitParticles(), TileDrawing.DrawTrees(), TileDrawing.EmitLivingTreeLeaf_Below(), TileDrawing.EmitLivingTreeLeaf_Sideways(), TileDrawing.EmitTreeLeaves(), WorldGen.FinishDrunkGen(), WorldGen.FinishGetGoodWorld(), WorldGen.FinishRemixWorld(), Player.FloorVisuals(), MessageBuffer.GetData(), TileDrawing.GetTileDrawTexture(), WorldGen.GrowDungeonTree(), WorldGen.GrowPalmTree(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), WorldFile.LoadWorldTiles(), TileDrawing.MakeExtraPreparations(), WorldGen.NotTheBees(), WorldGen.PaintTheClouds(), WorldGen.PaintTheDungeon(), WorldGen.PaintTheLivingTrees(), WorldGen.PaintTheMushrooms(), WorldGen.PaintThePurityGrass(), WorldGen.PaintThePyramids(), WorldGen.PaintTheSand(), WorldGen.PaintTheTemple(), WorldGen.PaintTheTrees(), WorldGen.paintTile(), Player.PlaceThing_PaintScrapper_TryScrapping(), WorldGen.PlaceTile(), TileDrawing.PrepareForAreaDrawing(), WorldGen.ReplaceTile_DoActualReplacement_Single(), WorldFile.SaveWorldTiles(), NetMessage.SendData(), WorldGen.ShimmerMakeBiome(), WorldGen.Statue(), SmartCursorHelper.Step_PaintBrush(), SmartCursorHelper.Step_PaintScrapper(), and Minecart.TrackColors().