Terraria: Tile.Clear
Clear()
void Tile.Clear (TileDataType types) inline
     {
         if ((types & TileDataType.Tile) != 0)
         {
             type = 0;
             active(active: false);
             frameX = 0;
             frameY = 0;
         }
         if ((types & TileDataType.Wall) != 0)
         {
             wall = 0;
             wallFrameX(0);
             wallFrameY(0);
         }
         if ((types & TileDataType.TilePaint) != 0)
         {
             ClearBlockPaintAndCoating();
         }
         if ((types & TileDataType.WallPaint) != 0)
         {
             ClearWallPaintAndCoating();
         }
         if ((types & TileDataType.Liquid) != 0)
         {
             liquid = 0;
             liquidType(0);
             checkingLiquid(checkingLiquid: false);
         }
         if ((types & TileDataType.Slope) != 0)
         {
             slope(0);
             halfBrick(halfBrick: false);
         }
         if ((types & TileDataType.Wiring) != 0)
         {
             wire(wire: false);
             wire2(wire2: false);
             wire3(wire3: false);
             wire4(wire4: false);
         }
         if ((types & TileDataType.Actuator) != 0)
         {
             actuator(actuator: false);
             inActive(inActive: false);
         }
     }
References active(), actuator(), checkingLiquid(), ClearBlockPaintAndCoating(), ClearWallPaintAndCoating(), frameX, frameY, halfBrick(), inActive(), liquid, liquidType(), slope(), type, wall, wallFrameX(), wallFrameY(), wire(), wire2(), wire3(), and wire4().
Referenced by Actions.SetTile.Apply(), Actions.SetTileKeepWall.Apply(), WorldGen.DungeonEnt(), WorldGen.DungeonHalls(), WorldGen.DungeonPitTrap(), WorldGen.DungeonRoom(), WorldGen.EmptyLiquid(), and WorldGen.MakeDungeon().