Terraria: Tile.liquidType
liquidType() [2/2]
void Tile.liquidType (int liquidType) inline
     {
         switch (liquidType)
         {
         case 0:
             bTileHeader &= 159;
             break;
         case 1:
             lava(lava: true);
             break;
         case 2:
             honey(honey: true);
             break;
         case 3:
             shimmer(shimmer: true);
             break;
         }
     }
References bTileHeader, honey(), lava(), liquidType(), and shimmer().
Referenced by Player.AdjTiles(), Actions.SetLiquid.Apply(), Modifiers.HasLiquid.Apply(), WorldGen.CanUnderwaterPlantGrowHere(), WorldGen.CheckCatTail(), BallCollision.CheckForPassThrough(), WorldGen.CheckLilyPad(), Conditions.HasLava.CheckValidity(), MapHelper.CreateMapTile(), Liquid.DelWater(), NetLiquidModule.Deserialize(), TileDrawing.DrawTile_LiquidBehindTile(), WorldGen.EmptyLiquid(), MessageBuffer.GetData(), WorldGen.GrowAlch(), LiquidRenderer.InternalPrepareDraw(), Player.ItemCheck_UseBuckets(), Liquid.LiquidCheck(), TileObjectData.LiquidPlace(), WorldGen.PlaceCatTail(), GraniteBiome.PlaceGranite(), WorldGen.PlaceLilyPad(), WorldGen.PlaceLiquid(), SceneMetrics.ScanAndExportToMain(), NetMessage.SendData(), NetLiquidModule.Serialize(), NetLiquidModule.SerializeForPlayer(), Liquid.SettleWaterAt(), SmartCursorHelper.Step_EmptyBuckets(), Player.TryRecalculatingTorchLuck(), Liquid.Update(), WorldGen.WouldTileReplacementBeBlockedByLiquid(), and Wiring.XferWater().