Terraria: Tile.slope
slope() [1/2]
byte Tile.slope () inline
     {
         return (byte)((sTileHeader & 0x7000) >> 12);
     }
References sTileHeader.
Referenced by DeadMansChestBiome.ActuallyPlaceBoulderTrap(), DeadMansChestBiome.ActuallyPlaceDartTrap(), DeadMansChestBiome.ActuallyPlaceExplosive(), WorldGen.AddBuriedChest(), WorldGen.AddLifeCrystal(), Collision.AdvancedTileCollision(), Projectile.AI_026(), Projectile.AI_067_FreakingPirates(), TileLightScanner.ApplyHellLight(), TileLightScanner.ApplySurfaceLight(), blockType(), bottomSlope(), Collision.CanHit(), Collision.CanHitWithCheck(), TileObject.CanPlace(), WorldGen.Check2x2(), WorldGen.Check3x2(), WorldGen.CheckCactus(), WorldGen.CheckLilyPad(), WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), WorldGen.CheckTorch(), Clear(), ClearTile(), NetMessage.CompressTileBlock_Inner(), HiveBiome.CreateHiveTunnel(), HiveBiome.CreateStandForLarva(), NetMessage.DecompressTileBlock_Inner(), Player.DoBootsEffect_PlaceFlowersOnTile(), TileDrawing.DrawBasicTile(), HitTile.DrawFreshAnimations(), TileDrawing.DrawPartialLiquid(), TileDrawing.DrawSingleTile(), TileDrawing.DrawTile_LiquidBehindTile(), WaterfallManager.DrawWaterfall(), NPC.FindFrame(), WaterfallManager.FindWaterfalls(), WorldGen.FinishNoTraps(), WorldGen.FixHeart(), Player.FloorVisuals(), MessageBuffer.GetData(), BallCollision.GetLeftOrRightEdge(), BallCollision.GetSlopeEdge(), TileLightScanner.GetTileMask(), BallCollision.GetTopOrBottomEdge(), WorldGen.GrowCactus(), WorldGen.GrowCatTail(), WorldGen.GrowDungeonTree(), WorldGen.GrowDungeonTree_MakePassage(), WorldGen.GrowEpicTree(), WorldGen.GrowPalmTree(), WorldGen.GrowShroom(), WorldGen.GrowTree(), WorldGen.GrowTreeWithSettings(), WorldGen.GrowUndergroundTree(), WorldGen.HellFort(), Collision.HurtTiles(), WorldGen.IsBelowANonHammeredPlatform(), WorldGen.IsFitToPlaceFlowerIn(), WorldGen.IslandHouse(), BallCollision.IsPositionInsideTile(), TileDrawing.IsTileDangerous(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), leftSlope(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), WorldFile.LoadWorldTiles(), WorldGen.makeTemple(), WorldGen.MarblePileWithStatues(), WorldGen.MineHouse(), WorldGen.outerTempled(), MiningExplosivesBiome.Place(), WorldGen.PlaceAlch(), WorldGen.PlaceBamboo(), WorldGen.PlaceCatTail(), WorldGen.PlaceDye(), WorldGen.placeLavaTrap(), WorldGen.PlaceLilyPad(), WorldGen.PlaceOasis(), WorldGen.PlaceOnTable1x1(), WorldGen.PlacePot(), SandMound.PlaceSandColumn(), WorldGen.PlaceSandTrap(), WorldGen.PlaceSunflower(), HouseBuilder.PlaceSupportBeams(), Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), WorldGen.PlaceTile(), WorldGen.PlaceUnderwaterPlant(), WorldGen.PlantCheck(), WorldGen.PlantSeaOat(), WorldGen.PlatformProperSides(), WorldGen.PoundPlatform(), WorldGen.Pyramid(), WorldGen.ReplaceTile_DoActualReplacement_Single(), rightSlope(), WorldFile.SaveWorldTiles(), NetMessage.SendData(), WorldGen.ShellPile(), WorldGen.ShimmerMakeBiome(), slope(), Collision.SlopeCollision(), WorldGen.SlopeTile(), SmoothSlope(), WorldGen.SolidTile(), WorldGen.SolidTile2(), WorldGen.SolidTileNoAttach(), SmartCursorHelper.Step_AlchemySeeds(), SmartCursorHelper.Step_Boulders(), SmartCursorHelper.Step_ClayPots(), SmartCursorHelper.Step_Platforms(), SmartCursorHelper.Step_PumpkinSeeds(), SmartCursorHelper.Step_Torch(), Collision.StepConveyorBelt(), Collision.StepUp(), Collision.StickyTiles(), PortalHelper.SupportedNormal(), PortalHelper.SupportedSlope(), WorldGen.templeCleaner(), Collision.TileCollision(), WorldGen.TileFrame(), topSlope(), ToString(), PortalHelper.TryPlacingPortal(), AmbientWindSystem.TrySpawningWind(), WorldGen.UpdateWorld_UndergroundTile(), Collision.WalkDownSlope(), and Collision.WetCollision().