Terraria: TilePaintSystemV2.ARenderTargetHolder.PrepareTextureIfNecessary
PrepareTextureIfNecessary()
void TilePaintSystemV2.ARenderTargetHolder.PrepareTextureIfNecessary (Texture2D originalTexture, Rectangle? sourceRect = null) inline protected inherited
         {
             if (Target == null || Target.IsContentLost)
             {
                 Main instance = Main.instance;
                 if (!sourceRect.HasValue)
                 {
                     sourceRect = originalTexture.Frame();
                 }
                 Target = new RenderTarget2D(instance.GraphicsDevice, sourceRect.Value.Width, sourceRect.Value.Height, mipMap: false, instance.GraphicsDevice.PresentationParameters.BackBufferFormat, DepthFormat.None, 0, RenderTargetUsage.PreserveContents);
                 Target.ContentLost += Target_ContentLost;
                 Target.Disposing += Target_Disposing;
                 instance.GraphicsDevice.SetRenderTarget(Target);
                 instance.GraphicsDevice.Clear(Color.Transparent);
                 Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
                 PrepareShader();
                 Rectangle value = sourceRect.Value;
                 value.X = 0;
                 value.Y = 0;
                 Main.spriteBatch.Draw(originalTexture, value, Color.White);
                 Main.spriteBatch.End();
                 instance.GraphicsDevice.SetRenderTarget(null);
                 _wasPrepared = true;
             }
         }
References TilePaintSystemV2.ARenderTargetHolder._wasPrepared, Color, Game.GraphicsDevice, Main.instance, TilePaintSystemV2.ARenderTargetHolder.PrepareShader(), Main.spriteBatch, TilePaintSystemV2.ARenderTargetHolder.Target, TilePaintSystemV2.ARenderTargetHolder.Target_ContentLost(), and TilePaintSystemV2.ARenderTargetHolder.Target_Disposing().
Referenced by TilePaintSystemV2.TreeTopRenderTargetHolder.Prepare(), TilePaintSystemV2.TreeBranchTargetHolder.Prepare(), TilePaintSystemV2.TileRenderTargetHolder.Prepare(), and TilePaintSystemV2.WallRenderTargetHolder.Prepare().