Terraria: WorldGen.Spread.WallDungeon
WallDungeon()
static void WorldGen.Spread.WallDungeon (int x, int y, int wallType) inline static
         {
             if (!InWorld(x, y))
             {
                 return;
             }
             ushort num = (ushort)wallType;
             List<Point> list = new List<Point>();
             List<Point> list2 = new List<Point>();
             HashSet<Point> hashSet = new HashSet<Point>();
             list2.Add(new Point(x, y));
             while (list2.Count > 0)
             {
                 list.Clear();
                 list.AddRange(list2);
                 list2.Clear();
                 while (list.Count > 0)
                 {
                     Point item = list[0];
                     if (!InWorld(item.X, item.Y, 1))
                     {
                         list.Remove(item);
                         continue;
                     }
                     hashSet.Add(item);
                     list.Remove(item);
                     Tile tile = Main.tile[item.X, item.Y];
                     if (!SolidTile(item.X, item.Y) && tile.wall != num && tile.wall > 0 && tile.wall != 244)
                     {
                         tile.wall = num;
                         Point item2 = new Point(item.X - 1, item.Y);
                         if (!hashSet.Contains(item2))
{
                             list2.Add(item2);
                         }
                         item2 = new Point(item.X + 1, item.Y);
                         if (!hashSet.Contains(item2))
{
                             list2.Add(item2);
                         }
                         item2 = new Point(item.X, item.Y - 1);
                         if (!hashSet.Contains(item2))
{
                             list2.Add(item2);
                         }
                         item2 = new Point(item.X, item.Y + 1);
                         if (!hashSet.Contains(item2))
{
                             list2.Add(item2);
                         }
                     }
                     else if (tile.active())
                     {
                         tile.wall = num;
                     }
                 }
             }
         }
References Tile.active(), WorldGen.InWorld(), WorldGen.SolidTile(), Main.tile, and Tile.wall.
Referenced by WorldGen.MakeDungeon().