Terraria: PlayerDataInitializer.LoadGangsterMale
LoadGangsterMale()
static void PlayerDataInitializer.LoadGangsterMale () inline static private
     {
         CopyVariant(2, 0);
         LoadVariant(2, new int[6] { 4, 6, 8, 11, 12, 13 });
     }
References CopyVariant(), and LoadVariant().
Referenced by Load().