Terraria: PlayerDataInitializer.CopyVariant
CopyVariant()
static void PlayerDataInitializer.CopyVariant (int to, int from) inline static private
     {
         for (int i = 0; i < PlayerTextureID.Count; i++)
         {
             TextureAssets.Players[to, i] = TextureAssets.Players[from, i];
         }
     }
References PlayerTextureID.Count, and TextureAssets.Players.
Referenced by LoadCoatFemale(), LoadCoatMale(), LoadDisplayDollFemale(), LoadDisplayDollMale(), LoadDressFemale(), LoadDressMale(), LoadGangsterFemale(), LoadGangsterMale(), LoadStarterFemale(), LoadStickerFemale(), and LoadStickerMale().