Terraria: PlayerDataInitializer.LoadVariant
LoadVariant()
static void PlayerDataInitializer.LoadVariant (int ID, int[] pieceIDs) inline static private
     {
         for (int i = 0; i < pieceIDs.Length; i++)
         {
             TextureAssets.Players[ID, pieceIDs[i]] = Main.Assets.Request<Texture2D>("Images/Player_" + ID + "_" + pieceIDs[i], (AssetRequestMode)2);
         }
     }
References Main.Assets, and TextureAssets.Players.
Referenced by LoadCoatFemale(), LoadCoatMale(), LoadDisplayDollFemale(), LoadDisplayDollMale(), LoadDressFemale(), LoadDressMale(), LoadGangsterFemale(), LoadGangsterMale(), LoadStarterFemale(), LoadStarterMale(), LoadStickerFemale(), and LoadStickerMale().