Terraria: System.Linq.Expressions.ExpressionVisitor.VisitTypeBinary
VisitTypeBinary()
virtual Expression System.Linq.Expressions.ExpressionVisitor.VisitTypeBinary (TypeBinaryExpression node) inline package virtual inherited
Reimplemented in System.Linq.Expressions.DebugViewWriter, and System.Linq.Expressions.ExpressionStringBuilder.
Definition at line 288 of file ExpressionVisitor.cs.
    {
        return node.Update(Visit(node.Expression));
    }
References System.Linq.Expressions.TypeBinaryExpression.Expression, System.Linq.Expressions.TypeBinaryExpression.Update(), and System.Linq.Expressions.ExpressionVisitor.Visit().
Referenced by System.Linq.Expressions.TypeBinaryExpression.Accept().