Terraria: System.Linq.Expressions.ExpressionVisitor.VisitConditional
VisitConditional()
virtual Expression System.Linq.Expressions.ExpressionVisitor.VisitConditional (ConditionalExpression node) inline package virtual inherited
Reimplemented in System.Linq.EnumerableRewriter, System.Linq.Expressions.DebugViewWriter, and System.Linq.Expressions.ExpressionStringBuilder.
Definition at line 148 of file ExpressionVisitor.cs.
    {
        return node.Update(Visit(node.Test), Visit(node.IfTrue), Visit(node.IfFalse));
    }
References System.Linq.Expressions.ConditionalExpression.IfFalse, System.Linq.Expressions.ConditionalExpression.IfTrue, System.Linq.Expressions.ConditionalExpression.Test, System.Linq.Expressions.ConditionalExpression.Update(), and System.Linq.Expressions.ExpressionVisitor.Visit().
Referenced by System.Linq.Expressions.ConditionalExpression.Accept().