Terraria: System.Linq.Expressions.ExpressionVisitor.Visit
Visit() [1/2]
virtual ? Expression System.Linq.Expressions.ExpressionVisitor.Visit (Expression? node) inline virtual inherited
Definition at line 11 of file ExpressionVisitor.cs.
    {
        return node?.Accept(this);
    }
References System.Linq.Expressions.Expression< TDelegate >.Accept().
Referenced by System.Linq.Expressions.ExpressionStringBuilder.OutMember(), System.Linq.Expressions.DebugViewWriter.ParenthesizedVisit(), System.Linq.Expressions.Interpreter.QuoteInstruction.Run(), System.Linq.Expressions.ExpressionVisitor.Visit(), System.Linq.Expressions.ExpressionVisitor.VisitAndConvert< T >(), System.Linq.Expressions.ExpressionVisitor.VisitAndConvert< T >(), System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(), System.Linq.Expressions.DebugViewWriter.VisitBinary(), System.Linq.Expressions.ExpressionStringBuilder.VisitBinary(), System.Linq.Expressions.ExpressionVisitor.VisitBinary(), System.Linq.Expressions.ExpressionStringBuilder.VisitBlock(), System.Linq.EnumerableRewriter.VisitBlock(), System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(), System.Linq.Expressions.Interpreter.LightCompiler.QuoteVisitor.VisitCatchBlock(), System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitCatchBlock(), System.Linq.Expressions.DebugViewWriter.VisitCatchBlock(), System.Linq.Expressions.ExpressionVisitor.VisitCatchBlock(), System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitCatchBlock(), System.Linq.EnumerableRewriter.VisitConditional(), System.Linq.Expressions.DebugViewWriter.VisitConditional(), System.Linq.Expressions.ExpressionStringBuilder.VisitConditional(), System.Linq.Expressions.ExpressionVisitor.VisitConditional(), System.Linq.EnumerableRewriter.VisitConstant(), System.Linq.Expressions.ExpressionStringBuilder.VisitElementInit(), System.Linq.Expressions.DebugViewWriter.VisitElementInit(), System.Linq.Expressions.ExpressionVisitor.VisitElementInit(), System.Linq.Expressions.DebugViewWriter.VisitExpressions< T >(), System.Linq.Expressions.ExpressionStringBuilder.VisitExpressions< T >(), System.Linq.Expressions.DebugViewWriter.VisitExtension(), System.Linq.Expressions.DebugViewWriter.VisitGoto(), System.Linq.Expressions.ExpressionStringBuilder.VisitGoto(), System.Linq.Expressions.ExpressionVisitor.VisitGoto(), System.Linq.EnumerableRewriter.VisitGoto(), System.Linq.Expressions.ExpressionStringBuilder.VisitIndex(), System.Linq.Expressions.ExpressionVisitor.VisitIndex(), System.Linq.Expressions.ExpressionStringBuilder.VisitInvocation(), System.Linq.Expressions.ExpressionVisitor.VisitInvocation(), System.Linq.Expressions.DebugViewWriter.VisitLabel(), System.Linq.Expressions.ExpressionVisitor.VisitLabel(), System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitLambda< T >(), System.Linq.Expressions.ExpressionStringBuilder.VisitLambda< T >(), System.Linq.Expressions.ExpressionVisitor.VisitLambda< T >(), System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitLambda< T >(), System.Linq.Expressions.DebugViewWriter.VisitListInit(), System.Linq.Expressions.ExpressionStringBuilder.VisitListInit(), System.Linq.Expressions.ExpressionVisitor.VisitListInit(), System.Linq.Expressions.DebugViewWriter.VisitLoop(), System.Linq.Expressions.ExpressionVisitor.VisitLoop(), System.Linq.Expressions.ExpressionVisitor.VisitMember(), System.Linq.Expressions.DebugViewWriter.VisitMemberAssignment(), System.Linq.Expressions.ExpressionStringBuilder.VisitMemberAssignment(), System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(), System.Linq.Expressions.DebugViewWriter.VisitMemberInit(), System.Linq.Expressions.ExpressionStringBuilder.VisitMemberInit(), System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(), System.Linq.Expressions.ExpressionVisitor.VisitMemberListBinding(), System.Linq.Expressions.ExpressionVisitor.VisitMemberMemberBinding(), System.Linq.EnumerableRewriter.VisitMethodCall(), System.Linq.Expressions.ExpressionStringBuilder.VisitMethodCall(), System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(), System.Linq.Expressions.ExpressionStringBuilder.VisitNew(), System.Linq.Expressions.ExpressionVisitor.VisitNewArray(), System.Linq.Expressions.DebugViewWriter.VisitSwitch(), System.Linq.Expressions.ExpressionStringBuilder.VisitSwitch(), System.Linq.Expressions.ExpressionVisitor.VisitSwitch(), System.Linq.Expressions.DebugViewWriter.VisitSwitchCase(), System.Linq.Expressions.ExpressionVisitor.VisitSwitchCase(), System.Linq.Expressions.DebugViewWriter.VisitTry(), System.Linq.Expressions.ExpressionVisitor.VisitTry(), System.Linq.Expressions.ExpressionStringBuilder.VisitTypeBinary(), System.Linq.Expressions.ExpressionVisitor.VisitTypeBinary(), System.Linq.Expressions.ExpressionStringBuilder.VisitUnary(), System.Linq.Expressions.ExpressionVisitor.VisitUnary(), System.Linq.Expressions.DebugViewWriter.WriteLambda(), and System.Linq.Expressions.DebugViewWriter.WriteTo().