Terraria: System.Linq.Expressions.ExpressionVisitor.ValidateChildType
ValidateChildType()
static void System.Linq.Expressions.ExpressionVisitor.ValidateChildType (Type before, Type after, string methodName) inline static private inherited
Definition at line 378 of file ExpressionVisitor.cs.
    {
        if (before.IsValueType)
        {
            if (TypeUtils.AreEquivalent(before, after))
            {
                return;
            }
        }
        else if (!after.IsValueType)
        {
            return;
        }
        throw Error.MustRewriteChildToSameType(before, after, methodName);
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Type.IsValueType, and System.Linq.Expressions.Error.MustRewriteChildToSameType().
Referenced by System.Linq.Expressions.ExpressionVisitor.ValidateBinary(), and System.Linq.Expressions.ExpressionVisitor.ValidateUnary().