Terraria: System.Linq.Expressions.ExpressionVisitor.ValidateBinary
ValidateBinary()
static BinaryExpression System.Linq.Expressions.ExpressionVisitor.ValidateBinary (BinaryExpression before, BinaryExpression after) inline static private inherited
Definition at line 355 of file ExpressionVisitor.cs.
    {
        if (before != after && before.Method == null)
        {
            if (after.Method != null)
            {
                throw Error.MustRewriteWithoutMethod(after.Method, "VisitBinary");
            }
            ValidateChildType(before.Left.Type, after.Left.Type, "VisitBinary");
            ValidateChildType(before.Right.Type, after.Right.Type, "VisitBinary");
        }
        return after;
    }
References System.Linq.Expressions.BinaryExpression.Left, System.Linq.Expressions.BinaryExpression.Method, System.Linq.Expressions.Error.MustRewriteWithoutMethod(), System.Linq.Expressions.BinaryExpression.Right, System.Linq.Expressions.Expression< TDelegate >.Type, and System.Linq.Expressions.ExpressionVisitor.ValidateChildType().
Referenced by System.Linq.Expressions.ExpressionVisitor.VisitBinary().