Terraria: System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding
VisitMemberBinding()
virtual MemberBinding System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding (MemberBinding node) inline protected virtual inherited
Definition at line 313 of file ExpressionVisitor.cs.
    {
        return node.BindingType switch
        {
            MemberBindingType.Assignment => VisitMemberAssignment((MemberAssignment)node),
            MemberBindingType.MemberBinding => VisitMemberMemberBinding((MemberMemberBinding)node),
            MemberBindingType.ListBinding => VisitMemberListBinding((MemberListBinding)node),
            _ => throw Error.UnhandledBindingType(node.BindingType),
        };
    }
References System.Linq.Expressions.MemberBinding.BindingType, System.Linq.Expressions.Error.UnhandledBindingType(), System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(), System.Linq.Expressions.ExpressionVisitor.VisitMemberListBinding(), and System.Linq.Expressions.ExpressionVisitor.VisitMemberMemberBinding().
Referenced by System.Linq.Expressions.DebugViewWriter.VisitMemberInit(), System.Linq.Expressions.ExpressionStringBuilder.VisitMemberInit(), System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(), System.Linq.Expressions.DebugViewWriter.VisitMemberMemberBinding(), System.Linq.Expressions.ExpressionStringBuilder.VisitMemberMemberBinding(), and System.Linq.Expressions.ExpressionVisitor.VisitMemberMemberBinding().