Terraria: System.Linq.Expressions.ExpressionVisitor.VisitTry
VisitTry()
virtual Expression System.Linq.Expressions.ExpressionVisitor.VisitTry (TryExpression node) inline package virtual inherited
Reimplemented in System.Linq.Expressions.DebugViewWriter, and System.Linq.Expressions.ExpressionStringBuilder.
Definition at line 283 of file ExpressionVisitor.cs.
    {
        return node.Update(Visit(node.Body), Visit(node.Handlers, VisitCatchBlock), Visit(node.Finally), Visit(node.Fault));
    }
References System.Linq.Expressions.TryExpression.Body, System.Linq.Expressions.TryExpression.Fault, System.Linq.Expressions.TryExpression.Finally, System.Linq.Expressions.TryExpression.Handlers, System.Linq.Expressions.TryExpression.Update(), System.Linq.Expressions.ExpressionVisitor.Visit(), and System.Linq.Expressions.ExpressionVisitor.VisitCatchBlock().