Terraria: System.Linq.Expressions.ExpressionVisitor.VisitCatchBlock
VisitCatchBlock()
virtual CatchBlock System.Linq.Expressions.ExpressionVisitor.VisitCatchBlock (CatchBlock node) inline protected virtual
Reimplemented in System.Linq.Expressions.Compiler.VariableBinder, System.Linq.Expressions.Interpreter.LightCompiler.QuoteVisitor, System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter, System.Linq.Expressions.DebugViewWriter, System.Linq.Expressions.ExpressionStringBuilder, and System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.
Definition at line 278 of file ExpressionVisitor.cs.
    {
        return node.Update(VisitAndConvert(node.Variable, "VisitCatchBlock"), Visit(node.Filter), Visit(node.Body));
    }
References System.Linq.Expressions.CatchBlock.Body, System.Linq.Expressions.CatchBlock.Filter, System.Linq.Expressions.CatchBlock.Update(), System.Linq.Expressions.CatchBlock.Variable, and System.Linq.Expressions.ExpressionVisitor.Visit().
Referenced by System.Linq.Expressions.ExpressionVisitor.VisitTry().