Terraria: System.Linq.Expressions.ExpressionVisitor.VisitLambda< T >
VisitLambda< T >()
virtual Expression System.Linq.Expressions.ExpressionVisitor.VisitLambda< T > (Expression< T > node) inline package virtual
Reimplemented in System.Linq.Expressions.Compiler.VariableBinder, System.Linq.Expressions.Interpreter.LightCompiler.QuoteVisitor, System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter, System.Linq.Expressions.DebugViewWriter, System.Linq.Expressions.ExpressionStringBuilder, System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter, and System.Linq.EnumerableRewriter.
Definition at line 200 of file ExpressionVisitor.cs.
    {
        Expression expression = Visit(node.Body);
        ParameterExpression[] array = VisitParameters(node, "VisitLambda");
        if (expression == node.Body && array == null)
        {
            return node;
        }
        return node.Rewrite(expression, array);
    }
References System.array, System.Linq.Expressions.LambdaExpression.Body, System.Linq.Expressions.Expression< TDelegate >.Rewrite(), System.Linq.Expressions.ExpressionVisitor.Visit(), and System.Linq.Expressions.ExpressionVisitor.VisitParameters().