Terraria: Terraria.Graphics.Shaders.ScreenShaderData.UseTargetPosition
UseTargetPosition()
ScreenShaderData Terraria.Graphics.Shaders.ScreenShaderData.UseTargetPosition (Vector2 position) inline
Definition at line 168 of file ScreenShaderData.cs.
    {
        _uTargetPosition = position;
        return this;
    }
References Terraria.Graphics.Shaders.ScreenShaderData._uTargetPosition.
Referenced by Terraria.Graphics.Effects.Filter.Activate(), Terraria.GameContent.Shaders.BlizzardShaderData.Apply(), Terraria.GameContent.Shaders.MoonLordScreenShaderData.Apply(), Terraria.GameContent.Shaders.SandstormShaderData.Apply(), Terraria.GameContent.Shaders.WaterShaderData.Apply(), Terraria.Graphics.Effects.SimpleOverlay.Draw(), and Terraria.GameContent.Shaders.BlizzardShaderData.Update().