Terraria: GemCaveShader.ProcessHighDetail
ProcessHighDetail()
void GemCaveShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
     {
         time *= TimeRate;
         float num = time % 1f;
         bool num2 = time % 2f > 1f;
         Vector4 vector = (num2 ? _secondaryColor : _primaryColor);
         Vector4 value = (num2 ? _primaryColor : _secondaryColor);
         num *= 1.2f;
         for (int i = 0; i < fragment.Count; i++)
         {
             Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
             Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
             float staticNoise = NoiseHelper.GetStaticNoise(canvasPositionOfIndex * 0.5f + new Vector2(0f, time * 0.5f));
             Vector4 value2 = vector;
             staticNoise += num;
             if (staticNoise > 0.999f)
             {
                 float amount = MathHelper.Clamp((staticNoise - 0.999f) / 0.2f, 0f, 1f);
                 value2 = Vector4.Lerp(value2, value, amount);
             }
             float dynamicNoise = NoiseHelper.GetDynamicNoise(gridPositionOfIndex.X, gridPositionOfIndex.Y, time / CycleTime);
             dynamicNoise = Math.Max(0f, 1f - dynamicNoise * ColorRarity);
             value2 = Vector4.Lerp(value2, _gemColors[((gridPositionOfIndex.Y * 47 + gridPositionOfIndex.X) % _gemColors.Length + _gemColors.Length) % _gemColors.Length], dynamicNoise);
             fragment.SetColor(i, value2);
             fragment.SetColor(i, value2);
         }
     }
References _gemColors, _primaryColor, _secondaryColor, ColorRarity, Fragment.Count, CycleTime, Fragment.GetCanvasPositionOfIndex(), NoiseHelper.GetDynamicNoise(), Fragment.GetGridPositionOfIndex(), NoiseHelper.GetStaticNoise(), Fragment.SetColor(), and TimeRate.