Terraria: Tile.topSlope
topSlope()
bool Tile.topSlope () inline
     {
         byte b = slope();
         if (b != 1)
         {
             return b == 2;
         }
         return true;
     }
References slope().
Referenced by WorldGen.AddBuriedChest(), NPC.AI(), NPC.AI_003_Fighters(), NPC.AI_007_TownEntities(), Projectile.AI_010(), NPC.AI_026_Unicorns(), NPC.AI_107_ImprovedWalkers(), WorldGen.AnchorValid(), TileObject.CanPlace(), WorldGen.Check2x1(), WorldGen.CheckBanner(), WorldGen.CheckOnTable1x1(), WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), WorldGen.CheckTorch(), WaterfallManager.DrawWaterfall(), Collision.HurtTiles(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), WorldGen.meteor(), WorldGen.PlaceCatTail(), WorldGen.PlaceSandTrap(), Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), WorldGen.SolidTile2(), WorldGen.SolidTileAllowBottomSlope(), DelegateMethods.SpreadDirt(), WorldGen.TileFrame(), WorldGen.TopEdgeCanBeAttachedTo(), and WorldGen.UpdateWorld_UndergroundTile().