Terraria: Tile.lava
lava() [1/2]
bool Tile.lava () inline
     {
         return (bTileHeader & 0x60) == 32;
     }
References bTileHeader.
Referenced by WorldGen.AddLifeCrystal(), Liquid.AddWater(), NPC.AI(), NPC.AI_003_Fighters(), NPC.AI_007_TownEntities_GetWalkPrediction(), Projectile.AI_067_FreakingPirates(), NPC.AI_121_QueenSlime(), NPC.AI_AttemptToFindTeleportSpot(), TileLightScanner.ApplyLiquidLight(), Liquid.AttemptToMoveLava(), NPC.BloodNautilus_CallForHelp(), WorldGen.CheckAlch(), WorldGen.CloudIsland(), WorldGen.CloudLake(), NetMessage.CompressTileBlock_Inner(), NPC.CreateBrickBoxForWallOfFlesh(), NetMessage.DecompressTileBlock_Inner(), Liquid.DelWater(), WorldGen.DesertCloudIsland(), Collision.DrownCollision(), WorldGen.DungeonEnt(), WorldGen.DungeonPitTrap(), WaterfallManager.FindWaterfalls(), WorldGen.FinishGetGoodWorld(), WorldGen.FinishNotTheBees(), WorldGen.FinishRemixWorld(), Projectile.GetFishingPondState(), TELogicSensor.GetState(), TileLightScanner.GetTileMask(), Gore.Gore_UpdateLeaf(), WorldGen.GrowAlch(), WorldGen.GrowShroom(), WorldGen.HellRoom(), NPC.HitEffect(), Player.ItemCheck_UseBuckets(), WorldGen.KillTile(), lava(), Liquid.LavaCheck(), Collision.LavaCollision(), Liquid.LiquidCheck(), liquidType(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), WorldFile.LoadWorldTiles(), WorldGen.MakeWateryIceThing(), WorldGen.mayanTrap(), WorldGen.MineHouse(), WorldGen.nextCount(), WorldGen.PlaceAlch(), DesertHive.PlaceClustersArea(), WorldGen.PlaceDye(), WorldGen.placeLavaTrap(), WorldGen.PlaceOasis(), WorldGen.PlaceSmallPile(), Player.PlaceThing_Tiles_CheckLavaBlocking(), Player.PlaceThing_Tiles_CheckRopeUsability(), WorldGen.placeTrap(), WorldGen.plantDye(), WorldFile.SaveWorldTiles(), Liquid.SettleWaterAt(), WorldGen.ShroomPatch(), WorldGen.SnowCloudIsland(), WorldGen.SonOfLakinater(), Player.Spawn_ForceClearArea(), NPC.SpawnNPC(), WorldGen.Spread.Spider(), WorldGen.SpreadGrass(), SmartCursorHelper.Step_AlchemySeeds(), TeleportHelpers.TileIsDangerous(), WorldGen.TileRunner(), Liquid.Update(), WorldGen.UpdateWorld_OvergroundTile(), WorldGen.UpdateWorld_UndergroundTile(), WorldGen.WaterCheck(), and Collision.WaterCollision().