Terraria: Tile.active
active() [1/2]
bool Tile.active () inline
References sTileHeader.
Referenced by active(), WorldGen.ActiveAndWalkableTile(), DeadMansChestBiome.ActuallyPlaceBoulderTrap(), WorldGen.AddBuriedChest(), WorldGen.AddHellHouses(), WorldGen.AddLifeCrystal(), WorldGen.AddShadowOrb(), DesertHive.AddTileVariance(), Liquid.AddWater(), Player.AdjTiles(), Collision.AdvancedTileCollision(), NPC.AI(), NPC.AI_003_Fighters(), NPC.AI_007_FindGoodRestingSpot(), NPC.AI_007_TryForcingSitting(), Projectile.AI_010(), Projectile.AI_016(), Projectile.AI_026(), NPC.AI_045_Golem(), NPC.AI_047_GolemFist(), Projectile.AI_062(), Projectile.AI_067_FreakingPirates(), Projectile.AI_075(), NPC.AI_110_Betsy(), NPC.AI_111_DD2LightningBug(), NPC.AI_112_FairyCritter(), Projectile.AI_135_OgreStomp(), Projectile.AI_149_GolfBall(), Projectile.AI_155_MysticSnakeCoil(), Projectile.AI_155_RemoveRope(), WorldGen.AllowsSandfall(), MinecartDiggerHelper.AlreadyLeadsIntoWantedTrack(), Collision.AnyCollision(), Collision.AnyCollisionWithSpecificTiles(), ActionGrass.Apply(), ActionVines.Apply(), Actions.TileScanner.Apply(), Actions.SetTile.Apply(), Actions.SetTileKeepWall.Apply(), Modifiers.OnlyTiles.Apply(), Modifiers.IsTouching.Apply(), Modifiers.NotTouching.Apply(), Modifiers.IsTouchingAir.Apply(), Modifiers.SkipTiles.Apply(), Modifiers.IsEmpty.Apply(), Modifiers.IsSolid.Apply(), Modifiers.IsNotSolid.Apply(), TileLightScanner.ApplyHellLight(), TileLightScanner.ApplySurfaceLight(), Player.ApplyTouchDamage(), WorldGen.AttemptFossilShattering(), WorldGen.AttemptToGeneratePlanteraBulbAt(), WorldGen.AttemptToGrowTreeFromSapling(), HiveBiome.BadSpotForHoneyFall(), WorldGen.BiomeTileCheck(), WorldGen.BlockBelowMakesSandFall(), PortalHelper.BlockPortals(), WorldGen.BottomEdgeCanBeAttachedTo(), WorldGen.CactusFrame(), MinecartDiggerHelper.CanGetPastTile(), Collision.CanHit(), Collision.CanHitLine(), Collision.CanHitWithCheck(), WorldGen.CanKillTile(), Player.CanMoveForwardOnRope(), TileObject.CanPlace(), GraniteBiome.CanPlace(), StructureMap.CanPlace(), WorldGen.CanPlaceSink(), WorldGen.CanPoundTile(), WorldGen.CanUnderwaterPlantGrowHere(), DelegateMethods.CastLightOpen(), DelegateMethods.CastLightOpen_StopForSolids(), DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), WorldGen.CaveOpenater(), WorldGen.Cavinator(), WorldGen.ChasmRunner(), WorldGen.ChasmRunnerSideways(), WorldGen.Check1x2Top(), WorldGen.Check1xX(), WorldGen.Check2x1(), WorldGen.Check2x2(), WorldGen.Check2x2Style(), WorldGen.Check2x3Wall(), WorldGen.Check2x5(), WorldGen.Check2xX(), WorldGen.Check3x1(), WorldGen.Check3x2(), WorldGen.Check3x2Wall(), WorldGen.Check3x3(), WorldGen.Check3x3Wall(), WorldGen.Check3x4(), WorldGen.Check3x5(), WorldGen.Check3x6(), WorldGen.Check4x2(), WorldGen.Check4x3Wall(), WorldGen.Check5x4(), WorldGen.Check6x3(), WorldGen.Check6x4Wall(), WorldGen.CheckBamboo(), WorldGen.CheckBanner(), WorldGen.CheckCactus(), WorldGen.CheckCannon(), WorldGen.CheckCatTail(), WorldGen.CheckChand(), WorldGen.CheckChest(), WorldGen.CheckDoorClosed(), WorldGen.CheckDoorOpen(), Player.CheckDrowning(), Player.CheckForGoodTeleportationSpot(), WorldGen.CheckJunglePlant(), TileObjectData.CheckLavaDeath(), WorldGen.CheckLilyPad(), Wiring.CheckLogicGate(), WorldGen.CheckLogicTiles(), WorldGen.CheckMan(), WorldGen.CheckMB(), WorldGen.CheckOasisPlant(), WorldGen.CheckOnTable1x1(), WorldGen.CheckPalmTree(), WorldGen.CheckPile(), WorldGen.CheckPot(), WorldGen.CheckSign(), Player.CheckSpawn_Internal(), WorldGen.CheckSpecialTownNPCSpawningConditions(), SpelunkerProjectileHelper.CheckSpot(), DelegateMethods.CheckStopForSolids(), WorldGen.CheckSunflower(), WorldGen.CheckSuper(), WorldGen.CheckTileBreakability(), WorldGen.CheckTileFrames(), WorldGen.CheckTorch(), WorldGen.CheckTree(), WorldGen.CheckTreeWithSettings(), WorldGen.CheckUnderwaterPlant(), Conditions.IsTile.CheckValidity(), Conditions.MysticSnake.CheckValidity(), Conditions.IsSolid.CheckValidity(), TileObjectData.CheckWaterDeath(), WorldGen.CheckWeaponsRack(), WorldGen.CheckWoman(), WorldGen.CheckXmasTree(), WorldGen.Chlorophyte(), Clear(), ClearTile(), TileDrawing.ClimbCatTail(), WorldGen.CloseDoor(), WorldGen.CloudIsland(), WorldGen.CloudLake(), NPC.Collision_MoveSlopesAndStairFall(), NetMessage.CompressTileBlock_Inner(), WorldFile.ConvertIlluminantPaintToNewField(), WorldGen.ConvertSkyIslands(), MinecartDiggerHelper.CorrectTrackConnections(), WorldGen.CountGrowingPlantTiles(), WorldGen.CountNearBlocksTypes(), StrayMethods.CountSandHorizontally(), WorldGen.CountTiles(), WorldGen.CountTileTypesInArea(), WorldGen.CountTileTypesInWorld(), TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint(), TileDrawing.CrawlToTopOfVineAndAddSpecialPoint(), HiveBiome.CreateBlockedHoneyCube(), NPC.CreateBrickBoxForWallOfFlesh(), HiveBiome.CreateDentForHoneyFall(), Projectile.CreateGroundExplosion(), HiveBiome.CreateHiveTunnel(), Projectile.CreateImpactExplosion(), MapHelper.CreateMapTile(), HiveBiome.CreateStandForLarva(), WorldGen.CrimEnt(), WorldGen.CrimPlaceHearts(), WorldGen.CrimStart(), WorldGen.CrimVein(), Player.DamageTileWithShovel(), Wiring.DeActive(), NetMessage.DecompressTileBlock_Inner(), Liquid.DelWater(), WorldGen.DesertCloudIsland(), WorldGen.DestroyHeart(), WorldGen.digTunnel(), Player.DoBootsEffect_PlaceFlamesOnTile(), Player.DoBootsEffect_PlaceFlowersOnTile(), AmbientWindSystem.DoesTileAllowWind(), WorldGen.DontStarveTryWateringTile(), TileDrawing.Draw(), TileDrawing.DrawAnyDirectionalGrass(), Main.DrawBackground(), TileDrawing.DrawBasicTile(), Main.DrawBlack(), Main.DrawClothesWindow(), HitTile.DrawFreshAnimations(), TileDrawing.DrawGrass(), Main.DrawInfoAccs(), TileDrawing.DrawMasterTrophies(), TileDrawing.DrawMultiTileGrass(), TileDrawing.DrawMultiTileVines(), TileDrawing.DrawRisingVineStrip(), TileDrawing.DrawSingleTile(), TileDrawing.DrawTeleportationPylons(), TileDrawing.DrawTile_LiquidBehindTile(), Main.DrawTileCracks(), Main.DrawTileInWater(), TileDrawing.DrawTrees(), TileDrawing.DrawVineStrip(), WaterfallManager.DrawWaterfall(), Main.DrawWires(), Mount.DrillSmartCursor_Blocks(), WorldGen.dropMeteor(), Collision.DrownCollision(), WorldGen.DungeonEnt(), WorldGen.DungeonHalls(), WorldGen.DungeonPitTrap(), WorldGen.DungeonRoom(), WorldGen.DungeonStairs(), DelegateMethods.EmitGolfCartDust_StopForSolids(), Collision.EmptyTile(), WorldGen.EmptyTileCheck(), WorldGen.EveryTileFrame(), Projectile.ExplodeCrackedTiles(), Projectile.ExplodeTiles(), Player.FigureOutWhatToPlace(), TerrainPass.FillColumn(), TileSmartInteractCandidateProvider.FillPotentialTargetTiles(), WorldGen.FillWallHolesInSpot(), DeadMansChestBiome.FindBoulderTrapSpot(), NPC.FindCattailTop(), DeadMansChestBiome.FindDartTrapSpotSingle(), Player.FindPulley(), Mount.FindTileHeight(), NPC.FindTreeBranch(), WaterfallManager.FindWaterfalls(), WorldGen.FinishDrunkGen(), WorldGen.FinishGetGoodWorld(), WorldGen.FinishNoTraps(), WorldGen.FinishNotTheBees(), WorldGen.FinishRemixWorld(), WorldGen.FinishTenthAnniversaryWorld(), WorldGen.FixChand(), WorldGen.FixChands(), WorldFile.FixDresserChests(), WorldGen.FixHeart(), WorldGen.FixHearts(), WorldGen.FixSunflowers(), WorldGen.FloatingIsland(), HiveBiome.FrameOutAllHiveContents(), TEDisplayDoll.Framing_CheckTile(), TEHatRack.Framing_CheckTile(), TETeleportationPylon.Framing_CheckTile(), TEWeaponsRack.Framing_CheckTile(), SurfaceMap.FromArea(), WallDrawing.FullTile(), Main.FullTile(), WorldGen.Spread.Gem(), WorldGen.GeneratePlanteraBulbOnAllMechsDefeated(), JunglePass.GenerateTunnelToSurface(), WorldGen.GenerateWorld(), WorldGen.GERunner(), WorldGen.GetCactusType(), MessageBuffer.GetData(), NPC.GetFairyTreasureCoords(), Player.GetHurtTile(), TileDrawing.GetPalmTreeBiome(), TileDrawing.GetPalmTreeVariant(), PlayerSittingHelper.GetSittingTargetInfo(), PlayerSleepingHelper.GetSleepingTargetInfo(), TileObjectData.GetTileData(), TileLightScanner.GetTileLight(), Collision.GetTileRotation(), TileDrawing.GetTreeBiome(), WorldGen.GetTreeBottom(), TileDrawing.GetTreeVariant(), WorldGen.GetVineTop(), WorldGen.GrowAlch(), WorldGen.GrowCactus(), WorldGen.GrowCatTail(), WorldGen.GrowCheckSeaweed(), WorldGen.GrowDungeonTree(), WorldGen.GrowDungeonTree_MakePassage(), WorldGen.GrowEpicTree(), WorldGen.GrowLivingTree(), WorldGen.GrowLivingTree_HorizontalTunnel(), WorldGen.GrowLivingTree_MakePassage(), WorldGen.GrowLivingTreePassageRoom(), WorldGen.GrowPalmTree(), WorldGen.GrowPumpkin(), WorldGen.GrowShroom(), WorldGen.GrowSpike(), WorldGen.GrowTree(), WorldGen.GrowTreeWithSettings(), WorldGen.GrowUndergroundTree(), WorldGen.GrowWeb(), Player.HandleBeingInChestRange(), WorldGen.hardUpdateWorld(), WorldGen.HasValidGroundForAbigailsFlowerBelowSpot(), WorldGen.HasValidGroundForGlowTulipBelowSpot(), NPC.HaveDryadDoStardewAnimation(), WorldGen.HellFort(), WorldGen.HellHouse(), WorldGen.HellRoom(), GolfHelper.HitGolfBall(), Collision.HitTiles(), Collision.HitWallSubstep(), Wiring.HitWireSingle(), Collision.HurtTiles(), Player.InterruptItemUsageIfOverTile(), WorldGen.IsBelowANonHammeredPlatform(), Player.IsBottomOfTreeTrunkNoRoots(), WorldGen.IsFitToPlaceFlowerIn(), DeadMansChestBiome.IsGoodSpotsForExplosive(), SmartCursorHelper.IsHoveringOverAnInteractibleTileThatBlocksSmartCursor(), WorldGen.IsItATrap(), WorldGen.IsItATrigger(), WorldGen.IslandHouse(), TrackGenerator.IsLocationInvalid(), TrackGenerator.IsMinecartTrack(), WorldGen.IsOpenDoorAnchorFrame(), Minecart.IsPressurePlate(), WorldGen.IsRope(), isTheSameAs(), WorldGen.IsTileALeafyTreeTop(), WorldGen.IsTileNearby(), WorldGen.IsTileReplacable(), Player.IsTileTypeInInteractionRange(), TEDisplayDoll.IsTileValidForEntity(), TEHatRack.IsTileValidForEntity(), TETeleportationPylon.IsTileValidForEntity(), Collision.IsWorldPointSolid(), Player.ItemCheck_ApplyHoldStyle(), Player.ItemCheck_CheckCanUse(), Player.ItemCheck_CutTiles(), Player.ItemCheck_IsValidDirtRodTarget(), Player.ItemCheck_Shoot(), Player.ItemCheck_TryPlacingWearablesOnMannequins(), Player.ItemCheck_UseMiningTools(), Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Player.ItemCheck_UseMiningTools_TryFindingWallToHammer(), Player.ItemCheck_UseMiningTools_TryHittingWall(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), Projectile.Kill(), Projectile.Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks(), WorldGen.KillTile(), WorldGen.KillTile_DropItems(), WorldGen.KillTile_GetItemDrops(), WorldGen.KillTile_GetTreeDrops(), WorldGen.KillTile_MakeTileDust(), WorldGen.Lakinater(), WorldGen.LaunchRocket(), WorldGen.LeftEdgeCanBeAttachedTo(), TileLightScanner.LightIsBlocked(), Liquid.LiquidCheck(), WorldFile.LoadSigns(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), WorldFile.LoadWorldTiles(), WorldGen.MakeDungeon(), WorldGen.MakeDungeon_Banners(), WorldGen.MakeDungeon_GroundFurniture(), WorldGen.MakeDungeon_Lights(), WorldGen.MakeDungeon_Pictures(), WorldGen.makeTemple(), WorldGen.MakeWateryIceThing(), WorldGen.MarblePileWithStatues(), WorldGen.MatureTheHerbPlants(), WorldGen.meteor(), WorldGen.MineHouse(), MinecartDiggerHelper.MineTheTileIfNecessary(), WorldGen.Spread.Moss(), WorldGen.Mountinater(), WorldGen.nearbyChlorophyte(), Chest.NearOtherChests(), WorldGen.nearPicture(), WorldGen.nearPicture2(), WorldGen.neonMossBiome(), WorldGen.nextCount(), WorldGen.nextDirtCount(), WorldGen.NoNearbyAbigailsFlower(), WorldGen.NoNearbyGlowTulips(), Collision.noSlopeCollision(), DelegateMethods.NotDoorStand(), NPC.NPCCanStickToWalls(), WorldGen.oceanCave(), Main.OldDrawBackground(), WorldGen.OpenDoor(), WorldGen.OrePatch(), WorldGen.OreRunner(), WorldGen.outerTempled(), WorldGen.paintCoatTile(), WorldGen.PaintTheClouds(), WorldGen.PaintTheDungeon(), WorldGen.PaintTheLivingTrees(), WorldGen.PaintTheMushrooms(), WorldGen.PaintThePurityGrass(), WorldGen.PaintThePyramids(), WorldGen.PaintTheSand(), WorldGen.PaintTheTemple(), WorldGen.PaintTheTrees(), WorldGen.paintTile(), Player.PickTile(), SandMound.Place(), CampsiteBiome.Place(), GraniteBiome.Place(), HiveBiome.Place(), HoneyPatchBiome.Place(), MiningExplosivesBiome.Place(), TileObject.Place(), WorldGen.Place1x1(), WorldGen.Place1x2(), WorldGen.Place1x2Top(), WorldGen.Place1xX(), WorldGen.Place2x1(), WorldGen.Place2x2(), WorldGen.Place2x2Horizontal(), WorldGen.Place2x2Style(), WorldGen.Place2x3Wall(), WorldGen.Place2xX(), WorldGen.Place3x1(), WorldGen.Place3x2(), WorldGen.Place3x2Wall(), WorldGen.Place3x3(), WorldGen.Place3x3Wall(), WorldGen.Place3x4(), WorldGen.Place4x2(), WorldGen.Place4x3Wall(), WorldGen.Place5x4(), WorldGen.Place6x3(), WorldGen.Place6x4Wall(), WorldGen.PlaceAlch(), WorldGen.PlaceBamboo(), WorldGen.PlaceBanner(), DeadMansChestBiome.PlaceBoulderTrapSpot(), WorldGen.PlaceCannon(), WorldGen.PlaceCatTail(), WorldGen.PlaceChand(), WorldGen.PlaceChestDirect(), DesertHive.PlaceClustersArea(), DunesBiome.PlaceCurvedLine(), GraniteBiome.PlaceDecorations(), WorldGen.PlaceDoor(), WorldGen.PlaceDresserDirect(), WorldGen.PlaceDye(), WorldGen.PlaceJunglePlant(), WorldGen.placeLavaTrap(), WorldGen.PlaceLilyPad(), WorldGen.PlaceLogicTiles(), WorldGen.PlaceMan(), WorldGen.PlaceMB(), WorldGen.PlaceOasis(), WorldGen.PlaceOasisPlant(), WorldGen.PlaceOnTable1x1(), WorldGen.PlacePot(), WorldGen.PlacePumpkin(), SandMound.PlaceSandColumn(), WorldGen.PlaceSandTrap(), WorldGen.PlaceSign(), MarbleBiome.PlaceSlab(), WorldGen.PlaceSmallPile(), WorldGen.PlaceStatueTrap(), WorldGen.PlaceSunflower(), Player.PlaceThing_CannonBall(), Player.PlaceThing_CheckSpecificValidtyCaseForBlockSwap(), Player.PlaceThing_ItemInExtractinator(), Player.PlaceThing_LockChest(), Player.PlaceThing_Paintbrush(), Player.PlaceThing_PaintScrapper_LongMoss(), Player.PlaceThing_PaintScrapper_TryScrapping(), Player.PlaceThing_Tiles(), Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Player.PlaceThing_Tiles_BlockPlacementForRepeatedCoralAndBeachPiles(), Player.PlaceThing_Tiles_BlockPlacementForRepeatedPigronatas(), Player.PlaceThing_Tiles_CheckRopeUsability(), Player.PlaceThing_Tiles_GetAutoAccessoryCache(), Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck(), Player.PlaceThing_TryReplacingTiles(), Player.PlaceThing_Walls(), Player.PlaceThing_XMasTreeTops(), WorldGen.PlaceTile(), WorldGen.placeTNTBarrel(), Minecart.PlaceTrack(), WorldGen.placeTrap(), WorldGen.PlaceUncheckedStalactite(), WorldGen.PlaceUnderwaterPlant(), Player.PlaceWeapon(), WorldGen.PlaceWoman(), WorldGen.PlaceXmasTree(), WorldGen.PlaceXmasTree_Direct(), WorldGen.PlantAlch(), WorldGen.plantDye(), WorldGen.PlantSeaOat(), WorldGen.PlatformProperSides(), TileDrawing.PrepareForAreaDrawing(), HitTile.Prune(), WorldGen.Pyramid(), Player.QuickGrapple(), Player.QuickMinecart(), Player.QuickMinecartSnap(), TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition(), WorldGen.ReplaceTile_EliminateNaturalExtras(), TerrainPass.RetargetColumn(), WorldGen.RightEdgeCanBeAttachedTo(), TELogicSensor.SanityCheck(), WorldFile.SaveChests(), WorldFile.SaveWorldTiles(), SceneMetrics.ScanAndExportToMain(), WorldGen.ScanTileColumnAndRemoveClumps(), MysticLogFairiesEvent.ScanWholeOverworldForLogs(), WorldGen.ScoreRoom(), WorldGen.ScoreRoom_CanBeHomeSpot(), DelegateMethods.SearchAvoidedByNPCs(), Framing.SelfFrame8Way(), NetMessage.SendData(), WorldGen.ShakeTree(), WorldGen.ShellPile(), WorldGen.ShiftTrapdoor(), WorldGen.ShimmeratorNext(), WorldGen.ShimmerCleanUp(), WorldGen.ShimmerMakeBiome(), WorldGen.ShimmerMakeBiomeOpening(), BlockBecauseYouAreOverAnImportantTile.ShouldBlockSmartInteract(), GraniteBiome.ShouldUseLava(), WorldGen.ShroomPatch(), Collision.SlopeCollision(), Player.SmartSelect_GetToolStrategy(), WorldGen.smCallBack(), WorldGen.SnowCloudIsland(), Collision.SolidCollision(), WorldGen.SolidOrSlopedTile(), WorldGen.SolidTile(), WorldGen.SolidTile2(), WorldGen.SolidTile3(), WorldGen.SolidTileAllowBottomSlope(), WorldGen.SolidTileAllowLeftSlope(), WorldGen.SolidTileAllowRightSlope(), WorldGen.SolidTileAllowTopSlope(), WorldGen.SolidTileNoAttach(), Collision.SolidTiles(), WorldGen.SonOfLakinater(), NPC.Spawning_SandstoneCheck(), NPC.SpawnOnPlayer(), WorldGen.SpawnPlanteraThorns(), WorldGen.SpawnTravelNPC(), Projectile.SpawnWebs(), WorldGen.Spread.Spider(), Player.SporeSac(), HiveBiome.SpotActuallyNotInHive(), WorldGen.SpreadDesertWalls(), DelegateMethods.SpreadDirt(), WorldGen.SpreadGrass(), DelegateMethods.SpreadLightOpen_StopForSolids(), DelegateMethods.SpreadTest(), WorldGen.Statue(), SmartCursorHelper.Step_Acorns(), SmartCursorHelper.Step_ActuationRod(), SmartCursorHelper.Step_Actuators(), SmartCursorHelper.Step_AlchemySeeds(), SmartCursorHelper.Step_Axe(), SmartCursorHelper.Step_BlocksFilling(), SmartCursorHelper.Step_BlocksLines(), SmartCursorHelper.Step_Boulders(), SmartCursorHelper.Step_ClayPots(), SmartCursorHelper.Step_ForceCursorToAnyMinableThing(), SmartCursorHelper.Step_GemCorns(), SmartCursorHelper.Step_GrassSeeds(), SmartCursorHelper.Step_Hammers(), SmartCursorHelper.Step_LawnMower(), SmartCursorHelper.Step_MinecartTracks(), SmartCursorHelper.Step_PaintBrush(), SmartCursorHelper.Step_PaintRoller(), SmartCursorHelper.Step_PaintScrapper(), SmartCursorHelper.Step_Pickaxe_MineShinies(), SmartCursorHelper.Step_Pickaxe_MineSolids(), SmartCursorHelper.Step_Pigronata(), SmartCursorHelper.Step_PlanterBox(), SmartCursorHelper.Step_Platforms(), SmartCursorHelper.Step_PumpkinSeeds(), SmartCursorHelper.Step_StaffOfRegrowth(), SmartCursorHelper.Step_Torch(), SmartCursorHelper.Step_Walls(), Collision.StepConveyorBelt(), Player.StickyMovement(), Collision.StickyTiles(), WorldGen.StonePatch(), DD2Event.SummonCrystalDirect(), WorldGen.SwitchCannon(), WorldGen.SwitchFountain(), WorldGen.SwitchMB(), WorldGen.SwitchMonolith(), Collision.SwitchTiles(), WorldGen.templeCleaner(), WorldGen.templePart2(), WorldGen.templePather(), Sign.TextSign(), Collision.TileCollision(), WorldGen.tileCountAndDestroy(), WorldGen.tileCounterKill(), WorldGen.tileCounterNext(), WorldGen.TileEmpty(), WorldGen.TileFrame(), Player.TileInteractionsCheck(), Player.TileInteractionsCheckLongDistance(), WorldGen.TileIsExposedToAir(), WorldGen.TileRunner(), WorldGen.TileType(), WorldGen.ToggleGemLock(), HiveBiome.TooCloseToImportantLocations(), WorldGen.TopEdgeCanBeAttachedTo(), Player.TorchAttack(), ToString(), Minecart.TrackColors(), WorldGen.TreeGrowFXCheck(), Player.TryBouncingBlocks(), DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryCloseDoor(), DoorOpeningHelper.TallGateOpeningInfoProvider.TryCloseDoor(), TETeleportationPylon.TryGetPylonTypeFromTileCoords(), WorldGen.TryGrowingAbigailsFlower(), WorldGen.TryGrowingGlowTulip(), Player.TryInteractingWithMinecartTrackInNearbyArea(), WorldGen.TryKillingReplaceableTile(), WorldGen.TryKillingTreesAboveIfTheyWouldBecomeInvalid(), Player.TryLandingOnDetonator(), Player.TryPlacingAGolfBallNearANearbyTee(), Player.TryRecalculatingTorchLuck(), AmbientWindSystem.TrySpawningWind(), WorldGen.TryToggleLight(), LegacyLighting.TryUpdatingMapWithLight(), Player.TryUsingDiggerCart(), Collision.TupleHitLine(), Gore.Update(), Player.Update(), Mount.UpdateFrame(), LegacyLighting.UpdateLightToSkyColor(), Wiring.UpdateMech(), PressurePlateHelper.UpdatePlayerPosition(), WorldGen.UpdateWorld_GrassGrowth(), WorldGen.UpdateWorld_OvergroundTile(), WorldGen.UpdateWorld_UndergroundTile(), TEFoodPlatter.ValidTile(), TEItemFrame.ValidTile(), TELogicSensor.ValidTile(), TETrainingDummy.ValidTile(), TEWeaponsRack.ValidTile(), WorldGen.Spread.Wall(), WorldGen.Spread.Wall2(), WorldGen.Spread.WallDungeon(), Framing.WallFrame(), WorldGen.WaterCheck(), Collision.WetCollision(), WorldGen.WillWaterPlacedHereStayPut(), and WorldGen.WouldTileReplacementWork().