Terraria: Tile.honey
honey() [1/2]
bool Tile.honey () inline
References bTileHeader.
Referenced by Liquid.AttemptToMoveHoney(), WorldGen.CloudLake(), NetMessage.CompressTileBlock_Inner(), HiveBiome.CreateBlockedHoneyCube(), HiveBiome.CreateHiveTunnel(), NetMessage.DecompressTileBlock_Inner(), Liquid.DelWater(), WaterfallManager.FindWaterfalls(), WorldGen.FinishNotTheBees(), WorldGen.FinishRemixWorld(), Projectile.GetFishingPondState(), TELogicSensor.GetState(), TileLightScanner.GetTileMask(), Gore.Gore_UpdateLeaf(), honey(), Player.ItemCheck_UseBuckets(), WorldGen.KillTile_GetItemDrops(), Liquid.LiquidCheck(), liquidType(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), WorldFile.LoadWorldTiles(), WorldGen.NotTheBees(), WorldGen.PlaceDye(), WorldGen.plantDye(), WorldFile.SaveWorldTiles(), Liquid.SettleWaterAt(), NPC.SpawnNPC(), Liquid.Update(), and Collision.WetCollision().