Terraria: Tile.inActive
inActive() [1/2]
bool Tile.inActive () inline
References sTileHeader.
Referenced by actColor(), WorldGen.ActiveAndWalkableTile(), Wiring.Actuate(), Wiring.ActuateForced(), Collision.AdvancedTileCollision(), Projectile.AI_067_FreakingPirates(), Collision.AnyCollision(), Collision.AnyCollisionWithSpecificTiles(), WorldGen.BottomEdgeCanBeAttachedTo(), Collision.CanHit(), Collision.CanHitLine(), Collision.CanHitWithCheck(), DelegateMethods.CastLightOpen(), DelegateMethods.CastLightOpen_StopForSolids(), DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Player.CheckForGoodTeleportationSpot(), DelegateMethods.CheckStopForSolids(), Clear(), ClearTile(), NetMessage.CompressTileBlock_Inner(), Wiring.DeActive(), NetMessage.DecompressTileBlock_Inner(), TileDrawing.DrawSingleTile(), TileDrawing.DrawTile_LiquidBehindTile(), Mount.DrillSmartCursor_Blocks(), DelegateMethods.EmitGolfCartDust_StopForSolids(), MessageBuffer.GetData(), TileDrawing.GetFinalLight(), TileLightScanner.GetTileMask(), WorldGen.hardUpdateWorld(), Collision.HitTiles(), Collision.HurtTiles(), inActive(), TileDrawing.IsTileDangerous(), Collision.IsWorldPointSolid(), Player.ItemCheck_UseWiringTools(), WorldGen.KillTile(), WorldGen.LeftEdgeCanBeAttachedTo(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), WorldFile.LoadWorldTiles(), Wiring.ReActive(), WorldGen.RightEdgeCanBeAttachedTo(), WorldFile.SaveWorldTiles(), NetMessage.SendData(), Collision.SlopeCollision(), Collision.SolidCollision(), WorldGen.SolidOrSlopedTile(), WorldGen.SolidTile(), WorldGen.SolidTile2(), WorldGen.SolidTile3(), WorldGen.SolidTileAllowBottomSlope(), WorldGen.SolidTileAllowLeftSlope(), WorldGen.SolidTileAllowRightSlope(), WorldGen.SolidTileAllowTopSlope(), WorldGen.SolidTileNoAttach(), Collision.SolidTiles(), DelegateMethods.SpreadLightOpen_StopForSolids(), SmartCursorHelper.Step_ActuationRod(), SmartCursorHelper.Step_GrassSeeds(), SmartCursorHelper.Step_Pickaxe_MineSolids(), SmartCursorHelper.Step_StaffOfRegrowth(), Collision.StickyTiles(), Collision.TileCollision(), WorldGen.TileEmpty(), WorldGen.TopEdgeCanBeAttachedTo(), Collision.TupleHitLine(), and WorldGen.UpdateWorld_GrassGrowth().