Terraria: Tile.nactive
nactive()
bool Tile.nactive () inline
References sTileHeader.
Referenced by WorldGen.AddLifeCrystal(), Liquid.AddWater(), NPC.AI(), NPC.AI_003_Fighters(), NPC.AI_006_Worms(), Projectile.AI_007_GrapplingHooks(), NPC.AI_007_TownEntities(), NPC.AI_007_TownEntities_GetWalkPrediction(), Projectile.AI_016(), NPC.AI_026_Unicorns(), NPC.AI_037_Destroyer(), NPC.AI_065_Butterflies(), NPC.AI_084_LunaticCultist(), NPC.AI_107_ImprovedWalkers(), NPC.AI_109_DarkMage(), NPC.AI_112_FairyCritter(), NPC.AI_113_WindyBalloon(), NPC.AI_114_Dragonflies(), NPC.AI_115_LadyBugs(), NPC.AI_121_QueenSlime(), NPC.AI_125_ClumsySlimeBalloon(), NPC.AI_AttemptToFindTeleportSpot(), WorldGen.AnchorValid(), WorldGen.BlockBelowMakesSandConvertIntoHardenedSand(), WorldGen.BlockBelowMakesSandFall(), NPC.BloodNautilus_CallForHelp(), TileObject.CanPlace(), WorldGen.CanPlaceSink(), WorldGen.CanUnderwaterPlantGrowHere(), WorldGen.Check1x2Top(), WorldGen.Check3x2(), WorldGen.Check3x3(), WorldGen.Check6x3(), WorldGen.CheckAlch(), WorldGen.CheckBanner(), WorldGen.CheckCactus(), WorldGen.CheckCatTail(), WorldGen.CheckChand(), Player.CheckCrackedBrickBreak(), WorldGen.CheckDye(), BallCollision.CheckForPassThrough(), Player.CheckIceBreak(), WorldGen.CheckMB(), WorldGen.CheckOrb(), WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), WorldGen.CheckRoom(), Player.CheckSpawn_Internal(), WorldGen.CheckSunflower(), Liquid.DelWater(), WaterfallManager.DrawWaterfall(), WorldGen.EmptyLiquid(), WorldGen.FixHeart(), NPC.GetBirdFlightRecommendation(), BallCollision.GetCollisionPointForTile(), Player.GetFloorTile(), Player.GetHurtTile(), TileDrawing.GetTileDrawData(), WorldGen.GetTileVisualHitbox(), WorldGen.GrowCactus(), WorldGen.GrowShroom(), WorldGen.GrowTree(), WorldGen.GrowTreeWithSettings(), WorldGen.GrowUndergroundTree(), NPC.HitEffect(), BallCollision.IsNeighborSolid(), NPC.IsValidSpawningGroundTile(), Player.ItemCheck_Shoot(), Player.ItemCheck_UseBuckets(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), WorldGen.mayanTrap(), Player.MinionRestTargetAim(), Main.oldDrawWater(), WorldGen.Place1x1(), WorldGen.Place1x2Top(), WorldGen.Place2x2(), WorldGen.Place3x2(), WorldGen.Place3x3(), WorldGen.Place6x3(), WorldGen.PlaceAlch(), WorldGen.PlaceBanner(), WorldGen.PlaceCatTail(), WorldGen.PlaceChand(), WorldGen.PlaceDoor(), WorldGen.PlaceDye(), WorldGen.PlaceLiquid(), WorldGen.PlaceOnTable1x1(), WorldGen.PlacePot(), WorldGen.PlaceSign(), WorldGen.PlaceSunflower(), Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), WorldGen.PlaceTile(), WorldGen.placeTrap(), WorldGen.PlantAlch(), WorldGen.PlantCheck(), WorldGen.ScoreRoom(), Liquid.SettleWaterAt(), Main.snowing(), Player.Spawn_DescendFromDefaultSpace(), Player.Spawn_ForceClearArea(), Player.Spawn_IsAreaAValidWorldSpawn(), NPC.SpawnNPC(), NPC.SpawnOnPlayer(), WorldGen.SpawnTownNPC(), WorldGen.SpawnTravelNPC(), WorldGen.StartRoomCheck(), SmartCursorHelper.Step_AlchemySeeds(), SmartCursorHelper.Step_Boulders(), SmartCursorHelper.Step_ClayPots(), Collision.StepConveyorBelt(), Collision.StepDown(), Collision.StepUp(), PortalHelper.SupportedHalfbrick(), PortalHelper.SupportedNormal(), PortalHelper.SupportedSlope(), WorldGen.TileFrame(), Minecart.TrackCollision(), Player.TryBouncingBlocks(), NPC.TryFindingFloor(), Liquid.Update(), WorldGen.UpdateWorld_OvergroundTile(), WorldGen.UpdateWorld_UndergroundTile(), Collision.WalkDownSlope(), and WorldGen.WaterCheck().