Terraria: Tile.isTheSameAs
isTheSameAs()
bool Tile.isTheSameAs (Tile compTile) inline
     {
         if (compTile == null)
         {
             return false;
         }
         if (sTileHeader != compTile.sTileHeader)
         {
             return false;
         }
         if (active())
         {
             if (type != compTile.type)
             {
                 return false;
             }
             if (Main.tileFrameImportant[type] && (frameX != compTile.frameX || frameY != compTile.frameY))
             {
                 return false;
             }
         }
         if (wall != compTile.wall || liquid != compTile.liquid)
         {
             return false;
         }
         if (compTile.liquid == 0)
         {
             if (wallColor() != compTile.wallColor())
             {
                 return false;
             }
             if (wire4() != compTile.wire4())
             {
                 return false;
             }
         }
         else if (bTileHeader != compTile.bTileHeader)
         {
             return false;
         }
         if (invisibleBlock() != compTile.invisibleBlock() || invisibleWall() != compTile.invisibleWall() || fullbrightBlock() != compTile.fullbrightBlock() || fullbrightWall() != compTile.fullbrightWall())
         {
             return false;
         }
         return true;
     }
References active(), bTileHeader, frameX, frameY, fullbrightBlock(), fullbrightWall(), invisibleBlock(), invisibleWall(), liquid, sTileHeader, Main.tileFrameImportant, type, wall, wallColor(), and wire4().
Referenced by NetMessage.CompressTileBlock_Inner(), and WorldFile.SaveWorldTiles().