Terraria: System.Xml.Xsl.XsltOld.CopyAttributesAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.CopyAttributesAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 14 of file CopyAttributesAction.cs.
    {
        while (processor.CanContinue)
        {
            switch (frame.State)
            {
            default:
                return;
            case 0:
                if (!frame.Node.HasAttributes || !frame.Node.MoveToFirstAttribute())
                {
                    frame.Finished();
                    return;
                }
                frame.State = 2;
                goto case 2;
            case 2:
                if (SendBeginEvent(processor, frame.Node))
                {
                    frame.State = 3;
                    break;
                }
                return;
            case 3:
                if (SendTextEvent(processor, frame.Node))
                {
                    frame.State = 4;
                    break;
                }
                return;
            case 4:
                if (SendEndEvent(processor, frame.Node))
                {
                    frame.State = 5;
                    break;
                }
                return;
            case 5:
                if (frame.Node.MoveToNextAttribute())
                {
                    frame.State = 2;
                    break;
                }
                frame.Node.MoveToParent();
                frame.Finished();
                return;
            case 1:
                return;
            }
        }
    }
References System.Xml.Dictionary, System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Xml.XPath.XPathNavigator.HasAttributes, System.Xml.XPath.XPathNavigator.MoveToFirstAttribute(), System.Xml.XPath.XPathNavigator.MoveToNextAttribute(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.Xsl.XsltOld.ActionFrame.Node, System.Xml.Xsl.XsltOld.CopyAttributesAction.SendBeginEvent(), System.Xml.Xsl.XsltOld.CopyAttributesAction.SendEndEvent(), System.Xml.Xsl.XsltOld.CopyAttributesAction.SendTextEvent(), and System.Xml.Xsl.XsltOld.ActionFrame.State.