Terraria: System.IO.StreamWriter.WriteLineAsync
WriteLineAsync() [5/7]
override Task System.IO.StreamWriter.WriteLineAsync (ReadOnlyMemory< char > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.TextWriter.
Definition at line 760 of file StreamWriter.cs.
    {
        if (GetType() != typeof(StreamWriter))
        {
            return base.WriteLineAsync(buffer, cancellationToken);
        }
        ThrowIfDisposed();
        CheckAsyncTaskInProgress();
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled(cancellationToken);
        }
        return _asyncWriteTask = WriteAsyncInternal(buffer, appendNewLine: true, cancellationToken);
    }
References System.IO.StreamWriter._asyncWriteTask, System.buffer, System.cancellationToken, System.IO.StreamWriter.CheckAsyncTaskInProgress(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.IO.StreamWriter.ThrowIfDisposed(), and System.IO.StreamWriter.WriteAsyncInternal().