Terraria: System.IO.StreamWriter.FlushAsyncInternal
FlushAsyncInternal()
Task System.IO.StreamWriter.FlushAsyncInternal (bool flushStream, bool flushEncoder, CancellationToken cancellationToken = default(CancellationToken)) inline private
Definition at line 786 of file StreamWriter.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled(cancellationToken);
        }
        if (_charPos == 0 && !flushStream && !flushEncoder)
        {
            return Task.CompletedTask;
        }
        return Core(flushStream, flushEncoder, cancellationToken);
        async Task Core(bool flushStream, bool flushEncoder, CancellationToken cancellationToken)
        {
            if (!_haveWrittenPreamble)
            {
                _haveWrittenPreamble = true;
                byte[] preamble = _encoding.GetPreamble();
                if (preamble.Length != 0)
                {
                    await _stream.WriteAsync(new ReadOnlyMemory<byte>(preamble), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            byte[] array = _byteBuffer ?? (_byteBuffer = new byte[_encoding.GetMaxByteCount(_charBuffer.Length)]);
            int bytes = _encoder.GetBytes(new ReadOnlySpan<char>(_charBuffer, 0, _charPos), array, flushEncoder);
            _charPos = 0;
            if (bytes > 0)
            {
                await _stream.WriteAsync(new ReadOnlyMemory<byte>(array, 0, bytes), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (flushStream)
            {
                await _stream.FlushAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
    }
References System.IO.StreamWriter._byteBuffer, System.IO.StreamWriter._charBuffer, System.IO.StreamWriter._charPos, System.IO.StreamWriter._encoder, System.IO.StreamWriter._encoding, System.IO.StreamWriter._haveWrittenPreamble, System.IO.StreamWriter._stream, System.array, System.bytes, System.cancellationToken, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.FlushAsync(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Text.Encoder.GetBytes(), System.Text.Encoding.GetMaxByteCount(), System.Text.Encoding.GetPreamble(), and System.IO.Stream.WriteAsync().
Referenced by System.IO.StreamWriter.FlushAsync(), System.IO.StreamWriter.WriteAsyncInternal(), and System.IO.StreamWriter.WriteAsyncInternal().