Terraria: System.IO.StreamWriter.WriteLine
WriteLine() [17/20]
override void System.IO.StreamWriter.WriteLine (string? value) inline virtual
Reimplemented from System.IO.TextWriter.
Definition at line 434 of file StreamWriter.cs.
    {
        CheckAsyncTaskInProgress();
        WriteSpan(value, appendNewLine: true);
    }
References System.IO.StreamWriter.CheckAsyncTaskInProgress(), System.value, and System.IO.StreamWriter.WriteSpan().
Referenced by Terraria.Netplay.AddBan(), Terraria.RemoteServer.ClientReadCallBack(), Terraria.Netplay.InnerClientLoop(), Terraria.Map.WorldMap.Load(), and Terraria.Map.MapHelper.SaveMap().