Terraria: System.IO.StreamWriter.ThrowIfDisposed
ThrowIfDisposed()
void System.IO.StreamWriter.ThrowIfDisposed () inline private
Definition at line 822 of file StreamWriter.cs.
    {
        if (_disposed)
        {
            ThrowObjectDisposedException();
        }
        void ThrowObjectDisposedException()
        {
            throw new ObjectDisposedException(GetType().Name, SR.ObjectDisposed_WriterClosed);
        }
    }
References System.IO.StreamWriter._disposed, System.Name, and System.SR.ObjectDisposed_WriterClosed.
Referenced by System.IO.StreamWriter.Flush(), System.IO.StreamWriter.FlushAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StreamWriter.WriteLineAsync(), and System.IO.StreamWriter.WriteSpan().