Terraria: Terraria.GameContent.Biomes.Desert.PitEntrance.PlaceAt
PlaceAt()
static void Terraria.GameContent.Biomes.Desert.PitEntrance.PlaceAt (DesertDescription description, Point position, int holeRadius) inline static private
Definition at line 16 of file PitEntrance.cs.
    {
        for (int i = -holeRadius - 3; i < holeRadius + 3; i++)
        {
            for (int j = description.Surface[i + position.X]; j <= description.Hive.Top + 10; j++)
            {
                double value = (double)(j - description.Surface[i + position.X]) / (double)(description.Hive.Top - description.Desert.Top);
                value = Utils.Clamp(value, 0.0, 1.0);
                int num = (int)(GetHoleRadiusScaleAt(value) * (double)holeRadius);
                if (Math.Abs(i) < num)
                {
                    Main.tile[i + position.X, j].ClearEverything();
                }
                else if (Math.Abs(i) < num + 3 && value > 0.35)
                {
                    Main.tile[i + position.X, j].ResetToType(397);
                }
                double num2 = Math.Abs((double)i / (double)holeRadius);
                num2 *= num2;
                if (Math.Abs(i) < num + 3 && (double)(j - position.Y) > 15.0 - 3.0 * num2)
                {
                    Main.tile[i + position.X, j].wall = 187;
                    WorldGen.SquareWallFrame(i + position.X, j - 1);
                    WorldGen.SquareWallFrame(i + position.X, j);
                }
            }
        }
        holeRadius += 4;
        for (int k = -holeRadius; k < holeRadius; k++)
        {
            int num3 = holeRadius - Math.Abs(k);
            num3 = Math.Min(10, num3 * num3);
            for (int l = 0; l < num3; l++)
            {
                Main.tile[k + position.X, l + description.Surface[k + position.X]].ClearEverything();
            }
        }
    }
References System.Math.Abs(), Terraria.GameContent.Biomes.Desert.DesertDescription.Desert, Terraria.GameContent.Biomes.Desert.PitEntrance.GetHoleRadiusScaleAt(), Terraria.GameContent.Biomes.Desert.DesertDescription.Hive, System.Math.Min(), Terraria.WorldGen.SquareWallFrame(), Terraria.GameContent.Biomes.Desert.DesertDescription.Surface, Terraria.Main.tile, Microsoft.Xna.Framework.Rectangle.Top, System.value, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.Desert.PitEntrance.Place().