Terraria: System.IO.StreamWriter.WriteLineAsync
WriteLineAsync() [6/7]
override Task System.IO.StreamWriter.WriteLineAsync (string? value) inline virtual
Reimplemented from System.IO.TextWriter.
Definition at line 718 of file StreamWriter.cs.
    {
        if (value == null)
        {
            return WriteLineAsync();
        }
        if (GetType() != typeof(StreamWriter))
        {
            return base.WriteLineAsync(value);
        }
        ThrowIfDisposed();
        CheckAsyncTaskInProgress();
        return _asyncWriteTask = WriteAsyncInternal(value.AsMemory(), appendNewLine: true, default(CancellationToken));
    }
References System.IO.StreamWriter._asyncWriteTask, System.IO.StreamWriter.CheckAsyncTaskInProgress(), System.IO.StreamWriter.ThrowIfDisposed(), System.value, System.IO.StreamWriter.WriteAsyncInternal(), and System.IO.StreamWriter.WriteLineAsync().