Terraria: System.IO.StreamWriter.WriteAsync
WriteAsync() [1/6]
override Task System.IO.StreamWriter.WriteAsync (char value) inline virtual
Reimplemented from System.IO.TextWriter.
Definition at line 572 of file StreamWriter.cs.
    {
        if (GetType() != typeof(StreamWriter))
        {
            return base.WriteAsync(value);
        }
        ThrowIfDisposed();
        CheckAsyncTaskInProgress();
        return _asyncWriteTask = WriteAsyncInternal(value, appendNewLine: false);
    }
References System.IO.StreamWriter._asyncWriteTask, System.IO.StreamWriter.CheckAsyncTaskInProgress(), System.IO.StreamWriter.ThrowIfDisposed(), System.value, and System.IO.StreamWriter.WriteAsyncInternal().