Terraria: System.IO.StreamWriter.WriteAsyncInternal
WriteAsyncInternal() [1/2]
async Task System.IO.StreamWriter.WriteAsyncInternal (char value, bool appendNewLine) inline private
Definition at line 583 of file StreamWriter.cs.
    {
        if (_charPos == _charLen)
        {
            await FlushAsyncInternal(flushStream: false, flushEncoder: false).ConfigureAwait(continueOnCapturedContext: false);
        }
        _charBuffer[_charPos++] = value;
        if (appendNewLine)
        {
            for (int i = 0; i < CoreNewLine.Length; i++)
            {
                if (_charPos == _charLen)
                {
                    await FlushAsyncInternal(flushStream: false, flushEncoder: false).ConfigureAwait(continueOnCapturedContext: false);
                }
                _charBuffer[_charPos++] = CoreNewLine[i];
            }
        }
        if (_autoFlush)
        {
            await FlushAsyncInternal(flushStream: true, flushEncoder: false).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.IO.StreamWriter._autoFlush, System.IO.StreamWriter._charBuffer, System.IO.StreamWriter._charLen, System.IO.StreamWriter._charPos, System.IO.TextWriter.CoreNewLine, System.IO.StreamWriter.FlushAsyncInternal(), and System.value.
Referenced by System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteAsync(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StreamWriter.WriteLineAsync(), System.IO.StreamWriter.WriteLineAsync(), and System.IO.StreamWriter.WriteLineAsync().