Terraria: System.IO.StreamWriter.WriteFormatHelper
WriteFormatHelper()
void System.IO.StreamWriter.WriteFormatHelper (string format, ParamsArray args, bool appendNewLine) inline private
Definition at line 454 of file StreamWriter.cs.
    {
        StringBuilder stringBuilder = StringBuilderCache.Acquire((format?.Length ?? 0) + args.Length * 8).AppendFormatHelper(null, format, args);
        StringBuilder.ChunkEnumerator chunks = stringBuilder.GetChunks();
        bool flag = chunks.MoveNext();
        while (flag)
        {
            ReadOnlySpan<char> span = chunks.Current.Span;
            flag = chunks.MoveNext();
            WriteSpan(span, !flag && appendNewLine);
        }
        StringBuilderCache.Release(stringBuilder);
    }
References System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.ChunkEnumerator.Current, System.format, System.Text.StringBuilder.GetChunks(), System.ParamsArray.Length, System.Text.StringBuilder.ChunkEnumerator.MoveNext(), System.Text.StringBuilderCache.Release(), System.ReadOnlyMemory< T >.Span, and System.IO.StreamWriter.WriteSpan().
Referenced by System.IO.StreamWriter.Write(), System.IO.StreamWriter.Write(), System.IO.StreamWriter.Write(), System.IO.StreamWriter.Write(), System.IO.StreamWriter.WriteLine(), System.IO.StreamWriter.WriteLine(), System.IO.StreamWriter.WriteLine(), and System.IO.StreamWriter.WriteLine().