Terraria: System.IO.StreamWriter.CloseStreamFromDispose
CloseStreamFromDispose()
void System.IO.StreamWriter.CloseStreamFromDispose (bool disposing) inline private
Definition at line 221 of file StreamWriter.cs.
    {
        if (!_closable || _disposed)
        {
            return;
        }
        try
        {
            if (disposing)
            {
                _stream.Close();
            }
        }
        finally
        {
            _disposed = true;
            _charLen = 0;
            base.Dispose(disposing);
        }
    }
References System.IO.StreamWriter._charLen, System.IO.StreamWriter._closable, System.IO.StreamWriter._disposed, System.IO.StreamWriter._stream, and System.IO.Stream.Close().
Referenced by System.IO.StreamWriter.Dispose(), and System.IO.StreamWriter.DisposeAsyncCore().