Terraria: System.IO.StreamWriter.WriteAsync
WriteAsync() [2/6]
override Task System.IO.StreamWriter.WriteAsync (char[] buffer, int index, int count) inline virtual
Reimplemented from System.IO.TextWriter.
Definition at line 622 of file StreamWriter.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer", SR.ArgumentNull_Buffer);
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentException(SR.Argument_InvalidOffLen);
        }
        if (GetType() != typeof(StreamWriter))
        {
            return base.WriteAsync(buffer, index, count);
        }
        ThrowIfDisposed();
        CheckAsyncTaskInProgress();
        return _asyncWriteTask = WriteAsyncInternal(new ReadOnlyMemory<char>(buffer, index, count), appendNewLine: false, default(CancellationToken));
    }
References System.IO.StreamWriter._asyncWriteTask, System.SR.Argument_InvalidOffLen, System.SR.ArgumentNull_Buffer, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.buffer, System.IO.StreamWriter.CheckAsyncTaskInProgress(), System.count, System.index, System.IO.StreamWriter.ThrowIfDisposed(), and System.IO.StreamWriter.WriteAsyncInternal().