Terraria: System.IO.StreamWriter.DisposeAsyncCore
DisposeAsyncCore()
async ValueTask System.IO.StreamWriter.DisposeAsyncCore () inline private
Definition at line 251 of file StreamWriter.cs.
    {
        try
        {
            if (!_disposed)
            {
                await FlushAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        finally
        {
            CloseStreamFromDispose(disposing: true);
        }
        GC.SuppressFinalize(this);
    }
References System.IO.StreamWriter._disposed, System.IO.StreamWriter.CloseStreamFromDispose(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.StreamWriter.FlushAsync(), and System.GC.SuppressFinalize().
Referenced by System.IO.StreamWriter.DisposeAsync().