Terraria: System.IO.StreamWriter.WriteSpan
WriteSpan()
unsafe void System.IO.StreamWriter.WriteSpan (ReadOnlySpan< char > buffer, bool appendNewLine) inline private
Definition at line 369 of file StreamWriter.cs.
    {
        CheckAsyncTaskInProgress();
        if (buffer.Length <= 4 && buffer.Length <= _charLen - _charPos)
        {
            for (int i = 0; i < buffer.Length; i++)
            {
                _charBuffer[_charPos++] = buffer[i];
            }
        }
        else
        {
            ThrowIfDisposed();
            char[] charBuffer = _charBuffer;
            fixed (char* ptr = &MemoryMarshal.GetReference(buffer))
            {
                fixed (char* ptr3 = &charBuffer[0])
                {
                    char* ptr2 = ptr;
                    int num = buffer.Length;
                    int num2 = _charPos;
                    while (num > 0)
                    {
                        if (num2 == charBuffer.Length)
{
                            Flush(flushStream: false, flushEncoder: false);
                            num2 = 0;
                        }
                        int num3 = Math.Min(charBuffer.Length - num2, num);
                        int num4 = num3 * 2;
                        Buffer.MemoryCopy(ptr2, ptr3 + num2, num4, num4);
                        _charPos += num3;
                        num2 += num3;
                        ptr2 += num3;
                        num -= num3;
                    }
                }
            }
        }
        if (appendNewLine)
        {
            char[] coreNewLine = CoreNewLine;
            for (int j = 0; j < coreNewLine.Length; j++)
            {
                if (_charPos == _charLen)
                {
                    Flush(flushStream: false, flushEncoder: false);
                }
                _charBuffer[_charPos] = coreNewLine[j];
                _charPos++;
            }
        }
        if (_autoFlush)
        {
            Flush(flushStream: true, flushEncoder: false);
        }
    }
References System.IO.StreamWriter._autoFlush, System.IO.StreamWriter._charBuffer, System.IO.StreamWriter._charLen, System.IO.StreamWriter._charPos, System.buffer, System.IO.StreamWriter.CheckAsyncTaskInProgress(), System.IO.TextWriter.CoreNewLine, System.IO.StreamWriter.Flush(), System.Buffer.MemoryCopy(), System.Math.Min(), and System.IO.StreamWriter.ThrowIfDisposed().
Referenced by System.IO.StreamWriter.Write(), System.IO.StreamWriter.Write(), System.IO.StreamWriter.Write(), System.IO.StreamWriter.Write(), System.IO.StreamWriter.WriteFormatHelper(), System.IO.StreamWriter.WriteLine(), and System.IO.StreamWriter.WriteLine().