Terraria: System.IO.StreamWriter.WriteAsyncInternal
WriteAsyncInternal() [2/2]
async Task System.IO.StreamWriter.WriteAsyncInternal (ReadOnlyMemory< char > source, bool appendNewLine, CancellationToken cancellationToken) inline private
Definition at line 664 of file StreamWriter.cs.
    {
        int num;
        for (int copied = 0; copied < source.Length; copied += num)
        {
            if (_charPos == _charLen)
            {
                await FlushAsyncInternal(flushStream: false, flushEncoder: false, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            num = Math.Min(_charLen - _charPos, source.Length - copied);
            ReadOnlySpan<char> readOnlySpan = source.Span;
            readOnlySpan = readOnlySpan.Slice(copied, num);
            readOnlySpan.CopyTo(new Span<char>(_charBuffer, _charPos, num));
            _charPos += num;
        }
        if (appendNewLine)
        {
            for (int i = 0; i < CoreNewLine.Length; i++)
            {
                if (_charPos == _charLen)
                {
                    await FlushAsyncInternal(flushStream: false, flushEncoder: false, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
                _charBuffer[_charPos++] = CoreNewLine[i];
            }
        }
        if (_autoFlush)
        {
            await FlushAsyncInternal(flushStream: true, flushEncoder: false, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.IO.StreamWriter._autoFlush, System.IO.StreamWriter._charBuffer, System.IO.StreamWriter._charLen, System.IO.StreamWriter._charPos, System.cancellationToken, System.ReadOnlySpan< T >.CopyTo(), System.IO.TextWriter.CoreNewLine, System.IO.StreamWriter.FlushAsyncInternal(), System.Math.Min(), System.ReadOnlySpan< T >.Slice(), and System.source.