Terraria: System.String.Compare
Compare() [10/10]
static int System.String.Compare (string? strA, string? strB, StringComparison comparisonType) inline static
Definition at line 223 of file String.cs.
    {
        if ((object)strA == strB)
        {
            CheckStringComparison(comparisonType);
            return 0;
        }
        if ((object)strA == null)
        {
            CheckStringComparison(comparisonType);
            return -1;
        }
        if ((object)strB == null)
        {
            CheckStringComparison(comparisonType);
            return 1;
        }
        switch (comparisonType)
        {
        case StringComparison.CurrentCulture:
        case StringComparison.CurrentCultureIgnoreCase:
            return CultureInfo.CurrentCulture.CompareInfo.Compare(strA, strB, GetCaseCompareOfComparisonCulture(comparisonType));
        case StringComparison.InvariantCulture:
        case StringComparison.InvariantCultureIgnoreCase:
            return CompareInfo.Invariant.Compare(strA, strB, GetCaseCompareOfComparisonCulture(comparisonType));
        case StringComparison.Ordinal:
            if (strA._firstChar != strB._firstChar)
            {
                return strA._firstChar - strB._firstChar;
            }
            return CompareOrdinalHelper(strA, strB);
        case StringComparison.OrdinalIgnoreCase:
            return Ordinal.CompareStringIgnoreCase(ref strA.GetRawStringData(), strA.Length, ref strB.GetRawStringData(), strB.Length);
        default:
            throw new ArgumentException(SR.NotSupported_StringComparison, "comparisonType");
        }
    }
References System.String.CheckStringComparison(), System.String.CompareOrdinalHelper(), System.Globalization.Ordinal.CompareStringIgnoreCase(), System.comparisonType, System.Globalization.CultureInfo.CurrentCulture, System.String.GetCaseCompareOfComparisonCulture(), System.Globalization.CompareInfo.Invariant, and System.SR.NotSupported_StringComparison.