Terraria: System.String.SplitInternal
SplitInternal() [3/3]
string[] System.String.SplitInternal (string separator, string[] separators, int count, StringSplitOptions options) inline private
Definition at line 2675 of file String.cs.
    {
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", SR.ArgumentOutOfRange_NegativeCount);
        }
        CheckStringSplitOptions(options);
        bool flag = (object)separator != null;
        if (!flag && (separators == null || separators.Length == 0))
        {
            return SplitInternal(default(ReadOnlySpan<char>), count, options);
        }
        while (true)
        {
            if (count <= 1 || Length == 0)
            {
                string text = this;
                if ((options & StringSplitOptions.TrimEntries) != 0 && count > 0)
                {
                    text = text.Trim();
                }
                if ((options & StringSplitOptions.RemoveEmptyEntries) != 0 && text.Length == 0)
                {
                    count = 0;
                }
                if (count != 0)
                {
                    return new string[1] { text };
                }
                return Array.Empty<string>();
            }
            if (!flag)
            {
                break;
            }
            if (separator.Length == 0)
            {
                count = 1;
                continue;
            }
            return SplitInternal(separator, count, options);
        }
        Span<int> initialSpan = stackalloc int[128];
        ValueListBuilder<int> sepListBuilder = new ValueListBuilder<int>(initialSpan);
        initialSpan = stackalloc int[128];
        ValueListBuilder<int> lengthListBuilder = new ValueListBuilder<int>(initialSpan);
        MakeSeparatorList(separators, ref sepListBuilder, ref lengthListBuilder);
        ReadOnlySpan<int> sepList = sepListBuilder.AsSpan();
        ReadOnlySpan<int> lengthList = lengthListBuilder.AsSpan();
        if (sepList.Length == 0)
        {
            return new string[1] { this };
        }
        string[] result = ((options != 0) ? SplitWithPostProcessing(sepList, lengthList, 0, count, options) : SplitWithoutPostProcessing(sepList, lengthList, 0, count));
        sepListBuilder.Dispose();
        lengthListBuilder.Dispose();
        return result;
    }
References System.SR.ArgumentOutOfRange_NegativeCount, System.String.CheckStringSplitOptions(), System.count, System.String.Length, System.String.MakeSeparatorList(), System.options, System.String.SplitInternal(), System.String.SplitWithoutPostProcessing(), System.String.SplitWithPostProcessing(), and System.text.