Terraria: System.String.TrimHelper
TrimHelper()
unsafe string System.String.TrimHelper (char * trimChars, int trimCharsLength, TrimType trimType) inline private
Definition at line 3153 of file String.cs.
    {
        int num = Length - 1;
        int i = 0;
        if ((trimType & TrimType.Head) != 0)
        {
            for (i = 0; i < Length; i++)
            {
                int num2 = 0;
                char c = this[i];
                for (num2 = 0; num2 < trimCharsLength && trimChars[num2] != c; num2++)
                {
                }
                if (num2 == trimCharsLength)
                {
                    break;
                }
            }
        }
        if ((trimType & TrimType.Tail) != 0)
        {
            for (num = Length - 1; num >= i; num--)
            {
                int num3 = 0;
                char c2 = this[num];
                for (num3 = 0; num3 < trimCharsLength && trimChars[num3] != c2; num3++)
                {
                }
                if (num3 == trimCharsLength)
                {
                    break;
                }
            }
        }
        return CreateTrimmedString(i, num);
    }
References System.String.CreateTrimmedString(), and System.String.Length.
Referenced by System.String.Trim(), System.String.Trim(), System.String.TrimEnd(), System.String.TrimEnd(), System.String.TrimStart(), and System.String.TrimStart().