Terraria: System.String.JoinCore
JoinCore() [2/3]
static string System.String.JoinCore (ReadOnlySpan< char > separator, ReadOnlySpan< string > values) inline static private
Definition at line 2164 of file String.cs.
    {
        if (values.Length <= 1)
        {
            object obj;
            if (!values.IsEmpty)
            {
                obj = values[0];
                if (obj == null)
                {
                    return Empty;
                }
            }
            else
            {
                obj = Empty;
            }
            return (string)obj;
        }
        long num = (long)(values.Length - 1) * (long)separator.Length;
        if (num > int.MaxValue)
        {
            ThrowHelper.ThrowOutOfMemoryException();
        }
        int num2 = (int)num;
        ReadOnlySpan<string> readOnlySpan = values;
        for (int i = 0; i < readOnlySpan.Length; i++)
        {
            string text = readOnlySpan[i];
            if ((object)text != null)
            {
                num2 += text.Length;
                if (num2 < 0)
                {
                    ThrowHelper.ThrowOutOfMemoryException();
                }
            }
        }
        string text2 = FastAllocateString(num2);
        int num3 = 0;
        for (int j = 0; j < values.Length; j++)
        {
            string text3 = values[j];
            if ((object)text3 != null)
            {
                int length = text3.Length;
                if (length > num2 - num3)
                {
                    num3 = -1;
                    break;
                }
                FillStringChecked(text2, num3, text3);
                num3 += length;
            }
            if (j < values.Length - 1)
            {
                ref char reference = ref Unsafe.Add(ref text2._firstChar, num3);
                if (separator.Length == 1)
                {
                    reference = separator[0];
                }
                else
                {
                    separator.CopyTo(new Span<char>(ref reference, separator.Length));
                }
                num3 += separator.Length;
            }
        }
        if (num3 != num2)
        {
            return JoinCore(separator, values.ToArray().AsSpan());
        }
        return text2;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.String.Empty, System.String.FastAllocateString(), System.String.FillStringChecked(), System.String.JoinCore(), System.length, System.obj, System.text, System.ThrowHelper.ThrowOutOfMemoryException(), and System.values.