Terraria: System.String.Replace
Replace() [2/4]
string System.String.Replace (string oldValue, string? newValue) inline
Definition at line 2436 of file String.cs.
    {
        if ((object)oldValue == null)
        {
            throw new ArgumentNullException("oldValue");
        }
        if (oldValue.Length == 0)
        {
            throw new ArgumentException(SR.Argument_StringZeroLength, "oldValue");
        }
        if ((object)newValue == null)
        {
            newValue = Empty;
        }
        Span<int> initialSpan = stackalloc int[128];
        ValueListBuilder<int> valueListBuilder = new ValueListBuilder<int>(initialSpan);
        if (oldValue.Length == 1)
        {
            if (newValue.Length == 1)
            {
                return Replace(oldValue[0], newValue[0]);
            }
            char value = oldValue[0];
            int num = 0;
            while (true)
            {
                int num2 = SpanHelpers.IndexOf(ref Unsafe.Add(ref _firstChar, num), value, Length - num);
                if (num2 == -1)
                {
                    break;
                }
                valueListBuilder.Append(num + num2);
                num += num2 + 1;
            }
        }
        else
        {
            int num3 = 0;
            while (true)
            {
                int num4 = SpanHelpers.IndexOf(ref Unsafe.Add(ref _firstChar, num3), Length - num3, ref oldValue._firstChar, oldValue.Length);
                if (num4 == -1)
                {
                    break;
                }
                valueListBuilder.Append(num3 + num4);
                num3 += num4 + oldValue.Length;
            }
        }
        if (valueListBuilder.Length == 0)
        {
            return this;
        }
        string result = ReplaceHelper(oldValue.Length, newValue, valueListBuilder.AsSpan());
        valueListBuilder.Dispose();
        return result;
    }
References System.String._firstChar, System.SR.Argument_StringZeroLength, System.String.Empty, System.SpanHelpers.IndexOf(), System.String.Length, System.String.Replace(), System.String.ReplaceHelper(), and System.value.