Terraria: System.String.InitializeProbabilisticMap
InitializeProbabilisticMap()
static unsafe void System.String.InitializeProbabilisticMap (uint * charMap, ReadOnlySpan< char > anyOf) inline static private
Definition at line 3337 of file String.cs.
    {
        bool flag = false;
        for (int i = 0; i < anyOf.Length; i++)
        {
            int num = anyOf[i];
            SetCharBit(charMap, (byte)num);
            num >>= 8;
            if (num == 0)
            {
                flag = true;
            }
            else
            {
                SetCharBit(charMap, (byte)num);
            }
        }
        if (flag)
        {
            *charMap |= 1u;
        }
    }
References System.String.SetCharBit().
Referenced by System.String.IndexOfCharArray(), System.String.LastIndexOfCharArray(), and System.String.MakeSeparatorList().