Terraria: System.String.CheckStringSplitOptions
CheckStringSplitOptions()
static void System.String.CheckStringSplitOptions (StringSplitOptions options) inline static private
Definition at line 2984 of file String.cs.
    {
        if (((uint)options & 0xFFFFFFFCu) != 0)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Argument_InvalidFlag, ExceptionArgument.options);
        }
    }
References System.options, and System.ThrowHelper.ThrowArgumentException().
Referenced by System.String.SplitInternal(), and System.String.SplitInternal().