Terraria: System.String.Compare
Compare() [5/10]
static int System.String.Compare (string? strA, int indexA, string? strB, int indexB, int length, StringComparison comparisonType) inline static
Definition at line 316 of file String.cs.
    {
        CheckStringComparison(comparisonType);
        if ((object)strA == null || (object)strB == null)
        {
            if ((object)strA == strB)
            {
                return 0;
            }
            if ((object)strA != null)
            {
                return 1;
            }
            return -1;
        }
        if (length < 0)
        {
            throw new ArgumentOutOfRangeException("length", SR.ArgumentOutOfRange_NegativeLength);
        }
        if (indexA < 0 || indexB < 0)
        {
            string paramName = ((indexA < 0) ? "indexA" : "indexB");
            throw new ArgumentOutOfRangeException(paramName, SR.ArgumentOutOfRange_Index);
        }
        if (strA.Length - indexA < 0 || strB.Length - indexB < 0)
        {
            string paramName2 = ((strA.Length - indexA < 0) ? "indexA" : "indexB");
            throw new ArgumentOutOfRangeException(paramName2, SR.ArgumentOutOfRange_Index);
        }
        if (length == 0 || ((object)strA == strB && indexA == indexB))
        {
            return 0;
        }
        int num = Math.Min(length, strA.Length - indexA);
        int num2 = Math.Min(length, strB.Length - indexB);
        switch (comparisonType)
        {
        case StringComparison.CurrentCulture:
        case StringComparison.CurrentCultureIgnoreCase:
            return CultureInfo.CurrentCulture.CompareInfo.Compare(strA, indexA, num, strB, indexB, num2, GetCaseCompareOfComparisonCulture(comparisonType));
        case StringComparison.InvariantCulture:
        case StringComparison.InvariantCultureIgnoreCase:
            return CompareInfo.Invariant.Compare(strA, indexA, num, strB, indexB, num2, GetCaseCompareOfComparisonCulture(comparisonType));
        case StringComparison.Ordinal:
            return CompareOrdinalHelper(strA, indexA, num, strB, indexB, num2);
        default:
            return Ordinal.CompareStringIgnoreCase(ref Unsafe.Add(ref strA.GetRawStringData(), indexA), num, ref Unsafe.Add(ref strB.GetRawStringData(), indexB), num2);
        }
    }
References System.SR.ArgumentOutOfRange_Index, System.SR.ArgumentOutOfRange_NegativeLength, System.String.CheckStringComparison(), System.String.CompareOrdinalHelper(), System.Globalization.Ordinal.CompareStringIgnoreCase(), System.comparisonType, System.Globalization.CultureInfo.CurrentCulture, System.String.GetCaseCompareOfComparisonCulture(), System.Globalization.CompareInfo.Invariant, System.length, and System.Math.Min().