Terraria: System.String.JoinCore
JoinCore() [3/3]
static string System.String.JoinCore (ReadOnlySpan< char > separator, string[] value, int startIndex, int count) inline static private
Definition at line 2014 of file String.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (startIndex < 0)
        {
            throw new ArgumentOutOfRangeException("startIndex", SR.ArgumentOutOfRange_StartIndex);
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", SR.ArgumentOutOfRange_NegativeCount);
        }
        if (startIndex > value.Length - count)
        {
            throw new ArgumentOutOfRangeException("startIndex", SR.ArgumentOutOfRange_IndexCountBuffer);
        }
        return JoinCore(separator, new ReadOnlySpan<string>(value, startIndex, count));
    }
References System.SR.ArgumentOutOfRange_IndexCountBuffer, System.SR.ArgumentOutOfRange_NegativeCount, System.SR.ArgumentOutOfRange_StartIndex, System.count, System.String.JoinCore(), System.startIndex, and System.value.
Referenced by System.String.Join(), System.String.Join(), System.String.Join(), System.String.Join(), System.String.Join(), System.String.Join(), System.String.Join(), System.String.Join< T >(), System.String.Join< T >(), System.String.JoinCore(), System.String.JoinCore(), and System.String.JoinCore< T >().