Terraria: System.String.MakeSeparatorListVectorized
MakeSeparatorListVectorized()
void System.String.MakeSeparatorListVectorized (ref ValueListBuilder< int > sepListBuilder, char c, char c2, char c3) inline private
Definition at line 2887 of file String.cs.
    {
        if (!Sse41.IsSupported)
        {
            throw new PlatformNotSupportedException();
        }
        Vector128<byte> mask = Vector128.Create(0, 2, 4, 6, 8, 10, 12, 14, byte.MaxValue, byte.MaxValue, byte.MaxValue, byte.MaxValue, byte.MaxValue, byte.MaxValue, byte.MaxValue, byte.MaxValue);
        Vector128<ushort> right = Vector128.Create(c);
        Vector128<ushort> right2 = Vector128.Create(c2);
        Vector128<ushort> right3 = Vector128.Create(c3);
        ref char reference = ref MemoryMarshal.GetReference(this.AsSpan());
        int num = Length & -Vector128<ushort>.Count;
        int i;
        for (i = 0; i < num; i += Vector128<ushort>.Count)
        {
            Vector128<ushort> left = ReadVector(ref reference, i);
            Vector128<ushort> right4 = Sse2.CompareEqual(left, right);
            right4 = Sse2.Or(Sse2.CompareEqual(left, right2), right4);
            right4 = Sse2.Or(Sse2.CompareEqual(left, right3), right4);
            if (Sse41.TestZ(right4, right4))
            {
                continue;
            }
            Vector128<byte> value = Sse2.ShiftRightLogical(right4.AsUInt64(), 4).AsByte();
            value = Ssse3.Shuffle(value, mask);
            uint num2 = Sse2.ConvertToUInt32(value.AsUInt32());
            value = Sse2.ShiftRightLogical(value.AsUInt64(), 32).AsByte();
            uint num3 = Sse2.ConvertToUInt32(value.AsUInt32());
            int num4 = i;
            while (num2 != 0)
            {
                if ((num2 & 0xFu) != 0)
                {
                    sepListBuilder.Append(num4);
                }
                num2 >>= 8;
                num4++;
            }
            int num5 = i + 4;
            while (num3 != 0)
            {
                if ((num3 & 0xFu) != 0)
                {
                    sepListBuilder.Append(num5);
                }
                num3 >>= 8;
                num5++;
            }
        }
        for (; i < Length; i++)
        {
            char c4 = Unsafe.Add(ref reference, (IntPtr)(uint)i);
            if (c4 == c || c4 == c2 || c4 == c3)
            {
                sepListBuilder.Append(i);
            }
        }
        static Vector128<ushort> ReadVector(ref char c0, int offset)
        {
            return Unsafe.ReadUnaligned<Vector128<ushort>>(ref Unsafe.As<char, byte>(ref Unsafe.Add(ref c0, (IntPtr)(uint)offset)));
        }
    }
References System.Runtime.Intrinsics.X86.Sse2.CompareEqual(), System.Runtime.Intrinsics.X86.Sse2.ConvertToUInt32(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.X86.Sse41.IsSupported, System.String.Length, System.offset, System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Ssse3.Shuffle(), System.Runtime.Intrinsics.X86.Sse41.TestZ(), and System.value.
Referenced by System.String.MakeSeparatorList().