Terraria: System.Reflection.Associates.AssignAssociates
AssignAssociates() [1/2]
static RuntimeMethodInfo System.Reflection.Associates.AssignAssociates (int tkMethod, RuntimeType declaredType, RuntimeType reflectedType) inline static private
Definition at line 35 of file Associates.cs.
    {
        if (MetadataToken.IsNullToken(tkMethod))
        {
            return null;
        }
        bool flag = declaredType != reflectedType;
        IntPtr[] array = null;
        int typeInstCount = 0;
        RuntimeType[] instantiationInternal = declaredType.GetTypeHandleInternal().GetInstantiationInternal();
        if (instantiationInternal != null)
        {
            typeInstCount = instantiationInternal.Length;
            array = new IntPtr[instantiationInternal.Length];
            for (int i = 0; i < instantiationInternal.Length; i++)
            {
                array[i] = instantiationInternal[i].GetTypeHandleInternal().Value;
            }
        }
        RuntimeMethodHandleInternal runtimeMethodHandleInternal = ModuleHandle.ResolveMethodHandleInternal(RuntimeTypeHandle.GetModule(declaredType), tkMethod, array, typeInstCount, null, 0);
        if (flag)
        {
            MethodAttributes attributes = RuntimeMethodHandle.GetAttributes(runtimeMethodHandleInternal);
            if ((attributes & MethodAttributes.MemberAccessMask) == MethodAttributes.Private)
            {
                return null;
            }
            if ((attributes & MethodAttributes.Virtual) != 0 && (RuntimeTypeHandle.GetAttributes(declaredType) & TypeAttributes.ClassSemanticsMask) == 0)
            {
                int slot = RuntimeMethodHandle.GetSlot(runtimeMethodHandleInternal);
                runtimeMethodHandleInternal = RuntimeTypeHandle.GetMethodAt(reflectedType, slot);
            }
        }
        RuntimeMethodInfo runtimeMethodInfo = RuntimeType.GetMethodBase(reflectedType, runtimeMethodHandleInternal) as RuntimeMethodInfo;
        return runtimeMethodInfo ?? (reflectedType.Module.ResolveMethod(tkMethod, null, null) as RuntimeMethodInfo);
    }
References System.array, System.RuntimeMethodHandle.GetAttributes(), System.RuntimeTypeHandle.GetAttributes(), System.RuntimeTypeHandle.GetMethodAt(), System.RuntimeType.GetMethodBase(), System.RuntimeTypeHandle.GetModule(), System.RuntimeMethodHandle.GetSlot(), System.Reflection.MetadataToken.IsNullToken(), and System.ModuleHandle.ResolveMethodHandleInternal().
Referenced by System.Reflection.RuntimeEventInfo.RuntimeEventInfo(), System.Reflection.RuntimePropertyInfo.RuntimePropertyInfo(), and System.Reflection.Associates.AssignAssociates().