Terraria: System.String.Replace
Replace() [1/4]
string System.String.Replace (char oldChar, char newChar) inline
Definition at line 2389 of file String.cs.
    {
        if (oldChar == newChar)
        {
            return this;
        }
        int num = IndexOf(oldChar);
        if (num < 0)
        {
            return this;
        }
        int num2 = Length - num;
        string text = FastAllocateString(Length);
        int num3 = num;
        if (num3 > 0)
        {
            Buffer.Memmove(ref text._firstChar, ref _firstChar, (uint)num3);
        }
        ref ushort reference = ref Unsafe.Add(ref Unsafe.As<char, ushort>(ref _firstChar), num3);
        ref ushort reference2 = ref Unsafe.Add(ref Unsafe.As<char, ushort>(ref text._firstChar), num3);
        if (Vector.IsHardwareAccelerated && num2 >= Vector<ushort>.Count)
        {
            Vector<ushort> right = new Vector<ushort>(oldChar);
            Vector<ushort> left = new Vector<ushort>(newChar);
            do
            {
                Vector<ushort> vector = Unsafe.ReadUnaligned<Vector<ushort>>(ref Unsafe.As<ushort, byte>(ref reference));
                Vector<ushort> condition = Vector.Equals(vector, right);
                Vector<ushort> value = Vector.ConditionalSelect(condition, left, vector);
                Unsafe.WriteUnaligned(ref Unsafe.As<ushort, byte>(ref reference2), value);
                reference = ref Unsafe.Add(ref reference, Vector<ushort>.Count);
                reference2 = ref Unsafe.Add(ref reference2, Vector<ushort>.Count);
                num2 -= Vector<ushort>.Count;
            }
            while (num2 >= Vector<ushort>.Count);
        }
        while (num2 > 0)
        {
            ushort num4 = reference;
            reference2 = ((num4 == oldChar) ? newChar : num4);
            reference = ref Unsafe.Add(ref reference, 1);
            reference2 = ref Unsafe.Add(ref reference2, 1);
            num2--;
        }
        return text;
    }
References System.String._firstChar, System.Numerics.Vector< T >.ConditionalSelect(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Numerics.Vector< T >.Equals(), System.String.FastAllocateString(), System.String.IndexOf(), System.Numerics.Vector< T >.IsHardwareAccelerated, System.String.Length, System.Buffer.Memmove(), System.text, and System.value.