Terraria: System.String.Ctor
Ctor() [5/9]
string System.String.Ctor (char[] value, int startIndex, int length) inline private
Definition at line 920 of file String.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (startIndex < 0)
        {
            throw new ArgumentOutOfRangeException("startIndex", SR.ArgumentOutOfRange_StartIndex);
        }
        if (length < 0)
        {
            throw new ArgumentOutOfRangeException("length", SR.ArgumentOutOfRange_NegativeLength);
        }
        if (startIndex > value.Length - length)
        {
            throw new ArgumentOutOfRangeException("startIndex", SR.ArgumentOutOfRange_Index);
        }
        if (length == 0)
        {
            return Empty;
        }
        string text = FastAllocateString(length);
        nuint elementCount = (uint)text.Length;
        Buffer.Memmove(ref text._firstChar, ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(value), startIndex), elementCount);
        return text;
    }
References System.SR.ArgumentOutOfRange_Index, System.SR.ArgumentOutOfRange_NegativeLength, System.SR.ArgumentOutOfRange_StartIndex, System.String.Empty, System.String.FastAllocateString(), System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.length, System.Buffer.Memmove(), System.startIndex, System.text, and System.value.