Terraria: System.String.EndsWith
EndsWith() [4/4]
bool System.String.EndsWith (string value, StringComparison comparisonType) inline
Definition at line 453 of file String.cs.
    {
        if ((object)value == null)
        {
            throw new ArgumentNullException("value");
        }
        if ((object)this == value)
        {
            CheckStringComparison(comparisonType);
            return true;
        }
        if (value.Length == 0)
        {
            CheckStringComparison(comparisonType);
            return true;
        }
        switch (comparisonType)
        {
        case StringComparison.CurrentCulture:
        case StringComparison.CurrentCultureIgnoreCase:
            return CultureInfo.CurrentCulture.CompareInfo.IsSuffix(this, value, GetCaseCompareOfComparisonCulture(comparisonType));
        case StringComparison.InvariantCulture:
        case StringComparison.InvariantCultureIgnoreCase:
            return CompareInfo.Invariant.IsSuffix(this, value, GetCaseCompareOfComparisonCulture(comparisonType));
        case StringComparison.Ordinal:
        {
            int num = Length - value.Length;
            if ((uint)num <= (uint)Length)
            {
                return this.AsSpan(num).SequenceEqual(value);
            }
            return false;
        }
        case StringComparison.OrdinalIgnoreCase:
            if (Length >= value.Length)
            {
                return Ordinal.CompareStringIgnoreCase(ref Unsafe.Add(ref GetRawStringData(), Length - value.Length), value.Length, ref value.GetRawStringData(), value.Length) == 0;
            }
            return false;
        default:
            throw new ArgumentException(SR.NotSupported_StringComparison, "comparisonType");
        }
    }
References System.String.CheckStringComparison(), System.Globalization.Ordinal.CompareStringIgnoreCase(), System.comparisonType, System.Globalization.CultureInfo.CurrentCulture, System.String.GetCaseCompareOfComparisonCulture(), System.String.GetRawStringData(), System.Globalization.CompareInfo.Invariant, System.String.Length, System.SR.NotSupported_StringComparison, and System.value.