Terraria: System.String.GetHashCode
GetHashCode() [3/4]
static int System.String.GetHashCode (ReadOnlySpan< char > value, StringComparison comparisonType) inline static
Definition at line 678 of file String.cs.
    {
        switch (comparisonType)
        {
        case StringComparison.CurrentCulture:
        case StringComparison.CurrentCultureIgnoreCase:
            return CultureInfo.CurrentCulture.CompareInfo.GetHashCode(value, GetCaseCompareOfComparisonCulture(comparisonType));
        case StringComparison.InvariantCulture:
        case StringComparison.InvariantCultureIgnoreCase:
            return CompareInfo.Invariant.GetHashCode(value, GetCaseCompareOfComparisonCulture(comparisonType));
        case StringComparison.Ordinal:
            return GetHashCode(value);
        case StringComparison.OrdinalIgnoreCase:
            return GetHashCodeOrdinalIgnoreCase(value);
        default:
            ThrowHelper.ThrowArgumentException(ExceptionResource.NotSupported_StringComparison, ExceptionArgument.comparisonType);
            return 0;
        }
    }
References System.comparisonType, System.Globalization.CultureInfo.CurrentCulture, System.String.GetCaseCompareOfComparisonCulture(), System.String.GetHashCode(), System.String.GetHashCodeOrdinalIgnoreCase(), System.Globalization.CompareInfo.Invariant, System.ThrowHelper.ThrowArgumentException(), and System.value.