Terraria: System.String.FormatHelper
FormatHelper()
static string System.String.FormatHelper (IFormatProvider provider, string format, ParamsArray args) inline static private
Definition at line 1945 of file String.cs.
    {
        if ((object)format == null)
        {
            throw new ArgumentNullException("format");
        }
        Span<char> initialBuffer = stackalloc char[256];
        ValueStringBuilder valueStringBuilder = new ValueStringBuilder(initialBuffer);
        valueStringBuilder.EnsureCapacity(format.Length + args.Length * 8);
        valueStringBuilder.AppendFormatHelper(provider, format, args);
        return valueStringBuilder.ToString();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.EnsureCapacity(), and System.format.
Referenced by System.String.Format(), System.String.Format(), System.String.Format(), System.String.Format(), System.String.Format(), System.String.Format(), System.String.Format(), and System.String.Format().