Terraria: System.String.IsNullOrEmpty
IsNullOrEmpty()
static bool System.String.IsNullOrEmpty ([NotNullWhen(false)] string? value) inline static
Definition at line 1319 of file String.cs.
    {
        if ((object)value != null && value.Length != 0)
        {
            return false;
        }
        return true;
    }
References System.value.
Referenced by System.String.Concat(), System.String.Concat(), System.String.Concat(), System.String.Concat(), and System.String.MakeSeparatorList().