Terraria: System.String.Replace
Replace() [4/4]
string System.String.Replace (string oldValue, string? newValue, StringComparison comparisonType) inline
Definition at line 2329 of file String.cs.
    {
        switch (comparisonType)
        {
        case StringComparison.CurrentCulture:
        case StringComparison.CurrentCultureIgnoreCase:
            return ReplaceCore(oldValue, newValue, CultureInfo.CurrentCulture.CompareInfo, GetCaseCompareOfComparisonCulture(comparisonType));
        case StringComparison.InvariantCulture:
        case StringComparison.InvariantCultureIgnoreCase:
            return ReplaceCore(oldValue, newValue, CompareInfo.Invariant, GetCaseCompareOfComparisonCulture(comparisonType));
        case StringComparison.Ordinal:
            return Replace(oldValue, newValue);
        case StringComparison.OrdinalIgnoreCase:
            return ReplaceCore(oldValue, newValue, CompareInfo.Invariant, CompareOptions.OrdinalIgnoreCase);
        default:
            throw new ArgumentException(SR.NotSupported_StringComparison, "comparisonType");
        }
    }
References System.comparisonType, System.Globalization.CultureInfo.CurrentCulture, System.String.GetCaseCompareOfComparisonCulture(), System.Globalization.CompareInfo.Invariant, System.SR.NotSupported_StringComparison, System.String.Replace(), and System.String.ReplaceCore().