Terraria: System.String.Concat
Concat() [6/12]
static string System.String.Concat (params string?[] values) inline static
Definition at line 1834 of file String.cs.
    {
        if (values == null)
        {
            throw new ArgumentNullException("values");
        }
        if (values.Length <= 1)
        {
            object obj;
            if (values.Length != 0)
            {
                obj = values[0];
                if (obj == null)
                {
                    return Empty;
                }
            }
            else
            {
                obj = Empty;
            }
            return (string)obj;
        }
        long num = 0L;
        foreach (string text in values)
        {
            if ((object)text != null)
            {
                num += text.Length;
            }
        }
        if (num > int.MaxValue)
        {
            throw new OutOfMemoryException();
        }
        int num2 = (int)num;
        if (num2 == 0)
        {
            return Empty;
        }
        string text2 = FastAllocateString(num2);
        int num3 = 0;
        foreach (string text3 in values)
        {
            if (!IsNullOrEmpty(text3))
            {
                int length = text3.Length;
                if (length > num2 - num3)
                {
                    num3 = -1;
                    break;
                }
                FillStringChecked(text2, num3, text3);
                num3 += length;
            }
        }
        if (num3 != num2)
        {
            return Concat((string[])values.Clone());
        }
        return text2;
    }
References System.String.Concat(), System.String.Empty, System.String.FastAllocateString(), System.String.FillStringChecked(), System.String.IsNullOrEmpty(), System.L, System.length, System.obj, System.text, and System.values.