Terraria: System.String.Concat
Concat() [10/12]
static string System.String.Concat (string? str0, string? str1) inline static
Definition at line 1714 of file String.cs.
    {
        if (IsNullOrEmpty(str0))
        {
            if (IsNullOrEmpty(str1))
            {
                return Empty;
            }
            return str1;
        }
        if (IsNullOrEmpty(str1))
        {
            return str0;
        }
        int length = str0.Length;
        string text = FastAllocateString(length + str1.Length);
        FillStringChecked(text, 0, str0);
        FillStringChecked(text, length, str1);
        return text;
    }
References System.String.Empty, System.String.FastAllocateString(), System.String.FillStringChecked(), System.String.IsNullOrEmpty(), System.length, and System.text.