Terraria: System.String.ReplaceHelper
ReplaceHelper()
string System.String.ReplaceHelper (int oldValueLength, string newValue, ReadOnlySpan< int > indices) inline private
Definition at line 2494 of file String.cs.
    {
        long num = Length + (long)(newValue.Length - oldValueLength) * (long)indices.Length;
        if (num > int.MaxValue)
        {
            throw new OutOfMemoryException();
        }
        string text = FastAllocateString((int)num);
        Span<char> span = new Span<char>(ref text._firstChar, text.Length);
        int num2 = 0;
        int num3 = 0;
        for (int i = 0; i < indices.Length; i++)
        {
            int num4 = indices[i];
            int num5 = num4 - num2;
            if (num5 != 0)
            {
                this.AsSpan(num2, num5).CopyTo(span.Slice(num3));
                num3 += num5;
            }
            num2 = num4 + oldValueLength;
            newValue.CopyTo(span.Slice(num3));
            num3 += newValue.Length;
        }
        this.AsSpan(num2).CopyTo(span.Slice(num3));
        return text;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.String.FastAllocateString(), System.indices, System.String.Length, and System.text.
Referenced by System.String.Replace().