Terraria: System.Reflection.Associates.AssignAssociates
AssignAssociates() [2/2]
static void System.Reflection.Associates.AssignAssociates (MetadataImport scope, int mdPropEvent, RuntimeType declaringType, RuntimeType reflectedType, out RuntimeMethodInfo addOn, out RuntimeMethodInfo removeOn, out RuntimeMethodInfo fireOn, out RuntimeMethodInfo getter, out RuntimeMethodInfo setter, out MethodInfo[] other, out bool composedOfAllPrivateMethods, out BindingFlags bindingFlags) inline static package
Definition at line 72 of file Associates.cs.
    {
        addOn = (removeOn = (fireOn = (getter = (setter = null))));
        Attributes attributes = Attributes.ComposedOfAllVirtualMethods | Attributes.ComposedOfAllPrivateMethods | Attributes.ComposedOfNoPublicMembers | Attributes.ComposedOfNoStaticMembers;
        while (RuntimeTypeHandle.IsGenericVariable(reflectedType))
        {
            reflectedType = (RuntimeType)reflectedType.BaseType;
        }
        bool isInherited = declaringType != reflectedType;
        List<MethodInfo> list = null;
        scope.Enum(MetadataTokenType.MethodDef, mdPropEvent, out var result);
        int num = result.Length / 2;
        for (int i = 0; i < num; i++)
        {
            int tkMethod = result[i * 2];
            MethodSemanticsAttributes methodSemanticsAttributes = (MethodSemanticsAttributes)result[i * 2 + 1];
            RuntimeMethodInfo runtimeMethodInfo = AssignAssociates(tkMethod, declaringType, reflectedType);
            if (runtimeMethodInfo == null)
            {
                continue;
            }
            MethodAttributes attributes2 = runtimeMethodInfo.Attributes;
            bool flag = (attributes2 & MethodAttributes.MemberAccessMask) == MethodAttributes.Private;
            bool flag2 = (attributes2 & MethodAttributes.Virtual) != 0;
            MethodAttributes methodAttributes = attributes2 & MethodAttributes.MemberAccessMask;
            bool flag3 = methodAttributes == MethodAttributes.Public;
            bool flag4 = (attributes2 & MethodAttributes.Static) != 0;
            if (flag3)
            {
                attributes &= ~Attributes.ComposedOfNoPublicMembers;
                attributes &= ~Attributes.ComposedOfAllPrivateMethods;
            }
            else if (!flag)
            {
                attributes &= ~Attributes.ComposedOfAllPrivateMethods;
            }
            if (flag4)
            {
                attributes &= ~Attributes.ComposedOfNoStaticMembers;
            }
            if (!flag2)
            {
                attributes &= ~Attributes.ComposedOfAllVirtualMethods;
            }
            switch (methodSemanticsAttributes)
            {
            case MethodSemanticsAttributes.Setter:
                setter = runtimeMethodInfo;
                continue;
            case MethodSemanticsAttributes.Getter:
                getter = runtimeMethodInfo;
                continue;
            case MethodSemanticsAttributes.Fire:
                fireOn = runtimeMethodInfo;
                continue;
            case MethodSemanticsAttributes.AddOn:
                addOn = runtimeMethodInfo;
                continue;
            case MethodSemanticsAttributes.RemoveOn:
                removeOn = runtimeMethodInfo;
                continue;
            }
            if (list == null)
            {
                list = new List<MethodInfo>(num);
            }
            list.Add(runtimeMethodInfo);
        }
        bool isPublic = (attributes & Attributes.ComposedOfNoPublicMembers) == 0;
        bool isStatic = (attributes & Attributes.ComposedOfNoStaticMembers) == 0;
        bindingFlags = RuntimeType.FilterPreCalculate(isPublic, isInherited, isStatic);
        composedOfAllPrivateMethods = (attributes & Attributes.ComposedOfAllPrivateMethods) != 0;
        other = list?.ToArray();
    }
References System.Reflection.Associates.AssignAssociates(), System.Reflection.MetadataImport.Enum(), System.RuntimeType.FilterPreCalculate(), System.RuntimeTypeHandle.IsGenericVariable(), System.list, and System.other.