Terraria: System.String.strlen
strlen()
static unsafe int System.String.strlen (byte * ptr) inline static package
Definition at line 1428 of file String.cs.
    {
        int num = SpanHelpers.IndexOf(ref *ptr, 0, int.MaxValue);
        if (num < 0)
        {
            ThrowMustBeNullTerminatedString();
        }
        return num;
    }
References System.SpanHelpers.IndexOf(), and System.String.ThrowMustBeNullTerminatedString().
Referenced by System.String.Ctor().