Terraria: System.String.GetCaseCompareOfComparisonCulture
GetCaseCompareOfComparisonCulture()
static CompareOptions System.String.GetCaseCompareOfComparisonCulture (StringComparison comparisonType) inline static package
Definition at line 890 of file String.cs.
    {
        return (CompareOptions)(comparisonType & StringComparison.CurrentCultureIgnoreCase);
    }
References System.comparisonType.
Referenced by System.String.Compare(), System.String.Compare(), System.String.EndsWith(), System.String.Equals(), System.String.Equals(), System.String.GetHashCode(), System.String.IndexOf(), System.String.IndexOf(), System.String.LastIndexOf(), System.String.Replace(), and System.String.StartsWith().