Terraria: System.String.LastIndexOfCharArray
LastIndexOfCharArray()
unsafe int System.String.LastIndexOfCharArray (char[] anyOf, int startIndex, int count) inline private
Definition at line 3497 of file String.cs.
    {
        ProbabilisticMap probabilisticMap = default(ProbabilisticMap);
        uint* charMap = (uint*)(&probabilisticMap);
        InitializeProbabilisticMap(charMap, anyOf);
        fixed (char* ptr = &_firstChar)
        {
            char* ptr2 = ptr + startIndex;
            while (count > 0)
            {
                int num = *ptr2;
                if (IsCharBitSet(charMap, (byte)num) && IsCharBitSet(charMap, (byte)(num >> 8)) && ArrayContains((char)num, anyOf))
                {
                    return (int)(ptr2 - ptr);
                }
                count--;
                ptr2--;
            }
            return -1;
        }
    }
References System.String._firstChar, System.String.ArrayContains(), System.count, System.String.InitializeProbabilisticMap(), System.String.IsCharBitSet(), and System.startIndex.
Referenced by System.String.LastIndexOfAny().