Terraria: System.String.GetNonRandomizedHashCodeOrdinalIgnoreCase
GetNonRandomizedHashCodeOrdinalIgnoreCase()
unsafe int System.String.GetNonRandomizedHashCodeOrdinalIgnoreCase () inline package
Definition at line 728 of file String.cs.
    {
        uint num = 352654597u;
        uint num2 = num;
        fixed (char* ptr = &_firstChar)
        {
            uint* ptr2 = (uint*)ptr;
            int num3 = Length;
            while (true)
            {
                if (num3 > 2)
                {
                    uint num4 = *ptr2;
                    uint num5 = ptr2[1];
                    if (Utf16Utility.AllCharsInUInt32AreAscii(num4 | num5))
                    {
                        num3 -= 4;
                        num = (BitOperations.RotateLeft(num, 5) + num) ^ (num4 | 0x200020u);
                        num2 = (BitOperations.RotateLeft(num2, 5) + num2) ^ (num5 | 0x200020u);
                        ptr2 += 2;
                        continue;
                    }
                }
                else
                {
                    if (num3 <= 0)
                    {
                        break;
                    }
                    uint num6 = *ptr2;
                    if (Utf16Utility.AllCharsInUInt32AreAscii(num6))
                    {
                        num2 = (BitOperations.RotateLeft(num2, 5) + num2) ^ (num6 | 0x200020u);
                        break;
                    }
                }
                goto end_IL_0011;
            }
            goto IL_00a1;
            end_IL_0011:;
        }
        return GetNonRandomizedHashCodeOrdinalIgnoreCaseSlow(this);
        IL_00a1:
        return (int)(num + num2 * 1566083941);
        unsafe static int GetNonRandomizedHashCodeOrdinalIgnoreCaseSlow(string str)
        {
            int num7 = str.Length;
            char[] array = null;
            Span<char> span = (((uint)num7 >= 64u) ? ((Span<char>)(array = ArrayPool<char>.Shared.Rent(num7 + 1))) : stackalloc char[64]);
            Span<char> destination = span;
            int num8 = Ordinal.ToUpperOrdinal(str, destination);
            destination[num7] = '\0';
            uint num9 = 352654597u;
            uint num10 = num9;
            fixed (char* ptr3 = destination)
            {
                uint* ptr4 = (uint*)ptr3;
                while (num7 > 2)
                {
                    num7 -= 4;
                    num9 = (BitOperations.RotateLeft(num9, 5) + num9) ^ (*ptr4 | 0x200020u);
                    num10 = (BitOperations.RotateLeft(num10, 5) + num10) ^ (ptr4[1] | 0x200020u);
                    ptr4 += 2;
                }
                if (num7 > 0)
                {
                    num10 = (BitOperations.RotateLeft(num10, 5) + num10) ^ (*ptr4 | 0x200020u);
                }
            }
            if (array != null)
            {
                ArrayPool<char>.Shared.Return(array);
            }
            return (int)(num9 + num10 * 1566083941);
        }
    }
References System.String._firstChar, System.Text.Unicode.Utf16Utility.AllCharsInUInt32AreAscii(), System.array, System.destination, System.String.Length, System.Numerics.BitOperations.RotateLeft(), System.str, and System.Globalization.Ordinal.ToUpperOrdinal().