Terraria: System.String.SplitInternal
SplitInternal() [1/3]
string[] System.String.SplitInternal (ReadOnlySpan< char > separators, int count, StringSplitOptions options) inline private
Definition at line 2608 of file String.cs.
    {
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", SR.ArgumentOutOfRange_NegativeCount);
        }
        CheckStringSplitOptions(options);
        ValueListBuilder<int> sepListBuilder;
        ReadOnlySpan<int> sepList;
        while (true)
        {
            if (count <= 1 || Length == 0)
            {
                string text = this;
                if ((options & StringSplitOptions.TrimEntries) != 0 && count > 0)
                {
                    text = text.Trim();
                }
                if ((options & StringSplitOptions.RemoveEmptyEntries) != 0 && text.Length == 0)
                {
                    count = 0;
                }
                if (count != 0)
                {
                    return new string[1] { text };
                }
                return Array.Empty<string>();
            }
            if (separators.IsEmpty)
            {
                options &= ~StringSplitOptions.TrimEntries;
            }
            Span<int> initialSpan = stackalloc int[128];
            sepListBuilder = new ValueListBuilder<int>(initialSpan);
            MakeSeparatorList(separators, ref sepListBuilder);
            sepList = sepListBuilder.AsSpan();
            if (sepList.Length != 0)
            {
                break;
            }
            count = 1;
        }
        string[] result = ((options != 0) ? SplitWithPostProcessing(sepList, default(ReadOnlySpan<int>), 1, count, options) : SplitWithoutPostProcessing(sepList, default(ReadOnlySpan<int>), 1, count));
        sepListBuilder.Dispose();
        return result;
    }
References System.SR.ArgumentOutOfRange_NegativeCount, System.String.CheckStringSplitOptions(), System.count, System.String.Length, System.String.MakeSeparatorList(), System.options, System.String.SplitWithoutPostProcessing(), System.String.SplitWithPostProcessing(), and System.text.
Referenced by System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), and System.String.SplitInternal().