Terraria: System.Xml.Schema.XmlUntypedStringConverter.StringToListType
StringToListType()
object System.Xml.Schema.XmlUntypedStringConverter.StringToListType (string value, Type destinationType, IXmlNamespaceResolver nsResolver) inline private
Definition at line 288 of file XmlUntypedStringConverter.cs.
    {
        if (_listsAllowed && destinationType.IsArray)
        {
            Type elementType = destinationType.GetElementType();
            if (elementType == s_objectType)
            {
                return ToArray<object>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_booleanType)
            {
                return ToArray<bool>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_byteType)
            {
                return ToArray<byte>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_byteArrayType)
            {
                return ToArray<byte[]>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_dateTimeType)
            {
                return ToArray<DateTime>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_dateTimeOffsetType)
            {
                return ToArray<DateTimeOffset>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_decimalType)
            {
                return ToArray<decimal>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_doubleType)
            {
                return ToArray<double>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_int16Type)
            {
                return ToArray<short>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_int32Type)
            {
                return ToArray<int>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_int64Type)
            {
                return ToArray<long>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_SByteType)
            {
                return ToArray<sbyte>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_singleType)
            {
                return ToArray<float>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_stringType)
            {
                return ToArray<string>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_timeSpanType)
            {
                return ToArray<TimeSpan>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_UInt16Type)
            {
                return ToArray<ushort>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_UInt32Type)
            {
                return ToArray<uint>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_UInt64Type)
            {
                return ToArray<ulong>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_uriType)
            {
                return ToArray<Uri>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
            if (elementType == s_xmlQualifiedNameType)
            {
                return ToArray<XmlQualifiedName>(XmlConvert.SplitString(value, StringSplitOptions.RemoveEmptyEntries), nsResolver);
            }
        }
        throw CreateInvalidClrMappingException(typeof(string), destinationType);
    }
References System.Xml.Schema.XmlUntypedStringConverter._listsAllowed, System.Xml.Schema.XmlUntypedStringConverter.CreateInvalidClrMappingException(), System.Xml.Dictionary, System.elementType, System.Type.GetElementType(), System.Xml.Schema.XmlUntypedStringConverter.s_booleanType, System.Xml.Schema.XmlUntypedStringConverter.s_byteArrayType, System.Xml.Schema.XmlUntypedStringConverter.s_byteType, System.Xml.Schema.XmlUntypedStringConverter.s_dateTimeOffsetType, System.Xml.Schema.XmlUntypedStringConverter.s_dateTimeType, System.Xml.Schema.XmlUntypedStringConverter.s_decimalType, System.Xml.Schema.XmlUntypedStringConverter.s_doubleType, System.Xml.Schema.XmlUntypedStringConverter.s_int16Type, System.Xml.Schema.XmlUntypedStringConverter.s_int32Type, System.Xml.Schema.XmlUntypedStringConverter.s_int64Type, System.Xml.Schema.XmlUntypedStringConverter.s_objectType, System.Xml.Schema.XmlUntypedStringConverter.s_SByteType, System.Xml.Schema.XmlUntypedStringConverter.s_singleType, System.Xml.Schema.XmlUntypedStringConverter.s_stringType, System.Xml.Schema.XmlUntypedStringConverter.s_timeSpanType, System.Xml.Schema.XmlUntypedStringConverter.s_UInt16Type, System.Xml.Schema.XmlUntypedStringConverter.s_UInt32Type, System.Xml.Schema.XmlUntypedStringConverter.s_UInt64Type, System.Xml.Schema.XmlUntypedStringConverter.s_uriType, System.Xml.Schema.XmlUntypedStringConverter.s_xmlQualifiedNameType, System.Xml.XmlConvert.SplitString(), and System.value.
Referenced by System.Xml.Schema.XmlUntypedStringConverter.FromString().