Terraria: System.Xml.Schema.XmlUntypedStringConverter.Int64ToUInt32
Int64ToUInt32()
uint System.Xml.Schema.XmlUntypedStringConverter.Int64ToUInt32 (long value) inline private
Definition at line 213 of file XmlUntypedStringConverter.cs.
    {
        if (value < 0 || value > uint.MaxValue)
        {
            string xmlConvert_Overflow = System.SR.XmlConvert_Overflow;
            object[] args = new string[2]
            {
                XmlConvert.ToString(value),
                "UInt32"
            };
            throw new OverflowException(System.SR.Format(xmlConvert_Overflow, args));
        }
        return (uint)value;
    }
References System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlConvert.ToString(), System.value, and System.SR.XmlConvert_Overflow.
Referenced by System.Xml.Schema.XmlUntypedStringConverter.FromString().