Terraria: System.Xml.Schema.XmlUntypedStringConverter.FromString
FromString()
object System.Xml.Schema.XmlUntypedStringConverter.FromString (string value, Type destinationType, IXmlNamespaceResolver nsResolver) inline package
Definition at line 60 of file XmlUntypedStringConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        if (destinationType == s_objectType)
        {
            destinationType = typeof(string);
        }
        if (destinationType == s_booleanType)
        {
            return XmlConvert.ToBoolean(value);
        }
        if (destinationType == s_byteType)
        {
            return Int32ToByte(XmlConvert.ToInt32(value));
        }
        if (destinationType == s_byteArrayType)
        {
            return StringToBase64Binary(value);
        }
        if (destinationType == s_dateTimeType)
        {
            return StringToDateTime(value);
        }
        if (destinationType == s_dateTimeOffsetType)
        {
            return StringToDateTimeOffset(value);
        }
        if (destinationType == s_decimalType)
        {
            return XmlConvert.ToDecimal(value);
        }
        if (destinationType == s_doubleType)
        {
            return XmlConvert.ToDouble(value);
        }
        if (destinationType == s_int16Type)
        {
            return Int32ToInt16(XmlConvert.ToInt32(value));
        }
        if (destinationType == s_int32Type)
        {
            return XmlConvert.ToInt32(value);
        }
        if (destinationType == s_int64Type)
        {
            return XmlConvert.ToInt64(value);
        }
        if (destinationType == s_SByteType)
        {
            return Int32ToSByte(XmlConvert.ToInt32(value));
        }
        if (destinationType == s_singleType)
        {
            return XmlConvert.ToSingle(value);
        }
        if (destinationType == s_timeSpanType)
        {
            return StringToDuration(value);
        }
        if (destinationType == s_UInt16Type)
        {
            return Int32ToUInt16(XmlConvert.ToInt32(value));
        }
        if (destinationType == s_UInt32Type)
        {
            return Int64ToUInt32(XmlConvert.ToInt64(value));
        }
        if (destinationType == s_UInt64Type)
        {
            return DecimalToUInt64(XmlConvert.ToDecimal(value));
        }
        if (destinationType == s_uriType)
        {
            return XmlConvert.ToUri(value);
        }
        if (destinationType == s_xmlQualifiedNameType)
        {
            return StringToQName(value, nsResolver);
        }
        if (destinationType == s_stringType)
        {
            return value;
        }
        return StringToListType(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlUntypedStringConverter.DecimalToUInt64(), System.Xml.Dictionary, System.Xml.Schema.XmlUntypedStringConverter.Int32ToByte(), System.Xml.Schema.XmlUntypedStringConverter.Int32ToInt16(), System.Xml.Schema.XmlUntypedStringConverter.Int32ToSByte(), System.Xml.Schema.XmlUntypedStringConverter.Int32ToUInt16(), System.Xml.Schema.XmlUntypedStringConverter.Int64ToUInt32(), System.Xml.Schema.XmlUntypedStringConverter.s_booleanType, System.Xml.Schema.XmlUntypedStringConverter.s_byteArrayType, System.Xml.Schema.XmlUntypedStringConverter.s_byteType, System.Xml.Schema.XmlUntypedStringConverter.s_dateTimeOffsetType, System.Xml.Schema.XmlUntypedStringConverter.s_dateTimeType, System.Xml.Schema.XmlUntypedStringConverter.s_decimalType, System.Xml.Schema.XmlUntypedStringConverter.s_doubleType, System.Xml.Schema.XmlUntypedStringConverter.s_int16Type, System.Xml.Schema.XmlUntypedStringConverter.s_int32Type, System.Xml.Schema.XmlUntypedStringConverter.s_int64Type, System.Xml.Schema.XmlUntypedStringConverter.s_objectType, System.Xml.Schema.XmlUntypedStringConverter.s_SByteType, System.Xml.Schema.XmlUntypedStringConverter.s_singleType, System.Xml.Schema.XmlUntypedStringConverter.s_stringType, System.Xml.Schema.XmlUntypedStringConverter.s_timeSpanType, System.Xml.Schema.XmlUntypedStringConverter.s_UInt16Type, System.Xml.Schema.XmlUntypedStringConverter.s_UInt32Type, System.Xml.Schema.XmlUntypedStringConverter.s_UInt64Type, System.Xml.Schema.XmlUntypedStringConverter.s_uriType, System.Xml.Schema.XmlUntypedStringConverter.s_xmlQualifiedNameType, System.Xml.Schema.XmlUntypedStringConverter.StringToBase64Binary(), System.Xml.Schema.XmlUntypedStringConverter.StringToDateTime(), System.Xml.Schema.XmlUntypedStringConverter.StringToDateTimeOffset(), System.Xml.Schema.XmlUntypedStringConverter.StringToDuration(), System.Xml.Schema.XmlUntypedStringConverter.StringToListType(), System.Xml.Schema.XmlUntypedStringConverter.StringToQName(), System.Xml.XmlConvert.ToBoolean(), System.Xml.XmlConvert.ToDecimal(), System.Xml.XmlConvert.ToDouble(), System.Xml.XmlConvert.ToInt32(), System.Xml.XmlConvert.ToInt64(), System.Xml.XmlConvert.ToSingle(), System.Xml.XmlConvert.ToUri(), and System.value.
Referenced by System.Xml.Schema.XmlUntypedStringConverter.ToArray< T >().