Terraria: System.Xml.Schema.XmlUntypedStringConverter.StringToQName
StringToQName()
static XmlQualifiedName System.Xml.Schema.XmlUntypedStringConverter.StringToQName (string value, IXmlNamespaceResolver nsResolver) inline static private
Definition at line 263 of file XmlUntypedStringConverter.cs.
    {
        value = value.Trim();
        string prefix;
        string localName;
        try
        {
            ValidateNames.ParseQNameThrow(value, out prefix, out localName);
        }
        catch (XmlException ex)
        {
            throw new FormatException(ex.Message);
        }
        if (nsResolver == null)
        {
            throw new InvalidCastException(System.SR.Format(System.SR.XmlConvert_TypeNoNamespace, value, prefix));
        }
        string text = nsResolver.LookupNamespace(prefix);
        if (text == null)
        {
            throw new InvalidCastException(System.SR.Format(System.SR.XmlConvert_TypeNoNamespace, value, prefix));
        }
        return new XmlQualifiedName(localName, text);
    }
References System.Xml.Dictionary, System.SR.Format(), System.Xml.ValidateNames.ParseQNameThrow(), System.prefix, System.text, System.value, and System.SR.XmlConvert_TypeNoNamespace.
Referenced by System.Xml.Schema.XmlUntypedStringConverter.FromString().