Terraria: System.Security.SecureString.Initialize
Initialize()
void System.Security.SecureString.Initialize (ReadOnlySpan< char > value) inline private
Definition at line 104 of file SecureString.cs.
    {
        _buffer = UnmanagedBuffer.Allocate(GetAlignedByteSize(value.Length));
        _decryptedLength = value.Length;
        SafeBuffer bufferToRelease = null;
        try
        {
            Span<char> destination = AcquireSpan(ref bufferToRelease);
            value.CopyTo(destination);
        }
        finally
        {
            ProtectMemory();
            bufferToRelease?.DangerousRelease();
        }
    }
References System.Security.SecureString._buffer, System.Security.SecureString._decryptedLength, System.Security.SecureString.AcquireSpan(), System.Security.SecureString.UnmanagedBuffer.Allocate(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.destination, System.Security.SecureString.GetAlignedByteSize(), System.Security.SecureString.ProtectMemory(), and System.value.
Referenced by System.Security.SecureString.SecureString(), and System.Security.SecureString.SecureString().