Terraria: System.Net.Security.CertificateHelper.GetEligibleClientCertificate
GetEligibleClientCertificate() [1/3]
static X509Certificate2 System.Net.Security.CertificateHelper.GetEligibleClientCertificate () inline static package
Definition at line 93 of file CertificateHelper.cs.
    {
        X509Certificate2Collection certificates;
        using (X509Store x509Store = new X509Store(StoreName.My, StoreLocation.CurrentUser))
        {
            x509Store.Open(OpenFlags.OpenExistingOnly);
            certificates = x509Store.Certificates;
        }
        return GetEligibleClientCertificate(certificates);
    }
References System.Security.Cryptography.X509Certificates.X509Store.Certificates, System.Net.Security.CertificateHelper.GetEligibleClientCertificate(), and System.Security.Cryptography.X509Certificates.X509Store.Open().
Referenced by System.Net.Security.CertificateHelper.GetEligibleClientCertificate(), and System.Net.Security.CertificateHelper.GetEligibleClientCertificate().