Terraria: System.Security.SecureString.EnsureNotDisposed
EnsureNotDisposed()
void System.Security.SecureString.EnsureNotDisposed () inline private
Definition at line 314 of file SecureString.cs.
    {
        if (_buffer == null)
        {
            throw new ObjectDisposedException(GetType().Name);
        }
    }
References System.Security.SecureString._buffer, and System.Name.
Referenced by System.Security.SecureString.AppendChar(), System.Security.SecureString.Clear(), System.Security.SecureString.Copy(), System.Security.SecureString.InsertAt(), System.Security.SecureString.IsReadOnly(), System.Security.SecureString.MakeReadOnly(), System.Security.SecureString.MarshalToBSTR(), System.Security.SecureString.MarshalToString(), System.Security.SecureString.RemoveAt(), and System.Security.SecureString.SetAt().