Terraria: System.Security.SecureString.EnsureNotReadOnly
EnsureNotReadOnly()
void System.Security.SecureString.EnsureNotReadOnly () inline private
Definition at line 306 of file SecureString.cs.
    {
        if (_readOnly)
        {
            throw new InvalidOperationException(SR.InvalidOperation_ReadOnly);
        }
    }
References System.Security.SecureString._readOnly, and System.SR.InvalidOperation_ReadOnly.
Referenced by System.Security.SecureString.AppendChar(), System.Security.SecureString.Clear(), System.Security.SecureString.InsertAt(), System.Security.SecureString.RemoveAt(), and System.Security.SecureString.SetAt().