Terraria: System.Security.SecureString.EnsureCapacity
EnsureCapacity()
void System.Security.SecureString.EnsureCapacity (int capacity) inline private
Definition at line 129 of file SecureString.cs.
    {
        if (capacity > 65536)
        {
            throw new ArgumentOutOfRangeException("capacity", SR.ArgumentOutOfRange_Capacity);
        }
        if ((uint)(capacity * 2) > _buffer.ByteLength)
        {
            UnmanagedBuffer buffer = _buffer;
            UnmanagedBuffer unmanagedBuffer = UnmanagedBuffer.Allocate(GetAlignedByteSize(capacity));
            UnmanagedBuffer.Copy(buffer, unmanagedBuffer, (uint)(_decryptedLength * 2));
            _buffer = unmanagedBuffer;
            buffer.Dispose();
        }
    }
References System.Security.SecureString._buffer, System.Security.SecureString._decryptedLength, System.Security.SecureString.UnmanagedBuffer.Allocate(), System.SR.ArgumentOutOfRange_Capacity, System.buffer, System.Runtime.InteropServices.SafeBuffer.ByteLength, System.capacity, System.Security.SecureString.UnmanagedBuffer.Copy(), System.Runtime.InteropServices.SafeHandle.Dispose(), and System.Security.SecureString.GetAlignedByteSize().
Referenced by System.Security.SecureString.AppendChar(), and System.Security.SecureString.InsertAt().