Terraria: System.Security.SecureString.AppendChar
AppendChar()
void System.Security.SecureString.AppendChar (char c) inline
Definition at line 145 of file SecureString.cs.
    {
        lock (_methodLock)
        {
            EnsureNotDisposed();
            EnsureNotReadOnly();
            SafeBuffer bufferToRelease = null;
            try
            {
                UnprotectMemory();
                EnsureCapacity(_decryptedLength + 1);
                AcquireSpan(ref bufferToRelease)[_decryptedLength] = c;
                _decryptedLength++;
            }
            finally
            {
                ProtectMemory();
                bufferToRelease?.DangerousRelease();
            }
        }
    }
References System.Security.SecureString._decryptedLength, System.Security.SecureString._methodLock, System.Security.SecureString.AcquireSpan(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Security.SecureString.EnsureCapacity(), System.Security.SecureString.EnsureNotDisposed(), System.Security.SecureString.EnsureNotReadOnly(), System.Security.SecureString.ProtectMemory(), and System.Security.SecureString.UnprotectMemory().