Terraria: System.Security.SecureString.MarshalToString
MarshalToString()
unsafe IntPtr System.Security.SecureString.MarshalToString (bool globalAlloc, bool unicode) inline package
Definition at line 354 of file SecureString.cs.
    {
        lock (_methodLock)
        {
            EnsureNotDisposed();
            UnprotectMemory();
            SafeBuffer bufferToRelease = null;
            IntPtr intPtr = IntPtr.Zero;
            int num = 0;
            try
            {
                Span<char> span = AcquireSpan(ref bufferToRelease).Slice(0, _decryptedLength);
                num = ((!unicode) ? Marshal.GetAnsiStringByteCount(span) : ((span.Length + 1) * 2));
                intPtr = ((!globalAlloc) ? Marshal.AllocCoTaskMem(num) : Marshal.AllocHGlobal(num));
                if (unicode)
                {
                    Span<char> destination = new Span<char>((void*)intPtr, num / 2);
                    span.CopyTo(destination);
                    destination[destination.Length - 1] = '\0';
                }
                else
                {
                    Marshal.GetAnsiStringBytes(span, new Span<byte>((void*)intPtr, num));
                }
                IntPtr result = intPtr;
                intPtr = IntPtr.Zero;
                return result;
            }
            finally
            {
                if (intPtr != IntPtr.Zero)
                {
                    new Span<byte>((void*)intPtr, num).Clear();
                    if (globalAlloc)
                    {
                        Marshal.FreeHGlobal(intPtr);
                    }
                    else
                    {
                        Marshal.FreeCoTaskMem(intPtr);
                    }
                }
                ProtectMemory();
                bufferToRelease?.DangerousRelease();
            }
        }
    }
References System.Security.SecureString._decryptedLength, System.Security.SecureString._methodLock, System.Security.SecureString.AcquireSpan(), System.Runtime.InteropServices.Marshal.AllocCoTaskMem(), System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Span< T >.Clear(), System.Span< T >.CopyTo(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.destination, System.Security.SecureString.EnsureNotDisposed(), System.Runtime.InteropServices.Marshal.FreeCoTaskMem(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Runtime.InteropServices.Marshal.GetAnsiStringByteCount(), System.Runtime.InteropServices.Marshal.GetAnsiStringBytes(), System.Security.SecureString.ProtectMemory(), System.Span< T >.Slice(), System.Security.SecureString.UnprotectMemory(), and System.IntPtr.Zero.