Terraria: System.Security.SecureString.MarshalToBSTR
MarshalToBSTR()
unsafe IntPtr System.Security.SecureString.MarshalToBSTR () inline package
Definition at line 322 of file SecureString.cs.
    {
        lock (_methodLock)
        {
            EnsureNotDisposed();
            UnprotectMemory();
            SafeBuffer bufferToRelease = null;
            IntPtr intPtr = IntPtr.Zero;
            int length = 0;
            try
            {
                Span<char> span = AcquireSpan(ref bufferToRelease);
                length = _decryptedLength;
                intPtr = Marshal.AllocBSTR(length);
                span.Slice(0, length).CopyTo(new Span<char>((void*)intPtr, length));
                IntPtr result = intPtr;
                intPtr = IntPtr.Zero;
                return result;
            }
            finally
            {
                if (intPtr != IntPtr.Zero)
                {
                    new Span<char>((void*)intPtr, length).Clear();
                    Marshal.FreeBSTR(intPtr);
                }
                ProtectMemory();
                bufferToRelease?.DangerousRelease();
            }
        }
    }
References System.Security.SecureString._decryptedLength, System.Security.SecureString._methodLock, System.Security.SecureString.AcquireSpan(), System.Runtime.InteropServices.Marshal.AllocBSTR(), System.Span< T >.Clear(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Security.SecureString.EnsureNotDisposed(), System.Runtime.InteropServices.Marshal.FreeBSTR(), System.length, System.Security.SecureString.ProtectMemory(), System.Span< T >.Slice(), System.Security.SecureString.UnprotectMemory(), and System.IntPtr.Zero.