Terraria: System.Security.SecureString.RemoveAt
RemoveAt()
void System.Security.SecureString.RemoveAt (int index) inline
Definition at line 247 of file SecureString.cs.
    {
        lock (_methodLock)
        {
            if (index < 0 || index >= _decryptedLength)
            {
                throw new ArgumentOutOfRangeException("index", SR.ArgumentOutOfRange_IndexString);
            }
            EnsureNotDisposed();
            EnsureNotReadOnly();
            SafeBuffer bufferToRelease = null;
            try
            {
                UnprotectMemory();
                Span<char> span = AcquireSpan(ref bufferToRelease);
                span.Slice(index + 1, _decryptedLength - (index + 1)).CopyTo(span.Slice(index));
                _decryptedLength--;
            }
            finally
            {
                ProtectMemory();
                bufferToRelease?.DangerousRelease();
            }
        }
    }
References System.Security.SecureString._decryptedLength, System.Security.SecureString._methodLock, System.Security.SecureString.AcquireSpan(), System.SR.ArgumentOutOfRange_IndexString, System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Security.SecureString.EnsureNotDisposed(), System.Security.SecureString.EnsureNotReadOnly(), System.index, System.Security.SecureString.ProtectMemory(), System.Span< T >.Slice(), and System.Security.SecureString.UnprotectMemory().