Terraria: System.Net.Security.CertificateHelper.IsValidForClientAuthenticationEKU
IsValidForClientAuthenticationEKU()
static bool System.Net.Security.CertificateHelper.IsValidForClientAuthenticationEKU (X509EnhancedKeyUsageExtension eku) inline static private
Definition at line 74 of file CertificateHelper.cs.
    {
        OidEnumerator enumerator = eku.EnhancedKeyUsages.GetEnumerator();
        while (enumerator.MoveNext())
        {
            Oid current = enumerator.Current;
            if (current.Value == "1.3.6.1.5.5.7.3.2")
            {
                return true;
            }
        }
        return false;
    }
References System.Security.Cryptography.OidEnumerator.Current, System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension.EnhancedKeyUsages, System.Security.Cryptography.OidCollection.GetEnumerator(), System.Security.Cryptography.OidEnumerator.MoveNext(), and System.Security.Cryptography.Oid.Value.
Referenced by System.Net.Security.CertificateHelper.IsValidClientCertificate().