Terraria: System.Security.SecureString.UnprotectMemory
UnprotectMemory()
void System.Security.SecureString.UnprotectMemory () inline private
Definition at line 417 of file SecureString.cs.
    {
        if (_decryptedLength != 0 && _encrypted && !Interop.Crypt32.CryptUnprotectMemory(_buffer, (uint)_buffer.ByteLength, 0u))
        {
            throw new CryptographicException(Marshal.GetLastPInvokeError());
        }
        _encrypted = false;
    }
References System.Security.SecureString._buffer, System.Security.SecureString._decryptedLength, System.Security.SecureString._encrypted, System.Runtime.InteropServices.SafeBuffer.ByteLength, Interop.Crypt32.CryptUnprotectMemory(), and System.Runtime.InteropServices.Marshal.GetLastPInvokeError().
Referenced by System.Security.SecureString.AppendChar(), System.Security.SecureString.InsertAt(), System.Security.SecureString.MarshalToBSTR(), System.Security.SecureString.MarshalToString(), System.Security.SecureString.RemoveAt(), and System.Security.SecureString.SetAt().