Terraria: System.Data.Common.DbCommandBuilder.GetSelectCommand
GetSelectCommand()
DbCommand System.Data.Common.DbCommandBuilder.GetSelectCommand () inline private
Definition at line 1010 of file DbCommandBuilder.cs.
    {
        DbCommand dbCommand = null;
        DbDataAdapter dataAdapter = DataAdapter;
        if (dataAdapter != null)
        {
            if (_missingMappingAction == (MissingMappingAction)0)
            {
                _missingMappingAction = dataAdapter.MissingMappingAction;
            }
            dbCommand = dataAdapter.SelectCommand;
        }
        if (dbCommand == null)
        {
            throw ADP.MissingSourceCommand();
        }
        return dbCommand;
    }
References System.Data.Common.DbCommandBuilder._missingMappingAction, System.Data.Common.DbCommandBuilder.DataAdapter, System.Data.Common.DataAdapter.MissingMappingAction, System.Data.Common.ADP.MissingSourceCommand(), and System.Data.Common.DbDataAdapter.SelectCommand.
Referenced by System.Data.Common.DbCommandBuilder.BuildCache(), and System.Data.Common.DbCommandBuilder.InitializeCommand().