Terraria: System.Data.Common.DbCommandBuilder.BuildUpdateCommand
BuildUpdateCommand()
DbCommand System.Data.Common.DbCommandBuilder.BuildUpdateCommand (DataTableMapping mappings, DataRow dataRow) inline private
Definition at line 761 of file DbCommandBuilder.cs.
    {
        DbCommand dbCommand = InitializeCommand(UpdateCommand);
        StringBuilder stringBuilder = new StringBuilder();
        string value = " SET ";
        int num = 0;
        stringBuilder.Append("UPDATE ");
        stringBuilder.Append(QuotedBaseTableName);
        DbSchemaRow[] dbSchemaRows = _dbSchemaRows;
        for (int i = 0; i < dbSchemaRows.Length; i++)
        {
            DbSchemaRow dbSchemaRow = dbSchemaRows[i];
            if (dbSchemaRow == null || dbSchemaRow.BaseColumnName.Length == 0 || !IncludeInUpdateSet(dbSchemaRow))
            {
                continue;
            }
            object obj = null;
            string text = _sourceColumnNames[i];
            if (mappings != null && dataRow != null)
            {
                DataColumn dataColumn = GetDataColumn(text, mappings, dataRow);
                if (dataColumn == null || (dbSchemaRow.IsReadOnly && dataColumn.ReadOnly))
                {
                    continue;
                }
                obj = GetColumnValue(dataRow, dataColumn, DataRowVersion.Current);
                if (!SetAllValues)
                {
                    object columnValue = GetColumnValue(dataRow, dataColumn, DataRowVersion.Original);
                    if (columnValue == obj || (columnValue != null && columnValue.Equals(obj)))
                    {
                        continue;
                    }
                }
            }
            stringBuilder.Append(value);
            value = ", ";
            stringBuilder.Append(QuotedColumn(dbSchemaRow.BaseColumnName));
            stringBuilder.Append(" = ");
            stringBuilder.Append(CreateParameterForValue(dbCommand, GetBaseParameterName(i), text, DataRowVersion.Current, num, obj, dbSchemaRow, StatementType.Update, whereClause: false));
            num++;
        }
        bool flag = num == 0;
        num = BuildWhereClause(mappings, dataRow, stringBuilder, dbCommand, num, isUpdate: true);
        dbCommand.CommandText = stringBuilder.ToString();
        RemoveExtraParameters(dbCommand, num);
        UpdateCommand = dbCommand;
        if (!flag)
        {
            return dbCommand;
        }
        return null;
    }
References System.Data.Common.DbCommandBuilder._dbSchemaRows, System.Data.Common.DbCommandBuilder._sourceColumnNames, System.Text.StringBuilder.Append(), System.Data.Common.DbSchemaRow.BaseColumnName, System.Data.Common.DbCommandBuilder.BuildWhereClause(), System.Data.Common.DbCommandBuilder.CreateParameterForValue(), System.Data.Common.DbCommandBuilder.GetBaseParameterName(), System.Data.Common.DbCommandBuilder.GetColumnValue(), System.Data.Common.DbCommandBuilder.GetDataColumn(), System.Text.RegularExpressions.i, System.Data.Common.DbCommandBuilder.IncludeInUpdateSet(), System.Data.Common.DbCommandBuilder.InitializeCommand(), System.Data.Common.DbSchemaRow.IsReadOnly, System.obj, System.Data.Common.DbCommandBuilder.QuotedBaseTableName, System.Data.Common.DbCommandBuilder.QuotedColumn(), System.Data.DataColumn.ReadOnly, System.Data.Common.DbCommandBuilder.RemoveExtraParameters(), System.Data.Common.DbCommandBuilder.SetAllValues, System.text, System.Text.StringBuilder.ToString(), System.Data.Common.DbCommandBuilder.UpdateCommand, and System.value.
Referenced by System.Data.Common.DbCommandBuilder.GetUpdateCommand(), and System.Data.Common.DbCommandBuilder.RowUpdatingHandlerBuilder().