Terraria: System.Data.Common.DbCommandBuilder.RowUpdatingHandler
RowUpdatingHandler()
void System.Data.Common.DbCommandBuilder.RowUpdatingHandler (RowUpdatingEventArgs rowUpdatingEvent) inline protected
Definition at line 1246 of file DbCommandBuilder.cs.
    {
        if (rowUpdatingEvent == null)
        {
            throw ADP.ArgumentNull("rowUpdatingEvent");
        }
        try
        {
            if (rowUpdatingEvent.Status != 0)
            {
                return;
            }
            StatementType statementType = rowUpdatingEvent.StatementType;
            DbCommand dbCommand = (DbCommand)rowUpdatingEvent.Command;
            if (dbCommand != null)
            {
                switch (statementType)
                {
                case StatementType.Select:
                    return;
                case StatementType.Insert:
                    dbCommand = InsertCommand;
                    break;
                case StatementType.Update:
                    dbCommand = UpdateCommand;
                    break;
                case StatementType.Delete:
                    dbCommand = DeleteCommand;
                    break;
                default:
                    throw ADP.InvalidStatementType(statementType);
                }
                if (dbCommand != rowUpdatingEvent.Command)
                {
                    dbCommand = (DbCommand)rowUpdatingEvent.Command;
                    if (dbCommand != null && dbCommand.Connection == null)
                    {
                        DbCommand dbCommand2 = DataAdapter?.SelectCommand;
                        if (dbCommand2 != null)
{
                            dbCommand.Connection = dbCommand2.Connection;
                        }
                    }
                }
                else
                {
                    dbCommand = null;
                }
            }
            if (dbCommand == null)
            {
                RowUpdatingHandlerBuilder(rowUpdatingEvent);
            }
        }
        catch (Exception ex) when (ADP.IsCatchableExceptionType(ex))
        {
            ADP.TraceExceptionForCapture(ex);
            rowUpdatingEvent.Status = UpdateStatus.ErrorsOccurred;
            rowUpdatingEvent.Errors = ex;
        }
    }
References System.Data.Common.ADP.ArgumentNull(), System.Data.Common.RowUpdatingEventArgs.Command, System.Data.Common.DbCommand.Connection, System.Data.Common.DbCommandBuilder.DeleteCommand, System.Data.Common.DbCommandBuilder.InsertCommand, System.Data.Common.ADP.InvalidStatementType(), System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.Common.DbCommandBuilder.RowUpdatingHandlerBuilder(), System.Data.Common.RowUpdatingEventArgs.StatementType, System.Data.Common.RowUpdatingEventArgs.Status, System.Data.Common.ADP.TraceExceptionForCapture(), and System.Data.Common.DbCommandBuilder.UpdateCommand.