Terraria: System.Data.Common.DbCommandBuilder.BuildInformation
BuildInformation()
void System.Data.Common.DbCommandBuilder.BuildInformation (DataTable schemaTable) inline private
Definition at line 560 of file DbCommandBuilder.cs.
    {
        DbSchemaRow[] sortedSchemaRows = DbSchemaRow.GetSortedSchemaRows(schemaTable, returnProviderSpecificTypes: false);
        if (sortedSchemaRows == null || sortedSchemaRows.Length == 0)
        {
            throw ADP.DynamicSQLNoTableInfo();
        }
        string text = string.Empty;
        string text2 = string.Empty;
        string text3 = string.Empty;
        string text4 = null;
        for (int i = 0; i < sortedSchemaRows.Length; i++)
        {
            DbSchemaRow dbSchemaRow = sortedSchemaRows[i];
            string baseTableName = dbSchemaRow.BaseTableName;
            if (baseTableName == null || baseTableName.Length == 0)
            {
                sortedSchemaRows[i] = null;
                continue;
            }
            string text5 = dbSchemaRow.BaseServerName;
            string text6 = dbSchemaRow.BaseCatalogName;
            string text7 = dbSchemaRow.BaseSchemaName;
            if (text5 == null)
            {
                text5 = string.Empty;
            }
            if (text6 == null)
            {
                text6 = string.Empty;
            }
            if (text7 == null)
            {
                text7 = string.Empty;
            }
            if (text4 == null)
            {
                text = text5;
                text2 = text6;
                text3 = text7;
                text4 = baseTableName;
            }
            else if (ADP.SrcCompare(text4, baseTableName) != 0 || ADP.SrcCompare(text3, text7) != 0 || ADP.SrcCompare(text2, text6) != 0 || ADP.SrcCompare(text, text5) != 0)
            {
                throw ADP.DynamicSQLJoinUnsupported();
            }
        }
        if (text.Length == 0)
        {
            text = null;
        }
        if (text2.Length == 0)
        {
            text = null;
            text2 = null;
        }
        if (text3.Length == 0)
        {
            text = null;
            text2 = null;
            text3 = null;
        }
        if (text4 == null || text4.Length == 0)
        {
            throw ADP.DynamicSQLNoTableInfo();
        }
        CatalogLocation catalogLocation = CatalogLocation;
        string catalogSeparator = CatalogSeparator;
        string schemaSeparator = SchemaSeparator;
        string quotePrefix = QuotePrefix;
        string quoteSuffix = QuoteSuffix;
        if (!string.IsNullOrEmpty(quotePrefix) && -1 != text4.IndexOf(quotePrefix, StringComparison.Ordinal))
        {
            throw ADP.DynamicSQLNestedQuote(text4, quotePrefix);
        }
        if (!string.IsNullOrEmpty(quoteSuffix) && -1 != text4.IndexOf(quoteSuffix, StringComparison.Ordinal))
        {
            throw ADP.DynamicSQLNestedQuote(text4, quoteSuffix);
        }
        StringBuilder stringBuilder = new StringBuilder();
        if (CatalogLocation.Start == catalogLocation)
        {
            if (text != null)
            {
                stringBuilder.Append(ADP.BuildQuotedString(quotePrefix, quoteSuffix, text));
                stringBuilder.Append(catalogSeparator);
            }
            if (text2 != null)
            {
                stringBuilder.Append(ADP.BuildQuotedString(quotePrefix, quoteSuffix, text2));
                stringBuilder.Append(catalogSeparator);
            }
        }
        if (text3 != null)
        {
            stringBuilder.Append(ADP.BuildQuotedString(quotePrefix, quoteSuffix, text3));
            stringBuilder.Append(schemaSeparator);
        }
        stringBuilder.Append(ADP.BuildQuotedString(quotePrefix, quoteSuffix, text4));
        if (CatalogLocation.End == catalogLocation)
        {
            if (text != null)
            {
                stringBuilder.Append(catalogSeparator);
                stringBuilder.Append(ADP.BuildQuotedString(quotePrefix, quoteSuffix, text));
            }
            if (text2 != null)
            {
                stringBuilder.Append(catalogSeparator);
                stringBuilder.Append(ADP.BuildQuotedString(quotePrefix, quoteSuffix, text2));
            }
        }
        _quotedBaseTableName = stringBuilder.ToString();
        _hasPartialPrimaryKey = false;
        DbSchemaRow[] array = sortedSchemaRows;
        foreach (DbSchemaRow dbSchemaRow2 in array)
        {
            if (dbSchemaRow2 != null && (dbSchemaRow2.IsKey || dbSchemaRow2.IsUnique) && !dbSchemaRow2.IsLong && !dbSchemaRow2.IsRowVersion && dbSchemaRow2.IsHidden)
            {
                _hasPartialPrimaryKey = true;
                break;
            }
        }
        _dbSchemaRows = sortedSchemaRows;
    }
References System.Data.Common.DbCommandBuilder._dbSchemaRows, System.Data.Common.DbCommandBuilder._hasPartialPrimaryKey, System.Data.Common.DbCommandBuilder._quotedBaseTableName, System.Text.StringBuilder.Append(), System.array, System.Data.Common.DbSchemaRow.BaseCatalogName, System.Data.Common.DbSchemaRow.BaseSchemaName, System.Data.Common.DbSchemaRow.BaseServerName, System.Data.Common.DbSchemaRow.BaseTableName, System.Data.Common.ADP.BuildQuotedString(), System.Data.Common.DbCommandBuilder.CatalogLocation, System.Data.Common.DbCommandBuilder.CatalogSeparator, System.Data.Common.ADP.DynamicSQLJoinUnsupported(), System.Data.Common.ADP.DynamicSQLNestedQuote(), System.Data.Common.ADP.DynamicSQLNoTableInfo(), System.Data.Common.DbSchemaRow.GetSortedSchemaRows(), System.Text.RegularExpressions.i, System.Data.Common.DbSchemaRow.IsHidden, System.Data.Common.DbSchemaRow.IsKey, System.Data.Common.DbSchemaRow.IsLong, System.Data.Common.DbSchemaRow.IsRowVersion, System.Data.Common.DbSchemaRow.IsUnique, System.Data.Common.DbCommandBuilder.QuotePrefix, System.Data.Common.DbCommandBuilder.QuoteSuffix, System.Data.Common.DbCommandBuilder.SchemaSeparator, System.Data.Common.ADP.SrcCompare(), System.text, and System.Text.StringBuilder.ToString().
Referenced by System.Data.Common.DbCommandBuilder.BuildCache().