Terraria: System.Data.Common.DbCommandBuilder.CreateParameterForValue
CreateParameterForValue()
string System.Data.Common.DbCommandBuilder.CreateParameterForValue (DbCommand command, string parameterName, string sourceColumn, DataRowVersion version, int parameterCount, object value, DbSchemaRow row, StatementType statementType, bool whereClause) inline private
Definition at line 922 of file DbCommandBuilder.cs.
    {
        DbParameter nextParameter = GetNextParameter(command, parameterCount);
        if (parameterName == null)
        {
            nextParameter.ParameterName = GetParameterName(1 + parameterCount);
        }
        else
        {
            nextParameter.ParameterName = parameterName;
        }
        nextParameter.Direction = ParameterDirection.Input;
        nextParameter.SourceColumn = sourceColumn;
        nextParameter.SourceVersion = version;
        nextParameter.SourceColumnNullMapping = false;
        nextParameter.Value = value;
        nextParameter.Size = 0;
        ApplyParameterInfo(nextParameter, row.DataRow, statementType, whereClause);
        if (!command.Parameters.Contains(nextParameter))
        {
            command.Parameters.Add(nextParameter);
        }
        if (parameterName == null)
        {
            return GetParameterPlaceholder(1 + parameterCount);
        }
        return string.Format(CultureInfo.InvariantCulture, _parameterMarkerFormat, parameterName);
    }
References System.Data.Common.DbCommandBuilder._parameterMarkerFormat, System.Data.Common.DbParameterCollection.Add(), System.Data.Common.DbCommandBuilder.ApplyParameterInfo(), System.Data.Common.DbParameterCollection.Contains(), System.Data.Common.DbSchemaRow.DataRow, System.Data.Common.DbCommandBuilder.GetNextParameter(), System.Data.Common.DbCommandBuilder.GetParameterName(), System.Data.Common.DbCommandBuilder.GetParameterPlaceholder(), System.Globalization.CultureInfo.InvariantCulture, System.Data.Common.DbCommand.Parameters, and System.value.
Referenced by System.Data.Common.DbCommandBuilder.BuildInsertCommand(), System.Data.Common.DbCommandBuilder.BuildUpdateCommand(), and System.Data.Common.DbCommandBuilder.BuildWhereClause().