Terraria: NPCPortraitInfoElement.CreateStarsContainer
CreateStarsContainer()
UIElement NPCPortraitInfoElement.CreateStarsContainer () inline private
     {
         int num = 14;
         int num2 = 14;
         int num3 = -4;
         int num4 = num + num3;
         int num5 = 5;
         int num6 = 5;
         int value = _filledStarsCount.Value;
         float num7 = 1f;
         int num8 = num4 * Math.Min(num6, num5) - num3;
         double num9 = (double)num4 * Math.Ceiling((double)num5 / (double)num6) - (double)num3;
         UIElement uIElement = new UIPanel(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Panel", (AssetRequestMode)1), null, 5, 21)
         {
             Width = new StyleDimension((float)num8 + num7 * 2f, 0f),
             Height = new StyleDimension((float)num9 + num7 * 2f, 0f),
             BackgroundColor = Color.Gray * 0f,
             BorderColor = Color.Transparent,
             Left = new StyleDimension(10f, 0f),
             Top = new StyleDimension(6f, 0f),
             VAlign = 0f
         };
         uIElement.SetPadding(0f);
         for (int num10 = num5 - 1; num10 >= 0; num10--)
         {
             string text = "Images/UI/Bestiary/Icon_Rank_Light";
             if (num10 >= value)
             {
                 text = "Images/UI/Bestiary/Icon_Rank_Dim";
             }
             UIImage element = new UIImage(Main.Assets.Request<Texture2D>(text, (AssetRequestMode)1))
             {
                 Left = new StyleDimension((float)(num4 * (num10 % num6)) - (float)num8 * 0.5f + (float)num * 0.5f, 0f),
                 Top = new StyleDimension((float)(num4 * (num10 / num6)) - (float)num9 * 0.5f + (float)num2 * 0.5f, 0f),
                 HAlign = 0.5f,
                 VAlign = 0.5f
             };
             uIElement.Append(element);
         }
         return uIElement;
     }
References _filledStarsCount, UIElement.Append(), Main.Assets, Color, Left, UIElement.SetPadding(), and Top.
Referenced by ProvideUIElement().