Terraria: System.Data.Common.DbCommandBuilder.IncrementWhereCount
IncrementWhereCount()
bool System.Data.Common.DbCommandBuilder.IncrementWhereCount (DbSchemaRow row) inline private
Definition at line 1151 of file DbCommandBuilder.cs.
    {
        ConflictOption conflictOption = ConflictOption;
        switch (conflictOption)
        {
        case ConflictOption.CompareAllSearchableValues:
        case ConflictOption.OverwriteChanges:
            if ((row.IsKey || row.IsUnique) && !row.IsLong)
            {
                return !row.IsRowVersion;
            }
            return false;
        case ConflictOption.CompareRowVersion:
            if (((row.IsKey || row.IsUnique) && !_hasPartialPrimaryKey) || row.IsRowVersion)
            {
                return !row.IsLong;
            }
            return false;
        default:
            throw ADP.InvalidConflictOptions(conflictOption);
        }
    }
References System.Data.Common.DbCommandBuilder._hasPartialPrimaryKey, System.Data.Common.DbCommandBuilder.ConflictOption, System.Data.Common.ADP.InvalidConflictOptions(), System.Data.Common.DbSchemaRow.IsKey, System.Data.Common.DbSchemaRow.IsLong, System.Data.Common.DbSchemaRow.IsRowVersion, and System.Data.Common.DbSchemaRow.IsUnique.
Referenced by System.Data.Common.DbCommandBuilder.BuildWhereClause(), and System.Data.Common.DbCommandBuilder.IncludeInWhereClause().