Terraria: System.Data.Common.DbCommandBuilder.RemoveExtraParameters
RemoveExtraParameters()
static void System.Data.Common.DbCommandBuilder.RemoveExtraParameters (DbCommand command, int usedParameterCount) inline static private
Definition at line 1238 of file DbCommandBuilder.cs.
    {
        for (int num = command.Parameters.Count - 1; num >= usedParameterCount; num--)
        {
            command.Parameters.RemoveAt(num);
        }
    }
References System.Data.Common.DbParameterCollection.Count, System.Data.Common.DbCommand.Parameters, and System.Data.Common.DbParameterCollection.RemoveAt().
Referenced by System.Data.Common.DbCommandBuilder.BuildDeleteCommand(), System.Data.Common.DbCommandBuilder.BuildInsertCommand(), and System.Data.Common.DbCommandBuilder.BuildUpdateCommand().