Terraria: System.Data.Common.DbCommandBuilder.GetDataColumn
GetDataColumn()
DataColumn System.Data.Common.DbCommandBuilder.GetDataColumn (string columnName, DataTableMapping tablemapping, DataRow row) inline private
Definition at line 1096 of file DbCommandBuilder.cs.
    {
        DataColumn result = null;
        if (!string.IsNullOrEmpty(columnName))
        {
            result = tablemapping.GetDataColumn(columnName, null, row.Table, _missingMappingAction, MissingSchemaAction.Error);
        }
        return result;
    }
References System.Data.Common.DbCommandBuilder._missingMappingAction, System.Data.Common.DataTableMapping.GetDataColumn(), and System.Data.DataRow.Table.
Referenced by System.Data.Common.DbCommandBuilder.BuildInsertCommand(), System.Data.Common.DbCommandBuilder.BuildUpdateCommand(), and System.Data.Common.DbCommandBuilder.GetColumnValue().