Terraria: System.Data.Common.DbCommandBuilder.IncludeInWhereClause
IncludeInWhereClause()
bool System.Data.Common.DbCommandBuilder.IncludeInWhereClause (DbSchemaRow row, bool isUpdate) inline private
Definition at line 1133 of file DbCommandBuilder.cs.
    {
        bool flag = IncrementWhereCount(row);
        if (flag && row.IsHidden)
        {
            if (ConflictOption.CompareRowVersion == ConflictOption)
            {
                throw ADP.DynamicSQLNoKeyInfoRowVersionUpdate();
            }
            throw ADP.DynamicSQLNoKeyInfoUpdate();
        }
        if (!flag && ConflictOption.CompareAllSearchableValues == ConflictOption)
        {
            flag = !row.IsLong && !row.IsRowVersion && !row.IsHidden;
        }
        return flag;
    }
References System.Data.Common.ADP.DynamicSQLNoKeyInfoRowVersionUpdate(), System.Data.Common.ADP.DynamicSQLNoKeyInfoUpdate(), System.Data.Common.DbCommandBuilder.IncrementWhereCount(), and System.Data.Common.DbSchemaRow.IsHidden.
Referenced by System.Data.Common.DbCommandBuilder.BuildWhereClause().