Terraria: System.Data.Common.DbCommandBuilder.BuildCache
BuildCache()
void System.Data.Common.DbCommandBuilder.BuildCache (bool closeConnection, DataRow dataRow, bool useColumnsForParameterNames) inline private
Definition at line 479 of file DbCommandBuilder.cs.
    {
        if (_dbSchemaTable != null && (!useColumnsForParameterNames || _parameterNames != null))
        {
            return;
        }
        DataTable dataTable = null;
        DbCommand selectCommand = GetSelectCommand();
        DbConnection connection = selectCommand.Connection;
        if (connection == null)
        {
            throw ADP.MissingSourceCommandConnection();
        }
        try
        {
            if ((ConnectionState.Open & connection.State) == 0)
            {
                connection.Open();
            }
            else
            {
                closeConnection = false;
            }
            if (useColumnsForParameterNames)
            {
                DataTable schema = connection.GetSchema(DbMetaDataCollectionNames.DataSourceInformation);
                if (schema.Rows.Count == 1)
                {
                    _parameterNamePattern = schema.Rows[0][DbMetaDataColumnNames.ParameterNamePattern] as string;
                    _parameterMarkerFormat = schema.Rows[0][DbMetaDataColumnNames.ParameterMarkerFormat] as string;
                    object obj = schema.Rows[0][DbMetaDataColumnNames.ParameterNameMaxLength];
                    _parameterNameMaxLength = ((obj is int) ? ((int)obj) : 0);
                    if (_parameterNameMaxLength == 0 || _parameterNamePattern == null || _parameterMarkerFormat == null)
                    {
                        useColumnsForParameterNames = false;
                    }
                }
                else
                {
                    useColumnsForParameterNames = false;
                }
            }
            dataTable = GetSchemaTable(selectCommand);
        }
        finally
        {
            if (closeConnection)
            {
                connection.Close();
            }
        }
        if (dataTable == null)
        {
            throw ADP.DynamicSQLNoTableInfo();
        }
        BuildInformation(dataTable);
        _dbSchemaTable = dataTable;
        DbSchemaRow[] dbSchemaRows = _dbSchemaRows;
        string[] array = new string[dbSchemaRows.Length];
        for (int i = 0; i < dbSchemaRows.Length; i++)
        {
            DbSchemaRow dbSchemaRow = dbSchemaRows[i];
            if (dbSchemaRow != null)
            {
                array[i] = dbSchemaRow.ColumnName;
            }
        }
        _sourceColumnNames = array;
        if (useColumnsForParameterNames)
        {
            _parameterNames = new ParameterNames(this, dbSchemaRows);
        }
        ADP.BuildSchemaTableInfoTableNames(array);
    }
References System.Data.Common.DbCommandBuilder._dbSchemaRows, System.Data.Common.DbCommandBuilder._dbSchemaTable, System.Data.Common.DbCommandBuilder._parameterMarkerFormat, System.Data.Common.DbCommandBuilder._parameterNameMaxLength, System.Data.Common.DbCommandBuilder._parameterNamePattern, System.Data.Common.DbCommandBuilder._parameterNames, System.Data.Common.DbCommandBuilder._sourceColumnNames, System.array, System.Data.Common.DbCommandBuilder.BuildInformation(), System.Data.Common.ADP.BuildSchemaTableInfoTableNames(), System.Data.Common.DbConnection.Close(), System.Data.Common.DbSchemaRow.ColumnName, System.Data.Common.DbCommand.Connection, System.Data.DataRowCollection.Count, System.Data.Common.DbMetaDataCollectionNames.DataSourceInformation, System.Data.Common.ADP.DynamicSQLNoTableInfo(), System.Data.Common.DbConnection.GetSchema(), System.Data.Common.DbCommandBuilder.GetSchemaTable(), System.Data.Common.DbCommandBuilder.GetSelectCommand(), System.Text.RegularExpressions.i, System.Data.Common.ADP.MissingSourceCommandConnection(), System.obj, System.Data.Common.DbConnection.Open(), System.Data.Common.DbMetaDataColumnNames.ParameterMarkerFormat, System.Data.Common.DbMetaDataColumnNames.ParameterNameMaxLength, System.Data.Common.DbMetaDataColumnNames.ParameterNamePattern, System.Data.DataTable.Rows, and System.Data.Common.DbConnection.State.
Referenced by System.Data.Common.DbCommandBuilder.GetDeleteCommand(), System.Data.Common.DbCommandBuilder.GetInsertCommand(), System.Data.Common.DbCommandBuilder.GetUpdateCommand(), and System.Data.Common.DbCommandBuilder.RowUpdatingHandlerBuilder().