Terraria: System.Data.Common.DbCommandBuilder.RowUpdatingHandlerBuilder
RowUpdatingHandlerBuilder()
void System.Data.Common.DbCommandBuilder.RowUpdatingHandlerBuilder (RowUpdatingEventArgs rowUpdatingEvent) inline private
Definition at line 1308 of file DbCommandBuilder.cs.
    {
        DataRow row = rowUpdatingEvent.Row;
        BuildCache(closeConnection: false, row, useColumnsForParameterNames: false);
        DbCommand dbCommand = rowUpdatingEvent.StatementType switch
        {
            StatementType.Insert => BuildInsertCommand(rowUpdatingEvent.TableMapping, row),
            StatementType.Update => BuildUpdateCommand(rowUpdatingEvent.TableMapping, row),
            StatementType.Delete => BuildDeleteCommand(rowUpdatingEvent.TableMapping, row),
            _ => throw ADP.InvalidStatementType(rowUpdatingEvent.StatementType),
        };
        if (dbCommand == null)
        {
            row?.AcceptChanges();
            rowUpdatingEvent.Status = UpdateStatus.SkipCurrentRow;
        }
        rowUpdatingEvent.Command = dbCommand;
    }
References System.Data.DataRow.AcceptChanges(), System.Data.Common.DbCommandBuilder.BuildCache(), System.Data.Common.DbCommandBuilder.BuildDeleteCommand(), System.Data.Common.DbCommandBuilder.BuildInsertCommand(), System.Data.Common.DbCommandBuilder.BuildUpdateCommand(), System.Data.Common.ADP.InvalidStatementType(), System.Data.Common.RowUpdatingEventArgs.Row, System.Data.Common.RowUpdatingEventArgs.StatementType, and System.Data.Common.RowUpdatingEventArgs.TableMapping.
Referenced by System.Data.Common.DbCommandBuilder.RowUpdatingHandler().