Terraria: System.Data.Common.DbCommandBuilder.GetDeleteCommand
GetDeleteCommand() [3/3]
DbCommand System.Data.Common.DbCommandBuilder.GetDeleteCommand (DataRow dataRow, bool useColumnsForParameterNames) inline package
Definition at line 1073 of file DbCommandBuilder.cs.
    {
        BuildCache(closeConnection: true, dataRow, useColumnsForParameterNames);
        BuildDeleteCommand(GetTableMapping(dataRow), dataRow);
        return DeleteCommand;
    }
References System.Data.Common.DbCommandBuilder.BuildCache(), System.Data.Common.DbCommandBuilder.BuildDeleteCommand(), System.Data.Common.DbCommandBuilder.DeleteCommand, and System.Data.Common.DbCommandBuilder.GetTableMapping().