Terraria: System.Data.Common.DbCommandBuilder.BuildWhereClause
BuildWhereClause()
int System.Data.Common.DbCommandBuilder.BuildWhereClause (DataTableMapping mappings, DataRow dataRow, StringBuilder builder, DbCommand command, int parameterCount, bool isUpdate) inline private
Definition at line 815 of file DbCommandBuilder.cs.
    {
        string value = string.Empty;
        int num = 0;
        builder.Append(" WHERE ");
        builder.Append('(');
        DbSchemaRow[] dbSchemaRows = _dbSchemaRows;
        for (int i = 0; i < dbSchemaRows.Length; i++)
        {
            DbSchemaRow dbSchemaRow = dbSchemaRows[i];
            if (dbSchemaRow != null && dbSchemaRow.BaseColumnName.Length != 0 && IncludeInWhereClause(dbSchemaRow, isUpdate))
            {
                builder.Append(value);
                value = " AND ";
                object value2 = null;
                string text = _sourceColumnNames[i];
                string value3 = QuotedColumn(dbSchemaRow.BaseColumnName);
                if (mappings != null && dataRow != null)
                {
                    value2 = GetColumnValue(dataRow, text, mappings, DataRowVersion.Original);
                }
                if (!dbSchemaRow.AllowDBNull)
                {
                    builder.Append('(');
                    builder.Append(value3);
                    builder.Append(" = ");
                    builder.Append(CreateParameterForValue(command, GetOriginalParameterName(i), text, DataRowVersion.Original, parameterCount, value2, dbSchemaRow, isUpdate ? StatementType.Update : StatementType.Delete, whereClause: true));
                    parameterCount++;
                    builder.Append(')');
                }
                else
                {
                    builder.Append('(');
                    builder.Append('(');
                    builder.Append(CreateParameterForNullTest(command, GetNullParameterName(i), text, DataRowVersion.Original, parameterCount, value2, dbSchemaRow, isUpdate ? StatementType.Update : StatementType.Delete, whereClause: true));
                    parameterCount++;
                    builder.Append(" = 1");
                    builder.Append(" AND ");
                    builder.Append(value3);
                    builder.Append(" IS NULL");
                    builder.Append(')');
                    builder.Append(" OR ");
                    builder.Append('(');
                    builder.Append(value3);
                    builder.Append(" = ");
                    builder.Append(CreateParameterForValue(command, GetOriginalParameterName(i), text, DataRowVersion.Original, parameterCount, value2, dbSchemaRow, isUpdate ? StatementType.Update : StatementType.Delete, whereClause: true));
                    parameterCount++;
                    builder.Append(')');
                    builder.Append(')');
                }
                if (IncrementWhereCount(dbSchemaRow))
                {
                    num++;
                }
            }
        }
        builder.Append(')');
        if (num == 0)
        {
            if (isUpdate)
            {
                if (ConflictOption.CompareRowVersion == ConflictOption)
                {
                    throw ADP.DynamicSQLNoKeyInfoRowVersionUpdate();
                }
                throw ADP.DynamicSQLNoKeyInfoUpdate();
            }
            if (ConflictOption.CompareRowVersion == ConflictOption)
            {
                throw ADP.DynamicSQLNoKeyInfoRowVersionDelete();
            }
            throw ADP.DynamicSQLNoKeyInfoDelete();
        }
        return parameterCount;
    }
References System.Data.Common.DbCommandBuilder._dbSchemaRows, System.Data.Common.DbCommandBuilder._sourceColumnNames, System.Data.Common.DbSchemaRow.AllowDBNull, System.Text.StringBuilder.Append(), System.Data.Common.DbSchemaRow.BaseColumnName, System.Data.Common.DbCommandBuilder.CreateParameterForNullTest(), System.Data.Common.DbCommandBuilder.CreateParameterForValue(), System.Data.Common.ADP.DynamicSQLNoKeyInfoDelete(), System.Data.Common.ADP.DynamicSQLNoKeyInfoRowVersionDelete(), System.Data.Common.ADP.DynamicSQLNoKeyInfoRowVersionUpdate(), System.Data.Common.ADP.DynamicSQLNoKeyInfoUpdate(), System.Data.Common.DbCommandBuilder.GetColumnValue(), System.Data.Common.DbCommandBuilder.GetNullParameterName(), System.Data.Common.DbCommandBuilder.GetOriginalParameterName(), System.Text.RegularExpressions.i, System.Data.Common.DbCommandBuilder.IncludeInWhereClause(), System.Data.Common.DbCommandBuilder.IncrementWhereCount(), System.Data.Common.DbCommandBuilder.QuotedColumn(), System.text, and System.value.
Referenced by System.Data.Common.DbCommandBuilder.BuildDeleteCommand(), and System.Data.Common.DbCommandBuilder.BuildUpdateCommand().