Terraria: System.Data.Common.DbCommandBuilder.GetTableMapping
GetTableMapping()
DataTableMapping System.Data.Common.DbCommandBuilder.GetTableMapping (DataRow dataRow) inline private
Definition at line 960 of file DbCommandBuilder.cs.
    {
        DataTableMapping result = null;
        if (dataRow != null)
        {
            DataTable table = dataRow.Table;
            if (table != null)
            {
                DbDataAdapter dataAdapter = DataAdapter;
                if (dataAdapter != null)
                {
                    result = dataAdapter.GetTableMapping(table);
                }
                else
                {
                    string tableName = table.TableName;
                    result = new DataTableMapping(tableName, tableName);
                }
            }
        }
        return result;
    }
References System.Data.Common.DbCommandBuilder.DataAdapter, System.Data.Common.DbDataAdapter.GetTableMapping(), System.Data.DataRow.Table, and System.Data.DataTable.TableName.
Referenced by System.Data.Common.DbCommandBuilder.GetDeleteCommand(), System.Data.Common.DbCommandBuilder.GetInsertCommand(), and System.Data.Common.DbCommandBuilder.GetUpdateCommand().