Terraria: System.ComponentModel.DataAnnotations.LocalizableString.GetLocalizableValue
GetLocalizableValue()
string System.ComponentModel.DataAnnotations.LocalizableString.GetLocalizableValue () inline
Definition at line 60 of file LocalizableString.cs.
    {
        if (_cachedResult == null)
        {
            if (_propertyValue == null || _resourceType == null)
            {
                _cachedResult = () => _propertyValue;
            }
            else
            {
                PropertyInfo property = _resourceType.GetRuntimeProperty(_propertyValue);
                bool flag = false;
                if (!_resourceType.IsVisible || property == null || property.PropertyType != typeof(string))
                {
                    flag = true;
                }
                else
                {
                    MethodInfo getMethod = property.GetMethod;
                    if (getMethod == null || !getMethod.IsPublic || !getMethod.IsStatic)
                    {
                        flag = true;
                    }
                }
                if (flag)
                {
                    string exceptionMessage = System.SR.Format(System.SR.LocalizableString_LocalizationFailed, _propertyName, _resourceType.FullName, _propertyValue);
                    _cachedResult = delegate
                    {
                        throw new InvalidOperationException(exceptionMessage);
                    };
                }
                else
                {
                    _cachedResult = () => (string)property.GetValue(null, null);
                }
            }
        }
        return _cachedResult();
    }
References System.ComponentModel.DataAnnotations.LocalizableString._cachedResult, System.ComponentModel.DataAnnotations.LocalizableString._propertyName, System.ComponentModel.DataAnnotations.LocalizableString._propertyValue, System.ComponentModel.DataAnnotations.LocalizableString._resourceType, System.SR.Format(), System.Type.FullName, System.Reflection.MethodBase.IsPublic, System.Reflection.MethodBase.IsStatic, System.Type.IsVisible, and System.SR.LocalizableString_LocalizationFailed.
Referenced by System.ComponentModel.DataAnnotations.DisplayAttribute.GetDescription(), System.ComponentModel.DataAnnotations.DisplayAttribute.GetGroupName(), System.ComponentModel.DataAnnotations.DisplayAttribute.GetName(), System.ComponentModel.DataAnnotations.DisplayFormatAttribute.GetNullDisplayText(), System.ComponentModel.DataAnnotations.DisplayAttribute.GetPrompt(), and System.ComponentModel.DataAnnotations.DisplayAttribute.GetShortName().