Terraria: System.Security.Authentication.ExtendedProtection.ServiceNameCollection.NormalizeServiceName
NormalizeServiceName()
static string System.Security.Authentication.ExtendedProtection.ServiceNameCollection.NormalizeServiceName (string inputServiceName) inline static private
Definition at line 119 of file ServiceNameCollection.cs.
    {
        if (string.IsNullOrWhiteSpace(inputServiceName))
        {
            return inputServiceName;
        }
        int num = inputServiceName.IndexOf('/');
        if (num < 0)
        {
            return inputServiceName;
        }
        string text = inputServiceName.Substring(0, num + 1);
        string text2 = inputServiceName.Substring(num + 1);
        if (string.IsNullOrWhiteSpace(text2))
        {
            return inputServiceName;
        }
        string text3 = text2;
        string text4 = string.Empty;
        string text5 = string.Empty;
        UriHostNameType uriHostNameType = Uri.CheckHostName(text2);
        if (uriHostNameType == UriHostNameType.Unknown)
        {
            string text6 = text2;
            int num2 = text2.IndexOf('/');
            if (num2 >= 0)
            {
                text6 = text2.Substring(0, num2);
                text5 = text2.Substring(num2);
                text3 = text6;
            }
            int num3 = text6.LastIndexOf(':');
            if (num3 >= 0)
            {
                text3 = text6.Substring(0, num3);
                text4 = text6.Substring(num3 + 1);
                if (!ushort.TryParse(text4, NumberStyles.Integer, CultureInfo.InvariantCulture, out var _))
                {
                    return inputServiceName;
                }
                text4 = text6.Substring(num3);
            }
            uriHostNameType = Uri.CheckHostName(text3);
        }
        if (uriHostNameType != UriHostNameType.Dns)
        {
            return inputServiceName;
        }
        if (!Uri.TryCreate("http://" + text3, UriKind.Absolute, out Uri result2))
        {
            return inputServiceName;
        }
        string components = result2.GetComponents(UriComponents.NormalizedHost, UriFormat.SafeUnescaped);
        string text7 = text + components + text4 + text5;
        if (string.Equals(inputServiceName, text7, StringComparison.OrdinalIgnoreCase))
        {
            return inputServiceName;
        }
        return text7;
    }
References System.Uri.CheckHostName(), System.Globalization.CultureInfo.InvariantCulture, System.text, and System.Uri.TryCreate().
Referenced by System.Security.Authentication.ExtendedProtection.ServiceNameCollection.AddIfNew(), and System.Security.Authentication.ExtendedProtection.ServiceNameCollection.Contains().