Terraria: System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiTypeAtTopLevel
SerializeWithXsiTypeAtTopLevel()
override void System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiTypeAtTopLevel (DataContract dataContract, XmlWriterDelegator xmlWriter, object obj, RuntimeTypeHandle originalDeclaredTypeHandle, Type graphType) inline package virtual
Reimplemented from System.Runtime.Serialization.XmlObjectSerializerWriteContext.
Definition at line 176 of file XmlObjectSerializerWriteContextComplexJson.cs.
    {
        bool verifyKnownType = false;
        Type underlyingType = rootTypeDataContract.UnderlyingType;
        bool isInterface = underlyingType.IsInterface;
        if ((!isInterface || !CollectionDataContract.IsCollectionInterface(underlyingType)) && !underlyingType.IsArray)
        {
            verifyKnownType = WriteTypeInfo(xmlWriter, dataContract, rootTypeDataContract);
            HandleCollectionAssignedToObject(underlyingType, ref dataContract, ref obj, ref verifyKnownType);
        }
        if (isInterface)
        {
            VerifyObjectCompatibilityWithInterface(dataContract, obj, underlyingType);
        }
        SerializeAndVerifyType(dataContract, xmlWriter, obj, verifyKnownType, underlyingType.TypeHandle, underlyingType);
    }
References System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.HandleCollectionAssignedToObject(), System.Runtime.Serialization.CollectionDataContract.IsCollectionInterface(), System.obj, System.Runtime.Serialization.XmlObjectSerializerContext.rootTypeDataContract, System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(), System.Runtime.Serialization.DataContract.UnderlyingType, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyObjectCompatibilityWithInterface(), and System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteTypeInfo().