Terraria: System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteTypeInfo
WriteTypeInfo() [1/4]
override bool System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteTypeInfo (XmlWriterDelegator writer, DataContract contract, DataContract declaredContract) inline protected virtual
Reimplemented from System.Runtime.Serialization.XmlObjectSerializerWriteContext.
Definition at line 77 of file XmlObjectSerializerWriteContextComplexJson.cs.
    {
        if ((contract.Name != declaredContract.Name || contract.Namespace != declaredContract.Namespace) && (!(contract.Name.Value == declaredContract.Name.Value) || !(contract.Namespace.Value == declaredContract.Namespace.Value)) && contract.UnderlyingType != Globals.TypeOfObjectArray && _emitXsiType != EmitTypeInformation.Never)
        {
            if (RequiresJsonTypeInfo(contract))
            {
                _perCallXsiTypeAlreadyEmitted = true;
                WriteTypeInfo(writer, contract.Name.Value, contract.Namespace.Value);
            }
            else if (declaredContract.UnderlyingType == typeof(Enum))
            {
                throw new SerializationException(System.SR.Format(System.SR.EnumTypeNotSupportedByDataContractJsonSerializer, declaredContract.UnderlyingType));
            }
            return true;
        }
        return false;
    }
References System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson._emitXsiType, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson._perCallXsiTypeAlreadyEmitted, System.SR.EnumTypeNotSupportedByDataContractJsonSerializer, System.SR.Format(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.RequiresJsonTypeInfo(), System.Runtime.Serialization.Globals.TypeOfObjectArray, System.writer, and System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteTypeInfo().