Terraria: System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyType
VerifyType()
void System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyType (DataContract dataContract, Type declaredType) inline private
Definition at line 194 of file XmlObjectSerializerWriteContextComplexJson.cs.
    {
        bool flag = false;
        if (dataContract.KnownDataContracts != null)
        {
            scopedKnownTypes.Push(dataContract.KnownDataContracts);
            flag = true;
        }
        if (!IsKnownType(dataContract, declaredType))
        {
            throw XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.DcTypeNotFoundOnSerialize, DataContract.GetClrTypeFullName(dataContract.UnderlyingType), dataContract.StableName.Name, dataContract.StableName.Namespace));
        }
        if (flag)
        {
            scopedKnownTypes.Pop();
        }
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.DcTypeNotFoundOnSerialize, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.XmlObjectSerializerContext.IsKnownType(), System.Runtime.Serialization.ScopedKnownTypes.Pop(), System.Runtime.Serialization.ScopedKnownTypes.Push(), and System.Runtime.Serialization.XmlObjectSerializerContext.scopedKnownTypes.
Referenced by System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.HandleCollectionAssignedToObject().