Terraria: System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyObjectCompatibilityWithInterface
VerifyObjectCompatibilityWithInterface()
static void System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyObjectCompatibilityWithInterface (DataContract contract, object graph, Type declaredType) inline static package
Definition at line 241 of file XmlObjectSerializerWriteContextComplexJson.cs.
    {
        Type type = contract.GetType();
        if (type == typeof(XmlDataContract) && !Globals.TypeOfIXmlSerializable.IsAssignableFrom(declaredType))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.XmlObjectAssignedToIncompatibleInterface, graph.GetType(), declaredType)));
        }
        if (type == typeof(CollectionDataContract) && !CollectionDataContract.IsCollectionInterface(declaredType))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.CollectionAssignedToIncompatibleInterface, graph.GetType(), declaredType)));
        }
    }
References System.SR.CollectionAssignedToIncompatibleInterface, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.CollectionDataContract.IsCollectionInterface(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.type, System.Runtime.Serialization.Globals.TypeOfIXmlSerializable, and System.SR.XmlObjectAssignedToIncompatibleInterface.
Referenced by System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiType(), and System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiTypeAtTopLevel().