Terraria: System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.HandleCollectionAssignedToObject
HandleCollectionAssignedToObject()
void System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.HandleCollectionAssignedToObject (Type declaredType, ref DataContract dataContract, ref object obj, ref bool verifyKnownType) inline private
Definition at line 151 of file XmlObjectSerializerWriteContextComplexJson.cs.
    {
        if (!(declaredType != dataContract.UnderlyingType) || !(dataContract is CollectionDataContract))
        {
            return;
        }
        if (verifyKnownType)
        {
            VerifyType(dataContract, declaredType);
            verifyKnownType = false;
        }
        if (((CollectionDataContract)dataContract).Kind == CollectionKind.Dictionary)
        {
            IDictionary dictionary = obj as IDictionary;
            Dictionary<object, object> dictionary2 = new Dictionary<object, object>(dictionary.Count);
            foreach (DictionaryEntry item in dictionary)
            {
                dictionary2.Add(item.Key, item.Value);
            }
            obj = dictionary2;
        }
        dataContract = GetDataContract(Globals.TypeOfIEnumerable);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.dictionary, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.GetDataContract(), System.item, System.obj, System.Runtime.Serialization.Globals.TypeOfIEnumerable, and System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyType().
Referenced by System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiType(), and System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiTypeAtTopLevel().