Terraria: System.Xml.Schema.TypedObject.SetDecimal
SetDecimal()
void System.Xml.Schema.TypedObject.SetDecimal () inline
Definition at line 79 of file TypedObject.cs.
    {
        if (_dstruct != null)
        {
            return;
        }
        XmlTypeCode typeCode = _xsdtype.TypeCode;
        if (typeCode == XmlTypeCode.Decimal || (uint)(typeCode - 40) <= 12u)
        {
            if (_isList)
            {
                _dstruct = new DecimalStruct(_dim);
                for (int i = 0; i < _dim; i++)
                {
                    _dstruct.Dvalue[i] = Convert.ToDecimal(((Array)_ovalue).GetValue(i), NumberFormatInfo.InvariantInfo);
                }
            }
            else
            {
                _dstruct = new DecimalStruct();
                _dstruct.Dvalue[0] = Convert.ToDecimal(_ovalue, NumberFormatInfo.InvariantInfo);
            }
            _dstruct.IsDecimal = true;
        }
        else if (_isList)
        {
            _dstruct = new DecimalStruct(_dim);
        }
        else
        {
            _dstruct = new DecimalStruct();
        }
    }
References System.Xml.Schema.TypedObject._dim, System.Xml.Schema.TypedObject._dstruct, System.Xml.Schema.TypedObject._isList, System.Xml.Schema.TypedObject._ovalue, System.Xml.Schema.TypedObject._xsdtype, System.Xml.Dictionary, System.Xml.Schema.TypedObject.DecimalStruct.Dvalue, System.Globalization.NumberFormatInfo.InvariantInfo, System.Convert.ToDecimal(), and System.Xml.Schema.XmlSchemaDatatype.TypeCode.
Referenced by System.Xml.Schema.TypedObject.Equals(), and System.Xml.Schema.KeySequence.GetHashCode().