Terraria: System.Xml.Schema.TypedObject.Equals
Equals()
bool System.Xml.Schema.TypedObject.Equals (TypedObject other) inline
Definition at line 125 of file TypedObject.cs.
    {
        if (Dim != other.Dim)
        {
            return false;
        }
        if (Type != other.Type)
        {
            if (!Type.IsComparable(other.Type))
            {
                return false;
            }
            other.SetDecimal();
            SetDecimal();
            if (IsDecimal && other.IsDecimal)
            {
                return ListDValueEquals(other);
            }
        }
        if (IsList)
        {
            if (other.IsList)
            {
                return Type.Compare(Value, other.Value) == 0;
            }
            Array array = Value as Array;
            if (array is XmlAtomicValue[] array2)
            {
                if (array2.Length == 1)
                {
                    return array2.GetValue(0).Equals(other.Value);
                }
                return false;
            }
            if (array.Length == 1)
            {
                return array.GetValue(0).Equals(other.Value);
            }
            return false;
        }
        if (other.IsList)
        {
            Array array3 = other.Value as Array;
            if (array3 is XmlAtomicValue[] array4)
            {
                if (array4.Length == 1)
                {
                    return array4.GetValue(0).Equals(Value);
                }
                return false;
            }
            if (array3.Length == 1)
            {
                return array3.GetValue(0).Equals(Value);
            }
            return false;
        }
        return Value.Equals(other.Value);
    }
References System.array, System.Xml.Array, System.Xml.Dictionary, System.Xml.Schema.TypedObject.Dim, System.Array.GetValue(), System.Xml.Schema.TypedObject.IsDecimal, System.Xml.Schema.TypedObject.IsList, System.Xml.Schema.TypedObject.ListDValueEquals(), System.other, System.Xml.Schema.TypedObject.SetDecimal(), and System.Xml.Schema.TypedObject.Value.