Terraria: FancyClassicPlayerResourcesDisplaySet.DrawManaBar
DrawManaBar()
void FancyClassicPlayerResourcesDisplaySet.DrawManaBar (SpriteBatch spriteBatch) inline private
     {
         Vector2 vector = new Vector2(Main.screenWidth - 40, 22f);
         _ = _starCount;
         bool isHovered = false;
         ResourceDrawSettings resourceDrawSettings = default(ResourceDrawSettings);
         resourceDrawSettings.ElementCount = _starCount;
         resourceDrawSettings.ElementIndexOffset = 0;
         resourceDrawSettings.TopLeftAnchor = vector;
         resourceDrawSettings.GetTextureMethod = StarPanelDrawer;
         resourceDrawSettings.OffsetPerDraw = Vector2.Zero;
         resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitY;
         resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
         resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = Vector2.Zero;
         resourceDrawSettings.Draw(spriteBatch, ref isHovered);
         resourceDrawSettings = default(ResourceDrawSettings);
         resourceDrawSettings.ElementCount = _starCount;
         resourceDrawSettings.ElementIndexOffset = 0;
         resourceDrawSettings.TopLeftAnchor = vector + new Vector2(15f, 16f);
         resourceDrawSettings.GetTextureMethod = StarFillingDrawer;
         resourceDrawSettings.OffsetPerDraw = Vector2.UnitY * -2f;
         resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitY;
         resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
         resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = new Vector2(0.5f, 0.5f);
         resourceDrawSettings.Draw(spriteBatch, ref isHovered);
         _hoverMana = isHovered;
     }
References _hoverMana, _starCount, ResourceDrawSettings.Draw(), ResourceDrawSettings.ElementCount, ResourceDrawSettings.ElementIndexOffset, ResourceDrawSettings.GetTextureMethod, ResourceDrawSettings.OffsetPerDraw, ResourceDrawSettings.OffsetPerDrawByTexturePercentile, ResourceDrawSettings.OffsetSpriteAnchor, ResourceDrawSettings.OffsetSpriteAnchorByTexturePercentile, Main.screenWidth, StarFillingDrawer(), StarPanelDrawer(), and ResourceDrawSettings.TopLeftAnchor.
Referenced by Draw().