Terraria: System.Buffer.ZeroMemory
ZeroMemory()
static unsafe void System.Buffer.ZeroMemory (byte * dest, nuint len) inline static package
Definition at line 188 of file Buffer.cs.
    {
        SpanHelpers.ClearWithoutReferences(ref *dest, len);
    }
References System.SpanHelpers.ClearWithoutReferences(), and System.len.
Referenced by System.Number.BigInteger.Clear(), System.IO.UnmanagedMemoryStream.SetLength(), System.IO.UnmanagedMemoryStream.WriteByte(), System.IO.UnmanagedMemoryStream.WriteCore(), System.Runtime.InteropServices.Marshal.ZeroFreeBSTR(), System.Runtime.InteropServices.Marshal.ZeroFreeCoTaskMemUnicode(), System.Runtime.InteropServices.Marshal.ZeroFreeCoTaskMemUTF8(), System.Runtime.InteropServices.Marshal.ZeroFreeGlobalAllocAnsi(), and System.Runtime.InteropServices.Marshal.ZeroFreeGlobalAllocUnicode().