Terraria: System.Buffer.BulkMoveWithWriteBarrier
BulkMoveWithWriteBarrier()
static void System.Buffer.BulkMoveWithWriteBarrier (ref byte destination, ref byte source, nuint byteCount) inline static package
Definition at line 31 of file Buffer.cs.
    {
        if (byteCount <= 16384)
        {
            __BulkMoveWithWriteBarrier(ref destination, ref source, byteCount);
        }
        else
        {
            _BulkMoveWithWriteBarrier(ref destination, ref source, byteCount);
        }
    }
References System.Buffer.__BulkMoveWithWriteBarrier(), System.Buffer._BulkMoveWithWriteBarrier(), System.byteCount, System.destination, and System.source.
Referenced by System.Array.Copy(), System.Array.Copy(), System.Array.Copy(), System.Object.MemberwiseClone(), and System.Buffer.Memmove< T >().