Terraria: System.Buffer.Memmove
Memmove()
static void System.Buffer.Memmove (ref byte dest, ref byte src, nuint len) inline static package
Definition at line 215 of file Buffer.cs.
    {
        if ((nuint)(nint)Unsafe.ByteOffset(ref src, ref dest) >= len && (nuint)(nint)Unsafe.ByteOffset(ref dest, ref src) >= len)
        {
            ref byte source = ref Unsafe.Add(ref src, (nint)len);
            ref byte source2 = ref Unsafe.Add(ref dest, (nint)len);
            if (len > 16)
            {
                if (len > 64)
                {
                    if (len > 2048)
                    {
                        goto IL_01db;
                    }
                    nuint num = len >> 6;
                    do
                    {
                        Unsafe.As<byte, Block64>(ref dest) = Unsafe.As<byte, Block64>(ref src);
                        dest = ref Unsafe.Add(ref dest, 64);
                        src = ref Unsafe.Add(ref src, 64);
                        num--;
                    }
                    while (num != 0);
                    len %= 64;
                    if (len <= 16)
                    {
                        Unsafe.As<byte, Block16>(ref Unsafe.Add(ref source2, -16)) = Unsafe.As<byte, Block16>(ref Unsafe.Add(ref source, -16));
                        return;
                    }
                }
                Unsafe.As<byte, Block16>(ref dest) = Unsafe.As<byte, Block16>(ref src);
                if (len > 32)
                {
                    Unsafe.As<byte, Block16>(ref Unsafe.Add(ref dest, 16)) = Unsafe.As<byte, Block16>(ref Unsafe.Add(ref src, 16));
                    if (len > 48)
                    {
                        Unsafe.As<byte, Block16>(ref Unsafe.Add(ref dest, 32)) = Unsafe.As<byte, Block16>(ref Unsafe.Add(ref src, 32));
                    }
                }
                Unsafe.As<byte, Block16>(ref Unsafe.Add(ref source2, -16)) = Unsafe.As<byte, Block16>(ref Unsafe.Add(ref source, -16));
            }
            else if ((len & 0x18) != 0)
            {
                Unsafe.As<byte, long>(ref dest) = Unsafe.As<byte, long>(ref src);
                Unsafe.As<byte, long>(ref Unsafe.Add(ref source2, -8)) = Unsafe.As<byte, long>(ref Unsafe.Add(ref source, -8));
            }
            else if ((len & 4) != 0)
            {
                Unsafe.As<byte, int>(ref dest) = Unsafe.As<byte, int>(ref src);
                Unsafe.As<byte, int>(ref Unsafe.Add(ref source2, -4)) = Unsafe.As<byte, int>(ref Unsafe.Add(ref source, -4));
            }
            else if (len != 0)
            {
                dest = src;
                if ((len & 2) != 0)
                {
                    Unsafe.As<byte, short>(ref Unsafe.Add(ref source2, -2)) = Unsafe.As<byte, short>(ref Unsafe.Add(ref source, -2));
                }
            }
            return;
        }
        if (Unsafe.AreSame(ref dest, ref src))
        {
            return;
        }
        goto IL_01db;
        IL_01db:
        _Memmove(ref dest, ref src, len);
    }
References System.Buffer._Memmove(), System.len, and System.source.
Referenced by System.Text.StringBuilder.Append(), System.Buffer.BlockCopy(), System.StubHelpers.AsAnyMarshaler.ConvertStringToNative(), System.StubHelpers.AnsiBSTRMarshaler.ConvertToNative(), System.StubHelpers.CSTRMarshaler.ConvertToNative(), System.StubHelpers.VBByValStrMarshaler.ConvertToNative(), System.StubHelpers.BSTRMarshaler.ConvertToNative(), System.Array.Copy(), System.Array.Copy(), System.Array.Copy(), System.String.Copy(), System.String.CopyTo(), System.String.CopyTo(), System.ReadOnlySpan< T >.CopyTo(), System.Span< T >.CopyTo(), System.String.Ctor(), System.String.Ctor(), System.String.Ctor(), System.String.Ctor(), System.String.Ctor(), System.String.FillStringChecked(), System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray< T >(), System.String.Insert(), System.String.InternalCopy(), System.String.InternalSubString(), System.Object.MemberwiseClone(), System.Buffer.Memcpy(), System.Buffer.Memcpy(), System.Buffer.Memmove< T >(), System.Buffer.MemoryCopy(), System.Buffer.MemoryCopy(), System.String.PadLeft(), System.String.PadRight(), System.Runtime.InteropServices.SafeBuffer.Read< T >(), System.IO.UnmanagedMemoryStream.ReadCore(), System.Runtime.InteropServices.SafeBuffer.ReadSpan< T >(), System.String.Remove(), System.String.Replace(), System.Array.Resize< T >(), System.Number.BigInteger.SetValue(), System.ReadOnlySpan< T >.ToArray(), System.Span< T >.ToArray(), System.String.ToCharArray(), System.String.ToCharArray(), System.Text.StringBuilder.ToString(), System.String.TryCopyTo(), System.ReadOnlySpan< T >.TryCopyTo(), System.Span< T >.TryCopyTo(), System.Runtime.InteropServices.SafeBuffer.Write< T >(), System.IO.UnmanagedMemoryStream.WriteCore(), and System.Runtime.InteropServices.SafeBuffer.WriteSpan< T >().