Terraria: System.Buffer.MemoryCopy
MemoryCopy() [1/2]
static unsafe void System.Buffer.MemoryCopy (void * source, void * destination, long destinationSizeInBytes, long sourceBytesToCopy) inline static
Definition at line 195 of file Buffer.cs.
    {
        if (sourceBytesToCopy > destinationSizeInBytes)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.sourceBytesToCopy);
        }
        Memmove(ref *(byte*)destination, ref *(byte*)source, checked((nuint)sourceBytesToCopy));
    }
References System.destination, System.Buffer.Memmove(), System.source, System.sourceBytesToCopy, and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.Security.SecureString.UnmanagedBuffer.Copy(), System.Net.NetEventSource.DumpBuffer(), and System.IO.StreamWriter.WriteSpan().