Terraria: System.Buffer.SetByte
SetByte()
static void System.Buffer.SetByte (Array array, int index, byte value) inline static
Definition at line 179 of file Buffer.cs.
    {
        if ((uint)index >= (uint)ByteLength(array))
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.index);
        }
        Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(array), index) = value;
    }
References System.array, System.Buffer.ByteLength(), System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.index, System.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.value.