Terraria: System.Xml.Linq.NamespaceCache.Get
Get()
XNamespace System.Xml.Linq.NamespaceCache.Get (string namespaceName) inline
Definition at line 9 of file NamespaceCache.cs.
    {
        if ((object)namespaceName == _namespaceName)
        {
            return _ns;
        }
        _namespaceName = namespaceName;
        _ns = XNamespace.Get(namespaceName);
        return _ns;
    }
References System.Xml.Linq.NamespaceCache._namespaceName, System.Xml.Linq.NamespaceCache._ns, System.Xml.Dictionary, and System.Xml.Linq.XNamespace.Get().
Referenced by System.Xml.Linq.XContainer.ContentReader.ReadContentFrom(), System.Xml.Linq.XContainer.ContentReader.ReadContentFrom(), System.Xml.Linq.XContainer.ContentReader.ReadContentFromAsync(), and System.Xml.Linq.XContainer.ContentReader.ReadContentFromAsync().