Terraria: System.Data.Common.RowUpdatingEventArgs.RowUpdatingEventArgs
RowUpdatingEventArgs()
System.Data.Common.RowUpdatingEventArgs.RowUpdatingEventArgs (DataRow dataRow, IDbCommand? command, StatementType statementType, DataTableMapping tableMapping) inline
Definition at line 76 of file RowUpdatingEventArgs.cs.
    {
        ADP.CheckArgumentNull(dataRow, "dataRow");
        ADP.CheckArgumentNull(tableMapping, "tableMapping");
        switch (statementType)
        {
        case StatementType.Batch:
            throw ADP.NotSupportedStatementType(statementType, "RowUpdatingEventArgs");
        default:
            throw ADP.InvalidStatementType(statementType);
        case StatementType.Select:
        case StatementType.Insert:
        case StatementType.Update:
        case StatementType.Delete:
            _dataRow = dataRow;
            _command = command;
            _statementType = statementType;
            _tableMapping = tableMapping;
            break;
        }
    }
References System.Data.Common.RowUpdatingEventArgs._command, System.Data.Common.RowUpdatingEventArgs._dataRow, System.Data.Common.RowUpdatingEventArgs._statementType, System.Data.Common.RowUpdatingEventArgs._tableMapping, System.Data.Common.ADP.CheckArgumentNull(), System.Data.Common.ADP.InvalidStatementType(), and System.Data.Common.ADP.NotSupportedStatementType().