Terraria: UIWorldListItem.TryMovingToRejectionMenuIfNeeded
TryMovingToRejectionMenuIfNeeded()
bool UIWorldListItem.TryMovingToRejectionMenuIfNeeded (int worldGameMode) inline private
     {
         if (!Main.RegisteredGameModes.TryGetValue(worldGameMode, out var value))
         {
             SoundEngine.PlaySound(10);
             Main.statusText = Language.GetTextValue("UI.WorldCannotBeLoadedBecauseItHasAnInvalidGameMode");
             Main.menuMode = 1000000;
             return true;
         }
         bool flag = Main.ActivePlayerFileData.Player.difficulty == 3;
         bool isJourneyMode = value.IsJourneyMode;
         if (flag && !isJourneyMode)
         {
             SoundEngine.PlaySound(10);
             Main.statusText = Language.GetTextValue("UI.PlayerIsCreativeAndWorldIsNotCreative");
             Main.menuMode = 1000000;
             return true;
         }
         if (!flag && isJourneyMode)
         {
             SoundEngine.PlaySound(10);
             Main.statusText = Language.GetTextValue("UI.PlayerIsNotCreativeAndWorldIsCreative");
             Main.menuMode = 1000000;
             return true;
         }
         return false;
     }
References Main.ActivePlayerFileData, Player.difficulty, Language.GetTextValue(), Main.menuMode, PlayerFileData.Player, SoundEngine.PlaySound(), Main.RegisteredGameModes, and Main.statusText.
Referenced by PlayGame().