Terraria: UIWorldListItem.UIWorldListItem
UIWorldListItem()
UIWorldListItem.UIWorldListItem (WorldFileData data, int orderInList, bool canBePlayed) inline
     {
         _orderInList = orderInList;
         _data = data;
         _canBePlayed = canBePlayed;
         LoadTextures();
         InitializeAppearance();
         _worldIcon = GetIconElement();
         _worldIcon.OnLeftDoubleClick += PlayGame;
         Append(_worldIcon);
         if (_data.DefeatedMoonlord)
         {
             UIImage element = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/IconCompletion", (AssetRequestMode)1))
             {
                 HAlign = 0.5f,
                 VAlign = 0.5f,
                 Top = new StyleDimension(-10f, 0f),
                 Left = new StyleDimension(-3f, 0f),
                 IgnoresMouseInteraction = true
             };
             _worldIcon.Append(element);
         }
         float num = 4f;
         UIImageButton uIImageButton = new UIImageButton(_buttonPlayTexture);
         uIImageButton.VAlign = 1f;
         uIImageButton.Left.Set(num, 0f);
         uIImageButton.OnLeftClick += PlayGame;
         base.OnLeftDoubleClick += PlayGame;
         uIImageButton.OnMouseOver += PlayMouseOver;
         uIImageButton.OnMouseOut += ButtonMouseOut;
         Append(uIImageButton);
         num += 24f;
         UIImageButton uIImageButton2 = new UIImageButton(_data.IsFavorite ? _buttonFavoriteActiveTexture : _buttonFavoriteInactiveTexture);
         uIImageButton2.VAlign = 1f;
         uIImageButton2.Left.Set(num, 0f);
         uIImageButton2.OnLeftClick += FavoriteButtonClick;
         uIImageButton2.OnMouseOver += FavoriteMouseOver;
         uIImageButton2.OnMouseOut += ButtonMouseOut;
         uIImageButton2.SetVisibility(1f, _data.IsFavorite ? 0.8f : 0.4f);
         Append(uIImageButton2);
         num += 24f;
         if (SocialAPI.Cloud != null)
         {
             UIImageButton uIImageButton3 = new UIImageButton(_data.IsCloudSave ? _buttonCloudActiveTexture : _buttonCloudInactiveTexture);
             uIImageButton3.VAlign = 1f;
             uIImageButton3.Left.Set(num, 0f);
             uIImageButton3.OnLeftClick += CloudButtonClick;
             uIImageButton3.OnMouseOver += CloudMouseOver;
             uIImageButton3.OnMouseOut += ButtonMouseOut;
             uIImageButton3.SetSnapPoint("Cloud", orderInList);
             Append(uIImageButton3);
             num += 24f;
         }
         if (_data.WorldGeneratorVersion != 0L)
         {
             UIImageButton uIImageButton4 = new UIImageButton(_buttonSeedTexture);
             uIImageButton4.VAlign = 1f;
             uIImageButton4.Left.Set(num, 0f);
             uIImageButton4.OnLeftClick += SeedButtonClick;
             uIImageButton4.OnMouseOver += SeedMouseOver;
             uIImageButton4.OnMouseOut += ButtonMouseOut;
             uIImageButton4.SetSnapPoint("Seed", orderInList);
             Append(uIImageButton4);
             num += 24f;
         }
         UIImageButton uIImageButton5 = new UIImageButton(_buttonRenameTexture);
         uIImageButton5.VAlign = 1f;
         uIImageButton5.Left.Set(num, 0f);
         uIImageButton5.OnLeftClick += RenameButtonClick;
         uIImageButton5.OnMouseOver += RenameMouseOver;
         uIImageButton5.OnMouseOut += ButtonMouseOut;
         uIImageButton5.SetSnapPoint("Rename", orderInList);
         Append(uIImageButton5);
         num += 24f;
         UIImageButton uIImageButton6 = new UIImageButton(_buttonDeleteTexture)
         {
             VAlign = 1f,
             HAlign = 1f
         };
         if (!_data.IsFavorite)
         {
             uIImageButton6.OnLeftClick += DeleteButtonClick;
         }
         uIImageButton6.OnMouseOver += DeleteMouseOver;
         uIImageButton6.OnMouseOut += DeleteMouseOut;
         _deleteButton = uIImageButton6;
         Append(uIImageButton6);
         num += 4f;
         _buttonLabel = new UIText("");
         _buttonLabel.VAlign = 1f;
         _buttonLabel.Left.Set(num, 0f);
         _buttonLabel.Top.Set(-3f, 0f);
         Append(_buttonLabel);
         _deleteButtonLabel = new UIText("");
         _deleteButtonLabel.VAlign = 1f;
         _deleteButtonLabel.HAlign = 1f;
         _deleteButtonLabel.Left.Set(-30f, 0f);
         _deleteButtonLabel.Top.Set(-3f, 0f);
         Append(_deleteButtonLabel);
         uIImageButton.SetSnapPoint("Play", orderInList);
         uIImageButton2.SetSnapPoint("Favorite", orderInList);
         uIImageButton5.SetSnapPoint("Rename", orderInList);
         uIImageButton6.SetSnapPoint("Delete", orderInList);
     }
References _buttonCloudActiveTexture, _buttonCloudInactiveTexture, _buttonDeleteTexture, _buttonFavoriteActiveTexture, _buttonFavoriteInactiveTexture, _buttonLabel, _buttonPlayTexture, _buttonRenameTexture, _buttonSeedTexture, _canBePlayed, AWorldListItem._data, _deleteButton, _deleteButtonLabel, _orderInList, _worldIcon, UIElement.Append(), Main.Assets, ButtonMouseOut(), SocialAPI.Cloud, CloudButtonClick(), CloudMouseOver(), WorldFileData.DefeatedMoonlord, DeleteButtonClick(), DeleteMouseOut(), DeleteMouseOver(), FavoriteButtonClick(), FavoriteMouseOver(), AWorldListItem.GetIconElement(), UIElement.HAlign, UIElement.IgnoresMouseInteraction, InitializeAppearance(), FileData.IsCloudSave, FileData.IsFavorite, L, UIElement.Left, LoadTextures(), UIElement.OnLeftClick, UIElement.OnLeftDoubleClick, UIElement.OnMouseOut, UIElement.OnMouseOver, PlayGame(), PlayMouseOver(), RenameButtonClick(), RenameMouseOver(), SeedButtonClick(), SeedMouseOver(), StyleDimension.Set(), UIElement.SetSnapPoint(), UIImageButton.SetVisibility(), UIElement.Top, UIElement.VAlign, and WorldFileData.WorldGeneratorVersion.