Terraria: System.Threading.Tasks.Dataflow.BatchBlock.BatchBlock
BatchBlock() [2/2]
System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlock (int batchSize, GroupingDataflowBlockOptions dataflowBlockOptions) inline
Definition at line 777 of file BatchBlock.cs.
    {
        if (batchSize < 1)
        {
            throw new ArgumentOutOfRangeException("batchSize", System.SR.ArgumentOutOfRange_GenericPositive);
        }
        if (dataflowBlockOptions == null)
        {
            throw new ArgumentNullException("dataflowBlockOptions");
        }
        if (dataflowBlockOptions.BoundedCapacity > 0 && dataflowBlockOptions.BoundedCapacity < batchSize)
        {
            throw new ArgumentOutOfRangeException("batchSize", System.SR.ArgumentOutOfRange_BatchSizeMustBeNoGreaterThanBoundedCapacity);
        }
        dataflowBlockOptions = dataflowBlockOptions.DefaultOrClone();
        Action<ISourceBlock<T[]>, int> itemsRemovedAction = null;
        Func<ISourceBlock<T[]>, T[], IList<T[]>, int> itemCountingFunc = null;
        if (dataflowBlockOptions.BoundedCapacity > 0)
        {
            itemsRemovedAction = delegate(ISourceBlock<T[]> owningSource, int count)
            {
                ((BatchBlock<T>)owningSource)._target.OnItemsRemoved(count);
            };
            itemCountingFunc = (ISourceBlock<T[]> owningSource, T[] singleOutputItem, IList<T[]> multipleOutputItems) => BatchBlockTargetCore.CountItems(singleOutputItem, multipleOutputItems);
        }
        _source = new SourceCore<T[]>(this, dataflowBlockOptions, delegate(ISourceBlock<T[]> owningSource)
        {
            ((BatchBlock<T>)owningSource)._target.Complete(null, dropPendingMessages: true, releaseReservedMessages: false);
        }, itemsRemovedAction, itemCountingFunc);
        _target = new BatchBlockTargetCore(this, batchSize, delegate(T[] batch)
        {
            _source.AddMessage(batch);
        }, dataflowBlockOptions);
        _target.Completion.ContinueWith(delegate
        {
            _source.Complete();
        }, CancellationToken.None, Common.GetContinuationOptions(), TaskScheduler.Default);
        _source.Completion.ContinueWith(delegate(Task completed, object state)
        {
            IDataflowBlock dataflowBlock = (BatchBlock<T>)state;
            dataflowBlock.Fault(completed.Exception);
        }, this, CancellationToken.None, Common.GetContinuationOptions() | TaskContinuationOptions.OnlyOnFaulted, TaskScheduler.Default);
        Common.WireCancellationToComplete(dataflowBlockOptions.CancellationToken, _source.Completion, delegate(object state)
        {
            ((BatchBlockTargetCore)state).Complete(null, dropPendingMessages: true, releaseReservedMessages: false);
        }, _target);
        DataflowEtwProvider log = DataflowEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.DataflowBlockCreated(this, dataflowBlockOptions);
        }
    }
References System.Threading.Tasks.Dataflow.BatchBlock< T >._source, System.Threading.Tasks.Dataflow.BatchBlock< T >._target, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.AddMessage(), System.SR.ArgumentOutOfRange_BatchSizeMustBeNoGreaterThanBoundedCapacity, System.SR.ArgumentOutOfRange_GenericPositive, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.Complete(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.Completion, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.Completion, System.Threading.Tasks.Task< TResult >.ContinueWith(), System.count, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.CountItems(), System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Dataflow.Internal.Common.GetContinuationOptions(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.Log, System.Threading.CancellationToken.None, System.state, and System.Threading.Tasks.Dataflow.Internal.Common.WireCancellationToComplete().