Terraria: UIWorldListItem.FavoriteButtonClick
FavoriteButtonClick()
void UIWorldListItem.FavoriteButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         _data.ToggleFavorite();
         ((UIImageButton)evt.Target).SetImage(_data.IsFavorite ? _buttonFavoriteActiveTexture : _buttonFavoriteInactiveTexture);
         ((UIImageButton)evt.Target).SetVisibility(1f, _data.IsFavorite ? 0.8f : 0.4f);
         if (_data.IsFavorite)
         {
             _buttonLabel.SetText(Language.GetTextValue("UI.Unfavorite"));
             _deleteButton.OnLeftClick -= DeleteButtonClick;
         }
         else
         {
             _buttonLabel.SetText(Language.GetTextValue("UI.Favorite"));
             _deleteButton.OnLeftClick += DeleteButtonClick;
         }
         if (base.Parent.Parent is UIList uIList)
         {
             uIList.UpdateOrder();
         }
     }
References _buttonFavoriteActiveTexture, _buttonFavoriteInactiveTexture, _buttonLabel, AWorldListItem._data, _deleteButton, DeleteButtonClick(), Language.GetTextValue(), FileData.IsFavorite, UIElement.OnLeftClick, UIText.SetText(), UIEvent.Target, and FileData.ToggleFavorite().
Referenced by UIWorldListItem().