Terraria: UIWorldListItem.FavoriteMouseOver
FavoriteMouseOver()
void UIWorldListItem.FavoriteMouseOver (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         if (_data.IsFavorite)
         {
             _buttonLabel.SetText(Language.GetTextValue("UI.Unfavorite"));
         }
         else
         {
             _buttonLabel.SetText(Language.GetTextValue("UI.Favorite"));
         }
     }
References _buttonLabel, AWorldListItem._data, Language.GetTextValue(), FileData.IsFavorite, and UIText.SetText().
Referenced by UIWorldListItem().