Terraria: System.Transactions.TransactionStatePSPEOperation.PromoteAndEnlistDurable
PromoteAndEnlistDurable()
override Enlistment System.Transactions.TransactionStatePSPEOperation.PromoteAndEnlistDurable (InternalTransaction tx, Guid resourceManagerIdentifier, IPromotableSinglePhaseNotification promotableNotification, ISinglePhaseNotification enlistmentNotification, EnlistmentOptions enlistmentOptions, Transaction atomicTransaction) inline package virtual
Reimplemented from System.Transactions.TransactionState.
Definition at line 105 of file TransactionStatePSPEOperation.cs.
    {
        if (!tx._attemptingPSPEPromote)
        {
            throw TransactionException.CreateTransactionStateException(tx._innerException, tx.DistributedTxId);
        }
        if (promotableNotification != tx._promoter)
        {
            throw TransactionException.CreateInvalidOperationException(TraceSourceType.TraceSourceLtm, System.SR.InvalidIPromotableSinglePhaseNotificationSpecified, null, tx.DistributedTxId);
        }
        tx._durableEnlistment = null;
        tx._promoteState = TransactionState.TransactionStatePromoted;
        tx._promoteState.EnterState(tx);
        Enlistment enlistment = tx.State.EnlistDurable(tx, resourceManagerIdentifier, enlistmentNotification, enlistmentOptions, atomicTransaction);
        tx._durableEnlistment = enlistment.InternalEnlistment;
        return enlistment;
    }
References System.Transactions.InternalTransaction._attemptingPSPEPromote, System.Transactions.InternalTransaction._innerException, System.Transactions.InternalTransaction._promoter, System.Transactions.InternalTransaction._promoteState, System.Transactions.TransactionException.CreateInvalidOperationException(), System.Transactions.TransactionException.CreateTransactionStateException(), System.Transactions.InternalTransaction.DistributedTxId, System.Transactions.TransactionState.EnlistDurable(), System.Transactions.TransactionState.EnterState(), System.Transactions.Enlistment.InternalEnlistment, System.SR.InvalidIPromotableSinglePhaseNotificationSpecified, System.Transactions.InternalTransaction.State, and System.Transactions.TransactionState.TransactionStatePromoted.