Terraria: System.Transactions.TransactionStatePSPEOperation.PSPEPromote
PSPEPromote()
DistributedTransaction System.Transactions.TransactionStatePSPEOperation.PSPEPromote (InternalTransaction tx) inline package
Definition at line 45 of file TransactionStatePSPEOperation.cs.
    {
        bool flag = true;
        TransactionState state = tx.State;
        CommonEnterState(tx);
        DistributedTransaction distributedTransaction = null;
        try
        {
            if (tx._attemptingPSPEPromote)
            {
                throw TransactionException.CreateInvalidOperationException(TraceSourceType.TraceSourceLtm, System.SR.PromotedReturnedInvalidValue, null, tx.DistributedTxId);
            }
            tx._attemptingPSPEPromote = true;
            byte[] array = tx._promoter.Promote();
            if (tx._promoterType != TransactionInterop.PromoterTypeDtc)
            {
                if (array == null)
                {
                    throw TransactionException.CreateInvalidOperationException(TraceSourceType.TraceSourceLtm, System.SR.PromotedReturnedInvalidValue, null, tx.DistributedTxId);
                }
                tx.promotedToken = array;
                return null;
            }
            if (array == null)
            {
                if (tx.PromotedTransaction == null)
                {
                    throw TransactionException.CreateInvalidOperationException(TraceSourceType.TraceSourceLtm, System.SR.PromotedReturnedInvalidValue, null, tx.DistributedTxId);
                }
                flag = false;
                distributedTransaction = tx.PromotedTransaction;
            }
            if (distributedTransaction == null)
            {
                try
                {
                    distributedTransaction = TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken(array);
                }
                catch (ArgumentException innerException)
                {
                    throw TransactionException.CreateInvalidOperationException(TraceSourceType.TraceSourceLtm, System.SR.PromotedReturnedInvalidValue, innerException, tx.DistributedTxId);
                }
                if (TransactionManager.FindPromotedTransaction(distributedTransaction.Identifier) != null)
                {
                    distributedTransaction.Dispose();
                    throw TransactionException.CreateInvalidOperationException(TraceSourceType.TraceSourceLtm, System.SR.PromotedTransactionExists, null, tx.DistributedTxId);
                }
            }
        }
        finally
        {
            tx._attemptingPSPEPromote = false;
            if (flag)
            {
                state.CommonEnterState(tx);
            }
        }
        return distributedTransaction;
    }
References System.Transactions.InternalTransaction._attemptingPSPEPromote, System.Transactions.InternalTransaction._promoter, System.Transactions.InternalTransaction._promoterType, System.array, System.Transactions.TransactionState.CommonEnterState(), System.Transactions.TransactionException.CreateInvalidOperationException(), System.Transactions.Distributed.DistributedTransaction.Dispose(), System.Transactions.InternalTransaction.DistributedTxId, System.Transactions.TransactionManager.FindPromotedTransaction(), System.Transactions.TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken(), System.Transactions.Distributed.DistributedTransaction.Identifier, System.Transactions.ITransactionPromoter.Promote(), System.SR.PromotedReturnedInvalidValue, System.Transactions.InternalTransaction.PromotedTransaction, System.SR.PromotedTransactionExists, System.Transactions.TransactionInterop.PromoterTypeDtc, System.state, and System.Transactions.InternalTransaction.State.