Terraria: System.Net.Mime.ContentType.ParseValue
ParseValue()
void System.Net.Mime.ContentType.ParseValue () inline private
Definition at line 226 of file ContentType.cs.
    {
        try
        {
            int offset = 0;
            _mediaType = MailBnfHelper.ReadToken(_type, ref offset, null);
            if (_mediaType == null || _mediaType.Length == 0 || offset >= _type.Length || _type[offset++] != '/')
            {
                throw new FormatException(System.SR.ContentTypeInvalid);
            }
            _subType = MailBnfHelper.ReadToken(_type, ref offset, null);
            if (_subType == null || _subType.Length == 0)
            {
                throw new FormatException(System.SR.ContentTypeInvalid);
            }
            while (MailBnfHelper.SkipCFWS(_type, ref offset))
            {
                if (_type[offset++] != ';')
                {
                    throw new FormatException(System.SR.ContentTypeInvalid);
                }
                if (!MailBnfHelper.SkipCFWS(_type, ref offset))
                {
                    break;
                }
                string text = MailBnfHelper.ReadParameterAttribute(_type, ref offset, null);
                if (text == null || text.Length == 0)
                {
                    throw new FormatException(System.SR.ContentTypeInvalid);
                }
                if (offset >= _type.Length || _type[offset++] != '=')
                {
                    throw new FormatException(System.SR.ContentTypeInvalid);
                }
                if (!MailBnfHelper.SkipCFWS(_type, ref offset))
                {
                    throw new FormatException(System.SR.ContentTypeInvalid);
                }
                string text2 = ((_type[offset] == '"') ? MailBnfHelper.ReadQuotedString(_type, ref offset, null) : MailBnfHelper.ReadToken(_type, ref offset, null));
                if (text2 == null)
                {
                    throw new FormatException(System.SR.ContentTypeInvalid);
                }
                _parameters.Add(text, text2);
            }
            _parameters.IsChanged = false;
        }
        catch (FormatException ex) when (ex.Message != System.SR.ContentTypeInvalid)
        {
            throw new FormatException(System.SR.ContentTypeInvalid);
        }
    }
References System.Net.Mime.ContentType._mediaType, System.Net.Mime.ContentType._parameters, System.Net.Mime.ContentType._subType, System.Net.Mime.ContentType._type, System.Net.TrackingStringDictionary.Add(), System.SR.ContentTypeInvalid, System.Exception.Message, System.offset, System.Net.Mime.MailBnfHelper.ReadParameterAttribute(), System.Net.Mime.MailBnfHelper.ReadQuotedString(), System.Net.Mime.MailBnfHelper.ReadToken(), System.Net.Mime.MailBnfHelper.SkipCFWS(), and System.text.
Referenced by System.Net.Mime.ContentType.ContentType().