Terraria: System.Net.Mime.ContentType.Encode
Encode()
string System.Net.Mime.ContentType.Encode (bool allowUnicode) inline package
Definition at line 177 of file ContentType.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.Append(_mediaType);
        stringBuilder.Append('/');
        stringBuilder.Append(_subType);
        foreach (string key in Parameters.Keys)
        {
            stringBuilder.Append("; ");
            EncodeToBuffer(key, stringBuilder, allowUnicode);
            stringBuilder.Append('=');
            EncodeToBuffer(_parameters[key], stringBuilder, allowUnicode);
        }
        return stringBuilder.ToString();
    }
References System.Net.Mime.ContentType._mediaType, System.Net.Mime.ContentType._parameters, System.Net.Mime.ContentType._subType, System.Text.StringBuilder.Append(), System.Net.Mime.ContentType.EncodeToBuffer(), System.key, System.Collections.Specialized.StringDictionary.Keys, and System.Net.Mime.ContentType.Parameters.
Referenced by System.Net.Mime.MimeBasePart.PrepareHeaders(), and System.Net.Mime.ContentType.ToString().