Terraria: System.Net.Mime.ContentType.PersistIfNeeded
PersistIfNeeded()
void System.Net.Mime.ContentType.PersistIfNeeded (HeaderCollection headers, bool forcePersist) inline package
Definition at line 156 of file ContentType.cs.
    {
        if (IsChanged || !_isPersisted || forcePersist)
        {
            headers.InternalSet(MailHeaderInfo.GetString(MailHeaderID.ContentType), ToString());
            _isPersisted = true;
        }
    }
References System.Net.Mime.ContentType._isPersisted, System.Net.Mail.MailHeaderInfo.GetString(), System.Net.Mime.HeaderCollection.InternalSet(), System.Net.Mime.ContentType.IsChanged, and System.Net.Mime.ContentType.ToString().
Referenced by System.Net.Mime.MimeBasePart.PrepareHeaders().