Terraria: CaptureInterface.ModeEdgeSelection.EdgePlacement
EdgePlacement()
void CaptureInterface.ModeEdgeSelection.EdgePlacement (Vector2 mouse) inline private
         {
             if (JustActivated)
             {
                 return;
             }
             Point result;
             if (!Main.mapFullscreen)
             {
                 if (Main.mouseLeft)
                 {
                     EdgeAPinned = true;
                     EdgeA = Main.MouseWorld.ToTileCoordinates();
                 }
                 if (Main.mouseRight)
                 {
                     EdgeBPinned = true;
                     EdgeB = Main.MouseWorld.ToTileCoordinates();
                 }
             }
             else if (GetMapCoords((int)mouse.X, (int)mouse.Y, 0, out result))
             {
                 if (Main.mouseLeft)
                 {
                     EdgeAPinned = true;
                     EdgeA = result;
                 }
                 if (Main.mouseRight)
                 {
                     EdgeBPinned = true;
                     EdgeB = result;
                 }
             }
             ConstraintPoints();
         }
References CaptureInterface.ConstraintPoints(), CaptureInterface.EdgeA, CaptureInterface.EdgeAPinned, CaptureInterface.EdgeB, CaptureInterface.EdgeBPinned, CaptureInterface.GetMapCoords(), CaptureInterface.JustActivated, Main.mapFullscreen, Main.mouseLeft, Main.mouseRight, and Main.MouseWorld.
Referenced by CaptureInterface.ModeEdgeSelection.Update().