Terraria: CaptureInterface.ModeEdgeSelection.Draw
Draw()
override void CaptureInterface.ModeEdgeSelection.Draw (SpriteBatch sb) inline virtual
Implements CaptureInterface.CaptureInterfaceMode.
         {
             if (Selected)
             {
                 sb.End();
                 sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.CurrentWantedZoomMatrix);
                 PlayerInput.SetZoom_Context();
                 DrawMarkedArea(sb);
                 DrawCursors(sb);
                 sb.End();
                 sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.UIScaleMatrix);
                 PlayerInput.SetZoom_UI();
             }
         }
References Main.CurrentWantedZoomMatrix, CaptureInterface.ModeEdgeSelection.DrawCursors(), CaptureInterface.ModeEdgeSelection.DrawMarkedArea(), CaptureInterface.CaptureInterfaceMode.Selected, PlayerInput.SetZoom_Context(), PlayerInput.SetZoom_UI(), and Main.UIScaleMatrix.