Terraria: CaptureInterface.ModeEdgeSelection.DrawCursors
DrawCursors()
void CaptureInterface.ModeEdgeSelection.DrawCursors (SpriteBatch sb) inline private
         {
             float num = 1f / Main.cursorScale;
             float num2 = 0.8f / num;
             Vector2 vector = Main.screenPosition + new Vector2(30f);
             Vector2 max = vector + new Vector2(Main.screenWidth, Main.screenHeight) - new Vector2(60f);
             if (Main.mapFullscreen)
             {
                 vector -= Main.screenPosition;
                 max -= Main.screenPosition;
             }
             Vector3 vector2 = Main.rgbToHsl(Main.cursorColor);
             Color color = Main.hslToRgb((vector2.X + 0.33f) % 1f, vector2.Y, vector2.Z);
             Color color2 = Main.hslToRgb((vector2.X - 0.33f) % 1f, vector2.Y, vector2.Z);
             color = (color2 = Color.White);
             bool flag = Main.player[Main.myPlayer].gravDir == -1f;
             if (!EdgeAPinned)
             {
                 Utils.DrawCursorSingle(sb, color, 3.926991f, Main.cursorScale * num * num2, new Vector2((float)Main.mouseX - 5f + 12f, (float)Main.mouseY + 2.5f + 12f), 4);
             }
             else
             {
                 int specialMode = 0;
                 float num3 = 0f;
                 Vector2 zero = Vector2.Zero;
                 if (!Main.mapFullscreen)
                 {
                     Vector2 vector3 = EdgeA.ToVector2() * 16f;
                     if (!EdgeBPinned)
                     {
                         specialMode = 1;
                         vector3 += Vector2.One * 8f;
                         zero = vector3;
                         num3 = (-vector3 + Main.ReverseGravitySupport(new Vector2(Main.mouseX, Main.mouseY)) + Main.screenPosition).ToRotation();
                         if (flag)
{
                             num3 = 0f - num3;
                         }
                         zero = Vector2.Clamp(vector3, vector, max);
                         if (zero != vector3)
{
                             num3 = (vector3 - zero).ToRotation();
                         }
                     }
                     else
                     {
                         Vector2 vector4 = new Vector2((EdgeA.X > EdgeB.X).ToInt() * 16, (EdgeA.Y > EdgeB.Y).ToInt() * 16);
                         vector3 += vector4;
                         zero = Vector2.Clamp(vector3, vector, max);
                         num3 = (EdgeB.ToVector2() * 16f + new Vector2(16f) - vector4 - zero).ToRotation();
                         if (zero != vector3)
{
                             num3 = (vector3 - zero).ToRotation();
                             specialMode = 1;
                         }
                         if (flag)
{
                             num3 *= -1f;
                         }
                     }
                     Utils.DrawCursorSingle(sb, color, num3 - (float)Math.PI / 2f, Main.cursorScale * num, Main.ReverseGravitySupport(zero - Main.screenPosition), 4, specialMode);
                 }
                 else
                 {
                     Point result = EdgeA;
                     if (EdgeBPinned)
                     {
                         int num4 = (EdgeA.X > EdgeB.X).ToInt();
                         int num5 = (EdgeA.Y > EdgeB.Y).ToInt();
                         result.X += num4;
                         result.Y += num5;
                         GetMapCoords(result.X, result.Y, 1, out result);
                         Point result2 = EdgeB;
                         result2.X += 1 - num4;
                         result2.Y += 1 - num5;
                         GetMapCoords(result2.X, result2.Y, 1, out result2);
                         zero = result.ToVector2();
                         zero = Vector2.Clamp(zero, vector, max);
                         num3 = (result2.ToVector2() - zero).ToRotation();
                     }
                     else
                     {
                         GetMapCoords(result.X, result.Y, 1, out result);
                     }
                     Utils.DrawCursorSingle(sb, color, num3 - (float)Math.PI / 2f, Main.cursorScale * num, result.ToVector2(), 4);
                 }
             }
             if (!EdgeBPinned)
             {
                 Utils.DrawCursorSingle(sb, color2, 0.7853981f, Main.cursorScale * num * num2, new Vector2((float)Main.mouseX + 2.5f + 12f, (float)Main.mouseY - 5f + 12f), 5);
                 return;
             }
             int specialMode2 = 0;
             float num6 = 0f;
             Vector2 zero2 = Vector2.Zero;
             if (!Main.mapFullscreen)
             {
                 Vector2 vector5 = EdgeB.ToVector2() * 16f;
                 if (!EdgeAPinned)
                 {
                     specialMode2 = 1;
                     vector5 += Vector2.One * 8f;
                     zero2 = vector5;
                     num6 = (-vector5 + Main.ReverseGravitySupport(new Vector2(Main.mouseX, Main.mouseY)) + Main.screenPosition).ToRotation();
                     if (flag)
                     {
                         num6 = 0f - num6;
                     }
                     zero2 = Vector2.Clamp(vector5, vector, max);
                     if (zero2 != vector5)
                     {
                         num6 = (vector5 - zero2).ToRotation();
                     }
                 }
                 else
                 {
                     Vector2 vector6 = new Vector2((EdgeB.X >= EdgeA.X).ToInt() * 16, (EdgeB.Y >= EdgeA.Y).ToInt() * 16);
                     vector5 += vector6;
                     zero2 = Vector2.Clamp(vector5, vector, max);
                     num6 = (EdgeA.ToVector2() * 16f + new Vector2(16f) - vector6 - zero2).ToRotation();
                     if (zero2 != vector5)
                     {
                         num6 = (vector5 - zero2).ToRotation();
                         specialMode2 = 1;
                     }
                     if (flag)
                     {
                         num6 *= -1f;
                     }
                 }
                 Utils.DrawCursorSingle(sb, color2, num6 - (float)Math.PI / 2f, Main.cursorScale * num, Main.ReverseGravitySupport(zero2 - Main.screenPosition), 5, specialMode2);
             }
             else
             {
                 Point result3 = EdgeB;
                 if (EdgeAPinned)
                 {
                     int num7 = (EdgeB.X >= EdgeA.X).ToInt();
                     int num8 = (EdgeB.Y >= EdgeA.Y).ToInt();
                     result3.X += num7;
                     result3.Y += num8;
                     GetMapCoords(result3.X, result3.Y, 1, out result3);
                     Point result4 = EdgeA;
                     result4.X += 1 - num7;
                     result4.Y += 1 - num8;
                     GetMapCoords(result4.X, result4.Y, 1, out result4);
                     zero2 = result3.ToVector2();
                     zero2 = Vector2.Clamp(zero2, vector, max);
                     num6 = (result4.ToVector2() - zero2).ToRotation();
                 }
                 else
                 {
                     GetMapCoords(result3.X, result3.Y, 1, out result3);
                 }
                 Utils.DrawCursorSingle(sb, color2, num6 - (float)Math.PI / 2f, Main.cursorScale * num, result3.ToVector2(), 5);
             }
         }
References Color, Main.cursorColor, Main.cursorScale, Utils.DrawCursorSingle(), CaptureInterface.EdgeA, CaptureInterface.EdgeAPinned, CaptureInterface.EdgeB, CaptureInterface.EdgeBPinned, CaptureInterface.GetMapCoords(), Player.gravDir, Main.hslToRgb(), Main.mapFullscreen, Main.mouseX, Main.mouseY, Main.myPlayer, Main.player, Main.ReverseGravitySupport(), Main.rgbToHsl(), Main.screenHeight, Main.screenPosition, and Main.screenWidth.
Referenced by CaptureInterface.ModeEdgeSelection.Draw().