Terraria: PartySky.GenerateBalloons
GenerateBalloons()
void PartySky.GenerateBalloons (bool onlyMissing) inline private
     {
         if (!onlyMissing)
         {
             _balloons = new Balloon[Main.maxTilesY / 4];
         }
         for (int i = 0; i < _balloons.Length; i++)
         {
             if (!onlyMissing || !_balloons[i].Active)
             {
                 int num = (int)((double)Main.screenPosition.Y * 0.7 - (double)Main.screenHeight);
                 int minValue = (int)((double)num - Main.worldSurface * 16.0);
                 _balloons[i].Position = new Vector2(_random.Next(0, Main.maxTilesX) * 16, _random.Next(minValue, num));
                 ResetBalloon(i);
                 _balloons[i].Active = true;
             }
         }
         _balloonsDrawing = _balloons.Length;
     }
References _balloons, _balloonsDrawing, _random, PartySky.Balloon.Active, Active, Main.maxTilesX, Main.maxTilesY, UnifiedRandom.Next(), PartySky.Balloon.Position, ResetBalloon(), Main.screenHeight, Main.screenPosition, and Main.worldSurface.
Referenced by Activate(), and OnLoad().