Terraria: PartySky.ResetBalloon
ResetBalloon()
void PartySky.ResetBalloon (int i) inline
     {
         _balloons[i].Depth = (float)i / (float)_balloons.Length * 1.75f + 1.6f;
         _balloons[i].Speed = -1.5f - 2.5f * (float)_random.NextDouble();
         _balloons[i].Texture = _textures[_random.Next(2)].Value;
         _balloons[i].Variant = _random.Next(3);
         if (_random.Next(30) == 0)
         {
             _balloons[i].Texture = _textures[2].Value;
         }
     }
References _balloons, _random, _textures, PartySky.Balloon.Depth, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), PartySky.Balloon.Speed, PartySky.Balloon.Texture, Asset< T >.Value, and PartySky.Balloon.Variant.
Referenced by GenerateBalloons(), and Update().