Terraria: CommonCode.DropItemFromNPC
DropItemFromNPC()
static void CommonCode.DropItemFromNPC (NPC npc, int itemId, int stack, bool scattered = false) inline static
     {
         if (itemId > 0 && itemId < ItemID.Count)
         {
             int x = (int)npc.position.X + npc.width / 2;
             int y = (int)npc.position.Y + npc.height / 2;
             if (scattered)
             {
                 x = (int)npc.position.X + Main.rand.Next(npc.width + 1);
                 y = (int)npc.position.Y + Main.rand.Next(npc.height + 1);
             }
             int itemIndex = Item.NewItem(npc.GetItemSource_Loot(), x, y, 0, 0, itemId, stack, noBroadcast: false, -1);
             ModifyItemDropFromNPC(npc, itemIndex);
         }
     }
References ItemID.Count, NPC.GetItemSource_Loot(), Entity.height, ModifyItemDropFromNPC(), Item.NewItem(), UnifiedRandom.Next(), Entity.position, Main.rand, and Entity.width.
Referenced by DropItemForEachInteractingPlayerOnThePlayer(), DropItemLocalPerClientAndSetNPCMoneyTo0(), CommonDrop.TryDroppingItem(), CommonDropNotScalingWithLuck.TryDroppingItem(), CommonDropWithRerolls.TryDroppingItem(), DropOneByOne.TryDroppingItem(), FromOptionsWithoutRepeatsDropRule.TryDroppingItem(), MechBossSpawnersDropRule.TryDroppingItem(), OneFromOptionsDropRule.TryDroppingItem(), OneFromOptionsNotScaledWithLuckDropRule.TryDroppingItem(), and SlimeBodyItemDropRule.TryDroppingItem().