Terraria: System.Linq.Enumerable.UnionIterator.MoveNext
MoveNext()
override bool System.Linq.Enumerable.UnionIterator< TSource >.MoveNext () inline sealed inherited
Implements System.Collections.IEnumerator.
Definition at line 2717 of file Enumerable.cs.
        {
            if (_state == 1)
            {
                for (IEnumerable<TSource> enumerable = GetEnumerable(0); enumerable != null; enumerable = GetEnumerable(_state - 1))
                {
                    IEnumerator<TSource> enumerator = enumerable.GetEnumerator();
                    SetEnumerator(enumerator);
                    _state++;
                    if (enumerator.MoveNext())
                    {
                        StoreFirst();
                        return true;
                    }
                }
            }
            else if (_state > 0)
            {
                while (true)
                {
                    if (GetNext())
                    {
                        return true;
                    }
                    IEnumerable<TSource> enumerable2 = GetEnumerable(_state - 1);
                    if (enumerable2 == null)
                    {
                        break;
                    }
                    SetEnumerator(enumerable2.GetEnumerator());
                    _state++;
                }
            }
            Dispose();
            return false;
        }
References System.Linq.Enumerable.Iterator< TSource >._state, System.Linq.Enumerable.UnionIterator< TSource >.Dispose(), System.Linq.enumerable, System.Linq.Enumerable.UnionIterator< TSource >.GetEnumerable(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Linq.Enumerable.UnionIterator< TSource >.GetNext(), System.Linq.Enumerable.UnionIterator< TSource >.SetEnumerator(), and System.Linq.Enumerable.UnionIterator< TSource >.StoreFirst().