Terraria: System.Net.Mail.ISmtpAuthenticationModule.Authenticate
Authenticate()
Authorization System.Net.Mail.ISmtpAuthenticationModule.Authenticate (string challenge, NetworkCredential credentials, object sessionCookie, string spn, ChannelBinding channelBindingToken)
Implemented in System.Net.Mail.SmtpLoginAuthenticationModule, System.Net.Mail.SmtpNegotiateAuthenticationModule, and System.Net.Mail.SmtpNtlmAuthenticationModule.
Referenced by System.Net.Mail.SmtpConnection.AuthenticateCallback(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.AuthenticateContinue(), System.Net.Mail.SmtpConnection.GetConnection(), and System.Net.Mail.SmtpConnection.SetContextAndTryAuthenticate().