Terraria: System.Security.AccessControl.FileSystemSecurity.AddAccessRule
AddAccessRule() [3/3]
void System.Security.AccessControl.FileSystemSecurity.AddAccessRule (FileSystemAccessRule rule) inline
Definition at line 117 of file FileSystemSecurity.cs.
    {
        AddAccessRule((AccessRule)rule);
    }
References System.Security.AccessControl.FileSystemSecurity.AddAccessRule().
Referenced by System.Security.AccessControl.FileSystemSecurity.AddAccessRule(), and System.IO.IsolatedStorage.Helper.CreateDirectory().