Terraria: Terraria.UI.ChestUI.DepositAll
DepositAll()
static void Terraria.UI.ChestUI.DepositAll (ContainerTransferContext context) inline static
    {
        Player player = Main.player[Main.myPlayer];
        if (player.chest > -1)
        {
            MoveCoins(player.inventory, Main.chest[player.chest].item, context);
        }
        else if (player.chest == -3)
        {
            MoveCoins(player.inventory, player.bank2.item, context);
        }
        else if (player.chest == -4)
        {
            MoveCoins(player.inventory, player.bank3.item, context);
        }
        else if (player.chest == -5)
        {
            MoveCoins(player.inventory, player.bank4.item, context);
        }
        else
        {
            MoveCoins(player.inventory, player.bank.item, context);
        }
        for (int num = 49; num >= 10; num--)
        {
            if (player.inventory[num].stack > 0 && player.inventory[num].type > 0 && !player.inventory[num].favorited)
            {
                if (player.inventory[num].maxStack > 1)
                {
                    for (int i = 0; i < 40; i++)
                    {
                        if (player.chest > -1)
{
                            Chest chest = Main.chest[player.chest];
                            if (chest.item[i].stack >= chest.item[i].maxStack || !player.inventory[num].IsTheSameAs(chest.item[i]))
{
                                continue;
                            }
                            int num2 = player.inventory[num].stack;
                            if (player.inventory[num].stack + chest.item[i].stack > chest.item[i].maxStack)
{
                                num2 = chest.item[i].maxStack - chest.item[i].stack;
                            }
                            player.inventory[num].stack -= num2;
                            chest.item[i].stack += num2;
                            SoundEngine.PlaySound(7);
                            if (player.inventory[num].stack <= 0)
{
                                player.inventory[num].SetDefaults();
                                if (Main.netMode == 1)
{
                                    NetMessage.SendData(32, -1, -1, null, player.chest, i);
                                }
                                break;
                            }
                            if (chest.item[i].type == 0)
{
                                chest.item[i] = player.inventory[num].Clone();
                                player.inventory[num].SetDefaults();
                            }
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(32, -1, -1, null, player.chest, i);
                            }
                        }
                        else if (player.chest == -3)
{
                            if (player.bank2.item[i].stack < player.bank2.item[i].maxStack && player.inventory[num].IsTheSameAs(player.bank2.item[i]))
{
                                int num3 = player.inventory[num].stack;
                                if (player.inventory[num].stack + player.bank2.item[i].stack > player.bank2.item[i].maxStack)
{
                                    num3 = player.bank2.item[i].maxStack - player.bank2.item[i].stack;
                                }
                                player.inventory[num].stack -= num3;
                                player.bank2.item[i].stack += num3;
                                SoundEngine.PlaySound(7);
                                if (player.inventory[num].stack <= 0)
{
                                    player.inventory[num].SetDefaults();
                                    break;
                                }
                                if (player.bank2.item[i].type == 0)
{
                                    player.bank2.item[i] = player.inventory[num].Clone();
                                    player.inventory[num].SetDefaults();
                                }
                            }
                        }
                        else if (player.chest == -4)
{
                            if (player.bank3.item[i].stack < player.bank3.item[i].maxStack && player.inventory[num].IsTheSameAs(player.bank3.item[i]))
{
                                int num4 = player.inventory[num].stack;
                                if (player.inventory[num].stack + player.bank3.item[i].stack > player.bank3.item[i].maxStack)
{
                                    num4 = player.bank3.item[i].maxStack - player.bank3.item[i].stack;
                                }
                                player.inventory[num].stack -= num4;
                                player.bank3.item[i].stack += num4;
                                SoundEngine.PlaySound(7);
                                if (player.inventory[num].stack <= 0)
{
                                    player.inventory[num].SetDefaults();
                                    break;
                                }
                                if (player.bank3.item[i].type == 0)
{
                                    player.bank3.item[i] = player.inventory[num].Clone();
                                    player.inventory[num].SetDefaults();
                                }
                            }
                        }
                        else if (player.chest == -5)
{
                            if (player.bank4.item[i].stack < player.bank4.item[i].maxStack && player.inventory[num].IsTheSameAs(player.bank4.item[i]))
{
                                int num5 = player.inventory[num].stack;
                                if (player.inventory[num].stack + player.bank4.item[i].stack > player.bank4.item[i].maxStack)
{
                                    num5 = player.bank4.item[i].maxStack - player.bank4.item[i].stack;
                                }
                                player.inventory[num].stack -= num5;
                                player.bank4.item[i].stack += num5;
                                SoundEngine.PlaySound(7);
                                if (player.inventory[num].stack <= 0)
{
                                    player.inventory[num].SetDefaults();
                                    break;
                                }
                                if (player.bank4.item[i].type == 0)
{
                                    player.bank4.item[i] = player.inventory[num].Clone();
                                    player.inventory[num].SetDefaults();
                                }
                            }
                        }
                        else if (player.bank.item[i].stack < player.bank.item[i].maxStack && player.inventory[num].IsTheSameAs(player.bank.item[i]))
{
                            int num6 = player.inventory[num].stack;
                            if (player.inventory[num].stack + player.bank.item[i].stack > player.bank.item[i].maxStack)
{
                                num6 = player.bank.item[i].maxStack - player.bank.item[i].stack;
                            }
                            player.inventory[num].stack -= num6;
                            player.bank.item[i].stack += num6;
                            SoundEngine.PlaySound(7);
                            if (player.inventory[num].stack <= 0)
{
                                player.inventory[num].SetDefaults();
                                break;
                            }
                            if (player.bank.item[i].type == 0)
{
                                player.bank.item[i] = player.inventory[num].Clone();
                                player.inventory[num].SetDefaults();
                            }
                        }
                    }
                }
                if (player.inventory[num].stack > 0)
                {
                    if (player.chest > -1)
                    {
                        for (int j = 0; j < 40; j++)
{
                            if (Main.chest[player.chest].item[j].stack == 0)
{
                                SoundEngine.PlaySound(7);
                                Main.chest[player.chest].item[j] = player.inventory[num].Clone();
                                player.inventory[num].SetDefaults();
                                if (Main.netMode == 1)
{
                                    NetMessage.SendData(32, -1, -1, null, player.chest, j);
                                }
                                break;
                            }
                        }
                    }
                    else if (player.chest == -3)
                    {
                        for (int k = 0; k < 40; k++)
{
                            if (player.bank2.item[k].stack == 0)
{
                                SoundEngine.PlaySound(7);
                                player.bank2.item[k] = player.inventory[num].Clone();
                                player.inventory[num].SetDefaults();
                                break;
                            }
                        }
                    }
                    else if (player.chest == -4)
                    {
                        for (int l = 0; l < 40; l++)
{
                            if (player.bank3.item[l].stack == 0)
{
                                SoundEngine.PlaySound(7);
                                player.bank3.item[l] = player.inventory[num].Clone();
                                player.inventory[num].SetDefaults();
                                break;
                            }
                        }
                    }
                    else if (player.chest == -5)
                    {
                        for (int m = 0; m < 40; m++)
{
                            if (player.bank4.item[m].stack == 0)
{
                                SoundEngine.PlaySound(7);
                                player.bank4.item[m] = player.inventory[num].Clone();
                                player.inventory[num].SetDefaults();
                                break;
                            }
                        }
                    }
                    else
                    {
                        for (int n = 0; n < 40; n++)
{
                            if (player.bank.item[n].stack == 0)
{
                                SoundEngine.PlaySound(7);
                                player.bank.item[n] = player.inventory[num].Clone();
                                player.inventory[num].SetDefaults();
                                break;
                            }
                        }
                    }
                }
            }
        }
    }
References Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Main.chest, Terraria.Player.chest, Terraria.Item.Clone(), Terraria.Item.favorited, Terraria.Player.inventory, Terraria.Item.IsTheSameAs(), Terraria.Chest.item, Terraria.Item.maxStack, Terraria.UI.ChestUI.MoveCoins(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.UI.ChestUI.DrawButton().