Terraria: Terraria.UI.ChestUI.MoveCoins
MoveCoins()
static long Terraria.UI.ChestUI.MoveCoins (Item[] pInv, Item[] cInv, ContainerTransferContext context) inline static
Definition at line 1066 of file ChestUI.cs.
    {
        bool flag = false;
        int[] array = new int[4];
        List<int> list = new List<int>();
        List<int> list2 = new List<int>();
        bool flag2 = false;
        int[] array2 = new int[40];
        bool overFlowing;
        long num = Utils.CoinsCount(out overFlowing, pInv);
        for (int i = 0; i < cInv.Length; i++)
        {
            array2[i] = -1;
            if (cInv[i].stack < 1 || cInv[i].type < 1)
            {
                list2.Add(i);
                cInv[i] = new Item();
            }
            if (cInv[i] != null && cInv[i].stack > 0)
            {
                int num2 = 0;
                if (cInv[i].type == 71)
                {
                    num2 = 1;
                }
                if (cInv[i].type == 72)
                {
                    num2 = 2;
                }
                if (cInv[i].type == 73)
                {
                    num2 = 3;
                }
                if (cInv[i].type == 74)
                {
                    num2 = 4;
                }
                array2[i] = num2 - 1;
                if (num2 > 0)
                {
                    array[num2 - 1] += cInv[i].stack;
                    list2.Add(i);
                    cInv[i] = new Item();
                    flag2 = true;
                }
            }
        }
        if (!flag2)
        {
            return 0L;
        }
        for (int j = 0; j < pInv.Length; j++)
        {
            if (j != 58 && pInv[j] != null && pInv[j].stack > 0 && !pInv[j].favorited)
            {
                int num3 = 0;
                if (pInv[j].type == 71)
                {
                    num3 = 1;
                }
                if (pInv[j].type == 72)
                {
                    num3 = 2;
                }
                if (pInv[j].type == 73)
                {
                    num3 = 3;
                }
                if (pInv[j].type == 74)
                {
                    num3 = 4;
                }
                if (num3 > 0)
                {
                    flag = true;
                    array[num3 - 1] += pInv[j].stack;
                    list.Add(j);
                    pInv[j] = new Item();
                }
            }
        }
        for (int k = 0; k < 3; k++)
        {
            while (array[k] >= 100)
            {
                array[k] -= 100;
                array[k + 1]++;
            }
        }
        for (int l = 0; l < 40; l++)
        {
            if (array2[l] < 0 || cInv[l].type != 0)
            {
                continue;
            }
            int num4 = l;
            int num5 = array2[l];
            if (array[num5] > 0)
            {
                cInv[num4].SetDefaults(71 + num5);
                cInv[num4].stack = array[num5];
                if (cInv[num4].stack > cInv[num4].maxStack)
                {
                    cInv[num4].stack = cInv[num4].maxStack;
                }
                array[num5] -= cInv[num4].stack;
                array2[l] = -1;
            }
            if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
            {
                NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, num4);
            }
            list2.Remove(num4);
        }
        for (int m = 0; m < 40; m++)
        {
            if (array2[m] < 0 || cInv[m].type != 0)
            {
                continue;
            }
            int num6 = m;
            int num7 = 3;
            while (num7 >= 0)
            {
                if (array[num7] > 0)
                {
                    cInv[num6].SetDefaults(71 + num7);
                    cInv[num6].stack = array[num7];
                    if (cInv[num6].stack > cInv[num6].maxStack)
                    {
                        cInv[num6].stack = cInv[num6].maxStack;
                    }
                    array[num7] -= cInv[num6].stack;
                    array2[m] = -1;
                    break;
                }
                if (array[num7] == 0)
                {
                    num7--;
                }
            }
            if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
            {
                NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, num6);
            }
            list2.Remove(num6);
        }
        while (list2.Count > 0)
        {
            int num8 = list2[0];
            int num9 = 3;
            while (num9 >= 0)
            {
                if (array[num9] > 0)
                {
                    cInv[num8].SetDefaults(71 + num9);
                    cInv[num8].stack = array[num9];
                    if (cInv[num8].stack > cInv[num8].maxStack)
                    {
                        cInv[num8].stack = cInv[num8].maxStack;
                    }
                    array[num9] -= cInv[num8].stack;
                    break;
                }
                if (array[num9] == 0)
                {
                    num9--;
                }
            }
            if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
            {
                NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, list2[0]);
            }
            list2.RemoveAt(0);
        }
        int num10 = 3;
        while (num10 >= 0 && list.Count > 0)
        {
            int num11 = list[0];
            if (array[num10] > 0)
            {
                pInv[num11].SetDefaults(71 + num10);
                pInv[num11].stack = array[num10];
                if (pInv[num11].stack > pInv[num11].maxStack)
                {
                    pInv[num11].stack = pInv[num11].maxStack;
                }
                array[num10] -= pInv[num11].stack;
                flag = false;
                list.RemoveAt(0);
            }
            if (array[num10] == 0)
            {
                num10--;
            }
        }
        if (flag)
        {
            SoundEngine.PlaySound(7);
        }
        bool overFlowing2;
        long num12 = Utils.CoinsCount(out overFlowing2, pInv);
        if (overFlowing || overFlowing2)
        {
            return 0L;
        }
        return num - num12;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.Utils.CoinsCount(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.Item.maxStack, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), and Terraria.Item.stack.
Referenced by Terraria.UI.ChestUI.DepositAll(), and Terraria.UI.ChestUI.QuickStack().