Terraria: Terraria.UI.ChestUI.GetContainerUsageInfo
GetContainerUsageInfo()
static void Terraria.UI.ChestUI.GetContainerUsageInfo (out bool sync, out Item[] chestinv) inline static
Definition at line 1352 of file ChestUI.cs.
    {
        sync = false;
        Player player = Main.player[Main.myPlayer];
        chestinv = player.bank.item;
        if (player.chest > -1)
        {
            chestinv = Main.chest[player.chest].item;
            sync = Main.netMode == 1;
        }
        else if (player.chest == -2)
        {
            chestinv = player.bank.item;
        }
        else if (player.chest == -3)
        {
            chestinv = player.bank2.item;
        }
        else if (player.chest == -4)
        {
            chestinv = player.bank3.item;
        }
        else if (player.chest == -5)
        {
            chestinv = player.bank4.item;
        }
    }
References Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Main.chest, Terraria.Player.chest, Terraria.Chest.item, Terraria.Main.myPlayer, and Terraria.Main.player.
Referenced by Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo(), Terraria.UI.ItemSlot.PickItemMovementAction(), and Terraria.UI.ChestUI.TryPlacingInChest().