Terraria: System.Security.AccessControl.FileSystemSecurity.RemoveAccessRuleSpecific
RemoveAccessRuleSpecific() [3/3]
void System.Security.AccessControl.FileSystemSecurity.RemoveAccessRuleSpecific (FileSystemAccessRule rule) inline
Definition at line 155 of file FileSystemSecurity.cs.
    {
        if (rule == null)
        {
            throw new ArgumentNullException("rule");
        }
        AuthorizationRuleCollection accessRules = GetAccessRules(includeExplicit: true, includeInherited: true, rule.IdentityReference.GetType());
        for (int i = 0; i < accessRules.Count; i++)
        {
            if (accessRules[i] is FileSystemAccessRule fileSystemAccessRule && fileSystemAccessRule.FileSystemRights == rule.FileSystemRights && fileSystemAccessRule.IdentityReference == rule.IdentityReference && fileSystemAccessRule.AccessControlType == rule.AccessControlType)
            {
                RemoveAccessRuleSpecific((AccessRule)rule);
                return;
            }
        }
        FileSystemAccessRule rule2 = new FileSystemAccessRule(rule.IdentityReference, FileSystemAccessRule.AccessMaskFromRights(rule.FileSystemRights, AccessControlType.Deny), rule.IsInherited, rule.InheritanceFlags, rule.PropagationFlags, rule.AccessControlType);
        RemoveAccessRuleSpecific((AccessRule)rule2);
    }
References System.Security.AccessControl.AccessRule< T >.AccessControlType, System.Security.AccessControl.FileSystemAccessRule.AccessMaskFromRights(), System.Collections.ReadOnlyCollectionBase.Count, System.Security.AccessControl.FileSystemAccessRule.FileSystemRights, System.Security.AccessControl.CommonObjectSecurity.GetAccessRules(), System.Security.AccessControl.AuthorizationRule.IdentityReference, System.Security.AccessControl.AuthorizationRule.InheritanceFlags, System.Security.AccessControl.AuthorizationRule.IsInherited, System.Security.AccessControl.AuthorizationRule.PropagationFlags, and System.Security.AccessControl.FileSystemSecurity.RemoveAccessRuleSpecific().
Referenced by System.Security.AccessControl.FileSystemSecurity.RemoveAccessRuleSpecific().