Terraria: Terraria.UI.ChestUI.DrawButton
DrawButton()
static void Terraria.UI.ChestUI.DrawButton (SpriteBatch spriteBatch, int ID, int X, int Y) inline static private
Definition at line 188 of file ChestUI.cs.
    {
        Player player = Main.player[Main.myPlayer];
        if ((ID == 5 && player.chest < -1) || (ID == 6 && !Main.editChest))
        {
            UpdateHover(ID, hovering: false);
            return;
        }
        if (ID == 7 && player.chest != -5)
        {
            UpdateHover(ID, hovering: false);
            return;
        }
        int num = ID;
        if (ID == 7)
        {
            num = 5;
        }
        Y += num * 26;
        float num2 = ButtonScale[ID];
        string text = "";
        switch (ID)
        {
        case 0:
            text = Lang.inter[29].Value;
            break;
        case 1:
            text = Lang.inter[30].Value;
            break;
        case 2:
            text = Lang.inter[31].Value;
            break;
        case 3:
            text = Lang.inter[82].Value;
            break;
        case 5:
            text = Lang.inter[Main.editChest ? 47 : 61].Value;
            break;
        case 6:
            text = Lang.inter[63].Value;
            break;
        case 4:
            text = Lang.inter[122].Value;
            break;
        case 7:
            text = ((!player.IsVoidVaultEnabled) ? Language.GetTextValue("UI.ToggleBank4VacuumIsOff") : Language.GetTextValue("UI.ToggleBank4VacuumIsOn"));
            break;
        }
        Vector2 vector = FontAssets.MouseText.Value.MeasureString(text);
        Color color = new Color(Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor) * num2;
        color = Color.White * 0.97f * (1f - (255f - (float)(int)Main.mouseTextColor) / 255f * 0.5f);
        color.A = byte.MaxValue;
        X += (int)(vector.X * num2 / 2f);
        bool flag = Utils.FloatIntersect(Main.mouseX, Main.mouseY, 0f, 0f, (float)X - vector.X / 2f, Y - 12, vector.X, 24f);
        if (ButtonHovered[ID])
        {
            flag = Utils.FloatIntersect(Main.mouseX, Main.mouseY, 0f, 0f, (float)X - vector.X / 2f - 10f, Y - 12, vector.X + 16f, 24f);
        }
        if (flag)
        {
            color = Main.OurFavoriteColor;
        }
        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(X, Y), color, 0f, vector / 2f, new Vector2(num2), -1f, 1.5f);
        vector *= num2;
        switch (ID)
        {
        case 0:
            UILinkPointNavigator.SetPosition(500, new Vector2((float)X - vector.X * num2 / 2f * 0.8f, Y));
            break;
        case 1:
            UILinkPointNavigator.SetPosition(501, new Vector2((float)X - vector.X * num2 / 2f * 0.8f, Y));
            break;
        case 2:
            UILinkPointNavigator.SetPosition(502, new Vector2((float)X - vector.X * num2 / 2f * 0.8f, Y));
            break;
        case 5:
            UILinkPointNavigator.SetPosition(504, new Vector2(X, Y));
            break;
        case 6:
            UILinkPointNavigator.SetPosition(504, new Vector2(X, Y));
            break;
        case 3:
            UILinkPointNavigator.SetPosition(503, new Vector2((float)X - vector.X * num2 / 2f * 0.8f, Y));
            break;
        case 4:
            UILinkPointNavigator.SetPosition(505, new Vector2((float)X - vector.X * num2 / 2f * 0.8f, Y));
            break;
        case 7:
            UILinkPointNavigator.SetPosition(506, new Vector2((float)X - vector.X * num2 / 2f * 0.8f, Y));
            break;
        }
        if (!flag)
        {
            UpdateHover(ID, hovering: false);
            return;
        }
        UpdateHover(ID, hovering: true);
        if (PlayerInput.IgnoreMouseInterface)
        {
            return;
        }
        player.mouseInterface = true;
        if (Main.mouseLeft && Main.mouseLeftRelease)
        {
            switch (ID)
            {
            case 0:
                LootAll();
                break;
            case 1:
                DepositAll(ContainerTransferContext.FromUnknown(player));
                break;
            case 2:
                QuickStack(ContainerTransferContext.FromUnknown(player));
                break;
            case 5:
                RenameChest();
                break;
            case 6:
                RenameChestCancel();
                break;
            case 3:
                Restock();
                break;
            case 4:
                ItemSorting.SortChest();
                break;
            case 7:
                ToggleVacuum();
                break;
            }
            Recipe.FindRecipes();
        }
    }
References Terraria.UI.ChestUI.ButtonHovered, Terraria.UI.ChestUI.ButtonScale, Terraria.Player.chest, Terraria.UI.ChestUI.DepositAll(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.editChest, Terraria.Recipe.FindRecipes(), Terraria.Utils.FloatIntersect(), Terraria.DataStructures.ContainerTransferContext.FromUnknown(), Terraria.Localization.Language.GetTextValue(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Lang.inter, Terraria.Player.IsVoidVaultEnabled, Terraria.UI.ChestUI.LootAll(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.UI.ChestUI.QuickStack(), Terraria.UI.ChestUI.RenameChest(), Terraria.UI.ChestUI.RenameChestCancel(), Terraria.UI.ChestUI.Restock(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.UI.ItemSorting.SortChest(), Terraria.UI.ChestUI.ToggleVacuum(), Terraria.UI.ChestUI.UpdateHover(), ReLogic.Content.Asset< T >.Value, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.UI.ChestUI.DrawButtons().