Terraria: Terraria.UI.ChestUI.RenameChestSubmit
RenameChestSubmit()
static void Terraria.UI.ChestUI.RenameChestSubmit (Player player) inline static
    {
        SoundEngine.PlaySound(12);
        Main.editChest = false;
        int chest = player.chest;
        if (chest < 0)
        {
            return;
        }
        if (Main.npcChatText == Main.defaultChestName)
        {
            Main.npcChatText = "";
        }
        if (Main.chest[chest].name != Main.npcChatText)
        {
            Main.chest[chest].name = Main.npcChatText;
            if (Main.netMode == 1)
            {
                player.editedChestName = true;
            }
        }
    }
References Terraria.Main.chest, Terraria.Player.chest, Terraria.Main.defaultChestName, Terraria.Chest.name, Terraria.Main.netMode, Terraria.Main.npcChatText, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), Terraria.Main.InputTextChest(), and Terraria.UI.ChestUI.RenameChest().