Terraria: Terraria.UI.ChestUI.IsBlockedFromTransferIntoChest
IsBlockedFromTransferIntoChest()
static bool Terraria.UI.ChestUI.IsBlockedFromTransferIntoChest (Item item, Item[] container) inline static
    {
        if (item.type == 3213 && item.favorited && container == Main.LocalPlayer.bank.item)
        {
            return true;
        }
        if ((item.type == 4131 || item.type == 5325) && item.favorited && container == Main.LocalPlayer.bank4.item)
        {
            return true;
        }
        return false;
    }
References Terraria.Player.bank, Terraria.Player.bank4, Terraria.Item.favorited, Terraria.Chest.item, Terraria.Main.LocalPlayer, and Terraria.Item.type.
Referenced by Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo(), Terraria.UI.ItemSlot.PickItemMovementAction(), and Terraria.UI.ChestUI.TryPlacingInChest().