Terraria: System.Security.AccessControl.FileSystemSecurity.Persist
Persist() [2/8]
void System.Security.AccessControl.FileSystemSecurity.Persist (SafeFileHandle handle, string fullPath) inline package
Definition at line 99 of file FileSystemSecurity.cs.
    {
        WriteLock();
        try
        {
            AccessControlSections accessControlSectionsFromChanges = GetAccessControlSectionsFromChanges();
            Persist(handle, accessControlSectionsFromChanges);
            bool flag2 = (base.AccessRulesModified = false);
            bool flag4 = (base.AuditRulesModified = flag2);
            bool ownerModified = (base.GroupModified = flag4);
            base.OwnerModified = ownerModified;
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.Security.AccessControl.FileSystemSecurity.GetAccessControlSectionsFromChanges(), System.handle, System.Security.AccessControl.FileSystemSecurity.Persist(), System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().