Terraria: UIVerticalSlider.DrawSelf
DrawSelf()
override void UIVerticalSlider.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         UISliderBase.CurrentAimedSlider = null;
         if (!Main.mouseLeft)
         {
             UISliderBase.CurrentLockedSlider = null;
         }
         GetUsageLevel();
         FillPercent = _getSliderValue();
         float sliderValueThatWasSet = FillPercent;
         bool flag = false;
         if (DrawValueBarDynamicWidth(spriteBatch, out sliderValueThatWasSet))
         {
             flag = true;
         }
         if (UISliderBase.CurrentLockedSlider == this || flag)
         {
             UISliderBase.CurrentAimedSlider = this;
             if (PlayerInput.Triggers.Current.MouseLeft && !PlayerInput.UsingGamepad && UISliderBase.CurrentLockedSlider == this)
             {
                 _slideKeyboardAction(sliderValueThatWasSet);
                 if (!_soundedUsage)
                 {
                     SoundEngine.PlaySound(12);
                 }
                 _soundedUsage = true;
             }
             else
             {
                 _soundedUsage = false;
             }
         }
         if (UISliderBase.CurrentAimedSlider != null && UISliderBase.CurrentLockedSlider == null)
         {
             UISliderBase.CurrentLockedSlider = UISliderBase.CurrentAimedSlider;
         }
         if (_isReallyMouseOvered)
         {
             _slideGamepadAction();
         }
     }
References _getSliderValue, _isReallyMouseOvered, _slideGamepadAction, _slideKeyboardAction, _soundedUsage, TriggersPack.Current, UISliderBase.CurrentAimedSlider, UISliderBase.CurrentLockedSlider, DrawValueBarDynamicWidth(), FillPercent, UISliderBase.GetUsageLevel(), TriggersSet.MouseLeft, Main.mouseLeft, SoundEngine.PlaySound(), PlayerInput.Triggers, and PlayerInput.UsingGamepad.