Terraria: Terraria.Social.WeGame.MessageDispatcherServer.Init
Init()
void Terraria.Social.WeGame.MessageDispatcherServer.Init (string serverName) inline
    {
        _ipcSever.Init(serverName);
        _ipcSever.OnDataArrive += OnDataArrive;
        _ipcSever.OnClientAccess += OnClientAccess;
    }
References Terraria.Social.WeGame.MessageDispatcherServer._ipcSever, Terraria.Social.WeGame.IPCServer.Init(), Terraria.Social.WeGame.MessageDispatcherServer.OnClientAccess(), and Terraria.Social.WeGame.MessageDispatcherServer.OnDataArrive().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.LazyCreateWeGameMsgServer().