Terraria: AmbientSky.SkyEntity.Helper_GetOpacityWithAccountingForOceanWaterLine
Helper_GetOpacityWithAccountingForOceanWaterLine()
float AmbientSky.SkyEntity.Helper_GetOpacityWithAccountingForOceanWaterLine () inline package inherited
         {
             Vector2 vector = GetDrawPositionByDepth() - Main.Camera.UnscaledPosition;
             int num = SourceRectangle.Height / 2;
             float t = vector.Y + (float)num;
             float yScreenPosition = AmbientSkyDrawCache.Instance.OceanLineInfo.YScreenPosition;
             float lerpValue = Utils.GetLerpValue(yScreenPosition - 10f, yScreenPosition - 2f, t, clamped: true);
             lerpValue *= AmbientSkyDrawCache.Instance.OceanLineInfo.OceanOpacity;
             return 1f - lerpValue;
         }
References Main.Camera, AmbientSky.SkyEntity.GetDrawPositionByDepth(), Utils.GetLerpValue(), AmbientSkyDrawCache.Instance, AmbientSkyDrawCache.OceanLineInfo, AmbientSkyDrawCache.OceanLineCache.OceanOpacity, AmbientSky.SkyEntity.SourceRectangle, Camera.UnscaledPosition, and AmbientSkyDrawCache.OceanLineCache.YScreenPosition.
Referenced by AmbientSky.FadingSkyEntity.GetColor().