Terraria: System.Collections.Concurrent.SingleProducerSingleConsumerQueue.EnqueueSlow
EnqueueSlow()
void System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >.EnqueueSlow (T item, ref Segment segment) inline private
Definition at line 124 of file SingleProducerSingleConsumerQueue.cs.
    {
        if (segment._state._firstCopy != segment._state._first)
        {
            segment._state._firstCopy = segment._state._first;
            Enqueue(item);
            return;
        }
        int num = _tail._array.Length << 1;
        if (num > 16777216)
        {
            num = 16777216;
        }
        Segment segment2 = new Segment(num);
        segment2._array[0] = item;
        segment2._state._last = 1;
        segment2._state._lastCopy = 1;
        try
        {
        }
        finally
        {
            Volatile.Write(ref _tail._next, segment2);
            _tail = segment2;
        }
    }
References System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >._tail, System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >.Enqueue(), System.item, and System.Threading.Volatile.Write().
Referenced by System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >.Enqueue().