Terraria: System.Collections.Concurrent.SingleProducerSingleConsumerQueue.TryDequeueSlow
TryDequeueSlow()
bool System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >.TryDequeueSlow (Segment segment, T[] array, bool peek, [MaybeNullWhen(false)] out T result) inline private
Definition at line 179 of file SingleProducerSingleConsumerQueue.cs.
    {
        if (segment._state._last != segment._state._lastCopy)
        {
            segment._state._lastCopy = segment._state._last;
            if (!peek)
            {
                return TryDequeue(out result);
            }
            return TryPeek(out result);
        }
        if (segment._next != null && segment._state._first == segment._state._last)
        {
            segment = segment._next;
            array = segment._array;
            _head = segment;
        }
        int first = segment._state._first;
        if (first == segment._state._last)
        {
            result = default(T);
            return false;
        }
        result = array[first];
        if (!peek)
        {
            array[first] = default(T);
            segment._state._first = (first + 1) & (segment._array.Length - 1);
            segment._state._lastCopy = segment._state._last;
        }
        return true;
    }
References System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >._head, System.array, System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >.TryDequeue(), and System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >.TryPeek().
Referenced by System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >.TryDequeue(), and System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >.TryPeek().