Terraria: System.IO.FileInfo.MoveTo
MoveTo() [2/2]
void System.IO.FileInfo.MoveTo (string destFileName, bool overwrite) inline
Definition at line 145 of file FileInfo.cs.
    {
        if (destFileName == null)
        {
            throw new ArgumentNullException("destFileName");
        }
        if (destFileName.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyFileName, "destFileName");
        }
        string fullPath = Path.GetFullPath(destFileName);
        if (!new DirectoryInfo(Path.GetDirectoryName(FullName)).Exists)
        {
            throw new DirectoryNotFoundException(SR.Format(SR.IO_PathNotFound_Path, FullName));
        }
        if (!Exists)
        {
            throw new FileNotFoundException(SR.Format(SR.IO_FileNotFound_FileName, FullName), FullName);
        }
        FileSystem.MoveFile(FullPath, fullPath, overwrite);
        FullPath = fullPath;
        OriginalPath = destFileName;
        _name = Path.GetFileName(fullPath);
        Invalidate();
    }
References System.IO.FileSystemInfo._name, System.SR.Argument_EmptyFileName, System.IO.FileSystemInfo.Exists, System.SR.Format(), System.IO.FileSystemInfo.FullName, System.IO.FileSystemInfo.FullPath, System.IO.Path.GetDirectoryName(), System.IO.Path.GetFileName(), System.IO.Path.GetFullPath(), System.IO.FileSystemInfo.Invalidate(), System.SR.IO_FileNotFound_FileName, System.SR.IO_PathNotFound_Path, System.IO.FileSystem.MoveFile(), and System.IO.FileSystemInfo.OriginalPath.