Terraria: Terraria.GameContent.Skies.PartySky.ResetBalloon
ResetBalloon()
void Terraria.GameContent.Skies.PartySky.ResetBalloon (int i) inline
Definition at line 115 of file PartySky.cs.
    {
        _balloons[i].Depth = (float)i / (float)_balloons.Length * 1.75f + 1.6f;
        _balloons[i].Speed = -1.5f - 2.5f * (float)_random.NextDouble();
        _balloons[i].Texture = _textures[_random.Next(2)].Value;
        _balloons[i].Variant = _random.Next(3);
        if (_random.Next(30) == 0)
        {
            _balloons[i].Texture = _textures[2].Value;
        }
    }
References Terraria.GameContent.Skies.PartySky._balloons, Terraria.GameContent.Skies.PartySky._random, Terraria.GameContent.Skies.PartySky._textures, Terraria.GameContent.Skies.PartySky.Balloon.Depth, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.GameContent.Skies.PartySky.Balloon.Speed, Terraria.GameContent.Skies.PartySky.Balloon.Texture, ReLogic.Content.Asset< T >.Value, and Terraria.GameContent.Skies.PartySky.Balloon.Variant.
Referenced by Terraria.GameContent.Skies.PartySky.GenerateBalloons(), and Terraria.GameContent.Skies.PartySky.Update().