Terraria: Terraria.GameContent.Skies.PartySky.Update
Update()
override void Terraria.GameContent.Skies.PartySky.Update (GameTime gameTime) inline
Definition at line 136 of file PartySky.cs.
    {
        if (!MultipleSkyWorkaroundFix && Main.dayRate == 0)
        {
            return;
        }
        MultipleSkyWorkaroundFix = false;
        if (Main.gamePaused || !Main.hasFocus)
        {
            return;
        }
        _opacity = Utils.Clamp(_opacity + (float)IsNearParty().ToDirectionInt() * 0.01f, 0f, 1f);
        for (int i = 0; i < _balloons.Length; i++)
        {
            if (!_balloons[i].Active)
            {
                continue;
            }
            _balloons[i].Frame++;
            _balloons[i].Position.Y += _balloons[i].Speed;
            _balloons[i].Position.X += Main.windSpeedCurrent * (3f - _balloons[i].Speed);
            if (!(_balloons[i].Position.Y < 300f))
            {
                continue;
            }
            if (!_leaving)
            {
                ResetBalloon(i);
                _balloons[i].Position = new Vector2(_random.Next(0, Main.maxTilesX) * 16, (float)Main.worldSurface * 16f + 1600f);
                if (_random.Next(30) == 0)
                {
                    _balloons[i].Texture = _textures[2].Value;
                }
            }
            else
            {
                _balloons[i].Active = false;
                _balloonsDrawing--;
            }
        }
        if (_balloonsDrawing == 0)
        {
            _active = false;
        }
        _active = true;
    }
References Terraria.GameContent.Skies.PartySky._active, Terraria.GameContent.Skies.PartySky._balloons, Terraria.GameContent.Skies.PartySky._balloonsDrawing, Terraria.GameContent.Skies.PartySky._leaving, Terraria.GameContent.Skies.PartySky._opacity, Terraria.GameContent.Skies.PartySky._random, Terraria.GameContent.Skies.PartySky._textures, Terraria.GameContent.Skies.PartySky.Balloon.Active, Terraria.Graphics.Effects.Active, Terraria.Main.dayRate, Terraria.GameContent.Skies.PartySky.Balloon.Frame, Terraria.Main.gamePaused, Terraria.Main.hasFocus, Terraria.GameContent.Skies.PartySky.IsNearParty(), Terraria.Main.maxTilesX, Terraria.GameContent.Skies.PartySky.MultipleSkyWorkaroundFix, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Skies.PartySky.Balloon.Position, Terraria.GameContent.Skies.PartySky.ResetBalloon(), Terraria.GameContent.Skies.PartySky.Balloon.Speed, Terraria.GameContent.Skies.PartySky.Balloon.Texture, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.