Terraria: System.Net.Http.HttpContent.LimitMemoryStream.CheckSize
CheckSize()
void System.Net.Http.HttpContent.LimitMemoryStream.CheckSize (int countToAdd) inline private
Definition at line 81 of file HttpContent.cs.
        {
            if (_maxSize - Length < countToAdd)
            {
                throw CreateOverCapacityException(_maxSize);
            }
        }
References System.Net.Http.HttpContent.LimitMemoryStream._maxSize, System.Net.Http.HttpContent.CreateOverCapacityException(), and System.IO.MemoryStream.Length.
Referenced by System.Net.Http.HttpContent.LimitMemoryStream.BeginWrite(), System.Net.Http.HttpContent.LimitMemoryStream.Write(), System.Net.Http.HttpContent.LimitMemoryStream.WriteAsync(), System.Net.Http.HttpContent.LimitMemoryStream.WriteAsync(), and System.Net.Http.HttpContent.LimitMemoryStream.WriteByte().