Terraria: System.Text.Encodings.Web.TextEncoder.Encode
Encode() [1/5]
virtual OperationStatus System.Text.Encodings.Web.TextEncoder.Encode (ReadOnlySpan< char > source, Span< char > destination, out int charsConsumed, out int charsWritten, bool isFinalBlock = true) inline virtual inherited
Definition at line 243 of file TextEncoder.cs.
    {
        ReadOnlySpan<char> text = source;
        if (destination.Length < source.Length)
        {
            text = source.Slice(0, destination.Length);
        }
        int num = FindFirstCharacterToEncode(text);
        if (num < 0)
        {
            num = text.Length;
        }
        source.Slice(0, num).CopyTo(destination);
        if (num == source.Length)
        {
            charsConsumed = source.Length;
            charsWritten = source.Length;
            return OperationStatus.Done;
        }
        int charsConsumed2;
        int charsWritten2;
        OperationStatus result = EncodeCore(source.Slice(num), destination.Slice(num), out charsConsumed2, out charsWritten2, isFinalBlock);
        charsConsumed = num + charsConsumed2;
        charsWritten = num + charsWritten2;
        return result;
    }
References System.destination, System.Text.Encodings.Web.TextEncoder.EncodeCore(), System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncode(), System.ReadOnlySpan< T >.Slice(), System.source, and System.text.