Terraria: System.Text.Encodings.Web.TextEncoder.EncodeToNewString
EncodeToNewString()
string System.Text.Encodings.Web.TextEncoder.EncodeToNewString (ReadOnlySpan< char > value, int indexOfFirstCharToEncode) inline private inherited
Definition at line 82 of file TextEncoder.cs.
    {
        ReadOnlySpan<char> source = value.Slice(indexOfFirstCharToEncode);
        Span<char> initialBuffer = stackalloc char[1024];
        System.Text.ValueStringBuilder valueStringBuilder = new System.Text.ValueStringBuilder(initialBuffer);
        int val = Math.Max(MaxOutputCharactersPerInputCharacter, 1024);
        do
        {
            Span<char> destination = valueStringBuilder.AppendSpan(Math.Max(source.Length, val));
            EncodeCore(source, destination, out var charsConsumed, out var charsWritten, isFinalBlock: true);
            if (charsWritten == 0 || (uint)charsWritten > (uint)destination.Length)
            {
                ThrowArgumentException_MaxOutputCharsPerInputChar();
            }
            source = source.Slice(charsConsumed);
            valueStringBuilder.Length -= destination.Length - charsWritten;
        }
        while (!source.IsEmpty);
        string result = string.Concat(value.Slice(0, indexOfFirstCharToEncode), valueStringBuilder.AsSpan());
        valueStringBuilder.Dispose();
        return result;
    }
References System.Text.ValueStringBuilder.AppendSpan(), System.Text.ValueStringBuilder.AsSpan(), System.destination, System.Text.ValueStringBuilder.Dispose(), System.Text.Encodings.Web.TextEncoder.EncodeCore(), System.Math.Max(), System.Text.Encodings.Web.TextEncoder.MaxOutputCharactersPerInputCharacter, System.ReadOnlySpan< T >.Slice(), System.source, System.Text.Encodings.Web.TextEncoder.ThrowArgumentException_MaxOutputCharsPerInputChar(), and System.Text.Encodings.Web.value.
Referenced by System.Text.Encodings.Web.TextEncoder.Encode().