Terraria: System.Text.Encodings.Web.TextEncoder.Encode
Encode() [2/5]
virtual string System.Text.Encodings.Web.TextEncoder.Encode (string value) inline virtual inherited
Definition at line 68 of file TextEncoder.cs.
    {
        if (value == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.value);
        }
        int num = FindFirstCharacterToEncode(value.AsSpan());
        if (num < 0)
        {
            return value;
        }
        return EncodeToNewString(value.AsSpan(), num);
    }
References System.Text.Encodings.Web.TextEncoder.EncodeToNewString(), System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncode(), System.Text.Encodings.Web.ThrowHelper.ThrowArgumentNullException(), and System.Text.Encodings.Web.value.
Referenced by System.Text.Encodings.Web.TextEncoder.Encode(), and System.Text.Json.JsonWriterHelper.EscapeString().