Terraria: System.Text.Encodings.Web.TextEncoder.EncodeCore
EncodeCore() [1/2]
virtual OperationStatus System.Text.Encodings.Web.TextEncoder.EncodeCore (ReadOnlySpan< char > source, Span< char > destination, out int charsConsumed, out int charsWritten, bool isFinalBlock) inline protected virtual inherited
Reimplemented in System.Text.Encodings.Web.DefaultHtmlEncoder, System.Text.Encodings.Web.DefaultJavaScriptEncoder, and System.Text.Encodings.Web.DefaultUrlEncoder.
Definition at line 270 of file TextEncoder.cs.
    {
        int length = source.Length;
        int length2 = destination.Length;
        OperationStatus result2;
        while (true)
        {
            if (!source.IsEmpty)
            {
                Rune result;
                int charsConsumed2;
                OperationStatus operationStatus = Rune.DecodeFromUtf16(source, out result, out charsConsumed2);
                if (operationStatus != 0)
                {
                    if (!isFinalBlock && operationStatus == OperationStatus.NeedMoreData)
                    {
                        result2 = OperationStatus.NeedMoreData;
                        break;
                    }
                }
                else if (!WillEncode(result.Value))
                {
                    if (result.TryEncodeToUtf16(destination, out var _))
                    {
                        source = source.Slice(charsConsumed2);
                        destination = destination.Slice(charsConsumed2);
                        continue;
                    }
                    goto IL_00ad;
                }
                if (TryEncodeUnicodeScalar((uint)result.Value, destination, out var charsWritten3))
                {
                    source = source.Slice(charsConsumed2);
                    destination = destination.Slice(charsWritten3);
                    continue;
                }
                goto IL_00ad;
            }
            result2 = OperationStatus.Done;
            break;
            IL_00ad:
            result2 = OperationStatus.DestinationTooSmall;
            break;
        }
        charsConsumed = length - source.Length;
        charsWritten = length2 - destination.Length;
        return result2;
    }
References System.Text.Rune.DecodeFromUtf16(), System.destination, System.length, System.length2, System.source, System.Text.Rune.TryEncodeToUtf16(), System.Text.Encodings.Web.TextEncoder.TryEncodeUnicodeScalar(), System.Text.Rune.Value, and System.Text.Encodings.Web.TextEncoder.WillEncode().
Referenced by System.Text.Encodings.Web.TextEncoder.Encode(), System.Text.Encodings.Web.TextEncoder.Encode(), System.Text.Encodings.Web.TextEncoder.Encode(), System.Text.Encodings.Web.TextEncoder.EncodeCore(), and System.Text.Encodings.Web.TextEncoder.EncodeToNewString().