Terraria: System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8
FindFirstCharacterToEncodeUtf8()
virtual int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8 (ReadOnlySpan< byte > utf8Text) inline virtual inherited
Reimplemented in System.Text.Encodings.Web.DefaultHtmlEncoder, System.Text.Encodings.Web.DefaultJavaScriptEncoder, and System.Text.Encodings.Web.DefaultUrlEncoder.
Definition at line 347 of file TextEncoder.cs.
    {
        int length = utf8Text.Length;
        Rune result;
        int bytesConsumed;
        while (!utf8Text.IsEmpty && Rune.DecodeFromUtf8(utf8Text, out result, out bytesConsumed) == OperationStatus.Done && !WillEncode(result.Value))
        {
            utf8Text = utf8Text.Slice(bytesConsumed);
        }
        if (!utf8Text.IsEmpty)
        {
            return length - utf8Text.Length;
        }
        return -1;
    }
References System.Text.Rune.DecodeFromUtf8(), System.ReadOnlySpan< T >.IsEmpty, System.length, System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), System.Text.Rune.Value, and System.Text.Encodings.Web.TextEncoder.WillEncode().
Referenced by System.Text.Encodings.Web.TextEncoder.EncodeUtf8().