Terraria: System.Text.Encodings.Web.TextEncoder.EncodeUtf8Core
EncodeUtf8Core()
virtual OperationStatus System.Text.Encodings.Web.TextEncoder.EncodeUtf8Core (ReadOnlySpan< byte > utf8Source, Span< byte > utf8Destination, out int bytesConsumed, out int bytesWritten, bool isFinalBlock) inline protected virtual inherited
Reimplemented in System.Text.Encodings.Web.DefaultHtmlEncoder, System.Text.Encodings.Web.DefaultJavaScriptEncoder, and System.Text.Encodings.Web.DefaultUrlEncoder.
Definition at line 183 of file TextEncoder.cs.
    {
        int length = utf8Source.Length;
        int length2 = utf8Destination.Length;
        Span<char> utf16ScratchBuffer = stackalloc char[24];
        OperationStatus result2;
        while (true)
        {
            int bytesConsumed2;
            int num2;
            if (!utf8Source.IsEmpty)
            {
                Rune result;
                OperationStatus operationStatus = Rune.DecodeFromUtf8(utf8Source, out result, out bytesConsumed2);
                if (operationStatus != 0)
                {
                    if (!isFinalBlock && operationStatus == OperationStatus.NeedMoreData)
                    {
                        result2 = OperationStatus.NeedMoreData;
                        break;
                    }
                }
                else if (!WillEncode(result.Value))
                {
                    uint num = (uint)UnicodeHelpers.GetUtf8RepresentationForScalarValue((uint)result.Value);
                    num2 = 0;
                    while ((uint)num2 < (uint)utf8Destination.Length)
                    {
                        utf8Destination[num2++] = (byte)num;
                        if ((num >>= 8) != 0)
{
                            continue;
                        }
                        goto IL_008d;
                    }
                    goto IL_00f9;
                }
                if (TryEncodeUnicodeScalarUtf8((uint)result.Value, utf16ScratchBuffer, utf8Destination, out var bytesWritten2))
                {
                    utf8Source = utf8Source.Slice(bytesConsumed2);
                    utf8Destination = utf8Destination.Slice(bytesWritten2);
                    continue;
                }
                goto IL_00f9;
            }
            result2 = OperationStatus.Done;
            break;
            IL_008d:
            utf8Source = utf8Source.Slice(bytesConsumed2);
            utf8Destination = utf8Destination.Slice(num2);
            continue;
            IL_00f9:
            result2 = OperationStatus.DestinationTooSmall;
            break;
        }
        bytesConsumed = length - utf8Source.Length;
        bytesWritten = length2 - utf8Destination.Length;
        return result2;
    }
References System.Text.Rune.DecodeFromUtf8(), System.Text.Unicode.UnicodeHelpers.GetUtf8RepresentationForScalarValue(), System.ReadOnlySpan< T >.IsEmpty, System.length, System.ReadOnlySpan< T >.Length, System.Span< T >.Length, System.length2, System.ReadOnlySpan< T >.Slice(), System.Span< T >.Slice(), System.Text.Encodings.Web.TextEncoder.TryEncodeUnicodeScalarUtf8(), System.Text.Rune.Value, and System.Text.Encodings.Web.TextEncoder.WillEncode().
Referenced by System.Text.Encodings.Web.TextEncoder.EncodeUtf8().