Terraria: System.Text.Encodings.Web.TextEncoder.TryEncodeUnicodeScalarUtf8
TryEncodeUnicodeScalarUtf8()
bool System.Text.Encodings.Web.TextEncoder.TryEncodeUnicodeScalarUtf8 (uint unicodeScalar, Span< char > utf16ScratchBuffer, Span< byte > utf8Destination, out int bytesWritten) inline private inherited
Definition at line 29 of file TextEncoder.cs.
    {
        if (!TryEncodeUnicodeScalar(unicodeScalar, utf16ScratchBuffer, out var charsWritten))
        {
            ThrowArgumentException_MaxOutputCharsPerInputChar();
        }
        utf16ScratchBuffer = utf16ScratchBuffer.Slice(0, charsWritten);
        int num = 0;
        while (!utf16ScratchBuffer.IsEmpty)
        {
            if (Rune.DecodeFromUtf16(utf16ScratchBuffer, out var result, out var charsConsumed) != 0)
            {
                ThrowArgumentException_MaxOutputCharsPerInputChar();
            }
            uint num2 = (uint)UnicodeHelpers.GetUtf8RepresentationForScalarValue((uint)result.Value);
            do
            {
                if (SpanUtility.IsValidIndex(utf8Destination, num))
                {
                    utf8Destination[num++] = (byte)num2;
                    continue;
                }
                bytesWritten = 0;
                return false;
            }
            while ((num2 >>= 8) != 0);
            utf16ScratchBuffer = utf16ScratchBuffer.Slice(charsConsumed);
        }
        bytesWritten = num;
        return true;
    }
References System.Text.Rune.DecodeFromUtf16(), System.Text.Unicode.UnicodeHelpers.GetUtf8RepresentationForScalarValue(), System.Span< T >.IsEmpty, System.Span< T >.Slice(), System.Text.Encodings.Web.TextEncoder.ThrowArgumentException_MaxOutputCharsPerInputChar(), and System.Text.Encodings.Web.TextEncoder.TryEncodeUnicodeScalar().
Referenced by System.Text.Encodings.Web.TextEncoder.EncodeUtf8Core().