Terraria: System.Text.Encodings.Web.TextEncoder.EncodeUtf8
EncodeUtf8()
virtual OperationStatus System.Text.Encodings.Web.TextEncoder.EncodeUtf8 (ReadOnlySpan< byte > utf8Source, Span< byte > utf8Destination, out int bytesConsumed, out int bytesWritten, bool isFinalBlock = true) inline virtual inherited
Definition at line 156 of file TextEncoder.cs.
    {
        ReadOnlySpan<byte> utf8Text = utf8Source;
        if (utf8Destination.Length < utf8Source.Length)
        {
            utf8Text = utf8Source.Slice(0, utf8Destination.Length);
        }
        int num = FindFirstCharacterToEncodeUtf8(utf8Text);
        if (num < 0)
        {
            num = utf8Text.Length;
        }
        utf8Source.Slice(0, num).CopyTo(utf8Destination);
        if (num == utf8Source.Length)
        {
            bytesConsumed = utf8Source.Length;
            bytesWritten = utf8Source.Length;
            return OperationStatus.Done;
        }
        int bytesConsumed2;
        int bytesWritten2;
        OperationStatus result = EncodeUtf8Core(utf8Source.Slice(num), utf8Destination.Slice(num), out bytesConsumed2, out bytesWritten2, isFinalBlock);
        bytesConsumed = num + bytesConsumed2;
        bytesWritten = num + bytesWritten2;
        return result;
    }
References System.Text.Encodings.Web.TextEncoder.EncodeUtf8Core(), System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(), System.ReadOnlySpan< T >.Length, System.Span< T >.Length, System.ReadOnlySpan< T >.Slice(), and System.Span< T >.Slice().
Referenced by System.Text.Json.JsonWriterHelper.EscapeString().