Terraria: System.Text.Encodings.Web.TextEncoder.EncodeCore
EncodeCore() [2/2]
void System.Text.Encodings.Web.TextEncoder.EncodeCore (TextWriter output, ReadOnlySpan< char > value) inline private inherited
Definition at line 319 of file TextEncoder.cs.
    {
        int val = Math.Max(MaxOutputCharactersPerInputCharacter, 1024);
        char[] array = ArrayPool<char>.Shared.Rent(Math.Max(value.Length, val));
        Span<char> destination = array;
        do
        {
            EncodeCore(value, destination, out var charsConsumed, out var charsWritten, isFinalBlock: true);
            if (charsWritten == 0 || (uint)charsWritten > (uint)destination.Length)
            {
                ThrowArgumentException_MaxOutputCharsPerInputChar();
            }
            output.Write(array, 0, charsWritten);
            value = value.Slice(charsConsumed);
        }
        while (!value.IsEmpty);
        ArrayPool<char>.Shared.Return(array);
    }
References System.array, System.destination, System.Text.Encodings.Web.TextEncoder.EncodeCore(), System.Math.Max(), System.Text.Encodings.Web.TextEncoder.MaxOutputCharactersPerInputCharacter, System.Buffers.ArrayPool< T >.Shared, System.Text.Encodings.Web.TextEncoder.ThrowArgumentException_MaxOutputCharsPerInputChar(), System.Text.Encodings.Web.value, and System.IO.TextWriter.Write().