Terraria: System.Data.DataRelationCollection.DataTableRelationCollection.GetDataSet
GetDataSet()
override DataSet System.Data.DataRelationCollection.DataTableRelationCollection.GetDataSet () inline protected
Definition at line 74 of file DataRelationCollection.cs.
        {
            EnsureDataSet();
            return _table.DataSet;
        }
References System.Data.DataRelationCollection.DataTableRelationCollection._table, System.Data.DataTable.DataSet, and System.Data.DataRelationCollection.DataTableRelationCollection.EnsureDataSet().
Referenced by System.Data.DataRelationCollection.DataTableRelationCollection.AddCore(), and System.Data.DataRelationCollection.DataTableRelationCollection.RemoveCore().