Terraria: Terraria.Player.Hooks.PlayerDisconnect
PlayerDisconnect()
static void Terraria.Player.Hooks.PlayerDisconnect (int playerIndex) inline static
Definition at line 308 of file Player.cs.
        {
            PressurePlateHelper.ResetPlayer(playerIndex);
        }
References Terraria.GameContent.PressurePlateHelper.ResetPlayer().
Referenced by Terraria.MessageBuffer.GetData(), Terraria.NetMessage.SyncOnePlayer(), and Terraria.Netplay.UpdateConnectedClients().