Terraria: BestiaryDatabaseNPCsPopulator.AddTownNPCs_Manual
AddTownNPCs_Manual()
void BestiaryDatabaseNPCsPopulator.AddTownNPCs_Manual () inline private
     {
         Register(BestiaryEntry.TownNPC(22));
         Register(BestiaryEntry.TownNPC(17));
         Register(BestiaryEntry.TownNPC(18));
         Register(BestiaryEntry.TownNPC(19));
         Register(BestiaryEntry.TownNPC(20));
         Register(BestiaryEntry.TownNPC(37));
         Register(BestiaryEntry.TownNPC(54));
         Register(BestiaryEntry.TownNPC(38));
         Register(BestiaryEntry.TownNPC(107));
         Register(BestiaryEntry.TownNPC(108));
         Register(BestiaryEntry.TownNPC(124));
         Register(BestiaryEntry.TownNPC(142));
         Register(BestiaryEntry.TownNPC(160));
         Register(BestiaryEntry.TownNPC(178));
         Register(BestiaryEntry.TownNPC(207));
         Register(BestiaryEntry.TownNPC(208));
         Register(BestiaryEntry.TownNPC(209));
         Register(BestiaryEntry.TownNPC(227));
         Register(BestiaryEntry.TownNPC(228));
         Register(BestiaryEntry.TownNPC(229));
         Register(BestiaryEntry.TownNPC(353));
         Register(BestiaryEntry.TownNPC(369));
         Register(BestiaryEntry.TownNPC(441));
         Register(BestiaryEntry.TownNPC(550));
         Register(BestiaryEntry.TownNPC(588));
         Register(BestiaryEntry.TownNPC(368));
         Register(BestiaryEntry.TownNPC(453));
         Register(BestiaryEntry.TownNPC(633));
         Register(BestiaryEntry.TownNPC(663));
         Register(BestiaryEntry.TownNPC(638));
         Register(BestiaryEntry.TownNPC(637));
         Register(BestiaryEntry.TownNPC(656));
         Register(BestiaryEntry.TownNPC(670));
         Register(BestiaryEntry.TownNPC(678));
         Register(BestiaryEntry.TownNPC(679));
         Register(BestiaryEntry.TownNPC(680));
         Register(BestiaryEntry.TownNPC(681));
         Register(BestiaryEntry.TownNPC(682));
         Register(BestiaryEntry.TownNPC(683));
         Register(BestiaryEntry.TownNPC(684));
     }
References Register(), and BestiaryEntry.TownNPC().
Referenced by Populate().