Terraria: BestiaryDatabaseNPCsPopulator.RegisterTestEntries
RegisterTestEntries()
void BestiaryDatabaseNPCsPopulator.RegisterTestEntries () inline private
     {
         Register(BestiaryEntry.Biome("Bestiary_Biomes.Hallow", "Images/UI/Bestiary/Biome_Hallow", Conditions.ReachHardMode));
     }
References BestiaryEntry.Biome(), BestiaryDatabaseNPCsPopulator.Conditions.ReachHardMode(), and Register().