Terraria: BestiaryDatabaseNPCsPopulator.TryGivingEntryFlavorTextIfItIsMissing
TryGivingEntryFlavorTextIfItIsMissing()
void BestiaryDatabaseNPCsPopulator.TryGivingEntryFlavorTextIfItIsMissing (BestiaryEntry entry) inline private
     {
         if (entry.Info.Any((IBestiaryInfoElement x) => x is FlavorTextBestiaryInfoElement))
         {
             return;
         }
         SpawnConditionBestiaryInfoElement spawnConditionBestiaryInfoElement = null;
         int? num = null;
         foreach (IBestiaryInfoElement item in entry.Info)
         {
             if (item is BestiaryPortraitBackgroundProviderPreferenceInfoElement bestiaryPortraitBackgroundProviderPreferenceInfoElement && bestiaryPortraitBackgroundProviderPreferenceInfoElement.GetPreferredProvider() is SpawnConditionBestiaryInfoElement spawnConditionBestiaryInfoElement2)
             {
                 spawnConditionBestiaryInfoElement = spawnConditionBestiaryInfoElement2;
                 break;
             }
             if (item is SpawnConditionBestiaryInfoElement { DisplayTextPriority: var displayTextPriority } spawnConditionBestiaryInfoElement3 && (!num.HasValue || displayTextPriority >= num))
             {
                 spawnConditionBestiaryInfoElement = spawnConditionBestiaryInfoElement3;
                 num = displayTextPriority;
             }
         }
         if (spawnConditionBestiaryInfoElement != null)
         {
             string displayNameKey = spawnConditionBestiaryInfoElement.GetDisplayNameKey();
             string text = "Bestiary_BiomeText.biome_";
             string text2 = displayNameKey.Substring(displayNameKey.IndexOf('.') + 1);
             text += text2;
             entry.Info.Add(new FlavorTextBestiaryInfoElement(text));
         }
     }
References FilterProviderInfoElement.GetDisplayNameKey(), BestiaryPortraitBackgroundProviderPreferenceInfoElement.GetPreferredProvider(), and BestiaryEntry.Info.
Referenced by ModifyEntriesThatNeedIt().