Terraria: BestiaryDatabaseNPCsPopulator.AddNPCBiomeRelationships_AddDecorations_Automated
AddNPCBiomeRelationships_AddDecorations_Automated()
void BestiaryDatabaseNPCsPopulator.AddNPCBiomeRelationships_AddDecorations_Automated () inline private
     {
         foreach (KeyValuePair<int, NPC> item in ContentSamples.NpcsByNetId)
         {
             BestiaryEntry bestiaryEntry = FindEntryByNPCID(item.Key);
             if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Events.Rain))
             {
                 if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Biomes.Snow))
                 {
                     bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Blizzard);
                 }
                 else
                 {
                     bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Rain);
                 }
                 continue;
             }
             if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Events.Eclipse))
             {
                 bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.EclipseSun);
             }
             if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Times.NightTime))
             {
                 bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Moon);
             }
             if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Times.DayTime))
             {
                 bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Sun);
             }
             if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Invasions.PumpkinMoon))
             {
                 bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.PumpkinMoon);
             }
             if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Invasions.FrostMoon))
             {
                 bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.FrostMoon);
             }
             if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Biomes.Meteor))
             {
                 bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Moon);
                 bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Meteor);
             }
         }
     }
References BestiaryEntry.AddTags(), BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.Blizzard, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Times.DayTime, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Events.Eclipse, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.EclipseSun, FindEntryByNPCID(), BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Invasions.FrostMoon, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.FrostMoon, BestiaryEntry.Info, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Meteor, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.Meteor, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.Moon, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Times.NightTime, ContentSamples.NpcsByNetId, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Invasions.PumpkinMoon, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.PumpkinMoon, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Events.Rain, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.Rain, BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Snow, and BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.Sun.
Referenced by Populate().