Terraria: Main.DrawInterface_7_TownNPCHouseBanners
DrawInterface_7_TownNPCHouseBanners()
void Main.DrawInterface_7_TownNPCHouseBanners () inline private
     {
         if (EquipPage != 1 && (!UILinkPointNavigator.Shortcuts.NPCS_IconsDisplay || !PlayerInput.UsingGamepad))
         {
             return;
         }
         if (ignoreErrors)
         {
             try
             {
                 DrawNPCHousesInWorld();
                 return;
             }
             catch (Exception e)
             {
                 TimeLogger.DrawException(e);
                 return;
             }
         }
         DrawNPCHousesInWorld();
     }
References TimeLogger.DrawException(), DrawNPCHousesInWorld(), EquipPage, ignoreErrors, UILinkPointNavigator.Shortcuts.NPCS_IconsDisplay, and PlayerInput.UsingGamepad.
Referenced by SetupDrawInterfaceLayers().