Terraria: Main.DrawKite
DrawKite()
void Main.DrawKite (Projectile proj) inline private
     {
         Texture2D value = TextureAssets.Projectile[proj.type].Value;
         Texture2D value2 = TextureAssets.Extra[103].Value;
         int num = 15;
         float num2 = 0f;
         int num3 = 10;
         int num4 = 5;
         float num5 = 10f;
         float num6 = 0f;
         int num7 = -14;
         int num8 = -2;
         int num9 = -1;
         int num10 = -1;
         int num11 = 8;
         int num12 = 0;
         int num13 = 1;
         int num14 = 0;
         int num15 = 0;
         bool flag = true;
         bool flag2 = false;
         switch (proj.type)
         {
         case 771:
             value2 = TextureAssets.Extra[104].Value;
             num = 12;
             num12 = 12;
             num2 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
             num3 = 12;
             num5 = 22f;
             num6 += (float)Math.PI / 8f * (float)proj.spriteDirection;
             num7 = -8;
             num8 = -6;
             num9 = 10;
             num10 = 8;
             num11 = 12;
             break;
         case 822:
             value2 = TextureAssets.Extra[132].Value;
             num = 7;
             num12 = 7;
             num2 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
             num3 = 7;
             num5 = 22f;
             num6 += (float)Math.PI / 12f * (float)proj.spriteDirection;
             num7 = -20;
             num8 = -6;
             num11 = 12;
             break;
         case 850:
             value2 = TextureAssets.Extra[147].Value;
             num = 8;
             num12 = 8;
             num2 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
             num3 = 8;
             num5 = 22f;
             num6 += (float)Math.PI / 12f * (float)proj.spriteDirection;
             num7 = -20;
             num8 = -38;
             num11 = 12;
             num14 = 6;
             num15 = 2;
             flag = false;
             break;
         case 823:
         case 846:
             value2 = TextureAssets.Extra[133].Value;
             if (proj.type == 846)
             {
                 value2 = TextureAssets.Extra[146].Value;
             }
             num = 6;
             num12 = 6;
             num2 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
             num3 = 6;
             num5 = 40f;
             num6 += (float)Math.PI / 12f * (float)proj.spriteDirection;
             num7 = -16;
             num8 = -10;
             num11 = 30;
             break;
         case 827:
         case 844:
             value2 = TextureAssets.Extra[135].Value;
             if (proj.type == 844)
             {
                 value2 = TextureAssets.Extra[144].Value;
             }
             num = 4;
             num12 = 3;
             num2 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
             num3 = 16;
             num5 = 10f;
             num6 += (float)Math.PI / 12f * (float)proj.spriteDirection;
             num8 = -4;
             num4 = 4;
             flag2 = true;
             break;
         case 828:
         case 829:
             value2 = TextureAssets.Extra[136].Value;
             if (proj.type == 829)
             {
                 value2 = TextureAssets.Extra[137].Value;
             }
             num = 2;
             num12 = 1;
             num2 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
             num3 = 6;
             num5 = 10f;
             num6 += (float)Math.PI / 12f * (float)proj.spriteDirection;
             num11 = 10;
             num8 = -4;
             num13 = 3;
             flag = false;
             flag2 = true;
             break;
         case 852:
             value2 = TextureAssets.Extra[148].Value;
             num = 2;
             num12 = 1;
             num2 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
             num3 = 6;
             num5 = 10f;
             num6 += (float)Math.PI / 12f * (float)proj.spriteDirection;
             num11 = 10;
             num8 = -4;
             num13 = 4;
             flag = false;
             flag2 = true;
             break;
         case 830:
         case 838:
             value2 = TextureAssets.Extra[138].Value;
             if (proj.type == 838)
             {
                 value2 = TextureAssets.Extra[139].Value;
             }
             num = 3;
             num12 = 3;
             num2 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
             num3 = 3;
             num5 = 60f;
             num10 = 40;
             num9 = 3;
             num6 += (float)Math.PI / 12f * (float)proj.spriteDirection;
             num11 = 50;
             num8 = -20;
             num14 = -10;
             break;
         case 843:
             value2 = TextureAssets.Extra[140].Value;
             num = 2;
             num12 = 2;
             num2 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
             num3 = 2;
             num5 = 30f;
             num6 += (float)Math.PI / 12f * (float)proj.spriteDirection;
             num11 = 20;
             num8 = -16;
             num14 = -10;
             break;
         case 845:
             value2 = TextureAssets.Extra[145].Value;
             num = 3;
             num12 = 3;
             num2 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
             num3 = 3;
             num5 = 42f;
             num10 = 50;
             num9 = 2;
             num6 += (float)Math.PI / 12f * (float)proj.spriteDirection;
             num11 = 30;
             num8 = -8;
             num14 = -10;
             break;
         case 824:
         case 826:
         case 839:
         case 840:
         case 853:
             num13 = 0;
             break;
         case 766:
         case 767:
         case 768:
         case 769:
         case 770:
             num12 = (proj.type - 766) * 3 + 3;
             break;
         }
         SpriteEffects effects = ((proj.spriteDirection != 1) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
         Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(projFrames[proj.type], 1, proj.frame);
         Vector2 origin = rectangle.Size() / 2f;
         Vector2 position = proj.Center - screenPosition;
         Microsoft.Xna.Framework.Color color = Lighting.GetColor(proj.Center.ToTileCoordinates());
         Microsoft.Xna.Framework.Color alpha = proj.GetAlpha(color);
         Texture2D value3 = TextureAssets.FishingLine.Value;
         Microsoft.Xna.Framework.Rectangle value4 = value3.Frame();
         Vector2 origin2 = new Vector2(value4.Width / 2, 2f);
         Microsoft.Xna.Framework.Rectangle rectangle2 = value2.Frame(num);
         int width = rectangle2.Width;
         rectangle2.Width -= 2;
         Vector2 origin3 = rectangle2.Size() / 2f;
         rectangle2.X = width * (num - 1);
         Vector2 playerArmPosition = GetPlayerArmPosition(proj);
         Vector2 center = proj.Center;
         Vector2.Distance(center, playerArmPosition);
         float num16 = 12f;
         _ = (playerArmPosition - center).SafeNormalize(Vector2.Zero) * num16;
         Vector2 vector = playerArmPosition;
         Vector2 vector2 = center - vector;
         Vector2 velocity = proj.velocity;
         if (Math.Abs(velocity.X) > Math.Abs(velocity.Y))
         {
             Utils.Swap(ref velocity.X, ref velocity.Y);
         }
         float num17 = vector2.Length();
         float num18 = 16f;
         float num19 = 80f;
         bool flag3 = true;
         if (num17 == 0f)
         {
             flag3 = false;
         }
         else
         {
             vector2 *= 12f / num17;
             vector -= vector2;
             vector2 = center - vector;
         }
         while (flag3)
         {
             float num20 = 12f;
             float num21 = vector2.Length();
             float num22 = num21;
             if (float.IsNaN(num21) || num21 == 0f)
             {
                 flag3 = false;
                 continue;
             }
             if (num21 < 20f)
             {
                 num20 = num21 - 8f;
                 flag3 = false;
             }
             num21 = 12f / num21;
             vector2 *= num21;
             vector += vector2;
             vector2 = center - vector;
             if (num22 > 12f)
             {
                 float num23 = 0.3f;
                 float num24 = Math.Abs(velocity.X) + Math.Abs(velocity.Y);
                 if (num24 > num18)
                 {
                     num24 = num18;
                 }
                 num24 = 1f - num24 / num18;
                 num23 *= num24;
                 num24 = num22 / num19;
                 if (num24 > 1f)
                 {
                     num24 = 1f;
                 }
                 num23 *= num24;
                 if (num23 < 0f)
                 {
                     num23 = 0f;
                 }
                 num24 = 1f;
                 num23 *= num24;
                 if (vector2.Y > 0f)
                 {
                     vector2.Y *= 1f + num23;
                     vector2.X *= 1f - num23;
                 }
                 else
                 {
                     num24 = Math.Abs(velocity.X) / 3f;
                     if (num24 > 1f)
                     {
                         num24 = 1f;
                     }
                     num24 -= 0.5f;
                     num23 *= num24;
                     if (num23 > 0f)
                     {
                         num23 *= 2f;
                     }
                     vector2.Y *= 1f + num23;
                     vector2.X *= 1f - num23;
                 }
             }
             float rotation = vector2.ToRotation() - (float)Math.PI / 2f;
             if (!flag3)
             {
                 value4.Height = (int)num20;
             }
             Microsoft.Xna.Framework.Color color2 = Lighting.GetColor(center.ToTileCoordinates());
             EntitySpriteDraw(value3, vector - screenPosition, value4, color2, rotation, origin2, 1f, SpriteEffects.None);
         }
         Vector2 vector3 = proj.Size / 2f;
         float num25 = Math.Abs(WindForVisuals);
         float num26 = MathHelper.Lerp(0.5f, 1f, num25);
         float num27 = num25;
         if (vector2.Y >= -0.02f && vector2.Y < 1f)
         {
             num27 = Utils.GetLerpValue(0.2f, 0.5f, num25, clamped: true);
         }
         int num28 = num4;
         int num29 = num3 + 1;
         for (int i = 0; i < num13; i++)
         {
             rectangle2.X = width * (num - 1);
             List<Vector2> list = new List<Vector2>();
             Vector2 vector4 = new Vector2(num26 * (float)num11 * (float)proj.spriteDirection, (float)Math.Sin(timeForVisualEffects / 300.0 * 6.2831854820251465) * num27) * 2f;
             float num30 = num7 + num14;
             float num31 = num8 + num15;
             switch (i)
             {
             case 1:
                 vector4 = new Vector2(num26 * (float)num11 * (float)proj.spriteDirection, (float)Math.Sin(timeForVisualEffects / 300.0 * 6.2831854820251465) * num27 + 0.5f) * 2f;
                 num30 -= 8f;
                 num31 -= 8f;
                 break;
             case 2:
                 vector4 = new Vector2(num26 * (float)num11 * (float)proj.spriteDirection, (float)Math.Sin(timeForVisualEffects / 300.0 * 6.2831854820251465) * num27 + 1f) * 2f;
                 num30 -= 4f;
                 num31 -= 4f;
                 break;
             case 3:
                 vector4 = new Vector2(num26 * (float)num11 * (float)proj.spriteDirection, (float)Math.Sin(timeForVisualEffects / 300.0 * 6.2831854820251465) * num27 + 1.5f) * 2f;
                 num30 -= 12f;
                 num31 -= 12f;
                 break;
             }
             Vector2 vector5 = proj.Center + new Vector2(((float)rectangle.Width * 0.5f + num30) * (float)proj.spriteDirection, num31).RotatedBy(proj.rotation + num6);
             list.Add(vector5);
             int num32 = num28;
             int num33 = 1;
             while (num32 < num29 * num28)
             {
                 if (num9 != -1 && num9 == num33)
                 {
                     num5 = num10;
                 }
                 Vector2 vector6 = proj.oldPos[num32];
                 if (vector6.X == 0f && vector6.Y == 0f)
                 {
                     list.Add(vector5);
                 }
                 else
                 {
                     vector6 += vector3 + new Vector2(((float)rectangle.Width * 0.5f + num30) * (float)proj.oldSpriteDirection[num32], num31).RotatedBy(proj.oldRot[num32] + num6);
                     vector6 += vector4 * (num33 + 1);
                     Vector2 vector7 = vector5 - vector6;
                     float num34 = vector7.Length();
                     if (num34 > num5)
                     {
                         vector7 *= num5 / num34;
                     }
                     vector6 = vector5 - vector7;
                     list.Add(vector6);
                     vector5 = vector6;
                 }
                 num32 += num28;
                 num33++;
             }
             if (flag)
             {
                 Microsoft.Xna.Framework.Rectangle value5 = value3.Frame();
                 for (int num35 = list.Count - 2; num35 >= 0; num35--)
                 {
                     Vector2 vector8 = list[num35];
                     Vector2 v = list[num35 + 1] - vector8;
                     float num36 = v.Length();
                     if (!(num36 < 2f))
                     {
                         float rotation2 = v.ToRotation() - (float)Math.PI / 2f;
                         EntitySpriteDraw(value3, vector8 - screenPosition, value5, alpha, rotation2, origin2, new Vector2(1f, num36 / (float)value5.Height), SpriteEffects.None);
                     }
                 }
             }
             for (int num37 = list.Count - 2; num37 >= 0; num37--)
             {
                 Vector2 vector9 = list[num37];
                 Vector2 vector10 = list[num37 + 1];
                 Vector2 v2 = vector10 - vector9;
                 v2.Length();
                 float rotation3 = v2.ToRotation() - (float)Math.PI / 2f + num2;
                 EntitySpriteDraw(value2, vector10 - screenPosition, rectangle2, alpha, rotation3, origin3, proj.scale, effects);
                 rectangle2.X -= width;
                 if (rectangle2.X < 0)
                 {
                     int num38 = num12;
                     if (flag2)
                     {
                         num38--;
                     }
                     rectangle2.X = num38 * width;
                 }
             }
         }
         EntitySpriteDraw(value, position, rectangle, alpha, proj.rotation + num6, origin, proj.scale, effects);
     }
References Entity.Center, EntitySpriteDraw(), TextureAssets.Extra, TextureAssets.FishingLine, Projectile.frame, Projectile.GetAlpha(), Lighting.GetColor(), Utils.GetLerpValue(), GetPlayerArmPosition(), Projectile.oldPos, Projectile.oldRot, Projectile.oldSpriteDirection, TextureAssets.Projectile, projFrames, Projectile.rotation, Projectile.scale, screenPosition, Entity.Size, Projectile.spriteDirection, timeForVisualEffects, Utils.ToRotation(), Projectile.type, Asset< T >.Value, Entity.velocity, and WindForVisuals.
Referenced by DrawProjDirect().