Terraria: Main.OpenShop
OpenShop()
void Main.OpenShop (int shopIndex) inline private
     {
         playerInventory = true;
         stackSplit = 9999;
         npcChatText = "";
         SetNPCShopIndex(shopIndex);
         shop[npcShop].SetupShop(npcShop);
         SoundEngine.PlaySound(12);
     }
References npcChatText, npcShop, playerInventory, SoundEngine.PlaySound(), SetNPCShopIndex(), Chest.SetupShop(), shop, and stackSplit.
Referenced by GUIChatDrawInner().