Terraria: Main.AnimateTiles
AnimateTiles()
static void Main.AnimateTiles () inline static private
     {
         tileFrameCounter[12]++;
         if (tileFrameCounter[12] > 5)
         {
             tileFrameCounter[12] = 0;
             tileFrame[12]++;
             if (tileFrame[12] >= 10)
             {
                 tileFrame[12] = 0;
             }
         }
         tileFrameCounter[665] = tileFrameCounter[12];
         tileFrame[665] = tileFrame[12];
         tileFrameCounter[639]++;
         if (tileFrameCounter[639] > 5)
         {
             tileFrameCounter[639] = 0;
             tileFrame[639]++;
             if (tileFrame[639] >= 10)
             {
                 tileFrame[639] = 0;
             }
         }
         tileFrameCounter[17]++;
         if (tileFrameCounter[17] > 5)
         {
             tileFrameCounter[17] = 0;
             tileFrame[17]++;
             if (tileFrame[17] >= 12)
             {
                 tileFrame[17] = 0;
             }
         }
         if (++tileFrameCounter[133] >= 4)
         {
             tileFrameCounter[133] = 0;
             if (++tileFrame[133] >= 6)
             {
                 tileFrame[133] = 0;
             }
         }
         tileFrameCounter[31]++;
         if (tileFrameCounter[31] > 10)
         {
             tileFrameCounter[31] = 0;
             tileFrame[31]++;
             if (tileFrame[31] > 1)
             {
                 tileFrame[31] = 0;
             }
         }
         tileFrameCounter[77]++;
         if (tileFrameCounter[77] > 5)
         {
             tileFrameCounter[77] = 0;
             tileFrame[77]++;
             if (tileFrame[77] >= 12)
             {
                 tileFrame[77] = 0;
             }
         }
         tileFrameCounter[106]++;
         if (tileFrameCounter[106] > 4)
         {
             tileFrameCounter[106] = 0;
             tileFrame[106]++;
             if (tileFrame[106] >= 2)
             {
                 tileFrame[106] = 0;
             }
         }
         tileFrameCounter[207]++;
         if (tileFrameCounter[207] > 4)
         {
             tileFrameCounter[207] = 0;
             tileFrame[207]++;
             if (tileFrame[207] >= 6)
             {
                 tileFrame[207] = 0;
             }
         }
         tileFrameCounter[215]++;
         if (tileFrameCounter[215] >= 4)
         {
             tileFrameCounter[215] = 0;
             tileFrame[215]++;
             if (tileFrame[215] >= 8)
             {
                 tileFrame[215] = 0;
             }
         }
         tileFrameCounter[592]++;
         if (tileFrameCounter[592] >= 5)
         {
             tileFrameCounter[592] = 0;
             tileFrame[592]++;
             if (tileFrame[592] >= 8)
             {
                 tileFrame[592] = 0;
             }
         }
         tileFrameCounter[217]++;
         if (tileFrameCounter[217] > 4)
         {
             tileFrameCounter[217] = 0;
             tileFrame[217]++;
             if (tileFrame[217] >= 5)
             {
                 tileFrame[217] = 0;
             }
         }
         tileFrameCounter[218]++;
         if (tileFrameCounter[218] > 4)
         {
             tileFrameCounter[218] = 0;
             tileFrame[218]++;
             if (tileFrame[218] >= 2)
             {
                 tileFrame[218] = 0;
             }
         }
         tileFrameCounter[219]++;
         if (tileFrameCounter[219] > 4)
         {
             tileFrameCounter[219] = 0;
             tileFrame[219]++;
             if (tileFrame[219] >= 10)
             {
                 tileFrame[219] = 0;
             }
         }
         tileFrameCounter[642]++;
         if (tileFrameCounter[642] > 4)
         {
             tileFrameCounter[642] = 0;
             tileFrame[642]++;
             if (tileFrame[642] >= 6)
             {
                 tileFrame[642] = 0;
             }
         }
         tileFrameCounter[220]++;
         if (tileFrameCounter[220] > 4)
         {
             tileFrameCounter[220] = 0;
             tileFrame[220]++;
             if (tileFrame[220] >= 4)
             {
                 tileFrame[220] = 0;
             }
         }
         tileFrameCounter[231]++;
         if (tileFrameCounter[231] > 16)
         {
             tileFrameCounter[231] = 0;
             tileFrame[231]++;
             if (tileFrame[231] >= 7)
             {
                 tileFrame[231] = 0;
             }
         }
         tileFrameCounter[235]++;
         if (tileFrameCounter[235] > 20)
         {
             tileFrameCounter[235] = 0;
             tileFrame[235]++;
             if (tileFrame[235] >= 4)
             {
                 tileFrame[235] = 0;
             }
         }
         tileFrameCounter[238]++;
         if (tileFrameCounter[238] > 20)
         {
             tileFrameCounter[238] = 0;
             tileFrame[238]++;
             if (tileFrame[238] >= 4)
             {
                 tileFrame[238] = 0;
             }
         }
         tileFrameCounter[243]++;
         if (tileFrameCounter[243] > 4)
         {
             tileFrameCounter[243] = 0;
             tileFrame[243]++;
             if (tileFrame[243] >= 6)
             {
                 tileFrame[243] = 0;
             }
         }
         tileFrameCounter[244]++;
         if (tileFrameCounter[244] > 4)
         {
             tileFrameCounter[244] = 0;
             tileFrame[244]++;
             if (tileFrame[244] >= 6)
             {
                 tileFrame[244] = 0;
             }
         }
         tileFrameCounter[247]++;
         if (tileFrameCounter[247] > 4)
         {
             tileFrameCounter[247] = 0;
             tileFrame[247]++;
             if (tileFrame[247] > 7)
             {
                 tileFrame[247] = 0;
             }
         }
         tileFrameCounter[96]++;
         if (tileFrameCounter[96] > 4)
         {
             tileFrameCounter[96] = 0;
             tileFrame[96]++;
             if (tileFrame[96] > 3)
             {
                 tileFrame[96] = 0;
             }
         }
         tileFrameCounter[171]++;
         if (tileFrameCounter[171] > 16)
         {
             tileFrameCounter[171] = 0;
             tileFrame[171]++;
             if (tileFrame[171] > 3)
             {
                 tileFrame[171] = 0;
             }
         }
         tileFrameCounter[270]++;
         if (tileFrameCounter[270] > 8)
         {
             tileFrameCounter[270] = 0;
             tileFrame[270]++;
             if (tileFrame[270] > 5)
             {
                 tileFrame[270] = 0;
             }
         }
         int num = tileFrame[270];
         tileFrame[271] = num;
         tileFrame[581] = num;
         tileFrameCounter[660]++;
         if (tileFrameCounter[660] > 8)
         {
             tileFrameCounter[660] = 0;
             tileFrame[660]++;
             if (tileFrame[660] > 4)
             {
                 tileFrame[660] = 0;
             }
         }
         tileFrameCounter[272]++;
         if (tileFrameCounter[272] >= 10)
         {
             tileFrameCounter[272] = 0;
             tileFrame[272]++;
             if (tileFrame[272] > 1)
             {
                 tileFrame[272] = 0;
             }
         }
         tileFrameCounter[300]++;
         if (tileFrameCounter[300] >= 5)
         {
             tileFrameCounter[300] = 0;
             tileFrame[300]++;
             if (tileFrame[300] > 6)
             {
                 tileFrame[300] = 0;
             }
         }
         tileFrameCounter[301]++;
         if (tileFrameCounter[301] >= 5)
         {
             tileFrameCounter[301] = 0;
             tileFrame[301]++;
             if (tileFrame[301] > 7)
             {
                 tileFrame[301] = 0;
             }
         }
         tileFrameCounter[302]++;
         if (tileFrameCounter[302] >= 5)
         {
             tileFrameCounter[302] = 0;
             tileFrame[302]++;
             if (tileFrame[302] > 3)
             {
                 tileFrame[302] = 0;
             }
         }
         tileFrameCounter[303]++;
         if (tileFrameCounter[303] >= 5)
         {
             tileFrameCounter[303] = 0;
             tileFrame[303]++;
             if (tileFrame[303] > 4)
             {
                 tileFrame[303] = 0;
             }
         }
         tileFrameCounter[305]++;
         if (tileFrameCounter[305] >= 5)
         {
             tileFrameCounter[305] = 0;
             tileFrame[305]++;
             if (tileFrame[305] > 11)
             {
                 tileFrame[305] = 0;
             }
         }
         tileFrameCounter[306]++;
         if (tileFrameCounter[306] >= 5)
         {
             tileFrameCounter[306] = 0;
             tileFrame[306]++;
             if (tileFrame[306] > 11)
             {
                 tileFrame[306] = 0;
             }
         }
         tileFrameCounter[307]++;
         if (tileFrameCounter[307] >= 5)
         {
             tileFrameCounter[307] = 0;
             tileFrame[307]++;
             if (tileFrame[307] > 1)
             {
                 tileFrame[307] = 0;
             }
         }
         tileFrameCounter[308]++;
         if (tileFrameCounter[308] >= 5)
         {
             tileFrameCounter[308] = 0;
             tileFrame[308]++;
             if (tileFrame[308] > 7)
             {
                 tileFrame[308] = 0;
             }
         }
         tileFrameCounter[314]++;
         if (tileFrameCounter[314] >= 10)
         {
             tileFrameCounter[314] = 0;
             tileFrame[314]++;
             if (tileFrame[314] > 4)
             {
                 tileFrame[314] = 0;
             }
         }
         tileFrameCounter[326]++;
         if (tileFrameCounter[326] >= 5)
         {
             tileFrameCounter[326] = 0;
             tileFrame[326]++;
             if (tileFrame[326] > 7)
             {
                 tileFrame[326] = 0;
             }
         }
         tileFrameCounter[327]++;
         if (tileFrameCounter[327] >= 10)
         {
             tileFrameCounter[327] = 0;
             tileFrame[327]++;
             if (tileFrame[327] > 7)
             {
                 tileFrame[327] = 0;
             }
         }
         tileFrameCounter[345]++;
         if (tileFrameCounter[345] >= 10)
         {
             tileFrameCounter[345] = 0;
             tileFrame[345]++;
             if (tileFrame[345] > 7)
             {
                 tileFrame[345] = 0;
             }
         }
         tileFrameCounter[458]++;
         if (tileFrameCounter[458] >= 10)
         {
             tileFrameCounter[458] = 0;
             tileFrame[458]++;
             if (tileFrame[458] > 7)
             {
                 tileFrame[458] = 0;
             }
         }
         tileFrameCounter[459]++;
         if (tileFrameCounter[459] >= 10)
         {
             tileFrameCounter[459] = 0;
             tileFrame[459]++;
             if (tileFrame[459] > 7)
             {
                 tileFrame[459] = 0;
             }
         }
         tileFrameCounter[336]++;
         if (tileFrameCounter[336] >= 5)
         {
             tileFrameCounter[336] = 0;
             tileFrame[336]++;
             if (tileFrame[336] > 3)
             {
                 tileFrame[336] = 0;
             }
         }
         tileFrameCounter[328]++;
         if (tileFrameCounter[328] >= 5)
         {
             tileFrameCounter[328] = 0;
             tileFrame[328]++;
             if (tileFrame[328] > 7)
             {
                 tileFrame[328] = 0;
             }
         }
         tileFrameCounter[329]++;
         if (tileFrameCounter[329] >= 5)
         {
             tileFrameCounter[329] = 0;
             tileFrame[329]++;
             if (tileFrame[329] > 7)
             {
                 tileFrame[329] = 0;
             }
         }
         int num2 = 20;
         if (++tileFrameCounter[507] >= num2 * 8)
         {
             tileFrameCounter[507] = 0;
         }
         if (++tileFrameCounter[508] >= num2 * 8)
         {
             tileFrameCounter[508] = 0;
         }
         for (int i = 340; i <= 344; i++)
         {
             tileFrameCounter[i]++;
             if (tileFrameCounter[i] >= 5)
             {
                 tileFrameCounter[i] = 0;
                 tileFrame[i]++;
                 if (tileFrame[i] > 3)
                 {
                     tileFrame[i] = 0;
                 }
             }
         }
         tileFrameCounter[351]++;
         if (tileFrameCounter[351] >= 5)
         {
             tileFrameCounter[351] = 0;
             tileFrame[351]++;
             if (tileFrame[351] > 2)
             {
                 tileFrame[351] = 0;
             }
         }
         tileFrameCounter[354]++;
         if (tileFrameCounter[354] >= 5)
         {
             tileFrameCounter[354] = 0;
             tileFrame[354]++;
             if (tileFrame[354] >= 8)
             {
                 tileFrame[354] = 0;
             }
         }
         tileFrame[355] = tileFrame[354];
         tileFrameCounter[377]++;
         if (tileFrameCounter[377] >= 5)
         {
             tileFrameCounter[377] = 0;
             tileFrame[377]++;
             if (tileFrame[377] >= 4)
             {
                 tileFrame[377] = 0;
             }
         }
         tileFrameCounter[379]++;
         if (tileFrameCounter[379] >= 10)
         {
             tileFrameCounter[379] = 0;
             tileFrame[379]++;
             if (tileFrame[379] >= 4)
             {
                 tileFrame[379] = 0;
             }
         }
         if (++tileFrameCounter[390] >= 8)
         {
             tileFrameCounter[390] = 0;
             if (++tileFrame[390] >= 7)
             {
                 tileFrame[390] = 0;
             }
         }
         if (++tileFrameCounter[228] >= 5)
         {
             tileFrameCounter[228] = 0;
             if (++tileFrame[228] >= 3)
             {
                 tileFrame[228] = 0;
             }
         }
         if (++tileFrameCounter[405] >= 5)
         {
             tileFrameCounter[405] = 0;
             if (++tileFrame[405] >= 8)
             {
                 tileFrame[405] = 0;
             }
         }
         if (++tileFrameCounter[406] >= 8)
         {
             tileFrameCounter[406] = 0;
             if (++tileFrame[406] >= 6)
             {
                 tileFrame[406] = 0;
             }
         }
         if (++tileFrameCounter[452] >= 5)
         {
             tileFrameCounter[452] = 0;
             if (++tileFrame[452] >= 15)
             {
                 tileFrame[452] = 0;
             }
         }
         if (++tileFrameCounter[455] >= 5)
         {
             tileFrameCounter[455] = 0;
             if (++tileFrame[455] >= 6)
             {
                 tileFrame[455] = 0;
             }
         }
         if (++tileFrameCounter[499] >= 5)
         {
             tileFrameCounter[499] = 0;
             if (++tileFrame[499] >= 8)
             {
                 tileFrame[499] = 0;
             }
         }
         if (++tileFrameCounter[129] >= 8)
         {
             tileFrameCounter[129] = 0;
             if (++tileFrame[129] >= 6)
             {
                 tileFrame[129] = 0;
             }
         }
         tileFrameCounter[453] += ((!WorldGen.gen) ? rand.Next(3) : 0);
         if (++tileFrameCounter[453] >= 60)
         {
             tileFrameCounter[453] = 0;
         }
         if (++tileFrame[412] >= 240)
         {
             tileFrame[412] = 0;
         }
         tileFrameCounter[456] += ((!WorldGen.gen) ? rand.Next(3) : 0);
         if (++tileFrameCounter[456] >= 80)
         {
             tileFrameCounter[456] = 0;
         }
         if (++tileFrame[456] >= 240)
         {
             tileFrame[456] = 0;
         }
         if (++tileFrameCounter[410] >= 8)
         {
             tileFrameCounter[410] = 0;
             if (++tileFrame[410] >= 8)
             {
                 tileFrame[410] = 0;
             }
         }
         if (++tileFrameCounter[480] >= 8)
         {
             tileFrameCounter[480] = 0;
             if (++tileFrame[480] >= 8)
             {
                 tileFrame[480] = 0;
             }
         }
         if (++tileFrameCounter[509] >= 8)
         {
             tileFrameCounter[509] = 0;
             if (++tileFrame[509] >= 8)
             {
                 tileFrame[509] = 0;
             }
         }
         if (++tileFrameCounter[657] >= 8)
         {
             tileFrameCounter[657] = 0;
             if (++tileFrame[657] >= 8)
             {
                 tileFrame[657] = 0;
             }
         }
         if (++tileFrameCounter[658] >= 4)
         {
             tileFrameCounter[658] = 0;
             if (++tileFrame[658] >= 10)
             {
                 tileFrame[658] = 0;
             }
         }
         if (++tileFrameCounter[421] >= 4)
         {
             tileFrameCounter[421] = 0;
             if (++tileFrame[421] >= 4)
             {
                 tileFrame[421] = 0;
             }
         }
         if (++tileFrameCounter[422] >= 4)
         {
             tileFrameCounter[422] = 0;
             if (--tileFrame[422] < 0)
             {
                 tileFrame[422] = 3;
             }
         }
         if (++tileFrameCounter[463] >= 10)
         {
             tileFrameCounter[463] = 0;
             if (++tileFrame[463] >= 6)
             {
                 tileFrame[463] = 0;
             }
         }
         if (++tileFrameCounter[464] >= 5)
         {
             tileFrameCounter[464] = 0;
             if (++tileFrame[464] >= 23)
             {
                 tileFrame[464] = 0;
             }
         }
         if (++tileFrameCounter[485] >= 20)
         {
             tileFrameCounter[485] = 0;
         }
         if (++tileFrameCounter[491] >= 40)
         {
             tileFrameCounter[491] = 0;
         }
         if (++tileFrameCounter[564] >= 5)
         {
             tileFrameCounter[564] = 0;
             tileFrame[564]++;
             if (tileFrame[564] >= 36)
             {
                 tileFrame[564] = 0;
             }
         }
         if (++tileFrameCounter[593] >= 5)
         {
             tileFrameCounter[593] = 0;
             tileFrame[593]++;
             if (tileFrame[593] >= 9)
             {
                 tileFrame[593] = 5;
             }
         }
         if (++tileFrameCounter[594] >= 5)
         {
             tileFrameCounter[594] = 0;
             tileFrame[594]++;
             if (tileFrame[594] >= 9)
             {
                 tileFrame[594] = 5;
             }
         }
         if (++tileFrameCounter[614] >= 5)
         {
             tileFrameCounter[614] = 0;
             tileFrame[614]++;
             if (tileFrame[614] >= 6)
             {
                 tileFrame[614] = 0;
             }
         }
         if (++tileFrameCounter[565] >= 4)
         {
             tileFrameCounter[565] = 0;
             tileFrame[565]++;
             if (tileFrame[565] >= 5)
             {
                 tileFrame[565] = 0;
             }
         }
         if (++tileFrameCounter[572] >= 6)
         {
             tileFrameCounter[572] = 0;
             if (++tileFrame[572] >= 4)
             {
                 tileFrame[572] = 0;
             }
         }
         if (++tileFrameCounter[597] >= 64)
         {
             tileFrameCounter[597] = 0;
         }
         int num3 = (int)MathHelper.Clamp((float)Math.Floor(Math.Abs(WindForVisuals) * 10f) * (float)Math.Sign(WindForVisuals), -5f, 5f);
         tileFrameCounter[489] += num3;
         tileFrameCounter[489] %= 320;
         if (tileFrameCounter[489] < 0)
         {
             tileFrameCounter[489] += 320;
         }
         AnimateTiles_WeatherVane();
         int num4 = (int)MathHelper.Clamp((float)Math.Floor(Math.Abs(WindForVisuals) * 10f) * (float)Math.Sign(WindForVisuals), -5f, 5f);
         tileFrameCounter[493] += num4;
         tileFrameCounter[493] %= 120;
         if (tileFrameCounter[493] < 0)
         {
             tileFrameCounter[493] += 120;
         }
         AnimateTiles_CritterCages();
     }
References AnimateTiles_CritterCages(), AnimateTiles_WeatherVane(), WorldGen.gen, UnifiedRandom.Next(), rand, tileFrame, tileFrameCounter, and WindForVisuals.
Referenced by DoUpdate().