Terraria: Main.UpdateTimeRate
UpdateTimeRate()
static void Main.UpdateTimeRate () inline static
     {
         if (IsFastForwardingTime())
         {
             dayRate = 60;
             desiredWorldTilesUpdateRate = 1;
             return;
         }
         bool enabled = CreativePowerManager.Instance.GetPower<CreativePowers.FreezeTime>().Enabled;
         int targetTimeRate = CreativePowerManager.Instance.GetPower<CreativePowers.ModifyTimeRate>().TargetTimeRate;
         bool flag = CurrentFrameFlags.SleepingPlayersCount == CurrentFrameFlags.ActivePlayersCount && CurrentFrameFlags.SleepingPlayersCount > 0;
         int num = targetTimeRate;
         if (!gameMenu && flag)
         {
             num *= 5;
         }
         if (enabled)
         {
             num = 0;
         }
         dayRate = num;
         desiredWorldTilesUpdateRate = num;
         if (gameMenu)
         {
             dayRate = 1;
             desiredWorldTilesUpdateRate = 1;
         }
     }
References Main.CurrentFrameFlags.ActivePlayersCount, dayRate, desiredWorldTilesUpdateRate, gameMenu, CreativePowerManager.Instance, IsFastForwardingTime(), and Main.CurrentFrameFlags.SleepingPlayersCount.
Referenced by WorldGen.clearWorld(), MessageBuffer.GetData(), WorldGen.JustQuit(), WorldFile.LoadHeader(), WorldGen.RenameWorldCallBack(), WorldGen.SaveAndQuitCallBack(), UpdateTime(), UpdateTime_StartDay(), and UpdateTime_StartNight().