Terraria: Main.UpdateTime_StartDay
UpdateTime_StartDay()
static void Main.UpdateTime_StartDay (ref bool stopEvents) inline static
     {
         WorldGen.ResetTreeShakes();
         if (fastForwardTimeToDawn)
         {
             fastForwardTimeToDawn = false;
             UpdateTimeRate();
         }
         AnglerQuestSwap();
         BirthdayParty.CheckMorning();
         LanternNight.CheckMorning();
         if (invasionDelay > 0)
         {
             invasionDelay--;
         }
         WorldGen.prioritizedTownNPCType = 0;
         checkForSpawns = 0;
         time = 0.0;
         if (bloodMoon && netMode != 1)
         {
             AchievementsHelper.NotifyProgressionEvent(5);
         }
         bloodMoon = false;
         CheckForMoonEventsScoreDisplay();
         CheckForMoonEventsStartingTemporarySeasons();
         checkXMas();
         checkHalloween();
         stopMoonEvent();
         dayTime = true;
         if (sundialCooldown > 0)
         {
             sundialCooldown--;
         }
         moonPhase++;
         if (moonPhase >= 8)
         {
             moonPhase = 0;
         }
         if (drunkWorld && netMode != 1)
         {
             WorldGen.crimson = !WorldGen.crimson;
         }
         if (netMode == 2)
         {
             NetMessage.SendData(7);
         }
         if (netMode == 1)
         {
             return;
         }
         AchievementsHelper.NotifyProgressionEvent(1);
         if (stopEvents)
         {
             return;
         }
         if (hardMode && NPC.downedMechBossAny && rand.Next(20) == 0)
         {
             sundialCooldown = 0;
             moondialCooldown = 0;
             eclipse = true;
             AchievementsHelper.NotifyProgressionEvent(2);
             if (eclipse)
             {
                 if (remixWorld)
                 {
                     if (netMode == 0)
                     {
                         NewText(Lang.misc[106].Value, 50, byte.MaxValue, 130);
                     }
                     else if (netMode == 2)
                     {
                         ChatHelper.BroadcastChatMessage(Lang.misc[106].ToNetworkText(), new Microsoft.Xna.Framework.Color(50, 255, 130));
                     }
                 }
                 else if (netMode == 0)
                 {
                     NewText(Lang.misc[20].Value, 50, byte.MaxValue, 130);
                 }
                 else if (netMode == 2)
                 {
                     ChatHelper.BroadcastChatMessage(Lang.misc[20].ToNetworkText(), new Microsoft.Xna.Framework.Color(50, 255, 130));
                 }
             }
             if (netMode == 2)
             {
                 NetMessage.SendData(7);
             }
         }
         else
         {
             if (snowMoon || pumpkinMoon || DD2Event.Ongoing)
             {
                 return;
             }
             if (WorldGen.shadowOrbSmashed)
             {
                 if (!NPC.downedGoblins)
                 {
                     if (rand.Next(3) == 0)
                     {
                         StartInvasion();
                     }
                 }
                 else if ((hardMode && rand.Next(60) == 0) || (!hardMode && rand.Next(30) == 0))
                 {
                     StartInvasion();
                 }
             }
             if (invasionType == 0 && hardMode && WorldGen.altarCount > 0 && ((NPC.downedPirates && rand.Next(60) == 0) || (!NPC.downedPirates && rand.Next(30) == 0)))
             {
                 StartInvasion(3);
             }
         }
     }
References WorldGen.altarCount, AnglerQuestSwap(), bloodMoon, ChatHelper.BroadcastChatMessage(), CheckForMoonEventsScoreDisplay(), CheckForMoonEventsStartingTemporarySeasons(), checkForSpawns, checkHalloween(), BirthdayParty.CheckMorning(), LanternNight.CheckMorning(), checkXMas(), WorldGen.crimson, dayTime, NPC.downedGoblins, NPC.downedMechBossAny, NPC.downedPirates, drunkWorld, eclipse, fastForwardTimeToDawn, hardMode, invasionDelay, invasionType, Lang.misc, moondialCooldown, moonPhase, netMode, NewText(), UnifiedRandom.Next(), AchievementsHelper.NotifyProgressionEvent(), DD2Event.Ongoing, WorldGen.prioritizedTownNPCType, pumpkinMoon, rand, remixWorld, WorldGen.ResetTreeShakes(), NetMessage.SendData(), WorldGen.shadowOrbSmashed, snowMoon, StartInvasion(), stopMoonEvent(), sundialCooldown, time, LocalizedText.ToNetworkText(), UpdateTimeRate(), and LocalizedText.Value.
Referenced by SkipToTime(), and UpdateTime().