Terraria: Main.checkXMas
checkXMas()
static void Main.checkXMas () inline static
     {
         DateTime now = DateTime.Now;
         int day = now.Day;
         int month = now.Month;
         if (day >= 15 && month == 12)
         {
             xMas = true;
         }
         else
         {
             xMas = false;
         }
         if (forceXMasForToday)
         {
             xMas = true;
         }
     }
References forceXMasForToday, and xMas.
Referenced by WorldGen.clearWorld(), WorldGen.GenerateWorld(), MessageBuffer.GetData(), WorldGen.Hooks.Initialize(), WorldFile.LoadWorld(), and UpdateTime_StartDay().