Terraria: Main.HandleIME
HandleIME()
void Main.HandleIME () inline
     {
         if (_imeToggle != PlayerInput.WritingText)
         {
             _imeToggle = PlayerInput.WritingText;
             if (_imeToggle)
             {
                 Platform.Get<IImeService>().Enable();
             }
             else
             {
                 Platform.Get<IImeService>().Disable();
             }
         }
     }
References _imeToggle, and PlayerInput.WritingText.
Referenced by DrawMenu(), DrawPlayerChat(), UISearchBar.DrawSelf(), UIVirtualKeyboard.DrawSelf(), and InputTextSign().