Terraria: Main.RenderBackground
RenderBackground()
void Main.RenderBackground () inline protected
     {
         if (drawToScreen)
         {
             return;
         }
         base.GraphicsDevice.SetRenderTarget(backWaterTarget);
         base.GraphicsDevice.Clear(Microsoft.Xna.Framework.Color.Transparent);
         spriteBatch.Begin();
         tileBatch.Begin();
         try
         {
             DrawWaters(isBackground: true);
         }
         catch
         {
         }
         tileBatch.End();
         spriteBatch.End();
         base.GraphicsDevice.SetRenderTarget(null);
         base.GraphicsDevice.SetRenderTarget(backgroundTarget);
         base.GraphicsDevice.Clear(Microsoft.Xna.Framework.Color.Transparent);
         spriteBatch.Begin();
         tileBatch.Begin();
         if (ignoreErrors)
         {
             try
             {
                 DrawBackground();
             }
             catch (Exception e)
             {
                 TimeLogger.DrawException(e);
             }
         }
         else
         {
             DrawBackground();
         }
         TimeLogger.DetailedDrawReset();
         tileBatch.End();
         spriteBatch.End();
         TimeLogger.DetailedDrawTime(33);
         base.GraphicsDevice.SetRenderTarget(null);
     }
References backgroundTarget, backWaterTarget, TileBatch.Begin(), TimeLogger.DetailedDrawReset(), TimeLogger.DetailedDrawTime(), DrawBackground(), TimeLogger.DrawException(), drawToScreen, DrawWaters(), TileBatch.End(), ignoreErrors, spriteBatch, and tileBatch.
Referenced by DoDraw().