Terraria: Main.LoadContent
LoadContent()
override void Main.LoadContent () inline protected virtual
Reimplemented from Game.
     {
         //IL_0039: Unknown result type (might be due to invalid IL or missing references)
         //IL_0043: Expected O, but got Unknown
         //IL_0108: Unknown result type (might be due to invalid IL or missing references)
         //IL_0112: Expected O, but got Unknown
         //IL_0167: Unknown result type (might be due to invalid IL or missing references)
         //IL_016d: Expected O, but got Unknown
         SoundEngine.Initialize();
         if (XnaExtensions.Get<IAssetRepository>((IServiceProvider)base.Services) == null)
         {
             AssetInitializer.CreateAssetServices(base.Services);
         }
         Assets = XnaExtensions.Get<IAssetRepository>((IServiceProvider)base.Services);
         Assets.AssetLoadFailHandler = new FailedToLoadAssetCustomAction(OnceFailedLoadingAnAsset);
         mapSectionTexture = new RenderTarget2D(base.GraphicsDevice, 200, 150);
         ShaderContentManager = new ContentManager(base.Content.ServiceProvider, base.Content.RootDirectory);
         PixelShaderRef.Value = ShaderContentManager.Load<Effect>("PixelShader");
         VertexPixelShaderRef.Value = ShaderContentManager.Load<Effect>("PixelShader");
         TileShaderRef.Value = ShaderContentManager.Load<Effect>("TileShader");
         ScreenShaderRef.Value = ShaderContentManager.Load<Effect>("ScreenShader");
         spriteBatch = new SpriteBatch(base.GraphicsDevice);
         tileBatch = new TileBatch(base.GraphicsDevice);
         DebugDrawer = new BasicDebugDrawer(base.GraphicsDevice);
         GameViewMatrix = new SpriteViewMatrix(base.GraphicsDevice);
         BackgroundViewMatrix = new SpriteViewMatrix(base.GraphicsDevice);
         if (SoundEngine.IsAudioSupported)
         {
             audioSystem = new LegacyAudioSystem();
         }
         else
         {
             audioSystem = new DisabledAudioSystem();
         }
         AssetSourceController = new AssetSourceController(Assets, (IEnumerable<IContentSource>)(object)new IContentSource[1] { (IContentSource)new XnaContentSource(base.Content.RootDirectory) });
         VanillaContentValidator.Instance = new VanillaContentValidator("Terraria.IO.Data.ResourcePacksDefaultInfo.tsv");
         if (SocialAPI.Workshop != null)
         {
             SocialAPI.Workshop.LoadEarlyContent();
         }
         AssetSourceController.UseResourcePacks(AssetInitializer.CreateResourcePackList(base.Services));
         AssetInitializer.LoadSplashAssets(asyncLoadForSounds: true);
         ChromaInitializer.Load();
         _gameContentLoadProcess = LoadContent_Deferred();
     }
References _gameContentLoadProcess, IAssetRepository.AssetLoadFailHandler, Assets, AssetSourceController, audioSystem, BackgroundViewMatrix, AssetInitializer.CreateAssetServices(), AssetInitializer.CreateResourcePackList(), DebugDrawer, FailedToLoadAssetCustomAction(), GameViewMatrix, SoundEngine.Initialize(), VanillaContentValidator.Instance, SoundEngine.IsAudioSupported, ChromaInitializer.Load(), LoadContent_Deferred(), WorkshopSocialModule.LoadEarlyContent(), AssetInitializer.LoadSplashAssets(), mapSectionTexture, OnceFailedLoadingAnAsset(), PixelShaderRef, ScreenShaderRef, ShaderContentManager, spriteBatch, tileBatch, TileShaderRef, AssetSourceController.UseResourcePacks(), Ref< T >.Value, VertexPixelShaderRef, and SocialAPI.Workshop.