Terraria: Main.GUIChatDraw
GUIChatDraw()
void Main.GUIChatDraw () inline
     {
         if (ignoreErrors)
         {
             try
             {
                 if ((npcChatText != "" || player[myPlayer].sign != -1) && !editChest)
                 {
                     GUIChatDrawInner();
                 }
                 return;
             }
             catch (Exception e)
             {
                 TimeLogger.DrawException(e);
                 return;
             }
         }
         if ((npcChatText != "" || player[myPlayer].sign != -1) && !editChest)
         {
             GUIChatDrawInner();
         }
     }
References TimeLogger.DrawException(), editChest, GUIChatDrawInner(), ignoreErrors, myPlayer, npcChatText, player, and sign.
Referenced by IngameFancyUI.Draw(), and DrawInterface_23_NPCSignsDialog().