Terraria: Main.OpenLegacySettings
OpenLegacySettings()
void Main.OpenLegacySettings () inline protected
     {
         try
         {
             if (!File.Exists(SavePath + Path.DirectorySeparatorChar + "config.dat"))
             {
                 return;
             }
             using FileStream input = new FileStream(SavePath + Path.DirectorySeparatorChar + "config.dat", FileMode.Open);
             using BinaryReader binaryReader = new BinaryReader(input);
             int num = binaryReader.ReadInt32();
             if (num >= 68)
             {
                 if (num >= 67)
                 {
                     clientUUID = binaryReader.ReadString();
                 }
                 bool flag = binaryReader.ReadBoolean();
                 mouseColor.R = binaryReader.ReadByte();
                 mouseColor.G = binaryReader.ReadByte();
                 mouseColor.B = binaryReader.ReadByte();
                 soundVolume = binaryReader.ReadSingle();
                 if (num >= 90)
                 {
                     ambientVolume = binaryReader.ReadSingle();
                 }
                 musicVolume = binaryReader.ReadSingle();
                 cUp = binaryReader.ReadString();
                 cDown = binaryReader.ReadString();
                 cLeft = binaryReader.ReadString();
                 cRight = binaryReader.ReadString();
                 cJump = binaryReader.ReadString();
                 cThrowItem = binaryReader.ReadString();
                 if (num >= 1)
                 {
                     cInv = binaryReader.ReadString();
                 }
                 if (num >= 12)
                 {
                     cHeal = binaryReader.ReadString();
                     cMana = binaryReader.ReadString();
                     cBuff = binaryReader.ReadString();
                 }
                 if (num >= 13)
                 {
                     cHook = binaryReader.ReadString();
                 }
                 caveParallax = binaryReader.ReadSingle();
                 if (num >= 2)
                 {
                     terrariasFixedTiming = binaryReader.ReadBoolean();
                 }
                 if (num >= 91 && binaryReader.ReadBoolean() && !dedServ && Platform.IsWindows)
                 {
                     ((Form)Control.FromHandle(base.Window.Handle)).WindowState = FormWindowState.Maximized;
                 }
                 if (num >= 4)
                 {
                     int width = binaryReader.ReadInt32();
                     int height = binaryReader.ReadInt32();
                     SetDisplayMode(width, height, flag);
                 }
                 if (num >= 8)
                 {
                     autoSave = binaryReader.ReadBoolean();
                 }
                 if (num >= 9)
                 {
                     autoPause = binaryReader.ReadBoolean();
                 }
                 if (num >= 19)
                 {
                     showItemText = binaryReader.ReadBoolean();
                 }
                 if (num >= 30)
                 {
                     cTorch = binaryReader.ReadString();
                     Lighting.Mode = (LightMode)binaryReader.ReadByte();
                     qaStyle = binaryReader.ReadByte();
                 }
                 if (num >= 37)
                 {
                     BackgroundEnabled = binaryReader.ReadBoolean();
                 }
                 if (num >= 39)
                 {
                     byte b = binaryReader.ReadByte();
                     _needsLanguageSelect = b == 0;
                     LanguageManager.Instance.SetLanguage(b);
                 }
                 if (num >= 46)
                 {
                     mapEnabled = binaryReader.ReadBoolean();
                     cMapStyle = binaryReader.ReadString();
                     cMapFull = binaryReader.ReadString();
                     cMapZoomIn = binaryReader.ReadString();
                     cMapZoomOut = binaryReader.ReadString();
                     cMapAlphaUp = binaryReader.ReadString();
                     cMapAlphaDown = binaryReader.ReadString();
                 }
                 if (num >= 89)
                 {
                     binaryReader.ReadInt32();
                 }
                 if (num >= 100)
                 {
                     cSmart = binaryReader.ReadString();
                     cSmartCursorModeIsToggleAndNotHold = binaryReader.ReadBoolean();
                 }
                 if (num >= 107)
                 {
                     invasionProgressMode = binaryReader.ReadByte();
                 }
                 if (num >= 111)
                 {
                     placementPreview = binaryReader.ReadBoolean();
                 }
                 if (num >= 111)
                 {
                     placementPreview = binaryReader.ReadBoolean();
                 }
                 SetFullScreen(flag);
             }
             binaryReader.Close();
         }
         catch
         {
         }
     }
References _needsLanguageSelect, ambientVolume, autoPause, autoSave, BackgroundEnabled, caveParallax, cBuff, cDown, cHeal, cHook, cInv, cJump, cLeft, clientUUID, cMana, cMapAlphaDown, cMapAlphaUp, cMapFull, cMapStyle, cMapZoomIn, cMapZoomOut, cRight, cSmart, cSmartCursorModeIsToggleAndNotHold, cThrowItem, cTorch, cUp, dedServ, LanguageManager.Instance, invasionProgressMode, Platform.IsWindows, mapEnabled, Lighting.Mode, mouseColor, musicVolume, placementPreview, qaStyle, SavePath, SetDisplayMode(), SetFullScreen(), LanguageManager.SetLanguage(), showItemText, soundVolume, and terrariasFixedTiming.
Referenced by LoadSettings().