Terraria: Main.SetupDrawInterfaceLayers
SetupDrawInterfaceLayers()
void Main.SetupDrawInterfaceLayers () inline private
     {
         if (_needToSetupDrawInterfaceLayers)
         {
             _needToSetupDrawInterfaceLayers = false;
             _gameInterfaceLayers = new List<GameInterfaceLayer>();
             _gameInterfaceLayers.AddRange(new GameInterfaceLayer[43]
             {
                 new LegacyGameInterfaceLayer("Vanilla: Interface Logic 1", delegate
                 {
                     DrawInterface_0_InterfaceLogic1();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: MP Player Names", delegate
                 {
                     DrawInterface_20_MultiplayerPlayerNames();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Emote Bubbles", delegate
                 {
                     DrawInterface_1_1_DrawEmoteBubblesInWorld();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Entity Markers", delegate
                 {
                     DrawInterface_1_2_DrawEntityMarkersInWorld();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Smart Cursor Targets", delegate
                 {
                     DrawInterface_2_SmartCursorTargets();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Laser Ruler", delegate
                 {
                     DrawInterface_3_LaserRuler();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Ruler", delegate
                 {
                     DrawInterface_4_Ruler();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Gamepad Lock On", delegate
                 {
                     DrawInterface_5_GamepadLockOn();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Tile Grid Option", delegate
                 {
                     DrawInterface_6_TileGridOption();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Town NPC House Banners", delegate
                 {
                     DrawInterface_7_TownNPCHouseBanners();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Hide UI Toggle", DrawInterface_8_CheckF11UIHideToggle, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Wire Selection", delegate
                 {
                     DrawInterface_9_WireSelection();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Capture Manager Check", DrawInterface_10_CheckCaptureManager),
                 new LegacyGameInterfaceLayer("Vanilla: Ingame Options", DrawInterface_11_IngameOptionsMenu, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Fancy UI", DrawInterface_12_IngameFancyUI, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Achievement Complete Popups", delegate
                 {
                     DrawInterface_13_AchievementCompletePopups();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Entity Health Bars", delegate
                 {
                     DrawInterface_14_EntityHealthBars();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Invasion Progress Bars", delegate
                 {
                     DrawInterface_15_InvasionProgressBars();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Map / Minimap", delegate
                 {
                     DrawInterface_16_MapOrMinimap();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Diagnose Net", delegate
                 {
                     DrawInterface_17_DiagnoseNet();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Diagnose Video", delegate
                 {
                     DrawInterface_18_DiagnoseVideo();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Sign Tile Bubble", delegate
                 {
                     DrawInterface_19_SignTileBubble();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Hair Window", delegate
                 {
                     DrawInterface_21_HairWindow();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Dresser Window", delegate
                 {
                     DrawInterface_22_DresserWindow();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: NPC / Sign Dialog", delegate
                 {
                     DrawInterface_23_NPCSignsDialog();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Interface Logic 2", delegate
                 {
                     DrawInterface_24_InterfaceLogic2();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Resource Bars", delegate
                 {
                     DrawInterface_25_ResourceBars();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Interface Logic 3", delegate
                 {
                     DrawInterface_26_InterfaceLogic3();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Inventory", delegate
                 {
                     DrawInterface_27_Inventory();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Info Accessories Bar", delegate
                 {
                     DrawInterface_28_InfoAccs();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Settings Button", delegate
                 {
                     DrawInterface_29_SettingsButton();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Hotbar", delegate
                 {
                     DrawInterface_30_Hotbar();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Builder Accessories Bar", delegate
                 {
                     DrawInterface_31_BuilderAccToggles();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Radial Hotbars", delegate
                 {
                     DrawInterface_32_GamepadRadialHotbars();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Mouse Text", delegate
                 {
                     DrawInterface_33_MouseText();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Player Chat", delegate
                 {
                     DrawInterface_34_PlayerChat();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Death Text", delegate
                 {
                     DrawInterface_35_YouDied();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Cursor", delegate
                 {
                     DrawInterface_36_Cursor();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Debug Stuff", delegate
                 {
                     DrawInterface_37_DebugStuff();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Mouse Item / NPC Head", delegate
                 {
                     DrawInterface_38_MouseCarriedObject();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Mouse Over", delegate
                 {
                     DrawInterface_39_MouseOver();
                     return true;
                 }),
                 new LegacyGameInterfaceLayer("Vanilla: Interact Item Icon", delegate
                 {
                     DrawInterface_40_InteractItemIcon();
                     return true;
                 }, InterfaceScaleType.UI),
                 new LegacyGameInterfaceLayer("Vanilla: Interface Logic 4", delegate
                 {
                     DrawInterface_41_InterfaceLogic4();
                     return true;
                 }, InterfaceScaleType.UI)
             });
         }
     }
References _gameInterfaceLayers, _needToSetupDrawInterfaceLayers, DrawInterface_0_InterfaceLogic1(), DrawInterface_10_CheckCaptureManager(), DrawInterface_11_IngameOptionsMenu(), DrawInterface_12_IngameFancyUI(), DrawInterface_13_AchievementCompletePopups(), DrawInterface_14_EntityHealthBars(), DrawInterface_15_InvasionProgressBars(), DrawInterface_16_MapOrMinimap(), DrawInterface_17_DiagnoseNet(), DrawInterface_18_DiagnoseVideo(), DrawInterface_19_SignTileBubble(), DrawInterface_1_1_DrawEmoteBubblesInWorld(), DrawInterface_1_2_DrawEntityMarkersInWorld(), DrawInterface_20_MultiplayerPlayerNames(), DrawInterface_21_HairWindow(), DrawInterface_22_DresserWindow(), DrawInterface_23_NPCSignsDialog(), DrawInterface_24_InterfaceLogic2(), DrawInterface_25_ResourceBars(), DrawInterface_26_InterfaceLogic3(), DrawInterface_27_Inventory(), DrawInterface_28_InfoAccs(), DrawInterface_29_SettingsButton(), DrawInterface_2_SmartCursorTargets(), DrawInterface_30_Hotbar(), DrawInterface_31_BuilderAccToggles(), DrawInterface_32_GamepadRadialHotbars(), DrawInterface_33_MouseText(), DrawInterface_34_PlayerChat(), DrawInterface_35_YouDied(), DrawInterface_36_Cursor(), DrawInterface_37_DebugStuff(), DrawInterface_38_MouseCarriedObject(), DrawInterface_39_MouseOver(), DrawInterface_3_LaserRuler(), DrawInterface_40_InteractItemIcon(), DrawInterface_41_InterfaceLogic4(), DrawInterface_4_Ruler(), DrawInterface_5_GamepadLockOn(), DrawInterface_6_TileGridOption(), DrawInterface_7_TownNPCHouseBanners(), DrawInterface_8_CheckF11UIHideToggle(), and DrawInterface_9_WireSelection().
Referenced by DrawInterface().