Terraria: Main.DrawInterface_1_1_DrawEmoteBubblesInWorld
DrawInterface_1_1_DrawEmoteBubblesInWorld()
static void Main.DrawInterface_1_1_DrawEmoteBubblesInWorld () inline static private
     {
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, null, SamplerState.PointClamp, null, null, null, GameViewMatrix.ZoomMatrix);
         EmoteBubble.DrawAll(spriteBatch);
         if (instance.currentNPCShowingChatBubble != -1)
         {
             DrawNPCChatBubble(instance.currentNPCShowingChatBubble);
         }
         instance.currentNPCShowingChatBubble = -1;
     }
References currentNPCShowingChatBubble, EmoteBubble.DrawAll(), DrawNPCChatBubble(), GameViewMatrix, instance, spriteBatch, and SpriteViewMatrix.ZoomMatrix.
Referenced by SetupDrawInterfaceLayers().