Terraria: Main.DrawBuilderAccToggles
DrawBuilderAccToggles()
void Main.DrawBuilderAccToggles (Vector2 start) inline private
     {
         if (!playerInventory)
         {
             return;
         }
         string.IsNullOrEmpty(npcChatText);
         if (false || Main.player[myPlayer].sign >= 0)
         {
             return;
         }
         int num = 0;
         Player player = Main.player[myPlayer];
         int[] builderAccStatus = Main.player[myPlayer].builderAccStatus;
         GetBuilderAccsCountToShow(player, out var blockReplaceIcons, out var torchGodIcons, out var totalDrawnIcons);
         start.Y += 24 * torchGodIcons;
         bool flag = totalDrawnIcons >= 10;
         int num2 = 10;
         for (int i = 0; i < num2; i++)
         {
             int num3 = i - 2;
             switch (i)
             {
             case 0:
                 num3 = 8;
                 break;
             case 1:
                 num3 = 9;
                 break;
             }
             Texture2D value = TextureAssets.BuilderAcc.Value;
             Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(0, 16, 14, 14);
             Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.White;
             Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(127, 127, 127);
             Vector2 vector = start + new Vector2(0f, num * 24);
             if (flag)
             {
                 vector.Y -= 24f;
             }
             bool flag2 = Utils.CenteredRectangle(vector, new Vector2(14f)).Contains(MouseScreen.ToPoint()) && !PlayerInput.IgnoreMouseInterface;
             bool flag3 = flag2 && mouseLeft && mouseLeftRelease;
             switch (num3)
             {
             case 8:
                 if (!player.InfoAccMechShowWires)
                 {
                     continue;
                 }
                 rectangle.X = num3 * 16;
                 color = ((builderAccStatus[num3] == 0) ? color : color2);
                 if (flag2)
                 {
                     player.mouseInterface = true;
                     MouseText((builderAccStatus[num3] == 0) ? Language.GetTextValue("GameUI.WireModeForced") : Language.GetTextValue("GameUI.WireModeNormal"), 0, 0);
                     mouseText = true;
                 }
                 if (flag3)
                 {
                     builderAccStatus[num3] = ((builderAccStatus[num3] == 0) ? 1 : 0);
                     SoundEngine.PlaySound(12);
                     mouseLeftRelease = false;
                 }
                 break;
             case 0:
                 if (!player.rulerLine)
                 {
                     continue;
                 }
                 rectangle.X = num3 * 16;
                 color = ((builderAccStatus[num3] == 0) ? color : color2);
                 if (flag2)
                 {
                     player.mouseInterface = true;
                     MouseText((builderAccStatus[num3] == 0) ? Language.GetTextValue("GameUI.RulerOn") : Language.GetTextValue("GameUI.RulerOff"), 0, 0);
                     mouseText = true;
                 }
                 if (flag3)
                 {
                     builderAccStatus[num3] = ((builderAccStatus[num3] == 0) ? 1 : 0);
                     SoundEngine.PlaySound(12);
                     mouseLeftRelease = false;
                 }
                 break;
             case 1:
                 if (!player.rulerGrid)
                 {
                     continue;
                 }
                 rectangle.X = num3 * 16;
                 color = ((builderAccStatus[num3] == 0) ? color : color2);
                 if (flag2)
                 {
                     player.mouseInterface = true;
                     MouseText((builderAccStatus[num3] == 0) ? Language.GetTextValue("GameUI.MechanicalRulerOn") : Language.GetTextValue("GameUI.MechanicalRulerOff"), 0, 0);
                     mouseText = true;
                 }
                 if (flag3)
                 {
                     builderAccStatus[num3] = ((builderAccStatus[num3] == 0) ? 1 : 0);
                     SoundEngine.PlaySound(12);
                     mouseLeftRelease = false;
                 }
                 break;
             case 3:
                 if (!player.autoPaint)
                 {
                     continue;
                 }
                 rectangle.X = num3 * 16;
                 color = ((builderAccStatus[num3] == 0) ? color : color2);
                 if (flag2)
                 {
                     player.mouseInterface = true;
                     MouseText((builderAccStatus[num3] == 0) ? Language.GetTextValue("GameUI.PaintSprayerOn") : Language.GetTextValue("GameUI.PaintSprayerOff"), 0, 0);
                     mouseText = true;
                 }
                 if (flag3)
                 {
                     builderAccStatus[num3] = ((builderAccStatus[num3] == 0) ? 1 : 0);
                     SoundEngine.PlaySound(12);
                     mouseLeftRelease = false;
                 }
                 break;
             case 2:
                 if (!player.autoActuator)
                 {
                     continue;
                 }
                 rectangle.X = num3 * 16;
                 color = ((builderAccStatus[num3] == 0) ? color : color2);
                 if (flag2)
                 {
                     player.mouseInterface = true;
                     MouseText((builderAccStatus[num3] == 0) ? Language.GetTextValue("GameUI.ActuationDeviceOn") : Language.GetTextValue("GameUI.ActuationDeviceOff"), 0, 0);
                     mouseText = true;
                 }
                 if (flag3)
                 {
                     builderAccStatus[num3] = ((builderAccStatus[num3] == 0) ? 1 : 0);
                     SoundEngine.PlaySound(12);
                     mouseLeftRelease = false;
                 }
                 break;
             case 4:
             case 5:
             case 6:
             case 7:
             case 9:
                 if (!player.InfoAccMechShowWires)
                 {
                     continue;
                 }
                 rectangle.X = num3 * 16;
                 color = ((builderAccStatus[num3] == 0) ? color : ((builderAccStatus[num3] == 1) ? color2 : ((builderAccStatus[num3] == 2) ? color2.MultiplyRGBA(new Microsoft.Xna.Framework.Color(0.66f, 0.66f, 0.66f, 0.66f)) : color2.MultiplyRGBA(new Microsoft.Xna.Framework.Color(0.33f, 0.33f, 0.33f, 0.33f)))));
                 if (flag2)
                 {
                     player.mouseInterface = true;
                     string arg = "";
                     switch (num3)
                     {
                     case 4:
                         arg = Language.GetTextValue("Game.RedWires");
                         break;
                     case 5:
                         arg = Language.GetTextValue("Game.BlueWires");
                         break;
                     case 6:
                         arg = Language.GetTextValue("Game.GreenWires");
                         break;
                     case 7:
                         arg = Language.GetTextValue("Game.YellowWires");
                         break;
                     case 9:
                         arg = Language.GetTextValue("Game.Actuators");
                         break;
                     }
                     string arg2 = "";
                     switch (builderAccStatus[num3])
                     {
                     case 0:
                         arg2 = Language.GetTextValue("GameUI.Bright");
                         break;
                     case 1:
                         arg2 = Language.GetTextValue("GameUI.Normal");
                         break;
                     case 2:
                         arg2 = Language.GetTextValue("GameUI.Faded");
                         break;
                     case 3:
                         arg2 = Language.GetTextValue("GameUI.Hidden");
                         break;
                     }
                     MouseText($"{arg}: {arg2}", 0, 0);
                     mouseText = true;
                 }
                 if (flag3)
                 {
                     builderAccStatus[num3]++;
                     if (builderAccStatus[num3] >= 3)
                     {
                         builderAccStatus[num3] = 0;
                     }
                     SoundEngine.PlaySound(12);
                     mouseLeftRelease = false;
                 }
                 break;
             case 11:
                 continue;
             }
             spriteBatch.Draw(value, vector, rectangle, color, 0f, rectangle.Size() / 2f, 1f, SpriteEffects.None, 0f);
             if (flag2)
             {
                 spriteBatch.Draw(TextureAssets.InfoIcon[13].Value, vector, null, OurFavoriteColor, 0f, TextureAssets.InfoIcon[13].Value.Size() / 2f, 1f, SpriteEffects.None, 0f);
             }
             UILinkPointNavigator.SetPosition(6000 + num + blockReplaceIcons + torchGodIcons, vector + rectangle.Size() * 0.15f);
             num++;
         }
         DrawBlockReplacementIcon(0, 0, flag, 0);
         num++;
         if (player.unlockedBiomeTorches)
         {
             DrawTorchBiomeSwapIcon(0, 0, flag, 1);
             num++;
         }
         UILinkPointNavigator.Shortcuts.BUILDERACCCOUNT = num;
     }
References Player.autoActuator, Player.autoPaint, TextureAssets.BuilderAcc, UILinkPointNavigator.Shortcuts.BUILDERACCCOUNT, Player.builderAccStatus, Utils.CenteredRectangle(), DrawBlockReplacementIcon(), DrawTorchBiomeSwapIcon(), GetBuilderAccsCountToShow(), Language.GetTextValue(), PlayerInput.IgnoreMouseInterface, Player.InfoAccMechShowWires, TextureAssets.InfoIcon, Player.mouseInterface, mouseLeft, mouseLeftRelease, MouseScreen, mouseText, MouseText(), myPlayer, npcChatText, OurFavoriteColor, player, playerInventory, SoundEngine.PlaySound(), Player.rulerGrid, Player.rulerLine, UILinkPointNavigator.SetPosition(), Player.sign, spriteBatch, Player.unlockedBiomeTorches, and Asset< T >.Value.
Referenced by DrawInterface_31_BuilderAccToggles().