Terraria: Main.SelectPlayer
SelectPlayer()
static void Main.SelectPlayer (PlayerFileData data) inline static
     {
         if (_pendingCharacterSelect != null)
         {
             _pendingCharacterSelect(data);
             _pendingCharacterSelect = null;
         }
         else if (menuMultiplayer)
         {
             ServerSideCharacter = false;
             data.SetAsActive();
             SoundEngine.PlaySound(10);
             if (autoJoin)
             {
                 if (Netplay.SetRemoteIP(getIP))
                 {
                     menuMode = 10;
                     Netplay.StartTcpClient();
                 }
                 autoJoin = false;
             }
             else if (menuServer)
             {
                 LoadWorlds();
                 menuMode = 6;
             }
             else
             {
                 menuMode = 13;
                 clrInput();
             }
         }
         else
         {
             ServerSideCharacter = false;
             myPlayer = 0;
             data.SetAsActive();
             player[myPlayer].position = Vector2.Zero;
             LoadWorlds();
             SoundEngine.PlaySound(10);
             menuMode = 6;
         }
     }
References _pendingCharacterSelect, autoJoin, clrInput(), getIP, LoadWorlds(), menuMode, menuMultiplayer, menuServer, myPlayer, player, SoundEngine.PlaySound(), Entity.position, ServerSideCharacter, PlayerFileData.SetAsActive(), Netplay.SetRemoteIP(), and Netplay.StartTcpClient().
Referenced by UICharacterListItem.PlayGame().